### ISSUE TITLE
condition in object key as name is ignore property when property value type T is equal it generic argument

### ISSUE THREAD

**Issue by dcvsling** [microsoft/TypeScript#44768]
# Bug Report

### 🔎 Search Terms

generic type, infer

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/LAKALgngDgpgBAWQPYBMCWAzCA5AhgWxgB4BhAGjgAU4YAPMGAOxQGc4BrGCJDOEgPjgBePgG1KAXRr0mrOAEEATotwQiuRhH6g4uvQH44AAwAkAb2oAyOCzCK0jAOZwAviyNwde3QC5j5qxs7B2cXAB0TIwBuUFBIWDgASUYMGEUAFRhbUkERMy9RKjgHDi4ePjhcNmR0LDxCUgpKQQk-EnEJUBc46HhM2wBGInTcuAAlGABjJEUUIgBySYBXZSYweYoRmJBQDCXGSbA0JEY4frABxJYAcSY0tEnh-gAKQ9o-ZNSMrLBhn6GRvwAJRwfIgXRvAB0y1WjDAJiicAA9EjpLBDmdPOC4FCYYo1ixESi4IwkDQ0GAABZpLqxEB7A5HE5nf5XADKwScrzA7ySKTS5z+gyItnsTn4wNBXlxK3xcIRyNRdHRYCCYuc0p50NlBKJqOmq0OtJ29P2h2Op3Olxud3skyUKjUI25vM+Ap+Qouw1EEglILBEK1eLWCuJBvxRuxMthYEJirRU1V6R9xt2ZqZltZLAdqhdH3532yVvUmh9fqlUaDOvlepxMwjYE1tG1MbjxOVicqpc6IG6JpRAFoh0OGLYAMxwDAzSooFBwKCKJCwRSQSoYBiKYoF4c7noJc5jp7CPlfQXFwFwawTA1zRbV+EbM78bZpxkWtcbt2KJ55lnjp7+k2LZyvCtYdhi6RYoGzbBnCbb6vWiZdEAA)

### 💻 Code

```ts
type ModifyName<C, P extends keyof C> = C[P] extends Array<any>
      ? `${P & string }s` 
      : `${P & string }\$`;

type InferTest<C> = {
  [ P in keyof C as ModifyName<C, P> ]: C[P]
}
type Test1<T> = Record<'current', T>;
```

### 🙁 Actual behavior
```ts
function Test1IsGeneric<T>(ctx: InferTest<Test1<T>>) {
  ctx.current$; // no this property
  ctx.currents; // no either
}
```
i know in this function T is unknown, but it could be T, but in this case, it ignore 'current' property 

### 🙂 Expected behavior
```ts
function Test1IsGeneric<T>(ctx: InferTest<Test1<T>>) {
  ctx.current$; // expect T 
  ctx.currents; // no this property , correct!
}
```
it could be just type T , is it bug or how to write ?

**Comment by andrewbranch** [comment]
Why would you expect it to resolve to `current$`? If `T` is instantiated to an array, it would resolve to the `currents` branch. `ctx` could take either form, so you’re not allowed to access either property.
