### ISSUE TITLE
type of Document.body getter should be nullable

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#44772]
https://github.com/microsoft/TypeScript/blob/3b2bc85594238583b3845e093ed7199483dbf8ee/lib/lib.dom.d.ts#L4453

Before the `body` is ready, the value is `null`.

PR: https://github.com/microsoft/TypeScript/pull/44773

Also, although TypeScript now has ability for a getter to have a different type than a setter, it is still not possible to make the type properly. Based on Chromes behavior this is what describes it:

```ts
class Document {
  get body(): HTMLBodyElement | HTMLFramesetElement | null { ... }
  set body(value: HTMLBodyElement | HTMLFramesetElement) { ... }
}
```

however such a type is not allowed in TS 4.3.

If we follow the deprecation of `HTMLFramesetElement`, which I think is a good idea, then the type would be this:

```ts
class Document {
  get body(): HTMLBodyElement | null { ... }
  set body(value: HTMLBodyElement) { ... }
}
```

but that still doesn't work.

Also, we could ignore the frameset deprecation and just write

```ts
class Document {
  get body(): HTMLElement | null { ... }
  set body(value: HTMLElement) { ... }
}
```

which also doesn't work.

This leads to runtime errors if someone is type-checking a `<script>` tag before `body` is ready.

**Comment by trusktr** [comment]
Here's a trick to make it work:

```ts
class Document2 extends Node {
	// @ts-expect-error
	get body(): HTMLBodyElement | null {
    	return {} as any
	}
	set body(el: HTMLBodyElement) {
	}
}

const b: HTMLBodyElement = new Document2().body // good, getter can return null

new Document2().body = null // good, setter accepts only non-null
```


[playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAiD2wCuBbApgOwC4CZpoA8tMATGAOXhLWgG8AoASAHpnoABLCAWkIAc0wLLwBOI+CKYBzNFmgAjKgE8AFAEoAXNAASAFQCyAGQBCygKIg06bNAA+0DEhAg69aO+iMRspCIx0AX2hIYIwlJgCmCFkFZRU0EC09I1MSJQsrTCw1V0ZIyPpgeAwIOXkkgxNzS2s5AF4HNAB3OERULJx1ADpFNOhWaCl4KgAaQdliEWhgMH9vLF9-R2d6egxm1uRazrUe5WgG5ZcBodHoaKxJ4OBgND4uaGKQJQdi7iP6IA)

**Comment by andrewbranch** [comment]
Are you asking for https://github.com/microsoft/TypeScript/issues/43662 in general, or are you actually asking for the type of `body` to be changed in the DOM lib typings, which incidentally may require something like #43662? The former would be a duplicate, and the latter would be a discussion for https://github.com/microsoft/TypeScript-DOM-lib-generator (but would likely be resolved as “technically correct but the ratio of pain to value is way, way beyond what we would ever consider shipping”).

**Comment by fatcerberus** [comment]
I don't understand why a getter that returns `T | null` is considered incompatible with a setter that takes `T`?  That setup makes perfect sense to me--the thing starts out uninitialized, but you have to provide a valid value the first time you invoke the setter.  I get that the idea is for `foo.x = foo.x` to always work, but that already fails in other cases, e.g. for optional properties under `strictOptionalProperties` (or whatever it's since been renamed to).

**Comment by andrewbranch** [comment]
I’m totally sympathetic to that reasoning and we’ve seen a number of examples from the DOM that can’t be described by today’s variant accessor implementation. I’d encourage both of you to post examples like these in #43662.

**Comment by trusktr** [comment]
@andrewbranch Hello, thanks for the reply. Indeed, I am not asking about #43662, but just noting that the actual type of `document.body` is `HTMLElement | null` when getting, and `HTMLElement` when setting (otherwise runtime error if `null` is passed in).

But related to #43662, as @fatcerberus mentioned, it is not currently possible to denote such a type in TS.

**Comment by trusktr** [comment]
Or, if `@ts-expect-error` is an ok thing to put in the lib definition, that previous workaround I gave would be better. :)

**Comment by andrewbranch** [comment]
Feel free to start a discussion at https://github.com/microsoft/TypeScript-DOM-lib-generator, but I am sticking with my analysis that this would be

> technically correct but the ratio of pain to value is way, way beyond what we would ever consider shipping
