### ISSUE TITLE
A warning should be given when there is a function in the template string

### ISSUE THREAD

**Issue by yuenc** [microsoft/TypeScript#44779]
A warning should be given when there is a function in the template string

var func = () => "foo";
var str = `${func}`; // warn

**Comment by Zzzen** [comment]
This is duplicated.  https://github.com/microsoft/TypeScript/issues/42983

**Comment by yuenc** [comment]
This is duplicated. #42983

**Comment by fadhilx** [comment]
@yuenc  why does issue #4298 marked as duplicate? and also linked to this issue. and the original issue is #16895 , but it was closed (4 years ago). and no implementation. I thought having "[object Object]" in string was a serious issue.
