### ISSUE TITLE
`implement Class` complains about missing #private fields

### ISSUE THREAD

**Issue by 71** [microsoft/TypeScript#44775]
# Bug Report

### 🔎 Search Terms

- `#private`
- `private implements`
- `property missing private`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about common bugs that aren't bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8CwAoa7oGIBmB7X0AvNAAwDcqqG0ADgK4BGIAlsNHrgBQCUi0ATgFMALnX4A7UmWgBfVHJSpQkGACFozALY0QgzYPHCY8ZGgz0mrdvh58hoidACM0hQqA)

### 💻 Code

```ts
class A {
    #foo = 0;

    public foo() { return 0; }
}

class B implements A {
    public foo() { return 1; }
}
```

### 🙁 Actual behavior

```
Class 'B' incorrectly implements class 'A'. Did you mean to extend 'A' and inherit its members as a subclass?
  Property '#foo' is missing in type 'B' but required in type 'A'.
```

### 🙂 Expected behavior

As `#foo` is hard-private, I expected it to be ignored from the check.

I'm not 100% sure about this behavior though. It might be intended that `#foo` is considered in this check, though I believe that it shouldn't since there is no way to build an object that `implements A` when `A` has `#`-private fields.

### Workaround

This workaround also works for regular `private` fields, so the result is not exactly the same.

```diff
class A {
    #foo = 0;

    public foo() { return 0; }
}

- class B implements A {
+ class B implements Pick<A, keyof A> {
    public foo() { return 1; }
}
```

### Fix

I fixed this issue and have a PR ready to go. I do want to make sure that behavior is unexpected before submitting the PR for review, though.

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/471

**Comment by MartinJohns** [comment]
Duplicate of #42660. Used search terms: `class implements private`

**Comment by 71** [comment]
@whzx5byb I'm actually wondering whether `private` and `#` should have the same semantics here. #471 doesn't touch that subject. I understand _why_ that limitation is here to start with; I'm wondering whether it makes sense to keep it when the runtime ensures that there can be no access to the private `#foo`.

**Comment by 71** [comment]
@MartinJohns Ah, indeed. Thanks for the pointer. Too bad I didn't see it.
