### ISSUE TITLE
tsc --help is unreadable or hard to read in Windows default themes

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#44798]
I decided to try out the new `tsc --help` in 4.4, but unfortunately noticed some contrast issues on Windows.

Using Command Prompt, the blue text has low contrast (2.38 contrast ratio). It starts to blur for me.

![image](https://user-images.githubusercontent.com/972891/123743357-f512a800-d861-11eb-8903-ce7223050522.png)

Even worse, using PowerShell the blue text is unreadable.

![image](https://user-images.githubusercontent.com/972891/123743284-d57b7f80-d861-11eb-84e1-cd0252241676.png)

This is really unfortunate - on other terminal themes, this seems to be a really nice touch, but it doesn't work well here.

**Comment by orta** [comment]
I have a WIP branch for this laying around
