### ISSUE TITLE
Find references/get occurrences on 'this' doesn't work in class expressions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4479]
```TypeScript
var x = class C {
    public x;
    public y;
    public z;
    constructor() {
        [|this|].x;
        [|this|].y;
        [|this|].z;
    }
    foo() {
        return [|this|].x;
    }
}
```

All the above spans should find the same references.

Issue is caused by `getThisReferencesInFile` in `services.ts`.

**Comment by DickvdBrink** [comment]
Hi @DanielRosenwasser, is this something that is up for grabs or you want to do this yourself?

**Comment by mhegazy** [comment]
@DickvdBrink feel free to send a PR
