### ISSUE TITLE
AsyncGenerator doesn't play nicely with TNext = Promise<...>

### ISSUE THREAD

**Issue by magiblot** [microsoft/TypeScript#44808]
# Bug Report

### 🔎 Search Terms

AsyncGenerator Promise TNext

### 🕗 Version & Regression Information

Can reproduce in Version 4.4.0-dev (5cea46c5376f244980207eff22436742e27417cc).

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "async", "generator" and "promise".

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0#code/C4TwDgpgBAShDOBXANsKBeKBvAtg+AhgOYQBcU8wATgJYB2RAvgFDMHwh0DGUAZot2A0A9nSgAqQgDcIVAOIQ6ACgCU5AIIduCurILBhVADxThNACYAaKKYvWAClWE4a8CEbhJUAPigAfKAFzCF56CHNfLGYoGKhkCDRIOnN6InJHZ1d3TxRgbwBtAF0MKCKAbmjYgHcACxp4qCVqRAgVbErY2K5RSigwEpAaCGRzCs7Oml5G-oBCTDoUZBUO8c6klIYAOjBEeBqlMBUx1ahJ6Yx5xbaok-Huul6qBFz4EoIqgho0DJc3TYJkMgDooNkQjitbutUiVyhCTvd4MJ4ptkMIiEoAOQAZQMtC2m02GPBt0670+aEohggOVQ8CUTy8wHgxJOLE6LBYzH4ghEYkpTxpTPpz1p5EFRWuKwRSIgKLRwsZzOOMSewEQVDEPyymwZSJkqgqnPYnB43K4QlEUC4T30ECxBBkVFU7U6CIpDtkJWksh0BpWZK+FA9VE2ugAHsA-Z1Veq+cHDawlMbuHwBObec6bl0eu7HW8PoHrRBbfbHVHYt6Q+HI1q-rrkPrcPhiGQoAAiACMbcYKhZMUroYgEaUtdl9cbeHghBI5DbACZu73lUHHYPh6OdQg9RAlE2py3ZwBmRd9leyNeR8E9g1AA)

### 💻 Code

```ts
type Result = {message: string}

async function *saverGen(): AsyncGenerator<void, void, Promise<Result> | undefined> {
    let pending: Promise<Result>[] = [];
    while (true) {
        const p = yield;
        if (p != null)
            pending.push(p);
        else {
            const results = await Promise.all(pending);
            pending = [];
            console.log('Storing...');
            await storeResults(results);
        }
    }
}

function storeResults(results: Result[]) {
    console.log(results);
    return Promise.resolve();
}
```

### 🙁 Actual behavior

`tsc` fails to compile the code above because of the `Promise<Result> | undefined` type of the generator's `next()`'s parameter.

```
../../home/magiblot/tvision/tv3/bug.ts:3:29 - error TS2322: Type 'AsyncGenerator<void, void, Result>' is not assignable to type 'AsyncGenerator<void, void, Promise<Result>>'.
  Types of property 'next' are incompatible.
    Type '(...args: [] | [Result]) => Promise<IteratorResult<void, void>>' is not assignable to type '(...args: [] | [Promise<Result>]) => Promise<IteratorResult<void, void>>'.
      Types of parameters 'args' and 'args' are incompatible.
        Type '[] | [Promise<Result>]' is not assignable to type '[] | [Result]'.
          Type '[Promise<Result>]' is not assignable to type '[] | [Result]'.
            Type '[Promise<Result>]' is not assignable to type '[Result]'.
              Property 'message' is missing in type 'Promise<Result>' but required in type 'Result'.

3 async function *saverGen(): AsyncGenerator<void, void, Promise<Result> | undefined> {
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../../home/magiblot/tvision/tv3/bug.ts:1:16
    1 type Result = {message: string}
                     ~~~~~~~
    'message' is declared here.

Found 1 error.
```

### 🙂 Expected behavior

Replacing `Result` with `any` in the generator signature (`AsyncGenerator<void, void, Promise<any> | undefined>`) makes the error go away. The program then runs as expected, which suggests that the code is valid and the problem lies in the type checking.

The program in the playground link should print the following output:

```
Storing...
[ { result: "1" }, { result: "2" }, { result: "3" } ]
```

**Comment by rbuckton** [comment]
It looks like we are incorrectly calling `getAwaitedType` on the `TNext` type, as calling `next(value)` does not await `value`, per the spec:

- [27.6.1.2 %AsyncGeneratorPrototype%.next ( value )](https://tc39.es/ecma262/#sec-asyncgenerator-prototype-next)
- [27.6.3.7 AsyncGeneratorUnwrapYieldResumption ( resumptionValue )](https://tc39.es/ecma262/#sec-asyncgeneratorunwrapyieldresumption), Step 1
