### ISSUE TITLE
set type of variable in for-in loop

### ISSUE THREAD

**Issue by J-Cake** [microsoft/TypeScript#44803]
# Suggestion

## 🔍 Search Terms

* for in
* type in for in
* set type of for in
* auto in type
* for type
* for in type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In short, my question/suggestion is that `for ... in` expressions should automatically set the type of the variable to keys of the object being iterated.

## 📃 Motivating Example

Here's a snippet from a project I'm working on.
```

const eventsWhichCauseStateChanges = [
    'add-components',
    'delete-components',
    'rotate-component',
    'flip-components',
    'move-component',
    'connect-components',
    'disconnect-components',
    'move-wire-node',
    'add-wire-node',
    'remove-wire-node',
    'import-document',
    'change-label',
    'cut',
    'copy',
    'paste',
] as const;
type val = typeof eventsWhichCauseStateChanges[number];

const burst: Record<val, boolean> = {
    'add-components': false,
    'delete-components': false,
    'rotate-component': false,
    'flip-components': false,
    'move-component': false,
    'connect-components': false,
    'disconnect-components': false,
    'move-wire-node': false,
    'add-wire-node': false,
    'remove-wire-node': false,
    'import-document': false,
    'change-label': false,
    'cut': false,
    'copy': false,
    'paste': false,
};

for (const i in burst)
    console.log(burst[i as keyof typeof burst]);
```

## 💻 Use Cases

Notice that on the last line, I must explicitely state the type of `i`. I think that should be obvious. Considering we're iterating over `burst`. The way it is at the moment, `i` has a type of `string`. Which is of course entirely true, but in my opinion, not as specific as it can be.

**Comment by MartinJohns** [comment]
See #44706, #44535, #35847, etc.
