### ISSUE TITLE
tsconfig validation doesn't know latest libs - update JSON Schema

### ISSUE THREAD

**Issue by jrieken** [microsoft/TypeScript#44807]
re https://github.com/microsoft/vscode/issues/121144

* in `src/tsconfig.base.json` of our repo
* some libs get a warning about not being known but that's wrong

**Comment by mjbvz** [comment]
Specific values are:

```
			"ES2020.Intl",
			"ES2021.Promise",
			"ES2021.String",
			"ES2021.Weakref",
```

**Comment by andrewbranch** [comment]
We need to figure out what else we’ve missed in the last release or two and update https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json (and the jsconfig one too)

**Comment by orta** [comment]
👍🏻 - the website generates the schemas now, so I'll ship an update to the schema store with 4.4b

**Comment by orta** [comment]
This has an upstream PR now

**Comment by orta** [comment]
This is in
