### ISSUE TITLE
Typescript can not recognize when expression is callable

### ISSUE THREAD

**Issue by ZhenyaUsenko** [microsoft/TypeScript#44817]
# Bug Report

![image](https://user-images.githubusercontent.com/76219110/123869025-2316eb80-d939-11eb-92ca-6b18e74643f1.png)

Quick fix

![image](https://user-images.githubusercontent.com/76219110/123869469-b7814e00-d939-11eb-87d1-88c36add510f.png)

### 🔎 Search Terms

Not all constituents of type are callable.

### 💻 Code

```ts
const getValue = <V>(value: V | (() => V)) =>
  typeof value === "function" ? value() : value;
```

### 🙁 Actual behavior

Error occurred

### 🙂 Expected behavior

Typescript should understand that expression is callable

**Comment by MartinJohns** [comment]
It would still not be safe, because `V` can be a function type.

**Comment by ZhenyaUsenko** [comment]
Yes, it can, but when ```typeof value === "function"``` returns ```true``` we are 100% sure ```value``` is callable

**Comment by MartinJohns** [comment]
But you are **not** sure if it's callable without any arguments. `T` can be of the type `(arg: number) => void` as well.
