### ISSUE TITLE
Navigate-to does not pick up any identifiers in class expression

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4481]
```TypeScript
var ffffffffffff = class Pnsndltn {
    public raggafragga;
}
```

Try searching for any of the identifiers in the above with navigate-to.

Expected: All of them are found.
Actual: Only `ffffffffffff` is found.

Probable cause: `computeNamedDeclarations` doesn't account for `ClassExpression` kinds.

**Comment by DanielRosenwasser** [comment]
Should this work for function expressions too? @mhegazy @CyrusNajmabadi

**Comment by mhegazy** [comment]
We chose to not include functions in the past, just to avoid polluting the list. I think class expressions are different enough; I woul not mind trying the experience with function expressions as well.

**Comment by scarlac** [comment]
@mhegazy While this was fixed for classes, I have an existing code base with a *lot* of modules written in the style of:
```
module.exports = function() {
  const methods = {};
  methods.myFirstFunction = function() { /* ... */ };
  methods.mySecondFunction = function() { /* ... */ };
  return methods;
}
```
What is counter-intuitive (by VSCode's own standard) is that it'll show these functions through "Goto Symbol in File" while "Goto Symbol in Workspace" will not show it. This discrepancy is very confusing and does not make sense. Anecdotally, Sublime does this and I have no issue using it - I never scroll through the list, just like I don't scroll through the list when using the command palette. I understand the argument that it may pollute, although I cannot confirm that I agree as I haven't seen it enabled, but the UX experience is really bad. It comes off as a bug.

Is there any way we could improve the experience or have it as a configuration setting?

**Comment by CyrusNajmabadi** [comment]
@scarlac That looks like an entirely different issue.  I would recommend creating a new bug to track this.

**Comment by scarlac** [comment]
@CyrusNajmabadi, I followed issues for that to this ticket. The others were closed with a reference to this one. Should I still create a new one?

**Comment by mhegazy** [comment]
The underlying issue is that the type system does not understand ` methods.myFirstFunction = function() { /* ... */ };` as a declaration of a new property `myFirstFunction` on `methods`. 

see https://github.com/Microsoft/TypeScript/issues/7632, https://github.com/Microsoft/TypeScript/issues/9474, https://github.com/Microsoft/TypeScript/issues/10868 and https://github.com/Microsoft/TypeScript/issues/15868

**Comment by scarlac** [comment]
@mhegazy That sounds odd as it works when using "Goto symbol in File". Was a specific workaround implemented to make it work there and not in the workspace?

**Comment by CyrusNajmabadi** [comment]
Is "go to symbol in file" using a different engine (perhaps just a textual one), rather than using the TS language server?

**Comment by andy-ms** [comment]
@scarlac It looks like "Go to Symbol in Workspace" requires you to start typing the name.
![shot](https://user-images.githubusercontent.com/19274678/31506419-3851d3ce-af2c-11e7-8129-3728e937eaf6.jpg)

The navigation features don't use the type system, they use custom code in `navigationBar.ts` and `navigateTo.ts`, so you can navigate to things that the type system doesn't understand.

**Comment by scarlac** [comment]
@andy-ms I appreciate that explanation. As a user I just need it to work. The only reasonable reason I've heard is that it's too many results for it to be practical, but Sublime does it and it works very well so I can't entirely agree with that argument. I wouldn't mind posting a separate issue but it seems I'm not the first to point this out - the request just keeps being tacked on to other issues without being directly addressed.

Right now, Sublime gives me better practical code navigation even though VSCode has much deeper code understanding. Thus, VSCode should theoretically be better at navigation and I think it's just a matter of pushing the boundaries a bit :)

**Comment by andy-ms** [comment]
You might want to make an issue on VSCode then? The TypeScript language service is the same for Sublime and VSCode.
