### ISSUE TITLE
Wrong key inference in object which expands the type and unions the functions 

### ISSUE THREAD

**Issue by h-a-n-a** [microsoft/TypeScript#44823]
# Bug Report

### 🔎 Search Terms

keyof in object type, function union in object type, generics

### 🕗 Version & Regression Information

Tested with 4.3.4 and the latest nightly version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210629#code/C4TwDgpgBA8gRgKygXigbwFBSgQwFxQAU+AdgK4C2cEATgJTIB85VtANFlHAYdwM7AaASxIBzBowHCxGAL4YMAYwD2JAVGWIC8JKkzZ8RHBJwds3InAlw5ClWuBQAZiRRQAPABUoEAB7AIEgATPigAawgQZSdYREZCABs8TzZFPAAFHBocCggAmj53HQBtTwBdRmKABjK6FEZ9bCgaPLIaV00EYoSywkU6WwwXQgAiHBG2KABGACYAZjogA)

### 💻 Code

```ts
type Obj = {
  a: (a:number)=>number,
  b: (b:string)=>string
}

const obj: Obj = {
  a: (a)=>a,
  b: (b)=>b
}

const fn = <T extends keyof Obj>(l:T,c:Parameters<Obj[T]>[0]) =>{
    return obj[l](c)
}

fn("a", 123)
```

### 🙁 Actual behavior

c is not assignable to `never`, and obj[l] appears to be the type of (xxx: number & string) => string | number,
It seems that T is still the type `keyof Obj`, not "a" itself

and I also tried this:

```ts
const fn = <T extends keyof Obj, U extends Obj[T]>(l:T,c:Parameters<Obj[T]>[0]) =>{
    return obj[l](c)
}

fn("a", 123)
```

Even the generic inference looks on the function signature, which is `(a: number) => number`, it is still not able to pass the type check in function block

### 🙂 Expected behavior

T should be infered to "a", not `keyof Obj`

**Comment by MartinJohns** [comment]
> T should be infered to "a", not `keyof Obj`

Generic arguments within functions are not evaluated based on the callsite, but by your definition. All TypeScript knows within your function is that `T` extends `keyof Obj`. This can be `"a"`, it can be `"b"`, but it can also be `"a" | "b"`.

That's the reason why the type is `number & string`. TypeScript doesn't know at this point what type of key is provided, so it must assume that all keys are an option, and you end up with an intersection. But this intersection is impossible to represent, so you end up with `never`.

**Comment by andrewbranch** [comment]
Incredible write-up on what you’re looking for: https://github.com/microsoft/TypeScript/issues/30581
Also relevant: https://github.com/microsoft/TypeScript/issues/27808

**Comment by h-a-n-a** [comment]
> Incredible write-up on what you’re looking for: #30581
> Also relevant: #27808

Would this issue be fixed by any chance sooner or later, or it's considered the actual behavior in TypeScript ?

**Comment by andrewbranch** [comment]
@h-a-n-a I think it’s something we would theoretically like to “fix,” but it’s a tricky problem and we haven’t seen a proposal we really like, and it’s not currently on the roadmap.

**Comment by h-a-n-a** [comment]
> @h-a-n-a I think it’s something we would theoretically like to “fix,” but it’s a tricky problem and we haven’t seen a proposal we really like, and it’s not currently on the roadmap.

Yea, sure! Are PRs welcome for this issue?

**Comment by andrewbranch** [comment]
We would prefer to see a proposal on one of the open issues first before seeing any code. When the label is “Awaiting More Feedback” or “In Discussion” it means we don’t really even know how or if we want to tackle the problem. It needs a lot of clarification first.
