### ISSUE TITLE
Refactoring CJS add missing Imports does wrongly assume that default exists in CJS

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/TypeScript#44825]
# Bug Report

### 🔎 Search Terms

commonjs,
cjs,
require,
default

### 🕗 Version & Regression Information

Not a Regression!

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 🙁 Actual behavior

When i Open a .js file that indicates via ```module.exports``` that it is CJS and i click on quickfix 

let assume the file test_module.js
```js
const MY_EXPORTS = {}
module.exports = MY_EXPORTS;
```

other file where i use add missing imports

```js
const newVar = {
   any: MY_EXPORTS,
}
```

results into
```js
const { default: MY_EXPORTS } = require('./test_module.js');
const newVar = {
   any: MY_EXPORTS,
}
```

### 🙂 Expected behavior

results into
```js
const MY_EXPORTS  = require('./test_module.js');
const newVar = {
   any: MY_EXPORTS,
}
```
i expect that result as a CJS module that uses require does not got a default export.

## Used TSCONFIG
```js
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "moduleResolution": "node",
        "module": "esnext",
        "target": "esnext",
        "noEmit": true,
        "declaration": true,
        "allowJs": true,
        "checkJs": true,
        "emitDeclarationOnly": false,
        "declarationDir": "dist/dts",
        /* Advanced Options */
        "skipLibCheck": true /* Skip type checking of declaration files. */,
        "forceConsistentCasingInFileNames": true /* Disallow inconsistently-cased references to the same file. */
    }
}
```

**Comment by andrewbranch** [comment]
@frank-dspeed do you have a tsconfig.json or jsconfig.json in the project where you’re seeing this happen? If so, can you paste the contents here?

**Comment by frank-dspeed** [comment]
@Andarist did add the tsconfig to the issue at the end
