### ISSUE TITLE
Allow type assertion in import statements

### ISSUE THREAD

**Issue by ImRodry** [microsoft/TypeScript#44833]
# Suggestion

## 🔍 Search Terms

import type assertion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
I'd like to suggest the addition of type assertion directly in import statements. This is already done somewhat automatically but doesn't cover all use cases, especially some edge ones I'll describe below.

## 📃 Motivating Example
I'll explain the exact scenario I faced when I thought of this idea. I use a library that accepts a HEX color string in one of its methods and the type for this is `#${string}`. When importing HEX color codes from a JSON file, these have the `string` type, which conflicts and errors out when trying to assign them to the parameter of the aforementioned method. The same doesn't happen if you declare these as constants, since TypeScript is able to identify the # in that value. Here's an example:

JSON file:
```json
{
    "color": "#FF0000",
    "otherColor": "FFFFFF"
}
```
TS file:
```ts
import { color, otherColor } from "./file.json"
// This method accepts one parameter which has the type `#${string}`
import { method } from "library"

method(color) // This throws an error because type "string" isn't assignable to type "#${string}".
```
My suggestion:
```ts
import { color: `#${string}`, otherColor: `#${string}` } from "./file.json"
// This method accepts one parameter which has the type `#${string}`
import { method } from "library"

method(color) // This works fine because the type for `color` was declared in the import statement
```

## 💻 Use Cases

Like I described, this would allow for type assertion of custom types without the need to write `as <type>` every time the variable is used and thus saving time and making the code cleaner. It also reproduces the behavior that would happen when using constants or variables to achieve the same behavior.

**Comment by MartinJohns** [comment]
I believe #32063 would solve your issue as well.

**Comment by ImRodry** [comment]
It would indeed, however this didn’t show up in my search results so apologies for the duplicate issue. Hope the information I provided helps with the issue you linked though
