### ISSUE TITLE
`querySelectorAll` cant pass a selector array as arguments

### ISSUE THREAD

**Issue by shlroland** [microsoft/TypeScript#44838]
# Bug Report

### 🔎 Search Terms

lib.dom.d.ts document dom d.ts querySelectorAll

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
document.querySelectorAll(['h1','h2','h3','h4','h5','h6'])
```

### 🙁 Actual behavior

vscode reminds me that 
```
没有与此调用匹配的重载。
  第 1 个重载(共 3 个)，“(selectors: keyof HTMLElementTagNameMap): NodeListOf<HTMLHtmlElement | HTMLElement | HTMLObjectElement | ... 67 more ... | HTMLVideoElement>”，出现以下错误。
    类型“string[]”的参数不能赋给类型“keyof HTMLElementTagNameMap”的参数。
      不能将类型“string[]”分配给类型“"wbr"”。
  第 2 个重载(共 3 个)，“(selectors: keyof SVGElementTagNameMap): NodeListOf<SVGSymbolElement | SVGAElement | SVGScriptElement | SVGStyleElement | ... 52 more ... | SVGViewElement>”，出现以下错误。
    类型“string[]”的参数不能赋给类型“keyof SVGElementTagNameMap”的参数。
      不能将类型“string[]”分配给类型“"view"”。
  第 3 个重载(共 3 个)，“(selectors: string): NodeListOf<Element>”，出现以下错误。
    类型“string[]”的参数不能赋给类型“string”的参数。ts(2769)
```

### 🙂 Expected behavior

no error

**Comment by MartinJohns** [comment]
This is the correct behavior. The function does not accept an array. See https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll#parameters

**Comment by shlroland** [comment]
> This is the correct behavior. The function does not accept an array. See https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll#parameters

but I run the `document.querySelectorAll(['h1','h2','h3','h4','h5','h6'])` in chrome console,it works correctly

**Comment by MartinJohns** [comment]
Then Chrome has non-standard support for this. This might not work in every browser.

But what is the issue? The documentation I linked clearly describes how to query for multiple selectors.

**Comment by orta** [comment]
Confirmed @MartinJohns's interpretation [with the spec](https://dev.w3.org/2006/webapi/selectors-api/) - that's some extra sugar which isn't in the standard.

**Comment by nmain** [comment]
This behavior actually _is_ in the standard.  `querySelectorAll` takes a string in webidl, and the conversion from arbitrary es values is defined here: https://heycam.github.io/webidl/#es-DOMString.  So `document.querySelectorAll(['foo', 'bar'])` is equivalent to `document.querySelectorAll(['foo,bar'])` with array to string coercion.

So this is instead a question of whether TypeScript should allow the myriad of coercions that JS engines do at runtime, and the answer to that has generally been no, owing to hazards like `[object Object]`.
