### ISSUE TITLE
编译后可以迭代 class 里面的log方法

### ISSUE THREAD

**Issue by 2395000206** [microsoft/TypeScript#44844]
![image](https://user-images.githubusercontent.com/58016208/124087253-6a5dc300-da84-11eb-899b-bfc2791c95f2.png)

**Comment by 2395000206** [comment]
![image](https://user-images.githubusercontent.com/58016208/124088847-edcbe400-da85-11eb-9fd9-c4da6eec92e0.png)
会不会打包成这样更好呢

**Comment by orta** [comment]
Hi there, I'd recommend looking for a Chinese TypeScript community if this is about your code, or if you think this is a TypeScript bug please follow the issue template and re-create the issue in English
