### ISSUE TITLE
This is not the tsc command you are looking for

### ISSUE THREAD

**Issue by spinlud** [microsoft/TypeScript#44843]
Just updated from `typescript 4.3.1` to `typescript 4.3.5`.  
When I try to compile using `npx tsc` or `npm run build`, I got this:

```                                                                               
                This is not the tsc command you are looking for                
                                                                               

To get access to the TypeScript compiler, tsc, from the command line either:

- Use npm install typescript to first add TypeScript to your project before using npx
- Use yarn to avoid accidentally running code from packages which haven't been installed

```

`package.json`
```json
{
  "name": "some-package",
  "version": "1.0.0",
  "description": "",
  "main": "build/index.js",  
  "scripts": {
    "clean": "rm -fr build",    
    "build": "npm run clean && tsc"
  },
  "author": "xyz",
  "license": "ISC",  
  "devDependencies": {    
  },
  "dependencies": {    
    "typescript": "^4.3.5"
  },
}
```

`OS`: `MacOS 10.15.7`
`Node`: `v12.18.4`

**Comment by MartinJohns** [comment]
Use `npx typescript`, not `npx tsc`. The `tsc` package on npmjs is not TypeScript.

**Comment by orta** [comment]
Confusing, but `npx typescript` should work if you have `typescript` in your node_modules.

Given your package.json - it's also possible you haven't `npm install`'d and so the lookup fails.

**Comment by braxtonb** [comment]
In case someone has encountered this lately trying to run `npx tsc --init` and is seeing "This is not the tsc command you are looking for," try the following:
```
npx --package typescript tsc --init
# OR
npx -p typescript tsc --init
```
This will run a command other than the command whose name matches the package name by specifying a --package option.

Sources:
https://stackoverflow.com/a/69058824
https://docs.npmjs.com/cli/v7/commands/npx#examples

**Comment by nightingale-dev** [comment]
Take a look at this post for the solution to it. 

Make sure you run `npm install -g typescript` and remove tsc package from the json file if you have them. 

https://stackoverflow.com/questions/67677320/this-is-not-the-tsc-command-you-are-looking-for

**Comment by KnightKrusty** [comment]
I need to first run  ```npx -p typescript``` that log me in new shell after that tsc -w works.. otherwise its the same error over and over again..

**Comment by Kazitanvirazad** [comment]
Try this if this error for windows operating system. 
First check in C:\Users\username\AppData\Roaming\npm\ Most probable you'll not find tscserver files which is the problem. 
**Just delete entire npm folder and go to powershell as admin and run -> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
select 'A' from the options. 
Now open cmd from anywhere and type to install tsc globally or locally as per your convenience -> npm install tsc --g
Hope your problem is solved. Please reply if my solution is working for your problem. Thank you

**Comment by rickychou2023** [comment]
> In case someone has encountered this lately trying to run `npx tsc --init` and is seeing "This is not the tsc command you are looking for," try the following:
> 
> ```
> npx --package typescript tsc --init
> # OR
> npx -p typescript tsc --init
> ```
> 
> This will run a command other than the command whose name matches the package name by specifying a --package option.
> 
> Sources: https://stackoverflow.com/a/69058824 https://docs.npmjs.com/cli/v7/commands/npx#examples

You are Awesom😘

**Comment by gain5151** [comment]
Please check permission and owner of .nvm directory.
ex)
  $ ls -al /root/.nvm/versions/node/v18.19.0/

And modify them if you need.
ex)
   chown -R root:root /root/.nvm/versions/node/v18.19.0/

And please remove tsc and typescript in global.
ex)
  npm uninstall -g tsc
  npm uninstall -g typescript

And please install tsc again!
ex)
  npm install -g tsc
  npm uninstall -g typescript
