### ISSUE TITLE
Different behavior exhibited between homomorphic mapped types

### ISSUE THREAD

**Issue by corymharper** [microsoft/TypeScript#44850]
# Bug Report

### 🔎 Search Terms

mapped, generic, string, union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried. (I tried every version the Typescript Playground has listed, and didn't see a pertinent answer in the FAQ)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEEEAUElQFQJ4AcCmBnAUAF2S0A5FAd0gEMAnUgWxSxXLQB4BRAOwBMkB7AS1azKUadBqAC8oVigBu9AHzjQAb1ABtANYoEoPqE0IuAM1BtOvfoOq16aALoAuUAAp8XVvgCuAGy+kARl4oLBzcfAIUViJoGlq2cgCUqragAL4A3BgYIPDoWKA4qKDSAIwYYfSGpADGeHC5AGrFyhgAkIZcXI4A5O1cXaAAPqBdfhT9QyOkAF5dGSmZ2XVoeQV40gBMZfwV1XgAykhePFhNSq293b2zGPNbIpU1oAdHWOvNbR3do+TXt+XkD32h2OAGZ3hdhqMZnNMqscst6m8JM9jk0hijXoMnsCsCCMlkwEssJgqm5lvlcsVHIQSBFhDZGETEQoJCoIapJjMADTDK48yY-ZLpTKk1jkujLdaOFQxbS6fRGeFYREOZyudzeXwBIJM9ayuKJIWKNmfNScrr8vmQsZC-Gi8W5EHU4iWekMRkNYos5Sgdnmy0dC3WwWpDJAA)

### 💻 Code

```ts
// API Types
type NewParameters<EndpointParameters = never> = { [key in keyof EndpointParameters]: (NonNullable<EndpointParameters[key]>)[] };

// Test type v1
interface TestV1 {
	foo: 'foo' | 'bar' | 'baz';
}

// Test type v2
interface Split1 {
	foo: 'foo';
}

interface Split2 {
	foo: 'bar';
}

interface Split3 {
	foo: 'baz';
}

type TestV2 = Split1 | Split2 | Split3;

// Tests
// This throws an error
const test1: NewParameters<TestV2> = { foo: ['baz', 'foo', 'bar'] };

// These do not
const test2: { [key in keyof TestV2]: (NonNullable<TestV2[key]>)[] } = { foo: ['baz', 'foo', 'bar'] };

const test3: NewParameters<TestV1> = { foo: ['baz', 'foo', 'bar'] };

```

### 🙁 Actual behavior

Test examples 1 and 2 produce different types.

### 🙂 Expected behavior

Behavior should be consistent between the first two test examples.

**Comment by whzx5byb** [comment]
According to https://github.com/microsoft/TypeScript/issues/23345#issuecomment-394165530, homomorphic mapped types are also distributive, though this behavior is never mentioned in the documentation.

If `TestV2` is a distributive union here, so `NewParameters<TestV2>`is mapped over to `NewParameters<Split1> | NewParameters<Split2> | NewParameters<Split3>`, which resolves to ` {foo: 'foo'[]} | {foo: 'bar'[] } | foo: 'baz'[]}`.

**Comment by corymharper** [comment]
> I'm not sure but it seems like an intended behavior caused by an unwritten rule.
> 
> According to [#23345 (comment)](https://github.com/microsoft/TypeScript/issues/23345#issuecomment-394165530), homomorphic mapped types are also distributive, though this behavior is never mentioned in the documentation.
> 
> If `TestV2` is a distributive union here, so `NewParameters<TestV2>`is mapped over to `NewParameters<Split1> | NewParameters<Split2> | NewParameters<Split3>`, which resolves to ` {foo: 'foo'[]} | {foo: 'bar'[] } | foo: 'baz'[]}`.

That would explain the behavior, but I don't exactly understand why the behavior in `NewParameters<TestV2>` differs from `{ [key in keyof TestV2]: (NonNullable<TestV2[key]>)[] }` as I would expect that to be distributive as well if that were the case.

**Comment by whzx5byb** [comment]
> > I'm not sure but it seems like an intended behavior caused by an unwritten rule.
> > According to [#23345 (comment)](https://github.com/microsoft/TypeScript/issues/23345#issuecomment-394165530), homomorphic mapped types are also distributive, though this behavior is never mentioned in the documentation.
> > If `TestV2` is a distributive union here, so `NewParameters<TestV2>`is mapped over to `NewParameters<Split1> | NewParameters<Split2> | NewParameters<Split3>`, which resolves to ` {foo: 'foo'[]} | {foo: 'bar'[] } | foo: 'baz'[]}`.
> 
> That would explain the behavior, but I don't exactly understand why the behavior in `NewParameters<TestV2>` differs from `{ [key in keyof TestV2]: (NonNullable<TestV2[key]>)[] }` as I would expect that to be distributive as well if that were the case.

I guess this is because `TestV2` appears as a generic type parameter in `NewParameters<TestV2>`, but does not in `{ [key in keyof TestV2]: (NonNullable<TestV2[key]>)[] }`. 
This is similar to the rule described in [the documentation](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types).

**Comment by corymharper** [comment]
> the documentation

I had seen that in the documentation, but it describes what happens in the case of a conditional type, of which this is not, but you are right that the behavior seems pretty much in line with what is described there.
