### ISSUE TITLE
Narrowing on await

### ISSUE THREAD

**Issue by polkovnikov-ph** [microsoft/TypeScript#44858]
# Bug Report

### 🔎 Search Terms

`narrowing await`

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210701#code/DYUwLgBAHgXBB2BXYwIB8IGcwCcCW8A5hALwQDkAFiCgPbkDcAUABQCGmAnvAMYQsBKUgD4IAbyYQpEPADN+YTgAcQteVAgBCEmXLZ8RckInTTEHOEQ54zUwF9J0tgHc2eSPBDOIABRy0AWzxMEBYWC0xaYAA3ECESURMzKQ0yJBRbZKxwABU8ANVEMHCQSJiQABoIAAYBTKk7OscpAHoWiABhNnh4WkgLNgATCCV-FRxFCjBaAGVcAkJyCDUEZGBmiB5aeDKQADpgWkIWKD3puYNjgSbGwQYgA)

### 💻 Code

```ts
let x: null | string = 'hello';
(async () => {
    if (typeof x !== 'string') {
        return;
    }
    await new Promise((resolve) => {
        x = null;
        setTimeout(resolve, 0);
    });
    // Cannot read property 'toString' of null
    console.log(x.toString());
})();
```

### 🙁 Actual behavior

`x` is narrowed to `string`, but `await` should have either extended it back to `null | string`, or narrowed it in the parameter of `Promise` constructor. `toString` gets called on `null`. In this way arbitrary type punning is possible.

### 🙂 Expected behavior

Code shouldn't have compiled.

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/issues/9998

**Comment by polkovnikov-ph** [comment]
Actually TS _can_ analyze every function, by `pure` annotation. It's discussed in linked thread.

**Comment by whzx5byb** [comment]
> Actually TS _can_ analyze every function, by `pure` annotation. It's discussed in linked thread, and it's what tools like `webpack` use to make tree shaking possible.

It is still in discussion. I guess you might be interested in https://github.com/microsoft/TypeScript/issues/7770.

**Comment by polkovnikov-ph** [comment]
@whzx5byb Thank you! I'd spend quite some time looking for these links.

**Comment by MartinJohns** [comment]
@polkovnikov-ph Basically any assignment via closure is missed by the compiler, due to #9998. Doesn't matter if async or sync.

#11498 is also a relevant issue to follow, although there is no progress at all.

**Comment by polkovnikov-ph** [comment]
What a nice joke! Thank you!
