### ISSUE TITLE
exactOptionalPropertyTypes: delete triggers error on optional property

### ISSUE THREAD

**Issue by mtreder** [microsoft/TypeScript#44852]
# Bug Report

The fix in https://github.com/microsoft/TypeScript/pull/44612 doesn't look to work as expected.  When there is an optional property and `exactOptionalPropertyTypes` is enabled, `delete` will now show an error for properties marked with `?`.

### 🔎 Search Terms
exactOptionalPropertyTypes
exactOptionalPropertyTypes

### 🕗 Version & Regression Information

The 6/30 nightly build

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.0-dev.20210701&exactOptionalPropertyTypes=true#code/CYUwxgNghgTiAEYD2A7AzgF3kgRgKwC54BvUAMwEsUKMQIBPACRDgFkp6cQBVFcqkMAD8RFAFcAtlxgBfANwAoBaAgha2fADp+1Wg2ZsOXXjsGKgA

The `exactOptionalPropertyTypes` flag doesn't preserve in the linked example, so you'll need to expand TS Config and select it again.

### 💻 Code

```ts
declare const obj: {definitelyHereMaybeUndefined?: number};

delete obj.definitelyHereMaybeUndefined;
```

### 🙁 Actual behavior

The delete line gives the following error with `exacteOptionalPropertyTypes` enabled.

`The operand of a 'delete' operator must be optional.`

### 🙂 Expected behavior

I don't expect there to be an error on this line since the property being deleted is already marked as optional.

**Comment by mtreder** [comment]
I never got a reply on this comment so I just created a new issue.

https://github.com/microsoft/TypeScript/pull/44612#issuecomment-871377789

**Comment by DanielRosenwasser** [comment]
Thanks for opening the issue, it's hard for us to keep track of all the activity on the issue tracker.
