### ISSUE TITLE
Formatting for union types needs improvements

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4486]
```TypeScript
type T = A
       | B
       | C;
```

If I try adding another union arm to the RHS of `T`, formatting ruins everything.

**Comment by SaschaNaz** [comment]
What's the expected result?

**Comment by mhegazy** [comment]
@DanielRosenwasser i believe this is handled by #4442.

**Comment by DanielRosenwasser** [comment]
I'd expect the `|`s to stay aligned to each other - if #4442 doesn't handle that, it doesn't have to be done there, but it would be great for us to have it eventually.

**Comment by SaschaNaz** [comment]
#4442 doesn't handle that. Maybe a new indentation style will give the better result, like the one discussed in #3781.

**Comment by mhegazy** [comment]
looks fixed now.
