### ISSUE TITLE
Generic function is not infered correctly when passed as an argument

### ISSUE THREAD

**Issue by zecuria** [microsoft/TypeScript#44861]
# Bug Report

When passing a function with a generic as an argument to another function. The generic parameters are not inferred correctly.

### 🔎 Search Terms

Generic, Generic function as argument, Function argument infer.

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generic inference

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocmATzCTgGFdIA7JFmAdWBgAsBBAM5wAvHAA8ABRxhBAPgAUYGYIBccaRFlwAZHADecFGsTEYAOibgIbDgBVaSKSrlwAvgEpRrlC2oUAGyR4OyRBLh4BEytWdgi+IVE4BS8RVxYAVwCAiipHOFDwzW0xfXI4CrgANxQAjKR1cKhgFgBzCkq4LRhgGxMmltaAbQBdcjcKND6QsJgYpKUVdUKYYsFU9KycyhXuBMEFMs7jZdmYgBpyypq6hoIb+vxLzu7elhMh-Ce4GCh6kbgAHpAXAplAiBgAtQ4K1gFUwnAkODoOMPKQgSC+MBhAB3aAAa0ElBodDgAHF2EjgGg1uI7K5SlcKg87nYOpVXn1lqMKBNyJgMiwMG9yZTmmgYnTFMotCYKWxxbT6V5DEQYBkoCw4Jlsu5crtIkJDkyjHKxdSLhi4AATCAIlgQeAtTBImHmtAmlnqL7PDlgHpcuCfb6-f5WwS8CBZa3ax1wPFQfGooA)

### 💻 Code

```ts
type ComponentWithAs = <Props>(props: Props & { as: React.ComponentType<Props> }) => any;
let TestWithAs: ComponentWithAs = () => null;

type TestProps = {
    value: string;
    options: string[]
};
const TestComp = (props: TestProps) => null;

TestWithAs({
    as: TestComp,
    value: "value",
    options: ["", true] // correctly gives error
}); // this works

type GenericProps<T> = {
    value: T;
    options: T[];
};
function GenericComp<T>(props: GenericProps<T>) { return null };

TestWithAs({
    as: GenericComp, // does not infer generic
    value: "",
    options: ["", true] // should give error but does not
})
```

### 🙁 Actual behavior

Does not infer the generic, instead infer produces unknown

### 🙂 Expected behavior

Should infer the generic and produce an error when the generic does not match.

**Comment by RyanCavanaugh** [comment]
I don't see any bug here. You could equally write
```ts
GenericComp({
    value: "",
    options: ["", true]
});
```
which also correctly doesn't error.

**Comment by zecuria** [comment]
Yep that does work as intended, but I for some reason it work for function parameters:
```ts
 type GenericProps<T> = {
    value: T;
    options: T[];
    genericFunc: (test: T) => void;
};
function GenericComp<T>(props: GenericProps<T>) { return null };

TestWithAs({
    as: GenericComp, // does not infer generic
    value: "",
    options: [""],
    genericFunc: (test: string) => {}, // gives error that string can't be assigned to unknown
})
```

I might be missing something in which case I do apologize.

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocmATzCTgGFdIA7JFmAdWBgAsBBAM5wAvHAA8ABRxhBAPgAUYGYIBccaRFlwAZHADecFGsTEYAOibgIbDgBVaSKSrlwAvgEpRrlC2oUAGyR4OyRBLh4BEytWdgi+IVE4BS8RVxYAVwCAiipHOABxdiQoYDRNWXE7VzF9cjgGuAA3FACMpHU7Cka4LRhgGxM7AG0AXW7GvoGWVoAxDJY0dQUYMJhO1NcmiGAAEwo3CkwFjGnC4tK0GKrFZS0TIrZLisEbr0MiGAyoFjhM7PcuVC4W4CUECjqPWM6keJTKMQANHAAPTIuC7CBhP4QeDAFiYEpwADmFzK9UaLTaHQI+AR5IaU0G6mG+HwozpPUZMwC80Wy1W4XU4VKLCJmwMbiRqLggl4ECyu2x8AA7tAANZ0zxAA)

I would expect it to have inferred string at that point.
