### ISSUE TITLE
Object with optional properties is not type narrowed

### ISSUE THREAD

**Issue by bartenra** [microsoft/TypeScript#44866]
# Bug Report

### 🔎 Search Terms

Type narrowing optional property

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.4#code/C4TwDgpgBAygNge2FAvFA3lAlgEwPwBcUAzsAE5YB2A5lAL4CwAUMwGYCulAxsFgpVEoQIOYgEkcACmKJgRTLiKkKNegEoMzRiyYduvflGARS02UXhIN6ZlGysoZpADpc123cHDREp8DUe2nRAA)

### 💻 Code

```ts
type Slot = { id?: string }

function needsId(slot: { id: string }) {
}

function test(slot: Slot) {
  if (slot.id) {
    needsId(slot)
  }
}
```

### 🙁 Actual behavior

The compiler complains that on the line where `needsId` is called, `string | undefined` cannot be assigned to `string`.

### 🙂 Expected behavior

Inside the if-statement, the Typescript compiler knows that `slot.id` is a `string`. I expect `slot` to be narrowed to `Slot & { id: string }` inside the if-statement, so that `needsId(slot)` is a valid call.

**Comment by MartinJohns** [comment]
[Quoting @jack-williams:](https://github.com/microsoft/TypeScript/issues/31755#issuecomment-498669080)

> Type guards do not propagate type narrowings to parent objects. The narrowing is only applied upon access of the narrowed property which is why the destructing function works, but the reference function does not. Narrowing the parent would involve synthesizing new types which would be expensive. More detail in this [comment](https://github.com/microsoft/TypeScript/issues/30506#issuecomment-474802840).
