### ISSUE TITLE
Class expression name not bound for static blocks 

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#44872]
[Playground Link](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210702#code/G4ewlgJgBAxgNgQwM5KgMRCKBvAsAKCiKiQBcFSwYoAHAJxBqgF4oBGA4k8y6vQrsRggAdkhBwApgDo4IAOYAKDCGn1GASgDcnQURVqGNANTGdAogF9dRMhSo4bg4WIky5Sg+pranXL0am5lzWFtz2fH5CouJSsgrKmIaawXroSd5BTqGWQA)

**Expected**: 1, 2, 3 printed on separate lines
**Actual**: Runtime error thrown, `Foo` is not defined.

```ts
void class Foo {
    static prop = 1
    static {
        console.log(Foo.prop);
        Foo.prop++;
    }
    static {
        console.log(Foo.prop);
        Foo.prop++;
    }
    static {
        console.log(Foo.prop);
        Foo.prop++;
    }
}
```

**Comment by DanielRosenwasser** [comment]
CC @Kingwl

**Comment by rbuckton** [comment]
Its a simple fix. I'll have a PR up shortly.
