### ISSUE TITLE
Node 16 has a force option for rmdir -- it's missing in the declaration files.

### ISSUE THREAD

**Issue by BobFrankston** [microsoft/TypeScript#44885]
# Bug Report

### 🔎 Search Terms

rmdir force

### 🕗 Version & Regression Information

Using Typescript 4.2.4 with node 16

### ⏯ Playground Link

Need declaration files for fs.rmdir

**Note** _this may be moot, now I'm getting told to stop using rmdir and use rm instead._

### 💻 Code

```
await fp.rmdir(stage, { recursive: true, force: true });

```

The force options is needed with recursive but isn't in the definition files yet.

### 🙁 Actual behavior

WIthout force I'm told I shouldn't use recursive unless I also specify force

### 🙂 Expected behavior

no error message because it's supposed to work in node.

**Comment by tjjfvi** [comment]
This is an issue with `@types/node`, not typescript; you should file an issue (or find an existing issue) at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/).

**Comment by BobFrankston** [comment]
Thanks
