### ISSUE TITLE
Option to require a break for each switch clause

### ISSUE THREAD

**Issue by BobFrankston** [microsoft/TypeScript#44886]
# Suggestion

## 🔍 Search Terms

switch break required

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'm surprised this isn't a common suggestio.

I'm very used to C# and VB so I forget to guard against falling through on switch/case. There should be an option to require a break statement between switch cases for safety. As an option, it wouldn't break existing code and would be compatible since it's an existing language feature.

The only change would be to assure that flow doesn't drop through to the next case.

## 📃 Motivating Example

switch(foo) {
 case "a": do something that involved a
 case "b": do something that shouldn't involve a
}

## 💻 Use Cases

Same as the motivation for adding the check in C#

**Comment by zardoy** [comment]
There is a tsconfig flag for that. Checkout https://www.typescriptlang.org/tsconfig#noFallthroughCasesInSwitch

**Comment by BobFrankston** [comment]
Thanks. WOnder why it didn't show up in the search.
