### ISSUE TITLE
To add `cache` support for GitHub Actions using `setup-node`

### ISSUE THREAD

**Issue by oscard0m** [microsoft/TypeScript#44898]
# Suggestion

To add `cache` support for GitHub Actions using `setup-node`

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

`cache`, `setup-node`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

## 💻 Use Cases
See https://github.com/microsoft/TypeScript/pull/44897

**Comment by jakebailey** [comment]
I think I'm going to close this one; `npm ci` in our repo takes 7 seconds. My experience with GHA caching is that it can take that long just to download and unpack the cache before npm or another package manager even starts running and can copy everything into `node_modules`. On a project with lots of dependencies, I can see this mattering, but I don't see it benefiting this particular repo when we are a single package using a lockfile.
