### ISSUE TITLE
Conditional type causes `Pick` to behave weird when the provided union to pick from is generic

### ISSUE THREAD

**Issue by gunnnnii** [microsoft/TypeScript#44890]
# Bug Report

If you create a type for an array of records, by picking a union from some interface, you get an array where every record contains all the keys of the union.
However, if you return the type from a conditional type, the array type changes. Instead, you end up with a union of record arrays that only allow for a single key. This does not seem like expected behaviour to me.

### 🔎 Search Terms
- Union
- Conditional types
- Pick
- Generic
- keyof

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and did not seem to fit any of the issues in the FAQ
- I was unable to test this on prior versions to 3.3.3 because I don't have older versions of typescript set up right now

It seems that this behaviour is long standing. I tried going back all the way to version 3.3.3 in the playground and the bug persisted, and it is still there in the nightly. My understanding of the problem does not match with any of the issues described in the FAQ.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoHsC2EBKEHpQAmyA3gFDLIAOU61AjAFzIDOYUoA5gNyU11qAJhbtOIXv1r0AzKI7c+VadQAs88ZIC+5APS7kAcWAA3CK2QAFYAgDWAHgzY8BYgBpkAchUNPAPgBtAF1kAB8rGwcnXHxCIg9vQSF-YOQAOgy9A0I0LBjXImDyMABPahQADXtDCBBoG2QIAA9IECILWwgS9Bhc51jiMK84ABsR-2QAXiNa+oRGltr24bHPZAB+Pvy41JZrO0c8lziPAFEmhBGAVyIIatnOBATR8b9AoPIso1NzMmQAzolZCgZDnS43O41OqPACqIGA6BAz1WfiCLGix2IAK6IS0RVK5WQAE17tCGs1WstAT0tpiSOFPC8JtN9lEjgN4qCLtdbqS5sjXu9PgQQOxkFAWFVGSipv9SAJ6MwvAB3dDKzweFQiFUACwg6s1gjkXh1Vx1GoVahYjJ1cDWWg+IrFrEl9kSirWDK1zLllqVnlVBst2oDevVyAdXyo0Zjsbj8YTiaoAD1U8gAEZ0TrIVPJ8hOsDIMAsEnuxierzevyygLynzWwMWrUNsP2oJAA)

### 💻 Code

```ts
interface SomeRecord {
  prop1: string;
  prop2: string;
  prop3: string;
  prop4: string;
}
// Gives Pick<SomeRecord, 'prop1'>[] | Pick<SomeRecord, 'prop2'>[] ...
// or SomeRecord[]
type X<Generic extends keyof SomeRecord | 'all'> = Generic extends 'all' ? SomeRecord[] : Pick<SomeRecord, Exclude<Generic, 'all'>>[]

// Gives { [key in Exclude<GenericUnion, 'all'>]: SomeRecord[key] }[]
type Y<Generic extends keyof SomeRecord | 'all'> = Pick<SomeRecord, Exclude<Generic, 'all'>>[]

const r: X<'all'> = [{ prop1: 'wow', prop2: 'whew', prop3: 'huh', prop4: 'aha' }]
const s: X<'prop1' | 'prop2'> = [{ prop1: 'wow', prop2: 'whew' }]
//                                               ^^^ broke ^^^
const t: Y<'prop1' | 'prop2'> = [{ prop1: 'wow', prop2: 'whew' }]
```

### 🙁 Actual behavior
You end up with an array of types from a union of single key records, like:
```
Pick<SomeRecord, 'prop1'>[] | Pick<SomeRecord, 'prop2'>[]
```
### 🙂 Expected behavior
You end up with an array of a single record type, where every key from the generic union appears, like:
```
{ [key in Exclude<GenericUnion, 'all'>]: SomeRecord[key] }[]
```

**Comment by MartinJohns** [comment]
This is working as intended. The issue is not the generic, but the union. Look up "Distributive Conditional Types", it's in the docs.

**Comment by bodinsamuel** [comment]
Hello,

I'm hijacking this issue to avoid opening an other one in case it's the same thing.

I have a similar behavior where using Pick does not result in compatible interface, while it is. 
A bit counter intuitive if it's working as intended but I can understand the problematic.

[Playground link](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/PTAECEHsEsBsFMBOAHWBDALvAUPAHspIhqBgJ7LygDKkArogMbwAqFVAvKAOSMDOAN26gAPjwDmaYWO5opAbmy4CREtAB2WRADM0zUAFE8W9WlgARTGloNmAcUiRxCAIKnYZDNH6gA3tlBQAFt4DERvPgAuUD4wjXEAbQBdRQBfJXxCYlANLV19IxMzSwxreiZ4AGFqADU-UAZYaNjw9XFQVMVlLJJySlBKyHV1eEYvIZK0UA4A0UNjJHdJmwqHJ1d3TwjZsULF4qsV5mqarszVHM0kfKo9xHcAWVC0ABMrcDQ+Kn9Avvhoo6sdiKQKMIYjMbQCZWaKDYajcbqSZpboXXLXPS3Bb3MxPUpvUprZzwNxmLY+fBYdQvPjzIqwPGvd6fb6zP7RbiSbgg0Bg+GQ6GlaJ3JaHcr2RzE0keLz8FHnbLonSYun7BnPAloE6gSnwam0kW4jXMr5+NnsDn8IQ8vkQxGTYXY0WlQEnFGo7J-VU49X4qzTHbex7G0onQOG31MwmSjZk2V8LraOjqAXqUjwWIACkpjvpjM1AEozaChnxIAgAHSwJzZ4wFlEgQzU0AAIxgCBQ6CwSkbAHUiABreKgT46ggI+AvbB82JjjAOoNGv2labF0gWnhW7gAGlmtoRUKRMLXgUaHIAFjvZqld+lsFgs5TJvWe2AALQfj-YRvmSCgdSQCQADug6tnQJCQC2ABWCK0mgiBUC03gYB4OQvHqsrfmALDntAtL4GgQSoFQeGgC8dBBC2rajGgdCmgAktwQSgMg3hDm0pDnohhFUAO8BkKACF8HQsBeBxGicdxISXHkKotuBORqLSGB-rh4jnrA0Dqb0XGgAAjnQGaIlhoAPFp54kC2VDkVQKmgOYeFxPJXgCFQfIvNAiJmOulC0gA-NOpYkE+VgAEzRAACmxAA8Eb5lY248H80ibuCB6ClIAB8q4-D5-yboIV4lvy9rHrlp6IE0PCXrugQ3tgd4Phgma5RWbUhaUtWgG1FYdWgoUNS+QA)

Is it the same explanation?
