### ISSUE TITLE
Possible bug with type narrowing via type guards

### ISSUE THREAD

**Issue by gabrielurbina** [microsoft/TypeScript#44894]
# Bug Report

### 🔎 Search Terms
 - Type guards
 - Type narrowing

### 🕗 Version & Regression Information
Seen as far as **3.3.3**

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about **Type Guards**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlhAIgUwGZzMgJjAvDACgDcAuGAVzAGswQB3MASjKPghgG8BfGAHxjDkANkLwA+GKwCEufJSxoM2ANwAoVaEixKVMjtoM8FMAvSYsauKkIIUZ7AR2NGnVTBibokgIZCy3PgFhUTlqZRgAegiYKABPAAdkGAB5AGkpVS51T1hoACcyfIwAc0D5RXNAwREjACIACxAhb1rLawJbCod851d3HJ8-GCKwUvx88KiYhKS0jKyNcC9BAFsyVYAjZDyyky6cfmqQmABGACY2myR9glXejjcPJdgiX3XyFa2d-FXJ6LjEil0plss8YKgwGQCAQXLgJEQQHAsC5+OV7AcgjV8DDxJwuJcOtd0QQIfdHgNXkMcXDJIicPgIX9poC5iDFloYN48gVOWBYgBtAC6u1MSgxRyM-JOABoYGdZQBmQUEzrErl5Mn9MGU8jIMjePlCozqpkA2bAhYDEAbABW-hiyGg70+2xgPFRe3RVWCRg4DqdpzObpVRLFBGtNs1Tw5Or1nH9UGdXzdRgjppmQPm6imAAltkkEDF6kl4nlrUJkCt2V48shgPb+bphlA8iVBUnXe7jKLKocffg-VBHYnA8HVFYrnYw7XgFGKb5dQ2myNiu2gi6djx8DP04CAKIAJQPyQPsuQAA9EsAhzg-Y3Ci22x3NzANuRYDPkHAiNg8RktRyVDILE7BkEBsQgNYZqQTAM51CutSRNEAByIAwOB7A9tgbJTAA6iAeRUFyIDyGQGyxOCBHACU8CwFAaEGhRWyoARSTeBAcDFGAJSynAsB0ARVAQNWsDAOxN4HnWS4Pq2oxrpsnYivs3pYvGQ4BucKbsbysRqOO7SqmGYnQNgkmzi4DwAV4sbSc2smrs+Kb4MZEl1ru5r-tGXgYTAYHATB0HWC5pl1vBj6jIhUypMB7BckkWFYLK2kXleN4gkAA)

### 💻 Code

```ts
const isPresent = (v: unknown): v is {} => v !== undefined && v !== null;
// Here is the problem
const rec: { [k: string]: number } | undefined | null = { test: 12 };
if (isPresent(rec)) {
  const value: { [k: string]: number } = rec; // type ERROR, expected { [k: string]: number } but received {}!
  const keys : keyof typeof rec = "string" // No keys defined
}

// Workaround: by asserting it to any before assigning, it works
const castedRec: { [k: string]: number } | undefined | null = { test: 12 } as any;

if (isPresent(castedRec)) {
  const value: { [k: string]: number } = castedRec; // type OK!
  const keys : keyof typeof castedRec = "string" // Keys are defined, as expected
}
```

### 🙁 Actual behavior
Using a type guard,  `(value: unknown) => value is {}`, to narrow a value of type `{ [k: string]: number } | undefined | null` initialized with an object literal, yields the type `{}`

It's necessary to type assert the object literal to `any`

### 🙂 Expected behavior

Using a type guard,  `(value: unknown) => value is {}`, to narrow a value of type `{ [k: string]: number } | undefined | null` initialized with an object literal, yields the type`{ [k: string]: number }`

**Comment by gabrielurbina** [comment]
There is another case, it appears that the type of the literal used to initialize the variable has something to do with it

```ts
const isDefined = (v: unknown): v is {} | null => v !== undefined;

const str: string | undefined | null = "hola";
if (isDefined(str)) {
  // @ts-expect-error
  const val: string = str; // type error string | null should not assignable to string
  // @ts-expect-error
  const nil: null = str;
}
// Works if we assert the type
const assertedStr = "hola" as string | undefined | null;
if (isDefined(assertedStr)) {
    // @ts-expect-error
  const val: string = assertedStr; // type OK string | null is not assignable to string
  // @ts-expect-error
  const nil: null = assertedStr; // type OK string | null is not assignable to null
}
```

[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlhAIgUwGZzMgJjAvDACgDcAuGAVzAGswQB3MASjKPghgG8BfGAHxjDkANkLwA+GKwCEufJSxoM2ANwAoVaEixoAJzK6MAcz4UwC9Jhz9BIvDABEACxBCAhvbVxUhBCgvYCXUZGTlUYGAB6CJgAASgIAFpkAA8AB2RgKCSdHRAdMJhNaElXIX0oHSM7XWVI6KgAT3SYZBy8mAMwY2thUQhnYRxaWFcICDhDMFcAIyFkGCgQDoqjAqjY+KS0jKzW3PzwotgwODKBXuqKtS5VdYB1PKp2Lxg6edGIVtgoR3nG9I04GKHy+2AAyhU7E4XO4YKNlpUuiZ5IpLCYbEJPN4CL5UQEQTooOCKsFQuFwus4okUulMtl9gUjiUzp1jPgCUSsBCdLV1v95gB5ADSCKqPVsCAEIBGYwmU1mfyWrLW0SpW1puzaB0KQOOpzIGLsHOJPLqCyagpFrPRF0lwzhssmMzmCyWGNUNyAA)

**Comment by RA80533** [comment]
> ### 🙂 Expected behavior
> 
> Using a type guard, `(value: unknown) => value is {}`, to narrow a value of type `{ [k: string]: number } | undefined | null` initialized with an object literal, yields the type`{ [k: string]: number }`

The type guard narrows its arguments to `{}` based on its definition: `value is {}`. Did you mean to define the type guard using `{ [k: string]: number }` instead?

Regarding your playground link, TypeScript knows that `str` is of type `string` when it's assigned. It's even of type `string` when it's assigned to `val` (hence why there is no error on that line).

**Comment by MartinJohns** [comment]
> There is another case, it appears that the type of the literal used to initialize the variable has something to do with it

This is working as intended. Assignment narrows variables to the assigned type.

**Comment by gabrielurbina** [comment]
Thanks Martin

Upon review, the posible problem, is not the typeguard, is this:

```ts
const testFn = (paramValue: Date | undefined | null) => {
    const staticValue: Date | undefined | null = null; 
    const assertedValue = null as  Date | undefined | null; 
    const D1: null = paramValue; // Expected Type 'Date | null | undefined' is not assignable to type 'null'
    const D2: null = assertedValue; // Expected Type 'Date | null | undefined' is not assignable to type 'null'
    const D3: null = staticValue; // Error? 'Date | null | undefined' should not assignable to type 'null'
}
```

@MartinJohns It appears as if the type of the expresion used to initialize `staticValue` overrides the type of the variable, is this the expected behavior?

Should the type of the initializing value override the variable type?

If so, could anyone please point me to this in any doc, to share it with my colleagues?

**Comment by MartinJohns** [comment]
> Should the type of the initializing value override the variable type?  
> If so, could anyone please point me to this in any doc, to share it with my colleagues?

Yes, and I'm not aware of any docs that explicitly state this. But there have been numerous issues about this already.

And this is honestly the behavior **most** people would expect to happen.  
Just take the following example: 

    const value: number | null = 123;
    value.toFixed();

Should this compile and work (current behavior, assigned type *wins*), or should this result in an error because `value` might be `null`, even tho the compiler **clearly** sees that it always has a `number` assigned (the behavior you expect)?

**Comment by gabrielurbina** [comment]
Perfect, now it makes sense 👍 

One more question, since this is the expected behavior, is there I way me or someone could add this to [Variable Declaration](https://www.typescriptlang.org/docs/handbook/variable-declarations.html)

**Comment by MartinJohns** [comment]
> is there I way me or someone could add this to Variable Declaration

Scroll to the bottom of the page and you will see:

![image](https://user-images.githubusercontent.com/5269069/124465503-cdf23400-dd95-11eb-837d-b1b70759dc53.png)

**Comment by gabrielurbina** [comment]
Thanks 👍
