### ISSUE TITLE
type inference is too broad and does not match all usages of class generic argument

### ISSUE THREAD

**Issue by Feirell** [microsoft/TypeScript#44900]
# Bug Report

I am really sorry if this is a duplicate, I tried to search my way through the issues but really could not identify issues which were already concerning this problem or were already addressing a possible misunderstanding on my side.

This might not even be an bug but I could not find corresponding information which makes it clear why the inferred type is broader than the available implementations.

### 🔎 Search Terms

generic type inference extends

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type inference and polymorphism

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=35&ssc=1&pln=43&pc=3#code/MYGwhgzhAEDKCuAHApgJwMLigHgCoE8UA+aAbwChorpF4AjEAS2GgFtkAXACwHsATAIIAKMKgDmALmgEUASikA3Hoz5loAX3KVqtBszadefAEIjxUmcnnQlKtZs3lQkGAHkFaAO6pGHRgDsxTBdoZAAPDmR-PhgEFAwsCGx-eFY6NBIKahp6JhZ2bn5TUUloFLS0aAAfaAgOH0DrW1VSDXJHAHoO6AB1LjAOWt54EFV+xBR-CS1gHn866AC69B5UVGRgQYBeMuRPaHcvHz9A4KghWQBuciWOFbWNjgA6AqNhACJIuver6C7pWAAJgAzAAWACsUgE4lSUUGPAAZtAOIRkNAAOR1BpidGLGD+HiDFyMMT+MAMNEcHg0URgAqVRHI1EY8rpVDop5acj-ACiYTpiBAaIEUgAqtBPIwQCBoOlavUAmJqmVUmzZfBBhBhqNZWjWWgtAj4P5Now5rUeOwAGLG4DYUVEMylOJoM5JB2yMjaKjrDjwVD+aAla6OWbzQa3ATQHYQS3IG0moS3e7rTZXG7hgQvQz8D5fDg-S5-bqwbWqAmDOWIHhQRgU9WDSywYA+RBEqCw1TcAbQcWMGBYxXK-WoLS8-msQVo4xSQ6oby+RWWPHy7HD1WVOgaoY8EaqOUjrQolDQADinEs2AAaiQdlfQhEojE4EhXYlsAEEZVcCQAPzSaApH8ZAPFQa5yGPNE5wXE4xGXHZzw4S9oOORU3SIa4wwWW4ZxfeI3WwFDF0CSxb12fYiNgt0LnAnDs0KQQhE+ZBvl+f5S13HUK11GgawgOshQbaRUWbVt2wgTtkX6QZKKXZl+1XIcakPMdulwLgFIgZBkFYGAqQlVYAGshL4HgWLKQlFkDMBpWgYBIBY7kAConESA5QJgtC3PCSJoliV8EhcZIN1QTJvRyPR8hzEwnSkQdGkUZQ+GubJdDyAwGOKcwVQqVAmiSlKdFyfRXiKWKcrVGp4rEfK7FaBxyCcjogA)

### 💻 Code

```ts
class SuperClass<Type> {
    public methodA(arg: Type): void { }

    public methodB(arg: Type): void { }
}

class OverwritingClass extends SuperClass<number> {
    public methodB(arg: number | string): void { }
}

// What should happen:

const instCorrect = new OverwritingClass();
instCorrect.methodA("test"); // TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.


// Example A: U will be string | number but should be number

function someFunc<U>(arg: SuperClass<U>) {
    return arg;
}

const instA = someFunc(instCorrect);
instA.methodA("test"); // Should not be possible but TypeScript assumed that U is string | number

// Example B: OverwritingType is string | number but should be number

type GetType<V> = V extends SuperClass<infer T> ? T : never;

type OverwritingType = GetType<OverwritingClass>;
const instB: SuperClass<OverwritingType> = new OverwritingClass();

instB.methodA("test"); // Should not be possible but TypeScript assumed that OverwritingType is string | number


// This seems to work but does not in all cases
/*
class OverwritingClass extends SuperClass<number> {
    public methodB(arg: string): void;
    public methodB(arg: number): void;
    public methodB(arg: number | string): void { }
}
*/
```

### 🙁 Actual behavior

The inferred type is too broad and assumes all other signatures are matching to the broadest one.

### 🙂 Expected behavior

The inferred Type should be the broadest possible intersection of all signatures where `Type` is used so it should be `number` in the example. Type checking should prohibit the usage of the `string` value in a method which has no signature to accept it.

**Comment by RyanCavanaugh** [comment]
This is the correct behavior, because functions declared as methods are bivariant.

You can see the "expected" behavior in non-method syntax:
```ts
class SuperClass<Type> {
    methodA = (arg: Type): void => { }
    methodB = (arg: Type): void => { }
}

class OverwritingClass extends SuperClass<number> {
    methodB = (arg: number | string): void => { }
}
```

**Comment by Feirell** [comment]
For whoever has found this issue and had the same problem.

I am quite astonished, I had never noticed this behavior:

[Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKIA84FsAOAbCAHgBUBPHCAPmQG8AoZR5LCMACwHsATAQQAo4UAOYAuZGQoBKMQDcOwLgG46DJi3bcAQgOFiJEacjkLlqxus5cAwjtHjyB2fKV0AvitCRYiFAHkZ0ADuUMBgoEIAymBQAK4IYDFQKPRMzKyW-IJ2IDFYAEbQhsYuZmkaXNpZYgDO0eFFzqapFtw2Vch5HBwEcCANJm4qAPRDyP5BIWEgQvrIwNXIHDDIYA7IOfnQyAA+yLUh0zsdXT0gdKsUYwFQwaHhswC8VxN301Gx8YkoEOiQIFwLDDYfBEUAwLbEagAfnEyDEIAg11MXAgCDwghQCA4IFqcxxYF6SDE4xuk3C7ziCSSyix+KMcDwMQgYiBuAIhA2BSgR324SOnW6EF61CeoFqhIgiiAA)
```ts
interface Example<Type> {
    methodA(arg: Type): void;

    methodB(arg: Type): void;

    methodC(arg: Type): void;
}

interface OverwritingStructure {
    methodA(arg: number): void;

    methodB(arg: string): void;

    methodC(arg: boolean): void;
}

// OverwritingType is of type number | string | boolean
type OverwritingType = OverwritingStructure extends Example<infer T> ? T : never;

declare const instance: OverwritingStructure;
const value: Example<number | string | boolean> = instance;
```

I was always under the impression that TypeScript would try to get the intersection of the types `number`, `string` and `boolean` , which in this case would result in `never`, which were used in places for the `Type` variable but it seems like it uses the union of those types since `OverwritingType` is resolved to `number | string | boolean`.

If you want to know why this happens have a look at [this article for the problem and the terminology](https://www.stephanboyer.com/post/132/what-are-covariance-and-contravariance) and then [the FAQ for the TypeScript specific reasoning](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant).

This gave me a slight idea on why this happens, but I am still not 100% understanding why TypeScript inferred the `Type` to be the union of all usages instead of the intersection which seemed more reasonable. But it is enough that I understood that this is not a bug.

### my "solution"

If you really need to get the generic type and not the superposed type, then you could do it like this.

The solution for me was to attach a another property onto the super class like so:

[Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDKCuAHApgJwMLigHgCoE8UA+aAbwChzpoB6AKjqurugJVmFQEtEAXaAPYA7EPmiJUAlKl5jeA8amQA3ZEP68AFsmiQIXAOZCAtmv4CAZtCHDoFrr15chB6M4i8wQ4MggA6JmhGaiDoAAFDGyVAljDNLgATBLUY8OdeNCEwEBiaJmTQMCVxeAAjEC5gaCUwBOFRVgBNAAUAUQB9ZoBJADlmgHle3AAuVkJkAG5KalMtAQSAQQAKIoNRtmQASlHlAUSyaABfaehZzXmAIRXUNbGUbehd-dIj8mPyQqhoVoAPDKEEs4DJg9NBkH81AkYAhpCCcEJ4MZSmgiBQZsg5gkrqtRgikWhoAAfaAebguB5PBIHY7vGg0aALAFuKz4ATwazIZBU+TVDHcVTQLQ6DbDSgFcDFYDCDxuIQeLw+Ua-f6AlxwiBTch01jaWXy7zIADiajQlQ2bhgeORqF0TIA7sIAOT8YCaLwGHQ8q0E4mkoHkWQoPWeA3GoSm4DmgC80CWgeQlmDCq2AG1HbgWh1un1Bj1cI6ALqayjarpWO1eDQKD0aXXmiySYy6cRFMCzNCigPjaDG3hhjbYLpy3gkGNDmXglXQpBodXYLz4EgAfmg494aYzbU6vQGQ0L0FxKjQmvFRR0Fng3ictiUfbUA7XyYANHcdJPITBe-3xoPh8miEQ1y3I+BoPBsmrargurxoIVi3vAqBCAAatk8A6PK+CWoi1q2lSDpCM60Cuu6noKN6Nq+rwZIGB80r8PBiEoSAaHQDGt7figSzuCGPibJqQA)
```ts
class SuperClass<Type> {

  /**
   * TypeScript only property to prevent the assignment of non fitting instances.
   *
   * @ignore
   * @hidden
   * @internal
   */
  declare public readonly TYPE_PINPOINT: Type;

  methodA(arg: Type): void { }

  methodB(arg: Type): void { }
}

class ExtendingClass extends SuperClass<number>{
  methodB(arg: number | string): void { }
}

// And if you need to retrive the Type:

declare const instance: ExtendingClass;

// The instanceGenericType is number and won't change to number | string
type instanceGenericType = (typeof instance)['TYPE_PINPOINT'];



// If want to get the Type from a parameter:

type GetGenType<Inst> = Inst extends SuperClass<any> ? Inst['TYPE_PINPOINT'] : never;

declare function retGenType<Instance, Type extends GetGenType<Instance>>(arg: Instance): Type;

// The type of returnValue stays number and won't change to number | string
const returnValue = retGenType(instance);
```

`TYPE_PINPOINT` is just fully synthetic property but is enough that I can get the `Type` property used in the generic. Just have the convention that no extending the class modifies this property without explicit intend to change the generic type.

**Comment by fatcerberus** [comment]
> This gave me a slight idea on why this happens, but I am still not 100% understanding why TypeScript inferred the Type to be the union of all usages instead of the intersection which seemed more reasonable.

Contravariance turns unions into intersections and vice versa.  While method types are checked for *assignability* bivariantly, contravariance still applies w.r.t. type inference, which is how [`UnionToIntersection`](https://fettblog.eu/typescript-union-to-intersection/) works (i.e. convert a union into a union-of-functions, then infer the type of its parameter).
