### ISSUE TITLE
Conditional type turns union into intersection 

### ISSUE THREAD

**Issue by calevio** [microsoft/TypeScript#44907]
# Bug Report

### 🕗 Version & Regression Information

Version 4.3.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `conditional types`

### ⏯ Playground Link

[link](https://www.typescriptlang.org/play?ts=4.3.5#code/C4TwDgpgBAwg9gOwCYEtgsQQwDYBVwQA8uAfFALxS5QQAewEyAzlAK7IQBmKCESUAfigAKAJQUyANzgp+ALhGScrCAtzjyUmUgDcAWABQhngwBOnTAGNo8ZGgwIc+SACUIwVqYTEyAb0NQgVCWiKjoWNgAYuyW4QgKtmEOTgQ++gYAvoaGnDFxUAAKEOZwpgC2TACCsQ5MxBRsHNy8SCRiCaH2Ec4Qbh5ePlD+BkFQpu6eCEMBo0EhdnE40Qg1iD7CStgqAmrivlAA9ABUUEhwUExwZe4AFjwA5lBHB1kjQa+vhscnAO6lANYsEKmcaxbAgKA-NA3RpILg8PhPA6GeZMYBQKz5ShFErlKqrBBMMTpTEOAB08ySEWWBLE2QM30hAKBpVBwHBkOhUAQrDKACNikiUYg0RiCbg-g0cZxShVqnE6jz+cU2qISeK-hTOosonkHMIAEyiekmYoWaxQSrYMA3TDTN6BBhogqmOCQUygBRKgWmdKfAym8xWaAAIVMmGk9tGcGAN2KuAgztd7s93N5Pr99MZfPGmEBjQcUFAkCFBlR6NJiFwN3G0GxZtl+IVhCtNrtAB8oGGI3BVYZKwhq7WtQtkrqVnFhPsncAXW7iqmDVAMsajAYgA)

### 💻 Code

```ts
type ConditionalType<T> = T extends undefined ? () => void : (value: T) => void;

interface ConditionalTypeReturn<T> {
    conditionalFunction: ConditionalType<T>;
}

function PerformsActions<T = undefined>(): ConditionalTypeReturn<T> {
    return {
        conditionalFunction<T>(value?: T) { /* do something */}
    }
}

/** works correctly with undefined */
const action = PerformsActions();
action.conditionalFunction()

/** works correctly with number */
const actionTwo = PerformsActions<number>();
actionTwo.conditionalFunction(2)

interface Alpha {
    testProperty: number;
}

interface Bravo {
    otherTestProperty: number;
}

/** breaks union type */
const actionThree = PerformsActions<Alpha | Bravo>()
actionThree.conditionalFunction({ testProperty: 2 })


```

### 🙁 Actual behavior

The `conditionalFunction` argument is Alpha & Bravo

### 🙂 Expected behavior

The `conditionalfunction` argument to be Alpha | Bravo

**Comment by whzx5byb** [comment]
This is working as intended. See https://github.com/microsoft/TypeScript/issues/35819.

**Comment by calevio** [comment]
It's not ideal, but I get it.
