### ISSUE TITLE
Type 'string | number' is not assignable to type 'never'.   Type 'string' is not assignable to type 'never'.

### ISSUE THREAD

**Issue by Azevedo-Dani** [microsoft/TypeScript#44909]
# Bug Report

### 🕗 Version & Regression Information

- Compilation error
- This is the behaviour in every version I tried. Since 3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/JYOwLgpgTgZghgYwgAgJKsgW2QbwFDKHLAAmAXMiAK6YBG0BRIcmEFAzmFKAOZ4C+ePAgD2ITsSwV0WZAF5cjQqQoBGADRLKLNsgDkwLKr0Cho8WGQwqIVfOQAKQxEzSML9cgBucADZVdGRcAbQBrCABPERg0d0wAXU9mVgpwqJigzABKeQA+RSJJEOSIePsffwhTYTEJaxAAJntkAB4AFWQIAA9IEBJ2WKxcpylkNs8KgIo2sMjoscTtFOQ0+bacuXz8QudMYJKyhUmqwSA)

### 💻 Code

```ts
interface IItem {
    id: number
    name: string
}

const item: IItem = {
    id: 1,
    name: 'item1'
}

const fun1 = (item: IItem, value: IItem[keyof IItem], name: keyof IItem) => {
    item[name] = value
}

const fun2 =  <T extends IItem>(item: T, value: T[keyof T], name: keyof T) => {
    item[name] = value
}

```

### 🙁 Actual behaviour

There's an error in `fun1`. We can't do `item[name] = value` otherwise we have the error `Type 'string | number' is not assignable to type 'never'.   Type 'string' is not assignable to type 'never'.`

But the fun2 works perfectly.

### 🙂 Expected behaviour

We should have the same behaviour in fun1 and fun2.

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/pull/30769

**Comment by RyanCavanaugh** [comment]
This is correct behavior. `fun1` would corrupt its item during a legal call:
```ts
const n: "id" | "name" = "id";
fun1(item, "item1", n);
```
