### ISSUE TITLE
TS/JS language features crashing every 5 minutes

### ISSUE THREAD

**Issue by LohitakshTrehan** [microsoft/TypeScript#44916]
Issue Type: <b>Bug</b>

Open Project in VS Code, thats it.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id 22f20271-80f3-48d7-99a0-02840fa2f05a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.6.12
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.1.23
gitlens|eam|11.5.1
prettier-vscode|esb|8.0.1
vscode-graphql|Gra|0.3.16
spaceweb-vscode-extension|Har|0.0.1
vscode-scss-formatter|sib|2.2.2
code-spell-checker|str|1.10.2
errorlens|use|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehovct:30309550
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30322307
binariesv615:30325510
vsccppwt:30329788
aatestflightcf:30331712

```

</details>

**Comment by mjbvz** [comment]
Have you tried some of the steps in https://code.visualstudio.com/docs/typescript/typescript-compiling#_working-with-large-projects?

**Comment by LohitakshTrehan** [comment]
@mjbvz yes these steps are being followed

**Comment by LohitakshTrehan** [comment]
@mjbvz I tried increasing the memory limit from default 3GB to 4GB, but still no good. Can we please check the plugin code to find any potential bottleneck

**Comment by andrewbranch** [comment]
@LohitakshTrehan please [get a TS Server log](https://github.com/microsoft/TypeScript/wiki/Getting-logs-from-TS-Server-in-VS-Code) if you can; failing that, you should at least be able to see the stack trace if you open the Output > Extension Host pane in the console. Thanks!

**Comment by LohitakshTrehan** [comment]
closing it as seems to be fixed in new version

**Comment by LohitakshTrehan** [comment]
> This isn't fixed - has been happening for as long as I can remember it has some issue with git and eslint plugins. Which makes me think that maybe it just needs to be told not to mess or check plugin directories. My best solution was to disable it so far and switch to Babel Javascript.

I changed my organisation. New one doesn’t have a mono repo Architecture (luckily).
The authors of the code are just forcing everyone to close the performance issues of the plug-in in huge mono repos. They are least bit interested in fixing the issue. Hence I closed all my issues related to this.
If they want to fix it, they can now replicate it on their own.
God Speed!

**Comment by andrewbranch** [comment]
If anyone has something actionable like a stack trace or repro steps, please open a new issue with that information.

**Comment by cmayorga** [comment]
I am unable to get it working today again after last VS Code upgrade:

The JS/TS language service immediately crashed 5 times. The service will not be restarted.
This may be caused by a plugin contributed by one of these extensions: VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode.
Please try disabling these extensions before filing an issue against VS Code.

I tried to disable all of these extension but nothing
