### ISSUE TITLE
Keyword to make a generic "whatever its requirements are."

### ISSUE THREAD

**Issue by SephReed** [microsoft/TypeScript#44918]
# Suggestion

## 🔍 Search Terms

infer generics, generic any, make generic match its requirements, auto generic

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The TS compiler knows exactly what type of generics it is willing to allow.  That type is known by the compiler, but sometimes extremely tormentful to try to recreate.

It would save unimaginable amounts of user time to be able to say: "this generic is whatever typescript thinks it must be".

## 📃 Motivating Example

```
type Foo<T extends { foo: string}> = Array<T>
type Bar<T extends { bar: string}> = Map<string, T>

class Qux<T extends auto = auto>() {
   public foo(): Foo<T> { return []; }
   public bar(): Bar<T> { return new Map(); }
}

// based off the generics which T is passed to, auto should become:
// { foo: string;  bar: string }
```

## 💻 Use Cases

1. Pretty much every single time you try to pass a generic type from one template to another, and you get an extremely complex error.

2. In general, there needs to be more "escape hatches" on generics, because they have a very bad habit of taking a project hostage if ever you try to do something complex with them.

3. Absolutely every single time the (user) error occurs of: "X meets requirements, but T could be instantiated with a bad (user error) type"

4. Seriously, just all the time.  For everything that it possibly can be used for, because wrestling generics is so rarely a satisfying or efficient use of time.

**Comment by RyanCavanaugh** [comment]
I don't know how one would reason about this. What do you propose happen if `Foo` and `Bar` were declared thusly?
```ts
type Foo<T extends { foo: string } | { qux: number }> = Array<T>;
type Bar<T extends { bar: string } | boolean> = Map<string, T>
```

**Comment by SephReed** [comment]
The type would be:

```
auto = { foo; bar; } | { qux; bar; }
```

To do it programmatically, you can just start plugging in the union of types which match Foo<T> into Bar<T> and it'll tell you what its missing:

*This one can not be resolved by any logic*
<img width="798" alt="Screen Shot 2021-07-06 at 5 04 03 PM" src="https://user-images.githubusercontent.com/14002040/124676720-ad54d780-de84-11eb-98fc-86b92a477196.png">

*This one can easily be resolved with logic*
<img width="860" alt="Screen Shot 2021-07-06 at 5 04 18 PM" src="https://user-images.githubusercontent.com/14002040/124676723-ae860480-de84-11eb-962c-c784d831c6f8.png">

**Comment by RyanCavanaugh** [comment]
I don't think this is workable given that answer -- it's combinatorially explosive in a way that actually work occur in reality

**Comment by SephReed** [comment]
If you think it's hard for a computer, imagine what it must be like for humans.

I'm sure you'll understand this: but working for a client that can't tell you what they want, but are very adamant about what they *don't* want as soon you show them it... it would be really, really nice to have the client know what they want.

Without such a feature, there is an obvious ceiling on the complexity of projects; and I've run into pretty hard on my last three.    A feature like this would clean up those projects a ton, as well as saving a bunch of time.

**Comment by tjjfvi** [comment]
> I don't know how one would reason about this. What do you propose happen if `Foo` and `Bar` were declared thusly?
> 
> ```ts
> type Foo<T extends { foo: string } | { qux: number }> = Array<T>;
> type Bar<T extends { bar: string } | boolean> = Map<string, T>
> ```

@RyanCavanaugh Wouldn't it just be the intersection, `({ foo: string } | { qux: number }) & ({ bar: string } | boolean)`?

**Comment by SephReed** [comment]
@tjjfvi Yeah, it'd be that with some cleaning up, so to simplify the polynomial:
```
({ foo } | { qux }) & ({ bar } | boolean)
({ foo } & { bar }) | ({ foo } & boolean) | ({ qux } & { bar }) | ({ qux } & boolean) 
{ foo; bar } | never | { qux; bar } | never
{ foo; bar } | { qux; bar }
```

Easy peasy.  And when it comes to really complex types, TS could far out-perform humans, which would make projects with complex generics much more fun.

I don't think the shoe of "too complex" fits here.  Doubly so because the expectation is that people should be able to do this instead?  Or maybe the projects I'm working on are the "too complex" aspect.  I've definitely noticed that TS shines much brighter on big-but-simple projects than it has with small-but-complex tools.
