### ISSUE TITLE
Awaiting a function that returns `never` or `Promise<never>` does not mark the code below as unreachable

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#44911]
# Bug Report

### 🔎 Search Terms

await, never, promise

### 🕗 Version & Regression Information

The last line starts being marked as unreachable in 3.7.x, but the others aren't in any version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwGcBPdAORADcQYAKASgC55VLqBuAKFElgRXWx54UYmVa1G8AAowcAWywEQAHhZUYAPk4cRJMEjSZc+GGnpMZ8xSoo4swDfADeHePCyJ4NDKZB1nrm7CAO5QWBjComDk6vScQSFhEVEx1HHwAPQZzDgRcrAA1iDAkfBocFBgABZQAEYQIIFuKeLpWTl5hcWl5SCVNfWNbgC+gWB4BDgNAHQQOADmNABEiDg4S3RsmdnjMHCYEETw+TBFJSJlqBXVdQ0cw0A)

### 💻 Code

```ts
declare function syncNever(): never;
declare function asyncNever(): Promise<never>;

async function run(): Promise<void> {
  if (true) {
    await asyncNever();
    await syncNever(); // not marked as unreachable
    syncNever(); // not marked as unreachable
  }
  console.log("foo"); // correctly marked as unreachable
}
```

### 🙁 Actual behavior

Only the last line is marked as unreachable.

### 🙂 Expected behavior

Expected everything after `await asyncNever();` to be marked as unreachable.

**Comment by MartinJohns** [comment]
Duplicate of #34955. Used search terms: `await never in:title`

**Comment by AlCalzone** [comment]
I swear that didn't show up 🙈
