### ISSUE TITLE
Typescript project with dotted-style project name like todo-app-3.0 failed to compile when deleting a certain file or switching between multiple branches

### ISSUE THREAD

**Issue by liuliangsir** [microsoft/TypeScript#44910]
# Bug Report

### 🕗 Version & Regression Information
- Compilation error
- A reproducible behavior in every version I tried. Since 3.8.3

### ⏯ Playground Link
[Here](https://github.com/liuliangsir/my-app-1.0) is a reproducible repository. The followings are a bunch of steps to reproduce the issue above.

- Use `Git` to clone that repository with https or ssh protocol
- Run `git checkout dvp`
- Run `npm start` npm scripts
- Run `git checkout main`

Then rename project name to `my-app` and follow the above step agin.

### 🙁 Actual behavior
Typescript compilation process crashed when Switching to another branch(`a`) from one branch(`b`). The difference between `a` and `b` is that `b` has some file but `a` not. In order to restart the process above, I need to terminate the above process and rerun some scripts.

### 🙂 Expected behavior
Typescript compilation process will not being crashed when Switching to another branch(`a`) from one branch(`b`). The difference between `a` and `b` is that `b` has some file but `a` not.

**Comment by MartinJohns** [comment]
Have you tried reproducing this issue without all the overhead, by just using the TypeScript compiler instead of webpack?

**Comment by liuliangsir** [comment]
@MartinJohns okay, I'll try

**Comment by liuliangsir** [comment]
@MartinJohns I have tried reproducing this issue with only the TypeScript compiler. Sadly, the issue above is still existing. Using only the TypeScript compiler instead of webpack in that reproducible repository is very simple.  What you need to do is follow the following steps.

- Make sure node version
- Run `git checkout dvp`
- Change noEmit option in tsconfig.json to true
- Run `npm run build:watch`
- Run git checkout main

Then rename project name to my-app and follow the above step agin.

**Comment by RyanCavanaugh** [comment]
I can't reproduce on 4.3.2. The package.json specifies 4.1 -- maybe try on a newer TS version? Otherwise please post the call stack

**Comment by liuliangsir** [comment]
@RyanCavanaugh I have already tried reproducing this issue on the latest typescript version(4.3.5). The following are a bunch of screenshots.

- Before rename

https://user-images.githubusercontent.com/8049878/124850730-c3bd7900-dfd3-11eb-9257-c9f54824e97b.mp4

- After rename

https://user-images.githubusercontent.com/8049878/124850809-e780bf00-dfd3-11eb-89fa-38384f92d9d3.mp4

**Comment by RyanCavanaugh** [comment]
I don't see a crash here, just an error? It looks like watch mode maybe fired during an intermediate state and needs retriggering.

**Comment by liuliangsir** [comment]
Instead of restarting a typescript process after killing a specified process for typescript, is there some way to work around or solve the issue above? Because throwing error too frequently is a disturbing and awful thing. @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
We don't seem to have other reports of this and this isn't a reproducible example
