### ISSUE TITLE
typescript has different types for the same variable in the same scope

### ISSUE THREAD

**Issue by eng-dibo** [microsoft/TypeScript#44921]
`value` here has two different types.
one is `string` and the other is `string | string[]`

```
function getValue(value: string | (()=>string)):void{}

function test(value: string | string[]): void{

 if(value instanceof Array){
   return
 }
 
  // commenting out this line resolve the issue, but I don't know why?
  // TS consider `value` here as string | string[], but it should be string only
  value = 'string'

  // `value` here is string
  getValue(value)

  // but here is string | string[]
  getValue(()=>value)
}
```

[play](https://www.typescriptlang.org/play?jsx=0#code/GYVwdgxgLglg9mABAcwKZQGoEMA2JUAUAbrvgFyIDOUATjGMogD6IEECUAvAHzV0Pt2ZInBgATAN4BfAFAzQkWAkRRU1YqVQU+9Rix0MA2gF0hiEeIlzEMYBryobYalkio4wRAEEaNLAE92K0QQmnQQGjAZRFlEaMQAegTECDgAWzTUMFgGRDgQKBUACxhKRBx6RzDKOBwiRygix1LKfAAaRAAjAsQASUQxBAByQoBrMDgAd0RJov8AfnikxAAVAGUUhEpxVBpEAAMSB33EJrDELDKDPSpaXRMO7sKYQsoi-JwxLsdrvLAcfzxI74RCcRBDa5DayJZKHTQnM7NK53BjxNCYTT2fDsaHLJ6nXZI278G7XExo9DYBxsLjcYGoHFSIA)

**Comment by MartinJohns** [comment]
Please respect the issue templates for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md). This will help the TypeScript team to quickly get an overview of your issue.

This is due to #9998.

**Comment by eng-dibo** [comment]
thank you @RyanCavanaugh for responding.
as you added the label "duplicate", please mention the duplicated issue !!

**Comment by nmain** [comment]
> as you added the label "duplicate", please mention the duplicated issue !!

That really is #9998.
