### ISSUE TITLE
Export * for interfaces generates redundant JS

### ISSUE THREAD

**Issue by Koloto** [Microsoft/TypeScript#4492]
I have a file`interfaces.d.ts` which defines some interfaces, e.g:
```ts
export interface IFoo {}
export interface IBar {}
```
I want to reexport all interfaces in another module:
```ts
export * from "interfaces";
```
When targeting AMD, compiled code looks like this:
```js
define(["require", "exports", "interfaces"], function (require, exports, interfaces_1) {
    function __export(m) {
        for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
    }
    __export(interfaces_1);
});
```
Module "interfaces" should not be imported at all, because it doesn't contain any JS code. To fix this I have to list all exported interfaces manually:
```ts
export { IFoo, IBar } from "interfaces";
```
It's a problem if the number of interfaces is large.

I use version 1.5.3.

**Comment by matthewjh** [comment]
Just curious as to why it's a problem if the number of interfaces are large, given that interfaces have no runtime representation?

**Comment by Koloto** [comment]
@matthewjh It's not a problem of performance at runtime. It's a problem of development. We convert old JS code to TS and actively add new types and interfaces. So the number of interfaces changes frequently and it's not very good idea to support them in two places.
