### ISSUE TITLE
DeprecationWarning: in testRunner 

### ISSUE THREAD

**Issue by Luxcium** [microsoft/TypeScript#44922]
# Bug Report

### 🔎 Search Terms

Mocha, Runner

### 🕗 Version & Regression Information

on the branch, [main](https://github.com/microsoft/TypeScript/blob/1de29af70922dc38218936f8acd246a94207acc1/src/testRunner/parallel/worker.ts#L212) with mocha out of sync with is definition  9.0.2/8.2

### 💻 Code
running `npm test` in main branch  

### 🙁 Actual behavior
`[Worker XX] (node:386YYY) DeprecationWarning: "Runner(suite: Suite, delay: boolean)" is deprecated. Use "Runner(suite: Suite, {delay: boolean})" instead.
(Use 'node --trace-deprecation ...' to show where the warning was created)`
![Screenshot_20210707_060054](https://user-images.githubusercontent.com/42672814/124742116-68fc2280-deea-11eb-91c3-f0923392f1ce.png)

### 🙂 Expected behavior
![Screenshot_20210707_060637](https://user-images.githubusercontent.com/42672814/124741279-84b2f900-dee9-11eb-8f5d-9d396308920d.png)

* [X] Code is up-to-date with the `main` branch
* [X] Successfully run `gulp runtests` locally
* [X] Successfully run gulp tests & gulp runtests-parallel --light=false locally
* [X]  ~~fixed by #44923~~
* [X]  fixed by #44925

**Comment by Luxcium** [comment]
[In Mocha the constructor was updated here](https://github.com/mochajs/mocha/commit/fbe3ce4f7d5c27fec3fa1e32ee86b23b169e02d2#diff-37b88258822cb207e2caa1a88d4fbc057924da72c5580d1f39b78349214ab622R129)

**Comment by jakebailey** [comment]
This was fixed in #46160.
