### ISSUE TITLE
Generic function parameters not narrowing properly

### ISSUE THREAD

**Issue by EnderShadow8** [microsoft/TypeScript#44937]
# Bug Report

### 🔎 Search Terms

generic function narrow narrowing parameters

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics and narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/GYVwdgxgLglg9mABMAFADwFyIIICdcCGAngMIIDOUuI0cuiAPogWEQNoC6AlIgN4BQiIYhiooRAA4BTOMERpEAXmWIARKEiwEqngOH7EYKQHd5KLoOEBffjf4bo8JMABMAHgAqiKWihSwACbkOPjEZGCU1LT0TCzsHAB86FgeupZCoiji0rLySirq4I7aaQbCRqZo5umINjZAA)

### 💻 Code

```ts
function f(x: ArrayConstructor | any[]) {
    if(typeof x === "function") {
        new x() // Works as intended
    }
}

function f2<T extends ArrayConstructor | any[]>(x: T) {
    if(typeof x === "function") {
        new x() // Error!
    }
}
```

### 🙁 Actual behavior

In `f2`, `T` was not narrowed to `ArrayConstructor`, while in `f`, it was, despite both functions being identical apart from `f2` using a generic type.

### 🙂 Expected behavior

In `f2`, `T` is narrowed to `ArrayConstructor` using the `typeof` type guard.

**Comment by RyanCavanaugh** [comment]
Generic narrowing is fairly conservative. In this case it's possible that `T` is instantiated to a type that both has `function` as its typeof *and* structurally matches an array (this is weird but possible), so narrowing to the constructor type isn't safe.

**Comment by fatcerberus** [comment]
Doesn’t that apply to the non-generic union too, though?
