### ISSUE TITLE
JSON parse works with type Buffer

### ISSUE THREAD

**Issue by KristianRykkje** [microsoft/TypeScript#44944]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition
`parse(text: string, reviver?: (this: any, key: string, value: any) => any): any;`

## Sample Code
`const object = JSON.parse(readFileSync("sample.json"));`

## Documentation Link
https://262.ecma-international.org/5.1/#sec-15.12.2
https://github.com/nodejs/node/blob/c41c09375b217d9daec614edb590147b14ff9b21/lib/buffer.js#L405

## Suggestion
`parse(text: string | Buffer, reviver?: (this: any, key: string, value: any) => any): any;`

**Comment by IllusionMH** [comment]
Same as #17203 and moreover `Buffer` is Node specific type and doesn't looks like it belongs to standard lib files.

**Comment by RyanCavanaugh** [comment]
This is just an implicit coercion, not anything `JSON.parse` does.

**Comment by RyanCavanaugh** [comment]
If you have a raw `Buffer` you don't know if it's UTF-8, UTF-16, base64, etc.. Arguably the entire point of TS is to tell you when you're making assumptions like that.
```ts
const b = Buffer.from("{}", "utf-16le");
JSON.parse(b); // throws
```
