### ISSUE TITLE
"Extract to method in class" in angular template not working correctly

### ISSUE THREAD

**Issue by stefanrybacki** [microsoft/TypeScript#44943]
Also see: 
https://github.com/angular/vscode-ng-language-service/issues/533
https://github.com/microsoft/vscode-typescript-next/issues/18

**Describe the bug**

"Extract to method in class" ability doesn't seem to behave correctly on a inline template function call. In below

**To Reproduce**

see GIF for clear reproduction. the inline template is missing the function addChildElement and is listed correctly. Using the autosuggested 'extract method' call in context menu removes the whole template properly and swaps it with a templateURL one, with a weird function call.

![image](https://user-images.githubusercontent.com/9585787/71540948-89116400-298c-11ea-918f-641ecfa621b0.gif)

**Expected**

A correctly named method in the class is generated and the template stays untouched.

**Comment by RyanCavanaugh** [comment]
Please include code to reproduce this in text format; we are not able to transcribe screenshots.
