### ISSUE TITLE
Statements in class static blocks do not narrow types

### ISSUE THREAD

**Issue by AumyF** [microsoft/TypeScript#44949]
# Bug Report

### 🔎 Search Terms

control flow analysis, class static blocks

### 🕗 Version & Regression Information

- v4.4.0-beta
- v4.4.0-dev.20210708
- This is the behavior in every version I tried, and I reviewed the [proposal](https://github.com/tc39/proposal-class-static-block/blob/main/README.md)
- I was unable to test this on prior versions because class static blocks were added in 4.4.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210708#code/DYUwLgBAZg9jBcEB2BXAtgIxAJwNwFgAoIgY2AEMBnSiAYQgG8iIJKxywBLEx5l6OBAC8EAMwFCLAL5EZxeSRhJKMUADpgMAOYAKWDACUEoA)

### 💻 Code

```ts
let foo: number;

class C {
  static {
    foo = 3;
  }
}

console.log(foo);
```

### 🙁 Actual behavior

An error `Variable 'foo' is used before being assigned.(2454)` occurs at line 10, `console.log(foo)`.

### 🙂 Expected behavior

Code compiles without errors.

**Comment by tchetwin** [comment]
I accidentally duplicated this in #45023. Carrying over a point from there:

"Side effects" in initialization of static fields already behaved similarly (since ~forever):

```typescript
let c: number;
class C {
  static f = (c = 10);
}
c; // Variable 'c' is used before being assigned.(2454)
```

**Comment by fwienber** [comment]
What about this even simpler case:
````
class Foo {
    static {
        Foo.doSomething(); // Error: "Property 'doSomething' is used before its initialization.(2729)"
    }

    // this is how Babel rewrites the above:
    static #_ = (() => {
        Foo.doSomething(); // Now, the forward reference is allowed!
    })();

    static doSomething(): void {
       console.log("gotcha!");
    }
}
`````
[This code on TypeScript Playground](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210910#code/MYGwhgzhAEBiD29oG8BQ0PQgFzNglsCupqQvAHQAm8AyvALYCm2AFvgHYDmAFAJQBuEhgC+qYVlwEiAYgD60ALzQe-JQD5ipMomp1GLdt35DSIvifGkceQtBr1mbTrz4AuaADd4+Klu3QwPAcEPAgTBQg8LwARFzw2MCsYACEMYISYmJAA)
Are class static blocks supposed to be more strict in this regard?
The Babel rewrite for class static blocks is to define an unused, #private static variable whose initializer is a self-evaluating arrow function. Using the rewrite, TypeScript does not complain about the forward reference.
At runtime, both variants work.
It seems to me that the TypeScript error should not be raised in this case.
Is this the same problem as above or should I create a separate issue?

**Comment by Zzzen** [comment]
I believe that's a separate issue.
