### ISSUE TITLE
This condition will always return true since this function is always defined. Did you mean to call it instead?

### ISSUE THREAD

**Issue by ScriptType** [microsoft/TypeScript#44948]
TypeScript Version: 4.3.5

Code:
```typescript
class foo {
    bar!: (a: string,b: number) => void;

    someFunction() {
        if(this.bar){

        }
    }
}
```
Gives an Error Message "This condition will always return true since the function is always defined"

```typescript
class foo {
    bar!: (a: string,b: number) => void;

    someFunction() {
        if(this.bar){
           consol.log(this.bar)
        }
    }
}
```
with the console.log(this.bar) it doesnt give an error Message

Expected behavior:
if(this.bar) 
should work without any Issues becaus the this.bar could be defined at a later Stage.

Actual behavior:
The message This condition will always return true since the function is always defined is allways showing
https://www.typescriptlang.org/play?#code/MYGwhgzhAEBmD29oG8CwAoaXoCMwCcBCALmgAoxSIAXfASwDsBzAGh1IYFcBbHAU3wBKaAF4AfNABu8OgBMA3BgzZoEeNz4AxTg2DU68BmWFpMK7HVhlqACzoQAdHiGnz2AL7KPGd0A

**Comment by MartinJohns** [comment]
> should work without any Issues becaus the this.bar could be defined at a later Stage.

But according to the type it is **always** defined, so checking for falsy values does not make sense, even if it gets redefined later on.

You have the choice to either:

- Disable `strictNullChecks`.
- Make the property **optional**.
- Change the type to a union including `undefined`.

**Comment by ScriptType** [comment]
> > should work without any Issues becaus the this.bar could be defined at a later Stage.
> 
> But according to the type it is **always** defined, so checking for falsy values does not make sense, even if it gets redefined later on.
> 
> You have the choice to either:
> 
> * Disable `strictNullChecks`.
> * Make the property **optional**.
> * Change the type to a union including `undefined`.
But its not consistent

```typescript
class foo {
    bar!: (a: string,b: number) => void;

    someFunction() {
        if(this.bar){
           consol.log(this.bar)
        }
    }
}
```
is working for example

**Comment by RyanCavanaugh** [comment]
This is the intended behavior, on all counts:

 * If you test a value that doesn't seem like it should ever be falsy, because it's a function, that's considered a likely forgot-to-call error
   * If you test it *then call it*, then the "forgot to call it" part doesn't make sense, so it's not an erro
 * `{}` is not a necessarily-truthy value.

**Comment by DE-Danloc** [comment]
> This is the intended behavior, on all counts:
> 
> * If you test a value that doesn't seem like it should ever be falsy, because it's a function, that's considered a likely forgot-to-call error

There is no error or hint that tells something about "forgot to call". The error messages clearly says "This condition will always return true" and this is not the case.

> If you test it then call it, then the "forgot to call it" part doesn't make sense, so it's not an erro

I get the point and agree with you if there were some hint about "forgot to call" but with `"strictPropertyInitialization": false` the advise that this check will never be false is much more misleading.

Can't image how this could be Working as Intended.

**Comment by fatcerberus** [comment]
Except according to the type of `bar`, it *will* always be truthy (under `strictNullChecks`). The fact that you’ve overridden the type checker with `!` is immaterial—according to the type annotations, `bar` can never be falsy so the error is correct.
