### ISSUE TITLE
Missing excess property errors when assigning to intersection

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#44942]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about excess property checking

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/C4TwDgpgBACgTgezAZygXigbygMwQgLimWDgEsA7AcygF8BuAKEdEigBEIBbBdLRqIKhhEKIvCTImtKADJ+Q4aOTjl0pi3DQAwggA2eiAGNgZBBT6YBQgCbdCHe9LkLb9opx7rmR8ySjAAIxEugbGpuaW1oJ2PERWiooikvHRiYp4DgDkmVkANGnpggBGAIZwRIF5UAD0NVAQAB6QJhA2DXCIcFA2AK7QwLxNRhDIqMlg1cW9wFBUCLMU5hCFQrQFiuuMDEA)

### 💻 Code

```ts
type Props = { foo: string };

type Demo = {
    props: Props;
} & {
    props: Props;
};

type Collection = {
    demo: Demo;
} & {
    demo: Demo;
};

const t1: Collection = {
    demo: {
        props: {
            foo: 'foo',
            bar: 1, // expected error due to excess prop, but got none ❌
        },
    },
};
```

If we remove one of the intersections, excess property checks kick in again.

This is clearly a contrived example however I have reduced it from a much more complicated example where we do actually need to use intersections in a similar way. I can elaborate if needed.

I have been able to workaround the issue using this `Compact` helper:

```ts
type Compact<A> = A extends Function ? A : { [K in keyof A]: A[K] } & {};

type Collection = Compact<{
    demo: Demo;
} & {
    demo: Demo;
}>;
```

### 🙁 Actual behavior

See comment in code above.

### 🙂 Expected behavior

See comment in code above.

**Comment by Andarist** [comment]
This was fixed in 4.9, likely by https://github.com/microsoft/TypeScript/pull/51140 (`4.9.0-dev.20221014` is the first one to report the correct error)
