### ISSUE TITLE
TS functionality keeps dying on large project

### ISSUE THREAD

**Issue by Abdelhady** [microsoft/TypeScript#44951]
Issue Type: <b>Bug</b>

VSCode keeps trying to "Initializing JS/TS language features", but fails consistently

I'm working on a large backend typescript project in Amazon though

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 15, 23|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id ff3e41e0-a3a4-4dad-a1e8-0e6d71d3b908|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
gitlens|eam|11.4.1
vscode-graphql|Gra|0.3.16
dotenv|mik|1.0.1
vscode-docker|ms-|1.13.0
remote-containers|ms-|0.177.2
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805:30301674
binariesv517:30312825

```

</details>

**Comment by Abdelhady** [comment]
I noticed also something .. 

even with the default `maxTsServerMemory`, I can work normally without having this issue until I open a JS file,

Opening one JS file, no matter how small it is, it will make it highly likely for VSCode to have this issue.

**Comment by byron70** [comment]
I was having this very similar issue in a remote devcontainer setup with docker on a somewhat larger project. I changed this setting `"typescript.tsserver.maxTsServerMemory": 8000` from the default and it seemed to help a bit, and it doesn't appear the tsserver process uses anywhere near that amount. The container only seems to report about 2GB of usage and `top` (in the container) shows usage at 40% for the tsserver process, so maybe really using around 1GB, which seems excessive.

**Comment by chrisvdp** [comment]
I am having the same issue with a large monorepo that I am working in. For context, our root tsconfig.json has about 110 references.

I have tried opening the project in the latest insider build with no extensions and see the same thing. When I opened it in insiders I did get a macOS crash report for an electron SIGABRT. I can send it to possibly @RyanCavanaugh.

<details>
  <summary>System Info</summary>
    Version: 1.66.0-insider (Universal)
    Commit: db0525ff4ba814780e901a5b9e399aaf596b9b20
    Date: 2022-03-17T05:18:05.656Z
    Electron: 17.1.1
    Chromium: 98.0.4758.109
    Node.js: 16.13.0
    V8: 9.8.177.11-electron.0
    OS: Darwin arm64 21.4.0
</details>

**Comment by Pickleboyonline** [comment]
Same issue here with a very large project. I have the same issue @Abdelhady has, when I open a JS file it increases the chance of the infinite TS server restarting to occur.

**Comment by valentinbeggi** [comment]
Same issue here, typescript goes out of memory on a multi package monorepo.
Event when increasing memory to 8gb Typescript will eventually die.
Project references are correctly used.. 🥲

**Comment by zen0wu** [comment]
I stumped on this problem and I believe the root cause is here: https://github.com/microsoft/vscode/issues/127105

It has nothing to do with TypeScript but rather vscode is running tsserver with an inherent memory from electron and it cannot be changed 😠

**Comment by Pokruk** [comment]
> I stumped on this problem and I believe the root cause is here: [microsoft/vscode#127105](https://github.com/microsoft/vscode/issues/127105)
> 
> It has nothing to do with TypeScript but rather vscode is running tsserver with an inherent memory from electron and it cannot be changed 😠

Why is this issue still open if the problem is just the vscode and not the ts itself, lol

**Comment by RyanCavanaugh** [comment]
We implemented https://github.com/microsoft/vscode/pull/191019 so you can now run tsserver under `node`, which has effectively unlimited memory if provided the right flags.
