### ISSUE TITLE
For checkJS, error when JSDoc `@see` tag text starts with `[`

### ISSUE THREAD

**Issue by jaydenseric** [microsoft/TypeScript#44958]
# Bug Report

In a JS file with TS checking enabled, JSDoc `@see` tag text content that begins with `[` (e.g. when the text content is a markdown link) incorrectly results in a TS error `Identifier expected.` at the `[`.

### 🔎 Search Terms

```
jsdoc @see tag Identifier expected
```

### 🕗 Version & Regression Information

Error seen in v4.1.5 and v4.3.5; probably the bug exists in every version so far that parses JSDoc `@see` tags.

### ⏯ Playground Link

```ts repro
// @checkJs
// @filename: a.js

/**
 * @see [TypeScript docs](https://www.typescriptlang.org/docs).
 */
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?checkJs=true&ts=4.3.5&ssl=6&ssc=4&pln=1&pc=1#code/PTAEAEGMAsFNINYCkDOBYAUCCAzAlgDawB2AhgLawBcopAdAFboabABUbmobEKssoANoAVAJ4AHWAGVIAJzziALqAAmAe0goAugApoixeJRUQAd3N1FE2CjkLFBUsQDmdNbOfB1mgJR0ubMBAA)

### 💻 Code

In `a.js`:

```js
// @ts-check

/**
 * @see [TypeScript docs](https://www.typescriptlang.org/docs).
 */
```

### 🙁 Actual behavior

TS error `Identifier expected.` at the opening `[` of the JSDoc `@see` tag markdown text.

### 🙂 Expected behavior

No TS error.

**Comment by jaydenseric** [comment]
What's funny is that even with the TS errors, VSCode can still render such `@see` tag markdown correctly in tooltips:

<img width="663" alt="Screen Shot 2021-07-09 at 6 11 35 pm" src="https://user-images.githubusercontent.com/1754873/125046427-58fa6380-e0e1-11eb-92df-2ff4888b59dd.png">

**Comment by Kingwl** [comment]
I guess it's should fallback to raw comments here? /cc: @sandersn 

> What's funny is that

Markdown render is provided by vscode. And the diagnostic is provided by TypeScript.

**Comment by sandersn** [comment]
Note that checkJS is the only mode that shows jsdoc parse errors because in that mode we assume you want to write correct tags. However, markdown links should count as 'correct' for `@see`.
