### ISSUE TITLE
Class generics ignored in extends-check

### ISSUE THREAD

**Issue by jeengbe** [microsoft/TypeScript#44952]
# Bug Report

### 🔎 Search Terms

class, generics, extends

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210708#code/MYGwhgzhAEpgXvAPAIQHzQN7QL4FgAoQgFwE8AHAU2gBNKAjAVwHNoBeaACk0OmgDtKAd04BKAFyxwiJJnqSARPQU40hHKOiUAHsUr8aMQUK6a2GODMxhFYFRgD80BcQBOjSgsUAzMCAieQA)

### 💻 Code

```ts
class clazz<B> { }

type debug = ({
  new(): clazz<{b: "b"}>
}) extends new () => clazz<{a: "a"}> ? "true": "false" // 'true'
```

### 🙁 Actual behavior

Type `debug` evaluates to `"true"`, although it is not supposed to, as `clazz<{b: "b"}>` and `class<{a: "a"}>` are clearly not the same. The information in generics seems to be lost while checking.

### 🙂 Expected behavior

The described behaviour should not happen, as generics for both classes are not compatible with each other.

**Comment by whzx5byb** [comment]
> In general, you should never have type parameters which are unused. The type will have unexpected compatibility (as shown here) and will also fail to have proper generic type inference in function calls.

See [the wiki](https://github.com/microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--).

It works if the type parameter `B` is used.
```ts
class clazz<B> { foo!: B }

type debug = ({
  new(): clazz<{b: "b"}>
}) extends new () => clazz<{a: "a"}> ? "true": "false" // 'false'
```

**Comment by jeengbe** [comment]
Thank you for your answer.
I did really not expect this to be intended.
