### ISSUE TITLE
Convert unit tests in 'convertCompilerOptionsFromJson' to use baselines

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#44950]
Some of the unit tests in `convertCompilerOptionsFromJson.ts` have long lines that are difficult to edit as the message text increases in size:

https://github.com/microsoft/TypeScript/blob/2a01f923caf06b011dbd0d6b0cb1ccc0d5a0f092/src/testRunner/unittests/config/convertCompilerOptionsFromJson.ts#L298

We should consider changing these tests to use baselines/snapshots instead of inline code.

**Comment by jakebailey** [comment]
This was done in #53324.
