### ISSUE TITLE
Have Ctrl+] to move between //#region/endregion in TypeScript

### ISSUE THREAD

**Issue by maxima120** [microsoft/TypeScript#44963]
Thank you for implementing #regions in TypeScript. Now the only missing part is a key shortcut in VisualStudio 2019 to move between region and endregion - currently its Ctrl+] in C# but it doesnt work in TypeScript.

Please add this

**Comment by uniqueiniquity** [comment]
Hi @maxima120, thanks for the suggestion!
Could you please report this request via the [Suggest a Feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019) functionality in Visual Studio 2019? We'll best be able to track your request that way.

**Comment by maxima120** [comment]
last time I suggested a feature I was directed here.. so just you know..
