### ISSUE TITLE
TypeScript doesn't show type checking error in the parameter decorator

### ISSUE THREAD

**Issue by aristocr2t** [microsoft/TypeScript#44965]
# Bug Report

Its very helpful feature, but it doesn't work... see Playground Link

### 🕗 Version & Regression Information

I use the latest (4.3.5) version of TypeScript.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAUwHgDg9gTgLgAjgTwiBAVVIAmBZEOACyhwBEQBjWAQzlgB4A1BAXgRoDtkA+NhBsAQIA8gnBwQnHAGcEAJSqwcDANIAaBAAoAbjQA2AVxAAuBEwCUbPoc4BrTlADunHuqEJV4sJOlyZcDAAlpwA5u48WhAwUPQoaGYimpw0ALamnlasfDpQQTgA3MCgkLCI1JwBCACSMgBCUFD6IFxmWGj4hCTkSjB0jABGjc1cfOxaWXwA3gC+RSXQ8EjYmNg4AAo0femSMBTUffQwzPxcvPyCwmISUrIKvSoa2gB0r1uhMmYAgpMItg7OVzuYReG5+BABYJhYE1by+O6cQypAYgGAwr5w25yM4AbQAuggAGQIKYIHHrBAhGp4swsGZEkkIZphYhmM4IGYRKIxOLYRKaOwgZBmJ4hHDgMzVX65fLzcCLcpQSqIWoAZUCIVCbTWm22hFR+1oRwYkM1Y20v1m80o+hoMjkGBAVSmHgA9K7KYgnLA7DIPAABWoNJotTgeIhcHDNYMjThaIZNMyI5GoixmGU4EkzYrCd2ehA4KBOzgAci9Ptez3Dkea6qhoS0gZkdc1EMCSaRKJgaYQGazwGzwDzQXLMF9wCDw1DWlJdjMug7Ke71izHM0JbsJYsRTVGrCM4Qc+0OkXXct9M5CA3Jc0AAZt8AgA)

### 💻 Code

```ts
export type TypedMethodDecorator<V = any> = <
  O extends Record<K, (value: V) => unknown>,
  K extends string,
>(prototype: O, name: K) => void;

export const IsBoolean: TypedMethodDecorator<boolean> = () => {};

export type TypedParameterDecorator<V = any> = <
  O extends Record<K, (...args: A) => unknown>,
  K extends string,
  I extends number,
  A extends any[] & { [P in I]: V } & { length: any },
>(prototype: O, key: K, index: I) => void;

export const IsString: TypedParameterDecorator<string> = () => {};

class Test {
  // it works
  @IsBoolean
  handleBoolean(bool: number): void {}

  // it doesn't work...
  handleString(@IsString str: number): void {}
}

// it works
IsBoolean({ k: (v: number) => {} }, 'k');
IsString({ k: (v: number) => {} }, 'k', 0);
```

### 🙁 Actual behavior

TypeScript doesn't show type checking error, when I use TypedParameterDecorator (see Code)

### 🙂 Expected behavior

TypeScript should show type checking error.

**Comment by RyanCavanaugh** [comment]
Duplicate #43132
