### ISSUE TITLE
`if` does not guard `unkown` not `null` correctly

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#44971]
# Bug Report

### 🔎 Search Terms

if unkown null

### 🕗 Version & Regression Information

`typescript@next`

This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/CYUwxgNghgTiAEYD2A7AzgF3iGMkwC54BXFAaxSQHcUAoWgSwDN4AKHPGASngG9b48DAAs8VIQE8ADiCQsO+eAF4V8AORIARgCtwGNfABkh9QFsQaNFADmIAwxTZcigPzwA8jr0A6KJYbWKKwoIOIAos4wrFwANE6cPEQKMLQAvkA)

### 💻 Code

```ts
declare const error: unknown

if (error) {
  throw typeof error === 'object' && 'message' in error ? Object.assign(new Error(), error) : error
}
```

### 🙁 Actual behavior

```log
Object is possibly 'null'.
```

### 🙂 Expected behavior

No error, `if (error)` has already ensured `error` will never be `null`.

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/28131

**Comment by JounQin** [comment]
Thanks.
