### ISSUE TITLE
Object.assign unexpectedly returns never type

### ISSUE THREAD

**Issue by VVatashi** [microsoft/TypeScript#44983]
# Bug Report

### 🔎 Search Terms

Object.assign, intersection type, never type, undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about intersection type and never type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/MYewdgzgLgBAZiEMC8MDeMCGAuGBGAGhgCNcAmGAXwG4AoUSWYzAJxRgHliArAU2CgA6TBAgBLAOZgAFGkpEEIIhlIwArmAAmvOGLC9NVAJR1mLYezx0gA)

### 💻 Code

I commonly use this pattern to "remove" unnecessary fields from an object in JS:

```ts
const foo = { a: 1, b: 2 };
const bar = Object.assign({}, foo, { b: undefined }); // Making a copy of 'foo' without field 'b'
bar.a = 1; // 'bar' should have at least 'a' field here, but TS gives error
```

### 🙁 Actual behavior

However, in TS the result of `Object.assign` was inferred to be of `never` type. So I got this error:
```
Property 'a' does not exist on type 'never'.
 The intersection '{ a: number; b: number; } & { b: undefined; }' was reduced to 'never' because property 'b' has conflicting types in some constituents.(2339)
```

Isn't this an error in definition of `Object.assign` function or in intersection type logic?

### 🙂 Expected behavior

I expected the result type to be something like  `{ a: number; b?: number; }`, `{ a: number; b: undefined; }` or `{ a: number; }`.

**Comment by MartinJohns** [comment]
See the second and third point of @jcalz comment: https://github.com/microsoft/TypeScript/issues/43110#issuecomment-791866774

You can use a type assertion as a workaround: `Object.assign({}, foo, { b: undefined as undefined | number });`
