### ISSUE TITLE
keyof ignores constraint

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#44985]
# Bug Report

### 🔎 Search Terms

keyof, generic constraint

### 🕗 Version & Regression Information

- This is a crash ❌ No
- This changed between versions _______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about keyof
- I was unable to test this on prior versions because it seems to be consistent behavior in all tested versions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAyBLAzjYA7YKAHgFEA3fGAPjgF44AKYCvGALjnMoEo6ayIGACYBuAFChIsBMlQBVPFgCuAIywBjKBhWp6DXrX6ChYsQHozcAOoALRHGwIbjqMCkwMeAOZwAhlj84MCgIFQAbYABbAH4xJBR0bFwCKCxSFhgsABo4AGk4UGShAJwtbzgAMjgAa2BECAAzTgysGnoAbwBtWsQOXIBdDkwcfEJ0yixOgapO-oBfU3MAKiWxOCW4AGUMSLAIh12IyMpfDwg8OEaCjILIjBhcKDh1CF3T7X2G6DgVEIB3LCENZLMxidRhfwBLisEh3B5jaGZAogIoBLo9DilTxeQZwJR4ap4CB-PBzGjtNZwADEYSSo1SQzpKTSiOyNTqV1ZVHElLMK0p6zgAGFzqUlOp4IjYfdHgKNgABUC+Q7AOVwAAGmoAVlg1S9FPAojLCHQ4AQ-s1KNL4VB9HrRfBaSMUqb9Hw4AA6L1qo02j3nBgAciUYCEp2AgZyTuShG4Prhj39DQaQZDYdwkbg0fpcbgeY2vsTvtTofDmfaQV8iDCEF8Qg4gfTvkDcDmufzGs1ctBef1Yol0DdFLzeZgziwHppTMIAQ6c3EeYWvP5I42ACVgF46U9fFnp1A1YqQMq9qrV531Tr7Qa986TXoDDQvR748aoEmU8HSxmo-v24LNXVbtKXOIgABVZGRVE4Cxcoqh6TkWioBh4mADgIJQX87ygRlsPGVhJgw4B+iobgOAUZQ1E0bRUDgYcRwwJoGAAQlQ3gx3+M1gAtEgoBCW1AyFXw8CJeB1F8MIwjgfCYGtR4qH9C4-nuGwICUeBd1QwNuAXBimOY7MUnYmxOPNTg+MHQThNE54JKkmS5MIBTzjgZSxzUjTbxjKBtN00dx0nQyZ06VD+lNMdsEC-dJlCuAAB84rgWY-KcSKp2wmLZH6D0wCULAbAYIKoB0gU4FcGAlCgC43UMOjSv8yLGhTVCsO8kqR1bSklzzPlVnPBRXC3EYniKw8lRVNVAKvc8+0dfdXUfT1vXPQtCA-Et0wjVqc0mrtVx7S5k3AyDCnwYoYJgMofHgjkmi5FDZHQ2RtpSXDvJkwistIjgIrRUrGMYVjZGM0zuPM-igyEkSIDEuzpKlBMnI-VyVI8wItPavTAaKkHiS4niLIEqGbPEyT4YyRyoGc5MUfc9TAiK3z-v036ooykKst4crKouX6Utmrz6VnVKJ3S7zMpQbKGgwMJHgYBgGjwN76Q+zoiJIxbFbgZjaHoHGUoBwroo9CJvDHOAaAABl4eiOtZsWhY5yXTSKrAUrmAowkBOqOrzIRgAiXARbZ8WneI93Su5qqRd07q4F6tVrWuSgxuPCbzym3UVsR99iy-Tby0rata3rOBG1OZtW3-DZAOAvNfWOhJTrwc7YOu9l6jupCHpQJ7MOT1gOFZNXOZ+8cfaxli2KcUGCYhqzodhsmHJzhTfVp1T6c02QmY6w3WICh3mTD-oueACro750r7ddk+PS+KASF8dQCqN7DlZSVX1dI90iqYDJuCYzzFHXm45Y5iCXBYOAcgsC+C8KqVCcAACyiBWSmlts8c4BAJQcAEMISOwB9TYPYGaJQkQdAHg6oQfiQ9CalSENgIhhCSF4JMAsAWq0nj0DMgjN8RAUH3TjBIHOikgxMIlJmBgYAqw1jrItDBUDpHFzrDBTeYQhA-FQKwiBvAoEij4swuAABaOAAB5XIzFhFvlEYGVw4iYCSKUbIoQ8jSqKJkSXVRal1GaNIeQoEbZ46WH0XY+AJjzGWM4TY6h0BHEeLke6BRlgnGePyt4jROhwbQB0UE4U0BQnGLMRYqxfoAyNkYVg5hcTlEuMSW45J8SNFpKUD4zJ2jAl6PyYY8JxSSlFjhGIypEicj4n9tLAgtTOkGIlIUiJ5hLDykyEYyQzDll0KiXnexmYAAsAAmXRwSukzJ6ZYqBiysDLPAKsmJB4NkDMDFsnI7QUl1gbFgV459nDeEDB0w50ywlFMiSIvOdihkOJyHsg5eT-mzOKXc+4QYbmZh4YTIMJA1xrm0lCkJ3TAV9LWnnBhGgwWZlGcAcZwBJl-IKScoAA)

### 💻 Code

```ts
// Implementation of event emitter - sample without all methods
type Listener<Event> = (event: Event) => void;

// Here the "key: K" complains "An index signature parameter type must be either 'string' or 'number'"
type Listeners<Events, K extends string & keyof Events> = {[key: K]: Listener<Events[K]>[]}

class EventEmitter<Events extends {[key: string]: unknown}> {
  #listeners: Listeners<Events, keyof Events>

  constructor() {
    this.#listeners = {}
  }
}

// Usage
type MyEvents = {
    connect: void
    reconnect: number
    error: Error
    disconnect: void
}
const emitter = new EventEmitter<MyEvents>()
```

### 🙁 Actual behavior

I am getting ts errors even though the types work as expected. See // usage section 

### 🙂 Expected behavior

The keyof returns the same type as the constraint generic and thus will be valid as index signature.

**Comment by MartinJohns** [comment]
Having `keyof T` as an indexer type would require #26797.

**Comment by alesmenzel** [comment]
So, does that mean it is currently not possible to do?
btw. why is `K extends string & keyof Events` not enough to make it an indexable type since it requires 'string' or 'number' and the generic K must be a string and also keyof Events?

**Comment by MartinJohns** [comment]
The type `string & keyof Events` is the same as `keyof Events`. And a union of keys can not be an index signature. You can use a mapped type instead.

**Comment by RyanCavanaugh** [comment]
This works without issue
```ts
type Listeners<Events, K extends keyof Events> = Record<K, Listener<Events[K]>>;
```

**Comment by alesmenzel** [comment]
Thanks guys,
the error message wasnt clear to me, but know I understand that you cant use a union of types which you get from the keyof - e.g. type union = 'a' | 'b' | 'c' to index but instead use it in either Record which handles the union case or use mapped type like `{[key in K]: ... }` instead of `{[key: K]:`

Lastly, do you know why there is the last error at the `.push(listener)` line in `.on()` method [ts playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAyBLAzjYA7YKAHgFEA3fGAPjgF44AKYCvGALjnMoEo6ayIGACYBuAFChIsBMlQBVPFgCuAIywBjKBhWp6DXrX6ChYsQHozcAOoALRHGwIbjqMCkwMeAOZwAhlj84MCgIFQAbYABbAH4xJBR0bFwCKCxSFhgsABo4AGk4UGShAIBrYEQIADNODKwaegBvAG0y+088gF0OTBx8QnTKLCbcjqomjoBfU3MAKhmxOBm4AGUMSLAIh3WIyMpfDwg8OCqCjILIjBhcKDh1CHX97U3K6DgVEIB3LEIFmbMxdRhfwBLisEgXK79UGZAogIoBZqtDg4LTeLpwJR4Ep4CAfPATGgNBZwADEYSSfVS3QpKTS0OycFaJ3pVHExLMc2JizgAGFDiilOp4NDwZdrlylgABUC+bbACVwAAGyoAVlgFXdFPAomLCHQ4AQPjVKKLIVB9Br+fByb0Uvr9Hw4AA6F0KnVmp2HBgAciUYCE+2A3pyNuShG4boh109lUqPr9AdwwbgocpEbgGaW7uj7vj-sDyYaQV8iDCEF8Qg43sTvm9cAm6czSuVEv+Gc1AqF0AdRIzGZgziwTrJNMIAUaEz8AR6YdSA1YDKZ1RZ4gzU3ZnL7SwASsAvBSbr4U6OoArpSBZRt5Vvm4q1ZatcfbXq9AYaC6nZHdVAY3HffmkxDE9G25ZVFVbYlDiIAAVWRYXhRlymZWoqAYeJgA4WCUCA58oGpXD50yJosOAUZuA4BRlDUTRtFQOBez7DBqgYABCdDeAHT4DWAI0SCgEJzW9HlfDwHF4HUXwwjCOBCNNa4qE9I4PkuGwICUeAj3Q71uFXRjmJY1MUg4mwuMNTh+O7ISRLE25JOk2So0IBTDjgZSBzUjSn1nbTdP7Qdh0MscmnQjp9QHbAApPIYQrgAAfWK4HGXynAikdcOi2QOidMAlCwGwGECqAdK5OBXBgJQoCOB1DHokq-Iiqo43QnDZ2Kvt62JdcMw5eYbwUVx916G5CrPGU5QVMD7xvDtrRPe032dV0b2zQhfzzRMgxatMJpbLc22OWMYLgwp8GKRCKmXFC0NkTDZC2lJ8NnQihhIsiOHChESqYxg2NkYzTJ48yBJ9YTRIgcS7JkkVHKgZzY1clSPMCLS2r0n7Cv+3FuN4izBNBmyJKkqGMjkpzfwR9z1MCQqfK+-SPsi9Lgsy3gyoqo4PuSmavMpccUqHNLZwylAssqDAwmuBgGEqPBHspZ7iMyqgFpluAWNoegMeS76Cqip0Im8Ac4BoAAGXgGPahnBd55mRf1QqsGSydgDCb5avajMhBd4BcH5xmhdt0inZKtnKv53SurgHqFVNU5KFGi9xpvSb1WWmGnVzf8NsLYtS3LSs4GrfZa3rECljAiCM3dI6EhOvAzqXY0F1Q9DbuwuPWA4elFZF8j+fdtHWPYpwAZx4GrLBiGiYc78FPdCnVKpzTZFp9qdbY-zrdpQOOlZn32fDkqrYdnenReKASF8dR8t13C5ZSBXXuVx1CqYDJuFRjNQ45wcI7EdcLBwDkFgXwXh5ToTgAAWUQPSfUFtbiHAIEKDgAhhAh2AJqJB7ADRKEiDoU87VCACS7rjEqQhsCYIwdg1BJgpjcxWjcegZlobfiINAlkFoJDpy9N6ShQpkwMDACWMsFYFrwMAUIvOFY4B5TUmEIQbxUA0P-rwQBfJ+JULgAAWjgAAeVyCxLh35FI+lcHwmAAjJEiKEGIkqEjhH5xkYveRiicF4J+A2KOlh1FmPgDo-RhiGEmO9EQ6AliHGiMdOIywVjHGyKUC4nQQNoAqK8byaAvjtF6IMUYj0PDyEaEQVQ8JUibFRLsTEiJCj4mJKUcYVJaiMmaP8Tk3JOYIQ+nMcmTEXsxYEDKY0jRQoskBLaatTOZiin8JyAAFgAEyqO8U04ZLTAnp0zqEqAyZmG4x9CQbc25tKLPSUMvx2S1nGMzgUrpOQenAD6cAAZSzTkjNaYA6CNhUAvCkriTwPganVNUkaTZOQfHNPOWMn8mcblwHmRGIJ0KpkWJyA0WJFYqxYHuD7Zw3hvQNiAA) 
```
Argument of type 'Listener<Events[Type]>' is not assignable to parameter of type 'Listener<Events[keyof Events]>'.
  Type 'Events[keyof Events]' is not assignable to type 'Events[Type]'
```
it seems to me that those types should be the same, no? One is `Events[keyof Events]` (so basically any values of the Events) and the second one is the concrete event `Events[Type]` where the type is defined as constraint of `keyof Events`

```ts
  on<Type extends keyof Events>(type: Type, listener: Listener<Events[Type]>): Unsubscribe  {
    if (!type) throw new Error('Cannot call <EventEmitter>.on without a type');
    if (!listener) throw new Error('Cannot call <EventEmitter>.on without a listener');
    this.#listeners[type] = this.#listeners[type] || [];
    this.#listeners[type].push(listener);
    return () => {
      this.off(type, listener);
    }
  }
```

**Comment by alesmenzel** [comment]
Looks like I had a mistake in the mapped type, working version for anyone interested
[ts playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAyBLAzjYA7YKAHgFEA3fGAPjgF44AKYCvGALjnMoEo6ayIGACYBuAFChIsBMlQBVPFgCuAIywBjKBhWp6DXrX6ChYsQHozcAOoALRHGwIbjqMCkwMeAOZwAhlj84MCgIFQAbYABbAH4xJBR0bFwCKCxSFhgsGnoAbwBtAGkHPDgAa2BECAAzTgysAF0OTBx8QnTKLEL6qjz6gF9TcwAqIbE4IbgAZQxIsAiHWYjIyl8PCBLquGZKLciMGFwoOHUIWdXtearoOBUQgHcsQjGhszF1MP8ArlYSPYO276ZLYgZJCAL5cqIDg4LTeRpwJR4Up4CB3PB9Gg5MZwADEYSSrVSTQJKTSgKy4mxZhG2PGcAAwusYUp1PBAb99odaRMAAKgXyLYDcuAAAzFACssMKTop4FFOYQ6HACHdapQOf8oPppUz4PiWiklfo+HAAHTm4XyzWm9YMADkSjAQlWwDtABo4PrkoRuJa-ocbVUqvbHc7cO7PSSfX6FVBTVaQ06XRGckFfIgwhBfEIOHaw747XA+r64KWJmKRdzXqWZczWdBjVjS6WYM4sKa8VHUkqcn0-AFmt7Uu1WBTsQMqTTmxMAErALwEo6+SMGp7TuB8kACuZC9cVyU62UrodGgw0c2mmPW6rBh1J8Mer2Ektl0ViqvY9ZEAAqsmBoICSFNnJKgGHiYAOF-FBHy7YlV2Ick8ig4Bum4DgFGUNRNG0VA4CbZsMBqBgAEJwN4Vt7mVYBVRIKAQi1O16V8PAUXgdRfDCMI4BHGANUOKgbRKO59hsCAlHgZdwLtbhxGbBwiOIp8UnImxKJVTg6IbRjmNY44OK4ni+MIAT1jgYTWzEiTj0JaTZObVtsA7JTCE6cD6iVBz207eDXNkdyAB9-LgXo7JbNsnK7XyUHqU0wCULAbAYZyoBk2k4FcGAlCgEpjUMPC0rCxybzA2QYPg1K5IGUsJ1LalRnXBRXAXFojmS4VN23CJhX3KV11rPUu1PE0LyvANirvMNXTKocXzpCsP1LG8fz-UAALKCpgLqUDwMg0rrJSOChx4zpkNQjhPPyuTCMYUjZBUtTqI0+j7SYliIDY-TuPZf1jMDGpzNE8TAikiqCIU5L7tRKiaM0hjXt09jOK+jIjKgEygzMkTLMCZLbLS66SM8iKfLyNzeAyrKSk80Ljl1faXI88LvKHKKUNNKoMDCQ4GAYKo8EOwljqQvyqDPOA+bgYjaHoCGaYJ5L2wibxWzgGgAAZeHwuSieZwlWfcmXIppvtgDCR5LrkuAhFN4BcCcRzddJUm-ONtKKey+2sDsmq4Dq4UNS2DJ2v5QVuolXrXytAMEwm5MPVTMB00zbNc3zQtizDytp2rXZ9mWhJVvwMF1sqGoQJKlBdugwPKA4RDTrQz2LdLAnbpQSHVXU2jnu0t6PqRwyfrR+M-kxiygck2Q8auhSdYV53ovJ23Kc9mm58ihe2auKASF8dREqS2DEngoXTtFk1kqYDJuFB0t3apttvbECcLDgOQsF8LwhXAuAAFlEHJD2NKMoCCsg4AIYQbtgAgOgewZUShIg6CgGlQg9E66wzSkIbAMCwFwAgSYAY-Vc6aiVF3FGQ8iD-3Lr6CQQ9BL2hwTACMDBE4ZizEIMWWtfaWFYcnIQcAEpiTCPwnQeDjDP14K-RkdFYFwAALRwAAPIFGIrQ2M9C7SuEYcw3h7DOFpVfro7MAjAbCJuKgPACCkESO4QyaAWj4AKOUaoqOhANGoOgDopOeiTRcMMd44xgilBmNEd3aANipH2NkU4lRajrx4HtFgjQ6xQFMI9CwgJHDfEGJ4ZkkxQiRGoHwREyw0iHHyKUbEuJ0c-gMJSbAiMiJrYcwIFkyJMjWQVOcdUtxMctH1NZBGAALAAJkkaUqJnSYkuLoTHDxUAIxd1hvaEgM4ZzSXGXYjpjjKkzPUTHJJ2iPRNOAC04AbSJnbK6VU1+34bCoCuJxVEngfBBLMYI1U8yPRlOibsnpcYY5HLgKM30riAW1LtECnIRicxwDtFgU4ttnDeDtMWIAA)

Thanks @MartinJohns and @RyanCavanaugh
