### ISSUE TITLE
Wrong tuple inference of async IIFE return value

### ISSUE THREAD

**Issue by enisdenjo** [microsoft/TypeScript#44992]
# Bug Report

### 🔎 Search Terms

tuple, array, promise, async, function, inference

### 🕗 Version & Regression Information

v4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=3&ssc=9&pln=3&pc=15#code/BQQwzgngdgxgBMAlHAvAPjgbwFBzgenzkBlyXOGAeyjABc4oKB3CgJwGsAuOABRYoFsAlmACmAHgDaVEVygBXfgCMRLADRwazLrRaCoAcwC6GFAnDR4SVBhx48LETTksocCQEZ1Ack0UvhgG4yAF9EJCCyQjhAUHIySmo6CBEwZnYuXgFhcSkoGXoFZTUNLTgdPSMTehFGHj4hUWAyPGAHMAoAGwA3EWR0OFaO7uAPb19-RFUyRCDQ8OwgA)

### 💻 Code and behavior

```ts
// ❌ Type '(string | number)[]' is not assignable to type '[one: number, two: string]'.
const nowork: Promise<[one: number, two: string]> = (async () => {
  return [1, 'two'];
})();
```

### 🙂 Expected behavior

As with supplying an instance of Promise, correctly infer returned value as assignable to the variable.

```ts
// ✅
const yeswork: Promise<[one: number, two: string]> = new Promise(
  (resolve) => resolve([1, 'two']),
);
```

**Comment by RyanCavanaugh** [comment]
Also works:
```ts
  const nowork2: () => [one: number, two: string] = () => {
    return [1, 'two'];
  }
```
