### ISSUE TITLE
Type Predicate not working on a union where one of the values is a strict subset of the other

### ISSUE THREAD

**Issue by samouri** [microsoft/TypeScript#44993]
# Bug Report

### 🔎 Search Terms

Narrow, Type Predicate

### 🕗 Version & Regression Information

Current versions of TS.

### ⏯ Playground Link

[Workbench link](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.4.0-beta#code/JYOwLgpgTgZghgYwgAgILIN4FgBQz-IBuAXMgM5hSgDmA3LgcgPRPICqICA9gLY8TgayMAAsUAIwgAbLgHdkU0ChjAAHhDLCxyYGQAqATwAOEdEagQAJsARxIAOgYEWyEaQpUQdXAF9cuUEhYRBQAIUwnfBJyShp6PAIAL1JKAFcIeL8cXDBjFABhZABeNGQAH2RQ+NwYVM4wYC4QHX081AAKBFJ8gEpSBBbS7AT8CzBUqGaAQl1DE1DOnsz-HFr6xubZvIWu5F7+wfDhxjGJ5oByRPOdZoRl7NW6hAam5AhVOB4jKQh2noiRshuCAKMg4MVMNFzmIpDJrj4wZp8rRkCtGC4AMqpcRkYDjSBaFDAGBAprWF7NWR4kSE5CSGTyRQgCAAGjBIEstO4lhQuRMQLECAA1ppzFwTFApAYwdQ4KBHICXMTkO0Zq15u04D1-scCMr2lsTB0tTrIoxmKwMSIuKkpJzJMI8qVxKkwLS+ShzFYbHYiZpJEJgNQQFwLJYzScIONJmD4owsmbMdbbZyQHAoFA5MIuI7+aE2S63bpkAADZmEaAlhWR6PNOD2Qj3IA)

### 💻 Code

```ts
interface A {
    v: string;
    // Uncommenting the below line fixes the isTypeA predicate.
    // h: string;
}

interface B {
    v: string;
    z: true;
}

type C = A | B;

function isTypeA(c: C): c is A {
    return !isTypeB(c);
}

function isTypeB(c: C): c is B {
    return 'z' in c;
}

function example() {
    const a = {v: 'hello' } as C; 

    // Subsitute the if condition with the below line, and the code type checks properly again.
    // if (!isTypeB(a)) {
    if (isTypeA(a)) {
        // Should be type A but the type predicate is being ignored and it is still inferred to be type C
        return a;
    }

    // Should narrow to type B, but is `never`.
    return a.v;
}
```

### 🙁 Actual behavior

While `isTypeB` works properly, for some reason `isTypeA` does not.

### 🙂 Expected behavior

`isTypeA` should type narrow.

**Comment by jcalz** [comment]
But `B extends A`, so every `B` is also an `A`.  In the absence of exact object types, and with the exception of excess property checking of object literals, there’s nothing about `A` which implies “not `B`”.  Your implementation of `isTypeA` is therefore mismatched with the type system.

This is working as intended.

**Comment by samouri** [comment]
@jcalz, I think I follow your logic. I'm lost why flipping the condition works. If the implementation for `isTypeA` does not work, why does replacing the call with the body of the function correct narrow the type?

I.e.

```ts
 if (!isTypeB(a)) { ... }
```

Does the logic go as follows:
- If an object is an `A`, then it can be either an `A` or a `B`
- Only by saying an object _isn't_ a `B` can we know that it can really only be `B`

**Comment by fatcerberus** [comment]
Yes, that’s correct. It makes more sense if you restate the first point as “If an object is an `A`, then it might *also* be a valid `B`—we can’t rule that out based on the types alone.” That’s how the compiler is reasoning about it.

**Comment by samouri** [comment]
Thanks all!
