### ISSUE TITLE
Enums cannot be used as a value when imports using the `import type` declaration.

### ISSUE THREAD

**Issue by AnmSaiful** [microsoft/TypeScript#44998]
# Bug Report

### 🕗 Version Information

TypeScript v4.1.3 Node.js v10.23.1 linux/amd64

### ⏯ REPL Link

https://replit.com/@AnmSaiful/ts-import-type-enum

### 💻 Code

```ts
// ---- enums.ts ----
export enum Sex {

  Male    = "male",
  Female  = "female",

}

// ---- type.ts ----
export * as Enum from "./enums";

// ---- index.ts ----
import type { Enum } from "./type";

function enumTest(): Enum.Sex {

  return Enum.Sex.Male;

}

console.log( enumTest() );
```

### 🙁 Actual behavior

It does not allow using Enum from the composed imported type and says:

> 'Enum' cannot be used as a value because it was imported using 'import type'.

### 🙂 Expected behavior

It should allow using Enums from the imported type.

**Comment by DanielRosenwasser** [comment]
`import type` doesn't generate any code, so you'll get a runtime error when evaluating `Enum.Sex` because `Enum` won't refer to anything in the output JavaScript.

**Comment by AnmSaiful** [comment]
@DanielRosenwasser I'm using `import type` to avoid failing ESLint's [no-cycle](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md) rule because my type imports result from circular dependency. It is normal because the type definition file uses the class file (for the instance type), and class file uses the type definition file.

I can suppress the ESLint error for that line, but should this be practiced?

**Comment by AnmSaiful** [comment]
Perhaps we should move this to the **feature** list instead of bug?

**Comment by DanielRosenwasser** [comment]
`import type` is meant to be erased away entirely - so unfortunately there's no way to make this functionality work that isn't at odds with design decisions we're already set on. At best, there's the discussion of whether we'd want to make exceptions for `const enum`s, which is awaiting more feedback at https://github.com/microsoft/TypeScript/issues/40344.

**Comment by AnmSaiful** [comment]
Currently, I'm using plain objects along with `typeof XYZ[ keyof typeof XYZ]` as a workaround. Hopefully TS will solve the enum issue someday.

**Comment by AnmSaiful** [comment]
Currently, I'm using plain objects `as const` along with `typeof Obj[ keyof typeof Obj]` as a workaround. Hopefully TS will solve the enum issue soon.

**Comment by AnmSaiful** [comment]
Currently, I'm using plain objects `as const` along with `typeof Obj[ keyof typeof Obj]` as a workaround. Hopefully, TS will solve the enum issue soon.
