### ISSUE TITLE
Checking if object[prop] is not undefined does not eliminate undefined type from object[prop] (type guard)

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#45002]
# Bug Report

### 🔎 Search Terms
type guard object property

### 🕗 Version & Regression Information
I'm using 4.2.4 in production, I don't know if this bug has occurred in prior versions.

I have tested in the playground that the bug also occurs in 4.3.x and 4.4 beta

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strict=true&ts=4.3.5#code/MYewdgzgLgBA1gFQIYCMA2BTAwiNBXAW0hgF4YBtAcgEsATSgGhkqmqk0eetDEoF0A3ACghUAJ4AHDDGToMAESRQkpGAG8hMLTDoAuGNABO1MAHNN21uwz6jJ89p09bUY2aEBfEeKkwAshjKtEoqZBqOeIZoLm7mXqKS0gCqEsFQGAAKhiASEKoZSIasSGgAPADyBGylspiKykw09AB8zTAAZDAFRdQlpQFBIc3CQgBmeGDArOAweKlKGAAUEtm5+ilpmasQAJTqFlo80DDKchsL+gCChoZIYqVqMKD4RDH2TABuJXg2Bq72MA8bTI5EEIkciFQmBwL0gADpRiBDABRJDAAAWi0Wz0IYD2JDa4Uc2mooxgix8GBAZJWOQg5BxRBgSDycAwYmpMHO6SydL4MAAhCQyJQJrQMKMTBh6HsicTiQB6BUwZEADwkaG4bDQYie6IwwDZtBO6KUMFpuQZuFxEH51DyYBAsDFEqltCYYkCMAAkjBTR9pFAQAd5dolbMINJHWAALRgPBoNDMiCRnozHIYW5BwwnEAGJT20a6qD6p4gAgSaiYQxwkOhmDh5E3JFvMwwAA+szA4slYGlOgdTuTEGopjAUMDecpf1iddDp0w3IwcIkeAgmMejLAn2+vwt9K3yfg7M5S95uT4Hj24fKYB1gqeSDAMElqp0UFr9cc4YAQhgILQ1D-ia9pMCW0gAAYsseHJkme2wQQY6IgAmxooNIhjSmKT6wEgozpIYc7yuGGIGnAAIlma4EwF8+DSPaMCOs63aun2tCfqGXiOFewgeEAA)

### 💻 Code

```ts
const kTableColumns = ['id', 'title', 'icon'];

type TableData = {
    id: string
    title: string
    icon: string
}

type Metadata = {
    url: string
}

type UpdateProps = Partial<Omit<TableData, 'id'>> & Partial<Metadata>;

function update(props: UpdateProps) {
    const tableUpdate: Array<{ column: string, value: string }> = [];

    kTableColumns.forEach((column) => {
        if (typeof props[column as keyof UpdateProps] !== 'undefined') {
            // Explicitly checked that props[columns] is not undefined, yet I have to
            // use non-null assertion operator to satisfy the compiler.
            // Error: string | undefined is not assignable to type string
            tableUpdate.push({ column, value: props[column as keyof UpdateProps]}) // Only ! can fix it.
            // Besdies this, the `as keyof UpdateProps` should be redundant after
            // checking that the value is not undefined.
        }
    });
}
```

### 🙁 Actual behavior
After validating that `prop[columns] is not `undefined`, the compiler still treats `prop[columns]` as possibly `undefined`.

A non-null assertion operator at the end of the value is a workaround, but it feels like it should not be there.

### 🙂 Expected behavior
The type of `prop[columns]` inside the if clause should not be undefined.

Additionally, using `column as keyof UpdateProps` should not be required after validating that column is a valid key of the object (though I understand if there are valid reasons against it, I'm mostly concerned about the first issue).

**Comment by RyanCavanaugh** [comment]
Duplicate #44899 , others
