### ISSUE TITLE
(Partial<Type>)[keyof Type] is udefined in certain settings and assignment is not possible

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#45003]
# Bug Report

### 🔎 Search Terms
Partial keyof undefined

### 🕗 Version & Regression Information
I'm using 4.2.4 in production and it occurs. I have tested with 4.4 beta on the playground and it also occurs. I have no knowledge if the bug occurred in prior versions.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it.

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?strict=true&ts=4.4.0-beta#code/C4TwDgpgBAIghsOBGKBeKBvAUFKwIDOwSAXFEQE4CWAdgOY56HABMZltDAvllqJLARwWaTI3xFS5YNXrjmbKACMA9ioA2EODSw8sm4FAAmQqQAU4FYFTjqAPPERIAfKIxQuAbn0RDJxIoWVjb2jsKu6O5evAD0MVAAtr5w-nAAdBKG6ADkmdneBlAA1hAgornMSPk+hgButgCu0Dl53lhxUADyRVipSADaJWVwBMWlKgBmgk4AuqL16k1tHQCiFBQqFGQAKuDQ2Rz02VBUozQqhiMEVHQ0cEqaeCp4e1DZDTRGEBO0EEbZ7XiAElDAQIBAEqN1FQSngABbQJQNOhQFQAYzRDQooxUNHUZSoU2ACNRSgAVhA0YZ+NA4SMoAsmjiJoDjISJhAKBAaNS9gRekIWINSlB6UNJtNhHN0IyIMt4tsSVzbFA0SNoAQ0dzLFRnqcoECoAB3bTUvX4CgIDUqJJQMAbSDBQiiz6sq43GjwiFPL12yzWWwAGnIz0NEAAHpAqfCEL6wP6QlA6WcVKzaFQA+o7Q7OdZnV8fjQ-qLLuos9ojKrtMpoO7bsXtGV7SpHaBUSyOvHgrZizS0rwaVBtvdNGFRGJcLgqEZ2DJOIxcNZgJpZ7IGJOTmjcav53pBwBZZKpNwLqBY9Q7uQbuBUqi1CBkVQaLQ6PevADCyvwZgdo3QnQSDM7GHB4IDCYNsmnbJXAAMigIJMzsQ9EFSZw2gmD5b1xVUvwgAAKZswAIMhPy0b9fwASjIWoVGnCdVVxIgTkrFpmGqRgtxoJjEFAsIdhHMChBPDdp0DU8lxXbMWwIDIM00MSRM4shCJkqhOMYHhcA4xjDCSFChDIBCQiQo8hAiTAPDaXAJk2KA8M4pihnbLpyUpYA0iGAgCMoij6I3DoACEGiodRKz0lIhImDYEnhFQwSkojjThNS4VFLkoHOakBLCU8pymPCaQlHjRyEYVhlGcUphAkrEGlVAcg+Atfn+XzsA3dqoFWdZNhIXL2o6XYBAOOd6CgAAfZQ1E0bRjn1TLRQIa5bgEn1B3eT5vma44+o3cLUjKhaxhACVkIi2rRBUg6xXGKZSKtH9pJmABCbwOs0yd3q4IA)

### 💻 Code

```ts
type Data1 = {
  test1: string
  test2: string
}

type Data2 = {
  test1: string
  test2: boolean
}

let data1: Partial<Data1> = { };
let data2: Partial<Data2> = { };

// metadata.test = 'test';
let key = 'test1';
let value = 'test';

// Ok
data1[key as keyof Data1] = value;

// Error: Type 'string' is not assignable to type 'undefined'
// It seems like the bug occurs only if the object type has values of
// different types
data2[key as keyof Data2] = value;

// The real case scenario is I want to iterate some properties and
// assign them to the partial, so I expect that the partial has no
// initial properties defined at all and can be assigned any property of
// partialed type.

type TableData =  {
    id: string
    title: string
    icon: string
}

type Metadata = {
    url: string
    active: boolean
}

type CreateProps = Omit<TableData, 'id'> & Partial<Metadata>;

function create(props: CreateProps): void {
  const id = 'test';

  const tableData: TableData = {
    id,
    title: props.title,
    icon: props.icon
  }
  
  const metadata: Partial<Metadata> = { };

  for (const key of Object.keys(props)) {
      // Build metadata from those props which are not tableData
      if (typeof tableData[key as keyof TableData] === 'undefined') {
          // Error:
          // Type 'string | boolean' is not assignable to type 'undefined' 
          metadata[key as keyof Metadata] = props[key as keyof CreateProps]!;
      }
    }
  }
```

### 🙁 Actual behavior
`data2[key as keyof Data2]` is `undefined` and it's not possible to assign anything to it.

### 🙂 Expected behavior
`data2[key as keyof Data2]` should not be `undefined`. At least it should be `undefined | string | boolean`. It should also be possible to assign a value to it, despite being possible `undefined`.

**Comment by MartinJohns** [comment]
Related: #32693

**Comment by RyanCavanaugh** [comment]
> `data2[key as keyof Data2]` is undefined and it's not possible to assign anything to it.

This is the correct behavior. `data2` has two properties, which have the legal values `string | undefined` and `boolean | undefined`. If you're assigning into an arbitrary property of `data2`, the only value which is legal for both possible target properties is `undefined`.

```ts
  metadata[key as keyof Metadata] = props[key as keyof CreateProps]!;
```
The same logic applies here.

**Comment by fatcerberus** [comment]
See also #30769.  In particular:

> When an indexed access `T[K]` occurs on the source side of a type relationship, it resolves to a union type of the properties selected by T[K], but **when it occurs on the target side of a type relationship, it now resolves to an intersection type of the properties selected by T[K]**. Previously, the target side would resolve to a union type as well, which is unsound.

Emphasis mine.  `(string | undefined) & (boolean | undefined)` is `undefined`.

**Comment by mckravchyk** [comment]
Thanks. I understand now that I should also check if the value is not undefined -  I'm accepting a partial, but I don't want undefined values on the object (which the partial type allows).

Do you have any suggestions how I could implement this in this particular case, without using ts-ignore?

I have tried to use type narrowing (check that metadata[key] is not undefined before assigning a value to it), but it doesn't seem to work.

```
type TableData =  {
    id: string
    title: string
    icon: string
}

type Metadata = {
    url: string
    active: boolean
}

type CreateProps = Omit<TableData, 'id'> & Partial<Metadata>;

function create(props: CreateProps): void {
  const id = 'test';

  const tableData: TableData = {
    id,
    title: props.title,
    icon: props.icon
  }
  
  const metadata: Partial<Metadata> = { };

  for (const key of Object.keys(props)) {
      // Build metadata from those props which are not tableData
      if (typeof tableData[key as keyof TableData] === 'undefined') {
        // Now checking that metadata[key] is not undefined (doesn't have an
        // effect though)
        if (typeof metadata[key as keyof Metadata] !== 'undefined') {
          // Error:
          // Type 'string | boolean' is not assignable to type 'undefined' 
          metadata[key as keyof Metadata] = props[key as keyof CreateProps]!;
        }
      }
    }
  }
```
[Playground link](https://www.typescriptlang.org/play?ts=4.4.0-beta&strict=true#code/C4TwDgpgBAKghgIwDYQCJ2HKBeKUDeAUHngJYAmAXFAM7ABOpAdgObEnCnArV2OvsyAYwD2TXg2ZsAvoUKhIUALIRM5DFlxESUAK70kE-mx1whnAG4RqCESJRwmhWfPDQAwvQgYIABXoiYDQ4UADyALZcADzwyGgaADRQAOQUyQB8UABkUL5w9JxwSFEqahrpANxyAGa6TOakYlBCXj4AFGABQdSe3sB+XTQAlNQWIhQE7KJMdFATuMn9dMlVU2KzmHHomNSxKNuakzoUCYJQnNzWUJ2BNAB0Fyinx9PUN0F3pNPssnhrM8AoOFVHB1DtcvlCsVSqDyiF8FBpKs8NURPQoG1prMANYQEBQETVMIIABWEHMd1xIBoHUGQyGRx0UAA9MyoAAhXSkJDkIEgsFYaoBcLnAAWIho0HewQA7qKvqKoPloEwRIDNvsNGcyES2goIITzohNZgANpUpXBKmGvbxTAAXRw2AWdXIEGqzAg5GSDO0TLwrKgADkRDLmqLydipGKMHyymaqY7SMFVYDXe7Pby2uQRBAaExFlBRXArEqnP6A2z3dVyerxboWKKhtqSKRdfrDcD43BzXjLVBrUSYQLHQBCZ0pdMephen2MisstkAUXoAXolBbOkDMDcKT40YAPlBbPZvAW5im1ZaaKQWExjdBgCJzrvklPM8koJuSF3YQm+3AVp4oaw4aI6uDSr2+KAQOwFEr0Pj+Lc9qjlUC6-EyGF4Bh0hAA)

**Comment by mckravchyk** [comment]
Thanks. Is there any workaround to allow the assignment besides using ts-ignore?

**Comment by RyanCavanaugh** [comment]
I would a type assertion corresponding to why the code isn't actually wrong, e.g. `data2[key as 'test1'] = value`

**Comment by mckravchyk** [comment]
I'm sorry, to be more precise I'm looking for a workaround to the more complex example.

I understand that the compiler is right, but I'm not able to code something which is pretty standard without using ts-ignore on the error line.

[Playground](https://www.typescriptlang.org/play?ts=4.4.0-beta&strict=true#code/C4TwDgpgBAKghgIwDYQCJ2HKBeKUDeAUHngJYAmAXFAM7ABOpAdgObEnCnArV2OvsyAYwD2TXg2ZsAvoUKhIUALIRM5DFlxESUAK70kE-mx1whnAG4RqCESJRwmhWfPDQAwvQgYIABXoiYDQ4UADyALZcADzwyGgaADRQAOQUyQB8UABkUL5w9JxwSFEqahrpANxyAGa6TOakYlBCXj4AFGABQdSe3sB+XTQAlNQWIhQE7KJMdFATuMn9dMlVU2KzmHHomNSxKNuakzoUCYJQnNzWUJ2BNAB0Fyinx9PUN0F3pNPssnhrM8AoOFVHB1DtcvlCsVSqDyiF8FBpKs8NURPQoG1prMANYQEBQETVMIIABWEHMd1xIBoHUGQyGRx0UAA9MyoAAhXSkJDkIEgsFYaoBcLnAAWIho0HewQA7qKvqKoPloEwRIDNvsNGcyES2goIITzohNZgANpUpXBKmGvbxTAAXRw2AWdXIEGqzAg5GSDO0TJ0rKgAFF6AF6JRtUzAzA3Ck+FIoAAfKC2ezeJjJObBVWAuA0GikFhMY3QYAic6x5Ku92e71QSM6YFlM0WvNQa1EmECx24aXmvGW9t4w29Hz+W72gCEVX9vxIc+kQA)
```
type TableData =  {
    id: string
    title: string
    icon: string
}

type Metadata = {
    url: string
    active: boolean
}

type CreateProps = Omit<TableData, 'id'> & Partial<Metadata>;

function create(props: CreateProps): void {
  const id = 'test';

  const tableData: TableData = {
    id,
    title: props.title,
    icon: props.icon
  }
  
  const metadata: Partial<Metadata> = { };

  for (const key of Object.keys(props)) {
      // Build metadata from those props which are not tableData
      if (typeof tableData[key as keyof TableData] === 'undefined') {
          // Error:
          // Type 'string | boolean' is not assignable to type 'undefined' 
          metadata[key as keyof Metadata] = props[key as keyof CreateProps]!;
      }
    }
  }
```

**Comment by mckravchyk** [comment]
After some more thinking, using ts-ignore is probably the most elegant option if the actual solution would require writing some additional generic types. Unless there is something simple.
