### ISSUE TITLE
Too large modules

### ISSUE THREAD

**Issue by jjangga0214** [microsoft/TypeScript#45005]
# Suggestion

Some modules are too large.

For example, **src/compiler/checker.ts** has 42,797 lines, in one single file.

(Some other modules have a few thousand lines, though that MAY be viewed as suitable in some cases. )

I think that's too much and not so easy to organize and grasp, especially for contributors.

Even several IDE(e.g. vscode) extensions don't properly work for it.

Thus I suggest splitting the logic into more files. 

## 🔍 Search Terms

large file
large module
big file
big module
long file
long module

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
Related: #35210 / #27891.

**Comment by RyanCavanaugh** [comment]
The file is this large because it's faster to have more functions in the same closure when sharing state.

**Comment by jjangga0214** [comment]
@RyanCavanaugh 

But 42,797 lines are insane!
I guess there are other solutions?

1. Generate the closure as a single file: Like bundling!
*or*
2. Change language: Having to optimize THAT MUCH(e.g. 42,797 lines) may mean the initial choice of language was fundamentally wrong. We should consider porting to faster languages (e.g. C++, Rust, Go, etc).

**Comment by RyanCavanaugh** [comment]
We (the engineers on this team) all work in this file every day. If it were truly a problem that needed solving through some complex external tooling, we would have done it by now. It's not.
