### ISSUE TITLE
Complex combinations of discriminated unions and intersections give unexpected type errors

### ISSUE THREAD

**Issue by azhiv** [microsoft/TypeScript#45011]
# Bug Report

### 🔎 Search Terms
complex discriminated unions intersections error 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about discriminated unions.
- I noticed that in ver. 3.7.5 the behaviour is even worse (`foo1` and `foo2` calls also yield compile errors).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210712#code/MYGwhgzhAEDKYgKYQPICcAmi3QN4ChpoBLCWAFzAHNiA7KgOUUSwwEIAuaAIwHtekYWgG5C0ABaQAkgAcAwmAC22ME3IB3XmgDWsROQCuMzj36CRYtIgCOB4lbKUa9KeUSLHiY1z4DEQ0SJJCAANXgA3UgARREjgZBNfc0CJSAAhNGJgbQhyKyUYuISfM38LAF98fHIATxlEaDdcgFVaYl5aAEZoAF4xAAoCIiJSCmo6RmZWLjyDRBTy6AAyaEGxIOl5JRU1TR09QxkZtDmF6AAfPHXUiFkFZTRVfT3dfSMuADMECHmxcoBKf4XK7DEiOcb0JgsFifb6-UHBO7bR67LSvQ4lPwBP6iap1BpNcitdq0ABMvQGQ2GVls9mQY2cVFc7k8R0aJ3h0EWK36awR6Uy2Vy+UUhSyyGOpz+wKpGwgGSyOTy-lFsXFEFhIB+CyBPNlNzCkQgYviGvZUqIi0u+uChuiatNmu1f0B-zE1uuNLsDgZE2ZHgoXidnLlCqFyoKDolpixFn5oQi9qKZqSZQWuNq9WgECM2GJHV6jWQRLaHW6K0J+bJuI+BlowHIJOgH34nX6MjAj0UM2LVc6-y44V4xAwV0q+Fr9cbBZbvFJ7c7Sh7LVLZIH0CHI7HVUnDabs4XXa4OfqaCr683o6ps7bHa7-xSs-nd6UD-w45v-VoiHUcAQyHQLA0H6QFRCfL8fz-JBUEwbAQLfA9v1-eBoMAuDQPwIA)

### 💻 Code

```ts
class SalesOrder {
  isStagingNeeded!: boolean;
  hasIpCameraNetworkSetup!: boolean;
  requiresStagingItemsStep!: boolean;
  hasXovisDevices!: boolean;
  hasBrickstreamDevices!: boolean;
}

type testUnion1 =
  ({
    isStagingNeeded: true;
  } & ({
    hasIpCameraNetworkSetup: true;
  } | {
    hasIpCameraNetworkSetup: false;
  })) | {
    isStagingNeeded: false;
    // hasIpCameraNetworkSetup: boolean;
  };

function foo1(param: testUnion1): void {
}

foo1(new SalesOrder());       // error
```
Error:
```
Argument of type 'SalesOrder' is not assignable to parameter of type 'testUnion1'.
  Type 'SalesOrder' is not assignable to type '{ isStagingNeeded: true; } & { hasIpCameraNetworkSetup: false; }'.
    Type 'SalesOrder' is not assignable to type '{ isStagingNeeded: true; }'.
      Types of property 'isStagingNeeded' are incompatible.
        Type 'boolean' is not assignable to type 'true'.ts(2345)
```
When I uncomment the commented line the code successfully compiles.
Going further:
```typescript
type testUnion2 =
  ({
    requiresStagingItemsStep: true;
  } & (({
    hasBrickstreamDevices: true;
  } | {
    hasBrickstreamDevices: false;
  }) & ({
    hasXovisDevices: true;
  } | {
    hasXovisDevices: false;
  })))
  | {
    requiresStagingItemsStep: false;
    // hasBrickstreamDevices: boolean;
    // hasXovisDevices: boolean;
  };

function foo2(param: testUnion2): void {
}

foo2(new SalesOrder());        // error
```
Error:
```
Argument of type 'SalesOrder' is not assignable to parameter of type 'testUnion2'.
  Type 'SalesOrder' is not assignable to type '{ requiresStagingItemsStep: true; } & { hasBrickstreamDevices: false; } & { hasXovisDevices: false; }'.
    Type 'SalesOrder' is not assignable to type '{ requiresStagingItemsStep: true; }'.
      Types of property 'requiresStagingItemsStep' are incompatible.
        Type 'boolean' is not assignable to type 'true'.ts(2345)
```
Again, uncommenting the lines above makes the call valid.
And finally (with all three fields uncommented):
```typescript
type superUnion = testUnion1 & testUnion2;

function foo(param: superUnion): void {
  foo1(param);
  foo2(param);
}

foo(new SalesOrder());         // error
```

Error:
```
Argument of type 'SalesOrder' is not assignable to parameter of type 'superUnion'.
  Type 'SalesOrder' is not assignable to type '{ isStagingNeeded: false; hasIpCameraNetworkSetup: boolean; } & { requiresStagingItemsStep: false; hasBrickstreamDevices: boolean; hasXovisDevices: boolean; }'.
    Type 'SalesOrder' is not assignable to type '{ isStagingNeeded: false; hasIpCameraNetworkSetup: boolean; }'.
      Types of property 'isStagingNeeded' are incompatible.
        Type 'boolean' is not assignable to type 'false'.ts(2345)
```

### Important note
If I completely remove either `hasBrickstreamDevices` or `hasXovisDevices` from `testUnion2`, the error disappears ([playground link](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210712#code/MYGwhgzhAEDKYgKYQPICcAmi3QN4ChpoBLCWAFzAHNiA7KgOUUSwwEIAuaAIwHtekYWgG5C0ABaQAkgAcAwmAC22ME3IB3XmgDWsROQCuMzj36CRYtIgCOB4lbKUa9KeUSLHiY1z4DEQ0SJJCAANXgA3UgARREjgZBNfc0CJSAAhNGJgbQhyKyUYuISfM38LAF98fHIATxlEaDdcgFVaYl5aAEZoAF4xAAoCIiJSCmo6RmZWLjyDRBTy6AAyaEGxIOl5JRU1TR09QxkZtDmF6AAfPHXUiFkFZTRVfT3dfSMuADMECHmxcoBKf4XK7DEiOcb0JgsFifb6-UHBO7bR67LSvQ4lPwBP6iap1BpNcitdq0ABMvQGQ2GVls9mQY2cVFc7k8R0aJ3h0EWK36awRkDCkQghSyyGOpz+wKpG1CEWisVFEFhIB+C0B-zEl2l0BpdgcDImzI8FC8ytV12CgvlRSVpixFiI5VxtXq0AgRmwxI6vUayCJbQ63RWhK9ZNxHwMtGA5BJ0A+-E6-RkYEeihmftDnX+XHCvGIGCulXwEajMe98d4pKTKaU6ZaAbJ2egufzhaqJejsYr1dTXHd9TQoabLYLVIrieTqf+KQrVcnSmn+CL4-6tEQ6jgCGQ6CwaH6gNEs9X683SFQmGw+8X3bXG-gZ53l4P+CAA)).

### 🙁 Actual behavior

Type check for `foo(new SalesOrder())` call fails. It also fails for `foo1` and `foo2` calls if I remove `boolean` fields from the type definitions.

### 🙂 Expected behavior

Type checks succeed. And even further, I would expect the first two examples to compile without explicitly declaring fields as `boolean`s. But having done that, I would expect the last example to compile as well.

**Comment by RyanCavanaugh** [comment]
There is logic to allow union-propertied values to be assigned to unions-of-singletons, but it has a hard cap of 24 possible originating values because this is otherwise [too computationally expensive](https://en.wikipedia.org/wiki/2-satisfiability). In this case, when you have 5 union-propertied values that need expansion, that's 32 possible values, so the check is failed.

Aside, what are you trying to do here? `testUnion1` is empirically the same as `{ isStagingNeeded: boolean, hasIpCameraNetworkSetup: boolean }`. All these pass:
```ts
const v1: testUnion1 = { isStagingNeeded: false, hasIpCameraNetworkSetup: false };
const v2: testUnion1 = { isStagingNeeded: true, hasIpCameraNetworkSetup: false };
const v3: testUnion1 = { isStagingNeeded: false, hasIpCameraNetworkSetup: true };
const v4: testUnion1 = { isStagingNeeded: true, hasIpCameraNetworkSetup: true };
```

**Comment by azhiv** [comment]
@RyanCavanaugh Couple of thoughts here:

1. The investigation I conducted took almost 2 working days, which was very frustrating. The error popped up in irrelevant places in the code, now I see why. I'm not going to debate about this limitation, but a self-describing error message would be of great help. This `Type 'boolean' is not assignable to type 'false'` confuses a lot!
2. Jumping back to the first example with `foo1`. I still don't get why I have to declare `hasIpCameraNetworkSetup: boolean;` in the last union. It looks excess. Can you please explain?

Speaking of the origin of the problem. In our app we use [Zod](https://github.com/colinhacks/zod) for business logic validation. This library offers a rich toolkit, specifically [unions](https://github.com/colinhacks/zod#unions) . In combination with [literals](https://github.com/colinhacks/zod#unions) you can compose complex objects that are conditionally validated. A simple example:
```ts
const schema = zod.union([
  zod.object({
    shouldValidate: zod.literal(true),
    fieldToValidate: zod.number().positive(),
  }),
  zod.object({
    shouldValidate: zod.literal(false),
  })
]);
```
So when `shouldValidate` is true the schema requires `fieldToValidate` to be a positive number. When it's false, this field may hold any value. Moving forward, you can create several schemas of that kind, and then combine them using intersections. We followed this approach for quite a while, and suddenly, after adding another additional discriminator, adjacent code refused to compile.
I admit that the resulting schema appears to be very complex, but so is the business object which is being modelled by this schema.

**Comment by azhiv** [comment]
I skipped a couple of steps, but to give you the whole picture - this schema may define a type by using
```ts
type Model = zod.input<typeof schema>
```
which will produce
```ts
{ shouldValidate: true, fieldToValidate: number } | { shouldValidate: false}
```
Which can then be used to define a signature of a function (like `function bar(model: Model) { }`). Hope you got the idea.
