### ISSUE TITLE
Allow class expressions in type declarations

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#45014]
# Suggestion

## 🔍 Search Terms

class expression declaration type 

## ✅ Viability Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This feature would agree with the rest of[TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When a class is created by a static method, there doesn't seem to be a way to _directly_ use it as a class type.

## 📃 Motivating Example

Implementation:

```ts
class BaseClass {
    static cloneClass() {
        return class extends BaseClass { }
    }
}
```

How I would expect the declaration to look, with the type error present now:

```ts
declare class BaseClass {
    static cloneClass(): class extends BaseClass {};
    //                   ~~~~~
    // Cannot find name 'class'.
}
```

The declaration actually created:

```ts
declare class BaseClass {
    static cloneClass(): {
        new (): {};
        cloneClass(): any;
    };
}
```

## 💻 Use Cases

Similar to #45013: it's difficult to represent class "factories" like this one in type declarations.

**Comment by fatcerberus** [comment]
`typeof BaseClass`?

**Comment by RyanCavanaugh** [comment]
Same as #41581 / #41587

**Comment by JoshuaKGoldberg** [comment]
Super, thank you!
