### ISSUE TITLE
[FR] Auto-complete Fragments

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/TypeScript#45010]
## ✅ Viability Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Currently, unlike other tags, fragments can't be auto-completed, would be nice to have them supported.

## 📃 Motivating Example

Entering `<>` won't auto-complete `</>`:

![2021-07-08 21_49_47](https://user-images.githubusercontent.com/28700378/124933745-b38ab580-e036-11eb-9212-aa4700817813.gif)

**Comment by ShuiRuTian** [comment]
Strange, it seems this completion is not handled by tsserver.
I set a breakpoint on `executeCommand`(in `session.ts`), then add '>' for '<foo'. When the breakpoint works, the completion has already been added to the file. The log does not have any related info too, I think.
@RyanCavanaugh would you mind give a kind guide about possible related code? I do not have any idea now...
