### ISSUE TITLE
Allow value pointing to a class or whose type has a new signature to be used as a type

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#45013]
# Suggestion

## 🔍 Search Terms

refers to value used as type static class generic

## ✅ Viability Checklist

My suggestion meets these guidelines:

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When a class is created by a static method, there doesn't seem to be a way to _directly_ use it as a class type.

## 📃 Motivating Example

```ts
class BaseClass {
    constructor() {}

    static cloneClass() {
        return class extends this { };
    }
}

function takeBase(base: BaseClass) {} // Ok
takeBase(new BaseClass()); // Ok

const CreatedClass = BaseClass.cloneClass();

function takeCreated(created: CreatedClass) {}
//                            ~~~~~~~~~~~~
// 'CreatedClass' refers to a value, but is being used as a type here.
// Did you mean 'typeof CreatedClass'?

takeCreated(new CreatedClass()); // Ok
```

While `CreatedClass` is indeed a value, it's a value that happens to be equal to a class.

## 💻 Use Cases

In general, class factories like this are rather unwieldy to set up in the type system.

For a specific use case, see https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions/pull/57, as posted in SO at https://stackoverflow.com/questions/68201386/how-to-make-required-constructor-options-optional-when-they-were-set-using-mycla. Those Oktokit classes have a static `defaults` member that returns a new class. That new class has a constructor parameter whose type information must be informed by the previous static class' generic.

See [this playground link](https://www.typescriptlang.org/play#code/PTAEGEHsCcFNQJIFsAOAbWTYDsAuBDXAS0mwFgAoSovWaAM3wGN4ARWRgVzVwGcAxZrhgBPADzg0+XrwA0oftzQB5FMVK9QsAB64cAE00BvAL6gAvKFMA+K5VAPQ2WAHcAFJDUlsvAFwKlVXUfAEp-SWleAG5Ke0d9DnxuPjjHRzEAOVcg700dPWxDUAAFfGhifDQxRTQVLw1ra1S00BBQAE1YOVBcAAsiTWdYIuFQTl54PvgAOlmc0krS6HwkBHoAUVRcEVAAWl3QOCRIADdh0HoYUAAjOBOibea0twncYmwAcz9QLJd50Kejn87C4PAEQlEEikMnkAEEUOgRCCkmDqoF6j55L9-rxGjEKCZYhRtih4PDEcjkrwxDitLoDMYTFjshi8vTCozbOZmksKlVsazbAAyUDKJAPGms+QAa1gIkg9B+LOCuPxlDaABUuu8PkSaHoGMx4ABlFboWC0ozNehEaC8XD+e3QGgffFpCZMUj6fzYThIa50N2OTzBSoAfn810gkAw+GwQYcbQA2rKRI7cM7PgBdfycbDS7CQFzxyiEqgUJjQzQAfQAsiIAELSeBWijugjEJigBKgvhuHsovj+U2oDA4kJ2NstBxwXCcaDYUCVyJ0gojfrGQHTz0+DOcJjCaBuWbTMpffxxkRJrMT1vT++OXicUlHoygE8DqnyE9n3hJgAMWagNIoAjuatImCECYPqAZYPmYIGUmCggHpCdaNs28hgWOgrQWWzQ7k6+6Hh4rLDmaOEqreW49Bu0whrkFigAxGh4WqU4OCxPjkaOFqsvi+EUAky5wEuGi4KA9ZNhMwKJFSKGHuI6HSbAWEUXxKrWOx9B5ge3g9NqKluNczb+MpzbURxJkTPRrLTDadq4OxjhtAAAnwuw6KSB6edA0AwKk1mwLZKrTHmXmwAewwCUSbkeRFPl0P50CUM4LiSRhExuFB6pgO5vCedo3m4L5yWpa4GVGaYIS5aA+WFcVpUBRQaWVc2bhvg59r+AARD1sE5RQcUFQlJVJc1rVSe1b4el6-j-gN+KTZlsAdRctrdaAfXyLNhTzYt5XpVNWWdRtDpbT1O2RXNoD-vIXGVP4e7wJB2m6cEBn2sdq1ICt-jfZZaTDQ1kVjX5zVpL9Kkhbk9lndBwOjU1KUcaAUPNjDGjTLt+jQejNlcbwmPYJUCN5fFRWg8jzT48FhNhc4lNRbjpZEoREkAOoPL0-BnUx33TJ+YJrV150AORiwd5aI0zYNlS1FVc30vOOdl+Iy4140o61Ss82dHWQYdoC6yr9prTj+2vUbJv66djm9ZdoAW7dUs69zpu4CLZ0O1dO7erd90Yo9PTQJwL2DZQOnYHppCfbgNuqy47ve8byeOYDDhJ8rZ3E0TosJhrVNa6kWd645ufY9dhQJqXHsVw9aAF+TI2y9THG1zn9PhbL0Ws+W7Op30xpV-oTEJ-agtycLM0j5bEcK+luvD37avW9zy9egbg1u0PI9e-bF2u4r697zPftz0tx+7yvdubdtTuzy7VsL4PvQb4U+9347zt3cxQdoE9UO4c3rRw+noe0S896l3fv7SBfsM6gGgSPCu+cS4nz9hXHGNd0Fenrv-JudUKaa3BijRwSCMFd0ZsVXuBI2biVAAAJWGHmfQcYJKWHHrgSevZeCf3FieMWvsbq7AAIxSyNkw-QLC2GrxfpI6ReAt6X3SvIwoMjb7nT6kfFRzC1GKLPjdBaz9WqqNYfo9aB974-20Yw3RZjPYaJ9g-c+Ac-6hgASHMOUtC6JRIRIux6ixhUNBsMfwEtxEUCjjHRc4DcCmJkaXeJeB-C6ySbgBBiSAl4BQfDNBfQ0mYJHtg-JWSuH0wbgQ+qSNi7t25gUyho0aFliAA) for a version that uses an interface to describe the class, and [this playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4QPIAczAD2IGyA3gLABQytyMwUGYAXMs1KAOYDc1d7CAmIATNiACuAWwBG0PjTqF8REHAA2AfjYzChdRDggFAX2rUE6zKXRYA6sDAALAOIQQ0YAgA8ASRJgRkgAYhLq6ngExBgAfOT8SirRbP7MQRCh4ZGqGAoJtMIBUBIIYIRQABTKUSQpAemZEUkkAJTxigK0zsAYAHTVOcgAvMgD0QoCZlT57IEECMgiEPBhYBjeMwIA9FvIAHKEyADucACeyGXIoABWQmDIcMgARADKc14AgupQhiKnAApQQgAN2ASxET2QTmgEE2dDecHmewgR3UAKBoPBABo4bQEfNGtlosM0JgcM0MFjkDtkL06UYRBcnD0rqQNCdTjYyUSSDMYhVccgPKj0SCwRAxMh8V5kSLAWLwTM2pQOp0fmAJFAQMhLNZkBAAB6QEAiLn2RyudyeHyCgTYKSObzShCEilUgDWEFOhBgUveCFlaPlmIlMUFcRVnSjOuiYGKpXKFR+UjgoG4bH+cCgBA0Tv9rpqsWQADJkPbHc6CzkPV6fX7ETKUUGMeKRDFlbboxgJLhoBUyLS6cLmwqJVS6b1k6mQNxkCYWhNo5NO7QV7MGwsAPqbpYyCRcNiRpfRmBhdRsStnnm5NcCYenC-+wOikMiRfHufvzomL9TKbUJZdR+HUrAwM0UENY1TVJc1nDcDxOB8WxyULCN-yoGkAAE1gAWkNXtSjwqAgSgahhRgiAKgXagsNw-C7iIkiyJRCj+3nBRaIwPCDQIsBGPKZijlYgcGCYVhnkhdiaN2bCuPowjoCYqhyOQ-tBEKSUnieKTlJY1SRMYZg2C0qksA0tgAAYqR0lSyTU0SjIk0yhFESyqTGNRzwuYoUB0ixY2QBxnGCQz7hGZDeiWFZ1DWezQuMyTqOmKggqcEKxN6bdd33PIMJkuieIYxSBN0oTUvS5gqI4-K5MKhTiJK8jytCtiks47jeP40jSsCi0KrAOKxISuckqavqWoHMzXOQCyRoUMbgom+h4qc9TpqsubBN6xaxMGxyTLWk03NGZoNDYOMJF8pL-ICbanBeFyTRJZqMqiuBVgwNSpqOmbNuS1KHo0zKdwgPdeHMPLkFkjqioa7qFvux6RCq6SoYKzrivhliAaR1r5uxi1AdEPbxK0v6EaJk0vqRyy5upXYAAlCCEkRDiOFANAwQ5IHCK57jgXQJHuF7mE0ABCLacY0kmEuc8yZus0aCecSnkYMobVu+yUNo8s7vMuv6gA) for a verson that purely uses a static class. The former would be resolved nicely by this issue's requested feature; the latter would be doable in a more complex way if #26242 and/or #5863 are implemented.

cc @gr2m

**Comment by MartinJohns** [comment]
But you can refer to it using the `typeof` operator. This works just fine:

    function takeCreated(created: InstanceType<typeof CreatedClass>) {}

**Comment by JoshuaKGoldberg** [comment]
@MartinJohns true, but that's got pretty bad ergonomics. See the linked issue -- library authors shouldn't have to force the constituents into using type shenanigans like that.

**Comment by MartinJohns** [comment]
I really don't see how this is "type shenanigans". It's just how the type system is designed and works.

But const variables not introducing new types [is the intended behavior](https://github.com/microsoft/TypeScript/issues/43923#issuecomment-831357036).

**Comment by RyanCavanaugh** [comment]
Name resolution isn't allowed to have fallback behavior. Doing this creates a semantic trap where adding a new top-level type possibly changes the meaning of existing code. And obviously we can't change the behavior to *prefer* an inner-scoped `const` over an outer-scoped `interface`; this would be breaking beyond measure.

**Comment by JoshuaKGoldberg** [comment]
I think the root of what this issue is asking for ends up not being fallback behavior, but rather more permissiveness in defining new type system constructs through variable creations.

Today, this does create a new `MyClass` type [[playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABBATgUwIZTQYQDYYDOhAFAJSIDeAUIoulCCkhAcVQL7VfUQKFREAWQCe+IoUQBeZOiy42pMgG5q1MGgDuwsYvLKgA)]:

```ts
function createClass() {
  return class {};
}

const MyClass = createClass();

new MyClass();
```

However, this does not [[playground](https://www.typescriptlang.org/play?ssl=7&ssc=15&pln=1&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzDigxAGFoBnCgCgEoAueAbwCh55UQB3OxpgXwDcLfixZg8FDPACyAT3JQq8ALwEiJRVTrCWnLrIWUatQUA)]:

```ts
declare function createClass(): {
  new(): {};
}

const MyClass = createClass();

new MyClass();
```

The only difference between the implementation `return class {};` and the declared `: { new(): {}; };` is that a class expression today adds a new type but a `{ new(): ... }` does not. 

Regardless of whether I'm introducing new information or just rephrasing points already refuted 😉 , #41581 would give us an alternate syntax (`typeof class`) in the type system to represent what this issue is asking for anyway. So I'd be happy to just internally consider this issue a duplicate of that one. 🤷
