### ISSUE TITLE
Incorrect narrowing of outer scope variable updated in callback

### ISSUE THREAD

**Issue by ZhangYiJiang** [microsoft/TypeScript#45012]
# Bug Report

### 🔎 Search Terms

union, access, update, narrowing

### 🕗 Version & Regression Information

In every version I can test in TS playground, from nightly and 4.4.0 beta to 3.3.33333 

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type system behavior 

### ⏯ Playground Link

https://www.typescriptlang.org/play?strict=true&ts=4.3.5#code/C4TwDgpgBAqlC8UDeVSQFxQOQEMtQF8oAfZVcCTLAIywBoocBjJiAZzYBUALASzcxtgAJ14A7AOaEA3AFgAUABsIwKAFdMcRCjSVseGQoUAzAPbCoACiamxQqAA8op41ADaARgC6ASmQKoQKgAemCoHmgzRUVTAHdxKVjzAGs2KHFGaLiE8IBlVFN0sWMIC2BuHFUAAzUqqAq06ggIMSgmCskIABMAoND1BDJdKloGZlYOHn4qcoSAWxwAK14JfAIFdfkFTy8AOjNhAFFmbktLP3gAPn95IJCwgCE1VVm0rtN2KDFTYF7AtUGOgoI3ojBY7C4fAE2FmkgWy1WhA2PjkWzRvFcljUu10CHgiBoWD8SD+bVsbFMyl2MQkWN24whUzYPg2CiAA
### 💻 Code

```ts
type U = { type: 'a' } | { type: 'b', accessThis: string };
let u: U = { type: 'a' };

for (const x of [1]) {
    // The following works in allowing TS to infer that `u` has been changed
    // u = { type: 'b', accessThis: 'thingmajig' }
}

[1].forEach(() => {
    // But this does not
    u = { type: 'b', accessThis: 'thingmajig' }
});

// This line errors because TS still thinks u is { type: 'a' }
if (u.type === 'b') {
    console.log(u.accessThis)
}
```

### 🙁 Actual behavior

TypeScript cannot infer that in the above, the variable `u `has been updated and therefore it should no longer be narrowed 

### 🙂 Expected behavior

TypeScript should recognize the variable could have been updated 

Worked around this by rewriting it as a reduce, which to be fair was what this was in the first place, reduce is just a bit trickier to use correctly

**Comment by MartinJohns** [comment]
#9998

**Comment by ZhangYiJiang** [comment]
Thanks for finding the duplicate!
