### ISSUE TITLE
Control flow analysis in class static initialization

### ISSUE THREAD

**Issue by tchetwin** [microsoft/TypeScript#45023]
# Bug Report

### 🔎 Search Terms

static, initialization

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `static initialization`

Suspect since TypeScript has supported `static` fields (eons), and more noticably with `4.4.0-beta` with class static initialization blocks.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&jsx=0&ts=4.4.0-beta#code/N4KABGA2CmAuYEMBcYB2BXAtgI2gJwG5wwBjSBAZwrAEExQIILYFYBLE+4xxMAXjABGAAxEeAX2KSICAmAD08sADUEeNgmwwwAcgQ6wbaugrQAJmFwAzAPZ5ol6G1QBzRFTYvU5gHQAKACYAFgBWIIBKEEkQRTAAWgTEhJAQBig4UhQMHHwxUnIqMABhLh5mVg4wK34wP04BEXC86VI5WNV1TW0dEgMjMBNzR1t7R2c3SgpPbzN-YLDIySA)

### 💻 Code

```typescript
{
  let a: number;
  class A {
    static {
      a = 10;
    }
  }
  a; // Variable 'a' is used before being assigned.(2454)
}

// --------

{
  let c: number;
  class C {
    static f = (c = 10);
  }
  c; // Variable 'c' is used before being assigned.(2454)
}
```

### 🙁 Actual behavior

TypeScript does not identify that the variables `a` and `c` have definitely been initialized following execution of static initialization in the class (either in a static field initializer, or in a shiny new static class block). 

### 🙂 Expected behavior

Control flow analysis spots that all paths initialize `a` and `c` and does not error.

### ✏ Commentary

The "c" example is a little far-fetched/weird, but the "a" example will perhaps be increasingly common. The [proposal](https://github.com/tc39/proposal-class-static-block/tree/bc3291544c56f49fc887372494d0cf62ac3df624#motivations) specifically lists this as an example:

```javascript
let getX;

export class C {
  #x
  constructor(x) {
    this.#x = { data: x };
  }

  static {
    // getX has privileged access to #x
    getX = (obj) => obj.#x;
  }
}

export function readXData(obj) {
  return getX(obj).data;
}
```

Which invites users to initialize things outside the class from the static blocks. In this instance the usage is within `readXData`, so [there's no error](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&jsx=0&ts=4.4.0-beta#code/DYUwLgBA5uAaBcEAUBjRBhAlBAvAPggG8IATAQzDMQDsBXAWwCMQAnCAXwG4AobkADwAOAexaQUwMgGcpEdEW4QIAYn6Ji5SjQbM2XRRBTDqUsC1oowopGoh0mrbIQNKwACwCWUgHSrcRUgoqCH4OHiV2XiVTCg8UBSUlAHok6DgIN2kIQRYPADcPUBgSCDIUFBAZCCsVfhc0sFh-JGFGACsMbHwIVrbffnCObki+IVFIADNaaksPYwgWEDISWAARIJb2zoSF8FoWagbYTbbMb00yHnYgA).

**Comment by MartinJohns** [comment]
Seems like a duplicate of #44949.

**Comment by tchetwin** [comment]
> Seems like a duplicate of #44949.

Oof, missed that one, looks like a dupe indeed. Will add some points in a comment there. Thanks!
