### ISSUE TITLE
Include all directories and sub-directories using '*' (wildcard) in tsconfig.json `paths`

### ISSUE THREAD

**Issue by searleser97** [microsoft/TypeScript#45024]
# Bug Report

### 🔎 Search Terms

- tsconfig paths
- subdirectories

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `tsconfig paths`

### 💻 Code

![image](https://user-images.githubusercontent.com/5056411/125632873-7e2d6b36-dd3e-4659-aa3b-45dfad10f00a.png)

### 🙁 Actual behavior

can't add all subdirectories to `tsonfig paths` using wildcards (*). I have to add them one by one.

### 🙂 Expected behavior

be able to use wildcard characters (*) to include all subdirectories with a single entry instead of one for each subdirectory.

**Comment by andrewbranch** [comment]
What environment would support those paths at runtime?

**Comment by searleser97** [comment]
> What environment would support those paths at runtime?

the objective of it would be to avoid writing paths for imports and instead just use "unique filenames", I know that with `Flow` that is possible

**Comment by andrewbranch** [comment]
I’m asking what _runtime_ would support such a scheme. Suppose we allowed you to do this, and you wrote `import "foo"`, referring to a file at `./Test/one/fish/two/fish/foo.js`. You compile, and your JS output still says `import "foo"`. Now what are you going to do with that file? Node doesn’t know that `"foo"` resolves to `./Test/one/fish/two/fish/foo.js`. Webpack doesn’t know. Deno doesn’t know. Browsers don’t know. Where can you successfully run this file?

**Comment by searleser97** [comment]
There are some libraries that transform import paths like [ts-transform-paths](https://www.npmjs.com/package/@zerollup/ts-transform-paths) when compiling to `javascript`.

**Comment by Jalliuz** [comment]
Working code: <br/>

My jsconfig in toplevel folder
````
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/*": [
                "./node_modules/*",
                "./apps/node_modules/*",
                "./apps/app-one/node_modules/*",
                "./apps/app-two/node_modules/*"
            ],
            "~/libs/*": ["./libs/*"]
            "~/packages/*": ["./packages/*"]
        }
    }
}
````
my vue.config.js in directory `apps/app-two/vue.config.js`. 
````

module.exports = {
  // ...
  configureWebpack: {
    resolve: {
      alias: {
        // This line with the ** does not translate to the jsconfig/tsconfig
        '@/': '**/node_modules',
        '~/libs/': path.resolve(__dirname, './../../libs'),
        '~/packages/': path.resolve(__dirname, './../../packages'),
      },
    },
  },
}
````
My webpack.config.js in folder `apps/app-one/htdocs`
````
Encore
    // ... more config
    .addAliases({
      // Again this line with the ** does not translate to the jsconfig/tsconfig 
      '@/': '**/node_modules',
      '~/libs/': path.resolve(__dirname, './../../../libs/'),
      '~/packages/': path.resolve(__dirname, './../../../packages/'),
    })
````
So solution is indeed to add every path to every node_modules folder yourself in jsconfig or tsconfig
