### ISSUE TITLE
Interface merging losing members after multiple merges in monorepo project.

### ISSUE THREAD

**Issue by BrianMar** [microsoft/TypeScript#45028]
I'm working in a monorepo. We have a type we'll call "EditorSettings" in Project A. A is used by B, and A and B are used by C, D by... you get the idea.

In A:
`export interface EditorSettings {
  locale?: Locale;
  cFlag1?: boolean; 
}`

Somebody in project C decided to add a specific setting for their project C feature, and they added it directly to the type in Project A. To fix the dependencies, I decided to instead have  C define it:

In A:
`export interface EditorSettings {
  locale?: Locale;
}`

In C - File 1:
`declare module 'A' {
  export interface EditorSettings {
    cFlag1?: boolean; 
  }
}`

This works as expected. In A, EditorSettings only has 'locale'. In C, EditorSettings has two members, "locale" and "cFlag1".

 (For completeness sake only, the only interesting thing I notice is that if I get to an EditorSettings object indirectly through something from the A space, it has the type of EditorSettings from A. I can work around that with a temporary variable, and I can see this being correct.)

However, multiple flags were added from C. When I added a second instance of this pattern to another file in C, however:
In C - File 2:
`declare module 'A' {
  export interface EditorSettings {
    cFlag2?: boolean; 
  }
}`

Then the interface "EditorSettings" when viewed in C only appears to have two members, "cFlag1" and "cFlag2". The initial "locale" is gone.

If I now look at "EditorSettings" from project D, it's picking up the C version without "locale". So the interface merge is taking place, but it's giving me an incorrect result from this point on.

Which means code in D that is setting a member from the initial interface declaration in A no longer compiles.

Here are the cases I've tried so far:

* If I put two new interface definitions for EditorSettings in two different files in C, then the interface loses everything that was defined in A.
* If I put two new interface definitions for EditorSettings in the same file in C, then the interface merges correctly. D continues to compile because "locale" is part of EditorSettings.
*  If I put one new interface definition in B and one in C, then D will see EditorSettings with the two new interfaces and nothing from A (same as two separate files in C)
*  I attempted to create a sample project with this issue, but I couldn't reproduce the problem just by using multiple files in a single project repo. Both the single file and two file versions merged fine.

**Comment by BrianMar** [comment]
We use a similar pattern for some lower level dependencies from outside the repo, and it appears to work correctly. The error occurs with Typescript version 4.3.5 in VSCode and 4.2.4 which we use in our build environment.

**Comment by RyanCavanaugh** [comment]
Without a way to reproduce this problem, we're not likely to be able to help diagnose this or fix any potential root cause

**Comment by BrianMar** [comment]
This is an internal Microsoft repo, so I can share it with you directly. I still haven't been able to isolate to a smaller case outside of our repo.

**Comment by RyanCavanaugh** [comment]
Please email me instructions and I'll get it forwarded to someone to investigate. Thanks!

**Comment by BrianMar** [comment]
This turned out to be user error, though driven by the compiler warnings.

If you don't import an interface from another library, and then attempt to extend it:

`declare module '@fluidframework/core-interfaces' {
  export interface IFluidObject {
    y?: boolean;
  }
} `

This will actually overwrite the original definition. Which is what I was seeing. 

You need to import the original type for augmentation to work:

`import { IFluidObject} from '@fluidframework/core-interfaces';

declare module '@fluidframework/core-interfaces' {
  export interface IFluidObject {
    y?: boolean;
  }
} 
`

However, if this is extent of your file, you will get an error that 'IFluidObject' is declared but its value is never used. This is also true for the "import type" variation.

So you need to make sure that you make the augmentation in a file that also uses the type. In my case, I have separate interface and implementation files, and I was adding this to the interface file that didn't use this type. Since the compiler flagged this unused type, I thought it was safe to delete the import. It isn't.

I could see this as a bug where augmenting and interface should count as "using" a type, but that's a different issue. Marking this issue as closed.
