### ISSUE TITLE
Incorrect narrowing for nested tag unions

### ISSUE THREAD

**Issue by RReverser** [microsoft/TypeScript#45027]
# Bug Report

### 🔎 Search Terms

"nested union narrowing", "nested tag union"

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ.

### ⏯ Code

```ts
type Config =
  | { type: 'text'; value: string }
  | { type: 'number'; value: number }
  | { type: 'window' | 'section'; children: Config[] }
  ;

function foo(config: Config) {
  if (config.type === 'window' || config.type === 'section') {
    return '';
  }
  return config.value; // <-- Property 'value' does not exist on type '{ type: "window" | "section"; children: Config[]; }'.
}

type Config2 =
  | { type: 'text'; value: string }
  | { type: 'number'; value: number }
  | { type: 'window'; children: Config[] }
  | { type: 'section'; children: Config[] }
  ;

function foo2(config: Config2) {
  if (config.type === 'window' || config.type === 'section') {
    return '';
  }
  return config.value; // <-- OK
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function foo(config) {
    if (config.type === 'window' || config.type === 'section') {
        return '';
    }
    return config.value;
}
function foo2(config) {
    if (config.type === 'window' || config.type === 'section') {
        return '';
    }
    return config.value;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.4.0-beta&filetype=ts#code/C4TwDgpgBAwg9gOwGYEsDmUC8BYAUFKAHygG8pRIAuKAcmAgA9gaBuKANwEMAbAVwmoBnYACcUCDAF88BYmQoDaCXgFsARhBGsOPftWXrNUafiKly4RTQDu4gCZxrNMzUEQAxsBSJt7gBYo3HYiEAjU8MjoANoAusYyUCx4eEi8CJ7eCFBIcHAAFO6IqGjhRegAlKQJKEhQBWVoAHQKWJiYtLYIDk5ExIWRTS1t7a4eXj6VJAkEIcC8Ilk0rAkmMxBzC1D9xY1cfBBJuCZ4LRHFAExYCXIWVLT0TNp7elDCYhLxpjcK1DQGGlo2M9FP8jKszPJLL9Ot1fAEgiEwrAGrFPrJzD9aG4Mj42P5AsFQqUBqjwYcUmkcVkcnBzvUBsSLpNqrV6Tshm0OvZHM5CH0Gs1LK0RtjxggaMzTGsNotlqZwbN5lltuhdroDngTEA)
      

### 🙁 Actual behavior

Getting an error in `foo`: `Property 'value' does not exist on type '{ type: "window" | "section"; children: Config[]; }'.`

This is strange because changing `config.value` to `config.type` on that last line of `foo` and hovering over it shows that it was correctly narrowed to `"number" | "text"`. However, the `config.value` access shows the error above that suggests that `config` was narrowed to `{ type: "window" | "section"; children: Config[]; }` instead, even though it's the branch that was supposed to be discarded by `if`.

### 🙂 Expected behavior

`foo` to compile successfully, just like `foo2`.

**Comment by RyanCavanaugh** [comment]
The problem here is that narrowing proceeds step-by-step, and after determining `config.type === 'window'` to be false, we can't narrow the union at all -- its original three constituents are still around. If there was a *single* operation to exclude `window` and `section` as an atomic step, then the code would work as expected:
```ts
declare function isWindowOrSection(s: Config): s is Config & { type: "window" | "section"};

function foo(config: Config) {
  if (isWindowOrSection(config)) {
    return '';
  }
  return config.value;
}
```
We'd need negated types to form a new type, `Config & { type: not 'window' }` at the `||` point in order to make this work.

**Comment by RReverser** [comment]
Okay, that makes sense I guess.

I still don't understand why the error says "Property 'value' does not exist on type '{ type: "window" | "section"; children: Config[]; }'." though - the worst case scenario, it should say "on type Config", no?

It feels very confusing that it shows the type that was narrowed inside the `if`.

**Comment by fatcerberus** [comment]
> I still don't understand why the error says "Property 'value' does not exist on type '{ type: "window" | "section"; children: Config[]; }'." though - the worst case scenario, it should say "on type Config", no?

It actually *does* say "on type `Config`"--the subsequent message is simply elaboration telling you *which constituent of `Config`* caused the assignment to fail and has nothing to do with the attempted narrowing. The fact that it matches the type you were trying to narrow away inside the condition is just a coincidence.

Whenever you see multiple lines for an assignability error, you can mentally prepend "because" to every line after the first.

**Comment by RReverser** [comment]
Hmm I see... but surely you agree if this can't be fixed in the short-term, then at least diagnostics can be improved in this case. Most users (me included) are not aware of internal design limitations.

**Comment by RReverser** [comment]
> We'd need negated types to form a new type, `Config & { type: not 'window' }` at the `||` point in order to make this work.

FWIW I think this can be achieved even via existing tools. Something like:

```ts
type ExcludeKV<Obj, K extends keyof Obj, V extends Obj[K]> = {
  [K2 in keyof Obj]: Exclude<Obj[K2], K2 extends K ? V : never>
};
```

would allow step-by-step narrowing by tag:

```ts
type ConfigButNotWindow = ExcludeKV<Config, 'type', 'window'>;
type ConfigButNotWindowAndNotSection = ExcludeKV<ConfigButNotWindow, 'type', 'section'>;
```

If TS can express this, then it can probably generate this internally as well.
