### ISSUE TITLE
Feature Request: Support for refactoring dynamic key interfaces.

### ISSUE THREAD

**Issue by EricLiuCY** [microsoft/TypeScript#45036]
# Suggestion

There's currently no way to rename globally references to a dynamic key in an interface. 
Let's say I have the following enum + interface setup for a simple user using dyanamic keys
```
const enum UserFields {
    id = 'id'
    name = 'name'
}

# Dynamic Key Version
interface IUser {
    [UserFields.id]: string;
    [UserFields.name]: string;
}

# Static Key Version
interface IUser {
    id: string;
    name: string;
}

# getUser returns a IUser object, and I can access interface properties
function foo () {
    const user : IUser = getUser();
    const userId: user.id;
    const userName = user.name;
}
```
Currently, if I were to press f2 on a static interface key, it would rename all the global properties. So for example, if I press f2 on 'name' in IUser and rename it to 'namesXXX', it would rename the reference in function foo from 'user.name' to 'user.namesXXX'

However, this renaming feature is not supported if I use dynamic keys in the interface.-->

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ X] This wouldn't change the runtime behavior of existing JavaScript code
* [X ] This could be implemented without emitting different JS based on the types of the expressions
* [ X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
The example is littered with syntax errors. Can you be more specific about which rename location you would expect to cause which edits?

**Comment by EricLiuCY** [comment]
@RyanCavanaugh Sorry about the syntax errors, I've created what is hopefully a better example.

![image](https://user-images.githubusercontent.com/35042747/127827161-1e55829f-d4d8-4ce0-b8a2-3455785a1851.png)

The idea is that I want to have a single point of access for variable naming in my MERN app for improved consistency. So I'm trying to accomplish that by using enum as a dynamic key in my interfaces to keep the variable naming consistent, as shown above.
 
![image](https://user-images.githubusercontent.com/35042747/127827858-77c33c02-b8fd-4d68-a0ad-5018d2ea1750.png)

TypeScript on VSCode has this fantastic feature where if you f2 a variable name in the interface, it renames that variable name instance in the class fields too, as shown above when trying to refactor bar.

![image](https://user-images.githubusercontent.com/35042747/127828121-cb3431b7-17ff-4123-a95d-7a7e02fb0d4c.png)

However, if I use a dynamic key in my interface, and try to rename the dyanamic key from foofields.bar to foofields.test, it renames the root declaration in fooFields along with all references. However, it is not renaming ```public bar : string ``` in the class.

![image](https://user-images.githubusercontent.com/35042747/127828846-128fad40-c6ef-42fd-a956-a3620285dec7.png)

Or if say I want to rename the string literally declaration in the enum from ```bar = 'bar'``` to ```bar = 'bark'```, it would be great if ```public bar : string``` in class Foo gets renamed to ```public bark : string```

**Comment by RyanCavanaugh** [comment]
Please use text, not screenshots (otherwise I would spend all day transcribing or trying to OCR stuff). Plus they're not searchable
