### ISSUE TITLE
Change phrasing for "default property value" diagnostic

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#45049]
In https://github.com/microsoft/TypeScript/pull/43005, we added a diagnostic:

> "Missing '=' before default property value.

But these aren't default property values - they're initializers. I guess they're "defaults" in the absence of any other values, but that's not really the right term.

I think it should be

> "Expected '=' for property initializer.

or

> "Missing '=' for property initializer.

**Comment by DanielRosenwasser** [comment]
(@JoshuaKGoldberg in case you're interested)

**Comment by roottool** [comment]
@DanielRosenwasser I guess `Expected '=' for property initializer.` is the best. Because I think unified words is better than non-unified words. The some error messages uses `Unexpected` or `expected` in #43005.

**Comment by JoshuaKGoldberg** [comment]
Looks like @a-tarasyuk has got it already 😄 , but thanks - makes sense!
