### ISSUE TITLE
class method destructuring assignment autocomplete not work

### ISSUE THREAD

**Issue by mantou132** [microsoft/TypeScript#45045]
# Bug Report

### 🔎 Search Terms

autocomplete intellisense

### 🕗 Version & Regression Information

4.3.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.3.5#code/JYWwDg9gTgLgBAbzgYQDbAKYDt4F84BmUEIcA5AAIDmUYAxgPQ30C0AVgM5kDcAULzACeYDHAAKxEMA7ACggDwAVAHxwAvHEVwAZLwS84cANoBpOMCxwAogA8YUAIZ0Y8gNYZBEApoA0cDvYWVKoOHHAABgAkCCa4EiTSGOEAugBcmqbJcBh22AAmYQAUBoZwUBgAjukWBBhQcABKlT4lhiAgGDAOeQ5d1Vi19QCynd29Di2lcBBgMMAQWP2DcADys-NYk6V0DqioAEZOrumFAPp1UOkOWIJ+5RxLdY0YHACU6qoAbhDAeVvvai+PzyrTgAH44Ep1M8OMpCuUqs8Kn52qMel0wekRl10RNpusFpjVgSsADVPEpBwMEplKD0lgMJ86nxcHxeHRUKEwgBlOqfYB0UT6NqdAAWEDyhXewtKqE6-j5AtEGgAjHBQuJJNJZAo0JgcMo+FM6AsAoh8BoqVB+YKjXBcLxcEA

### 💻 Code

```ts
import { Client } from '@grpc/grpc-js';

type Promisify<T> = T &
{
  [K in Extract<keyof T, string> as `${K}Promise`]: T[K] extends (
    req: infer Req,
    mmetadata: infer Metadata,
    option: infer Option,
    callback: (_err: any, res: infer Res) => void,
  ) => void
    ? <T = Res>(req: Req, mmetadata?: Metadata, option?: Option) => Promise<T>
    : never;
};

class Service {
  method() {
    let service = 1 as Promisify<Client>;
    const { /** press ctrl+space */ } = service;
  }
}
```

### 🙁 Actual behavior

When I press <kbd>CTRL+SPACE</kbd>, not displayed correctly suggest.

<img width="579" alt="Screen Shot 2021-07-15 at 8 03 01 PM" src="https://user-images.githubusercontent.com/3841872/125785942-61abcbc2-2485-49ba-894c-575fa47ab324.png">

### 🙂 Expected behavior

When I press <kbd>CTRL+SPACE</kbd>, should display the method suggest. e.g:

<img width="633" alt="Screen Shot 2021-07-15 at 8 03 12 PM" src="https://user-images.githubusercontent.com/3841872/125785982-b226ae57-676c-4747-b391-bbfd2d911110.png">

**Comment by RyanCavanaugh** [comment]
@gabritto this is actually a crash in the LS. Looks possibly similar to the txstate issue we were looking at yesterday?
