### ISSUE TITLE
Generic conditional doesn't generate correctly for arrow functions

### ISSUE THREAD

**Issue by PatrykWalach** [microsoft/TypeScript#45048]
.d.ts generic conditional doesn't generate correctly for arrow functions

```ts

interface Y { }

function no_bug<T extends unknown = Y extends { k: infer U } ? U : unknown>() { }

const bug = <T extends unknown = Y extends { k: infer U } ? U : unknown>() => { }
```

<details><summary><b>Output</b></summary>

```ts
interface Y {
}
declare function no_bug<T extends unknown = Y extends {
    k: infer U;
} ? U : unknown>(): void;
declare const bug: <T extends unknown = unknown>() => void;

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.3.5#code/FASwdgLgpgTgZgQwMZQAQE1UG9UF9jBwCuYSEIA9mKmBQPoBGRA5gDwAqqUAHtGACYBnVCQDWtAO7UAvBi68oA4TlEAuVODixUAVTyoA-LtTqxksAD4AFAEpseAsCRVBEVE2apZHeXyEiwcQopLzkeP2VUNQ0wLRhjXENjU0DzaztpC2xcIA)

**Comment by weswigham** [comment]
This is working as intended - in the function case, we're reusing the type nodes you wrote verbatim, while in the arrow case, we're writing the witnessed type of the expression - which, the default immediately evaluates to `unknown`, since there's nothing actually generic in it.
