### ISSUE TITLE
Only warn for unused functions and imports during development

### ISSUE THREAD

**Issue by Geigerkind** [microsoft/TypeScript#45043]
# Suggestion
## 🔍 Search Terms
allow unused imports, allow unused functions

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [ X ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ X ] This wouldn't change the runtime behavior of existing JavaScript code
* [ X ] This could be implemented without emitting different JS based on the types of the expressions
* [ X ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ X ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
I, as developer, dont want to be constantly annoyed by the compiler exciting because I uncommented some function while debugging code, such that it became unused.

Ideally I would like the compiler to spit out warning during development and spit out errors during production compile.
I can also imagine to add compiler options such as "allowUnusedImport" and "allowUnusedFunction". Currently only unused Variables and parameters are supported.

## 📃 Motivating Example
```
function debuggedFunction(): void {
   ... some code ...
   // someFunctionIBrieflyWantToCommentOut();
   ... some code ...
}

private someFunctionIBrieflyWantToCommentOut(): void {
   ... some code ...
}
```

## 💻 Use Cases
* Development
* Debugging

**Comment by RyanCavanaugh** [comment]
> Ideally I would like the compiler to spit out warning during development and spit out errors during production compile.

See https://www.typescriptlang.org/tsconfig#extends for how to easily configure separate "development" and "production" compiles.

**Comment by RyanCavanaugh** [comment]
Or maybe it sounds like you're asking for something to flag unused imports, separately from the dev/prod distinction? There are lint rules you can enable for those already, which fits your criteria well

**Comment by Geigerkind** [comment]
Hey @RyanCavanaugh ,
Im not sure we understand each other. Im aware that I can configure separate configs for production and development. 
What frustrates me is that I constantly have to either remove unused imports or unsued functions or flag them with "@ts-ignore", 
when I just want to briefly comment something out to see if that was the issue.

The error that is spit out at least when I have an unused function is "TS6133". In my opinion it should be configurable if it is a warning or a hard error. As hard error it is just really really annoying during development.

**Comment by RyanCavanaugh** [comment]
> What frustrates me is that I constantly have to either remove unused imports/functions or flag them with `@ts-ignore`,
when I just want to briefly comment something out to see if that was the issue.

If you have separate configs, why isn't your dev config set up to ignore unused imports? Isn't that the request?

>  In my opinion it should be configurable if it is a warning or a hard error

There's no warning/error distinction anywhere in TypeScript.

**Comment by Geigerkind** [comment]
@RyanCavanaugh 
Yeah, that and unused functions.
Could you link me the unused imports/function flag that I have to set?
I cant seem to find those, otherwise I wouldnt have made this suggestion in the first place, I suppose :)

**Comment by RyanCavanaugh** [comment]
There isn't a TS setting for this (see #30517), but it can be detected by a syntactic linter

**Comment by Geigerkind** [comment]
I dont want to detect dead exports though. On the contrary. I dont want the typescript compiler to throw an error on an unsused import or if the file has an unused function.
So if there is no option for this, this suggestion is quite valid then, isnt it?

**Comment by RyanCavanaugh** [comment]
> But I dont want to compiler to throw an error and exit. I want it to throw a warning an proceed.

The behavior you're describing here is `noEmitOnError` being on vs off

**Comment by Geigerkind** [comment]
@RyanCavanaugh ,
Hi, thanks for answering.
Neither true, nor false seems to have the desired effect.
In both cases this error is emitted and the compilation does not proceed. I have to annotate or remove the function in order to proceed.
```
Failed to compile.

src/app/app/components/app/app.component.ts:38:11 - error TS6133: 'wambo' is declared but its value is never read.

38   private wambo(): void {
```

**Comment by RyanCavanaugh** [comment]
TS does not issue the "Failed to compile" message; this indicates you're using a third-party build tool which would need to provide functionality for disregarding the tsc error code

**Comment by Geigerkind** [comment]
True, I use angular.
I will dig deeper if that is something specific to it.

**Comment by Geigerkind** [comment]
For anyone stumbling over it as I did, set following configurations:
```
"angularCompilerOptions": {
    "noUnusedLocals": false,
    "allowUnusedLabels": true
    ...
}
```

Thanks @RyanCavanaugh for bearing with me!
