### ISSUE TITLE
`Object.entries(Record<K, string>)` should get `[string, string]` but get `[string, unknow]`

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#45064]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=12&ssc=2&pln=1&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX1RxgFsoIsAvEACgAcAueAZwxi1QHMBKRltzgLAAoYSAAetIhiRpMufAAsoqYBBAAFKGADWUDiABC7JgB4A0vHEYQKps1bsOAPmoAjY4wBK4IsHMAae35nLmEAb2EASDgMZBh8AHlXACtwDAA6GwcQJjdjUKFIyPS4YGQwGmooQIBtbUD3VABdLngAXicoyIjCosISMkoaRoL4MfGJsag6pvb4Rq7okFj4+CgugF9AsI21u28wXwCgxycCjaA

### 💻 Code

```ts
entries<T>(o: { [s: string]: T } | ArrayLike<T>): [string, T][];
```

```ts
declare function normalize(p: string): string

export function handlePackageBins<K extends string>(bins: Record<K, string>)
{
	return Object.entries(bins)
		.reduce((a, [k, bin]) =>
		{
			normalize(bin)
            a[k] = bin
			return a
		}, {} as Record<K, string>)
}
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/167966/125920490-48123013-f46e-462f-84f0-089b325e3131.png)

### 🙂 Expected behavior

`string`

**Comment by MartinJohns** [comment]
See #43266.
