### ISSUE TITLE
Spreading the object with false condition

### ISSUE THREAD

**Issue by mackankowski** [microsoft/TypeScript#45066]
# Bug Report

## TypeScript v.4.3.5

Hi, I've found a potential TypeScript bug while spreading the object.

### 🔎 Search Terms

_Spread types may only be created from object types_

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/ATDGHsDsGcBdgK6QCYFMBmBLSrkDUBDAGwVQC5gDIBPYAXkRQ21wG4AoECGeTaAFQBOpesFjDUHTsAD0M4AHdwggNbQy07nGDgARgCsAjKIDewAHSWAFAEIkaLDnzERAMlfAzADwoAiaOAAtqiEJKi+wAC+AJRRHCByispqGlxQ2nr6AEymFtb2zE6hbh7efgHBxeFRsZHxsvLEAQA0SarqmunwmQDMuZbmVnxCJZ7APsD+QSEu1TFx0onI4KjQkADk8EqqlDSByuSdPDoGACz91jbDEsDuYxNTlbMR83XSi-K+AMoADoKoBGQYmoP1WwECBFoUCItF0qDA-wIsFwwHQgiCJ30qFA8FgINW5lg0CsWQAbABOAAc0V8HzE0GAy1WG3gBFAoFQP3g6Ca8IAbrNgFZdAhWTRgaDgHxUSxoq1UHzUJBgPoGaAqMA-uAOdAGZhYBogA

### 💻 Code

```
  const undefinedValue: any = undefined;
  const isTrue = true;

  // works:
  const obj1 = { ...(!undefinedValue && { x: "someValue" }) };
  // works:
  const obj2 = { ...(undefinedValue && { x: "someValue" }) };
  // also, works:
  const obj3 = { ...(isTrue && { x: "someValue" }) };
  // doesn't work anymore:
  const obj4 = { ...(!isTrue && { x: "someValue" }) };
  
  // "Spread types may only be created from object types.ts(2698)"
  // ts doesn't accept false value (but any type is fine), even js can process it:

```

### 🙁 Actual behavior

Getting the following error:

![image](https://user-images.githubusercontent.com/9574907/125937404-e2d3ebe7-f8ba-47b5-bdaa-1e4ca27ec904.png)

### 🙂 Expected behavior

No error - JS works as expected. Or maybe it's a feature that I don't get it ;-)

**Comment by mackankowski** [comment]
Similar issue: https://github.com/microsoft/TypeScript/issues/37491

**Comment by MartinJohns** [comment]
@mackankowski That's not a similar issue, that **is** your issue.

You can write `const isTrue = true as boolean;` to make TypeScript consider `isTrue` a `boolean` instead of `true`, then your code will compile.

**Comment by RyanCavanaugh** [comment]
This is the same error you'd see if you wrote `{ ...false }`, and TypeScript can see that that's actually what's happening.

**Comment by gabrielurbina** [comment]
@RyanCavanaugh out of curiosity, why does typescript restrict the spreading of primitive types
I mean `({...false})`, `({...true})`, `({...12})`, `({...null})`, and even `({...undefined})`, are valid javascript expressions, they return an empty object, but they are valid.

**Comment by MartinJohns** [comment]
@gabrielurbina See [this answer](https://stackoverflow.com/a/40223010) by Ryan.

**Comment by gabrielurbina** [comment]
Got it, thanks

**Comment by mackankowski** [comment]
@MartinJohns, thank you for the explanation - it looks clear now.

**Comment by ackvf** [comment]
I am very sad that this is not supported any more. I remember using it in older projects in React very very often.

```
function MyComponent({isLoading}: {isLoading: boolean}) {
  const extraProps = { background: 'pink', displayArea: true }

  return <SomeComponent {...(isLoading || extraProps)} />
}
``` 

Now I need to use this instead `{...(isLoading ? {} : extraProps)}`

---

For reference

```
interface Data {
    a: number,
    b: number
}

const data: Data = { a:1, b:2 }

const flag1 = true
const flag2 = false
const flag3: boolean = false as boolean

console.log({...(flag1 || data)}) // error
console.log({...(flag2 || data)})
console.log({...(flag3 || data)}) // error

// prints:
// {}
// {a:1, b:2}
// {a:1, b:2}
```


So I was wondering, is there a flag or a workaround for this?
