### ISSUE TITLE
Typescript Playground > tsconfig exactOptionalPropertyTypes option is ignored if set via URL parameter 

### ISSUE THREAD

**Issue by simeyla** [microsoft/TypeScript#45078]
# Bug Report

### 🔎 Search Terms

`exactOptionalPropertyTypes`
`typescript playground`

### 🕗 Version & Regression Information

Since TS4.4 beta including nightly.

- I was unable to test this on prior versions because **this is a new option**

### ⏯ Playground Link

The following playground link was generated by the share button. 

https://www.typescriptlang.org/play?ts=4.4.0-beta&exactOptionalPropertyTypes=true#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyxyIcAthAFzIZhSgDmANESXIxAPw0gCu5AEbQA3AQC+BAghx1kAB0w4a6KNlwBefG2JlKNAEQAROCGAQANgdYlkHasgBMAdgliCAE0sRICpSAA6exFiAHpQ5AAVAAsULEUoUw9kLBg7ZAByLwsfCAyUhLgwLChkcj45YQKwYBw4CwCpAiA

It includes the following parameter which was added automatically:

    exactOptionalPropertyTypes=true

However when visiting the link the option reverts back to being unset, which can be evidenced by the lack of an error in the line of code `delete person.age`.

Not sure if this was because the property was recently renamed or if it had never worked under its original name.

---

Please assign to @orta as per @sandersn - https://github.com/microsoft/TypeScript/pull/43947#issuecomment-881055949

**Comment by orta** [comment]
Fixed by https://github.com/microsoft/TypeScript-Website/pull/1940 - will close this issue now, expect the fix to get deployed sometime this week, likely today
