### ISSUE TITLE
Error TS2367: This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.

### ISSUE THREAD

**Issue by kivinm** [microsoft/TypeScript#45070]
# Bug Report

### 🕗 Version & Regression Information

TypeScript versions: all versions starting from 3.3.3, I was too lazy to check early versions.

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?ts=4.3.5#code/DYUwLgBAygXBDOYBOBLAdgcwgXggcjwG4AoUSAYTgCMB7G0AQzRwgAooIBCXPAQTwgAfQdBw8AQngCUhIA

### 💻 Code

let S: string = '';
let C: boolean = (S != 'A' || S == 'B');

### 🙁 Actual behavior

error TS2367: This condition will always return 'false' since the types '"A"' and '"B"' have no overlap.

### 🙂 Expected behavior

no error

**Comment by nmain** [comment]
Seems to make sense.  The only way you'd ever make it past the short circuit `||` to the second test is if `S == 'A'`.  So why test something that you know is false in that case?

**Comment by RyanCavanaugh** [comment]
The code is nonsense so it makes sense for an error to be issued on it. 99% of the time this is a `||` vs `&&` or `!=` vs `==` bug in the user code.

**Comment by kivinm** [comment]
Ok, my bad. It's end of Friday for me, my mind was not sharp enough to catch it :)
