### ISSUE TITLE
Possibly a doc issue or misleading error message: what does "error TS6305: Output file .../xyz.d.ts has not been built from source file .../xyz.ts" error mean exactly?

### ISSUE THREAD

**Issue by dko-slapdash** [microsoft/TypeScript#45086]
# Bug Report (well, maybe a "bug in error message text" report or "missed doc" report)

I'm currently not trying to debug some particular case (well, I do, but it's way beyond this particular topic here).

The question is, what is the exact meaning of the above message? Does it mean that xyz.d.ts file is outdated in comparison to the corresponding xyz.ts? Or also - does it mean that xyz.d.ts file is outdated in comparison to any other file REFERRED from the corresponding xyz.ts? (I.e. the xyz.ts is in sync with xyz.d.ts, but some other file abc.ts which is imported in xyz.ts is newer?)

That error doesn't seem to be documented; also, if it's about the references (or references of references), then it's a little misleading; maybe worth rephrasing it to make more clear, what's happening?

(Composite project in a monorepo with tsBuildInfoFile emitted.)

### 🔎 Search Terms

has not been built from source file
Output_file_0_has_not_been_built_from_source_file_1

### 🕗 Version & Regression Information

@next

**Comment by andrewbranch** [comment]
Looking at the code to double check, it seems to mean that xyz.d.ts doesn’t exist at all, which is what “has not been built” sounds like to me.
