### ISSUE TITLE
Unable to avoid a block of code's compilation in builds

### ISSUE THREAD

**Issue by harit-m-kumar** [microsoft/TypeScript#45095]
i am adding profiling call backs in react, which are to be used by developers. But we don't want it to be included in the production build. Is there any keyword to avoid compilation of a block of code in specific builds? 
On searching all I could find was '@ts-ignore'. But thisdors'nt serve the exact purpose and also cannot be used for blocks of code.
Kindly let me know if there is any solution.

  const profilingCallBack = (id , phase, actualDuration, baseDuration, startTime, commitTime, interactions) => {
    console.log("----------------------------------------------------");
    console.log("Profiler Id : ", id);
    console.log("Profiler Phase : ", phase);
    console.log("Profiler ActualDuration : ", actualDuration);
    console.log("Profiler Base Duration : ", baseDuration);
    console.log("Profiler Start Time : ", startTime);
    console.log("Profiler Commit Time :  ", commitTime);
    console.log("Profiler Interactions : ", interactions);
    totalRenderTime = (commitTime - totalStartTime1);
    console.log("Total Render Time is now : ", totalRenderTime);
    console.log("-----------------------------------------------------");
  }

The above code has to be checked in, but not to be included in the production build.

**Comment by MartinJohns** [comment]
Questions are better suited for platforms like StackOverflow.

Anyway, there is no such feature in TypeScript. You can subscribe to the existing proposals #3538 / #449, but don't expect them to be implemented any time soon (or ever).
