### ISSUE TITLE
types inside function error

### ISSUE THREAD

**Issue by kevupton** [microsoft/TypeScript#45094]
# Bug Report

### 🔎 Search Terms
types inside function error 

### 🕗 Version & Regression Information

- This is a bug
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this

### ⏯ Playground Link
https://www.typescriptlang.org/play?ts=4.4.0-beta#code/MYewdgzgLgBAhjAvDA3gKBvAXDKAnAVwFMAaDGAIxwCYyBfAbjTSIA8AHEPWKAT3aIw8SVOQDaAayK8YASzAwpvEADNc-IqvgBdHCiFEIIADYA3IjgAUpuMat8BWuAEpJ07c6QA+GKZCyAEwYYRjQ6ZlBIWCohERQ6eAh4MF4mNEjoRWlqHCUtB001BGQAchLE5NT08EybY2IcmEsCp1cWtSVqbTiEuCS4FKYKN14ugDo8QxNza1sG5zTLS09EH3RMDNglXOl8jScRMoqBqo2a2DriHHb4MRulbuR448HyYYeJqbMiWfqiBbeI20nyM31+8yYmHe2WBk1BM0u-0hlBG4zh0x+iOoALozmWDCAA

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
const a = {
  a: true,
  b: 2,
};

export type r = {
  [key in keyof typeof a]: { resolve: (val: typeof a[key]) => void; };
}

const b: r = {} as any;

const key2: keyof typeof a = '' as any;
const value2: typeof a[typeof key2] = {} as any;
b[key2].resolve(value2);

(() => {
  const key: keyof typeof a = '' as any;
  const value: typeof a[typeof key] = {} as any;
  b[key].resolve(value); // errors
  b[key].resolve(value2);
  b[key2].resolve(value); // errors
  b[key2].resolve(value2);

 b[key].resolve(value as typeof value2); // works
})();
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/2093615/126094864-17ab12a8-088f-4fbe-bab2-3485204a8bae.png)

As you can see in the image, for some reason when inside a function or another scope it is giving an error according to the types.

![image](https://user-images.githubusercontent.com/2093615/126094837-35c22897-c64b-43bb-bf6e-d802f2304da1.png)

### 🙂 Expected behavior

 That there are no errors.

**Comment by DanielRosenwasser** [comment]
`(typeof a)["a"] & (typeof a)["b"]` is just `number & boolean` which is a type with no values - no value can be both a `number` and `boolean`. That behavior is expected.

I'm not sure why you only see it for a subset of locations - in the playground, all locations fail equally.

**Comment by RyanCavanaugh** [comment]
I see errors on all call sites in VS Code as well. Doesn't seem like there's a defect here given the "expected behavior" being off.
