### ISSUE TITLE
`export default (declare as any)` is not parsed correctly

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#45091]
# Bug Report

### 🔎 Search Terms

default declare as export parser declared

### 🕗 Version & Regression Information

- This is broken at least in 4.3.5 and 4.4.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=next#code/DYUwLgBAJiDGwEMBOIDcAodIAeAHA9kpDAGYICuwkAFDPMiBAgM5MB2AngJQZA)

### 💻 Code

```ts
let declare;

export default (declare as any);
```

### 🙁 Actual behavior

The resulting AST is the same as
```js
let declare;
export default (as, any) => ;
```

### 🙂 Expected behavior

It's a normal type cast expression.

**Comment by DanielRosenwasser** [comment]
Looks like a duplicate of #44466. 😟

**Comment by nicolo-ribaudo** [comment]
Whops, I was focused on the `declare` keyword and I didn't find the other issue!
