### ISSUE TITLE
Overwriting an unknown variable does not change the type

### ISSUE THREAD

**Issue by midgleyc** [microsoft/TypeScript#45098]
# Bug Report

### 🔎 Search Terms

unknown, overwrite, replace

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about common bugs that aren't bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/JYWwDg9gTgLgBAbwM4ysAxvAhkuOkCmsAvnAGZQQhwDk+RMNA3AFAs4CeAduuQK48YwCFzgQAbkQDuaGAQAURKAC44AgNZcIUrgEpELOHCVwAvLQAWBADbWIzQ3iSFYiqFAB0KLLCQB1YBgLeRoLGl1dViMAemjjdzhgXBoNLR0aOAAjPngkCwg+awATLIJaFDQuAHMaFmIgA)

### 💻 Code

```ts
import {strict as assert} from 'assert';

async function overwrite(err: unknown) {
  err = 'hello';
  assert(err.startsWith('h'));
  // err is 'unknown' but should be 'string'
}
```

### 🙁 Actual behavior

Errors because `err` is type unknown.

### 🙂 Expected behavior

No error because `err` is a string by that point.

### Motivating example

I am reading off `.error` from an Angular `HttpErrorResponse` object. `error` is `any`, and can be at least string, JSON or Blob. I set it to "unknown" for type safety.

```ts
async function dealWith(err: unknown) {
  if (err instanceof Blob) {
    const isJson = err.type.endsWith('json');
    err = await err.text();
    if (isJson) {
      err = JSON.parse(err);
    }
  }
  // code that checks whether err is string or JSON and deals with it
}
```

**Comment by MartinJohns** [comment]
See the comments on #42687.

**Comment by midgleyc** [comment]
Thanks!

I note that the most general case #36579 has been marked as "Working as Intended". Most of the other tickets are still in discussion mode. Is narrowing `unknown` types on assignment a possibility? I'm not really concerned about other types: for the most part, they're much easier to work with.
