### ISSUE TITLE
intelligent code completion is not consistent

### ISSUE THREAD

**Issue by Zuckjet** [microsoft/TypeScript#45118]
# Bug Report

### 🔎 Search Terms

code completion

### 🕗 Version & Regression Information

typescript version 4.3.2 (also happen on version 4.3.5)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
import { a } from "moduleA" // moduleA is a npm package module

import { b } from "./moduleB" // moduleB is a local module
```

### 🙁 Actual behavior

I want to replace all double quote with single quote, when I delete moduleB's open double quote then insert single quote, it will auto complete close single quote, that is weird. But moduleA won't happen when applied same operation, I think this behavior is normal and expected. see gif:

![2021-07-20 15 59 14](https://user-images.githubusercontent.com/17976139/126283984-2011eda5-0464-4858-ae57-b09e64c53090.gif)

### 🙂 Expected behavior

I expect not to auto complete close single quote

**Comment by RyanCavanaugh** [comment]
Whether we insert a close quote or not is intentionally dependent on what syntax is to the right of the inserted character.

This is configurable in your editor if you don't like that.

**Comment by Zuckjet** [comment]
Thanks, closed since it is working as intended.
