### ISSUE TITLE
Should 'Suppress When Argument Matches Name' for parameter name inlay hints also apply to property names?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#45112]
# Bug Report

### 🔎 Search Terms

- inlay hints
- parameter hints

### 🕗 Version & Regression Information
4.4, not a regression 

### 💻 Code

Turn on parameter name hints for the code:

```ts
function foo(bar: string) { }

const o = { bar: 'abc' }

foo(o.bar);
```

### 🙁 Actual behavior

Currently you do get a hint:
![Screen Shot 2021-07-19 at 1 51 15 PM](https://user-images.githubusercontent.com/12821956/126225701-864e4ba4-7c9f-4cb1-a5da-ea63d8868de9.png)

### 🙂 Expected behavior
I wonder if we should tread this case like `foo(bar)` instead, which does not generate a hint due to the `"typescript.inlayHints.parameterNames.suppressWhenArgumentMatchesName": true` setting?

Thoughts?

**Comment by DanielRosenwasser** [comment]
CC @Kingwl

**Comment by Kingwl** [comment]
Well, What about element access? `o["bar"]`
