### ISSUE TITLE
Expected X arguments, but got Y.

### ISSUE THREAD

**Issue by aadiene** [microsoft/TypeScript#45115]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about rest syntax.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.3.5&ssl=10&ssc=28&pln=1&pc=1#code/GYVwdgxgLglg9mABMOcCMAKAhgLkWEAWwCMBTAJwBpEA6O8vAbQF0BKPANzhgBNEBvAL4BuAFCiU6DGmoAmVsMQB6JYgCiADwAOpaKT5pEWcgHMipMFADO1YiCiITcB7JoTUmGYlnUAzAuVVTR09AyNTc0sbRDsHJwdfN3FQSFgEZFRZbDwCEgpqOhoGIzAATxZ2RC5eARFkzOk5AJVEADk4RApyOHIrdzgsrx9Ef0UW9s7ybt6gA)

### 💻 Code

```ts
function foo1(a: number, ...r: []): void {};

foo1(1, 2); // Expected 1 arguments, but got 2.
foo1(1, 2, 3); // Expected 1 arguments, but got 3.


function foo2(a: number, ...r: any[]): void {};

foo2(1, 2); // No errors
foo2(1, 2, 3); // No errors
```

### 🙁 Actual behavior

Expected X arguments, but got Y.

### 🙂 Expected behavior

No errors

**Comment by aadiene** [comment]
When I open generated documentation (mouse hover functions) : 
- the rest parameters from `foo1` are absent.
- the rest parameters from `foo2` are present.

Is there something I am missing here ? 🤓

**Comment by Gerrit0** [comment]
`[]` is not the same as `any[]`, `[]` is an empty tuple, with exactly `0` length.

These are all equivalent:
```ts
function foo1(a: number) {}
function foo2(...[a]: [number]) {}
function foo3(a: number, ...r: []) {}
```

**Comment by aadiene** [comment]
Thank you @Gerrit0 for that detail I completely missed !
