### ISSUE TITLE
Object.entries not casting keys of Record<K, T> properly

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#45120]
# Bug Report

### 🔎 Search Terms

Object.entries string key

### 🕗 Version & Regression Information

latest version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsg9gEwgGwHIEMC20C8UDkAZnHPlAD4EBG6ATvgFAMDGcAdgM7BQAiAogDEAkqiEAVIQHlUAZQBcUAEoRWtBAB54SNFggAaKF1oBLNgHMA2gF0AfFDwBvBlBcFipBRaIkA0hBD4VnrOrvg09J5hdH4BQQwAvkwA9ElQtBDAAK60bBAIUKCQhgAWcJnI+VTQAERaKBjYFFCZbEiEpnnVUGxw3NVGpmZNLW0dCNUs7FxQ7a0NuFAAFJiIKArobCAAlPZ2Ti7pWTlQklQAVirAAHQQbMAmEByL-MKiEtIyWyEuV7MIi4sLGxdAYANb+DhWHY4OzgkAcG4ANwgtBAizhuxO50uVzhTxW2i2V1MzGQmSQTzhW2p3ygAH4rhYAAxWBLJVIAWi5TFYnG4VHS6FBCDgAHc2PYlgS1lANttMfsoLzprd7sZHpLThdmNdVQ8ni8ROIpLIdugOFALHUdNgDANzNYrNYoCkSmUKlAqt10Ed0MhkCAlebgHlZRarasbfpDGqHVYnayQodshK9eqOLTfqZ-oDgbaoHioZi8UiUWiMTCsdrrnjlpGiSSyRT0f5qV9XPTGSyEkA)

### 💻 Code

```ts
type ModelName = 'foo' | 'bar'

const DEFINITIONS: Record<ModelName, string[]> = {
    'foo': ['fooKey'],
    'bar': ['barKey'],
}

// returned type should be "ModelName | undefined" not "string | undefined"
const findName = (model: any) => {
  return Object.entries(DEFINITIONS)
    .find(([name, keys]) => keys.every(key => Object.keys(model).includes(key)))
    ?.[0]
}

// ---

const breakdown = (model: any) => {
  const entries = Object.entries(DEFINITIONS) as [ModelName, string[]][] // should be naturally casted as [ModelName, string[]][]

  return entries
    .find(([name, keys]) => keys.every(key => Object.keys(model).includes(key)))
    ?.[0]
}
```

### 🙁 Actual behavior

keys of the object passed in Object.entries as forcibly casted as string

### 🙂 Expected behavior

Keys to be narrowed down to the actual definition. Probably that Object.entries should get a 2nd type generic such as:

```ts
(method) ObjectConstructor.entries<T, K extends string = string>(o: {
    [key: K]: T;
} | ArrayLike<T> | Record<K, T>): [K, T][]
```

**Comment by MartinJohns** [comment]
See #43266. This is intentional and correct. Object types are not sealed.

Search terms used: `Object.entries in:title`
