### ISSUE TITLE
should type narrowing with non-null assertion / nullish coalescing operator when `strictNullChecks: false`

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#45123]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?strictNullChecks=false&strictBindCallApply=false&declaration=false&target=7#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQQBs8BvAWACgBIGATzGAC44BydY4Vq6pTAW2ZwAzjCjIA5jzCYYACxajxSKTWwQUwFAH5FYyVQC+VKqEixEmjDjwARBFGDYY0OnAo16jFqwAmD7ho+QT1lVWoZeVCDNQ1UHRYANwgEXyMTSjNoeC88AFEUKDcAXgJOOAAfOHtHZ1cM9ABXJGcEDTh0AEYABk6ACkwWArE6AEoqD2pHGEaoJDhMADp1TRQAQkWSFXl0yiomlpg2+a7ugCYBocKxiZ5p2fmllfiYbU2tCR3KYz3KA9b2qcAMyXODDIrjSiTBDoOB9XIQWFPOJaeBrYqlVjNXzADhIYC+VhwABkxIWyxRKDg6NKSEaRCIkOokymwBmc3Jz1R722ch4Pzggrg9w5yVScG6uyAA

### 💻 Code

```ts
export interface File {
	type: 'file'
	name: string
	path: string
	content?: string
}

export interface Directory {
	type: 'dir'
	name: string
	path: string
	content?: void
}

export type Entry = File | Directory

function f101(a: Entry)
{
	return a.content!.length
}

function f102(a: Entry)
{
	return a.content?.length
}

function f103(a: Entry)
{
	if (typeof a.content !== 'undefined' && a.content !== null)
	{
		return a.content.length
	}
}

```

![image](https://user-images.githubusercontent.com/167966/126322071-4ec81109-cffe-47f7-b4e4-553643cf1f32.png)

### 🙁 Actual behavior

only f103 no error

### 🙂 Expected behavior

all no error

**Comment by RyanCavanaugh** [comment]
`void` doesn't mean `undefined`. Use `undefined` if you mean `undefined`.

**Comment by bluelovers** [comment]
```ts
import { ITSPartialRecord } from '../../lib/type/record';

export type IFill<T, U, V> = T & ITSPartialRecord<Exclude<keyof U, keyof T>, void>
export type IOr<A extends any[], V> =
	A extends [infer T1, infer T2] ? IFill<T1, T2, V> | IFill<T2, T1, V>
		: A extends [infer T1, infer T2, infer T3] ? IFill<T1, T2 & T3, V> | IFill<T2, T1 & T3, V> | IFill<T3, T1 & T2, V>
			: never

export interface IPubSubEpub
{
	siteID: string;
	novelID: string | number;
	data: {
		path: string,
		cid: string,
		size: number,
	};
}

export interface IPubSubHello
{
	peerID: string,
	type: 1,
}

const json_void = {} as any as IOr<[
	IPubSubHello, IPubSubEpub, {
		cid: string
	}
], void>;

const json_undefined = {} as any as IOr<[
	IPubSubHello, IPubSubEpub, {
		cid: string
	}
], undefined>;

const json_never = {} as any as IOr<[
	IPubSubHello, IPubSubEpub, {
		cid: string
	}
], never>;

if (json_void.peerID!.length && json_void.type === 1)
{
	json_void.peerID
}

if (json_undefined.peerID!.length && json_undefined.type === 1)
{
	json_void.peerID
}

if (json_never.peerID!.length && json_never.type === 1)
{
	json_never.peerID
}

```
