### ISSUE TITLE
Ability to constrain values of an Object with auto-inference of  the object keys

### ISSUE THREAD

**Issue by oleg-slapdash** [microsoft/TypeScript#45139]
# Ability to auto-infer object keys with constraining object values

## 🔍 Search Terms

key inference

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'd like to propose the ability to constrain value types without constraining key types. Currently, one can use `Record<string, ValueType>` to ensure that an object matches a certain shape. However, there are cases when we would like to constrain only values without limiting possible keys values. For example `const COLORS = {"pink": "bright", "purple": "dark"}`. If we define it with `Record<string, string>` then we lose information about possible keys, for example `keyof typeof COLORS` will be `string` instead of `"pink" | "purple"`. The suggestion is to introduce a way to define an object literal with key auto-inference. For example: `const COLORS: Record<infer, string> = {"pink": "bright", "purple": "dark"};` should ensure that the object is defined properly (all values have correct type) and keys are well defined as a union type.

## 📃 Motivating Example

```typescript
type ColorDefinition = {r: number, g: number; b: number};

const COLORS: Record<infer, ColorDefinition> = {
    "blue": {r: 0, g: 0, b: 1},
    "dark-blue": {r: 0, g: 0, b: 0.5},
    "red": {r: 1, g: 0, b: 0},
    // This is an error, all object values should match ColorDefinition
    "error": {r: null, g: 0, b: 0}
}

// should resolve to "blue" | "dark-blue" | "red" | "error"
type ColorNames = keyof typeof COLORS

function foo(colors: Record<ColorNames, ColorDefinition>) {}
foo(COLORS);
```

### What do you want to use this for?
This simplifies and condenses code when a developer needs to have a mapping between a `string const` to a certain set of values.
### What shortcomings exist with current approaches?
There are a few possible workarounds at this moment. 

First, using an ENUM:
```typescript
type ColorDefinition = {r: number, g: number; b: number};

enum ColorName {
    BLUE = "blue",
    DARK_BLUE = "dark-blue",
    RED = "red"
}
const COLORS: Record<ColorName, ColorDefinition> = {
    [ColorName.BLUE]: {r: 0, g: 0, b: 1},
    [ColorName.DARK_BLUE]: {r: 0, g: 0, b: 0.5},
    [ColorName.RED]: {r: 1, g: 0, b: 0},
}

function foo(colors: Record<ColorName, ColorDefinition>) {}

```
Another one is to use a run-time check: 
```typescript 
type ColorDefinition = {r: number, g: number; b: number};

type ValidateColors<T> = {
    [K in keyof T]: ColorDefinition;
}

function validateColors<T>(colors: ValidateColors<T>): ValidateColors<T> {
    return colors;
}

const COLORS = validateColors({
    "blue": {r: 0, g: 0, b: 1},
    "dark-blue": {r: 0, g: 0, b: 0.5},
    "red": {r: 1, g: 0, b: 0},
});

type ColorNames = keyof typeof COLORS

function foo(colors: Record<ColorNames, ColorDefinition>) {}

```

In both cases, it leads to code duplication or extra run-time code. The ability to have leaner code will improve readability and reduce the number of bugs and boilerplate code.

**Comment by RyanCavanaugh** [comment]
This is another use case for #7481

**Comment by oleg-slapdash** [comment]
@RyanCavanaugh It seems like the #7481 feature request looks for an assert-like operator without type narrowing. In this feature request, I am looking for partial type narrowing. You provided a similar example in this comment https://github.com/microsoft/TypeScript/issues/7481#issuecomment-519283504 however, the outcome of that example is that the original record type does not change. In my proposal, I am looking to actually change the type of the original record. 

Technically, the effect is the same, I can use both variables (partially narrowed down and "asserted") interchangeably because they have the same "shape", however, it will make type hints, error and intelli-sense more confusing.

PS. I see you were looking for a name for the operator in that Feature Request, can I propose one? `const COLORS = { .... } assert extends Record<string, Color>`

**Comment by RyanCavanaugh** [comment]
I don't see a difference here - can you show what you'd expect to work with one, but not the other?

**Comment by oleg-slapdash** [comment]
@RyanCavanaugh 
Here is an example:

```typescript
type Color = {r: number, g: number, b: number}

const COLORS_ASSERTED = {
    "blue": {r: 0, g: 0, b: 1},
    "dark-blue": {r: 0, g: 0, b: 0.5},
    "red": {r: 1, g: 0, b: 0},
    "error": {r: 0.4, g: 0, b: 0},
    "light-blue": {r: 0, g: 0, b: 1},
    "light-red": {r: 1, g: 0, b: 0},
    "light-green": {r: 0.4, g: 0, b: 0},
    "dim-blue": {r: 0, g: 0, b: 1},
    "dim-red": {r: 1, g: 0, b: 0},
    "dim-green": {r: 0.4, g: 0, b: 0},
    "cotton-blue": {r: 0, g: 0, b: 1},
    "cotton-red": {r: 1, g: 0, b: 0},
    "cotton-green": {r: 0.4, g: 0, b: 0},
} // assert extends Record<string, Color>

type ColorName = keyof typeof COLORS_ASSERTED;

const COLORS_NARROWED_DOWN: Record<ColorName, Color> = COLORS_ASSERTED;

function customizeColorAsserted(name: keyof typeof COLORS_ASSERTED, color: typeof COLORS_ASSERTED[keyof typeof COLORS_ASSERTED]) {
    COLORS_ASSERTED[name] = color
};
function customizeColorNarrowedDown(name: keyof typeof COLORS_NARROWED_DOWN, color: typeof COLORS_NARROWED_DOWN[keyof typeof COLORS_NARROWED_DOWN]) {
     COLORS_NARROWED_DOWN[name] = color
};

// Ugly error message:
/**
 * The expected type comes from property 'r' which is declared here on type '{ r: number; 
 * g: number; b: number; } | { r: number; g: number; b: number; } | { r: number; g: number;
 *  b: number; } | { r: number; g: number; b: number; } | { r: number; g: number; b: number; } 
 * | { r: number; g: number; b: number; } | ... 6 more ... | { ...; }'
 */
customizeColorAsserted("red", {r: null, g: 0, b: 0})

// Nicer error message
/**
 * The expected type comes from property 'r' which is declared here on type 'Color'
 */
customizeColorNarrowedDown("red", {r: null, g: 0, b: 0})
```

As you can see the "Narrowed down" error message is much more user-friendly.

**Comment by RyanCavanaugh** [comment]
OK, I see what you're doing there.

The workaround you have (which could be collapsed to 1 line) seems very palatable. I don't think there's room in the language for a one-off operator like this - while it's easy to reason about what `Record<infer, T>` would do, it's not at all obvious what `infer` in any other position would mean.

**Comment by oleg-slapdash** [comment]
@RyanCavanaugh,

Would you consider having some modifications to the `Record` definition?
```typescript
/**
 * Construct a type with an inferred set of properties of type T
 */
type InferRecord<T> = {
    [?? something here ??]: T;
};
```

so it can be used as `InferRecord<Color>`?

**Comment by fatcerberus** [comment]
@oleg-slapdash You might be interested in this:
https://kentcdodds.com/blog/how-to-write-a-constrained-identity-function-in-typescript

**Comment by oleg-slapdash** [comment]
This looks like a duplicate/subset of https://github.com/microsoft/TypeScript/issues/26242 - if someone can link together would be nice.

**Comment by IanBellomy** [comment]
Possible additional use example:

I have a moderately large JSON dataset that may need to be modifiable and where entries occasionally need to refer to other entires. I thought I might quickly constrain it by treating the data as a concisely typed const instead of generating a full JSON schema but this would require inferring the keys. 

e.g.
````
const pickyLegos : {[~infer T~]:{stacksOn:T[]}} = {
   brickTypeA:{
      ...
   }
   brickTypeB:{
       stacksOn:[
           'brickTypeA'
       ]   
   }
} as const
````

I understand that 'alternative to JSON schema' is hardly a goal but had it worked it would've been such a pleasant alternative I thought I'd bring it up here. (Disclaimer: I don't know JSON schema well at all but 'learn another thing to type this data' when there's a data typing tool right in my hand is certainly a feeling.)
