### ISSUE TITLE
JSX elements not allowed to have comment trivia

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4514]
```TypeScript
<div>
</div>
```

Seems like this isn't getting parsed correctly.

> \> tsc .\file1.tsx --jsx preserve
file1.tsx(1,1): error TS1128: Declaration or statement expected.
file1.tsx(1,3): error TS1109: Expression expected.
file1.tsx(1,4): error TS1109: Expression expected.
file1.tsx(1,6): error TS1161: Unterminated regular expression literal.
file1.tsx(2,1): error TS1128: Declaration or statement expected.
file1.tsx(3,1): error TS1109: Expression expected.

![image](https://cloud.githubusercontent.com/assets/972891/9536693/c9dedd30-4ce3-11e5-8fde-53739787c147.png)

**Comment by mhegazy** [comment]
i would say this is by desing. //CC: @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
It's supported by the online JSX compiler and Babel; we should maintain parity with them.

**Comment by RyanCavanaugh** [comment]
Problem was that we were seeing the `</` and thinking it was the start of a closing tag. Fix is to check the next char for `*` when trying to produce a `LessThanSlash` token
