### ISSUE TITLE
Type not assignable to its own Partial

### ISSUE THREAD

**Issue by timargra** [microsoft/TypeScript#45145]
# Bug Report

A type consisting of a conditional type based on a class generic is not assignable anymore to its own partial

### 🔎 Search Terms

Type not assignable to partial with class generic

### 🕗 Version & Regression Information

Occuring in all TS versions >= 4.3, including _4.4.0-dev-20210715_

The issue occured after upgrading our project from from TypeScript 4.2 to 4.3.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.0-beta#code/KYDwDg9gTgLgBDAnmYcDKBHANgSQHYDOwsawMAPACoB8cAvHJXKDMHgCYFwCuHwAZgEs8wdnAD8cCACMAVsADG8AFxwA3nADaABTjC4Aa2CII-RgF1VvA3ggB3PHAC+AbgBQb0JFhwFWAIYEXJhYlP7SWMBUtGoecPFwYFAQrEqicABu-liC7P6sAEr2ABQA+sl2qtr+sILZ5CH4RCRk0dQAlKoZELnqbgkDcAD0Q-0JTmPxYNwRggpwgYh488LNMEV2xRWqjYTEMKQUNO19gwkwABaCBAB0WTl5hSUV7S7DQwjIwAQKUIJg8GoDAALDcAMzMKDJKBcC7EYCTQaXa53bK5fLADZbewLYLYJr7Q7RV7vZjgHIKQTwJAoBSBGDCADmcDs0AMsPswAyxEREwmbn4vCUgggjnu6KedmiZW2cGqtXquzWRJoHS6PTEsQGIzcE0FywZor0e1gG2lsqVhNax1OCXFj0xz3sJJGejMTGuCzg+uFooAtJFuVg4Iy2MQ5noYAByLjZAgQFlspm6oA

### 💻 Code

I broke down the issue from a library containing complex nested conditional types to the simplest manifestation I could produce (so don't expect the example to make much sense conceptually):

```
export type SqlInsertSet<T> = T extends undefined ? object : { [P in keyof T]: unknown };

export class SqlTable<T> {

    protected validateRow(_row: Partial<SqlInsertSet<T>>): void {
        //
    }
    public async insertRow(row: SqlInsertSet<T>) {
        this.validateRow(row); // typescript >= 4.3 errors here
        this.validateRow(row as SqlInsertSet<T>); // explicit typecasting works however
    }
}

function validateRow<T>(_row: Partial<SqlInsertSet<T>>): void {
    //
}
function insertRow<T>(row: SqlInsertSet<T>) {
    validateRow(row); // if T is a function-level generic it's also working
}
```

### 🙁 Actual behavior

```
Argument of type 'object | { [P in keyof T]: unknown; }' is not assignable to parameter of type 'Partial<SqlInsertSet<T>>'.
  Type '{ [P in keyof T]: unknown; }' is not assignable to type 'Partial<SqlInsertSet<T>>'.
    Type 'keyof SqlInsertSet<T>' is not assignable to type 'keyof T'.
      Type 'string | number | symbol' is not assignable to type 'keyof T'.
        Type 'string' is not assignable to type 'keyof T'.ts(2345)
```

### 🙂 Expected behavior

Assignment in class methods works as it does with function generics or in TS versions < 4.3

**Comment by ahejlsberg** [comment]
Simpler repro:

```ts
function f<T extends { a: string } | undefined>(x: T, y: Partial<T>) {
    y = x;  // Error, but should be ok
}
```

The issue here is that we wrongly conclude that `Partial<T>` contains no generics and therefore that it is advantageous to narrow the type of `x` to it's union type constraint (to give control flow analysis an opportunity to narrow the type further).

It's an easy fix, I'll have a PR up shortly.
