### ISSUE TITLE
TypeScript 4.0.8 throws an error in Node.js 14.17.2

### ISSUE THREAD

**Issue by msmarkova** [microsoft/TypeScript#45150]
# Bug Report

### 🔎 Search Terms

Iterator value undefined is not an entry object

### 🕗 Version & Regression Information

TypeScript 4.0.8
Node 14.17.2

Started noticing this after upgrading to Angular 10.2 and TypeScript to 4.0.8
- This changed between TS versions 3.8.3 and 4.0.8

### 🙁 Actual behavior

Jenkins and SonarQube keep throwing this error:

13:22:37  INFO: Sensor SonarTS [typescript]
13:22:38  INFO: Analyzing 449 typescript file(s) with the following configuration file /home/jenkins/agent/workspace/<project_name>/project/angular/tsconfig.json
ERROR: /home/jenkins/agent/workspace/<project_name>/project/angular/node_modules/typescript/lib/typescript.js:8740
13:22:39  ERROR:     var textToKeyword = new ts.Map(ts.getEntries(textToKeywordObj));
13:22:39  ERROR:                         ^
13:22:39  ERROR: 
13:22:39  ERROR: TypeError: Iterator value undefined is not an entry object
13:22:39  ERROR:     at new Map (native)
13:22:39  ERROR:     at ts (/home/jenkins/agent/workspace/<project_name>/project/angular/node_modules/typescript/lib/typescript.js:8740:25)
13:22:39  ERROR:     at Object.<anonymous> `(/home/jenkins/agent/workspace/<project_name>/project/angular/node_modules/typescript/lib/typescript.js:10888:3)`
13:22:39  ERROR:     at Module._compile (module.js:577:32)
13:22:39  ERROR:     at Object.Module._extensions..js (module.js:586:10)
13:22:39  ERROR:     at Module.load (module.js:494:32)
13:22:39  ERROR:     at tryModuleLoad (module.js:453:12)
13:22:39  ERROR:     at Function.Module._load (module.js:445:3)
13:22:39  ERROR:     at Module.require (module.js:504:17)
13:22:39  ERROR:     at require (internal/module.js:20:19)

tsconfig file:

{
  "compileOnSave": false,
  "compilerOptions": {
    "importHelpers": true,
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
    "strictTemplates": false
  }
}

This fails the build occasionally. I haven't been able to find any solutions yet, only one [open bug](https://github.com/microsoft/TypeScript/issues/40166) that suggested upgrading Node to our current version, so that couldn't be what is causing it. Any ideas how to fix it?

**Comment by RyanCavanaugh** [comment]
We need some way to reproduce this, even intermittently, so that we can verify it's not just the Node problem again. tsc is pretty much 100% deterministic (there is no async, for example) so if something is only happening sometimes, it's almost certainly external to this repo

**Comment by msmarkova** [comment]
We made some config changes elsewhere, and the error disappeared, so I think you are right @RyanCavanaugh. Thanks for responding though, it makes me feel better having confirmation that it was not TS. I am going to close this, as I don't think it's a bug anymore.
