### ISSUE TITLE
`noUncheckedIndexAccess` behavior with for...in loops with a constant

### ISSUE THREAD

**Issue by charles-toller** [microsoft/TypeScript#45169]
# Bug Report

Using a `for...in` loop with a constant key variable errors with `noUncheckedIndexAccess`.

### 🔎 Search Terms

for...in
noUncheckedIndexAccess
for(const in)

### 🕗 Version & Regression Information

Seen in v4.1.5 (oldest playground with noUncheckedIndexAccess) and next (v4.4.0-dev.20210723 at time of writing)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.4.0-dev.20210723#code/C4TwDgpgBAglC8UDeBtA1hEAuKBnYATgJYB2A5gLo4kCuAtgEYQEC+A3ALABQAJhAMYAbAIYFoAN1FRhOGJy4AzAPYEoACn5KS+KBhBRS0gJTJuUc1E3bgUSYJoRq9JqsTD0mCvJZA)

### 💻 Code

```ts
type A = {[key: string]: number};
declare var a: A;
for (const key in a) {
    const value: number = a[key];
}
```

### 🙁 Actual behavior

Error:

```
Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.(2322)
```

### 🙂 Expected behavior

No error, key is in object by the `for...in` loop and clearly isn't modified as variable is const

**Comment by RyanCavanaugh** [comment]
This is the documented behavior of the flag; see https://github.com/microsoft/TypeScript/pull/39560. It's entirely possible to read an `undefined` out of this loop if mutation were to occur prior to the read.
