### ISSUE TITLE
`Omit` returns an invalid type when the target has a generic key

### ISSUE THREAD

**Issue by szmarczak** [microsoft/TypeScript#45177]
# Bug Report

### 🔎 Search Terms

`omit generic`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECiAeYC2AHEBTaBvAUNf0AZgPbEBc0AdgK5IBG6ATgNx4F1iMUQAujAlpQDmrAJAcAXtz6CRONvmDFKvRtWA9ijABQBKbAoL4eAC34QAdCWLQAvNACMrI0dPmLHRnegByH2NE3S0lvP2cCAF95IwBtAGt0AE9pAWEAXQpqSjjKYgB3SlYonCUVHmgedF4KAHkkfh4AHgRkNHQAGl9PH2gAHy6wCR8APm9KdDy4RFQMPVYcAHoF6AADaxXocyp81ayc-MoVkuUIYgwLEGIhbUreK1JoAGpoAFZdZiA)

### 💻 Code

```ts
class Example {
    foo: number;
    bar: string;
	baz: string;

    constructor() {
        this.foo = 1;
        this.bar = '';
		this.baz = '';
    }

    [key: string]: unknown;
}

const test: Omit<Example, 'bar' | 'baz'> = new Example();

// `foo` is now `unknown`
console.log(test.foo + 5);
```

### 🙁 Actual behavior

`test.foo` is `unknown`

### 🙂 Expected behavior

`test.foo` should be `number`

**Comment by szmarczak** [comment]
```ts
type Omit<T, K extends string | number | symbol> = { [P in Exclude<keyof T, K>]: T[P]; }
type keys = Exclude<keyof Example, 'bar'>; // Exclude<'foo' | 'bar' | string, 'bar'>
type excluded = 'foo' | string; // string
```

**Comment by jcalz** [comment]
Duplicate of #43139 and others

**Comment by szmarczak** [comment]
This is extremely counterintuitive.

**Comment by MartinJohns** [comment]
It's due to the design of the language, and there are workaround available.

**Comment by szmarczak** [comment]
I've updated the example. `OmitIndex` doesn't support union types as keys to remove.

**Comment by szmarczak** [comment]
> there are workaround available.

I'm sure there are, but I don't want to

```ts
OmitIndex<OmitIndex<OmitIndex<Example, 'foo'>, 'bar'>, 'baz'>
```

**Comment by MartinJohns** [comment]
> I've updated the example. `OmitIndex` doesn't support union types as keys to remove.

There is no mention of a `OmitIndex` in your example.

**Comment by szmarczak** [comment]
See https://github.com/microsoft/TypeScript/issues/41966

**Comment by szmarczak** [comment]
Figured it out. I just need to fix the `Filter` like this:

```ts
type Filter<K, I> = Equals<K, I> extends 1 ? never : IfPrimitiveString<I, K, (K extends I ? never : K)>;

// or (which I prefer)
type Filter<K, I> = IfPrimitiveString<I, Equals<K, I> extends 1 ? never : K, K extends I ? never : K>;
```
