### ISSUE TITLE
wrong path on `sources` on generated sourcemap when using linked(yarn link or npm link) packages

### ISSUE THREAD

**Issue by Eliav2** [microsoft/TypeScript#45176]
actually, after writing this whole issue, it is probably a feature request because in order to fix this another property should be added to tsconfig.json, but I will let you decide.

# Bug Report

when using linked packages, the relative path on `sources` is wrong in nested folders in src (means folders in src/*).
**please read this for more details** [here](https://stackoverflow.com/questions/68336645/javascript-debugger-typescript-catches-breakpoint-on-src-but-not-on-src).  

### 🔎 Search Terms

sourcemap , source map, wrong path, linked packages

### 🕗 Version & Regression Information

appeared on v3.9.x and v4.3.x did not tested on other versions. 

### ⏯ Playground Link

here's a project which consists of a library(named react-xarrows) project at ./* and example project using the lib at ./examples/* , the example project(create-react-app) using the library with a `yarn link` command, so ./examples/node_modules/react-xarrows is actually symlinked to the compiled files at ./lib.

here's a [quick GitPod](https://gitpod.io/#https://github.com/Eliav2/react-xarrows/blob/master/src/index.tsx), it will take about a minute to set up and you could see the code on ./src immediately reflected to the running example at port 3000.

unfortunately, debugging is not possible on Gitpod so you will have to clone this repo and run it locally.
to setup locally:

```
git clone https://github.com/Eliav2/react-xarrows

cd react-xarrows
yarn install 

cd examples
yarn install

yarn run link-xarrows
yarn run fix-invalid-hooks

yarn start
```
now start a javascript debugging session on port 3000.  try breakpoint on any file src/* (for example src/Xwrapper.tsx). the breakpoint should be hit. now try in any file in src/**/* (like src/Xarrow/Xarrow.tsx). the breakpoint would not hit because Xarrow.js.map.sources has wrong path relative to the running example project ("../../src/Xarrow/Xarrow.tsx" instead of     "../src/Xarrow/Xarrow.tsx")

open sources tab on dev-tools in the browser. you can see the mapping is wrong.

### 🙁 Actual behavior

generated source map sources maps to wrong relative paths when using linked packages.

### 🙂 Expected behavior

generated source map sources maps to the right paths on projects using linked packages.

### assumption for cause and possible fix

when typescript generates sources for ts files in a project it generates the sources in the assumption that the generated files would be consumed from the same project. if you will consume the generated ./lib on another project the relative sources paths would be wrong because '../../src' is a wrong mapping from the perspective of the running example.

a possible solution would be a property in tsconfig.json which instructs typescript to generate source map as this packages is located in ./node_modules of the running project, or in simpler words - any `../**/src/**/*` should just become `../src/**/*` (nested folders in a linked package should not be counted).

**Comment by DanielRosenwasser** [comment]
Can you provide a simpler repro which only uses `tsc` that just can be cloned over git?

We want to know which specific piece of output is incorrect and what you would suggest its value should be.

**Comment by Eliav2** [comment]
I think there is enough info on this thread, and I explain exactly what is issue and how it could be fixed. you can read the link to StackOverflow question on the top the see a full specific example with screenshots. if you think there is not enough info you can close this issue.

**Comment by RyanCavanaugh** [comment]
We don't have time to reconstruct file layouts from screenshots, so I would agree there is not enough info here. Thanks!
