### ISSUE TITLE
Incorrectly infers Object key to be number instead of string

### ISSUE THREAD

**Issue by leebyron** [microsoft/TypeScript#45170]
# Bug Report

In all recent versions of Typescript, TS may infer an object property to be a subtype of number instead of a subtype of string if that property is written in the quote-less shorthand and happens to be a numeric string (eg `{ 1: "One" }` instead of `{ "1": "One" }` (these two objects being equivalent, since all non Array-exotic objects have [string named literal properties](https://tc39.es/ecma262/#sec-object-initializer-runtime-semantics-evaluation) and all [property keys must be symbols or strings](https://tc39.es/ecma262/#sec-topropertykey)). This affects both the built in `keyof` and types with index signatures.

### 🔎 Search Terms

Numeric string index signatures, object keys

### 🕗 Version & Regression Information

Has always been an issue

### ⏯ Playground Link

[Playground Link showing keyof](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvAjALhgcgHkwBTPAXwFgAoagelpgEkxQAnV44KAGwE8YAlmABmxVhBhReAB2IxMgyFGIBDACZxhMAESZt1KbJgANVDADWxXiC2HiNuEmpA)

[Playground Link showing runtime behavior not mapping to type inference](https://www.typescriptlang.org/play?#code/PTAEGEHsDsDcFMBOAXAzqAhqADgGwwJbSiQBGAVvAMbKjKSagCyG2ANKAK6pEDmmuXDkSRsSZAXjoM6FtlABreAE9UAOgCwAKABmnaDQIwSFasgAqkOQB4A0qHgAPZPGgATdKmSI+oAD6g0JwAtqRI-qCoyqGQuBwAagB8ABRk5ABcoADeoADaAAqgRKC2ALoA-JnxoAC+AJSZAErwGG4wuMo2tgmJ2dqgA6CI8MiciMTQ8ADuzKzJAPKmNGqu3pKoqRR1mNLQynXaNdraIKDmAMpF0DpI6MgAFgR3DGGgza3tnazWAOQYPxEAIwcLw+aC8XpTe6uIq0VD3SCcXBuUCvd5taAdGx-AEBH6An4gtbgxLaKgwLxDKRI2gAXhMlBoljkyRyGEyPwAgvdCaBARz5pMAfVjlpThcrjdEHdHs9UfBQLAMLgCG4OBh3HRlGJIsT+AF9G54DoiPA1aAoTDijoMDRYUVpLgphhVFx3MbTW5NFpydBULF4GpcJBeMlgVTUDS1LwRmG6gctCcwBKiFKZU9MMQNQ5ECJEBxLcRrbbaARS9JFcrVYoVJmUcNRuMK6DfErcJwFckAESC+Bdure33+3CB4Oh-G84aR3DIaOxicJoA)

### 💻 Code

Smallest example using `keyof`

```ts
const obj = {1: 'One'}

// Incorrectly infers type 1 instead of "1"
type X = keyof typeof obj
```

Example showing function runtime behavior differing from inference:

```ts
// Converts a plain object to a Map, using all properties as Map keys.
function objectToMap<K extends string | number | symbol, V>(obj: { [P in K]?: V }): ReadonlyMap<K, V> {
    return new Map(Object.entries(obj) as any)
}

// TS infers this to be ReadonlyMap<'a' | 1, string> when it should be ReadonlyMap<'a' | '1', string>
const result = objectToMap({ a: 'Ah', 1: 'One' })

// TS infers this to be valid, and type string | undefined, when in fact it is always undefined.
console.log(1, result.get(1))

// TS infers this an an error, when in fact it is a valid key and returns a string value ("One").
console.log('1', result.get('1')
```

### 🙁 Actual behavior

TS infers non Array-exotic object numeric string keys are numbers

### 🙂 Expected behavior

TS should infer that all object keys are strings, even numeric strings

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. The meaning of `keyof` isn't "What runtime storage representation is there", it's "What kind of values would be legal to index this object with", and it's intended that you can write
```ts
declare function read<T, K extends keyof T>(a: T, k: K): T[K];
const arr = [0, 1, 2];
// Proposed: This should be made illegal, because 0 is not a string
read(arr, 0);
```
instead of 
```ts
read(arr, "0");
```
because we equally let you write
```ts
const e= arr[0];
```

**Comment by leebyron** [comment]
For anyone coming back across this via search, here's some resolution I found for this issue.

>  "What runtime storage representation is there", it's "What kind of values would be legal to index this object with"

This is pretty subtle. Technically the values legal to index the object *are* the storage representation, but JS has a quirk where it first converts non-symbols to strings via the indexing syntax. Other methods of accessing object properties don't do this, so I suppose this will always a be a footgun and not one TypeScript intends to save people from.

Here's a small utility for getting the actual safe-to-access property keys from an object via the fantastic new template string types syntax:

```typescript
type PropOf<T> = { [K in keyof T]: K extends number ? `${K}` : K }[keyof T]

const obj = {1: 'One', '2': 'Two'}

// Incorrectly infers type 1|"2" instead of "1"|"2"
type KeysAsWritten = keyof typeof obj

// Correctly infers type "1"|"2"
type KeysAsCoerced = PropOf<typeof obj>
```

**Comment by Johnrobmiller** [comment]
> This is the intended behavior. The meaning of `keyof` isn't "What runtime storage representation is there", it's "What kind of values would be legal to index this object with", and it's intended that you can write
> 
> declare function read<T, K extends keyof T>(a: T, k: K): T[K];
> const arr = [0, 1, 2];
> // Proposed: This should be made illegal, because 0 is not a string
> read(arr, 0);
> instead of
> 
> read(arr, "0");
> because we equally let you write
> 
> const e= arr[0];

I understand that there are technical reasons why this quirk is the intended behavior. However, the existence of a valid technical reason does not excuse the problem. The problem may exist with or without the valid technical reason explaining it. In other words, it explains why it is the way it is, but it does not explain why the problem ought to be permitted to continue existing (and, in fact, it shouldn't)

The problem is with the design of the API, not with any technical features of typescript. And that is where the problem ought to be addressed. It ought to be redesigned in a way such that:

a) developers don't need to bloat their code with tautologies such as: `Object.keys(someObj) as keyof typeof someObj`
b) if an object is made using numbers rather than strings, then Object.keys(someObj) should return something that can be used to index someObj

**Comment by RyanCavanaugh** [comment]
> developers don't need to bloat their code with tautologies such as: Object.keys(someObj) as keyof typeof someObj

See https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript

> if an object is made using numbers rather than strings, then Object.keys(someObj) should return something that can be used to index someObj

There's no way to do this without breaking other desirable invariants
