### ISSUE TITLE
Generics Extending Distributed Conditionals Cannot be Narrowed

### ISSUE THREAD

**Issue by anthonyjoeseph** [microsoft/TypeScript#45174]
# Bug Report

### 🔎 Search Terms

Generics, Union, Narrow, Narrowing, Distributed, Conditional, Inference

### 🕗 Version & Regression Information

TS v4.3.5 (and nightly build as of 7/23/2021)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types & inference

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgrmANgSwGYgDwEEB8UC8UWUEAHsBAHYAmAzlHJQNaUD2A7pVAPxQDaWALpQAXFEoQAbhABOAKFCQoFWsAKwEKdBgDkAQx1QAPlB0AjHXgD0V5RFXq++ncJNOLguXOoQAxoj0ZaF9WSgdkSlRZADFGXzFsABooACUScio6DSQ0TFwcAAo9MSxkszEUgEoCPBTvPwCgqBCwtRVgST1EMWdjUws5Focgjq6xJwNhQgiomVjKXwL2zsRkiZdqm2UAC2R6Wm3WOERqKHZWGSYoAu5KrzkbR6fnl5sH2wBhAHkAVQA5GAAUTSgIAGlgALIABQAMoCAMpQN6vFGvLw+fyBYKhcKRGJxABMCWIZAoNHovRM5kMVN8OmSaVJmXo8By2nyRRKZQq1XwtUGOLUIxWRP4zimUBm+IWBKW9lGqzFk02tnOl3oqAiEHRDSxzUFkrxcziAGZiYVikReXgMIyMuTslo8jhCuVUtbUgLWlBhV0zUqXOopcaFia5aoVpUCutBCqzhcmBqtV5FNB5r5ctg8IQSfasowWBwuLwCh7iGIJNJ5BjGtjvcH0wBWYkM9JkrLpzMcy2lKBuqo1T1DIUQBXN64e3rTI1N8MK5KlwfOONqxNQTUSFPgaDwnLAeHAGQYRFMh2qGQRADm2agcigUBPefoAAMACQAb2DUGiyBkqgAvgAtB+X4pPK-7Pne948N+v4OCYu4oPuh62vKOBQfeYjwvUmJNMOhqoMSbbMlA55XskABCxEOohyDIUe3Zcn2YgUR6FFeg4lo6KEECGNOqAFNxEiAcA5widsQS8ckQm8SuCZJhIQA)

### 💻 Code

```ts
type Tuplify<A> = A extends unknown ? [A] : never
type test = Tuplify<'a' | 'b'> // test = ['a'] | ['b']

declare const inferFunc: <A, R extends Tuplify<A>>(a: A, b: R) => R
declare const testval: 'a' | 'b'
const retval: ['a'] = inferFunc(testval, ['a']) // this should work (?)
```

### 🙁 Actual behavior

```ts
const retval: ['a'] | ['b']
```

### 🙂 Expected behavior

```ts
const retval: ['a']
```

I expected `R` to be inferred as a subtype of `Tuplify<A>`, since that's how parameterized union types work as of https://github.com/microsoft/TypeScript/issues/13995 (I think)

Please forgive me if this is actually expected behavior or has already been reported

**Comment by RyanCavanaugh** [comment]
Constraints aren't inference locations, so there isn't a sufficient hint at `b` to infer a literal type for the array.

You could write it this way, which works as expected:
```ts
type Tuplify<A> = A extends unknown ? [A] : never
type test = Tuplify<'a' | 'b'>;
declare function inferFunc<A, R>(a: A, b: R & Tuplify<A>): R;
declare const testval: 'a' | 'b';
const retval: ["a"] = inferFunc(testval, ['a']);
```

**Comment by anthonyjoeseph** [comment]
@RyanCavanaugh Thank you for such a speedy response!

I'm not sure I understand - different constraints give the correct inference:

```ts
declare const inferFunc2: <R extends ['a'] | ['b']>(b: R) => R
const retval2: ['a'] = inferFunc2(['a']) // works fine

declare const inferFunc3: <A extends 'a' | 'b' | 'c', R extends Tuplify<A>>(a: A, b: R) => R
const retval2: ['a'] = inferFunc3(testval, ['a']) // works fine
```

I think this is somehow related to the `Tuplify` type specifically, or maybe distributed conditionals (there are other counter-examples in the [linked playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgrmANgSwGYgDwEEB8UC8UWUEAHsBAHYAmAzlHJQNaUD2A7pVAPxQDaWALpQAXFEoQAbhABOAKFCQoFWsAKwEKdBgDkAQx1QAPlB0AjHXgD0V5RFXq++ncJNOLguXOoQAxoj0ZaF9WSgdkSlRZADFGXzFsABooACUScio6DSQ0TFwcAAo9MSxkszEUgEoCPBTvPwCgqBCwtRVgST1EMWdjUws5Focgjq6xJwNhQgiomVjKXwL2zsRkiZdqm2UAC2R6Wm3WOERqKHZWGSYoAu5KrzkbR6fnl5sH2wBhAHkAVQA5GAAUTSgIAGlgALIABQAMoCAMpQN6vFGvLw+fyBYKhcKRGJxABMCWIZAoNHovRM5kMVN8OmSaVJmXo8By2nyRRKZQq1XwtUGOLUIxWRP4zimUBm+IWBKW9lGqzFk02tnOl3oqAiEHRDSxzUFkrxcziAGZiYVikReXgMIyMuTslo8jhCuVUtbUgLWlBhV0zUqXOopcaFia5aoVpUCutBCqzhcmBqtV5FNB5r5ctg8IQSfasowWBwuLwCh7iGIJNJ5BjGtjvcH0wBWYkM9JkrLpzMcy2lKBuqo1T1DIUQBXN64e3rTI1N8MK5KlwfOONqxNQTUSIA))

> You could write it this way

I'm realizing that my acceptance criteria were poorly outlined - it looks like your `inferFunc` actually returns `[string]`, which technically matches `['a']` but doesn't solve my problem. Imo ideally it would return exactly `['a']`

**Comment by anthonyjoeseph** [comment]
I've realized that this is a string literal inference issue:

```ts
type Tuplify<A> = A extends unknown ? readonly [A] : never
declare const inferFunc: <A extends string, R extends Tuplify<A>>(a: A, b: R) => R
declare const testval: 'a' | 'b'
const retval = inferFunc(testval, ['a'] as const) // correctly inferred as `readonly ['a']`
```

Thanks for your guidance!

**Comment by anthonyjoeseph** [comment]
In case anyone else is reading, this works too and is a little simpler:

```ts
type Tuplify<A> = A extends unknown ? [A] : never
declare const inferFunc: <A extends string, R extends Tuplify<A>>(a: A, b: [...R]) => R
declare const testval: 'a' | 'b'
const retval = inferFunc(testval, ['a']) // correctly inferred as `['a']`
```
