### ISSUE TITLE
TS 4.4.0-beta: #44624 change breaks existing code in CommonJS emit

### ISSUE THREAD

**Issue by DavidANeil** [microsoft/TypeScript#45189]
# Bug Report

### 🔎 Search Terms

TS 4.4 beta commonjs

### 🕗 Version & Regression Information

- This changed between versions 4.3.5 and 4.4.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=3&module=1&ts=4.4.0-beta#code/JYWwDg9gTgLgBAbygUwHYBNlQL5wGZQQhwDkANsgM6UkDcAUPShlgBQnCpgCuMJANHFYBKOAF4AfImzCG9IA)

### 💻 Code

```ts
import {render} from 'less';

render('input', () => {});
```

### 🙁 Actual behavior

`render` is called with a `this` of `Window`
Emit is
```javascript
(0, less_1.render)('input', () => { });
```

### 🙂 Expected behavior

`render` is called with a `this` of `require('less')`
Emit should be
```javascript
less_1.render('input', () => { });
```

It looks like this was caused by #44624.

**Comment by DavidANeil** [comment]
To be totally honest, the new behavior _feels_ correct, but the reality is that this just breaks an unknown amount of existing code.

**Comment by andrewbranch** [comment]
The new behavior is correct, and I thought we did some kind of analysis to see how breaky it would be, but I can’t find that. It at least should be mentioned in the breaking changes section of the release notes (it’s missing from the beta notes). CC @DanielRosenwasser @rbuckton.

**Comment by JaredNeil** [comment]
Is it also Working as Intended that these two snippets have different behavior?
```ts
import * as less from 'less';
less.render('input', () => {});
```
```ts
import {render} from 'less';
render('input', () => {});
```

**Comment by andrewbranch** [comment]
I mean, it’s _expected_. The weird thing is that under the _actual_ implemented CJS/ESM interop in Node v12+, neither of these will work. The only correct way to write an ESM import for this particular CJS module is `import less from "less"`. So in some ways it’s pretty unfortunate that we let you write these at all, but we’ve been doing that for longer than Node’s ESM implementation has existed. The fact is, it’s an accident that `import { render } from "less"` ever worked at runtime, but now that it _doesn’t_, it does become a real problem that we can’t _tell_ you that it’s not going to work at check time. 🤔

**Comment by fatcerberus** [comment]
For the record, in an actual native ESM implementation where `less` is an ESM module, those two snippets would indeed have different behavior at runtime.

**Comment by andrewbranch** [comment]
Yeah, totally. The behavior seen in 4.4 looks completely expected, if you had some reason to believe that the receiver of `render` is supposed to be `less`. The problem is, that’s not obvious at all, and in fact we have no way of looking at the typings and determining that you can’t/shouldn’t use a named import here.

**Comment by DavidANeil** [comment]
Yeah I think the emit change is acceptable, but this should definitely be highlighted as a breaking change that affects the runtime.  Most breaking changes just mean broken type checking, but given that this can break runtimes, and the type system won't catch it, I think it deserves bold lettering.

**Comment by rbuckton** [comment]
The problem with `less` is that its type definitions make it seem like you *can* use `import * as less from 'less'` or `import { render} from 'less'`, but the way the actual code for `less` is written you *should* be using `import less = require("less")` or `import less from "less"` with `--esModuleInterop`. 

Our emit now matches the emit of BabelJS, where you would also get an issue if you tried using `import { render } from 'less'`.

**Comment by andrewbranch** [comment]
That’s true to an extent, but AFAIK there’s no way to change less’s type definitions to make `import { render } from "less"` be an error under `--module=commonjs`. Even if it was 100% clear that the export is a class instance and `render` is an instance method, that kind of import is legal.

```ts
// @filename: node_modules/less/index.d.ts
declare class Less {
  render(input: string): void;
}
declare const less: Less;
export = less;

// @filename: test.ts
import { render } from "less"; // no error
render("");
```

**Comment by rbuckton** [comment]
We could change the definition of `render` to have a `this` argument.
