### ISSUE TITLE
Incorrect "Property is used before its initialization" error with body-less arrow functions

### ISSUE THREAD

**Issue by jhnns** [microsoft/TypeScript#45182]
# Bug Report

### 🔎 Search Terms

Property is used before its initialization
arrow function
body
property
initializer
constructor parameter
useDefineForClassFields

### 🕗 Version & Regression Information

- `>= 3.8.3`
- Also nightly

- This changed between versions 3.7.5 and 3.8.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=3.8.3#code/MYGwhgzhAECC0G8BQ1XQG5hAVwKbQF5oBGAbiQF8klRIYAhRFNYAewDsIAXAJ22C6seACgAOPAJaYu+MAC44ASkRVmqAPTroAZQAWrAO4wARAAUerUbh5cAntADkYB9AkxsEXABNoAI1wAZkL4ElwwEuyhElgSAF5gXBIcxmrQAOa4XLAAalh4hNDCygQAfNBcum4AdGBVmDi45GjQqZrQAHKs0NYWPNAGurjs5YM8uA4wYNAB2OwCScO+rF62rVoZWbkNBUWEZQjQY1zYPMMV1bX1+RTkFEA)

### 💻 Code

```ts
class A {
    value = 1;
}

class B {
    constructor(private a: A) {}

    // Shows "Property 'a' is used before its initialization"
    getAValue = () => this.a.value;
    
    // No error when there's a function body
    // getAValue = () => { return this.a.value };
}
```

`useDefineForClassFields` must be `true`

### 🙁 Actual behavior

With `useDefineForClassFields: true` there's an error when the arrow function has no body

### 🙂 Expected behavior

There should be no error

**Comment by RyanCavanaugh** [comment]
> I upgraded to TS 4.7.4, problem persists.

Can you post an example? OP's code does not error in the 4.7 Playground

**Comment by Akimotorakiyu** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/31165554/189598598-a0be9c6c-c055-45a5-ba13-de471ef43b6b.png">

@RyanCavanaugh please have a look! It's so confused!

**Comment by MartinJohns** [comment]
| Target | useDefineForClassFields | Playground | Error|
|--|--|--|--|
|ES2022|false|[link](https://www.typescriptlang.org/play?target=9&useDefineForClassFields=true#code/MYGwhgzhAECCB2BPAwuK0DeAoavrAHt4IAXAJwFdgSCyAKABwoCMQBLYaeaAXmgEYAlJgC+WHHgYgKEAPLwApgC4uFALbMFZXtBIALNhAB03ANQCA3FjFZCxAiAVGQBAOZ1FAdzhJUkCHSCRlIy8gqCQA)|no (correct)|
|ES2022|true|[link](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9#code/MYGwhgzhAECCB2BPAwuK0DeAoavrAHt4IAXAJwFdgSCyAKABwoCMQBLYaeaAXmgEYAlJgC+WHHgYgKEAPLwApgC4uFALbMFZXtBIALNhAB03ANQCA3FjFZCxAiAVGQBAOZ1FAdzhJUkCHSCRlIy8gqCQA)|**no (wrong)**|
|ESNext|false|[link](https://www.typescriptlang.org/play?target=99&useDefineForClassFields=true#code/MYGwhgzhAECCB2BPAwuK0DeAoavrAHt4IAXAJwFdgSCyAKABwoCMQBLYaeaAXmgEYAlJgC+WHHgYgKEAPLwApgC4uFALbMFZXtBIALNhAB03ANQCA3FjFZCxAiAVGQBAOZ1FAdzhJUkCHSCRlIy8gqCQA)|no (correct)|
|ESNext|true|[link](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99#code/MYGwhgzhAECCB2BPAwuK0DeAoavrAHt4IAXAJwFdgSCyAKABwoCMQBLYaeaAXmgEYAlJgC+WHHgYgKEAPLwApgC4uFALbMFZXtBIALNhAB03ANQCA3FjFZCxAiAVGQBAOZ1FAdzhJUkCHSCRlIy8gqCQA)|yes (correct)|

@RyanCavanaugh On TypeScript 4.8.2, when having target set to **ES2022** and enabled `useDefineForClassFields` there is **no error**, when there should be an error.

**Comment by chharvey** [comment]
Does this also address cases where the property name is used in a static field? In a static field, the object should be fully constructed so the property name should be accessible.

```ts
declare function assert(condition: boolean): asserts condition;

class Person {
    // Unexpected Error: Property 'name' is used before its initialization
    static initial_name_length = new Person().name.length;

    // fixed with an IIFE:
    static initial_name_length_fix = (() => new Person().name.length)();


    name = 'Alice';
}

assert(new Person().name === 'Alice');

assert(Person.initial_name_length === 5);

assert(Person.initial_name_length_fix === 5);
```

[Playground](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=5.2.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMAKMPYLbPALngCMccIQpUBKRokswvCqoadVAG4AUJMh94ABVKE88AN6T4m+AHpt8AKqoQADwAO4DCGDwAojBg4YjeQ-NkAnvADkqKAFsQL3gsQWQSayYQREcEWkEsVFosKAgsAC8oMQ0tQgxMrDBgxOwUgH1fANL2VABzDAALeABeeCMAdwUlPHIuADoKkF7quvqpbM1dJCxjK3g22kbOeABJZYAxG3px+Fz8woSksoGqkFqG0sRp5vhyHuaAPlaQDsUYZVQe-v9B4YauHrG2wG1y8AEFUmBAlIAL7SPikCjtTpvbp9YFNDHecEFQJcMbwsjkV7vXoHEoQcrfE5nRoYloAVjxcOICKJXVQpOKyQpx1+9QuVzp8EZUiAA)
