### ISSUE TITLE
Add a way to get JSDoc comment text

### ISSUE THREAD

**Issue by GoogleFeud** [microsoft/TypeScript#45197]
# Suggestion

## 🔍 Search Terms

- JSDoc
- Comments

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a way to get the text part of a JSDoc comment. Currently, the compiler API only exposes methods to get JSDoc tags (e.g `ts.getJSDocXTag`), but not regular comment text, which usually sits above the tags. 

```
/**
  * This is the normal comment text - What is the proper way of getting this section??
  * @tag - This is a tag
*/
```

## 💻 Use Cases

This addition can ease the writing of projects which need the contents of a JSDoc comment, like documentation generators.
 
As of right now, the only ways to get the text is via using internal properties and methods like `Node.jsDoc` and `getJSDocCommentsAndTags`, or by getting the entire comment as a string and then parsing it.

**Comment by sandersn** [comment]
This makes sense to me, it's just not something the language service has needed before since it has access to internals.

**Comment by Ryuurock** [comment]
How is this PR going?

**Comment by Gerrit0** [comment]
TypeDoc is now depending on this internal API to access comments. It's kind of odd that `getJSDocCommentsAndTags` isn't exposed, while `getJSDocTags` is.
