### ISSUE TITLE
Compile On Save Not Working

### ISSUE THREAD

**Issue by dorad007** [Microsoft/TypeScript#4519]
Just opening a project in vs 2015 community and that is happening:
The message below: "Output generation canceled"
![image](https://cloud.githubusercontent.com/assets/5598420/9539965/95c9c5fe-4d61-11e5-8755-3eab82380178.png)
In VS 2015 RC everything was fine.

**Comment by mhegazy** [comment]
looks like a duplicate of #4296.
@paulvanbrenk can you verify.

**Comment by paulvanbrenk** [comment]
Yes, this is a duplicate, and is fixed in the next TypeScript for VS 2015 release.
