### ISSUE TITLE
Support multiple template literal string index signatures

### ISSUE THREAD

**Issue by dwelle** [microsoft/TypeScript#45202]
# Suggestion

Support multiple template literal string index signatures (initial support of which was added in TS 4.4 https://github.com/microsoft/TypeScript/pull/44512):

```ts
const config: {
	[a: `a.${string}`]: string[],
	[b: `b.${string}`]: number[]
} = {
	[`a.abc`]: ["a", "b"],
	[`b.def`]: ["c", "d"]
}
```

## 🔍 Search Terms

template literal strings index signatures

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example & Use Cases

Same use cases as single template literal index signature, but more useful.

One example are objects containing queries for databases/APIs that support it (Firebase Firestore...) for validation purposes.

For example, this is what an API to update Firestore documents which validates update paths could look like:

```ts
type BookDocument = {
	[chapterText: `chapter.${string}.text`]: string,
	[chapterAuthor: `chapter.${string}.authors.${string}`]: { name: string, email: string }
};

const {bookId, author, chapterId, chapterText} = req.params;

updateDoc<BookDocument>(
	firestore.collection("books").doc(bookId),
	{
		[`chapters.${chapterId}.text`]: chapterText,
		[`chapters.${chapterId}.authors.${author}`]: author
	}
)
```

Current best workaround is to define an overloaded function with `[path, value]` parameter pairs, but the downside is you can't supply a map or list of tuples (e.g. during class construction etc.).

**Comment by DanielRosenwasser** [comment]
Your second example seems to have more to do with the fact that a template string computed property doesn't create an index signature.

[The first example does though](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210727&ssl=7&ssc=1&pln=7&pc=2#code/MYewdgzgLgBKYDMCWBzAXDA3gWAFAEgBtAQwwANiA6AEk2gCckwUBfMgXQwaZUPYBo8RAEblhNOlEbM2nGGACuAW2EBTenzwsYAXixDCFSsWHAOGQgCJil-jEvDLAg2XEATVQnMwrwW-bcnLSA).

So I'm not sure if I understand what the suggestion is here.

**Comment by dwelle** [comment]
Never mind. It just so happens I made a mistake when trying to define multiple template literal index signatures, where both resolved to the same template literal type. It looked something like this:

```
type T = {
	[q: `a.${string}.b`]: string,
	[q: `a.${string}.${string}`]: number
};
```

Which obviously shouldn't work.

The rest was confirmation bias and not looking for counter examples.

Sorry for wasting your time :).

(The first example contains a typo — it shouldn't be set to `["c", "d"]` which doesn't type check indeed.)
