### ISSUE TITLE
Better default return for object destructuring assignment

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#45208]
# Suggestion

## 🔍 Search Terms

object destructuring assignment 

Edit: Found this  [object-spread-on-generic-types](https://devblogs.microsoft.com/typescript/announcing-typescript-3-2/#object-spread-on-generic-types)

> We could have come up with a new concept in the type system called an “object spread type”, and in fact we had a proposal for exactly that. Essentially this would be a new type operator that looks like { ...T, ...U } to reflect the syntax of an object spread. When both T and U are known, that type would flatten down to some new object type.  However, this is pretty complex and requires adding new rules to type relationships and inference. While we explored several different avenues, we recently arrived at two conclusions:

Between that release and now, there has been some new syntax added to make filtering and conditioning on keys possible.  
[key remapping via as](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#key-remapping-via-as).
Thanks very much for adding that.  This proposal just makes use of that wonderful new set of functionality.  I imagine a new definition for merge objects would have arrived soon anyway. 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I believe it wouldn't be a breaking change because it does not add more type errors, it only removes them.

## ⭐ Suggestion

Change the default return type to a value similar to `MergeObjects` as shown in section "Use Cases" below.

## 📃 Motivating Example

```
type A = {a: string; b: string, w?:string, x?:string};
type B = {b: number; c: number, x?:number, y?:number};
type C = {c: boolean; d: boolean, y?:boolean, z?:boolean};

const a:A = {a:'',b:'',w:'',x:''};
const b:B = {b:1,c:1,x:1,y:1};
const c:C = {c:true,d:true,y:true,z:true}

// function mergeObjectsX<A, B, C>(a: A, b: B, c: C): A & B & C
function mergeObjectsX<A,B,C>(a:A,b:B,c:C){
  return {
    ...a,...b,...c
  }  
}

const mX = mergeObjectsX(a,b,c)
mX // const mX: never
```
The return value for the function `mergeObjectsX` appears in the UI as `A & B & C`.  
However that type is `never` whereas the actual result is not of type `never`. 
So the actual result has a type more strict than it's content.

Is this a bug?  No it's not a bug.  It was the best solution for deconstructer assignment which was available in Typescript 3.2 when it was released.  (See Search Terms above.)  But now Typescript has enabled key remapping via `as`.  

The following dirty fix is easy to write: 

```
function mergeObjectsX<A,B,C>(a:A,b:B,c:C){
  return {
    ...a,...b,...c
  }  as unknown as A|B|C
}
```
However `A|B|C` is looser than it needs to be.  
A better fix would be a return type that worked in ALL cases, and that is shown below.
Best of all would be if the typescript default return was that same return type that worked in all cases.  That is the suggestion in this issue.

## 💻 Use Cases

If we use the following type code to calculate the return type of object destructuring assignment:

```
type Evaluate<X> = {
  [K in keyof X]: X[K];
};

type ProjectUndefinedToOptional<X> = {
  [K in keyof X as undefined extends X[K] ? K : never]+?: X[K]; // excluding 'undefined' on rhs doesn't work
} &
  {
    [K in keyof X as undefined extends X[K] ? never : K]: X[K];
  };

type MergeObjects2<A, B> = ProjectUndefinedToOptional<
  {
    [K in keyof A | keyof B]: K extends keyof B
      ? K extends keyof A
        ? undefined extends B[K]
          ? B[K] | A[K]
          : B[K]
        : B[K]
      : K extends keyof A
      ? A[K]
      : never;
  }
>;

type MergeObjects<T extends any[]> = T extends [infer F, ...infer R]
  ? R extends []
    ? F /* when T is length 1 */
    : MergeObjects2<F, MergeObjects<R>>
  : never; /* when T is empty */

```
Then we can get a better return type as show below:

```
function mergeObjects3<A, B, C>(a: A, b: B, c: C) {
  return {
    ...a,
    ...b,
    ...c,
  } as unknown as MergeObjects<[A, B, C]>;
}

const m = mergeObjects3(a, b, c);

type typeof_m = Evaluate<typeof m>;
/**
 type typeof_m = {
    x?: string | number | undefined;
    y?: number | boolean | undefined;
    z?: boolean | undefined;
    w?: string | undefined;
    b: number;
    c: boolean;
    d: boolean;
    a: string;
}
 */

// check reverse assignment 
const t:MergeObjects<[A,B,C]> = {
  "a": "",
  "b": 1,
  "w": "",
  "x": 1,
  "c": true,
  "y": true,
  "d": true,
  "z": true
} 
// no error 
```

Extending to a variadic list of objects:

```
function mergeObjects<AT extends {[key:string]:any}[]>(...args:AT):MergeObjects<typeof args>{
  if (args.length===0)
    return {} as unknown as MergeObjects<typeof args>;
  else if (args.length===1)
    return args[0]  as unknown as MergeObjects<typeof args>;
  else return {
    ...args[0],
   /* @ts-ignore */
    ...mergeObjects(...args.slice(1))
  } as unknown as MergeObjects<typeof args>;
}
const mo = mergeObjects(a,b,c)
type typeof_mo = Evaluate<typeof mo>
/**
 type typeof_mo = {
    x?: string | number | undefined;
    y?: number | boolean | undefined;
    z?: boolean | undefined;
    w?: string | undefined;
    b: number;
    c: boolean;
    d: boolean;
    a: string;
}
 */
``` 
So, the usage case where the suggested feature would be helpful is in writing `mergeObjects`.  The benefits would be

 - It would not be  necessary to manage the code for `MergeObjects` on the application level.   `MergeObjects` is actually not application specific, it actually describes the type of all object destructuring assinments in the Typescript language.
 -  Currently it is necesssary to write the return type `MergeObjects<typeof args>` in four places.  If `MergeObjects<typeof args>` were the actual typescript return type, it would not be necessary to write it *at all*.

The entire type code used in the issue is on the [typescript playground](https://www.typescriptlang.org/play?#code/PTAEBcE8AcFMGcDGAnAltcpX3gV1qAMQAsArAEwAMAHAFAigBCs44syoAJrAGYCGuADaZkLXMgB2oHgHsOMgEYArWIkzd44ZLjXjUEgOag+OVAYkBbWBPC07UOKACiANz6DcfNgB4AGgD5QAF5QAG9aUFAAbQBpLCkAa1hIGR5QXwBdAC502IyAbloAX0LaBwIABWQZFTUAVQluHn1YTgAVGQB5DFQZCXc-QJDwyNj40CSUtN9jeFBcRt4WzlBYAA82RrnfPNAAflA4nIlYF3YMgGo9nJ2YgtAGdcQPTn0jAHIFpuX30D7QZAACzmnBkCAk70wAHc5AliqAAGQRMLI0ZxfQTZKpdKzeaLZonFbrTacba7A4nM4cHJ3G55QqREr2GAEACy7AMsE6ylU4Hg5G8AEEADRMIagKo1XkNb6EjrdcC9fqCbzIkaRaLoxJYtKC0AAH0xUyY2UOqw21lJRuxjFRGoOcWJlrmk2xgrtGv2eNlrXNJLmjDyHs9XsDdwNoEFQZDIZyYYywcicejsbNTq21t1wYOUbuweOp3YDNARVo-lK5VA7OQnO5tT53jafudxgkkCiGXFTfTVqi+h47FAADFRQA6cf9wcAJQTkQOU+bGY7doOQ4eACpQFDAdZQE3sKBBNYDOBAaAAIygdfAO05au1nlqfneEdVjlcx8Nqf+fzIgtU-INy3HcpH3OZYAsDBICvG96DAJw1j4SCjzKFlI2CMI+ByTQ0EMQCFGwrQ3kAqFrlAHDiNANYyIowwmUrRgMNCAjQAkXALAUItQEQY52M45BAOo3iOK4yAyLYkTkHotCAGEmJ40AFBkGQjz4CRAM4HIlJU2A1MAsStOU1T1NAAAvMjtOMplaEQPpNGMHI9WGLDQHed5RRYtzRShHIvKo3z3iZWyJHsljGOGFjz1FBSov8i9RUgHJzyCuzMAUuThgUrR8FFTSIG0WAEpybLCrM4qCushgeAWNQlVAKwa1gGJkngXwhVFRhRRk-wAAoXJFRS42inIZIASkcxEmEmmTaGqiRav+BqH3rVr2qYLrev6jyhu4kbRpRSJRHAcQpHVSJx1HPhhTtC6FGuz0LsQe6S0KUsbNS+qZhCJaPxW3w+o86LRsKCxfEAhhgvs0H-3YOw5oWqQfrrXl4AAZjWzrQG6vrHO29bdqx-b1SOk6Do1C6rpu8c7qp0cnuRIpcQWBIJBkKEpBMN9GuRp9vCiAbMZkztXrsSHMAsDCkc-NGAcUoGKzQ8pUgAfQlkJXHcTwfCVtILHLeh13XCJKx11WmLtITyKIwwIwk-iIy+JZCWLSIDNYvjB0NSzdKkQ1HYJVoXbMiyjJ9h38WWIPSMI3CjD9iPnbtFi7aLO0FO9vS7TyjP1LtFzaIMEWYNFuydNHQQZAMHr3gsIJ3IsYG7AhndEASAFC2QeACBMeAzEsaxMHekLMHALJ71+lG+ZFTqhfFdUACI+HnnJ5-n5754UZf4uReeoS31f17WLeop3xAt5K9fIHPgr184a+cp30z79geE4NYmRVmQaoODhmrFUW98PMGyCm7BaDMoQoiTCyAXbIalIBFA7L1CmNZ4BZBAeNceQD4DeB1sYFB-h1SoDSH1FB5djyniCJQygo07Qk0kGERmnNmas3ZriTB0scEsmxHwfBxZYCCC7lgYhPCDDwDIYYChlDzw0M9HQjmKCoiUAyJEJhEgWZsw5nMdhK1OFwG4bw5E-DBFyLJudccIj4CKIyM9SIwBNwAAE+QAFo+5yAINeWmUsVo9WQaI0c8BBCoEQLAHq0iZEliZmolhmiubLUnrgix+tSxi3qh-b6gDpYAzuogGhJsuE8FVmk5wbgPBeFgLo2A2ILAyF-HYo2EBFb5MKebT0lsC62w9hweOPpOBBzdinLpilQ5qXDj0oO5lDI6RGd0p2gc7TRytrHUZszelJ2EvxIO6dhm509NnbZQd87W0LsUCIHjIZlwrlXee1Sghr2qY3IAA)

To repeat, the requested feature is that object destructing assignment have a default type return similar to `MergeObjects` above. 

Note:  If the rhs of a *non*-optional property of a object type being merged contains `undefined`, then it is effectively treated as an optional property.  There is no other way to do it.  That is because typescript treats all optional properties as implicitly having `undefined` on their rhs.

**Comment by andrewbranch** [comment]
One kind of discouraging note is that we used to infer quite accurate spread types when the inputs were _not_ generic, since we have all the info up front, but we actually simplified it a lot recently because it had an _outrageous_ performance penalty when people built up huge objects with conditional spreads, as is pretty common in some CSS-in-JS libraries. Going straight to a huge nested conditional type is probably a non-starter here. That said, I’m sympathetic to the fact that `A & B & C` is pretty wrong here, and consequently can lead to some pretty bizarre assignments:

```ts
function mergeObjectsX<A,B,C>(a:A,b:B,c:C){
  return {
    ...a,...b,...c
  }  
}

function toLower(str: string) {
  return str.toLowerCase();
}

// wat?
toLower(mergeObjectsX(
  { isLoggedIn: undefined, name: 'Andrew' },
  { isLoggedIn: true, name: 'Whatever' },
  { isLoggedIn: false, id: 12345 }
));
```

**Comment by craigphicks** [comment]
The typescript-specific-union avoids O(2^N) times AST size calculation for deep objects with conditions when used on the LHS of an `extends`.  However, even an O(1) times AST size calculation can have a high constant factor.

Targeting specific cases with explicit use of merging keys where it actually useful is best. 

When you say "but we actually simplified it a lot recently" do you mean you changed the resulting fiunction?  Or optimized the calculation?

**Comment by craigphicks** [comment]
As an aside, it might be better to modify the above by adding `removeUndefinedProperties`
```
function removeUndefinedProperties<T extends {[key:string]:any}>(obj:T):T{
  for (const k in obj)
    if (obj[k]===undefined)
      delete obj[k];
  return obj
}

function mergeObjects<AT extends {[key:string]:any}[]>(...args:AT):MergeObjects<typeof args>{
  if (args.length===0)
    return {} as unknown as MergeObjects<typeof args>;
  else if (args.length===1)
    return removeUndefinedProperties(args[0])  as unknown as MergeObjects<typeof args>;
  else return {
    ...args[0],
    /* @ts-ignore */
    ...removeUndefinedProperties(mergeObjects(...args.slice(1)))
  } as unknown as MergeObjects<typeof args>;
}
```
to prevent overwriting non-`undefined` values with `undefined`.  For example, when a user passes `undefined` for a key which is optional, intending to mean "use the default`.  That's a tricky case.

**Comment by craigphicks** [comment]
Given [the historical information](https://github.com/microsoft/TypeScript/issues/45208#issuecomment-893068881)

>  "but we actually simplified it a lot recently because it had an outrageous performance penalty when people built up huge objects with conditional spreads"

the proposal offered is not practical as a default return type for spread merging.

I think it would be interesting to know more details about the performance issued mentioned:
- cost of buidling the type
- cost of using the type on the LHS of an extends
- cost of using the type on the RHS of an extends
- any other costs

which might give insight about possible intermediate solutions.  But that is beyond the scope of this issue.

**Comment by craigphicks** [comment]
>  an _outrageous_ performance penalty when people built up huge objects with conditional spreads, as is pretty common in some CSS-in-JS libraries. 

Was it this kind of usage?:

```
type TrimWhiteSpace<Str extends string> = 
  string extends Str
  ? "Error"
  : Str extends ` ${infer Str}` | `\n${infer Str}`
  ? TrimWhiteSpace<Str> 
  : Str

type GetType<Str extends string> = 
  string extends Str
  ? "Error"
  : Str extends `${infer Value}px`
  ? number 
  : string;

type ParseCSSProps<S extends string> = 
  S extends `${infer Prop}:${infer Value};${infer Rest}`
    ? {
      [k in TrimWhiteSpace<Prop>]: GetType<TrimWhiteSpace<Value>>
    } & ParseCSSProps<Rest>
    : unknown


type GetRestCSS<Rest extends string> = 
  TrimWhiteSpace<Rest> extends `${infer Content}}${infer RRest}` 
  ? RRest 
  : Rest;

type ParseRestCSS<Rest extends string> =
  TrimWhiteSpace<Rest> extends `${infer Content}}${infer RRest}`
  ? ParseCSSProps<Content>
  : string;

type ParseCSS<S extends string> =
  string extends S
  ? "Error"
  : TrimWhiteSpace<S> extends `${infer ClassName} {${infer Rest}` 
  ? {
    [k in TrimWhiteSpace<ClassName>]: ParseRestCSS<Rest>
  } | ParseCSS<GetRestCSS<Rest>> : string;

type CSSTypes = ParseCSS<`
  body { 
    max-width: 20px;
    background-color: lightblue;
  }

  .h1 {
    color: white;
  }

  #p {
    font-family: verdana;
    font-size: 20px;
  }
`>


const allRight: CSSTypes = {
  body: { "background-color": "red", "max-width": 100 },
  "#p": { "font-family": "verdana", "font-size": 10 },
  ".h1": { color: "white" },
}

const willError: CSSTypes = { // Property '"max-width"' is missing in
  body: { "background-color": "red" },
  "#p": { "font-family": "verdana", "font-size": 10 },
  ".h1": { color: "white" },
}
```
found [here](https://github.com/ghoullier/awesome-template-literal-types).  Pretty amazing stuff.  
Do you have more examples?
