### ISSUE TITLE
Add inlay hints for getters

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#45210]
From https://github.com/microsoft/vscode/issues/129519

# Bug Report

### 🔎 Search Terms
- inlay hints
- `TypeScript › Inlay Hints › Function Like Return Types: Enabled`

### 🕗 Version & Regression Information
4.4.0-dev.20210727

Not a regression

### 💻 Code

```ts
class Foo {
    prop = 1
    foo() { return 1; }
    get bar() { return 1; }
}
```

Enable all inlay hints in VS Code, specifically: `TypeScript › Inlay Hints › Function Like Return Types: Enabled`

### 🙁 Actual behavior

Hints are shown on `foo` but not on `bar`:

<img width="486" alt="Screen Shot 2021-07-27 at 4 13 06 PM" src="https://user-images.githubusercontent.com/12821956/127239227-ad21d1e9-ecfd-4b81-90b8-c354d87056b4.png">

### 🙂 Expected behavior

I think we should include hints for getters if `TypeScript › Inlay Hints › Function Like Return Types: Enabled` is enabled

**Comment by DanielRosenwasser** [comment]
Seems like we could also just plop on the `: void` for setters too.

**Comment by Tyriar** [comment]
@DanielRosenwasser that would be a little confusing since setters cannot have return types?

![image](https://user-images.githubusercontent.com/2193314/127313319-f194dd98-ba29-44b6-b239-832f440d90f9.png)

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

Just saw @Tyriar's comment though. Perhaps we should remove the `: void`.

**Comment by DanielRosenwasser** [comment]
FWIW I've also filed #45224.
