### ISSUE TITLE
ts2536 thrown when use key remapping to filter out some keys

### ISSUE THREAD

**Issue by venecy** [microsoft/TypeScript#45212]
# Bug Report

### 🔎 Search Terms

key remapping
ts2536

### 🕗 Version & Regression Information

- This is a crash
- v4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAshwAsD2ATAzgHgCoD4oF4oBvKAbQAUoBLAOygGsIQkAzKLKAQzXYoF0oEAB7AINdFABiAVxoBjYFSR0A-FEoAuKDQgA3CACc+WrPygBfANwAoUJCgAJbHkKnGzNnESpMuPpaA)

### 💻 Code

```ts
type Methods<T> = { [P in keyof T as T[P] extends Function ? P : never]: T[P] };
type H<T> = T[keyof Methods<T>]; // here it throws
```

### 🙁 Actual behavior

Type `keyof Methods<T>` cannot be used to index type `T`. (2536)

### 🙂 Expected behavior

key remapping in type `Methods<T>` dose not make new keys, only filter out some of it. I think it could be used to type `T` in this case.

**Comment by andrewbranch** [comment]
I agree, though `type H<T> = Methods<T>[keyof Methods<T>]` is a pretty straightforward workaround.
