### ISSUE TITLE
Failed type check for T[keyof T] 

### ISSUE THREAD

**Issue by ilyub** [microsoft/TypeScript#45219]
# Bug Report

### 🔎 Search Terms

Failed type check for T[keyof T] 

### 🕗 Version & Regression Information

v4.3.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.3.5#code/GYVwdgxgLglg9mABMAPAFQHwAo4CMBWAXImgDSIDWApgJ7HU1zAnkBuAhgDYhXFoDaDJiQC6ASmKs4MACaIA3gChEiPPkG0RiALyIO3KgG5FAX0WKICAM5READx0LE7YgEZyuYgCI7XxCeNFYCw7ci92LzCaLzFAuwA6dkcvaOMgA

### 💻 Code

```ts
function f<T>(obj: T, key: keyof T, value: T[keyof T]): void {
  obj[key] = value;
}

const x = { a: 1, b: "x" };

f(x, "a", "y");

x.a = "y";
```

In this example typescript catches this invalid assignment: x.a = "y";

But it misses the same invalid assignment done with: f(x, "a", "y");

This happens because the line:
obj[key] = value;
passes validation when it should not.

### 🙁 Actual behavior

No error in line "obj[key] = value;"

### 🙂 Expected behavior

Error in line "obj[key] = value;"

**Comment by nmain** [comment]
You can ask typescript for a more specific generic inference that will catch this at the callsite for `f`:

https://www.typescriptlang.org/play?ts=4.3.5#code/GYVwdgxgLglg9mABMAPAFQDSINKIKYAeUeYAJgM6IDWeAnnMImgHwAUcARgFYBcTWNWn2xYAbgEMANiDx80AbWwBdAJR9RcGKUQBvAFCJEnLvMFLEAXkQTpeANx6Avnr0QE5KIgKXdicXwBGLA4+ACICUMRHBz1gVgIsUPFQxNpQlRiCADpxH1C0hyA

**Comment by ilogico** [comment]
@nmain, although that's much better, it's still unsound:
```ts
const key = Math.random() > 0.5 ? 'a' : 'b';
const value = Math.random() > 0.5 ? 1 : 'x';
f(x, key, value);
```
Properties are assumed to be covariant, which works really well for immutable data, but usually breaks when you set properties:
```ts
function update(obj: { prop: | string | null  }) {
  obj.prop = null;
}

const obj = { prop: '42' };
update(obj);
obj.prop.toUpperCase()
```

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; in general, writes to properties through a supertype alias are not sound.
