### ISSUE TITLE
Add missing member codefix changes lib files

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#45225]
```ts
declare let p: Promise<string>;
async function f() {
  p.toLowerCase();
}
```

Available fixes are

1. Add await
2. Declare method 'toLowerCase'
3. Declare property 'toLowerCase'
4. Add index signature for property 'toLowerCase'

2–4 modify the `Promise` declaration in `lib.es5.d.ts`.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/3277153/127402353-a4e883f6-f17c-47ed-866a-575c10896dc0.png">

I recently suggested to @sandersn that a new codefix shouldn’t change any `.d.ts` files, since they’re likely to be downloaded or autogenerated. That may or may not be too aggressive a rule for all codefixes, but I think it may be worth asserting that no codefixes change lib files or node_modules.

**Comment by DanielRosenwasser** [comment]
I think it's nice to be given the opportunity to add members to `.d.ts` files in case they're not yet on DT. This

> I think it may be worth asserting that no codefixes change lib files or node_modules.

Seems reasonable though.
