### ISSUE TITLE
Inconsistent behaviour for react component proptypes in v3.3 vs v3.5

### ISSUE THREAD

**Issue by gaurav5430** [microsoft/TypeScript#45222]
# Bug Report
Inconsistent behaviour for the same code in v3.3 vs v3.5 

### 🔎 Search Terms
- Requireable
- proptypes

### 🕗 Version & Regression Information
- used to occur for me a lot, due to which I had stopped using PropTypes with typescript, 
- suddenly stopped happening after ts version upgrade

This changed between versions _3.3_____ and ___3.5____

### ⏯ Playground Link
3.3 - not working - https://www.typescriptlang.org/play?ts=3.3.3#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQoksiK6ACsWACoCeYW6IiXJhOAWhh8BtOgwB2MLFAJ4scAJIAZZDwgBXGBwhh0Abzpw4AE2BQA-AC5yAC2jAAXhAXIANmTgAPuQAbkowwLi+ZHQAvvR0uF6o8Nq6Bk7YeDAAdABienL4wF4AwiSQclgKADxaOvqGnKgAfHAAvHAAFKLGqACU7a3mlpQwelByXRaWcNU2wc3TM3CmPSbZuM7APlaUcjFLswD084uWffRxsqkN2VZYKno+jb3tK9M2UE5krlAeXjAorF6DcDNk1rx+OgOsNrLYnEZuFJUNkvFgAPIEToAbR+bk83j8ABoQmEIlEALp9YF0LAADyY8Huj2ecFBMHoQA

3.5 - working alright - https://www.typescriptlang.org/play?ts=3.5.1#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQoksiK6ACsWACoCeYW6IiXJhOAWhh8BtOgwB2MLFAJ4scAJIAZZDwgBXGBwhh0Abzpw4AE2BQA-AC5yAC2jAAXhAXIANmTgAPuQAbkowwLi+ZHQAvvR0uF6o8Nq6Bk7YeDAAdABienL4wF4AwiSQclgKADxaOvqGnKgAfHAAvHAAFKLGqACU7a3mlpQwelByXRaWcNU2wc3TM3CmPSbZuM7APlaUcjFLswD084uWffRxsqkN2VZYKno+jb3tK9M2UE5krlAeXjAorF6DcDNk1rx+OgOsNrLYnEZuFJUNkvFgAPIEToAbR+bk83j8ABoQmEIlEALp9YF0LAADyY8Huj2ecFBMHoQA

### 💻 Code

```ts
import * as React from 'react';
import * as PropTypes from 'prop-types';

interface ILayoutProps {
  dir?: 'horizontal' | 'vertical'
};

const Layout: React.FunctionComponent<ILayoutProps> = (props) => {
  return (
    <div>
      {props.children}
    </div>
  );
};

Layout.defaultProps = {
  dir: 'horizontal'
};
Layout.propTypes = {
  dir: PropTypes.oneOf(['horizontal', 'vertical'])
};
export default Layout;
```

### 🙁 Actual behavior
on 3.3 it gave me a cryptic error about prop types
on 3.5.1 it does not give me any error

### 🙂 Expected behavior
behaviour should be consistent across minor versions

**Comment by MartinJohns** [comment]
> behaviour should be consistent across minor versions

But why? TypeScript does not follow SemVer. You can treat every minor version as a potential breaking change (and it often does include breaking changes).

**Comment by gaurav5430** [comment]
yeah, got to know that TS does not follow semver

i think in that case the actual question / bug becomes what changed that the code is not breaking anymore? i went through the release notes and could not find anything related to this (or at least what I could understand)

**Comment by nmain** [comment]
3.5 just improves generic parameter inferences in some cases.  You can get the right behavior in 3.3 by explicitly specifying a type parameter:

https://www.typescriptlang.org/play?ts=3.3.3#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQoksiK6ACsWACoCeYW6IiXJhOAWhh8BtOgwB2MLFAJ4scAJIAZZDwgBXGBwhh0Abzpw4AE2BQA-AC5yAC2jAAXhAXIANmTgAPuQAbkowwLi+ZHQAvvR0uF6o8Nq6Bk7YeDAAdABienL4wF4AwiSQclgKADxaOvqGnKgAfHAAvHAAFKLGqACU7a3mlpQwelByXRaWcNU2wc3TM3CmPSbZuM7APlaUcjFLswD084uWffRxsqkN2VZYKno+jb3tK9M2UE5krlAeXjAorF6DcDNk1rx+OgOsNrLYnEZuFJUNkvFgAPIEaoAIl+-28PmxgTg2NCsAivmxzU6AG0fm5PASyAAaEJhCl+AC6fWBdCwAA8mPB7o9nnBQTB6EA

**Comment by RyanCavanaugh** [comment]
Wouldn't giving fewer errors not even be a breaking change under Semver? 🤔

Anyway we don't do that and it sounds like the right thing started happening, which is good.
