### ISSUE TITLE
Typescript doesn't check what modules I installed on the FTP server

### ISSUE THREAD

**Issue by ray-1337** [microsoft/TypeScript#45227]
This is something that I don't get it. Does Typescript detect the modules that I installed on the FTP server?

## Proof

![image](https://user-images.githubusercontent.com/33544674/127432078-4359c983-bb21-4958-a459-12bd8919e1b5.png)
![image](https://user-images.githubusercontent.com/33544674/127432095-d25e5057-1405-48b2-a8f7-fc0aa56c7c9d.png)

## System
- TS: **v4.3.5**
- VSC: **v1.58.2**
- FTP: (WinSCP **v5.17.9** | Build 10905)

#### package.json
![image](https://user-images.githubusercontent.com/33544674/127433080-4ea06d62-94dd-4871-ae4b-66c93ff580d4.png)

#### tsconfig.json
![image](https://user-images.githubusercontent.com/33544674/127433133-165f5c9c-838b-4397-8587-ab465c30fa83.png)

**Comment by RyanCavanaugh** [comment]
TS does not attempt network connections of any sort. Also I don't see any FTP here?
