### ISSUE TITLE
Contextual narrowing not narrowing on generic map.

### ISSUE THREAD

**Issue by whitneyit** [microsoft/TypeScript#45234]
# Bug Report

### 🔎 Search Terms

* [contextual narrowing](https://github.com/microsoft/TypeScript/issues?q=contextual+narrowing)
* [type narrowing 4.3](https://github.com/microsoft/TypeScript/issues?q=type+narrowing+4.3)
* [4.3](https://github.com/microsoft/TypeScript/issues?q=4.3)

### 🕗 Version & Regression Information

- This is something that I expected to work after 4.3's [Contextual Narrowing for Generics](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#contextual-narrowing)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3iAbiFGAKgJ4AOIAXPANYjFIBm8AIkmAK4C2+GAongQCyUUgG4AUOOBsuPAHRRgwfjwAyAS0z4QMABS4eJcgBp4+gRgCU8ALwA+eAG9x8bBdHwA9J-gAJHQgABgYEgfCa8IEqBPAAPvAAqgCS0VjxAIIo6pxQGOqoqXHwgkjsaCCF8UkopOx8FkUAYjJolfAAwkicpEho6nkFDfFyI-AAnPCcSHDwI3JF7RDqpABGSLDKFi7hTOaGZAg2R5GQ6mDUgdbOrq4hGB7e8LwAHuRgGCDAVMEWYRhI8BWCAwB0iJTKFV+83S73YUAgVCSGAA5Gh4BgABYIdhZVDwBgwLrwKBrPBybYAX3EFMsoiAA)

### 💻 Code

```ts
declare const eventType: keyof DocumentEventMap;

document.addEventListener(eventType, (event) => {
  event; // Here `event` is `Event | UIEvent | AnimationEvent | MouseEvent | InputEvent | FocusEvent | CompositionEvent | ... 9 more ... | ClipboardEvent
  if (eventType === `click`) {
    event; // Expected: `event` to be type `MouseEvent`. Actual: It's the union from above.
  }
});
```

### 🙁 Actual behavior

Second reference of `event` is type `Event | UIEvent | AnimationEvent | MouseEvent | InputEvent | FocusEvent | CompositionEvent | ... 9 more ... | ClipboardEvent`.

### 🙂 Expected behavior

Second reference of `event` to be of type `MouseEvent`.

**Comment by jcalz** [comment]
Generic functions like `document.addEventListener()` have their type parameters *specified* when you call them.  In the case above, the `K` type parameter is inferred to be `keyof DocumentEventMap` and therefore the type of `event` in the callback is the full union; it is no longer "generic" in the way that #43183 (the contextual narrowing feature) would have any bearing on.

It seems like what you really want is something like #27808 where the type parameter `K` is treated as some unknown single member of the `keyof DocumentEventMap` union... although then the compiler might not even let you call `document.addEventListener()` with a union-typed `eventType`.  

This also feels like `eventType` and `event` are supposed to be *correlated unions* but the compiler has no way to track that; which is #30581.  (This is where #25051 would have helped, if you could wrap the call to `document.addEventListener()` in a hypothetical `type switch (eventType) {...}` block.  Oh well!)

**Comment by whitneyit** [comment]
Thanks @jcalz  for the detailed response! I agree that this is similar to #30581.

Unlike #30581, I was under the impression that the `if` check would be sufficient to narrow the type to `MouseEvent`.

**Comment by fatcerberus** [comment]
Right - the compiler doesn’t understand that `eventType` and `event` are interrelated for the purposes of type narrowing.
