### ISSUE TITLE
Useless empty class fields are generated when using parameter properties and target=ESNext

### ISSUE THREAD

**Issue by angryziber** [microsoft/TypeScript#45235]
# Bug Report

```
  class MenuItem {
    constructor(public name: string) {}
  }
```

Compiling this with `-t ESNext` produces:
```
class MenuItem {
    name;
    constructor(name) {
        this.name = name;
    }
}
```
The name field above also confuses some next stage build tools that don't support class fields yet, e.g. the popular acorn that is used by Svelte compiler (https://github.com/sveltejs/svelte/issues/6592)

However, compiling with `-t ES2021` produces more compact code without useless field declaration:
```
class MenuItem {
    constructor(name) {
        this.name = name;
    }
}
```

### 🔎 Search Terms

constructor shorthand 

### 🕗 Version & Regression Information

Version 4.3.5 & next
- This changed between versions 4.2.x and 4.3.x

**Comment by IllusionMH** [comment]
ESNext uses `useDefineForClassFields` by default
See #45076

**Comment by fatcerberus** [comment]
Just to add because I feel this is important: in an environment that *natively* supports class fields, the declared field is not useless - behavior actually *differs* between the two snippets because ECMAScript dictates `[[Define]]` semantics for fields.
