### ISSUE TITLE
TSServer unable to load plugin from a local directory

### ISSUE THREAD

**Issue by bstaletic** [microsoft/TypeScript#45232]
# Bug Report

### 🔎 Search Terms

plugin tsserver relative path

### 🕗 Version & Regression Information

This was reported to me here: https://github.com/ycm-core/YouCompleteMe/issues/3924

The gist is that @FuDesign2008 wanted to use [this plugin](https://github.com/mrmckeb/typescript-plugin-css-modules) with vim/YCM/TSServer.

- YCM, by default, installs TSServer in a local directory, somewhere in `~/.vim/`.
- The user's plugin is installed inside `node_modules`, in user's project.
- TSServer, according to [the log](https://github.com/FuDesign2008/example-app/blob/master/ycm-logs/tsserver_xjmmtz1k.log#L48) searches for plugins in its directory and all parent directories.
- As a result, TSServer fails to find the plugin.
- According to [this wiki page](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#testing-locally) relative paths for module names should work.
  - Yet, when I tried to specify a relative path, TSServer complained that:

&nbsp;

    Info 19   [10:43:12.331] Skipped loading plugin ./node_modules/typescript-plugin-css-modules because only package name is allowed plugin name

### ⏯ Playground Link

Sorry, I don't have one.

### 💻 Code

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-plugin-css-modules"
      }
    ]
  }
}
```

```json
{
  "dependencies": {
    "typescript-plugin-css-modules": "*"
  }
}
```
### 🙁 Actual behavior

TSServer failed to find the plugin.

### 🙂 Expected behavior

TSServer should have found the plugin in the local `node_modules`.

### Workarounds

1. Installing the TSServer plugin in `~/.vim/path/to/tsserver/node_modules/` worked.
2. Installing the TSServer itself in the local `node_modules` and telling YCM to use that one also worked.

Both seem less than idea, especially considering that [the wiki](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) says the user's expectations should work.

**Comment by RyanCavanaugh** [comment]
This is disallowed for security reasons. I'll update the wiki when I get a chance
