### ISSUE TITLE
Vscode is not showing auto suggestions after one usage (shows up only one time)

### ISSUE THREAD

**Issue by LarsFlieger** [microsoft/TypeScript#45240]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.58.0 (user setup)
- OS Version: Windows_NT x64 10.0.19042

The auto suggestion is only showing up once and after that it's not showing any suggestions anymore. (Window size of it is fine)

Steps to Reproduce:

1. Open up vscode
2. Start to write something => It's working
3. When I do it again => It's not showing suggestions

Here a small clip: https://i.imgur.com/OTrHwM0.mp4

**Comment by andrewbranch** [comment]
The combination of @types/node and ts-node caused completions crashes (#45030) and was already fixed by #45055. More completions crashes will be fixed in tonight’s nightly by #45289. Please comment/reopen if the issue still repros with the TS nightly extension after tomorrow. Thanks!
