### ISSUE TITLE
module is cjs and esModuleInterop is set to true, the "default" is still output

### ISSUE THREAD

**Issue by ProfBramble** [microsoft/TypeScript#45246]
# Bug Report

### 🔎 Search Terms

allowSyntheticDefaultImports
commonjs
cjs
default

### 🕗 Version & Regression Information

typescript 3.8.2
node 12.18.0

### 💻 Code

```
// source code
import React from 'react'

export default function Circle (props) {
    const { ...other } = props;
    return (
        <div
            {...other}
        >
            {props.children || ''}
        </div>
    )
}

// tsconfig
{
      "compilerOptions": {
        "outDir": "./lib/",
        "module": "commonjs",
        "target": "es5",
        "declaration": true,
        "jsx": "react",
        "moduleResolution": "Node",
        "keyofStringsOnly": true,
        "esModuleInterop": true,
        "experimentalDecorators": true
      },
      "include": [
        "src/components"
      ],
      "exclude": [
        "node_modules",
        "build",
        "scripts",
        "**/__tests__/*.test.tsx",
      ]
}
```

### 🙁 Actual behavior

```
function Circle(props) {
   // Some non-critical output
    return (react_1.default.createElement("div", __assign({}, other, { className: classes }), props.children || ''));
}
```

### 🙂 Expected behavior

The output at this time should point to React.createElement, **but if the output target is es module, this problem will not occur**

**Comment by andrewbranch** [comment]
You want `esModuleInterop`, not `allowSyntheticDefaultImports`.

**Comment by ProfBramble** [comment]
I tested it before raising the issue, but it still outputs `react_1.default.createElement`

> You want `esModuleInterop`, not `allowSyntheticDefaultImports`.

**Comment by ProfBramble** [comment]
It's a bit embarrassing. I didn't know that the help function __importDefault has already mounted the entire package on default, although the display still carries default. But it's working
