### ISSUE TITLE
Array spread in compiled JS files is incorrect when targeting ES5

### ISSUE THREAD

**Issue by eritbh** [microsoft/TypeScript#45251]
# Bug Report

### 🔎 Search Terms

array spread, iterator spread, empty array

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _the spread operator_.

### ⏯ Playground Link

Playground does not support the `--allowJs` flag, so I can't provide a playground link. If the bug workbench supports demonstrating runtime behavior bugs, I can't figure out how.

### 💻 Code

```js
const foo = new Set([1, 2]);
console.log([...foo.values()]); // expected: [1, 2]
```

### 🙁 Actual behavior

Compiling the above Javascript file with `--allowJs` in all versions of Typescript I tested results in incorrect behavior at runtime. The actual behavior varies based on the version installed. I tested against `typescript@3`, which generates a runtime error, `typescript@4.2` and `@4.3`, which both result in empty arrays being logged, and `typescript@next`, which puts the iterator itself inside the array.

<details>
<summary>4.4.0-dev.20210730</summary>

```
% tsc test.js --allowJs --target es5 --outfile test.out.js

% cat test.out.js
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || from);
};
var foo = new Map();
foo.set('a', 1);
foo.set('b', 2);
console.log(__spreadArray([], foo.values(), true));

% node test.out.js
[ [Map Iterator] { 1, 2 } ]
```

</details>

<details>
<summary>4.3.5 and 4.2.4</summary>

```
% tsc test.js --allowJs --target es5 --outfile test.out.js

% cat test.out.js
var __spreadArray = (this && this.__spreadArray) || function (to, from) {
    for (var i = 0, il = from.length, j = to.length; i < il; i++, j++)
        to[j] = from[i];
    return to;
};
var foo = new Map();
foo.set('a', 1);
foo.set('b', 2);
console.log(__spreadArray([], foo.values()));

% node test.out.js
[]
```
</details>

<details>
<summary>3.9.10</summary>

```
% tsc test.js --allowJs --target es5 --outfile test.out.js

% cat test.out.js
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
var foo = new Map();
foo.set('a', 1);
foo.set('b', 2);
console.log(__spreadArrays(foo.values()));

% node test.out.js
/home/erin/test.out.js:3
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
                 ^

RangeError: Invalid array length
    at __spreadArrays (/home/erin/test.out.js:3:18)
    at Object.<anonymous> (/home/erin/test.out.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
</details>

Note that adding the `--checkJs` flag alongside `--allowJs`, or just putting the same code in a `.ts` file, returns an error:

```
% tsc test.js --allowJs --checkJs --target ES5 --outfile test.out.js
test.js:1:17 - error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

1 const foo = new Map();
                  ~~~
```

Since the error states `--lib es2015` is required, and es2015 is a later version than the target of es5, this can lead the user to fix the error by bumping the build target to es2015, which doesn't try to include a helper for the spread operator.

On the other hand, following the advice of the error directly and setting `lib` higher than `target` results in a different error, which in turn suggests adding the `--downlevelIteration` flag. After following the prompts directly, I wound up with the following:

<details>
<summary>Correctly behaving code from lots of flags with a large helper</summary>

```
% tsc test.js --allowJs --checkJs --target ES5 --lib dom,es2015 --downlevelIteration --outfile test.out.js

% cat test.out.js
var __read = (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || from);
};
var foo = new Map();
foo.set('a', 1);
foo.set('b', 2);
console.log(__spreadArray([], __read(foo.values()), false));

% node test.out.js
[ 1, 2 ]
```
</details>

### 🙂 Expected behavior

Either the emitted code should work correctly, or the compiler should error. I'm not exactly sure what the correct behavior is, since the bug arises when using builtins TS doesn't have helpers for and can't assume are present in the given target. It seems like an error may be appropriate, but since `--checkJs` isn't being used (and an error is in fact thrown if it is used), maybe the right call is just to rework the helper so it works across targets? Or maybe this isn't a bug at all, and setting a target lower than the code requires (or failing to change the default target) is just user error - I'm not entirely sure what's considered a bug with `--allowJs` but not `--checkJs`, but emitting transformed code which has different behavior than the input code doesn't seem right to me.

**Comment by rbuckton** [comment]
This isn't a bug, per se. If you have the correct types for `Map`, the actual error `--checkJs` would show is this:

```
Type 'IterableIterator<number>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
```

The `__spreadArray` helper can only be used when the value being spread is an Array (or array like), since our default downlevel behavior is essentially to just call `Array.prototype.concat`.

If you specify `--downlevelIteration`, then the output runs correctly as long as `Symbol.iterator` is defined:

```
% tsc test.js --allowJs --target es5 --downlevelIteration --outfile test.out.js

% cat test.out.js
var __read = (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
var foo = new Set([1, 2]);
console.log(__spreadArray([], __read(foo.values()), false));

% node test.out.js
[ 1, 2 ]
```
