### ISSUE TITLE
Converting string of typescript to code but keep getting _os.platform is undefined

### ISSUE THREAD

**Issue by AlenToma** [microsoft/TypeScript#45259]
# Bug Report

I am trying to compile string to code using `typescript` in `react-native` but keep getting the below error in `typescript`

`TypeError: _os.platform is not a function. (In '_os.platform()', '_os.platform' is undefined)`

Here is the test code I made

```
import * as ts from "typescript";
const sourceFile = ts.createSourceFile(
  "file.ts", // filePath
  "function myFunction() {}", // fileText
  ts.ScriptTarget.Latest, // scriptTarget
  true // setParentNodes -- sets the `parent` property
);
```

Note: I have tested reinstalling the typescript with no luck.

typescript version NO: `4.3.5`

**Comment by RyanCavanaugh** [comment]
Works fine here. Can you post a full stack trace, or provide other info to help repro this?

**Comment by AlenToma** [comment]
Well, I was running this on a Web project and not a service that is why it did not work.  Will close this issue.
