### ISSUE TITLE
TS don't recognize array tuples in *.js files even when they are specified in definition file

### ISSUE THREAD

**Issue by suns-echoes** [microsoft/TypeScript#45253]
# Bug Report

### 🔎 Search Terms

Array tuples not working for JS files
Arrays in JS files are always union of element types so tuple type never works
Broken tuples in JS files

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about array tuples and types union
- It looks like it never worked

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?checkJs=true&allowJs=true&noEmit=true#code/PTAEAEEMBtoewO4CkDOBYAUCCBjAFgKY4DWqmm24AZgJbQEB2kAtgQFygH2sMAuAdABN+vdBgIAPAA5wATr1C8AnlIKgAyr1kBXHL22y1AXlAAKANqYAkMtUcUWmgwDmAGmtwpogPwc4AIwArIgUAH1AGbVh3DCsUbX9fDS1dfUMYgF1QcMjmfwJZbNAHWSdnAEpzLJyo6ABucnFpOQUcaEgUFFAAUW5GBQBvaxLUgwJTco5NHT0xzABfRspaeiZWDi4CHgFAsUkZeVA2jq7erf7QIdiR2cMJy+srQzSGCNqG2MWML4owajpGCx2KBBAUaAA3AjCXaYGjMA6DHp9PigeagKiyODMUAAcn4wE2234uxxH0w+xaR3anVAABEwZDBJwJLxGIJTsjBsMUrdxuUHrEngQXqBLIKrOYcQBBHGuN7RUWPKwSnEAIVll3mcrFyt1OMg-hwsqVyoAjAAmADMMV1VgyGRtyvtjoyHysXy+QA)

### 💻 Code

```ts
// @allowJs
// @checkJs

// @filename: element.d.ts
export type Structure = ([
	type: string,
	opts?: object | null,
	sub?: Structure,
] | number | string)[] | null;

export class Element {
	structure(): Structure
}

// @filename: element.js
export class Element {
	structure() {
		return null;
	}
}

// @filename: derived.js
import { Element } from './element.js';

export class Derived extends Element {
	structure() {
		return [
			['A', null, [
				['B', {}, [
					'abc',
					123,
				]],
			]],
		];
	}
}
```

### 🙁 Actual behavior

Compiler Errors

Property 'structure' in type 'Derived' is not assignable to the same property in base type 'Element'.
  Type '() => (string | {}[][] | null)[][]' is not assignable to type '() => Structure'.
    Type '(string | {}[][] | null)[][]' is not assignable to type 'Structure'.
      Type '(string | {}[][] | null)[]' is not assignable to type 'string | number | [type: string, opts?: object | null | undefined, sub?: Structure | undefined]'.
        Type '(string | {}[][] | null)[]' is not assignable to type '[type: string, opts?: object | null | undefined, sub?: Structure | undefined]'.
          Target requires 1 element(s) but source may have fewer.

Returned structure from Derived class is interpreted as union of types and cause compiler error even though it matches Structure type from declaration type.

### 🙂 Expected behavior

Compiler should first try to check if structure returned from Derived class matches tuple from definition file.

**Comment by RyanCavanaugh** [comment]
This is the same behavior you'd see in TS; return type expressions of class methods don't acquire a contextual type via the `extends` clause. You can fix this by writing
```js
	/**
	 * @returns Structure
	 */
```
above the method
