### ISSUE TITLE
tsserver should support open buffers not file only

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#4526]
Currently the open and all following commands require a file name. However most editors support untitled files. The tsserver should support sending the content of these untitled files to the tsserver to get TypeScript features for them

**Comment by weswigham** [comment]
TBH, I had actually been thinking about this for another project - I had just been planning on loading in dummy files since I wasn't actually using the filesystem anyway, but first class support at the API level for arbitrary buffers would be nice.

**Comment by RyanCavanaugh** [comment]
Isn't this just a matter of the editor providing a temporary filename? The compiler still has to be able to talk about *which* file e.g. an error is coming from.

**Comment by weswigham** [comment]
Yes. Except it the buffers are not _actually in the filesystem yet_. If that's what we'd like to support, we can bake it in to tsserver by wrapping the `ServerHost` used by `IOSession` with a host that has an internal cache for anonymous named buffers in addition to the fs reads/writes it already supports, then adding commands to the server protocol to allow the filling and editing of these buffers by the server's client.

**Comment by dbaeumer** [comment]
@mhegazy: I had the following two use cases in mind which most editors (sublime, vscode, ...) can then support:

- user creates new file without naming it and saving it to disk. He changes the 'file type' to TypeScript. Would be cool if he gets error markers, IntelliSense, for the single file only
- in an untitled file a user adds and import statement. I am fine here with showing an error telling the user he must save the file first. 

@RyanCavanaugh: given the problem of imports I think we should not simulated unsaved files with a temporary file name. This might be confusing for imports and the tsconfig.json resolution.

**Comment by mhegazy** [comment]
@zhengbli can you take a look, looks like a similar change to https://github.com/Microsoft/TypeScript/pull/5593

**Comment by mhegazy** [comment]
This should be working now. `open` command supports a `fileContent`, and a `scriptKindName` properties. The file name (`file`) can be anything, not just a valid file path on disk. so you could pass a uri `"inmemory:\\temp1"`.
