### ISSUE TITLE
Skip strictPropertyInitialization on derived class property with same and type as base class property and useDefineForClassFields is off

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#45268]
# Suggestion

## 🔍 Search Terms

strict property initialization derived property matching base property

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In these cases, we are already guaranteed after a `super()` call that the property has been assigned a value that is the type of the base class property. Thus, `--strictPropertyInitialization` could skip that property.

## 📃 Motivating Example

[playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG8BQ0PQPQCofQCNFoAXCAEwHthpyEJgAnASwAcTnKA7aQPg3B2Xeg4s6TK0aUSCYFPLQAbmBABXBAC5oXZQFsCCRgG5UojMG4QSjZTMqMAFAEoUJzBhIALZhAB0ilUgBeaABGACYAZiNXAF9UWNRQSBgAEX1meQQ5BAAPKS5yGHgIJDRXXHw6Fgy5MioaOgYWdk4eQApyIRFXVmUCEGYaP1UNLV19KNdMLCxoAD85uZcy6YBRRglGDQAFCVZ9EgBPaAByQYQj6HdITUpoZi5mDiVmAC99RcnpsHzbmC5JWgQADM7g8ECBDklmABzLiZW48DxIMxcCxWGyMbxxVBAA)

```ts
class Base {
    /** base tsdoc description 🤷 */
    protected value: number;

    constructor() {
        this.value = 123;
    }
}

class Derived extends Base {
    /** derived tsdoc description ✨ */
    public value: number;
        // ~~~~~
        // Error: Property 'value' has no initializer
        // and is not definitely assigned in the constructor.
}
```

## 💻 Use Cases

Derived classes sometimes redeclare properties with the same name and type annotation as parent properties, but with different peripheries such as member visibility and/or TSDoc comments.

This feels like a halfway point between a bug and a feature.

**Comment by whzx5byb** [comment]
You can use `declare public value: number;`

**Comment by JoshuaKGoldberg** [comment]
True, good point! Seems odd to have to use a syntax most often used for definition files and global variable declarations in a class member, though. Perhaps I should have used the 'bug' template after all?

**Comment by fatcerberus** [comment]
If `useDefineForClassFields` (ES-spec-compliant behavior) is enabled, or when targeting `esnext`, the error is actually correct, because the uninitialized property in `Derived` overwrites the one in `Base` and ends up being `undefined` at runtime in contravention of its type annotation.  `declare` is the correct way to deal with this scenario.

**Comment by JoshuaKGoldberg** [comment]
Err @RyanCavanaugh I think this is still a bug report
