### ISSUE TITLE
lib "dom" doesn't fix "Cannot find namespace 'window'"

### ISSUE THREAD

**Issue by knynkwl** [microsoft/TypeScript#45265]
# Bug Report
### 🔎 Search Terms
dom, lib, Cannot find namespace 'window'

### 🕗 Version & Regression Information
"typescript": "^4.3.5",
"@typescript-eslint/eslint-plugin": "^4.28.5",
"@typescript-eslint/parser": "^4.28.5",

### 💻 Code

```json
{
  "compilerOptions": {
    "outDir": "./theme/assets",
    "allowJs": true,
    "target": "es6",
    "module": "esnext",
    "moduleResolution": "Node",
    "lib": ["es6", "es2015.promise", "dom"]
  },
  "include": ["./src/js/**/*"]
}
```

### 🙁 Actual behavior
Cannot find namespace 'window'

### 🙂 Expected behavior
No namespace error on window

**Comment by DanielRosenwasser** [comment]
Could you give a complete and self-contained reproduction of the issue you're running into? It'll be hard to diagnose the problem otherwise.
