### ISSUE TITLE
Structurally assignable generic types with an object contraint are not assignable, when their properties are a type expression of the constraint

### ISSUE THREAD

**Issue by soul-codes** [microsoft/TypeScript#45261]
# Bug Report

### 🔎 Search Terms

generic object type assignment

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for all entries on "bugs that aren't bugs", and nothing matches.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gWygaxABUBPABxAC54AeQgPgAoBKeAXjvkIG4AoHkAB6kkMLBjIIAgrXiCMIFMDTwA3vCgUArijwokAdxTwAvh1aqe8K3CjBUEYvABmSJFUIBtAERQvAXXgAH3hMGABLFABzHmM+ZHQsJDwqaRUNFE1sACMQGFNvFyR-Nhx8IglqVI1QiMj8r0L-RiZeeMx4fQALYgBRGBgRAEYU6jSKDOzc0xLcAhJyStHqjHCo02bW1Hau3v6RACYRsYmcmAAaLIoatbNSuYqqq5Xa9eZNhI7uvoGYAGYj9KZU4XJ6rOq3WblBaPE65EFZVwQEBQFCvFo8IA)

### 💻 Code

```ts
declare const makeType: <T>() => T;

export type A<T extends { a:unknown }> = {
   readonly foo: T["a"] | string
}

const ok: A<{a:number}>["foo"] = makeType<A<{a:string}>["foo"]>();
const whyError1: A<{a:number}> = makeType<A<{a:string}>>();
const whyError2: A<{a:number,b:string}> = makeType<A<{a:string}>>();
const whyError3: A<{a:number,b:string}> = makeType<A<{a:number,b:boolean}>>();
```

Note that in the code above:
- The type `{ readonly foo: string }` is assignable to `A<T>` **for _all_ `T`**.
- `A<{ a: string }` _is_ `{ readonly foo: string }`.

### 🙁 Actual behavior

The assignments of `whyError1`, `whyError2`, `whyError3` fail even though the types on both sides _structurally_ resolve to what should be assignable types. 

- For `whyError1` and `whyError2`, LHS resolves to `{ readonly foo: number|string }`, RHS resolves to `{ readonly foo: string }`.
- For `whyError3`, both LHS and RHS resolve to `{ readonly foo: number|string}`.

### 🙂 Expected behavior

All assignments should be allowable.

**Comment by soul-codes** [comment]
FWIW, if the type is instead defined like this:

```ts
export type A<T extends { a:unknown }> = T extends { a: infer X } ? {
   readonly foo: X | string
} : never
```

Then all assignments work. However, this form makes it impossible to make `A` an `interface`.

Also, the OP gives a _minimal_ example of the behavior. In reality, the constraint `T` is being thrown around in a number of types, interfaces and functions, and has several properties.

**Comment by RyanCavanaugh** [comment]
We intentionally take a completeness/performance trade-off here since this situation isn't particularly common, and always performing a structural check when a reliable variance measurement exists is extremely expensive.
