### ISSUE TITLE
Object.values can't infer type for interface

### ISSUE THREAD

**Issue by MarcelGerber** [microsoft/TypeScript#45273]
# Bug Report

### 🔎 Search Terms

Object.values, any, interface

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Object.values`.
In particular, this happens in version 4.3.5.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/PTAEBUE8AcFMCgCWA7ALrATgMwIYGNZQBBAD0QGcBJZLAe1AG95QXQ9abEBzALkdAC2KPsgCuAgEaYANIJwkR4qRlABfeOvghQAEQDyAUQDKAOQDk4UAHU9AJQDSfAMI5yhAIx8AquRRdQKOjY+AiBmLgExCSwVDT0TKygClEU1HTMrJB8pKlxGvDw7MjkqKDyMdnRsXSgALyMGSzJCYmsRVjcfAyCwqAADLIC8nwArH1q0o0TU1kNrW0cHbz8Qsh8A3LJ7n3jqpOJe-laYLUAfGyL3AB0QyQB5KC0WKAABjjIkC+gqDAIehIAK1geFQVwAbjgADaiGIACnK5AAlFc6BgDPgABaw2HddrcNSIurnKGYVCwvFcG7yRGIgraGwOIygABilBMBmcrkIACZvL5kP5RMhEBxQLZgbQMAATeA-OBRGJpWjcupiiXSgA8ACISFrQAAfUBayBa2Q5aq0U4FIolMpVXkKi0q+otJpdKaJCldHprfqDYagMbTA77TLu+YsL0rXobW58ba7UMsQ6abRnC6cSm3e6PZ5ywgvMSSTAveD-IEg8FQmHkeH25Go9F4LE4jNLAlEsqQ0nky5Z6mIoA)

### 💻 Code

```ts
// Type
interface AxisInfo {
    config: { min: number, max: number }
}

// DOESN'T WORK: Case 1: Using interface
interface AxesInfo {
    x: AxisInfo
    y: AxisInfo
}

const axes: AxesInfo = {
    x: {
        config: { min: 0, max: 50 },
    },
    y: {
        config: { min: 0, max: 100 },
    },
}

// => config.max is of `any` type
Object.values(axes).forEach(({ config }) => alert(config.max))

// WORKS FINE: Case 2: Using union Record
type AxesInfo2 = Record<"x" | "y", AxisInfo>

const axes2: AxesInfo2 = {
    x: {
        config: { min: 0, max: 50 },
    },
    y: {
        config: { min: 0, max: 100 },
    },
}

// => config.max is of type `number`
Object.values(axes2).forEach(({ config }) => alert(config.max))
```

### 🙁 Actual behavior

`Object.values(axes)` is of type `any[]`.
`Object.values(axes2)` is of type `AxisInfo[]`, as expected.

### 🙂 Expected behavior

`Object.values(axes)` is of type `AxisInfo[]`.

**Comment by MarcelGerber** [comment]
Note that this issue can be worked around with the rather cumbersome
```ts
export const values = <Obj>(obj: Obj): Obj[keyof Obj][] =>
    Object.values(obj)
```

**Comment by MartinJohns** [comment]
See #38520.
