### ISSUE TITLE
Allow query string in module path

### ISSUE THREAD

**Issue by otakustay** [microsoft/TypeScript#45277]
# Suggestion

## 🔍 Search Terms

query string, import query, import param 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Here is an example which **do not ** work:

```ts
// static.d.ts
declare module "*.svg" {
    const url: string;
    export default url;
}

declare module "*.svg?react" {
    const value: number;
    export default value;
}

// index.ts
import foo from './foo.svg';
import bar from './bar.svg?inline';
```
With this example `tsc` outputs:

```
2 import bar from './bar.svg?inline';
                  ~~~~~~~~~~~~~~~~~~


Found 1 error.
```

Add query string to paths is quite common in webpack land.

I suggest to support multiple `declare module` with different query string, each query can specify a different types, so developers can, for example, get a string from `./foo.svg` and a react component from `./foo.svg?react`.

## 📃 Motivating Example

By providing different query string in module declaration types, TypeScript can make a single file extension to behave as different types, this works with bundler tools like webpack.

## 💻 Use Cases

The real world case is we import `.svg` file as a react component in component files like:

```jsx
import {ReactComponent as FooImage} from './foo.svg';

return (
  <div>
    {/* In this way we can specify the color and size */
    <FooImage style={{fill: 'color'}} />
  </div>
);
```

And in other javascript files we need it as a url string:

```js
import fooImageURL from './foo.svg';

document.body.style.backgroundImage = fooImageURL;
```

**Comment by glen-84** [comment]
@otakustay Did you find a solution?
