### ISSUE TITLE
Separate more clearly what is Typescript and what is Javascript code

### ISSUE THREAD

**Issue by jpolo** [microsoft/TypeScript#45271]
# Suggestion

## 🔍 Search Terms

keywords, enum, namespace, conflicts, ecma

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code (not at first at least)
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Use `ts` prefix for Typescript only keywords (ex: enum, namespace).
Deprecating existing keywords is not mandatory, this could happen in a future major release.

### Problem
Typescript keywords can conflict with future ECMA spec.

Unless perfectly knowing each ECMA and Typescript features, a developer cannot easily identify pure Typescript feature from an ECMA.

### Situation

The current philosophy of Typescript is : it is just a superset of Javascript. This superset is not clearly recognizable from ECMA features.

At the moment Typescript is using grammar keywords that are ECMA relevant (ex: class, const, etc) along with others that are pure Typescript (namespace, enum)
This leads to some problems and dangers : 
* unless a certain level of expertise, understanding the result of tsc : "basic type stripping" VS "little more complicated code with potential caveats" is not always natural
* ECMA future features will always represents a technical threat. For example if they decided to use the namespace keyword, enum with different behavior.

Global type helpers like (`ReadonlyArray`, etc) could also conflict with a new ECMA global (the probability could be low, but possible)

The last point to the situation : Typescript, like Babel is a strategical tool for ECMA innovation and should continue to explore new patterns.

### Suggestion

I would suggest to adopt the keyword prefix strategy like CSS properties and rendering vendors (WebKit, Mozilla, etc).

For example : 
`ts_namespace`/ `tsNamespace`/ `tsnamespace` /(...) instead of just `namespace`
`ts_enum`/ `tsEnum`/ `tsenum` /(...) instead of just `enum`.

From a user perspective every `ts*` keyword will be easier to spot in the code.

The use of prefix will probably have the same benefits than with WebKit : Typescript team will be able to implement innovative features, without worrying of conflicting ECMA future proposals and breaking other tools. Those features could be later added to the ECMA language "easily" by just removing the prefix.

**Comment by MartinJohns** [comment]
> Typescript team will be able to implement innovative features, without worrying of conflicting ECMA future proposals and breaking other tools.

But they **want** to do this. That's an explicit [design goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) they state:

> Align with current and future ECMAScript proposals.

By implementing "innovative features" they run risk to not align with future ECMAScript proposals anymore. What would they do then? Remove entire features causing massive breaking changes?

**Comment by RyanCavanaugh** [comment]
We're trying not to add these features in the first place, and in fact haven't for many years.

**Comment by jpolo** [comment]
@MartinJohns There are already some features that are not aligned with ECMA syntax. ex: enum and namespace. More recently override was introduced. => What if ECMA suddenly choose to implement this keyword with a different behavior than Typescript ?
The immediate consequence if ECMA decides to use keywords, it will defacto imply the change of many existing libraries.
This potential problem would also happen with global type helpers.

I see all these globals and keywords as little mines that could explode one day or never. IMHO, Typescript should extends grammar and globals in safer manner, i.e. using some kind of prefix. 

@RyanCavanaugh The goal of this issue is not a change TS philosophy. I am perfectly fine with the alignment with ECMA. As a matter of fact you did recently extend grammar adding `override` keyword. So my point is just that with this standard of adding new keywords and global type helpers, Typescript is going to the opposite direction of aligning with "Future ECMA spec".
