### ISSUE TITLE
Improve the performance of updateExportedFilesMapFromCache

### ISSUE THREAD

**Issue by amcasey** [microsoft/TypeScript#45283]
https://github.com/microsoft/TypeScript/pull/45238 mitigates performance problems in `updateExportedFilesMapFromCache` but doesn't address the underlying problems.

 1. Why is `updateExportedFilesMapFromCache` called so many times during the course of building a single projects?
 2. If not making any updates is the common case, would another representation be more appropriate (e.g. storing a delta, rather than a copy)?
 3. If we continue to update the "real" map from a full cache, can the update share code with `clone`?  (The PR doesn't because `clone` appears to make a shallow copy which (a) seems wrong and (b) wasn't what the code being replaced did.)

**Comment by sheetalkamat** [comment]
> clone appears to make a shallow copy 

This was intentional.. After state is formed, the referenceMap (the way it was normal map before) can only be set with New set of values.. doesnt modify existing values..

**Comment by sheetalkamat** [comment]
Fixed by https://github.com/microsoft/TypeScript/pull/48579
