### ISSUE TITLE
Wrong type inference

### ISSUE THREAD

**Issue by dschuessler** [microsoft/TypeScript#45282]
# Bug Report

The following code throws an error that – as far as I can judge – is unwarranted.

```ts
class OrderFixture {
  orderId: string;

  constructor() {
    this.orderId = "foo";
  }
}

class DecisionFixture {
  decisionId: string;

  constructor() {
    this.decisionId = "bar";
  }
}

class FixtureStore {
  order = () => new OrderFixture();
  decision = () => new DecisionFixture();
}

const fixtureStore = new FixtureStore();

export function getFixture<
  K extends keyof FixtureStore,
>(entityName: K): ReturnType<FixtureStore[K]> {
  return fixtureStore[entityName](); // ERROR: Type 'OrderFixture | DecisionFixture' is not assignable to type 'ReturnType<FixtureStore[K]>
}
```

I've given Typescript every information it needs to infer the correct type, yet it doesn't.

I am not an expert in type systems so I might be wrong but I was encouraged to report this behavior as a bug from a fellow StackOverflow user who [had a look at this problem before.](https://stackoverflow.com/a/65615187/5388264)

### 🔎 Search Terms

I am lacking the expertise in type systems necessary to even know how to generalize my problem and derive search terms. 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDyBOATApvAYgSwB4BcCu8y0A3gFDTQD2SqAkogFzQQ7wYB2A5gNynnTBK7FvDzAc1ABQBKEvwo4AFhggA6ainj1oAXmgAiAGaVK+3hQC+pK6VCQYAEWTAVGIZlwEiZCihcQ3dnomEQ4ePgpBYVYxCXgZOQoFZTU-VyFtPX0AIzB4M34rGzsoaA98QgBlOO9+DVRdaASdAD5odmQAdzgadGwK5BlzaDSAoUbmto7up39A8q8h6z4olmhDfq9q6iI9abLNqpql0mQsAAdqHHW8dnFA6E5kHAXCAB5+AGloM5xkdkQMAA1sgAJ6UQwHTxHHYAGlILUk-xwGBwoIAcmAALbIJifaRMABKzwI7AAKqDzsg3q9kNtCABtT4AXTaPmghAq7HWhzpNQZyNRGOxyGZQ2gAHoJdAAKKEwmwQlMClU6AAcgQmlpaugKnalGu9gwnHYYGyICIEmgaNVarJatUyyAA)

### 💻 Code

see above

### 🙁 Actual behavior

The following error is thrown in line 27:

```
Type 'OrderFixture | DecisionFixture' is not assignable to type 'ReturnType<FixtureStore[K]>'.
  Type 'OrderFixture' is not assignable to type 'ReturnType<FixtureStore[K]>'.(2322)
```

### 🙂 Expected behavior

No error is thrown.

**Comment by MartinJohns** [comment]
You're wrongly assuming `K extends keyof FixtureStore` means that `K` **always** just refers to **one** key, but that's wrong. `K` can be `"order" | "decision"` as well.

You would need #30581 or #27808 for this.
