### ISSUE TITLE
Figure out how to encode `sortText` (because it means TypeScript deprecated completions show up first)

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#45288]
Try requesting completions in a blank file.

![image](https://user-images.githubusercontent.com/972891/127911815-ad027f3c-0710-45dc-b3d4-090b002072de.png)

I think this is because [our `SortText` uses numeric text](https://github.com/microsoft/TypeScript/blob/76d754329e42ba641759b78ea3e37c2a0cf57a04/src/services/completions.ts#L9-L25), but the text is sorted as a string. Why would that matter? Well, global deprecated completions have a numeric value of `13`, **which is less than almost any other completion entry type**.

[Editors just do a basic string comparison of `sortText`s, so we should figure out how to fix this](https://github.com/microsoft/vscode/blob/a2c4a0ca8ca8b86e8dd32e20e596a2e00bfdeaf9/src/vs/editor/contrib/suggest/suggest.ts#L302-L319).

**Comment by andrewbranch** [comment]
We’ll need an entirely new scheme if we want to do https://github.com/microsoft/TypeScript/issues/41083, which I plan on looking at for 4.5.
