### ISSUE TITLE
`as const` does not narrow when object literal defined with type

### ISSUE THREAD

**Issue by jisaacks** [microsoft/TypeScript#45287]
# Bug Report

### 🔎 Search Terms

Searched: 
> `typeof` doesn't narrow, ignores `as const` when object literal defined with type 

### 🕗 Version & Regression Information

[Example in playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4Chm+QbQGsAuZAZzClAHMBdUgchgHtmHkAfZBgIzinZdecAF6DuzMAAtoDLAF8sWBMxAVkLZsXQBeTDjxxGmhgBoDuHoz4Dz85HDLIVasErABPAA4oAYqwBpCA8nPUJg5hhkTx9IjVYgA)

### 💻 Code

```ts
interface A {
    [k: string]: 'foo' | 'bar' | 'baz' | 'other'
}

const foo:A = {
    a: 'foo',
    b: 'bar',
} as const

type FooKeys = keyof typeof foo
```

### 🙁 Actual behavior

Since foo is defined as `A` the `typeof` ignores the `as const` and `FooKeys` ends up being `string | number`

### 🙂 Expected behavior

I would expect foo being defined with `as const` would narrow to a type with only `a` and `b` keys.
So I would expect `FooKeys` to be `"a" | "b"`

-----

# Workaround

```ts
interface A {
    [k: string]: 'foo' | 'bar' | 'baz' | 'other'
}

const bar = {
    a: 'foo',
    b: 'bar',
} as const

const foo:A = bar

type FooKeys = keyof typeof bar
```

### If this is not a bug

If this is actually expected, can this issue be transferred into a feature request?

**Comment by RyanCavanaugh** [comment]
See https://github.com/microsoft/TypeScript/issues/7481

**Comment by jcalz** [comment]
This is working as intended and doesn't have much to do with `as const`.

`A` is not a union type, so the assignment of a value of type `{  readonly a: "foo";  readonly b: "bar"; }` to a variable of type `A` does not result in any narrowing via [control flow analysis](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#control-flow-analysis).  The variable `foo` is of type `A`; it is not narrowed by assignment; its keys are `keyof A`.

If you're asking that control flow analysis take place on non-union types, then this might be a duplicate of #16976.

**Comment by jisaacks** [comment]
@jcalz gotcha thanks, I'll close it then.
