### ISSUE TITLE
FR: assertions that throw could narrow types

### ISSUE THREAD

**Issue by samouri** [microsoft/TypeScript#45280]
# Suggestion

After a type narrowing assertion which throws, the type can be narrowed.
This is a common pattern in Closure codebases.

```ts
function assert<T>(o: any): NonNullable<T> {
    if (typeof o === null) {
        throw new Error();
    }
    return o;
}

function doThings() {
    let n = (42 as unknown) as (null|number);
    assert(n)

    n; // <--- Should be narrowed to `number`
}
```

## 🔍 Search Terms

Type Narrow Assertion Throw Error

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases

- This would assist with migrating a large Google Closure based codebase to TS.

**Comment by nmain** [comment]
You're looking for [assertion functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions).

**Comment by samouri** [comment]
@nmain, thats exactly what I'm looking for. Do you know if it is compatible with JSDoc Typing?

**Comment by IllusionMH** [comment]
You can use same TS specific return type `@returns` annotation
[Playground](https://www.typescriptlang.org/play?noImplicitAny=false&filetype=js#code/FAegVGwARlACAHAhgJyQWygbzAXygMYD2AdgCYCWALhadLHCgKZUCuKJAztkp50yirdi5arRK56IYADNWJAjVJRe-QQAoRlJSQCU2aFBAgoFdAgA2TdExJUkO4JNAR68ZGkw58ANyQXWJjdGFnYuHj4BISg-AKZTbk4qFAoSAHNJGGk5BR0VSMEAZWTUtPVYwP0sQ2NTcysbOwdxJ2BZeUVxKComJIBGdSSUKsMhgDoqIgAxCgAPJjJ1XQBuIxMSIigBFCIUfKhWTlZ-Vvbcrp6kgCZB5JGofLUqdSoATwQmIhkoIagAXgBUAARENSkCVqNkhMiABVBAfFAAYV4TCWaygGy2KB2KEhKGhM3mixW6O2u24vC2sw+igWpxynWUlyoNyG90eUWKKXSt2Gyzx0LhCOR-DRtUxZNxD3Gk0JCyWq1qkop3CY1KYtLITiAA)

**Comment by samouri** [comment]
Thank you all so much! Closing
