### ISSUE TITLE
Re-export class from namespace

### ISSUE THREAD

**Issue by Koloto** [Microsoft/TypeScript#4529]
I want to re-export some class defined in a module scope from a nested namespace. First I tried new ES6 syntax, but got an error:
```ts
export class Foo {}
export namespace a {
	export { Foo } // TS1194: Export declarations are not permitted in a namespace.
}
```
Ок, tried `export import`:
```ts
export class Foo {}
export namespace a {
    export import Foo = Foo; // TS2303: Circular definition of import alias 'Foo'.
}
```
So I have to define temporary import:
```ts
export class Foo {}
import FooTemp = Foo; // TS2503: Cannot find namespace 'Foo'.
```
Ok, let's declare module `Foo` also:
```ts
export class Foo {}
export module Foo {}
import FooTemp = Foo;
export namespace a {
    export import Foo = FooTemp;
}
```
And only now the compilation is successful. It's really complicated workaround. And it forces to define extra variable in generated JS. I would prefer the first or second code sample. Or maybe is there another way?

**Comment by Koloto** [comment]
I found a better workaround - rename the source class:
```ts
class FooTemp {}
module FooTemp {}
export { FooTemp as Foo }
export namespace a {
    export import Foo = FooTemp;
}
```
It's also complicated but there is no extra variable in JS.

**Comment by RyanCavanaugh** [comment]
There's not much we can do here since, at runtime, the name `Foo` only has one meaning inside `a`.

**Comment by Koloto** [comment]
@RyanCavanaugh Why ES6 export declarations are not supported in namespaces? In the generated JS code this can look like this:
```
    var Foo = (function () {
        function Foo() {
        }
        return Foo;
    })();
    exports.Foo = Foo;
    var a;
    (function (a) {
        a.Foo = Foo;
    })(a = exports.a || (exports.a = {}));
```
This works fine at runtime.

And why do I have to declare module `Foo` to import class `Foo`?

**Comment by mhegazy** [comment]
> And why do I have to declare module/namespace Foo to import class Foo?

There is no reason really. we wanted to limit the use of imports to avoid conflicts with ES6 syntax. i think we should reconsider. @Koloto would you mind filing a suggestion for it.

**Comment by rybolt** [comment]
@mhegazy anything come out of this? if so could you link from here, as I landed here via google search.  Thanks.

**Comment by mhegazy** [comment]
no issue tracking this.

**Comment by mzygmunt** [comment]
@Koloto in TS 2.1.1 you can use following pattern:
```typescript
// export1.ts
export class A {}
export namespace B {
    export { A } // TS1194: Export declarations are not permitted in a namespace.
}
```
```typescript
// export2.ts
import { B as _B } from "export1.ts";

export namespace C {
    export import B = _B;
}
```

**Comment by robey** [comment]
I got here from a desperate search too. It appears to still be broken? Any new word?

**Comment by bios21** [comment]
Please make it append. Non intuitive workaround can lead to bad practices.

```typescript
import Class1 from "./Class1";
import Class2 from "./Class2";
import {Class3, Class4} from "./OtherClasses1";
import {Class5, Class6} from "./OtherClasses2";

export {Class1, Class2} //ok

export namespace OtherClasses {
    export {Class3, Class4, Class5, Class6}; // export not permitted...
}
// or better
export {Class3, Class4, Class5, Class6} as OtherClasses;
```

**Comment by MaximBalaganskiy** [comment]
@bios21 does TS let you define variables in other modules?
`
var someVar: rootModule.OtherClasses.Class3;
`
I cannot get it to work in my project

**Comment by bios21** [comment]
@MaximBalaganskiy I have no problem with this line.
Dummy code for example:

```typescript
// MyModule.ts
export default class Sub {} // (Sub ~= Class3 in your snippet)
```

```typescript
// index.ts (my entry point in webpack context)
// all exports are bundled into the rootModule object
import Sub from './MyModule';

export const NS = { //in this fake namespace, it's !object! not type description (NS ~= OtherClasses in your snippet)
    Sub: Sub // can be 'AnyOtherVarName: Sub' ; Sub type is invariant in this case except if you 'import-as' it.
}
```

```typescript
// in any other external ts file
var someVar: rootModule.NS.Sub; // ok
var someOtherVar = new rootModule.NS.Sub(); // ok
```
