### ISSUE TITLE
using an event handler in a jsx tree, "this" must be bound explicitly

### ISSUE THREAD

**Issue by flq** [Microsoft/TypeScript#4530]
consider the following react component:

    class Button extends React.Component<ButtonProps,{}> {
      render() {
        return (
          <button type="button" onClick={this.handleClick.bind(this)}>
            {this.props.caption}
          </button>
        );
      }

      private handleClick() {
        alert(this.props.caption + ' was clicked');
      }
    }

You will notice that I needed to explicitly state to which `this` the event handler needs to be bound. I assume that the compiler that I was using previously (from react tools) did the binding for me, as the call to `bind` was not necessary.

I would like to propose that typescript's jsx parser should provide similar functionality, as it further improves readability and eliminates a typical source of error that cannot be checked during compilation time. What do people think?

**Comment by RyanCavanaugh** [comment]
I don't see why we'd treat expression occurring inside JSX expressions any differently from normal code -- that'd be exceptionally weird and hard to explain.

There are already many good solutions for this, e.g.
```ts
class Button extends React.Component<ButtonProps,{}> {
  render() {
    return (
      <button type="button" onClick={this.handleClick}>
        {this.props.caption}
      </button>
    );
  }

  private handleClick = () => {
    alert(this.props.caption + ' was clicked');
  }
}
```
I expect whatever you were using before did a similar thing (putting a per-instance `this`-bound closure on the class).

**Comment by jbrantly** [comment]
To supplement Ryan's answer (which is 100% correct):

The autobinding behavior was actually part of the `React.createClass` API and is not available when using ES6 classes. [See here](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding) for more info. It never had anything to do with JSX.

[This article](http://babeljs.io/blog/2015/06/07/react-on-es6-plus/) is also really useful when making the switch to ES6 classes in React.

**Comment by fzzzt** [comment]
That doesn't actually work, at least not with TS 1.7 and TSX, as far as I can tell. Maybe there is some other dependency for this to work. When I write it that way, `this` still doesn't reference the component instance and my `this.state` doesn't exist (same for just defining it as `handleClick()`, which is what brought me here). Maybe that works if you're writing ES7 directly, I dunno, we're using TypeScript and TSX, which up until now has been great.

Without pasting everything, this is what I have:

```
private getHeaderCell = (label, cellDataKey, colData, rowData, width) => {
    // this -> Object {align: "left", cellData: "id", cellDataKey: 0, className: undefined, columnData: ImmutableObject…}
}
// ...
render() {
    // ...
    var cols = this.state.headerColumns.map(function (headerColumn, index) {
        return <FixedDataTable.Column
            cellRenderer={this.getCell}
            headerRenderer={this.getHeaderCell}
            // ...
        />;
    }.bind(this));
    // ...
}
```

Pulling it out of the `map` to get rid of that `bind(this)` doesn't help. `getHeaderCell` does get called, but `this` isn't correct when it's in there. I'll just keep using `bind(this)` on all the callbacks for now.
