### ISSUE TITLE
`stripInternal` should remove the `export` keyword from declarations instead of removing them entirely

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#45307]
# Bug Report

my use case for `stripInternal` is a type definition i want to share between two different files in my project, but not expose as part of the public api. since `stripInternal` removes the type entirely it breaks the types that use it.

### 🔎 Search Terms

stripInternal

### 🕗 Version & Regression Information

4.4.0-dev.20210803

#### `foo.ts`
```ts
/** @internal */
export type Foo = 1

export type Bar = Foo | 'bar'
```
#### `bar.ts`
```ts
import {Foo} from "./foo";

export type Baz = Foo | 'foo'
```
#### `foo.d.ts`
```ts
export declare type Bar = Foo | 'bar'; //Foo doesn't exist, so Bar is now just an alias for any
```
#### `bar.d.ts`
```ts
import { Foo } from "./foo"; //Foo doesn't exist
export declare type Baz = Foo | 'foo'; //Baz is now just an alias for any
```

### 🙂 Expected behavior
perhaps the `export` keyword is stripped from internally defined types and they instead are duplicated wherever they are used in the declarations
#### `foo.d.ts`
```ts
type Foo = 1
export declare type Bar = Foo | 'bar';
```
#### `bar.d.ts`
```ts
type Foo = 1
export declare type Baz = Foo | 'foo';
```

**Comment by RyanCavanaugh** [comment]
https://www.typescriptlang.org/tsconfig#stripInternal (emph. mine)

> Do not emit declarations for code that has an @internal annotation in its JSDoc comment. __This is an internal compiler option; use at your own risk, because the compiler does not check that the result is valid__. If you are searching for a tool to handle additional levels of visibility within your d.ts files, look at api-extractor.
