### ISSUE TITLE
creation of README.md file in Brazilian-Portuguese

### ISSUE THREAD

**Issue by pecampelo** [microsoft/TypeScript#45303]
# Suggestion

brazilian-portuguese, language support, PT-BR;

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

I want to be able to participate in the facilitation of a worldwide-used product which is Typescript by enabling speakers from my country, so fellow Portuguese speakers that do not speak English to have access to TS' original documentation.

I have already submitted the README_PT-BR.md as a pull request, if it is accepted I will certainly translate more of it.

**Comment by RyanCavanaugh** [comment]
Documentation on this repo, including README.md, is for developers working on TS itself, which can't be meaningfully approached without understanding of English. We're not staffed to keep multiple READMEs in various languages up-to-date or verified, so this isn't something we're able to accept.

The original documentation is the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/), which is [available in Portuguese](https://www.typescriptlang.org/pt/docs/handbook/) where it's been translated. Further translation work there is always greatly appreciated; see https://github.com/microsoft/TypeScript-Website-Localizations
