### ISSUE TITLE
`noUncheckedIndexedAccess` does not work correctly with `Array`

### ISSUE THREAD

**Issue by SuperITMan** [microsoft/TypeScript#45306]
# Bug Report

### 🔎 Search Terms

`noUncheckedIndexedAccess` with arrays

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `noUncheckedIndexedAccess`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?noUncheckedIndexedAccess=true#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAAoKolLCoAFxoZOxKKqGc8ACq5tiwANaQ3ACSPJAAHnkAgrAWgoJxkYnBCJwRYmRkcRGUnMwA2gC6oAC8oH0A3A3wTTQKzUMAFACUgwB8oADeiqCbIgBmoLOOZAHuXaiaKwCMi+tbN6AqZcIHR5AnZ6Dn-FKgJUTRWAw0Y7MU6gJZDABMAW8DhoyDMj1a3QADP17BxoK5pM5QAADDoULo4ja3TaNZoddqRAnMQYtMjdJ5AkEAWlA4N6I1AxJJZPg7iO8GYsw68zGNwAvsEbipiAxkKBsE5PigNJAcnTnq9BkMPqBBBgDsjUZh0ZjsXiqYSxDwTGZUjQsbiuNxINsCXkcWJKvAyNxqWgMC7YIwyACKBNcWSaAdKZ0ev0hqMiTcKLt9q1NcDNAMc+9QAAyfN0o0BRAAjSzYDTVDAeZXLkk0kTfX86CC2YAIgAYhQyM0CS7iqAy6hVcIAOTV8cd0Xc0CSyXBFQ4DDuTzDn3OaQcKbYNxmZjsBjMSD8YPqbJibd6EReDsAUWKcoI7kEHdAPtAHfAMPHwgAcpAEgdkEKgAPKnJAZASEIp5aJANARI4CiYngoBOIg8A6P6kGCCqSDIJwqCPDakGSD6GIiAYHBkKAL5MKwHA8EEmxAA)

### 💻 Code

```ts
// @strict: true
// @noUncheckedIndexedAccess: true

const arr: string[] = [];

const test = () => {
    if (arr.length > 1) {
        // As arr.length > 1, we expect that length >= 2. That means arr[0] should be a `string`
        const str: string = arr[arr.length - 2]; 
        console.log(str);
    }

    // Same here, we check arr.length == 1, so arr[0] should be a `string` and cannot be `undefined` according to declaration `const arr: string[] = [];`
    if (arr.length === 1 && arr[0].match(/test/)) { 
        console.log("First index matches 'test'");
    }
}
```

### 🙁 Actual behavior

Get following errors: 

```bash
error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
    const str: string = this.arr[this.arr.length - 2];

error TS2532: Object is possibly 'undefined'.
    if (arr.length === 1 && arr[0].match(/test/))
```

### 🙂 Expected behavior

The code should not generate any error since the array is type `string[]` and not `(string|undefined)[]`

**Comment by RyanCavanaugh** [comment]
This was one of the outlined caveats of the flag; see #13778
