### ISSUE TITLE
Comment is removed if it is followed by an unused import

### ISSUE THREAD

**Issue by alvinleung1996** [microsoft/TypeScript#45318]
# Bug Report

Comment is removed if it is followed by an unused import.

### 🔎 Search Terms

comment removed unused import

### 🕗 Version & Regression Information

- I can reproduce the bug using v4.3.5 and v4.4.0-dev.20210803
- I have reviewed the FAQ for entries about ["Why some comments are not preserved in emitted JavaScript even when --removeComments is not specified?"](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-some-comments-are-not-preserved-in-emitted-javascript-even-when---removecomments-is-not-specified) and this is not covered

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/PTAEGMHsFtoUwHYBdQEYBQBLaAHSAnFAb1H0QBM59QBDAZ1IqtVAF9QAzfGUAchzI1wSXuhAQY8ZKABMWXAWKMElavWWqZbTt2h8BcISLFgosRCgDM8vIVAkyKqrQaPVl7Vx79Bw0eLMpFAAWdHQ3ZgAKAEpwpnxLGPQgA)

### 💻 Code

```ts
// comment 1
import { render as render1 } from 'preact'
// comment 2
import { render as render2 } from 'preact'
// comment 3
import { render as render3 } from 'preact'
// comment 4

render1()
render3()
```

### 🙁 Actual behavior

```js
// comment 1
import { render as render1 } from 'preact';
// comment 3
import { render as render3 } from 'preact';
// comment 4
render1();
render3();
```

Comment 2 is missing.

### 🙂 Expected behavior

```js
// comment 1
import { render as render1 } from 'preact';
// comment 2
// comment 3
import { render as render3 } from 'preact';
// comment 4
render1();
render3();
```

Comment 2 should be outputed.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior - comments are attached to their following nodes and are not printed if their corresponding node is not printed. In general this is also the desired behavior from a user perspective
