### ISSUE TITLE
TS intelligence not working

### ISSUE THREAD

**Issue by bradyasana** [microsoft/TypeScript#45316]
Issue Type: <b>Bug</b>

I had just generated a bunch of TS files on my local machine, which may have overloaded the TS server?

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (3.12GB free)|
|Process Argv|. --crash-reporter-id f8790d37-ee16-4930-bf63-ec4dd5a67828|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490

```

</details>

**Comment by RyanCavanaugh** [comment]
It's certainly possible (and likely) to exhaust resource limits with 15,000 files. The LS is not really designed to scale up to an unbounded size; you will likely need to create some configuration to scope it down if you want intellisense. We are also working on some modes to automatically limit the analysis to the set of opened files; stay tuned for info on that.

**Comment by bradyasana** [comment]
Hi sorry for the delayed response here.

> We are also working on some modes to automatically limit the analysis to the set of opened files; stay tuned for info on that.

This sounds very promising!

As an addendum to my request, would it be possible to add more verbose logging so users can more accurately diagnose the failure here? As said above, the last log line wasn't particularly informative - indicating why the server crashed / what resource it ran out of would be incredible!
