### ISSUE TITLE
strictPropertyInitialization detect initialization of member variables in functions that were called form with in constructor

### ISSUE THREAD

**Issue by wesleyolis** [microsoft/TypeScript#45322]
## 🔍 Search Terms
strictPropertyInitialization [[call] function, detect variables initialized]

## ⭐ Suggestion

Basically enhanced typescripts ability to track variable initialization to span member function calls from the constructor.

Typically this style code writing is done a lot in many software stack I have been in.

## 📃 Motivating Example

```.ts
class A {
private a:number;
private b: string;

construction(props) {
this.resetInit();
this.state = this.getDerivedStateFromProps(this.state, props); // Proposed it to become member variable as well.
}

  resetInit() {
  this.a = 1;
  this.b = "test';
  }

  getDerivedStateFromProps() {
  
  return newState;
  }
}

```

## 💻 Use Cases

React, many places where want to avoid duplicate initialization code and reset code, which call all take place in a common function, but due to typescript can't be done.

## ✅ Viability Checklist

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
In 2018 it was called a Design Limitation. Most likely this still applies. See #21132.
