### ISSUE TITLE
TS 4.3.5  Property '' is used before its initialization. ts(2729)

### ISSUE THREAD

**Issue by askeet** [microsoft/TypeScript#45325]
# Bug Report
When I switched workspace version of TS from 4.1.5  to  4.3.5 I started to see an warning 
_Property 'getters' is used before its initialization. ts(2729)_
```
export class RootGetters {
  constructor(private getters: any) {}
  evenOrOdd = (): string => this.getters[`${MODULE}evenOrOdd`];
}
```

It can be fixed like this 

```
export class RootGetters {
  private getters: any;
  constructor(getters: any) {
    this.getters = getters;
  }
  evenOrOdd = (): string => this.getters[`${MODULE}evenOrOdd`];
}
```
 
But why the first case is not valid ? 

### 🙂 Expected behavior

Warrning ts(2729) should be fixed

**Comment by fatcerberus** [comment]
This looks like #45182.
