### ISSUE TITLE
Typescript intellisense is slow

### ISSUE THREAD

**Issue by momocow** [microsoft/TypeScript#45327]
Issue Type: <b>Performance Issue</b>

---

Screen record available on Imgur:
<a href="https://imgur.com/d39eZ1O">View post on imgur.com</a>

The slowness happens since I resolved a conflict on my node_modules and did the `npm audit fix`, I think it's related to dependencies but I have no idea how to further find out the problem.

Before resolving the conflict of `ajv` (the project is planning to use v8 while my dependency, `schema-utils` uses v6), the intellisense has no problem, and after I installed `ajv` with flag `--legacy-peer-deps` and did `npm audit fix`, the intellisense started to get delay.

Here is what `npm list ajv` looks like.

```
webpack-userscript@3.0.0-alpha.1 D:\Programming\nodejs\webpack-tampermonkey
├─┬ @microsoft/tsdoc-config@0.15.2
│ └── ajv@6.12.6
├── ajv@8.6.2
├─┬ eslint@7.31.0
│ ├─┬ @eslint/eslintrc@0.4.3
│ │ └── ajv@6.12.6
│ ├── ajv@6.12.6
│ └─┬ table@6.7.1
│   └── ajv@8.6.2 deduped
├─┬ gitmoji-cli@4.1.0
│ └─┬ conf@10.0.1
│   ├─┬ ajv-formats@2.1.0
│   │ └── ajv@8.6.2 deduped
│   └── ajv@8.6.2 deduped
├─┬ schema-utils@3.1.1
│ │ └── ajv@6.12.6 deduped
│ └── ajv@6.12.6
└─┬ semantic-release@17.4.4
  └─┬ @semantic-release/npm@7.1.3
    └─┬ npm@7.20.1
      └─┬ node-gyp@7.1.2
        └─┬ request@2.88.2
          └─┬ har-validator@5.1.5
            └── ajv@6.12.6
```

The CPU raises about 25% when performing intellisense and drop to 0% after intellisense done. I use keyboard shortcut to trigger it. There is still much CPU and memory available but the intellisense is slow.

---

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.33GB free)|
|Process Argv|--folder-uri file:///d%3A/Programming/nodejs/webpack-tampermonkey --crash-reporter-id a1c09b66-09d4-4443-84a2-b604c0c0e983|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    94	 15732	code main
    1	   291	  3904	   gpu-process
    0	    21	  4520	   crashpad-handler
    0	    36	  7232	   utility
    0	   228	 11400	   window (● UserscriptPlugin.ts - webpack-tampermonkey - Visual Studio Code)
    0	   101	  9696	     extensionHost
    0	    68	  8148	       electron_node tsserver.js 
    0	    92	 11484	       "C:\Users\momocow\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\momocow\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=9696
   27	   204	 12644	       electron_node tsserver.js 
    0	    56	 16944	         electron_node typingsInstaller.js typesMap.js 
    0	    56	 13808	     searchService
    0	    15	 15344	     watcherService 
    0	     5	 15636	       console-window-host (Windows internal process)
    0	    76	 15712	   shared-process
    0	    61	  8408	     ptyHost
    0	     6	 15460	       console-window-host (Windows internal process)
    0	    51	 15540	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    80	 17352	   window (問題回報程式)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● UserscriptPlugin.ts - webpack-tampermonkey - Visual Studio Code)
|    Folder (webpack-tampermonkey): 59 files
|      File types: ts(26) json(8) js(4) yml(2) md(2) eslintignore(1)
|                  gitignore(1)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hant|MS-|1.58.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306cf:30341832
bridge0708:30335490

```

</details>

**Comment by armanio123** [comment]
This is issue is the same as in #44851, which I'm still looking into. For now as a work around you can modify the file `node_modules/ajv/dist/types/json-schema.d.ts` to use named types as shown on gist: https://gist.github.com/armanio123/95a33f9ad3286a7d78590eb11af293c4
