### ISSUE TITLE
TS Server seems to momentarily get out of sync with VS Code edits

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#45320]
# Bug Report

### 🔎 Search Terms

- vs code
- update opened
- provideInlayHints
- inlay hints

### 🕗 Version & Regression Information

Tested in 4.4.0-dev.20210802

### 🐛 Bug

Not 100% reproducible but I've attached the logs from the following repo:

1. Enable parameter hints
1. In the VS Code codebase, open https://github.com/microsoft/vscode/blob/b2142b93e0a0fb37f0a00a46a8474daea2ec8a0f/extensions/markdown-math/notebook/katex.ts#L1
2. Go to the end of the very first line
3. Quickly type `123`

I believe that after typing `3`, the parameter hints and semantic highlighting all shifted left. Here is the log from this: 
[corrupt.log](https://github.com/microsoft/TypeScript/files/6928723/corrupt.log)

![Screen Shot 2021-08-03 at 10 03 50 PM](https://user-images.githubusercontent.com/12821956/128124899-ff823a64-5f31-44c0-9a94-09cb1aa4005b.png)

This may very well be a VS Code issue but I need help looking through the logs to figure out what is going on

**Comment by mjbvz** [comment]
Looking through the logs, here are the relevant `provideInlayHintCalls`:

```
// type 1:     {"seq":0,"type":"response","command":"provideInlayHints","request_seq":8,"success":true,"body":[{"text":"searchValue:","position":{"line":7,"offset":43},"kind":"Parameter","whitespaceAfter":true},{"text":"replaceValue:","position":{"line":7,"offset":56},"kind":"Parameter","whitespaceAfter":true},{"text":"id:","position":{"line":12,"offset":51},"kind":"Parameter","whitespaceAfter":true},{"text":"message:","position":{"line":14,"offset":19},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":18,"offset":38},"kind":"Parameter","whitespaceAfter":true},{"text":"...tokens:","position":{"line":20,"offset":21},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":27,"offset":42},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":32,"offset":39},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":40,"offset":47},"kind":"Parameter","whitespaceAfter":true},{"text":"...tokens:","position":{"line":41,"offset":30},"kind":"Parameter","whitespaceAfter":true},{"text":"id:","position":{"line":46,"offset":24},"kind":"Parameter","whitespaceAfter":true}]}
type 2: {"seq":0,"type":"response","command":"provideInlayHints","request_seq":11,"success":true,"body":[{"text":"searchValue:","position":{"line":7,"offset":43},"kind":"Parameter","whitespaceAfter":true},{"text":"replaceValue:","position":{"line":7,"offset":56},"kind":"Parameter","whitespaceAfter":true},{"text":"id:","position":{"line":12,"offset":51},"kind":"Parameter","whitespaceAfter":true},{"text":"message:","position":{"line":14,"offset":19},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":18,"offset":38},"kind":"Parameter","whitespaceAfter":true},{"text":"...tokens:","position":{"line":20,"offset":21},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":27,"offset":42},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":32,"offset":39},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":40,"offset":47},"kind":"Parameter","whitespaceAfter":true},{"text":"...tokens:","position":{"line":41,"offset":30},"kind":"Parameter","whitespaceAfter":true},{"text":"id:","position":{"line":46,"offset":24},"kind":"Parameter","whitespaceAfter":true}]}
type 3: {"seq":0,"type":"response","command":"provideInlayHints","request_seq":13,"success":true,"body":[{"text":"searchValue:","position":{"line":7,"offset":42},"kind":"Parameter","whitespaceAfter":true},{"text":"replaceValue:","position":{"line":7,"offset":55},"kind":"Parameter","whitespaceAfter":true},{"text":"id:","position":{"line":12,"offset":50},"kind":"Parameter","whitespaceAfter":true},{"text":"message:","position":{"line":14,"offset":18},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":18,"offset":37},"kind":"Parameter","whitespaceAfter":true},{"text":"...tokens:","position":{"line":20,"offset":20},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":27,"offset":41},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":32,"offset":38},"kind":"Parameter","whitespaceAfter":true},{"text":"tagName:","position":{"line":40,"offset":46},"kind":"Parameter","whitespaceAfter":true},{"text":"...tokens:","position":{"line":41,"offset":29},"kind":"Parameter","whitespaceAfter":true},{"text":"id:","position":{"line":46,"offset":23},"kind":"Parameter","whitespaceAfter":true}]}
```

**Comment by mjbvz** [comment]
Possibly related to https://github.com/microsoft/vscode/issues/129870

Duplicate on VS Code side https://github.com/microsoft/vscode/issues/129637

**Comment by Kingwl** [comment]
After review some code again. Seems the inlay hints does nothing different with other features.

Is that only affect inlay hints？Or it's a generic issue with all features. And it's very obvious for inlay hints.

**Comment by Kingwl** [comment]
It's seems a generic issues rather than only inlay hints and semantic highlight。

**Comment by andrewbranch** [comment]
I have no guesses as to what could be causing this, but I’m guessing you might be able to witness the bad state in TS Server by looking at a `scriptInfo.textStorage.getLineMap()`, which hopefully might be able to lead you backwards to the root cause.

**Comment by rebornix** [comment]
I'm currently seeing this constantly while typing comments

![recording (18)](https://user-images.githubusercontent.com/876920/128556752-8b09a3bd-950b-4c9e-bb42-69a570968d2b.gif)

**Comment by sheetalkamat** [comment]
This would happen if LS and server go out of sync and ls operation was invoked without synchronized data from project …

**Comment by DanielRosenwasser** [comment]
👀

https://github.com/microsoft/TypeScript/blob/5e496d52e1bb2b937f5492991cfcd0c81b8b7ba1/src/server/session.ts#L1456

**Comment by DanielRosenwasser** [comment]
I don't entirely know if that's the cause, since , but `ensureSynchronized` will certainly not be `true` meaning that at the very least, there are possibly other cross-file issues with inlay hints.

**Comment by weswigham** [comment]
This doesn't just affect inlay hints (though they're the most noticeable when they move even a little); classification spans are also shifted:

![image](https://user-images.githubusercontent.com/2932786/128786415-8abb2584-b6c0-4d27-a936-4e7e23f196b4.png)

Indeed, if you type fast outside a comment, you find that even diagnostics are out of sync (and not just the spans, but the errors reported have old content!):

![image](https://user-images.githubusercontent.com/2932786/128786815-cf2def24-e9bb-4eba-9b7b-bc32cdb7bbcc.png)

It's definitely a general synchronization issue.

**Comment by DanielRosenwasser** [comment]
I've been working with @sandersn and neither he nor I can reproduce the issue anymore. @weswigham if you've be able to get a consistent repro, that's great.

**Comment by weswigham** [comment]
"consistent" is not a word I would use. I essentially have to destroy my keyboard to press enough buttons fast enough to trigger the issue.

**Comment by weswigham** [comment]
....Welp, you've jinxed it - I restarted by insiders editor to enable tsserver debugging again and now I can't repro it no matter how fast I type.

**Comment by DanielRosenwasser** [comment]
Here's what I did to just get it again.

1. Open up the vscode folder, open up the katex file, wait for the LS to load
2. Open up a new untitled file, switch its language to TypeScript
3. insert

   ```ts
   function foo() {
       return bar();
   }
   
   function bar() {
       return 100;
   }
   ```
4. Add `export ` right before `function bar`

**Comment by DanielRosenwasser** [comment]
Sounds like this is hard to repro, so I'll try to give as much detail as I can for something that is actually showing up for me:

* Root folder is `C:\Users\USERNAME\scratch\example`.
* Current options are
   ```json5
   "editor.inlayHints.enabled": true,
   "typescript.inlayHints.parameterTypes.enabled": true,
   "typescript.inlayHints.functionLikeReturnTypes.enabled": true,
   ```

[example.zip](https://github.com/microsoft/TypeScript/files/6958048/example.zip)

Create an untitled file, insert the following.

```ts
function foo() {
    return bar();
}

function bar() {
    return 100;
}
```

Swap back to `foo.ts`, reload the editor, and wait for inlay parameter hints.

Now switch back to the untitled buffer, wait for inlay hints, and insert the `export ` before `function bar`. Note that it's not alwyas just about typing as fast as possible - it seems like there's often a need for a very quick stutter.

https://user-images.githubusercontent.com/9 72891/128790012-b371e319-8579-469e-ab18-2245841c7cc0.mp4

**Comment by DanielRosenwasser** [comment]
I've put up https://github.com/microsoft/TypeScript/pull/45392 for people to play with, it seems to fix the issue and it seems "obviously correct" even if it doesn't. I haven't yet tried to put a test that fails without the change though.

**Comment by weswigham** [comment]
#45394 has a test and the explanation for why that fix works~
