### ISSUE TITLE
Type is cannot satisfy A and cannot satisfy B but satisfies A | B

### ISSUE THREAD

**Issue by jisaacks** [microsoft/TypeScript#45339]
### 🕗 Version & Regression Information

v4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UAKBDATsAligNgHgG8oAoKKAMwHtKAuKAOwFcBbAIwjVKlfToGdgaTPQDmxAL4A+YsVCQoAIQTJ0WXIS5VaDFu05lKwABYd+g4WKky50AMLK4AMkVRnRACTCTQ4HQBErH5Q4jIAxpT0AlAodHCIBJrUdADMADRcht50AOThlDjZqVAA9MXZmRzZUAAmlBB8DIZQEAAemFHCUDYSYRFRrHT28SXFUJ703pjAUO1QzO18FonaaRnGplC51AXpIcThkdOhsVAAPlBDUESlUADyANJQAPwvT8sp6QbraDl5OxJAA)

### 💻 Code

```ts
type A = Partial<{ 
  foo: number
  bar: string
}>

type B = Partial<{
  foo: number
  other: string
}>

type C = A & B & { $inherit: "b" }

const a: A = {
  foo: 3,
  other: 'cool', //'other' does not exist in type
}

const b: C = { // $inherit is missing
  foo: 3,
  other: 'cool',
}

const c: A | C = { // OK ????
  foo: 3,
  other: 'cool',
}
```

### 🙁 Actual behavior

`c` is OK.

### 🙂 Expected behavior

If the same structure cannot satisfy A and cannot satisfy B it should be logical to assumed that it cannot satisfy A | B but here it does.

I would expect that since I have included `other` it cannot be `A` and since I have not included `$inherit` it cannot be `C` so I would expect this to fail. I would expect that I could only make `const c` ok by either removing `other: cool` or by adding `$inherit: "b"`

**Comment by RyanCavanaugh** [comment]
Excess property checking (`other` in `a`) is a heuristic that tries to, without false positives, identify properties that "don't belong there". It is not a facet of the type system per se -- excess properties are OK in the subtype relationship. As such, it sometimes will issue fewer errors in the presence of different hints.

What we found in real-world code is that there were many cases where people wrote unions that didn't capture the full extent of allowed properties, so excess property checking allows excess properties as long as a matching property name is found anywhere in the target union.

**Comment by jisaacks** [comment]
@RyanCavanaugh this seems weird. I mean That is how I would expect `Partial<A & C>` to work. Not how I would expect `A | C` to work.

It just seems illogical that by design X != A, X != C, X == A | B

So if this is by design, then is there a way to actually achieve this, so that a type MUST satisfy one of the union types NOT a mishmash of parts of different types in the union?

**Comment by RyanCavanaugh** [comment]
> So if this is by design, then is there a way to actually achieve this, so that a type MUST satisfy one of the union types NOT a mishmash of parts of different types in the union?
```ts
const c: A | C = { // OK!
  foo: 3,
  other: 'cool',
}
```
The initialization here *is* a valid `A`; you could equally write
```ts
const d = {
  foo: 3,
  other: 'cool',
};
const c: A | C = d;
```
You might be looking for #12936 or #14094, depending

**Comment by jisaacks** [comment]
@RyanCavanaugh but that is bypassing the object literal.

I could also do:

```ts
const d = {
  foo: 3,
  other: 'cool',
};
const a: A = d;
```

even though I cannot do:

```ts
const a: A = {
  foo: 3,
  other: 'cool', //'other' does not exist in type
}
```

I was under the impression that extra properties were OK when using a variable but NOT OK when using an object literal.

So it seems like you can bypass the object literal restriction on excess properties as long as the type is a union?

**Comment by MartinJohns** [comment]
> So it seems like you can bypass the object literal restriction on excess properties as long as the type is a union?

See #20863.
