### ISSUE TITLE
Keywords should not be valid identifiers 

### ISSUE THREAD

**Issue by avestura** [microsoft/TypeScript#45332]
# Bug Report

### 🔎 Search Terms

- keyword valid identifier
- keyword identifier
- keyword names

### 🕗 Version & Regression Information

TypeScript v4.3.5, and nightly v4.4.0-dev.20210805

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about keywords.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.4.0-dev.20210805#code/C4TwDgpgBKlQvFAjAKFtAMkhNwQNwpp5QCWAdgGYQBOOATMXBvThdTYU9BcDRQGdSAYxwBmblAxi25PoJH4gA)

### 💻 Code

Sample 1:
```ts
type type = 1 // <- TS sees no problem here
type L1 = type; // <- Compiles correctly
```
Sample 2:
```ts
type infer = 2 // <- TS sees no problem here
type L2 = infer // <- Error
```

Sample 3:
```ts
type intrinsic = 3 // <- TS sees no problem here
type L3 = intrinsic; // <- Error: The 'intrinsic' keyword can only be used to declare compiler provided intrinsic types.
```

### 🙁 Actual behavior

It is possible to define types with reserved keywords as the type name, making it impossible to use the type later.

### 🙂 Expected behavior

It should not be able to use reserved keywords as type names.

**Comment by RyanCavanaugh** [comment]
There are plenty of cases where you can legally refer to these types. For example, if they are exported out of a module or namespace:
```ts
namespace N {
    export type infer = 2 // <- TS sees no problem here
}
type M = N.infer;
```

**Comment by avestura** [comment]
Fair enough.
