### ISSUE TITLE
Generic object can be widened unsafely

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#45335]
# Bug Report

### 💻 Code

```ts
const obj = { prop: 5, field: '' }


// Expected error: other properties of 'data' can have types of not a number
// Currently: no error
const func1 = <T extends { prop: number }>(data: T): Record<string, number> => data

// No error
const result1 = func1(obj)

// Got: number | undefined
// Real value: string
const field  = result1.field


// Type checker must make us rewrite func1 into
const func2 = <T extends { prop: number } & Record<string, number>>(data: T): Record<string, number> => data

// Error as expected: Type '{ prop: number; field: string; }' is not assignable to type 'Record<string, number>'.
const result2 = func2(obj)
```

### 🙁 Actual behavior

`T extends { prop: number }` is assignable to `Record<string, number>`

### 🙂 Expected behavior

`T extends { prop: number }` is not assignable to `Record<string, number>`

**Comment by RyanCavanaugh** [comment]
`Record<string, number>` has the same soundness hole as optional properties. I don't see how we could change this without breaking a huge amount of working code.

**Comment by awerlogus** [comment]
How about adding some new tsconfig option?

**Comment by fatcerberus** [comment]
I don’t think such an option would be feasible.  `T extends X` means precisely “T is assignable to X”.  If `{ prop: number }` were not assignable to `Record<string, number>` then you also couldn’t do this:

```ts
const rec: Record<string, number> = {
    prop: 42
};
```

Or for that matter, even initializing it with `{}` would have to be an error (because every object is assignable to `{}`).

**Comment by awerlogus** [comment]
@fatcerberus it's incorrect to say that if `A` is assignable to `B` and `B` is assignable to `C`, then `A` is always assignable to `C`.

Counterexample:
`A`: `{ a: number, b: string }`
`B`: `{ a: number }`
`C`: `Record<string, number>`

**Comment by fatcerberus** [comment]
As Ryan pointed out, the same kind of unsoundness exists for all types with optional properties, so this isn’t unique to `Record`.

**Comment by awerlogus** [comment]
Yes, and this doesn't mean that we can leave everything as it is because of it. It just means that the problem, needs to be solved, simply takes on a larger outline.

**Comment by awerlogus** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/39915
