### ISSUE TITLE
Object.freeze should infer narrow types on immediate properties 

### ISSUE THREAD

**Issue by dwjohnston** [microsoft/TypeScript#45341]
# Bug Report

### 🔎 Search Terms

Object.freeze narrow string 

### 🕗 Version & Regression Information

Apologies, this doesn't look like a regression, but I couldn't find this in any of the FAQs.  If this is a duplicate or a 'won't do' can someone point me to it? 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gWwgeQEYCsIGNhQLxQDeAUFGVAK4DOEATgCrgQBcUARAIYAmCAlgHZsoAH3bU6bANxRiAX2IKAZhX45ecfpRpUAgvzSYcACjgZW8JAezAAlEQXyFCrBqq5gACxQZrAVnxQVjgAdIq0EBAAXhBGJORadIyQrJw8AmxyNtIK4rr6Psae3obAvllQAPQVUDq0AOYUSPy4cIpQoJBQAOQAShDcGgA2IAA8hAkMTKxutAJ10rIAfF1QvFRQ-HC4HFRUvHX8HKiD0MBwUGActBxIwHRQre1M3RbF1l3BCkA)

### 💻 Code

```typescript
type SomeObject = {
    userType: "admin" | "user"; 
}


function usesAnObject(obj: SomeObject) {

}




const theObject5 = Object.freeze({
    userType: "admin"
}); 

usesAnObject(theObject5); // Argument of type 'Readonly<{ userType: string; }>' is not assignable to parameter of type 'SomeObject'.


```

### 🙁 Actual behavior

In this code the type of the `userType` property is widened to `string`. 

### 🙂 Expected behavior

The type should be kept as the narrower `"admin"` as it is not possible for that property to be reassigned.

**Comment by fatcerberus** [comment]
Use `as const`. The object literal is getting widened *before* `Object.freeze()` sees it.

**Comment by RyanCavanaugh** [comment]
We don't have hardcoded logic specifically for `Object.freeze`; it's just another function.

**Comment by jcalz** [comment]
If we had #30680 then the signature to `Object.freeze()` could use it; without it, there are dirty tricks that could work, but I don't think anyone wants to see them in the standard TypeScript library.
