### ISSUE TITLE
types from imported json files aren't narrowed when assigned to a variable with a type annotation

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#45358]
# Bug Report

### 🔎 Search Terms

json import narrow

### 🕗 Version & Regression Information

4.5.0-dev.20210807

### ⏯ Playground Link
n/a
#### `test.json`
```json
{
  "foo": "bar"
}
```
#### `main.ts`
```ts
interface Foo {
    foo: 'bar'
}

(async () => {
    //TS2322: Type '{ foo: string; }' is not assignable to type 'Foo'.
    //  Types of property 'foo' are incompatible.
    //      Type 'string' is not assignable to type '"bar"'.
    const foo: Foo = (await import('./test.json')).default
})()

//no error, object type is correctly narrowed to fit the type annotation
const foo: Foo = {
    foo: 'bar'
}
```
### 🙁 Actual behavior

the type of the object imported from the json file is `{foo: string}`, which isn't assignable to `{foo: 'bar'}`

### 🙂 Expected behavior

the type of the object imported from the json file is narrowed to fit the type annotation

**Comment by MartinJohns** [comment]
You want #32063. For now use a type assertion.
