### ISSUE TITLE
Add a config to control no import or export define file types only work in local, not pollute global types.

### ISSUE THREAD

**Issue by zenHeart** [microsoft/TypeScript#45353]
# Suggestion

## 🔍 Search Terms

scoped module config

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X ] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Add a config to control file type work in global scope or module scope.

## 📃 Motivating Example
In official docs [module](https://www.typescriptlang.org/docs/handbook/modules.html) 

> a file without any top-level import or export declarations is treated as a script whose contents are available in the global scope (and therefore to modules as well).

This means not use export or import in the file, the file's type will work globally. Sometimes we need no import or export file types just work in the current file don't pollute the environment globally. For example:

1.  the tests file, we just declare some local test functions, it didn't rely any dependency, doesn't have any export or import define, but this make types in this file will pollute global. so I need to use like `export {}` to hack this. 
2. When writing some docs, I need to create many example files, these example file types just work locally, some example file doesn't have any export or import define, this also pollute globally. To avoid this situation I need to use some like `type Fooxx` to avoid name collesion or use like `export {}` to hack this. 

I want there is some way to control which file or directory type will be not working globally. some config like 

```js
{
 // file has no import or export define, type only work in local
 "moduleScopeFiles" : [ "a.ts", "test/foo*.ts" ]
}
```

I found there is some config that can control umd export work in global [allowUmdGlobalAccess](https://www.typescriptlang.org/tsconfig#allowUmdGlobalAccess), So I think this feature will also can control by config.

## 💻 Use Cases
see previous example

**Comment by RyanCavanaugh** [comment]
Tracked at #18232
