### ISSUE TITLE
Constraint fallback during generic type inference

### ISSUE THREAD

**Issue by h-a-n-a** [microsoft/TypeScript#45363]
# Bug Report

### 🔎 Search Terms

constraint fallback, generics

### 🕗 Version & Regression Information

Tried every version after 4.x

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0#code/JYOwLgpgTgZghgYwgAgLJwA4DU4BsCuKA3gFDLIDWEAngFzIDOYUoA5gDRnIBueh9TFiFYkAviRKhIsRCgAiEALYB7dNj4oIAD0ggAJgzSYcBYuJIJlIJskXGNhgLzIA2l1LlyVOsgDkMZWVfTk8eDXpfADFA4K5REOQPT28IgCM4KFjQ3lMIgCEMrORxAF1kOENLazAAbgkwagwUSOBcaQBBKCg4ajzqAGkaAB4AFWRtXQNkKAg4PStcanKQahcS9mQABXGdCH1DEZcQfEVU6BKXX29fEoA+ZGcucjGJvamZuYWll1AYaGQWlAmBsAHRg37-ADyYAAFtAGGUAPxPTyAmyvfaJSg0ejbUTIRHIFGhFxosCgsEtNrQTrdXoDYbQuFAjabW5lejEgGtDpdHp9QbUIZM+Gs+6ckklCRVGysCBgNQmQgPZCjHaTQwfeYgRbLVbrLbqt4HI4nM5QC5XGg3W4ACjwuHoIw2OX4WwAlA97g6QTBQHpbbbFO76IpkMBDFTeXSBcNnVtbi4AAxlRz3RQg7wPRzOV0Qd11CxWGxwFVyhX2UxByuEBgbXzpTIFoA)

### 💻 Code

```ts
interface MapValue {
  key: string,
  value: string
}

interface DemoMapValue extends MapValue {}

const mapValues = [
  {
    key: 'foo',
    value: 'Foo',
  },
  {
    key: 'bar',
    value: 'Bar',
  }
] as const;

type FilterArrayByKey<T extends readonly any[], P extends T[number]['key']> = 
    T extends readonly [infer First, ...infer Others] ?
      First extends { key: P } ? 
        [First, ...FilterArrayByKey<Others, P>] : 
      FilterArrayByKey<Others, P> : 
    []

const getMapValue = <T extends readonly any[], P extends T[number]['key']>(all: T, value: P) => all.find((m): m is FilterArrayByKey<T, P>[0] => m.key === value);

// we lost 'bar' here and fallback to 'foo' | 'bar'
const a = getMapValue(mapValues, 'bar');
```

### 🙁 Actual behavior

`'bar'` fallbacks to `'foo'|'bar'`, if we use `P extends string` the constraint is working as intended

### 🙂 Expected behavior

`'bar'` should not be widened during the evaluation procedure

**Comment by RyanCavanaugh** [comment]
I'm seeing `a` inferred as `"foo"` here, which is totally wrong. Not sure what's going on there.

That said, I'm not sure if we'd necessarily establish a literal context here automatically. You could add this and it works as expected:
```ts
const getMapValue = <T extends readonly any[], P extends (string | number) & T[number]['key']>(all: T, value: P) => all.find((m): m is FilterArrayByKey<T, P>[0] => m.key === value);
```

**Comment by h-a-n-a** [comment]
> I'm seeing `a` inferred as `"foo"` here, which is totally wrong. Not sure what's going on there.
> 
> That said, I'm not sure if we'd necessarily establish a literal context here automatically. You could add this and it works as expected:
> 
> ```ts
> const getMapValue = <T extends readonly any[], P extends (string | number) & T[number]['key']>(all: T, value: P) => all.find((m): m is FilterArrayByKey<T, P>[0] => m.key === value);
> ```

Thanks for the quick reply! Would you mind making a more detailed explanation on this change?

**Comment by RyanCavanaugh** [comment]
String literals (in expression space) generally get inferred to literal types if they are contextually typed by a string literal union or by a generic type parameter constrained to a union containing `string`. IOW
```ts
declare function fn1<T>(id: T): T;
declare function fn2<T extends string | number>(id: T): T;

let a = fn1("hello"); // a: string
let b = fn2("hello"); // b: "hello"
```
Technically `a` produces a *widening* version of `"hello"`` and `b` produces a *non-widening* version but you should think of the widened result when reasoning about generic inference.

**Comment by andrewbranch** [comment]
> I'm seeing `a` inferred as `"foo"` here, which is totally wrong. Not sure what's going on there.

This tripped me up for about 20 minutes of playing with it and then I realized the type predicate on `find` is written as

```ts
m is FilterArrayByKey<T, P>[0]
```

You’ll _only_ ever pull the first element out of the filtered tuple type here, but if `value` is a union type like `"foo" | "bar"`, what you’re actually testing is whether `m` is _any_ of the elements in the filtered tuple. The type predicate should be

```ts
m is FilterArrayByKey<T, P>[number]
```

and then it works properly with unions:

```
const a = getMapValue(mapValues, undefined! as 'foo' | 'bar');
// {
//   readonly key: "foo";
//   readonly value: "Foo";
// } | {
//   readonly key: "bar";
//   readonly value: "Bar";
// } | undefined

const b = getMapValue(mapValues, undefined! as 'foo');
// {
//   readonly key: "foo";
//   readonly value: "Foo";
// } | undefined

const c = getMapValue(mapValues, undefined! as 'bar');
// {
//   readonly key: "bar";
//   readonly value: "Bar";
// } | undefined
```

Of course, this is moot when you consider the root of the confusion that Ryan already cleared up. The unexpected thing that exposed the problem with the type was that in `getMapValue(mapValues, "bar")`, `P` was being instantiated with `"foo" | "bar"` instead of `"bar"`. But once you end up with a union for `P`, whether by accident or on purpose, the flaw in the type annotation makes things even more confusing.
