### ISSUE TITLE
TypeScript making too many assumptions about object property types

### ISSUE THREAD

**Issue by Aquilosion** [microsoft/TypeScript#45366]
# Bug Report

TypeScript assumes that, if you set an object's property to some value, it will remain that value until at least the end of the scope. This is erroneous, because:

- The object might have a custom getter which doesn't reflect the value set in the setter
- The object's properties might be changed by another function called in the scope

For former issue I grant is rarely a good idea anyway, but the latter issue is more problematic:

```
const object = { property: true }; // Type is { property: boolean }

object.property = false; // Type is now { property: false }

function setObjectPropertyTrue(object: { property: boolean }) {
    object.property = true;
}

setObjectPropertyTrue(object);

if (object.property == true) { // ← tsc: "This condition will always return false"
    console.log("Object property is true!");
}
```

Here, I manually set `object.property` to `false`. I later call a function, passing in that object, where its property is changed. I later compare the property's value to `true`, which TypeScript thinks will always fail. Of course I can think of several ways around this issue, but they all seem very hacky or unnecessary. A more functional code style would also help, but I don't think TypeScript should be assuming it.

IMO, TypeScript shouldn't change its assumptions about an object property after it has been explicitly set, as there are too many scenarios in which it'll get it wrong. However, this seems like an oddly trivial example that surely other people have discussed in the past and it was decided that the current behaviour was acceptable, but I was unable to find anything relevant. It would be good to see the justification for this feature, anyway, if there is one written somewhere.

### 🔎 Search Terms

incorrect type assumption object properties set

### 🕗 Version & Regression Information

- TypeScript 2.0.3 was the first version which complains about the above snippet
- Tested on 4.5.0-dev.20210808 which also complains

### 🙁 Actual behavior

Setting an object's property makes TypeScript assume that the property has that value until the end of the scope.

### 🙂 Expected behavior

Setting an object's property doesn't affect TypeScript's assumptions of the value of that property.

**Comment by MartinJohns** [comment]
Another duplicate of #9998.

**Comment by Aquilosion** [comment]
> Another duplicate of #9998.

I assumed this would be reported already but couldn't find it. Thanks!
