### ISSUE TITLE
unknown inference in optional chaining ?

### ISSUE THREAD

**Issue by eczn** [microsoft/TypeScript#45378]
# Suggestion

``` ts
interface Student { name: string };

// current: Error thrown when using i?.name because ts don't know what the keyof i will to be
const isStudent = (i: unknown): i is Student => typeof i?.name === 'string';
```

but in fact, optional chaining is designed for safety get the value of var, so an optional chaining for unknown types should be unknown too:

``` ts
declare const i1: unknown;

const i2 = i1?.aaa; // optional chaining for unknown i1
type T = typeof i2; // T should be unknown too
```

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## One: for type predicate, avoiding the usage of any

``` ts
interface File { fileId: string; }
interface Folder { folderId: string; }
const isFile = (i: unknown): i is File => typeof i?.fileId === 'string';
const isFolder = (i: unknown): i is Folder => typeof i?.folderId === 'string';

// better than any:
const isFile = (i: any): i is File => typeof i?.fileId === 'string';
```

## Two: a better unknown types processing experience

``` tsx
const getRawUser = (id: string): Promise<unknown> => fetch(`/api/user/${id}`).then(d => d.json());

const eczn = await getRawUser(`eczn`);
const maybeAvatar = eczn?.profile?.avatar; // <<<< unknown typed maybeAvatar
// narrowing for `maybeAvatar: unknown`
if (typeof maybeAvatar === 'string') <img src={maybeAvatar} />
```

**Comment by RyanCavanaugh** [comment]
Duplicate #37700
