### ISSUE TITLE
Allow multiple unused parameters to be named _

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#45370]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When multiple parameters are unused in a function, allow them to all be named `_` .

## 📃 Motivating Example

Sometimes it's reasonable to have multiple unused parameters in a function. Function parameter / API designs sometimes end up using multiple parameters with some being unnecessary, instead of destructuring a single object with optional members.

TypeScript already allows prefixing parameter names with `_` to exclude them from `noUnusedParameters`. Allowing parameters specifically named `_` be excluded from duplicate identifier checking would make declarations in this case less.

```ts
type Logger = (first: string, second: string, third: string) => void;

// (imagine other loggers do use first and second)

let logsThird: Logger = (_, _, third) => {
                      // ~  ~
                      // Unused parameters
  console.log(third);
};
```

## 💻 Use Cases

Right now they generally have to be given unique names, even though they're not used. Common workarounds for needing unique unused parameters include:
* Naming them normally after a `_` prefix: above, `= (_first, _second, third) => {`.
    * Downside: parameter names can be long despite being unused.
    * Downside: parameter names can over time mismatch with their declared name.
* Giving them increasingly long names: above, `= (_, __, third) => {`.
    * Downside: can be irksome to keep track of the lengths

JavaScript already allows function parameters to share names; it's a TypeScript-specific feature to disallow duplicate parameter identifiers. Normally that kind of overlap (shadowing?) would be a problem because you can't access earlier parameters. That problem is not relevant if they're all unused.

Related to, but not the same as, #29202's `unused` type suggestion. `_` parameters of functions passed to locations with existing type location (e.g. `[].map((_) => ...)`) often don't need explicit type annotations.

**Comment by nmain** [comment]
> JavaScript already allows function parameters to share names

JavaScript does not allow this in strict mode, and you will see a JS error if you try your example in the playground:  https://www.typescriptlang.org/play?#code/C4TwDgpgBAMg9gcwRATlAvFAFAMwJYoDOwAXFMSngHYIA05EAxnFQCZkXV1TAAWB7csEo0AlBgB8UAG5w8rANwAoJQHpV2PAFsAhgmrQ4fVFAA2iZESis4UAK6Fo+IsCg62DZm1ErTEV+YIhAAq-CiC8EgmmFgA+vTxPGGs4uhSAN5KUNk5uXn5UOpQAH7ZxVkFlflFAKpUDhCsUGA6KDpa-qiEFV6EcH4AdIFYfAKiygC+CkA

**Comment by JoshuaKGoldberg** [comment]
Well, dangit! TIL. Thank you @nmain!

Pity. Hopefully someone some day will propose this change to the ES spec.
