### ISSUE TITLE
Union type does not get narrowed down by passing it as a key to a mapped type

### ISSUE THREAD

**Issue by vostrnad** [microsoft/TypeScript#45373]
# Bug Report

### 🔎 Search Terms

union narrow object key mapped type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about **Type System Behavior**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEGUEsFsAcBsCmpEA8CGckC4BQuAXAT1mQBlECDEAnUAXlAHIBBJ0AH2YCEn8ATRAGN46GsiEB7AHYBnAqEkAjAFbZQAb1ABtAAqhI00BSq0Auuv0BfXIJFiJM+aCSma6k9Rr4QoACrgoLIAFpIArvD8oOJSAObSkABeyATB6AquXgayoOiyspDx6EpIuQoA1ohELpReuMoq2pnmDDVuoL60NJLeuL4soNA9jliQQumIUejSUUPi0Yjo8JDyYygYWIh4hCTIAKIAbojSBAAi6egAsuiwrRq4oBAENIaxAGpLYVuaoAef3-IXtJYqAbI8AHJhaBKWgfeBfdRaP7w77SKEwug2Gw7UigQ7HAjgzDIRiVIiSABmeKOJ3OBCuNx8YHQoDCCRkiipBAA7pJQPxIBSKbQCaBYOgiPBJOgosRSLIcchdBKpTK7g8dHsDEZ8ScidBEBYfogaQR1HsANz8i7m010hmwbR7Myg3BWJ2m-WGgTCUTzKRyBQxRCQI78RGa7XUgleo26s4Xa6O52uux+xyBsUq6Xh0DKyU5pn+QIhcKRBZxBLJUCpdJZgsygB0-Au2Vy+UK0mKpTrZPrqv4jZNBNwwdDk204obg+HJxdjCnA+brc6NG63iAA)

### 💻 Code

Simple example:

```ts
type Letter = 'A' | 'B'

declare const obj: { [P in Letter]: P }
declare const letter: Letter

// TS should recognize that letter is assignable at key letter
obj[letter] = letter // error
```

A more complicated and more realistic example:

```ts
type EventDataMap = {
  StringValue: { value: string }
  NumberValue: { value: number }
}

type EventName = keyof EventDataMap

// a union of two different payload types
type Payload = {
  [E in EventName]: { event: E; data: EventDataMap[E] }
}[EventName]

declare const received: { [E in EventName]: EventDataMap[E] }
declare const payload: Payload

// TS should recognize that payload.data is assignable at key payload.event
received[payload.event] = payload.data // error
```

### 🙁 Actual behavior

TypeScript reports errors in the above code.

### 🙂 Expected behavior

TypeScript should not report errors in the above code.

**Comment by jcalz** [comment]
Looks like #30581 to me.

**Comment by vostrnad** [comment]
> Looks like #30581 to me.

Thanks, correlated union types seems like exactly what I need. The use case of correlating the union type with a mapped type isn't directly discussed in the PR, but I saw a link to StackOverflow in there dealing with exactly that, so I'm assuming this is a known thing.

Closing as duplicate.
