### ISSUE TITLE
Feature Request: Quoting Expressions

### ISSUE THREAD

**Issue by AdamSobieski** [microsoft/TypeScript#45379]
# Suggestion

Hello. I would like to share a recent development in the JavaScript language design forum with the TypeScript language community.

https://es.discourse.group/t/feature-request-quoting-expressions/862

The proposed language feature involves quoting JavaScript syntax into abstract syntax trees or expression trees by means of something like:
```typescript
quote(1 + 1)
```
or
```typescript
quote((x, y) => x + y + z.value);
```

Also relevant to TypeScript, we can envision _typed quoting_, where a quoting syntax (whatever it might eventually resemble) could be described as returning content of type `Expression` or `LambdaExpression<T>`.

That is, something like the following should be possible:
```typescript
function foo(lambda: LambdaExpression<(x:number) => number>)
{
   // ...
   let compiled: (x:number) => number = lambda.compile();
   // ...
}

foo(quote((x:number) => x + 1));
foo(quote(function (x: number) { return x + 1; }));
```

I would like to invite the TypeScript language community to the JavaScript language forum where these ideas are presently being considered and discussed: https://es.discourse.group/t/feature-request-quoting-expressions/862 . Thank you.

## 🔍 Search Terms

quote, quoting, abstract syntax trees, expression trees, lambda expressions

**Comment by RyanCavanaugh** [comment]
This would need to go through TC39 first, of course, so we'll meet up with the proposal in that venue should it make it to the formal proposal process.

**Comment by Kingwl** [comment]
I guess you need something like [this](https://github.com/HearTao/ts-creator)?

**Comment by AdamSobieski** [comment]
@RyanCavanaugh, thank you.

@Kingwl, yes, something like [that](https://github.com/HearTao/ts-creator) would be a component of it. A difference is that, with quoting, as opposed to string inputs, runtime objects can be more easily referenced and utilized.

So, for something like:
```typescript
let obj_y = { value: 123 };

let lambda = quote(function (x: number) { return x + obj_y.value; });

let compiled = lambda.compile();

// ...
```
we could visualize something like:
```typescript
let obj_y = { value: 123 };

let x = Expression.parameter('x');
let y = Expression.capture(obj_y);
let y_value = Expression.member(y, 'value');
let add = Expression.addition(x, y_value);
let ret = Expression.return(add);
let lambda = Expression.lambda<(x: number) => number>([x], Expression.block([ret]));

let compiled = lambda.compile();

console.log(compiled(0)); // 123
console.log(compiled(1)); // 124
console.log(compiled(2)); // 125

obj_y.value = 126;

console.log(compiled(0)); // 126
console.log(compiled(1)); // 127
console.log(compiled(2)); // 128
```

though, with a JavaScript `quote`, the above TypeScript `quote` could map to or compile to:
```javascript
let obj_y = { value: 123 };

let lambda = quote(function { return x + obj_y.value; });

let compiled = lambda.compile();

// ...
```

Also, with `quote` syntax, developers could enjoy syntax checking, syntax highlighting, type checking, intellisense, and so forth for quoted content (whatever quoting might eventually syntactically resemble).
