### ISSUE TITLE
Suggestion: "Replace" Utility Type/Inline Operator

### ISSUE THREAD

**Issue by SploxFox** [microsoft/TypeScript#45395]
# Suggestion

## 🔍 Search Terms

override, modify, replace, interface, property, utility type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a utility type `Replace` to standard library:
```
type Replace<TFrom, TReplaceWith> = Omit<TFrom, keyof TReplaceWith> & TReplaceWith;
```
Or inline operator `+` for replace, which is like `&` except properties from the type on the right override existing properties on the type on the left:
```
type T0 = From + ReplaceWith;

// Example:
type A = {
    x: number
    y: number
    z: number
}

type B = A + {
    x: string
}

/*
typeof B: {
    x: string
    y: number
    z: number
}
*/
```

Additionally, interfaces could use `from`, which is similar to `extends` except that it overrides duplicate properties instead of throwing an error:
```
interface A {
    x: number
    y: number
    z: number
}

interface B extends A {
    x: string // Error! string is not assignable to type number
}

interface B from A {
    x: string
}

/*
typeof B: {
    x: string
    y: number
    z: number
}
*/
```

## 📃 Motivating Example & Use Cases

Right now if you want to override a type in an extension like this:
```
type A = {
    x: number
    y: number
    z: number
}

type B = {
    x: string
    // plus all of the other types of A besides x
}
```

You need to do:
```
type B = Omit<A, 'x'> & {
    x: string
}
```
since the intersection operator `&` creates a union out of duplicate types (not what we want) and `extends` on interfaces throws an error. While you can just add this to your code:
```
type Replace<TFrom, TReplaceWith> = Omit<TFrom, keyof TReplaceWith> & TReplaceWith;
```
I don't see why it shouldn't be a part of the standard library, considering that it's a simple add and would be a massive convenience.

**Comment by MartinJohns** [comment]
> I don't see why it shouldn't be a part of the standard library, [,,]

Because https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388:

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.
