### ISSUE TITLE
stricter definition of Object.keys; why not?

### ISSUE THREAD

**Issue by abetaev** [microsoft/TypeScript#45390]
why instead
https://github.com/microsoft/TypeScript/blob/d8e830d132a464ec63fd122ec50b1bb1781d16b7/lib/lib.es5.d.ts#L261
not to have
```typescript
keys<T = Record<string, unknown>>(o: T): (keyof T)[];
```
?
are there any issues with that?

**Comment by jcalz** [comment]
If by "issues" you mean "GitHub issues", yes there are plenty: #30314, #13254. #30228, #28899, #28284, #26901, #30749, #31087, #32321, #34498, #35145, #37495, #44706, etc.  😜

See https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript

**Comment by abetaev** [comment]
my bad, didn't look through closed ones.
thanks for the explanation.
