### ISSUE TITLE
Object.getOwnPropertyNames and Object.getOwnPropertySymbols cannot be used as object keys

### ISSUE THREAD

**Issue by EnderShadow8** [microsoft/TypeScript#45407]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `ESNext`.

## Missing / Incorrect Definition

```ts
Object.getOwnPropertyNames
Object.getOwnPropertySymbols
```

Current definitions:

```ts
{
  getOwnPropertyNames(o: any): string[],
  getOwnPropertySymbols(o: any): symbol[],
}
```

Improved definitions:

```ts
{
  getOwnPropertyNames<T>(o: T): (keyof T & string)[],
  getOwnPropertySymbols<T>(o: T): (keyof T & symbol)[],
}
```

## Sample Code

```ts
const sym = Symbol()
const myObject = {
  foo: 1,
  bar: 2,
  [sym]: 3
}

for(let i of Object.getOwnPropertyNames(myObject)) {
  myObject[i] // Error
}

for(let i of Object.getOwnPropertySymbols(myObject)) {
  myObject[i] // Error
}
```

Currently objects cannot be indexed by the results of Object.getOwnPropertyNames/Object.getOwnPropetySymbols without a type assertion.

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames

**Comment by MartinJohns** [comment]
See #15570 and others.
