### ISSUE TITLE
Difference of Type and Interface in constraint behavior.

### ISSUE THREAD

**Issue by val-o** [microsoft/TypeScript#45403]
# Bug Report

Generics with type arguments under mapped type constraint (e.g. Record<string, string>) differ when closing the type argument with type declared with `type` keyword and interface. 

Suppose I have a generic type with mapped type constraint:
`type A<T extends Record<string, string>> = never;`

And I have two types with the same shape
```
type PersonT = {
    name: string;
}

interface PersonI {
    name: string;
}
```
But when I try to close type `A` with `PersonI` I am getting an error `2345`, which I didn't get using `PersonT`. This may potentially lead to bugs (because there is no check for property existence), because `T extends Record<string, any>` is a popular pattern, which is used when people who don't know the `object` keyword try to make an object constraint.

### 🔎 Search Terms
generic constraint, record constraint

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/C4TwDgpgBAChBOBnA9gOwCpQLxQN4CgoipUBDAWwgC4pFh4BLVAcwG58BfffJ4BAM1IBjaHCRoAknkLEylGnUYt2XfELR0oAE2QBlYAFd+-bFAA8mCAA8+qLYigAlCOvhazipswA0tel4A+AKgAClIadABKbGCCYih1VE1+BggAGy1TUgA6VDQAUSsGOghUYHZ4+AhDeFQoFPStbOBkAFUwSHgAYVJECBDIlW5EzU6UDBoxccwcONkKaigAcjTkNKXONQ1gKDHJSYRxqVmZIjlFlbWN1R19I34QvYxB-FvDY0fDyRegA
)

### 🙁 Actual behavior

TS let me pass type created by `type` keword

### 🙂 Expected behavior

Same behaviors as interface

**Comment by MartinJohns** [comment]
Duplicate of #42825. Used search terms: `interface extends record unknown`

**Comment by val-o** [comment]
@MartinJohns thanks! closing
