### ISSUE TITLE
Extending Object.prototype with map function adversely affects Array.prototype.map type inference

### ISSUE THREAD

**Issue by joshuakb2** [microsoft/TypeScript#45414]
# Bug Report

### 🔎 Search Terms

Object, prototype, Array, map, extend

### 🕗 Version & Regression Information

Oldest version available on TypeScript Playground

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=0&module=1&ts=3.5.1#code/KYDwDg9gTgLgBDAnmYcDCEA2ngGMYCWEAdgPIBmAPAIIB8cAvHAN4BQcHcA2gNIBccAM4woBYgHMAugOqsAvq1YATPJgCGUVOMwQARmswt2nMTGBRya3KlK6AVnnhtOLuAFs1YGgBo4AIVoAChgACwJBAQxsRyIyKjpfcgFAgDcDAFdgGV8Aa2BEAWFRCQBKRno-EsisHHxYikoA4w4FBVZbB3wAOhVyMWAABSgIFFhEQI7HLrBhmAgkFF8Acg8wJd9nTjTMTIFydOI6kh9-INDw6uijuJpaROTt3bhqXPzCkTFxMoYKqvQamIkBoBIyuTg4eB6OyXWqEIFUEFMZhtMEccjQOCBCFwPKIOBiBBhQRlTaozhQri4ySMODkYJEyn5SSvRAlZquFGozQwdJQYhwKHsuTedm4Eh9cS8tS6HACESZeRs1jYkA05i0iAQAQAdl8+igAgAtAAWOAKbF4pggLqrQL8n5wfkAKjgAGYlQB6D1wPHhFgarVwABMAEY9RojSGg2bWGLiIIsMAujpxIFWYpsSgRjgaVx2eriGo3Fk4EsAFIQEL8gDKbgIoXWcDU4hLQYAHGaRS4C0WS+WIKhqyE3BBG82SwBWAAMMckGeA8CzYBwfkQADlezTiMAAO5wACynkCS5wNqPYHK3DgYC6heLvgvkhKJSAA

### 💻 Code

```ts
declare global {
    interface Object {
        map<A, B>(this: { [K: string]: A }, f: (value: A, key: string) => B): { [K: string]: B }
    }
}

Object.defineProperty(Object.prototype, 'map', {
    value: function<A, B>(this: { [K: string]: A }, f: (value: A, key: string) => B): { [K: string]: B } {
        let obj = {}
        for (let key in this) obj[key] = f(this[key], key)
        return obj
    }
})

let arr = [ { foo: 5, bar: 20 }, { foo: 8, bar: 100 } ]

// When Object.prototype.map is declared above,
// the following line gives an error because TypeScript infers the type of
// [ x.foo, x ]
// as
// (number | { foo: number, bar: number })[][]
// instead of the correct inference,
// [ number, { foo: number, bar: number } ][]
let mapFromArr = new Map(arr.map(x => [ x.foo, x ]))
```

### 🙁 Actual behavior

Somehow, defining `Object.prototype.map` interferes with type inference when using `Array.prototype.map`.

### 🙂 Expected behavior

`Array.prototype.map` should be unaffected because the Array prototype's map function overshadows that of the Object prototype.

**Comment by joshuakb2** [comment]
I worked around this issue in my code by giving my `Object.prototype.map` function a different name, but I reported it anyway because this seems like a bug to me. It's possible that this is intended behavior for some reason. If that's the case, I would love to understand it better.

**Comment by RyanCavanaugh** [comment]
Doing this creates new structural inference sites that shouldn't be here.

Fundamentally it's extremely unsafe to put stuff like this on `Object`, since you could legally write code that did this:
```ts
let arr = [ { foo: 5, bar: 20 }, { foo: 8, bar: 100 } ]
const p: { [K: string]: any } = arr;
p.map((a, b) => b);
```
which is not going to do what it appears to do.
