### ISSUE TITLE
Inferred type of properties in a union type

### ISSUE THREAD

**Issue by ferjul17** [microsoft/TypeScript#45412]
# Suggestion

In some cases, Typescript may improve inferred type of properties of unions of objects.

## 🔍 Search Terms

I found a similar issue: https://github.com/microsoft/TypeScript/issues/45397
However, I tried the fixed, but it implies to do additional checks that I want to avoid.

inferred type union object

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases

```typescript
type A = { A: string };
type B = { B: string };
type ACaller = (a: A) => void;
type BCaller = (b: B) => void;

function call({ letter, caller }: { letter: A; caller: ACaller } | { letter: B; caller: BCaller }): void {
  caller(letter); // Argument of type 'A | B' is not assignable to parameter of type 'A & B'.
}
```

In this example, Typescript infers that `caller` if of type `(arg0: A & B) => void` instead of `ACaller | BCaller`.
However, it should also know that if `caller` is `ACaller`, `letter` will be `A` and if caller is `BCaller` then `letter` will be `B`.

Currently, as a workaround, we do that:
```typescript
function callA({ letter, caller }: { letter: A; caller: ACaller }): void {
  caller(letter); 
}
function callB({ letter, caller }: { letter: B; caller: BCaller }): void {
  caller(letter);
}
```
But I would love to find a solution to factorise that.

**Comment by MartinJohns** [comment]
This sounds like a duplicate of #30581.

**Comment by ferjul17** [comment]
Yes, you're right, thank you!
