### ISSUE TITLE
Is there a list of required ES features to compile to ES5 or ES6?

### ISSUE THREAD

**Issue by SamuelEnglard** [Microsoft/TypeScript#4541]
I'm looking in to compiling my TypeScript to ES5 or 6 but I want to know what features are required by the browser to run code compiled for that environment. Like are the ES5 Array methods needed for ES5 or are the only needed if the developer uses them?

**Comment by kitsonk** [comment]
That is a hugely broad topic, especially when it comes to ES6.  There are two main resources for understanding the vagaries of browsers support [Can I Use?](http://caniuse.com) and [kangax's Compatibility Tables](http://kangax.github.io/compat-table/es6/).

**Comment by SamuelEnglard** [comment]
I think I wasn't clear on what I was asking. I want to know what features TypeScript uses from ES5 and ES6. So per my example does TypeScript use the ES5 Array methods or not?

**Comment by mhegazy** [comment]
What do you mean by "TypeScript uses"? do you mean the compiler? or do you mean the generated code?

If the generated code depends on a specific feature you will get an error from the compiler that this feature is not supported on your specified target. e.g. getters/setters when targeting ES3.

**Comment by SamuelEnglard** [comment]
I meant the generated code. I want to switch to using higher than ES3 but I want to know what features would need to be present for the code to run. Mostly so I can pollyfill it (or worst case accept that I'm stuck with ES3 still).

**Comment by SamuelEnglard** [comment]
That and I'm hoping to create a system that serves the correct ES version to a browser based on what they support, based on feature-test.io

**Comment by mhegazy** [comment]
If you are already building with no errors on ES3, it should be safe to switch to ES5. the compiler does not add any dependencies.

one thing to note, TypeScript does not inject/detect the use of polyfills. so if you are using any non-ES3 APIs (e.g. array.prototype.forEach) you need to polyfill them.

**Comment by SamuelEnglard** [comment]
And ES6?

**Comment by danquirk** [comment]
Same policy (no provided polyfills). You might want to look at core.js for the implementations of what you need to polyfill.
