### ISSUE TITLE
Intersection type is not resolved as expected when used with generics.

### ISSUE THREAD

**Issue by JeongHoJeong** [microsoft/TypeScript#45428]
# Bug Report

### 🔎 Search Terms

narrowing, grouping, generic and intersection

### 🕗 Version & Regression Information
I have tested all available versions on TypeScript Playground.
- 3.9.7 and after: `Expected` type works as expected. `Unexpected` types do not.
- 3.8.3 and before: `Expected` and `Unexpected` types both do not work as expected.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHZQLwCgpQD5QDeOupokAXFAOQBiyy1JpUYAhiADbJsAmVxFiwBmDKgGdgAJ0SoA5s1IBfRStwFBQ8hCrUAQmylMhrDtz4DFLAEaGqqAK4BbaxClWoa5VizbYCFFQAdURgAAsAFXAIADk2JwgAHgiAPkx-JDQoADIiKG0qCM9faKgAUQAPSAQIXnT4TODQyOi4hMS6BmoUgG1qdi4eXmoAXR8-AAUzIYB5YQbAkPCoyDaIAEZktIwMxeaV2Pik1L6B82GxvwBVVAgqiBredfSpwb45hbQlltWjzc7GClxqVXucPgEvvtWkcAExbdIACk+6FyhHy0UKngAlKdpnxRiVIFAbndqsBajCXnjeODGt8Dms4QDulggA)

### 💻 Code

```ts
// TypeScript version: 4.3.5
type Action =
  | {
      type: 'Foo'
      payload: {
        foo: string
      }
    }
  | {
      type: 'Bar'
      payload: {
        bar: number
      }
    }

type ActionWithTypeName<T> = Action & { type: T }
type Expected = ActionWithTypeName<'Foo'>['payload'] // { foo: string }

type PayloadOfActionWithTypeName1<T> = ActionWithTypeName<T>['payload']
type Unexpected1 = PayloadOfActionWithTypeName1<'Foo'> // { foo: string } | { bar: number }

type PayloadOfActionWithTypeName2<T> = (Action & { type: T })['payload']
type Unexpected2 = PayloadOfActionWithTypeName2<'Foo'> // { foo: string } | { bar: number }
```

### 🙁 Actual behavior

`Unexpected1` and `Unexpected2` are not identical to `Expected`.

### 🙂 Expected behavior

`Unexpected1` and `Unexpected2` should be identical to `Expected`.

**Comment by ahejlsberg** [comment]
This is effectively a design limitation. We don't realize that `{ type: 'Bar', payload: { bar: number } } & { type: 'Foo' }` is an empty type and therefore we don't eliminate it. I suggest writing this instead:

```ts
type ActionWithTypeName<T> = Extract<Action, { type: T }>;
```

**Comment by svenssonaxel** [comment]
@ahejlsberg Could you expand on what you mean by not realizing it's an empty type? It is eliminated when declared explicitly:
```ts
type Expected = { type: 'Bar', payload: { bar: number } } & { type: 'Foo' } // never
```

Also, I don't think `Extract` always is a viable workaround since it doesn't implement intersection. Example:
```ts
type NotAnIntersection = Extract<{ foo: 'bar' | 'baz' }, { foo: 'bar' }>; // never
```

**Comment by RyanCavanaugh** [comment]
It's not apparent from the form of the type that intersection reduction is necessary at all.

For example, if you wrote `({ x: number } & { y: string })["y"])`, there appears to be no reason to do type computation on the `{ x: number }` part of it at all, since the `y` property is clearly on the RHS.
