### ISSUE TITLE
Make TypeScript output work as ES modules by adding file extensions

### ISSUE THREAD

**Issue by richardkazuomiller** [microsoft/TypeScript#45439]
# Suggestion

## 🔍 Search Terms

typescript output extensions import

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I know there has been discussion about this before, but a lot of time has gone by and I can't find any reasonable solution. The file extension is required to use `import x from './y.js'` in JavaScript. On the other hand, TypeScript supports imports without an extension, and doesn't add the extension in the output. Importing without extensions is the de facto standard for TypeScript as far as I know, which means these two things are incompatible. I personally think it would be nice if it also worked without `.js`, but we are where we are, so I want to ask for help to fix this with a compiler option, or some other solution.

I really like TypeScript, but I think at this point, we all know that the output doesn't work in Node or the browser, which is effectively everywhere. I hope a solution that can be agreed on by most people can be found 🙏 

## 📃 Motivating Example

This would make `import x from './y';` compile to modern JavaScript 👏 

## 💻 Use Cases

ES modules

**Comment by nmain** [comment]
Frequently requested.  See https://github.com/microsoft/TypeScript/issues/16577 and https://github.com/microsoft/TypeScript/issues/42151 among others.
