### ISSUE TITLE
Update TypeScript Wikipedia article

### ISSUE THREAD

**Issue by chocolatechipui** [Microsoft/TypeScript#4543]
The Wikiepedia article wrongly mentions that TypeScript uses header files. I know they mean interfaces, but this is not the same thing. This can confuse and discourage persons investigating TypeScript. I suggest someone from Microsoft look into getting that corrected. 

https://en.wikipedia.org/wiki/TypeScript:
"TypeScript supports header files that can contain type information of existing JavaScript libraries, enabling other programs to use objects defined in the header files as if they were strongly typed TypeScript objects. There are third-party header files for popular libraries like jQuery, MongoDB, and D3.js. TypeScript headers for the Node.js basic modules are also available, allowing development of Node.js programs within TypeScript.[7]"

**Comment by jesseschalken** [comment]
Isn't the principle roughly the same as a C/C++ header file? It specifies the declaration and types of things that will exist at runtime (link time in C/C++) but are not part of the compilation unit. I suspect the author was just trying to express the idea using terminology the reader might already be familiar with.

**Comment by chocolatechipui** [comment]
TypeScript doesn't require d.ts files to transpile. They exist as a way to offer types at compile time. They are a convenience, not a requirement. Similarly interfaces are not required to compile TypeScript. You can write valid TypeScript without every using an interface. So, calling TypeScript declaration files headers is very misleading, especially if you're tring to attract Web developers. I can hardly imagine a normal Web developer wanting to write headers files for their JavaScript.

**Comment by jesseschalken** [comment]
You don't need header files in C/C++ if everything is part of the same compilation unit. Same thing.

**Comment by DanielRosenwasser** [comment]
Changed it:

> TypeScript supports definition files that can contain type information of existing JavaScript libraries, much like C/C++ header files describe the structure of existing object files. This enables other programs to use the values defined in the files as if they were statically typed TypeScript entities.
