### ISSUE TITLE
Word based suggestions returned when starting to type spread

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#45436]
Discovered in https://github.com/microsoft/vscode/issues/130096

# Bug Report

### 🔎 Search Terms

-  word based suggestions
- javascript
- spread
- warning suggestions

### 🕗 Version & Regression Information

4.4.1-rc

### 💻 Code

1. In a JS file:

```ks
const abc = {};

({ })
```

2. Put cursor inside the object literal and type: `.`

### 🙁 Actual behavior

JS `warning` suggestions (word based suggestions) are returned:

```
[Trace  - 22:36:59.359] <semantic> Response received: completionInfo (308). Request took 7 ms. Success: true 
Result: {
    "isGlobalCompletion": false,
    "isMemberCompletion": true,
    "isNewIdentifierLocation": false,
    "entries": [
        {
            "name": "abc",
            "kind": "warning",
            "kindModifiers": "",
            "sortText": "17"
        }
    ]
}
```

### 🙂 Expected behavior

No suggestions should be returned in this case since the user is likely starting to type a spread operator

**Comment by DanielRosenwasser** [comment]
Rescheduling to 4.5. @mjbvz if we need we can easily cherry-pick the fix into a patch for 4.4 if necessary.
