### ISSUE TITLE
Array.reduce initialValue allows incorrect array type to be supplied

### ISSUE THREAD

**Issue by jamesbrobb** [microsoft/TypeScript#45441]
# Bug Report

When supplying an array to the `initialValue` argument of `Array.reduce` and specifying the type of that array as a multi type array (i.e `Array.reduce<(string|number|boolean)[]>`), it's possible to then supply an array typed to only one of those types to the `initialValue` argument (i.e `string[]`) without an error being raised.

### 🔎 Search Terms

typescript array reduce initial value bug

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about `reduce`

### ⏯ Playground Link

[Playground example](https://www.typescriptlang.org/play?ts=4.3.5&ssl=13&ssc=21&pln=1&pc=1#code/C4TwDgpgBAhgNnA9gdwgEwIICcsxAFXAgGcoBeKY4LASwDsBzKAHyjoFcBbAIwixajdEiOBBh0A3ACgpAY0R0qsHOSgBtAIwAaKACYdAcmAALLBAgHDAM0TsslqAas0AbhZ0A2HdXYQAulpSUMGUwIhmAFyhtIxqfqpx0nIKSmbE7HDAqjA4AHRmaOyyEAA8ABTwSKiYOHiEkMQAlHEAfGUVsrJcURUIKOjYuARETXE6LvC+UZX9NUP1JI1RUL1VA7XDDc3xZC1QAN5BIUfBMJ1cueyKxjRWwGUTcL6N0iFQZsB2dLDnnEkAvjoqOEIC8ZPJFCIILkkAwymkMsAwUA)

### 💻 Code

```ts
type arrayTypes = string | number | boolean;

const arr = [1, 2, 'three', 'four', 'five', 6, true],
    store: string[] = [];

const result = arr.reduce<(arrayTypes)[]>((accum: (arrayTypes)[], value: arrayTypes):  (arrayTypes)[] => {
    
    accum.unshift(value);
    return accum;

}, store);

console.log(result); // [true, 6, "five", "four", "three", 2, 1] 
console.log(store); // [true, 6, "five", "four", "three", 2, 1] 
console.log(result === store); // true
```

### 🙁 Actual behavior

Allows an incorrect array type to be supplied to `initialValue` argument

### 🙂 Expected behavior

Supplying the incorrect array type to `InitialState` argument should raise a type error

**Comment by jcalz** [comment]
This is working as intended.  [Method parameters are intentionally bivariant](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant), which leads to `Array<T>` being covariant in `T`; hence `string[]` is considered to be a subtype of `(string | number | boolean)[]`.  This is unsound, but convenient.  Strict soundness is not a goal of TypeScript (see [Non-Goal #3](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals)).   See [this comment](https://github.com/microsoft/TypeScript/issues/274#issuecomment-232193911) on #274 and [this comment](https://github.com/microsoft/TypeScript/issues/9825#issuecomment-234115900) on #9825 for more information.
