### ISSUE TITLE
Auto import of React components not working if no previous import of React module...

### ISSUE THREAD

**Issue by Odonno** [microsoft/TypeScript#45449]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.4.1-rc

**Search Terms**
- auto import
- jsx
- react

---

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.59.0
- OS Version: Windows 10

Steps to Reproduce:

1. Start to write a new component (.tsx file)
2. Try to import a component inside your component, from another file

Details:

When using auto import of components, vscode do not display the import line unless I have imported React before (`import React from "react";`);
But, since React 17, importing react is no longer needed and so I don't see why we still need to have this import to make the auto import work.

Please refer to this article about the new JSX syntax: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

Note that I am using TypeScript, that's why my files are .tsx files instead of .jsx.

**Comment by RyanCavanaugh** [comment]
We need an actual concrete repro, including things like:
 * Your tsconfig
 * The layout of files on disk
   *  Where the file you created is
   * Where the file you're expecting to import from is
 * Where your cursor was in the importing file
 * etc

**Comment by Odonno** [comment]
I am using Next.js 11, without any specific configuration. Only the one recommended on the official website to switch from js to ts.

I can create a repro repository if you like.

**Comment by RyanCavanaugh** [comment]
A repository would be great, thanks!

**Comment by Odonno** [comment]
Here we go: https://github.com/Odonno/repro-45449

Clone the repo, open the index.tsx file (https://github.com/Odonno/repro-45449/blob/main/pages/index.tsx) and try to import the <Footer /> component with auto import.

**Comment by RyanCavanaugh** [comment]
>  try to import the component with auto import.

What is "the" component? What are you typing, and where?

**Comment by Odonno** [comment]
Sorry, I made a mistake when writing my previous message. Trying to import the `<Footer />` component using `CTRL+.` shortcut.

**Comment by RyanCavanaugh** [comment]
You need to set `"jsx"` to `"react-jsx"` in your tsconfig if you're intending to depend on the React automagic importing

**Comment by Odonno** [comment]
Can you give me more info?

I have tried this but this is not working:

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "downlevelIteration": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "react-jsx": "preserve"
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

Did I miss anything?

**Comment by Odonno** [comment]
Ok. Working fine. Thank you!
