### ISSUE TITLE
keyof Record<string, any> is string | number

### ISSUE THREAD

**Issue by ZhenyaUsenko** [microsoft/TypeScript#45447]
# Bug Report

### 🔎 Search Terms

keyof Record<string>

### 🕗 Version & Regression Information

4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

type Type = keyof Record<string, any>

![Screenshot from 2021-08-13 22-35-39](https://user-images.githubusercontent.com/76219110/129410797-14fe4551-a9c2-44a2-9a78-18f56cfdceba.png)

### 🙁 Actual behavior

keyof Record<string, any> returns string | number

### 🙂 Expected behavior
keyof Record<string, any> should be string

**Comment by jcalz** [comment]
This is working as intended.  See #23592 and the [TS2.9 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#support-number-and-symbol-named-properties-with-keyof-and-mapped-types).
