### ISSUE TITLE
update imports after move files

### ISSUE THREAD

**Issue by stupicode** [microsoft/TypeScript#45451]
update imports after move *.js files to new directory work fine for all *.js imports except CSS, SVG, ... .

Programming Language: JavaScript React
VS Code Version: 1.58.2
OS Version: win 10.0.19042 x64
`Module not found: Can't resolve '../../styles/xxx.module.css'`
`Module not found: Can't resolve '../../assets/empty_xct9.svg'`

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
