### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [microsoft/TypeScript#45452]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by orta** [comment]
This looks like the current Microsoft one: https://github.com/microsoft/AcceleratedML/commit/a469e0bd8c7d1e8cb16eced9791706e5dead8ad0

**Comment by RyanCavanaugh** [comment]
Sure; in the mean time please email ryanca@microsoft.com . Thanks!

**Comment by JamieSlome** [comment]
@RyanCavanaugh - the details will be sent over to you in the next hour! 🎉
