### ISSUE TITLE
HTMLMediaElement.preload has wrong documentation

### ISSUE THREAD

**Issue by mqus** [microsoft/TypeScript#45458]
# lib Update Request

## Configuration Check

~My compilation *target* is `ES2015` and my *lib* is `the default`.~
I found this issue directly in the `main` branch of typescript-src.

## Missing / Incorrect Definition

The `preload` attribute of `HTMLMediaElement` has the following documentation in typescript:
https://github.com/microsoft/TypeScript/blob/d50c91da1719dc4dd32474108dc4cf082d751f1b/lib/lib.dom.d.ts#L7480-L7483

but it should rather be something like
```
how the browser should preload the media. Can be one of `auto`, `metadata`, `none`
```

## Sample Code

see above. I found it while viewing the documentation with PHPStorm.
This should be a copy-paste-error from the description of `currentTime`. 

## Documentation Link

See https://developer.apple.com/documentation/webkitjs/htmlmediaelement/1633059-preload or https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attr-preload for what it actually does (hinting the browser if it should preload as much as possible(`auto`), only metadata(`metadata`) or nothing(`none`).

Imho for improved typing this could be an enum and not a string but I don't know the concept behind this file and am a newbie to ts(and having a string also has better backwards compatibility). But my main gripe here is the documentation :D

EDIT: Filled in the template.

**Comment by mqus** [comment]
I would have opened a PR myself but seeing you have a CLA in place, I rather don't.

**Comment by MartinJohns** [comment]
@RyanCavanaugh Would the team want only the documentation updated, or also introduce a breaking change and make the type more strict?

**Comment by RyanCavanaugh** [comment]
For "magic strings" that are almost always hardcoded in practice, we're generally open to a breaking change

**Comment by MartinJohns** [comment]
PR opened: microsoft/TypeScript-DOM-lib-generator#1113

**Comment by MartinJohns** [comment]
@RyanCavanaugh [My PR in TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1113) has been merged. What's the approach to get these changes in this repo to get this issue closed and a milestone assigned? I assume the team will import the changes at some point.

Also I want to point out explicitly that this introduces a **breaking change**:  
The type `string` changes to `"none" | "metadata" | "auto" | ""`.

**Comment by andrewbranch** [comment]
I believe @orta and/or @sandersn has a schedule for importing the generated libs back into TypeScript. I’m going to go ahead and close this since that process will not find this bug, and it ideally should have been opened against the generator repo. Thanks!

**Comment by mqus** [comment]
Thank you for adressing this as fast as you did!
