### ISSUE TITLE
Incorrect type flag TypeFlags.BooleanLiteral instead of TypeFlags.Boolean

### ISSUE THREAD

**Issue by ilyub** [microsoft/TypeScript#45468]
# Bug Report

### 🔎 Search Terms

TypeFlags Boolean BooleanLiteral

### 🕗 Version & Regression Information

v4.3.5

### ⏯ Playground Link

-

### 💻 Code

-

### 🙁 Actual behavior

It looks like compiler sets BooleanLiteral flag instead of Boolean

### 🙂 Expected behavior

Should set correct flag

**Comment by MartinJohns** [comment]
Is this #40203? Hard to tell, because you provided close to no information.

**Comment by ilyub** [comment]
I found that typescript provides union type that consists of true and false literals instead of just Boolean type.
This is suitabe for me.
Probably this is expected behavior.

**Comment by MartinJohns** [comment]
That is the expected behaviour, yes.
