### ISSUE TITLE
Compile latin1 source files to latin1 output files

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#45462]
# Bug Report

Source files encoded as latin1 are not compiled to latin1 files, making their size balloon unnecessarily.

### 🔎 Search Terms

- latin1

### 🕗 Version & Regression Information

- @latest, never worked differently AFAIK

### ⏯ Playground Link

It would be meaningless as the output files need to be written to disk for the issue to manifest.

### 💻 Code

The following archive contains the source file and the output file I'm getting.

[files.zip](https://github.com/microsoft/TypeScript/files/6988978/files.zip)

### 🙁 Actual behavior

The source file (latin1) weighs 1.3MB, the output file (utf-8?) weighs 2.3MB, and the source file contains only a string basically so that dramatic size difference shouldn't exist.

### 🙂 Expected behavior

Latin1-encoded source files should produce latin1-encoded output files, unless that's not possible, otherwise their size will most probably balloon for no good reason.

**Comment by fabiospampinato** [comment]
Apparently latin1 modules are not imported properly in Node, maybe it's assumed that those are utf-8-encoded modules 🤔 I guess it's more complicated than I thought it was at the very least.

**Comment by RyanCavanaugh** [comment]
This isn't really in-scope for TS given how rare it is. It'd be appropriate to use a post-build step to re-encode the file if you have some other JS process that can actually ingest that sort of file.
