### ISSUE TITLE
Disable global types per file

### ISSUE THREAD

**Issue by mwisnicki** [microsoft/TypeScript#45477]
I need to define my own type called `Map`.
This is currently conflicting with global type of the same name.

I need a way to disable global types in single file (or really have a way to import them explicitly and with aliasing).

**Comment by mwisnicki** [comment]
Note that there's no conflict if i use TS namespaces but I'm trying to make ESM module:

```ts
namespace foo {
  interface Map {} // this is ok but I don't want that
}
interface Map {} // All declarations of 'Map' must have identical type parameters.(2428)
```

**Comment by DanielRosenwasser** [comment]
You can add `export {}` to ensure that your `Map` doesn't merge or collide with the one in the global scope.

If modules are out of the question, a namespace is really the only thing that can allow you to create a separately-declared `Map` type.

**Comment by DanielRosenwasser** [comment]
Also, please take future questions to the TypeScript Discord or StackOverflow.
