### ISSUE TITLE
No suggestion diagnostic for unchecked JS files in method from class

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#45479]
```js
class Person {
    getFavoriteColor() {

    }
}

const person = new Person();
person.getFavoriteColour();
```

**Expected**

A suggestion diagnostic:

```
Property 'getFavoriteColour' may not exist on type 'Person'. Did you mean 'getFavoriteColor'?
```

**Actual**

No suggestion diagnostic.

In contrast, see this example:

```js
const person = {
    getFavoriteColor() {

    }
}

person.getFavoriteColour();
```

**Comment by DanielRosenwasser** [comment]
Ugh, from https://github.com/microsoft/TypeScript/pull/44271

> The error is suppressed for property accesses on a class because the compiler doesn't understand JS constructor functions well enough. In particular, it doesn't understand any inheritance patterns.

**Comment by sandersn** [comment]
I think that rule could be improved to allow suggestions from class types that are known to come from a class declaration or expression which *don't* have an `extends` clause. It's constructor functions where I observed the bad suggestions, and it's possible that completions from a base class might also be bad.

That rule is even harder to explain though.
