### ISSUE TITLE
Feature/Limitation: Dynamic Initialization of Discriminated Unions improved support, else one any's

### ISSUE THREAD

**Issue by wesleyolis** [microsoft/TypeScript#45486]
Discriminated Unions, type inference kind field, results in narrowing, prevents initialization of this structures dynamically, with out casting. Typically thinking similar behavior to that of class contractor may be wanted here. Or that if one puts the statement in additional braces, block scope { } then like class constructor, check in that block scope for the remaining parameters, but by convention only if the variable immediately follows the opening brace, else just do traditional logic, because there is no early stop for end brace in evaluation the validation.

# Bug Report

Basically when using Discriminated Unions, one has a very difficult time to initialize such structures, because
the kind field always gets narrowed. The kind discriminator field should only be narrow if kind field has been narrow in the object literal, otherwise it must list all common fields, such that common fields can be initialized, using a single section of code.
Its not perfect, because someone thinking of it, could expect the type to have been fully initialized, where they mayn't have followed with the conditional initialization. But trade of is going to have to be made, either ts checks for a conditional that initialize the result of the structure or there needs to be a single base common fields type identifier.

Here is one other idea to maybe solve this problem, some solution is need to avoid casting, and making the typing system more intelligent. Any other ideas with out casting, repetition, call base function inline function to solve the problem would be welcomed.

### 🔎 Search Terms
Discriminated Unions [This condition will always return 'false' ]

### 🕗 Version & Regression Information
I think this has always been the behavior, 3.3 and latest version still show the behavior.

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=3.3.3#code/FAUwdgrgtgBA0gSzAEwCoE8AOIYG9gyEwCCANAUQELlEwDCwAvsMEgC4gBOAZgIYDGOSrwDOIADyoYIAB4cUI+EjRYQAPkL5aAa2UAuGKhpFuCEABtkwsQZFtOSAOZMW7Ln0ElrOWfOSLvcUQUDGwAOmINfBdWMA4eASFvaTlwfxhA4JVwyiiKQhi3BM86ZN80gNEJLNCQMLo82lMLZDoDSCgAIy4YtlUMqsUAXi8qmAAfDOTJ0qqWfgB7MDsYTqReTnRUBYA5aG7Odv2uGBGABgBueaWV0REERzADb2G8fJhdFD01sA2t3eOnGMhGalmSBgARJR1pttgBlexOCGkWhMGAAenRMFEAzEIhRhgAFghFH1sDASTBfpxOAsAO4gZAwNgLZmEnBQXhsfjEsCOD7KGB2TgQfhsCCcEAsVjcAAUdweYDCnyZQzVShCqnqAEo8BisahiYpFigEGwEEsYHSEOZzNjzHTeOhFJLxZwwDAAOR8cxiT1CpCeNjs5mqRSempa4gTDXZOqUf28FBeyPhOj+wm8ABuODArIWOc45l4mDCsoATABmABsAHZte8FY8wvqUoJMGw2VyYAAxMyWOhCwkLCCWVY4bO8cwIXidcwgFEia3cwnYwmkkMiXhQHCYWlzkBQMIxIA)

### 💻 Code

**Case 1:**
```ts repro

enum KindType {
    A,
    B,
    C
}

interface Base<T extends KindType>  {
    kind: T,
    fieldBase: string
}

interface ABase extends Base<KindType.A> {

}

interface BBase extends Base<KindType.B> {

}

interface CBase extends Base&lt;KindType.C> {
    fieldC: number
}

type Bases = ABase | BBase | CBase

const binaryToNumber: number = 0;

// The following assignment, typescript seem to narrow 
const assign: Bases = {
    kind:binaryToNumber,
    fieldBase : "BinaryToString",    
} // as Bases,  This type is narrowed to the matching kind structure

// Now attempt to initialize all the specific fields for each kind, using if or switch state, is not possible.

if(assign.kind === KindType.C) { // This condition will always return 'false' since the types 'KindType.A | KindType.B' and 'KindType.C' have no overlap.(2367)
    assign. // except that FieldC should be available, switch has the same problem.
}
```

**Case 2:**

```.ts

enum KindType {
    A,
    B,
    C
}

interface Base<T extends KindType>  {
    kind: T,
    fieldBase: string
}

interface ABase extends Base<KindType.A> {
     fieldA: number //  uncommnet for case 2
}

interface BBase extends Base<KindType.B> {
     fieldB: number // uncommment for case 2
}

interface CBase extends Base<KindType.C> {
    fieldC: number
}

type Bases = ABase | BBase | CBase

const binaryToNumber: number = 0;

Type '{ kind: number; fieldBase: string; }' is not assignable to type 'Bases'.
  Property 'fieldC' is missing in type '{ kind: number; fieldBase: string; }' but required in type 'CBase'
  Incorrectly picking the last field, should just be the base set of fields and not specific, because there
  is type specific narrowing here at all..
 
const assign: Bases = {
    kind:binaryToNumber,  // This is a number, thus kind field shouldn't be narrow, especially since the variable has been given the a type of Union Discriminator for its type, it should represent all kind possibilities.
    fieldBase : "BinaryToString",    
} // as Bases,  This type is narrowed to the matching kind structure

// Now attempt to initialize all the specific fields for each kind, using if or switch state, is not possible.
if(assign.kind === KindType.C) { // This condition will always return 'false' since the types 'KindType.A | KindType.B' and 'KindType.C' have no overlap.(2367)
    assign. // except that FieldC should be available, switch has the same problem.
}

```
Expected behavior of type narrowing for algebraic discriminators
```.ts
const assign: ABase = {
    kind: KindType.A ,  
    fieldBase : "BinaryToString",    
fieldA:""
} // OK, type narrows to kindType.A of the union.

typeof assign => {
kind: KindType.A
fieldBase: string
fieldA:  number
}

const kindField : number | KindType;

const assign: Base = {
    kind: kindField ,   // or a number shouldn't result in the type being narrowed, only commons fields.
    fieldBase : "BinaryToString" // Common fields should appear here, because we havn't narrowed.
} // OK, kindType.A is not narrow can a conditional check needs to be used to see fields that are not shared
// by all in the Union Discriminator.

// Should be allowed to assign anything to assign, but the type has been narrow, with the last enum.
typeof assign => {
 kind: KindType
fieldBase : string
} | {
kind: KindType.A
FieldA: number
} | {
kind: KindType.B
FieldB: number
}| {
kind: KindType.C
FieldC: number
}

```
**Otherwise on how to maybe improve solving the problem with out introduce ambiguity.**

```.ts
        let rec:unknown|Base;//Deferable to inference, or checked that type has been assigned before the end of the let scope and not read before hand.
        switch((rec : Bases = {KindType:0}).KindType) {
            default:                
                rec.fieldBase = BufR.Reader;                
            case KindType.A:

            break;
            case KindType.B
            beak;
        }
```

Another Idear for allow more find grained control of typing's change the as operator that the first instance
is type narrowing for validation and casting must first go to 'as any as Base

```.ts
const num: number = 
let rec: Bases = {
kind: num,
baseField:"sd"
} as Base<any> // this statement explicitly turns off the checking of non common fields, intentially, right now assignment will not be allowed..

```

```.ts
        const recBase = {
           kind:kindtype as number,
           fieldBase
        }

         let recBases;

        switch(recBases) {
            default:                
               rec = recBases;
            case KindType.A:

            break;
            case KindType.B
            beak;

        }
```

**Comment by RyanCavanaugh** [comment]
I really can't tell what's going on here. If this is a bug, please clearly demonstrate it. If this is a suggestion, please use the Suggestion template.

**Comment by wesleyolis** [comment]
@RyanCavanaugh You are joking right, like ability for ts guys understand stuff is very low in seeing permutations/combinations puzzle peace come to gather for nice tight fitting language, starting to get frustrated. 2 Seconds on a problem you guys give up, by the looks of it.
