### ISSUE TITLE
Type parameter which extends `Partial`ed tuple is not assignable to rest args

### ISSUE THREAD

**Issue by h-a-n-a** [microsoft/TypeScript#45488]
# Bug Report

### 🔎 Search Terms

type inference, partial, tuple, rest

### 🕗 Version & Regression Information

tested for every 4.x releases

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShDOwCCAnA5vAPAFShAHsBAHYAm8UAFAHS0CG68AXFHcSANoC6AlFALwA+VuwA0UAKp5CJciM5dh-KAAUGdALYQiKLACgoUbHuEEiZCh1rUJ465QCWxAGYQUqnlwNQA-Ku8s3ADcenoAxgD2xIhQAEZOpAJQmN64ZrIUNPSMLGwKfELyot5S6RaqDMAOdAA2mGoomtpuWNiCgiaU3s7ELNjFhsAAFg7wqGi5Yt7WYOoazJJ6BcIA3t4o2gCuKMRQzpvEYVVRVNZOxG7jC3CIVzjiEoI8LHDA28TY4BA4q96GkdFgHtiABpCAgJIAZRAGliERqlB4IUMgxGY3QHB6YJAXCSPWRKIBMQ28E2NSBymGo3GmNB4K4WWos0a8zstHOl0YSL+UFIEBqzSgVPRaFp2K4BMMGzeOygJLJwAJAF8QirQvtDsdds4IhFKMQmixECgnGhxHQ0BAWMRNrC3ObSKQUEbgCbiGg+CslaEiUCUAcLu5lPEyJQdRFxDaajVuf7iIHKAAiRPiACMAA5xImNAx4InuUA)

### 💻 Code

```ts
type RestArgs<T extends (...args: any[]) => any, U extends any[]> = Parameters<
  T
> extends [...U, ...(infer P)]
  ? P
  : [];

const bind = <
  T extends (...args: any[]) => any,
  U extends Partial<Parameters<T>>
>(
  fn: T,
  thisArg: any,
  ...params: U // A rest parameter must be of an array type.
) => {
  return function (...innerArgs: RestArgs<T, U>): ReturnType<T> {
    const fnKey = Symbol();
    thisArg[fnKey] = fn;
    const result = thisArg[fnKey](...params, ...innerArgs);
    delete thisArg[fnKey];
    return result;
  };
};

function foo(name: string, age: number, addr: string) {}

const runner = bind(foo, null);
runner("", 18, "mars");
```

### 🙁 Actual behavior

Type parameter `U` is not assignable to `params`. TypeScript compiler complains `A rest parameter must be of an array type.`

### 🙂 Expected behavior

TypeScript compiler should not complain about this.

### Current workaround

Add `& any[]` to ` U extends Partial<Parameters<T>>`, which becomes ` U extends Partial<Parameters<T>> & any[]`, which forces TypeScript to regard it as an array. It works fine, but I'm still wondering if this is a bug.

**Comment by RyanCavanaugh** [comment]
`Partial<` isn't a match for what you need here, since it implies the allowance of e.g. objects which lack a `length` property but have a `3` property and no `0` `1` or `2`, which is not a valid description of a parameter list.

What you want is something like this, which works like what you're expecting:
```ts
// TODO: Convert to fancy recursive version; simpler form demonstrated here
type LeadingOf<T> =
  T extends [infer A] ? [] | [A] :
  T extends [infer A, infer B] ? [] | [A] | [A, B] :
  T extends [infer A, infer B, infer C] ? [] | [A] | [A, B] | [A, B, C] : []

const bind = <
  T extends (...args: any[]) => any,
  U extends LeadingOf<Parameters<T>>
>(
```

**Comment by jcalz** [comment]
@RyanCavanaugh 

Hmm, can we explain why this works?

```ts
const bind = <T extends any[], U extends Partial<T>>(
  fn: (...arg: T) => any,
  thisArg: any,
  ...params: U
) => { };

function foo(name: string, age: number, addr: string) { }

bind(foo, null);
bind(foo, null, ""); // okay
bind(foo, null, "", 3); // okay
```

Seems to be an inconsistency between when `Partial<T>` is and is not considered arraylike enough for the compiler.
