### ISSUE TITLE
Import hint for `path/posix` is incorrect

### ISSUE THREAD

**Issue by Nixinova** [microsoft/TypeScript#45485]
VSCode issue, by previous one was redirected here, so assuming TS hints are covered here.

# Bug Report

### 🔎 Search Terms

- path import autocomplete hint
- cannot import module

### 🕗 Version & Regression Information

- [x] I was unable to test this on prior versions because ... Playground doesn't install builtin modules correctly (`Check dependency list! Synchronous require cannot resolve module 'path'. This is the first mention of this module! `)

### ⏯ Playground Link

N/A

### 💻 Code

```ts
import path from 'path/posix';
console.log(path.resolve('foo', 'bar'));
```

- [Repo](https://github.com/Nixinova/Linguist/tree/fe9718c54a6924bc09e164f7c02db14f223a7711)
- [Workflow](https://github.com/Nixinova/Linguist/runs/3347099061) ([v14](https://pipelines.actions.githubusercontent.com/yRMPmcGa5V3vf8t8xPevUPdv2YUcg4ECl7D6E60fJ95MATcjWB/_apis/pipelines/1/runs/37/signedlogcontent/4?urlExpires=2021-08-17T05%3A18%3A02.3293292Z&urlSigningMethod=HMACV1&urlSignature=Q7zFKtAPvWR1pXqUrJirgkcfrGvQblHdHjkF9lwT4hI%3D), [v16](https://pipelines.actions.githubusercontent.com/yRMPmcGa5V3vf8t8xPevUPdv2YUcg4ECl7D6E60fJ95MATcjWB/_apis/pipelines/1/runs/37/signedlogcontent/3?urlExpires=2021-08-17T05%3A18%3A18.4354540Z&urlSigningMethod=HMACV1&urlSignature=RD2Xxrk%2Bh4%2FxDe1N3s71nkX%2FnqHE9Jkatqs4AYK95Ls%3D))

TSConfig targets es2019 + esModuleInterop true

#### Reproduce
Create a new TS file and attempt to import `path` or `posix`:
![image](https://user-images.githubusercontent.com/42429413/129667236-4f22183a-4ab6-4cc3-a857-e1f1d245c011.png)

You get the following:
```ts
//> import pos→:
import { posix } from "path/posix";
//> import path→:
import path from "path/posix";
```

When, to support Node <16, it should be: 
```ts
//> import pos→:
import { posix } from "path";
//> import path→:
import path from "path";
```

### 🙁 Actual behavior

- Node 16: works fine
- Node 14: `Error: Cannot find module 'path/posix'`

**Comment by IllusionMH** [comment]
These declarations are provided by `@types/node` and you have single version installed
https://github.com/Nixinova/Linguist/blob/fe9718c54a6924bc09e164f7c02db14f223a7711/package.json#L46

`ts4.3` is tag for `16.6.1` which has declaration for `path/posix` module.
For project with Node.js 14 support you should install `@types/node@^14.17.9`
