### ISSUE TITLE
Generic type inferring via `instanceof` and `isArray` not working when returning new variable

### ISSUE THREAD

**Issue by davwheat** [microsoft/TypeScript#45492]
# Bug Report

### 🔎 Search Terms

generic, infer, instanceof, return type, isArray

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/GYVwdgxgLglg9mABAEwKaoA4GEA2DUDyARgFarQA8AKgHwAUcpAXIlQJQtWIDeAsAFCJEAemGIAEgEMwyHKkRgQOHImnIFCALSMy0AM4ChMYIgalEAXiuJwaYDDCp1AH2eIdl64uWJXiKACeGKhwJh4AhNYA5DrkUFFsiABOqFAgSUg6ANwChiJiUjJyKJJQqAaCiMamHg56UNIQISYAIqWoiXyVQqKIAJJgejBo-gAWMHqIRHgQANYANIgA7vKzYHBLrFWTkohtZaqTAAY6R9vujgB0eUJyUIgQcBgBlgqom-uodGw53Q9PAUuelSVBgAFsvjpLgBzEHgr5sH43ZKpdJIR7PX5CAC+eVQOGBVRMdAAgkkkpJARMyRSAmYSIieMjegMhiMoONJtM4HNFitEGsNlsJqokDTKYdECdSGcRfhrn87v9nq8ANoAXSxQkQwDgSVMSpgrwADIs5EgLO5SJdzdCOVkqogKIhzQ6YABqd2dZFCDEBVUwdWvNCYXD4Yi6KD0gPqpF-XF-FJpDLKgJahNCfGE6r0qqDBqQZqICNxb1-FmDYbyDki7m85ardabLgi6TF0hxSXSkiyyby5FKv2vbjYrVCXX6uhK0pQfUOK0Mpl-IzEqGjSR6AhLMAABSST1QSUCdBnSUZftVp6DlpD2DwjhL0GjV7j2sQGe1SbRqfTuUqHP3TYACIAFVBhADAMD1Mp1ECYJLiA35sSAA)

### 💻 Code

```ts
function example<T>(obj: T): T {
  if (obj instanceof Date) {
    // Inside this block, we know T is a Date as `obj` is one.
    let copy = new Date();
    copy.setTime(obj.getTime());
    return copy;
  }

  return obj;
}
```

### 🙁 Actual behavior

Typescript shows an error on `return copy` as T might not be a Date.

### 🙂 Expected behavior

No error should be shown. T is the same type as `obj`. Is `obj` is an instance of a Date, then `T`'s type should be `Date`, creating no error.

**Comment by fatcerberus** [comment]
Your check proves that `obj` has `Date` in its prototype chain, it proves nothing about `T`.  In particular `T` might be a *subtype* of `Date`, in which case returning a plain `Date` would be an error.

**Comment by davwheat** [comment]
Ah, that totally flew over me. Thanks for spotting!
