### ISSUE TITLE
error TS2300: Duplicate identifier for self-referencing packages.

### ISSUE THREAD

**Issue by theodorDiaconu** [microsoft/TypeScript#45497]
# Bug Report

I have two packages A and B.

B has peerDependency on A
A has devDependency on B (for running certain tests)

B extends an external package and exports a module:
```ts
declare module "yup" {
  export type ObjectIdSchemaConstructor = { ... }
}
```

Now funnily, because of B's peerDependency on A, running installation brings A bundle into node_modules of A. Thus the error of duplicate identifier.

```ts
node_modules/@bluelibs/x-bundle/dist/validators/declarations.d.ts:21:10 - error TS2300: Duplicate identifier 'ObjectIdSchemaConstructor'.

21     type ObjectIdSchemaConstructor = {
            ~~~~~~~~~~~~~~~~~~~~~~~~~

  src/validators/declarations.ts:25:15
    25   export type ObjectIdSchemaConstructor = {
                     ~~~~~~~~~~~~~~~~~~~~~~~~~
    'ObjectIdSchemaConstructor' was also declared here.

node_modules/@bluelibs/x-bundle/dist/validators/declarations.d.ts:24:11 - error TS2451: Cannot redeclare block-scoped variable 'objectId'.

24     const objectId: () => ObjectIdSchema;
```

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't know anything about peer dependencies or dev dependencies. It sounds like someone is just shipping wrong types? I don't understand what the implied bug is here.

**Comment by theodorDiaconu** [comment]
@RyanCavanaugh let me clarify as I understand how it can be confusing.

Inside my `x-bundle` I do inside a file: `declare module yup { export type X { } }`. 
In my `x-bundle` I have a devDependency on `x-password-bundle` (to run some specific tests).
`x-password-bundle` has a peerDependency and devDependency on `x-bundle`.

This means that I end up having `x-bundle` inside node_modules on `x-bundle` thus triggering error of duplicate export of type from yup.

Now that I think about it this may not be a TS bug in the sense that TS does it's thing, it reads the types of the node_modules and "detects" a duplicate export of the same type from two different sources. (the one from node_modules/.../x-bundle/dist/declaration.ts and the one from dist/declarations.ts)
