### ISSUE TITLE
Maximum call stack size exceeded in `isValidSpreadType()`

### ISSUE THREAD

**Issue by kevinbeal** [microsoft/TypeScript#45493]
# Bug Report

### 🔎 Search Terms

"Maximum call stack exceeded"
I think this is different from any of the other issues that appear because of the template literal types I mention below.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.0.5 and 4.3.5 (template literal types involved?)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210817#code/C4TwDgpgBAylC8UAGASA3gOwK4FsBGEATgL5IDcAUAMYD2GAzsFHglGhVJ1FQFxQAUAbQDkAFmEBdKAEN6sQRICUAOhzSw-AGZYMVYAEs6-eovZdz3Ooxms0y+-QA0UEHwBsxDl2KKKxSkA)

### 💻 Code

```typescript
type S = `${number}`;
const b = {
    c: (['4'] as S[]).map(function(s){
        const a = {...s, y: 6}
    })
};

```

### 🙁 Actual behavior

Maximum call stack exceeded, probably due to some missing implementation for template literal types in `isValidSpreadType()` although I can't find it in the typescript source on Github. None of the functions in the stack trace can be found on the Github repo. Weird right?

The trace looks like this:

> RangeError: Maximum call stack size exceeded
>    at getResolvedBaseConstraint (/home/kev/www/monorepo/node_modules/typescript/lib/typescript.js:55192:43)
>    at getBaseConstraintOfType (/home/kev/www/monorepo/node_modules/typescript/lib/typescript.js:55172:34)
>    at isValidSpreadType (/home/kev/www/monorepo/node_modules/typescript/lib/typescript.js:69059:34)
>    at isValidSpreadType (/home/kev/www/monorepo/node_modules/typescript/lib/typescript.js:69061:28)

### 🙂 Expected behavior

I expected an error to be reported that template literal types are not valid spread types.

**Comment by RyanCavanaugh** [comment]
> None of the functions in the stack trace can be found on the Github repo.

They're in `checker.ts`, presumably past some hardcoded file length limit the GitHub search indexer has (since that file is very long).
