### ISSUE TITLE
type Tuple<T> = T extends [...infer P] ? P : never;  

### ISSUE THREAD

**Issue by chacent** [microsoft/TypeScript#45495]
# Bug Report

### 🕗 Version & Regression Information

4.3.5

### 💻 Code

```ts
type Tuple<T> = T extends [...infer P] ? P : never;
    type Merge<T extends any[] , U extends [...{ [P in keyof T]:any}]> = [];
    type X =  [(a:number)=>number,(a:number)=>number];
    type Y = Merge<X,Tuple<X>>;
    type Test<T extends any[] > = Merge<T,Tuple<T>>; // this line has error
```

类型“Tuple<T>”不满足约束“[...{ [P in keyof T]: any; }]”。
  不能将类型“unknown[]”分配给类型“[...{ [P in keyof T]: any; }]”。
    目标仅允许 1 个元素，但源中的元素可能不够。
      不能将类型“any[]”分配给类型“[...{ [P in keyof T]: any; }]”。
        目标仅允许 1 个元素，但源中的元素可能不够。

### 🙁 Actual behavior

T!=```Tuple<T>```  where T extends any[]

### 🙂 Expected behavior

```Tuple<T>```  should be T where T extends any[]

**Comment by chacent** [comment]
i thought that because diffrence from array and tuple is discard incorrected,and i want to know how to constraint type to be tuple and not be array

**Comment by awerlogus** [comment]
```ts
type Tuple<T> = (ReadonlyArray<T> & { 0: T }) | readonly []
```

**Comment by chacent** [comment]
i thought that because diffrence from array and tuple is discard incorrected,and i want to know how to constraint type to be tuple and not be array

> ```ts
> type Tuple<T> = (ReadonlyArray<T> & { 0: T }) | readonly []
> ```
not ok, ts's type really hard to understand

**Comment by RyanCavanaugh** [comment]
This is a correct error; `T` could be instantiated with something like `[unknown] & { m: string }`, which has `m` as a key which would be expected in the mapped type but missing from the inferred tuple

**Comment by chacent** [comment]
> This is a correct error; `T` could be instantiated with something like `[unknown] & { m: string }`, which has `m` as a key which would be expected in the mapped type but missing from the inferred tuple

thank you . 
but i do not understand this point, i had constraint T as any[], why `m` occured? even if `m` exists is corrected,why ts does not differentiate array(or tuple) and mapped type? thanks again

**Comment by chacent** [comment]
```ts
type Tuple<T extends any[]> = [...T] extends [...infer P] ? P : never;
        type Tuple2<T extends any[]> = [...T,any] extends [...infer P,any] ? P : never;
        type Merge<T extends any[] , U extends [...{ [P in keyof T]:any}]> = [];
        type X =  [(a:number)=>number,(a:number)=>number];
        type Y = Merge<X,Tuple<X>>;
        type Test<T extends any[] > = Merge<Tuple<T>,Tuple2<T>>;
```

it seems that it has another problem

Type 'Tuple2<T>' does not satisfy the constraint '[...{ [P in keyof Tuple<T>]: any; }]'.
  Type 'unknown[]' is not assignable to type '[...{ [P in keyof Tuple<T>]: any; }]'.
    Target requires 1 element(s) but source may have fewer.

**Comment by RyanCavanaugh** [comment]
That is also a correct error.
```ts
// M === any[], which is not a 1-tuple
type M = Tuple2<any[]>
```

**Comment by chacent** [comment]
> That is also a correct error.
> 
> ```ts
> // M === any[], which is not a 1-tuple
> type M = Tuple2<any[]>
> ```

i don't think so. both Tuple<T> and Tuple2<T> is inferred ,with same T, result should be same too.
