### ISSUE TITLE
Type definition  reference complie error with camelcase types in linux.

### ISSUE THREAD

**Issue by xiamidaxia** [microsoft/TypeScript#45509]
# Bug Report

I create a file `src/typings/spine.d.ts`:

```typescript
/// <reference types="phaser/types/spine"/>
/// <reference types="phaser/types/SpinePlugin"/>
/// <reference types="phaser/types/SpineFile"/>
/// <reference types="phaser/types/SpineGameObject"/>
```
but  compile with error on linux:

```
[compile] src/typings/spine.d.ts(2,23): error TS2688: Cannot find type definition file for 'phaser/types/spineplugin.d.ts'.
[compile] src/typings/spine.d.ts(3,23): error TS2688: Cannot find type definition file for 'phaser/types/spinefile'.
[compile] src/typings/spine.d.ts(4,23): error TS2688: Cannot find type definition file for 'phaser/types/spinegameobject'
```
These files exist in `node_modules/phaser/types/` , but are converted to lowercase.

![image](https://user-images.githubusercontent.com/4162271/130004673-e1f1e507-7c6a-49c0-b8a7-758528277ffa.png)

https://github.com/photonstorm/phaser/tree/master/types

### 🕗 Version & Regression Information

Typescript version: 3.9.3 and 4.x

Linux Red Hat 6.4.0-1. 

There is no such problem on Mac.

**Comment by fatcerberus** [comment]
Looks like #45096.
