### ISSUE TITLE
New typescript error only appears while emitting declarations

### ISSUE THREAD

**Issue by heath-freenome** [microsoft/TypeScript#45505]
# Bug Report

I have two config files... one that checks types but does not emit anything and the other pretty much the same, except it emit types for when we publish our library. When I run the first configuration everything passes. When I merged my code and the publish happens it failed with the following error:

```
<path to code>/gridOneOfField.tsx:22:17 - error TS2742: The inferred type of 'getSelectedOption' cannot be named without a reference to '@rjsf/core/node_modules/@types/json-schema'. This is likely not portable. A type annotation is necessary.

22 export function getSelectedOption(options: SchemaType[], selectorField: string, value: any, convertOther: boolean) {
                   ~~~~~~~~~~~~~~~~~
```

### 🔎 Search Terms

TS2742 on emit only

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I just started using Typescript

### ⏯ Playground Link

None

### 💻 Code
config that works:

```
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "noUnusedParameters": false,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "jsx": "react",
    "lib": ["dom", "dom.iterable", "esnext"],
    "noEmit": true
  },
```

config that fails:

```
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "noUnusedParameters": false,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "jsx": "react",
    "lib": ["dom", "dom.iterable", "esnext"],
    "declaration": true,
    "emitDeclarationOnly": true,
    "declarationMap" : true,
    "outDir": "./lib"
  },
```

### 🙁 Actual behavior

Why would emitting types cause new errors to show up?

### 🙂 Expected behavior

I would expect the error to have been detected regardless of whether I was emitting types or not

**Comment by RyanCavanaugh** [comment]
> I would expect the error to have been detected regardless of whether I was emitting types or not

This is not a correct expectation. There are certain constructs, like the one you have here, which can't have declarations emitted, but which typecheck fine.

**Comment by heath-freenome** [comment]
> > I would expect the error to have been detected regardless of whether I was emitting types or not
> 
> This is not a correct expectation. There are certain constructs, like the one you have here, which can't have declarations emitted, but which typecheck fine.

Does specifying the emit parameters along with `noEmit: true` allow me to check for this situation without actually emitting?
