### ISSUE TITLE
Please add toBlob as implemented by FF & more recently Chromium

### ISSUE THREAD

**Issue by charlesprogrammr** [Microsoft/TypeScript#4550]
Chromium added support for the HTMLCanvasElement.toBlob method, as it should have been added 5 years ago. lib.d.ts is now lacking support for said method.

See https://code.google.com/p/chromium/issues/detail?id=67587#c112 for details.

**Comment by charlesprogrammr** [comment]
Perhaps this might help.

interface HTMLCanvasElement extends HTMLElement {
    /**
      * Gets or sets the height of a canvas element on a document.
      */
    height: number;
    /**
      * Gets or sets the width of a canvas element on a document.
      */
    width: number;
    /**
      * Returns an object that provides methods and properties for drawing and manipulating images and graphics on a canvas element in a document. A context object includes information about colors, line widths, fonts, and other graphic parameters that can be drawn on a canvas.
      * @param contextId The identifier (ID) of the type of canvas to create. Internet Explorer 9 and Internet Explorer 10 support only a 2-D context using canvas.getContext("2d"); IE11 Preview also supports 3-D or WebGL context using canvas.getContext("experimental-webgl");
      */
    getContext(contextId: "2d"): CanvasRenderingContext2D;
    getContext(contextId: "experimental-webgl"): WebGLRenderingContext;
    getContext(contextId: string, ...args: any[]): CanvasRenderingContext2D | WebGLRenderingContext;
    /**
      * Returns a blob object encoded as a Portable Network Graphics (PNG) format from a canvas image or drawing.
      */
    msToBlob(): Blob;
    /**
      * Returns the content of the current canvas as an image that you can use as a source for another canvas or an HTML element.
      * @param type The standard MIME type for the image format to return. If you do not specify this parameter, the default value is a PNG format image.
      */
    toDataURL(type?: string, ...args: any[]): string;
    /**
      * Returns a blob object encoded as a Portable Network Graphics (PNG) format from a canvas image or drawing.
      */
    toBlob(_callback?: FileCallback, preferedtype?: string, ...args: any[]): void;
}

declare var HTMLCanvasElement: {
    prototype: HTMLCanvasElement;
    new(): HTMLCanvasElement;
}

/**
 * This interface is the callback used to obtain a File.
 */
interface FileCallback {
    function (file: File): void;
}

declare var FileCallback: {
    prototype: FileCallback;
    new (): FileCallback;
}

**Comment by charlesprogrammr** [comment]
Kind of got messed up there, should be more like:
/**
 * This interface is the callback used to obtain a File.
 */
interface FileCallback {
    function (file: File): void;
}

**Comment by mhegazy** [comment]
PRs are welcomed. here is some documentation for adding new types to lib.d.ts: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes
