### ISSUE TITLE
`Partial<Record<L, T>>[L]` can not  be distinguished as possible `undefined`

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#45506]
# Bug Report

### 🔎 Search Terms

Partial

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/GYVwdgxgLglg9mABAfQOYFMoDUCGAbEdAHgBlF0APKdMAEwGdF6oAnGMVAGkQBUA+ABQBYAFCImcECwjoAXIgAKOFrHxEASughwWtUt359EAH0RgQePJ1Hi8cCPjmIS1sYjtx66APzyARnBweOg4YKIAlIgA3jaIMMCIAgCE9JLS6JExbuIsmFJgANyxAL6xwVCIAG74hIgAvBJSMgDadg7BALpFbvGJ1QTo9Q3mlogAZGPugV6ZseL9tQD0i0wAFpJ4tIh+g+C06MDs6LQloqUiQA)

### 💻 Code

```ts
function _getValue<L extends string, T>(
  source: Partial<Record<L, T>> | null,
  locale: L,
  loose?: boolean
) {
  if (!source) {
    return;
  }
  let value = source[locale];
  if (value == null && loose) {
    value // should be undefined
  }
}
```

### 🙁 Actual behavior

As title and code comment

### 🙂 Expected behavior

As title and code comment

---

related https://github.com/typescript-eslint/typescript-eslint/issues/3755#issuecomment-901514405

**Comment by RyanCavanaugh** [comment]
This isn't a defect. `Partial<Record<L, T>>[L]` is a valid description of `value` here. Keeping the type higher-order generally improves assignability, and given how control flow works, narrowing to `null`/`undefined` here would create problems after the `if` branch.

**Comment by JounQin** [comment]
> The type of value is reported by TS exactly as you see in the screenshot.
TS reports it to us as a unique type - Partial<Record<L, T>>[L].
>
> It does not report it to us as T | undefined - it just chooses not to resolve the complex generic type.
> I had a quick look and there doesn't seem to be an API available which supports resolving this.

@RyanCavanaugh Is there any possible to resolve the usage case in `typescript-eslint`?
