### ISSUE TITLE
Support `Array.prototype.at`

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#45512]
There is a new method being added for `Array`: `at`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

I think typing this in a way that `undefined` is returned would allow a gradual adoption of the `noUncheckedIndexedAccess` rule:

```ts
at(index: number): T | undefined;
```

**Comment by MartinJohns** [comment]
> I think typing this in a way that `undefined` is returned would allow a gradual adoption of the `noUncheckedIndexedAccess` rule:

I don't see how this is related to `noUncheckedIndexedAccess`. The function returns an explicit `undefined` if the index does not exist.

**Comment by bpasero** [comment]
> I don't see how this is related to noUncheckedIndexedAccess. 

Being in a codebase that would produce hundreds of compile errors when `noUncheckedIndexedAccess` is enabled, adopting `Array.at` would allow to gradually adopt this to the point where `noUncheckedIndexedAccess` could then be enabled by default.

**Comment by SimonSchick** [comment]
You can always just add `!` null assertions to your array indexing, and gradually remove it, `at` shouldn't be used as a migration strategy imo.

**Comment by bpasero** [comment]
👎  For me, using `!` is like using `any` and I stay away from it unless there is really no other way.

**Comment by FelipeSharkao** [comment]
The biggest thing of Array.prototype.at is the possibility to use negative indexes. `array.at(-1)` is way clearer than `array[array.length - 1]`.

**Comment by Ethan-G** [comment]
For impacts: I went to use .at() today only to discover it's not supported yet.

**Comment by djmisterjon** [comment]
ho i lost so many time to try understand ! 
![image](https://user-images.githubusercontent.com/24865815/135762716-cfe66407-143b-414e-9c13-34726e124c07.png)


So It not yet added ! ?

**Comment by MartinJohns** [comment]
> Also linking to #44656 which this should probably be a part of

@orta You probably mean #44571.

**Comment by PabloLION** [comment]
I'm with `typescript@4.5.3` yet still having the same problem as @djmisterjon did. 
In the [playground](https://www.typescriptlang.org/play?#code/DYUwLgBAhgvA2gBgDQEYC6AoKA6KYAUAtCgJRA) it shows the same. How should I configure TS to suppress the error?

**Comment by PabloLION** [comment]
It seems I would have to wait until es2022 lib comes out?

**Comment by djmisterjon** [comment]
it added in 2022 lib
![image](https://user-images.githubusercontent.com/24865815/145734841-95f2e7e9-8f45-4a31-a03e-9a1c6aa61907.png)

**Comment by PabloLION** [comment]
I can't get ES2022 lib in my TSconfig with 4.5.3.. I'll wait for 4.6

**Comment by djmisterjon** [comment]
> I can't get ES2022 lib in my TSconfig with 4.5.3.. I'll wait for 4.6

ho you may true, i using `4.6-dev` in my workspace
![image](https://user-images.githubusercontent.com/24865815/146097255-89327504-eb8c-4c8b-9e62-dfec3a3b11bd.png)

**Comment by hochan222** [comment]
Thanks to those who raised the issue in the first place!

**Comment by PabloLION** [comment]
As for now, this functionality is supported by `typescript@4.5.4`, while setting the `tsconfig.module` to `es2022`.

**Comment by RebeccaStevens** [comment]
Would it be possible to change the return type of `at` for tuples?
For example make it so that `([1, 2, 3] as const).at(1)` will be `2` rather than `number | undefined`?

Or would this be too difficult considering that we'd need to take into account how negative indexes work?

**Comment by djmisterjon** [comment]
> 

hum yes , maybe they will need change the way how the generic share value.
Maybe try open a new post 
Here a hack solution where is work !
```ts
interface ReadonlyArray<T> {
    /**
     * Returns the item located at the specified index.
     * @param index The zero-based index of the desired code unit. A negative index will count back from the last item.
     */
    at<U extends number>(index: U): this[U] | undefined;
}
```

**Comment by PabloLION** [comment]
I agree with @djmisterjon 's idea on new post.
But here's the code I used. `const a = (([1, 2, 3] as const).at(1 as const))!`
BTW @djmisterjon I find your "hack solucion" doesn't work. maybe you used a `T` and a `U`?

**Comment by PabloLION** [comment]
The `!` I used was for the `at()` method cannot check if the element exists, so a `| undefined` is always deduced. I remembered that this problem is reported.

**Comment by djmisterjon** [comment]
> 

i dont know what to say, worked on my side with the hack

![image](https://user-images.githubusercontent.com/24865815/151673558-92388b30-3224-45d4-917d-c4c7ee26bf42.png)
And if you remove `as const` it become number
![image](https://user-images.githubusercontent.com/24865815/151673590-512a1ed7-3a1e-4b50-bfba-dc841a12381e.png)

So for me its should natively support this without manual hack.

**Comment by PabloLION** [comment]
I think it's working correctly. TS deduces that the type of `[1,2,3]` is `number[]`, like `[]` as `never[]`. What do you suggest here..?

**Comment by MartinJohns** [comment]
@djmisterjon That's not a hack, that's the expected and desired behaviour.

**Comment by djmisterjon** [comment]
> 

...heum ,hi, i think you don't understand the meaning of the word hack in this context.
Hack mean `bidouillage` and not hacking.
**Hack your code or hack this code** can mean **add, edit or modify**
Modify (hack) the native code provided by default to test a new behavior.
