### ISSUE TITLE
Intl constructors missing formatToParts type signature

### ISSUE THREAD

**Issue by ryzokuken** [microsoft/TypeScript#45510]
# lib Update Request

## Missing / Incorrect Definition

The `formatToParts` method (corresponding to each `format` method) on each `Intl` formatter constructor is not included in the type definitions.

## Sample Code

```javascript
new Intl.NumberFormat().formatToParts(Math.PI)
```

## Documentation Link

The following methods exist: https://developer.mozilla.org/en-US/search?q=formatToParts

**Comment by MartinJohns** [comment]
Duplicate of #41299. Used search terms: `formatToParts`

If you target `ESNext` you have support already.
