### ISSUE TITLE
4.2.3 Regression: Type with optional properties not safely asserting with `undefined` in their unions

### ISSUE THREAD

**Issue by frank-weindel** [microsoft/TypeScript#45523]
# Bug Report

Sorry I don't feel like I have the proper TypeScript vernacular to describe this issue in words very well. So any help there will be highly appreciated! See example below.

### 🔎 Search Terms

optional property, properties, Record, type assertion, indexed accessor

### 🕗 Version & Regression Information

- Via playground testing, the expected error occurs in TS <= 4.1.5, but stopped occurring in TS >= 4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noPropertyAccessFromIndexSignature=false&ts=4.2.3#code/C4TwDgpgBAsiAq5oF4oG8CwAoKUCGAXFAM7ABOAlgHYDmANFAPSNQASA9gG4RlSiRFSlWtlwAjAPxEqAVwC2Yng2ZsuPPkmnzFvAD5QZVACYQAZtQhHRUAMZSS5avSYsO3XvwiDHtKPsMm5lSW1kb2Qk4uqu4aAg7CNH4GxmYWVlgAvgDc2Ng27FSkUHIgAPJiAFZEcIiQUKiYOPhEAOSceAA2MhAtdNZiRACMAEwAzH1NNkQBqcHp2blY+YXAUGDsFexEAEoQ+WRGADwRtAwnifqyCjwAfPXFZZVZUQB0b1AAFAAyFlAAggBKbCMABU2AAwuw5GAKB1oDwyOxeBAAB6QGzASwMMQyVZGdgQYhUFqrAAWeDAkCoUGoUFqEAAyjZKGBVjdUAAWF7DF6jAiLelQFo1JAtGnEKBUdirPDEYgUGhUPBiOF8dixaAtXb7I7nM4+C6S7S3FovawABURkDIoCFYjFFAl1Hy0LwwAoKugAHcKMBSTSUiiSAqlcAZGQIGamrhBS0rjokjMgpYHRKpTK5SHlargOrPELzkl4zxTdZcDGkEKk2lU5LpfhM4rs9BcxqCwai8ayKaPmNhsMgVgQYxFuUKntgC8ANYQEDED7rTYAl6mJEAUTwNlJHxnIHqd0auGWRXaHXui-YAG1dwBdZ4qTzsUxQU-i7wJTvXXhvF6fH7BKAACFByPApiHYOEXg6dgaA+U8ARyTJB2BFhIUKCDoHYXEwFxfksBUAAiU9ugIlCoBGUYyOrOZy1ouioEOABaZjGOSQI0nFAMXTAN0PVVH0-U+QtLi7AEAEIoB-P9fnBAEgA)

### 💻 Code

```ts
type MyType = {
  a: string, // Hover type: string
  b?: number, // Hover type: number | undefined
  c?: string, // Hover type: string | undefined
  d?: string // Hover type: string | undefined
};

const myObj: MyType = {
  a: 'value',
  b: 123,
  c: undefined
};

const pojo: Record<string, string | number> = myObj; // ... (Line A)
/*
Compile error expected, but doesn't happen in TypeScript >= 4.2.3:

Type 'MyType' is not assignable to type 'Record<string, string | number>'.
  Property 'b' is incompatible with index signature.
    Type 'number | undefined' is not assignable to type 'string | number'.
      Type 'undefined' is not assignable to type 'string | number'.(2322)
*/

Object.keys(pojo).forEach(key => {
  const val = pojo[key]; // typeof val is: string | number ... (Line B)
  console.log(val);
})

// Console output:
// "value"
// 123
// undefined             <---- undefined is incompatible with (string | number)! ... (Line C)
```

### 🙁 Actual behavior

No compile error on the assignment on Line A. Hence an undefined value can emerge from a `Record<string, string | number>` (Line C)

### 🙂 Expected behavior

The following compile error is expected on the assignment on Line A.
```
Type 'MyType' is not assignable to type 'Record<string, string | number>'.
  Property 'b' is incompatible with index signature.
    Type 'number | undefined' is not assignable to type 'string | number'.
      Type 'undefined' is not assignable to type 'string | number'.(2322)
```

This will inform the developer to either add `undefined` to the Record value union, or find another way to fix the error.

**Comment by fatcerberus** [comment]
This looks like a use case for `exactOptionalPropertyTypes` (TS 4.4, currently in beta), which would prevent the assignment to `myObj` due to the explicit use of `undefined` for an optional property.  That being said, `undefined` can already emerge from a `Record<string, T>` even without this pitfall:

```ts
console.log(pojo["arglbarghlarggggg"]);  // undefined, no compile error
```

...which is why `noUncheckedIndexedAccess` exists (and why `val` has `undefined` in its type in your playground).

**Comment by RyanCavanaugh** [comment]
What @fatcerberus said; the desired behavior is achieved with that configuration (EOPT on, NUIA on).

**Comment by frank-weindel** [comment]
> This looks like a use case for `exactOptionalPropertyTypes` (TS 4.4, currently in beta), which would prevent the assignment to `myObj` due to the explicit use of `undefined` for an optional property.

> What @fatcerberus said; the desired behavior is achieved with that configuration (EOPT on, NUIA on).

Interesting, but wouldn't this still be considered a bug if it worked prior to 4.2.3? I'm glad there's a new option to cover it in 4.4, but confused why there's an option in 4.4 to fix something that broke in 4.2.3.

> ...which is why `noUncheckedIndexedAccess` exists (and why `val` has `undefined` in its type in your playground).

Ahh yes, I did turn that on in the playground later while trying to find a solution. Originally it was off. But that option shouldn't be needed at all in this specific case.

**Comment by frank-weindel** [comment]
So I tried enabling both `noUncheckedIndexedAccess` and `exactOptionalPropertyTypes` in 4.4 and it does not have the effect that I'd expect. 

1. First, just enabling it with the [code I posted](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noPropertyAccessFromIndexSignature=false&exactOptionalPropertyTypes=true&ts=4.4.0-beta#code/PTAEDsHsFVwYwBYFM4GskBMCS4NIB6YCCccSAzuaJOADSgECGcALgPIAOLAljYwDYAFAE6QOSYSwCeAFSniqNALAAoVdPGgAsrPlJQAXlABvVaFCMAXKHIth3cAHN6IUAAlIANwmgNSa7b2TmagAEYA-NbgAK4AtqESLmAe3sK+elFxCcIhcJE2dg7OoK4pPn4BhcEq5hj5gUUlyV7lGQVBjqoAvgDcqqpwNLagsVJsoQBW1jpymkamNRbWAOSeAtFIy7QhodYAjABMAMzbi3DW0bhIAGYOmE2gADwAtK+gAKL44qz3EqJpcEY0XI91CUgY+GY7C4vHAAhEYgk0lmFG6fTUKkG4GGHEgE0g1gASihIMIMI8Gk56JTHKAAD4QLISAB8hhGY0mPQeADpeaAABQAGTuoCIAEpVMAAFSqADCkFiHG4-H0f1JBWV-Ah3xYmHooWiLFAGEgFHAyyNCEYHHE4FADlAKIAynB7FxQMyjAAWbkHblHSz9FQo0DLGZ6Zb2qhQI2MSjcRxw0Iq3yQdKaZbEwZkilVYo0+mM+Is5bckII8SScHLUKR7hUByDRWMHjJ-QAd24LAQ9qu+BsCbhLGiwiQZcW5hDyxixbSDMueFu4EwdejkFj8cTjDbqfT+mWBYZM+ypZC5knelDC5udwwq4g64sm6TKZYab8ocPRZP3P5xwOBwSioUrAEG4wTCgLDcugUjkPyuL4mK3LXKS7zMAg-IwYYrILOYWLDGsWpGAhkAANowQAulyrh+JA1ygIRUaVB0hbHj485XEu9z8teXEYBYGB4Pxb6gJcsLUOA-DggkgLAvodEPrAiAoOg2B9sQpAUOQYqgLy3ICsKy6gAAQkBeFDJAKrcvwkCOPyhFiuiXRAZKYDytilnyYaHCGoGKiuAARIRGwBa5oCHEcYW8be56xXFTyvG8uqIOA3CAvwUmgGwADSD7thJmUyUCILUPRUBKcgaCYDgeCEBgJBkJQ+qGqAhn6EQUa+MgoCjgIUbkBsul8m1oCykAA) causes a compile error because of my assignment of property `c` as undefined on line 13. That makes sense based on what `exactOptionalPropertyTypes` is designed to do. Okay.
2. If [change my code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noPropertyAccessFromIndexSignature=false&exactOptionalPropertyTypes=true&ts=4.4.0-beta#code/PTAEDsHsFVwYwBYFM4GskBMCS4NIB6YCCccSAzuaJOADSgECGcALgPIAOLAljYwDYAFAE6QOSYSwCeAFSniqNALAAoVdPGgAsrPlJQAXlABvVaFCMAXKHIth3cAHN6IUAAlIANwmgNSa7b2TmagAEYA-NbgAK4AtqE+AD6g0bhIAGYOmC5gHt7CvnpRcQkFyal4meCYIXCRNnYOjqDlaVXZoK55Pn4BjU4tKW1ZGCEY9YFNgxUZI525Xj1FDUHNrZUjqgC+ANyqqnA0tqCxUmyhAFbWOnKaRqYq5lagAOSeAtFIL7QhodYAjAAmADMP0eoDg1hm7VGKl2+xUh3Axw4kAukGsACUUJBhBgADyTJz0IlrCAlCQAPkMJzOlx281AADoWaAABQAGSyoCIAEpVMAAFSqADCkFiHG4-H0ElEBQAyjIsByOQx8OJWB1QtEWKAMJAKOAXrqEIwOOJwKAHKBbkh5XB7FxQJSjAAWJmApnAywI22vG56F5WqhQXWMSjcRzgRihaW+SCFTQvbGHPGE-rOFZTZIxeJUl5MkIiMQSaSvUJB7hUByHCWMHix-QAd24LAQVrS+BskejLGiwiQhfB5j9L1zpWmw2qGErIcgYYjUZjcZYCb8r1Jg3HEgLIXMI70r2hI1nEHnFkX0cb8cT+hem5zFOEBbZIMBgP5KkFwAR5wuKBYJl0Ckcg2VRdFeSZdJcQAUWYBA2WAwxqQecwkWOd5+BpcDIAAbWAgBdBlXD8SB0lATDgz6VYtyfScNmndlj0YxgMDwDAb1SXhLRofgpDCFBGGich9DIs9YEQFB0GwTtiFIChyF5ZlWU5bkACFPzQo5IGlJl+EgRw2Uw3k9jhT8BTAMVkR00SdQ4HUfRUVwACJMM+ZyLNAIFgU85jMH3ALAtAfEAFowpC3wUAQcBuDgAQ+NANgAGkzybahwAShI4uE0TyKgCTkDQTAcDwQgMBIMhKHobVdS5aoeWDXxkFAAcBGDchPmUplQDq-QRSAA) to explicitly allow `undefined` as a value for optional properties b, c, d, it now compiles, but now we're back to the same essential place I was at in my original bug report. Line A should be reporting an error due to `undefined` not being in the union for the Record  value.

```ts
// noUncheckedIndexedAccess on, exactOptionalPropertyTypes on

type MyType = {
  a: string, // Hover type: string
  b?: number | undefined, // Hover type: number | undefined
  c?: string | undefined, // Hover type: string | undefined
  d?: string | undefined // Hover type: string | undefined
};

const myObj: MyType = {
  a: 'value',
  b: 123,
  c: undefined
};

const pojo: Record<string, string | number> = myObj; // ... (Line A)
/*
Compile error STILL expected, but doesn't happen in TypeScript >= 4.2.3:

Type 'MyType' is not assignable to type 'Record<string, string | number>'.
  Property 'b' is incompatible with index signature.
    Type 'number | undefined' is not assignable to type 'string | number'.
      Type 'undefined' is not assignable to type 'string | number'.(2322)
*/

Object.keys(pojo).forEach(key => {
  const val = pojo[key]; // typeof val is: string | number | undefined (undefined added to union only because of noUncheckedIndexedAccess) ... (Line B)
  console.log(val);
})

// Console output:
// "value"
// 123
// undefined             <---- technically OK now only because of noUncheckedIndexedAccess, but Line A is the real issue ... Line C
```

**Comment by frank-weindel** [comment]
@RyanCavanaugh @fatcerberus Please see the above if you get a chance. The suggestion solution does not solve the core of the problem.

**Comment by andrewbranch** [comment]
> I'm not aware of any release documentation saying this was regressed intentionally.

https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#relaxed-optional-index-rules

**Comment by fatcerberus** [comment]
Hmm, I wonder if `exactOptionalPropertyTypes` should disable that behavior.

**Comment by andrewbranch** [comment]
I think `exactOptionalPropertyTypes` makes that behavior more robust—it indicates that the optional properties represent keys that are either present or missing, but not `undefined`-valued, just like an index signature represents keys that could be present or not.

**Comment by fatcerberus** [comment]
> it indicates that the optional properties represent keys that are either present or missing, but not undefined-valued, just like an index signature represents keys that could be present or not.

That was my point - the mentioned change makes it possible to explicitly assign `undefined` to a `Record` type without `undefined` in its value slot, even with exactOptionalPropertyTypres enabled.  Seems inconsistent.

**Comment by andrewbranch** [comment]
Oh, you’re talking about properties that are declared optional _and_ have `undefined` in their property type signature? Yeah, that could be worth changing. I feel like I commented something about that on the exactOptionalPropertyTypes PR, actually.
