### ISSUE TITLE
resolvedTrueType and resolvedFalseType of conditionType are not resolved when used in the compiler api

### ISSUE THREAD

**Issue by Zzzen** [microsoft/TypeScript#45537]
# Bug Report

### 🔎 Search Terms

resolvedTrueType not resolved, resolvedTrueType not defined, conditionType not resolved

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because typescript version is not configurable in ts-morph.

### ⏯ Playground Link

https://codesandbox.io/s/charming-easley-27zik?file=/src/index.ts

### 💻 Code

```ts
import { createProjectSync, ts } from "@ts-morph/bootstrap";

const project = createProjectSync();
const mainFile = project.createSourceFile(
  "main.ts",
  `
    function f<A, B, C, D>() {
        return null as A extends B ? C : D;
      }
    `
);
const program = project.createProgram();
const typeChecker = program.getTypeChecker();
const func = mainFile.statements[0] as ts.FunctionDeclaration;
const signature = typeChecker.getSignatureFromDeclaration(func)!;
const returnType = typeChecker.getReturnTypeOfSignature(
  signature
) as ts.ConditionalType;

const isConditionalType = !!(returnType.flags & ts.TypeFlags.Conditional);
const checkType = !!returnType.checkType;
const extendsType = !!returnType.extendsType;
const resolvedTrueType = !!returnType.resolvedTrueType;
const resolvedFalseType = !!returnType.resolvedFalseType;

console.log({
  isConditionalType,
  resolvedTrueType,
  resolvedFalseType
});

```

### 🙁 Actual behavior

It outputs `{isConditionalType: true, resolvedTrueType: false, resolvedFalseType: false}`. But according to the public definition, both `resolvedTrueType` and `resolvedFalseType` should have been resovled.

```ts
export interface ConditionalType extends InstantiableType {
    root: ConditionalRoot;
    checkType: Type;
    extendsType: Type;
    resolvedTrueType: Type;
    resolvedFalseType: Type;
}
```

### 🙂 Expected behavior

It outputs `{isConditionalType: true, resolvedTrueType: true, resolvedFalseType: true}`.

**Comment by andrewbranch** [comment]
I think those properties should have been written as optional. Changing them to optional currently produces no errors. I’d support changing them if someone opens a PR.

**Comment by Zzzen** [comment]
And expose `getTrueTypeFromConditionalType`/`getFalseTypeFromConditionalType`?

**Comment by andrewbranch** [comment]
No, I think those are meant to be internal and their signature could change.

**Comment by jbrown16** [comment]
@andrewbranch I have a draft PR available that I believe fixes this issue, as per your suggestion above. Let me know whether you think this change is adequate.
#45838

**Comment by andrewbranch** [comment]
@Zzzen, feel free to open a new issue requesting to expose `getTrueTypeFromConditionalType`/`getFalseTypeFromConditionalType`, I’m just not sure off the top of my head whether we’ll feel good about accepting it. But no harm in discussing.

**Comment by olsonpm** [comment]
Is there a recommended way to resolve the true and false conditional types without those functions?  The use case I came across was a type testing tool.

edit: nevermind - it seems the typescript api is frozen in prep for ts 7, at which this discussion becomes obsolete.
