### ISSUE TITLE
Automagic data properties in JavaScript classes

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#4554]
The ES6 spec for classes doesn't include properties making the code below valid JavaScript (and invalid TypeScript) code

```javascript
class Cat { 
  constructor(name) {
    this.name = name;
  }
  
  speak() {
    console.log(this.name + ' makes a noise.');
  }
}
```

When feeding code like this into the TypeScript compiler you get an error about ```this.name``` not being defined. TypeScript should be able to detect that this is a JavaScript class (```*.js,*.jsx```-files) and (1) not mark the property access ```this.name``` as error and (2) offer tooling support for the data property (IntelliSense et al)

**Comment by danquirk** [comment]
We have another issue somewhere tracking adding support for this style of pattern (ie enumerate assignments to ```this``` in the constructor body and consider them instance properties implicitly) but I can't find it at the moment.

**Comment by billti** [comment]
#4790 covers this and other topics for better TypeScript inference of < ES6 style JavaScript.

**Comment by RyanCavanaugh** [comment]
#4955
