### ISSUE TITLE
Honor compilation target when checking JavaScript

### ISSUE THREAD

**Issue by jrieken** [microsoft/TypeScript#4556]
There is a code branch for [JavaScript specific checks](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L2796) but it doesn't honour the target defined in the compiler options. When `ES3` or `ES5` is being used these things should be reported as errors as well
- use of arrow function
- use of `const` and `let`
- use of default parameter values
- short hand object literal notation
- ...

Also, I wonder if this code path can be executed in addition to the semantic analysis instead of instead.

**Comment by mhegazy** [comment]
I think `target` is the wrong property here. we need something else to mean `sourceVersion` or something along these lines.

**Comment by sheetalkamat** [comment]
With #5471 we would be emit the es3 and es5 syntax of javascript input file for es6 syntax hence these are not errors any more

**Comment by niieani** [comment]
instead of `target` or `sourceVersion`, perhaps: `standard` could be used - indicating what standard the code should comply with.

**Comment by RyanCavanaugh** [comment]
It doesn't seem like anyone needs this functionality. A curated list of lint rules would suffice if otherwise.
