### ISSUE TITLE
`import from "."` doesn't reference folder if folder and file have same name

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/TypeScript#45563]
# Bug Report

### 🔎 Search Terms

import folder file refactor

### 🕗 Version & Regression Information

4.4.0-insiders.20210805, next, and the 4.3.x branch

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ...?

### ⏯ Playground Link

Can't reproduce in playground as it has to do with multiple files and imports

### 💻 Code

This has to do with file imports, so I made a minimal repro:

https://github.com/MarkKahn/ts-import-refactor-bug.git

### 🙁 Actual behavior

I was refactoring a file, `module.ts` into a directory, `module`.  I created `module/index.ts`, and in `module/submodule.ts` I had written: `import { otherSubModule } from '.'`

TS threw an error saying `Module '"."' has no exported member 'otherSubModule'.ts(2305)`

After some banging my head on the wall I figured out that `from '.'` wasn't referencing `./index.ts`, but instead was referencing `../module.ts`

### 🙂 Expected behavior

`import from '.'` should reference the current folder, always.  This is likely only a bug that would be triggered when refactoring code as I can't think of a use case for a file and folder to have the same name and be a valid structure.

**Comment by andrewbranch** [comment]
Your minimal repro doesn’t seem to be a repro—it doesn’t have any imports from `"."`

**Comment by MarkKahn** [comment]
whoops, I hit undo one too many times before committing.  Fixed, sorry

**Comment by andrewbranch** [comment]
Thanks! Now if you don’t mind, can you restate your actual behavior and expected behavior in terms of the file names and identifiers used in that repro? I had a little trouble following your hypothetical example.

**Comment by MarkKahn** [comment]
Sure.

`c.ts`
```
import { b } from '.';
```

I would expect `'.'` here to look at `index.ts` in the same folder.  It doesn't, it references `../a` instead.

**Comment by MarkKahn** [comment]
Also I just tested this in node using `module.exports` and `require`, and `require('.')` does reference the folder.

And I learned that es6 modules oddly don't officially support directory imports...

**Comment by Jamesernator** [comment]
So in Node's official ESM support yes you can't [import directories](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions), you have to import the file you want directly or use a package and [`"exports"`](https://nodejs.org/api/packages.html#packages_exports).

Technically TypeScript doesn't support Node's ESM behaviour at all atm. Although the issue you're getting is a TypeScript specific issue as it only recognizes CommonJS style imports atm. So yeah `import foo from '.';` should resolve the same as `import foo = require('.');` in TypeScript's current resolution.

Proper ESM support with the same behaviour as Node's esm mode is [expected in the next major version of TypeScript](https://github.com/microsoft/TypeScript/issues/45418) (but it could be delayed as its a big job). In this case it should be an error as per Node's official ESM resolution.
