### ISSUE TITLE
"Convert to template string" interprets escape characters

### ISSUE THREAD

**Issue by Elias-Graf** [microsoft/TypeScript#45562]
# Bug Report

### 🔎 Search Terms

Convert to template string, escape

### 🕗 Version & Regression Information

Not sure but it happens in 4.3.2 and in 4.3.5

- I was unable to test this on prior versions because the playground site always says "no refactorings available" :(

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEQIYwKYBVQbgXzgDMoIQ4AiAGwFcAPCAOwoG4AoNgegCpu25ucADIQA5gGc4IDOPGpRMuDAhxxMACYQaMAHRwsACzwxcS0wHdgVKnABGeMFAxgMjdRnVxUbygB1mcAAUVMCMGPyCtk6oANYAlF5gLm4eOhFwAAJgqFCo5CDiEkoq9nCOoZiegSA0VCZgVHjSsvKKltZ2eABWEKEedgCelMMA2hjgMAPpalChogC6cWkCnGwYdJCwcO5EqLXwRDSMAMYmTHBUYoE6NwUSAFyqMLOMoiOLjwBuvZ4I-GWkY4ycQ6NSabQ6cyzTCBNCYHDSHSMCDmQJLZQASQAygB5NFwADUfhgFEJUkKIJ6oUCpIoCSJFH8dPY+CAA)

### 💻 Code

```ts
import { DateTime } from "luxon";

/**
 * Logs messages to stdout. The time time will be prepended and "\n" (line
 * break) appended.
 * @param msgs to be printed (multiple messages will be joined by " " [empty
 * string]).
 */
export default function log(...msgs: string[]): void {
  process.stdout.write(DateTime.now().toISO() + "\t" + msgs.join(" ") + "\n");
}
```

### 🙁 Actual behavior

The escaped characters get interpreted. 

![Peek 2021-08-24 15-54](https://user-images.githubusercontent.com/46671625/130629475-6c8714b4-647e-474f-bcc6-4a7dcf8511f8.gif)

### 🙂 Expected behavior

It should not interpret escaped characters.

Possible related to https://github.com/microsoft/TypeScript/issues/40625?

**Comment by MartinJohns** [comment]
That sounds like #40625.

**Comment by andrewbranch** [comment]
Indeed, it works correctly in the nightly.

**Comment by Elias-Graf** [comment]
Okay perfect, in case you didn't notice I mentioned the issue in my issue. But I thought as it was from 2020 and closed, that it might be a bug that re-appeared. Thanks for the awesome work guys :)!

**Comment by MartinJohns** [comment]
> in case you didn't notice I mentioned the issue in my issue (right at the bottom)

I noticed. You mentioned possible related, I said it is. :-)

> But I thought as it was from 2020 and closed, [..]

Well, it is closed and it is from 2020. But it was just recently closed. :-)  
Most of the times the team adds the corresponding milestone for the release:
![image](https://user-images.githubusercontent.com/5269069/130754886-155685b0-46f0-4082-8f2b-9cfca12f0a57.png)
