### ISSUE TITLE
Can't narrow T | undefined into T with a falsy check when using --noUncheckedIndexedAccess

### ISSUE THREAD

**Issue by viell-dev** [microsoft/TypeScript#45570]
# Bug Report

When using `--noUncheckedIndexedAccess` it seems impossible to narrow, for example, `string | undefined` into `string` when using a variable key/index when accessing either objects or arrays. Unless you first assign it to a new variable and then doing a falsy check on that variable instead.

### 🔎 Search Terms

noUncheckedIndexedAccess
object
array
key
index
undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about noUncheckedIndexedAccess.
- Tested in 4.1.5, 4.3.5 and 4.4.0-beta.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.3.5#code/PQKhFgCgAIWgVAngBwKbQHYEMBOOD2A7gJYYDmm+ALtIfjgNakUlUAW0AtJxvgKoYAxm1SCGqACYBJDBNQAPSQEFBg1AGd1ALiiwu0AOoiM0AK7rm0LNABuuYlgBGAG3TjE0KviuqN6qyb4jgBWolQAdLpwnIbGZhbkVrb2Tq7QpHLynt5YvpoBVnhYiJEwIMBQUKDQAMJYGADkNNh4RNDqVDiWAD5msqgAZqSS2e2dlqwcdl2pbqgepNBBoYJU6uGwFZCkVKg4A7noMpkAysRk2FSmOOgA3tAA2u5aY13kALovHW8UAL4A3JVIIJ8BgOksQi9jgozhcsFcbtAALzQe4DfD4F4NRy4BrQAFQEFgmjuZHQBro-ANQGQKDEAbQAAUpMWy2gADJ2RDgk95u8AJSo3TQEVE8F2ZymdAo5a8xDvf7QYDAV49PpyIYYSRQX5A+lMlmBEIcrmy9zvaAAQhRGFMzmcgtuwtFoPFWEl0u5coVSpV3zVpn6mu1kF1tO2DOZ83SRuCJs8KFQ+AZZr5VqRKIagY1wwkDUdzugYpoEqlZNT8sVytViV62cGuZ1QOrACVUFhNOcMJZ2OgKxb6hIiyIxD2RJhUIRkjMXOg6Ix-Ox8KYyGxSvqowtYwWYCKi66aABbYqOVAANXdZZlIW9Vb941r6obWokhcLG+PiFPF49O73--3Ylkg9MlP2-S9UDvGsyBpf8wzDKo4BOLBD3QdhLEWXAcGKfxJiSaYHFnGNMg2cpCQPQocDJB4KQxBoFXIoCMgUMkAAYaTpSNmKyTC8HjLCHm4gUhV3F0gNLT0BKEqD-Ufetg1fUM9S4-oeJMLD+LwQTVIta1MDtB0RP-YtgKvSjtMyH1q1kig6yDRslPDDduJjSj4yoRNk3MoT00zeTc3zIy9xMiSySknSZIfWynwUptw1bdtOwuMd0HCyyAiHYRRCYRJewnKcCNmWh6AYRc2GXVd1xUzJXKwv9goosDzwgsKtOk31oOgOycxfN9RPSSMmp-KV6oAwC3RAlEhogyKflgvd4KgIA)

### 💻 Code

```ts
// In objects
const obj: { [key: string]: string } = { foo: 'bar' };
const key = 'foo';
if (key in obj && obj[key]) { const value = obj[key]; } // value is string | undefined
if (key in obj && obj[key] != null) { const value = obj[key]; } // value is string | undefined
if (key in obj && typeof obj[key] !== 'undefined') { const value = obj[key]; } // value is string | undefined
// In arrays
const arr = ['foo'];
const index = 0;
if (index in arr && arr[index]) { const value = arr[index]; } // value is string | undefined
if (index in arr && arr[index] != null) { const value = arr[index]; } // value is string | undefined
if (index in arr && typeof arr[index] !== 'undefined') { const value = arr[index]; } // value is string | undefined
```

### 🙁 Actual behavior

It's impossible to narrow `obj[key]` from `string | undefined` to `string` without first assigning it to another variable and then checking if that variable is `undefined` instead.

### 🙂 Expected behavior

Expected to be able to narrow `obj[key]` from `string | undefined` into `string` with a simple falsy check.

**Comment by MartinJohns** [comment]
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by viell-dev** [comment]
Ok. I'll close this one then.
