### ISSUE TITLE
checker.ts :: checkModuleDeclaration(): Redundant type guard erroneously narrows node type to 'never'

### ISSUE THREAD

**Issue by rafaelsofizadeh** [microsoft/TypeScript#45572]
# Bug Report

I have a ready, very easy fix for this bug, so if you indeed recognize this as a bug, **please assign it to me**, and I'll submit a PR.

### 🔎 Search Terms

checkModuleDeclaration node type never
checker.ts
isExternalModuleAugmentation
Property 'parent' does not exist on type 'never' (ts2339)

### 🕗 Version & Regression Information

 This is a logical bug in `checker.ts` that **should** arise in pretty much any TypeScript version that supports type guards/predicaments. However, since `isAmbientModule()`'s result is assigned to a variable, and control flow of aliased conditional expressions is introduced only in v4.4.0, this issue will only appear in v4.4.0+ (or any other version with  pull request https://github.com/microsoft/TypeScript/pull/44730)

Judging by related commits that I've found by using `git blame -L37720,37722 src/compiler/checker.ts` and 
`git log -L37720,37722:src/compiler/checker.ts`, the bug was introduced somewhere around [v2.8-rc](https://github.com/microsoft/TypeScript/releases/tag/v2.8-rc):

- https://github.com/microsoft/TypeScript/commit/4a963a26c37b6c23b1d8238da768cf2448f8ec25 – Dec 22, 2015, seems to be [v1.7.5](https://github.com/microsoft/TypeScript/releases/tag/v1.7.5) or [v1.8.0-beta](https://github.com/microsoft/TypeScript/releases/tag/v1.8.0-beta) – Added the `isExternalModuleAugmentation()` check (which **will become redundant** in the next commit)
- https://github.com/microsoft/TypeScript/commit/5e593acad9db40cd911a39c3b957dfabb7779c79 – Mar 6, 2018, seems to be [v2.8-rc](https://github.com/microsoft/TypeScript/releases/tag/v2.8-rc) – Added a type predicate to `isExternalModuleAugmentation()`, **which created a redundancy** with parent `isAmbientModule` check.

### ⏯ Playground Link

[Close recreation of the issue](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/PTAEFpNBlBDBbADgGwKagC4E9HoCaoDGysATrBgJYD2AdgM4SQBQqtArvDFrRrAB4BpSrTygA3s1DTQAQXgAjSmwwBZannZoAIkRLkqdADTMAvs2YhQAIgByG1NdD0M5WgHNUyLKHeUAbqiMsDaaKJSEFOjYuKAEAGYilIa0TqikpNSkzDHoACr2BKAAvBKgANYieABc3LwCwqKgpgDcOTjo8koq6po6emQUNLQlZZWitdA8fEJVAHRdyry9Wqi6xIMpzW2WYFCyhBjssMighA6gpKiImZqHw6DU8ZgAFuiU9PTsqEagAO7JF6geIjWgIIKgWCMERnN6EcrpOYYYJNdhUZDJZT0JH0CxWeikQjAc5IShoUjANFkzFBHHMeLsWj3OigD6LHoaVYACloDlqBQcAEparyih85IolmpOf0NgYHpIZJdUEdSCMAELUahoWC0LmqCgvOaZRl4fWG426vDUeBcwX2trmXbOQnEm2IMnpSnomnY5H0xnMkYfACi-Aw6TByBWaFk7Hc8BUQzoPL5oAFBGFoFF70Y7OWMrWA3lLMVMiuquD9Hz0r6qFTmdAADIm6BNdrULrzRgjSbRN3e1abXaHWY8WACUSSR7ycS4QjSHSGUytoR5zGi3Lk3qc-zCqhBRIpDJzgwMKzq5KVGGI2qThvRmyrwW6w2DzslZRnlyn91eDfI3vQtDzLJVpCsAA9KDjzA0ArAAYToVxtWBZBqD+SEoywehxSeSEMShVAxFPPBMToE5QFQfgbiCHC6EYGCwKsLlUDmdw5kwDpfGOUgxCuL5kHPehYECMQYRCfwyEoWAFDQQ8yHeXhbnYQgiMYpUrDobxWRGfwABY5gMgAGUAXgwDBEHoaoQD8Ht2AUOYSWAeAIkyegngwYA8g6aBCFIShEE8xAtGQYA9L0gB2ABmIz1JkKwAEk5lY0AFFQeIsnQfTDLmIzfhzUz0lzR5nlyUAAHIM1Qcq4vAsBZHiW9QGy4z8ouXDSq48qaw3dZ9G3GratZb9Q3DQDo0LOMEyTFI33tI9YNgqw8jebN2uhURUCIzDKLGu9TlbBA-3PeBCziYttyGpUK3YNU1oIOZxjwNpFuaSjkHodBQNeuCwHVIhYHYT6StefB2HCSII042IaNIyJE14WEiHKHTQEQBTEau+KwC-UAf0vY6N0PLG6sw4iXjJMQSd+4a8dG28ow3KaEb4FJBWpqwCphawvE+pwNiB4qCFvFzaG2jBqFS9A8LK6wxcCUhrGpm67pzR6qhexbzCVcxTCAA)

### 💻 Code

`checker.ts : line 37664`
```ts
function checkModuleDeclaration(node: ModuleDeclaration) {
    // ...

    // Control flow analysis of aliased conditional expressions 
    // (e.g. type guard result saved in a variable) are introduced
    // only in v4.4.0 https://github.com/microsoft/TypeScript/pull/44730
    const isAmbientExternalModule = isAmbientModule(node);

   // ...

    if (isAmbientExternalModule) {
        // Before v4.4.0, node here is of type 'TNode'
        // After v4.4.0, node here is of type 'AmbientModuleDeclaration'
        if (isExternalModuleAugmentation(node)) {
            // isExternalModuleAugmentation() contains a redundant isAmbientModule() check
        }
        else if (isGlobalSourceFile(node.parent)) {
        //                          ^^^^^^^^^^^^
        // Here, tsc v4.5.0-dev.20210824 (and all others) give an error:
        // Property 'parent' does not exist on type 'never'.ts(2339)
        // Because of the redundant check in if (isExternalModuleAugmentation(node)) ...,
        // control flows deduces node's type to be 'never'.

        // ...
        } else {
            // ...
        }
    }
    // ...
}
```

### 🙁 Actual behavior

Covered in the code examples/playground.

### 🙂 Expected behavior

Covered in the code examples/playground.

**Comment by andrewbranch** [comment]
I think your sources are out of date; this was fixed as soon as it became a problem. It now reads

```ts
const isAmbientExternalModule: boolean = isAmbientModule(node);
```

The compiler compiles itself in CI, so we automatically catch things like this as we go.

**Comment by rafaelsofizadeh** [comment]
@andrewbranch that doesn't really change anything about the issue, does it? The issue is not in the type definition of isAmbientExternalModule, it is in the intersection of `isAmbientModule()` and `isExternalModuleAugmentation()`, defined in `utilities.ts`.

The line `if (isExternalModuleAugmentation(node))` should be `if (isModuleAugmentationExternal(node))` instead, as `isExternalModuleAugmentation()` **already includes** `isAmbientModule()` check inside of it.

```ts
// utilities.ts:773
export function isExternalModuleAugmentation(node: Node): node is AmbientModuleDeclaration {
  return isAmbientModule(node) && isModuleAugmentationExternal(node);
}
```

I think the issue should be reopened. The bug is still there.
<img width="773" alt="Screen Shot 2021-08-25 at 17 35 52" src="https://user-images.githubusercontent.com/19387589/130830195-9f8973e0-12f3-41e5-87c5-9323e993c57c.png">
