### ISSUE TITLE
Type checking on generic interfaces are not throwing errors.

### ISSUE THREAD

**Issue by paulshir** [Microsoft/TypeScript#4558]
Sorry if this is a dupe. I haven't found any issues with this problem. The problem is occurring using generic interfaces.

When creating a variable with a type of generic interface (ISubscriber<IType1>) I can assign any ISubscriber<T> to it. I would expect this to fail.

When I create a variable with a type of a generic class (SubscriberBase<IType2>) and I try to assign any ISubscriber<T> to it an error is displayed as I would expect.

Is this behavior expected or am I missing something fundamental.

```typescript
interface IDatabaseEntry {
	_id: string;
}

interface IType1 extends IDatabaseEntry {
	name: string;
}

interface IType2 extends IDatabaseEntry {
	value: number;
}

interface ISubscriber<T extends IDatabaseEntry> {
	Subscribe(): void;
}

class SubscriberBase<T extends IDatabaseEntry> implements ISubscriber<T> {
	private object: T;
	constructor(object: T) {
		this.object = object;
	}
	
	Subscribe(): void {
		
	}
}

var type1 = <IType1>{
	_id: "type1",
	name: "Type 1"
}

var type2 = <IType2>{
	_id: "type2",
	value: 2
}

var base1Subscription: ISubscriber<IType1>;
var base2Subscription: SubscriberBase<IType2>;

base1Subscription = new SubscriberBase<IType1>(type1); // Expect No Error -> No Error
base1Subscription = new SubscriberBase<IType2>(type2); // Expect Error -> No Error

base2Subscription = new SubscriberBase<IType1>(type1); // Expect Error -> Error
base2Subscription = new SubscriberBase<IType2>(type2); // Expect No Error -> No Error
```

Also if create a class directly implementing the type of interface it doesn't throw an error.
```typescript
class Subscriber2 implements ISubscriber<IType2> {
	private object: IType2;
	constructor(object: IType2) {
	}
	
	Subscribe(): void {		
	}
}

base1Subscription = new Subscriber2(type2); // Expect Error -> No Error
```

Many thanks.

Paul

**Comment by SimonMeskens** [comment]
Typescript does not do identity. What this means is that it uses duck-typing to check type compatibility. If you want identity, you need to find a solution with `instanceof` and constructors or explicitly make your own solution, for example by doing something similar to JSON-LD or by using the new ES6 symbol spec, which isn't available yet in Typescript, but you can probably use an external library for that purpose.

**Comment by paulshir** [comment]
Thanks,

My ISubscriber type doesn't have any type T on it so it satisfies any method which has a subscribe on it.

Updating the interface to use the type throws the errors as expected.

```typescript
interface ISubscriber<T extends IDatabaseEntry> {
    object: T;
    Subscribe(): void;
}

class SubscriberBase<T extends IDatabaseEntry> implements ISubscriber<T> {
    public object: T;
    constructor(object: T) {
        this.object = object;
    }

    Subscribe(): void {
    }
}

**Comment by SimonMeskens** [comment]
Yeah, that works, because now, when duck-typing, the compiler detects the wrong type for `object`. Basically, you're now using the `object` property as a simple identity system. It's there to guarantee the identity of T.
