### ISSUE TITLE
useDefineForClassFields defaults to true in 4.2.4

### ISSUE THREAD

**Issue by KeithHenry** [microsoft/TypeScript#45584]
# Bug Report

### 🔎 Search Terms

`useDefineForClassFields`

### 🕗 Version & Regression Information

- This changed sometime between versions 3.7 and 4.2.4
- Upgrading the version of Typescript in Visual Studio 2019 introduced this issue

### ⏯ Playground Link
Same code compiles in VS Code and command lines, it breaks in Visual Studio 2019+Typescript 4.2.4 only

### 💻 Code
Use a `@decorator` on class properties or any code that is incompatible with `useDefineForClassFields: true`

Something like:

```ts
class MyClass {
    @myDecorator()
    myField: any;
}
```

Do not include `useDefineForClassFields` in your `tsconfig.json` at all.

Run Typescript compile.

When VS2019 with TS 4.2.4 compiles JS output includes class fields, something like:

```js
var __decorate = // ...autogenerated implementation

let MyClass = class MyClass {
    myField;
};

__decorate([
    myDecorator()
], MyClass.prototype, "myField", null);
```

When `tsc` 4.3.5 compiles _for the same `tsconfig` and source files_ it *doesn't* include class fields, something like:

```js
var __decorate = // ...autogenerated implementation

let MyClass = class MyClass {
    // No fields here
};

__decorate([
    myDecorator()
], MyClass.prototype, "myField", null);
```

Adding `useDefineForClassFields: false` works around the issue and makes the JS output consistent.

Property decorators are ignored (as per #35081).

### 🙁 Actual behaviour

JS output includes class fields (as if `useDefineForClassFields` was set to true) in VS2019+TS 4.2.4
JS output does not include class fields (as if `useDefineForClassFields` was set to false) in tsc 3.7 or 4.3

### 🙂 Expected behaviour

JS output should not include class fields unless `useDefineForClassFields` is explicitly set to true.

Whatever default `useDefineForClassFields` setting is should be consistent between tsc and VS2019+TS

**Comment by KeithHenry** [comment]
@andrewbranch I'm a little confused by this:

> the title is a false assertion and leaving it open may lead people to believe it’s true

My assertion is that `useDefineForClassFields` defaults to `true`.

However, @MartinJohns said:

> The default of `useDefineForClassFields` depends on your target. For `ESNext` or `ES2020` and above it defaults to `true`, which is the desired behaviour (to align with the ECMAScript standard).

Are you closing this because `useDefineForClassFields` _should_ default to `true` when `target` is `ESNext` ?

- It **doesn't** with `tsc` 3.7 (which [introduced it](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier))
- It **does** with VS2019+Embedded Typescript 4.2.4
- It **doesn't** with `tsc` 4.3.5
- It now **does** with `tsc` 4.4.2
- According to https://github.com/microsoft/TypeScript/pull/42663 it _should_ default to `true`.
- Which is what I'm asserting.

Where is this breaking change documented? Should or shouldn't it default to true?

**Comment by MartinJohns** [comment]
> It doesn't with tsc 4.3.5

Yes, it does. I just verified this behaviour.

**Comment by KeithHenry** [comment]
@MartinJohns apologies, it was a bank holiday over here in the UK and when I came back the issue was closed, there didn't seem much point working on reproducing the problem when the response was that it's by design, just undocumented.

**Comment by justinfagnani** [comment]
We keep having users who have broken projects because of this. It's very frustrating.
