### ISSUE TITLE
4.4 has incorrect output (.d.ts) when inferred from JSX proptypes

### ISSUE THREAD

**Issue by frehner** [microsoft/TypeScript#45593]
# Bug Report

### 🔎 Search Terms

proptypes
4.4 proptypes
prop types
proptype function

### 🕗 Version & Regression Information

- This changed between versions 4.3.5 and 4.4

### ⏯ Playground Link

[4.3 playground](https://www.typescriptlang.org/play?strictNullChecks=true&filetype=js#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4AFHMAFQE8wkBnObXAsOgWhmZsypNBAB2reAGUkAGyQY4AXjgAKAN4hGAMQCuYtMrhjds2QF8AlMoB8cdaThwiMXVDFwAPACNdMGOJw4gDCssBoANZK6qrWSnZaegYA-AB0seY2ABbAngD0vv7iNqTmpKQy8hipPBAMguwqDk6J+mgAXDR0TCysqZhtpeVIAB6U8AAmSJgoptJyCjBAA)

```.d.ts
declare function Select({ myFunc }: {
    myFunc?: any;
}): JSX.Element;
```

Now see the difference with [4.4 playground](https://www.typescriptlang.org/play?strictNullChecks=true&ts=4.4.0-beta&filetype=js#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4AFHMAFQE8wkBnObXAsOgWhmZsypNBAB2reAGUkAGyQY4AXjgAKAN4hGAMQCuYtMrhjds2QF8AlMoB8cdaThwiMXVDFwAPACNdMGOJw4gDCssBoANZK6qrWSnZaegYA-AB0seY2ABbAngD0vv7iNqTmpKQy8hipPBAMguwqDk6J+mgAXDR0TCysqZhtpeVIAB6U8AAmSJgoptJyCjBAA)

```.d.ts
declare function Select({ myFunc }: {
    myFunc?: null | undefined;
}): JSX.Element;
```

`myFunc` is no longer allowed to be, well, anything except null/undefined, when it should be `any`

**Note that this appears to happen in 4.4 when I turn on `strictNullChecks`** - if you turn that toggle off in 4.4, it goes back to the `myFunc?: any;` def, so there appears to be something going on there maybe? I can't tell if this is some sort of interaction with the new `exactOptionalPropertyTypes` toggle or what, though if I turn that off in 4.4 it still doesn't change the .d.ts. So 🤷 

### 💻 Code

```jsx
import React from 'react'
import PropTypes from 'prop-types'

const Select = ({myFunc = null}) => {
  return <button onClick={() => myFunc?.()}>hi</button>
}

Select.propTypes = {
  myFunc: PropTypes.func
}

export default Select
```

### 🙁 Actual behavior

```.d.ts
myFunc?: null | undefined;
```

`myFunc` is only allowed to be `null | undefined`

### 🙂 Expected behavior

```.d.ts
myFunc?: any;
```

`myFunc` is `any`

-----

From reading the [release blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/), I don't notice anything that would appear to change this behavior. I could have misunderstood or missed it though!

**Comment by frehner** [comment]
Appears to still happen in 4.5 beta https://www.typescriptlang.org/play?strictNullChecks=true&ts=4.5.0-beta&filetype=js#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4AFHMAFQE8wkBnObXAsOgWhmZsypNBAB2reAGUkAGyQY4AXjgAKAN4hGAMQCuYtMrhjds2QF8AlMoB8cdaThwiMXVDFwAPACNdMGOJw4gDCssBoANZK6qrWSnZaegYA-AB0seY2ABbAngD0vv7iNqTmpKQy8hipPBAMguwqDk6J+mgAXDR0TCysqZhtpeVIAB6U8AAmSJgoptJyCjBAA

**Comment by weswigham** [comment]
So first, nothing about this is related to JSX. The much simpler
```js
export const Select = ({myFunc = null}) => {
  myFunc?.();
}
```
is enough to show the issue in the declaration emit/errors on `myFunc?.()`.

Second, this regressed in #43933, definitely unintentionally.
