### ISSUE TITLE
checker.ts: explicit boolean type annotation overrides type guard, silencing an error

### ISSUE THREAD

**Issue by rafaelsofizadeh** [microsoft/TypeScript#45594]
# Bug Report

I wouldn't call this a bug, but rather a piece of code inconsistent with "best practices" and prone to cause more confusion in future.

**This is a spin-off from issue https://github.com/microsoft/TypeScript/issues/45572**. I have investigated the line mentioned in @andrewbranch 's comment, and answered my own question in the subsequent reply.

If you indeed recognize it as a bug, please read the "Solution" section and assign the bug to me. Thanks for working on and maintaining such a wonderful project!

### 🔎 Search Terms

Control flow analysis of aliased conditional expressions
Type guard result saved to variable

### 🕗 Version & Regression Information

This was introduced in [**v4.4.0-beta**](https://github.com/microsoft/TypeScript/releases/tag/v4.4-beta), by pull request https://github.com/microsoft/TypeScript/pull/44730 "Control flow analysis of aliased conditional expressions", commit https://github.com/microsoft/TypeScript/pull/44730/commits/08b6e2e0fe8d1cb1b5b3d563244a22e82e8e91df. 

"inlining CFA" through an explicit type annotation:

``` diff
@@ -38340,9 +38340,9 @@
function checkModuleDeclaration(node: ModuleDeclaration) {
    ...
-   const isAmbientExternalModule = isAmbientModule(node);
+   const isAmbientExternalModule: boolean = isAmbientModule(node);
```

### ⏯ Playground Links & 💻 Code

```ts
// utilities.ts

export function isAmbientModule(node: Node): node is AmbientModuleDeclaration {
    return isModuleDeclaration(node) && (node.name.kind === SyntaxKind.StringLiteral || isGlobalScopeAugmentation(node));
}

export function isExternalModuleAugmentation(node: Node): node is AmbientModuleDeclaration {
    return isAmbientModule(node) && isModuleAugmentationExternal(node);
}          ^^^^^^^^^^^^^^^^^^^^^
```
[Playground link illustrating the **"Before"** code example](https://www.typescriptlang.org/play?ts=4.3.5#code/C4TwDgpgBAypDGBLAhgGxsATogdgcygF4oBnLXAgMigG8SEVUAuKAIwHt3UJkcBfANwAoIQDMArjnjBE7HFEQk4EJGgzZ8ACgAeLXiACULbQpKwGa8vlpCodqJgjBxmeQCFO3XpoCyyYAAWAHSY7JIAJr7+wZi84ewAtpoGKcJ8IhJSMnKkFqgAwgEqANY6ejiGLBxcPPI0tvaOzq5QJoTtUADk9CqMnWkZktKy8orKquhWeACC0uJoqCDjjGVQ+katpua9lhoE9fYOTi6jSnnqFDoGUJTUPROFJVcDYkPZ8sAQZJpkmCy-FA2OHECVYEEwNkO8DkZFMcHgkwhxDG5ymPywBmEDTsAHocVB8gAxaZQeJfHCdYBHZDSKDAdhrVAoEgQcJ08DQPDzTBsxwkcSoYAkIJQbFQPFQAByDNAkCgOGQmFCAHcKFB2PB4C4SAAaOlFRyidiOKAAA1+WwB+FNUAgADdwSBlQboLgSIhwhAxRLAtBoThwoh3mhSMB-P4IAkIDhgEExYhRFBNCiEeprgdDvYE0mUTtERRZs4Fks8ujMClIZmq00TqHMEFuPhAsIq3Y+LbUCzK63GscWr8G9G8M2xYd0mORIcay0AAxpIA)
Before https://github.com/microsoft/TypeScript/pull/44730 ([v4.3.5](https://github.com/microsoft/TypeScript/releases/tag/v4.3.5)):

```ts
function checkModuleDeclaration(node: ModuleDeclaration) {
    // ...
    
    // Type guard result gets assigned to a variable.
    const isAmbientExternalModule = isAmbientModule(node);

    // ...

    // Control flow analysis would've narrowed `node` to AmbientModuleDeclaration 
    if (isAmbientExternalModule) {
        // ... so, here, `node` doesn't get narrowed to AmbientModuleDeclaration — it stays just a ModuleDeclaration, 
        // as annotated in the function signature

        if (isExternalModuleAugmentation(node)) {

            // Now, because the type guard is inside the conditional statement, `node` will get narrowed to AmbientModuleDeclaration.

        }
        // However, outside the if statement, `node` is still ModuleDeclaration. No errors.
        // If CFA recognized that isAmbientExternalModule narrows `node` to AmbientModuleDeclaration,
        // the redundancy in isExternalModuleAugmentation() type guard (which contains isAmbientModule() in itself)
        // would cause `node` to be narrowed down to `never`.
        else if ( /* `node` is `ModuleDeclaration` here... */ ) { 
       
        }
        else {
            // ...and here.
        }
    }

    // ...
}
```

[Playground link illustrating the **"After, current"** code example](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/C4TwDgpgBAypDGBLAhgGxsATogdgcygF4oBnLXAgMigG8SEVUAuKAIwHt3UJkcBfANwAoIQDMArjnjBE7HFEQk4EJGgzZ8ACgAeLXiACULbQpKwGa8vlpCodqJgjBxmeQCFO3XpoCyyYAAWAHSY7JIAJr7+wZi84ewAtpoGKcJ8IhJSMnKkFqgAwgEqANY6ejiGLBxcPPI0tvaOzq5QJoTtUADk9CqMnWkZktKy8orKquhWeACC0uJoqCDjjGVQ+katpua9lhoE9fYOTi6jSnnqFDoGUJTUPROFJVcDYkPZ8sAQZJpkmCy-FA2OHECVYEEwNkOAHooVAACrgaC8HDsYD+EZQdgAN3B2HCXyggWgoEgUDw80w4SOJHEqGAABpSOwoPkAGLTKAAd0QqFQUCxiAgnMJAUUDTsMNIiASYEWazMyDYnlqaxwVJRwCg4hI0EQmtE7AhOGQmFC3PwQXFUHgcjIpjg8EmfyVNV4RHt5ymPywBmEVslcICvGKZmAzKJUDAtL5jgAjuIvgyWezrW6UcLjab2MKAAa-HNsZA6qlyf2wtAoYvWuThPUjNCkNGfBIQHDAIJQAAS2YgOMwjIjYzAjvUWwAVtrNYrql4cPSy1ANWtCYiyRSqY4aXSoJowI5a-BkC22wB+AyMkjMvNYAuOBLIXBma97AtxKDxL44TrABd4JyLk1QiFCAqTDbYJguC0rUQUQdyHEcfUhQ57BguCzh2J0KFmZwFiWPJvUwFIkOQ5CmhORtMCCbh8ECYQSLsPgoAgVAdWI+iJVhAA5ZlcUNKBAGQCKBnwLRRGx5PlFWfCgC00VhxE1fFRFwPVmJARdUWXZZdgoVUQASQ0IAMS12MOMiWl+KjWzwWirUOdI7JEUzjhaAAGNIgA)
After (with explicit type annotation, e.g. current version, WITHOUT error) https://github.com/microsoft/TypeScript/pull/44730 ([v4.4-beta](https://github.com/microsoft/TypeScript/releases/tag/v4.4-beta)):

```ts
function checkModuleDeclaration(node: ModuleDeclaration) {
    // ...
    
    // Type guard result gets assigned to a variable. CFA would've narrow down `node`
    // in conditional statements below, IF NOT for the `boolean` explicit annotation. Because of it, CFA no longer treats isAmbientExternalModule as a type guard result. No type narrowing will happen below, so further this example
    // is identical to the "Before" example above.
    const isAmbientExternalModule: boolean = isAmbientModule(node);
    
    // ...
}
```

[Playground link illustrating the **"After, current"** code example](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/C4TwDgpgBAypDGBLAhgGxsATogdgcygF4oBnLXAgMigG8SEVUAuKAIwHt3UJkcBfANwAoIQDMArjnjBE7HFEQk4EJGgzZ8ACgAeLXiACULbQpKwGa8vlpCodqJgjBxmeQCFO3XpoCyyYAAWAHSY7JIAJr7+wZi84ewAtpoGKcJ8IhJSMnKkFqgAwgEqANY6ejiGLBxcPPI0tvaOzq5QJoTtUADk9CqMnWkZktKy8orKquhWeACC0uJoqCDjjGVQ+katpua9lhoE9fYOTi6jSnnqFDoGUJTUPROFJVcDYkPZ8sAQZJpkmCy-FA2OHECVYEEwNkOAHooVAAHLsKCgSBrHA4djAfwjAA0UHyADFplAAO6IVCoI7wdh4HCIABe0DGYHgkwhyDMyCR4GgeHmmHCRxI4lQwAadhhqIF8F4UHEJEZwCgonYEJwyEwoVJ1lwSvEzQgQTFUCpODIpjgLPURHN5ymPywBmERolABUArximZgIjAtAwMKKY4AI7iL7AXEEonS+To4lQNUa9hxgAGv2TbHZEAFcmdsLQKHlUrk4UQ7zQpExnwSEBwwENh0QoigmiZlodkMO9glAHkAG7g1DIMBgChclFgRwl6XV2sKU7LXaXa5xG07VkUWbOBZLPLJI3Q2FecJexGRqAQbTuuUyawLMfQdhgd5mZUQ1NYdM6oWseUhmuKk0SzLClWFiKQihIfcuzzHABQTTVR3fTB029KBkxwCB+2Q+tOzsRtmyZNcLnwTd5nJHc13tTAUg7XDDiaE4K0wIJuHwQJhDoqA+HPVB5VozijmaeRfhYms8HYqC7HSQ50iNBiWgABjSIA)
After https://github.com/microsoft/TypeScript/pull/44730 (edited out the type annotation, GIVES ERROR) ([v4.4-beta](https://github.com/microsoft/TypeScript/releases/tag/v4.4-beta)):

```ts
function checkModuleDeclaration(node: ModuleDeclaration) {
    // ...
    
    // Type guard result gets assigned to a variable. Now, there's no explicit type annotation, 'boolean' doesn't override
    // the type guard's result (predicament?)
    const isAmbientExternalModule = isAmbientModule(node);

    // ...

    // Control flow analysis NARROWS `node` to AmbientModuleDeclaration 
    if (isAmbientExternalModule) {
        // And here, because both isAmbientExternalModule and isExternalModuleAugmentation assert that `node` is AmbientModuleDeclaration ...
        if (isExternalModuleAugmentation(node)) {
            // `node` is `AmbientModuleDeclaration` here 
        }
        // ... CFA will exhaust all possible types for `node` after the first if() statement 
        // (what else can AmbientModuleDeclaration be if not an AmbientModuleDeclaration?)
        // so `node` will be `never`.
        else if ( /* `node` is `never` here... */ ) { 
       
        }
        else {
            // ...and here.
        }
    }

    // ...
}
```

### ✅ Solution

[Playground link the proposed solution based on prev. examples](https://www.typescriptlang.org/play?ts=4.4.0-beta&ssl=19&ssc=38&pln=18&pc=5#code/C4TwDgpgBAypDGBLAhgGxsATogdgcygF4oBnLXAgMigG8SEVUAuKAIwHt3UJkcBfANwAoIQDMArjnjBE7HFEQk4EJGgzZ8ACgAeLXiACULbQpKwGa8vlpCodqJgjBxmeQCFO3XpoCyyYAAWAHSY7JIAJr7+wZi84ewAtpoGKcJ8IhJSMnKkFqgAwgEqANY6ejiGLBxcPPI0tvaOzq5QJoTtUADk9CqMnWkZktKy8orKquhWeACC0uJoqCDjjGVQ+katpua9lhoE9fYOTi6jSnnqFDoGUJTUPROFJVcDYkPZ8sAQZJpkmCy-FA2OHECVYEEwNkO8DkZFMcHgkwhxDG5ymPywBmEDTsAHocVAACoBXjFMzAdhQQLQMDiVCoI4AR3EX2AABooPkAGLTKDwXhQHDsADuAuQmFCIoABr9JWxkCQIOEoHJsVA8WtUCgFUroThwoh3mhSMB-BAEhAcMAgqrEKIoJoUQj1NcDod7OqAHIU9gAN3BqGQYAFwoAhKrDrb7fdGI94KVfilIW7k00TsbMEFuPhAsJk3Y+FAIKgFUm841ji1fpmLXgc+H7OlDulVamWgAGNJAA)

``` diff
src/compiler/checker.ts

function checkModuleDeclaration(node: ModuleDeclaration) {
    ...
    // Removing explicit boolean type annotation will allow CFA to narrow `node` in subsequent conditional statements.
-   const isAmbientExternalModule: boolean = isAmbientModule(node);
+   const isAmbientExternalModule = isAmbientModule(node);

    ...
    
    if (isAmbientExternalModule) {
         // Removing the second isAmbientModule() check (as a part of isExternalModuleAugmentation()) will prevent
         // CFA from narrowing `node` to `never`.
-       if (isExternalModuleAugmentation(node)) {
+       if (isModuleAugmentationExternal(node)) {
        ...
```

**Comment by fatcerberus** [comment]
By design, per #44730:
> Narrowing through indirect references occurs only when the conditional expression or discriminant property access is declared in a const variable declaration **with no type annotation**, and the reference being narrowed is a const variable, a readonly property, or a parameter for which there are no assignments in the function body.

Emphasis mine.

**Comment by rafaelsofizadeh** [comment]
@fatcerberus thank you for the reference! I missed that somehow.
