### ISSUE TITLE
Discriminated unions with booleans require explicit `===`

### ISSUE THREAD

**Issue by Luke-zhang-04** [microsoft/TypeScript#45609]
# Bug Report

### 🔎 Search Terms

- Strict equal
- discriminated unions
- boolean

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about strict boolean equals

### ⏯ Playground Link

No errors on playground, but errors occur in the CLI
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAygFgQ0lAvFA3gSwM4GFMBOAxgDYQBcUwBArhANxQEIAmmN2lAdjQLYBGEAgF8oAHww58xMpQBmCEtgZRsmFhAAyELgHNgcbn0EiAsACgLcmlyLBMAey5QEBCAgAU2RJErwkEACURgJCGBZQkVAA9NFQAKIAHtQIdlAONMBUcNAA5ADWmFwsuVBymBAkLGWE2MAAdBFRRE51kniEpBCiaN4BFk2RmHJQXj4Q9VKdZIHh5lELMXEA6tD5XA4A7lCb0IgAbtAIUETTe0IQAISDi27ANATOALIIBvUACgCSUABUquP1ZhsDi-P4AJhuokqyjmiyisSgqyg6y2OwguTcUDIciym0wBhcqgAjjRXOc3Nd5nCmBB7o9-gF6moNNo9ASfuDIRZhANzC0uNgHGR6iQHLoPGTPFgOjIKGVFMoADSqdRaHT6QxQACMAAZhIFAhYgA)

### 💻 Code

```ts
type Shape = {isCircle: true; radius: number} | {isCircle: false; sideLength: number}

// https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#cfa-aliased-conditions
function area(shape: Shape): number {
    if (shape.isCircle) {
        // We know we have a circle here!
        return Math.PI * shape.radius ** 2
    } else {
        // We know we're left with a square here!
        return shape.sideLength ** 2
		 // Property 'sideLength' does not exist on type 'Shape'.
		   // Property 'sideLength' does not exist on type '{ isCircle: true; radius: number; }'.ts(2339)
    }
}

// https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#cfa-aliased-conditions
function area2(shape: Shape): number {
    if (shape.isCircle === true) {
        // We know we have a circle here!
        return Math.PI * shape.radius ** 2
    } else {
        // We know we're left with a square here!
        return shape.sideLength ** 2 // Works ok
    }
}
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/55749227/131204070-7eb737f0-4498-4037-a46b-7fb339754bcc.png)

`Property 'sideLength' does not exist on type '{ isCircle: true; radius: number; }'` for versions next, latest, and `3.8`

![image](https://user-images.githubusercontent.com/55749227/131204094-24380d6d-d1a9-4bb7-a9a0-8a1ef334e578.png)

The example above works in the playground, but not the command line or VSCode.

### 🙂 Expected behavior

No error. True is truthy, and should be narrowed in the same way as `null` and `undefined`. TSConfig is simple too:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2020",
        "jsx": "preserve",
        "sourceMap": true,
        "noEmit": true
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ],
    "include": ["test.ts"]
}
```

**Comment by MartinJohns** [comment]
> No errors on playground, but errors occur in the CLI

The error is the same if you compile with the same settings. In this case the relevant setting is `strictNullChecks`, which is enabled in your playground link, but not in your tsconfig.

This is working as intended.

**Comment by Luke-zhang-04** [comment]
Ok, sorry about opening the issue then. But IMO this is super weird behaviour even with the flag. It feels counter-intuitive that a strict flag makes the code "less strict".

**Comment by MartinJohns** [comment]
> It feels counter-intuitive that a strict flag makes the code "less strict".

That's not quite what is happening. With `strictNullChecks` enabled the compiler sees the `boolean` as either `true` or `false`. You checked for `true` in the if, so in the else-branch it must be `false` and matches your second union type. But without `strictNullChecks` the type also encompasses `null` and `undefined`. Just because you checked for `true`, doesn't mean it's `false` in the else-branch.

**Comment by Luke-zhang-04** [comment]
Oh I see. I guess I just misunderstood what `strictNullChecks` was, since I never have it off. Thanks!

**Comment by MartinJohns** [comment]
> since I never have it off

Well, it's off in the tsconfig you posted, including all other strict flags. The default setting is `false`. I always suggest enabling all of them, as they vastly improve type-safety.

**Comment by Luke-zhang-04** [comment]
Yeah I just had it off while playing with some examples 😐

**Comment by tamlyn** [comment]
> But without strictNullChecks the type also encompasses null and undefined. Just because you checked for true, doesn't mean it's false in the else-branch.

This makes sense, but I don't understand how it results in the behaviour demonstrated by the OP.

With `strictNullChecks` disabled, this compiles OK.

```
function area(shape: Shape): number {
    if (shape.isCircle === true) {
        return Math.PI * shape.radius ** 2
    } else {
        return shape.sideLength ** 2
    }
}
```

But removing the `=== true` results in an error, as seen in this updated [Playground](https://www.typescriptlang.org/play?strictNullChecks=false&ts=4.4.2#code/C4TwDgpgBAygFgQ0lAvFA3gSwM4GFMBOAxgDYQBcUwBArhANxQEIAmmN2lAdjQLYBGEAgF8oAHww58xMpQBmCEtgZRsmFhAAyELgHNgcbn0EiAsACgLcmlyLBMAey5QEBCAgBMACmyJIleCQIAEojASEMCyhoqEw5KB8-CAA6KUJSaBQsqloQyPMYwqgAemKoAHVoAGsuBwB3KDroRAA3aAQoInSyKDghCABCKKLot2AaAmcAWQQDZIAFAEkoACpVJOTmNg5VtY9h6NEIJWh0A6LSiurahqaAcjcoMjlgRswDF1UARxpXZv6hgURkwIONJusgsk1BptHoPis9udhBZkZZzNZbPYnC43AgAIyJIIBJKhKA8cIEfKFOIJXyQtIyPJnIEjS6VKA1eqNZoINqfLqM3oA86FMYTaazOALZZrOmQTasdjYXZQfYsqBHE5U4FsuAgKAsJx3V5NDk3bkPaDPE3vOCfbA-P5CtwAfhFMTF4LlKWhWh0+jtCNVSJRQA).
