### ISSUE TITLE
Snippet import statement completions don't work for 'import type'

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#45607]
```ts
// @filename: yadda.ts
export interface Yadda {
}

// @filename: badda.ts
import type /**/
```

Request completions at `/**/`

**Expected**

`Yadda` is a completion item.

**Actual**

`Yadda` is not a completion item.

**Comment by iamdevelopergirl** [comment]
Can I work on this? This is my first time contributing to Typescript.

**Comment by orta** [comment]
You can, give it a shot!

**Comment by Pika-Pool** [comment]
Hey @orta, could you please point me to a file/snippet of code where I can start looking for this issue in the source code?

**Comment by iamdevelopergirl** [comment]
Hey @Pika-Pool, I started looking in to the issue and found related completions under src/services/completion.ts. But I could not get to solve the issue yet.

**Comment by andrewbranch** [comment]
Hint: the function that needs a change is `getImportCompletionNode`.

**Comment by a-tarasyuk** [comment]
@andrewbranch do we need to have `type` import in `getInsertTextAndReplacementSpanForImportCompletion` for this case?

**Comment by andrewbranch** [comment]
Yes, or alternatively the replacement span could be smaller, after `import` and `type`. For now, the whole import declaration gets replaced just because that was easiest and really had no downside.
