### ISSUE TITLE
Catch variables typed as unknown is not correctly limited by type guards when used in functions

### ISSUE THREAD

**Issue by donjar** [microsoft/TypeScript#45611]
# Bug Report

### 🔎 Search Terms

- catch variables
- unknown
- type guards
- functions

### 🕗 Version & Regression Information

This is a bug specific for version 4 onwards, when catch variables can be typed as unknown.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.2#code/C4JwngBA3gvhDGBDY8AWEAUBTAlNAUBBAJYBmmWJAdgM7CJXxYD25AoiCMyHlIUZjwBeAHwQsAOgC2WGjUQBzLAG5+MfDCA

### 💻 Code

```ts
try {} catch (e) {
  if (e instanceof Error) {
    () => e.message;
  }
}
```

In previous versions of TS that is >= 4:
```ts
try {} catch (e: unknown) {
  if (e instanceof Error) {
    () => e.message;
  }
}
```

### 🙁 Actual behavior

Does not work: it says `e` is of type unknown. I expected it to work because `e` has been type guarded.

### 🙂 Expected behavior

Should work, just like in the following example:
```ts
const fn = (a: string | Error) => {
  if (a instanceof Error) {
    () => a.message
  }
}
```

### Workaround
Currently something like this works.
```ts
try {} catch (e) {
  if (e instanceof Error) {
    const message = e.message;
    () => message;
  }
}
```

**Comment by fatcerberus** [comment]
The type guard doesn’t work because of the closure.  See #9998.

**Comment by donjar** [comment]
Got it, thanks!
