### ISSUE TITLE
Navigator interface no longer extends MSFileSaver

### ISSUE THREAD

**Issue by jrmcpeek** [microsoft/TypeScript#45612]
# Bug Report

Recent changes to the Navigator interface for 4.4 removed previous extensions; however, the previously extended type is still present in lib.dom.d.ts and should be added back to the interface.

### 🔎 Search Terms

Navigator, MSFileSaver, msSaveBlob, msSaveOrOpenBlob

### 🕗 Version & Regression Information

Injected starting with https://github.com/microsoft/TypeScript/commit/9d443b76aac0832d7f3c890441264d39307fe31a

- This prevents building

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/JYMwBAFA7sB2AmB7KA6WBDAbsA5ugLogE4oC2AzgMpYCmAQgDaIBGAlGAN4BQYvYAxoljlEDGiiY4IAIgAqATwAONMFGIBrcgEJprLgF8uXUJBgJkaLLgLEyVWgHkiD5bEYt23PgKEixExCk5JRU1Ik0dPX0gA)

### 💻 Code

```ts
if (window.navigator.msSaveBlob) {
    console.log("Type works!")
}

if (window.navigator.msSaveOrOpenBlob) {
    console.log("Type works!")
}
```

### 🙁 Actual behavior

`TS2339: Property 'msSaveOrOpenBlob' does not exist on type 'Navigator'.`
`TS2339: Property 'msSaveBlob' does not exist on type 'Navigator'.`

### 🙂 Expected behavior

Appropriately typed file continues to build as it did previously.

**Comment by orta** [comment]
Both of these have been marked from removal from the browsers and removed from the W3C specs, which means they were removed from the DOM.d.ts files as they follow the specs as summarized in https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029

 - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveOrOpenBlob
 - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/msSaveBlob

**Comment by MartinJohns** [comment]
You can use [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) and declare the types locally in your project.

**Comment by jrmcpeek** [comment]
I figured it was probably something like that. We already worked around it with the declaration merging, so no issues there.

Now to focus on the real fix. Thanks!

**Comment by mesqueeb** [comment]
In case anyone comes looking here,
@MoSattler 's answer didn't work for me, and it only accept `Blob` while it should also accept base64 strings and a filename!

This fixed it for me:
```ts
declare global {
  interface Navigator {
    msSaveOrOpenBlob: (blobOrBase64: Blob | string, filename: string) => void
  }
}
```

I just added this at the top of the file where I was using this function.
