### ISSUE TITLE
Better error message for non-local imports with --m=commonjs

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#4562]
importing a file in the same directory, with non-relative path in node causes an error for unknown file. the error message can be a bit helpful if the file is around.

```ts
import * as ns from "file1";
```
generates error:
> Error TS2307: Cannot find module 'file1'.

can be:
> Error TS2307: Cannot find module 'file1'. did you mean `./file1`

**Comment by falsandtru** [comment]
`comonjs` is misspell?
