### ISSUE TITLE
Please support [import value XXX, {YYY} from "{./}ZZZ"] statement

### ISSUE THREAD

**Issue by MR-L-2015** [microsoft/TypeScript#45621]
# Suggestion

## 🔍 Search Terms
import value, import value from

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ * ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ * ] This wouldn't change the runtime behavior of existing JavaScript code
* [ * ] This could be implemented without emitting different JS based on the types of the expressions
* [ * ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ * ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

When solving Circular reference problem, we need import("") or require("").

1. import("") need await, async, promise etc, hard to get result immediately.
2. typescript, tsc, vscode doesn't support require("") path parameter legality check.
3. Typescript 3.8 support [import type from], but hard to use. ( Because it need works with import("") or require("") )

## 💻 Use Cases

A new [import value from] statement is easy use, and keep  require("") path parameter legality check.

Example
==================================

TypeScript source code:
==================================
import value ABC from "./a/b/c/ABC";  //wanna typescript to support the path parameter legality check
let abc : typeof ABC = new ABC();

After tsc compile, we get JavaScript source code:
==================================
let abc = new require("./a/b/c/ABC").default

**Comment by andrewbranch** [comment]
Fails this box (emphasis mine):

> This isn't a runtime feature (e.g. library functionality, **non-ECMAScript syntax with JavaScript output**, new syntax sugar for JS, etc.)

You might be interested in https://github.com/microsoft/TypeScript/pull/44501 which has support for transpiling `import Foo = require("...")` into a `createRequire` helper when targeting Node's ESM module format.
