### ISSUE TITLE
Typescript fail to unify type variables

### ISSUE THREAD

**Issue by xieyuheng** [microsoft/TypeScript#45627]
I have to write `cons<string>` (instead of simply `cons`) in this example: https://github.com/xieyuheng/logic-db/blob/6b51e52e5aefb8dd3c24a3929f702c0a2afe9563/src/examples/clause-and-effect/worksheet-05-member.test.ts

**Comment by jcalz** [comment]
This doesn't constitute a proper bug report; please fill out the [full template](https://raw.githubusercontent.com/microsoft/TypeScript/fd067e9e81dd00a126f8cccf91cda53bebd73f31/.github/ISSUE_TEMPLATE/Bug_report.md) if you want someone to look at this.

**Comment by xieyuheng** [comment]
Thanks for replying, I will write a proper report.

**Comment by xieyuheng** [comment]
I will close this and do a new one, Thanks again.

**Comment by MartinJohns** [comment]
Advice for the next time: You can actually edit your issues.
