### ISSUE TITLE
Missing error when handling union type templates

### ISSUE THREAD

**Issue by Finomnis** [microsoft/TypeScript#45622]
# Bug Report

### 🔎 Search Terms

- union missing error abstract class
- union template missing error 

### 🕗 Version & Regression Information
- I tested it on https://www.typescriptlang.org/play with versions 3.5.1 and 4.4.2
- I stumbled across this bug while trying to find an answer for https://stackoverflow.com/questions/68974596/argument-of-type-eventhandlertk-is-not-assignable-to-parameter-of-type-ev

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAcgrgWwEYQE4HlUGVioJYB2A5lALxQDOuhJAPlAYiqgNwBQbAhklapwMbAo-ADacKFKABkA9kSJoAPAGkoEAB7AIBACaT4yNJhz5iAPgDebKDajdeAoSLkAKdQC4oygJSeAbjJ4OuwAvhyi4pImNLLyaGqa2nrScgqoirw0lta2zkRunpnEvlABQVBWtlVQeABmUC6gkDL16lAAhKTkAERFRN3eFTnV1QD0o1AAKgAWeJIU0zJwIjoMEH7x05xgkATDI7bA06gyAO5r55PgEACiqCeoLt0Agvz8Mqg6NFDAMj-XFH4+DAQjaCyWKygKDslGoxAANFC4EI8CjJAQZMAAHQDdgHKBhfHvAgUGQiCBYvJubx42xhMJsCISKAAYRkBGAnEI8UquVSaE8sTSigMzGMcKIZjIFyg0WIQrQLhpHCqYDgSBEeH4UCpfk4IjgEE8oqM2Alg15IyOc0p-NQtvyeoNEGVVXpHHJQmJnO5qGlBAg5zZHK5Aceyu9obQDpcAEYAAzKoA)

### 💻 Code

```ts
type NumberOrString = string | number;

abstract class Logger<K extends NumberOrString>{
    abstract log(x: K): void;
}

class StringLogger extends Logger<string>{
    log(x: string): void {
        if (typeof x !== "string") {
            // This should never happen
            throw new TypeError("According to typescript x should be a string, but it is not.");
        }
        console.log(x);
    }
}

class Container {
    logger: Logger<NumberOrString> = new StringLogger();

    public log(value: NumberOrString) {
        this.logger.log(value);
    }
}

let container = new Container();
container.log(10);
```

### 🙁 Actual behavior
No typescript error occurs. The code behaves like all types are correct.

### 🙂 Expected behavior
Some typescript error should occur. Something in the lines of:
```
Argument of type ... is not assignable to parameter of type ...
  ... is assignable to the constraint of type ..., but ... could be instantiated with a different subtype of constraint 'NumberOrString'.ts(2345)
```

### Related errors
Changing this code slightly by introducing the template `K1` does throw errors as expected:
```ts
class Container<K1 extends NumberOrString> {
    logger: Logger<K1> = new StringLogger();

    public log(value: NumberOrString) {
        this.logger.log(value);
    }
}
```
[Playground Link](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAcgrgWwEYQE4HlUGVioJYB2A5lALxQDOuhJAPlAYiqgNwBQbAhklapwMbAo-ADacKFKABkA9kSJoAPAGkoEAB7AIBACaT4yNJhz5iAPgDebKDajdeAoSLkAKdQC4oygJSeAbjJ4OuwAvhyi4pImNLLyaGqa2nrScgqoirw0lta2zkRunpnEvlABQVBWtlVQeABmUC6gkDL16lAAhKTkAERFRN3eFTnV1QD0o1AAKgAWeJIU0zJwIjoMEH7x05xgkATDI7bA06gyAO5r55PgEACiqCeoLt0Agvz8Mqg6NFDAMj-XFH4+DAQjaCyWKygKDslGoxAANFC4EI8CjJAQZMAAHQDdgHKBhfHvAgUGQiCBYvJubx42xhMJsCISKAAYRkBGAnEISmUAEYElpdPomEZsHCiGYhlU8mlPLE0ipeZLyAQIOdosR5WgXDSOFUwHAkCI8PwoFS-JwRHAIJ4DMxjOLBpUDkc5pTUmh3fkLVaILqqvSOOShMTOdzUGQLqz2WHVY9daGuXGvS5eQAGXVAA)

```
test.ts:18:5 - error TS2322: Type 'StringLogger' is not assignable to type 'Logger<K1>'.
  Types of property 'log' are incompatible.
    Type '(x: string) => void' is not assignable to type '(x: K1) => void'.
      Types of parameters 'x' and 'x' are incompatible.
        Type 'K1' is not assignable to type 'string'.
          Type 'NumberOrString' is not assignable to type 'string'.
            Type 'number' is not assignable to type 'string'.

18     logger: Logger<K1> = new StringLogger();
       ~~~~~~
test.ts:21:25 - error TS2345: Argument of type 'NumberOrString' is not assignable to parameter of type 'K1'.
  'NumberOrString' is assignable to the constraint of type 'K1', but 'K1' could be instantiated with a different subtype of constraint 'NumberOrString'.
    Type 'string' is not assignable to type 'K1'.
      'string' is assignable to the constraint of type 'K1', but 'K1' could be instantiated with a different subtype of constraint 'NumberOrString'.

21         this.logger.log(value);
                           ~~~~~
```

<br>
Removing the explicit definition will also throw an error as expected:

```ts
class Container {
    logger = new StringLogger();

    public log(value: NumberOrString) {
        this.logger.log(value);
    }
}
```
[Playground Link](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAcgrgWwEYQE4HlUGVioJYB2A5lALxQDOuhJAPlAYiqgNwBQbAhklapwMbAo-ADacKFKABkA9kSJoAPAGkoEAB7AIBACaT4yNJhz5iAPgDebKDajdeAoSLkAKdQC4oygJSeAbjJ4OuwAvhyi4pImNLLyaGqa2nrScgqoirw0lta2zkRunpnEvlABQVBWtlVQeABmUC6gkDL16lAAhKTkAERFRN3eFTnV1QD0o1AAKgAWeJIU0zJwIjoMEH7x05xgkATDI7bA06gyAO5r55PgEACiqCeoLt0Agvz8Mqg6NFDAMj-XFH4+DAQjaCyWKygKDslGoxAANFC4EI8CjJAQZMAAHQDdgHKBhfHvAgUGQiCBYvJubx42xhMJsCISKAAYRkBGAnEI8UquVS8XIBAg52ixFiaRcNI4VTAcCQIjw-CgVL8nBEcAgngMzGMcKIg15IyOc0p-NQpvyqvVEClVXpHHJQmJnO5qDIF1Z7JdQseUudXJ9FpcAEYAAxSoA)
```
test.ts:21:25 - error TS2345: Argument of type 'NumberOrString' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

21         this.logger.log(value);
                           ~~~~~
```

**Comment by MartinJohns** [comment]
Method parameters are always bivariant. See #43789 and others.

**Comment by Finomnis** [comment]
As I understand this is intended behaviour, I will close this issue.
