### ISSUE TITLE
it doesn't work when i use new AsyncFunction() to build a async function in ts.

### ISSUE THREAD

**Issue by on1onkn1ght** [microsoft/TypeScript#45635]
# Bug Report

### 🔎 Search Terms

AsyncFunction

### 🕗 Version & Regression Information

    "typescript": "^4.1.2",

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
class cla {
    public resolveAfter2Seconds =  async function(x) {
        return new Promise(resolve => {
            setTimeout(() => {
                resolve(x);
            }, 2000);
        });
    }
}

var AsyncFunction = Object.getPrototypeOf(async function(){}).constructor;
var a = new AsyncFunction('a',
    'b',
    'c',
    ' return await c.resolveAfter2Seconds(a) + await c.resolveAfter2Seconds(b);');
a(10, 20, new cla()).then(v => {
    console.log(v); // 4 秒后打印 30
});

### 🙁 Actual behavior

undefined:3
 return await c.resolveAfter2Seconds(a) + await c.resolveAfter2Seconds(b);
        ^^^^^

SyntaxError: await is only valid in async function
    at new Function (<anonymous>)
    at Object.<anonymous> (/Users/dingyufang/WebstormProjects/bpmntest/abc.js:58:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

Process finished with exit code 1

**Comment by IllusionMH** [comment]
You forgot to provide link to playground that will demonstrate your error

**Comment by on1onkn1ght** [comment]
> You forgot to provide link to playground that will demonstrate your error

https://www.typescriptlang.org/play?ssl=21&ssc=1&pln=1&pc=1#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQMANgIabZnmgDeRoToADgK4BGpAljKIZjikAbkgCCAMwAuBAEwBlJPAB2CbAF4mlSMr4S2uqdzjKAFAA8AXMrYBbDgQCU9RszeEpbfMtDKkAd1AABXw4W25MJFMBIVFQdQA+FzcU5kipABVuWyQ4NilTU2dE5NSyphiRKPNHAG5XcqYAXwAaUFkABi66hpSmnrcmoiGiImFyfFAxTB0YADEDGCMTeNAAeQ4AKyUpADpUJCkQuCkTyBYkNYlTbV1QfUNjM0c6ft2VTCl8NiW4fHrxpNaJo-IFprMFo8TKYAOTkGEtXowjgIpEwVFuGH8Q5eHzkfzkbhSWC7SqiSQyfAKJQmNQ3ZwAalA+MJxJgpKwsXE0jkihUdI4dRhPXIpgAjB02p02qDYBQio5dlI8GZTMJrHYHPhikkGG4PkIkLtSHBUGq6qAQKAACygQBLnoA4FUAykaAB2VQABmDrDHpAA

it works when i run in playground.  but i can't run in jest or compile to javascript and run in node.js.

**Comment by fatcerberus** [comment]
You're probably compiling to a `target` that doesn't support async functions natively (most likely `es5` or `es2015`), in which case this can't possibly work.

**Comment by on1onkn1ght** [comment]
> You're probably compiling to a `target` that doesn't support async functions natively, most likely `es5` or `es2015`, in which case this can't possibly work (the async function gets compiled down to a regular function using promises and thus `fn.constructor` is `Function`).

you are right!!!

**Comment by jetBn** [comment]
how solve it
