### ISSUE TITLE
Type guard function overloading is infered not properly when function is passed to a parameter

### ISSUE THREAD

**Issue by younho9** [microsoft/TypeScript#45634]
# Bug Report

### 🔎 Search Terms

- function overload
- type guard
- `Array.prototype.filter`
- discriminated unions

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/JYOwLgpgTgZghgYwgAgMIHsYwig3gKGWTAE8AHCALmQHIFNsIaBuQ5BOLCUK5EAVwC2AI2isAvvnyhIsRCgxcIASRAx0yCAA9IIACYBnNAxzICRMlGBJqAkWLb0lAIQhwQ1A2CsgA5hKkZaHgkZABBPTw2UgpqGjhIljYDfl84KFshUSgA6XBg+XDI1XVNHQh9IwioiysbPiyHIhgofmAwT29Qf3xJfBiUABEfAGtkAF5jJWQAHyKIVgHkYdARko1JxUZ12fn11nwAekPkAGVgXxA4MH4oFAAKAEYASnwYfhAEMGB0EGRgAxbHD3ABucAANvxeCsQGs1OhntQwZCUACptt4axjmcLlcbndkPcAEyvd6fb6-f6AkwQUEQqHUGEjRHIZFQqnonCsMlfH5-AFA2ls6GjFnCjmCsxsO74v7CgB0S3GytoTkYST6kQQ4PSKHoIC8yD0owMjNGAG0ALpHE4AUSgUHQUGQ6AQCFuED0yAA7gALCo4y7XD2EkkcmDAKBeeX4Y2rAzyiPg2T3AU057ywRwMj3Oko54TAB8rPpEHlHC4PFesYg2t17F+hrjsPWpuWo3WVptyHtjudrvddy9foD5yD+IeL3DkejsY78ITSZTaaUGazObzUIL42LCrVOFc7mr2IAchpe07kAB1f1-AwQChQa4oHkUv7oEHQcHoBIGN4fXlKRXRgiU3EVVjFUsJRpKUiBlW45VLRVyBQZVJjoGkNSkZsRkXYBk2gVNqSUElM2zXNhW3XckIrbAqykV8+SpQV1jAs1VnWSCUWgpQdnMZB4KgRCUWQigJhVDClCwucOIXRN8OXYiMXUNdyLAqiSxE-cIEPEBjxOM8ewdS8bwDfh7zKMhwWsdpiBQksrDgYRwQgGTYT-Ih5IIqAAB5BULIjBVeTz1wo0sNL3Tg6JACBngOHDWzYLzZD8ml1gC4CcGC5AyI3Sii00qFyxpXS4qAA)

### 💻 Code

```ts
interface Coffee {
  type: 'coffee';
  caffeine: number;
}

interface CoffeeInfo extends Coffee {
  price: number;
  coffeeBean: string;
}

interface Ade {
  type: 'ade';
  sugar: number;
}

interface AdeInfo extends Ade {
  price: number;
  fruit: string;
}

type Drink = Coffee | Ade;
type DrinkInfo = CoffeeInfo | AdeInfo;

// Signature (1)
function isCoffee(value: DrinkInfo): value is CoffeeInfo;
// Signature (2)
function isCoffee(value: Drink): value is Coffee;
function isCoffee(value: Drink): value is Coffee {
  return value.type === 'coffee';
}

declare const drinks: Drink[]
// Error occured when Signature (2) is first.
drinks.filter(isCoffee).map((value) => value.caffeine)

declare const drinkInfos: DrinkInfo[]
// Error occured when Signature (1) is first.
drinkInfos.filter(isCoffee).map((value) => value.coffeeBean)

// No Error When seperate function overloads
function isCoffee2(value: Drink): value is Coffee {
  return value.type === 'coffee';
}

drinks.filter(isCoffee2).map((value) => value.caffeine)

function isCoffeeInfo(value: DrinkInfo): value is CoffeeInfo {
  return value.type === 'coffee';
}

drinkInfos.filter(isCoffeeInfo).map((value) => value.coffeeBean)

// No Error When use explicit type variable
drinks
  .filter<Coffee>(isCoffee)
  .map((value) => value.caffeine);

drinkInfos
  .filter<CoffeeInfo>(isCoffee)
  .map((value) => value.coffeeBean);
```

### 🙁 Actual behavior

```
Property 'coffeeBean' does not exist on type 'DrinkInfo'.
  Property 'coffeeBean' does not exist on type 'AdeInfo'.
```

### 🙂 Expected behavior

`Array.prototype.filter` infer type guard function without explicit type variable.

To reduce duplicate type guard functions for discriminated unions, I used type guard function overloads. It works well elsewhere, but when used as a parameter (ex. in `Array.prototype.filter`), it works not properly.

I know the [order of overload signatures is important](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#ordering).
And this signatures are written in order of specificity and generality.

However, it is difficult to understand how the signature of `isCoffee` is inferred in `Array.prototype.filter`.
When a function is passed to a parameter, could you explain how the signature is inferred from the overload of the function?

**Comment by andrewbranch** [comment]
Unfortunately, inference from a function will only try the last overload signature. When it doesn’t work because `Coffee` is not assignable to `DrinkInfo`, the type parameter `S` in

```ts
filter<S extends T>(predicate: (value: T, index: number, array: T[]) => value is S, thisArg?: any): S[];
```

 falls back to its constraint `T`, which in this case is `DrinkInfo`. @DanielRosenwasser pointed out that you don’t need overloads for this function though:

```ts
function isCoffee<T extends Drink>(value: T): value is T & { type: "coffee" } {
  return value.type === 'coffee';
}
```

**Comment by younho9** [comment]
>  Unfortunately, inference from a function will only try the last overload signature.

If this rule is applied, the behavior of the `Array.prototype.filter` is understood.

> TypeScript chooses the first matching overload when resolving function calls.
>
> https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#ordering

I was a little confused because the type inference of the overload "function call" and the "overload function" were different.

Now I have a better understanding of the overload function.

> ```ts
> function isCoffee<T extends Drink>(value: T): value is T & { type: "coffee" } {
>   return value.type === 'coffee';
> }
> ```

Also, I think this method is great. Thank you for answer!
