### ISSUE TITLE
Regression from 4.2 to 4.3 : RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by JSteunou** [microsoft/TypeScript#45632]
# Bug Report

Since TypeScript 4.3 we are unable to run TypeScript check on our projet (more than 10.000 ts modules)
We are trying to upgrade from TypeScript 4.0 to 4.4 and stuck on 4.2

The error is quite generic `RangeError: Maximum call stack size exceeded` 

If there is a way to get more log or to see which module trigger this behavior it would help a lot!

Maybe close to #44281?

### 🔎 Search Terms

* 4.3
* 4.4 
* RangeError: Maximum call stack size exceeded
* Circular dependency
* Recursive

### 🕗 Version & Regression Information

- This changed between versions 4.2 and 4.3 (still present in next / 4.5-dev)

### ⏯ Playground Link

Sorry no playground I'm unable to isolate the part linked to the bug

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

```
 tsc --noEmit --project tsconfig.ci.json
/project/node_modules/typescript/lib/tsc.js:90672
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at checkExpressionWorker (/project/node_modules/typescript/lib/tsc.js:62461:39)
    at checkExpression (/project/node_modules/typescript/lib/tsc.js:62428:38)
    at getTypeOfExpression (/project/node_modules/typescript/lib/tsc.js:62382:24)
    at getMatchingUnionConstituentForObjectLiteral (/project/node_modules/typescript/lib/tsc.js:54126:40)
    at discriminateContextualTypeByObjectMembers (/project/node_modules/typescript/lib/tsc.js:56777:20)
    at getApparentTypeOfContextualType (/project/node_modules/typescript/lib/tsc.js:56789:93)
    at getContextualTypeForObjectLiteralElement (/project/node_modules/typescript/lib/tsc.js:56696:24)
    at getContextualType (/project/node_modules/typescript/lib/tsc.js:56855:28)
    at hasContextualTypeWithNoGenericTypes (/project/node_modules/typescript/lib/tsc.js:55760:17)
    at getNarrowableTypeForReference (/project/node_modules/typescript/lib/tsc.js:55766:53)
error Command failed with exit code 1.
```

### 🙂 Expected behavior

no error :)

**Comment by andrewbranch** [comment]
Possibly related/duplicate https://github.com/microsoft/TypeScript/issues/45576

**Comment by andrewbranch** [comment]
Ah, if it's happening in 4.3 it's more likely related to #44281

**Comment by andrewbranch** [comment]
> If there is a way to get more log or to see which module trigger this behavior it would help a lot!

You should be able to get some info by following the tracing instructions in the wiki: https://github.com/microsoft/TypeScript/wiki/Performance-Tracing

Let us know if that helps you solve the problem or create a repro.

**Comment by JSteunou** [comment]
Thank you @andrewbranch for the hints. Looking at #44281 it is closed, but my issue is still happening in `@next (4.5-dev)` version so either the fix is not really merged yet, or this issue is not related :/ 

Will continue to debug / trace today

**Comment by andrewbranch** [comment]
One common root cause of #44281 was fixed, but it has become clear there are more, but we haven’t been able to identify common patterns yet. Really hoping your tracing session helps us figure it out 😄

**Comment by JSteunou** [comment]
Ok we succeed to isolate the issue in our base code, but it is very hard yet to reproduce it in a playground.

To sum it up, there are 2 files involved, one full of type def, the second with types & components. There is some circular dep because the 1st import some types from the second, and the second import some types from the 1st. Checking those files with tsc separately does not trigger the error, **BUT**, here is the issue, when those two modules are imported together in another module, then :boom:

**Comment by JSteunou** [comment]
@ahejlsberg tested with `4.5.0-dev.20211101` and the issue is gone! Good job thank you :+1:

**Comment by andrewbranch** [comment]
@JSteunou thanks for testing!
