### ISSUE TITLE
Intersection produces duplicate overloads in resulting type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4564]
```TypeScript
interface I1 {
    a(x: number, y: string): void;
}

interface I2 {
    a(x: number, y: string): void;
}

var v: I1 & I2;

v.a/*requestQuickInfoHere*/(/*requestSignatureHelpHere*/
```

![uselessoverloads](https://cloud.githubusercontent.com/assets/972891/9588334/8106f92a-4fdc-11e5-9041-e1c5dcf9a020.gif)

**Comment by mhegazy** [comment]
this is identical to the behavior if you specified two identical overloads

```ts
interface I1 {
    a(x: number, y: string): void;
    a(x: number, y: string): void;
}
```

**Comment by ahejlsberg** [comment]
This is by design and per spec. Not sure it is worth the effort to deduplicate the set and it wouldn't affect the outcome of overload resolution.
