### ISSUE TITLE
IndexedDB types are missing from lib.webworker.d.ts

### ISSUE THREAD

**Issue by bschlenk** [microsoft/TypeScript#45649]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2017` and my *lib* is `the default`.

## Missing / Incorrect Definition

I don't see `IDBArrayType` in what is published, but I do see it in the repo.

- Does not exist in this: https://unpkg.com/typescript@4.4.2/lib/lib.webworker.d.ts
- Does exist in this: https://github.com/microsoft/TypeScript/blob/main/lib/lib.webworker.d.ts#L1692

## Sample Code

N/A

## Documentation Link

Could not find anything...

**Comment by andrewbranch** [comment]
The `lib` folder contains the previous stable version of the compiler. The libs have changed since then and that type was deleted. It’s equivalent to `IDBValidKey[]`.
