### ISSUE TITLE
insertSpaceAfterOpeningAndBeforeClosingEmptyBraces is inconsistent between editor and tooling

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#45645]
Follow up on #45501

# Bug Report

### 🔎 Search Terms

- format / formatting
- `insertSpaceAfterOpeningAndBeforeClosingEmptyBraces`

### 🕗 Version & Regression Information
4.5.0-dev.20210830

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.5.0-dev.20210830#code/IwAgPmIN4gvg3EA

### Bug

Format code such as:

```ts
1 || { };
```

In VS Code using typescript nightly, this preserves the space between the braces

However in the playground or when using tools like typescript-formatter, the space is removed. This is also the behavior on slightly older TS versions, such as 4.5.0-dev.20210816

**Comment by andrewbranch** [comment]
It looks like the default is set in the editor settings:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/3277153/131404958-7aeae60e-ffb5-40ea-af1c-c69e517781f9.png">

The new behavior obeys this setting consistently. However, I wasn’t aware that the default would be leaving/inserting the space—the default in our language service is for no space. @mjbvz does the default just need to be toggled to false in the extension, or do you think we need to break this setting into two: one for object literals and one for blocks?

**Comment by mjbvz** [comment]
Ah yes good call! I added that to our tsfmt settings but it looks like it never gets passed through. Will open a bug against typescript-formatter

I don't think we need a new formatter setting

**Comment by andrewbranch** [comment]
I do think we should consider changing the default value in the extension to be unchecked though; it is pretty unconventional to write empty object literals with a space in them. Empty blocks, on the other hand, are rare enough that I don’t think there is a strong convention.

**Comment by mjbvz** [comment]
Sounds good. I'll make the change on the VS Code side and see if there's any feedback during 1.61 insiders

**Comment by mjbvz** [comment]
The main place we use them in the VS Code codebase is:

```
	constructor(
		readonly action: modes.CodeAction,
	) {}
```

Right now these have spaces but after the change they would not

**Comment by mjbvz** [comment]
Actually let's talk about since this in our sync as it does seem to cause quite a few formatting changes in our codebase
