### ISSUE TITLE
Wrong type inference when returning generic function call directly

### ISSUE THREAD

**Issue by ticklepoke** [microsoft/TypeScript#45655]
# Bug Report

### 🔎 Search Terms

`return type` `generics` `cast` `type inference`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `type inference`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcA8AVAfACgB4D8AXIhgJQkaIDeAUIogE4CmUIjS+iAhgM6LgA1mDgB3MGR78MAbloBfWrVCRYCRACNujHBURgQAWw3NGNeoggJeUJogC8yVLrkMWbDkzmLl4aPCQtAC9dEgNjU3M3VnYkFDgXBSA)

### 💻 Code

```ts
function foo<T>(x?: T): T {
  return (x as unknown) as T;
}

function bar(): number {
  const r = foo();
  return r; // Type unknown is not assignable to type number
}

function baz(): number {
  return foo(); // No error here
}
```

### 🙁 Actual behavior

No error for return line in `baz`

### 🙂 Expected behavior

There should be an error for return line in `baz`: `Type unknown is not assginable to type number`, similar to that in `bar`

**Comment by MartinJohns** [comment]
> There should be an error for return line in baz: Type unknown is not assginable to type number, similar to that in bar

The inferred generic type in `baz` is `number`, not `unknown`. Here TypeScript is able to infer it based on the return type of the `baz` function (because you return it directly). This association can't be made in `bar` because you first store it in a variable.

**Comment by pluma** [comment]
I think the argument is that the type inference in `bar` should back-propagate from the designated return type of the function all the way into the call of `foo()` rather than stopping at the assignment where `unknown` is inferred because there's no hint.

I can see how this might be too difficult to implement though.

**Comment by ticklepoke** [comment]
> I think the argument is that the type inference in bar should back-propagate from the designated return type of the function all the way into the call of foo() rather than stopping at the assignment where unknown is inferred because there's no hint.

I initially opened this issue with the impression that the bug is at `baz` (missing error). However it seems like the type inference for `foo` is by design and I will have to create a work around.

**Comment by MartinJohns** [comment]
> I think the argument is [..]

That's not what he wrote in "Expected behaviour". :-)

> I can see how this might be too difficult to implement though.

I think this was mentioned several times already, that it's too computationally expensive to keep track of all the variables.

**Comment by ticklepoke** [comment]
Here's a workaround using function overloading to avoid type inference in `baz`:

```ts
function foo(): undefined;
function foo<T>(x: T): T;
function foo<T>(x?: T): T | undefined {
  return (x as unknown) as T;
}

function bar(): number {
  const r = foo();
  return r; // Type undefined is not assignable to number
}

function baz(): number {
  return foo(); // Type undefined is not assignable to number
}
``

**Comment by MartinJohns** [comment]
@ticklepoke That's a much cleaner approach, and it doesn't even require the type assertion anymore.

Remember folks: Type assertion means loss of type-safety.

**Comment by pluma** [comment]
> That's not what he wrote in "Expected behaviour". :-)

I'm aware. I was going by the preceding conversation I had with them on the TypeScript Discord.
