### ISSUE TITLE
Enum string values do not work with switch cases for string literal union types

### ISSUE THREAD

**Issue by KTGLeiden** [microsoft/TypeScript#45654]
# Bug Report

When using an `enum` with string values and converting it to a string literal union type, using the original `enum` in a switch case does not fully compile. TS recognizes the options but does not understand that all cases are covered.

### 🔎 Search Terms

string literal enum switch case

### 🕗 Version & Regression Information

It seems that this has never worked since TS 4.1 was released.
- I was unable to test this on prior versions because the construct `${enum}` was introduced in 4.1.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210831#code/KYOwrgtgBAGlDeAoKKoEEoF4oHI04BplUAhLXEw4lAYXJxp0QF9FEAXATwAdgoAPACo8+2AAYASeDGZiA3FAD0i3PigAfCjg25GbZVAAiAe2ABnKCGPsoAd2MAnANYAuKADEwIAMbsAlsYgUAA2AIbeThagACZ+IADmUA7A7GAOQWbsoezAEKA2oSDRSSlpQVy8UNGmFlY2cd7BYNF8OF4tAGZxwNFM3oGZUDmD2AAU-G5CIgCUbuAQAEbADlgAfAjUUGa2fuzeABZQ49MbqGdQ3qFmfDAAdGgum+eoyanpUACMck+ol9ewtxIj2ez1eZSgACZviCLlcbrcaMCYS9Su8AMzQ1CsViIAwAdUckUQ-RAg2G7Ah5HGk2EvFmlkgSxWmHWSDO212ByO-BObJBf1a+CRyJKbyCXx+KAFWmFyLB7yhkth-wYOFlMPlQQxm2xbCAA)

### 💻 Code

```ts
enum X {
    A = 'A',
    B = 'B',
    C = 'C'
}

type xType = `${X}`; // 'A' | 'B' | 'C'

// Does not work: Function lacks ending return statement and return type does not include 'undefined'
const test = (x: xType): number => {
    switch (x) {
        case X.A:
            return 1;
        case X.B:
            return 2;
        case X.C:
            return 3;
    }
}

// Works
const test2 = (x: xType): number => {
    switch (x) {
        case 'A':
            return 1;
        case 'B':
            return 2;
        case 'C':
            return 3;
    }
}
```

### 🙁 Actual behavior

A switch case with `enum` values that have strings as backing values does not recognize when all cases are covered and thus will not compile

### 🙂 Expected behavior

A switch case recognizes `enum` values that have strings as backing values and thus compiles when all cases are covered

**Comment by andrewbranch** [comment]
I think this is a side effect of the semi-opaqueness of string enums, i.e., the fact that `"A"` is not assignable to `X.A`. You’re allowed to write the switch statements because _comparability_ of those types is allowed, but narrowing relies on assignability.

**Comment by skrtheboss** [comment]
I have encountered a similar problem:

```typescript
type NumericOperatorS = 'lt' | 'lte';

enum NumericOperator {
    LESS_THAN = 'lt',
    LESS_THAN_EQ = 'lte',
}

function assertNever(value: never): never {
    throw new Error(`Unknown ${value}`);
}

function test(operator: NumericOperatorS): NumericOperator {
    switch (operator) {
        case NumericOperator.LESS_THAN:
            return NumericOperator.LESS_THAN;
        case NumericOperator.LESS_THAN_EQ:
            return NumericOperator.LESS_THAN_EQ;
        default:
            return assertNever(operator) // Operator still of type NumericOperatorS
    }
}

function test2(operator: NumericOperatorS): NumericOperator {
    if (operator === NumericOperator.LESS_THAN) {
        return NumericOperator.LESS_THAN;
    } else if (operator === NumericOperator.LESS_THAN_EQ) {
        return NumericOperator.LESS_THAN_EQ;
    } else {
        return assertNever(operator) // Works
    }
}

function test3(operator: NumericOperatorS): NumericOperator {
    switch (operator) {
        case 'lt':
            return NumericOperator.LESS_THAN;
        case 'lte':
            return NumericOperator.LESS_THAN_EQ;
        default:
            return assertNever(operator) // Works
    }
}
```

As far as i can tell all three function should behave the same? Or am I wrong?

**Comment by huangzl97** [comment]
I also feel the similar confused about the numeric literal enum: 

⏯ Playground Link
[Playgroupd Link](https://www.typescriptlang.org/play?#code/KYOwrgtgBAcpwCcCWBjAouaBvAUFWA9lALxQAMANHlAJrADOJUAjFQL444BmYIKALkgIgoCBgAdhAEwAUEBvQCGAc2AAuWPGTpMASg0A3AkilRc+MfzAIRRk+QDcODjgD0rwlBQEI4pABtEKEQEAgQcMXpJEFkAZl0nbl4BIRFI6PpgADEwgFUQVLkFFXVyAB9mfSg7U3NRYCsbauNTMicXdygAQQRleBB+KAIuKH4AT3FgKAByWOmoJEYQAkHFenokZRBFACNA0aJxRQRFeX4g4dGJqemyKDKWaYA6CIlhTJyEfML4pyA)

```ts
enum NumericEnum {
  No = 0,
  Yes = 1,
}

function respond(message: NumericEnum): void {
  return void 0;
}

// No compiler error
respond(3);

function responseForUnion(message: 0|1): void {
  return void 0;
}

// Argument of type '3' is not assignable to parameter of type '0 | 1'.
responseForUnion(3);
```

When we use a numeric literal enum as a function argument type declaration, and call this function with a numeric literal value that is out of range, typescript somehow thought it was type safety.

Idealy using enum as a function type declaration should work just as an union type declaration right?

**Comment by Melcrea** [comment]
I found another solution to get around the problem and to have an error handling at compile time.

`enum NumericOperator {
    LESS_THAN,
    LESS_THAN_EQ,
}

function test(operator: NumericOperatorS): void {
    switch (+NumericOperator[operator]) {
        case NumericOperator.LESS_THAN:
            // Does something
        case NumericOperator.LESS_THAN_EQ:
            // Does something
    }
}
`
