### ISSUE TITLE
Intl types: Better typing for exactOptionalPropertyTypes needed

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#45652]
# Bug Report
I did not find a "planning" issue for related issues.
All delivered types should be safe to use with the new Typescript option.

### 🕗 Version & Regression Information
- I was unable to test this on prior versions because this is a new option

### ⏯ Playground Link

```ts repro
// @exactOptionalPropertyTypes
const IntlOptions: Intl.DateTimeFormatOptions = {
    timeZone: undefined
};
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?exactOptionalPropertyTypes=true&ts=4.4.2#code/PTAEAEFMA8EMGMAuB5ADoglgewHawDYAKATlqpMYgJ4AqV5AzgLABQ8uDioAkjovmkwcAXDz74AdABFYiSDQwBbSADEsxRbMHYcDUAF5QAb1agzoTMoBauSKICuOACaQAZhhyQnrAL4BuViA)
### 🙁 Actual behavior

Type 'undefined' is not assignable to type 'string'.(2322)

### 🙂 Expected behavior

Should compile because undefined is a valid property for that object.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

copied from https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1126

**Comment by orta** [comment]
I'm half-half on this, `undefined` is the default for those values, yes, but it's not documented as something you should really pass in via that MDN page - can you think of a specific reason why we should add this?

**Comment by HolgerJeromin** [comment]
My real world code is something like that:
```ts
let timeZone: string | undefined = getUserTimeZone();
let IntlOptions: Intl.DateTimeFormatOptions = {
     timeZone: timeZone
};
```
refactoring to 
```ts
let timeZone: string | undefined = getUserTimeZone();
let IntlOptions: Intl.DateTimeFormatOptions = {};
if (timeZone) {
    IntlOptions.timeZone = timeZone;
}
```
to make TS happy feels clumsy.

**Comment by orta** [comment]
Yeah, that seems reasonable to me

**Comment by tolysz** [comment]
I would love if the setting of undefined would simply delete the key in the object...i.e. set it to the default of `timeZone?`

**Comment by orta** [comment]
Maybe I'm also confused, but point is what this issue is about. The change would allow all three options by adding `| undefined` in the `.d.ts` which you can see in https://github.com/orta/TypeScript/commit/689bf6f4be4bf7d66ef38933e8fa219d4f4e3139

**Comment by fatcerberus** [comment]
@tolysz 
```ts
delete foo.optional;
```

**Comment by orta** [comment]
This is included with https://github.com/microsoft/TypeScript/pull/45647 👍🏻
