### ISSUE TITLE
Type guard not working in nested conditional types

### ISSUE THREAD

**Issue by 07akioni** [microsoft/TypeScript#45651]
# Bug Report

### 🔎 Search Terms

type guard, nested conditional types

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- ✅ This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAggJnACgJwPZgCqoPICMBWEAxsADx75QQAewEAdnAM5SoHHAA0UK6VtDZlCbBkAS3oBzAHxQAvDzRh+dRiwDWEEKgBmUCgCgoUAPz6CAbV5gAuisEsArvXX1UAd3oWbR46agWAHTBFFZKNj5+UABcUPQQAG4QyL6x8UnIQA

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
type AddPropToObject<Obj extends object, Prop extends string> = Prop extends keyof Obj
  ? Obj[Prop] extends unknown[]
    ? [...Obj[Prop]]
    : never
  : never
```

### 🙁 Actual behavior

`Obj[Prop]` is not viewed as an array.

![image](https://user-images.githubusercontent.com/18677354/131442681-6a8ca7ad-686e-4ba1-b6d7-5c8501732178.png)

### 🙂 Expected behavior

`Obj[Prop]` should be viewed as an array.

**Comment by andrewbranch** [comment]
Looks like we’re failing to create/use a substitution type here on the indexed access type. It works if you move the inner conditional type into its own type alias.

**Comment by andrewbranch** [comment]
Note to self or other future fixer: use #46145 as another test case
