### ISSUE TITLE
lib.dom.ts `MediaDeviceInfo` does not include `getCapabilities` function

### ISSUE THREAD

**Issue by uahnbu** [microsoft/TypeScript#45660]
# lib Update Request

## Configuration Check

```json
{
  "lib": [
    "DOM",
    "DOM.Iterable"
  ]
}
```

## Missing / Incorrect Definition

There's no function `getCapabilities` in `MediaDeviceInfo` objects.
I currently have to declare my own type
```typescript
type VideoInputDeviceInfo = MediaDeviceInfo & {
  getCapabilities(): MediaTrackCapabilities
};
```

## Sample Code

```typescript
navigator.mediaDevices.enumerateDevices().then(devices => {
  devices.forEach(device => {
    if (device.kind !== 'videoinput') return;
    const videoDevice = device as VideoInputDeviceInfo;
    console.log(videoDevice.getCapabilities());
  });
});
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceInfo/getCapabilities

**Comment by orta** [comment]
It's not supported in enough browser engines to be added to the DOM APIs yet I'm afraid - looks like just Chromium

**Comment by uahnbu** [comment]
Oh I thought it goes along with `getUserMedia`. Is there any other way to check if the device has a back camera (environment) without request for camera permission?

**Comment by orta** [comment]
The APIs can exist in the runtime, you'd just need to see if it's on DefinitelyTyped or you can add a d.ts file which adds those API definitions to your project for TypeScript.

**Comment by uahnbu** [comment]
Thank you. I think I'll just add a info if `getCapabilities` is not supported and escape the checking function.
