### ISSUE TITLE
control flow analysis incorrectly narrows type to `never` when type-guarded

### ISSUE THREAD

**Issue by pomack** [microsoft/TypeScript#45664]
# Bug Report

The new control flow analysis incorrectly narrows a type that is type-guarded to fallback to `never` in the else clause when they should either remove the type-guarded type or stay the original type if not explicitly typed earlier. They should only fallback to `never` when all types are exhausted (if enum or was an initial set of types).

### 🔎  Search Terms

`control flow analysis`
`never`
`type narrowing`
`type guard`

### 🕗  Version & Regression Information

- This changed between versions 4.3.5 and 4.4
- This is still a problem in 4.5.0 nightly as of 2021-08-31

### ⏯  Playground Link

[Playground link for 4.3.5 (no error)](https://www.typescriptlang.org/play?ts=4.3.5#code/JYOwLgpgTgZghgYwgAgEIHsAeyDeAoZQ5YAZwGUBbOAG2o0wAoBKALmTAAtTiTlKa6WANwEipADJwoAcwj1mbTt26SZc4aMIk4ATwASEWugXI4IHSIC+ePKEixEKfrXrIImSCAAmvV-iLI2vqG1MasgWBQoNJWNnbQ8EjIqrKu7p4+aFi4moG6BkYmIACuFABG0LF4COggJGDIZWzOgpgAPinq2AC8OQGkLfJMuMhQEGDFUCDI8NQkEELIlgA0uRJSqVjMI2MTU+xQxQtLqwFBBaHbOKPjk9MADAB0AOzPAMwALIvW1tW19TxOq5emVHus1EMRLYYAxwZtMMN-ERQecQmErG45igkYQUfk0cxYkA)

[Playground link for 4.4.2 (error)](https://www.typescriptlang.org/play?ts=4.4.2#code/JYOwLgpgTgZghgYwgAgEIHsAeyDeAoZQ5YAZwGUBbOAG2o0wAoBKALmTAAtTiTlKa6WANwEipADJwoAcwj1mbTt26SZc4aMIk4ATwASEWugXI4IHSIC+ePKEixEKfrXrIImSCAAmvV-iLI2vqG1MasgWBQoNJWNnbQ8EjIqrKu7p4+aFi4moG6BkYmIACuFABG0LF4COggJGDIZWzOgpgAPinq2AC8OQGkLfJMuMhQEGDFUCDI8NQkEELIlgA0uRJSqVjMI2MTU+xQxQtLqwFBBaHbOKPjk9MADAB0AOzPAMwALIvW1tW19TxOq5emVHus1EMRLYYAxwZtMMN-ERQecQmErG45igkYQUfk0cxYkA)

[Playground link for 4.5.0-dev.20210831 (error)](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210831#code/JYOwLgpgTgZghgYwgAgEIHsAeyDeAoZQ5YAZwGUBbOAG2o0wAoBKALmTAAtTiTlKa6WANwEipADJwoAcwj1mbTt26SZc4aMIk4ATwASEWugXI4IHSIC+ePKEixEKfrXrIImSCAAmvV-iLI2vqG1MasgWBQoNJWNnbQ8EjIqrKu7p4+aFi4moG6BkYmIACuFABG0LF4COggJGDIZWzOgpgAPinq2AC8OQGkLfJMuMhQEGDFUCDI8NQkEELIlgA0uRJSqVjMI2MTU+xQxQtLqwFBBaHbOKPjk9MADAB0AOzPAMwALIvW1tW19TxOq5emVHus1EMRLYYAxwZtMMN-ERQecQmErG45igkYQUfk0cxYkA)

### 💻  Code

```ts
interface Box {
    isSmallBox(): this is SmallBox;
    isLargeBox(): this is LargeBox;
    sayHello(): any;
}

interface SmallBox extends Box {
    sayHello(): string;
}

interface LargeBox extends Box {
    sayHello(): number;
}

const b: SmallBox|LargeBox = {
    isSmallBox() { return false; },
    isLargeBox() { return true; },
    sayHello() { return 0.7734; }
}

const isLargeBox = b.isLargeBox();

if(isLargeBox) {
    b.sayHello();
} else {
    b.sayHello();
}
```

### 🙁 Actual behavior

The last `b.sayHello()` has `b` as type `never`, causing an error.

### 🙂 Expected behavior

The last `b.sayHello()` should have `b` as type `SmallBox`

**Comment by MartinJohns** [comment]
This is the correct behaviour. Your variable `b` is **not** typed `SmallBox | LargeBox`, it is typed `LargeBox`. TypeScript correctly sees that the value `isLargeBox` is **always** `true`, and as a result you end up with `never` in the `else`-branch.

You see the behaviour you expect if you type `b` as `SmallBox | LargeBox`, e.g. using a type-assertion: `const b = { ...} as SmallBox | LargeBox`.

**Comment by MartinJohns** [comment]
That `b` is narrowed to `LargeBox` despite your explicit type annotation `SmallBox | LargeBox` is intentional as well. Assigning a value to a variable narrows the variable to the assigned type. Otherwise code like this would not work:

    const value: number | undefined = 123;
    value.toString(); // If this were still typed `number | undefined` then we couldn't call the function.
    // But TypeScript can see that a number is always assigned and the value can't be `undefined`.

**Comment by andrewbranch** [comment]
> TypeScript correctly sees that the value `isLargeBox` is **always** `true`

To clarify, it sees this not because of the `return true` in the object literal initializer; it sees this because of everything else @MartinJohns explained; that `b` is immediately narrowed to `LargeBox` and then it simply looks at `this is LargeBox` and says “yep, it sure is.”

**Comment by ilogico** [comment]
I don't think TypeScript sees `isLargeBox` always returns true.
Instead, I think it sees `sayHello()` return `number`, making `b` a `LargeBox`, which means `b` has an impossible type in the `else` statement.

You can validate this by checking that `b.sayHello()` returns `number`  before any narrowing. But `b.isLargeBox()` is still described as returning an open value: `this is LargeBox`. TypeScript doesn't look into the function's implementation to see if it always return `true` or not.

**Comment by MartinJohns** [comment]
@andrewbranch This updated example actually looks like a bug of the #44730 feature. `a.isLargeBox() || b.isLargeBox()` should not narrow `a` to `LargeBox`.

**Comment by pomack** [comment]
Thanks @MartinJohns Will add the explicit attribute.
