### ISSUE TITLE
Double implicit cast of optional function arguments allows a callback to receive the wrong types

### ISSUE THREAD

**Issue by keeslinp** [microsoft/TypeScript#45666]
# Bug Report

### 🔎 Search Terms
optional argument cast callback 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about substitutability

There is a FAQ for half of this bug https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.7.5&ssl=10&ssc=28&pln=11&pc=41#code/MYewdgzgLgBFCm0DMMC8MAUwBGAuTAhgE4DmAjPtEQJZgkCUaAfDAG4jUAmjqLA3gCgYMHBgBECaGPoCAvgIGhIsSVABMaTDnwYeLdlz0xBw1UizYZ8xeGhxEsdLubGh96GowZWBADYB+fDAAVwBbbHgiIxNhEVsQX3gAOl8QEgwoAE8AB3gQADM2P0YAehKYAFEAD1zgWBDwyJhsYNhqWGyaMCgIGCpaEjdZKwFVXSA)

### 💻 Code

```
const test3 = (cb: (arg1: string) => void) => {
  cb("test")
}

const test2 = (cb: () => void) => {
  test3(cb)
}

const test = () => {
  test2((val?: number) => {
    console.log(typeof val) // Expect number but it prints string
  })
}
test()
```
### 🙁 Actual behavior
This type checks just fine and prints out "string"

### 🙂 Expected behavior
This should fail somehow because it is unsound. I'm not sure where it should fail and maybe this is just an accepted bug, but if that is the case then the FAQ should be updated to reflect that you can make unsound behavior by implicitly casting functions with optional parameters.

**Comment by MartinJohns** [comment]
Duplicate of #13043. Used search terms: `callback optional unsound`

**Comment by keeslinp** [comment]
> This doesn't seem to be an issue in practice, and our appetite for breaking changes diminishes every day.

I guess there's no desire to fix this. Thanks for linking the other issue 👍

**Comment by MartinJohns** [comment]
> I guess there's no desire to fix this.

As far as I understood there simple is **no good way** to fix this, without introducing a whole other can of issues.
