### ISSUE TITLE
Support 'did you mean' for assignments to unions with string literals

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript#45679]
# Suggestion

```ts
type A = "abc" | "abcd" | "abcde";
const a: A = "abb";
// Type '"abb"' is not assignable to type 'A'.
```

Could instead be:

```ts
type A = "abc" | "abcd" | "abcde";
const a: A = "abb";
// Type '"abb"' is not assignable to type 'A'.
//   Did you mean "abc"?
```

## 🔍 Search Terms

did you mean literals unions assignment

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

If we already know all/a set of the possible entries, it can't hurt to see if any are close enough and try recommend them like we do in other places.

My actual case was this:

```
src/compiler/commandLineParser.ts:1088:13 - error TS2322: Type '"strong"' is not assignable to type '"string" | "number" | "boolean" | "object" | ESMap<string, string | number> | "list"'.

1088             type: "strong",
                 ~~~~

  src/compiler/types.ts:6272:9
    6272         type: "string" | "number" | "boolean";
                 ~~~~
    The expected type comes from property 'type' which is declared here on type 'CommandLineOption'
```

Where we know a set of literals and a non-literal are possible, and as I was very close to one I figured TS would have enough knowledge to offer the case for what the typo probably is.

## 💻 Use Cases

Just dev workflow stuff.

**Comment by DanielRosenwasser** [comment]
I think when I last checked, spelling suggestions operate on `__String`s, which might've given me some "stop" energy when I last looked into this. @sandersn might have some insight into how difficult this would be.

**Comment by sandersn** [comment]
Completions already work, and you can cast any string to `__String` without a problem, so I think it should be straightforward.

**Comment by DanielRosenwasser** [comment]
Thanks @hi-ogawa!
