### ISSUE TITLE
Generic union type inferred differently from equivalent direct union type

### ISSUE THREAD

**Issue by captain-yossarian** [microsoft/TypeScript#45676]
# Bug Report

### 🔎 Search Terms

I found a question on [StackOverflow](https://stackoverflow.com/questions/64405477/generic-union-type-inferred-differently-from-equivalent-direct-union-type)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgdwE4EMwDkCuAbbKBG2EAjFALxQBKEAjpgJZIQAmAPAN5QAeA-AFxQAFKQA+UTHGYQAZvTgsAlFAC+APgDaAIi6aAugFgAUEdCRYiVBhx5CEVgBVV5KrQZM2nXgPsqN2vUYm4ND2EADOwM7wyGhYuARErKLikjJyLKpAA)

### 💻 Code

```ts
type UnwrapNullable1 = Required<{ x?: (1 | undefined) }>["x"] // 1

type UnwrapNullable<T> = Required<{ x?: T }>["x"]

type Test = UnwrapNullable<1 | undefined> // 1 | undefined
```

### 🙁 Actual behavior

Test is `1 | undefined`

### 🙂 Expected behavior

Test should be `1`

**Comment by IllusionMH** [comment]
Please note that with `exactOptionalPropertyTypes` enabled - it no longer strips `undefined` from `UnwrapNullable1` (as `Required` only removes optionality (as was mentioned on SO)

![image](https://user-images.githubusercontent.com/1312662/131643443-b2a41508-b211-45d1-9ea2-5112e3efbbee.png)

**Comment by captain-yossarian** [comment]
@IllusionMH Thanks, my bad, seems to be this is not an issue no more
