### ISSUE TITLE
`never extends never ?` works inconsistently when using generic type

### ISSUE THREAD

**Issue by k8w** [microsoft/TypeScript#45674]
# Bug Report

### 🔎 Search Terms
- nerver extends never

### 🕗 Version & Regression Information
4.4.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTAEEYCgBcE8AcCmoB25QF5WIG6IE6iIAe0iKAJgM7Z6ED8EoAXKAEwDckMCyAklQByuAgB4AKgD5MocUVLlqtAqEbpWnSCGX4eSVGxkDhdUShH5JkIA

### 💻 Code

```ts
// 1
type n1 = never extends never ? 1 : 2;

type IsNever<T> = T extends never ? 1 : 2;
// never
type n2 = IsNever<never>
```

### 🙁 Actual behavior
`n1` and `n2` is different.

### 🙂 Expected behavior
`n1` and `n2` is the same.

**Comment by MartinJohns** [comment]
[Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types)

**Comment by k8w** [comment]
Thanks.
It seems that `never` is treated as empty Union.

**Comment by MartinJohns** [comment]
> It seems that `never` is treated as empty Union

That's exactly what `never` is: an empty set.
