### ISSUE TITLE
Typescript: node_modules/@types/babel__traverse/index.d.ts:68:50: ']' expected.

### ISSUE THREAD

**Issue by Deepangose** [microsoft/TypeScript#45677]
We're getting below issue while building our angular based react project.

![image](https://user-images.githubusercontent.com/56765950/131666186-3eaaec69-f700-48b9-8f26-afd44367a1ba.png)

React app version: 16.13.1
Angular: 4.3.6
Typescript: 2.5.2

Could anyone please help me on this to be fixed?

**Comment by MartinJohns** [comment]
That doesn't look like an issue with TypeScript, but with Angular.

**Comment by Deepangose** [comment]
But I can see different error if I upgrade typescript

**Comment by IllusionMH** [comment]
> Typescript: 2.5.2

Is it correct TS version? I think definitions (DT tests only 3.7+) has new syntax that not supported by TS version from 4 years ago.

**Comment by nmain** [comment]
Yes, if you'd like to use current NPM packages, you'll need to upgrade the 4 year old typescript and upgrade the 4 year old angular.
