### ISSUE TITLE
Builds with Rollup hang and never finish

### ISSUE THREAD

**Issue by jonkoops** [microsoft/TypeScript#45680]
# Bug Report

### 🔎 Search Terms
rollup, build hang, watchers

### 🕗 Version & Regression Information

This bug was noticed in version 4.4.x and looks to be fixed in the `next` version.

### 💻 Code

There is no specific code involved. https://github.com/ptv-logistics/Leaflet.NonTiledLayer/pull/116 can be used as a means to reproduce the issue.

### 🙁 Actual behavior

Compilation using the TypeScript plugin for Rollup should finish.

### 🙂 Expected behavior

Compilation using the TypeScript plugin for Rollup never finishes.

More information can be found in the bug report on the Rollup repo (https://github.com/rollup/plugins/issues/983). Considering this is a very popular package it might be worth to release a patch version to fix the issue.

**Comment by MartinJohns** [comment]
This sounds like a duplicate of #45633.

> This bug was noticed in version 4.4.x

Patch versions matter! :-o

**Comment by jonkoops** [comment]
@MartinJohns Yes, this is indeed a duplicate of that issue. I'll go ahead and close this one.
