### ISSUE TITLE
[VS2013/VS2015] Closing tag is indented incorrectly after 'format document' operation

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#4568]
- create a new .tsx file with content
```ts
<div>
</div>
```
- select all -> format document

**Expected:** formatting stays the same
**Actual:** closing tag is indented

![formatclosingtag](https://cloud.githubusercontent.com/assets/8052307/9590717/495e58ec-4feb-11e5-9c16-da45220c76fd.gif)

**Comment by SaschaNaz** [comment]
#3838 should fix this.

**Comment by SaschaNaz** [comment]
#4398 should fix this.

**Comment by DanielRosenwasser** [comment]
Fixed by #4398. Thanks @SaschaNaz!
