### ISSUE TITLE
Type inference of inline expression should be treated the same as extracted untyped const

### ISSUE THREAD

**Issue by Pyrolistical** [microsoft/TypeScript#45683]
# Bug Report

The following two are equivalent semantically, therefore typescript should treat them the same, but right now the later errors. See playground link for all the cases.

```ts
// this works
greet({
    type: 'student',
    gpa: 4
})

// this errors
const student3 = {
    type: 'student',
    gpa: 1
}
greet(student3)
```

Error
```
Argument of type '{ type: string; gpa: number; }' is not assignable to parameter of type 'Person'.
  Type '{ type: string; gpa: number; }' is not assignable to type 'Student'.
    Types of property 'type' are incompatible.
      Type 'string' is not assignable to type '"student"'.
```

### 🔎 Search Terms

- const
- inline
- type inference
- escape analysis
- untyped

### 🕗 Version & Regression Information

Linked playground is for nightly v4.5.0-dev.20210901

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210901#code/C4TwDgpgBAChBOBnA9gOygXgFBV1APlAMrACuAJhKsDnoQCoQCGAxgBYIDcWWAltQgBmraCQpVgUAN61coSAC4oAckRlK1ZdzxQA5mCZLUpALYAjLlgC+PfsCEiojVh3jTZUeRCXL7LhFoeiEwANkzwIEamFvDcNliCpKgswLxoevAQEMAAFJBIaEpwBagAlO46iADuvMDsUHkIKKgAdF7lMjo6LEyI0KrqEsoKHl14mWTw6CxoKCEQLSHIujkABqi8LND6TFDIglAAJFL5zS07Vqul2mNQPX0qfuwBI7ddE6RTd7PI84vLaw2WygwTCET2B2OpzQLVB4RAl2uozwlGEpBCwFebzwAHocVBUBAAG4IDw2eJ4qD8EL8aA9EIhRBQKrIeAAawANFBep5wBBECx4LwwJIeugzPxyFAIAAPMCZRCINLoYDIDJZXLFZrlLxQci8TIpEIgLC6TLZHKdPBeHxqcSaDkeHZKAAs1lKpvNuStcj5PiermUjsqoXhroADJHw+6eJSvFKieEmSz2VyeV4BUKRXcmOLJdK5QqlelVbAmiW+XqDRAjSaZqg1CDBtQAIxFcvoDAVa1+lR2jTAINOgxKADM1k9Gpy-YkLY99cbAYQbbLJUw3d9ikezGe8CHIbBkSgo6j0ZsZqnS-gc9j+KS8agiaQzNqbG5TIXkhTnPfvMgmeFSRgEyJhJDUIVUF0JkeRpewhVCRAsE-Jt7WAAAmdcfT-bw+2bQdf0-YM8GdKA0InC8LRnag0PnWYgJ3VwMK7LCbW3fw9wIuiiNwOEIiUNDT3Ir0civGjbyge8+QTJM9TQXxmVZNkAH4lKgMxSCAjgQBBNhkHRKVvypA4M0FQCoAAK1IRtyGQfkQWQEwICwSklRMMB5mlAUmEgblUFCEAlSZUs+mgYA2FAlCB1HXypSvaLwjpOiWmc-Ewt4JlEF0-S1NCkD7ClVA1X1QRBAQCRPHC9BqX4fhdE8NVEmSVI0CQujIokaLmI8ViBlQ-diJHKAWyEqcqOAUdaIbej2M6jdsP9BiAm4kFQz4obBPPYS4o9LAgA)

### 🙁 Actual behaviour
When an inline expression is extracted from a function call to an untyped const immediately before the call site, typescript loses its ability to do type inference even though the code is semantically unchanged

### 🙂 Expected behaviour
Typescript can do escape analysis on variables passed into function calls and do type inference as if it were an inline expression

**Comment by MartinJohns** [comment]
That's what `as const` was added for.

**Comment by Pyrolistical** [comment]
Yes, but I think in this narrow case it should work without the `as const` hint
