### ISSUE TITLE
Synthetic comment duplicated on class with decorators

### ISSUE THREAD

**Issue by crisbeto** [microsoft/TypeScript#45696]
# Bug Report

### 🔎 Search Terms
`setSyntheticLeadingComments`, `updateClassDeclaration`, `transformer`

### 🕗 Version & Regression Information

My project has a custom transformer that declares new `static` properties on classes and attaches comments to them using the `setSyntheticLeadingComments` function. In TypeScript version 4.4 the comments are duplicated if the class has at least one decorator. If the class doesn't have decorators, the comments are emitted only once.

- This changed between versions 4.3.5 and 4.4.2

### ⏯ Playground Link
Since this is a problem with the compiler API, I can't link to the playground. Instead I have isolated the issue in a small repository. 

### **[Link to the reproduction repository](https://github.com/crisbeto/ts-4.4-synthetic-comment)**

To reproduce the issue, do the follwoing:
1. `git clone https://github.com/crisbeto/ts-4.4-synthetic-comment.git`
2. `npm install` inside the repo.
3. `npm run transform`.
4. Observe the console output which contains two comments with the text `/* This should only exist once */` instead of one.

### 💻 Code
This is the same code as the repository that is linked above.

**Transformer that adds the synthetic comment (transform.ts):**
```ts
import * as ts from 'typescript';

const program = ts.createProgram(['./sample.ts'], {
  module: ts.ModuleKind.CommonJS,
  importHelpers: true,
  lib: ['dom', 'es2015'],
  target: ts.ScriptTarget.ES2017,
  declaration: true,
  experimentalDecorators: true,
  emitDecoratorMetadata: false,
});

const transformer: ts.TransformerFactory<ts.SourceFile> = context => {
  return sourceFile => {
    const visitor = (node: ts.Node): ts.Node => {
      if (ts.isClassDeclaration(node)) {
        const initializer = ts.createLiteral('hello');
        const prop = ts.createProperty(
            undefined, [ts.createToken(ts.SyntaxKind.StaticKeyword)],
            'customStaticProp', undefined, undefined, initializer);

        ts.setSyntheticLeadingComments(prop, [
          {
            kind: ts.SyntaxKind.MultiLineCommentTrivia,
            text: ' This should only exist once ',
            pos: -1,
            end: -1,
            hasTrailingNewLine: true,
          },
        ]);

        return ts.updateClassDeclaration(
            node, node.decorators, node.modifiers, node.name,
            node.typeParameters, node.heritageClauses, [...node.members, prop]);
      }

      return ts.visitEachChild(node, visitor, context);
    };

    return ts.visitNode(sourceFile, visitor);
  };
};

program.emit(
    undefined, ((fileName, outputText) => {
      console.log(outputText);
      console.log('---------------------', fileName);
    }),
    undefined, undefined, {before: [transformer]});
```

**File that is being transformed (sample.ts):**
```ts
function MyDecorator<T>(cls: T, ...args: any[]) {
  return cls;
}

@MyDecorator
export class Foo {
}
```

### 🙁 Actual behavior
TypeScript compiles the `customStaticProp` to the following:

```ts
/* This should only exist once */
/* This should only exist once */
Foo.customStaticProp = "hello";
```

### 🙂 Expected behavior
The `customStaticProp` should be compiled to:

```ts
/* This should only exist once */
Foo.customStaticProp = "hello";
```

**Comment by DanielRosenwasser** [comment]
Thanks @mprobst!
