### ISSUE TITLE
[VS2013/2015] Intersection types are formatted incorrectly

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#4569]
Code below does not have correct shape after formatting
```ts
let x :            string            & number
```

![formatcomponentsofintersectiontypes](https://cloud.githubusercontent.com/assets/8052307/9590878/441f862a-4fec-11e5-92a1-a3d233e29aed.gif)

**Comment by mhegazy** [comment]
thanks @SaschaNaz !
