### ISSUE TITLE
Isolated unreferenced files in compiler tests are not compiled by the harness compiler

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#457]
The two tests
* tests/cases/compiler/externalModuleResolution.ts
* tests/cases/compiler/externalModuleResolution2.ts

each have file regions that are not compiled by the test harness. The harness uses only the last file as a root, if the last file has a require or ///reference. All other files are only compiled if they are referenced. The tests mentioned above have file regions that are not referenced by the root file. They need to be converted to project tests.

**Comment by mhegazy** [comment]
Does not seem to be an issue that we run into often. closing for housekeeping purposes.
