### ISSUE TITLE
Private fields in ECMAScript modules

### ISSUE THREAD

**Issue by rauschma** [microsoft/TypeScript#45708]
# Bug Report

### 🔎 Search Terms

* `__classPrivateFieldGet`
* Private fields
* Private class fields

### 🕗 Version & Regression Information

* tsc  v4.4.2

### 💻 Code

For private fields, TypeScript currently emits the following code:

```js
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
```

### 🙁 Actual behavior

esbuild gives me the following warning:

```
> ../stoa/dist/client/util/hydration.js:1:30: warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
    1 │ var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
      ╵                               ~~~~
```

### 🙂 Expected behavior

Ideally, in ECMAScript modules, `this` shouldn’t be used at the top level. Given that the private field helper code must also run elsewhere, maybe the following approach works (instead of using `this`):

```
if (typeof __classPrivateFieldGet === 'undefined') ...
```

**Comment by nmain** [comment]
Closely related:  https://github.com/microsoft/TypeScript/issues/43728

My search terms were "this helper undefined".

**Comment by rauschma** [comment]
Update: My main worry was that this code wouldn’t detect imported helpers, but that’s wrong because it completely disappears when helpers are imported (by setting `importHelpers` to `true`). I’m importing helpers now and the problem is fixed for me.

Thus I’m closing the issue. However, not using `this` is ESM and leaving out the unnecessary part `(this && this.__classPrivateFieldGet)` would still make sense, AFAICT.
