### ISSUE TITLE
Type 'FileList' must have a '[Symbol.iterator]()' method that returns an iterator.

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#45716]
# Bug Report

### 🔎 Search Terms

TS2488 must have a `'[Symbol.iterator]()'`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 'TS2488, iterator'

### ⏯ Playground Link

For some reason I am unable to reproduce this issue in the playground.
But I have created a stackblitz project that demonstrates the issue.
[StackBlitz project](https://stackblitz.com/edit/node-u3fvk4?devtoolsheight=33&file=index.js)
Then in the console type `npx tsc -p jsconfig.json`

#### index.js
```js
const fileList = new FileList();
for (const file of fileList) {
  console.log(file);
}
```

#### jsconfig.json
```json
{
	"compilerOptions": {
		"lib": ["dom", "esnext"],
		"target": "esnext",
		"checkJs": true
	},
	"files": ["index.js"]
}
```
And then run `tsc -p jsconfig.json`

### 🙁 Actual behavior

Error: TS2488: Type 'FileList' must have a '[Symbol.iterator]()' method that returns an iterator.

### 🙂 Expected behavior

It doesn't fail.

**Comment by MartinJohns** [comment]
https://www.typescriptlang.org/tsconfig#lib

You're missing `"dom.iterable"`.

**Comment by jespertheend** [comment]
Ah thanks!

Sorry, it thought that `"lib": ["dom"]` would include all other `dom.*` libs as well.
