### ISSUE TITLE
Type evaluating support for React components with implicit conditional rendering logic

### ISSUE THREAD

**Issue by vasilii-kovalev** [microsoft/TypeScript#45728]
# Suggestion

## 🔍 Search Terms

conditional react, condition react

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The proposal suggests adding a type checking support for React components with implicit conditional rendering logic.
As a minimum, there should be a mechanism of helping Typescript to correctly evaluate types of such components.
As a maximum, on top of that, Typescript automatically can correctly evaluate types in simple cases.

A simple example:
```typescript
import React, { FC, VFC } from "react";

interface ConditionalRendererProps {
  condition: boolean;
}

const ConditionalRenderer: FC<ConditionalRendererProps> = ({ condition, children }) => {
  return condition ? <>{children}</> : null;
};

// Usage
interface User {
  username: string;
}

interface UserProps {
  user?: User;
}

const UserProfile: VFC<UserProps> = ({ user }) => {
  return (
    <ConditionalRenderer condition={user !== undefined}>
      {/* `user` has type User, so `user.username` doesn't throw an error */}
      {user.username}
    </ConditionalRenderer>
  );
};
```

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecBiAwtgGpFwC+cAZlBCHAERSoaMDcAUJ8AHYxIo1dEjiEIvACbAYwCSgA2yKYMEAFOmADOuTnDhoJ02RIBccAEYQIC1Ly4Vuh3lvjipMub0XLJqqOZEADzuxl4+SCosUBoQ2gB8cAC8cAAUeM5hEthoABbACpIsvJQAlMmJOHpwLDAArlAlmZ4ScAD8cEHxOHkFRZEUQQD0iea8dQoKDlycQ0NwAKpaKADmSDz8gsJookuCuvp1WoLeIEjmrlB8Kw7cfAJCIovHMZo6VYcvbeZ7ULeczlcz3UdGoBXOcDIhCCv1iCWSaTwR32FHKSUq1VqDRKqWq+hCRha3iUkT80QMhJMvCSOGRUDgAEIkik6iowbwkJIKPE8fpOrlUGSeXyRbghgAqOAAAzpUrguRQOhgAE8wLsXtgtBBpXSAHR005IOWSCBILS8ADk8BguToAHc4CgSoI6PTxUNHKK+bSXvqXobPaLhgKUELecNQkSIlFBMK4KVptwkAAPSCwXDA14QMG2ShcIA).

## 📃 Motivating Example

This feature would allow writing more elegant and easy-to-read and work with code, without ternaries or logical `&&` operators.

### With the proposed feature

```typescript
import React, { FC, VFC } from "react";

interface ConditionalRendererProps {
  condition: boolean;
}

const ConditionalRenderer: FC<ConditionalRendererProps> = ({ condition, children }) => {
  return condition ? <>{children}</> : null;
};

const isUndefined = (value: unknown): value is undefined => {
  return value === undefined;
};

// Usage
type Status = 'online' | 'offline';

interface User {
  username: string;
  status: Status;

  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: Date;
  bio?: string;
}

interface UserProps {
  user?: User;
}

const UserProfile: VFC<UserProps> = ({ user }) => {
  return (
    <ConditionalRenderer condition={!isUndefined(user)}>
      <header>
        {user.username}
        <div className={user.status} />
        <ConditionalRenderer condition={!isUndefined(user.firstName) && !isUndefined(user.lastName)}>
          <div>{user.firstName} {user.lastName}</div>
        </ConditionalRenderer>

        <section>
          <ConditionalRenderer condition={!isUndefined(user.phone)}>
            <div>
              <span className="title">Phone:</span>
              {" "}
              <span className="description">{user.phone}</span>
            </div>
          </ConditionalRenderer>
          <ConditionalRenderer condition={!isUndefined(user.dateOfBirth)}>
            <div>
              {user.dateOfBirth}
              {" "}
              ({(new Date()).getFullYear() - user.dateOfBirth.getFullYear()})
            </div>
          </ConditionalRenderer>
          <ConditionalRenderer condition={!isUndefined(user.bio)}>
            <p>{user.bio}</p>
          </ConditionalRenderer>
        </section>
      </header>
    </ConditionalRenderer>
  );
};

export { UserProfile };
```

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecBiAwtgGpFwC+cAZlBCHAERSoaMDcAUJ8AHYxIo1dEjiEIvACbAYwCSgA2yKYMEAFOmADOuTnDhoJ02RIBccAEYQIC1Ly4Vuh3lvjipMub0XLJqqOZEADzuxl4+SCosUBoQ2gB8cAC8cAAUeM5hEthoABbACpIsvJQAlMmJOHpwLDAArlAlmZ4ScAD8cEHxOHkFRZEUQQD0iea8dQoKDlyczq5wwFoAqirUfEiSyWkAbop1SOZ1vADWvBAA7ryl5rsK+ws6R35rvBsVuvq1DSW390n-cCeSBeG2m3CGQzgSy0KAA5khODAAJ5gUQAZRgKHqOhSAHIJAp1ri4AAfOD46jUQmvXEzPgCIQiKFaQQfQEsxooEAHOCuKB8WFcfSuLF1LTmDGirQzfRrKCuAByXKQbXMfIFQrgChQiuVqt5MH5vEF1TAuQkKrVho11UkWKQAHlqAAhYCwXL6gAi9s1Fjk+vVxoc3HpgmEaFE0PUmh0VX0YsE+qjUGDswk82TsTWtnMZEIQUzMcSKXS7NZFHKSUq1S+jTS1X0ISMLW8SkifmiBmbJl4SRwAEJFitnutJKkE1BShR4g39J1cqgOzO5yvcBOAHQT7zcxyrudBaTbAzarRaJXcvsbkXYqgjWcrpseHsRKKs5o9vuD5arUfjjnruVdW5coADIQLgL9h2BX8NxPGBzyQKdlz3fdD26DdAPg5UqBwWCdSwndhjQ+99yGUIWxfDtBBnEjGxZDAvGQlDOnI5821fKAuyfLxPyHH9XjHDczQtJDaNXA9gG2JjmP3LQwBQJoTzPZUkkYWQYFsRh4jUc1XlMYY5IU6SZNwRgmF3EzZPkxSdWUi9GD8LQ0H5MAey03D-2E15BiGQzeGMlCiMkgKHzI7twnYqioBC-dWIi3x-C4rJewHPiRwEv9BHXO0BCdV13VEyzOmIor9A8rKcsdF03RgXILKKnAzMYerLPSVJXnOOBvQEVJSlKdd4RgfAJgUABNVAoF6uAAFoyygbL7TymrcgGpAhpG8aUEmqdSjE0KSpk4Y4vkSL-BixtjtbBLO3fHjUu-dKNky+a-QgQrLKCMB0P-V6fK+vbOjC7iTuu6ixIMpAGIkALhgXFAl1nI7wpB9szuqUowU4JAAA9IFgXBmWjCBs1ECguCAA).

### Current approach

```typescript
import React, { VFC } from "react";

const isUndefined = (value: unknown): value is undefined => {
  return value === undefined;
};

type Status = 'online' | 'offline';

interface User {
  username: string;
  status: Status;

  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: Date;
  bio?: string;
}

interface UserProps {
  user?: User;
}

const UserProfile: VFC<UserProps> = ({ user }) => {
  if (isUndefined(user)) {
    return null;
  }

  const {
    username,
    status,
    firstName,
    lastName,
    phone,
    dateOfBirth,
    bio,
  } = user;

  return (
    <header>
      {username}
      <div className={status} />
      {
        !isUndefined(firstName) && !isUndefined(lastName)
          ? <div>{firstName} {lastName}</div>
          : null
      }

      <section>
        {
          !isUndefined(phone)
            ? (
                <div>
                  <span className="title">Phone:</span>
                  {" "}
                  <span className="description">{phone}</span>
                </div>
              )
            : null
        }
        {
          !isUndefined(dateOfBirth)
            ? (
                <div>
                  {dateOfBirth}
                  {" "}
                  ({(new Date()).getFullYear() - dateOfBirth.getFullYear()})
                </div>
              )
            : null
        }
        {
          !isUndefined(bio)
            ? (
                <p>
                  {bio}
                </p>
              )
            : null
        }
      </section>
    </header>
  );
};

export { UserProfile };
```

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecBqAYgMJwC+cAZlBCHAERSob0DcAUO2hAHYDO8YHwCqPACZJKwHkjFwAvHAAUANxQAbAK5IAXHE08A1jwgB3HgEo9arUjhD94ydNkKAfLnZw4TGJqg8cDbaCvKKBhJSMmIcZBzsMACeYHYAyjAofnwKcADkvOouuXAAPnkQlJSFMrnx0jBIUJTodsJ8jZ7emu0BKCC6cAJQ0gDmHN4Cmd166VN88d5SUAIAcn1IAPx6Q6PjcOooq+tbgzDDPGNecGAAFryb22e7V2KZSADylABCwLA3JwARN57ABGwAgJx2F1inHqjWaaFaPQACjQwNkcFduo0Tm1GjCuLwBHA8VBURVgOoBkRiAAeUnk9EeRRKPDYqDkCzuTr2SjKISiSIuMRKdkWLmY7zeXz+QI8TTqdR7MicbzcfjwSVS9k8daYK4TDJZfVSqi-I79E1Sg4WpBW7y3e72uCvBqfH5-Z1giBWijhHoLHxIPwBZQGuC0m6oCRQNzh7w4HXrFWm7y0sTAFRwNA2vhrfryHCTLIUAD0cdTPMrAEIBU4orIlEtbVyAGStuC1kT14VKG0wfNICzx1MbCMZlRuHDNgfJ3D9wdkWmlicVytSvTyxUjlUj2ntDDgnhryta9edutC6JKR0yYfn01jpQjh-jzMn1+p-dgFCBHOHPN1nkegYGAGAqXoNxkTuGQdGXPgf2PF9PxwegGBTT9K2-X9s1zQdgIkPg0GGMBQN4SCcFvJAl1LBDfw-TDl1XZDK3vT9NwVdRkIw08WIvbsr0bV0Pm+X4YBuNjXyfPisOYzDT2E90xJuHj5ITND6FUtTWSUGRTDgIEGiUcUADoRmDQhOIATVQKBjLgABaF03iUv4zIs6zbOMshJPkpj3xkqVfPPDjt3PLSpTPdcu0FZxr29YL12ktS0zABj5Jwb0ItfZc0sC7xEsrUKuPCvdaKQQ9eA-ZcoxQGM1wsWJ4iQAAPSBYFwEkURoKQqXIDggA).

I've found a library [tsx-control-statements](https://github.com/KonstantinSimeonov/tsx-control-statements) with such kind of components, but I'm not sure if it handles the type checking correctly in the branches + it has a lot of [limitations](https://github.com/KonstantinSimeonov/tsx-control-statements#known-limitations).

P.S.: I've noticed, that @kettanaito also [has a post on Twitter about it](https://twitter.com/kettanaito/status/1434135022928375813).

**Comment by kettanaito** [comment]
Hey, @vasilii-kovalev. Thanks for raising this.

While I think such component, and underlying TypeScript support, may be practical, there are also good reasons [not to do so](https://twitter.com/dan_abramov/status/1034037659193290758). In short, it disrupts the render flow of a component. I think the safest way to achieve such conditional rendering (without resorting to ternary) would be to ensure the children are lazily evaluated.

```jsx
<Condition if={user}>
  {() => <UserProfile id={user.id} />}
</Condition>
```

This way `user.id` won't throw an exception if the `user` is undefined. With the function-as-children I believe you can annotate that `user` always exists in that function. But regardless, such abstraction is not worth the cost.

**Comment by vasilii-kovalev** [comment]
@kettanaito, from my experience, if there are a lot of optional fields, you'll either end up with a wall of ternaries/logical `&&` operators, which makes the code harder to read, or a lot of little components with the `undefined`/`null` checks in them, which pollute are in a module/folder. Sometimes these little components are necessary, because they can hide a complex logic, but creating a component just to put there the `undefined`/`null` check looks like an overhead IMO.

So I've created this proposal in hope to achieve a better readability without making these little components in the end.

Am I right, that the "function-as-children" approach can't be done with the current state of TypeScript anyway? I'm not sure that I understand, how I can pass the knowledge to the children about `user` not being `undefined`/`null`.

**Comment by andrewbranch** [comment]
The problem with this proposal isn’t type checking; the problem is how JSX works.

```ts
return (
    <ConditionalRenderer condition={!isUndefined(user)}>
      <header>
        {user.username}
```

`user.username` is _always_ evaluated, regardless of whether or not `ConditionlRenderer` would choose to _render_ it. There is no possible implementation of `ConditionalRenderer` in which this code does not crash. It crashes before a `ConditionalRenderer` element has even been created by whatever JSX factory is wired up. @kettanaito is right; you need native control flow constructs or closures in order to prevent evaluation.
