### ISSUE TITLE
`to` statement in `import`

### ISSUE THREAD

**Issue by pjalsGit** [microsoft/TypeScript#45724]
# Suggestion

## 🔍 Search Terms

import to
import object

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

allow for importing with the to statement, example:
```ts
let imports:string = {}

import * as example to providers from 'example';

imports['example'].doSomething()
```

## 📃 Motivating Example

If you want to make a program that has something like `imports['example']`, then it would probably error. This feature fixes that.

## 💻 Use Cases

I'm making an application which saves imports to an object. This would be essential for it to work.

**Comment by Retsam** [comment]
This isn't a viable suggestion - the point of the viability checklist is that suggestions should meet all the criteria in the list, and it definitely fails this one, as you've indicated:

>  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

TS really isn't interested in inventing new semantics for ECMAScript syntax like `import/export`.  For this to be implemented in TS, it'd need to be a TC-39 proposal at stage 3.

**Comment by pjalsGit** [comment]
ahh, ok.
