### ISSUE TITLE
Newly created files don't belong to typescript project on MacOS

### ISSUE THREAD

**Issue by yifanwww** [microsoft/TypeScript#45721]
# Bug Report

### 🔎 Search Terms

Maybe `ts`, `vscode`, `file is not part of ts project`, `newly created`?

### 🕗 Version & Regression Information

Tested on the following typescript versions:
- 4.5.0-dev.20210904
- 4.4.2
- 4.4.1-rc
- 4.3.5

vscode version: 1.60.0

### ⏯ Playground Link

https://github.com/yifanwww/ts-bug-repo

This is a very simple project...

### 🙁 Actual behavior

Open that project via vscode(whatever open folder directly or open the workspace file).
Open the file `src/index.ts` to get tsserver started, then create a new file `src/test.ts`.

There should be an error `cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.ts(1208)`, but actually it got no error.

Execute vscode command `Typescript: Go to Project Configuration`, a panel appears with info `File is not part of a Typescript project. Click here to learn more.`

In that new ts file, no auto-completion and no auto-import to use the function `fn` which is declared in `src/index.ts`.

I have to restart tsserver or reload vscode.

I have checked these issues but still don't know how to solve this problem.
- https://github.com/microsoft/TypeScript/issues/43290
- https://github.com/microsoft/TypeScript/issues/36532
- https://github.com/microsoft/TypeScript/issues/35794
- https://github.com/microsoft/TypeScript/issues/33564

**This bug never happens on my win laptop, but does always happen on my mac laptop.**

### 🙂 Expected behavior

The file gets added into the existing typescript project.

BTW, If you need `tsserver.log`, please tell me how to get it.

**Comment by orblazer** [comment]
Hello,
I have exactly same issue but on Linux, but i have found the problem and an temporary solution.

The problem come from `include` property in `tsconfig.json` when that property is set to folder or too ambigu in that case `src`(but this is same if is set to `src/**/*`).
My solution its stupid but simply specify file type `src/**/*.ts`.

Thanks.

**Comment by yifanwww** [comment]
@orblazer Thanks a lot, seems this temporary solution works for me.

**Comment by andrewbranch** [comment]
Hmm, I can’t reproduce this. I’m on macOS 12.1 Beta, VS Code 1.63.0-insider, and TypeScript 4.4.2 (also tried latest nightly). How are you creating/opening the new file `test.ts` in your repro instructions? If this is still happening for you, can you post a TS Server log ([instructions](https://github.com/microsoft/TypeScript/wiki/Getting-logs-from-TS-Server-in-VS-Code))? Thanks!

**Comment by yifanwww** [comment]
@andrewbranch 
I usually click this button to create a new file, name it and then save it.
![image](https://user-images.githubusercontent.com/55199350/146725603-5fedfed3-ec62-4ed1-8b26-cafaf5bd8ef9.png)

I'm now on macOS 11.6.1, VSCode 1.63.2, and TypeScript 4.5.4, that problem still occurs to me.

I will try to get a tsserver log.

**Comment by yifanwww** [comment]
@andrewbranch 
BTW, I read the tsconfig reference again (https://www.typescriptlang.org/tsconfig#include).
I want to know is it allowed to set the `include` option without any glob patterns, like `"include": ["src"]`?

It seems that `"include": ["src"]` and `"include": ["src/**/*"]` behave the same on my win but not on my mac.

**Comment by lgarron** [comment]
I'm also seeing the same issue for the last few... weeks?

> My solution its stupid but simply specify file type `src/**/*.ts`.

Thanks!
If anyone is trying this workaround, I recommend restarting VSCode rather than just restarting the TypeScript server. That helped it stick for me.

**Comment by andrewbranch** [comment]
> It seems that `"include": ["src"]` and `"include": ["src/**/*"]` behave the same on my win but not on my mac.

I thought these were the same. And I still can’t reproduce the issue. @lgarron are you still able to reproduce this if you revert changing the glob format?

Another issue about glob weirdness, though perhaps ultimately unrelated: #46788

**Comment by yifanwww** [comment]
@andrewbranch
Hello, here are my tsserver logs https://gist.github.com/yifanwww/f06c9ee62260140f0cca0433bab457c7

There are two files `tsserver-1.log` and `tsserver-2.log`, the first one was generated when `includes` was set as `src`, and the other one was generated when `includes` was set as `src/**/*`. Seems there are huge differences.

**Comment by yifanwww** [comment]
![image](https://user-images.githubusercontent.com/55199350/148872448-2e75e397-2edc-48fc-8421-a8db36d44318.png)
The first difference comes from line 42+, tsserver-2 will watch `/ts-bug-repo/src` while tsserver-1 won't do that.

![image](https://user-images.githubusercontent.com/55199350/148872949-f6b95818-c9e3-48a2-a141-d4e8f1a2c4f4.png)
So when I created `test.ts` and opened it, tsserver-2 knew it but tsserver-1 only knew that I opened a new file.

Then... I don't know what does the other difference mean.

**Comment by lgarron** [comment]
> I thought these were the same. And I still can’t reproduce the issue. @lgarron are you still able to reproduce this if you revert changing the glob format?

Indeed:

- Create a new file ⇒ recognized.
- Remove the globs and restart VSCode.
- Create a new file (adjacent to the last time) ⇒ NOT recognized. 🧐

**Comment by lgarron** [comment]
For what it's worth, I'm also able to repro in Codespaces using https://github.com/cubing/cubing.js/tree/exclude-glob-for-ts45721

`src/sites/experiments.cubing.net/cubing.js/stub/index.ts` supports autocompletion:

<img width="654" alt="Screen Shot 2022-01-10 at 20 08 35" src="https://user-images.githubusercontent.com/248078/148879639-78ee60a2-9a9f-4903-b722-e572ce4dea6c.png">

If I create a file at `src/sites/experiments.cubing.net/cubing.js/stub/index2.ts`, it does not:

<img width="491" alt="Screen Shot 2022-01-10 at 20 09 02" src="https://user-images.githubusercontent.com/248078/148879677-ca2476c3-cb41-4cbf-907c-28bc0139c314.png">

If I go back to a commit with the globs and restart the TS server, then it works again. So it's quite reproducible for our repo.

**Comment by andrewbranch** [comment]
I can reproduce in Codespaces and have traced the likely root cause down to the huge differences between file watching on Linux vs. other OSes. This does not explain your observations of it being broken on macOS, which I still can’t reproduce 🤔

**Comment by andrewbranch** [comment]
Actually, to clarify, in Codespaces I’m seeing the bad behavior _all_ the time. I haven’t yet seen why this would depend on the glob format.

**Comment by andrewbranch** [comment]
Discovered with much help from @lgarron that there is an issue when the absolute path to an include pattern contains a `.` character. @yifanwww, does your repo or any ancestor directory have a `.`?

**Comment by yifanwww** [comment]
@andrewbranch No `.` character in the repo but yup the home directory in my mac has a `.` character, that is my name `fan.yi`.

**Comment by andrewbranch** [comment]
Welp, that’s why your repro was not a repro for me 😅 Fixed at #47418

**Comment by divmgl** [comment]
This problem seems to have returned in the latest version of TypeScript and VSCode.

**Comment by zburgermeiszter** [comment]
> This problem seems to have returned in the latest version of TypeScript and VSCode.

It is indeed.
The only fix is to restart TS Server manually, which is not ideal.


```
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 21.6.0
```

**Comment by RyanCavanaugh** [comment]
There are many reasons this can happen and it depends a lot on your configuration. Please log new issues(s) with *concrete* repro steps.
