### ISSUE TITLE
Suggestion infer type from constant array

### ISSUE THREAD

**Issue by lygstate** [microsoft/TypeScript#45736]
# Suggestion
```
const ArchList = ['x86', 'x64', 'arm64', 'arm']
type ArchType = 'x86' | 'x64' | 'arm64' | 'arm'

// provide a way such as ArchType  = valueof ArchList 
// as an alternative to keyof

and
for (let arch of ArchList ) {
  // arch would automatically have the type ArchType 
}
```

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
You forgot to fill out most of the issue template.

If I understand you correctly (which is hard from the incomplete template) you just want this:

    const ArchList = ['x86', 'x64', 'arm64', 'arm'] as const
    type ArchList = (typeof ArchList)[number]

**Comment by lygstate** [comment]
Thanks

**Comment by lygstate** [comment]
@MartinJohns How to infer 0 | 1 | 2 | 3 from `const ArchList = ['x86', 'x64', 'arm64', 'arm'] as const` ?
