### ISSUE TITLE
tsconfig outDir support multiple Dir

### ISSUE THREAD

**Issue by joriewong** [microsoft/TypeScript#45740]
# Suggestion

tsconfig.json
```json
{
	"compilerOptions": {
		"outDir": ["./lib", "./es"],
	}
}
```

## 🔍 Search Terms

tsconfig outDir support multiple Dir

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

tsconfig outDir support multiple Dir

## 📃 Motivating Example

generates corresponding `.d.ts` file for `esmodule` and `commonjs` when building

## 💻 Use Cases

generates corresponding `.d.ts` file for `esmodule` and `commonjs` when building

**Comment by andrewbranch** [comment]
You would need different `module` options for each directory anyway, so there’s no way this could work. You just want two different `tsconfig` files at that point. Note also that tools like Rollup exist to do this for you.
