### ISSUE TITLE
[VS2015] JSX in extends clauses is auto-formatted oddly

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4576]
![jsxextendsspacing](https://cloud.githubusercontent.com/assets/2932786/9593341/00224c30-5002-11e5-8029-75e170f09aac.gif)

Generally speaking, the opening and closing tags should line up vertically, but the autoformatter seems to disagree in this case.

**Comment by vladima** [comment]
looks like a dupe of #4568
