### ISSUE TITLE
Add RequiredProperties utility type

### ISSUE THREAD

**Issue by Thisen** [microsoft/TypeScript#45768]
# Suggestion

## 🔍 Search Terms

- RequiredProperty
- `T & Required<Pick<T, K>>`
- RequiredProperties

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I suggest to add a new utlity type, that makes selected properties required:

```ts
type RequiredProperties<T, K extends keyof T> = T & Required<Pick<T, K>>
```

## 📃 Motivating Example

This could help in such a sneario:
```ts
interface Person {
  id: string;
  name?: string;
  alias?: string;
}
// A single property
type PersonWithRequiredName = RequiredProperties<Person, "name">
const john: PersonWithRequiredName = { id: "123123", name: "john" }
// Will error, name is missing
const alice: PersonWithRequiredName = { id: "234234" }

// Multiple properties
type PersonWithRequiredNameAndAlias = RequiredProperties<Person, "name" | "alias">
const fullJohn: PersonWithRequiredNameAndAlias = { id: "123123", name: "john", alias: "j" }
// Will error, alias is missing
const fullAlice: PersonWithRequiredNameAndAlias = { id: "234234", name: "alice" }
```

## 💻 Use Cases

An ideal use case would be as part of type predicates to use with `Array.prototype.filter`:

```ts
interface Person {
  id: string;
  name?: string;
  alias?: string;
}
type PersonWithRequiredName = RequiredProperties<Person, "name">

function hasName(person: Person): person is PersonWithRequiredName {
 return (person as PersonWithRequiredName).name !== undefined;
}
const persons: Person[] = [ ... ]
persons.filter(hasName).sort()

```

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388:

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.
