### ISSUE TITLE
Incompatable types in assigment.

### ISSUE THREAD

**Issue by rmbar** [microsoft/TypeScript#45777]
# Bug Report

### 🔎 Search Terms

Parameterized Types

### 🕗 Version & Regression Information

3.7.2

### ⏯ Playground Link

[Playground link with relevant code]https://www.typescriptlang.org/play?#code/MYGwhgzhAEBKCmBzAruATgZQC5oJYDtEAeAFWngA8t58ATGCHAxAPgCgBvN6H6YAe3yM0yYFn5oAFAAc8ANzDVoaeGFqCQAT2gKQyeAC5ow5gBplSSgAVF1NPgDCg4WAJYjJAJTdeXXv+hcADNJAEJ8eAB3OCQAUQppSRVEa1t4eychHFd8LE8AOmpGSV19T28AyugsAAs0fmiI6Ni0eqkAIgBxXDkaHTA9eGh1eBh8fiw+QSCJAFtq-gsUimh26ABqJdSsO0dnbLcN1fzoGeQ6IzXN0vgK3gBfNh8ecWw8Qkk7nj8qlSxkezVGq4CD5G7PaCPR5sARZYw4AAyNEQtRIdXghhiKHQb2YRHaAD18sSACTtFjQAC80CaWNQYEwTEI+KJpPJknaAEEAEIOdrmQnE-JkzzQGH7eFoJGEWoAeQiRh4CGxDNxzMFZIp1OE0pRNTRKiGAHojeQEvAxPBaDSJgsprNpLgQPBzAAjZCTEYQJ6wiD8Z35ED8RCSHXIuURQr8NUhgrOmU1UUm6CyNwwADMbCAA)

### 💻 Code

```ts
class RegularString<T extends string>
{
    constructor(private readonly value: string, regexPatternConstraint: T)
    {
        if(!new RegExp(regexPatternConstraint).test(value))
            throw new Error("Given value does not conform to regex " + regexPatternConstraint + ". found: " + value)
    }

    toString()
    {
        return this.value
    }
}

const strLengthThree: RegularString<"^...$"> = new RegularString<"^...$">("ABC", "^...$") 
const strLengthOne:   RegularString<"^.$"> = strLengthThree // expected not to compile, but does

console.log(strLengthOne.toString().length) // prints 3


```

### 🙁 Actual behavior

Compiled

### 🙂 Expected behavior

Should not compile

**Comment by MartinJohns** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--

**Comment by rmbar** [comment]
I think the confusion originated because this is not a valid program:

```
const a : "^...$" = "^...$"
const b : "^.$" = a
```

**Comment by rmbar** [comment]
I am able to induce the expected compilation error with this modified version:

```
class RegularString<T extends string>
{
    constructor(private readonly value: string, private readonly regexPatternConstraint: T)
    {
        if(!new RegExp(regexPatternConstraint).test(value))
            throw new Error("Given value does not conform to regex " + regexPatternConstraint + ". found: " + value)
    }

    toString()
    {
        return this.value
    }
}

const strLengthThree: RegularString<"^...$"> = new RegularString<"^...$">("ABC", "^...$") 
const strLengthOne:   RegularString<"^.$"> = strLengthThree // expected not to compile, and does not compile
```
