### ISSUE TITLE
Boolean typeguards do not narrow type on else branch

### ISSUE THREAD

**Issue by dyc3** [microsoft/TypeScript#45775]
# Bug Report

### 🔎 Search Terms

- type narrow boolean

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type guards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210907#code/JYOwLgpgTgZghgYwgAgDLAOYFs7IN4BQyyAJsAM4RyUBcyYUArhADRHIID2j4dIjWAEbQ2AXwIFQkWIhQAhTvHzsylahDrwANpTbEYWuADdOUOuQagMYiWACeABxQApTgGsUAXjSYcyAD7ICvAA3BJaEGDIAFbuGsiuHsjehMSqVLT0TKzsXDxgdABMYmGSMMgAFLEeAHTp6gCUysRcIOScETVanBgVAAZavrgAJHjVEDV54KJ9DWHiEDooqRycbR0T3b19goq4YNSQ5MiDSaPjNQbGpjNzBOJAA)

### 💻 Code

```ts
interface Ligma {
  disease: true,
  count: number,
}

interface Bofa {
  disease: false,
  flavor: string,
}

type Joke = Ligma | Bofa;

let joke: Joke = {
  disease: true,
  count: 2,
};

if (joke.disease) {
  console.log(`ligma ${joke.count}`);
}
else {
  console.log(`bofa tastes like ${joke.flavor}`);
}
```

### 🙁 Actual behavior

In the else branch `joke` is type `never`. It could be argued that this is expected behavior because `disease` could be undefined, but I think that only makes sense if the declaration is `disease?: bool`

### 🙂 Expected behavior

In the else branch `joke` should be type `Bofa`.

**Comment by fatcerberus** [comment]
It narrows to `never` because it already knows it *can't* be `Bofa` due to narrow-on-assignment.  If you suppress the narrowing you'll see it does what you expect:

```ts
let joke: Joke = {
  disease: true,
  count: 2,
} as Joke;
```

**Comment by dyc3** [comment]
Oh, that's not exactly intuitive but good to know. I'll go ahead and close this then.

**Comment by fatcerberus** [comment]
It's so you can do this:

```ts
let x: string | number = 42;
takesANumber(x);
x = "foobar";
takesAString(x);
```

...without having to add a pointless type guard.
