### ISSUE TITLE
Editing Pulumi scripts (Typescript): CPU maxes out

### ISSUE THREAD

**Issue by vincesp** [microsoft/TypeScript#45788]
Issue Type: <b>Bug</b>

Editing an NPM project that contains Pulumi scripts in Typescript.

High CPU load on process "Code Helper (Renderer)"	

Error message in VS Code:
"The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 9, 11|
|Memory (System)|16.00GB (1.76GB free)|
|Process Argv|--crash-reporter-id 87c9fe1a-c202-411b-8b12-fe0c69314b53|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.6.3
Bookmarks|ale|13.1.0
ng-template|Ang|12.2.0
swagger-viewer|Arj|3.1.2
asciidoctor-vscode|asc|2.8.9
npm-intellisense|chr|1.4.0
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.22
prettier-vscode|esb|8.1.0
github-actions|for|0.0.1
go|gol|0.27.2
gitignore-templates|has|1.0.1
vscode-drawio|hed|1.6.2
reg|ion|1.0.3
vscode-edit-csv|jan|0.6.0
vue|jcb|0.1.5
vscode-gutter-preview|kis|0.27.1
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.191.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.5.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestaticwebapps|ms-|0.8.0
vscode-azurestorage|ms-|0.12.1
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.16.1
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.1236758218
remote-containers|ms-|0.191.1
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
color-highlight|nau|2.4.0
vetur|oct|0.34.1
vscode-sassdoc|raf|1.0.2
java|red|0.81.0
vscode-commons|red|0.0.6
vscode-xml|red|0.18.0
vscode-yaml|red|0.22.0
LiveServer|rit|5.6.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.2.1
rewrap|stk|1.14.0
copy-with-imports|str|0.2.0
vscode-stylelint|sty|0.86.0
c4-dsl-extension|sys|2.2.5
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0
gitblame|wad|8.1.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also can you please share a minimal example project that demonstrates this issue?
