### ISSUE TITLE
[VS2015]Formatting multiline class expressions indents incorrectly

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4580]
![extendsexpressionformatting](https://cloud.githubusercontent.com/assets/2932786/9593834/a1a5f470-5008-11e5-9a1b-1cc12e21f8f2.gif)

Running the autoformatter over a multiline class expression causes the indentation to shift in incorrectly.

**Comment by mhegazy** [comment]
//CC: @SaschaNaz
