### ISSUE TITLE
Missing NumberFormatUnit symbol in lib.es2020.intl.d.ts

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#45804]
# Bug Report

### 🔎 Search Terms

- lib
- d.ts

### 🕗 Version & Regression Information

4.5.0-dev.20210909

### 💻 Code

1. Update the VS Code code base to build with the latest TS nightly
2. Run `yarn monaco-compile-check`

### Problem
https://github.com/microsoft/vscode/runs/3558995204?check_suite_focus=true

We see the errors:

```
Error: node_modules/typescript/lib/lib.es2020.intl.d.ts(222,9): error TS2717: Subsequent property declarations must have the same type.  Property 'type' must be of type 'ES2018NumberFormatPartType', but here has type 'ES2020NumberFormatPartType'.
9
Error: node_modules/typescript/lib/lib.es2020.intl.d.ts(229,16): error TS2304: Cannot find name 'NumberFormatUnit'.
10
Error: node_modules/typescript/lib/lib.es2020.intl.d.ts(237,16): error TS2304: Cannot find name 'NumberFormatUnit'.
```

I searched through the libs but also couldn't find where `NumberFormatUnit` is defined. Let me know if I've overlooked something silly

/cc @orta

**Comment by orta** [comment]
Thanks! Will look at this tomorrow

**Comment by AlimovTILLO** [comment]
i have some problem

**Comment by renbou** [comment]
CI fails on DefinitelyTyped with exactly the same error (the result is being unable to push any changes to the repo):
- [Github CI](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55641/checks?check_run_id=3563138106)
- [Azure](https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=109617&view=logs&j=8635df7d-ecde-52a7-c7a8-84b998e35690&t=c264d665-0b79-59b7-7e04-9965cbe74860&l=100)
