### ISSUE TITLE
TypeScript statement completion with symbols does not always work 

### ISSUE THREAD

**Issue by leidegre** [microsoft/TypeScript#45800]
Issue Type: <b>Bug</b>

This is wonky.  I put together a small repo here https://gist.github.com/leidegre/e51afd311eb4d9729c3ea2a5e6411d3b

For example, here VS code is not giving me statement completion. I'm expecting to see `FOO` in the suggestion box.

![image](https://user-images.githubusercontent.com/63085/132568231-823a85a9-ca1e-4a48-8187-a0ef31b53be9.png)

but, if I move the symbol and type definition into a seperate file it does work

![image](https://user-images.githubusercontent.com/63085/132568362-279500ef-6c4c-4000-8e23-222ca1fff0d4.png)
![image](https://user-images.githubusercontent.com/63085/132568366-05fdf2b5-a679-4621-8272-47fec5ed716b.png)

but this isn't consistent. I have in a larger codebase examples of where it still doesn't work reliably. I don't know why it works sometimes and sometimes not. it's functionally equivalent code.

also, apologies if this is better served by the TypeScript team but I thought I'd ask here first. I have observed this behavior for the past two years on both old and brand new systems. So it's been like this for a while but I'd like to fix that.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (23.27GB free)|
|Process Argv|. --crash-reporter-id 888dbca9-2022-45aa-889b-64b30d1eaa60|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.11.0
mermaid-markdown-syntax-highlighting|bpr|1.2.2
prettier-vscode|esb|8.1.0
go|gol|0.27.2
reason-vscode|jar|1.7.13
jlang-clang|l3d|0.0.10
jlang-tundra2|l3d|0.0.1
vscode-azurefunctions|ms-|1.5.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.12.1
csharp|ms-|1.23.15
python|ms-|2021.9.1191016588
vscode-pylance|ms-|2021.9.0
jupyter|ms-|2021.8.2031190714
jupyter-keymap|ms-|1.0.0
azure-account|ms-|0.9.8
cpptools|ms-|1.6.0
hexeditor|ms-|1.8.2
vsliveshare|ms-|1.0.4761
java|red|0.81.0
code-spell-checker|str|2.0.4
code-spell-checker-swedish|str|0.1.9
vscode-lua|tri|0.12.4
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.35.0
vscode-java-dependency|vsc|0.18.7
vscode-java-pack|vsc|0.18.4
vscode-java-test|vsc|0.31.3
vscode-maven|vsc|0.33.0

(1 theme extensions excluded)

</details>

**Comment by andrewbranch** [comment]
I get the same result as @IllusionMH, can reproduce on the playground but not anywhere else: https://www.typescriptlang.org/play?ts=4.5.0-dev.20210909#code/MYewdgzgLgBAYgeQTAvDAygTwLYCMQA2AdAGYgBOAFAEQBcZI1AlAFAtSYAOApvCCKhgBvANqIEAXQD8taOQCWYAOYBfNgBNuwAgENyvAG56YDWnH4BuNgHprMMAOg6o3bNzCxQ2TgW5R54DAAFtz6MLSUMCwMRCxAA

Likely a Monaco bug.

**Comment by leidegre** [comment]
I did open an issue on the IntelliCode repo as well.

https://github.com/MicrosoftDocs/intellicode/issues/311
