### ISSUE TITLE
Type narrowing based on function typeof is broken when function is intersected with a record

### ISSUE THREAD

**Issue by safareli** [microsoft/TypeScript#45801]
# Bug Report

### 🔎 Search Terms

type narrowing based on function typeof is broken when intersection with a record is used

### 🕗 Version & Regression Information

- Recent change in behaviour happened in version 4.3.5

### ⏯ Playground Link
 
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAshwEMoF4oG8oDMD22BcUAzsAE4CWAdgOZQC+AUJcBCZggMbQBi6UAFAEoCxctQb122CsSgAPFPwQE+PAGSx4CAVAA+RUpSrbkAPnT0olqGUz9QkbLaTIXUAESYArhXbAyUtwE0CytQgHowqGBCADoANxZCfwooE1QAFhiAZhiAVgIKCASSKABaUqhvCFlIXwgAExDQywio2OKkqSgAHgyYgCZsgjUNRDKK6trmRuarBABuJrooCAAbQmhg2ZbIyYg6+uEDaiXwyOj4xOTUvpz8-VEacpWa-enTq1aLjuveqEzBlkjo9dPwRnBENpnlVXgcPpYFksGLQgA)

### 💻 Code

```ts
type Meta = { foo: string }
interface F { (): string}
const x = (a: (F & Meta) | string) => {
    if (typeof a === "function"){
        // ts.version >= 4.3.5: never -- unexpected
        // ts.version <= 4.2.3: F & Meta -- expected
        a;
    } else {
        // expected: string
        // ts.version >= 4.3.5: string -- expected
        // ts.version <= 4.2.3: string | (F & Meta) -- unexpected
        a;
    }
}
```
### 🙁 Actual behavior

behavior was half correct from in TS versions  <= 4.2.3, but then it was changed in 4.3.5 which fixed the part that was wrong previously, but broke the other part that was correct. So we still have half broken behavior.

### 🙂 Expected behavior

It's expected to pick the correct parts from the both versions.

**Comment by a-tarasyuk** [comment]
It's a little bit tricky case. The previous versions used `|` for `Union` and `Intersection` types
```ts
function getTypeFactsOfTypes(types: Type[]): TypeFacts {
    let result: TypeFacts = TypeFacts.None;
    for (const t of types) {
        result |= getTypeFacts(t);
    }
    return result;
}
```

Currently, TS separates `Union` and `Intersection`. To get a type in `if block`, all types should follow the same flags  

```ts
interface A { (): number; }
interface B { (): string; }
interface C { (): void; }

const x = (a: (A & B & C) | string) => {
    if (typeof a === "function"){
        a; // A & B ((FunctionFacts & FunctionFacts) & TypeofEQFunction
)
    }
    else {
        a; // string 
    }
}

```

Or to be empty 

```ts
interface A { (): number; }
type B = {};

const x = (a: (A & B) | string) => {
    if (typeof a === "function"){
        a; // A
)
    }
    else {
        a; // string 
    }
}
```

```ts
if (flags & TypeFlags.Intersection) {
    // When an intersection contains a primitive type we ignore object type constituents as they are
    // presumably type tags. For example, in string & { __kind__: "name" } we ignore the object type.
    ignoreObjects ||= maybeTypeOfKind(type, TypeFlags.Primitive);
    return reduceLeft((type as UnionType).types, (facts, t) => facts & getTypeFacts(t, ignoreObjects), TypeFacts.All);
}
```

I'm not sure which fix is appropriate for such cases. Should the TS allow a intersection with the non-empty object and functions?

/cc @andrewbranch
