### ISSUE TITLE
Type narrowing of interfaces inside of type guards does not conform to type narrowing of discriminative unions

### ISSUE THREAD

**Issue by IgnusG** [microsoft/TypeScript#45815]
# Bug Report

### 🔎 Search Terms

type narrowing, type guards, discriminative unions

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type guards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgApyhcAeAagPmQG8AoZc5RMAVzgBsAuYsi1sATwAcImBGZAD7IATAG4WrcgDd61HslwTkAXxKqSoSLEQoAwgAtgdACYB5EBDyEIAD0ghjAZzQYsYK81ZVajT5PIc3Hzi-tKy8rghFKrqmtDwSMgGRsYAKgDuAPYetvZOLpg4BH7k3vRMpKHIgfJiSqwydHJMkUoxJCQw1CAIYMCZIMjAjskm5pYAkvgAFFJM6IXuUwCUTFJDzqNmFthTJciYNFCDYFBy4uoIA45gyAiGJsgAvMgg1HR0lM7dANYgmelBnBnNMFm5sAAicYQwhCLbjSGpfSYCAw5YdYAwZDTYbwizTe4pZbLfYAelJd1eGCgAIgxmqmSSD22lghSJRMKU5OQACFqLdgLdHPpMu9jAByKQoABGECwTJSkOhgmQbORcs5rCuIBud2Z4yYeNZ0MIL0JJii5G1uvNaXV8iNiPtMOeepSFw6NSG4GgjggvX6IAA4lhoHBIMYeewAIKOP1QPoDV2g1w4KEWF0AMgVYx26dRKrVHNhOZZTuLyGzjvzEML7I1+HRJC9cSgfoDAwAYsA22AFrcXtX66jCFX9XnlUIiw3xNbbjYmK324mQN3e-3XW8Pl9kL9-oCd0PnfhRMhuQB1TJQH6OT1cFBL-0rgDK-oGxg3LzBaZNldLCJrOtj1na5bnYRcfTbJ9A1fbUPwwAdXneT5gV3EA-gBIFNnHY0MxPM8KUva9b2be9vS0ZdA1dR8O1XHsbg3IQaJfN8HH7ECdVuAAvXgIIo6CkxeLcUO+dD9yw-8Jzw08LyvG9kAAWmQaV+W9aoyOBeMVyGW5jEyCBHBAcUwBIOdkC44Q+N9ATBiE5Cdz3TDDxw8sZwI5AiJvEggA)

### 💻 Code

```typescript
interface Parent<V> {
    actual: {
        type: 1 | 2;
        value: V
    }
}

interface ChildOne<V> extends Parent<V> {
    actual: {
        type: 1;
        value: V;
    }
}

interface ChildTwo<V> extends Parent<V> {
    actual: {
        type: 2;
        value: V;
    }
}

function isChildOne<I>(v: Parent<I>): v is ChildOne<I> {
    return true;
}

// Child can either be actual.type=1|2 with value "One" or actual.type=1 with value "Three"
const child = null as unknown as (Parent<"One"> | ChildOne<"Three">)

// The type should be narrowed as actual.type=1 with value "One" or actual.type=1 with value "Three"
if (isChildOne(child)) {
    // child narrowed to ChildOne<"Three">
    // But it should've been Child<"One" | "Three">
    const childOne: ChildOne<"One"> = child; // Compiler complains becase child is ChildOne<"Three"> now?
    const childThree: ChildOne<"Three"> = child;
}
```

### 🙁 Actual behavior

Child narrowed to ChildOne<"Three"> even though the type guard shows it's going to narrow to ChildOne<"One" | "Three">.

### 🙂 Expected behavior

But it should've been Child<"One" | "Three">. Given the intersection of type guards I've added an example below that shows the intersected types with the narrowed type guard result but in that case the result is correct. In the conditional the narrowing is not.

I might be misunderstanding how they work though. In that case let me know. Always nice to learn something new about typescript.

**Comment by MartinJohns** [comment]
There's no union in your example. You have inheritance. It's a finite vs infinite set.

**Comment by MartinJohns** [comment]
I'm not quite following the exact behaviour, but one thing to mention is that you're **not** dealing with discriminated unions. Your `child` gets simplified to `Parent<"One" | "Three">`, because `ChildOne<"Three">` is also a `Parent<"Three">`. That means your type guard does not receive a union type and can't narrow it.

But I am puzzled why after calling `isChildOne<"One" | Three">(..): v is ChildOne<"One" | "Three">` the type suddenly becomes `ChildOne<"Three">`. It's probably because in `child` the type is `Parent<"One">`, not `ChildOne<"One">`, so `"One"` gets excluded from the result.

**Comment by IgnusG** [comment]
> I'm not quite following the exact behaviour, but one thing to mention is that you're **not** dealing with discriminated unions. Your `child` gets simplified to `Parent<"One" | "Three">`, because `ChildOne<"Three">` is also a `Parent<"Three">`. That means your type guard does not receive a union type and can't narrow it.
> 
> You're probably assuming `Parent<V>` can only be either `ChildOne<V>` or `ChildTwo<V>`, but that's not the case. There could be infinite more interfaces matching `Parent<V>`, that means you're not dealing with a finite narrow-able union type.
> 
> But I am puzzled why after calling `isChildOne<"One" | Three">(..): v is ChildOne<"One" | "Three">` the type suddenly becomes `ChildOne<"Three">`. It's probably because in `child` the type is `Parent<"One">`, not `ChildOne<"One">`, so `"One"` gets excluded from the result.

Oh I see. I was originally dealing with discriminated unions (`({ type: 1 } & { value: T }) | ({ type: 2 } & { error: T })`) but I wanted to extract them into interfaces since the type aliases were being inlined in VS Code and it was difficult to read (`ChildOne<"Two">` is much more readable than `{ type: 1 } & { value: "Two" }`). Maybe that's when the type guards broke.

I'm still not sure why the type inside the conditional changes though. If I understood how the guards intersect the original type than the example in the playground below the conditional works, but the type guard should then be doing the same (and it isn't).

**Comment by IgnusG** [comment]
Btw. I've created more streamlined playground examples with unions and interfaces. It works with discriminated unions.

[Playground link for discriminated unions](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQg9sAFgHgGoD4oF4oG8rABcUARAPIB2EJANFAG4CGANgK4TGpQC+UAPngLESAFQDucWgxbtOPANwAoUJCiUIaTDnxFS6qUzYcoXbksUAzVhQDGwAJZwKUewGcA4hCoAnezeQAkugAFPTE8EiBmALqUQCUhPQurmpUUXiKUFlQ3hDArN7OwN7sStyKijZOrsBQTtDaQqTiknSGsqSoMtARiCQ8UIwpwb3IJF1GsAh90aka491zJOhx5irQIuAQ7qyM3gAmAEoQrqzMtTgj02MT7FNIy-xzN4v6K1AAZM8Lk-pPP3desslFUKDUoDZEBAbABrdTETaQHZ7I4nM4XPC8IbfW7QN7yKAAekJUAA6nBvDDXJVqrVIdCYb0EVtkQdjqdzthMYMUrEAT1psCiSTyZTqYp7BYoME3J4fH5gvU4nFBMT7ogoBJKVBACjkmWyoPB9Nh6lZ+2IfNxSy0dSoPJxryowP1WUNdKhsN6ZotaX56seOHq9stiyB6DKiiAA)

Playground link for interfaces](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEIHswAsA8A1APmQG8AoZC5MALmQCIB5ECO5AH3oBUB3dOgbnKUAbnAA2AVwi08ggL6lSoSLEQomEfEQgAPSCAAmAZzSZchEkIo16GgVeSjJ05HlIKl4aPCTIe6LWRdfWNTbECySipaOn97KKcpGXlFGAkQBDBgdBBkYCMAcQhmKGAEHABJAgAKYVoMcKr2ZA1KggBKamE8k1amyMooCDAJKFywKCkU0gQcozBkHJQAXhJorl46ABpHcST6PD2UBqxWOWQ4E2qTnDpD5zDTog5Wu6OW5joOwVIwAE8AA4oTiAiAFCRwKAGABKECMEjEC1W1zMt3uUkeX2ar3R6k+HWQADIPpo3g87M0yRiTl9BLMQPNkAgsBAEABrDS0EFA8GQmFwhFIkjnS4ktHvOwEfjIAD0MuQAHV0FA2UYZnMFszWWyTlzQbyobD4YjkKtiCLesxxQ8aVLZfKlSq1UoYMhqvkiiUytUlu12ms5cgACLoOEgADkC14KoA-A56YyteyNAaDLQcRL8abFswLpbSbiSbT7Yrlar4xqmSz2SdU+mrVTjmYsaslnmxY3MXbAyGw5HkNG2XGFEA)

**Comment by IgnusG** [comment]
Oh and it gets a bit weirder if we force the compiler to disregard the more narrow child interface, suddenly it does properly intersect with the original - that is `(Both<"Value Both"> | One<"Value One">) & One<"Value Both">` does end up narrowing to `One<"Value Both">` inside the type guard.

[Playground link to interfaces - see at the end example with excluding the narrower type](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEIHswAsA8A1APmQG8AoZC5MALmQCIB5ECO5AH3oBUB3dOgbnKUAbnAA2AVwi08ggL6lSoSLEQomEfEQgAPSCAAmAZzSZchEkIo16GgVeSjJ05HlIKl4aPCTIe6LWRdfWNTbECySipaOn97KKcpGXlFGAkQBDBgdBBkYCMAcQhmKGAEHABJAgAKYVoMcKr2ZA1KggBKamE8k1amyMooCDAJKFywKCkU0gQcozBkHJQAXhJorl46ABpHcST6PD2UBqxWOWQ4E2qTnDpD5zDTog5Wu6OW5joOwVIwAE8AA4oTiAiAFCRwKAGABKECMEjEC1W1zMt3uUkeX2ar3R6k+HWQADIPpo3g87M0yRiTl9BLMQPNkAgsBAEABrDS0EFA8GQmFwhFIkjnS4ktHvOwEfjIAD0MuQAHV0FA2UYZnMFszWWyTlzQbyobD4YjkKtiCLesxxQ8aVLZfKlSq1UoYMhqvkiiUytUlu12ms5cgACLoOEgADkC14KoA-A56YyteyNAaDLQcRL8abFswLpbSbiSbT7Yrlar4xqmSz2SdU+mrVTjmYsaslnmxY3MXbAyGw5HkNG2XGPIGAHLobgDlATMpsqgspnoAC2AOAYmgeXA6BzYj+FwBAN3oAA5vOm9hkMfitAyhdDMh4QYDMVd3kFgZQyZsChlNAjKyshyRZXW-TcVB8FBZigIZMl3Ug0gyQDcg9a9SgQABBRFoBAOAsmETQKh2TgajqR42mxK1iM6bp8jFfoHCGEYxioSYIGmYBXXdQpULKTCVBwvCIB9Zg-QDeUAAloB-KMyxMDip2QGBlV8YAFjAbcDHyIZjz5M8qzXAwqFBCsGU1asdTMOsO0LW1szbUUMxtZspXcUggA)

**Comment by sandersn** [comment]
I think the part you're missing is that assertions. In this case, `if (isChildOne(child))` asserts that a `Parent<"one"> | ChildOne<"three">` is narrowed by `ChildOne<"one" | "three">`. This doesn't necessarily produce a `ChildOne<"one" | "three">`, it narrows by it. So, from the original type, `Parent<"one">` is removed because it's incompatible with `ChildOne<"one" | "three">`, while `ChildOne<"three">` is retained. It's a lot like this example expressed in terms of primitives:

```ts
declare const tsn: "typescript" | number
if (typeof tsn === 'string') {
    tsn // tsn: "typescript", not string
}
```

**Comment by IgnusG** [comment]
Ah I think I was thinking the other way, since `ChildOne<"one">` would be compatible with `Parent<"one">` (because it extends it), but not the other way around. 

I'm still unsure why the latter example from my previous [comment](https://github.com/microsoft/TypeScript/issues/45815#issuecomment-917163974) works though since in there we do exactly this "incompatible" narrowing (`Parent<"one">` becomes `ChildOne<"one">`). If someone could explain the second example and why the compiler lets me do that (since it shouldn't?) that would be amazing. 

Just so I can better understand it though (I understand if no one has time, that's ok too), I solved my problem in a different way so I regard the issue as closed from my side as well.

**Comment by sandersn** [comment]
I don't understand why `isGenericAlternative` is legal -- maybe type predicates just don't have much checking (or enough). But whenever you *use* it, it's going to assert that a `Parent<"one"> | ChildOne<"two"> is ChildOne<"one">`, even though that doesn't make sense.

**Comment by sandersn** [comment]
In the compiler, the check is `checkAssignableTo(typePredicate.type, signature.parameters[typePredicate.parameterIndex])`. In other words, `ChildOne<"one">` has to be assignable to `Parent<"one"> | ChildOne<"two">`, which it is because `ChildOne<"one"> ==> Parent<"one">`
