### ISSUE TITLE
Optional template string pattern index shows error

### ISSUE THREAD

**Issue by davidbielik** [microsoft/TypeScript#45821]
# Bug Report

### 🔎 Search Terms

typescript optional template string pattern error

### 🕗 Version & Regression Information

v4.4.2 and with the `4.5.0-dev.20210910`

- This changed between versions 4.4.2+
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about expected errors
- I was unable to test this on prior versions because the feature was introduced on 4.4.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAUMmcgO7AAmYAFgPwBcyIArgLYBG0A3KeToRgAczphmrTjyj8AvsWKhIsRCgxZceAOrB6AEThg4ABSjZ0BCAA9IIagQ058RAWQD075Cegc9yOBAAT2R0c3RoMBC8YygsEBFKPTpkAHJqIzgAWlSAOjdkAG0AaxYAAwzjLIASQhioUBE5MoBdFi5sbAAbCED5RWVoeCQ0TGcdZKdcOC7DYzMLK1sIe0cxrVdyZE9vX39AkLCLSOjY+MSqejTK7LyCkvKbmrqwBoTmlskO7t6QfsUemBkFwWFN8LoDJkFpZkABeTbkKi0OgsACMAAZ0QAaApCUTiNGYnFbABETy4XTgdBJLFebAgWK25B22mwUGKeAAhMQ5LwgA)

### 💻 Code

```ts
interface Options {
    width?: number;
    height?: number;
}

interface OptionsWithDataProps extends Options {
    // Permit any property starting with 'data-'.
    [k: `data-${string}`]: boolean; // this works as expected
}

interface OptionsWithOptionalDataProps extends Options {
    // Permit any property starting with 'data-'.
    [k: `data-${string}`]?: boolean; // this fails unexpectedly
}
```

### 🙁 Actual behavior

```ts
[k: `data-${string}`]?: boolean
```
fails with error:

>  error TS1005: ';' expected.

### 🙂 Expected behavior

it should work using the optional `?:` directive.

**Comment by MartinJohns** [comment]
[Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAUMmcgO7AAmYAFgPwBcyIArgLYBG0A3KeToRgAczphmrTjyj8AvsWKhIsRCgxZceAOrB6AEThg4ABSjZ0BCAA9IIagQ058RAWQD075Cegc9yOBAAT2R0c3RoMBC8YygsEBFKPTpkAHJqIzgAWlSAOjdkAG0AaxYAAwzjLIASQhioUBE5MoBdFi5sbAAbCEDeZE9kemACCmwoYoI4K2sIhEhqYgUlcGh4JDRMZx1kp1w4LsNjMwsZuwdNzRcScgGvHyg-MADg0PDI6Nj4xKp6NMrsnkCiVygCanUwA0Es0WpIOt1eiB+oNhgR4MAugQ2CAbHMFl0gktiEA), because @davidbielik didn't bother filling out the issue template.

**Comment by davidbielik** [comment]
> [Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAUMmcgO7AAmYAFgPwBcyIArgLYBG0A3KeToRgAczphmrTjyj8AvsWKhIsRCgxZceAOrB6AEThg4ABSjZ0BCAA9IIagQ058RAWQD075Cegc9yOBAAT2R0c3RoMBC8YygsEBFKPTpkAHJqIzgAWlSAOjdkAG0AaxYAAwzjLIASQhioUBE5MoBdFi5sbAAbCEDeZE9kemACCmwoYoI4K2sIhEhqYgUlcGh4JDRMZx1kp1w4LsNjMwsZuwdNzRcScgGvHyg-MADg0PDI6Nj4xKp6NMrsnkCiVygCanUwA0Es0WpIOt1eiB+oNhgR4MAugQ2CAbHMFl0gktiEA), because @davidbielik didn't bother filling out the issue template.

weird - i definitely filled it out, must have accidentally deleted the top section before I hit submit. I'll update it.

**Comment by nmain** [comment]
Index signatures don't support optionality:  https://github.com/Microsoft/TypeScript/issues/7118.  The template string part is a red herring -- try doing this with any other index signature and you'll see the same result.
