### ISSUE TITLE
Suggestion: Provide a way to infer the type of a `let` from usage

### ISSUE THREAD

**Issue by glenjamin** [microsoft/TypeScript#45823]
# Suggestion

Provide a way to infer the type of a `let` from usage

## 🔍 Search Terms

`let`, `infer`.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Provide some way to state that a `let` statement should adopt the type of its first use, rather than defaulting to `any` or requiring an explicit type declaration.

## 📃 Motivating Example

When a variable is populated at the same time as it is defined, we don't need to use a type declaration - typescript infers the type from first usage.

```ts
const x = 1; // number
const y = "blah"; // string
```

However, sometimes we need to modify a binding over time, and cannot assign it right away. A common scenario is in test fixtures:

```ts
describe("some tests", () => {
  let fixture;
  beforeEach(() => {
    fixture = setupFixture();
  });
});
```

In these cases, `fixture` has an implicit type of `any`.

We can avoid the any by using an explicit type annotation:

```ts
let fixture: ReturnType<typeof setupFixture>;
```

But it would be nice if we could tell typescript that we're just treating this like a single assignment that needed to be in a different scope, and have it infer the type for us, eg:

```ts
let fixture: infer;
```

This could lead typescript to set the type to the union of all assignments to the variable, or possibly just the first assignment lexically.

## 💻 Use Cases

Not having to explicitly annotate let bindings, this is especially relevant when the type is quite complicated - although using `ReturnType` or equivalent usually gets around this.

As well as the scenario above, this pattern can appear when extracting values via a loop:
```ts
let found: infer;
for (const x of list) {
  if (x.id == 1) {
    found = x;
    break;
  }
}
```

In the mean time I am explicitly annotating unassigned `let` statements

**Comment by nmain** [comment]
> In these cases, fixture has an implicit type of any.

It does not.

```ts
let foo;
(() => { foo = 3; })();

// This condition will always return 'false' since the types 'number' and 'string' have no overlap.(2367)
foo === "3";
```

**Comment by MartinJohns** [comment]
An explicit `infer` type annotation has already been proposed and declined: #36450

**Comment by MartinJohns** [comment]
@nmain In his fixtures example it's more in the realm of #9998. TypeScript has no way of knowing that the provided callback is executed immediately, resulting in the variable being set. You get the same behaviour in your example if you don't execute the callback.

**Comment by ahejlsberg** [comment]
The key point here is that we _do_ already infer the type of an uninitialized `let` variable from usage. It's just that we only make inferences when we know they're correct. In the motivating example, we don't know if or when the callback is ever called, so we make no inferences from it.

**Comment by glenjamin** [comment]
Right, this is motly my point - I'm looking for some way to explicitly annotate "use that one".

Given the extra details provided in these comments, I can see that this is a bit more niche than I'd originally thought.

**Comment by MartinJohns** [comment]
@glenjamin This issue is related: #11498
