### ISSUE TITLE
TypeScript server slow - CPU goes up to 160% when waiting for the autocompletion

### ISSUE THREAD

**Issue by gino** [microsoft/TypeScript#45824]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.61.0-insider (Universal)
- Operating system:
- macOS 11.5.2

Steps to Reproduce:

1. Got a simple Next.js application with `react-hook-form` installed (not sure if that matters), trying to get autocompletion on their `useForm` hook. Shows me "Loading..", takes a couple seconds, and CPU jumps up to 160% in the Activity Monitor. (I also got autocomplete issues on other places, not only on their hook, just used that as an example).
2. Originally got this issue in the normal version. Switched over to the Insiders version and still got this issue. The project isn't large and my CPU usage only spikes when I use features from the TypeScript server. I already installed the typescript@next extension and made sure that VSCode uses that version, unfortunately the same issue.

Even saving ts/tsx files can take a couple seconds. And whenever I try to use something that it is not imported, it shows the red line under it. However, when I do import it, it takes a couple seconds before VSCode notices it so the "not imported" error stays there for quite a long time and my CPU usage spikes.

**Edit:** I recorded a small video that shows when my CPU usage spikes and that VSCode randomly had trouble with importing a few things and that it takes a couple of seconds before it noticed that I already imported it. Also the autocomplete takes a couple of seconds and the CPU usage also spikes on that.

(I am not too sure why VSCode didn't automatically import the first two hooks, I needed to manually click on them and then it let me import them, as you can see in the video.)

https://user-images.githubusercontent.com/23482089/132833606-1c13bde4-a232-4f11-925f-cedccf7b239c.mov

When using the normal VSCode (not the Insiders version), the autocomplete is even slower and the CPU usage spikes up to 180% (even though all extensions are disabled). I noticed that the fans were going crazy when I was waiting for the autocompletion.

In the Process Explorer, `electron_node tsserver.js` is the one that spikes.

**Comment by mjbvz** [comment]
Can you please share a minimal example project along with steps to reproduce this issue so that we can investigate

**Comment by andrewbranch** [comment]
Sounds like #44851

**Comment by Lemzer** [comment]
@mjbvz I will have an example ready as soon as possible. I am trying to figure out if this issue is caused by the `ajv` package.

@andrewbranch I think it is. I see that this has something to do with the `ajv` package. I do not directly use this package in my project. However, I am using a resolver package from `react-hook-form` that does have `ajv` as a dependency. So I think this causes the same issue.

**Comment by gino** [comment]
@mjbvz I will have an example ready as soon as possible. I am trying to figure out if this issue is caused by the `ajv` package.

@andrewbranch I think it is. I see that this has something to do with the `ajv` package. I do not directly use this package in my project. However, I am using a resolver package from `react-hook-form` that does have `ajv` as a dependency. So I think this causes the same issue.

**Comment by andrewbranch** [comment]
@gino is it better when you disable semantic highlighting?

**Comment by gino** [comment]
After some time, I am having the same issue while being on TypeScript version 4.8.4.

I am having the same issue when I restart VS Code while having all extensions disabled.

[tsserver.log](https://gist.githubusercontent.com/gino/3db4660e016fefa50d91eea9b79eb80c/raw/d48603abb895ea9f00b146ce2ba10012a5aae93f/tsserver.log)

**Comment by andrewbranch** [comment]
Unfortunately that log looks totally normal. It took a little over 2 seconds for the project to load and the longest completions time was 618 ms, which isn’t phenomenal but it’s not terrible for a response that offers almost 1000 auto-imports. It’s normal for CPU usage to be high when TS Server is actively working, but from this log it looks like those spikes should be quite brief. If you’re experiencing delays that feel significantly longer than half a second, the issue doesn’t seem to be in TypeScript itself.

**Comment by gino** [comment]
@andrewbranch Thanks a lot for your quick response! Totally makes sense. I will look into what's actually happening and keep you updated.

**Comment by gydroperit** [comment]
Unfortunately, last version of zod is unusable due this speed regression for me.
I also did some benchmarks and found that problem is somehow connected this target in tsconfig.json

https://github.com/gydroperit/zod-test-regression

after version 3.19.1 the check time up to 14x times  longer for this simple repo

**Comment by gydroperit** [comment]
> @gydroperit Setting `"strict": true` in the `tsconfig.json` file as described in the [Zod documentation](https://github.com/colinhacks/zod#requirements) worked for me.
It really reduce check time, but unfortunately not the speed of autocompletion and also ESLint check. Nevertheless, I guess  it is not typescript problem, I bisected problematic commit in zod.

**Comment by gino** [comment]
Hi there. I would like to mention that I did not have this issue for a very long time but recently this issue is even worse than before. 

I feel like (zod)[https://npmjs.com/package/zod) might be the issue here, but I am not sure. Whenever I import something from the Zod library, my autocompletion takes very long and my CPU usage spikes. I am using it in combination with a few other libraries. Working on a `Form` component that uses Zod for validation.

```json
"zod": "^3.21.4"
"react-hook-form": "^7.43.9",
"@hookform/resolvers": "^3.0.1",
"typescript": "^5.0.2",
```

`tsserver.log`: https://gist.github.com/gino/ae445531e29b3f4cf42e34b659285b69

`tsc --extendedDiagnostics`:

```
Files:                          156
Lines of Library:             28794
Lines of Definitions:         33391
Lines of TypeScript:            236
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Identifiers:                  77603
Symbols:                    1649290
Types:                       974148
Instantiations:             5037430
Memory used:               1127521K
Assignability cache size:      5267
Identity cache size:           1242
Subtype cache size:               3
Strict subtype cache size:       10
I/O Read time:                0.03s
Parse time:                   0.63s
ResolveModule time:           0.08s
ResolveTypeReference time:    0.00s
Program time:                 0.81s
Bind time:                    0.24s
Check time:                  26.10s
printTime time:               0.00s
Emit time:                    0.00s
Total time:                  27.15s
```

For reference, I am following [this guide](https://www.brendonovich.dev/blog/the-ultimate-form-abstraction) for a nice Form approach.

**Comment by andrewbranch** [comment]
The best thing to do is take a [performance trace](https://github.com/microsoft/TypeScript/wiki/Performance-Tracing). But I would be shocked if zod isn’t the problem.

**Comment by gino** [comment]
> The best thing to do is take a [performance trace](https://github.com/microsoft/TypeScript/wiki/Performance-Tracing). But I would be shocked if zod isn’t the problem.

Yeah, I've also created [an issue](https://github.com/colinhacks/zod/issues/2311) in the Zod repository. Hope that this will get fixed soon!
