### ISSUE TITLE
Typescript does not pick up definitions with `exports` field in package.json

### ISSUE THREAD

**Issue by k2snowman69** [microsoft/TypeScript#45828]
# Suggestion

The ESM spec from Node has introduced the [exports](https://nodejs.org/api/packages.html#packages_exports) property which can replace main. This means that packages can now have exports and not main. An example of this is [globby](https://github.com/sindresorhus/globby/blob/main/package.json).

However without defining main, typescript's [definition location logic](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#editing-the-packagejson) does not automatically pick up the types.

The proposal is when there is No “types” field in the package json, to change `checks “main”, then index.d.ts` to `checks “main”, then “exports”, then index.d.ts`

This said, we would also need to figure out how to handle the more complex object structured "exports" functionality so this is an overly simplistic ask compared to what would actually be needed.

## 🔍 Search Terms

ESM, ES modules, exports, package, package.json

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The proposal is when there is No “types” field in the package json, to change 

 - `checks “main”, then index.d.ts` to
 - `checks “main”, then “exports”, then index.d.ts`

## 📃 Motivating Example

My org is currently basing a bunch of new updates based off the ESM spec and using sindresorhus' projects as a baseline. You can see his package.json doesn't have a main to automatically determine the types for.

https://github.com/sindresorhus/globby/blob/main/package.json

## 💻 Use Cases

Automatically finding the types associated with the entry file of exports.

**Comment by IllusionMH** [comment]
Looks like duplicate of #33079

**Comment by k2snowman69** [comment]
Sure is!
