### ISSUE TITLE
Typescript's function `transpile` ignores the project's compiler options and uses the default ones

### ISSUE THREAD

**Issue by ImRodry** [microsoft/TypeScript#45856]
# Bug Report

### 🔎 Search Terms

`transpile`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about transpile

### 🏷 Description

Since this issue cannot be accurately reproduced with a playground link or code, I have decided to remove those two fields and add this one.
Basically when using typescript's function `transpile`, the code that gets transpiled uses default compiler options if none are passed. I believe this should be improved so that it uses the project's compiler options by default without us having to use getParsedCommandLineOfConfigFile in order to get the compiler options.

### 🙁 Actual behavior

The code gets transpiled with typescript's default compiler options

### 🙂 Expected behavior

The code should get transpiled using the project's compiler options

**Comment by DanielRosenwasser** [comment]
`transpile` (semi-deprecated) and `transpileModule` shouldn't take the environment's context into account. It makes code less portable, so we expect API consumers to pass in what they expect.

**Comment by ImRodry** [comment]
I don’t understand, how does it make the code less portable? I use this function to evaluate strings of code and to see how they look when transpiled, and I want the actual result that TS would produce if it was a regular file. Is there a better way to do this?

**Comment by andrewbranch** [comment]
I guess the easiest way would be to read in the tsconfig options and then pass them to `transpileModule`, but you could also make a more sophisticated compiler host that knows about some virtual files if you want it to be more of a direct substitution of project-based compilation. What Daniel means is that the whole point of `transpileModule` is to provide transpilation to API consumers who _can’t_ read from a file system at will, so the whole process of resolving from a CWD to a project file on disk and reading those in is antithetical to the spirit of the API. (Also, changing it now to suddenly be FS-aware, causing current consumers to suddenly start producing different results, would be devastating.)

**Comment by DanielRosenwasser** [comment]
Thanks for giving more context @andrewbranch!

**Comment by ImRodry** [comment]
Thanks for the explanation @andrewbranch 
Just one last question, you mentioned transpileModule instead of transpile, is there a practical difference between using one or the other?

**Comment by DanielRosenwasser** [comment]
I think we have a slight preference for `transpileModule` just because it's easier to get the extra information later on. The original motivation for `transpileModule` was explained at https://github.com/microsoft/TypeScript/pull/3982

> \[The] existing `transpile` function returns emitted source code as a string so augmenting it to also return source map information will be a breaking change. Instead I've added new function `transpileModule` (suggestions for better names are welcome) that accepts arguments as record and returns an object containing generated code. source map data, diagnostics and any other stuff that we might want to add in the future.
