### ISSUE TITLE
Function rest parameter generic inference

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#45851]
# Bug Report

### 🔎 Search Terms

Keywords: `"rest"` `"infer"`
Found: https://github.com/microsoft/TypeScript/issues/45448 which seems slightly related.

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMYEYoF4oAoB0eCGATgOYDOAXFPgiANoC6AlBgHxQBuA9gJYAmA3AChBSTglLAoAd27AAFpzjAACkXwBbUikrxkaTFmbo2AbwC+IsROmy5qwhq07EqDNnwAaKACMvSI6YWgqCQsC4ATAA8ACpQEAAewBAIvKRUNAxsBng4RGSU0QEcPALCouKSMvKKKmqa4c7I4W6GrFDmlhU28vaODWFNLfiUEoTcCMRe3iPAYxN+M3PERR1AA)

### 💻 Code

```ts
type Func1 = (...args: any[]) => void;

const withoutParams1: Func1 = () => {}
const withParams1: Func1 = (a, b, c) => {}

type Func2<T extends any[]> = (...args: T) => void;

const withoutParams2: Func2 = () => {}
const withParams2: Func2 = (a: string, b: string, c: string) => {}
```

### 🙁 Actual behavior

`Func2` type raises error, even though it seems pretty similar to `Func1` type.

### 🙂 Expected behavior

`withoutParams2` at minimum should not throw error, because there's no difference with `withoutParams1`

**Comment by MartinJohns** [comment]
`Func2` is a generic type with one type-argument. You provided no type-argument. When the type-argument has no default type it **must** be provided. [Docs on generic types](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-types)

There's no defect here.

**Comment by IllusionMH** [comment]
I guess you confused position of type parameters. If they are used in type alias declaration - you need to use it as `Func2<Param>`, most likely guess you wanted to make type parameter as part of function declaration `type Func3 = <T extends any[]>(...args: T) => void;`
This will be closer to `Func1` but still produce different set of expected errors related to this [FAQ](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters).

[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMYEYoF4oAoB0eCGATgOYDOAXFPgiANoC6AlBgHxQBuA9gJYAmA3AChBSTglLAoAd27AAFpzjAACkXwBbUikrxkaTFmbo2AbwC+IsROmy5qwhq07EqDNnwAaKACMvSI6YWgqCQsC4ATAA8ACpQEAAewBAIvKRUNAxsBng4RGSU0QEcPALCouKSMvKKKmqa4c7I4W6GrFDmlhU28vaODWFNLfiUEoTcCMRe3iPAYxN+M3PERR3B4NC6SADMbjFxicmp6XT0LLgEJBRQhW1cfEKd1lUKSr2aW43bLSsW5U+2AHkEBA3h8Bl8DMMoKNxss2h0-pVbG9SGDNjtIYtYVMsfMoEhcXDjO0zEA)

**Comment by kitsoRik** [comment]
I think you can reach similar behaviour with function generics. Like that 
`function justFunc<T extends any[]>(fn: Func2<T>) {

}

justFunc((a: string, b: number, c: boolean) => {

})`

Where `justFunc` can determinate type from first argument, but for types (for variables) you can't do that, because there's two different behaviours behind the single type.

**Comment by y-nk** [comment]
thank you @kitsoRik for the extended answer with example. it feels somehow counter intuitive that 1st can work. I totally understand why `any[]` is not matching `undefined` in the second example, but the fact that it works in the 1st is at the same time very convenient _and_ weird.

I would have expected that `...any[]` expects the type of rest arguments to be array of any, but it seems that `undefined` also works implicitly.

It should, in my opinion, have been `fn(...args?: any[])` to allow a call with no arguments.

**Comment by MartinJohns** [comment]
> It should, in my opinion, have been `fn(...args?: any[])` to allow a call with no arguments.

An optional spread argument makes no sense and is invalid. But `fn(...args: any[])` actually is callable without arguments.

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMMAKAdJghgJwOYDOAXIlmAJ4DaAugJSIDeAvgLABQ7Kqt7QA

**Comment by kitsoRik** [comment]
> thank you @IllusionMH @kitsoRik for the extended answer with example.
> 
> (@ALL) it feels somehow counter intuitive that 1st can work. I totally understand why `any[]` is not matching `undefined` in the second example, but the fact that it works in the 1st is at the same time very convenient _and_ weird.
> 
> I would have expected that `...args: any[]` expects the type of rest arguments to be array of any, but it seems that `undefined` also works implicitly.
> 
> It should, in my opinion, have been `fn(...args?: any[])` to allow a call with no arguments.

FYI, you can assign default values for generic (`type Func2<T extends any[] = []> = (...args: T) => void;`) and you won't receive errors for `const withoutParams2: Func2 = () => {}`

**Comment by y-nk** [comment]
@MartinJohns what i'm pointing out is the lack of consistency between Func1 and Func2 behaviors, which was explained by @kitsoRik solution's to set default. but thanks for the constructive comment which just points out what i didn't understand, it really helped 😓 

@kitsoRik that made sense a lot, thank you.
