### ISSUE TITLE
Being able to keep uninitialized properties in classes (via tsconfig)

### ISSUE THREAD

**Issue by sharshuv-quotient** [microsoft/TypeScript#45852]
# Suggestion

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a new flag for the tsconfig, that will enable to change the following the behavior: 

This typescript class:
```ts
class A {
  x: number;
}
```
Will be currently compiled to:
```js
class A {
}
```
Aka the property x will be dropped because it's not initialized. But in javascript it is actually possible to define:
```js
class A {
  x
}
```
So when calling `new A()` the property x will be initialized with undefined. 

I would like to add a flag for typescript to change this behavior so the above code will be compiled to a class with the property. 

## 📃 Motivating Example and 💻 Use Cases

Sometimes you want to pro-grammatically get the properties of a class. If a class is not initializing the properties, you cannot get all the properties easily in runtime, like described [here](https://stackoverflow.com/questions/51057508/uninitialized-typescript-class-properties-are-not-iterated).

The workaround (setting default values for all properties) is not preferred since it forces me to add additional redundant code to the class. Also in strict null checking mode I will not be able to just pass undefined.

**Comment by nmain** [comment]
This already exists as `useDefineForClassFields`.

**Comment by fatcerberus** [comment]
> Also in strict null checking mode I will not be able to just pass undefined.

With strictNullChecks enabled, not initializing the property before the constructor returns is still an error, so this particular point doesn’t really change anything.
