### ISSUE TITLE
[VS2015]Opening a list of files excludes tsx files from tsconfig project

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4585]
If you open visual studio and click file -> open -> file, and open your `tsconfig.json` and the `ts` files it includes, they're usually dumped into a "tsconfig project". Unfortunately, `tsx` files, even when explicitly listed in your `tsconfig.json` are split into a _different_ anonymous project. Additionally, that second project with only the `.tsx` files ignores your `tsconfig.json` settings.

**Comment by mhegazy** [comment]
@paulvanbrenk you have a fix for this, correct?

**Comment by paulvanbrenk** [comment]
Yes, I checked in a fix yesterday.
