### ISSUE TITLE
Extension can't distinguish between variables in one file and the other

### ISSUE THREAD

**Issue by grian32** [microsoft/TypeScript#45867]
First file, error after the second file was created:
![image](https://user-images.githubusercontent.com/54550982/133284310-aa693e10-6a1d-4da7-8cc0-47960203a4a1.png)

Second file, no error: 
![image](https://user-images.githubusercontent.com/54550982/133284259-1e539b4d-318d-4dfa-b503-15c039a2cc6e.png)

File tree:
![image](https://user-images.githubusercontent.com/54550982/133284338-04d7c620-3b41-437e-8b8d-c9003e45b056.png)

denoland/vscode_deno#540 related

**Comment by IllusionMH** [comment]
Without `import`/`export` file is treated as scripts in global scope, not modules.

You can add `export {}` to make it explicit or use `isolatedModules`
