### ISSUE TITLE
Invalid parse error with newline and division

### ISSUE THREAD

**Issue by jrieken** [microsoft/TypeScript#4587]
This snippet (note the newline) produces a parse error

``` javascript
if ((a / b > c) &&
d) {
// Do stuff
}
```

**Comment by mhegazy** [comment]
@vladima can you take a look

**Comment by JoshuaKGoldberg** [comment]
There is no longer a parse error for that snippet! 🙌

**Comment by jakebailey** [comment]
Just looking at ancient issues; this bug has been fixed longer than I can reasonably test without a time machine to resurrect a machine which can build such old versions of TS; I'm going to close this.

**Comment by jrieken** [comment]
2015!
