### ISSUE TITLE
DeviceMotionEvent in lib.dom.d.ts remove the property requestPermission

### ISSUE THREAD

**Issue by MrIrick** [microsoft/TypeScript#45888]
version 4.4.3

![image](https://user-images.githubusercontent.com/22052869/133395578-2bbcbc4d-b310-4e51-bac0-c3be1b60ca92.png)

why remove the requestPermission property in type file.

got error no property in DeviceMotionEvent after update

**Comment by RyanCavanaugh** [comment]
Duplicate #47161

**Comment by MrIrick** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，邮件已经收到，近期回复！！！！
