### ISSUE TITLE
The ES Nest bind operator has reached stage 1

### ISSUE THREAD

**Issue by hexagonrecursion** [microsoft/TypeScript#45885]
# Suggestion

https://github.com/Microsoft/TypeScript/issues/3508#issuecomment-456615454
> We'll revisit this if the proposal proceeds to stage 1.

A fork of the bind operator proposal has reached stage 1: https://github.com/tc39/proposal-extensions. Unfortunately the original issue is locked. Ping @DanielRosenwasser

## 🔍 Search Terms

revisit bind proposal

**Comment by DanielRosenwasser** [comment]
https://github.com/microsoft/TypeScript/issues/3508#issuecomment-920288203

**Comment by MartinJohns** [comment]
@DanielRosenwasser You opened the issue again, but the conversation is still locked.

**Comment by andrewbranch** [comment]
Thanks @MartinJohns, fixed

**Comment by DanielRosenwasser** [comment]
@MartinJohns 🤫

(kidding)
