### ISSUE TITLE
direct import of files from node_modules triggers errors in ts 4.4 if watch mode is enabled

### ISSUE THREAD

**Issue by eltonio450** [microsoft/TypeScript#45891]
# Bug Report

Summary : with typescript 4.4, yarn PNP and `moduleResolution: "node"`, the behaviour is inconsistent between watch mode and normal mode (when importing css files for example)

### 🔎 Search Terms

pnp watch tsc exclude option moduleResolution node

### 🕗 Version & Regression Information

Not present in 4.3.2
Present in 4.4.2

### ⏯ Playground Link

https://github.com/eltonio450/example-tsc

yarn install first

then : 
`yarn tsc` => normal behaviour
`yarn tsc --watch` : buggy behaviour

### 💻 Code

```
import "mapbox-gl/dist/mapbox-gl.css"; //has to be from a dependency
const basicCode = 1
```

### 🙁 Actual behavior

When running `yarn tsc`, the code is transformed without error
When running `yarn tsc --watch`, I get the following error : `Error: ENOTDIR: not a directory, stat '/node_modules/mapbox-gl/dist/mapbox-gl.css/package.json'`

### 🙂 Expected behavior

The behaviour should be consistent between watch mode and normal mode

More info : 
- Windows WSL 2
- the bug does not occur when using `nodeLinker: node-modules`

I feel that it is related to a weird interaction between watch mode, pnp and path resolution of node_modules (starting  from typescript 4.4)

I did not find any related issue, I am not sure if it's a typescript or yarn issue

Thank you !

EDIT : it is not specific to css file, any import of a file from node_modules crashes

`import "mapbox-gl/dist/mapbox-gl.js"`

**Comment by andrewbranch** [comment]
What is `nodeLinker: node-modules` and does the problem reproduce without pnp? This feels like a yarn issue to me.

**Comment by eltonio450** [comment]
thank you for the answer

indeed, the problem does not reproduce without pnp (= `nodeLinker: node-modules` )

but the thing is : the behaviour is different with and without the --watch option, pointing that this is also related to typescript itselft

**Comment by andrewbranch** [comment]
As far as I know, pnp totally overrides our resolution, so I don’t think this is a TypeScript problem.

**Comment by merceyz** [comment]
It's probably a bit of both, TypeScript is checking if `C:/Yarn/Berry/cache/mapbox-gl-npm-2.4.1-7d6142909b-8.zip/node_modules/mapbox-gl/dist/mapbox-gl.js` is a directory which it isn't so we end up here https://github.com/microsoft/TypeScript/blob/6758a12f03f5df77b7e5122e2788a4d11843e8a7/src/compiler/moduleNameResolver.ts#L1402 later when it's creating the watchers at https://github.com/microsoft/TypeScript/blob/793bfe32745bf6797924354b0fd5be62cf01950c/src/compiler/watchPublic.ts#L479 `packageCacheEntries` contains 
```json
["C:/Berry/cache/mapbox-gl-npm-2.4.1-7d6142909b-8.zip/node_modules/mapbox-gl/dist/mapbox-gl.js/package.json",false]
```
which it tries to create a watcher for when it's probably supposed to skip it

**Comment by andrewbranch** [comment]
Happy to mark this as a bug if anyone can repro it without pnp

**Comment by eltonio450** [comment]
Thanks @merceyz for the hint. I tried many things to mitigate the bug, such as configuring watchOptions to ignore node_modules, or mapbox-gl, with no luck

I cannot reproduce the problem without pnp :(

**Comment by merceyz** [comment]
@andrewbranch I see now that TypeScript is watching for the file to potentially exist at some point in the future which does make it a bug on our end, feel free to close 👍

**Comment by andrewbranch** [comment]
👍 thanks for investigating!
