### ISSUE TITLE
Error 1064 should apply to `@callback` definitions in the same way as `@param`, but doesn't 

### ISSUE THREAD

**Issue by katelynsills** [microsoft/TypeScript#45901]
# Bug Report

I'm using JSDoc to provide type information for JavaScript files. I found a difference in behavior between one-off `@param` definitions and `@callback` definitions where there should not be a difference. Specifically, with `@param`, async functions require a return value of Promise<T>, but with `@callback`, they do not. 

### 🔎 Search Terms

1064, `callback`, async functions, Promise<T>
"The return type of an async function or method must be the global Promise<T> type. Did you mean to write 'Promise<{0}>'?"

### 🕗 Version & Regression Information

I was able to reproduce using Typescript v4.2.3 and v4.4.3. I didn't test other versions.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about common bugs that aren't bugs, as well doing a text search for `Promise` and `async`.

### ⏯ Playground Link

[Playground link with `@param`](https://www.typescriptlang.org/play?ts=4.4.2&ssl=7&ssc=3&pln=1&pc=1&filetype=js#code/PQKhCgAIUgBAHAhgJ0QW0gbwM4BdkCWAdgOYC+keyUMsyAprgK7JHZZXHk3DgDGAeza5IaAJ4AxIpAC8kRNjFE+lfLIB8WKJB0NmrVcgDc4MkaA) - has error
[Playground link with `@callback`](https://www.typescriptlang.org/play?ts=4.4.2&filetype=js#code/PQKhCgAIUgBBjAhgG2QI0fA1pAsgTwDEA7KGWAB0QCdEBbSAbwGcAXagS2IHMBfSNtTJxqAU1YBXasWZNBXPmWDhwocq3wVRTAiX4hl8APYzWkOkWKQAvJETN8xeAPY2AfEyiRvYydJfUANzgvIFAA) - no error

### 💻 Code

With `@param`:
```js
/**
 * @param {string} str
 * @returns {string}
 */
const myFn = async str => {
    return str;
};
```

With `@callback`:
```js
/**
 * @callback MyFn
 * @param {string} str
 * @returns {string}
 */

/** @type {MyFn} */
const myFn = async str => {
    return str;
};
```

### 🙁 Actual behavior

The version with `@param` produces error 1064, but the version with `@callback` does not.

### 🙂 Expected behavior

Both ways of writing the definition should produce the error.

**Comment by sandersn** [comment]
This is definitely a bug. My guess is that some specific async-checking code is not running correctly in the `@type` code path.
There's probably an easy fix -- make the async code run on `@type` -- and a medium-difficulty fix -- make it harder for `@type` checking to mismatch the main code path.

**Comment by a-tarasyuk** [comment]
Currently, TS assign an error to return type
```ts
/**
  * @param {string} str
  * @returns {string}
              ~~~~~~
!!! error TS1064: The return type of an async function or method must be the global Promise<T> type. Did you mean to write 'Promise<string>'?
  */
const foo = async str => str;
```

@sandersn Where do we need to assign the error for `@type/@callback`?

/cc @andrewbranch

**Comment by CptPanko** [comment]
First time contributor here, trying to understand/fix the issue

**Comment by sandersn** [comment]
@a-tarasyuk Are you asking about the error span? It should be on the type reference of the `@type` tag -- `MyFn`.
The error should probably refer to the function type as a whole instead of just the return type, although there will likely be an elaboration.

**Comment by sidharthv96** [comment]
https://github.com/microsoft/TypeScript/blob/506a95b5a5c992c774eb0c9463ee20dc1f5c8a6c/src/compiler/utilitiesPublic.ts#L840-L862

There are 3 checks being done and all fails, isTypeLiteralNode, isFunctionTypeNode, isJSDocFunctionType

Because actually, it is a ReferenceType so, `isTypeReferenceType` can be used to check that case.

But I'm kinda lost on what to do after that, How can I get the return type from a reference type?

@sandersn Am I on the right path and if so any pointers on how to proceed?

**Comment by sandersn** [comment]
`getReturnTypeFromAnnotation` does the necessary work and calls `getEffectiveReturnTypeNode/getJSDocReturnType` as needed. The problem is that it returns the type, not the node that references the type. So the fix to `checkAsyncFunctionReturnType` isn't trivial.

**Comment by sidharthv96** [comment]
Won't `getJSDocReturnType` returning undefined affect other use cases too?

https://github.com/microsoft/TypeScript/blob/eb3645f16b66ed05110ea957c77773cea739bae8/src/services/codefixes/annotateWithTypeFromJSDoc.ts#L57-L60

and `getEffectiveReturnTypeNode` seems to have lots of uses too... 

<img width="621" alt="image" src="https://user-images.githubusercontent.com/10703445/138022085-9494dbb6-bdc9-4628-a51a-9f821ea59ae2.png">

**Comment by a-tarasyuk** [comment]
@sandersn I've prepared a draft PR. Would you be able to review it and share your thoughts on whether it's the correct approach to handle that particular case? Thanks
