### ISSUE TITLE
Capture more info in TS Server errors to help provide repros

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#45900]
When TS Server crashes / issues an error response, VS Code will prompt users to open an issue with the error stack under some circumstances: https://github.com/microsoft/vscode/blob/4fcbe9449c57ff1e65f134dde6df58cb28bcea5f/extensions/typescript-language-features/src/typescriptServiceClient.ts#L988

Many of these users open the issue, but don’t fill out other info in the template, and don’t respond to requests for more information. TS Server could provide more info about its current state in its error response to help make these issues easier to reproduce, even if the user is unresponsive. What I want most right now is a list of dependencies being processed when the stack mentions `AutoImportProviderProject`: see #45874. @DanielRosenwasser suggested it might be possible to include the last few commands that the server processed.

**Comment by DanielRosenwasser** [comment]
> @DanielRosenwasser suggested it might be possible to include the last few commands that the server processed.

If we're thinking about user-reported crashes, I would be interested in being able to see the last few files that got "jumped to" within the checker etc. Maybe some way to track calls to `host.getSourceFile`.

**Comment by DanielRosenwasser** [comment]
I wonder if users would be able to provide a repro more easily if we were able to tell them what file and range was requested (if that's relevant)

**Comment by andrewbranch** [comment]
We can come back to this if needed, but I’m going to close it out given our recent success in finding repros via better TS Server fuzzer scenarios.
