### ISSUE TITLE
Type parameter in template literal type is inferred as never

### ISSUE THREAD

**Issue by zyf0330** [microsoft/TypeScript#45906]
# Bug Report

### 🔎 Search Terms

Template Literal Type
Default Value of Generic
Property Chain

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____Template Literay Type_____

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&noLib=true&jsx=0&module=1&isolatedModules=false&allowSyntheticDefaultImports=true&keyofStringsOnly=true&ts=4.3.5#code/C4TwDgpgBAygxgCwgWwIZQLxQN4FgBQURUqAXDgcVVAEbl6HVNzkB2ArsjRAE6VNQAvvyLD8YggDN2rOMACWAe1ZREqeawA8AMSgQAHsAisAJgGcoAawghFk2IhTosMkxEkaIJgDRRtARj1DY3MrGzsHJDQAbW0AXUwoV3dPHz8AJiCjUwtrW3t4KNRYuNj-BJdTFNYvKAA+AAoPCAAbE3JdAB8oAAMAEmxtQQA6AYDBHqhu-sGRsf85wfSJgEoKfAIxaVkFZVUEdVZ0nSyQ3PCCxzRE5I8atIDTnLD8yKcSm6q7r19tTINsqE8hFCu94mUKkkvql6k15K12n5fJJ-AB+Dr+ZHpdEZNYMTYEAhqDQNABEqFJKyJBxJ5OGNEpUAA9EyMlAAObGXjyOBQeQWDSSXi1VAWGoAN14vho7GAfLl-KCkDktWAilo0FuqWphzJqHpwzglMJ+GJRz1xtNNPN5NJvlJDLWLLZiq19xIFgMyqMJh1GnSFvtDPtRpWQA)

### 🙁 Actual behavior
1. `F, F1, F2` in function `chain` is infered wrongly as `never, never, never` when only first level property `field` is passed
2. `F2` in function `chain("a.b")` is infered as `never`

### 🙂 Expected behavior
1. `F` in function `chain` is infered correctly as `"a", undefined, undefined` when only one argument `field` is passed
2. `F2` in function `chain("a.b")` is infered as `undefined`

**Comment by zyf0330** [comment]
I have above problem is because that I write code like this
```
type A<T = undefined, T1 = undefined, T2 = undefined> = T1 extends undefined ? T : T2 extends undefined : T1 : T2  
```
And I cannot make it work if use `extends never` instead of `extends undefined` to judge.

**Comment by DanielRosenwasser** [comment]
[Shorter example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAygxgCwgWwIZQLxQN4FgBQURUqAXDgcVVAEbl6HVNzkB2ArsjRAE6VNQAvvyLD8YggBMIcADaoe0AGbtWcYAEsA9qyiJUG1gB4AYlAgAPYBFaSAzlADWEEFqWxEKVAD4AFEo0IWUlyMwAfKAADABJsE0EAOlj4yIBKcgA3LQ1JAG4CfUNfACJUYtSCIA)

```ts
type Schema = {
    a: {
        b: {
            c: number
        }
    }
}

declare function chain<F extends keyof Schema>(field: F | `${F}.${F}`): void;
chain("a")
```


I'm guessing what happens is that when we try to infer from a string literal type to a template string type, we assume that we should infer `never` for each type parameter rather than not inferring at all.

**Comment by zyf0330** [comment]
@ahejlsberg Hello, may I know when this fix will be released?

**Comment by ahejlsberg** [comment]
>Hello, may I know when this fix will be released?

It'll be in the TS 4.5 beta, due to release any day now.

**Comment by DanielRosenwasser** [comment]
You can also use it in our nightly releases.
