### ISSUE TITLE
TS2775 when using arrow function for type predicate

### ISSUE THREAD

**Issue by dckc** [microsoft/TypeScript#45919]
# Bug Report

Our shop prefers arrow function style and JSDoc annotations. I've got a type predicate that works as a function declaration but as an arrow function, I get 2775

### 🔎 Search Terms

 - arrow function
 - type predicate
 - TS2775

### 🕗 Version & Regression Information

Version 4.2.3 (and whatever version the playground runs)

- This is the behavior in every version I tried

### ⏯ Playground Link

[error](https://www.typescriptlang.org/play?ts=4.4.2&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQcJIBPAB2QBNkAzUAb3tABtkBzaALlADsBXALYAjZACdQAXwmgAgjwCWAgIbMCOYFlz5CxclVoNZC5c1AAyQ9CUkuoAORClotHamgAIgHs2ajdjxqEGROSgIMcooq0tAU8IrIPIHgosiQfKI80IZK0NBiMKAxqPE8oPJZXmySvhjIAB5knqKQoPCemS3wSgo8yKAAvIWxJQMAfAwEZXQAFFq6FIaVkoRg00VxAgkAlAB0VjagAIT9gw5OLlugkIiingDuoAAqegCiorei01sA3JMpaRlQHweNQaPJepRfhJfv4iOBgqJQpZIKJwWwANoAXWWTjYADcVrUGk1Ou1oC1lOCBqBcQT+uN6JM5lA9IYIiZlupJm0OkNipseABGakAKQAygB5AByOwReWmtPRAGZMT9ud1wcg1sMBYK1aBWmTPKwdsxvNr+QlBXtrNA1dCMEA)

### 💻 Code

```ts
// @ts-check

/**
 * @typedef {{ legs: number }} Animal
 */

/**
 * @typedef { Animal & { says: 'bark'}} Dog
 */

/**
 * @param {Animal} specimen
 * @returns { asserts specimen is Dog }
 */
export const canine = specimen => {
  if (/** @type { Dog } */ (specimen).says !== 'bark') throw TypeError();
  return undefined;
};

/** @param { string[] } argv */
export const main = argv => {
  /** @type { Animal } */
  const specimen1 = JSON.parse(argv[3]);
  canine(specimen1);
  console.log(specimen1.says);
};
```

### 🙁 Actual behavior

```
Assertions require every name in the call target to be declared with an explicit type annotation.(2775)
```

### 🙂 Expected behavior

same as when I change the arrow function to a function declaration:

[no error](https://www.typescriptlang.org/play?ts=4.4.2&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQcJIBPAB2QBNkAzUAb3tABtkBzaALlADsBXALYAjZACdQAXwmgAgjwCWAgIbMCOYFlz5CxclVoNZC5c1AAyQ9CUkuoAORClotHamgAIgHs2ajdjxqEGROSgIMcooq0tAU8IrIPIHgosiQfKI80IZK0NBiMKAxqPE8oPJZXmySvhjIAB5knqKQoDR8PPCQ8p6l8EoKPMgAFEVxAgkAlAwEZXRDWroUhpWShGAjsSUTAHRWNqAAhAC8R-aOznZTkIiingDuoAAqegCioreiQxMA3DMpaRlQO1qDR5INKL8JL9-ERwMFRKFLJBRGC2ABtAC6qycbAAbmtag0mi14D1oC1lGDQKccfijgA+aagUALKB6QwREyrdQzUmZFqjEoARmpoAAUgBlADyADltvC8kNaWiAMwYn68-pg4aC8Y8IUa5l86CeVjbZjeDbFPVC3bWaAaqEYIA)

**Comment by ilogico** [comment]
Looks like you can work around it by using a `@type` annotation instead: [playground](https://www.typescriptlang.org/play?ts=4.4.2&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQcJIBPAB2QBNkAzUAb3tABtkBzaALlADsBXALYAjZACdQAXwmgAgjwCWAgIbMCOYFlz5CxclVoNZC5c1AAyQ9CUkuoAORClotHamgAIgHs2ajdjy6FAwAFNAU8IrIPNxyiioAlKAAvAB8oErQ0GIwoGGokTyg8tAe3tLqGMgAHmSeopCg8J480A3wSgo8yMm54QXJafQERXTBWoHdTF5skoRgoX0CUfEAdFY2oACESUn2js52iZCIop4A7qAAKnoAoqKnosHxANzDosiQfKKFfDzUNPIupRXhJXv4iOAyE4lAJLJBRIC2ABtAC6sycbAAbnNKjU6m1mq1QMpAT0MdjUgxhuMoHpDLETLMKqBGoSGnkIkseABGHoAKQAygB5AByKyhoiywXJSIAzCiXsN2p1kAt8lzuYqWU0Wp5WCtmN41Zyoty1tZoIrQRggA)
