### ISSUE TITLE
String literal completions missing when last argument of a call is followed by a comma

### ISSUE THREAD

**Issue by ionut-gheorghe** [microsoft/TypeScript#45917]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.1
- OS Version: win 10 version 2004

Steps to Reproduce:
Suggestions not shown if arguments of a method are on multiple lines and the last argument is followed by a comma

![image](https://user-images.githubusercontent.com/54311614/133656470-48325563-8e90-492d-9bb2-9fe385b596f8.png)
![image](https://user-images.githubusercontent.com/54311614/133656515-f4e819d2-0223-4071-8445-d3b5b457325a.png)

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
