### ISSUE TITLE
Different behavior for "Conversion ... may be a mistake" when the type being cast contains `undefined`

### ISSUE THREAD

**Issue by niieani** [microsoft/TypeScript#45926]
# Bug Report

### 🔎 Search Terms

conversion, cast, undefined, 2352

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type casting (no entries)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/PTAEBcHcHtQQwDYFtoGdygJYBMCmA7cTAY0VADMBXfYo6fVAGlHt1ACc5NVdV59Qudu2jtmrUNmi98AcnAAoEBAAWbeggCekzOXJCCxNtywDIKkipbs87UADc47THABGCY32JriAa1zYFKKgAAbUeOSY+AEhCgrE9OigAOa44ABqOLjQAGKiSHAYALygABTgnH6oAFygACqVvgDaALoAlKBFAHygAN4KoKAJDBj2WdANcH6dEI2oAHSR+NilA4NlFVO+Hd2zW-PgmgAObEVnoLKZeNCya21rw0lj1wCS+OSwJc-Zk9NwfFcfo1QAAfUDhXBLAJrXRlACE32gbw+HXYaUo7HwazWaPAGIEiOR0AUAF84o8MKkMuM8uwCuAAOqYcAqaCUcAAVWWkKiARm5TmtV+zXanR6-UGFIc42FM02VUWURWa0GAq2Ox68t8B2Op3Ol3Gt0G90GsNKCJljVR6MxD0So3GRJmiNl-1AgImjWxg1x+Olr3exLJClwAA8jqIMFFwEJyFM2B7ZRKILragbrkbQAARDGFTD0WroZz4ZKkuJhiPsDCHE71YElZM13BpgDiBCEiFkoIuHq7YNkAEFKNh87cSaAAGSgABKuASNgAPEWoslmNRfPhoJB8F0FEA)

### 💻 Code

```ts
const getVideoFormat = (tracks: Track[]) => {
  const videoTrack = tracks.find(
    (track) => track.type === 'Video'
  )
  const videoInfo = videoTrack as VideoTrack | undefined
  //                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  //                             no error

  if (!videoInfo) return
  return videoInfo
}

const getVideoFormatWithoutUndefined = (tracks: Track[]) => {
  const videoTrack = tracks.find(
    (track) => track.type === 'Video'
  )
  if (!videoTrack) return
  const videoInfo = videoTrack as VideoTrack
  //                ^^^^^^^^^^^^^^^^^^^^^^^^
  //                          error
  
  return videoInfo
}

export interface VideoTrack {
  type: 'Video'
  Duration: string
}

export type Track = {
  type: 'General' | 'Video' | 'Audio'
} & Record<string, unknown>

```

### 🙁 Actual behavior

When we cast `as VideoTrack | undefined`, the error 2352 isn't raised, but when we cast `as VideoTrack` it is raised. Full error:

> "Conversion of type 'Track' to type 'VideoTrack' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first." 

### 🙂 Expected behavior

Error 2352 is raised in both cases.

**Comment by andrewbranch** [comment]
`as` prevents you from asserting between two types with no overlap. When both types contain `undefined`, that’s an overlap. Is it a meaningful overlap? Maybe not most of the time. But I don’t think we could seriously consider such back-compat breaking change to make a feature designed to allow unsoundness slightly less unsound.
