### ISSUE TITLE
type A = ['🌑', '👾'] [-1]   //----------->  🌑" | "👾" 

### ISSUE THREAD

**Issue by fc01** [microsoft/TypeScript#45927]
```ts
// ?????  TypeScript 4.4.2
type A = ['🌑', '👾']
type B = A[-1] //-------------> "🌑" | "👾"
type C = -1 extends keyof A ? 1 : 0 //-------------> 1
```

[playground](https://www.typescriptlang.org/play?#code/PTAEH5M1QFQTwA4FMDKBjATgS0QF1ABYA6EgJgFgAoPJZUAQVAF5QBtAckB4NwRH2OAaUB0C8G4D8djgF1qtFKABCLRmwC0ARgmgQy7Tt06AfKABEvI6AA+xsUel1QAYUVrQyAB55kAOwAmAZ1AA1sjwAPYAZowQoKqgAFygAAyawHqp2oaqQA)
 
![image](https://user-images.githubusercontent.com/9409898/133745973-922449e5-58ea-4de0-b218-9dc5d6cb1288.png)
![image](https://user-images.githubusercontent.com/9409898/133746024-72af46db-5d6b-4638-ab4d-ff437c990077.png)

- 👾 Sokoban Game in Pure TypeScript Type System

- Repo: [https://github.com/fc01/TypeGame](https://github.com/fc01/TypeGame)

- ![](https://fc01.github.io/TypeGame.gif)

**Comment by MartinJohns** [comment]
Is this a bug report? A feature request? Just advertisement? No clue.
