### ISSUE TITLE
Bad path for tsc.exe when using TypeScript 1.4 or 1.5 with Visual Studio Online Builds for Visual Studio 2015 Projects

### ISSUE THREAD

**Issue by TheSchmoe** [Microsoft/TypeScript#4593]
This issue is similar to issue #3493.

When running a build using the new build system via Visual Studio Online, the following errors occur:
![image](https://cloud.githubusercontent.com/assets/2472663/9612579/6f0a1d46-50b4-11e5-98e7-619e863f77dc.png)

This occurs whether I am using TypeScript 1.4 or 1.5 in my project (the highlighted part of the path reflects the TS version being used).  My last successful build finished at 5:03 PM, EST on 8/31/2013 and without any code changes, my builds are all failing now with this same set of errors.

**Comment by mhegazy** [comment]
As mentioned in https://github.com/Microsoft/TypeScript/issues/3493#issuecomment-13682268, we have  contacted the VSO team and they are working on fixing the issue. this is not caused by any changes on the TypeScript side.

**Comment by TheSchmoe** [comment]
Closing issue, as this is a problem with VSO, not TypeScript.
