### ISSUE TITLE
es5 destructing error

### ISSUE THREAD

**Issue by Reaphook** [microsoft/TypeScript#45949]
# Bug Report

### 🔎 Search Terms
destructing transformers

### 🕗 Version & Regression Information

- This is a crash when i use target in es5
- This is the behavior in every version I tried
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1#code/GYVwdgxgLglg9mABFApgZygRgBQEpEDeAsAFCKIA2KUiwMAThogLyIAMA3KeVTWihAQATFuy5la4aPDAAqRAHM8hbuVoMmAalaZxaxAE8YKCkL1r+gsCO2JdqgL6lVvRPQCGYAMLuoEABaiwO4U-OKqUPQGKhLkUP70cADuinjmDogQvgGI2ADaAHRFeQA0ALpl+MSxVmhwVAUUcEp0jFAldrjm5LX1KI3N2JbCHZhdquQe3tmBrJEgKOnOEr0NTUpTPn7+HQBEKAAeAiCoIgAGWdtniABGTRAA1rvjJE4kqBg4uEA)

### 💻 Code

```
function test() {
  let first = 0;
  let second = 0;
  function* g() {
    first += 1;
    yield;
    second += 1;
  }

  let ranCatch = false;

  try {
    throw g();
  } catch ([...[,]]) {
   console.log(first, 1);
    console.log(second, 1);
    ranCatch = true;
  }

  console.log(ranCatch, "executed `catch` block");
}
test()
```

### 🙁 Actual behavior
[ERR]: "Executed JavaScript Failed:"
[ERR]: _a.slice is not a function
reason: it don't convert to array before calling slice method

### 🙂 Expected behavior
log:
1 1
1 1
true 'executed `catch` block'

**Comment by IllusionMH** [comment]
Loooks like you forgot to enable `downlevelIteration` in `tsconfig.json`. 

See https://www.typescriptlang.org/tsconfig#downlevelIteration
