### ISSUE TITLE
Inconsistent behavior in comparing Records whose key types are template literals

### ISSUE THREAD

**Issue by jim-nomad** [microsoft/TypeScript#45945]
# Bug Report

### 🔎 Search Terms
looked at both open and closed
"template literal"
"Record const return"
"Record template literal"
Based on how simple this issue is and how easy it is to replicate, I'm surprised that I wasn't able to find someone else reporting it and I'm unsure if this is even a bug- but it sure seems that way.
### 🕗 Version & Regression Information
v4.4.2 (also replicable on nightly)
Does not appear to be a regression but seems to be a duplicate of/related to: https://github.com/microsoft/TypeScript/issues/42192 which was closed as fixed.

### ⏯ Playground Link
I was able to replicate this pretty succinctly in the playground:
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/GYVwdgxgLglg9mABFApgZygZSgJxmAcwAoBKALkQAMASAbwz0IF8AjAQx0sVoFgAoRIhwooIHEgBEwOHAkBuRAHpFiFDhxwciNmlUAPAA4poKACb8m-fqEiwEydFlz4CAYQQZSFGvWfN2nNz8ghAeUIjScIgAvFSRlMFCImJIkQrKquqa2roohsao5nyWfNbg0PBIqBgASsaapl6IdaE4pgA8PgwurByUADSIYCAAtixqAHxBAkmi4tyRFACMTEoqahpaOvpGJkUlZbaVDrX1be5gnuTNZx1dfgS9nIPDY5PTIWERMjELMgBeyxKgmEc1SMnSKlMcHQQzg4Q2mgAhBYrHwMmB4SgKBAABZsQhmRABRAAWim7H+iHwyFxKAi5TsSDpbFMam+WigdLQ9IANjpwgAmQ4VezVKAtBoAMTArjYvN5TUlbU6dG6-jY-wGQ1G4xwU14M1BKROEtupEhiGhsMxCKyOBRxTRNlFVUcytMMrlCouVwoHtVvkYj0p2teeoNiVCl3CkV+4o9FsSxvmaTWVphultmU2jpKQA)

### 💻 Code

For the lazy, this is the same as the playground link ^
```ts
function testString(): `${string}bar` {
  return "foo"; // error as expected
}

function testStringConst(): `${string}bar` {
  const foo = `foo`
  return foo; // error as expected
}

function testRecord(): Record<`${string}bar`, number> {
  return {foo: 1} // error as expected
}

function testRecordConst(): Record<`${string}bar`, number> {
  const foo = {fooz: 1}
  return foo; // does not error!
}

// note: changed bar -> baz in the function header for these last 2
function testRecordFnCall(): Record<`${string}baz`, number> {
  return testRecord(); // does not error!
}

function testRecordFnCallConst(): Record<`${string}baz`, number> {
  const foo = testRecord();
  return foo; // does not error!
}

```

### 🙁 Actual behavior

I was seeing some cases where template literal type checking of keys of Records should have had an error but the compiler let it through anyway. This behavior is puzzling because returning an object literal correctly errors but wrapping in a const or function return does not.

### 🙂 Expected behavior

I expect the typechecker to correctly check keys of objects against Record-types whose keys are template literal types in all situations, and to correctly identify that 2 different Records whose keys are incompatible template literal types to be unassignable to each other. I realize that template literals are based on string unions, and putting a `${string}` inside a template literal type might be something that shouldn't be done, but I felt the behavior was inconsistent anyway.

**Comment by MartinJohns** [comment]
> This behavior is puzzling because returning an object literal correctly errors but wrapping in a const or function return does not.

The "excess property check" only kicks in for object literals, otherwise there's just a compatibility check. And as long as the object is not incompatible it will succeed, and additional properties are allowed.

This looks alright to me.

**Comment by jim-nomad** [comment]
Thank you for the quick reply, I agree that your explanation makes sense for my 3rd and 4th examples (where in the latter case, `foo` is inferred as `{fooz: number}` literally) but I don't think it covers the 5th and 6th examples; here is an additional example:

```
function fn1(): Record<`${string}bar`, number> {
  const foo: Record<"three", number> = {three: 3}
  return foo; // does not error!
}
function fn2(): Record<"one" | "two", number> {
  const foo: Record<"three", number> = {three: 3}
  return foo; // error
}
```

The way I see it, `"three"` is not assignable to either the template literal type nor the string union in `fn2` however one passes and one fails. What is it about the template literal that allows it to sneak by the compatibility check you spoke of?

**Comment by andrewbranch** [comment]
`Record` might be obscuring what’s happening here. 

```ts
type R1 = Record<`${string}bar`, number>; // { [index: `${string}bar`]: number }
type R2 = Record<"one" | "two", number>;  // { one: number, two: number }
```

These are quite different types. Because the key type of `R1` here is infinite, there are no required properties to speak of—all it says is that any keys whose names end in `bar` _must_ have values of type `number`. It does not say anything about the keys or values that do not match the pattern `` `${string}bar` ``. `R2`, on the other hand, immediately collapses to an object type with two required properties. Somewhat like `R1`, the presence of these properties do not preclude the possibility that there are _additional_ keys with names other than `one` or `two`, but _unlike_ `R1`, the properties `one` and `two` are required, and we cannot be sure that `Record<"three", number>` (which is just `{ three: number }`) has those keys.

**Comment by jim-nomad** [comment]
Thanks for taking a look, after reading your response (a few times hehe) I guess it makes sense...
I'm tempted to suggest something like:

```ts
type R3 = Record<`${string}bar`, number> & Record<string, never>; // doesn't work don't even try it
```

but I think it is too un-facile to consider seriously. /shrug

Thanks again for all your work on everyone's favorite language 💪
