### ISSUE TITLE
Error with Generic Enum

### ISSUE THREAD

**Issue by ducnguyen96** [microsoft/TypeScript#45957]
# Bug Report

### 🔎 Search Terms

Generics Enum Error

### 🕗 Version & Regression Information

- Tested on bunch of versions (`4.4.2`, `4.3.5`, `4.2.3`, `4.1.5`, `4.0.5`, `3.9.7`, `3.8.3`, `3.7.5`, `3.6.3`, `3.5.1`, `3.3.3`, `Nightly - 4.5.0-dev.20210910`) on playground all failed.
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQRSAHgA5z4AuoSAdgK4C2oA8vsvgMo0CGNJtgDeRUKADChQUgSgAvKABEMGTTnKANOKn8GMJABsjcxSpj7DJzTokBBAO78AljRcNUABX6QWjOiVlfmc3D1QALgpffwYabV1JOBYKUw1zVWTUpA0EgF8SGkgKFABVBmiYAGs5AB4AFQA+c3r6Mg0GBGwACg8AMwJQUoBKAG0AXV0AfiHdCNBW8g6u0AAlJH4EOAYjSHt8fF9a-sHSxunZiXn6gG5C4pR7Bj2Do6aWidAAHzWNrZ2XodIA1GnciEUSqAAIpMAiQHjGJAwGjUEHmMQSAAkHim1zay2wT0BR30kGaM3KlRqCBBn2uEzueTBEJQMLhCNMyOoAEkGOZONw+IJhJ8lowVkT9kDaqTzhIKRV+NU6gKCEKhJhGhM5hwuGqBBqGSR4AxMHQAI6w-DwxFc-DzNnWjlIlH4Wqq3gG4TNJQiJlES3s22ugB02L5SlGHvVwhDTlc7k8Pj8AS0usFXswIckVmMpgQ4zuQA)

### 💻 Code

```ts
export enum OrderStatus {
  Created = "created",
  Cancelled = "cancelled",
  AwaitingPayment = "awaiting:payment",
  Complete = "complete",
}

type Unpacked<T> = T extends (infer U)[]
  ? U
  : T extends ReadonlyArray<infer U>
  ? U
  : T;

type AnyArray<T> = T[] | ReadonlyArray<T>;

type QuerySelector<T> = {
  $in?: T extends AnyArray<any> ? Unpacked<T>[] : T[];
};

type QuerySelectorIn = OrderStatus[] extends AnyArray<any>
  ? Unpacked<OrderStatus>[]
  : OrderStatus[];

const querySelector: QuerySelector<OrderStatus> = {};
querySelector.$in = [OrderStatus.AwaitingPayment, OrderStatus.Cancelled];

```

### 🙁 Actual behavior

![2021-09-19_15-16_1](https://user-images.githubusercontent.com/47471616/133920857-fb1859d2-0608-4d8f-a436-be69a80ab5c4.png)

Type of `$in` must be `OrderStatus[]` but I got its wrong. I don't know why but `QuerySelectorIn` has right type but `$in` have not.

### 🙂 Expected behavior

![2021-09-19_15-16](https://user-images.githubusercontent.com/47471616/133920872-cb45fbff-54a4-4761-a8e2-ad9b76d12c7e.png)

Type of `$in` must be `OrderStatus[]` like `QuerySelectorIn`

**Comment by MartinJohns** [comment]
[Distributive Conditional Types](Distributive Conditional Types)

This seems more like a question than a bug report.

**Comment by ducnguyen96** [comment]
@MartinJohns 

![2021-09-19_22-16](https://user-images.githubusercontent.com/47471616/133932881-f60ca954-394a-48bf-9b0b-b7a3397821cf.png)
First `$in` has `WeirdType[]` type means `T extends AnyArray<any>` is falsy. But then
![2021-09-19_22-16_1](https://user-images.githubusercontent.com/47471616/133932885-b53f6e85-dee0-4d6d-96e4-22f1eacec8f3.png)
Somehow, after checking `T extends AnyArray<any>`, `T`  is not `OrderStatus` anymore.  If I remove the checking part, it works
![2021-09-19_22-17](https://user-images.githubusercontent.com/47471616/133932889-5e5acaa5-9f79-43e6-8d03-960640f622f3.png)

If this is not a bug please tell me how to code `$in?: T extends AnyArray<any> ? Unpacked<T>[] : T[]` part correctly.
Actually this code is a part of `mongoose`.

**Comment by FilipeBeck** [comment]
You need wrap `T` into `[]` to avoid _union distribution_.
```diff
type QuerySelector<T> = {
-  $in?: T extends AnyArray<any> ? Unpacked<T>[] : T[];
+  $in?: [T] extends [AnyArray<any>] ? Unpacked<T>[] : T[];
};
```

The `Unpacked<T>[]` is redundant too.
```typescript
type QuerySelector<T> = {
  $in?: [T] extends [AnyArray<any>] ? T : T[];
};
```

**Comment by MartinJohns** [comment]
@ducnguyen96 You didn't read the link I provided, did you? Filipe provided you the solution, which is mentioned in the provided documentation as well.

> If this is not a bug please tell me how to code `$in?: T extends AnyArray<any> ? Unpacked<T>[] : T[]` part correctly.

Just because you don't know how it's done correctly doesn't mean it's a bug. :-) You're just dealing with behaviour your don't understand, but don't try to line out what exactly is the bug, instead want to know how to achieve the desired result.

> Actually this code is a part of `mongoose`.

Terrible library. I always feel pain having to use it.

**Comment by ducnguyen96** [comment]
@MartinJohns 
Sorry my bad, clearly I don't understand enum  behavior here.
