### ISSUE TITLE
Shorter dot syntax to access enum values

### ISSUE THREAD

**Issue by FilipeBeck** [microsoft/TypeScript#45956]
# Suggestion

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow access to `enum` values without having to type the entire _path_ to the value. Any _subpath_ starting with dot is valid.

```typescript
namespace Geometry {
  export enum Shape {
    CIRCLE,
    SQUARE
  }
}

function setShape(shape: Geometry.Shape) {
  // ...
}

setShape(.CIRCLE)
// too
setShape(.Shape.SQUARE)
```

With unions, we have a compiler error when the _subpath_ is ambiguous.
```typescript
namespace GeometryA {
  export enum ShapeA {
    CIRCLE = 1,
    SQUARE = 2,
  }
}

namespace GeometryB {
  export enum ShapeB {
    CIRCLE = 'circle',
    SQUARE = 'square',
  }
}

function setShape(shape: GeometryA.ShapeA | GeometryB.ShapeB) {
  // ...
}

setShape(.CIRCLE) // Error. Is `1` or `'circle'`?
setShape(.ShapeA.CIRCLE) // OK
```

## 📃 Motivating Example

Sometimes, the _path_  is too long. I have this code in react:
```tsx
<Scene sampleRate={88200} latencyHint={ATOM.Scene.LatencyCategory.PLAYBACK}>
```
Besides having to import `ATOM`, the _path_ is too long. That way it would be better:

```tsx
<Scene sampleRate={88200} latencyHint={.PLAYBACK}>
```

This example would emit an `import` of `ATOM` at runtime.

**Comment by MartinJohns** [comment]
#40343

**Comment by FilipeBeck** [comment]
You're right. Updated

**Comment by jcalz** [comment]
This is also 
> non-ECMAScript syntax with JavaScript output

Requests of this sort tend to get declined.

Usually they'd say "if you want to see this, go to tc39 and get them to put it in JavaScript first".  But you're talking about `enum`, the epitome of non-ECMAScript syntax with JavaScript output, so I'm interested in seeing the wording of the response here. 👀

**Comment by fatcerberus** [comment]
My suspicion is that `enum` is just considered legacy baggage nowadays and, if it didn’t exist and had been requested today, would be declined with the same rationale as any other request for non-ES runtime features.

However, for *this* issue in particular, there’s another reason it’ll almost certainly be declined: it requires type-directed emit.  `.Circle` means something different depending on the type it’s being assigned to.  TS doesn’t do type-directed emit, it’s an explicit non-goal of the project.

**Comment by FilipeBeck** [comment]
Since `enum` is already a non-ECMAScript syntax, it's a shame not to be able to use such a practical and intuitive feature. Without it, its use becomes discouraging. If `enum` is a legacy feature, then it would be better to officially deprecate it and remove it in future releases in favor of _unions_.

**Comment by MartinJohns** [comment]
> If enum is a legacy feature, then it would be better to officially deprecate it and remove it in future releases in favor of unions.

This would also be against the design goals of TypeScript:

> Do not cause substantial breaking changes from TypeScript 1.0.

**Comment by FilipeBeck** [comment]
@MartinJohns This is not a _breaking change_. Any current code will compile without errors after this feature. This is a _minor_  change. Reinforcing: We're talking about `enum`, which is already a feature that breaks the rule

**Comment by MartinJohns** [comment]
Removing the `enum` feature would be a breaking change. Note that my statement was about the quote of yours, suggesting to remove the feature from TypeScript.

**Comment by FilipeBeck** [comment]
Ah, sorry. It is true

**Comment by FilipeBeck** [comment]
@MartinJohns Really, you argument in this comment makes a lot of sense: https://github.com/microsoft/TypeScript/issues/45968#issuecomment-924303794

But, as i said, `enum` already exists and is a exception. We can do a last improvement by adding this syntax.

**Comment by fatcerberus** [comment]
> We can do a last improvement by adding this syntax.

Except we can't because it requires type-directed emit, as noted in my comment above.  See Non-Goals here:
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals

Specifically # 5 on that list:
> [Don't] Add or rely on run-time type information in programs, *or emit different code based on the results of the type system*. Instead, encourage programming patterns that do not require run-time metadata.

**Comment by FilipeBeck** [comment]
The `enum` itself already does this:

TS:
```typescript
enum A {
  CASE1 = 'case1'
}

const a = A.CASE1
```
JS:
```javascript
"use strict";
var A;
(function (A) {
    A["CASE1"] = "case1";
})(A || (A = {}));
const a = A.CASE1;
```

As `const`:
```typescript
const enum A {
  CASE1 = 'case1'
}

const a = A.CASE1
```
JS:
```javascript
"use strict";
const a = "case1" /* CASE1 */;
```

That is, _it emits different code based on the results of the type system_

I don't see sense in __not be able to emit different code based on the results of the type system__ with a new syntax for a type that __emits different code based on the results of the type system__

**Comment by FilipeBeck** [comment]
The snippets above are generated by typescript: https://www.typescriptlang.org/play?#code/KYOwrgtgBAglDeBYAUFKBhGBlAogRigF4oByAYwEMBnYPElAXxRTIHsQqAXKCo2AOky48zZGw7dQkKACEEKNEPx9y1WvWRNkLdlygAjPjMHZ8KIA

**Comment by FilipeBeck** [comment]
I think this illustrates my point better:

https://user-images.githubusercontent.com/11150041/134590454-90758f2d-a619-4665-9912-1de8b38c9a9e.mp4

**Comment by andrewbranch** [comment]
FWIW I _love_ this feature of Swift, but yeah, sadly it’s a no-go for us. I have thought about trying to make completions let you type something like you suggested `latencyHint={.P/*cursor here*/ }` and triggering completions for the whole qualified enum member from the dangling `.` so you could accomplish the same feel as writing Swift, but haven’t had time to investigate it.

**Comment by tjjfvi** [comment]
> But, as i said, `enum` already exists and is a exception. We can do a last improvement by adding this syntax.

Perhaps this analogy will help:
> \> Feature Request: ...
> < That would require setting a building on fire, which we don't do
> \> But the building is already on fire, so it's ok
> < Well, yeah, that was before we stopped setting buildings on fire. We have to keep the flaming building because some people use it to cook their meals, but we're not setting any more buildings on fire.
> \> Ok, so I get that we don't set *new* buildings on fire, but if we flung some gasoline on the *existing* flaming building, it would be an *even better* fire
> < ...

**Comment by FilipeBeck** [comment]
![esco-fosforo](https://user-images.githubusercontent.com/11150041/135701670-a650c3ce-4886-445e-8583-b5e2a682874e.png)
