### ISSUE TITLE
Using the Linux kernel's Case-insensitive feature in Ext4

### ISSUE THREAD

**Issue by last-Programmer** [microsoft/TypeScript#45966]
It seems to be that it is possible to have case insensitive file system in linux

Reference : https://www.collabora.com/news-and-blog/blog/2020/08/27/using-the-linux-kernel-case-insensitive-feature-in-ext4/

I tried this and it does works. Tested in the terminal and we make the directory case insensitive.

But typescript compiler does not respect this. It is throwing up error when  import  statement case does not match with file exists on the disk. This should work as in windows and mac., where as typescript compiler is trying to look out for case sensitive file name.

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
