### ISSUE TITLE
TypeScript failing to narrow field types indexed w/ const assertions

### ISSUE THREAD

**Issue by bsuth** [microsoft/TypeScript#45965]
# Bug Report

### 🔎 Search Terms

const assertion
const narrow
assertion narrow

### 🕗 Version & Regression Information

First seen in 4.1.2, reproduced in 4.4.3 and 4.5.0-dev.20210919.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Type System Behavior", "Type Guards", "Things That Don't Work"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBFCm0BcMDeMC2BPAZgS3gBsATAfhTAFcMAjeAJxgF8YBeNJgbgFgAoUSLAHQAYgRJsYAcmz4ixKTACGEGMKg9efPDhgAKBNADa6sfIC6ASjR8Ya8BBCF4AOkIgA5gcRQTDqGYk5jAA1DAAjJaadsJOru5ehlAusuLEoRFRfExAA)

### 💻 Code

```ts
const test: { myfield?: number } = {};
const constField = 'myfield' as const;

if (test[constField]) {
  console.log(test[constField] + 1); // Object is possibly 'undefined'
  console.log(test.myfield + 1); // Object is possibly 'undefined'
}
```

### 🙁 Actual behavior

TypeScript is not able to narrow `test[constField]` from `undefined|number` to `number`

### 🙂 Expected behavior

TypeScript infers that `test[constField]` is simply `number` in the `if` block

**Comment by IllusionMH** [comment]
Looks like duplicate of #44899 and linked issues.

**Comment by easyrider** [comment]
This is also possibly a https://github.com/microsoft/TypeScript/issues/10530 duplicate - an issue that appears frequently since 2016, the solution was already proposed as a PR but was declined.

**Comment by bsuth** [comment]
indeed this seems to be a duplicate, closing in favor of #10530
