### ISSUE TITLE
Infer the type of import * as Foo from './Foo'

### ISSUE THREAD

**Issue by n0th1ng-else** [microsoft/TypeScript#45962]
# Bug Report

Why the typescript compiler can not figure out the type of the `Bar` variable from the `import * as Bar from './Bar'`?

### 🔎 Search Terms

`type of import all`,
`import * as`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://stackblitz.com/edit/typescript-9kpli9?file=Importer.ts)

### 💻 Code

```typescript
// Foo.ts
export interface Bar {
	test: boolean;
}
```

```typescript
// Importer.ts
import * as Foo from './Foo';

const VarWithError: {
  Bar: Foo.Bar;
} = Foo;
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/46719800/133944854-bf06b03f-ea60-41ea-ba27-076bad3ba48c.png)

In the meantime, the autocomplete work and I can use any exported value via `Foo.Bar`...
### 🙂 Expected behavior

Code compiles. Typescript compiler infers the type of the `Foo` variable correctly i.e. 

`Foo is { Bar: { test: boolean } }`

so the assignment is correct

**Comment by MartinJohns** [comment]
Why would the assignment be correct? Your module `Foo` does not export a **value** named `Bar`.

**Comment by FilipeBeck** [comment]
@n0th1ng-else `Bar` is a _type_. What you can do is something like this:
```typescript
import * as Foo from "./Foo";

type FooLike = {
  Bar: Foo.Bar;
}

function log(foo: typeof Foo) {
  // ...
}

const fooLike: FooLike = {
  Bar: {
    test: true
  }
}


log(fooLike) // No errors
```

**Comment by n0th1ng-else** [comment]
Okay let's modify the example.

```typescript
// Foo.ts
export const Bar = 42;
```

then
```typescript
import * as Foo from "./Foo";

type FooLike = {
    Bar: Foo.Bar; // <<-- TS2694: Namespace '"./Foo"' has no exported member 'Bar',
	Gun: 42 // Okay
}

const Bar = Foo.Bar; // Okay
```

The main question remains the same.
```
Why the typescript compiler can not figure out the type of the Bar variable from the import * as Bar from './Bar'?
```

**Comment by n0th1ng-else** [comment]
okay, I think it is related, but I need to do a step back to tell you where I am coming from.

My research started with this code [playground](https://stackblitz.com/edit/typescript-9kpli9?file=Importer.ts)

I tried to understand how the `export import Foo = Bar` work in general and then bumped into this

![image](https://user-images.githubusercontent.com/46719800/133978033-26af9309-2a3e-4415-ae89-6ed17b6ee971.png)

I dont understand why it works fine in case I import everything from the module. and causes type error
when I import some particular item

**Comment by fatcerberus** [comment]
Types are erased by the compiler and don’t exist at runtime.  Therefore, when you `import *` from some module, the type-only exports of that module won’t be part of the imported value, and thus aren’t part of the type of `import *` either.

**Comment by IllusionMH** [comment]
What is `export import`?
If you update them to `export type` then there are no issues and difference.
If you update them to `export const` then there will be issue for both (different codes, but reason is same there is no `Bar` in value namespace).
