### ISSUE TITLE
When specifying --jsx preserver and outfile with '.js' extension compiler should error

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#4597]
When you specify the following compiler options `--jsx preserve --outfile index.js` the compiler should give an error, since the expected output should be a `.jsx` file.

**Comment by DanielRosenwasser** [comment]
I'm not sure how consistent this is with the rest of the compiler - we don't give an error for `tsc foo.ts --outFile wargarbl.wav`.

**Comment by mhegazy** [comment]
that has been the strategy all the way, outFile/out is not checked. we trust you know what you are doing. if you say emit to `out.intermediate` then we will emit to `out.intermediate`
