### ISSUE TITLE
TSServer died unexpectedly more then 5 times  in big monorepo - Vscode

### ISSUE THREAD

**Issue by carlonoelle** [microsoft/TypeScript#45986]
# Bug Report

I have a big Monorepo (32 subpackages) using Yarn Workspaces (node_modules symlinking). The VSCode integrated Typescript Language server dies every few minutes, making it hard to use Typescript functionality. Error Message is:
Ts server dies unexpectedly more then 5 times in the last 5 minutes

### 🔎 Search Terms

TSServer died unexpectedly, tsserver crash, vscode ts server, monorepo, large

### 🕗 Version & Regression Information

currently using typescript 4.2.2, the problem started occuring once my project got bigger (subpackages added up)

### 💻 Code

I can provide the verbose ts server log, but would appreciate if it could not be posted publicly.

### 🙁 Actual behavior

Error Message is:
Ts server dies unexpectedly more then 5 times in the last 5 minutes

### 🙂 Expected behavior

it doesent crash, and i can use vscodes ts features like a charm

**Comment by andrewbranch** [comment]
4.2.2 is several versions old. Does it crash with the nightly? https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

**Comment by carlonoelle** [comment]
Hey, sorry totally forgot about this issue. It was fixed along the way by upgrading TS i think.
