### ISSUE TITLE
Documentation of unshift is incorrect

### ISSUE THREAD

**Issue by pjammula** [microsoft/TypeScript#45981]
# Bug Report

It's not functional issue, I am reporting documentation error.
Instead of explaining what unshift method does, it's JSDoc comments are same as of indexOf method.

### 🔎 Search Terms

unshift, jsdoc comments

### 🕗 Version & Regression Information

<!-- When did you start seeing this bug occur?
It's there for long time.

Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about documentation

### ⏯ Playground Link

NA

### 💻 Code

Following is snippet from lib.es5.t.ds:
```ts
unshift(...items: T[]): number;
    /**
     * Returns the index of the first occurrence of a value in an array, or -1 if it is not present.
     * @param searchElement The value to locate in the array.
     * @param fromIndex The array index at which to begin the search. If fromIndex is omitted, the search starts at index 0.
     */```

### 🙁 Actual behavior

Incorrect explanation of unshift method

### 🙂 Expected behavior

Update JSDoc comments to explain what unshift method does

**Comment by andrewbranch** [comment]
I don’t think so?

https://github.com/microsoft/TypeScript/blob/61d29393594f81fa5032b426c8bfcdbc8bd90c98/src/lib/es5.d.ts#L1335-L1339

<img width="828" alt="image" src="https://user-images.githubusercontent.com/3277153/134593692-5409b5d1-a7bb-4efa-9550-2cab352b7226.png">
