### ISSUE TITLE
Provide the ability to change assigned generic inside a class

### ISSUE THREAD

**Issue by radzserg** [microsoft/TypeScript#45992]
# Suggestion

Provide the ability to change assigned generic inside a class - `class Buzz<R>`

Currently, it's possible to change class generic only by creating a new object.

```typescript 

class Buzz<R extends Object> {
    public add<N extends Object>(newValue: N): Buzz<R & N> {
        return ({} as unknown) as Buzz<R & N>;
    }
}

let buzz = new Buzz();
let buzz2: Buzz<{ a: number }> = buzz.add({ a: 123 });
let buzz3: Buzz<{ a: number; b: string }> = buzz2.add({ b: "string" });
```

But there's no way to change R if we call a member function of a class. 

It's possible to make another workaround with `this` in a guard

```typescript 

class Buzz<R extends Object = {}> {
    public add<N extends Object>(newValue: N): this is Buzz<R & N> {
        return true;
    }
    public get<N extends keyof R>(name: N): R[N] {
        return ({} as unknown) as R[N];
    }
}

let buzz = new Buzz();
if (buzz.add({ a: 123 })) {
  let a: number = buzz.get("a")   // works fine
} else {
  let a: number = buzz.get("a") // TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.
}

```

but in this case we still need to use `if` condition that doesn't work

## 🔍 Search Terms

class generic 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

use `this as CurrentClass<NewGenericType>` syntax to allow changing assigned generic.

```typescript
class Buzz<R extends Object = {}> {
    public add<N extends Object>(newValue: N): this as Buzz<R & N> {
        // this.values.push(newValue);
    }
}

```

## 📃 Motivating Example

It allows using the OOP approach without a need to create new objects. 

## 💻 Use Cases

Live example. Dependency Injection container is getting new definitions. It is supposed to be a singleton in the program. 

```typescript 
const container = new DIContainer();

container.add({ key1: new Foo() });
container.add({ key2: new Bar() });
const value = container.get("key1");

// currently I can only do

let container = new DIContainer();
container = container.add({ key1: new Foo() });
container= container.add({ key2: new Bar() });
```

**Comment by MartinJohns** [comment]
This sounds **very much** like #41339. Finding that issue again was tough.

**Comment by radzserg** [comment]
Great, that's exactly what I was looking for. It was tough to find this in the docs. Thank you. Closing this one.
