### ISSUE TITLE
bug with anonymous classes in extends for interfaces

### ISSUE THREAD

**Issue by alexander-akait** [microsoft/TypeScript#46006]
# Bug Report

### 🔎 Search Terms

Nothing, found bug locally

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `extends` and `interface`
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

```ts
class Bar {
  #color: number;

  constructor() {
    this.#color = 1;
  }
}

interface Foo extends Bar {
  prop: number;
}

// error TS2420: Class 'Baz' incorrectly implements interface 'Foo'. Property '#color' is missing in type 'Baz' but required in type 'Foo'.
class Baz
  extends class {
    #color: number;

    constructor() {
      this.#color = 1;
    }
  }
  implements Foo
{
  prop: number;

  constructor() {
    super();

    this.prop = 1;
  }
}

class Baw extends Bar implements Foo {
  prop: number;

  constructor() {
    super();

    this.prop = 1;
  }
}
```

### 🙂 Expected behavior

No errors,

**Comment by MartinJohns** [comment]
Duplicate of #42660.

**Comment by alexander-akait** [comment]
@MartinJohns I understand idea of private fields, but why it works for regular classes, but if I modify it to anonymous it will not?

**Comment by alexander-akait** [comment]
Looks at second example:
`Bar` class

and

```js
extends class {
    #color: number;

    constructor() {
      this.#color = 1;
    }
  }
```
are same

**Comment by MartinJohns** [comment]
The `Baw` example works because it's extending `Bar`. Your `Baz` class is not extending `Bar`. The interface `Foo` refers to the private property `#color` of the class `Bar`.

**Comment by alexander-akait** [comment]
hm, got it

**Comment by MartinJohns** [comment]
Same reason why this example does not compile:

    class Bar {
        #color: number;

        constructor() {
            this.#color = 1;
        }
    }

    const Baw = class {
        #color: number;

        constructor() {
            this.#color = 1;
        }
    }

    const bar: Bar = new Baw();
