### ISSUE TITLE
use unknown as paramters types to implement overloading function

### ISSUE THREAD

**Issue by willzhanglala** [microsoft/TypeScript#46000]
Allow using unknown as the type of parameters to indicate that the implementing of the function don't add more signature to paremeters.  As following expamle, in old signature, the best signature of a overloading function allows (number, string) as parameter input, however, that throw errors.
With the new syntax, allowing unknown as the implementing function signature, compiler has chance to generate only 
(number, number):number  |  (string, string):string  signature of function.  So that it will give type error when you tries add(1, "2") 
and also can give you the determined return type of number when tries let c=add(1,2)

Old Syntax:
```
function add(a:number, b:number):number
function add(a:string, b:string):string
function add(a:number|string, b:number|string):number|string{
    if (typeof a === 'number' && typeof b=== 'string' )
        error()
    if (typeof a=== 'string'  && typeof b === 'number' )
        error()
    //...
}
```
Syntax:
```
function add(a:number, b:number):number
function add(a:string, b:string):string
function add(a:unknown, b:unknown):unknown{

}
```

**Comment by MartinJohns** [comment]
[Issue template for feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Feature_request.md)

**Comment by IllusionMH** [comment]
Not counting on missing template: not clear what is new in this proposal and now result exactly differs from current behavior?
In call sites only overload signatures are used already and implementation signature only used inside of implementation.

Code in second example is valid already and should have same behavior as code from old example at call site.

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
