### ISSUE TITLE
The paths option does not work when compiling in docker

### ISSUE THREAD

**Issue by jiankafei** [microsoft/TypeScript#46016]
# Bug Report

### 🕗 Version & Regression Information

Typescript Version: 4.4.2

Project Type: nodejs14

#### package.json
```json
{
  "name": "server",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "build-ts": "rimraf dist && npx tsc",
    "watch-ts": "npx tsc -w"
  },
  "devDependencies": {
    "@types/koa": "^2.13.4",
    "@types/koa-compress": "^4.0.3",
    "@types/koa-static": "^4.0.2",
    "@types/koa__router": "^8.0.8",
    "@types/mime": "^2.0.3",
    "@types/module-alias": "^2.0.1",
    "cross-env": "^7.0.3",
    "fs-extra": "^10.0.0",
    "nodemon": "^2.0.12",
    "rimraf": "^3.0.2",
    "typescript": "^4.4.2"
  },
  "dependencies": {
    "@koa/router": "^10.1.1",
    "ajv": "^8.6.2",
    "chalk": "^4.1.2",
    "dotenv": "^10.0.0",
    "koa": "^2.13.1",
    "koa-body": "^4.2.0",
    "koa-compress": "^5.1.0",
    "koa-static": "^5.0.0",
    "mime": "^2.5.2",
    "module-alias": "^2.2.2",
    "mongoose": "^6.0.5",
    "ora": "^5.4.1"
  },
  "_moduleAliases": {
    "@src": "dist"
  }
}

```

#### dockerfile 
```dockerfile
# server
FROM node:16-bullseye-slim
COPY package* yarn.lock /srv/tsapp/
WORKDIR /srv/tsapp
RUN yarn global add pm2 --registry=https://registry.npm.taobao.org \
    && yarn install --registry=https://registry.npm.taobao.org
COPY . .
RUN yarn build-ts

ENV NODE_ENV=development
# ENV NODE_ENV=production
EXPOSE 80 443 43554 8081
CMD [ "pm2-runtime", "start", "ecosystem.config.json" ]
```

#### tsconfig.json
```json
{
  "compilerOptions": {
      "target": "ES2020",
      "module": "commonjs",
      "lib": ["ES2020"],
      "allowJs": false,
      "sourceMap": true,
      "outDir": "dist",
      "rootDir": "src",
      "removeComments": false,
      "strict": true,
      "alwaysStrict": true,
      "noUnusedLocals": true,
      "moduleResolution": "node",
      "baseUrl": "./",
      "paths": {
        "@src/*": ["src/*"],
      },
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "skipLibCheck": true,
      "forceConsistentCasingInFileNames": true
  }
}
```

#### pm2.config.js
```js
module.exports = {
  apps : [{
    name: 'server',
    cwd: '.',
    script: './dist/server.js',
    watch: true,
    source_map_support: true,
    exec_mode: 'cluster',
    instances: 3,
    env: {
      NODE_ENV: 'development',
    },
    env_production: {
      NODE_ENV: 'production',
    },
  }],
};
```

When building a docker image, it shows that '@src /...' cannot be found.

### 🙁 Actual behavior

The paths option works in a non docker environment, but not in docker.

### 🙂 Expected behavior

The paths option works when compiling in docker.

**Comment by vBread** [comment]
You need to be more specific than just "doesn't work".

**Comment by MartinJohns** [comment]
How are you compiling? You run a yarn script, but don't say what it is.

**Comment by jiankafei** [comment]
I'll make up one when I have time.

**Comment by IllusionMH** [comment]
Are you using any bundler that supports this aliasing?
Because `tsc` won't use `"paths"` to replace `@src` with `src` in compiled code.

You should either use bundler that supports aliasing (e.g. webpack) and will perform transformation or use imports to files as they are located on in runtime.

**Comment by andrewbranch** [comment]
Never heard of pm2-runtime, can you produce an example that just builds with tsc?

**Comment by jiankafei** [comment]
@IllusionMH 
```txt
rimraf dist && npx tsc
src/controllers/event.ts(5,23): error TS2307: Cannot find module '@src/models/project' or its corresponding type declarations.
src/controllers/info.ts(6,23): error TS2307: Cannot find module '@src/models/project' or its corresponding type declarations.
src/controllers/project.ts(4,19): error TS2307: Cannot find module '@src/models/project' or its corresponding type declarations.
```
I just reported an error when compiling. I didn't start the service at all, and I deleted the CMD of starting the service, which is still the case.

Note that local compilation can succeed.

**Comment by kmiloangel** [comment]
> @IllusionMH @andrewbranch
> 
> ```
> rimraf dist && npx tsc
> src/controllers/event.ts(5,23): error TS2307: Cannot find module '@src/models/project' or its corresponding type declarations.
> src/controllers/info.ts(6,23): error TS2307: Cannot find module '@src/models/project' or its corresponding type declarations.
> src/controllers/project.ts(4,19): error TS2307: Cannot find module '@src/models/project' or its corresponding type declarations.
> 
> The command '/bin/sh -c yarn build-ts' returned a non-zero code: 2
> ```
> 
> I just reported an error when compiling. I didn't start the service at all, and I deleted the CMD of starting the service, which is still the case.
> 
> Note that local compilation can succeed.

did you fix it? I'm having the same issue

**Comment by linus-jansson** [comment]
@kmiloangel @jiankafei Any solutions to this problem? Having the same problem using Vite + Typescript in docker but its working locally.

**Comment by pthieu** [comment]
@jiankafei @kmiloangel @linus-jansson having the same issue, were any of you able to resolve?

**Comment by davidspura** [comment]
Same issue for me with Vite + Typescript, im also using vite-tsconfig-paths plugin. Fails in docker but builds locally.

**Comment by DiZiNnEs** [comment]
Gusy, somone fix the errors ?

I have in `package.json`:
`
{
  "name": "jd-oc",
  "version": "1.0.0",
  "description": "",
  "main": "",
  "scripts": {
    "start": "...",
    "start-bullmq": "...",
    "start-internal-jd-api": "...",
    "test": "jest",
    "build": "tsc --build && tsc-alias -p tsconfig.json && cp .env dist/ && cp -r fonts dist/",
    "build-windows": "tsc --build && tsc-alias -p tsconfig.json && copy /Y .env dist && xcopy /E /Y fonts dist\\\\fonts"
  },
  "author": "dizinnes",
  "license": "ISC",
  "dependencies": {
    "axios": "^1.5.0",
    "axios-cookiejar-support": "^4.0.7",
    "bullmq": "^3.12.0",
    "chartjs-node-canvas": "^4.1.6",
    "chartjs-plugin-datalabels": "^2.2.0",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    "cron": "^2.3.0",
    "currency-converter-lt": "^2.0.0",
    "dayjs": "^1.11.7",
    "dotenv": "^16.0.3",
    "exceljs": "^4.3.0",
    "express": "^4.18.2",
    "lodash": "^4.17.21",
    "pdfmake": "^0.2.7",
    "puppeteer": "^19.11.1",
    "qs": "^6.11.2",
    "tough-cookie": "^4.1.3"
  },
  "devDependencies": {
    "@swc/cli": "^0.1.62",
    "@swc/core": "^1.3.57",
    "@types/cron": "^2.0.1",
    "@types/jest": "^29.5.4",
    "@types/lodash": "^4.14.195",
    "@types/node": "^18.17.12",
    "@types/passport": "^1.0.12",
    "jest": "^29.6.4",
    "nodemon": "^3.0.1",
    "prettier": "2.8.8",
    "ts-jest": "^29.1.0",
    "ts-node": "^10.9.1",
    "tsc-alias": "^1.8.8",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.2.2"
  }
}
`

If I build on the local machine everything works, but if I use a Dockerfile and build and run images, I get an error with the path:
```
~/projects/jd-oc-parser$ docker logs 02cda827446c
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '@src/server/routes/routes'
Require stack:
- /app/dist/src/server/index.js
- /app/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/app/dist/src/server/index.js:10:34)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/dist/src/server/index.js', '/app/dist/index.js' ]
}

Node.js v18.18.2
```

my `Dockerfile`:
```
FROM node:18-slim

WORKDIR /app

COPY . /app

RUN ls -a

RUN npm ci
RUN npm run build
COPY dist /app/dist
RUN npm install pm2 -g
EXPOSE 8000
CMD ["node", "dist/index.js"]
```

**Comment by prkagrawal** [comment]
This still persists, or at-least I can't figure it out yet.

Anyone looking for a [reproduction](https://github.com/prkagrawal/animated-garbanzo/tree/path-issue).

In the [main branch](https://github.com/prkagrawal/animated-garbanzo/tree/main) it works fine after I remove using typescript path imports. Their is also a screenshot in root.

**Comment by smirji-finishline** [comment]
What is the solution for this, I have the same issue

**Comment by RyanCavanaugh** [comment]
Locking to prevent future "Me toos"

If you're encountering this problem or a similar one, please log a new issue with enough information for someone else to reproduce the problem. This should be in the form of a TypeScript Playground link, GitHub repo, StackBlitz, etc. -- we are not able to assist with problems that can't be reproduced except in your specific environment (unless you can describe how to recreate such an environment). Thanks!
