### ISSUE TITLE
Type predicates doesn't work while using call() and apply() function but work with bind() function.

### ISSUE THREAD

**Issue by LvChengbin** [microsoft/TypeScript#46015]
I am using a callback function, in a method of a class, which is using type predicates syntax, but it's not working while using `call()` or `apply()` function and it can work correctly while using `bind()`.

```ts
class Test<T> {

    add( value: T ) {}

    fn<S extends T>( predicate:( value: T, index: number ) => value is S ): any {
        const list = new Test<S>();
        const value: T = 1 as unknown as T;

        if( predicate.call( null, value, 1 ) ) list.add( value ); //  Argument of type 'T' is not assignable to parameter of type 'S'. 'S' could be instantiated with an arbitrary type which could be unrelated to 'T'.(2345)

        if( predicate( value, 1 ) ) list.add( value ); // ✅

        if( predicate.bind( null )( value, 1 ) ) list.add( value ); // ✅
    }
}
```

https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAuAeWA+aBvAUD6B0YAJsQBTQBuYIArvAFxzQCU2AvnodAGYB2KAMrR4ADyTw+xGBgoAHAE7xiAS2BgJDCtTqM4AGmgqpYpn1oBbAEbwFraAF5MO+kZjCWTMHwCe2fNyEwAD2fMjQICrhDtB88ADucIioguhkLADcAYHQIWFIVDT0TLCO0ACMRDC0fADWfMHxfFVwWTkEKjzySqrqEgB06iAgFObDhi7whpVsbJHI-STkhbqsbe2d3cpqGvDaRVMV9nNRSIuk+6uZ2YGb0IrbffD9VsbLYyCsl-TTxxGn52WkzWN047CAA

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
