### ISSUE TITLE
static type checking ES module exports

### ISSUE THREAD

**Issue by acfasj** [microsoft/TypeScript#46019]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a feature that can static type checking ES module exports

## 📃 Motivating Example

it may looks like
```
// file.ts
export const x = 4
export const y = 'whatever'
export const foo = () => 2

// the interface describes the what file.ts  exports
export interface module {
    x: 4
    y: string
    foo: () => number
}
```

## 💻 Use Cases

Actually I asked a question on [stackoverflow](https://stackoverflow.com/questions/69297129/typescript-interface-static-type-checking-es-module-export), and not really konw what the sugar syntax looks like if the the feature could be implemented.

```
// file.ts
export const x = 4
export const y = 'whatever'
export const foo = () => 2

// the interface describes the what the module exports
interface Module {
    x: 4
    y: string
    foo: () => number
}
```
I want the exports in file.ts satisfy the interface Module, and typescript can tell me that I export right or not

**Comment by MartinJohns** [comment]
Duplicate of #38511.

**Comment by acfasj** [comment]
closed since duplicated
