### ISSUE TITLE
# Bug Report

### ISSUE THREAD

**Issue by fc01** [microsoft/TypeScript#46018]
# Bug Report
```ts
// ?????  TypeScript 4.4.2

type Index<T, K> = K extends keyof T ? T[K] : '????'
type Data = ['a', 'b']

//  bug
//  "a" | "b"
type A1 = Index<Data, -12>
type A2 = Index<Data, -12.34>

//  bug
//  undefined
type B1 = Index<Data, 12>
type B2 = Index<Data, 12.34>

//  bug
//  "�"
type C1 = '👾23' extends `${infer R}${any}` ? R : never

```

[Playground](https://www.typescriptlang.org/play?#code/PTAEH5M1QFQTwA4FMDKBjATgS0QF1ABYA6EgJgFgAoavJZUASQDsATZADwB5YAaUANIA+UAF5BoTnmRsAzqADWyeAHsAZnAhwA2gIC6oAFygA5FHAna9UABEAhnjtjQ2k3ZP8TAIxN7q1EBgvAFcAcwCwUAAiOyjQAB9oryirFFAAQQBGZxZ2bntHfgBaTLIhVIZ0shy2Ti4Cu2LS4gBmQnKaKkDQEPCuyODatWxmZFYK0AAhbPFcuob+Uo66NMnq2dr8h0bQZraOiKCww+jAX-+UqhWGAGEZ00BeDcA-HbIWk0kOaTlQAAMAEgBvEZqZCYUAAJQAvgC7Mx4BDvlowUZQKMAG4goA)

**Comment by MartinJohns** [comment]
[Issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md)

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
