### ISSUE TITLE
Compiled variable name not match `import` name

### ISSUE THREAD

**Issue by wang-prtimes** [Microsoft/TypeScript#4601]
```ts
import J from 'jquery';

J('body').css('background', 'yellow');
```

comes out this...
```js
var jquery_1 = require('jquery');
jquery_1["default"]('body').css('background', 'yellow');
```

Why didn't it just use 'J' instead of 'jquery_1'!?

**Comment by kitsonk** [comment]
It is as designed because you are trying to import the default export of a module and the compiler is trying to do it in a way it knows won't cause it runtime problems, but I think what you really want is this:

```typescript
import * as J from 'jquery';

J('body).css('background', 'yellow');
```

That should emit as:
```js
var J = require('jquery');
J('body').css('background', 'yellow');
```
