### ISSUE TITLE
Should that be ts(2454)?

### ISSUE THREAD

**Issue by zhangenming** [microsoft/TypeScript#46017]
![image](https://user-images.githubusercontent.com/21235555/134463424-b1332fe6-50bb-400f-93db-e6304e443c1c.png)

```ts
  ;(function f1() {
    value // Variable 'value' is used before being assigned, work as expect
  })()

  function f2() {
    value // here, no hint
  }
  f2()

  const value = 1
```
### 🙁 Actual behavior

did not hint

### 🙂 Expected behavior

has a hint

**Comment by MartinJohns** [comment]
Most likely falls into the realm of #9998.

**Comment by zhangenming** [comment]
The wonder is f1 work well...

**Comment by fatcerberus** [comment]
`f1` shows the error because IIFEs are special-cased in control-flow analysis.  The compiler knows that 1) the IIFE will run immediately and 2) only run once, and so treats it the same as code written inline.  `f2` falls into the realm of #9998, as mentioned by @MartinJohns.
