### ISSUE TITLE
Type inference when using array destructuring assignment fails to catch undefined values when the array is shorter than the destructure expression

### ISSUE THREAD

**Issue by mturley** [microsoft/TypeScript#46026]
# Bug Report

### 🔎 Search Terms

array destructure assignment inference rest undefined
(found semi-related https://github.com/microsoft/TypeScript/issues/21519)

### 🕗 Version & Regression Information

Found in version 4.0.0, reproduced in nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210910#code/MYewdgzgLgBAhgJwQLhmArgWwEYFMEDaAujALwzEDcAUNQPR0wBmII8YAJjNovArtxBQAFjACWYJvn5cobPDBBMYUAJ4AHARhz4ANN3SwRuVTAjCQ6ADZcFACm14EMAD4x0nXEwm4OASgA6alBIWAIWEH0eBBJyRAQaekYAZThMAWF8XCi4AC9xCHg0LCcDWHNLG24BBxL8V3dPbzBfQJh+aAKYUCRcYCgrUwkpXq44Qsd8YiCQzoIeXP0A5Y6oWL4E2lmQK1wAqxAAczsAb2ZWHIQcxfbcToBfP0oYBnPI7l44Tg-8xAEPDheHxcOwAQj8W3AnTgHC45DscFQkyu3CRdQQfjIAD4igBqbiJV4AFWEYkKFWstgEXxg0hAzisYgA1gIAEQAQQQhywuDAsCUKg0AgA5ACgS0uG5kcKumAhPAIBAxIcwHBsLsVGx1Ig0rgoPUBWpNDBhdLWUFXgBJUK4GHiWCgTDqMS7QoAdzEIjMWHEkmkvk11SKyKihl9zDg-XtXQAcnAYzMoeUfXFYXYIvoAExPYJQnZ7A7HCBYJ5AA)

### 💻 Code

```ts
const arr: number[] = [];

// foo and bar are both inferred to be of type number, but they should be (number | undefined).
const [foo, bar] = arr;

// Same here, baz is a number but should be (number | undefined). rest is correctly inferred as number[].
const [baz, ...rest] = arr;

console.log({ foo, bar, baz, rest }); // foo, bar and baz are undefined (!)

const add = (a: number, b: number) => a + b;

// This should be an error like "Argument of type 'undefined | number' is not assignable to parameter of type 'number'".
// Instead it compiles with sum inferred to be a number, but in fact it is NaN.
const sum = add(foo, 2);
console.log(sum);
```

### 🙁 Actual behavior

When destructuring an array, if the number of declared variables is longer than the length of the array, the extra ones will be undefined. However, TypeScript always infers the type of these variables to be defined. This can lead to uncaught errors when destructuring arrays that can be empty. Passing these destructured values to functions that require defined parameters will cause errors at run time that the compiler could easily catch.

### 🙂 Expected behavior

I would expect the inferred type of these destructured variables to be `T | undefined` where the type of the array is `T[]`.

**Comment by MartinJohns** [comment]
This is working as intended. When you enable `noUncheckedIndexedAccess` you get `number | undefined`.

**Comment by mturley** [comment]
Ah! Oops, thanks.
