### ISSUE TITLE
High tsserver memory use

### ISSUE THREAD

**Issue by mattpallissard** [microsoft/TypeScript#46028]
# Bug Report

In some of our medium sized projects (a handful of files at a few hundred lines each, mostly in the 15-20 or so dependency range)  I've noticed tsserver memory usage hitting nearly 1GB.

There were a few other issues that seemed related, but they were all closed due to lack of reproducibility. 

### 🔎 Search Terms

high memory usage consumption leak

### 🕗 Version & Regression Information
typescript/tsserver version 4.4.3
node version: v16.9.1

I've noticed this for several months, since I started using typescript actually, I haven't taken the time to reproduce it until now. 

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about tsserver memory usage

### ⏯ Playground Link

Not applicable

### 💻 Code

**note** all the memory usage below is for tsserver itself.  No editors, lsp-clients, or anything else.

```
~ npm install typescript
~ touch index.ts
```
boxing this in a transient systemd unit, shows that the memory usage peaks at ~200M on an empty file.
```
  Transient: yes
     Active: active (running) since Thu 2021-09-23 10:01:38 PDT; 12s ago
         IO: 0B read, 0B written
      Tasks: 18 (limit: 9363)
     Memory: 188.3M (high: 1.0G max: 1.0G swap max: 10.0M available: 835.6M)
        CPU: 3.479s
```

again, from a fresh directory adding an additional package moves memory usage up to 383M
```
~ npm install typescript @cdktf/provider-aws
~ touch index.ts #(open empty file)
```
```
  Transient: yes
     Active: active (running) since Thu 2021-09-23 10:03:53 PDT; 18s ago
         IO: 0B read, 0B written
      Tasks: 18 (limit: 9363)
     Memory: 383.4M (high: 1.0G max: 1.0G swap max: 10.0M available: 640.5M)
        CPU: 9.162s
 ```

But the entire directory of node_modules is less than 150M.
```
~ du -sh node_modules
156M    node_modules
```

I did a quick strace on the processes thinking that maybe the entire directory was being enumerated and read into memory, but that did not seem to be the case.

188M sitting idle feels like a lot to begin with, on top of that the memory usage appears to increase at a rate greater than sizeof(node_modules).

This seems like an awful lot of memory usage.

### 🙁 Actual behavior
Memory usage is really high for no apparent reason.

### 🙂 Expected behavior
Lower memory usage in general.

**Comment by andrewbranch** [comment]
I see 131MB for a small project with a fairly hefty node_modules. VS Code's extension host process is at 328MB—sure you’re not looking at that? VS Code has a built-in process explorer that’s helpful for inspecting. But if you’re not having a specific performance problem, there’s nothing we can do here.

**Comment by mattpallissard** [comment]
This isn't the vscode extension.  The measurements are of the node process running tsserver itself.

As an aside, I use neovim to start tsserver.

**Comment by mattpallissard** [comment]
```
 while read pid; do
        cat /proc/$pid/cmdline \
                |tr '\0' ' ' \
                | awk '{print $3}'
        grep ^Rss: /proc/$pid/smaps_rollup
done < <(ps -o comm,pid -u matt | grep node | awk '{print $2}')

/home/matt/usr/venvs/yarn/node_modules/.bin/typescript-language-server
Rss:               50296 kB
/home/matt/work/scratch/test/node_modules/typescript/bin/tsserver
Rss:              351928 kB
--globalTypingsCacheLocation
Rss:               69696 kB

```

**Comment by mattpallissard** [comment]
Here is another example.  The memory growth appears to be a function of the code size.  it's at least size*2
Any chance this could be re-opened?  It's clearly tsserver.  And it's clearly sub-optimal. 

```
~  du -sh src node_modules
14M     src
334M    node_modules
```
```
while read pid; do
        cat /proc/$pid/cmdline \
                |tr '\0' ' ' \
                | awk '{print $2}'
        grep ^Rss: /proc/$pid/smaps_rollup
done < <(ps -o comm,pid -u matt | grep node | awk '{print $2}')
/home/matt/usr/venvs/yarn/node_modules/.bin/typescript-language-server
Rss:               49116 kB
/home/matt/work/s/[snip]/node_modules/typescript/bin/tsserver
Rss:              828200 kB
/home/matt/work/s/[snip]/node_modules/typescript/lib/typingsInstaller.js
Rss:               67996 kB

```

**Comment by aromeronavia** [comment]
@mattpallissard I'm having the EXACT same issue as you, adding packages like `aws-sdk` which are 80MB of size adds **400MB** to my project LSP. Do you happen to have found a workaround to this?

**Comment by aromeronavia** [comment]
Omg it's been 2 years since this hahaha

**Comment by MaymoonaAlBoloshi** [comment]
@aromeronavia any luck?

**Comment by saumitra-txt** [comment]
any update?
