### ISSUE TITLE
For-in loop does not properly work on a `Partial<Record<...>>`

### ISSUE THREAD

**Issue by derolf** [microsoft/TypeScript#46023]
The following code turns some keys into numbers:

```TypeScript
export type Dict<K extends keyof any, T> = Partial<Record<K, T>>;

function numberized(obj: Dict<string, string>, keys: string[]): Dict<string, string | number> {
  const result: Dict<string, string | number> = {};
  for (const key in obj) {
    const value = obj[key];
    result[key] = keys.includes(key) ? parseFloat(value) : value;
  }
  return result;
}
```

The compiler complains with:

```
Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2345)
const value: string | undefined
```

However, from the construct 

```TypeScript
  for (const key in obj) {
    const value = obj[key];
```

the compiler should know that `value` can't be undefined.

**Comment by MartinJohns** [comment]
[Issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md)

---

> the compiler should know that `value` can't be undefined.

But this is not true:

    numberized({ 'a': undefined }, ['a'])

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions completely, follow them, and then fill in all the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by derolf** [comment]
> [Issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md)
> 
> > the compiler should know that `value` can't be undefined.
> 
> But this is not true:
> 
> ```
> numberized({ 'a': undefined }, ['a'])
> ```
> 
> Also note that object types are not sealed.

@MartinJohns shouldn’t exactOptionalPropertyTypes disallow undefined?
