### ISSUE TITLE
lib Update Request: RegExp `compile` method (lib.es5.d.ts)

### ISSUE THREAD

**Issue by kt3k** [microsoft/TypeScript#46030]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

RegExp interface has `compile` method of the following definition:

```
compile(): this;
```

But `compile` is acutally the same as RegExp constructor. So it should have the following definition:

```
compile(pattern: string, flags?: string): this;
```

## Sample Code

```ts
/foo/.compile(); // no type error, but now regexp becomes empty, a meaningless usage
/foo/.compile("bar"); // has type error, but this is a normal usage of compile method
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/compile

While this is non standard extension of RegExp, this is documented in Annex B of ES Spec (browsers probably won't remove this), and all major browsers still implement this feature. So I think it's meaningful to fix this type.

**Comment by andrewbranch** [comment]
We automatically remove deprecated/non-standard methods. You’re welcome to add it back to your program with global augmentation.

**Comment by kt3k** [comment]
I'm ok with the removal of this method from `lib.es5.d.ts`. My problem is that the current type definition is wrong one and it's been causing confusion.

> We automatically remove deprecated/non-standard methods.

Does that removal happen anytime soon? This item seems existing for a long time

**Comment by andrewbranch** [comment]
Sorry, I misread the issue and thought you were saying `compile` was missing, not wrong. Also, in terms of removing non-standard things, I was thinking about the DOM, not es5 libs. Sorry, it’s been a long day 😅

**Comment by andrewbranch** [comment]
This does seem flat out wrong, and I think we’d be open to a PR despite it being deprecated.

**Comment by kt3k** [comment]
Thanks! I'll send a PR
