### ISSUE TITLE
How to add and enable the "Convert named imports to namespace imports" refactor action?

### ISSUE THREAD

**Issue by mceachen** [microsoft/TypeScript#46034]
# Bug Report

### 🕗 Version & Regression Information

When trying to patch up a codebase to deal with [unbound named imports](https://github.com/microsoft/TypeScript/issues/46027#issuecomment-926014259), I found that the "Convert named imports to namespace imports" refactor action was missing  in vscode.

- This is not a crash
- This is a new refactor action, afaik, so I don't know if/when it changed between versions
- This is the behavior in every version I tried. I couldn't find any references to why this refactor would be disabled.
- I tried this with TS 4.3, 4.4, and 4.5.0-dev.20210923 on stable and insider releases of vscode on Ubuntu 20.04.3

With 4.3:
![image](https://user-images.githubusercontent.com/216377/134577059-ee396bec-38f0-44fa-a2a4-9729a4530feb.png)

With typescript@next:
![image](https://user-images.githubusercontent.com/216377/134576869-57dbf24a-8ec7-4b2f-a3d5-d943db9d66f2.png)

### 💻 Code

Tested with https://github.com/mceachen/ts44-event-typeerror

### 🙁 Actual behavior

The refactor action doesn't exist.

### 🙂 Expected behavior

I want this: https://github.com/microsoft/TypeScript/issues/46027#issuecomment-926026177

**Comment by andrewbranch** [comment]
This consistently works for me on macOS. @orta @elibarzilay or @sandersn would any of you be able to attempt a repro on Linux?

**Comment by mceachen** [comment]
@andrewbranch thanks for the update. I tried on my macOS box, with viscose version: 1.60.2 (Universal) and got this:

<img width="409" alt="Screen Shot 2021-09-23 at 6 06 48 PM" src="https://user-images.githubusercontent.com/216377/134603181-d543f89f-b77c-45ae-941d-2d649139d581.png">

**Comment by mceachen** [comment]
Ah: I didn't remember I'd used vscode on that box before, and there were extensions hiding in `~/.vscode`. I deleted the prior configs, and _behold_, the refactoring shows up!

But... it turns out that this refactoring doesn't help solve #46027 at all: it just switches between

```
import { addListener } from "process";
```
and
```
import * as process from "process";
```
both of which fail with the same error due to invoking the unbound method.

Should I open _yet another_ issue to solve that?

**Comment by andrewbranch** [comment]
😞 Yes please, thank you @mceachen
