### ISSUE TITLE
Cast to derived class is invalid even after checking the type

### ISSUE THREAD

**Issue by DavidRigglemanININ** [Microsoft/TypeScript#4605]
The following code doesn't compile even though I would expect it to. Inside the if statement, we know that the greeter is a ChildGreeter, but we are not allowed to cast to it for some reason. 

```
class Greeter {
   greet() { console.log("Hi"); }
}

class ChildGreeter extends Greeter {
	greetChild() { console.log("Hi child"); }
}

function greet<T extends Greeter>(greeter: T) {
	if(greeter instanceof ChildGreeter){
		// the following cast is invalid
		var childGreeter = <ChildGreeter>greeter;
	}
}
```

**Comment by DavidRigglemanININ** [comment]
The workaround is to do a cast of <ChildGreet><Object> greeter, but this shouldn't be necessary

**Comment by xLama** [comment]
It does not work either:

```
class Greeter {
   greet() { console.log("Hi"); }
}

class ChildGreeter extends Greeter {
    greetChild() { console.log("Hi child"); }
}

function isChildGreeter(a: Greeter): a is ChildGreeter {
	return a instanceof ChildGreeter;
	
}

function greet<T extends Greeter>(greeter: T) {
    if(isChildGreeter(greeter)){
		var childGreeter : ChildGreeter = greeter;
	}
}
```

**Comment by falsandtru** [comment]
Generic type `T` is not extended from `ChildGreeter` .

```ts
- function greet<T extends Greeter>(greeter: T) {
+ function greet<T extends ChildGreeter>(greeter: T) {
```

**Comment by mhegazy** [comment]
As @falsandtru mentioned, a value of type `T` is not guarantteed to be `ChildGreeter`. consider this:

```ts
class AnotherChildGreeter extends Greeter {
    NotGreetChild() { console.log("Hi another child"); }
}
```

You can either use `ChildGreeter` as your constraint, or cast to `any`.

**Comment by DavidRigglemanININ** [comment]
I'm not sure I fully understand. I know T is not guaranteed to be ChildGreeter, but it can be, right? Are you saying even if I checked that T is an instance of ChildGreeter, it may not actually be an instance of ChildGreeter?

**Comment by mhegazy** [comment]
it is not safe to assume that `T` is assignment compatible with `ChildGreeter` nor that `ChildGreeter` is assignment compatible with `T`.

```ts
var t : T;
var childGreeter: ChildGreeter;

t = childGreeter;  //  Not true, T might be of type AnotherChildGreeter, and would be missing NotGreetChild method if the assignment was allowed
childGreeter = t;  // Not true either, if T is AnotherChildGreeter, childGreeeter is now missing greetChild method if the assignment was allowed
```

This is basically what a cast operator does, it checks that the conversion is correct in at least one way, either up casting to a base type or down casting to a more specialized type; but you can not do it across. so:

```ts
// valid casts
var g = <Greeter> childGreeter; // up cast
var c = <ChildGreeter> g;  // down cast

// invalid cast
var x = <number> "string";  // Error: Neither type `string` nor type `number` is assignable to the other
```

Again, to work around this, you need to cast twice, once to a common base type, and then down to your more specialized type:
```ts
var child = <ChildGreeter><Greeter> t; // OK
```

But the question here, is why do you have a generic function, that declares a constraint on a base type has any knowledge about a specialized version of it. Either this function should not be generic, or it should have a different constraint.

**Comment by RaphiStein** [comment]
Personally I was having this issue when trying to cast a variable onto itself, for example

`mycustomobj = <CastToThis> mycustomobj;`

I solved it by simply creating a new var

`let newcustomobj = <CastToThis> mycustomobj`
