### ISSUE TITLE
Regression onicecandidateerror in TS4.4

### ISSUE THREAD

**Issue by jolting** [microsoft/TypeScript#46054]
onicecandidateerror should have a RTCPeerConnectionIceErrorEvent argument.

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidateerror

RTCPeerConnectionIceErrorEvent was removed here https://github.com/microsoft/TypeScript/commit/9d443b76aac0832d7f3c890441264d39307fe31a
```
    onicecandidateerror: ((this: RTCPeerConnection, ev: RTCPeerConnectionIceErrorEvent) => any) | null;
```

onicecandidateerror was readded in this merge with the incorrect type here https://github.com/microsoft/TypeScript/commit/eb1e5664447b47850370f28d8f7237cb5fc03ed1
```
    onicecandidateerror: ((this: RTCPeerConnection, ev: Event) => any) | null;
```

Currently in TS4.4 if I do something like this.
```
    peerConnection.onicecandidateerror = (errorEvent: RTCPeerConnectionIceErrorEvent) => {}
```
I get
```
     TS2322: Type '(errorEvent: RTCPeerConnectionIceErrorEvent) => void' is not assignable to type '(this: RTCPeerConnection, ev: Event) => any'.
  Types of parameters 'errorEvent' and 'ev' are incompatible.
```

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
