### ISSUE TITLE
Failed to infer types of initialized variables on async control flow

### ISSUE THREAD

**Issue by cometkim** [microsoft/TypeScript#46057]
# Bug Report

### 🔎 Search Terms

- async, await, Promise
- implicitly has type 'any'

### 🕗 Version & Regression Information

I think this is from a very early version (at least 3.3). But I couldn't found reported issues. Please let me know if it's a duplicate

### ⏯ Playground Link

[link](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210925#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMQMBJDEAWwGcAKMZGKnGALnioxi1QPgB94qZBAgBKNhy48A2gF0A3AChFoSLAQp02PIWJlKVAIJUAnujoMmrdp268BQkePgAFGDgpYqIADyS7cgB8SopQpuhIaJi4+CAw7jA0ovAA3orwGfAQxPD0jMwStjz8gsIQ8AC8pSLpmdkY8Fjk1IVSBHKV8HIhmfAA7gAWWNnwNE0GAHTZPBgD8D7wAIwADMvJab299bkMcKgNVVB9UE26pM1G4WAW+TCiSpt1OaggAB4YAMKWzJ15exgTKgQLBgEA0AC0i1E0mWsn4DjKD0ejUQowAhC93l9butasjMgAjOBQADWSMeAF88Zs8lZOpjPt8YOT4FSqYpNNEdDgSYskqlqdtaQUbG0So5ylUJYKcuMWqKAnCqt1lL1BsMEGMLlMQDM5gsVmsBfihbtdQczvpqDcrPdqVtnm9Gbdfmb9oDgaCIVCYXC+AiRCzelhUTQMU7sbbjfjCcSyfbMlT8cKYPSI0yWWzlGEzGBIloYvAeQAmfkbJ4NFOtOzisr0soyhpyqjVmRKroKVWZdUjLWTaYEWbzJarXEmnJ-c2dI4nBpEc4GYy5m3MO3jhoMyM-KqT91AkFgyHQ2Hw6oQIOZEPozdMscxjJEkCki8ZJPIgD0752Lql6dumcUdkcwiTltHwHkAGYy0bb8rFbewz3rGoHSbC54I6ZVO2pHtNWbHU9WHQ070eU14inQ5jlOecrUuZcUzXZFthvH9v3+D0D29Y8-QDc8EwyK8w2YqNy3vR9nz41kJJTNMsSZeAwgVYoeIAikgA)

### 🙁 Actual behavior

TypeScript failed to infer the correct type of initialized variable definitions before the assignment.

![image](https://user-images.githubusercontent.com/9696352/134777333-d1d455b6-1aa8-4aea-acf4-291f9bc9372a.png)

```
'current' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)
```

And with a few modifications (removing the `await` keyword, removing the assignment, matching the assignment type), it works as expected.

### 🙂 Expected behavior

It should pass type checking

**Comment by MartinJohns** [comment]
Duplicate of #43047. Used search terms: same as you.

**Comment by cometkim** [comment]
you are right. It seems to be the same issue, I'll close this and move on to that.
