### ISSUE TITLE
Default watch options not working as expected — steady-state CPU usage

### ISSUE THREAD

**Issue by srmagura** [microsoft/TypeScript#46069]
# Bug Report

### 🔎 Search Terms

watch, watchOptions, TSC_WATCHFILE

### 🕗 Version & Regression Information

I don't think this is a new issue. The behavior is the same between the latest official release (4.4.3) and the latest dev release (4.5.0-dev.20210926).

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _watchOptions_

### ⏯ Playground Link

N/A

### 💻 Code

Tested on a medium TypeScript codebase that contains ~1110 TypeScript files and an average amount of `node_modules`.

### 🙁 Actual behavior

This issue concerns steady-state CPU usage when running `tsc --watch`. When I say "steady-state", I mean the CPU usage after the initial compilation is done and TypeScript is just watching files, none of which are changing.

**Case 1**

`TSC_WATCHFILE` environment variable not set. `tsconfig.json` has
```json
"watchOptions": {
    "fallbackPolling": "dynamicPriority"
}
```

Steady-state CPU usage: ~6.5%

**Case 2**

`TSC_WATCHFILE` environment variable not set. `tsconfig.json` has
```json
"watchOptions": {
    "watchFile": "useFsEvents",
    "watchDirectory": "useFsEvents",
    "fallbackPolling": "dynamicPriority"
}
```

Steady-state CPU usage: ~0.1%

**Case 3**

`TSC_WATCHFILE = UseFsEventsWithFallbackDynamicPolling`. No `watchOptions` in `tsconfig.json`.

Steady-state CPU usage: ~0.1%

### 🙂 Expected behavior

According to [the TypeScript 3.8 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#better-directory-watching-on-linux-and-watchoptions), the defaults for `watchFile` and `watchDirectory` are `useFsEvents`. Unless these defaults were changed in a later TypeScript version, my "Case 1" and "Case 2" should have exhibited the same CPU usage.

It makes sense that "Case 2" and "Case 3" had the same CPU usage, since the environment variable is just a different way of setting the same options.

Overall, the desired behavior is that `tsc --watch` uses as little CPU as possible while still doing a good job of watching files **using the default watchOptions**.

### 🔗 Related links

- [TypeScript Handbook: Configuring Watch](https://www.typescriptlang.org/docs/handbook/configuring-watch.html)  
- [2019 Johnny Reilly blog post on TSC_WATCHFILE](https://blog.johnnyreilly.com/2019/05/23/typescript-and-high-cpu-usage-watch/)  
- [2019 issue posted by Johnny Reilly about watch performance](https://github.com/microsoft/TypeScript/issues/31048)  

### 💻 Test environment
Windows 10
Node 14.17.6
AMD Ryzen 5 2600 Six-Core Processor
PowerShell 7.1.4

**Comment by andrewbranch** [comment]
@amcasey know anything about this?

**Comment by amcasey** [comment]
@andrewbranch I manage to misspeak every time I speculate about file watchers. :wink:

It seems reasonably clear that Case 1 is using polling, but I have no idea whether that's by design - I don't know either the default or whether heuristics are used to adapt to the environment (though I would certainly expect FS events to be used on Windows without an explicit override).

**Comment by sheetalkamat** [comment]
Watch file is default to polling for correctness .. so your case 1 and 2 are not same ..

**Comment by srmagura** [comment]
Okay, so it's just that the TS 3.8 release notes were wrong?

I do wonder if FS events would be a better default than polling but that's up to you all.

**Comment by sheetalkamat** [comment]
Option 1 and options 2 are not same since option1 uises polling for file watching which will be cpu intensive
