### ISSUE TITLE
enum type error

### ISSUE THREAD

**Issue by mengxinssfd** [microsoft/TypeScript#46065]
# Bug Report

### 🔎 Search Terms
enum depends on another enum

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ___4.3.5___ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____enum_____
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
enum A {
  a = 0,
  b = 1,
  c = 2,
}
enum B {
  a = A.a,
  b = A.b,
}
const a: Record<A, string> = {
  [A.a]: '',
  [A.b]: '',
  [A.c]: '',
  3: '', // error
};
const b: Record<B, string> = {
  [B.a]: '',
  [B.b]: '',
  3: '', // expect type error but no
  str: '', // error
};
// the type of b is equal to the type of c
const c: Record<number, string> = {
  [B.a]: '',
  [B.b]: '',
  3: '',
  str: '', // error
};
```

### 🙁 Actual behavior
no type error,  enum B seems to become number type in Record<B, string>

### 🙂 Expected behavior
expect the attribute 3 of object b to report an type error, expect object b to show type errors like object a

**Comment by andrewbranch** [comment]
See https://www.typescriptlang.org/docs/handbook/enums.html#union-enums-and-enum-member-types

`A` is special because its values are number literals. `B` is a plain old numeric enum whose type gets treated as `number`.
