### ISSUE TITLE
tsconfig  exclude doesn't work for index.d.ts in node_modules

### ISSUE THREAD

**Issue by 412799755** [microsoft/TypeScript#46078]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEBcGcGMHsDsBmBLA5gOgFaQaAUCKAEQCmAHtADYCuAJiUQFygDaRAhgA6fAC2stapRLAAVKLHpa6KEQC6eAmBTDQtZACcSccBoCejPKGOhCAWi6cjJwidBn+g4deO27DgUJIBBF6bB27vACJAD6jl6Qfm6B7ji8JACyns52MbF2yPD0ZFIyUWkBGYHgJJDgeVCKhKXllZCgyA3kVHQktPiEAEbU4I3Z5PWNDdAAFtoA1u2gQA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior
tsconfig.json :
{
 "exclude": ["app/module/**/*.d.ts"]
}

 file direcotry:
     -app
         -module
          -moduleA
             -node_modules
                -someModule
                  index.d.ts
                  test.d.ts

 test.d.ts is excluded 
 but index.d.ts is checked 

### 🙂 Expected behavior

 index.d.ts is also excluded 
 no typechecking on index.d.ts

**Comment by ilogico** [comment]
1. [exclude](https://www.typescriptlang.org/tsconfig#exclude) is not a mechanism that prevents a file from being included in the codebase - it simply changes what the include setting finds.
2. [types](https://www.typescriptlang.org/tsconfig#types) can be used to restrict the ambient declarations present in your node_modules. However, if you import code that references those global declarations, they will still be loaded.
3. [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) can be used to avoid checking library code.

**Comment by andrewbranch** [comment]
`exclude` will not prevent the inclusion of something that gets imported/referenced. node_modules is in the default value of `exclude`, so this config has no effect.

**Comment by andrewbranch** [comment]
You can use `--explainFiles` to show why each file is getting included.
