### ISSUE TITLE
Member Prediction wrong in Typescript Code....

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#46084]
# Bug Report

Typescript wrongly returns: 
This condition will always return 'false' since the types 'ParserState.ParseBinary' and 'ParserState.ParseMember' have no overlap.

### 🔎 Search Terms

member prediction wrong 

### 🕗 Version & Regression Information

Don't know if it is a regression. Does not work with current Version: 4.4.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwAoEMoGdhQDKMWMwcA3gFBy1wByEiwANDXdnsAEICWiOAJ5s6mHPgCywVACMCIjuJ78hjKbPlUAvlSqhIsOAGMANlly44AUXBRgF3kwAqEAGK8TZKFZPSkMTnwoWmoqAEgwKF4AN1JyXBIyAC4xLiJE8gBeVKDiOIA6RmYAbl1RSIgyIzIAEzho3lxeGAAKAEpKdlFaGAALRvyEuLhswII8snyx9TkoUtEdcIqq2vrG5r4BKEF2zrCwvoGhshGc8YyppU2hUv3D3HyGpta28P233gAzOBb7wYyRqMlOkCtNpLNXvsDv0HscsmcQZMxtdtmpwQRbjotEA

### 💻 Code

```ts
	export enum ParserState {
		None,
		ParseBinary,
		ParseMember,
		ParseBinaryNoMember,
	}

	export class ExpressionToFilterElementParser  {

		private state: ParserState = ParserState.None;

		protected visit() {
			this.state = ParserState.ParseMember;
		}

		protected visitBinary() {
			this.state = ParserState.ParseBinary;
			this.visit()
				
			if (this.state == ParserState.ParseMember)
				this.state = ParserState.ParseBinaryNoMember;
		}
	}
```

### 🙁 Actual behavior

Typescript complains line

        if (this.state == ParserState.ParseMember)

with error:
This condition will always return 'false' since the types 'ParserState.ParseBinary' and 'ParserState.ParseMember' have no overlap.

### 🙂 Expected behavior

Code should work

**Comment by fatcerberus** [comment]
*le sigh*
#9998

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/issues/44336#issuecomment-859070807

**Comment by jogibear9988** [comment]
I will fix the issue in the evening, sorry

**Comment by jogibear9988** [comment]
@MartinJohns 
Sorry, for doing it wrong (again). Hopfully it's better so

**Comment by jogibear9988** [comment]
When I see how mayn issues there are linked in #9998, wouldn't it be better to disable the FlowAnalysis (at least after function calls wich could modify state) as default, and enable it via setting? 
Or introduce a way to mark functions if they have side effects or not.

**Comment by fatcerberus** [comment]
#9998 itself explains why that would be a bad idea: TS would have to assume every single function call modified your local state and reset all your narrowings, making CFA practically useless.

mad for the side effect annotation, see #7770.

**Comment by jogibear9988** [comment]
i think it's mostly useless since in classes most methods would modify the state of a class variable. If not, it does not need to be a method of the class? (if it is a function, then this maybe could be different, but i would not asume so)
