### ISSUE TITLE
Invalid type narrowing when returning function call directly

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#46082]
# Bug Report

### 🔎 Search Terms

Invalid direct return type narrowing

### 🕗 Version & Regression Information

At least in 4.2.x or earlier, occurs in 4.4.x

- This is the behavior in every version I tried, and I reviewed the FAQ for entries.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20210927#code/C4TwDgpgBAUgygeQHJQLwCgpQD5QHYCuANkZjlAEYD2VREAhnmbhQJYDmrewz+BAthQgAnXgGdgwru14BvKAG0uAEwgAPAFxQJUvOwC6W+MigBfXsaQL9AbnTp1YKsOBRQkKAAUi9LggoAVhAAxq6oULJkSniqmtqS0oawiEjopnbo7tAAosLCAILC7GIAPADCUOrAEDFi8brs5ISCIgA0UAAilWrVtVAEMRAAZlwQyuTevnj+QaEAfGgRZFjBVKpaZctQ-BBiYvTsEFo60lvK9MD0APxaHWn2WVC5wuXdvcp1J3pNAkLC7V0qjUPv1BiM8GMJj4-IEQsAFuFIlgsHh6DstAAiIY0DFbVbrKCbZHbXb7Q7HBJ6M4Xa63e7oIYDUKsKh4fAQADuz1eQL6X0auGafwBb2BdQGqnBkNwkxhszCoMlo2UcwAFPQimItM9CsVygC5gBKbV5fWdBZI5HCCDAAjCNmW4kotFHKBYnGtLbE-GujXFAB0Ps9TuROz2B19mv9YbJEGDIag-qTqqyVCGUD9Yn950uUAAhKhwgByCXDZVFqBXCJQHP0LSZ7M0sxQLSyUyG+NYczmdB0VxqRYQrl5VWOqA+zHVCQYzsk8Pkt1T4C49sZRl4ZmstwAC1YYgA6s4ANZiVXGqAANyorHGuG5RaXRfapalKvI96XACYnxEl1pJAQECmBaeKshIlR5IOnLPKOXrIhOi67Mus7EjGEaTkhM5bKu9jEtatr2hBwh2D266bmywC7mIHRULsSBUMAh7CEeZ5aFeN7vqaD5IT+L7Kgsd5cV+P6yH+bjCIBwFLHhNp2myQ4wWO3prK6GJLlhCZzrGGHTrOOFbAA9AZUAACrbtAYDCFQFB0PwUB7juFw7tAjxps5UD4XJl70EQgH2XU3JqZh7TyGJAEQDYza4HxEIqhWFAEDwxJGfZrhiNuVDEOMQhPKaQW6YqZaxXM9LoClACS6asK45lEGAYjtJR0BCNu9AXiywhQFu9A1qw1qhB5smERePl+Q5TXaC6GZ1Kw6blb14x4AxNbDPQxCuF0hwQlIwT2fJ0GQcAVCFa+9hkcALL7cOwj7tVGWJR0q3rQA4jUIisMEACqYLKiUZAVLyIL8j8LT-GQgI9GKJ3KlCUwzHC6BqpmJoFJqZodEaKPoyBMkEQ6cHOuibrYlQGkJghDZBgTWnoRmUZoYcKHIkm-opuAEBuQ2tb5oWUAlj9sUVlW8i1vWUbc6YLYRO2en0n2RFQddt2UZlwCPUMa1EMAr3bR931KrFo5QClH48e0srTLCA3RQLYwlZpCH5ch1MM6p6l6YakXoEAA)

### 💻 Code
```ts
type JSON =
  | null
  | boolean
  | bigint
  | number
  | string
  | { [index: string]: JSON }
  | JSON[];

export type PlainObject = {
  [index: string]: JSON
};

type ErrArgs<C extends string | number, D extends undefined | PlainObject> = {
    code: C
    message: string
    data?: D
}

type Err<C extends string | number, D extends undefined | PlainObject> = {
    name: "foo"
    code: C
    message: string
    data?: D
}

function newErr<C extends string | number, D extends undefined | PlainObject = undefined>(args: ErrArgs<C, D>): Err<C, D> {
    return {
        name: "foo",
        code: args.code,
        message: args.message,
        ...(typeof args.data !== 'undefined' ? { data: args.data } : {}),
    }
}

let x = newErr({
    code: "test",
    message: "test"
});

function thisWorks(): void | Err<'test', undefined> | Err<'test2', {test: true}> {
    const err = newErr({
        code: "test",
        message: "test",
    });

    return err;
}

function thisDoesNotWork(): void | Err<'test', undefined> | Err<'test2', {test: true}> {
   // Error: Type 'Err<"test", { test: true; } | undefined>' is not assignable to type 
  // 'void | Err<"test", undefined> | Err<"test2", { test: true; }>'.
    return newErr({
        code: "test",
        message: "test",
    });

    // The problem is that the type of the return value is Err<"test", { test: true; } | undefined>' but
    // it should be Err<"test", undefined>
}

// If it helps, the behavior on a direct return value is the same as if I did not default D generic in newErr to undefined

function newErrWithoutDefaultGenericUndefined<
  C extends string | number,
  D extends undefined | PlainObject
>(args: ErrArgs<C, D>): Err<C, D> {
    return {
        name: "foo",
        code: args.code,
        message: args.message,
        ...(typeof args.data !== 'undefined' ? { data: args.data } : {}),
    }
}

let err = newErrWithoutDefaultGenericUndefined({ // Err<'test', PlainObject | undefined>
        code: "test",
        message: "test",
    }); 
```

### 🙁 Actual behavior
The problem is that the type of the return value is Err<"test", { test: true; } | undefined>' but it should be Err<"test", undefined> and it happens only if the call to `newErr` is directly returned, but works ok in variable assignment.

### 🙂 Expected behavior
Type should be properly narrowed to `Err<'test', undefined> and be consistent with what happens in variable assignment.

**Comment by sandersn** [comment]
This is working as intended.

1. When you don't pass a `data` property to `newErr`, it has no way to infer `D` from its argument. 
2. When you assign `newErr` to a variable, it has no other source of information to infer `D`. That's why it's `undefined` in `thisWorks`, because it uses `D`'s default value.
3. When you return an expression directly, it gets its contextual type from the return type of the containing function, `thisDoesNotWork` in this case.
4. This serves as a source of information to infer `D`.
4. So `D` is inferred as `undefined | { test: true }` -- it just uses all the types from the return type. It does not use its default `undefined`
5. Unfortunately, Typescript can't prove that `Err<"test", undefined | { test: true }>` is assignable to `Err<"test", undefined> | Err<'test", { test: true }>` so you get an error.
