### ISSUE TITLE
Object allows not existing properties on type when assigned value was touched by type

### ISSUE THREAD

**Issue by andjsrk** [microsoft/TypeScript#46087]
# Bug Report

### 🔎 Search Terms
object not existing keys

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behavior

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?target=8&module=1&ts=4.4.3#code/G4QwTgBAZg9jBcEDeBYAUASAEbkQOwFcBbLAUzHWxAC9EBnAFzAEs8BzdAXwgF5lKcYRAAYANAJqIA5FPGZYMQSK4QQdfpiURCJchNoRGLdpQVadZCmk7ooBPAGMGzGHkMwipAGL2HAHgAlAD4ACig8RBCASl4giACoxACNDDBSBgIwN3DornQ6D29fPyRoOHxiSwhOUOjYiBDShUQARlEyxVwIGWqoqKA)

### 💻 Code

```ts
var foo: {
	bar: number
	baz: string
} = {
	bar: 0,
	baz: '',
	foobar: 0
} as {
	bar: number
	baz: string
	foobar: number
}
function someFunc<R>(fn: () => R): R {
	return fn()
}
someFunc<{ foo: number }>(() => ({ foo: 1, foobar: '' }))
```

### 🙁 Actual behavior
error doesn't occurs even `foobar` property is exists in object.

### 🙂 Expected behavior
error occurs because `foobar` is not existing property in object.

**Comment by IllusionMH** [comment]
Excess property checks is lint/helper feature, not type error as if you assign incompatible type and type assertion is first way to intentionally skip this error that is mentioned in handbook https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks

Errors in cases above would be possible only with support of Exact Types #12936

**Comment by andjsrk** [comment]
Then why even function's return type works like type assertion?
I used `Array#map`, and I found no error occurs even unexpected properties are in returning object, this is why I started to think this is bug.

**Comment by andjsrk** [comment]
I got it, thanks.
