### ISSUE TITLE
Quick info for abstract class names/methods do not inform the user of abstractness

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4610]
![image](https://cloud.githubusercontent.com/assets/972891/9644598/e422a252-517b-11e5-9413-8192da3c436f.png)

![image](https://cloud.githubusercontent.com/assets/972891/9644605/ee6e3730-517b-11e5-96b9-4277db1aa220.png)

**Comment by mhegazy** [comment]
this looks like the same behavior as C# and VB. would like to keep the experience as close as we can,

**Comment by DanielRosenwasser** [comment]
Perhaps Roslyn should inform the user of abstractness as well. @CyrusNajmabadi any thoughts?

**Comment by mhegazy** [comment]
@DanielRosenwasser can you log a https://github.com/dotnet/roslyn issue for this.

**Comment by DanielRosenwasser** [comment]
Tracking this at https://github.com/dotnet/roslyn/issues/5739.
