### ISSUE TITLE
strictNullChecks does not work in === 

### ISSUE THREAD

**Issue by AlexDM0** [microsoft/TypeScript#46129]
# Bug Report

### 🔎 Search Terms

strictNullChecks
strictNullChecks equals
strictNullChecks === 

### 🕗 Version & Regression Information

I had not encountered this before until I found a bug in our framework, which I thought would be caught by TS.
Playground shows this being an issue since 3.3.3333 (as far back as it goes) and also on nightly (4.5.0-dev202110929).

Please keep and fill in the line that best applies:

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about strictNullChecks

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTC0oZwFwJwSwMZQHIFcA26DCALApggNYQCwAUOnlAAQCG1AXNQHaoC2ARnjNQLzUAmcuRDUAKgGUBAZgECANNSg44EahBwB7AO5ro8JGky4CxOjDzU8zWh0oATAHTl6-VpmFlRkmQDYA7IrwAOY4UABmGOgAnupwzAiWrJzcdMz21ByampS0zNQ4tABuSZrUmiUw6LQADi58vPywqHie3lLSAUFwoRFRsRCoCUnsXDx5GfrxwQXFpeWV1XVkro3UAORQeNDr1G3A1ADqOLH2mttKKmrMmjTKMDriHQEA-NRoKePpLFGzJSxlCrcJbUbT4fJTQxRExENSqKw2Ox4Jz1RpuKL7cRXahsHphTKWIq0dBwDJwcJ0UG0NRDeJwKBwYlwABeyMUHFQd3w1DOCD0tFiQ3seHC8WRaQy7nQ5ksCE0zAgpO44ogeBqtBgtC2SmiNW2zhWDX4QpFYvsQA

### 💻 Code

```js
//--strictNullChecks
let a : number = 2

// Why does this not throw TS2367? Number and null have no overlap when strictNullChecks is enabled.
a === null

// This might be valid if a was uninitialized, but the docs say undefined and null are considered separate types.
a === undefined
```

### 🙁 Actual behavior

As per the documentation "When strictNullChecks is true, null and undefined have their own distinct types and you’ll get a type error if you try to use them where a concrete value is expected."
This would mean that a number being compared to null, will throw TS2367 "This condition will always return 'false' since the types 'number' and 'X' have no overlap.". However, both null and undefined in the code above do not raise TS2637.

### 🙂 Expected behavior

If strictNullChecks is enabled, number === null should raise TS2637 since there is no overlap between the types.

**Comment by MartinJohns** [comment]
Duplicate of #11920. Used search terms: `compare null in:title `

**Comment by AlexDM0** [comment]
Right, sorry missed that one. I'll close this. Thanks for the heads up!
