### ISSUE TITLE
`lib.es3.d.ts` for DefinitelyTyped libraries with legacy support

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/TypeScript#46130]
# Suggestion

## 🔍 Search Terms

es3 lib tsc

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Adding a `lib.es3.d.ts` and `--lib es3` option for the `tsc` compiler.
The file would provide every ES3 feature and TS utilities from `lib.es5.d.ts`.
 
## 📃 Motivating Example

A large number of older libraries such as JQuery will target ES3 only.
You can find these on the DefinitelyTyped monorepo.
There should be the option to use these libraries without opting into ES5, for legacy support.

## 💻 Use Cases

- **What do you want to use this for?**
  I've been writing a DefinitelyTyped package that depends on JQuery and supports IE8. Horrible but go figure.
- **What shortcomings exist with current approaches?**
  Right now, `lib` can be left empty but that misses all the TS core utils and ES3 types.
- **What workarounds are you using in the meantime?**
  `--lib ES5` which is not ideal but will have to do.

**Comment by andrewbranch** [comment]
You should be able to do this yourself with https://github.com/microsoft/TypeScript/pull/45771. I don’t think we’re going to invest in targeting ES3 at this point 😕
