### ISSUE TITLE
Callbacks can use uninitialized variables that aren't defined during callback execution

### ISSUE THREAD

**Issue by Fleker** [microsoft/TypeScript#46136]
# Bug Report

### 🔎 Search Terms

Callback, undefined, null-pointer exception

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChkHICuwAJgFzLphSgDmuAvrrqJLIigGLBQTUB7PgBUocEOkRhgAkDnyE+cCsgAUASmQBeAHzIAClAEBbYJgA8GaDoUEiAB1JxIlVQA9K4gJ6bdBo6YWAEYCAgA2EOI2zLhgXvYoouKSCNKyAMJwYWFBiADW2mpglDx8giJiElIyIL563ixw6F4gCMgwRK1pclCdSVWpNaoIWTn5lP0p3ZnZuQh5mniEyAD0KwZhnAAW4aRYpfxgQig0ydWytsgIstTIpwPdJbyHx5Pnclryy8tKKk0tbQ02j0qmwJBUAHJ7JskDswnsoBDGOoADSXZYOJwuZD-VpqDw4kA+YF3XoQNHLZg-CBgIhQOSGExmCAAOjK4QAbhBVHAAO5wYBgK6jOZ5VT3KY1dTqJiNZp4jpdGrIYwCkBApaEa4SIVETBQQp8gVC3ogN6DWQ8+VtIV+TXfUleL4O77a25gsiMQp66Dol1u8KssICOiqCHgiHIADUxDIMpdyC9IzACC2aggiz9DoDERZ0CMUDDmRAIAEJsipGI+uQAEkACIQlHIDNZ75gLZGXnN1tUl18Wn0nH8wV3NkVjSXZGXHNBkNhn2I6PIABSAGUAPIAORZ1FoIDowBgXlUC+lstwqtAE6AA)

### 💻 Code

```ts
interface User {
    uid: string
}

interface FirestoreTransaction {
    read: () => Promise<User>
    update: (x: any) => Promise<boolean>
}

type TransactionCallback = (t: FirestoreTransaction) => any

async function runTransaction(callback: TransactionCallback) {
    // Placeholder Firestore transaction
    const transaction: FirestoreTransaction = {
        read: async () => ({uid: 'placeholder'}),
        update: async (x: any) => true,
    }
    return Promise.resolve(await callback(transaction))
}

async function main() {
    const user = await runTransaction(async t => {
        try {
            const {uid} = user
            console.log('uid' + uid)
        } catch (e) {
            console.error('Cannot read user ID', e)
            throw e
        }
        return await t.read()
    })
    console.log('user' + JSON.stringify(user))
}

main()
```

### 🙁 Actual behavior

I have a project that fetches user details from a Firestore database, which uses a callback pattern to define transactional events. In one of these functions I ran into a runtime error because I was trying to access `user` within the transaction accidentally and received an undefined error.

```
[ERR]: "Cannot read user ID",  Cannot access 'user' before initialization 
```

This in turn caused the rest of the logic to fail and I was surprised by this error. While I had written this a bit hastily, I thought that the type checker in Typescript would certainly catch that this value would be undefined before trying to access. My `tsconfig.json` has `"strictNullChecks": true`.

It seems like a callback is allowed to access a variable that is defined outside of the callback. This seems like a poor assumption, particularly when I am using async/await to halt further execution and the definition of these variables. I also notice that Typescript is fine if the variable name is defined after the callback flow entirely.

```ts
    const user2 = await runTransaction(async t => {
        try {
            const {uid} = user
            console.log('uid' + uid)
        } catch (e) {
            console.error('Cannot read user ID', e)
            throw e
        }
        return await t.read()
    })
    const user = {uid: 'placeholder2'}
```

### 🙂 Expected behavior

While callbacks may be able to run at any time, the use of `await` may give a stronger signal that the return variable and later variable names might not actually exist at the execution time of the callback. I would like there to be some extra warning that the variable might not exist. An error, particularly during `strictNullChecks` would be useful in catching errors of this class going forward.

**Comment by MartinJohns** [comment]
> It seems like a callback is allowed to access a variable that is defined outside of the callback.

**JavaScript** allows this. This is unrelated to TypeScript. Also, **many** languages support such a feature. Keyword here is "closures".

> This seems like a poor assumption, particularly when I am using async/await to halt further execution and the definition of these variables. 

I don't see how this is relevant. You're not "halting" execution of the function. The function is returning a value, immediately, and that value is a `Promise` in case of async functions. You can't "halt" execution of functions and prevent an immediate return value (without crashing your runtime).

> I also notice that Typescript is fine if the variable name is defined after the callback flow entirely.

Again, this is JavaScript that allows it. It's nothing related to TypeScript.

**Comment by Fleker** [comment]
> IMO referencing the variable you're initializing within the callback of said initialization is a really bad smelling pattern.

I agree it's a code smell, and a mistake that I made accidentally. I understand that _technically_ it is permissible, but I'd like to request that this becomes a error in certain settings so that Typescript will let me know when I make this kind of mistake.

**Comment by fatcerberus** [comment]
As a counterpoint I'm going to note that, in my own neoSphere and Oozaru game engines, this is a perfectly acceptable piece of code:

```ts
const jobToken = Dispatch.onUpdate(async () => {
    // do stuff each frame, maybe an await here and there...
    if (amIFinished) {
        Dispatch.cancel(jobToken);
    }
});
```

If this were an error, I don't think it would be easy to refactor the above code to remove the backreference without turning it into a full-blown object (i.e. `Dispatch.cancel(this.token)`).

**Comment by FilipeBeck** [comment]
The compiler could handle as _Possibly undefined_ for the whole expression after `=`

**Comment by Fleker** [comment]
I proposed this being an error under the `strictNullChecks` flag. If this variable was seen as possibly undefined, then you could use the exclamation operator to override that check. Because technically the variable should be considered possibly undefined.

**Comment by FilipeBeck** [comment]
> JavaScript allows this. This is unrelated to TypeScript. Also, many languages support such a feature. Keyword here is "closures".

Javascript also allows this:
```javascript
let x

console.log(x.toString())
```
Typescript, not:
```typescript
let x: number

console.log(x.toString()) // ERROR: Variable 'x' is used before being assigned.(2454)
```

Handle as _Possibly `undefined`_ is consistent for these scenarios:
```typescript
function doIt<T>(handler: () => T): T {
    return handler()
}

let y: number = doIt(() => {
    console.log(y.toString()) // Currently, OK. Should be ERROR: Object is possibly 'undefined'.(2532)
    return 10
})

console.log(y.toString()) // OK: `y` is already setted
```

This feature already can achieved by declaring y as `number | undefined`:
```typescript
function doIt<T>(handler: () => T): T {
    return handler()
}

let y: number | undefined = doIt(() => {
    console.log(y.toString()) // Currently, Error: Object is possibly 'undefined'.
    return 10
})

console.log(y.toString()) // Currently, OK: `y` is already setted
```

[Playground code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAEzgSSgHgCoD4AUAFgIZjIA2ApgE4Bci+AlIgLy6LaP3aIDeAUIiGJqlKCGpISZKtSb8Avv35UoiAJ70wIALYAjGogA+icMkrAYYSslYp0UfE1bsBwxBAQBnOFQB05HAA5vjqflBwAMpQ1FYhjMwA9ImIAMISomBQ5OoANIgAotTUcHSIAPJ6AFaU0IgwXogADnBeXjB6OYgA5GYWVjbdfoLCouKSiACMAAyKjMqeYD7+gSFhEdGxYPFJKenFlFk5+eUA0vQABuoX9Y3E5KLEyOqIXmJQNkA)

**Comment by MartinJohns** [comment]
> // Currently, OK. Should be ERROR: Object is possibly 'undefined'.(2532)

You can argument in both ways: Why should it be possibly `undefined`, when it's clearly **always** assigned a value?

IMO the proper solution would be #11498 to indicate whether the callback is invoked immediately (meaning it's always `undefined`) or deferred (it's never `undefined`).

**Comment by FilipeBeck** [comment]
> You can argument in both ways: Why should it be possibly undefined, when it's clearly always assigned a value?

No, because the value has not been assigned yet during the access within the callback. In `console.log(y.toString())`, `y` is clearly `undefined`. After `return 10`, `y` is defined. A `immediate` notation described in https://github.com/microsoft/TypeScript/issues/11498 makes it more evident. As described by the [Playground example](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAEzgSSgHgCoD4AUAFgIZjIA2ApgE4Bci+AlIgLy6LaP3aIDeAUIiGJqlKCGpISZKtSb8Avv35UoiAJ70wIALYAjGogA+icMkrAYYSslYp0UfE1bsBwxBAQBnOFQB05HAA5vjqflBwAMpQ1FYhjMwA9ImIAMISomBQ5OoANIgAotTUcHSIAPJ6AFaU0IgwXogADnBeXjB6OYgA5GYWVjbdfoLCouKSiACMAAyKjMqeYD7+gSFhEdGxYPFJKenFlFk5+eUA0vQABuoX9Y3E5KLEyOqIXmJQNkA), if declare `y` as `number | undefined`, the compiler already understand that the value is not assigned within the callback and is assigned after de _assignment statement_ (after `y = doIt(...`).

Use a _Possibly undefined_ is more consistent than _Variable 'x' is used before being assigned_ because the callback can have _deferred code_. In the following example, `console.log(y.toString())` works because `y` is already assigned within the  `setTimeout` callback.
```typescript
let y: number = doIt(() => {
    setTimeout(() => console.log(y.toString()), 10)
    return 10
})
```

I think the idea here is just to prevent the _accidental access_ that the issue describes. I think the compiler handle `y` as `number | undefined` in all code within the _assignment expression_ is simple and sufficient for these scenarios. Again, this is exactly the behaviour when declares `y` explictly as `number | undefined`.

**Comment by FilipeBeck** [comment]
> IMO the proper solution would be #11498 to indicate whether the callback is invoked immediately (meaning it's always undefined) or deferred (it's never undefined).

Yes, a `immediate` notation resolves the problem but, I think this should be the behaviour without the `immediate` notation because, technically, this is the case. The following code:
```typescript
let x: number = doIt(() => {
    console.log(x.toString())
   return 10
}
```

Is the same that:
```typescript
let x: number

console.log(x.toString())

x = 10
```

That is, the expression `doIt(...` is executed before the assignment. At lowest level, the JS engine calls the expression (`doIt`) and after assigns the return value to `y`.

**Comment by MartinJohns** [comment]
> Is the same that:

But it's not, as it has been mentioned several times already...

**Comment by FilipeBeck** [comment]
In this example, yes. Simply because `x` is not assigned in `x.toString()`. First, the expression, after the assignment

**Comment by fatcerberus** [comment]
See my example above for a counterexample.  There are *plenty* of valid cases where the callback is *not* called immediately, and TS has no way to know that.

**Comment by FilipeBeck** [comment]
@fatcerberus That's exactly what I'm trying to demonstrate. In `Dispatch.cancel(jobToken)`, `jobToken` should be handled as __Possibly `undefined`__. All inside the expression following `=` should handle `jobToken` as __Possibly `undefined`__

**Comment by fatcerberus** [comment]
Assuming I accept that premise, that wouldn’t be enough because in that case *accessing the variable at all* is a runtime error.  In that case even checking whether it’s undefined or not will throw, and your argument becomes one where TS rejects this pattern outright.  This is why we’d need the `immediate` annotation.

**Comment by FilipeBeck** [comment]
> In that case even checking whether it’s undefined or not will throw


I did not understand. `jobToken` can be undefined, no? If you know it's not be `undefined`, a `!` whoul solves:
```typescript
const jobToken = Dispatch.onUpdate(async () => {
    // do stuff each frame, maybe an await here and there...
    if (amIFinished) {
        Dispatch.cancel(jobToken!); // Just use a `!`
    }
});
```

You don't need refactors the code, etc... Just use a `!`

**Comment by FilipeBeck** [comment]
The compiler handles `let v: number = $expression` as _defined_ inside the expression. It is not because the _expression_. It is because `v` is a `number` and not a `number | undefined`. A `immediate` does not solve this problem.

**Comment by FilipeBeck** [comment]
The compiler sees all after `let v: number =` as _v is assigned_.It seems that the check to determine if _v has a value_ is done before checking the _assignment expression_. Even with `immediate`, when verifiyng the expression after `=`, `v` _has value_ and is of type `number`. Then, it will allow `v.toString()` within the expression without compiler errors. Someone with more experience in the implementation can clarify this point better. The idea in https://github.com/microsoft/TypeScript/issues/11498 seems to have another purposes.

**Comment by FilipeBeck** [comment]
@Fleker If https://github.com/microsoft/TypeScript/issues/11498 solves _used before assigned_ (mentions [here](https://github.com/microsoft/TypeScript/issues/11498#issuecomment-252829806) and [here](used before assigned), then this issues is, in fact, a subset of https://github.com/microsoft/TypeScript/issues/11498

**Comment by fatcerberus** [comment]
The point I'm trying to make here is that adding `| undefined` to the type *doesn't actually solve the problem you want to solve* because it doesn't reflect what actually happens at runtime:
```ts
function doIt(callback) {
    callback();
    return 42;
}

const x: number = doIt(() => {
    if (x !== undefined)  // ReferenceError: Cannot access 'x' before initialization
        console.log(x);
});
```

The error TS would need to produce here would necessarily be one that *couldn't* be silenced by simply writing `x!` and so would break cases where this pattern is actually valid.

**Comment by Fleker** [comment]
Yes it does seem like #11498 is related issue assuming that the compiler handles errors correctly. I'm not entirely sure about the `immediate` annotation, but it does address the same issue.

**Comment by FilipeBeck** [comment]
@fatcerberus Yes, with `immediate` covering the _used before assigned_ error, it makes more sense. My concern was whether `immediate` would not cover these scenarios.

**Comment by FilipeBeck** [comment]
> Yes, a immediate notation resolves the problem but, I think this should be the behaviour without the immediate notation because...

In fact, on second thought, I think it is better to be solved using `immediate`.

**Comment by andrewbranch** [comment]
I know it’s not an exact match, but for housekeeping purposes I’m going to call this an extension of #9998 / #11498.
