### ISSUE TITLE
Support `main` in package.json lookup

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#4613]
Final work on https://github.com/Microsoft/TypeScript/issues/2338 Works great. One minor issue, `main` isn't supported, that means that one needs to do `import * as root from "ts-npm-module/js";` [example](https://github.com/basarat/ts-npm-module-consume/blob/5de69a1b6314d8d12a8ef6438a8d5d232c5c6616/ts/index.ts#L2) instead of a simpler (and more common in js) `import * as root from "ts-npm-module";`

Creating a separate issue for tracking :rose: + possible PR.

**Comment by mhegazy** [comment]
so why not set `typings` to `js\index.d.ts` instead?

**Comment by basarat** [comment]
As it prevents deep reaching e.g. `"ts-npm-module/js/deep/foo";`

**Comment by basarat** [comment]
It is used quite commonly e.g. `"react"` and `"react/addons"`

**Comment by basarat** [comment]
> so why not set typings to js\index.d.ts instead

Setting it to `js/index` does indeed work. Basically `typings` is just an alias for `main`, the rest of the lookups don't even use typings :+1: :) Thanks :rose: 

Complete example : 

```ts
// Use from main
import * as root from "ts-npm-module";

var foo = root.foo;
var Bar = root.Bar;
var bas = root.bas;

// Or any of the other files within the module
import {foo as deepFoo} from "ts-npm-module/js/deep/foo";
import {Bar as deepBar} from "ts-npm-module/js/deep/deeper/bar";

foo = deepFoo;
Bar = deepBar;
```

Closing

**Comment by mhegazy** [comment]
> Setting it to js/index does indeed work. Basically typings is just an alias for main,

correct. and in fact @vladima had an earlier iteration that had look up for both `main` and `typings` but that felt redundant. so we removed main checking. We would be interested to know if this will block some scenarios that `typings` would not be sufficient in.
