### ISSUE TITLE
Improve type inference on parameter types and return types of overload class methods implementation.

### ISSUE THREAD

**Issue by tychenjiajun** [microsoft/TypeScript#46132]
# Suggestion

## 🔍 Search Terms

class\implements\type inference\overload\class methods

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Read the codes and comments below.

## 📃 Motivating Example

```ts
class Foo {
    foo(a: number): 1;
    foo(a: string): 2;
    foo(a: boolean): 3;
    foo(a: boolean | number | string): 1 | 2 | 3 {
        if (typeof a === 'number') return 1;
        if (typeof a === 'string') return 2;
        return 3;
    }
}

interface IFoo {
    foo<T extends 1>(a: number): T;
    foo<T extends 2>(a: string): T;
    foo<T extends 3>(a: boolean): T;
}

type F = {
    <T extends 1>(a: number): T;
    <T extends 2>(a: string): T;
    <T extends 3>(a: boolean): T;
}

class Bar2 implements IFoo {
    foo(a) { // error here: ts 7006. expected to be number | string | boolean
        if (typeof a === 'number') return 1;
        if (typeof a === 'string') return 2;
        return 3;
    }
}

class Bar implements IFoo {
    foo(a: number | string | boolean) {
        if (typeof a === 'number') return 1;
        else if (typeof a === 'string') return 2;
        else return 3;
    }
}

class Baz {
    foo: F = (a: any) => {
        if (typeof a === 'number') return 1;
        if (typeof a === 'string') return 2;
        return 3;
    }
}

new Foo().foo(1); // infer as 1
new Baz().foo('1'); // infer as 2;
new Bar().foo(true) // infer as 1 | 2 | 3, expected to be 3;
```

## 💻 Use Cases

Some request/fetch library, return specific type based on path or parameters.

Maybe releated to https://github.com/microsoft/TypeScript/issues/14107 https://github.com/microsoft/TypeScript/issues/22609 https://github.com/microsoft/TypeScript/issues/28172 https://github.com/microsoft/TypeScript/issues/25352 https://github.com/microsoft/TypeScript/issues/14515

**Comment by MartinJohns** [comment]
[Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQGaIBRgC5oA7AVwFsAjAUwCcBKIgRgG51Md58iIAXWgJbEA5o2gAmNpmx5C0SohDUwxMQGYpHWUQXwlK6AB8SFGrSPQ+gkWKYXxFtSnbSMArNFy8AngAdq8B5g0AC8YdAA5GRUdBH00LTUvKS0xNCsLq7unj7+gdDBYSGRVkLCcQlJKWmSmdKJyanQGpkAvqjtqEK8dFhgwNTQAJIISGjSnAA8ACrQ1AAePcQAJjBMAHzcJjEMRNOaGFOzC0urEptypTZ7BzLwM3OL1Cswahc6isqqNx2oqLmDWChZzSB4nZ5nDZbaJmMT7TJgp4vc5bK6iH6g45Is5vLa6fTfaDwzqgSAwABCYFoDgE5F8SnIz14MBGiBBWi4YHiyGgAHpeXNaLR4OYABZ0ahEZnQADsAAY5QA2AB0j38wB6y2gvCQNG2ZgsaIs+K+dUw2S8fgCQVC4Sipli8Qa1XSt2kFoB+UKdrRFWdTVqrkw-rSLWk7RJ4Cg0Ep5lp9OojOI0tZY0ynGhDvMxiNxhNKm5ZrcHkteRtRUiMMdlUaaQyQYw1BAEEGHqtXttxQivqdVQDbswTZbNZdYcwEb+pOjlIAXuzDogiEDilsVN54iF1vOsiXPeW7VXaH6+3WB8Wcu3912eyP+0Xb6HbhPUMRqAB3OB4ejKjNMegsPkBSELA6AKNYX3fGMwBnXBvwzCImDiAD+WgYDQMgCQ2FfD9Y1gn88H4UhqHiFC0PMDC7GMBxjDUAAaNVqA1agtR1eRBhaIA)...
