### ISSUE TITLE
///references should support resolving environment variables

### ISSUE THREAD

**Issue by larsendaniel** [microsoft/TypeScript#4615]
For example, instead of using
`/// <reference path="../../../myCustomPathWhichMightNotWorkOnMyCoWorkersComputer/library.d.ts" />`

I’d like to use either
`/// <reference path="$(MY_PARTNER_TEAM_LIB)/library.d.ts" />`
Or
`/// <reference path="%MY_PARTNER_TEAM_LIB%/library.d.ts" />`

**Comment by mhegazy** [comment]
one thing to note, tsconfig.json does not support environment variables either.

**Comment by ctartamella** [comment]
+1 for parsing environment variables in (at least) tsconfig.json.  Build systems that want to use this file rely on being able to use variables for things like output directories.

**Comment by arkdemon** [comment]
+1

**Comment by markdrake** [comment]
+1

**Comment by rrgarciach** [comment]
+1

**Comment by bkielbasa** [comment]
+1

**Comment by RyanCavanaugh** [comment]
We're at ~9 upvotes after five years of being opened and this opens up a big can of worms for things like cloud build systems; with other means to have file inclusion we've added in the meantime, I don't think this one meets the bar for implementation.
