### ISSUE TITLE
instanceof type narrowing is different when instance type is defined as an object type vs. interface

### ISSUE THREAD

**Issue by butchler** [microsoft/TypeScript#46154]
# Bug Report

### 🔎 Search Terms

instanceof, interface, type narrowing, object type, class

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `instanceof`

Note that while this issue is related to type narrowing and `instanceof`, it is not about the fact that `instanceof` is a nominal-typing check while TypeScript is structurally typed. The example code tries to use `instanceof` to distinguish between a class and a primitive, not between two structurally equal classes.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.3#code/PTAEEkDsGcBcENIGMCmpYE8AOaAmKAzAS0hV1HmlBNhQCcD5UAoG+x1UAQSjkVSi0GTNAG8KALlCQArgFsARvVABfANzMkAexixug9iKnjSAdwAUASik9d-FAeGcVoALygCM5LCI6roURdKCkgMDWZPb19IdBQ4Rw4UcwAPG14EZAdIIUTQAB9QODoSAHNLAOZQKtBk6jtMrQJ9bMMWatAAfhqqkGa+TISRSuqpZLVQXqLS5hVmZl70+3RsPEISMgoqLQUAKxQkPUwcTR04bgB5Xf3YABUV42kUC2sAyWl5JTpVb-dIg+j-IFNiEwnM-j4dLE4Jc9gc7jgUg94FJZIplC4ClNIGUKu1aiR+qhGhcrnCVsMql1ahMwOJke80V9Zu1RuNJrBitj8q96ajPqoZswgA

### 💻 Code

```ts
// Instance type defined as interface
interface AInstanceInterface { a: number };
const AInterface: { new(): AInstanceInterface } = function() {} as any;

function testInterface(x: AInstanceInterface | string) {
    x instanceof AInterface
    ? x  // AInstanceInterface
    : x; // string
}

// Instance type defined as object type
const AObjectType: { new(): { a: number } } = function() {} as any;

function testObjectType(x: { a: number } | string) {
    x instanceof AObjectType
    ? x  // { a: number }
    : x; // string | { a: number }
}
```

Note that the behavior is the same when using `if`/`else` statements instead of ternary expressions.

### 🙁 Actual behavior

The type narrowing behavior is different when the instance type is defined as an interface vs. as an object type. This feels wrong because in most cases object types and interfaces can be used interchangeably, and it's not clear why they would have different behavior in this case.

### 🙂 Expected behavior

The type narrowing behavior is the same for both `testInterface` and `testObjectType`.

**Comment by Zamralik** [comment]
It doesn't looks like a bug.

`{ a : number }` is not necessarily an instance of `AGood` or `ABad`, it can be any generic object that looks like it without having the class in its prototype chain. That's why there is no type narrowing.

If there is a bug, it's in `testGood()`. Not all `AInstanceInterface` would have `AGood` in their prototype chain, so it should not narrow the type to string in the false branch.

**Comment by butchler** [comment]
You're right, what I wrote as the expected behavior might not be the correct behavior. I don't have any strong feelings about what the behavior should be in this case, though. The main thing that surprised me and seemed like a bug was the fact that the behavior is different when using an interface or an object type. I'll update the title and description accordingly.

**Comment by butchler** [comment]
> `{ a : number }` is not necessarily an instance of `AGood` or `ABad`, it can be any generic object that looks like it without having the class in its prototype chain. That's why there is no type narrowing.

Does this mean that both cases are wrong, and `instanceof` should have no effect on the types at all in this case? In other words, should the type be `string | { a: number }` in both the true and false branch?

**Comment by Zamralik** [comment]
> 
> 
> > `{ a : number }` is not necessarily an instance of `AGood` or `ABad`, it can be any generic object that looks like it without having the class in its prototype chain. That's why there is no type narrowing.
> 
> Does this mean that both cases are wrong, and `instanceof` should have no effect on the types at all in this case? In other words, should the type be `string | { a: number }` in both the true and false branch?

No. In the true branch, it should be narrowed to `AGood` or `ABad` instance.

Let's make a clearer exemple. [Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIImAWzgGwFADeeyJyIcmEAXMgM5hSgDmA3HgL554I5y23IAChDDIsABxwRK4Aeiy5CxUuICuAIxzAEZCtToNmbZSTWbtyBAHsQ9KKoRgrUABTlKNO8wCUJ5EVJA5DAAC2BaADp3FABeXUo2QM5Obht6IQBRABUaYVE4gnj9ACIAMQgtAA9i5HZjAHp6zKzkABMrMitRELgANxQ8sRAxMAFxKC6ugE9xFAQe0DxgGGQXQWyh+jgQJCsVvN8A0kbkAHUIAHIcHDIIfqhkJhFgkOgIABpkKefQuDALgQAd1eUBQWRmEFoCEY4lEoVAAGsgZdrshcIC4FMBBAQK1kKpxH5rLYrFIIjgrEwXAADAAkBHWWSienYYgEcGQszA1O8bE4FVoECUgRO4NmUJhcLCICRQme4WQe2CEOQxRAd2gNRBHy+Px6-yB2uQgMuoMeVmYwSsRLSpIg5MpNIAkm0bBdRAiQFZAcb9S8FeFqZ9GbyOEA)

    interface Animal
    {
        name: string;
    }
    
    class Pet implements Animal
    {
        public name: string;

        public constructor(name: string)
        {
            this.name = name;
        }
    }
    
    const PET: Pet = { name: "Felix" };
    
    // PET do not have Pet in its prototype chain
    if (PET instanceof Pet)
    {
        // We'll never get there, yet that's where Typescript thinks we'll always end up
        console.log(`${PET.name} is a pet`);
    }
    else
    {
        // Typescript thinks Pet is of type "never" here, yet that's where we're going to
        console.log(`I don't know what this is`, PET);
    }

What is causing the error is that when you duck type an object to an existing class, Typescript trust it "too easily".

`const PET: Pet = { name: "Felix" };` should fail because Pet is a real class.
`const PET: Animal = { name: "Felix" };` should be valid because Animal is an interface and the object conform to it.
`const PET: Pet = { name: "Felix" } as Pet;` should be the only way to override Typescript distrust.

**Comment by fatcerberus** [comment]
What you seem to want is nominal typing.  To get that, just add a private property to your class.

**Comment by butchler** [comment]
Like I said in the description:

> Note that while this issue is related to type narrowing and instanceof, it is not about the fact that instanceof is a nominal-typing check while TypeScript is structurally typed.

The issue is not about nominal typing, only about the fact that the behavior is different when using an interface vs. an object type. I apologize for creating confusion by initially claiming that the behavior where the type is narrowed is the expected behavior. I've since updated the description and title to not claim any particular behavior as expected.

**Comment by andrewbranch** [comment]
I would demo it like this: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJLmvJyDey4BcyAzmFKAObIC+AUGAJ4AOKAKsygLy75GnkgqdWgBMICADZwoKCRDBoMsRBADCAexD8ArgjDqoRPCAgB3ABQBKIukjLs1ANyjxUmcjkL2LDVrK79Qx4TC2tkbxQnWhdJaVl5ZAAPGyUsFAAfEjJKZ2AYZHNE5FBSOBAkdXzbTBVfHT0DS1xaZFak52pkCAliFBwWtsTHZAB6EeQEdQBbJjjkMAALYGJaYTFY909kBiII5Ez+HNo8goZivzKK-Ii6-waoJv627Y6unr6B1oZhseRTYEW8yWKzoQA

The behavior seen on the interface side definitely looks unsound, but changing it now would be a breaking change and likely not worth the pain. The inconsistency is not a reason to change things per se—different code has different behavior, and while I generally agree that there’s not a great reason for these two things to exhibit different behavior, we need to evaluate any proposed change on the merits of the change itself.

**Comment by butchler** [comment]
> The inconsistency is not a reason to change things per se—different code has different behavior, and while I generally agree that there’s not a great reason for these two things to exhibit different behavior, we need to evaluate any proposed change on the merits of the change itself.

I completely agree. My goal in opening this issue was simply to point out the difference in behavior, not to propose a change.

For the case where this was causing us a problem, we simply used a user-defined type guard instead (using an interface was not an option because the instance type needed to use mapped types). It's a rare case and it's easy to work around even if it does happen, so I don't expect it to be worth spending much time trying to change the behavior.

Personally I'm just curious why there is a difference in behavior in this case, because understanding that might help fill some gaps in my knowledge about how TypeScript works.

**Comment by Zamralik** [comment]
> 
> 
> I would demo it like this: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJLmvJyDey4BcyAzmFKAObIC+AUGAJ4AOKAKsygLy75GnkgqdWgBMICADZwoKCRDBoMsRBADCAexD8ArgjDqoRPCAgB3ABQBKIukjLs1ANyjxUmcjkL2LDVrK79Qx4TC2tkbxQnWhdJaVl5ZAAPGyUsFAAfEjJKZ2AYZHNE5FBSOBAkdXzbTBVfHT0DS1xaZFak52pkCAliFBwWtsTHZAB6EeQEdQBbJjjkMAALYGJaYTFY909kBiII5Ez+HNo8goZivzKK-Ii6-waoJv627Y6unr6B1oZhseRTYEW8yWKzoQA
> 
> The behavior seen on the interface side definitely looks unsound, but changing it now would be a breaking change and likely not worth the pain. The inconsistency is not a reason to change things per se—different code has different behavior, and while I generally agree that there’s not a great reason for these two things to exhibit different behavior, we need to evaluate any proposed change on the merits of the change itself.

At the very least, I would see a stricter flag that disallows equating a generic object to be an instance of a class without an explicit "as" mention. `--noImplicitInstance` or something. As a flag, it would not compromise existing code relying on this quirk.

With it, those would raise an error
```ts
const CAT: Pet = { name: "Felix" };

const DOG: Pet = makeAnimal("Zeus");

function makePet(name: string): Pet
{
    return { name };
}
```

Those would not raise an error
```ts
const CAT: Pet = { name: "Felix" } as Pet;

const DOG: Pet = makeAnimal("Zeus") as Pet;

function makePet(name: string): Pet
{
    return { name } as Pet;
}
```

**Comment by fatcerberus** [comment]
@Zamralik That can already be accomplished by adding a private property to the class.

**Comment by Zamralik** [comment]
> @Zamralik That can already be accomplished by adding a private property to the class.

Which is basically the self imposed constraint "do not make a class when an interface is sufficient", but would not prevent mistakes from being made because TSC would not warn you that `instanceof` wouldn't work.

**Comment by andrewbranch** [comment]
> I'm just curious why there is a difference in behavior in this case

I looked at this with a few others on the team and nobody could quite remember or figure out where the difference comes from within a short amount of time, but we supposed there is probably an old, old PR that would explain it. I will say that it does kind of match my intuition of the subtle differences between object types and interfaces, where interfaces are just presumed to be more class-like. There is clearly not some super rigorous principle that we can appeal to in the abstract here—the example you came up with does look sort of surprising—but it is likely driven by heuristics that lend more useful type checking behavior to certain patterns in code that uses a lot of classes and interfaces. Coming up with a more specific answer would require a bit more spelunking into the `git blame` of the checker.

**Comment by butchler** [comment]
Thanks for taking the time to look into it 🙂

> I will say that it does kind of match my intuition of the subtle differences between object types and interfaces, where interfaces are just presumed to be more class-like.

That sort of makes sense, since the `class` syntax implicitly declares an interface type and not an object type (I think). This explanation is enough to satisfy my curiosity, personally. 👍

Feel free to close this ticket, or leave it open to use it for discussion.
