### ISSUE TITLE
typeError when trying to type check code in Intellij with TS 1.6 beta

### ISSUE THREAD

**Issue by sgronblo** [Microsoft/TypeScript#4617]
I did `npm install -g typescript@1.6.0-beta` and then I updated my compiler settings in Intellij to point to the lib directory that contains the `typescriptServices.js` file. Now Intellij shows me the following error:

```
Error:Error has occurred in the compile process TypeError: Object [object Object] has no method 'fileExists'
```

The "Console" tab gives me a bit more specifics about the error:

```
Compile file: /Users/samu/projects/PROJECTNAME/client/events/supervisorEvents.ts
Read file from disk /Users/samu/projects/PROJECTNAME/client/events/supervisorEvents.ts
Last modified 1441255436000 for /Users/samu/projects/PROJECTNAME/client/events/supervisorEvents.ts
Hashcode for file content /Users/samu/projects/PROJECTNAME/client/events/supervisorEvents.ts is 34921e1c2d054cdd0f6925ef36abb398
Creating source (compiling file)
error while compiling: TypeError: Object [object Object] has no method 'fileExists' TypeError: Object [object Object] has no method 'fileExists'
    at tryLoad (evalmachine.<anonymous>:35165:22)
    at Object.forEach (evalmachine.<anonymous>:880:30)
    at loadNodeModuleFromFile (evalmachine.<anonymous>:35161:23)
    at nodeModuleNameResolver (evalmachine.<anonymous>:35144:36)
    at resolveModuleName (evalmachine.<anonymous>:35134:41)
    at resolveModuleNamesWorker (evalmachine.<anonymous>:35411:113)
    at Object.map (evalmachine.<anonymous>:945:29)
    at resolveModuleNamesWorker (evalmachine.<anonymous>:35411:65)
    at processImportedModules (evalmachine.<anonymous>:35827:35)
    at findSourceFile (evalmachine.<anonymous>:35789:21)
```

It's entirely possible that Intellij is using some changed API incorrectly but I thought I would report this anyway. I really wanted to see if we can get the node_modules resolution working in TS1.6.

**Comment by vladima** [comment]
This is issue with IntelliJ - its implementation of TypeScript `CompilerHost` interface lacks `fileExists` and `readFile` methods that are used by module resolution code. I would suggest to file an bug in JetBrains issue tracker

**Comment by sgronblo** [comment]
Thanks for the info and the quick response, I will take it over to Intellij's bug tracker.

**Comment by timtian** [comment]
maybe you can try this 

https://github.com/timtian/webstorm-typescript/blob/master/ts-compiler-host-impl-1.6.fix.js

**Comment by trylas** [comment]
Where should I stick this file?

**Comment by Pro** [comment]
Same problem here. The fix above seems to solve it.
Put it into:
`JetBrains\WebStorm 10.0.4\plugins\JavaScriptLanguage\typescriptCompiler\ts-compiler-host-impl.js`
as statet in the readme: https://github.com/timtian/webstorm-typescript
