### ISSUE TITLE
regression in 4.5 - recursive conditional type with generic input fails to narrow

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#46171]
# Bug Report

### 🔎 Search Terms

4.5 recursive conditional type narrow generic

### 🕗 Version & Regression Information
4.5.0-dev.20211001

- This changed between versions 4.4.3 and 4.5.0-beta

### ⏯ Playground Link

- [4.4.3](https://www.typescriptlang.org/play?ts=4.4.3#code/C4TwDgpgBAggTnAhiAMhAdgc2ACwDwBQUxUaWuUEAHsBgCYDOU6ArgLYBGEcANESQGEWCDMHhIQlGvSboIAN24BtALoEAfFAC8UISPRiEyJQHIANhmw4TKqbXSNSl3P2IB+XcLijxyV1AAuWCNUZ3wyKx4oJTlFXigAOiS9bwNfEBV1AgJQSCgAdSQwdLwAFTsZKBZ0AGt0AHsAd3RVTR1S7IB6TuZ6ygR6uECASgJqMEHgKFzoADF6+rKKh1l2Ljg2gqKS9IjcMqjW9SA) 
- [4.5.0-dev.20211001](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211001#code/C4TwDgpgBAggTnAhiAMhAdgc2ACwDwBQUxUaWuUEAHsBgCYDOU6ArgLYBGEcANESQGEWCDMHhIQlGvSboIAN24BtALoEAfFAC8UISPRiEyJQHIANhmw4TKqbXSNSl3P2IB+XcLijxyV1AAuWCNUZ3wyKx4oJTlFXigAOiS9bwNfEBV1AgJQSCgAdSQwdLwAFTsZKBZ0AGt0AHsAd3RVTR1S7IB6Tu44ergg0vBoE3SI3DKo1pMoOnqIWXrgKAZEYABLBgAzSVxoAGN69AZgJHWDKBNquqaWlRMCajB+5dzoADF6+rKKh1l2LhwNoFIolMZhSbRTLqIA) 

### 💻 Code

```ts
type ArrayLength<
    Length extends number,
    CurrentArray extends never[]
> = CurrentArray['length'] extends Length
    ? CurrentArray
    : ArrayLength<Length, [never, ...CurrentArray]>

type WrapArray<T extends unknown[]> = T

//error: Type 'ArrayLength<T, []>' does not satisfy the constraint 'unknown[]'
export type Foo<T extends number> = WrapArray<ArrayLength<T, []>>
```

### 🙁 Actual behavior
```
error: Type 'ArrayLength<T, []>' does not satisfy the constraint 'unknown[]'
```

### 🙂 Expected behavior
no error

**Comment by ruohola** [comment]
Is this the same error as https://github.com/microsoft/TypeScript/issues/46183?

**Comment by DetachHead** [comment]
yep

**Comment by DetachHead** [comment]
why was my issue marked as a duplicate of the newer one lol
