### ISSUE TITLE
Unrecognized self-referencing @scope/package

### ISSUE THREAD

**Issue by Conaclos** [microsoft/TypeScript#46175]
# Bug Report

### 🔎 Search Terms

- self-referencing
- self-referencing package
- node12
- module resolution

### 🕗 Version & Regression Information

TypeScript 4.5 Beta and TypeScript Nightly

### 🙁 Actual behavior

Given the next package.json:
```json
{
    "name": "@scope/package",
    "type": "module",
    "main": "./compiled/src/index.cjs",
    "exports": {
        "import": "./compiled/src/index.js",
        "require": "./compiled/src/index.cjs"
    },
    ...
}
```
And the following tsconfig.json:
```json
{
    "module": "node12",
    ...
}
```
The following code does not compile:
```ts
import * as src from "@scope/package"
```
The obtained error is `Cannot find module '@scope/package' or its corresponding type declarations.`

### 🙂 Expected behavior

TSC currently compile self-referencing package that has unscoped names. TSC should also compile self-referencing [scoped packages](https://docs.npmjs.com/cli/v6/using-npm/scope/) such as `@scope/package`.

**Comment by IllusionMH** [comment]
do you have `exports` in `package.json` as required by Node.js?
https://nodejs.org/api/packages.html#packages_self_referencing_a_package_using_its_name

**Comment by Conaclos** [comment]
@IllusionMH Yes. I updated the issue to highlight this. Thanks.

**Comment by andrewbranch** [comment]
Also just checking that your `...` in `tsconfig.json` does not include `moduleResolution` (which is implied by `module` but can be overridden).

**Comment by Conaclos** [comment]
@andrewbranch
Yes this field is not present.
To be exhaustive, I have the following tsconfig:

```json
// tsconfig-base.json
{
  "compilerOptions": {
    // https://node.green/#ES2019
    // https://kangax.github.io/compat-table/es2016plus
    "lib": ["ES2019"],
    "module": "node12",
    "target": "ES2019",

    "noEmit": true,

    "sourceMap": true,

    "importHelpers": true,
    "newLine": "lf",
    "stripInternal": true,
    "useDefineForClassFields": true,

    "esModuleInterop": true,
    "importsNotUsedAsValues": "error",
    "isolatedModules": true,
    "preserveValueImports": true,

    "allowUnreachableCode": false,
    "checkJs": true,
    "exactOptionalPropertyTypes": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "strict": true
  }
}
```

```json
// src/tsconfig.json
{
  "extends": "../tsconfig-base.json",
  "compilerOptions": {
    "outDir": "../compiled/src",
    "noEmit": false,
    "emitDeclarationOnly": true,

    "composite": true,
    "declarationMap": true,

    "types": ["node"]
  },
  "include": ["**/*.ts"]
}
```
