### ISSUE TITLE
Parameter type detection for generic functions broken

### ISSUE THREAD

**Issue by nstuyvesant** [microsoft/TypeScript#46187]
# Bug Report

Using VS Code 1.60.2 and TypeScript 4.4.3. Given two typed functions...
```typescript
type NonGenericResult = (input: number) => number
export const returnNumber: NonGenericResult = (input) => input

type GenericResult = <T>(input: number) => T
export const returnWhatever: GenericResult = <T>(input) =>  <T> input
```
Hovering over the input parameter for the `returnNumber` function says its type is "number" (correct).
Hovering over the input parameter for the `returnWhatever` function says its type is "any" (incorrect).

### 🔎 Search Terms

parameter type generic

### 🕗 Version & Regression Information

TypeScript 4.4.3 - just noticed the problem today.

### 💻 Code

Code above is self-contained and reproduces the issue 100%.

### 🙁 Actual behavior

TypeScript did not recognize the parameter type when the function and function type used a generic.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/5770938/135763881-7e814dbb-acbb-49fd-bbb1-bb941bc4e851.png">

### 🙂 Expected behavior

Expected TypeScript to see input parameter in both functions as type "number" as it does for the first function...
<img width="678" alt="image" src="https://user-images.githubusercontent.com/5770938/135763906-3ebb1491-9844-41b6-897e-890d82adcca7.png">

**Comment by andrewbranch** [comment]
Functions with type parameters are not context-sensitive. You still get proper checking here—if you say `input: string`, that’s properly reported as not assignable to to `GenericResult`. But once you introduce type parameters to your declaration, your parameter types and return types are no longer eligible to be contextually typed.

**Comment by nstuyvesant** [comment]
OK, trying to wrap my head around this...

My actual use-case looks like this...
```typescript
import type { QueryResult } from 'pg'
import pg from 'pg'

const pgNativePool = new pg.native.Pool({
  max: 10,
  connectionString: import.meta.env.VITE_DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
})

type AcceptableParams = number | string | boolean

type PostgresQueryResult = (sql: string, params?: AcceptableParams[]) => Promise<QueryResult<any>>
const query: PostgresQueryResult = (sql, params?) => pgNativePool.query(sql, params)

type GetOneResult = <T>(sql: string, id: number | string) => Promise<T>
const getOne: GetOneResult = async <T>(sql, id) => {
  const { rows } = await query(sql, [id])
  return <T> rows[0]
}

const user = await getOne<User>('SELECT * FROM users WHERE id = $1;', 33)
// returns a User
```

My hope was to flag errors if someone tries calling getOne and passes something other than a string for the first parameter and string or number for the second.

Hovering over either of the two parameters for the function with the type parameter shows them having a type of any.

**Comment by andrewbranch** [comment]
The correct approach would be to manually annotate the parameters:

```ts
const getOne: GetOneResult = async <T>(sql: string, id: number | string) => {
  const { rows } = await query(sql, [id])
  return <T> rows[0]
}
```

It may _look_ redundant with the `GetOneResult` annotation, but it’s not—because of the `<T>` type parameter, the parameter types defined in `GetOneResult` don’t automatically flow into your parameter declarations.

**Comment by nstuyvesant** [comment]
Interesting... that was what I ended up doing. But since I was exporting the getOne function, TypeScript was bugging me to create a type declaration for it as well and that left me wondering what to do with the parameters there.
