### ISSUE TITLE
Refactoring `Move to a new file` removes comments in enum

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#46196]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### 💻 Code

```ts
export const enum CharCode {
	"/" = 47, // foo
	"a" = 48,
}
```

### 🙁 Behavior

Moving to a new file removes `// foo`, expected comment to remain

<img width="262" alt="Code_2021-10-04_10-39-19" src="https://user-images.githubusercontent.com/30108880/135820130-b321a405-2164-4f0c-85fc-8cff5ae13a66.png">

<img width="217" alt="Code_2021-10-04_10-39-27" src="https://user-images.githubusercontent.com/30108880/135820139-9d5e192e-f861-4a67-8b52-383101068a64.png">

**Comment by andrewbranch** [comment]
I’m going to lump this into #29972
