### ISSUE TITLE
Types inside a namespace disappear when the namespace is exported through HoC

### ISSUE THREAD

**Issue by cdpark0530** [microsoft/TypeScript#46194]
# Bug Report

### 🔎 Search Terms

namespace disappear, namespace lost

### 🕗 Version & Regression Information

`4.3.5`
also tested: `3.9.10`, `4.0.8`, `4.1.6`, `4.2`,  `4.4.3`

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about namespace

### ⏯ Playground Link

Couldn't use it as the issue occurs in a script importing another script.

### 💻 Code

```
// Child.tsx
import React from "react";

function Child(props: Child.Props) {
    return <>{props.name}</>;
}

namespace Child {
    export interface Props {
        name: string;
    }

    export const constant = "Hello, World!";
}

function hoc<C extends React.ComponentType<any>>(component: C) {
	return component;
}

export default hoc(Child);
```

```
// Parent.tsx
import Child from "./Child";

const constant = Child.constant; // Child.constant is visible
type childProps = Child.Props; // Child.Props is not visible
```

### 🙁 Actual behavior

Child.Props is not visible in `Parent.tsx`

### 🙂 Expected behavior

Child.Props is visible in `Parent.tsx` because I think it should be as Child.constant is visible in `Parent.tsx`.

**Comment by andrewbranch** [comment]
@DanielRosenwasser I know we’ve talked about this as a feature request before but I can’t for the life of me find anything to link it to. Tried searching for “function return namespace” but no luck.

**Comment by DanielRosenwasser** [comment]
I think any time we discuss namespaces being carried together with values, the feature is "associated types" which allow values' types to contain other types, effectively turning them into namespaces.

https://github.com/microsoft/TypeScript/issues/17588

**Comment by andrewbranch** [comment]
I looked at that issue and even searched “associated types” but that particular proposal is so complicated that I felt like there must have been a simpler proposal to link to 😅
