### ISSUE TITLE
error TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'esnext', 'commonjs', 'amd', 'system', or 'umd'... es2022 missing!

### ISSUE THREAD

**Issue by simllll** [microsoft/TypeScript#46198]
# Bug Report

I tested the new ts beta version, and set my module to es2022. Now one build fails due to the error:
error TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'esnext', 'commonjs', 'amd', 'system', or 'umd'.

Edit: this could be related to "[ttsc](https://github.com/cevek/ttypescript)", will close the issue as soon as I found the correct root cause.

### 🔎 Search Terms

dynamic imports, es2022

### 🕗 Version & Regression Information

new typescript beat (4.5), module set to es2022

### 🙁 Actual behavior

Compile fails

### 🙂 Expected behavior

Like in es2020 mode, it should work with es2022 too.

**Comment by MartinJohns** [comment]
The diagnostic error message was updated and the mention of es2022 is missing in yours: https://github.com/microsoft/TypeScript/pull/44656/files#diff-fdf3f532dc2d3188ad1c05c8c9e064d0aa4143b8ba09b8f3313a0243f0a43effR923

Have you tried it using the TypeScript compiler directly?

**Comment by simllll** [comment]
Yeah it seems related to the issue that npm does not recognize "3.5-beta" as an higher version of "typescript": ">=3.2.2". Therefore my monorepo setup installs a 2nd (older) version for ttsc right now. Sorry for the noise.
