### ISSUE TITLE
Inner types

### ISSUE THREAD

**Issue by FilipeBeck** [microsoft/TypeScript#46191]
# Suggestion

## 🔍 Search Terms
- inner types
- nested types

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A kind of "syntax sugar" to merge declarations. It is equivalent to using `namespace`. Some possibilities:

```typescript
/**
 * Classes and interfaces 
 */

class Listing <T> {
    inner interface Pagination {
        page: number
        totalPages: number
        records: T[]
    }
    // `Pagination` is implicitly `Pagination<T>` 
    constructor(private pagination: Pagination) {}
}

const aPagination: Listing<string>.Pagination = {
    // ...
}

/**
 * Functions.
 */

function fetch(method: fetch.Method) { // Maybe, just `fetch(method: Method)` is enough
    inner type Method = 'GET' | 'PUT' | 'POST'

    const request = // ...
}

const aMethod: fetch.Method = 'GET'


/**
 * Types.
 */
type Payload = Payload.User | Payload.Address { // Maybe, just `Payload = User | Address` is enough
    inner interface User {
        // ...
    }

    inner interface Address {
        // ...
    }
}

const aPayload: Payload = Payload.Address
```

- Maybe `inner` is not the better keyword name.
- Maybe a _access level_ for classes (public, protected, private).

**Comment by jcalz** [comment]
Seems like #7061

**Comment by tjjfvi** [comment]
Also #17588

**Comment by MartinJohns** [comment]
Also somewhat related: #41470.

---

I find the idea of "local" types declared within the implementation body to leak outside extremely unpleasant and disturbing. I hardly see any benefit and a lot of complexity.

And unfortunately the issue template for feature requests was not filled out.
