### ISSUE TITLE
GLOBAL NETWORK MARKETING

### ISSUE THREAD

**Issue by CharlesKelly759** [microsoft/TypeScript#46226]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Documentation Link

Help is on the way
http://www.CharlesKellyCompany.Paypal.com
![CHARLES E KELLY   COMPANY](https://user-images.githubusercontent.com/91978603/136090564-d15ef78e-0777-4ba7-8797-21f75c3809e0.jpg)

**Comment by orta** [comment]
wanted: `lib.b.sa`
