### ISSUE TITLE
When using Omit, (TypeA | TypeB) & {...} doesn't work as expected anymore

### ISSUE THREAD

**Issue by RowanDZ** [microsoft/TypeScript#46220]
# Bug Report

### 🔎 Search Terms

Omit, OR

### 🕗 Version & Regression Information

I tried multiple versions on the playground, but all(?) of them have it.

If using Omit, an OR statement doesn't work as expected anymore.
(sorry, I don't know how to call the `(TypeA | TypeB)` part)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.3#code/C4TwDgpgBAggQgV2AOQPbDlAvFA3lAQwC4oA7BAWwCMIAnAbiioH4TSIA3OqAXwChQkKHEQp0MbHkKsynOoyptKNWrz4Dw0ACoQAzsEkAKeEjQYoAH2GizMAJRQAZFIDGS6vKgATdysYRfbn4+F1RSfShgPWAARhIAeQoAS2AAHh19ABooACIIHIA+SVw+KEISGOyAeiqoAElkAGF4gCUWgFFGrRIAdwALOmgk3UiBqDpaVFpmGfrCCm8IADMk0lWAcygAAwItwlIvbd3SphIAJkyTtygAZkuynygAFkvg0PCDKP0zkgyDHBKZWIUEqUBqUGabU63XGtEmtF+mhGqCWUDAk0gtFAUAA5AQcYRaENSKEKGACMAklQADYQAB0UC0mlx5A8tAJwzI6EIul0SXWpAINOgwFQkWZOIQB2WqwgXhxdJOiigFyuJDuJ0eLz4wSAA)

### 💻 Code

```ts
type AButNotB = { a: number; b?: never }
type BButNotA = { a?: never; b: number }

type Test = (AButNotB | BButNotA) & { c: number; d: number; e: number }

const test1: Omit<Test, "e"> = {
  a: 1, // INCORRECT: where is the error??? `a` and `b` are both defined
  b: 2,
  c: 3,
  d: 4,
}

const test2: Test = {
  a: 1, // CORRECT: gives error
  b: 2,
  c: 3,
  d: 4,
}

```

### 🙁 Actual behavior

No error for `test1`

### 🙂 Expected behavior

Error like `test2`

**Comment by MartinJohns** [comment]
Omit uses `keyof`, which only returns common properties for union types. Works as expected.

**Comment by RowanDZ** [comment]
Hmm, okay, is there any way to accomplish what I expect then?

**Comment by MartinJohns** [comment]
Look up "distributive omit".

**Comment by RowanDZ** [comment]
Clear, thank you for the detailed answer ! :)
