### ISSUE TITLE
Type Guards Don't Work on Parent Generic Object

### ISSUE THREAD

**Issue by GeoMarkou** [microsoft/TypeScript#46233]
# Bug Report

### 🔎 Search Terms
type guard generic parent object

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generic object type guard

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211005#code/JYOwLgpgTgZghgYwgAgCIHsDmyDeyDu66MAXAM5hSjYC+A3AFCiSyIoDCcYuyAthOnzlK1ZPQZgAngAcUAQRDBecADbIAvGiwAfTmEZNw0eEmQAJdAFcyKADwAVAHw84i5SpLJ7dMRJkoMTAtrFE1gm1tAx0YYSxAEMGB0EGQABSh0JDIyQPCUAAoACysbElySiABKXHEGBGSKZGKQkjzbBSVVZ00cBmR+5FdOj2Q4gBMIGFAIMcGyQZBJBlrgGGR8gHJCYg3kUCaKgDoh92regeQAekvkAHUUAGsQQWQwQpQpWWRiA5DX9GQACMUG0okDLNw3sB5hRgCo1NAMlAyH0BulMhBsuUQkUKpUDBdrncIMAoGMVJJXoVocgxuhMSANtxEegoKj+uisjksHl8ucLgMTqpPM0bMc3Kp2WJ8csgA)

### 💻 Code
```ts
interface Dog { woof:string };
interface Cat { meow:string };
type Animal = Dog|Cat;

interface House <T> { animal: T; }
type DogHouse = House<Dog>;
function ProcessDogHouse (house:DogHouse) {};

const house:House<Animal> = {
    animal: undefined as any
};

if ('woof' in house.animal) {
    // We know the type to be House<Dog> but this still errors
    ProcessDogHouse(house);

    // Weirdly this doesn't error
    ProcessDogHouse({
        animal: house.animal
    });
}
```

### 🙁 Actual behavior
Generic types can't be narrowed by checking their child objects.

### 🙂 Expected behavior
Should be able to narrow a generic object by the types of its children.

**Comment by MartinJohns** [comment]
Here's a recent duplicate that's still open: #42384
