### ISSUE TITLE
Overload the sort() function depending on type of array elements

### ISSUE THREAD

**Issue by moonman239** [microsoft/TypeScript#46232]
# Suggestion

By default, TypeScript should know how to sort an array of numbers, strings, etc.
TypeScript should provide overloads for each such type that allow us to specify whether we want ascending or descending order, so that we don't need to specify a comparator. Just like we don't in some other programming languages like Python.

For example,
[1,5,6,2].sort(ascending=true);
would return
[1,2,5,6].

sort overload

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions.
The whole IDEA is to implement somewhat type-dependent overloads, so not sure if this item should be checked.
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

By default, TypeScript should know how to sort an array of numbers, strings, etc.
TypeScript should provide overloads for each such type that allow us to specify whether we want ascending or descending order, so that we don't need to specify a comparator. Just like we don't in some other programming languages like Python.

I'm thinking something like:

Array<number>.prototype.sort(order=true) = super.sort((x,y) (x > y && order) ? 1 : -1);

as example syntax that could be implemented somehow.

Or just have a bunch of type-dependent sorting functions and have TS decide which one to use at runtime.

## 📃 Motivating Example

Right now, if I want to sort [1,2,10,5], I have to do something like [1,2,10,5].sort((x,y) => x > y ? 1 : -1);
Otherwise, TS treats the numbers like strings, and I get an invalid result.

**Comment by jcalz** [comment]
Note that the above issues are only related in that they attempt to resolve pitfalls of calling `sort()` without a comparator for non-`string` arrays.  They do so by merely issuing a compiler warning on such a call in TypeScript; no runtime behavior is changed.

On the other hand, *this* suggestion will almost certainly be declined.  You are specifically asking for runtime functionality, and it's more or less set in stone now that such things would have to first be introduced in JavaScript (at least stage 3 of [the tc39 process](https://tc39.es/process-document/)) before they would be supported by TypeScript.
