### ISSUE TITLE
4.5 beta - module nodenext appears to break resolution when combining package.json exports and @types

### ISSUE THREAD

**Issue by JacobLey** [microsoft/TypeScript#46243]
# Bug Report

### 🔎 Search Terms

4.5 beta
module resolution nodenext
@types
package.json exports
Could not find a declaration file for module

### 🕗 Version & Regression Information

Typescript: typescript@next (4.5.0-dev.20211006)
Node: v14 AND v16
Npm: v6 AND v7

- This is an unexpected failure introduced by 4.5 beta using module=nodenext

### 💻 Recreation Link

(Was easier to make a mock repo than manage dependencies in ts playground)
https://github.com/JacobLey/typescript-issue-recreation

See readme, but effectively run `npm i` + `npm run recreate-issue`.

### 🙁 Actual behavior
When using module=nodenext, typescript fails to find type definitions for `yargs/helpers`.

Emitted error is:
```
broken/yargs/index.ts:2:25 - error TS7016: Could not find a declaration file for module 'yargs/helpers'. '/Users/jacobley/typescript-issue-recreation/node_modules/yargs/helpers/helpers.mjs' implicitly has an 'any' type.
  If the 'yargs' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/yargs'

2 import { hideBin } from 'yargs/helpers';
                          ~~~~~~~~~~~~~~~


Found 1 error.
```

### 🙂 Expected behavior

When the proper `@types/yargs` is installed, typescript should be able to find (or fall back on) type definitions for `yargs/helpers`

### Current Understanding (Guess  ¯\\_(ツ)_/¯)

yargs correctly uses the package.json exports to declare what files are outputted. https://github.com/yargs/yargs/blob/main/package.json#L15

However they do not emit typings with the package itself, and definitely do not provide a custom `types` condition in exports (and it is unreasonable to expect that to exist, given the feature has existed for less than a week).

Instead typescript users should install the `@types/yargs` package, which is _usually_ handled gracefully.

However it appears that because typescript discovers a declaration for `/helpers` in yarg's package.json exports, it simply tries to find the types there, fails, and gives up.

Pre-4.5 (or module != nodenext) typescript would have ignored package.json entirely and fallen back on @types/yargs.

Expected/ideal behavior would be for typescript to continue falling back on @types when package.json exports are declared but do not point to a typescript declaration. Although if yargs _were_ to declare types in their package.json exports, that should be selected first.

My current workaround is to explicitly declare this mapping using the `paths` attribute of tsconfig (see working example from recreation).

It is also worth noting that importing the root `yargs` package appears to work just fine. Despite that being declared in package.json exports as well. I assume there must be some special handling for root/index imports that correctly falls back on @types.

Also worth noting that I have been unable to trigger vscode (which is configured to use locally installed version of typescript) to recreate this issue. It appears to correctly find the typings for `yargs/helper` everytime (provided @types/yargs is installed)

**Comment by JacobLey** [comment]
I made a similar comment in the recreation README but worth mentioning here.

My usage of `yargs` is simply because it is the first package I ran into with this issue while testing out 4.5 beta. It is a very popular package so I suspect this issue could/would pop up for many users when 4.5 is officially released.

If my diagnosis is correct, this is by no means an issue with yargs itself, and could be recreated with any other package that:
1) Uses package.json `exports` field
2) Exports a file under some path (not just root/index)
3) Do not include native typings and rely on something like @types

**Comment by weswigham** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56495 should update the current version of the `@types/yargs` package to provide proper esm entrypoints to mirror `yargs` itself. It might take a bit to merge, since we have to check that the DT automation can handle the changes.

**Comment by JacobLey** [comment]
It seems that ESM resolution is inconsistent across packages though.

Another (cherrypicked) example is [@types/config](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/config) which exposes a submodule [defer](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/config/defer.d.ts)

`import { deferConfig } from 'config'` works just fine for me with `nodenext`.

Neither that type declaration nor the [original package](https://github.com/lorenwest/node-config/blob/master/package.json) use the `exports` field.

So it seems that by given logic, if the root package uses `exports`, then the `@types/package-name` must also use package.json `exports`?

While I am generally supportive of updating packages/types to properly use the `exports` field, this seems like an unnecessary restriction that might break for more packages?
Why not use the same resolution methods for `@types/yargs` as for `@types/config`?

**Comment by weswigham** [comment]
From esm you'd need to import `config/defer.js` - esm resolution does not add extensions for you.

**Comment by weswigham** [comment]
I can confirm that post-https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56495, the version of `@types/yargs` we have published now has esm entrypoints and proper `exports` map entrypoints looking at them, and everything seems to be in working order. There's probably a pile of other DT packages which need updating to better mirror their source packages in this way (I think we generated a list a few weeks ago), but I don't think this is the issue to track that effort in, so I'm going to chalk this one up as done.
