### ISSUE TITLE
Type '(arg: string) => string' does not satisfy the constraint '(...args: unknown[]) => unknown'

### ISSUE THREAD

**Issue by jbmanning** [microsoft/TypeScript#46242]
# Bug Report

### 🔎 Search Terms

function generic, T extends (...args: unknown[]) => unknown

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [generic function types? Didn't see much about this]

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211006#code/GYVwdgxgLglg9mABMMB1GUAWBVMBrMOAdzAB4AVAMSQFMAPKGsAEwGdEAKAOh4EMAnAOasAXInAFiYANoBdAJSIAvAD5x+QiRUcUYqmAA0iAA68AngBs4vZmIAKA3gFsajfqwrUV0gAwKxAEquIPxg5GbGNJ5gagDeAFCIiAD0yYjkmDDsEHD8-DTQFmaIzHA07IRQiES5eImIOWCscBY0XFaCHKaW1sxczDTAMGAYNEUA+qXlYFDj9FlQ8gDc9Vj8xIhgNESIAKJ5uRwARACMR-LxAL7xoJCwCMhoGJgAgmBm0Yj0jCzs3HxCUSIXjvOSKVTA97aXTpahGbpWGz2RwuNwefTePzyQLBULhSLROL1VKIF4WKxEdhYLLiVi8QQ0Iw0ABuTEQWDgIEEmEhxRyIAszEQACMaF8GEwBkLgOsnMCSjBgMAaPkZuyIjR6o1mq12nBOgjev1BsNRhMpqwZnM6AtlqtMOsdlsdvt1vxjmcLtcbuBoPAkE4zNQOAJBGJWFB+MNBNjEBGo2BBIhYoh8lAQkgjkdEN6SfixQByCSaMAFxA0yrA1isGCCMC8YWtdlwdWRRAF+PRssAfl73ZuTywuEkJA4gbhiCzFzzGvbIaE4cj0fBak7ibLFs2cCqdNgrGAxSwYu1kd4wyqBf+XFDQOLUjByjUd5IPb7A-QQ40UlIUA1cGAiDjjEY5BoYk7nPE8QkgAwrk+SFMUvDViqUBUhE0bvs8bxmCBE5TphWDYbhYEnBckFAA)

### 💻 Code

```ts
function fnWithUnknown<TFn extends (...args: unknown[]) => unknown>(fn: TFn, payload: Parameters<TFn>[0]): ReturnType<TFn> {
  // This correctly does not work
  console.log(payload.definitely_doesnt_exist);
  throw new Error("1")
}
function fnWithAny<TFn extends (...args: any[]) => any>(fn: TFn, payload: Parameters<TFn>[0]): ReturnType<TFn> {
  // Allows this usage, even though any could be extended from a different type
  console.log(payload.definitely_doesnt_exist);
  throw new Error("1")
}

function myFn(arg: string): string { return "" }

// Type 'unknown' is not assignable to type 'string' ????
fnWithUnknown(myFn, "")
// Type '(arg: string) => string' does not satisfy the constraint '(...args: unknown[]) => unknown' ????
fnWithUnknown<typeof myFn>(myFn, "")

// Correctly asserts typing
fnWithAny(myFn, "")
fnWithAny(myFn, 1)


```

### 🙁 Actual behavior

When passing a func into a generic parameter of `TFn extends (...args: unknown[]) => unknown`, TS complains that type type of the function does not satisfy the constraint of unknown. 

Using `any` instead of `unknown` allows usage inside the generic when that is not the intended behavior. 

### 🙂 Expected behavior

No error, this code is not assigning an unknown value to a string, it is assigning a string value to unknown, which should be allowed. 

Alternatively, if there are other patterns to accomplish a generic function property those would be appreciated

**Comment by DanielRosenwasser** [comment]
This is working as intended - under stricter settings, the parameters are compared in the opposite direction, and `unknown` isn't assignable to `string`. This makes sense, because `...args: unknown[]` says that it's safe to call that function with anything. `...args: any[]` bypasses that restriction. I would think the only safe-ish alternative is `...args: never[]` (which I'll admit even I have trouble reasoning about).

**Comment by jbmanning** [comment]
Huh... That really stumps me, I guess what `extends (...args: unknown[]) => unknown` is saying is that it accepts a function that accepts an unknown set of parameters, which isn't what the goal is. I thought the generic would be able to increase the specificity of the extended condition..? Or I'm not sure I totally understand how `extends` works in this case.

Is there a more intended way of accomplishing this? Or is this just an uncommon use-case? *(`(...args: never[]) => any` does seem to work though)*
