### ISSUE TITLE
Unhelpful error message when `interface ... extends number`

### ISSUE THREAD

**Issue by Mr-Andersen** [microsoft/TypeScript#46246]
# Bug Report

### 🔎 Search Terms

interface extends only refers to a type

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about interface extension

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211006#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgWWAGcjMBzYASQBM5RUlqi4kBXAWwCM04BvAXyA)

### 💻 Code

```ts
export interface MessageId extends number {}
```

### 🙁 Actual behavior

error TS2693: 'number' only refers to a type, but is being used as a value here.

### 🙂 Expected behavior

Informative error about why an interface cannot extend `number` (or `string` -- the error is the same besides the type name)

**Comment by younes-io** [comment]
I would think of a message like: `an interface cannot extend a primitive type like 'number'; an interface can only extend named types and classes`

What do you think?

**Comment by HarsheetKakar** [comment]
I was actually working on it, sorry I forgot to mention that earlier

**Comment by charan1998** [comment]
Anyone working on this? Or can I take this up?

**Comment by JoelFickson** [comment]
Was this issue closed? I wanna take it.

**Comment by bentongxyz** [comment]
Hi there, if this is not being actively worked on right now, may I give this a try?
Thanks!

**Comment by JCalmCrasher** [comment]
Hi, @RyanCavanaugh I'm new to TypeScript; I'll like to give this a try.

Thanks.

**Comment by maross3** [comment]
I opened a draft PR for this issue: https://github.com/microsoft/TypeScript/pull/49208
