### ISSUE TITLE
"may be converted to an ES6 module" is a lie

### ISSUE THREAD

**Issue by felix9** [microsoft/TypeScript#46240]
# Bug Report

### 🕗 Version & Regression Information

tsc 4.4.3
vscode 1.60
webpack 5.57.1

### 💻 Code

file webpack.config.cjs:
```js
/** @type {import("webpack").Configuration} */
const config = {};
module.exports = config;
```

### 🙁 Actual behavior

vscode shows the hint
> File is a CommonJS module; it may be converted to an ES6 module. ts(80001)

which is a lie, since the file is a .cjs module, and webpack doesn't have support for loading config from an .mjs module.

I don't see any way to squelch that lie, other than disabling JS hints entirely, which is undesirable because the JS hints are otherwise quite helpful.

**Comment by sidharthv96** [comment]
https://github.com/microsoft/TypeScript/blob/08361e3d3c1e5fe2e1d19267d72c8292345c695e/src/services/suggestionDiagnostics.ts#L10-L13

@DanielRosenwasser Should I raise a PR adding necessary checks in here?

**Comment by andrewbranch** [comment]
@sidharthv96 looks like the right place to me 👍
