### ISSUE TITLE
Definition of Array.isArray() seems to be broken

### ISSUE THREAD

**Issue by headcr4sh** [Microsoft/TypeScript#4624]
When trying to use the definitions for ES6 I run into the following error.

Steps to reproduce:
```
user@host$ tsc lib/lib.es6.d.ts 
lib/lib.es6.d.ts(1168,28): error TS1005: ';' expected.
lib/lib.es6.d.ts(1168,31): error TS1005: ';' expected.
lib/lib.es6.d.ts(1168,41): error TS1005: '(' expected.
lib/lib.es6.d.ts(1169,26): error TS1005: '(' expected.
lib/lib.es6.d.ts(1170,1): error TS1128: Declaration or statement expected.
```

The following code block seems to cause the issues:
```typescript
interface ArrayConstructor {
    new (arrayLength?: number): any[];
    new <T>(arrayLength: number): T[];
    new <T>(...items: T[]): T[];
    (arrayLength?: number): any[];
    <T>(arrayLength: number): T[];
    <T>(...items: T[]): T[];
    isArray(arg: any): arg is Array<any>;
    prototype: Array<any>;
}
```

... obviously ```isArray(arg: any): arg is Array<any>;``` should be replaced by ```isArray(arg: any): boolean;```

The following files need to be patched (they all contain the malformed expression):
  * lib/lib.core.d.ts
  * lib/lib.core.es6.d.ts
  * lib/lib.d.ts
  * lib/lib.es6.d.ts

**Comment by vladima** [comment]
what version of TypeScript compiler do you use. Return type in form `arg is Array<any>` is a [user-defined type guard function](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#user-defined-type-guard-functions) which is a new feature of TypeScript 1.6

**Comment by headcr4sh** [comment]
Oh. My bad. I didn't know about "use-defined type guard functions".

Just to clarify:
Does it make sense to include this IMPLEMENTATION-SPECIFIC detail (?) in a typings (.d.ts) file?

**Comment by vladima** [comment]
Can you please elaborate why using officially [accepted] (https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#68-type-guard-functions) (TODO in spec will eventually go away) TypeScript syntax in [TypeScript declaration source files] (https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#111-programs-and-source-files) is implementation-specific detail?

**Comment by headcr4sh** [comment]
Oh. Sure.

Array.isArray is defined as a method that will return either "true" or "false" (it depends upon the input parameter, whether "true" or "false" will be returned).
```arg is Array<an>``` on the other hand is a (TypeScript)-implmenentation that could be used as a polyfill / drop-in-replacement for JS runtimes that lack the existence of Array.isArray, right?
