### ISSUE TITLE
Statement to fallthrough in switch cases with --noFallthroughCasesInSwitch

### ISSUE THREAD

**Issue by FilipeBeck** [microsoft/TypeScript#46251]
# Suggestion

## 🔍 Search Terms

- fallthrough keyword
- fallthrough statement 
- fallthrough instruction
- fallthrough syntax

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I like the `--noFallthroughCasesInSwitch` option, but I always end up having to disable it because inevitably I need to fallthrough in a _switch case_. It would be nice to be able to explicitly allow this when necessary. A `fallthrough` statement (like in [Swift](https://docs.swift.org/swift-book/ReferenceManual/Statements.html#ID443)) would solve this problem.

```swift
switch (step) {
  case 1:
    console.log("step-one")
  break

  case 2:
    console.log("step-two")
  fallthrough // No error with --noFallthroughCasesInSwitch enabled
 
  case 3:
    console.log("step-three")
  break

  default:
    console.log(step)
}
```

Constraints:
- Must be the last statement in a _case block_ (to avoid violation of _design goals_).
- Must have the `--noFallthroughCasesInSwitch` enabled (or no?).

__EDIT - 2021/10/07:__
- I also thought about using just `fall`.
- The option `--noFallthroughCasesInSwitch` can get weird with this feature. Maybe, a new option named `noImplicityFallthroughCasesInSwitch` can be more semantic and avoid confusion.

**Comment by aaamenezes** [comment]
Good

**Comment by andrewbranch** [comment]
We don’t add expression-level syntax these days. In my opinion, we never should have added that compiler flag and left it to linters. Putting our money where my mouth is: we don’t use the flag in the TypeScript codebase, but rather use an eslint rule which allows fallthrough with a comment: https://eslint.org/docs/rules/no-fallthrough

**Comment by FilipeBeck** [comment]
@andrewbranch Thanks for the clarification.

**Comment by yjfvictor** [comment]
TypeScript should add an explicit `[[fallthrough]]` statement like this:

https://en.cppreference.com/w/cpp/language/attributes/fallthrough.html
