### ISSUE TITLE
Incorrect Types in Monorepo

### ISSUE THREAD

**Issue by JanThomas118** [microsoft/TypeScript#46257]
# Bug Report

I am using a monorepo and i have a library (history) in two versions. Yarn hoists the newer version (v5) (which already has typescript definitions) and the @types package of the older version to the root node_modules. 
The older library (v4) is in the node_modules of package-b (see picture)

In package-b package.json the old library (no definitions included) version and the correct types package is listed.
When compiling package-b typescript uses the the typings from the newer package (v5) in the root (incorrectly) which makes the compilation fail.

"error TS2305: Module '"history"' has no exported member 'createLocation'"
createLocation is exported in the definition file of history v4. It is not exported in v5

![grafik](https://user-images.githubusercontent.com/35668921/136388524-2c9d9472-5571-470f-95a3-010a577613c0.png)

Output with --traceResolution: https://gist.github.com/JanThomas118/dc6269806b363a73a578a6a576d2cb03

### 🔎 Search Terms

Monorepo
Typings
Module Resolution
Incorrecy dependency

### 🕗 Version & Regression Information
I checked this in typescript 4.4.3 and 3.9.10 (!)

### 💻 Code
https://github.com/JanThomas118/Typescript_bug

-Clone this repo
-run "yarn set version berry"
-run "yarn install"
-run "yarn tsc packages/package-b/index.ts"
-> the compilation fails

### 🙁 Actual behavior
"error TS2305: Module '"history"' has no exported member 'createLocation'"
The Code doesnt compile because the incorrect typings are used

### 🙂 Expected behavior
The code compiles because typescript uses the typings i specified in my package.json

Typescript resolves modules correctly

**Comment by andrewbranch** [comment]
The compiler doesn’t know anything about which version of `history` is which. When you try to resolve `history` in `package-b`, we’ll do something like (highly simplified):

1. Look in `typingsrepo/packages/package-b/node_modules/history` - no types
2. Look in `typingsrepo/packages/package-b/node_modules/@types/history` - doesn't exist
3. Look for `typingsrepo/packages/node_modules` - doesn’t exist
4. Look for `typingsrepo/packages/history` - found types ✅ 

Trying to match up v4 to v4 and v5 to v5 just isn’t part of the resolution algorithm. It’s up to you and your package manager to put things in a place where TypeScript can distinguish between them.
