### ISSUE TITLE
tsc outputting extra unwanted directory

### ISSUE THREAD

**Issue by Ascendus** [microsoft/TypeScript#46252]
I'm trying to use `tsc` to compile some TypeScript files within the `src` folder into the `dist` folder. However, the issue is that `tsc` creates a new `src` folder inside the `dist` folder instead of just the contents inside the `src` folder. Here is an image of the directory: 
![image](https://user-images.githubusercontent.com/72182515/136321517-711d38ce-e0cb-406f-bb4b-08b330b5e555.png)

This is what my `tsconfig.json` currently looks like:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2018",
        "outDir": "dist",
        "lib": [
            "ESNext",
            "ESNext.Array",
            "ESNext.AsyncIterable",
            "ESNext.Intl",
            "ESNext.Symbol",
            "DOM"
        ],
        "sourceMap": false,
        "inlineSourceMap": true,
        "resolveJsonModule": true,
        "inlineSources": true,
        "incremental": true,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "include": [
        "src/**/*",
    ],
    "exclude": [
        "node_modules"
    ]
}
```

This is what does `tsc` does:
![image](https://user-images.githubusercontent.com/72182515/136321720-efba5175-df1c-4e02-96dc-c77937f8e850.png)

And this is what I would like `tsc` to do:
![image](https://user-images.githubusercontent.com/72182515/136321811-6057cd4d-4913-4484-bcb2-7c8512f5d492.png)

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by andrewbranch** [comment]
Sounds like you might want `rootDir` though
