### ISSUE TITLE
jsx tagName this is not treated as string currently

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#46275]
# Bug Report

### 🔎 Search Terms

jsx this

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.4.3 and 4.4.3
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DwQwBA9AfA3AsAKGAFwBYEsDOlaOAQRxiA)

### 💻 Code

```tsx
<a />;
<this />;
<A />;
```

### 🙁 Actual behavior

```js
"use strict";
React.createElement("a", null);
React.createElement(this, null);
React.createElement(A, null);
```

### 🙂 Expected behavior

```js
"use strict";
React.createElement("a", null);
React.createElement("this", null);
React.createElement(A, null);
```

[User-Defined Components Must Be Capitalized](https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized)

**Comment by andrewbranch** [comment]
Our behavior matches the official Babel transform here. I would encourage you to file an issue upstream clarifying the expected behavior. If Babel changes what they do, we’ll follow suit, but we’re not going to spearhead this one.
