### ISSUE TITLE
Would be nice to have multiple constructors

### ISSUE THREAD

**Issue by evilprince2009** [microsoft/TypeScript#46289]
# Suggestion

I usually write C# almost all the time. It would be nice if TypeScript supports multiple constructor like C# or Java. I know porting multiple constructors in TS and transpile it down to JS is not an easy thing. But I hope we'll have this feature in TS.

**Comment by FilipeBeck** [comment]
@evilprince2009 Your suggestion will be declined. It does not conforms with:

> This could be implemented without emitting different JS based on the types of the expressions

I have already created some issues suggesting this type of behavior and they were all rejected. You can do:
```typescript
class Foo {
  private value: number

  constructor(value: number)
  constructor(value: string)

  constructor(value: number | string) {
    if (typeof value === 'string') {
      value = Number(value)
    }

    this.value = value
  }
}

new Foo(42)
new Foo('42')
```

[Playground code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oAcBOBLAbmAC4Cm0hIAriQFzQB2lAtgEYnarrTDz0RHZKwIvGwAKCtTqNW7AJRcefAUJHjJtaPzz0A5gsW9tq0RLBVNMttmgAfLQNx65KLhlwAzaGKIBPTCTwXhrQALzh0ADk2k66kS5oGEnk5tRh0AByzNZmFgrJAL6cyUQAFrgQAHQhoSkWXEVFqPQkAO5wiGIALABMCi3tCPBikb3xQA)

This is how overload works in Typescript. The compiler will strip the two constructors without body.
