### ISSUE TITLE
Seemingly false alerm in monorepo: This syntax requires an imported helper but module 'tslib' cannot be found.

### ISSUE THREAD

**Issue by vilicvane** [microsoft/TypeScript#46288]
# Bug Report

The project uses yarn workspaces and has many packages with structures like:

```
- node_modules/
- package.json
- packages/
   - app/
     - node_modules/ 
     - package.json
   - server
     - node_modules/
     - package.json
```

In my case "tslib" is added to every relevent nested package.json but obviously it's only present under root `node_modules/`.

### 🕗 Version & Regression Information

This changed between versions 4.4.3 and 4.5.0-beta

### 💻 Code

```ts
import * as ReactDOM from 'react-dom';
```

### 🙁 Actual behavior

```
packages/app/src/program/main.tsx:3:1 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.

3 import * as ReactDOM from 'react-dom';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### 🙂 Expected behavior

No error.

---

Let me know if a repro is needed.

**Comment by vilic** [comment]
https://github.com/vilic/bug-repros/tree/typescript-46288

**Comment by vilic** [comment]
That seems to have fixed the problem, thanks!
