### ISSUE TITLE
Trim trailing whitespace in d.ts output

### ISSUE THREAD

**Issue by jedmao** [Microsoft/TypeScript#4629]
Here's a scenario in which trailing whitespace is not trimmed in d.ts output, specifically when adding jsdoc-style comments above each arg with line breaks in-between:

```ts
export class Point {
	constructor(
		/**
		 * The x coordinate.
		 */
		public x: number,
		/**
		 * The y coordinate.
		 */
		public y: number
	) {
		
	}
}
```

The generated output has spaces after each argument's comma that has another argument after it. In this case, only the `x` arg has the space after the comma:

```ts
define(["require", "exports"], function (require, exports) {
    var Point = (function () {
        function Point(
            /**
             * The x coordinate.
             */
            x, <-- trailing whitespace!
            /**
             * The y coordinate.
             */
            y) {
            this.x = x;
            this.y = y;
        }
        return Point;
    })();
    exports.Point = Point;
});
```

See the result on the [TypeScript Playground](http://www.typescriptlang.org/Playground/#src=export%20class%20Point%20%7B%0A%09constructor(%0A%09%09%2F**%0A%09%09%20*%20The%20x%20coordinate.%0A%09%09%20*%2F%0A%09%09public%20x%3A%20number%2C%0A%09%09%2F**%0A%09%09%20*%20The%20y%20coordinate.%0A%09%09%20*%2F%0A%09%09public%20y%3A%20number%0A%09)%20%7B%0A%09%09%0A%09%7D%0A%7D%0A).

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by DanielRosenwasser** [comment]
@yuit and I spent a good bit of time looking into alternative approaches, and while we got something that works decently, the gain seems relatively marginal compared to the hoops we had to jump through.

I think that overall this is easily amended by a pretty-printer or minifier.
