### ISSUE TITLE
Enum object keys pollution when referenced by Map

### ISSUE THREAD

**Issue by godenji** [microsoft/TypeScript#46299]
# Bug Report

When setting a Map that references an Enum in its type signature, the enum's object properties are modified such that the map's variable inexplicably becomes the last entry in properties array (see example below) 

### 🕗 Version & Regression Information

TS 4.3.5

### 💻 Code

```typescript
export enum RosterPosition {
  LW = 'Left Wing',
  RW = 'Right Wing',
  C = 'Center',
  LD = 'Left Defense',
  RD = 'Right Defense',
  G = 'Goalie'
}

export namespace RosterPosition {
  export const all = new Map<string, RosterPosition>()
  Object.keys(RosterPosition).forEach(x => {
    console.log(x)
    all.set(x, RosterPosition[x])
  })
}

[LOG]: "LW" 
[LOG]: "RW" 
[LOG]: "C" 
[LOG]: "LD" 
[LOG]: "RD" 
[LOG]: "G" 
[LOG]: "all" // excuse me?
```
### 🙁 Actual behavior

Map's variable becomes last entry in object properties array that references target Enum.

### 🙂 Expected behavior

That Map's defining variable doesn't magically enter object properties array of referenced Enum.

**Comment by jcalz** [comment]
You’ve merged the namespace and the enum.  `RosterPosition.all` exists because you exported `all`.

**Comment by godenji** [comment]
ahhh, that explains it, was wondering what on earth was going on :)
