### ISSUE TITLE
How to print anonymous recursive types

### ISSUE THREAD

**Issue by JsonFreeman** [microsoft/TypeScript#463]
``` TS
var a: { foo: typeof a; }
```

`a` has a recursive type. If we try to print this type, it prints `{ foo: any; }`, but it does not behave as such in type comparisons. So we are lying when we print it.

When fixing this, it's important to consider both displaying a type to the user, and generating .d.ts files.

**Comment by mhegazy** [comment]
A fix here should handle the case outlined in #475.

**Comment by Andarist** [comment]
To the best of my understanding of the issue at hand - this is already fixed and the issue could be closed cc @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
Wow, throwback. Indeed. Thanks @Andarist !
