### ISSUE TITLE
typeof item in Array incrorrect

### ISSUE THREAD

**Issue by q2578443177** [microsoft/TypeScript#46304]
# Bug Report

> `text[key]` on left infer to `never` ???  but why `text[key]` on right infer to `string | number`?

### 🕗 Version & Regression Information
`typescript - 4.5.0`

- This is a crash

### ⏯ Playground Link
[link](https://www.typescriptlang.org/zh/play?#code/JYOwLgpgTgZghgYwgAgJKQLbIN4ChkHLAAmAXMiAK4YBG0A3PoSHBhOQM5hSgDmjhZHF7sK1OlEYBfXLgQB7EF2Qx5UDOXQQsAXhxMCJcgE5jAGgMVWogOQBrGxcHDRpi1MZzFyyAA8wmpjIeniCRsgAjE7M1uQ2gAT6gJByjpYu5BEAHO6eABQA2jYkjjYsbMUuNgC6QhzICkpgAJQAdKpQAKKIABY5dhAAnsEAfPqCfmB5ff3VeuOTA5XSjYxAA)

### 💻 Code
```ts
interface Item {
    id: number;
    name: string;
    age: number;
}

const form: Item = {
    id: 99,
    name: 'k',
    age: 99,
};

const text: Item = {
    id: 1,
    name: '张三',
    age: 18,
};

(['id','name','age'] as const).forEach(key => {
    text[key] = text[key];
});

// Type 'string | number' is not assignable to type 'never'.
// Type 'string' is not assignable to type 'never'.
```

### 🙁 Actual behavior
bug occured

### 🙂 Expected behavior
no bug

**Comment by jcalz** [comment]
Working as intended, as per #30769.  Possible duplicate of #32693

**Comment by fatcerberus** [comment]
> This is a crash

Uh... no it's not?  Nor is it a bug.  It's just an error you didn't expect.
