### ISSUE TITLE
SpeechRecogntion types are missing in v4.4

### ISSUE THREAD

**Issue by Sharcoux** [microsoft/TypeScript#46308]
# lib Update Request

SpeechRecogntion was available in typescript v4.3 and not anymore in v4.4. Please, reintroduce it so that we can move from v4.3 to v4.4

## Configuration Check

My compilation *target* is `ES2016` and my *lib* is `['esnext', 'dom']`.

## Missing / Incorrect Definition

[SpeechRecognition](https://developer.mozilla.org/fr/docs/Web/API/SpeechRecognition)

## Sample Code

```ts
const BrowserSpeechRecognition: SpeechRecognition =
  window.SpeechRecognition ||
  // @ts-expect-error fallback objects
  window.webkitSpeechRecognition ||
  // @ts-expect-error fallback objects
  window.mozSpeechRecognition ||
  // @ts-expect-error fallback objects
  window.msSpeechRecognition ||
  // @ts-expect-error fallback objects
  window.oSpeechRecognition
```

`Property 'SpeechRecognition' doesn't exist on type 'Window & typeof globalThis'. ts(2339)`

## Documentation Link

[SpeechRecognition](https://developer.mozilla.org/fr/docs/Web/API/SpeechRecognition)

**Comment by AviVahl** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029#issuecomment-908454034

**Comment by Sharcoux** [comment]
For further reader, just install @types/web version 0.0.1 to solve the issue. Don't forget to remove 'dom' from the 'lib' array in your tsconfig as described in the [Install process](https://www.npmjs.com/package/@types/web).

**Comment by JohnDeved** [comment]
`npm i @types/dom-speech-recognition -D` provides typings for SpeechRecogntion
