### ISSUE TITLE
Have timeout for long-running operations in Visual Studio

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#4634]
Need abort feature of auto type checking because most developers don't notice that when type checking hanged. And some developers can not restore the code. Developers must immediately know the hanged timing.

https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+compile+hang+label%3ABug+

**Comment by danquirk** [comment]
There is some precedent for aborting operations in Visual Studio after some threshold is passed (ex we used to kill formatting operations that took longer than 2 seconds).

**Comment by falsandtru** [comment]
How do I setting it?

**Comment by danquirk** [comment]
Sorry, I didn't mean there is a workaround for this particular issue, just that if we did fix this in the way you wanted (essentially adding a timeout) it would not be the first time we've had to adopt that approach.

**Comment by falsandtru** [comment]
I got it. I am waiting for the improvement of Visual Studio. Thanks.

**Comment by mhegazy** [comment]
Any long lags should be treated as bugs. please file issues for these as you run into them. closing this issue, as we believe this is the wrong fix for the underlying lags.
