### ISSUE TITLE
tsc 4.5 explicit eventual-extension-for-relative-imports policy breaks webpack's resolver logic

### ISSUE THREAD

**Issue by JasonKleban** [microsoft/TypeScript#46344]
# Bug Report

Related to https://github.com/TypeStrong/ts-loader/issues/1383 

https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#type-in-packagejson-and-new-extensions

> This code works in CommonJS modules, but will fail in ES modules because relative import paths need to use extensions. As a result, it will have to be rewritten to use the extension of the output of foo.ts – so bar.ts will instead have to import from ./foo.js. ... This might feel a bit cumbersome at first, but TypeScript tooling like auto-imports and path completion will typically just do this for you.

(side note: I don't have nearly that much confidence in the consistency of the IDE tooling related to import autocompletion especially in monorepos)

### 🔎 Search Terms

mjs mts webpack extension tsc 4.5-dev

### 🕗 Version & Regression Information

tsc 4.5-dev

I was unable to test this on prior versions because the new extensions behavior is new.

### ⏯ Playground Link

N/A - involves relative path module resolution.

### 💻 Code

With webpack's module resolution, 

`import { foo } from "./misc"` works as always
`import { foo } from "./misc.ts"` is wrong and gives `TS2691: An import path cannot end with a '.ts' extension. Consider importing './misc.js' instead.`

but 

`import { foo } from "./misc.js";` works with `tsc` but fails only in webpacking with `Module not found: Error: Can't resolve './misc.js' in 'C:\example\src'
resolve './misc.js'`

### 🙁 Actual behavior

`import { foo } from "./misc.js";` works with `tsc` but fails only in webpacking with `Module not found: Error: Can't resolve './misc.js' in 'C:\example\src'
resolve './misc.js'`

### 🙂 Expected behavior

Webpack has no obvious way of _overriding_ the resolved file extensions from ".js" to ".ts" or ".mjs" to ".mts".  [resolve.extensions](https://webpack.js.org/configuration/resolve/#resolveextensions) takes an array of suffixes, but doesn't seem to be able to express _replacements_ and doesn't seem to take such an expressive function.

I know this policy of `tsc` not modifying non-type-annotations in the emit is long settled, but we at least could appreciate some guidance on this.  Is there a webpack compatible configuration for this?  Is a particular change in webpack recommended? What do we do?

**Comment by andrewbranch** [comment]
This is still something we’re working out. I’m not convinced that `node12`/`nodenext` are appropriate module resolution modes if you’re writing for the browser or for a bundler. There is some discussion about this going on at https://github.com/microsoft/TypeScript/issues/37582 and I’d like to use that as the canonical issue to discuss this problem. For Webpack specifically, it looks like you should be able to use https://www.npmjs.com/package/resolve-typescript-plugin, though it will probably need an update for the mts file extension. But for now, I think my best recommendation would be not to use mts and/or `node12`/`nodenext` with Webpack and keep writing extensionless imports. Let’s move additional discussion to #37582.

**Comment by thw0rted** [comment]
Seen in a related issue: [webpack just fixed this](https://github.com/webpack/webpack/releases/tag/v5.74.0) with `resolve.extensionAlias`, so you should be able to write a `.js` extension and make both `tsc` and webpack happy.
