### ISSUE TITLE
TypeScript file Watcher consuming over 5k watchers

### ISSUE THREAD

**Issue by oof2win2** [microsoft/TypeScript#46351]
Issue Type: <b>Bug</b>

Since the latest update of Insiders, it has begun to use a new file watcher (from what I see [here](https://github.com/microsoft/vscode/issues/132483#issuecomment-939980296) and the new `Files: Legacy Watcher` setting). My issue however is that **this is not working** and file watchers are still being consumed. 

This is the output of [`inotify-consumers`](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers), `npm i` and then running `inotify-consumers` again. To note, `node_modules/` was removed prior to the first consumer check.
```
oof2win2@koelkast:/opt/factorio/AwF-Bot-Test$ rm -rf node_modules/
oof2win2@koelkast:/opt/factorio/AwF-Bot-Test$ ~/cmds/inotify-consumers 

   INOTIFY
   WATCHER
    COUNT     PID     CMD
----------------------------------------
     235  2812552  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node --max-old-space-size=3072 /home
      96  2812533  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node /home/oof2win2/.vscode-server-i
       4    46817  /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
       4  2812522  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node /home/oof2win2/.vscode-server-i
       4  2812450  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node /home/oof2win2/.vscode-server-i
       2    46787  /lib/systemd/systemd --user
       1    46787  /lib/systemd/systemd --user
       1    46787  /lib/systemd/systemd --user
       0  2812582  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node /home/oof2win2/.vscode-server-i

     347     WATCHERS TOTAL COUNT
oof2win2@koelkast:/opt/factorio/AwF-Bot-Test$ npm i

npm installation here

oof2win2@koelkast:/opt/factorio/AwF-Bot-Test$ ~/cmds/inotify-consumers 

   INOTIFY
   WATCHER
    COUNT     PID     CMD
----------------------------------------
    2540  2812552  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node --max-old-space-size=3072 /home
    2305  2812582  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node /home/oof2win2/.vscode-server-i
      96  2812533  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node /home/oof2win2/.vscode-server-i
       4    46817  /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
       4  2812522  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node /home/oof2win2/.vscode-server-i
       4  2812450  /home/oof2win2/.vscode-server-insiders/bin/284e0db6c4cac1e557a43cd6691babdaafc2e1a9/node /home/oof2win2/.vscode-server-i
       2    46787  /lib/systemd/systemd --user
       1    46787  /lib/systemd/systemd --user
       1    46787  /lib/systemd/systemd --user

    4957     WATCHERS TOTAL COUNT
oof2win2@koelkast:/opt/factorio/AwF-Bot-Test$ 
```

Here are my settings.json. Used this as just `"**/node_modules/**: true`, which is included, did not work.
```json
{
  "files.watcherExclude": {
    "**": true,
    "**/**": true
  }
}
```

VS Code version: Code - Insiders 1.62.0-insider (284e0db6c4cac1e557a43cd6691babdaafc2e1a9, 2021-10-12T05:44:21.888Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-80-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 11b22232-fe4c-4ed0-a0a1-d5910ebb956b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: awf|
|OS|Linux x64 5.4.0-80-generic|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 1200)|
|Memory (System)|31.27GB (4.74GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.8
remote-ssh-edit|ms-|0.65.8
todo-tree|Gru|0.0.214
html-preview-vscode|tht|0.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30377800
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis400:30374798
vsaa593cf:30376535

```

</details>

**Comment by mjbvz** [comment]
Yes the typescript server has its own file watcher. Moving upstream to TS

**Comment by bpasero** [comment]
> but this sounds expected for us

Why can you not rely on the file events VS Code sends for a workspace to your extension?

**Comment by bpasero** [comment]
Fyi https://github.com/microsoft/vscode/issues/146066 makes the `createFileSystemWatcher` API more powerful: if you watch inside the workspace and your watcher is not recursive, the `files.watcherExclude` setting will not apply to you. This will help you watching inside `node_modules` folder because that folder is ignored by default via settings.

My understanding is that TypeScript does not require recursive watching because you only need to watch the `@types` folder for changes and that would work with a flat watcher :rock

**Comment by sheetalkamat** [comment]
If anyone wants to do custom watching, we do allow users to exclude directories and folders from watches.. So users can opt to disable watching and refresh the state as they like but our watching tries to cater for various types of scale and uses and also os variants.
