### ISSUE TITLE
Interface in function declaration statement

### ISSUE THREAD

**Issue by codelegant** [Microsoft/TypeScript#4635]
There is a interface like this:
```ts
interface searchFunc {
	(source: string, subString: string): boolean;
}
```
I know I can use it in **function definition expression**:
```ts
var mySearch: searchFunc = function(src, sub) {
	var result = src.search(sub);
	if (result == -1) {
		return false;
	}
	else {
		return true;
	}
}
```
But how can I use it in **function declaration statement** like below? Do I need to change the structure of interface?
```ts
function mySearch(src, sub): searchFunc {
	var result = src.search(sub);
	if (result == -1) {
		return false;
	}
	else {
		return true;
	}
}
```
I'm waiting online,hope a answering.

**Comment by DanielRosenwasser** [comment]
The short answer is you can't do it for a function declaration, only a function expression. You can still use your interface to ensure that when passing `mySearch` somewhere that its type is compatible, but you can't have your parameter types inferred the same way.

**Comment by codelegant** [comment]
Thank for your answer  :).

**Comment by DanielRosenwasser** [comment]
You're very welcome!
