### ISSUE TITLE
Change errors to use the term "ES module" not "ES6 module".

### ISSUE THREAD

**Issue by sidharthv96** [microsoft/TypeScript#46363]
aside: Some time we should change errors to use the term "ES module" not "ES6 module".

_Originally posted by @sandersn in https://github.com/microsoft/TypeScript/pull/46270#discussion_r729172501_

**Comment by fatcerberus** [comment]
That’s fair, but generally people use “ES modules” or “ESM” to differentiate from other module types. Even Node.js uses the term “ECMAScript Modules” in their documentation:
https://nodejs.org/api/esm.html

I personally haven’t heard the term “standard JS modules” used in the wild, but most people know what “ESM” means.
