### ISSUE TITLE
Syntax coloring as server service

### ISSUE THREAD

**Issue by bartosz-k** [microsoft/TypeScript#4637]
As in the title. Was this discussed before? Having that we'd avoid situations like this:
https://youtrack.jetbrains.com/issue/WEB-14441#viewimage=jsx%2520and%2520ts.png%3Ffile%3D74-228624%26v%3D0%26c%3Dtrue%26rw%3D371%26rh%3D97%26u%3D1430252561644. And this is still happening in WebStorm now :)

**Comment by vladima** [comment]
PR will be appreciated.

**Comment by RyanCavanaugh** [comment]
Semantic highlighting is available, or use textmate grammar as provided
