### ISSUE TITLE
tsc fails to report unreachable code that other typescript tooling (ts playground at least) reports correctly

### ISSUE THREAD

**Issue by dgoldstein0** [microsoft/TypeScript#46377]
# Bug Report

### 🔎 Search Terms

unreachable code detection

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it.
- I discovered it on 4.0.7 and verified on 4.4.4

### ⏯ Playground Link

NOTE: as this is a bug in tsc and not the playground, the playground doesn't do it justice. but is useful for poking at the example code.  we might need a slightly different example if #46376 gets fixed

[Playground link with relevant code](https://www.typescriptlang.org/play?strict=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&alwaysStrict=false&noUnusedLocals=true&target=1&module=2&ts=4.0.5#code/GYVwdgxgLglg9mABGApgNxQJwEoqiTMACgEoAuZdLRAbygAtM4B3S1gUUyc1IG4BfAFCDUGHHgLESvQcDiZERCAgDOURAA9EcYIgDaAIgCGBgDSIDAIzMWIBgLolagxK8TKwKuABsUAOm84AHMiDWlBfiA)

### 💻 Code

```ts
// b.ts
function neverReturn(): never {
  throw new Error();
}

neverReturn();
for (const x of ['a', 'b', 'c']) {
  console.log(x);
}
```

compile with `tsc`

### 🙁 Actual behavior
```
$ ./node_modules/.bin/tsc b.ts
b.ts:7:11 - error TS2339: Property 'log' does not exist on type 'never'.

7   console.log(x);
            ~~~


Found 1 error.
```

### 🙂 Expected behavior

expected "7027 Unreachable Code Detected" in tsc's error output as well.  Narrowing `console` without also signaling that the code is unreachable is a super confusing error message.

Interestingly, TS playground shows errors about unreachable code, it's just tsc that doesn't.

**Comment by MartinJohns** [comment]
The compiler settings used in the playground are different from the standard settings of the compiler. If you use the same settings running tsc you will have the same result.

**Comment by dgoldstein0** [comment]
I do actually have a tsconfig, I just never realized that allowUnreachable was tri-valued.  I've totally seen unreachable code warnings before so I thought we had them on as errors.  Agree that changing the default would be a breaking change and thus is probably undesirable.

perhaps my suggestion would be better with an example: for the sample code in the issue, instead of the current error message, I'm thinking something like
```
$ ./node_modules/.bin/tsc b.ts
b.ts:7:11 - error TS2339: Property 'log' does not exist on type 'never'.  Variable console is never because typescript determined this expression is unreachable

7   console.log(x);
            ~~~


Found 1 error.
```

that would not add any errors that don't already exist today, yet would make the existing error messages more actionable.  Seems like a pure win?  it would have saved me at least an hour of debugging tonight had that been the message I got.

**Comment by MartinJohns** [comment]
Just FYI, the way you invoke tsc it won't use your tsconfig file. Not sure if you're aware of that.
