### ISSUE TITLE
Invalid optional promotion to non null

### ISSUE THREAD

**Issue by gottfired** [microsoft/TypeScript#46383]
# Bug Report

### 🔎 Search Terms

- optional
- promotion

### 🕗 Version & Regression Information

- This issues exists since optional were introduced
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "type system behaviour"

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAiD2BleBbApgFwBYEsB2A5tAN4BQ0F0AJvABQCUJ5lLw8eE8IaAdCPAVoAiGtE7ps+AkPoBuZhQC+pZaVCQYAFTQQMiDPABOaJiwD66FACM0hgFxwkqTLkLQAPtDwBXECGgAvF5oAO6OyBKugnKkCtAEmNCWNoYMpiyUbBwY0MY5QZIQPBZo1rbyGZSFxcm2gV6+IBWVuZjehnitGM1KKrEAZt54wBg47NAYOhhpZKzsutBg9Xih0Nq6+kZoDD3QOP3QtGA8tYbQAIRBPn6Msy3Hpzw0O9AA9K-QADwAtN-QAMSA6AAIQAqgBxByaRATVwAaxg2DAOTw8AuexgKzQVGx0CwtjQcWUqkmuh2pCAA)

### 💻 Code

```ts
class DoSomething {
    do() {
        console.log("do something");
    }
}

class TestStore {
    _member: DoSomething | null = new DoSomething();

    get member() {
        const ret = this._member;
        this._member = null;
        return ret;
    }
}

function test() {
    const a = new TestStore();
    if (a.member != null) {
        a.member.do(); // <-- ### BUG: TS thinks that no "!" needed here
    }
}

test();
```

### 🙁 Actual behavior

When performing a non null/undefined check for an optional variable that is a getter, the TS parser promotes the variable to being not null. The variable can be accessed without non-null-assert via !.

This is a bug, since getters are not idempotent and can return null/undefined on the next call.

### 🙂 Expected behavior

TS should enforce the use of non-null-assert and inform the user that the variable access can still be null/undefined. This is handled corectly by dart, where you have to either store the variable in a local variable, or use ! to promote the variable.

[Correct use with local variable in TS](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAiD2BleBbApgFwBYEsB2A5tAN4BQ0F0AJvABQCUJ5lLw8eE8IaAdCPAVoAiGtE7ps+AkPoBuZhQC+pZaVCQYAFTQQMiDPABOaJiwD66FACM0hgFxwkqTLkLQAPtDwBXECGgAvF5oAO6OyBKugnKkCtAEmNCWNoYMpiyUbBwY0MY5QZIQPBZo1rbyGZSFxcm2gV6+IBWVuZjehnitGM1KKrEAZt54wBg47NAYOhhpZKzsutBg9Xih0Nq6+kZoDD3QWQtW9WA8tYa7OP3QtIcAhEE+foyzLVY8NDvQAPSf0AA8ALT-PZGYwjOLKVSTXQ7UhAA)

Same sample in Dart. See that there you have to promote via !. [DartPad link](https://dartpad.dev/?null_safety=true&id=8e1bb623664177623aae58df3c90f046)

Also see info on same issue for dart: https://dart.dev/tools/non-promotion-reasons#property-or-this or https://github.com/dart-lang/sdk/issues/44327

**Comment by MartinJohns** [comment]
This surely falls under #9998.

**Comment by QbDesu** [comment]
While I do agree with @MartinJohns my argument why this shouldn't really be considered a bug would be on a much more fundamental level.

There is not much typescript can do about this without breaking it's [Non-Goal No 3](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals):
> Apply a sound or "provably correct" type system. Instead, strike a balance between correctness and productivity.

The only alternative would be treating properties that are known to be getters the same as function calls, which is not what you want in most cases, they are almost always supposed to be treated like regular properties. This kind of check is quite common check to prevent check if a value is not null so flagging it based on the signature alone would be annoying to most people that dont have such edge case uses as they'd have to do the non-null assertion even if it's not really needed.

So yes the only way you could detect it without troubling people when it mostly isn't necessary  is by analyzing the flow in depth, which isn't worth it for such an edge case in my opinion but the issue above has more discussion on that.

On top of that a simple way to avoid this using modern ECMAScript features is `a.member?.do()`.

**Comment by gottfired** [comment]
@fatcerberus Thanks, that's interesting, I never noticed that. Then the only "correct" solution would be going the same route as Dart and not allowing promotion of members at all, only of local variables. (Dart has a similar problem because child classes allow overriding member properties with getters, so they also can not auto promote member null checks which is forbidden in TS). 

Question is, if the TS devs want to go the correct route like Dart or stay with the more convenient current behaviour. I assume the latter because I don't think I'm the first one to have noticed this :)

I've modified your sample a bit to illustrate member vs local promotion

```ts
type A = {
    foo?: number;
}

class B {
    counter = 0;

    get foo():number|undefined {
        return (this.counter++&1) === 0 ? 1 : undefined;
    }

    set foo(v: number|undefined) {}
}  


function test(v: A) {
    console.log("member", v.foo); // output: 1
    console.log("member", v.foo); // output: undefined <-- this is not safe
    
    const local = v.foo;
    console.log("local", local); // output: 1
    if (local) {
        console.log("local", local); // output: 1 <-- this is safe
    }
}

test(new B());
````
