### ISSUE TITLE
Syntax for expressions as JSX Components for factories

### ISSUE THREAD

**Issue by QbDesu** [microsoft/TypeScript#46381]
# Suggestion

Add support for a new JSX syntax to allow using any expression as component in a jsx factory. Currently you need to first assign the expression you want to use to a named variable beginning with an uppercase character.

Using curly-braces for the expression is sensible because ithey already used for the purpose of passing expression values to the component in all other places. The obvious problem when doing so is that the closing you don't want to also have to duplicate said expression into the closing tag. I'm guessing this wasn't introduced to begin with. The way I suggest to work around this problem is by using empty curly braces in the closing tag.
Because of XML's/JSX's hierarchical structure this shouldn't be a problem because the closing tag should still unambiguous given the syntax is correct.

### Rationale

If you want to use a component from an outside source such as a property of a foreign object or props passed to another component which usually have lowercase names you have to first assign it to another variable.
On top of that determining whether something is supposed to be read as a symbol resolving to it's value rather than a string to b passed is very unlike ECMAScript.

To make one thing clear: **This is not intended to be used for complex expressions!** Rather than that it's intended to be used with simple expressions such as the property of a foreign object or so an incoming property doesn't have to be renamed when being restructured. Adding a syntax for expression makes it flexible enough to work in most such cases, even ones that I didn't consider here.

## 🔍 Search Terms

JSX expression component factory

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### Proposed syntax
```ts
//
<{expr} [...props]>
    [...children]
</{}>
// self-closing
<{expr} />

// these are equivalent to
const NamedExpr = expr;
<NamedExpr [...props]>
    [...children]
</NamedExpr>
// and
const NamedExpr = expr;
<NamedExpr [...props] />
```

:x: `<{ props.bold ? "strong" : SemanticParagraph.baseTextTagType || "span"  }>{props.children}</{}>`
:heavy_check_mark: `<{ Composer.base }>{props.children}</{}>`
:heavy_check_mark: `<{ props.component }>{props.children}</{}>`
:o: `<{ props.component ?? "span" }>{props.children}</{}>`

**Comment by andrewbranch** [comment]
We don’t control the JSX spec: https://facebook.github.io/jsx/
