### ISSUE TITLE
Uppercase/Lowercase don't work in conditional type

### ISSUE THREAD

**Issue by shau-kote** [microsoft/TypeScript#46393]
# Bug Report

### 🔎 Search Terms

lowercase uppercase 
extends clause 
conditional type

### 🕗 Version & Regression Information

I tested this in 4.4.3 and 4.5.0-beta.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.3#code/GYVwdgxgLglg9mABDAzgVQA4YKYCcICGK2APAMqLYAeU2YAJioilLjGAOYB8AFCgFyIyASkEVqtBk0w58RUizacuiAPyJWIbIkHACAG2KIA3gCgAkLmxQQuJEwC8T5gDoocGXgDC8nsIDcpgC+pqYQCCyIAEYEuDoauFqIDsjoWHiExDwA5ABCAIIAStkBiAD0ZYgA7nC4ANZMRJRUONDY9GERUIjAcHDxeobaKaieclnZvXAl-uWVxNgAtkxRuHB1dEA)

### 💻 Code

```ts
function isUppercase<S extends string>(s: S): S extends Uppercase<string> ? true : false {
	return s === s.toUpperCase();
}

const bar : true = isUppercase('BAR'); // works as expected
const foo : false = isUppercase('foo'); // seems broken
```

### 🙁 Actual behavior

The code from the snippet above contains two errors:
1. «Type 'boolean' is not assignable to type 'S extends string ? true : false'» in the `isUppercase` function body.
2. The `isUppercase` function always returns `true`, even with `'foo'` as argument.

### 🙂 Expected behavior

No errors.
The `isUppercase` function returns `true` or `false` depending on the argument content.

**Comment by xiBread** [comment]
This isn't a bug, you need to pass `S` as the type parameter for `Uppercase`. `Uppercase<string>` is just `string`.

**Comment by eeckhardt-chwy** [comment]
@shau-kote Try this:

```
function isUppercase<S extends string>(s: S): s is Uppercase<S> {
	return s === s.toUpperCase();
}
```

**Comment by erikeckhardt** [comment]
@shau-kote Try this:

```
function isUppercase<S extends string>(s: S): s is Uppercase<S> {
	return s === s.toUpperCase();
}
```

**Comment by FilipeBeck** [comment]
I found [this solution](https://www.typescriptlang.org/play?ts=4.4.3#code/C4TwDgpgBAkgzgVTJATgYwIZwgHgMpQQAewEAdgCZxRzAoCWZA5gHxQC8UBxpl1SqTNnxsA-FDoBXaAC4oAMwwAbbAChV8yWTTB6AezJR6iZBHRZc3EuSo06jVgAo4cvAEo58AWaGW2Ab1UASBQIYEkUQ2cOdk44ADpgPW8UAGELRzc3KCxYE0ELEQBuVQBfdTQDWigAIwwUKDkpaE5jFN9HAHIAIQBBACVOtyKoAHpRqAB5AGlVSrJq+T09RoVlbA4jfJ8MzqW9IZHxqemgA):
```typescript
type IsUppercase<S extends string> = S extends Uppercase<S> ? true : false

function isUppercase<S extends string>(s: S): IsUppercase<S> {
	return (s === s.toUpperCase()) as IsUppercase<S>;
}

const bar : true = isUppercase('BAR'); // OK
const foo : false = isUppercase('foo'); // OK
``` 

But, it will [wrongly infer](https://www.typescriptlang.org/play?ts=4.4.3&ssl=8&ssc=1&pln=8&pc=77#code/C4TwDgpgBAkgzgVTJATgYwIZwgHgMpQQAewEAdgCZxRzAoCWZA5gHxQC8UBxpl1SqTNnxsA-FDoBXaAC4oAMwwAbbAChV8yWTTB6AezJR6iZBHRZc3EuSo06jVgAo4cvAEo58AWaGW2Ab1UASBQIYEkUQ2cOdk44ADpgPW8UAGELRzc3KCxYE0ELEQBuVQBfdQoINCUMUKg0A1oFPT05WgZmVQayJoAjWqg5KWhOYxTfR3kWtyKoAHo52DJ5MwgKHOoAA2HNgBooXslgI2OAWwwQKDI9Y96IIA) when the argument is just a `string` type:
```typescript
type IsUppercase<S extends string> = S extends Uppercase<S> ? true : false

function isUppercase<S extends string>(s: S): IsUppercase<S> {
	return (s === s.toUpperCase()) as IsUppercase<S>;
}

declare const foo: string
const bar : true = isUppercase(foo); // Infered as `true`, but it may not be
```
