### ISSUE TITLE
Keyword Arguments

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#46391]
# Suggestion
## 🔍 Search Terms
destructuring function arguments

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I when I have a function with multiple arguments of the same time, I prefer to use keyword arguments instead. However, it's painful how many times I have to write these arguments twice -- once in the definition and once to destructure the arguments in the first line of the function.

```ts
function setPlayerName(gameId: string, playerId: string, playerName: string) {}

// Easy mistake and the ambiguous types means the type-checker doesn't help.
setPlayerName(playerName, playerId, gameId)

// Lots more typing.
function setPlayerName(args: {
  gameId: string, 
  playerId: string, 
  playerName: string
}) {
  const {gameId, playerId, playerName} = args
}
```

I would love it if I didn't have to type those arguments twice. 😁

Not sure how you want to deal with syntax for this... maybe you can leave out the `args: ` and it generates a unique variable name and everything just works.

```
function setPlayerName({
  gameId: string, 
  playerId: string, 
  playerName: string
}) {

}
```

**Comment by jcalz** [comment]
Generating variable names from type annotations is type-directed emit and a no-go (and you checked the box saying your suggestion doesn’t do that), so that can’t happen.

Otherwise seems like a duplicate #29526

**Comment by ccorcos** [comment]
Ah this one: "This could be implemented without emitting different JS based on the types of the expressions". I misread that the first time.

Looks like a dupe though. Thanks!
