### ISSUE TITLE
Inconsistent results for interfaces and types in special cases

### ISSUE THREAD

**Issue by oxy-plus** [microsoft/TypeScript#46400]
# Suggestion

Make the type and interface results consistent when use `extends`.

## 🔍 Search Terms

interface type inconsistent

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In the following code, we can see that even if an interface and a type can be `extends` to conclude that they are equivalent, the behavior will be inconsistent when used with other types:
```typescript
type _1_TObj = {
  key: "value"
}
interface _2_IObj {
  key: "value"
}

//true
type EqualCheck = _1_TObj extends _2_IObj ? _2_IObj extends _1_TObj ? true : false : false

type TJsonData = string | number | boolean | null
type TJson = {
  [key: string]: TJson
} | TJsonData | TJsonData[] | TJson[]

//true
type TypesIsOk = _1_TObj extends TJson ? true : false
//false
type InterfaceIsOk = _2_IObj extends TJson ? true : false
```

## 📃 Motivating Example
It seems this is related to #15300

**Comment by jcalz** [comment]
I know from #15300 that this is by design but I don’t know that I quite understand why.  Is there a unique danger to allowing implicit index signatures for interface types? 

Merging new properties into existing interfaces seems like it could always break code that depends on these interfaces; I don’t really see the problem as being worse with implicit index signatures.  

Could someone enlighten me?

**Comment by fatcerberus** [comment]
Just a shot in the dark but it might be that the implicit index signature is statically computed from the type's properties (i.e. by unioning them all) when it's first defined and that would be broken by augmentation.

**Comment by andrewbranch** [comment]
Yeah, I think @fatcerberus’s explanation is correct.

**Comment by andrewbranch** [comment]
Where this starts to feel unfortunate for me is that if this occurs in a module where nothing is exported, so the types are not augmentable, you still get the same behavior. I guess switching on that would possibly be _more_ unexpected, but it does completely invalidate the augmentation rationale.
