### ISSUE TITLE
Template literal types with decorator crashes in emit

### ISSUE THREAD

**Issue by AdrianAbramczyk** [microsoft/TypeScript#46406]
# Bug Report

### 🔎 Search Terms

Template literal type annotation 

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about annotation / literal.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/JYWwDg9gTgLgBAIigUwGYBtkGMYFoTIwCGAJkcQgNwBQ1WEAdgM7yrQjkCyhp5RA0sgCecALxwAykJAAjCOgAUCNlA4wEAShrVUAVwY5gjOCrULT5CTCjAGAcwBccFjfsa4Ab2pw4KGLqgGOAAlNEwcADoCYjJic3YuHliBYQAaEwSYK1c7LWoAX1osdCImJjgAcRRCZChPbzgAAQsYJQAJZHR0CHSAUiZNBrtqmFtHOAADABIPFzH8iZofBvpma10caAV3Lx8fGAALYCYI4eRCMbE4AHIAYgANR-vrpb3VpnlkCO67BWvD46nEZja7pAEnM4XNyvQqFagMZAAd0qI1q20oQA) (See console)

### 💻 Code

```ts
import "reflect-metadata";

const formatMetadataKey = Symbol("format");

function format(formatString: string) {
  return Reflect.metadata(formatMetadataKey, formatString);
}

class Greeter {
  // Here : Can't use a literal type with an annotation
  @format("Hello, %s")
  greeting: `${string}`;
  
  constructor() {
    this.greeting = '#XXXX';
    console.log('this.greeting', this.greeting);
  }
}

new Greeter();
```

### 🙁 Actual behavior

When using a template literal type with an annotation I get the following error in the console : 
```
Error: Debug Failure. Unexpected node.
Node TemplateLiteralType was unexpected
```
Because the template literal type is not currently supported : 
https://github.com/microsoft/TypeScript/blob/68ff7380d2aae287282dd972a1d153cbb4e9ae2a/src/compiler/transformers/ts.ts#L1541

### 🙂 Expected behavior

I should not get an error.

**Comment by a-tarasyuk** [comment]
@rbuckton How should the `TemplateLiteralType` be serialized? 

```ts
__metadata("design:type", ????)
```

For instance union type serialized as `Object`

```ts
class A {
    @dec
    foo: string | number;
}
```

```js
__metadata("design:type", Object)
```

/cc @RyanCavanaugh @andrewbranch

**Comment by rbuckton** [comment]
Probably as `String`, since it can only represent a string type.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
