### ISSUE TITLE
object property name starts with 2 or more underscores, it's node.escapedText will be real plus 1 leading underscore

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#46401]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.4.3 and 4.4.3
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```js
const ts = require('typescript');

const code = `
( { __: 2 } )
`;

const root = ts.createSourceFile('', code, ScriptTarget.Latest, false, ScriptKind.TS);

console.log(
    root
    .statements[0]
    .expression
    .expression
    .properties[0]
    .name
    .escapedText
);
```

### 🙁 Actual behavior

```
___
```

The property name `__` become `___`. I found this bug only happen when the name starts with 2 or more underscores.

BTW: any other feature is no bug, e. g. `pos`, `transpileModule`...

### 🙂 Expected behavior

```
__
```

**Comment by fehengli** [comment]
Hi, I have the same problem. How did you solve it？Thanks

**Comment by fehengli** [comment]
My typescript version is 4.6.2

**Comment by RyanCavanaugh** [comment]
This isn't a bug; `escapedText` *means* the version of the name that's safe to use in a context where internal names start with `_`. You usually want `.getText()` or `.getFullText()` instead depending on the kind of node
