### ISSUE TITLE
*.tsx file  webpack externals invalid

### ISSUE THREAD

**Issue by wuliqiangqiang** [microsoft/TypeScript#46410]
# Bug Report

this is my error report when webpack build time

![image](https://user-images.githubusercontent.com/16221367/137706488-e5564779-bdad-4c10-8492-5149836ded0e.png)

**Cannot find module 'React' or its corresponding type declarations.**

just the *.tsx files has this error，*.jsx files is normal build

the react / react-dom from the outside file pass the webpack externals make linked 

//webpack.config.js
module.exports = {
  //...
  externals: {
      React: 'React',
      ReactDOM: 'ReactDOM',
  },
};

//ts.config.js
![image](https://user-images.githubusercontent.com/16221367/137707347-4354d456-c82e-4997-aefe-3a8dd83186e5.png)

### 🕗 Version & Regression Information

"@tsconfig/recommended": "^1.0.1",
    "@types/node": "^16.10.1",
    "@types/react": "^17.0.30",
    "@typescript-eslint/eslint-plugin": "^4.31.1",
    "@typescript-eslint/parser": "^4.31.1",

"webpack": "5.54.0",
    "webpack-bundle-analyzer": "^4.4.2",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.3.0",
    "webpack-merge": "^5.8.0"

"typescript": "^4.4.2",

help~~~~~~~~~~~~~~~~~~

**Comment by DanielRosenwasser** [comment]
This doesn't seem to follow the issue template which requires a simple repro that doesn't require external tools to run. Seems like you have a Webpack + TS configuration problem which is maybe better-suited for StackOverflow.
