### ISSUE TITLE
Slow performance in incremental mode with no changes

### ISSUE THREAD

**Issue by JelleZijlstra** [microsoft/TypeScript#46420]
# Bug Report

### 🔎 Search Terms

Performance

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about performance

### ⏯ Playground Link

n/a

### 💻 Code

n/a

### 🙁 Actual behavior

I have a huge, closed-source TypeScript project (7600+ files, 2M+ lines of TypeScript).

Typechecking is slow, about 30 s even with incremental mode on. We'd like to get this faster and discovered that even with incremental mode on and with no changes in the code, TS visits and parses every single file in the project.

Here is a screenshot from the awesome perf tracing tool (from an incremental run with no changes since the previous run):
![Screen Shot 2021-10-18 at 5 26 15 PM](https://user-images.githubusercontent.com/906600/137824151-0e1dd01e-725d-4da3-bff3-f9b28ac27892.png)

This was from typescript@next (which seems a little faster than the current release, thanks for that!). Of 28 s total, 22 s was spent in findSourceFile.

### 🙂 Expected behavior

Incremental mode should cache enough information that it's not necessary to re-parse each file on the next run.

**Comment by DanielRosenwasser** [comment]
Do you have this issue with `findSourceFile` on non-incremental compiles?

**Comment by JelleZijlstra** [comment]
![Screen Shot 2021-11-17 at 2 55 25 PM](https://user-images.githubusercontent.com/906600/142295602-776fe1a4-3604-42c0-a571-2a00ad7d3558.png)

When I turn off `incremental: true` and `tsBuildInfoFile` in my tsconfig, I get the above trace. `findSourceFile` is still equally slow, but in addition it spends a lot of time actually type checking the code.

**Comment by samuliasmala** [comment]
I'm experiencing the same. I was expecting the incremental flag to reduce the compilation time to watch mode incremental compilation time, but the reality is different. I have smaller codebase so `npx tsc` with `incremental: false` takes 8 seconds. First `incremental: true` run takes the same 8 seconds but after that it's reduced to 4 seconds.

However, if I run `npx tsc --watch` it takes the same amount of time to start as without the `--watch` flag (8 s or 4 s) but after that the compilation takes less than a second.
```
[10:37:59 PM] Starting compilation in watch mode...

[10:38:03 PM] Found 0 errors. Watching for file changes.

[10:38:31 PM] File change detected. Starting incremental compilation...

[10:38:31 PM] Found 0 errors. Watching for file changes.
```

## Steps to reproduce

Some output removed for clarity.

```bash
$ node -v
v16.10.0

$ npm -v
7.24.0

$ git clone git@github.com:microsoft/TypeScript-Node-Starter.git
$ cd TypeScript-Node-Starter/
$ npm install

$ time npx tsc
real    0m6.447s

$ time npx tsc
real    0m6.365s

$ time npx tsc --incremental
real    0m6.444s

$ time npx tsc --incremental
real    0m2.441s

$ time npx tsc --incremental --watch
```

Again the first compilation of the watch command takes that 2 s but after that it is less than a second.

**Comment by nh2** [comment]
@RyanCavanaugh Was this solved? What was the fix?

**Comment by DanielRosenwasser** [comment]
If you're experiencing a performance issue at this point, we recommend trying out [early previews of TypeScript 7](https://devblogs.microsoft.com/typescript/progress-on-typescript-7-december-2025/):

```
npm install -D @typescript/native-preview

# use 'tsgo' where you would otherwise use 'tsc'
tsgo -p tsconfig.json
```

**Comment by nh2** [comment]
Thanks, I'm aware of that; that's not what I asked though. I asked what closed this as completed, as I'm looking into bugs related to incremental mode (which I believe `tsgo` also does have).
