### ISSUE TITLE
Use new node recursive file watching in tsserver

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#4643]
courtesy of @billti 

Recursive directory watching for Windows and OSX is landing in node master: https://github.com/nodejs/node/pull/2649 

This enables watching a folder recursively on Windows (was already available on OS X). Under the covers this is a change in libuv (which abstracts away the OS) and uses the ‘watchSubtree’ option on the Win32 ReadDirectoryChanges function – so it should be highly reliable. (libuv change viewable here).

**Comment by dhusemann** [comment]
Looks like it will be in node.js 4.0 and backported to IO.js 3.3.1.

**Comment by zhengbli** [comment]
That means we can get rid of our own pollling mechanism currently in use for file watching? What about users who uses a lower node version?

**Comment by mhegazy** [comment]
We should do feature detection. I think it is fine for new features like watching directories for new files to work on node 4 only.

**Comment by zhengbli** [comment]
Another question is, where should we start the directory watching? If we start from the root level (e.g. "C:\"), we will have to response to a lot of system level file changing events that is pure noise to us; if we start from the current path, we may miss when the user adds a tsconfig file in an upper level directory.

**Comment by zhengbli** [comment]
Fixed with #5127
