### ISSUE TITLE
Unhandled Error for using "enum" as a parameter

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#46433]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEWIhACmBSQFsBKOAbwCgBIKYGJKXYsgbhoF8g)
    
### 💻 Code

```ts
export function foo(enum) {
	return enum;
}
```

### 🙁 Actual behavior

```ts
function foo(enum) {
             ^^^^^ Error: Identifier expected. (1003)
```
```ts
	return enum;
               ^^^^^ Error: Expression expected. (1109)
```

### 🙂 Expected behavior

```ts
function foo(enum) {
             ^^^^ Error: Identifier expected. 'enum' is a reserved word that cannot be used here. (1359)
```

**Comment by MartinJohns** [comment]
`enum` is a reserved keyword.
