### ISSUE TITLE
Getters/setters are required when their corresponding type permits `undefined`, cannot be marked optional

### ISSUE THREAD

**Issue by SelyankinFyodor** [microsoft/TypeScript#46448]
# Bug Report

It requires filed which is a getter and setter for optional filed in return value

### 🔎 Search Terms
getters setters existential type

### 🕗 Version & Regression Information

typescript  version: 4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211020#code/MYGwhgzhAECWB28CmAnACig9gBxgbwChpjocAXAM1iRABMBGAfgC5p4BXAWwCNUBuIiXJUatAEwtoEMigQBzAQF8CBUJBiZ2ZVBhzRCJaAH0jCZOiy4TkszssQBhuUjJxEdnBAAUASla2LT2gAH2h2eFokKmRafUFDYhQXdhR4aDIAC1gIADoTAN0rI0cSZUMIFzdzQu8ANzAQdiR-d0DcELCIqIQkWh84hJJM7LzTVpqTaABeaHrGpBLiMpIweExM1AB5bDJYTHgGwskOHn4CZQIKcOBd-egKMFgQXoAxa99WTW02gZIkshSaTwq3WGS2Oz2BxAhVY9EUSiAA)

### 💻 Code

```ts
class innerProps {
    optfield1?: number;
    optfield2?: string;
}

class outerProp {
    __innerProps__?: innerProps;
    get innerProps(): innerProps | undefined {
        return this.__innerProps__;
    }
    set innerProps(value: innerProps | undefined) {
        this.__innerProps__ = value;
    }
    anotherOptionalProp?: number;
}

function failedFunc(): outerProp {
    return {anotherOptionalProp: 1};
}
```

### 🙁 Actual behavior

error: a required field is missing, although it is optional

### 🙂 Expected behavior

the returned object does not conflict with the declared type

**Comment by DanielRosenwasser** [comment]
It doesn't really make sense to distinguish a missing getter from `| undefined` because that get accessor will always be installed. You might be better off mirroring the type of your class and using optional properties.
