### ISSUE TITLE
Extending class can use superclass' namespace in values but not in types

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#46445]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/KYDwDg9gTgLgBAYwDYEMDOa4EE4G8BQAkANYCWAdgCYD8AXNgHQDSFl+AvvqJLHOSgFtgaMCgTBseIt2jwEEcmnjByAVwFwWVKYUJoBKJEgA0RQgCNSAcyKdOydJgBCcUDBWVMOXJ3z55ivAUAPoAboaqwME4ALyMWpQM+oZIANxw+AD0mXC5efkFuQB61IioGJL8QiJiElj+CkpwIeFIkcEucU7MrEkGRqlZOYUjeSVljnBOfgFNITAAnmBRWPRYPVR9KXBxLRErg7NB5MGLyx303QlbRjvNJ63tToPZoyNFcADaAKJQUNAAXTgAHInMC4AokAs4FBgAAzYBQTAwCBwFBwM7AYxwcyqIKYczAChWOCqNDAShozDoqrCUTiOAAC0RwAYcAAFAAmADsAAZOQBKIA)
    
### 💻 Code

```ts
export class A {
	kind?: A.Kind
}
export namespace A {
	export const enum Kind {
		small,
		big
	}
}
class B extends A {}


const in_value_A = A.Kind.small; 
//                 ^? class A namespace A
const in_value_B = B.Kind.small;
//                 ^? class B

const in_type_A: A.Kind.small = in_value_A;
const in_type_B: B.Kind.small = in_value_B;
//               ^ [Error] 'B' only refers to a type, but is being used as a namespace here. (2702)
```

### 🙁 Actual behavior

`B.Kind` can be used in values but not in types

### 🙂 Expected behavior

1) Hovering `B` should indicate it's also `namespace A`
```ts
const in_value_B = B.Kind.small;
//                 ^? class B namespace A
```
2) `B` should be usable as a namespace in types
```ts
const in_type_B: B.Kind.small = in_value_B;
//                 ^^^^? const enum A.Kind
```

**Comment by DanielRosenwasser** [comment]
This is working correctly, `extends` "copies" members from the extended type, but doesn't do the same of namespaces.
