### ISSUE TITLE
Lost context when generating a direct import

### ISSUE THREAD

**Issue by andrejleitner** [microsoft/TypeScript#46460]
# Bug Report

### 🔎 Search Terms

context, direct import

### 🕗 Version & Regression Information

- This changed between versions `4.3.5` and `4.4.4`

### ⏯ Playground Link

Repro repo: https://github.com/andrejleitner/nr-ts-issue

### 💻 Code

```ts
import {recordMetric} from "newrelic";

setInterval(() => recordMetric('SampleTestMetric', 123), 8 * 1000);
```

### 🙁 Actual behavior

Code generated with `v4.4.4`:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const newrelic_1 = require("newrelic");
setInterval(() => (0, newrelic_1.recordMetric)('SampleTestMetric', 123), 8 * 1000); // <--- difference here
```

> Here, the (0, newrelic_1.recordMetric) will in fact return the recordMetric function but now we'll be executing it outside of the context of the API instance and so this is undefined. It is some odd / unnecessary seeming code gen.

More info: https://github.com/newrelic/node-newrelic/issues/956

### 🙂 Expected behavior

Code generated with `v4.3.5`:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const newrelic_1 = require("newrelic");
setInterval(() => newrelic_1.recordMetric('SampleTestMetric', 123), 8 * 1000);
```

**Comment by whzx5byb** [comment]
This is [a breaking change](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#more-compliant-indirect-calls-for-imported-functions) in ts 4.4.
