### ISSUE TITLE
Erroneous TS2783 when ternary expressions are inlined in a spread operator

### ISSUE THREAD

**Issue by tpict** [microsoft/TypeScript#46463]
# Bug Report

### 🔎 Search Terms

TS2783, spread operator, control flow analysis

### 🕗 Version & Regression Information

This changed between versions 4.3.5 and 4.4.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/CYUwxgNghgTiAEYD2A7AzgF3kgbiGMAlqAFzwDeiSESMZARAOZwgr3wC+A3AFCiSwEydFmHBCGQqigQyAIyTUQUFLx48IILBhCYAjL2GZ4IAB5QAtgAdN8ALwUe8Z1Rp149OMHoAaJy4A6IIAKHX17eGCxCSkUGXgAfmw8AmIEMko0QgAvEAZoGEYQeg4ASlKeDnUwjD14AHp6ildaMkwiFEZOeAAfZqzctowOrqqeIywzSxsQACYI8n9nZDcGL18l+CCAmr1K9UaeRvgVYHgATy0feAB3AAtWE-gMc6sEfgKoSVR4QjR4KwAVywqAwSGeugwsz8xwwD3gaHAqDOU2stj+8BQSCwKhMBFoASO9XUmm0kNmGRa7nahE63T6mRyeQRw1po0MqGMqJmAGYFpsVq0POs-C4tiEavMHFFkTFpBBEsl8ERQPBKQNmfQCkUSuV9uNOZNzGiQAAWfliwXuTwgbyiwJBSWVIA) (thanks webstrand#8856 on the TS community server)

### 💻 Code

```ts
const override = { color: "green" };
const conditional = false as boolean;

const example = {
    color: "red",  // TS2783 here
    ...(conditional ? override : { size: "large"})
}

const more = conditional ? override : { size: "large"};
const example2 = {
    color: "red", // no TS2783 here
    ...more
}
```

### 🙁 Actual behavior

When using a ternary expression within a spread operator to conditionally apply properties to an object, a TS2783 error (`This spread always overwrites this property`) is raised even if the property is only overwritten in one branch of the conditional. The error is not present if the result of the ternary is assigned to a variable which is then applied with the spread operator.

### 🙂 Expected behavior

TS2783 should not be raised in situations where the property is only conditionally overwritten by a spread.

**Comment by sandersn** [comment]
Broken by #44696, where I commented "I think it's fine to ship a stricter check; we'll see if people complain in the beta."

I'm not sure the break was intentional, though, so I'm going to make sure.

**Comment by sandersn** [comment]
The new 4.4 code assumes that `conditional ? override : { size: "large"}` produces a type `{ color: string, size?: undefined } | { color?: undefined | size: string }` -- non-optional properties on either side of the union will produce the error.

However, the type is still `{ color: string } | { size: string }`. I need to figure out how to produce the correct union type and make sure to call that function for spreads.

**Comment by sandersn** [comment]
I pushed the fix to make-spread-overwrite-error-more-lenient for future reference.
