### ISSUE TITLE
Parsing error with ternary operator and arrow function

### ISSUE THREAD

**Issue by zesik** [microsoft/TypeScript#46462]
# Bug Report

### 🔎 Search Terms

ternary operator, arrow function, if

### 🕗 Version & Regression Information

- 3.3.3 (earliest version in the TypeScript Playground)
- 4.4.4 and Nightly (v4.5.0-dev.20211021)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/MYewdgzgLgBAZgVzAJhgXhgCgJToHwxQBOCApgNwBQloksiY6WADgIZGsC2AXDAEYgQAG1KswuNAUwBvSjHkxmvNh04wA-DACMMXsgA0chXF458MWQqswAlnCwNkOXJetuipKAiKMtVN-IAvkbunt6MyP4KwYHY5EA)

### 💻 Code

```ts
const fun2 = () => true;

const fun = (param: boolean) => ({
    p: param ? 1 : 2,
    f: () => {
        if (fun2()) {
            return 1;
        }
        return 2;
    }
});
```

### 🙁 Actual behavior

A lot of syntax errors

### 🙂 Expected behavior

It should compile.

Any of following changes resolves all errors:
- Swapping position of `p` (line 4) and `f` (line 5-10)
- Adding parenthesis to line 4 (`(param) ? 1 : 2`, `(param ? 1 : 2)`)
- Changing line 5 to `f() {` or `f: function() {`
- Inserting a semicolon before the if clause at line 6
- Changing the condition of if clause at line 6 to something other than function call, or something like `if (fun2() === true) {`

**Comment by webstrand** [comment]
slightly more minimal reproduction
```ts
declare const param: boolean;
const example = ({
    p: param? 1 : 2,
    f: () => {
        while((1)) {}
    }
});
```

**Comment by DanielRosenwasser** [comment]
Possibly the same as https://github.com/microsoft/TypeScript/issues/32914
