### ISSUE TITLE
Cannot use the `enum[member]` notation in types

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#46473]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.0-beta&ssl=14&ssc=93&pln=1&pc=1#code/MYewdgzgLgBApmArgWxgYQBYEMBOaQAmcMA3gFAyUwBEAFNTALwwAsADADQVXUCUDzFgEYuVGFiYwAnAHZRVAEaSpADnmVgyqVwC+ZMqEiwANiADucHAEFJmXPiIA6LAG4yUAJ4AHYgBlzljbMdniEcM5uBuDQMF64CBC+cABmsMHYoUQA2nTUALpunj4wAArxkEmpthkOcDn0BWQA9E1ibe0dVAB6PTAAojg4IDgAXKVDPjieMADktDMwBCBwEDBgILBwAB4AljHgMEXEMyG1M44wtABMAMw3UrxAA)
    
### 💻 Code

```ts
const enum CharCode {
    "(" = 40,
    ")" = 41,
    "a" = 97,
    "b" = 98,
    "c" = 99,
}

const lowerA = CharCode.a;
type LowerA = CharCode.a;

const parensLeft = CharCode["("];
type ParensLeft = CharCode["("];
//                         ^^^ Error: Property '(' does not exist on type 'CharCode'. (2339)

type ParensLeft2 = typeof CharCode["("]; // No Error
```

### 🙁 Actual behavior

The `enum[member]` notation does not work in types, rendering members that are not valid identifiers inaccessible. 
Using `typeof` is required to make it work.

### 🙂 Expected behavior

The `enum[member]` notation works in types.

**Comment by fatcerberus** [comment]
Because `CharCode` is the type of a value of the enum, a number, and `number["("]` doesn’t make sense.  So if `typeof` didn’t work, you couldn’t do this at all.

Also, `const enum` *can* have runtime representation in certain cases, IIRC.

**Comment by pushkine** [comment]
@fatcerberus I'm not sure what you're trying to say, directly accessing properties `enum.member` always works fine without `typeof` both as a value and as a type

Please explain why `CharCode.a` means `number` but `CharCode["a"]` means `number["a"]`
