### ISSUE TITLE
TSX rejects custom elements

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#4648]
``` jsx
return <my-custom-element />;
```
Results in error: `Property 'my-custom-element' does not exist on type 'JSX.IntrinsicElements'`. As far as I'm aware, this ought to be valid JSX and so compile to:
``` js
React.createElement("my-custom-element").
```
I can get around this by using the second form, but it'd be nice to avoid the check for standard elements (unless it's there for a good reason?)

**Comment by weswigham** [comment]
Have you compiled with `--jsx=react`? Or `--jsx=preserve`? I believe this is the intended behavior for `--jsx=preserve`, as in that case, we rely on declaring `JSX.IntrinsicElements` to typecheck elements. (I think)

**Comment by stevemao** [comment]
@weswigham what if the element doesn't have a class?

**Comment by weswigham** [comment]
Try typing it as `any`?

**Comment by stevemao** [comment]
Isn't `any` a bad pattern?

**Comment by weswigham** [comment]
If you have no type which describes the attributes allowed on the object, `any` may be acceptable, in order to allow any attribute to be applied. Alternatively, write an interface for the component.

**Comment by jyotendra** [comment]
See [this](https://stackoverflow.com/a/37414418/1639453), typescript complains if React component does not start with a capital letter.

**Comment by Alino** [comment]
I confirm that changing my component name first letter to uppercase did fix the problem.

**Comment by ak99372** [comment]
@jyotendra thanks for that starting the component with capital letter fixed the error for me too.
Conclusion:
-> This error is misleading and should spell it out what the actual issue is or...
-> Why on earth is typescript dictating for components to start with uppercase?

**Comment by weswigham** [comment]
It's part of jsx - lowercased names are considered intrinsics, while uppercased names are custom components. They get called differently, too. Intrinsics are just a string passed into createElement, while custom components pass in their constructor.
