### ISSUE TITLE
Feature request: Infer the parameter type from the return type

### ISSUE THREAD

**Issue by cqh963852** [microsoft/TypeScript#46483]
My suggestion meets these guidelines:

While create a function accepct a function param.

If user not give the param function's input type. Can typescript infer input type from retrun type?

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals]

## 💻 Use Cases

```
const createFuntion = <T>(fn: (data?: T) => T) => {
  return () => fn();
}

//const createFuntion: <unknown>(fn: (data?: unknown) => unknown) => () => unknown
createFuntion((input)=>{
  return ""
})

const testFn = (input)=>{
  return ""
};

//const createFuntion: <string>(fn: (data?: string | undefined) => string) => () => string
createFuntion(testFn)
```

The function I created createFuntion accept a function as param, it's type is `<T>(data?: T) => T`

But I didn't give the input param's type.

Wish typescript can infer T from retrun type ,if input param 's not given.

**update:**

**Here is the ts playground demo**

https://www.typescriptlang.org/play?jsx=0#code/MYewdgzgLgBMBOBTAhlRAxArmKBLcMAvDADwAqAfABQBmYAXDFQCarID8jZAlERTDz4wA3gFgAUDBhIomeGCa9C-OlW4BuCQF8JEhCjRYc+MFSq4wAB0xRuysZOmJZ8mACI327rvGhIsNGh0BWJzKxs7CgcpGTkFD21NcT0kVAxsPHAqQKhg73EgA

**Comment by cqh963852** [comment]
any update on this feature request?

**Comment by andrewbranch** [comment]
Duplicate/related:

- https://github.com/microsoft/TypeScript/issues/15114
- https://github.com/microsoft/TypeScript/issues/15196
- https://github.com/microsoft/TypeScript/issues/1265
- https://github.com/microsoft/TypeScript/issues/11440
