### ISSUE TITLE
Iterator return type not constraining typed arrays literals

### ISSUE THREAD

**Issue by oguimbal** [microsoft/TypeScript#46481]
# Bug Report

### 🕗 Version & Regression Information

It has always been there. (tested with every Typescript version available in the playground since the support or typing for iterator return types)

### ⏯ Playground Link

👉 [Reproduction link in playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCS8C86bCgQxmgB4BtAZxigEsA7AcwBo5aBXAWwCM8BdZiqnSYsO3KDwB8AbgBQMgGataAYxjUItOACpqMABQBKAFw44AbxlwrcRNWAAbACZxSAclfMADD1nW4UYBhWKE03DzhvWQBfGSA)

### 💻 Code

```typescript
export type It = Iterator<[string, number], [string, number]>;

function *it(): It {
    yield ['', 0]; // this works ✔️
    return ['', 0]; // this fails ❌
}

```

### 🙁 Actual behavior

The return statement does not constraint the array literal to the right type. Instead, it takes its... I dont know how to put it... its "natural" type ?

### 🙂 Expected behavior

Both yield & return statements should compile.

👉  Workaround:  Force the array to be correctly typed via `return ['', 0] as const`.

**Comment by rbuckton** [comment]
This looks to have been fixed in TypeScript 4.8 as a result of #49736.
