### ISSUE TITLE
Function declarations break inheritance of ambient class declarations

### ISSUE THREAD

**Issue by zOadT** [microsoft/TypeScript#46503]
# Bug Report

### 🔎 Search Terms

- Inheritance
- Function declaration
- Ambient class declaration

### 🕗 Version & Regression Information

- This seems to be the behaviour since Typescript 3.6 (the version that introduced merging [ambient function and class declarations](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#ambient-classes-and-functions-can-merge))
- I tried my best to find this issue, I hope this is no duplicate

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/CYUwxgNghgTiAEUBGBnALjKY30lFK8AgvAN4CwAUPDbgPYB26MArtnTABQAOAXPAxYBbJCBgBKANxVaifoJFjplAL5UqoPHHgAzFg2wBLRvABCPfs0MMA5uP6nlm6NrwEz8EAA80IBsEISCmpaMEZmNjQOC3grWykZWiR5YVEYZTVKKggQHCR4AF4BEAB3M04AIgAJEABPCvEqMKY6HIA6CDobTiQ2qHEgA)

### 💻 Code

```ts
declare class A {
    a: number;
}

declare function B(): B; // (a)
declare class B extends A {
    constructor();
    b: number;
}

let b = new B("Hey")
console.log(b.a) // Property 'a' does not exist on type 'B'.
```

### 🙁 Actual behavior

Line `(a)` breaks inheritance of class `B`.

### 🙂 Expected behavior

`B` should inherit all properties of `A` as it does when you remove line `(a)`.

**Comment by DanielRosenwasser** [comment]
Thank you @Zzzen!
