### ISSUE TITLE
Question about change of type relations rules in regards to index signatures

### ISSUE THREAD

**Issue by osdm** [Microsoft/TypeScript#4651]
From 1.6 spec, rules about subtypes/supertypes:
> * M is a string index signature of type U, and U is the Any type or S has an apparent string
index signature of a type that is a subtype of U.
> * M is a numeric index signature of type U, and U is the Any type or S has an apparent
string or numeric index signature of a type that is a subtype of U.

"U is the Any type or " was added here. But similar rules for assignability weren't changed. That is strange: until 1.6 assignability rules were more relaxed than subtyping rules. What is the rationale for that? Thanks!

**Comment by DanielRosenwasser** [comment]
The original change was performed in PR #4074. Why this isn't part of assignability, I'm not sure, but maybe @ahejlsberg can answer.

**Comment by osdm** [comment]
Well, an example at #4074 deals with assignability, not subtyping. So I guess it's just an error in spec, and changes should be moved or copied to assignability.

**Comment by ahejlsberg** [comment]
It's an error in the spec. The new wording should also be present in the section on assignability. Thanks for pointing it out.
