### ISSUE TITLE
error TS2339: Property 'textSizeAdjust' does not exist on type 'CSSStyleDeclaration'.

### ISSUE THREAD

**Issue by StringManolo** [microsoft/TypeScript#46539]
error TS2339: Property 'textSizeAdjust' does not exist on type 'CSSStyleDeclaration'.                                                                                                            11 body.style.textSizeAdjust = "none";

This experimental CSS feature is really usefull to avoid font-size increasing in smartphones. 

https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

**Comment by andrewbranch** [comment]
See: https://github.com/microsoft/TypeScript-DOM-lib-generator#why-is-my-fancy-api-still-not-available-here
