### ISSUE TITLE
Void type and type parameters constraints

### ISSUE THREAD

**Issue by osdm** [Microsoft/TypeScript#4654]
Spec for 1.6, p. 3.6.1 says:
> Omitting a constraint or specifying type any as the constraint corresponds to specifying the empty object type {}.

This phrase is not clear, because the following code works:
```ts
function foo<A>() {
	return 2;
}
var x = foo<void>();
```
and the following code doesn't
```ts
function foo<A extends {}>() {
	return 2;
}
var x = foo<void>();
```

Could you please clarify what is meant by the word "corresponds" then?

**Comment by ahejlsberg** [comment]
We should remove that statement from the spec and instead say that

* Any type can be a type argument  for a type parameter that has no constraint, and
* A type parameter with no constraint has the same apparent members as type `{}`.

We can probably also remove the notion of a ***base constraint*** as it isn't actually used anymore.
