### ISSUE TITLE
Wrong inferred type when using nullish coalescing operator with a readonly object

### ISSUE THREAD

**Issue by patrickszmucer** [microsoft/TypeScript#46540]
# Bug Report

### 🔎 Search Terms

readonly object nullish coalescing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about readonly and nullish coalescing

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3lAjALngG9sB+AzGASxQHN4BfeAH3gFcVQAzakYAbgBQA0JFgJk6LFABMBAEogowVBACeAHmJQy8CtTr0AfIIETM2AMzwAvNhzwSJbNMFA

### 💻 Code

```
declare const a1: { a?: string } | undefined;

declare const a2: Readonly<{ a?: string }>;

const a3 = a1 ?? a2; // { a?: string | undefined }
```

### 🙁 Actual behavior

Type of `a3` is `{ a?: string | undefined }`

### 🙂 Expected behavior

Type of `a3` is `Readonly<{ a?: string | undefined }>`

**Comment by patrickszmucer** [comment]
@andrewbranch is this actually working as intended? The readonly modifier getting dropped seems like a bug to me - it’s easy to end up with a runtime error in this case.

**Comment by andrewbranch** [comment]
The fact that the readonly and non-readonly properties are assignable to each other (which is not a bug, it’s a usability tradeoff) means it’s easy to end up with a runtime error even if subtype reduction preferred the `readonly` one. I’ll try to ask about this but the assignability makes it feel kind of arbitrary which one is picked.

**Comment by andrewbranch** [comment]
A discussion about this led to #46814, which is definitely a bug and probably related to this report.
