### ISSUE TITLE
Unhelpful "Did you forget to include 'void' in your type argument to 'Promise'" in JS file

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/TypeScript#46570]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.5.0-dev.20211028

**Search Terms**
- javascript
- checkjs
- strict

See https://github.com/microsoft/TypeScript/issues/46570#issuecomment-954340635 for more minimal repro

---

In minimal-hello-world extension sample, using this code:
```js
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
const vscode = require('vscode');

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed

/**
 * @param {vscode.ExtensionContext} context
 */
function activate(context) {
	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated
	console.log('Congratulations, your extension "helloworld-minimal-sample" is now active!');

	// The command has been defined in the package.json file
	// Now provide the implementation of the command with  registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
		// The code you place here will be executed every time your command is executed

		const quickpick = vscode.window.createQuickPick();
		quickpick.items = [{ label: 'step 1' }];

		void (await new Promise(resolve => {
				quickpick.onDidAccept(() => {
						console.log(quickpick.selectedItems.map(i => i.label).join(', '));

						if (quickpick.selectedItems.length === 0) return;

						if (quickpick.selectedItems[0].label === 'step 1') {
								quickpick.value = '';
								quickpick.canSelectMany = true;
								quickpick.items = [{ label: 'a' }, { label: 'b' }, { label: 'c' }];
								// If I uncomment this it will fix the bug
								// quickpick.selectedItems = [];
						}
						else {
								resolve();
						}
				});

				quickpick.show();
		}));

		quickpick.hide();
	});

	context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
function deactivate() {}

// eslint-disable-next-line no-undef
module.exports = {
	activate,
	deactivate
}

```

I see this error:
![image](https://user-images.githubusercontent.com/8586769/139349788-016981c1-b438-4a48-878c-2d17c177076e.png)

This isn't really something we should be warning about in JS.

**Comment by andrewbranch** [comment]
This is very much something we have tried / are trying / would like to solve; there's an experiment up at https://github.com/microsoft/TypeScript/pull/40466 and design notes at https://github.com/microsoft/TypeScript/issues/40505. I do think we should probably modify the error message for JS files though. (But it would be better if we could just not error 😕.)

**Comment by andrewbranch** [comment]
@DanielRosenwasser @rbuckton what should this message even say in JS? We should at least ditch the “did you forget” language, since what we’re asking JS users to do is pretty weird.

**Comment by DanielRosenwasser** [comment]
Maybe

> `Expected 1 arguments but got 0. TypeScript may need a hint that the call to 'new Promise()' produces a 'Promise<void>'.`

**Comment by andrewbranch** [comment]
+JSDoc?

> `Expected 1 arguments but got 0. TypeScript may need a JSDoc hint that the call to 'new Promise()' produces a 'Promise<void>'.`

**Comment by osaimola** [comment]
Hi all, I'm new here and trying to take this one on. Would appreciate some feedback on the pr (especially around localization)
thanks!

**Comment by andrewbranch** [comment]
@osaimola localization happens automatically after the fact. All you have to do is write the English text in `diagnosticMessages.json`.

**Comment by frank-dspeed** [comment]
@DanielRosenwasser @andrewbranch 

This confused me:
Expected 1 arguments but got 0. TypeScript may need a hint that the call to 'new Promise()' produces a 'Promise<void>'.

a new Promise() without a handler or anything in it that calls resolves produces already never and that is correct has the analyzer can not track that it gets resolved some where. it does 100% not return void. new Promise(res=res()) produces void. and even calling res with (undefined) is void. at last out of engine view it translates to the same byte code.

**Comment by nicdard** [comment]
@andrewbranch Is this issue still open? In case I would like to contribute :)

**Comment by andrewbranch** [comment]
@nicdard yes, https://github.com/microsoft/TypeScript/pull/46637 was on the right track but was then abandoned. If you pick it up, please branch off @osaimola’s WIP or cherry-pick their commit(s) so they get attribution for the work they did.

**Comment by nicdard** [comment]
Ok I'll try during this weekend :)

**Comment by jimmywarting** [comment]
this error message is very annoying... don't think a jsdoc should even be necessary (as the resolver argument is optional) 
In many cases you don't need to resolve with anything. it should just know that passing 0 arguments results with undefined

**Comment by fatcerberus** [comment]
@jimmywarting The argument is *not* optional for anything other than a `Promise<void>`.  The default inference in the absence of a type hint is `Promise<unknown>`, hence the error.  TS currently has no mechanism to infer `Promise<void>` automatically.

**Comment by frank-dspeed** [comment]
@fatcerberus it is missing in general a lot of inference by design but it is the best that works at present i am not sure about the state of flow is it solving some issues does it still exist?

**Comment by fatcerberus** [comment]
Right, that’s what this issue aims to solve, so you can write that without complaint.  But in general, the argument is not (and *should not be*) optional if the promise has a type other than `void`: if I have a `Promise<number>` then it doesn’t make sense to let me resolve it without an argument, so I’m glad the compiler makes it required in that case.

I don’t think anybody is arguing with you that your examples should work as written; the fact they don’t is due to a design limitation of generic inference that needs to be solved.  Making the resolver argument optional would of course fix your examples, but in the process it would compromise type safety for TS programs (or even jsdoc-based ones with `checkJs`!) using strongly-typed promises.  So that’s not a good tradeoff, IMO.
