### ISSUE TITLE
TS 4.5.0-dev.20211029: JSX attrbutes not showing in intellisense 

### ISSUE THREAD

**Issue by markusjohnsson** [microsoft/TypeScript#46576]
# Bug Report

### 🔎 Search Terms

jsx tsx props attributes intellisense not working after newline

### 🕗 Version & Regression Information

- This changed between versions 4.4.4 and 4.5.0-dev.20211029

### ⏯ Playground Link

Sorry, cannot use JSX in playground.

### 💻 Code

```ts

function MyComponent({ a, b }: { a: number; b: string; }) {
    return <div/>;
}

function Foo() {
    return <div>
        <MyComponent
                  (invoke intellisense here)
        />
    </div>
}
```

### 🙁 Actual behavior

In 4.5.0-dev.20211029, JSX/TSX props/attributes are not displayed in intellisense completion after a newline.

same line works:
![image](https://user-images.githubusercontent.com/557685/139419362-69b791eb-cd26-4446-a643-f64fac954a72.png)

after newline, does not work:
![image](https://user-images.githubusercontent.com/557685/139419421-8b11ac87-c102-4d3a-806a-f7875465f6e4.png)

### 🙂 Expected behavior

JSX/TSX props/attributes

4.4.4:
both works:
![image](https://user-images.githubusercontent.com/557685/139419520-e93959bc-83a2-41e3-895a-b2de76a24689.png)

![image](https://user-images.githubusercontent.com/557685/139419489-621b4cba-03a5-4ade-bb09-554828e4eba1.png)

**Comment by a-tarasyuk** [comment]
I checked the provided example and it looks like the completion works [Playground](https://www.typescriptlang.org/play?jsx=1&ts=4.5.0-dev.20211029#code/CYUwxgNghgTiAEBbA9sArhBApAygDXgG8BYAKHgvgEsA7AFxBgDMowEBRTREeo+AXzKVq9RizbwAkvRi0AzlTCcQ3enL7AqANwBc8KDQCeAsoNJkmaGmDpVkNeAFlDAYWSIADvZ50AFIX0AGngAIwE9AKg9GjREEMYAblC9OTpZGgBzJP4ASiIhSjg6NBgHAB5NLXgAegA+BNMyCysbOwcAMWRkXzySckKQYtL4Cu1aguEKMuc3T296CcnhReE6xbLqyvHSfiA). Are there any additional steps to reproduce this issue?

/cc @andrewbranch

**Comment by DanielRosenwasser** [comment]
It repros locally on an insiders VS Code, so I assume that when an editor supports snippet completions (the playground doesn't AFAIK) then we're doing something wrong.

**Comment by andrewbranch** [comment]
Ah indeed, this looks like a VS Code bug. I can repro in VS Code, but the TS Server log looks as expected:

```ts
{
  "seq": 0,
  "type": "response",
  "command": "completionInfo",
  "request_seq": 231,
  "success": true,
  "body": {
    "isGlobalCompletion": false,
    "isMemberCompletion": true,
    "isNewIdentifierLocation": false,
    "entries": [
      {
        "name": "a",
        "kind": "JSX attribute",
        "kindModifiers": "",
        "sortText": "11",
        "insertText": "a={$1}",
        "replacementSpan": {
          "start": {
            "line": 11,
            "offset": 7
          },
          "end": {
            "line": 11,
            "offset": 8
          }
        },
        "isSnippet": true
      },
      {
        "name": "b",
        "kind": "JSX attribute",
        "kindModifiers": "",
        "sortText": "11",
        "insertText": "b=\"$1\"",
        "replacementSpan": {
          "start": {
            "line": 11,
            "offset": 7
          },
          "end": {
            "line": 11,
            "offset": 8
          }
        },
        "isSnippet": true
      },
      {
        "name": "key",
        "kind": "JSX attribute",
        "kindModifiers": "declare,optional",
        "sortText": "12",
        "insertText": "key={$1}",
        "replacementSpan": {
          "start": {
            "line": 11,
            "offset": 7
          },
          "end": {
            "line": 11,
            "offset": 8
          }
        },
        "isSnippet": true
      }
    ]
  }
}
```

**Comment by DanielRosenwasser** [comment]
Nice, I'll defer to Andrew - @mjbvz can you transfer this to the VS Code side? I don't have permissions to do so.

**Comment by markusjohnsson** [comment]
I've pushed my repro here: https://github.com/markusjohnsson/ts-46576

**Comment by andrewbranch** [comment]
Just verified that our response on a single-line and on the split-line locations looks basically identical, so yeah, I think VS Code is just incorrectly filtering these out for some reason?

**Comment by markusjohnsson** [comment]
Was this ever transferred to the vscode tracker?
