### ISSUE TITLE
4.5.0-dev.20211029: Does not throw error `TS5056: Cannot write file '/to/file/path' because it would be overwritten by multiple input files.`

### ISSUE THREAD

**Issue by sosukesuzuki** [microsoft/TypeScript#46577]
# Bug Report

### 🔎 Search Terms

`TS5056`, `because it would be overwritten by multiple input files`

### 🕗 Version & Regression Information

- This changed between versions  4.4.4 and `4.5.0-dev.20211029`

### ⏯ Playground Link

This bug cannot be reproduced in Playground.

### 💻 Code

Sorry this bug cannot be reproduced as as simple code. Instead of I've created the repository to reproduce this.

https://github.com/sosukesuzuki-sandbox/ts-4.5-bug-reproduce

### 🙁 Actual behavior

Does not throw error `TS5056: Cannot write file '/to/file/path' because it would be overwritten by multiple input files.`

### 🙂 Expected behavior

Throw error `TS5056: Cannot write file '/to/file/path' because it would be overwritten by multiple input files.`

**Comment by DanielRosenwasser** [comment]
Isn't this correctly catching an error now? The two files would have been written to the same output `.js` file.

If you're using a bundler or similar build tool that does its own compilation, you can turn `--noEmit` on and this should work.

**Comment by andrewbranch** [comment]
The error is correct and it’s _gone_ from 4.5.

It seems that `matchFiles` is broken in 4.5; it’s not picking up the TSX file at all. Investigating.
