### ISSUE TITLE
Tuple Union Type Handling

### ISSUE THREAD

**Issue by SamiSdd** [microsoft/TypeScript#46579]
I think the code below is valid
![image](https://user-images.githubusercontent.com/1784844/139465928-18c7168a-89d1-4c5d-821e-98cdb2160dfa.png)
![image](https://user-images.githubusercontent.com/1784844/139466037-655c22b7-4417-460e-9e96-a0268326dd6c.png)

**Comment by fatcerberus** [comment]
I don't think TS even has a way, internally, to track the correlation between the two values here.  The compiler just sees an expression of the form `x + y` where `x` and `y` are independent terms of type `string | number` (because it doesn't know which type `par` is) and errors accordingly.

**Comment by andrewbranch** [comment]
Covered by #30581
