### ISSUE TITLE
Extra `?` added to method in method signature completion for optional method

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#46589]
# Bug Report

### 🔎 Search Terms
- Method signature completions
- suggest / suggestions
- completions

### 🕗 Version & Regression Information
4.5.0-dev.20211029

### 💻 Code

For the code:

```ts
interface IFoo {
    barOpt?(x: number): void;
}

class Foo implements IFoo {
    |
 }
```

Complete `barOpt` inside `Foo`

### 🙁 Actual behavior

`barOpt ` gets added with a `?`

```ts
interface IFoo {
    barOpt?(x: number): void;
}

class Foo implements IFoo {
    barOpt?(x: number): void {
        
    }
}
```

### 🙂 Expected behavior

Since we have implemented the method, I'd expect us the remove the `?`

**Comment by DanielRosenwasser** [comment]
This is especially true under [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes)

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
