### ISSUE TITLE
There doesn't seem to be way to suppress a warning if I set removeComments to false

### ISSUE THREAD

**Issue by BobFrankston** [microsoft/TypeScript#46596]
# Bug Report

### 🔎 Search Terms

removeComments warning

![image](https://user-images.githubusercontent.com/5490484/139510216-d0222bdd-e34c-4446-a015-bf306746a339.png)

### 🕗 Version & Regression Information

It started recently -- perhaps with the automatic upgrade to 4.2.4. I know it's just a warning but I want to be "warning-free" to assure clean code. I can suppress warnings in code but I can't suppress this warning about tsconfig.

This is an annoying warning that seems to have appeared, perhaps, with 4.2.4

My editorial aside is that I understand that these warnings are an effort to impose good practices but what is attractive about TS is that I can make my own decisions. Thus the need to suppress such warnings. I am reporting this as a bug because the inability to get to "0 problems" is an issue for those of us who want clean code.

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/5490484/139510227-e7f49d6f-a809-4878-9ceb-f64d4cf0e4cc.png)

If I say I don't want to remove comments I don't need a warning 100% of other times telling me that I'm a terrible person. I don't want to be told that I have or am a problem.

### 🙂 Expected behavior

Just let me say false, per perhaps "false!" to say, yes, I have read the terms of service and I am willing to waste precious computer bits on keeping the comments in my JS code

**Comment by andrewbranch** [comment]
> telling me that I'm a terrible person

<img width="348" alt="image" src="https://user-images.githubusercontent.com/3277153/139510620-ab33ea46-902b-4b64-b63c-593484594394.png">

I can't find a warning like that. Maybe you were paraphrasing, but having the exact message would really help me understand what's going on 😉

**Comment by BobFrankston** [comment]
if I set removeComments to false I get the yellow tilde and a warning that adding comments makes the output file larger. I got that. But how do I suppress that warning message.

![image](https://user-images.githubusercontent.com/5490484/139511840-d5ab56a0-9f33-4fb6-93b8-500b6e44c6b7.png)

**Comment by fatcerberus** [comment]
I... don't think that's a TypeScript warning?  It says the message was generated by Microsoft Edge Tools.

**Comment by fatcerberus** [comment]
IMO that lint rule is kind of baffling - if someone cares about code size over-the-wire enough to strip the documentation from their code, thye'd just have a minifier in the loop, which would render the whole debate moot.

**Comment by BobFrankston** [comment]
I can accept such suggestions as long as I can say "OK, fine, now stop reminding me". Even better if I can do that globally.

**Comment by fatcerberus** [comment]
That's fine, but this message is not from TypeScript, so there's nothing TS can do about it.  It's to do with something that's been enabled in your webhint config: https://webhint.io/

**Comment by DanielRosenwasser** [comment]
I've filed https://github.com/webhintio/hint/issues/4839

**Comment by BobFrankston** [comment]
Thanks. I guess should blame the edge installation for the "favor". One downside of VScode is too many chefs. Before we close this out any hint on how to fix this in webhints -- I'll look myself but figure I'd ask.

**Comment by andrewbranch** [comment]
Maybe you have this VS Code extension installed?

<img width="365" alt="image" src="https://user-images.githubusercontent.com/3277153/139513769-7f7fddf2-98d7-48ff-95fd-e4de2f23adc2.png">

Its [README](https://marketplace.visualstudio.com/items?itemName=webhint.vscode-webhint) has some info on configuration. (Of course you could just disable the extension if you didn't mean to be using it.)

**Comment by BobFrankston** [comment]
The reason it was not obvious is that I had **not** installed WebHint -- I had installed EdgeTools and it installed WebHint unasked. The solution, for now, is to disable edgeTools and report the problem there.

![image](https://user-images.githubusercontent.com/5490484/139514315-20f0314a-bbc8-43d0-8483-b05fba08d397.png)

**Comment by BobFrankston** [comment]
I should add that the reason this is so annoying is the cascading effect of telling me to install tslib and then warning me about settings when I'm trying to get other work done. And then adding injury by not giving me a "click on this to avoid this message" button with it all seeming to be tsc related. A very bad UX.
