### ISSUE TITLE
Object literal with method containing required parameter can be assigned to interface with method containing optional parameter

### ISSUE THREAD

**Issue by hbo-iecheruo** [microsoft/TypeScript#46591]
# Bug Report

### 🔎 Search Terms

object literal assign interface optional parameter

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (v3.3.3 - v4.4.4)
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/JYOwLgpgTgZghgYwgAgJICUIAcoHtkDeAUMsgLYRgAWuAJgBQBucANgK4QD8AXMgM5gooAOYBKXgAU8ZYHwgAeAUJDCAfAG4iAXyJEEuEAOSYcuXhmx5kAXkIlSyAPSO0yWvhC4wyCAA8sEAje1LLIYPj6ZFjALCgARoFwbHJhVChgAJ4ByLgwyADycQBWgd4swJBQrG64EHzInt5kcGAIVKkoAAYWWLidyKCV8Ej2pM7IACppA+DQwyi0EDCgFcAGyFAQAI5swJv11ChYcFUUlcidzOwQ-Qk5WGBrIKyjyHB8GSAI5JQ0DFccXhKESiOwOcEbShsKAgZAAiCacE6HREPy9KDeQZzRAoVAAdVwUAA1idcGwQLQwT9qHReExWBwePxBCCbKpkFJcDI5IoWSoNNpdPpDN4CcTSeTaOYxSS8JKbFSxi4pihItFYlABvV3CJkAB3KgtVxo0rINKbAA0A0x9U2JSCusObz4fGAwhAFHAyASCCSKU6Zz+-XcdQaXjNcEY6WmQmEVG8rvdLWhEFe70+30DdHp1yBfLEkmksgUwP5iohmzA0Nh8MRDmRQA)

### 💻 Code

```ts
interface IRepro {
  method(value?: string): Promise<string>;
}

const repro: IRepro = {
    // I do not expect this to compile because the type of Object literal does not match the `IRepo` interface
    // The interface definition requires the parameter `value` be optional
    async method(value: string) {
        return value.substr(0);
    }
}

repro.method(); // This call will result in a undefined exception because the interface implementation never expects undefined to be passed as an argument

export interface IWorkaround {
  method: (value?: string) => Promise<string>;
}

const workaround: IWorkaround = {
    // The compiler is doing what I expect here, it is rejecting the assignment because `method` does not have the right signature
    async method(value: string): Promise<string> {
        return value.substr(0);
    }
}
```

### 🙁 Actual behavior

The compiler allows an object literal to be assigned to an incompatible type.

The object literal contains a method with a required parameter, the type being assigned to has the same method but with an optional parameter.

Meaning that a caller can omit the optional parameter but the implementation assumes the parameter cannot be omitted

### 🙂 Expected behavior

A compiler error showing a type mismatch in the methods parameters

**Comment by fatcerberus** [comment]
This is likely due to method bivariance.

**Comment by hbo-iecheruo** [comment]
Yup that looks like it.

Awesome and thanks a ton for the pointer, I tried looking around for an explanation but could not find one.

**Comment by hbo-iecheruo** [comment]
P.S The following (recommended) es-lint rule steers developers toward the safer syntax
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/method-signature-style.md

**Comment by fatcerberus** [comment]
Note that it may not always be practical depending on your type hierarchy; for example if this were enforced for methods too then `Array` would be invariant (which is a big part of the reason it isn’t done).
