### ISSUE TITLE
Parser treats comma expression as type arguments

### ISSUE THREAD

**Issue by mheiber** [microsoft/TypeScript#46604]
# Bug Report

The last line below evaluates to `true` but is rejected by TS due to `< b, c >` being parsed as a type parameter list:

```ts
const a = 1;
const b = 2;
const c = 3;
const d = 4;
   (a < b, c > (d));  // Error: c refers to a value, but is being used as a type here
```

Adapted from https://github.com/rust-lang/rfcs/pull/2527#issuecomment-414635205.

Sorry if this issue was known already.

### 🔎 Search Terms

turbofish
ambiguity
generics
"refers to a value"

### 🕗 Version & Regression Information

3.5.1 through 4.5.0-beta

This is the behavior in every version I tried, and I reviewed the FAQ for entries about parsing and generics.
3.33 has a slightly different error message.

Note: when using `// @ts-check` on a JS file the only error is that the left side of the comma expression is unused (good).

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/MYewdgzgLgBAhjAvDAjAbgFCkrARkmAJk22hmAIGYTwyATAgFkxlYAoEAeGXAGnJgA+GGzoBKMWlYB6aTACCwYAFMADlGUNcATxgApAMoxlYAOYBLMMoj9lANzgAbAK5wNEGFBAwABlABOzso+GLKsAD6sMJEwAHowAKL+-iD+AFzGMP7KAGbK-h5e8DAOLsr8uM6w5h64ypamMM4QmvAeCFDaqsowABb5yqFy0VHxSSnpAtl5BZ7eCKVBFVUwNTz1Zk0tDHDtnl09-dlDrGPJqRkAKr1rygAeqtkQEObgqx5gILDATo5wuI5BkA)

[ts-ast-viewer](https://ts-ast-viewer.com/#code/MYewdgzgLgBAhjAvDAjAbgFCkrARkmAJk22hmAIGYTwyATAgFkxlYAoEAeGXAGnJgA+GGzoBKMWlYB6aTACCwYAFMADlGUNcATxgApAMoxlYAOYBLMMoj9lANzgAbAK5wNEGFBAwABlABOzso+QA)

### 💻 Code

```ts
const a = 1;
const b = 2;
const c = 3;
const d = 4;
   (a < b, c > (d)); 
//  |   |  ^ Error: e refers to a value, but is being used as a type here
//  |   ^ Error: c refers to a value, but is being used as a type here
//  ^ Error: This expression is not callable
```

### 🙁 Actual behavior

- Errors:
    - `Error: This expression is not callable`
    - `Error: c refers to a value, but is being used as a type here`
    - `e refers to a value, but is being used as a type here`

- And the AST contains CallExpression

### 🙂 Expected behavior

- No errors
- The AST contains BinaryExpression with LessThanToken etc. instead of CallExpression.

**Comment by whzx5byb** [comment]
It seems similar to https://github.com/microsoft/TypeScript/issues/33639

**Comment by mheiber** [comment]
> It seems similar to #33639

Looks like a duplicate. Thanks, closing

**Comment by MartinJohns** [comment]
Is there any legit reason to write code like this?

**Comment by mheiber** [comment]
> Is there any legit reason to write code like this?

Humans no, machines maybe: https://github.com/microsoft/TypeScript/issues/46604#issuecomment-956422073

**Comment by mheiber** [comment]
> Is there any legit reason to write code like this?

Humans no, machines maybe: https://github.com/microsoft/TypeScript/issues/36662
