### ISSUE TITLE
metadata only exists when at least a decorator is used

### ISSUE THREAD

**Issue by ktangels** [microsoft/TypeScript#46608]
# Bug Report
 
In the document, it says " When enabled, as long as the reflect-metadata library has been imported, additional design-time type information will be exposed at runtime. "
https://www.typescriptlang.org/docs/handbook/decorators.html#metadata

but the truth is, import the lib is not the only condition.
Is this a bug or a mistake of  the document?

### 🕗 Version & Regression Information

tsc 4.4.4

### 💻 Code

import "reflect-metadata";

function Empty(): PropertyDecorator {
  return () => {};
}

class A {
  @Empty()
  a: string = "";

  b: string = "";
}

const a = new A();
console.log(1,Reflect.getMetadata("design:type", a, 'a'));
console.log(2,Reflect.getMetadata("design:type", a, 'b'));

### 🙁 Actual behavior

1 [Function: String]
2 undefined

**Comment by MartinJohns** [comment]
No expected behaviour? That's unexpected.

**Comment by MartinJohns** [comment]
Only emitting metadata for decorated classes is intentional, see #11861.

**Comment by ktangels** [comment]
> Only emitting metadata for decorated properties is intentional, see #11861.

thanks
