### ISSUE TITLE
How to compile TS in VSCode?

### ISSUE THREAD

**Issue by codelegant** [Microsoft/TypeScript#4660]
As the title.

**Comment by kitsonk** [comment]
[Here](http://lmgtfy.com/?q=visual+studio+code+compile+typescript)

**Comment by codelegant** [comment]
I find a way to compile TS----  [This](https://code.visualstudio.com/Docs/languages/typescript#_tsconfigjson).
But I have to write the filename in tasks.json `args` like below
```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": ["HelloWorld.ts"],
    "problemMatcher": "$tsc"
}
```
Is there a easyway to compile TS?Not hardcode the filename in tasks.json.

**Comment by codelegant** [comment]
I shoul writer the tasks.json like below:
```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "showOutput": "silent",
    "args": [],
    "problemMatcher": "$tsc"
}
```
default user current ts file's name;
