### ISSUE TITLE
assignment semantics for callable object types

### ISSUE THREAD

**Issue by icefapper** [Microsoft/TypeScript#4661]
hello
consider this: var pickyCallable: {(l: any): any, (): aType };
in the above example, only functions that have _both_ (l: any): any and (): aType signatures could be assigned to this "pickyCallable" thing; could I ask if I'm right?

**Comment by mhegazy** [comment]
the general rule is you can pass more arguments to a function than it expects, as they will be ignored, but the opposite is not true.

so
```ts
var pickyCallable: { (l: any): any, (): number };

pickyCallable = (a) => a; // Error. pickyCallable can be called with no arguments, but this function expects one
pickyCallable = () => 2; // OK, as the additional argument will be ignored
```
