### ISSUE TITLE
Type of Array.prototype[Symbol.unscopables] is wrong

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#46616]
# lib Update Request

In `lib.es2015.symbol.wellknown.d`:

```ts
interface Array<T> {
    /**
     * Returns an object whose properties have the value 'true'
     * when they will be absent when used in a 'with' statement.
     */
    [Symbol.unscopables](): {
        copyWithin: boolean;
        entries: boolean;
        fill: boolean;
        find: boolean;
        findIndex: boolean;
        keys: boolean;
        values: boolean;
    };
}
```

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

It is an object, instead of a function that returns an object.

**Comment by MartinJohns** [comment]
It being an object seems to be right, according to the MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/unscopables

**Comment by Jack-Works** [comment]
The current definition in TypeScript is a function

**Comment by MartinJohns** [comment]
Related: #34610

It was wrongly fixed. :-D
