### ISSUE TITLE
Typescript may not recognize jsdoc `@type` on class method

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#46611]
# Bug Report
Typescript may not recognize jsdoc `@type` on class method

### 🔎 Search Terms
`jsdoc` `@type` `@typedef` `class method` `strict` `@ts-check`

### 🕗 Version & Regression Information
Version 4.4.4
Version 4.5.0-dev.20211028

### Reproduce Repo
https://github.com/loynoir/reproduce-typescript-46611.js

### 🙁 Actual behavior
```js
  // TS7006: Parameter 'a' implicitly has an 'any' type.
  // TS7006: Parameter 'b' implicitly has an 'any' type.
  /**
   * @type {bar}
   */
  bar1(a, b) {
    void a;
    void b;
    return false;
  }


  // a is typed as string, and b is typed as number
  /**
   * @type {(...args:Parameters<bar>)=>ReturnType<bar>}
   */
  bar2(a, b) {
    void a;
    void b;
    return true;
  }
```

### 🙂 Expected behavior
```js
  // a is typed as string, and b is typed as number
  /**
   * @type {bar}
   */
  bar1(a, b) {
    void a;
    void b;
    return false;
  }


  // a is typed as string, and b is typed as number
  /**
   * @type {(...args:Parameters<bar>)=>ReturnType<bar>}
   */
  bar2(a, b) {
    void a;
    void b;
    return true;
  }
```

**Comment by andrewbranch** [comment]
@sandersn is this a pattern we want to support? I've never seen it before, personally, but it seems fairly unambiguous and analogous to `@type` on a function declaration, which [we support](https://www.typescriptlang.org/play?filetype=js#code/PQKhAIAEBcE8AcCm4DeAKAhgLnAZ2gE4CWAdgOYCU4AvAHzgYmwC+4IwAUAGYCuJAxtCIB7EuC7DhmKimZA).

**Comment by loynoir** [comment]
@andrewbranch @sandersn 

FYI, I try to reuse existing types on class method.

So, I try `@type {X}` approach, which is not working.
```js
/**
 * @type {bar}
 */
bar1(a, b) {
    void a;
    void b;
    return false;
}
```

Then, I came up with idea `@type {(...args:Parameters<X>)=>ReturnType<X>}` workaround, which is working. 
```js
/**
 * @type {(...args:Parameters<bar>)=>ReturnType<bar>}
 */
bar2(a, b) {
    void a;
    void b;
    return true;
}
```

**Comment by sandersn** [comment]
`@type` should work on methods the same as functions, and as @loynoir's workaround shows, it very nearly does. As long as this is a simple fix or a small addition, it's worth fixing.
