### ISSUE TITLE
Add alias operator

### ISSUE THREAD

**Issue by AtlasLuca** [microsoft/TypeScript#46613]
# Suggestion
Add alias operator, this would create a link to the original object.

## 🔍 Search Terms
"alias"
"alias operator"
"alias prefix"

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.
"alias"

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [Y] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [Y] This wouldn't change the runtime behavior of existing JavaScript code
* [Y] This could be implemented without emitting different JS based on the types of the expressions
* [Y] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [Y] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Also this would be easy to implement, since u can just replace the names of the aliases with the originals.

## ⭐ Suggestion

Add an alias operator that would be used like this:
```typescript
var examplea = 10;
alias exampleb = examplea; //exampleb is now linked to examplea
examplea += 10; //examplea is now 20
console.log(exampleb); //will print "20", since exampleb is linked to examplea
exampleb -= 5; //exampleb is now 15, thus, examplea is now 15 too
console.log(examplea); //will print "15"
```

this would compile to:
```javascript
var examplea = 10;
examplea += 10;
console.log(examplea);
examplea -= 5;
console.log(examplea);
```

## 📃 Motivating Example
would allow multiple names for a function, for example:
if i have a class called color, i could add an alias called colour, which would be nice

## 💻 Use Cases

allowing multiple names for one object and making it easy to add aliases.
currently there are alot of problems trying to do it, like when u want to make a class `color` and `colour`, you'ld need to either duplicate classes, or make one of them the other, which is not the same.

**Comment by andrewbranch** [comment]
Emphasis mine:

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, **new syntax sugar for JS**, etc.)
