### ISSUE TITLE
some types in 4.5.0 aren't correctly resolving to same types in 4.4.4

### ISSUE THREAD

**Issue by suneettipirneni** [microsoft/TypeScript#46624]
# Bug Report
I recently ran into the this strange error when I updated to typescript 4.5.0-beta, generic types that were resolving properly in 4.4.4, are not correctly resolving in 4.5.0-beta. Instead 4.5.0 returns a unions of all of the possible values while the same code in 4.4.4 returns a narrowed generic type.

### 🔎 Search Terms
4.5.0-beta, unions, generics

### 🕗 Version & Regression Information
typescript@beta, 4.5.0-beta, typescript@next

- This changed between versions 4.4.4 and 4.5.0-beta

### ⏯ Playground Link
Same code for both versions:

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/KYDwDg9gTgLgBDAnmYcDWBLAdgEzgXjgCIItgi4AfYmAdwguqJgAsphyBuAKG9ElhxsMYFABmAQwDGqAPJgYGUgGcAPABUAfHADe3OEJEBbAPwAuOOp4GkKc+mw4eAX1625ZAruc93l+l46Ptx+6mwcgcEhyB7A8ooqXvFKWGqyZJq+Mf4QyYmEeaka9JnRKJbhcQopSdUqGpWl3MKikjJwALISYCg4AJJYIuLSVQmpuvoGxKTkFumjKcrWU8z0RBbq9IVLkwbMlesV7AukLrz80PB+A0NtwACiIDBQ0jDQqpPqcKAiuMoOuAANNxtIQvj9gH8AThJiZOt1ejdWiNtgBtdQAXW+T0hOH+21U2DEojgfWMml2cDhZOARkpFjIADdRJM5nUivMmhdBH4AAoSF5GNTgnFQzC4UGTah6KZTdz2KyU5xwABkcAJSOGMkez1e7y0TRwwCkABsBagxABXLBSMZwADmwBgmruADEoBAjABlZ7Ye0fAwi3546HAzQACgg7OU9n5guFmgAlBYXSMdS9bfqmlIVPB2MpLSb4IRHc7BsiZO7PT6oH7wzoEDELAByOgQZtwZyJzhAA)

### 💻 Code

```ts
export type kind = "one" | "two" | "three";

export interface Options<T> {
  item?: T;
  type?: kind;
}

type One = {};
type Two = {};
type Three = {};

type OneOptions = Options<One>;
type TwoOptions = Options<Two>;
type ThreeOption = Options<Three>;

interface MappedInterfaceOptions {
    "one": OneOptions;
    "two": TwoOptions;
    "three": ThreeOption;
}

export type InterfaceExtractor<
  T extends kind,
> = T extends kind
  ? MappedInterfaceOptions[T] extends Options<infer Item>
    ? Item
    : never
  : Options<One>;

export type Params<T extends kind> = { type?: T; } & Options<InterfaceExtractor<T>>;

declare function getInterfaceFromString<
  T extends kind,
>(options?: Params<T>): InterfaceExtractor<T>;

// Typescript 4.4.4 states the type is `Two`, 4.5.0 states the type is `One` | `Two` | `Three`
const result = getInterfaceFromString({ type: 'two' });
```

### 🙁 Actual behavior

In typescript 4.4.4 the type is correctly resolved to `Two`, whereas in typescript 4.5.0 the type is resolved to `One | Two | Three` which is incorrect.
4.4.4:
<img width="135" alt="Screen Shot 2021-11-01 at 1 27 03 PM" src="https://user-images.githubusercontent.com/77477100/139713784-e51545c4-dd40-4df3-94e4-ac890d7bd227.png">
4.5.0-beta:
<img width="234" alt="Screen Shot 2021-11-01 at 1 27 22 PM" src="https://user-images.githubusercontent.com/77477100/139713823-586d9bcd-b3b8-46f5-95f5-eb07105b33a3.png">

### 🙂 Expected behavior

The correct type for `result` in the playground and the codesample is `Two`, not `One | Two | Three`, typescript 4.5.0 should resolve to this type.

**Comment by suneettipirneni** [comment]
it seems that this line causes the discrepancy:

```ts
export type Params<T extends kind> = { type?: T } & Options<T>;
```

Changing this to:
```ts
export type Params<T extends kind> = { type?: T };
```

Resolves the correct type, however I'm not sure why the original typedef causes issues on 4.5.0

**Comment by andrewbranch** [comment]
The issue is we're seeing

```ts
const result = getInterfaceFromString({ type: 'two' });
//                                    { type?: kind }
```

instead of

```ts
const result = getInterfaceFromString({ type: 'two' });
//                                    { type?: "two" }
```

Using `getInterfaceFromString({ type: 'two' } as const)` gets the result you expect. Looks like a contextual typing regression.

**Comment by andrewbranch** [comment]
Unclear if fixing this in 4.5 will be possible without other breaking changes, but worth looking into.

**Comment by sandersn** [comment]
Note that both 4.5 and 4.4 say that the type is `Two` from `tsc`.

**Comment by sandersn** [comment]
Broken by #46052

**Comment by andrewbranch** [comment]
The surprising thing is that `exactOptionalPropertyTypes` isn't even enabled in this repro. @ahejlsberg any ideas?

**Comment by ahejlsberg** [comment]
Ooo, this is a nasty little issue. During union type construction we repurpose certain `TypeFlags` to gather data about what kinds of types are in the union. But we then have a test for whether a union should be marked primitive-types-only, and that test erroneously assumes the original meanings of the `TypeFlags`. It broke because we moved some of the repurposed flags around. I have a fix for it, will put up a PR shortly. If possible, we should take this for 4.5.1.

**Comment by ahejlsberg** [comment]
Here's a simplified repro:

```ts
export type Kind = "one" | "two" | "three";

declare function getInterfaceFromString<T extends Kind>(options?: { type?: T } & { type?: Kind }): T;

const result = getInterfaceFromString({ type: 'two' });  // Should be "two", not Kind
```
