### ISSUE TITLE
Intersection type of generics gives warning in .d.ts.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#4662]
```ts
declare function assign<Target, Source>(target: Target, source: Source): Target & Source;
//                                                                                ~~~~~~
// Warning: Cannot find name 'Source'.
```

**Comment by mhegazy** [comment]
I can not get a repro for this. passing this in a empty file compiles with no errors. Looks like there is more code needed to make the issue appear.

**Comment by vilic** [comment]
Seems to be a bug related to Visual Studio Code.

Three files to repro:

1. `tsconfig.json` (A empty `{}` will do).
2. `test.d.ts`:
  ````ts
  declare function foo<T, U>(): T & U;
  ````
3. `test.js` (Empty file will do).

Open `test.d.ts` then `test.js`, the warning would appear.

**Comment by mhegazy** [comment]
Aah.. looks like you need to update your VSCode to latest TypeScript. follow the instructions in https://github.com/Microsoft/TypeScript/issues/247#issuecomment-136776941 to  update your VSCode to latest typescript version
