### ISSUE TITLE
TypeScript exclude node_modules not working at all

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/TypeScript#46634]
# TypeScript exclude node_modules not working at all

> Bug Report

https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/project-config/tsconfig.json.md

```json
{
    "compilerOptions": {
        "target": "es5",
        "lib": [
            "dom",
            "dom.iterable",
            "esnext"
        ],
        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": false,
        "jsx": "react",
        "outDir": "./dist/",
        "baseUrl": "./",
        "paths": {
            "@/*": ["src/*"],
            "@/components/*": ["src/components/*"]
        },
    },
    "include": [
        "./src/**/*"
    ],
    "exclude": [
        "node_modules"
    ],
    "files": [
        "./test/test.ts"
    ]
}
```

```sh
$ cd test

$ tsc -v
# Version 4.1.3

$ node -v
# v12.18.0

$ tsc ./test.ts

```

![image](https://user-images.githubusercontent.com/7291672/139773517-afbc0822-b720-4fdc-afb4-cb3739243fb2.png)

https://github.community/t/typescript-exclude-node-modules-not-working/209865

**Comment by xgqfrms** [comment]
# solution

> just add `--skipLibCheck` params in the CLI

```js
# ✅
$ tsc --skipLibCheck ./test.ts

```

**Comment by ritschwumm** [comment]
wait, do you say if you add it in the compilerOptions is doesn't work, but as a command line parameter it does? that would be.... surprising.

**Comment by xgqfrms** [comment]
> wait, do you say if you add it in the compilerOptions is doesn't work, but as a command line parameter it does? that would be.... surprising.

that's right.

**Comment by andrewbranch** [comment]
Your tsconfig is completely ignored when you specify files on the command line instead of `-p`.

```
$ tsc --showConfig ./test.ts
{
    "compilerOptions": {},
    "files": [
        "./test.ts"
    ]
}
```

**Comment by xgqfrms** [comment]
@andrewbranch without `files `, it's still has that question.

**Comment by andrewbranch** [comment]
https://www.typescriptlang.org/tsconfig/#types

**Comment by xgqfrms** [comment]
not. work, too

```js
{
    "compilerOptions": {
        "target": "es5",
        "lib": [
            "dom",
            "dom.iterable",
            "esnext"
        ],
        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noFallthroughCasesInSwitch": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "noEmit": false,
        "jsx": "react",
        "outDir": "./dist/",
        "baseUrl": "./",
        "paths": {
            "@/*": ["src/*"],
            "@/components/*": ["src/components/*"]
        },
        "types": []
    },
    "include": [
        "./src/**/*"
    ],
    "exclude": [
        "node_modules"
    ],
    "files": [
        "./test.ts"
    ]
}

```


![image](https://user-images.githubusercontent.com/7291672/140616988-cc7a1d20-1073-4156-b325-950782406906.png)

**Comment by andrewbranch** [comment]
Use `--explainFiles` to show why every file is included. You cannot prevent the inclusion of files that are included by other files. All of this is completely working as intended and [explained in the docs](https://www.typescriptlang.org/tsconfig#exclude). If you still have questions after reading them, please ask on StackOverflow or the TypeScript Discord. This issue tracker is not a good place to get support. If you file something here, you need to thoroughly search for duplicates and completely fill out the issue template.
