### ISSUE TITLE
Peculiar inference of type unions in if-statements

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/TypeScript#46639]
# Bug Report

### 🔎 Search Terms

type union, if statement, type inference, narrowing

### 🕗 Version & Regression Information

Appears to happen in all versions between 3.3.3 and 4.4.4 on the playground.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type unions, type inference, narrowing (and it could be [this](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-isfoox-narrow-x-to-foo-when-isfoo-is-a-type-guard), maybe? but there's no real description, just a headline, so.)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/AQ4MwVwOwYwFwJYHsrAQZwKIBsCmBbXKOACiiQBNcAuYAOUtwEpbyq11gcCi5gBvALAAoUKABOuOBHGoyjAHRtcAFQCeAB1zAAvHuABGJgG4RYgL4izoSLEQoOAQQgVk8qrQZUWwZR2AAEioAsgAyzq5I3ITEAtZiktKyHNG87szAAGSZwOkKcACGAOZ0BYS6+gBEjgCqACIAkgDylSbxwJbC7bbwyKgYAGoIVEjpnow+fhiBIaFDI6mxQqJiwIky-Vh4MaTKTFk5eYUlZdp6OsCVAw11mC1tKyCd7TAo6Hx+FxRIMBA7CgBHCC4cRqADKuDw8CQ4hIlQUhFcBVaAEJTF1HmgwLkMBE3HtgAAfQkcea4UZ7fbLVa+RjoixWTEIbEkQbDcnpfbEpwufETKntEDKemgTpAA)

### 💻 Code

```ts
    function isElement(node: Node): node is Element {
      return (node.nodeType === 1);
    }

    function isAudio(node: Node): node is HTMLAudioElement {
      return isElement(node) && (node.tagName === "AUDIO");
    }

    function isVideo(node: Node): node is HTMLVideoElement {
      return isElement(node) && (node.tagName === "VIDEO");
    }

    const node = document.querySelector(".media")!;

    if (isAudio(node) || isVideo(node)) {
      node; // 👈 HTMLAudioElement
    }

    if (isVideo(node) || isAudio(node)) {
      node; // 👈 HTMLAudioElement
    }
```

### 🙁 Actual behavior

`node` is inferred as `HTMLAudioElement` - regardless of which type guard appears first.

### 🙂 Expected behavior

`node` should be inferred as `HTMLAudioElement | HTMLVideoElement`, because that is what a person would naturally expect after checking two type guards - and this ensures safe access only to properties that these types have in common.

(It's hard to tell if `HTMLAudioElement` is preferred here for a reason or whether that's somehow arbitrary, based on source order or something else? By the looks of it, `HTMLAudioElement` does have all the properties of `HTMLVideoElement`, and not vice versa, so maybe that is the explanation? Either way, seeing `HTMLAudioElement` in the inferred type is confusing.)

**Comment by MartinJohns** [comment]
Subtype reduction. Every `HTMLVideoElement` is also a `HTMLAudioElement`, because all properties are present.

You want #45218.

**Comment by andrewbranch** [comment]
> Every `HTMLVideoElement` is also a `HTMLAudioElement`

What an absurd assertion to make, anywhere except for on this issue tracker 😅

**Comment by fatcerberus** [comment]
It’s a bit like saying “every DVD player is also a CD player” which is demonstrably not the case.

**Comment by mindplay-dk** [comment]
> You want #45218.

This seems like a general problem with typing - not specific to DOM?

> It’s a bit like saying “every DVD player is also a CD player” which is demonstrably not the case. _Sometimes_ structural typing breaks down…

I guess this 🙃

I think I've run into this problem before, actually.

In that DOM thread, they're talking about adding tag properties to the types to make them structurally different - and it sounds like that would work for that case, but sometimes that won't work.

If a `Person` and `User` both have identical fields, that does not make them conceptually or practically interchangeable, since they're likely stored in two different databases. 

Similarly, if both `Person` and `User` have an ID property, which is `number`, that does not mean you can take a Person ID and expect to get something from `findUserByID`.

What we need most likely is some way to tell the compiler, "type identity matters for this particular type - do not use structural subtyping to automatically convert it, please" - some kind of flags for class/type/interface declarations, e.g. `type UserID = distinct number` or `distinct class User`, etc. which would prevent those types from automatically converting to other types without an explicit (compatible) type cast?

**Comment by MartinJohns** [comment]
> What we need most likely is some way to tell the compiler, "type identity matters for this particular type - do not use structural subtyping to automatically convert it, please"

Aka nominal types: #202

**Comment by fatcerberus** [comment]
For what it's worth, for your own types, you can get `distinct class` simply by adding a private member to the class.

```ts
class A { private foo!: number }
class B { private foo!: number }
let x: A = new B();  // error
let y: B = new A();  // also error
```

**Comment by lu4** [comment]
Consider https://github.com/microsoft/TypeScript/issues/45218#issuecomment-961861038

**Comment by mindplay-dk** [comment]
Closing this, as there are already other open requests for it.

(With all the workarounds for this, you would think they would see the need and add the feature.)
