### ISSUE TITLE
Error Using Constrained Type Parameter in Generic Mapped Type

### ISSUE THREAD

**Issue by agrattaqrypt** [microsoft/TypeScript#46646]
# Bug Report

### 🔎 Search Terms

is:issue is:open mapped type generic constraints label:Bug

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBiBLANjYUA8AKssAHxwC8cA3gFBwNwDaAClBCrInBgHZwBrYIggAzOMRQBdANQB+AFwSSrdpyRSA3LQC+tWkhRwAyigDGGURjOTUVanAD6GACZKAzjCh8A5gBo4XgBDAFtgDy9fOD1aUEhYODMsIPd3OABZRABxYF48awBhZNSiOFBcXhc002ALKxsScjpGBGBPAAoASiUANwhXGnoWxjMIXk84d3NLa0wcPCU53AIauutbcntnNzgAIlddnU04AHoTuAA5CDgAUSh2KCHhxLGJn1z8syWF9Gxlok2NG2Sn2LkOxzOt3u0CUtjgAHIHMC9gdjjp4Tw0rwIPAUu4MD5ggAjLCoGDXQyoeHfAiEUjwp7RXRAA)

### 💻 Code

```ts
export type Filter<Type> = {
    [Property in keyof Type]+?: Type[Property];
}

type SpecificType = { _id: string, name: string }

export class MyGenericClass<T extends SpecificType> {
    test(): void {
        const specificFilter: Filter<SpecificType> = {_id: "id"}; // No Error
        const genericFilter: Filter<T> = {_id: "id"}; // Error: Type '{ _id: "id"; }' is not assignable to type 'Filter<T>'
    }
}
```

### 🙁 Actual behavior

A ts error occurs. We know all fields on `Filter<T>` are optional, but we are unable to assign any value with this type without getting a ts error. The error doesn't provide details on _why_ we can't assign the value; just that it is not assignable.

### 🙂 Expected behavior

No ts error. We have enough information to know that `{ _id: "id" }` is a valid `Filter<T>` since `T extends SpecificType`, any subclass of `SpecificType` will have the `_id` field, and all fields in `Filter<T>` are optional.

**Comment by MartinJohns** [comment]
> We have enough information to know that `{ _id: "id" }` is a valid `Filter<T>`

But we don't. The type of `_id` could be a more constrained one. For example:

    type SpecificId = { _id: "abc", name: string }

Assigning `"id"` to the property `_id` would be invalid.

**Comment by agrattaqrypt** [comment]
I see, so the issue is that TypeScript lets you constrain even primitive types when extending a type.

Strangely, even if I specify a hard-coded string in the type, it doesn't help.
```
export type Filter<Type> = {
    [Property in keyof Type]+?: Type[Property];
}

type SpecificType = { _id: string }
interface MoreSpecificType extends SpecificType { _id: "string" }

export class MyGenericClass<T extends MoreSpecificType> {
    test(): void {
        const genericFilter: Filter<T> = {_id: "string"}; // Error: Type '{ _id: "string"; }' is not assignable to type 'Filter<T>'.
    }
}
```

This much narrower example isn't very useful in the real world though. Closing this issue.

**Comment by fatcerberus** [comment]
That happens because you *could* make the string literal even narrower, e.g. `"string" & { brand: unknown }`
