### ISSUE TITLE
Need to `extends` `static` getter and setters.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#4664]
Maybe something like this?

```ts
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) Object.defineProperty(d, p, Object.getOwnPropertyDescriptor(b, p));
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
```

Or is there a better polyfill around the corner?

**Comment by mhegazy** [comment]
looks right to me.

Also related to #2009

**Comment by vilic** [comment]
Consider this:

```ts
class A {
    static y;
    static get x() {
        return this.y;
    }
}

class B extends A { }

B.y = 123;
console.log(B.x);
```

The code emitted by TypeScript will log `undefined`, while Babel will handle it correctly.

**Comment by vilic** [comment]
I guess you might expect us to define customized helper, but this could be a common usage I think.

**Comment by vilic** [comment]
@mhegazy Hi, this is still an issue. __extends should copy the **property descriptor** instead of the value directly. Currently the helper is doing:

```ts
d[p] = b[p];
```

But it should better do:

```ts
Object.defineProperty(d, p, Object.getOwnPropertyDescriptor(b, p));
```

**Comment by DanielRosenwasser** [comment]
I think this has always been an issue, which is why users are free to use their own `__extends`. See @RyanCavanaugh's comment on https://github.com/Microsoft/TypeScript/issues/1520#issuecomment-67369005

**Comment by DanielRosenwasser** [comment]
Marking this as a duplicate of #1520.

**Comment by vilic** [comment]
@DanielRosenwasser Thanks for the information!
