### ISSUE TITLE
Control flow analysis for dependent function parameters "destructured" from a tuple type

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#46658]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

dependent arguments, parameters

[This issue](https://github.com/microsoft/TypeScript/issues/35873) is very related to mine here, but I don't believe it's the same. That issue propose some bigger changes to TS - while I'd only like to "reuse" the, just landed, logic for the situation described below.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It's today possible to mimic dependent function parameters with tuples, spreads & co. Using such function parameters is clunky though because one can't destructure the arguments tuple without losing nice control flow analysis.

Since control flow analysis for destructured properties from unions has just landed on the main branch ( https://github.com/microsoft/TypeScript/pull/46266 ), I think it would be great to extend the logic to cover this situation.

I've looked briefly at how this works for the newly introduced control flow analysis and I think the problem is that the information about the identifier coming from the arguments list is not propagated to `getCandidateDiscriminantPropertyAccess`. So it has no chance of handling this "correctly". If we could pass this info there and then check the signature type, if it's spread+tuple based then we could apply the same logic as for binding patterns.

## 📃 Motivating Example

I've added a test case for this here: https://github.com/Andarist/TypeScript/commit/3e87dec24c8cb4c990d048d7d4c1342e6c49f779

```ts
type Args = ['A', number] | ['B', string]

declare function fn10(cb: (...args: Args) => void): void

fn10((kind, data) => {
    if (kind === 'A') {
        data.toFixed();
    }
    if (kind === 'B') {
        data.toUpperCase();
    }
})
```

Currently, with this technique, one could do this to keep the control flow analysis working:
```ts
type Args = ['A', number] | ['B', string]

declare function fn10(cb: (...args: Args) => void): void

fn10((...args) => {
    if (args[0] === 'A') {
        args[1].toFixed();
    }
    if (args[0] === 'B') {
        args[1].toUpperCase();
    }
})
```

but this ain't super friendly to the user.

## 💻 Use Cases

In XState (a state machine library) we have actions (can be thought of as functions/callbacks) that can be declared like this:
```js
assign((context, event) => {
  // this particular action can return a partial update to the context value
  return {}
})
```

Since XState is a state machine library some combinations of context & event types are **impossible**. With this feature in place, we could explore computing valid combinations and **maybe** (since the task ain't trivial) we could narrow down types of the `context` parameter based on different `event.type`s. So for instance, there is a chance that this would become possible:
```js
type Context = { userId: string | null }

assign((context, event) => {
  if (event.type === 'CHANGE_PASSWORD') {
    // `context` could be narrowed down to `{ userId: string }` if we could figure out how to create compute proper parameter tuples
  }
  return {}
})
```

cc @ahejlsberg

**Comment by MartinJohns** [comment]
I think this is related: #35873

**Comment by Andarist** [comment]
Yep, this looks related (but imho it's not the same) and i've already mentioned that in the original post.

**Comment by devanshj** [comment]
I guess someone should label this? (Reminding in case if got overlooked while triaging issues)

**Comment by andrewbranch** [comment]
It hasn’t been overlooked, I’m just drowning in issues 😞

**Comment by devanshj** [comment]
Oh apologies! Take your time, and thanks for the work you do :)

**Comment by andrewbranch** [comment]
It sounds like this could be used to solve Node-style callbacks, where we usually just type the `err` param as optional and the payload param as always defined for convenience, even though that’s wrong:

```ts
fs.readFile("foo.txt", (err, data) => {
  if (err) {
    // `data` should be undefined here
    throw err;
  }
  // `data` should be a Buffer here
});
```
