### ISSUE TITLE
ScrollBehavior definition is missing 'instant' for scrollTo

### ISSUE THREAD

**Issue by patik** [microsoft/TypeScript#46654]
# Bug Report

### 🔎 Search Terms

instant
scrollbehavior
scrollTo
type definition

### 🕗 Version & Regression Information

v4.4.4, but it's also mentioned in https://github.com/microsoft/TypeScript/issues/28755 (v3.2.1)

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/O4SwdgJg9sB0DOBjATlANmgKlAFAbwFgAoAAhIBcoAHALhIAYAaYstAUwDNy6mWSAjNgAsAhgDcQUZHQDk4eORFhyM4gF8AlEA)

### 💻 Code

```ts
window.scrollTo({
  top: 0,
  left: 0,
  behavior: 'instant' // This should be allowed
})
```

### 🙁 Actual behavior

The value of `'instant'` cannot be assigned to `behavior` when using `element.scrollTo()` according to https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo as well as testing it in a browser

### 🙂 Expected behavior

The value of `'instant'` is allowed when using `element.scrollTo()` according to https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo as well as testing it in a browser. Note that a similar issue, https://github.com/microsoft/TypeScript/issues/28755, was about `scrollIntoView()`, which indeed does _not_ allow `'instant'`.

**Comment by PaperStrike** [comment]
I guess it's https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/fe01c9a6d6afde86bd15f2588dc9360416a2beb4#r31507840, `instant` isn't valid anywhere ever since.

**Comment by patik** [comment]
I stand corrected! For anyone else who comes across this, in my testing I found that browsers do indeed treat `instant` the same as `auto`, so it's safe to simply drop the property unless you need `smooth`.

**Comment by ObjectAssign** [comment]
@patik auto to me works as scrolling does, I guess that is because I have enabled smooth scroll in my browser...

However, I would really like the instant to be available

**Comment by jiri-thiemel-te** [comment]
> I stand corrected! For anyone else who comes across this, in my testing I found that browsers do indeed treat `instant` the same as `auto`, so it's safe to simply drop the property unless you need `smooth`.

That most definitely is not true. It depends on the CSS. The 'instant' value needs to be allowed.

**Comment by helloint** [comment]
> I stand corrected! For anyone else who comes across this, in my testing I found that browsers do indeed treat `instant` the same as `auto`, so it's safe to simply drop the property unless you need `smooth`.

not ideally solution but this works for me. I introduced the latest TS5.6 still not seeing 'instant', how can it be?
```
type ScrollBehavior = "auto" | "smooth";
```
