### ISSUE TITLE
Cannot get type of Class level varible

### ISSUE THREAD

**Issue by ShadabFaiz** [microsoft/TypeScript#46653]
# Bug Report
- Tested on   v4.3.5

I'm working on some angular project. Inside a class, i'm trying to do the following:
``` ts
someList = ['A', 'B', 'C'] as const;
someFunction() {
 // Case 1: This will give error 'Cannot find name "this"'
  const x: typeof this.someList [number] = 'A'; 

//Case 2:  But this  works
	const oldX= this.campaginCategories;
        const x: typeof oldX[number] = 'A';
}

```

### 🙁 Actual behavior
Case 1 does not work  even though it is same as case 2

### 🙂 Expected behavior
Case 1 should work as case 2

**Comment by MartinJohns** [comment]
The syntax you try to use is not supported. You need to use this syntax to refer to class members: `this["someList"]`

**Comment by IllusionMH** [comment]
You need to properly fill in template and provide repro case on playground.
Because `oldX` in provided example is `any` as there is no `campaginCategories` - can be assigned anywhere.
