### ISSUE TITLE
[TS 4.5-dev] Regression: Promise.all -- "Expected 1 type arguments, but got 2"

### ISSUE THREAD

**Issue by eamodio** [microsoft/TypeScript#46651]
# Bug Report

It seems some `Promise.all` inferencing has changed in 4.5.*, as I have some patterns in GitLens where I am building an array in the call to `Promise.all` where some of the promises might be `undefined`. And in TS 4.5.* I now get a `Expected 1 type arguments, but got 2` error.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions `4.4.4` and `4.5-beta` and still present in `4.6.0-dev.20211102`.
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/JYOwLgpgTgZghgYwgAgOLDAISnECAWyA3smAJ4AOEAXMgOQBGOe+dyAvgLABQPoksRCnRgAKnADmxZKUo16YSWy69ucAM5k8yGAFc8YYAHsQyCRCzMCEdQAoAlLQAKUIwFtg6iAB4R2XAQA2gC6AHzEPACQUBa6UKb6ACYQMKAQiQCEANw8KjwaWgg6+giGJmYW4hJ2jsgu7p4+IlUh4URRMWBxCSDJqSDp2bk8I2qa2noGxqbmlgH4NgDyUFV2oAgANrrJAPy0dHAbG2wAPvRM8zanCpLqdPYR3JEIJupgyIEXLDYANKS3wWQAF5kHAAO5wDB1VweLwAOkOG18GH8LBCyDOSRSaUSf2aknRmN62IGiVCtkCUUi6y2yWBIJAuiOGLONO2KCBnPoiNOrLwtI5XMYVgWdypkR2FTm3xq4toWP66R+VLZdK5jOZJz5m3Z9JBByOvOQqsF+sU1To4sls1WDjlyAVOOVT2C9hyqkiX2s6ndkXNPtyQA)

### 💻 Code

```ts
interface GitBranch { type: 'branch' }

interface GitTag {  type: 'tag' }

async function getBranches(): Promise<GitBranch[]> {
	return undefined!;
}

async function getTags(): Promise<GitTag[]> {
	return undefined!;
}

async function getBranchesOrTags(include?: 'all' | 'branches' | 'tags') {
	const [branches, tags] = await Promise.all<GitBranch[] | undefined, GitTag[] | undefined>([
		include == null || include === 'all' || include === 'branches'
			? getBranches()
			: undefined,
		include == null || include === 'all' || include === 'tags'
			? getTags()
			: undefined,
	]);

	branches;
	tags;
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
async function getBranches() {
    return undefined;
}
async function getTags() {
    return undefined;
}
async function getBranchesOrTags(include) {
    const [branches, tags] = await Promise.all([
        include == null || include === 'all' || include === 'branches'
            ? getBranches()
            : undefined,
        include == null || include === 'all' || include === 'tags'
            ? getTags()
            : undefined,
    ]);
    branches;
    tags;
}
```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>
      
### 🙁 Actual behavior

Got `Expected 1 type arguments, but got 2` on the `Promise.all` call.

### 🙂 Expected behavior

No errors like in TS 4.4.4 and prior

**Comment by eamodio** [comment]
I did just notice that if I remove the `<GitBranch[] | undefined, GitTag[] | undefined>` from the `Promise.all` call, it gets inferred correctly.

**Comment by IllusionMH** [comment]
Another way is to specify types that you have in arguments.
`Promise.all<[Promise<GitBranch[]> | undefined, Promise<GitTag[]> | undefined]>` then first overload will be used.

[Playground](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/JYOwLgpgTgZghgYwgAgOLDAISnECAWyA3smAJ4AOEAXMgOQBGOe+dyAvgLABQPoksRCnRgAKnADmxZKUo16YSWy69ucAM5k8yGAFc8YYAHsQyCRCzMCEdQAoAlLQAKUIwFtg6iAB4R2XAQA2gC6AHzEPACQUBa6UKb6ACYQMKAQiQCEANw8KjwaWgg6+giGJmYW4hJ2jsgu7p4+IlUh4URRMWBxCSDJqSDp2bk8I2qa2noGxqbmlgH4NgDyUFV2oAgANrrJAPy0dHAbG2wAPvRM8zanCpLqdPYR3JEIJupgyIEXLDYANKS3wWQAF5kHAAO5wDB1VweLwAOkOG28gXqsKaGH8LFayDOSRSaUSf1RjV8GBaYRxyDx-XSYVsgSikXWW2SwJBIF0RxxZ2Z2xQQIF9ERpx5eBZ-MFjCsCzujMiOwqc2+NTltGpBJ+o0ZvNZgo5XJOos2fLZIIORxFyB1ErNimqdDlCtmqwcqqpvXxA0JUWC9hyqkiX2s6n9kTtIdyQA)

**Comment by andrewbranch** [comment]
Maybe we should call this out more explicitly in the stable blog post. There’s a section about the broader Promise/Awaited changes but the type parameter change isn’t specifically mentioned.
