### ISSUE TITLE
No outlining span returned for multiline comment

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#46666]
# Bug Report

### 🔎 Search Terms

- getOutliningSpans
- fold / folding

### 🕗 Version & Regression Information
4.5.0-dev.20211029

### 💻 Repro

For the code:

```js
/*
x
*/

console.log(1) 
```

Try folding the multiline comment

### 🐛  Repro

No outlining span returned

One is returned if you remove `console.log(1)`

**Comment by zohaibmalik994** [comment]
Also @mjbvz  , I have a feature request to have an option to fold/unfold a selection of desired code. It can also fix a lot of such problems in future.

**Comment by andrewbranch** [comment]
Works if you put a space before `x`
