### ISSUE TITLE
Not inferring type correctly in union

### ISSUE THREAD

**Issue by rluvaton** [microsoft/TypeScript#46663]
# Bug Report

### 🔎 Search Terms

Type narrowing, infer type 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about

Tested versions:
- Nightly
- `4.5.0-beta`
- `4.4.4`
- `4.3.5`
- `4.2.3`
- `4.1.5`
- `4.0.5`

### ⏯ Playground Link

[Not working](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwgY2AaQiAysATgSwDsBzfAM3wgBMAeDEKCAD2AkKoGcoOQBbOAPYAbKAB9ueIsTFRCAV34RcAPigBeKPUYs2nbn0EiA-LIgA3JVABcUAAYASAN70AvrYDcQA)

[Workaround](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwgY2AaQiAysATgSwDsBzfAM3wgBMAeDEKCAD2AkKoGcoOQBbOAPYAbKAB9ueIsTFRCAV34RcAPigBeKPUYs2nCQRIz5i3FAD8UAAYASAN70AvpagAuWRABuSgNxA)

### 💻 Code

Not working:
```ts
type ObjectKeyStringified<Key extends symbol | string | number> = Key extends symbol ? never : `${Key}`;
```

Workaround:
```ts
type ObjectKeyStringified<Key extends symbol | string | number> = Key extends string | number ? `${Key}` : never;
```

### 🙁 Actual behavior

The error (kinda weird one 😬:
```
Type 'Key' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
  Type 'string | number | symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
    Type 'symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
      Type 'Key' is not assignable to type 'number'.
        Type 'string | number | symbol' is not assignable to type 'number'.
          Type 'string' is not assignable to type 'number'.
```

### 🙂 Expected behavior

Not having the error 😀

**Comment by andrewbranch** [comment]
While it's easy to see how this would work for union types where the `extends` type is a subset of the constituents of the type parameter’s constraint, for it to work in general we would need negated types, i.e., the ability to say that a type is `T & not U`. Without that, we can’t create a substitution type on the negative side of conditional types.

**Comment by rluvaton** [comment]
So what is the difference with [this](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAJ3ACgG4EMA2ICmAXIgM5TIxgDmiAPomCALYBG+ydpAnq3DgJSIA3gFgAUIkmIYwNFC4AHfHGCJsefIgC8OxAHISPFnz2DREqZfGWAvonw4Sm85csQEZUnCb4oAC0oqYkZWdk4yCmptNVwCAG5rKRtxZLFxIA) code?

```ts
function run(value: string | number | symbol) {
    if(typeof value === 'symbol') {
        
    } else {
        const something: number | string = value;
    }
}


```

**Comment by andrewbranch** [comment]
The difference is that control flow narrowing is a heuristics-based convenience feature, where we know we can never do a perfect job (#9998), so it gives us more room to do the best we can and make improvements to those efforts over time. When control flow narrowing works in one case and doesn’t work in another, it might be confusing or frustrating, but it’s the only way we can do it at all. For type definitions, I think it’s more valuable to keep things consistent.
