### ISSUE TITLE
Google feedback on TS 4.5-beta

### ISSUE THREAD

**Issue by rahul-kamat** [microsoft/TypeScript#46665]
This GitHub issue contains feedback on the TS 4.5-beta release from the team
that is responsible for keeping Google's internal software working with the
latest version of TypeScript.

## Executive summary

*   We do not expect to have significant difficulty in upgrading Google to TS
    4.5.
*   Some changes to our TypeScript code are required to make it compile with TS
    4.5.
    *   About a third of the new errors reported by TS 4.5-beta are clearly
        related to the announced changes.
    *   The remaining new TS errors are few. Some seem to be legitimate source
        code errors but others will need further inspection.
    *   Detail sections below explain the changes to our code we expect to make
        to unblock the upgrade.

## Impact summary

| Change description                     | Announced | Libraries affected |
| -------------------------------------- | --------: | -----------------: |
| lib/d.ts Changes                       | yes       | 0.006%             |
| Added isTypeOnly attribute to ImportSpecifier and ExportSpecifier in typescript.d.ts | no        | 0.003%             |
| Promise.all Changes                    | yes       | 0.003%             |
| Template String Types Changes          | yes       | 0.003%             |
| Awaited Type Changes                   | yes       | 0.001%             |

The **Announced** column indicates whether we were able to connect the observed
change with a section in the
[TS4.5-beta announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/).

The following sections give more detailed explanations of the changes listed
above.

### lib/d.ts Changes

We support the typing improvements. Generally it's clear what's changing.

Our fix will be casting away the errors in existing code.

We observed the following breakdown within this category:

*   `HTMLElement` related breakages : 65%
*   Others : 35%

### Promise.all Changes

Providing more than 1 parameter to `Promise.all` breaks.

Examples:

*   `Promise.all<boolean>` builds successfully.
*   `Promise.all<boolean, boolean>` fails - TS2558: Expected 1 type arguments,
    but got 2.
*   `Promise.all<void, boolean, void>` fails - TS2558: Expected 1 type
    arguments, but got 3.
*   `Promise.all<string|null, string|null>` fails - TS2558: Expected 1 type
    arguments, but got 2.

Exactly how we resolve this error will be determined later.

### Template String Types Changes

Template string literals are sometimes recognized as a type when explicitly
being cast to a different type.

Example:

*   ``return `r${variable1}` as Type1;`` fails - TS2352: Conversion of type
    'r${variable1}' to type 'Type1' may be a mistake because neither type
    sufficiently overlaps with the other.

We will likely resolve this error by inserting a cast to `any` for the error
along with a `TODO` comment containing the error message and a request to the
team owning the code to investigate and make a more correct fix when they can.

### Awaited Type Changes

Type inference with `Awaited` fails in some cases.

Some of the breakages we have seen look like:

*   TS2352: Conversion of type 'Awaited\<T>' to type 'NonNullable\<T>' may be a
    mistake because neither type sufficiently overlaps with the other.
*   TS2322: Type 'Awaited\<Row\<T, K\>\>[K]' is not assignable to type 'T[K]'.

We will likely resolve this error by inserting a cast to `any` for the error
along with a `TODO` comment containing the error message and a request to the
team owning the code to investigate and make a more correct fix when they can.

### Added isTypeOnly attribute to ImportSpecifier and ExportSpecifier in typescript.d.ts

`ImportSpecifier` and `ExportSpecifier` in [typescript.d.ts](https://github.com/microsoft/TypeScript/blob/release-4.5/lib/typescript.d.ts)
have an added `isTypeOnly` attribute that is not optional. Any code that
includes calls `createImportSpecifier`, `updateImportSpecifier`,
`createExportSpecifier`, `updateExportSpecifier` breaks because of this added
`isTypeOnly` parameter. This breaks Angular and our [tsickle tool](https://github.com/angular/tsickle).

Compare(ImportSpecifier):

*   TS4.4 - [ImportSpecifier interface](https://github.com/microsoft/TypeScript/blob/01de6ff2ecdc6175727f7f999b887519d40ca115/lib/typescript.d.ts#L1677)
*   TS4.5 - [ImportSpecifier interface](https://github.com/microsoft/TypeScript/blob/5764cdc8ec19da02858376ae5c1407a923c2d124/lib/typescript.d.ts#L1696)

Compare(ExportSpecifier):

*   TS4.4 - [ExportSpecifier interface](https://github.com/microsoft/TypeScript/blob/01de6ff2ecdc6175727f7f999b887519d40ca115/lib/typescript.d.ts#L1683)
*   TS4.5 - [ExportSpecifier interface](https://github.com/microsoft/TypeScript/blob/5764cdc8ec19da02858376ae5c1407a923c2d124/lib/typescript.d.ts#L1703)

Our fix would be adding the `isTypeOnly` parameter to all
`ts.factory.(create/update)(Import/Export)Specifier` calls.

**Comment by DanielRosenwasser** [comment]
> Providing more than 1 parameter to Promise.all breaks.

So the hope here is that you can omit all the type arguments to `Promise.all` from now on. I'd be hope that doing so would cause no new issues.

**Comment by andrewbranch** [comment]
The direct equivalent though is to wrap the multiple type arguments in a tuple. `Promise.all<T, U>(...)` → `Promise.all<[T, U]>(...)`.

**Comment by IllusionMH** [comment]
@andrewbranch looks like it might be not always that straightforward #46651

**Comment by rahul-kamat** [comment]
> > Providing more than 1 parameter to Promise.all breaks.
> 
> So the hope here is that you can omit all the type arguments to `Promise.all` from now on. I'd be hope that doing so would cause no new issues.

It seems like type inference with `Promise.all` when all the type arguments are omitted still causes failures. 
However, as mentioned by @andrewbranch, wrapping the type arguments in a tuple resolves our breakages. 

Thanks for clarifying how `Promise.all` works!

**Comment by rahul-kamat** [comment]
I've tested TS 4.5-rc and the results were identical to TS 4.5-beta with the addition of the following:

 *   About 67% of new errors reported by TS 4.5-rc are clearly related to `lib.dom.d.ts` changes.
 
 ## Impact summary

Change description   | Announced | Libraries affected
-------------------- | --------: | -----------------:
lib.dom.d.ts Changes | no        | 0.001%

The **Announced** column indicates whether we were able to connect the observed
change with a section in the [TS4.5-rc announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-rc/) or in [TypeScript 4.5 libdom changes](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1143).

### lib.dom.d.ts Changes

[src/lib/dom.generated.d.ts](https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts) has been updated in [Update TypeScript DOM Libs](https://github.com/microsoft/TypeScript/pull/46222/)
between the release of TS 4.5-beta and TS 4.5-rc. 
This code generates [lib/lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts).

The following two changes that update the `Event` type to
`MediaRecorderErrorEvent` have caused breakages with error 
`TS2717: Subsequent
property declarations must have the same type. Property 'error' must be of type
'MediaRecorderErrorEvent', but here has type 'Event'`.

Compare(MediaRecorderEventMap):

*   TS 4.5-beta - `"error": Event;` in [MediaRecorderEventMap interface](https://github.com/microsoft/TypeScript/blob/d6cd2c7c11a38baa32b45e5efb3177cc040212c8/src/lib/dom.generated.d.ts#L9014)
*   TS 4.5-rc - `"error": MediaRecorderErrorEvent;` in [MediaRecorderEventMap interface](https://github.com/microsoft/TypeScript/blob/df53f4def2d50f68270f739c81fc99104e4526d8/src/lib/dom.generated.d.ts#L9094)

Compare(MediaRecorder):

*   TS 4.5-beta - `onerror: ((this: MediaRecorder, ev: Event) => any) | null;`
    in [MediaRecorder interface](https://github.com/microsoft/TypeScript/blob/d6cd2c7c11a38baa32b45e5efb3177cc040212c8/src/lib/dom.generated.d.ts#L9025)
*   TS 4.5-rc - `onerror: ((this: MediaRecorder, ev: MediaRecorderErrorEvent) =>
    any) | null;` 
in [MediaRecorder interface](https://github.com/microsoft/TypeScript/blob/df53f4def2d50f68270f739c81fc99104e4526d8/src/lib/dom.generated.d.ts#L9105)

Exactly how we resolve this error will be determined later. We will likely
resolve this error by either:

1.  Changing `lib/lib.dom.d.ts` internally to temporarily change the
    `MediaRecorderErrorEvent` types to `Event`.
2.  Inserting a cast to `any` for the error along with a `TODO` comment
    containing the error message and a request to the team owning the code to
    change `any` to `MediaRecorderErrorEvent` when they can.

**Comment by tronguye** [comment]
Hey all, commenting on this thread as it's the only existing one that makes mention of `MediaRecorderErrorEvent`.

On our team, we upgraded from TS 3.8 to 4.4 and noticed that the `MediaRecorder.onerror` declaration had changed to type the error as a `MediaRecorderErrorEvent` although that is what the spec calls for. Can anyone chime in on why this change happened? Is it related to rahul's beta testing results?

**Comment by tronguye** [comment]
Looking again, I see that many Chromium attaches an `error` to the generic event instead of using `MediaRecorderErrorEvent`
