### ISSUE TITLE
'unknown' is not assignable to type for static API with generic methods

### ISSUE THREAD

**Issue by marikaner** [microsoft/TypeScript#46662]
# Bug Report

I am trying to have an interface (`Constructable`) for the static API of a class (`SomeClass`), which I want to be able to pass to some function (`fn`).
I have some static methods in the static API, that should allow to pass parameters with generic types.
I can't get the generic types to be assignable to one another.

### 🔎 Search Terms

'unknown' is not assignable to type

Possibly related to https://github.com/microsoft/TypeScript/issues/45255

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about - couldn't find anything relevant

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=5&ts=4.4.4#code/JYOwLgpgTgZghgYwgAgMIHsQGcxQK4JhwBGANhADwAqAfMgN4CwAUMm8iBAO7IAUAdILhQA5lgBcyOCACeAbQC6ASklUA3C3bIAtjIDKRMMAQBZCGAAW6ACYUACsggAPSCGtYpsmrwAOwuNqSdirIAG7owNZqyAD0MchcFjLIwB6Wqci4EHCQ1lIeDs6u7sh4IADWIOhcIMgA-CwAviwsCKRwWB566NoQqO2dDJrsODnGOvqGxmaWNvaOLhBuHjhQoCLeflABQSHhkQzIzczHLDBlhMCYyDAgvIToUJIY2LgERGSU3b39HVg0ewieXop2Yt143z6AywSjUQA)

### 💻 Code

```ts
interface Constructable<T> {
    new (...args: any[]): T;
    myStaticMethod<P extends any>(param: P): void; // why is this treated as P extends unknown ?
}

class SomeClass {
    static myStaticMethod<P extends string>(param: P): void { }
}

function fn(ctor: Constructable<SomeClass>): void {}

fn(SomeClass);
```

### 🙁 Actual behavior

I cannot call `fn` with `SomeClass` because the generic type "'unknown' is not assignable to type string". This also does not work if I change the `Constructable` interface to have this method: `myStaticMethod<P>(param: P): void;`  (generic parameter does not extend any). Then the error is simply "'P' is not assignable to type string".

### 🙂 Expected behavior

I expected that `SomeClass` is assignable to the type `Constructable<SomeClass>`.

**Comment by MartinJohns** [comment]
> // why is this treated as P extends unknown ?

See the release notes for TypeScript 3.9: [Type Parameters That Extend `any` No Longer Act as `any`](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#type-parameters-that-extend-any-no-longer-act-as-any)
