### ISSUE TITLE
Generic type intersection not narrowing down

### ISSUE THREAD

**Issue by Julien-Marcou** [microsoft/TypeScript#46691]
# Bug Report

### 🔎 Search Terms

Generic type, Intersection, Narrowing down, Property does not exist on type, Extends, Discriminated unions, Type kind

### 🕗 Version & Regression Information

This is the behavior in every version I tried (from v3.3.3 to v4.4.4, and v4.5.0-beta), and I reviewed the FAQ for entries about type narrowing without finding additional information about it

### ⏯ Playground Link

[Type not narrowing down](https://www.typescriptlang.org/play?#code/C4TwDgpgBACg9gSwHbADwBEEFsJIM4JxJQQAewuAJnlAExQA+UAzFALx2MsB87UA3gFgAUFCiVsuAkQBcUTDnyEkAbhFjScpAFcsAIwgAnNaKggtug8ZEBfKADIoACgVTlJclRqsA-APVQAF4W+kYmdnL8NgCUJiIAxkR4wFBgiCi06HLwyGi0vBxCphKK0khytAA0AZpQAAzVpub1jTZxwon4KWm5zFmw6WjMBf7FkkqyLI0acg0BzXOmwS227Z3JqYN4cgCChoYAhiCoOSgjANo9GeiVm73oALom692DfFfAeOd1TyIiCAAzZwfAB0JTcRHYbA4tGiozEAHoEQNclAEDQkHAUkgDvs4AB3CCUcQE4jAOAolCofIBdZwAA2EBB9LgAHMnKDSLdQSBuYMQYFYlAkVAAKKkSDxCjEoyGOCGWz-IEc-ngibEaEcZhwoqI5GnFLoqCY7G4uWE4mUUlQcmUobcWlJBlMlnszl83Ig3l3FACoUigCqSDIkulJDxCuENhEQA)

[Type narrowing down](https://www.typescriptlang.org/play?#code/C4TwDgpgBACg9gSwHbADwBEEFsJIM4JxJQQAewuAJnlAExQA+UAzFALx2MsB87UmOfIWJkKSapyasA-FADeAWABQUKJWy4CRAFz8NQogG5lq0rqQBXLACMIAJ2MqoIc1dsPlAXygAyKAAoBTWEScioaGXkTKAAvVxt7R29dOU8ASihzCAA3ROVlAGMiPGAoMEQUWnRdeGQ0Wl4ORSd1QS0kXVoAGmizKAAGHqcXAaHPR0Li0vK65mrYCrRmRqiW-XbdZiHTXUHokb2nONGvCaUi-GnFvF0AQTs7AEMQVFqUFYBtGcr0LrLFuYAXUcFxK-zqfG+wDwH36wPySgQADMAlCAHStYJEdhsDi0DLNVQAeiJCwhCBoSEeDzgAHcIJQ1HTiMA4GSUKgGtFQXAADYQNG8uAAc386NIf3RIElizRMTShigJKgAFFSJAChRGfY7HA7F5lMjUbLMQZiLiOMwCdFlW9ShSoFSafTGZRmVBWeyltxucU+QKhaLxTK6mjpeCUHKFUrSQB5ADWBqUQA)

### 💻 Code

Base on the documentation about [Discriminated unions](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) to determine the kind of a Shape

I'm trying to intersect 2 types depending on a given generic type so I don't have to repeat some common properties, but TypeScript is not narrowing down the intersection unless I test that the generic type extends itself before intersecting (which seems unnecessary to me)

```typescript
type Point<Dimension extends 2 | 3 = 2 | 3> = {
  dimension: Dimension;
  x: number;
  y: number;
} & (Dimension extends 3 ? {
  z: number;
} : {});

const point2D: Point<2> = {
  dimension: 2,
  x: 0,
  y: 0,
};

const point3D: Point<3> = {
  dimension: 3,
  x: 0,
  y: 0,
  z: 0,
};

const points: Array<Point> = [point2D, point3D];
const point = points[0]; // Point<2 | 3>

if (point.dimension === 2) {
  // Point is not narrowed down to Point<2>
  console.log(point.x, point.y, point.z); // Expected error on point.z
}
if (point.dimension === 3) {
  // Point is not narrowed down to Point<3>
  console.log(point.x, point.y, point.z); // Unexpected error on point.z
}
```

### 🙁 Actual behavior

The `points[0]` which is a generic `Point<2 | 3>` is not narrowing to `Point<2>` or `Point<3>` when testing for the `dimension` property

### 🙂 Expected behavior

The `points[0]` should narrow down to `Point<2>` in the first `if` and narrow down to `Point<3>` is the second `if`

### Addination information

The example I gave is for demonstration purpose, in real world my case is much more complicated that a 2D or 3D point, which explains why I'm using this approach

My problem here is that declaring the generic type with:

```typescript
type Point<Dimension extends 2 | 3 = 2 | 3> = Dimension extends 2 | 3 ? {
  dimension: Dimension;
  x: number;
  y: number;
} & (Dimension extends 3 ? {
  z: number;
} : {}) : never;
```

Makes the type narrowing work, but testing if the Dimension type extends 2 or 3 to describe the generic Point (otherwise `never`) seems like unnecessary to me as the Dimension can only be 2 or 3 anyway

To me, it seems like the same typing as:

```typescript
type Point<Dimension extends 2 | 3 = 2 | 3> = {
  dimension: Dimension;
  x: number;
  y: number;
} & (Dimension extends 3 ? {
  z: number;
} : {});
```

But it doesn't ?

**Comment by MartinJohns** [comment]
Look up distributive conditional types. The "working" version is distributive, the not working one is not. That makes a **huge** difference, because then you actually end up with `Point<2> | Point<3>` instead of `Point<2 | 3>`.

**Comment by Julien-Marcou** [comment]
I've been on the problem for so long I didn't even thought about that, so the correct solution is to surround my type with:

`Dimension extends 2 | 3 ? ... : never`

or is there a proper way to declare the type I want without it ?

**Comment by MartinJohns** [comment]
I think this is extremely and overly complicated for no benefit, and you'd be far better off to just declare two different types.

**Comment by Julien-Marcou** [comment]
Well, yes (for 2D/3D Point at least), but in my real case, I have several types (with a lot of properties) with this behavior and, I have more than 2 possible values for the generic type.

I.E: TypeA<1|2|3>, TypeB<1|2|3>, TypeC<1|2|3>, etc

Which would make me copy/pasta a lot of common properties

**Comment by Julien-Marcou** [comment]
I'm really dumb, sorry for the inconvenience xD

But, I just thought about this, I could use a greater type:

```typescript
TypeA<T extends 1|2|3> = { ... };
type MyTypeA = TypeA<1> | TypeA<2> | TypeA<3>;
```

So I don't have to repeat myself to declare the properties, and the typing ends up being what I want as long as I use the MyTypeA instead of TypeA.

**Comment by fatcerberus** [comment]
For future reference, you can disable the distributive behavior of conditional types by surrounding the type parameter with `[]`:

```ts
type Foo = T extends any ? Array<T> : never;
type Bar = [T] extends [any] ? Array<T> : never;

type Fooey = Foo<string | number>;  // string[] | number[]
type Bard = Bar<string | number>;   // (string | number)[]
```

**Comment by MartinJohns** [comment]
> For future reference, you can disable the distributive behavior of conditional types by surrounding the type parameter with []:

Just as written in the documentation: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types
