### ISSUE TITLE
Partial application of functions loses type assertion information

### ISSUE THREAD

**Issue by samuela** [microsoft/TypeScript#46702]
# Bug Report

### 🔎 Search Terms

type assertion, assert v is T, asserts condition, partial application, type inference, case splitting

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, including 4.4.4 and 4.5.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=8&jsx=0&ts=4.5.0-beta#code/PTAEGUFNNALAXeAHAzgLhAcwJb1gVwCMA6AYwHsBbYAWW1ICdyVyAzeYAFQE8lJxG2JB2woU+SCmAB2AKyyAbMQBQ8XjACiDJg06gAvKADeoAHaQA7qAAUlSSgCGmSGlAp4DbKcwBKV1p1QAF8AblV1UA1cWEgGA2NQeCdXACIAGUh2FJDQB1d3T29g0AAfBKTMVIAlbEwEbNBCV1N8SkJY4LDlEFAAWn7IgA8kABt6XFAAN1iUbHJTGwcxWPg5hbU+UC9WcgZKB1X5rZRQJCYkJwPIABM-ZVZ8U1JDhaWUFY1hsdJcawpTa64NauQjkcgjSAOUx+XLLBjwE7-QEvYzKUBbVg2ACESKB8x8qPR6LwTCs5isAV21hSYNQKR8YXRQWUzIeTxR8Ek8AA6rsANYoayDfzRWIEoxo2HveGfUbjeBC4gVAz6QwpGp1eD0xmgf4sCHEEbkTCKwgMlnKbpgfq9UAABQc8OwDhGuSQctIBzWUxm3usbxW3o2MG2u32KNEoCN7jubOe3oA+gH4dZYjoeHx-NpdpwADS6+bI4GNMEQqEw5MIgsAvELCXo7CY6w4wu18WS4mwUlmSygNM59TU2kobWS5nMvXwKUreJ-VsvEGlyHQgwAPlASbhCspDHzuJe5rjHK5ADEHNgRoLhZFRQx2+jK4rlaq1Rksub0XrwZBDcbFQ5zWZZRIGGXYpyMUJlCAA)

### 💻 Code

```ts
// See https://github.com/Microsoft/TypeScript/issues/7556.
type ErrorT = { new (message: string): Error };
type Either = { tag: "Left"; a: string } | { tag: "Right"; b: number };

// --- Explicit version (assertion type information is propagated):
function assertExplicit(condition: boolean): asserts condition {
  if (!condition) {
    throw new Error("oops");
  }
}
function testWorks(x: Either) {
  assertExplicit(x.tag === "Right");
  console.log(x.b);
}

// --- Partial application version (assertion type information is lost):
function _assert(errorType: ErrorT, condition: boolean): asserts condition {
  if (!condition) {
    throw new errorType("oops");
  }
}
const assert = (condition: boolean) => _assert(Error, condition);
function testFails(x: Either) {
  assert(x.tag === "Left");
  console.log(x.a); // fails with "Property 'a' does not exist on type 'Either'."
}

export {};
```

### 🙁 Actual behavior

Type assertion information is lost outside of immediate call-sites. For example, if `f(x): asserts <condition>` then TS will only respect the assertion of the condition in the direct scope of where `f` is called and nowhere else, eg if `g` call `f`, there is no propagation of the information that `asserts <condition>` should hold in `g`.

### 🙂 Expected behavior

Assertion types to be propagated everywhere they apply.

**Comment by MartinJohns** [comment]
Working as intended. `assert` is not an asserting function. See #32695.

**Comment by samuela** [comment]
But why is `assert` not an asserting function? Simple control-flow analysis should reveal that it ought to have the same asserting properties as `_assert` since there's no `try/catch` in `assert`.

**Comment by devanshj** [comment]
As pointed out in #32695 these are the conditions for participation in CFA:

> A function call is analyzed as an assertion call or never-returning call when
> - the call occurs as a top-level expression statement, and
> - the call specifies a single identifier or a dotted sequence of identifiers for the function name, and
> - each identifier in the function name references an entity with an explicit type, and
> - the function name resolves to a function type with an asserts return type or an explicit never return type annotation

`_assert` doesn't fulfil the third condition, it's not explicitly typed. There is a feature request to lift this condition: #45385
