### ISSUE TITLE
Condition type bug

### ISSUE THREAD

**Issue by MichaelHao25** [microsoft/TypeScript#46708]
# Bug Report
```ts
interface AAA {
    b?:string;
    a:boolean,
}
enum Type{
    A,
    B
}
interface BBB {
    a:boolean;
    b:string;
}
function  Test<C extends Type,T extends (C extends Type.A?AAA:BBB)>(a:C,params:T) {
    
}
Test(Type.B,{
    a:false,
    b:'false',
})
```
After using the condition type to constrain the second parameter, the second parameter seems to become any?

```ts
Test(Type.B,{
    a:false,
    b:'false',
c:'error'
})
```
Why does key c not report an error if it is not in aaa or bbb?

[demo https://codesandbox.io/s/distracted-lovelace-mdfmq](https://codesandbox.io/s/distracted-lovelace-mdfmq)

**Comment by MartinJohns** [comment]
Please don't forget to fill out the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md). It's not really clear what your actual and expected behaviour is.

Why do you think passing a type with the `c` property should result in an error? The parameter is generic, the type is inferred, and it doesn't collide with any type, so it's valid.

**Comment by fatcerberus** [comment]
`T` is *constrained* (i.e. upper-bounded) by `AAA`/`BBB`, so you don't get an excess property check on `params` because adding properties makes a valid subtype.  As @MartinJohns says, the function is generic.

**Comment by MichaelHao25** [comment]
Thank you so much reply

I will submit the next question according to the [ issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md)

The result I want is that parameter b depends on parameter a. For example, if parameter a is true, parameter b is mandatory, and if parameter a is false, parameter b is optional.

```ts

interface AAA {
    b?:string;
    a:boolean,
}
enum Type{
    A,
    B
}
interface BBB {
    a:boolean;
    b:string;
}
function  Test<C extends Type>(a:C,params:C extends Type.A?AAA:BBB) {
    
}
// Here b is a required parameter
Test(Type.B,{
    a:false,
})
// Here b is an optional parameter
Test(Type.A,{
    a:false,
})

```

Writing like the above can solve my essay question, but if there are many conditions, the following conditional expressions will grow linearly.
Secondly, can the function's input parameters use two parameters be changed to one parameter?



The specific requirement is that I am building a tree. There are many types of nodes in the tree. The function of this function is to create a specified type of node. For example, if node a is a leaf node, it has a title, and node b is The root node has not only a title but also a right node. I want to use typescript to restrict it. For example, the incoming leaf node has only the title attribute, and the incoming b node has only the title and right node attributes.

**Comment by MichaelHao25** [comment]
@fatcerberus  pls help me...thanks....

**Comment by whzx5byb** [comment]
I'm not really sure but it seems that you are worried about the conditional type `(C extends Type.A?AAA:BBB)` would become complex as the amount of interfaces `AAA`, `BBB` increase? 
If so, using [discriminated unions](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions) will help.

```ts
enum Type {
    A,
    B
}

interface AAA {
    type: Type.A;
    a   : boolean;
    b?  : string;
}

interface BBB {
    type: Type.B;
    a   : boolean;
    b   : string;
}

function Test<T extends AAA|BBB, U extends T['type']>(a: U, params: Omit<T extends {type: U} ? T : never, 'type'>) {

}

// OK
Test(Type.A, {
    a:false,
})

// Error, as expected
Test(Type.B, {
    a:false,
})

// Error, as expected
Test(Type.B, {
    a:false,
    b:'false',
    c:'error'
})
```

**Comment by MichaelHao25** [comment]
thanks
