### ISSUE TITLE
"Index signature missing" error when using Interface vs Inline Type Definition

### ISSUE THREAD

**Issue by brwarner** [microsoft/TypeScript#46715]
# Bug Report

### 🕗 Version & Regression Information

Typescript version 4.4.4 (also tested on the nightly v4.6.0-dev.20211105)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gEgMJIFsAjASxRGAGUMoMQAueAVxRIEcmE0BPYpCAFACA9MPgARcNDiJCpcsHiZaCKGnhQUzVqnhIAZhqW8i-eGVAAPDSkUYAFgjoEADtDrwXsKARB0Y8JQCGNwuCPjEZBTUKgDqSDAA1mgAPJQAfPAAvPAA3gLwhfBwUMCoENzwANp4clFUNHQAugD8jCyg+vUCAL7wAGSBANxCovAAKjCVGEgaaGgkAOZaULKRCkqNTrOrAErgCcApmDBkiwA02okoSADuKJkAdM9KTGBgIPMAhPA3ay4kCAIEAwGAJNACfKFZDoLDIdYURgReTRLbxJKpXJQRgoJjEEE9TI5XIaRgAJngPRG0NQmGKBxgwEY+2QjOOGFOKAuVxu9yJaxRwBGPVGYkkkFgCHhgs2KjmNm0JF0BngDgQZH8+igH3gACIAKKuEIAeSIACtwBhdfAABQkUAoDAkMBQCCq2Zq8woCBRVWhVSmABuIAAlDY7I5VSBXO4EF4YD4-CDAgINSCtTrDS4TebLXkCkUSmVvZUasj6jFmm1tJ1uiKQmF4OWFJWQAAxKCA1IZbLwLM5i1gLCDSgjERiSbTHbzJYrAX1WUeGZGFmHdmc7ksa53B7wZ6PeBawFfSEFmF06X1JF1FtbDtdlJYnF4ogE-kk7HwClUgtjfW7XZjV2eBdgASQAcQACXGeBIP-fUz1pLA4FZJkQIZI4TjOS4t15XcckvBRhSAA)

### 💻 Code

```ts
declare const $CombinedState: unique symbol

// Declare combined state as an union of a symbol index and the template parameter S
type CombinedStateWorks<S> = {
    readonly [$CombinedState]?: undefined
} & S;

// Try to assign a combined state to a Record<string, unknown> ... success! no compile errors
{
  const combined: CombinedStateWorks<{a: number}> = { a: 2 };
  const record: Record<string, unknown> = combined;
}

// Declare combined state as an union of the interface "EmptyObject" (identical to the inline type above) and the template parameter S
interface EmptyObject {
    readonly [$CombinedState]?: undefined
}
type CombinedStateFails<S> = EmptyObject & S;

// Try to assign a combined state to a Record<string, unknown> ... fail!
{
  const combined: CombinedStateFails<{a: number}> = { a: 2 };
  // ERROR RIGHT HERE
  const record: Record<string, unknown> = combined;
}
```

### 🙁 Actual behavior

Despite `CombinedStateFails` and `CombinedStateWorks` being the same type specification (except one uses an interface, one an inline type definition), one fails to case to a `Record<string, unknown>` and the other succeeds.

### 🙂 Expected behavior

Both cases should have the same compilation result (success).

This is a problem because recent releases of Redux have refactored their `CombinedState` type from the first example here to the second, breaking some of my code. I'm not sure what type besides `Record<string, unknown>` I can use as my parameter type now.

**Comment by MartinJohns** [comment]
`type` and `interface` are not interchangeably. This is working as intended. See https://github.com/microsoft/TypeScript/issues/42825#issuecomment-789242594.

**Comment by brwarner** [comment]
Thanks. Guess I'll need to find a different way to do this.
