### ISSUE TITLE
"exceptZero" for "signDisplay" option of Intl.NumberFormat() constructor options object 

### ISSUE THREAD

**Issue by bolatovumar** [microsoft/TypeScript#46712]
# lib Update Request

In TS 4.4.4 `signDisplay` options of `Intl.NumberFormat()` constructor options object used to be of type `string`. See here: https://github.com/microsoft/TypeScript/blob/f633446969c069e11a9641faa13c5124745bdaad/src/lib/es2020.intl.d.ts#L267

That was changed in this PR: https://github.com/microsoft/TypeScript/pull/45647. Now it's of type `"auto" | "never" | "always" | undefined`. However, I believe this type union is incomplete and should also include `"exceptZero"` (see MDN and spec links below). As a result starting from TS 4.5.0-beta (or possibly earlier, I didn't test versions between 4.4.4 and 4.5.0-beta) you now get an error if you try to instantiate `Intl.NumberFormat` with `signDisplay` option set to `"exceptZero"`.

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

I'm expecting `"exceptZero"` to be a valid value for `signDisplay` option of `Intl.NumberFormat()` constructor options object.

## Sample Code

```ts
const numberFormatter = new Intl.NumberFormat('en', {
    signDisplay: 'exceptZero' // expect `exceptZero` to be a valid value but it's not according to type definitions
});
```

## Documentation Link

See MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#parameters
See spec: https://402.ecma-international.org/7.0/#sec-getoption

**Comment by iAziz786** [comment]
I would like to pick this issue.

**Comment by iAziz786** [comment]
I assume adding the missing type in the union will do the work.

**Comment by bolatovumar** [comment]
@iAziz786 yeah, that's correct.

**Comment by iAziz786** [comment]
Cool, @DanielRosenwasser may I request for the PR to review by anyone?

**Comment by ArthurGuez** [comment]
Hi there,

I've updated Typescript to 4.5.5 but I'm still having the aforementioned issue. Has the fix been applied?
