### ISSUE TITLE
Disallow widening of accessors for overridden methods

### ISSUE THREAD

**Issue by drake7707** [Microsoft/TypeScript#4672]
```
class Test {
	protected doSomething() {
	}
}
class SubTest extends Test {
	doSomething() {
		super.doSomething();
		alert("Something");
	}
}
```

This will give an error:
```
let test:Test = new SubTest();
test.doSomething();
```

This will not:
```
let test:SubTest = new SubTest();
test.doSomething();
```

**Comment by benliddicott** [comment]
Is your suggestion that it should not be possible to override a protected method with a public method?

If so, I think that will cause problem - in fact we have people like me asking for the opposite:

#471 Permit in implementing class to ignore private methods of implemented interface
#3854 Allow interface implementors to implement protected methods
#3598

**Comment by drake7707** [comment]
Ah you bring up good points. I'm so used to writing C# where subclasses can't change the accessors of methods it's overriding that I found myself thinking that this might not be intended behaviour.

I thought about it some more and looked things up (it seems Java does allow this behaviour), e.g http://stackoverflow.com/questions/23081671/why-can-i-override-a-protected-method-with-public-method , http://stackoverflow.com/questions/10458142/why-a-function-with-protected-modifier-can-be-overridden-and-accessible-every-wh , http://stackoverflow.com/questions/12780779/why-java-allows-increasing-the-visibility-of-protected-methods-in-child-class

So in hindsight this might not be the best idea, I do wonder why C# does not allow this hmmm, something to read up on.
