### ISSUE TITLE
Please add a clickable file link

### ISSUE THREAD

**Issue by present-g** [microsoft/TypeScript#46729]
Please add a clickable file link to the console error message

Instead:
`src/directory/component.tsx`

Something like this:
`file://$(pwd)/src/directory/component.tsx`

<img width="804" alt="Знімок екрана 2021-11-08 о 11 44 17" src="https://user-images.githubusercontent.com/47174128/140719788-2541a086-3e96-46cb-922a-19c4fb1094fb.png">

This will greatly speed up bug fixes!)

Thanks)

**Comment by DanielRosenwasser** [comment]
Please follow the issue template and provide more detail.

**Comment by present-g** [comment]
When the Typescript compiler encounters an error, it displays the following message in the console:

<img width="1406" alt="Знімок екрана 2021-11-08 о 12 03 33" src="https://user-images.githubusercontent.com/47174128/140723138-41ae723e-48f5-4ada-ae1c-eb9df4e53cd1.png">

There is a link to the file and line number where the error occurred, and it's cool!

But it would also be good. be able to go to the problem area by clicking the link ...

It would be nice to show the full path with the prefix **file: //**, as I suggested above ...

**Comment by andrewbranch** [comment]
FWIW these links are already clickable in the VS Code terminal and in iTerm 2. Sadly not in Terminal.app. 😕 In VS Code it even takes you to the exact line and number. I personally don’t think the extra verbosity is worth it for what seems should just be a terminal feature, and already is a feature of many terminals.

**Comment by sandersn** [comment]
Clickability differs per-tool. For example, the above output is clickable when you compile inside emacs.

**Comment by present-g** [comment]
Yes, thanks, the links are clickable in VS Code.

I work at WebStorm and before that I thought the only way to make them clickable was to add the prefix `file: //` or `http: //`, `ftp: //` and so on.

So this is a question for WebStorm developers.

Thank you all for your time!)
