### ISSUE TITLE
Twoslash quick infos for all!

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript#46720]
# Suggestion

## 🔍 Search Terms

twoslash, quick info, language server protocol, tsserver, `//^?`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The TypeScript playground recently got a new feature which lets users introduce special comments, which the playground will automatically annotate with type info.

![image](https://user-images.githubusercontent.com/19329837/140652838-8d93abee-1692-4226-87fb-232502af3ddb.png)

This is incredibly useful when writing types, since it makes it possible to look at the results of several types, change a type alias, and quickly review each test case without needing to hover over each resulting type. I think this feature should be provided by tsserver, so that it can be easily made available in other development environments, particularly within VSCode.

## 📃 Motivating Example

The TypeScript website is a perfect example of how useful this feature is. Take a look at the documentation for [`Exclude<T, U>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#excludetype-excludedunion). It's easy to scan the example and immediately guess at what the type does.

Then put the same example in your IDE. It's no longer possible to, at a glance, see the result of all three types. You have to hover over `T0`, `T1`, `T2` in order to see what the type produced.

```ts
type T0 = Exclude<"a" | "b" | "c", "a">;
type T1 = Exclude<"a" | "b" | "c", "a" | "b">;
type T2 = Exclude<string | number | (() => void), Function>;
```

## 💻 Use Cases

- Easier development of complex type transforms
- Reduction of mouse use ;)

**Comment by tjjfvi** [comment]
[Here's an example of this in action on the playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgDFAvFAogDwMYBsCuATCAHgCIBDYqAHymICMLriNiAaG8gPgG4AoAej5QhAPQD8PUJFgBGJKky4CJclRr1VTVuwZri3foJHjJ0GACY56bPiIBnYACcAlgDsA5qpc4AtrQgPVAApAgEokDigANwB7JzwQtgAxHBcMYCdol30BISgxHiA)

**Comment by DanielRosenwasser** [comment]
> Reduction of mouse use ;)

For what it's worth, you can trigger quick info with the keyboard in editors like Visual Studio Code. It's a sequence of <kbd>Ctrl</kbd>+<kbd>K</kbd>, <kbd>Ctrl</kbd>+<kbd>I</kbd> 🙂

![image](https://user-images.githubusercontent.com/972891/140695316-ad122045-cc6d-4515-9b87-2e6c15d3ed59.png)

But I understand it's useful to have this update dynamically.

**Comment by Gerrit0** [comment]
There's a VSCode extension which supports this now, don't think it needs to be builtin: https://marketplace.visualstudio.com/items?itemName=Orta.vscode-twoslash-queries
