### ISSUE TITLE
Discriminating a type union results in unexpected possible unsoundness

### ISSUE THREAD

**Issue by denis-sokolov** [microsoft/TypeScript#46730]
# Bug Report

### 🔎 Search Terms

type guard, property checking, discriminated, narrowing, union, property existence, type assertion,

I’m sorry if this is a duplicate, I could not come up with a clear way to name this behavior and recognize it in the list of issues.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs and Type System Behavior

Earliest version tested: 3.3.3333
Last version tested: 4.6.0-dev.20211105

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=4&ts=4.6.0-dev.20211105#code/C4TwDgpgBAYg9nKBeKBvKBLAJgLigZ2ACcMA7AcygF8oAfNTXA4s8gbijjGAzlIEMANnlIBXALYAjCEWpsAUADNRpAMY8+UUnADy3XgMEBBQYLgB3CFgAUYfkX7i86bHkIkKHLhsMB+ERAAbjLUAJRoVPLyqnyEUJLIDK5QAOQpADSc+nxCeABM1FD8+LAICtp6PkImZpY2kqEcAPRNUACiRERwRJnFUBAAHpDqVvIV2YY1FlbWAETeBkKzmKTxUL5reA3NrQByiDJdRL7yQA)

### 💻 Code

```ts
type Foo = { id: string } | { id: string; optional: number };
function noOptionalAllowed(param: { id: string; optional?: never }) {}

const b = { id: '', optional: 2 } as Foo;
noOptionalAllowed(b); // Error, as expected
noOptionalAllowed("optional" in b ? b : b); // No error?
```

### 🙁 Actual behavior

No error on the last line.

### 🙂 Expected behavior

Error on the last line. `x ? b : b` and `b` should be of the same type and behave the same (ignoring side-effects in `x`). On the last line of the example the type of `b` in the “if-true” branch includes the optional field, but the type of the entire expression `"optional" in b ? b : b` is `{ id: string }` with the optional field missing!

**Comment by MartinJohns** [comment]
Your variable `a` is narrowed to the type `{ id: string; optional: number }`, that's why you see the different behaviour. This narrowing is intended. Using the type assertion `as Foo` you prevent this narrowing.

**Comment by denis-sokolov** [comment]
@MartinJohns, thank you, this explains the case with `a`. I was misled by the type hint at the declaration line ([new issue](https://github.com/microsoft/TypeScript/issues/46731)), but everywhere else it is consistent. This simplifies the issue considerably and leaves only the core of the question in here. Thank you!

**Comment by andrewbranch** [comment]
Subtype reduction strikes again. This example looks pretty unfortunate though 😕

**Comment by andrewbranch** [comment]
I don’t think there’s anything we can do here. The ternary does subtype reduction on the union of the narrowed type and the unnarrowed type of `b` (the true and false branch of the conditional), which is `{ id: string }`. Then that is subsequently assignable to `{ id: string, optional?: never }`. This is the same unsoundness as this aliasing: https://www.typescriptlang.org/play?jsx=4&ts=4.1.5#code/CYUwxgNghgTiAEEQBd7NgcxQLngb3ilwGdkYBLAOwwBp4AjAfl0oFcBbekGeAXwG4AUKEiwESVFWTd2IYOSjTcBIvFIVqfIYLAB7SqXi76AK3gBefIVwAiKGrJUMNuvVugAZlXLSIAT3hKXVR7Nk5uGz5BKRk5BWkLI1MhdBgsVEsYmFl5RRBtIA

so there’s nothing new here, just two things working as expected that combine to look very strange in this case.

**Comment by denis-sokolov** [comment]
Thank you for your investigation, @andrewbranch! That sounds like a very precise explanation of what’s happening. This helps me find this to be a duplicate of #46449.
