### ISSUE TITLE
Typescriptlang.dev

### ISSUE THREAD

**Issue by TarunavBA** [microsoft/TypeScript#46745]
# Suggestion

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
I would like a typescriptlang.dev domain for typescript beta and RC.

## 📃 Motivating Example

Like flutter.dev

**Comment by MartinJohns** [comment]
But... Why?
