### ISSUE TITLE
Change JSON.parse return type to JsonObject | JsonValue

### ISSUE THREAD

**Issue by gajus** [microsoft/TypeScript#46749]
# Suggestion

At the moment, `JSON.parse` returns `any` type. It would be nice if the returned type was more strict, e.g.

```ts
type JsonObject = { [key: string]: JsonValue, };
type JsonValue = JsonObject | JsonValue[] | boolean | number | string | null;
```

It then could be `JsonObject | JsonValue`.

**Comment by tadhgmister** [comment]
see #1897, I'm not sure why there isn't more movement on it I swear I've seen TSConf boast about how they can now represent `json` with a single type declaration.
