### ISSUE TITLE
can't assert the type through `Object.prototype.toString`

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#46758]
# Bug Report

check playground, the problem as the title says

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQRscAdpgC6gBmc+AtgIZUAirKAvKABRWYAXKA5UUAH1DkArowBGBAJSguAPlABvUqACWtPlUgAHJHH0CVXHgHIZ8gtdAAyJ7swA5Zu-6ZFywlTS+OQA3CSgZJQ0VDqM3NoRAPJyAFZIMFQAdEb4cFR5xkiZ+QDKVPg65KiZMMwANnU+ylY2ANpwqek0okgAuo4A-KAWwuRIAO4inLwA1AKKYRHwUaCMKsOxRahIVOAUVDi8yjOgAIyLkdSgCOsxcZnb7NML2stXOLebDzsAEnBBmCOFzeNEYax4dy2O3AlWkYkBLwAviEgA)

### 💻 Code

```ts
const formatDate = (ts: Date | number) => {
  if (typeof ts === 'number' && isNaN(ts)) return;

// already assert the type here
  const time =
    Object.prototype.toString.call(ts) === '[object Date]' ? ts : new Date(+ts);

  const m = time.getMonth() + 1;
  const d = time.getDate();
  const h = time.getHours();
  const mm = time.getMinutes();
};
```

**Comment by MartinJohns** [comment]
1. You forgot to fill out the issue template.
2. TypeScript has no understanding that `Object.prototype.toString.call(ts) === '[object Date]'` would narrow `ts`. And I highly doubt this is a big use case.
3. You can simplify the code by just checking if the type is `number` and swap result.

**Comment by bbrk24** [comment]
Consider the following example:

```ts
let obj = new String('[object Date]');
```

`obj.toString()` returns `[object Date]`, but `object instanceof Date` returns `false`. In general, it is not possible to narrow the type of an object based on its `toString()` method.

**Comment by whzx5byb** [comment]
You should use a user-defined type guard.
```ts
function isDate(input: unknown): input is Date {
  return Object.prototype.toString.call(input) === '[object Date]';
}
```

===
> `obj.toString()` returns `[object Date]`, but `object instanceof Date` returns `false`. In general, it is not possible to narrow the type of an object based on its `toString()` method.

`Object.prototype.toString.call(obj)` is not equivalent to `obj.toString()`.
`Object.prototype.toString.call(new String('[object Date]'))` returns `[object String]`.

**Comment by HomyeeKing** [comment]
it's more like a feature 
you can break any rules if you want, but isn't  better for general case to narrow the type of  `Object.prototype.toString` case 

I'd like to talk it from implement complexity , the trade-off,  not the code writing,  also I can even just use `as Type` and leave it as is

**Comment by fatcerberus** [comment]
Or you could, you know, just check whether `ts instanceof Date`?  Or `typeof ts === 'number'`.  What you're doing is more complex (in terms of cognitive overhead) than both of those.
