### ISSUE TITLE
Null check does not cause control flow analysis to narrow nullable interface property

### ISSUE THREAD

**Issue by btoo** [microsoft/TypeScript#46757]
# Bug Report

### 🔎 Search Terms

interface optional properties props nullable nonnullable non-nullable control flow analysis type narrow

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed all the FAQ entries

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/JYOwLgpgTgZghgYwgAgHIFcA2m4CNMQAKUA9gA4DOyA3gFDLIhY75GlkD8AXMhWFKADmtAL61aYAJ5kUAJQgBHdMCgQAJsXJUAvMnlKV6gDwZseApsoA+cWogIcq5DHQgEYYCRDIA7sDAAFvrKqhrsFAAUqgahlhQ8wYZhWgCUPHAgkgDc4i5uHl6+-gGmLBbhEWThPKXmbKk09MjAMMgRAIRVWgB0TGaslinIqmDoUCA5TQD0AFQzyIHAVEvICCRQqu7IM1NNUjLIltCYkgAq0hCocBskPuqnJABCl161rMi6+xAkrV2Uvcw6pZxAxZvNcOgwAsAitYW51psoTs9hdkABJeEbexgE4AZQ82De5S0HwWFx+yD+FEmoLmTW2yAAglBBOgALYQcDIClfZAAciJ9UofOaVBAJChcAoFGAghAdQWJEp1zgHMgUG5rV5fMSoRMgIG4SsfO69PmDHOMioFL+0Ck-IoJA5gssIuuKFAazZZDgHlYpoYDMDyEtKD5fAEIEEyAAPshXHYYKB1CKVuLJdLZfL3mAldqI0ITWbg4HQ-yExAkyAU6LGBLkFKZXKFbmyQdw-xC90IgAmADMABYAKwpM27Bh+QK69RxSrhUdiIA)

### 💻 Code

```ts
interface NullableProps {
  nullableProp?: string
}

type RequiredProps = Required<NullableProps>

declare function withRequiredProps(requiredProps: RequiredProps): any;

function withNullableProps(props: NullableProps) {
  if (!props.nullableProp) return;

  /** this is correct */
  type ProperlyTypeNarrowedToBeNonNullable = typeof props.nullableProp

  /** but this is incorrect */
  type IncorrectlyStillNullableProps = typeof props;

  /**
   * Argument of type 'NullableProps' is not assignable to parameter of type 'Required<NullableProps>'.
   *   Types of property 'someNullableProp' are incompatible.
   *     Type 'string | undefined' is not assignable to type 'string'.
   *       Type 'undefined' is not assignable to type 'string'.(2345)
   */
  withRequiredProps(props)
}
```

### 🙁 Actual behavior

the line
```ts
if (!props.nullableProp) return;
```
does not narrow `props` to be `{ nullableProp: NonNullable }`

### 🙂 Expected behavior

the line
```ts
if (!props.nullableProp) return;
```
should narrow `props` to be `{ nullableProp: NonNullable }`

**Comment by jcalz** [comment]
duplicate of #31755 ?

**Comment by MartinJohns** [comment]
Duplicate of #42384.

**Comment by btoo** [comment]
glad i'm not the only one. let's hope https://github.com/microsoft/TypeScript/issues/42384#issuecomment-763048323 leads somewhere!
