### ISSUE TITLE
Trying to install typescript@1.6.0-beta results in "invalid" package in npm ls -g output

### ISSUE THREAD

**Issue by sgronblo** [Microsoft/TypeScript#4676]
Looking to try out the TS1.6 beta but having trouble installing it properly. Any ideas? I'm using node 0.12.7 installed through nvm.

**Comment by mhegazy** [comment]
i can see the same issue too. @DanielRosenwasser can you take a look.

**Comment by DanielRosenwasser** [comment]
What version of npm are you using? Try updating with `npm install -g npm` (if you're on Windows [you might have to follow these instructions](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)).

**Comment by sgronblo** [comment]
I was using 2.11.3. Problem solved by updating npm. Thanks.

**Comment by DanielRosenwasser** [comment]
For any future readers, this *seems* to have been caused by the fact that the version in our `package.json` was had a tag in the name (i.e. `1.6.0-dev...`/`1.6.0-beta`). This was a regression and fixed in later versions of npm.
