### ISSUE TITLE
Conditional type simplified too early

### ISSUE THREAD

**Issue by webstrand** [microsoft/TypeScript#46761]
# Bug Report

### 🔎 Search Terms
conditional tuple extend simplify type parameter constraint

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQglsKBeKAGKAfKBGA3AKFEigEEA7AEwB4SoIAPYCSgZ1gQBpY7HmK34wAHzIoAbRJcYAXR5NW47F2yyA-DigAuNAULhoAFQgtgNOXwGduDef3bDR5arRsWN69NqXXeC7FA8tHCECAHpQqEioAD1VfD1iAFtRIxMqb2wQqHCcLhYACwB7AFcAGwooACNoVCA)

### 💻 Code
```ts
type Bit = 0 | 1;
type And<A extends Bit, B extends Bit> = [A, B] extends [1, 1] ? 1 : 0;

type Test<A extends Bit, B extends Bit> = And<A extends 1 ? 0 : 1, B extends 1 ? 0 : 1>;
//    ^? type Test<I1 extends Bit, I2 extends Bit> = 1

type a = Test<1, 1>; // 1, should be 0
```

### 🙁 Actual behavior

`Test<A, B>` is being incorrectly simplified to `1` before being called, and `Test<1, 1>` is resolving incorrectly to `1`.

### 🙂 Expected behavior

`Test<A, B>` should not be simplified, and `Test<1, 1>` should resolve to `0`.

**Comment by andrewbranch** [comment]
Your inner conditional types being fed to `And` are distributive. Making them not distributive [fixes it](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211105#code/C4TwDgpgBAQglsKBeKAGKAfKBGA3AKFEigEEA7AEwB4SoIAPYCSgZ1gQBpY7HmK34wAHzIoAbRJcYAXR5NW47F2yyA-DigAuNAULhoAFQgtgNOXwGduDef3bDR5ahNk2LitWi04uYmeYUxFSh1dG1sIQIAeiioOKgAPVV8PWIAW1EjEyolHEioGJ8oFgALAHsAVwAbCigAI2hUIAO). Still, it feels odd to me. @weswigham is this expected behavior?

**Comment by webstrand** [comment]
Some more weird behavior: If I extract the conditional out into an alias, `Test1<A,B>` still gets simplified to `1`, but if I add another branch to that conditional, `Test2<A,B>` is not simplified: [playground](https://www.typescriptlang.org/play?ts=4.4.4#code/C4TwDgpgBAQglsKBeKAGKAfKBGA3AKFEigEEA7AEwB4SoIAPYCSgZ1gQBpY7HmK34wAHzIoAbRJcYAXR5NW47F2yyA-DigAuNAULhoAOQD2wbFQCScvgIQiUlhvP4b16bXj3EAKhBamaVgqCUoHOgnaklFTG-iRCXDFmMEJCBAD0aVBZUAB6qvie0AC2oj5+Zko4qVAZOFwsABZGAK4ANhRQAEbQqAX4tSQUFHBkAOZQAIZkJg0QAE5QAMZGlAhwKxOtSw1To75QwLNdEDsAbusLE4gTUMN+U4sQmgVEhiYATBahNsKiDrwKbBQVxaKD-JxsdDqIHaVAEV5QMrAT60RzWdjAEJooK2UTkagxFHxKCEqjJVL9TLZPIvfRQMilXzIqiVbDVWroCZsBiQRZMCj4IA)

**Comment by whzx5byb** [comment]
If you make `And` like this, `Test<A, B>` will resolve to `0`. That's weird.
```ts
type And<A extends Bit, B extends Bit> = A extends 1 ? B extends 1 ? 1 : 0 : 0;
```
