### ISSUE TITLE
Arrow function with generic is confused with JSX tag

### ISSUE THREAD

**Issue by reggi** [microsoft/TypeScript#46765]
# Bug Report

### 🔎 Search Terms

react typescript generic anonymous function

### 🕗 Version & Regression Information

Latest version

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/G4QwTgBAFgpgNnA9hAvBAPAFQHwAoQBcEmAlKthAC5gCuMQA

### 💻 Code

```
var hello = <T>(a: T) => true
```

### 🙁 Actual behavior

Seems like typescript thinks that generic is JSX tag 

### 🙂 Expected behavior

Typescript would realize that this is a generic and not JSX tag

**Comment by reggi** [comment]
If you add extends does work `var hello = <T extends any>(a: T) => true`

**Comment by MartinJohns** [comment]
Duplicate of #15713.
