### ISSUE TITLE
Improve type inference for anonymous/nested functions that return a Tuple Type

### ISSUE THREAD

**Issue by corno** [microsoft/TypeScript#46777]
# Suggestion

First of all: Type inference in TypeScript is phenomenal. I rarely encounter situations where the compiler is not able to deduce the type where it would be trivial.
However, there is one pattern that I use a lot which requires me to specify the type every time.
That is when I use a nested anonymous function that I immediately call

## 🔍 Search Terms
Tuple Type
nested anonymous function
return type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Anonymous Nested functions can determine what it's proper return type is, not based on it's own implementation, but on its context

## 📃 Motivating Example

````
        type Bar =
            | ["A"]
            | ["B"]

        function foo(input: string): Bar {
            //return (() => { <--- this is not working
            return ((): Bar => { //<-- the type has to be specified
                switch (input) {
                    case "aa":
                        return ["A"]
                    case "B":
                        return ["B"]
                    default:
                        throw new Error("")
                }
            })()
        }
````

## 💻 Use Cases

It would clean up the code I write a lot, and it would make it easier to write the code in the first place

**Comment by whzx5byb** [comment]
[It works in v4.5.0-beta](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/C4TwDgpgBAQghgJygXgLACgpezrAfKAbQCIBBYgXQ1xqgJJkowwDMBXAOwGNgBLAew5QW-fgApeHMG2AAuKAGdgCSQHMAlPPhIA3tWwIIwNgiFix6lAD4oezLQUB3XsC4ALKBKkzLd2ri44BWhiODhiWX1-GkNjUyIyJntoqEDgqGJGSOSUgyMTIQYk3KgAEwgWODYAGzkokqhgNwR+RygOCDaAUQQWhDFiYnV6nABfetH1CwxRoA)

**Comment by corno** [comment]
Nice!

(sorry for not checking this on the beta)
