### ISSUE TITLE
`extends` within dt function is not safe?

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#46779]
# Bug Report

### 🔎 Search Terms
`extends` `dt function`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
    type dtExtends<X, Y> = X extends Y ? true : false

    // Expected `true`, but actually it's `never`
    type y = dtExtends<never, never>
```

### 🙁 Actual behavior
`never extends never` is `true`.

But `_dtExtends<never, never>` is not `true`, but `never`.

```typescript
  {
    'describe: extends within dt function is unsafe'

    type _dtExtends<X, Y> = X extends Y ? true : false

    'describe: never extends never'
    // $ExpectType true
    type x = never extends never ? true : false

    'describe: unexpectedly, never is not extends never within dt function
    // Expected `true`, but actually it's `never`
    // $ExpectType never
    type y = _dtExtends<never, never>

  }
```

### 🙂 Expected behavior
`never extends never` is `true`.

`_dtExtends<never, never>` is `true`.

```typescript
  {
    'describe: extends within dt function is unsafe'

    type _dtExtends<X, Y> = X extends Y ? true : false

    'describe: never extends never'
    // $ExpectType true
    type x = never extends never ? true : false

    'describe: never extends never within dt function'
    // $ExpectType true
    type y = _dtExtends<never, never>

  }
```

**Comment by JeroenoBoy** [comment]
try `dtR<X, Y>()` you currently use an Array for the first type, and nothing as the second.

**Comment by loynoir** [comment]
> try `dtR<X, Y>()` you currently use an Array for the first type, and nothing as the second.

Ah, that is not the problem, just add reference to avoid `... is declared but never used`.

The problem is `_dtExtends<never, never>` is not return `true`. 🤔

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/23182#issuecomment-379091887

**Comment by MartinJohns** [comment]
`never` is a special union type, so your conditional type is distributed. But since `never` is basically an empty union, there's nothing to distribute over and you end up with `never`. If you disable distribution in the conditional type (as documented) you end up with `true`.

**Comment by loynoir** [comment]
You guys are awesome!!!!!!!! 😘
