### ISSUE TITLE
Function none optional parameters are not enforced

### ISSUE THREAD

**Issue by gilamran** [Microsoft/TypeScript#4677]
This code will compile with NO errors:

```code
type callback = (a:number, b:string)=>void;
var c : callback = function(a:number) {}; // b is not optional
```

This also can be found for example on forEach of the Array declarations in lib.d.ts:
```code
forEach(callbackfn: (value: T, index: number, array: T[]) => void, thisArg?: any): void;
```

index, and array should be marked as optional. In practice (Like the example above) TypeScript will not error if you didn't supply them, but it should.

**Comment by mhegazy** [comment]
In JavaScript it is not a runtime error to pass additional parameters to a function. in this example, callback says it will provide 2 parameters, but your function expression, says it only needs one. your function would still work at runt time, and this is a valid assignment. this is similar to declaring a second parameter `b` but never using it. the oposite however is not correct.

```ts
type callback = (a:number, b:string)=>void;
var c1 : callback = function(a:number) { }; // OK, will get an extra argument at runtime that will be ignored
var c2 : callback = function(a:number, b: string) { }; // OK, still, will get a b that will never be used

var c : callback = function(a, b, c) { }; // Error, this function declares it needs 3 arguments, callback will only pass 2, this is not a safe assignment.
```

**Comment by danquirk** [comment]
In addition, not only is this allowed in JS, but it's used constantly. If we did this:
_In practice (Like the example above) TypeScript will not error if you didn't supply them, but it should._
then nearly every Array.map and such function call would now be an error in TypeScript. People don't want to write ```[1,2,3 ].map((val, idx, arr) => val + 1);``` just to satisfy the compiler.
