### ISSUE TITLE
It will report an error while writing the coupling code

### ISSUE THREAD

**Issue by forget-forever** [microsoft/TypeScript#46773]
# Bug Report

It will report an error while writing the coupling code, 
[like this demo](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/C4TwDgpgBAKgjFAvFA3lAhgLigOwK4C2ARhAE5QC+A3AFCiSwBMSuhJpt90MAzCwM7BSASxwBzWgGMA9jkFQAFuhwATADbRkKGlF1QA1hBBxsACnSkx2eAEokAPlQ69LgPSuoK6VH7SCEYAVRMQA6MOddCgAaCIMjRjMLKyY7REdtFzcPLx8-AKDxMJDY6NjDEB5Ey2seVPTYrM9vX39A4KKSmIoaGTlgKAAzaW9kAB4AaSgIAA9gCFV+OJBpAaguFcVldQh7c0sTKHGojEsEqAAFC3RWsn5R03XVpVUNGwBtcYBdezeABk+6k5GjkWvlRPwOi5SAE8KQcJsXhA3kk4J89mJGDZaBQgA)

### 💻 Code

[like this demo](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/C4TwDgpgBAKgjFAvFA3lAhgLigOwK4C2ARhAE5QC+A3AFCiSwBMSuhJpt90MAzCwM7BSASxwBzWgGMA9jkFQAFuhwATADbRkKGlF1QA1hBBxsACnSkx2eAEokAPlQ69LgPSuoK6VH7SCEYAVRMQA6MOddCgAaCIMjRjMLKyY7REdtFzcPLx8-AKDxMJDY6NjDEB5Ey2seVPTYrM9vX39A4KKSmIoaGTlgKAAzaW9kAB4AaSgIAA9gCFV+OJBpAaguFcVldQh7c0sTKHGojEsEqAAFC3RWsn5R03XVpVUNGwBtcYBdezeABk+6k5GjkWvlRPwOi5SAE8KQcJsXhA3kk4J89mJGDZaBQgA)

I could just write “//@ ts-ignore” in 16th line to hide this error。
```

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
