### ISSUE TITLE
typescript can't recognize the type of keys object

### ISSUE THREAD

**Issue by sinajamshidi247** [microsoft/TypeScript#46775]
# Bug Report

`
interface useInfoState {
    code : number;
    name : string;
    new_password : string;
    new_password_confirm : string
}

    const changeInfoState: (k: keyof useInfoState, v: string | number) => void = (k, v) => {
        const _userInfo = Object.assign({}, userInfo);
        _userInfo[k] = v;
        setUserInfo(_userInfo);
    }

`
![image](https://user-images.githubusercontent.com/67558594/141284981-aa21ca95-8be7-4640-819d-2e6d335315f3.png)

Error : TS2322

**Comment by MartinJohns** [comment]
This error is correct. `k` could refer to a `string` property, but `v` could be a `number`. No defect here.

**Comment by sinajamshidi247** [comment]
whats the correct type of `k` ? would you help me in this func  ?

**Comment by tadhgmister** [comment]
[probably use a generic](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyycAXMgM5hSgDmA3AUQEZkgCuAtk9A-gL4EAJhAQAbOFBSiIYCmDiQyGdARhsQCMMHQhkg9ABUAFrQBCcQQAoA1mWsQAnuhhpMAGmQA3JZgDa9pxdlAF0ASjxCZAB6KOQAATByAFoIAA8ABxEwFKgodChGOQUIf2DkAF4vAgF8fWMzC0sAIjgmjwBGUOjYsBNyCiN0NlFBZBB0WW5iUVF0AHcIUe4EOHI2FAByOA2BoZHkHVEHZCnV8mAaEDgmaWQwLEpqEBoAQgJ3-DUNLR09QxNngBxTCCAA8AGlkGlICBBP0As5XOgAHw2MjgjzeZS+cFhCJESjFUoVLy8Gp1AE0YHoKwtNrITrdO59ZA0YCeCD9dJ5TJQKG5fJAA). The way you have written the function I could pass any key and any value whether or not it matches the key.  If you use a generic you get the correct type signature on both the inside and outside of the function

```ts
interface Foo {
  a: string;
  b: number;
}
declare let state: Foo
function doThingBad(k: keyof Foo, v: Foo[keyof Foo]){
  // @ts-expect-error
  state[k] = v
}
doThingBad("a", 1) // this should not be allowed becasue 'a' should only be assignable to string!


function doThingGood<K extends keyof Foo>(k: K, v:Foo[K]){
  state[k] = v;
}
doThingGood("a", 1) // this gives proper error
```
