### ISSUE TITLE
TypeScript Coding guidelines have no scope

### ISSUE THREAD

**Issue by StefanSchoof** [Microsoft/TypeScript#4679]
In Coding guidelines at [Coding guidelines](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) is not written if this guidelines are for contributing to the typescript project itself or if this are kind of guidelines for any project written in typescript.

The bug https://github.com/ligershark/side-waffle/issues/303 show a result of this.

**Comment by mhegazy** [comment]
These are meant for the typescript compiler primarily. nevertheless, they do represent views from the typescript team on how a typescript code base should look like. they are not complete, nor comprehensive, we would like to think of them as work in progress. if you do find them helpful for your project by all means use them.

**Comment by StefanSchoof** [comment]
This is the kind of information I think should placed at top of the Coding Guidlines. Searching for [typescript coding conventions](https://www.bing.com/search?q=typescript+coding+conventions) is this page the first result. So the visitor is missing who is the audience of this page.

**Comment by DanielRosenwasser** [comment]
@StefanSchoof I've added a small comment, thanks for the suggestion!
