### ISSUE TITLE
Extract<T, T> should be the same as T. But It does not behave the same way.

### ISSUE THREAD

**Issue by amine-benselim** [microsoft/TypeScript#46794]
# Bug Report

### 🔎 Search Terms

Extract
Extract is not pure
Extract behaviour

### 🕗 Version & Regression Information

v4.5.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/C4TwDgpgBAkgdmArsKBeKdEFsBGEBOA2gLpQA+UAzsPgJZwDmJA3AFCuiRQBSA9vQEF8+AIYhKAHgAqAPjRQpUCAA9gEOABNKUABT0AZgSgBRADYQs64AEoSUAPwnzluMDsAuDBABuBNp2g+QWExSgB1WmAAC2NVUQBjYGk5dFiaEUTpABoFORU1TW09OEN8JwsrW1JHMwrXDy9ffDYOcGgAeWQkFHQguCFRcQl4brkAejGMbDwiUgpqOkYSVq5O4G6I6LSEnp5+fpDxTZi4jKSR5HHJnQX6BnIp3AIq9gCoMJFXCA15HUwnsrzGh3KrMIA)

### 💻 Code

```
type Input = number[] | string[];

type JoinArrays<T> = T extends (infer Element)[] ? Element[] : never;
type JoinArraysWithExtract<T> = Extract<T, T> extends (infer Element)[] ? Element[] : never;

type Output = JoinArrays<Input> // number[] | string[]
type OutputWithExtract = JoinArraysWithExtract<Input> // (string | number)[]

type Wanted = (number | string)[];
```

### 🙁 Actual behavior

`type Extract<T, U> = T extends U ? T : never` implies that replacing `Extract<T, T>` with `T` should return exactly the same type. 

But replacing it in the example I have provided results in two different types. 

### 🙂 Expected behavior
```
type JoinArrays<T> = T extends (infer Element)[] ? Element[] : never; 
```

should be the same as 

```
type JoinArraysWithExtract<T> = Extract<T, T> extends (infer Element)[] ? Element[] : never;
```

**Comment by fatcerberus** [comment]
`T extends…` is distributive.  `Extract<T, T> extends…` is not, because `Extract<T, T>` is not a naked type parameter.

https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

**Comment by amine-benselim** [comment]
Thank you for the explanation. Now that you spell it out it makes sense. Where do I find the information that naked type params are not distributive? 

> `T extends…` is distributive. `Extract<T, T> extends…` is not, because `Extract<T, T>` is not a naked type parameter.
> 
> https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

**Comment by fatcerberus** [comment]
I believe it used to say it explicitly in the v1 handbook. It looks like the new version doesn’t mention it?  It is mentioned here, however:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types

**Comment by MartinJohns** [comment]
@fatcerberus You're not fat, just full of wisdom and knowledge.
