### ISSUE TITLE
TypeScript Template Literals break generic constraints

### ISSUE THREAD

**Issue by knyzorg** [microsoft/TypeScript#46799]
# Bug Report

I made [a SO post for it as well](https://stackoverflow.com/q/69957669/4088472) but this behavior feels like a bug as whether the first argument of a function is generic or not, should not disable constraints on the second.

### ⏯ Playground Link
[Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMIAs5gKIDcLgDOyA3gFDLIID2IIECYAXKRZcgK6HQuFhSgA5gG42AX1GUAJsEI06DZq3aduUXvyGT2UCHEK0WAIgBGcBVKPIAPsiNhgAWwjUOYK7aMAbPfiPaJMjEyMikGLzhdZDAATwAHFAwsPAIwZABeZABrCBjqGDRMHHwiUTJQSFhEFABlDhMUomQIAA9IECliACUGaigpAB4k4tSAGmQ+ARBBAD5lKlp6RmNBAmg4Lw87AHcsaBpqHygt72oTExj-Nhk5RcVjXGpgJBPINqvg0PDIlFiE5EaYAA6sAwOg6g0SmABgAVZptAidQrJKFzTIAAwAJCQYWJsWxPEYCch0UxsRDAYQANowgC6YnRDLKAHpmXZ5Et3DZ2Xdlqt6FANicOfddpUDkdhbzmF4zhciWEEBEon9EkVUNLARkAVCQWCKVCBkYRYwjDNRKy7DcTVzPNbpUxHs8ICd7Qplm93F8lT9ovE1VgACKyG1azKAvXg+qAo1uzlmllsmrUZDwKATFOCajUKQAQhCloAMhAwAByYjbASQDPOZD86DPQhMb3KlAwDggRjAWgTepyAQmCAw6gx7Dw9pI4aAmYACjYEChLGwozYCA2XjMCCyLBncTgMVlcCkLCnUOp2FpAEoMnMnVIyJeWHeyoQ+wgB0OR1CZ8bpUZxru+6HlI17pHM5AqJaGpQLojBeDE46CowxCOFgCDoEIfoJGwlCqsgMIAApAdQR7aqq+TIHuB4kVIwjIJaJCqDwEyaNMdHBGIl5lIqraph2XY9q+Jj9sAg7DgaqQDGOrQTsQp6pLO86LjqqSRhJ4BSTMK6UGuXgbog27IIB1FHieRSUlSF6gbeTz3o+yDPiEQkiWJ1DqWAP42kw9aCpsAFUcB1nzJQlrYG0SFgMQ66UdQhCEKJPiUcRpGqsQoB8HoUjIBRtDwdE6AoOiNrotl9A4fRABU5UqBBKh1ZQXDMZMWjVewYjcrV9UqI16gsVMIitfVuj6IYdhmBYrxOC4bgnD4cB+No9XBCoFXMuVeGEclWWZORBQBTRoicS+b4fuJ0bfr+7rME6LwAUFJCcfRSboK4XhZfAwBeMgJhuMgUjUBAhAgKWYAAHQko6TxICVsjIHAvaDlC2UFOicaKOi4wgNQaRFdK6Kg0AA)

### 💻 Code

```ts
interface ChatEvents {
  connect: {
    user: string;
  };
  disconnect: {
    user: string;
    reason: "banned" | "timeout" | "leave";
  };
}

declare type ChatEvent = keyof ChatEvents;

interface SubEvents extends Record<ChatEvent, string> {
  connect: "general" | "watercooler" | "lobby";
  disconnect: "voice" | "text";
}

declare type EventWithSubEvent<T extends ChatEvent> = `${T}${
  | ""
  | `:${SubEvents[T]}`}`;

// "connect" | "connect:general" | "connect:watercooler" | "connect:lobby"
declare type ChatConnectEvent = EventWithSubEvent<"connect">;
// "disconnect" | "disconnect:voice" | "disconnect:text"
declare type ChatDisconnectEvent = EventWithSubEvent<"disconnect">;

// So far so good!

// Let's write some generics:
declare function subscribeToEvent<E extends ChatEvent>(
  event: E,
  callback: (payload: ChatEvents[E]) => void
): void;

subscribeToEvent("connect", (payload) => {
    // Correctly extracts matching type
    type TPayload = typeof payload; // { user: string; }
});

declare function subscribeToSubEvent<E extends ChatEvent>(
  event: EventWithSubEvent<E>,
  callback: (payload: ChatEvents[E]) => void
): void;

subscribeToSubEvent("connect:general", (payload) => {
    // Extracts all possible payload types instead of only the `connect` one
    /*
        {
            user: string;
        } | {
            user: string;
            reason: "banned" | "timeout" | "leave";
        }
    */
    type TPayload = typeof payload;
});

subscribeToSubEvent("connect:voice", () => {}) // Should fail but doesn't. `:voice` is a subevent of `disconnect`, not `connect`.
```

### 🙁 Actual behavior

Generic constraints stop being checked

### 🙂 Expected behavior

Generic constraints continue to apply

**Comment by uhyo** [comment]
Seems like your type definition went beyond TypeScript's ability to infer type parameters.

I found a workaround: change the definition of `EventWithSubEvent` to the following.

```ts
declare type EventWithSubEvent<T extends ChatEvent> = T | `${T}:${SubEvents[T]}`;
```

---

Here is a little simpler reproduction:

```ts
type FooBar = "foo" | "bar"
type U<T extends FooBar> = `${T}${"" | "1"}`

declare function foo<T extends FooBar>(arg: U<T>): T;

const a: "foo" = foo("foo1")
// Actual Behavior  : foo<FooBar>("foo1")
// Expected Behavior: foo<"foo">("foo1")
```

[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAQgQwE5QLxQEQDMHZQA+OARmtgFCiRQCqAPACpQQAewEAdgCYDOsBClQA+TFAAGAEgDeTAL6zshEtgCM2eRMqUeEAMYAbNNFwBXLvuABLOFyj44zVh279BSNCIAUaAOYAXPTMIgCUQUwA3Dr6dnzAUMhBeATijt4pcBqhlAD0uVAAglZmyIZQiBAAFsgAbrboUEGODPCeohmO2XkFAKJskFYQPBXVdQ3NCAyZ2D6Z2UA)

**Comment by RyanCavanaugh** [comment]
This doesn't demonstrate a bug. The declaration
```ts
declare type EventWithSubEvent<T extends ChatEvent> = `${T}${
  | ""
  | `:${SubEvents[T]}`}`;
```
has a legal instantiation `EventWithSubEvent<"connect" | "disconnect">`, of which `connect:voice` is a legal inhabitant:
```ts
const p: EventWithSubEvent<"connect" | "disconnect"> = "connect:voice";
```

**Comment by knyzorg** [comment]
@RyanCavanaugh I see. Why can't it infer the `T`, though?
