### ISSUE TITLE
unused React import doesn't get removed running organize imports with new react jsx transform

### ISSUE THREAD

**Issue by lcdlyxrqy** [microsoft/TypeScript#46803]
# Bug Report

### 🔎 Search Terms

jsx organize imports

### 🕗 Version & Regression Information

vscode 1.62.2
not sure about what version the built-in typescript has

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCqQA9JY4ATJTFAVwBt4AKASgC8APgA8TYADdRAenFSgA)

### 💻 Code

```tsx
import React from 'react';

export default ()=><div></div>
```
jsconfig.json
```json
{
  "compilerOptions": {
    "jsx": "react-jsx"
  },
}

```

### 🙁 Actual behavior

unused React doesn't get removed
### 🙂 Expected behavior

it should get removed because it's using the new jsx runtime

**Comment by tadhgmister** [comment]
interestingly if there are any other imports react does get removed [playground](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCtEljiIBMBXADzm1wKbbKqrQQAdgGd47ALwMkLVhUpJWdeIySYUzADbwAFAEoJAPgA8jYADcTAejOWgA) so it seems like a pretty minor issue.
