### ISSUE TITLE
Unable to move sourceMap(.map) files to separate folders in Typescript

### ISSUE THREAD

**Issue by jayapalt** [Microsoft/TypeScript#4680]
Hi,

I've posted my issues in stackoverflow. Below is the link of my issue:

http://stackoverflow.com/questions/32426004/unable-to-move-sourcemap-map-files-to-separate-folders-in-typescript

Please let me know how to move sourceMap files to other folders on run-time.

**Comment by mhegazy** [comment]
The compiler will not place your map files in a different place. the `sourceRoot` and `mapRoot` values are just to be written in the js file to help your debugger locate them at runtime. if you want them to be located at a different place, add a post build step that will copy them and set the `mapRoot` to point to thier final destination.

**Comment by entr0cks** [comment]
A value would be nice that would move the map files to the location specified in sourceRoot.
