### ISSUE TITLE
Preact's JSX runtime is not imported properly

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#46809]
# Bug Report

### 🔎 Search Terms

- preact
- preact/react-jsx
- react-jsx
- jsx

### 🕗 Version & Regression Information

It's broken on TS v4.4.3, I've never seen this working.

### ⏯ Playground Link

I don't think this can be replicated on the playground, here's the code: [asd.zip](https://github.com/microsoft/TypeScript/files/7539200/asd.zip).

### 🙁 Actual behavior

TypeScript for whatever reason is unable to import `preact/jsx-runtime`:

<img width="1728" alt="Screen Shot 2021-11-15 at 14 09 28" src="https://user-images.githubusercontent.com/1812093/141795908-f56fddf8-a1ce-4051-b1b5-ec2638e643db.png">

But even stranger than that if I import a fictitious "asd123" module suddenly JSX is type checked correctly:

<img width="1728" alt="Screen Shot 2021-11-15 at 14 10 11" src="https://user-images.githubusercontent.com/1812093/141796035-ecbb7f40-d94a-4718-8f41-d17c97964b4f.png">

And not only that makes no sense in the world, the "asd123" module doesn't even exist, and I'm not even getting an error about that!

### 🙂 Expected behavior

- Importing existent modules should not be seen as an error.
- Importing non-existent modules should be seen as an error.
- Importing non-existed module should be completely orthogonal to how JSX is type checked.

**Comment by RyanCavanaugh** [comment]
> Importing existent modules should not be seen as an error.

preact ships its own types and doesn't define this module as existing. Presumably the authors did this intentionally, either that or they have a bug. TypeScript is following the declarations provided to it.

> Importing non-existent modules should be seen as an error.

This is the intended behavior when no bindings are sourced from that import.

> Importing non-existed module should be completely orthogonal to how JSX is type checked.

I don't see a demonstration of this

**Comment by fabiospampinato** [comment]
> > Importing existent modules should not be seen as an error.

> preact ships its own types and doesn't define this module as existing. Presumably the authors did this intentionally, either that or they have a bug. TypeScript is following the declarations provided to it.

Maybe there's an issue with Preact's types here too, I'm not sure, /cc @JoviDeCroock if you'd like to comment on that.

Certainly though from what I can see TypeScript is behaving inconsistently (assuming VSCode is reporting errors from the LSP faithfully), Preact's types didn't change one bit, the only thing that changed is that I uncommented the `import "non-existent-module";` line, or is it expected that first the component has an issue and then the issue disappears?

> > Importing non-existent modules should be seen as an error.

> This is the intended behavior when no bindings are sourced from that import.

Ok, I didn't know that. I disagree with this decision but I understand that this is just a matter of preference.

> > Importing non-existed module should be completely orthogonal to how JSX is type checked.

> I don't see a demonstration of this

I'm seeing different errors for the `<Asd>{"2"}</Asd>` line depending on if the import statement exists or not, an import statement to a module that for what is worth doesn't exist, so I don't know, is TS assuming that "preact/jsx-runtime" could be declared by that module? If so this seems really confusing at best.

**Comment by JoviDeCroock** [comment]
The `types` and the reference to them look okay to me https://www.runpkg.com/?preact@10.5.15/jsx-runtime/package.json

**Comment by RyanCavanaugh** [comment]
> I'm seeing different errors  ...

This is also the intended behavior; the difference is depending on whether the file "is a module" (contains any imports/exports) or not. When a file is a script (non-module), the assumption is that you'll be pulling the JSX factory function from the global scope, since there's no other way to get it. When the file is a module, the assumption is that you'll be pulling the JSX factory function from an import, since in most contexts where a module loader is present, the JSX factory function is not installed into the global scope.
