### ISSUE TITLE
Inferred type of union with readonly properties is dependent on declaration order

### ISSUE THREAD

**Issue by EricCornelson** [microsoft/TypeScript#46814]
# Bug Report

### 🔎 Search Terms
union, readonly, order

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about unioned readonly properties

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEHUAsFMDtQC41AJ2gQwCYHtYBsBPRAgB2lAEsBnUTaAYz3TU1ADMKUqEAaRZAK6wKuaKwSly2NqAAGSNNFmV4snAGVsAW2hIKsAObLqodHgDu6AjQRp0CMaZp2c+IgCMiScvW0kKeNAoALAAUCC+sNygogBcoADeqBiuhKbx3Cj6BqAAvqAAvInpoADkoqV5ANxhEbjRCObY8UnoGbbZeYXFbWWN2JW5NaG1YFBw-OSwuAC0LrhpEmSUNHSMzI4cXLyToEIisI5LUjLykIrGqhraupDZxjSHAG5BiHYOrOjOKQsEYZENJotEqZTr5IqteKlfqDYYAhAxQ7A+ZuEEdQxdCElcqHWFhMJsIT0BAHWjYTQ6PSGAAUkUwFBJuHi7mw2EC6FgAEpEqNQAA9AD8YVAItAIFA5hgqlEyl8OhoW2i+l2dIZBzMoHoMHoAGs+N5kggBCh4McYqdrpS7oYHio2EEWE45OhbSjCHx3AIEbIXSthaLxb83hgPk63URqRQAHTQKOUBHmAJ4UAkFDYTACejkdC0CjoAzTbgUeiUGQEbACN5ebBOKgUAuIGsM7nuL6OXC7bAoOgoc20BhMFD2A40aRyGWmWCseRNZToFkvf0i+H8RTdWm4emMrmgAWI8jxfrDJdisCSiYz7Cym4KzhK03IVXbjVahh63ZoI0m4jLMdqck3FSRgrHaDqOF8oDTAi4agJ6CKpummbQDYyBUOgOi5vmhYkvQNAQfO2CLqEoqnrBbasB2BprIOw4dl2PZ9rIE4ctO-SyCedRRAiCjQOQRQblOaq4Nye79KA8SiMexGijxsY5kUpRsKypTDCR4qCvi0kiuKBr6PaKCOtS9JUCQTAEGIArcmaf6+mYVA1nQZBTqOD5SN2rxjgaT6kgRLxxuM0qHNe8rsHeOxUdQplWEckggT6sAEOxWmkeeqhsZqN6hds+rIMZUXmeIsUmLIoI2h6Xq7PSWHYEWJaJngyZmJY1gZQZDAIGkHBTvw9jxqUNClQYJ6yVG8llEp2AAEwqRxYCihpIzJZ+xoPoowy5EAA)

### 💻 Code
![image](https://user-images.githubusercontent.com/38218905/141845661-59469e46-f969-4574-a79e-26a0f4c171b9.png)

### 🙁 Actual behavior
The order of the declaration of the variables `one` and `two` affects whether the compiler will treat the property `a` as readonly. Also, the order of each variable in the conditional for the return type of `doSomething` affects the inferred return type (i.e. whether `a` is displayed as readonly or not)

Finally, when `one` is first in the conditional, the displayed type of `a` is `any`

### 🙂 Expected behavior

I would not expect the declaration order nor the conditional order to affect whether the property is considered readonly.

**Comment by RyanCavanaugh** [comment]
I believe we agreed in chat that this should be changed in an arbitrary way to make subtyping directed again? If that's not the case (or has broader implications) we should discuss at the design meeting.

**Comment by jcalz** [comment]
Can @EricCornelson  please provide plain text code and a functioning playground link? I'm looking at a possibly related issue but it's hard to tell and copying code from a screenshot is no fun for anyone.

**Comment by EricCornelson** [comment]
@jcalz fixed the playground link
