### ISSUE TITLE
Ship ts-analyze-trace

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#46813]
@amcasey has proven out https://github.com/amcasey/ts-analyze-trace/ is useful for self-servicing with performance issues. We are interested in moving it into the Microsoft org on GitHub. Let's do so and publish it on npm under `@microsoft`.

**Comment by amcasey** [comment]
I've rejected a couple of (good) PRs on my repo to prevent legal complications.  When it's somewhere public and has a real CLA, we should ping those authors about porting their fixes.

**Comment by amcasey** [comment]
New home is https://github.com/microsoft/typescript-analyze-trace.
