### ISSUE TITLE
Eliminate circular reference error on type T = Record<string, string | T>

### ISSUE THREAD

**Issue by jedwards1211** [microsoft/TypeScript#46846]
# Bug Report

TS should accept `type T = Record<string, string | T>` instead of flagging a circular reference error.  This is self-evidently a valid and well-defined type and any arguments to the contrary are fundamentally incorrect.

The equivalent type in Flow works exactly as expected: https://flow.org/try/#0C4TwDgpgBAKlC8UDeBtAzsATgSwHYHMBdALigxwKgB9YBfAKHoGMB7XDKAMxZdLkST0oUAIalBw4QCNSAchGyANEMlNxKyVAAmcgMxKNUBsIYNmbDlJGY+CZCrH3NMqPIOa1Tzdr3vvEUgBGZU1jI3ozVnZgKCsAL1sBB3VnOQUQ1RTvHVd9DM0AqBRCfPCTCKA

### 🕗 Version & Regression Information

Seems to be any version of TS 4, tested with 4.4.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UBKEDGB7ATgEwDwGdhMBLAOwHMAaKQkiqAH1gD4AoIA
### 💻 Code

```ts
type T = Record<string, string | T>
```

### 🙁 Actual behavior
```
Type alias 'T' circularly references itself.
```
### 🙂 Expected behavior
No errors

**Comment by jcalz** [comment]
Duplicate of #41164.  

Looks like you forgot to fill out the "search terms" section.  This is used to show that you have searched for existing issues before opening a new one and also to allow future potential issue-filers to find your issue before opening theirs.  

As an aside, I'll have to remember to use "any arguments to the contrary are fundamentally incorrect" from now on, as it evidently renders claims unassailable.

**Comment by fatcerberus** [comment]
Workaround:
```ts
type U = { [key: string]: string | U };
```

**Comment by jedwards1211** [comment]
@jcalz I say that because I find this issue so frustrating that I wish to express utter disrespect for any counterarguments in advance

**Comment by jcalz** [comment]
Preemptive disrespect is quite an opening move!

**Comment by fatcerberus** [comment]
The counterargument is not "by design" but "design limitation".  See https://github.com/microsoft/TypeScript/issues/41164#issuecomment-712418462.

**Comment by jedwards1211** [comment]
@jcalz not supporting recursion naturally is also quite a bold design decision :wink:

**Comment by jedwards1211** [comment]
@fatcerberus I'm failing to understand what "generic instantiation is deferred" even means in this case.

For example the following type seems like it would have problems related to generic instantiation, yet it works:

```ts
type Stuff<T> = {[x: string]: T | Stuff<T>}

const foo: Stuff<number> = {
  a: {
    b: {d: 2}
  }
}
```

Whatever the supposed design limitations are, the observed behavior from a user perspective seems so illogical I feel extremely skeptical of the reasoning behind the design limitations.

**Comment by jedwards1211** [comment]
closing as duplicate
