### ISSUE TITLE
Performance issue with chained intersections and a fluent api with key mapping

### ISSUE THREAD

**Issue by Feirell** [microsoft/TypeScript#46840]
# Bug Report

### 🔎 Search Terms

performance recursive key

Remark: Had not that much time looking into other issues, just wanted to create this issue, will have a look after work today.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about performance issues about intersections

Sadly the new optimizations in the 4.5-beta did not fix this.

### ⏯ Playground Link

**WARNING: THE TAB FOR THE FOLLOWING LINK WILL FREEZE**
[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAysBOBpCIDOAeA8lCAPYEAdgCapQDeAvgHxQC8UAovvAIYDGw6A1igPYAzKJgA0UVAgCWhAObUA3AChFoSFAByrALYQMAQRz4ipCpTEAhQwRJkqtBnCQp9tAD6wEyNOnMKV4aAApPmkIYnQDPGsTKgsrY1saeigABUl2bgioADIoczFNHX0Laj9lPDA+eGAoVWgANVYAGwBXXQBZVjB0ACV2gu1deJsPJ28+0uTyRShZqABtLyhpDUHUAF0ALig+xZR1xUpy3Erq5cICeAEOaB6IGUkJCHgwzrBIeHQASUJJYElmsMYmYdu0gYlaNM5stiNtHF4MBMlNDiBBICQiOxJLptoVdN9fv9mmIJvN1iIZnMBIR2NsABSseAybZ8ABGACsIJwAJT0WisQggQ7HU41dhNVioMhpSBNUIEv4Aprg0wksFRBKmKZJKFzMAtVly9hQeBaACE2z6SkpszA8EkADdWAQoFouh9koQIAB3KBvdDw5y9drUEn3R6XV7u54KolNNWlOnc63Ql4PJ7wN4fb6oi6SATY+AqiT22QU6HQnpfAAiaOM0hkKrxGB+iuJoNDNorWbCABUAtQ6V3oZJYVAvrn-gXnuWK7NUejiA3MIRLTW6yQG2TZ3PqbSoAymdtGq0Ol10MFQuFW3GEyT14uG9ReXRaD3iP3IF3ebq5-mD3UggwlAZoMAARCWDZgdyw5zrUAAW8B8L6Xq+ow8BIfAdIAOQAMIClAhB8DUaYRs8rrRkWfCEFArCEdR4hSLIUBOqeAB02HJsocFQAA9LxUC9pg1bYKwxDEFATR8HwYBQOw8FctwsGzMA8GPGxbrvM8bGoBAwB0qOtFkAKIBiL+PEwtshmSrRgo7hZC7GJi2KoNsjmbrIK72Txe7bHuRm2UKPGUFxym1AEGg+n0yTRbk5ALEsKwTkQU6FlsfrRh+EWUCmcEvMALTwDRqmPAFJkBTKEByl6sZKgUUUhsicxHEcyiouKjLQHUOxohK7AQJ+0AMCZ1oVFUNTdXcGLwJV1UQCkSH9VK1bOnRDDmQIbA6BO2yEC0Wiss8TWzKgkhaC0Er-NRvZnRAu37Yd8C5SpbACAW+53GAfUDQEx2SawIB8C0wCWr1NyDc9hiimEegyClK3AKwoNfeDv3cXMakyPBcpYwQY6fd9g1kn97B8FJLz42D-VE+sSite1EovHJ1ESLRnCSNR9JsdzjIyK5Jlktyr4jSK43M4QrPsC8zoQFNqIzZIsqhMkSZ8hQ6OzPlhU0ahqSK1V8py88s2hAtfBLagCOsIOMFhfxdsCb2XwADKMDADsaxWbGkRmPZYWF0LYf8TS6DAZ1ffm2LENh3lwfM2ESoDwPYeSAdzHS5CJ0DIMUMHuiUCFfJp3OeeoBpXR0jUr5s1dhCV9yME8bbPHe+GvuUUOFlzEHkgh+0fCok0qAx8XCw9yHqBh1oEfTtHYjYZj2OSLjYQx1A2Gk+Tq+p13swZ6XU8z1HYiLzj8F42Im9VGEhevqP0IcLXGf33BCACqdtfNEbbCGndtS96HcOcpZ6x13hjZeS9cauSgKfCBF8X5zivvAaBSCwgIKgCFMKzc4Kt3TJcP2ndd7jwgOoai-clyz3aM8OGc9R7xzzuQqqw8d6733gAxhQ9tjkCIoQchkcb632oOgx+HM648L4bPRucFsFzlwWRTMHdR7EIABLND4FQpkq9QEVnoewgeTCU7aOhGwvu+jOEUHgmo1ABcXxCLAQ-dm1E6SWKkqgKRc4ZFex9vgxRYDiG4TJtfYgGiaEjzAbo0xg9mFGPTuQBhZjoHkFQcQGxRd7FzBEU45J7iKyeOhPbHi-FBJ6AAOLu0KbxT20I5Hty0v7PxiM+aH2AVHMJu945Z2TiwruGdOk5ziawPmqS77pJUoMsumlK5q0yXXYADcsFVLmDUnxdTCFdyDoMjhw8YmzHoeM5p-C57r1gSvI5G9AkU0MaPfe+ygGHJPhAs+F9mZbxSbY4Rji67mVGbUNgEtFTUS-k5H+IdtiNMnnckB6DoQnPPtA2F8CfnQiQSgi5aCfmYKbos2YyzngEKUY00hvCB6HJCVouhGyZBbKuWAm5VKElcPESS2ewy7GjJmXSJlFCo45OhHkpZ3i8W+KIY01RUkyW0PCZS6l3SLJ0q2VwlxfBrGCI+U-JVbiFlhVxQo1ZBLBkBNeRKtpXc9n0qiTS1hAzzVMK4ck1larRF0myVqipDsoD1EYMor4uFXblLgvbbVgrdUfDWRZbCDoIBqXFIA6eLTyVSrfm9dIlqelxNeu9Lhkbo0TwdT87N6QJ7lzAFM6uHK5m8rmPynFwb8V+ILTG6lOyx4Nongc2ea8F6PLgVo9eyTU1yvIK22NR8wgPKxk8sdLygmqp+Ry75oy37-M-k0b+rBf7bGHRCuN9zoXgInXA+F3bTnNp4ii7YyT0GYukdiqAOq61EOHUSiRUdjXNvjsOmVzaM6foZRQLlhy83ss+ZyshzKeWupwbW4V6zh1ivUdQhN7SI1RsLRAL91yh2ocbX+8gGqgPpI5Rqytsxq13ug3q+t2GQ6GqCW+ilv6LWyp4j+6j6HcP2tncBp+LqsW3vvTB8NqB+pehNRZeY6DiHPvA68RDZy87wbfevPOtGKb0Z+ZS6T3LZOaPk4MxTcnO2NNUzp0Jp7u5PrA9p4Jhn55wbUUplDOaIAmZs7p7Co9mNwUPHzd5c6QO801U3OmiggA)

I put this code example in an external repository for better inspection:
https://github.com/Feirell/ts-key-performance-issue

### 💻 Code

Sorry I tried to break it down as much as possible, but I need to continue with work.
I will try to break it down further after work today.

I also created a repo for it:
https://github.com/Feirell/ts-key-performance-issue

```ts
type StrKeys<O extends {}> = Extract<keyof O, string>;

type Names<A extends {}, B extends {}> = StrKeys<A> | StrKeys<B>;
type Joined<A extends {}, B extends {}> = Pick<A & B, Names<A, B>>;


export type ValuesMap<RM, Names extends StrKeys<RM>> = {
    [Key in Names]: RM[Key]
}

export interface RegisteredMapper<Initial extends {}, RM extends {}> {
    id: StrKeys<RM>;
    dependencies: Names<Initial, RM>[],
    fnc: (arg: object) => any
}

export class Pipeline<Initial extends {}, RM extends {} = {}> {
    public rm!: RM;

    private mapper = new Map<StrKeys<RM>, RegisteredMapper<Initial, RM>>();

    registerMapper<Identifier extends string,
        RIDepending extends Names<Initial, RM>,
        MappedType>(
        id: Identifier,
        dependingOn: RIDepending[],
        fnc: (arg: ValuesMap<Joined<Initial, RM>, RIDepending>) => MappedType
    ) {
        if (typeof id != "string")
            throw new Error('Can not register mapper on a non string value.');

        // TODO add loop check
        this.mapper.set(id as any, {
            id: id as any,
            dependencies: dependingOn,
            fnc: fnc as any
        });

        type NewRM = RM & { [Key in Identifier]: MappedType };

        return this as any as Pipeline<Initial, NewRM>;
    }
}

declare type ReplaceType = any;

export type RenderPipelineProcessData = {
    frameId: number;
    simulationTime: number;

    traffic: ReplaceType;
    layout: ReplaceType;

    exportedAgentData: ReplaceType;

    highlighted: ReplaceType[];
    colored: ReplaceType[];
}

declare const action: (...args: any[]) => any;

export const createRenderPipeline = () => {

    return new Pipeline<RenderPipelineProcessData>()

        //
        // TILES
        //

        .registerMapper(
            'tilesSimplified',
            ['layout'],
            ({layout: {tiles}}) =>
                tiles.map(t => action(t))
        )

        .registerMapper(
            'tileModels',
            ['tilesSimplified', 'highlighted', 'colored'],
            ({tilesSimplified, highlighted, colored}) =>
                action({
                    transitionalRenderable: tilesSimplified,
                    highlights: highlighted,
                    colors: colored
                })
        )

        .registerMapper(
            'tileNonModifiedMerged',
            ['tileModels'],
            ({tileModels: {nonModified}}) =>
                action(nonModified)
        )

        .registerMapper(
            'tileHaloMerged',
            ['tileModels'],
            ({tileModels: {halos}}) =>
                action(halos)
        )

        .registerMapper(
            'tileColoredMerged',
            ['tileModels'],
            ({tileModels: {colored}}) =>
                action(colored)
        )

        //
        // TAGS
        //

        .registerMapper(
            'tagsSimplified',
            ['layout'],
            ({layout: {tags}}) =>
                tags.map(t => action(t))
        )

        .registerMapper(
            'tagModels',
            ['tagsSimplified', 'highlighted', 'colored'],
            ({tagsSimplified, highlighted, colored}) =>
                action({
                    transitionalRenderable: tagsSimplified,
                    highlights: highlighted,
                    colors: colored
                })
        )

        .registerMapper(
            'tagNonModifiedMerged',
            ['tagModels'],
            ({tagModels: {nonModified}}) =>
                action(nonModified)
        )

        .registerMapper(
            'tagHaloMerged',
            ['tagModels'],
            ({tagModels: {halos}}) =>
                action(halos)
        )

        .registerMapper(
            'tagColoredMerged',
            ['tagModels'],
            ({tagModels: {colored}}) =>
                action(colored)
        )

        //
        // VEHICLES
        //

        .registerMapper(
            'vehiclesSimplified',
            ['traffic'],
            ({traffic: {vehicles}}) =>
                vehicles.map(t => action(t))
        )

        .registerMapper(
            'vehicleModels',
            ['vehiclesSimplified', 'highlighted', 'colored'],
            ({vehiclesSimplified, highlighted, colored}) =>
                action({
                    transitionalRenderable: vehiclesSimplified,
                    highlights: highlighted,
                    colors: colored
                })
        )

        .registerMapper(
            'vehicleNonModifiedMerged',
            ['vehicleModels'],
            ({vehicleModels: {nonModified}}) =>
                action(nonModified)
        )

        .registerMapper(
            'vehicleHaloMerged',
            ['vehicleModels'],
            ({vehicleModels: {halos}}) =>
                action(halos)
        )

        .registerMapper(
            'vehicleColoredMerged',
            ['vehicleModels'],
            ({vehicleModels: {colored}}) =>
                action(colored)
        )


        .registerMapper(
            'scene',
            [
                'tileNonModifiedMerged', 'tileHaloMerged', 'tileColoredMerged',
                'tagNonModifiedMerged', 'tagHaloMerged', 'tagColoredMerged',
                'vehicleNonModifiedMerged', 'vehicleHaloMerged', 'vehicleColoredMerged'
            ],
            (args) =>
                action(args)
        );
}
```

### 🙁 Actual behavior

The TypeScript build, and sadly the language server as well, need around 50s for the `Check` step.

Have a look at the diagnostic file:
https://github.com/Feirell/ts-key-performance-issue/blob/master/diagnostic.txt

I have also generated the required trace files, as suggested here: https://github.com/microsoft/TypeScript/wiki/Performance#providing-performance-traces
You can find those in this repository as well but be awere that the `cpu.profile` will freeze the profiler several times before it has fully parsed the file (47MB JSON takes some time).

### 🙂 Expected behavior

Either the `Check` for this file should abort alot faster or it should be able to resolve the types faster.

I belive that the culprit is the resolving of the `ValuesMap` for the mapper argument. Since this resolving is basing on the intersection type of several intersection beforehand.

I am open to suggestions as how to avoid intersections altogether. It would be really nice to have some way to force a new fresh type which is the previous object plus a new field to replace `type NewRM = RM & { [Key in Identifier]: MappedType };`

**Comment by MartinJohns** [comment]
Possibly related: #46783

**Comment by Feirell** [comment]
@MartinJohns Thank you very much! Yes that seems like the exact same issue! Sad that I had not found this earlier. Should I close this issue in favor of the other one?

**Comment by Feirell** [comment]
https://github.com/microsoft/TypeScript/issues/46783#issuecomment-968089325 resolves the issue for me I will close this issue, since the integral problem is discussed in the linked issue. Thank you @MartinJohns and @ahejlsberg for this!
