### ISSUE TITLE
Change to template literals is breaking and undocumented

### ISSUE THREAD

**Issue by afrieder** [microsoft/TypeScript#46844]
# Bug Report

### 🔎 Search Terms

Template literals, moment

### 🕗 Version & Regression Information

This began happening with the release of https://github.com/microsoft/TypeScript/pull/45304 when targeting ES5.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?target=1&ts=4.6.0-dev.20211117#code/MYewdgzgLgBBIFsCmAxArmYUCW4YF4YAKASgID4YBvAXwG4AoB0SEAGyQDo2QBzIgAYBlREhgAzDFlxgAXDAAkVeMnSYc4UjQEk6QA)

### 💻 Code

```ts
import * as moment from 'moment';
window.alert(`Moment: ${moment()}`);
```

### 🙁 Actual behavior

In 4.5.2+, this compiles to `"Moment: ".concat(moment())` which evaluates to `"Moment: Wed Nov 17..."`

### 🙂 Expected behavior

In previous versions of Typescript, this compiled to `"Moment: " + moment()` which resolves to `"Moment: 1637....`.

This change is breaking and was not documented in the release notes for 4.5.

<img width="442" alt="Screen Shot 2021-11-17 at 3 54 13 PM" src="https://user-images.githubusercontent.com/8473729/142300896-22f1e183-2ac4-4d67-900c-999707e36a89.png">

**Comment by RyanCavanaugh** [comment]
We don't usually treat removing spec violations as breaking changes, but we can add it to the notes regardless.

**Comment by DanielRosenwasser** [comment]
It's not in the wiki and on the blog. Thanks!

**Comment by DanielRosenwasser** [comment]
(@orta don't know if the website needs updates)
