### ISSUE TITLE
TypeScript version incorrectly lists Intl.DateTimeFormat Parameter Options

### ISSUE THREAD

**Issue by Guergeiro** [microsoft/TypeScript#46852]
# Bug Report

As per [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#parameters) the option `fractionalSecondDigits` should accept `0`, `1`, `2`, `3` which is not being respected by the latest TypeScript version.

### 🔎 Search Terms

DateTimeFormat
Intl.DateTimeFormat
fractionalSecondDigits
options

### 🕗 Version & Regression Information

- This changed between versions `4.4.4` and `4.5.2`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211118#code/MYewdgzgLgBAJgQygUxgXhmZB3GARJZACgEoBuAKFElmgCd15CA6KEAGRGAQBtkCUAZSh0AlmADmRAETIwAWgCqg6QBoYAbwowYAMzoJgUUeF6Dk1OHlETRUCAC4YAZhgB6NzAAqAC1EQYf0wQWF4eEGxkOAoAX3IKKnAIED5mcKl6EiA)

### 💻 Code

```ts
const date = new Date();
const str = date.toLocaleDateString("en-US", {
  fractionalSecondDigits: 3 // This is not allowed
});
```

### 🙁 Actual behavior

Doesn't work.

### 🙂 Expected behavior

Allow this behaviour.

**Comment by ilogico** [comment]
I had the same issue, the solution is to have ES2021 or ES2021.Intl in your lib setting.
See https://github.com/microsoft/TypeScript/issues/42944

**Comment by Guergeiro** [comment]
> I had the same issue, the solution is to have ES2021 or ES2021.Intl in your lib setting. See #42944

Makes sense. Thanks @ilogico!

@RyanCavanaugh you can close this issue if needed 😄
