### ISSUE TITLE
Bug on declaring namespace . 

### ISSUE THREAD

**Issue by hasnath1** [microsoft/TypeScript#46851]
I wrote this code but it does not work . Throws duplicate identifiers . 
`
declare namespace global {
  let hello: string;
}

global.hello = "this will fail !";
console.log(global.hello);
`
But If I just import any kind of module . It works . Even if I don't use it . 
`
import {} from "express";

declare namespace global {
  let hello: string;
}

global.hello = "This is work";
console.log(global.hello);
`

Device Specification : 
Nodejs -> v16.13.0
ubuntu -> 20.04
tsc aka typescript -> 4.4.4

I don't know if it is a bug . If not please , explain why this happens . I am not a typescript expert . 

Updated . 
Here is the tsconfig.json
`
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}

`

**Comment by MartinJohns** [comment]
**Not a bug.**

---

1. Please respect the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md). This makes it easier for the TypeScript team to handle issues.
2. When your file has no `import` or `export` statement it is considered a script-file with a shared global scope, not a module. So you declare a `hello` variable twice. See the [documentation on modules](https://www.typescriptlang.org/docs/handbook/modules.html).

**Comment by hasnath1** [comment]
Thanks for explaining
