### ISSUE TITLE
Bug in rest of arguments

### ISSUE THREAD

**Issue by OlegDokuka** [Microsoft/TypeScript#4685]
Hi guys, let consider the next example of code, where rest of args is used.

``` ts
public static something(clazz: Class, ...args: any[]) {
            return new (clazz.bind.apply(clazz, args))();
}

```

It looks pretty good and what we have got in compiled js file

``` js
            someclass.newInstance = function (clazz) {
                var args = [];
                for (var _i = 1; _i < arguments.length; _i++) {
                    args[_i - 1] = arguments[_i];
                }
                return new (clazz.bind.apply(clazz, args))();
            };
```

And what I have found - there are no way to pass arguments, that has already been collected, in for-loop for example 

``` ts
resolvedValues = someArray
                .map((td) => this.resolveDependency(td));
BeanUtils.newInstance(clazz, resolvedValues); 
```

As you have already seen the code

``` js
 for (var _i = 1; _i < arguments.length; _i++) {
                    args[_i - 1] = arguments[_i];
                }
```

values has been packed into array and in the end we got 
```
Array
    --> Array
          -->0:val1
          -->1:val2
```

But what we really need is 

```
Array
          -->0:val1
          -->1:val2
```

In another language, for example java, when we  try to pass an array in the end, in function, we got this
```
Array
          -->0:val1
          -->1:val2
```

and not this

```
Array
    --> Array
          -->0:val1
          -->1:val2
```

How we can fix it - just add little part of args checking:

```
if(arguments.length===1&&arguments[0] instanceof Array) {//for example just 1 args that is rest and passed argument is array
args = arguments[0];
} else{
for (var _i = 0; _i < arguments.length; _i++) {
                    args[_i - 1] = arguments[_i];
                }
}
```

in this case if we want pass rest of arrays just do something like this

```
Someclass.newInstance([a,b,c],[a,b,c],[a,b,c]);
```
if we have just one array as argument we can do something like this

```
Someclass.newInstance([[a,b,c]]);
```

I understand that it is a bit difficult and maybe more complex than replace ...args:any[] to args:any, but in my opinion it had a sense.

Of course we can use power of compiler and check type of argument and depends on it provide different outcomes of events

P.S. I bring my apologies if this issue has already been discussed .

**Comment by SaschaNaz** [comment]
You want [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator):

```typescript
resolvedValues = someArray
                .map((td) => this.resolveDependency(td));
BeanUtils.newInstance(clazz, ...resolvedValues); // Note the three dots
```

**Comment by OlegDokuka** [comment]
Wow))) I have not known about this feature yet)))! Thank you, @SaschaNaz,  a lot!!!
