### ISSUE TITLE
Suggest filename as an autocomplete token 

### ISSUE THREAD

**Issue by mohsen1** [microsoft/TypeScript#46857]
# Suggestion

<img width="790" alt="Screen Shot 2021-11-18 at 10 26 43 AM" src="https://user-images.githubusercontent.com/543633/142474894-1da8830e-1968-4224-9fe4-d4344dcc8398.png">

I am typing the filename again, help me not do it! 

## 🔍 Search Terms

Autocomplete
Suggestion
Keyword 

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by tadhgmister** [comment]
What is the suggestion? Are you wanting to import stuff from the other file? why aren't you typing `import {} from ''` then auto-complete in the import filename and once that is filled in auto complete in the import members.

**Comment by RyanCavanaugh** [comment]
My interpretation (maybe wrong) is that it's very common to e.g. create MyCoolButton.ts, then write `const MyCoolButton = ...`.

My trepidation is that for filenames that aren't semantic in the domain (`index`, `utils`, etc), this might be very annoying.

**Comment by mdbetancourt** [comment]
> My interpretation (maybe wrong) is that it's very common to e.g. create MyCoolButton.ts, then write const MyCoolButton = ..., so having autocomplete there would be neat.

yes, he is trying to get autocompletation for react components which it's common to have the same name as the file, but i think this is not needed.

@mohsen1 you could use a vscode snippet for it
```json
{
  "Component": {
    "prefix": ["comp"],
    "body": ["const ${TM_FILENAME/(.*)\\..+$/$1/} = "],
    "description": "Create a component."
  }
}
```

**Comment by tadhgmister** [comment]
Not everyone using typescript uses vscode so a snippet may not always be applicable.

Also use the `TM_FILENAME_BASE` variable instead of trimming the file extension yourself. [available variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables)

**Comment by mdbetancourt** [comment]
> Not everyone using typescript uses vscode so a snippet may not always be applicable.
providing autocomplete in vars declaration feels weird, also i could say not everyone using react uses typescript so is better to provide this feature to those users too and almost any editor support snippets though
