### ISSUE TITLE
Unable to rename parameter properties

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#4686]
Rename `parent` to `parent_`.

```ts
class Foo {
  constructor(private parent) {
    parent
  }
}
```

expected

```ts
class Foo {
  constructor(private parent_) {
    parent_
  }
}
```

actual

```ts
class Foo {
  constructor(private parent_) {
    parent
  }
}
```

Visual Studio 2013

**Comment by danquirk** [comment]
Repros in 2015 too.

**Comment by drake7707** [comment]
And on the playground as well.

Note that it does work if you remove the private.

It also doesn't highlight both as reference to the same variable (which is probably related)

**Comment by DanielRosenwasser** [comment]
This is just a language service issue, anything that uses it will have a problem.
