### ISSUE TITLE
Module: ES Next, Target: ES Nextm noEmitHelpers, experimental decorators

### ISSUE THREAD

**Issue by fis-cz** [microsoft/TypeScript#46868]
# Suggestion

Hello,

it would be nice if it is possible to have a possibility to use TypeScript with ESNext modules without need of any additional tools in the build chain.

Currently, it is possible, but with just some specific settings and assumptions (see bellow)

###

## 🔍 ESNext, ModuleResolution, .js extension, tslib path, No-build-chain

Searched sentences:

## ✅ TypeScript Target ESNext tslib

My suggestion meets these guidelines:

## ⭐ Suggestion

####When it currently works well (but it is not comfortable):

a) Every import with executable code (so this is not true just for files with type definitions, i.e. types and interfaces) must end with a ".js" extension, otherwise the transpiled file can't be loaded by browser directly. This is bit impractical and it would be great if the ".js" is added automatically by transpiler whenever it is needed.

b)  noEmitHelpers must be set to false, importHelpers must be set to false

c) no additional modules from node_modules folder are imported.

####Current behavior with another than described settingsr:

a) When no .js is added to every import manually, with executable code, browsers are not able to load it. It is bit impractical to add the .js to every import to every file in the project as it is not needed in any other case (node, buildchain with dep resolver such as webpack).

b) When noEmitHelpers and importHelpers is set to "true", every file where import is needed is transpiled with
````import { __helper } from "tslib". ```. Again, this is useless without a .js extension. Moreover, at least a relative path should be added 
 (i.e. "./") to the file as browser can't resolve it. 

It would be fine if this works out of the box so we can use just TypeScript without need of any additional tooling in the chain.

a) TypeScript can add .js extension automatically to transpiled output (or basically any extension configured in the tsconfig.json file - i.e. ".mjs")

b) TypeScript can add configurable path to all modules resolved in any level of node_modules folder, including the path to the module (so fthe fnal path wil look like <configurable_path>/tslib/tslib.js) and we can manually copy - resolve :) - these modules to the folder where browser can resolve it
OR 
at it at least adds relative path to the module located in the node_modules folder from the rootDir (or location of the tsconfig.json)/

## 💻 Use Cases

Transpile TS modules directly to code loadable by browsers without need of any additional tooling.

**Comment by fatcerberus** [comment]
I can tell you right now that automatically adding extensions to imports has been discussed to death in the past and is not likely to ever happen.

**Comment by RyanCavanaugh** [comment]
We don't modify paths on emit. See #16577
