### ISSUE TITLE
Support Intl.ListFormat

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript#46866]
Introduce types for `Intl.ListFormat`. The code below shall not generate errors:
```javascript
new Intl.ListFormat('bg', {type: 'conjunction'}).format(['a','b','c'])
```

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
