### ISSUE TITLE
Broken `keyof` inference

### ISSUE THREAD

**Issue by DScheglov** [microsoft/TypeScript#46870]
# Bug Report

### 🔎 Search Terms

`keyof`

### 🕗 Version & Regression Information
- This changed between versions 4.4.4 and 4.5.2

Also the bug was reproduced in the Playground with version 4.5.0-beta

### ⏯ Playground Link

[Playground (v4.5.0-beta)](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocmATzCTgGUkYGYUYkAeBgPjgF44Ab3JwxcABQA3FABsArkgBcjAJQqpEYABMK4yUW3y0SKColp5UIgDsWbDioaqBfZxq27yAXwpVa9KzsSACyKDYoAOam3HyCIvrR9sES6ox64gDOzEGOjDkOXLwZYpnyAEaZaFDA5UgSssCZHDam5jIKymqucJo6aak9fV6+lDR0jIUAKgHcIXGMIXBIAB4t2pmTwWER0VCcwDaYpox8APyMcCqtUqZ+4-QA0kjUAPKYM3Tcy2tINhvCbwAGjgUwWCXEAG0AApwQ5wADWLwgmEYAF0nDC0T91pspnALrDrkhblAKN5IUjqCj0X5VpBYHBMPIbBhgBAbHB5NlcqFwlEYrwJEI4EleSDsskOBKKlUanU4N4nIUdgL9rw0pCGCCmFKijxsRCxGgOc04JCQa01tjBMh0DAAHTcpDIIwmKASaTXeQgOpQFz8PhSOAAajgAEYQQAGVQlRDER3OgCimGOGE9Ab4ZUq1Vq9UGgbgVpgqVUIMhaNjlH0RBgVk5kLFhVSEoKwTR5Mo9OgWBZbI5XJ5Kv5ewAYjgQABhDkcNacSc4v4AoTAuAAOUX-02zzeH1mk51w92MXC1B454konEJrsqxgKjtGAd09vc8nPCBV9KR7Va5QIC6NdyBcI04BvM0MBWFRoWANAEXnEEd3eT4uAPLYOFVPZOFPc8FkfRNshfWcSxvYiqxrZh60HJBeUwwVpn3SE1zRC9IMhZpthHUw-wAytySAA)

### 💻 Code

```ts
import React from "react";

type SetState<S> = {
    (value: S): void;
    (reducer: (currentState: S) => S): void;
};

type StateManager<S> = {
    getState(): S;
    setState: SetState<S>;
    subscribe(listener: (value: S) => void): () => void;
};

type StateType<SM> = SM extends StateManager<infer S> ? S : never;

type KeyOfType<S extends {}, T> = {
    [P in keyof S]: S[P] extends T ? P : never;
}[keyof S];

export function useStateManager<S>({ getState, setState, subscribe }: StateManager<S>): [S, SetState<S>] {
    const [, next] = React.useReducer((v: number) => v + 1, 0);
    React.useEffect(() => subscribe(() => next()), []);

    return [getState(), setState];
}

export function useStateManagerFromContext<C extends {}, N extends KeyOfType<C, StateManager<any>>>(
    context: React.Context<C>,
    stateManagerName: N
) {
    const ctx: Pick<C, KeyOfType<C, StateManager<any>>> = React.useContext(context);
    return useStateManager<StateType<C[N]>>(ctx[stateManagerName]);
}
```

### 🙁 Actual behavior

The Error reported and compilation failed:
```sh
Errors in code
Argument of type 'C[N]' is not assignable to parameter of type 'StateManager<StateType<C[N]>>'.
  Type 'C[KeyOfType<C, StateManager<any>>]' is not assignable to type 'StateManager<StateType<C[N]>>'.
    Type 'C[C[keyof C] extends StateManager<any> ? keyof C : never]' is not assignable to type 'StateManager<StateType<C[N]>>'.
      Type 'C[keyof C]' is not assignable to type 'StateManager<StateType<C[N]>>'.
        Type 'C[string] | C[number] | C[symbol]' is not assignable to type 'StateManager<StateType<C[N]>>'.
          Type 'C[string]' is not assignable to type 'StateManager<StateType<C[N]>>'.
```

### 🙂 Expected behavior

No error reported as it works before, as instance in v4.4.4:

[Playground (v4.4.4)](https://www.typescriptlang.org/play?ts=4.4.4#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocmATzCTgGUkYGYUYkAeBgPjgF44Ab3JwxcABQA3FABsArkgBcjAJQqpEYABMK4yUW3y0SKColp5UIgDsWbDioaqBfZxq27yAXwpVa9KzsSACyKDYoAOam3HyCIvrR9sES6ox64gDOzEGOjDkOXLwZYpnyAEaZaFDA5UgSssCZHDam5jIKymqucJo6aak9fV6+lDR0jIUAKgHcIXGMIXBIAB4t2pmTwWER0VCcwDaYpox8APyMcCqtUqZ+4-QA0kjUAPKYM3Tcy2tINhvCbwAGjgUwWCXEAG0AApwQ5wADWLwgmEYAF0nDC0T91pspnALrDrkhblAKN5IUjqCj0X5VpBYHBMPIbBhgBAbHB5NlcqFwlEYrwJEI4EleSDsskOBKKlUanU4N4nIUdgL9rw0pCGCCmFKijxsRCxGgOc04JCQa01tjBMh0DAAHTcpDIIwmKASaTXeQgOpQFz8PhSOAAajgAEYQQAGVQlRDER3OgCimGOGE9Ab4ZUq1Vq9UGgbgVpgqVUIMhaNjlH0RBgVk5kLFhVSEoKwTR5Mo9OgWBZbI5XJ5Kv5ewAYjgQABhDkcNacSc4v4AoTAuAAOUX-02zzeH1mk51w92MXC1B454konEJrsqxgKjtGAd09vc8nPCBV9KR7Va5QIC6NdyBcI04BvM0MBWFRoWANAEXnEEd3eT4uAPLYOFVPZOFPc8FkfRNshfWcSxvYiqxrZh60HJBeUwwVpn3SE1zRC9IMhZpthHUw-wAytySAA)

**Comment by yseymour** [comment]
[Minimal playground repro](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/C4TwDgpgBA0hIGcDqALCAnCAeAKgGigFUA+KAXigG8BtGKASwDsoBreAewDMocBdALh61eUCAA9gERgBMERKAH5YUQYwgA3DAF9qbEFx68A3AChQkKAFkAhmEjTcoiVNlRGAVwC2AIwykKlFAA+oI4UFom0hAAxgA21phQnO6M0cD07Myc7Oy4BHTikjJycIioGNj4bl6+6MTEABQsgjAAlII2dhAOOMLEpkA)

**Comment by yseymour** [comment]
I think this is the same as #46855.
