### ISSUE TITLE
Typescript 4.5 + yarn pnp issues

### ISSUE THREAD

**Issue by billyvg** [microsoft/TypeScript#46874]
# Bug Report

### 🔎 Search Terms

yarn
yarn3
pnp
berry
cannot find module

### 🕗 Version & Regression Information

4.5.x 

- This changed between versions ___4.4___ and __4.5_____

### ⏯ Playground Link
N/A, view repo below

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
Minimal reproducible repo here: https://github.com/billyvg/yarn-pnp-ts-4.5

```
git clone
yarn
yarn tsc
```

### 🙁 Actual behavior
It fails to build: https://github.com/billyvg/yarn-pnp-ts-4.5/runs/4268834214?check_suite_focus=true#step:5:4

```
migrations/20210209131202_initial-schema.ts:1:22 - error TS2307: Cannot find module 'knex' or its corresponding type declarations.

1 import { Knex } from 'knex';
```

### 🙂 Expected behavior

It should build successful. If I change [`nodeLinker`](https://github.com/billyvg/yarn-pnp-ts-4.5/blob/main/.yarnrc.yml#L1) to `node-modules` (instead of `pnp`), `typescript@4.5` works fine. Likewise, downgrading to `typescript@4.4` will also work with PnP.

**Comment by merceyz** [comment]
See https://github.com/yarnpkg/berry/issues/3722 (specifically https://github.com/yarnpkg/berry/issues/3722#issuecomment-974634888)

**Comment by billyvg** [comment]
Thanks, closing as this is a `yarn` issue.
