### ISSUE TITLE
Include a compiler option to omit export statements in Javascript output.

### ISSUE THREAD

**Issue by bdcoder2** [microsoft/TypeScript#46876]
I am very green with regard to Typescript (as I have only started converting our Javascript codebase), but have been "bitten" by the same problem described in [Issue 41513](https://github.com/microsoft/TypeScript/issues/41513).

I initially posted a similar [question on StackOverflow](https://stackoverflow.com/questions/69775362/typescript-prevent-from-inserting-magic-code-how), and found my own (not-very-elegant) solution.

What I (and apparently others) would really like to see is a compiler switch such as:  

`tsc --noGeneratedExports`

Regardless of the compiler option / switch name, the effect would be that tsc would NOT emit statements such as the following (which appear at the top of a Javascript file):

`Object.defineProperty(exports, "__esModule", { value: true });`

... or the following, which appear at the end of a Javascript file:

`export {};`

In both cases above, when trying to load the resulting Javascript **LOCALLY** (from the file system) -- the browser will throw an exception.

Having a compiler option that outputs Javascript that can be loaded into a browser locally would eliminate the need for a module bundler and/or local web server.

Thanks in advance for your consideration.

**Comment by MartinJohns** [comment]
- You forgot to fill out the issue template.
- This is a duplicate of #41567.

**Comment by bdcoder2** [comment]
Apologies - but if it re-opens the issue, It would REALLY help!

**Comment by RyanCavanaugh** [comment]
Duplicate #39446
