### ISSUE TITLE
Allowing duplicated identifiers on importing, but not duplicated declaration type.

### ISSUE THREAD

**Issue by namse** [microsoft/TypeScript#46889]
# Suggestion

## 🔍 Search Terms

- `Duplicate Identifer`
- `Typescript data type and instance name duplicate`
- `React Typescript Component and type duplicate identifier`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Typescript allows duplicated identifier declarations in a single ts file, if duplicated identifiers have different declaration types.
But it doesn't work to import identifiers from multiple files even though you know each imported identifiers have different declaration types.
Let's allow import statement duplicate identifiers, but check whether duplicated identifiers have a same declaration or not.

## 📃 Motivating Example

```ts
// Page.ts
type Page = {
  id: string;
  ...
}

const Page: React.Component ... = () => { ... }

export default Page;  // Yes, this works.
```

But sometime we put types in one file, like `types.ts`, right?

```ts
// types.ts
export type Page = {
  id: string;
  ...
}

// Page.tsx
export const Page: React.Component<...> = (...) => { ... }

// App.tsx
import { Page } from './types.ts'; //<--- Duplicate identifier 'Page'. ts(2300)
import { Page } from './Page.tsx'; //<--- Duplicate identifier 'Page'. ts(2300)

const App = () => {
  const page: Page = {
    id: 'hello-world',
  };
  return <Page page={page}>;
}
```

Importing same name identifiers makes error 'Duplicate identifier', but with this suggestion, it allows it.

### What workarounds are you using in the meantime?

- Importing types using import * as types from '../types' – I find that having types. makes it a bit messy, especially for more complicated components.
- Importing just the conflicted types with an alias (import { Bookshelf as BookshelfType } from '../types') – This works in some places, but when I have a type I called BookshelfType that I want to import then it becomes a problem.
- Giving all components the suffix Component or View (e.g. BookshelfComponent or BookshelfView)
- Giving only problematic components the suffix Component or View – Component names would then be inconsistent.

Reference
- https://www.reddit.com/r/reactjs/comments/kto2ll/conventions_for_react_component_naming_when/
- https://www.reddit.com/r/reactjs/comments/hxseh3/naming_convention_for_data_type_vs_component/

### What do you want to use this for?
Removing meaningless, long suffix like `Data`, `Component`, `Info`, etc to avoid identifier duplication.

### What shortcomings exist with current approaches?
System should let programmer know that identifier they imported has same declaration types. I think it would be enough with new error message like `Duplicate declaration`.

**Comment by tadhgmister** [comment]
I can't imagine this being useful when both are regular import statements but at the same time I'm quite surprised this doesn't work:

```ts
import type { Page } from "./types" // explicitly only import the type!
import { Page } from "./Page"
```
If `Page.tsx` only exports a value called `Page` typescript is still unhappy about multiple imports even though one is clearly only the type and the other is only a value.

That said, why are you putting your type declarations in a separate file anyway? If the `Page` type is related to the `Page` value then exporting them both in the same file is allowed and works as you'd expect.

**Comment by namse** [comment]
@tadhgmister 
> That said, why are you putting your type declarations in a separate file anyway? If the Page type is related to the Page value then exporting them both in the same file is allowed and works as you'd expect.

I usually separate dependency between component and type. For example, Page component uses Page type, but Page type is not only for Page component. Other logic could use page type without any information of Page component.

The type could be from other package.

**Comment by RyanCavanaugh** [comment]
```ts
import { Page } from './types.ts';
import { Page } from './Page.tsx';
```
This is illegal JavaScript; depending on the import being removed is a really big code smell (Babel et all cannot handle this) and we would prefer people not be relying on this.

```ts
import type { Page } from "./types" // explicitly only import the type!
import { Page } from "./Page"
```
This is not illegal JS *but*:
 * The second `Page` might still bring a long a type (e.g. if it's a class)
 * Both import statements bring in the *namespace* meaning:
```ts
// Page.foo is ambiguous between the export from
// "./types" and the export from "./Page"
const t: Page.foo = ...
```

**Comment by namse** [comment]
Thanks for the clear explanation, I understand well. I didn't know that it is illegal javascript, so it looks violating ts design rule...

**Comment by gomain** [comment]
> ```ts
> import type { Page } from "./types" // explicitly only import the type!
> import { Page } from "./Page"
> ```
>   
> This is not illegal JS but:
> 
> The second Page might still bring along a type (e.g. if it's a class), so this pattern is fragile at best. Changes to "./Page" that seem innocuous could break this file

Had the second import of `Page` brought in a type, then, and only then, should it be a duplicate identifier error. Of course, change in the second source file to also export a type (e.g. changing to Class) would break the import. But this is expected and should be considered _safe_, not _fragile_.

Types and values (i.e. instances) have distinct usage positions. We should be able to do this
```ts
// Page.ts
export type Page = {
  ...
};

export const Page: Page = { ... };
```
and
```ts
// main.ts
import type { Page } from './Page.ts'; // the type
import { Page } from './Page.ts'; // the value

const MyPage: Page = Page;
```

**Comment by StreetStrider** [comment]
Having
```ts
export type Foo = {}
export default function Foo () {}
```
is correct, while importing them via explicit `import`/`import type` is incorrect.

If it is safe to have them both in one file, because one of them is in type position it should be allowed to import them in the same manner.

> Had the second import of Page brought in a type, then, and only then, should it be a duplicate identifier error.

I second this. Current behavior kinda breaks some nice patterns for me. It is much better to have adequate dup names rather than `import type { Foo as $Foo } …` or something like that.

**Comment by Praise-gregor** [comment]
> [@tadhgmister](https://github.com/tadhgmister)
> 
> > That said, why are you putting your type declarations in a separate file anyway? If the Page type is related to the Page value then exporting them both in the same file is allowed and works as you'd expect.
> 
> I usually separate dependency between component and type. For example, Page component uses Page type, but Page type is not only for Page component. Other logic could use page type without any information of Page component.
> 
> The type could be from other package.





https://fragility-unnoticed.github.io/Quxj_mrW1RxGqZuY13nfBAsiLadJFAjinVdr1uL2JVLwXrJ7GlMr/
