### ISSUE TITLE
ts 

### ISSUE THREAD

**Issue by spiritwindy** [microsoft/TypeScript#46882]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Documentation Link

原型链类型

```ts
interface BigInt extends Object {   
    constructor: BigIntConstructor;
    __proto__: this
}
```

**Comment by MartinJohns** [comment]
I have no idea what you're trying to tell or ask.

**Comment by RyanCavanaugh** [comment]
The only thing I get from the translation is ‎"prototype chain type‎"... I also am not sure what's being said here.

Please fill in the template completely.
