### ISSUE TITLE
Introduce option to tell tsc prefer *.d.ts over *.ts

### ISSUE THREAD

**Issue by pauldraper** [microsoft/TypeScript#46880]
Continuing discussion of #14787, allow preferring .d.ts over .ts. This is helpful for packages that include their .ts sources in addition to the .js and .d.ts build products.

----

@kitsonk repeatedly says "use it the right way," but that doesn't make sense.

The .ts files are necessary in order for source maps and declaration maps to work.

example.d.ts
example.d.ts.map
example.js
example.js.map
example.ts

Why is this the "wrong" way to arrange files in the package and what is the "right" way, and why does the TypeScript compiler default to the "wrong" way?

**Comment by RyanCavanaugh** [comment]
Side-by-side compilation, the default/"wrong" way, is the default because otherwise we'd have to just make up a directory name (`outDir`) to emit into.

All the rationale from #10704 still applies here and I'm not sure how this option even helps -- the issue is in downstream consumers of the package, who might not be able to enable this option for whatever reason, so they'd just be completely stuck?

**Comment by pauldraper** [comment]
I guess...it's still not clear to me what the "right way" (to quote #14787) is to produce a TS package.

**Comment by fatcerberus** [comment]
Set an `outDir`.  But I honestly fail to see how this is an issue because, to quote #10704:

> if the two files represent the same module, then the `.ts` is more accurate as it is the source. *if they do not represent the same module, they should not live side by side in the same folder.*

Since these appear to be the `.d.ts` files actually generated from your compilation, I'm not sure I understand why this is an issue at all?  You should get the same results from either, regardless.

**Comment by mdbetancourt** [comment]
> Since these appear to be the .d.ts files actually generated from your compilation, I'm not sure I understand why this is an issue at all? You should get the same results from either, regardless.

not at all, if you use some tools like api extractor to remove `@internals` functions

**Comment by pauldraper** [comment]
> Set an outDir.

That changes the import path for consumers, right?
