### ISSUE TITLE
Add Intl.ListFormat to es2021 lib

### ISSUE THREAD

**Issue by vhfmag** [microsoft/TypeScript#46907]
# Suggestion

## 🔍 Search Terms

- `Intl.ListFormat`
- `Intl`
- `ListFormat`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add `Intl.ListFormat` to es2021 lib types (as per [Finished Proposals](https://github.com/tc39/proposals/blob/master/ecma402/finished-proposals.md)).

Bringing this API to Typescript has been directly suggested before, but didn't follow the issue templates (#46866), and was also mentioned before (https://github.com/microsoft/TypeScript/issues/45646#issuecomment-962430370, https://github.com/microsoft/TypeScript/issues/29129#issuecomment-449608280), but, as I couldn't find any specific active issue where the feature suggestion is being considered, I'm opening this issue.

## 📃 Motivating Example

Code that uses the Intl.ListFormat API should not fail type checking:

```ts
new Intl.ListFormat('bg', {type: 'conjunction'}).format(['a','b','c'])
new Intl.ListFormat('bg', {type: 'disjunction'}).formatToParts(['a','b','c'])
```

## 💻 Use Cases

```ts
new Intl.ListFormat('bg', {type: 'conjunction'}).format(['a','b','c'])
new Intl.ListFormat('bg', {type: 'disjunction'}).formatToParts(['a','b','c'])
```

**Comment by saschanaz** [comment]
It's ES2021 per the [Finished Proposals](https://github.com/tc39/proposals/blob/master/ecma402/finished-proposals.md) list.

**Comment by vhfmag** [comment]
Thanks for pointing that out, I've updated the issue accordingly.

**Comment by chasm** [comment]
Is there a workaround for this?

**Comment by vhfmag** [comment]
Personally, I used something like:

```ts
declare namespace Intl {
    type ListType = "conjunction" | "disjunction";

    interface ListFormatOptions {
        localeMatcher?: "lookup" | "best fit";
        type?: ListType;
        style?: "long" | "short" | "narrow";
    }

    interface ListFormatPart {
        type: "element" | "literal";
        value: string;
    }

    class ListFormat {
        constructor(locales?: string | string[], options?: ListFormatOptions);
        format(values: any[]): string;
        formatToParts(values: any[]): ListFormatPart[];
        supportedLocalesOf(
            locales: string | string[],
            options?: ListFormatOptions,
        ): string[];
    }
}
```

**Comment by chasm** [comment]
Thanks for the help. That works great for making the linting errors go away, but (I'm using Deno) I still get `[ERROR]: Property 'ListFormat' does not exist on type 'typeof Intl'.`  when I try to bundle it or run tests. And yet it works fine in the Deno REPL, so I know that it _does_ exist.... I guess I don't understand Deno/TS enough to see what's going on.

**Comment by andreubotella** [comment]
The Deno REPL uses swc to transpile TypeScript without doing any type-checking, so that difference is not indicative of there being types for `Intl.ListFormat` in Deno or TypeScript.

**Comment by chasm** [comment]
Yes. I understood that. The types are missing, but the REPL cares not. But the actual _code_ must be there or it wouldn't work at all, no? The VSCode linter picks up the above namespace declaration and the red squiggles go away, but clearly the bundler and test in Deno do not, as they fail the type check.

**Comment by vhfmag** [comment]
@chasm I haven't much experience with it, but I found this in [Deno's docs](https://deno.land/manual/typescript/types#using-a-configuration-file): 

> Another option is to use a configuration file that is configured to include the type definitions, by supplying a "types" value to the "compilerOptions". For example:
>
> ```json
> {
>   "compilerOptions": {
>     "types": [
>       "./types.d.ts",
>       "https://deno.land/x/pkg@1.0.0/types.d.ts",
>       "/Users/me/pkg/types.d.ts"
>     ]
>   }
> }
> ```

Maybe refering to the `.d.ts` file would make the bundler aware of it?

**Comment by chasm** [comment]
Excellent. I will check that out. Thanks.

**Comment by AndreMantas** [comment]
is this live? i cant find ListFormat after installing https://www.npmjs.com/package/@types/intl

**Comment by saschanaz** [comment]
This is live, and that package is outdated and should not be required in any situation. Make sure your `target` is `es2021` or higher, and if that still doesn't work, *please open a new issue rather than commenting on an old issue*. Thanks.
