### ISSUE TITLE
--experimental-json-modules syntax error

### ISSUE THREAD

**Issue by imsys** [microsoft/TypeScript#46903]
I just started using VScode and I'm not exactly sure if this is the correct repo for the js syntax checking.

I converted my code from CJS to ES Module, and a way to import json files there is shown in the links below.

https://nodejs.org/docs/latest-v17.x/api/esm.html#json-modules

https://github.com/tc39/proposal-json-modules

Node runs the code correctly, but VScode keeps showing me an error message. And I would not want to disable the whole syntax checking just for this line, but it kind of annoys me and take my attention away.

![Screenshot_20211121_232823](https://user-images.githubusercontent.com/911254/142792261-62ac4ea7-1c96-4b4f-8a21-76c9bc7cefe5.png)

**Comment by dbaeumer** [comment]
This is related to TS/JS language server.

**Comment by IllusionMH** [comment]
Module assertions support was added in TS 4.5 but current VS Code stable ships with 4.4.
VS Code Insiders builds already have TS 4.5 built-in.

**Comment by imsys** [comment]
> Module assertions support was added in TS 4.5 but current VS Code stable ships with 4.4.
VS Code Insiders builds already have TS 4.5 built-in.

Thanks! I would not know were to look for. I just have set Code OSS 1.61.0 to use TS 4.5.2, and it works! Thanks!
