### ISSUE TITLE
require() call not suppressed when only accessing constant enumerations

### ISSUE THREAD

**Issue by sebastian-lenz** [microsoft/TypeScript#4690]
I'm currently converting a project to use the new es6 module style (which is really a great feature!). The compiler removes all references to modules I'm using only typing information from which makes absolutely sense. However, when accessing a constant enumeration the require call will be preserved in js output although it is not needed, e.g.:

**a.ts**

```
export const enum MyEnum {
    ValueA,
    ValueB,
    ValueC
}
```

**b.ts**

```
import * as a from "./a";
export var myValue = a.MyEnum.ValueB;
```

Now, <code>b.ts</code> compiles to this, note the unnecessary <code>require</code> call:

**b.js**

```
var a = require("./a");
exports.myValue = 1;
```

First I thought this is my fault but then I tried to use the imported types solely as type arguments which results in the compiler removing the require call correctly, e.g.:

**c.ts**

```
import * as a from "./a";

export function myFunction(value:a.MyEnum):string {
    return "myReturn";
}
```

Will compile to this:

**c.js**

```
function myFunction(value) {
    return "myReturn";
}
exports.myFunction = myFunction;
```

**Comment by yortus** [comment]
Another case:

```typescript
// @fileName: a.d.ts
declare module "a" {
    export const enum Enum {
        Member
    }
}

// @fileName: b.ts
import a = require("a");
let q = a.Enum.Member;

// @fileName: c.ts
import a = require("a");
import Enum = a.Enum;
let q = Enum.Member;

```

which emits:

```typescript
// @fileName: b.js
var a = require("a");
var q = 0 /* Member */;

// @fileName: c.js
var q = 0 /* Member */;
```

I feared this was by design recalling a team member's comment way back on #319 that "There aren't any guarantees about import declarations are elided" (although I see that comment has since disappeared but my reply which quotes it is still there). Thanks in advance for fixing this.

**Comment by nojvek** [comment]
Seems this bug is open for almost an year. Not sure if anyone is looking into it. Is there an ETA on this? The current hack is to convert the .d.ts files into .ts files. 

If it's relatively easy to fix I can take a stab.

**Comment by RyanCavanaugh** [comment]
Seems like this works now
