### ISSUE TITLE
Add formatRange to Intl.DatetimeFormat

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript#46905]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

• formatRange

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add formatRange to Intl.DatetimeFormat, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange .

## 📃 Motivating Example

`new Intl.DateTimeFormat('bg').formatRange(new Date(), new Date())` shall not produce an error from typescript, stating that the method formatRange does not exist.  The current error is “Property 'formatRange' does not exist on type 'DateTimeFormat'.”

## 💻 Use Cases

`new Intl.DateTimeFormat('bg').formatRange(new Date(), new Date())` shall not produce an error from typescript, stating that the method formatRange does not exist.  The current error is “Property 'formatRange' does not exist on type 'DateTimeFormat'.”

**Comment by stefee** [comment]
Any update on this would be massively appreciated!

**Comment by zohar-exon** [comment]
Hi, does typescript already supports the format range method?
I'm using version 5.5.4 and it throws me: ``Property 'formatRange' does not exist on type 'DateTimeFormat'.ts(2339)``

**Comment by msssk** [comment]
TypeScript 5.9.2 is still throwing the error:
`Property 'formatRange' does not exist on type 'DateTimeFormat'.ts(2339)`

**Comment by RyanCavanaugh** [comment]
You need to set your `target` (or lib) to `es2021` or higher, as this is an ES2021 feature
