### ISSUE TITLE
Use a specific aka.ms/tsc link in tsc --help for tsc CLI options

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#46919]
# Suggestion

## 🔍 Search Terms

tsc cli help options aka ms aka.ms

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Could an https://aka.ms/tsc-reference link be created that links to the [TSC CLI options](https://www.typescriptlang.org/docs/handbook/compiler-options.html)?

## 📃 Motivating Example

Right now the main aka.ms links used in tsc are:

* The last text printed by `tsc --help`: https://aka.ms/tsconfig-reference
* The first comment in `tsc --init`'s `tsconfig.json`: https://aka.ms/tsconfig.json

```shell
# tsc --help
You can learn about all of the compiler options at https://aka.ms/tsconfig-reference
```

```jsonc
// tsconfig.json
/* Visit https://aka.ms/tsconfig.json to read more about this file */
```

The `tsc --help` one is a little confusing because most would, I think, associate "tsconfig" with specifically the `tsconfig.json` files. Both links go to the same place.

Could we change them to instead match and be something like:

* The last text printed by `tsc --help`: https://aka.ms/tsc-reference
* The first comment in `tsc --init`'s `tsconfig.json`: https://aka.ms/tsconfig-reference

## 💻 Use Cases

I'm writing a _Learning TypeScript_ book chapter on how to configure TypeScript that covers both the `tsc` CLI and TSConfig files. https://aka.ms/tsconfig.json is a great and useful link, but there isn't a friendly aka.ms permalink equivalent for the `tsc` CLI.

**Comment by RyanCavanaugh** [comment]
Link created; accepting PRs for the UI update

**Comment by JoshuaKGoldberg** [comment]
Oh @RyanCavanaugh, sorry, I just had an epiphany -- what do you think about aka.ms/tsc and aka.ms/tsconfig.json? I rather like them for matching the locations people are seeing them in...

**Comment by RyanCavanaugh** [comment]
Happy to make whichever links; they're easy to do from our side and helps people who only half-remember or half-type them

**Comment by JoshuaKGoldberg** [comment]
In that case, yes please to **aka.ms/tsc** and **aka.ms/tsconfig.json** :)
