### ISSUE TITLE
Implicit type guard by other variables are not always working

### ISSUE THREAD

**Issue by Egor-Koldasov** [microsoft/TypeScript#46915]
# Bug Report

### 🔎 Search Terms

Implicit type guard by other variables.

### Related

https://github.com/microsoft/TypeScript/pull/44730

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about **type guards**

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBNCGUCmMC8MDeAoGMAOATiHgIwBcMA5AG7wA2ArkiZQDQ75F4BMFN9Tbmw6FiAZj61GSMcIC+WLFACeeFAGUoiFOhVqQAMzhbkAbkV6UAaSTKIaGAAoA1rcMxN2gJSLQkWAC28K7qSFAAClwOjniIABYUNnYwAD4wDGAAJkgGAJZgSJleaAB8mBwA9BUwAEQQYZHENTC59mAgsGAMdHQtRjWxUHHNrTDtsBnZeQWZHH7QcA1R6By4g3EwAPyruE5STBTQBPkA5sWoZQjIANrrALoO+yhkO7hdPea4VbWZiPAjbQ6Y26vVGA3iALGQMmOXyhTm4AWvy0aB26y2ryoBQAHlAAGoCJCUGAvXa7d50cyVao1ZH-Fr2egAd3gyXGwJ6fVq9QiXEh7IprBgACMGLAhihQAE8Lk6EgCDBMiAkIDYAQkKATmBcgAvFC5KAcXJGRw8xp4YpmriOOleUwwb4AQQIJwYASQYFg7ksVCOp1SHLoxNG7PgEAguS18GFcpgUBA+HgBHg7uQCu9qhQlD9YBOlCNJtti15xBtfztDuqAGF4GB2flqCBXDBazAQMKAFYa2BMuK5YAbUZ4EDh3Ix5RYkGUAB0Bac60tS1Ltvt3xrdaBDabKFb7a7wB7fYHDPwI4j48nPRnMGdrvdnrbRh92agx1zAYpwdVLdHUZjKHjRNk1TeVHzjTNfVfU4ZznU0lzwGAADJEMVcti3NMstArb4mRAAhnAgLA5CAA)

### 💻 Code

```ts
const state = {
  prop1: 'value1',
  prop2: 'value2',
  prop3: 'value3',
}

type State = typeof state;

type Keys = (keyof State)

const makeSetProp = (path: Keys | undefined) => {
  // "setProp" is not null if "path" is not undefined
  const setProp = 
    path ?
      (value: string) => state[path] = value :
      null;
  // "data" is not null is "path" is not undefined
  const data =
    path ?
      'nextValue' :
      null;

  // "data" is always not null if "setProp" is not null, but the compiler does not recognize it
  if (setProp) setProp(data); // Argument of type 'string | null' is not assignable to parameter of type 'string'
  if (data) setProp(data); // Cannot invoke an object which is possibly 'null'.
  if (path) setProp(data); // Cannot invoke an object which is possibly 'null'. Argument of type 'string | null' is not assignable to parameter of type 'string'.
  if (setProp && data) setProp(data); // works
}
```

### 🙁 Actual behavior

- `data` does not narrow by checking the `setProp`
- `setProp` does not narrow by checking the `data`
- `data` and `setProp` both do not narrow by checking the `path` even though they were defined by it

### 🙂 Expected behavior

Logically they all can be narrowed by each other:
- `data` can be narrowed by checking the `setProp` or `path`
- `setProp` can be narrowed by checking the `data` or `path`

**Comment by RyanCavanaugh** [comment]
The behavior in #44730 doesn't go as far as a full-blown counterfactual analysis, which is basically what'd be required here. The guarding expression has to be a boolean.
