### ISSUE TITLE
Wrong TypeReference name in TypeAliasDeclaration in AST

### ISSUE THREAD

**Issue by Enapiuz** [microsoft/TypeScript#46921]
# Bug Report

### 🔎 Search Terms

typealias
type alias

### 🕗 Version & Regression Information

Reproduces with every version staring from 4.2.1, including nightly.

- This changed between versions 4.1.5 and 4.2.1

### ⏯ Playground Link

[~~Playground~~ AST Visualiser link with relevant code](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBDAnmYCCiA7GBLJBJAEwB4A5AQwFtVQZgMCBnOBmKbDAcwD44BeOAN5wMlYAC445KnAC+AbgBQoSLATJUMPBTIdghPuiy5EhIgCIGEKgH0RVM10VA)

### 💻 Code

```ts
export type tEntityId<Name extends string> = { name: Name };
export type tImageId = tEntityId<"some_name">;
```

### 🙁 Actual behavior

The second line of provided example is a TypeAliasDeclaration and `tEntityId<"some_name">` is a TypeReference.
`escapedName` property of this type reference is `tImageId` which breaks out code generation that depends on it.

### 🙂 Expected behavior
`escapedName` property of this TypeReference should be `tEntityId<"some_name">` as is always was before.

**Comment by RyanCavanaugh** [comment]
I'm not sure what you're pointing at. Code I'm running:
```ts
const ts = require("typescript");
const sourceFile = ts.createSourceFile(
  "file.ts",
  "export type tEntityId<Name extends string> = { name: Name }; export type tImageId = tEntityId<'some_name'>;",
  ts.ScriptTarget.Latest
);
console.log(sourceFile.statements[1].type.typeName.escapedText);
```
This prints `tEntityId` as expected. Can you provide a sample that prints the wrong thing?

**Comment by RyanCavanaugh** [comment]
This doesn't seem like a defect; returning `tImageId` here is what the `aliasSymbol` property is *for*. It's attached so that type printback uses the alias name when possible.

I'm probably confused here -- you linked an AST explorer as part of the repro, but the AST part of this is all as expected (?). It's the type alias resolution that's changed for the better, not anything with parsing. The code here asks two different questions (what is the parsed tree of this program; what is the name to give this type) and gets two different answers.

**Comment by Enapiuz** [comment]
Sorry, I'm a bit new to all these core language things, so I might use wrong terminology.

There is nothing wrong with AST structure itself. I linked AST explorer because for me it was easier to see the difference. I'll add some screenshots of it.

This is 4.1.5:
![Screenshot 2021-12-02 at 11 43 39](https://user-images.githubusercontent.com/3235481/144397485-46f091a4-b6a0-43b3-8a88-fa3e93f09c8f.png)
And this is 4.5.2:
![Screenshot 2021-12-02 at 11 44 08](https://user-images.githubusercontent.com/3235481/144397502-3a805979-f05c-4244-b5eb-39e56a8285a2.png)

The same expression, but different result for different language versions. Question here is — was it changed by intension?
Because on the second line we have type alias declaration, where what lies before `=` is Identifier (as in AST) and its value (escapedText property I suppose) is `tImageId`. And what lies after `=` is TypeReference (according to AST) and it refers to the first line of our example code. Which is `tEntityId`. I just don't get the idea how it became `tImageId`.

**Comment by xenJ** [comment]
A bit modified script:
`import * as ts from "typescript";

const sourceFile = ts.createSourceFile(
    "file.ts",
    "export type tEntityId<Name extends string> = { name: Name }; export type tImageId = tEntityId<'some_name'>;",
    ts.ScriptTarget.Latest
);
const host = ts.createCompilerHost({});
host.getSourceFile = (name: string, version: ts.ScriptTarget) => {
    return sourceFile;
}

const program: ts.Program = ts.createProgram(["file.ts"], {}, host);
const node = (sourceFile.statements[1] as ts.TypeAliasDeclaration).type as ts.TypeReferenceNode;
const type = program.getTypeChecker().getTypeAtLocation(node);
const sym = program.getTypeChecker().getSymbolAtLocation(node.typeName);
console.log("NODE: " + node.getText());
console.log("NODE SYMBOL: " + sym.escapedName);
console.log("NODE SYMBOL DECLARATION: " + sym.declarations[0].getText());
console.log("NODE TYPE SYMBOL: " + type.symbol.escapedName);
console.log("NODE TYPE SYMBOL DECLARATION: " + type.symbol.declarations[0].getText());
console.log("NODE TYPE ALIAS SYMBOL DECLARATION: " + type.aliasSymbol.declarations[0].getText());
console.log("NODE TYPE ALIAS SYMBOL: "+ type.aliasSymbol.escapedName);`

With TS 4.5.2 product the following:
`
NODE: tEntityId<'some_name'>
NODE SYMBOL: tEntityId
NODE SYMBOL DECLARATION: export type tEntityId<Name extends string> = { name: Name };
NODE TYPE SYMBOL: __type
NODE TYPE SYMBOL DECLARATION: { name: Name }
NODE TYPE ALIAS SYMBOL DECLARATION: export type tImageId = tEntityId<'some_name'>;
NODE TYPE ALIAS SYMBOL: tImageId
`
And with TS 4.1.5:
`
NODE: tEntityId<'some_name'>
NODE SYMBOL: tEntityId
NODE SYMBOL DECLARATION: export type tEntityId<Name extends string> = { name: Name };
NODE TYPE SYMBOL: __type
NODE TYPE SYMBOL DECLARATION: { name: Name }
NODE TYPE ALIAS SYMBOL DECLARATION: export type tEntityId<Name extends string> = { name: Name };
NODE TYPE ALIAS SYMBOL: tEntityId
`
And the last one seems correct...

**Comment by RyanCavanaugh** [comment]
This is what `aliasSymbol` is for -- to tell you which type alias (if any) declared this type. This is why `aliasSymbol` property exists. The difference between `symbol` and `aliasSymbol` is about whether you're asking about the type itself, or an alias that declared it if one exists. That is why there are two properties, and you need to access the one that corresponds to the behavior you're looking for.

**Comment by xenJ** [comment]
@RyanCavanaugh this is true - but please notice that in the example above for the type `{ name: Name }` the alias symbol should be `type tEntityId<Name extends string> = { name: Name }` but type checker suggest the `type tImageId = tEntityId<'some_name'>;` what is not correct.

**Comment by RyanCavanaugh** [comment]
This is, again, a misunderstanding of what these properties mean. The type you got from `getTypeAtLocation` is `tEntityId<'some_name'>`, which is an instantiation whose symbol has a declaration of `{ name: Name }`, but this instantiation has the attached alias `tImageId` because you wrote
`type tImageId = tEntityId<'some_name'>`

```ts
import * as ts from "typescript";

const sourceFile = ts.createSourceFile(
    "file.ts",
    `/*0*/ export type tEntityId<Name extends string> = { name: Name };
    /*1*/ export type tImageId = tEntityId<'some_name'>;
    /*2*/ export type tImageIdOther = tEntityId<'other_name'>;
    /*3*/ declare const j: tEntityId<'foo'>;`,
    ts.ScriptTarget.Latest
);
const host = ts.createCompilerHost({});
host.getSourceFile = (name: string, version: ts.ScriptTarget) => {
    return sourceFile;
}

const program: ts.Program = ts.createProgram(["file.ts"], {}, host);
console.log('ref 1');
desc((sourceFile.statements[1] as ts.TypeAliasDeclaration).type as ts.TypeReferenceNode);
console.log('ref 2');
desc((sourceFile.statements[2] as ts.TypeAliasDeclaration).type as ts.TypeReferenceNode);
console.log('ref 3');
desc((sourceFile.statements[3] as ts.VariableStatement).declarationList.declarations[0].type! as ts.TypeReferenceNode);

function desc(node: ts.TypeReferenceNode) {
    const type = program.getTypeChecker().getTypeAtLocation(node)!;
    const sym = program.getTypeChecker().getSymbolAtLocation(node.typeName)!;
    console.log("NODE: " + node.getText());
    console.log("NODE SYMBOL: " + sym.escapedName);
    console.log("NODE SYMBOL DECLARATION: " + sym.declarations![0].getText());
    console.log("NODE TYPE DISPLAY: " + program.getTypeChecker().typeToString(type));
    console.log("NODE TYPE SYMBOL DECLARATION: " + type.symbol.declarations![0].getText());
    console.log("NODE TYPE ALIAS SYMBOL DECLARATION: " + type.aliasSymbol?.declarations![0].getText());
    console.log("NODE TYPE ALIAS SYMBOL: "+ type.aliasSymbol?.escapedName);
}
```
You can't just look at the `.declarations` of a type's symbol and assume that's the whole story -- a generic type instantiation will have a symbol whose declaration points at the underlying template, but the type itself is different.
