### ISSUE TITLE
`@type` on http(s) import

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#46936]
# Suggestion

```js
/**
 * @type {import('chai')}
 */
import { expect } from 'https://cdn.skypack.dev/chai'
```

Sugar for
```js
// @ts-ignore
import { expect as _expect } from 'https://cdn.skypack.dev/chai'
/**
 * @type {import('chai')['expect']}
 */
const expect = _expect
```

## 🔍 Search Terms

`jsdoc` `@type` `http loader` `ESM` `skypack` `.d.ts`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Alternatively, maybe let `tsconfig.compilerOptions.paths` accept `RegExp`

**Comment by ncpa0cpl** [comment]
You can add typing to a module via `declare module`. Create `.d.ts` file with this:
```ts
declare module "https://cdn.skypack.dev/chai" {
  import chai from "chai";
  export = chai;
}
```
and you will get the same result you want

**Comment by loynoir** [comment]
Yeah, working. 😄
Not very graceful, but I'm ok to close.
