### ISSUE TITLE
Generic curried functions lose type information when partially applied within another generic type

### ISSUE THREAD

**Issue by jmartinezmaes** [microsoft/TypeScript#46940]
# Bug Report

### 🔎 Search Terms

generic, curried, function, infer, inferred, unknown, type, partial, partially, applied

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about functions and generics.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABALxgBwDwEEB8AKAQwC5EsBKEjAIXwCMSqzEBeHRAbSwBpEqBdRAG8AUIjGIATgFMoICUjy0mrDgR60+AbmEBfYcIgAbAgGcTvOAA9sbEeMQQEJqBJDQ4EvNIIATBIYBPRAA3AkMQKRJyIUQ9UXEAWwJMGjxgEkIo5TZGBitqW3j7MWlZeUQwKQB3C0s0vCgACxgTADpQ8KkyMm17OPtktECAFThsHlSmlrzrTNJs3hweJoIoGZsKWoKhIuLSuSRKmqorBua2joiz1fawiO7e8X7xQcCAMQk4BILrta256IqGibE7WGg7YrifblI61X63TpnFoI+49XZ6OKOMDOCogBKglgVapwgAsACY0Vicc4JATmETjqcAOSNKSGQxwJlo4QAeh5iAAopY0FJoFIfCR2GA8bQpBIeDSYGAAOZ8Xn8rDQEBhMSS6UJWXyxDgADWYDgVTAaqpUEQUCkzgADIT9aDWkk0HhUGgyK1XgFRngaaDuXzBcLRfaJRxFSqePrDWqw5rZDrEJLY8qeKbzZbrU5bfbnABGF14t3+j5fIMuN0er3oB76MMASTAwDlUkgUkQLUQwCVPaqrKQAANvaPe+Y0AQJLAwoFEK8YOLELQgjAoCY2ekDAXEMrCd68OTKfui1AyYTlXgWWyOVzEGGpTK5QqXErVUA)

### 💻 Code

```ts
function zip<A>(a: A): <B>(b: B) => [A, B] {
    return (b) => [a, b];
}

class Box<A> {
    constructor(readonly value: A) { }

    map<B>(f: (a: A) => B): Box<B> {
        return new Box(f(this.value));
    }

    applyTo<A, B>(this: Box<(a: A) => B>, that: Box<A>): Box<B> {
        return new Box(this.value(that.value));
    }

    applyFrom<B>(that: Box<(a: A) => B>): Box<B> {
        return new Box(that.value(this.value));
    }
}

const numBox = new Box(42);
const strBox = new Box('hello');

// Expected: [number, string]
// Actual  : [number, unknown]
const test0 = numBox.map(zip).applyTo(strBox);

// Expected: [string, number]
// Actual  : [string, unknown]
const test1 = numBox.applyFrom(strBox.map(zip));

// Inference is fine when `zip` is partially applied by itself:
const g = zip(42);
const test2 = g('hello') // [number, string]
```

### 🙁 Actual behavior

The generic `B` of the `zip` function is not properly inferred when `zip` is partially applied within another generic type (in this example, `Box<A>`). Instead, the value defaults to `unknown`. Behavior does not change when the order of arguments are switched - see the `applyTo` and `applyFrom` methods of `Box` and their corresponding results. 

When `zip` is partially applied outside of another generic type it has no problem correctly inferring the generic `B`.

### 🙂 Expected behavior

Generic curried functions should be able to correctly infer generic parameters when partially applied in another generic type.

**Comment by RyanCavanaugh** [comment]
Not sure if this is a bug or design limitation...
```ts
function zip<A>(a: A): <B>(b: B) => [A, B] {
    return (b) => [a, b];
}

class Box<A> {
    constructor(readonly value: A) { }

    map<B>(f: (a: A) => B): Box<B> {
        return new Box(f(this.value));
    }

    applyTo<A, B>(this: Box<(a: A) => B>, that: Box<A>): Box<B> {
        return new Box(this.value(that.value));
    }

    applyFrom<B>(that: Box<(a: A) => B>): Box<B> {
        return new Box(that.value(this.value));
    }
}

const numBox = new Box(42);
const strBox = new Box('hello');

// Expected: [number, string]
// Actual  : [number, unknown]
const test0 = numBox.map(zip).applyTo(strBox);

// Not specific to 'this'
declare function freeApplyTo<A, B>(thiss: Box<(a: A) => B>, that: Box<A>): Box<B>;
const test1 = freeApplyTo(numBox.map(zip), strBox);

// Not specific to intermediate generic call
const arg = numBox.map(zip);
const test2 = freeApplyTo(arg, strBox);
```

**Comment by ahejlsberg** [comment]
This is effectively a design limitation in our inference logic. Inference has the ability to contextually type generic function arguments passed for non-generic function parameters only when the function types are "naked" (i.e. top-level and not nested). For example:

```ts
function zip<A>(a: A): <B>(b: B) => [A, B] {
    return b => [a, b];
}

class Box<A> {
    constructor(readonly value: A) { }
    map<B>(f: (a: A) => B): Box<B> {
        return new Box(f(this.value));
    }
}

const strBox = new Box('hello');
const numBox = new Box(42);
const zipBox = numBox.map(zip);  // Box<(<B>(b: B) => [number, B])>

declare function applyFuncToBox<X, Y>(f: (a: X) => Y, box: Box<X>): Box<Y>;
declare function applyBoxedFuncToBox<A, B>(f: Box<(a: A) => B>, box: Box<A>): Box<B>;

const t0 = applyFuncToBox(zipBox.value, strBox);  // Box<[number, string]>
const t1 = applyBoxedFuncToBox(zipBox, strBox);  // Box<[number, unknown]>
```

Above, when the `f` parameter has a non-generic function type and the corresponding argument `zipBox.value` has a generic function type, inference has the ability to unify the two. But when the function types are nested in an object type (in this case as the type of the `value` property) inference doesn't have that ability and, in effect, the type parameters are erased to their bounds.

**Comment by janwirth** [comment]
I'm having the same problem.

**Comment by jm4rtinez** [comment]
@janwirth You may be experiencing an unrelated issue here. Try changing the signature of your function to:

```ts
const get2 = <T>(sample: T) =>(value: T) => <Label extends keyof T>(label: Label): T[Label] => { /* ... */ }
```

Notice how the `Label` generic parameter has been moved to its corresponding function parameter list. Does this help with type inference?

Here's a [playground link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMQMAmAHgBUA+ACgGcoBbABwhAC54KBKTmgNygRkHLt3gBeKvEoAZKACMQEeCAAeGEKmB14AaxABPHIi61oSiJwrzL4qVwDaNxcoC6AbgCwAKF+hIWAQwPDoMeAYWNk4Ab3g1TgAiAAtlCBxEgBp4QySAdxwYCGBE+ABfbx8A6Dh4ENQw+EFhUTiE+BS0jOzcjoKikvLK33rGzTCARklCYhJ6JlYQbgEhEWXEtUTuStHw8dJpolJ5qKWVlvXDLeGfAHpb+AABDDoAWnVmcAx3mBhCrmSWF0dGSOGQxVUv3+SjAUGQdAQGFS+iM8AABgAvNHwYA4EC6VA4cLqIHhLD4NEUNEjUJ7fEYADMh1mJ0Wy2aaxoiQx1yAA) that demonstrates this working as expected.

**Comment by janwirth** [comment]
@jm4rtinez thank you for your help. I see now where my problem was! Very useful.

**Comment by renatoaraujoc** [comment]
> @janwirth You may be experiencing an unrelated issue here. Try changing the signature of your function to:
> 
> ```ts
> const get2 = <T>(sample: T) =>(value: T) => <Label extends keyof T>(label: Label): T[Label] => { /* ... */ }
> ```
> 
> Notice how the `Label` generic parameter has been moved to its corresponding function parameter list. Does this help with type inference?
> 
> Here's a [playground link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMQMAmAHgBUA+ACgGcoBbABwhAC54KBKTmgNygRkHLt3gBeKvEoAZKACMQEeCAAeGEKmB14AaxABPHIi61oSiJwrzL4qVwDaNxcoC6AbgCwAKF+hIWAQwPDoMeAYWNk4Ab3g1TgAiAAtlCBxEgBp4QySAdxwYCGBE+ABfbx8A6Dh4ENQw+EFhUTiE+BS0jOzcjoKikvLK33rGzTCARklCYhJ6JlYQbgEhEWXEtUTuStHw8dJpolJ5qKWVlvXDLeGfAHpb+AABDDoAWnVmcAx3mBhCrmSWF0dGSOGQxVUv3+SjAUGQdAQGFS+iM8AABgAvNHwYA4EC6VA4cLqIHhLD4NEUNEjUJ7fEYADMh1mJ0Wy2aaxoiQx1yAA) that demonstrates this working as expected.

A simple google research and I find this, thank you! Saved my life.

I had this:

```typescript
const getInputMaskByPath =
    <
        T extends NestedKeyOf<IInputMasks, InputMask>,
        K extends Extract<keyof T, string>
    >(
        inputMasksObj: IInputMasks
    ) =>
    (maskPath: K): T[K] =>
        maskPath.split('.').reduce((p, c) => p?.[c], inputMasksObj) as T[K];
```

And now, by moving some parts, it works! 

```typescript
const getInputMaskByPath =
    (inputMasksObj: IInputMasks) =>
    <
        T extends NestedKeyOf<IInputMasks, InputMask>,
        K extends Extract<keyof T, string>
    >(
        maskPath: K
    ): T[K] =>
        maskPath.split('.').reduce((p, c) => p?.[c], inputMasksObj) as T[K];
```
