### ISSUE TITLE
allow separate `compilerOptions` for node modules

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#46943]
# Suggestion

## 🔍 Search Terms
tsconfig compilerOptions node_modules

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
it would be nice if you could include your `tsconfig.json` in your published package, and projects that depend on it could use its `compilerOptions` when type checking it

## 📃 Motivating Example
it's frustrating when you try to enable strictness flags in your project, only for it to cause type errors in `node_modules`. if each package included its `tsconfig.json` it could type-check them with the `compilerOptions` defined there, instead of your project's `tsconfig.json` which should only really apply to the source code that you can control

## 💻 Use Cases

enabling strictness flags without having to enable `skipLibCheck`

**Comment by MartinJohns** [comment]
This essentially sounds the same as #37853.
