### ISSUE TITLE
Interfaces that extend 'Symbol' cannot be used as 'symbol' type directly

### ISSUE THREAD

**Issue by yusufkandemir** [microsoft/TypeScript#46956]
# Bug Report

### 🔎 Search Terms

extends Symbol
extends Symbol index key
extending Symbol
InjectionKey
cannot be used as an index type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries
- I was unable to test this on versions prior to 4.4(PR #44512) because symbols weren't accepted as index types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/PTAECUFMDNIJ0gOwMaVNA9nUBJRArSZAFwEsNEBpSATwC5QALY4gBwGc6QBzU4xgK4AjAHTIMAW2AA3AZHzsZcgLSJIAD2LAhAGwxDgAJgAmAFmimArJdMBmUwE5jQgGxCADAHZ3hz8ffILoYu0JYuyKYAHP6GtrbQLp7ArACGyADWKdyQinACiGQSkMriCMDscMjAKaykeIQkIsTsAMQAMi4AUKQF8NBpaPVEZBTUNAA8ACoAfKAaxEjG7KAAyjQSQhg6oADeAL6d3b1w-airkpB4CycDu+gYGAzsxHA93KAH4ojPoOm0DEMSOQqLRxisLlc+gNZgBeVbrTY6AAUAEpDl8fghSksGFBseNnq9EO8AD6gdgIrYAGlAKUQNFhuz2AG5DlisEsANoAchSykJb25AF1maAxWKQKAAOpYdLsTrsuBctYbLaokXizWSmVwOUKogc9icv40DWa80SsAAEQwOUQ3OIoAA7rL9dijSbacsKaqdGbtbL5Z1JQBBdjsUjcRApISkHR8GigBbPeUYx0AfRNAEYnpTtnCTaKLVrrbb2PbHS7dZ006BM7RDLnfaAC7QveS86KA7qg5KAMIpZ5vJM5ZqHT2Dju+rtgHVy4ugJEAUXUrGGkGMaIn3pebxnoBtdodztli5Xa5IG63bcniAEG3g+8P5ePVfSZ9X683wbAIj-6IoH4fRbeFfVRVlOmAycfURfc52WYtl0-S9vygnciW4J8ywrE9dQ-C8FlQ9Z2zvB84Cwo9K1PJCCKvH9QD-EROiAA)

### 💻 Code

```ts
// Reference for InjectionKey: https://github.com/vuejs/vue-next/blob/2d4f4554349db6b07027d0c626f56c48d0233f67/packages/runtime-core/src/apiInject.ts#L6
interface InjectionKey<T> extends Symbol {}

interface SomeInterface { foo: string }
const key: InjectionKey<SomeInterface> = Symbol()

const records: Record<string | symbol, any> = {};

records['a-string'];     // Works
records[Symbol()];       // Works
records[key];            // Doesn't work
records[key as symbol];  // Works

// Assignability tests
const _key1: symbol = key;           // Doesn't work
const _key2: symbol = key as symbol; // Works

// Casting tests

key as symbol; // Works        (Expected)
key as string; // Doesn't work (Expected)
key as number; // Doesn't work (Expected)
// ...

const sym = Symbol();

sym as symbol; // Works        (Expected)
sym as string; // Doesn't work (Expected)
sym as number; // Doesn't work (Expected)
// ...
```

### 🙁 Actual behavior

Interfaces that extend `Symbol`(e.g. `InjectionKey`) can't be used as `symbol` directly although they can be explicitly cast.

### 🙂 Expected behavior

Interfaces that extend `Symbol` can be used as `symbol`, which includes being used as index types.

**Comment by whzx5byb** [comment]
A wrapper object type(`Symbol, Number, String`...) is not assignable to the corresponsive primitive type(`symbol, number, string`...). And [the doc](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types) says you should avoid using them in practice.

In your example, consider making the `InjectionKey` as a intersection type.
```ts
type InjectionKey<T> = symbol & T;
```

**Comment by yusufkandemir** [comment]
@whzx5byb thanks for the info and suggestions 👏.

```ts
type InjectionKey<T> = symbol & T;
```
wouldn't be the same as
```ts
interface InjectionKey<T> extends Symbol {}
```
`T` shouldn't be a possible value.

So, it would be like
```ts
type InjectionKey<T> = symbol;
```
then the type becomes primitive, which makes extracting the generic parameter type impossible.

I also found that the docs don't recommend using a generic type parameter with an unused type parameter, see [here](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#generics). So, this means the code I shared is wrong in many ways. But, I think it's the only way possible to create symbols that are paired with a specific type.

See [this playground](https://www.typescriptlang.org/play?ts=4.5.2#code/PTAEFkEsFtIYwNaQHYHNQAsAuWAOBnALhADcBmAOhIFcBTAK3woHsAnVYVayAE1uDjNouZvkhZIzZAFoAhrkjTcrZiV61pKerThYK2aABsAUMZCgASrQBmtVrWRxaoa21ABJZNt2TkAaVoAT0JMHAJiTnEMagAjCkFoYBoGfCS6aWRaAA8sYBjDZhjgACYeABZrMoBWKrKyMoBOHhiANhiABgB2duLOnna4FuKW6yqWuDKADn7isjJrFs7gXFlEWVRaVNZqZAloDUF7YHxWOGB5SE9vPSx8AGIAGRbjFCw7a1XnK50JKQDAgA8ABUAHygbJvZA8fCgADKgWgMWYhlAAG8AL6mV7vT5woS0TxvVgfJxolzMZghfBYVgodCYwTIamgBBBELfHx-IIA2H4wk4pxggC8cIRSMMAAoAJSmRnM6DyEJWQ48AH4MXI0AAH1A1NpaAANKBZMhAsK0ZjjNYdpzkKBlKp1MCQRLWcEPF4fr5-s6jSRZIY6CEgVK0cZQBHQArcABtN3GmHqxHIgC6oBF-sDtGMmOtjl+dq0P2drrZHuu3u5oKlwbDkdA9iw1FYdoxCdAQJzpgdaj4pcCRtR5MpoAA5G9qaPQOiZWYwFkQrz9vziZ9jHKsKAsunQEXdP3Z+YAMJCXCGSAmzcAdyioTwRBAV6fFCwgVwmzgtNwWEMJtQLHYYAeGYOBUgwE1mgpBAgJ0X9WFkAtpGsSBDE2IDmGkfA5ChaRgJkW59CwIw7mQahETsTCaTpaQkWRWgTUwjVDGwnhpEKa45zhCRDBRZBmE3BIzwvXZQBvLAMDvcJH2fV933wT9IG-X80AAjhgNA4BwKhWjoL4OA4IQ3wkJQtDgMwljcKkaQCIMQw7g2TJaVA4xZK+T1bX+YpnR3JNxSxXYBWcJcCQC1dSSHVwRz1Olp3XKRmTdYp2XcgtPJ5PlQpJWhzXhZNJVnPNbXtFRe1oLzQX7ZKKy5QJypBP0AyDDtQ1RcNI2jOMgjTDNGuzXMbQLXcUrqyryy9Gq6prDs60jRtm1bdF207S0e3UYp+2KQcZ1Acw+NAVzpDgDAdCQNBQDcWRqCwDDBNQwaUFAYooXtWR4OgI0Yh0S78GcIFdxhPjNxNANAgAL1kfJs04rIktAHYED4q87WIOKmU3GGdz3LB1sSmUgA) for a use case, with two approaches.

At this point, it looks like it's against the best practices, but the only way to solve a particular problem, at least the people at Vue, and also me after digging through this. So, I guess the maintainers could just close the issue because it's against their recommendation(which is fine), provide a legit alternative solution to this problem(it would be fantastic), or search for ways to create a legit way if it doesn't exist yet(i.e. they are willing to accept a feature request about this).

**Comment by RyanCavanaugh** [comment]
Yeah, this code just isn't doing what you think it's doing. The type `Symbol` is an object type, and object types aren't valid object keys (the same reason `foo[{ }]` is not allowed). The same problem is present with `number` / `Number`, etc

**Comment by pikax** [comment]
@yusufkandemir the `InjectionKey` on `vue 3` is to be used *only* with [provide](https://github.com/vuejs/vue-next/blob/2d4f4554349db6b07027d0c626f56c48d0233f67/packages/runtime-core/src/apiInject.ts#L8)/[inject](https://github.com/vuejs/vue-next/blob/2d4f4554349db6b07027d0c626f56c48d0233f67/packages/runtime-core/src/apiInject.ts#L30-L45)

The reason that `extends Symbol` is to make sure the user is using with a `unique symbol` to guarantee the dependency at runtime. 

If someone is using `InjectionKey<T>` to direct access a property (like the example on the issue) that's is not supported by `vue`.


Since this interface is **_only_** to be used with `provide/inject` in `vue` I don't think there's an issue with the current implementation on `vue 3`, since the goal is to have a typed safe interface for `inject/provide`.

**Comment by yusufkandemir** [comment]
@pikax I appreciate the explanation. The main idea behind this was basically to have an `appInject` helper, which is still possible to achieve, and not directly related to this issue. But, when playing around with the idea, I came across some problems and dived into how everything works, how TS behaves, etc., and decided to open this issue because it seemed like a bug.

I guess you are mainly referring to this:
> So, this means the code I shared is wrong in many ways.

which is correct in terms of "being wrong according to the TS best practices".
And, it is followed by
> But, I think **it's the only way possible** to create symbols that are paired with a specific type.

and similar supporting sentences.

So, with the last answer I received from Ryan Cavanaugh(_don't want to bother with a ping_), the situation became clearer(_I hope I understood it correctly 😛_). The current implementation in Vue 3 is correct, because it just works and it's clean to use and understand, and there is no other way possible to achieve this, even though it looks like it's against TS best practices. But, I think it's safe to say that if this is the intended behavior of TS, and there is no other way of achieving such a thing (_both of which seems to be the case_), we can't really say the current implementation on Vue 3 is against the TS best practices. A best practice becomes invalid when it completely blocks us from achieving something. By the way, I love your work ❤️

**Comment by pikax** [comment]
Since `vue` also need to allow defining `provide/inject` through the object API, is worth to investigate a bit further, based on the @whzx5byb  it works but adds the possibility of assigning `T as InjectionKey<T>` which is not correct.

Based on that I think is save to do something like:
```ts
declare const InjectionSymbol: unique symbol
type InjectionKey<T> = symbol & { [InjectionSymbol]: T };

//@ts-expect-error it cannot be the same type
const foo = {foo: false} as InjectionKey<{foo: false}>
```

The only issue, it works now but will it work in the future or will typescript support this type in the future? For example `PropertyKey<T>` typed?
