### ISSUE TITLE
Mutable arrow function variable that returns void can be assigned different return types without erroring.

### ISSUE THREAD

**Issue by TigerQAa** [microsoft/TypeScript#46950]
# Bug Report

### 🔎 Search Terms

mutable function void
mutable arrow function void
arrow function void

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about functions and function-related things in Type System Behavior.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAZg9jEF4IAoCUiB8EDeBfAsAFBGzxJqYQDaAjALpFEDGMAdgM4ygB0wMA5slJpuAWwCGAB2QAPSgGp5M1KiJA)

### 💻 Code

```ts
let foo = () => {}

foo = () => [1]

console.log(foo().map(x => ++x))
```

### 🙁 Actual behavior

It did not error on line 2; and instead, it changed the variable. It errored on line 5 because the function "map" did not exist on type void.

### 🙂 Expected behavior

I expected it to error on line 2 because it was assigning a different return type to the arrow function.

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void
