### ISSUE TITLE
Key inferred from own property cannot be used to index the property

### ISSUE THREAD

**Issue by alecgibson** [microsoft/TypeScript#46954]
# Bug Report

### 🔎 Search Terms

infer this property key generic

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "this", "property", "generic"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAKYCcCmA7ALtA3gWAFDWgAcBXAIxAEthpgB7FAMwoHNoBeLPAgh22gLmgByELWQBbIQBou0AL4BuPLJLkq0MMGBIoAHgDS0JAA80qACYwA1kgCetBtDQALChADaQuoxZCAugB8ABQ2toL6AJSCLm6e3kzM-u76fpz43MhoxAgoTq4QAHTxLO6hfkrpcnhVuHigkDAAwq4g5kamFjDwyOhpBKqU1LQAbkgICBTmSDT0Cex93LwCwqIS0rIEpIiCQhSEEMSSMpUVNXgoSADucIioaEERBZraUEFCS0IRFQD039AAAmgIABaEyEJDANCg8Zic5XG49e6PZ46CBvLYIT4VOHXZoUVoPJ5aVFvD5fHHQPEE5HE15CDFYvC-AFA0HGcGQ6EIWG4C64lrmQkoulbABeWKAA)

### 💻 Code

```ts
class Parent {
  public config = {
    foo: 'lorem',
  };

  public access<K extends keyof this['config']>(key: K): this['config'][K] {
    return this.config[key];
  }
}

class Child extends Parent {
  public override config = {
    foo: 'lorem',
    bar: 'ipsum',
  };
}

new Parent().access('foo');
// @ts-expect-error
new Parent().access('bar');

new Child().access('foo');
new Child().access('bar');
// @ts-expect-error
new Child().access('baz');
```

### 🙁 Actual behavior

Compilation error:

```
Type 'K' cannot be used to index type '{ foo: string; }'.(2536)
```

### 🙂 Expected behavior

I'd expect the above code to compile, since `K` is _defined_ as a key of `{foo: string}`

(Edit: simplified example by replacing getters with dumb properties)

**Comment by RyanCavanaugh** [comment]
Property access on class fields doesn't get deferred type resolution like you're expecting: the type of `this.config` is plain `{ foo: string }`, not `this["config"]`. That causes this example to break, but is necessary for other scenarios to work -- otherwise you couldn't write
```ts
class Parent {
  public config = {
    foo: 'lorem',
  };
  public mut() {
    this.config.foo = "ergo";
  }

  public access<K extends keyof this['config']>(key: K): this['config'][K] {
    return this.config[key];
  }
}
```
since there's no guarantee that the derived type doesn't need a more-specific value of `foo`

**Comment by alecgibson** [comment]
That's a shame. It might be nice to be able to clarify intent with something like `as const`, which would effectively tie the two types together. That would basically make it possible to "opt in" to my expected behaviour (which would opt out of the ability to do your example).

```ts
class Parent {
  public config = {
    foo: 'lorem',
  } as const; // added `as const`, to show that this shouldn't change

  public mut() {
    // @ts-expect-error
    this.config.foo = 'ergo';
  }

  public access<K extends keyof this['config']>(key: K): this['config'][K] {
    return this.config[key];
  }
}
```

Anyway, I realise this is niche. Just thought I'd flag it, since I found it unexpected.

**Comment by alecgibson** [comment]
Thanks again for the quick and informative response!
