### ISSUE TITLE
default type not working when extending

### ISSUE THREAD

**Issue by robertIsaac** [microsoft/TypeScript#46957]
# Bug Report

### 🔎 Search Terms

default type not working when extending

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about extend

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211130#code/MYGwhgzhAEDCD2A7AbgUwE4BcCCiCe0A3gFDRnBJpYA8AKtALzRj4B8AFGAFzQSboBLRAHMAlD3oky06OlSYArukTQAUgGUA8gDkAdAAcw6CKk6iA3KTIBfYreKhIMBCgyZtCgLYAjDNFQAHpioiAAmzpRuuARSZAD0cdDeCpjQmAAWAjAA7vDoANYQVtAJ0BSuWJw8fIIi4sz4RMXlVJhVvPxCYk0yZHKKytAePhhmltK29uV8ZZFY0YzQiKjZcHM4+OwWDkgQ8CCouiDwwuwtUfi655UA5ACMN6Lb06nX7l6+6IvLqy6tw58tpZpvtDsdTm8ARgrut2PdHtsgA)

### 💻 Code

```ts
class ConvertAny {
   convert<T = any>(a: string): T {
      return JSON.parse(a);
   }
}

class ConvertNumber extends ConvertAny {
   // but this works
   // convert(a: string): any {
   convert(a: string) {
      return Number(a);
   }
}

const convertAny = new ConvertAny();
console.log(convertAny.convert('1'));
const convertNumber = new ConvertNumber();
console.log(convertNumber.convert('1'));
```

### 🙁 Actual behavior

it throw error

```
Property 'convert' in type 'ConvertNumber' is not assignable to the same property in base type 'ConvertAny'.
  Type '(a: string) => number' is not assignable to type '<T = any>(a: string) => T'.
    Type 'number' is not assignable to type 'T'.
      'T' could be instantiated with an arbitrary type which could be unrelated to 'number'.
```

### 🙂 Expected behavior

to compile normally since in the base class it falls back to any

### additional details
while this may seem like a trivial change the developer can do easily, but in real case scenario when we are doing refactor for a method to allow generic type, this makes us change everywhere it has been polymorphism

**Comment by MartinJohns** [comment]
Why **should** that work? It would be inherently unsafe. Just take this example:

    const val: ConvertAny = new ConvertNumber();
    const result = val.convert<string>("bla"); // Type is string, but actual value is number.

**Comment by whzx5byb** [comment]
To make it polymorphism the generic type parameter is usually applied to the class itself, not the methods.

```ts
class ConvertAny<T = any> {
   convert(a: string): T {
      return JSON.parse(a);
   }
}

class ConvertNumber extends ConvertAny<number> {
   convert(a: string) {
      return Number(a);
   }
}
```

**Comment by robertIsaac** [comment]
> Why **should** that work? It would be inherently unsafe. Just take this example:
> 
> ```
> const val: ConvertAny = new ConvertNumber();
> const result = val.convert<string>("bla"); // Type is string, but actual value is number.
> ```

you are talking about that specific example, but the problem is not like that at all
the real problem is dealing with objects with different types, now we are trying to stop any and pass the proper type, but it's impossible to make all teams do this change at the same time

**Comment by robertIsaac** [comment]
> To make it polymorphism the generic type parameter is usually applied to the class itself, not the methods.
> 
> ```ts
> class ConvertAny<T = any> {
>    convert(a: string): T {
>       return JSON.parse(a);
>    }
> }
> 
> class ConvertNumber extends ConvertAny<number> {
>    convert(a: string) {
>       return Number(a);
>    }
> }
> ```

in my case it's an Angular service, we use that same methods multiple times in the same file each time with a different type
so I can't make the class itself generic
