### ISSUE TITLE
Rest parameters declaration is not work

### ISSUE THREAD

**Issue by ShieldBennet** [microsoft/TypeScript#46966]
I have declared a parameter as *rest parameters*, but when passing parameters to it, the type error "Expected to be 2 parameters but got 3" appears:

```ts
type Arrow<A = any, B = any> = (a: A) => B;

type ArrowEnd<R> = R extends Arrow<any, infer B> ? B : never;

type IsEmpty<T> = T extends never[] ? true : false;

type Head<T> = T extends [infer H, ...any] ? H : never;

type Tail<T> = T extends [any, ...infer R] ? R : never;

type Piper<A, F> = Head<F> extends Arrow<A, infer B>
  ? IsEmpty<Tail<F>> extends true
    ? F
    : Piper<B, Tail<F>>
  : never;

type Last<T> = T extends [...any, infer L] ? L : never;

export function pipeline<A, F extends Arrow[]>(
  a: A,
  ...functions: Piper<A, F>
): ArrowEnd<Last<F>> {
  return undefined as ArrowEnd<Last<F>>;
}

const v = pipeline(
  1,
  (s: number) => String(s),
  // @ts-expect-error TS2554: Expected 2 arguments, but got 3.
  (s: string) => '1'
);
```

**Comment by MartinJohns** [comment]
Questions are better suited for sites like [StackOverflow](https://stackoverflow.com/). Bug reports should follow the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md), helping the TypeScript team triage and address the issue.

**Comment by RyanCavanaugh** [comment]
Generic inference can't flow backwards through conditional types like you're expecting here
