### ISSUE TITLE
Regression: compiler error on the left-hand side of an 'instanceof' expression for intersection types

### ISSUE THREAD

**Issue by alessandro-tucci-visiontech** [microsoft/TypeScript#46968]
# Bug Report

### 🔎 Search Terms

`intersection types left-hand side of an instanceof expression`

### 🕗 Version & Regression Information

This changed between versions **4.2.3** and **4.3.5**. The issue still appears in **4.4.4**, whereas it looks solved in **4.5.2**.
We were able to fully reproduce the issue in the playground. If you "run" the example against 4.3.5 and 4.4.4, you will see a compilation error, whereas you will see no compilation error in 4.1.5, 4.2.3 and 4.5.2.
The problem seems to be rooted in the intersection-type handling itself. Indeed, if we replace `never` with `any` in the `TypedKey` definition, the error still appears.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.3.5#code/KYDwDg9gTgLgBDAnmYcAqzgBMDSxEA8ASgDToB8cAvHAN4CwAUHHANo5wCWAdnANb4IAMzhEAugC4mLIuzFxQMYNywBndHAD8cDhLjdgAN2BQmAX1YDEw0WIDcTJqEiw4AYwA2AQ1XqAkljKMJxCnF4ARh7AACJoAPJ00ixcWACEeqowUDwA5g7MycZQqpwQ3On6AK4AtuEm+WaOjM7Q8J4+6tHAUTARUbEJispqcAFBIWGRMfGJBSyBPdgV4RAQUV7cDU0tru2+cABqXh6cWH3TgyBKKp3dwL1TA7PJcIbHp8ur65vmTU7grXc3n2AGU7m4YGCvFA3AALADCEGqkAM3BgBCSIIUV2G-kCaIm5wGJCSHCGN3QmFw+AIILIYwJoSJ8XIJIKRGx1xGILkcAAZHAABQM4JMx7xACUSUoDEYSTAlUinDccFU9xFhKmgp4mQ2bmAeiIEsNz2SISFOt63H1XG4uutwBsRxOZ3FcQlppe2rtVptPkO71d-UlADo3i7qAgoJVgPkXo05lwRN77TbLXrHSIuj1me7PckU77UP7s-dcxKQwt7thI0Jjmq48kEy8oPdKlBeOmHY2EwmgA)

### 💻 Code

```ts
/**
List of all the keys 
**/
export type TypedKey<R, T> = {
  [K in keyof R]:
  R[K] extends T ? K : never
}[keyof R];

export class IdentifiableDTO {
    id!: string;
    version!: number;
}

export class DeletableDTO extends IdentifiableDTO {
    deleted!: boolean;
}

export class ValidableDTO extends DeletableDTO {
    valid!: boolean;
}


export class SelectSearchComponent<
  S extends IdentifiableDTO,
  K extends TypedKey<S, IdentifiableDTO>,
  R extends S[K] & (IdentifiableDTO)
  > {

  public setIdentifiable(instance: R): R {
    if (instance instanceof ValidableDTO) {
      (instance as ValidableDTO).valid = true;
    }
    if (instance instanceof DeletableDTO) {
      (instance as DeletableDTO).deleted = false;
    }
    return instance;
  }
}
```

### 🙁 Actual behavior

`ERROR: The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.`

### 🙂 Expected behavior

No compilation error

**Comment by RyanCavanaugh** [comment]
> The issue still appears in 4.4.4, whereas it looks solved in 4.5.2.

4.5 is the latest version and we wouldn't normally backport a fix to an older release unless it was critical (this would not qualify). Can I close this or is something else needed?

**Comment by alessandro-tucci-visiontech** [comment]
@RyanCavanaugh I realize that it is a non-blocking issue which can be worked around by doing `const untypedInstance: any = instance;` and making all the checks on `untypedInstance`. However, please let me add that 4.3.5 is also the most recent Typescript version which is officially supported by the most recent Angular LTS version. Therefore, I kindly ask you to consider the positive impact such a backport would have on the user base.
In case you are not willing to, nothing else is needed from my side about this issue.

**Comment by RyanCavanaugh** [comment]
Thanks for the context. Given the severity/frequency of the problem (and workaround) and risk associated with changing a release as old as 4.3.5, we won't be porting the fix to prior versions.
