### ISSUE TITLE
Wrapping the left-hand side of an awaited assignment in parenthesis incorrectly changes the order of execution of the operands.

### ISSUE THREAD

**Issue by GabRoyer** [Microsoft/TypeScript#4696]
In the current Async/Await prototype, we found a bug in the order in which the operands are called if assigning to a parenthesis expression.

# Repro
While the following code works properly : 

```javascript
class classA {
	get b() {
		console.log("a.b");
		return new classB();
	}
}

class classB {
	set c(val) {
		console.log("b.c");
	}
}

async function d():Q.Promise<number> {
	return Q.fcall(() => { console.log("d"); return 4;});
}

async function main(): Q.Promise<void> {
    var a = new classA();
    a.b.c = await d();
}

main();
```
And correctly logs the following : 
```
a.b
d
b.c
```

Surrounding the left hand side operand with parenthesis so that the code now looks like : 
```javascript
async function main(): Q.Promise<void> {
    var a = new classA();
    (a.b.c)  = await d();
}
```

Now gives the following logs :
```
d
a.b
b.c
```

# Analysis
This seems to be due to how the compiler looks only for if the left expression is a property access and treats parenthesis expression like any other expression.

If we change the last two functions to be synchronous so that the code now look like this : 
```javascript
function d():number {
	console.log("d");
	return 4;
}

function main() {
    var a = new classA();
    (a.b.c) = d();
}
```

The logs are : 
```
a.b
d
b.c
```

**Comment by rbuckton** [comment]
@GabRoyer Is this targeting TypeScript 1.6 or the older prototypeAsync branch?

**Comment by GabRoyer** [comment]
Older prototypeAsync branch yes. Sorry about that.
