### ISSUE TITLE
Type not matched when using keyof instead of literal

### ISSUE THREAD

**Issue by truemogician** [microsoft/TypeScript#46964]
# Bug Report

### 🔎 Search Terms

I've posted this problem on [StackOverflow](https://stackoverflow.com/questions/70165652/typescript-type-pattern-not-matched-when-using-keyof-instead-of-literal) but received no comments or answers.  
This problem is rather difficult to describe briefly in natural language (or maybe due to my poor English), thus I failed to find any relative questions through the search engine.

### 🕗 Version & Regression Information

I'm currently using TypeScript 4.4.4, earlier versions are not tested, but I suppose they'll behave the same.

### 💻 Code

```ts
type a = { foo: "bar" } extends { "foo" } ? true : false;
type b = { [K in keyof { "foo" }]: { foo: "bar" } extends { K } ? true : false }["foo"];
```

### 🙁 Actual behavior

```ts
a = true
b = false
```

### 🙂 Expected behavior

`b` should also be `true`

**Comment by RyanCavanaugh** [comment]
```ts
type a = { foo: "bar" } extends { "foo" } ? true : false;
type b = { [K in keyof { "foo" }]: { foo: "bar" } extends { K } ? true : false }["foo"];
```
The type being resolved here is
```ts
{ foo: "bar" } extends { K: unknown } ? true : false
```
K in this position is a property name, not a reference to the key type. You could equally have written
```ts
type a = { foo: "bar" } extends { "foo" } ? true : false;
type b = { [K in keyof { "foo" }]: { foo: "bar" } extends { QQQ } ? true : false }["foo"];
```
Which is clearly correctly `false`

This is `true` as expected:
```ts
type b = { [K in keyof { "foo": any }]: ({ foo: "bar" } extends Record<K, unknown> ? true : false) }["foo"];
```

**Comment by truemogician** [comment]
@RyanCavanaugh  Thank you!  
It is me instead of TypeScript that turns out wrong lol  
In fact, I'm not quite sure whether this is a bug, but since I can't get help even in StackOverflow, reporting the problem here becomes my only choice.
