### ISSUE TITLE
Inference is broken for object generics with return function

### ISSUE THREAD

**Issue by tannerlinsley** [microsoft/TypeScript#46977]
# Bug Report

### 🔎 Search Terms

inference, generics, return type

### 🕗 Version & Regression Information

I'm not sure when this bug "appeared", but it seems to behave this way for every version, even the nightly

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about object property inference with regards to function returns

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.5.2#code/GYVwdgxgLglg9mABCAzgUwIojQJwJ4A8AKlrngNJp4A0iRAIgIZSMB8AFAPpwAOsCKAFyIA3gChEiAI7Z8lPMJKyKVANwTpygGJhh7CAihoAHlAD8wkZrLzFpOVUQBfAJSIAvKzpMW6yQgBlEAgINBQhRHYAE2ZGRR9GN09EADc4GCj1V1EnMTEDMBQoawc8D0QAbQAiIyKq2gBGWgAmWisAZmEoHGxnAF08gHpBxDA4RAKjU1HxiHwxVExldnFJGRsqag11-B09F2EwEABbACNcDy8mjUDg0PC9GJYkryfGADooOC0YYzQo9guLaudRiYaIRgoRAoOAICFQgCSyHQEygxlob0QMChY0QABsEABzC5wYCIKB4HhoUYnc44RDAOD024hMIoBboex4FbbZTyLZrbS6SLQYwHGlnC7Ja6ScEAdQAFmVsYgAAZvVWIUnkynU1WMMB4VVmG5gIKsh6RN4vRBvT7fX7-QHAlzqIA

### 💻 Code

```ts
function useQuery<TQueryKey, TData>(_options: {
  queryKey: TQueryKey;
  queryFn: (context?: { queryKey: TQueryKey }) => TData;
  onSuccess: (data: TData) => void;
}) {}

const queryKey = ["test", 1, 2, { 3: true }]

// no context no cry
useQuery({
  queryKey,
  queryFn: (): number => 1,
  onSuccess: (data) => data.toFixed(),
});

// as soon as I use ctx, data is no longer of type number for onSuccess
useQuery({
  queryKey,
  queryFn: (ctx): number => 1,
  // Why is `data` of type `any`?
  onSuccess: (data) => data.toFixed(),
});

```

### 🙁 Actual behavior

In the second example the `data` argument on the `onSuccess` function is typed as `any`.

### 🙂 Expected behavior

In the second example the `data` argument should be typed as the return value of the `queryFn` property, or more specifically, `number`

**Comment by tannerlinsley** [comment]
cc @tkdodo

**Comment by MartinJohns** [comment]
Pretty sure it's the same as #43371.

**Comment by tannerlinsley** [comment]
Thanks @MartinJohns. I'll track it there.
