### ISSUE TITLE
[Bug] Variadic tuple type is (sometimes) not preserved

### ISSUE THREAD

**Issue by TeoTN** [microsoft/TypeScript#46979]
# Bug Report

It seems types inferred from variadic tuple types sometimes get lost. Please see below for an example

### 🔎 Search Terms

variadic tuple 

### 🕗 Version & Regression Information

Checked in playground v4.5.2 and v4.6.0-dev.20211201

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211201#code/C4TwDgpgBA0hJQLxQM7AE4EsB2BzKAPlNgK4C2ARhOoaiJQPYA2A3AFBuiRQCS2AJhAAeAQwpNoyAN5socqAG0A1vCg5Y8ALoAuKCOwh2AX3adw0ADIi0AHgAqUYcAgCUUEtiXYGAd2wLNAD4kKAcnF343BQA6WLVsADNqKAB9ABp4pJoARU0oAH4obKhdbAgAN2pTLmgAcQhgGwB5CgArRyFnV14BYTEJDIAFdAYwDq7IjRBg5BbWhWHRzWrzKABRUTIwCWa28Yi3PkFRcQgMuxJt6HDuuBAAmah6xrmMq1sLq8DAle4NkS2Ek+EhCCgA5CIwRkwRQwZozH9NlcAIwhd6Nf6AiDAiCBNgAYwY2DQUAoukxKJCMLBLCAA)

### 💻 Code
```
type Key = string | number | symbol;

type Indexable = {
    [key in Key]: any;
};

type Last<T extends unknown[]> = T extends [... infer _, infer Q] ? Q : never;

type Get<Obj extends Indexable, Prop extends Key> = Obj[Prop];

// Next line errors - it seems Last<Tuple> becomes unknown
type Example<Obj extends Indexable, Tuple extends Key[]> = Get<Obj, Last<Tuple>>;

type ExampleTuple = ['a', 'b']
type Example1 = Last<ExampleTuple>
// This works fine
const b: Example1 = 'b';
```

### 🙁 Actual behavior

The error produced is:
```
Type 'Last<Tuple>' does not satisfy the constraint 'Key'.
  Type 'unknown' is not assignable to type 'Key'.
    Type 'unknown' is not assignable to type 'symbol'.
      Type 'Last<Tuple>' is not assignable to type 'symbol'.
        Type 'unknown' is not assignable to type 'symbol'.(2344)
```

### 🙂 Expected behavior
No errors expected.

It'd also be very helpful if TypeScript had `Head<T>`, `Last<T>`, `Tail<T>`, `Leading<T>` implemented natively

### Potentially related issues:
#41136
#39713

**Comment by ahejlsberg** [comment]
This is working as intended. The `Last<T>` type resolves to `never` when `T` is an array type (it only produces a non-never result for a non-empty tuple type). Since `Tuple` is constrained to `Key[]`, this means `Last<Tuple>` has no constraint. It works as expected if you modify the `Last<T>` type to handle arrays:

```ts
type Last<T extends unknown[]> =
    T extends [...unknown[], infer Q] ? Q :
    T extends (infer Q)[] ? Q :
    never;
```
