### ISSUE TITLE
Project baselines sometimes cannot be accepted

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4697]
If a project test baseline fails, a `jake baseline-accept` doesn't currently seem to work.

**Comment by danquirk** [comment]
jake baseline-accept has never worked with the project tests, you've always had to manually baseline them.

**Comment by DanielRosenwasser** [comment]
1. That's sort of odd.
2. Actually baselines aren't even generated when they fail:

![image](https://cloud.githubusercontent.com/assets/972891/9750505/b169bfcc-564d-11e5-85a4-f990b8d568a8.png)
