### ISSUE TITLE
[Bug] Object.assign incorrect return type when source argument is a function

### ISSUE THREAD

**Issue by askvortsov1** [microsoft/TypeScript#46982]
# Bug Report

### 🔎 Search Terms

object.assign function

### 🕗 Version & Regression Information

First noted with v4.1.3. Replicat
Please keep and fill in the line that best applies:
-->
- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gWwgMQK4DsDGwCWd1QC8UAFAIYBOA5gFxQDOwFO6VAlEQHxQBucOAEwDcAKFCRYiCAHkARgCsI2IlADeAMzhw6jZqwC+okZnyMo6uvCRosufCvLUdTFuy5rDx08CjbJSOUVlYg0tOgByWUpwzy90MxMKCiVgSykbbDwCADJ-GQUUlUCUgDoyenocKnQSdQAaXzZRE3ifFkTk7DTrDEz7XKt8oJ9iYuwyiqqauAb1JpERAHpFqAAVAAsceigAdzgKAGtt8qgIAA9IbAgBLySUkgAieilgTdYH+aWVkp+oACFUD5XlsoK8KHAdscCBAkvsRO19p1gI9nkhge9PstJFAAAYIu7YHFQEHia7EhBgcGQCgAGxAJSAA)

### 💻 Code

```ts
type SomeFunction = (arg: string) => void;
type SomeObject = {foo: string};

const f: SomeFunction = (arg: string) => {};
const o: SomeObject = {foo: 'bar'};

const correct: SomeFunction & SomeObject = Object.assign(f, o);
const incorrect: SomeFunction & SomeObject = Object.assign(o, f);

// This works as expected
correct("something");

// ... But this throws an error
incorrect("something");

// So `incorrect` should not be typable with `SomeFunction & SomeObject`.
```

### 🙁 Actual behavior

`incorrect` is typed as `SomeFunction & SomeObject`, but since Object.assign only copies enumerable properties, the output should be a function iff the target object is a function.

### 🙂 Expected behavior

The only function types included in the output type intersection should be from the `target` input.

**Comment by RyanCavanaugh** [comment]
`Object.assign` is just a userland function from our perspective; it doesn't have any special behavior. Intersection is the closest available representation and was chosen per user feedback.
