### ISSUE TITLE
Bug: Valid programs with JSX fail to typecheck when JSX is de-sugared

### ISSUE THREAD

**Issue by jameshfisher** [microsoft/TypeScript#46988]
### 🔎 Search Terms

jsx children

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about jsx

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSATJNAGxSLkwFcA7DYCFuACVQoAoA3nDQALYDQpEuAXwBccQaTgqR4ydIXJ0MAHTaMAOQhUA3KRkBKBQCkAygA1dAURpIQSFjHOk0nAM7wAAooAOZIAOrAMKL2DnAAvHD8lokAfMnKqgA8vCgUaVmqOTDRbmm8NDQQ2QD0pTDlRXB1eQWkluR+LIFwIeFRMRBMMHGJyakJGQZ6aEQoMEiu7p4w-G0ANIoyG80zunOoi8seXvz4DW74W4I7BJXV+Ja7lkA)

### 💻 Code

```tsx
import React from 'react'

// This example comes from https://github.com/vercel/next.js/blob/5544adc481f8821567e947a6e6d51d9d68ebd367/packages/next/shared/lib/head.tsx#L172
declare function Head({ children }: {
    children: React.ReactNode;
}): JSX.Element;

// This typechecks
const PageWithJSX = () => (
    <Head>
        <title>Hello</title>
    </Head>
)

// This does not typecheck
const PageWithoutJSX = () => React.createElement(Head, {},
    React.createElement('title', {}, 'Hello'),
)
```

### 🙁 Actual behavior

The non-JSX code gives the type error:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{}' is not assignable to parameter of type 'Attributes & { children: ReactNode; }'.
      Property 'children' is missing in type '{}' but required in type '{ children: ReactNode; }'.(2769)
input.tsx(5, 5): 'children' is declared here.
```

### 🙂 Expected behavior

No type error should be given, because it's just the same as the code that does type-check, only without JSX.

**Comment by IllusionMH** [comment]
Looks like this is problem with overloads provided by `@types/react` which expect intersection of  `Attributes` and props of `Head` to be present or `null`. If you change `{}` (which prevents match to any of overloads) to `null` error is gone.

So either `@types/react` needs to be updated or generated code should produce `null` instead of `{}`. I don't see problem with `tsc` here.

**Comment by jameshfisher** [comment]
@IllusionMH that's a good point that the error doesn't occur with `null`. However, this is an edge case - if any _other_ properties are required, the error comes back. [Here's an example of this:](https://www.typescriptlang.org/play?ts=4.5.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSATJNAGxSLkwFcA7DYCFuACVQoAoA3nDQALYDQpEuAXwBccQaTgrGECAoDOMKMBYBzANzLVYiVKQsFydDAB0NjADkIVYzICUCgFIBlABp2AKI0SCCWMMakaJzacAAKKPpIAOrAMKJ+-nAAvHD8HrkAfPkmKgA8vCgUahA5AEQARvT1RWWqFTDpoUW8NDQQ5QD0XTA97cNVFG0e5DEscYnJaRkQTDBZufmFOSWO9mhEKDBIIWER-FMANIqY6gr4zVD4Mlft+3aHqCdn4Sww-Hwo1C+BugleBD6A3wHjeHiAA)

```tsx
import React from 'react'

declare function Head({ children }: {
    foo: string;
    children: React.ReactNode;
}): JSX.Element;

const PageWithJSX = () => (
    <Head foo="bar">
        <title>Hello</title>
    </Head>
)

const PageWithoutJSX = () => React.createElement(Head, {foo: 'bar'},
    React.createElement('title', {}, 'Hello'),
)
```

In this case, replacing with `null` is not an option.

**Comment by jameshfisher** [comment]
I believe this is a `tsc` problem because of this principle: if a program typechecks, then its de-sugared equivalent should also typecheck. In other words, `tsc` should essentially be de-sugaring any JSX before it typechecks the program. Would you agree with this principle?

**Comment by IllusionMH** [comment]
I still think that it's case with overloads available for `createElement`.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/00e423d21da9c9f81dc2bb15c700b9c8f456c42d/types/react/index.d.ts#L283-L298

All calls use props of Class/Function and in your case `children` is explicitly specified as required prop.

**Comment by jameshfisher** [comment]
I believe this is the type declaration being used in my example:

```ts
    function createElement<P extends {}>(
        type: FunctionComponent<P>,
        props?: Attributes & P | null,
        ...children: ReactNode[]): FunctionComponentElement<P>;
```

If we were to fix this declaration, I'm not sure what the right fix would be. I came up with this:

```ts
declare function c<P extends {}>(
  type: FunctionComponent<P>,
  props?:
    | (Attributes & Omit<P, 'children'> & { children?: ReactNode[] })
    | null,
  ...children: ReactNode[]
): FunctionComponentElement<P>;
```

Effectively, this resets `P`'s `children` type to `children?: React.ReactNode[]`. This works, although I'm not sure it's the most elegant way to solve the problem.

@IllusionMH do you have any opinion? I can open an issue with the React typings.

**Comment by IllusionMH** [comment]
I'm typing on phone so can't keep up with all comments.

> Would you agree with this principle?

I'd say it depends.

AFAIK JSX typechecks don't rely on `createElement` definition and vice-versa. Therefore I think it's incorrect to assume that both of these code blocks would have same results during typecheck.
Moreover in this case definitions are provided by third party and not TS.

> do you have any opinion? I can open an issue with the React typings.

Tricky question again and probably you should wait for response from team.

IMHO this change (specifically `Omit`, that IIRC might break complex discriminated unions) might be problematic. Also can't check if it would work as expected for cases when `children` in component have some other specific type e.g. function as it's popular in some libs. However `createElement` never properly checked these types in `...children` position.

I think it's possible to create issue/PR to update `@types/react` definitions but it's hard to say if this change would break more than it fixes.

**Comment by jameshfisher** [comment]
Thanks @IllusionMH - I've opened a discussion at https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57511

**Comment by RyanCavanaugh** [comment]
See #14729; there are substantial performance problems if we treat JSX elements as their corresponding function calls

**Comment by jameshfisher** [comment]
@RyanCavanaugh interesting. I'm biased since I don't use JSX, but I would almost always take a slower compiler over an inaccurate one.

**Comment by trusktr** [comment]
I would take a slower compiler over an inaccurate one too.

Having return types for JSX expressions (in #14729) would be phenomenal.

**Comment by fatcerberus** [comment]
> I would almost always take a slower compiler over an inaccurate one.

Normally I’d agree, but because of how TS is designed (structural typing, Turing-complete type system, etc.), performance doesn’t always scale in the way you’d expect (as a general observation, can’t say whether this is one such case or not).  That’s not hyperbole—it often means the difference between a few seconds to compile and several *minutes*, even in reasonably-sized codebases.

**Comment by trusktr** [comment]
We can currently write a DOM tree using hyperscript-style code with nested functions and get types. I don't see why not simply extend this to JSX syntax.

**Comment by trusktr** [comment]
JSX is syntax for something we can otherwise already do with nested function calls, and therefore I believe JSX should benefit from the same sort of typing.

**Comment by trusktr** [comment]
Why the confused face @RyanCavanaugh ? The performance of nested function calls is that bad?

**Comment by RyanCavanaugh** [comment]
@trusktr because I said

> there are substantial performance problems if we treat JSX elements as their corresponding function calls

and then you said

>  I don't see why not simply extend this to JSX syntax.

after I literally told you why?
