### ISSUE TITLE
Offer quick fix for some uses of 'await' outside an async context

### ISSUE THREAD

**Issue by rbuckton** [microsoft/TypeScript#46986]
_Originally discussed in #38483._

We currently offer a quick fix to add an `async` modifier if we parse `await` in a non-async context when the `await` is unambiguously an _AwaitExpression_:

![image](https://user-images.githubusercontent.com/3902892/144331531-7cf52b20-bb3c-4672-85e0-8ae4b57d1c31.png)

However, we do not offer that quick fix if we parse `await` in cases where it is ambiguous (such as in a call expression):

![image](https://user-images.githubusercontent.com/3902892/144331680-a4d4f6b7-dae8-477c-827b-d250b8961271.png)

We should consider special-casing the error message for `await` when it is ambiguous so that we can offer compatible quick fixes.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser @rbuckton Should it be done in [suggestionDiagnostics](https://github.com/microsoft/TypeScript/blob/main/src/services/suggestionDiagnostics.ts)?

**Comment by DanielRosenwasser** [comment]
I think the idea is that instead of `Cannot find name 'await'.` we would possibly issue a special-cased diagnostic like

```
Cannot find name 'await'. Did you mean to write this in an async function?
```

and provide a quick fix for that.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Ok, thanks

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Not at all :).
