### ISSUE TITLE
Syntactic sugar for ADTs... Don't close! Listen to me for a moment.

### ISSUE THREAD

**Issue by anilanar** [microsoft/TypeScript#46984]
Let's start with the fact: **Everybody loves ADTs** .

We already have product types, we are just missing a nicer way to create tagged sum types. We are also missing a nicer way pattern match tagged sum types.

`enum` is the most obvious choice to implement this feature on top because it already breaks the **"Gotta stay similar to JS"** rule and Rustlang also uses it to achieve ADTs.

I know that the aforementioned rule is very serious for TS core team; but if there's anything we want to bend the rules for, it must be for ADTs, right? 

Actually, the code can be converted in such a way that it has no runtime component.

---------------

e.g.

```
enum X<Q> {
  A(t: T);
  B(t: T, u: U);
}

match(X.A(foo)) {
  case A(t): t;
  case B(t, u): t;
  default: bar;
}
```

would be transformed to the following, potentially at the syntax level, just to make it a syntactic sugar and nothing else:

```typescript
type X<Q> = { tag: 'A', value: { t: T } | { tag: 'B', value: { t: T; u: U } };

const X = {
  A: <Q>(t: T): X<Q> => ({ tag: 'A' as 'A', value: { t } }),
  B: <Q>(t: T, u: U): X<Q> => ({ tag: 'B' as 'B', value: { t, u } }),
};

(() => {
  const val = X.A(foo);
  switch(val.tag) {
    case 'A': return val.value.t;
    case 'B': return val.value.t;
    default: return bar;
  }
})();
```

--------------

Those who opt-in for ADTs would surely welcome little complexity this transformation introduces.

**Comment by MartinJohns** [comment]
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

**Comment by anilanar** [comment]
@MartinJohns It would be great if you could also specify which goal/non-goal this contradicts with.

**Comment by RyanCavanaugh** [comment]
It looks like you want to follow https://github.com/tc39/proposal-pattern-matching

We don't want to add new runtime syntax to JS ourselves (especially something this invasive) and I don't know how to be any clearer about that.

**Comment by anilanar** [comment]
@RyanCavanaugh Let's ignore `match` for a moment.

How about extending `enum` for tagged unions? It won't be solved by any JS proposals and it would be extending an already existing mechanism. Or is that invasive too?

**Comment by RyanCavanaugh** [comment]
See also #36336, #42497

There are very compact ways to write tagged unions today if that's the intent:
```ts
interface Taggo {
    "alpha": {
        a: number,
        b: string
    };
    "beta": {
        c: boolean;
    };
    "gamma": {
        d: object;
    };
}

type ToADT<T> = {
    [K in keyof T]: {
        kind: K
    } & T[K];
}[keyof T]

type M = ToADT<Taggo>;
declare const m: ToADT<Taggo>;
switch(m.kind) {
    case "alpha":
        m.a;
        break;
    case "gamma":
        m.d;
}
```

**Comment by anilanar** [comment]
That doesn't work with a generic `Taggo` though.
