### ISSUE TITLE
Missing expandEntityReferences in document.createTreeWalker

### ISSUE THREAD

**Issue by ststeiger** [microsoft/TypeScript#46995]
# Bug Report
Typescript 4.5

Defines:
createTreeWalker(root: Node, whatToShow?: number, filter?: NodeFilter | null): TreeWalker;

It's missing the expandEntityReferences parameter. 
https://developer.mozilla.org/en-US/docs/Web/API/Document/createTreeWalker

**Comment by RyanCavanaugh** [comment]
This parameter is deprecated and no longer appears in the spec, which is what the lib is generated from.
