### ISSUE TITLE
Hover on `as const` shows `type const = /*unresolved*/ any` in 4.5.2

### ISSUE THREAD

**Issue by yume-chan** [microsoft/TypeScript#46998]
# Bug Report

### 🔎 Search Terms

as const

### 🕗 Version & Regression Information

- This changed between versions 4.4.4 and 4.5.2

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.5.2#code/CwJgBAhgzmDGD2A7KAXA3EA)

### 💻 Code

```ts
42 as const
```

Hover on `const`

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/1330321/144534197-ac0a632f-7efe-4c80-8215-0e28a6100171.png)

### 🙂 Expected behavior

Shows `type const  = 42` or nothing as in 4.4.4

This also affects Semantic Highlighting in vscode microsoft/vscode#138362

**Comment by jakebailey** [comment]
See also #47043; the Playground appears to have a different hover implementation, as it allows you to hover on `const`, wheras VS Code does not; if we want to fix #47043 and have `const` have the keyword type, then we probably need to ensure that the same thing happens to `const` as does to `as`, not emit a type like 4.5 or #47000.

**Comment by jakebailey** [comment]
Hm, this is even more confusing. Switch the playground back to 4.4, and you get no hover, whereas 4.5 does have the (wrong). But, testing #47043 with the linked PR, no matter what I do, the token is always a "type".

The hover doesn't work on my machine, but @DanielRosenwasser tried it on his and the hover worked.

**Comment by jakebailey** [comment]
Seems like the hover is present in VS Code's insiders, just not on the stable build, which explains the discrepancy.

Hopefully this means that the semantic tokenization takes a different path so #47043 can be fixed separately, but thankfully it at least means the linked PR is good to go as it's not impacted.
