### ISSUE TITLE
Allow `readonly` / `const` keyword for class member function definitions

### ISSUE THREAD

**Issue by thw0rted** [microsoft/TypeScript#47003]
# Suggestion

## 🔍 Search Terms

readonly class member function assign overwrite

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Class definitions should provide a way to protect member function definitions from accidentally being overwritten.

The syntax `public readonly callback() { ... }` is currently an error, as is `public const callback() { ...}`.  I can see where some people might get confused or surprised about the use of one of these keywords, thinking it applies to the return value, so I'm open to other suggestions -- but frankly, the current behavior is surprising.

## 📃 Motivating Example

This is currently valid code:

````ts
class Foo {
  callback() { ... }
  start() {
    let callback = x => { this.doX(x); };
    if (someCondition) {
      // Oops, I meant to type "callback = ..."
      this.callback = y => { this.doY(y); };
      // I just overwrote the implementation of `Foo#callback`
    }
    library.doThing(callback);
  }
}
````

As far as I can tell, the only way to catch the above logic error is to declare all methods of `Foo` as `const` member variables, e.g.

````ts
class Foo {
  public readonly callback;
  constructor() {
    this.callback = (function() { ... }).bind(this);
  }
}
````

## 💻 Use Cases

This probably doesn't actually come up *that* often in the wild, but it can produce difficult-to-trace logic errors at runtime when it does.  The workaround posted in the previous section is unwieldy, and some syntactic sugar would make the feature more likely to be used.

**Comment by RyanCavanaugh** [comment]
#22315. Missing search term - these are commonly called "methods"

**Comment by thw0rted** [comment]
Thanks @RyanCavanaugh , I could *swear* I'd tried "method" as well but maybe it was part of some other combination of terms.

That other issue looks like it was tagged "awaiting feedback" nearly 3 years ago.  It has received 34 thumbs-up reactions and garnered a bit of discussion, but it doesn't look like the team has participated at all.  Is this on the radar?  Is the problem not widespread enough to take any action?

**Comment by RyanCavanaugh** [comment]
34 votes in 3 years is pretty low-traffic as far as suggestions go, especially for one with fairly invasive syntax changes. I don't think action here is particularly likely.

**Comment by thw0rted** [comment]
That's more than fair.  I may take this over to typescript-eslint and see if they think it's worth a rule.  On reflection, it might feel more like an "antipattern" than a language feature anyway.
