### ISSUE TITLE
No path completions in `--module nodenext`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47011]
```ts

//// @filename: ./node_modules/dependency/package.json
//// {
////     "type": "module",
////     "name": "dependency",
////     "version": "1.0.0"
////     "exports": {
////         ".": {
////             "types": "./lib/index.d.ts",
////         }
////         "./lol": {
////             "types": "./lib/lol.d.ts",
////         }
////     }
//// }

//// @filename: ./node_modules/dependency/lib/index.d.ts
//// export function fooFromIndex(): void;

//// @filename: ./node_modules/dependency/lib/lol.d.ts
//// export function fooFromLol(): void;

//// @filename: ./package.json
//// {
////     "type": "module",
////     "dependencies": {
////         "dependency": "^1.0.0"
////     }
//// }

//// @filename: ./src/foo.ts
//// import { indexFoo } from "/**/";
```

**Comment by dzearing** [comment]
Fixing this would be so valuable to complete the picture. Thanks for logging @DanielRosenwasser!

Basically if we build a library with 2 exports explicitly defined, autocomplete can help consumers know which 2 exports to choose from. This is critical for making deep imports a first class citizen that can be enforced and managed. Otherwise it's a guessing game.

**Comment by dzearing** [comment]
Some things to consider that I hadn't earlier; 

exports maps support conditionals:

```js
{
  exports: {
    '.': 'index.js',
    test: {
        './test': 'test.js'
    }
}
```

I believe this is valid; if the `test` condition is defined, then `/test` is a valid import. So there might need to be a way to support this. Maybe. I don't know what that looks like, from an IDE perspective.

**Comment by weswigham** [comment]
You can't mix conditions and paths in the top level of the export map (or at any level) - that's an invalid export map. Specifically, the specification requires all keys start with `.` (and are therefore subpaths), or not start with `.` (and are therefore conditions). Incidentally, this means you can't have a condition that starts with `.`.
