### ISSUE TITLE
ReturnType doesn't work consistently when used as a return type of a method with generics

### ISSUE THREAD

**Issue by lukasz-zaroda** [microsoft/TypeScript#47013]
# Bug Report

I noticed that when I use ReturnType as a return type of a method, and I put into it a callback type being inside of a different type, and accessed using generics, I'm getting a palette of inconsistent errors. They change even based on how deeply nested is my callback type.

### 🔎 Search Terms

ReturnType on a callback in a nested property doesn't work

### 🕗 Version & Regression Information

It exists in all versions available in Playground.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ReturnType

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.2#code/JYOwLgpgTgZghgYwgAgPIggGQgNwgGwBUBPABwgGdkBvAKGQeQHIwyIBGJgLmQCMB7fvghwQAGnqMWbAEzdkFMFFABzCQF9atVuTQZseImwoBhOPny9EAayoBeGpIYBtaxGLJQyN8X4w9WLgEJOQUALo8ABT8vABWEAhgPKLEAJTIdgB8AQbBxq7uYQDctJq0oJCwiCiEAO78ufgUIZSOjMw6HPJ07e3S5OwA+pw8AkIi4k7I6hJ9nXI8Pb0M-RAygwsKSqqzjDOlWp3IdQ1BTS2m5pY29m2MBcTsniDe7n7H9Y3NxhF3yw8yZ6vXz+E5fC4PdhhX7ROIJJLIFLpLIfU6Gb6hSFhAHFKbqEr4rQIfBwChUFoABSg-BwwAAJtBHFNSMocHBIMgEFcrAhrABZOCkdCBQw8YWNC5mCw82wZP69TrsKIxeKJZHZeBNCC7ZbzZVwtUZbIsShgJg66YlZms9koLnSmwC0hgs4UHgu9GS7k3OVLXVsJXy5YMRXDfWqsDq5CaijaqbtfbB5B6oPB+YbcPwqMmxTm+N7C2E5kAV14+GACGQUGLICl1154rOAB5CMgIAAPSAgOlUHzvRuGL0O3kUTKRemBwipHgAJQgYGLUBALSbA7yoTrMoozkIYWyft6CH4IEUnO9vLlYAAFsAKAA6e31-mCtf4ZwT3H5hhQeeLl6PmVIiYAAvYCmFSEok16AB6aCAD0EMQhCv2WWCAFEZxnVAZ2QAB1K8PBaABlBBlFIMAzxAEB+Ao0AYEZI8oB-RIq1-JdkzYZAr2gbVPH8YAKK5F46IY89rA43QvGvFBywwZAAFYAAYAH5kDnBd2KOW9EUSYsrg8Ug4CgCj3jgM9h3Ezo72svEtHaUhS3LSsVHnTcbFfFs207CBu17N5-FfIcn1Hcc6UnaccjOIKtx3MJU2-NiXmvW8HzEp1X3fMLimQWDkAACR4iSUG0xjmLAfAPBEpiIDpO9bJLMsKyrGs3N5D0CAoTyOy7HtgXedrzmMVrbDEY5W26nzer7UFPldaKbliscJ3dUb6Rkd0p1nRKVwGjFKGG7ddx3Xd9xQqDzouy6ruum7bru+6cvgpDnpe163uQh7Pq+76ft+m70Mw7C8KvdkmCoFR+FUZBjy4njlJQo8T0EsTLxve8AMdQVdsyqFMpkT8kx-DT-zEoDQPAyDLtgt6zvaAGsJwgBBbtYZ-VS8v4WpPCoATkGo5GLDgMsIHhhM7MYBzGuc1yxN2rrvN8vqZrRDr5pHUbCHGhWpv81FwSGsTDr3ULJ1Wul1rGiLdrV2xYuOuKD3aIm-2TNHUosp1sY-PHstygqfyK7nOX4arEgq556Oq2r6s0RHTxZGl6Wgd02CpROGSgOUMC5ylqVpDPIggolj1PMZhFEAA1cxiw4UZBHLl4HAT-PoDvatazE18gMVCnaDjijFGUEAVCr-Aa8DQeoabvOk6gNuWs7-Qzm72Re77kuKLLiZhsDWEI2SEA0iNPh64mOVm9nu8XLAYau9WTgi-7rYh5UHfM0SA+j5RSfh-PmeM6vjLCyd95hr3XkjE+4xK7VzWHXKBjdkAXwAe3Yau0V4DHNB0AMwxe5Px-iPGBFt8F-3Tq3FBstZronQWsTBqx1hyCLuA0up9RDDQtnveEn8oxb1ECQluc9r6oMoR1ahnBRr3xwY-Dez9VBsPfgiJEx9iHT1IQIoBT40F0NoemBhRQgA)

### 💻 Code

```ts
interface OneLevelTypes {
    'type1': boolean,
    'type2': string,
}

type OneLevelTypesCallbacks = {
    [key in keyof OneLevelTypes]: (object: any) => OneLevelTypes[key];
}

interface TwoLevelsTypes {
    'type1': {
        'type1_1': boolean,
    },
    'type2': {
        'type2_2': string,
    },
}

type TwoLevelsTypesCallbacks = {
    [key1 in keyof TwoLevelsTypes]: {
        [key2 in keyof TwoLevelsTypes[key1]]: (object: any) => TwoLevelsTypes[key1][key2];
    };
};

class TypeProvider {

    private callbackMapOneLevel: OneLevelTypesCallbacks = {
        type1: (object) => false,
        type2: (object) => 'test',
    };

    private callbackMapTwoLevels: TwoLevelsTypesCallbacks = {
        type1: {
            type1_1: (object) => false,
        },
        type2: {
            type2_2: (object) => 'test',
        },
    };

    public runCallbackOneLevel<T extends keyof OneLevelTypesCallbacks>(id1: T): ReturnType<OneLevelTypesCallbacks[T]> {
        const callback = this.callbackMapOneLevel[id1];

        return callback('zz');
             //^^^^^^^^
             //ERROR Why TypeScript cannot infer correct return type here, if it can infer callback type in the line 50? Return type is actually part of a callback type...
    }

    public getCallbackOneLevel<T extends keyof OneLevelTypesCallbacks>(id1: T): OneLevelTypesCallbacks[T] {
        return this.callbackMapOneLevel[id1]; // Here type is correctly inferred.
    }

    public runCallbackTwoLevels<T extends keyof TwoLevelsTypesCallbacks, TT extends keyof TwoLevelsTypesCallbacks[T]>(id1: T, id2: TT): ReturnType<TwoLevelsTypesCallbacks[T][TT]> {
                                                                                                                                                //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                                                                                                //ERROR What's going on here?
        const callback = this.callbackMapTwoLevels[id1][id2];

        return callback('zz');
             //^^^^^^^^
             //ERROR And here? How is it not callable?
    }

    public getCallbackTwoLevels<T extends keyof TwoLevelsTypesCallbacks, TT extends keyof TwoLevelsTypesCallbacks[T]>(id1: T, id2: TT): TwoLevelsTypesCallbacks[T][TT] {
        return this.callbackMapTwoLevels[id1][id2]; // Here type is correctly inferred.
    }

}
```

### 🙁 Actual behavior

`ReturnType` doesn't work consistently as a return type of a method.

### 🙂 Expected behavior

Above code should compile. `ReturnType` should work consistently in all showcased situations.

**Comment by RyanCavanaugh** [comment]
This doesn't have anything to do with `ReturnType` per se, but rather how operations involving lookup types are / are not deferred. A related discussion can be found here: https://github.com/microsoft/TypeScript/issues/46991#issuecomment-985737073

The simplest way to think about it is this program
```ts
const p = {
    a: () => "",
    b: () => 1
};
function fn<T extends keyof typeof p>(name: T) {
    const x = p[name]();
    return x;
}
```
We have to assign some type to `x`. There are *many correct answers* to choose from:
 * `string | boolean`
 * `ReturnType<(typeof p)['a']> | ReturnType<(typeof p)['b']>`
 * `ReturnType<(typeof p[keyof typeof p]>`
 * `ReturnType<(keyof typeof p)[T]>`

Now a question is, should this code be legal?
```ts
const p = {
    a: () => "",
    b: () => 1
};
function fn<T extends keyof typeof p>(name: T) {
    const x = p[name]();
    if (typeof x === 'string') s.toLowerCase();
    return x;
}
```
A type like `ReturnType<(keyof typeof p)[T]>` can't be narrowed; it is not a union, so this code fails if that's the type we give x.

So in this case we choose to produce the concrete form `string | boolean` since that corresponds to behavior that is reasonable simple and still very much correct for cases where narrowing is needed. In some of the other cases you have here, there is indirection that prevents this resolution from happening, which means some codepaths you could write there which you *would* expect to work won't. It's a trade-off.

**Comment by lukasz-zaroda** [comment]
Thank you for this explanation. I assumed that if I learn all TypeScript's building blocks, I will be able to use them as I want to do what I want, but it seems not to be the case. Because TypeScript seems to not tolerate too much indirection, I'm constantly hitting roadblocks. It seems to me that it's impossible to design anything without a lot of trials and errors, to learn what TypeScript actually allows in specific contexts. That's a bit horrifying to be honest, but at least now I have better mindset. Thank you.
