### ISSUE TITLE
Error message should be fixed for ambient module inside namespace

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4701]
```TypeScript
namespace n {
    declare module "m" {
        var x;
    }
}
```

Currently: `TS2435: Ambient modules cannot be nested in other modules.`
Suggested: `TS2435: Ambient modules cannot be nested in other modules or namespaces.`

**Comment by mhegazy** [comment]
Feel free to send a PR for this.
