### ISSUE TITLE
Decorators Class Assignment `design:paramtypes`

### ISSUE THREAD

**Issue by LeonardSSH** [microsoft/TypeScript#47015]
# Suggestion

Decorators's metadata `'design:paramtypes'` to first check whether or not the class assigned as type in the method parameters is defined.

## 🔍 Search Terms

`paramtypes`, `class assignment`, `decorators metadata`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Check if the class exists before to be assigned to the decorator metadata `design:paramtypes`.

## 📃 Motivating Example

```ts
declare class Car { }

export const Bought = (target: Target, propertyKey: PropertyKey, descriptor: PropertyDescriptor) => {};

class People {
	@Bought
	public boughtCar(car: Car) {}
}
```
Will be transpiled into:
```js
const Bought = (target, propertyKey, descriptor) => { };

class People {
    boughtCar(car) { }
}

__decorate([
    Bought,
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [Car]), // <-- ISSUE 😡
    __metadata("design:returntype", void 0)
], People.prototype, "boughtCar", null);
```

As you can see, we are just declaring a class that theoretically does not exist and is only used for type. But, typescript sees it as a real class and therefore attributes it to `design:paramtypes`.

### What's the solution?

The solution has already been implemented by @kdy1 in [SWC](https://github.com/swc-project/swc), that's where I got my inspiration from.

```js
__decorate([
    Bought,
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [typeof Car === "undefined" ? Object : Car]), // <-- FIXED 😏
    __metadata("design:returntype", void 0)
], People.prototype, "boughtCar", null);
```

See in action: [SWC Playground](https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA0WOQQqDMBBF1w3kDn%2Bp4AkUS2m768ZFLxDjYIXUhMkIFfHuTRXqZub%2FGWb%2B68g6w4RUY8TNMBatTm%2FfkSsRhYexr7RatdKKPsGzwPoxCq5%2B6l%2BCGpkY7klKPLdeILAPxDI%2FaC7RHKZAR9HyEMTzsbj%2FZznqM5a1%2BkXtNA354GgDuux5SYWpdYNFu%2FnEm1mT3iWRp%2BNE%2BgXeBNqZ0QAAAA%3D%3D&config=H4sIAAAAAAAAA02OsQ6DMAxE%2F8UzQ8vI3JWPsIJBoCSObCM1Qvx7Ewqlm3W%2Be3cbLOqg2yChKEm9NEfDN3RgOZE6mZNBA6ZFGtErNTCQY0FjUehMVtrLWzDqyBIqwdOELr8u19f0F%2BvJcEDDO40ykZVK0vbRPkudZ1b6FYY5zmOuaMchCaneL4yTv5x7YQUe1ipsx%2F7CLJHAcVHYb9AZnrU%2F3ceQD4rj4nINAQAA)

## 💻 Use Cases

In an environment where you don't have predefined library types definitions, and you have to write your own. (e.g [ragemp-types](https://github.com/LeonardSSH/ragemp-types))

**Comment by RyanCavanaugh** [comment]
But that's what `interface Car { }` does, and if the *value* `Car` doesn't exist, then the correct declaration is `interface Car { }`. Writing `declare class Car { }` when there's no `Car` value opens you up to a wide variety of runtime errors, including this one.

**Comment by LeonardSSH** [comment]
I totally agree with what you say, and so would I, but my environment doesn't allow it.

Why?

'Cause the project I'm working on is a multiplayer mod, and it has these classes written internally, and I don't have access to those classes or interfaces, so I wrote my interfaces myself to benefit from type-safe.

e.g
```ts
// https://github.com/LeonardSSH/ragemp-types/blob/main/packages/server/index.d.ts
declare class PlayerMp extends EntityMp { }

declare class PlayerMpPool extends EntityMpPool<PlayerMp> { }

declare interface Mp {
  Player: typeof PlayerMp;
  players: PlayerMpPool;

  joaat(str: string): number;
  joaat(strs: string[]): number[];
}

declare const mp: Mp;
```

#### Usage:
```ts
mp.Player.prototype.myMethod = function myMethod() {
    ...
}

mp.players.call(...);

class House {
  @On({ name: 'playerEnterColshape' })
  public playerEnterColshape(player: PlayerMp) { // <--- THE ABOVE ISSUE
    player.position = ....
    // blah blah
  }
}

// etc...
```

Do you understand?

They're just some types.

Their logic is written in C++ and then made into an engine (V8) for use in Node... details, anyway.

*I don't know if I expressed myself very well.*

**Comment by RyanCavanaugh** [comment]
I'm not really following - there's always a value-free equivalent declaration.
```ts
declare interface PlayerMp extends EntityMp { }

declare interface PlayerMpPool extends EntityMpPool<PlayerMp> { }

declare interface Mp {
  Player: new() => PlayerMp;
  players: PlayerMpPool;

  joaat(str: string): number;
  joaat(strs: string[]): number[];
}

declare const mp: Mp;
```

**Comment by LeonardSSH** [comment]
![image](https://user-images.githubusercontent.com/35312043/144684836-6a2c38b1-12a7-4b84-89bd-5abc945b3511.png)

**Comment by LeonardSSH** [comment]
With your method, you lose the other methods and properties of the `PlayerMp` class.

without class
![](https://i.imgur.com/EDQnHjs.gif)

with class
![](https://i.imgur.com/CCPj0qs.gif)

**Comment by RyanCavanaugh** [comment]
These are all solveable in user land by writing out the `prototype` member.
