### ISSUE TITLE
function overload in type

### ISSUE THREAD

**Issue by andrei9669** [microsoft/TypeScript#47012]
# Bug Report

### 🔎 Search Terms

call signature, function overload, type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about function overload

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211203#code/MYGwhgzhAEAiYBcwBkwE8CmAnaBvAUNNOAHYDmAXNBAlgJbn6HTAD2JNWArsAq1gApSlarQZkAlHmZEEACzoQAdMOgBeYmEZEAvvj342HBNAAmIddBIYA7nEQp02AQHIMJFxIDcTBGgAOGNAAwmAgIABCYMAA1gA8ACoAfJYCpg6omFhU8EiZ2FJqKQk++ABmXCS8dOzQCBg0AhI5GU5YPhVVCDUkdQ0IiUkCwGEgAEbRMVSh4VGxg83QJeWV1bX1NIPDoxOxAPzTo3PxyVIERHRl0AIAhCPhuzFnMtBYGAhcWL3mPrrMbx8viwdpM0iBvPomBgAB7+fgmPyBaAAZSQ9Us52gW3u40mh1mkwWVGWRG2D0mB2glVMGDKDAwpkWuUcWR8OlKRhofRoACYqKjEEENGTcbFCilMZdrncQWLpEQiADPt8QL9oHpFe9lcDybEwRCDJyTFcNBsEE0fEboGNLGaBE11CkXHIMOFWNAbPwQKZPJb2FzgLb+vbxdAAMwQwz+408oO8i1R4zW2Om-o8kOO6DO10gd2erDe32JgMp7kIdMOorhyNW4BjABiJHxkUJnHEKWF6TybVDXZZ2BUWjIHOj1rAOFTjTrje8QA)

### 💻 Code

```ts
type CallBack<T> = (dataLayer: DataLayer) => T;

export type State = {
  <T>(callback: CallBack<T>): T;
  (callback?: undefined): DataLayer;
};

const test2: State = (callback) => { // callback gives error: Parameter 'callback' implicitly has an 'any' type.
  if (!callback) {
    return dl;
  }
  return callback(dl);
}
// but the function's return types are correct.
const f2 = test2();  // DataLayer
const b2 = test2(() => 'hello world'); // string

```

### 🙁 Actual behavior

test2 function parameter callback gives an error that it implicitly has an 'any' type.
funny thing is that f2 and b2 have the correct return type.

### 🙂 Expected behavior

I expected it to work the same way as regular function overload, the function `test` shows a working example in ts playground

**Comment by RyanCavanaugh** [comment]
I'm not sure what "work" should mean in this context? The parameter can't implicitly be typed as `T` (there's no generic parameter name in scope) and can't be implicitly typed as `undefined` (since it could be any value).

**Comment by andrei9669** [comment]
> (there's no generic parameter name in scope)
what do you mean by this?

my issue is that if you use the `test2` function, the return types are correct, it "works". But in the function implementation, the callback has implicitly type any but it should be either `CallBack<T>` or `undefined`

**Comment by andrei9669** [comment]
okay, I had some help and found the issue, it seems the type has to be like this
```
export type State = {
  <T>(callback: CallBack<T>): T;
  <T>(callback?: undefined): DataLayer;
};
```
no idea why the <T> has to be for the second one but hey, at least it works.
