### ISSUE TITLE
Type constraints lost when using Parameters<>

### ISSUE THREAD

**Issue by xbc5** [microsoft/TypeScript#47029]
# Bug Report

### 🔎 Search Terms

Pararameters
constrained Paramaters
conditional Parameters

### 🕗 Version & Regression Information

I first noticed this yesterday (05/12/2021)
- I was unable to test this on prior versions because I am lazy and make assumptions.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAysATlAvFA3lAZggLigGdUBLAOwHMoBfAKFEigCEBDFAOQFcBbDbFABGHIhT5CIaBvQDGcCqTwUBAHgAqUCAA9gECgBNiJctSgAfKON6SUAPgAUHKgEYi6gDRRnAJndbdfSMTFEoaAH5YBGQ0InYuPigASgw7bHooKHlFOAAbCAA6XLgqJxRXL18k+hlspVwKHwEHAtbnYiIABQ42Xgg9FGJVJgg4XGU7FNTlFrby4mr6AHolqDAevoGoEayFUhQ2SmBjAHc4FABrKAALKWgoegaHFy8cERQiFzoplas4LRQKHOlWMOkgsj0BkeFGerzwhCgACJ9ojvlBflIgSgQQFwZDPlAyMZrLYSP83hw6LiIBCIFDlqshNxgFADP8KHAWWdLlAAG5kNhQboHTZSIZ2aE+WGCfBwIjI1Co2gpX7EXrQYDXMJeJksjkArEeehAA)

### 💻 Code

```ts
type FooStr = { foo: string }
type BarNum = { bar: number }

const fn = <T extends string | number>(arg1: T, arg2: T extends string ? FooStr : BarNum ) => {
  console.log(arg1, arg2)
}

const fn2 = (...args: Parameters<typeof fn>)  => fn(...args)

// parameter type constraints work here  
fn(1, { bar: 1 })  // no error, as expected
fn(1, { foo: "str" }) // error, as expected: 1 is number so { bar } expected

// but do not work via Parameters<>
fn2(1, { foo: "str" }) // same thing, but no error,
```

### 🙁 Actual behavior

The conditional constraints of `fn` is lost when using `fn2(...args: Parameters<typeof fn>)`

### 🙂 Expected behavior

The preservation of exact parameter typings when using `Parameters<>`.

**Comment by RyanCavanaugh** [comment]
>  because I am lazy and make assumptions.

Gotta respect the honesty 😅

`Parameters<T>` has no way to produce a generic type in this context, so the function is resolved in terms of its constraint.

This isn't a loss of soundness since you're also able to call `fn` this way, just with an explicit type parameter:
```ts
fn<string | number>(1, { foo: "str" });
fn2(1, { foo: "str" });
```
