### ISSUE TITLE
union type cannot be generics function argument

### ISSUE THREAD

**Issue by hzura** [microsoft/TypeScript#47032]
# Bug Report

### 🔎 Search Terms

Union Type, Generics

### 🕗 Version & Regression Information

Typescript: 4.5.2
- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generics and Union Type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgMowoxLZFICiAZvUhnAL5z1QQhwDkUqDLwDcAKFHAAdpSj10SOABUkhGAA0APIoB8uUXDgATCigBcSsQYGTDSKOYAUx8ucUBKOAF5dk-CABGdmKs4vT4khjAEJJwALIAngDC3CDRAGLhaFraDnjOKNjWtlBsrirq2R44+nACMPhQMRraOEV2TiZurBoA9NrB4jDxYAog8YrDCp5K5Zq+AXa6AD4zqpqqUFIA5v3iaNGqcGlecA4e3noG+5KHANoAXtjEMABaALonNGQUSBpjEyMcnkTOYAIyFJA2OyOMxweaBKDnXSgthuSxwa53GhQACSkjA+CwcGeAFViLj8YSPtMvuRKBp4YsHKC0TUaAwmBgHGcvLpqgYDMB6KdsXiCfBPJK4CzLgKDM8XrkjCDpRCofZTrDGYjedLUeiDOwkAAbYiyuUKpX5cy8UG8NXFGHmDbbJF61isuUhQ3YW6iykwN6e2pIeqNOAaBLJECpSQZCK4AB0yfu7D6wWEPR6cXiGIgtjgWwgKjgAAs7EggA)

### 💻 Code

```ts
import React, { useState, useEffect } from 'react';

interface TestX<T> {
  data: T;
  render: (data: T) => number;
}

function MyCommonFunc<T>({ data, render }: TestX<T>) {
  return <>{render(data)}</>;
}

type myType = TestX<number> | TestX<string>;

const F = () => {
  const [z, setZ] = useState<myType>({ data: 1, render: (a: number) => 1 });
  const [userInput, setUserInput] = useState<number>(1);
  useEffect(() => {
    if (userInput === 1) {
      setZ({ data: 1, render: (a: number) => 1 });
    } else {
      setZ({ data: '1', render: (a: string) => 1 });
    }
  }, [userInput]);
  return <MyCommonFunc {...z} />;
};

// other small simple
function myF<T>(data1: { data: T }) {
  return '';
}

let x: { data: number } | { data: string } = { data: '1' };
if ((window as any).user === 1) {
  x = { data: 1 };
}
myF(x);
```

### 🙁 Actual behavior

Typescript throw errs below:
```
Type '{ data: number; render: (data: number) => number; } | { data: string; render: (data: string) => number; }' is not assignable to type 'IntrinsicAttributes & TestX<number>'.
  Type '{ data: string; render: (data: string) => number; }' is not assignable to type 'TestX<number>'.
    Types of property 'data' are incompatible.
      Type 'string' is not assignable to type 'number'.
```
It seems like MyCommonFunc infer the generics ```T``` should be number directly, and then the union type argument is not suitable to ```TestX<number>```

But actually I think when the argument is a union type, it should check whether each of the union type can satisfatied generics. 

And if it's word as intended, what should I do to solve this problem without change the structure of the program? Use type guard can somehow solve this problem, but it need lots of ```if-else```. 

### 🙂 Expected behavior

no errs.

**Comment by RyanCavanaugh** [comment]
> But actually I think when the argument is a union type, it should check whether each of the union type can satisfatied generics.

You made a good observation that the only way to check if the `<MyCommonFunc {...z}>` call is valid is by seeing if every member of the union is a valid call, because that is indeed the crux of the issue -- let's say you wrote
```ts
func(a, b, c);
```
where `a`, `b`, and `c` were members of a 64-member enum (as would not be unlikely; we have enums with hundreds of members). That implies TypeScript would have to check all 262,144 possible variations of `a`, `b`, and `c` -- this is simply impractical from a performance perspective.
