### ISSUE TITLE
`tsc` with `--watch` is running `checkSourceFile` and `transformNodes` unnecessarily when using `declaration: true`

### ISSUE THREAD

**Issue by jamesflightwsf** [microsoft/TypeScript#47034]
# Bug Report

### 🔎 Search Terms
tsc, --watch, declaration, performance

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (4.3.4, 4.5.2 and next)

### 🙁 Actual behavior

When using both `declaration: true` and `--watch` together, the build is much slower on save than if `declaration: false`. This is true even if the file that has been changed has no imports, and is not imported by any other files.

`--generateTrace` shows that this is because when `declaration: true` is set, tsc is running `checkSourceFile` and `transformNodes` for all files in the project, regardless of if they have changed or have any dependency on them.

### 🙂 Expected behavior

I would expect tsc to skip `checkSourceFile` and `transformNodes` in subsequent runs for any files that have not changed or are not depended on, and hence build much faster (as is the behaviour when `declaration: false`).

**Comment by DanielRosenwasser** [comment]
Hm - someone with more experience with `--incremental` should chime in, but the checker doesn't have the ability to reuse work from a previous run, and may need to jump into an arbitrary file for some information. Still, I would have thought that we don't try to do a *full* type-check - that *sounds* like a bug.

Another thing we could try to do is jump to the corresponding `.d.ts` file instead of the `.ts` file, similar to what project references does (did?). That might add a lot of memory pressure though.

**Comment by jamesflightwsf** [comment]
On further digging in my project, I'm having a very similar issue when running in `--build` mode.

My project is structured as follows:
 - /web
  - /api
  - /shared (this project is the one with `declaration: true` as it's a project reference)
 
I've compared the traces for:
 1. building the whole project in `--build` mode
 2. isolating down to just `/web` and `/shared` and running in `--build` mode with a temporary `tsconfig.json` file I made specially, with no project references

In example 1, when I save a file in `/web` (a new `temp.ts` file with almost no code - one exported string) `checkSourceFile` is being run over the whole project, just like in my original issue.
In example 2, `checkSourceFile` is only being run on `temp.ts`, as expected.

It's as if the presence of of the `declaration: true` is changing the 'watch strategy' completely, even when saving a file in the other project... I originally assumed I'd misconfigured something as this was so strange, but I can't see how - happy to be wrong here though of course.

**Comment by sheetalkamat** [comment]
There are multiple factors here. when there is change to a file, the declaration and semantic diagnostics can change for any file that imports the changed file directly or indirectly (through other imports) So you would need to emit d.ts for these files again. And you would need to check those source files again.

**Comment by sheetalkamat** [comment]
Please share concrete repro steps to check whether what you are seeing is issue or not. Thanks.
