### ISSUE TITLE
Common HTML named entity handled badly within JSX (.tsx) files

### ISSUE THREAD

**Issue by tshinnic** [microsoft/TypeScript#47030]
# Bug Report

I've encountered a known HTML named entity that is not recognized by TSC when present within a React JSX file (aka .tsx), which is instead then spat out unchanged into the HTML page in its original entity text form.

Specifically, using ```&numsp;``` within JSX code does not work, with "&&zwnj;numsp;" being displayed in the browser window. ```&numsp;``` does work when placed directly within ```index.html```, and the numeric form ```&#x2007;``` works everywhere.

Looking at the intersection between Unicode "General Punctuation" (2000–206F) sections "Spaces" (2000-200A) and "Format Characters" (200B-200F) [chart@Unicode](https://www.unicode.org/charts/PDF/U2000.pdf)...

and the list of known HTML entity names [table@whatwg](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references)...

and looking at the definition of HTML entity names known to TSC [TypeScript/src/compiler/transformers/jsx.ts](https://github.com/microsoft/TypeScript/blob/1ade73df2bf3e83085ca4647d0a3339abe3f869b/src/compiler/transformers/jsx.ts#L543-L797)...

TSC has 7 of these named HTML entities defined:
```
        ensp: 0x2002,
        emsp: 0x2003,
        thinsp: 0x2009,
        zwnj: 0x200C,
        zwj: 0x200D,
        lrm: 0x200E,
        rlm: 0x200F,
```
I have used 6 of these in projects.

The other known HTML entity names for 'spaces' are:
```
    2004   emsp13
    2005   emsp14
    2007   numsp
    2008   puncsp
    200A   hairsp
    200B   ZeroWidthSpace
```
I have used the last 4 in projects as well, the last only for experiments.

I believe it is true that the list of entities in ```jsx.ts``` has not changed since that file was created [rbuckton committed on Feb 16, 2016](https://github.com/microsoft/TypeScript/commit/6c0551f86788e3c3df305dbed99b2991c59a5802#diff-dc11140227232feb0bf40ae98c6aecacb6eb20ff9b9e4593370566292ba418ec)  (ca. line 232)

And above I have identified named entities missing from only two very small sections within Unicode.

It is certainly true that the workaround for entity names missing from TSC is to use the numeric entity references, such as ```&#x2007;```, but then matters of 'usability', 'cryptic', 'confusing', etc. arise.

I am wondering what policy you would use in deciding whether to include or not include additional entity names. I am hoping you can be somewhat less severe than WHATWG's ["additions are bad"](https://github.com/whatwg/html/blob/main/FAQ.md#html-should-add-more-named-character-references) stance.

In any case, documentation somewhere that TSC does not handle 'every' HTML named entity would be useful. Such as "CounterClockwiseContourIntegral" or "leftrightsquigarrow" or "angrtvbd"...

### 🔎 Search Terms

entity numsp thinsp HTML

### 🕗 Version & Regression Information

TSC 4.5.2

Inspecting source on Github shows this code section in jsx.ts has not changed in (4?) years.

### 🙁 Actual behavior

HTML entity &&zwnj;numsp; when present in a JSX file is echoed unchanged to web page and displayed there as &&zwnj;numsp;

### 🙂 Expected behavior

use of &&zwnj;numsp; should have exactly the same result as &&zwnj;#x2007; , instead JSX (.tsx) source containing for example
```
      !&numsp;!&#x2007;!
      !&thinsp;!&#x2009;!
```
appears in browser window as
```
!&numsp;! ! ! ! !
```
which is not surprising given the generated JS code has:
```
children:[Object(s.jsx)(p,{}),Object(s.jsx)("br",{}),"!&numsp;!\u2007! !\u2009!\u2009!"]
```

**Comment by nmain** [comment]
Typescript appears to match Babel here:

[Babel REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DwEwlgbgfAZAdgVwLYGcAOBuYB6c0MBQoksANgC5a4mFA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.16.4&externalPlugins=%40babel%2Fplugin-syntax-dynamic-import%407.8.3&assumptions=%7B%7D)

[Typescript Playground](https://www.typescriptlang.org/play?#code/DwEwlgbgfAZAdgVwLYGcAOBuYB6c0MCwAUKJLADYAuWuZhRQA)

**Comment by tshinnic** [comment]
Interesting, yes, I see the original commit for Babel's [src/plugins/jsx/xhtml.js](https://github.com/babel/babel/commit/423d8c510def2c6ac392c9f545f37ea804f0f2c3#diff-309687105c1c2cd2858cafa4d120eb5c353021f3693c396b057674e3ddd1a289) 7(?) years ago, since then renamed to [packages/babel-parser/src/plugins/jsx/xhtml.js](https://github.com/babel/babel/blob/main/packages/babel-parser/src/plugins/jsx/xhtml.js)

The same content is found both there and [src/compiler/transformers/jsx.ts](https://github.com/microsoft/TypeScript/blob/1ade73df2bf3e83085ca4647d0a3339abe3f869b/src/compiler/transformers/jsx.ts#L543-L797).  Same number of entities (253) and same ordering. One can assume one is derived from the other, or both are derived from the same third source.

Ah, I think "from where" is solved. The list of entities contains all the named entities from [**HTML 4.01**](https://www.w3.org/TR/1999/REC-html401-19991224/sgml/entities.html) with the addition of `   apos: 0x0027,` 

HTML 4.01 was ... a while ago.  2000?

The number currently supported, 253, indicates the scale of the problem. There are ~2100+ HTML5 entity names for over 1500 separate Unicode characters. TSC nears handling one-eighth of those.

I would not suggest attempting to handle all 2100+ of the HTML named entities. 
Something like the currently supported &&zwnj;aelig; &aelig; is much more likely to be useful than &&zwnj;angrtvbd; &angrtvbd; . 

I would wish a review of named entity support could add names beyond the bare-bones HTML 4.01 list. (Surely somewhere there is data on frequency of entity name usage?) But in any case, documenting that TSC is currently limited to those entity names published 21 years ago would be a good thing (even if potentially embarrassing).

**Comment by MartinJohns** [comment]
TypeScript doesn't own the JSX specification. They'll follow whatever Facebook defines. TypeScript doesn't support a limited set of HTML entities, they support JSX.

There's some traction happening regarding this subject: https://github.com/facebook/jsx/pull/132#issuecomment-984174775

**Comment by RyanCavanaugh** [comment]
> documenting that TSC is currently limited to those entity names published 21 years ago would be a good thing (even if potentially embarrassing).

I find zero embarrassment in exactly matching the behavior of the de facto reference implementation of the JSX transform 😃

The above linked issue would be the place to track change in this behavior. As-is, I don't want people randomly seeing `&dash;` vs `-` in their program depending on whether they use Babel or TypeScript -- that's a far more deleterious problem than being surprised at an entity not being supported at all.

**Comment by RyanCavanaugh** [comment]
This is now the specified behavior https://github.com/facebook/jsx/pull/136
