### ISSUE TITLE
`useUnknownInCatchVariables` does not apply to Promise#catch()

### ISSUE THREAD

**Issue by fregante** [microsoft/TypeScript#47033]
# Bug Report

### 🔎 Search Terms

promise promises catch method function any unknown useUnknownInCatchVariables

### 🕗 Version & Regression Information

All versions with flag, like 4.5.0, including 4.6.0-nightly

```ts
async function veryverynice() {
    fetch('').catch(error => {
        console.log(error)
    })

    try {
        await fetch('')
    } catch (error) {
        console.log(error)
    }
}
```

### ⏯ Playground Link

[4.6.0-nightly playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211205#code/IYZwngdgxgBAZgV2gFwJYHsIwG4FMBOYehEqUuAFAJQwDeAUDE-LslABYUDkXVAdFGBtOBfOnwwAvAD46jZgqiYQ6ADa4+q9AHMKo8VQDc8pgF8j9EzGSE5ChcADuwVMhbDuvK6ZiDhMPXwxfBoGe2YlCBV1TR1A4IsFU3pTIA)

### 💻 Code

```ts
async function veryverynice() {
    fetch('').catch(error => { // any
        console.log(error);
    });

    try {
        await fetch('')
    } catch (error) { // unknown
        console.log(error);
    }
}
```

### 🙁 Actual behavior

`error` in `promise.catch(error => {})` is of type `any`

### 🙂 Expected behavior

`error` in `promise.catch(error => {})` is of type `unknown` 

### 🍝 Related

- https://github.com/microsoft/TypeScript/pull/41013

**Comment by MartinJohns** [comment]
This is not a bug. The flag is not supposed to change the type of the catch method.

This was suggested as a feature request already: #45602. This was mentioned in the PR you linked.

**Comment by fregante** [comment]
> This was suggested as a feature request already: #45602

I was literally writing a comment about that 😅 sorry for the duplicate
