### ISSUE TITLE
How can I guard interface argument type of function type?

### ISSUE THREAD

**Issue by mizunashi-mana** [Microsoft/TypeScript#4704]
```typescript
// test.ts

interface A {
  a: string;
}
interface B extends A {
  b: string;
}
const a = (a: B) => a.b;
const b = (a: (a: A) => string) => a({a: "param a"});
console.log(b(a));
```

This is valid typescript code.
But, of course:

```
$ tsc test.ts
$ node test.js
undefined
$
```

Is this bug?
Or my misunderstanding?

**Comment by mizunashi-mana** [comment]
As a reference, this sample passed Online Check (http://goo.gl/8020p7)

**Comment by kimamula** [comment]
Your code looks totally valid and should output `undefined` with no wonder.
Which part looks a bug to you?

To avoid confusion, it'd be better to use distinct variable names.
```typescript
// test.ts

interface A {
  a: string;
}
interface B extends A {
  b: string;
}
const func1 = (b: B) => b.b;
const func2 = (func: (a: A) => string) => func({a: "param a"});
console.log(func2(func1));
```

**Comment by mizunashi-mana** [comment]
Sorry & thx for fixing my sample code.

I wondered `func2(func1)` is valid typescript code.

In the case:
```typescript
const b: B = { a: "param a", b: "param b" };
const a: A = b;
```

This is valid because `interface B` must have all of `interface A`'s.  It is safe.

However, in the case using function, I think non safe.
This is clear for the sample code.

`interface B` can behave like `interface A`, but, there are cases `(b: B) => any` cannot behave like `(a: A) => any`.

**Comment by mizunashi-mana** [comment]
For another example, this is valid case.

```typescript
// test.ts

interface A {
  a: () => string;
}
interface B extends A {
  b: () => string;
}
const func1 = (b: B) => b.b;
const func2 = (func: (a: A) => (() => string)) => func({a: () => "param a"});
console.log(func2(func1)());
```

The last sample only printed `undefined`, but, this has trouble.

However, I maybe misunderstand.

This is also valid code:
```typescript
// test.ts

interface A {
  a: string;
}
interface B extends A {
  b: string;
}
interface C<T extends (a: A) => string> {
	c: T;
}

var func: C<(a: B) => string>;
```

Perhaps, this maybe be valid for some critical reason.
I have less knowledge.  So, if you know the reason, please tell me.

**Comment by kimamula** [comment]
Ah, I see, you are talking about something related to PECS (Producer Extends and Consumer Super).
In TypeScript, if `B extends A`, then `SomethingGeneric<B> extends SomethingGeneric<A>` and this can be problematic in some cases as you mentioned.

I don't know if there is a explicit reason for this behavior (probably for simplicity, I suppose). 
Changing this behavior would be a big breaking change and I'm not sure if everyone is willing to accept it (for me, it's not bad).

**Comment by falsandtru** [comment]
refine

```ts
// test.ts

interface A {
  x: string;
}
interface B {
  x: string;
  y: string;
}

const a: A = {x: 'x'};
const b: B = a; // <= cannot assign

const fa =      (b: B) => alert(b.y);
const fb = (fa: (a: A) => void) => fa({x: 'x'});
fb(fa); // <= can assign but should not be assignable
```

**Comment by mhegazy** [comment]
looks like a dupe of  #1394

**Comment by mizunashi-mana** [comment]
@mhegazy oh, thx.

Let me discuss in that issue.

Thx for all of advicers.
