### ISSUE TITLE
Feature: Import module using alias as path if there is one

### ISSUE THREAD

**Issue by lucasbasquerotto** [microsoft/TypeScript#47053]
# Suggestion

I want to request the option to auto-import typescript files in vscode using the alias as specified at paths in `tsconfig.json`, otherwise use a relative path. The related setting is `typescript.preferences.importModuleSpecifier`.

None of the options works this way. The closest is `project-relative`, but it only works if all aliases are outside the project. I want that all paths that satisfy an alias to use the alias, but without having to use absolute imports for other paths (those should be relative). The preferred way would be alias followed by relative.

Related: https://github.com/microsoft/vscode/issues/138067 (VSCode feature request; I was asked to create the Feature Request here)

Thanks.

## 🔍 Search Terms

Autoimport

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by alumni** [comment]
This would be great! In angular/nestjs we often alias the modules to avoid long relative imports or project imports. 
We also alias certain paths where we store things like middleware, decorators, guards, filters etc

**Comment by lucasbasquerotto** [comment]
Just one thing to consider, is that an import in a file **inside** the path used in an alias should use relative path if the imported file is also in the path described by the same alias. 

For example, `/src/lib/file1` has an import to `/src/lib/file2`, and there's an alias defining `@/lib/` pointing to `/src/lib`. In this case, the import should be `import ... from './file2'`

One workaround while not having this feature is to use absolute paths (and possibly making an alias for the root path, for example `@/src/` points to `/src/`, although that might not be viable for every project). One benefit is that, because all paths are absolute, no imports need to be changed in the file that was moved (but imports in the files that pointed to the moved file may need to be changed, although a search & replace all occurrences is easier because all imports will be the same, while relative imports to the same file may differ and should be handled on a case by case basis). To sum it up, this might be better than relative imports in several cases, excepts in those cases in which files are moved together (which would keep the relative imports unchanged), especially if a lot of files are moved together.

That said, each project may have their own conventions, and having the option to use relative paths, except those specified in an alias, would be great.

**Comment by luukvhoudt** [comment]
@lucasbasquerotto I guess it would be very tough to determine if "a file is in the path". Would `/src/lib/dir/file3` or `/src/file4` also be in the path?

I would rather like to see a straight forward toggle like `forceUseOfPathAliases: boolean` then a half-baked solution of absolute/relative/path alias.

**Comment by lucasbasquerotto** [comment]
@luukvhoudt When I say "a file is in the path" I mean "a file can be used with at least 1 of the paths in the alias".

If more than 1 path in the alias is satisfied, it could use the smaller path, defaulting to a random path if the path lengths are the same.

> Would /src/lib/dir/file3 or /src/file4 also be in the path?

An alias `@/src: /src` would include both, an alias `@src/path: /src/lib` would satisfy only the first. 

If you mean to say about the path of both files (current file and imported file) using the same alias (when I said `an import in a file inside the path used in an alias should use relative path if the imported file is also in the path described by the same alias`), it might be trickier because even if they both satisfy the same alias, they might be using other alias in other places, which could cause confusion about which path to consider. Unless all aliases have no subpaths in common. This case can be ignored, if needed.

**Comment by Shaglock** [comment]
Any news about this issue? I also would like that aliases specified at paths in `tsconfig.json` would be the first suggestion from VSCode, not the second.

**Comment by alfaproject** [comment]
I'd love this as well. I've tried a few different options (no `baseUrl` set), but all auto imports seem to always use a relative path no matter what `importModuleSpecifier` setting is set to. Very weird and undesired ):

**Comment by andrewbranch** [comment]
The behavior being asked for is what should happen when you have `paths` but no `baseUrl` and set `typescript.preferences.importModuleSpecifier` to `project-relative` or `non-relative`. I should note, though, that [we do not recommend using `paths` this way](https://www.typescriptlang.org/docs/handbook/modules/reference.html#paths). If you’ve defined `paths` and are not seeing them in auto-imports, please provide specific repro steps (a GitHub repo would be excellent) here or in a new issue (preferred). Thanks!
