### ISSUE TITLE
Order-dependent type display behavior in language service

### ISSUE THREAD

**Issue by the-spyke** [microsoft/TypeScript#47055]
# Bug Report

### 🔎 Search Terms

generic infer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about functions and generic

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/PTAEGEHsDsBcFMAetQEsDOoBWBXdKBDaUSAIy3gGMUB3VWACzWgAccUATA2AgWACgOVADYEATvFCwAni0kAJIh2HwxAHnAAaUACUAfKAC8oABQDQoSjATIAXBAEBKIwYAKYyAFsM8NfoDcAgIgoADi8LCYBKCK0MqqoEqgErA4YtBRoNDwNCTZAkKUohJSspIAsqgc8TTivlqgAHINjTra+kam5llIsPax8erN2q16Ti4xSirqDQFBgiJ1zAhiAGYElJIAkqzsUHC9oADe3Yj20DiepKqB-AC+8yE7oJ7SlgTokoyS4gDml-A4KA6IxgQxUJQmFsAOTCYSga7vOGoaC-UAMKaqdDBMAYRLCWrSTDfUDoAieSQmHZsWD7GywRzadCQUAwgBuklWqEQ8A4UgYkhRNNKcgKixKqxw0GoqBgwPoDEq1RUtQkfng6D0Zn4FgxcWm-Ux6mpe2svXaGrG-Echv1qjUJtpZuQFs1t0KxU5UplcpBiqqNTq6oAjq7tAAtLXdTw0ACM9iVgbVjrp5t08FD6fQEb0mm6esGtsGIddVptkztxt2ToOLtAkfd4q90tgsuIfsTKqDACELZmdBrtABNHPaiwx+OgTs5IMp52wbS90Aj+u56M0ABMCYDXbVS4H-cHy7XOvRRqL0xLWbLF-tc9rC9XtxxoG7HwhU4A6toOJANVlIEYFFfm0XB8FAFgPnQYD+UkLgeH5DwcF+BgBCsDIUAQfBp1VSRjA0dotXLHCgwaWZCJcbpsmQCZ0PpCZqNgEw6N6Rxn34FEVnWTYp2kAd0BYGBPmOboCHsfAxGA24Hn4F8AGUGEgHBhD5TiEhkOQK2Le96W0co+I1QSMngXMEXYUBfgiTABkvHS0ylABraBIBoaArSQQSxBQdDwNeGzVFjToOx3GcJDHKQNVgEiwsZUT0GkaVTCOUBEFAO5y3cLwfDUfT+KMz4DEMAwTlPCwQjOLJLmuMRQFWDxPFZatUxolFVixWqUXgABCeYLAsFI0mIEq+pGxJ7AAA1S4wABIjkQO5xu6Cw7luZanHYj0lg0ipVEstQAEFF0K0AAHlvFgA7tAc+BpEgVZXwMAAyV92JCcpIBKAgODZIhNj5cpP2zSw9Usyx50SOJgA+5JDKEr4ynQAA6NChMIaoABVIGaqLP06AjQAAMTaXQtW42APukexmPnexwGcIrCZ0YiQtw-Hyl2+ptCJ0ziY6IqqMOBmWJohnGJMZLEcl4XH0lxGyYp6mH2cdL2J8tGOExvK4YBvGGiJwiTHlsRKdMCQBLh+wmYmInmeVULOYgdo9I5vwuf0QqrQsRjaPB0XekV+lHER75oBMGqGfF0BZbEbRZaN6Qw+Vxw2MeMAFKUlTmDamrtq02ymvnbRkrE0lYEk1FtFIexSEgSAVCINLTNIczLMiPO7wLh9tEc5zXPcxBPO81GXmkfyxA3IKFWi+Bwq+jWsfnAHmImSOTdjAAGNLk7zU85812HjKX8ODEjqupDEHBJHS2Ld-ixLI8QbQ3nS+xMu8T4coM83jI9kTStAEIJsLhXASK1dqXJsg9Vkv-Aa6Q-6jT6iXSanRZqpQANSgGkAtJaaVVppXWgIIAA)

### 💻 Code

I'm trying to make typed middleware chain. Every middleware is a function which accepts the next handler and returns a new one. 

```ts
// Context is just an object with input data
declare type Handler<C, R> = (
  context: C
) => Promise<R>;

// Gets a Handler and returns a new one
declare type Middleware<C, NC, NR, R> = (
  next: Handler<NC, NR>
) => Handler<C, R>;

declare interface InputContext {
  x: number;
}

// In my case the argument with which I'll be calling handlers
// is always the same (InputContext), so I've fixed the input type
declare function withMiddleware<Res>(
  handler: Handler<InputContext, Res>
): Handler<InputContext, Res>;
declare function withMiddleware<Req, Res, Z>(
  mw1: Middleware<InputContext, Req, Res, Z>,
  handler: Handler<Req, Res>
): Handler<InputContext, Z>;
declare function withMiddleware<B, Req, Res, Y, Z>(
  mw1: Middleware<InputContext, B, Y, Z>,
  mw2: Middleware<B, Req, Res, Y>,
  handler: Handler<Req, Res>
): Handler<InputContext, Z>;

// Basic MW, does nothing, just passing the data through
const testMiddleware = <C, R>(): Middleware<C, C, R, R> =>
  next => context => next(context);

interface MyResponse {
  a: string;
}

// #1 Should inter type Handler<InputContext, MyResponse>, but gets Handler<InputContext, unknown>
export const myHandler1 = withMiddleware(
  testMiddleware(), // #2 If I comment/uncomment of indent/deindent this line, type inference breaks sometimes. See the video
  async ({ x }): Promise<MyResponse> => {
    // x: number from InputContext infers fine!

    return {
        a: `x = ${x}`
    };
  }
);
```

### 🙁 Actual behavior

Line :40. Sometime it infers the types right, sometimes it doesn't. It may took ~30 tries to flip it, but it's reproducible.

[Link to the video on Google Drive](https://drive.google.com/file/d/1Ghbb4ZGM9RCy4IfqXW2tXscFGDVy2xAg/view?usp=sharing)

And I also can't get `withMiddleware` return type working. It's defined as the return type of the first argument, but it's always `unknown` even when the tooltip for the first argument shows its return type as resolved to `MyResponse`.

### 🙂 Expected behavior

`testMiddleware()` at line 40 should always resolve to `Middleware<InputContext, InputContext, MyResponse, MyResponse>` no depending on indentation, etc. Also, the return type of the `myHandler1` at the line 39 should be `Handler<InputContext, MyResponse>`

**Comment by RyanCavanaugh** [comment]
Shorter (but likely not minimal) repro
```ts
declare type Handler<C, R> = (
  context: C
) => Promise<R>;

declare type Middleware<C, NC, NR, R> = (
  next: Handler<NC, NR>
) => Handler<C, R>;

declare interface InputContext {
  x: number;
}

declare function withMiddleware<Req, Res, Z>(
  mw1: Middleware<InputContext, Req, Res, Z>,
  handler: Handler<Req, Res>
): Handler<InputContext, Z>;

const testMiddleware = <C, R>(): Middleware<C, C, R, R> =>
  next => context => next(context);

interface MyResponse {
  a: string;
}

export const myHandler1 = withMiddleware(
             // HERE^
  testMiddleware(), // <--- HERE
  async ({ x }): Promise<MyResponse> => {
    return {
        a: `x = ${x}`
    };
  }
);
```
In a freshly-edited file, hovering on `myHandler1` followed by `testMiddleware()` shows the `Middleware<InputContext, InputContext, unknown, unknown>` type arguments, but in the other order you'll see `Middleware<InputContext, InputContext, MyResponse, MyResponse>`

**Comment by the-spyke** [comment]
The issue still present in `4.6.0-dev.20220116`
