### ISSUE TITLE
Friend please fix this

### ISSUE THREAD

**Issue by JowoScript** [microsoft/TypeScript#47051]
const createProgram= ts.createProgram(["test.ts"], {});
const diagnostics = ts.getPreEmitDiagnostics(createProgram);

Case is each for loop diagnostics file source. Then error "useCaseSensitiveFileNames" from file test.ts name ? whats wrong i put right root.

VM848:113056 Uncaught TypeError: Cannot read properties of undefined (reading 'useCaseSensitiveFileNames')
    at createCompilerHostWorker (<anonymous>:113056:73)
    at createCompilerHost (<anonymous>:113048:16)
    at Object.createProgram (<anonymous>:113748:49)

WHAT THE ERROR HERE -> return file property name" useCaseSensitiveFileNames "

I think because ts.sys function not call in javascript. ts.syst is private function mode. so cant call back ts.sys function
Thanks Regards

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by JowoScript** [comment]
Before TypeScript compiler using callback like this
compiler.parser.errorRecovery = true;
            compiler.setErrorCallback(function(start, len, message, block) {
                console.log('Compilation error: ', message, '\n Code block: ', block, ' Start position: ', start, ' Length: ', len);
            });
            compiler.addUnit(libfile, 'lib.d.ts');
            for(i = 0; i < src.length; i++) {
                compiler.addUnit(src[i], '');
            }
            compiler.typeCheck();
            compiler.emit(false, function createFile(fileName) {
                return outfile;
            });
