### ISSUE TITLE
Conditional types are not correctly resolved on object fields in generic functions

### ISSUE THREAD

**Issue by knikolov-nuvolo** [microsoft/TypeScript#47065]
# Bug Report

### 🔎 Search Terms

function generic extends type conditional

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `generic`, `extends`, `function`, `conditional`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/C4TwDgpgBAkgJlAvFAdgVwLYCMICcDcAsAFAkCWKweAZgIYDG0A6mcABbxQDeJUUZcAFyw4RYgF8S5SjQbQAQrQDO0CAA8qKOEqgt2nHsT4paGCMKXBcFAOZi+uCNWEB5dnjGTSxClVx1GKDc2PCh1TW1dVg4EQz4Ae3dcADEyCAAbIVRMHAISL2k-AOgAYTYyTLCNCC0dRRVuXih6cszUjKysePj0iFoUTyliUEgoAFFejAAeABUAPiRGoygbCGAANVp0tAgACgBKYRnB7xHoACUnWaqInT0YheQJiGn4BYAyJb5V4EvqA6OJxIZ10uFoYEguGu4RqkXub0WcSgAG0ZgBpCAgfgoKAAa0x8WoUBmAF0jqiMSASTdYXdopwAPxQP6zCmYkkLYTPaYzNlUuZA4gAeiFUHYZB0AHd4rhcTplFVIPQqHASNQ0ChlWR4jiqJZdsBhEwwRC8FN6hA5vsvlARVAAAYCe1QfoIe0mMzO2iOcaTKZzJp2+2OajOiXMq4B7x8YAAOgEsZ+m22e32seA8VSaggcAO9jFsY9EETa2TOwOsZa3oAgsBdgBGfb5uMhksbLbltMZrM5vNNFtONt-CuJEIpNKZQV2sC4eJYSZQAC0UGoE4QZ3lPoo9BljmVao1Wp1YoglgA4jU8GR6NDqrUoBa5gajSbIbMrTa7Vt0iu15voJK0RiuA0D2iyCwAD6+i8-r2kMMbxnAbZlqm6aZmQ2a5k2-aFqYxZJh2qFVrgtYNk2tqings64MIAAKs6QqAUAAOTEbWzFQHA8SnqgiRVBKwBQMeILMeg2ChFBvIAERFlJJLMbGOGtgRKYVt2GG9uRdpUTKdEMXgTHMepmEcVxPEoHx6gCUJuogSxYm5FAknIlJIZyQpSmDj8w5pqOeDtJOFFhLg1F6fEjFYsx3lOKZ3E6BZglWZYNnAaMzEstJbkck50E8i5WVzB5EhAA)

### 💻 Code

```ts
type Id = number;

interface WithId {
  id: Id;
}

interface Base extends WithId {
  name: string;
  ref: Other;
}

interface Other extends WithId {
  otherField: number;
}

interface Child extends Base {
  childField: boolean;
}

type Elem<T> = {
  getValue(): T;
}

type Ref<T extends WithId> = Elem<Id> & {
  getRef(): T;
}

type Wrapper<T extends WithId> = {
  [TKey in keyof T]: T[TKey] extends WithId ? Ref<T[TKey]> : Elem<T[TKey]>;
}

// this works as expected
function test(t: Wrapper<Base>) {
  // `id` and `name` are Elem<>
  // `ref` is Ref<>

  t.id.getValue().toFixed();
  t.name.getValue().charAt(1);
  t.ref.getValue().toFixed();
  t.ref.getRef().otherField;
}

// problem - field types are incorrect
function testGeneric<T extends Base>(t: Wrapper<T>) {
  // all fields are with type `Ref<> | Elem<>`

  t.id.getValue().toFixed();
  t.name.getValue().charAt(1); // error: Property 'charAt' does not exist on type 'number | T["name"]'.
  t.ref.getValue().toFixed(); // error: Property 'toFixed' does not exist on type 'number | T["ref"]'.
  t.ref.getRef().otherField; // error: Property 'getRef' does not exist on type 'Ref<T["ref"]> | Elem<T["ref"]>'.
}
```

### 🙁 Actual behavior

In `testGeneric()`, all fields of `t` are of type `Ref<T[...]> | Elem<T[...]>`.

- `t.id` is `Ref<T["id"]> | Elem<T["id"]>`
- `t.name` is `Ref<T["name"]> | Elem<T["name"]>`
- `t.ref` is `Ref<T["ref"]> | Elem<T["ref"]>`

### 🙂 Expected behavior

In `testGeneric()`, the fields of `t` should have types correctly resolved, as they are in `test()`.

- `t.id` should be `Elem<number>`
- `t.name` should be `Elem<string>`
- `t.ref` should be `Ref<Other>`

**Comment by MartinJohns** [comment]
Same as #46155. The type for `T` is not known, so resolving of the conditional type is deferred.

**Comment by knikolov-nuvolo** [comment]
So, conditional types are not resolved on generics, and this is expected behavior?

**Comment by MartinJohns** [comment]
They're not resolved unless the actual type is known. For example:

```
type Test<T> = T extends boolean ? string : number

function fn<T>(arg: () => Test<T>) { }

fn<boolean>(() => 'str')
```

In this case the `T` part of `Test<T>` is known to be `boolean` at the callsite, so the conditional type is resolved to `string`. Passing a callback that returns a `number` would be an error.

In your example within `testGeneric` the function the type of `T` is not known. It will be provided at the callsite, but the implementation of the function is unaware of it. That's why the conditional type is not resolved.

**Comment by knikolov-nuvolo** [comment]
Thanks for your time!

I was confused because inside `testGeneric()` TypeScript knows that `t` extends `Base`, so it has the fields `name`, `id` and `ref`. Also, TypeScript correctly resolves that `T["ref"]` is of type `Other` (as well all other fields of `T`).

This example brings even more confusion to me ([playground](https://www.typescriptlang.org/play?ts=4.5.2#code/C4TwDgpgBAkgJlAvFAdgVwLYCMICcDcAsAFAkCWKweAZgIYDG0A6mcABbxQDeJUUZcAFyw4RYgF8S5SjQbQAQrQDO0CAA8qKOEqgt2nHsT4paGCMKXBcFAOZi+uCNWEB5dnjGTSxClVx1GKDc2PCh1TW1dVg4EQz4Ae3dcADEyCAAbIVRMHAISL2k-AOgAYTYyTLCNCC0dRRVuXih6cszUjKysePj0iFoUTyliUEgoAFFejAAeABUAPiRGoygbCGAANVp0tAgACgBKYRnB7xHoACUnWaqInT0YheQJiGn4BYAyJb5V4EvqA6OJxIZ10uFoYGu4RqkXu8AANFAZgBpCAgG7QnQAa1R8WoiMeiIA2sjUQBddG1KL6BAAfigf1mxJRIFJC2Ez2mMyZZLmYmB4GYYLAkFwkOqlNhcAJcSg3LRFCg2JAuMRpOETCFswRJJAvPyQwA9AaoOwyDoAO7xXCYnTKKqQehUOAkahoFCOsjxFAmiCWXbAdVCkVTeoQOb7L5QI1QAAGAhjUH6CBjJjMCdojnGkymcya0ZjjmoCbN9Kuue8fGAADoBFWfpttnt9lXgPFUmoIHADvYTVXUxA62sGzsDlWWhmAILAXYARn2PerhcHGy2I+brfbne7TUXTmXf1HiRCKTSmSBxGjYFw8SwkygAFooNRTwgzrbMxR6FbHI6XW6PV6PqWAA4jUeBkPQYq3FAoban8FKRFyABEhZIeSyDIahrIHJGvTACahZHH8C6FgAhFWR54O0mQtm2ZAdl285RsapoWlaNpDHweHNF6cAzIRiLwVCErRJwdIMjMfxslmLyzFJPZflo-FOORPwHs2lEnh0+DMSa5RsdaSicSaApQAAsiA8EYYSKFOGhPbcRgIACRZxFNE5ZEUUk1FwLRm6MTp0asVAlqGcZ3GKXAFkuZZTgIXcom0qW1BTK5TjSRyqWxdQerLJF0UqfuTiHt5L6BcaeDXrgD5QAA5GpTi1VAcDxL6qCJFUZrAPkQA)):

```ts
function testGeneric<T extends Base, TRef extends T["ref"] = T["ref"]>() {
  let tref: TRef;
  tref!.otherField.toFixed(); // this works - tref is `Other`

  let condTref: TRef extends WithId ? Ref<TRef> : Elem<TRef>;
  condTref!.getRef().otherField; // this works - condTref is `Ref<Other>`

  type MyRef = T["ref"];
  let myref: MyRef;
  myref!.otherField.toFixed(); // this works - myref is `Other`

  let condMyref: MyRef extends WithId ? Ref<MyRef> : Elem<MyRef>;
  condMyref!.getRef().otherField; // error - 'getRef' does not exist - condMyref is `Ref<Other> | Elem<Other>`
}
```

TypeScript knows that `T` is a type that has the same fields as `Base`, but it does not _always_ resolve the conditional types when generics are used.

I'm sure that the team has good reason to do it this way, but I am curious to know why.
Is there any documentation page or FAQ where this is explained in more detail?
Looking at the issue which you mentioned, seems that this is confusing a lot of people.

**Comment by knikolov-nuvolo** [comment]
I understand that, but I am curious to know which are the use cases, and why is that.
IMO this should be documented somewhere, to prevent creating new and duplicate issues (like this one).

I personally do not find any significant difference between the `TRef` and `MyRef` types but it seems that am missing something.

**Comment by RyanCavanaugh** [comment]
It's not sound to use constraints to resolve conditional types because the type can be aliased in a way that renders it incorrect relative to a concrete instantiation. Here's a shorter example:
```ts
type WithId = {
  id: number;
};
type Wrapper<T> = {
  [TKey in keyof T]: T[TKey] extends WithId ? string : number;
}

type Base = {
  name: { first: string }
};

function generic<T extends Base>(obj: Wrapper<T>) {
  // Alleged: this is OK
  obj.name.toFixed();
}

// Legal call
generic<Base & {name: WithId}>({
  name: ""
});
```

Responses in the issue tracker are a part of the documentation; if your reaction to that is that the issue tracker is too long to read and too hard to search given how big it is, consider how big and hard to search the documentation would be if every "why" discussion here were part of it 😅

**Comment by knikolov-nuvolo** [comment]
@RyanCavanaugh, thanks!
This example helped a lot!

A workaround is something like this, which will prevent passing a type that overrides the Base fields.
But maybe we should consider not using generics at all. Depends on the use case.

```ts
function generic<T extends Base>(obj: Wrapper<T> & Wrapper<Base>) {
  obj.name.toFixed();
}

// error
generic<Base & {name: WithId}>({
  name: ""
});
```

Thank you both. I'll close this issue, since I do not have any more questions :)
