### ISSUE TITLE
Type of element selected from (potentially) empty array

### ISSUE THREAD

**Issue by jaksenko** [microsoft/TypeScript#47060]
# Bug Report

### 🔎 Search Terms

array index element undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type of element selected from (potentially) empty array

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwJ4C4bQQSzAcwNoC6MAvDIQNwCwAUKJLAGaYLQCiANgKYC2nYspREjwAGAlWoB6STAAWIAG6cEMRcpgADJiygcefKBphQQ6TpxiYoEY0gAOFzDY0ZsOIwHdZmLpdgR5AFd2ABMYACMLFygsXBgAHxhAsBDOJjBOEKMQFU4lMAjOKCh1DWTU9MyjCGxgCyhZOFhgOALImFSQwLqwhgQQbmNZC3ZsCzhwtQA6IA)

### 💻 Code

```ts
const ary: string[] = [];
const firstElement = ary[0];
// `firstElement`'s type is `string` while it should be `string | undefined`
// or even better `undefined` since that can be deduced from the line above.
```

### 🙁 Actual behavior

`firstElement` is of type `string`.

### 🙂 Expected behavior

`firstElement` should be of type `string | undefined` or `undefined` if that can be deduced.

**Comment by whzx5byb** [comment]
See https://github.com/microsoft/TypeScript/pull/39560

**Comment by jaksenko** [comment]
Thanks, I didn't know about the flag, but as soon as I turned it on I got bombarded with TS errors because the flag deals not only with arrays but also with objects. And I import a lot of objects that aren't typed until I cast them (json, css, ...).

Anyway, I still think this report is valid because TS currently doesn't follow JS specification. In JS, if index doesn't exist, it returns `undefined`.

**Comment by MartinJohns** [comment]
> I still think this report is valid because TS currently doesn't follow JS specification.

But the problem is solved. That's exactly what the mentioned flag is for.

**Comment by jaksenko** [comment]
You are right, I guess I just don't agree with the implementation that mixes arrays with objects, but that's another story. Thank you for pointing me to the flag.

**Comment by RyanCavanaugh** [comment]
> Anyway, I still think this report is valid because TS currently doesn't follow JS specification. In JS, if index doesn't exist, it returns undefined.

This is equally true of objects? Anyway.
