### ISSUE TITLE
Equivalent types are marked as not equivalent

### ISSUE THREAD

**Issue by schicks** [microsoft/TypeScript#47068]
# Bug Report
In certain cases, types that should be equivalent are not recognized as such by the compiler. We are able to get around this by showing that a term is one type, then casting it to the other, but it adds boiler plate and casting seems likely to be error prone.

### 🔎 Search Terms

Inference, Type Flattening

### 🕗 Version & Regression Information

4.5.2 and 3.3.3 both reproduce this in the playground.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about contravariance of functions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/C4TwDgpgBAQg9gDwDwEEB8UC8UDeAjRALihQF8BYAKAGM4A7AZ2CggEcBXASwDcBDAGwh1q0bKgA0MNAAo+-YvGQoAPlICUCxKgzLYWqVgxygA)

### 💻 Code

```ts
type Box<A> = {box: A}
const equivalence = <A,B>(val: Box<A|B>): Box<A> | Box<B> => val
// ^ type error; Type 'Box<A | B>' is not assignable to type 'Box<A> | Box<B>'.
```

### 🙁 Actual behavior

Certain obviously distributive types do not distribute

### 🙂 Expected behavior

`Box<A|B>` should be equivalent to `Box<A>|Box<B>`

**Comment by MartinJohns** [comment]
The types are not equivalent. The one type is either a box storing A, or a box storing B. The other type is a box storing either A or B. That's a fundamental difference.

**Comment by schicks** [comment]
So they are structurally equivalent, in the sense that any value which satisfies the first type also satisfies the second type, and vice versa. The problem also doesn't really appear to be related to the existence of the `Box` type; if we inline it's structure, `<A,B>(val: {box: A|B}): {box: A} | {box: B} => val` gets the same type error. Shouldn't structural equivalence be sufficient to consider them equivalent in typescript?

**Comment by MartinJohns** [comment]
> So they are structurally equivalent, in the sense that any value which satisfies the first type also satisfies the second type, and vice versa.

Again, they are not. Neither `Box<A>` nor `Box<B>` can store a value that is `A | B` (either `A` or `B`). `Box<A>` can store `A`, and `Box<B>` can store `B`. Only `Box<A | B>` can store `A | B`.

**Comment by schicks** [comment]
But any concrete value of type `Box<A|B>` either contains an `A` or a `B`, and is therefore also of type `Box<A>|Box<B>`. I'm missing some distinction you're making. Is the issue that someone might try to mutate the inner value in an unsafe way? Because the type error is also still there if the `box` property is read only.

**Comment by MartinJohns** [comment]
Maybe this helps you to understand the issue.

- You have objects with the forms of rectangles (`A`) and triangles (`B`).
- The box that can store rectangles (`Box<A>`) is not high enough to store triangles (`B`). It can only store rectangles.
- The box that can store triangles (`Box<B>`) is not wide enough to store rectangles (`A`). It can only store triangles.
- The box that can store both rectangles and triangles ( `Box<A | B>`) is high and wide enough for both forms.
- If you have a rectangle (`A`) you can either store it in a box for rectangles (`Box<A>`) or in a box that can store either rectangles or triangles (`Box<A | B>`). You can't store it in a box for triangles (`Box<B>`).
- If you have a triangle (`B`)  you can either store it in a box for triangles (`Box<B>`) or in a box that can store either rectangles or triangles (`Box<A | B>`). You can't store it in a box for rectangles (`Box<A>`).
- Now someone calls you: "Hey, buddy, I have a form to store, bring me a box!"
  - But he didn't tell you whether he will bring a rectangle (`A`) or a triangle (`B`).
  - You only know it will be either a rectangle or a triangle, one of those two options (`A | B`).
  - If you bring a box for rectangles (`Box<A>`) you will be screwed if he actually has a triangle (`B`).
  - If you bring a box for triangles (`Box<B>`) you will be screwed if he actually has a rectangle (`A`).
  - So the only option that is safe to either store a rectangle (`A`) or a triangle (`B`) is a box that can store both (`Box<A | B>`).

**Comment by schicks** [comment]
It's a nice geometric example, but it doesn't help me understand why an object with a property `box` that is either `A` or `B` is not either:
- an object with a property `box` that is `A`
- an object with a property `box` that is `B`

Is there something beyond what I said above that the `equivalent` function is attempting to claim? Is there something that I can do with a `Box<A> | Box<B>` that I can't do with a `Box<A|B>`? The example seems to point at trying to change the value contained in the box as what we can't do, but again, the error still occurs with readonly types.

**Comment by fatcerberus** [comment]
In your specific case there's little structural difference because there's only one value of the generic type, but that's a degenerate case; *in general,* such types are not equivalent.  Consider the difference between `A[] | B[]` vs. `(A | B)[]` and that should give you an idea.

**Comment by MartinJohns** [comment]
> Is there something beyond what I said above that the equivalent function is attempting to claim?

Trying to explain the code in question ` <A,B>(val: Box<A|B>): Box<A> | Box<B> => val` with my example:

- I give you a box that can store both a rectangle **and** a triangle.
- I get back from you a box that can store either a rectangle, **or** a triangle.
- I don't know which of those two you give me back.

---

But I'm sorry, beyond this I'm not able to make it any more clear to you. I'll drop out from this conversation.

**Comment by schicks** [comment]
Before you go @MartinJohns , why doesn't that mean that `<A,B>(val: Box<A>|Box<B>): Box<A|B> => val` has a type error? It seems like in your example, the problem with subtyping should go in the other direction.

@fatcerberus , that's a good point but even if we get rid of the `Box` generic entirely and just use its definition inline, these type errors still occur.

**Comment by RyanCavanaugh** [comment]
> So they are structurally equivalent, in the sense that any value which satisfies the first type also satisfies the second type, and vice versa.

The only way you can make this determination is via a combinatorially-explosive expansion of all possibilities, which is not great from a "typecheck within a human's patience" perspective.
