### ISSUE TITLE
Incorrect imported function `this` context using ES6 module

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#4706]
Code

``` ts
// export.ts
export function foo() {
  'use strict'
  console.log(this);
}

foo();
```

``` ts
// import.ts
import { foo } from './export';

foo();
```

expected

```
$ node import.js
undefined
undefined
```

actual

```
$ node import.js
undefined
{ foo: [Function: foo] }
```

**Comment by falsandtru** [comment]
Fix: add `'use strict'`

**Comment by mhegazy** [comment]
The emitter will need to identify call/new expressions from aliases, and rewrite them using as `foo.call(void 0, arg)`

A PR would be appreciated.

**Comment by falsandtru** [comment]
Thanks for your acceptance.

**Comment by falsandtru** [comment]
Babel's implementations:
>  `(0, _assert2['default'])(true); // (A)`
>
Note that the default export is always accessed via the exports object_assert2 (line A), never directly, like this:
>
    var assert = _assert2.default;
>
The reason for that is support for cyclic dependencies.

http://www.2ality.com/2015/12/babel-commonjs.html

**Comment by Andarist** [comment]
As the current emit does this:
```ts
Object.defineProperty(exports, "__esModule", { value: true });
var export_1 = require("./export");
(0, export_1.foo)();
```

I think that the issue can be closed, cc @jakebailey
