### ISSUE TITLE
Type inference breaks in chain of generic functions

### ISSUE THREAD

**Issue by SLaks** [microsoft/TypeScript#47074]
# Bug Report

### 🔎 Search Terms

type inference nested generic 

### 🕗 Version & Regression Information

v4.5.2, v4.6.0-dev.20211208

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211208#code/MYGwhgzhAEBiD28BCBXAliAJgUwE4B4AVAZQAswAHbAPmgG8BYAKGmmHgDsIAXXFYbvFwAKXNjCZOIAJ7QAZoggAuaCXJUAlPWgBfZqwmYE8IgDkwAW2zRsAD27YOmGD1xoOAcwA0qgGpgQFBphDktsFUJzKx8ANwCgiP9A7C1GFlZoMW4UXA5oDmwAdzhEVAwcEUNhblI0CAA6BXgIH1Do6DjkjQ0Abn1dZn7CtBqzIrJKazsHJxhjMqw8fDodamphftZgACMVYW30RdwVGrqtAF5aSPH1FPpN6AB6R+gAYUhuaEFod1AUHC+pCmtjq3HcHi+0io0DATkB1jEEBQIE+8Dk8LYARA2zAwAA1vUHlkcnkdtVahAtJBAXVoAAyVSmG6TPrpPRMdnMOwUISfOQoDgCNCcGGYTBIMC4ACMACZhKl+sTctAiDZ7I5nCVkIcKstVusDuU8BELrQ0hlMthssrDUd6oZjMIAAY46VOnxSjT2sWOl2SmXu6Ay3r9HSszlMbm8+QCoUiwwS6UygDMABZ5fd0kq8qrphq5qUdUsVmt9kXjqpTZmLdnoLaKvVhjVhAnJbL5V6HYhna7k4Hk52fd2-bhU4HUyG2eHBkxntBiGgLBQQNYcBZ4NBhOQYGB6XWNEoZ+wuHzEFLoOd8kUtQsKsIVoOjN2AORgZ8ex+O5-bd9PGWPScmilRpFHqbZWWYOdXngJcV1saA1w3FsxRgV1zwZV1g0PJhjx4eREBlC98PgYCm1IZDxTbOVulZJoZRA5owIgphIJeABZIRrHYWC7AQ7B103WAAEEAEkABliBUQxUMlZM91dVMfAOT4OHgT5XXk-0D2gZhcNPeA5MvIDGxGcjWyTNMO1oxBkwYhpwJnR4AConLeEBOGwHc8ngbYACtsAEGE4WkmFoAoXB4CoXBuGkHwwE+PgODBKwgswH48hqawYuhCBpB4fj6mgJzHi5WweWimNBTBeMxSICYqB8SIwjVGZNVccFGqSIJ1n6HzfIiersFaMIIiiIaOnicI-EmhV0jnQggUxPDaQKYBPIgSVZEwIIvg3UhuG4ChlGeDxTJQbZ6m4x42LQYAIogNFuEeQgoWwYg7rQCgnrqJFPMeZMAA4AHYAE4ADZCSzK0SW0eo4b6nwAG02mwABdFROh2nQYRgNRJj3OhLQkKRZGR5r3EZMJ0em5JdHDIA)

### 💻 Code

```ts
class FooBuilder<TShape> {
  constructor(readonly foos: TShape) { }
  addFoo<TName extends string, TValue>(name: TName, value: TValue) {
    return new FooBuilder(add(this.foos, name, value));
  }

  with<TNewShape extends FooBuilder<{}>>(
    cb: (builder: this) => TNewShape) {
    // Cast to include the existing type and the result of the callback.
    return cb(this) as this & TNewShape;
  }
}

export function addBar12() {
  return <T extends FooBuilder<{}>>(builder: T) => {
    return builder.addFoo(`bar1`, 1).addFoo(`bar2`, 2);
  };
}

export function addBar1234() {
  return <T extends FooBuilder<{}>>(builder: T) => {
    return builder.with(addBar12()).addFoo(`bar3`, 3).addFoo(`bar4`, 4);
  };
}

// Simple demo (has a & b):

const foo1 = new FooBuilder({}).addFoo('a', 1).addFoo('b', /2/);
foo1.foos.b;

// Complex demo (adds bar1 & bar2):
const foo2 = foo1.with(addBar12());
foo2.foos.b;


// More complex demo (FAILS: adds bar3 & bar4, but not bar & bar2): 
const foo3 = foo1.with(addBar1234());
foo3.foos.b;

/** Clones an object and adds a property, at runtime and in the type system. */
export function add<TShape, TName extends string, TValue>(
  obj: TShape, name: TName, value: TValue) {
  // The cast is necessary due to https://github.com/Microsoft/TypeScript/issues/38796.
  return { ...obj, [name]: value } as TShape & { readonly [name in TName]: TValue };
}
```

### 🙁 Actual behavior

`foo3.foos` contains `bar3` & `bar4`, but not `bar1` & `bar2`.

Calling `.addFoo()` after `.with(addBar12())` seems to lose the type information from the latter.

### 🙂 Expected behavior

It should also have `bar1` and `bar2`, from the `.with(addBar12())` in `addBar1234()`.

### Further note

If you comment out `as this & TNewShape` on line 10, it will correctly include `bar1` and `bar2`, but it then won't have `a` and `b`.

That's expected, because that makes `.with()` ignore the existing `this` type from `foo1`.

It looks like including `this` in the return type of `with()` makes it drop the nested `with()` call.  I can't imagine why though.

**Comment by whzx5byb** [comment]
I think the signature of your `with` method is not corrected. It should be
```ts
with<TNewShape>(cb: (builder: this) => FooBuilder<TNewShape>) {
    return cb(this);
}
```
which will make your example work.

**Comment by whzx5byb** [comment]
I think the signature of your `with` method is not corrected. It should be
```ts
with<TNewShape>(cb: (builder: this) => FooBuilder<TNewShape>): FooBuilder<TShape & TNewShape> {
    return cb(this) as FooBuilder<TShape & TNewShape>;
}
```
which will make your example work.

**Comment by SLaks** [comment]
You're right; that works.

Thanks!

But why doesn't it work my way? This feels like a bug with the `this` type.

**Comment by whzx5byb** [comment]
> But why doesn't it work my way? This feels like a bug with the `this` type.

Another solution in your way would be
```ts
with<TNewShape extends FooBuilder<{}>>(cb: (builder: this) => TNewShape) {
// The only change here is replacing 'this & TNewShape' with 'TNewShape & this'. 
    return cb(this) as TNewShape & this;
}
``` 

It may seem weird where `T & U` and `U & T` have different behavior, but I guess the way ts treats an intersection of function signature is the same as overloading: [The first applicable overload is chosen](https://github.com/microsoft/TypeScript/issues/1860#issuecomment-72154737). 

A simple example:
```ts
type A = { (input: string): string };
type B = { (input: string): number };
declare var fn1: A & B;
declare var fn2: B & A;
var result1 = fn1('foo'); // string
var result2 = fn2('foo'); // number
```

**Comment by RyanCavanaugh** [comment]
Seems like you got the right help -- intersecting two object types with the same method name is pretty fraught and it's usually better to use a sort of spread equivalent to exclude the overwritten method from one of the input types.
