### ISSUE TITLE
Improve non-top-level import/export error, especially for JS

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#47076]
ES imports and exports can only be used at the top level of a module. This is illegal:

```ts
function container() {
  import 'fs'
  export { container }
  namespace N { }
}
```

The current errors for these three statements are vague and, for JS, contain irrelevant terms:

Actual:

(1) "An import declaration can only be used in a namespace or module."
(2) "An export declaration can only be used in a module."
(3) "A namespace declaration is only allowed in a namespace or module."

Expected:

(1) When the node is in a JS file, "An import declaration can only be used at the top level of a module."
  Otherwise, "An import declaration can only be used at the top level of a namespace or module."
(2) When the node is in a JS file, "An export declaration can only be used at the top level of a module."
  Otherwise, "An export declaration can only be used at the top level of a namespace or module."
(3) "A namespace declaration is only allowed at the top level of a module."

Implementation:
`checkGrammarModuleElementContext` issues these errors. I don't know whether it's better to make it smarter or just avoid calling it for case (1).

**Comment by fatcerberus** [comment]
Isn’t `export` used inside namespaces too?  So (2) should probably be “An export declaration can only be used at the top level of module *or namespace*.”

**Comment by vicente-s** [comment]
Hey everyone, I'd like to take on this issue.

**Comment by lokicodedaily** [comment]
can I work on this issue?

**Comment by sandersn** [comment]
@lokicodedaily sure, although you might want to co-ordinate with @vicente-s.

**Comment by sandersn** [comment]
@fatcerberus Good point. I updated the Expected seciont.

**Comment by islandryu** [comment]
@sandersn 
I tried to fix it in #47076, but did I do something wrong in the PR procedure?
I would be grateful for any feedback.

**Comment by sandersn** [comment]
@islandryu I'm backlogged on community PRs. I'll review it when I can.

**Comment by DanielRosenwasser** [comment]
Thank you @islandryu!
