### ISSUE TITLE
warning: Experimental support for decorators is a feature that is subject to change in a future release

### ISSUE THREAD

**Issue by chenqiangkobe** [microsoft/TypeScript#47084]
# Bug Report

### 🔎 Search Terms

Experimental  decorators

### 🕗 Version & Regression Information

monaco: v0.30.1
typescript: 3.2.4

### 💻 Code
playgroud code:
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
	noSemanticValidation: true,
	noSyntaxValidation: false
});

// compiler options
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
	target: monaco.languages.typescript.ScriptTarget.ES2015,
        experimentalDecorators: true,
	allowNonTsExtensions: true
});

var jsCode = [
    'import { Injectable } from \'@angular/core\';',
    'import { ApplicationParamService } from \'@farris/command-services\';',
    'import { HttpClient, HttpHeaders } from \'@angular/common/http\';',
    '@Injectable()',
    'export class List1FrmWebcmpService {',
        'constructor(private obj: ApplicationParamService, private http:HttpClient) {',
            'this.obj.parseParams;',
        '}',
        'private get() { }',
        'set() { }',
    '}'
].join('\n');

monaco.editor.create(document.getElementById('container'), {
	value: jsCode,
	language: 'typescript'
});

### 🙁 Actual behavior

'List1FrmWebcmpService' has underline&warning ' Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning '

### 🙂 Expected behavior
'experimentalDecorators: true' option not wok,how to remove this warning?

**Comment by MartinJohns** [comment]
Did you mean to set `typescriptDefaults` instead of `javascriptDefaults`? Regardless, this doesn't seem to be an issue with TypeScript itself.

> typescript: 3.2.4

Are you really using a version released on 3. January **2019**? The latest version is 4.5.2.

**Comment by chenqiangkobe** [comment]
@MartinJohns  I use **typescriptDefaults** instead of **javascriptDefaults**, the option **experimentalDecorators: true** works. Thanks a lot.
