### ISSUE TITLE
Feature: warn about function expression used as boolean

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#4708]
(I guess this may have been raised before, but it's hard to search...)

I think there should be a warning about usages like
```
if (functionToCheckIfWeShouldDoBadThings) { // <- forgot to invoke the function.
    doBadThings();
}
```

Specifically, the warning should be given when an expression evaluating to a function is coverted to a boolean variable/argument. (I.e. `var which: Function  = funA || funB` would not cause a warning.)

If the user really want to use a function as a boolean, they can trivially add a type assertion or `!!`. (In this case, `!!` should be treated specially to not generate a warning.)

**Comment by ahejlsberg** [comment]
While I sympathize with the issue, I think common patterns like these would be broken by what you suggest:

```typescript
if (callback) {
    callback(x, y);
}

var result = callback? callback(x, y) : 0;
```

I think it would be quite an irritant if we required `!!` in situations like those.

**Comment by billccn** [comment]
Yeah, that was my concern as well. I was trying to think of some kind of AST check that looks for trivial cases like this and suppress the warning, but there are simply too many cases to cover and makes the feature unpredictable.

A possible compromise is to hide this feature behind a compiler flag (similar to the implicit `any` one), so people who are willing to be slightly inconvenienced for safety can have the option.

**Comment by billccn** [comment]
Yeah, that was my concern as well. I was trying to think of some kind of AST check that looks for trivial cases like this and suppress the warning, but there are simply too many cases to cover and makes the feature unpredictable.

A possible compromise is to hide this feature behind a compiler flag (similar to the implicit `any` one), so people who are willing to be slightly inconvenienced for safety can have the option.

(It might still be worthwhile to implement some suppression for very simple and clear cases though.)

**Comment by ahejlsberg** [comment]
@billccn Just curious, what is an example of a simple and clear case where we should do this?

**Comment by billccn** [comment]
@ahejlsberg I am thinking in terms of AST checks for the cases that using the function expression as a boolean leads straight to the function being called. Like the two examples you gave in the comment above and the case like `fun && fun()`. All with no other expressions between the boolean part and the call part.

**Comment by mhegazy** [comment]
this looks like a tslint rule that teams can opt in/opt out from based on their policy rather than a cross cutting compiler check.

**Comment by billccn** [comment]
@mhegazy As far as I can see, tslint can only work with the AST with no type information and this analysis can't really be done without typing.

**Comment by mhegazy** [comment]
TSLint uses the LS for things like unused variables. you can query the LS for the kind of a symbol.

**Comment by mhegazy** [comment]
As mentioned in the earlier comments, this is more of local style that can be enforced by a tslint rule, than a generic rule that can be applied all the time by the compiler.
