### ISSUE TITLE
wrong generic type.

### ISSUE THREAD

**Issue by Bezmehrabi** [microsoft/TypeScript#47082]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.5.1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXywGcB5YYAHgBV4QAPDEVYQ+VZAWwCMQZ4BeeAEYAfAAo27AFzxKASmkTuMANwAoUJFgIU6bHgKEAogDdG5AFI16jZvEIYYWVAHN+8AOQALEBAg53ADQyVgxMLIo8biLiHNJyChxKaqoA9CnwAO44MADWhKpEpMCiAKyyyWmZ2XkFRqaoogAssqqp6Vm5+UQmZu6cAJ4ggfAlYmWtlR15BIjw-TjI8AAOUIQsGN7woIhQyBAY8MZQEMggtT2o5H2D7mKCLW1bOCCEqO4HU+f1VwNDYw9AA)

### 💻 Code

```ts
declare function isOdd<T extends number = 1>(num: T): number;
declare function isEven<J extends string = 'hello', T extends number = 1>(num: T): number;

// works
isOdd(5);

// works
isEven(4)

// works
isEven<'bye', 5>(5)

// works if you pass the default value
isEven<'bye'>(1)

// doesn't work
isEven<'bye'>(5)
```

### 🙁 Actual behavior

in the last example, the `T` type is `number` and it throws an error.

### 🙂 Expected behavior

in the last example, the `T` type should be `5`.

**Comment by MartinJohns** [comment]
This is working as intended.

TypeScript does not support partial type inference (see #26349). In your last example you only provided the type argument for `J`, but not for `T`. As a result the provided default type for `T` is used, which is `1`. Passing the value `5` to this is an error.

**Comment by Bezmehrabi** [comment]
I didn't know that, thanks!
I'll close the issue.
