### ISSUE TITLE
TypeScript service reports interfaces as a variables

### ISSUE THREAD

**Issue by andrecasal** [microsoft/TypeScript#47086]
### 🔎 Search Terms

vs code, suggestions, variables

### 🙁 Actual behavior

[According to Martin](https://github.com/microsoft/vscode/issues/138677#issuecomment-989766666):

> The TypeScript service reports the AbortController as a variable. That's related to how the typing were designed
> ```
> declare var AbortController: {
>     prototype: AbortController;
>     new(): AbortController;
> };
> ```

### 🙂 Expected behavior

I'd expect the TypeScript service to report all interfaces as interfaces.

**Comment by RyanCavanaugh** [comment]
We emit some of these global constructors with inline types to reduce the total number of global symbols, which is generally a convenience. This has been the case since release -- what's the bug here?

**Comment by andrecasal** [comment]
Apparently, in VS Code, when the TS extension generates the interface suggestions, [it marks them as variables](https://github.com/microsoft/vscode/issues/138677), making them show and hide with the `"editor.suggest.showVariables": false` instead of the `"editor.suggest.showInterfaces": false` setting.

**Comment by RyanCavanaugh** [comment]
This declaration represents the variable in the browser called `AbortController`. You can check it in your console:
```
> AbortController
< ƒ AbortController() { [native code] }
```
Hiding/showing this variable according to the hide/show variables is the intended behavior.

**Comment by andrecasal** [comment]
Isn't AbortController a _constructor function_ for the [AbortController API](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)?

It's not a variable as in `let a = 10`, right? What am I missing?

**Comment by fatcerberus** [comment]
It is a variable in the sense that it's a value you can pass around, because functions and classes are first-class values in JS.  Interface in TS parlance means something like `interface Foo {}`, i.e. a pure type.  Looking at the declaration...

```ts
declare var AbortController: {
    prototype: AbortController;
    new(): AbortController;
};
```

...it seems that the interface should also exist *in addition to* the variable representing the constructor, otherwise it wouldn't be a valid declaration.

**Comment by andrecasal** [comment]
Thanks @fatcerberus, I was suspecting `AbortController` was a variable in the weak sense of being an identifier.

It's definitely not an interface in the TS sense, but shouldn't it be annotated as a `class`, `constructor`, or `function`?

I don't think it makes sense to toggle JS's Web APIs on the suggestions box with the [`editor.suggest.showVariables` setting](https://github.com/microsoft/vscode/issues/138677).
