### ISSUE TITLE
Public<Type> - make private class properties in to public

### ISSUE THREAD

**Issue by AvshT** [microsoft/TypeScript#47083]
**One Usage:**
```
export class A {
private a1:string;
    #a2: string;

    constructor(p: Public<A>) {
        Object.assign(this, p);
    }
}
```

**Comment by RyanCavanaugh** [comment]
Duplicate #22677

To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
