### ISSUE TITLE
emit code didn't follow `.mts` `.cts` extensions

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#47093]
# Bug Report

### 🔎 Search Terms

mts

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

temp.cts
```ts
export default 77
```

temp.mts
```ts
export default 88
```

### 🙁 Actual behavior

`.cts` output as `esm` when tsconfig is `"module": "esnext"`
`.mts` output as `CommonJS` when tsconfig is `"module": "CommonJS"`

### 🙂 Expected behavior

`.cts` should always output as `CommonJS` when tsconfig is `"module": "esnext"`
`.mts` should always output as `esm` when tsconfig is `"module": "CommonJS"`

**Comment by IllusionMH** [comment]
AFAIK `.cts` and `.mts` are only supported with `module` set to `node12` and `nodenext`
See https://www.typescriptlang.org/docs/handbook/esm-node.html for details about experimental (Nightly builds only) support for these types of files.

**Comment by weswigham** [comment]
This is working as expected - these extensions function identically to .ts (in terms of emit) except in the node12 and nodenext module modes, where they adopt the emit implied by the extension.
