### ISSUE TITLE
Issue with appoint parameter

### ISSUE THREAD

**Issue by OlegDokuka** [Microsoft/TypeScript#4709]
Hi guys, I have gotten issue during compilation and have no idea how to fix it.

`The argument type "typeof A" impossible appoint parameter type "{new (): any; new (... args: any []): any;}"`

```typescript

@someannotation
class A {
    constructor(a: string) {

    }
}
```
here someannotation function
```typescript
export function someannotation(clazz: Class){

}
```
here Class definition
```typescript
 export type Class = {
        new (): any;
        new (...args: any[]): any;
    };
```

Are there any way to declare `new (something here):any` that would be available for any kind of constructor include abstract class

**Comment by DanielRosenwasser** [comment]
This isn't one of our error messages. Are you using WebStorm?

**Comment by OlegDokuka** [comment]
nope, it is in russian language.

here is the original message :
`TS2345	Аргумент типа "typeof A" нельзя назначить параметру типа "{ new (): any; new (...args: any[]): any; }".	Typejector	D:\WorkSpace\VisualStudio\Project\Typejector\Typejector\app.ts	2`

**Comment by DanielRosenwasser** [comment]
Also, our language service [seems to be fine with it](http://www.typescriptlang.org/Playground#src=%20type%20Class%20%3D%20%7B%0A%20%20%20%20new%20()%3A%20any%3B%0A%20%20%20%20new%20(...args%3A%20any%5B%5D)%3A%20any%3B%0A%7D%3B%0A%0Afunction%20someannotation(clazz%3A%20Class)%7B%0A%0A%7D%0A%0A%40someannotation%0Aclass%20A%20%7B%0A%20%20%20%20constructor(a%3A%20string)%20%7B%0A%0A%20%20%20%20%7D%0A%7D).

**Comment by DanielRosenwasser** [comment]
Just tried it out with 1.6 beta, seeing it. The issue is that your type alias shouldn't have both `new (...args: any[]): any;` and `new (): any;` because it requires that `A` needs both constructor overloads. Try removing `new (): any;`.

**Comment by OlegDokuka** [comment]
Yep, I see, but I still have this issue in my VS 2015. I`m using TS 1.6-beta.

**Comment by OlegDokuka** [comment]
oh, yep it  work fine, but what about abstract class? Ara there any way to use `Class` for abstract classes

**Comment by OlegDokuka** [comment]
Here is an example of code

```typescript
type Class = {
    new (...args: any[]): any;
};

function someannotation(clazz: Class) {

}

@someannotation
abstract class A {
    constructor(a: string) {

    }
}
```

**Comment by DanielRosenwasser** [comment]
I believe that for now, the only way to do that is to use `Function` instead of your `Class` type which what [the decorator declarations](https://github.com/Microsoft/TypeScript/blob/971c7770314467964c536242becad2555ef9c758/src/lib/core.d.ts#L1168) right now. I've brought the issue here up in #4693.
