### ISSUE TITLE
Ability to exclude some compiled .ts files from output

### ISSUE THREAD

**Issue by markbook2** [Microsoft/TypeScript#4710]
It would be good (and probably necessary for big projects) to have implementation that supports the following (I will provide a concreate example) use case:

1. I have the terminal.ts file that depends on the core.ts, env.ts files:
```
///<reference path="env">
///<reference path="core">

// this is terminal.ts
```
2. I already included the compiled version of it in the main index.html file:
```html
<html>
...
<script src="env-core-terminal_merged.js"></script>
</html>
```
The env-core-terminal_merged.js contains compiled content of the following files: env.ts, core.ts, terminal.ts. I created the env-core-terminal_merged.js file with the following command:
```
tsc --out public/js/env-core-terminal_merged.js terminal.ts
```
In this case the tsc will find all files (env.ts and core.ts) using ///reference directive and merge them into one.
3. Now for some area of the site I need other files, say editor.ts that depends on env.ts, core.ts and other editor specic files: color.ts, mode.ts:
```
///<reference path="env">
///<reference path="core">
///<reference path="color">
///<reference path="mode">

// this is editor.ts
```
I want to include it like this:
```html
<html>
...
<script src="env-core-terminal-merged.js"></script>
<script src="color-mode-editor_merged.js"></script>
</html>
```
and I created it with the following command:
```
tsc --out public/js/color-mode-editor_merge.js editor.ts
```
But now there is a problem: as the editor.ts depends on the core.ts and env.ts the tsc will paste the compiled content of them into the color-mode-editor_merged.js again. But I need to have only one the compiled content of the core.ts, env.ts be included. I can't include only one file that will have compiled content for the all .ts files and replace the env-core-terminal-merged.js with it, because the site has block architecture and each block can define its own javascript files and have a common part for all blocks (in this case the common part is defined in the env-core-terminal-merged.js) For now to resolve of this problem I can only open the color-mode-editor_merged.js with editor and delete the compiled content of the core.ts and env.ts by hand (manually).

**Comment by weswigham** [comment]
I believe the conventional wisdom right now is to reference the generated `.d.ts` files for the files whose sources you don't wish to compile, rather than the original sources.

**Comment by markbook2** [comment]
@weswigham, yes it works, thanks.
