### ISSUE TITLE
Use type as value

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [microsoft/TypeScript#47103]
# Suggestion
Transform types to values.

## 🔍 Search Terms
type value

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Not sure if option number 3 should be checked or not...

## 📃 Motivating Example
I was coding and I had this function:
```typescript
function writeTags(pathOfMedia: string, data:  Readonly<{
 	pictureURL?: string;
  	genres?: string;
        artist?: string;
        album?: string;
 	title?: string;
}>) {}
```
And I needed to get the type of `data`:
```typescript
// I did this workaround:
const allowedOptionToChange: Readonly<
	Array<keyof Parameters<typeof writeTags>[1]>
> = ["pictureURL", "genres", "artist", "album", "title"];

type ChangeOptions = typeof allowedOptionToChange[number];
// ^ type ChangeOptions = "genres" | "artist" | "album" | "title" | "pictureURL"
```
Would be great if I could do something like this:
```typescript
type ChangeOptions = keyof Parameters<typeof writeTags>[1]
// ^ Equals to: `type ChangeOptions = "genres" | "pictureURL" | "artist" | "album" | "title"`.

const foo = keyof ChangeOptions;
// ^ And receive: `foo = Object.freeze(["pictureURL", "genres", "artist", "album", "title"]);`
// on the Javascript side.
// One thing is that the type of `foo` would not actually be the type `ChangeOptions`...
```

## 💻 Use Cases
This would be amazing to get the types and use them as values cause we wouldn't need to type so much more.

**Comment by xiBread** [comment]
https://github.com/kimamula/ts-transformer-keys

**Comment by Gabriel-Alves-Cunha** [comment]
> https://github.com/kimamula/ts-transformer-keys

That's awesome😊
