### ISSUE TITLE
Wrong import assist

### ISSUE THREAD

**Issue by Tysiachnyi** [microsoft/TypeScript#47110]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.5.2

**Search Terms**
- jsx
- react

---

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.62.3 (Universal)
- OS Version: macOS 12.0.1

Steps to Reproduce:

1. Create TSX component which using HOC 
<img width="1157" alt="Screenshot 2021-12-07 at 22 52 16" src="https://user-images.githubusercontent.com/31761316/145104543-cd9dd7b9-d28b-42c2-b795-18cca06ae9e4.png">

2. Try to write component name inside tag, and autosuggestion was wrong 
<img width="1237" alt="Screenshot 2021-12-07 at 22 52 48" src="https://user-images.githubusercontent.com/31761316/145104654-0acebd11-376d-4644-a83c-6cdda6451903.png">

**Comment by mjbvz** [comment]
Thanks!

For TS Team: I believe this happens because `ComponentAsync` is a default export and the name is generated from the file name. You can test this by changing the filename to `component-foo`

However I don't understand why using the lowercase version produces an error in this case

**Comment by andrewbranch** [comment]
JSX tags starting with a lowercase letter are assumed to be intrinsics (e.g. `<div />`). We need to change the autogenerated name for default exports when we’re in a JSX opening tag.
