### ISSUE TITLE
TypeScript compiler incorrectly handles /// <reference path = "..." />

### ISSUE THREAD

**Issue by KostyaTretyak** [microsoft/TypeScript#47114]
# Bug Report

TypeScript compiler incorrectly changes relative path from

```ts
/// <reference path = "../src" />
```

to

```ts
/// <reference types = "src" />
```

### 🔎 Search Terms

- triple-slash

### 🕗 Version & Regression Information

4.5.3

### 💻 Code

I have [my own npm package][1], which depends on [jsonwebtoken][2]. There are corresponding TypeScript types on `@types/jsonwebtoken`, but I wrote a better definition for this library, placed it in the `src/types/jsonwebtoken.d.ts` and imported it into `src/index.ts`:

```ts
/// <reference path="../src/types/jsonwebtoken.d.ts" />
```

### 🙁 Actual behavior

With `tsc -b -f` command (it doesn't matter if it's from a root or another directory),  TypeScript compiler incorrectly changes this import inside `dist/index.d.ts`:

```ts
/// <reference types="src/types/jsonwebtoken" />
```
I think this is a bug because the [documentation][3] does not describe this behavior:

> A triple-slash reference path is resolved relative to the containing file, if a relative path is used.

  [1]: https://github.com/ditsmod/ditsmod/tree/jwt-2.0.0-next.1/packages/jwt
  [2]: https://github.com/auth0/node-jsonwebtoken
  [3]: https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

### 🙂 Expected behavior

Everything would work fine if in `dist/index.d.ts` there were such imports:

```ts
/// <reference types="../src/types/jsonwebtoken" />
```

**Comment by weswigham** [comment]
Your `baseUrl` compiler option means that `src/types/jsonwebtoken` is considered a valid nonrelative path to access that file, and since we prefer using nonrelative paths where possible, we use that instead. Simply remove your `baseUrl` compiler option if this is not your intent.

**Comment by KostyaTretyak** [comment]
Thanks. But the connection between `baseUrl` and the behavior of the compiler in this case is not obvious. The [documentation](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) does not say that this connection exists.
