### ISSUE TITLE
conditional generic Type assignable Error

### ISSUE THREAD

**Issue by iahu** [microsoft/TypeScript#47127]
# Bug Report

### 🔎 Search Terms
`conditional`

### 🕗 Version & Regression Information

- This changed between versions `4.4.4`  and `4.5.2`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.2#code/C4TwDgpgBA0g9gOwG4EMCiSIOAeQEYBWEAxsADwAqAfFALxQDeAsAFCsC+rrEAHmHACdgUUJCgBxCMACyAVwA2wAJYVwESlF7AsAEwDOUPcAFKEAcxr0KmntoT6oAAwAkDUwDMIAqAEF2UVw8vKAAhdkdWKCgAfgkpOUUVNTIfGgAfOJkFZVVIMhCqSKgALihrLV0DFzcET28AYXYAOlcjE3NwotjJLMTc9XrClijS8ttKqABrCBA4dygAEThiWQBbLGAMDekUMC7YRFQt7HwiUjIllfXsY5ldgG0KAF0hkbKbOwcAcmBdr6gMj84LJiAALIwoIT-QHAYFg1ZwTDQqBAkGg4goBDECDyZGosG6L77eDIdCYE6EEjkChw0G3V4lA6k26nKlkelcNgsUTQAASmJ08mCdCgAAoIKUSUdybhKedMSAqABKOg0JBwJQ6VjERBGKCIEWinmlNqmMwAGigoIFQoEpX59ltKtoNGYXM4LB1CD1c3m9CNahNxjNlutjq89ptXmdrs5Hu4fEEwi9epgPgWAH0fPUKABJHAAOQzBYAyiKvpMUDofKQlIgiSxePwhFAU8IAO5KYCgmBVmvKRClw16IPtMwxsV6JqmYjyWQ6CB6UVfJpfFWxAylap6ZquNOZ7N5wvFkvhJUJ5vJ3XCLB6WQCCAAdS7oKH-uNhmD5gnPKaejA8hdsuKJKk0qy7KKnbdr21a1oOJagQQGoIMBa4XkmrbXvqWIQDgCAihoFT2AYprmFQRqQmYUilAWcALpaH4UJagF6BsEZihAMqlD0CQ5Mk1ATuqmoTm6URtiIajPt2b6aN695Pi+pYBpA57DJh3rCGGgrBP6nEbNx8TZEkeQCaqjBFFELFsQI4oyqpURRAA9I5rYoMAYJQJimgCAIggWfq7juMpCnSSWoZRgI9lQPGakPsA974YgwVSa+YVWhFqkxUAA)

### 💻 Code

```ts
type KonvaEventObject<T> = {

}

export type GetMultiType<T extends string> = T extends `${infer A} ${infer B}`
  ? GetMultiType<A> | GetMultiType<B>
  : T extends `${infer C}.${string}`
  ? GetMultiType<C>
  : T extends keyof DocumentEventMap
  ? KonvaEventObject<DocumentEventMap[T]>
  : T extends 'tap' | 'touchstart' | 'touchmove' | 'touchcancel' | 'touchend'
  ? KonvaEventObject<TouchEvent>
  : KonvaEventObject<Event>


type Handler  = (e: KonvaEventObject<any>) => void
const on = (type: string, handler: Handler) => {

}
const off = (type: string, handler: Handler) => {

}

export const KAD_ACTION_NS = 'kadAction'
export const withKadActionNS = (s: string) => (s.includes('.') ? s : `${s}.${KAD_ACTION_NS}`)
export const ensureWithNS = (type: string) => type.split(' ').map(withKadActionNS).join(' ')
export const onceOn = <T extends string>(target: Node, type: T, lisenter: (event: GetMultiType<T>) => void) => {
  const typeWithNS = ensureWithNS(type)
  const handler = (event: GetMultiType<T>) => {
    lisenter(event)
    // throw an error
    off(typeWithNS, handler)
  }
  // also throw an error here
  return on(typeWithNS, handler)
}

```

### 🙁 Actual behavior
Type 'KonvaEventObject<any>' is not assignable to type 'GetMultiType<T>'

### 🙂 Expected behavior
can assign type 'KonvaEventObject<NodeEventMap[T]>'  to type 'GetMultiType<T>'

**Comment by RyanCavanaugh** [comment]
Simplified
```ts
type EventWrapper<T> = {
  event: T;
}

export type GetEventType<T extends string> =
    T extends `${infer A} ${string}`
  ? GetEventType<A>
  : T extends keyof DocumentEventMap
  ? EventWrapper<DocumentEventMap[T]>
  : EventWrapper<Event>

function go<T extends string>(type: T, lisenter: (event: GetEventType<T>) => void) {
  const src: EventWrapper<any> = null as any;
  // OK in 4.4, error in 4.5
  // Should be OK [?]; all terminuses of GetEventType<T> are EventWrapper<any>'s
  const dst: GetEventType<T> = src;
}
```

**Comment by RyanCavanaugh** [comment]
This was an announced breaking change:

https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#restrictions-on-assignability-to-conditional-types

**Comment by RyanCavanaugh** [comment]
FYI @ahejlsberg for visibility anyway
