### ISSUE TITLE
I agree that a complete yank is better than the old half-yank, but it's not a resolution to this ticket imo.

### ISSUE THREAD

**Issue by Umer19** [microsoft/TypeScript#47124]
I agree that a complete yank is better than the old half-yank, but it's not a resolution to this ticket imo.

A minimum resolution here could be some kind of deprecation notice - so when mark a gem version as "deprecated" and/or yanked then the end user sees a bit of explanatory text, e.g.  a reference to a CVE number or something like that to close the loop on /why/ the gem was yanked.

_Originally posted by @sodabrew in https://github.com/rubygems/rubygems/issues/858#issuecomment-143475962_

**Comment by xiBread** [comment]
Wrong repository

**Comment by MartinJohns** [comment]
You seem very confused @Umer19, are you okay? #47122 #47120

**Comment by RyanCavanaugh** [comment]
![Lost John Travolta](https://c.tenor.com/fuiG0_pco2wAAAAM/confused-john-travolta.gif)
