### ISSUE TITLE
Distracting colour for @param in JSDoc

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#4712]
Hi,

**Version**: VS 2015 / TS 1.6

I believe this is actually a feature, but the white colour for `@` and the parameter names makes it rather difficult to read.

![image](https://cloud.githubusercontent.com/assets/1106823/9769444/25370e3a-5722-11e5-89cb-9221f6e7ddae.png)

I find this distracting, because it suggests there are method and parameter names (which are also in white) amongst the documentation.

Perhaps a different shade of green might work?

**Comment by RyanCavanaugh** [comment]
We've changed colorizers in the meantime
