### ISSUE TITLE
Support lodash and lodash/fp

### ISSUE THREAD

**Issue by Aster89** [microsoft/TypeScript#47135]
# Suggestion

(I'm a Vim user, and indirectly make use of `tsserver` via YouCompleteMe; [from there](https://gitter.im/Valloric/YouCompleteMe?at=61b60cb38853d3164044182c), I got the suggestion of filing a issue here.)

(I've looked into [Common Feature Requests](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-feature-requests), but I haven't found any substatial reference to Lodash, so I decided to file this request.)

## 🔍 Search Terms

  - lodash
  - fp
  - javascript

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

***As regards the non checked boxes, honestly I've looked into it, but I'm not experienced enough to understand what they even mean.***

## ⭐ Suggestion

I think better support for [`lodash`](https://lodash.com/) and [`lodash/fp`](https://github.com/lodash/lodash/wiki/FP-Guide) would be a good improvement.

## 📃 Motivating Example

With the suggested change we'd get diagnostics for a very powerful library like lodash. Probably that could also encourage somebody else to make use of it.

## 💻 Use Cases

For now, a lot of code is marked as wrong.

Here's an example from the linked conversation:

> The following line of JavaScript
> ```
> _.over([x => x.a, 'b'])({ a: 3, b: 4 });
> ```
> which returns `[3, 4]`, is detected as erroneous, the hightlighted part being `'b'`, which should be taken as a shorthand for `x => x.b`, and the error message being `Type 'string' is not assignable to type '(...args: any[]) => any'.`

As another example, using `lodash/fp` (I have `<script src="https://cdn.jsdelivr.net/g/lodash@4(lodash.min.js+lodash.fp.min.js)"></script>` in my HTML, and the JavaScript code does work), this is marked as erroneous too:
```javascript
const getQuestionsAndAnswers = _.compose(
  _.groupBy('post_type'),
  _.map(_.pick(['post_type', 'post_id', 'reputation_change'])),
  _.sortBy('post_id'),
  _.filter('reputation_change')
);
```
Every single `_` is marked red, with diagnostic `Cannot find name '_'.`.

**Comment by benwainwrightcinch** [comment]
Does `@types/lodash` not solve your problem?

**Comment by nmain** [comment]
>  The following line of JavaScript
>  ```
>  _.over([x => x.a, 'b'])({ a: 3, b: 4 });
>  ```
> which returns `[3, 4]`, is detected as erroneous, the hightlighted part being `'b'`, which should be taken as a shorthand for `x => x.b`, and the error message being `Type 'string' is not assignable to type '(...args: any[]) => any'.`

This appears to be a shortcoming in `@types/lodash`.  It doesn't support the `string` shorthand for iteratees.  I guess you would file something against DefinitivelyTyped for that.

**Comment by puremourning** [comment]
> configuring your editor to pick up that definition

I don't understand. the diagnostic in question is coming from `tsserver` which presumably reads the `jsconfig.json`. Unless there is some API provided by `tsserver` for configuration that we're not aware of I'm not sure there's anything for the "editor" (or, in this case the _client_ of `tsserver` which is ycmd) to do here?.

**Comment by fatcerberus** [comment]
tsserver doesn't *necessarily* read the js/tsconfig.  The application calling it is free to pass in any configuration it wants.

**Comment by puremourning** [comment]
But it says this in the documentation https://github.com/microsoft/TypeScript/wiki/Standalone-Server-(tsserver)#configured-project

Anyway, in this case, the calling application doesn't provide any config and it presumably loads from the jsconfig.json. Are we saying that there's something the user can add to jsconfig.json to support this or not? Or is there a specific thing that applications using tsserver via its API can do to solve this. I'm completely lost.

**Comment by fatcerberus** [comment]
`npm install @types/lodash`

**Comment by puremourning** [comment]
@Aster89 can you try that and report back?

**Comment by Aster89** [comment]
> `npm install @types/lodash`

After executing the above, the reported errors change. For instance, with reference to the snippet in my original message, `compose` is highlighted in red with message
> Property 'compose' does not exist on type 'LoDashStatic'.

Furthermore, in a thing like this
```cpp
_.groupBy('post_id')(answers);
```
`_.groupBy('post_id')` is highlighted in red with error message
> This expression is not callable.   Type `'Dictionary<[string, ...string[]]>'` has no call signatures.

but uncurrying the call, `_.groupBy('post_id', answers);`, which in general might be not doable, solves the problem.

**Comment by Aster89** [comment]
> I guess you would file something against DefinitivelyTyped for that.

Would you suggest the most appropriate way to do so? I don't find a repo named that way.

**Comment by fatcerberus** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by Aster89** [comment]
Oh, ok, I didn't think there could be a typo. Thanks

**Comment by Aster89** [comment]
@nmain , by the way. Is your suggestion for both the mis-disgnostics when using `lodash` and `lodash/fp`?

**Comment by nmain** [comment]
Your example seems to work well enough in the playground as a module: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAfTgMyhEcBEAbCATAQwGcALAemTEwChqBjCAOyPgHMBTGARQFd2XgTIgEFGeUUQDu7KETgBeRADoG4CEXYAKanGWs0PMACEAnpoDkkFghgmw7cwEoANDuUgCYTQiVhgdAGtNAG1LdRgbOwdnODDrYDxzGPModjAeGAIYQUYEOhICRg5zAF1HFzcfImgYUwsrCISnV10fZGBsGBkLVPTM7KY8gqKHR2pHAG5qIA

So whatever's going wrong there may be something related to your particular dev and build environment?  Not sure.

**Comment by Aster89** [comment]
@nmain , concerning your last message, when I click on the link, I see there's one error on the `import` that reads like this:

> `Cannot find module 'lodash/fp' or its corresponding type declarations.`

Does it _not_ work well, or have I misunderstood what you mean?

**Comment by Aster89** [comment]
@puremourning , as suggested earlier by @nmain (and also [here](https://github.com/lodash/lodash/issues/4326)), [I'm seeking help in `DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23532). Would you mind giving a look at that, in case you can suggest more info I could give them?
