### ISSUE TITLE
Type of union of objects lists excess properties

### ISSUE THREAD

**Issue by bbenezech** [microsoft/TypeScript#47132]
# Bug Report

### 🔎 Search Terms

union type excess undefined properties

### 🕗 Version & Regression Information

All versions available in playground (from `3.3.3` to `4.5.2`)

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.5.2#code/GYVwdgxgLglg9mABFApgZygCmAGwIYDmAXIgEZxw4p5gCUiA3gLABQi7iVUiAbnjiBQBuVqw6IYwRNnwF6zNuI58BKRAF5GYpTqgBPAA4oSAcgAqATQAKAUQCMJxHjSIICDABptO8XihQAJxhSEFQ7Uz9A4NCUBycXNzBPbyUAXxTUxBQcNDUFH15+QQ0tRQL2fSNTS1sAJkdnV3coLzLyyKCQ1FqI-06Y+vimpKgU8XS2iZTKtQA1IpQzQzVNGbgpFUERFhSAlCgQAKRNlFYJoA)

### 💻 Code

```ts
function test(flag: boolean) {
    let value;

    if (flag) {
        value = {
            type: 'TYPE1' as const,
            attribute1: 'attribute1' as const,
        }
    } else {
        value = {
            type: 'TYPE2' as const,
            attribute2: 'attribute2' as const
        }
    }

    type ValueType = typeof value;

    return value
}
```

### 🙁 Actual behavior

`ValueType` is
```typescript
type ValueType = {
    type: "TYPE1";
    attribute1: "attribute1";
    attribute2?: undefined;
} | {
    type: "TYPE2";
    attribute2: "attribute2";
    attribute1?: undefined;
}
```

### 🙂 Expected behavior

It should be:

```typescript
type ValueType = {
    type: "TYPE1";
    attribute1: "attribute1";
} | {
    type: "TYPE2";
    attribute2: "attribute2";
}
```

Please note that hovering `value` shows the correct type.
<img width="497" alt="Screenshot 2021-12-13 at 11 32 57" src="https://user-images.githubusercontent.com/26794/145797360-6c3ac5ea-3b19-42bf-ac27-f3c70afb86ad.png">
<img width="523" alt="Screenshot 2021-12-13 at 11 32 50" src="https://user-images.githubusercontent.com/26794/145797376-ec816ce1-db4a-4f77-9e8c-f74ac8a06de6.png">

**Comment by MartinJohns** [comment]
This is working as intended, but I can't find a more fitting issue than #44247 right now. The type that `ValueType` shows is also the one that your function returns. You can prevent this by adding a type annotation to explicitly type your variable / function.

**Comment by bbenezech** [comment]
Thank you for your answer. 

I am still puzzled by the hovering part.
Why is the value's type tooltip different from the value's type itself? Is it somehow "cleaned up" (undefined values removed)? Or something else?

FYI, my use-case is openapi generation, which doesn't know what to do with a value that is always undefined.

Anyway I imagine there is a good reason for this, because it feels very remote from the straightforward "what you see is what you get" usual behaviour of the type engine.

This looks awkward for example: https://www.typescriptlang.org/play?ts=4.5.2#code/GYVwdgxgLglg9mABFApgZygCmAGwIYDmAXIgEZxw4p5gCUiA3gLABQi7iVUiAbnjiBQBuVqw6IYwRNnwF6zNuI58BKRAF5GYpTqgBPAA4oSAcgAqATQAKAUQCMJxHjSIICDABptO8XihQAJxhSEFQ7Uz9A4NCUBycXNzBPbyUAXxTUxBQcNDUFH15+QQ0tRQL2fSNTS1sAJkdnV3coLzLyyKCQ1FqI-06Y+vimpKgU8XS2iZTJaRVBADpKtXUVxHNrexN6AJQoEACwERYUgHoTpz7osMQwOG5+HDgAdxQAExTEtEoUeceCTDmPw6V1itCOKR2ewOhVUrCmLFAkFgCGQ6CgtRkhBI5G+NHkKS4MME4LaM0xclKBUBJXy5QqhmMaxqmyGnxaYx8wK6sV6UW5cUabNaBQm4yyOTyHPY1M0tLpS2qG0GguawrpFz5A15-W6DQSzSliFFHHh4kh+yQgLhogR4Gg8CQIFyZjRGPxbTZROWqIwGMCgjB0ykAKKPyWGlW61sDm2uwtJPEZw1OtiThwjxe7w97m+vzg-0B8y5MTsgZYqSAA

**Comment by RyanCavanaugh** [comment]
See https://github.com/microsoft/TypeScript/pull/19513 for motivation.

Re: quick info, type display for values tries to shorten things a bit to keep them more readable on-screen.
