### ISSUE TITLE
Inconsistent QuickInfo on type-only imported symbols

### ISSUE THREAD

**Issue by lowr** [microsoft/TypeScript#47134]
# Bug Report

### 🔎 Search Terms

type-only import quickinfo modifier specifier

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because the `type` modifier on import names had only been introduced in the latest version.

### ⏯ Playground Link

[bug workbench](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKW0BGA6AFwGcBYAKHgA8AHAewCdDRCBPG+UAQVAF5REAV1S54DANwVq9Ji3acAQnwHDREqbUbMAxnUTFmPfgBYATJMqbZu-cyUnzFCiAgwEKdFlTJoiImXJoVBlmNg5QAG9uUABfUEgGOlRQACJ8YBxcFIsXUDz8gtAAPQB+CiCQyLlwpTiEpNT0zOznMEL20qA)

### 💻 Code

```ts
// @filename: lib.ts
export type A = number;
export type B = number;
export const A = 42;
export const B = 42;

// @filename: main.ts
import type { A } from "./lib";
import { type B } from "./lib";
```

### 🙁 Actual behavior

Hovering on `A` in the import statement gives you:

```
(alias) type A = string
import A
```

### 🙂 Expected behavior

Hovering on `A` gives you:
```
(alias) type A = string
(alias) const A: 42
import A
```
like hovering on `B` does, because you can use `A` as a value as long as it's in type contexts.

**Comment by lowr** [comment]
On a second thought, this may be the other way around, that is, QuickInfo on `A` should actually give you alias for both type and value. Am I right that TypeScript lets you import with `type` modifier and use values as long as they are in type contexts?

reference: https://github.com/microsoft/TypeScript/issues/40583#issuecomment-693542271

@RyanCavanaugh Sorry to bother you, but could you re-triage this issue?

**Comment by RyanCavanaugh** [comment]
> Am I right that TypeScript lets you import with type modifier and use values as long as they are in type contexts?

Correct.

I don't have a strong opinion either way on how these should display, but since they mean the same thing they should display the same way.

**Comment by lowr** [comment]
Thanks, I've updated the bug report accordingly.
