### ISSUE TITLE
Questions about type inference for tuple types in 1.6 spec

### ISSUE THREAD

**Issue by osdm** [Microsoft/TypeScript#4713]
The following text was added in 1.6 spec (3.11.7):
> Otherwise, if S and T are tuple types with the same number of elements, inferences are made from each element type in S to each corresponding element type in T

It's a little bit unclear why special processing for tuples is needed. Inferences for element types would be made anyway, because default processing for object types would make inferences for each property, including tuple numerical properties. Is it just to prevent inferences for numerical index signatures? Could you provide an example where default processing can go wrong?

And the second question. What happens if S and T are tuple types with different numbers of elements? Default processing for object types or no inferences at all?

**Comment by DanielRosenwasser** [comment]
> What happens if S and T are tuple types with different numbers of elements? 

I believe that in this case, default processing for object types takes effect, so inferences are made from properties { `0`, `1`, ... `n` }.

@ahejlsberg might be able to answer your other question (and potentially correct me).

**Comment by ahejlsberg** [comment]
See #4153 regarding your first question.

Regarding your second question, if tuple lengths don't match we just do the default processing for object types.

**Comment by osdm** [comment]
Thanks!
