### ISSUE TITLE
infer on setter argument gives unknown

### ISSUE THREAD

**Issue by Galphimbl** [microsoft/TypeScript#47146]
# Bug Report

### 🔎 Search Terms
setter, getter, infer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Conditional Types

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211214#code/JYOwLgpgTgZghgYwgAgCoQM5gIzIN4CwAUMqcgOYRjIAOUA9jQBQCUAXMllKOQNzFlOVWg2YA3Dlx7IAPshABXALYAjaC35EAvsTABPGigDKVSFFQGIAHlQAaZAGlkEAB6QQAEwzIA1hD30MGgAfMgAvGjObhCe3ngYwgDaAArIoI4AukwSaSAw0MgAqhpayAD8RcgcqIkOGZrEHhAIADZwUCgI9CBYQmBmHCb90BaGNpg49gDkdIxTwbzIAPRLyAogPiD0AO4gyEA)

### 💻 Code

```ts
interface Test1 {
    get prop(): string;
    set prop(v: string | number);
}
type SetterType<T, K extends keyof T> = T extends {set [P in K](v: infer U);} ? U : T[K];

declare const setter: SetterType<Test1, 'prop'>; // unknown 
```

### 🙁 Actual behavior
Hovering on `setter` gives you
```ts
const setter: unknown
```

### 🙂 Expected behavior
Hovering on `setter` gives you
```ts
const setter: string | number
```

**Comment by RyanCavanaugh** [comment]
😲 `set [P in K](v: U)` was never supposed to be allowed syntax. I'm honestly shocked this doesn't crash; the syntax doesn't really work at all.

The "fix" here is to make this a syntax error, at least for now.

**Comment by Galphimbl** [comment]
@RyanCavanaugh i try yo get setter type, is there any solution ?

**Comment by fatcerberus** [comment]
TypeScript doesn't really distinguish between accessors and regular properties at the type level, so `Test1['prop']` is about the best you can do.

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh Should TS throw the following error?
```ts
A computed property name must be of type 'string', 'number', 'symbol', or 'any'.
```

**Comment by RyanCavanaugh** [comment]
The error should be that `get`/`set` can't be combined with mapped types.

```ts
type Foo1<K extends string> = {[P in K]: number};
// Should error
type Foo2<K extends string> = {get [P in K](): number};
//                             ^^^^^^^^^^^^
//  Cannot combine property get/set with mapped type syntax

type A = Foo1<"prop">;
type B = Foo2<"prop">;

type AP = A["prop"];
type BP = B["prop"];
// ^ never worked anyway
```

**Comment by Galphimbl** [comment]
I tried to work with the changes added in release 4.3 ("Separate Write Types on Properties"), but there is no way to select only those setter keys that accept a specific data type.

**Comment by RyanCavanaugh** [comment]
The future's a long time, but no this is not part of the scheduled roadmap

**Comment by RyanCavanaugh** [comment]
Wow, this is *super* broken...
```ts
type OH_NO = {
  get [K in WAT](): string
};
```

**Comment by MartinJohns** [comment]
@Galphimbl You might want to follow #43729.
