### ISSUE TITLE
Support for multiple tsconfig.json files in ASP.NET v5 projects

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#4714]
We want to enable the ability to have more than 1 `tsconfig.json` file in an asp.net v5 project, this will make the compilation of ts files more flexible.

```
/Common.Classes
   - tsconfig.json {out: "../Outputs/Common.Classes.js"}
   - Class1.ts
   - Class2.ts

/Common.Plugins
   - tsconfig.json {out: "../Outputs/Common.Plugins.js"}
   - Class3.ts
   - Class4.ts

/Outputs
   - Common.Classes.js
   - Common.Plugins.js
```
See these comments: 
https://github.com/Microsoft/TypeScript/issues/4161#issuecomment-129369116
https://github.com/Microsoft/TypeScript/issues/4161#issuecomment-137248228

**Comment by mjohnsonengr** [comment]
Will this allow me to have my tsconfig.json in some other location?

Currently, our structure has all of our typescript files in /projectroot/client; naturally I created my tsconfig file in that directory originally.

**Comment by paulvanbrenk** [comment]
@mjohnsonengr Yes, that will work for 1.8, further for 1.7 we made a small change to allow the `tsconfig.json` in the root of your project, so that should work with your project structure.

**Comment by basarat** [comment]
@paulvanbrenk curious what will happen if we have a `.ts` file in two projects. Show both errors? Show both autocomplete entries?

**Comment by paulvanbrenk** [comment]
Yep, that will give 2 errors.. similar to what happens when you use 'linked files' in C# projects. And you do want two errors, since they are potentially in a different context (e.g. es3, and es5)... the effort to filter out true duplicates is probably not worth it. <insert remark about trade-off between features, and value-add, and time>

**Comment by basarat** [comment]
> the effort to filter out true duplicates is probably not worth it

Completely agree :rose: :+1:

**Comment by lcorneliussen** [comment]
What is the status on this issue? Release date yet known?

**Comment by paulvanbrenk** [comment]
Still planned for 1.8, no concrete date yet.

**Comment by mhegazy** [comment]
Should be fixed in TS 1.8

**Comment by MrAndMrsK** [comment]
Is this actually fixed in 1.8?  And is it specifically limited to the ASP.NET v5 project type?  I'm using a C# console app with the old .targets manually added but visual studio complains about duplicate definitions and does not seem to be honoring either of my tsconfig.json files' output settings.  

(This is for an Electron project that I'm trying to organize and basing it on an ASP.NET web project with a web server and so on is unnecessary overhead.  I'm struggling to get a really clean setup going for this in Visual Studio.)

**Comment by mhegazy** [comment]
@MrAndMrsK can you share your project, and/or a build log (msbuild /v:detailed)?

**Comment by mhegazy** [comment]
also what version of TS are you using in VS?

**Comment by paulvanbrenk** [comment]
@MrAndMrsK for a Console App, I would recommend using the NuGet package to get the best experience. https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild/

**Comment by MrAndMrsK** [comment]
@paulvanbrenk - Cool, that's good to know but it didn't fix the problem.

@mhegazy - I already updated my PATH to 1.8 (which I keep having to do manually??) and rebooted.  Visual Studio was already using 1.8, yes, and now with the suggested NuGet package I can see the `1.8.4` being used by msbuild.  

Here's the project structure, with the newly placed/refreshed files output in the wrong place:

![image](https://cloud.githubusercontent.com/assets/5518652/13270716/f8ecbc48-da5d-11e5-92bb-87262e0de9b7.png)

Contents of one of the two similar .tsconfig files:

```
{
    "compilerOptions": {
        "module": "system",
        "target": "es5",
        "noImplicitAny": true,
        "outFile": "main.js",
        "outDir": "../built",
        "rootDir": ".",
        "sourceMap": false,
        "noLib": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

And the build log:

http://hastebin.com/fuhozojicu.tex

**Comment by mhegazy** [comment]
the log indicates that there were no config files, so obviously something went wrong there. can you verify that the content type of your tsconifig.json is "Content", and can you share a sample project?

**Comment by mhegazy** [comment]
also can you file a different issue.

**Comment by MrAndMrsK** [comment]
Ok, they weren't "Content", so I corrected that.

After that it seems like `outFile` does not get combined with `outDir` - the files were being generated correctly, but not in the out folder.  So I combined them myself into `outFile` and dropped `outDir`.  Not sure if that represents a bug or not.

If you think there's a bug here, please let me know what it is and I'll be happy to file it.  The situation was confusing to me, but I'm not sure how to describe that as a bug.

**Comment by mhegazy** [comment]
@MrAndMrsK this is actually a new feature. module outputs are concatenated using --outFile. i am assuming you are using module.. is that correct?

For more details please see: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#concatenate-amd-and-system-modules-with---outfile

**Comment by MrAndMrsK** [comment]
Yes, but the outDir is not being honored.  I had:

```
    "outFile": "combinedOut.js",
    "outDir": "../built",
```

"combinedOut.js" was being generated, but it wasn't being put in ../built.

**Comment by mhegazy** [comment]
aah.. they do not combine. actually it should be an error to specify outFile and outDir in conjunction. this is tracked bu https://github.com/Microsoft/TypeScript/issues/3305

**Comment by deni35** [comment]
As I understand this feature is named Virtual Project ?
Can I use Virtual Project in HTML with TypeScript project type?

**Comment by mhegazy** [comment]
For the OP. multiple tsconfig.json support is not related to Virtual Projects, multiple tsconfig.json support is enabled for all projects.

> As I understand this feature is named Virtual Project ?

this is not true. Virtual Projects are the file tree you get in your solution explorer if you do not have a real project, i.e. if you just open a .ts file in VS without loading a solution or a project file. it looks something like:
![image](https://cloud.githubusercontent.com/assets/8000722/14937723/29cda5e8-0ec5-11e6-9d6e-1c1921e4020f.png)

> Can I use Virtual Project in HTML with TypeScript project type?

The virtaul project view is disabled by default when a solution is loaded, just to limit noise, as all the files in the poject will be listed twice. to enable it go to tools\options\text editor\typescript\project and select "Display Virtual Projects when solution is loaded" :
![image](https://cloud.githubusercontent.com/assets/8000722/14937730/a1022e90-0ec5-11e6-9b6d-eb4dd5051d53.png)
