### ISSUE TITLE
PromiseOrValue<EmptyObject> accepts Promise<null>

### ISSUE THREAD

**Issue by Cellule** [microsoft/TypeScript#47145]
# Bug Report

### 🔎 Search Terms

- promise or value [null] [empty object] [{}]
- empty object matching null

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Empty Classes" 

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.3&ssl=30&ssc=74&pln=1&pc=1#code/C4TwDgpgBAyghgMwgBQE4HsC2BLAzhAeVQDU4AbAVwgB4AVAPigF4oBvAXyggA9gIA7ACa4otKAH4o-CADcIqKAC5RUAD5Q0WPDQYBuAFChIGjDnxFSlHYxZj1ms9YPZ+fVAjgBjaADF06Nn0oYKg4ZX4KTAAjeQN2fRc3D28oACE4BVYgkKjwyJjUOP19AHoSqCNoAFFMMFACKIArCE9gZjYAbQBrCBBlXGBUFwBzAF1w2Xl4yqgAQU9vOohBWnAIERYONSg-dGKyubIyCoALdehcE-QKMkEuVAxUYs90fgGK9eAARmUHbQtyFRqPNFnwVmtcDYpDcyAYXm82nwBgAmX6mf4kQE0EEQJbgyCQ9p-fAAOlQ63QZDkAAoIkcAJS6KAHWgnPBQdnAM5QcnkMggKBgDBRMgQTBwYDYTxQV4QfTw95I4AAZjRWnMmKswIWuLBqwJUNYuSgX04cBE6UK8teis+ABY1Y4AVqcXj9esocSIGSKVSaJb6NSjcpTYzrQiPgMAKyOjGWIGuvUQqEdUahEQRaLyVNwm2Iz4ANljGvj2J1buTRPRpPJuEpcmomYKqcDqbDCvzAwA7MpE8t3RtoUdcxGlQAOXvlpME9rBk1mi0ZEe2gYATknoP7EPaqfT0KzqBz4ZX3wADMWy5v8R6q+rvbX6xBaTD6cfO98fiY79qrwPPdX719BsAyDY1QzfSNvlRL9HB-XUtwNW9HB9Os-UbfJs1GVtRjDfZyhgFwUj7a8RHhYA4BcEQxTqAV0CaFo2kEAJ+HQNo+XQAB3Dk2hcGC4yxCClS+VVYEQFAAOdBMpwQm8WC9FDH2fBkmSAA)

### 💻 Code

```ts
type PromiseOrValue<T> = T | Promise<T>;
interface Foo { a: number; }
type AcceptedTypes = {} | Foo
const test1: PromiseOrValue<AcceptedTypes> = null; // Correctly errors
const test2: PromiseOrValue<AcceptedTypes> = Promise.resolve(null); // No error
const test3: Promise<AcceptedTypes> = Promise.resolve(null); // Correctly errors
const test4: AcceptedTypes = null; // Correctly errors
```

### 🙁 Actual behavior

Using `PromiseOrValue` with "Empty Object" `{}` caused a `null` value to sneak past the typings.
In my real-world scenario, the type was protecting a non-nullable MySQL field and it failed to detect a function could potentially return null

As shown in the playground link, there are numerous other types that I would have liked to block (Bar, Array) but I understand that empty object is a special cookie that let those pass
But letting `null` pass was really unexpected.

### 🙂 Expected behavior

I expected to have a compiler error that `Promise<null>` was not compatible with the type `PromiseOrValue<AcceptedTypes>`

Looking more into it, I understand now that `{}` is the reason `Promise<any>` is accepted in the type
```ts
const test: {} = Promise.resolve() // no error
```
Any way to make empty object checks more strict ? Ideally I really don't want `Promise` to be a valid `{}`

**Comment by fatcerberus** [comment]
Anything that isn’t `null` or `undefined` is assignable to `{}`; without negated types, there’s nothing you can do about that other that to use a more specific type.  It’s tempting to blame the over-permissiveness of `{}` here, but in this case even `object` doesn’t help you because “promise for `null`” is also a legal object.  To express this as-is, you’d need to be able to say “any object, except promises”, which you can’t do today.

**Comment by Cellule** [comment]
I figured that was the case. 
I consider myself a more veteran typescript user and managed to figure it out, but I know a lot of people on my team, even myself, has been and/or would be tripped by such behavior (aka {}/object matching any object-like)
Are there any consideration by the typescript team to treat `{}` as an "Empty object" and not as "object" ?

For now my solution is to instrument PromiseOrValue to not allow `{}` or `object` and I was able to change to use only `Promise` in the problematic case
```ts
type PromiseOrValue<T> = {} extends T ? never : T | Promise<T>;
```

**Comment by fatcerberus** [comment]
> Are there any consideration by the typescript team to treat {} as an "Empty object" and not as "object" ?

That's wading into [Exact Types (#12936)](https://github.com/microsoft/TypeScript/issues/12936) territory.  It's maybe a bit weird that primitive types like `number` and `string` are assignable to `{}`, but even if that weren't the case, under TS's brand of structural typing, `{}` is fundamentally a legal subtype of every single possible object you could imagine, for the same reason that `{ a: string, b: string }` is assignable to `{ a: string }`.

**Comment by Cellule** [comment]
Thanks for the explanation, I'll try to be more careful when writing/reviewing code using `{}` then.

You're right that this seems to feel into Exact Types, I'll look up this issue and close this one.

Thanks again for the quick response!
