### ISSUE TITLE
Intl.DisplayNames.prototype.of should return string | undefined

### ISSUE THREAD

**Issue by tao-cumplido** [microsoft/TypeScript#47143]
# Bug Report

### 🔎 Search Terms
- intl
- displaynames

### 🕗 Version & Regression Information

The type information didn't exist before 4.5
PR by @orta https://github.com/microsoft/TypeScript/pull/45647

### 🙁 Actual behavior
`Intl.DisplayNames.prototype.of` returns `string` in `lib.es2020.intl.d.ts`

### 🙂 Expected behavior
It should return `string | undefined`
See spec https://tc39.es/ecma402/#sec-Intl.DisplayNames.prototype.of

**Comment by orta** [comment]
Yep, agree, open to PRs for this 👍🏻
