### ISSUE TITLE
Type Assertion passes with only partial implementation of an interface

### ISSUE THREAD

**Issue by jmroon** [microsoft/TypeScript#47140]
# Type Assertion passes with only partial implementation of an interface

### 🔎 Search Terms

- type assertion
- casting

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (up to 4.5.4), and I reviewed the FAQ for all entries.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyyARnFAFzIDOYUoA5gNwFGkBelNdITBAvgQIJ0IGsnTEAVhARgAogA9IIACZUMWALzIAFAEpKG5JoB8OFsigQwAVyghzhIiTKUA5ADc4AGxsQ3ADQWrHAcyJ4+foHByHAqKsBgwCI+AApQ6AAO7l6+-kFOfLFUaJiMyAD0FcjCUFay3gCeyJlwVFQQJW3IYAAWKBLSssi93T7elhAAjjbAViotGZnQSZ38zPhCImKDMmCpZEnjjQDyHtDecJnqmMa6BqVaZnhOVrb2js4uFOG5UQVfOIJJIpbzpLI5SL5CxFboacpVGroOp7Jo9XoZADuXQc0AyUGK6IGUj2yGAJQAtuSqAwiZMZnMIAtMksVs03Ow3OtBPhhKIwOISbITiAmgBJCmZbwQCkQcBUA5QI7eIzafSGW6mT6Td4OF5fUg-CJ5aKFQnwyrVUC1epgNGtdqdQl9YlDAXk5BU9q0l302bzRZZNnhTnc-BAA)

### 💻 Code

```ts
interface Foo {
  bar: string;
  baz: string;
}

const objectExtendsFoo = (): Foo => {
  return {
    bar: 'value',
    baz: 'value',
    additionalProp: 'value',
  } as Foo; // correctly passes as the object has all required properties
};

const objectPartiallyOverlapsFoo = (): Foo => {
  return {
    bar: 'value',
    additionalProp: 'value',
  } as Foo; // correctly throws an error as the object is missing the required property 'baz'
};

const objectOnlyImplementsPartialFoo = (): Foo => {
  return {
    bar: 'value',
  } as Foo; // incorrectly passes as the object is missing the required property 'baz'
};
```

### 🙁 Actual behavior

An object missing required parameters can be cast to that interface if the object is a subset of that interface.

### 🙂 Expected behavior

An error should be thrown if the object does not correctly provide all required parameters.

The fact that the error is shown once the object only partially overlaps Foo seems to indicate this is a bug.

**Comment by RyanCavanaugh** [comment]
Type assertions are used to downcast, of which this is one example. See https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions

**Comment by RyanCavanaugh** [comment]
See also #16995

**Comment by jmroon** [comment]
Thanks for the clarification.

**Comment by fatcerberus** [comment]
@jmroon You might be interested in #46827.
