### ISSUE TITLE
Awaited<T> not resolved to T when T is a generic type

### ISSUE THREAD

**Issue by frank-weindel** [microsoft/TypeScript#47144]
# Bug Report

I thought this issue might be related to #46543, but that issue seems to apply to ALL ts versions. This issue is a regression between 4.4.4 and 4.5. In addition to reporting this bug I offer a very simple workaround.

### 🔎 Search Terms

generic, index, indexed record, type resolution, promise, awaited, workaround

### 🕗 Version & Regression Information

- This changed between versions 4.4.4 and 4.5
- **Edit (3/7/22)**: Still an issue in 4.5.5 and 4.6.2

Bug started in 4.5 release.

Not fixed in the nightly version as of December 14th 7am ET.

### ⏯ Playground Link

The example below is purposely contrived in order to express the issue in simple terms.

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.3#code/KYDwDg9gTgLgBDAnmYcDiwB2woEsDGAyjFAK74ylTAA8AsAFBxwCC++wYMAhgEYA2wANLBEAFWSpQMLABMAznHklcmAOZwAvEpXrGAPi1wASsHzRZNNhy59BI8ZIA0cTKQC2vHPoDcjRgD0AFRBjHBBOmQUVMAA2gDWogC6cNzy8rhqmO5Y8ObuYLiCimB40AgQcAAsAHQArC68pPAAZtxFiqrV9TUAzGFBAYxpiJj4cC2kYzC4EJhwvFAQiZgAoiDcBYJW7Jw8AsKiEihw0nKKynjqRpeqavoAFJfklNQACkvuuPLAAFxwHwgXx+NAw2DwRBILxiOxs+3sR0k+n0LkSiH+1j2dkOjhQAEp-oDgbQAG4QXCyQwAbzCcHMmGUkWh1CM3AA7u14M9ou9Pt9gH4mEyeXE0SltABGQUAX38DGCoSYETeEHSuAOcDZ0Hi3CWU1kC0Qp3A-AIuHgSEK1wgLTgAHJua9gHaBkMGCMxhMphRZvMtVB4iw9ZhZOtNmBtpjbAcHMcpCAZCGLroNNpbupHo6YkT+YS+SCwTgCMQok7YViY4iUMjUaIMbtowjccACQD86TyZS4DShfTGVnqP9CxCS8zaFH4Ti44ZtOzOcKnTmfoLmAPRckjFLGLKGHLAm6AgE4OsSGkJuVqC0cFgOPu5QqBnAxAALb7G8OCOlAwrFBbNOCqMowDcAaNrGhGZowPwRqlBAJIUncqRwGoWBFuMlqoC05TDsWUIipqqCkD8AEwIosjAG0pD8PAYEAAbpmotGusM8ijOMkzTL6mrancABCzQAKoZOoOH4HGAAiFHcFRpFhlswBPHhi7tnmQL8qCqEjkpMQonAaL-AxrZLh2FLUrSfZctpLKzhy5oLtm7YrvZ1AJBukoyveISPi+b6gB+qD5D+wCKE08CiaOIoOshmkEHAYC6psAGKKAEH4Oa0FwPRKZMUqboeux3ozHM3EBnxgnCWookSVJMnyHJEbAAATIppYOWpPyqcSGngrhrXUDQDE1npdaRHcRntjQZKmd25lzP2VmoDZ85rsZTlrq5iDinAW4MNKQA)

### 💻 Code

```ts
export type GenericStructure<
  AcceptableKeyType extends string = string
> = Record<AcceptableKeyType, number>;

/**
 * structure[key] assignment compiles prior to 4.5, but fails in 4.5.3
 */
async function brokenExample<AcceptableKeyType extends string = string>(structurePromise: Promise<GenericStructure<AcceptableKeyType>>, key: AcceptableKeyType): Promise<void> {
  const structure = await structurePromise;
  structure[key] = 1;
}

/**
 * Possible workaround by explicit typing of 'structure'
 */
async function workAroundExample<AcceptableKeyType extends string = string>(structurePromise: Promise<GenericStructure<AcceptableKeyType>>, key: AcceptableKeyType): Promise<void> {
  const structure: GenericStructure<AcceptableKeyType> = await structurePromise;
  structure[key] = 1;
}
```

### 🙁 Actual behavior

In `brokenExample()`:

The type of `const structure` is implicitly resolved to `Awaited<GenericStructure<AcceptableKeyType>>`

Assignment of `structure[key] = 1;` results in this error:
```
Type 'number' is not assignable to type 'Awaited<GenericStructure<AcceptableKeyType>>[AcceptableKeyType]'.(2322)
```

### 🙂 Expected behavior

In `brokenExample()`:

The type of `const structure` should be implicitly resolved to `GenericStructure<AcceptableKeyType>`

Assignment of `structure[key] = 1;` should not result in an error.

**Comment by NtsDK** [comment]
Got the same problem. Workaround works, thank you)

**Comment by connor4312** [comment]
I believe I ran into a similar issue in VS Code. On 4.6.0 nightly, this is broken:

```
async function filterDefined<T>(arr: Promise<T | undefined>[]): Promise<T[]> {
    const r = await Promise.all(arr);
    return r.filter((r): r is T => r !== undefined);
}
```

But adding a type annotation makes it work:

```
async function filterDefined<T>(arr: Promise<T | undefined>[]): Promise<T[]> {
    const r: (T | undefined)[] = await Promise.all(arr);
    return r.filter((r): r is T => r !== undefined);
}
```

**Comment by jctaoo** [comment]
I also ran into a similar issue:
```typescript
class Test<Model> {
  constructor(private model: Model) {
  }
  
  async getObj(): Promise<Partial<Model>> { 
    return this.model;
  }
  
  async getKey<Key extends keyof Model>(obj: Model, key: Key): Promise<Model[keyof Model] | undefined> {
    const model = await this.getObj();
    // error: Type 'Awaited<Partial<Model>>[Key]' is not assignable to type 'Model[keyof Model] | undefined'.
    return model[key];
  }
}
```
But when I removed `Partial`, it will works will.

[Typescript Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAuAeAsgewCbxAPmgG8AoaaYDAO2QCcBXYJDGgCgAcaBLANzCXmgBbbLgBc0TDhABKIqWgBfefMgBPSsGgBzeEgDyAIwBWLaeIAKNDIM4R4Kc2BpJOYEOhH4ChaPLI1dOhpKaCQAC1sAOmEpAG55JTIVCHVNHSQAaXhVFCzVaHgAD35KLBgAa2yMADMJTzwWDGNxSVwAGmhK1XE8s2hLa1t7VpAAbS6auqkAXWgAH2g6Uvhqzkp4LG8-cipkIU9oAF5oMAB3ME4kUIiISPTDE2l4sn9A4P2pcezp58ViBSAA)

**Comment by frank-weindel** [comment]
Verified that this is still an issue in 4.6.2.

[Playground](https://www.typescriptlang.org/play?ts=4.6.2#code/KYDwDg9gTgLgBDAnmYcDiwB2woEsDGAyjFAK74ylTAA8AsAFBxwCC++wYMAhgEYA2wANLBEAFWSpQMLABMAznHklcmAOZwAvEpXrGAPi1wASsHzRZNNhy59BI8ZIA0cTKQC2vHPoDcjRgD0AFRBjHBBOmQUVMAA2gDWogC6cNzy8rhqmO5Y8ObuYLiCimB40AgQcAAsAHQArC68pPAAZtxFiqrV9TUAzGFBAYxpiJj4cC2kYzC4EJhwvFAQiZgAoiDcBYJW7Jw8AsKiEihw0nKKynjqRpeqavoAFJfklNQACkvuuPLAAFxwHwgXx+NAw2DwRBILxiOxs+3sR0k+n0LkSiH+1j2dkOjhQAEp-oDgbQAG4QXCyQwAbzCcHMmGUkWh1CM3AA7u14M9ou9Pt9gH4mEyeXE0SltABGQUAX38DGCoSYETeEHSuAOcDZ0Hi3CWU1kC0Qp3A-AIuHgSEK1wgLTgAHJua9gHaBkMGCMxhMphRZvMtVB4iw9ZhZOtNmBtpjbAcHMcpCAZCGLroNNpbupHo6YkT+YS+SCwTgCMQok7YViY4iUMjUaIMbtowjccACQD86TyZS4DShfTGVnqP9CxCS8zaFH4Ti44ZtOzOcKnTmfoLmAPRckjFLGLKGHLAm6AgE4OsSGkJuVqC0cFgOPu5QqBnAxAALb7G8OCOlAwrFBbNOCqMowDcAaNrGhGZowPwRqlBAJIUncqRwGoWBFuMlqoC05TDsWUIipqqCkD8AEwIosjAG0pD8PAYEAAbpmotGusM8ijOMkzTL6mrancABCzQAKoZOoOH4HGAAiFHcFRpFhlswBPHhi7tnmQL8qCqEjkpMQonAaL-AxrZLh2FLUrSfZctpLKzhy5oLtm7YrvZ1AJBukoyveISPi+b6gB+qD5D+wCKE08CiaOIoOshmkEHAYC6psAGKKAEH4Oa0FwPRKZMUqboeux3ozHM3EBnxgnCWookSVJMnyHJEbAAATIppYOWpPyqcSGngrhrXUDQDE1npdaRHcRntjQZKmd25lzP2VmoDZ85rsZTlrq5iDinAW4MNKQA)

**Comment by frank-weindel** [comment]
Verified that this is still an issue in 4.8.0-beta

[Playground](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/KYDwDg9gTgLgBDAnmYcDiwB2woEsDGAyjFAK74ylTAA8AsAFBxwCC++wYMAhgEYA2wANLBEAFWSpQMLABMAznHklcmAOZwAvEpXrGAPi1wASsHzRZNNhy59BI8ZIA0cTKQC2vHPoDcjRgD0AFRBjHBBOmQUVMAA2gDWogC6cNzy8rhqmO5Y8ObuYLiCimB40AgQcAAsAHQArC68pPAAZtxFiqrV9TUAzGFBAYxpiJj4cC2kYzC4EJhwvFAQiZgAoiDcBYJW7Jw8AsKiEihw0nKKynjqRpeqavoAFJfklNQACkvuuPLAAFxwHwgXx+NAw2DwRBILxiOxs+3sR0k+n0LkSiH+1j2dkOjhQAEp-oDgbQAG4QXCyQwAbzCcHMmGUkWh1CM3AA7u14M9ou9Pt9gH4mEyeXE0SltABGQUAX38DGCoSYETeEHSuAOcDZ0Hi3CWU1kC0Qp3A-AIuHgSEK1wgLTgAHJua9gHaBkMGCMxhMphRZvMtVB4iw9ZhZOtNmBtpjbAcHMcpCAZCGLroNNpbupHo6YkT+YS+SCwTgCMQok7YViY4iUMjUaIMbtowjccACQD86TyZS4DShfTGVnqP9CxCS8zaFH4Ti44ZtOzOcKnTmfoLmAPRckjFLGLKGHLAm6AgE4OsSGkJuVqC0cFgOPu5QqBnAxAALb7G8OCOlAwrFBbNOCqMowDcAaNrGhGZowPwRqlBAJIUncqRwGoWBFuMlqoC05TDsWUIipqqCkD8AEwIosjAG0pD8PAYEAAbpmotGusM8ijOMkzTL6mrancABCzQAKoZOoOH4HGAAiFHcFRpFhlswBPHhi7tnmQL8qCqEjkpMQonAaL-AxrZLh2FLUrSfZctpLKzhy5oLtm7YrvZ1AJBukoyveISPi+b6gB+qD5D+wCKE08CiaOIoOshmkEHAYC6psAGKKAEH4Oa0FwPRKZMUqboeux3ozHM3EBnxgnCWookSVJMnyHJEbAAATIppYOWpPyqcSGngrhrXUDQDE1npdaRHcRntjQZKmd25lzP2VmoDZ85rsZTlrq5iDinAW4MNKQA)

**Comment by frank-weindel** [comment]
Thanks @rbuckton!
