### ISSUE TITLE
TypeScript removes comments even when `removeComments: false`

### ISSUE THREAD

**Issue by abelepereira** [microsoft/TypeScript#47158]
# Bug Report

TypeScript removes comments when transpiling even when `removeComments: false`.

### 🔎 Search Terms

removeComments; comments;

### 🕗 Version & Regression Information

Seems to happen on all versions (at least from 3.x to latest).

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.3#code/DYUwLgBAhhC8EHoBUBtFASA3gSwHbbAAUoAnKAWwGcBfAXVqQQk2oG4BYAKFEgCMAuCAHteAKxABjSPGRoseAsTJU6DJiw6cgA)

### 💻 Code

Specifying a type on `b` causes the problem to manifest,

```ts
let a = /*[[${something}]]*/ {};
let b: any = /*[[${something}]]*/ {};
```

### 🙁 Actual behavior

Produces the following output when `removeComments` is set to `false` on tsconfig.json:

```js
"use strict";
let a = /*[[${something}]]*/ {};
let b = {};
```

### 🙂 Expected behavior

Should  keep the comments on both lines:

```js
"use strict";
let a = /*[[${something}]]*/ {};
let b = /*[[${something}]]*/ {};
```

**Comment by RyanCavanaugh** [comment]
Just to set expectations, `removeComments: false` is not a guarantee that 100% of comments will be retained -- those attached to interfaces, for example, will still not be present in the JS.

This case looks like an oversight though

**Comment by a-tarasyuk** [comment]
It looks similar to https://github.com/microsoft/TypeScript/issues/40943

**Comment by abelepereira** [comment]
yup, it's a dup of  #40943.

@RyanCavanaugh for interfaces and other type artifacts that are lost while transpiling, it's fine. And I would say, it's even expected those to be lost.
