### ISSUE TITLE
❄ Holiday Staffing 2021 ❄

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#47154]
An exceptionally high share of the team is taking vacation this year. Please expect delayed responses to incoming issues/PRs/comments. We'll get back to you soon in 2022!

![Happy Holidays from the TypeScript Team](https://user-images.githubusercontent.com/6685088/146080596-4ec56fc4-ab64-4f2e-a8dd-005849697a9b.png)

**Comment by a-tarasyuk** [comment]
Happy Holidays!

**Comment by RyanCavanaugh** [comment]
Also: 🌞 for our friends in the Southern Hemisphere 🌞

**Comment by MartinJohns** [comment]
Merry Christmas!

**Comment by frank-weindel** [comment]
Happy holidays! Thank you all for what you do!

**Comment by hochan222** [comment]
Happy holidays~!  Thank you for always.

**Comment by saschanaz** [comment]
Happy Holidays ☃️

**Comment by RyanCavanaugh** [comment]
Aaand the holiday backlog is cleared

![Frodo: It's Over. It's Done.](https://user-images.githubusercontent.com/6685088/149245163-c68c3213-94fe-45f5-8307-d6370f74a5a6.png)
