### ISSUE TITLE
Get completions in type parameter of type alias cause an error

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#4715]
```typescript
type constructorType<T1,T2> = new <T1/*completion1*/, /*completion2*/
```
At ```completion1``` and ```completion2``` language service fails to get completions and throws below error messages:

![fail_completions_type_alias](https://cloud.githubusercontent.com/assets/489742/9773783/4e7b55fe-56f9-11e5-9a56-1e2126efb11f.PNG)

**Comment by DanielRosenwasser** [comment]
Looks related to #4616.

**Comment by yuit** [comment]
@DanielRosenwasser  very likely
