### ISSUE TITLE
MutationRecord.type incorrectly typed as Node?

### ISSUE THREAD

**Issue by adbutterfield** [microsoft/TypeScript#47155]
# Bug Report

### 🔎 Search Terms

MutationRecord

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about MutationRecord

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/ATDGHsDsGcBdgBYENIBMA2BTAsgV1krAJZTQBcweBxUAwkuugEZKgDWwAvMABQC2+QiRgBKLgD5gAbwCwAKBAgB1YdAB0AM3AAnAKKsEPHlOCwAngAdMAGlNJtAc0zwAvmM6TZCxSCIbe5lZcnNwA5ISw2kRM+JjQoWJePj4QMPARUTGwmLTIkE5cdo7OAPxqTrAAgrCR0bE8oaiESAC0FtrgDtpx8SIA3PLyyYp+vBl12bkoTolDwyP+PATF8ABkq0UVanBmWGLLWztYagDuRKiwCIXjWTl5TgPewy5zPi9PwG6PIC59QA)

### 💻 Code

```ts
  const handleMutations: MutationCallback = (mutations) => {
    mutations.forEach(({ type, target }) => {
      if (type === 'attributes') {
        const attributeChange = target?.getAttribute('data-progress');

        if (attributeChange) {
          if (target && target.style) target.style.width = attributeChange;
        }
      }
    });
  };
```

### 🙁 Actual behavior

Getting errors:
`Property 'getAttribute' does not exist on type 'Node'.`
`Property 'style' does not exist on type 'Node'.`

### 🙂 Expected behavior

Since those properties do in fact exist on `target`, I would expect there to not be any errors.

I noticed a comment in another issue: https://github.com/microsoft/TypeScript/issues/31889#issuecomment-501694111
It says that "All HTMLElements are Nodes". But I guess not all Nodes are HTMLElements?

Link to the type definition: https://github.com/microsoft/TypeScript/blob/3d3825e78350d6dd8807b8455b52ae2df7c87a2e/lib/lib.dom.d.ts#L10313

**Comment by RyanCavanaugh** [comment]
> Since those properties do in fact exist on target,

They are not guaranteed to be present. This is a correct error.
```js
let m = new MutationObserver(function f(t) {
  console.log('getAttribute is ' + t.getAttribute);
});
m.observe(document, { childList: true });
document.removeChild(document.children[0]);
```
prints
```
> getAttribute is undefined
```

**Comment by adbutterfield** [comment]
Type of t in your example is `MutationRecord[]`. So yeah, it would always be undefined...

**Comment by RyanCavanaugh** [comment]
Fixed
```
let m = new MutationObserver(function f(t) {
  console.log('getAttribute is ' + t[0].target.getAttribute);
});
m.observe(document, { childList: true });
document.removeChild(document.children[0]);
```

**Comment by adbutterfield** [comment]
I guess that's the outlier though, if it's a document node. Probably the most common use case is that putting a mutation observer on an element node (which would make target be type HTMLElement I think?). But I guess it's too difficult for TS to distinguish?  Maybe could make MutationObserver generic to accept the type of target, defaulting to `Node`?

**Comment by MartinJohns** [comment]
> Maybe could make MutationObserver generic to accept the type of target, defaulting to `Node`?

That would be bad for the same reason why `JSON.parse()` is not generic. It would make people wrongly believe there's any type-safety present, when it's not.

The solution is easy: Add a type assertion.

**Comment by adbutterfield** [comment]
Indeed what I did in the end.

**Comment by gtbuchanan** [comment]
`type` is already defined on `MutationRecord`, so why not define `MutationRecord` as a discriminated union? For example:

```typescript
interface AttributesMutationRecord {
  type: 'attributes';
  target: Element;
  attributeName: string;
  ...
}

interface ChildListMutationRecord {
  type: 'childList';
  target: Node;
  ...
}

type MutationRecord = AttributesMutationRecord | ChildListMutationRecord | ...;
```

Then we don't have to use guards:

```typescript
const observer = new MutationObserver(mutations => {
  for (const m of mutations) {
    if (m.type !== 'attributes') continue;
    console.log(m.target.getAttribute(m.attributeName)); // No type error
  }
});
```

At least that's accurate according to the [current docs](https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord/target). I may be missing something regarding the history of the API.
