### ISSUE TITLE
Reassigned types ignored after return

### ISSUE THREAD

**Issue by oliver-ni** [microsoft/TypeScript#47153]
# Bug Report

### 🔎 Search Terms

* return
* early return

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `return`

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211214#code/MYewdgzgLgBAhjAvDAFBAXDaAnAlmAcwEokA+GAbwF8AoG0SWAIyVQyyj0JgB8YwArgFsmAU2wlE5CjRhZWAIgUBuWTGyioA7GFVy4aIqtr1w0GMFZpMOfAV79hYiWUpqIilWoMQjNWkA)

### 💻 Code

```ts
const a = (s: string) => {}

const b = (s: string | number) => {
  s = "";
  return;
  a(s);  // <- Error occurs here (type 'number' is not assignable to type 'string')
}

const c = (s: string | number) => {
  s = "";
  a(s);  // <- No error here
}
```

### 🙁 Actual behavior

On the line `a(s);` in the function `b`:

```
Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.
```

Type error is thrown even though `s` is reassigned as a `string` before the call.

### 🙂 Expected behavior

No type error.

Without the `return`, as in the function `c`, everything works as expected.

Not sure whether this is intended or not, but seems like a bug to me. Thanks!

**Comment by RyanCavanaugh** [comment]
See #26914

**Comment by oliver-ni** [comment]
Ahh, thanks. Missed that.
