### ISSUE TITLE
`Intl.Locale.language` should be required / should not include `undefined`?

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#47169]
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Intl.Locale.language`

## Sample Code

```ts
new Intl.Locale('en-GB').language;
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/language

I played around and I couldn't find any scenario where `language` would return `undefined`.

The first thing that came to mind was this:

```ts
new Intl.Locale('').language
```

However, `new Intl.Locale('')` throws with:

```
Uncaught RangeError: First argument to Intl.Locale constructor can't be empty or missing
    at new Locale (<anonymous>)
```

… so it's not even possible to read the `language` property.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/microsoft/TypeScript/pull/47720

**Comment by jakebailey** [comment]
Yep; this is fixed, as noted above.
