### ISSUE TITLE
' Error: Debug Failure' with the @fullcalendar/react plugin

### ISSUE THREAD

**Issue by songzhenze2** [microsoft/TypeScript#47163]
*TS Template added by @mjbvz*

**TypeScript Version**:  4.6.0-dev.20211214

---

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: code_1.63.0-1638855526_amd64.deb
- OS Version: Ubuntu 20.04.3 LTS
![image](https://user-images.githubusercontent.com/83216051/146138715-ce4c0f79-8466-49b2-9807-67d584805d42.png)

Steps to Reproduce:
1. Pull my project 
https://github.com/songzhenze2/vscode-issue
2. npm i
3. reload vscode
4. View BaseCalendar.tsx and App.js files

**Comment by mjbvz** [comment]
Thanks @yume-chan!

**Comment by jakebailey** [comment]
This no longer reproduces on main; I bisected and it looks like I fixed this in #48079.
