### ISSUE TITLE
`from` keyword can get hover definition in `import ... from '';` statement

### ISSUE THREAD

**Issue by hiaux0** [microsoft/TypeScript#47165]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.6.0-dev.20211215

**Search Terms**
- `definitionAndBoundSpan`

---

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0-insider
- OS Version: Kubuntu 21.04

Steps to Reproduce:

1. Have 2 files (2nd file is just to have something to import)
```ts
// index.ts
import { hi } from './other';

// other.ts
export const hi = 'hi'
```

2. Ctrl+hover between `"./other"` and `from` (may have to try multiple times)
```ts
// index.ts
import { hi } from './other';
                     ^^^^^^
              ^^^^

// other.ts
export const hi = 'hi'
```

Expected behavior:
Because the `from` keyword is normally not defintion-clickable, it should not be clickable as describe above as well.

Video:

![image](https://user-images.githubusercontent.com/30693990/145872105-9f1e2628-ce49-40ea-97c4-4c4838035624.png)

https://user-images.githubusercontent.com/30693990/145874967-eaae0e11-e988-457a-82d7-5dbcb3c90bc7.mp4

**Comment by mjbvz** [comment]
Thanks @hiaux0 

It looks like this happens when hovering over the space immediately after `from`. Here's an example request and response:

```
[Trace  - 01:26:30.949] <semantic> Sending request: definitionAndBoundSpan (265). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/x.ts",
    "line": 2,
    "offset": 19
}
[Trace  - 01:26:30.950] <semantic> Response received: definitionAndBoundSpan (265). Request took 1 ms. Success: true 
Result: {
    "definitions": [
        {
            "file": "/Users/matb/projects/san/other.ts",
            "start": {
                "line": 1,
                "offset": 1
            },
            "end": {
                "line": 1,
                "offset": 1
            }
        }
    ],
    "textSpan": {
        "start": {
            "line": 2,
            "offset": 15
        },
        "end": {
            "line": 2,
            "offset": 19
        }
    }
}
```
