### ISSUE TITLE
Support requestPermission in DeviceMotion and DeviceOriention

### ISSUE THREAD

**Issue by evanshortiss** [microsoft/TypeScript#47161]
# lib Update Request

I have made changes in a local fork and they seem to be working, so I'm happy to PR this if it's worth making the addition.

## Configuration Check

My compilation *target* is `es5` and my *lib* is `es2020` and `dom`.

## Missing / Incorrect Definition

`DeviceMotionEvent.requestPermission()` and DeviceOrientationEvent.requestPermission()` functions. These are only implemented in Safari in iOS 13+, but they feature in the [spec for the API](https://www.w3.org/TR/orientation-event/#dom-deviceorientationevent-requestpermission) now too.

## Sample Code

```ts
return DeviceMotionEvent.requestPermission()
      .then((permissionState) => {
        if (permissionState !== 'granted') {
          throw new Error('DeviceMotionEvent permission request failed')
        }
      })
```

## Documentation Link

https://www.w3.org/TR/orientation-event/#dom-deviceorientationevent-requestpermission

Perhaps this falls under experimental or early feature omissions? I didn't find a discussion about it in GitHub Issues though.

**Comment by MartinJohns** [comment]
The repository for DOM related changes is: https://github.com/microsoft/TypeScript-DOM-lib-generator

Here they write:

> It's possible that the automated algorithm decided that it's not well supported by browsers and thus removed it. Say we want to add a new interface named Foo. Check if there is a document about that interface in MDN. If there is, see the browser compatibility section and check whether **it's supported by two or more browser engines**. (Note that Chromium-based browsers use the same browser engine and thus support from them counts as a single support.)

**Comment by evanshortiss** [comment]
Thank you! Sounds like it's a no go for now based on the criteria.
