### ISSUE TITLE
Array: Object is possible 'undefined'.

### ISSUE THREAD

**Issue by infacto** [microsoft/TypeScript#47167]
# Bug Report

### 🔎 Search Terms

array is possible undefined

### 🕗 Version & Regression Information

Tested with `typescript@next` (4.6.0-dev.20211216). I initially came from 4.2.4.

### ⏯ Playground Link

Playground does not work for this.

### 💻 Code

```ts
export const myFunc = (): void => {
  const bytes: number[] = new Array<number>(16).fill(0);
  bytes[0] = bytes[6] & 0xf0;
};
```

### 🙁 Actual behavior

I get an error `Object is possiible 'undefined'.` 

### 🙂 Expected behavior

I know that `new Array(n)` generates an array with length and undefined items. But I also use `fill` and fixed types. I don't know how to avoid this error. Cast to `number[]` does also not work (unsafe cast).

![demo](https://user-images.githubusercontent.com/60390085/146352762-6f35f29b-29d0-4510-b726-75fe535fac4d.gif)

<details>
  <summary><b>tsconfig.json</b> (click to expand)</summary>
  

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedIndexedAccess": true,
    "target": "ES2018",
    "module": "commonjs",
    "moduleResolution": "Node",
    "importHelpers": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "rootDir": "src",
    "incremental": true,
    "tsBuildInfoFile": "node_modules/.cache/.tsbuildinfo",
    "noErrorTruncation": true
  },
  "include": ["src"],
  "exclude": ["./**/*.spec.ts", "tests"]
}
```
</details>

**Comment by MartinJohns** [comment]
> Playground does not work for this.

It does, you just need to enable `noUncheckedIndexAccess`: [Playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noPropertyAccessFromIndexSignature=false#code/KYDwDg9gTgLgBAYwgOwM7wLYE8BiBXZBOAXjgAoBKALjgDcIBLAExID44BvAWACg5EU6OACMsMYKhrI8GYcCgBtALok4yYAHc4AQShQAhlgA802fNZkAjADYKAOgBmDADbOyABgoBuXv1HjUBXcVUn8JBWsVADI4dxAHdx8eAF8koA)

And then it's basically the same as #46922. The type `number[]` has no notion of "index 6 is always defined".

**Comment by infacto** [comment]
Ok thanks. Disabling [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) works.

**Comment by fatcerberus** [comment]
Sure, if you know for sure the value won’t be undefined then just write `bytes[6]!`.
