### ISSUE TITLE
`Exclude<string, SomeType>` not working as expected

### ISSUE THREAD

**Issue by NiloCK** [microsoft/TypeScript#47178]
Possibly this lies between being a Bug and being a blind spot in the documentation (Handbook, in this case), but I can't see any indication in the specification of `Exclude` that it only works to exclude individual types from a union type. I might *guess* that this is the case from the provided examples, but probably that's not the intent of the documentation.

Here is a minimal example of what I'm referring to:

# Bug Report

### 🔎 Search Terms

- exclude utility type
- exclude from string
- exclude from type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____bugs that are not bugs_____
- I was unable to test this on prior versions because __time__

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgDFAvFAogDwMYBsCuATCAHigGdgAnASwDsBzAGigCIBDJgPgG4AoAel6iCoAPQD83UJFgBGJKky4CxVkygAfZgCMmjFV27csEYFBYIAXLATIVUfqQAWAexxY8UTdAgL8EPOKMTFllLGFkbNjsBAHcncgBrEiA)

### 💻 Code

```ts
type T0 = Exclude< string, "a">;
//    ^?  (== string)
type T1 = Exclude< "a" | "b", "a">;
//    ^?

let a0 : T0 = "a" // should be excluded?
let a1 : T1 = "a" // works ( ie, the assignment does not work. The _exclude_ works )
```

### 🙁 Actual behavior

`Exclude` did not exclude the supplied `ExcludedUnion` (`"a"`) from `string`.

### 🙂 Expected behavior

`Exclude` excludes `"a"` from the defined type. From [the handbook](https://www.typescriptlang.org/docs/handbook/utility-types.html#excludetype-excludedunion):

> Exclude<Type, ExcludedUnion> 
> Constructs a type by excluding from Type all union members that are assignable to ExcludedUnion

**Comment by fatcerberus** [comment]
`Exclude` can’t work on `string` because there’s no way to represent `string & ~"foo"` in the type system.  It only works to exclude types from a union type.

**Comment by NiloCK** [comment]
> `Exclude` can’t work on `string` because there’s no way to represent `string & ~"foo"` in the type system. It only works to exclude types from a union type.

Do you think this is implied by the quote from the handbook?

**Comment by NiloCK** [comment]
I am finding this meaning in the wording of the handbook now - it's reference to `union members` refers both to the (implicit) union members of `Type` and the union members `ExcludedUnion` - not just the latter.

> there’s no way to represent string & ~"foo" in the type system

... because I'm here - why not? Type system is OK with unions and intersections. What does `~` break?

**Comment by fatcerberus** [comment]
> ... why not? Type system is OK with unions and intersections. What does `~` break?

Q. Why isn't this feature supported?
A. Because nobody implemented it yet.

It doesn't break anything - it's just not something that's supported right now.  See #29317.

**Comment by JustFly1984** [comment]
I would love to have a type string & not ""
Also number & not 0 would be great

**Comment by RyanCavanaugh** [comment]
`Exclude`, being a conditional type, is distributive over unions, which is why it works, but TS doesn't have any notion of an "infinite union" to represent all `string`s.

**Comment by NiloCK** [comment]
Closing via https://github.com/microsoft/TypeScript-Website/pull/2192
