### ISSUE TITLE
Allows to pass generic of different type, than expected

### ISSUE THREAD

**Issue by CrazyFlasher** [microsoft/TypeScript#47175]
# Bug Report

Found use case, where TS transpiler allows to pass variable of type, that differs from expected.
I've tested case with **Haxe**, and if works as expected (added link to Haxe playground also below)

### 🔎 Search Terms

No error, when passing variable of wrong generic type

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=8#code/C4TwDgpgBAyg9gWwgFXNAvFA3gWAFBRQBOEAhgCZwB2ANiFAM4BcjwRAllQOYDc+Avnzz5SAIwZtSAY2BQpNUgwZQAguMkyA8qIBWAHmQA+fLgJQwHAG6lg0APpVSSFhI7ch+QmACuomuyk5aldvGTgiAApHZ1Y3LihMACJEgEpPbHTCYAALdgYAOgcnDChoiCFCfnx0nz8AqC4IWTKIlJc2Ti5000JCEmBvIiooHLzCsoqoKrxp-HlFZQBZEG19IygIAA9bKnJlNVdpYFWDYzwe819-QIkbepIKajooAAUAJU0XpmWT+CRUSCGBKlCAAdygP10ej+KDQhlaQlmeHmSghK10ACZThtthBdvt1EQjicjCYald6rdgPcyJRaPR3p8mAcNMcoTCARAgZgqGC0assRy4QiBNU8AAzbxUGTsahQSgw0bcU4ROC6ZmE4lQowAGnlNlILGQbSgyDJZikwTgNAg+RocC4EXIBrSwjM-UGw2dwFIiLFCsQTVy3AikJ0+UZLz1AEYMQBmFI8KAAemTpTgGyIRHCetE3lkDGycG8NHIUFE0AAtFAAHKaZBQTQAaXwAaQSsdYYxEY+UagsYTSdTQQQYH80AgWfCUGrzb1oEgjCLJbLFagiSFkESYvwQA)
[Haxe playground link, where works as expected](https://try.haxe.org/#eb241799)

### 💻 Code

```ts
type SomeType = {
  readonly s: string;
};

abstract class AbstractObj<T>
{
  private _name: string;

  public constructor(name: string = "")
  {
    this._name = name;
  }

  public get name(): string
  {
    return this._name;
  }
}

class MyObj<T> extends AbstractObj<T>
{
  public static readonly PROP:MyObj<SomeType> = new MyObj<SomeType>();
}

class MyObj2<T> extends AbstractObj<T>
{
  public static readonly PROP:AbstractObj<SomeType> = new MyObj2<SomeType>();
}

function doSomething<T>(obj:AbstractObj<T>, data: T): T
{
  console.log(data)

  return data;
}

doSomething(MyObj.PROP, 123); // no error, but should be - NOT OK
doSomething(MyObj2.PROP, 123); // complie error - OK, type should be "SomeType"
```

### 🙁 Actual behavior
Doesn't throw compile error on line
```ts
doSomething(MyObj.PROP, 123);
```

### 🙂 Expected behavior

Should throw compile error on line 
```ts
doSomething(MyObj.PROP, 123);
```

**Comment by MartinJohns** [comment]
Not a bug, and is mentioned in the FAQ.

https://github.com/microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--

**Comment by CrazyFlasher** [comment]
Thanks for your answers...it works as expected if I define some class member in `AbstractObj<T>` with generic type.
```ts
type SomeType = {
  readonly s: string;
};

abstract class AbstractObj<T>
{
 private a: T;
}

class MyObj<T> extends AbstractObj<T>
{
  public static readonly PROP:MyObj<SomeType> = new MyObj<SomeType>();
}

class MyObj2<T> extends AbstractObj<T>
{
  public static readonly PROP:AbstractObj<SomeType> = new MyObj2<SomeType>();
}

function doSomething<T>(obj:AbstractObj<T>, data: T): T
{
  console.log(data)

  return data;
}

doSomething(MyObj.PROP, 123); // complie error - OK, type should be "SomeType"
doSomething(MyObj2.PROP, 123); // complie error - OK, type should be "SomeType"

```
