### ISSUE TITLE
Inline condition type narrow

### ISSUE THREAD

**Issue by behnammodi** [microsoft/TypeScript#47174]
# Suggestion

## 🔍 Search Terms

Inline condition type narrow

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Well, if we have type narrow front of condition this would be very helpful
```ts
if (typeof thing.x === 'number'): thing is A {
  ...
```

## 📃 Motivating Example

This is very helpful to reduce redundant code for type narrow, without that we have to write a function to check type:
```ts
...
const isA = (thing: A | b): thing is A => typeof thing.x === 'number';

if (isA(thing)) {
    console.log(thing.x + 1);
}
...
```

## 💻 Use Cases

```ts
class A {
    x: number = 0;
}

class B {
    x: string = ""; 
}

const thing: A | B = {} as any;

if (typeof thing.x === 'number'): thing is A {
    console.log(thing.x + 1);
}
```

**Comment by fatcerberus** [comment]
For the record, this is no safer than just using a type assertion, since the type predicate isn’t checked (if it could be checked, you wouldn’t need it).  The same goes for type guard functions, but those at least are reusable.
