### ISSUE TITLE
Loss of function parameter typing when inferring props of React component

### ISSUE THREAD

**Issue by probablyup** [microsoft/TypeScript#47185]
# Bug Report

### 🔎 Search Terms

polymorphic component, react component prop inference

### 🕗 Version & Regression Information

I noticed this 4.5.2, not sure how far the issue goes back or if it ever worked.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOAYV0gDskmYB5KACQBUBZADI8UAczgBeOAGsklCJjgApAMoANAHQBJNlGBMAzsDQBRADZIQrGPrgAfRMRjqG4CCzY9qSADwomlAD4AbnIqGnoAV30YXBdmKwAFHDB9b1I4OABBDAiUUzi3KzgkAA8YVgATGwL3Dm5+IVEAGnSsnLyaxOSbSWR0J062JIgU72yYXPzGQrYA0gCJNomO6drhlLgAMjgAb1aMtFWrAH4ALiXJwZgQjIBfENI9cqhMdFo6KJiQK7SMgDE8qYAEboKRXYplSrVI5sTi8QTCEQtBZ7DJjdpTVy1CHlJhVegwurwxpiSQA0zA0FXAIACn2cDA3XOH2isUJ61S40uhLmGQAlOc+hh1EKYGYLFZvCyvlcOejlpj4rNgqRbuRDgZ4H9gEhTBVFjSdocsVZmYTFvg9GAIjB8E04OpHYyRvpbucjYSzSbYfUEaJbnyJAspeado71M6Urc4AB6OakUqQWBwDXROAAEWU2t1FWZnzZ3pg3ktTGttoWZJ1eoeYVomnKeEkqLgTBQlnO0V0TBEqvVbjTPAglG0ZYA6sAYAALP4RJgYYBudYGnYQttgcwzucwBdMe0Tiz28ORmxu3ar8Ab2fztznGn7kDnesWQPiBadvRIjL3x8NgNBuDeFaNpwBUKAwCgAC0U4fuIOylGul5bjud4Nny0Zhk63TRnG5CYFe25uHAIAoHoNKBs2RATFATBwHSGRopm2Z6imhKwYOw6lja45Tpu15MOs0bwReSC8QRTCwfe-73uoraWNG96wSuslIOc+CYBAED4Lc2G8nAfK9kAA)

### 💻 Code

```tsx
import React from 'react'

type ComponentOrHTMLTag = keyof JSX.IntrinsicElements | React.ComponentType<any>;

type CustomComponentProps<
  ActualComponent extends ComponentOrHTMLTag,
  ActualComponentProps = React.ComponentProps<ActualComponent>
> = ActualComponentProps & {
    component?: ActualComponent;
  };

interface CustomComponent<
  FallbackComponent extends ComponentOrHTMLTag,
> {
  <ActualComponent extends ComponentOrHTMLTag = FallbackComponent>(
    props: CustomComponentProps<ActualComponent>
  ): React.ReactElement<CustomComponentProps<ActualComponent>>;
}

const Field = ({component: Component = 'input', ...props}: {component: ComponentOrHTMLTag}) => <Component {...props} />

export const DSField: CustomComponent<'input'> = Field;

type Item = {
  name: string
}

const ToyInputWithFunctionProp = ({ exampleFunction, item, ...props }: { exampleFunction: (item: Item) => string,  item: Item}) => <input data-thing={exampleFunction(item)} {...props} />

function main() {
  return (
    <DSField component={ToyInputWithFunctionProp} exampleFunction={item => item.name} item={{ name: 'foo'}} />
  )
}

```

### 🙁 Actual behavior

Error: `Parameter 'item' implicitly has an 'any' type.`

### 🙂 Expected behavior

`item` should retain its type `Item`

Tf you hover on `exampleFunction` to get the intellisense for it, the correct type is observed. It seems to be lost on the interpolated JSX value.

<img width="599" alt="Screen Shot 2021-12-17 at 10 21 20 PM" src="https://user-images.githubusercontent.com/570070/146627281-862fcb78-06ad-4540-b3bb-3f57780c6bf4.png">
<img width="436" alt="Screen Shot 2021-12-17 at 10 21 31 PM" src="https://user-images.githubusercontent.com/570070/146627282-6962f254-6501-4902-b012-3280afd7d40f.png">

**Comment by devanshj** [comment]
Here's a more minimal repro. [Playground](https://tsplay.dev/mqQBdm).

```tsx
import React from 'react'

declare const Identity:
  <C extends UnknownComponent>
    ( props: { component?: C } & Props<C>
    ) => 
      React.ReactElement

type UnknownComponent =
  | keyof JSX.IntrinsicElements
  | ((props: never) => React.ReactElement)

type Props<C extends UnknownComponent> =
  C extends keyof JSX.IntrinsicElements ? JSX.IntrinsicElements[C] :
  C extends ((props: infer P) => unknown) ? P : 
  never

declare const Input:
  (props: { value: string, onChange: (v: string) => void }) => React.ReactElement;

<Identity
  component={Input}
  onChange={value => {
    // value is any, expected string
  }}
  value="foo" />

Identity({
  component: Input,
  onChange: value => {
    // value is string, expected string
  },
  value: "foo"
})
```

It works for the function version (`Identity(...)`) but not for the jsx version (`<Identity {...} />`).

Also is it just me or the playground is actually very slow for this snippet?

**Comment by MartinJohns** [comment]
This sounds like #44596.

**Comment by probablyup** [comment]
> This sounds like #44596.

Yes I can confirm it's the same issue. You can mark this as duplicate.

**Comment by MartinJohns** [comment]
I'm no member of the TypeScript team, I can't do shit but talk. :-D

**Comment by RyanCavanaugh** [comment]
Appreciated as usual @MartinJohns 😅
