### ISSUE TITLE
sys.readFile for Node.js: the encoding parameter is ignored, so charset compiler option is ignored on Node.js

### ISSUE THREAD

**Issue by denvned** [microsoft/TypeScript#4718]
[Current implementation](https://github.com/Microsoft/TypeScript/blob/a5c72014b0c345f6978bfe2fa38e5711c256e5af/src/compiler/sys.ts#L199-L226) of `sys.readFile` for Node.js ignore the `encoding` parameter. This effectively makes the _charset_ compiler option ignored on Node.js. If it is "by desing", then it probably should be documented.

**Comment by mhegazy** [comment]
it is by design. the encoding is an option for engines that support it. node's read file does not support the whole encoding ranges. What sort of documentation you want? just a comment in the code, or an error message that this compiler option is not supported on this engine?

**Comment by denvned** [comment]
At least [here](https://github.com/Microsoft/TypeScript/wiki/Compiler%20Options) I think. An error message and a description in the help output would be nice also. But this all is not so critical for me. Probably I will send a PR later.

**Comment by mhegazy** [comment]
A PR would definitely be appreciated!
