### ISSUE TITLE
Error is thrown, when is "as const" is used

### ISSUE THREAD

**Issue by davoam** [microsoft/TypeScript#47187]
# Bug Report

Although all objects in the array has the same type, and it works without error without `as const`, adding `as const` breaks the code. 

### 🔎 Search Terms

`as const`, `array`, `union`

### 🕗 Version & Regression Information

Typescript version `4.4.3` throws the following error 

```
This expression is not callable.
  Each member of the union type '{ <S extends 1 | 2 | 3>(predicate: (this: void, value: 1 | 2 | 3, index: number, obj: readonly (1 | 2 | 3)[]) => value is S, thisArg?: any): S | undefined; (predicate: (value: 1 | 2 | 3, index: number, obj: readonly (1 | 2 | 3)[]) => unknown, thisArg?: any): 1 | ... 2 more ... | undefined; } | { ...; }' has signatures, but none of those signatures are compatible with each other.(2349)
```

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.4#code/MYewdgzgLgBBCWATApgWWWArjAvDA2gFAwwDexJMGUATvMhAFwEWUwCMANK5QEzdsSAZh4BdATAC+E8m2p0GzIoJgAWCWwCsGygDYxE6YVEwAhhBihIUANyFiCFOiwA6AGbwwiABTf5ATwBxGhBMAAcASlwAPjIeEhpkKEwaMCowWiCQ8Jd5egh3Tx8-DJp-KJxY2RVLcAgQABtkFwaQAHMSzIi7FUlunj6bIA

### 💻 Code

```ts
const sideMenu = [
  {
    entries: [
      1,
      2,
      3
    ],
  },
  {
    entries: [
      4,
      5,
      6
    ],
  },
] as const;

 sideMenu.find((entryGroup) => {
      return entryGroup.entries.find((entry) => { // <--- error is thrown here 🤷🏻
        console.log(entry);
      });
    });
```

### 🙁 Actual behavior

It throws error. If `as const` is removed, it works without an error
 
### 🙂 Expected behavior

I expected it to work because each member of the array has property `entries` which is equal to an array. I could understand the  error, if some of them has `entries` array and some not.

**Comment by MartinJohns** [comment]
> I expected it to work because each member of the array has property `entries` which is equal to an array.

But they're not. The first is a tuple only containing the literals `1`, `2` and `3`. The latter is a tuple only containing the literals `4`, 5`, `6`. That means these two tuple have different signatures for `find()`.

You can also solve this by explicitly making these tuple number arrays by adding ` as number[]` to each.

**Comment by PythonCoderAS** [comment]
> > I expected it to work because each member of the array has property `entries` which is equal to an array.
> 
> But they're not. The first is a tuple only containing the literals `1`, `2` and `3`. The latter is a tuple only containing the literals `4`, `5`, `6`. That means these two tuple have different signatures for `find()`.
> 
> You can also solve this by explicitly making these tuple number arrays by adding ` as number[]` to each.

I agree, by replacing the `4`, `5` and `6` with `1`, `2`, and `3`, it works again. Therefore, `as const` makes it check for exact values. My theory was that he was expecting the types to be a 3-item `number` tuple, but not care about the values.

**Comment by davoam** [comment]
@MartinJohns  @PythonCoderAS  thanks for the quick responses! 

@PythonCoderAS yeah, I was expecting that TypeScript will narrow down types automatically, I mean that it will "understand" that `sideMenu[0].entries[0] = 1` and `sideMenu[0].entries[1] = 2` etc.

It is surprising that `entries` is an `array` in both elements, but I cannot use `find` method. Moreover, `sideMenu` elements also has different signatures (I removed some properties from for the sake of simplicity), but `find` method works there without an error. 

![image](https://user-images.githubusercontent.com/9194866/146733433-09978d0d-8c1c-42e6-bec8-2762f04ecd60.png)

**Comment by MartinJohns** [comment]
> It is surprising that `entries` is an `array` in both elements, but I cannot use `find` method. 

It can find the `find` method, it actually can find **two** `find` methods with different incompatible signatures.

**Comment by davoam** [comment]
@MartinJohns thanks! I am closing the issue. 

P.S. I solved the problem by using `as MyType` in this example `as number` as @MartinJohns proposed
