### ISSUE TITLE
Type 'Awaited<Pick<RecordT, T>>[T]' is not assignable to type 'RecordT[T]'

### ISSUE THREAD

**Issue by MarcCelani-at** [microsoft/TypeScript#47182]
# Bug Report

After awaiting a Promise<Pick<RecordT, T>>, applying operator [](T) on it does not resolve to RecordT[T] as expected. When not awaited, it does.

### 🕗 Version & Regression Information

4.5

- This changed between versions 4.4 and 4.5.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.3#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcswBrEYAfURxwqgGcBPdAHgCVwcZgAVAGng94IAB4YQqYPXhlGORPA5guvAHwAKAFDwdMkI3o8cABWIkAXIpBRgeCIwCCMGFEYseqvpoCUl4zBwAWyx6EBZTUnZObn5BVVUAbk1NBmYwJDRMXHxlVAA3EBh6bLomViUVWKFRcUlpWXkrZRiNWSMIi0FfeH8gkLCKmIBtHgBdVXgAb21dXPoMQjNyeABeeCgAdygsBaJScioaUrSo5t4BD3UhtpMzUe8k3Xg4DGQYfD2yYGv9drukgC+yVAkFgCBQ6GweEW+0o1Bwp0qF2EYgkUj0cgUgzUWieskMt1Ilg4Njsjmcrncnh8fjMiJiF0SyQhWWhuQKRWy9POghRtXRDSx0RxNw6lh43WxPBGoymMx0c12S2AqxhX0OCKljKuoruD3lzxAr3eavIP0Yf1Io0BQA)

### 💻 Code

```
declare function picked_foo_async<RecordT, T extends keyof RecordT>(
    keysToPick: ReadonlyArray<T>,
): Promise<Pick<RecordT, T>>;

async function conversion_async<RecordT, T extends keyof RecordT>(keyToPick: T): Promise<RecordT[T]> {
    const picked = await picked_foo_async<RecordT, T>([keyToPick]);
    /* @ts-expect-error https://github.com/microsoft/TypeScript/issues/47182 */
    return picked[keyToPick];
}

declare function picked_foo<RecordT, T extends keyof RecordT>(
    keysToPick: ReadonlyArray<T>,
): Pick<RecordT, T>;

function conversion<RecordT, T extends keyof RecordT>(keyToPick: T): RecordT[T] {
    const picked = picked_foo<RecordT, T>([keyToPick]);
    return picked[keyToPick];
}
```

### 🙁 Actual behavior

Typescript error in conversion_async in example

### 🙂 Expected behavior

No typescript errors

**Comment by RyanCavanaugh** [comment]
This is a correct error.
```ts
type M = {
    x: Promise<string>
}
const f = conversion_async<M, "x">("x");
```
Here, `f` has type `Promise<Promise<string>>`, but it's actually a `Promise<string>`
