### ISSUE TITLE
Extract<string, 'a'> != 'a'

### ISSUE THREAD

**Issue by javier-cornejo** [microsoft/TypeScript#47201]
# Bug Report
`Extract<string, 'a'>` is `never`, while it should be `'a'`. A type like `string` could be seen as a virtual union of all literal string types. Therefore when extracting a literal from a more general type it is assignable to, the literal type should be returned.
In other words, Extract should be implemented as:
```ts
type Extract<A,B> = A extends B ? A : B extends A ? B : never
```

### 🔎 Search Terms
Extract utility type
Extract literal from type

### 🕗 Version & Regression Information
This is present in v3.3.3 (oldest available in playground)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about distributive conditionals, negated types
- I was unable to test this on prior versions because they're not available in playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3#code/PTAEGEEMDtoewC6gKYA8ECdIGMmVNJBhnAO6gA2AlgslhaAGYkC2oNAzqAObLR2QGCAJ4AHZACgR40ABUADAEZQAXlABRdFlwAeDpirRuAGlABySGYB8oEAWQA3OhOxxo+0JEUAuOUtXmlhISdgCCFLQYhAhUTuwsohTILHwIkDFuUmLIoOEImpg4CDqhxgBCNmqhKOh8ACZcZaAA-Lmgvk1otNANba1NvvxOGFkyCgBMAXkF2sX6GIYmgda2YJAubh6Q474TARZmwXYAyjEUDCzp2AAWyFxwFHWgdciMhjRUm6M5CgDMUxEZkUdAAiSAg0AAH1AIIARhDoSDsCDTGCETDGCCrN8-AAWAH5LTA+aLKEEACuLFhdDJAApaQBKVQ2BxwKh1BmmABi5OguE+0CsAG4gA)

### 💻 Code

```ts
// Cannot extract a narrow literal from its general type
type T01 = Extract<string, 'a'> // never
const a1: T01 = 'a'

// Alternative implementation
type AltExtract<A,B> = A extends B ? A : B extends A ? B : never
type T02 = AltExtract<string, 'a'> // a
const a2: T02 = 'a'

// Still matches old definitions
type T03 = AltExtract<"a" | "b" | "c", "a" | "f">
type T04 = AltExtract<string | number | (() => void), Function>;
```

### 🙁 Actual behavior
`Extract<string, 'a'>` is `never`

### 🙂 Expected behavior
`Extract<string, 'a'>` is `'a'`

**Comment by MartinJohns** [comment]
`Exclude<>` operates on union types. `string` is not a union type, so there's nothing to exclude from. TypeScript does not have the ability to represent the a type "string, except this specific string". This would require #29317.

This is a duplicate from the 2 days old #47178, and many more.

**Comment by javier-cornejo** [comment]
@MartinJohns I think it's analogous to the issue you mention it duplicates, but it does not require negated types. I've suggested an alternative implementation of Extract that works without changes to the language.

**Comment by MartinJohns** [comment]
I completely misread `Extract` as `Exclude`. However, the comment about union remains true.

This is not a bug, but working as intended. You might want to rephrase it as a feature request.

**Comment by VanCoding** [comment]
I think what you describe is not a bug, but the intended way that Extract works.
What you want could be done with custom types like this, though:

```ts
type Narrow<Base,Target> = Target extends Base?Target:never

type A = Narrow<string,"a">
```
