### ISSUE TITLE
keyof { [ x: string ]: any } returns `string | number` type

### ISSUE THREAD

**Issue by Dan503** [microsoft/TypeScript#47200]
# Bug Report

### 🔎 Search Terms

keyof returns string or number

### 🕗 Version & Regression Information

Still exists in TypeScript v4.5.4

Was discovered in TypeScript v4.1.2

- This is a case of an incorrect type being returned
- This changed between versions 2.1.0 and 4.1.2
- This is the behavior in every version I tried
- I was unable to test this on prior versions because I don't have time to test every possible version of TS

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211219#code/PTAEFEA8EMFsAcA2BTUBGAUBgLgT3qgBqgC8oA1srgPYBmoA3qANq4BcoAztgE4CWAOwDmAXQ7QBuUAF9QILgAtqAV0QATUl16ChWPAVABNTVDhJkaADyEAfHLAAxaH0SdQAI2QBjaMs5FNbn5hUAAfUAFlWE8eLEFsZB5aaC9UUwQUKwAVUGRIBIE1NyCdOyYAN2hEZWQOHOkseXTzUCyAd2o9fFQAQU1KGnomVg5I6MSxUAkpWXkxmK6DACETGAzkACZLHrt5LIU+N0PQDp5yHSm3PIIvBLU4gQSklLS18y2cvIKiiKiYstAlWqtVaMgwQA)

### 💻 Code

```ts
type X = keyof { [y: string]: any } // should return type `string`
```

Note that the below code DOES work as expected, only string has the issue

```ts
type A = keyof { [b: number]: any } // returns type `number` as expected
```

### 🙁 Actual behavior

The code sample is returning type `string | number`

### 🙂 Expected behavior

The code sample should returning type `string`

The documentation here explains that string should be what is returned:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html

**Comment by IllusionMH** [comment]
It was charged since 2.1. See current Handbook content https://www.typescriptlang.org/docs/handbook/2/keyof-types.html#the-keyof-type-operator

**Comment by Dan503** [comment]
So is it possible to resolve the string type conflict at all?

I can't pass type `string | number` into something expecting only type string :(

**Comment by IllusionMH** [comment]
Depends on the case. Can be `T & string`, `Exclude<T, number>`, condition type etc.

**Comment by Dan503** [comment]
This ended up working for me :)

```ts
Exclude<keyof { [t: string]: any }, number | symbol>
```

I'll close this issue since this was an intentional change by the maintainers of TS.
