### ISSUE TITLE
Static property causes ts2302 on `@typedef` in jsdoc

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#47215]
# Bug Report

### 🔎 Search Terms
ts2302 jsdoc

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `generic`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4&filetype=js#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUowICeqiAJogGaQDeA8gEYBWiAxvAL6QBiA9rwTioATr1LD4RWri6V+BYOHCgI0OEjRYcAVQXhWWAM6HIAIUzDaUSDZXqS5KrT68APNoB8XALJEX0RWtbMHtSWkN4YQBLADsAcy4QRRsbCOwo1khDXmREAGV4dNYABVFxSUgAXkgAIgALRHR0XhqAbiUUyBUgm0JUC0xkWl8XWXlOgJ7s3O9EeDreMlw67G1DREMR-gAKOV4ASisejnATpWVgSABXQ0w4xEhEAA9BjEQlO2IwmnNhVwjovEvJNWLwYhFIE8qpAYogAO5mCzbfbtJ4AOmmiFm80Wy1W602fh2ND2AC5IABmDgoi54OpREyGBZXdBkSBxKIANwemBij2EoksDDYmBuDwABntxZAGY8nqR2ORIPBeJBhZBMFlIrE4mjaQAlFC8Tk6yDitLwDLSsGQdCxB4ARgALJBKFEnhsZfA0UA)

### 💻 Code

```js
/**
 * @template T
 * @typedef {Object} Foo
 * @property {T} foo
 */

/**
 * @template U
 */
class Bar {
    /** @typedef {Foo<U>} MyFoo */
    //               ^^^--------------- Static members cannot reference class type parameters

    /** @type {string} */
    static someStaticProperty = "hello";

    /**
     * @param {MyFoo} foo
     */
    someMethodThatUsesMyFoo(foo) {

    }
}
```

### 🙁 Actual behavior
It gives an error: `Static members cannot reference class type parameters`.

### 🙂 Expected behavior

This shouldn't happen because `static` properties should have no effect on `@typedef`s.

**Comment by RyanCavanaugh** [comment]
This is a correct error since `static` members can use typedefs. If this were allowed, you could leak an uninstantiated type parameter, which is a huge no-no:
```ts
/**
 * @template U
 */
class Bar {
    /** @typedef {U} A */
    //               ^^^--------------- Static members cannot reference class type parameters

    /** @type {A} */
    static someStaticProperty = { foo: null };
}
// p: U (type parameter)!
const p = Bar.someStaticProperty;
```

**Comment by jespertheend** [comment]
Ah sorry I realise I forgot to add some crucial information.
The error disappears when you move the `@typedef` below the static property:
```js
class Bar {
    /** @type {string} */
    static someStaticProperty = "hello";

    /** @typedef {Foo<U>} MyFoo */
    //               ^^^----- No error
}
```
([playground](https://www.typescriptlang.org/play?ts=4.5.4&filetype=js#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUowICeqiAJogGaQDeA8gEYBWiAxvAL6QBiA9rwTioATr1LD4RWri6V+BYOHCgI0OEjRYcAVQXhWWAM6HIAIUzDaUSDZXqSiWofjCAlgDsA5lxCKbN52xXVkhDXmREAGV4INYABVFxSUgAXkgAIgALRHR0XnSAbiV-SDtiUgpqGj5eAB5tAD4uAFkiGug-f2BgEt6+gD1BgFoRocgAOV5IRGFRYWKusGt-QlQLTGRaVprZeV7fZdDwxGbEeEzeMlxM7G1DRENt-gAKOV4ASitDjnAfpWUegBXQyYTyORAADw2GEQSjKklItHMwlqzjcXiaHX0vHczkgENSkHciAA7mYLM93kUIQA6MIRU7nS7XW73R5tF40N4ALkgAGYOFSAXhMq4TIYLoD0GRIJ5XAA3RyYdzTWa8SwMNiYYGOAAGb11kDF0whpHY5Eg8CmmsgmFCLg8nhpwoASihePLHZBdYF4MFDTjIOgPI4AIwAFkglFcEIeRvgNKAA))

Or if you place any non static property below the typedef:
```js
class Bar {
    /** @typedef {Foo<U>} MyFoo */
    //               ^^^---- No error
    
    nonStaticProperty = "hi";

    /** @type {string} */
    static someStaticProperty = "hello";
}
```
([playground](https://www.typescriptlang.org/play?ts=4.5.4&ssl=25&ssc=2&pln=10&pc=1&filetype=js#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUowICeqiAJogGaQDeA8gEYBWiAxvAL6QBiA9rwTioATr1LD4RWri6V+BYOHCgI0OEjRYcAVQXhWWAM6HIAIUzDaUSDZXqS5KrT68APNoB8XALJEX0RRtbYCDQsKCAPSiAWljoyAA5XkhEYVFhaxtMyAA7XhyAZXhsAEtWAAVRcUlIAF5IACIACxKGgG4lULtiUlpDeGESnIBzLhBAoP7S1khDXmREIunKsVSa+ubEdHReds6glWy1WFQLTGRaXxdZeTDx7LmF70R4Jt4yXCbsbUNEQyv+AAKOS8ACUVmyHHAUKUyhCAFdDJhhogUgAPc4YRBKbqSXo0czCVz9QYjLwBfT5fqQNF1XKIADuZgsgNBHTRADpHohnq93p9vr9-n4gTQQQAuSAAZg4bLheBaJkMb3h6DIkGGJQAbqjMDkUmleJYGGxMIjUQADEEWyAlEyINGkdjkSDwZImyCYWYDIbDDnygBKKF4Wt9kAtU3gZRt+Ug6CGqIAjAAWSCUEpov62+AcoA))

The issue you described is a real issue, but this is already taken care of when creating the static property with a TS(2322), rather than TS(2302).
This is your example but with a non static property placed in between the `@typedef` and the `@type`:
```js
class Bar {
    /** @typedef {U} A */
    //           ^^^--------------- No error

    nonStaticProperty = "ok";

    /** @type {A} */
    static someStaticProperty = { foo: null };
    //     ^^^^^^^^^^^^^^^^^^--- TS(2322)
}
```
([playground](https://www.typescriptlang.org/play?ts=4.5.4&ssl=19&ssc=2&pln=10&pc=1&filetype=js#code/PQKhCgAIUgBAXApgWwA4BsCGTIBUowICeqiAJogGaQDeA8gEYBWiAxvAL6QBiA9rwTioATr1LD4RWri6V+BYOHCgI0OEjRYcAVQXhWWAM6HIAIUzDaUSDZXqS5KrW1cAgtEU3bwL798A9QIBaENCw8MgAOV5IRGFRYSVfADteZIBleGwAS1YABVFxSUgAXkgAIl4Aa3KAbiSvO2JSWlcuEE8vQyz4XMhDXmRETJz8wrjisppIOV4ALkhkgFd0dEgOet9gHwDAvf2DvdC8dIAKACYAZnPzgEpwDmUfVAXtSFPJFtQLTCGkYVuAEJ9GlupBUKUzBYAHQDIYjXpjMQTIj1cBAA))

The reason why I think this is not intended is that `@typedef`s and `@type`s should have no effect on each other in a way where the order matters.

**Comment by jespertheend** [comment]
Can this be reopened? I am fairly confident this is not working as intended.
