### ISSUE TITLE
Object is "not comparable" when using JSX attributes on array entry

### ISSUE THREAD

**Issue by TrevorBurnham** [microsoft/TypeScript#47211]
# Bug Report

When I define a type or interface that extends `React.HTMLAttributes<HTMLElement>`, attempting to cast an array of objects to an array of that type fails if any of those objects has a `data-` attribute.

### 🔎 Search Terms

React, JSX, data attributes

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about array type assertions.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211221#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4Aoc4AOxiSk3STgFkBPABRzAGc4kAHnWoATPsnQwAdAAkAKiwAyAQRgwowAEYBXOjwA88pQFEANkhBJaAPjgBvcnDimUmpKYBccHupoBzCgBfSgB6ELgAdWgAax5yNAhqHzgwbj4AXntHZ1d3L3xXNHwAGmz8ERQYFABaPRhgEXx8zAgIEvJAuBQ+di4IXgpyMLhjKBwoLwAiOTYwZnw7HLdPb19qAIIKqtqkHwam1Y110jhA-DhgPmoIeATwFChXczgYCBfZ+d60-ClJ+MTkql+jxlGMUGw4JkANrZBxOJwuZb5QrteGbSo1Or7ZqtVGnUoAXS6PU4aShBNIQA)

### 💻 Code

```ts
import React from 'react';

interface MyProps extends React.HTMLAttributes<HTMLElement> {
  label: string;
}

// Works
const props = {
  label: 'abc',
  'data-testid': 'foo',
} as MyProps;

// Error: "Type '{ label: string; 'data-testid': string; }' is not comparable to type 'MyProps'."
const propsArray = [
  {
    label: 'abc',
    'data-testid': 'foo',
  },
] as MyProps[];
```

You can also replicate it more simply with this one-liner:

```ts
[{'data-testid': 'foo'}] as React.HTMLAttributes<HTMLElement>[];
```

### 🙁 Actual behavior

The array fails type checking with this error:

```
Conversion of type '{ label: string; 'data-testid': string; }[]' to type 'MyProps[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ label: string; 'data-testid': string; }' is not comparable to type 'MyProps'.
    Object literal may only specify known properties, and ''data-testid'' does not exist in type 'MyProps'.(2352)
```

### 🙂 Expected behavior

No type error should occur here.

**Comment by dragomirtitian** [comment]
As mentions in #28960 you can model this interface in Typescript now (https://github.com/microsoft/TypeScript/issues/28960#issuecomment-903519759). 

You could use 

```ts
interface MyProps extends React.HTMLAttributes<HTMLElement> {
  [n: `data-${string}`]: any
  label: string;
}

```
[Playground Link](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211221#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4Aoc4AOxiSk3STgFkBPABRzAGc4kAHnWoATPsnQwAdAAkAKiwAyAQRgwowAEYBXOjwA88pQFEANkhBJaAPjgBvcnDgBtagC44AAxEoYKALQAJHY86jQA5gC+ngC6HijUbI5wpiiaSKYeoRrU4RSR5AD0hXAA6tAA1jzkaBDUoXBg3HwAvPbJqemZBGlo+AA0yfg+fv56MMAi+B74mBAQA+SRcCh87FwQvBRFJcZQOFAeAERybGDM+HYpaRlZYbmkBCMB45PTcNkRj5H4cMB81Ag8Fq4BQUDS5jgMAgULOF3WzXwUiONTqDSamx4yn2KDYcDazmSDicTk6tx6mj6gxJT18LyQoTeMzmC2pJJQKGORzZkUGMRWa04zWcMVIQA)

Any further changes are more likely to be required in the types for react (they could add the index signature to `HTMLAttributes`)
