### ISSUE TITLE
never gets prematurely simplified in conditional types that use inheritance

### ISSUE THREAD

**Issue by stephenh** [microsoft/TypeScript#47213]
# Bug Report

### 🔎 Search Terms

conditional-types, never, inheritance

### 🕗 Version & Regression Information

TS 4.5.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4QDwBUA0yAqshAB6QgAmGyIEAbtMgD7ICu1EMoEVAfMgDeAKGTIARpggAuZLlbEA3CIC+I0JFiIUAYQAWwADZU8hEuUo06jZm05VuvAaQoRqtdFjPFBo8QiGJnIKbEQq6iIA9FHIYIa0AO4A9lAA1hiEcMiBxlTIwLRgUBBwkPmYyNlSWCIIySAYYDlBVHIGedhNUKAA5oT0TFCCALx07EZGAIQq9Y3NNbJo0l3FfQO2w8hjuSYq0bES7M2JwPHIAAagMNAXhBdEFznJALYQtMnHVbQXDk70VAuIjAAE8AA4oACCVCoAAUoMkwXhRvJXFZPCtrswCAUQDcoL5kAB+YRVGF8EKKEiqZByIRkxxtcYvCTMVSzBpNZDJCQAK22whplWhcIRSI6JlWPRA-RsQ34-BUMXkCWQGH0nxMyBS6UIR2aFzg5MBBR+3T6ij+PABT1ATVK+WSMEu5plikGtzqnOacDkrt67s2Ap5vIAdEbGSogA)

### 💻 Code

```
// define parent/child interfaces that both use a "never | undefined" generic
interface Base<T, U extends never | undefined> {
  base: T | U;
}
interface Child<T, U extends never | undefined> extends Base<T, U> {
  child: T | U;
}

// Match against _Base_, and use `infer` to find what `U` is
type AddProp<T> = T extends Base<infer T, infer U> ? { added: T | U } : { added: number };

// Use `AddProp` here U is never
const obj = {} as AddProp<Child<string, never>>;

// This assignment should work, but `added` is `string | undefined` instead of `string | never`
const a: string | never = obj.added;
```

Note that changing `AddProp` to `T extends Child<infer T, infer U>` works.

### 🙁 Actual behavior

`obj.added` is typed as `string | undefined`

### 🙂 Expected behavior

`obj.added` is typed as `string | never`

My guess is that `U extends never | undefined` in `Child` is getting simplified to `U extends undefined` when passed to `Base`, and so `infer U` sees it as "always `undefined`".

However, that only seems to happen in conditional types b/c with just regular variable assignment, TS still knows that `Child<string, never>` is a valid subtype of `Base<string, never>`:

```
// this works, a child is treated as a base
const child: Child<string, never> = null!;
const base: Base<string, never> = child;
```

**Comment by MartinJohns** [comment]
`never` represents an empty union type. When you add another type to the union you don't have an empty union type anymore, so `never` gets removed. This is working as intended.

**Comment by stephenh** [comment]
@MartinJohns yeah, your example makes sense, but I'm using the generic `U` to represent _sometimes_ I want an empty union type (`never`) and sometimes I don't (`undefined`).

This pattern/approach, of `U extends never | undefined` that is later instantiated as either `never` or `undefined`, is working just fine, in many usages across a large codebase, so I get it looks weird, but IMO/AFAICT it's fine/supported.

I.e. in places like:

```typescript
interface Base<T, U extends never | undefined> {
  base: T | U;
}

// `b1.base` is correctly `string`
const b1: Base<string, never> = null!;

// `b2.base` is correctly `undefined`
const b2: Base<string, undefined> = null!;
```

So TS is "late binding" the generic constraint of `never | undefined` (i.e. it does not _immediately_ simplify it to `undefined`), until the generic is later instantiated & used in the rest of type.

The only wrinkle is conditional types, where the `T extends Base<infer A, infer B>` sees a prematurely simplified view of the generic `U` and thinks it must always be `undefined`.

**Comment by fatcerberus** [comment]
*Any* generic can be instantiated with `never`, regardless of its constraint, because `never`, being the bottom type, is a subtype of all other types.  There is thus no fundamental difference between `U extends never | undefined` and `U extends undefined`.

**Comment by stephenh** [comment]
Hm @fatcerberus , true, so let's remove some of the `U extends never | undefined` because that looks weird, and make them just `U extends undefined`:

```typescript
// define parent/child interfaces that both use a "U | undefined" generic
interface Base<T, U extends undefined> {
  base: T | U;
}
interface Child<T, U extends undefined> extends Base<T, U> {
  child: T | U;
}

// Match against _Base_, and use `infer` to find what `U` is
type AddProp<T> = T extends Base<infer T, infer U> ? { added: T | U } : { added: number };

// Use `AddProp` here U is never
const obj = {} as AddProp<Child<string, never>>;

// This assignment should work, but `added` is `string | undefined` instead of `string | never`
const a: string = obj.added;
```

I assert that bug is still there, because I've instantiated `Child<string, never>` in the call to `AddProp`, using the `never` bottom type, but the matching on `T extends Base` the `infer U` is picking up `undefined`.

But `U` should not be `undefined` here. It should be `never`. I'm passing `Child.U` (which is `never`) to `Base.U`, but the conditional type has lost the never-ness.

**Comment by jcalz** [comment]
Nobody asked me but here I am!  `Child<string, never>` is definitely a subtype of `Base<string, undefined>`, so I don't see the bug.  If there's an issue here, I'd say it's about how developers can successfully reason about type inference.  

Trying to infer `T` and `U` from a type like `T | U` seems problematic to me.  My *guess* here (I'd be interested in hearing some official answer) is that when you infer `Child<string, never> extends Child<infer T, infer U>` the compiler takes a shortcut and does not bother with structural comparison.  It just pattern matches on type parameters and you magically get `string` for `T` and `never` for `U`, even if there were no structural dependence of `Child<T, U>` on its type parameters.

But (still guessing here) when you infer `Child<string, never> extends Base<infer T, infer U>`, the compiler does goes ahead and does a structural comparison, and then you get whatever the compiler thinks the best fit will be.  It's looking at `{base: string; child: string}` and has to match that to `{base: T | U}` for some `T` and `U`.  What happens there? Who knows! I guess the compiler says, well `T` is `string`, and then there's nothing obvious from which `U` can be determined here, so it falls back to the constraint, which is `undefined`.  Not awesome, but not a *bug*.

If I were you I'd improve the inference sites to be unambiguous and then see if problems still happen:

```ts
interface Base<T, U extends undefined> {
  baseT: T;
  baseU: U;
}
interface Child<T, U extends undefined> extends Base<T, U> {
  childT: T;
  childU: U;
}

type AddProp<T> = T extends Base<infer T, infer U> ? { addedT: T, addedU: U } : never;

const obj = {} as AddProp<Child<string, never>>;
const a: string = obj.addedT;
const b: never = obj.addedU;
```

Looks okay to me, I think.

[Playground link to code](https://www.typescriptlang.org/play?jsx=0#code/JYOwLgpgTgZghgYwgAgEJwM4QDwBUA0yAqshAB6QgAmGyArtRDKBFQHzIDeAsAFDLIARpgi4AXMlwBuPgOFYiEojN4BfPqEixEKAMIALYABsqeQiXKUa9RsxCsOliNVrosZ4hx79kCQyfFJFQE-YypFYhV1Xj4wAE8ABxQAQSoqAAUoAHsEvA4AXklSCmdrNxxQGGhJQkrqog4Afi5kODTWQIJW9vClZFVkCXsAN2gVPgQskAwwZCzBACtkQs4BzGRUjOzcgzDsGahQAHNCEeg2NhVJ6dm4CQPj5bnFgDo2qg6rqZmhIYhRqBPeYLN49ZRAA)

**Comment by stephenh** [comment]
@jcalz ha! It's always a pleasure when you show up, so np. 

> Child<string, never> is definitely a subtype of Base<string, undefined>

Hm, yeah, that's true...

It took me awhile to figure out why your snippet was working, given how similar it is to what I was trying to do; I think what actually makes it "break", i.e. cause the same error I was seeing, is making `baseU` optional:

```
interface Base<T, U extends undefined> {
  baseT: T;
  baseU?: U;
}
```

This makes `obj.addedU` revert to `undefined`.

So, maybe that is what is going on; i.e. without a concrete usage of `U` in `Base`, it just fades away, and so is more likely to be simplified.

I already knew about the symbol trick, i.e.:

```
const T = Symbol();
interface Base<T> {
  [T]?: T;
}
```

To nudge marker interfaces from being structuralized away; but I'd always seen it used with `[T]?` instead of `[T]`.

Granted, if I use `[U]: U` then my concrete implementations will actually have to implement the dummy symbol...huh.

Okay, well I think the points around "`never` really is a subtype of `undefined`" + "known behavior of unused generics in marker interfaces" has convinced me that, right, there is not a bug here. I'll try to move forward with the not-optional `[U]: U` nudge and see how that goes.

Thanks guys!

**Comment by fatcerberus** [comment]
> So, maybe that is what is going on; i.e. without a concrete usage of U in Base, it just fades away, and so is more likely to be simplified.

Yep, this is just a fact of life in a structural type system.  Given:

```ts
type Fooey<T> = { foo: string };
type A = Fooey<string>;
type B = Fooey<number>;
```

Unlike in a nominal type system, `A` and `B` are the same type in TS.  In certain cases with phantom types like this, TS can still recover the type parameter, but you generally can't rely on it.

**Comment by RyanCavanaugh** [comment]
> Trying to infer T and U from a type like T | U seems problematic to me. My guess here (I'd be interested in hearing some official answer) 

I don't have spare cycles to dig all the way into a resolved issue, but yes, this is an extremely problematic thing to do and is best avoided wherever practical.
