### ISSUE TITLE
Strange behaviour when checking if an object extends with keyof

### ISSUE THREAD

**Issue by jaxoncreed** [microsoft/TypeScript#47218]
# Bug Report

### 🔎 Search Terms

 - "is not assignable to type" explanation
 - "is not assignable to type" keyof

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "keyof" and "extend"

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAggznCAnYBRAHsCA7AJnAHgyzwlwBopid8oJMa4qHTcA+KAXmZPwG4AUKEhQA8gCMAVhADGwAOoBLYAAsAYoogAbfAQ3bcAOQCGAWwhN6vJnGBJF2AOYduAbwFQoAbX06oDqABrCBAAewAzKF8jMwsAXQAuKGwAV1NxZCgAHyhbeydBAF9BYWgAZUgZRWMtCWk5LlgEZDQWXQ8xKVkFZXVNHUIAImNB7KhB8UG2cg73T09jJNT05EF5qHEkvIdHNahCgTZBIA)

### 💻 Code

```ts
type AssertExtends<Extended, Extends extends Extended> = Extends;
type ObjectWithFields<FieldNames extends string> = {
  [Field in keyof FieldNames]: number | string;
};
type SpecialObject = AssertExtends<
  ObjectWithFields<"a" | "b">,
  {
    a: number;
    b: string;
  }
>;
```

### 🙁 Actual behavior

The above code (simplified for demonstration) will cause an error when you assert that an object extends another. The error provided is "Type '{ a: number; b: string; }' is not assignable to type '"b"'."

### 🙂 Expected behavior

There should be no type errors.

**Comment by MartinJohns** [comment]
`FieldNames` is of the type `string`, you surely don't want to use `keyof` on this.

**Comment by jaxoncreed** [comment]
Welp. I'm an idiot. Thanks.
