### ISSUE TITLE
Relative outDir is ignored when it points to current working directory.

### ISSUE THREAD

**Issue by denvned** [Microsoft/TypeScript#4721]
So common source directory is not calculated and rootDir is also ignored.

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by mhegazy** [comment]
so your outputDir is the same as your input? so why specify an outputDir all together?

**Comment by denvned** [comment]
My source files are located in directory "src", and I want compiled files to be placed in current working directory (not in "src" directory). But without the *outDir* option outputs are placed in the same location as sources.

**Comment by mhegazy** [comment]
thanks @denvned.
