### ISSUE TITLE
TSLIB -  Unexpected token 'export'

### ISSUE THREAD

**Issue by PedroGuilhermeFariaDuarte** [microsoft/TypeScript#47225]
# Bug Report

### 🕗 4.4.4 

- This is a crash

### 💻 Code

```ts
// On line 15 in tslib.d.ts file i get the following error Syntax Error: Unexpected token 'export'

export declare function __extends(d: Function, b: Function): void;
```

### 🙁 Actual behavior

this error crash my application

**Comment by david-shortman** [comment]
Probably a tsconfig issue. `export` is a keyword that is only understood by ES6 modules. See https://stackoverflow.com/a/46611662/11087018 and https://www.google.com/search?q=typescript+library+unexpected+token+export+site:stackoverflow.com&client=safari&sa=X&ved=2ahUKEwjA_5fZ8vj0AhUDTd8KHT_1A3UQrQIoBHoECAYQBQ&biw=1440&bih=786&dpr=2
