### ISSUE TITLE
Add generic type to collections getters

### ISSUE THREAD

**Issue by Syjalo** [microsoft/TypeScript#47235]
# lib Update Request

## Configuration Check

My compilation *target* is `es2021` and my *lib* is `es2021`.

## Missing / Incorrect Definition

A generic type in `get` method of collections.

## Sample Code
``` ts
const m = new Map<string, string | number>();
m.set('key', 'value');
conat v = m.get('key') // Map<string, string | number>.get(key: string): string | number | undefined
```

## Request
``` ts
const m = new Map<string, string | number>();
m.set('key', 'value');
conat v = m.get<string>('key') // Map<string, string | number>.get<string>(key: string): string | undefined
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/get

**Comment by MartinJohns** [comment]
This would mistakingly lead people to believe they will surely get the specific type. Same reason why `JSON.parse()` is not generic.
