### ISSUE TITLE
Pattern matching does not work with `typeof`

### ISSUE THREAD

**Issue by orange4glace** [microsoft/TypeScript#47232]
# Bug Report

### 🔎 Search Terms

typeof pattern matching 

### 🕗 Version & Regression Information

4.5.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAGjAvDA3gKBjAhgLhgZgBoMYAjPARjQF81RJYBNJVE3GAVmM2D3xrRQAngAcApvGbJh4kADN4MAD4wZY+TEYBuNHICuYYFACW4GAFssUYAAsAPAC0YYgB5QxYACYRJAPgAUAF54DgCUrJjGCkEAdFhIiMj44eiYmIExpCS01EA

### 💻 Code

```ts
const X = {
  a: 3,
  b: 1
}
const Y = {
  a: 5,
  c: 3
}
type XY = typeof X | typeof Y;
function match<Z extends XY>(z: Z) {
  if (z.a === 3) {
    z.b
  }
}
```

### 🙁 Actual behavior

`z` stays as `Z`

### 🙂 Expected behavior

`z` should be inferred as `X`

**Comment by xiBread** [comment]
Use [`const` assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions)

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAGjAvDA3gKBjAhgLhgZgBoMYAjPARjQF9sIZRIo1HoYBNJVE3GAVmKZgefDToNw0NFACeABwCm8TslmKQAM3gwAPjDULNHANxoNAVzDAoAS3AwAtlijAAFgB4AWjAUAPKApgACb0cOwAfAAUAF54ngCU3Jg2WjEAdFhIiMj4ieiYmNFppCTUNEA

**Comment by orange4glace** [comment]
@xiBread A-ha. my bad. Thanks!
