### ISSUE TITLE
Enum string index access/narrowing string to valid enum key

### ISSUE THREAD

**Issue by brunnerh** [microsoft/TypeScript#47231]
# Suggestion

## 🔍 Search Terms

enum index signature
enum type guard
enum type narrowing

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow accessing an enum using a string via the index signature:

```ts
enum Test { ... }
const key: string = '...';

// Should ideally be of type `Test | undefined`, even without `noUncheckedIndexedAccess` because
// this apparently is an uncommon use case.
const value = Test[key];
```

Alternatively require a check that narrows the type from `string` to the enum type:

```ts
enum Test { ... }
const key: string = '...';
if (key in Test) { // Error without this
    const value = Test[key];
}
```

## 📃 Motivating Example

This would allow mapping of values that are potentially out of range/unsafe to an enum value.

E.g. if an URL path should be part of the enum, but is not guaranteed to be due to potentially different user inputs:

```ts
enum Section {
    details = 0,
    history = 1,
    //...
}

const pathTail = new URL(document.location).pathname.split('/').reverse()[0];
const currentSection = Section[pathTail] ?? Section.details;
// Or if check would be required first:
const currentSection = pathTail in Section ? Section[pathTail] : Section.details;
```

## 💻 Use Cases

This can be used in scenarios where a name needs to be mapped to an enum value for processing/storage but the input is unsafe (user input, third party system or API). My current workaround is to just add `// @ts-expect-error` because the JS already behaves as expected.

**Comment by RyanCavanaugh** [comment]
The enum objects are bidirectional, so if `key` is `"0"` you'll get back `"details"`. You can use `Test[key as keyof typeof Test]` if you want to proceed anyway

**Comment by brunnerh** [comment]
I was aware of the bidirectionality but forgot about the fact that properties are always strings, so as you mentioned there would be nothing preventing a lookup via a string containing an integer.
