### ISSUE TITLE
Implicit generics inference with nested types 

### ISSUE THREAD

**Issue by leibale** [microsoft/TypeScript#47230]
# Bug Report

### 🔎 Search Terms
Generics, Implicit Generics, Generics Inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generics

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAwg9gWwQQwHYBMoF4oAoB0hyATgOYDOAXFAILHHIgA8aIAfAJTZtSsDcAKAGhIsADYBLCKmBMYUCAA9g09OViIUGHjgDeAqFADGmtOmoxBAX0HDw0GJOnAA8mGAS4qcnIXLV6vBIZjpQ+oYmwRgW1kIi0ADKEMAArmC+SioYgaba2HhGTjIWRbIwnNxQKagA1qhwAO6otgBm1UYeXlAq5MAAjBn+2RpR6Gy4BlDkyWnUSanp5QA0k3Dunt4lUjJund5ybAIc1ABucBKYulZxEL19uMjkIKhGxqWV4VAA9F9QAAaFbbAfCRLToP7dexQCTqP5BMF-JZQABGKWAUwAFnAUmJMMjoBJUC0IPQIJgWsREP81ntyCDcuDJoDnPTRrgAOQIW7kZCkCDsjiCQw-QyigB6AH4BFYkZ9QWZcFzyDy+dResRCaRjlAzhcwpMIl5yHAxBB8GI4KRFdzeRBBZNrlZ7QI2i89t1bsAAEyDLJqEZg8aTaYLOYzRZsFaG0YWI6nc6Xa7CT1eh5PF5vIEfSYihpwYg1dSPPyQDpkpEAImZMlZYIrkNEMOhRJJxDJUApVIBDIhuGAGOgqEyvDIKS5Mg4TNKtYVnJtfIFQu+v1FUEl0qR1uVtrVwA1qC18b1WB4cqNJrNFqtSpVdus9qAA)

### 💻 Code

```ts
type Command = (...args: Array<any>) => any;

type Client<C extends Command> = {
  command: C;
};

type ClientOptions<C extends Command> = {
  command: C;
}

type Setup<C extends Command> = (client: Client<C>) => unknown;

function test1<C extends Command>(
  setup: Setup<C>,
  options: ClientOptions<C>
): void {}

test1(async client => {
  // `client.command` type is `Command`, but should be inferred from `options.command`
  client.command('message');
  //     ^?
}, {
  command(message: string): void {
    console.log(message);
  }
});

function test2<C extends Command>(
  setup: Setup<C>,
  command: C
): void {}

test2(async client => {
  // works as expected, "client.command" type is inferred from `command` (the next argument)
  client.command('message');
  //     ^?
}, (message: string): void => {
  console.log(message);
});
```

### 🙁 Actual behavior
test1 - `client.command` type is `Command`
test2 - works as expected

### 🙂 Expected behavior
test1 - `client.command` type should be `(message: string) => void`

**Comment by leibale** [comment]
[another demo](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAwg9gWwQQwHYBMoF4oAoB0hyATgOYDOAXFAILHHIgA8aIAfAJTZtSsDcAKAEAzAK6oAxsACWcVFGARywAIxMYUCAA9FGcrEQoMbXAKhRyEYKLDVcEw2nTUYXLD3EBrVHADuqABozKAckJxcBDmoANzhpTABvAF8hRWUVU3NkchBJEMcMbigE4PNQo3RcAHIEJXJkUggqjkFzcwB6dqgAPQB+YKSg81xa8nrG6mViaVRSNx4HVHI4ABsIfBW4UhG6hogOSMERcSlZeTTgACZ1TR0IPQMw40yLKxs7cvDYeagvH38hlA4GAZHIqMV8k9nLAoCkolBYvFiikBBdLi9srkJJCKkUSm0cU5qqNxk0WqUoJ0ev1zINgvi2p8MDsxntJsBprN4YjEhSymDVutNtsSXsDgSUrTDgIgA)

**Comment by RyanCavanaugh** [comment]
Duplicate #38623
