### ISSUE TITLE
Array.reduce: No overload matches this call

### ISSUE THREAD

**Issue by hamzahamidi** [microsoft/TypeScript#47238]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=24&ssc=21&pln=1&pc=1#code/C4TwDgpgBA8mwEsD2A7KBeKBvAUFKwEAHsAFxQDKwATgigOYDceUANgIYMCu79E5VWg2b4O3XhADqSagBM69ATQUioXaqyVCmOAL7McAY1QBnYFCTxkKE1HJxEqANoBdDFCe583gsTJQAckEFAIAaFjF6Hj5yIOUGMIjOKIlpOQVY4ITw-HVNQKz6AL0XHCNTc2oIEy5Wc0xLRxsWfAA6KtkuQwgAChbvHvZDQ1CLK1RRulliAEoMAD4Pfp9W1aGR5e8AwjNin3wXHP3XI-wZg2MbJFYIVtYkeh6qmrrzoAı)

### 💻 Code

```ts
type Option = {
  text: string;
  language: string;
  languageWording: string;
  url: string;
};

const options : Option[] = [{
  text: 'String',
  language: 'String',
  languageWording: 'String',
  url: 'String'
}]

const result = options
    .reduce(
      (acc, option, index) => [
        ...acc,
        'test'
      ],
      [],
    );

console.log(result);

```

### 🙁 Actual behavior

I get the following error. The compiler can't deduce `result` type when using `Array.reduce`
>No overload matches this call.
  Overload 1 of 3, '(callbackfn: (previousValue: Option, currentValue: Option, currentIndex: number, array: Option[]) => Option, initialValue: Option): Option', gave the following error.
    Type 'string[]' is missing the following properties from type 'Option': text, language, languageWording, url
### 🙂 Expected behavior
The compiler should deduce `result`type

**Comment by MartinJohns** [comment]
This is intentional, see #20407.

You can work around this by helping the compiler understand the type of `[]`: `reduce<string[]>(...)` or `[] as string[]`
