### ISSUE TITLE
Debugging Typescript codebase : Can't attach to VS Code TS server

### ISSUE THREAD

**Issue by orange4glace** [microsoft/TypeScript#47244]
# Bug Report

I'm trying to debug Typescript codebase by following 
https://github.com/microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code
I tried
[*Using stable VS Code to Debug Stable TSServer*](https://github.com/microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code#using-stable-vs-code-to-debug-stable-tsserver)
and [*Development VS Code with Development TSServer*](https://github.com/microsoft/TypeScript/wiki/Debugging-Language-Service-in-VS-Code#development-vs-code-with-development-tsserver)
but both are not working.

![Dec-25-2021 11-58-48](https://user-images.githubusercontent.com/17820596/147376455-17804941-05c8-41f4-804a-830df046fa86.gif)

### 🕗 Version & Regression Information

4.6.0

**Comment by andrewbranch** [comment]
Can you try using <kbd>⌘</kbd><kbd>⇧</kbd><kbd>P</kbd>  + "Attach to Node Process" instead of the attach debug configuration and see if that works for you? Allow at least a minute for breakpoints to be verified with that method... it is temperamentally slow sometimes.

**Comment by andrewbranch** [comment]
Can’t repro. I will say the debugger in VS Code is often pretty flaky for me, but this doesn’t seem to be a problem with our config.
