### ISSUE TITLE
Allow synchronous type-only import of ESM package from CJS

### ISSUE THREAD

**Issue by otakustay** [microsoft/TypeScript#47248]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

import, type, esm

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

For a ESM-only package `esm-package`, if we import types from it in a CommonJS file:

```ts
import type {SomeType} from 'esm-package';
```

TypeScript warns in typescript `4.6.0-dev.20211225`:

```
Module 'esm-package' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.ts(1471)
```

For type-only import this shouldn't matter since it doesn't emit JavaScript code, so we can allow 

## 💻 Use Cases

Types, in some cases, are not possible to lazy import asynchronously, such as a top level export:

```ts
import type {SomeType} from 'esm-package';

export const DEFAULT_CONFIG: SomeType = {
  // ...
};
```

**Comment by fatcerberus** [comment]
That error makes no sense.  It’s an `import`, not a `require()` - why wouldn’t it be able to load ES modules using the ES module import syntax? 😕 

That said, I’d expect this to work:
```ts
type SomeType = import(‘esm-package').SomeType;`
```

**Comment by weswigham** [comment]
#47807 should provide options here - you'll be able to explicitly

```ts
type SomeType = import(‘esm-package', { assert: {"resolution-mode": "import"} }).SomeType;
```
