### ISSUE TITLE
Inconsistency in treatment of methods between subclasses and mixins

### ISSUE THREAD

**Issue by zrait** [microsoft/TypeScript#47246]
# Bug Report

### 🔎 Search Terms

Mixin, Overloading, Intersection Types

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about differing behavior between mixins and standard subclasses

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?&fbclid=IwAR0EQvgEyF2RPcKvCz8lz1J-TnE40-L0P0ZZlnSpywzgw-Zp0VeEMkY9XgY#code/C4TwDgpgBAwg9gOwM7AE4FcDGw6oDwAqAfFALxQIQDuUAFAHSMCGqA5kgFxRMIgDaAXQCUZEgQDcAWABQMzABsmSJFABicOFADeMqFACO6JpgDWtJlwToAtgCMIqADRRblm-dQitAXxm-Z0gBm6AjYAJaIFCyocFQAikamhFAQAB7AEAgAJirwyGhYOPjqcEREtDBFXAReulCoEMDoqAhQCkoqAEIsKemZObBF2nV6eobGZhYU7g5e-nr+-nKIKFDdqACMZFGoMfGJZiVCUgHtymssAEy9GdkqJcPSYwfmbnaz2osyy-lt25Q0dYbWjHOT0camWgbUHSTDgl4bZzQk4-VZZf7UC6oS4gk5ZeETKEw-EQsyIqCXGHfAJAA)

### 💻 Code

```ts
type Constructor<T> = new (...args: any[]) => T;

class Foo {
  quack(a: number, b: number) {}
}

function narrowQuack<T extends Constructor<Foo>>(Ctor: T) {
  return class Bar extends Ctor {
      quack(a: number) {}
  }
}

const BarViaMixin = narrowQuack(Foo);

class BarViaSubclass extends Foo {
  quack(a: number) {}
}

const c = new BarViaMixin();
c.quack(1);
// ts is fine with this even
c.quack(1, 1);

const d = new BarViaSubclass();
d.quack(1);
// ts complains here that there is no method signature for quack(number, number)
d.quack(1, 2);
```

### 🙁 Actual behavior

Permitted method signatures differs between subclasses and mixins: subclasses treat method as override by subclass whereas class created through mixin treats method as having multiple valid signatures.

### 🙂 Expected behavior

Typechecking of method to be the same for subclasses and mixins, if the typechecker considers it valid to call quack with two args on the instance of the mixin class, I would think it would also work that way on an instance of a conventional subclass.

**Comment by RyanCavanaugh** [comment]
Unfortunately the `extends` mechanism doesn't generalize to higher-order, so `narrowQuack` produces an intersection (which doesn't overwrite the method signatures the way `extends` does). There's not much to fix here given than changing that (in either direction) would be a fairly impactful breaking change without much clear upside.

**Comment by Youmenomi** [comment]
Hi, @RyanCavanaugh 

I think this flaw pretty much indicates that `Mixin` is not available in `Typescript`. It is unacceptable that `c.quack(1, 1);` does not report an error. 

Forgive me for commenting without understanding how the source code works. But look again at the incorrect type `((a: number) => void) & ((a: number, b: number) => void)`. The first of the incorrect types `((a: number) => void)` is always the correct type we need. Hope this clue makes the correction process easier.

The following is the workaround used in my project.
```ts
type Constructor<T = unknown, U extends any[] = any> = new (
  ...args: U
) => T;
type ITrait<
  TBase extends Constructor = any,
  TDerived extends TBase = any
> = (Base: TBase) => TDerived;
type Trait<TTrait extends ITrait> =
  Parameters<TTrait>[0] extends Constructor<infer R, any> ? R : never;

type FixOverrideMethod<
  TTrait extends ITrait,
  IInstance = InstanceType<ReturnType<TTrait>>
> = {
  [key in keyof IInstance &
    keyof Trait<TTrait>]: Trait<TTrait>[key] extends IInstance[key]
    ? IInstance[key]
    : IInstance[key] extends infer M & Trait<TTrait>[key]
    ? M
    : never;
};
```
`FixOverrideMethod` effectively removes unnecessary types. However, The price is that I will lose vscode's go to definition jump and method annotation hints.
