### ISSUE TITLE
Type inference on an indexed type does not work with function values

### ISSUE THREAD

**Issue by acarrasco** [microsoft/TypeScript#47240]
# Bug Report

This comes from this StackOverflow question, which I suspect to be a bug:
https://stackoverflow.com/questions/70453626/how-to-build-typescript-objects-from-mapped-type-builder-functions

When you have an object that maps keys to values and those values are plain objects; accessing one of the values by a key that has a parametric type produces a value of the exact type. When the values are functions, accessing the object in the same way produces a value whose type is the union of all function values.

It does not matter how I write it (declaring types explicitly instead of using `typeof` and `ReturnType` in various places; or even wrapping the functions in objects that have the function as a field), the result is always the same, the type inference picks the union type instead of the concrete type.

### 🔎 Search Terms

- mapped types
- index types
- type inference
- type narrowing 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: 
- https://www.typescriptlang.org/docs/handbook/2/mapped-types.html
- https://www.typescriptlang.org/docs/handbook/advanced-types.html

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?target=5&ts=4.3.4#code/MYewdgzgLgBARgVwJYBsAmBTAThGBeGAbwFgAoGGKATwAcMB9AQwC4YAKASnwD52TyKMAGYgQrAOQALDChQhxAGjIUAvhyUDqdenFacefZYLiMsEgOai08KhkVG1GlQG4yZDAA8aILLCEIwYCgkcHhkdAAeABUYTygMMDRcAGsMKhAhSloMDLDUTBxuNlSqViiOVgAlDCgELDAo7IitHMzEfOwIAG0ogF1efgosGrqwPPROrpLezldSFSA)

### 💻 Code

```ts
const builders = {
  type_a: () => ({
    foo: 'hello',
  }),
  type_b: () => ({
    bar: 'good bye',
  }),
};

export function build<T extends keyof typeof builders>(key: T): ReturnType<typeof builders[T]> {
  return builders[key](); // here the compiler thinks builders[key] is the union of both values instead of the type indexed by `key`
}
```

### 🙁 Actual behavior

the type of `builders[key]` is `(() => {foo: string}) | (() => {bar: string})`

### 🙂 Expected behavior

the type of `builders[key]` is `builders[T]` for a concrete instance of the type `T`; as it happens when the map has values of types other than functions.

**Comment by MartinJohns** [comment]
You're wrong assuming `T` always refers to a single key, but that's not right. It can be a union of keys as well. You want #27808.

**Comment by acarrasco** [comment]
@MartinJohns then why does it work when trying to access a value that is not a function? :thinking:

**Comment by RyanCavanaugh** [comment]
This is a trade-off. Let's say you write
```ts
const a = builders[key]();
```
What's the type of `a` here? If we infer `ReturnType<typeof builders[T]>`, then that's an opaque conditional type that can't be narrowed. You wouldn't be able to write e.g.
```ts
if ("foo" in a) {
  // do something with narrowed 'a'
  consumeFooProperty(a);
}
```
We can either have the deferred generic form, or have the concrete "here are the possible options" form, but not both.
