### ISSUE TITLE
@deprecated does not work on index signatures

### ISSUE THREAD

**Issue by ab-pm** [microsoft/TypeScript#47256]
### 🔎 Search Terms

index signature deprecation annotation `@deprecated` jsdoc

### 💻 Code

```ts
interface Example {
    /** @deprecated please no longer use this, it's unsafe and kept only for b/c */
    [p: string]: any;
    /** @deprecated please use `.y` instead  */
    x: number;
    /** Superseeds `.x` */
    y: number;
}

function example(e: Example) {
    console.log(e.x); // marked as deprecated, as expected
    console.log(e.y); // not marked as deprecated, as expected
    console.log(e.z); // not marked as deprecated, but should be
}
```
[Playground with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKIA84FsAOAbFAbwChkzkB6AKiuQAEATCHKCBOSB5fCOAZxQgA9sjxCQAc2jIArgORgAFsD4AaZMDAByPrJB84MFHBBcA1szDJxeAJ7IYQqMgBGFBMioVS5ANo4ALmQ+MChQCQBdIJNbAG4fMmpaRmZWdk5uAn4UORQAAwA6WzyNfUg4Lk9vcmR0IJAZLBdoeJqk5ABlGRxoAQgGXUL0Eq8E5Ft6xuaoeIBfYmIYGRAEMGBxZAhMXAIACgggjGweAEpkEhqEcT4hAgKxCX2C9BPYygpkLDgoCy5+ZCYLDYHH66n+Wx6q36Yyu+luEHuQkeCNsr3eyGEVi+P36yH+gLSIIYYN0ELYnBh13hiORBQAXmiKB9MZ9vr88boCcDOOoXDIrHxFEIZHguM1iLMgA)

### 🙁 Actual behavior

`e.z` shows up like a normal property, but it's deprecated.

### 🙂 Expected behavior

Any usage of `e.z` should be highlighted as deprecated.

**Comment by ab-pm** [comment]
@a-tarasyuk Wow thanks for the fix! I don't know if it's easy to add, or rather should be asked in a separate issue, but I noticed that actually none of the jsdoc annotations work for index signatures, it doesn't show doc comments either.

**Comment by sandersn** [comment]
@ab-pm Definitely open a new issue for that. Thanks for noticing and filing these bugs.
