### ISSUE TITLE
A strict typed decorators for classes, methods, properties and parameters

### ISSUE THREAD

**Issue by sviat9440** [microsoft/TypeScript#47255]
# Suggestion

Right now we can make strict typed decorators for [classes](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgggg3gKAUIQAcoB7CAU3koBMEBbSiACzNoAoBKALgUigBLAHYBzXASJSozAK5RhCAOQBGAEwBmJQG5JhAL55DeAGazh8QWUW1qZGBHsAeACoJKADyrDaGCAE9iSjITLAA+DghgKFFmPhdeBDd8KQB6VIA6LL0EGQh5RSiY5l1jAAFbWHtgRygEdIRgZGQEQQwyAGs8FDQMACF3L0ofDGx8IzxJirsHe3rU9yhyKAAaRoxPIJpabtR0BABhCQnCIA) and [methods](https://www.typescriptlang.org/play?#code/FDBmFcDsGMBcEsD2kAEATAptRAnAhrLgBSx44DmGsAXCnpAJ4A0KADjoqxjrAwNIYGtANaDEoOoxaYAztBzxWhHLQAqDLmgAKHLjwYARDHIVLcAHiIBKFAF4AfCkjgAtgCNu9q2o0Ztu7l4jE0VlSxsHJ1cPHEcAb2AUJJQAehSAOkzE5JwqcBxUBOTilEz02XlQ3CZskpQANzwAG3AMWggYBGQUaxQiupLc2HzUCtNldMaWjAB+dOhmppIAC3gZGwAfDZQABgBuWpKAX0OTk+BoJrwZGRQAQT7DgAFMbHxlVJSUbg4cFmvvgAPLhwPyHdiIWBYKFoFAuKjLRBoay0GSwBSQciPAYoIYjFAAcgAjAAmADMBIOxXOxReWFwBFwnzoTSaKDWKEQwnBHChoNh8NgiLQJJRUXc3GxAzxBRQpLJVOSZ2yQA), but not for properties and parameters, because it does not have descriptors. This is the problem of typing such decorators.

## Example

```
function defineString(target: any, propertyKey: keyofAny) {
   Object.defineProperty(target, propertyKey, {
       enumerable: true,
       value: 'string',
   });
}

class A {
   @defineString // no error, but expected
   public someProperty: number;
}
```

[playground](https://www.typescriptlang.org/play?strictPropertyInitialization=false&ssl=5&ssc=7&pln=2&pc=4#code/GYVwdgxgLglg9mABAEwKbBmVBlKAnTAcwAooBDPQ1KALkTLAE8AaRABzzjdTykYGlUjOgGshcYPSYBKRAG8AUImUB5AEYArVNAB0aDFgAKnbr0akKVKKw5cefQS3lLlrxKjAgAtjzJqANqh0+CCozC5uiABuZP6hdADkAM74RAnhrgC+0gDcCpkKChD+ZElJiACCzq4AAvqYOKlghIgA9K2IYHDueJx4rGogUO4AHtzQqMgRbCABMBCISXA+xnZmdJ5eajx5BUUIS4E6-nAkWADulcTSuUA)

## 🔍 Search Terms
decorator typing strict property parameter

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

1. Think about how you can explain types for decorators without a descriptor.
2. Or provide special decorators syntax

## 📃 Motivating Example

1. I don't really like this solution, but it doesn't add any syntactic constructs.
```
declare type PropertyDecorator<T> = (target: Object, propertyKey: string | symbol) => void & {_type_: T};
declare function createPropertyDecorator<T>(decorator: (target: any, propertyKey: keyof any) => void): PropertyDecorator<T>;

const defineString = createPropertyDecorator<string>((target: any, propertyKey: keyofAny) => {
   Object.defineProperty(target, propertyKey, {
       enumerable: true,
       value: 'string',
   });
});

class A {
   @defineString // error, as expected
   public someProperty: number;
}
```

2.
```
// in generic - type for property
property decorator <string> defineString(target: any, propertyKey: keyof any) {
   Object.defineProperty(target, propertyKey, {
       enumerable: true,
       value: 'string',
   });
}

parameter decorator <number> numberParameter(target: any, propertyKey: keyof any, parameterIndex: number) {
   ...
}

// so if we have syntax for property and parameters, we can add for uniformity: 

class decorator classDecorator(target: any) {

}

method decorator methodDecorator(target: any, propertyKey: any, descriptor: TypedPropertyDescriptor<() => string>) {

}
```

## P.S.

If you don't like my idea, offer your options. Let's solve the problem of typing such decorators!

**Comment by MartinJohns** [comment]
```typescript
function notNull<T, K extends keyof T>(target: [T[K]] extends [string] ? T : never, propertyKey: K) { }

class Data1 { @notNull name!: string; } // No error.
class Data2 { @notNull name!: number; } // Error.
```

**Comment by sviat9440** [comment]
Wow! Thank you!.
What about parameter decorator?

**Comment by MartinJohns** [comment]
It's not possible for parameter decorators, because the `parameterIndex` argument is not a number literal.

Your best option is to wait for TypeScript to officially support decorators (which requires the [decorators proposal](https://github.com/tc39/proposal-decorators) to enter [stage 3](https://github.com/tc39/proposals#stage-3)). The TypeScript team mentioned several times that no further work will be put into decorators until then.

**Comment by sviat9440** [comment]
Thanks.

**Comment by sviat9440** [comment]
@MartinJohns How about private or protected members?

```
function notNull<T, K extends keyof T>(target: [T[K]] extends [string] ? T : never, propertyKey: K) { }

class Data1 { @notNull protected name!: string; } // Error
```

**Comment by RyanCavanaugh** [comment]
It looks like this is answered for non-parameters, and parameters are explicitly out of scope in the stage 3 decorator proposal.
