### ISSUE TITLE
Implicit Compilation of d.ts files not included in a VS project.

### ISSUE THREAD

**Issue by gravidThoughts** [Microsoft/TypeScript#4726]
I have an issue where I added a `Bower` component that distributes angular.d.ts, which I already have included elsewhere in my project.

Even though my `bower_components` directory is excluded from the project, it appears TSC is still compiling this d.ts resulting in duplicate declaration errors.

Is this the intended behavior of implicit compilation?

**Comment by danquirk** [comment]
Yes this is a problem today. See https://github.com/Microsoft/TypeScript/issues/4665 for some proposed solutions and discussion.

**Comment by mhegazy** [comment]
@gravidThoughts can you use `--listFils` and let me know where is the other angular.d.t.s is coming form? we have no builtin resolvers that will look under bower_component.

**Comment by gravidThoughts** [comment]
@mhegazy I found your answer on SO about adding compiler parameters to the project file, but I cannot find an item pointing to tsc in my project file.

It is a TS node console project.

Do I need to modify the targets file described here? 
`<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="False" />`

**Comment by mhegazy** [comment]
@gravidThoughts i am not sure i understand the question. can you link to the SO issue?

**Comment by gravidThoughts** [comment]
@mhegazy http://stackoverflow.com/questions/12710691/visual-studio-typescript-options

I created a new project with the HTML App with TS template as you refererred to in the above post. I still don't see the BeforeBuild target your refer to in your answer.

I do have VS 2013 Update 5, and installed VS TS 1.5 since I started this issue.

The bottom line is, I don't know how to send the  `--listFiles` parameter to the tsc compiler in VS.

**Comment by mhegazy** [comment]
can you share your build log.
in VS, goto tools\optoions\Projects and Solutions\Build and Run\ select "MSBuild project build output verbosity" to be "Detailed"

rebuild your project, and share that. feel free to email me at mhegazy at microsoft.
