### ISSUE TITLE
super access inside a private getter in es6 emit

### ISSUE THREAD

**Issue by Reaphook** [microsoft/TypeScript#47264]
# Bug Report

### 🔎 Search Terms
transformer,es5,class,super,private

### 🕗 Version & Regression Information

- This is a error
- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?downlevelIteration=true&target=2&ts=4.5.4#code/GYVwdgxgLglg9mABFApgZygCgJSIN4CwAUIohADYCGaaiAgvsaaQLYpQAWcAJjoyc1IAndiCFIARABV0UAEwA2ORIDcTZgF91WouorVaAYUQoAHqjDdaDPILvMABU4f3Xb9x9fPvPn4iduvkHBIcGe4Y7epOqkAObsiADELHyEAoIiUGJIaCAADihCAHRsnDw4aumIOjGIlBAQ6GiptcKi4sgcMGhFyZWCOqQ1AuQJEIgAvIhgKADuiIYVxBAIaHCjReRwsZgQRfWNNHwTJ4jSsorK2JU6qBg4QA)

### 💻 Code
```
function test() {
  class A {
    method() {
      return "Test262";
    }
  }

  class C extends A {                                                                                                                                                                  
    get #m() {
      return super.method();
    }

    access() {
      return this.#m;
    }
  }

  let c = new C();
console.log(c.access() === "Test262");
```

### 🙁 Actual behavior
Uncaught SyntaxError: 'super' keyword unexpected here

### 🙂 Expected behavior
print true

**Comment by IllusionMH** [comment]
You've intentionally ignored TS error(`// @ts-expect-error`) that tells you why this feature won't work when target is `ES5`:
`Private identifiers are only available when targeting ECMAScript 2015 and higher.`.

**Comment by Reaphook** [comment]
i found it dosen't work in es6 emit
