### ISSUE TITLE
CLI: --pretty flag should force add colors

### ISSUE THREAD

**Issue by SnirShechter** [microsoft/TypeScript#47266]
# Bug Report

### Summary

When running `tsc` with the pretty flag (`--pretty`), it will format the output correctly, but the color will not be forced and still be determined by the defaults. Thi

### 🔎 Search Terms

No search, I looked at the code itself.

### 🕗 Version & Regression Information

- This is just not the expected behavior 

### ⏯ Playground Link

No playground since this is a CLI issue. See the code in main branch [here](https://github.com/microsoft/TypeScript/blob/main/src/executeCommandLine/executeCommandLine.ts#L93).

### 💻 Code

Run `tsc --pretty`

### 🙁 Actual behavior

If the default is determined not pretty, --pretty will not force add colors.
![image](https://user-images.githubusercontent.com/26040325/147676698-3b373bcb-7bf0-42fc-b85b-acdae99c2793.png)

### 🙂 Expected behavior

`--pretty` should force add colors
![image](https://user-images.githubusercontent.com/26040325/147676713-f58c25a3-3b40-4c42-842c-8c4c69ea8465.png)

**Comment by RyanCavanaugh** [comment]
The "is default pretty" check is what we believe to be isomorphic to "does this terminal support colors?", so forcing color when we believe the terminal doesn't support colors isn't the right thing to do.
