### ISSUE TITLE
private members of of other instances of same class accessible within class member functions

### ISSUE THREAD

**Issue by piyushsoni** [microsoft/TypeScript#47265]
# Bug Report

### 🔎 Search Terms 

private member variable, other instance of class, other object, member function, private property accessible 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about private members access.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/MYGwhgzhAEAKCmAnCB7AdtA3gWAFDQOgAdEBLANzABd5oAzU5KgOTAFtaBeaAch4G48hYmUo1o4CC3ZdeAvEMLB0UxAFdgVFIgAUDJqw4AuaKtJoA5gBoJkacdNUylgJRZFwglQAWpCADp9KUNZIPt4QXxPL18AyXDobniQyOEAXwUogiI1ACMQUmBoUHR4HRcTBGR0dyzCEHgqaBRcgCtE6DR4AHc4JFQ0HT4bPhdUzwB6CegAFVjTbxQ1EAATaG8wcloLCngMJERtaDBcpaawkOhc+HMLEQpqeBsPQinjmFIqHhgwaBXSOh0JB7JrmKRgNDAWgoOjQHy0UCQCAAQmgLwILVagUYwRkHR8fmxBhk42EmP8yTx3AJcTsKXR0EQjTUiAwmNJ0AyuBeOXyhXuaCo5Vq0WUaFQDQpKDuQzmtDQeL8vGgAGo4bEibiOKrlTwdTSKXSZGMXlyuXgxVJiP10ABGDpdXpVAay9AATx4IwAylQwIgANY8E3c3BvOZKnZbGA8ZRsIikBp6qikbUHI4mABEsEORCQVDdvAuMj1SpID3EELW6BABbAwChUFI+Vo3U+vgwiKgvGd6B4-gzeDekGg8AAHrnNPAVhaVChJSBpTpc9U0LbNeFg4PpuGYN1tP6YAwukYZ+KmsuBgAmDoXu3+EpdcqRLdwZxUGAZuWdRUwGbu6A+n6VAZv4eC3mgl7+GWgpPngQA)

### 💻 Code

```ts
class Person {
    private firstName = '';
    private lastName = '';

    constructor(firstName: string, lastName: string) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public clone(): Person {
      let obj = new Person('', '');
      // This should have given error about firstName being private, 
      // as it's a different instance of the class! 
      obj.firstName = this.firstName;
      obj.lastName = this.lastName;
      return obj;
    }

    public print() {
      console.log ('The name is ' + this.firstName + ' ' + this.lastName);
    }
}

const person1 = new Person('Tony', 'Stark');

// This gives 'compile' time error : "Property 'firstName' is private and only accessible within class 'Person'."
// as expected
console.log(person1.firstName);

// This works fine:
const person2 = person1.clone();

// Prints "The name is Tony Stark".
person2.print();

```

### 🙁 Actual behavior

Typescript compiler should have given an error about accessing private member `firstName` of the instance `obj` as it's private even though we are in the same 'class' (in member function `clone()`). The private members should only be accessible with the `this` keyword. "private" access modifier doesn't work this way in C++, Java etc. 

### 🙂 Expected behavior

In the `clone()` function of class Person, calling `obj.firstName` should have given an error just like trying to access `person1.firstName` does below in the code.

**Comment by MartinJohns** [comment]
This is working as intended. `private` allows access from within the `class`, not only from within the very same instance.

> "private" access modifier doesn't work this way in C++, Java etc.

In Java and C# it works the same.

**Comment by piyushsoni** [comment]
Ha. That's news for me. I know it doesn't work that way in C++, but having worked only a little in Java I assumed it would be the same. I have no idea why it is allowed in Java and C#, but it looks like it's not a bug after all. Closing. Thanks!

**Comment by fatcerberus** [comment]
Looks like it's the same in C++, actually.

https://en.cppreference.com/w/cpp/language/access

> A private member of a class is only accessible to the members and friends of that class, **regardless of whether the members are on the same or different instances**

**Comment by piyushsoni** [comment]
@fatcerberus : Ok, that's a big revelation for me. :| ... For some reason I strongly remembered trying this exact thing in the past in C++ and it failing for me, but I surely can't be trusted for anything anymore :| ... Apologies for wasting people's time ... :(
