### ISSUE TITLE
Allow to specify type constraints at type declarations

### ISSUE THREAD

**Issue by Zip753** [microsoft/TypeScript#47268]
# Suggestion

## 🔍 Search Terms

`check type condition`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a convenient way to check that a declared type satisfies another type constraint.

## 📃 Motivating Example

Imagine if you could write the following:
```ts
// given
enum State {
    A = "a",
    B = "b",
    C = "c"
}

type StateToPayload = {
    [State.A]: number,
    [State.B]: boolean,
    [State.C]: string // <-- should fail here
} extends {[S in State]: number | boolean}; // new syntax proposal
```
The new syntax would check that the declared `StateToPayload` type extends the type that follows the `extends` keyword. This would take care of two things:
1. If you add another value to `State` enum, say `State.D`, then compiler would inform you that `State.D` key is missing from `StateToPayload`.
2. You're able to map each state to its own potentially more narrow payload type (`number` for `State.A`, `boolean` for `State.B`), while making sure that the payload type still matches the defined constraint (`string` isn't assignable to `number | boolean`).

## 💻 Use Cases

Let's imagine that we have a state machine which has some states and each state has a corresponding payload which has common properties, but can also have its own state-specific properties:
```ts
enum State {
    A = "a",
    B = "b"
}

interface StatePayload {
    done: boolean;
}

interface StateAPayload extends StatePayload {
    a: string;
}

interface StateBPayload extends StatePayload {
    b: number;
}
```
Now, if we want to express a mapping of state to its payload type, we can define another type for this:
```ts
type StateToPayload = {
    [State.A]: StateAPayload,
    [State.B]: StateBPayload
};
```
and then use it like this:
```ts
type StateAToPayload = StateToPayload[State.A]; // StateAPayload
```
But now if you add another state, then it's possible to forget to update the `StateToPayload` mapping with the new type. So if `State` becomes:
```ts
enum State {
    A = "a",
    B = "b",
    C = "c"
}
```
then everything else still compiles. However, it's not the end of the world, since having mapping for every state can be enforced as follows:
```ts
type StateToPayload<S extends State> = {
    [State.A]: StateAPayload,
    [State.B]: StateBPayload
}[S];

type StateAToPayload = StateToPayload<State.A>; // StateAPayload
```
which won't compile anymore after adding `State.C`, which is what we want. However, the following still compiles:
```ts
type StateToPayload<S extends State> = {
    [State.A]: StateAPayload,
    [State.B]: StateBPayload,
    [State.C]: string
}[S];
```
This isn't desirable in our use case, since we'd like to make sure that every payload has base properties from `StatePayload`. The way that I know how to make sure of that is not ideal:
```ts
type AssertTrue<T extends true> = T;
export type AssertStatePayload = AssertTrue<StateToPayload<State> extends StatePayload ? true : false>;
```
This works, however this requires polluting type exports with `AssertStatePayload` which isn't used anywhere, otherwise compiler complains about unused types or variables. (on the side note, if you know a better way to do it, I'd love to know it too, as it would make writing compile time type tests much more convenient)

Wouldn't it be much easier if you could do something like this instead? ✨ 
```ts
type StateToPayload = {
    [State.A]: StateAPayload,
    [State.B]: StateBPayload,
    [State.C]: string // <-- should fail here
} extends {[S in State]: StatePayload}; // new syntax proposal
```
The syntax is debatable of course, it's just the first thing that came to my mind. Upsides:
- more intuitive, concise and semantic syntax
- no need to pollute type exports with unused types only used for compile time assertions

**Comment by ahejlsberg** [comment]
How about just this:

```ts
type EnsureExtends<T extends U, U> = T;

type StateToPayload = EnsureExtends<{
    [State.A]: number,
    [State.B]: boolean,
    [State.C]: string // <-- fails here
}, { [S in State]: number | boolean }>;
```

**Comment by Zip753** [comment]
Oh wow, so simple and elegant, and covers everything described in my use case 🚀   Thank you!

**Comment by Zip753** [comment]
For posterity, `satisfies` now does exactly the thing that I originally wanted (and which `EnsureExtends` helped achieve) ❤️ 
https://github.com/microsoft/TypeScript/issues/47920
