### ISSUE TITLE
Readonly open-ended tuples have writable length property

### ISSUE THREAD

**Issue by ASDFGerte** [microsoft/TypeScript#47260]
# Bug Report

In general, `readonly` tuples appear to not have a `readonly length` property.

```ts
type Test = Pick<[number], 'length'>;
//   ^?
// type Test = { length: 1; }
// no readonly modifier
declare const x: readonly [number?];
x.length = 0; // no error
declare const y: readonly [number, ...number[]];
y.length = 0; // no error
declare const z: readonly number[];
z.length = 0; // error, as expected
```

### 🔎 Search Terms

readonly tuple length property

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about common "Bugs" that aren't bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=4.5.4#code/C4TwDgpgBAKhDOwoF4oAUCWBjA1gHgG0A7AVwFsAjCAJwF0AaKAcgBsIiBzYACyYD4A3AFgAUAHoxUKQD0A-KIlRQkWAiSoA3lDaceALigBGAVAC+CyUQD2UahACGAEytEWIKGSuOMAMww1RRwgsFns7KCwXRCgADwM7Jxc3KGJyKmpZWmERGIA6HS5uFCgABhNFaygaaitqQODQ8MiiaJB4h2dXd1TKGkZcgdJe6gJaLNEQfPZC4rKoCptq2vqQsOhm6IAvdsSuqCH00ezNqd0i1DnFJepGe3gqmMgsYAhHIA)

### 🙁 Actual behavior

A `readonly` tuple's `length` property is not `readonly`, and can as such we overwritten.

### 🙂 Expected behavior

A `readonly` tuple's `length` property should be `readonly`, similar to arrays, and disallow writes.

**Comment by jcalz** [comment]
(Linking to https://stackoverflow.com/questions/70501410/why-is-a-readonly-tuples-length-writable where this presumably came from)
