### ISSUE TITLE
Mapped type fails in typescript 4.5.4

### ISSUE THREAD

**Issue by tmtron** [microsoft/TypeScript#47271]
# Bug Report

In typescript 4.4.4 this code compiled fine:

```typescript
/**
 * type to get only those properties that are functions
 */
type FunctionProperties<T> = {
  [P in keyof T]: T[P] extends (...args: any) => any ? P : never;
}[keyof T];

type ReturnTypeOfMethod<T, K extends FunctionProperties<T>> = ReturnType<T[K]>;
```

see [Playground 4.4.4 example][1]

But the same code fails to compile in typescript 4.5.4 - see [Playground 4.5.4 example][2]
```
Type 'T[K]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[FunctionProperties<T>]' is not assignable to type '(...args: any) => any'.
    Type 'T[T[keyof T] extends (...args: any) => any ? keyof T : never]' is not assignable to type '(...args: any) => any'.
      Type 'T[keyof T]' is not assignable to type '(...args: any) => any'.
        Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(...args: any) => any'.
          Type 'T[string]' is not assignable to type '(...args: any) => any'.
```

The strange thing is that the `ReturnTypeNumber` type still shows the expected type (`number` in this example).  

Related [Stackoverflow Question: How to define mapped type for method return types in typescript 4.5.4?](https://stackoverflow.com/questions/70522585/how-to-define-mapped-type-for-method-return-types-in-typescript-4-5-4)

### 🔎 Search Terms

* 4.5.4
* type-mapping
* mapped-types

### 🕗 Version & Regression Information

- This is a <s>crash</s> compile error
- This changed between versions 4.4.4 and 4.5.4
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about *mapped types*
- <s>I was unable to test this on prior versions because _______</s>

### ⏯ Playground Link

* [Failing Playground 4.5.4 example][2]
* [Working Playground 4.4.4 example][1]

### 💻 Code

```typescript
/**
 * type to get only those properties that are functions
 */
type FunctionProperties<T> = {
  [P in keyof T]: T[P] extends (...args: any) => any ? P : never;
}[keyof T];

type ReturnTypeOfMethod<T, K extends FunctionProperties<T>> = ReturnType<T[K]>;
```

### 🙁 Actual behavior

We get a compile error, but the mapped type works as expected: see example in [Failing Playground 4.5.4 example][2]

### 🙂 Expected behavior

No compile error, like in previous typescript versions (< 4.5.4)

  [1]: https://www.typescriptlang.org/play?ts=4.4.4#code/C4TwDgpgBAYgrgOwMbAJYHsEAUBO7I5oQDOAPACoB8UAvFAN4CwAUFFANpZSoJQDWEEOgBmUcgF0AXGM7ioEAB7AICACbEoACgB0ugIY4A5sWl6EIAJS1qZkFAD8ULtIQQAbhBwBuFgF92AkKiEj7MLKCQUABKEMBwOAjk4BAA8sIAsrEAFuiqFAA0UADS8koq6rCIKBjYeAREZFTUdDFxCUmQFOxF4pShLAD0AFRDLFBDUACiABoAgulYADKTY0MDLEgANnrEGuQkwADC27sMY1DEwDg8hgBqepsAhNKX1wiG-awXVzcwKJpWJhfNg4WLxXgAcj0ACMkBDQmxfCxzgg4ABbaGeP7ATQ8MBwYAudGYnCA84gsEJbgIfHABFQJHMRnhZLRSmJZIAOWJnlobLaHMgaUywByeX2l2OO2IhQhqIxWJQEL6QA
  [2]: https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAYgrgOwMbAJYHsEAUBO7I5oQDOAPACoB8UAvFAN4CwAUFFANpZSoJQDWEEOgBmUcgF0AXGM7ioEAB7AICACbEoACgB0ugIY4A5sWl6EIAJS1qZkFAD8ULtIQQAbhBwBuFgF92AkKiEj7MLKCQUABKEMBwOAjk4BAA8sIAsrEAFuiqFAA0UADS8koq6rCIKBjYeAREZFTUdDFxCUmQFOxF4pShLAD0AFRDLFBDUACiABoAgulYADKTY0MDLEgANnrEGuQkwADC27sMY1DEwDg8hgBqepsAhNKX1wiG-awXVzcwKJpWJhfNg4WLxXgAcj0ACMkBDQmxfCxzgg4ABbaGeP7ATQ8MBwYAudGYnCA84gsEJbgIfHABFQJHMRnhZLRSmJZIAOWJnlobLaHMgaUywByeX2l2OO2IhQhqIxWJQEL6QA

**Comment by ASDFGerte** [comment]
If your main goal is to just get it to work, you can give the compiler a helping hand:
```ts
type ReturnTypeOfMethod<T, K extends FunctionProperties<T>> =
  T[K] extends (...args: any[]) => any ? ReturnType<T[K]> : never;
```
You know the `extends` always holds, and then the compiler can also be sure. Tbh i'd even expect it worked in earlier versions due to some bug, not the other way around. While i am not sure, it seems unlikely, that the compiler would reason that far about the type there. However, i'm just some other TS user, maybe i'm wrong.

**Comment by RyanCavanaugh** [comment]
This was a documented breaking change; see https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#restrictions-on-assignability-to-conditional-types

**Comment by tmtron** [comment]
Thanks for the info.
