### ISSUE TITLE
tsserver does not respect watchOptions, always uses defaultWatchFileKind (FixedChunkSizePolling)

### ISSUE THREAD

**Issue by MarcCelani-at** [microsoft/TypeScript#47279]
# Bug Report

tsserver does not respect the watchOptions configuration in a tsconfig.json file. Because the ConfiguredProject is not passed all the way down to this [host watchFile](https://github.com/microsoft/TypeScript/blame/1298f498f4cde7fa53cbf050ebfeefdf85c848ec/src/compiler/sys.ts#L891) function, it instead goes to [the default](https://github.com/microsoft/TypeScript/blob/8590f0db408c419d25ea767783428b59fe6c9d0b/src/tsserver/nodeServer.ts#L249). This introduces latency any time a project is updated in the background, making tsserver slow to reflect changes after a checkout or rebase.

### 🔎 Search Terms

performance, slow, FixedChunkSizePolling, useFsEvents, watches, tsserver, checkout, rebase

### 🕗 Version & Regression Information

I do not know when this regression was introduced, but it is older than 4.4.

### ⏯ Playground Link

I do not have a playground link.

### 💻 Code

I have a very simple repro of this with instructions on how to repro here: https://github.com/MarcCelani-at/TypeScriptRepros/pull/1

### 🙁 Actual behavior

tsserver does not respect tsconfig.json watchOptions and the default file watch option is used instead.

### 🙂 Expected behavior

tsserver should respect tsconfig.json watchOptions and useFsEvents when it is specified

**Comment by sheetalkamat** [comment]
This is working as intended… You would want to set the watch options in vscode as well.. the files for the project are shared between multiple projects from tsserver point of view and they are governed by tsserver watching strategy ..

**Comment by MarcCelani-at** [comment]
Thanks for the quick reply @sheetalkamat , I'll give that a try.

**Comment by MarcCelani-at** [comment]
That's working. I had to dig to find documentation of this. I think it would be helpful to advertise this more widely.
