### ISSUE TITLE
One year later: TypeScript still cannot emit valid ES modules

### ISSUE THREAD

**Issue by ctjlewis** [microsoft/TypeScript#47270]
# Bug Report

This report is being submitted again as one year has passed since this team proposed Node12 module resolution as a workaround.  There has been no effort to make VS Code autocomplete resolve full specifiers with this module target set, presumably because that would involve resolution by the compiler (something that has been precluded on the basis of bureaucratic sclerosis). 

The best we can get out of the compiler as far as emitting valid ESM is letting VS Code populate the import and then manually resolving the entry points by hand, for *each* import.  It seems incredibly obvious that these are bad decisions and we should really work towards supporting the standard that was released 7 years ago now.

See original report: https://github.com/microsoft/TypeScript/issues/42151#issue-776143967

**Comment by RyanCavanaugh** [comment]
We've explained the rationale behind not modifying import paths on emit many times, and don't see value in rehashing that discussion since it relates to a core design goal.

This report is not actionable beyond venting and that's been accomplished. Please file something concrete in the future.
