### ISSUE TITLE
Infer removes keyof constraint from resulting type

### ISSUE THREAD

**Issue by sethveale** [microsoft/TypeScript#47276]
# Bug Report

### 🔎 Search Terms

infer mapped type variadic tuple keyof homomorphic

### 🕗 Version & Regression Information

4.4.4
Reproduced with 4.5.4 and 4.6.0-dev.20211230

I've spent quite a lot of time in various recursive mappings of object and variadic tuples and I think I've eliminated most of the pebkac issues I've had in the past. I'm perhaps over-using the `readonly` keyword with tuples.

Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about everything. (I've read the FAQ before.)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211230#code/JYOwLgpgTgZghgYwgAgCoQM5mQb2XAZTClAHMAuZLEkUgbnwCEB7ZgGwjhEoCNWOuDOAFkIYABbMAJpQAUASmQBeAHzIAbs2BSGAXwBQ+gPQAqE-uQm0cANaZ8yOwE9mMZGACuABw7JXDsCcvFC4pZABbOC8MZGBsMGYA719-CRRwiHCeaHcgzAA6CxMjfUDg5FEs6FQ8jFRkiEYoZjsQAB5UABpkAGkIJxiIAA9IECkYqE4pZhA2J2RZZ39UeQBtAF01JQte-sGRiDGJqZm55A3kAH5kSbhp2fmLyiMjZBBgNkNkXYHkYdHxjcTg9zqAYDk+k51lcgXdTo9UKtIetoc9Xjw4BgIDtvjtIfsAcc4SDVmCcgAJKbdfI02RkqDWD7yaEvZDiKZAhAeKAYYDqbHfb7XW73M6rRGUu7rak0yrZKA1YJ1BpNFqHDrdVBwD4qdY45CUEAQflQOj6wXIYyvOJUCCZGIJZAIZhQSYIMBnBBwNhcthwSDudm5coSZgeUjiUp5ZAEZgZdBYOXQDCq1rKCqZeWKzD1HyNZqtDqYMDdVYAckIxDIZe6FdEoakZc2ZuMZiK1jsMTgjn6qQafjc3bKITGESiMRtjqH-dSQYyVQZw4whUsJWGXhd8WjSYVtVzHA1PwJh0BIvhCyWbhWGy2eL2fwOR1hose0OFwLFqOQrPenzvv3+E8iRfUEQHBBlkW-dFMQFQVrlkSEH0JHsXCvGEzxJRFkS-I0TUUH87TCR1JgAWmLOAeDYYAMHEQMUEvJ0ZmobVwC+QVKHxJCgOfc9STAikqWQGl8jpfiGS1JkWVedk7k5bleX5c0YUlMJAKfBjUCg-BRzgUgWKUoVGTYLinwws5Fl7K81iktloBQBJmAMuCeMw1YVOlITZUzao9waQ8JLYXUnO+Q1jRyJzQpNS0LRCt4wtNQxWQkajkAAdxdGwSLgZoPFHFKYFAFAeA8bAAElAzDCMyrLMJJg3KBsBtUAnRg2JsHZNhojSuJaOYNIGWK0gYhdZBSrLcI2TgdQyAceAkC8b0JvCONDmwch5CjcpY3jYsdxiJQMwXbNlTzIssFLCsiBoUga2QOsxEkRtm30IA)

### 💻 Code

```ts
interface Test { aString: string; aBoolean: boolean; aMethod: () => void; }

type MemberTypesTupleBroken<T, Keys extends readonly (keyof T)[]> =
  Keys extends readonly [] ? readonly [] : // nil

  Keys extends readonly [infer Key] ? readonly [T[Key]] : // base <-- doesn't think Key is a keyof T
    
  Keys extends readonly [infer Head, ...(infer Tail)] // head recursive
    ? readonly [T[Head], ...MemberTypesTupleBroken<T, Tail>] // <-- doesn't think head or tail are keyofs T
    : never;
        
// it seems to correctly calculate the type though
type SomeTestMembersBroken = MemberTypesTupleBroken<Test, ['aString', 'aMethod']>;

// Work-around
export type MemberTypesTuple<T, Keys extends readonly (keyof T)[]> =
  Keys extends readonly [] ? readonly [] : // nil

  Keys extends readonly [infer Key] // base
    ? (Key extends keyof T ? readonly [T[Key]] : never) // need to re-establish the keyof constraint

    : Keys extends readonly [infer Head, ...(infer Tail)] // head recursive
      ? Head extends keyof T // and again
        ? Tail extends readonly (keyof T)[] // here too
          ? readonly [T[Head], ...MemberTypesTuple<T, Tail>]
          : never 
        : never 
      : never;

// this work-around is fine but I thought I'd report it in case it helps with other bugs or I'm having a facepalm
type SomeTestMembers = MemberTypesTuple<Test, ['aString', 'aMethod']>;
```

### 🙁 Actual behavior

If, prior to infer, a type is a keyof T; after the infer it is no longer a keyof T.

### 🙂 Expected behavior

Types retain the type information they had prior to infer, after infer.

**Comment by sethveale** [comment]
The need to re-add the `readonly` keyword on resulting tuple types seemed like it might be related as well.

Maybe a year or so ago, I found a ticket that was about retaining type information within the compiler but I seem to have lost the link to it.

It was certainly a bit painful to figure out that solution for mapping tuples.

**Comment by sethveale** [comment]
I figured out how to use Github. These are the issues that I think may be related:
https://github.com/microsoft/TypeScript/issues/40945
https://github.com/microsoft/TypeScript/pull/41169

I'm out of my depth on this stuff but mapping tuples via de-structured `infer`s does seem to require some massaging in most cases.

**Comment by RyanCavanaugh** [comment]
The positional information of where an `infer` occurs isn't used to infer additional constraints on it - it's a straightforward structural match the same way you'd get in other inference contexts. This is generally more desirable.

WLOG, you can write
```
  Keys extends readonly [infer Key] ? readonly [T[Key & Keys[number]]] : // base
  //                                                  ^^^^^^^^^^^^^^^
```

**Comment by nkappler** [comment]
> WLOG, you can write

>  Keys extends readonly [infer Key] ? readonly [T[Key & Keys[number]]] : // base
  //                                                  ^^^^^^^^^^^^^^^

I have tried this but it doesn't help.
It does resolve the error in this line, but not the subsequent errors, also the resulting type is then not very specific.
Could you provide an example from start to finish @RyanCavanaugh ?
