### ISSUE TITLE
Enum internal reference points to the wrong value.

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#47285]
# Bug Report

### 🔎 Search Terms
- Enum 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

#### I tried the latest version 4.5.4 and version 3.3.3 as well as nightly 4.6.0-dev.20211231 in Playground.
All successfully reproduced this issue.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/KYOwrgtgBAglDeAoKKoEMoF4oCYA0yqARllAMwGpQAepaAdEZagJ6lH1rMoBepL9WgCp0gggF8gA)

### 💻 Code

```ts
enum A {
    a = 2,
    b = 3,
    x = a.b,
    y = b.a,
    z = y.x * a.x,
}
```

### 🙁 Actual behavior

```js
var A;
(function (A) {
    A[A["a"] = 2] = "a";
    A[A["b"] = 3] = "b";
    A[A["x"] = 3] = "x";
    A[A["y"] = 2] = "y";
    A[A["z"] = 9] = "z";
})(A || (A = {}));
```

### 🙂 Expected behavior

- Keep `a.b`, `b.a`, `y.x * a.x` unchanged OR they should be qualified to `EnumName.MemberName` like `A.a.b`,`A.b.a`,`A.y.x`, `A.a.x`
-  report an error.

**Comment by MartinJohns** [comment]
This seems to be intentional, as per [this comment](https://github.com/microsoft/TypeScript/issues/25044#issuecomment-398125921):

> Last in wins when there are duplicate values in an enum

**Comment by fatcerberus** [comment]
The duplicate values aren’t the problem AFAICT (see the linked PR); it’s that `a.b` resolves *at all*.  Enum members can reference other enum members, but `a.b` shouldn’t resolve since that’s essentially `(2).b`.  TS seems to be treating it as a reference to the enum itself instead.
