### ISSUE TITLE
RegExp exec/match/split/etc return type should be `(string | undefined)[]`, not `string[]`

### ISSUE THREAD

**Issue by dj-foxxy** [microsoft/TypeScript#47284]
`/(a)|(b)/.exec('a')` returns `['a', 'a', undefined]`. The libs say `string` is the return array element type. But `undefined` is present if a reg exp group did not match.

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/17053#issuecomment-314154098

**Comment by dj-foxxy** [comment]
Thanks @fatcerberus. Is there a way to opt out of this? It's been the root cause of two bugs in the project I'm working on and it really annoys the ESLint @typescript-eslint/no-unnecessary-condition because it believes it can't be undefined.

**Comment by fatcerberus** [comment]
Your only real option is to enable `noUncheckedIndexedAccess` which implicitly adds `undefined` to all array accesses, though that might prove to be an overly large hammer.

**Comment by dj-foxxy** [comment]
Yer, that hammer is a bit too weighty for us. I think we'll make a collections of wrappers (e.g. `exec = (pattern, string) => (string | undefined)[]`) and get ESLint to error when not using the wrappers.
