### ISSUE TITLE
Having `noImplicitAny` Not Enabled Impacts Type Inference

### ISSUE THREAD

**Issue by joealden** [microsoft/TypeScript#47294]
# Bug Report

### 🔎 Search Terms

array union types type inference noImplicitAny disabled

### 🕗 Version & Regression Information

This  changed between versions `4.2.3` and `4.3.5`, as before `4.3.5`, type inference for the 2nd case inferred `any` regardless of if `noImplicitAny` was enabled. After `4.3.5`, the expected inference happens when `noImplicitAny` is enabled, but behaves as it did before `4.3.5` when `noImplicitAny` is not enabled.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noImplicitAny=false&ts=4.5.4#code/PTAEAMEsBcFMFtygIYDsAmEDWsCeTkAnWUAIwHtoALUaXAB1k2QGdRYAPRgYzkwApwLaIUioA5qAA+oVAFd4pWIQIYI8xcvABKAFDdyqYSkKFkuAIwAuUAEFT5gDzDRE6bIVLCAPlABeUABtAF0Abn1DY3hkekZ0C38TM0sAOmj6fn4YBAAaUBxcbX9fQOz4PILgvV0QCDLVTHACgmIySho6OJQ2cDR8CKNoJPMAJht7ZOcRMXFfGQmnDS9fAJDwg0HQdLiRxKJkkbSYzLKKvCK-EtP8vCqgA)

### 💻 Code

```ts
// `item` and `key` are both typed as expected (`string | number` and `number` respectively)
const array1: Array<string | number> = [];
const mapped1 = array1.map((item, key) => [item, key])

// `item` and `key` are both typed as `any`
const array2: Array<string> | Array<number> = [];
const mapped2 = array2.map((item, key) => [item, key])
```

### 🙁 Actual behavior

When `noImplicitAny` is not enabled in the TS config, inferred types are impacted (inferred as `any` in the above case).

### 🙂 Expected behavior

`noImplicitAny` shouldn't impact inferred types, or if this is expected behaviour as having this option enabled allows for better heuristics to work, then I think having it documented that this settings isn't essentially just a "lint rule" might be a good idea.

**Comment by DanielRosenwasser** [comment]
I've checked, has nothing to do with the initializer.

[Playground link with `noImplicitAny` **disabled**](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&ts=4.5.4#code/FAMwrgdgxgLglgewgAhAhBGAFCCBBAJwIEMBPDALmUJNIB4BnGAuCAc2QB9kIwBbAEYBTAgD4AlMgDewZHOQB6BcgAGcGEL4rkxCABNVAayGltxAkOQCEMABbIYpAA5CDxBsiEAPF7FfIsFSYWdi4efmECM31VXkERFXFZeSgkJmQ+YicXPQxkAF5UfCIyDAA6TKcsLHVNABpkY1JJfNFkAG1avgamgF0kgF9gUEhYRBQ0BAAmHGLaKaoaMkZmVjY27iX6OMiJaWS5JVUu6IMVJrMLKxt7RxydDxVdUwPkVIh0ypypgqKtqYqWWqXR6JhabU6Gm6jRM-WAAyAA)

```ts
function foo1(fnArray1: Array<string | number>) {
    // `item` and `key` are both typed as expected (`string | number` and `number`)
    const mapped1 = fnArray1.map((item, key) => [item, key])
}

function foo2(fnArray2: Array<string> | Array<number>) {
    // `item` and `key` are both typed as `any`
    const mapped2 = fnArray2.map((item, key) => [item, key])
}
```

**Comment by ahejlsberg** [comment]
This is apparently by design. See #42620. I presume code existed before that PR that depends on parameters being assigned type `any` when `-noImplicitAny` is disabled.

**Comment by DanielRosenwasser** [comment]
Thanks for digging that up, totally forgot about it!
