### ISSUE TITLE
Proposal: --bundle option should allow for restricting output to parts of a project

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#4729]
Taking up issues #4225 and #4434 I like to propose that it should be possible to create *groups of bundles* within a project.

A project commonly consists of files constituting the task to accomplish (i.e. the "library" to create), a number of test cases and other supporting files.

Concatenating them all into a single file would not be the intention of the programmer.

Hence, I'd like to propose to add an optional parameter to the `--bundle` option allowing for selectively adding branches of the project to the generated file.

The suggested format is a JSON array, allowing for concatenating parts of a project into different JavaScript files.

.

Here's an example of such argument:

``````javascript
[ "./TypeScript/*.ts": "./js/combined.js"   // end glob either with wildcard or directory to search for input
, "./Lib/*.ts": "./js/Lib.js"   // syntax is: "source file list": "concatenated destination file"
, "./Test/TypeScript": "./Test/js/main.js"
]
``````

... or a more vivid example:

``````javascript
[ "./Angular/**/*.ts": "./out/angular.js"
, "./Animation/**/*.ts": "./out/angular-animate.js"
, "./Aria/**/*.ts": "./out/angular-aria.js"
, "./Cookies/**/*.ts": "./out/angular-cookies.js"
, "./Loader/**/*.ts": "./out/angular-loader.js"
, "./Messages/**/*.ts": "./out/angular-messages.js"
, "./Touch/**/*.ts": "./out/angular-touch.js"
, "./~Test": "./out/Test/main.js"
]
``````

**Comment by weswigham** [comment]
Question: Why not just have multiple config files, one for each target?

**Comment by SetTrend** [comment]
I'm not sure if Visual Studio project settings will allow for that.

**Comment by weswigham** [comment]
Even if they don't presently, they probably could.

**Comment by cveld** [comment]
Will we be moving completely from msbuild towards nodejs/gulp taskrunners?
Because I believe your requirement can already be met with this approach,
even within a classic msbuild project.

2015-09-11 11:31 GMT+02:00 Wesley Wigham <notifications@github.com>:

**Comment by weswigham** [comment]
Yeah, if you use `gulp-typescript` you can use as many tsconfigs as you'd like. The `tsc` command line compiler itself can, too - it just has the odd limitation that the `--project` flag takes a folder and not a config file... but since `tsconfig.json` files can reference files outside their own subfolder... it works fine, it can just be a bit awkward to use.

**Comment by mhegazy** [comment]
As @weswigham mentioned, this is something that is achievable by calling the compiler multiple times. The compiler is not meant to be a replacement to your build driver, e.g. gulp/grunt/msbuild etc.. and it can not assume all of their tasks.
