### ISSUE TITLE
setting envirment variables for tsserver in vscode

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#47301]
# Suggestion

## 🔍 Search Terms

is:issue vscode tsserver environment variables 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [y ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ y] This wouldn't change the runtime behavior of existing JavaScript code
* [ y] This could be implemented without emitting different JS based on the types of the expressions
* [ y] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ y] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow selected bash environment environment variables to be forwarded to  **tsserver** under **vscode**.

## 💻 Use Cases

My environment requires the bash environment variable setting NODE_PATH=$(npm root -g) in order that tsc can find the global node_modules folder. So I set it in ~/.profile and ~/.bashrc. No problem.

However, in vscode the **tsserver** apparently doesn't have access to the NODE_PATH setting, so it reports an error when global imports are declared, e.g.,

```
import npm from 'npm' // Cannot find module 'npm' or its corresponding type declarations.ts(2307)
```

However, by ignoring the error

```
/* @ts-ignore */
import npm from 'npm' // No error now.
```

the compilation will succeed because **tsc** knows about NODE_PATH.

I cannot see any vscode/typescript setting for setting environment variables for **tsserver**, let alone a setting that requires executing a program.

Either such a feature is missing or it is not well documented (or I haven't found it).

Any info about a workaround would be greatly appreciated in the meantime.

*Note: originally submitted as a [vscode issue](https://github.com/microsoft/vscode/issues/140064)*

**Comment by sheetalkamat** [comment]
We do pass environments to tsc and tsserver. NODE_PATH is never used in our code.. So I am not sure what you say by its working in `tsc`. From your report it sounds like some of the imports are not working.. You can see the difference in resolution by setting traceResolution to true in compiler options and running tsc and checking tsserver log to see what is the difference.

**Comment by craigphicks** [comment]
@sheetalkamat - 
> You can see the difference in resolution by setting traceResolution to true in compiler options and running tsc and checking tsserver log to see what is the difference.

Extremely helpful.  Thank you so much.
