### ISSUE TITLE
"any" type overriding the type defined inside class

### ISSUE THREAD

**Issue by NikhilG777** [microsoft/TypeScript#47316]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙂 Expected behavior

When we are initialising the properties inside the class and writing their type, "any" is making the type override.
TS playground link: https://www.typescriptlang.org/play?#code/MYGwhgzhAEAKCmAnCB7AdgbwLAChr+jTAFt4AuaCAF0QEs0BzAblwOmHWsQFdgqVEACjRkwaAJ4BKbHjYEqAC1oQAdEVLQAvIRaz8AX1yGcuEPCqF4AdwTJ0Wy1bhJUaQQBZJujmlRmVICgMwta2rl64kSbRQA
As you can see, we are able to assign number to type string.
Not sure if this is a bug or just "any" is the reason.

**Comment by MartinJohns** [comment]
This is working as intended. `any` is a way to opt-out of type-safety.
