### ISSUE TITLE
bind generic type error

### ISSUE THREAD

**Issue by macheteHot** [microsoft/TypeScript#47318]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 3.3.3 and  4.5.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysD2AnCAeAKgPigXigbwFgAoKKAZ2AENgIAuKNYgX2NaIDMBXAOwGNgAlvG5R28eOgwAKYAAsBZWnCSpMASkIlSUXsLLwANhAB0B+AHMZ8ssYrUIa5my59BwqACNKiSVIHcBQUoDOHtaNA1ibR09YHIEZCUE1SxcTWjouxpaf0CBYNCaKO0WLVJkYE5EETF4Yw9-ABNfChVHIlLiL0QpPEpaAEYmNSk1IA)

### 💻 Code

```ts
type Store<T> = {
  state: T
}


function foo<T>(this:Store<T>){
    console.log(this.state)
}

function bar<T>(initialState:T){
    const store:Store<T> = {
        state:initialState
    }
    return foo.bind<T>(store)
}

bar({a:1})()
```

**Comment by DanielRosenwasser** [comment]
There is currently no way to propagate type parameters, so `bind`, `call`, and `apply` don't work well with generic functions.

**Comment by DanielRosenwasser** [comment]
Also please fill out the issue template more accurately in the future. This is not a crash
