### ISSUE TITLE
lib.es5.d.ts incorrectly disallows a null or undefined input for parseInt()

### ISSUE THREAD

**Issue by octogonz** [microsoft/TypeScript#47313]
# Bug Report
 
### 🔎 Search Terms

parseInt

### 🕗 Version & Regression Information

4.5.5

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about parseInt

### ⏯ Playground Link

 
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAHhC8EAcCGAnAziAkgOzACgFdsATEAMwEtsRiBKAbgFgAoIA)

### 💻 Code

```ts
let x = parseInt(undefined);
```

### 🙁 Actual behavior

Compile error: `Argument of type 'undefined' is not assignable to parameter of type 'string'.`

### 🙂 Expected behavior

This code should compile without errors.

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) says: 

> The parseInt function converts its first argument to a string, parses that string, then returns an integer or NaN.

And more specifically, the ECMAScript standard says:

![image](https://user-images.githubusercontent.com/4673363/148142586-8db67572-aab5-41e5-91ea-d52763a50c22.png)

Thus `parseInt(null)` and `parseInt(undefined)` will return `NaN` because their string forms are "not a number."  This is a more intuitive and useful behavior.

### Recommended fix:

Change this definition:

**lib.es5.d.ts**  (CURRENT)
```ts
/**
 * Converts a string to an integer.
 * @param string A string to convert into a number.
 * @param radix A value between 2 and 36 that specifies the base of the number in `string`.
 * If this argument is not supplied, strings with a prefix of '0x' are considered hexadecimal.
 * All other strings are considered decimal.
 */
declare function parseInt(string: string, radix?: number): number;
````

...to this:

**lib.es5.d.ts**  (PROPOSED)
```ts
declare function parseInt(string: string|null|undefined, radix?: number): number;
````

**Comment by RyanCavanaugh** [comment]
This has been the behavior for approximately forever without complaint, so I'm inclined to believe people find it more helpful than hurtful. The much more common feedback we get is that people want operations that produce `NaN` to be type errors, since very little code is resilient to `NaN`s. You can add an overload to your project through declaration merging if you'd like.

Also, not that this really matters, but:
```
> parseInt(null, 26)
< 23
> parseInt(undefined, 36)
< 86464843759093
```
