### ISSUE TITLE
Nodenext not recognized as moduleResolution

### ISSUE THREAD

**Issue by jmclean-starburst** [microsoft/TypeScript#47311]
# Bug Report

When using Typescript v4.5.4 along with VS Code v1.63.2, `nodenext` appears to be running into incompatability issues:
![image](https://user-images.githubusercontent.com/72760973/148089551-40904fd1-c4ec-4696-9851-accb29b5f73b.png)

hovering over the `moduleResolution` IDE hint provides the below message when value is `nodenext`
```
Value is not accepted. Valid values: "Classic", "Node".
```

hovering over the `module` IDE hint provides the below message when value is `nodenext`
```
Compiler option 'module' of value 'nodenext' is unstable. Use nightly TypeScript to silence this error. Try updating with 'npm install -D typescript@next'.
```

compiler options configured based on docs: https://www.typescriptlang.org/tsconfig#moduleResolution

### 🙁 Actual behavior
typescript compilation error
```
> tsc
tsconfig.json:6:15 - error TS4124: Compiler option 'module' of value 'nodenext' is unstable. Use nightly TypeScript to silence this error. Try updating with 'npm install -D typescript@next'.

6     "module": "nodenext",
                ~~~~~~~~~~


Found 1 error.
```

### 🙂 Expected behavior

Typescript compilation is happy

**Comment by MartinJohns** [comment]
This is intentional, and the compiler error tells you this. See #46454 for more information. `nodenext` is only supported when using a nightly version, and `4.5.4` is not a nightly version.

**Comment by jmclean-starburst** [comment]
@MartinJohns thanks for the pro-tip; I had seen that issue but saw it was from 2 months ago and wasnt sure if it was still relavent.

FWIW - the VS Code IDE still complains, even with the nightly version
![image](https://user-images.githubusercontent.com/72760973/148094516-6dbd5fae-1365-4566-adbc-869c2ffc62d3.png)

**Comment by MartinJohns** [comment]
By default VS Code is using whatever TypeScript version it is shipped with, **not** your local TypeScript version. You can explicitly change this.

![image](https://user-images.githubusercontent.com/5269069/148096452-b0e7350a-fbb2-4f26-aae7-0be75c03eab4.png)
![image](https://user-images.githubusercontent.com/5269069/148096479-ef53cf99-9210-40ef-baa6-9797f6576a9a.png)

**Comment by DanielRosenwasser** [comment]
Thanks for helping out @MartinJohns!
