### ISSUE TITLE
Rest parameter must be of an array type (ts230) after inferring a tuple.

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#47325]
# Bug Report

### 🔎 Search Terms

ts2370 infer 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `infer`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAYg9nAPAFQHxQLxWVCAPYCAOwBMBnKM4AJwEsiBzKAfgCgoOoBtPKALihEArgFsARhGoBdfu049+g0ROkBuVq3xg41YFFCQoAIQCG1FOizwkaXAWLko9AGaSoAeRYfFRCADdJdVZnISIAY2BaOCIoMJMAG3iUO0JSCio6RlQACgA6fOoIKgFTczQASigAbw0AX1YgA)

### 💻 Code

```ts
type Foo<T> = T extends string ?
    [x : number] :
    [x : number];

export type Bar<T> = Foo<T> extends infer O ? O : never;

function call<T extends string>(...rest: Bar<T>) {
//                              ^^^^^^^^^^^^^^^----- TS2370 Rest parameter must be of an array type
}
```

### 🙁 Actual behavior

TS2370, even though `Bar<T>` is always a tuple.

### 🙂 Expected behavior

No error.

**Comment by jespertheend** [comment]
Hmm I have found a workaround, which is to infer from inside the tuple and then return a forced tuple:
```ts
type Bar<T> = Foo<T> extends [...args: infer O] ? [...args: O] : never;
```
([playground](https://www.typescriptlang.org/play?ts=4.5.4&ssl=5&ssc=1&pln=7&pc=1#code/C4TwDgpgBAYg9nAPAFQHxQLxWVCAPYCAOwBMBnKM4AJwEsiBzKAfgCgoOoBtPKALihEArgFsARhGoBdfu049+g0ROkBuVq3xg41YFFCQoAIQCG1FOizwkaXAWLluAOhdmGZAfQBmkqAHkZZmdXancBAMUiCAA3SXVWLyEiAGNgWjgiKGSTABsclDtCUgoqOkZUAAoXJ2oIKgFTczQASigAbw0AX1YgA))

So this might be working as intended then, not sure.

**Comment by RyanCavanaugh** [comment]
In general we don't have constructs probe both ends of conditional types to see if something is true for both of them, since what typically follows is not something we can keep the conditionalization of.
