### ISSUE TITLE
Using tsc creating .d.ts, diffenence behaviors between command or npm run 

### ISSUE THREAD

**Issue by wvq** [microsoft/TypeScript#47323]
# Bug Report

What's the difference between command line tsc ..., or define tsc script and npm run ...

the src directory has two file:
src/index.js
src/test/test.js

Directly use command (correct way):
```bash
tsc src/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir types
# or
npx tsc src/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir types

# output 
# types/index.d.ts
# types/test/test.d.ts

```

Define in package.json and using npm run build (wrong way):

package.json
```json
{
  "scripts": {
    "build": "tsc ./src/**/*.js --declaration --allowJs --emitDeclarationOnly --outDir types"
  },
}
```

```bash
npm run build
# output
# types/test/test.d.ts


# any src/*.js will not generated
```

Why?

```
tsc --version # Version 4.5.4
node -v          # v16.6.1
npm -v           # 8.3.0
```

**Comment by MartinJohns** [comment]
Perhaps you should try to execute the same commands in both cases. Regardless, from TypeScripts perspective there is no difference. It might be your shell that interferes.

**Comment by IllusionMH** [comment]
Most likely there is difference in globs expansion where in some cases it's done by tsc but in other it's done by shell.
Try putting them in quotes to prevent expansion by shell

**Comment by RyanCavanaugh** [comment]
I suspect @IllusionMH is correct but anyway we don't control `npx` nor even know that we're being invoked differently
