### ISSUE TITLE
tsc --init should generate default values aligned with the docs

### ISSUE THREAD

**Issue by DavideViolante** [microsoft/TypeScript#47324]
# "Bug" Report
It's more a UX problem.

### 🔎 Search Terms
tsc --init init

### 🕗 Version & Regression Information
4.5.4

- This is the behavior in every version I tried

### 🙁 Actual behavior
`tsc --init` generates:
```js
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true, // This is false by default in the docs
    "forceConsistentCasingInFileNames": true, // This is false by default in the docs
    "strict": true, // This is false by default in the docs
    "skipLibCheck": true // This is false by default in the docs
  }
}

```

### 🙂 Expected behavior
I expected that `tsc --init` would generate tsconfig according to the default options [documented](https://www.typescriptlang.org/tsconfig#esModuleInterop) [in](https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames) [the](https://www.typescriptlang.org/tsconfig#strict) [docs](https://www.typescriptlang.org/tsconfig#skipLibCheck).
1. In particular why esModuleInterop and skipLibCheck are default to true?
2. Why other options are default to false in the docs, when it's _better and safer_ to have them true (eg: see strict)

**Comment by MartinJohns** [comment]
`tsc --init` creates a tsconfig with curated options ([see comment](https://github.com/microsoft/TypeScript/issues/20961#issuecomment-354832904)).

The **default** options listed in the documentation are the default options used by the compiler, and these default options are mainly for **backwards compatibility** (see #37351).

**Comment by DavideViolante** [comment]
Yea not a bug absolutely as I said, but if I need backwards compatibility I would rather _change_ a default option instead of the contrary. If I use tsc init I'm starting a new project (correct?), so why a new project needs backwards compatibility? Just thinking out loud to understand the decision.

**Comment by MartinJohns** [comment]
- The default option for `strict` is `false`, to remain backwards compatible with projects that don't specify an explicit value.
- The documentation shows `false` as the default value, because that's what it is.
- `tsc --init` initializes a configuration with it set to `true`, because that's best practice.

**Comment by RyanCavanaugh** [comment]
⬆ I can't explain it more clearly than that 🙂

**Comment by DavideViolante** [comment]
I'm ok with strict true as default, less with esModuleInterop and skipLibCheck. A better explaination in the docs about the generated tsconfig would be nice imho.
