### ISSUE TITLE
Expanding type predicate for object.

### ISSUE THREAD

**Issue by horita-yuya** [microsoft/TypeScript#47320]
# Suggestion

## 🔍 Search Terms

type predicate

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow type predicate in the following case
```typescript
type GeneralUser = {
    name: string
    credential: string | undefined;
    profile: string
}

type SecretUser = {
    name: string;
    credential: string
}

// Allow this one.
function validate(user: GeneralUser): user is SecretUser {
    return user.credential !== undefined
}
// At this time, this will be error.
// `A type predicate's type must be assignable to its parameter's type.`
// `Type 'SecretUser' is not assignable to type 'GeneralUser'.`
```

## 📃 Motivating Example

If `profile` property is disappeared, the following `newValidate` function will be compiled safely.
```typescript
type NewGeneralUser = {
    name: string
    credential: string | undefined;
    // profile: string
}

function newValidate(user: NewGeneralUser): user is SecretUser {
    return user.credential !== undefined
}
```
Why the existence of `profile` property controls the behavior?

```typescript
// `A type predicate's type must be assignable to its parameter's type.`
// `Type 'SecretUser' is not assignable to type 'GeneralUser'.`
```
According to the above error message, a type predicate's type must be assignable to its parameter's type.

Let's think about the following case.

`newGeneralUser` cannot be assigned to `secretUser`, but type predicate can be performed.
```typescript
const newGeneralUser: NewGeneralUser = {
    name: "name",
    credential: "cred",
}

// error
// Type 'NewGeneralUser' is not assignable to type 'SecretUser'.
// Type 'undefined' is not assignable to type 'string'.
const secretUser: SecretUser = newGeneralUser

// But, ok
function newValidate(user: NewGeneralUser): user is SecretUser {
    return user.credential !== undefined
}
```

## 💻 Use Cases

This can be useful in scenarios where you scan all users and extract secret users have credential, filtering non-secret user.

**Comment by RyanCavanaugh** [comment]
Keeping the parameter and predicate type related is generally a useful check.

Without loss of generality, you can write `user is GeneralUser & SecretUser` here.

**Comment by horita-yuya** [comment]
I understand. This is very helpful. Thank you
