### ISSUE TITLE
Object.entires is not strict enough

### ISSUE THREAD

**Issue by Pentadome** [microsoft/TypeScript#47321]
# lib Update Request

## Configuration Check

My compilation *target* is `esnext` and my *lib* is `the default ??`.

## Missing / Incorrect Definition

Object.entries

## Sample Code
Before:
![image](https://user-images.githubusercontent.com/16758470/148232369-5263bb28-b06d-45e6-8914-7178596fd8c6.png)

After:
![image](https://user-images.githubusercontent.com/16758470/148232466-f1e46465-fccc-4121-9910-f28cbfab7ac4.png)

Implementation:
![image](https://user-images.githubusercontent.com/16758470/148232834-95d6f2dc-8241-400a-a220-4f6fede3b280.png)

![image](https://user-images.githubusercontent.com/16758470/148232572-4bb39c62-8025-45c3-94fc-ddd9d9d859b2.png)

**Comment by MartinJohns** [comment]
- You didn't add any example code. Pictures do not qualify as code.
- This is intentional, see #45064 / #38520. Used search terms: `object.entries` (the ones you listed).
