### ISSUE TITLE
typescript infer type of 'this' wrongly 

### ISSUE THREAD

**Issue by mhamri** [microsoft/TypeScript#47333]
# Bug Report

### 🔎 Search Terms
decorator, type inference

### 🕗 Version & Regression Information

all of the versions 

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220105#code/PQKgBApgzgNglgOwC4FoAmcoEMBGMJgACSAngA7QDGATnGatPMsAgPYoQAeZ8lcqWBCTAhgAWABQXMq2pIwiJBGoAzLJQIBlOAFseEAMIALQQHMIAHgAqAPjABvSWDAq41KEmNmIALjA5WVnxBAG4nMDJqCAA3OFYAVygANSwYeN8wKzCJZ0p46ijkFLSMrPDMADE3Dy8Ecz8ACgBKMABeOwCgiFDJAF9JSWlZeRV4hEokOIQwAHkEWvNrNrBBEhsG8MpUmBx1AGtGqF19BYgAfj9tPXxT6xsW9rBo1jg0SRbHHLBKVgQPb-URggaGK6QA0hBhK0wJoSDoAjBmtlcr9-pVqp4THUIBCoTC4QikeEokh8tMGkgsNRzEg-KsADRgPaQvwABWorAochIuIedk+zmcMxwACsIBMAHRoCCuBAQdmc5SkClUmmM5kkRkCwXOKAQWkuMYTKZgBrRVLpD7hHUov5dCUwVimClGTBNEJgYDAIFRMCkChgVgqMAAAyQrqgIYUUDAAHIAIKx602r3fLHmMAeLCkmNBsAAInR7kx3nzyZ1cGDLswAG0izV0zjIQBdNqtaFjaWy4FWr42wXh2v1kvY3Gt6FIajpZH9sC9SAwPUOcs2wdQOtQKrF05j5ZqRcQGf9-p9lPAMAAOVYga52ZNlbAcoA7k8LQRMJmsDoCFhczA0K+JQrs4D4NAAhGuG5bg23i7gAZHBfoRjWWyUECIJvru7bQuaJS9rOgokmSR42ieBE-H88hBBhJTLJBqHoaCTYkM2JE6vRgLAkxWGAdOwHfKi8hHNchiNpcxw3I2dzLNqBGuNuYlIUOm4YjuLb0vxziRDEcSJExfjUUxGmnv2eQFBARRvn4HFoVxmHqZp0bQSO9SmnySnrsOakscZBG9GxgpbDAOz7BKQWImujLCScjbuiuvS+TaNJ+KM4yTL8bnLiZhH6mSHkoZxNHgi2AUJcmvRxV8-l9AMEiUDAv4xvGWXOIQcy3Ag8Twso6wNNFkneE0jyyR5EqRIoDSxggsaMmuEoIO6nrnmu0ZgGMexsE+0w+hA4QVeE0zQgADNk4RtfMUmdd11DrKlxoZX1EmiYNLUDhGY20Mgk0AF4zaN32LV6K0fnm-o-kIe1NOE33LCdtVaZ9SB9Qk1AaH4HifaYjK4ekfhXTgyj4YFqL2o6zpQCjGjY2+lXOCeJ6SBR-xYAAjMsz5gPGRISKz83LAATNkvOHWAguSLzMPQgAzELLN89LssSpLYAy+LcvK6rdUk-gDpOg0rOVUAA)
### 💻 Code

```ts
export interface SimpleChange<T> {
  firstChange: boolean;
  previousValue: T;
  currentValue: T;
  isFirstChange: () => boolean;
}

export function OnChange<T = any>(
  callback: (simpleChange?: SimpleChange<T>) => void
) {
  const cachedValueKey = Symbol();
  const isFirstChangeKey = Symbol();
  return (target: any, key: PropertyKey) => {
    Object.defineProperty(target, key, {
      set: function (value) {
        console.log(this); // <----- here type of `this` is 'A'

        if (this[isFirstChangeKey] === undefined) {
          this[isFirstChangeKey] = true;
        } else {
          this[isFirstChangeKey] = false;
        }
        // No operation if new value is same as old value
        if (!this[isFirstChangeKey] && this[cachedValueKey] === value) {
          return;
        }
        const oldValue = this[cachedValueKey];
        this[cachedValueKey] = value;
        const simpleChange: SimpleChange<T> = {
          firstChange: this[isFirstChangeKey],
          previousValue: oldValue,
          currentValue: this[cachedValueKey],
          isFirstChange: () => this[isFirstChangeKey],
        };
        callback.call(this, simpleChange);
      },
      get: function () {
        return this[cachedValueKey];
      },
    });
  };
}

class A {
  // convert the arrow function to the normal function to make it works
  @OnChange<number>((simpleChange)=> {
    this.print('n', this.n); // <-----  this is unknown here
  })
  n = 0;

  @OnChange<number>(function (simpleChange) {
    this.print('z', this.z); // <----- this is of type any
  })
  z = 0;

  print(source: string, value: number) {
    console.log(source, value);
  }
}

const a1 = new A();
a1.n = 2;
a1.n = 2;
a1.z = 3;
a1.n = 3;
a1.z = 3;
a1.z = 3;
console.log(a1);

```

### 🙁 Actual behavior

the type of `this` should be inferred correctly

this is respect to this https://stackoverflow.com/questions/70595096/tyepscript-set-type-of-this-on-function-decorator

based on the position that the `this` is called on the callback, the `this` should be inferred. 

it's similar to what mentioned in https://github.com/microsoft/TypeScript/issues/37300#issuecomment-787493352
but that thread is closed and have slightly different reasoning, but the issues are related and I expect those also be addressed

also note that the behavior is against the documentation, at least not how the difference between the arrow function and normal function is described. 

moreover, the type of target is known by the typescript. if I call the callback like this the typescript should infer the type correctly 
```ts
callBack.call(target, args);
```

### 🙂 Expected behavior

the type of `this` inferred as part of the decorator signature
arrow functions shouldn't throw an error

**Comment by RyanCavanaugh** [comment]
Please provide a *minimal* example and identify exactly what you believe to be the bug here. There's a lot of extraneous code here and multiple uses of `this` and it's not clear what you're trying to get at.

**Comment by mhamri** [comment]
@RyanCavanaugh I provided the playground, what else do you need? first, in the playground you can see that multiple errors appears and there is nothing wrong with the code the TS is showing error. that's one of the bug. 

second the type of `this` in both decorators are wrong, one is `any` another is `unknown` that is wrong too.
