### ISSUE TITLE
array types don't extend type with wider key type

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#47331]
# Bug Report

### 🔎 Search Terms

array record extends 
### 🕗 Version & Regression Information
4.6.0-dev.20220105
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220105#code/C4TwDgpgBAglC8UBKEDGB7ATgEwDwDsBXAWwCMJMoAfKAZ2EwEt8BzAGikPwGt90B3fAD4AUKEhQAQgmRoseImQocuvAcLHhoAYRmq+ggNoBdEZokAxdOhnSIAD2AR82WrCgB+KA0LQAXFAAZgCGADa00AD0kT4QZuLQksGUiLoOTi5u0l6xUAEh4VExmL7xWlLBAF4yaY7Oru45Jf5BYRFQ0QURQA)

### 💻 Code

```ts
type A = Record<number | string, unknown>
type B = Record<number, unknown>
type C = unknown[]

type Foo = B extends A ? true : false //true

type Bar = C extends B ? true : false //true

type Baz = C extends A ? true : false //false
```

### 🙁 Actual behavior

`C` doesn't extend `A`, even though it extends `B` which extends `A`

### 🙂 Expected behavior
`C` extends `A`

**Comment by RyanCavanaugh** [comment]
Transitivity is not a property of assignability (this fact is easily demonstrated with optional properties, which is one way to reason about how index signatures should work).

**Comment by DetachHead** [comment]
> this fact is easily demonstrated with optional properties
 
 could you show an example of this please

**Comment by RyanCavanaugh** [comment]
`{ a?: number }` -> `{ }` -> `{ a?: string }`

**Comment by DetachHead** [comment]
i see what you mean now. however in that example it's obvious `{ a?: number }` doesn't extend `{ a?: string }`  but i'm having trouble wrapping my head around why `unknown[]` doesn't extend `Record<number | string, unknown>`
