### ISSUE TITLE
createIncrementalProgram is not emitting incrementally 

### ISSUE THREAD

**Issue by AaroncoolPx** [microsoft/TypeScript#47334]
# Bug Report

### 🔎 Search Terms

createIncrementalProgram

### 🕗 Version

Typescript 4.5.4

### 💻 Code

```
import ts = require("typescript");

var options = {
    incremental: true,
    allowJs: true,
    sourceMap: true,
    tsBuildInfoFile: "buildInfoTestOutput",
};
let program = ts.createIncrementalProgram ({
    rootNames: ["./test1.ts"],
    options: options
});
let emitResult = program.emit();
```

### 🙁 Actual behavior
createIncrementalProgram is not emitting incrementally. Files are recompiled even though the source files are not changed. It is behaving same as createProgram.

### 🙂 Expected behavior
Should not recompile when no source files have been changed.

**Comment by DanielRosenwasser** [comment]
This is possibly related to https://github.com/microsoft/TypeScript/issues/47309, and possible mitigations are discussed in https://github.com/microsoft/TypeScript/issues/46677.

**Comment by sheetalkamat** [comment]
I am not sure what issue you are seeing. Can you share exact repro code, (Apart from your code, the source on which you are running this.) i have run this on simple repro and it works as expected.
