### ISSUE TITLE
importing a class from a CJS package inside ESM package complains "not constructable"

### ISSUE THREAD

**Issue by otakustay** [microsoft/TypeScript#47332]
# Bug Report

### 🔎 Search Terms

class, not constructable, has no construct signatures

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it's related to `nodenext` module

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=5&moduleResolution=99&ts=4.6.0-dev.20220105#code/JYWwDg9gTgLgBAUQMoBlgDsYAUA2BXAcwzgDMoIQ4ByAUwGccMYBaAdxoCMwBDAYwGtmYfEXRUA3AChJvCOjrxhhYgF446Gq0SomuZegAUASnFA)

Change `Module` configuration to `NodeNext` to reproduce errors.

### 💻 Code

```ts
import ESLintPlugin from 'eslint-webpack-plugin';

const plugin = new ESLintPlugin();
```

### 🙁 Actual behavior

This simple code inside a `"type": "module"` package with `tsconfig.json` declaraing `"module": "nodenext", "moduleResolution": "nodenext"` can result in type errors:

```
import ESLintPlugin
This expression is not constructable.
  Type 'typeof import("/Users/otakustay/Downloads/s/node_modules/eslint-webpack-plugin/declarations/index")' has no construct signatures.ts(2351)
```

### 🙂 Expected behavior

Since TypeScript already resolves type definition to correct `.d.ts`, and this type definition seems correct:

```ts
export default ESLintWebpackPlugin;
export type Compiler = import('webpack').Compiler;
export type Options = import('./options').Options;
declare class ESLintWebpackPlugin {
  // ...
}
```

This code should compile as expected.

**Comment by weswigham** [comment]
You wanna say `new ESLintPlugin.default()`. This is because your package is esm, while `eslint-webpack-plugin` (as far as we know) is CJS. The thing about node-native esm is that it loads the whole cjs module as the default (unlike in interop land where that's disabled with a runtime flag).

I'm gunna look into seeing if we can issue a better error here that can help indicate what the correct solution is.

**Comment by otakustay** [comment]
Despite the type error, I'm able to import it's `default` properly in Node, I'm wondering why type check is not aligned with runtime behavior:

```
Welcome to Node.js v16.13.0.
Type ".help" for more information.
> const {default: Plugin} = await import('eslint-webpack-plugin')
undefined
> new Plugin()
ESLintWebpackPlugin {
  key: 'ESLintWebpackPlugin',
  options: {
    extensions: 'js',
    emitError: true,
    emitWarning: true,
    failOnError: true
  },
  run: [Function: bound run] AsyncFunction
}
```

How can we fix the type declaration to ensure it works in both ESM and CJS environment?

**Comment by weswigham** [comment]
Does `eslint-webpack-plugin` expose an esm entry point? If so, exposing types for that entry point in its types would be correct.

**Comment by weswigham** [comment]
(Alternatively, the types may just be wrong in saying that it's a default export, and a `export =` may be correct)

**Comment by otakustay** [comment]
I'm still a little confused about this.

According to [Node's official documentation](https://nodejs.org/api/esm.html#interoperability-with-commonjs):

> When importing CommonJS modules, the module.exports object is provided as the default export. Named exports may be available, provided by static analysis as a convenience for better ecosystem compatibility.

It seems only syntax `module.exports = foo` becomes default export when `import`ing it in ESM modules, and static analysis should ensure simple syntax like `exports.foo = foo` or `defineProperty(exports, 'foo', {value: foo})` is transformed into named exports.

So, I think TypeScript (with `nodenext` module resolution) shouldn't simply consider all CommonJS modules as default export, which breaks "static analysis" of Node's native ESM & CJS interoperability.

As the case of `eslint-webpack-plugin`, its source code is like:

```js
"use strict";
// ...
var _default = ESLintWebpackPlugin;
exports.default = _default;
```

Which is perfectly fit for static analysis, and it's type declaration looks like:

```ts
export default ESLintWebpackPlugin;
declare class ESLintWebpackPlugin {
}
```

This declaration also fits its source code and Node's static analysis results.

IMHO, this is a lack of TypeScript supporting for Node's static analysis for CommonJS modules, and could be a feature request for upcoming `nodenext` module resolution.

**Comment by otakustay** [comment]
Sadly TypeScript is unable to export types along with a `export =` statement:

```
error TS2309: An export assignment cannot be used in a module with other exported elements.

59 export = FooBar;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Maybe this (export types along with `export =`) could be a feature request?

**Comment by weswigham** [comment]
`eslint-webpack-plugin`'s actual runtime entrypoint is

```js
"use strict";

const plugin = require('./');

module.exports = plugin.default;
```

It shouldn't declare a default at all - just an `export=`.

**Comment by weswigham** [comment]
The package in question actually already contains a definition for their cjs entrypoint, but their `package.json` doesn't point at it. I put up https://github.com/webpack-contrib/eslint-webpack-plugin/pull/140 on them with a fix, but they've had the issue since they first added [generated types](https://github.com/webpack-contrib/eslint-webpack-plugin/pull/8).

**Comment by SalamandraDevs** [comment]
> > Sadly TypeScript is unable to export types along with a export = statement:
> 
> You just move the other types-to-be-exported into the namespace associated with the `export=`'d thing. Eg,
> 
> ```ts
> class Plugin {
>  // ...
> }
> export = Plugin;
> namespace Plugin {
>   export interface Whatever {} // like this
> }
> ```

Hi, thanks to this response I was able to fix a problem with an old CJS module that I traied to use in a ESM Typscript project. I wondering where is the documentation about class exports with CJS to ESM compatibility.

**Comment by damianobarbati** [comment]
I'm having the same problem: since I moved to `NodeNext` to use the native node flag `--strip-types`, this `not constructable` started popping out everywhere!

```json
{
  "compilerOptions": {
    "moduleResolution": "NodeNext",
    "module": "NodeNext",
    "target": "esnext",
    "lib": ["dom", "dom.iterable", "esnext", "WebWorker"],
    "allowJs": true,
    "allowImportingTsExtensions": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "noImplicitAny": false,
    "noUnusedLocals": false,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "strictPropertyInitialization": false,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": "."
  }
}
```

Is there any workaround?
