### ISSUE TITLE
Should we get rid of the concept of pinned comments 

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#4734]
In the PR #3883, the `removeComments` flag will remove all comments (tripleslash, pinned, and normal) except in the case of copyright header comment prefix with `/!*`. The original functionality of pinned comment is no longer applicable and it may be better than we completely remove the concept of pinned comment entirely. So that `removeComments` will remove all comments except copyright header comments (regardless of the prefix)

**Comment by mhegazy** [comment]
Other tools, mainly minifiers do use this concept. this is the main reason why support it.
