### ISSUE TITLE
Inference fails for generic-typed constructor parameter when no explicit constructor is present

### ISSUE THREAD

**Issue by nex3** [microsoft/TypeScript#47340]
# Bug Report

I'm trying to write a function that takes a (generic) constructor and calls it to instantiate a class. The type inference for such a function normally works fine, but if the constructor is for a generic class it fails *even if the generic parameter has a default*.

### 🔎 Search Terms

generic constructor parameter inference instanceof

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about constructor parameters

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/MYGwhgzhAEBiD28A8BpaBTAHgF3QOwBMYBvAX2gF5oyA+a0gKAYDMBXPYbAS3j2mABO6MLiQAVGgApsATwAO6AFzQ86AO7RJASkp0xW5WOoNop6EOysBfVRtkLtAbgaMGIdNmgRsArngDmlPxCIuiSAMo+fv5ajtAA9PHQABaQ0Pbo0JG+AUzunsyIQYLCuJII8LEJSRDJ8KwgBClgAG6ZGXCISLQANM0wHewA1njwangMQA)

### 💻 Code

```ts
class Foo<K extends {} = {}> {}

function create<T>(type: new () => T): T {
    return new type();
}

let string = create(String); // has type String

let foo = create(Foo); // should have type Foo<{}>, has type unknown
```

### 🙁 Actual behavior

The `foo` variable has type `unknown`.

### 🙂 Expected behavior

I expected the `foo` variable to have type `Foo<{}>`.

**Comment by cijiugechu** [comment]
Probably because the class `Foo` don't have a constructor, `K` didn't be consumed in the class.

**Comment by MartinJohns** [comment]
Use this instead:

```typescript
function create<T extends new () => any>(type: T): InstanceType<T> {
    return new type();
}
```

**Comment by RyanCavanaugh** [comment]
This is a bug; inserting the constructor that's "there" by default
```ts
constructor() {}
```
changes the behavior
