### ISSUE TITLE
Rest parameter type narrows to first rest argument

### ISSUE THREAD

**Issue by icecream17** [microsoft/TypeScript#47353]
# Bug Report

### 🔎 Search Terms

function parameter coerce assume
rest parameter narrow

### Related issues

Possibly related to https://github.com/microsoft/TypeScript/issues/27706
<s>Edit: Definitely related to https://github.com/microsoft/TypeScript/issues/42138, might be a duplicate so maybe this could be closed</s>
*Edit 2: Actually this issue is about the narrowing.* I assumed this would be fixed if `Listener` was of type `(...args: infer) => infer`, but now that I think about it, maybe not.

### 🕗 Version & Regression Information

- This is the behavior in every version in the playground, and I reviewed the enitre FAQ but it doesn't apply

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAMglgZ2BAdhATlAvFAFAOkIEN0BzBALiiJRAEpsA+KANwHs4ATAbgCheAxmxRIoEFqmAAlCKUTB0IbFDQB3KAFkiYADxJ0cFKQA0seagwBtALqNcdfgDMArigHA4wlWw+OQOgBU7cUkqfUMTKEJ8EnIqAJsGAG9eKDSoIRFgMQkUYHgkC3QEZRC8mTl9EHxSCGBcMuAHdKg4RzxGguQ0YqgAQiwcV04IR0MITmTUlvTHNkxcTNEAG3MeqDZ2zrWMBCmZg6hVwp6CYjI96YOAXyuoW9veFzcPLwgADyIAWzBliAAJGicP7oRZsEZUFDOL4AIwwpnQEAQzmWwDCCgi+3SbTwQhG2EGUAATAAGEkMJZsP74ZZsUi4RHI1EOR4AelZUAAgpxOFAAEQfb6-AFAkF86glGg5SRHHboCi8RoVeSKfAIOq4PljFCIAAWEz5pksgp+f0BKGBGGsDl4KB8bRAmu1eoNplJJNMfICRE4RD5Djtvn8UNhGCgAB8oOEjHYtYYXZxDcSyZ7vb7-bwgA)

### 💻 Code

```ts
type Listener = (...args: any) => void;

const eventRegistry = new Map<string, Listener[]>()

function notify<T>(event: string, ...args: T[]) {
    const eventListeners = eventRegistry.get(event)
    if (eventListeners !== undefined) {
        for (const listener of eventListeners) {
            listener(...args)
        }
    }
}

function exampleHandler(code: number, result: string) {
    if (code === 200) console.log(result)
}

// Add "exampleHandler" as an event listener:
eventRegistry.set("finished", [exampleHandler])

notify("finished", 200, "Tada") // Error: "Tada" is not of type number
notify<number | string>("finished", 200, "Tada") // Works
```

### 🙁 Actual behavior

When calling `notify` with `200, "Tada"` as the `...args: T[]`, `T` is narrowed to `number` instead of `number | string` causing the error

### 🙂 Expected behavior

No error

**Comment by ajafff** [comment]
You actually want this definition:

```ts
function notify<T extends any[]>(event: string, ...args: T) {
```

Quite a while ago there was an issue discussing the difference, but I cannot find it right now.

**Comment by icecream17** [comment]
I guess this issue is resolved - will comment as soon as I find such issue discussing the difference

**Comment by fatcerberus** [comment]
@ajafff @icecream17 The difference is that `<T extends any[]>` is a hint to the compiler to infer a tuple type, which allows the rest arguments to be inferred independently.  With just `<T>` it will infer an array type instead, and for better type safety the compiler avoids inferring array types across inference sites (otherwise you end up with overly wide array types like `Array<string | number | boolean | Foo | Bar | Baz | etc>`).
