### ISSUE TITLE
Two level deep indexed access: read works, write fails

### ISSUE THREAD

**Issue by quixot1c** [microsoft/TypeScript#47352]
# Bug Report

Reading from a two level deep Indexed Access type works, but writing gives "Type cannot be used to index".

### 🔎 Search Terms

- Indexed Access
- Mapped Type

### 🕗 Version & Regression Information

- This changed between versions 3.3.3 and 3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220108&ssl=15&ssc=2&pln=1&pc=1#code/KYOwrgtgBAglDeAoKKoDECWAnAzgFygF4oAiARhIBplUBlYAYwHsQATI0gJhMQF9FEeAJ4AHYFABqAQwA2YYDg7woAbSlQMIWAF0AXAlUAjffiyaA5nqimLUXv2Yh8UAG6z5OfdLkKlvKFKKUiBCANwCAGZgIAx4GCxQeAp4ADwAKlDAAB5JbIowAHwAFFL6aZRQxtZ4ZiDmAJQINCiOzm4+cMTtHmra4aiu7gq9HN3AMOHNUK0EYwBCo0M4vSqGfVAA9BsabNm23j1p2lAA7hh4ABbVteanTFgA1jhTY8tS2qvHXUNzoZvbhAKUDSonEAHIbHUwdNgiAmARDOIwDhgOw8EwdqxsolQVAwQdhkdoag+EA)

### 💻 Code

```ts
enum A {
    First = "1",
    Second = "2"
}

type Values = { [a in A]: { [b: string]: string }}
const values: Values = {} as any;

function test<T extends A>(a: T, b: string) {
    const valueA = values[a];
    values[a] = valueA;

    const valueB = values[a][b]; // indexing Values[T] with string works
    values[a][b] = valueB; // => Type 'string' cannot be used to index type 'Values[T]'    
}
```

### 🙁 Actual behavior

Indexing a type while reading works, while writing fails with the same indexer.

### 🙂 Expected behavior

Indexed reads and writes both work when using the same indexer.

**Comment by jcalz** [comment]
I don't see what this has to do with TS4.6 or the linked PR.  Your code example has the same behavior [in TS4.5](https://www.typescriptlang.org/play?ts=4.5.4#code/KYOwrgtgBAglDeAoKKoDECWAnAzgFygF4oAiARhIBplUBlYAYwHsQATI0gJhMQF9FEeAJ4AHYFABqAQwA2YYDg7woAbSlQMIWAF0AXAlUAjffiyaA5nqimLUXv2Yh8UAG6z5OfdLkKlvKFKKUiBCANwCAGZgIAx4GCxQeAp4ADwAKlDAAB5JbIowAHwAFFL6aZRQxtZ4ZiDmAJQINCiOzm4+cMTtHmra4aiu7gq9HN3AMOHNUK0EYwBCo0M4vSqGfVAA9BsabNm23j1p2lAA7hh4ABbVteanTFgA1jhTY8tS2qvHXUNzoZvbhAKUDSonEAHIbHUwdNgiAmARDOIwDhgOw8EwdqxsolQVAwQdhkdoag+EA) and indeed all the way back to [TS 3.5](https://www.typescriptlang.org/play?ts=3.5.1#code/KYOwrgtgBAglDeAoKKoDECWAnAzgFygF4oAiARhIBplUBlYAYwHsQATI0gJhMQF9FEeAJ4AHYFABqAQwA2YYDg7woAbSlQMIWAF0AXAlUAjffiyaA5nqimLUXv2Yh8UAG6z5OfdLkKlvKFKKUiBCANwCAGZgIAx4GCxQeAp4ADwAKlDAAB5JbIowAHwAFFL6aZRQxtZ4ZiDmAJQINCiOzm4+cMTtHmra4aiu7gq9HN3AMOHNUK0EYwBCo0M4vSqGfVAA9BsabNm23j1p2lAA7hh4ABbVteanTFgA1jhTY8tS2qvHXUNzoZvbhAKUDSonEAHIbHUwdNgiAmARDOIwDhgOw8EwdqxsolQVAwQdhkdoag+EA).  I assume it's a consequence of #30769.

**Comment by quixot1c** [comment]
@jcalz seems you are right. I previously tested with a different return type for each of the Values with

```
interface Lookup {
  [A.First]: number
  [A.Second]: string
}
type Values = { [a in A]: { [b: string]: Lookup[a] }}
```
This is where 4.6 did come in to play. Simplifying the problem further I must have forgotten to check if it persisted in older versions. Will update the issue.

**Comment by quixot1c** [comment]
As @jcalz pointed out it does seem related to [#30769](https://github.com/microsoft/TypeScript/pull/30769). In particular the following:

- Given a type variable T with a constraint C, when an indexed access T[K] occurs on the target side of a type relationship, index signatures in C are now ignored. This is because a type argument for T isn't actually required to have an index signature, it is just required to have properties with matching types.

```ts
function f3<T extends { [key: string]: any }>(obj: T) {
    let foo = obj['foo'];
    let bar = obj['bar'];
    obj['foo'] = 123;  // Error
    obj['bar'] = 'x';  // Error
}
```
If in my case `values[a]` is typed as `Values[T]`, does that mean that it in effect becomes the `T` with constrain `C` that is referred to in the PR?

**Comment by RyanCavanaugh** [comment]
On *read* you're allowed to fall back to the constraint type, but as noted above this isn't allowed during a write

**Comment by quixot1c** [comment]
@RyanCavanaugh I can't say I understand why, that may be way above my pay grade :) But it seems to me
```
const valueB = values[a][b];
values[a][b] = valueB;
```
should never fail given no changes in `a` and `b`.

**Comment by RyanCavanaugh** [comment]
To correctly analyze that, the type of `valueB` would somehow have to encode that it came from the specific indices given by `a` and `b`. The type system is generally designed to track sets of values (types), not specific values or variables.
