### ISSUE TITLE
[tsx] `<T extends U></T>;` is not parsed correctly

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#47355]
# Bug Report

### 🔎 Search Terms

jsx extends ambiguity type parameters

### 🕗 Version & Regression Information

I only tested 4.5.4 and Nighty on the repl

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "JSX and React"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220108#code/PTAEBUAsEsGdQO4HsBOBrWAoAPOU0BbABwBsBTAsgOwBd4BVAPm2HEYG5NMQIZ4ATJGVhUA5DRx4yADxrV+DZqw6YgA)

### 💻 Code

```ts
// This works
<T implements U></T>;

// This doesn't
<T extends U></T>;
```

### 🙁 Actual behavior

The second JSX expression is parsed as a malformed arrow function

### 🙂 Expected behavior

Both are valid JSX elements

**Comment by ozanhonamlioglu** [comment]
@nicolo-ribaudo Can I take this bug?

**Comment by RyanCavanaugh** [comment]
In this you'd need to write `<T U extends>`, etc instead. Otherwise we'd have to do a lookahead of the entire rest of the file.

**Comment by Josh-Cena** [comment]
Seems [Babel handles it correctly](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DwFQBApgHgLhB2ATAzmAqgPmAehBg3AFChgCWAtgA4A2E5CMqmOeRQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.16.9&externalPlugins=&assumptions=%7B%7D) 🤔

**Comment by RyanCavanaugh** [comment]
The Babel behavior is *surprising* to say the least

This is parsed as a `<T>...</T>` JSX element with the content `"(x: T) => ", console.log('hi'), "f(); //"`
```ts
let f = <T extends U>(x: T) => { console.log('hi') }

f();

//</T>
```

This is parsed as a generic arrow function:
```ts
let f = <T extends U>(x: T) => { console.log('hi'); }

f();

//</T>
```

Not sure I would call this "correctly" - it appears to be entirely heuristical

**Comment by Josh-Cena** [comment]
Ah, that's interesting to know😄

**Comment by nicolo-ribaudo** [comment]
Yeah, Babel first tries to parse it as JSX and then falls back to an arrow function.

I reported this "bug" while checking what ne need to do to align to your parser.

**Comment by Josh-Cena** [comment]
FWIW, I actually like Babel's result more. It's better to be parsed as correctly as possible before spitting an error.

**Comment by fatcerberus** [comment]
Downside of the Babel behavior is that it basically requires infinite lookahead.
