### ISSUE TITLE
for.... of.... undefined bug

### ISSUE THREAD

**Issue by ccravens** [microsoft/TypeScript#47360]
# Bug Report
The `for ... of ...` loop results in a run-time error if the object is undefined. This results in run-time errors that seem they may be nearly impossible to debug due to the translation into Javascript. For example the following Typescript:

```typescript
for (const obj of objs) {
}
```

is resulting in the following javascript:
```javascript
for (_l = 0, _m = objs; _l < _m.length; _l++) {
}
```

However if `objs` is undefined, a `Cannot get length of undefined` runtime error occurs, which is difficult to debug due to the fact that the `.length` is put in by the typescript compiler. It seems like typescript should be adding some safety guards to check for undefined before calling the `.length` on it

### 🔎 Search Terms
for of undefined length

### 🕗 Version & Regression Information
Version `4.5.4`

Please keep and fill in the line that best applies:
- I was unable to test this on prior versions because this hasn't caused an issue for me until now.

### ⏯ Playground Link
The playground does not produce the same loop that I'm seeing

https://www.typescriptlang.org/play?#code/GYewTgBAFAxiB2BnALhEAjAVm4auIEoIBvAKAF9SIIg

### 💻 Code

```typescript
for (const container of obj.spec.initContainers) {  // << Runtime Error "TypeError: Cannot read property 'length' of undefined" Here
  // do stuff
}
```

Resulting Javascript:

```javascript
for (_q = 0, _r = obj.spec.initContainers; _q < _r.length; _q++) { // << Runtime Error "TypeError: Cannot read property 'length' of undefined" Here
  // do stuff
}
```

### 🙁 Actual behavior
Because of the call to `.length` this leaves the compiled javascript vulnerable to the reported error. It seems like undefined values should be handled in the compiled javascript rather than the typescript developer having to anticipate for this.

### 🙂 Expected behavior
I'm not sure how to solve this problem it feels like I'm writing typescript code around my for loops to try and account for a potential run-time issue. It feels like the typescript compiler should handle this scenario.

**Comment by MartinJohns** [comment]
This is working as intended. When the type is potentially `undefined` you already get a compilation error, so this case is handled in TypeScript.

Running a for-of loop will cause an error in ES versions that support this feature as well, so handling `undefined` is out-of-scope for TypeScript. The only improvement I could see here is to not have the "read property of undefined" error, but instead throw the same error you would get in modern ES versions ("undefined is not iterable").

**Comment by fatcerberus** [comment]
> The playground does not produce the same loop that I'm seeing

This is because the Playground defaults to target ES2017, where `for...of` is supported natively.  Your own project is clearly targeting ES5 without `downlevelIteration` if it's emitting a length-based loop.  And if you're not getting a type error that the value is possibly `undefined`, then you also might have `strictNullChecks` disabled.  It seems like you might not really understand how tsconfig works?

**Comment by DanielRosenwasser** [comment]
Thanks @MartinJohns, @fatcerberus!
