### ISSUE TITLE
`Module '"x"' has no default export.` even with `esModuleInterop` and/or `allowSyntheticDefaultImports` enabled

### ISSUE THREAD

**Issue by quantumsheep** [microsoft/TypeScript#47367]
# Bug Report

### 🔎 Search Terms

TS1192

### 🕗 Version & Regression Information
Tried on `typescript@next`, `typescript@4` and `typescript@3`.

### ⏯ Playground Link

[Playground link with relevant code](https://codesandbox.io/s/typescript-playground-export-forked-j644f?file=/index.ts)

### 💻 Code

```ts
// a.ts
export function x() {
  return 1;
}
```

```ts
// index.ts
import a from "./a"; // Module '"/x/a"' has no default export.
a.x(); // _a.default is undefined
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

### 🙁 Actual behavior
```
src/a.ts:1:8 - error TS1192: Module '"/x/a"' has no default export.

1 import a from './a';
         ~
```

### 🙂 Expected behavior

Happy compilation.

**Comment by IllusionMH** [comment]
It because `a.ts` only has named export `x` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#syntax

You should either use it directly as `import { x } from './a';` or use [namespace-like import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_an_entire_modules_contents) ``import * as a from './a';``

**Comment by quantumsheep** [comment]
@IllusionMH `allowSyntheticDefaultImports` should allow `import a from './a'` directly instead of `import * as a from './a'`.

**Comment by IllusionMH** [comment]
Isn't it just for CommonJS modules that doesn't have own `modules.exports.default`?

**Comment by quantumsheep** [comment]
If I'm not mistaking, `esModuleInterop` ensure that this is not an issue.

**Comment by RyanCavanaugh** [comment]
The meaning of the `allowSyntheticDefaultImports` flag is used to describe your runtime environment, not change TS's behavior. It's saying "*My module loader* will provide a default export if one does not exist, so please allow me to do that even though it seems like this shouldn't work".

**Comment by xavierchow** [comment]
@quantumsheep  As your `module` in tsconfig is specified as `ESNext`, it's pure ESM world, see: [module-output-format](https://www.typescriptlang.org/docs/handbook/modules/theory.html#the-module-output-format). The `a.ts` doesn't have a `export default` so you can not use it as `import a from "./a";` (which is identical to `import { default as a } from "./a";`
`esModuleInterop` is for interoperability between ESM and CJS, but you don't have commonjs module in your example so it doesn't help with the `default` missing problem.
