### ISSUE TITLE
How to emit type annotation

### ISSUE THREAD

**Issue by robianmcd** [Microsoft/TypeScript#4737]
If I have a typescript file like this:

```
import {Http} from 'http/http';
import {Component} from 'angular2/angular2';

export class Test {
    constructor(http:Http) {
        console.log(http);
    }
}
```

and I compile it like this ` tsc -m commonjs -t es5 --emitDecoratorMetadata --experimentalDecorators test.ts`

I would expect it to output the type annotation for the Http parameter. Angular2 would then be able to use that information to figure out how to inject http. However tsc is just outputting this

```
var Test = (function () {
    function Test(http) {
        console.log(http);
    }
    return Test;
})();
exports.Test = Test;
```

I noticied that If I add an annotation (decorator?) to my class then I get the type annotations in the output. e.g. if I compile this:

```
import {Http} from 'http/http';
import {Component} from 'angular2/angular2';

@Component({})
export class Test {
    constructor(http:Http) {
        console.log(http);
    }
}
```

I get 

```
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
    switch (arguments.length) {
        case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
        case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
        case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
    }
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var http_1 = require('http/http');
var angular2_1 = require('angular2/angular2');
var Test = (function () {
    function Test(http) {
        console.log(http);
    }
    Test = __decorate([
        angular2_1.Component({}), 
        __metadata('design:paramtypes', [(typeof (_a = typeof http_1.Http !== 'undefined' && http_1.Http) === 'function' && _a) || Object])
    ], Test);
    return Test;
    var _a;
})();
exports.Test = Test;
```

and I'm guessing this line adds the type annotation at runtime

```
 __metadata('design:paramtypes', [(typeof (_a = typeof http_1.Http !== 'undefined' && http_1.Http) === 'function' && _a) || Object])
```

Am I doing something wrong? How do I get type annotations at runtime without adding a class annotation?

**Comment by mhegazy** [comment]
as the flag name suggests `emitDecoratorMetadata` the metadata is only emitted for "decorated" entities (classes, methods, properties and parameters).

The rational is emitting all metadata for all types in your program will generate a huge amount of unused type information, where as for decorated declarations, we know we have an audience there (decorator function) that would consume the emitted type information.

**Comment by robianmcd** [comment]
oh ok thanks for the info. Not sure what the best practices are for injecting a service into another service in Angular2 using type annotations but I'll ask over there

**Comment by robianmcd** [comment]
Reopening this as a feature request. It would be great if there was a way to opt into always emitting type annotation metadata. e.g. @robwormald suggested adding a `--alwaysEmitDecoratorMetadata` option here https://github.com/angular/angular/issues/4120

This is causing a great deal of confusion amongst angular2 users (https://github.com/angular/angular/issues/2788) and adding a random decorator to every class is not a very elegant solution.

This wouldn't just be useful for angular2 users. e.g. if you wanted to include something like [Assert.js](http://angular.github.io/assert/) to get runtime type assertions it would be really useful to have TypeScript output the required metadata everywhere.

I'm currently doing this in all of my classes but this is obviously not a great solution.

```
var OutputTypes = () => () => {};

@OutputTypes()
export class MyClass {
    constructor(private http:Http) {

    }
}
```

**Comment by mhegazy** [comment]
types are available for classes, methods, properties and parameters. if we emit these for all declarations in your code, this will generate a huge amount of calls to `__metadata` and that will have a noticeable impact on your application runtime. 

for runtime type assertion purposes, this looks like a unittest scenario, and that seems reasonable to mark them with some decorators to declare the need for meta data.

**Comment by weswigham** [comment]
Y'know, we say it has runtime impact... And it does... But [closurescript](https://github.com/clojure/clojurescript) retains runtime type information, and it enables some interesting patterns. We have the capability to emit the information if consumers desire it, and @robianmcd is right, putting a noop decorator on everything to coax runtime type emit is cumbersome. Unlike closurescript, TS isn't packaged with a stdlib that uses runtime polymorphism, so we dont inherrently feel compelled to emit the information by default, but the capability to do so is there... Maybe we aught to make it more frictionless to do so?

**Comment by robwormald** [comment]
@robian's use case (like mine) is dependency injection in Angular2, rather than test time assertions. Potentially TS could leverage the Reflect API for this sort of thing, which might save a bit of cruft.

**Comment by weswigham** [comment]
The decorator emit does use the reflect API.  `__metadata` desuagars to a call to `Reflect.metadata` if present.

**Comment by robwormald** [comment]
Welllll then ignore my silly previous comment and simply accept my agreement with your last!

**Comment by robianmcd** [comment]
How big of a performance impact would this have? Any Angular 2 app using Types for DI will need to output the types on every class so the way I see it, either the performance impact will be too big and the idea of using types for DI should be abandoned or there should be an easy way to get runtime types on all classes.

**Comment by robianmcd** [comment]
I just thought of something I might have misunderstood. When you add a class decorator will TypeScript output type information for all the types in the class or only the types on the parameters of the constructor function? I've been assuming it would output types for all the types in the class but if it is only for the constructor function then I get how this will cut down on unnecessary metatdata.

**Comment by mhegazy** [comment]
the compiler only emits types for decorated entities. 
if you decorate a class, the class constructor parameter types are emitted. 
if you decorate a method, its parameter types and return type will be emitted. 
if you decorate a property, its type will be emitted. 
if you decorate a parameter of a method/constructor its type will be emitted.

**Comment by robianmcd** [comment]
ok thanks for clearing that up. I understand the reasoning behind this now. It would still be nice if there was an easier way fulfill the DI use case. e.g. something like a `--emitClassMetadata` or `--emitConstructorMetadata` flag. Maybe that would be too specific to the Angular 2 DI use case though...

**Comment by PascalPrecht** [comment]
OTOH, you also don't want to have metadata generated for every class in your code, even in Angular 2 apps. Sometimes you just do `class Car { }` and `new Car()`, bypassing A2 DI.

This again gives me the feeling that an explicit decorator (that unfortunately doesn't du anything) is currently the best way to deal with that. People just have to understand why it is.

**Comment by robianmcd** [comment]
@PascalPrecht I doubt that more than 20% of the classes in an angular 2 project wouldn't need DI. I can't imagine emitting metadata about their constructor parameters could cause a performance bottle neck. So I don't really see the value in having the ability to specify which classes emit metadata about their constructors. Seems like it just adds extra work for the user without any benefit. Either I'm going to be working on a project that doesn't make any use of the metadata or I'll be working on a project where I want it to be output and it might as well be for all classes. And to clarify I'm just talking about the metadata for constructor parameters.

**Comment by emilniklas** [comment]
I'm hesitant to bring this up all over again, but I need to share an idea.

We've seen some really cool new features of the TypeScript type system, like the `never` type, the `this` type, index types with the `keyof` keyword etc.

All of these are necessary to describe the dynamic nature of JavaScript in all its flawed glory. This whole discussion is because we need to generate _a lot of code_ if we don't have a _proof_ that the type emissions will be interesting (i.e. `@decorators`).

It seems to me that there has to be a way to solve this by extending the type system even more:

```typescript
class A {}
class B {}

function x(target: reflective typeof A): void { // Okay, A is reflective
    const dependencies = Reflect.getMetadata('design:paramtypes', target);
    console.log(dependencies);
}
```

```javascript
var A = (function () {
    function A() {
    }
    A = __decorate([
        __metadata('design:paramtypes', [])
    ], A);
    return A;
})();
var B = (function () {
    function B() {
    }
    return B;
})();

function x(target) {
    const dependencies = Reflect.getMetadata('design:paramtypes', target);
    console.log(dependencies);
}
```

---

```typescript
class A {}
class B {}

function x<T>(target: reflective T): void { ... } // Okay, T is reflective

x(new B()); // Okay, B is T, which is reflective --> B is reflective
```

```javascript
var A = (function () {
    function A() {
    }
    return A;
})();
var B = (function () {
    function B() {
    }
    B = __decorate([
        __metadata('design:paramtypes', [])
    ], B);
    return B;
})();

function x(target) { ... }
```

---

```typescript
interface I {}
class A {
  constructor(i: I) {}
}

function x<T>(target: reflective typeof T): void { ... } // Okay, T is reflective

class B {} // implements I <-- opitional with structural subtyping

x<I>(B); // Okay, I is T, which is reflective. I is reflective. B is I, which is reflective. B is reflective.
```

```javascript
const I = Symbol('I'); // Maybe even go so far as to generate JS for reflective types
var A = (function () {
    function A() {
    }
    return A;
})();

function x(target) { ... }

var B = (function () {
    function B() {
    }
    B = __decorate([
        __metadata('design:paramtypes', []),
        __metadata('design:implements', [I]) // We know B is used structurally as I. We may also choose to only emit metadata for nominal subtypes
    ], B);
    return B;
})();

x(B);
```

---

There are probably a lot of hidden issues here that need to be resolved. One might be that the JS may already be generated, and being typed with some `.d.ts`. In that we would have to make the decorations after the fact, perhaps closer to the call site where a type is actually being used reflectively. This may be really uncomfortable and hard, but it might work.

As long as the type system keeps track of what types are ever used in a `reflective` context, I believe this is possible. Maybe the compiler can complain if a `reflective T` is passed an `any`.

The best part is—consumers won't even have to use or even understand the `reflective` keyword.

I don't know. I realize this is really stretching the limits of what TS should be doing, but it's worth discussing I think.
