### ISSUE TITLE
#47341 breaks knockout.mapping tests on Definitely Typed

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#47371]
Knockout.mapping tests rely on the old signature relation rules. The repro is fairly small:

```ts
interface Kow<T> {
    (value: T): void;
}
declare var src: Kow<true> | Kow<false>;
var tgt: Kow<boolean> = src;
```

Expected: src assignable to target.
Actual: Error, type 'boolean' is not assignable to type 'false'.

**Comment by ahejlsberg** [comment]
Hmm, the [repro also fails with TS 4.5.4](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgNIHsDuAeAKgPmQG8AoZc5ACgDc4AbAVwgC5lcBKV69YAEwG4SAXxK8ICOnCgpaUZAGcoCVhhxgoTQgB80WbPDryI+QbORgA5mBV6ARunR0IcEIQC8CpYKA). Am I missing something?

**Comment by ahejlsberg** [comment]
Actually, here's a repro that only fails with #47341.

```ts
interface Kow<T> {
    (): void;
    (value: T): void;
}
declare var src: Kow<true> | Kow<false>;
var tgt: Kow<boolean> = src;
```

But really, that ought to fail, it just happened not to previously because we cross-related the signatures. I mean, `src` might reference a `Kow<true>` which shouldn't be callable with a `boolean`.

**Comment by ahejlsberg** [comment]
And, just to add to the bizarreness of our current behavior, we error if the type is written as an aliased type instead of an interface:

```ts
type Kow<T> = {
    (): void;
    (value: T): void;
}
```

The two obviously should behave the same.

**Comment by sandersn** [comment]
So it sounds like `main` is in a better state than 4.5.4, right? If that's the case then this issue should be closed.

**Comment by ahejlsberg** [comment]
Yes, I'd say `main` has better and more consistent behavior.
