### ISSUE TITLE
Typescript is unable to infer correctly parameter types of a function with a default generic value, but can infer the return type

### ISSUE THREAD

**Issue by HommeSauvage** [microsoft/TypeScript#47378]
# Bug Report

I have a function that takes a map that depends on a generic, that generic is defined by the second argument and there's a default when none is provided. When the second argument is provided, the function behaves well, however, when it's not provided, typescript can infer the return type of the function defined in the map, but not the parameters.

### 🔎 Search Terms

infer parameter generic
generic not using default value

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about generics and inference

### ⏯ Playground Link

[Playground Link with relevant code and docs about what I'm trying to achieve](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220110#code/PQKhFgCgAIWgVAFgUwM7OgQwE4YCYCWAZkcrgHYAu0A1geXqtAPZHSKYMA2GRAruQDGlAs3JM8yAA7IG9AOYty0SimgAiSgE8Z66EQLIueKLGBRtM6AAlOeHtng6MAXmgBvUyucAuaAHJMfy8ObjI-AApMP1RKbAUASmgXAD5ocj4AWwAjMmgoAF9oAB8PL0tkP39s4Jh2OwdI6Ohs5mYeTiTU6Fj48nlCkrK6iqrBWuh6sOwmv2ZsgCtkYQAaFr9W9uRO5LT5peFCqChQCBg4AFEADzjMYSwemUFiAkEp+zIAOmgAeSkRMSoADa-gq-gAutBBJwWhgBJIDORkHg1qhmNAAO5w9DQAAiyCImD4XEofwB4hBYMhmCYmH0mC4XGydxophA5kgFRsDTIAEFBIJmNhCP14MwnDIADw-aDIG6yRi-f6icTJPEEokkskq1BpNw-SnOCGy+UMJjwgn0ZHQAD8+Tq11uwkltmmEuQa3c3hkfnxhOJpOVgMNMmNBTSfi8juwd0oLp5jmcnu9lV+IeQYZSx0gpzZ0F53OmUJhyAIqjyuRUagRmuo-CE5KwAqFIsUlHR5eg8lkZAZLCDqtYVYwUmwzEEaFQro+2FQefrwhVayFLAAbmR4pIq8wccwB0xslpHstiFoFMPCzP3dBMpw+AyuFo2RyudOHNKTZQFUxtYC1X7a1-cQ9UvBxr1KN8+WbYUFDFd1pRSEFQhnCFsxOMA8yAph21haA+HQPBMTLRBoFHcdJ0g2csCYdBBQYLBsHkLJZEoZ8oHoL9sEJCclXJJhPBGZwbSqIIhmqfwxPGI5IHQs5YGgABJZRoRxch0T3Pj6nXWFZFImkCLWfCMFUAgmA4shuOQNjIHMri7gwACAywz9v14nVhkmUYAiCaTZLzSjaGQLQ53OF9nGgABpIKmDcfwrgk0p-C0BKAgAL1qPzzgQNRbykFg2GQhxsPRSsEStExQoscLKIAWUwKQPzlL8zTcv83EcrV9xAgTJiBTJkFUZhCPoSLovBYTQLIBDfMgOjYlIscJ1QKcExi6BGtNRVnPajUnK6iJED8Wr6oQ5cJp+Lo0h66BgGAaBPgerw5q2T4uGYeQDoSJ7ARet6PuYL7IAKbMyKWlbplQCJrquJpLo8e1JkmZ6eFe96IgqIc6RcbGAn2ZZKH8JJbpUbA+AwOwEAAZS7MnlrQLB-Gw8LBWwXBhEfLxJlwSg+GwZQAAZOYKFYvC0PwvS8-xxjWQrwmgKI1myOGvU5qEfpRv70ecTHkhx-w8eEQmbruuIyawej4GppjJ3poImasFm2coDm6iR9XkFRj6MbYbJddizYOnII3idNqzXegbneeUdxgbqIphcKZNJdEgpAagUGKNWqGvBh+XMGV43oAABRwTB+s47yJIITIpC4V4y0fepaWUQJyGSlNPlV5GPc172Hmx2KDYJomTdJjAACEAFV4Cp4sg+oa3loZ+3yfowUa64TB6CYDFiIvDchWzRHC6Uzi0BEfpG9kZg+HkRA1kttWN631VMFaPhqE7SO+ZTdJmGoXI551AZByGQdQawMSIFeCRUyXY2iEQplAqgIVj4hw4NQR+NA1IYmwmoeId86wCEXGIFQ6JBCIDaDiIgY5MiTUTFYbIH9oBljnqCGmk4LxSFLuXPIFQvCx1TkAA)
### 💻 Code

This is the short version of the code, the playground has a better more elaborate code of what I'm trying to achieve.

```ts
type HandlerType = {
  type: 'a'
  handler: (a: string) => number 
} | {
  type: 'b'
  handler: (a: boolean) => string
}

type Keys = HandlerType['type']
type Handler<O extends Keys> = HandlerType | Extract<HandlerType, { type: O }>['handler']

type HandlerMap<O extends Keys> = {
  [method in string]?: Handler<O>
}

const processHandlers = <K extends Keys = 'a'>(h: HandlerMap<K>, o?: { type: K }) => {}

processHandlers({
  x: (a) => { // Parameter 'a' implicitly has an 'any' type.
    console.log(typeof a === 'object') // true BUT TS can't guess a's type and complains with the error

    // Interestingly enough, TS complains about the return type not being "number", which is good and hints
    // that TS knows the right function to choose from HandlerType but it can't guess the parameter type
  }
})
```

### 🙁 Actual behavior

The compiler guesses correctly that the first function `x` inside `processHandlers` must return a `number`, but it fails to infer the type of the parameter `a`.

This wouldn't happen if you pass `{ type: 'a' }` as the second parameter of `processHandlers`.

### 🙂 Expected behavior

The compiler should know both the return type of the function AND the type of parameter `a`.

**Comment by whzx5byb** [comment]
@RyanCavanaugh That's not true. The issue is unrelated to the second argument, and TS should still give an inference because we provide a default generic value. 

Let's see [a simple repo](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220110#code/C4TwDgpgBA0hIGcoF4oHIBmB7LaoB90AjAQwCc0BYAKBoHo6oAVACwgWgHMIA7CMgJYBjKKEhIELLAFcANgBMoRaBACO0gQDcSs3sAB0NMdADiARgA8TKBAAewXvKRxEAPhRQAFOU4AuZgCUKO6aWALyANxG4KYATFY29o7O8AjuqN5kflAA3pg4aP75uAA0xOSF5RQAvgDaTAC6QcghYZHRkFAmAMwJdg48TrCp6bk0UOjYuP6Z2cVoza3hZeNVlbNFpBSLUKHLNHWNUbTU8hBCsuTQGNI8QsACWDxQAGI8ltb9ycOIHvOuniERH85isrgC-j27VO50uZGut3uj2eb3inySgxSv1Q-0BwK6aPBkLaxzOFyuUBudweT1ePF66IGQxcSBxUzQAKBIIZRN2JJoNDeZlmwVy1SCDCgAHkYPooECoAIkKCAERTFWuMokQZQHyKpBqnAqwU8WIilpiiWMGVyhVKgkWQ1YDVanV6+1O43UN7dc3uHLiqCSl4kAS6eS2oj6xU8DD8CCKEgGjaTAo7KEq+VYMjw+6yEBlIjSYBQADuLBAuqy0Z4WGAAH4gA):
```ts
type Keys = 'foo' | 'bar'

// These generic types should be equivalent.
type G1<T extends Keys> = (arg: T) => void;
type G2<T extends Keys> = (arg: {'foo': 'foo', 'bar': 'bar'}[T]) => void;
type G3<T extends Keys> = {
  'foo': (arg: 'foo') => void, 
  'bar': (arg: 'bar') => void,
}[T];

declare function Fn1<T extends Keys = 'foo'>(cb: G1<T>): void;
declare function Fn2<T extends Keys = 'foo'>(cb: G2<T>): void;
declare function Fn3<T extends Keys = 'foo'>(cb: G3<T>): void;

Fn1(arg => {}) // OK. cb is G1<"foo">, and arg is "foo"
Fn2(arg => {}) // OK. cb is G2<"foo">, and arg is "foo"
Fn3(arg => {}) // Failed. cb is infered as "(arg: 'foo') => void" correctly, but why arg is not?
```

**Comment by RyanCavanaugh** [comment]
Being contextually typed by a function type is different from being contextually typed by a lookup type. Any number of different programs will have different behavior; this is not a bug.

**Comment by dmitrysteblyuk** [comment]
Apologies if this was already discussed, but I also have an issue with generic type default values being overriden by the expected return type. And I feel like TypeScript is missing some crucial component when it comes to generic defaults. Consider this simple example:

```typescript
enum Type { Default, Custom }
interface Instance<T extends Type> {
  type: T;
}
function create<T extends Type = Type.Default>(type = Type.Default as T): Instance<T> {
  return { type };
}
const instance1 = create(); // ✅ Instance<Type.Default>
let instance2 = create(Type.Custom); // ✅ Instance<Type.Custom>
// @ts-expect-error
instance2 = instance1; // ✅ Type 'Instance<Type.Default>' is not assignable to type 'Instance<Type.Custom>'
const instance3: Instance<Type.Custom> = create(); // ❌ no error, but 'Instance<Type.Default>' is being assigned to type 'Instance<Type.Custom>'
instance2 = create(); // ❌ also no error, same
instance3;
```

One of the ways to fix this is to use a hack:
```typescript
type PreventGenericDefaultOverride<T> = [T][T extends unknown ? 0 : never];
// this `create()` will not infer the expected return type
function create<T extends Type = Type.Default>(type = Type.Default as T): Instance<PreventGenericDefaultOverride<T>> {
  return { type };
}
```
The problem with this is that TS compiler can become smarter and it'll stop working.

Another way is to create multiple declarations:
```typescript
function create(type?: undefined): Instance<Type.Default>;
function create<T extends Type>(type: T): Instance<T>;
function create<T extends Type = Type.Default>(type = Type.Default as T): Instance<T> {
  return { type };
}
```
The problem with this approach is that if you have multiple generics with default values the number of declarations will be a power of 2 - that is for, say, 4 default generics you'll need 16 declarations.
