### ISSUE TITLE
Enable TS Server plugins on web 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#47376]
For microsoft/vscode#140455

A few key VS Code extensions — such as IntelliCode — are powered by TS Server plugins. Currently we don't support loading these plugins at all on web versions of TypeScript

This feature request tracks enabling plugins from extensions on vscode.dev and GitHub.dev. We don't plan to support plugins from the workspace since these require running npm install

**Comment by mjbvz** [comment]
At the moment VS Code doesn't even try to initialize plugins with the server. However once I remove this check on the VS Code side, the code starts failing at `require` not being implemented:

https://github.com/microsoft/TypeScript/blob/c0796c1dfb62198976474c09350e98a1227d17fb/src/webServer/webServer.ts#L139

**Comment by mjbvz** [comment]
I wonder if we need a browser version of these plugins too, similar to what VS Code does for extensions in browsers

- We wouldn't try executing code the relies on node
- Authors could easily vary their implementation between node and browser 
- We could require the plugin be compiled to a single file, just like we do for vscode extensions in browsers

**Comment by mjbvz** [comment]
I've cleaned up my prototype in #47377 quite a bit. Noteworthy changes:

- Plugins are now only loaded if they have a `browser` field in their `package.json`
- Plugins are loaded using `import(...)` in web
- Plugins on web must be compiled to a module that can be imported

I think web enabled plugins are good opportunity to move plugins to adopt modern JS practices. Trying to load plugins synchronously on web is also very ugly as my original prototype showed

**Comment by leti367** [comment]
Thanks all for the help. @rbuckton Since this change is already merged, do you have any idea when would this be available?

**Comment by RyanCavanaugh** [comment]
PRs merged today will be in the nightly build starting immediately the following day, and also in 4.8 Beta (plus any subsequent release)
