### ISSUE TITLE
Destructuring of `unknown` catch variable is not an error

### ISSUE THREAD

**Issue by frigus02** [microsoft/TypeScript#47383]
# Bug Report

### 🔎 Search Terms

catch, destructure, destructuring, useUnknownInCatchVariables

### 🕗 Version & Regression Information

- This is the behavior in every version I tried: v4.0.5, v4.5.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/DYUwLgBAhgXBCuA7A1og9gd0QbgFCkgG8QAnEtEgXwgF5o9cAzJAYzAEs1EIAjKEgBSFGaNJThJUmRAEoIhSrlxgSAT3m5qLKGBYALCENLkqElOixzCmoA)

### 💻 Code

```ts
let a: unknown;
let {foo} = a;
//   ^^^ Property 'foo' does not exist on type 'unknown'.(2339)

function bar({foo}: unknown) {}
//            ^^^ Property 'foo' does not exist on type 'unknown'.(2339)

try {
} catch ({foo}: unknown) {
  // foo is type any
  // with useUnknownInCatchVariables foo is type unknown
}
```

### 🙁 Actual behavior

Destructuring `unknown` is an error, but destructuring a catch variable, which is of type `unknown` is not an error.

### 🙂 Expected behavior

I would expect destructuring of a catch variable of type `unknown` to produce an error.

**Comment by lvelden** [comment]
If the type annotation is `any`, the property type seems also wrong with `--useUnknownInCatchVariables`:

```typescript
try {
} catch ({foo}: any) {
  // foo is type any
  // with useUnknownInCatchVariables foo is type unknown
}
```

[[Playground link](https://www.typescriptlang.org/play?useUnknownInCatchVariables=true#code/C4JwngBA3gUAvhAxgQ2IgFhAFFAZge3zgC4JkA7MASmnhiA)]

### Expected behavior
Property type of destructured `any` type is also `any`.
