### ISSUE TITLE
Generic mapped type does not satisfy the constraint

### ISSUE THREAD

**Issue by akwodkiewicz** [microsoft/TypeScript#47385]
# Bug Report

TS does not seem to understand that a mapped type contains only a specific subset of properties (thus satisfying a particular constraint) when used as a generic. It's hard for me to precisely describe the error, but the code example should be sufficient. The error was introduced in 4.5.

### 🔎 Search Terms

- not assignable
- index type
- 4.5

### 🕗 Version & Regression Information

- This changed between versions 4.4 and 4.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/IYIwzgLgTsDGEAJYBthjAgogOwgSwgE8EBvAKAUoTwBMBCALgWwFcBbEAUygG4yBfMmRRoMAZWDYaAdzywAFgk4APCJykYc+IqQpU82AOZRONPOohhGCAJJGTZiwG0Aun0HDU6W-dPncSqrqNJq4BMTkVMzAbJzWkFAGhnxRhOxshNic6NasHNzuQkQADpxYYUQAClAA9qVQRAA8ACqBahrl2oQAfAgAvAgASpwAjix4Do2RVE4A0tTYCADWnIQ1AGYIzS5MzXMubcEYABRa4QgAPp3hrpcILFKc6wamAJQIAPwI80xZAG7cATdJwrNabbZ8MglMpiGqxACqYCeLGQAHF1Nw5M1CKUWocOmcdFdCYRXL0Bs1IesHvA8DVFmpII1MPiQtciAAaBDVOqs0JdHn1JqYbrdY56SiMiCVYAwNhMWEIpHUtEYxKwbG4zBOQUubocsivHhAA)

### 💻 Code

```ts
abstract class Entity {
    id!: number;
}

class Sandwich extends Entity {
    ingredients!: Ingredient[];
}

class Ingredient extends Entity {
    name!: string;
    yummyness!: number;
}

type EntityProperty<T extends Entity> = Required<{
    [K in keyof T]: T[K] extends (Entity | Entity[] | undefined) ? K : never
}>[keyof T];

type SomeUsefulGenericType<T extends Entity | Entity[]> = T;

function test<E extends Entity, Prop extends EntityProperty<E>>(
    testParam: SomeUsefulGenericType<E[Prop]>,
//                                   ^^^^^^^ ERROR
);
```

### 🙁 Actual behavior

Following error:
```
Type 'E[Prop]' does not satisfy the constraint 'Entity | Entity[]'.
  Type 'E[EntityProperty<E>]' is not assignable to type 'Entity | Entity[]'.
    Type 'E[E[keyof E] extends Entity | Entity[] | undefined ? keyof E : never]' is not assignable to type 'Entity | Entity[]'.
      Type 'E[keyof E]' is not assignable to type 'Entity | Entity[]'.
        Type 'E[string] | E[number] | E[symbol]' is not assignable to type 'Entity | Entity[]'.
          Type 'E[string]' is not assignable to type 'Entity | Entity[]'.
            Type 'E[string]' is not assignable to type 'Entity[]'.
              Type 'E[keyof E]' is not assignable to type 'Entity[]'.
                Type 'E[E[keyof E] extends Entity | Entity[] | undefined ? keyof E : never]' is not assignable to type 'Entity[]'.
                  Type 'E[EntityProperty<E>]' is not assignable to type 'Entity[]'.
                    Type 'E[Prop]' is not assignable to type 'Entity[]'.
                      Type 'E[EntityProperty<E>]' is not assignable to type 'Entity[]'.
                        Type 'E[E[keyof E] extends Entity | Entity[] | undefined ? keyof E : never]' is not assignable to type 'Entity[]'.
                          Type 'E[keyof E]' is not assignable to type 'Entity[]'.
                            Type 'E[string] | E[number] | E[symbol]' is not assignable to type 'Entity[]'.
                              Type 'E[string]' is not assignable to type 'Entity[]'.
```                              

### 🙂 Expected behavior

No error (like in TS 4.4)

**Comment by RyanCavanaugh** [comment]
This appears to be https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#restrictions-on-assignability-to-conditional-types

**Comment by ahejlsberg** [comment]
Best I can tell it's not related to assignability to conditional types. We simply don't check this correctly in 4.4. For example, changing `SomeUsefulGenericType` to

```ts
type SomeUsefulGenericType<T extends { spoiler: number }> = T;
```

the example _still_ compiles when clearly it shouldn't. In 4.4, `E[Prop]` is assignable to _anything_, and that appears to have been fixed in 4.5. The error we now report is what I would have expected in the first place. Even though the `EntityProperty` type returns names of properties whose type is `Entity | Entity[]`, this knowledge isn't propagated in any way by the type checker, and from its perspective, `E[Prop]` could select any property of `E`. Thus, `E[Prop]` shouldn't be assignable to `Entity | Entity[]`.

**Comment by akwodkiewicz** [comment]
>In 4.4, `E[Prop]` is assignable to _anything_ (...)

Oh, I did not realize that before, thank you.

>Even though the `EntityProperty` type returns names of properties whose type is `Entity | Entity[]`, **this knowledge isn't propagated in any way by the type checker**, and from its perspective,`E[Prop]` could select any property of `E`. Thus, `E[Prop]` shouldn't be assignable to `Entity | Entity[]`.

This is what I suspected, but was hard for me to put in words, due to my lack of knowledge about the type checker internals. Also the fact it's not mentioned in the _Breaking Changes_ section of 4.5 made me question what's the exact reason for this change in behaviour. I am curious, do you consider it a _breaking change_ if it actually fixed some broken behaviour from previous versions?

Does it mean that `...[keyof T]` at the "very end" of `EntityProperty` definition somehow overrides the whole information about the possible members of the type? I see you added the _Working as Intended_ label to the issue, but I just wanted to ask anyway, do you consider propagating such information about the type in next TS versions?

**Comment by akwodkiewicz** [comment]
Are the [_indexed access inference improvements_](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6-beta/#indexed-access-inference-improvements) going to change the behaviour here?
