### ISSUE TITLE
not ignoring node_modules after explicitly setting --skipLibCheck flag and exclude

### ISSUE THREAD

**Issue by CxGarcia** [microsoft/TypeScript#47387]
TS version: 4.5.2
expected behavior: to ignore node_modules
actual behavior: doesn't ignore node modules

command: 
`$ tsc --skipLibCheck && vite build`

log: 
```
node_modules/react-dropzone-uploader/dist/Dropzone.tsx:504:44 - error TS2571: Object is of type 'unknown'.

504       console.error('Error Upload Params', e.stack)
                                               ~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

img log:
<img width="771" alt="Screen Shot 2022-01-11 at 16 35 47" src="https://user-images.githubusercontent.com/57994942/148974165-0ca9c8de-8878-42d8-acf3-5349118d2be3.png">

tsconfig: 
```{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "module": "ESNext",
    "moduleResolution": "Node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "downlevelIteration": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "ES2015",
    "baseUrl": "./src",
    "paths": {
      "@components/*": ["components/*"],
      "@components": ["components"],
      "@views": ["views"],
      "@views/*": ["views/*"],
      "@guards/*": ["guards/*"],
      "@guards": ["guards"],
      "@api-client/*": ["api-client/*"],
      "@api-client": ["api-client"],
      "@store": ["store"],
      "@store/*": ["store/*"],
      "@helpers": ["helpers"],
      "@helpers/*": ["helpers/*"],
      "@snippets/*": ["_snippets/*"],
      "@services/*": ["services/*"],
      "@services": ["services"],
      "@customTypes/*": ["types/*"],
      "@customTypes": ["types"],
      "@hooks/*": ["hooks/*"],
      "@hooks": ["hooks"],
      "@assets": ["assets"],
      "@assets/*": ["assets/*"],
      "@router": ["Router"],
      "@router/*": ["Router/*"]
    }
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
```

**Comment by MartinJohns** [comment]
You're most likely including the source file in your project. `exclude` only acts as a filter on top of `include`, but imported files are always part of the compilation. You can use the [--explainFiles](https://www.typescriptlang.org/tsconfig/#explainFiles) compiler option to figure out why the file was included in the compilation.

**Comment by RyanCavanaugh** [comment]
`skipLibCheck` means "Don't check `.d.ts` files any more than you have to". It doesn't mean "ignore .tsx files in node_modules".

**Comment by beinghaziq** [comment]
Hi, @CxGarcia have you resolved this issue?? I'm getting the same issue and I haven't reached any solution yet.

**Comment by CxGarcia** [comment]
hey @beinghaziq. yeah I decided to change libs and am now using `react-dropzone` since `react-dropzone-uploader` seems abandoned for over 2 years now

**Comment by beinghaziq** [comment]
Thank you very much 🙏

**Comment by felskov** [comment]
> `skipLibCheck` means "Don't check `.d.ts` files any more than you have to". It doesn't mean "ignore .tsx files in node_modules".

Why not tho? I have a project using `strict: true`, but it breaks on some dependencies that have been developed without this same flag. These dependencies will type-check and build on their own without a problem, but my project fails on them because `strict: true` is enforced for their files as well.

I would very much like to use `strict: true` on my code only, and ignore checking of node_modules all together, as there is nothing I can do to fix errors nested in those files anyway - save perhaps reporting the issue, and hoping the authors will adjust their config and publish a new, complaint version.

Is there nothing I can do but to accept using a configuration that's compliant with my dependencies, and therefore restricting my ability to use strict rules in TypeScript? That seems like a design flaw in my eyes. Do you have other reasons for imposing this limitation? :)

**Comment by MartinJohns** [comment]
@felskov The correct approach for the package owner would be to release JavaScript and declaration files, not TypeScript files. See this comment: https://github.com/microsoft/TypeScript/issues/44205#issuecomment-849895090

**Comment by felskov** [comment]
@MartinJohns Thanks for your feedback! :)

I agree, that the perfect solution in that particular case would be publishing with compiled JS files - unfortunately we don't always control third party packages. We can ask the authors nicely to compile TS to JS before publishing, but in the end we have no control over whether or not that happens. That can leave us with the choice of abandoning that dependency and either finding a new one or writing whatever it does ourselves -- or making our TypeScript config less strict to enable checking the dependency without errors, but negatively impacting type checks on our on code.

Another real-life example I've encountered with this, is within mono repos where you want to incrementally adapt stricter configurations of TypeScript. You setup each package with it's own tsconfig.json file, so configurations can be changed on a per-package basis. Everything works great, until the packages start depending on each other. You now risk having a scenario, where team A want to upgrade the tsconfig.json of package A with new stricter options. Unfortunately package A depends on package B, which is not yet compliant with these options. This leaves team A with the only option of requesting team B to adjust package B accordingly, and wait for them to finish doing so. Sometimes these dependencies cascade in very big repos, making it hard to update tsconfig.json without doing a full upgrade across the entire repo.

I understand from the comment you linked that the main concern is emitted files. In our case (and I think this reflects the reality in many new projects), TypeScript is not used as a compiler, only a type checker (ie. we always use --noEmit, and actual output is created by esbuild or similar).

To work around the issue on our end, I've created a tiny wrapper script to mimic running `tsc --incremental --noEmit` (it will read your tsconfig.json, but bear in mind that it doesn't currently accept command line arguments). Before outputting the result, it will filter errors in all files outside of the project root and/or within a node_modules folder. This solves our specific issues as described above.

The script is available here:
https://gist.github.com/felskov/84fa477e87fb18f3ff7bee4ee2ce1c57

Do you have any thoughts about using such a script or any feedback to the implementation?

**Comment by danielschnetler** [comment]
I was facing the issue with node_modules not being excluded after upgrading node to 18.4.0 LTS  
Turned out ``` tsc -v ``` was still showing the previous version.  
Just closing the terminal and reopening it resolved the issue for me!

**Comment by RobRendell** [comment]
I'm having similar issues, where I have stricter options set in my tsconfig.json (`noFallthroughCasesInSwitch` and `noUncheckedIndexedAccess`) than the dependency does in its.  However, what's interesting is that the dependency (`@streamparser/json`) actually *does* export javascript and .d.ts files in its dist folder, and its `package.json` references those files:
```
  "main": "./dist/mjs/index.js",
  "module": "./dist/mjs/index.js",
  "browser": "./dist/mjs/index.js",
  "types": "./dist/mjs/index.d.ts",
```

However, because it also bundles its `src` folder with .ts files inside, Typescript is trying to redundantly typecheck those files anyway, forcing me to remove my stricter tsconfig options if I want to build.

**Comment by robert-melonn** [comment]
> [@MartinJohns](https://github.com/MartinJohns) Thanks for your feedback! :)
> 
> I agree, that the perfect solution in that particular case would be publishing with compiled JS files - unfortunately we don't always control third party packages. We can ask the authors nicely to compile TS to JS before publishing, but in the end we have no control over whether or not that happens. That can leave us with the choice of abandoning that dependency and either finding a new one or writing whatever it does ourselves -- or making our TypeScript config less strict to enable checking the dependency without errors, but negatively impacting type checks on our on code.
> 
> Another real-life example I've encountered with this, is within mono repos where you want to incrementally adapt stricter configurations of TypeScript. You setup each package with it's own tsconfig.json file, so configurations can be changed on a per-package basis. Everything works great, until the packages start depending on each other. You now risk having a scenario, where team A want to upgrade the tsconfig.json of package A with new stricter options. Unfortunately package A depends on package B, which is not yet compliant with these options. This leaves team A with the only option of requesting team B to adjust package B accordingly, and wait for them to finish doing so. Sometimes these dependencies cascade in very big repos, making it hard to update tsconfig.json without doing a full upgrade across the entire repo.
> 
> I understand from the comment you linked that the main concern is emitted files. In our case (and I think this reflects the reality in many new projects), TypeScript is not used as a compiler, only a type checker (ie. we always use --noEmit, and actual output is created by esbuild or similar).
> 
> To work around the issue on our end, I've created a tiny wrapper script to mimic running `tsc --incremental --noEmit` (it will read your tsconfig.json, but bear in mind that it doesn't currently accept any additional command line arguments). Before outputting the result, it will filter errors in all files outside of the project root and/or within a node_modules folder. This solves our specific issues as described above.
> 
> The script is available here: https://gist.github.com/felskov/84fa477e87fb18f3ff7bee4ee2ce1c57
> 
> If we suppose that `type-check.mjs`, `package.json` and `tsconfig.json` are all located at the root of your project, you would then configure it by adding the following script to `package.json`:
> 
> {
>   "scripts": {
>     "type-check": "./type-check.mjs"
>   }
> }
> And then run the type-check script from anywhere within your project folder:
> 
> npm run type-check
> Do you have any thoughts about using such a script or any feedback to the implementation?

👏👏👏👏 @felskov  you ve told everything. Even trying to fix this with ts project references is a nightmare and not sure if the best solution. There is another case besides yours. Is that when  app1 and app2 depend on lib1 in a monorepo, you re going to have issues if app1 is strict and app2 is not. Both of them will check lib1 with their tsconfigs and this will fail. Lib1 have to satisfy both configs. What a nightmare work with typescript :/.

**Comment by borisrakovan** [comment]
I wrote this workaround script that solves this without needing to relax the TypeScript configuration of your project. It adds a @ts-nocheck directive to the top of all problematic files of the 3rd party libraries, essentially silencing the errors when your project is compiled.

You can run it automatically on install by adding this to the `scripts` section in `package.json`

`"postinstall": "tsx scripts/fix-lib-types.ts"`

```typescript
import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';

type PackageConfig = {
	// Package name as it appears in node_modules
	name: string;
	// Base directory within the package where source files are located
	sourceDir: string;
	// List of problematic file paths relative to sourceDir
	problemPaths: string[];
};
const PROBLEMATIC_PACKAGES: PackageConfig[] = [
	{
		name: '@solana/spl-token',
		sourceDir: 'src',
		problemPaths: [
			'extensions/tokenGroup/state.ts',
			'extensions/transferFee/instructions.ts',
			'extensions/transferHook/instructions.ts',
			'extensions/transferHook/seeds.ts',
			'extensions/transferHook/state.ts',
			'state/account.ts',
		],
	},
];

async function addTsNoCheck() {
	try {
		// Go up to common's parent (monorepo root)
		const rootNodeModules = join(__dirname, '..', 'node_modules');

		for (const pkg of PROBLEMATIC_PACKAGES) {
			const packagePath = join(rootNodeModules, pkg.name, pkg.sourceDir);
			console.log(`Processing ${pkg.name} in ${packagePath}`);

			for (const problemPath of pkg.problemPaths) {
				const fullPath = join(packagePath, problemPath);

				try {
					const content = await readFile(fullPath, 'utf-8');

					if (!content.includes('// @ts-nocheck')) {
						const newContent = `// @ts-nocheck\n${content}`;
						await writeFile(fullPath, newContent);
						console.log(`Added @ts-nocheck to ${fullPath}`);
					} else {
						console.log(
							`@ts-nocheck already present in ${fullPath}`
						);
					}
				} catch (err: any) {
					if (err.code === 'ENOENT') {
						console.warn(`File not found: ${fullPath}`);
					} else {
						console.warn(`Could not process ${fullPath}:`, err);
					}
				}
			}
		}

		console.log('Successfully processed all packages');
	} catch (err) {
		console.error('Error processing files:', err);
		process.exit(1);
	}
}

void addTsNoCheck();
```

**Comment by phil294** [comment]
the above concerns (primarily by @felskov) are now in #40426

**Comment by repulsio** [comment]
So how do you ignore `node_modules/`? No solution was given
