### ISSUE TITLE
WebAssembly namespace only found in lib.dom.d.ts and not available for NodeJS

### ISSUE THREAD

**Issue by tomaka** [microsoft/TypeScript#47381]
# lib Update Request

Hi :wave: 

`lib.dom.d.ts` contains a namespace named `WebAssembly` in accordance with https://webassembly.github.io/spec/js-api/

However, correct me if I'm wrong, but WebAssembly is not a web-specific technology but a "core" JavaScript API.
NodeJS for example also supports creating/running WebAssembly instances.
And on the MDN, it is classified as a "global object", and not something specific to the web: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#webassembly

As a consequence, it is not currently possible to use WebAssembly from JavaScript without importing the `dom` library.
An example of that is that the `@types/node/wasi.d.ts` file contains dummy return values for its functions:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8745cf9f8425bfcabaed69fba1684082a18f3191/types/node/wasi.d.ts#L136

## Configuration Check

This issue applies to situations where `lib` does **not** contains `dom`.

## Missing / Incorrect Definition

The missing definition is the `WebAssembly` object/namespace and everything below.

`WebAssembly` shouldn't be present in the `dom` library but, if I'm not mistaken, as a language feature.

## Sample Code

Any code that uses WebAssembly doesn't work, for example:

```js
await WebAssembly.instantiate(wasmBytecode, {});
```

## Documentation Link

https://www.w3.org/TR/wasm-js-api-1/
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#webassembly

**Comment by IllusionMH** [comment]
WASM isn't part of ECMAScript spec and it's just browsers/runtime providing JS API.
Similar to `console` which is not part of ES spec, but it's may be non-trivial to find runtime that doesn't have it.

**Comment by tomaka** [comment]
A duplicate of which issue? Is there an issue I can follow to know whether there is a work-around and/or when this is fixed?

**Comment by IllusionMH** [comment]
> UPD. Basically duplicate of https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/826
