### ISSUE TITLE
Generics inside array doesn't determined correctly

### ISSUE THREAD

**Issue by Flairax** [microsoft/TypeScript#47393]
# Bug Report

### 🔎 Search Terms
Generics inside array doesn't determined correctly

### 🕗 Version & Regression Information
- This changed between versions 3.8.3 and 3.9.7 - types inferred correctly if function argument is omited.
- If the argument is present not working in any version.

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgJIAVgAcIB5UA0yA8gHzIDeyAvgFCiSyIqY4A2oehJ5VdtCNnADOw5ACEArsNwAVXrWRLkWbHgCCpABSqcwgFzIA2hjVyimgLoBKQ6wgcQeWRdIBuRct0ai47d4NjUxxzZE0iYJ8JUhs7NUdnX3dPJW9cdV8iAGF-NUCTe1DwtEKM6IjC8WyY22R7BNCcj2UVMzKq5CyiABFcvUMCsxcw0gq2pLGQjpzJvC7kXti6+M5Q3uavNR08w0jcOBAATyIDw9IjJfrV05OjhRaWqAgwSSgQZBBJNjYNpTp+GCSEAIMDAAD27wAtnAsPgiGQtNCsDgoIYtAA3OBsSQQXbWZAAXnIxFqe24ZEoyCeLzebhotAEEOEYGQACNpISPhAAO4SaS4T6Q1nQbTWDy0dnCAB03i0RhSyCRWgAHoTyAADdXWAgKpWqonGMBQHE2HUtPVq4ya026mEqy3wNjCCDWWg2NxAA)

### 💻 Code
```ts
interface IPipe<I, O> { }
interface Pipeline<I, O> { }

class Bus<T> {
    pipe<A>(pipes: [IPipe<T, A>]): Pipeline<T, A>;
    pipe<A, B>(pipes: [IPipe<T, A>, IPipe<A, B>]): Pipeline<T, B>;
    pipe<A, B, C>(pipes: [IPipe<T, A>, IPipe<A, B>, IPipe<B, C>]): Pipeline<T, C>;
    pipe<A, B, C, D>(pipes: [IPipe<T, A>, IPipe<A, B>, IPipe<B, C>, IPipe<C, D>]): Pipeline<T, D>;
    pipe(pipes: IPipe<any, any>[]): Pipeline<any, any> {
        return null;
    }
}

function map<I, O>(mapper: (value: I) => O): IPipe<I, O> { return; }

const bus = new Bus<number>();

bus.pipe([
    map(() => ``),
    map(() => [true]),
    map(() => [``]),
    map(() => false)
]);
```

### 🙁 Actual behavior

Every next pipe first generic argument determined as Bus basic type.
```typescript
bus.pipe(
   map((x) => ``),
     // ^ x: number
   map((x) => [true]),
     // ^ x: number
   map((x) => [``]),
     // ^ x: number
   map((x) => false)
     // ^ x: number
);
```

### 🙂 Expected behavior

Every next pipe first generic argument should be based on previous pipe second generic type.
```typescript
bus.pipe(
   map((x) => ``),
     // ^ x: number
   map((x) => [true]),
     // ^ x: string
   map((x) => [``]),
     // ^ x: boolean[]
   map((x) => false)
     // ^ x: string[]
);
```

**Comment by whzx5byb** [comment]
> * This changed between versions 3.8.3 and 3.9.7

Actually your example doesn't work in 3.8.3. Add the omitted first argument in the functions like `bus.pipe(map((x) => ``), map((x) => [true]), map((x) => [``]), map((x) => false));` and these `x` will still be inferred as `number`.


And I would suggest using variadic arguments as workaround.
```ts
interface IPipe<I, O> { }
interface Pipeline<I, O> { }

declare class Bus<T> {
    pipe<A>(...pipes: [IPipe<T, A>]): Pipeline<T, A>;
    pipe<A, B>(...pipes: [IPipe<T, A>, IPipe<A, B>]): Pipeline<T, B>;
    pipe<A, B, C>(...pipes: [IPipe<T, A>, IPipe<A, B>, IPipe<B, C>]): Pipeline<T, C>;
    pipe<A, B, C, D>(...pipes: [IPipe<T, A>, IPipe<A, B>, IPipe<B, C>, IPipe<C, D>]): Pipeline<T, D>;
}

declare function map<I, O>(mapper: (value: I) => O): IPipe<I, O>

const bus = new Bus<number>();

bus.pipe(
    map((x) => ``),
      // ^ x: number
    map((x) => [true]),
      // ^ x: string
    map((x) => [``]),
      // ^ x: boolean[]
    map((x) => false)
      // ^ x: string[]
);
```
[Playground](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgJIAVgAcIB5UA0yA8gHzIDeyAvgFCiSyIqY4A2oehJ5VdtAEwgI2cKChFwAzlOQAhAK5TcAFV61km5Fmx4AgqQAUAOlM6cUgFzIA2hl2qiBgLoBKa6wgcQeFU9IA3Bpa5vpEckamxqFWtvY4jsgGRPFh8qRuHrrevuGBwZqhuHrhRADCkWa6sXaeiclodSXpKXVy5RnuyJ45iRVBWtoOze3IZUQAIpXR1da1Dn5JpK3DeSsJoxXreOPIU5nd2ZyJU0H8QpLiyDAKIAhgwAD2IMgAtnBY+ERkhu9YOFBrIYAG5wNgKCDWVCuZAAXnIxC6qS+PFotAQzykYGQACMlHDkD4AO7yJS4EAKV446BGVxBWh4qQzHCGApvD6GQwADxh8OQAAN+a4CGy-pyeXDyDYwFAIW4RYMxdzeVLBfLRRzlZLrmCpBBXLQ6UA)

**Comment by Flairax** [comment]
@whzx5byb yes, you are right, doesn't seems to ever worked. Unfortunately variadic arguments is not an option because in my code I want to use few more arguments after pipes. Omitted them for simplicity. 
```typescript
interface IConfig<I, O> {}

class Bus<T> {
   pipe<A>(pipes: [IPipe<T, A>], config?: IConfig<T, A>): Pipeline<T, A>;
   pipe<A, B>(pipes: [IPipe<T, A>, IPipe<A, B>], config?: IConfig<T, B>): Pipeline<T, B>;
   pipe<A, B, C>(pipes: [IPipe<T, A>, IPipe<A, B>, IPipe<B, C>], config?: IConfig<T, C>): Pipeline<T, C>;
   pipe<A, B, C, D>(pipes: [IPipe<T, A>, IPipe<A, B>, IPipe<B, C>, IPipe<C, D>], config?: IConfig<T, D>): Pipeline<T, D>;
   pipe(pipes: IPipe<any, any>[]): Pipeline<any, any> {
      return null;
   }
}
```
Because of this such solution is also not fitting
```typescript
class Bus<T> {
   pipe<A>(pipe_1: IPipe<T, A>): Pipeline<T, A>;
   pipe<A, B>(pipe_1: IPipe<T, A>, pipe_2: IPipe<A, B>): Pipeline<T, B>;
   pipe<A, B, C>(pipe_1: IPipe<T, A>, pipe_2: IPipe<A, B>, pipe_3: IPipe<B, C>): Pipeline<T, C>;
   pipe<A, B, C, D>(pipe_1: IPipe<T, A>, pipe_2: IPipe<A, B>, pipe_3: IPipe<B, C>, pipe_4: IPipe<C, D>): Pipeline<T, D>;
   pipe(pipes: IPipe<any, any>[]): Pipeline<any, any> {
      return null;
   }
}
```
Thanks anyway :)

**Comment by RyanCavanaugh** [comment]
I don't understand what the actual vs expected problem is. Can you state it more clearly?

**Comment by Flairax** [comment]
@RyanCavanaugh, changed description in @whzx5byb way. Think it more clearer now.

**Comment by RyanCavanaugh** [comment]
Thanks, that's much clearer.

Generic inference has a fixed number of passes for fixing type parameters and isn't capable of inferring this sort of pattern.

See also #30134
