### ISSUE TITLE
Unable to narrow indexed type by generic

### ISSUE THREAD

**Issue by jethrolarson** [microsoft/TypeScript#47396]
# Bug Report

### 🔎 Search Terms

narrowing generic index

### 🕗 Version & Regression Information

As of Jan. 11, 2022 
- This is the behavior in every version I tried (4.5.4 and everything else supported on the playground), and I reviewed the FAQ for entries about narrowing with generics. I saw some potentially relevant items but they seemed different

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4&ssl=7&ssc=16&pln=6&pc=18#code/C4TwDgpgBAkgdgEwgDwgZygXigcgGYD2BOUAPrgEYCGATjgFD2iRQCyVYYAlnAOYA8MBMgB8WWMKgpgERBnxESAfigBvQgQBcUCkQA2EKnAC+UbauOMAxgThpgUALZUA1hAAqACx69xgydKyCBjwSKhoIgAUPGHaQsgAlNrsnD7+olhiqvRQUGgA7lzAVp7RiCgJajm5UFZUaNAKxJrVNVA0EMAArjRwahraeFR6DZZtSENdesAtbbkd3b1qpgD0K1Du4I0WJFwYcAQO9WhcvHBUFAZQwATXW7gp3HzpIjgAdNWWlvRrUACqaCovGg+QINBcGHqUB4MnKCGungIXV4nnoNjsDmQyQ4TwEOGodDE2Gcbi8Pki+NoOASaNs9igIGxqWeTRwRKcrg83j4FI01NpGKgAC8mbj+JTCeILABuehAA)

### 💻 Code

```ts
type Indexes = 'foo' | 'bar'

type Mapping<Idx> = Idx extends 'foo' ? {foo: boolean} : {}

const makeThing = <Idx extends Indexes>(index: Idx): Mapping<Idx> => {
  switch(index) {
    case 'foo':
      return {foo: false}
    default:
      return {} // Type '{}' is not assignable to type 'Mapping<Idx>'.
  }
}

// Usage works as intended though
const x: Mapping<'bar'> = makeThing('bar')
const y: Mapping<'foo'> = makeThing('foo')
const z: Mapping<'bar'> = {};
```

### 🙁 Actual behavior
TSError: Type '{}' is not assignable to type 'Mapping<Idx>'.

### 🙂 Expected behavior

Implementation of `makeThing` is accepted.

I tried a variety of other encodings such as:
* Making the union of indexes an enum.
* Making the switch a nested ternary
* Using an lookup type (interface where keys were the Indexes and values were the intended output types and then indexing into them)

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/33912

**Comment by jethrolarson** [comment]
Will close and watch the linked issue with interest.
