### ISSUE TITLE
Not getting "Unreachable code" error in: a = true; if (a) { throw; }; console.log(a); 

### ISSUE THREAD

**Issue by devinrhode2** [microsoft/TypeScript#47405]
What should happen:
![CleanShot 2022-01-12 at 10 45 32](https://user-images.githubusercontent.com/539816/149173733-33fb93db-cf6b-4c23-be59-dace3e6f0d17.png)
What does happen: (no error)
![CleanShot 2022-01-12 at 10 47 41](https://user-images.githubusercontent.com/539816/149173798-c60f843d-05bd-4425-b4a2-3a5dd6907481.png)
I also tried adding `as const`, still no error:
![CleanShot 2022-01-12 at 10 44 38](https://user-images.githubusercontent.com/539816/149173820-5dfd55ac-87a3-4bfc-b921-35c1e211b8be.png)

**Comment by devinrhode2** [comment]
What I really want is for this to work:
```ts
const a = 'a'

if (!a) {
  throw new Error('a')
}

console.log('dead code')
```
But this boolean issue version above seems like a smaller, easier to work on issue

**Comment by RyanCavanaugh** [comment]
Why are you writing code like this?

**Comment by RyanCavanaugh** [comment]
I see. Anyway, unreachability errors only occur for syntactically-unreachable positions. We don't do reachability based on types because it prevents you from writing defensive code
```ts
function f(s: string) {
  if (typeof s !== "string") {
    throw new Error("Bad JS caller go away");
    // ^ "unreachable"
  }
  // etc
}
```

**Comment by devinrhode2** [comment]
Bad is caller... Ok.. but maybe the tide has turned. Maybe your code snippet should require a @ts-expect-error? I think it's a good example 6 years ago, idk.

**Comment by devinrhode2** [comment]
I know it's important to gradually migrate a js project to ts, but that's just a transitional period. Eventually codebases are pure TS, and writing this extra defensive code is just wasting bandwidth.

**Comment by fatcerberus** [comment]
If you're publishing a library, you can't mandate that all your API consumers are TS so you have to write the defensive code.

**Comment by RyanCavanaugh** [comment]
There are other examples where you want to write type-unreachable code, e.g. https://stackoverflow.com/questions/39419170/how-do-i-check-that-a-switch-block-is-exhaustive-in-typescript

**Comment by devinrhode2** [comment]
If there was a really nice cli wizard to setup a tsconfig or jsconfig, we may be able to ask users to run it. Then they get rich type info inside their ide, and type errors. Cli wizard could even add a husky pre-commit hook to check for type errors

**Comment by devinrhode2** [comment]
https://www.typescriptlang.org/tsconfig#allowUnreachableCode

So if code is probably unreachable base on JavaScript syntax, we can get errors. But if.. some code is unreachable based on type analysis, then TS doesn't say anything.

If you haven't handled both the `undefined` and defined (`string | number | ...`), TS will correctly complain that some value could be undefined. So, you add type guards, it statements, optional chaining, to help you avoid errors.

But, when an underlying library is refactored to guarantee that a value is always defined... You can delete the code TS told you to add.

In a way, typescript is only telling you to add code.

Perhaps we could adjust tsconfig compilerOptions.

- Gauranteed unreachable based on JavaScript syntax. These are very likely coding errors.
- Unreachable based on type analysis. 

The in-editor warning vs cli aspect could easily be solved by taking from eslint, warnings only appear in-editor, errors are both. And of course you can just turn it completely off. Being conceptually aligned with eslint here I think could help in the long term

**Comment by sstchur** [comment]
I too would really like to see this available as a compiler option.  I think the argument about defensive code is kinda weak, especially in an all TS world, as many of our codebases are.

Take this example:
![image](https://user-images.githubusercontent.com/47366639/178810701-dea37706-90be-45f1-830d-3d128f24d49c.png)

TS has no problem with this check even though it knows that `x` can never be `null`.  TS won't let me use x without first assigning it, and it certainly won't let me assign it null.

In fact, it's almost comical when you try to set `x` to `null`.  Observe this screen shot:
![image](https://user-images.githubusercontent.com/47366639/178810896-033c4bdd-3c14-43ff-a2b6-b3b7df0e5a62.png)

Typescript is yelling at me that `null` is not assignable to `x`'s type (`string | number`); yet in the same breath, TS is saying "but sure, go ahead and check if x is null anyway!"

**Comment by RyanCavanaugh** [comment]
We let you check against `undefined` because many people don't run with `noUncheckedIndexedAccess` but want to write code like
```ts
function fn(x: string[], i: number) {
  if (x[i] === undefined) throw new Error("Out of bound");
  return x[i];
}
```
Sort of the same thing for `null` - you might get a `null` from a library that was built or written with `strictNullChecks` off and have to do a *valid* null check against its outputs.
