### ISSUE TITLE
Loading modules declared in .d.ts files with relative paths and rootDir

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#4740]
Assuming you have two files, `modtest/mod.ts` and `whatever/somedef.d.ts`.

`somedef.d.ts` declares an external module like this:
```ts
declare module "modtest/parent" {
  export var x: number;
}
```

And mod.ts imports it as a relative import:
```ts
import {x} from "./parent";
```

When I pass `--rootDir $PARENT_OF_MODTEST` and explicitly pass all the `.d.ts` and `.ts` files into tsc, it used to find `./parent` in 1.5.3, but no longer finds it in 1.6.0-beta:

```
tsc --rootDir $PWD --module commonjs modtest/mod.ts whatever/somedef.d.ts
modtest/mod.ts(2,17): error TS2307: Cannot find module './parent'.
```

@vladima

**Comment by vladima** [comment]
@mprobst cannot repro, maybe there are other steps that I've missed?

```bash
v2m@v2m-ThinkPad-W520:~/sources/bugs/relativeDirs$ tree
.
├── modtest
│   └── mod.ts
└── whatever
    └── somedef.d.ts

2 directories, 2 files
v2m@v2m-ThinkPad-W520:~/sources/bugs/relativeDirs$ cat modtest/mod.ts 
import { x } from "./parent";
v2m@v2m-ThinkPad-W520:~/sources/bugs/relativeDirs$ cat whatever/somedef.d.ts 
declare module "modtest/parent" {
    export var x: number;
}
v2m@v2m-ThinkPad-W520:~/sources/bugs/relativeDirs$ node ~/sources/TypeScript/built/local/tsc.js  --version
message TS6029: Version 1.5.3
v2m@v2m-ThinkPad-W520:~/sources/bugs/relativeDirs$ node ~/sources/TypeScript/built/local/tsc.js  --rootDir $PWD --module commonjs modtest/mod.ts whatever/somedef.d.ts 
modtest/mod.ts(1,19): error TS2307: Cannot find module './parent'.
v2m@v2m-ThinkPad-W520:~/sources/bugs/relativeDirs$ 
```

**Comment by mprobst** [comment]
Yeah, it seems that this was shadowed in the previous version (actually 1.5.2) not respecting `--noResolve` (or previous version of our build driver, but I don't think something changed there).

That being said, I still think this is a bug: if I have a `.d.ts` file declaring `modtest/parent`, then this should behave just as if I had a `modtest/parent.ts` lying around, which it doesn't. Let's talk a bit about this offline.

**Comment by vladima** [comment]
I would argue that this is a bug - compiler never resolved relative module names to ambient external modules and this behavior is [defined in spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#11.3.1). The fact that is somehow worked before looks like an implementation glitch. Your case looks more like a feature request and I agree that there is a value in it. What we currently need is design proposal, we can discussion offline

**Comment by mhegazy** [comment]
ambient module names are not meant to be relative. as a matter of fact there is an explicit check for this. this looks like a bug that was fixed. @vladima is working on another proposal for resolving relative module names, so that should solve the underlying issue.
