### ISSUE TITLE
Error assigning value using a setter after applying `Object.freezee` 

### ISSUE THREAD

**Issue by scristobal** [microsoft/TypeScript#47408]
# Bug Report

### 🔎 Search Terms

Object.freeze, freeze, setter, set, Object.defineProperty, 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Object.freeze` and setters.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/MYewdgzgLgBARgQwE4wLwwPJwFYFNhQB0AZkrrgF64AUA3hLrMSCNWAFwwCuYA1mCADuYAJQxaYAL6SRAKFmIkJFmhgAmGAHpNMAMIIwA2AggQAlgHMwMKCBgByZiHvx8CLgxhnYZiDAQwZAgAJgC04AA2AJ4wAA5IILG4SFBRhNRqAKwALAAMIkA)

### 💻 Code

```
const bar = Object.freeze({set foo(n: unknown) {n}})

bar.foo = 2
```

### 🙁 Actual behavior

```
 Cannot assign to 'foo' because it is a read-only property.(2540)
```

### 🙂 Expected behavior

No error message 😄

**Comment by RyanCavanaugh** [comment]
TIL this is how Object.freeze works with accessors 🤔

The type system doesn't track this information and it's not clear how we'd even write the type of `Object.freeze`. This seems out of scope unless we gain other scenarios where tracking property vs accessor and find other places where a mapped type might care

**Comment by scristobal** [comment]
Thanks for the input @RyanCavanaugh !

There are of course workarounds, and it is not a critical issue anyway! We can live with it 😉 

In case you think this is worth considering any further, count on me!
