### ISSUE TITLE
False "variable is used before being assigned" error

### ISSUE THREAD

**Issue by sempasha** [microsoft/TypeScript#47402]
# Bug Report

### 🔎 Search Terms

Variable is used before being assigned ts(2454) 

### 🕗 Version & Regression Information

According to [TypeScript Playground](https://www.typescriptlang.org/play?#code/DYUwLgBAbghsCuIBcEDkAzGBLYqIB80B7Aa1QG4AoMAJwE8IBvSgSFgRAgF5iyqBfCAGMYYIQAsIAChA0aRGgEomrdom5pMOCpUHosAOzjAGzFkKIGAzkVAA6YEQDmUtSEUDKQA) error appears for TypeScript versions `>= 3.3.3 && <= 4.5.4` and for latest nightly `4.6.4-dev.20220112`. For versions ``, `3.5.1` and `3.6.3` no error happens.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAbghsCuIBcEDkAzGBLYqIB80B7Aa1QG4AoMAJwE8IBvSgSFgRAgF5iyqBfCAGMYYIQAsIAChA0aRGgEomrdom5pMOCpUHosAOzjAGzFkKIGAzkVAA6YEQDmUtSEUDKQA)

### 💻 Code

```ts
let value: 'fail' | 'ok';
try {
  value = 'ok';
} catch (error) {
  value = 'fail';
} finally {
  console.log(value);
}
```

### 🙁 Actual behavior

Error `Variable 'status' is used before being assigned.ts(2454)` at `finally` block.

### 🙂 Expected behavior

Expect provided code sample has no error at `finally` block, because variable `status` will be surely initialized.

**Comment by sempasha** [comment]
Workaround is to initialize status variable immediately
```ts
function test(): void {
  let status: 'fail' | 'ok' = 'ok';
  try {
    if (Math.random() < 0.5)
      throw new Error('Error');
  } catch (error) {
    status = 'fail';
    console.error(error);
    throw error;
  } finally {
    // Variable 'status' is used before being assigned.ts(2454)
    console.log(status);
  }
}
```

**Comment by RyanCavanaugh** [comment]
We don't have the necessary machinery to figure this out. Determining that this is OK requires knowing that the line `status = 'fail';` *cannot* throw, and we don't track what kinds of statements/expressions can/can't throw. Even if we did, an assignment statement *can* throw due to the target being in TDZ.
