### ISSUE TITLE
Maybe type like this: ?string

### ISSUE THREAD

**Issue by andrisole92** [microsoft/TypeScript#47426]
# Suggestion

Can we add the Maybe type like in [Flow](https://flow.org/en/docs/types/maybe/)? I found it handy since we deal with many nulls/undefined in JavaScript/TypeScript. Something like `Maybe<string>` is way more verbose than `?string`.

## 🔍 Search Terms

Nullable, Maybe type, optional type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behaviour of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Built-in maybe type: `const nullableString = ?string`

## 📃 Motivating Example

Current: 

```
type Maybe<T> = T | null | undefined;
const nullableString: Maybe<string> = undefined;
```

Future:
```
const nullableString: ?string = undefined;
```

## 💻 Use Cases

N/A

**Comment by DanielRosenwasser** [comment]
We've discussed this in the past. The conclusion we came to was that `?` ends up being too broad of a hammer that could get overused when much of the time a type is really only possibly `null` or possibly `undefined`. Check out the discussions at https://github.com/microsoft/TypeScript/issues/23477 and https://github.com/microsoft/TypeScript/issues/7426 for more details.

**Comment by andrisole92** [comment]
Hmmm - I found it handy, and this is one of the things I am missing the most after moving from Flow to Typescript.

**Comment by andrisole92** [comment]
There is a good saying for this - "Never say never (and always)"

**Comment by fatcerberus** [comment]
I think you missed my point.  The point was that most of the time you’re writing one or the other of `T | undefined` or `T | null`, which one depends on context, but it’s *much* rarer to see `T | null | undefined`. So then we get into bikeshedding what `T?` should actually mean.  If it means `T | undefined | null` but it turns out that most functions only accept one or the other, then the cost of adding it to the syntax is not justified as few people will use it.

**Comment by andrisole92** [comment]
Yeah, well. Working more with all JavaScript/TypeScript and Flow for over five years, I found that Maybe Type in Flow is handy and might be something that TypeScript is currently missing.
