### ISSUE TITLE
Private generic function cause subtype assignment error

### ISSUE THREAD

**Issue by icese7en** [microsoft/TypeScript#47422]
# Bug Report

### 🔎 Search Terms

- private generic function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried(from 4.4.3 to 4.5.4), and I reviewed the FAQ for entries about `Generics`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAglC8UDeAoKsBcUB2BXAtgEYQBOA3CgL4UqiSwBCCyaUDWeRpFlUAZLBp1oACQgAbSCQBiubAGNgASwD22ADwAVAHzMAFEuAR8WTQEoEuwipXiIAQ2w154+wGc3UAMrASuRVq6qOhgJEoAbvZGUAAWElJYYpKksgrKaoH6hsamFvC6vrgQFOgA5hDAmjFKbnpmWD5+ATrIUCQVuCTYUMDVbmRQlKy4YAAmURBVNXpuhYoNc8CB9VDhKkqjyEPobhUGRiZQ5lhrG1tUKCjyarNQs03AcIjYEADu3ovqMNp1FNfYt3u-keTGebw+Dy+DB+ZhoADM5IpVN1sCoSPh7OIAOJ7IHzCHAr7aCzBKAAejJRy8ACYAMwAFgArFgYCRSgQINhgFAVHCeuBoAByRqEmDQwVQGo4FTc9xuJSlbD2Qh2HoqKBgewkez4CqkHl84RQYWfb6CgB0RwFxpgEqlqNlHgVSpV0GA6qNgrFFqgAAUSCopKBjQw7Z58DV5dhSpLup7bVBCLhue0AI64JTtTZKOPWwVINgcAjEciDC2sPHAc0jcZGKa1Sti83lSp9Oqwi4oBFpZFQcovMLyHFLTRQCAADyM2FGnm+M0WC0hOhJrApsDZHK5Bv59HzmBwxe4ZclngdUDlzuVqvdGq1Or1JG3ns0Pr3MCLXFLlDD56diqvboenEUD-Pc9g5tyvI7kKL4ADSJsmxoviBKi4OImzELGsyOMoEybK8hgxOeUCjEocJwqQnLcm4uCEEaUGgb44Fbl65Y7Is5q7MAegFu+UAAIyDGYnb9qQShDriixih2QA)

mainly focus on the `normalGet` part.

### 💻 Code

```ts
type A = {
  A: number;
};

type AB = {
  B: number;
} & A;

type HelperFunction<T> = (item: T) => boolean;

class Struct<T> {
  private helper: HelperFunction<T> = (item: T) => true;
  getThis(): Struct<T> { return this; }
  updateThis(struct: Struct<T>): void {}
  set(item: T): void {}
}

const structA = new Struct<A>();
const structAB = new Struct<AB>();

function normalGet(struct: Struct<A>) {
  // TS2345: Argument of type 'Struct<AB>' is not assignable to parameter of type 'Struct<A>'. Type 'A' is not assignable to type 'AB'. Property 'B' is missing in type 'A' but required in type '{ B: number; }'.
  struct.updateThis(structAB.getThis());
}
```

### 🙁 Actual behavior

- if we avoid assigning generic function to `this.helper`, like commenting out this line `private helper: HelperFunction<T> = (item: T) => true;`, then no error would be thrown.

### 🙂 Expected behavior

private generic function or property doesn't affect type signature.

**Comment by MartinJohns** [comment]
I don't see an error here. The first issue is because those types are not compatible. You can fix this by accepting a type parameter, e.g. `updateThis<R extends T>(struct: Struct<R>): void {}`.

The second issue is also as expected. Why do you expect you could assign `{ A: 1, B: 2 }`? It might be that `T` provides more properties than this.

**Comment by icese7en** [comment]
> I don't see an error here. The first issue is because those types are not compatible. You can fix this by accepting a type parameter, e.g. `updateThis<R extends T>(struct: Struct<R>): void {}`.
> 
> The second issue is also as expected. Why do you expect you could assign `{ A: 1, B: 2 }`? It might be that `T` provides more properties than this.

Yep, I found the error of the second one. So I changed the playground link. You can check again.

For the first issue, If I add an intermediate interface `IStruct`, you can see the [playground code here](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAglC8UDeAoKsBcUB2BXAtgEYQBOA3CgL4UqiSwBCCyaUDWeRpFlUAZLBp1oACQgAbSCQBiubAGNgASwD22ADwAVAHzMAFEuAR8WTQEoEuwipXiIAQ2w0l2IyQBm9+dACSAZWASXEUtXVR0AHMIYE0ACyUAZz0zLH9A4OBQinRcMAATeyM4xL0E9MVUgKCQnRSoADcVJTzsqATogyMTKHMsRuaeFBR5cXsEhKgqjNCoJXwwO3wIVwm06sydFnQwEiV6wuhYiSksMUlSWQVlNRnETuNTC3hddIhWqJj4pLqpmrCoEjRXAkbBQYBfMhQSisXIFIpfUrlYBYX4bbR1fp5ZDQ9DtYD3bq9BpNLFIaHQ4ZqMptJEwSpI9QwXSIbAQADukwZTOSFHkVOANPWMHYUDW02FzJw7M560ZDG0PKG7jkilUoOwKhI+Hs4gA4h0yut6bKmRZwlAAPQWnp+ABMAGYACwAViwMBIEQIywFKncYPA0AA5Ki5dpA7MJhqBWMEkoIth7IQ7GCVFAwPYSPYlm4oL7-fRg1ywwA6HoBqCBmDhxI4FTR8ZxhNJ6DAVPCCvCwOlgAKJBUUlAFYY1Ym+ESsewEVmoPblfDhFwAsBAEdcEpAViXPmg0g2BwCMRyFCu6xDRli7CDsUkmfFMLix9r8kzIMgA), then no error would be thrown.

**Comment by fatcerberus** [comment]
`Struct<T>` is contravariant in `T` under `strictFunctionTypes` because `helper` takes a `T` as a parameter.

**Comment by icese7en** [comment]
> `Struct<T>` is contravariant in `T` under `strictFunctionTypes` because `helper` takes a `T` as a parameter. You therefore can't substitute a `Struct<AB>` in place of a `Struct<A>` because its corresponding `HelperFunction` is less capable.

But `helper` is private property. Should private properties and methods affect type checking?
If I change the private property `helper` to a private method: [Playground code link](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAglC8UDeAoKsBcUB2BXAtgEYQBOA3CgL4UqiSwBCCyaUDWeRpFlUAZLBp1oACQgAbSCQBiubAGNgASwD22ADwAVAHzMAFEuAR8WTQEoEuwipXiIAQ2w154+wGc3UAMrASuRVq6qOhgJEoAbvZGUAAWElIGRiZQ5sgkEMC4JNhQvrgQZLysAOYZmjFKbnpmWD5+ATrIUOmZ2bkVbmRQlKy4YAAmURDllXpueYq1E8CBNVDhKkr9yD3obhmJxqZzC0srVCgo8mrjUOP1wHCI2BAA7t7T6jDa1RTH2Kfn-pdM13cPFyeDBeZhoADM5IpVDlsCoSPh7OIAOIbL6TAHfJ7aCzBKAAejxKS8ACYAMwAFgArFgYCRigQINhgFAVGDcuBoAByOqYmDAzlQSo4FTM9xuJTFbD2Qh2XIqKBgewkez4DKkFls4RQbmPZ6cgB0KQ52pgAqFsNFHglUpl0GA8q1nL5BqgAAUSCopKBtQwzZ58JVxdhioKco7TVBCLhmekAI64JTpZZKMPGzlINgcAjEcjdA2sNHAfV9QZGEZVQt8-WlYDl6qgg4oCEKZRqKClG5heQomaaKAQAAeRmw-U8zzG0ymgJ0ONYBNgdIZTI17Po6cwOGz3Dzgs8FqgYut0tl9oVSpVapIK8dmhd65gWa4ucofoPVslx7tDriUHe53sKbMqyq5creAA0kbRtqt6-iouDiMsxChuMjjKEMyy3IYMQHlA-RKGCYKkIyzJuLghBasBf6+ABy5OvmazTPq6zAHoGYPlAACM3RmI2HakEo3aotMfINkAA), then no error would be thrown.

From [this code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAglC8UDeAoKsBcUB2BXAtgEYQBOA3CgL4UqiSwBCCyaUDWeRpFlUAZLBp1oACQgAbSCQBiubAGNgASwD22ADwAVAHzMAFEuAR8WTQEoEuwipXiIAQ2w0l2IyQBm9+dACSAZWASXEUtXVR0AHMIYE0ACyUAZz0zLH9A4OBQinRcMAATeyM4xL0E9MVUgKCQnRSoADcVJTzsqATogyMTKHMsRuaeFBR5cXsEhKgqjNCoJXwwO3wIVwm06sydFnQwEiV6wuhYiSksMUlSWQVlNRnETuNTC3hddIhWqJj4pLqpmrCoEjRXAkbBQYBfMhQSisXIFIpfUrlYBYX4bbR1fp5ZDQ9DtYD3bq9BpNLFIaHQ4ZqMptJEwSpI9QwXSIbAQADukwZTOSFHkVOANPWMHYUDW02FzJw7M560ZDG0PKG7jkilUoOwKhI+Hs4gA4h0yut6bKmRZwlAAPQWqAAORUUFIJE1UDZKlw4ixxDBsSdbOwrENGQAdLCDsUkoHFMKgx9w8kzIMgA), Is there any difference between `IStruct` which we assume it has all public properties and methods of `Struct` class?

**Comment by fatcerberus** [comment]
Why *wouldn't* private properties affect type checking?  Methods of a class can access private members of other instances of the same class, so variance still applies.

**Comment by icese7en** [comment]
> Why _wouldn't_ private properties affect type checking? Methods of a class can access private members of other instances of the same class, so variance still applies.

From this perspective, why can we bypass this error once we create an interface?

Thx for replying. But from this perspective, why can we bypass this error once we create an interface? I am just curious about the difference between the `Struct` class and the `IStruct` intermediate interface.

**Comment by fatcerberus** [comment]
That's actually a real soundness hole caused by structural typing.  Be careful, here be dragons:

[Playground](https://www.typescriptlang.org/play?ts=4.5.4#code/MYGwhgzhAEBiD28A8AVAfNA3gKGtY8AdhAC4BOArsCfGQBQAOFARiAJbDQAeAXNCgEosAX1z5m0ALzQ6vfkMkYCxeCACmAOhDwA5nRIBPBmvgAzbgIDcY0xUJ1TiPgmToBfAG7w2AEyxi8EgALNggNYGYHRA0uKzFRYWtsNkISNTJTMGA1aABJF1QMHDxbezl8xEL3aC9fa1FsZVJoR3hnSsIKAFtmdIxpQjUAdzhEOgAWACY4ppJoZjAyPgrkUjIUnWgAH2hOnr6pFsRrVo1SukGRlzoAIla1AxuBKzwAelf8WjI1amh0slo2AWZDOdguw1G8Fu90ez0sbw+iAYEAANNAGJAIGo-GBoGsNtAaNBcQADAp7XpkNAk7BAA)

```ts
class Foo<T> {
  constructor(public x: T) {}
  cb = (x: T) => console.log(typeof x);
  fun(foo: Foo<T>): void {
    this.cb(foo.x);
  }
};

interface IFoo<T> {
  fun(x: IFoo<T>): void;
}

const foo: Foo<number> = new Foo(42);
const bar: IFoo<string | number> = foo;
foo.fun(new Foo("fooey"));  // correct error
bar.fun(new Foo("fooey"));  // oops, passed a Foo<string> to a Foo<number>
```
