### ISSUE TITLE
Suggestion: omit `void 0` from output of new JSX transform (`react-jsx`)

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#47439]
# Bug Report

### 🔎 Search Terms

- jsx
- React
- `react-jsx`
- transform
- `void 0`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSX

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=4#code/KYDwDg9gTgLgBAYwgOwM72AGzgXjgHgBMBLANwD4AzCCfAehIoG4g)

### 💻 Code

```ts
export const el = <div>foo</div>;
```

`tsconfig.json`:
```json
        "jsx": "react-jsx",
```

### 🙁 Actual behavior

```ts
import { jsx as _jsx } from "react/jsx-runtime";
export const el = _jsx("div", { children: "foo" }, void 0);
```

### 🙂 Expected behavior

```ts
import { jsx as _jsx } from "react/jsx-runtime";
export const el = _jsx("div", { children: "foo" });
```

---

This is how it works in Babel: [Babel playground](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAYwgOwM72AGzgXjgHgBMBLANwD4AzCCfAehIoG4g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.16.9&externalPlugins=&assumptions=%7B%7D).

I just tried to migrate our codebase at Unsplash to use the new JSX transform but [I noticed a cumulative increase of 5 KB across all chunks](https://unsplash-web-build-tracker.herokuapp.com/builds/3fd6f4102bf56c07041328e97a2984ea9f121602/e202d5a42301fc5d21af44dc4d9d8568796cf9da?sizeKey=gzip&disabledArtifactsVisible=true&graphType=STACKED_BAR&comparedRevisions=3fd6f4102bf56c07041328e97a2984ea9f121602&comparedRevisions=e202d5a42301fc5d21af44dc4d9d8568796cf9da). If we can remove the extraneous `void 0`, this should help reduce the bundle size.

Twitter thread for reference: https://twitter.com/OliverJAsh/status/1481912497175203840

**Comment by RyanCavanaugh** [comment]
I'm not sure how that got there in the first place -- was it required at some point? Some background research to help us convince ourselves this is safe for all React versions would be good

**Comment by OliverJAsh** [comment]
The new JSX transform was implemented in https://github.com/microsoft/TypeScript/pull/39199. I searched the code and comments but didn't find very much. Maybe @weswigham could chime in?

This issue was also mentioned here but it was never addressed: https://github.com/microsoft/TypeScript/issues/40774

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
