### ISSUE TITLE
Don't offer "Remove Unused Code" suggestion for files with syntax errors

### ISSUE THREAD

**Issue by golopot** [microsoft/TypeScript#47435]
# Bug Report

### 🔎 Search Terms

jsx quick fix

### 🕗 Version & Regression Information

- This changed between versions 3.6.3 and 3.7.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220113#code/GYVwdgxgLglg9mABAMTnAFASkQbwFACQATgKZQhFLqEEA8AEiQDZNwB8NdASnAO64BGAEwBmAL5i2tAPQ9eHAnWmMW7QpgDceMXiA)

### 💻 Code

```ts
function Foo() {
	return (
		<Hello>
			<Row {123}}></Row>
		</Hello>
	);
}
```

### 🙁 Actual behavior

Language server provides a quick fix of "Remove unreachable code". The fix replaces `</Hello>` with `</  `. This is annoying because it is applied when I save file, and I have to add back the removed codes.

### 🙂 Expected behavior

No quick fix.

**Comment by RyanCavanaugh** [comment]
> This is annoying because it is applied when I save file

Is this some extension? TS/VS Code definitely doesn't do this automatically.

**Comment by golopot** [comment]
>> This is annoying because it is applied when I save file

> Is this some extension? TS/VS Code definitely doesn't do this automatically.

Oops, I didn't notice that I have fix on save in my settings.

```
"editor.codeActionsOnSave": {
  "source.fixAll": true
}
```

**Comment by RyanCavanaugh** [comment]
I don't want to tell you how to configure your editor but that setup is probably not a great plan 😅

Anyway we shouldn't offer up Remove Unused Code when there are syntax errors in the file since it's going to be wrong a nontrivial amount of the time.
