### ISSUE TITLE
No auto-complete for 'this.' or the class inside static blocks

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript#47438]
# Bug Report

```ts
class A  {
  static #field = 123

  static { 
    this.#field = 123 

    A.#field = 13
  }
}
```

Writing `this.` and `A.` does not give a list of static fields on `A` in the completions. Type checking works fine.

### 🔎 Search Terms
 
static blocks autocomplete completions

### 🕗 Version & Regression Information

N/A

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC3QN4FgBQCIBcyYJbGgGIAzXAUxABNoBeaARgCYBmNNDbPAxadhaTAAtcEAHQlyVWgxa9UfBLHGkK1OvVbpoAXzTagA)

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
