### ISSUE TITLE
Module augmentation overrides interface rather than merge it

### ISSUE THREAD

**Issue by supproduction** [microsoft/TypeScript#47443]
Our behavior when augmenting a module interface, this interface fully overriding, rather than merging with them.

### 💻 Code

```ts
import { Price } from '@spryker-vsf/api';

declare module '@spryker-vsf/api' {
  interface Price {
    relevantGrossAmount: number | null;
    relevantNetAmount: number;
  }
}

let price: Price;
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/16482929/149561299-e52d705a-41f9-4962-8165-869dc25847ba.png)

![image](https://user-images.githubusercontent.com/16482929/149561334-b4c33fc3-e8a1-4071-a9aa-2ae3221a2296.png)

### 🙂 Expected behavior

Merged interface

**Comment by RyanCavanaugh** [comment]
There isn't a `Price` definition in that library. Judging from the screenshots, it seems like you have a global type declared somewhere that you're re-exporting through a different module augmentation? In this case, you need to augment the global type instead.
