### ISSUE TITLE
Function return type assignability error 

### ISSUE THREAD

**Issue by leemhenson** [microsoft/TypeScript#47458]
# Bug Report

I'm using [graphql-mesh](https://www.graphql-mesh.com/) which generates some type definitions for GraphQL resolvers. It also generates a type which contains functions for loading some remote data. I have encountered a situation where the resolver type accepts the return type of the remote data loader without error, even though they are not assignable. If I place the same function call inside another function, then the resolver does reject it.

### 🔎 Search Terms

function return type assignable error

### 🕗 Version & Regression Information

I tried 3.3.3 and nightly in the playground. They all behave the same way.

This is the behavior in every version I tried, and I reviewed the FAQ for entries about common errors.

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgFgSwHYHMoF4oCJ7JVgbgChRIoB5YOCAJ11Q20ursVUKJPGgBkBDAF4h6aTAAoAlBgB8sNmgA+UAAo0A9gFsEAZwgAeEdOJcyIgLJ8wjAN5Eo9qFTwAuKPyEiANHYdPUAJld3YXlvAF9OUl41PgATWj0AQVlMPQAhRmTJGRV1LV10o054gGMAGz4aaBK1JG1gKDKY2OZaESDmhNbWPCKiGrqGgDN-Rmz0WSa47pFJYwH6qA1LV3NLGx97PxRXcdkRyW8HR3lAqD3G5pn5SSIwoA)

### 💻 Code

```typescript
type Thing = "Thing";
type OtherThing = "OtherThing";

type LazyThing = () => Thing | Promise<Thing>;

type ThingMap = {
    thing: LazyThing,
    thing2: LazyThing,
}

type Loader<A> = <B = A>() => Promise<B>;

declare const loadOtherThing: Loader<OtherThing>;

const f2 = () => loadOtherThing();

const map: ThingMap = {
    thing: () => f2(),
    thing2: () => loadOtherThing()
}
```

### 🙁 Actual behavior

The `thing2` doesn't trigger any Typescript errors.

### 🙂 Expected behavior

`thing2` should error out in the same way as `thing`: with `Type "OtherThing" is not assignable to type "Thing"` but it doesn't. 

I'm guessing it's something to do with the `<B = A>` in `Loader`?

**Comment by andresmo001** [comment]
Sys.exe

**Comment by RyanCavanaugh** [comment]
Just simplifying this:
```ts
type A = "A";
type B = "B";

type LazyThing = () => Promise<A>;

type ThingMap = {
    thing: LazyThing,
    thing2: LazyThing,
}

type LoadWithDefault<T> = <U = T>() => Promise<U>;

declare const loadB: LoadWithDefault<B>;

const fixed = () => loadB();

const map: ThingMap = {
    thing: fixed,
    thing2: () => loadB()
}
```

When the type of `fixed` gets determined, there are no candidates for `U`, so `U` gets fixed to the default `B` and the assignment eventually fails.

When the type of `() => loadB()`, there *is* a contexutally-provided inference candidate `A` through `ThingMap`, so `U` gets fixed to `A` and the assignment succeeds.

These types don't make much sense (how can `loadB` know what its type parameter is?) so the resulting inference doesn't behave as predictably as one might hope.

**Comment by leemhenson** [comment]
Thanks @RyanCavanaugh, I figured it was something like that. For future readers, the real type in question is: 

https://github.com/Urigo/graphql-mesh/blob/878ee12cf231e5ee15ec90178a4eb47babc63c63/packages/types/src/index.ts#L146-L158

```typescript
export type InContextSdkMethod<TDefaultReturn = any, TArgs = any, TContext = any> = <
  TKey,
  TReturn = TDefaultReturn
>(params: {
  root?: any;
  args?: TArgs;
  context?: TContext;
  info?: GraphQLResolveInfo;
  selectionSet?: SelectionSetParamOrFactory;
  key?: TKey;
  argsFromKeys?: (keys: TKey[]) => TArgs;
  valuesFromResults?: (results: TDefaultReturn, keys: TKey[]) => TReturn | TReturn[];
}) => Promise<TReturn>;
```

The `TReturn = TDefaultReturn` bit is the equivalent bit to your `U = T`. It exists like this because the idea is the fn is supposed to return a TDefaultReturn, but you can modify the return type with `selectionSet` and `valuesFromResults`. In reality it's not a truthful fn signature because the `selectionSet` affects the shape of `results` but there's no way to statically join that up
