### ISSUE TITLE
Suggestion: Infer type of `property` (to left of `in`) when using "in operator" in if statements on readonly objects

### ISSUE THREAD

**Issue by danieltroger** [microsoft/TypeScript#47450]
# Suggestion

## 🔍 Search Terms

* in operator type inference
* inference in
* in operator
* infer type in operator
* in operator type inference
* in operator string type inference 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

<details>
<summary>When using the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in">in operator</a>, the type of <code>object</code>* is inferred.</summary>

```typescript
const el = document.querySelector("a");
if("href" in el){
   console.log(el); // <-- here el is HTMLAnchorElement
}
```
  </details>
However, the type of <code>property</code>* is not inferred on <code>as const</code>/readonly objects, which it could (and IMO should) be.

## 📃 Motivating Example

```typescript
const obj = { key1: "value1", key2: "value2" } as const;
const string = prompt("Enter a string");
if (string in obj) {
  console.log(string); // <-- here string HAS TO be `"key1" | "key2"` because obj is readonly and the in operator always does the same thing
  // however, `string` is still `typeof string` here
}
```

## 💻 Use Cases

> What do you want to use this for?

Situations where it's important to have a precise type of a string to not get another type error, like this one:

```typescript
const sections = {
  "Motivating Example": process1,
  "Use Cases": process2,
} as const;
const processed_sections = new Set<keyof typeof sections>();

for (const { innerText } of document.querySelectorAll<HTMLHeadingElement>("h2")) {
  if (innerText in sections) {
    sections[innerText]();
    processed_sections.add(innerText); // <-- Argument of type 'string' is not assignable to parameter of type '"Motivating Example" | "Use Cases"'.
  }
}
```

> What shortcomings exist with current approaches?

Getting a type error for something that is obviously not wrong in any way. It is impossible, in runtime, for `innerText` not to be `"Motivating Example" | "Use Cases"` inside of the if-statement at runtime.

> What workarounds are you using in the meantime?

Making a second variable inside of the if-statement that has the name of the first one but `_with_correct_type` appended where I cast the type to what it is when I define it. (i.e. `const innerText_with_correct_type = innerText as keyof typeof sections;`);

## Related issues:

https://github.com/microsoft/TypeScript/issues/21732 is about inferring types on `object` and therefore not the same issue, this one refers to the type of the `property` side.

#### Footnotes

*: `object` refers to the thing to the right of the in operator
*: `property` refers to the thing to the left of the in operator

**Comment by MartinJohns** [comment]
> because obj is immutable

`obj` is not immutable. TypeScript has no way to represent immutable objects in its type system.

**Comment by danieltroger** [comment]
> obj is not immutable.

Sorry, updated it to "readonly". I'm not up to speed on all the labels and their specific meaning.

> This suggestion would add yet another unsound behaviour to the in operator.

In what way is it unsound? Can you please point out to me in the example code what can happen for `innerText` to become something other than `"Motivating Example" | "Use Cases"` after this line: `if (innerText in sections) {`?

I know that TypeScript's type declarations are "fake" and you _could_ get it changed somehow, but as long as you don't trick typescript and the type annotations are correct, that object only has these two keys and `innerText` is for sure one of them inside of the if statement.

**Comment by MartinJohns** [comment]
```typescript
function foo(data: Record<string, unknown>) {
  data["example"] = false;
}

foo(sections);
```

Or alternatively if `sections` is initialized somewhere else and you have an explicit type annotation. Objects are not sealed in TypeScript, additional properties are valid.

**Comment by danieltroger** [comment]
Hmm shit your example would indeed produce an incomplete type annotation.

Why does setting data["example"]=false not change the type of data? I've never understood that.

**Comment by fatcerberus** [comment]
How could it change the type?  That's quite a few steps above normal control-flow analysis and would basically require the compiler to actually *run* your code so it could follow the values through function calls, etc. to track their types.  The types only exist at compile time.

**Comment by danieltroger** [comment]
Fair enough. But @MartinJohns example code rather shows an issue with TypeScript than with my proposal, no?

After their code has ran there will be 'example' in sections even though the type doesn't reflect it. That fact does not change through my proposal. My proposal is simply to "propagate" the existing type information, whether correct or incorrect, down to the type of `property` inside of the if-statement.

**Comment by MartinJohns** [comment]
You're just wrongly assuming objects are sealed, when they're not. Here's a different example:

    const sections = {
      a: 1,
      b: 2
    } as const;

    function foo(data: { a: number; b: number; c?: number }) {
      data.c = 3;
    }

    foo(sections);

The type of `section` has the properties `"a"` and `"b"`, but the value has the additional property `"c"`. This is valid, because TypeScript is structurally typed. If you were to narrow the left side of the `in` operator to `"a" | "c"` you would have unsound behaviour.

**Comment by MartinJohns** [comment]
And if you **really want** this unsoundness, you could just as easy provide it by wrapping it in a function:

```typescript
const obj = { key1: "value1", key2: "value2" } as const;
const str = prompt("Enter a string")!;
//    ^? string
if (isPropertyOf(str, obj)) {
  console.log(str);
  //          ^? "key1" | "key2"
}

function isPropertyOf<T extends object>(key: string | number | symbol, obj: T): key is keyof T {
  return key in obj;
}
```

**Comment by RyanCavanaugh** [comment]
We'd really prefer to not have narrowing cause unsound behavior by default. This can be revisited if/when we get exact types
