### ISSUE TITLE
Implicit 'any' quick fix text grabs text from wrong file

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#47451]
```ts
// @noImplicitAny: true

// @Filename: foo.ts
////var blahblahblahblahblahblahblah;

// @Filename: bar.ts
//// // lol what?
////
////function bar() {
////    let y = blahblahblahblahblahblahblah/*$*/;
////}
```

Request quick fixes at `/*$*/`.

*Expected*: Quick fix text is `Infer type of 'blahblahblahblahblahblahblah' from usage.`

*Actual*: Quick fix text is `Infer type of 'lol what? function bar() ' from usage.`

The problem is that we're passing in the wrong source file to `getText()` at

https://github.com/microsoft/TypeScript/blob/fcdbc932bf51620d9cc70d2299ae5278f0f9d694/src/services/codefixes/inferFromUsage.ts#L61

so maybe we shouldn't pass it at all.

**Comment by MichalPorag** [comment]
Can I take it?

**Comment by DanielRosenwasser** [comment]
Sure! Write a failing test in `tests/cases/fourslash` based on the above. Take a look at other files in that directory for inspiration.

Also take a look at our [`CONTRIBUTING.md`](https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#instructions-for-contributing-code) and the [relevant section about running tests](https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#running-the-tests).

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Should QF be shown at this position? `blahblahblahblahblahblahblah` is an initializer, not a variable declaration. 

```ts
let y = blahblahblahblahblahblahblah/*$*/;
```

**Comment by DanielRosenwasser** [comment]
A quick fix can respond to any error span - personally, I think it's okay to respond to the non-declaration usage (maybe @sandersn has opinions here). The only "bad" experience here is giving a suggestion when the type is going to be `any`.

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser For this case, the QF will produce something like so :). I think this is a +1 issue. 

```ts
function b: anyar() {
  let y = blahblahblahblahblahblahblah/*$*/;
}
```

That's because it tries to use declarations from symbol (which is located in a different file) `var blahblahblahblahblahblahblah`. Where do we need to apply changes?

**Comment by DanielRosenwasser** [comment]
The change should happen in `foo.ts` - does the current code make it hard to keep track of which files changes need to take place in?

**Comment by a-tarasyuk** [comment]
> The change should happen in foo.ts
Oke, got it.
