### ISSUE TITLE
TypeScript allows invalid intersection type with index signature

### ISSUE THREAD

**Issue by srmagura** [microsoft/TypeScript#47456]
# Bug Report

### 🔎 Search Terms

intersection type, index signature

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

Tested in TS Playground for version 3.9 up to 4.6 nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBA4gTgQwLZIXKBeKBvAUFAqOCAZ2AC4oByYsqqAegagFE44B7OSgIluB5QAliSgA7DsCgISJIQHMxCAEYAbaMA5QeANwSqArhB75CAbQDWEEJTJwhY+QF1KVPYYhVcAX1y4mUAByWhDsXFAAtFAkABYcBqoAJmJUUsAxIlDKEDEIOhox0CTI0ADuCCAA-LigkLCIKGgATJg4pgT8rvxe3lAAZG2EUJbWtsD2ji7U7kY9fgEAwhxIYELqUKGc6FHwyKhwLbXQmaQkEGLAQvqqIFAGYgbFahC4AMYcYmRQ8g37TZS7RoHVp4IadajdAA07SgSBAAGlRtN9LMfEA)

### 💻 Code

```ts
type Grammar = {
    rest: 'rest' // Error: "rest" is not assignable to "value"
    [key: string]: 'value'
}

// No error - shouldn't this behave the same way?
type Grammar2 = {
    rest: 'rest'
} & {
    [key: string]: 'value'
}

// Compile error - Grammar2 type is essentially unusable
const grammar2: Grammar2 = {
    rest: 'rest',
    myKey: 'value'
}
```

### 🙁 Actual behavior

* Only `Grammar` produces a compile error even though it is equivalent to `Grammar2`.
* `'rest`' cannot be assigned to the `rest` property of `Grammar2`.

### 🙂 Expected behavior

I'm not sure how this should behave.

### Additional Context

Posting this issue due to a [problem with `@types/prismjs`](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58208). A Prism `Grammar` has a `[key: string]: GrammarValue` index signature AND special properties like `rest` which are not assignable to `GrammarValue`. How can I fix this in `@types/prismjs`?

**Comment by jcalz** [comment]
Duplicate #37809
