### ISSUE TITLE
Array spread operator does not resolve type correctly (for javascript in vscode)

### ISSUE THREAD

**Issue by goestav** [microsoft/TypeScript#47462]
# Bug Report

### 🔎 Search Terms

array spread, jsdoc spread operator, spread operator type

### 🕗 Version & Regression Information

- This happens in every version I tried, I searched through the FAQ and issues for related issues.

### ⏯ Playground Link

Does not seem to occur in typescript.

### 💻 Code

```js
const mapOfStrings = new Map([["foo", "bar"]])

const arrayOfStrings = [...mapOfStrings.values()]
//    ^ should be type string[]
```

### 🙁 Actual behavior

The type shown in VSCode is `any[]` while it should be `string[]`.

- VSCode 1.63.2 (commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3)
- OS: MacOS 12.0.1 (21A559)
- Typescript 4.5.4

<img width="379" alt="wrong array spread type" src="https://user-images.githubusercontent.com/27970303/149642158-16fff6fd-1f57-45be-8b19-65e4a292b35e.png">

### 🙂 Expected behavior

The type should be `string[]` as shown below (this does work with `Array.from()`).

<img width="429" alt="const arrayOfStrings string" src="https://user-images.githubusercontent.com/27970303/149642189-36825705-2e73-412a-a47a-c3b018deefda.png">

**Comment by Josh-Cena** [comment]
Interesting, works for me both locally and in [TS playground](https://www.typescriptlang.org/play?filetype=js#code/MYewdgzgLgBAtgQwA4HkBmBlKAnAlmAcwhgF4YwBTAdxgFlkAKAbSYCI0QRWAaGVgIwTZWAXREBKAFCTQkWEOwIAnuix5CxMkwB0uxKkw58RbQDcEAGwCuFCA3EjJQA)

![image](https://user-images.githubusercontent.com/55398995/149662220-47012f84-8efa-430d-b4dd-f4ea24c598ef.png)

**Comment by goestav** [comment]
Strange, I tried running in safe mode and seems to work fine.
Just tried disabling all extensions one by one but it's still showing `any[]` type for me...
For some reason this only happens for saved files in javascript projects.

Unsaved file:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/27970303/149775586-cf6d73ab-2c36-4c0e-a0d2-e15878d752aa.png">

Saved file:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/27970303/149775725-c7fb78c9-7dd7-4e94-a61c-9300e4f374bf.png">

**Comment by RyanCavanaugh** [comment]
I can't repro this either. We'll need some specific (probably *very* specific) steps to see this

**Comment by goestav** [comment]
I tried making a test file in a different project and worked fine too...

Update as I'm typing this, it looks like an empty `jsconfig.json` caused the problem
