### ISSUE TITLE
Visual Studio 2015 Community: after reinstalling TS extension not present on the list of installed extensions

### ISSUE THREAD

**Issue by migajek** [Microsoft/TypeScript#4747]
I've had to uninstall TS 1.5.4.0 because it has crashed my VS2015 (https://github.com/Microsoft/TypeScript/issues/4238#issuecomment-139521600)
Than I had to install TypeScript 1.5.0.0 beta for VS2015 (which is - for unknown reason - the latest available extension for VS2015)
It has installed successfully and works fine, but it's not present on the list of Installed Extensions and Updates. 
Because of that, I'm not able to update it, neither did I found 1.5.4.0 installer/vsix anywhere on the Internet. 
Any chances to get that version somehow?

**Comment by migajek** [comment]
I've found http://www.microsoft.com/en-us/download/details.aspx?id=48593&WT.mc_id=DX_MVP4025064
this still doesn't resolve the problem of not-appearing on installed extensions list

**Comment by mhegazy** [comment]
what do you mean by "installed extension list"? the list in VS? TypeScript never shows there. look under Add or Remove Programs, you should find something like 
![image](https://cloud.githubusercontent.com/assets/8000722/9823148/5d7b6c84-5879-11e5-9814-e0b9159ad60c.png)
Other than the list, do you see any other issues?

**Comment by migajek** [comment]
@mhegazy I'm pretty sure I've seen it on the list of "Extensions and Updates", listed in "Installed"
Also, from TS 1.5.4 release notes  https://github.com/Microsoft/TypeScript/releases/tag/v1.5.4

> The release should be accessible through Visual Studio Extension and Updates window.

**Comment by mhegazy** [comment]
i see. but just to confirm, you have no other issues, just the missing installed extensions entry?

**Comment by mhegazy** [comment]
@yuit can you take a look

**Comment by migajek** [comment]
@mhegazy yes. syntax highlighting, intellisense, project properties "TypeScript build" tab - everything is fine.

**Comment by yuit** [comment]
@migajek sorry for very very very long overdue reply. In short, the version 1.5.0.0 beta doesn't have proper setup authorization that is why the extension page doesn't work correctly. 

The new version TypeScript 1.7 will be in the VS Gallery (this will allow you to search in the Tools-> Extensions and Updates page in VS Community) as well as [here] (http://www.microsoft.com/en-us/download/details.aspx?id=48593&WT.mc_id=DX_MVP4025064). Please let me know if you run into this again. 

Also, for your reference we have republished all previous version in VS gallery which allows you to search in the Tools-> Extensions and Updates page in VS Community.
