### ISSUE TITLE
Issue #14422 back with VS2022

### ISSUE THREAD

**Issue by v-maxson** [microsoft/TypeScript#47477]
Same with title. All projects I've attempted, even random cloned ones from Github have these issues. 

I've disabled all Extensions and changed themes just to make sure.

**Comment by DanielRosenwasser** [comment]
We need more details about your setup, TS version, extensions you might have, etc.

**Comment by gam03** [comment]
I'm running TS 4.5.4. The only extension I did have was Codemaid, which I disabled and uninstalled just to see if that's what was causing the issue. I've also attempting running VS with Admin privileges to no avail. 

Keywords (var, let, const, class, import, etc.) are all colored blue, and strings are colored brown. That's the extent of the highlighting, everything else shows as white. However, when hovering over things (shown below) the highlighting seems to work perfectly. 
![image](https://user-images.githubusercontent.com/93727813/150062699-31fed710-ef2b-499d-b158-993a09b366f8.png)

For reference, here's the same statement with proper highlighting in VSCode.
![image](https://user-images.githubusercontent.com/93727813/150062956-9317f6c2-170b-4ed5-a258-5905cb415dae.png)

**Comment by DanielRosenwasser** [comment]
@minestarks is there a good way to diagnose this? I know that similar bugs that cause TSServer to crash on certain commands will break syntax highlighting. Is there at least a workaround to enable the TmLanguage highlighter for @gam03 in the meantime?

**Comment by minestarks** [comment]
@gam03 try unchecking the Tools->Options->Environment->Preview Features->Faster Syntax Highlighting for JavaScript/TypeScript option.

![image](https://user-images.githubusercontent.com/16928427/154576629-7e69fde9-2fef-474e-b458-105fbf731ca0.png)

**Comment by gam03** [comment]
That option doesn't seem to be there on version 17.1.0.

![image](https://user-images.githubusercontent.com/93727813/155449915-336d0b18-981c-4445-88f1-9b77f2fd45a0.png)

**Comment by minestarks** [comment]
@gam03  my bad, I think that option is only available in VS Preview. You can try setting the registry key directly to turn this off. From the Developer Command Prompt that corresponds to your VS install, you can run:

```
vsregedit set local HKLM FeatureFlags\JavaScript\LanguageService\ServerSyntacticClassification Value dword 0
```
