### ISSUE TITLE
Document type of HTML elements in .html files

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#47474]
# Suggestion

## 🔍 Search Terms

dom html types 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

I want to make a custom JSX transformer that just returns strings.
I want to export the types the JSX module needs.
I want to map over the attribute types you see in .html files.
But I can't find these things.
They are mysterious and hidden from me.
Can you document them?
And export them if needed?

## 💻 Use Cases

See above.

**Comment by sdegutis** [comment]
More details:

I have created these types:

```ts
export type IntrinsicElements = {
  [Tag in keyof HTMLElementTagNameMap]: (
    { [Attr in keyof Omit<HTMLElementTagNameMap[Tag], 'children' | 'toString'>]?: string }
    & { children?: any, class?: string }
  );
};

export type Element = string;
```

However, this is not exactly the same type as what .html files offer. There are two obvious differences:

1. `className` is offered instead of `class` so I have to manually add this in here
2. `style` is a Style object instead of a string; which also means I don't get VS Code's super great auto-completion inside the style-string

**Comment by Josh-Cena** [comment]
It seems everyone is confused, because how would you actually _use_ it?

- `class` is a reserved word in JS, so everywhere you refer to it in JS, it's `className`. It's the same for JSX and the native [`Element.className`](https://developer.mozilla.org/en-US/docs/Web/API/Element/className).
- How would you get auto-complete if you are in a string anyways?

**Comment by sdegutis** [comment]
@Josh-Cena (a) it's just a key in attrs; (b) VS Code already does this in HTML mode

**Comment by fatcerberus** [comment]
What VS Code does in HTML files has nothing to do with TypeScript.  The types you seem to be looking for aren't hidden from you; they just don't exist.

**Comment by RyanCavanaugh** [comment]
You would really need to make some kind of codegen tool to make this work ergonomically.

For CSS string completions, I would recommend using a VS Code or TypeScript language service plugin. We're not in a position to be providing that kind of data.

**Comment by sdegutis** [comment]
Thanks @RyanCavanaugh. This is one of the few missing things that would make the new TypeScript web framework [Novo Cantico](https://www.novocantico.org/) better, since right now it has nothing close to VS Code's `.html` convenient support for HTML attributes. My plan based on your advice is to somehow pre-generate a `.d.ts` file to include into the framework itself.
