### ISSUE TITLE
Template literal type is lost when used as generic

### ISSUE THREAD

**Issue by vs-cristian** [microsoft/TypeScript#47475]
# Bug Report

### 🔎 Search Terms

template string literal lost generic

### 🕗 Version & Regression Information

- Reproduced on version 4.5.4/Nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgSgVQCJQLxQOQGMBOECGwEGUAPpnvgCYnkYCuYVhxZmVEANhERgFB9QkKHAgBnAPacAbhBwAeAIJZgASwkA7MVAgAPIhqraxwHKo0BzAHxoRELBJxV5AAwAkAb2VrNYgL6ikjJyLgA0UAAUAJRoNgAKOBIAtqpiEPL0GgDWGhIA7hpWVgJYnPhi2vDIgVKyOFCqSWDcSRAawNo1wQpVSDYefFBQuAREXXW20bFQCcmpEAB0eEGy0YNQHNxj4rVykzGo8YkpaUs7wWtDlFTje+hThzPH82crEJdQjMzbb-X3B0c5qdlrs1n4Sr5gMNKEQABL4QzcP5QJQqdRaHT6NpGKAmMyWKwREHdABcdl+qJ8WisAKgAyGAHoGcMJBwGk0Wm1gIR0XxwXwRix4Yi5BENBA8rBEEhbjholEgA)

### 💻 Code

```ts
type CRUD = 'create' | 'read' | 'update' | 'delete'

type Resolver<Actions extends string> = Record<`${Actions}Resolver`, () => Promise<unknown>>

class CRUDResolver implements Resolver<CRUD> {
  createResolver = () => Promise.resolve()
  deleteResolver = () => Promise.resolve()
  readResolver = () => Promise.resolve()
  updateResolver = () => Promise.resolve()
}

const createHandler = <Actions extends string>(resolver: Resolver<Actions>) => {
  // code implementation
}

createHandler(new CRUDResolver())
```

### 🙁 Actual behavior

`Actions` generic on `createHandler` function is lost when used as template literal type (fallback to `string` type).

### 🙂 Expected behavior

`createHandler` function should infer generic `Actions` type from parameter.

**Comment by RyanCavanaugh** [comment]
The critical thing to note here is that `implements` clauses don't do anything except check that you fulfilled the stated contract. Nothing else. So an equivalent program (shortened) is
```ts
type CRUD = 'create' | 'read';
type Resolver<Actions extends string> = Record<`${Actions}Resolver`, () => Promise<unknown>>
class CRUDResolver {
  createResolver = () => Promise.resolve()
  deleteResolver = () => Promise.resolve()
}
const createHandler = <Actions extends string>(resolver: Resolver<Actions>) => {
}

createHandler(new CRUDResolver());
```
There's no inference rule that says "Do reverse string interpolation matching on all keys to try to work backwards to possible index signature key". *Maybe* that would be desirable but this is the first example I've heard of someone wanting it. There are better ways to write this function signature - either it doesn't need to be generic (as would seem to be the case), or the ways in which it would benefit from genericness would allow for a more straightforward inference source.
