### ISSUE TITLE
Need help with my windows subsscription

### ISSUE THREAD

**Issue by SleepyPanda44** [microsoft/TypeScript#47485]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by SleepyPanda44** [comment]
It keeps saying I have windowss 7 but I should have windows 10 and this all stemed from the windows insider program trying to upgrade to 11 and it crashed my computer. I have lost everything brought it back with windows 7 and now I stuck there.

**Comment by fatcerberus** [comment]
This is not a Windows support forum.

**Comment by SleepyPanda44** [comment]
My issue is scanning my computer and how do I build the computer back to where it used to be. I have lost all files memory or anything.

**Comment by xiBread** [comment]
https://support.microsoft.com/en-us/windows

**Comment by fatcerberus** [comment]
You're not going to get help for that here.  This is the Git repository for TypeScript, a programming language.  Nobody here is going to help you fix your Windows installation.

**Comment by RyanCavanaugh** [comment]
Sorry to hear you're having problems with this, but this form isn't a place where we're able to provide support for that. It looks like https://github.com/microsoft/TypeScript/issues/47485#issuecomment-1015003465 provided the right link. Thanks!
