### ISSUE TITLE
IntelliSense should suggest all possible object properties for overloaded function

### ISSUE THREAD

**Issue by leoriviera** [microsoft/TypeScript#47498]
# Bug Report

### 🔎 Search Terms

**union of types on function overload**
**function overloading not showing arguments in object with intellisense**

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, including 4.5.4 and the nightly, and I reviewed the FAQ for entries about function overloading.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/C4TwDgpgBAGlC8UDeAoK6oEMBcUB2ArgLYBGEATgNwoC+1KokUAmgslGhjvsWVZ+hK4AzsHIBLPAHNqdFCgBmBPAGNg4gPZ4oCgBSZyU4bhgBKXADcN4gCbUlq9Vp37DxluahXb9B2s3aegZGJlAAPh5INPJ6qBhYuADstKZAA)

### 💻 Code

```ts
type X = {
    a: number;
};

type Y = { 
    a: number;
    b: string;
};

function f(args: X): void;
function f(args: Y): void;

function f(args: X | Y){}

f({
    a: 7,
    |
})
```

Trigger completions at `|`

### 🙁 Actual behavior

No further completion suggestions are returned.

### 🙂 Expected behavior

A suggestion for both `b` should be returned as that is a valid option if `args` is of type `Y`.

**Comment by MartinJohns** [comment]
Related, or perhaps even a duplicate: #47227

You don't get any further completions because you already have a valid object.

**Comment by leoriviera** [comment]
> Related, or perhaps even a duplicate: #47227
> 
> You don't get any further completions because you already have a valid object.

I did think that would be the case, but it does feel like a bit of an odd behaviour to have as you _could_ have another valid object with the `b` as a property.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior (as in, it used to work this way and now it doesn't) - people didn't like when "extra" properties showed up in the list, especially in cases where there was an obvious discriminant argument earlier in the argument list.
