### ISSUE TITLE
Subtyping is not a transitive relation

### ISSUE THREAD

**Issue by masaeedu** [microsoft/TypeScript#47499]
Sorry about not filling out all the forms, not really using TypeScript actively and don't feel like doing that, but I was surprised by this and thought I'd post on the off chance that you would be too.

```typescript
type x = <a extends string | boolean>(a: a) => a extends string ? string : a extends boolean ? boolean : a extends string | boolean ? string | boolean : TypeError
type y
  = ((a: string) => string)
  & ((a: boolean) => boolean)
  & ((a: string | boolean) => string | boolean)
type z = {
  (a: string): string
  (a: boolean): boolean
  (a: string | boolean): string | boolean
}

type isSubtypeOf<a, b> = a extends b ? true : false

type xIsSubtypeOfy = isSubtypeOf<x, y> // true
type yIsSubtypeOfz = isSubtypeOf<y, z> // true
type xIsSubtypeOfz = isSubtypeOf<x, z> // false
```

Here's a playground link: https://www.typescriptlang.org/play?#code/C4TwDgpgBAHlC8UA8BDKEbAgOwCYGcp9gAnAS2wHMoAfKAIwHtGAbCFbAPgAoUAuKCgCUCToPSYcBIqQrUA-DPJUoAtBix5CTVu2xRFOth1XiNUwsWXU6RvQaVzaDZsf0CAKuAgBREiUYSAChQSCgQIKgEKG5eASs5EXgxBKohSKgAMhi4l10OJLE7Aozs2P5HFVtXPULKmzy3dNDoAC9ogG8M3NTKIXjZKm6K4ux+xr1hgetnUfHe2ZqOIIBfIJDvKDJ8AGUAV3oWgHkAM1QAGgYxRHVJLQYHUj3oAROUFnwIdZbYAEldg7HE4gaLbfaHbynJAwS4gTgbMIgf7goHtRBgwGQs4gS6teE-GDIzGQU5orYAiEks4wqB4oA

**Comment by jcalz** [comment]
https://github.com/microsoft/TypeScript/issues/42479

https://github.com/microsoft/TypeScript/issues/47331#issuecomment-1010457038

**Comment by masaeedu** [comment]
@jcalz Cool, thanks for the pointer.
