### ISSUE TITLE
AbortController.abort is missing parameter support

### ISSUE THREAD

**Issue by laurenzhonauer** [microsoft/TypeScript#47505]
# lib Update Request

## Configuration Check

My compilation *target* is `es5` and my *lib* is `["dom", "dom.iterable", "esnext"]`. (But i think that does not matter here)

## Missing / Incorrect Definition

[Abort Controller](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L1900-L1909).abort() in lib.dom.d.ts does not accept a `reason` parameter.

[Abort Controller MDN Description](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort) mentions that this `reason` is already supported by browsers. 

It would be quite handy to have this in place because it would be possible to set a timeout to api calls (just one example) and then get a custom error object thrown in case the request takes too long.

The Error Parameter bellow `controller.abort(new Error("This call takes too long"));` would not work with the current implementation. Instead its only possible to abort like `controller.abort()` and then get a "standard" abort error thrown.

## Sample Code

```
const controller = new AbortController();
const timeoutId = setTimeout(() => controller.abort(new Error("This call takes too long"), 10000);

const request = await fetch(`www.some.api`, {
    signal: controller.signal,
  });

  clearTimeout(timeoutId);
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort

[Same Issue in [@types/node]](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58273)

**Comment by johannpinson** [comment]
Hello @laurenzhonauer

For your information, it looks to be fixed with the `4.6` release (feb 2022).


The latest `v4.6.4` has the `reason` parameter
https://github.com/microsoft/TypeScript/blob/v4.6.4/lib/lib.dom.d.ts#L1895-L1906

**Comment by douglascayers** [comment]
Thanks @johannpinson -- although I'm on that version of typescript, in my project the type inference is coming from [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fe81c93cc2b5e07879aaba1af3b1ef744e46e331/types/node/globals.d.ts#L56) which doesn't yet have the `reason` parameter.

Any thoughts? Thanks

**Comment by douglascayers** [comment]
Although typescript v4.6.4 updated the AbortController.abort method to accept a `reason` parameter, the AbortSignal interface was not updated to expose the `reason` property =/

https://github.com/microsoft/TypeScript/blob/v4.6.4/lib/lib.dom.d.ts#L1913-L1921

**Comment by tonivj5** [comment]
I think this issue is resolved, isn't it?

**Comment by RyanCavanaugh** [comment]
Seems so. Thanks!

**Comment by eden-eitani** [comment]
@douglascayers did you find another solution?
