### ISSUE TITLE
Type narrowing does not properly narrow type of generic class instance

### ISSUE THREAD

**Issue by caffeinewriter** [microsoft/TypeScript#47502]
# Bug Report

### 🔎 Search Terms

code path, type narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing

### ⏯ Playground Link

[TypeScript Nightly](https://www.typescriptlang.org/play?ts=next#code/C4TwDgpgBA4hB2EBOBLAxgYQDYEMDOeUAvFIgO5QAUAdLTkgOZ4BcUO8IAlMQHxscBuAFBCIADzAB7JMCgATCADMcAVyyy0uAlADKKeAywRgk+ADEcaE0hAAeACpRxwBHMJxEqTFrx8A3kJQQVBIEDhyplggUADE+njA7GgQ2PgsUPbCwbHxifDJAPysAJLwCUkQ9uAQDjxZwWimCUgqVtKUuRWpBKz23AHZ2cAAFih41HFlecndhCSd+Sk+9UEAvoHBDMal5YuUkmDAKE1FUBhNwC1tSAAK9DgAtsbIeLWcJVMVVZC1UAODQRQiioIzGEwWyWIRBIKngCkU+ggcn6GwB2SBVAAhAcjk0UWiCVARkhJBRyFAAKJIElISgAcgAcpIoBDoIpJLC5AAafhyUjMnHHMpQMAkgBuKAUcjpnFRhPWhOCoPGk12kJI5OV4M+i1m+0OQrwnBWhIA9KbdMMOVg+fBJLIAEbQTlKRHctiEFCyMj4Fk6o44Fx8lAPJ5yFCBiBRNgOyRiiBygnmqAAJQgDzj+gYRNGhCwiN5bCwWFJWZzbP0OCwIWMKiQ8BFJLkrQghBG0Dwj2gyBpibRoWAdYbWtV0wgJuyCv7tfrObBo4qJvWqyAA)
[TypeScript v4.5.4](https://www.typescriptlang.org/play?ts=4.5.4&ssl=21&ssc=1&pln=21&pc=2#code/C4TwDgpgBA4hB2EBOBLAxgYQDYEMDOeUAvFIgO5QAUAdLTkgOZ4BcUO8IAlMQHxscBuAFBCIADzAB7JMCgATCADMcAVyyy0uAlADKKeAywRgk+ADEcaE0hAAeACpRxwBHMJxEqTFrx8A3kJQQVBIEDhyplggUADE+njA7GgQ2PgsUPbCwbHxifDJAPysAJLwCUkQ9uAQDjxZwWimCUgqVtKUuRWpBKz23AHZ2cAAFih41HFlecndhCSd+Sk+9UEAvoHBDMal5YuUkmDAKE1FUBhNwC1tSAAK9DgAtsbIeLWcJVMVVZC1UAODQRQiioIzGEwWyWIRBIKngCkU+ggcn6GwB2SBVAAhAcjk0UWiCVARkhJBRyFAAKJIElISgAcgAcpIoBDoIpJLC5AAafhyUjMnHHMpQMAkgBuKAUcjpnFRhPWhOCoPGk12kJI5OV4M+i1m+0OQrwnBWhIA9KbdMMOVg+fBJLIAEbQTlKRHctiEFCyMj4Fk6o44Fx8lAPJ5yFCBiBRNgOyRiiBygnmqAAJQgDzj+gYRNGhCwiN5bCwWFJWZzbP0OCwIWMKiQ8BFJLkrQghBG0Dwj2gyBpibRoWAdYbWtV0wgJuyCv7tfrObBo4qJvWqyAA)
[TypeScript v3.3.3 \(no private fields\)](https://www.typescriptlang.org/play?ts=3.3.3#code/C4TwDgpgBA4hB2EBOBLAxgYQDYEMDOeUAvFIgO5QAUAdLTkgOZ4BcUO8IAlMQHxscBuAFBCIADzAB7JMCgATCADMcAVyyy0uAlADKKeAywRgk+ADEcaE0hAAeACpRxwBHMJxEqTFrx8A3kJQQVBIEDhyplggUPp4wOxoENj4LFD2wsEx8HEJEAD8rACS2fHwifbgEA48GcFopnFIKlbSlLGlickErPbcAZmZwAAWKHjU7bldhCQTZUk+tUEAvoHBDMbFOXOUkmDAKA0FUBgNwE0tSAAK9DgAtsbIeNWcRSW5FZDVUP0DQSiKVGGo3GbzmxCIJBU8AUin0EDkfVWv0y-yoAEJdvsGojkbioMMkJIKOQoABRJCEpCUADkADlJFktokoIpJFC5AAafhyUgMzEHbJQMCEgBuKAUcmpnCReJWeOCQLGs2ZJBJipBTPmKR2ewFeE4izxAHojbohmysDz4JJZAAjaDspRwzlsQgoWRkfCM0r7HAuHkoW73OQoP0QKJsW2SEUQGW4k1QABKEFu0f0DHxI0IWDh3LYWCwRPTmegsPgOCwIWMKiQ8CFhLkzQghGG0Dwd2gyEpceRoWANbr6uVEENmTlvertczwOHhpWSyAA)

### 💻 Code

```ts
type GenericClass = new (...args: any) => any;

export default class SingletonFactory<T extends GenericClass> {
    readonly #instanceClass: T;
    #instance?: InstanceType<T>;
    constructor(instanceClass: T) {
        this.#instanceClass = instanceClass;
    }
    getInstance(options?: ConstructorParameters<T>): InstanceType<T> {
        if (this.#instance === undefined) {
            if (!options) {
                // Error if both instance and options are undefined
                throw new Error('No instance found, and no options provided');
            }
            // Create new instance if not defined, and options are provided
            this.#instance = new this.#instanceClass(options);
            return this.#instance; // Error: Type 'InstanceType<T> | undefined' is not assignable to type 'InstanceType<T>'.
        }
        return this.#instance;
    }
}
```

### 🙁 Actual behavior

After creating a new instance of `this.#instanceClass`, TypeScript still reports the type as possibly undefined.

### 🙂 Expected behavior

After creating a new instance and assigning it to `this.#instance`, the type of `this.#instance` should narrow to only `InstanceType<T>`. A workaround can be achieved by assigning the new instance to an intermediary variable, and then returning the intermediary variable instead.

[Example playground of workaround](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBA4hB2EBOBLAxgYQDYEMDOeUAvFIgO5QAUAdLTkgOZ4BcUO8IAlMQHxscBuAFBCIADzAB7JMCgATCADMcAVyyy0uAlADKKeAywRgk+ADEcaE0hAAeACpRxwBHMJxEqTFrx8A3kJQQVBIEDhyplggUADE+njA7GgQ2PgsUPbCwbHxifDJAPysAJLwCUkQ9uAQDjxZwWimCUgqVtKUuRWpBKz23AHZ2cAAFih41HFlecndhCSd+Sk+9UEAvoHBDMal5YuUkmDAKE1FUBhNwC1tSAAK9DgAtsbIeLWcJVMVVZC1UAODQRQiioIzGEwWyWIRBIKngCkU+ggcn6GwB2SBVAAhAcjk0UWiCVARkhJBRyFAAKJIElISgAcgAcpIoBDoIpJLC5AAafhyUjMnHHMpQMAkgBuKAUcjpnFRhPWhIaFyJDzAO2m0BI5NB40muxmPn2hyFeE4K0JOvBn0WxBVautyXNBNCwBUSHgdvVFSdwQVaJdbo9lr1GvN61WQA)

Additionally, even though the type of the property is `InstanceType<T> | undefined`, other similar situations properly narrow the code path. I've created an example using `string | undefined` [here](https://www.typescriptlang.org/play?ts=4.5.4#code/MYGwhgzhAEAqCmEAuBhcVoG8BQ0-QGIIB7AW3gDEBLeEAEwH4AuaZAJyoDsBzAbm1z5gxTuwCuwJMTYAKEuQDKSDj2atlXbgEosg-PiQALKhAB0RMpRr1oAXlaWlKvnugBfAfu7wk1WnRktFnZNXX19KgAzaBkAQiMTc3krfx0ccIzoBLMLcj8bewAiZPVnQv5M8IB6KrgATwAHeGgTaE4wNjZiAHd4OiziaAADEJ4h6EjpaDZ4UjAuOng2aGJo4UXoBrAjABoswzEYGYgxECRQrjbBpa7l7f3mmaQxNk5TV30PSqeXzn3E3IpegVfAeNxAA) for comparison.

Thanks!

**Comment by RyanCavanaugh** [comment]
```ts
this.#instance = new this.#instanceClass(options);
```
The RHS of this line is `any` because the constructor types is reduced to its constraint, so no narrowing occurs.

It'd be better to define the class this way
```ts
export default class SingletonFactory<Class, Params> {
    readonly #instanceClass: { new(args: Params): Class };
    #instance!: Class;
    constructor(instanceClass: { new(args: Params): Class }) {
        this.#instanceClass = instanceClass;
    }
    getInstance(options?: Params): Class {
        if (this.#instance === undefined) {
            if (!options) {
                throw new Error('No instance found, and no options provided')
            }
            this.#instance = new this.#instanceClass(options);
            // Should not be undefined, as it was instantiated immediately above
            // Removing this line and allowing the final return produces the same error
            return this.#instance;
        }
        return this.#instance;
    }
}
```
or just not declare `#instance` optional, assuming it's reliably initialized in this codepath.
