### ISSUE TITLE
Variable still null after forEach reassignement

### ISSUE THREAD

**Issue by JPeer264** [microsoft/TypeScript#47513]
# Bug Report

### 🕗 Version & Regression Information

All versions in the playground do have this "bug" (3.3.3 - 4.6.0-dev.20220115)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/DYUwLgBAbghgTgSxgI1ALggZzIgdgcwgB8JcBXYYCAXlIuAG4AoJgbQHJ2BdAOgDMA9nACiMAMYALABRSAlDQB8EAN5MI66PCSoQNCO0wCAtrux587ZgF9ZzJmIG5DoHsAH4psRClC2gA)

### 💻 Code

```ts
let variable: string | null = null;

[''].forEach(() => {
    variable = 'some string';
});

console.log(variable)
```

### 🙁 Actual behavior

`variable` has the type `null`

### 🙂 Expected behavior

`variable` should have the type `string | null` (preferably for this usecase only `string`, but maybe even harder to tackle). I assume this happens as the variable is assigned inside the callback function. I would totally understand this decision when using non-blocking functions such as setTimeout or any async functions. But doesn't this implementation differ from what is possible in the actual runtime? I reported this as a bug because In this specific case `variable` is always a string and can never be null, instead of the given opposite.

**Comment by fatcerberus** [comment]
#9998

**Comment by IllusionMH** [comment]
And another one! Duplicate of #9998

**Comment by fatcerberus** [comment]
From TS point of view there’s no difference between your `forEach` call and a `setTimeout` call.  Both take a function, and TS doesn’t know when that function will be called.  See also https://github.com/microsoft/TypeScript/issues/11498.

**Comment by JPeer264** [comment]
Closing this in favor of duplicates. Sorry for the duplicate, but thanks for pointing this out!
