### ISSUE TITLE
Can't get (partial) union type on extended generics

### ISSUE THREAD

**Issue by rubenferreira97** [microsoft/TypeScript#47528]
# Bug Report

### 🔎 Search Terms

Generic Inference
Type Narrowing

### 🕗 Version & Regression Information
Seems to occur in every version I tried. I reviewed the FAQ about 'Generic Inference'

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgZWwAtgBbTOAbwCg44pgBnSJR4AfgC44BXJAayQQA7kgDc1AL7VqoSLEQo0WXAWJlMAUShRocUKiQATRmpLkqtekxZtuNOnQAsABgCM3RjCjIA5hMc4VwBmbiQeUgAjNAC4SQlpahgATzA8ACUbCFZgAFUkBGyAHnx9EEMTMw0APjgAXgIAbQByBmZstmaAXUb+YGSIdCbWrJzurolqbA74VC96uCKAFTKK00JzLR1oaoAKRnVybiWASnrahzgAeiu4JdSmbB8weGxMJDhfYHgVxiJMNJwd5GILuOApNJWaaseCYVxuBYHTYAOjatmALXh3TEcBkdBucAA6tB+KZMKY5MBsKgjFYIXgAIILTLtHL5QpIEqHLa6KDVHEErw+JC+OAAHzg4SiaChMzgwhJjG4TIazUwkWwzUm+NuKwMwGM6252l5cEYEHBJHBDzNRAgPAANiCGDAeFAPkK-OLJRFolBvXxBCIPvtkKphHg3khmvAjMAjDxVI16aZBncWmiOsBxnASAwTrKYfptlBuCz0eziktaqr1ZrtddbgBJJRQNjUjlwIwQJiSiDwBVQfj6BAwPOF+ZoXkAJjLozYlc5KwAZFVyCadgs1Rqtbj4kA)

### 💻 Code

```ts
export interface Schema {
  response?: unknown;
}

export interface SchemaError extends Schema {
  response: {
    401: string;
    403: number;
  };
}

type ResponseUnion<S extends Schema> = S['response'][keyof S['response']];

const test = <T extends SchemaError>(schema: T) => {
  // Typescript can get T shape and 401 type
  const a401 = schema.response['401']; 

  // Works as expected
  type A = ResponseUnion<SchemaError>; // string | number
  const works: A = 'abc';

  // T extends SchemaError so the type should return string | number | unknown (since we can't deduce [types of T['response']] here)
  const error: ResponseUnion<T> = 'abc';

  // Intersection does not work either
  const error2: ResponseUnion<T & SchemaError> = 'abc'; 
};
```

### 🙁 Actual behavior

Gives the following error `Type 'string' is not assignable to type 'ResponseUnion<T>'.`
Can't get a union of a extended generic, even if it's guaranteed (at least I think) to be of a partial extended type.

### 🙂 Expected behavior

Given a extended generic return a narrowed type like: `ResponseUnion<T> = string | number | unknown`

**Comment by RyanCavanaugh** [comment]
This is a correct error.
```ts
const test = <T extends SchemaError>(schema: T): ResponseUnion<T> => {
  // Assertion: this is OK
  const error: ResponseUnion<T> = 'abc';
  return error;
};

// Unsound: value 'abc' inhabits binding of 0 | 'def'
const m: 0 | 'def' = test({response: { 401: 'def', 403: 0 }} as const);
```

**Comment by rubenferreira97** [comment]
Sorry, I couldn't follow that example. `ResponseUnion<T>` returns the types of the keys of `response` of a given `T`. Your example seems to return the keys. I think `test` will never return `0 | 'def'`, it will return types, something like `string | number`.

```TS
const test = <T extends SchemaError>(schema: T): ResponseUnion<T> => {
  const error: ResponseUnion<T> = 'abc'; // error is a String, since T extends SchemaError 
  return error; // I am returning a string, it complies to string | number
};

// Since I am supplying a T that extends SchemaError, it shouldn't be always true that ResponseUnion<T> returns a union of string | number?
const m: string | number = test({response: { 401: 'def', 403: 0 }} as const); // Supplying a T that extends SchemaError
```
