### ISSUE TITLE
Cannot use local value when merged with type-only alias

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#47536]
# Bug Report

### 🔎 Search Terms

cannot be used as a value import type merge 

### 🕗 Version & Regression Information

All versions since `import type`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAQsA5gSQDsYB5MGYCQgZzgF84AzKCEOAIkevYG4BYAFCCAxlWrwcBYmQpi4AXgx1+QgZKKlylGoKA)

### 💻 Code

```ts
import type { BigIntOptions } from "fs";

const BigIntOptions = {};

BigIntOptions
```

### 🙁 Actual behavior

`'BigIntOptions' cannot be used as a value because it was imported using 'import type'.(1361)`

### 🙂 Expected behavior

No error

**Comment by fatcerberus** [comment]
fwiw, https://github.com/microsoft/TypeScript/issues/46889 seems to have reached a conclusion that this not a bug.

Also, the error message quoted makes me think it was intentional?

**Comment by andrewbranch** [comment]
I think that’s completely different—aliases don’t merge with other aliases, but they will merge with locals.

**Comment by andrewbranch** [comment]
As the person who wrote type-only imports, it definitely wasn’t intentional 😁
