### ISSUE TITLE
Wrong module resolution on import in Node

### ISSUE THREAD

**Issue by aMediocreDad** [microsoft/TypeScript#47533]
# Bug Report

When importing a module using node, the `exports` field is what node references if it exists. The field is well documented here: https://nodejs.org/api/packages.html#package-entry-points and here: https://nodejs.org/api/packages.html#dual-commonjses-module-packages

When in an environment that is: `"type" : "module"`. Using the `import {} from "foo"` syntax node resolves that import using the `exports` field with a fallback to the `main` field. However, Typescript seems to require an extra setting in `tsconfig.json` with `"moduleResolution" : "nodenext"` to ellicit the same behaviour. 

This quickly becomes hairy when attempting to use the Typescript/Javascript LSP in a Javascript project where the equivalent (but not true equivalent) is `"module": "nodenext"` in `jsconfig.json` (jsconfig does not seem to support `"moduleResolution" : "nodenext". Using the equivalent field in `jsconfig` creates other problems. For example. Or any instance where the exported esm and cjs packages have differences.

On top of this, it seems that Typescript only recognizes the `node` or `default` property of the `exports` field.
 
### 🔎 Search Terms

exports, moduleResolution, import, require, jsconfig

### 🕗 Version & Regression Information

4.5.4, 4.6.0-dev.20220117

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about moduleResolution

### ⏯ Playground Link

Not relevant

### 💻 Code

```js
// ./node_modules/myESMpackage/src/index.js
export { someTypedFunctionFromNodeModules as function } from "some-forwarded-library-with-types"

// ./node_modules/myESMpackage/package.json
{
  "type" : "module", 
  "main" : "dist/index.cjs", // <- For legacy node import <v12.x
  "exports" : {
    "import" : "./dist/index.mjs", // <- Maps to import in a module environment
    "require": "./dist/index.cjs", // <- Maps to require() in a commonjs environment
    "default": "./dist/index.mjs" // <- Future proofing assuming browser support
  }
}

//  ./package.json
{
  "type" : "module"
  ...
}

```

### 🙁 Actual behavior

**Assuming the setup above**

```js
import { function } from 'myESMpackage' // <- dist/index.cjs

function({ /* Intellisense does not kick in here because the CJS is bundled by necessity losing the types from the forwarded library */ })

```

### 🙂 Expected behavior

```js
import { function } from 'myESMpackage' // <- dist/index.mjs

function({ /* Intellisense from the forwarded library is available here */ })

```

### Workarounds

It is possible for the package forwarding the typed library to set `main` to `dist/index.mjs`. But this shouldn't be required. The bug here is that Typescript does not seem to honor the `exports` field by default if it exists, and the `import`, `required` properties if they exist. Primary behaviour should be to look for these with a fallback to `main`. And the `moduleResolution`/`module` fields in `tsconfig`/`jsconfig` should be optional and used in order to override the above.

 **Addendum**
A lot of the issues I have seen while researching this issue mention the top-level `module` field as something Typescript should honor when doing module resolution. This would be contrary to expectation, since Node ignores this field when doing module resolution and Typescript should be expected to follow Node's conventions in this and not the bundlers'/compilers'.

**Comment by weswigham** [comment]
If I'm getting you right, you're just asking that `module: commonjs` read export maps like `module: nodenext` does, right?

**Comment by aMediocreDad** [comment]
If by "commonjs" you mean Typescript's default behaviour, then yes. 

I would expect Typescript to be able to convert a Javascript node app to a Typescript node app without having to change alter the default moduleResolution of Typescript (as it should behave as close Javascript's module resolution in Node as possible. Especially since `exports` is now where you define package exports.

**Comment by weswigham** [comment]
See, the issue there is that that's a breaking change for existing TS projects (that much is obvious from how many reports we get about people swapping to nodenext and having some degree of confusion as to what package json fields need to be present to accomplish what they want (since many packages 'fallback' entry points work for TS but export map entry points _don't_).

I can say we _might_ change the default `module` setting to one of the new `node` specific settings, but not in the very near future, I don't think; we'd have to fully release it (rather than it just being nightly only) and see its adoption levels rise first.

**Comment by aMediocreDad** [comment]
Sorry it's taken me some time to get back to this. Is it possible that Typescript is contributing to this confusion?

> Note: I am coming at this from the viewpoint of a VS Code user who likes to have autocomplete/intellisense in JS from imported modules.

The way I see it people need to misuse the `main` field in their `package.json` to emit types that can get picked up by the Typescript Language Server. 

The rationale is as follows: A CJS bundle usually doesn't include types/comments (like JSDoc), this means the need for including a `type` field in the `package.json` which isn't always possible if your project is in JS and use JSDoc. The alternative is to set `main` to the `src`-file entrypoint (what many point the bundler specific `module` to), which is entirely wrong as `main` is the only field used by legacy node versions < 12. So you would be nuking compatibility by pointing to an ESM module there.

Any changes to this will of course be a breaking change, but that is only because the current status quo is perpetuating the wrong use of the `main` and `exports` fields and contributing to misunderstanding in the community at large.

**Comment by aMediocreDad** [comment]
It seems Typescript 4.7 closes out this request: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/

I will create an updated and more specific issue should I notice anything.

Thanks for your hard work!
