### ISSUE TITLE
typeof generic function with a specific template type should be possible

### ISSUE THREAD

**Issue by brandon942** [microsoft/TypeScript#47542]
# Suggestion

## ⭐ Suggestion

```js
function func<T>(a: T) { return a }
var value : ReturnType<typeof func<number>> // should be possible
```
Related to #37181 but even simpler - have a concrete type instead of a template type.
I wonder how this simple thing is not possible.

## 💻 Use Cases

```js
function getValue<T>() {
	var a : T
	return { a: a }
}
var value
value = getValue<number>() // assigned later lazily
value // any (no typehint)
```

Currently it is impossible to have a variable be of a specific type that involves a generic function.

```js
var value : ReturnType<typeof getValue<number>> // Error!
```

One has to create extra functions as a workaround, just to get a typehint for a variable:

```js
// A workaround
function getValue<T>() {
	var a : T
	return { a: a }
}
function getValue_number() { // Extra function workaround just to avoid template syntax in typeof!
	return getValue<number>()
}
var value : ReturnType<typeof getValue_number>
// ...
value = getValue<number>() // assigned later
value // { a: number } - OK
```
## 🔍 Search Terms

typeof generic function

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
Duplicate #40542 ? I'm not sure what distinguishes this, #40542, and #37181 - they all seem to be the same thing IMO

**Comment by brandon942** [comment]
> I'm not sure what distinguishes this, #40542, and #37181
Probably the expected operator precedence of typeof.  
This opened issue focuses on the simpler case for which there is even a workaround. Defining a concrete type from a referenced generic function.  
I don't see a workaround for the template type version.
