### ISSUE TITLE
Including an argument in a function passed to a generic function breaks type inference

### ISSUE THREAD

**Issue by Pinpickle** [microsoft/TypeScript#47547]
# Bug Report

Including an argument in a function passed to a generic function under certain circumstances breaks type inference.

### 🔎 Search Terms

inference function parameter 3.8

### 🕗 Version & Regression Information

- This changed between versions 3.7.5 and 3.8.3

### ⏯ Playground Link

[Playground link with relevant code (on nightly)](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/FASwdgLgpgTgZgQwMZQAQHkAOEQHswDOAPACoBKUEArjGADSokCSYmVEAfKgN7Cr+pwbCAC5GLYXT4CkCADZIqchNDEAKIezHNW7AJSoAvF3KUaYANzAAvsGBJ8BCKgAmuEgAtwAcyOpSFNS0DDrCHGrelFg4juoIMN5iVGAA1mC4AO5gBsYY2HiEAWbB4rqcOVy8AqgOhM7cNfKKytAMms7WfpEQ0QUEamBKcnpW1TDFYI0KSipQGmUjNnYA9MuoEACemGggBIJgcLDjLjW4MONIEHIbqAh7vY5EAMwM4whuYNeoANoAjAwNN4fL4QDK4MRPVDWAC6HGAbk8PjUagqqDUVQE7TEfwB6zBEKh0Nue1qTik1Vk0xaUHU31xoNwhNRGOq-HGQUmDNGAls1j0ehWa08aHwXxcIDgh3GYBQgj2EA8aEw4wIUBlIrgt0m8W8VAAtmqIAA6RhbHZ7cBS47EvIxQrJNKZeioB3pLJwhFeMDeZE61Ho6T8LE-ABE+CgIfp+NQkJhNtJEHJMiaM1UaLpPDxjJhzMDrPZ5iz3P4vP5wCAA)

If you change to 3.7.5, the inference will work

### 💻 Code

```ts
interface Options<TReturn, TInput> {
    input: TInput,
    calculate: (input: TInput) => TReturn;
}

const doThing = <TReturn, TInput>(getOptions: (arg: unknown) => Options<TReturn, TInput>) => {
    const { calculate, input } = getOptions(null);
    return calculate(input);
}

// type is inferred correctly as Options<3, readonly [1, { readonly two: 3 }]>
doThing(() => ({
    input: [1, { two: 3 }] as const,
    calculate: ([, { two }]) => {
        return two;
    }
}))

// The only difference is the presence of an argument. Type is inferred as Options<unknown, unknown>
doThing((arg) => ({
    input: ["one", { two: 3 }] as const,
    calculate: ([, { two }]) => {
        return two;
    }
}))
```

### 🙁 Actual behavior

The second invocation of `doThing` has an inferred options type of `Options<unknown, unknown>`

### 🙂 Expected behavior

The second invocation of `doThing` to infer as `Options<3, readonly [1, { readonly two: 3 }]>`, just like the first. The _only_ difference between the invocations is the presence of an (unused) argument in the function.

**Comment by RyanCavanaugh** [comment]
Tracking at #47599

**Comment by Pinpickle** [comment]
Thanks @RyanCavanaugh! Do you have any suggested workarounds for making this particular example work without adding explicit type parameters?

**Comment by RyanCavanaugh** [comment]
I'd add either a type annotation on the parameter, or provide an explicit type argument, whichever was shorter or best communicated my intent
