### ISSUE TITLE
Indexed Access Types don't play well with overloads

### ISSUE THREAD

**Issue by eamodio** [microsoft/TypeScript#47540]
# Bug Report

For type-safety, I often use Indexed Access Types in my decorators. But if the method being decorated has overloads, the IAT seems to resolve to the overload definition _above_ the decorator, rather than the actual implementation _below_ the decorator. I also tried "indexing" into the IAT to see if I could pick a specific overload, but that doesn't seem possible.

Because the IAT doesn't resolve to the implementation, it can lead to bugs where things look type-safe but will fail at runtime -- see my code below.

### 🔎 Search Terms

Indexed Access Types, overloads

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwIZQKYB4AqiMAemYAJgM6IAUAdLagE7IBciqYAngJSIC8AfKw59K9DGTgAbAG4Z6AfhY06jMiwAKDVAFsMmemVx9u-RGSj0YYZNwDeAWABQASFFQQ9JJSgNkulm3YAGkQAawx2FjMLK2CSMQgLAAcoOHp1ejhE2Sh2ABF4pJT6YwF7B0QKxDiyBJhk1OopVAkQDF5EUEhYBCooAAsYVUEgxFpqHyGAgG0AXVtHSsqIBHEJDGoJOGQRMUkZeWolQ4nWCg16bV1ZAxwjTk4AbgXKgF9HJxenhzeHRwgJVBkCgAMTgcEQZQqACMGJRUApTOZLMhglCEVFkZwWFI4DASF9obDUCwwCAtFDZKiSWSKcVsbj8YgAPRMxBYAC0iH6bVBcCmAHIYfR+TNTBgMFoKClECAyG1+oNEHB9ptUCRngABNCYLC8gVCkXCOGokqsagpADKSKslG4AGpEFDzXArdFtvdnkK4ZFrchEAAfRCk8myAOOsFrNhh8BxYCWDAkKmIt1h4O0sNQiMYKOBmMYONgBNYxA4vEQ54-H5-FZQDpg9qFgDuiF5tq+wDB1C9-NQ-OCgv5j0cHbgXdhj2ZrI5iCmAFEAErzmYsADCbDAcFrojViESGSy9FgYiVwBlpHz8ZIVG3JGRiH5lt9g8cjiAA)
      
### 💻 Code

```ts
function gate<T extends (...arg: any) => any>(resolver?: (...args: Parameters<T>) => string) {
	return (target: any, key: string, descriptor: PropertyDescriptor) => {
    descriptor.value = function (this: any, ...args: any[]) {
      console.log(resolver?.(...(args as Parameters<T>)));
    }
	};
}

class Foo {
  bar(a?: string, b?: string): void;
  bar(a: number, b: number): void; // <- the Foo['bar'] seems to use this overload
  @gate<Foo['bar']>((a, b) => a.toString() + b.toString())
  bar(a: string | number | boolean | undefined, b: string | number | boolean | undefined): void {
  }
}

const foo = new Foo();
foo.bar('a', 'b');
foo.bar(); // <- [ERR]: Cannot read properties of undefined (reading 'toString')


```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
function gate(resolver) {
    return (target, key, descriptor) => {
        descriptor.value = function (...args) {
            console.log(resolver === null || resolver === void 0 ? void 0 : resolver(...args));
        };
    };
}
class Foo {
    bar(a, b) {
    }
}
__decorate([
    gate((a, b) => a.toString() + b.toString()),
    __metadata("design:type", Function),
    __metadata("design:paramtypes", [Object, Object]),
    __metadata("design:returntype", void 0)
], Foo.prototype, "bar", null);
const foo = new Foo();
foo.bar('a', 'b');
foo.bar(); // <- [ERR]: Cannot read properties of undefined (reading 'toString')

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

### 🙁 Actual behavior

No type error, but runtime error

### 🙂 Expected behavior

Type error

**Comment by fatcerberus** [comment]
The implementation signature for a set of overloads is always invisible from outside the function, by design.  It’s only used for type checking the implementation itself.

**Comment by MartinJohns** [comment]
> // <- the Foo['bar'] seems to use this overload

This is not correct, and the playground demonstrates this:

![image](https://user-images.githubusercontent.com/5269069/150486963-b1ad6056-786d-4f2f-9fbf-1b8ac7fdcf52.png)

The issue is not with the indexer, but the usage of `Parameters<T>`. This is a conditional type using inference, and inference in conditional types does not support overloads. The [documentation](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types) explicitly mentions that inference is made from the *last* signature.

**Comment by eamodio** [comment]
I guess it is inferencing from the _last public_ signature -- not the _last_ one. Is there any way to get this to work?

**Comment by fatcerberus** [comment]
No; you can't access the implementation signature from outside the function.

**Comment by MartinJohns** [comment]
Add another signature, if you want another signature.
