### ISSUE TITLE
Wrong type file generated when using baseURL or local package json file

### ISSUE THREAD

**Issue by ImanMh** [microsoft/TypeScript#47557]
# Bug Report

Minimal example: https://github.com/ImanMh/ts-import-types-issue
I have used TSDX to initiate this project. You can find 2 commits. The first one is the initialization commit and it works fine. Ignore that. The second one is an example where consumers of this package can import the two function (sum and concat) and happily use it, but the types don't work due to issues in the generated d.ts file.

These are 2 separate problems but I guessed maybe the are being originated from the same source. You can link this package locally and see that the types are not working.

### 🔎 Search Terms

wrong type file baseURL, can't resolve import type file,

### 🕗 Version & Regression Information

v4.5.5

### 💻 Code

Please check 6 lines of my commit: [commit changes](https://github.com/ImanMh/ts-import-types-issue/commit/db6ad575435640423a13f7311c702971f86650f1)

### 🙁 Actual behavior

 Here is an output of the generated type file:

```
import { sum } from 'math/sum';
import { concat } from 'string/concat';
export { sum, concat };
```

### 🙂 Expected behavior

If I want to make this work in other consumer projects, I should change the type file like this:

```
import { sum } from './math/sum/sum';
import { concat } from './string/concat';
export { sum, concat };
```

Then it works perfectly. The issue with the ./ at the beginning of files appear when you use "baseUrl": "./src" in your tsconfig. If I want to remove it then I'll end up with ugly paths everywhere.

The issue with './math/sum' appears when I add a package.json file inside sum directory. here is the content of the package.json file:

```
{
  "main": "sum.ts"
}
```
In the output file this package.json file is removed after build so there is no way for the compiler to know where to find the sum.ts .

**Comment by RyanCavanaugh** [comment]
We don't rewrite the import paths here as part of `.d.ts` emit to try to undo the baseUrl setting. If your project has a baseUrl but the consuming project doesn't, you'll need to "fix up" the paths as a post-build according to whatever the actual runtime situation is (which we have no way of knowing)

**Comment by ImanMh** [comment]
> We don't rewrite the import paths here as part of `.d.ts` emit to try to undo the baseUrl setting. If your project has a baseUrl but the consuming project doesn't, you'll need to "fix up" the paths as a post-build according to whatever the actual runtime situation is (which we have no way of knowing)

Hey Ryan, thanks for your answer. I though it's a bug. The base URL is inside my tsconfig file. When you said we have no way of knowing, you meant no way of knowing about the base URL or about the difference between consumer project and the TS until(my repo) package?

And what about the package JSON issue?

And by fixing the paths post build, is there a tool for such purposes or you mean I got to craft something. Just giving me a name will solve my problem.

Thanks for the support by the way.

**Comment by ImanMh** [comment]
I guess you mean something like this: https://www.npmjs.com/package/typescript-transform-paths

**Comment by ImanMh** [comment]
@RyanCavanaugh Hey man the more I read about this the harder it gets for me to understand this. Seems like people had issues with the almost the same topic. Here an [interesting comment](https://github.com/microsoft/TypeScript/issues/10866#issuecomment-400796690).

This is actually my question as well. If baseURL option break the .d.ts generation, Why do we even have it? I may be able to fix my problems by transforming paths, but it's probably no ideal. I totally did not understand why do you think appending baseURL and package.json.main paths should not be part of TS compiler at all. I'm just asking to make sure I'm not missing an important point here.
