### ISSUE TITLE
Inlay hints suppression should be case insensitive and look within variable names

### ISSUE THREAD

**Issue by Johnhersh** [microsoft/TypeScript#47562]
# Suggestion
## 🔍 Search Terms

* inlay hints
* suppression

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow suppression of inlay hints to be a bit smarter. Case insensitive and looking within variable names would be nice.

## 📃 Motivating Example

Often times the variable name matches the type, but is just a different case so I get the same name twice.
![149641846-c3252031-3acd-4834-a53e-6e6ef27e0506](https://user-images.githubusercontent.com/20746719/150659345-3e73400c-f7eb-407b-8e00-93d99047b51c.png)

But also sometimes the name of a parameter is contained within the name of the variable:
![149641867-12cdaa5e-97ec-493d-88b1-bca3731af850](https://user-images.githubusercontent.com/20746719/150659357-9ca6103e-47a2-4d77-888a-22b6869a988f.png)

As it is right now I get a lot of repetition which makes things more difficult to read.

## 💻 Use Cases

I think the example covers the use cases, or vice versa.

**Comment by RyanCavanaugh** [comment]
@mjbvz I think this would be pretty easy for us or VS Code to do. How does it fit into the overall vision of how hints should work?

**Comment by Johnhersh** [comment]
> @mjbvz I think this would be pretty easy for us or VS Code to do. How does it fit into the overall vision of how hints should work?

Note that I submitted this in the VSCode repo initially and was told this is a typescript feature so was sent here.

**Comment by mjbvz** [comment]
@RyanCavanaugh We already suppress some inlay hints on the TS side (specifically we don't show the hint when the argument name matches the parameter name) so I'd prefer to keep the logic there so it can be consistent between different clients

We on VS Code don't have general advice for specific cases like this. Instead we leave it up to each language to decide what makes sense

**Comment by huytd** [comment]
In the preferences, we have the `includeInlayParameterNameHintsWhenArgumentMatchesName` to handle the case where we pass a variable as a param, which matches the name of the argument. I think it can also be used for some of the cases like the second example too.

I think for the first example, we can introduce a new option, maybe calling it `includeInlayVariableTypeHintsWhenTypeMatchesName`, which should be set to `true` by default, so the user can opt-in the suppress behavior.

![](https://user-images.githubusercontent.com/20746719/150659345-3e73400c-f7eb-407b-8e00-93d99047b51c.png)

In the second example, I think the inlay hint is displayed correctly here, I'm not sure if it's a good idea to suppress the `address:` inlay when it comes with `recipientAddress`.
