### ISSUE TITLE
Argument type infer not work correctly without specify types of function params

### ISSUE THREAD

**Issue by Jokcy** [microsoft/TypeScript#47577]
# Bug Report

### 🔎 Search Terms

- Argument type infer not work correctly

### 🕗 Version & Regression Information

seems to be every version of typescript shows this behavior

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.4#code/FDAuE8AcFMAIHlKgJYHsB2BnAPAZVAIajQA0sAwqgLZXKiazQAex6AJgwErQDGqATm2yZQ-ZOgDmZABQii0AFyx88sgDoNBfhMxKC6cAEpYAXgB8sAG6pkbMxZOwA3sFhvYBHigy7Y3PoLCouJSsNJ8NHS+lJH0xuZWNnYkru4RtPRKMRmYKe6wcsRKKsTAAL4gAGYAruheaOiwbNCV4tD4AtB4hMRk2VGMLNDsXLwCQiJikjKFiso9pBpqWjp6BvEW1rb20qhIDb6I3ljdqhTUOWbGLvn80KDV-I17x5jlIBAw8-Kmzqlu6AIVDmkxC72AzVa6HaoE60hu7k8ryUCPybgISnCFyiG1g6Siy3+sDKeTS2MyfzRiMxszI0IA7gA5IEg4KSXEAcgIHKJJKJsxRRPygOBSg5ACtUABrHjgDmkqlafhKADaAF1eeVDCAgA)

In this example, if you try the use `commits` in `actions.a`, you will see the type of `commits` is:

```ts
Record<string, (state: {
    name: string;
    arr: never[];
}, ...args: any) => void>
```

If I update the commit function to use `state: State`,

```ts
...
{
  commits: {
    a: (state: State, newName: string) => 'a'
  }
}
...
```

 then the `commits` type in `actions.a` will be exactly what `commits` is, eg:

```ts
{
    a: (state: State, newName: string) => string;
}
```

### 🙁 Actual behavior

Without specify `state: State`, the commits type infer in `actions.a` not correct. I suppose TS will infer what state is, and there should not be different with/without specify `state: State`.

### 🙂 Expected behavior

there should not be different with/without specify `state: State`.

**Comment by Jokcy** [comment]
@jcalz So in this situation is there any better soluation to make it work?

**Comment by jcalz** [comment]
Split the single object into multiple parameters like [this](https://tsplay.dev/WKV7zm)?  (Note that the specific type named `State` will not magically be inferred anywhere since you never refer to it anywhere inside the call to `defineStore()`.)

**Comment by Jokcy** [comment]
@jcalz THX very much, help a lot. Is there any article about *context sensitive* of typescript? I still not quite sure when something is context sensitive.

**Comment by jcalz** [comment]
A context sensitive function is not fully [annotated](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#parameter-type-annotations) and so the compiler must use [contextual typing](https://www.typescriptlang.org/docs/handbook/type-inference.html#contextual-typing) to infer something about its type.

According to [this comment](https://github.com/microsoft/TypeScript/issues/38872#issuecomment-651450956) the compiler performs a phase of inference for every function parameter which is context sensitive, but it does not perform multiple phases of inference for a single function parameter.

**Comment by RyanCavanaugh** [comment]
I opened #47599 to track further work in the area

**Comment by AtLastDopamine** [comment]
> [像这样](https://tsplay.dev/WKV7zm)将单个对象拆分为多个参数？（请注意，命名的特定类型`State`不会在任何地方神奇地推断出来，因为您永远不会在调用中的任何地方引用它`defineStore()`。）

@jcalz  Your answer is very helpful, but I still don't understand how splitting into multiple parameters works.

In your example, if I switch the position of 'commits' and 'actions', the type derivation still does not work properly

**Comment by jcalz** [comment]
Some inference only works from left-to-right in order of parameters, see [this comment](https://github.com/microsoft/TypeScript/issues/34865#issuecomment-548867473) for example.
