### ISSUE TITLE
Increase default targets over time

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#47572]
# Suggestion

## 🔍 Search Terms

default target es3 es5

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Continuing #10117: can we increase the default TypeScript target to newer than ES3? Let's say, ES5 to start?

Starting suggestion: how about introducing these breaking changes with TypeScript's major version numbers?

* Increase to ES2015 for 5.0
* Increase to ES2016 for 6.0
    * Alternately, as TypeScript major versions have hit at roughly one every two years, it might make sense to jump two years per version and skip to ES2017
* _...and so on_

An alternate strategy would be bumping to ES5 first and pushing subsequent releases later. ES2015 is so well-supported, though, it'd be nice to skip straight to supporting `let`, `const`, etc.

## 📃 Motivating Example

I know the TypeScript team is loath to introduce breaking changes, especially when it comes to emit and default settings. Throwing in semantic versioning probably isn't doing this issue any favors either.

But! 

* ES2015 support is significantly better now than it was a few years ago. [IE is reaching consumer EOL in June 2022](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge). Per https://kangax.github.io/compat-table/es6 all desktop browsers, mobile browsers, and server browsers with >=1% market share have 100% ES2015 syntax support _(I think?)_.
* ES3 and ES5 emit are harder to read than ES2015+ because classes, `for`/`of`, and so on need to be transpiled
* Many runtime APIs such as `Array.from` aren't supported in <= ES5

This may be a breaking change for projects that target old runtimes _and_ use TypeScript's emit _and_ don't specify target... but that's what major versions are for, right? 😉 

## 💻 Use Cases

Increasing default targets to emit code much cleaner in modern browsers gives a nicer default output for new TypeScript projects. For beginners to TypeScript in particular, it makes the learning curve a little easier as they won't have to mess with configuration options to be able to use basic features.

**Comment by JacobMGEvans** [comment]
I feel like that tweet could be added as evidence lol

**Comment by styfle** [comment]
If this is going to introduce a breaking change, how about changing the default target to esnext instead? Then there would be no need to keep changing the default in the future and it would move typescript toward the goal of a type checker instead of transpiler.

**Comment by wojpawlik** [comment]
Consider also defaulting `strict` to `true`.

**Comment by RyanCavanaugh** [comment]
Default target in 5.0 is now ES5 and I suspect we might have appetite for ES6 in 6.0

**Comment by styfle** [comment]
Thanks @RyanCavanaugh!

Can you comment on my suggestion about defaulting to `target: "esnext"` instead of bumping each release?

https://github.com/microsoft/TypeScript/issues/47572#issuecomment-1074679216

**Comment by RyanCavanaugh** [comment]
ESNext includes features that work in 0% of runtimes, like standard decorators. Seems very aggressive.
