### ISSUE TITLE
For in array should be number index?

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#47578]
# Bug Report

### 🔎 Search Terms

for in , array index

### 🕗 Version & Regression Information

Current 4.5.5, I think this is a common issue.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.4#code/DYUwLgBAhgTjBcBBOUCeAeARge26KAdgHwQC8EA2gLoBQAZtjABSiQDWIqEAlgdHAEoA3jQhiIAY2wEAznhAA6YNgDmTDqgE0AvkA)

### 💻 Code

```tsx
let arr:Array<boolean> = []
for(let key in arr){
    console.log(key)// key is string in runtime, but index of type Array is number
}
```

### 🙁 Actual behavior

Index of array is number.

### 🙂 Expected behavior

Index of array is string.

**Comment by jcalz** [comment]
But [`for..in`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) gives strings, not numbers.  Even for arrays, you get string representations of numbers and not the numbers themselves:

```ts
let arr: Array<boolean> = [true, false]
for (let key in arr) {
    console.log(typeof key) // "string"
    console.log(key + key) // "00", "11"
}
```
[Playground link](https://www.typescriptlang.org/play?ts=4.5.4#code/DYUwLgBAhgTjBcECCcoE8A8AjA9j0UAdgHwQC8EA2mDAK4gA0EAZlMAM4gC6AUMzjAgAKUJADWINBACWhaHACUEAN48I6iAGMchdvhAA6YDgDmQsGgAOIHMwgS0SgPROIAInY1ZJt2o3bdfSNTIQcIAGp7SWdXNwAGOLcmNwBGFN8AXyA)

The current behavior is more correct than the behavior you're suggesting.  TypeScript doesn't currently expose a type like `NumericString` corresponding to strings to which numbers can be coerced, so `string` is what you get; see #32047 and #6346.

**Comment by ruojianll** [comment]
@jcalz There is a type error on union typeof array and string index object.

```ts
let arr:Array<any> = []
for(let key in arr){
    let value = arr[key] //OK
}

let obj:{[index:string]:any} = {}
for(let key in obj){
    let value = obj[key] //OK
}

let arrOrObj:{[index:string]:any}|...
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.4#code/DYUwLgBAhgTjBcBBOUCeAeKA7VA+CAvBANoC6AUAGYD2MAFKJANYioQCWW0cAlAN7kIQiIwgA3KMACuIQtxjEWqUhAD0qgPIBpcgF9y5UdQBGAK3h9inACYgAHvADOYGJwDmpeNlS65ffTT0okocXCam-ILCohLSskThiqwq6tp6BqKwMBrZZhZWWLYOzq5YHl44ugA+yDBomDi4BGRUtAzgECGc8jkaZpHCIh2xMnJZvWZJymqqACqoAA6yIHC08BAActShRRCO7G5YUGBSMLIA7uxgABbQEAuwUAC24CsQ1JQQYIuyAOQl7l+EHOUEcEBoUkK7y43yWEF+3jIECqED4JBs9nWALKnmgOAA3BBdL90kA)

**Comment by RyanCavanaugh** [comment]
There's a special rule that specifically allows
```ts
let arr:Array<any> = []
for(let key in arr){
    let value = arr[key] //OK
}
```
but this is only in effect when `arr` is exactly an array. Otherwise you get the stricter behavior.

**Comment by ajitjha393** [comment]
> ```ts
> let arrOrObj:{[index:string]:any}|Array<any>=[]
> for(let key in arrOrObj){
>     let value = arrOrObj[key] //Type error: No index signature with a parameter of type 'string' was found on type 'any[] | { [index: string]: any; }'
> }
> ```
> 

> Is the intended behavior? Why?

Yes, this is the intended behavior as Ryan mentioned.

`for...in` iterates over your object using `(key: string)` .
When indexing the Array, the casting of the key from string to number is done, 
And while looking up the property on objects (since your union type is an object `{  [index: string]: any  }`) we need to keep looking up with string
Hence the above behavior!

So to make it work in your case we can do -

```ts
let arrOrObj: { [index:string]:any }| Array<any>=[]
for(let key in arrOrObj){
    let value;
    if(Array.isArray(arrOrObj)){
        value = arrOrObj[Number(key)] 
    }else {
        value = arrOrObj[key]
    }
}

```
 
And you should probably not use `for..in` for traversing array in the first place
There are other alternatives for it.

From the above case of yours, If you are not interested in key you can just iterate over the values itself 
```ts 
let arrOrObj_: { [index:string]:any} | Array<any>=[]
for(let val of Object.values(arrOrObj_)){
        let value = val
}
```

**Comment by ruojianll** [comment]
> TypeScript doesn't currently expose a type like NumericString corresponding to strings to which numbers can be coerced.

Why don't we use number directly? To support early versions of typescript?

**Comment by ruojianll** [comment]
A similar issue #47636.

**Comment by fatcerberus** [comment]
> Why don't we use number directly?

Because TypeScript is largely just JavaScript with type annotations - and `key` **will** be a string when the loop actually runs.

**Comment by jcalz** [comment]
>  TypeScript doesn't currently expose a type like `NumericString` corresponding to strings to which numbers can be coerced, 

In particular, `` `${number}` `` (unfortunately, imo) does not correspond to strings to which numbers can be coerced, see #41893.
