### ISSUE TITLE
ts v4.5.4 ,the lib.dom  navigator not have  hid.  

### ISSUE THREAD

**Issue by SNH-48** [microsoft/TypeScript#47588]
# lib Update Request

ts v4.5.4 ,the lib.dom  navigator not have  hid.  can give me some suggestion ？

## Documentation Link

https://wicg.github.io/webhid/

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
