### ISSUE TITLE
exactOptionalPropertyTypes being inconsistent with T[keyof T]

### ISSUE THREAD

**Issue by sarimarton** [microsoft/TypeScript#47587]
# Bug Report

### 🔎 Search Terms

exact optional property types

### 🕗 Version & Regression Information

- This seems to be an incomplete feature of version 4.4's exactOptionalPropertyTypes. Possibly related to #45764.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/C4TwDgpgBAKlC8UDeUCGB+AXFAdgVwFsAjCAJwG4ojsBnYUgSxwHMoBfAKA4Hpuo8cAEwgAzJhEFQAbqgA2eaAxpQAxgHtSpCCuCyQuNcChg1NGgyKyIPPgAFgNALQQAHpB3PNGjupx0oLthwiCio2ALCYjgS7Fy8UADKABZqeLKSJLiEJKRQAD5QdIwsHKCQsABMCLAA2gDWECBqIrAAunF8MElKhSlpGdCoOFBkpBoANFR4RgzAAOTKOIY2UPZOru7AnmOkPmp+Ri4VQVWIEaLighxAA)

### 💻 Code

```ts
type T = { a?: number; b: string }

// undefined value is correctly not possible
// @ts-expect-error
const x: T = { a: undefined }

// Should be number | string
type T2 = T[keyof T]

// This should be an error, but it's not
// @ts-expect-error
const x2: T2 = undefined
```

### 🙁 Actual behavior

`T[keyof T]` is `string | number | undefined`

### 🙂 Expected behavior

`T[keyof T]` is `string | number`

**Comment by fatcerberus** [comment]
`T[K]` is the type you get by *reading* from `T` with a key of type `K`.  Having `undefined` in that type is therefore expected, regardless of `exactOptionalPropertyTypes`.  If it wasn’t then
```ts
const x: T = {};
const x2: T2 = x.a;
```
wouldn’t work.

**Comment by sarimarton** [comment]
> `T[K]` is the type you get by _reading_ from `T` with a key of type `K`. Having `undefined` in that type is therefore expected, regardless of `exactOptionalPropertyTypes`. If it wasn’t then
> 
> ```ts
> const x: T = {};
> const x2: T2 = x.a;
> ```
> 
> would be a type error.

I see your point. That's a pity, because it means there's no safe way to type an object's possible keys' possible values. `T[keyof T]` was supposed to that, but any optional prop of T undermines it in a way which goes against exactOptionalPropertyTypes: optionality of a prop introduces an extra item in the value union. I understand that `undefined` is per se an expression of optionality, but exactOptionalPropertyTypes is supposed to nullify this rule.

**Comment by fatcerberus** [comment]
> I understand that undefined is per se an expression of optionality, but exactOptionalPropertyTypes is supposed to nullify this rule.

Except it doesn't nullify the rule, because you can still *read* an `undefined` from the optional property.  The only thing EOPT does is to prevent you from *writing* one.

**Comment by RyanCavanaugh** [comment]
This seems to be a misunderstanding of what EOPT means.

The type you want instead of `T[keyof T]` is this:
```ts
type NotUndefinedKey<T, K extends keyof T> = Pick<T, K> extends {} ? NotUndefined<T[K]> : T[K];
type GetWriteShape<T> = { [K in keyof T]-?: NotUndefinedKey<T, K> };
type TW = GetWriteShape<T>;
type M = TW[keyof TW];
```

**Comment by sarimarton** [comment]
@RyanCavanaugh This code correctly removes undefined from optional properties, but it removes it too, when undefined is allowed:

```ts
type NotUndefined<T> = T extends undefined ? never : T;
type NotUndefinedKey<T, K extends keyof T> = Pick<T, K> extends {} ? NotUndefined<T[K]> : T[K];
type GetWriteShape<T> = { [K in keyof T]-?: NotUndefinedKey<T, K> };
type PossibleValues<T> = GetWriteShape<T>[keyof GetWriteShape<T>];

type T = { a: number, b: string, c: undefined }
type xxx = PossibleValues<T> // string | number
type yyy = T[keyof T] // string | number | undefined
```
