### ISSUE TITLE
Parent class and a Sibling class can be used as an argument that expects a specific class

### ISSUE THREAD

**Issue by formula1** [microsoft/TypeScript#47585]
# Bug Report

When extending a parent class, I may overload some functions or properties. As a result, it may be incompatible with the base class since the methods or properties may produce different behaviors. Currently, I can still use both the parent class and sibling class in a method that expects a specific class. If the function accepted the parent class as an argument type, I would understand why it accepts everything else as a possible type.

I don't particularly want to reimplement the entire class and call each of the classes methods just to prevent the parent or sibling classes from being used.

```typescript
class WholeNumber  {
  add(v: WholeNumber|BigNumber.Value): WholeNumber {
   return  BigNumber.prototype.add.call(this, v);
  }
}
```

### 🔎 Search Terms

Extends, Parent, Child, Sibling, Compilation, Function, Argument, Typescript

### 🕗 Version & Regression Information

I'm not planning on testing every version of typescript. I have tried

```
typescript: 4.5.4
typescript: next
```

### 💻 Code

```typescript
import BigNumber from "bignumber.js";

class ChildNumber extends BigNumber {
  comparedTo(y: BigNumber.Value, b?: number): number{
    console.log(y);
    console.log(b);
    return 0;
  }
}

class SiblingNumber extends BigNumber {
  comparedTo(y: BigNumber.Value, b?: number): number{
    console.log(y);
    console.log(b);
    return 1;
  }
}

const childOne = new ChildNumber(1);
console.log("cN is Child?", childOne instanceof ChildNumber);       // true
console.log("cN is Sib?", childOne instanceof SiblingNumber);           // false
console.log("cN is Big?", childOne instanceof BigNumber);           // true

const sibOne = new SiblingNumber(1);
console.log("sN is Child?", sibOne instanceof ChildNumber);         // false
console.log("sN is Sib?", sibOne instanceof SiblingNumber);             // true
console.log("sN is Big?", sibOne instanceof BigNumber);             // true

const bigOne = new BigNumber(1);
console.log("bN is Child?", bigOne instanceof ChildNumber);         // false
console.log("bN is Sib?", bigOne instanceof SiblingNumber);             // false
console.log("bN is Big?", bigOne instanceof BigNumber);             // true

function divideByThree(n: ChildNumber): ChildNumber {
  return n.div(3);
}

console.log("cN div 3:", divideByThree(childOne).toString());    // works
console.log("sN div 3:", divideByThree(sibOne).toString())       // Should not work
console.log("bN div 3:", divideByThree(bigOne).toString());      // Should not work

```

### 🙁 Actual behavior

BigNumber and DecNumber can be used when a WholeNumber is expected. In some libraries, they may extend a class from another library and setup a custom configuration for that library. If the base class or a sibling class is used in the function this has the potential to cause unexpected results. For example, if it precision was important to a class, one might return 0 another 0.3 and another 0.333. All different values

### 🙂 Expected behavior

I expect there to be a compilation error preventing the use of BigNumber or DecNumber from being used in the divideByThree function.

**Comment by RyanCavanaugh** [comment]
These classes are structurally identical, thus interchangeable. See https://github.com/Microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by formula1** [comment]
But like in the example, although it's very simple, the functions compareTo are not the same. This can lead to unexpected results. The typing may be the same with regard to arguments and return functions but if one number rounded down all decimals and the other stored up to 5 decimals, they would be different.

It makes sense for

```typescript
class Person {
  name: string;
}

class Individual {
  name: string;
}
```

Because they are effectively the same class. But in my example, the parent, child and sibling classes are different. As a result, you should not be able to use the parent or sibling when the child is expected 


This may be "working as intended" but it seems like I have to get hackey in order to prevent unwanted usage. Im under the impression organized, safe code is more typescripts style than hackey work arounds.

**Comment by fatcerberus** [comment]
This is completely a consequence of structural typing; function assignability can’t be based on anything other than argument and return types because otherwise passing around callbacks wouldn’t work.

That being said, it usually makes more sense for classes to be nominally typed.  Luckily, you can get that by just adding a private property to each class.  Subclasses will still be assignable to superclasses, but that’s expected in OOP.

**Comment by formula1** [comment]
@fatcerberus Someone else mentioned this and it work partially but was throwing errors. But I believe that may be due to immutability of the library causing it to return an instance of the original class than my extended class. Nonetheless, I appreciate the feedback.
