### ISSUE TITLE
Nested promises are not properly unwrapped in `Promise.then`

### ISSUE THREAD

**Issue by GauBen** [microsoft/TypeScript#47593]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2017` and my *lib* is `the default`.

## Missing / Incorrect Definition

I think the definition of `Promise.then` is incorrect

https://github.com/microsoft/TypeScript/blob/a9efe2be6040e581100231891dea78a7fbc4f46c/src/lib/es5.d.ts#L1476-L1482

## Sample Code

```ts
const z = new Promise<Promise<string>>(
	resolve => resolve(new Promise<string>(
		resolve => resolve('z'))
	)
)
// Correctly typed as Promise<Promise<string>>

z.then(str => console.log(str))
//     ^ Incorrectly typed as Promise<string>

```

[Playground Link](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/MYewdgzgLgBAXjAvDMBTA7jACgJxAWwEsJUAeXA4s6HQsAcwD5GAKAWACgZuYdUIQAGwBuqJI178holmkwUiJUjTpN2XHpr4CRYxBO3TULAORwTASgudN1jnc5wAdFAAWqMCxriYoSENQnQRB6LygcK04gA)

## Fix

The correct function definition could be (replace `T` with `Awaited<T>`):

```ts
then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: Awaited<T>) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): Promise<TResult1 | TResult2>;
```

**Comment by tangjfn** [comment]
then<...>(...): PromiseLike<**Awaited**<TResult1 | TResult2>>;

**Comment by rbuckton** [comment]
If you amend your example to the following, it should type check correctly:

```ts
const z = new Promise<string>(
    resolve => resolve(new Promise<string>(
        resolve => resolve('z'))
    )
)
// Correctly typed as Promise<string>

z.then(str => console.log(str))
//     ^ Correctly typed as string
```

It is a known caveat that we cannot currently restrict the type of `T` in `Promise<T>` to only be a non-promise type, as that would require negated types (i.e., `interface Promise<T extends not PromiseLike> { ... }`). We also cannot change the type for `value` to `Awaited<T>` without breaking assignability with existing third-party promise libraries such as `Q`, `rsvp`, etc. We ran into issues with this with the old `awaited T` PR, so I'm not sure this is something we can change at this point.

**Comment by GauBen** [comment]
Thanks for the heads up @rbuckton! Unfortunately, the `Promise<Promise<Something>>` is created by a library. I'll use `as Promise<Something>` to work around this issue.
