### ISSUE TITLE
non overlapping casts are allowed for literals

### ISSUE THREAD

**Issue by ilogico** [microsoft/TypeScript#47592]
# Bug Report

### 🔎 Search Terms
non overlapping cast

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the handbook for entries about type assertions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/CYUwxgNghgTiAEYD2A7AzgF3lAXPA5FPgFCiSwLLpYBGeAjKeNHIqpongN7YPwC+xYlQ4APPPhr54AXmzY0BKQG5h7LAE88AJlnwaC+NtUisAL268jAvWEM9c1-sqA)

### 💻 Code

```ts
declare const a: 'a';
declare const b: 1;
declare const c: { a: 1 };

const x: 'b' = a as 'b'; // unexpectedly allowed 
const y: 2 = b as 2; // unexpectedly allowed 
const z: { a: 2 } = c as { a: 2 }; // expectedly disallowed
```

### 🙁 Actual behavior
TS allows type assertions between literal types with no overlap.

### 🙂 Expected behavior
TS errors saying the conversion is mistake because neither type sufficiently overlaps with the other, maybe suggesting an intermediate type assertion to a common supertype.

According to the [manual](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions):
> TypeScript only allows type assertions which convert to a more specific or less specific version of a type.

**Comment by RyanCavanaugh** [comment]
See  #14156

**Comment by ilogico** [comment]
I don't understand the rationale and I suspect the justification is outdated.
> Widening is important so that null / undefined can be asserted to other types 
Well, as far as I know, `null` and `undefined` cannot be asserted as other types (except using the non null assertion).

The example below in the issue (`something as false`) would equally apply to interfaces and it doesn't.
Also, the documentation is not consistent with the intended behaviour.

I object to the design, but of course, I accept it and I don't think I have anything to add to this.
