### ISSUE TITLE
React Javascript Builtin Hooks Import bug

### ISSUE THREAD

**Issue by omonkulov** [microsoft/TypeScript#47601]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2  x64
- OS Version: Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. Create a react app using `npx create-react-app my-app`
2. Create a component and try importing any build-in hooks

When importing build-in hooks in a fresh react project, vscode imports suggests `react/cjs/*` instead of just `react` as shown below.
The weird thing is when I clone old projects and try to import, it works perfectly fine. I check package.json for both old and new project and they were exactly the same. 

It is also weird that when you create the react project with typescript template, everything works perfectly fine again.
```js
BEFORE:
 import { useState } from "react";

NOW:
 import { useState } from "react/cjs/react.production.min"; 
 or
 import { useState } from "react/cjs/react.development";
```

Searching online, I only found people who have the same issue but no solutions.

https://www.reddit.com/r/reactjs/comments/sbdrow/vs_code_auto_import_is_bugging_or_i_am_stupid/

**Comment by omonkulov** [comment]
That solved the problem! Thank you!

**Comment by raph90** [comment]
Sadly this doesn't solve the issue for me

**Comment by dmytro-shchurov** [comment]
For me it was solved after I installed `@types/react`, but this was unexpected as my project was pure JavaScript one. I think some extension affects a content of an auto import list. Someone has decided that react === typescript =)

**Comment by omarqra** [comment]
think you , it works for my 



> Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
> 
> Does upgrading fix the issue?

**Comment by ShahriarKh** [comment]
> Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)
> 
> Does upgrading fix the issue?

Didn't help.

**Comment by ddikodroid** [comment]
installing `typescript@next` once solved the problem, but today it appears again.
i'm using plain js for the project.
