### ISSUE TITLE
Narrowing down the type of a Promise which had Promise.allSettled called on doesn't work

### ISSUE THREAD

**Issue by hugohabicht01** [microsoft/TypeScript#47617]
# Bug Report

When calling Promise.allSettled on an array of promises, the returned array will contain values of the type `PromiseSettledResult<T>`,  as found [here](https://github.com/microsoft/TypeScript/blob/3206df8e6d4580381cd3712e385574b0351c3ff0/lib/lib.es2020.promise.d.ts#L31)
When you filter this array afterwards for by Promises that were fulfilled, you will find that the compiler doesn't seem to understand that the filtered arrays will only contain values of type `PromiseFulfilledResult<T>`. Same goes for the opposite, when filtering for rejected promises the compiler won't understand that all results of promises which are left have to be rejected promises.
A similar bug has been reported before at #42012 but was closed by the bug reporter, after he commented a very hacky workaround which doubled the processing time in the worst case
### 🔎 Search Terms

filtering Promise.allSettled result doesn't narrow down the type of the values

### 🕗 Version & Regression Information

This bug seems to occur in all versions which support Promise.allSettled

### ⏯ Playground Link
[playground link](https://www.typescriptlang.org/play?target=7&pretty=true&ts=4.6.0-dev.20220116#code/MYewdgzgLgBAtgQwJZhgXhgiBPMwYAUAlOgHwwDeAUDDKJLAA4BOIcSEAphOjANoAFVuy4A6ZtxAAbAG6cCAIijcoCogBoYQth07jOAK07Aoi5dABMazdpF6JEaXIIByBMyQhoYEO6hgXIgBdKho6cGgYBwBXKSgeDAQAd2RYW11RBCkpAGVOKCgpTgATAhYdLggiUNoJKGjmVBi4iFEAMyQ4zmYCGSyyGD6pUWgEeoS0DBc22I7sksDRREZe-rRyIdEh6M5qgF8gA)

### 💻 Code

```ts
const main = async () => {
  const promises = [Promise.resolve("qwfpgjuy;"), Promise.reject("zxcvbkm,."), Promise.resolve('arstneio')]

  const results = await Promise.allSettled(promises)

  return results.filter(val => val.status === 'fulfilled').map(val => val.value)
}
```

### 🙁 Actual behavior

When trying to compile this code, the compiler will complain the following:
```
Property 'value' does not exist on type 'PromiseSettledResult<string>'.
  Property 'value' does not exist on type 'PromiseRejectedResult'.
```

### 🙂 Expected behavior

The compiler should just compile the code and be able to identify that all values of the array, that still exist after filtering it for fulfilled promises, should be of type `PromiseFulfilledResult<T>`

**Comment by MartinJohns** [comment]
**This is working as intended.**

---

The `filter` function does not narrow the type, unless you pass in a [type guard](https://www.typescriptlang.org/docs/handbook/2/narrowing.html?#using-type-predicates). The function you pass in is **not** a type guard.

`(val): val is PromiseFulfilledResult<string> => val.status === 'fulfilled'` would be a type guard because of the return type annotation.

```typescript
return results.filter((val): val is PromiseFulfilledResult<string> => val.status === 'fulfilled').map(val => val.value)

// Or alternatively provide a custom function:
function isFulfilled<T>(val: PromiseSettledResult<T>): val is PromiseFulfilledResult<T> {
  return val.status === 'fulfilled';
}

return results.filter(isFulfilled).map(val => val.value)
