### ISSUE TITLE
[Huge] Alternative File-Type extension for typescript files (.ts = mpeg-2 video)

### ISSUE THREAD

**Issue by adroste** [microsoft/TypeScript#47611]
# Suggestion

Huge request. One thing that I don't like about typescript is the file extension itself. ".ts" was already reserved for mpeg-2 video long before anyone thought about shipping JS apps with the complexity we see today.
This causes a lot of problems:
* backup tools consider them as videos and handle them differently
* nearly every file management/operation tool think it's a video (file recovery, search, remote access, ...)
* file explorers think it's a video (tested on windows and macOS)
  * it opens the file in a video player per default <=> changing the default makes no sense as proper .ts (actual videos) would open up in a text editor
  * os specific features like code-preview (quicklook) stop working (see https://github.com/microsoft/TypeScript/issues/25945)
  * wrong icons
* file patterns (e.g. web servers, custom apps) that are not optimised for the existence of typescript send typescript files with wrong mime type or apply the wrong handling per default <=> again changing this manually breaks handling of actual video files 
* even vscode is confused (see https://github.com/microsoft/TypeScript/issues/21136)

I think giving typescript the extension ".ts" was a mistake.
As there is just no simple solution, we could introduce an alternative file extension like ".reallynotavideo", ".tscript", ".tsc", ... (I really don't care).

## 🔍 Search Terms

* video
* mpeg-2

Somewhat related issue: https://github.com/microsoft/TypeScript/issues/25945 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

=> However, it would still be a breaking change and could also require a lot of reconfiguration (e.g. file-patterns).

## ⭐ Suggestion

Introduce an "official" alternative file extension that can be used ootb for typescript files (e.g. ".tsc", ".tscript", ...).

## 📃 Motivating Example

See above

## 💻 Use Cases

See above

**Comment by nmain** [comment]
How does an alternative file extension benefit you?  If you're consuming other people's work that uses the normal extension, you'll still have the same issues.

**Comment by adroste** [comment]
@nmain True, to *really* fix this problem the whole community must adopt a new file extension. I just don't understand why they went with .ts in the first place. This is a huge problem as a file extension should tell the system or other software what the file is about. Confusing one text format with another is not that bad but creating ambiguity between a common media/video format and a code-file is (see linked issues above).

**Comment by MartinJohns** [comment]
> This is a huge problem as a file extension should tell the system or other software what the file is about.

I can count the amount of times I encountered `.ts` mpeg files on one hand. Haven't heard of anyone struggling with this either. I would say this problem is rather niche, definitely not huge.

**Comment by RyanCavanaugh** [comment]
You can use `.tsx` even if you're not using JSX syntax. Think of it as the "TypeScript eXtension" if that helps 😉

**Comment by adroste** [comment]
While using tsx is definitely an option to circumvent the problems mentioned above it breaks semantic consistency. Using tsx in a context without jsx-elements will certainly lead to confusion when sharing code as the assumption is: tsx will contain jsx elements so it‘s probably code for the view.

**Comment by RyanCavanaugh** [comment]
If it makes you feel any better, even if we did add a brand new file extension (which we won't), we'd almost certainly eschew the `ts/tsx` distinction and just have it only be `tsx` grammar. The `<T>expr` syntax has largely fallen out of favor.

**Comment by adroste** [comment]
Thanks for the statement. I just wanted to raise awareness that file extension ambiguity is a thing (and it‘s annoying).

**Comment by fatcerberus** [comment]
This isn't a *huge* problem day-to-day, but it can cause problems when opening a folder full of `.ts` files in Windows Explorer - the file manager thinks they're all video files and often spends *several seconds* trying to load their thumbnails, during which time the Explorer window is unresponsive.  Sometimes it even crashes.  It can be fixed by switching the folder to Details view, but that setting isn't always remembered.

macOS Finder sometimes stumbles in the same way.

**Comment by fatcerberus** [comment]
> If you're going to make something that implicitly opens every single file and scans every single one of them for content, it has to be bulletproof for both performance concerns and security concerns. File explorers should be incapable of crashing or performing slowly regardless of the inputs.

I definitely agree, but sadly we don't live in a perfect world. 😞  That being said, I was a bit surprised to find out that Finder was affected by this, since I always thought macOS used file content to determine the types of files in addition to their extensions.

**Comment by jackpunt** [comment]
Cost me a few hours wondering why MacOS Spotlight finds text in [compiled] .js files but not in [source] .ts files.
And there's no way to tell Spotlight to override/disable the mpeg interpretation of the '.ts' extension.

Can you say what potential conflict from renaming my *.ts -> *.tsx? 
Where/How does the <T>expr syntax apply?

**Comment by berniegp** [comment]
I was quite annoyed by Windows explorer's sluggishness with `.ts` and `.d.ts` files and found a solution that involves remapping their "file kind" to `document` instead of `video`.

More info here: https://superuser.com/questions/1304114/windows-explorer-hangs-creating-thumbnails-for-typescript-files/1733384#1733384

**Comment by pouriap** [comment]
I fully agree.
I also have a huge problem with this because I have to choose whether I want to associate .ts files with a text editor or a video player. And 'open with' is not an option when dealing with archives, etc. I don't know why they would pick an extension that is already in use by another file type. It is unprofessional and extremely annoying.

**Comment by DaveyJake** [comment]
+1

I would also like to see **something** done that doesn't involve renaming `.ts` to `.tsx`.  `.tsc` seems like it would be the ideal extension name as well as a **HUGE** help, especially in regards to CPUs hitting 100% in VSCode.

**Comment by mattcph** [comment]
Is it just too late for this extension violation (blunder) to be changed? is it like the www sub-domain misunderstanding from 1994?

**Comment by adroste** [comment]
This already got the label `declined` from @RyanCavanaugh a year ago. I think a 'no' is not a great answer here tbh.
The web-dev world is changing super fast. Improvements can always be made. Would like to see this considered again.

> even if we did add a brand new file extension (which we won't), we'd almost certainly eschew the `ts/tsx` distinction and just have it only be `tsx` grammar.

Making and promoting tsx as the default would definitely be one possible solution. What holds you back?

**Comment by ritschwumm** [comment]
i think the problem goes much deeper: metadata meant for consumption by the OS should not be part of the file name - the file name should cater for human users, and _only_ them. other operating systems like mac os classic and amiga os got this right, it's just windows that didn't...

**Comment by RyanCavanaugh** [comment]
I don't know what anyone expects us to do here beyond what's already available. There are 10 years of TypeScript files out there; we can't unring that bell. You can write `.tsx`, `.mts`, or `.cts` depending on what you're doing. It's extremely realistic to switch your code over to those extensions today, and unrealistic to expect everyone else in the world to rename their files because you somehow have actual real transport stream files as part of your daily routine.

I tried to write a .reg file to completely unassociated `.ts` from video, but only got this far before giving up (this stuff is pretty buried these days). Anyone able to make it work faster than just choosing "Open With" -> VS Code -> Always?
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.ts]
@=-
"Content Type"=-
"PerceivedType"="text"

[-HKEY_CLASSES_ROOT\.ts\OpenWithProgids]
[-HKEY_CLASSES_ROOT\.ts\ShellEx]

[HKEY_CLASSES_ROOT\.ts\OpenWithProgids]
"VSCode.ts"=""

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.TS\OpenWithProgids]
"WMP11.AssocFile.TTS"=-

[HKEY_CLASSES_ROOT\Applications\wmplayer.exe\SupportedTypes]
".ts"=-

[-HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\PackageRepository\Extensions\windows.fileTypeAssociation\.ts]

[-HKEY_CLASSES_ROOT\SystemFileAssociations\.ts]

[HKEY_CURRENT_USER\Software\Classes\.ts\OpenWithProgids]
"VSCode.ts"=""

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.TS\OpenWithList]
"a"="Code.exe"
"MRUList"="a"
```

**Comment by kkirby** [comment]
> You can write `.tsx`, `.mts`, or `.cts`

For the record, `.mts` is also reserved for video files. And `.cts` is falling out of favor. My only issue with using `.tsx` is that its reserved for React and can be confusing if your app doesn't use React. Plus, TypeScript will do additional, unnecessary parsing if you use `.tsx`.

I'm in favor of switching to `.tsc` and `.tscx`. You can keep `.ts` and `.tsx` as legacy extensions and still support them.

**Comment by GabrielGorta** [comment]
MS Teams always treat TS files as video, and it shows error when it contains text.

**Comment by cjens19** [comment]
> Do we have any generic workaround this issue. It has literally stopped my progress on working on a typescript project all of a sudden.

Looks like we arrived here at this closed post for the same reasons today. I too have just noticed some weirdness while working on my angular project in webstorm. Changes I was making in my IDE were not being saved to the file system so git was not seeing my changes. Went to just edit my .ts files in notepad to see if my IDE changes were there and saw that all my .ts files are being seen as type 'WMP11.AssocFile.TTS'. 

Still looking around online for how to correct this. I did install the Win 11 24H2 update last night, and it borked my work VPN so I rolled back to the previous build. Not sure if that's the cause of this new issue for me, but it's worth mentioning. I've been working on this same project for 18 months now and just today have seen this issue. Very strange. Best of luck!

**Comment by RyanCavanaugh** [comment]
Most modern code targets either explicitly ESM or CJS, so you can use `.mts` or `.cts` file extensions respectively instead.

**Comment by jackpunt** [comment]
My main problem with .ts is on the Mac, where Finder will not index/search .ts files.

Mostly solved that with bash, xargs, grep; can not search my ts project directories
Here, FWIW:

```
export XFIND_DIR='.' # or 'src' or whatever: export XFIND_DIR=src
export XFIND_EXCLUDE="node_modules target CVS .svn .hg _darcs .git .bzr test build"
export GREP_COLORS="1;32"

export XFIND_HELP="FOUR args: \"*.extension\" FLAGS String|Regex Directory
 \"*.ext\" (or other 'find -name' selector; supplied by findX functions)
 Need to quote \"*.ext\" ::  xfind \"*.js\" foo .
 -v show expanded dir and file commands
 -i use grep -i
 -s to compress whitespace
 -L to follow symlinks
"
# > xfind {iname:*.java} {-visL} str {dir:.}
function xfind() {
    local t=$(printf '\t')    ## OSX sed does not recognize "\t" as a tab
    local GREP_COLORS="1;31"
    local GREP='grep --color=always'  # color even when piping into sed
    local ext="*"
    if [[ "$1" =~ [*][.]* ]] ; then ext="$1" ; shift ; fi
    local vecho=""
    local sp1=""
    local el=""
    if [[ "$1" =~ ^-[hivsL]*$ ]] ; then
        if [[ "$1" =~ -.*h ]] ; then printf "$XFIND_HELP" ; fi
        if [[ "$1" =~ -.*v ]] ; then vecho="-v" ; fi
        if [[ "$1" =~ -.*i ]] ; then GREP="$GREP -i" ; fi
        if [[ "$1" =~ -.*s ]] ; then sp1="true" ; fi
        if [[ "$1" =~ -.*L ]] ; then el="-L" ; fi
        shift
    fi
    local namex=() # "-iname \"${ext}\""
    local names=()
    IFS=';' read -d '' -ra names < <(printf '%s;\0' "$ext")
    for name in "${names[@]}" ; do namex+=( -o -iname \"$name\" ) ; done
    namex=( ${namex[@]:1} )
    
    local str=$1
    local dir=${2:-$XFIND_DIR}
    if [ "$vecho" == "-v" ] ; then
	echo "find \"$dir\" -type f \( ${namex[@]} \) -print | xargs $GREP -nH -e \"$str\" | onespace $sp1"
    fi
    local noname='*~'
    local exclude=${XFIND_EXCLUDE:-"node_modules target CVS .svn .hg _darcs .git .bzr"}
    local nopath=()
    for x in ${exclude} ; do nopath+=( -o -path \"*/$x\") ; done
    nopath=( ${nopath[@]:1} ) ## remove initial ' -o '

    if [ "$vecho" == "-v" ] ; then
	echo echo $el \"$dir\" "\(" ${nopath[@]} "\)" -prune \
	     -o -type f "\(" ${namex[@]} "\)" ! -name \"${noname}\" -print \| xargs find
	echo "xargs $GREP -nH -e \"$str\" | spaceafter | onespace $sp1"
    fi

    echo $el "$dir" \( ${nopath[@]} \) -prune \
	 -o -type f \( ${namex[@]} \) ! -name "${noname}" -print | xargs find |\
	xargs $GREP -nH -e "$str" | spaceafter | onespace $sp1
}

# xfind over a tree of [project] directories; getting down to src, src/app, .vscode; bypassing dist, lib...
# could probably just put those into XFIND_EXCLUDE
function findtree() {
    local ext="*.ts"
    if   [[ "$1" =~ [*] ]]     ; then ext="$1" ; shift ; 
    elif [[ "$1" =~ [*][.]* ]] ; then ext="$1" ; shift ; fi
    local sub=""
    if [[ "$1" =~ -.*d ]] ; then shift ; sub="/$1" ; shift ; fi
    for dir in ./* ; do { if [[ -d "./$dir" ]] ; then xfind "$ext" "$1" "$dir$sub" ; fi ; } done
}

# findts {-i} regex (typescript)
function findts() {
    xfind "*.ts" "$@"
}

# Search [ng] project sources [*.ts]: (because Apple finder ignores .ts files)
function findtsrc() {
    findtree "*.ts" -d "src" "$@"
}
```

**Comment by DaveyJake** [comment]
@jackpunt Would I just copy/paste this into my `.bash_profile` / `.zshrc` and go from there?

**Comment by jackpunt** [comment]
A minor flaw in the code; 
in the final statement, $el (the -L option for symlinks) should be applied to 'find' (not echo)
```
echo "$dir" \( ${nopath[@]} \) -prune \
	 -o -type f \( ${namex[@]} \) ! -name "${noname}" -print | xargs find $el |\
	xargs $GREP -nH -e "$str" | spaceafter | onespace $sp1
```

**Comment by DaveyJake** [comment]
> A minor flaw in the code; in the final statement, $el (the -L option for symlinks) should be applied to 'find' (not echo)

Is there supposed to be an extra `echo` inside the `if [ "$vecho" == "-v" ]` statement?

**Comment by jackpunt** [comment]
> Is there supposed to be an extra echo inside the if [ "$vecho" == "-v" ] statement?

Yes: that is part of the -v option for debugging. It prints to the terminal the commands that it will or would be executing.  I suppose it might be more clear to say `echo "echo" ...` One can even cut and paste (and edit) that output back into the terminal to see why it works/fails...  
But yes, that line should also have the $el moved to find (although it does not affect the functional operation)

I've also improved the -h (help) option, so I'll just republish the whole thing.
(If I were a better person, this [.bash_xfind.sh] would be in a repo on github)

Note: rather than pasting directly into .bash_aliases (or whereever) 
easier to put in ~/.bash_xfind.sh and use "source ~/.bash_xfind.sh" in .bash_aliases

````
# edit these, or export new values after sourcing this file:
export XFIND_DIR='.' # or 'src' or whatever: export XFIND_DIR=src
export XFIND_EXCLUDE="node_modules target CVS .svn .hg _darcs .git .bzr test build dist"
export XFIND_IGNORE="*~"
export GREP_COLORS="1;32"

export XFIND_HELP="usage: xfind \"*.ext\" FLAGS String|Regex Directory
 up to four args:
 Files: \"*.ext\" (or other 'find -name' selector; typically supplied by findX functions)
   MUST be quoted \"*.ext\" ::  xfind \"*.js\" foo .
 FLAGS: (optional, merge in order: -isL)
   -h show this help
   -v show expanded dir and file commands [debugging]
   -i use grep -i [ignore case]
   -s to compress whitespace [onespace]
   -L to follow symlinks [find -L]
 Regex: quote if necessary
 Dir: (defaults to XFIND_DIR='.')

XFIND_DIR: default directory (.)
XFIND_EXCLUDE: directories to ignore (node_modules, build, ...)
XFIND_IGNORE: filenames to ignore (*~)
"

# This was originally from B&N to find names in/between java & C#
# [did they use CVS? what is */{arch} ?
# Usage: xfind {iname:*.java} {-hvisL} regex {dir:.}
function xfind() {
    if [[ "$#" == "0" ]] ; then echo "$XFIND_HELP"; return ; fi

    local t=$(printf '\t')    ## OSX sed does not recognize "\t" as a tab
    local GREP_COLORS="1;31"
    local GREP='grep --color=always'  # color even when piping into sed
    local ext="*"
    if [[ "$1" =~ [*][.]* ]] ; then ext="$1" ; shift ; fi
    local vecho=""
    local sp1=""
    local el=""
    if [[ "$1" =~ ^-[hivsL]*$ ]] ; then
        if [[ "$1" =~ -.*h ]] ; then printf "$XFIND_HELP" ; return ; fi
        if [[ "$1" =~ -.*v ]] ; then vecho="-v" ; fi
        if [[ "$1" =~ -.*i ]] ; then GREP="$GREP -i" ; fi
        if [[ "$1" =~ -.*s ]] ; then sp1="true" ; fi
        if [[ "$1" =~ -.*L ]] ; then el="-L" ; fi
        shift
    fi

    local namex=() # "-iname \"${ext}\""
    local names=()
    IFS=';' read -d '' -ra names < <(printf '%s;\0' "$ext")
    for name in "${names[@]}" ; do namex+=( -o -iname \"$name\" ) ; done
    namex=( ${namex[@]:1} )
    
    local str=$1
    local dir=${2:-$XFIND_DIR}
    local CMD="$GREP -nH -e \"$str\"" # only for vecho, not actual xargs $CMD !

    if [ "$vecho" == "-v" ] ; then
	echo "# command to search all files in all directories:"
        echo "find \"$dir\" -type f \( ${namex[@]} \) -print | xargs $CMD | onespace $sp1"
    fi
    local noname=${XFIND_IGNORE:-'*~'}
    local exclude=${XFIND_EXCLUDE:-"node_modules build target CVS .svn .hg _darcs .git .bzr"}
    local nopath=()
    for x in ${exclude} ; do nopath+=( -o -path \"*/$x\") ; done
    nopath=( ${nopath[@]:1} ) ## remove initial ' -o '

    if [ "$vecho" == "-v" ] ; then \
	echo "# extended to -prune (XFIND_DIR) -name (noname)"
	echo echo \"$dir\" "\(" "${nopath[@]}" "\)" -prune -o -type f \\
	echo "\(" ${namex[@]} "\)" ! -name \"${noname}\" -print \| \\
        echo xargs find $el \| xargs $CMD | spaceafter | onespace $sp1
	return
    fi
    echo "$dir" \( ${nopath[@]} \) -prune  -o -type f \( ${namex[@]} \) ! -name "${noname}" -print | \
    xargs find $el | xargs $GREP -nH -e "$str" | spaceafter | onespace $sp1
}

# xfind over a tree of [project] directories; getting down to src, src/app, .vscode; bypassing dist, lib...
# could probably just put those into XFIND_EXCLUDE
# findtree "ext" sub target
# findtree "*.ts" -d src/app foo
function findtree() {
    local ext="*.ts"
    if   [[ "$1" =~ [*] ]]     ; then ext="$1" ; shift ; 
    elif [[ "$1" =~ [*][.]* ]] ; then ext="$1" ; shift ; fi
    local sub=""
    if [[ "$1" =~ -.*d ]] ; then shift ; sub="/$1" ; shift ; fi
    for dir in ./* ; do { if [[ -d "./$dir" ]] ; then xfind "$ext" "$1" "$dir$sub" ; fi ; } done
}

# Findts {-i} regex (typescript)
function findts() {
    xfind "*.ts" "$@"
}

# Search [ng] project sources [*.ts]: (because Apple finder ignores .ts files)
function findtsrc() {
    findtree "*.ts" -d "src" "$@"
}

# jsfind {-i} regex (javascript)
function findjs() {
    xfind "*.js" "$@"
}

function onespace() {
    # $1==true ? compress all spaces : compresss \t -> ' '
    if [[ "$1" == "true" ]] ; then 
	tr '\t' ' ' | tr -s '[:space:]'
    else
	tr '\t' ' '
    fi
}

function spaceafter() {
    sed -e 's/\(.*:[0-9]*\):\([^ ]\)/\1 \2/'
}

````

**Comment by jackpunt** [comment]
Eh, I'm an idjit:  onespace() and spaceafter() were in a different file:
[edit: now included in code/comment above]

````
function onespace() {
    # $1==true ? compress all spaces : compresss \t -> ' '
    if [[ "$1" == "true" ]] ; then 
	tr '\t' ' ' | tr -s '[:space:]'
    else
	tr '\t' ' '
    fi
}

function spaceafter() {
    sed -e 's/\(.*:[0-9]*\):\([^ ]\)/\1 \2/'
}

````
