### ISSUE TITLE
Use the cluster module, Typescript will compile a default property that does not exist

### ISSUE THREAD

**Issue by NaOHCC** [microsoft/TypeScript#47610]
# Bug Report

### 🔎 Search Terms

cluster, native module

### 🕗 Version & Regression Information
tsc version 4.5.5
node version 16.13.2
This is the behavior in every version I tried, and I reviewed the FAQ for entries about node module.

### 💻 Code
```
import cluster from "cluster";
import { cpus } from "os";

cluster.setupPrimary({
    exec: "worker.js",
});
let numCPUs = cpus().length;
for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
}
```

### 🙁 Actual behavior
The following is the content of the file compiled using the tsc command. 
```
// mycluster.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const cluster_1 = require("cluster");
const os_1 = require("os");
cluster_1.default.setupPrimary({
    exec: "worker.js",
});
let numCPUs = (0, os_1.cpus)().length;
for (let i = 0; i < numCPUs; i++) {
    cluster_1.default.fork();
}
```
Use the ```node mycluster.js``` command. Node gives an error
```
cluster_1.default.setupPrimary({
                  ^

TypeError: Cannot read properties of undefined (reading 'setupPrimary')
```
### 🙂 Expected behavior
The default property of cluster should not be compiled out.
```
cluster_1.setupPrimary({
    exec: "worker.js",
});
```

**Comment by MartinJohns** [comment]
https://stackoverflow.com/a/41148675

**Comment by NaOHCC** [comment]
Thanks!! I went to check the TypeScript definition file `@types\node\cluster.d.ts`, it is different from other files, it uses `default`.
```TypeScript
declare module 'cluster' {
// ...
    const cluster: Cluster;
    export default cluster;
}
```

**Comment by zWaR** [comment]
@NaOHCC How did you end up importing the `cluster` module in your TypeScript code? Could you give me an example, please?
