### ISSUE TITLE
Typescript 1.5/1.6 hitting wrong debug point (visual studio 2015)

### ISSUE THREAD

**Issue by pranaydutta89** [Microsoft/TypeScript#4761]
I am building an Apache cordova project in vs2015 and the project has gone little big with many .ts ,.d.ts files, the problem is it is always hitting the wrong debug point , however the stack trace shows perfect,but the file is always wrong,
        This is not happening in case when i debug app in windows phone but in case of android and ios its always hitting the wrong debug point (device or simulator both)

[Stackoverflow question](http://stackoverflow.com/questions/31741678/typescript-project-hitting-wrong-debug-point-visual-studio-2015-cordova-project)

**Comment by mhegazy** [comment]
@pranaydutta89 can you provide more details? can you share your project? or a sample project that exhibits the same issues?

**Comment by pranaydutta89** [comment]
my project has gone big cannot share that up and also  ,in case of 4-5 files it doesn't show up but when it goes beyond approx 20 files it shows up the failure ,and this thing is only happening in case of android and ios ,windows works fine

**Comment by mhegazy** [comment]
@mbraude any idea what is going on here?

**Comment by mbraude** [comment]
Hi @pranaydutta89. Sorry for your trouble. I would love to investigate this but we need to see a repro to dig any further. There could be any number of things causing this, from bad source maps to something in your build process, to an actual product bug.

**Comment by pranaydutta89** [comment]
@mbraude  ok i will try to build a repo ,give me a couple of days, just to point that is when i debug windows app it works fine, in case of other platform it is messing things up everytime

where should i upload the repo afterwards???

**Comment by basarat** [comment]
> where should i upload the repo afterwards???

*unofficial response:* create a temp github repo

**Comment by mhegazy** [comment]
@pranaydutta89 any news? is this still an issue?

**Comment by pranaydutta89** [comment]
no it has been since vs for cordova update 3
