### ISSUE TITLE
`this` possibly not being inferred properly from `ThisType`

### ISSUE THREAD

**Issue by Myrdden** [microsoft/TypeScript#47628]
# Bug Report

### 🔎 Search Terms

ThisType inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ThisType

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAshwEMAKAnA9mKAeAKgGihwAsBLAZygF5DSykEUEBbeCFHcCXAPm6qgDeAWABQUcVABmaNAH4AXFDLAUJAHYBzANyiJUAEYMFSleu26JANwQAbAK4RFAChxQAZDXIdIuWtwCUOiIAvkGioJCw8MjoYBS4BMTk-Dh81MJiEgDaUGCxUOpQANYQIGiShFAAuopwiKgYuFl5GFWJfkGhoqKSdmoAxsAkaGpQLIhDAF7QuFAQAB7AEGoAJhRo+gBWEIN8Thvbg4r4Y9FktdENcVj0KEO2PIkBipZoJCuCXSKi-SPKUAd+Bk9AhFAByBD6forCBgvAWcT6ZwjRxQNR2Jj6NgEYAAdzQinRmLY-ioexRUAA1FA8Wh-KIvqJxggphB9lsCMCJEjBFBrPZUb0BkMRlAnKSuXpxMBaEEpRIUPA7ChRgAmOUSYJQYIMwJAA)

### 💻 Code

*(This is a rather boiled down example that I'm maybe 85% sure demonstrates the issue fully)*
```ts
type MetaProp <T, This = ThisParameterType<T>> = {
    foo?: string;
    bar?: string;
    value: (T & ThisType<This>);
};

type MetaProps <T, This = T> = {
    [ prop in keyof T ]: MetaProp<T[prop], This>;
};

function metatize <T extends object> (object: T, metas: MetaProps<Partial<T>, T>): void {};

const obj = {
    a: 'abcde',
    b: (one: number, two: number) => (one + two)
};

metatize(obj, {
    b: { value: function () {
        this;
        return 2;
    } }
});
```

### 🙁 Actual behavior

This is looking to be an IntelliSense issue, but as far as I'm aware IntelliSense (in VSCode and the like) is powered by ts-server which lives here so I think this is the right place to be...

In any case, when using Vim w/ CoC & VSCode, the value of `this` inside of the function assigned to value in `metatize` is simply `any`. However, in the playground, it's given as
```ts
MetaProp<((one: number, two: number) => number) | undefined, {
    a: string;
    b: (one: number, two: number) => number;
}>
```
Whereas in my actual production code where I ran into this issue, `this` is being interpreted as (it's equivalent) of the entire `MetaProps<Partial<T>, T>` type, which then causes compilation to fail when I try to use it as just T. So I'm not entirely sure what's going on, it seems like everywhere I try this I get a different result. In all examples, IntelliSense on `value` in `b: { value: ... }` in that function argument does correctly display
```ts
(property) value: ((one: number, two: number) => number) & ThisType<{
    a: string;
    b: (one: number, two: number) => number;
}>
```
which would lead me to believe that the proper type of `this` *should* be available there.

### 🙂 Expected behavior

I would expect, if I'm understanding how `ThisType` is actually supposed to work, that the type of `this` within that function would be
```ts
{
    a: string;
    b: (one: number, two: number) => number;
}
```
Because that's the type being passed to the `This` parameter of the generic, and is what's present in `ThisType` in all examples.

Unless, of course, this is not actually what `ThisType` is supposed to do at all. Though I'm not sure what it *does* do, if that's the case...

**Comment by fatcerberus** [comment]
This is what `ThisType` does ([Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt0QJ7IN4BQyxyMmAFAJQBcyAbusACYDcBAvgQaJLIigCE4UJviIkARsNoBnMFFABzNpwIJ0IOaUwBGWhiy4AvGJLb0VU2ZJgAFsBlsA9E+vIAegH5xxTqvWaYOYATPqYOMgAZMgAKvYyMdgADhAAPEIiAHzIJoRmZBaUVm52Ds6u1l4+yH4EQA)):

```ts
interface Fooey {
    foo(): void;
}

interface Bard {
    bar: string;
}

const foo1: Fooey = {
    foo() {
        this;
//      ^? this: Fooey
    }
}

const foo2: Fooey & ThisType<Bard> = {
    foo() {
        this;
//      ^? this: Bard
    }
}
```

`ThisType<T>` modifies the methods of object literals, it's not meant to be used on function types directly.

**Comment by fatcerberus** [comment]
For bare function types you can just include the `this` type directly, e.g.: `(this: Bard, x: number) => void`

**Comment by Myrdden** [comment]
Ahh, I see. So for the sake of completeness it looks like to fix my example situation above I'd do something along the lines of this:
```ts
type MetaProp <T, This = ThisParameterType<T>> = {
    foo?: string;
    bar?: string;
    value: T;
} & ThisType<This>;

type MetaProps <T, This = T> = {
    [ prop in keyof T ]: MetaProp<T[prop], This>;
};

function metatize <T extends object> (object: T, metas: MetaProps<Partial<T>, T>): void {};

const obj = {
    a: 'abcde',
    b: (one: number, two: number) => (one + two)
};

metatize(obj, {
    b: { value: function () {
        this;
        return 2;
    } }
});
```
And... Yes! That does appear to do exactly what I want, in my production code as well. Wonderful! Thank you for that insight @fatcerberus. I'll close this as just a misunderstanding on my part.
