### ISSUE TITLE
Support IntelliSense for JSDoc `@property`/`@prop` tags

### ISSUE THREAD

**Issue by sixclones** [microsoft/TypeScript#47622]
# Suggestion

## 🔍 Search Terms

+ JSDoc
+ `@property` / `@prop`
+ suggest / suggestion
+ complete / completions
+ IntelliSense

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Enable IntelliSense inside JSDoc `@typedef`/`@property` tags.

`@param` is already supported, `@property` doesn't seem too different.

## 📃 Motivating Example

<img width="521" alt="VSCode screenshot showing completion on @param JSDoc tag" src="https://user-images.githubusercontent.com/19307232/151223489-71dca886-3cf9-4ea5-a9ce-8820b2a49ce2.png">
<img width="336" alt="VSCode screenshot showing no completion on @property JSDoc tag" src="https://user-images.githubusercontent.com/19307232/151223498-d7ca5669-711b-416f-9bc3-89c2767c2d79.png">

The completion on `@param` is really useful! When you have complexes objects or types that you are using across your app, `@typedef` is the perfect tag to define a custom type. But the completion is missing from `@property`. Even `@typedef` got completion!

<img width="166" alt="VSCode screenshot showing completion on @typedef JSDoc tag" src="https://user-images.githubusercontent.com/19307232/151224372-5ff4b28b-1159-46c7-9227-6071608b05be.png">

## 💻 Use Cases

This would help significantly while writing `@property` tags on `@typedef` definition.

Right now, I don't have any workaround.

Thanks

**Comment by a-tarasyuk** [comment]
Looks similar to https://github.com/microsoft/TypeScript/issues/46606. The fix should be in the [`4.6-beta`](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116&filetype=js#code/PQKhCgAIUgBAXAngBwKYBNUDNIG8DyARgFaoDG8AvpAIJQyzIBOA9mk0ngHYCuAtoVRNqAQ3rBw4UBGhwkaTDgIlyVSACF6cZmyGdcvAUNHjJ0rQhQZseIqQrUAYixYWd7fZVNA)

/cc @RyanCavanaugh

**Comment by sixclones** [comment]
Absolutely, sorry I didn't found this issue before posting mine.
I close this one.
