### ISSUE TITLE
Comma Operator breaks Functions that return `never`

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#47634]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.4#code/GYVwdgxgLglg9mABAUwB4ygCgJQC5FjIBuyATogN4BQitiUAFqXAO4HJsCipzpOA3FQC+VKqEiwEiADZwA5gH1GyMArQYc+QiXLU6iCAgDOcacgB0suQJp11WbIJFjw0eEitKGKteigLDAFtAgENNdh1KW1oAehj9BMSk-QA9NLTEbl58AEFEcTcpUmQoEFIwGDA5RABybTIagxCwMDgoRAYQkkQQxGKQiE6AIzMUMAATRAAHOEqoc0wAJgBWAGYAFmxog2NTCyscABoUPxshIA)
    
### 💻 Code

```ts
function exit(): never {
    throw new Error();
}

function log_then_exit(): never {
    console.log();
    exit();
}

function log_then_exit_comma(): never {
    //                          ^^^^^ A function returning 'never' cannot have a reachable end point
    console.log(), exit();
}
```

### 🙁 Actual behavior

Error

### 🙂 Expected behavior

No Error

Related : #44487

**Comment by fatcerberus** [comment]
I believe this is expected because (per https://github.com/microsoft/TypeScript/pull/32695):

> A function call is analyzed as an assertion call or never-returning call when
>
> * **the call occurs as a top-level expression statement**, and
> * the call specifies a single identifier or a dotted sequence of identifiers for the function name, and
> * each identifier in the function name references an entity with an explicit type, and
> * the function name resolves to a function type with an asserts return type or an explicit never return type annotation.

In your example, the call `exit()` is part of a comma expression, and thus not a top-level statement.
