### ISSUE TITLE
Array index has different types on same object

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#47636]
# Bug Report

### 🔎 Search Terms

Array index

### 🕗 Version & Regression Information

4.5.4

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/DYUwLgBAhgTjBcEDaByKKA0EUCNPYGMUBdCAXmTX12qOIFgAoJgMwFcA7AsASwHsOEMCADOYADwAVCCAAewjgBMREAIJwoAT3FQOmgHz6AFLAQRJWdl0RG+ABzCIA3sgCSSuRB6CA1iE18LObEzkwQ4V4esojuinJMAL4QCUgcbAC2OCAwxACU5PoQAG58PIr5TmERVgRGlYwRjZFx0RAADFXhCbmJTEzCYiZwWLYO+WSF9Y32YAB03i3k7Ym5QA)

### 💻 Code

```typescript
let arr: ['a', 'b', 'c'] = ['a', 'b', 'c']

function test<T extends Array<any>>(arr: T, func: (opt: { [Index in keyof T]: {
    index: Index
} }[number]) => void) {
    func({
        index: 0  // index is number
    })
}

test(arr, (opt) => {
    opt.index = 0 //error, index is string on the same object
})
```

### 🙁 Actual behavior

Types of `opt.index` are different.

**Comment by ruojianll** [comment]
```typescript
let arr: ['a', 'b', 'c'] = ['a', 'b', 'c']
type T = typeof arr
type Z = { [index in keyof T]: T[index] }

/*
type Z = {
    [x: number]: "a" | "b" | "c";
    0: "a";
    1: "b";
    2: "c";
    length: 3;
    toString: () => string;
    toLocaleString: () => string;
    pop: () => "a" | "b" | "c" | undefined;
    push: (...items: ("a" | "b" | "c")[]) => number;
    ... 26 more ...;
    [Symbol.unscopables]: () => {
        ...;
    };
}
 */
```
The index type of Z is number but the key of 'abc' is string.

**Comment by IllusionMH** [comment]
You need to filter out methods etc. I think https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#key-remapping-in-mapped-types can help with this one
