### ISSUE TITLE
Unclear type compatibility of primitives with generic mapped types

### ISSUE THREAD

**Issue by ab-pm** [microsoft/TypeScript#47633]
# Bug Report

### 🔎 Search Terms

primitive type partial object mapped type

### 💻 Code

I was trying to define my own `DeepPartial` generic type mapper. Here are three attempts (and, for comparison, the builtin `Partial`):
```ts
export type DeepPartial1<T> = T extends object ? { [K in keyof T]?: DeepPartial1<T[K]> } : T;
export type DeepPartial2<T> = { [K in keyof T]?: DeepPartial2<T[K]> };
export type DeepPartial3<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial3<T[K]> : T[K] };

function example0<T>(x: T): Partial<T> {
    return x;
}
function example1<T>(x: T): DeepPartial1<T> {
    return x;
}
function example2<T>(x: T): DeepPartial2<T> {
    return x;
}
function example3<T>(x: T): DeepPartial3<T> {
    return x;
}
```

[⏯ Playground Link](https://www.typescriptlang.org/play#code/FAUwHgDg9gTgLgAjgTwiBAREIIAUCG8AlvgDYCMAPACoB8CAvAtQuHCAHYAmAzglACMAViADGiAPwIA3ggDaAaQREOCANYhkUAGbMAuhIBcmbHkJwSFGor30AvgmPUA3KEixEKNCZwFiZACYaeiZZRWVVDS1dagNjLF9zSyDqG3tXcGh4JFR0BLN-UgBmYMYZeSUVdU0dfSNmG1Ywdm4+QRFxBCl8vwsyEtSFW0cGoYQ7V2BtAFcOcSIoVXB8AFsIUhAABmCACjAnAEpjXstS6WAES4QYEDhpmFUwVzsp2fnFptX1kCo6PcP4qYTmRfvRzldrrd7o9nq85hYPss1hsUrR-swjj4Cn1SKiZBcrjc7g8EE9gC8ZvCFkswF8NgM0fsMYDEoUGfiIUToaTYcBRIseIgwJsykjvpsdgByQUwFQAc0lCHwfA40xWAhAMAQAB8EDL5TqEAIoFANvgOAdXPyOILSeRRbTkT8pfqOAqlSq1RqtbrXXLDcbTSBzZa+QKhQEHXSQAEXXBZW7FcqEKr1ZrDX6AyazRareHSUUo06inGE+7k6nvRn4wbdYGc6HhQA6OBQADKNbdO0b5Bb7c7cu7rjAAT7HbLQ+AYCKY4Hk8p71U0x4IAAcl7NejK5rMQA3KBELgyF7LtcbmA7MUbCXkA4HYCn9dpi9X523++P8+Xx3fWPvh8rk+3rftGJbvkAA)

Passing a primitive value to the `example` function should correctly infer the same primitive type to be returned. `DeepPartial<number>` should be equivalent to `number`, not to a mapped object type.
This is why I chose implementation 1 with the type condition directly on `T` - and calling `example1` with `string` or `string | number` for the type parameter does indeed infer that very same type as the result type of the call, unlike `example2<string | number>(…)` returning `DeepPartial2<string | number>`.

### 🙁 Actual behavior

Using `DeepPartial1`, which I thought is the correct implementation, doesn't work. On the `return` statement of the generic `example1` function, tsc complains:
```text
Type 'T' is not assignable to type 'DeepPartial1<T>'.(2322)
```
(also this message is not very helpful - there's no indication which properties are missing or incompatible)

### 🙂 Expected behavior

Using `DeepPartial1` in the generic function should typecheck just fine.

### Questions

I don't understand three things:
* why the compiler complains about `T` not being compatible with `DeepPartial1<T>` - it seems to be a proper subtype to me regardless whether `T extends object` or not. Is it a bug or am I missing something?
* why the similar construction in `DeepPartial3` does work, instead of causing the same problem on the first nesting level
* why `Partial<number>` is considered compatible with `number` - it seems that mapped helper types like `Partial` should only be used on objects. Why and how does this work, where is this behaviour documented?

**Comment by fatcerberus** [comment]
It's a design limitation - conditional types predicated on a generic type parameter are "deferred" (i.e. not actually evaluated) while in a generic context.  Essentially, TS doesn't know whether or not `T` is assignable to `DeepPartial1<T>` because it hasn't resolved the conditional type yet (because it doesn't know what `T` is) and thus doesn't know how the input and output types relate--and assumes the worst.  In cases like this you should use a type assertion.

**Comment by ab-pm** [comment]
@fatcerberus Ah, interesting. However, that doesn't explain why `DeepPartial3` works - why then does TypeScript know that `T[K]` can be assigned to `T[K] extends object ? DeepPartial3<T[K]> : T[K]`?

**Comment by fatcerberus** [comment]
*That* I'm not sure of.  You would think so though, right?  Someone else more knowledgeable about the internal workings of the compiler will need to chime in on that one. 😅. I presume it has something to do with the mapped type being known by the compiler to be homomorphic (`[K in keyof T]`) but I might be off-base on that.

I do seem to recall there was a special rule where if the compiler can figure out that a type is assignable to both sides of a conditional type, assignment is allowed even while deferred, but I don't know what triggers it.

**Comment by ab-pm** [comment]
Oh, thanks! I didn't know about this neat little trick. Unfortunately, I think I would want my `DeepPartial` to be distributive, `DeepPartial<number | SomeInterface>` should be equivalent to `number | DeepPartial<SomeInterface>`. (Although apparently it is anyway, given `{[K in keyof number]?: number[T]}` is equivalent to `number` for some reason - that was my third question).

Also I don't understand why the compiler assumes that `T` can be a union but `T[K]` can't - but I think this is more of a guessing game than what one would expect in a sound type system.

**Comment by fatcerberus** [comment]
> Also I don't understand why the compiler assumes that `T` can be a union but `T[K]` can't

It's not that `T[K]` can't be a union - it's that `T[K] extends ...` doesn't trigger the distributive behavior (because `T[K]` isn't a bare type parameter), so TS can just go "okay, `T[K]` is assignable to both sides of the conditional type regardless of what it is so I'll allow it despite it being deferred."  It won't take that shortcut for distributive conditional types.

**Comment by fatcerberus** [comment]
For what it's worth, soundness is explicitly not a goal of the type system - it's designed to catch common errors in idiomatic JS and so you'll find there are a lot of these kinds of guessing games w.r.t. what the rules are.  It's been my observation that beyond the basic structural type system which is fairly well-defined for concrete types, things are largely guided by pragmatism in the more abstract corners of the system.

**Comment by ab-pm** [comment]
Yes, that's what I meant - I know that TypeScript doesn't aim for a sound type system. Unfortunately that imo makes it very unpredictable when attempting to define more advanced types for generic functions, a game of try-and-error :-( But I'll stop my rant here and continue trying to learn about all the undocumented intricacies of the compiler implementation…
