### ISSUE TITLE
Documental changes needed

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [microsoft/TypeScript#47638]
# Bug Report

### 🙁 Actual behavior

A few places had wrong prepositions used and commas missing.

### 🙂 Expected behavior

Lesser gramatical mistakes and better readability

**Comment by MartinJohns** [comment]
https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/pull_request_template.md

> ** Please don't send typo fixes! **  
> Please don't send a PR solely for the purpose of fixing a typo, unless that
> typo truly hurts understanding of the text. Each PR represents work for the
> maintainers, and that work should provide commensurate value.

**Comment by ItsAdityaKSingh** [comment]
Yes! I saw that, but there were some changed words and commas that needed adding, and I couldn't find any issue for it. So as a starting contribution, I opened an issue for it, fixed them and created this PR.

**Comment by jcalz** [comment]
If you want to be helpful to the TS community, the best thing you can do is to close this issue and #47637.  The TS team will undoubtedly do so soon, and it would be helpful to everyone if you save their time by doing it yourself.  If you're interested in contributing you might want to look at the [issues labeled "Help Wanted"](https://github.com/microsoft/TypeScript/labels/help%20wanted).  Good luck!

**Comment by RyanCavanaugh** [comment]
Replied in the PR.
