### ISSUE TITLE
`__export` helper should ignore `default` when targeting ES3/ES5.

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#4763]
http://www.ecma-international.org/ecma-262/6.0/#sec-getexportednames

**Comment by ahejlsberg** [comment]
The type checker does ignore `default` when processing `export *`. However, the `__export` helper we emit when targeting ES3/ES5 doesn't, but that matters only if you consume the generated down-level ES3/ES5 code from JavaScript. Is that the issue?

**Comment by vilic** [comment]
Yes. Updated the title to clarify. :D

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be affecting anyone. You can also provide your own helper if there's a compliance scenario where this is important.
