### ISSUE TITLE
option to omit `Promise` from return type on `async` functions

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#47630]
# Suggestion

## 🔍 Search Terms

omit promise return type async

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
when functions that return promises use the `async` keyword, you should be able to define its return type without wrapping it in a `Promise` type, as it's redundant information that's already made clear by the `async` keyword

#### before
```ts
const doThing = async (): Promise<string> => {
    //...
}
```
#### after
```ts
const doThing = async (): string => {
    //...
}
```
### function types
perhaps additional syntax could also be added to types to make them consistent with this behavior:
#### before
```ts
type Foo = () => Promise<string>
```
#### after
```ts
type Foo = async () => string
```

## 💻 Use Cases

- removes unnecessary/redundant clutter from function signatures

**Comment by RyanCavanaugh** [comment]
Duplicate #45387, #43303, #40425, #32551, #7284
