### ISSUE TITLE
Make true absolute imports relative to source roots work

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#47646]
# Suggestion

## 🔍 Search Terms

* absolute import 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The code `import foo from '/foo';`

should import `{sourceRoot}/foo`

where `sourceRoot` is `{pwd}/src`

all configurable via `tsconfig.json`.

## 📃 Motivating Example

It just seems obvious to me that `/foo` means `./src/foo` relative to the project root, assuming src is the root source dir.

## 💻 Use Cases

I was pretty sure we could do this? I vaguely remember doing this like 4-5 years ago in VS Code in a TypeScript project? But I can't find any code to do this. Everything I find online says either import "@foo/etc" or "foo/etc"

**Comment by fatcerberus** [comment]
Since TypeScript doesn’t change import specifiers in the emitted JS (even with `paths`), `import … from "/foo"` means whatever it means at runtime.  In the browser it’s relative to the current subdomain; in Node I assume it’d be relative to the file system root, if it works at all.

**Comment by sdegutis** [comment]
I have a runtime where it works as I described above.

**Comment by fatcerberus** [comment]
If your runtime supports it then adding this to tsconfig should do the trick:

```json
        "paths": {
            "/*": [ "./src/*" ]
        },
```

**Comment by sdegutis** [comment]
I have that, and in VS Code, auto-complete in the path and double-click on the path does nothing.

**Comment by sdegutis** [comment]
That works for when auto-importing from an absolute path. But it doesn't work when ctrl-clicking an absolute path, it doesn't find it in VS Code.

That said, I don't use this feature of my runtime anymore since the absolute paths don't seem to auto-import (and it's generally not very helpful). So feel free to close this.
