### ISSUE TITLE
--save will not work if packages are already installed

### ISSUE THREAD

**Issue by matthewharwood** [Microsoft/TypeScript#4764]
Say I want to install a package and I run `tsd install  angular`  

By mistake I forgot to use the `--save` flag.

If I try to re-run `tsd install angular --save` the `tsd.json` is not updated with install commits.

A user must delete installed angular package and then rerun `tsd install angular --save` for the installed package commits to appear inside `tsd.json`

**Comment by DanielRosenwasser** [comment]
Hi @matthewharwood, `tsd` isn't actually managed by the TypeScript team - it's managed by DefinitelyTyped. You can file an issue with them at https://github.com/DefinitelyTyped/tsd/issues/new
