### ISSUE TITLE
Variable type can not be determined when I set the generics type of a function

### ISSUE THREAD

**Issue by NicoKam** [microsoft/TypeScript#47648]
# Bug Report

### 🕗 Version & Regression Information

- version: 4.5.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiDyAjAVlAvFA3gKClAhgFxQB2ArgLaIQBOA3LlIsQM7A0CWJA5g3gMbFEAe2EAbCPhIMAvtmwAzMiX7AOwklAUkAjAB4AKgBooAaQggoEAB7AIJACYsoAawvCFUA+lfvPBgD4ACjcQYnMQE358MTFEfH4XYiCANxiyCGIDAG0IgF0ASnQAqBThDgcinGw5RWVVdU1tAHUOYAALABEIBXwyMWADcAhDHzgkZBMIq1t7J18QDy8fUKXAkItwiyiYuISkqFT0zK9ci0Li0vLKrHla7X1xlGCAcnwXkzSxDMucPAB6f5QAAGXwywKgoEgUGiJBIwmATGgDggdhoFC4EAcADoagUGPIWm0uj0+gMhpAgm8PqVjr9GICQWCIBCOM5+MIaDQIKoxJYUZwUliCM5geQqLRgbiZPigA)

### 💻 Code

```ts
type MyObj = {
  a: number;
  b: string;
  c: boolean;
}

function fn1<T, Key extends keyof T = keyof T>(key: Key, callback: (value: T[Key]) => void) {}

function fnWithDefaultType<T = MyObj, Key extends keyof T = keyof T>(key: Key, callback: (value: T[Key]) => void) {}

fn1<MyObj>('a', value => {
  // `value` type cannot be determined.
});


fnWithDefaultType('a', value => {
  // `value` is correctly derived as `number`.
});
```

### 🙁 Actual behavior

When I call `fn1`, the type of `callback`'s argument can not be determined, even though I set the first parameter to `'a'`.
The type of `value` is recognized as `number` | `string` | `boolean`.

![image](https://user-images.githubusercontent.com/6757303/151517015-f81e6ac5-a691-4ced-946a-5925facdfde7.png)

### 🙂 Expected behavior

The type of `value` should be `number` as the type `MyObj`. Just like the function `fnWithDefaultType`.

![image](https://user-images.githubusercontent.com/6757303/151517068-18a71c22-97d7-416f-93da-eb0cddb6c660.png)

**Comment by MartinJohns** [comment]
This is working as intended.

In your first example you specified the type arguments explicitly. This is **all or nothing**. Since you provided one (`MyObj`), the second type parameter must be provided as well. And as you didn't provide one, the default type `keyof T` is used.

You want #26349.

**Comment by jcalz** [comment]
Or #26242

**Comment by NicoKam** [comment]
@MartinJohns @jcalz Thank you so much. I am happy to see that a large number of people are focusing on the same issues. But I am so sad when I see the PR is still stagnant. So now it is no way to let the compiler to infer the second type, is it?

**Comment by MartinJohns** [comment]
Correct, there's no way.
