### ISSUE TITLE
Overlooks arbitrary value for type asserted property (in object spread)

### ISSUE THREAD

**Issue by wclr** [microsoft/TypeScript#47650]
# Bug Report

### 🔎 Search Terms

Checked for 4.5, and latest 4.6-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5ICwAUAC6QAOKA8gEYBWoAvKAN6migBm+cAtgC5QmMvgCWAO1SdQZOMNETppAL6lSFaqAAi4-C1AAiXgKOgAPsflGNJeJNGgE+4XoOsjN0AENs70hA5PBEffhRuOHxBQLBkGAAbH0JYOEcyZ1ddfTtSeKSUhyc4RmF6BjsijKFQcsMOEi4AOhaShgAaWQBtF3wAXWEARnbQIMk4UAI+fBG6AFcMzBw4OYSEUDpiEnUSWODxbAPQAHcogGspVF9sJAAPShgyJAQY+zSnXoAmN31DLzhbLsgVVQPxvrVGPVZC0mm1Oo1QD19J8BqBhqMwFMotcRMtVutNmpSEA)

### 💻 Code

```ts
type Obj = {
  from: string
  to: string
}

type Dir = "from" | "to"

const dir: Dir = "to" as Dir
// the same for:
// declare const dir: Dir


declare const obj: Obj

const m: Obj = {
  ...obj,
  [dir]: 1, // no error, but should be
}

// this is working as expcted:
const dir2: Dir = "to"


const m2: Obj = {
  ...obj,
  [dir2]: 1, // error as should be
}


```

### 🙁 Actual behavior

Should not allow arbitrary value.

### 🙂 Expected behavior

Overlooks arbitrary value for type asserted property in object spread.

**Comment by MartinJohns** [comment]
This sounds very much like #32236.

**Comment by wclr** [comment]
Yes, seems it is the same, wonder why it is not fixed since 2019, this creates not pleasant cases when such a prop comes from fn arguments.
