### ISSUE TITLE
Missing parentheses in mapped type for combination of types should be invalid syntax

### ISSUE THREAD

**Issue by amunger** [microsoft/TypeScript#47654]
# Bug Report

When creating a mapped type that combines the properties of two types, parentheses are needed around the two types. If you leave them out, the syntax is still valid, but you've just created an `any` type.

```
type FieldDescriptions = {
  [key in keyof T1 & T2]: string;
};
```

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/FAFwngDgpgBAKgRhgXhgb2DGAzAllAGwBMEAuGAOwFcBbAIygCcBuYAX1dEljgCYV0mHPmK9y1ek1YdgXaDABiIogBEoAZwDGjXBBC4A9hXUCMWAPTmYmg40ZRNIGOrAUQAQwAeMAO4GqxDAMpEKWMADaANZQYDC4FDDRYAbYMAAUiDAAZPC8AJQAuuTqIDoUAOasWFExcQlJKfBIOXxFzqXxleycNsZO2ETq5EqEqhrauvpGJqhmMOXujHTu5VDkAETqABb+gQx1AG7uBLhE6wA03bK96gYEUAB0BAblaQBSAMoA8gByDyVlcq4bBgNIDdR5PJVGBAA)

### 💻 Code

```
type T1 = {
  field1: number;
};

type T2 = {
  field2: number;
};

type FieldDescriptions = {
  // correct syntax would be:
  // [key in keyof (T1 & T2)]: string;
  [key in keyof T1 & T2]: string;
};

const fds: FieldDescriptions = {
  garbage: "should be invalid",
};

console.log(JSON.stringify(fds));
```

### 🙁 Actual behavior

compiles and runs fine, no errors

### 🙂 Expected behavior

should fail compilation

**Comment by fatcerberus** [comment]
I assume without the parens it’s parsed as `key in (keyof T1) & T2`.  `any` comes about as a result of mapping over `never`.

**Comment by amunger** [comment]
thanks for the explanation, that makes sense. Still feels like something that could get you into trouble by losing type checking, but maybe a more of a linter issue.
