### ISSUE TITLE
Unnecessary, misleading expansion lines for a keyof generic used in a template literal

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#47668]
# Bug Report

### 🔎 Search Terms

keyof generic template literal type symbol

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics and assignability

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIHELADwBUB8UC8UAGA5sgCQDeA1vAPYBmUaAvngNwCwAUEA)

### 💻 Code

```ts
type KeyGet<T> = `get${keyof T}`;
```

### 🙁 Actual behavior

Notice the fourth `Type 'keyof T'` line onward. Seems unnecesary?

```ts
Type 'keyof T' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
  Type 'string | number | symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
    Type 'symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
      Type 'keyof T' is not assignable to type 'number'.
        Type 'string | number | symbol' is not assignable to type 'number'.
          Type 'string' is not assignable to type 'number'.
```

### 🙂 Expected behavior

```ts
Type 'keyof T' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
  Type 'string | number | symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
    Type 'symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
```

Note that if you replace `keyof T` with `string | number | symbol`, the error message is the expected behavior. [[playground link with replacement](https://www.typescriptlang.org/play?#code/C4TwDgpgBA0hIHELADwBUB8UC8UAGA5sgCQDeAzsAE4CWAdgVAD5R0CuAtgEYRXNTkQ3APYAbAL54A3AFgAUEA)]

```ts
type KeyGet<T> = `get${string | number | symbol}`;
```

```
Type 'string | number | symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
  Type 'symbol' is not assignable to type 'string | number | bigint | boolean | null | undefined'.
```

**Comment by RyanCavanaugh** [comment]
Weird
