### ISSUE TITLE
`Array.prototype.at` should return a more precise type when operating on a tuple

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/TypeScript#47660]
# Suggestion

Extracted out of #45512

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

Tuple Array.prototype.at

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`at` called on a tuple should work consistently with how index access on tuples works.

```ts
const tuple = [1, 2, 3] as const;
const element = tuple.at(1);
type T = typeof element; // currently `number | undefined`, ideally should be `2`

// Should also work with negatives.
const element2 = tuple.at(-1);
type U = typeof element2; // ideally should be `3`

// Compiler error or `undefined` for out of bounds numbers?
const element3 = tuple.at(100); // should be compiler error or
type V = typeof element3; // should be undefined
```

## 📃 Motivating Example

This is how tuples work when using index access.

## 💻 Use Cases

Preferring `.at(index)` to `[index]`.

## Partial Hack Solution

as suggested by @djmisterjon

```ts
interface ReadonlyArray<T> {
    /**
     * Returns the item located at the specified index.
     * @param index The zero-based index of the desired code unit. A negative index will count back from the last item.
     */
    at<U extends number>(index: U): this[U];
}
```

**Comment by fatcerberus** [comment]
I don’t think there’s a way to handle negative indices without the compiler special-casing `.at` internally (it’s just another method); you can’t do arithmetic on literal types.  The hack you posted is about the closest you can get.

**Comment by jcalz** [comment]
You *can* get negative indices to work for tuples (template literals to drop the minus sign and then use the numberlike string to index into a shifted reversed tuple), but nobody would want this in the actual TS library.  Still, enjoy:

<details><summary>⚙🛠</summary>

```ts
type Reverse<T extends readonly any[], U extends any[] = []> =
  T extends readonly [infer F, ...infer R] ? Reverse<R, [F, ...U]> : U

type At<T extends readonly any[], I extends number> =
  `${I}` extends `-${infer J}` ? [never, ...Reverse<T>] extends infer R ? J extends keyof R ? R[J] :
  undefined : never : I extends keyof T ? T[I] : never;

interface ReadonlyArray<T> {
  at<I extends number>(index: I): At<this, I>;
}
interface Array<T> {
  at<I extends number>(index: I): At<this, I>;
}
```

</details>

```ts
const tuple = [1, 2, 3] as const;
const element = tuple.at(1);
type T = typeof element; // 2
const element2 = tuple.at(-1);
type U = typeof element2; 3
const element3 = tuple.at(100); 
type V = typeof element3; // undefined
```

[Playground link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCuAHANgUxgXhgbQIwBoYAmQgZgF0YBDCGUSKAbgCh7oZU0BbVMWLBClQA6KlAAUuAJQsoAT0ToAKpjgLUIAGYduvJjAD0B4q3DtOqHnyKrBaURIC002epgBVW+q07LeoowwpKYMvlZQpLZI9mKSAAxxMszyijAAal6KPhbhpIFGMPBgACaomgCWYKjFzLW1KegASqgAbqgAThCoADwqqAAeULzFtO2oVMXgyHLUYHLY5ISeA0MltFRzC6oLAHyYzDAwfYPDo+OTYNM4lZodMABihMLPN3eNlAD8MM1tnT2NhGwjxgz2E7nIewAXB56m4AIJQXocE5rGBjCZTGYbeaLGAASWRqxGMDA8C4ACMOnsMAcYAADAAkAG88QBfOmE070xzM17tGAAKXZMC+2Cqvyezx+HS6vR2lBWXL53xFgs5qIA1qg5D5GqrGtgBZRIbSiqUKlVijBoeK7tCCYrNdqfCovkpsHjjSTWh0WMxKkN2poqMAmudMXD2u0qHI5TAmbSxN0HSjiaSKVTxJVSv17VJoQjulAABblCCEPE7Fis-18DrB0MwSPR2NKPYJw5JlNE2jpyntHZZkoDPMFxElssVqvMVlAA)

**Comment by RyanCavanaugh** [comment]
For positive indices I really don't see a reason not to use `a[n]` vs `a.at(n)`, and negative indices are not really representable today.

@jcalz ow my soul

**Comment by Jamesernator** [comment]
> and negative indices are not really representable today.

Like some could just be hard coded right for at least small numbers? This seems to work fine [in the playground](https://www.typescriptlang.org/play?isolatedModules=true#code/KYDwDg9gTgLgBAbwL4G4BQaAmwDGAbAQymDgHM8IAjAvRNOBuASwDsZgoAzAnEgJWAFMEFngCeAQShQCYgDwAVAHx1GauARhy+SgBQwAFkwDOALjjEhI8XADaAOkcEWY2wF0ANHD6fmLbCDmALQAjACU5nzoakhosWg4IsbwBHAAvHYhHgDknBAQ2V4IcIFwIQAMcEhuGsZwiSzJ6AlJ8ABe6Rr2mrqhYShAA):

```ts
declare global {
    interface ReadonlyArray<T> {
        at<R>(this: readonly [...any[], R], index: -1): R;
    }
}

const a = [1,'foo', { x: 10 }] as const;

const z = a.at(-1);
```

**Comment by RebeccaStevens** [comment]
Yeah, if support for positive indexes and -1 are added, that should handle most use cases.

**Comment by jcalz** [comment]
> @jcalz ow my soul

@RyanCavanaugh ah yes, the theological argument for #26382

**Comment by locriacyber** [comment]
The return type of `array[idx]` is wrong. Should I open an issue for this?

```typescript
let a = [Array(0), Array(0)]
let b: number = a[2]
```

**Comment by wesbos** [comment]
Had this problem, I think @Jamesernator's code should be:

```ts
declare global {
  interface ReadonlyArray<T> {
    at<R>(this: readonly [...any[], R], index: number): R;
  }
}
```

so it allows reference by any index

**Comment by jamiebuilds** [comment]
@wesbos That type is not correct, `R` will always be the type of the last item in the array:

```ts
const instruments = ["guitar", "drums", "base", "vocals", "keys"] as const
type Instrument = typeof instruments[number];
let value = instruments.at(2);
//  ^? "keys"
```

[[Playground](https://www.typescriptlang.org/play?target=9#code/JYOwLgpgTgZghgYwgAgEoTgEwPYgDYCeAglFHAQDwAqAfMgN4CwAUMm8nGBajQBRgALYAGcAXMigYc+AsgDaAOiVwQBOQF0ANGi3JQmCAA9xIAK4BbAEbQAlONQBuFgF8WLBLmFg9IL1AsQ4MLIALzyAEQA5qbAYHBQ4drhmP7mwonI4ZZwwhAZ4QBu2AhweOlJANYQBOnqHMEevmAsYAQADigAkk2pgd5hrR3YMD5+AUFyZlbQ6k7MeBDeBaWmKGGgY+Z9wgqcvABMNnMA9MdsAHoA-CxAA)]

**Comment by jamiebuilds** [comment]
@wesbos I think you want something more like this:

```ts
interface ReadonlyArray<T> {
    at<R extends ReadonlyArray<T>, I extends keyof R>(this: readonly [...R], index: I): R[I];
}
```

[[Playground](https://www.typescriptlang.org/play?target=9#code/JYOwLgpgTgZghgYwgAgEoTgEwPYgDYCeAglFHAQDwAqAfMgN4CwAUMm8nGBashAB6QQmAM5oMOfMVLlqNADTIAkrwEQhogNYQC2GGhoAKMAAtgwgFzIo43IWQBtAHTPUAXQWhM-S4oCUl1HtFVwBuFgBfFhYEXGEwZFA4qABXAFs1MFEAXgcAIgBzZOAwOChchVzMFNThcuRcgCM4YQg63IA3bAQ4PFqKrQJa1w5RGJA4ljACAAcURXGwaozkHKnZ3QSFpfBhexA0huhQljwIePae5JQcxMW0jOFHTgMAJl8w5gB6T7YAPQB+FhAA)]

**Comment by wesbos** [comment]
@jamiebuilds  hmm.. Works for me, your playground correctly logs the 3rd item

**Comment by Harpush** [comment]
@jamiebuilds Why do you need `this: readonly [...R]` and not just `this: R`?

**Comment by djmisterjon** [comment]
"Too Complex" mean, i am too lazy to code, but if you give me 1M$ , i will do it.

**Comment by reteps** [comment]
Wanted to add my own use-case, as I would like this behavior for these scenarios:

I want either of these behaviors:

```ts
export type NonEmptyTuple<T> = readonly [T, ...T[]];
const foo: NonEmptyTuple<number> = [1, 2];

const lastFoo = foo.at(-1); // I want type to be `number`, not `number | undefined`
```

```ts

const foo: number[] = [1, 2];
if (foo.length > 0) {
  const lastFoo = foo.at(-1); // I want type to be `number`, not `number | undefined`
}
```
