### ISSUE TITLE
"Organize imports" should remove import any alias that are aliased as the same name as the export

### ISSUE THREAD

**Issue by alii** [microsoft/TypeScript#47670]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2
- OS Version: Darwin arm64 21.2.0

Steps to Reproduce:

1. Write the following code:
```ts
import {item as item} from 'mod';
```
2. Run 'Organize Imports' on the file
3. Notice that the import's alias is not removed despite being the same name (unnecessary, unorganized). Expected to see
```ts
import {item} from 'mod';
```

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!

**Comment by alii** [comment]
Thanks team! Very swift :)

**Comment by a-tarasyuk** [comment]
@alii Even though I'm not part of the MS team 😃 - You're welcome!
