### ISSUE TITLE
broken js compatibility

### ISSUE THREAD

**Issue by d0b3** [microsoft/TypeScript#47671]
### 🕗 Version & Regression Information

Running my project in deno didn't work.
The example doesn't work in any TypeScript version in the playground.
The example works in Node, Chrome, Firefox, QuickJS.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/GYVwdgxgLglg9mABFApgZyogFASkQb0QCcUoQikAmAZgG5EBfAKBmGyiJBT3ycUVCRYCZOky4CxUuSQAWSvWbNW7MRICEAXk2J5eKAAsicAO6IA5GDiYAVmkQQ4AWwAOAQ1gAjADYpztJkcwNDhfADpvOABzLHM3b29EOABrcxwAoA)

### 💻 Code

```ts
function test () { return 23; }
if (true) {
  function test () { return 42; }
}
if (test() !== 42) throw 'not js compatible';
console.log('all ok');
```

### 🙁 Actual behavior

`test()` still returns `23` at the end

### 🙂 Expected behavior

`test()` should return `42` at the end

**Comment by IllusionMH** [comment]
It's just difference between sloppy and strict mode.
ES Modules are always executed in strict mode, TS emit (at least in playground) is in strict mode by default, however **DevTools Console is in sloppy mode**.

To make sure that your code runs in strict mode in console you can wrap it in IIFE with corresponding pragma.

```js
(function(){
    "use strict";
    function test () { return 23; }
    if (true) {
        function test () { return 42; }
    }
    if (test() !== 42) throw 'not js compatible';
    console.log('all ok');
})();
```

**Comment by d0b3** [comment]
Ok, thanks. I did not expect that.
