### ISSUE TITLE
Arrow function which return {} compiles to function without return statement 

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript#4767]
Hello!
![d2x1tgs](https://cloud.githubusercontent.com/assets/2854910/9837769/c5d4a676-5a52-11e5-80a4-f325cfbd25f8.png)
I think, generated function must have return statement
```javascript 
this.getData = function (params) {return { boundary: params.data; }};
```
@ahejlsberg  What do you think about it?
Thank you!

**Comment by Eyas** [comment]
This is an ES6 limitation, see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Returning_object_literals)

> Keep in mind that returning object literals using the consise syntax `params => {object:literal}` will not work as expected:
> ...

This is a limitation of the ES6 grammar that TypeScript unfortunately cannot deviate from.

**Comment by DanielRosenwasser** [comment]
As @Eyas said, you'll need to wrap the object literal in parentheses to ensure it's parsed as an expression.

**Comment by stepancar** [comment]
Thank you!
