### ISSUE TITLE
Contextual generic return type of an async function includes union members from the context that it shouldn't

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#47682]
# Bug Report

### 🔎 Search Terms

contextual typing, generic, async, return type, union

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[TS playground (latest)](https://www.typescriptlang.org/play?ts=4.5.4#code/CYUwxgNghgTiAEkoGdnwMoBcqZAWSjAAsBLAOxAB4AVAPngG8BYAKHngHsyARLkALngAKKIOoBKeAF56ANw4lgAblYBfVq1BI48AGYBXMmEwkuiODnyFSFGrSEkAtgAcIIRyDLYTXZIOZs8MggMLIkYCB+8ABK4BwwwJTImDDkAOYANMKSMvAACjAcjiTBdvAAPhjeVsTkVHS0Kiyq4oLyik2sYBa4BLW2DIgchpiCZPqOAEYh8Kr2AezBoeGR-qzs7LjJgigAnkbZ0vQFRSUgAHRwAFbgmEIARMhFCCEw9+IZ6xt7B1uYAExCSQLDbsOCYfQwMj5QrFYKXEA3YwPJ4eeCvd5NUGqT6BHFqcSdFgGIw+aG6MgARiBgiBRxhp1KgzAwy8Ywm0xgs3olSwlj6NiozNZo3g4ymMzmjC+4Mh0J+YEOuROcIu11uQgA5KiXjAYJrxGogA)
[TS playground (nightly)](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/CYUwxgNghgTiAEkoGdnwMoBcqZAWSjAAsBLAOxAB4AVAPngG8BYAKHngHsyARLkALngAKKIOoBKeAF56ANw4lgAblYBfVq1BI48AGYBXMmEwkuiODnyFSFGrSEkAtgAcIIRyDLYTXZIOZs8MggMLIkYCB+8ABK4BwwwJTImDDkAOYANMKSMvAACjAcjiTBdvAAPhjeVsTkVHS0Kiyq4oLyik2sYBa4BLW2DIgchpiCZPqOAEYh8Kr2AezBoeGR-qzs7LjJgigAnkbZ0vQFRSUgAHRwAFbgmEIARMhFCCEw9+IZ6xt7B1uYAExCSQLDbsOCYfQwMj5QrFYKXEA3YwPJ4eeCvd5NUGqT6BHFqcSdFgGIw+aG6MgARiBgiBRxhp1KgzAwy8Ywm0xgs3olSwlj6NiozNZo3g4ymMzmjC+4Mh0J+YEOuROcIu11uQgA5KiXjAYJrxGogA)

### 💻 Code

```ts
declare class StateMachine<T> {
  onDone: (a: T) => void;
}

declare function createMachine<T>(implementations: {
  services: Record<string, () => Promise<T> | StateMachine<T>>;
}): void;

// this is close to my original issue found in the real-world in XState
createMachine<{ count: number }>({
  services: {
    test: async () => Promise.reject("some err"),
    async test2() {
      return Promise.reject("some err");
    },
  },
});

// this is an additional test case I've figured out that behaves in a similar way.
function fn1(): () => Promise<{ count: number }> | StateMachine<{ count: number }> {
  return async () => Promise.reject('some err')
}
```

### 🙁 Actual behavior

Both tests fail to compile and the reported error looks bizzare(-ish):
```
Type '() => Promise<{ count: number; } | StateMachine<{ count: number; }>>' is not assignable to type '() => Promise<{ count: number; }> | StateMachine<{ count: number; }>'.
  Type 'Promise<{ count: number; } | StateMachine<{ count: number; }>>' is not assignable to type 'Promise<{ count: number; }> | StateMachine<{ count: number; }>'.
    Type 'Promise<{ count: number; } | StateMachine<{ count: number; }>>' is not assignable to type 'Promise<{ count: number; }>'
```

For some reason, the return type here didn't narrow the contextual union to include only Promise(-like?) members and dragged the whole `Awaited<Union>` to the computed contextual type. And this has caused an assignability problem.

Note that this "only" happens with `Promise.reject`, it's not reproducible with `Promise.resolve` and other similar types. My guess is that it's because `Promise.reject` contains a generic only at the return type position and this is what makes this issue manifest somehow.

### 🙂 Expected behavior

No error should be reported because this is valid code and it looks like sufficient information has been provided in the context for this to be narrowed down properly~.

--- 

While looking into this problem I've poked around the internals of TS and figured out that this might be a potential fix for this issue: https://github.com/microsoft/TypeScript/pull/47683

**Comment by JoostK** [comment]
This is also causing errors in Angular codebases as reported in angular/angular#46697.

Minimum example:

```ts
declare function load(): Promise<boolean>;

type LoadCallback = () => Promise<boolean> | string;

const cb1: LoadCallback = async () => load().then(m => m); // errors
const cb2: LoadCallback = async () => load();              // works
const cb3: LoadCallback = () => load().then(m => m);       // works

```

[Playground link (nightly)](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220704#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwhymAAoBKALngAUYcBbLAZxAB4AjHHCEKVAPgDcAKGEYAngAcEAGSLAAwlAgR2UMAGt4AXnjkd-GnUYsOXHn0MAfeEwwwsqAOYjhYPHfhh2ARipziJRU1TR14KCZxdD0yAwJ5cgA6DAALEFQSejj6MhF3VE9vACZ-eSDVdS1dCKiwGLjCYnI8jwwvdgBmUsDlCtDdfW1DRtIyZLSMrKH4HJEgA)

**Comment by Andarist** [comment]
@JoostK I've confirmed that my PR fixes your case too and pushed out your minimal repro as an additional test case there: https://github.com/microsoft/TypeScript/pull/47683/commits/ce8c01201397be12642a7f1deabe320cf2afc5f0
