### ISSUE TITLE
Generic record key (string | number) doesn't allow an empty record

### ISSUE THREAD

**Issue by JSin** [microsoft/TypeScript#47689]
# Bug Report

When a record with a generic key is assigned an empty object (a object with zero properties), I am given an TS error that `Type '{}' is not assignable to type 'Record<T, T[]>'.(2322)`.

The use-case was to convert a edge list to an adjacency list, my workaround was to use a `Map` instead.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Record

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/MYewdgzgLgBApgEwOZwDIEtoBUQEEEBWG0MAvDADxbwAeUcYCEMYArgLYBGcATjAD4xoPdGCQA+ABSIUxKAC4YAbSwAaGFgC6SzQEpFAJTigeCKuqw7xZawG8AUDCcxQkWAENCcw8ZCnzGlZkMLYAvgDcjs48cFCsPGAwnkSYUJERQA)

### 💻 Code

```ts
const edgeListToAdjList = <T extends number | string>(edgeList: [T, T][]): Record<T, T[]> => {
    const adjList: Record<T, T[]> = {}; // This line throws the TS error
    return adjList;
};
```

### 🙁 Actual behavior

`Type '{}' is not assignable to type 'Record<T, T[]>'.(2322)`

### 🙂 Expected behavior

Record with a generic key (string | number) can be expressed as an empty object.

My assumption was this would a be a duplicate issue but I haven't found any that matched.

**Comment by Josh-Cena** [comment]
If `T` is resolved to the literal type `'foo'` (which does extend `number | string`), then `adjList` would have type `Record<'foo', 'foo'[]>`. This would require `adjList` to always have a key `'foo'`. You should try `Partial<Record<T, T[]>>`.

**Comment by JSin** [comment]
@Josh-Cena Thanks for the insight that generics may be incompatible because by extension it can resolve to any type of `string | number`. Unfortunately, `Partial<Record<T, T[]>>` would not resolve to `Record<T, T[]>`, a quick and dirty way would be to assert the type as `Record<T, T[]>` on the empty object.

Using the just a generic string (`T extends string`), would you know if it were possible assert a generic as a string (not a type of string)?

**Comment by fatcerberus** [comment]
You probably want something like https://github.com/microsoft/TypeScript/issues/27808 where you'd be able to write `T extends oneof string | number` and that would mean "`T` is either `string` or `number`, but not anything derived from that union."

That being said, there's no reason to write `T extends string` if you don't mean to also accept string literals or unions of them for `T`.  As @Josh-Cena said, if `T` is, say `"foo" | "bar"`, then `Record<T, T[]>` *can't* be assigned an empty object.

**Comment by JSin** [comment]
@fatcerberus Thank you! I'll be following that thread. I'll so put more on thought on a better approach.

Closing the issue for now.
