### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by caioagiani** [microsoft/TypeScript#47685]
[ACCROSS]: FOUND: 3 - https://github.com/microsoft/TypeScript/search?q=accross&type=code
[SUCCES]: FOUND: 13 - https://github.com/microsoft/TypeScript/search?q=succes&type=code
[OVERRIDEN]: FOUND: 16 - https://github.com/microsoft/TypeScript/search?q=overriden&type=code
[UNKOWN]: FOUND: 6 - https://github.com/microsoft/TypeScript/search?q=Unkown&type=code
[STING]: FOUND: 4 - https://github.com/microsoft/TypeScript/search?q=sting&type=code
[INTANCE]: FOUND: 4 - https://github.com/microsoft/TypeScript/search?q=intance&type=code
[INTIALIZATION]: FOUND: 5 - https://github.com/microsoft/TypeScript/search?q=intialization&type=code
[DEFINTION]: FOUND: 1 - https://github.com/microsoft/TypeScript/search?q=defintion&type=code

**Comment by caioagiani** [comment]
@MartinJohns, Hi!
This is a problem and not a PR, the purpose is just to alert the team that there are typos.

**Comment by RyanCavanaugh** [comment]
It's okay to have a few typos here and htere

**Comment by caioagiani** [comment]
@RyanCavanaugh, It sounds strange to keep typos in a language that is mainly used for writing aids and corrections / methods and typing.

**Comment by RyanCavanaugh** [comment]
Our time is a finite resource and we want to deploy it to useful ends, instead of talking about typos. No one reading the TypeScript source code is going to be confused by seeing the word 'INTIALIZATION'.

**Comment by caioagiani** [comment]
You won't be confused, but you'll know it's a mistake.

A wrong thing is still a mistake and it always will be, if for you the culture of keeping typos in the repository is normal, that's fine, go for it :)

**Comment by MartinJohns** [comment]
> the purpose is just to alert the team that there are typos.

Do you think the team is not aware of this, when they explicitly mention typos in the PR template?

**Comment by caioagiani** [comment]
> > the purpose is just to alert the team that there are typos.
> 
> Do you think the team is not aware of this, when they explicitly mention typos in the PR template?

?
