### ISSUE TITLE
Ensure alignment with ecmascript-types

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/TypeScript#47686]
Typescript, in order to maintain future proofness, should collaborate with the authors of the Javascript types proposal:
https://github.com/sirisian/ecmascript-types
And ensure that the proposal is optimally compatible with typescript and that future typescript changes are compatible with the proposal.
I hope this proposal will be designed as a subset of typescript, it would make perfect sense or otherwise fall into irrelevancy in practice.
A typescript subset would enable:
1) faster transpilation by reducing the need of transpilation. 
2) a minimal type lingua franca that would enable moderate interoperability between multiple javascript supersets/typed javascript alternatives to typescript.

Sorry of this issue happens to be a duplicate.

**Comment by MartinJohns** [comment]
That proposal apparently exists for three years already, and it's still in the status "-1". There are certainly better places to spend resources on.

But be assured that the TypeScript team is usually very involved in ECMAScript proposals and follows them.

**Comment by LifeIsStrange** [comment]
Yes I agree but you guys should check once every year then :)

**Comment by MartinJohns** [comment]
Please don't confuse me with the TypeScript team. I'm just a noisy follower.

The proposal declares itself to be in stage -1, but stage 0 is meant to allow input into the specification. So the author of that proposal apparently does not want any input yet.

**Comment by RyanCavanaugh** [comment]
We're already working on various efforts here; stay tuned.

The linked repo in particular doesn't appear to be anything ready for committee; we can't manage alignment with every stage -1 proposal in existence -- this is neither feasible nor desirable.
