### ISSUE TITLE
Array element type cannot be inferred from union of arrays depending on overlap

### ISSUE THREAD

**Issue by jtbandes** [microsoft/TypeScript#47692]
# Bug Report

### 🔎 Search Terms

`array union inference`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `array unions`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/GYVwdgxgLglg9mABABwIYCdawQHgCoB8AFBugFyIBKApqgCYIA2AngILrqrP4EA0iwMBSIB9CngCUiALwFEAIzhxGtMBIoBtPBoC6-bTp2IA3gChEFxOmpQQ6JBt29dO0wF9TpqM2TVEAIVQAZz9pE1QKMBAAW3lqdH55SJi49A9vX0RWGQDgvwAycIoARjdEQuMICih0EGp0nz9-HMCQ8pMkxCjY+LKKqsQauobMgGEWvPbjTtKpgaH6z1BIbCRgEhE4dBFO1l1EAB8Ap0RUTe2BvaMj0d0pM0sUDCx4MA2tnf4iAA8KVgP-FJZIhvgA6CAScyWNCYGCrd4XL6-LIHUZAuRgiFQiwwl64f7+YhnD7yJHokHgyGPXFw144f6jInnEQQJF-VHkzGQjxAA)

### 💻 Code

```ts
function partition<T>(arr: ReadonlyArray<T>, fn: (_: T) => boolean): [T[], T[]] {
    return [[], []]
}

type Base = {a: number, b: number}
type A = Base & {a: 1} & {c: true}
type B = Base & {b: number} & {c: true}
type C = Base & {b: 1} & {c: true}

function f(a_or_b: A[] | B[], a_or_c: A[] | C[]) {
    partition(a_or_b, (x: A|B) => x.c)
    partition(a_or_c, (x: A|C) => x.c) // error - why?
    partition<A|B>(a_or_b, (x) => x.c)
    partition<A|C>(a_or_c, (x: A|C) => x.c)
}
```

### 🙁 Actual behavior

error on `partition(a_or_c, (x: A|C) => x.c)` even with explicit callback parameter type

### 🙂 Expected behavior

no error — T should be inferred as `A|C`

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. When generic inference collects multiple candidates for the same type parameter from multiple locations and there's no common subtype between those types, inference fails. This is the mechanism by which
```ts
declare function fn<T>(a: T, b: T): T
fn(1, "hello");
```
fails.

**Comment by jtbandes** [comment]
Don’t `A` & `C` have a common subtype, `{c: true}`?

**Comment by RyanCavanaugh** [comment]
Misspoke, a common *supertype* from the list of candidates. Otherwise we would just pick `{ }` between any two arbitrary types (this used to be the behavior and everyone hated it 😅)

**Comment by jtbandes** [comment]
🤔 Is `{c: true}` not also a common supertype? (because object types are inexact?)

**Comment by RyanCavanaugh** [comment]
It's a common supertype, but it's not in the list of candidates. e.g. If you have `f(dog, cat)`, we won't infer `Animal` even though it's a common supertype.
