### ISSUE TITLE
JSDoc template constraint ignored when noImplicitAny

### ISSUE THREAD

**Issue by mhofman** [microsoft/TypeScript#47694]
# Bug Report

### 🔎 Search Terms

 jsdoc template constraint unknown

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ 

Tested all recent versions and nightly (4.6)

### ⏯ Playground Link

**Playground Link:** [Provided](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=true&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&downlevelIteration=true&esModuleInterop=false&experimentalDecorators=false&emitDecoratorMetadata=false&jsx=0&ts=4.5.4&filetype=js#code/PQKhFgCgAIWgBALgUwLYAcA2BDF0DeA9gEYBWyAxogL7QAqUsC62ATtqgQM6KsCWAOwDmtACbJE2PpkZx4Ldp3x1aJUrISsJAV1YCuBFbOBQAZtoFU+hAdFOFCACnGTpAGmhroAXlBzEAJ7oyIa0IMDQjvjUAJQxBIzQfKaRAETEbKlJtmrx+InQ0BQ2XISYyAB0mIRCjmoVGawxANyJ1IlaiLo5ZK2Q1EA)
      

### 💻 Code

```ts
/**
 * @template {object} T
 * @param {string} detail
 * @param {T} obj
 * @returns {T}
 */
function foo(detail, obj =/** @type {T} */ ({})) {
  if ("bar" in obj) {
    console.log(obj.bar);
  }
  return obj;
}
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strictNullChecks": true,
    "downlevelIteration": true,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "target": "ES2017",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```
</details>

### 🙁 Actual / 🙂Expected behavior

`T` should extend `object`, but when `noImplicitAny: false`, type `T extends unknown` (toggle in config to see correct `extends object`)

This seem to be a JSDoc only behavior as the equivalent TS code with `noImplicitAny: false`

```ts
function foo<T extends object>(detail: string, obj: T = ({} as T)) {
  if ("bar" in obj) {
    console.log(obj.bar);
  }
  return obj;
}
```

<details><summary><b>Output</b></summary>

```ts
function foo(detail, obj = {}) {
    if ("bar" in obj) {
        console.log(obj.bar);
    }
    return obj;
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strictNullChecks": true,
    "downlevelIteration": true,
    "declaration": true,
    "target": "ES2017",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&downlevelIteration=true&esModuleInterop=false&experimentalDecorators=false&emitDecoratorMetadata=false&jsx=0&ts=4.5.4&filetype=ts#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdE4AjAK22gD4AKI7KAQxgBsAuREqAJxhgA5gBpy1HlgC8iBgG8AvolZkMASnWJ5AWABQiRDGByARBVb9TRpJSpbdBw4ggIScDtgB0HOMIZ2Xhb86gDc+oaKEYj8LCD8ttTheopAA)

**Comment by sandersn** [comment]
`object` in JSDoc means `any` when `noImplicitAny: false`. That's the setting that we expect people will use when first adding old JS to a compilation, and `object` is frequently used to mean "basically any type" in non-checked JSDoc. Setting `noImplicitAny: true` is a signal that you want stricter TS semantics applied to JS.

You'll get the same `T extends unknown` in TS when you write `T extends any`. That's because `any` doesn't behave soundly in assignability checks that use the constraint of a type parameter.

**Comment by mhofman** [comment]
> `object` in JSDoc means `any` when `noImplicitAny: false`

That's a surprising and fairly significant limitation I haven't seen documented anywhere! For code that cannot transition to `noImplicitAny` yet, is there any way to get the behavior of `object` so that code can be gradually made stricter?

**Comment by sandersn** [comment]
> ... I haven't seen documented anywhere! 

Hm, I thought that it was, but it's not. Historically, the `object` type was introduced about the same time as checkJs, and it was a niche, new feature for a couple of years.

The workaround I have suggested before is to alias `object` in Typescript and refer to the alias in Javacript file.
