### ISSUE TITLE
Enable `Required` (and Similar Utility Types) to Work with "Function Objects"

### ISSUE THREAD

**Issue by ITenthusiasm** [microsoft/TypeScript#47704]
# Suggestion

Currently, the `Required` type does not work with function objects. If someone tries to create a type using `Required<FunctionObject>`, the resulting type does indeed make all the properties required, but it also _strips_ the function aspect of the type. See [here](https://www.typescriptlang.org/play?#code/PTAEHkAcBcEsHsB2BDANqSAnekCmm5cBnUZTXURXAY2KLIE9Rp5QATXAM1iuYAsKnAK6p0wxNThJQ8AEYArGtFABzTMjZC0qJj1KgiPFakGwTAOgCwAKBCgAFAHUKyagGtE8AO4m2KitB8sCTBoEKIVLRE9JhMAuQANKCyQsqwygCSAMqUNHSMoF4CiOy4aEaF6XzMDHgkqLBuFAAGAEplkuac8JheZGztnM0AlDY80PicrhQAYuGSCIjgCkqgAN42oA7mO2QqRABcpIgMANoAusNHAG7wsGwA3JsY2JAAjAD8R4hCALay+Ce1i2WBwACYvpQ-gDMECAL42GzQWoUZaKSSOKrtACOQlg5DYAAVXiQALygHF4gkAHjmEikSxWkgAfEDkXhQABhACCADleeAACozHgDXC4-G4NjczD7UDkwlkZC-XATTBEalopSYwKUyVEkmspEorl8kWIMUSgkyuUKpUqtUaukLJBaySgABkFPFVKltPmDLd0GZRusxo5QZ1fEJsHcUuJODJoBj7n99MWQaSACJQe8s6H2RQefyheaibGmtLZUnFeoHfgNZGqinKwnIEQCybi2WW1KbTX7aqG2mXYz0covS2R4GmdBs7m3vnWUA).

## 🔍 Search Terms

Required, React

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

From a hover in VS Code, it seems like `Required` looks like this:

```ts
type Required<T> = { [P in keyof T]-?: T[P]; }
```

It should be safe enough to change the type to this:
```ts
type Required<T> = T & { [P in keyof T]-?: T[P]; }
```

For objects, this should have no impact. Although `T` may contain optional properties, the index signature will force those properties to become required. We're basically saying the type is itself, but with required props. However, this approach gives us the added benefit of maintaining the function portion of a type if it was defined.

A similar approach could be taken for the other Object Utility Types (e.g., `Pick`, `Partial`, etc.).

## 📃 Motivating Example

Developers will now be able to use the object utility types (e.g., `Required`, `Pick`, `Partial`, etc.) on functions without losing any type information.

## 💻 Use Cases

This use case is especially helpful when it comes to `React` projects. In lieu of `slots` (in frameworks like `Svelte` or `Vue`), the [dot notation](https://reactjs.org/docs/jsx-in-depth.html#using-dot-notation-for-jsx-type) approach is incredibly useful for modularizing components. It decreases the number of imports one has to include in their file, and it scopes a component to its proper context.

Usually this is fine if you're using regular components. But when a `React.forwardRef` is involved, using dot notation becomes impossible. This is because `React.forwardRef` has its own return type (which itself is a function with object properties). In this case, to use dot notation, a custom interface with optional properties is needed to define individual functions along the way

```tsx
interface MainComponent {
  SubComponent?: typeof SubComponent;
}

const MainComponent = React.forwardRef(/* ... */);
const SubComponent = (/* ... */) => <div />;

MainComponent.SubComponent = SubComponent;
export default MainComponent;
```

However, in order for the modularized components to actually be _usable_, the properties need to be required. Otherwise, TS will (rightly) complain. So a required object must be exported instead.

```diff
- export default MainComponent;
+ export default MainComponent as Required<MainComponent>;
```

However, the above code is not currently possible due to the limitation I described in TS. I'm aware that this can be resolved locally by the users, but it is admittedly odd that TS would strip the function aspect of an `interface` off _at all_ to begin with. I was assuming this wasn't intentional, and it could be a source of confusion for users.

(Note: I'm aware that one could `export default Object.assign(MainComponent, ...otherComponents)`, but this would strip any useful JSDoc information that was on the components -- including the main component. It also creates a new object when it isn't necessary.)

**Comment by RyanCavanaugh** [comment]
This would be a highly disruptive breaking change, since code could very reasonably be *depending* on the function signature parts being removed by mapped types.

**Comment by ITenthusiasm** [comment]
Ah. I didn't think about that. Fair enough. :sweat_smile: Thanks @RyanCavanaugh!
