### ISSUE TITLE
Inferring and reusing a func's (rest) params with Parameters<> Utility

### ISSUE THREAD

**Issue by Kaseano** [microsoft/TypeScript#47706]
# Bug Report

### 🔎 Search Terms

Typescript Parameters Utility Type, Rest Parameters, Reusing function parameters

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: Parameters Utility rest params spread

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOdEApEAcCGAnHAWwC5EBnKPGMAc0QEpSA3OGAEwFgAoUSWBZKgzZ8RUmBCEARgFM8AGkRws-MKSmoANjJxJGiFu269o8JCjSZcBEuUrU6AH0QTpcxctUB+dVp17mVjZEAG8AX25jcFMBCwAhfGEAOhT8GjJSAAVRQhkoOTIAHigATywZOGBBOAA+BlDuRCbqzBSktLIGbgiuY1RMACIpHAAvAfqAegnEAHkAaT64BLxB4bHJ6YBRAA9y6BlggCZENMkZMCgyRSkQKEQaODuARiSgA)

### 💻 Code

```ts
function foo ( param: string ): void
function foo ( param: number, option: boolean ): void
function foo ( param: string | number, option?: boolean ): void {}

function fooBar ( ...args: Parameters<typeof foo> ) {
    foo( ...args )
}

foo( "baz" ) // OK
fooBar( "baz" ) // Expected 2 arguments, but got 1.
```

### 🙁 Actual behavior

If I'm not misunderstanding, it seems like TS should be able to infer the parameters (ex optional: boolean|undefined) of the last signature with the function implementation, ie the most permissive catch-all from the overloads.

### 🙂 Expected behavior

Being able to pass along parameters with that pattern has been handy for me in JS, and it seems like the compiler has everything it needs to infer those parameters and successfully compile with type safety

**Comment by MartinJohns** [comment]
Conditional types do not work with overloads, as the documentation mentions. They'll always pick up the last signature.

**Comment by RyanCavanaugh** [comment]
`Parameters` always produces the parameter set from the last overload. I believe this is an artifact of conditional types predating parameter tuples.

**Comment by RyanCavanaugh** [comment]
> the last signature with the function implementation, ie the most permissive catch-all from the overload

Oh this is probably the actual root cause of confusion - the implementation signature is not visible to callers

**Comment by Kaseano** [comment]
Hi @RyanCavanaugh sorry I'm not quite following you, are you saying the code needs to be implemented differently so that the last signature is visible to callers?

**Comment by RyanCavanaugh** [comment]
Yes, you would need to write
```ts
function foo ( param: string ): void
function foo ( param: number, option: boolean ): void
function foo ( param: string | number, option?: boolean ): void
function foo ( param: string | number, option?: boolean ): void {}
```

**Comment by Kaseano** [comment]
Got it! Completely makes sense to me now, thank you for taking the time to explain it!
