### ISSUE TITLE
Intl.DateTimeFormat options object is missing properties

### ISSUE THREAD

**Issue by Tefricker** [microsoft/TypeScript#47700]
# Bug Report

### 🔎 Search Terms

'DateTimeFormat', 'Intl'

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Intl.DateTimeFormat

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=8&ssc=24&pln=1&pc=1#code/MYewdgzgLgBAJgQygUxgXhmZB3GARJZACgEoBuAKAtElgDMQAnAWyRTnUxxgEkwoANgDoCKACoBLZsgBiTVlCIByZGCUAaGAG8KASH2IUAZSgBPAcgBcMJRAAWTKBr36oU5CfNWb9x8-0AviRCDCxIRIbI5FQ0ECAWQgIgAOZEoQrs5EA)

### 💻 Code

```ts
const date = new Date();

const formatted = new Intl.DateTimeFormat('en', {
			dateStyle: 'short',
			timeStyle: 'short',
		}).format(date);

console.log(formatted);
```

### 🙁 Actual behavior

Intl.DateTimeFormat options object is missing properties.

### 🙂 Expected behavior

Intl.DateTimeFormat options object should have types for dateStyle and timeStyle

**Comment by MartinJohns** [comment]
Your target is set to ES2017, but this target does not support these properties. When you change your target to ES2020 it will work. See also #44632.
