### ISSUE TITLE
Narrowing with a typeguard fails on condensed expression

### ISSUE THREAD

**Issue by ryanrhee** [microsoft/TypeScript#47710]
# Bug Report

### 🔎 Search Terms

narrowing, union, control flow analysis, type guard

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about discriminated unions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/C4TwDgpgBAysBOBLAdgcwGIHtNQLxQG8AzbOJNALigCIBnBFVagXwChRIoAlAQwHcsOfMVIM0Afir1yqNh2gARCAGNM8HsAgATQXigAKAolplGVBAFcIzKADJYYjNgCUUAD6FjpylCI8ANrQQANy+ojKSUNKMbKxEFsjKwIiYyFBejoL6JJhUvAIuVDnptA4yugSsUNVQ8BDAFvBpOQB0Od6oUACEuPgJWhBEKNqssfGJyalQA6rqmtnYefyCzlRKsxraFVU1APS7UAggUACMFDvV+xdQ+1AAklB8mBb+WlAQAB6QSYcAFtAAIwg-kwfCgqgAthCIMhNG9nsBavVGml6JtobDDjgnvAANYAGmut1oKGU0GA-2OPDqf2gtB40PeXzqtBJUx4pQpgPgmFxMKgFjAhwgTWpxyBILBiERRN2sqRDSahHlNRKHSoGXK2AWmGchNVt1VLWNOXlsQNByOUAATOcLfKHhTnqhfoiITwQECoGAXv5GFAEbTDuAIKgLNS3ihgDhpaVQWkAogOdppsZlEgISgeLD5ZmXW6eHzg5BaOnEGBEXVEwAvcn-YsQWj4qAAiyIinGKLJfz+Xw8RCBBvKf7KXH++XXVTIehqxx6TWMLI5ZzyuqKtKVC2q2cyfV7A5Gk3YM2sa5rlE7-3iZXbmoLtB72-GtrH1XMKib2+Xh-XQ8vzDXGwbBAA)

### 💻 Code

```ts
type StringFoo = {fooString: "string"}
type RawFoo = {fooString?: string}
type DecoratedFoo = ({isString: true} & StringFoo) | {isString: false; fooString?: string}

function isStringFoo(foo: RawFoo): foo is StringFoo {
    return foo.fooString !== undefined
}

function decorate(foo: RawFoo): DecoratedFoo {
    // try 1:
    //
    // I would expect the below commented out return statement to work,
    // since they are the same expression as the broken up ternary below it 
    //
    // return {
    //     isString: isStringFoo(foo),
    //     ...foo
    // }

    // try 2:
    //
    // I thought maybe pulling out the typeguard into its own aliased discriminant
    // might make typescript realize the types, but this still fails typechecking 
    // 
    const isString = isStringFoo(foo)
    // return {
    //     isString,
    //     ...foo
    // }

    return isString ? {
        isString,
        ...foo
    }: {
        isString,
        ...foo
    }
}
```

### 🙁 Actual behavior

I expect condensing the ternary to a single expression to still yield the same result via control flow analysis

### 🙂 Expected behavior

once the ternary is condensed into a single expression as above, typescript no longer recognizes the type literals and discriminated union, even though the property assigned to the object is a type literal.

---

this is happening when working with our grpc library. the types generated by the protobuf compiler is loose, so we provide a discriminant key that can narrow the loose type into a stronger type. utilizing this requires writing ternary expressions that are trivially collapsible, because actually collapsing the ternary makes typechecking fail.

**Comment by RyanCavanaugh** [comment]
The implicit proposal here is that we do a combinatorial expansion of all possible types the spreaded object can have, taking into account control flow effects that one property might have on another.

It turns out people can and do write *enormous* spreads that look like this (shown with the spreaded expressions inlined for clarity)
```ts
return {
   ...{ a: someStringOrNumber },
   ...{ b: someStringOrNumber },
   ...{ c: someStringOrNumber },
  // dozens more
}
```
so producing this kind of combinatorially-exploded type is not something we can do in practice

**Comment by ryanrhee** [comment]
I see, that makes sense, re: combinatorial explosion. Would typescript need to compute the combinatorial even if the type guard were aliased and therefore executed before the object spread?

Also, is there a recommended way to write these types of expressions that aren't obviously collapsible?

**Comment by Fryuni** [comment]
Normally I'd do this in such scenarios:
```ts
return isStringFoo(foo)
  ? {isString: true, ...foo}
  : {isString: false, ...foo};
```

Mostly because I prefer using string literals as discriminators, so if I could control the type it would be this:
```ts
return isStringFoo(foo)
  ? {stringType: 'foo', ...foo}
  : {stringType: 'other', ...foo};
```
