### ISSUE TITLE
Mapped type doesn't take into account multiple overloads for mapped values

### ISSUE THREAD

**Issue by n1kk** [microsoft/TypeScript#47714]
Hi, I'm trying to figure out how to wrap each value of a mapped type into a generic type but the trick is that that generic type has to be inferred. Since inferred types can't have their own generics I've tried to come up with a generic that gets the result value, but seems like it has a problem when it comes to function types with several overloads. 

I have a callback that can process values differently based on their type so it has several overloads, and I want to treat each value of the object with it and get the resulted type.

```ts
type GenericCbResult<Type, Args extends any[]> = 
    Type extends (...args: Args) => infer Result ? Result : never;

declare function mapValues<
    T extends { [key: string]: any }, 
    CB extends (value: any) => any
>(
    target: T,
    cb: CB
): { [k in keyof T]: GenericCbResult<CB, [T[k]]> };

// string becomes number and number becomes string
declare function cb1(v: string): number;
declare function cb1(v: number): string;

const test1 = mapValues({ a: 1, b: "asd" }, cb1);
```

Given `{ a: number; b: string; }` I'm expecting to get a reverse `{ a: string; b: number; }`

The computed type ends up being:
```
const test1: {
    a: string;
    b: never;
}
```

But if I change the order of the overloads then the resulted map type will change too:
```ts
// string becomes number and number becomes string
declare function cb1(v: number): string;
declare function cb1(v: string): number;  // this was first before
```
And now the type is:
```
const test1: {
    a: never;
    b: number;
}
```

Seems like it only takes into account the last override, since it does infer the type correctly but only for one value in each case.

Is this a bug or a limitation? And is there a different way to achieve this?

**Comment by MartinJohns** [comment]
You forgot to fill out the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md).

`GenericCbResult` is a conditional type, and conditional types do not support overloads. As the [documentation](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types) mentions, only the last signature is used.

**Comment by n1kk** [comment]
Oh, I apologize frot that. Somehow when I clicked "New Issue" there was no template. If I do it now I can see that there is a choice, now sure why it wasn't there before.

Thanks for the quick response and the documentation link @MartinJohns.
