### ISSUE TITLE
Discriminated union shows inconsistent error messages

### ISSUE THREAD

**Issue by andrefcdias** [microsoft/TypeScript#47722]
# Bug Report

### 🔎 Search Terms

discriminated union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about discriminated unions.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/C4TwDgpgBAEg9gJwJYC84DtgEMA2BhLBAEwAUE4wBnKAXigG8AoKFqRJCTLYJDAfgBcUAOQALdmi45hzVpVQRBIygFtc0qAB8RKiESQBXFTIC+jUJCgA1CAh4BjXAWJkK1Ok1ZtknbD35CwgButg64Ml7yKIqBuvpGwloiOIQA5hCm5uDQzqTkVLSwEhjY+IR5bkk2dkiOZS75lIyMAPQtUADqiADWTfYYlMBQITV1QrmuBR6yLOy+3LzogSNh0gA0M1BREIGq6pltUAAicBDU6HBDAO49jP3og1DiyJKl4+WT7gybc1z+SyJnqgSuENpEFIEUgh0pkgA)

### 💻 Code

```ts
type HorizontalCardProps = {
    orientation?: 'horizontal'
    size?: 'small' | 'medium'
}
type VerticalCardProps = {
    orientation?: 'vertical'
    size?: 'medium' | 'large'
}
type CardProps = HorizontalCardProps | VerticalCardProps

// Works
const vertical: CardProps = {
    orientation: 'vertical',
    size: 'small'
}
// Does not work
const horizontal: CardProps = {
    orientation: 'horizontal',
    size: 'large'
}
```

### 🙁 Actual behavior

**Working**: Using a `vertical` orientation, linter shows properly that the `size` property's value is invalid.

![linter marking property size to have an invalid value "small" as it is not assignable to type "medium" | "large"](https://user-images.githubusercontent.com/39736248/152387238-8ecbb502-9230-4de5-b44f-3ce502214e04.png)

**Not working**: Using a `horizontal` orientation, linter marks `orientation` to be invalid, instead of `size`.

![linter marking property orientation to have an invalid value "horizontal" instead of size](https://user-images.githubusercontent.com/39736248/152387722-dc8422e3-716a-4987-a1d5-d51dc7ec1dc7.png)

### 🙂 Expected behavior

Consistency in the error messages. The ideal scenario would be for the non working example to show _`Type "large" is not assignable to type "small" | "medium"  | undefined.`_, as the property `orientation` with the value `horizontal` matches the `HorizontalCardProps` type.

**Comment by RyanCavanaugh** [comment]
These messages are equally validly correct. In this case we consider both properties to be valid discriminants since they're all composed of literals, so the choice of which property to flag is ultimately arbitrary.

**Comment by RyanCavanaugh** [comment]
I can't find any offhand. You might be able to tweak things a little to activate different heuristics, but we don't provide any mechanisms which guarantee that a particular error path gets chosen over another one.

**Comment by andrefcdias** [comment]
A shame, more control over this would bring great benefit, specially with JSX.
Closing issue as it's by design.

**Comment by andrefcdias** [comment]
Let me know if this is a valid feature request proposition. If so, I can go ahead and create one @RyanCavanaugh.

**Comment by RyanCavanaugh** [comment]
You can file it; FWIW I don't think we'd be likely to accept it given how rarely "impostor" discriminants appear as in this case.
