### ISSUE TITLE
Presumably incorrect refinement of object types in a union

### ISSUE THREAD

**Issue by LiamGoodacre** [microsoft/TypeScript#47723]
# Bug Report

### 🔎 Search Terms

Union, Record, Object, Bug

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing objects & unions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/FAehAIEMGNoUwA4BcDOUB2BPcB7ARgFZzRLhIAWkplaABpAFzgCMtGAJiDgE7i15MATLWDQc6FKQDW4ALzgAFADcmAbyhNm4AL7gAPuHUDwgnQEomSnAEt2cgHyHg4F+GsAzRQHJIXt+nAlcAAyYPAvPD9rAKUzJ1cE8DAyTAQ4FGhua2R-MW5uYiQAG2wAVxR0vh8omLYkHGdEl2TuUqK4XFLSWiMhHTZ3bhwAWzJyDtL0a3FgRqbk61IKOADovIKSEvByytoImsC6hqbmiFb2zu71RhZ+8EGRsYmpmbnE5JQccHQcAHdwX4dFZ2UoIAGLch8FTfOBKODcNgAWnAmGsUnSAEI3gkxBJSKVyAB5chMdCw+FyQLY1wUIb-AnEt7aYDM0AQcYFLxocQdX4Q8B4HAUPiQNhhfgiKQKa6aAA0Ar62jMwCAA)

### 💻 Code

```ts
// accepts any object that has `a: 1` and/or `b: 2`
const k = (v: { a: 1 } | { b: 2 }): void => {
    if ('a' in v && 'b' in v) {
        // typescript incorrectly uses `'a' in v` to
        // rule out `{ b: 2 }` from the union

        // it then incorrectly uses `'b' in v` to
        // rule out `{ a: 1 }` from the union

        // so now we end up with `v: never` - yikes!
        const uhOh: never = v
        throw uhOh
    }
}

// here's one with both `a` & `b`
k({ a: 1, b: 2 })
```

### 🙁 Actual behavior

(See code comments above.)
`'a' in v` refines `v` to exclude `{ b: 2 }`, when it shouldn't.
It shouldn't, because any `o` of type `{ b: 2 }` doesn't mean `o` only has a `"b"` key, it means it has at least a `"b"` key.

### 🙂 Expected behavior

`'a' in v` shouldn't refine `v` to exclude object alternatives that don't mention key `"a"`.
But `!('a' in v)` should eliminate object alternatives that do mention key `"a"` (unless optional like `{ a?: 1 }`).

**Comment by RyanCavanaugh** [comment]
`in`'s narrowing isn't sound in any sense; the behavior here is designed to be useful when used idiomatically and when the objects are actually mutually exclusive in practice.

**Comment by LiamGoodacre** [comment]
Feels to me like there ought to be a distinction between "objects" and "records"; in which records have fixed keys, but objects are allowed to forget.

**Comment by RyanCavanaugh** [comment]
Yep, see #12936
