### ISSUE TITLE
Conditional Type Failed extending `never`

### ISSUE THREAD

**Issue by yordis** [microsoft/TypeScript#47735]
# Bug Report

### 🔎 Search Terms

Conditional Type

### 🕗 Version & Regression Information

- Version: `v4.6.0-dev.20220116 `

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/KYDwDg9gTgLgBDAnmYcAKBDGALTUMC2APACoB8cAvHCXKDMAHYAmAznI8AG7BRwD8cAN4BfOAC5hcMFmyTaIgNwAoUJFgJkqAIoBXXojyFSFarXpM2HbrwHCxkoXACO+qInlwlq8NHhIUOAAhCGZDDHxicioaOhAGFnZOHj5BUQkpACNQj1jvNT9NQIB5MBgASwhGViMCGKFlODgIMsrq-kdGprhWcoBzRgwAGw64AEFs2ABlfsGhlSbvER91fy04AFUoIdrWUkwcABoaPQNTLoPcCOMSS7IugDI4U-da0hfEMhUVwoDUUt4WDau32shiukYAGtGBAAO6MY4kD7gqEw+GIkJhFHQuGMc5NUoVKo1a4ER6bbYg26yREfe5NJ6Y8KRUhMr7KZR-OAAURAhDAQ2AAEYYlsdqS9k5BgRgJJWDAoOVGH0vMdkrx7gB6TXdAB6-A5XN5-MFACYYgD8ETGCCpYRZT0FUqVSJjk5WH45U7la7rCktTqmvqgA)

### 💻 Code

```ts repro
export type PathParam<T> = T extends never ? {} : { path: T };
export type QueryParam<T> = T extends never ? {} : { query: T };
export type BodyParam<T> = T extends never ? {} : { body: T };
export type OptionsParam = {
  options?: {
    signal?: AbortSignal;
  };
}
export type UrlParams<TPath, TQuery> =
  PathParam<TPath>
  & QueryParam<TQuery>;

export type OperationParams<TPath = unknown, TQuery = unknown, TBody = unknown> =
  OptionsParam
  & UrlParams<TPath, TQuery>
  & BodyParam<TBody>;

type Example1 = UrlParams<{ name: string }, never>
//   ^?

type Example2 = OperationParams<{ name: string }, { sort: string}, never>
//   ^?
```

### 🙁 Actual behavior

The following Asserts happened:

```ts
type Example1 = never
type Example2 = never
```

### 🙂 Expected behavior

The following Asserts to happen:

```ts
type Example1 = { path: { name: string } };
type Example2 =
  OptionsParam
  & { path: { name: string } }
  & { query: { sort: string } }
  & { options?: { signal?: AbortSignal; };
```

**Comment by MartinJohns** [comment]
This is working as intended.

`never` is essentially an empty union type, and using union types with conditional type inference results in distributive behaviour. Distributing over an empty union results in an empty union, as there's nothing to distribute over. See the documentation: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types

**Comment by yordis** [comment]
@MartinJohns any chance you know how to accomplish what I am intending to do?

**Comment by RyanCavanaugh** [comment]
```ts
export type PathParam<T> = [T] extends [never] ? {} : { path: T };
export type QueryParam<T> = [T] extends [never] ? {} : { query: T };
export type BodyParam<T> = [T] extends [never] ? {} : { body: T };
```

**Comment by MartinJohns** [comment]
@yordis From the documentation I linked:

> Typically, distributivity is the desired behavior. To avoid that behavior, you can surround each side of the `extends` keyword with square brackets.

**Comment by yordis** [comment]
I see it now 🤦🏻 , but it went over my head, my apologies, I literally went to sleep with that page open for 20 mins.

Thank you so much for your patience and support.
