### ISSUE TITLE
Feature: Extends doesn't constrain a generic type

### ISSUE THREAD

**Issue by formula1** [microsoft/TypeScript#47730]
# Suggestion

## 🔍 Search Terms

EventEmitter, extends, generics, nodejs, typescript, keyof, Objects, interface, constraints

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). (I'm pretty sure)

## ⭐ Suggestion

Extends doesn't constrain the generic type, it just expects the type to have at least those qualities. I'd like to ensure that only the expected types are allowed. This is useful for things like a typed event emitter that loop over the keys of a generic. As it stands now, I have to get a bit ugly which may open up possible errors.

Having a `constrainedby` keyword or something similar would allow only generic types or child classes to be subclasses rather than extensions. This would allow child classes to still be considered children of their parents but more strict. However, extensions of the constrained child may try to override the parent so that still needs to be checked.

```ts

interface KeyListener {
  [key: string]: Array<0|1>
}

// No errors
class TypedEmitter<C constrainedby KeyListener> extends EventEmitter {
  on<T extends keyof C>(
    event: T, listener: (...args: C[T])=>void
  ){
    super.on(event, listener);
    return this
  }
}

const zero = Symbol("0");
const badInstance = new TypedEmitter<{ [zero]: [0,0,0,0], 1: [1,1,1,1] }>()
/*
    Error, The generic C in TypedEmitter<C> is constrained by KeyListener, only specified keys are allowed
    - [key: string]: Array<0|1>
    Found Bad Keys
    - [symbol("0")]: [0,0,0,0]
    - 1: [1,1,1,1]

*/


interface BadChildInterface constrainedby KeyListener {
  [zero]: [0,0,0,0],
  1: [1,1,1,1] 
  /*
    Error, BadChildInterface is constrained by KeyListener, only specified keys are allowed
    - [key: string]: Array<0|1>
    Found Bad Keys
    - [symbol("0")]: [0,0,0,0]
    - 1: [1,1,1,1]
  */
}


```

## 📃 Motivating Example

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/JYWwDg9gTgLgBAbzgUQG4FMB2NkmDGdKOAXzgDMoIQ4AidDbAZ1oChXhsjyBDAY3RwA0ugCeAGWBNCmIolZw4AbQDWYgFxxpUTgHMAupoCCUKD1EAeHplEA+BcrWjNTUSABGEADaG4Js5bWdqwk7HwQmNJabnAAvHAAym6eXgAUtBAqcLoQtACUANwcXFC8AnAAEuheXhAA6tBeACaS0lhETHDoAB4yTZ0iElIycggOtAAW1bW0mkq0PLT64wDujU2zyrTuSwA0DkquIL7zTOh8UOgwSwcAjCe0qEtwAPQvcABCPE27cACScAiXlEcBW1ng2j0nWsTWiHm8TBC7De-zgTQiAHJ4ABXTBNDowGG-GBTOBOQHkQGg4A1OA8Lxg0SddyCAAqrHIuL4MGAETgqGQpmgFgA8l1elh+sIxK0RlBfqzxX1Ok4IJSRbZUhBNCK8ppWWNFJcYNioJg4CL3AArc4wAB0TiYWrySgADPoiqEOVyeXzUF8mqKlZKBjLhu15XBFT1lWSxGqLZrtRa9VHDXBjabzZabdyHWInRAXe66Z1WZ72KwUQAFKjuLzoGhMUA0njEGAQOmeDCsPheHhMTqCqhQNBYGCs0RgdBNXD4QhQCwAYWDeNDQzasigtlXUrH2DnBFGDgiFmjErXcdECaXvwAarvOkulKz9JqHIoGOP9b8vOGt5oqR2sBba6EwmjPq+eSxLYqAQMATQOHk6aKEw2LTlAdoRKkX7YL+-5EIUH4ZlcWZwCSUgOKEXoogCA5oSAggkjw8D4OREycCoT4vvocDhNizRwCygLWraSiYNiHhELx8RBL2-aDigQpQLKEaTtOs54Eei4rjGIbShuco7npl77jgWkLvIiinuesaquqWnLr8ElSdu96PnAkFvqkxG4TAP5wH+m5EIBwF2qB4GeTx0GwfBiGKMhxFoRhWGYDhjAwPhwVQERihGqRZrsZRijUewMBToIXxnKpW5xHAQEgVAYHGKY5hWDYtgxXBCHIu8AByEDwOE3jyfRnzfOpM6Hguy4eYMNVEMZF57hl03HtZmBnh59kWo5t5wC5LJuXAD4mVKXnvnlXQZQFQVyqFjXNVFUEwd18VwIlV3JUQqXpeOWVyqW43VQROVFFdmaFRRiIlUirBAA)

[Overloading can get absurd](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L254)

Certianly not DRY

## 💻 Use Cases

EventEmitters, can't think of much else. But with how common event emitters are, this would be pretty great

Anything that loops over a keyof for type definition

**Comment by RyanCavanaugh** [comment]
See #14520

**Comment by formula1** [comment]
I didn't know what to call it but I like super, at typescript is aware of what people want. Overall, I'm pleased though.

**Comment by thw0rted** [comment]
Hi @RyanCavanaugh , you pointed to #14520  but no one from the team has been active on that issue.  Could you please take a look?
