### ISSUE TITLE
Hold back squiggling code fragments until all symbols have been imported 

### ISSUE THREAD

**Issue by moniuch** [microsoft/TypeScript#47734]
This code below is all squiggled as if the entire fragment was completely wrong, eg. messed up by an unbalanced parenthesis, or a missing comma. 

![image 2022-01-27 22-15-13](https://user-images.githubusercontent.com/681956/151446194-889487c0-4190-4c5c-abea-f96ef6f72eb1.png)

Meanwhile, this is just because of a missing import of `map` from `rxjs`.
The TS typing error messages weren't helpful enough to make me immediately spot the problem.

What I am asking here is to change the principle behind rendering of the squiggles to the following: don't mark any fragments of code before all symbols have been known. First flag missing imports **only**, once this is done, go and mark the squiggles as need be.

(Could be that there is a theme-related setting that I am unaware of, which can render double squiggles: one run for the unknown symbol, another for the code error. If so, I could adjust my theme with different styles for each runs. If so, then please share the name of the theme setting with me.) 

Not sure why the `cmd-.` auto-fix item for bringing all missing imports is not available, either.

**Comment by mjbvz** [comment]
Thanks @moniuch 

Someone on the TS team can weigh in too

Here's a simple repo:

```
export function foo(x: string) { }

foo({ x: noSuchSymbol })
```

We already surface two errors here: one for the missing symbol missing and one for the incorrect type. My ideas on improving this:

- Figure out a better UX for showing overlapping error spans on the VS Code side (previously discussed on https://github.com/microsoft/vscode/issues/88514)
-
- Keep both errors but make the outer one clearer that it involves an unresolved symbol and fixing that may fix the problem (potentially using related error spans)



As a side note, I do see the add missing import quick fix when my cursor is the missing symbol name (`map`):

![Screen Shot 2022-02-03 at 6 08 50 PM](https://user-images.githubusercontent.com/12821956/152460765-0aa80f05-97aa-40fe-b334-53c873f8d42f.png)

**Comment by moniuch** [comment]
@mjbvz I am by no way an expert in TS, but IMO:

> one for the missing symbol missing and one for the incorrect type

It is not possible to evaluate the type as correct or incorrect before you have all imports in place. Hence my ticket title: first flag missing imports only, flag only these code "units" where you don't have missing imports. IMO, very logical and clutter-free. 

Your side note also points to another productivity issue - the caret position required for the import fix is unnecessarily strict. I believe, under the hood it is clear for the language service that there are some imports still unresolved, in which situation the `Add all missing imports` fix should be available regardless of the caret position. Please correct me if I am wrong in my assumption. Relaxed position wherever possible would save developers from unnecessary navigation/mousing around the code.

**Comment by fatcerberus** [comment]
@moniuch In the specific example given:

```ts
export function foo(x: string) { }

foo({ x: noSuchSymbol })
```

The typing here is known to be incorrect regardless of the type of `noSuchSymbol`, since the function wants a `string`.  Thus the type error here is still useful (arguably *more* useful than the unresolved symbol error, even, since there's no sense fixing the latter, e.g., by adding imports, if I'm still going to have a type error afterwards).  If the call is changed instead to `foo(noSuchSymbol)` then the type error goes away (the unresolved symbol is treated as `any`).

**Comment by moniuch** [comment]
@fatcerberus As I did not author the simplified snippet that you are quoting, I am not claiming it is correct or conclusive. My belief is that the code from the OP should not be squiggled while some of the imports within it were still missing.

**Comment by RyanCavanaugh** [comment]
I don't see a concrete description of what to change here that isn't in conflict with other goals
