### ISSUE TITLE
Promise#finally may return promises

### ISSUE THREAD

**Issue by danielrentz** [microsoft/TypeScript#47736]
# lib Update Request

Callback function of `Promise#finally` is allowed to return promises [1]. This is not reflected in the type definitions and causes linter errors.

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `the default`.

## Missing / Incorrect Definition

`lib.es2018.promise.d.ts` defines the callback of `Promise#finally` to be a void function.
```typescript
interface Promise<T> {
    finally(onfinally?: (() => void) | undefined | null): Promise<T>
}
```
This causes typescript-eslint to issue a warning about unexpected usage of promises [2] (see sample code below).

Proposed change:
```typescript
    finally(onfinally?: (() => void | Promise<void>) | undefined | null): Promise<T>
```

This would also allow to return other pending promises that will settle later and will defer the promise returned by `finally`. The resulting promise will resolve/reject with the original value/error when that promise fulfils, or will reject with the new error when that promise rejects. At least this works in V8 although I did not find an explicit specification of this behavior.

## Sample Code

```typescript
const promise = Promise.resolve().finally(() => Promise.reject(new Error()));
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Promise returned in function argument where a void return was expected.
// eslint(@typescript-eslint/no-misused-promises)
```

## Documentation Link

[1] https://github.com/tc39/proposal-promise-finally
[2] https://typescript-eslint.io/rules/no-misused-promises/

**Comment by MartinJohns** [comment]
It works just fine: https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBADgJxAWwJYQKYwLwwApJqYB0CGEIANgG4YAUAlMQGapgCGllAnnYzgD58hdBlIYAVhmBQ6YDAHcYAUQRIEjBgwDcAKCA

You're receiving a linter warning, not an error from TypeScript. See #38752 and #44980.

**Comment by danielrentz** [comment]
I see. Seems I forgot to remove the "is:open" tag when searching for dups before reporting...
