### ISSUE TITLE
TSC cannot infer type indirectly

### ISSUE THREAD

**Issue by KermanX** [microsoft/TypeScript#47745]
# Bug Report

### 🔎 Search Terms

type inference, type parameter, extends

### 🕗 Version & Regression Information

Every version. including `nightly`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCA8AVAfNA3gKGtMAuai0APtAK4B2AJgKYBmAludZQNwYC+GokMAQkqmoAPAC7UqMBOVIBbAEbUATqkzY5+QiQo0GTVhwwiAngAdqBU9QDytBIWFiJceBQDW5APYB3cslTQAXgJoB3FKSXhGWiUCWGQAfkRYIm06RmZcJgA3JTYucChoAGEkENEwvhdyd29fFSxoWnIACiENSxs7ZABKdAbselpoVugAQgCg1N1mXtVsebAQJRFm4zMPIaFutnnoTmxOTiA)

### 💻 Code

```ts
class A<T> {
  a: T | undefined;
}
type TypeOfA<T extends A<unknown>>  = T extends A<infer TA>?TA|undefined:never;

class C<T extends A<number>> {
  fn(x: TypeOfA<T>) {
    if (x !== undefined) {
      x++; //ERROR: An arithmetic operand must be of type 'any', 'number', 'bigint' or an enum type.
    }
  }
}
```

### 🙁 Actual behavior

Cannot infer `x` a `number|undefined`. 

### 🙂 Expected behavior

`x` should be inferred as `number|undefined`. 

Because whatever the `T` of `C<T>` is, `T` is extended from `A<number>`.

So `TypeOfA` should always be `number|undefined`.

Also, `TypeOfA<A<number>>` is `number|undefined`.

**Comment by fatcerberus** [comment]
Counterpoint:
```ts
const c = new C<{ a: 812 | 1208 }>();
```

**Comment by MartinJohns** [comment]
When you pass a generic type to a conditional type resolving it will be deferred until you have an actual type. See #46155 for more information.

**Comment by KermanX** [comment]
> Counterpoint:
> 
> ```ts
> const c = new C<{ a: 812 | 1208 }>();
> ```

Thanks a lot.

But this is only for `++` operation.

Actually, `x` is not inferred as `number`.

See: [playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCA8AVAfNA3gKGtMAuai0APtAK4B2AJgKYBmAludZQNwYC+GALgJ4AO1Av2oB5WgkLUAHl2pUYCCgGtyAewDu5ZKmgBeAtGmz5ceI1rUATgVjIA-IlhEKNBk0q4mANytsMoSBgAYSRDGTlKBXhyUgBbACMrbXQsaFpyAAopfERhMQlkAEoU7Gx6Wmgs6ABCXX0XOkZmYsxS0pBqLhw9aCkAagBGNjbObE52IA)

**Comment by KermanX** [comment]
@MartinJohns 

> When you pass a generic type to a conditional type resolving it will be deferred until you have an actual type. See #46155 for more information.

Thanks a lot.

I've tried my best to understand it *(using my poor English)*, but still confusing...

The code of this issue is a minified version of my real situation.

In my real situation, the type isn't a "generic type" like `number`, but a `class` or `interface`.

So, could someone give me some more information, or a way to solve it ( To make `x` a `number` as expected)?

**Comment by MartinJohns** [comment]
> So, could someone give me some more information, or a way to solve it ( To make `x` a `number` as expected)?

Drop the generic type.

```typescript
class C {
  fn(x: TypeOfA<A<number>>) {
    if (x !== undefined) {
      x++;
    }
  }
}
```

**Comment by KermanX** [comment]
@MartinJohns 

This works, thanks a lot.

I personally think that this is a REAL BUG of typescript.

In this [playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCA8AVAfNA3gKGtMAuai0APtAK4B2AJgKYBmAludZQNwYC+GALgJ4AO1Av2oB5WgkLUAHl2pUYCCgGtyAewDu5ZKmgBeAtGmz5ceI1rUATgVjIA-IlhEKNBk0q4mANytsMoSBgAYSRDGTlKBXhyUgBbACMrbXQsaFpyAAopfERhMQlkAEp0aAB6UoBaAAkragAaaAADKUboehg1LiaYhKtnKjpGZkbU8ugAPTtU7HpaaCzoAEJdfRdB92K0Mewd3cBEwmmdkGousD1oKQBqAEYWXd3t+52iQ-Yn94-H95fsN4--+5fJ4vP4AsHYIH3F7HLrAc5MdTQIIZQp3f6Q3aAZMJ-AA6dIZa4AJgAzAAWACsADZUWVKhV6Qz6QAhUhdAAWtQazVa7W6cUSln6riGlBGY0mQA), I find it acts differently as parameters and arguments.

##### Expected:

The same parameter and argument should have the same inferred type.

```ts
class A<T> {
  a: T | undefined;
}
type TypeOfA<T extends A<unknown>>  = T extends A<infer TA>?TA|undefined:never;

class C<T extends A<number>> {
  fn(x: TypeOfA<T>) { //-Here, `x` is not `number|undefined`
  // ^?
    if (x !== undefined) {//          ↑
      let a = x+1;        //          |
    }                     //          |
  }                       //          |
}                         //          |
let c = new C();          //          ↓
c.fn(123456); //---------But here, `x` is `number|undefined`
// ^?
```

**Comment by MartinJohns** [comment]
> I personally think that this is a REAL BUG of typescript.

You may think that, but it's simply not. The issue I linked earlier goes into more details. This is at most a design limitation.

> fn(x: TypeOfA<T>) { //-Here, `x` is not `number|undefined`

Here the compiler **doesn't know** what type `T` is, so resolving the conditional type `TypeOfA<T>` is deferred. In order to resolve this type it must know what type `T` is.

> let c = new C();  
> c.fn(123456); //---------But here, `x` is `number|undefined`

Writing `new C()` is the same as writing `new C<A<number>>()`. Here the compiler **knows** what the type `T` is, because it's provided: it's `A<number>`. So now the compiler can resolve the type `TypeOfA<T>`, because it is known what `T` is: `TypeOfA<A<number>>`.

**Comment by KermanX** [comment]
> It boils down to the simple question: Does the compiler know what type T is? It is not enough to know what it extends, but what the type actually is.

I agree with you, and I read #46155 again. That is exactly what I mean.

Thanks for your help, I think I've known why it works like that.

However, there are 3 questions in my mind:

1. Is there some situations that `T` which extends `A<number>` has `a` whose type isn't `number|undefined`?
    Or, is there some situations that `T` extends `A<"SomeTypeIsNotNumber">`?
    In a nother word, what is missing since @MartinJohns said "It is not enough to know what it extends"? I have no idea as far as I know
2. If the answer of Q1 is "No, there isn't", can it be a feature of TypeScript to infer `TypeOfA<T>` and `x.a` as `number|undefined`, or it is a limitation of compiler, or there is something bad happends if ts has this feature? I don't know.
3. In my project, [my error code](https://github.com/UniCoderGroup/ucon/blob/839c28c52a30f47edb573ef17c72dd9414ad1c4c/src/std_components/block.ts#L128) cannot be solved like [the reply](https://github.com/microsoft/TypeScript/issues/47745#issuecomment-1030610895). Because that will make code worse. Now, I can only solve it via `as` operator. Is there some better ways to solved it *(if Q2's answer is "this can be a feature", I will wait for it)*?

**Comment by MartinJohns** [comment]
> 1. Is there some situations that `T` which extends `A<number>` has `a` whose type isn't `number|undefined`?
>    Or, is there some situations that `T` extends `A<"SomeTypeIsNotNumber">`?

Fatcerberus already gave you an example. `A<123>`

**Comment by KermanX** [comment]
> Fatcerberus already gave you an example. Here's another: `A<123>`

Oh, I carelessly forgot this. I didn't use to think Fatcerberus's words this way.

Thank you a lot.
