### ISSUE TITLE
Imported alias invoking generic is `any` where original alias & manual recreation in other file resolves correctly.

### ISSUE THREAD

**Issue by Myrdden** [microsoft/TypeScript#47743]
# Bug Report

### 🔎 Search Terms

imported type any
imported type alias any
imported type widening
imported type becomes any
exported type any
exported type alias any
exported type widening
exported type becomes any

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about import, export, widen

### ⏯ Playground Link

This is related to the use of import/export across files & I'm not sure how to get TS Playground to use multiple files so I don't really know how to provide this.

### 💻 Code

There are two files:
File A has something like
```ts
export type RequireSome <T, Ks extends keyof T> = (Omit<T, Ks> & Required<Pick<T, Ks>>);

export type SymbolA = unique symbol;
export type SymbolB = unique symbol;

export type Foo <T, U> = {
    [SymbolA]?: boolean;
    [SymbolB]?: boolean;
    
    // other props
};

export type DefaultFoo <T, U> = RequireSome<Foo<T, U>, (typepof SymbolA | typeof SymbolB)>

type TestWithinFileA = DefaultFoo<string, string>; // => Correct, resolves to Foo<string, string> with symbols required.
```
File B then has something like:
```ts
import { Foo, DefaultFoo, SymbolA, SymbolB, RequireSome } from './fileA';

type TestManual = RequireSome<Foo<string, string>, (typeof SymbolA | typeof SymbolB)>; // => Correct, resolves to Foo<string, string> with symbols required
type TestDefault = DefaultFoo<string, string>; // => Incorrect, resolves to just any
```

### 🙁 Actual behavior

When I use the `DefaultFoo` alias within the file where it's defined, it correctly shows Foo with the two symbol types marked as required. When I attempt to use the `DefaultFoo` alias in any other file as an import, it incorrectly just shows up as `any`. However, manually recreating `DefaultFoo` in any of these files will resolve correctly as it does in the original export.

### 🙂 Expected behavior

I'd expect the DefaultFoo alias to resolve to the correct object type, or at the very least resolve consistently to the same thing regardless of where it's being invoked.

**Comment by RyanCavanaugh** [comment]
I can't reproduce this. We'll need something more specific.

![image](https://user-images.githubusercontent.com/6685088/152601427-4975421e-d81e-4d0a-8130-6163a8bb2e2c.png)

**Comment by Myrdden** [comment]
Yep, you're right, not a bug... The `DefaultFoo` type was mapped and somehow that mapping was the root cause, because it was rewritten and now everything works. My bad, never mind.
