### ISSUE TITLE
Missing properties quickfix does not handle generic parameters

### ISSUE THREAD

**Issue by hpx7** [microsoft/TypeScript#47746]
# Bug Report

### 🔎 Search Terms

quickfix missing properties generic parameter

### 🕗 Version & Regression Information

The quickfix was added in https://github.com/microsoft/TypeScript/pull/44576 (cc @a-tarasyuk) but it doesn't appear to handle generic parameters.

### 💻 Code

```ts
interface Foo<T> {
  foo(): T;
}
const x: Foo<string> = {};
```

### 🙁 Actual behavior

The following is generated by the quickfix:
```ts
interface Foo<T> {
  foo(): T;
}
const x: Foo<string> = {
  foo: function (): T { // <-- this is wrong
    throw new Error("Function not implemented.");
  }
};
```

### 🙂 Expected behavior

I would expect to see `string` instead of `T`:
```ts
interface Foo<T> {
  foo(): T;
}
const x: Foo<string> = {
  foo: function (): string {
    throw new Error("Function not implemented.");
  }
};
```

**Comment by komyg** [comment]
Hey @RyanCavanaugh, I would like to help on this bug. Could you assign this issue to me?
