### ISSUE TITLE
Organize imports removes type imports that are only referenced in `@link` (jsdoc)

### ISSUE THREAD

**Issue by brunnerh** [microsoft/TypeScript#47753]
# Bug Report

### 🔎 Search Terms

organize imports link

### 🕗 Version & Regression Information

As far as I know this is the behavior ever since `@link` support was added.

### ⏯ Playground Link

[Playground link with relevant code][pg]

### 💻 Code

```ts
/// <refenrece types="zod"/>
import type { ZodType } from 'zod';

/** Intended to be used in combination with {@link ZodType} */
export function fun() { /* ... */ }
```

### 🙁 Actual behavior

Import is shown as not being used and gets removed on executing "Organize imports".

### 🙂 Expected behavior

Keep it.

[pg]: https://www.typescriptlang.org/play?#code/PQgEB4CcFMDNoHYwMbVAFwJ4AdoGcBeAIgC8B7AEyOAD4BYAKAEsBbbMydDHNAb1ABalACo9QAX1CxIZFqADk5CvIDcjRsABUm0AEkE6RBWgUMZUACM0AVzwnQTBKGSyLjgIbomZJwHcm6AAWoLwAAgA2jgDWgiI8kprAjNAAHuycUtYIyF4+mQgAFACUIeoM4oxAA

**Comment by komyg** [comment]
Hi @RyanCavanaugh, I would like to help out on this. Could you assign this issue to me?

**Comment by komyg** [comment]
Hi, the PR is ready for review. Please let me know what you think.

**Comment by DanielSWolf** [comment]
This is related to #47558.
