### ISSUE TITLE
Merging signatures using a union as rest parameters results in `never`.

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#47754]
# Bug Report

### 🔎 Search Terms

merged parameters rest union never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `union`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAShDOwAKBDATigtvKBeKA2iAFxSJoCWAdgOYC6UAPoSVFQK6YBGEadA3AChBoSFADKFGlRTB2aaPgAUAD1LlqNADRQAdPoWJScRKgzYAlHgB8UAG4B7CgBMhI8NACyvGhGdmsHHwAzAhgXngAHklpWXkIa34oAHpktgg7XiA)

### 💻 Code

```ts
type RestParams = [y: string] | [y: number];

type Signature = (x: string, ...rest: RestParams) => void;

type MergedParams = Parameters<Signature>; // never
```

### 🙁 Actual behavior

`MergedParams` is of type `never`.

### 🙂 Expected behavior

`MergedParams` is of type `[x: string, y: string] | [x: string, y: number]`

I realise this can sort of be done by using `[y: string | number]` as type for `RestParams`. However, I'm using unions in parameters like this in order to overload the signatures of functions in jsdoc as shown here: https://github.com/microsoft/TypeScript/issues/25590#issuecomment-942782630
If I use a union like that it will show up as union in VSCode, instead of using the multiple signatures UI.
Here's an example of this: [Playground link](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAShDOwAKBDATigtvKBeKA2iAFxSJoCWAdgOZQA+UVArpgEYRoC6A3AFChIUAMoUaVFMGZpo+ABQAPUuWo0ANFAB02mYlJxEqDNgCUeAHxQAbgHsKAE36DoAWU40I9o1ngBGPFDemBDAnPAAPKLiktIQ5vwAxjZUiFCYIABizFQJwBTJ-vLamug08KRuaB5e6D6+ZriWAN4AvnwC4NBRAIIBisrAlLQaJGSDqg2Wtg5OnSJiAEJ9SmND6lCjLOyck9Z2jh1CldVB8ABMAUEhYZFivYxRC-F8SSnAaZnZuflUF0XapXKUGOnlOZ12rXa7QA9NDAgAbFAJaAgGzSKAJdAyd4AC040BQVHsUDAuhwCUw9mhuTQ8KgAGoyDiKAAzd6M+BgJEQPiwqD8gUC+j0XlwwWCgA60L46SyOTyBTkJihoqgABVmTgKDhgHioBwcSgrPl0QBJKAAdzR8OJEAUkFyqvFQpFfOd-KlMs+8p+ZyVQA).

**Comment by RyanCavanaugh** [comment]
@ahejlsberg what's the intended behavior here?

**Comment by ahejlsberg** [comment]
The core issue here is that we don't always consider equivalent signatures to be assignable. For example:

```ts
declare let f1: (...rest: [string, string] | [string, number]) => void;
declare let f2: (x: string, ...rest: [string] | [number]) => void;

f1 = f2;  // Error
f2 = f1;  // Error
```

Ideally the assignments above would be permitted as the signatures are functionally equivalent.

**Comment by ahejlsberg** [comment]
I should add that a workaround is to write the signature such that all parameters are specified in the rest tuple:

```ts
type RestParams = [x: string, y: string] | [x: string y: number];

type Signature = (...rest: RestParams) => void;

type MergedParams = Parameters<Signature>; // [x: string, y: string] | [x: string y: number]
```

But ideally that wouldn't be necessary.
