### ISSUE TITLE
Please standardize the practice about importing external js/node/wasm module with a *.d.ts type declaration file

### ISSUE THREAD

**Issue by chenzx** [microsoft/TypeScript#47757]
Currently, there is no explicit documentation on how to import an external js/node/wasm module with a *.d.ts type declaration file, I'm trying to import a Nodejs native *.node addon into a TypeScript project with a *.d.ts type declaration file, here is my intuitional expect:

- During TSC compilation process, a *.d.ts type declaration file should be enough, no *.js/*.node/*.wasm is needed at this phrase;
- When TSC has done compilation and bundler has got a bundle.js file, I'll put the *.js/*.node/*.wasm module file at according path, since it's `external`

However, i only managed to make it work with the limits below:
- The external *.js/*.node/*.wasm module file and the related *.d.ts type declaration file have to be put together, &
- Although it's said TS operates *.ts compilation in `type space` (with JS in `value space`), but this confuse me in this scenario……

**Comment by chenzx** [comment]
I'm concerning *.node as `typed external module import`, to add *.js/*.wasm is for their common similarities. As with *.js, there has been `best` practice: node_modules/@types/xxx with DifinitelyType? but this solution has internal limits:

- js lib MUST be published to npm publicly, if it's a private lib maintained by another team in enterprise, and setup a private npm registry server seems too heavy, then tsconfig's `typeRoots` and `paths` mapping is very confusing
- wasm lib is under my consideration, I'm hoping it can be used to improve performance of an interbal React-native like GUI lib's animation module.. AWS has a report recently.

**Comment by RyanCavanaugh** [comment]
I don't understand what you're talking about, or what you're asking to do.

Please follow the issue template.
