### ISSUE TITLE
Support async & await over ES5

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/TypeScript#4776]
Hi all.

If I target ES5, with noLib option and manually pointing to lib.es6.d.ts, with a polyfill for es-6 Promise, It would be to be able to use async & await. Even with a limited transpilation (i.e. not supporting yield).

**Comment by danquirk** [comment]
I think this might just fall under issues like https://github.com/Microsoft/TypeScript/issues/4389, albeit one of the more important cases today. Agree/disagree?

**Comment by SergioMorchon** [comment]
Definitely agree!
Sorry for duplicate it. I've searched any similar issue but didn't find anything.

Thank you @danquirk

**Comment by danquirk** [comment]
Great, don't worry about filing dupes (although I'm quite happy if you do a cursory search like you did :)), all feedback is good, we'll always route/triage it ourselves as necessary.
