### ISSUE TITLE
How to auto-generate a <///reference ...> in top of typescript file

### ISSUE THREAD

**Issue by WanderWang** [Microsoft/TypeScript#4777]
I 'm writing TypeScript with WebStorm in MacOS . I hate write ```<///reference ...>``` in every typescript file manually .
Is there some way to generate it with typescript-service or other 3rd-library ?????????

**Comment by aleksey-pastuhov** [comment]
Use `*.d.ts` as global definition in your project... And usually you do not need to use `<///reference ...>` in case of [tsconfig.json](http://basarat.gitbooks.io/typescript/content/docs/project/tsconfig.html).
Read this [TypeScript book](http://basarat.gitbooks.io/typescript/content/docs/project/globals.html).

**Comment by WanderWang** [comment]
I know tsconfig.json , but....
I want to sort my file list with right dependency  , but all of  sort-utils depend on  ```<///referece>``` ( such as https://www.npmjs.com/package/typescript-filesort

so , I want to do it this way :

1. generate  ```<///referece>``` 
2. generate file list with https://www.npmjs.com/package/typescript-filesort 
3. generate a output.js from multi-typescript files

and I know VS can generate ```<///referece>``` automatically  , so I want to know how can it do that ? which TypeScript Service API ?

thank you !!

**Comment by aleksey-pastuhov** [comment]
Oh.. maybe I don't understand you good, buy in VS2015 we have project settings. And it compiles in this order:
```XML
...
  <ItemGroup>
    <TypeScriptCompile Include="scripts\core.ts" />
    <TypeScriptCompile Include="scripts\resource.ts" />
  </ItemGroup>
...
```

**Comment by mhegazy** [comment]
There is not an API to generate a reference. the API only consumes them. if you know the file you want to generate the reference to just write it as a string to the top of the file `/// <reference path="<filepath>" />`
