### ISSUE TITLE
Don't show methods on classes from declarations not imported

### ISSUE THREAD

**Issue by jovdb** [microsoft/TypeScript#47789]
# Suggestion

```
// point.ts
export class Point {
  public constructor(public x: number, public y: number) {
  }
}

// point-transform.ts
import { Point } from "./point";

declare module "./point" {
  interface Point {
    transform(this: Point, transform: ITransform): Point;
  }
}

Point.prototype.transform = function transform(this, transform) {
  const [x, y] = transformPoint(transform, this.x, this.y);
  return new Point(x, y);
};

// main.ts
import { Point } from "./point";
import { Transform } from "./transform";
// import "./point-transform"; // missing!

const point = new Point(1, 2);
point.transform(Transform.scale(2)); // @compile time: OK, @run time: TypeError: transform is not a function
```
Example: https://stackblitz.com/edit/point-transform-8zvjtw?file=index.ts

- The `transform` method is added to the intellisense, but the file containing that declaration was never imported.

## 🔍 Search Terms
extend class interface prototype declare

## ⭐ Suggestion
I don't know if there is a reason for it, but it would be nice if Typescript doesn't show methods on classes from declarations not imported.
Here `point.transform()` should not be available until we load the file containing the declaration in the project.
For backwards compatibility I would expect a compiler flag is needed for the more stricter behavior.
**Remark:** This can still cause a runtime error if the `Point.prototype.transform` is not available.

## 📃 Motivating Example
It happens quite a lot that that we forget imports because TypeScript does not complain.
We only notice the problem in tests when that code path was used.

**Comment by DanielRosenwasser** [comment]
It won't show up in StackBlitz for whatever reason, but if you switch your `tsconfig.json` to only include entry-points, or non-augmenting files, you should get the behavior you want.

```json5
{
  "compilerOptions": {
    "target": "esnext"
  },
  "files": ["index.ts"]
}
```

**Comment by RyanCavanaugh** [comment]
You can use `explainFiles` to see why this file is in your program: https://www.typescriptlang.org/tsconfig#explainFiles
