### ISSUE TITLE
Awaited on typescript 4.5.5 not working

### ISSUE THREAD

**Issue by Egorzaa** [microsoft/TypeScript#47803]
# Bug Report

I've installed: 
"typescript": "^4.5.5"

try to use Awaited type, but vscode writes: Cannot find name 'Awaited'.ts(2304)

I read that it should be already included in package here:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#:~:text=TypeScript%204.5%20introduces%20a%20new,in%20async%20functions%2C%20or%20the%20.&text=The%20Awaited%20type%20can%20be,all%20%2C%20Promise.

<img width="574" alt="Снимок экрана 2022-02-08 в 16 35 01" src="https://user-images.githubusercontent.com/30752631/152998011-82b48b95-2d95-4f23-8a11-1bbd3788622a.png">

How to use Awaited type?

**Comment by MartinJohns** [comment]
Make sure you have the `"es5"` lib referenced in your tsconfig.json file.

**Comment by sk-** [comment]
In my case the issue arose because I hadn't updated my version of vscode. It would be nice if there was a warning when the typescript compiler is higher than the version supported by vscode.

**Comment by enheit** [comment]
> In my case the issue arose because I hadn't updated my version of vscode

Same thing. After updating vscode to the latest version `Awaited` type started to work

**Comment by Mng12345** [comment]
Still showing errors with tsc.
**typescript version: 4.8.3**
![image](https://user-images.githubusercontent.com/21278900/190606574-cdb58cc6-3918-429d-a5da-a3aab8415a6d.png)

**Comment by MartinJohns** [comment]
@Mng12345 It's a configuration / user issue. You should post your tsconfig file and the **exact** command you use to compile.

**Comment by AndrewRayCode** [comment]
Same issue
```
npx tsc --version
Version 4.4.4
```

```
npx tsc
api/update.ts:20:17 - error TS2304: Cannot find name 'Awaited'.

20     enrollment: Awaited<ReturnType<typeof getActive>>[0]
                   ~~~~~~~
```

Strangely, vscode reports no issues with this code. 

tsconfig:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by MartinJohns** [comment]
@AndrewRayCode The `Awaited<T>` type was added in TypeScript 4.5. You're running version 4.4.
