### ISSUE TITLE
New keyword to declare similar interface to a class

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#47815]
# Suggestion

## 🔍 Search Terms

implements class 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add keyword `seemskindalike` which would be used similarity to `implements` but has a concrete class operand on the right.

## 📃 Motivating Example

Sometimes we want to implement classes that are similar to others, but instead of using inheritance, we want composition. However, in these cases we often want to declare that we implement the same interface as the class we're composing. Yet `implements` only takes an interface, and often times the class itself is the only interface available.

## 💻 Use Cases

Consider for example composing a Map with a custom Map-like object:

```ts
class MultiIdMap<K extends { ids: string[] }, V> {
  #multiKeys: Map<string, K>;
  #realMap; Map<K, V>;

  get(key: K): V | undefined { /* ... */ }
  // ... etc for all other Map methods
}
```

In this case, the compiler won't in any way help us ensure our new MultiIdMap is anything like a real Map. We just have to rely on coincidence or extra diligence.

But if we had this:

```ts
class MultiIdMap<K extends { ids: string[] }, V> seemskindalike Map<K, V> {
  // ...
}
```

Then the compiler could warn if we miss some methods on Map, and will help with auto-complete on the use-sites.

**Comment by sdegutis** [comment]
Ah yes, I forgot classes produce an interface automatically in TypeScript. Dang. I was hoping for the keyword `seemskindalike` to have a chance. Oh well.

**Comment by fatcerberus** [comment]
> `seemskindalike`

😆
