### ISSUE TITLE
Bloomberg feedback on TypeScript 4.6 Beta

### ISSUE THREAD

**Issue by molisani** [microsoft/TypeScript#47814]
_This issue has been created by the team responsible for the infrastructure behind most of Bloomberg's TypeScript code._

### Summary

We have tested TypeScript `4.6.0-beta` on our codebase and our experimentation **has not revealed any new errors in TypeScript source**, pointing to this being a straightforward update.

### Grammar Errors in JavaScript Files

As reported in the [4.6 iteration plan](https://github.com/microsoft/TypeScript/issues/46858), TypeScript now reports grammar errors for JavaScript files contained within TypeScript projects: https://github.com/microsoft/TypeScript/issues/45349

These errors are now reported even when `checkJs` is not specified, and require explicit `checkJs: false` to disable them:

**Before:**
- `checkJs` `false` or \<unspecified\>: no diagnostics on *.js files
- `checkJs` `true`: grammar + inference-based type errors on *.js files

**After:**
- `checkJs` `false`: no diagnostics on *.js files
- `checkJs` \<unspecified\>: grammar errors on *.js files
- `checkJs` `true`: grammar + inference-based type errors on *.js files

Is it intentional that users now need to be explicit to avoid any errors on *.js files?

_Credits to @dragomirtitian & @tchetwin for helping with this investigation._

**Comment by RyanCavanaugh** [comment]
Interesting. Can you share what kind of grammar errors were encountered?

**Comment by molisani** [comment]
> Interesting. Can you share what kind of grammar errors were encountered?

Virtually all of the grammar errors that are now reported are redeclaration errors. They are technically valid errors for our JavaScript source, and we're actively working on fixing them. However, without going into too much detail, they don't cause runtime errors for our specific runtime. As such our solution is to set `checkJs: false` for these projects, ignoring these grammar errors. This allows us to maintain the same set of diagnostics from ts4.5 (for now) while re-evaluating our strategy for how we'll tackle these.

**Comment by sandersn** [comment]
Can you describe the structure of the files that contain the redeclaration errors? Are they scripts (files without import/export)? Are they compiled all at once, but loaded or bundled individually?

**Comment by sandersn** [comment]
@molisani It would help me to talk to you to decide whether Bloomberg's errors will appear in most other codebases and whether to turn off that error. I sent you a DM on twitter in case you have time in the next couple of days.

**Comment by sandersn** [comment]
From talking in person, it sounds like the mismatch between the new errors and the runtime should only apply to Bloomberg, and the few other people who are using that (quite old) runtime.
