### ISSUE TITLE
emitDecoratorMetadata should include abstract-ness

### ISSUE THREAD

**Issue by billccn** [microsoft/TypeScript#4781]
Before TS 1.6, I "annotated" many classes with a static boolean property named `abstract` to tell some introspection code not to use them. However, it seems there is no run-time equilavent of this for TS 1.6 abstract classes. Can something like this be added?

Maybe this could be done as an implicit decorator that does nothing by default?

**Comment by danquirk** [comment]
Could you give a more concrete example of why your own decorator function isn't sufficient here?

**Comment by billccn** [comment]
If I use my own, I'll have to use on the same class a keyword and a decorator that seems to mean the same thing. This is confusing and error prone, so definitely not good for maintainability. The decorators proposal allow additional type info to be exposed through decorators, so why not the abstract-ness?

**Comment by danquirk** [comment]
So would it be sufficient if this flag https://github.com/Microsoft/TypeScript/issues/2577 included the abstractness?

**Comment by billccn** [comment]
Yeah, that would work I guess.

**Comment by RyanCavanaugh** [comment]
Doesn't seem to be sufficient demand to warrant further investigation here
