### ISSUE TITLE
Key remapping breaks definition navigation for mapped type properties

### ISSUE THREAD

**Issue by ayatkevich** [microsoft/TypeScript#47813]
# Bug Report

When using mapped type with key remapping, definitions for the properties of mapped types are no longer discoverable. Though, references are still in there.

### 🔎 Search Terms

mapped types, key remapping, language server, editor hints

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/MYewdgzgLgBCBGArApsWBeGBvAUDfMAhgFwwCMANATAPQ0yCg5DMIWDAOYgxRcAmyAMwCWYIVCHgaAJ0HIZYYMghUWbeYQC2yPAXikATFQJ1GzVhy48Y-YaPGSZAucgVKV59Vp35gpAOQgANZ+VCZMYFyOzq7KZmoumtoAvgDcODQAVBmmnshwAtgAAgA2IoFwSKhQAHSESURgvEWlYOUIKGjV8PUA7kLFxcwgUjJoxQCeMLlEA9wAFnlR8ooQRKs9yLMZNDg4oJCwMhqEAA4AQuMA0sjjpLjUANoACjAiMIE3IAVQ4yfIXxUOrBCKsXsgAB5QFy8VZ+YB+GAAfhgYGQADc5DBSE8ALqkAAMaXqmCwRAJVD0MHxMFSuyOpwu13GtRStHogBlyOJ+WCcbh8QQiMQSMDuMDcqYJLRUJjjZCwOZCdhzUpKqCrGyC+xgHD085XG5dVkmTmqcW8qwauzC0Xi3LSmCy+WK5XOtXWAVW8A65DHPVM6rAI30JhyKTDVYgmAQv5oZC8Xb7aAS30XABqhGKAFdkHdvDBnq82B9xgCfn8Ae0qmtuL9-gVK2hnjio5DoatoFIROwkSj0ZjsXiqUSYCSyVSKQSaWlvSnxums8gWWyYCbWGbLPzbELwDbDpLkPbHTAFUqVXM3Zbt9rdWmM9nDcvV2KeRv3VutbuJWBEoe5cfnWeF4eleM4MnOd6LoGy4hiM4bVtGVRxjgQA)

### 💻 Code

```ts
const object = {
    a: 1,    // ✅ can go to definition/references, can rename
    b: 2,    // ✅ can go to definition/references, can rename
    c: 'ok', // ✅ no references, can rename
};
/** ✅ rename of {@link object.a} and {@link object.b} will correctly rename all the references as well */

const remapByKey: {
    [P in keyof typeof object as P extends 'c' ? never : P]: 0;
} = { a: 0, b: 0 };

remapByKey.a; // ❌ can't go to definition, can't rename, ✅ yet highlights definition
remapByKey.b; // ❌ can't go to definition, can't rename, ✅ yet highlights definition
remapByKey.c; // ✅ errors as expected

const remapByValue: {
    [P in keyof typeof object as typeof object[P] extends string ? never : P]: 0;
} = { a: 0, b: 0 };

remapByValue.a; // ❌ can't go to definition, can't rename, ✅ yet highlights definition
remapByValue.b; // ❌ can't go to definition, can't rename, ✅ yet highlights definition
remapByValue.c; // ✅ errors as expected
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/139799/153194436-73e456e4-d438-4971-902f-9d56769ecfa8.png)

### 🙂 Expected behavior

Capability to navigate to definition of remapped property.

**Comment by RyanCavanaugh** [comment]
The highlighting you see is purely syntactic; unrelated instances of `a` will also highlight for example.

**Comment by ayatkevich** [comment]
@RyanCavanaugh ah, I see.

What about the capability to go to definition? In remapped type you can go to reference from any reference or definition point. But you can't go to definition from a reference.
Contrary, in a mapped type without remapping, you can go back and forth between definition and reference, in both directions.

**Comment by RyanCavanaugh** [comment]
It definitely "should" work, but it's a bit tricky to implement AFAIR

**Comment by sfedorov-at-wiley** [comment]
Still does not work
But it definitely will be nice to make a hint for IDE, that mapped key refers to corresponding key in given object
<img width="679" alt="Screenshot 2022-04-03 at 01 05 47" src="https://user-images.githubusercontent.com/83008702/161402873-9f486911-040a-410d-9159-0f98dc15718f.png">

**Comment by thomasballinger** [comment]
I encountered a case where this nearly works, which makes me wonder if there's a worthwhile partial fix.

When I use key remapping on a record of functions, the functions can be found once I add parens. "Go to type definition" in VSCode works with and without parens.

[playground link](https://www.typescriptlang.org/play?ssl=8&ssc=31&pln=1&pc=1#code/MYewdgzgLgBAZgVzMCMC8MDe8QgFwwAUAlOgHxYC+ANDAEYCGATgSeVTJQFBeiSzB0HBqmwBtANIwAlmBgBrAKYBPEHBhRlAB0Vr4SFDBEwJAXQKadexMgiTTnXgDo4uGAHp3MACYhFEMAByWABhAFtvAFoQgBtpYHlnVxA2TxhwqNj4+RgAdxAmeVQ4WUUePmgfIUxKI1EYSRk5JVV1S111GxRzDW0O-Vt7R28XNzSM6LiE1HzC4tKgA)

```javascript
const funcs = { foo: () => {}, bar: () => {} }

const c = {} as { [K in keyof typeof funcs as K]: typeof funcs[K] }
c.foo   // doesn't cmd-click (known, that's this issue #47813) but "go to type definition" works (VSCode)
c.foo() // cmd-click works fine!
```
