### ISSUE TITLE
Class constructor with Partial<Record<Enum, ...>> param accepts bad values for general enum keys

### ISSUE THREAD

**Issue by osdiab** [microsoft/TypeScript#47826]
# Bug Report

### 🔎 Search Terms

class constructor default initializer enum partial record

### 🕗 Version & Regression Information

Seems to be the same behavior all the way back to 3.3.3 on typescript playground.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bugs that aren't bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/KYOwrgtgBAwmBO9QGMCeMD2ATYUDeAUFFAKoDOWUAvFAOQkDKAIrQDRFQCiC1UARJxIAlPgQC+BAsgA2AQzJkoAFWBkALvg7FkGEOvhhkajPAAUAB1nxZEAFxQAClbUBLWdIA8Q4DvhYPcIgo6NjArFDgEABGwPAAfHEAlJrEqakA9OlQZAAWGGDSlDFQshGQMfBQObHAWlASElK66lAA1sCovIFIIGiYOAB05JTysAg9faFNehpqqmoAQrKUNCDAAO7K86Z4ANrtqAC69nxYLmSyUdLAWHxiyZlQajnnUFgYqhEYagCE0y1zdQAcQw2F4a02KnUO123WC-WAQwox34ZwuVxudweWWerwAZrIXNJFKNgAAPcw+OZYIA)

### 💻 Code

```ts
enum CurrencyCode {
  Usd = 'USD',
  Eur = "EUR"
}

class Test {
    constructor(param: Partial<Record<CurrencyCode, number>>) {
        // should be a number here
    }
}

const key = CurrencyCode.Usd as CurrencyCode
const testBad = new Test({[key]: "disabled"}) // this does not fail!
const testGood = new Test({[CurrencyCode.Usd]: "disabled"}) // this fails as expected
```

### 🙁 Actual behavior

The value in the parameter above is an incorrect value, but it gets accepted by TypeScript if the key is referred to as a general enum value, not a specific one.

### 🙂 Expected behavior

Both cases cause a compile error.

**Comment by RyanCavanaugh** [comment]
This is effectively the same problem as described in https://github.com/microsoft/TypeScript/issues/47703#issuecomment-1028171262 - the expression `{[key]: "disabled"}` has type `{ [key: string]: string }`, which we effectively treat as `{ }` for the purposes of being an assignment source, and `{ }` is a valid `Partial<Record<CurrencyCode, number>>`. There's not really an obvious fix here apart from just annotating `key` differently (`as const` vs `as CurrencyCode`)

**Comment by osdiab** [comment]
Yeah, the actual production issue I had was not that there was such an annotation, but that that "currency code" came from a mapping:

```
const key: CurrencyCode = countryCodeToCurrencyCode[countryCode]
```

so this was a pretty tricky footgun. I'll comment on the other issue my thoughts on that.
