### ISSUE TITLE
Question: How do I build/run the TS compiler?

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/TypeScript#4783]
So this seems pretty basic, but I've been struggling with it for a few hours and I was hoping you guys could help point me in the right direction.

I'm trying to get the TS compiler building and running from within Visual Studio. I'm brand new to the TypeScript world and my only experience with JS has been basic front end web dev, so I'm probably misunderstanding a few things here.

What I've tried:

1. Clone the TS Repo
2. Run all of the `jake` commands in the README to ensure everything is fine. (I can build/run tests fine)
3. Installed the various [build tools](https://github.com/Microsoft/TypeScript/wiki/Integrating-with-Build-Tools) (I doubt I needed them all but I wanted to be sure)

This is where I've started to run into issues. I'm not even 100% sure how to open a Typescript project. I've tried:
 * Opening an individual file, which loads all the sibling files found in the `tsconfig.json` file. However, I'm faced with ~3000 various errors. (A lot are complaining about `hasProperty` not being defined)

* Creating a NodeJS project from existing code and pointing it at the root `Typescript` folder. This loads all of the various `.ts` files and folders, but I'm still looking at thousands of build errors. (I'm not even sure if TS even **is** a NodeJS project, but there aren't many options when creating a new TS project in Visual Studio).

I see there's a wiki page on [Dev Mode in VS](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio) but it seems to assume you can build and run the project.

Is there any other material that would help me get off the ground and figure out what I'm doing wrong?

**Comment by mhegazy** [comment]
looks like you are trying to open latest TS sources on an older version of the TS language service.

the TS repo is biilt using the `jake` build command, and there is not a `.proj` file for it that you can build in VS.

To build the TS repo:

> jake local

To run tests:

> jake runtests

To update to latest Language Service, either install [TS1.6-beta](http://blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx) or enable [devMode](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio). 

Personally, i have a folder `c:\ls` that has the latest copy of the language service i want to run, and i enable DevMode to point to it. i can then update it whenever i need to.

> jake local
> copy built\local\typescriptservices.js c:\ls
> copy built\local\lib.*.d.ts c:\ls
> powershell
> scripts\VSDevMode.ps1 -enableDevMode -tsScript c:\ls 14

Please let us know if you are still running into issues.

**Comment by mhegazy** [comment]
also looks like our documentation need some work.

**Comment by JoshVarty** [comment]
Thanks, I'll try installing the 1.6 beta.

So if I use `jake` to run tests and follow the steps in [Dev Mode in VS](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio) will I also be able to place breakpoints, use edit and continue etc.?

**Comment by mhegazy** [comment]
breakpoints, yes. just open your .ts files (e.g. src\compiler\tsc.ts), and place your breakpoints, run the compiler with `cscript /x tsc.js` and you should be good to go.

to get `edit and continue` i.e. compile-on-save to work; what i do is i start `tsc --w --p src\compiler` and that gives me the same effect as compile on save in VS.

**Comment by basarat** [comment]
Shameless (but genuinely helpful) plug: you might have an easier time looking at https://github.com/TypeStrong/ntypescript :rose: 

Feel free to fork it *to create your own flavor of build*.
