### ISSUE TITLE
adding new keywords

### ISSUE THREAD

**Issue by Shahzodbek2001** [microsoft/TypeScript#47831]
# Adding new keywords

## 🔍 Search Terms

if in javascript
if elem in arr javascript
if in typescript

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

add new keywords:
	and (in javascript = &&)
	or (in javascript = ||)
	not (in javascript = !)
and new feature for usage if statement:
	if (elem in arr) {}
	or
	if (elem in object) {}

## 📃 Motivating Example

1) allows you to better understand and develop code
2) makes work easier, for example, it looks like this now when writing code in ts / js:
```js
if (arr.includes("myword"))
if (object.hasOwnProperty("mykey"))
if (true || false)
if (true && false)
if (!true && false)
```
and this is how it will look after adding new syntactic sugar:
```js
if ("myword" in arr)
if ("mykey" in object)
if (true or false)
if (true and false)
if (not true and false)
```
## 💻 Use Cases

```js
if ("myword" in arr)
if ("mykey" in object)
if (true or false)
if (true and false)
if (not true and false)
```

**Comment by RyanCavanaugh** [comment]
This isn't within the scope of TypeScript, as noted by the viability checklist.

**Comment by Shahzodbek2001** [comment]
if you say so, then the typescript itself arose from such ideas

**Comment by Shahzodbek2001** [comment]
then why am I writing this already exists and has successfully justified itself in the python programming language

**Comment by Shahzodbek2001** [comment]
when they developed topscript they also added some things from other programming languages, for example:
interfaces,
enum,
types,
.....

**Comment by Shahzodbek2001** [comment]
> This isn't within the scope of TypeScript, as noted by the viability checklist.

read what I wrote and tell me why this feature cannot be in typescript

**Comment by RyanCavanaugh** [comment]
Please see the checklist:

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, **new syntax sugar for JS**, etc.)

There is a difference between runtime sugar and type syntax. We do not add new runtime syntax to JS at this time.
