### ISSUE TITLE
The performance of ReadonlyArray in union is different from others

### ISSUE THREAD

**Issue by heretic-G** [microsoft/TypeScript#47842]
# Bug Report

### 🕗 Version & Regression Information

- 4.5.4
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAdgrgWygXigRihAHsCMAmAzrIgEYQBOUA-FMBXNAFxQBmAhgDaEQBQA9PygUIhOJ2BQAlsXqNeC0JBIIAqjCkB7GCnRQAPivIUBQkWInTi8BMYW8l0Ee3wB5GJxABBClVQ3jAG0AXUwcPCIoACUIF21PHwp2EAAeAMoAPho6BmY2Lh5TYVFxSRkc+UVwJ1i3D29fdS0dfzJKEINo2viGpNT0igyi81KrI3bQw2d8HvGKDqhFqAB3AAsQKHwpVlZKPElqaiA)

### 💻 Code

```ts
type num = 1 extends number ? true : false
// result is true

type numUnion = 1 | number
// result is number

type readOnlyArr = number[] extends ReadonlyArray<number> ? true : false
// result is true

type readOnlyArrUnion = number[] | ReadonlyArray<number>
// result is number[] | readonly number[]     why different ??
```

### 🙁 Actual behavior
![image](https://user-images.githubusercontent.com/13850591/153529135-53f0ef42-a23c-4593-a477-0747c945220f.png)
![image](https://user-images.githubusercontent.com/13850591/153529157-4373dfd2-a8ff-4f80-8c86-dd5426e67ad9.png)

why different in second ? 

### 🙂 Expected behavior
only show `ReadonlyArray<number>`

**Comment by RyanCavanaugh** [comment]
Unions reduce base on the stricter subtype relation, whereas conditional types are evaluated based on the assignability relation.

**Comment by fatcerberus** [comment]
I think the question was rather about why `number[] | readonly number[]` isn't subject to subtype reduction while `1 | number` is.  The answer is that it *is*, but isn't done eagerly:

```ts
declare const foo: { a: number } | { a: number, b: string };
declare const bar: number[] | readonly number[];

const x = foo ? foo : foo;
//    ^? const x: { a: number }
const y = bar ? bar : bar;
//    ^? const y: readonly number[]
```
