### ISSUE TITLE
Add support for specifing super type of type parameters

### ISSUE THREAD

**Issue by Nokel81** [microsoft/TypeScript#47841]
# Suggestion

Currently it is possible to write type parameters that specify subtypes. This is very common and is done with the `extends` keyword. 

For example:

```ts
function foobar<T extends MyInterface>(args: T): number { ... }
```

However, it is not very easy to specify a super type for type parameters. You can do something similar with conditional types but it is finicky and doesn't compose well.

```ts
function foobar<T>(args: MyInterface extends T ? T : never): number { ... }
```

Now, in most cases this is not very useful. However, it is useful to qualify the outer limits of what is allowed. For instance, there is the `JsonValue` type from the `type-fest` (https://github.com/sindresorhus/type-fest/blob/main/source/basic.d.ts).

Now, it is not very good practice to have `JsonValue` be the subtype for some function or class because TS then requires the index field.

However, if you are writing some library that only supports JSON serialization it would be very useful to be able to specify that at the type level. This becomes very useful when working with generic classes.

## 🔍 Search Terms

- satisfies
- type
- super
- generic
- parameter

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a new declaration `T satisfies ConcreteType` where a type error would be emitted if `ConcreteType` is not a super type of `T`.

## 📃 Motivating Example

Writing a class that is a generic interface over some type which must be no broader that some other type.

## 💻 Use Cases

For some small cases, using `ConcreteType extends T ? T : never` is possible, but can get very finicky quickly and doesn't always work.

**Comment by fatcerberus** [comment]
> Add a new declaration `T satisfies ConcreteType` where a type error would be emitted if `ConcreteType` is not a super type of `T`.

`T extends ConcreteType` already means this, though ("ConcreteType is a supertype of T" = "T is a subtype of ConcreteType").  Are you actually looking for #14520?

**Comment by Nokel81** [comment]
> T extends ConcreteType already means this, though ("ConcreteType is a supertype of T" = "T is a subtype of ConcreteType")

The error when you specify a type outside that range is the interesting part.

But I think you have your supertype/subtype side backwards. A supertype is bigger than a subtype. So `T extends ConcreteType` means that `T` is "bigger" than `ConcreteType` and thus `ConcreteType` is a subtype of `T` and `T` is a supertyp of `ConcreteType`.

But yes, that is what I was looking for.

**Comment by fatcerberus** [comment]
> `T extends ConcreteType` means that `T` is "bigger" than `ConcreteType` and thus `ConcreteType` is a subtype of `T` and `T` is a supertype of `ConcreteType`

No, that's not what `extends` means.  `extends` means specifically "is assignable to", or in other words "is a subtype of".  If I have `function foo<T extends number>()` then `T` can e.g. `1 | 2 | 3` (a subtype of `number`) but *can't be*, say, `string | number`.

The relationship you describe is the hypothetical `T super ConcreteType`, which doesn't exist right now.
