### ISSUE TITLE
TypeScript module "NodeNext" does not resolve `index.d.ts` from CJS modules

### ISSUE THREAD

**Issue by AndrewLeedham** [microsoft/TypeScript#47848]
# Bug Report

### 🔎 Search Terms

NodeNext, esm, CJS, cli-spinners

### 🕗 Version & Regression Information

- This only occurs in nightly builds.
- I was unable to test this on prior versions because `nodenext` is only supported in the nightly versions.

### ⏯ Playground Link

From what I can tell you can't install npm modules in the playground, so I made a repro on StackBlitz: https://stackblitz.com/edit/node-opvt9e?file=index.ts run `npm run typecheck` in the console to see the issue.

### 💻 Code

```ts
import spinners from 'cli-spinners';

console.log(spinners);
```

### 🙁 Actual behavior
TypeScript cannot find the typings for `cli-spinners` which is a CJS module. It does not use a `main` or `exports` or `types` field in the `package.json`, it just includes a `index.js` and `index.d.ts` file.
```
index.ts:1:22 - error TS2307: Cannot find module 'cli-spinners' or its corresponding type declarations.

1 import spinners from 'cli-spinners';
                       ~~~~~~~~~~~~~~


Found 1 error in index.ts:1
```

### 🙂 Expected behavior

New `NodeNext` module behaviour to import CJS as it used to. E.g looking at `index.d.ts` if there is no `main` field. https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules

### 👪 Related
- https://github.com/sindresorhus/cli-spinners/issues/61
- https://github.com/microsoft/TypeScript/issues/46452

**Comment by weswigham** [comment]
Huh, I didn't realize we were relying on the directory lookup behavior to fallback to find the main `index.js` if it wasn't explicitly listed. Shouldn't be too hard to fix.

**Comment by weswigham** [comment]
Hm, it's a _little bit_ more complicated than that - looks like `node` doesn't assume a `index.js` `main` for packages found via relative imports, but _does_ for those found via nonrelative imports. (Even if both look at the same package file!) That's... a headache.

**Comment by weswigham** [comment]
I've opened both #47854 with a fix for this to match node's current behavior, and https://github.com/nodejs/node/issues/41940 to get some kind of discussion about node surprising esm resolver behavior when importing packages via relative paths.

**Comment by wight554** [comment]
Hi, don't know if I should open new issue, so decided to report here
I've tried to switch my project to TS 4.7 with new module: nodenext and some libraries I use fail to find type declarations, here's the list:
https://github.com/facebookexperimental/Recoil
https://github.com/preactjs/preact (+ preact/hooks)
https://github.com/developit/htm
Currently I was able to shim those by declaring local module and  importing type declarations from node_modules, like this
```
declare module "preact" {
  export * from 'node_modules/preact/src/index.js'
}
```
I'd like to open issues in corresponding libraries, to fix it properly
Is there any doc/issue I can use for reference, so It'd be easier to fix those by library maintainers?
