### ISSUE TITLE
TypeScript 4.6 sometimes treats tuple union types as "never" when switch-case has a "default" clause

### ISSUE THREAD

**Issue by ide** [microsoft/TypeScript#47857]
# Bug Report

The error described below started with TypeScript 4.6.1-rc. A minimal repro is included.

### 🔎 Search Terms

- Destructuring
- Union types

### 🕗 Version & Regression Information

- This changed between versions 4.5.5 and 4.6.1-rc

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/KYDwDg9gTgLgBDAnmYcCi4rAM7YJYQB2cAvHAEIQQA2wAhoQDIQDmeAxhmFrgcQD5wA5DCgBXYELiChAMzrVskgNwAoUJFgJkqSjXpNWHLj3xFScANpCGAEyEAaOADpXJnGcKWAut+lWhQggYR3RMDz5vNXVwaHhZMUJ2GD44YAA3BTE6GGAACg1TPgAuMO4IogBKUoAjKloGOABvVTg4PFk4PIBBKCg6RGc8bF7+xALw3irK5ta2uHYibHhLCBR+mGgnV2c14H7CW2w-MkKKwjV5uGwAdzwYdgALLr2N6BmWq7b2OiVhOyEpU+XzaWBgYigxFedmwzgy+3GeSeeGothmJAAfGlMtRsrkkY8UWjKpcvgBfOZXH5-QLBQGzEGg4DgyFwACEGSyOXy0MO2EsAAZvCTKfMKSDbMB5GJqDAgaKrjBHlAIDc4IRgGq0H1oHkAAYAEia0M2UDJ7Ww6uCcDo1zEYE0uVscBN0D1IpB4rFc3NwEUqGBTJZxDOU2IJAjwlEEiEpIpZKAA)

### 💻 Code

See this toy NAND evaluator. Something about the recursive union type causes TS to fail when destructuring the array. Deleting the `default` clause causes the error to go away. (The `default` clause is unnecessary if assuming TS is sound but one can see why a safety net is helpful.)

```ts
export type Expression = BooleanLogicExpression | 'true' | 'false';
export type BooleanLogicExpression = ['and', ...Expression[]] | ['not', Expression];

export function evaluate(expression: Expression): boolean {
  if (Array.isArray(expression)) {
    const [operator, ...operands] = expression;
    switch (operator) {
      case 'and': {
        return operands.every((child) => evaluate(child));
      }
      case 'not': {
        return !evaluate(operands[0]);
      }
      default: {
        throw new Error(`${operator} is not a supported operator`);
      }
    }
  } else {
    return expression === 'true';
  }
}
```

### 🙁 Actual behavior

The line `const [operator, ...operands] = expression;` produces the error: `TS2488: Type 'never' must have a '[Symbol.iterator]()' method that returns an iterator.`

### 🙂 Expected behavior

Expected there not to be an TS error.

**Comment by gabritto** [comment]
Bisected to https://github.com/microsoft/TypeScript/commit/56f81075f9802c85365ab24046e7eb947cd7800a

**Comment by gabritto** [comment]
After some more digging, the error arises in new code added by https://github.com/microsoft/TypeScript/pull/46266.
