### ISSUE TITLE
Conditional operator nullchecking does not work as intended in nested objects

### ISSUE THREAD

**Issue by VividLemon** [microsoft/TypeScript#47851]
# Bug Report

### 🔎 Search Terms

Conditional operator, ternary operator, issues 
### 🕗 Version & Regression Information

- I was unable to test this on prior versions because, I feel like it exists on other versions and am unsure how to test other versions

### 💻 Code
(Using discord.js code, the idea is the same and I will reference types)

```ts
const value = (interaction.guild != null) ? (await keyv.get(interaction.guild.id) : undefined
```
Where interaction.guild is type Guild | undefined, and guild.id is string
In this code, it should be checking if interaction.guild is not null, and if it is not, get that value from keyv. Which should make the value inside keyv.get (interaction.guild.id) absolutely not null.

### 🙁 Actual behavior
the value inside keyv.get -- interaction.guild, since it was just null checked earlier in the code, should run as normal and say the type of interaction.guild is type Guild, however, it incorrectly states interaction.guild is still Guild | undefined. When it should not be because it was just checked that it was _not_ undefined. 

Since interaction.guild was checked to not be null, it should not say the type is possibly undefined.
### 🙂 Expected behavior
interaction.guild to be type of Guild with no possibility of undefined

It was checked to be not null, so it shouldn't have the possibility of being undefined.
To clarify I use != null to check if it is loosely either not null or not undefined
In addition, the reverse correctly checks, `(interaction.guild == null) ? undefined : (await keyv.get(interaction.guild.id)`. works completely fine. Also, doing the code in a long if statement, also works as intended. It is only when it is checking that it is not null, and using that value in the first condition, it errors out. Using the ! works too, but it shouldn't be erroring regardless.

**Comment by RyanCavanaugh** [comment]
My best guess at your types is this, which checks successfully:
```ts
declare const interaction: { guild?: { id: number } };
declare const keyv: { get(id: number ): void };
async function f() {
  const value = (interaction.guild != null) ? (await keyv.get(interaction.guild.id)) : undefined
}
```
Please post a self-contained example with a playground link; the template outlines the requirements for this.

**Comment by VividLemon** [comment]
Probably just a skill issue of mine
