### ISSUE TITLE
Function arguments inferring as `any`

### ISSUE THREAD

**Issue by renjithspace** [microsoft/TypeScript#47864]
# Bug Report

### 🔎 Search Terms
`function arguments` `inferring any`

### 🕗 Version & Regression Information
Tested version: `Version 4.5.5`

- I didn't test this on prior versions because I think this is not related to a version-specific behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABIgNnCBDKBTAFADwC5EwQBbAI2wCcAaRAT2NMpoEpEBvAKGQgQDOURBnyIAvCOoBzctjBQBAbQAMAXUQB6TSLEwBIsA3rZ8AB2zRsAExLkq1Xon5ghIhhKmyy8xUoCMGtruiPqGxoimFla2LA7cAL5AA)

### 💻 Code

```ts
function  locate(x: number, y: number) {
  const ax = arguments[0] // ax is any, expected number
  const ay = arguments[1] // ay is any, expected number
}
```

### 🙁 Actual behavior

Function `arguments` is `any[]` type.

### 🙂 Expected behavior

The typescript should infer the type of `arguments` from function implementation.

**Comment by MartinJohns** [comment]
Is there any good reason to use `arguments` in this way? That parameter predates the tuple functionality, and changing this would be breaking change.

**Comment by RyanCavanaugh** [comment]
This starts to get pretty weird with overloads and there's not really much usage of `arguments` compared to other things like rest args available today.
