### ISSUE TITLE
Conversion to ES Module should not change whole-module import to named imports

### ISSUE THREAD

**Issue by Josh-Cena** [microsoft/TypeScript#47869]
# Suggestion

## 🔍 Search Terms

- convert es module
- default and named import

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'm currently using the `File is a CommonJS module; it may be converted to an ES module.` diagnostic to refactor CJS modules to ESM. It has been pretty effective, except that TS wants to transform default imports to named imports for me, which defeats the whole purpose of me sticking to default imports in the first place.

## 📃 Motivating Example

Given this code:

```js
const path = require('path');

const newPath = path.resolve('foo', 'bar');
```

TS transforms it to:

```js
import { resolve } from 'path';

const newPath = resolve('foo', 'bar');
```

However, I expect it to be:

```js
import path from 'path';

const newPath = path.resolve('foo', 'bar');
```

## 💻 Use Cases

I think there are several problems with this approach.

1. In Node ESM, named import has less support than default import. While default imports always work, named imports have the possibility of triggering `SyntaxError: Named export 'xxx' not found. The requested module 'xxx' is a CommonJS module, which may not support all module.exports as named exports.` This causes extra debugging efforts.
2. I believe, overall, named imports are less readable than default import, especially in the case of `path`. `resolve(x, y)` would take me more time to understand than `path.resolve` because `resolve` is such a vague word on its own.
3. The named import introduces extra identifiers to the scope. In case of a naming clash (for example, when I have declared another `resolve` in the module), TS goes to great lengths and writes it as `import { resolve as _resolve } from 'path';`, which is totally unnecessary since name clashes don't exist in the first place!

I suggest that TS respect the fact that I wrote a whole-module import and transform `const foo = require('foo');` to `import foo from 'foo';`. If I wrote a destructure like `const { bar } = require('foo');`, then transforming it to a named import is justified.

**Comment by RyanCavanaugh** [comment]
If you have a CJS module that you're importing and *can* convert its usage to an ES module, the odds are much better that the imported module (under an ES interpretation) has the shape
```
export function resolve() { ...
```
than
```
export default {
  resolve() { ... }
}
````

**Comment by Josh-Cena** [comment]
If I'm progressively converting a codebase to ESM, I'll be first converting the downstream _caller_ than the upstream _provider_, because CJS can't import ESM, but ESM can import CJS. Chances that I have a CJS module `require`ing an ESM module are extremely low, because that means at some point my codebase is not working, which is not something you want during a refactor.

I think the biggest disagreement is whether the upstream package I'm `require`ing is CJS or ESM. I certainly believe it's CJS in most cases. Considering the possibility of dual-package, I wonder if it's possible for TS to do some basic detection of the upstream package's module system? Maybe with the same logic as the `NodeNext` module system?
