### ISSUE TITLE
Simplify longer tuple definitions

### ISSUE THREAD

**Issue by Patersooon** [microsoft/TypeScript#47874]
# Suggestion

## 🔍 Search Terms

Simplify longer tuple definitions.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

type ArrayWithLengthFive = [string, string, string, number, number];
Simplify
type ArrayWithLengthFive = [string * 3, number * 2];
## 💻 Use Cases

type ArrayWithLengthFive = [string, string, string, number, number];
Simplify
type ArrayWithLengthFive = [string * 3, number * 2];

I haven't assessed feasibility, but I'd like to mention it anyway😁.

**Comment by IllusionMH** [comment]
What if instead of trying shorter cryptic type that starts with 3 strings and ends with 2 numbers (no idea what API can be described this way, instead of an object), it was tuple with labeled elements so any user will know correct order of some strings and some numbers, not only type and count?

**Comment by jcalz** [comment]
It's weird that the only use case listed for this is the same as the motivating example.  Is there some actual real-world situation where tuples like this are being used that are so long as to be hard to use?  I'd expect a motivating example to be like `[string * 17, number * 7]` or something, and a use case to be... like, some description of where such a monstrosity would actually be used.  

Aaanyway, given that #26223 is closed as fixed you can do something like this yourself without too much trouble and without extra syntax:

```ts
type ArrayWithLengthFive = [...TupLen<3, string>, ...TupLen<2, number>];
// type ArrayWithLengthFive = [string, string, string, number, number]

type LenTwentyFour = [...TupLen<17, string>, ...TupLen<7, number>];
// type type LenTwentyFour = [string, string, string, string, string, string, string, 
//    string, string, string, string, string, string, string, 
//    string, string, string, number, number, number, number, number, number, number];
```
<details><summary>🛠⚙</summary>

```ts
type TupLen<N extends number, T = any, A extends T[] = []> =
	N extends A['length'] ? A : TupLen<N, T, [T, ...A]>;
```

</details>

[Playground link](https://www.typescriptlang.org/play?ts=4.5.4&ssl=10&ssc=87&pln=4&pc=1#code/C4TwDgpgBAKgrmAMhAdgHgHJQgD2KgEwGcoU4BbAIwgCcAaWKAXigEMUQGBBbPQkmAG0AusygiAfMwCwAKACQWXPhTEoXQQHIANqgDmwABabRAfnVQAXLATJ0GBjAaCnUAHQeuwiQG45c0Eh1GhpWEAB1AEsjOwNDADFIgDdoFkEPN3gkVDQAZgYiYBpIlD0JBgysuzQAJgYyKloJYT9ZAHo2qEDoLhCwqJj9I0SUsUFC4tKCopK9acm50gpqeiXGmmF-WW6oOxgAd1RQeIB7OBoxytscgEYAdnnZ8vcPKpyHtZXm1o6u8GgdntDihjmcLmkJrNHlMoJCYXDFgjoYiZjC5L8oJikbDUSiFsiCTj8USoVB0Z1MST4bjCQ0VvVlrQGetmfTPkz2as6bQWkA)

**Comment by RyanCavanaugh** [comment]
This doesn't come up often enough that we would "spend" syntax/complexity on it.

**Comment by RyanCavanaugh** [comment]
Alternative you can use btw
```ts
interface TupleOfLength<T> {
  0: [];
  1: [T];
  2: [T, T];
  3: [T, T, T];
  // Keep going as far as you have to (????)
}

// S = [string, string, string]
type S = TupleOfLength<string>[3]
```
I would recommend this over clever conditional type tricks because it's more performant and there's no reason you can't list out the longest tuple you'd realistically have
