### ISSUE TITLE
(Bug Report): GoToDefinition won't work if CommonJS module contains import statement on the top of a js file

### ISSUE THREAD

**Issue by rhzone** [microsoft/TypeScript#47872]
# Bug Report

### 🕗 Version & Regression Information

- TypeScript Version: `typescript@next`
- VSCode Version: `1.64.1`，[relevant issue](https://github.com/microsoft/vscode/issues/136203)
- This is the behavior in every version I tried

### ⏯ Playground Link

[Go to definition with relevant code](https://stackblitz.com/edit/node-c5r7ft?file=index.js)

### 💻 Code

```js
// index.js
const { foo } = require('./foo')
```

```js
// foo.js
import fs from 'fs' // try to toggle comment in this line

function foo() {

}

module.exports = {
  foo,
}
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/30968676/153783064-3ccfefe6-b43a-4c0c-8017-b91538754d27.png)

### 🙂 Expected behavior

Go to definition could find the definition of `foo`

**Comment by RyanCavanaugh** [comment]
Pretty sure this is an easy fix in the JS logic, though it might have downstream consequences: We assume a file is either uniformly CommonJS (using `module.exports` assignments) or ES (using top-level `import`/`export`); when a file has at least one import/export statement then the CJS detection code doesn't run at all. We should probably just run the CJS detection code unconditionally.

**Comment by a-tarasyuk** [comment]
TypeScript skips binding if the file has an `externalModuleIndicator`. So `module.exports = { foo }` doesn't have foo property

https://github.com/microsoft/TypeScript/blob/c3a055203306682ee0b4c5cba1fa508128ca6c03/src/compiler/binder.ts#L2880-L2887

https://github.com/microsoft/TypeScript/blob/c3a055203306682ee0b4c5cba1fa508128ca6c03/src/compiler/binder.ts#L2834-L2842

I've created draft PR which allows it. @RyanCavanaugh Could you take a look at it?

**Comment by sandersn** [comment]
The team discussed this and thought that while it could theoretically be possible to have completely mixed commonjs/ESM syntax modules, it's a pretty big change that would likely need some additional limits designed in. Before we do that, we'd like more information about the scenario.

@rhzone How you are using foo.js? Are you running it through a bundler? What runtime? Do you expect that this will be a common scenario?
