### ISSUE TITLE
extends condition fails on conditional type

### ISSUE THREAD

**Issue by patrickjcurran** [microsoft/TypeScript#47892]
# Bug Report

### 🔎 Search Terms
conditional infer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "This conditional type returns never when it should return the true branch" <- I'm pretty sure this is different from that since I'm not using `never`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4&ssl=3&ssc=19&pln=3&pc=25#code/C4TwDgpgBAYg9nAPAIQIYCcB8UC8U3pQQAewEAdgCYDOU1w6AluQOZQD8UDArtAFxQAZqgA21CAG4AsAChQkKABUI9RAA1seNUVIUasBImaCIhAtk49+Q0eOkyAxnHL0oxActXwk9Jq0yaXOi89kA)

### 💻 Code

```ts
type Foo<Bar> = Bar extends string ? true : false;
type Test<X> = X extends Foo<infer Bar> ? true : false;
const x: Test<Foo<string>> = true;
```

### 🙁 Actual behavior

Fails to compile because `Test<Foo<string>>` becomes `false` after the conditional.

### 🙂 Expected behavior

Doing a substitution:
`Foo<string> extends Foo<infer Bar> ? ... : ...`
I'd expect that to go down the true branch of the conditional and infer `Bar` as `string`.

Note that `const x: Test<Foo<number>> = true;` compile fine. `Foo<Bar>` is conditional on `Bar` being a `string`. And that's the only type where the `extends Foo` doesn't seem to work.

**Comment by RyanCavanaugh** [comment]
`infer` performs a structural inference process, not a reasoning-backwards process. There are no occurrences of `Bar` to infer from in `Foo<Bar>`, so `Foo<infer T>` is going to give you `T = unknown` pretty much always.

**Comment by patrickjcurran** [comment]
Thanks for the response. I played around with some more examples and it makes better sense.

What I still don't get is why it goes down the false branch of the conditional. `T = unknown` makes sense.

This [code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAYg9nAPAIQIYCcB8UC8U3pQQAewEAdgCYDOU1w6AluQOZQD8UDArtAFxQAZqgA21CAG4AsACgAxnHL0oxAfCTluAWwBGELEVIUasBImaD9UACrZO1qAPIQAblbwByYlEa1u5AGtyOAB3cg9peUVlEDUzeiZWbBIyKlp1c3JLQlsOG0coZzdCTxAfWiL9CKA)
```typescript
type Foo<Bar> = Bar extends string ? true : false;
const x: Foo<number> extends Foo<infer T> ? T : never = 'x is unknown';
const y: Foo<string> extends Foo<infer T> ? T : never = 'y is never';
```
seems odd to me. The first one has `x`'s type being `unknown` which makes sense per your comment. But I'd expect `y`s type to also be `unknown`.

**Comment by RyanCavanaugh** [comment]
This perhaps is illuminating. There is a small amount of "reasoning backwards" that can appear to occur:
```ts
type Foo<Bar> = Bar extends string ? true : false;
type GetBarOfFoo<T> = T extends Foo<infer B> ? B : "does not";

// Original forms
type M1 = GetBarOfFoo<Foo<number>>; // M1 -> unknown
type M2 = GetBarOfFoo<Foo<string>>; // M2 -> "does not"

// Evaluated forms
type M3 = GetBarOfFoo<false>; // M3 -> unknown
type M4 = GetBarOfFoo<true>; // M4 -> "does not"

// Inlined forms
type M3_0 = false extends Foo<infer U> ? U : "does not"; // unknown
type M3_1 = false extends (infer U extends string ? true : false) ? U : "does not"; // unknown

type M4_0 = true extends Foo<infer U> ? U : "does not"; // "does not"
type M4_1 = true extends (infer U extends string ? true : false) ? U : "does not"; // "does not"
```
Conditional types are in general assumed to be *linear*, meaning that they relate their inputs to their outputs in consistently covariant or contravariant ways (any conditional type that doesn't do this is basically assured to be unsound in the presence of actual values). If given some type variable `T` we ended up in the truthy branch, then we can be sure that the tested type met the test and thus can be given some type, but in this case there are no candidates from which to find that type, so we fall back to `unknown` (again, this is sound). But given a type variable that ends up the falsy branch, we don't have a definitive proof of anything, so we can't soundly assume anything.

By analogy - if someone says you do have a rabbit, then you can be sure it's an animal. But if someone says you don't have a rabbit, then you can't make any determinations about it being an animal. So the truthy and falsy arms of conditional types are necessarily different in behavior.

**Comment by patrickjcurran** [comment]
Thanks for the detailed reply. It _was_ illuminating enough to solve my (actual) problem :-).

So it's fine if you don't want to spend more time on this, but your paragraph is still confusing to me: In the code example (`M3_1`) is the falsy branch and _that's_ when it infers `unknown`. (and that makes sense to me), but your paragraph suggests it's the _truthy_ branch that would be able to infer `unknown`.

Anyway, thanks again for the reply, I do appreciate it.
