### ISSUE TITLE
Return type of partially applied bound generic function

### ISSUE THREAD

**Issue by thscott** [microsoft/TypeScript#47899]
# Bug Report

### 🔎 Search Terms

partial application generic bind return type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bind, generics, partial application

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220211#code/GYVwdgxgLglg9mABAQwDwBVEFMAeUtgAmAzogIIBOFyAnqsmDQHxMAUDl1NAXIugJS9MAbwBQiCYgpYoICkg5VaAblEBfUaIA2MxACNEAXhQA6PTCKtwhLMAtZCAGkQBtAIwBdfssQB6X-qIABbIpFA0AA5YiKz8RkwojC4e2roQRjFxhgnIrO5ePpJFkv6I6SFhkdGx8YhgIAC2elgUyZqipQBiclBBLYjEMA0RWjB2DpqgkLAIiDA2YLDhGFVsyBQA5kJVgnxViGIS0rLyKJuqGqlQiIQZ8wRLNGYWhFZEtvZOiABE+MRQ328fgCtwqiHCUUytXAAGswHAAO5gK7YDI1bJzBaPVi-LD-QGFYpFUrRMEQ6pZBL-CgWDZAA)

### 💻 Code

```ts
function a<T extends Array<any>>(anArray: T): T {
    return anArray;
}

let b = a.bind(undefined, [1]); // b has type () => any[]
let c = () => a([1]);           // c has type () => number[]


// Further simplified

function identity<Type>(arg: Type): Type {
  return arg;
}

let d = identity.bind(undefined, "test"); // d has type () => unknown
let e = () => identity("test");           // e has type () => string
```

### 🙁 Actual behavior

The types of b and c are different, and the types of d and e are different.

### 🙂 Expected behavior

I'd expect them to both have the same type (b that of c, ```() => number[])```, d that of e ```() => string```), as the expressions are doing the same thing (arrow function vs bind for partial application of a function).

This limitation is noted in a [comment](https://github.com/microsoft/TypeScript/pull/27028#issuecomment-429334450) to the "Strict bind, call, and apply methods on functions" PR, but I couldn't find an actual issue referencing this behaviour.
That comment is also mentioned as a known limitation in a [similar issue](https://github.com/microsoft/TypeScript/issues/28900#issuecomment-445305567) which was closed in #28920, but unfortunately that pr only fixes the issue when binding only this, and not other parameters.

**Comment by RyanCavanaugh** [comment]
For the case where you exhaust all the arguments, there's really no reason to use `bind` over a function call.

For the case where you *don't* exhaust all the arguments, we don't have a type that can represent that - there's not a type annotation on `b` that you could write that would make it behave the same way as if its `bind` argument(s) were present at the subsequent call site.
```ts
function a<T extends Array<any>>(anArray: T, s: T): T {
    return anArray;
}

// b: ??
let b = a.bind(undefined, [1]); // b has type () => any[]
```

**Comment by natew** [comment]
This would be really nice to have
