### ISSUE TITLE
AMD code generator setting exports.prop1 = exports.prop2 = [...] void 0 blows stack

### ISSUE THREAD

**Issue by kevmeister68** [microsoft/TypeScript#47902]
We are upgrading from TypeScript to 3.1 to 4.4.

We have a source file that itself is an auto-generated file that relates to our data-model and hence it contains approximately 3,700 classes at present. Each class basically just contains a bunch of constant strings for various purposes.

Our compilerOptions object defines a target of es5 and a module of amd.

The compiled/transpiled code (JS output file) generates (amongst other things) one line of code that is 70,000 bytes long that basically reads like this:

exports.prop1 = exports.prop2 = exports.prop3 [....] = void 0;

Of course this continues for 3,700 properties.

As soon as we try load this code (just that line with a bit of scaffolding for testing), even via a base <script> element in our browser (Edge Chromium or Chrome), we get a range error, stack size exceeded.

If we split the code up into two lines, about 1850 initialisers per line, the code is parsed and runs successfully. 

Expected behaviour

The generated code should be able to be loaded, even with a large number of exports (classes) involved. 

The code generator should impose a limit on how many assignments it chains together before starting a new line of code.

For example, after every 500 properties a new line of code is generated to continue initialising the exports.

**Comment by nmain** [comment]
Seems like a V8 bug.

**Comment by RyanCavanaugh** [comment]
This is legal JS and doesn't have any intrinsic reason to crash. We could consider a workaround here but I'd prefer this be fixed in the runtime instead of us needing to implement some special behavior.
