### ISSUE TITLE
Type information lost when renaming object destructure variables in parameter

### ISSUE THREAD

**Issue by sarunluitel** [microsoft/TypeScript#47915]
# Bug Report
 function signature,
updateIndex: ({ getters : paramGetters, commit }, payload: number): void => {..
..
}

### 🙁 Actual behavior

getters here gets the correct type but paramGetters which should only be an alias has type any.

### 🙂 Expected behavior
paramGetters should automatically get the type of getters as it is only an alias in the function scope

I looked for a solution before posting here but could not find anything. am I missing something? if paramGetters gest the same value as getters, It should also get same type automatically. hope this is the default

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template for bug reports.

Your first argument (the destructured one) has no type annotation.

**Comment by sarunluitel** [comment]
Thank You for the reply @MartinJohns. This is working as expected. there was another variable named getters and the IDE was showing me type from the other variable and was confused.

The underlying framework was supposed to send the parameter with the types (it does send for the commit variable) but the getters is defined as any. It's not an issue with typescript. 

Thank again!
