### ISSUE TITLE
Having a .js file excludes a .jsx with the same name from the project 

### ISSUE THREAD

**Issue by MoyuScript** [microsoft/TypeScript#47914]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.63.2 (Universal)
- OS Version: MacOS 12.1 (21C52)

File structure:

![image](https://user-images.githubusercontent.com/45550579/147072048-777244ac-45f1-45a4-a06d-8843f530217a.png)

**jsconfig.json**

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "allowSyntheticDefaultImports": false,
    "baseUrl": "./",
    "paths": {
      "@util/*": ["src/util/*"],
    },
  },
  "exclude": ["node_modules"],
  "include": ["src"]
}
```

When `index.js` and `index.jsx` in same folder, path alias are not working at `index.jsx` but work at `index.js`.

![image](https://user-images.githubusercontent.com/45550579/147072229-6d8588ff-3816-44a0-8193-fdefdc8ca34d.png)

![image](https://user-images.githubusercontent.com/45550579/147072337-c6b338f7-78c7-45e6-be94-37ab9afd3a33.png)

**Comment by mjbvz** [comment]
Looks like when there are two files with the same name but different extensions (`.js` vs `.jsx`) the js file is always preferred. Relevant part of TSServer log:

```
Info 138  [17:09:46.260] 	FileName: /Users/matb/projects/san/vscode-alias-path-not-working-demo/src/util/index.js ProjectRootPath: /Users/matb/projects/san/vscode-alias-path-not-working-demo
Info 138  [17:09:46.260] 		Projects: /Users/matb/projects/san/vscode-alias-path-not-working-demo/jsconfig.json
Info 138  [17:09:46.260] 	FileName: /Users/matb/projects/san/vscode-alias-path-not-working-demo/src/index.jsx ProjectRootPath: /Users/matb/projects/san/vscode-alias-path-not-working-demo
Info 138  [17:09:46.260] 		Projects: /dev/null/inferredProject1*
```

**Comment by RyanCavanaugh** [comment]
When we see two files with the same extension during `includes` processing, we assume one is the built output of the other, thus we shouldn't include them both (lest we cause duplicate definition errors or cause confusing find-all-references results). You'll need to specify both files in the `files` array, at which point things work as requested:
```
   "files": ["src/index.js", "src/index.jsx"]
```
