### ISSUE TITLE
Literal types cannot be used in JSDoc `export default { }` syntax

### ISSUE THREAD

**Issue by nicojs** [microsoft/TypeScript#47946]
# Bug Report

There seems to be an issue with regards to literal types and JSDoc when using `export default {}`  syntax.

### 🔎 Search Terms

"jsdoc" and "export default"

Found this related issue: #45233, and [Ryan asked me to create a new issue](https://github.com/microsoft/TypeScript/issues/45233#issuecomment-1043663716)

### 🕗 Version & Regression Information

It seems to have been introduced in TS@4.5. I don't think TS 4.4 had support for typed `export default {}` with JSDoc.

- This changed between versions 4.4 and 4.5

### ⏯ Playground Link

Not possible I think (playground doesn't have plain "js" support?)

### 💻 Code

In a file "foo.js":

```js
// @ts-check
/**
 * @typedef Foo
 * @property {string} bar
 * @property {'qux'} baz
 */

/** @type {Foo} */
export default {
    bar: '42',
    baz: 'qux' // 👈 This is NOT ok
      // ^^^^^  Type 'string' is not assignable to type '"qux"'
}

/** @type {Foo} */
export const foo = {
    bar: '42',
    baz: 'qux' // 👈 This is OK
}
```

### 🙁 Actual behavior

> Type 'string' is not assignable to type '"qux"'

### 🙂 Expected behavior

> _no compile error_

**Comment by Jamesernator** [comment]
> Not possible I think (playground doesn't have plain "js" support?)

Actually it does, [here's a playground link of your issue](https://www.typescriptlang.org/play?filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUMAVNjpsJIBPAB2QBNkAzUAMQHsH9DxSAnB89k0Ab2iR2ASwB2AcwC+oAEYBDdiwgcuyHsX4ByAI4BXAB6bp8gF4tgGLLiJlk-Rg2nYLyfaQY9QVanN0AbSH58UBD5dgAuUE0AFgAmTQAaYNC5E0idA01QEFBAXg3ACR3QABVEYWhQMtAAOQB5ItAGTBDm7LAAPQ6OkKLbKMERCSzK0QZAuWhoYXFRORk-O0gGUBJyKIAiPX01zQxJSxxWFbs+BycXNw9A+AZRQVBqJlAAXiCWsPS4xOTZVPTNrJyBWKpXKlRqAGldkA).
