### ISSUE TITLE
TS represent is not correct

### ISSUE THREAD

**Issue by vyvc-comartek** [microsoft/TypeScript#47942]
# Bug Report

### 🔎 Search Terms

https://www.typescriptlang.org/docs/handbook/2/functions.html#call-signatures

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKoGdrIN4FgBQAkAK6ZQBycAthAFzLphSgDmA3AYXC3ciMVQBG0DkQAUAdwD2UACbp6jZiBYBKegDcpwWaIC+BBFJCNkpaAEZ6GLAF5kAeUEArCAjAA6OOnTAWIMU4YYhB3YGNkSRl5RSZWVRxOQigIMGIoEGRpOXRRQj0AGk48IhIyShp6AHIAWSgPABUATwAHCCqi0u5eACYAFk78glVRQ2N0KQAbCA9JqRYxcygLMSqAC2Aq1RGgA)

### 💻 Code

```ts
interface User {
	userName: string;
	age: number;
	(words: string): void;
}
const user1: User = Object.assign(
	function (words: string) {
		return words;
	},
	{
		userName: 'Mr.Type',
		age: 24,
	}
);

console.log(user1('hi'));
```

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

Throw an error: Type 'string' is not assignable to type 'void'

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

**Comment by jcalz** [comment]
Also https://www.typescriptlang.org/docs/handbook/2/functions.html#return-type-void

**Comment by MartinJohns** [comment]
And #46982. Used search terms: `object assign function in:title`

**Comment by fatcerberus** [comment]
#46982 doesn't apply (that one is about `Object.assign(obj, func)` incorrectly being callable), since the target object here *is* a function.  This issue is specifically a case of `(x: string) => string` being assignable to `(x: string) => void`, which is expected.
