### ISSUE TITLE
Re-export submodule

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#4795]
file1.ts
```
export function A() {}
export function B() {}
```

Currently, if I want to export `file1.ts` as a sub module, I have to do:
file2.ts
```
import * as subModule from "./file1.ts";

export var subModule = subModule;  // or,
export { subModule }
```

Is there an easier way such as:
```
export { * from subModule } from "./file1.ts"
```
Would it be ES6/ES7 compatible I didn't see any sample regarding this usage.

One question need to solve is how to handle any `default export` in the sub module.

**Comment by basarat** [comment]
Recommended

`export * from "./file1.ts"`

or an even older syntax (pre es6): 

`export import subModule = require('./file1.ts');`

**Comment by mhegazy** [comment]
there is an ES7 proposal for this: https://github.com/leebyron/ecmascript-more-export-from#proposed-additions

Once this reaches Stage 3, TypeScript will need to support it.

**Comment by mhegazy** [comment]
i have filed #4813 to track this work.
