### ISSUE TITLE
Magic Comments

### ISSUE THREAD

**Issue by last-Programmer** [microsoft/TypeScript#47955]
Pardon me for not using the existing form.

Feature Request:

if the typescript file contains

/* magic comments */
/* webpackChunkName: "VendorSmartWebComponentsCharts" */
/* magic comments */

It would be helpful if tsc compiler keeps this magic comments when removecomments in tsconfig.json is set to true.

**Comment by RyanCavanaugh** [comment]
The leading comment in a file will be preserved if it starts with `/*!`. Also if you're passing tsc's output to a downstream bundler, why not just have the downstream bundler remove the comments intead?

I'm legitimately curious why you ignored the template - why do you think we have it?

**Comment by Retsam** [comment]
A lot of the downvotes are probably from skipping the template - Typescript gets a *lot* of issues filed, and filling out the template helps the team manage them - it doesn't come across as very respectful of the team's time when you skip it.  

---

It's also not really clear what you're suggesting.  You're saying "TS should keep magic comments" - how is TS supposed to know what comments are "magic comments"?  That's the point of the `/*!` syntax, to mark what comments TS should preserve.  (Though I think it's more commonly used for comments that must be maintained for legal reasons - like Ryan said, if you're using a bundler, it probably makes more sense to let the bundler strip out the comments)

**Comment by somebody1234** [comment]
to put it another way - how would typescript know which comments are magic comments?

**Comment by last-Programmer** [comment]
With the current typescript comment syntax, only  `first line comment with  /*!`  is passed on to javascript. 
Its like who comes `first 🍏 ` find the way to javascript 🌍 and the `rest  🍎`stuck in typescript 🌐. this is not a fair rule/design. 

typescript is unique with its feature set. it may have thought about having different commenting system syntax
like /@---------------------@/  and with the use of tsconfig if the typescript programmer wants to keep the comments in compiled javscript files it can transform typescript comment syntax to javascript comment syntax or strips the typescript syntax comments if the typescript programmer wants.

This way if typescript finds javascript syntax comments it can safely pass them to javascript untouched.

typesript may have thought about this. but there may not be need for that at time. but now typescript world needs it. 

typescript should think about this and it should change and improve its world. so that `rest 🍏` can also exit to javascript 🌍so that the justice is served. typescript programmer can find million alternate ways to do this.  that is not the change the world want to see. even typescript would think so if it wants to improve.

Typescript can think of this possible solutions and many more.

1.  all the comments inside `/*!` can exit to  javascript 🌍 with the destination world comment syntax.
2. none of comments inside `/*!` can exit to  javascript 🌍
3. create a unique comment syntax system for typescript and leave the javascript 🌍 in peace. 

Come on typescipt change yourself and have some fun.

**Comment by last-Programmer** [comment]
@typescript-bot @RyanCavanaugh this is not a question. it can be be actionable in code.

**Comment by RyanCavanaugh** [comment]
@last-Programmer You requested a way to retain some comments in emit. I provided two of them, one of which is basically what you asked for, and one of which seems like the more logical solution for the scenario. Combined with not using a template that describes what you're looking for, this is not further actionable.
