### ISSUE TITLE
Type inference regression in TypeScript v4.5

### ISSUE THREAD

**Issue by TeoTN** [microsoft/TypeScript#47958]
# Bug Report

Sorry for the vague title, wasn't sure how to name it otherwise

### 🔎 Search Terms

* type inference 4.5
* PickKeysByValue

### 🕗 Version & Regression Information

- This changed between versions 4.4.4 and 4.5.4

### ⏯ Playground Link

* [Example in 4.4.4](https://www.typescriptlang.org/play?ts=4.4.4#code/C4TwDgpgBACglgYwNYGkIgM4CEQDUCGANgK4QA8AKgDRS4B8UAvFAN5QDaKUcAdlEugD2AMygUAugC4xncVAgAPYBB4ATDLSgB+KF2k8IANwgAnKAF92AkCLHiA3AFgAUC8VhBJ4FFCRYiJBgTQUgvOAgMShoYBmZ4ZCj-ZDRMHAIScmpYOjonV2cEQR4Mb0EAIwArJlYXKCh8aQByfEaqWqgy6QBGAFY253M8l2FiHgRgOCL6hAQIMGAAeR5CEABlYBNeAHMAChKTaX3tgEppQ0E4VVZzF2HR8cm+YR5KeSUVdShyiohxmi5FMo1Bp4qh0Ng8ERSIkjjwtjkdnBlABbaRZazSFDHGrOOr4GZzRbLNYbbaIlFWdDiY55G7OIA)
* [Same example in 4.5.4](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBACglgYwNYGkIgM4CEQDUCGANgK4QA8AKgDRS4B8UAvFAN5QDaKUcAdlEugD2AMygUAugC4xncVAgAPYBB4ATDLSgB+KF2k8IANwgAnKAF92AkCLHiA3AFgAUC8VhBJ4FFCRYiJBgTQUgvOAgMShoYBmZ4ZCj-ZDRMHAIScmpYOjonV2cEQR4Mb0EAIwArJlYXKCh8aQByfEaqWqgy6QBGAFY253M8l2FiHgRgOCL6hAQIMGAAeR5CEABlYBNeAHMAChKTaX3tgEppQ0E4VVZzF2HR8cm+YR5KeSUVdShyiohxmi5FMo1Bp4qh0Ng8ERSIkjjwtjkdnBlABbaRZazSFDHGrOOr4GZzRbLNYbbaIlFWdDiY55G7OIA)

### 💻 Code

```ts
type PickKeysByValue<T, V> = { [K in keyof T]: T[K] extends V ? K : never }[keyof T];

export type PickProperties<T, P> = Pick<T, PickKeysByValue<T, P>>;

const obj = {
  a: 'a',
  b: 15,
};

function acceptOnlyString(str: string): void {}

function fn<T extends object, K extends PickKeysByValue<T, string>>(item: T, key: K) {
  acceptOnlyString(item[key]); // Argument of type 'T[K]' is not assignable to parameter of type 'string'.
}
```

### 🙁 Actual behavior

Line `acceptOnlyString(item[key]);` throws an Error `Argument of type 'T[K]' is not assignable to parameter of type 'string'.`

### 🙂 Expected behavior

The line should pass - key is limited to only keys for which `item[key]` is string

**Comment by RyanCavanaugh** [comment]
This code only worked in 4.4 because the type wasn't being checked at all:
```ts
type PickKeysByValue<T, V> = { [K in keyof T]: T[K] extends V ? K : never }[keyof T];

export type PickProperties<T, P> = Pick<T, PickKeysByValue<T, P>>;

const obj = {
  a: 'a',
  b: 15,
};

function acceptOnlyString(str: string): void {}
function acceptOnlyNumber(num: number): void {}

function fn<T extends object, K extends PickKeysByValue<T, string>>(item: T, key: K) {
  acceptOnlyNumber(item[key]);
  acceptOnlyString(item[key]);
}
```

We don't yet have logic that can figure out that `K extends PickKeysByValue` means `item[key]` must be a subtype of string. I'm going to make a follow-up proposal for this since it's an oft-requested feature

**Comment by TeoTN** [comment]
That makes sense, thanks for explaining it! It'd be great if this could eventually become a feature :)

**Comment by hisuwh** [comment]
I've got a similar issue with a similar utility type:

```ts
export type KeysOfType<T, K> = { [I in keyof T]: T[I] extends K ? I : never }[keyof T];
```

I have two other types this is causing issues with in 4.5:

```ts
export const groupBy = <
    T,
    K extends KeysOfType<T, string | number>,
    KT extends K | K[]
>(
    arr: T[],
    key: KT
): KT extends any[] ? Record<T[K], any> : Record<T[K], T[]> => {
     ...
```

This type takes an array and a key and outputs an object with a key for every distinct key provided with the corresponding items underneath this.  If you pass an array of keys it does this recursively.  E.g.

```ts
const arr = [
    { group: "a", value: 1 },
    { group: "a", value: 2 },
    { group: "b", value: 3 },
    { group: "b", value: 4 }
];

const result = groupBy(arr, "group");

expect(result).toEqual({
    a: [
        { group: "a", value: 1 },
        { group: "a", value: 2 },
    ],
    b: [
        { group: "b", value: 3 },
        { group: "b", value: 4 }
    ]
});
```

In v4.4.4 the typing doesn't quite work as expected here:
![image](https://user-images.githubusercontent.com/4470351/155314050-291bb557-9fff-46dc-b998-d21db6eb364e.png)

I would expect:
```ts
Record<string, { group: string, value: number }[]>
```

In v4.5.5 usages of this function still work as expected by I get errors on the definition:

![image](https://user-images.githubusercontent.com/4470351/155314696-4aac0424-08b6-4ed4-8f0e-4fbddce09a8c.png)

My **other example is more problematic**.  I'm enhancing the typings of Vuex modules so I can call a strongly typed version of commit and dispatch:

```ts
import type { ActionContext, CommitOptions, DispatchOptions, Payload } from "vuex";
import { VuexModule } from "vuex-module-decorators";

import type { KeysOfType } from "./types/KeysOfType";

interface EnhancedDispatch<T> {
    <K extends KeysOfType<T, (arg: any) => any>>(type: K, payload?: Parameters<T[K]>[0], options?: DispatchOptions): Promise<any>;
    <P extends Payload>(payloadWithType: P, options?: DispatchOptions): Promise<any>;
}

interface EnhancedCommit<T> {
    <K extends KeysOfType<T, (arg: any) => any>>(type: K, payload?: Parameters<T[K]>[0], options?: CommitOptions): void;
    <P extends Payload>(payloadWithType: P, options?: CommitOptions): void;
}

interface EnhancedContext<T, S, R> extends ActionContext<S, R> {
    dispatch: EnhancedDispatch<T>;
    commit: EnhancedCommit<T>;
}

export class EnhancedVuexModule<T, S, R = any> extends VuexModule<S, R> {
    public override context: EnhancedContext<T, S, R>;
}
```

This works as expected in v4.4.4:

![image](https://user-images.githubusercontent.com/4470351/155314481-7883bd18-e13d-4e93-9069-1f140373dd22.png)

Again with v4.5.5 usages still seem to work but I get a typescript error in the definition: 
![image](https://user-images.githubusercontent.com/4470351/155314910-142cf5c1-8d25-4a2f-b330-b1a4fc6effce.png)

**Comment by kaya3** [comment]
A workaround is to declare the type of `item` as `T & Record<K, string>`. This fixes the type error in the function, and usually won't cause an error at the call-site.

```
function fn<T extends object, K extends PickKeysByValue<T, string>>(item: T & Record<K, string>, key: K) {
  acceptOnlyString(item[key]);
}
```

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBACglgYwNYGkIgM4CEQDUCGANgK4QA8AKgDRS4B8UAvFAN5QDaKUcAdlEugD2AMygUAugC4xncVAgAPYBB4ATDLSgB+KF2k8IANwgAnKAF92AkCLHiA3AChHCQTwzAoggEYArJqyOUFD40gDk+GFUQVDe0gCMAKzR5k6OwsQ8CMBwbiEICBBgwADyPIQgAMrAJrwA5gAUHibSzfUAlNKGgnCqrObOGVk5ecI8lPJKKupefhDZNFyKymoa8MhomDgEJOTUUG08dXR0DXDKALbSFFAAZFAASvOCJqpkKDSHxzTW0ijtgWC+AKRVK5SqNXqZ0uVnQ4naTgGjgA9MioCUUOkeA0fL4aBEwgiUWjTCYXtIAIImOrEC4qTy2UCQKBhABE3lZYW4Gh4gk8+AwGDgdR4+G8hGgwEEUDA+BM+DpyjMjPA0DZ+E5ADosTi-PjvISnEA)

**Comment by hisuwh** [comment]
@kaya3 doesn't seem to solve my case

**Comment by lorenzodallavecchia** [comment]
Expanding on @kaya3 workaround: if you need to match function properties you can let `T` extends `Record<K,Function>`.

**Comment by hisuwh** [comment]
Still an issue in `4.6.3`.

Can someone from the Typescript team confirm if this going to be fixed?  Currently stuck on `4.4.4` because of this issue.

**Comment by RyanCavanaugh** [comment]
The above comment https://github.com/microsoft/TypeScript/issues/47958#issuecomment-1045009026 still applies. We don't have any plausible fixes available; this code was previously *broken* and is now *working*, just in a way that flags errors that we're not capable of detecting that they shouldn't be issued.

**Comment by thscott** [comment]
@RyanCavanaugh 

You mention making a proposal to support this in  https://github.com/microsoft/TypeScript/issues/47958#issuecomment-1045009026 - did this ever happen? The examples from the original post and your comment above still result in errors.

**Comment by RyanCavanaugh** [comment]
Yes, #48992
