### ISSUE TITLE
Missing subfolder path completions with wildcard `typesVersions`

### ISSUE THREAD

**Issue by kim3er** [microsoft/TypeScript#47952]
# Bug Report

Sub folders of a folder listed in `typeVersions`, do not resolve in VS Code's autocomplete. I originally believed the issue to be related to [Support for NodeJS 12.7+ package exports](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1043271180).

### 🔎 Search Terms

typeVersions
autocomplete

### 🕗 Version & Regression Information

This is using Visual Studio Code 1.64.2 and TypeScript 4.5.5. I believe this bug to not be a revision, and is not resolved in TypeScript 4.7.0.

### ⏯ Playground Link

Code required relationship between two projects, so used Github instead.

[Github repo](https://github.com/kim3er/type-version-sub-folder)

### 💻 Code

We have an internal package, written in TS, transpiled to a sub folder called 'dest'. The package.json of the package looks like:

```
{
  ...
  "type": "module",
  "exports": {
    "./*": "./dest/*"
  },
  "typesVersions": {
    "*": {
      "*": [
        "dest/*"
      ]
    }
  },
  ...
}
```

We're able to consume the package in our projects, like this:

```
import { something } from 'test-package/something'; // Actual file './dest/something.js'
```

This works. Our code is transpiled correctly. We get autocomplete on the import path, and typing on the imported whatever, within VS Code.

Until, we attempt to access a sub folder within the 'dest' folder. Within a subfolder, like:

```
import { somethingElse } from 'test-package/sub-folder/something-else'; // Actual file './js/sub-folder/something-else.js'
```

In this instance, we get everything from above, except autocomplete on the import path. The file still resolves, and we get typing. Our build script still runs, the files is just invisible.

This is using Visual Studio Code 1.64.2 and TypeScript 4.5.5. Both project and package have the following tsconfig.json:

```
{
  ...
    "target": "ES2016",
    "module": "ESNext",
  ...
}
```

### 🙁 Actual behavior

Autocomplete does not resolve the scripts with the sub folder.

![Demo](https://p-4qFNYDd.t4.n0.cdn.getcloudapp.com/items/P8u6o7mW/e4ca180a-a8ad-4db3-93f6-f67e9a3ea15b.gif?source=viewer&v=d7c549522979cafb78c5f28a6309e1d6)

### 🙂 Expected behavior

Autocomplete should resolve the scripts within a sub folder.

**Comment by jasonwilliams** [comment]
I was about to raise this too. I was following https://2ality.com/2021/07/simple-monorepos.html#a-better-solution%3A-npm-workspaces-and-typescript-project-references

I needed to have paths in a library instead of just one default export.

@andrewbranch I know you [worked](https://github.com/microsoft/TypeScript/pull/43149) on this feature, is this a bug? It looks like the resolution works but just not on auto complete?

Here is another example:

https://user-images.githubusercontent.com/936006/154711473-cf43aee0-57f4-4d53-a8f7-1e330d8e706c.mp4

Here is a test case repository (shown in the video).
https://github.com/jasonwilliams/subpath-testcase

**Comment by kim3er** [comment]
Hey @jasonwilliams, that blog was also my starting point! 😁

**Comment by jasonwilliams** [comment]
> @jasonwilliams your case is a separate issue. Does it work after there is already one import of projecta elsewhere in projectb? If not, that’s _another_ separate issue.

no it doesn't. And in the video you can see I have the top line, the second line still doesn't work. 
But even if i import from another file in project B, it still won't auto complete elsewhere

**Comment by andrewbranch** [comment]
The way auto imports work and path completions work are just super different. Two different language features with completely different code paths.

**Comment by jasonwilliams** [comment]
I've just tested this again with the `4.7.0-dev.20220322` version and it still doesn't work. (auto complete doesn't work but the module is definitely there). 

I have set VSCode to use the workspace version and it made no difference. Is this expected @andrewbranch ?

**Comment by TheMrZZ** [comment]
Using Typescript 3.7 beta, I get the exact same issue with the `exports` field. I didn't find another issue specifically for this, is there already one?
