### ISSUE TITLE
The return type is not compared to the argument

### ISSUE THREAD

**Issue by aonics** [microsoft/TypeScript#47968]
# Bug Report
In my case, I fixed it by changing the type, but it looks more like a bug or am I missing something
### 🔎 Search Terms

- pass return type as argument to function 
- string record can be assign to number record 
- return type not checked with argument 

### 🕗 Version & Regression Information

v4.5.4, and v4.7.0-dev.20220215

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogtgQwJYBsYCd0Ht1QLxQDeUEiqAXFAM7DpIB2A5lAL4DcAUKJFADJI0A8gDMM2dFXxQAShADGOACYAeegFc4AIwjoANLDJpMOAHycOC+jSiMIweMiPipACh3jKNOkwCUlB6hiOPgmUC7EpI6U7sEsPpyW1rbA-EKixhKukYEZVJSpwCJBEn5EJLn5AoXp4pIsIWERFSSGxXXxHBZYVsAtjsVSyQFOOC4A5ADKWHDQMehjHckFRblurRnxUAD0W7AAHpBywBCKUAhQ3LMZUAAWOhCUAILojBoQ9L1Ywhfg0GPDxTGUAEUHoWF6CCoVCQjHoCE0KGgwCwUDACHQCBmx1wXx+PDGyxqOCoYwAdJ0llUVrUXEN1uJxlMZuVxAtNjt9odjqdzpcWcE7ugHlBnq8Zh8oLi+f96TggSCwRCoTC4QikSi0RisTpJd9pYS2mTOhyAO44ADWkhNEBQKA4lLSbXCfQoUDG2RQQLibG2u1FbwlUt+boihk8tAYjB9LHlkkVZ2VsPhiIuGvRmLsOqD+INuSNQA)

### 💻 Code

```ts
type EmailError = { email: string };
type ListOfErrors = Record<number, EmailError>;

const getEmailError = (error: string): EmailError => ({ email: error });
const getListOfErrors = (emailErrors: ListOfErrors): { errors: ListOfErrors } => ({ errors: emailErrors });

const emailError = getEmailError('Some error');
getListOfErrors(emailError); // Expected a type error here: Argument of type 'EmailError' is not assignable to parameter of type 'ListOfErrors'.

getListOfErrors(getEmailError('Some error')); // Expected a type error here: Argument of type 'EmailError' is not assignable to parameter of type 'ListOfErrors'.

// works well
getListOfErrors({ email: 'email' }); // Argument of type '{ email: string; }' is not assignable to parameter of type 'ListOfErrors'.

```

### 🙁 Actual behavior

Compiler not throwing error, when checking return type and accepted argument. In my case I fixed by changing type of ListOfErrors like `Record<string, EmailError>`

### 🙂 Expected behavior

Expected a type error: Argument of type 'EmailError' is not assignable to parameter of type 'ListOfErrors'.

**Comment by whzx5byb** [comment]
I think what you need is [Exact Types](https://github.com/microsoft/TypeScript/issues/12936).

For your example, using `EmailError[]` instead of `Record<number, EmailError>` will solve the issue.

**Comment by aonics** [comment]
@whzx5byb  As I said above, I solved it as `Record<string, EmailError>` and it is not the same as array of emails. So in this case I can't agree with you, it seems missing strict type checking with aliases or something like this.

**Comment by fatcerberus** [comment]
So the issue is that `Record<number, T>` is effectively a type where all `number` keys are optional (i.e. it can be `{}`) and from that point of view `email` is just an extra property tacked on to a valid record, which is legal due to structural subtyping.  To prevent this assignment TS would need to support exact types (#12936), as mentioned.
