### ISSUE TITLE
Add an option to the compiler to switch between the strict equality or strict inequality operator and the non-strict version syntax

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/TypeScript#4796]
JavaScript is awesome, I love many things about it and in many places TypeScript made it even better but unfortunately it also inherited one of the most annoying things that I really hate, personally.

I tend to use the strict equality operator or strict inequality operator for everything but rarely when I don't mind comparing a number to a string that contains a number I'm using the non-strict version.

It can be really great if we could have an option in the compiler that whenever we use the non-strict version in the TypeScript it will emit the strict version to the generated code and vice-versa!

Many people are using JSLint/TSLint to catch the non-strict version in their code and prevent it but the issue with it is to fix the violation we need to use the syntax of the strict version which is verbose and it's always possible to disable the rule locally.

So with this option turned on the TypeScript compiler will emit code as follows:

| TypeScript | JavaScript
|:-----------:|:------------:|
| "2" == 2	 | "2" === 2 
| "2" === 2 | "2" == 2 
| "2" != 2 | "2" !== 2 
| "2" !== 2 | "2" != 2 

I know that TypeScript is smart enough to sometimes catch errors at compile-time but sometimes it's just not enough.

This will allow us to reduce the typing a bit, make the code cleaner and safer and really prevent errors.

**Comment by DanielRosenwasser** [comment]
Unfortunately, I don't think we can cater to this use case. Our view is that generally if you wanted to write something one way, you should have written it that way.

> Many people are using JSLint/TSLint to catch the non-strict version in their code and prevent it but the issue with it is to fix the violation we need to use the syntax of the strict version which is verbose 

I don't think a single character is significantly more verbose, but it might be my muscle memory. :smile: 

> and it's always possible to disable the rule locally.

But that's *definitely* more verbose than using `===`/`!==`, so it would be less likely to be used and more likely to be caught in a code review.

**Comment by eyalsk** [comment]
Okay thanks! :)
