### ISSUE TITLE
Compiler does not fully understand complex OR logic in conditional statements

### ISSUE THREAD

**Issue by AmirAsghary** [microsoft/TypeScript#47964]
# Bug Report

### 🔎 Search Terms
possibly null, conditional, condition, compiler

### 🕗 Version & Regression Information

Typescript version 4.5.4

Also tried it with the latest version available at the time (4.7.0-dev.20220218) and the issue persisted.

Please keep and fill in the line that best applies:
- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about known bugs that aren't bugs, etc.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgezAZwCrmgXigbwFBRQCuYAJgIbASkD6lAXFACKXQA+UAdkQDY8DcBKAGM4EVrQbNWUDtz6DCyCHABuAS2EQa60o24BbAEYrBAX0F4AZkU7Dg6hJygB3BHADW6zgHMAwggGYORiABRgYqqM8EhoGAA0XBAAHsDRiCjokACUuELCTsjAUBEQqixUUNilqgB0JBRUksVsHDW1ouJNdMCKIoXFnCnAFVhJqfVkEj2ycsMdYtOUloTqVlDhkaNQAGQ74yOsufiEhGLARHDONdsAPAfbAPxQAIxQjAC0L31meELnl2cQwmyjUmm0uigHxKkVqoI0Wh0pHMfxsdgcTigRkQHggnACQRCEE2ZXSsSyEESwLSsAycRyeVW61CQkIJLqDSWLTasM6XNye1ZG2pk0a1BmrQOCy64so2SExyFAKuG3anO6lFmMLK0v5UFuQrZIvVsu5Ur5GuA8tOp2eL0N7yh3yEv3+EAuKpF8PBSKh2rq3sRuhRQA)

[Codesandbox link](https://codesandbox.io/s/nostalgic-chaum-x164lq?file=/src/index.ts:0-716)

### 💻 Code

```ts
type PropsType = {
  updated_at: Date | null;
  created_at: Date | null;
  service_id: number;
};

function brokenCompare(prev: PropsType, next: PropsType) {
  // tsc can't deduce from this if statement that 
  //    the return ternary conditions are not null and are Date objects
  if (
    (prev.updated_at || prev.created_at) &&
    (next.updated_at || next.created_at)
  ) {
    return (prev.updated_at || prev.created_at) < (next.updated_at || next.created_at)
      ? 1 : -1;
  }

  return next.service_id - prev.service_id;
}

function workingCompare(prev: PropsType, next: PropsType) {
  const prevDate = prev.updated_at || prev.created_at;
  const nextDate = next.updated_at || next.created_at;

  // re-writing it like this will make the error go away
  if (prevDate && nextDate) {
    return prevDate < nextDate ? 1 : -1;
  }

  return next.service_id - prev.service_id;
}
```

### 🙁 Actual behavior

Using the `brokenCompare` function will throw an error because the Typescript compiler cannot understand that the `updated_at` and the `created_at` keys inside the curly braces are Date objects and not null. 

### 🙂 Expected behavior

One would expect that the `updated_at` and the `created_at` keys inside the if statements are Date objects and not null.

**Comment by fatcerberus** [comment]
TS narrows variables/properties, not whole expressions, and `(prev.updated_at || prev.created_at)` is not enough information to narrow either one of the operands individually.  Your `workingCompare` is the correct way to handle this.

**Comment by AmirAsghary** [comment]
@fatcerberus thanks for the reply.
