### ISSUE TITLE
Imports containing path mapping aren't replaced on emit

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#47979]
# Bug Report

Basically I have a couple of `compilerOptions.paths` configured, but these paths aren't getting replaced in compiled code.

### 🔎 Search Terms

- paths
- replacement
- import

### 🕗 Version & Regression Information

I'm seeing this issue in v4.5.5. I haven't experienced this issue before.

### 💻 Code

Run the following to reproduce the issue:

```
git clone https://github.com/fabiospampinato/voby
git checkout d0a3519b62d532d7b0fdd145c820cab0f2265453
cd voby
npm install
npm run compile
cat dist/components/error_boundary.js
```

### 🙁 Actual behavior

You'll see stuff like `__importDefault(require("~/create_element"))`.

### 🙂 Expected behavior

Those tildes should be replaced.

**Comment by fabiospampinato** [comment]
I should probably add that those paths seem to be handled properly during type-checking, if I remove them TS isn't able to resolve those imports anymore, so it doesn't look like I've misconfigured it.

**Comment by fatcerberus** [comment]
Duplicate of #26722 (among many others).

TS doesn’t rewrite import paths, the `paths` option exists only for telling TS about paths/aliases that your runtime or bundler already knows about.

**Comment by fabiospampinato** [comment]
Oh really, it didn't even cross my mind that this could be broken on purpose.

Thanks.
