### ISSUE TITLE
Narrowing union of enums does not work when one is derived from the other

### ISSUE THREAD

**Issue by kaya3** [microsoft/TypeScript#47971]
# Bug Report

This bug concerns type narrowing of a union of two enum types. It occurs when one enum is declared depending on the other; this pattern is meant to ensure that two enums have disjoint value sets so that it is safe to take a union of them.

### 🔎 Search Terms

narrow union enum

### 🕗 Version & Regression Information

Bug occurs in all versions of Typescript currently available on the Typescript Playground (3.3.3 to 4.5.4 and nightly).

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about enums and narrowing.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/KYOwrgtgBAYg9nKBvAUFdsDymoF4oCMKAviqJFAEICGATsmhpQIIBKesCAdDNlANSFG6APQiqbDgCYSKFABNgAYwA2dYFBXAALlAAeALk6IAPlToBuOQEsAZgAo9UAIS58NWlxasAlAwxQYlDAtLRwtEYAKgCeAA4aAOTwpua0CVDWAM5QIHC61JmZ1gDmINQARlpQ2ojacYnJCVzCUEpwIJm6wHrxStrJRskcelakQA)

### 💻 Code

```ts
enum Foo {
    FOO = 1
}
enum Bar {
    BAR = Foo.FOO + 1
    // BAR = 2
}

declare let x: Foo | Bar;

if(x !== Bar.BAR) {
    // error: Type 'Foo | Bar' is not assignable to type 'Foo'.
    const expectFoo: Foo = x;
}
```

### 🙁 Actual behavior

The condition `x !== Bar.BAR` does not narrow the type of the variable `x` to `Foo`, however replacing the line `BAR = Foo.FOO + 1` with the equivalent line `BAR = 2` does result in narrowing.

### 🙂 Expected behavior

The type of the variable `x` should be narrowed to `Foo`, regardless of whether `Bar.BAR` is declared as the constant expression `Foo.FOO + 1` or the literal `2`.

**Comment by MartinJohns** [comment]
Sounds like a duplicate of #43839. Used search terms: `enum narrow in:title`

**Comment by kaya3** [comment]
That does seem to be the same issue, yes.
