### ISSUE TITLE
TypeScript 4.5+: typescript.d.ts is missing new moduleResolution values

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/TypeScript#47987]
# lib Update Request
https://github.com/microsoft/TypeScript/blob/main/lib/typescript.d.ts is missing "node12" "nodenext"
## Configuration Check
My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition
https://github.com/microsoft/TypeScript/blob/main/lib/typescript.d.ts is missing moduleResolution: "node12" "nodenext"

## Sample Code
tsconfig.json
```json
{ 
"compilerOptions": { 
  moduleResolution: "node12"
 }
}
```

## Documentation Link
https://www.typescriptlang.org/tsconfig#moduleResolution

## Related
- #46452

**Comment by MartinJohns** [comment]
What version are you running? This feature is currently only available in the nightly version. #46454

**Comment by frank-dspeed** [comment]
@MartinJohns i am using the nightly typescript marketplace extension of typescript because i am from the nodejs package maintainance group and i want to prepare upgrades for the most essential community modules.

**Comment by IllusionMH** [comment]
Do you mean this message?
![image](https://user-images.githubusercontent.com/1312662/155157140-3be5292b-f8e6-4811-9f85-b19736411984.png)
This one is regular JSON Schema validation error as nightly values aren't added to Schema Store
https://github.com/SchemaStore/schemastore/blob/065f36c63001253df25baf31406eaa9c644b49be/src/schemas/json/tsconfig.json#L315-L331

**Comment by frank-dspeed** [comment]
@IllusionMH your 100% correct

**Comment by frank-dspeed** [comment]
@RyanCavanaugh please reopen and see https://github.com/SchemaStore/schemastore/pull/2100

this issue gets internal as we need to use the external schemastore method to supply the spec https://raw.githubusercontent.com/ory/hydra/master/.schema/version.schema.json this is a example i can handle that for you but it is a internal issue
