### ISSUE TITLE
ESM mode should emit `__importDefault` for import of CommonJS module

### ISSUE THREAD

**Issue by MarcelGerber** [microsoft/TypeScript#47981]
# Bug Report

### 🔎 Search Terms

esm
es modules
esModuleInterop
__importDefault
es2020
commonjs
import

### 🕗 Version & Regression Information

I'm using TypeScript 4.5.5. This issue has been happening for all recent versions of TypeScript.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&noEmitHelpers=true&noLib=true&importHelpers=true&target=7&module=6&allowSyntheticDefaultImports=true&allowUmdGlobalAccess=false&isolatedModules=false&ts=4.5.4#code/JYWwDg9gTgLgBAJQKYEMDGMAiB5AsgZSSgDci4AzKCEOAIilQwFoATagegGcjSoA6AFadaAKFCRYiRvErU6DdDFFjw0eMkWEANkgwUqNetKbcdGZWggA7ThB18tEAOYAKDRm26YAShEjLNnZIDs4uInARUoo4BDxEfAxWLEQAKhD4MFDAVq7uMHxoCjBIAKI6IEhWMG7Snhjevt5AA)

### 💻 Code

```ts
import ReactDOMServer from "react-dom/server.js"
import React from "react"

import ReactSelect from "react-select"

console.log(ReactDOMServer.renderToString(React.createElement(ReactSelect)))
```

These are the relevant `tsconfig.json` settings:
```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "target": "es6",
    "module": "es2020",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true
  }
}
```

### 🙁 Actual behavior

Depending on whether `react-select` is a ES6 module or a CommonJS module, the code behaves differently.
* When it's a ES6 module, everything works fine.
* When [it's a CommonJS module](https://cdn.jsdelivr.net/npm/react-select@5.2.2/dist/react-select.cjs.dev.js), the code breaks since `ReactSelect` is an object (that has a `default` property somewhere).

Notice that react-select [has the following](https://cdn.jsdelivr.net/npm/react-select@5.2.2/dist/react-select.cjs.dev.js) CommonJS exports:
```js
exports.useStateManager = useStateManager.useStateManager;
// ...
exports.NonceProvider = NonceProvider;
exports.default = StateManagedSelect;
```

Also, if I change the TS target module to `commonjs` the code also works fine.

### 🙂 Expected behavior

TS should emit a `__importDefault` wrapper for the import, as it does in CommonJS mode. With that wrapper the import would work as expected.

**Comment by RyanCavanaugh** [comment]
When you have an ES import and target ES module mode and the target module is written using `export *`, as is the case here, this is a "No rewriting" scenario from the compiler's perspective -- there's no indication at all that a CJS module has entered the mix and we should do something differently.

**Comment by lalLAL95828** [comment]
Hello, have you solved this problem
