### ISSUE TITLE
Second generic function argument not type-checked correctly when generic type is inferred from the first one

### ISSUE THREAD

**Issue by sschultze** [microsoft/TypeScript#47988]
# Bug Report

### 🔎 Search Terms

Generic type inference

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about generic type inference.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=3&ts=4.5.4#code/JYOwLgpgTgZghgYwgAgIILMA9iAPAFWQgA9IQATAZ2QFcQBrELAdxAG0BdAPmQG8BYAFDIRyKHQAUcKAHNKALmT4AlIoBuWYOQDcQgL5ChMOhmwhkCKBDiR0mHASKkIFanUYt23CcZAJFEgB0wdJyiirIALw8GlqqaKYO+DwCwqJWYDRQ5qmieWJ0AaGUylE8vghBIbIlQnl6uoIGgkYm9uaW1raJIABKdCDQjiRkVLQMTKycXFI9inZmBFwANMjF4fESpdHIseR8dekQmdnIW2UHaflrPYHiIFI1yo31jc1CCDiUYGjk5AByNAAtgAjaCUBY4KIWKw2CCQh4SEBwIEQRTfKCgGSrOCKEDAsFQVYgvEE6DbHifECULAAGwggVpWBkEgABgAJYDIAAkvGRqL0qzAAAsUFZKDRaT9gNReXBkABqZAgvSs5TPQyCVB-QGg8EIu6SNgAcgAypB4CBjasAIyrABMHA1Wp1ZKgENu9wkJvNEEt1uQxoDjueyAA9GHkABhLBAgAOwHpUAssbjtLgoGoAFpkCKZch8yQ4xAMBByJqqd8CiBtQC3R72jboZ04Qj+iBBlAJLXdYSG2ZVj6LXArbaHU7Gvce-WETato0Pl8flPXXr3Qj7c3Yd12u3O93V32EYOzcPR4HgxPw5GY-HE9BkJRhVhJftPvH06BkDmQTQfuQsAgagmDAIQVzrNd+xwe15yEIA)

### 💻 Code

```ts
interface Action<T extends unknown[]> {
    run(args: T): void;
}

function createAction<T extends unknown[]>(func: (...args: T) => void): Action<T> {
    return {
        run: (args) => func(...args)
    };
}

function createActionRunner<T extends unknown[]>(action: Action<T>, args: T): () => void {
    return () => {
        action.run(args);
    };
}

const AddNumbersAction = createAction((name: string, a: number, b: number) => console.log(`Hi ${name}, the result is ${a + b}`));

AddNumbersAction.run(['Stefan', 1, 2]);
AddNumbersAction.run(['Stefan', '', 2]); // Compiler complains - this is expected

const runAddNumbersAction1 = createActionRunner(AddNumbersAction, ['Stefan', 1, 2]);
runAddNumbersAction1();

const runAddNumbersAction2 = createActionRunner(AddNumbersAction, ['Stefan', '', 2]); // Compiler should complain - but does not
runAddNumbersAction2();
```

### 🙁 Actual behavior

The compiler doesn't complain because of the empty string in the second-last line.

### 🙂 Expected behavior

The compiler should complain because of the empty string in the second-last line.

**Comment by MartinJohns** [comment]
This fixes your issue:

```typescript
interface Action<T extends unknown[]> {
    run: (args: T) => void;
}
```

https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

It's working as intended.

**Comment by sschultze** [comment]
First of all, thank you @MartinJohns , this does indeed fix the issue!

However, while I think that I understand the FAQ article, it is not clear to me how the suggested change of the Action<> interface (which I actually thought has an identical meaning to the previous one) helps fixing the issue. 🙈

**Comment by fatcerberus** [comment]
Martin's workaround fixes the issue (with `strictFunctionTypes` enabled) because declaring methods as fields makes the type checker check them contravariantly, as it does for plain function types.  When they are declared using method syntax, as in your original code, they are compared bivariantly (you can substitute both supertypes and subtypes).

**Comment by sschultze** [comment]
Thank you for the helpful explanation @fatcerberus !
