### ISSUE TITLE
Compile on save does not work on website projects

### ISSUE THREAD

**Issue by hugodevreugd** [Microsoft/TypeScript#4798]
I'm working on an old website project in Visual Studio 2015 with TypeScript 1.5.4. This type of project is still supported, but cannot be chosen for new projects.
When saving a TypeScript file the message "Output generation canceled" appears in the status area, and no JavaScript file is generated. Compiling the .ts file from the command line works fine.

When I create a new web project from scratch every thing works well.

**Comment by mhegazy** [comment]
looks like the same as #4350, can you give TS1.6 a try?

**Comment by hugodevreugd** [comment]
Yes, it could be the same issue, in the website project I have no access to the TypeScript Build properties for unchecking settings like "Do not emit outputs if any errors are reported". Maybe this setting causes the problem if it's checked by default.
I would love to give TS1.6 a try, but where can I find a setup for installing the 1.6 beta plugin for VS 2015? I have not much experience with github and such, sorry :(

**Comment by mhegazy** [comment]
TS 1.6 released today, For VS2015 it should be available shortly in the Extensions & Updates tab, and you can find the download links in the blog:
http://blogs.msdn.com/b/typescript/archive/2015/09/16/announcing-typescript-1-6.aspx
