### ISSUE TITLE
Bug: The AND operator ( && )  are Broken

### ISSUE THREAD

**Issue by frank-dspeed** [microsoft/TypeScript#47984]
# Bug Report
ECMAScript The AND operator ( && ) gets wrong interpretet it has the assumption that a Object that can not be NULL can be NULL 

### 🔎 Search Terms

Javascript chain operator

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
any.js
```js
// @ts-check
function resolveCustomResolver(customResolver) {
  return (customResolver
    && typeof customResolver === 'function'
      ? customResolver
      : typeof customResolver.resolveId === 'function' && customResolver.resolveId
      ) || null;
}
```

the above function uses the so called ECMAScript The AND operator ( && ) a chain of && s, each value will be evaluated from left to right. If any of these values happen to be falsy, that value will be returned and the chain will not continue. If the chain doesn't break before reaching the end, the last value in the chain will be returned.

so lets start reading customResolver && every thing after that knows customResolver Can Not be null null is a falsy value so the chain would return it and end. 

### 🙁 Actual behavior

It does not get correct interpreted i can fix it via typecasting 

### 🙂 Expected behavior

type inferense should be able to read the chain and so not tell me that customResolver Can be null or undefined

**Comment by frank-dspeed** [comment]
@MartinJohns can you give some more feedback whats wrong with my assumption? can it be null ?

**Comment by MartinJohns** [comment]
I give a thumbs down to every new issue that ignores the issue template. :shrug: You didn't fill out three sections.

**Comment by Josh-Cena** [comment]
I don't understand the problem at all either. If you code is able to enter the second branch (`typeof customResolver.resolveId === 'function' && customResolver.resolveId`) that means the condition is falsy, i.e. `customResolver` is already something like `null`/`undefined`. Do you happen to mean this instead? (The ternary is parenthesized)

```ts
function resolveCustomResolver(
  customResolver: (() => void) | {resolveId: () => void} | null,
) {
  return (
    (customResolver &&
      (typeof customResolver === 'function'
        ? customResolver
        : typeof customResolver.resolveId === 'function' &&
          customResolver.resolveId)) ||
    null
  );
}
```

**Comment by fatcerberus** [comment]
> over 90% of all JS Devs are not even aware of the `&&` operator

🤣

**Comment by frank-dspeed** [comment]
looks identical: https://github.com/microsoft/TypeScript/issues/40359
