### ISSUE TITLE
Negative tuple index access should not be allowed

### ISSUE THREAD

**Issue by Septh** [microsoft/TypeScript#47983]
# Bug Report

### 🔎 Search Terms
`tuple,` `negative`

Found #39293 with the same remarks but regarding types, not values.

### 🕗 Version & Regression Information
Observed in 4.5.5, 4.5.4 (Playground) and 3.9.7 (Playground)

### ⏯ Playground Link
There: [Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4&q=141#code/MYewdgzgLgBAtgTwCoFcAOaA2BTAXDAbRjBTgCNsAnAGmNIspgF0YBeQmABls+YFgAUIID0wmAHEQIACa00AQwgRsEQaEiwQAazbxk6LNgIBGJoJFjJMmFCm0AZvICWmCDEUxsADzTZgUbGkYAHcnKAALGAAiVEMbBF8YAHICEnIqWjSGJiSYEHsYHDAAcwjkgCZc8I8wEE8cOGwwWHlYJzBpb2SAZiSAOhsIAApygBYATm6ASii1cGg8rXLdRFjDAm6WGHMBURgAORBYYqlZGAhwkBRMIKpKEEYrqDmNPJA0N3ZVgxwCAFpTIIgA)

### 💻 Code
```ts
const myTupple: [ number, number ] = [ 0, 0 ]

// Good, passes
const ok = myTupple[1]

// Good too, fails as expected with "Tuple type '[number, number]' of length '2' has no element at index '3'. ts(2493)"
const ok2 = myTupple[3]  

// Not good, should error out
const oops = myTupple[-1]

```

### 🙁 Actual behavior
Passes.

### 🙂 Expected behavior
Should fail (I guess).

**Comment by MartinJohns** [comment]
I don't see how this is any different from #39293.
