### ISSUE TITLE
code generation

### ISSUE THREAD

**Issue by unicomp21** [microsoft/TypeScript#47986]
https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts

How is the above generated?  Is it generated via a tool which parses webidl?  The reason for asking, I'm wondering if we could do the same for blazor/c#/js interop?

https://github.com/yoshiki-okawa/BlazorJSProxy/issues/1#issuecomment-1046793751

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator
