### ISSUE TITLE
Function parameter type check failed

### ISSUE THREAD

**Issue by yclgkd** [microsoft/TypeScript#47997]
# Bug Report

### 🔎 Search Terms
type inference
type narrowing
object
constant

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 3.3.3 and 4.5.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/JYWwDg9gTgLgBAbwKIEcCuBDANgXzgMyghDgHIABGATzAFMBaAYwAtstaA7Ac1oGcB6NDGBZepANwAoScA4xaUfBka04ABQW8IHRJLhwOGELQBccXjCiyuAGj3naADzMWr3STkmNtFuGACMcAC8uvqGxmakIMAA1rSkdvq8TpEARhBUCfYYPGb+AEwektR0cABKwXComFgAPCW0EPh+-jaI4abmltZtyc5dbrZwOZ0caCCpCjgAfHD8-HAN5ZWWaLRePvCMULQY8hpQWjohABRgGFBGvGYHRwCUwbMI9t4cWuwAdFgQXGcXV3cittdvtNNozv4HvM4AB3ZhUODAeDAXgGCBwBREKBAA)

### 💻 Code

```ts
import {Equal} from '@type-challenges/utils';

interface Person {
  name: string,
  sex: string
}
const p1 = {
  name: 'mike',
  sex: 'boy',
  age: 12
}
type R = Equal<typeof p1, {name: string, sex: string, age: number}> // type R = true
const createPerson = (params: Person) => {
  console.log(params)
}
createPerson(p1) // why it is no error
```

### 🙁 Actual behavior

no error
### 🙂 Expected behavior

error

**Comment by MartinJohns** [comment]
Because the types are compatible.

https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by yclgkd** [comment]
Thank you so much.
