### ISSUE TITLE
Some never types are not considered to be equal to the never type

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#47996]
# Bug Report

### 🔎 Search Terms

never reduced intersection type equality

### 🕗 Version & Regression Information

- This changed between versions 4.3.x and 4.4.x

### ⏯ Playground Link

- [TS playground 4.3.5](https://www.typescriptlang.org/play?ts=4.3.5#code/CYUwxgNghgTiAEkoGdnwMoBcqZAHgBUBhAewDtcAPTAPngG8AoeeAfTHKswC55jOQ1ZmwBuUCAFcQvZJhgBLMgHNhAWxxgAFiGSF0ANXiDcZYGlkLlNABSycIfeKm8CBgJS9Mm+Wh8ZsuISkFMZ0AGQM8GKS0nwG8AC+jEmMoEhwiOSy8Ha4vFj2ePTwAGYkJLxkEqoARiAwiTSMjPIl8LYBIAB06phaOtYA5FCDbvBhEbndvf3IQ1BdNaNjTCxTwgD0G-AAegD8wpgAngAOCAQ6mPAAvPAAogCOEuK6x2ckbVMANPBkICL1JosLYsfaHU7nS4AJhu9yeLzwfwBMB+SMBm22uwOKTeCEezwgugAgj8AEJ0W7WQg2MbXOgEIzUECmNCk+B7eAARngvAADGNjMyzPBqdZafTGSZhUThBzOcI+bL4HIpArSi8QABuIA) (working as expected)
- [TS playground 4.4.4](https://www.typescriptlang.org/play?ts=4.4.4#code/CYUwxgNghgTiAEkoGdnwMoBcqZAHgBUBhAewDtcAPTAPngG8AoeeAfTHKswC55jOQ1ZmwBuUCAFcQvZJhgBLMgHNhAWxxgAFiGSF0ANXiDcZYGlkLlNABSycIfeKm8CBgJS9Mm+Wh8ZsuISkFMZ0AGQM8GKS0nwG8AC+jEmMoEhwiOSy8Ha4vFj2ePTwAGYkJLxkEqoARiAwiTSMjPIl8LYBIAB06phaOtYA5FCDbvBhEbndvf3IQ1BdNaNjTCxTwgD0G-AAegD8wpgAngAOCAQ6mPAAvPAAogCOEuK6x2ckbVMANPBkICL1JosLYsfaHU7nS4AJhu9yeLzwfwBMB+SMBm22uwOKTeCEezwgugAgj8AEJ0W7WQg2MbXOgEIzUECmNCk+B7eAARngvAADGNjMyzPBqdZafTGSZhUThBzOcI+bL4HIpArSi8QABuIA) (not working, changed behavior)
- [TS playground 4.5.4, current](https://www.typescriptlang.org/play?ts=4.5.4#code/CYUwxgNghgTiAEkoGdnwMoBcqZAHgBUBhAewDtcAPTAPngG8AoeeAfTHKswC55jOQ1ZmwBuUCAFcQvZJhgBLMgHNhAWxxgAFiGSF0ANXiDcZYGlkLlNABSycIfeKm8CBgJS9Mm+Wh8ZsuISkFMZ0AGQM8GKS0nwG8AC+jEmMoEhwiOSy8Ha4vFj2ePTwAGYkJLxkEqoARiAwiTSMjPIl8LYBIAB06phaOtYA5FCDbvBhEbndvf3IQ1BdNaNjTCxTwgD0G-AAegD8wpgAngAOCAQ6mPAAvPAAogCOEuK6x2ckbVMANPBkICL1JosLYsfaHU7nS4AJhu9yeLzwfwBMB+SMBm22uwOKTeCEezwgugAgj8AEJ0W7WQg2MbXOgEIzUECmNCk+B7eAARngvAADGNjMyzPBqdZafTGSZhUThBzOcI+bL4HIpArSi8QABuIA) (still not working)
- [TS playground 4.7.0-dev.20220215, nightly](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220215#code/CYUwxgNghgTiAEkoGdnwMoBcqZAHgBUBhAewDtcAPTAPngG8AoeeAfTHKswC55jOQ1ZmwBuUCAFcQvZJhgBLMgHNhAWxxgAFiGSF0ANXiDcZYGlkLlNABSycIfeKm8CBgJS9Mm+Wh8ZsuISkFMZ0AGQM8GKS0nwG8AC+jEmMoEhwiOSy8Ha4vFj2ePTwAGYkJLxkEqoARiAwiTSMjPIl8LYBIAB06phaOtYA5FCDbvBhEbndvf3IQ1BdNaNjTCxTwgD0G-AAegD8wpgAngAOCAQ6mPAAvPAAogCOEuK6x2ckbVMANPBkICL1JosLYsfaHU7nS4AJhu9yeLzwfwBMB+SMBm22uwOKTeCEezwgugAgj8AEJ0W7WQg2MbXOgEIzUECmNCk+B7eAARngvAADGNjMyzPBqdZafTGSZhUThBzOcI+bL4HIpArSi8QABuIA) (still not working)

### 💻 Code

```ts
declare class State<TContext> {
  _context: TContext
  _value: string
  matches<TSV extends string>(stateValue: TSV): this is State<TContext> & { value: TSV }
}

declare const state: State<{ foo: number }>

if (state.matches('a') && state.matches('a.b')) {
  state
  // ^? this gets displayed as never
  type Test = Equals<typeof state, never>
  //  ^? since 4.4 this gets reported as false
  type Test2 = Equals<never, never>
  //  ^? even though this is always true
}

type Equals<A, B> = (<T>() => T extends B ? 1 : 0) extends <T>() => T extends A
  ? 1
  : 0
  ? true
  : false;
```

### 🙁 Actual behavior

Some types coming from intersections are not "reduced" to never even though they appear to be `never` for all other practical purposes, they are also displayed as `never`, but they are not considered to be equal to `never`.

### 🙂 Expected behavior

I would expect this kind to be reduced to `never` and to be considered "equal" to `never`

**Comment by MartinJohns** [comment]
Related: #27024

**Comment by aspic-fish** [comment]
related to: #45674

you can upgrade your `Equals` to this:
```typescript
type Equals<A, B> = (<T>() => T extends [B] ? 1 : 0) extends (<T>() => T extends [A] ? 1 : 0)
  ? true
  : false;
```
however I'm not sure this won't break any other type assertions
so you can check for never explicitly: 
```typescript
type IsNever<T> = 
  [T] extends [never]
    ? true
    : false

type BothAreNever<A, B> = 
  IsNever<A> extends true 
    ? IsNever<B> extends true
      ? true
      : false
    : false
  
type Equals2<A, B> = (<T>() => T extends B ? 1 : 0) extends (<T>() => T extends A ? 1 : 0)
  ? true
  : BothAreNever<A, B>
```

[Playground](https://www.typescriptlang.org/play?ts=4.5.4#code/CYUwxgNghgTiAEkoGdnwMoBcqZAHgBUBhAewDtcAPTAPngG8AoeeAfTHKswC55jOQ1ZmwBuUCAFcQvZJhgBLMgHNhAWxxgAFiGSF0ANXiDcZYGlkLlNABSycIfeKm8CBgJS9Mm+Wh8ZsuISkFMZ0AGQM8GKS0nwG8AC+jEmMoEhwiOSy8Ha4vFj2ePTwAGYkJLxkEqoARiAwiTSMjPIl8LYBIAB06phaOtYA5FCDbvBhEbndvf3IQ1BdNaNjTCxTwgD0G-AAegD8wpgAngAOCAQ6mPAAvPAAogCOEuK6x2ckbVMANPBkICL1JosLYsfaHU7nS4ARhu9yeLwATHg3iAPjlOj8-gCYED4CDdgcWCi+JcEbDHs8ILosfVMf9AZttgTwWcSbIEWTbhTEXgaTA6djcfiwSlidyqXgAII-ABCdFu1kINjG1zoBCM1BApjQAG0ZQBdeB7eAw3gABjGxi1ZnaSusKrVGpMNp1ksNxtN8AtwmNcikwl4JReIAA3M1iQBJZAAOXpMCVsOEOoIhqt2vgOr5+uELF9MH9LBYgeD4Yh8BlJC8krgsexUtl8vgwijtfqUroaZtfoQOaN8Bbcbwcqd1rQ3d7ufg48LheLVJAvbnyAXLEYYvhVKR0vLjcVBGVN0dnbQMr7notI-Te4Pqr4l5tkrP8HNbh9U-zK+f5crmmrIFb8bbnKQA)
