### ISSUE TITLE
--project flag not working as expected

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#4799]
I've got an [npm package which is written in TypeScript](https://github.com/johnnyreilly/globalize-so-what-cha-want).  The code for it sits in the [./src/lib](https://github.com/johnnyreilly/globalize-so-what-cha-want/tree/master/src/lib) folder.  Alongside it sits this `tsconfig.json`: (please note the **outDir** property)

```json
{
    "compileOnSave": true,
    "version": "1.6.0-beta",
    "compilerOptions": {
        "module": "commonjs",
        "declaration": true,
        "target": "es5",
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": false,
        "outDir": "../../"
    },
    "files": [
        "index.ts"
    ]
}
```

I'm using atom-typescript as my editor - and when I build inside atom, generation takes place as you'd expect.  My `index.ts` is compiled down to an `index.d.ts` and `index.js` in the **root** of the repository.  However, during my CI build I regenerate the file using a script in my [package.json](https://github.com/johnnyreilly/globalize-so-what-cha-want/blob/demo-project-compiler-flag-issues/package.json): 

```
  "scripts": {
    // ...
    "build-lib": "tsc -v&&tsc --project ./src/lib",
    // ...
  }
```

Surprisingly, this generates  `index.d.ts` and `index.js` in the **same** directory as `index.ts`.  This is unexpected.  I've managed to work around this by changing my `build-lib` script to switch to the `./src/lib` folder and then invoking `tsc` without any options like so:

```
  "scripts": {
    // ...
    "build-lib": "tsc -v&&cd ./src/lib&&tsc&&cd ../../",
    // ...
  },
```

However, I'm wondering why the --project option isn't working as you might expect.  In case you want to demo this you can see the workaround here: (master branch)

https://github.com/johnnyreilly/globalize-so-what-cha-want

And the problematic --project approach here: (demo-project-compiler-flag-issues branch)

https://github.com/johnnyreilly/globalize-so-what-cha-want/tree/demo-project-compiler-flag-issues

I'd initially thought that `rootDir` would resolve the issue for me (supplying the value "../../") but that made no difference.

**Comment by mhegazy** [comment]
this should be fixed by #4724. can you give `typescript@next` a try tonight.

**Comment by johnnyreilly** [comment]
Sorry for the delay in responding @mhegazy - all looks good.  Thanks :+1:

**Comment by mhegazy** [comment]
thanks for checking.
