### ISSUE TITLE
Support AbortSignal.timeout()

### ISSUE THREAD

**Issue by johanneswuerbach** [microsoft/TypeScript#48003]
# Suggestion

Add support for https://github.com/whatwg/dom/pull/1032 to the `AbortSignal` types.

## 🔍 Search Terms

AbortSignal, abort signal, timeout

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

The implementation in NodeJS https://github.com/nodejs/node/pull/40899

**Comment by huytd** [comment]
I think it is the same issue as #48444, looks like `AbortSignal.timeout` hasn't made it to the major browsers yet.

Here are the implementation tickets from the browsers:

- https://bugs.chromium.org/p/chromium/issues/detail?id=1181925
- https://bugzilla.mozilla.org/show_bug.cgi?id=1753309
- https://bugs.webkit.org/show_bug.cgi?id=236039 (seems to be resolved)

cc @orta @saschanaz

**Comment by malobre** [comment]
This feature has now shipped in (at least) Chrome, Firefox & Safari: https://chromestatus.com/feature/5768400507764736.

**Comment by blake-regalia** [comment]
This is now supported by all major browsers across the board. It's time to add the type.

**Comment by saschanaz** [comment]
The type has been there for a while in https://github.com/microsoft/TypeScript-DOM-lib-generator/, the remaining work is to fetch that lib here.

If you are in hurry, you can try https://www.npmjs.com/package/@types/web instead of waiting for a new TS release.

**Comment by ianschmitz** [comment]
This is in the latest TypeScript. It appears to have been introduced in 4.9.5. See example: https://www.typescriptlang.org/play?ts=4.9.5#code/IIIw9gTgLgyglgcwHYEMA2A6KcC2BTMAVygAoBWABioEog

I think this ticket can be closed as completed.

**Comment by jakebailey** [comment]
Done in #50884.
