### ISSUE TITLE
Paste into editor with format on paste removes pasted word

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#48006]
*TS Template added by @mjbvz*

**TypeScript Version**: @4.7.0-dev.20220222

**Search Terms**
- Format on paste
- format

---

I have auto save enabled and format on paste. When I paste a string into a another string, that string is removed. See 

![Recording 2022-02-08 at 12 51 17](https://user-images.githubusercontent.com/900690/153026022-87540838-eac4-4881-9425-05789d958499.gif)

//cc @sandy081

**Comment by mjbvz** [comment]
Here's the `format` request I see pasting into the first argument in the above example:

```
[Trace  - 00:27:06.888] <syntax> Sending request: format (5). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/matb/projects/san/index.ts",
    "line": 1,
    "offset": 14,
    "endLine": 1,
    "endOffset": 18
}
[Trace  - 00:27:06.919] <syntax> Response received: format (5). Request took 32 ms. Success: true 
Result: [
    {
        "start": {
            "line": 1,
            "offset": 13
        },
        "end": {
            "line": 1,
            "offset": 23
        },
        "newText": ""
    }
]
```

**Comment by RyanCavanaugh** [comment]
Repro explained:

Turn on Format on Paste, then write
```ts
const a = f('').x();
```
Put the caret between the quotes and paste `bar` (or anything really?) and the new text is
```ts
const a = f().x();
```
instead of
```ts
const a = f('bar').x();
```

**Comment by mjbvz** [comment]
@RyanCavanaugh I'm marking this as a VSCode priority for 4.7 as we've seen a few reports of it now

**Comment by sandersn** [comment]
So far, it looks like the tree walking part of the formatter doesn't correctly increment the scanner, so the end-of-tree section of the code ends up formatting `(` `)` instead of `(` `"bar"`.

Now I have to go understand how the tree walk works.

**Comment by sandersn** [comment]
Broken in #46875, which is not surprising since that PR adds the end-of-tree section.
