### ISSUE TITLE
missing DataTransferItem.getAsFileSystemHandle

### ISSUE THREAD

**Issue by jimmywarting** [microsoft/TypeScript#48002]
https://github.com/microsoft/TypeScript/blob/aa920c00f21e8a378e0b282401786b00d6310803/lib/lib.dom.d.ts#L4127-L4146

```diff
/** One drag data item. During a drag operation, each drag event has a dataTransfer property which contains a list of drag data items. Each item in the list is a DataTransferItem object. */
interface DataTransferItem {
    /** Returns the drag data item kind, one of: "string", "file". */
    readonly kind: string;
    /** Returns the drag data item type string. */
    readonly type: string;
    /** Returns a File object, if the drag data item kind is File. */
    getAsFile(): File | null;
    /** Invokes the callback with the string data as the argument, if the drag data item kind is text. */
    getAsString(callback: FunctionStringCallback | null): void;
+   /** @deprecated Non standard, use getAsFileSystemHandle() instead */
    webkitGetAsEntry(): FileSystemEntry | null;
+   /** The getAsFileSystemHandle() method of the DataTransferItem interface returns a FileSystemFileHandle if the dragged item is a file, or a FileSystemDirectoryHandle if the dragged item is a directory. */
+   getAsFileSystemHandle(): Promise<FileSystemFileHandle|FileSystemDirectoryHandle>;
}
```

**Comment by RyanCavanaugh** [comment]
This isn't sufficiently-supported yet
![image](https://user-images.githubusercontent.com/6685088/155382051-8c917965-7577-407e-8dd6-565863f4f7d0.png)

**Comment by wbt** [comment]
Is there a published rule for what constitutes "sufficiently supported?"

**Comment by wbt** [comment]
For example, [FileSystemDirectoryHandle.values](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle/values) has broader support, but is still missing from the DOM library type definition, along with [other methods](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle) of that object and related objects in this API. 
Knowing what the rule is would help prevent myself & others from wasting time on suggesting improvements that won't be accepted due to insufficient browser support, even if they do bring the TypeScript definition better in line with the standards.

**Comment by jimmywarting** [comment]
according to https://github.com/microsoft/TypeScript/issues/48001#issuecomment-1049204267
it must be two different engines (eg: Blink and Firefox) or Firefox and webkit (safari)

chrome and brave browser would count as one...

I do not think this is a good justification... blink have taken over opera, edge, IE, a early version of brave, Samsung and many other smaller browser that is just a shell around blink. so the other browser players basically don't matther at all - that's what you are saying...

I think that: if there is a standard for something in whatwg or tc39, then that should be a justification for adding something into the type def

**Comment by wbt** [comment]
> according to [#48001 (comment)](https://github.com/microsoft/TypeScript/issues/48001#issuecomment-1049204267) it must be two different engines (eg: Blink and Firefox) or Firefox and webkit (safari)

Apparently the requirement is even stricter than that, because #48001 was autoclosed with the suggestion rejected.

**Comment by jgentes** [comment]
For others who run into this, installing `@types/wicg-file-system-access` will provide proper type support for the File System Access API: https://www.npmjs.com/package/@types/wicg-file-system-access
