### ISSUE TITLE
Fixed length arrays causing errors with overloads

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#48013]
# Bug Report

### 🔎 Search Terms

"This overload signature is not compatible with its implementation signature."

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEWIhAdWgGsBnAHgGUAaOAFQEZa6AmAPgAoAoOOAWwCGATwBGwAApQIfTKWCkAXHCjABAExwAbIXADajZiwC61LgEolk6bOBU2Abi6hIsOANJD0iVBmy4E+ERQZFTMnDz8wmJWMnKKcABKqhoo2gCCUFDC5HRsphZwMTZ2cADeESowSFC4qGrACJgowGpupHCoxCgQAO647nCUjgC+XGPO0PDI6Fg4eBAAYgKYmhQ09Ez07Ny8gqISUrHySirqWjr6m6wmEaDAaEgw0EocAG4CmkjAJ8nnegZbIxmOAAXjYhUOxUobHMlkhcjsjgmrncnjQ3hmfnmSxWazCO0i+yKcSUSTOqSEGSyQhyeVuIHuj2ecDeHy+pN+FKp2VywLBEOsCOhsIFRxK5V4lWqtRQ9UazVaA063T6bUGIyAA)

### 💻 Code

```ts
export function fooWorks<S, T1, T2>(
  values: readonly [T1, T2],
): Promise<S>;
export async function fooWorks<S, T>(
  values: ReadonlyArray<T>,
): Promise<S> {
  return undefined as unknown as S;
}


export function fooFails<S, T1, T2>(
  values: readonly [T1, T2],
  executor: (value: readonly [T1, T2]) => Promise<S>
): Promise<S>;
export async function fooFails<S, T>(
  values: ReadonlyArray<T>,
  executor: (value: ReadonlyArray<T>) => Promise<S>
): Promise<S> {
  return undefined as unknown as S;
}
```

### 🙁 Actual behavior

Line 11 has "This overload signature is not compatible with its implementation signature."

### 🙂 Expected behavior

There would be a way to spell "I will pass an an array to executor that will have the same amount of elements as the one passed into values"

**Comment by RyanCavanaugh** [comment]
The problem TypeScript is trying to tell you about is that you could legally write
```ts
executor([]);
```
in the body of `fooFails`, which would be an unsound invocation because `[]` doesn't have two elements.

You could write `any` or `never` (with an accompanying assertion at the call site) here instead of `ReadonlyArray<T>`. Overload/implementation matching is admittedly very frustrating due to the nature of overloading itself.
