### ISSUE TITLE
Command line auto-fix

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#48012]
# Suggestion

When migrating a big repo, it's convenient if TypeScript can provide an auto-fix for auto-fixable problems.

For example: when enabling [preserveValueImports](https://www.typescriptlang.org/tsconfig#preserveValueImports) flag, TS should be able to auto-fix all missing `type` modifers.

## 🔍 Search Terms

auto-fix cli

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a command-line tool to auto-fix those.

**Comment by MartinJohns** [comment]
Related: #29450

**Comment by Jack-Works** [comment]
> Related: #29450

Can VSCode auto-fix perform a project-scope fix to all source files? And limit it to a specific fix operation, instead of applying all suggestions/fixes

**Comment by RyanCavanaugh** [comment]
See #19255

**Comment by Jack-Works** [comment]
Oh... A 4yr problem... So I guess we won't get it in short time

**Comment by hybridherbst** [comment]
As this is "closed as completed" - has it actually been completed? I can't find a way to auto-fix such issues.

**Comment by silverwind** [comment]
A `tsc --noEmit --fix` would certainly be welcome to fix trivial issues.
