### ISSUE TITLE
Why distributive conditional types works on non-union type?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#48010]
# Bug Report

### 🔎 Search Terms

conditional types

### 🕗 Version & Regression Information

  2.8.1 ~ 4.7.0-dev.20220222

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJLmvJyDeAoZQ5GYCAGwBMAuZEAVwFsAjaAbjwF88EB7EAZzDIKEeHTJgAanDJ0INdJFiIUAXlzFSlGgEZkHdrwFCKcMHGTqA8kwBWEBGAB0cfv2ABzEAAocHADTConDiUjJygQAiZhBOIDwA7t4AlMgAfMgAzMgA-Bok5NTIAEz6yDR+yexgAJ4ADigAogAeYFCIYABKcAkAwjwMdXwQ4AA8ACoZ6uPIEK0jFPwaAPrL7Qk0oDDQyL1leQDa4zTjgb00vQC65chHJ5fsAPQAVM8Ez8gAtN-vyMBC-AAFol+L8AAYQsCg5AfIyCYRmOAKDDKbAAMlwvyIBW0tEYLCg7Bh+l+tQayCE6juaBRWBQGPwxOxWiK9GYbF+HGuAB9bsdaBAAG7QM40OggADW8QSIEu4IhvwAQnQhAlATUcu9HngyShKcgWm0Ot0+gMhiARmBRrqeDAEeY0qwgA)

### 💻 Code

```ts
interface Interface {
    field: number;
}
const defaultValue: Interface = { field: 1 };
const data = Object.assign({}, defaultValue, Date.now() > 3 ? { field: 2 } : {});
type ExtractRawComponent<T> = T extends { __raw: infer C } ? [T: T, C: C] : [T: T];
/**
 * ---
 * it shows
 * ```ts
 * const data: Interface & {
 *    field: number;
 * }
 * type t = [T: Interface & {
 *    field: number;
 * }] | [T: never, C: unknown]
 * ```
 * But why?
 */
type t = ExtractRawComponent<typeof data>;
```

### 🙁 Actual behavior

It shows `typeof data` is not union type. But `ExtractRawComponent<T>` add a `| never` type on it and distributive it.

### 🙂 Expected behavior

I don't know. But it will break https://github.com/johnsoncodehk/volar in some case.

**Comment by RyanCavanaugh** [comment]
Something's gone a bit wrong here. The actual type of `data` is not what we're showing in the quickinfo - it's still a union, though not one I seem to be able to write. `typeToString` is simplifying this beyond what's actually going on underneath, but I can't see why we'd infer *anything* from the truthy branch of the conditional -- `__raw` is not uttered anywhere else in the sample.

```ts
interface Interface {
    field: number;
}
const defaultValue: Interface = { field: 1 };

// Displayed type: Interface & { field: number }
// Underlying type: Something else...
const data1 = Object.assign(defaultValue, Date.now() > 3 ? { field: 2 } : {});
// Is it this? Not quite
declare const data2: (Interface & { field: number }) | (Interface & {});
// Is it this? Not quite
declare const data3: Interface & ({ field: number } | {});

// dataA is the displayed type - not same as any of the above ofc
declare const dataA: Interface & { field: number };

type ExtractRawComponent<T> = T extends { __raw: infer C } ? [L1: T, L2: C] : [R1: T];
type t1 = ExtractRawComponent<typeof data1>;
// 2 and 3 are the same
type t2 = ExtractRawComponent<typeof data2>;
type t3 = ExtractRawComponent<typeof data3>;
type tA = ExtractRawComponent<typeof dataA>;

// ???
type Explode<T> = T extends { x: infer A } ? [A] : 'X';
// 'X' | [unknown] -- why?
type e1 = Explode<typeof data1>;
// 'X' - OK
type e2 = Explode<typeof data2>;
// 'X' - OK
type e3 = Explode<typeof data3>;
// 'X' - OK
type eA = Explode<typeof dataA>;
```

**Comment by weswigham** [comment]
Step one: Unsimplified return type is actually `Interface & ({ field: number; } | { field?: undefined; })`.
Step two: Lift the union to produce `(Interface & { field: number; }) | (Interface & { field?: undefined; })`.
Step three: `Interface & { field?: undefined; }` reduces to `never` (as in `getReducedType`), but in a deferred fashion - meaning we still have a union, but a member of the union is a deferred `never` (so the whole type ends up displaying as a non-union).
Step four: Distribute over this two element union where one element is a deferred `never`. `never` extends anything, and so always results in the `true` branch of a conditional.

PR up at #48061
