### ISSUE TITLE
Autocomplete fails in certain situations when using namespaces for generic types

### ISSUE THREAD

**Issue by mkafrin** [microsoft/TypeScript#48011]
# Bug Report

### 🔎 Search Terms

function generic type namespace intellisense
function generic type namespace autocomplete
function generic type autocomplete with namespace

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics and namespaces

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA7KBbEBnADlMCBiA9gfAN4CwAUPNUqhtrvAEKymU0fwAuAnpgiwBe8ALzx0XGAEtEAcwDc7GgF9KqipQBmAV0RguUgoniaiAHgAqAPgAUASgBc8AG4EpwUusoB6b-ACSmvA8BNrcMDzcfDKy3AAWCJpSMBLcAO7EBEFcCegIIAAeqJgQGPA2UPBQiB4ARnYANPAABoQEAHQsMJ1Qgs3waVIQEFXaXARgBCglIFwImDAE-DAQPO0+fgASBGkgziAwTVJBIWGSkbyYMfEIiIVc6cSFxaXo5WBVNSZEjfAyc8MpHlEHkBkMRpooENuMQoGMJlMZnMWl1+tUPM0hM11hRSg8oE4AIIwGBQHhmNo9bpCKzyeC+eCUro9YRw8aTaZ4srobRgXDodA6YY8Sh4+C1JxM2AsukMqXU3qjdmIrlvHl8jCC7TC0WzeAfMR3NLwYmk8nylm2OyyvwWoTwYAEMqIAj4+EcpEgLTmO29K02xlEKksh1Ot4ut3KzmzL0aCgMwkQdDER0YRAAcgeGRgAGtvjB4CgCMBtRhKKBILAEEWS6VAwQAExsKiF4ul5iscgtjiXASKsQSaRyRQt9ReXF64BEklkilEBvBmkBtoL5n2tkI6NzNW8-lanUTh4gSXzxe9ZenteKjce1XiXeaoWrXUPIKGkDG02zldnwT++m2pe0r2qm4aukqm6et6BBzo2v7-nKQEKsIoFIOBN4qjGQA)

### 🙁 Actual behavior

The `Foo.Bar.Baz` namespace/module nested type fails to autocomplete in certain situations when used as a generic type (specifically lines 13, 14, 25, and 26).

### 🙂 Expected behavior

All the provided examples (lines 11-14 and 23-26) should autocomplete the `Foo.Bar.Baz` namespace/module nested type properly.

**Comment by RyanCavanaugh** [comment]
This works fine for me in the Playground. Can you clarify?

![image](https://user-images.githubusercontent.com/6685088/155376739-5c18d5c9-67fe-4146-a0f3-9eac7728d5c5.png)

**Comment by RyanCavanaugh** [comment]
When you're writing `foo<X`, we treat that as a value space production, because it is (it's literally `is foo less than X`), thus only show value-side possibilities. Once the closing `>` is there, it's a type argument, and we switch to type mode. I don't think there's any way to "fix" this - the type/value filtering is super value in most expression positions.

**Comment by mkafrin** [comment]
Darn, that's unfortunate given it is weird to type out the line then go back and add the generic type after, but I understand the limitations of the parsing given the dual usage of the <> tokens. Thanks for the info!
