### ISSUE TITLE
System.register named modules output

### ISSUE THREAD

**Issue by pkozlowski-opensource** [Microsoft/TypeScript#4801]
I'm in the process of writing a TypeScript pre-processor for [Karma runner](http://karma-runner.github.io/) where I'm trying to use the System.register output. The problem I'm bumping into is that I can't seem to figure out how to have named System.register output from TS transpiler. 

This is, given this config:

```javascript
 var compileResult = ts.transpile(content, {
            module: ts.ModuleKind.System,
            moduleName: 'foo'
});
``` 

I would expect to get `System.register('foo', ['deps'], function(exports_1)` but I'm getting (with typescript@next): `System.register(['deps'], function(exports_1)`

Is there any additional compiler switch that needs / should be used? I've [found](https://github.com/Microsoft/TypeScript/issues/3655#issuecomment-124263773) the `moduleName` option being mentioned, but it seems not to be enough with the above config. 

Is there any additional compiler switch that needs / should be used? Or named modules with System.register are not implemented?

**Comment by vladima** [comment]
it is already implemented. Initially there was `transpile` function with the following signature
```ts
export function transpile(input: string, compilerOptions?: CompilerOptions, fileName?: string, diagnostics?: Diagnostic[], moduleName?: string): string;
```

This version was pretty difficult to extend (i.e to add new input parameters or return some extra information like source maps) without breaking existing consumers so later this function was superseded by `transpileModule` 

```ts
export interface TranspileOptions {
    compilerOptions?: CompilerOptions;
    fileName?: string;
    reportDiagnostics?: boolean;
    moduleName?: string;
    renamedDependencies?: Map<string>;
}

export interface TranspileOutput {
    outputText: string;
    diagnostics?: Diagnostic[];
    sourceMapText?: string;
}

/*
 * This function will compile source text from 'input' argument using specified compiler options.
 * If not options are provided - it will use a set of default compiler options.
 * Extra compiler options that will unconditionally be used by this function are:
 * - isolatedModules = true
 * - allowNonTsExtensions = true
 * - noLib = true
 * - noResolve = true
 */    
export function transpileModule(input: string, transpileOptions: TranspileOptions): TranspileOutput 
```

Example:
```js
var ts = require("typescript");
var content = 
	"import {f} from \"foo\"\n" +
	"export var x = f()";

var compilerOptions = { module: ts.ModuleKind.System };
var res1 = ts.transpile(content, compilerOptions, /*fileName*/ undefined, /*diagnostics*/ undefined, /*moduleName*/ "myModule1");
console.log(res1);

console.log("============")

var res2 = ts.transpileModule(content, {compilerOptions: compilerOptions, moduleName: "myModule2"});
console.log(res2.outputText);
```

prints
```
System.register("myModule1", ["foo"], function(exports_1) {
    var foo_1;
    var x;
    return {
        setters:[
            function (foo_1_1) {
                foo_1 = foo_1_1;
            }],
        execute: function() {
            exports_1("x", x = foo_1.f());
        }
    }
});

============
System.register("myModule2", ["foo"], function(exports_1) {
    var foo_1;
    var x;
    return {
        setters:[
            function (foo_1_1) {
                foo_1 = foo_1_1;
            }],
        execute: function() {
            exports_1("x", x = foo_1.f());
        }
    }
});

```

**Comment by pkozlowski-opensource** [comment]
@vladima perfect, that did the trick! Thank you so much for your prompt input!

Out of curiosity: is it documented anyplace that I've missed?

**Comment by mhegazy** [comment]
We do not have this documented. @vladima Can you add this to the compiler API wiki page?

**Comment by vladima** [comment]
Done, I've added the note to [Using then compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) page.

**Comment by pkozlowski-opensource** [comment]
Thnx @mhegazy @vladima for your help and reactivity. Love what you guys are doing with TS, keep it up!
