### ISSUE TITLE
Support ts.factory.createPropertySignature with leadingComment or jsDoc

### ISSUE THREAD

**Issue by gaoupon** [microsoft/TypeScript#48023]
# Suggestion

## 🔍 Search Terms

compiler api, code generate, createPropertySignature, comment, jsDoc

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Checking the `interface` example below in ast explorer, we can see the `jsDoc` node in `PropertySignature`. But it seems that we can not achieve this via `ts.factory.createPropertySignature`.
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/8264905/155540272-8330dd98-ee1b-4914-86f8-12cee47a56ee.png">

## 📃 Motivating Example

for better editor intelligence when using generated code from compiler api. 

## 💻 Use Cases

 Add support for adding comment / jsdoc when use compiler api for code gen, like: `ts.factory.createPropertySignature(...args, comments)`.

**Comment by RyanCavanaugh** [comment]
You can use `ts.addSyntheticLeadingComment` to do this

**Comment by gaoupon** [comment]
Thanks for your reply.
It looks great with `ts.addSyntheticLeadingComment` when we want to add some `text comment` to some node.
I'm wondering is there any way we can add `jsDoc` to nodes like`PropertySignature` or `FunctionDeclaration`, since that could provide better editor intelligence and develop experience, and whether there is any plan to do it.
