### ISSUE TITLE
Inferring within mapped tuple's type parameter raises error unexpectedly

### ISSUE THREAD

**Issue by Semperia** [microsoft/TypeScript#48026]
# Bug Report

### 🔎 Search Terms

- mapped tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried from 3.5.1 to the latest nightly (4.7.0-dev.20220215)

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220215#code/C4TwDgpgBAyg9gWwgMQK4DsDGwCWd1QC8UAFAHQUCGATgOYDOAXFJeiAJREB8LbAUKEixEEALKUwkACYAVVGAA2EADwyoEAB7AI6KfSjUIlKfgUgoGANbo4Ad3QBtALpQAPlGc9iAbw8AFKBwCSwgQOAAzKBknZj9qRBx6FRkHPyceAF8+AHpsqDhLQMjbaDBUYCgAAyDwiGpK-PL6HCloCKhgAAtoQVKaSiRtagFwaABBVXUtHT1hJDQsXHwvKKntXX1yKjomQPRa6ig-TkIeVnMAflIKMhoGZngkcUkIWXklZT8uE54ANzgWlBmOccnk6vFqMwxgYIPQKmB+oM6lAEKg4VAAEZtSKsFjUaiUcy9EZCABCk0061mjxQGGweHQKy2tx2DxEz2kckUyTWM02NzuuxqyOO3F4lyOQPF3zF-xafFBmPKe0xcC6UEwlCS+i6dQgAHJ9DZ1Pi4IdhfigrQOt0NWbDNgOqMSdBKEQoBMSJRmHDqFaADSY5joVAILHUH5QOVSLguzHuz3eqC+gNBqAhsN1SPRrhAA)

### 💻 Code

```ts
type SomeFunction = (...args: any) => any
type SomeMappedTuple<T extends readonly unknown[] | []> = { [P in keyof T]: Promise<T[P]> }
// ok if we put `infer` outside of the type parameter of SomeMappedTuple
type A<T extends SomeFunction> = T extends (...args: infer P) => any ? (...args: SomeMappedTuple<P>) => void : any
// error: A rest parameter must be of an array type
type B<T extends SomeFunction> = (...args: SomeMappedTuple<T extends (...args: infer P) => any ? P : any>) => void

// but in both cases there's no error inferring the correct type
type a = A<(a: string, b: number) => void>
type b = A<(a: string, b: number) => void>
```

### 🙁 Actual behavior

An error is raised for type `B`: A rest parameter must be of an array type, where the type parameter passed into `SomeMappedTuple` should be `unknown[]` or `any`

### 🙂 Expected behavior

type `B` should not raise any error

**Comment by RyanCavanaugh** [comment]
See #29919
