### ISSUE TITLE
Conditional type prevents assignability

### ISSUE THREAD

**Issue by dylhunn** [microsoft/TypeScript#48033]
# Bug Report

### 🔎 Search Terms

Index signature assignability, generic index signatures, conditional types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFUGcFNQewGagC4AtYGM4DsAmBLZfHAQwBsUBPAB1gANJkAnfbAc1GgA9lo9JQAFTqhqTaADc+yASUiR8bbCQBG+MoUoA6AFAhQACTgB3SdCYAaFOlBY8hYsorIa9QZx59cAxi3Yj8WQwMaGpeXF0dXGgMMhJxWzj5UAAxODgAHkEAPlBQAG8dPLyVeIAuUF9WDm5efiFQAH5QbABXAFsVc1AKlXSyaBJsAG4dAF8dKJi4hIHkUFZorlUBirTM-IBtAGtoSgqq9gBdXv7B7DHs0ejY+Ng5lpJ26FwABSY4ajX0jPzSgC9TnABkNLqMdItuCtYABeR7PN4fajDIA)

### 💻 Code

```ts
// Use of the conditional type `string extends T` prevents assignability.
// However, the conditional type `T extends string` is accepted.

declare class Foo<T>  {
    bar: string extends T ? number : boolean;
}

declare let indexable: Foo<{[key: string]: boolean}>;
declare let namedProp: Foo<{baz: boolean}>;

indexable = namedProp;
```

### 🙁 Actual behavior

When a conditional type is present in `Foo`, I sometimes cannot assign `Foo<{a: any}>` to `Foo<[x: string]: any>`, depending on the condition.

### 🙂 Expected behavior

Regardless of the conditional type, I should be able to assign `Foo` with named properties to `Foo` with an index signature.

**Comment by RyanCavanaugh** [comment]
Likely we're considering a `type extends T` to mark `Foo<T>` as invariant in `T`

**Comment by RyanCavanaugh** [comment]
It's very possible a straightforward fix here (if one is even possible) could have side effects that result in the fix being rejected. I'd recommend designing around it if possible.

**Comment by jihndai** [comment]
Is the expected behavior for `type extends T` to be flagged as bivariant like `T extends type`? Although it might satisfy the above test case, I think that it would probably lead to a weird behavior similar to how bivariance currently interacts with `T extends type`, for example:
```typescript
declare class A { a: string; }
declare class B extends A { b: string; }
declare class Foo<T> { foo: T extends B ? number : boolean }

declare let fooA: Foo<A>;
declare let tempA: Foo<A>;
declare let fooB: Foo<B>;

fooA.foo; // boolean
fooB.foo; // number

tempA = fooA;
fooA = fooB;
fooB = tempA;

fooA.foo; // incorrectly boolean
fooB.foo; // incorrectly number
```

Or should we somehow apply a structural comparison between the classes when we encounter those kinds of conditional types with generics? For example, below I use a duplicate of `class Foo<T>` to cause the compiler to perform a structural comparison instead of checking type parameters variance:
```typescript
declare class A { a: string; }
declare class B extends A { b: string; }
declare class Foo<T> { foo: B extends T ? number : boolean }
declare class Boo<T> { foo: B extends T ? number : boolean }

declare let fooA: Foo<A>;
declare let tempA: Foo<A>;
declare let fooB: Boo<B>;

tempA = fooA;
// both assignment works because fooA.foo and fooB.foo are both number
// even though the type parameters aren't bivariant
fooA = fooB;
fooB = tempA;
```

**Comment by dylhunn** [comment]
> Here's a more robust and extremely surprising example of what can happen as a result of this invariance. [Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD2AnAtgQUYsBPAPAFWgFMAPAF0IDsATGBFAYXgtMXhBzAqwD5voBvALAAoaNGBMILAK7BSSABQAHaQCMQAS2DREhMFSYgs4pizYQAXNHSZcebgEoBAXxEixAeg-QA6gAtKaAINGCZoUgDoACUACQBlaHgAM2gwE2oNUg0mMBBwrCVCABo4JDQMbHw+VUIJZEIYDQoANzBEDU5SaCaggDp3aC9oP1JSJUsvAHNMvzVeuo9kLVYIZNIPPALCOOB2pXWQiGkGjwAWAA4ABgBma4Gk+HgAQispdopJojJKGiDoAH5wohjtArElchBCABuESuYQiUCQWhlRjMVjsewCAYSChvWTyRDKNSabS6fSGYytEDHKx4Jz8OFwkRJaQUOTZCjhBqkBT0gZDABy8CywEI4T8YC6m0KOz2XSaSUIiBgERCqRgAAM6MhUWZ2KpHiA9BRuBroABac3ipVitpi1b1fneBSaADWhCM0AghWAHRA5uAkEIVCcwKNMAeiG6FEVGCanw1BrYxrNTSkeioiRSETFFDarAA7tBNORMHlSFtoBqZIQNdjJF0ksAAIzQAC80AohCL2t16IUNYcMNEg28MRtJRIShJmU93tqGiSWHj1ugSaNnESnJz0AAMvE1yB4MBXSrIvPfblxJAV2ADc1ik7r9IICud7EEji8XIkOF4GuxQVJVdEzSAq17Ux0RwGtTX6Ecv0bYAACYrAgtE2BwddjT4Dsux7FFILYAdgUIIc3BHIY8D8NUgOVdVwLKGxKjQvVMMNbDTRKMC73gB84LEBDoHBVtcO7UoUCYrAFAAbTw8SdUIkBiOOBwAF0yIo7wAFEMCQJ5rEmMAmhKJRWGaDQqFvTkpxnLoK0KZ9ITPMUP3SPU-wA6NYxAp8wK1Aj0PYGDU1xch9CzBiGEUtjk04WDoAAIVqMAXzFfyJIqOxTSfGiWjaDpmGjIISnS8pbGgkjTW6GAKGFdVX0mPN1DFeRIrKyosLijV+PSKQhLAFD5MknAWKgzqTRwzsxO1SSZLk0aiMHdThzhIA). Code:
> 
> ```
> class FormArray<T extends FormControl<any>> {
>   constructor(public readonly controls: Array<T>) {}
> 
>   // When T is on the RHS of a conditional type, FormArray<T> becomes invariant in T.
>   // https://github.com/microsoft/TypeScript/issues/48033
>   foo!: string extends T ? true : false;
> }
> 
> class FormControl<T> {
>   constructor(public readonly value: T) {}
> }
> 
> function test() {
>   // Notice that TypeScript infers this as `FormControl<boolean>` -- there are some
>   // (likely special-cased) rules for inferring `boolean` instead of the narrow literal type `true`
>   const fc1 = new FormControl(true);
>   // Here, explicitly specifying the boolean on the LHS blocks the special casing above,
>   // causing the RHS constructor to be inferred as `FormControl<true>`.
>   const fc2: FormControl<boolean> = new FormControl(true);
> 
>   // This infers as `FormArray<FormControl<boolean>>`, as above.
>   const fa1 = new FormArray([new FormControl(true)]);
>   // Error! Again, providing an explicit type causes the RHS control to be inferred
>   // as `FormControl<true>` instead of `FormControl<boolean>`. Because `FormArray<T>`
>   // is invariant in T, `FormArray<true>` is not assignable to `FormArray<boolean>`.
>   const fa2: FormArray<FormControl<boolean>> = new FormArray([new FormControl(true)]);
> }
> ```

**Comment by yseymour** [comment]
This also affects mapped types:
```ts
interface M {
    A: number;
    B: number;
}

declare class Foo<T extends keyof M> {
    bar: M[T]
}

declare let foo1: Foo<"A">;
let foo2: Foo<"B"> = foo1; // "A" is not assignable to "B"
```

**Comment by RyanCavanaugh** [comment]
@yseymour that's a correct error. When `M[T]` is anything other than a roundabout way of writing `number`, the assignment is unsafe
```ts
interface M {
    A: number;
    B: string; // <- changed
}

declare class Foo<T extends keyof M> {
    bar: M[T]
}

// Legal initialization
let foo1: Foo<"A"> = { bar: 32 }
// Purported legal assignment
let foo2: Foo<"B"> = foo1;
// Unsound - number inhabits string binding
const m: string = foo2.bar;
```

**Comment by RyanCavanaugh** [comment]
Types are not evaluated by iterating over each possible thing the type could be inhabited by, since doing things that way is combinatorially explosive. Things are generally either true for a category, or not, and an operation like this isn't valid at a category level.

**Comment by mkantor** [comment]
[Here's another example of this behavior which caught me by surprise](https://www.typescriptlang.org/play/?jsx=0#code/C4TwDgpgBAwg9gOwCYEtgsQQwDYB4BCAfFALxTABOArtBAB7ATIDOU+UA-FFQgNYJwA7gigAuKAggA3CBQBQc0JCgAxOHALEyAbygUImJImwgodcfGRoMCHJqgBfReGj5MFezr0GjCE2YtEVHQsPCJHBSQIAGNsd2hoxGZgKAAzdRUcZghxNQ1UrIhCOSjY+KhEhGSoACN3TOxs8TcPAsaihUrq9LgVCjgAWzzc9VwefiEELTSMwqgAenmoWX75LpS6ij7Blub3Mb4BYWnNhuyFpZW4eTl1md7+gd3VUfGjqdJa+rnFiThliirW5JDb1R7DNj7N6TaY9M7QX4CAFAoA):

```ts
type Conditional<B> = true extends B ? unknown : never

type Foo<B> = { readonly x: Conditional<B> }
type Bar<B> = { readonly x: Conditional<B> }

declare const fooFalse: Foo<false>
declare const barFalse: Bar<false>

const fooFromFoo: Foo<unknown> = fooFalse // error
const barFromBar: Bar<unknown> = barFalse // error

const fooFromBar: Foo<unknown> = barFalse // no error
const barFromFoo: Bar<unknown> = fooFalse // no error
```
