### ISSUE TITLE
Custom type guard not working as expected

### ISSUE THREAD

**Issue by bpasero** [Microsoft/TypeScript#4803]
I would like to adopt custom type guard functions and realized they dont seem to work in 1.6 as expected. See the example below where my custom check for isString does not narrow the foo parameter from any to string:

```typescript
function isString(arg:any): arg is string {
	return !!arg;
}

var foo:any;

if (isString(foo)) {
	// foo is an instance of any here
}

if (typeof foo === 'string') {
	// foo is of type "string"
}
```

**Comment by DanielRosenwasser** [comment]
Thanks @bpasero, we're planning to change the behavior in TypeScript 1.7. See issue #4432.

**Comment by bpasero** [comment]
@DanielRosenwasser great!
