### ISSUE TITLE
Type union bug

### ISSUE THREAD

**Issue by Fanda36** [microsoft/TypeScript#48037]
# Bug Report

### 🔎 Search Terms

union bug

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.0.5 and the latest

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKFEljgG9FiYBRAGyRCQDsYAaOAAkAKgFkAMgEluYAK4xhATzBIAgjBhRgAI3lIBydDAByEACZI4AXzjZccAEREjDipSpIAHrXgxll6TkYAAUcMABnOABeKgBIAB8GONjYvxUALiExKRl5JRV1TR09OET8GC8YFGd8Kjh6hsb6gHpmuDSkTPw0AAskNABrbQhPfFKCCs8qmrhW9p7gSIB3aAHlpDY2ZNiLcLRM8KLuAHM4+qs4xPptjq7e-qGR2soUnaQ9zMMMUwsz6yoAZQvD44BZMChZGwsLJuBhgBBuHBAvIABRgMLhTLIkIYgCUn2Y7E4PHg10ojWAmDRGIAdB1olEohNKtVUPhcWSmg0iDBZFBEQAeSbTVBwMBsdBIHoQNgWKBRejoiARGm7NA2ZoAPlmbRYCAQAHkEHA+kQ4JT5pZMMAoId2v5zZEYWhcCSkGYBAAmbhme0qOArKBrAMbLbkhoXcP1Hl8wVmYAAN01itpaqsAua8aTVEjVE5DQFmrqXLgAuxfqQUQc90Gw08DlB7zQCoFWa1GqLUaaZdyvn8VZrj3rjb2UXK7xgYy1xa5PaCFarwtZKAbapbbc1HZ180WcCQUBwUEdcBdB-6MBn3fLHUXLOcq6bY4qhynncaGc7ViAA)

### 💻 Code

```ts
import React from 'react';
import { ReactElement, HTMLInputTypeAttribute, ReactNode } from "react";

export type InputProps =
	| {
			type: HTMLInputTypeAttribute | 'textarea'
            // type: 'checkbox' | 'textarea' // this works well
			desc: string
	  }
	| {
			type: 'checkbox'
			desc: ReactNode
	  }


export default function Input(props: InputProps): ReactElement {
    if(props.type === 'textarea'){
        return <textarea placeholder={props.desc} /> // ERROR here if the first type is uncomented, 2nd type works well
    }
    return <div>{props.desc}</div>
}

{
    <>
        <Input type="checkbox" desc={<div/>} />
        <Input type="checkbox" desc='test' />
        <Input type="textarea" desc={<div/>} /> // this error is correct
        <Input type="textarea" desc='test' />
    </>
}
```

### 🙁 Actual behavior

Error: Type 'ReactNode' is not assignable to type 'string | undefined'.

### 🙂 Expected behavior

There shouldn't be an error because of the if statement on line 17.

**Comment by MartinJohns** [comment]
The type `HTMLInputTypeAttribute` includes the type `string | {}`. That screws up the narrowing. For what purpose they include this type I do not know.
![image](https://user-images.githubusercontent.com/5269069/155726980-2310ff8d-4959-477e-9794-1377ce2be5b2.png)


A workaround is to exclude this type from the union:

```typescript
type: Exclude<HTMLInputTypeAttribute, string & {}> | 'textarea'
```

**Comment by Josh-Cena** [comment]
@MartinJohns It's `string & {}`, which is practically still the same as `string`. However, it prevents TS from collapsing the type to `string` and provides better editor autocompletion.

**Comment by fatcerberus** [comment]
> For what purpose they include this type I do not know.

Any string is assignable to `string & {}`.  From what I understand this pattern is generally used to allow the IDE to provide suggestions for a string value without constraining it, as the more obvious `"foo" | "bar" | string` automatically simplifies to `string`.

**Comment by MartinJohns** [comment]
That makes sense. I still have a hard time wrapping my head around why subtype reduction behaves the way it does.

Here's a simplified example without all the React stuff:

 ```typescript
export type Props =
    | { type: 'textarea' | (string & {}); desc: string        }
    | { type: 'checkbox';                 desc: string | null }

declare const props: Props
if (props.type == 'textarea') {
    const desc: string | undefined = props.desc;
}
```

**Comment by MartinJohns** [comment]
@RyanCavanaugh Mind sharing an explanation why the non-React example behaves the way it does? [Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgezAZygXgFBWwHygbylEgC4oByYCAD2AEM4I7yo8AKZYOASwDsBzKADICAXwCUAbigATCMgDGZTjwHZ160VlwEi4CGXIKAFhAUBrAEYJq5aRoePZ8pVBV9BeXgFcANr6gtDDkFXwZoBQReTigwRBQyeCRkDG4AMyg2OOSAOmJoNDQKKlpw5nECbShI6OBnRWUuD1Yob145NL4IGXRY+OQcuUVJDC0gA)

I get that the first union type includes `'checkbox'`, still I'm struggling to understand why the `'checkbox'` specific type `string | null` for `desc` gets merged with the first type.

**Comment by RyanCavanaugh** [comment]
@MartinJohns I don't have a good explanation for that off-hand

**Comment by abduraufsherkulov** [comment]
> > For what purpose they include this type I do not know.
> 
> Any string is assignable to `string & {}`. From what I understand this pattern is generally used to allow the IDE to provide suggestions for a string value without constraining it, as the more obvious `"foo" | "bar" | string` automatically simplifies to `string`.

This doesn't work, returns never.
