### ISSUE TITLE
NonNullable not properly casting generic type when excluding nullish values

### ISSUE THREAD

**Issue by flavianh** [microsoft/TypeScript#48048]
# Bug Report

### 🔎 Search Terms

Generic types nonnullable

### 🕗 Version & Regression Information

This bug appears to exist ever since NonNullable was introduced (tested from 3.3.3 to 4.5.4)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFAFgJzgdwJLAHIgA2hAhgEaECmAPACoB8AFALABQiiAbiYSJQFyJaAGjYBKQXgQFi5KnXqIA3mw4xgiRt16VEAQgC8BxOAAmlYDDCVTAAoBk9rjz76jiMEUJjlqjojRKKBA0JG0+AG4-AF82P1QMTEQAUTQMNEYAchlSCkpMsTZY1iA)

### 💻 Code

```typescript
function throwIfNullable<T>(
  value: T,
): NonNullable<T> {
  if (value !== undefined && value !== null) {
    return value;
  }

  throw Error('Nullable')
}
```

### 🙁 Actual behavior

The line `return value` raises a compilation error `Type 'T' is not assignable to type 'NonNullable<T>'.`

### 🙂 Expected behavior

No compilation error as the if clause properly guards against nullish values

**Comment by jcalz** [comment]
Feels like #33912

**Comment by fatcerberus** [comment]
An alternative construction that works would be:
```ts
function throwIfNullable<T>(value: T | null | undefined): asserts value is T
{
    if (value == null) throw Error("Nullable!");
}

declare let x: string | undefined;
throwIfNullable(x);  // x: string | undefined
x;  // x: string
```

**Comment by RyanCavanaugh** [comment]
See e.g. #22348
