### ISSUE TITLE
Default parameter errors

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#48046]
# Bug Report

### 🔎 Search Terms

default parameter

### 🕗 Version & Regression Information

Tested on version 4.5.4 (latest in playground).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAFQKYGcqIDzMagDylTABN1FMAnGMAc0QB9EwQBbAI1SoD4AKAG4BDADYhUALhSIAvIgDkpVMCEgRUALTCxqeQEpEAbwC+AKFNpMfRctXqto8fsQB6F4hhYYFAA7dgqNAiAJ6IwLSoiFBwiELo6DB0SFAAFpHUtAxpVKgANIgA7imhnh4UYHBYoiJwBaiksRRKKmpYPkJUQmwA-KZuiAB63UA)

### 💻 Code

```ts
function Test <T extends string | number>(value: T = 'default-value') {}
//                                                    ↑↑↑ Error

Test('default-value') // it is perfectly fine to assign the string here, why it is not allowed as default param?
```

### 🙁 Actual behavior

I am getting the following error:
```
Type 'string' is not assignable to type 'T'.
  'string' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'string | number'.(2322)
```

### 🙂 Expected behavior

There are no errors, the default parameter is considered as valid value.

**Comment by alesmenzel** [comment]
The type T could become any of the constraints, so it becomes `function Test <number> (value: '....')`in which case the contract would be broken. One must include the default value as a possible type in the parameter
```ts
function Test <T extends string | number>(value: T | string = 'default-value') {}
```

**Comment by MartinJohns** [comment]
You can be more explicit with a literal type: `T | "default-value" = "default-value"`.

**Comment by fatcerberus** [comment]
Be careful with `arg: T | <default>` though - if the function is called without the argument, `T` defaults to its constraint rather than being inferred from the default value.  In general, defaulted parameters and generics don't mesh very well.
