### ISSUE TITLE
Intersection types - conflicts

### ISSUE THREAD

**Issue by jbondc** [Microsoft/TypeScript#4805]
I've been looking at using intersection, would like to understand the future plan:
```
// Case #1
class cls {
	a() { }
}
enum num { a }

type enumClass = typeof num & cls; // (a) should order matter?
type classEnum = cls & typeof num; 

let ec: enumClass;
ec.a; // a() => void

let ce: classEnum;
ce.a;  // a() => void ??

// Case #2
abstract class userConstraint {
	abstract voodoo(): string
}
abstract class otherConstraint {
	abstract voodoo(): number
}
type combine = userConstraint & otherConstraint; // (b) should conflicts just error?
let com: combine;
```
Are (a) and (b) bugs?
If there's no interest in supporting traits (conflict resolution) then it should be either:
- order matters (last one wins), no errors
- conflicts error

**Comment by mhegazy** [comment]
`num` is an enum type, not the enum value, so on both `enumClass` and `classEnum` `a` has only one declaration, which is a function.

i think what you mean is:
```ts
type enumClass = typeof num & cls;
type classEnum = cls & typeof num; 

let ec: enumClass;
ec.a; // num & a() => void

let ce: classEnum;
ce.a;  // a() => void  & num
```

this is described in #3622:
> The type A & B has a property P if A has a property P or B has a property P. If A has a property P of type X and B has a property P of type Y, then A & B has a property P of type X & Y.

**Comment by ahejlsberg** [comment]
Regarding order and errors, a key feature of the `&` type operator is that it can be applied to *type parameters*. This deeply affects the semantics of the operator, particularly as it relates to ordering and error reporting, [as I explain here](https://github.com/Microsoft/TypeScript/issues/4278#issuecomment-130240112).

A bit more regarding ordering: With the current rules we can assume `A & B` is a subtype of (and assignable to) both `A` and `B`, even when `A` and `B` are type parameters. With "last one wins" we could only assume `A & B` is a subtype of `B` (because `B` might override members of `A`). That would lead to a number of surprises and inconsistencies.

**Comment by jbondc** [comment]
Thanks @mhegazy, corrected the enum. As a concrete example I saw recently string enum/module combined with class:
https://github.com/Initsogar/cordova-webintent/blob/master/www/webintent.js

```
module Intents {
  export const ACTION_SEND = "android.intent.action.SEND";
}
class Api {
  startActivity() { }
}
type combine = typeof Intents & Api;

class ApiConflict {
  ACTION_SEND = 5;
  startActivity() { }
}
type combineConflict = typeof Intents & ApiConflict;
```
Rule makes sense though possibly:
```
1. The type A & B has a property P if A has a property P or B has a property P.
 If A has a property P of type X and B has a property P of type Y, 
then A & B has a property P of type X & Y. 
If types X & Y conflict then A & B has a property P of type Y.

The types X & Y conflict if ...?
```
Something like that though I'm not really sure. Think what I'm trying to get at is in the case of a conflict, you'd get a 'merged/composed type' where 'last one wins'?

That would allow for example to create a type:
```
type a = {a: number};
type b = {b: number};
type intersectionType = a & b; // a & b (no conflicts)
type mergeType = a & b & {a: string|number}; // {a: string|number, b: number}
``` 
It's another subtle detail but would allow to get an actual 'new type' out of the intersection.

**Comment by mhegazy** [comment]
Like @ahejlsberg explained earlier intersection tupes do not have a concept of a conflict; if the two types have a property with the same name, the intersection of the will have a property with the intersection of the property type in both. The rational is we have no way to resolve these conflicts correctelly, nor s good place to show the error.

I think what you are looking for is traits or mixin support for classes; if and when this is supported, we should be able to enforce a resolution policy and flag conflicts. We shied away from these as the Emmasctipt committee showed interest in pursuing it and we do not want to conflict with the standard.

**Comment by jbondc** [comment]
@mhegazy Not really 'traits or mixin support for classes', just some way to make sense of:
```
type whatIsThis = number & string;

abstract class a {
  abstract foo();
}
class b {
   foo();
}
type whatIsThis2 = a & b;

// Assuming these exists
type n12 = 1 | 2;
type AB = "A" | "B";
type True = true;

type whatIsThis3 = AB & "c";
type whatIsThis4 = n12 & "c";
type whatIsThis5 = true & "c";
```
Are these not conflicts, errors? The type system should do something?

**Comment by jbondc** [comment]
Another example:
```
class prv {
    private a;
}
class pub {
    public a;
    public b;
}
type mix = prv & pub; // can anything be assignable to this?
let hmm: prv & pub = new prv;
let hmm2: mix = new prv;
// Interestingly enough, the errors reported are different.
let hmm3: mix = new pub;

type param<A, B> = number & A & B;
let waa: param<prv, pub>;
```
The issue is the compiler allows creating types that have nothing assignable to them which seems totally impractical.

**Comment by jbondc** [comment]
Correction, you can assign any, null, undefined to these sort of 'non-existing' types:
```
let hmm4: mix = <any>new prv;
let hmm5: mix = null;
let hmm6: mix = undefined;
```

**Comment by jbondc** [comment]
@ahejlsberg The rule makes sense as-is for type parameters and displaying ```X & Y``` e.g.
```
type param<A, B> = { a: number, b: A & B } // ok
```
> Of course I'm perfectly happy to consider proposals that would bring them closer, but with the constraint that  &  needs to work with type parameters

For type parameters, conflicts can be checked at instantiation:
```
let waa: param<prv, pub>; // error
```
The simplest case would be to report an error. Seem like a better starting point, then easier to see how/if 'last one wins' could make sense.

**Comment by ahejlsberg** [comment]
@jbondc Type instantiation is aggressively deferred (i.e. it only happens if and when it needs to) it is not possible to consistently report errors during instantiation (because it may never happen). We also can't eagerly instantiate types because we quickly end up in infinite instatation chains when types reference themselves.

**Comment by jbondc** [comment]
One idea could be to:
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts#L4174
```
checkConflicts(types);
```
Would storing a TypeFlags.Conflict flag on the type help? Nothing is assignable to a target type that has 'conflict flag'. Not very familiar with recursive types & type parameters so hopefully not oversimplifying the issue(s).

**Comment by jbondc** [comment]
Think it could be a 'propagating flag':
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L1813

So if you have something invalid:
```
type bad = number & string;
type badAgain = any & bad;
```
The 'conflict' flag propagates to make this still an 'invalid / unassignable' type. Assignment to a  'conflict' type fails and reportAssignConflictError(node, type) which gives a nicer error message.

**Comment by mhegazy** [comment]
> gives a nicer error message.

We really can not do that. by the time you discover the conflict, you are way deep in instantiating a type, and there is not much meaningful information you can give to the user. this is one of the main reasons intersection types work the way they do.

**Comment by jbondc** [comment]
Ok I see what you were both saying, still doesn't answer the question. Is there an interest in:
(a) reporting an error on conflicts?
(b) auto-resolving conflict with 'last wins'?
(c) pretend conflicts don't exist

I think there's a way to do (a) or (b) though it isn't obvious.
Here's an attempt:
https://github.com/Microsoft/TypeScript/compare/master...jbondc:intersection-conflict

```
type aliasConflict = number & string; // error

let ac: aliasConflict;
ac = 5;
ac = "5";

let varConflict: number & string; // error

type n = { a: number }
type s = { a: string } 

let propConflict: n & s; // could error here
propConflict.a; // undefined

type param<A, B> = { a: number, b: A & B } // ok
let paramConflict: param<n, s>; // could error?
``

**Comment by jbondc** [comment]
Interestingly enough, ```type invalid = number & string;``` acts like a bottom type #1298 (nothing is assignable to it).

**Comment by aleksey-bykov** [comment]
@jbondc nice catch on `type invalid = number & string;`

**Comment by jbondc** [comment]
Another case to consider:
```
enum HttpMethodsWithoutBody { Get };
enum HttpMethodsWithBody { Post = 1 };
enum HttpMethodsWithWaa { Waa = 1 };

type HttpMethodsCombine = HttpMethodsWithoutBody & HttpMethodsWithBody;
type HttpMethodsConflict = HttpMethodsWithoutBody & HttpMethodsWithWaa;

let t: HttpMethodsCombine;
```

**Comment by jbondc** [comment]
@ahejlsberg Think errors could be emitted in ```instantiateAnonymousType``` but I'm not too sure. Doing it 'properly' would seem to involve a solution to #517 so that compiler is aware some type is recursive (and doesn't try to create the type).
