### ISSUE TITLE
Description of `tsBuildInfoFile` is misleading in generated tsconfig.json

### ISSUE THREAD

**Issue by uhyo** [microsoft/TypeScript#48053]
# Bug Report

### 🔎 Search Terms

tsconfig tsBuildInfoFile Specify the folder

### 🕗 Version & Regression Information

4.5.5, 4.7.0-dev.20220227

### ⏯ Playground Link

N/A

### 💻 Code

After running `tsc --init` the generated `tsconfig.json` includes the following line:

```js
  // "tsBuildInfoFile": "./",                          /* Specify the folder for .tsbuildinfo incremental compilation files. */
```

### 🙁 Actual behavior

The description says "Specify the **folder**" and the sample value also indicates that you specify a folder for this option.

However, specifying a folder would result in a following error when running `tsc`:

```
error TS5033: Could not write file '/path/to/folder': EISDIR: illegal operation on a directory, open '/path/to/folder'.
```

### 🙂 Expected behavior

Actually you need to specify the **file** .

[The official tsConfig doc](https://www.typescriptlang.org/tsconfig#:~:text=This%20setting%20lets%20you%20specify%20a%20file) also says “This setting lets you specify a **file**”.

 A fix would be, for example:

```js
  // "tsBuildInfoFile": "./.tsbuildinfo",                          /* Specify the path to .tsbuildinfo incremental compilation file. */
```

**Comment by juank1809** [comment]
Can I be assigned to this issue? I'd be glad to help

**Comment by Blopaa** [comment]
sorry, I didn't get to write anything but I started to help on this one, I think I have the solution, sorry for the inconvenience.
