### ISSUE TITLE
Unable to use recursive references in index signature value

### ISSUE THREAD

**Issue by ethanresnick** [microsoft/TypeScript#48063]
# Bug Report

### 🔎 Search Terms

recursive index type

### 🕗 Version & Regression Information

This is the behavior in every version I tried (including nightly), and I reviewed the FAQ.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAglC8UD2AjAVhAxsA3AKFEigCUsBXAJwGcBLANwgEkA7AEwgA8AVcaRAbygByAPRCAXMnRZcUANoBrCCElVgFGswDmAXUmlMlWgxbtuvKAF8cQA)

### 💻 Code

```ts
type A = { name: string };
type RecursiveIndexType = { '/': A; [key: string]: RecursiveIndexType };
```

### 🙁 Actual behavior

Error when defining `RecursiveIndexType`: `Property ''/'' of type 'A' is not assignable to 'string' index type 'RecursiveIndexType'`

### 🙂 Expected behavior

`RecursiveIndexType` should be a valid type, inhabited by objects like:

```ts
{ "/": { name: "A" } }
{ "/": { name: "B" }, "something": { "/": { name: "X" } } }
{ "/": { name: "C" }, "something": { "/": { name: "Y" }, "somethingElse": { "/": { name: "Z" } } } }
```

I.e., my expectation is that the index signature is supposed to define the type _for all properties not explicitly enumerated_, so it should be impossible for the type of the explicitly-listed `"/"` property to conflict with the type of the properties covered by the index signature.

**Comment by RyanCavanaugh** [comment]
> I.e., my expectation is that the index signature is supposed to define the type for all properties not explicitly enumerated,

This isn't what it does. See #17867

**Comment by ethanresnick** [comment]
Ah, ok, thanks for the reference! Closing :)
