### ISSUE TITLE
Error has different types in browser and in node.js

### ISSUE THREAD

**Issue by psnider** [Microsoft/TypeScript#4807]
In the browser, Error has a minimal interface. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

But in node.js, Error includes the **stack** property.  See https://nodejs.org/api/errors.html#errors_javascript_errors

So when I annotate existing node.js code such as:
```
new Error('oops').stack
```
*tsc* issues an error:
```
t.ts(1,19): error TS2339: Property 'stack' does not exist on type 'Error'.
```
This is correct for the browser, but incorrect for node.js.
If you cut and past the above code into the node REPL, node prints the stack trace for the error.

I thought this might be handled by *tsc* with a configuration parameter, but I couldn't find one.

Did I find a bug, or is there some corrective action I should take?

**Comment by mhegazy** [comment]
this looks like a typings issue on the [node.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts) side.

defining this in one of your files should do the trick:

```ts
interface Error {
    stack: string;
}
```

**Comment by psnider** [comment]
Thanks. That works.
I'll issue a Pull Request on DT...

**Comment by psnider** [comment]
See https://github.com/borisyankov/DefinitelyTyped/pull/5838

**Comment by vvakame** [comment]
it merged! :+1:
