### ISSUE TITLE
Instantiating record entries with a generic key is not possible when this key extends string. It is when the key extends number.

### ISSUE THREAD

**Issue by quadristan** [microsoft/TypeScript#48074]
# Bug Report

### 🔎 Search Terms

record key generic  2322 string 
homomorphic mapped string number

### 🕗 Version & Regression Information
This changed between versions 3.3.1 and 3.5.1 

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=3.5.1#code/MYewdgzgLgBFCm0DCAneBDBA5ArgWwCN4UYBeAHgBUZ4APBMAEwhjHyJQBoA1APgAoA1vACeALkqcAbugA2OeGO4BKMQCgYmmAAV0KKAEs55AErxQKRlR69epXgG8NWl6Eix4YKChFkYDgG1hEQBdMRl5eABfZxdNNCgcFDAaLx81GLU3aDhEKFQMBABlbwMwAHMyKhp6T2YYaBQy8pshUQlpOQUlVVidPUNjMwsrST47Rz7XcBzPb19SfyDRMIiFGLitBKSUufSYoA

### 💻 Code
```ts
const testCreateNumber =<T extends number,V>(key:T,value:V):
    Partial<Record<T,V>>=>{
        const entry = {[key]:value}
        return entry
}

const testCreateString =<T extends string,V>(key:T,value:V):
    Partial<Record<T,V>>=>{
        const entry = {[key]:value}
        return entry
}

```

### 🙁 Actual behavior
- `{[key]:value}` is inferred to its primitive type , ex :`{ [x: number]: V; }` (Sounds similar to[Bugs that are not bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs) , however here i am not using a mapped type ? )
- Starting between 3.3.3 and 3.5.1, it is possible to assign a `Partial<Record<T extends number,V>>` from a `Record<number,V>`, while it is not possible to do the same thing for strings.

### 🙂 Expected behavior
- The behaviour should be the same for `number` and `string` ( it was the case in version 3.3.3 but not in 3.5.1) 
- It should be easy to create an entry of a record without having to do `as Partial<Record<T,V>>`

**Comment by RyanCavanaugh** [comment]
This is an intended divergence. A value with a numeric index signature is interpreted to be implicitly bounded (e.g. usually by a `.length` property), but a string index signature is not.

**Comment by quadristan** [comment]
Can you confirm that 
> {[key]:value} is inferred to its primitive type , ex :{ [x: number]: V; }
is an intended behavior also M
Thank you
