### ISSUE TITLE
Infer function return type as type-guard for typeof comparison

### ISSUE THREAD

**Issue by borfig** [microsoft/TypeScript#48099]
# Suggestion

## 🔍 Search Terms

`typeof`, type-guard, `filter`, `Array.filter`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

If a function returns the result `typeof something === "<type>"`, then the return type of this function should be inferred as `something is <type>` and not just `boolean`.

## 📃 Motivating Example

An arrow function such as `item => typeof item === "string"` is prime example of a predicate that can be used with `Array<string | undefined>.filter<string>`. With the new automatic type infering, this arrow function can be used a type narrowing predicate.

## 💻 Use Cases
The following code is valid JavaScript, but not TypeScript.
```typescript
const list = ["foo", undefined, "bar"].filter(item => typeof item === "string");
for (const item of list) {
  console.log(item.length); // Object is possibly 'undefined'.
}
```
Because the type of `list` is `(string | undefined)[]` and not `string[]`. The proposed feature fixes this.

To work-around this issue, the predicate must be explictly typed as a type-guard. For example:
```typescript
function isString(item: string | undefined): item is string {
  return typeof item === "string";
}
const list = ["foo", undefined, "bar"].filter(isString);
for (const item of list) {
  console.log(item.length); // OK
}
```

**Comment by MartinJohns** [comment]
Duplicate of #38390.

**Comment by borfig** [comment]
> Duplicate of #38390.

indeed.

> 
> > To work-around this issue, the predicate must be explictly typed as a type-guard.
> 
> While this is correct, it doesn't necessarily have to be a new function, it can stay the fat-arrow function.

yes.
