### ISSUE TITLE
downlevel emit for spread does not match ES6 spec

### ISSUE THREAD

**Issue by vladima** [Microsoft/TypeScript#4810]
```ts
var x: number[] = undefined;
console.log([1, ...x]);
```

is compiled to
```js
var x = undefined;
console.log([1].concat(x)); // prints [1, undefined]
```

per spec it should be TypeError: [GetIterator](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getiterator) -> [GetMethod](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getmethod)->[GetV](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getv) -> [ToObject](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-toobject) -> raise TypeError.

**Comment by mhegazy** [comment]
looks like a dupe of #1679
