### ISSUE TITLE
Import of Enum from .d.ts only used as type results in unused import in JS

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/TypeScript#48124]
# Bug Report

Have a .d.ts in a package/another file with an enum like:
```ts
export enum MyEnum {
    a = 0,
    b,
    c,
    d
}
```

Have a file which imports that enum and uses it like such:
```ts
import { MyEnum as MyEnumFromModule } from "my-package";

enum MyEnum {
    a = MyEnumFromModule.a,
    b,
    c,   
    d
}
```

Once transpiled to JavaScript, there should not be any generated imports/requires like `const my-package_1 = require("my-package")` in the file.

Recently, I am now seeing such a `require` be generated, and it is marked unused with a message like: `'my-package_1' is declared but its value is never read.ts(6133)`

I have seen the expected behavior in:
- 4.5.5
- 4.6.0-beta

I have seen the wrong behavior in:
- 4.6.1-rc
- 4.6.2
- 4.7.0-dev.20220304

### 🔎 Search Terms

enum unused .d.ts regression

### 🕗 Version & Regression Information

- This is a regression
- This changed between versions 4.6.0-beta and 4.6.1-rc
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about enums

### ⏯ Playground Link

I had a hard time creating a playground for this, as my repro requires importing from another file. 

### 💻 Code

See above.

### 🙁 Actual behavior

See above.

### 🙂 Expected behavior

See above.

**Comment by andrewbranch** [comment]
@MRayermannMSFT what are your tsconfig / CLI options?

**Comment by MRayermannMSFT** [comment]
@andrewbranch 
```json
{
    "compilerOptions": {
        "allowJs": false,
        "forceConsistentCasingInFileNames": true,
        "importHelpers": true,
        "module": "commonjs",
        "noFallthroughCasesInSwitch": false,
        "noImplicitAny": false,
        "noImplicitReturns": false,
        "noImplicitThis": false,
        "noUnusedLocals": true,
        "noUnusedParameters": false,
        "outDir": "./out/app",
        "preserveConstEnums": false,
        "resolveJsonModule": true,
        "skipLibCheck": true,
        "strictNullChecks": true,
        "target": "esnext",
    },
    "include": [
        "./app/**/*"
    ]
}

```

**Comment by MRayermannMSFT** [comment]
@andrewbranch any update on this? :)

**Comment by rishipal** [comment]
I'm unable to provide a playground link since the repro requires importing another file, but here's the generated JS for the example TS input files which shows the unused import:

exporter.ts

```
export enum Enum {
  X = 'x',
}
```

main.ts
```
import {Enum} from './exporter';

export enum ValuesInInitializer {
  ENUM_MEMBER = Enum.X,
}
```

Generated js:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValuesInInitializer = void 0;
const exporter_1 = require("./exporter"); // unused import in JS 
var ValuesInInitializer;
(function (ValuesInInitializer) {
    ValuesInInitializer["ENUM_MEMBER"] = "x";
})(ValuesInInitializer = exports.ValuesInInitializer || (exports.ValuesInInitializer = {}));
```

**Comment by andrewbranch** [comment]
```ts repro
// @module: commonjs

// @filename: enum.ts
export enum MyEnum {
  a = 0,
  b,
  c,
  d
}

// @showEmit
// @filename: index.ts
import { MyEnum as MyEnumFromModule } from "./enum"

enum MyEnum {
  a = MyEnumFromModule.a
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?module=1#code/PTAEAEFsHsBMFcA2BTAXKAxtSMB2ArAZwFgAoMkCAMwEsVcBDSNUZXeSAOgBcTTkAHgAdoAJ26t2kUAFkAngFEpoAN5lQoBqAC8oAAwAadaABGR0hozmNsMgF8yFMOEIALaAHcFkGtyfU6NiYWGlxYQR4+GkgRcVVZRWUGQgSlDgAxUWwZOCRkUDtQKizpACJOYDYOUsd+ZXk06TULTR1UqUzs3JROBnsgA)

**Comment by MRayermannMSFT** [comment]
Lol @andrewbranch that's a lot of reactions.

**Comment by andrewbranch** [comment]
If only I could react with each of those twice over, there would be one for every I spent getting this to work after I thought I’d already be done

**Comment by MRayermannMSFT** [comment]
@andrewbranch I'll add a round of reactions to give you the twice over. Thanks for taking the time to look at this. :)
