### ISSUE TITLE
Support ES7: exponentiation operator

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#4812]
Here is the ES7 proposal: https://github.com/rwaldron/exponentiation-operator
As of today, the proposal is at Stage 3.

**Comment by danquirk** [comment]
For posterity, the original issue asking us to support this: https://github.com/Microsoft/TypeScript/issues/2102

**Comment by bluong** [comment]
Is this compatible for ES5 or does this target only ES7?

**Comment by DanielRosenwasser** [comment]
It's compatible with ES3.
