### ISSUE TITLE
TypeScript v4.6.2 is not supported for @typescript-eslint/typescript-stree.

### ISSUE THREAD

**Issue by gustavoabell** [microsoft/TypeScript#48131]
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

**Comment by gustavoabell** [comment]
I'm having problems with lint in my project, is anyone else?

**Comment by fatcerberus** [comment]
Umm, this isn't a TypeScript issue.  You need to take this up with whoever authored the eslint plugin you're having a problem with.

**Comment by gustavoabell** [comment]
I got it, thanks.
