### ISSUE TITLE
Infer function parameter types from usage

### ISSUE THREAD

**Issue by theninthsky** [microsoft/TypeScript#48138]
# Suggestion

## 🔍 Search Terms

infer function parameter

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Function parameter types should be inferred from the way the function is invoked.

## 📃 Motivating Example

```
import type { FormEvent } from 'react'

const Demo = () => {
  const onSubmit = event => {
    event.preventDefault()
  }

  return (
    <form onSubmit={onSubmit}>
      <button type="submit">Go</button>
    </form>
  )
}

export default Demo
```
![image](https://user-images.githubusercontent.com/39136331/156912044-9722f092-d2c9-4d7e-ade5-566c36a0f24a.png)

Here I would like to avoid having to specifiy the event type as:
`(event: FormEvent<HTMLFormElement>) => {...}`

## 💻 Use Cases

This would greatly reduce the amount of code that has to be written, especially in those event handler cases where we all know they get an 'event' parameter.

**Comment by RyanCavanaugh** [comment]
Duplicate #34738, #38992, #11440, #15114, #15196, etc

**Comment by fatcerberus** [comment]
This looks even more complex than most of those, as it aims to infer parameter types from call sites.  Inferring parameter types from usage *within the function* is one thing (and TS can already do this manually in a limited capacity, with a refactoring), but inferring them from *call sites* is a whole other can of worms, and even if it were tractable I'm not sure I'd want it as global type inference a la Hindley-Milner is much harder to reason about.

**Comment by theninthsky** [comment]
I understand, thanks.

**Comment by jarble** [comment]
The v8 JavaScript engine has a [type profiler](https://medium.com/fhinkel/runtime-type-information-for-javascript-b134faac3c0a) that infers function parameter types at runtime. Could this tool (or a similar tool) be used to generate parameter type annotations for TypeScript?
