### ISSUE TITLE
Problem with ConstructorParameters

### ISSUE THREAD

**Issue by swojdyga** [microsoft/TypeScript#48133]
# Bug Report

ConstructorParameters returns error "Target requires 1 element(s) but source may have fewer." when it's use in callable parameter. Example:

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAJwKYGc4BsBuqA8A0gDSIAqiqAHlKmACbqJioDuiAFAHQ8CGyAc3QAuRLzABPANoBdAJSIAvAD5EhZRwCwAKER7EEBOijIQ0OMlFliO-QaMmzUCwAV+vALboAwryxZeACMsVFEOBRVEbwdTc2Q3ZE9UWmR0fDJlG205UUJEAG9bfTQoEGQkfIBfMSZCAG4dSp1m7QgA9CYAZTgPVG92pkLdfQAHEGCYCHswY1jnZC1huz0R5BgcXloUVF56BCwJRExegBFUEbp6OggJUVmYMAEsuwUhor0m7U+dNExcVA43V6-V4HVI4SUqikACIABKofxwRAAdQsWHoAEJofI6kA

### 🕗 Version & Regression Information

Version: 4.5.4 and newest (^4.7.0-dev.20220305)

**Comment by jcalz** [comment]
Please fill out the entire [bug report template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md) including inline code example, search terms, expected vs actual behavior, etc.  It's even better if you can show that you've searched existing issues and what other ones are relevant.
