### ISSUE TITLE
[FER] Type guard on left-hand-side of operator `in`

### ISSUE THREAD

**Issue by yw662** [microsoft/TypeScript#48149]
# Suggestion
Operator `in` can narrow the right-hand-side value, but it could also narrow the left-hand-side:
```ts
const a = {
    a: 1, b: 2, c: 3
} as const

const f = (char: keyof typeof a) => {}
const char = ['c', 'd'][Math.round(Math.random())]

if(char in a) {
    f(char)
}
```
`char` is `'c' | 'd'` (or `string`), but if `char in a` is true, it should be able to narrow to `'c'`.

## 🔍 Search Terms
`type guard`, `narrow`, `operator in`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

As shown above: narrow also left-hand-side when possible.

## 📃 Motivating Example
As shown above

## 💻 Use Cases
As shown above

**Comment by RyanCavanaugh** [comment]
This wouldn't be sound. See https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript
