### ISSUE TITLE
Compiler API: Expose `signature.thisParameter`

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript#48144]
# Suggestion

Remove `@internal` for the `thisParameter` on the `Signature` interface.

https://github.com/microsoft/TypeScript/blob/20c93d3b1da44d8ee740b466a5cde7894e8b3260/src/compiler/types.ts#L5771-L5772

## 🔍 Search Terms

compiler api, thisParameter

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

As above.

## 📃 Motivating Example

TypeDoc needs to access the this parameter to properly document functions via their signature rather than relying on nodes. Today, I plan to add this to a declaration file to expose it manually. https://github.com/TypeStrong/typedoc/issues/1875

**Comment by sandersn** [comment]
It's just another parameter, so I think it should be public just like `parameters`.

**Comment by isc-aray** [comment]
Is there a way to turn this off? It just feels off to me to document "this" as if it were a normal parameter, since it can't be passed that way, and in the course of normal use, most users won't be thinking about the type of "this" when they call a method.

**Comment by RyanCavanaugh** [comment]
Turn what off, exactly? This issue is about API availability of `this` parameters

**Comment by isc-aray** [comment]
Ah! Sorry, I misunderstood what was happening here. Never mind.
