### ISSUE TITLE
Typescript checking fails when ternary operator logic is extracted

### ISSUE THREAD

**Issue by ArthurMbraga** [microsoft/TypeScript#48146]
# Bug Report

### 🔎 Search Terms

- ternary operator problem
- shallow type check 
- extracted ternary operator condition problem

### 🕗 Version & Regression Information

- V4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1#code/GYVwdgxgLglg9mABAUwB4EMC2AHANsgRgAo4AjAKwC5EBvRAN3VxGQH5qwRNTkAnRAL4BKWgChEExBAQBnKIhkALOAHcAakxaIAvIigBPbMjjBEZcgDpGzZDu26ARJ258HAblHjJS1RpuJWRGxeGDAoEgorTWQRakUYABNkIiFRAU9QSFgEFAwcfAAmCKpaBmj2RGcefmExST1DY1NzKP97RyrXAKCQsOLWlljEeKSUtIzwaHgkYNDw5w4uapE6aTAZOHwLXDgAcyJnEXTMqZyR5JXBTyA)

### 💻 Code

```ts
function example1(obj: { value?: number }) {
    const showValue = typeof obj.value === "number";

    showValue ? print(obj.value) : hide()
}

function example2(obj: { value?: number }) {
    typeof obj.value === "number" ? print(obj.value) : hide()
}

function print(num: number) { console.log(num) }
function hide() { }
```

### 🙁 Actual behavior

 Only at `example1()` I'm getting this error:
> Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
>   Type 'undefined' is not assignable to type 'number'.

but the argument will never be `undefined`

![image](https://user-images.githubusercontent.com/16090650/156955343-217edf97-b4d0-4649-bf25-173a8f87c67d.png)

### 🙂 Expected behavior

Is expected that both `example1()` and `example2()` functions compile, because, technically, they are the same

**Comment by equt** [comment]
Marking the value as `readonly` will make example 1 work. And the reason has been explained in the corresponding fix PR [here](https://github.com/microsoft/TypeScript/pull/44730#issuecomment-868703811), which in brief is

> ...
> 
> We'd effectively have to check that there are no assignments to obj.data between the declaration of isString and the reference to isString in the if statement. This adds complexity and could be prohibitively expensive.
