### ISSUE TITLE
Ambient external module name incorrectly appears in `keyof typeof globalThis`

### ISSUE THREAD

**Issue by saucesteals** [microsoft/TypeScript#48147]
# Bug Report

### 🔎 Search Terms

- `keyof typeof globalThis`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/PTAEFkHsBMFcBsCmpqIMbwIYCdMBcBLSAO1AApQBnAC0gWlGMj1DRLUW1IHN5IAjTPAAq1ApVAB+UAEoAsAChUGHMgC2MBMgBEAM0iRtoAN4BfRSEVWFivAE8ADsl4Chwx8gC8oe08i7QF0ERMUprX2c+YIBpRDtQbwBrOP9AqLcPayC3UIBtPQNtAF0LMAAFbEgnbHtQAHJ9SDqUSEQJJhZEAA9xFhIfD3qI1OyQ8TqAOms2YkoWXQAuNNd4WPjvAsNS0AB5aOtrEFAAcUQWTFAANyFYZF1KtR9qSJWqNidQRRm5wLPj9PgCVAAB5hKBunhEMRoBJRmsAHxkRJLYQyJajdxOXLCIoJeEmRSgImgbBnWBcZbBUTiXKJEoKcwKbh-AFkTbaeQKSw2HnbZl4f6vADuBDwtFgLGZxE4BDQYQU30lLJWACYgUj0QC1jI8QSFMSSWSKRi8nTCcSjhUqpxag0DM1oK12sxwT0fv0IkMPCMAdTKJNFIz+YLgiq2Y0OaUgA)

### 💻 Code

```ts
// Module declaration ( should not concern globalThis ? )
declare module "foo" {}

type globalType = typeof globalThis

type globalKey = keyof globalType

globalThis["foo"]
// Property 'foo' does not exist on type 'typeof globalThis'.

const f: globalKey = "foo"
// OK

// See playground for more examples
```

### 🙁 Actual behavior

"foo" is a valid key/property of `typeof globalThis`

### 🙂 Expected behavior

"foo" should not be a valid key/property of `typeof globalThis` as `globalThis["foo"]` is not valid

**Comment by sandersn** [comment]
It took me a long time to figure out, but it turns out that `globalThis["\"foo\""]` is *also* erroneously valid. `keyof typeof globalThis` flattens `"\"foo\""` to `"foo"`, which makes the bug more obvious.
