### ISSUE TITLE
Possible regression in typechecker for Required type

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/TypeScript#48157]
# Bug Report

Since upgrade to 4.6 from 4.4 I have an error with Required type
full repro here
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIBGcUA-AFzIDOYUoA5rgL664wCuICYw6IyGJgA8AFWQQAHpBAATasgDWEAJ7oYaTAD4AFAAco6PVVEAaQVQBKEAI4dgUCLOEZ0WgJQ58hElB0wAbQMjAF13AG4WNk5uXn5iUh0wKlp6EAZPPEJkBH5qdAAbCAA6AvQGJIiWIA

The error was not happening on 4.4 and seems like also not in 4.5.
I didn't really see something obvious in release notes on what would cause this change.

### 🔎 Search Terms

Went through issues in ts repo to see if there was something already open

### 🕗 Version & Regression Information

4.6

Please keep and fill in the line that best applies:
-->
- This is a crash
- This changed between versions __4.4____ and __4.6_____

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIBGcUA-AFzIDOYUoA5rgL664wCuICYw6IyGJgA8AFWQQAHpBAATasgDWEAJ7oYaTAD4AFAAco6PVVEAaQVQBKEAI4dgUCLOEZ0WgJQ58hElB0wAbQMjAF13AG4WNk5uXn5iUh0wKlp6EAZPPEJkBH5qdAAbCAA6AvQGJIiWIA)

### 💻 Code

```ts
interface Foo {
    bar?: string
}

function foo<T extends keyof Foo>(prop: T, f: Required<Foo>) {
    bar(f[prop]);
}

function bar(t: string) {
    console.log(t);
}
```

### 🙁 Actual behavior

It complains that `f[prop]` can be undefined, but it is wrapped in `Required` which should have all keys from `Foo` as non optional

### 🙂 Expected behavior

Well, I guess it should not complain about undefined, if I properly understand the meaning of the `Required` generic

**Comment by DerGernTod** [comment]
this only happens with `strictNullChecks` enabled, in case this is of any help

**Comment by RyanCavanaugh** [comment]
Bisected to #47953

**Comment by ahejlsberg** [comment]
This and #48246 are caused by the same core issue. We need to exclude mapped types with optionality modifiers and/or as clauses from the new constraint logic introduced in #47370.
