### ISSUE TITLE
Generic derivation cannot show the correct type when used in function parameters

### ISSUE THREAD

**Issue by heretic-G** [microsoft/TypeScript#48151]
# Bug Report

### 🔎 Search Terms

generic

### 🕗 Version & Regression Information
4.6.2 
4.5.5 
4.4.4
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX1AFsd4AeAYXhAA8MRVgBneAJXBxmFMYxi1QDmAGngAKYFAxQAXPDQBrVDgDuqAJTwAvAD45qRStTaRAdSq16TeISgAHE5LAALCtu2icAIwBW0gN7wtjA4toyy5CLKjk6yZgC+arIAbjhYwABQoJCwCCjo2HgEIMQAjGSUNHQMzGxgHFw8fIIi4pIyegaqGjodSqrG8GaVlsw29tElru5evgFBIWHwEfBRGM6x8AnJqRkYAJ62CGMOa07l5lVWtfXcvPzCYgB0zxJSslCoe926H3tuWvAAul4CD4ABteTwfjweQgPY4RBLAC6slab1YIAwyBgqAAKgcQBQIUjtN9eoZ4Ok4ul9odrHYTs4yhQLiMMXVOLcmg9RM9Hq92r8yb9-ppAcDQRCofhYfDEeQURisTj8YcifISVT0plijhRH4JSD5qF-IbQSDUFBCCBRGoAnBlfgAOSNe5OzZmuJCM2rdYG83my3W0SoEDKABqUAgyBAdri8AA9AmxNaME4cMANEGbaGI1GY7IFH11Ns0p6qWptUQcCV9WbjWF-QGLVabXb4A7sc7XYJ3dTzV6fdFTc2W9bZE6SgAmADM7qTYmNIBg+yzrdkPYE5YSQA)

### 💻 Code

```ts
declare function demo <C extends Record<string, (data: unknown) => unknown>, W extends mapWatch<C>>(obj:{ props: C, watch: W }): void
declare function demo1 <C extends Record<string, (data: unknown) => unknown>, W extends mapWatch1<C>>(obj:{ props: C, watch: W }): void
type mapWatch <C extends Record<string, (...data: any) => any>> = { 
    [k in keyof C]: (data: ReturnType<C[k]>) => unknown  // use ReturnType as parameter, i get unknow
}
type mapWatch1 <C extends Record<string, (...data: any) => any>> = {
    [k in keyof C]: ReturnType<C[k]> // i get string type
}

demo({
    props:{
        name(){ return 'string' }
    },
    watch:{
        name(newValue){} // (method) name(newValue: unknown): void
    }
})

demo1({
    props:{
        name(){ return 'string' }
    },
    watch:{
        name: '123' // (property) name: string
    }
})

```

### 🙁 Actual behavior

When the ReturnType is used as a parameter, it is a unknow 

### 🙂 Expected behavior

When the ReturnType is used as a parameter, it is a string

**Comment by whzx5byb** [comment]
Workaround:
```ts
declare function demo <C extends Record<string, (data: unknown) => unknown>, W extends mapWatch<C>>(obj:{ props: C, watch: W }): void
type mapWatch <C extends Record<string, (...data: any) => any>> = { 
    [k in keyof C]: <T extends ReturnType<C[k]>>(data: T) => unknown 
}

demo({
    props: {
        name(){ return 'string' },
        age() { return 20 },
    },
    watch:{
        name(newValue){ 
            newValue.toLowerCase() // OK
        },
        age(newValue){ 
            newValue.toFixed() // OK
        }
    }
})

```
