### ISSUE TITLE
Restrict interface type. Disallow additional properties or strictly check type.

### ISSUE THREAD

**Issue by infacto** [microsoft/TypeScript#48162]
# Bug Report / Feature Request / ?

### 🔎 Search Terms

interface, restrict, disallow, additional properties, etc. In various combinations. Hard to find better words at this moment. Thinking in progress... (ETA: pending) 🤤

### 🕗 Version & Regression Information

Tested with `4.3.5` and `4.6.2` and the nightly `4.7.0-dev20220302`.

### 💻 Code

```ts
interface Apple {
  id?: string;
  /** [cm] */
  value: number;
}

interface Pear {
  name: string;
  /** [grams] */
  value: number;
}

class Test {
  public write(obj: Apple): void {
    console.log(obj);
  }
}

const test = new Test();

const pear: Pear = {
  name: 'WTF',
  value: 2
}

// No error. You can pass a pear as apple.
// It's not really a bug. But not expected / wanted here.
// How to allow only apples here? No pears!
test.write(pear);
```

### 🙁 Actual behavior

You can pass pears as apples. Pass interface with another meaning. It's perhabs no bug. But keep reading the expected behavior...

### 🙂 Expected behavior

I expect an error here. Don't pass pear as apple. Strictly allow Apple interface only.
The interface `Pear` has additional property `name` which is not allowed in interface `Apple`. I would except it if I use this:

```ts
interface Apple {
  id?: string;
  value: number;
  [additionalProp: string]: unknown;
}
```

I not sure, but it's probably not a bug. The pear object is compatible to interface `Apple` because it has the property `value`. And `id` is optional. We could argue about the `name`. Because the Apple has no property `name`. But even if we have to interfaces with just one property `value`. How to restrict the interface to only that interface what is specified?

It's ok if I pass a literal object. But in this case I branded an object explicitly to an interface type. The object has explicitly the type `Pears` and is passed to `Apples`. TypeScript know it. But only checks the property. I think this is intended. Using classes may fix it. But is there no way to work with interfaces here? - So, sorry I can't mark that issue clearly as bug, feature request or docs/question.

**Comment by fatcerberus** [comment]
What you're asking for is [Exact Types (#12936)](https://github.com/microsoft/TypeScript/issues/12936).

**Comment by MartinJohns** [comment]
Also see the FAQ: https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing

**Comment by infacto** [comment]
Ok thanks for info. I close this as duplicate of the referred issue. I'll post a comment to it (with a workaround I found).
