### ISSUE TITLE
Control flow analysis for dependent parameters doesn't work for methods

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript#48160]
# Bug Report

### 🔎 Search Terms

control flow analysis, dependent parameters, methods, #47190, #48110

### 🕗 Version & Regression Information

This behavior has been present since #47190 was merged, so TS4.6.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyyAthGABboAmAFAHQNxQDmAzgFzIDaA5HDwBpkIAK7EARtAC6yAD7ce4wclZgooZlICUnAG7pgVAgF8A3AQIJ0IVSTKUqAZQCe4OAA9OGLAF4cBIlIKahoAa1AqIQAHOGcAG3Q4Ki1-QiJkYBhkMIjkH3zkPh4UvDT05Bj4xKo6MHRUYHcIWi1TZAB6duRoKHQoIQAFXqjoMGdCuoamqh5kKnQIVmF0MG73YFtrZDGRwtV1EGY5YTFJKB4A9ONLokzs8JAqPILFYtTyokqEpNr0AFUoiMoABhOCsCA0VodLo9PqDYajcY8OoAoGg8GzeaLZarCDrTYgbbOXY8fYaY6iCTQC5lZDXNL0+mWay2GAiEAIACi7iiUC8mDy7zswSonDZHLAwC2OUe0Vi32SQtuWRlT3yfiKJRu6S+1V+U2akKInWQ6FCsW19PKd1Vzw1Si1tM+8r1KMB0HREKhJrNFtpVrpJgs+GZNlWTF6AHdUOyEPzfEKgg5OKq5VUkikfAA+JUZFUPNUvfiOj4VF0-SaNQ3erq+5yW7U2gt2woO3PO9M1N1osFeto+831-2XRnBqxhkhwURwOIAEUWahECDAIgOzHjgtKgXsIQYdCYbBL6XHti4BbTCpkfgPrHMtKbuXVhWL7bLnf1VZa-drg4b9-zj4vG2W4fLqFb-O6IK9pC36mr+w4MiYQA)

### 💻 Code

```ts
interface Foo {
  method(...args: ['a', number] | ['b', string]): void
};

const methodSyntax: Foo = {
  method(kind, payload) {
    if (kind === 'a') {
      payload.toFixed(); // error, Property 'toFixed' does not exist on type 'string | number'
    }
    if (kind === 'b') {
      payload.toUpperCase(); // error, Property 'toUpperCase' does not exist on type 'string | number'
    }
  }
}
```

### 🙁 Actual behavior

Checking `kind` inside the body of `method()` does not narrow `payload` from `string | number`.

### 🙂 Expected behavior

Given #47190, I'd expect `kind === 'a'` to narrow `payload` to `number`, and `kind === 'b'` to narrow `payload` to `string`, which does happen when `method` is a `function` expression:

```ts
const funcExpr: Foo = {
  method: function (kind, payload) {
    if (kind === 'a') {
      payload.toFixed()  // okay
    }
    if (kind === 'b') {
      payload.toUpperCase(); // okay
    }
  }
}
```

And when `method` is an arrow function:

```ts
const arrowFunc: Foo = {
  method: (kind, payload) => {
    if (kind === 'a') {
      payload.toFixed(); // okay
    }
    if (kind === 'b') {
      payload.toUpperCase(); // okay
    }
  }
}
```

And by #46266 when destructured from a rest argument:

```ts
const manualDestructuring: Foo = {
  method(...args) {
    const [kind, payload] = args;
    if (kind === 'a') {
      payload.toFixed(); // okay
    }
    if (kind === 'b') {
      payload.toUpperCase(); // okay
    }
  }
} 
```

I don't know whether this is really a bug or just a follow-up feature request to add to #46658 / #47190.  For context: I [mentioned](https://github.com/microsoft/TypeScript/pull/47190#issuecomment-1057603588) this in #47190, and @Andarist has written a PR for it at #48110.

**Comment by RyanCavanaugh** [comment]
Seems like an oversight
