### ISSUE TITLE
Implicit member resolution for namespaces through a 'using' keyword

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#4816]
Are there plans to support the `using` keyword? In large projects there are usually set of modules called "utils" and it's pretty annoying to write `import foo = utils.foo;` for every used entity.

**Comment by DanielRosenwasser** [comment]
Related to (but not quite quite a duplicate of) #2819.

**Comment by NoelAbrahams** [comment]
Also related to #2956.

**Comment by DanielRosenwasser** [comment]
Thanks @NoelAbrahams! Looks like we should be tracking that there.
