### ISSUE TITLE
Compiler – Semi colon is required when should be optional

### ISSUE THREAD

**Issue by mrctrifork** [microsoft/TypeScript#48176]
# Bug Report

### 🔎 Search Terms

"typescript left side of comma operator is unused and has no side effects"
"typescript property  does not exist on type 'void'"

### 🕗 Version & Regression Information

Not sure, just tried to write a unit-test and stubled upon it. Here's the unit-test:

```typescript
fdescribe('interceptor.utils', () => {
  describe('isAssetUrl', () => {
    [
      ['https://domain.com/base-uri', 'https://domain.com', '/base-uri'],
      ['https://domain.com/base-uri/something/assets', 'https://domain.com', '/base-uri'],
      ['https://domain.com/something/assets', 'https://domain.com', '/'],
    ].forEach(([url, origin, baseUri]) => {
      it(`should return false for '${url}'`, () => {
        expect(isAssetUrl(url, origin, baseUri)).toBeFalse()
      })
    })

    [
      ['https://domain.com/assets', 'https://domain.com', '/'],
      ['https://domain.com/assets', 'https://domain.com', ''],
      ['https://domain.com/base-uri/assets/something', 'https://domain.com', '/base-uri'],
    ].forEach(([url, origin, baseUri]) => {
      it(`should return true for '${url}'`, () => {
        expect(isAssetUrl(url, origin, baseUri)).toBeTrue()
      })
    })
  })
})
```

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/NoRgNATGDMC6B0AzA9gJwKIEMDGALAFNsgHYDOyANgKbwXIDmAlAFCiQwIoY4FFmU06TIA)

### 💻 Code

```ts
[1,2,3].forEach(console.log) // 🙂
```

```ts
 // 🙁
[1,2,3].forEach(console.log)
[1,2,3].forEach(console.log)
```

```ts
// 🙂
[1,2,3].forEach(console.log);
[1,2,3].forEach(console.log)
```

### 🙁 Actual behavior

> Element implicitly has an 'any' type because expression of type '3' can't be used to index type 'void'.
> Property '3' does not exist on type 'void'.
> Left side of comma operator is unused and has no side effects.
> Left side of comma operator is unused and has no side effects.

### 🙂 Expected behavior

To run the code as expected because semi-colons are optional

**Comment by MartinJohns** [comment]
But the error is correct. The semi-colon **is** required there, because of JavaScripts ASI behaviour (automatic semicolon insertion).

Take this exampe:

```typescript
[1]
[0]
```

This will print `1`, because the `[0]` is used to index access the `[1]` value.

**Comment by Josh-Cena** [comment]
If you want to enforce semi-free style, the recommended practice (and [what's practiced by Prettier](https://prettier.io/docs/en/rationale.html#semicolons)) is to put a leading semicolon before any `(` or `[` at the very beginning of a line:

```js
;[1,2,3].forEach(console.log)
;[1,2,3].forEach(console.log)
```

```js
;(() => {
  console.log("foo")
})()
```

**Comment by mrctrifork** [comment]
I guess I wasn't aware that those statements were affected by ASI ¯\_(ツ)_/¯

**Comment by mrctrifork** [comment]
In my editor I did not 🤔
![imagen](https://user-images.githubusercontent.com/45353144/157261731-72eeaea2-3e18-4c16-bedd-f48b43b4c6a6.png)

**Comment by Josh-Cena** [comment]
Maybe an auto backslash insertion hazard?

**Comment by fatcerberus** [comment]
> I guess I wasn't aware that those statements were affected by ASI

IIRC the general rule is, if the statement can be parsed successfully without adding a semicolon, the parser doesn't add one.
