### ISSUE TITLE
@augments not working when class definition doesn't use 'extends' keyword

### ISSUE THREAD

**Issue by akwotom** [microsoft/TypeScript#48177]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.6.2

**Search Terms**
- jsdoc
- javascript
 
---

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.2
- OS Version: Ubuntu 21.10

Steps to Reproduce:

```js
/**
@augments String
*/

export class NormalClass extends Number{

}

/**
@augments String
*/
export class SomeOtherClass {

}

// If you use the classes elsewhere in code, you'll notice that autocomplete for `SomeOtherClass` is lacking string methods
//And that NormalClass is working just fine.
```

**Comment by sandersn** [comment]
`@augments` is intended only for [passing type arguments to base classes that expect them](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#extends). In fact, if you check for errors in the above example with `// @ts-error`, you'll get the error message

"JSDoc `@augments String` does not match the 'extends Number' clause."

When the two mismatch, the compiler provides the instance methods of both as a best effort but that's not the intended usage.

**Comment by stronny** [comment]
So... what do we do instead? Is it impossible to separate a class type from its implementation? 

Using `/**@type {Abstract}*/class Concrete {}` works to an extent, but the extent is very unsatisfactory with how much it fails to check and infer.

```ts
export abstract class Abstract {
  num: number
  str: string
  fn(_: undefined): true
}
```

```js
/** @type {import('types').Abstract} */
class Concrete {
  num = 'invalid' // no error
  constructor() {
    this.str = 123 // okay, alright, this one is working: "Type 'number' is not assignable to type 'string'.ts(2322)"
  }
  fn(x) {throw new Error('mhm')} // no error, also: "Concrete.fn(x: any): void"
}
```

So far the best I could come up with is `@implements {Interface}` and manually typing the properties and methods again, which annoys me to no end. Surely there must be a better solution.
