### ISSUE TITLE
The evaluation of the Keyof Type Operator produces different results to the Pick built-in tool.

### ISSUE THREAD

**Issue by raohongtai** [microsoft/TypeScript#48173]
# Bug Report

### 🔎 Search Terms
Pick

### 🕗 Version & Regression Information
v4.5.4

### ⏯ Playground Link
[Link](https://www.typescriptlang.org/play?ts=4.5.4#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChnIhwC2EA-AFzLphSgDm+yc95VIArsQEbRNwATAVAjp0larQa4AvrlxgAngAcUAMQD2GgDwAVADRpkAXmQBrCIo0xkugHwmcTANoAFZKGQBRAB61EYNqohhZWNvYAulS6bhGy8goqKABCcFB6+qjGoda2DqYAShAAjhzAIgLarsAIZhneflABQSGWufZ2dglKqshF6I6aOhjQhgDkRKRjDgQEAPRzkxBUNHQg9MgAPsgcIAIQMKAQAgDcib39AEyOqekjUONL07MLSytS60A)

### 💻 Code
```lang=ts
interface User {
  name?: string
  age?: number
  address?: string
}

type Foo<T, U = keyof T> = {
  [P in Extract<U, keyof T>]: T[P]
}

type Bar<T,U=keyof T> = Required<Pick<T, Extract<U, keyof T>>>

type Res = Foo<User, 'name'>     //name: string | undefined;
type Res2 = Bar<User, 'name'>   //name: string
```

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior
```
type Res = Foo<User, 'name'>     //name: string | undefined;
```
The value evaluated for the name contains undefined

### 🙂 Expected behavior

```
type Foo<T, U = keyof T> = {
  [P in Extract<U, keyof T>]: T[P]
}
```
[P in Extract<U, keyof T>]: T[P]   should not return undefined because  Extract only narrows down the range of the keys

**Comment by jcalz** [comment]
I don’t see a bug here.  The type  `User["name"]` is `string | undefined`, so that’s the type of the `name` property of `Foo<User, "name">`.  Homomorphic mapped types and mapped type modifiers can complicate this, but neither of those are happening in `Foo`.

**Comment by fatcerberus** [comment]
`User["name"]` evaluates to `string | undefined` because the property is optional.  `-?` removes optionality in the new type, but this is separate from the evaluation of `T[P]`, so you end up with `name: string | undefined`.  You might consider `NonNullable<T[P]>`.

**Comment by ben-lau** [comment]
But there is another question: I think the `?` symbol means this property is optional. So in this case, the `name` which is the keyof `Users` should be optional, but if you have this property , it has to be `string` not `undefined` as well.

**Comment by ben-lau** [comment]
> But there is another question: I think the `?` symbol means this property is optional. So in this case, the `name` which is the keyof `Users` should be optional, but if you got this property , it has to be `string` not `undefined` as well.

**Comment by jcalz** [comment]
If you have a value `u` of type `User`, then in `const n = u.name`, the type of `n` is `string | undefined`.  That's just how it works. Whether or not the key is *present* vs *absent* and whether or not you can actually *write* `undefined` to `u.name` has to do with [`--exactOptionalPropertyTypes`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#exact-optional-property-types---exactoptionalpropertytypes) (#43947) but that doesn't change things here.

**Comment by ben-lau** [comment]
All right, I missed this, thanks.
