### ISSUE TITLE
[JSDoc] @type import would be overridden with namespace of the same name

### ISSUE THREAD

**Issue by Thaina** [microsoft/TypeScript#48181]
# Bug Report

### 🔎 Search Terms

JSDoc "export as namespace" / JSDoc "import default" namespace

### 🕗 Version & Regression Information

 4.6.2 + 4.7.0-dev.20220309

### ⏯ Playground Link

It happen in vscode intellisense

### 💻 Code

```npm
npm install firebase
```

```js
/** @type {typeof import("firebase/compat/app").default}*/
var firebase;
```

### 🙁 Actual behavior

Intellisense still use namespace

![image](https://user-images.githubusercontent.com/1042507/157405695-81d8eea6-4de2-47ab-aa09-3d3d6177816b.png)

### 🙂 Expected behavior

By changing the `export namespace` of the `node_modules\firebase\compat\index.d.ts` from 

![image](https://user-images.githubusercontent.com/1042507/157405069-7f07dfc1-d541-461a-86bd-72df24c13450.png)

into

![image](https://user-images.githubusercontent.com/1042507/157405331-d080676a-8252-4b62-b196-09301c577b5a.png)

The autocomplete will work as expected

![image](https://user-images.githubusercontent.com/1042507/157404762-db4917ab-c8f4-4223-a84f-d6347706d140.png)

### ps

I don't know if this was limitation of typescript import system and it was caused by firebase team or I have done anything wrong but I was expected that my direct jsdoc `@type`  should take precedence in declaring variable, or let us import namespace directly

**Comment by sandersn** [comment]
My first attempt to repro this failed in a file that was part of a tsconfig with checkJs on. In a standalone file, the incorrect suggestion disappears with `// @ts-check` is added, and `firebase.default` shows an error on `default`. I think this is a bug in completions only, not in Javascript name resolution.

**Comment by sandersn** [comment]
The fact that completions contain `default` in the bug is a result of default JS handling, which adds all identifiers from the file as low-priority entries. That's the way it's supposed to work, though, and it's known to be incorrect.

You can turn this off by adding `// @ts-check` to the top of your file, or adding a tsconfig.json with `checkJs: true`. But then typescript will add errors all over your JS file, which may not be what you want either.

**Comment by Thaina** [comment]
@sandersn event with `// @ts-check` it still not working and only make error in my code

![image](https://user-images.githubusercontent.com/1042507/197684630-cd251455-44aa-4e97-88f1-b81f229f67c9.png)

Could you have any kind of workaround for this case or else the firebase compat, which is the package that very needed intellisense, would render the vscode ts autocomplete virtually useless

**Comment by sandersn** [comment]
I'll take another look.

**Comment by sandersn** [comment]
I'm trying again to repro this and my results are still different from yours.

1. No error on `var firebase`. What is that error?
2. Many more completions available on firebase.
3. `default` is only present without `ts-check`.

Here is what I did:

```
$ npm init -y
$ npm i firebase
$ touch index.js
```

then I open index.js in emacs and type

```js
// @ts-check
/** @type {typeof import("firebase/compat/app").default} */
var fbase;
fbase
```

That gives me firebase@9.17.1, although I tried 9.0.0 and got the same results; 8 gave me an error saying that 'firebase/compat/app' wasn't found.

**Comment by Thaina** [comment]
> I'm trying again to repro this and my results are still different from yours.
> 
> 1. No error on `var firebase`. What is that error?
> 2. Many more completions available on firebase.
> 3. `default` is only present without `ts-check`.
> 
> Here is what I did:
> 
> ```
> $ npm init -y
> $ npm i firebase
> $ touch index.js
> ```
> 
> then I open index.js in emacs and type
> 
> ```js
> // @ts-check
> /** @type {typeof import("firebase/compat/app").default} */
> var fbase;
> fbase
> ```
> 
> That gives me firebase@9.17.1, although I tried 9.0.0 and got the same results; 8 gave me an error saying that 'firebase/compat/app' wasn't found.

Surely, rename the variable to `fbase` or anything make it work as it should

**But** name the variable as `firebase` will **make it _not_ work as it should**

This is current behaviour

![image](https://user-images.githubusercontent.com/1042507/216892072-5384e809-e5bf-4063-81f1-c90cdb0a2346.png)

**This** is expected behaviour

![image](https://user-images.githubusercontent.com/1042507/216892246-4419bc13-6c25-4869-b20d-29be42cb939f.png)

This is error with `// @ts-check`

![image](https://user-images.githubusercontent.com/1042507/216892347-fc9778dd-36c5-4bc4-ace8-560b5ff7a379.png)

**Comment by sandersn** [comment]
Thanks for pointing out that the variable name must be `firebase`. Starting from the error you showed, I was able to figure out that the problem is that firebase declares a global named `firebase` already. You can find it if you find-all-references on `var firebase`. There is a `export as namespace firebase` in firebase/compat/index.d.ts.

Unfortunately, referencing firebase/compat/app pulls this declaration into your compilation, because they're declared in the same file (`app` is declared as `declare namespace firebase.app`) Once there's a conflict, typescript treats `firebase` as having the error type and falls back to identifier completions like `default`.

**Comment by Thaina** [comment]
First problem. That `index.d.ts` was made from firebase team and it seem working normally in typescript file. Why it not working in js ?

Second problem. if declare the same name will make it error, how can we possibly import that index file into js properly? Are there any other way we could declare `firebase` variable as that type?

**Comment by Thaina** [comment]
The problem is the actual code to access it is `firebase.analytics` not `firebase.default.analytics`

As you can see from my above comment's first image. The `default` field exist there alright, but that's not correct property path of firebase.

What I have speculate is `export as namespace firebase` is actually merge the type and namespace together to it could access both type declare in namespace and property declare in type

As you can see, in the typescript file, not only it it don't make any error, the intellisense are showing autocomplete correctly

![image](https://user-images.githubusercontent.com/1042507/217308949-a7a38a33-5e7a-4cc8-8fde-07f809074fda.png)

Which make me wonder if javascript can import type definition from `d.ts` with typescript language server, why it don't work like typescript

**Comment by sandersn** [comment]
Have you tried writing `import firebase from "firebase/compat";` in JS? It should work.

If your non-module usage is correct, then firebase's `export as namespace firebase` is incorrect. It will gather all exports in index.d.ts into an object and call that `firebase`. Unfortunately, that includes the `default` property created by `export default firebase`. The default export should actually be `export = firebase`.

**Comment by Thaina** [comment]
It work as an intellisense in ide but my js file is not a module so `import` have made error in runtime

And so I have tried to workaround with `/** @type {import("firebase/compat")} */` `/** @type {typeof import("firebase/compat")} */` and any combination possible, nothing work as it should

Especially

```js
/** @type {typeof import("firebase/compat").default} */
var firebase;
```

When adding `.default` here it was clear intention that I want the variable named firebase be forced overridden. The js compiler should take priority to force the type over this variable and ignore the unnecessary ts conflict
