### ISSUE TITLE
Parameters type loses names with object params

### ISSUE THREAD

**Issue by aphex** [microsoft/TypeScript#48185]
# Bug Report

### 🔎 Search Terms

Paramaters, object, named parameters

### 🕗 Version & Regression Information
4.6.2, though likely nor introduced here

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcDqcBOBrGYDmAFAB4BciYIAtgEYCmmANIgJ7mW0MCUiA3gLAAoIQF8hoSLATJUJdtXpNW8zkt6IAXohHl1GgPzkAzlEx582xAF4+IngOGCxjgPQvCABwCGmL1TpQ3Ihe5ADaZBQKDMxskaoAuuLg0PBIND4YOOaEAHR5IYgACj5+AQxGADxQLB50cMAy6Fi4BAB89s5CboieJf6BmDwFoRyKzKPRPQ7diLMGxqbmiAA+iOAAJnTAeHTrANxdLparG1s761z6iYISKdLpmLn55MW+-eVVNXUNKHDttkA

### 💻 Code
```ts
function fooWorking(x: number, y: number) { }
function foo(x: number, y: number, { z }: { z?: string } = {}) { }

//(parameter) a: [x: number, y: number]
function barWorking(...a: Parameters<typeof fooWorking>) {}

// (parameter) a: [number, number, ({
//    z?: string | undefined;
// } | undefined)?]
function bar(...a: Parameters<typeof foo>) {}
```

### 🙁 Actual behavior

bar function is not able to resolve x and y parameter names. This causes the bar function to be type
```ts
(a_0: number, a_1: number)
```

### 🙂 Expected behavior

bar function should be able to resolve the x and y parameter names.

**Comment by fatcerberus** [comment]
Seems similar to https://github.com/microsoft/TypeScript/issues/48049, note this comment:

> The short answer is that the parameter -> tuple name feature is "best effort" (since nothing in the type system works/doesn't work depending on these names), and the effort to handle this particular case simply hasn't been done yet
