### ISSUE TITLE
Use constructor arguments in class field definitions 

### ISSUE THREAD

**Issue by maxwrlr** [microsoft/TypeScript#48184]
# Bug Report

### 🔎 Search Terms

use constructor arguments in class field definitions 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about constructor arguments

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XQGYHtPQLzQCMwAnAbhTWEwDsIAXYgV2Ds2IAoji9oByLTLwCUiCqgC+ScUA)

### 💻 Code

```ts
class A {
    foo = bar;
    constructor(bar = 'foo') {
    }
}
```

### 🙁 Actual behavior

TypeScript reports an error:
```
Cannot find name 'bar'. 'bar' is declared but its value is never read.
```

This might seem right at first, but let's look at the produced JavaScript, which is perfectly valid:
```js
"use strict";
class A {
    constructor(bar = 'foo') {
        this.foo = bar;
    }
}
```

### 🙂 Expected behavior

It would be nice to use constructor arguments in the class field definitions so that constructor arguments don't have to be stored in fields, that they can be used in the field definitions without separating declaration and definition.

I am not sure if this is by design or a hacky bug, but I couldn't find any situations like that anywhere.

**Comment by Josh-Cena** [comment]
This is against JS semantics, because this code is directly runnable in JS.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/55398995/157450640-7b307c65-bb77-41da-892f-44320f8504f3.png">

**Comment by MartinJohns** [comment]
> This might seem right at first, but let's look at the produced JavaScript, which is perfectly valid:

This is only the case because you're using the old-style fields. With newer ECMAScript versions (or `useDefineForClassFields` enabled) the produced JavaScript will be:

```typescript
class A {
    foo = bar;
    constructor(bar = 'foo') {
    }
}

```

**Comment by maxwrlr** [comment]
Hm 😕, I didn't consider the newer ECMAScript. It's kind of disappointing.
I honestly prefer a hacky yet small `@ts-ignore` over the alternatives in my scenario.

Especially with these circumstances, I guess there is no point in keeping this issue open?

**Comment by Josh-Cena** [comment]
It's always better to think in terms of the written code instead of the compiled results. The compiled JS makes sense, but your example doesn't, because the `bar` in `foo = bar` is certainly unbound from its scope.

**Comment by maxwrlr** [comment]
Generally speaking, I agree with you and close the issue.
Practically speaking, I'm gonna keep on using the hack when it reduces the number of lines drastically.

**Comment by MartinJohns** [comment]
If the property and argument name are the same and you're not using #fields, then you can use this syntax:

```typescript
class A {
    constructor(private bar = 'foo', public mep = 5) {}
}
```

This will make your class have a `private` field `bar` and a `public` field `mep`, with the constructor arguments assigned.

But this syntax is explicitly not supported for #fields.

**Comment by maxwrlr** [comment]
Thanks for the tip, but my case I actualy do not wan't to keep the constructor argument, I just need it for initialization.

My real use case is like so:

```ts
class Database {
    // @ts-ignore: Use the constructor argument
    private sequelize = new Sequelize(connectString);

    readonly this.Model1 = this.sequelize.define(...);
    readonly this.Model2 = this.sequelize.define(...);
    readonly this.Model3 = this.sequelize.define(...);
    ....

    constructor(connectString: string) {}
}
```
