### ISSUE TITLE
New option for `typescript.preferences.importModuleSpecifier` to use relative only if path starts with `./`

### ISSUE THREAD

**Issue by AlbertoSadoc** [microsoft/TypeScript#48192]
I would like an option to import modules using always non-relative urls except if it can be a relative url starting with `./`.

`non-relative` is great to show the full path the file is referenced, specially if the relative path have several `../` path segments. `shortest` still can show several `../` path segments if relative path is shorter than the non-relative path. This new option will avoid `../` at all costs but can use relative if the file is located under the same folder of the current file.

An extra option would be to also allow one single `../` as it is going up the path just once which it is not very confusing either.

**Comment by laverdet** [comment]
+1 as described is exactly what I'd like as well.

`shortest` is currently the best we have. TypeScript has good support for [self-referencing packages](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) but we have to choose between either always using full references [`non-relative`] or an unreliable sometimes-relative sometimes-absolute hybrid [`shortest`].

**Comment by dmitri-gb** [comment]
Duplicate pf https://github.com/microsoft/TypeScript/issues/45015.
