### ISSUE TITLE
Add option for navto to exclude built-in libs and files from node_modules

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#48194]
# Feature request

### 🔎 Search Terms
- navto
- go to symbol in workspace
- tsserver

### Request
Currently `navto` includes all known symbols in a project. This include both symbols from the stdlib and from `node_modules`. However the most common use case for `navto` in my experience is jumping to another symbol within my code. 

I propose we add new options to `navto` that let us exclude:

- Symbols from the standard library
- Any symbols from `node_modules`

This could be exposed as either a single new option on the request that's called something like `justMyCode`, or as two separate options for more fine grained control. In either case, we would expose the option(s) to users in the VS Code settings UI

Extracted https://github.com/microsoft/vscode/issues/46718 as the most common use case there seems to be excluding files under `node_modules`

**Comment by RyanCavanaugh** [comment]
Let's talk next week about how this might be handled
