### ISSUE TITLE
`Promise.resolve` fails to infer the correct type when the argument is a union type like `T | Promise<T> | PromiseLike<T>`

### ISSUE THREAD

**Issue by nahcikuy** [microsoft/TypeScript#48195]
# Bug Report

### 🔎 Search Terms

- Promise.resolve
- PromiseLike
- Union Type

### 🕗 Version & Regression Information

- This changed between versions 3.5.1 and 3.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/GYVwdgxgLglg9mABMAjACgB4C5FhAWwCMBTAJwEoc8izEAfRABVLnxgGdiAeak0gPkQBvAFCJEpYlBCkkzVh2IA6SezgAbAG7FM5ANwiAviJGhIsBMgBMmKgT6Vc92g3ltOAGRgBrbrzKCouKS0rJMLO7KqhraugbGpuDQ8EjAAMy2TjQUdtn04QqcPM4C+W6KXr7F2YFiElIychGKKsRqWjoY+kYmEAjsUIgA5ig45UX+pQC8BZGt7bGoaAAsVuTdfWADw1ZjzRMlgjPjUW0xOsA2q+sGm9tDaXuFfoeIx-unCxcZ191AA)

### 💻 Code

```typescript
function f1(x: number): number | Promise<number> {
  return Promise.resolve(x);
}

function f2(x: number): number | PromiseLike<number> {
  return Promise.resolve(x);
}

function f3(x: number): number | Promise<number> | PromiseLike<number> {
  return Promise.resolve(x);
}

const g1: Promise<number> = Promise.resolve(f1(42)); //OK
const g2: Promise<number> = Promise.resolve(f2(42)); //OK
const g3: Promise<number> = Promise.resolve(f3(42)); //Fails
```

### 🙁 Actual behavior

The variable `g3` fails the type check with the following error
> Type 'Promise\<number | Promise\<number>>' is not assignable to type 'Promise\<number>'.
> Type 'number | Promise\<number>' is not assignable to type 'number'.
> Type 'Promise\<number>' is not assignable to type 'number'.

Here, `g3` is infered to the type `Promise<number | Promise<number>>`. However, comparing to the behavior on `g1` and `g2`, this seems to be a bug, which should be `Promise<number>` instead.

### 🙂 Expected behavior

No error.

**Comment by weswigham** [comment]
https://github.com/microsoft/TypeScript/pull/37615
