### ISSUE TITLE
TypeScript doesn't understand that array shift mutates the values of array from initialization

### ISSUE THREAD

**Issue by workinggrafton** [microsoft/TypeScript#48204]
# Bug Report
TypeScript doesn't understand that array shift mutates the values of the array.

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDA2gRgDQwExYMwC6A3AFAkCWAZjABRwoAMBSiyaAlDAN4kzwB0EABZUoNdqT5Va9Ji2TZOPPn1CQQAGwCm-DSADmNAOQgA1kYm8YAXxLWgA

### 🔎 Search Terms
Array
shift
unshift

### 🕗 Version & Regression Information
Happens on nightly, currently failing on 4.7.0 also.

### ⏯ Playground Link
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDA2gRgDQwExYMwC6A3AFAkCWAZjABRwoAMBSiyaAlDAN4kzwB0EABZUoNdqT5Va9Ji2TZOPPn1CQQAGwCm-DSADmNAOQgA1kYm8YAXxLWgA

### 💻 Code
```ts
const x: number[] = [1, 2, 3];
if (x[0] === 1) {
  x.shift();
  if (x[0] === 2) {    // <--- Error here.
    console.log('ok');
  }
}
```

### 🙁 Actual behavior
Error evaluating x[0] after a shift. TypeScript thinks array values are fixed to the values from initialization.

### 🙂 Expected behavior
Error evaluating x[0] is typed as 'number', not a numeric literal (i.e. no error in example, console statement is reachable and prints).

**Comment by fatcerberus** [comment]
#9998
