### ISSUE TITLE
lib.es2022: `hasOwn` appears to be defined on `Object` prototype rather than on constructor

### ISSUE THREAD

**Issue by lediur** [microsoft/TypeScript#48206]
# Bug Report

### 🔎 Search Terms

hasOwn, Object.hasOwn, es2022, prototype, lib.es2022.object.d.ts

### 🕗 Version & Regression Information

- This changed between versions 4.2.4 and 4.6.2

Appears to be introduced by https://github.com/microsoft/TypeScript/pull/46291

### ⏯ Playground Link

Doesn't appear to reproduce on Playground or Bug Workbench, reproduces in VS Code 1.66.0-insider (e80a0ca648fe9bef07070e4f7fb04e67f2243252) running TypeScript 4.6.2.

### 💻 Code

```ts
interface SomeComponentProps {
  requiredProp: boolean
  hasOwn?: boolean;
}

const SomeComponent: React.FC<SomeComponentProps> = () => {}

return <SomeComponent requiredProp />
```

### 🙁 Actual behavior

I ran into this issue because I was trying to upgrade the project from 4.3.5 to 4.6.2. The project has some object types with `hasOwn` as a boolean property.

```
// TS2322: Type '{ requiredProp: boolean }' is not assignable to type 'SomeComponentProps'.
  Types of property 'hasOwn' are incompatible.
    Type '(o: object, v: PropertyKey) => boolean' is not assignable to type 'boolean'.
```

### 🙂 Expected behavior

`hasOwn` should be a method of the `Object` constructor (`Object.hasOwn`), not the prototype (`foo.hasOwn`).

**Comment by RyanCavanaugh** [comment]
This is an intended UX trade-off in JS files. Since often you'll have untyped variables, we show method help based on name-matching; this way if you're looking for help for a common method name, it shows up even without matching type information. 

For more precise behavior, you can turn on `checkJs`.

See also #33565

**Comment by lediur** [comment]
Thanks for the reply! I'm seeing this in a TypeScript file in a TypeScript project. Does the same behavior apply?

**Comment by lediur** [comment]
I ran into this issue because I was trying to upgrade the project from 4.2.4 to 4.6.2. The project has some object types with `hasOwn` as a boolean property.

e.g.

```ts
interface SomeComponentProps {
  requiredProp: boolean
  hasOwn?: boolean;
}
```

Using those types started failing to typecheck after the upgrade since TypeScript. For example:

```ts
const SomeComponent: React.FC<SomeComponentProps> = () => {}

return <SomeComponent requiredProp />
// TS2322: Type '{ requiredProp: boolean }' is not assignable to type 'SomeComponentProps'.
  Types of property 'hasOwn' are incompatible.
    Type '(o: object, v: PropertyKey) => boolean' is not assignable to type 'boolean'.
```

**Comment by RyanCavanaugh** [comment]
No, you're totally right, this is just the lib being wrong. Misread what you were getting at.

**Comment by lediur** [comment]
No problem! I should've provided the more specific error case up front.

**Comment by lediur** [comment]
I'm happy to make a PR with test cases for the new change, though it might take me a bit longer since I haven't contributed to TypeScript before. If you'd like to fix this internally that's fine by me.

**Comment by RyanCavanaugh** [comment]
I'll put up a PR. Thanks for the report 👍

**Comment by lediur** [comment]
Do you know if or when this might land in a patch version?
