### ISSUE TITLE
Narrowing doesn't work with constant-named properties

### ISSUE THREAD

**Issue by jluxenberg** [microsoft/TypeScript#48203]
# Bug Report

### 🔎 Search Terms

narrowing, constant-named properties, computed property names

### 🕗 Version & Regression Information

3.3.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "common bugs that aren't bugs"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3#code/PTAEBcAsEsGdQCYHsCmsB2BycoDuSAnAawCgAzAV3QGNxol1R0lwB9fY6dAc1dnAJdeAG2jgUBAIbCAFAEpQAbxKhVoag36hWZJElABeUJh17MAbhIq14AJ4AHFKABiew0tCTQALiYUAtgBGEqAAvpZqEA5OAEKSBO6KoADapkgAugD8vq764VaRGuhagfG+cQlGSam6Gb5Jkr4AjGFhltaq0GQypQQ1eukKvf0ZAHReRgDMlqFWIBAw8MhoeISklDR0DKucPHwCQqyi4lKyCsqFmjhp7ia1Fh1Rji5uVZ4+fkEh+ZF2zxWJFJpLI5Nz5R5FEplUAAt4jdL1TzNVrgyJdHrxZJ3MyDUDDbFITDpcbuaYkWYkeZQOCeYSwfTLDDYHbrKi0eiMZhsDhEQ5UaAARwoKD4tiCSDp8iUEKu2lq7gAymLAhKZATMHJ2r9oi99G8vL50AFggkfjYdbCPPDsrq2gU1JCcL1yvFAfDEY1QC1QnbHujhsChpjgSSpjMrEA)

### 💻 Code

```ts
// this doesn't work
function not_working_string_literal() {
    const _foo = '_foo';

    type Foo = { a : number };
    type Bar = { [_foo]?: Foo };

    const bar: Bar = { [_foo]: { a: 1 } };

    if(bar[_foo]) bar[_foo].a = 3;
}

// this does work
function working_string_literal() {
    const _foo = '_foo';
    type Foo = { a : number };
    type Bar = { [_foo]?: Foo };

    const bar: Bar = { [_foo]: { a: 1 } };

    if(bar['_foo']) bar['_foo'].a = 3;
}

// this also doesn't work
function not_working_unique_symbols() {
    const _foo = Symbol('_foo');

    type Foo = { a : number };
    type Bar = { [_foo]?: Foo };

    const bar: Bar = { [_foo]: { a: 1 } };

    if(bar[_foo]) bar[_foo].a = 3;
}
```

### 🙁 Actual behavior

Line 10 fails to type check with the error:
```
Object is possibly 'undefined'.
```

### 🙂 Expected behavior

I expect the narrowing `if(bar[_foo])` to remove the possibility that `bar[_foo]` is undefined inside the body of the if statement.

**Comment by RyanCavanaugh** [comment]
Duplicate e.g. #48035
