### ISSUE TITLE
Getting the parameters of a constructor `Parameters<MyClass["constructor"]>`

### ISSUE THREAD

**Issue by formula1** [microsoft/TypeScript#48205]
# Suggestion

## 🔍 Search Terms

Parameters, Class, Function, typescript, static, instance

## ✅ Viability Checklist

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code (It might, though I don't think people are using untyped functions]
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). (I don't feel like looking at the design goals

## ⭐ Suggestion

Right now, you can get the parameters of a function with `Paramaters<myFunction>`.
However, `MyClass["constructor"]` seems to return an untyped `Function`. Thus `Paramaters` doesn't know how to handle it.
Not only would I like the constructor to be able to be typed but all static and instance functions as well.

## 📃 Motivating Example

```typescript

class A {
  constructor(a: void, b: void, c: void, d: void}{}
}

class B {
  constructor(a: boolean, b: boolean, c: boolean, d: boolean}{}
}

class C {
  constructor(a: number, b: number, c: number, d: number}{}
}

class D {
  constructor(a: ArrayBuffer, b: ArrayBuffer c: ArrayBuffer, d: ArrayBuffer}{}
}


function createABunchOfClasses(
{ aArgs, bArgs, cArgs, dArgs }: {
  aArgs: Parameters<A["constructor"]>,
  bArgs: Parameters<B["constructor"]>,
  cArgs: Parameters<C["constructor"]>,
  dArgs: Parameters<D["constructor"]>,
}){
  return {
    a: new A(...aArgs), b: new B(...bArgs), c: new C(...cArgs), d: new D(...dArgs),
  }
}

```

## 💻 Use Cases

When creating servers, At times the index.ts will have a bunch of parameters regarding database clients like redis or mongodb. Arguably these can just be in their own function, however it would be nice to know from the top down where args for each client are coming from. Thus, parameters are defined and everything gets passed down to where they are actually needed.

**Comment by RyanCavanaugh** [comment]
`A["constructor"]` refers to the type of the `constructor` property of an *instance* of `A`. The type you're looking for is written `ConstructorParameters<typeof A>`

**Comment by formula1** [comment]
Thankyou
