### ISSUE TITLE
VS Community doesn't read tsconfig.json

### ISSUE THREAD

**Issue by mechanicious** [Microsoft/TypeScript#4820]
The project is created from the default Typescript Web Application template, I've created `tsconfig.json`; it wans't included in the default project template. I am trying to get [this](http://stackoverflow.com/questions/32380131/how-do-i-use-typescript-1-6-with-visual-studio-code-to-get-generators-support) working.

Visual Studio version:
![](http://i.imgur.com/Ivi6JGX.png)

This is my `tsconfig.json` file:
```json
{
    "compilerOptions": {
        "target": "ES5",
        "module": "amd",
        "sourceMap": true
    },
    "exclude": [
        "node_modules",
        ".vscode"
    ]
}
```

See:
![](http://i.imgur.com/esrosQJ.png)

**Comment by mechanicious** [comment]
I've switched to [Webstorm 11 EAP](http://blog.jetbrains.com/webstorm/2015/07/webstorm-11-early-access-program/) which integrates TypeScript seamlessly.

**Comment by mhegazy** [comment]
This is the intended behavior. a project file supersedes a tsconfig. if you do not want the project file to be your source of project information, close the project, and open any ts file from your project, and it will be pick up the tsconfig. 

In the next release we intend to make this configurable. see #3949.

**Comment by mechanicious** [comment]
The user doesn't expect it at all, VS should alert that the settings have been overwritten with a configuration from a source with a higher priority.

**Comment by mhegazy** [comment]
> VS should alert that the settings have been overwritten by a configuration 

this is a good idea. reactivating.

**Comment by paulvanbrenk** [comment]
Support for multiple tsconfig.json files is part of 1.8, as is support for more project types.
