### ISSUE TITLE
Interface + enum = keymapper type

### ISSUE THREAD

**Issue by rip222** [microsoft/TypeScript#48216]
# Suggestion

Define your keymap like so:
```
keymapper MyForm {
   id = 'rndobjid',
   name = 'rndobjnm',
  ...
}
```

And this
```
const myForm: MyForm = {
   id: '123',
   name: 'John Doe'
}
```
Compiles to this
```
const myForm = {
   rndobjid: '123',
   rndobjnm: 'John Doe'
}
```

## 🔍 Search Terms

- [`interface type`](https://github.com/microsoft/TypeScript/issues?q=interface+type)

## ✅ Viability Checklist

My suggestion meets these guidelines:

✅ This wouldn't be a breaking change in existing TypeScript/JavaScript code
✅ This wouldn't change the runtime behavior of existing JavaScript code
❌ This could be implemented without emitting different JS based on the types of the expressions
✅ This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
✅ This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example
I've been working with forms where field names are autogenerated on the backend, and most of the time I've had to deal with them somehow on the frontend. To ensure strictness I've had to employ interfaces and types like so:
```
interface MyObj {
  /** Customer Name */
  cmpccavdtdtc1: string;
  /** Prepaid */
  cmpccavdtdtc2: string;
  /** Open State */
  cmpccavdtdtc3: string;
  /** Pulled State */
  cmpccavdtdtc4: string;
  /** Closed State */
  cmpccavdtdtc5: string;
  /** Open Credit */
  cmpccavdtdtc6: string;
  /** Credit Limit */
  cmpccavdtdtc7: string;
}
```

It's become very tedius and unreadable over time. 

I've used enums as a workaround for this problem like this:
```
export const enum GridColumn {
  ProductId = 'objprfvpdpname',
  ProductName = 'objprfvpdprname',
  Category = 'objprfvpdcat',
  Distributor='objdifvdsdtd',
  ...
}
```
Cons of enums:
* they are, unlike interfaces and types, compiled to javascript which increase the bundle size and big projects
* extremely verbose and annoying to type

So the primary reason for this feature is having the option of defining concise and friendly names in obscure objects. Sort of like interface + enum with superpowers

**Comment by RyanCavanaugh** [comment]
This violates an inviolable design goal:

> This could be implemented without emitting different JS based on the types of the expressions

**Comment by nmain** [comment]
Practically speaking, your best bet may be to tap into the logic that autogenerates your backend field names and use it to autogenerate mapping functions that turn  `objprfvpdpname` spaghetti into reasonably named objects, and vice versa.

**Comment by fatcerberus** [comment]
> `objprfvpdpname` spaghetti

what the pfargtl?
