### ISSUE TITLE
Support safe dereferencement operators

### ISSUE THREAD

**Issue by Fruneau** [Microsoft/TypeScript#4821]
Languages such as C# and more recently Swift have introduced a safe dereferencement operator that let write much simpler code in cases where a field may be nullable.

It would help improve the expressiveness of the language and play nice with the existing notion of optional member/parameter to have such operators supported in typescript.

    let c = a?.b;

would be equivalent to

    let c : typeof a.b;

    if (a !== undefined) {
        c = a.b;
    }

Identically, on the left side of the expression

    a?.b = c;

would be rewritten to something like

    if (a !== undefined) {
        a.b = c;
    }

**Comment by DanielRosenwasser** [comment]
Thanks for filing @Fruneau, we have an issue tracking this at #16.
