### ISSUE TITLE
`Intl.DisplayNames` options object type needs to be split

### ISSUE THREAD

**Issue by tchetwin** [microsoft/TypeScript#48218]
# Bug Report

### 🔎 Search Terms

DisplayNames, Intl, locale

### 🕗 Version & Regression Information

The behaviour was altered in TypeScript 4.6.2, but it was differently incorrect prior to that:

- Originally introduced in https://github.com/microsoft/TypeScript/pull/45647, merged 8th Sep -> 4.5 (probably)
- An Issue reported in https://github.com/microsoft/TypeScript/issues/46845, resulted in https://github.com/microsoft/TypeScript/pull/46849, merged 3rd Jan -> 4.6

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBAJgSwgBwDYEMCeA5dBbAUwHlkoFwIAuGABXQCcz1UAeASTClQDoARJNFlyEIJMhQB8MALwwA3gCgYymFEzIC1AEQYwAcwCu6PQS0AaJSoD0VmAAEoEALQEAHhuBQX9eiHownVQALJBgIIJADVDgYMBBYACMCGAA3ZgQ4bhgAFSDkgEEaNjCCAjwIVRBK1AJ6dChkt2ACCArkXw1GBBbLZVQQYGZNGC0CMCcAcQAhcwUAXwBuBQUa2AQZWIIAdxgOLj4BDBx8FoAKAG0tKHotAF0zeEOhE7FySABKJYVQSFh6FpAqBSBDgrwoGwQ3H+EEBwNBpDeEFOn2+FEBBG4-T0p2hsJBYI+CxgNhg7QQnAq6DAMBACQAVgRPDAflB0OTyXoYAADfqDGpch5c6CYfmCtQaAXcgBmzFQCXQwAA1pKeVTDMYCPwUEcucsSblQuFItEYElUuk4ApcUD8QiKJi1UYTFrBJgviSHM43B4vLVfP5AlAQhUjVEYnFEsk0qgMqjfjBecwALL1YB5fyya1wgkQTEDIYpqBp2pLH4wmp57GJ1CF4v0T7E2xkincgxgOAEKXkkG6oA)

### 💻 Code

```ts
const displayNameOptions: Partial<Intl.DisplayNamesOptions> = {
    type: "language",
    // @ts-expect-error - this should *not* be valid. The Intl API seems to cope with excess properties
    locale: "en-GB",
};

const i = new Intl.DisplayNames(["tr"], displayNameOptions);

const resolvedOptions = i.resolvedOptions();
console.log(resolvedOptions); // prints an object containing `locale`, `style`, `type`, `fallback`, `languageDisplay`

// This should be valid
resolvedOptions.languageDisplay;

// @ts-expect-error - this should not be valid
const localMatcher = resolvedOptions.localeMatcher;
console.log(localMatcher); // prints `undefined`
```

### 🙁 Actual behavior

Type errors in the above code for valid patterns, no type errors for invalid patterns.

### 🙂 Expected behavior

Only valid type errors, accurate representation of the API

### Notes

The `DisplayNamesOptions` `interface`:
https://github.com/microsoft/TypeScript/blob/a4f5555e09862d442185c09cb0b0630f6c06fbd0/src/lib/es2020.intl.d.ts#L294-L300

...is currently shared by [`Intl.DisplayNames()` constructor](https://github.com/microsoft/TypeScript/blob/a4f5555e09862d442185c09cb0b0630f6c06fbd0/src/lib/es2020.intl.d.ts#L346), and [`Intl.DisplayNames.prototype.resolvedOptions()`](https://github.com/microsoft/TypeScript/blob/a4f5555e09862d442185c09cb0b0630f6c06fbd0/src/lib/es2020.intl.d.ts#L325). While the underlying objects share several properties, they are not a perfect match as the types suggest.

Per MDN:
* [`Intl.DisplayNames()` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames#syntax) should accept an object with (`Partial<>`):
  * `localeMatcher`
  * `style`
  * `type`
  * `languageDisplay`
  * `fallback`
* [`Intl.DisplayNames.prototype.resolvedOptions()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/resolvedOptions#description) should return an object with:
  * `locale`
  * `style`
  * `type`
  * `fallback`

ECMA-402 links:
* [`Intl.DisplayNames()` constructor](https://tc39.es/ecma402/#sec-Intl.DisplayNames)
* [`Intl.DisplayNames.prototype.resolvedOptions()`](https://tc39.es/ecma402/#sec-Intl.DisplayNames.prototype.resolvedOptions)

Shoutout to @mkubilayk who spotted this during our TypeScript update!

### Suggested Fix

These types are not compatible, suggesting they should be split into something like (bikeshed) `DisplayNamesOptions` and `DisplayNamesResolvedOptions`.

Probably a _Good First Issue™_

**Comment by gfyoung** [comment]
Thanks @tchetwin for filing this: just opened a PR to update these.
