### ISSUE TITLE
Module augmentation should be ignored during `import type` (maybe?)

### ISSUE THREAD

**Issue by thw0rted** [microsoft/TypeScript#48222]
# Bug Report

### 🔎 Search Terms

"import type" module augmentation declare

### 🕗 Version & Regression Information

- I was unable to test this on prior versions using Playground/Bug Workbench because the behavior involves imports from multiple files

### ⏯ Playground Link

It doesn't appear to be possible to make a Bug Workbench example where one of the "files" is not included in compilation

### 💻 Code

```ts
// @filename: foo.ts

export interface Foo {
    a: string;
}

// @filename: bar.ts
export interface Bar { x: boolean; }

declare module "./foo" {
    interface Foo {
        b: number;
    }
}

// @filename: consumer.ts
import {Foo} from "./foo";
// Uncomment one of the below
// import "./bar";
// import type { Bar } from "./bar";

declare const f: Foo;
f.b.toFixed(1);    // Should always be a type error when `bar.ts` is not included at runtime
```

### 🙁 Actual behavior

There is no way to use the Bar type declared in `bar.ts` without also augmenting `Foo`.

### 🙂 Expected behavior

If the JS emit does not actually import the augmenting code, the typechecker should not honor the module augmentation.

**Comment by thw0rted** [comment]
I should add, I put "maybe?" in the title because it's possible there's an issue I'm missing here.  The motivation behind this issue is https://github.com/pnp/pnpjs/issues/2145 -- short version is, they use side-effect imports to augment their library object with additional capabilities, and the typechecker thinks those capabilities are "installed" if I `import type` from the add-on module, even though they are not.  Either the library needs to implement this differently, or it's a TS bug that needs to be fixed.

**Comment by thw0rted** [comment]
I'm confused, because the emit does change based on "how it got in" -- that is, `import "./bar" generates `import "./bar"` but `import type {Bar} from "./bar"` emits nothing.  That's not a "parallel universe" on its own, at least.  Is the problem with transitive imports, somehow?  Maybe a counterexample would help?

Assuming it's "working as intended", does this mean that the use case in the library I linked is not supported?  Are they doing something "wrong"?  Or is it a design limitation that TS can't catch the error I encountered?

**Comment by RyanCavanaugh** [comment]
Let's say you had a `tsconfig.json`
```
{
  // ...
  files: ["foo.ts", "bar.ts", "consumer.ts"]
  // ...
}
```
and you tried to use `f.b.toFixed(1);` without uncommenting any of those imports. Legal or no?

Today, we say "all files loaded contribute their augmentations". Your proposal, from what I am inferring, is that the augmentation would be conditionally visible based on whether we emitted an import of `bar`.

If we say "you have to have an explicit import, `files` list doesn't count", then a) that's a breaking change and b) users would need some way to *opt back in* to having the augmentation present if the reality is that the module is loaded through other means, so now you have `files` and `filesAlwaysImported` as well as the same for `include` and `exclude`

If we say "no, including in the file list is sufficient to add the augmentation", then we're back where we started, because it's impractical to suggest that everyone manually filter out these things from their `include` globs.

So yes this is basically an unsupported scenario - the upstream library should not mix types with augmentations if those augmentations need to be conditionalizable.

**Comment by thw0rted** [comment]
My understanding of `tsconfig` might be a little shaky, but I thought `files` was supposed to roughly correspond to things you'll link at runtime (`<script>` tag or whatever) -- entry points, basically.  So I'd expect augmentations created by those files to definitely "happen", because their corresponding runtime code definitely gets executed.  Instead, I'm talking about importing from an NPM package, so the file in question isn't actually "globbed in" from tsconfig anywhere -- unless I misunderstand, there's no glob that sends all of `node_modules/**/*.ts` to the typechecker, right?  (Should I update the example to clarify that the augmentation is happening in a package outside the current project?  Does that make a difference?  It's harder to illustrate in e.g. Bug Workbench.)

I'm specifically talking about files that are... introduced? loaded? included? transitively, from some `files` entry-point code, via `import`.  I *think* I understand that idea correctly, because if I completely remove all forms of `import "mylib/bar"` then the file does not "contribute its augmentations".

The behavior change I'm asking for is, if a file is "loaded" only because of an `import type`, and otherwise would not be "loaded", it should not contribute augmentations.  Like just about any change to the type system, this would technically be breaking, but I *think* it would only break code that should never have worked in the first place.

**Comment by RyanCavanaugh** [comment]
Right, what I'm explicitly declining is treating files differently based on what caused them to be part of your program.

**Comment by thw0rted** [comment]
Thanks for following up, Ryan.  I filed the issue because I encountered what appeared to be inexplicable behavior and eventually discovered that this was the root cause -- and I assumed that if it happened to me, it's probably happening to someone else.

If changing this behavior does not make sense, should it at least be explicitly documented?  Either something user-facing ("you may need both `import type {Foo} from "foo"` and `import "foo"` if....") or something for library authors ("libraries should not export types from a module that also applies augmentations via side-effect import"), or both.

As an aside: did somebody tighten the timing on typescript-bot?  It appears to close issues after 48 hours, and some of us take time off on the weekend....

**Comment by RyanCavanaugh** [comment]
This is the first I've heard of this problem. We try not to add to the docs until things have been encountered at least a few times.
