### ISSUE TITLE
Cannot declare unique symbol type in jsdoc in js file

### ISSUE THREAD

**Issue by panlina** [microsoft/TypeScript#48231]
# Bug Report

### 🔎 Search Terms

jsdoc, unique symbol

### 🕗 Version & Regression Information

Any version.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2&filetype=js#code/PQKhAIAEBcE8AcCm4DeBXAdgSwI5uQM6wC2ARgPYA2AvuCMALABQAxuRgdOAIbgC84AMokKlABQBKANzMgA)

### 💻 Code

```ts
/** @type {unique symbol} */
const a = Symbol();
```

### 🙁 Actual behavior

`a` is typed `unique symbol` in ts file but `symbol` in js file.

### 🙂 Expected behavior

`a` is typed `unique symbol` in both ts file and js file.

**Comment by ritikBhandari** [comment]
Hi,
Can i have a try on this issue?

**Comment by 8HoLoN** [comment]
I don't know if it's relevant to post it here, but I still have this issue (I opened an issue in vscode repo, may be it is more appropriate here ?)

https://github.com/microsoft/vscode/issues/200489

**Comment by sandersn** [comment]
The difference is only in quickinfo display. I filed a new bug: #56737
