### ISSUE TITLE
File is missing properties definition ! in lib.webworker.d.ts

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#48230]
# Bug Report

### 🔎 Search Terms
File, type, lib.webworker.d.ts

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctCAOwGd4YkG4BeOACnLh7gB4AfN14i+wGmACu8YSJ4wAnmCSsA3gCJMwADZJ1AX1lyRwACZrNOpAFpJYbRBSmDR4zxooQKjVt237js6GbnLoaEhgMBagKADmSAD0YDSxADRwMfEJAFbKsS4hIrQAwgAWKCneHEgAlGwCcKquhTzU9FhWbHBIAHRoklBENDAAKihQ8TAA-D2+zDMA2gAMALqkcAkJcADK4rG6cHOH0HAwpcB0p8wwzS3AmJxzdU0tbgkAVO9wAAJ0SEiNABiVn0cGscBGSgBwIOKDgYBQl1MALAOGUsAU8JQZzgUzgAHdSpi8XB3glbq9WrQWAicew5j1aaV1hTKW0adjSoDoOEuhwjoi4JIaABrGgQfE0OCC1RYs4ALjgDCgezg+hqjM5LMpImCr30hgpCSEomN5BqQA)

### 💻 Code

```tsx
const test = (
    <>
        <input 
        type={"file"}
            id={"file-upload"}
            name={"file-upload"}
            accept={"image/png, image/jpeg"}
            onChange={(e) => {
                const file = e.currentTarget?.files?.[0]; // Single file for this test
                if (file) {
                 /** @see {File} - Type File not have property path ? why ?  */
                    const path = file.path; 
                    const pathForce = (file as unknown as { path: string }).path; 
                }
            }}

        />
    </>
)
```

### 🙁 Actual behavior

type File is missing some property , like path where we can use inside nwjs or electron desktop app.
see https://github.com/microsoft/TypeScript/blob/main/lib/lib.webworker.d.ts
### 🙂 Expected behavior

We should able to see path , because is valide in js 
![image](https://user-images.githubusercontent.com/24865815/158012461-51f9262e-46a8-485f-b09b-91d7f029a9d1.png)

**Comment by MartinJohns** [comment]
The `File` type has no `path` property. That's an electron specific addition, it shouldn't be part of the webworker lib.

**Comment by djmisterjon** [comment]
ho oups sorry for the mistake !
