### ISSUE TITLE
`instanceof` clauses fail to assert a generic type

### ISSUE THREAD

**Issue by portasynthinca3** [microsoft/TypeScript#48237]
# Bug Report

### 🔎 Search Terms

`generic`, `infer`

### 🕗 Version & Regression Information

- `typescript@next` and `4.6.2`: present

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECykBcCmAnAPAFWkgHsgdgCYwDK4AbkgHzQDeAUNE9BBUgFzQYDcjzrYSgAUUAewAOqBAE9OGANoAicWMkoZigLq8+TYKPwQEKAK7AEolAAoBlOQEo6u5kwQALAJYQAdLaTQAXhY2XhcXdy9fNhEJKWlA4MEkbxVY9WlQ5gBfehz6MAAjIxQwc2hQSFI2JxdUtRlOE3wAa3xRAHd8XhyKqGgAORMAWzIk7DwkIiqxhlrVOM58YYLUBIBGACYAZm76XtJjUcpxgmJoI-9Z5jqFlmMPfABzBMVNrcVdvYMjaCHEVE4YHw8SC+CQ7Tg-2sYIhgxGbCs9nsOg8ADMrH8jKsHkYgcAkKJUZCsShHFcmGiMVComMcQg8QSiXCLvZnC59IZRCBkiBRI8rIolkMVihFAAaX7UvwxerSZHQAD0CugAANMcgUDThPN0iroF5VUDpCqJbhJOYHs8VUKRSqAIT0ZxIEAQfyU9WoLVuwz0-D4wnnQ5sVlhZgciBcnl8gXFS3iyUkr0yuLypWqj2a6U6mR6g0qo0m8bmhCW1Wxp723L0IA)

### 💻 Code

```ts
class Master<T extends Slave> {
    slave: T;
    slaveProperty: T["property"];

    constructor(slave: T) {
        this.slave = slave;
        this.slaveProperty = slave.property;
    }
}

abstract class Slave {
    property: unknown;
}
class NumSlave extends Slave {
    property: number = 123;
}
class StrSlave extends Slave {
    property: string = "123";
}

const master: any = new Master(new NumSlave());

if(master instanceof Master) {
    if(master.slave instanceof NumSlave)
        console.log("number", master.slaveProperty); // `master.slaveProperty` is `any`, expecting `number`!

    else if(master.slave instanceof StrSlave)
        console.log("string", master.slaveProperty); // `master.slaveProperty` is `any`, expecting `string`!
}

```

### 🙁 Actual behavior

The outer `if` statement asserts `master`'s type correctly despite it having been explicitly marked as `any`. The inner `if` statements succeed at asserting `master.slave`'s type, and therefore `master.slave.property`'s types, correctly in both cases. TypeScript thinks that `master.slaveProperty` is of `any` type.

### 🙂 Expected behavior

I expected TypeScript to infer `master.slaveProperty`'s type from the nested `isntanceof`s.

**Comment by fatcerberus** [comment]
You probably want to use a discriminated union.

Even in non-generic cases, narrowing is done on a per-property basis; type checks of one property don't affect the other members of the object.  TS also can't infer the `T` in `Master<T>` based on a type guard applying to `master.slave` - generic inference doesn't work that way.

**Comment by portasynthinca3** [comment]
Thanks! That works
