### ISSUE TITLE
TS gives JSDoc error on ...rest parameter, even when the prescribed fix in the error msg is implemented.

### ISSUE THREAD

**Issue by redbar0n** [microsoft/TypeScript#48238]
# Bug Report

For JavaScript typed with the JSDoc version of TypeScript.
Then TS gives JSDoc error on ...rest parameter, even when the prescribed fix in the error msg is implemented.

Could be related to this PR: https://github.com/microsoft/TypeScript/pull/29352
Which was implemented as a fix for this issue: https://github.com/microsoft/TypeScript/issues/27010

### 🔎 Search Terms

ts8032 rest, ts 8032 typescript, jsdoc typescript type rest object

### 🕗 Version & Regression Information
```
› npx tsc -v
Version 4.6.2
```

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noImplicitAny=false&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUBkoCiAnfAe3wC5QADARQFcBDAGwEsAzJ5AE1ADs6BbZKADkAOjH5k0SENBNoPIpFCMGRAO6dQappEREaSuqAbI6HJtwDmw8AAc6+fqADeRAEYArVJAC+oMaIwABQAHAAMAMwATACUFNgAVAkYoAkQ9o58Lu5e8L7+4pKQKQnAGCw03HlMRNygLACMoEFiIhJSMS4poBKQNPh17cU+WDgA6iRo0KSJyanpDk6unt5+QyVlFVWQNXUsUc2tQ53O3b39g0UYPkA)

### 💻 Code

```js
// @ts-check

// Error: `Qualified name '...rest' is not allowed without a leading '@param {object} ..'. ts(8032)`
/**
 * @param {object} ...rest
 */
function f1 (...rest) {
  return rest
}

// Works:
// But this is slightly problematic, as the JSDoc then will give a wrong indication to the user of the function:
// by indicating a single input object, instead of a variable amount of input objects.
/**
 * @param {object} rest
 */
function f2 (...rest) {
  return rest
}
```

### 🙁 Actual behavior

The `f1` case gives error on the ...rest parameter in the JSDoc.

The `f2` case renders the documentation as `@param rest` which is misleading.

### 🙂 Expected behavior

No error on the ...rest parameter in the JSDoc. Since the code implements exactly what the error message prescribes (adding or removing dots doesn't help).

**Comment by MartinJohns** [comment]
Rest parameters in JSDoc are annotated by adding the `...` in front of the type, so write `{...object} rest` instead of `{object} ...rest`.

See: https://jsdoc.app/tags-param.html#multiple-types-and-repeatable-parameters

**Comment by redbar0n** [comment]
Thanks! For future reference to others, this works, without error:

```js
/**
 * @param {...object} rest   the name of the argument array
 */
function f2 (...rest) { // the argument array is spread out into individual arguments.
  return rest           // but can still be referenced directly, as here.
}
```

The tooltip doc shows:

```
function f2(...rest: object[]): any[]
@param rest — the name of the argument array
```

Which makes sense. So I'm closing this issue.
