### ISSUE TITLE
Support decorators on function declarations

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/TypeScript#4824]
Hi all.

I think it would be a great feature if we can use decorators with functions too.

# Example

``` typescript
// SImple use case
function deprecated(target: Function) {
    let oldFunction = target;
    return (...args) {
        console.log("You are using a deprecated function").
        return oldFunction.apply(null, args);
    };
}

@deprecated
function legacy(...args) {/* ... */};
```

It also would enable patterns like Contract, with pre/post conditions checks etc.

**Comment by DanielRosenwasser** [comment]
Functions are hoisted, so what are the intended semantics? See https://github.com/Microsoft/TypeScript/issues/2249#issuecomment-86367067

That's the main problem, and the ECMA-262 committee doesn't seem totally sure what to do about it either.

**Comment by mhegazy** [comment]
Any thing that typescript will support in this domain needs to be inline with the ES proposal. see https://github.com/wycats/javascript-decorators/issues/31 for related discussion.

**Comment by mhegazy** [comment]
The JS-decorator proposal is the right place to have this discussion. Please submit the proposal on https://github.com/wycats/javascript-decorators repo instead.

**Comment by SergioMorchon** [comment]
@mhegazy definitely agree, thank you for the info!
