### ISSUE TITLE
Conditional type doesn't go to true or false branch.

### ISSUE THREAD

**Issue by alexeymolchan** [microsoft/TypeScript#48243]
# Bug Report

### 🔎 Search Terms

generic conditional types

already checked https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs and https://github.com/microsoft/TypeScript/issues/31751

### 🕗 Version & Regression Information

3.9.7 / 4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2&ssl=6&ssc=2&pln=1&pc=1#code/C4TwDgpgBAggxsAlgewHYB4AKAaKAVKAXilQgDcIAnAPiKgG8pRIAuKAZ2EsVQHMBuKGACGIADbJhAEzaYoAXygAyKAAoA2ngC6UCAA9gEVFPZR1pCpR0B+BlAC2EYMIDKAa0RhIMppQCu0IpsjI7ObATyAJT8AFAxAGZ+qAgoqEKUECIZ8EhoWLgE+obGpgBKEHDIlFLonNx8uEluqMgA7qi0xOWV1bVcPLyNqM1tHdSqwilobDmp+fjUkWxkyIhSDDFQW1CTuagAdKHCm9u7qYdOrh5eEFIx8idAA)

### 💻 Code

```ts
type Action<P, T = never> = { type: string; payload: P } & ([T] extends [never] ? { metaSkipped: true } : { meta: T });

function prepareAction<P, T extends Record<string, unknown> = Record<string, unknown>>(action: Action<P, T>): void {
    action.meta // Property 'meta' does not exist on type 'Payload<P, T>'.(2339)
    action.metaSkipped  // Property 'metaSkipped' does not exist on type 'Payload<P, T>'.(2339)
}
```

### 🙁 Actual behavior

properties from intersection are not accessible (conditional type doesn't resolve as true / false branch)

### 🙂 Expected behavior

conditional type should go to false branch. correct my please if i'm wrong

Thanks in advance.

**Comment by MartinJohns** [comment]
Resolving of conditional types involving unbound generic type arguments is deferred. At that point the compiler doesn't know what `Action<P, T>` resolves to, because the compiler doesn't know what types `P` and `T` are.

**Comment by alexeymolchan** [comment]
@MartinJohns thanks for clarification

**Comment by alexeymolchan** [comment]
@MartinJohns [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHYB4AKAaKAVKAXilQgDcIAnAPiKgG8pRIAuKAZ2EsVQHMBuKGACGIADbJhAEzaYoAXygAyKAAoCEAB7AIqKexLkqUAPwMoAWwjBhAZQDWiMJBlNKAV2iK2jKzbYE8gCU-ABQoQBm7qgIKKhClBAiifBIaFi4Gtq6+lAAShBwyJRS6JzcfLjR9qjIAO6otMQFRSVlXDy8Vag19Y3UqsKxaGypcRn41EFsZMiIUgyhUMtQQ2moAHR+wksra3Fb1naOzhBSofK7QA) but why this works ?

**Comment by RyanCavanaugh** [comment]
> if i'm telling it that T will extend Record<string, unknown>

Conditional types are not necessarily linear (meaning that they have predictable behavior between `T` and an a subtype of `T`), and figuring out whether or not they are requires reasoning in the form of "Does *any* type exist such that this type would behave in the other way?", which is not very tractable.

**Comment by alexeymolchan** [comment]
@fatcerberus as i see from [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHYB4AKAaKAVKAXilQgDcIAnAPiKgG8pRIAuKAZ2EsVQHMBuKGACGIADbJhAEzaYoAXygAyKAAoCEAB7AIqKexLkqUAPwMoAWwjBhAZQDWiMJBlNKAV2iK2jKzbYE8gCU-ABQoQBm7qgIKKhClBAiifBIaFi4Gtq6+lAAShBwyJRS6JzcfLjR9qjIAO6otMQFRSVlXDy8Vag19Y3UqsKxaGypcRn41EFsZMiIUgyhUMtQQ2moAHR+wksra3Fb1naOzhBSofK7QA) where ```T extends ...``` no defer occur and i can access ```action.meta```. correct me please, if i'm wrong.

**Comment by alexeymolchan** [comment]
@MartinJohns mapped type like this ```type OptionsFlags<Type> = {
  [Property in keyof Type]: boolean;
};``` will be deferred too ?

**Comment by MartinJohns** [comment]
How would the compiler know what the final type will look like without knowing what type `T` actually is?

**Comment by fatcerberus** [comment]
To be clear, generic types in TS don't work like C++ templates.  The compiler only looks at the body of a generic *once* and tries to determine if it will work for all possible combinations of type parameters, but these checks are necessarily conservative because it would be prohibitively expensive and/or complex to do otherwise.
