### ISSUE TITLE
rename symbol broke with prefixText and suffixText when disabled

### ISSUE THREAD

**Issue by hanzooo** [microsoft/TypeScript#48258]
# Bug Report

### 🔎 Search Terms
rename symbol、use aliases for renames disabled、prefixText and suffixText when disabled

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

We can try it in vscode.

### 💻 Code

- For example we have two files.

```ts
// a.ts, we just declare a anonymous function
export default function () { }

// b.ts
import aTest from './a';

function test() {
    return aTest();
}
```

- Disable the vscode setting Use Aliases For Renames

<img width="485" alt="image" src="https://user-images.githubusercontent.com/16368939/158226131-ecdf2312-608a-40ef-8572-19605aa8b35b.png">

- Rename the 'aTest' symbol at 'aTest()' location of b.ts file. Rename to cTest.

### 🙁 Actual behavior

- 'default' was changed, the a.ts file broke.
```ts
// a.ts
export cTest function () { }

// b.ts
import cTest from './a';

function test() {
    return cTest();
}
```
- if the export default function at a.ts file is not anonymous function, it works fine.

### 🙂 Expected behavior

- the export anonymous function at a.ts file should not be changed.
```ts
// a.ts
export default function () { }

// b.ts
import cTest from './a';

function test() {
    return cTest();
}
```

**Comment by RyanCavanaugh** [comment]
> `export cTest function () { }`

🤦‍♂️
