### ISSUE TITLE
Update the type definitions of bind, apply and call

### ISSUE THREAD

**Issue by nicu-chiciuc** [microsoft/TypeScript#48257]
# Suggestion

Currently the type definition of `bind` is defined in `microsoft/TypeScript/lib/lib.es5.d.ts`

```ts
bind(this: Function, thisArg: any, ...argArray: any[]): any;
```

this seems to be easily transformed into something like this:

```ts
bind<T extends Function>(this: T, thisArg: any, ...argArray: Parameters<T>): T;
```

I didn't yet test this fully but I think it's a good idea to replace `any` with more strong types.
Are there any caveats I don't see?

## 🔍 Search Terms
bind es5 function

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Storybook seems to favour using bind as a method for copying functions, unfortunately that means that all the other data about the function is gone. This change would solve this issue. I could probably try to do it myself.

**Comment by IllusionMH** [comment]
> Are there any caveats I don't see?

Starting from the fact that returned function isn't `T` especially is you bind parameters.

**Comment by MartinJohns** [comment]
`Parameters<T>` is a conditional type using inference and does not support overloads, so you'd get false errors.

**Comment by nicu-chiciuc** [comment]
@MartinJohns nice, I guess the issue in my case was that the `Function` interface was used instead of `CallableFunction` interface
