### ISSUE TITLE
HTMLDialogElement should have methods `show`, `showModal` and `close` as well as Properties `open` and `returnValue`

### ISSUE THREAD

**Issue by d-koppenhagen** [microsoft/TypeScript#48267]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020`/`ES2021`/`ESNext` and my *lib* is `lib.dom.d.ts`.

## Missing / Incorrect Definition

```diff
-/** @deprecated - this is not available in most browsers */
+/** @experimental - this is not available in some browsers */
interface HTMLDialogElement extends HTMLElement {
+   open: boolean;
+   returnValue: string;
+   /**
+    * Closes the dialog element.
+    *
+    * The argument, if provided, provides a return value.
+    */
+   close(returnValue?: string): void;
+   /** Displays the dialog element. */
+   show(): void;
+   showModal(): void;
    addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDialogElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLDialogElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}
```

- [See here current implementation](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L6328-L6334)
- [Compare with implementation in `microsoft/TypeScript-DOM-lib-generator`](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/31e9b893980c91991f45a565dfbd6280798e2b4f/baselines/dom.generated.d.ts#L6232-L6248)

## Sample Code

```
const dialogEl = document.getElementById("dialog") as HTMLDialogElement;
dialogEl.show();
dialogEl.showModal();
dialogEl.close();
```

## Documentation Link

[See Docs at MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/)

**Comment by d-koppenhagen** [comment]
Meanwhile lot's of Browsers are supporting the `HTMLDialogElement`, so I think the `@deprecated` annotation can be either:
- removed completely
- adjustes like: `/** @deprecated - this is not available in some browsers */`

**Comment by orta** [comment]
This issue wants to live over in https://github.com/microsoft/TypeScript-DOM-lib-generator/

**Comment by d-koppenhagen** [comment]
You mean I should create another issue with same content in https://github.com/microsoft/TypeScript-DOM-lib-generator/ ? I've seen the deprecated Warning has already been removed here with https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1259
But there are still the Methods / props missing.

**Comment by HolgerJeromin** [comment]
> But there are still the Methods / props missing.

They are there even before your linked PR:
https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/31e9b893980c91991f45a565dfbd6280798e2b4f/baselines/dom.generated.d.ts#L6234

**Comment by Mikilll94** [comment]
Any update on this? This issue is still not fixed.

**Comment by d-koppenhagen** [comment]
@RyanCavanaugh is there any update / schedule when to expect this change landing in TS?

**Comment by HolgerJeromin** [comment]
Can you provide a playground link which shows a missing thing?

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJgSwIYBsQHMCiKYF54jACuAtgKZhQB06ZU2Z5lAQgJ4CScAFAESKoYeAShhIIMABIAVALIAZACLI0WFIwpQA3ACh+K7FQgALEAHcuQnXowHjZmSDioLV5TZRVgaCGRdA

![image](https://user-images.githubusercontent.com/2410353/186592972-b9638fd5-7209-466f-9ce5-4f89624c8164.png)

**Comment by d-koppenhagen** [comment]
You are right: I just tried it again and I think the problem is disappeared by now.
See: https://stackblitz.com/edit/vite-vue3-dialog
