### ISSUE TITLE
Use strictest possible type when inferring array literal with known in advance types

### ISSUE THREAD

**Issue by Francesco-Manicardi** [microsoft/TypeScript#48272]
# Suggestion

## 🔍 Search Terms

Use strictest possible type when inferring array literal
Array elements' types are known in advance, but array is typed as an array of the union of all elements' types
Array literal single element typing information gets lost
TypeScript array literal elements are inferred correctly, but the whole array loses order information
Non-optimal array literal type inference

## ✅ Viability Checklist
 
My suggestion meets these guidelines:

* [ 🗸 ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ 🗸 ] This wouldn't change the runtime behavior of existing JavaScript code
* [ 🗸 ] This could be implemented without emitting different JS based on the types of the expressions
* [ 🗸 ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ 🗸 ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When inferring the type of a variable initialized with an array literal where all of the elements have known type, use the strictest possible type.

## 📃 Motivating Example
 
let's say that I have these variables:
```
a : string;
b: number;
c: unknown;

```
now, i build an array with those variables:
`let myArray = [a,b,c]`

Clearly, the myArray type is [string,number,unknown].

instead, typescript infers it as unknown[].

This means that this code raises an error, even though it shouldn't:

`myArray[0].includes("asd") // should work, instead gives Object is of type 'unknown'.ts(2571)
`
## 💻 Use Cases

Doing some async work with rxjs:
```

let obs = [
      this.customerService.getCustomerData(), // Observable<Customer>
      this.profilingService.getRiskProfile(), // Observavle<RiskProfile>
      this.profilingService.getCategorisation() // Observable<Categorisation>
    ];

```
all of the individual elements have correctly inferred typing.

I'd expect the array to have this type:
```
[
Observable<Customer>,
Observavle<RiskProfile>,
Observable<Categorisation>
]
```

Instead, the type is 

`(Observable<Customer> | Observable<RiskProfile> | Observable<Categorisation>)[]
`
So when i do something like:

```
combineLatest(obs).subscribe(results => {
   // do something....
});
```

results[0] should be of type Customer, res[1] should be of type RiskProfile, and res[2] should be of type Categorisation.

Instead, I get type `(Categorisation | RiskProfile | Customer)` for every element of results.

The only workaround is manually providing typing information to the observables array. But this feels redundant since we've already defined the type of all of the elements, which are correctly inferred by TypeScript.

**Comment by fatcerberus** [comment]
```ts
let myArray = [ a, b, c ] as const;
```
