### ISSUE TITLE
Why not to remove typeof from Typescript?

### ISSUE THREAD

**Issue by gen1lee** [microsoft/TypeScript#48275]
# Suggestion

Why not to remove (make deprecated) typeof from TS types? It will make code cleaner and shorter without any cons.

```typescript
// before

action: ReturnType<typeof setUserCity>

route: typeof state.routes[0]

// after

action: ReturnType<setUserCity>

route: state.routes[0]
```

## 🔍 Search Terms

is:issue in:title typeof 
is:issue in:title remove typeof 
is:issue in:title delete typeof 
is:issue in:title deprecate typeof 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Remove typeof from types.

## 📃 Motivating Example

Code looks shorter and cleaner.

```typescript
// before

action: ReturnType<typeof setUserCity>

route: typeof state.routes[0]

// after

action: ReturnType<setUserCity>

route: state.routes[0]
```

## 💻 Use Cases

```
const renderTab = (route: state.routes[0], index: number) => {
  return null;
}
```

**Comment by xiBread** [comment]
Shorter and cleaner code is not a valid use case/reason.

**Comment by MartinJohns** [comment]
This would require every function to automatically become a type as well. That's quite messy and unnecessary.

**Comment by gen1lee** [comment]
@xiBread why?

**Comment by gen1lee** [comment]
Is there any reason why we need it? Any use case?

**Comment by MartinJohns** [comment]
> every function has its type already. It is just a syntax improvement.

Defining a function does not define a type. By writing `function foo(){}` I create a **value** named `foo`, but not a **type**. Your suggestion would either require to always introduce a type as well (which would get messy, so many unnecessary types) or have an *implicit* `typeof`, which would muddy the waters between type and value-space. When before it could only refer to a type, now it can refer to a type or implicit the type of a value - you wouldn't know from a glance anymore. This could also result in ambiguity when having a value and a type with the same name - what then? Prefer the type? Throw an error?

And what about classes? When having a class `class A {}` then `A` and `typeof A` refer to different types. Have a special logic for classes?

**Comment by gen1lee** [comment]
Ok, thanks for explaining. Will close the issue.

This looks terrible btw:

```
type Foo = number
const Foo = "Foo"
```

@MartinJohns would it be possible in better TS where there are no classes and where you can create variable and type with equal names?

**Comment by xiBread** [comment]
Classes are a fundamental part of TypeScript seeing as it builds off of JS… removing them doesn't make any sense.

**Comment by gen1lee** [comment]
@xiBread yeah but I'm talking about better TS [without](https://github.com/jonaskello/eslint-plugin-functional/blob/master/docs/rules/no-class.md) js legacy. Anyway, uselessness of classes is a separate discussion.

**Comment by MartinJohns** [comment]
That.. would not be TypeScript, that would be a completely new language, and there you'd be free to do whatever you want. TypeScript is fundamentally tied to JavaScript, as TypeScript is *just* type information for JavaScript.
