### ISSUE TITLE
Indentation not respected when executing various refactorings (TypeScript/JavaScript)

### ISSUE THREAD

**Issue by axefrog** [microsoft/TypeScript#48281]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.7.0-dev.20220315

**Search Terms**
- getCodeFixes
- code action
- quick fix

---

Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.65.2
- OS Version: Windows 10

When I execute a code action that requires vscode to format part of the document, it _always_ messes up the indentation of the code. I have experienced this repeatedly with both JavaScript and TypeScript, in a variety of different scenarios.

Before reporting this issue, I have tested with all extensions disabled _and_ all settings reset to factory default.

See the following:

![NVIDIA_Share_2022-03-11_11-01-16](https://user-images.githubusercontent.com/298883/157781792-dc68d8c7-5fd6-4d37-9e74-8818268b4a48.gif)

**Comment by mjbvz** [comment]
Thanks @axefrog 

Relevant TS Server edit using 4 space indents:

```
{
    "fixName": "fixMissingProperties",
    "description": "Add missing properties",
    "changes": [
        {
            "fileName": "/Users/matb/projects/san/abc.ts",
            "textChanges": [
                {
                    "start": {
                        "line": 9,
                        "offset": 7
                    },
                    "end": {
                        "line": 9,
                        "offset": 65
                    },
                    "newText": "{\n    foo: \"\",\n    bar: function (a: string): void {\n        throw new Error(\"Function not implemented.\");\n    }\n}"
                }
            ]
        }
    ]
}
```

**Comment by axefrog** [comment]
@mjbvz Sorry could you clarify? Are you saying I should directly modify the typescript source code in node_modules as a workaround? Or do you mean there's configuration I can modify that will persist in the same way that user snippets persist?

**Comment by mjbvz** [comment]
My comment is for helping us understand what is going wrong here. I don't think there's a workaround you can apply as a user

**Comment by MQuy** [comment]
hi, I take a try to fix the issue above, it would be great to have your thought @RyanCavanaugh and @mjbvz.

PR https://github.com/microsoft/TypeScript/pull/48340
