### ISSUE TITLE
Conditional types could not inference type in expect way

### ISSUE THREAD

**Issue by Rey-Wang** [microsoft/TypeScript#48286]
# Bug Report

### 🔎 Search Terms

I have tried search several issues related to conditional types, but did not found a familiar one
### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVxhAWQEMwxMUBzAHgCg44AVOUGYFAEwGc4AlYNaOyqcYUchQA0cIigCeAPgl04AVWYhWHbgGtgsiAkZL6BdZq5xd+ww2NwAojXkAKIlChFZALkYBtALpSVj4qUgBuRAA2SMA+pgA+cM7OEABGAFb8MD4MAJRwALzyDrn5AN7KUMAwSFC4bh6yAHRV7EhowMlEaGhSaZkY+UVwFfT0mIbOMLJgwAZwEdHAhQUFcADkyOhYOOvlymNwAigicFWcSJHwa4sxKRlZuQdjVTV1I8+HTd-dvZ9jvn6WV8Vn8-h850uMDshwAvs9YcxIpxlqNDmdqrVcGj0XBvk1fjD0YCHhgQXowT4gWTbsBAv94XDlLCpGVEURuKYWGwLFZ5kwAPx+Aj+OA+exPeE0aXTWYYi5XQofQ6Ydg+ERiSjPEREGqcHwoJAAW1SwCgNClx1O50gJ1i8qhASVvhxcFVPnWAEZ1kSdXqfAAmC3+aVW+BQTiepX4YikcTOG04FFSdZ+pCcH1JfpDYrOMrrVUodY+T2w0pwGgAekrRyT4cjPj4AigQkNJrNUg14jgiTbpqg8lDdbOnAD0cIJDIlATwE4tuTG1VmdTMF16b2VZrYZHAcb-EEwlE4ikfbN8iAA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
export function toMapping<
  T extends Record<string, any>,
  U extends keyof T,
  M extends keyof T,
  E
>(array: T[], key: U, value: M | ((object: T) => E)) {
  return array.reduce((acc, object) => {
    if (typeof value === 'function') {
      const result = value(object)
      return {
        ...acc,
        [object[key]]: result,
      }
    } else {
      return {
        ...acc,
        [object[key]]: object[value],
      }
    }
  }, {} as M extends keyof T ? T[M] : E)
}



type result = {
    id: string
    status: number
}

const response: result[] = [{
    id: '1',
    status: 2
}]

const rs1 = toMapping(response, 'status', (obj) => ({'newKey': 1})) 
// const rs1: Record<number, string | number>

const rs2 = toMapping(response, 'id', 'status')
// const rs2: Record<string, number>
```

### 🙁 Actual behavior

the type of rs1 is not been inferenced correctly

### 🙂 Expected behavior

expect the type of rs1 to be `Record<number, {newKey: number}>`

**Comment by whzx5byb** [comment]
`toMapping<T, U, M ,E>` returns a conditional type `M extends keyof T ? T[M] : E`, which will always be `T[M]` because `M` has a default generic constraint `M extends keyof T`.

Checking `E` instead of `M` will make the conditional type work as expected: `{} as unknown extends E ? T[M] : E`.

**Comment by cypherfunc** [comment]
I think the confusion is because either M or E will be meaningless, depending on whether value is a function. You can simplify things by moving the `if` check outside of the `reduce` (which is also better runtime behavior).

`export function toMapping<
    T extends Record<string, any>,
    U extends keyof T,
    M extends keyof T,
    E
>(array: T[], key: U, value: M | ((object: T) => E)) {
    if (typeof value === 'function') {
        return array.reduce((acc, object) => {
            const result = value(object)
            return {
                ...acc,
                [object[key]]: result,
            }
        }, {} as E)
    } else {
        return array.reduce((acc, object) => {
            return {
                ...acc,
                [object[key]]: object[value],
            }
        }, {} as T[M])
    }
}`

**Comment by cypherfunc** [comment]
Alternatively, if you really don't want to change the code, you could do something like this:

```
type KeyOrFunc<T> = (keyof T)|((object: T) => any);
type Output<T, V> =
    V extends keyof T ? T[V]
    : V extends ((...args: any) => any) ? ReturnType<V>
    : never;

export function toMapping<
    T extends Record<string, any>,
    U extends keyof T,
    V extends KeyOrFunc<T>
>(array: T[], key: U, value: V) {
    return array.reduce((acc, object) => {
        if (typeof value === 'function') {
            const result = value(object)
            return {
                ...acc,
                [object[key]]: result,
            }
        } else {
            return {
                ...acc,
                [object[key]]: object[value],
            }
        }
    }, {} as Output<T,V>)
}
```

**Comment by Rey-Wang** [comment]
@cypherfunc  
- for the fist solution, if we make if outside reduce, would make the return type of  `toMapping` become messy, because there no E passed in
  ```
  const rs2 = toMapping(response, 'id', 'status')
  // const rs2: Record<string, unknown> | Record<string, number>
  ```
- for the second solution
we can not confirm the value type, it would always be `KeyOrFunc`, you would got error below
```
// (parameter) value: V extends KeyOrFunc<T>
Type 'V' cannot be used to index type 'T'.
```

**Comment by Rey-Wang** [comment]
I do check the solution of @whzx5byb rise up, that works! but thats little hard to understanding. why `{} as unknown extends E` works, would reduce could detect the callback function return type?

**Comment by cypherfunc** [comment]
Ah, right. Yeah, @whzx5byb's solution is probably the best option then. I think my suggestions could work, but it would take some extra conditional types.

The reason `unknown extends E ? Record<T[U],T[M]> : Record<T[U], E>` works is because `unknown` only extends itself, so if E is defined as anything useful, `unknown extends E` is false. However, there are a couple cases that won't work as intended, if E is `unknown` or `any`.

```
// with @whzx5byb's solution:

const rs1 = toMapping(response, 'status', (obj) => ({'newKey': 1})) 
// Record<number, {'newKey': number}>
// this is correct

const rs2 = toMapping(response, 'id', 'status')
// Record<string, number>
// this is correct

const rs3 = toMapping(response, 'status', (obj): unknown => ({'newKey': 1})) 
// Record<number, string | number>
// this should be Record<number, unknown>

const rs4 = toMapping(response, 'status', (obj): any => ({'newKey': 1})) 
// Record<number, string | number>
// this should be Record<number, any>
```

**Comment by cypherfunc** [comment]
I was able to update my second suggestion, so it outputs the correct type for all inputs. Unfortunately it requires a cast, but it's safe, since `value` **_must_** be a `keyof T` when you reach that line. (TS just can't infer it properly.) Once the `satisfies` keyword is added to TS, I think it would simplify this, or at least replace the casting.

```
type KeyOrFunc<T> = (keyof T)|((object: T) => any);
type OutputValue<T, V> =
    V extends keyof T ? T[V]
        : V extends ((...args: any) => any) ? ReturnType<V>
            : never;

export function toMapping<
    T extends Record<string, any>,
    U extends keyof T,
    V extends KeyOrFunc<T>
    >(array: T[], key: U, value: V) {
    return array.reduce((acc, object) => {
        if (typeof value === 'function') {
            const result = value(object)
            return {
                ...acc,
                [object[key]]: result,
            }
        } else {
            return {
                ...acc,
                [object[key]]: object[value as keyof T], // cast is required, but safe
            }
        }
    }, {} as Record<T[U], OutputValue<T,V>>)
}

type result = {
    id: string
    status: number
}

const response: result[] = [{
    id: '1',
    status: 2
}]

const rs1 = toMapping(response, 'status', (obj) => ({'newKey': 1})) 
// Record<number, {'newKey': number}>

const rs2 = toMapping(response, 'id', 'status')
// Record<string, number>

const rs3 = toMapping(response, 'status', (obj): unknown => ({'newKey': 1})) 
// Record<number, unknown>

const rs4 = toMapping(response, 'status', (obj): any => ({'newKey': 1})) 
// Record<number, any>
```

**Comment by Rey-Wang** [comment]
@cypherfunc Thats Perfect!

**Comment by Rey-Wang** [comment]
Would close this issue, thanks @cypherfunc and @whzx5byb provide the solutions and for their patience in explaining reasons!!!
