### ISSUE TITLE
Optional chaining on undefined or null only types

### ISSUE THREAD

**Issue by iamogbz** [microsoft/TypeScript#48280]
# Bug Report

Not sure if a bug or expected behaviour

### 🔎 Search Terms

Optional chaining on undefined or null only types

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about
  - Common "Bugs" That Aren't Bugs
  - Common Feature Requests

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgApynAtgZ2QbwChlkZgIAbAEwEEAuZHMKUAcwG5CBfQw0SWIhQAlCDgCuFMAWLIAHgyYsQHbrxjiQCMMAD2IUgB4AKsghzIIKnnSZcAPgAUABwbGAlA1ESpnDVp19I2MnZwB+N09kTSoIMhAIKj9NbT0DGBMnAH0I5A8vMUlpAB9oqzjQRJkSKAgwcSgDIhISBWQAIhxdLDqACzZ2gBpZLk4eQgR9JmQ4ZABeUkd8LndOODCAOjlOIA)

### 💻 Code

```ts repro
interface Params {
  fieldA: string;
}

interface Result {
  x: string;
}

function f<T extends Params>(p: T): Result;
function f<T>(p?: T): undefined;
function f<T>(_?: T): Result | undefined {
  return {
    x: "something",
  };
}

const a = f({});
a?.x; // this fails
```

### 🙁 Actual behavior

> ts(2532) Object is possibly 'undefined'.

> ts(2339) Property 'x' does not exist on type 'never'.

### 🙂 Expected behavior

No errors since the optional chaining should just result in more `undefined`

```ts
const x: undefined = a?.x; // succeeds?
```

**Comment by RyanCavanaugh** [comment]
Why would you be doing this on purpose?

**Comment by iamogbz** [comment]
It came up in the case of a polymorphic function that could return `null`|`undefined` in some argument cases. Attempting to optional chain on the return resulted in the aforementioned error, when the return was inferred to `null`|`undefined`

**Comment by RyanCavanaugh** [comment]
The error seems entirely desirable; if you thought you might be holding a `Params` then letting you write `a?.fieldA` is a disservice.
