### ISSUE TITLE
Generic types combined with & instead of |

### ISSUE THREAD

**Issue by RoelVB** [microsoft/TypeScript#48287]
### 🔎 Search Terms

generic, type, class, and, &, or, |, combined

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?#code/FAYwNghgzlAECiAPCBbADmApgYUjAPACoB8wA3sLFbAC6ZQ0AUAbhGAK6YBcshAlD0KVqFamNgAnTDXYSAdrFYdMAbmFUAvsC2g8cJKgyYAjLEyI6cgCb7k6LLmhR8AZRoSAlnIDmxWGVgtcCcEOyMAJjMLTGtbQwc9fAA5dhQAI0wJPwCdADN2ORAaDwB7BQN7TEZzeO5YYwAfcL5YAHpWyWlZOTgAAxoATzRMEtzQ2tMG2iGRsYqI3vJ1Tpl5KNqAXi3jAH55rGMufcxwtR0QMoZYLwYIQsxYDdg5TAB3WEZjxmM+PkY+NQ3Gh3ECYAB0dAYjAA5NCAW0OoQABYeOAQECgtA0PpuTw+WAAMlgKXSmV6sGgFIk3lSMRoABpYK8USAkdc4KNYBdZFAHh50CUYB40lgPuZhkVMFZYL1cV5vLApiSMhJenxgEA)

### 💻 Code

```ts
class ExampleClass<T>
{
    test(value: T): T
    {
        return value;
    }
}

class Example1 extends ExampleClass<String> { }
class Example2 extends ExampleClass<Number> { }

function Example(example: 1|2) // returns `typeof Example1 | typeof Example2`
{
    return example===1?Example1:Example2;
}

const instance = new (Example(1))();
instance.test(''); // ERROR: Argument of type 'string' is not assignable to parameter of type 'Number & String'
```

### 🙁 Actual behavior

Combining classes with generic type results in generic types on arguments to be combined with `&`.
But get combined with `|` for return types.

### 🙂 Expected behavior

Expected the types to be combined with `|`

**Comment by whzx5byb** [comment]
This is a correct error. Here is a simple example in which your expected behavior is unsound:
```ts
class ExampleClass<T> {
    test(value: T): T {
        return value;
    }
}

class Example1 extends ExampleClass<string> { 
    test(value: string): string {
        return value.toLowerCase();
    }
}

class Example2 extends ExampleClass<number> { 
    test(value: number): number {
        return Number(value.toFixed(2));
    }
}

function Example(example: 1|2) // returns `typeof Example1 | typeof Example2`
{
    return Math.random() > 0.5 ? Example1 : Example2;
}

const instance = new (Example(1))();

console.log(instance.test('Foo'))
// You expect it return 'foo', but there's a 50% chance of runtime error
``` 

See: https://github.com/microsoft/TypeScript/pull/30769 for more details.

**Comment by RoelVB** [comment]
I don't see how this would be correct.
In `test(value: T): T` the first `T` becomes `String & Number`, the second `T` becomes `String | Number`

**Comment by RoelVB** [comment]
Thanks @fatcerberus, I understand now
