### ISSUE TITLE
dynamic import closes over the module specifier argument

### ISSUE THREAD

**Issue by PsixokoT** [microsoft/TypeScript#48285]
# Bug Report

Dynamic import JSON compiled into js code with closures. What does not look like what was expected. 

### 🔎 Search Terms

Dynamic import JSON

### 🕗 Version & Regression Information

TypeScript Version 4.6.2
- I was unable to test this on prior versions because I think there is the same 

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "strict": true,
    "newLine": "LF",
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "esModuleInterop": true
  }
}
```

### 💻 Code

1.json
```json
[1]
```

2.json
```json
[2]
```

import_test.ts
```ts
function load() {
  let fileName = '1';
  const promises = [import(`./${fileName}.json`)];
  fileName = '2';
  promises.push(import(`./${fileName}.json`));
  
  Promise.all(promises).then(results => console.log(results));
}

load();
```

Compiled js
```javascript
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
function load() {
    let fileName = '1';
    const promises = [Promise.resolve().then(() => __importStar(require(`./${fileName}.json`)))];
    fileName = '2';
    promises.push(Promise.resolve().then(() => __importStar(require(`./${fileName}.json`))));
    Promise.all(promises).then(results => console.log(results));
}
load();
```

### 🙁 Actual behavior

```
0 { '0': [Getter], default: [ 2 ] }
1 { '0': [Getter], default: [ 2 ] }
```

### 🙂 Expected behavior

```
0 { '0': [Getter], default: [ 1 ] }
1 { '0': [Getter], default: [ 2 ] }
```

**Comment by nmain** [comment]
Agreed.  The expression inside `import(expr)` should be toStringed synchronously, but the downlevel code isn't doing that correctly here.

Relevant spec: https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-import-call-runtime-semantics-evaluation

**Comment by Josh-Cena** [comment]
Worth noting that `babel-plugin-dynamic-import-node` compiles this to ``Promise.resolve(`./${fileName}.json`).then((c) => __importStar(require(c)))`` (equivalent). However, this makes Webpack unable to statically analyze the `require` call. If we are to fix this and remain compatible with Webpack, we need to handle string literals specially (https://github.com/airbnb/babel-plugin-dynamic-import-node/pull/89). It's a shame that we can't handle _all_ constant expressions specially given the type information available, if we don't do type-directed emit.

**Comment by Josh-Cena** [comment]
Since it's been three months without much progress—may it be "help wanted"? I have made a quick fix using the solution proposed above.

**Comment by RyanCavanaugh** [comment]
If you have a PR please go ahead and post - the only thing we *don't* want PRs for are unapproved Suggestions 🥰

**Comment by rbuckton** [comment]
This doesn't seem to have anything to do with JSON, but is more about how we transpile `import()` downlevel.
