### ISSUE TITLE
Addition assignment for properties with different getter & setter types

### ISSUE THREAD

**Issue by m93a** [microsoft/TypeScript#48292]
# Bug Report
If a getter of a field has a numeric type which is narrower than the type of its setter, it should be perfectly fine to use `+=` on it.

For example consider the following field definition:
```ts
get x(): number { ... }
set x(value: number | Foo) { ... }
```
Then `obj.x = obj.x + 1` works fine, because it translates to `set_x( get_x() + 1 )`. Since `get_x` returns a number and `set_x` accepts numbers, there is no reason for this to fail.

However, using `obj.x += 1` does **NOT** work – it fails with:
```
Operator '+=' cannot be applied to types 'number | Foo' and 'number'.
``` 

Clearly, `x += 1` and  `x = x + 1` aren't the same for the type checker, even though they are the same at runtime.

### 🔎 Search Terms

Incrementing or decrementing a field with getter and setter doesn't work properly. Getter and setter with incompatible types, shorthand assignment, operator '+=' cannot be applied to types.

### 🕗 Version & Regression Information
 - this bug exists since 4.3
 - before 4.3, getter and setter couldn't have different types

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/MYGwhgzhAEBiD29oG8BQ0PQPoA8Bc0AdgK4C2ARgKYBO0APtMYQCaUBmAloZc6upgHNKAF2g4AFAEoCJCjRTRqI4tULRhACw4QAdLmgB+A9AAMAbmgBffhggix4gG5gQxSjLJVaDJq07dmSQVNbT0caABeaGdXSgtrG2hyMGopFETMdS1dcKiQnOgAamgARgsAenLof0pEhMyAR2IJILRMzPydcMKosuhK6BpqOtRrIA)

### 💻 Code

```ts
class Foo {
    _x: number | undefined

    get x(): number { return this._x ?? 0; }
    set x(value: number | undefined) { this._x = value; }

    bar() {
        this.x = this.x + 1; // fine
    }

    qux() {
        this.x += 1; // err
    }
}
```

### 🙁 Actual behavior

`this.x += 1` fails with `Object is possibly 'undefined'.`

### 🙂 Expected behavior

It should not fail.

**Comment by ritikBhandari** [comment]
Hi,
Can i resolve this issue?
