### ISSUE TITLE
Compiler allows 'number' to be used where enum is expected

### ISSUE THREAD

**Issue by AbakumovAlexandr** [microsoft/TypeScript#48296]
# Bug Report

Compiler shouldn't allow `number` to be used where `enum` is expected.

### 🔎 Search Terms

number where enum expected

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _enums_and_function_params_
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&ts=4.7.0-dev.20220302#code/KYDwDg9gTgLgBMAdgVwLZwMowIY2QZwFEV0BvAKDirgGFtEBjYAG2eABM4BeOAFgBpK1AArYAlpx4A2cgF9y5UJFhwxiGMCgAzbE0xpU2KAE84FanCjBs7CIman8OPPgBccEgCNNAbjkKlaHgGZmx8fDgAFSgxMAwDI1NzajAYgDdcYEtrW3tHZwJ3LFwCYjQ-ISowZE9mMQY4BjsnKGQGGGgACnYOooSTfjgnErcPNG8oAEozSos4GAALMXwAOmGXbiGC-B84AHo9rZHVCK9NQc9keGxWCAB3DnmIOG84MPwxAHNER463xAQJDgWjELHYswsEOoi2Wa2AMAAYshWMUXN0OmttpNdgc4D0IJjjssxqgJhcrm9bg9OH9XmB3o8wv9AWg4PSoNhULN5LNUmIMhohvCkSjtp11oVMNsyqhJu40hAJDM5tQmoh8BA2CtmBBPuKsX4LPJ5EA)

### 💻 Code

```
export enum StatusEnum {
    Cancelled = 4,
    Paid = 6
}

export interface Summary {
    readonly status: number;
}

export class TripSummary {
    private readonly status: StatusEnum;

    public constructor(dto: Summary, status: number) {
        this.status = status; // status is number, but allowed to be assigned to an enum field
        
        this.setFullStatus(dto.status); // dto.status is number, but allowed to be passed as an enum param
    }

    private setFullStatus(status: StatusEnum): void {
        console.log(status);
    }
}

```

### 🙁 Actual behavior

Compiler allows `number` to be used where `enum` is expected. It's incorrect because narrowing conversion is done implicitly while the compiler cannot make sure that a value passed as the enum param is within a range of the enum values.

### 🙂 Expected behavior

Implicit conversions from `number` to `enum` should generate an error requiring an explicit conversion to be performed (for exampe, using `as`)

**Comment by fatcerberus** [comment]
This is intentional because numeric enums are often used as bitfields, e.g. `FooEnum.Foo | FooEnum.Bar` is typed as `number` because it’s not explicitly part of the enum.  You can use string-valued enums for stricter checks.

**Comment by AbakumovAlexandr** [comment]
> This is intentional because numeric enums are often used as bitfields, e.g. `FooEnum.Foo | FooEnum.Bar` is typed as `number` because it’s not explicitly part of the enum. You can use string-valued enums for stricter checks.

Can you provide a full line of code to demostrate what you've meant? I'm not sure how this is related to allowing implicitly assigning numbers into enum typed members.

**Comment by AbakumovAlexandr** [comment]
@RyanCavanaugh What is the justification for 'Working as Intended'? Especially in 'strict' mode?

**Comment by fatcerberus** [comment]
```ts
let computedFlags = FlagsEnum.One | FlagsEnum.Two;
obj.flagsEnum = computedFlags;
```

`computedFlags` should ideally be assignable back to the enum type, if `obj` is using it as a bitfield.  However it’s currently typed as `number` because its actual value is not part of the enum.  Thus why this type hole is present.

**Comment by AbakumovAlexandr** [comment]
> ```ts
> let computedFlags = FlagsEnum.One | FlagsEnum.Two;
> obj.flagsEnum = computedFlags;
> ```
> 
> `computedFlags` should ideally be assignable back to the enum type, if `obj` is using it as a bitfield. However it’s currently typed as `number` because its actual value is not (necessarily) part of `FlagsEnum`. Thus why this type hole is present.

If you needed this type 'abuse' (in my opinion, sorry if too harsh :) ), you always could shut up the compiler explicitly:
```
let computedFlags: FlagsEnum = (FlagsEnum.One | FlagsEnum.Two) as FlagsEnum;
obj.flagsEnum = computedFlags;

```So, this bug doesn't affect your use case.

**Comment by RyanCavanaugh** [comment]
@AbakumovAlexandr because we did this behavior on purpose

**Comment by fatcerberus** [comment]
I’m not making any value judgments here, just telling you why the behavior is the way it is, and why it’s intentional.  It’s also unlikely to change—at least, not without an additional opt-in compiler flag—as it would be pretty disruptive to a lot of code in the wild.

**Comment by AbakumovAlexandr** [comment]
> @AbakumovAlexandr because we did this behavior on purpose

Can you elaborate: what is the purpose?

**Comment by fatcerberus** [comment]
> Can you elaborate: what is the purpose?

🤦‍♂️

**Comment by RyanCavanaugh** [comment]
So that you can use bitflag-style enums without getting an error, as described above.

**Comment by AbakumovAlexandr** [comment]
> So that you can use bitflag-style enums without getting an error, as described above.

So, what should I do to ensure that the value in an enum-typed member is actually the one I've defined in my enum without any runtime code?

**Comment by RyanCavanaugh** [comment]
There currently isn't a way to do that. The suggestion tracking adding a way to do so is #32690

**Comment by fatcerberus** [comment]
Use a string-valued enum.

**Comment by RyanCavanaugh** [comment]
You could also use a `const`-style enum
```ts
const StatusEnum = {
    Cancelled: 4,
    Paid: 6
} as const;
type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
```
from there the code sample works as desired

**Comment by AbakumovAlexandr** [comment]
> There currently isn't a way to do that. The suggestion tracking adding a way to do so is #32690

it's 3 years old :(

TypeScript is intended to bring static type safety. At the same time, its default behavior is to implicitly allow `(-Infinity, +Infinity)` where `(1, 2, 3)` only are explicitly expected including the 'strict' mode.

If someone wants to assign a value into an enum member which doesn't exist in its definition (bit flags), doesn't it look like it is him who should explicitly tell it to the compiler? Or what's even the point of enumerating possible values of an enum, then?

I just can't remember any other language with static types allowing this.

**Comment by fatcerberus** [comment]
This is how enums work in C++ and C#, too, fwiw.

**Comment by AbakumovAlexandr** [comment]
> This is how enums work in C++ and C#, too, fwiw.

Of course,  it's not true:
![image](https://user-images.githubusercontent.com/6968009/158708281-7466353a-caac-49f6-bc06-5dc3e06a830d.png)

**Comment by fatcerberus** [comment]
Re: Statically-typed languages and correctness, at this point I'm just going to leave this here:
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

> **Non-goals**
> 3. Apply a sound or "provably correct" type system. Instead, **strike a balance between correctness and productivity.**

**Comment by AbakumovAlexandr** [comment]
> Re: Statically-typed languages and correctness, at this point I'm just going to leave this here: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
> 
> > **Non-goals**
> > 3. Apply a sound or "provably correct" type system. Instead, **strike a balance between correctness and productivity.**

So what do you want to say by this exactly? 'The ability to do bit flagging with enums IMPLICITLY (when there's no problem to use `as` at all) is more productive than completely messing the primitive type system rules and breaking the MOST COMMON use case of enums'? Really?

Are you aware that such breakage leads to massive and undetectable at compile time issues. which is much more counter-productive(!) than the above 'inconvenience'?

How about [this one](https://stackblitz.com/edit/typescript-8hvuzg?file=index.ts)?

```
export enum StatusEnum {
  Cancelled = 4,
  Paid = 6
}

export interface Summary {
  readonly status: number;
}

export class TripSummary {
  private readonly status: StatusEnum;

  public constructor(status: number) {
      this.status = status; // status is number, but allowed to be assigned to an enum field
      console.log(this.status);
      
      const s: string = this.setFullStatus(100500); // dto.status is number, but allowed to be passed as an enum param
      
      if (s !== undefined)
        console.log("TypeScript rocks!");
      else
        console.log("Really? 'undefined' from the method which return type is 'string' (NOT 'string | undefined')???");
    }

  private setFullStatus(status: StatusEnum): string {
      switch(status) {
          case StatusEnum.Cancelled:
              return "Cancelled";
          case StatusEnum.Paid:
              return "Paid";
      }
  }
}

const ts: TripSummary = new TripSummary(200500);

```
![image](https://user-images.githubusercontent.com/6968009/158733346-c7c7c69c-5a7d-45ff-9779-5572359beaaf.png)

**Comment by RyanCavanaugh** [comment]
This doesn't seem like a productive discussion. A trade-off was intentionally made; if you don't agree with the trade-off that's fine but there's no value to be found in reiterating all the same discussion points that occurred at the point of the decision.
