### ISSUE TITLE
Visual Studio 2015 plugin completely broken

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#4830]
So i got the latest typescript plugin for VS 2015.

If i open a .ts file, VS does correctly recognize the `tsconfig.json` file in the root folder. However, it does not seem to be compiling any of my files to .js. I also cannot see any menu for settings when i right click on project name. 

![2015-09-16_1858](https://cloud.githubusercontent.com/assets/3190176/9923084/14014bfc-5ca5-11e5-9f9f-455885e4ac8b.png)

It is surprising that the plugin comes with zero documentation on how to setup a typescript project

**Comment by mhegazy** [comment]
tsconfig.json is not a project file. it is just a json file that tells the editor how to interpret your files. to build you have one of two options: 1. build from the command line e.g `tsc --p <path to the folder containing tsconfig>` or 2. using compile-on-save (disabled by default, to enable it go to tools\options\Text Editor\TypeScript\Project and select "Automatically compile TypeScript files which are not part of a project") see image below:
![image](https://cloud.githubusercontent.com/assets/8000722/9923312/55adcd52-5ca8-11e5-86dd-8ae7ac01c24b.png)

If you want your are *normal* project system support in VS, just create a new project from template, add your files to the project using add new/add existing, and edit the project properties using the project property pages.

![image](https://cloud.githubusercontent.com/assets/8000722/9923332/92f36226-5ca8-11e5-8b76-c439de492951.png)


for more documentation about tsconfig.json please see: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json, hope that helps!

**Comment by pdeva** [comment]
the link you gave has no mention of visual studio. I know how a tsconfig file works.

If I have to give visual studio all the settings in that dialog box, then what is the use of tsconfig.json?

**Comment by RichiCoder1** [comment]
For systems like node.js, where vs (and msbuild) aren't at all involved in the build.

**Comment by mhegazy** [comment]
You have the options, either use your MSBuild project file, with a normal .csproj/.vbproj, .jsproj, etc.. TypeScript will fit in there like a any other language in VS.

The other option is to use tsconfig.json, use your json editor to modify it, and the language service will pick it up.

The choice is yours.

**Comment by pdeva** [comment]
yeah well if u use tsconfig, visual studio has no idea of any other files in the directory like gulpfile or package.json.
this is as good as tsconfig not being supported at all, since you cant use this to develop a real app.

**Comment by mpawelski** [comment]
I also must agree with pdeva.

In comment in blog post about release of TS 1.6 you say that "VS2015 has full support for tsconfig.json since RTM" ([link](http://blogs.msdn.com/b/typescript/archive/2015/09/16/announcing-typescript-1-6.aspx))
But can we really use tsconfig.json in existing ASP.NET MVC app that is using MSBuild and make VisualStudio to use tsconfig.json to get options to compile .ts files correctly?

Right now I still don't know if it is possible.

**Comment by mhegazy** [comment]
One thing to note, all compiler flags that are available through tsconfig.json are already available through your MSBuild project file, here is a list of mappings compiler options to MSBuild properties: https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects

ASP.net 5 project having to put tsconfig.json files in the script directory has been resolved in 1.6, you can now place it at the root, and it should work normally. see #4161 for more information.

For the next release, we intend to make the interaction smoother, allowing for tsconfig support in a project file is tracked by #3949, and multiple tsconfig in a single project is tracked by #4714
