### ISSUE TITLE
Class methods are missing in destructuring assignement with ...rest pattern

### ISSUE THREAD

**Issue by jbmaisner** [microsoft/TypeScript#48308]
# Bug Report

When using destructuring assignment with the '...' rest pattern, methods from source object are missing.

### 🔎 Search Terms

typescript destructuring remaining items missing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about destructuring

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAuBhcVoG8BQBIADgE4D2+AjNALzRkDceRpATFdAERNv0En4DMrNkgAWhePC7Y8wYgDtkhAK7AkxQtAAUASiwBfKbgC28EcQAmFbXrzHTZllcz6jJ4eYGP9+7DPlIs0IzkADTQAHQRYsjQuqyy8ADucIio6BDa9NgA9FnQIvDQtm5mMGBihQCWUBWyAObQNexRSGzQvshgskhAA)

### 💻 Code

```ts
class TestClass {
	prop1 = 1;
	prop2 = "2";
	prop3 = "three";

	constructor () {}

	method1 () {}
	method2 () {}
	method3 () {}
}

const { prop1, ...rest } = new TestClass();

// the methods are missing in "rest" constant
```

### 🙁 Actual behavior

the methods are missing in "rest" constant

### 🙂 Expected behavior

the methods should be available in "rest" constant

**Comment by MartinJohns** [comment]
That behaviour is correct. The rest object does not actually have those methods at runtime either.

**Comment by jbmaisner** [comment]
> That behaviour is correct. The rest object does not actually have those methods at runtime either.

Thanks for your answer, I didn't know that.
Is there a better and more elegant way to declare both variables `test` and `prop1` ?

```ts
const test = new TestClass();
const { prop1 } = test;
```

**Comment by fatcerberus** [comment]
No, and just to be clear, your original example wouldn’t have done that either, even if it preserved the methods—`rest` ends up missing `prop1` and therefore can’t be a valid `TestClass`.
