### ISSUE TITLE
Class member lost after TSC command

### ISSUE THREAD

**Issue by yinhunfeixue** [microsoft/TypeScript#48302]
# Bug Report

![image](https://user-images.githubusercontent.com/29660825/158721923-57534a68-1e71-4a58-9fd0-b79191dd2f46.png)

### 🕗 Version & Regression Information
4.6.2

### 💻 Code
```
class MyClass {
  public attribute?: string = undefined
  public attribute2?: string;
}

export default MyClass
```

```
import MyClass from './MyClass';

const p = new MyClass();
for (let key in p) {
  console.log('key=', key)
}
```

### 🙁 Actual behavior
Only ‘attribute’ is printed

### 🙂 Expected behavior

Output "attribute、attribute1"

**Comment by Josh-Cena** [comment]
`attribute2` is never assigned. It only exists as a type signature telling the outside that this property _might_ exist, but it has never been actually initialized.

**Comment by yinhunfeixue** [comment]
> `attribute2` is never assigned. It only exists as a type signature telling the outside that this property _might_ exist, but it has never been actually initialized.

Is there any way to set `attribute2` to undefined？  can be obtained in` for in`?

**Comment by fatcerberus** [comment]
You could enable `--useDefineForClassFields`.
