### ISSUE TITLE
Object.defineProperty improvement

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#48306]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- `F2 renaming lazy property`
- `Object.defineProperty`
- `syntax sugar`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Syntax sugar
```ts
interface Foo {
    readonly bar?: string
}

const foo: Foo = {}

foo.bar = prop {
    get: () => {
        return 'lazy prop'
    }
}
```

Equals to
```ts
interface Foo {
    readonly bar?: string
}

const foo: Foo = {}

Object.defineProperty(foo, 'bar', {
    get: () => {
        return 'lazy prop'
    }
})

```

## 📃 Motivating Example

When renaming interface `Foo` property from name `bar` to `zzz`,

Expect code `Object.defineProperty(foo, 'zzz', {`.

But actually still `Object.defineProperty(foo, 'bar', {`.

So, here is a feature request

```ts
obj.lazyprop = prop descriptor
```

de-sugar to 

```ts
Object.defineProperty(obj, lazyprop, descriptor)
```

Or, **maybe better if possible to implement**, update property name argument of `Object.defineProperty(obj, prop, descriptor)`

## 💻 Use Cases

When renaming interface `Foo` property from name `bar` to `zzz`, don't left lazy property behind.

**Comment by Josh-Cena** [comment]
Unfortunately, this is a "non-ECMAScript syntax with JavaScript output" and violates the design goal.

**Comment by MartinJohns** [comment]
> [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

Your suggestion would be an expression-level syntax and is against goal 8.
