### ISSUE TITLE
typeof ignoring early return when used in object with string keys

### ISSUE THREAD

**Issue by equal-matt** [microsoft/TypeScript#48307]
# Bug Report

### 🔎 Search Terms

typeof, guard, early return, object, keys, null

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _everything(?)_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/GYVwdgxgLglg9mABAEzgZTgWwKZQBYxgDmAFAJSIDeAUInYhAgM5SKYCeAKgcYgLyIAsgEN8AOgBOwsKkzlEAPkQAGMQFZEAfiqJgcOAC5EAcgBGwiccQBfREbAgANo4DctejGCISAQg7dCIgoJXBAJMDd3OkYwFkQ4AGthLh4iI0pdfSModgAHbDgvf1SxPTgbfh0yozMLK2sohmZWMDgoAHkklMD0xABtBOx2IxYJQIBdbLyCou7iUv0KgQzqk3NLG2oGoA)

### 💻 Code

```ts
function doSomething() {
    const myThing = Math.random() > 0.5 ? { foo: 'bar' } : null;
    if (!myThing) return;

    const okayThing: { foo: typeof myThing.foo } = { foo: 'bar' }
    const notOkayThing: { [key: string]: typeof myThing.foo } = { foo: 'bar' }
    // Error: Object is possibly 'null'
}
```

### 🙁 Actual behavior

`notOkayThing` errors with `Object is possibly 'null'`.

### 🙂 Expected behavior

Types for values in `okayThing` and `notOkayThing` should be equivalent.

**Comment by Blopaa** [comment]
@ritikBhandari are you working on this issue, if not I would like to try to resolve the issue.

**Comment by ritikBhandari** [comment]
@Blopaa I'm working on another issue. You can try it! :)
