### ISSUE TITLE
NumberFormatOptions is missing currencyDisplay option

### ISSUE THREAD

**Issue by hknguyenvu** [microsoft/TypeScript#48319]
# Bug Report

currencyDisplay is missing from NumberFormatOptions

### 🔎 Search Terms

currencyDisplay

### 🕗 Version & Regression Information

version "4.6.2"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220302#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmC7nS22gAGF8U5zHgef1IBJQABJI0BABy7EQ0m+ADFxYg6kqAOTcBilAAi8T9-AA3qAfasoa6PWQGLB6o1gxRtKgCqAAEx2VB4dz5UB+2BmlGwPDhkxli1Fv3BgDSDarpbI5oracECyYdYQ3EgftAAF8dQBuYIqHDNDxkLyIcXOYHsGhfNxmZjsBjMSD8WDQdSJDnwPQiLx8ukMpmCPlJbF88AOVB+4ROm18oIqADyXzI70EO60SAjlQRwFFcaRLScecdGGLB9BQBBEGhYRLlXCRxWiEQDA4bFuxYNguG4IISiAA)

### 💻 Code

```ts
let intlCurrency = new Intl.NumberFormat('da-Dk', { maximumFractionDigits: 2, style: 'currency', currency: 'DKK', currencyDisplay: 'code' });
```

### 🙁 Actual behavior

I get a TS error Object literal may only specify known properties, and 'currencyDisplay' does not exist in type 'NumberFormatOptions'.

### 🙂 Expected behavior

No Error

**Comment by MartinJohns** [comment]
You're targeting ES2017, but `currencyDisplay` is only supported from ES2020 or later.

**Comment by hknguyenvu** [comment]
> You're targeting ES2017, but `currencyDisplay` is only supported from ES2020 or later.

I see. Do you know any cheat sheet to research related issues easier?

Thanks so much
