### ISSUE TITLE
Redundant `await` added

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#48312]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.7.0-dev.20220316

**Search Terms**
- suggest / suggestions
- completions
- async
- await

---

Steps to Reproduce:

1. have something that returns an object as promise
2. type to access a property without awaiting

=> 2 awaits added

![Recording 2022-03-16 at 08 30 32](https://user-images.githubusercontent.com/900690/158538669-cbd59b09-5999-48e5-aa8f-fe8bcb5ac50e.gif)

**Comment by mjbvz** [comment]
Simply repo:

```ts
async function foo() {
    const a = await fetch('.'). // Trigger suggest here an accept the suggestion for `.blob`
}
```

**Comment by MQuy** [comment]
hi, I would like to work in this bug :D

**Comment by fatcerberus** [comment]
Isn’t the second await necessary in the `fetch` example? (i.e. await `fetch()`, then await the promise returned by `.blob()`).  In the OP, `entry` doesn’t seem to be a promise.

**Comment by MQuy** [comment]
@fatcerberus autocompletion only suggests properties and use that property if you select it, it doesn't auto completing a function call so another `await` is not necessary.
 
@mjbvz, I am creating a test case for this issue, but it seems that the completion list only have `catch` and `then`. I am not sure what I am missing?
https://github.com/microsoft/TypeScript/pull/48328
