### ISSUE TITLE
IntrinsicElements are not supporting hyphens in their properties.

### ISSUE THREAD

**Issue by msteller-connyun** [microsoft/TypeScript#48324]
# Bug Report

IntrinsicElements are not supporting hyphens in their properties.

### 🕗 Version & Regression Information

"typescript": "^4.4.2"

### 💻 Code

```
export interface DataTable {
  data?: object
  'rows-per-page'?: number
  'sort-multi'?: boolean
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "kds-data-table": KdsDataTable
    }
  }
}
```

### 🙁 Actual behavior

<img width="568" alt="image" src="https://user-images.githubusercontent.com/31731643/159019148-2fe4070a-ebc4-4a0a-8afa-4532eee1fade.png">

### 🙂 Expected behavior

The hyphens attribute should be accepted.
At the moment it's only working in camel-case, which is not optimal for custom elements, used in React.

**Comment by RyanCavanaugh** [comment]
This error isn't issued by TypeScript. It looks like Android Studio generates this message.
