### ISSUE TITLE
Unable to widen an indirectly recursive generic type

### ISSUE THREAD

**Issue by maxxxxxdlp** [microsoft/TypeScript#48339]
# Bug Report

Trying to assign a subtype to a type produces an error when those types have a nondirect recursion and a generic argument with a constraint. In the error message, the constraint and the provided generic type switch places.

### 🔎 Search Terms

Closed and open issues that contain `generic` and `recursive`

### 🕗 Version & Regression Information

Reproduced in nightly, 4.6.2, 4.5.4, 4.0.5, 3.3.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common Bugs, Type System Behavior, Generics
- I was unable to test this on prior versions because 3.3.3 is the earliest version in TS Playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0&ts=4.6.2#code/PTAEBEFMDMEsDtYBdYHt4GcBQSCeAHSUAFQEMAjAG0gEFQBeUAcjKtqYG4cCjXqAhBsz6R+nboVA14uEUJYVqNJqAA+wxaPESiAWVQATSJQA8xGvwAyAUQD6AORq7roSAA8kkeAYxSZIgD4hAG8sUHD4UgBbSAAuEgsbBydrLnDQAGNUSmoMlHR4gGFs3Pz4M0S7R2cArgBfLB1QYpzIPLRy8ysqlNcPLx8-WU0gxlDw0gMDeIAKACdIDFQAVzmMuNAAJUWVtcgK7uSagEoGIIA3VFgDeq4m7aXV9YOk6pd3T29faWG2UdBxqAooZjPF9EZTF1Xilalg6ncQFI8stSJRQPg5qg2FEsIiAJKgaKgZYYBAAc1AACJlvAANbwVAAd3glNACFASAAFkR4B9QJQEEQ5qQuZA5hzOaR4ISMKSyYh4BSMahCOK8JJ2ag5kY1ahQAsDMt1hKiKSAF5EVDQCWwXzuaL4agAOlAeKQoAMqEWoAZ7tI0GgbXdotA5GWZKwWUw7oWjz28hUpF8NPpTOlSa2Oye+xENFhiOsc0x4tQGQyq183IWsUj6AwfpkD1263iTezJh+gSEsebkA4QA)

### 💻 Code

```ts
// Definitions
type TableA = 'TableA';
type TableB = 'TableB';
type AnyTable = 'TableA' | 'TableB';

type Model<TABLE_NAME extends AnyTable> = {
   name: TABLE_NAME;
   collection: Collection<TABLE_NAME>;
}

type Collection<TABLE_NAME extends AnyTable> = {
  add: (resource: Resource<TABLE_NAME>) => void;
};

type Resource<TABLE_NAME extends AnyTable> = {
  model: Model<TABLE_NAME>;
};

// Actual problem
// I am using "unknown" in the next line rather than assigning from a proper type in order to reduce the size of this example. It does not affect the bug
const resource = '' as unknown as Resource<TableA>;
// Error occurs here:
const anyResource: Resource<AnyTable> = resource;
```

The example is a significantly simplified piece from a much larger codebase, which is why it looks so contrived

### 🙁 Actual behavior

The following error is produced:
```markdown
1. Type 'Resource<"TableA">' is not assignable to type 'Resource<AnyTable>'.
2.   The types of 'model.collection.add' are incompatible between these types.
3.    Type '(resource: Resource<"TableA">) => void' is not assignable to type '(resource: Resource<AnyTable>) => void'.
4.      Types of parameters 'resource' and 'resource' are incompatible.
5.        Type 'Resource<AnyTable>' is not assignable to type 'Resource<"TableA">'.
6.          The types of 'model.name' are incompatible between these types.
7.            Type 'AnyTable' is not assignable to type '"TableA"'.
8.              Type '"TableB"' is not assignable to type '"TableA"'.
```
**Note how "TableA" and "AnyTable" switch places between lines 3 and 5**

Slight changes to the code snipped cause the bug to disappear. Examples:
 - Replacing `add: (resource: Resource<TABLE_NAME>) => void;` in the code snippet with a direct reference (e.g `resource: Resource<TABLE_NAME>`) does not cause the bug to happen.
 - Getting rid of the Collection type and having Model reference Resource directly does not cause the bug to happen.

The bug also happens when Model, Collection and Resource are defined as interfaces instead of types

### 🙂 Expected behavior

The error should not happen as `TableA` is a subtype of `AnyTable`, and thus widening of types should be allowed.

**Comment by MartinJohns** [comment]
This looks like it's working correctly. Here's a simplified example demonstrating your issue:

```typescript
type Kind = 'A' | 'B'
type Example<K extends Kind> = {
  add: (kind: K) => void;
}

declare const e: Example<'A'>
const anyExample: Example<Kind> = e
```

Accessing `anyExample` would allow to invoke `add` with either `'A'` or `'B'`, when the instance is actually an `Example<'A'>` and as a result only allows invocation of `add` using `'A'`.

**Comment by maxxxxxdlp** [comment]
This makes sense now
Thank you for your help
