### ISSUE TITLE
intersection result in 4.x behave differently

### ISSUE THREAD

**Issue by lynnic26** [microsoft/TypeScript#48336]
# Bug Report
### 🔎 Search Terms
intersection type
### 🕗 Version & Regression Information
- changes between versions 3.9 and 4.x
### ⏯ Playground Link
[typescript playground](https://www.typescriptlang.org/play?ts=4.6.2&ssl=19&ssc=29&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4ChnLgLmQGcwpQBzAbh2QUJLJCqwF8stRJZEUAhTGgWKkK1XHWQAjAPbSANhDghqbDuGjwkyAMIDcQhqJoSQAVwC2k6CvYB6W8k7QiEBGGDSQyKBCKm5YI5EyCAQAG7QWGAAngAOKE5QLm4eIKj8ALxoyABkyLzU9o7qSa7unt6+-oHAweh52lFxCSXJ5Wm6WfU61OxYQA)
### 💻 Code
```
interface A {
  a: string;
  c: string;
}

interface B {
  a: string;
  c: boolean;
}

interface C {
  a: string;
  c: number;
}
```

### 🙁 Actual behavior
```
// intersection result is never
type intersectionAB = A & B;
// intersection result is A & C
type intersectionAC = A & C;
```

### 🙂 Expected behavior
```
// intersection result is never
type intersectionAB = A & B;
// intersection result is never too
type intersectionAC = A & C;
```

**Comment by MartinJohns** [comment]
1. You forgot to fill out the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md).
2. This change happened within 3.x already (specifically 3.9).
3. This change is intended and correct. The new behaviour is right: The type can't ever be represented.
4. This change was [documented](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#intersections-reduced-by-discriminant-properties).

**Comment by lynnic26** [comment]
> MartinJohns

sorry, updated
