### ISSUE TITLE
Compile error when trying to return a type predicate closure from a function

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#48332]
# Bug Report

### 🔎 Search Terms

"type predicate"
"must be a type predicate"

### 🕗 Version & Regression Information

4.6.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `type predicates`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.3.5#code/LAKALgngDgpgBAFQBYEsB2BzA6gSTEnAEwB4E4YAPMGNQgZzjrACd0MA+OAXjgG9Q4cFIQBciANygAvqFAAzAK5oAxmBQB7NELrI2WFPiKlyVGvUYs27ABTCxCAJRjrANwCGAGwUwxbtBAduTncveBQGXUxcQxIEdn4QQWVNJjgoZhhCFGU3amcQ719-QK5gz29tRFQovAJYzh4C+FLtSOwDOpwAWygPV3KYABohQgdJRLgBOAywBWYtdMzs3JhxmRB5JVUNLXC2-Rju3uNKaloGJlZMGyaiiGG7RCc4Jsr92qM4hMFBGbmtFjeNZAA)

### 💻 Code

```ts
type ThingWithId<T extends string> = {
  id: T;
}

function isThingWithId<T extends string>(id: T): (value: any) => value is ThingWIthId<T>{
  const predicate: (value: any) => value is ThingWIthId<T> = value => isThingWithIdImpl(value, id);
  
  return predicate;
}

function isThingWithIdImpl<T extends string>(value: any, id: T): value is ThingWIthId<T>{
    return true;
}
```

### 🙁 Actual behavior

Error: 
```
Type '(value: any) => boolean' is not assignable to type '(value: any) => value is ThingWIthId<T>'.
  Signature '(value: any): boolean' must be a type predicate.
```

### 🙂 Expected behavior

Should compile fine

**Comment by MartinJohns** [comment]
You haven't typed your anonymous function, so the return type is inferred as `boolean`. When you type it correctly it will work.

```typescript
(value): value is ThingWIthId<T> => isThingWithIdImpl(value, id);
```

**Comment by Roaders** [comment]
ok... So this works:

```ts
function isThingWithId<T extends string>(id: T): (value: any) => value is ThingWIthId<T>{
  return function(value: any) : value is ThingWIthId<T>{
    return isThingWithIdImpl(value, id)
  }
}
```

how would I type my original code using a lambda?

**Comment by MartinJohns** [comment]
> how would I type my original code using a lambda?

[I.. told you already..?](https://github.com/microsoft/TypeScript/issues/48332#issuecomment-1072955901)

```typescript
function isThingWithId<T extends string>(id: T): (value: any) => value is ThingWIthId<T>{
  const predicate: (value: any) => value is ThingWIthId<T> = (value): value is ThingWIthId<T> => isThingWithIdImpl(value, id);
  
  return predicate;
}
```

Or simplified:

```typescript
function isThingWithId<T extends string>(id: T): (value: any) => value is ThingWIthId<T>{
  const predicate = (value: any): value is ThingWIthId<T> => isThingWithIdImpl(value, id);
  
  return predicate;
}
```

**Comment by Roaders** [comment]
ok, thanks. Couldn't quite see how to apply the type to the function but yes. Obvious now.
