### ISSUE TITLE
statement.getFullText() errors if program.getTypeChecker() is not called beforehand

### ISSUE THREAD

**Issue by LarryWu1** [microsoft/TypeScript#48333]
# Bug Report

### 🔎 Search Terms

typescript getFullText cannot find property text of undefined
typescript how to get statement text

### 🕗 Version & Regression Information

Happens in typescript v2, v3, v4

### ⏯ Playground Link

This is a typescript compiler API bug. Playground link is not applicable.

### 💻 Code

Repro steps:

1. npm install typescript

2. Create a `src/test.ts` with contents:
```
const a = 5
```

3. Create `src/run.js` with contents:
```
const ts = require('typescript')

const src = `${__dirname}/test.ts`
const program = ts.createProgram([src], {})

const f = program.getSourceFile(src)
console.log(f.statements[0].getFullText())
```

4. Run `node run.js` inside `src/`

### 🙁 Actual behavior

Error message:
```
C:\Users\someuser\Desktop\test\node_modules\typescript\lib\typescript.js:106693
            return (sourceFile || this.getSourceFile()).text.substring(this.pos, this.end);
                                                        ^

TypeError: Cannot read property 'text' of undefined
```

### 🙂 Expected behavior

This should print `const a = 5`.

Adding `program.getTypeChecker()` before calling `.getFullText()` works:

```
const ts = require('typescript')

const src = `${__dirname}/test.ts`
const program = ts.createProgram([src], {})

const f = program.getSourceFile(src)
program.getTypeChecker()
console.log(f.statements[0].getFullText())
```

**Comment by RyanCavanaugh** [comment]
These functions depend on parent references being set, but this doesn't happen until the binder runs which occurs as part of `getTypeChecker`. Based on the use cases it seems like you want to call `createSourceFile` with `setParentNodes = true`

**Comment by LarryWu1** [comment]
Why is there an expectation I should call `program.getTypeChecker()` to get text for nodes when I'm not using the `TypeChecker`? I spent hours trying to figure out why AST source files weren't set. Would appreciate if there's some documentation.

My real use case is finding interfaces with a specific name, but in the future I may rely on `.getFullText()` for other things.

**Comment by RyanCavanaugh** [comment]
This is necessary for performance reasons to get the un-parented ASTs back as quickly as possible. Setting the parent references requires an additional pass over the tree and API scenarios that don't require those references are expecting to not pay that performance penalty.
