### ISSUE TITLE
Hide method completions with incompatible `this` parameters

### ISSUE THREAD

**Issue by shaylew** [microsoft/TypeScript#48343]
# Suggestion

## 🔍 Search Terms

intellisense, completions, this parameter, this type, method receiver

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When showing completion results for methods after a receiver with a known type, intellisense should hide methods that have an explicit `this` parameter if the receiver definitively isn't assignable to it. Trying to call one of these methods is always a type error, so displaying them just clutters things up and hampers discoverability by leading the user down dead ends.

## 📃 Motivating Example

Here's a simple wrapper class illustrating the problem. The `map` method is intended to only be applicable when the wrapped value is an array. This works fine in the type system (it's an error to try to use `b.map` when `b` is a `Wrap<number>`), but showing `map` as a possible completion after `b.` is somewhat misleading.

[Playground link](https://www.typescriptlang.org/play?target=9#code/MYGwhgzhAEDqBOYAOAeAKgPmgbwLAChppgB7AOwgBd4BXYSk+ACngFMwATckAT2gDcwIGqwBc0NAEocAXwIEiAW2QoAggBpoAIQxNKACwCWEcQhWqA2gF0MmgGZlxTQ5VaLxG6IfFkaigEas8NIAvFhakqaIqFrWWHiERNBslDTwZNBkrADucNF6RhAAdILCrEXKSEwOkpIK0HL4jQQA9C15yDBgGWDwiDyaECTQPCQ0xN3QlV6U0ABWNFTQdoZZRQSkFLNg0CGZOR1VFgDkRsdWdfhgFchMTPyhWAAGACTY-DKa2YwgHE+XrXaZiQXUyfkC8HW+Da0Ce-huSCeXi6IGyYB4oMoPCQrGgQXgjE0-hosxc0Ag+hI2RgNCQXgypEUSBArEohnIXTIPDRPChmyW-l2+1ywKYAAZLvDKncHrssABGSRAA)

```typescript
class Wrap<T> {
  constructor(readonly value: T) {}

  map<A, B>(this: Wrap<A[]>, fn: (item: A, i: number) => B): Wrap<B[]> {
    return new Wrap(this.value.map(fn))
  }
}

// Wraps an array, so you can map it just fine.
const a = new Wrap(['hi'])
a.map((v) => `${v}, world`)

// Wraps a number.
// `b.map` is always a type error, but it shows up in completions anyway.
const b = new Wrap(0)
b.map((v) => 1)
```

## 💻 Use Cases

I ran into a situation very similar to the `Wrap` example above while writing a reactive programming library. Certain operations on reactive collections ("map over a reactive array", "get the value at key K from a reactive map", etc.) admit a more efficient implementation than just "rerun the operation when the collection changes", and it's convenient to expose these as methods on a `Reactive<Map<K, V>>` that wouldn't be present on a `Reactive<number>`, rather than having a separate  `ReactiveMap<K, V>` type. Since the type checking works fine, I'm likely to go with this approach anyway -- but it'd be nice if the completions were better.

I suspect this sort of thing is relevant to other frameworks with strongly-typed wrappers: reactive frameworks, ORMs, handles to typed objects provided by some external system, EDSLs that want to use the host type system to check the embedded language, etc.

**Comment by RyanCavanaugh** [comment]
We've looked into similar requests before and this unfortunately doesn't pencil out from a performance vs usability perspective. The cost to compute if the current `this` matches a given target `this` is effectively unbounded, and we'd have to do that work on every completion invocation up front since there's no mechanism to do a "deferred removal" of an item (to say nothing of how janky that would look in realtime). In some frameworks this was 30% or worse hit on every `.` keystroke. Even determining whether or not a method *has* a `this` parameter isn't free since base class type resolution might do extra work that wasn't going to happen already. Most methods with `this` parameters are `this: this` (or even `this: Base` where we'd have to do the work but the answer is effectively predestined), so even a first-pass filter to determine if there's any checking to do at all is still going to burn a lot of battery for not much UX enhancement.

If `this`-filtering were *common* it might maybe be worth considering, but in practice this is very often going to remove no methods at all.

**Comment by shaylew** [comment]
Oh, yeah, that makes total sense -- I was thinking about it from the side of "the type system already knows all this" but of course this is on the hot path for a system that doesn't know it _immediately_ and cares about the cost of having to figure it out.

For anyone who stumbles across this in the future with the same request, here's one alternative if you _really_ care about the completions here and are willing to sacrifice other aspects of type ergonomics. You can make two separate interfaces, with a conditional type that chooses the right one based on its parameter. Then you continue writing `Wrap<T>` in declarations, return types, etc. and it will resolve to an interface that has only the applicable methods for the situation -- even if concretely it's always going to be the same class.

```typescript
type Wrap<T> = T extends unknown[] ? WrappedArray<T> : WrappedValue<T>

interface WrappedValue<T> {
  value: T
}

interface WrappedArray<T extends unknown[]> extends WrappedValue<T> {
  map<A, B>(this: Wrap<A[]>, fn: (item: A, i: number) => B): Wrap<B[]>
}

// Can't write out the implements clause for it, but also implements WrappedArray<T>
// whenever T extends unknown[].
class Wrapper<T> implements WrappedValue<T> {
  constructor(readonly value: T) {}

  map<A, B>(this: Wrap<A[]>, fn: (item: A, i: number) => B): Wrap<B[]> {
    return new Wrapper(this.value.map(fn))
  }
}

function wrap<T>(value: T): Wrap<T> {
  // Not sure how to get this to be accepted without a cast; it's true for any individual type
  // that's either array-ish or not, but not for a generic T that might or might not be array-ish.
  return new Wrapper(value) as Wrap<T>
}

// Wraps an array, inferred to be a WrappedArray<string[]>, so you can map it just fine.
const a = wrap(['hi'])
a.map((v) => `${v}, world`)

// Wraps a number, inferred to be a WrappedValue<number>, has no map method on the interface.
const b = wrap(0)
```

As you can see, there are some infelicities here from breaking parametricity and using a conditional type that can't always be resolved to a specific branch. Not worth it for me, but it might be workable for someone else's use case.
