### ISSUE TITLE
`tsc --noEmit` silent fail

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#48341]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ___Version 4.6.2___ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
$ docker run -w /prj -it node:16 bash
```
```sh
$ npm -g i typescript@4.6.2
$ npm init -y
$ tsc --init
$ grep '"target"' tsconfig.json
"target": "es2016",

$ echo 'Object.entries({})' > index.ts
$ tsc --noEmit
error TS2550: Property 'entries' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2017' or later

$ npm i -D sort-package-json@1.54.0
$ tsc --noEmit && echo 'Silent fail: expect error!'
Silent fail: expect error!
```

### 🙁 Actual behavior

```sh
$ npm i -D sort-package-json@1.54.0
$ tsc --noEmit && echo 'Silent fail: expect error!'
Silent fail: expect error!
```

### 🙂 Expected behavior

```sh
$ npm i -D {{any_package}} 
$ tsc --noEmit && echo 'Silent fail: expect error!'
error TS2550: Property 'entries' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2017' or later
```

**Comment by MartinJohns** [comment]
> tsc --init

FYI, this is pointless. You're not using the generated tsconfig anyway.

**Comment by MartinJohns** [comment]
You're installing `sort-package-json`, which includes the `@types/node` package. This package includes the `es2020` lib in the `index.d.ts` file (line 72), which provides type definitions for `Object.entries()`.

This is no issue with TypeScript.

**Comment by loynoir** [comment]
@MartinJohns 
Is there any options in `{{base}}/tsconfig.json`, which let `{{base}}/node_modules/**/*` will have no effect for type checking?

In another word, given 
- want to limit target environment to `es2016`, lint any syntax > es2016
- dev tool X refer to `@types/node@17.0.21`, eg: sort-package-json@1.54.0

How can I lint any syntax > es2016, after install X as devDependecy?

**Comment by loynoir** [comment]
@MartinJohns 

Ah, beside of `npx` approach, found pnpm `public-hoist-pattern` approach

```
; // .npmrc
; default:  https://pnpm.io/npmrc#public-hoist-pattern
; remove '*types*' from default
public-hoist-pattern[]='*eslint*', '@prettier/plugin-*', '*prettier-plugin-*
```

Is there a `tsconfig.json` approach?

**Comment by MartinJohns** [comment]
https://www.typescriptlang.org/tsconfig#types
