### ISSUE TITLE
Current (1.6) TypeScript Specification documents (.docx & .pdf) still point to 1.5 version

### ISSUE THREAD

**Issue by cyparu** [Microsoft/TypeScript#4834]
The current TypeScript Specification documents [.docx](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.docx) & [.pdf](http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf) are obsolete, pointing to v1.5 from February 2015.

**Comment by mhegazy** [comment]
can you refresh the website in your browser (ctrl+R). the links should be updated.

md: https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md
doc: https://github.com/Microsoft/TypeScript/blob/master/doc/TypeScript%20Language%20Specification.docx?raw=true
pdf: https://github.com/Microsoft/TypeScript/blob/master/doc/TypeScript%20Language%20Specification.pdf?raw=true

**Comment by cyparu** [comment]
It look like **typescriptlang.org** still points to 1.5: http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf
http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.docx

**Comment by mhegazy** [comment]
@cyparu i have tried on a few other machines, and i see the updated links. i think you have a caching issue going on.

**Comment by cyparu** [comment]
Hmm .. please note that I'm referring to **typescriptlang.org** location (not **github.com** ones that are fine) ... that definitely & reproductively load 1.5 ...

**Comment by danquirk** [comment]
I see the confusion. Where are those links on the website? This:
![image](https://cloud.githubusercontent.com/assets/7121557/9970164/6769170c-5e08-11e5-803c-5276a5c4952a.png)
and
![image](https://cloud.githubusercontent.com/assets/7121557/9970175/7763281e-5e08-11e5-931a-7e8e8117c078.png)
both point directly into the GitHub repo. You're looking at things in the /Content directly but I don't see which links on the website point there.

**Comment by cyparu** [comment]
The links from the GitHub repo: https://github.com/Microsoft/TypeScript#contribute under _Read the language specification ([docx](http://go.microsoft.com/fwlink/?LinkId=267121), [pdf](http://go.microsoft.com/fwlink/?LinkId=267238))_ are actually pointing (as previously the ones on  **typescriptlang.org**) to old locations/version. The **github.com** links by @mhegazy are pointing corectly to 1.6.

**Comment by DanielRosenwasser** [comment]
Thanks @cyparu, I addressed this in https://github.com/Microsoft/TypeScript/commit/e4f0ebbb3ef354fbd156aa5f1663133b01149bc7. Feel free to send us a pull request in the future.
