### ISSUE TITLE
Control Flow Analysis for Dependent Parameters doesn't work when the parameters are generic

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#48345]
# Bug Report

### 🔎 Search Terms
Control Flow Analysis for Dependent Parameters generic 

### 🕗 Version & Regression Information
v4.7.0-dev.20220302
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220302#code/C4TwDgpgBAYgrgOwMZQLxQDwBUoQB7AQIAmAzlANoBEAhlQDRQJwC2ARhAE4C6UAPpSpsGUUsE4BLBAHNuAPgAUAOhU1O00gC4oWAJRo5UAG4B7CcQDcAKCtITCMVABmARm3xkaKAoDWU4oxgNCAANiY0xPqohgDeVlAJUBJO3n4kaKjotFT6cYn5UEGh4cRKwCYwEngQxAq6FgkA9I24nJwmnPGJAL5dCcmp-hlZwrl9BUVhEWUmAKpgkJwAwjSkEHUNUM2t7Z35vd0WQA)

### 💻 Code

```ts
type Func = <T extends ["a", number] | ["b", string]>(...args: T) => void;

const f1: Func = (kind, payload) => {
    if (kind === "a") {
        payload.toFixed();  // error
    }
    if (kind === "b") {
        payload.toUpperCase();  // error
    }
};
```

### 🙁 Actual behavior
parameter type not narrowed

### 🙂 Expected behavior
parameter type is narrowed, like in the example from the [typescript 4.6 blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6-beta/#control-flow-analysis-for-dependent-parameters)

```ts
type Func = (...args: ["a", number] | ["b", string]) => void;

const f1: Func = (kind, payload) => {
    if (kind === "a") {
        payload.toFixed();  // 'payload' narrowed to 'number'
    }
    if (kind === "b") {
        payload.toUpperCase();  // 'payload' narrowed to 'string'
    }
};

f1("a", 42);
f1("b", "hello");
```

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts?

**Comment by ahejlsberg** [comment]
Yeah, that ought to work. Very easy fix. I'll put up a PR.
