### ISSUE TITLE
Colorization of JSX code in VS 2015

### ISSUE THREAD

**Issue by djanosik** [Microsoft/TypeScript#4835]
Hi,

I've installed TypeScript 1.6 and tried to replace my `.jsx` files with `.tsx`. Everything works as expected except that JSX code is not colorized. I've tried to reset my "Fonts and Colors"  settings, but nothing helps.

![tsx](https://cloud.githubusercontent.com/assets/858180/9927173/7b0927c6-5d1c-11e5-9ae9-5d07df834c10.png)

Is that supposed to work? Is there any way to fix this?

Thank you!

**Comment by DanielRosenwasser** [comment]
This is actually a known issue and is unfortunately we won't have proper colorization for JSX until we reactivate the syntactic classifier. I'm not entirely sure when that will be. @CyrusNajmabadi might know more about this.

**Comment by matijagrcic** [comment]
@DanielRosenwasser @CyrusNajmabadi Except for colorization and formatting could you provide support for emmet, something as VS code did in Microsoft/vscode#732?

**Comment by DanielRosenwasser** [comment]
I feel like that might be out of scope, since another project could always use our language service to implement the same functionality. Still, I'm not that familiar with emmet and others might disagree.

You're more than welcome to open up a separate issue, and if you do, if you could give a quick description on emmet itself with a link that would be much appreciated.

**Comment by olmobrutall** [comment]
Here are links:

Emmet syntax: http://docs.emmet.io/abbreviations/syntax/

YouTube video: https://m.youtube.com/watch?v=EfrqtMmmb0k

Challenges for react: https://gist.github.com/max-mykhailenko/41d0c3991d92f38dcbc6

Anyway, I think syntax coloring, proper formatting and basic tag auto-closing should be priorized. 

While VS and TypeScript have a much deeper understanding of the type system, the experience is almost ruined because of the final polish.

Pleeese fix this.

**Comment by billti** [comment]
@RyanCavanaugh @vladima Is simple colorization of the JSX element and attribute identifiers, and punctuation, not something we can do easily within the enabled classifiers?

**Comment by mhegazy** [comment]
We will need to re-enable the syntactic classifier. There should not be a perf hit now after the work @CyrusNajmabadi did in VS2015 update1.

**Comment by CyrusNajmabadi** [comment]
Also, I put in some very useful helpers in the Roslyn codebase for this work.  Check out ITextViewExtensions.GetVisibleLinesSpan as well as:
http://index/Microsoft.CodeAnalysis.EditorFeatures/R/cd078e79a62bd496.html

**Comment by vladima** [comment]
fixed in #6406 and #6411

**Comment by olmobrutall** [comment]
Awesome!

**Comment by matijagrcic** [comment]
@vladima Awesome work! Do we need to wait for a particular VS update or can we just use latest TypeScript? :shipit:

**Comment by vladima** [comment]
managed side of changes should be available in TypeScript 1.8 which is our next release (I don't have any exact timings at this point)

**Comment by olmobrutall** [comment]
@vladima That's awesone! You have some pretty screenshot already?

**Comment by vladima** [comment]
something like this (colors for tags, attributes and inner text can be redefined)
![jsx](https://cloud.githubusercontent.com/assets/8052307/12271404/b875c502-b90f-11e5-93d8-c6740be354d1.png)

**Comment by olmobrutall** [comment]
:+1: Oeeee!!

**Comment by techird** [comment]
@vladima Is that possible to get this working in my visual studio now? Can't wait for typescript 1.8.

**Comment by vladima** [comment]
Unfortunately no, this requires changes on the managed side that were not yet released

**Comment by matijagrcic** [comment]
This is working great with [TypeScript 1.8](http://blogs.msdn.com/b/typescript/archive/2016/01/28/announcing-typescript-1-8-beta.aspx).

![2016-01-28 22_12_53-typescriptreact - microsoft visual studio](https://cloud.githubusercontent.com/assets/3612395/12660614/784de860-c60c-11e5-8f5a-5610cb416e8b.png)

[TypeScript_Dev14Full.exe download](http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS1.8.1-Beta-TS-master.20160126.1/TypeScript_Dev14Full.exe)

Thanks for all the hard work!

**Comment by olmobrutall** [comment]
Awesome team and awesome language. Thanks a lot!

**Comment by techird** [comment]
Really productive!!

**Comment by djanosik** [comment]
Is it intentional that colors used for tags, attributes and inner text are different from colors used in `.cshtml` or `.jsx` files? What colors I need to redefine to make it look the same?

**Comment by djanosik** [comment]
Well, it looks it uses colors for `VB XML Literals` instead of colors for `XML` or `HTML`. That feels wrong.

**Comment by olmobrutall** [comment]
I think it makes sense. This is markup inside code like in VB, no code inside markup like in cshtml. 

I think .jsx are wrong and .tsx right.

**Comment by djanosik** [comment]
It makes sense, but it should be consistent at least.

**Comment by olmobrutall** [comment]
I've found colorization errors about this feature using Inner Types. I posted a separated issue https://github.com/Microsoft/TypeScript/issues/6756

**Comment by paulvanbrenk** [comment]
@djanosik this inconsistency is because the `jsx` support was originally implemented by the ASP.NET team and the `tsx` support by the TypeScript team. We have a plan to unify this, however no clear timeline yet; the next version of Visual Studio is more likely than an interim release of TypeScript.

**Comment by djanosik** [comment]
@paulvanbrenk Good to know. I've changed `VB XML Literals` colors because it's not readable when you use Dark color theme.

**Comment by CyrusNajmabadi** [comment]
pinging @dpoeschl .  Hey David, is is a known issue that the VB xml literal colors aren't readonable in the Dark theme?  Sounds like something we'd want to fix for both VB and TypeScript.

**Comment by nippur72** [comment]
what are the VB XML color code-names for `<`, `>`, `/`, `=` ?

I would like to colorize the whole component definition, delimiters included.

Also, it would be nice if code within JSX expressions  (`{ }`) had a custom background (slightly lighter or darker) like in the razor syntax.

**Comment by paulvanbrenk** [comment]
@nippur72  I don't think VB XML literals has configurable options for the delimiters, at least I couldn't find them.

I'll see if I can use the `VB XML Literals - Embedded Expression` color for the JSX expressions, but that may look terrible.
