### ISSUE TITLE
Have JSX transformer respect return type of createElement

### ISSUE THREAD

**Issue by nilpatelmicrosoft** [microsoft/TypeScript#48365]
# Suggestion

Currently, JSX usage ignores the return type of the createElement call and always forces the return type of JSX to be JSX.Element. I think it would allow more flexibility if the return type of the JSX was identical to the createElement call, and would solve many of the other issues folks have around flexibility here.

[typescript playground snippet](https://www.typescriptlang.org/play?module=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQduEAdqvAEIA2yAFnALxwAFGGJhUALjgBvAEbceU5gFcQsrFAC+ASgEA+GXTjG4lGMqjM4AHj3WA9HvqaGTVvAAeAzFRgA6XEpkGCwAUU4sECxmGCEuXgAaGXleKQBmHRo4e3s4AHkCOBgATzAsHzx-ADFlZnxgFgBhEkhmaJhwyPbrOQUlVXUtPUYWNjhi72t4vhSefmkM7IMc-MKSsrgAKQBlAA0-TqiYoA)

This could be an opt in feature via tsconfig to prevent in being a breaking change.

## 🔍 Search Terms

createElement, JSX, JSX children, generic in createElement

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [?] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Return type of JSX to match the createElement return type of the same pattern, and enforce the other constraints from the transform to allow for prop and children constraints using generics.

## 📃 Motivating Example

See below, but this would greatly improve usability of React typings and contraining.

## 💻 Use Cases

We would like to build an API that allows the parent to provide context to its children, such that this could be built in a type safe way. It can be built in a type-unsafe way today:

```jsx
<Form>
    <Step id="someId" />
        <Input onChange={(state) => { state.someId; }} /> { /* This state access is not inferrable today, which can lead to unmaintainable code  */}
    </Step>
</Form>
```

**Comment by RyanCavanaugh** [comment]
Duplicate #14729
