### ISSUE TITLE
Invalid possible function parameters

### ISSUE THREAD

**Issue by YuichiOnodera** [microsoft/TypeScript#48372]
# Bug Report

### 🔎 Search Terms

function parameters tuple join

### 🕗 Version & Regression Information

all versions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgZRk1TgG8AoASAHcEATGACwH4AuOJAVwFsAjNANxVsEFMBRs4AZxhRkAcyEBfcuVCRYcGAE8weAAqYomblIA8AFTihUSOlIJESAXkfFgAPjiuKlANoA0ohIcADWwNoQ6HAWALoAtJJ+4drsAQA0cABumAA2nMDsFoGxscrJEVExZaoiSDLSToVuLmRKQuTonEjYMAii0sAwhO4AjAAUAHTTYEYmUuyGxqYAlOxZEPRk5HC7je5+s8tSfgAMpd5wR-N+ozUqnd29-SFSQyOoAExTM3Omi38pGtsps6Ns9tJaDBsIxxtdTGdYitwRC9thMG84AByWgMRhY1g7VHEmQHeEnc6xS7k241YnE3hQYCYUJCelwdGYrF1WwwAlE9m7UmoQ6AxFU1w0u5swW7RnM1kCuAqFS7IA)

### 💻 Code

```ts
export interface State {
	width?: number;
	content?: string;
}

export type Params<T extends State = State> = {
	[K in keyof T]-?: [key: K, value: T[K]];
}[keyof T];

const state: State = {};

function setState1(...params: Params): void {
    state[params[0]] = params[1]; // an error here
}

function setState2(...params: Params): void {
    switch(params[0]) {
        case 'width':
            state[params[0]] = params[1];
            break;
        case 'content':
            state[params[0]] = params[1];
            break;
    }
}
```

### 🙁 Actual behavior

In this example, the alias type Params is: `['width', number] | ['content', string]` This means that the possible value is strongly limited by its key. And it is impossible that  inside the function `params` could be `['width' | 'content', number | string]`.

### 🙂 Expected behavior

The expected result should be the correct operation of the function setState1 as in the setState2 function but without switch/case operator.

**Comment by RyanCavanaugh** [comment]
TS doesn't validate operations by combinatorially exploding out the possibility space, as `setState2` does -- this isn't practical to do beyond trivial examples. If you rearrange this example a bit and leverage the behavior added in #47109 this might be able to be made to work, though

**Comment by fatcerberus** [comment]
To expand on the above: Since the type checker only sees the types, there’s no difference (from the compiler’s POV) between:

```ts
state[params[0]] = params[1];
/* VS */
state[params1[0]] = params2[1];
```

There’s no higher order logic that says the two sides of the assignment are correlated.
