### ISSUE TITLE
type of interface in Union not able to get key?

### ISSUE THREAD

**Issue by rajhim** [microsoft/TypeScript#48370]
Version: 4.6.2

Note: The TypeScript Playground can be used to try older versions of TypeScript.
[play ground link ](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAChBOBnA9gOwCLADZQLywRVQEYoAfApNAJnMqIGYBuAKBYEtVgEAzAQwDG0OFRJQA3iyhRUfALYQAXFETB4nAOatpfDUpkBXOQCMErAL6sOXXoOGEaEqVAFY+iZavWotLS205ueH4hejQGJ2l4ZCwsTzVNCyseA1QBYHY0KD1gADU+LAMIAAp2bjllESJMLABKSWlpLAhgKAA3AqK8KDKIOQB+ADpXd21GgTQUZsGsZA1igCkAZQB5ADlBr012HhBijsKIWtqLNhz8w+LxWQVlACJ4PgArAAt2OTuAGiho2PvgF7wCAQO7mWpsKBAA)

### 💻 Code
```
type PersonDtl = Person1 | Person2 | Person3;

interface Person1 {
  name: string;
  age: number;
};

interface Person2 {
  clas: string;
};

interface Person3 {
  roll: string;
};

function getValue(item: PersonDtl){
    let value = item.clas;
    console.log(JSON.stringify(value));
}
```
### 🙁 Actual behavior

item.clas -> not able to get value

### 🙂 Expected behavior

item.clas -> take key from interface type (PersonDtl)

**Comment by MartinJohns** [comment]
This is working as intended. Your value may be a `Person1` or a `Person3`, in which case there is `clas` property.

**Comment by rajhim** [comment]
Is there any way to get key `clas`   from `type PersonDtl`? with Union concepts? 
and What is the best way to declare it?

**Comment by MartinJohns** [comment]
Not in a type-safe way. But it sounds like you want an intersection type instead of a union type.

Also, these kind of questions are better suited for platforms like StackOverflow. The issue tracker is for bug reports and feature requests.

**Comment by rajhim** [comment]
thankyou for the information.!
