### ISSUE TITLE
Discriminated union doesn't work when  using strings and `Exclude` or `string extends 'xyz' ? 'xyz' : never`

### ISSUE THREAD

**Issue by alber70g** [microsoft/TypeScript#48373]
# Bug Report

### 🔎 Search Terms

Discriminated union for nested property in type

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because **it never worked before and still doesn't work**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIglgZ2HAdgY2AFXNAvLRZdYAYQHsAbMgJ20igB8ClUMA5Mlcq2nAKD6h68FsW406eKAG8+UKAGsIIAFxQk1VAHMoEAB7AIKACYIoAcjSUa5qAH4LVnrbUoIANwjUoAeh9QAQwpDahQA5E8KECgAA0tranMYuSgyMGROBDVxagB5dLhMvgBfASFoESJ2ThzJKHxZeSVVdWBNFB19QxMzeOd7KDdPbzUNbV9-IJCwiIgo2IBRPTQKAFdjCAAeMY6AGkcE8wA+ZPk0jJQsqHyLhBKynGuCzPqZFIoAgCM50bbtAG57oJHjkboVLq8wS8AGRveQAC30v3aWkBpT4fnquGxONxeJxGP8qwQAS00DIADMoOUzN8qAB3QlY-Es3ECKyXYCDGoJJYBAC2YAoEDUlVYWEeDRSzTU5gQcAAXhBzPsUudwVdGvIoIi9LKKQbDSqJlBNmaoAsAEqW3KWlLyD502VzBDKlKldEcpBQJw0PmC4WiwjiupSprKWW+xKqs7PS5qLUIpEWQ1G-aYs2bKAASSp2ag1Ag-LInmp8MQ+2AiMLUEQ3N01GoNHtUEdPwsLrd8g9fCAA)

### 💻 Code

```ts

type DistinctType = DistinctColorType | DistinctNonColorType

type DistinctColorType = {
  key: string extends 'color' ? 'color' : never // alternatively `'color'`
  options: ColorOptions
}

type DistinctNonColorType = {
  key: string extends 'color' ? never : string // alternatively `Exclude<string, 'color'>`
  options: Options
}

type Options = {
  label: string;
}

type ColorOptions = Options & {
  hex: string;
}
// ===================
// usage of types below
// ===================

const nonColorExample: DistinctType = {
  key: 'size', 
  options: {
    hex: 'ffffff', // <<< ERROR
    label: 'else'
  }
}

const colorExample: DistinctType = {
  key: 'color', 
  options: {
    hex: 'ffffff', // <<< If I remove this, there is no error
    label: 'else'
  }
}

```

### 🙁 Actual behavior

when `colorExample.options.hex` is removed, the typechecker doesn't recognize that it's missing

### 🙂 Expected behavior

When `colorExample.options.hex` is removed, the typechecker should recognize that the property is required, because the `key === 'color'`

**Comment by RyanCavanaugh** [comment]
See also #29317
