### ISSUE TITLE
ts1.6 ,  interface errors in  VS2013

### ISSUE THREAD

**Issue by lusess123** [Microsoft/TypeScript#4837]
interface  IA
{
    A?: string;
    B?: number;
    C?: any;
}

var f: IA  = {
    C: "",
    D: 2
  
   };

errors:
  	Type '{ C: string; D: number; }' is not assignable to type 'IA'.
  Object literal may only specify known properties, and 'D' does not exist in type 'IA'.	D:\AtawSources\Ataw.Platform\TypeScriptHTMLApp1\app.ts	38	5	TypeScriptHTMLApp1

The Errors are shown in  1.6 ,but no in 1.5 ,why ??

**Comment by ahejlsberg** [comment]
This is an effect of the stricter object literal checking in 1.6. [Read more about it here](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#strict-object-literal-assignment-checking).
