### ISSUE TITLE
function created with .bind() has wrong return type

### ISSUE THREAD

**Issue by ArdorDeosis** [microsoft/TypeScript#48385]
# Bug Report

When a function `newFunc` is created with `func.bind(/*...*/)`, it has erroneously the same return type as the original function `func`. This is wrong because the return type is dependent on the bound `this` context. I noticed the problem with literal types, but made reproduction code with a simple `number`/`string`example (see below).

### 🔎 Search Terms

`rebound function wrong type`, `bind function wrong type`, `bind type inference`

### 🕗 Version & Regression Information

Tested in TypeScript Play: Found the same behaviour beginning with v3.3.3333 up to the current nightly v4.7.0-dev.20220302.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/MYewdgzgLgBKZQIYEswFMBOMC8MDeAUDDBCALZoDC40iCAaogDYCuaAXDAAwAeAQgFEBAMQA0RGADMWYYAEYAFAEp8E4hjRQWGMDCgALZBAB0pCtUhIGzNgG4JAX3HFpsgEydXwKMnBSQIMqqxOqa2roGRqbkVDRWUIysaPbEDgQO9gTw0DDoAO4WSKiYOPgkMRa01kmcAEQARmhokrUwGQRZcTAa9SAyACbCMvKl8EXoGMZecsb1qP0K+YUoE0r22bA9fWCDw26j4OOYU3uz84toBYcrmGsd2SBMaMZMIADmCgDk05+iegCeAAc0CBJHBrsVJtNlHcHk8Xu8vl43L8AcDQeCEDcoXsYesaI9nq8Pp8tgMhrI5KioECQWCyTsKfI8Z1IISESSGbt3NTaRiuUy3CygA)

### 💻 Code

```ts
const container = {
  someConstantValue: 0xBEEF,
  func1() {
    return this.someConstantValue;
  },
  func2: function foo() {
    return this.someConstantValue;
  }
};

const newContainer = { someConstantValue: 'beef' };

const reboundFunc1 = container.func1.bind(newContainer);
const reboundFunc2 = container.func2.bind(newContainer);

console.log('func1', typeof container.func1());
console.log('func2', typeof container.func2());
console.log('reboundFunc1', typeof reboundFunc1());
console.log('reboundFunc2', typeof reboundFunc2());
```

### 🙁 Actual behavior

When hovering over `reboundFunc1` or `reboundFunc2`, the hint shown is `const reboundFunc1: () => number`, which is wrong, since both functions will return the string `'beef'`.

### 🙂 Expected behavior

I assume that the actually expected value (in this case  `const reboundFunc1: () => string`) cannot be inferred, since the value could come from a dynamic compile-time construct, but I think it should then rather show `const reboundFunc1: () => any`, than giving a wrong hint.

**Comment by fatcerberus** [comment]
This would require all methods to be generic.  When you declared `func1`, the compiler infers it as returning `number` because that's what the type of `this.someConstantValue` is at that point.  The compiler doesn't look at the implementation after that, so there's not enough information to know it should infer a new return type from the `.bind()` call (e.g. what if the implementation was instead `return 42`?).

**Comment by ArdorDeosis** [comment]
@fatcerberus not all methods, only methods created with `.bind()`, right? I mean, I understand that it is probably more helpful the way it is, that a method created with `.bind()` gets the signature of its unbound equivalent, that's also what I would expect, I guess. I was just wondering if there could be taken special care if `.bind()` is involved, somehow checking if the signature still holds up. Since the type was inferred for `func1` when was created, I thought it, could infer the type anew for the newly created function `reboundFunc1`.
