### ISSUE TITLE
Declaring type for "this" in functions does not work with private fields on class

### ISSUE THREAD

**Issue by danmana** [microsoft/TypeScript#48384]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Specifying the type of this for functions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#specifying-the-type-of-this-for-functions)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQHIEMC2qBiYAFFABYwDOAXIgKoWoBOAlDRVIzGMogN4BQiIYgD0IxAHdSAT0QATOKgpgA5FERlKkuIwDWiClwipJJrIxPAdELjwBEminY1xEAIxP0mAfkHCxiAAKjHAADkxQsirAMIzsAPpguKgqiFqhnABuWFBmYHKICAA2slgQxhSGbkUmEjCaSBBFWJWIKl6MKgB0RABMAMwALACMzH5CFlAgjEiOXTFxUInJiADUbRvrc80JSXgA3PwAvvz8TS0UdAyMfOOIEAjsjCDQOkQZMNm5iAu7yWwcWwAGkQHy+Jh2Sz2qABnG4zD4JzuaEwKwAvCh0Ng8IRDkjzq0Or1bsJ7o8OC8oG8wTlLLE-nhYcDQVlaYhIctGQZAfDEadSSjsagiKxuXCeAJSaTJtNZuQKPN6VCVutUqktvKuhzoYdSSckQE3HAyNo9IgcohnmBYHgzo84DUtXBkER2tcaOrEGBUBIrkxXQBBFRAlQAIRUzC6guSIuYhweYAoDtQTpdbqYvQ9ay9Pr9jF6geDYYjUaxMeYcf4QA)

### 💻 Code

```ts
function getNameFn(this: User): string {
    // why doesn't this work since we are forcing "this" to be User?
    // Property 'first_name' is private and only accessible within class 'User'.(2341)
    return this.first_name + ' ' + this.last_name;
}

class User {
    constructor(private first_name: string, private last_name: string) {}

    getName = getNameFn;
}

// works at runtime
console.log('User: ' + new User('A','B').getName());
```

### 🙁 Actual behavior

Accessing private fields on `this` shows a compile error
```Property 'first_name' is private and only accessible within class 'User'.(2341)```

### 🙂 Expected behavior

Since we are specifying that `this: User` I would expect that I can access all fields of this.

Is there some other way to specify that `this: User` refers to also the `private User`?
It would help with extracting methods in separate files.

**Comment by MartinJohns** [comment]
https://www.typescriptlang.org/docs/handbook/2/classes.html#private

> `protected` members are only visible to subclasses of the class they’re declared in.  
> `private` is like `protected`, but doesn’t allow access to the member even from subclasses:

You're trying to access a `private` field from outside the class. This is not allowed.

**Comment by danmana** [comment]
This also has the same effect ([playground link](https://www.typescriptlang.org/play?target=1#code/GYVwdgxgLglg9mABAcwKZQHIEMC2qBiYAFFABYwDOAXIgKoWoBOAlDRVIzGMogN4BQiIYgD0IxAHdSAT0QATOKgpgA5FERlKkuIwDWiClwipJJrIxPAdELjwBEmihriIARifpMA-IOFjEAAqMcAAOTFCyKsAwjOwA+mC4qCqIWiGcAG5YUGZgcogIADayWBDGFIauhSYSMJpIEIVYFYgqnowqAHREAEwAzAAsAIzMvkIWUCCMSI6d0bFQCUmIANSt62uzTfGJeADc-AC+-PyNzU7tfGOIEAjsjCDQOkTpMFk5iPM7SWwctgA0iFe7xM20Wu1Qv043GYfGOxy4OUYwFKHgYjCuwhQ6GweCIrAMf24B2O7U66TgUEp0jCnTQmGWAF5sQy8IQDid-BIdLonNlEA8wLA8Kc7nBqp1CnBkEQ2uiaCk1mBUBI6OjZQBBFT-FQAIRUzDpOKS+OYHKAA)):
```ts
function getNameFn(this: User): string {
    // why doesn't this work since we are forcing "this to be User?
    // Property 'first_name' is private and only accessible within class 'User'.(2341)
    return this.first_name + ' ' + this.last_name;
}

class User {
    constructor(private first_name: string, private last_name: string) {}
}
interface User {
    getName(): string;
}
User.prototype.getName = getNameFn;
```

**Comment by whzx5byb** [comment]
> Is there some other way to specify that this: User refers to also the private User?

You could use brackets notation to access protected/private members from outside.
```ts
function getNameFn(this: User): string {
    return this['first_name'] + ' ' + this['last_name']
}
```

**Comment by danmana** [comment]
Yes, that seems to work, and even preserve intellisense types.
Thanks :)

Feels just a bit clumsy, since I imagined `(this: User)` would mean that the function body is executed on a `User` class (not a subclass)

See [playground](https://www.typescriptlang.org/play?target=1#code/GYVwdgxgLglg9mABAcwKZQHIEMC2qBiYAFFABYwDOAXIgKoWoBOAlDRVIzGMogN4BQiIYgD0IxAHdSAT0QATOKgpgA5FERlKkuIwDWiClwipJJrIxPAdELj00UNcRACMT9JgH5BwsYgAKjHAADkxQsirAMIzsAPpguKgqiFpBnABuWFBmYHKICAA2slgQxhSGzvkmEjCaSBD5WGWIKu6MKgB0RABMAMwALACMzN5CFlAgjEj27ZHRUHEJiADUzasr0w2x8XgA3PwAvvz8oJCwCCjo2HiEXSTk1HQMLGwctnwjouL2BqioOA5QJwSHS6AA0iCwOUQqDSqCQqSUTFhANIJjCIUQVkYyTAWXy+UocIYHzGEym9wA2hEolsEioALrLVZJdaUlSbebbRL0vaHfj1RoOVrvYSICAIdiMEDQHREVIwDJZTE0zkJF6cbjg+WKkwchZ4dW2Zh8PmitCYRYAXguFuuYD2ZsuCS6iGt5quBDAXV5R18zjgZG0egh6iluJgeH5ErglXa+TgyCILSeNBZiDAqAkjyYSYAgipQSoAEIqZjtd0JIjMZh7cVgCgx1BxhNJ1pdVNMjNZ1p5gvF0vlp14W7VvZAA)

**Comment by danmana** [comment]
Yes, you are right. I seem to have misunderstood how `this: User` works.

The ts behavior seems to be consistent with the new `hash mark` private fields in ECMAScript:

```js
// running in Chrome
class User {
    #first_name;
    #last_name;
    constuctor(first_name, last_name) {
        this.#first_name = first_name;
        this.#last_name = last_name;
    }
}
// Uncaught SyntaxError: Private field '#first_name' must be declared in an enclosing class
User.prototype.getName = function() { return this.#first_name + ' ' + this.#last_name; };
```

I will close this issue.
Thank you for the clarifications.
