### ISSUE TITLE
Property 'dataMenu' does not exist on type 'HTMLAttributes<HTMLDivElement>'.ts(2322)

### ISSUE THREAD

**Issue by RahelSiddiqi** [microsoft/TypeScript#48382]
In Vue3, I am having some property that does not exist in the HtmlElement error. please help me solve this issue.

Error :

```
(property) dataMenu: string

(property) data-menu: string
```

```
Type '{ class: string; dataMenu: string; "data-menu": string; }' is not assignable to type 'HTMLAttributes'.
```

**Comment by DanielRosenwasser** [comment]
Hey there, this issue tracker isn't meant to work as a support forum. These questions tend to be better suited for StackOverflow. You may want to open a question up there instead. Thanks!
