### ISSUE TITLE
Doc comments when hovering sometimes break for optional properties

### ISSUE THREAD

**Issue by johan** [microsoft/TypeScript#48395]
# Bug Report

### 🔎 Search Terms

`refdocs` `tooltip` `help` `docs` `reference`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `/**`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEj4NwCXYLlALA9gNwKYCdQBMEGMDOoA7gmgNagAUiqGALnCqAA5oJPq0CeoAlgHagACgBsAhpwDmrAK59MeWD1oE0KAGbZ8RHsOGg8iQgEoAUCFCBeDcCke7GrosuAtj4ByWkRLkqye0oA0oKJyoJwI0i66oAh8wtx4KIz0iZzsAXwIoKoajqZmYABGong8OKA4RSgE9KLuxGSw6aAARIVoTcysTIHuoroBJIGgALZBmDUk3C2iGCxsTdAmONF47hIICJigALygAOqeeBQA3iHisE1Q7QC+RgDci8s9wngZOwAiSrQIx6ec55cBVqwWhoaSMG73JZ8FZRUjibagD60L4-ThnZoA0BA0BqXrxAJqdb-SDXO4mPK8NRERgjUiMKZtKJMWg8aK9AK9PR2OjrYQsrpZTQEfKqUSkAL0MISOALKEw9K0ACMCIAQqw6aj0U1rE0CUTmjrQBCHtD3AqAEyq9UoTV-A1WXVY6bA0Hgu6gcxCqIxbh1ciEjAMpom+UIWgAZitCA1JzRdu1DsBzpxeJQeoQ50NEI9YAomE+GQYqlyalkOBZ0T2BwocdgAE1xEZYEgEDxNkcriZS3xy6yBEiUbMmApKA3uAAyUAq6YAMVTRlAAB9R-DJ9O0AAVV1GJugFtt0AdrtlisCNXRm1DkcUMegNez+dLlcTqfTLdghfLm+r0AAOQQ647s2rbtp2Jj8LQ6C4jgjC3kcJigIhHoAFTIQ4WgBr8oDIcACFIXGAD8sArGg-ASPcYEQVBogwX+AHTIeeGIcAqHNK07QIEMnwoJgsCEhkXoUKoACO0g8KomxDguOFMTi+okWRFHklRaDQYw65zs8jDwUhKFoUGKZabArToQQMm6diuJafcuksfp7GGfEfHrKZlAiWJEkdGw0m4bp-HESCikmJRfCQapNHqW+rqMbZrEGSCYLGQxXrmUh2IJSgNlIXZbHTO0GXOQJjiUGwp69F5TA+bJ-FEfogV8ORwUmEAA)

### 💻 Code

```ts
// 🤠: hover docs work (hover the property in Playgrounds: its refdocs will show)
// 😥: hover docs don't work (hover it, and you'll only see the type, no refdocs)

// basic cases that work: no "bar" prop at all, or a mandatory "bar prop":
const good = Works({ yay: "🤠" });
const also = Ditto({ yay: "🤠", bar: true });
const okay = Ditto({ yay: "🤠", bar: false, foo: "🤠" });

// if we make "bar" optional, all hover tooltip refdocs break, though:
const not1 = Broke({ yay: "😥", foo: "😥" });
const not2 = Broke({ yay: "😥", bar: true }); // docs only work for "bar"
const not3 = Broke({ yay: "😥", bar: false, foo: "😥" }); // (ditto here)

function Works(yay: Yay): void {}
function Ditto(props: (Yay & BarFalse) | (Yay & BarTrue)): void {}
function Broke(props: (Yay & BarFalse) | (Yay & BarTrue) | (Yay & NoBar)): void {}

interface Yay {
    /** docs for yay */
    yay?: string;
}

interface NoBar {
    /** "bar" omitted: foo docs (required prop) */
    foo: string;
}

interface BarFalse {
    /** "bar" false: bar docs */
    bar: false;
    /** "bar" false: foo docs (required prop) */
    foo: string;
}

interface BarTrue {
    /** "bar" true: bar docs */
    bar: true;
    /** "bar" true: foo docs (optional prop) */
    foo?: string;
}
```

### 🙁 Actual behavior

In the playgrounds (or in vscode), hover any of the property names whose values are `😥` (`not1`'s or `not3`'s `yay` or `foo` keys, or `not2`'s `yay`). You are shown only a `(property) yay: string` tooltip.

### 🙂 Expected behavior

The tooltip should show the associated `/** refdoc */` from its definition, i e something like the top example's `(property) Yay.yay?: string | undefined` followed by a horizontal rule, followed by `docs for yay`. This latter part is missing.

**Comment by RyanCavanaugh** [comment]
We used to mash together the documentation when a property had more than one originating declaration, but people complained because this can and does result in some *extremely* confusing text, so this no longer happens.

**Comment by johan** [comment]
Does it have to be an all or nothing thing? Writing reference documentation that disappears because a type grew non-trivial structure to it is confusing, too, not least when it affects properties that used to appear just fine.

Could the one most specific applicable signature win and be shown? Or even just _any one_ arbitrary originating declaration be shown, plus perhaps an optional indicator that there are N other redundant doc strings that aren't being shown?

Complex types and api:s need documentation.

**Comment by RyanCavanaugh** [comment]
If someone wants to try again I'm willing to have a PR, but it'd need to be accompanied by some kind of research effort. We tried a bunch of ideas and nothing seemed like it would fix the problem of confusing hovers.
