### ISSUE TITLE
官网文档语句不通

### ISSUE THREAD

**Issue by zangguojun** [microsoft/TypeScript#48397]
文档-手册指南-接口-额外的属性检查中的一句话
`还有最后一种跳过这些检查的方式，这可能会让你感到惊讶，它就是将这个对象赋值给一个另一个变量： 因为 squareOptions不会经过额外属性检查，所以编译器不会报错。`其中`它就是将这个对象赋值给一个另一个变量`中的第一个`一个`，是否有些多余。

**Comment by Josh-Cena** [comment]
The localized docs are here: https://github.com/microsoft/TypeScript-Website-Localizations Please also file your issue there.
