### ISSUE TITLE
Checking instanceof import, valid TypeScript produces runtime errors; valid runtime JS is invalid TS

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#48390]
# Bug Report

### 🔎 Search Terms
import CommonJS module 2359 instanceof 

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 'Common "Bugs" That Aren't Bugs' and 'Common Feature Requests'

### 💻 Code

The following code is in a project with a package.json file containing `"type": "module"` and tsconfig.json file setting compiler options including the following as required for compatibility under other issues:
```
"module": "ES2020",
"moduleResolution": "node",
"esModuleInterop": true,
"noImplicitAny": true, //explains the inclusion of 'any' type below
```

Sample 1: Does not transpile. Executes perfectly fine as JavaScript if the sole type annotation 'any' is removed.
````typescript
import HttpProvider from 'web3-providers-http';
function isHttpProvider(whatToTest: any) {
	console.log('HttpProvider is', typeof HttpProvider, HttpProvider); //function [Function: HttpProvider]
	//Transpile-time error on next line:
	//The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.ts(2359)
	return whatToTest instanceof HttpProvider;
}
const result = isHttpProvider( { contents: 'This object is not an HTTP provider; the result should be false.' } );
console.log('Result is ', result);
````
Sample 2: Transpiles, but produces a runtime SyntaxError on the import line:
````typescript
// Try 2: Transpiles, but produces a runtime SyntaxError on the import line:
import { HttpProvider } from 'web3-providers-http';
// SyntaxError on above line: Named export 'HttpProvider' not found.
// The requested module 'web3-providers-http' is a CommonJS module, which may not support all module.exports as named exports.
// CommonJS modules can always be imported via the default export, for example using:
// import pkg from 'web3-providers-http';
// const { HttpProvider } = pkg;
function isHttpProvider(whatToTest: any) {
	console.log('HttpProvider is', typeof HttpProvider, HttpProvider); //undefined undefined
	return whatToTest instanceof HttpProvider; //TypeError: Right-hand side of 'instanceof' is not an object
}
const result = isHttpProvider( { contents: 'This object is not an HTTP provider; the result should be false.' } );
console.log('Result is ', result);
````
Sample 3, following the instructions in the SyntaxError: Still transpiles, but leads to a runtime TypeError.
````typescript
import HttpProviderImport from 'web3-providers-http';
const { HttpProvider } = HttpProviderImport;
function isHttpProvider(whatToTest: any) {
	console.log('HttpProviderImport is', typeof HttpProviderImport, HttpProviderImport); //function [Function: HttpProvider]
	console.log('HttpProvider is', typeof HttpProvider, HttpProvider); //undefined undefined
	return whatToTest instanceof HttpProvider; //TypeError: Right-hand side of 'instanceof' is not an object
}
const result = isHttpProvider( { contents: 'This object is not an HTTP provider; the result should be false.' } );
console.log('Result is ', result);
````

Sample 4: A different import style, which neither transpiles nor runs as JavaScript.
````typescript
import * as HttpProvider from 'web3-providers-http';
function isHttpProvider(whatToTest: any) {
	console.log('HttpProvider is', typeof HttpProvider, HttpProvider); //object [Module: null prototype] { default: [Function: HttpProvider] }
	// Transpile-time error on next line:
	// The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.ts(2359)
	return whatToTest instanceof HttpProvider; //As JS, gives runtime TypeError: Right-hand side of 'instanceof' is not callable
}
const result = isHttpProvider( { contents: 'This object is not an HTTP provider; the result should be false.' } );
console.log('Result is ', result);
````
Sample 5: Based on observing that the import above had a single member named default.
This does not transpile, but executes perfectly fine as JavaScript if the sole type annotation 'any' is removed.
````typescript
import * as HttpProviderImport from 'web3-providers-http';
// Transpile-time error on next line:
// Property 'default' does not exist on type .ts(2339)
const HttpProvider = HttpProviderImport.default;
function isHttpProvider(whatToTest: any) {
	console.log('HttpProvider is', typeof HttpProvider, HttpProvider); //function [Function: HttpProvider]
	return whatToTest instanceof HttpProvider;
}
const result = isHttpProvider( { contents: 'This object is not an HTTP provider; the result should be false.' } );
console.log('Result is ', result);
````
### 🙂 Expected behavior

At least: Samples 1 and/or 5, which work perfectly fine in JavaScript, also work in TypeScript (assuming the explicit `any` typing is either removed from the JavaScript or not required by the TypeScript compiler options).
At best: Also, samples 2 and/or 3, which throw type-based errors from the emitted JavaScript, instead have those errors flagged by TypeScript. 
Alternatively: More helpful error messages for figuring out what code changes should make this work.

### 🙁 Actual behavior
Vice versa.  (See more detail in comments above.)

**Comment by RyanCavanaugh** [comment]
Reading the docs for web3-providers-http, it looks like it exports a top-level function. You may need to turn on `allowSyntheticDefaultExports` depending on your loader behavior. I'm not sure from this report what you're actually trying to do; issuing errors based on misconfiguration is an expected behavior of TypeScript; none of the described behavior here points to a defect.

**Comment by wbt** [comment]
I assume you mean `allowSyntheticDefaultImports` which is a config option while the `...Exports` version is not. However, the behavior is the same whether that is set to true or false.

The importance of having a minimal example makes it hard to show the value but what I'm trying to do is an `instanceof` check, for example in a narrowing type guard. Since that's a runtime check, it requires actually importing the object, not just the type.  Thus, in sample 1, the error message (`TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.`) is correct in asserting that the right-hand side must be a function, but misses the fact that **it is**.  In Sample 5, TypeScript is missing that `default` does in fact exist on that type.  If either of these are part of a non-TS JavaScript file, they execute just fine. 

The main issue observed here is that TypeScript isn't recognizing the valid types on functional code, and it's not at all clear what the valid JavaScript code should be rewritten to.  Figuring out what it should be based on what satisfies TypeScript produces Sample 2 or 3 but these actually introduce runtime typing errors and I had though the main objective of TypeScript was to get rid of those, not add more in.  The secondary issue is that code which started out resembling Sample 2 or 3 should have the issue flagged by TypeScript.

**Comment by RyanCavanaugh** [comment]
Understood, but I don't see evidence of a bug here. It sounds like you've misconfigured your module settings relative to your runtime environment. Erroring / not erroring here based on the module settings is expected behavior. If you're seeing something *specific* to the `instanceof` operator (vs, say, `new`, or anything else) that would be likely to be a bug, but I don't see that here.
