### ISSUE TITLE
`Intl.DateTimeFormat` extend `TimeZoneName` option

### ISSUE THREAD

**Issue by nick-krantz** [microsoft/TypeScript#48391]
# lib Update Request

The `timeZoneName` property of the `option` object passed to `Intl.DateTimeFormat` can be extended to include "shortOffset", "longOffset", "shortGeneric", and "longGeneric". The proposal is in Stage 3 and has browser support across [major browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#browser_compatibility).

## Sample Code

The below currently throws an error as `timeZoneName` is only assignable to `short` or `long`
```ts
new Intl.DateTimeFormat('en-US', { 
  timeZone: 'America/New_York', 
  timeZoneName: 'shortOffset', // 'short' | 'long' | 'shortOffset' | 'longOffset' | 'shortGeneric' | 'longGeneric'
};
```

[TS Playground](https://www.typescriptlang.org/play?target=99&jsx=0#code/MYewdgziA2CmB00QHMAUZYHcAEBJMALtPACICGBsAKgJYC2sAYiAE50WoDksYAtAKoBlTgBpsAb2wF6sAFrhYALmycAggxY1gZAPQA5LAH0AmqwDWoqTPkY9ZBss4QAFqwIB5AGaeIsAp2wAXwBKeE9WdgJ0LGxySlRgxIBuAChQSBgEJDQMHHwiUgpqGWY2Dm4+IUtJaQYbJRV1WE1tHQBhZy0yZBBLWrkFOwcVJDBkLx8-AJCwiI5c2KKE5LTwKDhEFGi8wmI44oZSyK4eAWExGusFR1UAVwgCFjJoGl0AWVhoACMQW5YMPpXWz2BpOVwsAgAcR4zS001C4TKUQW+2WwVS6XWWS2C3yeyKtEOcyiFTO1SsdWujQgr3az2AtwIBDIgMpwOGnFGyGhGBa8NmSO2i3iiXRKSAA) with an example of each new option.

## Documentation Links

- [MDN Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#using_timezonename)
- [GitHub timeZoneName Proposal](https://github.com/tc39/proposal-intl-extend-timezonename)
- [emca402](https://tc39.es/ecma402/#sec-datetimeformat-abstracts)

**Comment by ritikBhandari** [comment]
Hi,
Can I try to resolve this issue?

**Comment by nick-krantz** [comment]
> Hi, Can I try to resolve this issue?

Absolutely!
