### ISSUE TITLE
Const primitive value type getting lost?

### ISSUE THREAD

**Issue by TeoTN** [microsoft/TypeScript#48402]
# Bug Report

It seems to me that type for primitive value assigned to a const variable gets widened in some contexts - I'm not 100% sure if this is a bug report or feature request, but this is a bit counterintuitive. Is this an expected behaviour?
(From what I saw in the playground hints, primitive values assigned to `const` behave as if they had `as const` modifier)

### 🔎 Search Terms
primitive value
primitive widening

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAKgTQAoFED6BGGBeGByRVTPAbgChRJZD0AmHfGtW0i8aeZdAZgYK7Tc8MAIYQYlaOUnUBAFj5M5wsRPZRybKqOBQAluCy4AFAEocAPhjGA3jCgBPAA4BTAFyciWAL6np6nX1wehNzbCtbe2d3TzoAGhgnEQcAGxARABMPG28YX39tEV0DMF5Qy2s7R1cPJl58rQ4ioLAFcvDKqJrYtDkEpNT0rJgcvL8yMmqXGAA5cABhdThogEFi9hwyGBgAHxgAJRcoAFcAJzBl1wAeKZAAM0CSjAst3YOjs4vom+j7x+CXpopjBFlRLi41i1xNhXntDidzuCfq4-s0StwXts4R9Ed9bg80eA5ICJndjmB1mAYGAFktohBDhljsAXKdjNARFAYjkEoSwB45mBQdBwZCShBzDZXhAAO56KDAAAW1j5ADoppLXttgGJpkxaG4tdsYKccVS1QM0plyMaYBkXHcRMcUlBDbbtqaEVScja8mRvKTyZSYHKoIrhVBwQyXEyWWyOVzst5eZSPBHRZSJSNpaGlSrKeroprbTqIHr5G73Z7Pv8wKrLUNfdt7Y7na6jR6zSNvL6A94gA)

### 💻 Code

The hint shows the `TYPE_1` is not string:
<img width="277" alt="Screenshot 2022-03-24 at 18 04 34" src="https://user-images.githubusercontent.com/5840198/159982242-296c9e10-e863-45b8-aa7d-053f4f4bc7b0.png">

```ts
const TYPE_1 = 'TYPE_1';
const TYPE_2 = 'TYPE_2';
const TYPE_3 = 'TYPE_3' as const;
const TYPE_4 = 'TYPE_4' as const;

const action1 = () => ({ type: TYPE_1 });
const action2 = () => ({ type: TYPE_2, payload: {} });
const action3 = () => ({ type: TYPE_3 });
const action4 = () => ({ type: TYPE_4, payload: {} });

type NonConstTypeActions =
  | ReturnType<typeof action1>
  | ReturnType<typeof action2>
;

type ConstTypeActions =
  | ReturnType<typeof action3>
  | ReturnType<typeof action4>
;

function nonConstTypesReducer(state: {}, action: NonConstTypeActions) {
  switch (action.type) {
    case TYPE_2:
      return action.payload; // Property 'payload' does not exist on type 'NonConstTypeActions'.
    default:
      return {};
  }
}

function withConstTypesReducer(state: {}, action: ConstTypeActions) {
  switch (action.type) {
    case TYPE_4:
      return action.payload;
    default:
      return {};
  }
}
```

### 🙁 Actual behavior

Type guard wasn't able to narrow down a type because field type got widened to `string`.

### 🙂 Expected behavior

Both examples should pass

**Comment by DuncanWalter** [comment]
Another way to express the issue (I think this is the same issue at least):

[Playground](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220302&ssl=9&ssc=24&pln=1&pc=1#code/MYewdgzgLgBAKgTQAoFED6BGGBeGByRVTPAbgChRJZD0AmHfGtWvGAQwhkunIvGnbAoAS3BZcAbxhQAngAcApgC54ydFgC+5brDZDRYepOnzlqovS1kyekWIB0sxQzzQATsLABzPGQD0fjAA6gAWMjAAJiAKnFAhwrEhbiAA7gD8MACSUK4wYCC6MG4KbFFgADbhcslyNvrgtI6mLu6ePkA)

```ts
const TYPE_1 = 'TYPE_1';
const TYPE_2 = 'TYPE_2' as const;

const action1 = { type: TYPE_1 };
const action2 = { type: TYPE_2 };

action1.type = 'string'
// Why does this throw? It's not a readonly prop
action2.type = 'string'
```

**Comment by whzx5byb** [comment]
`const TYPE_1 = 'TYPE_1'` have a widening type, while `const TYPE_2 = 'TYPE_2' as const` have a non-widening literal type.

See https://github.com/microsoft/TypeScript/pull/10676, https://github.com/Microsoft/TypeScript/pull/29510 for more details.

**Comment by TeoTN** [comment]
I'm not 100% sure this is the case, the playground hints that type of `const TYPE_1 = 'TYPE_1'` is `"TYPE_1"`. Moreover, this (somewhat stupid but proving the point) example would suggest that it's not widening:
```
const TYPE_1 = 'TYPE_1';
function fn() {
    switch (TYPE_1) {
        case TYPE_1:
        return 4;
        case 'any': // Type '"any"' is not comparable to type '"TYPE_1"'.(2678)
        return 5;
    }
}
```

**Comment by fatcerberus** [comment]
What you're ultimately observing is the difference between:
```ts
const action1 = { type: "foo" };  // { type: string }
const action2 = { type: "foo" as const };  // { type: "foo" }
```

It is a bit odd that the widening flag is apparently being preserved in the variable assignment, though.  The behavior should only apply to fresh literals.

**Comment by TeoTN** [comment]
@RyanCavanaugh that felt a bit rough :D It's not a question, and doesn't belong to stackoverflow.
I don't think it's good that primitive value assigned to const is (allegedly) of literal type value, and then information about the type is lost. I'm not sure if the problem lies in what types are reported (of the const variable) or if type is lost (**either is a bug**), and I'd probably expect that the type is actually literal for primitives assigned to `const` since they can't be (meaningfully) reassigned. (Feature request?)

**Comment by RyanCavanaugh** [comment]
@TeoTN the difference in behavior, which is intentional, was correctly described by @fatcerberus above. There is a difference between the widening and non-widening forms of literals, which isn't displayed in the UI (we discussed this and decided that it would be more confusing, rather than less, on net).

**Comment by fatcerberus** [comment]
@RyanCavanaugh I find it odd that the “widening literal” flag gets preserved through a `const` declaration.  That’s very confusing since it’s not reflected in any way in the type of the variable.  This seems analogous to if object literal freshness were preserved by a `const` declaration, which would be just as confusing.

**Comment by RyanCavanaugh** [comment]
The intuition is that this program should not have an error:
```ts
const a = "foo";
const b = { prop: a };
b.prop = "bar";
```

The widening rules for literals were largely derived empirically, since code like this predates the existence of literal types. One way to think about it is that it should be extremely difficult to get yourself into a literal type mismatch if none of your code contains either an `as const` or a literal type declaration *somewhere* in it.

If I'm misunderstanding your observation let me know; happy to clarify.

**Comment by fatcerberus** [comment]
I guess that makes sense.  I think I would rather have `const a` itself be widened to `string` (like what happens with `let`) rather than the potentially confusing deferred widening, but that would be a breaking change at this stage so I won’t suggest it.
