### ISSUE TITLE
Update from 4.6.0-Beta to 4.6.1-RC introduced bug with Electron 12

### ISSUE THREAD

**Issue by JirkaDellOro** [microsoft/TypeScript#48404]
# Bug Report

After updating and compiling the project, the Electron-App (Runniing on Electron v12.0.2) does not load the resulting javascript file but reports an error just a view lines into the code.
`Uncaught SyntaxError: Unexpected token '{'`

### 🔎 Search Terms

`Uncaught SyntaxError: Unexpected token '{'` Electron 4.6.1-RC

### 🕗 Version & Regression Information

After update from 4.5.0-Beta to 4.6.2, did some research to find it was introduced with 4.6.1-RC

- This is a crash
- This changed between versions 4.6.0-Beta and 4.6.1-RC

### 💻 Code

```ts
    class DebugConsole extends FudgeCore.DebugTarget {
        static { this.delegates = {                                                    // error thrown from this line
            [FudgeCore.DEBUG_FILTER.INFO]: console.info,
            [FudgeCore.DEBUG_FILTER.LOG]: console.log,
            [FudgeCore.DEBUG_FILTER.WARN]: console.warn,
            [FudgeCore.DEBUG_FILTER.ERROR]: console.error,
            [FudgeCore.DEBUG_FILTER.FUDGE]: DebugConsole.fudge,
            [FudgeCore.DEBUG_FILTER.CLEAR]: console.clear,
            [FudgeCore.DEBUG_FILTER.GROUP]: console.group,
            [FudgeCore.DEBUG_FILTER.GROUPCOLLAPSED]: console.groupCollapsed,
            [FudgeCore.DEBUG_FILTER.GROUPEND]: console.groupEnd,
            [FudgeCore.DEBUG_FILTER.SOURCE]: DebugConsole.source
        }; }
```

Previous output, which Electron12 was able to run, was
```ts
    class DebugConsole extends FudgeCore.DebugTarget {
          ....
    }
    DebugConsole.delegates = {
            [FudgeCore.DEBUG_FILTER.INFO]: console.info,
             ....
```

### 🙁 Actual behavior

Electron aborts loading the compiled Javascript file and throws the error 

### 🙂 Expected behavior

Load the compiled file and run it

**Comment by DanielRosenwasser** [comment]
Hmm, are you using `--target esnext`? If so, that isn't a stable output target across different versions of TypeScript, and will emit syntax that may be newer than what your engine expects. In this case, I would expect `--target es2020` would be good enough.

**Comment by JirkaDellOro** [comment]
Wow, didn't expect that quick of an answer. Correct, I used `esnext` to target whatever the newest is, but until I find the time to port the project to a newer Electron version, I just figured I can even use `es2021` with typescript@next. It's better this way round.

Thanks a lot!

**Comment by DanielRosenwasser** [comment]
No problem, glad the workaround was simple!
