### ISSUE TITLE
TypeScript Language Specification - string interpolation

### ISSUE THREAD

**Issue by falconepl** [Microsoft/TypeScript#4840]
TypeScript Language Specification does not mention string interpolation feature.

**Comment by mhegazy** [comment]
The typescript spec is based on the ES6 spec, so it is amused that any syntactic ES6 feature is a TypeScript feature unless stated other wise. as mentioned in the Grammar section:

> This appendix contains a summary of the grammar found in the main document. As described in section 2.1, the TypeScript grammar is a superset of the grammar defined in the ECMAScript Language Specification (specifically, the ECMA-262 Standard, 6th Edition) and this appendix lists only productions that are new or modified from the ECMAScript grammar.

this however seems like a good entry in the [handbook](https://github.com/Microsoft/TypeScript-Handbook). there is a reference to string templates in the [basic types](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Basic%20Types.md#string) section. Contributions to the handbook are always welcomed.

**Comment by falconepl** [comment]
Good point. Thanks for clarification.
