### ISSUE TITLE
Source provides no match for required element at position 0 in target despite source extending [any, ...any[]]

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#48401]
# Bug Report

### 🔎 Search Terms

tuple, conditional type

### 🕗 Version & Regression Information

4.6.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Conditional Types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4&q=315#code/C4TwDgpgBAShDGBXATgZwJYDcIBVwQB4cAZdVYKCAD2AgDsATVKAbQEM6QAaKAOn44gWAXWEA+KAF4oAChkBYAFBQVffgBsywAFxQSWpQEopExHQDWdAPYB3Oseq1GzGQAtd6OgDMIyKAAkINgYefl5gNnR1D29fPUj1Y0lTC2s7JVUoAH5ZN11A4KSUy1t7Shp6Jll3KABBZGQ2EAJPHz8YMSKoMxL05UzVHJgMgZVdORqCkLVwhN0cBK6etLLHSpcR0dGawS5NrcywiKjddk5QgU4RYSgAelvKOlQUaGBXNgoFqPKnKrPuGaCa77UZLVKlEGDWAIFAYbB4SBEBISe5QACiDSsyF0AGUrCh4NAwMgrJh0AwIMxrFAALYfeCuKBeLFQZAQACOiHQbIYlHUEBp9AoHygYCsGGA6CsdCgAAYoJ4oBFkABzCDASFjbrgvqZXTLUoAbiUJsUoEgUAAYiSafVGiApNCkGgsLh8ARyMhPCqRCiHr4SX42Mw2A0mlSrBRnmAxchaNNpeoHcBEGB+ahTeboNarDSccAvXQVXamo64M64W7ESxPd6RDw6IgaQAjOLiO4PNkp5BPKC1otKLNWm0AOSbreQJYd0nLsNdCMINYL3ob498Iig7dRqFc+PUvK7KBljZbviAA)

### 💻 Code

```ts
type RecursiveType<TList extends [any, ...any[]]> = ((
    ...list: TList
) => unknown) extends (h: infer Head, ...tail: infer Tail) => unknown
    ? ((h: Head) => unknown) extends (h: Array<infer R>) => unknown
        ? R
        : ((h: Head, ...tail: Tail) => unknown) extends (
              h: any,
              ...tail: [any, ...any[]] // ensure that Tail extends [any, ...any[]]
          ) => unknown
        ? RecursiveType<Tail> // Error: Source provides no match for required element at position 0 in target
        : unknown
    : unknown;
```

### 🙁 Actual behavior

Comile error:
Error: Source provides no match for required element at position 0 in target

### 🙂 Expected behavior

We should be able to pass `Tail` back into `RecursiveType` as we are ensuring that `Tail` extends `[any, ...any[]]`. I have tried this a few different ways, by re-inferring the type of the tail and by switching the `Tail` and `[any, ...any[]]` around so we check that `[any, ...any[]]` extends `Tail` instead.

**Comment by RyanCavanaugh** [comment]
We don't have a way to indirectly propagate the facts of the parent constraint into the `infer` result in a way that is still generic but allows it to directly pass constraint checks. #48112 should help with this use case

**Comment by Roaders** [comment]
Yes, that would have definitely helped in several places. I look forward to it being merged. Thanks

**Comment by 50an6xy06r6n** [comment]
Is this why `T[]` is not assignable to `[T, ...T[]] | []`?

That's a degenerate case, but I have some use for [things like this](https://www.typescriptlang.org/play?ts=5.1.6#code/MYewdgzgLgBAbjAvDA2gBgDQwIxYExYDMAugNwBQoksU2AXKmAK4C2ARgKYBOWAdP83bcUxYjAA+qMcjgUq0GFDwMUgzlwD8fAa3Ujp8CuSgBPAA4cYAcQA8AFSQwA3gF8AfI6eoA1hxMwASzAYXxMQADMYO2IGAEMwfxdKcAVI5HsMNwAKMwYuDliAE3AAG38UWzs3bV4rfQkpAEokD1dycKy4RooOlFwYAhgSbvasvvwiMViIGHkoEaA):
`const f = <T,>(p: readonly [G<T>, ...G[]] | []) => {}`
