### ISSUE TITLE
Document `@link` failed to resolve in type annotation.

### ISSUE THREAD

**Issue by AkatQuas** [microsoft/TypeScript#48406]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.2
- Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
- Date: 2022-03-10T14:33:49.188Z
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

```typescript
/**
 * given {@link a} have fun
 */
function b(a: number) {}

type B = {
  /**
   * given {@link a} have fun
   */
  c: (a: number) => void;
};
```

The inference works well in function annotation, like this:

![image](https://user-images.githubusercontent.com/24731539/159887366-8201d46d-d119-4f66-95d7-0022752c0a0f.png)

However, it fails in a type annotation, like the following:

![image](https://user-images.githubusercontent.com/24731539/159887487-4c260aa4-2b17-4f5a-a3e0-781c39136633.png)

Any hints to make this work?

**Comment by RyanCavanaugh** [comment]
Aside: Please put the text of screenshotted code in issues.

This isn't tractably fixable because there's not an unambiguous scope to resolve the name from. You could have equally written, for example, this:
```
c: ((a: number) => void) & { a: string };
```
now there are two `a`s with "equal footing" from which to resolve the name.

**Comment by AkatQuas** [comment]
@RyanCavanaugh  thank you for the tips and example.

However, it might as well to display the annotation when it's possible to resolve it, just for enchancement.

**Comment by a-tarasyuk** [comment]
To me, it looks like a _bug_. `getHostSignatureFromJSDoc` handles many edge cases to get _function like declaration_

https://github.com/microsoft/TypeScript/blob/6cb58d382fa31ac264a7e589cdcab1593b557f2e/src/compiler/utilities.ts#L2826-L2841

however, it doesn't handle `PropertySignature`, which can have `FunctionTypeNode`. `FunctionTypeNode` is a part of `SignatureDeclaration` which returned by `getHostSignatureFromJSDoc`. Does that make sense to have `FunctionTypeNode` as part of `SignatureDeclaration`?

https://github.com/microsoft/TypeScript/blob/d962091d94c8fa1a02a4a88c2b6e9809472a1509/src/compiler/types.ts#L1274-L1287
