### ISSUE TITLE
Configurable mock TypeChecker for unit testing

### ISSUE THREAD

**Issue by LarryWu1** [microsoft/TypeScript#48408]
# Suggestion

## 🔍 Search Terms

typescript compiler api create minimal type checker
typescript how to create a mock typechecker
typescript mocking typechecker

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

We would appreciate a configurable mock TypeChecker for unit testing.

```
import * as ts from 'typescript'

const mockSymbolToString = (symbol) => 'mockString'

// TypeChecker uses methods provided in configuration, or defaults if none provided
const mockTypeChecker: ts.TypeChecker = ts.createMockTypeChecker({
    symbolToString: mockSymboToString
})

mockTypeChecker.symbolToString(...) // calls "mockSymbolToString"
mockTypeChecker.typeToString(...) // calls the default
```

## 💻 Use Cases

Our codebase has a bunch of utility functions that process types/symbols using the type checker in custom ways:

```
// a custom utility function we wrote
const isTypeSupported: (typeNode: TypeNode, checker: TypeChecker): boolean => {
    const type = checker.getTypeFromTypeNode(typeNode)
    return type?.isClassOrInterface() || type?.isLiteral() || type?.isUnion()
}

test(('recognizes union type') => {
    const mockTypeChecker = ts.createMockTypeChecker({
        getTypeFromTypeNode: (...) => createUnionType(...) // assume valid "createUnionType" exists
    })
    const canWeSupport = isTypeSupported(constructUnionNode(...), mockTypeChecker) // assume valid "constructUnionNode" exists
    expect(canWeSupport).toBeTrue()
})
```

We currently have a huge custom `createMockTypeChecker`.

```
function createMockTypeChecker(config): TypeChecker => ({
    ... // we made defaults for everything in this interface https://github.com/microsoft/TypeScript/blob/main/src/compiler/types.ts#L4178
})
```

It looks like there's only one `createTypeChecker()` on line 308 https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/checker.ts. It requires a `TypeCheckerHost`, which is marked internal https://github.com/microsoft/TypeScript/blob/main/src/compiler/types.ts#L4166

**Comment by RyanCavanaugh** [comment]
We don't have the resources to create or maintain such a thing, even as a community effort. I'm not sure what this would do differently from a concrete type checker initialized with a mocked-out program.

**Comment by LarryWu1** [comment]
@RyanCavanaugh Thanks for the response! If mocking-out a program involves calling `ts.createProgram(...)` for each test suite, this will be too slow for lots of test suites. Is there an alternative?

**Comment by RyanCavanaugh** [comment]
In theory the thing you get back from `createProgram` is immutable enough (🙃?) that you can share it across instances. It really depends what you're doing.
