### ISSUE TITLE
TypeElement seems to be missing keys (specifically, "parameters")

### ISSUE THREAD

**Issue by kaiyoma** [microsoft/TypeScript#48409]
# Bug Report

### 🔎 Search Terms

TypeElement parameters

### 🕗 Version & Regression Information

TypeScript 4.6.2

### 💻 Code

If I console log a `TypeElement`, I get something like this:

```
NodeObject {
  pos: 27717,
  end: 27841,
  flags: 0,
  modifierFlagsCache: 0,
  transformFlags: 1,
  parent: undefined,
  kind: 167,
  decorators: undefined,
  modifiers: undefined,
  symbol: undefined,
  localSymbol: undefined,
  locals: undefined,
  nextContainer: undefined,
  name: IdentifierObject {
    pos: 27717,
    end: 27726,
    flags: 0,
    modifierFlagsCache: 0,
    transformFlags: 0,
    parent: undefined,
    kind: 79,
    originalKeywordKind: undefined,
    escapedText: 'getOne'
  },
  typeParameters: undefined,
  parameters: [
    NodeObject {
      pos: 27727,
      end: 27771,
      flags: 0,
      modifierFlagsCache: 0,
      transformFlags: 1,
      parent: undefined,
      kind: 163,
      decorators: undefined,
      modifiers: undefined,
      symbol: undefined,
      localSymbol: undefined,
      locals: undefined,
      nextContainer: undefined,
      name: [IdentifierObject],
      initializer: undefined,
      type: [NodeObject],
      dotDotDotToken: undefined,
      questionToken: undefined
    },
    NodeObject {
      pos: 27772,
      end: 27801,
      flags: 0,
      modifierFlagsCache: 0,
      transformFlags: 1,
      parent: undefined,
      kind: 163,
      decorators: undefined,
      modifiers: undefined,
      symbol: undefined,
      localSymbol: undefined,
      locals: undefined,
      nextContainer: undefined,
      name: [IdentifierObject],
      initializer: undefined,
      type: [NodeObject],
      dotDotDotToken: undefined,
      questionToken: [TokenObject]
    },
    pos: 27727,
    end: 27802,
    hasTrailingComma: true,
    transformFlags: 1
  ],
  type: NodeObject {
    pos: 27807,
    end: 27840,
    flags: 0,
    modifierFlagsCache: 0,
    transformFlags: 1,
    parent: undefined,
    kind: 177,
    typeName: IdentifierObject {
      pos: 27807,
      end: 27818,
      flags: 0,
      modifierFlagsCache: 0,
      transformFlags: 0,
      parent: undefined,
      kind: 79,
      originalKeywordKind: undefined,
      escapedText: 'Observable'
    },
    typeArguments: [
      [NodeObject],
      pos: 27819,
      end: 27839,
      hasTrailingComma: false,
      transformFlags: 1
    ]
  },
  questionToken: undefined
}
```

Clearly, there's a `parameters` key there, but if I try to access `element.parameters` in my code, I get this error:

```
Property 'parameters' does not exist on type 'TypeElement'.
```

### 🙁 Actual behavior

A type error.

### 🙂 Expected behavior

No type error.

**Comment by kaiyoma** [comment]
If I compare the output of what's actually in the object versus the latest types, all these properties are missing from the types:

```
localSymbol
locals
modifierFlagsCache
nextContainer
parameters
symbol
transformFlags
type
typeParameters
```

**Comment by kaiyoma** [comment]
I'm seeing similar issues with other internal types too. For instance, I have an object of type `Statement` and when I log it, I see a `name` property (among many others) that I can't access in code because I get this:

```
Property 'name' does not exist on type 'Statement'.
```

I see a lot of the same properties as I listed above in the actual data, but missing from the types. Is it a known issue that the types are really incomplete?

**Comment by MartinJohns** [comment]
I'm not sure what you expect here. Not every `TypeElement` has these properties. There are extending types that provide additional properties.

For example `ConstructSignatureDeclaration` extends `TypeElement` and `SignatureDeclarationBase`, and the type `SignatureDeclarationBase` provides the `parameters` property.

**Comment by kaiyoma** [comment]
@MartinJohns I'm getting this data from `createSourceFile`, which is provided by the `typescript` package. Are you saying that the data returned from this function isn't typed correctly, and I have to apply casts myself?

**Comment by MartinJohns** [comment]
I'm saying the types are correct and you have a fundamental mis- / lack of understanding of TypeScript. Did you see my example?

**Comment by kaiyoma** [comment]
Given your example, the analogy to my situation is that I'm given `a` by the `typescript` package (via `createSourceFile`), which has a type of `A`, but is secretly/really type `B` (the more specific type). How am I, as the consumer here, supposed to know that? From my point of view, the type doesn't match the data.

**Comment by MartinJohns** [comment]
Yes, in general the consumer is supposed to know how to use the library. In this you can identify what sub-type the data is by checking the `kind` property.

What else is the option? To add the `parameters` property to `TypeElement`? That would be completely wrong, because again: Not every `TypeElement` has this property. You have access to all properties that all `TypeElement` are guaranteed to have. For anything more you must check what potential subtype you're dealing with and either use a type assertion or an assertion function (if the library is providing one).

**Comment by kaiyoma** [comment]
> In this case you can identify what sub-type the data is by checking the `kind` property.

Ah, this is very helpful, and helps explain why the more generic types are being returned. (I was hoping that something like this existed in the API.)

**Comment by kaiyoma** [comment]
I've been able to use a combination of `kind` and type coercion to assign more specific types to the data being returned. Thanks for your guidance on that.

I have one lingering issue though: when I console log `Statement` objects, I usually see a `jsDoc` property, but I don't see this documented anywhere in the entire types file. I see the right interface for the value (`JSDoc`) in the types file, but I don't see the property. Am I missing something?

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/blob/main/src/compiler/types.ts#L882-L885

It's marked as internal, meaning the it's stripped from the generated .d.ts file.

**Comment by kaiyoma** [comment]
Ah, that's why I couldn't find it. 😄 Cool, I think everything here is settled then. Hopefully this discussion helps others in the future who are trying to do the same thing.
