### ISSUE TITLE
Type inference is overly wide when a return statement is within a finally block

### ISSUE THREAD

**Issue by sam-goodwin** [microsoft/TypeScript#48419]
# Bug Report

### 🔎 Search Terms
try, catch, finally, inferred return type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "return statement in finally block"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEEEGEBUFVwDKgC4E8AOBTUBLAdgGaYBOmeAxpgFyjkD2eAzsqAXXTQBQCUoAvAD5QAIgAWmADYS6w0AB9QeAK5SAUCFABRABoAFTTE0ARFBmz4ipCtVoNmrdl16CR4qTNX0mLNnX6gefiEAb1VQFGJUUFDw8NJkJWI8RRUJMNAAX1oAQ2RyUWj0rIJ8bKkomNj4xOSxSWlhAG4i1Qzm1XUwMoB3bNRGUDolZHRhgbr3YU87OglMADppAHNOXx5uRqA)

### 💻 Code

```ts
// ACTUAL type inference: const foo: () => "hello" | null
// EXPECTED type inference: const foo: () => "hello"
const foo = () => {
  try {
    return null
  } catch {
  } finally {
    return "hello";
  }
};

// always outputs "hello"
console.log(foo());
```

### 🙁 Actual behavior

The return type is inferred to `"hello" | null`.

### 🙂 Expected behavior

The return type is inferred to `"hello" `.

**Comment by MartinJohns** [comment]
Duplicate of #27454.

**Comment by sam-goodwin** [comment]
Ughhhh, I searched and failed to find this. Sorry.

**Comment by Josh-Cena** [comment]
This is probably, among other weird things of JS, borrowed from Java. A use-case would be using it as a form of GOTO, but it's still weird
