### ISSUE TITLE
Extended Class Static methods don't refer to correct `this`

### ISSUE THREAD

**Issue by sean256** [microsoft/TypeScript#48414]
# Bug Report

### 🔎 Search Terms

- static class this reference 

### 🕗 Version & Regression Information

I can replicate this bug in all versions provided by the typescript playground, including Nightly:

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/MYGwhgzhAEDKD2BbApgBTAJ2QOwC4GFwpoBvAKGkugAcMBLANzF2WgDN54AuaCXe7AHMA3BSrB42PhgCuwXPAwAKDt1786QgJSkxVKrgAWdCADpV0ALztOo-QF8ye6IOS4AYpyU7y+-VlwZDGxoIxNzW2dHZz5mOmA4JGRYXDjgdzB5RQBPb10-KgCgkOxkAHdQ4wglAHJDZBAQeGgyxRAAExqtOypHaIkpXF4k9Cw8AElBsGxgVmsEFFGcAiIzBeTU3HiMrIxc7rIBiHgQZFMmwSVjxcxlydiZs9cPLy0Dw9XElHxjDsJIGDIAAeLGw7Rg6yWeH+xF8VGuyAAcuUALJuQzwdp5OEFIrBaA1OhDVoYADWEBqPUofScRyGCJ+dA691SjysX2QjL+q1M6xSaR2Cj23lERxOZwuVySXPaLOms1MCORZTRRkx3m60AA9FroKgMPBqMgMLhsgSlaj0ZiatB2vBkDBsPAhsCTENJKFskaCZDbtDVjVTEoAEwAZlDAE4tEA)

### 💻 Code

```ts
class SomeParentClass {
    private foo: string;
    constructor(foo: string) {
        this.foo = foo;
    }

    getFoo() {
        return this.foo;
    }

    static SomeStaticFactory() {
        return new this('hello world');
    }
}

const someParentInstance = SomeParentClass.SomeStaticFactory();
console.log(someParentInstance.getFoo());

class SomeChildClass extends SomeParentClass {
    someNewMethod() {
        return 'it works';
    }
}

const someChildInstance = SomeChildClass.SomeStaticFactory();
console.log(someChildInstance.someNewMethod()); // Property 'someNewMethod' does not exist on type 'SomeParentClass'.(2339)
```

### 🙁 Actual behavior

A subclass which uses a Static method of the parent references the wrong `this`. In the above example, `someChildInstance` which is returned from `SomeChildClass.SomeStaticFactory();` DOES have `someNewMethod`, but TypeScript barfs on it.

### 🙂 Expected behavior

I expect TypeScript to understand that the return type from `SomeChildClass.SomeStaticFactory();` is an instance of `SomeChildClass` and not `SomeParentClass`

**Comment by MartinJohns** [comment]
Sounds like a duplicate of #5863. You can't type the return value of `SomeStaticFactory` as `this` because it's static.

**Comment by MartinJohns** [comment]
Just pointing out that code like this is unsound in TypeScript. It's legible to provide a different incompatible constructor in your subclass, which would result in `new this('hello world')` to result in a runtime error.

```typescript
class SomeChildClass extends SomeParentClass {
    constructor(n: number) {
        super('bla')

        // Causes: n.toExponential is not a function 
        n.toExponential();
    }
}
```

**Comment by sean256** [comment]
#5863 does in fact cover this
