### ISSUE TITLE
Passing interpolated string as string when assigning dynamic keys bypasses type guard

### ISSUE THREAD

**Issue by gildebrand** [microsoft/TypeScript#48417]
# Bug Report

### 🔎 Search Terms
* Object dynamic keys
* String interpolation
* Type guard bypassed

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bugs regarding missing type support for dynamic keys derived from string interpolation

### ⏯ Playground Link

[Small example on TS Playground](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAsiAq5oF4oG8BQVtQPYDsIAuKAZ2ACcBLfAcwG4sdgB3XE86uxgXwwwDGBclBoA3AIYAbKgBMA0hBBRUAcmAALChAirGQ-CMlSArsVgIkK9E2wFzAIgB0LhwBooAek9R4GqqSigQDy8rZQANoABqy4UQC6JM6uHt6+-oEBUKHh0QAkaOLScoogPAlJLk7uXj5+WQH46tnyUABGJsBQtFRi0Pi4UBAUFLgUpB4s-gIaUACSqrJDAB6QAl1UXcC4uVEAZrgmFBVQydWpdRlBovjGcjdgnR4dXdr4ssOBw6PjGDxAA)

### 💻 Code

```ts
type MyType = {
    one: string;
    two: string;
}

const invalidKey = 'three';
const value: MyType = {
    one: "...", // ✅ This is OK
    [`two`]: "...", // ✅This is OK
    [`${invalidKey}`]: "...", // ❌ This isn't OK according to the type, and gives no errors
    [`four`]: "...", // ✅ This is invalid input, but renders errors
}
```

### 🙁 Actual behavior
When passing a interpolated string when constructing an object using dynamic keys, no type check takes place even though it's easy to derive the types, and faulty keys passes the type checks.

### 🙂 Expected behavior
I would expect TS to highlight the line with the invalid key passed in using string interpolation as faulty, since it can easily be derived as being incorrect.

This passing the type checks gives us a faulty sense of everything being ok, and we'd like for this to be captured by TypeScript.

**Comment by fatcerberus** [comment]
Note that it’s legal for objects to have more properties than listed in their type and the excess property check for directly assigned object literals isn’t intended to be comprehensive.
