### ISSUE TITLE
Support `/dev/stdout` as a valid `--out` praramter

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#4841]
See @sebastien https://github.com/Microsoft/TypeScript/issues/1226#issuecomment-141086624 for details:

```
tsc --out /dev/stdout example.ts
error TS5033: Could not write file '/dev/stdout': ESPIPE, invalid seek
```

**Comment by Gaelan** [comment]
:+1:

**Comment by RyanCavanaugh** [comment]
Unclear why we're calling `seek` -- accepting PRs that address that.

**Comment by mhegazy** [comment]
thanks @MartyIX!
