### ISSUE TITLE
Convince browser vendors to support TypeScript in devtools

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#48415]
I had filed this issue to browsers years ago but get ignored somehow. Try to work in dev tools of e.g. Edge with a project that uses TypeScript and fail:

* open https://insiders.vscode.dev/
* make sure sourcemaps are enabled
* open a file via quick pick such as `localHistoryTimeline.ts`
* try to use quick outline to navigate to `provideTimeline`

=> 🐛  quick outline shows no symbols

Upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1087762&q=&can=4

**Comment by RyanCavanaugh** [comment]
We don't have any additional context/leverage on this. The Edge team is also at Microsoft, try talking to them?
