### ISSUE TITLE
Visual Studio 2015 Plugin and TS 1.6 does not properly recognize subclasses with decorators

### ISSUE THREAD

**Issue by WreckedAvent** [Microsoft/TypeScript#4842]
Use case:

I have an abstraction over the angular 1.x API using more typescript-style classes until 2.x is popular enough to be used in the wild. As part of this, I have a base directive abstraction which simplifies the angular API. Classes then use decorators to indicate that they are angular components.

Problem:

In Typescript 1.6, the visual studio (and Typescript playground) does not properly identify subclasses for decorator calls. Instead, they give the red squiggly under it, saying that the types are not compatible, indicating some inherited member not being present on the subclass type.

Example of reproduction:

```typescript
declare var angular: any;

class Component {
	start() {}
}

// error here, "argument typeof SomeDirective is not assignable to type Component,
// property 'start' is missing in typeof SomeDirective"
@directive('something')
class SomeDirective extends Component {
	
}

function directive(name: string) {
	return <T extends Component>(fn: T) => {
		angular.module('app').controller(name, fn);
	}
}
```
(and in the [playground](http://www.typescriptlang.org/Playground#src=declare%20var%20angular%3A%20any%3B%0D%0A%0D%0Aclass%20Component%20%7B%0D%0A%09apply()%20%7B%7D%0D%0A%7D%0D%0A%0D%0A%40directive('something')%0D%0Aclass%20SomeDirective%20extends%20Component%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0Afunction%20directive(name%3A%20string)%20%7B%0D%0A%09return%20%3CT%20extends%20Component%3E(fn%3A%20T)%20%3D%3E%20%7B%0D%0A%09%09angular.module('app').controller(name%2C%20fn)%3B%0D%0A%09%7D%0D%0A%7D))

Interestingly, the error is *still present* even when the subclass *directly implements* whatever the parent class has:
```typescript
declare var angular: any;

class Component {
	start() {}
}

// error here, "argument typeof SomeDirective is not assignable to type Component,
// property 'start' is missing in typeof SomeDirective"
@directive('something')
class SomeDirective extends Component {
	start() {}
}

function directive(name: string) {
	return <T extends Component>(fn: T) => {
		angular.module('app').controller(name, fn);
	}
}
```
(and in the [playground](http://www.typescriptlang.org/Playground#src=declare%20var%20angular%3A%20any%3B%0D%0A%0D%0Aclass%20Component%20%7B%0D%0A%09start()%20%7B%7D%0D%0A%7D%0D%0A%0D%0A%40directive('something')%0D%0Aclass%20SomeDirective%20extends%20Component%20%7B%0D%0A%09start()%20%7B%7D%0D%0A%09%0D%0A%7D%0D%0A%0D%0Afunction%20directive(name%3A%20string)%20%7B%0D%0A%09return%20%3CT%20extends%20Component%3E(fn%3A%20T)%20%3D%3E%20%7B%0D%0A%09%09angular.module('app').controller(name%2C%20fn)%3B%0D%0A%09%7D%0D%0A%7D))

This error also appears to be related only to decorators, normal functions work as expected, even when the decorator is called as a normal function:
```typescript
declare var angular: any;

class Component {
	start() {}
}

// still nope
@directive('something')
class SomeDirective extends Component {
	
}

function directive(name: string) {
	return <T extends Component>(fn: T) => {
		angular.module('app').controller(name, fn);
	}
}


var test = new SomeDirective();

function withGeneric<T extends Component>(something: T) {
	
}


function withTypeErasure(something: Component) {
	
}

withGeneric(test); // ok
withTypeErasure(test); // ok
directive('something')(test); // ok
```
(and in the [playground](http://www.typescriptlang.org/Playground#src=declare%20var%20angular%3A%20any%3B%0D%0A%0D%0Aclass%20Component%20%7B%0D%0A%09start()%20%7B%7D%0D%0A%7D%0D%0A%0D%0A%40directive('something')%0D%0Aclass%20SomeDirective%20extends%20Component%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0Afunction%20directive(name%3A%20string)%20%7B%0D%0A%09return%20%3CT%20extends%20Component%3E(fn%3A%20T)%20%3D%3E%20%7B%0D%0A%09%09angular.module('app').controller(name%2C%20fn)%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0A%0D%0Avar%20test%20%3D%20new%20SomeDirective()%3B%0D%0A%0D%0Afunction%20withGeneric%3CT%20extends%20Component%3E(something%3A%20T)%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20withTypeErasure(something%3A%20Component)%20%7B%0D%0A%09%0D%0A%7D%0D%0A%0D%0AwithGeneric(test)%3B%20%2F%2F%20ok%0D%0AwithTypeErasure(test)%3B%20%2F%2F%20ok%0D%0Adirective('something')(test)%3B%20%2F%2F%20ok))

This code still compiles on save in both the 2015 plugin and the playground, and works as expected. It is just that both environments identify this as an error, and add red squiggles everywhere.

Expected Behavior:

None of the provided examples should provide an error in the IDEs, and if there is some error in here I'm not seeing, the error messaging needs to be better improved to indicate what. In short, it should behave like 1.5 did.

**Comment by mhegazy** [comment]
The decorator operate on the constructor function of the class. so your  directive` takes the class constructor (i.e. `typeof SomeDirective`) as an argument and not an instance of the class (i.e. `SomeDirective`).

Your type annotation, mentioned that you have to be a `Component`, i.e. have a field called `start`, but the constructor function of `SomeDirective` does not (the return type of calling it with new does, but that is the instance type)

so i think what you meant to write was:

```ts
function directive(name: string) {
    return <T extends typeof Component>(fn: T) => {
        angular.module('app').controller(name, fn);
    }
}
```

**Comment by WreckedAvent** [comment]
If that is the case, is there a reason it worked correctly in 1.5, and even as expected, only allowing it to be added to `Component` subclasses?

**Comment by WreckedAvent** [comment]
Changing it all to `typeof Component` (et. al) does appear to make the error go away in the IDEs. That solves my issue, but does leave the questions.

**Comment by mhegazy** [comment]
in 1.5 the compiler was not checking decorators as a function call. it was checking them against a generic type that it internally created; that was a bug, and caused it to be more lax than it should be. in 1.6 it checks the decorator as if you were using it in a call expressions, e.g. 
```ts
@directive('something')
class SomeDirective {
}

// is checked as if you wrote
class SomeDirective {
}
SomeDirective = directive('something')(SomeDirectie);
```

**Comment by WreckedAvent** [comment]
Ok, that makes sense. That might want to be documented on the breaking changes page then.

**Comment by mhegazy** [comment]
done. thanks for pointing this out. here is the issue: #3246
