### ISSUE TITLE
Initialization not required for interface and class with same name

### ISSUE THREAD

**Issue by JacobZwang** [microsoft/TypeScript#48439]
# Bug Report

### 🔎 Search Terms

initialize no error class interface type checks

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about interfaces and classes.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=14&ssc=70&pln=1&pc=1#code/MYGwhgzhAECiAeAHApsALsgJgIWQCzADcBLAewCdoBvAWACgBIDCNALmhfOIDsBzAbmgB6IdGRJUGTGPLkK9BiOgAFOSnJoAntADkzNDugEY3UtB7E0xMCGIAvZJTDdpxE6TTRMyAGYWMINqQEMS83Fjm3NBoeMjQwKTcnACu6BQAdAAUAEwArABsACwAlPQAvvT0PBjkPmDAcQCq4RLoWLgEJBTUCvrsnDwC5ZV0oMHQzeIobTj4RGSUtIxKpjJy5MN09OEA7hMt01Id8xSZxen66cguEADqlniZenhu0DvEICDx5JB40GCecjJbhWAC2yB0xX4QA)

### 💻 Code

```ts
class ExpectedBehavior {
	test: string; // expected error
	// Property 'test' has no initializer and is not definitely assigned in the constructor.(2564)
}

interface UnexpectedBehavior {
	test: string;
}

class UnexpectedBehavior {
	// no error
}

new UnexpectedBehavior().test.endsWith('this will crash at runtime');
```

### 🙁 Actual behavior

When creating a class and interface with the same name, the properties defined in the interface are not required to be initialized by the class. The class can constructed and accessed without any type error and will error at runtime.

### 🙂 Expected behavior

The class should have a type error when not all properties on the interface with the same name are initialized. From my understanding, when properties are defined on an interface with the same name as a class it should perform exactly the same as when properties are defined directly on the class.

**Comment by IllusionMH** [comment]
This technique is used for Class augmentation https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation
and should be used to describe actual runtime behavior with added props/methods. 

To have warnings about missing props or incorrect types you should use `implements`.

**Comment by JacobZwang** [comment]
I see, so this is intended behavior. A bit disappointing since using `implements` is quite impractical in many situations because it requires you to manually rewrite property definitions (or generate them using some sort of tool, either way, muddies up the code if there are a large number of properties). But I supposed that's outside the scope of this issue, so I'll go ahead and close it. Thanks for clarifying.

**Comment by RushikeshPatange** [comment]
> This technique is used for Class augmentation https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation and should be used to describe actual runtime behavior with added props/methods.
> 
> To have warnings about missing props or incorrect types you should use `implements`.

Hi @JacobZwang and @IllusionMH , I also encountered the same issue #61370 when class and interface share the same name.

Commenting here to share my observation on below statement:

> To have warnings about missing props or incorrect types you should use `implements`.

I have tried it **with/without** `implements` keyword but there is no success in it, still it will not warn about missing props or incorrect types.I think how declaration merging/class augmentation works between `classes` and `interfaces` particularly when they share the same name and its implications for implementation guarantees need to be documented somewhere to avoid similar confusion in future.

### ⏯ Playground Link
[TypeScript Playground Link](https://www.typescriptlang.org/play/?ts=5.8.2#code/JYOwLgpgTgZghgYwgAgArQM4HsTIN4BQyxyIcAthAFzIZhSgDmA3ESXI9aQK7kBG0ViWSMoECGAAUAShoA3LMAAmrAL4ECCADZwMGNJhzJg5AA5aIlcPvRRsuQsLKUadBiBZtiHLiF4CoVi9kBBw3bgQwLChJZy43JgAaZB8aP35oaXxg4TAAC2AMADo45ABeUgoIIWESfMKin3KUzhridWCAek7kAFlCjCZkAANRcTBh5Ep8rCUCDtCQOmRIZYqQCAB3AzscSQAiACEsPn3kgBYAZmlWVbAisYkZZmRu5AA5LBCsM2ALAFowCYUNAoNFknxuGBkPA-vo4NCoNxwMCgA)
