### ISSUE TITLE
readonly tuple breaks type inferrence - only inferred type of first item returned each time

### ISSUE THREAD

**Issue by Roaders** [microsoft/TypeScript#48435]
# Bug Report

### 🔎 Search Terms

readonly tuple

### 🕗 Version & Regression Information

4.6.2 (playground)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Why doesn't type inference work on this interface`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4ghsYBhAFnATnAxsC6CWAzsPlgHJwC20AvFAOQAiEAbqdBdfVAD4MBCCXOhBQAMqwgAbegG4AsACglEAB5gA9umBR8AO2EAzbNHiJUGbMKIksAHgAqUNbj0ATQrCEXMOPDdJOWi9zNF9rYkCqCAA+KABvJShk3TcALihiAj0AcwVFFKg9aIyHfIBfJRV1LR1QSCgAZWBMXByQMRsoOgBtADoBgEkfK39IrCQNPRY8Qnwp5taIdp6AXVXeKHQIODcpqVF+oZG-AnHJ6dn5vUWEZZA11fzqzW0oeuhbtpAAJQhgACu6D0DnAEDsSRSDjEGg0AGsAWBnKpXB4mi07u1OsQADSQ5JOFwQdyeMzIMKjM62IJ4xRxOgAvRwvQaADuemRqM8X3uf0BwNBkEGlDAUkcMPhiJxUAccQA-FBGAg4AA1fAQVlQDI89p8oEgsHC0Xi2EIsDS2XPRQfGWIqQQADy6D+uwdegO3SgRz6cD0D3Wm22u32hwGPr9jytAHoo1A-pQNDNPCgdm4oIZ0BpKFApF1fWmwHBCIQIJ58HUNFAABKpnW-f76wUQI1SJQ2ut6gWGkVihx17E6Ikk22ix3O1Nug4WznEtFkk4RanRelQAAUq-xUDDWAppwCWAHpX7NiUAEpunFGcy2Xpz0O0auUBl9IY8NXU9Kw4gMr7-eeaJeTIsuym4KjWuwdg2XZCj2djgW4FrHriMoxJuGRXsBejRrGgyGOiSztO8YJQJQCA7qWMpbFBeieMAaA6FkmIgNK+B4SyOiFsWFG5sQ7yVg4cD4FIkH8gaMGim2xHwSJjbdsam59hi3y0oUikER0XT3p4Dh2mOLpuJOzEKTOw7zrui5RNQtIrmpTEmWiwzmWMtgXDM6BzAsSn3I4LF6K+6BxvKcZajKgnCV5urUU2LaOEhwAWjE2FxhACZJu+uzppm2Y8To+a6HhcDvGFyI2J4nElmWFb4UxnZic2PaSQ0AlCTJ0H1fJBRQnFzVSPZ2m6U6+mGSpUJ9SE5KWHu4w0koNndcVWler+vn+aFQnwZ+Awvm+Yg9asoHVd8tXRbBPQ9RtW4DLtYWrAlaFQBhN5JQAoqoVCjkRkCeAARtIbJVIoaivDo+hGCYUCOZNFkTFMbkeTcEUgBCnUEguzmkGNZlQ+j5DRJ6WPhDjM0ozKx3EQyQE3tZCSbsU1ClGjVKkPkhRYL6Vb5vaq47tjTNYBkBOUvujiM-uMSnhk32wvavosykWCw3gwDc05fMC94qvCw4ovjDE0osHAUgAhAGRKsAqrqqyEuk1FYIVADWBSEWnjMGwWAQEEda6D2KXEsAniQ4TfOuVcnnqXYTCsOwUBBPQ0pZPoORxIkJN08Ekduxw0TcEWUAKzRwBy8kbN6Bz7hc9bUsaDLHIp4UhR0Zmmp6BqUDPegmboKu9AALL-CgGhpux3ujtQBgQG4fT0KeRdQJUJP525yvWwnuQ0yTDcoE3RSt+3nfd33dGD0UGggz7Y+4JP0+z-P89KI7ztQIIiB4B0kjhepI-2hfAc6y5ivuWuHWCOz9hCiAkDMGQ0o9AAkoL9dAydaZ4zoPQUBr9xDvxzp4fOxBZ4lzLm4CuktpY7FrpuTe28W6aj3loA+-dj7D3wOfP2E8p4z03PPVmADl4ZBgXAt8dd67JEbmyHe1CO60N7vQoep8v6+3HlfdhJNb4AxtIxb4SAnZcU8L0V27BPaI2lGgkQEDpB1ieADIGtQ85TF4uo+4ej3ZBG1IjMmkA7D2PaJo52pZpQZ2jrHFc9BGjvXtPhROcgXjWJwQxRGxi36QJcepNx4JPEgG8dovx8SMGQPoCuAArPkq0aiIrqkIE2T0QY9jukOI4j20Q6xGKEK-UxH8mIWOUIDGobwYlQDcBAYwAIpDADqc4w6vJbbuM8WUpsfi6kx2zkEkJPtwm5EiV04GNiC59IGXAIZwB4mtKSTVSZqTSmllmQIZpIgcnSDyZ6QpsggA)

### 💻 Code

```ts
type strategyClasses = [DeviceNameStrategy, BatteryLevelStrategy];

export const strategyDeviceName: StrategyReturnType<strategyClasses, 'Device Name'> = 'Sample String';
export const strategyBatteryLevel: StrategyReturnType<strategyClasses, 'Battery Level'> = 55; // correctly typed as number

type readonlyStrategies= readonly [DeviceNameStrategy, BatteryLevelStrategy]; // i.e. typeof [new DeviceNameStrategy(), new BatteryLevelStrategy()] as const

export const defaultDeviceName: StrategyReturnType<readonlyStrategies, 'Device Name'> = 'Sample String';
export const defaultBatteryLevel: StrategyReturnType<readonlyStrategies, 'Battery Level'> = 55; // ERROR: incorectly typed as string
```

### 🙁 Actual behavior

when passing a normal tuple to my `StrategyReturnType` the correct inferred type is returned. When passing the same tuple that is `readonly` the inferred type of the first item in the tuple is always returned.

The tuple is readonly as it's created as so:

```ts
const myStrategies = [new strategyOne(), new strategyTwo()] as const;
type StrategyTuple = typeof myStrategies;
```

### 🙂 Expected behavior

The inferred return value of each strategy in a tuple should be returned regardless of if the tuple is readonly or not.

**Comment by whzx5byb** [comment]
```ts
type TailStrategyReturnTypeImpl<TStrategyListTail extends TupleOrReadOnly, T extends GattCharacteristicName> = 
  TStrategyListTail extends readonly [any, infer TailHead, ...infer LTail]
//                           ^ You need "readonly" here, because a readonly tuple is not assignable to a writable one.
  ? StrategyReturnTypeImpl<[TailHead, ...LTail], T>
  : unknown
;
```

**Comment by Roaders** [comment]
Brilliant, many thanks
