### ISSUE TITLE
out option in tsconfig file is not relative to project

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#4843]
Eg. here is tsconfig.json file that's present in directory called project
tsconfig.json:
```Json
{
   "compilerOptions": { "out": "test.js" }
}
```
Compiling this from a directory above project with command results in test.js to be generated in current directory instead of in project
```
tsc --p project
```
And if I do 
```
cd project
tsc
```
The test.js is generated in project directory. 
Shouldn't test.js be always relative to project and be generated in project directory

Look at dbb2772ed8af81e0356a8da91f0bcf10a2fc92bc, expected emittedFiles shouldn't they be inside DifferentNamesSpecified

**Comment by weswigham** [comment]
On the subject of relative paths, "outFile" is also not currently relative to "outDir". Should it be?

**Comment by sheetalkamat** [comment]
Out paths are always relative current directory, but if the --p is specified the paths should be relative to project directory.

**Comment by mhegazy** [comment]
that is an intentional "bug". see https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L128-L129.

use outFile instead.
