### ISSUE TITLE
Add minified version

### ISSUE THREAD

**Issue by stephenlacy** [microsoft/TypeScript#4844]
Propose adding a minified version of `typescript.js` `lib/typescript.min.js`.
This will allow cdn and browser installs (browserify, etc) to have a smaller file to load into memory.

https://github.com/jsdelivr/jsdelivr/pull/6956

**Comment by mhegazy** [comment]
we would accept a PR for this. we would add a new build target to minify only in if not in debug mode.

**Comment by BSG-75** [comment]
Any updates on this?

**Comment by RyanCavanaugh** [comment]
We've looked into this and the gains are very minimal (especially with compression), and people both patch and live-debug these sources so would be quite disrupted by it.
