### ISSUE TITLE
Missing TypeScript 4.6.3 for Visual Studio (nupkg)

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#48456]
# Bug Report
https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild
is missing released 4.6.3
https://github.com/microsoft/TypeScript/releases/tag/v4.6.3
which links only the npm package

### 🕗 Version & Regression Information

ref #42880 :-)

**Comment by NoelAbrahams** [comment]
Clearly the long-standing practice of treating Visual Studio users as second-class citizens in this repo continues.

I mean to say, the 4.6.2 IDE experience is totally buggy, and yet a fix is released only to npm. 

Quite lax.

**Comment by DanielRosenwasser** [comment]
Should be out now.

**Comment by HolgerJeromin** [comment]
I think you meant #48463
Thanks.

https://github.com/microsoft/TypeScript/milestone/162?closed=1

**Comment by HolgerJeromin** [comment]
https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild
is up to date. Thanks
cc @NoelAbrahams

**Comment by NoelAbrahams** [comment]
Another annoyance that was introduced with 4.6.2 (although this is lesser an issue than #48463): 

https://github.com/microsoft/TypeScript/issues/48006

Please do make these fixes available via Nuget for Visual Studio users. 

For large VS solutions (40+ projects) it's just not feasible to install on every project via npm. We decided to go with Nuget after the TS global installer was discontinued (from VS 2022 I believe).
