### ISSUE TITLE
New tuple type

### ISSUE THREAD

**Issue by haydaralrikabi** [microsoft/TypeScript#48452]
As the [proposal to omit array methods from tuples](https://github.com/microsoft/TypeScript/issues/6325) has been declined to avoid breaking existing codes; I would suggest that we have a "strictTuple" type that denies those array methods on tuples.
This gives developers the option whether to keep the array methods on tuples or not.

**Reference:** https://stackoverflow.com/a/64070080/1883323

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
