### ISSUE TITLE
ConstructorParamaters for extended interfaces

### ISSUE THREAD

**Issue by s-cork** [microsoft/TypeScript#48458]
# Bug Report

### 🔎 Search Terms

ConstructorParameters
also might be related to overloading, #37039 - so possibly a duplicate.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ConstructorParameters

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRyIEA7gBQCUAXMnCAJ4EC+BBoksiKAQnFGQQAHpBAATAM5pMOAsRLkKwupLBRQAc1r0mrdvjCMADigzoAglE3SAvMgDC6EGqgBXBGHRQACgLgAthBckgA85gB8ANwERqbI-FBWNsj2Ti7qHl6+-kEhoYnRQA)

### 💻 Code

```ts
interface Foo {
    new(): any
}

interface Bar extends Foo {
    new(x: string): any
}

type FooArgs = ConstructorParameters<Foo>; // []
type BarArgs = ConstructorParameters<Bar>; // []
```

### 🙁 Actual behavior

`BarArgs` is an empty array.

### 🙂 Expected behavior

`BarArgs` should be `[x: string]`, which it is if it doesn't extend `Foo`

### Additional Context:

Using an edited version of [this answer](https://stackoverflow.com/questions/59535995/parameters-generic-of-overloaded-function-doesnt-contain-all-options/59538756#59538756) for demonstration I can force it to work.

```ts
type ConstructorParameters2<T extends abstract new (...args: any) => any> = T extends {
    new (...args: infer P1): any;
    new (...args: infer P2): any;
}
    ? P1
    : never;

type BarArgs = ConstructorParameters2<Bar>; // [x: string]

```

**Comment by RyanCavanaugh** [comment]
Extending an interface adds a overload at the *top* of the overload list*, whereas conditional types always pick the *last* overload when doing `infer` (which is what `ConstructorParameters` does). If you intended to replace the constructor, you'd have to write this instead, which works as expected:
```ts
interface Foo {
    new(): any
}

type PropertiesOf<T> = { [K in keyof T]: T[K] };
interface Bar extends PropertiesOf<Foo> {
    new(x: string): any
}

type FooArgs = ConstructorParameters<Foo>;
type BarArgs = ConstructorParameters<Bar>;
```

`*` i.e. this is valid
```ts
interface Foo {
    new(): any
}

interface Bar extends Foo {
    new(x: string): any
}

type FooArgs = ConstructorParameters<Foo>;
type BarArgs = ConstructorParameters<Bar>;

declare const b: Bar;
new b();
```

**Comment by s-cork** [comment]
Thanks for the pro tips @RyanCavanaugh 

Makes sense, and just saved me hours of frustration.
