### ISSUE TITLE
Union type property wrongly incompatible

### ISSUE THREAD

**Issue by amortemousque** [microsoft/TypeScript#48457]
# Bug Report

### 🔎 Search Terms

`Union types property incompatible` 

### 🕗 Version & Regression Information

Tested on 4.6.2 and 4.6.3

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKuEHkB20C8UDeAoKUBmA9gQFyY65QBGAhgE6kBEBKD5Avlh1qJLPDAHcCUdNlyESZClTqNgQ1rg5ce0AKpIAlszi90uxCigAfPpEEEs3eFABiRAyKgbtSAwG0GEhgF0reAFckAGNgVyhg2ghqYAgACglSewIDAEpSFx0bMSgo4ADaJCkKCQAadk4rAHoqqGAAC00AZ3wg0PChWgBrFogANwgizTwoTWBciHzCloboJuoAW2gGzSQAc1GiygIGiOYAEzHXJqxAkLDmKD7qABtNfYBhKJj4xLsHeHTnLSzeHLyCkUJAA6Gi0ESodBMFhQAD8mHwRCgbCgpAwiOEyiAA)

### 💻 Code

```ts
type TypeOne = {
  foo: {
    bar: "one"
  }
}

type TypeTwo = {
  foo: {
    bar: "two"
  }
}

type UnionType = TypeOne | TypeTwo

type FooType = UnionType["foo"]

function dontWork(foo: FooType): UnionType {
  return {
    foo,
  }
}
```

### 🙁 Actual behavior

Got a TS error: 
```
Type '{ foo: { bar: "one"; } | { bar: "two"; }; }' is not assignable to type 'UnionType'.
  Type '{ foo: { bar: "one"; } | { bar: "two"; }; }' is not assignable to type 'TypeTwo'.
    Types of property 'foo' are incompatible.
      Type '{ bar: "one"; } | { bar: "two"; }' is not assignable to type '{ bar: "two"; }'.
        Type '{ bar: "one"; }' is not assignable to type '{ bar: "two"; }'.
          Types of property 'bar' are incompatible.
            Type '"one"' is not assignable to type '"two"'
```

### 🙂 Expected behavior

Expect typescript not to complain 🙂

**Comment by MartinJohns** [comment]
The type that `UnionType` represents:

```typescript
| { foo: { bar: "one" } }
| { foo: { bar: "two" } }
```

The type you're trying to return:

```typescript
{
    foo: { bar: "one" } | { bar: "two" }
}
```

These are correctly incompatible.

**Comment by MartinJohns** [comment]
This is also the reason why this code works:

```typescript
function create(foo: FooType): UnionType {
  return foo.bar === "one" ? { foo } : { foo }
}
```

- If `foo.bar` equals `"one"`, then the type is narrowed to `{ bar: "one" } `, and the object literal is `{ foo: { bar: "one" } }`.
- Otherwise the type is narrowed to `{ bar: "two" }`, and the object literal is `{ foo: { bar: "two" } }`.
