### ISSUE TITLE
tsc doesnt transform every static readonly from a file

### ISSUE THREAD

**Issue by romain22222** [microsoft/TypeScript#48453]
# Bug Report

### 🔎 Search Terms

tsc, static readonly variables, missing transformations

### 🕗 Version & Regression Information

- This happen in version 4.3.2
- I was unable to test this on prior versions because the problematic variables weren't in the file prior this version

### ⏯ Playground Link

https://github.com/DraftBot-A-Discord-Adventure/DraftBot/tree/slash-commands

### 💻 Code

Actually, the relevant code is in [Constants.ts](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/slash-commands/src/core/Constants.ts).

### 🙁 Actual behavior

Some static readonly are getting ignored by tsc, and everytime the same ones (take a look at `static readonly XP`)

### 🙂 Expected behavior

I'd expect that everything is transformed from ts to js

**Comment by MartinJohns** [comment]
You're not assigning anything to your static variable, so there's nothing to transform to JS.

**Comment by BastLast** [comment]
We got the problem and fixed it 🙃 this issue can be closed thanks !

**Comment by MartinJohns** [comment]
Related: #27899
