### ISSUE TITLE
postMessage types don't align with what is in MDN and the spec

### ISSUE THREAD

**Issue by 43081j** [microsoft/TypeScript#48469]
According to MDN and the linked spec ([here](https://html.spec.whatwg.org/multipage/web-messaging.html#dom-window-postmessage-options-dev)), `postMessage` has two signatures:

```ts
window.postMessage(message [, options ])
window.postMessage(message, targetOrigin [, transfer ])
```

~Typescript's dom lib doesn't contain the second one (with a string parameter).~

MDN doesn't contain the first one (with an object).

This smells to me like a change MDN hasn't picked up on yet ~and typescript has removed too soon~. But i can't find much around the web mentioning it, or explaining why there's a difference.

Since i also can't find any other issues or PRs around this, i feel like i must be missing something...

As far as i can tell, browsers still support passing a string origin, so im not sure why it wouldn't exist in the types anymore.

edit:

i misread the spec, this is specific to `MessageEvent#source`. the types on `window` are correct.

```ts
({} as unknown as MessageEvent).source?.postMessage({}, 'abc'); // Fails to compile
```

**Comment by IllusionMH** [comment]
You forgot to fill in issue template and provide playground repro.
In playground you would see that TS has both overloads after 4.4 and it's still there in Nightly as well [link](https://www.typescriptlang.org/play?ts=4.6.2#code/O4SwdgJg9sB0AOUDOAXAsgUyUghgcwwAoByAWyT2IBoACAbxpRwCcCUB5ZkPcALhuJQulWimY4wSAGYZm-ANoBdGgF8AlAG4AUKEgwEydFlwES5EQKHdqNJZqA)

**Comment by 43081j** [comment]
it seems to be when used with a source, my mistake:

```ts
({} as unknown as MessageEvent).source?.postMessage({}, 'abc'); // ERROR
```

https://www.typescriptlang.org/play?ts=4.6.2#code/BQbwvgBAhgzhCuA7A1og9gd0dOBZApjDFAOb4CiAbvogC4CUAdDGvAE4DG+A-IwA5oYtAkVL5QYADQQA5FABGHGfQDcAKCA

maybe this is correct behaviour? can't seem to find in the spec where it is defined

**Comment by IllusionMH** [comment]
That's correct behavior because you don't have just `Window` but `MessageEventSource` ([spec](https://html.spec.whatwg.org/multipage/comms.html#messageeventsource)) which is union of objects that have different signatures for `postMessage`. You need to narrow it or use assertions.

**Comment by 43081j** [comment]
```ts
(({} as unknown as MessageEvent).source as WindowProxy).postMessage({}, 'abc');
```

yup now i understand. I saw the union and each of those types but didn't realise the signatures wouldn't just end up merged.

thanks for the explanation, will close this.
