### ISSUE TITLE
 Type 'T' is not assignable to type when Generic Anonymous Function is inside an interface.

### ISSUE THREAD

**Issue by zkldi** [microsoft/TypeScript#48461]
# Bug Report

### 🔎 Search Terms

Generic Anonymous Function inside Interface
Type 'T' is not assignable

### 🕗 Version & Regression Information

Appears to be an error on all versions back to atleast 4.0.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5#code/JYOwLgpgTgZghgYwgAgOIRNYCBiIDCA9uHKNMgN4BQytyMIAXMgDwAqAfABRzNsCUyALwdkcEAE8qAXypUExAM5gxzdJijY8REmSjDK9Jsh7NlmkAHNBI5ACI4d5NIDcQA)

### 💻 Code

```ts
interface GenericFnContainer {
    fn: <T>(a: T) => any
}

const a: GenericFnContainer = { fn: (a: string) => "a" };
```

### 🙁 Actual behavior

```
Type '(a: string) => string' is not assignable to type '<T>(a: T) => any'.
  Types of parameters 'a' and 'a' are incompatible.
    Type 'T' is not assignable to type 'string'.
```

### 🙂 Expected behavior

This shouldn't be an error, as the generic in this function is `string`. I might've stumbled onto a known bug, or maybe I'm using this syntax wrong? I'm not sure.

**Comment by whzx5byb** [comment]
Consider the following code. 
`fn2(1)` is a legal call because `<T>(a: T) => any` can receive anything. But `(a: string) => "a"` can only receive string type input, and it will cause a runtime error.
```ts
const fn1: (a: string) => string = function (a) {
  return a.toLowerCase();
}

// @ts-ignore-error
const fn2: <T>(a: T) => any = fn1;

fn2(1);
```
