### ISSUE TITLE
Property name bind/call/apply breaks generic inference in non-Function edge case

### ISSUE THREAD

**Issue by texastoland** [microsoft/TypeScript#48474]
# Bug Report

### 🔎 Search Terms

<kbd>bind/call/apply breaks generic inference</kbd>

### 🕗 Version & Regression Information

- This is the behavior in _every (all) Bug Workbench_ version, and I reviewed the _entire_ FAQ

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.7.0-dev.20220302#code/MYewdgzgLgBAbiAlgEwAoCcQA8CeMC8MAPACoCC6A5hDAKZZS1jI0DaArmANZggDuYAPwBdAjDC04tdAD4AFACgYMSrSiN0ALiXKYAHxgBvHbt2qommHK60cl6OkRhKASgIz4SZCdMwA9H4w6EwAhgC2TpQwIQAOMQA2eFAg0WA4UAAWkXRYwLQxsMAh8fEwIOgwAEZOyDAAZohYtDROddJMeT6msQk4gpZyAHTDIVQQluRjbvgeCChdMAC+PgZy1rb2UI7O07NeLjoBQWrs6GAwyDhg4YjAZZUAVrTAUAouloYwrDZ2MA6Rwksc1qixgADIrKxJtRRPRGMw2BIpOhhDpBDBODx+GAdJYjnxEJl6pwXohwH9EJRrlBTrQYIg6tExvSwG10MFvKYhiMxhMKNRdp4UILjMo-AAqcV0ZhlRlQHAxZowcV+Q6BPjoWLEsCk8lOGCgVmUnSG6AwDIhZjxaRicwaFnQS15ECMgBiJKgZPO6M+5ksdptoP9ag0ABofL61KHonFEksxBardI1TAYiEIDRkOwwmE8HUPV76YzDQ1KLTaskqnSiiUQpVrTpgjSzuJaHwYBhsDg5D04+i5CKg0ZFtHRbojk4EDYDcV4pUQsAuDACUSfj4-VYAPrRn6C8zrPDpv5bSIucOmCdgKfV2fzxfLwkZMoFL3FJmUHy935f8EQtbbmBNwARmjUYBXcGNem5QYe2ZI9oQgFwkPPJY3CPS0cAUZYFCOCAMhAdh4lqVobSIJFpBkBRTVgLIxGBTtcDWXcINNEBrUGeIQEoOQAANaIAEkMH5Fh4pCcMCXxdAAPUEBQskGPhyiIuTEDkAAiRT0CItS3Fw-DCOQMAAHJChAMIYkQBsgA)

### 💻 Code

```ts repro
const voidProxy = <TArgs extends [unknown?] = never>(
  getter:
    | {
        get: (key: string) => void
        // renaming apply to anything except call or bind fixes inference
        apply?: (...args: TArgs) => void
      }
    | ((key: string) => void)

// return dynamic object
): { [key: string]: void } & ([TArgs] extends [never]
  ? unknown
  : // with function signature if args inferred
    (...args: TArgs) => void) => {
  /** end of types */

  // wrap function in config
  const handler = getter instanceof Function ? { get: getter } : getter,
    { get, apply } = handler
  // pass dummy function if configured to be callable
  return new Proxy(apply ? () => {} : {}, {
    // invoke callback with key
    get: (_, key) => get(key as string),
    // invoke callback with optional arg
    apply: apply && ((_, _1, args) => apply(...(args as TArgs))),
  }) as any
}

// should infer <never>
const hi = voidProxy((key) => console.log(`hi ${key}`))
//         ^?
hi.world
hi("world") // shouldn't compile

```

### 🙁 Actual behavior

`voidProxy` is inferred as `voidProxy<[unknown?]>` (the base type of `TArgs`) and `hi` is callable.

### 🙂 Expected behavior

`voidProxy` is inferred as `voidProxy<never>` and `hi` isn't callable.

### Observations

- Renaming `apply` to `invoke` or almost anything else fixes inference
- Renaming `apply` to `call` or `bind` doesn't change inference
- ~~Passing a function value (vs expression) like `console.log` fixes inference~~
- Refactoring `get` to a non-function type fixes inference

I wouldn't expect anyone else to stumble into this but tracking in case there's an obvious cause.

**Comment by RyanCavanaugh** [comment]
This is generally expected; the structural inference we use for collecting generic inference candidates doesn't match against the non-type-parameter-referencing parts of the outer type. Almost always it's possible to rewrite the function signature in a way where this doesn't matter; I try to demonstrate this for simple examples but this one is pretty hairy 🙂

> Passing a function value (vs expression) like console.log fixes inference

This is the only one that surprises me - can you show what you mean? I don't see any change doing this:
```ts
const f = (key) => console.log(`hi ${key}`);
const hi = voidProxy(f)
//         ^?
hi.world
hi("world") // shouldn't compile
```

**Comment by texastoland** [comment]
I assume there's a misunderstanding. Just rename the `apply` property to any name except `call` or `bind`. It's a bare object so I wouldn't expect any inference from `Function`.


```ts
const voidProxy = <TArgs extends [any?] = never>(
  getter:
    | {
        get: (key: string) => void
        invoke?: (...args: TArgs) => void
        ^ here and where it's destructured too
      }
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.7.0-dev.20220302#code/MYewdgzgLgBAbiAlgEwAoCcQA8CeMC8MAPACoCC6A5hDAKZZS1jI0DaAhmDgPwC6BMMLTi10APgAUAKBgxKtKI3QAuGbJgAfGAG8169fKjKYEgNa0cx6OkRhKASgJj4SZHv0wA9J5jom7AFtbShh2AAcwgBs8KBBQrigAC2C6LGBaMNhgdkjImBB0GAAjW2QYADNELFoaW3LRJnT3fVsEc25jCQA6HvYqCGNyfsd8ZwQUZpgAX3ctCTMLKygbOxGx13s1b18FAFd0MBhkHDBAxGB8ooArWmAoKXtjbRhWc0sYa2DeY3GyqZgAGQmVhDaj8eiMZhsIQidC8NTcGC7MCmMAgADuYDUxm26MQSQqyLuiHAH0QlFOUH2tBgiHKoX6tLA9XQfjc+m6vX6gwo1DWLhQ-N0sk8ACpRXRmPl6VAcGEajBRZ4tj50ehwoSwMTSbYYKBmeS1ProDBEpxkJFRAJDEomdBOOkQPSAGJEqAkw6I56GYw2q3-X0KJQAGnc3oUwaZbVoxnCUTw-0IZuYlvQKpgYXYEBoyF2AQCeHKbo9tPp+sqlGpZVixRp2Vy7CKlrUfipB0EtHRMAw2BwEjj0RgiIkQoDOimkeF6m2rRA5j1OUiRXYwFMMDxBLe7h9JgA+pG3vzDAs8FmPstgvZQ-oZ2BowvcsvV+v8Yl8pkPTkGZR3AP3n-ASBeZ9xgXcAEZIz6PknFCCJok5Lp+0ZM9QQgex0OvaZHDPTgcCkGYpG2CBEhAXZIjKOorSIGFRDEKRjVgZIBF+HtcHmQ8YONEBLS6SIQEoCQAAMmIAEm0N4pkE9DCJ8Dx1AAPW4KRki6dECnImSYAAASgCAAFp6HlO4DNZAplMQCQACI1PQcjLM2IA)

> This is generally expected

This is extremely edge case but doubtfully intended. It took several hours trimming down the code for a test case to even accidentally discover the cause. I encountered 3 additional issues along the way. 2 I suspect _are_ expected and the last 1 I'll report with a smaller test case because it seems wrong although equally edge case. I left this case longer for context.

> I don't see any change doing this:

You're right. That's what I was referring to. It worked in my library but not my trimmed-down test case.

> This is generally expected; the structural inference we use for collecting generic inference candidates doesn't match against the non-type-parameter-referencing parts of the outer type.

That matches my expectation. The object part of my union infers correctly but the function part doesn't participate at all. Therefore `TArgs` isn't specialized beyond its base type `[any?`]. Did I understand correctly?

The odd thing is for `bind`/`call`/`apply` it doesn't proceed to use the provided default `never`. It stops at `[any?]` which breaks the `[never`] check in my return type.

**Comment by RyanCavanaugh** [comment]
> That matches my expectation.

If you agree with this, then I don't understand what the disconnect is.

 * Functions have a built-in `apply` method
 * The value being inferred from is a function, thus has an `apply` property
 * An inference position exists at the `apply` property
 * A candidate is collected from that that position
 * Being the lone candidate for `TArgs`, it is the inference result

**Comment by RyanCavanaugh** [comment]
The only thing that matters for inference is the function signature; the reduced example is
```ts
declare const voidProxy: <TArgs extends [unknown?] = never>(
    getter:
    | {
        get: (key: string) => void
        apply?: (...args: TArgs) => void
      }
    | ((key: string) => void)
) => { [key: string]: void } & ([TArgs] extends [never]
  ? unknown
  : // with function signature if args inferred
    (...args: TArgs) => void);

const hi = voidProxy((key) => console.log(`hi ${key}`));
```
where the function expression is a (partial) match for `{ get: (key: string) => void; apply?: (...args: TArgs) => void }` and thus collects a `TArgs` candidate

**Comment by texastoland** [comment]
Oh wow I hadn't considered the intersection between the config and the closure 🙀 Sorry if I'm missing something you explained already:

1. Does that mean `TArgs` infers from `Function.apply` here?
2. If so why `[unknown?]` instead of whatever `[thisArg]` resolves to?
3. If not why `[unknown?]` instead of the default (`= never`)? I assume that means it matched on something (maybe `[thisArg]`) it couldn't narrow beyond my constraint (`extends [unknown?]`).
4. My XY problem was representing the union of a `ProxyHandler`-like config and its `get` property. Am I hitting a fundamental limitation of structural typing if I want to name the other property `apply`?

Generally happy to close since none of it seems odd to you.

**Comment by RyanCavanaugh** [comment]
1. Yes
2. It's a contravariant inference site, so the upper bound applies
3. Once there's at least one candidate, the default is never chosen
4. I don't think you need to rename `apply` necessarily, but I can't figure out what the intended behavior of this function is. If you can supply 4-6 examples of how it's supposed to work, I can write a definition
