### ISSUE TITLE
'typeof' doesn't return real type in switch control flow(type guard)

### ISSUE THREAD

**Issue by Messiahhh** [microsoft/TypeScript#48471]
# Bug Report

### 🔎 Search Terms

type guard、narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/MYewdgzgLgBAbgQwDYFcCmAuGYUFsBGaATjAD4zRECWYA5jALwwCMADKwNwBQXAZimGBQq4GLzAAKAJRYcBYmRgCAJml400ymAG8uMfRQDuVKMAAWMCVACeABzQhe8ZOik69Bz8AQQ0MAORyhET+GB6eETCgkLBwjDA29o7OqGjckZFEaFAoRGDw6RmqvAgoSFBY4Rn6WTl5MFUAvlyNQA)

### 💻 Code

```
const value: number | string = 100;

function fn(): number | undefined {
    switch (typeof value) {
        case 'number':
            const v = typeof value;
            return v;
        default: 
            return 
    }
}
```

### 🙁 Actual behavior

the type of 'v' is not number

### 🙂 Expected behavior
the typeof of 'v' is number

**Comment by Josh-Cena** [comment]
The operator `typeof` has two meanings. When it's used in the context of a type, it is a TS syntax that gets the type of a value; when it's used in the context of a value, it is a JS syntax, which always returns a string. You can check the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) and the [handbook](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html#handbook-content)

**Comment by Messiahhh** [comment]
> The operator `typeof` has two meanings. When it's used in the context of a type, it is a TS syntax that gets the type of a value; when it's used in the context of a value, it is a JS syntax, which always returns a string. You can check the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) and the [handbook](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html#handbook-content)

I already know about this, but typeof of value in 'case "number"' statement is number, while typeof value doesn't return number

**Comment by Messiahhh** [comment]
> The operator `typeof` has two meanings. When it's used in the context of a type, it is a TS syntax that gets the type of a value; when it's used in the context of a value, it is a JS syntax, which always returns a string. You can check the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) and the [handbook](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html#handbook-content)

![image](https://user-images.githubusercontent.com/22492458/160598939-ee8f0d70-f0fc-4a2d-ac27-38739e8223ea.png)
![image](https://user-images.githubusercontent.com/22492458/160598968-e7fcfd63-cfa7-4bf9-9b42-d077720ba3bb.png)

**Comment by Josh-Cena** [comment]
```ts
const a: typeof v = 1;
      // ^ `typeof` is used in type-space: it is a TS syntax,
      // will be erased when you compile to JS.
      // This will make `a` have the type `number`.
const a = typeof v;
       // ^ `typeof` is used in value-space: it is a JS syntax.
       // This will make `a` have the value `"number"`, which is a string.
```

**Comment by Messiahhh** [comment]
> > The operator `typeof` has two meanings. When it's used in the context of a type, it is a TS syntax that gets the type of a value; when it's used in the context of a value, it is a JS syntax, which always returns a string. You can check the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) and the [handbook](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html#handbook-content)
> 
> ![image](https://user-images.githubusercontent.com/22492458/160598939-ee8f0d70-f0fc-4a2d-ac27-38739e8223ea.png) ![image](https://user-images.githubusercontent.com/22492458/160598968-e7fcfd63-cfa7-4bf9-9b42-d077720ba3bb.png)

@Josh-Cena  my example code is not exactly correct, but look at this picture, the type of v

**Comment by whzx5byb** [comment]
@Messiahhh It seems that you are confused when `value` is `number` but `typeof value` is `"string" | "number" | etc...`, right? The behavior is discussed in https://github.com/microsoft/TypeScript/issues/46399.
