### ISSUE TITLE
Nullish coalescing assignment operator doesn't work correctly with logical operators

### ISSUE THREAD

**Issue by m93a** [microsoft/TypeScript#48473]
# Bug Report

Using the nullish coalescing assignment operator `??=` on a logical statement which contains a logical operator (`&&` or `||`) fails to narrow the type, even though using the nullish coalescing operator `??` works correctly.

```typescript
declare function acceptBoolean (s: boolean): void
declare let x: boolean | null, y: boolean | null;

x = x ?? (4 < 3 && 3 < 4);
acceptBoolean(x); // narrowed correctly

y ??= 4 < 3 && 3 < 4;
acceptBoolean(y); // error
```
[Playground.](https://www.typescriptlang.org/play?#code/FAEwpgxgNghgTmABAMwK4DsIBcCWB7dRGCCMABywCE88owZ0AKAZwC5EAjGuhgSnYBueHCGChIsBIjpZEAD3Zda9QgB9E6VFCgAaRAE9F3FYnWbtAbjFzEAXnmIA-I8SMALIgA8iAMyIAZP6+XohuvFbEpBTUygyMcuFi+k6O9h7efoHB3m4RJORUxnH6iUA)

 - TypeScript version 4.6.2

Probably related to: #40359, #40494, #44988 #42203

**Comment by RyanCavanaugh** [comment]
This looks identical to #40359 actually
