### ISSUE TITLE
Numeric index type treated as string

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#48478]
# Bug Report
### 🔎 Search Terms

numeric index for in "Argument of type 'string' is not assignable to parameter of type 'number'" 2345

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about index signatures

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJgQygUwgLhgbwNoEsxzIAeGYArgLYBGyATgLoYAiSyAvjALxZsDcAUKEixgAG2QIwAQVGiuMAGZkwwKLnAAKAJRZ+ASAUhaG8bEQoAkkxj54rCDsz69AehcA5YrFH5kMABYIEDCSMHS0RmjOblK0AOaUyGCwIAowUACeAA5+AOTQtPhxuTbBYCCwQRC4cWAIVOLpIDBZCLQIFMgotDCp6dl55NR0uQB0UBAaAEwAzAAsAKxazmISYCwoGubIVgA0MGDIAO4wG8jaWgJ6bPw3QtAwq5Jn8koqaprbVqSUNLT7UH8tFQ-hAojgzFYjn0uAUW3s2C+THoowAbghRGRkAB5OE6AA86SBILBcDRGKxuIuuj0ekIpj82wgiNYVnoVxubCAA)

### 💻 Code

```ts
const dates: {[index: number]: Date} = {};
const cleanAll = function() {
	for(let dateID in dates) {
		//Next line has an error:
		//Argument of type 'string' is not assignable to parameter of type 'number'.ts(2345)
		cleanDate(dateID, new Date());
	}
}
const cleanDate = function(dateID: number, threshold: Date) {
	if(dates[dateID].valueOf() < threshold.valueOf()) {
		delete dates[dateID];
	}
}
```

### 🙁 Actual behavior
For...in on an object indexed with a **number** type is treated as if the object was actually indexed with a **string** type.

### 🙂 Expected behavior
The dateID parameter, in its first appearance is narrowed to `number` rather than `string`, because the object whose properties/keys are being iterated over is indexed with a `number` type rather than a `string` type.

Note that this can't be manually annotated because doing so would produce an error:
>The left-hand side of a 'for...in' statement cannot use a type annotation.ts(2404)

Also note that the dateID values might not be consecutive integers, so a traditional counter would not be appropriate.

**Comment by fatcerberus** [comment]
This is actually correct.  `dateID` is in fact a string at runtime.

**Comment by MartinJohns** [comment]
And objects are not sealed. It's possible that there are non-number properties defined in your object.

**Comment by wbt** [comment]
@MartinJohns wouldn't that make the type-checker raise an issue in the type given for `dates` above?

**Comment by wbt** [comment]
@MartinJohns I see that works.  My mistaken understanding was based on having repeatedly gotten errors trying to add properties to a type where the index was specified and the property was not consistent with it.  For a numeric-index example: 
```ts
interface MyObj {
    [index: number]: Date;
    0: string; //Property '0' of type 'string' is not assignable to 'number' index type 'Date'.ts(2411)
}
```
or more commonly:
```ts
interface MyObjectSet {
    [index: string]: MyOtherObject; //the general index follows a pattern that the names below don't match
    propertyOfWholeSet: number; //Error: not assignable to 'string' index type 'Date'.ts(2411)
    otherPropertyOfWholeSet: string; //Error: not assignable to 'string' index type 'Date'.ts(2411)
}
```
This leads to having to rewrite a nontrivial amount of working-fine JavaScript code as part of the conversion to TypeScript, making the costs of doing so much less predictable and way higher than just adding type annotations and fixing any typing-related bugs that may exist.  It's also confusing by producing an (incorrect) lesson that all non-index specified properties must be consistent with the index specification. 

(I also think JavaScript's behavior of automatically converting numeric indicies to strings for the `for...in` iteration is confusing, but that's not an issue in TypeScript.)

**Comment by fatcerberus** [comment]
TypeScript enforces that named properties be consistent with any index signatures because, if, e.g. the index signature is `string` and you index the object with an arbitrary unknown string, the compiler can’t guarantee it doesn’t clash with one of the named properties; forcing the named properties to be compatible avoids any unsoundness that would otherwise result from that.

**Comment by RyanCavanaugh** [comment]
You can always write this to achieve "mixed" objects:
```ts
type MyObjectSet = {
    [index: string]: MyOtherObject;
} & {
    propertyOfWholeSet: number; // OK
    otherPropertyOfWholeSet: string; // OK
}
```
Any weirdness that follows from this is, of course, on you.

**Comment by MartinJohns** [comment]
Having types with an index signature and known properties is always subject to unsoundness, that's why I personally avoid them.

```typescript
interface MyObjectSet {
    [index: string]: number | string;
    a: number;
    b: string;
}

const key = "a" as string

const myObj: MyObjectSet = { a: 1, b: "" }
myObj[key] = "";

myObj.a // typed number, actually string
```
