### ISSUE TITLE
Type compatibility in nested interfaces

### ISSUE THREAD

**Issue by gooverdian** [microsoft/TypeScript#48472]
# Bug Report

### 🔎 Search Terms

type compatibility
compatibility nested

sry, not many ways I can rephrase that, cos English is not my native language

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220302#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecBiAwnAL5wBmUEIcA5FKhrQNwCwAUB8AHYxJTl0SOAEkAKlAA2uDnDlwA2gA8AXNwCuIAEb8AuirgBnGFB4BzNuxIcuvfoLTCRAZWrCcs+RG5IDx09wWnnImKNyGkigwwN6GBh7s8klw6DDqKJLxwclJymqaOlD6Ribmljly1onyVVUcaLHwMM1wALxwABQoKuJSAJRtAHy4cM0wAExdA3XsDeFNzeNtnd0ubgOtw3hjU6Q2s41whAAWwJIAJgZEADw4JpJxohKSJMPtHXdShiQbwx3Z13OwAAboNPg8FABGXQkcGGAB0qXSkihMOuAHogaCOH19nNjHAAAooBi8K6EW6GNwGNYgJCvZYfKl0n5DToAk5nc6jL6tHDMpDw0LhSLRWJkdGDHFAA)

### 💻 Code

```ts
import React, { FC } from 'react';

interface ITrl {
    [x:number]: string;
}

interface ISome {
    one: string;
    translations: {
        actual: {
            [x:number]: string;
        }
    }
}

const ttt = (a:ITrl) => { ttt2(a) }

const ttt2 = (a:ISome) => { ttt(a) }

const Child: FC<{trls: ITrl}> = ({ trls }) => (
    <div>{trls[1]}{trls.actual[1]}</div>
)

const Parent: FC<{some: ISome}> = ({ some }) => (
    <Child trls={some.translations} />
)
```

### 🙁 Actual behavior

We can pass `some.translations` to `Child` despite it having not compatible type.

### 🙂 Expected behavior

Error about types incompatibility

**Comment by MartinJohns** [comment]
But the types are compatible. Your type `ITrl` says all `number` properties must be `string`, and that's the case. Additional properties are allowed in TypeScript.

You probably want #12936.

**Comment by brianconnoly** [comment]
> But the types are compatible. Your type `ITrl` says all `number` properties must be `string`, and that's the case (because `ISome["translations"]` has no `number` properties). Additional properties are allowed in TypeScript.
> 
> You probably want #12936.

But why then direct using of such types causes an error?

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIBUoBtkG8CwAUMicgNoAeAXCAK4C2ARtALpXIDOYUoA5gNxEAvkSKhIsRCgzYATHiKlOAe3oQwACz7sCxJaUo0GzKG07c+gvSRHXkyzdB2L9JQ3Sat2XHiAEubYVFCBGUQLmQwKOQAXmQACjgqGSwASliAPjxIqNlE9NsiUPCwHLB5OMTkzCxZdJis3DL85FsgA

**Comment by brianconnoly** [comment]
> 



> Numeric index signatures are a constraint on what types numerically-named keys can have, not a constraint on whether or not non-numeric properties can exist in a type.

@RyanCavanaugh 
Can you please describe why there is error in my example?
It does same thing but interface described directly — nesting is the only difference
