### ISSUE TITLE
Declarations emit internal functions when used in export definitions

### ISSUE THREAD

**Issue by RDIL** [microsoft/TypeScript#48488]
# Bug Report

### 🔎 Search Terms

generation, declarations, emit, export

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (dating back to 4.2, didn't try any older though), including nightly, and I reviewed the FAQ for entries about common issues

### ⏯ Playground Link

[Bug workbench link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?stripInternal=true#code/PTAEAEGcBcCcEsAOBJAdtAprVBDANgFAgQAmGAxnjrDtPAPaoBcocArhkWFABb0DuAUQC28aFwiQ+Q0dEwkAYvDwYW8VGQAeAOhLbokAhOg8MoAGb08eAeoDmFtqnJ1GoeJHfosuPKBwaoFL0bHgkqADk0KAARmYYmoj0sPJeoGSU1LQMqBbKGJAAhEbAAFSlBKClEOqY2PiVpcAE5k4uOaB2sBgY0AAUuMKqQXD2AJSgAN6VoLPd0GzYoAAGABLwoAAkk4MYAL6FywR7JWD88YnJ0WKgpt0WyVW1Pvig5IyQbMKIrqgVCUkUlNOt1eqATkA)

### 💻 Code

```ts repro
// @stripInternal
// @declaration: true
// @showEmit
// @showEmittedFile: index.d.ts

// the following function is internal and shouldn't be exported in declaration files!

/**
 * @internal
 */
function greet(name: string) {
    return `Hi ${name}!`
}

// we export it here for *internal consumption*
export { greet }

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?stripInternal=true#code/PTAEAEGcBcCcEsAOBJAdtAprVBDANgFAgQAmGAxnjrDtPAPaoBcocArhkWFABb0DuAUQC28aFwiQ+Q0dEwkAYvDwYW8VGQAeAOhLbokAhOg8MoAGb08eAeoDmFtqnJ1GoeJHfosuPKBwaoFL0bHgkqADk0KAARmYYmoj0sPJeoGSU1LQMqBbKGJAAhEbAAFSlBKClEOqY2PiVpcAE5k4uOaB2sBgY0AAUuMKqQXD2AJSgAN6VoLPd0GzYoAAGABLwoAAkk4MYAL6FywR7JWD88YnJ0WKgpt0WyVW1Pvig5IyQbMKIrqgVCUkUlNOt1eqATkA)

### 🙁 Actual behavior

The compiler emits `export { greet }`, when it should not do so.

### 🙂 Expected behavior

The compiler should export an empty object, since greet is internal.

**Comment by RyanCavanaugh** [comment]
This is not a supported use case. Please see the documentation - https://www.typescriptlang.org/tsconfig#stripInternal
