### ISSUE TITLE
Error Target requires N element(s) but source may have fewer

### ISSUE THREAD

**Issue by GTOsss** [microsoft/TypeScript#48485]
# Bug Report

### 💻 Code

Here is ok:
```ts
type A = [...any[], boolean];
type B = [string, string, boolean];

let a: A = ['test', false];
let b: B = ['test', 'test', false];
a = b; // no errors
b = a; // error, it's ok
```

But why is error here?
```ts
type M = (...params: [...any[], boolean]) => void;

const m: M = (a: string, b: string, cn: boolean) => {} // error? why? 
```

### 🙁 Actual behavior

 Error: Target requires 3 element(s) but source may have fewer.

### 🙂 Expected behavior

No errors.

### Example
[Example here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAslC8UAUA6NYCGAnDBbAzgFxQDaaKGAdiCQLoA0UARgPYsA2EVtAlAgHxQAbiwCWAEwDcAWABQcgMYtK+YFFzE4iJBmKqsoygHNGTPcAPHGCysVYculPvEEBvAL5y5oSFACCCKTkVDQMzGyc3DKyPtAAQoEk+oYmUMlW4Q5RXrKcarr+iQDkwBCqRYwAZhjs+BC00XnMxAmIJCVlwBVQHeVVNXUNchiBTNFAA)

**Comment by MartinJohns** [comment]
Your method `M` may be invoked with only one argument, but the method you try to assign there requires at least three arguments.

**Comment by GTOsss** [comment]
@MartinJohns In this case, how can I describe that the function accepts as many arguments of any type as necessary, but in the end it must be boolean.

**Comment by fatcerberus** [comment]
Yeah, even if you could describe such a type ("any function, as long as the last argument is boolean"), you wouldn't be able to call it since the compiler wouldn't know how many arguments it actually requires.

**Comment by MartinJohns** [comment]
You can't, simple as that. TypeScript is right here and protects you. **None** of these functions fulfills the requirement "accepts as many arguments of any type and lastly a boolean". The first function accepts one argument before the boolean, not any amount. The second accepts two arguments before the boolean, not any amount.

What you're trying to do is simply not type-safe.

**Comment by fatcerberus** [comment]
@MartinJohns I meant in the case that you could actually represent the type “any function with any number of required parameters”, you wouldn’t be able to safely call it.

**Comment by Helveg** [comment]
I would like to indeed accept "any function with any number of required parameters" but still apply some constraints, and set default argument types, to perhaps influence IDE autocompletion.

The use case is dependency injection systems where via inspection functions with any number of required parameters will indeed safely be called:

```
func(@Inject(A) a: A)
func(@Inject(A) a: A, @Inject(B) b: B)
```

Under normal circumstances I expect a certain signature, but any signature is allowed so I tried something like:

```ts
interface InjectedInterface {
  func<
    T extends [...any] = [a: A],
    R extends Record<string, any> = {hello: string, world: string>
  >(...args: T): Promise<{ data: T, meta: R }>
}
```

There's 2 goals here:

* Suggest a default type but allow any number
* Put constraints on the return type based on input type

I would expect that `extends [...any]` would let the compiler infer tuple types for the spread arguments of any number?
