### ISSUE TITLE
TypeScript error when importing TypeScript

### ISSUE THREAD

**Issue by bbrk24** [microsoft/TypeScript#48504]
# Bug Report

### 🔎 Search Terms

LanguageServiceHost useCaseSensitiveFileNames

### 🕗 Version & Regression Information

- This changed between versions 4.7.0-dev.20220311 and 4.7.0-dev.20220312

### ⏯ Playground Link

N/A, requires import statement which isn't possible in the playground

### 💻 Code

```ts
import * as ts from 'typescript';
```
Yep, that's it.

### 🙁 Actual behavior

The following error is generated:

```
node_modules/typescript/lib/typescript.d.ts:5716:15 - error TS2430: Interface 'LanguageServiceHost' incorrectly extends interface 'MinimalResolutionCacheHost'.  Types of property 'useCaseSensitiveFileNames' are incompatible.
    Type '(() => boolean) | undefined' is not assignable to type 'boolean | (() => boolean)'.
      Type 'undefined' is not assignable to type 'boolean | (() => boolean)'.

5716     interface LanguageServiceHost extends GetEffectiveTypeRootsHost, MinimalResolutionCacheHost {
                   ~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/typescript/lib/typescript.d.ts:5716
```

### 🙂 Expected behavior

TypeScript should compile without errors.

**Comment by bbrk24** [comment]
It seems the problematic inheritance was added in commit d1fa945261a30616c5e3557d1a9fc18f3482af30.

**Comment by weswigham** [comment]
OK, I understand why our CI and builds don't catch this - this error only appears with `exactOptionalPropertyTypes` set. @RyanCavanaugh are we, uh, supposed to have our API be safe under this flag? We don't build with it ourselves...

**Comment by RyanCavanaugh** [comment]
We should probably try to turn it on 😶
