### ISSUE TITLE
Type guard from Function | RegExp to Function fails

### ISSUE THREAD

**Issue by dsherret** [Microsoft/TypeScript#4850]
Is this a bug?

```typescript
var a: Function | RegExp;

if (typeof a === "function") {
    a(100); // compile error, still a Function | RegExp
}
```

...since the typeof a RegExp will be an object and `RegExp` is a type that lacks a call signature.

It works fine when a user-defined type guard is used, which seems inconsistent:

```typescript
function isFunction(obj: any) : obj is Function {
    return typeof obj === "function";
}

var a: Function | RegExp;

if (isFunction(a)) {
    a(10); // no compile error
}
```

Version: TypeScript 1.6
Discovered [here](http://stackoverflow.com/questions/32643409/breaking-change-regarding-type-guards-and-union-type-since-ts1-6).

**Comment by danquirk** [comment]
Today the === pattern for type guards only supports the literal types. The supported pattern for type guarding function types is to use ```instanceof```. So this does work:
```ts
var a: Function | RegExp;

if (a instanceof Function) {
    a(100); // ok
}
```
This is usually the general recommendation for doing actual type tests on functions in JavaScript anyway.

**Comment by RyanCavanaugh** [comment]
Logged #4868
