### ISSUE TITLE
Allow arithmetic operations on objects that have `valueOf()` method

### ISSUE THREAD

**Issue by dawidgarus** [microsoft/TypeScript#48503]
# Suggestion

## 🔍 Search Terms

valueOf

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow arithmetic operations on objects that have `valueOf()` method which returns type compatible with arithmetic operations

## 📃 Motivating Example

```
class NumberWrapper {
    constructor(private val: number) {}
    valueOf(): number {
        return this.val;
    }
}

const a = new NumberWrapper(4);
const b = new NumberWrapper(5);
console.log(a - b);
```
Currently this produces errors:
```
    The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
    The right-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
```
But this works perfectly fine with vanilla JavaScript

## 💻 Use Cases

Creating wrappers for primitive types that could be used as a target for `Proxy`

**Comment by RyanCavanaugh** [comment]
Duplicate #2361
