### ISSUE TITLE
1.65.0 Consuming a lot of CPU...code navigation is slow

### ISSUE THREAD

**Issue by skhilliard** [microsoft/TypeScript#48517]
Issue Type: <b>Bug</b>

After updating to the latest release of VS Code (1.65.0), it has starting consuming a lot more CPU and memory....code navigation is unusable.  Any insights as to why this is happening?

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (18.62GB free)|
|Process Argv|--crash-reporter-id a33ec631-4700-4009-b1a5-ec7d22d15b65|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
nugetpackagemanagergui|ali|1.1.9
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|12.0.1
prettier-vscode|esb|9.3.0
gitkraken-authentication|git|1.0.3
vscode-nuget-package-manager|jmr|1.1.6
vscode-azurefunctions|ms-|1.6.0
vscode-azureresourcegroups|ms-|0.4.0
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.20.0
csharp|ms-|1.24.1
remote-containers|ms-|0.224.2
remote-wsl|ms-|0.64.2
azure-account|ms-|0.10.0
azurecli|ms-|0.5.0
powershell|ms-|2021.12.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.13.0
language-stylus|sys|1.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmt:30438805
vscgsvid1:30447480
helix:30440343

```

</details>

**Comment by andrewbranch** [comment]
@skhilliard sorry for the delay. From your log I can see you have a dependency (direct or indirect) on mongoose, which has gotten a lot of complaints about the performance of their typings:

- https://github.com/Automattic/mongoose/issues/10349
- https://github.com/microsoft/TypeScript/issues/45249

The recent comments match the timing of when you noticed a slowdown:

> VSCode February 2022 (TS >4.6) has terrible performance, where as VSCode January 2022 (TS <4.6) shows no regression.

You could follow the instructions on [generating a performance trace](https://github.com/microsoft/TypeScript/wiki/Performance-Tracing) and send us that if you’re interested, but I suspect it will show a lot of time being taken up on mongoose.

I’m interested in seeing if the new variance annotations being introduced in TypeScript 4.7 would help mongoose typings—I’ll plan to investigate a bit during the next release.

**Comment by JustFly1984** [comment]
this could be related to incomplete tsconfig setup, or eslintrc. You need to add node_modules, and build artifacts into exclude sections of tsconfig, and eslintrc files. This way it will stop looking there, hence reduce the load on CPU.

**Comment by skhilliard** [comment]
> this could be related to incomplete tsconfig setup, or eslintrc. You need to add node_modules, and build artifacts into exclude sections of tsconfig, and eslintrc files. This way it will stop looking there, hence reduce the load on CPU.

Thanks for the suggestion, but I don't think that is the case.  Here are the contents of my tsconfi.json file:

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "removeComments": true,
    "noImplicitAny": false,
    "skipLibCheck": true,
    "allowUnusedLabels": false,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "typeRoots": [
      "./node_modules/@types/"
    ]
  },
  "include": [
    "**/*.ts",
    "**/*.js"
  ],
  "exclude": [
    "app",
    "node_modules",
    "**/*.spec.ts",
    "smarttest",
    "fhirtest",  
    "build"
  ]
}

```

**Comment by andrewbranch** [comment]
The mongoose maintainers have identified some recent regressions and have a proposed fix up; see https://github.com/Automattic/mongoose/pull/12284. I don’t think there’s anything specific to do on our side so I’m going to go ahead and close this out.
