### ISSUE TITLE
Add an option to issue warnings when using globals

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/TypeScript#4851]
I'm not sure whether it's possible but can we have a flag that will instruct the compiler to warn us whenever we use global variables?

Yesterday I wrote a tiny class that basically abstracts the 'jake.createExec' function and so instead of typing 'this.process' I typed 'process' which is pointing to a global object and is defined inside NodeJS, I didn't know why the events didn't fire, I've spent like 15min to realize it.

*p.s. pity that we need to use 'this' everywhere!*

To give some context here is the class.
```
import {Event, IEvent} from "./events"

export class Process {
	private process: jake.Exec
	
	constructor(command: string) {
		this.process = jake.createExec(command, {windowsVerbatimArguments: true})

		let data = ""

		this.process.on("cmdStart", () => {
			console.log("> " + command)
		});

		this.process.on("stdout", (chunk: string) => {
			data += chunk
			console.log(chunk.toString().trim())
		});

		this.process.on("error", (msg: string, status: number) => {
			if (this.onError.count > 0) {
				this.onError(this, {msg, status})
			} else {
				fail(`Process exited with code '${status}'.`)
			}
		})

		this.process.on("cmdEnd", () => {
			this.onCompleted(this, data)
		})
	}
	
	public onError: IEvent = Event.create()
	public onCompleted: IEvent = Event.create()
	
	public run() {
		this.process.run()
	}
}
```

**Comment by drake7707** [comment]
Wouldn't this be better to add this in the tslint linter instead of the compiler (https://github.com/palantir/tslint)?

**Comment by eyalsk** [comment]
@drake7707 sure, it's possible but why do you think it's better there than implementing this in the compiler? 

I kinda agree and think you're right to some extent if it's just about warnings then maybe it's better there, however, some people don't even use tslint.

I asked for issuing warnings but maybe the compiler guys can be more creative and go farther with it like having this feature where tools can differentiate between non-global variables and global variables and then tools like IDEs might be able to color them differently and whatnot.

**Comment by kitsonk** [comment]
> sure, it's possible but why do you think it's better there than implementing this in the compiler?

How do you determine if accessing `process` was what the developer actually meant?  What is one person's mistake is another's intent.

**Comment by eyalsk** [comment]
@kitsonk I don't but then again that's why I asked for an option and for this option to issue a warning and not an error.

**Comment by danquirk** [comment]
This should only really happen if your global and your local happen to have the same type right? It seems like a fairly rare occurrence really better suited to a linter.

**Comment by RyanCavanaugh** [comment]
I don't see any non-pathological program not using a global somewhere. `RegExp`, `Date`, `window`, `console`, etc, are all globals that are a) needed in many cases and b) have no other means of access.

**Comment by eyalsk** [comment]
@RyanCavanaugh yeah, I guess you're right. :)
