### ISSUE TITLE
Suggest parameter names when writing callback

### ISSUE THREAD

**Issue by alexdima** [microsoft/TypeScript#48514]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.6.3

**Search Terms**
- function / arrow
-  IntelliSense
- Suggest / Suggestion
- completion

---

```ts
class A {}
class B {}
class C {}

function withTestCodeEditor(text: string, options: { something?: true }, callback: (editor: A, viewModel: B, instantiationService: C) => void): void {
	callback(null, null, null);
}

function caller() {
	withTestCodeEditor('', {}, (editor, ) => {

	});
}
```

After the comma, I would expect TS to at least give textual suggestions for `viewModel` as a name.

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/5047891/161240691-ece37d10-854d-486f-9856-064ce13069f5.png">

**Comment by RyanCavanaugh** [comment]
Duplicate #18577 actually?

**Comment by alexdima** [comment]
Indeed, it's a dup. Thank you!
