### ISSUE TITLE
Restrained generic types and keyof type operator - mapped type is not concrete

### ISSUE THREAD

**Issue by eelilag** [microsoft/TypeScript#48510]
# Bug Report

### 🔎 Search Terms

Restrained generics 
keyof
mapped type

### 🕗 Version & Regression Information

We currently use Typescript 4.1.3 but same result with 4.6.2 on Playground

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAEASCmIAO8BOAeAqgPgFAG9dpjokBXAIxAEthowATB9ABWngA8AXeAOwZgBreAE8A9gDNoOABRJUYpAC5oLAJQqA6tQYBzeFywBtFgF08JaIUuXUBsql7Re8AO7RtegzLUBuIiQAvrjBuKCQMJ76hgDyeIQhuGHgUNAAIgAqMQQBxORUtPQqEFyo1Ly60AC80ABEYLX+lvk0dBQqvGQAthRo1dAAjP6h4akAsmDl6Jrs3HwC6VnxuaRlAG5gPNAAFogoqCoIyGjT2P0u7kf7Pv4rLYVdk7w+KmtiOivWNsTAYrwl0Fcui4-S422oEAAdLtjqhIYwGDJ6rU-CtLAB6dHQX7-EFArhaHTRaZGZHmFbBQJAA

### 💻 Code

```ts
class Helper<U>
{
    public add<P extends keyof U>(prop: P): Widget<U[P]>
    {
        return new Widget();
    }
}

class Widget<O> { }
class DTO
{
    public a: string = "a";
}

class Main<W extends DTO>
{
    private helper: Helper<W> = new Helper();
    public main(): void
    {
        const wgt = this.helper.add("a");
        // const wgt: Widget<W["a"]>
    }
}
```

### 🙁 Actual behavior

The generic type of "wgt" is `W["a"]`. 

### 🙂 Expected behavior

I would have expected `wgt` to be `Widget<string>` since a derived class can not change the type of a super attribute.

```ts
class A extends DTO
{
    public a: boolean;
    //Property 'a' in type 'A' is not assignable to the same property in base type 'DTO'.
    // Type 'boolean' is not assignable to type 'string'.(2416)
}
```

### Comment

Note that the same issue can be observed if we remove the `Widget` class : 
```ts
class Helper<U>
{
    public add<P extends keyof U>(prop: P): U[P] { ... }
}

class DTO
{
    public a: string = "a";
    public b: number = 1;
}

class Main<W extends DTO>
{
    private helper: Helper<W> = new Helper();

    public main(): void
    {
        const wgt = this.helper.add("a");
        // const wgt: W["a"]
    }
}
```

**Comment by MartinJohns** [comment]
> I would have expected `wgt` to be `Widget<string>` since a derived class can not change the type of a super attribute.

It can provide a more specific type:

```typescript
class A { a!: string }
class B extends A { a!: 'abc' }
```

**Comment by RyanCavanaugh** [comment]
What @MartinJohns said ⬆️
