### ISSUE TITLE
TypeScript Playground doesn't support most TypeScript 1.6 features

### ISSUE THREAD

**Issue by cyparu** [Microsoft/TypeScript#4853]
When using [TypeScript Playground](http://www.typescriptlang.org/Playground) with TypeScript 1.6 [features](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-16) various highlighting, completion & compilation issues are encountered (ES6 generators, ES7 experimental async/await)

**Comment by mhegazy** [comment]
ES6 generators and ES7 async/await are only available with `--target ES6`; the playground is hard wired to emit to ES5. we are working on making the playground more configurable to allow for better experimentation with the language, but this is not going to be available until the next release.

other features e.g. generic type aliases, class expressions, abstract classes, local types, intersection types, etc.. should all work though.

**Comment by cyparu** [comment]
10x for clarification. It will be good to have some small docs/hints at playground describing what's the TypeScript version running and what's available as features.

**Comment by danquirk** [comment]
Logged https://github.com/Microsoft/TypeScript/issues/4866 for that notification.
