### ISSUE TITLE
Typecheck with Interfaces

### ISSUE THREAD

**Issue by ragokan** [microsoft/TypeScript#48535]
# Suggestion

## 🔍 Search Terms

is, interface type, is not.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Being able to do type check just like `instanceof Class` for interfaces.

## 📃 Motivating Example

```ts
interface Person{
   name: string;
   age: number;

  // Validate here and return boolean
  *is(target) {
     return "name" in target && typeof target.name === "string" && "age" in target && typeof target.age === "number";
  }
}

// Use
const data = await http.get("url");

if (data is Person) {
  // data is typed as Person here
  person.name // string
}

// and maybe
if (data is not Person){
 // just like C# does, it can be a shortcut and a more declarative way of doing if(!(data is Person))
}
```

## 💻 Use Cases

I think it is a cool feature that many languages have, some of them do it in a different way such as using *classes*, but in Javascript/Typescript, we often use objects. With this approach, some libraries also can add a way to check their interfaces. 

It has a similar way in Typescript, too. Such as `const isPerson = (target: any): target is User => /* operation here */`, but using it in interface might be a more readable way, especially in if condition.

**Comment by MartinJohns** [comment]
> [x] This could be implemented without emitting different JS based on the types of the expressions

You want to emit different JS based on the type.

**Comment by ragokan** [comment]
> > [x] This could be implemented without emitting different JS based on the types of the expressions
> 
> You want to emit different JS based on the type.
> 
> Your suggestion would also be against the design goal 8:
> 
> > Avoid adding expression-level syntax.

I didn't know that, sadly. Okay, I am going to close this, thanks.
