### ISSUE TITLE
webworker: waitUntil should require a Promise

### ISSUE THREAD

**Issue by punkeel** [microsoft/TypeScript#48553]
# webworker lib Update Request

## Missing / Incorrect Definition

Today, `ExtendableEvent`'s `waitUntil` accepts `any`. A common mistake is to pass it a function, expecting the engine to call it. It doesn't, and will silently fail.

This is defined here:
https://github.com/microsoft/TypeScript/blob/cec2fda9a53620dc545a2c4d7b0156446ab145b4/lib/lib.webworker.d.ts#L1542

I would argue this needs to be typed as `Promise<any>` rather than `any`. This will catch two mistakes:
- Passing a function, expecting it will be called
- Passing a value, expecting it won't be called right away (eg: `waitUntil(longTask());`, with `longTask` a non-async function).

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil

> [Parameters](https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil#parameters)
> A [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

**Comment by jakebailey** [comment]
This was fixed in #49596.
