### ISSUE TITLE
Question on using Web Workers

### ISSUE THREAD

**Issue by Judahh** [Microsoft/TypeScript#4855]
Is there any example for using Threads/Web Workers in Typescript?
The intellisense of your web site shows that exists a Class Called Worker that receives a URL in the constructor, but i didn't find in the web how to use it properly or a Thread (the intellisense does not show any support for Thread).

**Comment by mhegazy** [comment]
Webworks need to be in their own compilation unit, they do not have access to the dom for instance. so they use their own library file. here is the file: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.webworker.d.ts

Include this file your webworker project (or just add a /// reference to it), and you should get webworker intellisense.

**Comment by Judahh** [comment]
Sorry maybe I wasn't clear enough. What I'm trying to say is Should I use it the same way as the classic JavaScript Web Worker or there is a more organised way using OO in TypeScript? an Example maybe?
Thanks for answer anyway! =D

**Comment by kitsonk** [comment]
Generally TypeScript doesn't provide the higher order structure on top of JavaScript, but provides you the tools to do such a thing in a type safe way.  The `.d.ts` linked to allows you to utilise WebWorkers in a type safe way, in the way they are structure within the environments that implement them.

If you are looking for examples and the like, it is usually better to ask the question on StackOverflow, but ultimately that is really the domain of something that might be built using TypeScript.
