### ISSUE TITLE
Support @deprecated in Visual Studio (2019/2022)

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#48567]
# Suggestion

Visual Studio Code has support for `@deprecated` since #390

This feature should be available with Visual Studio (Not VS code), too.

VS2019+2022:
![image](https://user-images.githubusercontent.com/2410353/161727736-f0eba135-6846-4cbe-953a-57545dcf021c.png)

vscode:
![image](https://user-images.githubusercontent.com/2410353/161727657-c98ab9d4-9732-44b3-a93c-d3b7f90e4ccc.png)

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by mdevdatta** [comment]
(Found this when I was helping a fellow developer who was wondering why Visual Studio doesn't tell them that a function they are calling is `@depracated`)

We (company of ~2300+ developers) follow internal coding guidelines to include helpful message with `@deprecated` tag to help the consumer to explain what they should do instead.

Visual Studio doesn't show any of this including that function is `@deprecated` - that makes us very very sad.

**Comment by icepower03** [comment]
same need.
very good idea

**Comment by HolgerJeromin** [comment]
ref #50285 for another feature parity issue.

**Comment by HolgerJeromin** [comment]
I have no idea when this was fixed, but my current VS 17.5.2 shows something 🎉

![image](https://user-images.githubusercontent.com/2410353/227160976-2fb440b0-ddb5-4b68-b6b2-c7e86fdb22ff.png)

Still nothing in VS2019, so I suspect this is a change in VS2022 and not TS.
