### ISSUE TITLE
Type inference on called function is too narrow 

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#48561]
# Bug Report

### 🔎 Search Terms

type inference parameter called function too narrow 2345

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about default parameters

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgDLAEZTlAngZQAcIFgZgEB5QsYAexAGcBJcaeJZAbwChl-k5KIzDVaDAFzIMdOgBsIcEAG5kAejXIAdDp4BfZTwQMRyOZmx4AYiFYAVfMgC8ggK4gE4kAAo+AqBAAjq7AAQAmAAo4cAC2UiJQoADmADR+-ITRMQDqwGAAFgASEHKEMK5yACIQ8BVgUiCuMRjQzsgADGkCggoAHpgKUdhxyAnJyAA+yI3NrS4A5PNdAnQ09CBwcpQYAFYkYMgA-FLoWDgExKTkVGsmrJCwiBBpAJTc6epqOlr6PBqsyAAUnAAG5wfAIRI0FKCeRyOgAd3GUAqKAKcAOYRqcDqjGQMVcphayAgvUI5lIYDkuGQhCgdBBwCxYT+ahgdCgyE2clpWTxcBgD0EoVMqy8m15wwgDyMJgO5jO1lsIEBjhc5Q8Xl83QCwVCEEiWWWGSyuQKxVK5Sq2LqbU6HxgfQGECGsTai2NyDF6022z2nja7ix5BABs9b143W6Gm0uj0sqYBwQ3OSVncnnWbQ1GYY3gjHwVllwNns+G8811IXC+DAiRASSWyAALAAmGEARgAbDCuEIRGJ1lJa64IHoXoZo2oAIJQJJNCDgL0wZBgXDEZDzGYtKDzZDAPEgOgHOCMRjAJIbDAKFd0SWxaWtOjL1fr+ZjevzLRgRjeFsAZibABWF4Pg0Gc5xiBcDifFc1xQeYuGFYRRFuEApBkeRFBUZA9F3fdpiPLlT3PS9rzAW9MilIUYJfeCgxqUADU-AsLHOEsVTLCsgirA0azrBsYVbDtu24PsUK8IcUVHcdfiAA)

### 💻 Code

Suppose a library written in JavaScript would, if written in TypeScript, be written as follows:

```ts
interface LibrarySpecificOptionsInterface {
    firstOption: boolean; // ...
};
const libraryFnInTS = function(
    requiredParam: string,
    paramWithHelpfulDefault: number = 0,
    flexibleParam: string | number = '',
    optionalObject ?: LibrarySpecificOptionsInterface,
) {
    //...
}
```
but since that library is in JavaScript rather than TypeScript, in the spirit of supporting progressive/incremental conversion, it might be written as follows:
```js
//This code follows the rule that defaults must be explicitly provided
//for all parameters after the first optional parameter.
const libraryFnInJS = function(
    requiredParam,
    paramWithHelpfulDefault = 0,
    flexibleParam = '',
    optionalObject = undefined,
    ) {
        // ...
}
```
Converting the code which calls this to Typescript fails, because the parameters are inferred too tightly.
```ts
const callingFunction = function() {
    libraryFnInTS('requiredString', 42, 16, {firstOption: true});
    //Argument of type 'number' is not assignable to parameter of type 'string'.ts(2345)
    //Argument of type '{ firstOption: boolean; }' is not assignable to parameter of type 'undefined'.ts(2345)
    libraryFnInJS('requiredString', 42, 16, {firstOption: true});
}
```
### 🙁 Actual behavior

Optional parameters are typed too narrowly to permit calls which provide parameters of a different type than the default.  This is especially an issue when the default is `undefined`. 

### 🙂 Expected behavior

Parameters of functions in JavaScript files are of type 'any' and the inclusion of a helpful or required default should make things easier, not harder.

### More details
Here, the first parameter is inferred as type 'any' and as #15114 [explains](https://github.com/microsoft/TypeScript/issues/15114#issuecomment-293133377), 
>Typescript never infers function arguments. So, unless you specify them, they are always going to be `any`.

The library's specification of a helpful default value for a parameter should make things better, but actually it makes things significantly worse.  This is especially true when the default value of a parameter is `undefined` because you can't pass anything into that parameter.

It appears that the primary response options are to (1) abandon the idea of converting the calling context to TypeScript, (2) add TypeScript typings for that whole library, which might be a LOT of work, or (3) use `ts-ignore` on the line preceding each call (which again, might be a lot).  A key problem with option 3 is that if types are eventually added to the library, and the parameter in the call is not a match, that **is** an issue that should be flagged in Typescript beginning upon the addition of types to the library.  (There is also option (4) of casting each parameter to `any` but that has all the downsides of (3) while being less obviously an issue workaround). 

Even if there is some reason to not implement inference of function parameters without explicit types in non-TypeScript files as `any` in all cases, at least making that a configurable option, likely on by default, would be a great help in incremental conversions.

**Comment by RyanCavanaugh** [comment]
For a huge majority of functions with a default, the inferred parameter type is what you would have written anyway. This is really no different from how TS disallows code like this
```ts
let a = 0;
a = "hello";
```
while allowing code like this
```ts
let a: string | number = 0;
a = "hello";
```

Defaults to `undefined` seem like a good case of not letting the tail wag the dog -- style guides should be there to improve your code, not make it unnecessarily verbose.

All of these proposed cures seem worse than the disease and this behavior is extremely longstanding in TS/JS; I don't see us changing this based on these scenarios.

**Comment by wbt** [comment]
In what situation is it useful to limit a parameter in a non-TS file to be of type 'undefined' so that it can never be called with a value?  That seems like quite a useless parameter.

At least a compiler option to allow treating all function parameters in JS files as 'any' type (with checkJS == false) would allow incremental conversion of one file at a time, instead of having to convert an entire codebase all at once.
