### ISSUE TITLE
Inheritance messes with comparison to primitive

### ISSUE THREAD

**Issue by CALICAWESOME** [microsoft/TypeScript#48565]
# Bug Report

Typescript version 4.6.2
VSCode version 1.65.0

### 🔎 Search Terms

https://github.com/Microsoft/Typescript/issues/202
https://github.com/microsoft/TypeScript/issues/25642

### 💻 Code
```
1 type Foo = String & { bar: 'baz' }
2
3 function qux(quux: Foo) {
4   const quuz = '';
5   quux === quuz;
6 }
7
8 qux('');
```

### 🙁 Actual behavior

Line 5:
`This condition will always return 'false' since the types 'string' and 'Foo' have no overlap.`

### 🙂 Expected behavior

No compiler error

**Comment by Josh-Cena** [comment]
`String` is a wrapper type of `string`, and in general `String` ≠ `string`, because `typeof new String("foo") === "object"` while `typeof "foo" === "string"`.

**Comment by CALICAWESOME** [comment]
Wow. Thanks for the quick response! That did it.
