### ISSUE TITLE
Optional Iterator parameter "incorrectly" accepts spread arguments

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48575]
```ts
declare const strs1: string[];
declare const strs2: IterableIterator<string>;

declare function badFoo(x?: Iterable<string>): void

// This function is BAD.
// The last two calls are INCORRECTLY accepted.

badFoo(strs1); // accepted - fine
badFoo(strs2); // accepted - fine

badFoo(...strs1); // accepted, BAD ❌
badFoo(...strs2); // accepted, BAD ❌
```

[Playground Link](https://www.typescriptlang.org/play?target=9&ts=4.6.2&msclkid=37df9526b20111ec982d296cc346cf35#code/CYUwxgNghgTiAEYD2A7AzgF3pmaCMAXNhjAJYoDmA2gLoDcAUKJLAsuljmgExECSGEDCgAjCCAFCoGJDAA8OchQB8jJuGhx4AMwCuKMBlKp4FJEmAAxc3gAUADwD8RRZVoBKIgDckpYAwYAekD4ABUAC1I0eCj4KFNzYHhUEAA6IJCAeRQIAE94DHCEbVJcLDAoCAgY6KgwMBAAB0FgdIYzC2skOy48dzp4YLj6ppb4AFodchB2xK6ekh5+wZC4ACtwMcmSlBnZzptbVOPe5aH1zZAk7en9q0Pj1K5uM9WQDcMriandgOZNYr6QzGFAJA5IbgOfiCYRiEAKEhKZSeeA+PwBIYRWKxSpoJBxMFJFLpIbZPIFIpTMoFADu+IqVRqwwazSubQ69whtlOAyGdRZWx+Mw5XUhz1ezNGXxuvzuoqOJ0WfV5bw+gp2wrm5khj3FKvgF0+1yFAXULC0egMRhMIignIczngklh4gRZEoyO8vn8GTCkWiluBJliACEAIIAERJIQiCGgmFp9MqEFqWj4ADkAMKZABKOYAopnQgAZACaktZrQCtvtPJWFfVtxrXW5ixe+v5UuNGurdpbuqVEs7lYANPBwxH4IAZcgYzfMCqebaHI1H48j04YQA)

**Comment by jakebailey** [comment]
@bschnurr thanks 😄

**Comment by DanielRosenwasser** [comment]
So from other discussions, this "works" because spreading a string produces another set of strings for each optional position. This is two slightly undesirable behaviors combined into one harder-to-explain one.

```ts
declare function optionals(x?: number, y?: number): void;
declare const nums: Iterable<number>;
optionals(...nums); // fine, but suspicious

declare function eatStrings(strs: Iterable<string>): void;
eatStrings("hello"); // almost never desirable to begin with?
```

**Comment by fatcerberus** [comment]
I was under the impression that spread calls weren’t even *allowed* unless 1. You’re spreading into a rest parameter or 2. The spread source is a tuple type matching the function’s parameter list.  When did that change?

**Comment by RyanCavanaugh** [comment]
I don't quite get what the defect is supposed to be? We also let you write the equivalent
```ts
badFoo(strs1[0]);
badFoo([...strs2][0]);
```

The behavior we actually work hard to exhibit here is that a spread is valid if all its possible arities result in valid calls, including the generally-allowed pattern of dynamic excess arity.

Strings being iterables of themselves means it's always going to be possible to be "off by one" in terms of the number of times you spreaded something. I don't know how we can detect that unless we somehow said that string iterations produced some special supertype of string that itself was not iterable by convention, but then we'd need some way to *undo* that despecialization once they combined with other chars.

**Comment by jakebailey** [comment]
This came from a bug in pyright/pylance that came down to a the spread hiding the fact that `...` shouldn't have been there for creating a set; I hadn't realized it had to do with the optional parameter; I agree that it's unfortunate but working as intended. One can write similar code with tuples/lists and `*args` in Python, for comparison, and get it wrong by adding a `*` in the wrong place.

**Comment by DanielRosenwasser** [comment]
Ultimately I think it's a case where `string`s being at all compatible with `Iterable<string>` is *extremely* suspicious unless it's made explicit with a type assertion. Seems a bit heavy-handed, but I can't think of the last time I needed to spread a string except for emoji examples.

**Comment by dkolman-vendavo** [comment]
Doesn't have to be Iterable, function with an optional parameter (of any type) incorrectly accepts spread arguments:

```
declare function required(a: number): void;
declare function optional(a?: number): void;

const nums = [1, 2, 3];

required(...nums); // error as expected 
optional(...nums); // accepted, BAD ❌
```

[Playground link](https://www.typescriptlang.org/play?ts=5.0.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzgEdks5gAKKALnlWQFsAjEGAShoDcctgBuAKFCRYCFOmx54OAA4TUUCJQD8NOkxbt4XHgP5g8AZwy0GB+AF54AbQCMAGngAmBwGYAurqIky5AHT+1A1ZeeAB6UPgWGBwYeCgzEAAPaXAMEGB4fhk5BT8A02CwiKgwMBBZdIcAIQBBABF4QBlyIA)
