### ISSUE TITLE
Require Syntax Problem

### ISSUE THREAD

**Issue by gravidThoughts** [Microsoft/TypeScript#4857]
Assuming foo.ts is located in the same directory.

```
import foo = require('foo');
import foo2 = require('./foo');

var bar = new foo.Bar();
var bar2 = new foo2.Bar();
```

The above builds fine, and intellisense work fine for both module imports.

`var bar = new foo.Bar();` causes a runtime exception that it cannot find a module.

Unless there is a use case I don't understand for `import foo = require('foo')`, this can be potentially confusing to a first time user. 

It happened to me. I started out just using just the module name, and because there was no issue with the build, I assumed it was the proper way to reference a module in the same directory.

Perhaps the compiler should fail to build?

**Comment by kitsonk** [comment]
The problem is that module resolution is fully determinable until run-time.  At run-time, both of those could have been valid and worked, depending on your run-time configuration, if you were using CommonJS, AMD or SystemJS and depending on how you emitted it and how you configured your loader.

So how does the compiler know how you are going to configure your run-time?

**Comment by gravidThoughts** [comment]
@kitsonk Thanks for the feedback. 

What module loader would see `'foo`' as valid? [All of the examples given here](http://www.typescriptlang.org/Handbook) use `'./foo'` to refer to a relative module. Based on the way those samples are written I assume they apply to both CommonJS and AMD.

**Comment by vladima** [comment]
Prior to TypeScript 1.6 compiler has used its own (Node\RequireJS hybrid) algorithm to resolve module names and indeed it treated non-relative module names as relative. In 1.6 we've updated [module resolution logic](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#adjustments-in-module-resolution-logic) so for CommonJS scenarios it mimics Node behavior. In 1.6 attempt to build code from your example yields an error
```
...>node built\local\tsc.js --m commonjs ..\test.ts
../test.ts(1,22): error TS2307: Cannot find module 'foo'.
```

if necessary you can always force the compiler to use old 'classic' algorithm by using `--moduleResolution classic` command line option
```
```
