### ISSUE TITLE
Object.values removes undefined from optional properties

### ISSUE THREAD

**Issue by WiseBird** [microsoft/TypeScript#48587]
# Bug Report

### 🔎 Search Terms

enum index signature values
object values infer optional

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.7.0-dev.20220406#code/KYOwrgtgBAou0G8CwAoK6oHsTCgXigHJthCAaVDKAFwHdN8i7NzUBfVVAY2wGdqooSAFkAhgAcAXFAQBtAJY4AHlEWx4AXQD80-gCdFAczaMEbANyohEMeNlxIAOhIbGYEABNgAM0XAPliio3ph6ABQ8IPxQAG6iADZguJjeUADyAEYAVsBc1I5xicC8Yda2AJTlMpQYkbyY8cCO8ZiGYYVJzaCG1AAW5YEcQcOo1ACe4rgAKhPAaeLU8tgJpjXoJDpQ+kZQAD5Q7l6+OAFrNPSb2yCGeweePn6nKEPcfALjk-PUttIznwtLEArAhmQIfOYLWzOHBue7HfyBYKhCJvWIJJJYVKZHJ5Aro4phcFfCpVZBoWp8BpNFptDrU7p9AbsTgjFDgqB-XAgs4kXTUAzXW6HB4nQJUZh8gU3fbC+FPF4oOrvWY-DmzUwmUS8KCiEBjMEqiTQrl3I6PREoELhJVooqY9LZXL5OklcEk6rk9B1KnNVrtfFda6MwYsllAA)

### 💻 Code

In the following code type of values returned by `Object.values` is correctly infered to `string | undefined`:

```ts
type Type = {
    one: string | undefined;
    two: string | undefined;
}

const typeMap: Type = {} as any;
typeMap.one = undefined;

for(const value of Object.values(typeMap)) {
    console.log(value.length); // Object is possibly 'undefined'
}
```

But if I add `?` to the properties, the type is now `string`
```ts
type TypeOptional = {
    one?: string | undefined;
    two?: string | undefined;
}

const typeOptMap: TypeOptional = {} as any;
typeOptMap.one = undefined;

for(const value of Object.values(typeOptMap)) {
    console.log(value.length); // no error here
}
```

Real-world example is about using enums for indexing an object:
```ts
enum Enum {
    one = 'one',
    two = 'two',
}

const enumMap: {[inex in Enum]?: string} = {};
enumMap[Enum.one] = undefined;

for(const value of Object.values(enumMap)) {
    console.log(value.length); // no error here as well
}
```

### 🙁 Actual behavior

Values from properties with `?` and `| undefined` are considered non-nullish. 

### 🙂 Expected behavior

Error in all the cases

**Comment by whzx5byb** [comment]
The option [exactOptionalPropertyTypes ](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) will produce your expect behavior.

**Comment by WiseBird** [comment]
True, but the error should be reported even if `exactOptionalPropertyTypes` is not set

**Comment by WiseBird** [comment]
@IllusionMH 
In case when `exactOptionalPropertyTypes` is off and TS can't differentiate between `key?: type` and `key?: type | undefined`, shouldn't it assume that values can be undefined?
In my example TS does it but partially:
```ts
type TypeOptional = {
    one?: string | undefined;
    two?: string | undefined;
}

const typeOptMap: TypeOptional = {};
typeOptMap.one = undefined; // Here it's fine to assign `undefined`

for(const value of Object.values(typeOptMap)) {
    console.log(value.length); // Here no error accessing the length as if value couldn't be undefined
}
```

**Comment by IllusionMH** [comment]
That's how it was implemented initially and changing that would break a lot of existing code.

But for cases like yours new flag was implemented so you can enable it and see expected errors.

What's the problem with flag? Just enable it ang get errors in your code base without breaking code of others.

**Comment by WiseBird** [comment]
@IllusionMH 
I don't have anything against the flag. I just feel that TS can be more restrictive here.
Consider this slightly changed example:

```ts
type TypeOptional = {
    one?: string | undefined;
    two?: string | undefined;
}

const typeOptMap: TypeOptional = {};
'one' in typeOptMap && console.log(typeOptMap.one.length); // Object is possibly 'undefined'.

for(const value of Object.values(typeOptMap)) {
    console.log(value.length); // no errors
}
```

TS knows that the value is nullable when you directly access it, but not when you get it from `Object.values`.
If changing this will break a lot of existing code then I guess better leave it as it is.

**Comment by eliasm307** [comment]
Is there any possibility of having this show a warning by default atleast?

I'm working in an existing codebase where enabling exactOptionalPropertyTypes would break a lot of things. I think there is room for improvement if the only options for this are to either:

- live with TS allowing potentially buggy code when iterating object property values 
- enable a feature that means we can't assign undefined to optional properties at all (which some people might not want) and potentially have to refractor code.

TS is meant to allow us to "Catch errors early in your editor" which it does excellently but in this case its surprising the only way to get any indication of an issue is to make a potentially major change with some refactoring cost. 

I haven't tried it but I guess enabling exactOptionalPropertyTypes and making the type of all optional properties unions with `undefined` could maintain existing behaviour with the flag on but not sure if it would show undefined when iterating over object values 🤔 I'll give it a go when I'm on a computer next, however if it does work it would make the types look a bit odd and some refactoring cost is still required.

Also @IllusionMH you mentioned "that's how it was implemented initially" however it seems this behaviour changed in v4.3, where it used to show undefined values when an object had optional properties, so is this not a regression?

**Comment by d07RiV** [comment]
Would it be possible to allow `x?: string | undefined` to work without the flag? As mentioned, the flag can break a lot of existing code, which is why it's not on by default, but there is no reason why someone would write `string | undefined` on optional types if they didn't want to specifically imply that the value can be present but optional.

**Comment by AlexErrant** [comment]
Workaround: use a utility fn that gives `Object.values` better types.

```ts
export const objValues: <TRecord extends Record<string, unknown>>(
  o: TRecord,
) => TRecord[keyof TRecord][] = Object.values;
```

Usage:

```ts
type PartialPerson = { name?: string}
let pp: PartialPerson = {}

let a = Object.values(pp).map(v => v) // v: string
let b =     objValues(pp).map(v => v) // v: string | undefined
```
