### ISSUE TITLE
Support function reload in class 

### ISSUE THREAD

**Issue by keyiis** [microsoft/TypeScript#48582]
If there are multiple methods with the same name but different parameters in a class, their comments are also different, which cannot be implemented in typescript at present.
**Example:**
```
import { EventEmitter } from 'events';
class ClassA extends EventEmitter{
    constructor(){
        super();
        this.emit("a","abc");
        this.emit("b","abc",123);
    }
    //I added two "on" method so that VSCODE can prompt comments and parameter types when using it.but typescript does not allow functions with the same name.
    /**
      *  comments about event "a"
      */
    on(eventName: "a", listener: (arg:string) => void){
         return super.on(eventName,listener);
    }

     /**
      *  comments about event "b"
      */
    on(eventName: "b", listener: (arg1:string,arg2:number) => void){
         return super.on(eventName,listener);
    }
}

let insA = new ClassA();
// I hope vscode can prompt comments and parameter types when using it
insA.on("a",(arg:any)=>{
       // "arg" type cannot be inferred
});

```

**Comment by fatcerberus** [comment]
TS does support overloads, but they have to share a single implementation:
https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads

What you wrote is not valid TS.

**Comment by fatcerberus** [comment]
It **does** meet your needs:
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUQG4FMB2NkmDGdKOAXzgDMoIQ4BydDbAZ1oG4AodgYwBsBDJkzgBhfoICCcdAA9CmACZC0WHHgJEE7ONrhcImJjCgBXLjGgAKAJSadduE2Ngi1jvZ0wAFsCYA6dGoWAER8QQA0IQBGXEFWbu5wXj7+gUGR4VExYQCMAEwAzHFaOiScdgD0AFSVxXaV2nogICpCfJEQxvAMKnAhQbU6leUD+hbd2AByfM0AXL2hYXA8PnJEcxZ8UADmM4ZQwJhbVnAAvAB8cKgQwPJWc0lMHANwVTXu9brUzcxwbR1djHgaX672GdlG4xgU1mvXSi2WhiwazgG222V2RgOWzCmy2uRmmGMIEiRGO50u11u928jzKOnK5USNLgPiZ6BZ4B4ARUfBgwH0cAg5Do+loi3wtCEmAg8FQPmAkS5iQguj4PC5UCYI0wY0B0PQcz6cAAPrDwksVkioOtcei9ljFrj8YTiaTThcrjc7kzWbYEnAoOgYMYoJgHE4iL4IXrpugwgjVlAinZSqV2Fz4AcmJITnBMOgAO4iMTZ1ycBlwTwQDDEatEEWYWjKhzodkAKQAygARCBcCjQKSAuDidhZ8RRnV9MKoo7nTQV-3aAB6AH52CQikA

**Comment by keyiis** [comment]
@fatcerberus Thank you very much for your help!
