### ISSUE TITLE
Index type not recognised as string when the value type has a generic function argument

### ISSUE THREAD

**Issue by mi-col** [microsoft/TypeScript#48590]
# Bug Report

### 🔎 Search Terms

generic
index signature

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about index signatures

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5gDyoHzIDeAUMsmAFzIAUlaAlMgLwEBuA9sACYDcxAvsWKhIsRCnRYMRUsgDaAawgBPKliigA5gF0qknAFcQCkOwDuIPAKFhlABxQBlMBpCb9zNJhzqtePrYOyAByBgC2AEbQHkxeWNgg4VFQ-kIi0PBIyACCAAq5yBAAHpAgXNL60iRkvm5Uzq7u3nxkiZHQVKHtUPp8gkA)

### 💻 Code

```ts
interface Test<T> {
  t: (t: T) => void;
}

interface Tests {
  [key: string]: Test<unknown>
}

type StringTest = Test<string>;

interface APP extends Tests {
  key: StringTest;
}
```

### 🙁 Actual behavior

Getting the error `Property 'key' of type 'StringTest' is not assignable to 'string' index type 'Test<unknown>'.`

If the generic T is moved from being an argument to being the return type, the error disappears.

### 🙂 Expected behavior

The error should not appear, as I don't believe whether a generic is used in the function argument or not should affect the indexing.

**Comment by whzx5byb** [comment]
This is a correct error. `Test<string>` is not assignable to `Test<unknown>` because type parameter `T` is used in a contravariant position `(t: T) => void`.

**Comment by mi-col** [comment]
> This is a correct error. `Test<string>` is not assignable to `Test<unknown>` because type parameter `T` is used in a contravariant position `(t: T) => void`.

If that is the case then why is replacing `t: (t: T) => void` with `t: T` or `t: () => T` negating the error?

**Comment by fatcerberus** [comment]
Just for good measure, in case the reason for the contravariance is not obvious: `Test<unknown>`, by type, is a function which can be called with any value.  You can’t substitute a function that only accepts strings.

**Comment by fatcerberus** [comment]
@mi-col Because by moving the type parameter to the return type, it becomes covariant. See my comment above.
