### ISSUE TITLE
Suggestion: allow partial applications

### ISSUE THREAD

**Issue by zpdDG4gta8XKpMCd** [microsoft/TypeScript#486]
This is going to be a tough one. Consider a poor-man partial application hack:

```
interface Partial { f: Function; args: any[]; }
interface Partial0<r> extends Partial { 'know r': r; }
interface Partial1<a, r> extends Partial0<r> { 'know a': a; }
function partial<b, a, r>(f: (one: b, two: a) => r, one: b) : Partial1<a, r>;
function partial<b, a, r>(f: (one: b, two: a) => r, one: b, two: a): Partial0<r>;
function partial(): any {
    return {
        f: arguments[0],
        args: Array.prototype.slice.call(arguments, 1)
    };
}
function call<r>(partial: Partial0<r>): r;
function call<a, r>(partial: Partial1<a, r>, two: a): r;
function call() : any {
    var f : any = arguments[0].f;
    var args : any[] = arguments[0].args;
    return f.apply(undefined, args.concat(Array.prototype.slice.call(arguments, 1)));
}

function add(x: number, y: number) { return x + y; }
var addTo10 = partial(add, 10);
alert(call(addTo10, 5));
```

It works although it's rather cumbersome and awkward. The motivation behind this example is that creating data objects is less expensive than creating closures. It would be really nice if TypeScript could emit this design pattern in response to the syntax like this:

```
function add(x: number, y: number) { return x + y; }
var addTo10 = add(10, ..);
alert(addTo10(5));
```

**Comment by NN---** [comment]
@danquirk ``While I'm a big fan of functional programming I'm not sure this feature is really valuable enough at the moment given the work required, especially considering how few existing JavaScript libraries will have been written in a way that you can usefully take advantage of currying.``

Partial application is not the same as currying.
Currying takes last parameter and makes a new function.
Partial application can be applied in any position.
Example:

```typescript
function f(a:number, b: number, c: number) { return a + b + c; }

function g(x: (q:number,w:number) => number) { return x(1,2) }

g((q,w) => f(q,w,3))
// Same with partial application
g(f(_, _, 3)) 

// But we can use partial in any place, this is not easily done with currying
g(f(_, 3, _)) 
g(f(3, _, _)) 
```

It is not a complex feature.
