### ISSUE TITLE
missing: transaction durability in indexeddb

### ISSUE THREAD

**Issue by jimmywarting** [microsoft/TypeScript#48601]
# Bug Report

### 🔎 Search Terms

transaction durability

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBATgUwI4wLwwJZgCYIB4LYAiAQgHQgAOCYAFAOQBmII9ANDAIwCUAsAFCIkZRBACuAGyhkocAIaQ5wKBnANmrDvURzs4CQE92MAN4CYMbGPkAjDBIxQDALhjaEEuQWz0BAX24gA)

### 💻 Code

```js
const req = indexedDB.open('foo', 1)
req.result.transaction('foo', 'readonly', {
  durability: 'relaxed'
})
```

### 🙁 Actual behavior

expected 2 arguments got 3

### 🙂 Expected behavior

not to throw any error

**Comment by jakebailey** [comment]
This was fixed in #49596.
