### ISSUE TITLE
tsc: --incremental does not provide compilation speed benefits when used with --outFile

### ISSUE THREAD

**Issue by ajaska** [microsoft/TypeScript#48604]
# Bug Report

### 🔎 Search Terms

`outDir`, `outFile`, `incremental`, `performance`, `compilation`, `tsc`, `amd`, `build times`

### 🕗 Version & Regression Information

I think we noticed this for the first time in 2020, and are still seeing this as of 4.6.2

This is the behavior in every version I tried, and I reviewed the entire FAQ, the docs for outDir, outFile, and incremental, and did a bunch of Github/StackOverflow searching.

This seems similar to https://github.com/microsoft/TypeScript/issues/33163, but even if we still have to pay the emit costs (20s), I'm hopeful that we could still reduce the check time (130s). It looks look there are [multiple tests](https://github.com/microsoft/TypeScript/blob/main/src/testRunner/unittests/tsbuild/outFile.ts) checking the behavior of outFile with incremental, so perhaps something that is intended to be supported?

### ⏯ Playground Link

N/A

### 💻 Code

I'd be happy to help produce a relevant code sample, but I'd like confirmation that this is a bug that 1) needs a code sample to reproduce and 2) is worth fixing, and isn't inherent to the implementation of outDir/outFile/incremental.

I'm also kind of hoping that one of you experts sees this and realizes it's a one-line change or something 😉 .

### 🙁 Actual behavior

We're seeing improvements on rebuild for outDir, but not outFile.

(Times with --extendedDiagnostics)

| Time | outDir/outFile | Initial/Rebuild |
| --- | --- | --- |
| 175s | outFile | initial |
| 175s | outFile | rebuild |
| 175s | outDir | initial |
| 20s | outDir | rebuild |

I also confirmed that the tsbuildinfo file was actually being generated and looked correct.

<details>
<summary>--extendedDiagnostics for: incremental, outFile, initial</summary>

```
Files:                         3354
Lines of Library:             25867
Lines of Definitions:        608106
Lines of TypeScript:         572245
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Nodes of Library:            114304
Nodes of Definitions:       2305341
Nodes of TypeScript:        1847120
Nodes of JavaScript:              0
Nodes of JSON:                    0
Nodes of Other:                   0
Identifiers:                1468436
Symbols:                    2132778
Types:                       691348
Instantiations:             5123088
Memory used:               2381703K
Assignability cache size:   1371397
Identity cache size:          39281
Subtype cache size:          153734
Strict subtype cache size:    42490
I/O Read time:                0.28s
Parse time:                   9.39s
ResolveModule time:           0.87s
ResolveTypeReference time:    0.00s
Program time:                13.63s
Bind time:                    5.01s
Check time:                 129.85s
transformTime time:           4.30s
Source Map time:              2.08s
commentTime time:             0.10s
I/O Write time:               0.43s
printTime time:              22.72s
Emit time:                   22.72s
Total time:                 171.21s
```
</details>

<details>
<summary>--extendedDiagnostics for: incremental, outFile, rebuild</summary>

```
Files:                         3354
Lines of Library:             25867
Lines of Definitions:        608106
Lines of TypeScript:         572245
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Nodes of Library:            114304
Nodes of Definitions:       2305341
Nodes of TypeScript:        1847120
Nodes of JavaScript:              0
Nodes of JSON:                    0
Nodes of Other:                   0
Identifiers:                1468436
Symbols:                    2132778
Types:                       691348
Instantiations:             5123088
Memory used:               2048903K
Assignability cache size:   1371397
Identity cache size:          39281
Subtype cache size:          153734
Strict subtype cache size:    42490
I/O Read time:                0.29s
Parse time:                   8.93s
ResolveModule time:           0.90s
ResolveTypeReference time:    0.00s
Program time:                13.48s
Bind time:                    4.90s
Check time:                 130.30s
printTime time:              22.56s
Emit time:                   22.62s
transformTime time:           3.69s
Source Map time:              2.00s
commentTime time:             0.10s
I/O Write time:               0.64s
Total time:                 171.31s
```
</details>

<details>
<summary>--extendedDiagnostics for: incremental, outDir, initial</summary>

```
Files:                         3354
Lines of Library:             25867
Lines of Definitions:        608106
Lines of TypeScript:         572245
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Nodes of Library:            114304
Nodes of Definitions:       2305341
Nodes of TypeScript:        1847120
Nodes of JavaScript:              0
Nodes of JSON:                    0
Nodes of Other:                   0
Identifiers:                1468436
Symbols:                    2132778
Types:                       691348
Instantiations:             5123088
Memory used:               2373831K
Assignability cache size:   1371397
Identity cache size:          39281
Subtype cache size:          153734
Strict subtype cache size:    42490
I/O Read time:                0.29s
Parse time:                   8.53s
ResolveModule time:           0.94s
ResolveTypeReference time:    0.00s
Program time:                12.90s
Bind time:                    5.53s
Check time:                 137.38s
transformTime time:           4.51s
Source Map time:              1.83s
commentTime time:             0.10s
I/O Write time:               0.52s
printTime time:              23.39s
Emit time:                   23.39s
Total time:                 179.20s
```
</details>

<details>
<summary>--extendedDiagnostics for: incremental, outDir, rebuild</summary>

```
Files:                         3354
Lines of Library:             25867
Lines of Definitions:        608106
Lines of TypeScript:         572245
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Nodes of Library:            114304
Nodes of Definitions:       2305341
Nodes of TypeScript:        1847120
Nodes of JavaScript:              0
Nodes of JSON:                    0
Nodes of Other:                   0
Identifiers:                1468436
Symbols:                     872859
Types:                           78
Instantiations:                   0
Memory used:               1125433K
Assignability cache size:         0
Identity cache size:              0
Subtype cache size:               0
Strict subtype cache size:        0
I/O Read time:                0.31s
Parse time:                   8.62s
ResolveModule time:           0.91s
ResolveTypeReference time:    0.00s
Program time:                13.04s
Bind time:                    4.81s
Total time:                  17.85s
```
</details>

<details>
<summary>tsc --showConfig</summary>

```
{
    "compilerOptions": {
        "baseUrl": "../../..",
        "forceConsistentCasingInFileNames": true,
        "noEmitOnError": false,
        "noFallthroughCasesInSwitch": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noResolve": false,
        "preserveConstEnums": true,
        "removeComments": true,
        "rootDir": "../../..",
        "stripInternal": true,
        "experimentalDecorators": true,
        "noUncheckedIndexedAccess": true,
        "target": "es6",
        "moduleResolution": "node",
        "strictNullChecks": false,
        "keyofStringsOnly": true,
        "lib": [
            "dom",
            "es5",
            "es2015.core",
            "es2015.collection",
            "es2015.iterable",
            "es2017.object",
            "es2018.promise"
        ],
        "importHelpers": false,
        "inlineSourceMap": true,
        "inlineSources": true,
        "module": "amd",
        "outDir": "./",
        "incremental": true,
        "noEmitHelpers": true,
        "skipLibCheck": true,
        "paths": {
            "*": [
                "*",
                "external/npm/node_modules/*",
                "external/npm/node_modules/@types/*"
            ]
        },
        "typeRoots": [
            "/home/user/external/npm/node_modules/@types"
        ],
        "extendedDiagnostics": true,
        "tsBuildInfoFile": "../../../../../../../../../../home/user/foo.tsbuildinfo",
        "outFile": "../../../../../../../../../../home/user/foo.js"
    },
    "files": [
       // each and every file specified here
     ]
}
```
</details>

### 🙂 Expected behavior

Faster type-checking comparable to how it works with outDir, ~20s rebuilds for small changes.

**Comment by sheetalkamat** [comment]
This is known behavior.. With --out we cannot calculate per file d.ts file which is used to determine set of files to refresh diagnostics for.. That is what results in this behavior.. Most of the time `--out` is written when not using modules so anyways its not going to help.. But with modules you probably can wire declaration emitter to do per file emit and get those benefits but I have never gotten around to working on that.

**Comment by ajaska** [comment]
Thanks for the quick reply!

I was wondering why we couldn't just compute it based off of the tsbuildinfo file, and I'll admit to having just looked at a non-outDir tsbuildinfo file for the first time a few minutes ago, it never occurred to me to do so. I understand now that it's much more minimal :D 

>Most of the time --out is written when not using modules

Useful to know, thanks! So -- potentially possible? But I imagine this would be lower priority for you if this is an uncommon use-case.

>But with modules you probably can wire declaration emitter to do per file emit and get those benefits

Do you have a sense of which files would need to be updated / how difficult it would be to take this on? I'm not very familiar with the TypeScript codebase.

Would this result in a more "complete" tsbuildinfo file that looks more like one produced with outDir?

**Comment by ajaska** [comment]
Hi, I believe this was mislabeled as a question. It is a Bug Report / Feature Request.

**Comment by ajaska** [comment]
Hi, could this be labeled as a Bug / Experience Enhancement and re-opened? I can also create a new issue.

I asked follow-up questions specifically about the implementation of a TypeScript compiler improvement to fix the bug. The question label is for "An issue which isn't directly actionable in code," but this is very much directly actionable in code. cc @RyanCavanaugh
