### ISSUE TITLE
4.6 crashes on project that compiles fine with 4.5 (at BinaryExpressionStateMachine.onEnter)

### ISSUE THREAD

**Issue by bjornbacklund** [microsoft/TypeScript#48608]
# Bug Report

I have a quite large TS project (www.3d-decks.com) that compiles fine under 4.5 but 4.6 crashes. See error details below.
 What can I do to track down this one?

Unknown output:                 throw e;
  Unknown output:                 ^
  Unknown output:     at BinaryExpressionStateMachine.onEnter (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:77139:21)
  Unknown output:     at Array.enter (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:29608:50)
  Unknown output:     at trampoline (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:29756:52)
  Unknown output:     at C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:77127:30
  Unknown output:     at checkExpressionWorker (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:78215:28)
  Unknown output:     at checkExpression (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:78089:38)
  Unknown output:     at checkExpressionCached (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:77753:38)
  Unknown output:     at C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:76312:32
  Unknown output:     at traverse (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:15189:28)
  Unknown output:     at visitNodes (C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.6\tsc.js:29816:30)

### 🔎 Search Terms

BinaryExpressionStateMachine.onEnter

### 🕗 Version & Regression Information

Problem started with 4.6. 

- This is a crash
- This changed between versions 4.5 and 4.6

**Comment by DanielRosenwasser** [comment]
I'm speculating, but it *looks* like you should be able to narrow this down by trying to remove more and more files from your compilation until the crash goes away. When you've narrowed down the file(s?) that trigger the crash, you can try removing more and more code from these files until you have something that's smaller than 20 lines of code.
