### ISSUE TITLE
Incorrect circularity detection Error 7022

### ISSUE THREAD

**Issue by zuozp8** [microsoft/TypeScript#48611]
### 🕗 Version & Regression Information

doesnt work from typescript 3.3 (oldest in playground) all the way to 4.7-nigtly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/MYewdgzgLgBA5gUygIQIZWACxgXhqiATzGBgAoJgAnEAG1oEkATALhmioEsw4YAfGAFcwTBADNuCJgEo2ABRoBbThAQAeAN7tqdWmw7c4AbhgBfAHy5LGgFAwYVJIKpgYWyjXow2AcjEgQfxAfMxtTGxtaJG1PRlZ2KC4efiERcUkmXFTRCTApG38qcijYUGEoBCK8AAYTMrAKorUYAEZamHrGgGou6Tc7DvBoBwQIQVpYPFQAd1ROWEQUdCwKHXpmaQGPXWYsxzGJgDpt+jCIhAAPAAcQKlgNUyA)

### 💻 Code

```ts
const getBatch = async (scrollId: string | undefined): Promise<{ scroll: string; }> => {
  return { scroll : 'foofoo' }
}

let scrollId: string | undefined = undefined
for (let counter = 0; counter < 10; counter++) {
  const result = await getBatch(scrollId)
  scrollId = result.scroll
}
```

### 🙁 Actual behavior

i get error:
```
'result' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)
```

### 🙂 Expected behavior

I expect no errors: `result` variable should be resolved as `{ scroll: string; }`, as function `getBatch` has very concrete return type

**Comment by MartinJohns** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/43047#issuecomment-821453073.

**Comment by zuozp8** [comment]
right, comment referenced by you talks about the same issue
