### ISSUE TITLE
Conditional types don't seem to reject supertypes where they should

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/TypeScript#48610]
# Bug Report

### 🔎 Search Terms

conditional types, supertype

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&exactOptionalPropertyTypes=true&ts=4.7.0-dev.20220406&ssl=12&ssc=1&pln=2&pc=1#code/LAKALgngDgpgBAFRgZzAHgQPjqOe4C8icMAHmDAHYAmycArjTAGYCWlM1cA-HAEQBjAPaUwAQ3bIAtI2ot2nPrnwB6FYgAWrOsJqswrEXGQah9ADZcARvGZjzyW0IBOcSvQC2N1wB8GTNg5qZTw1ODE6dy8YV204ADkAeQRw43pYZ0hYOCFmN09vOD9ZeSCQuAAufOjXMgoaOhTePijvJRB8SrcYADcYgG5QUDCAaXYuEzNLOAArelQ4G35dcUkZAIVqPgAaOFMAd16YuH0TuntkIWH1PxaCmL44fa0BDTOn5xEAc1As+DGaIRECh0K1jsUNkFMKAgA)

### 💻 Code

```ts
type Test<T> 
    = T extends undefined ? "contains-undefined"
    // This condition should be false for number | undefined
    // as number is NOT a supertype of number | undefined
    : number extends T ? "number"
    : never;

// Kind should just be "contains-undefined", however it is also
// | "number" which is wrong
type Kind = Test<number | undefined>
```

### 🙁 Actual behavior

The branch `number extends T` is incorrectly included as `number` not being a supertype of `number | undefined`. (NOTE: This would not be the same as `T extends number`, because `T = number | undefined` is indeed a supertype of `number`).

You can observe the same behaviour with just:

```ts
// number is clearly not a supertype of (number | undefined)
type ShouldBeNever = number extends (number | undefined) ? "not-never" : never;
```

### 🙂 Expected behavior

Only `"contains-undefined"` should be included in the final type, similarly for the smaller example `ShouldBeNever` should, well, be `never`.

**Comment by fatcerberus** [comment]
```ts
type ShouldBeNever = number extends (number | undefined) ? "not-never" : never;
```

This is *correctly* evaluated to `"not-never"`.  `extends` means “is a subtype of”, or more accurately in the case of conditional types, “is assignable to”.  `number` is assignable to `number | undefined`, so it takes the true branch.

As for `Test`, its behavior is also correct due to distributivity of generic conditional types:
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

**Comment by Jamesernator** [comment]
> This is _correctly_ evaluated to `"not-never"`. `extends` means “is a subtype of”, or more accurately in the case of conditional types, “is assignable to”. `number` is assignable to `number | undefined`, so it takes the true branch.

Admittedly I got it mixed up as I was trying `T extends number` and `number extends T`, and the fact `T extends undefined` worked made me assume `T extends undefined` refered to is `T` a supertype of `undefined`.

> As for `Test`, its behavior is also correct due to distributivity of generic conditional types:

Okay this works as expected, I'm not sure that I agree with the docs that:

> Typically, distributivity is the desired behavior.

It seems more confusing to me that in this one specific instance unions are distributed like nowhere else in TS, it actually makes me now concerned that pretty much all of my conditional types don't work with union types now.

**Comment by fatcerberus** [comment]
if it helps, the rule is that conditional types distribute whenever the type being checked (`T extends…`) is a naked generic type parameter.  You can easily suppress it by writing the check as `[T] extends [U] ? …`
