### ISSUE TITLE
Class expressions should support `in` and `out` variance modifiers

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#48618]
Likely an oversight but

```ts
let Anon = class <out T> {
    foo(): InstanceType<(typeof Anon<T>)> {
        return this;
    }
}

let OuterC = class C<out T> {
    foo(): C<T> {
        return this;
    }
}
```

Results in the following message:

```
error! 'out' modifier can only appear on a type parameter of a class, interface or type alias
```

**Comment by ahejlsberg** [comment]
Yup, that's an oversight.

**Comment by ahejlsberg** [comment]
The repro actually reveals another problem: Validation of variance annotations needs to be deferred as it may otherwise cause circularity errors. Indeed, the `Anon` example errors if validation isn't deferred.
