### ISSUE TITLE
Stateless function components for jsx

### ISSUE THREAD

**Issue by Lenne231** [Microsoft/TypeScript#4861]
ReactJS gets stateless function components https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html

How does it work with the current JSX support in TypeScript? It would be nice if something like this would work as well:

![image](https://cloud.githubusercontent.com/assets/2046557/9967143/1757147e-5e41-11e5-8e79-39201e7d704b.png)

**Comment by mhegazy** [comment]
//cc: @RyanCavanaugh

**Comment by Lenne231** [comment]
`const Headline = (title: string) => <h1>{title}</h1>;` doesn't make sense because JSX attributes have names and parameters of a function not.

But `const Headline = (props : { title: string }) => <h1>{props.title}</h1>;` should work!

**Comment by RyanCavanaugh** [comment]
This needs a spec if we're going to do automatic inference from it.

As @Lenne231 points out, the example posted doesn't seem to be how it works.

Given the example from the release notes:
```ts
var Aquarium = ({species}) => (
  <Tank>
    {getFish(species)}
  </Tank>
);
```
We could type this fairly easily:
```ts
// Put this somewhere
interface ReactStateless<T> extends React.Component<T, {}> {
  (props: T): JSX.Element;
}

var Aquarium: ReactStateless<{species: string}> = ({species}) => (
  <Tank>
    {getFish(species)}
  </Tank>
);
```

**Comment by Lenne231** [comment]
Is there a reason why we are currently not inferring the valid JSX components and the matching JSX properties from the `React.createElement` function? Don't we have all information we need?

```typescript
type JSX = typeof React.createElement

// Type of valid JSX components: type of the first parameter of JSX
// Type of matching JSX properties: first generic parameter of JSX
```

**Comment by Lenne231** [comment]
There will probably be a third kind of component in the future, so it would be nice if the implementation is flexible enough to handle that:

https://github.com/reactjs/react-future/blob/master/07%20-%20Returning%20State/04%20-%20Callback%20Chaining.js

**Comment by RyanCavanaugh** [comment]
Fleshing out the design at #5478
