### ISSUE TITLE
specifiable type parameters for uncalled functions

### ISSUE THREAD

**Issue by lmmarsano** [microsoft/TypeScript#48622]
# Suggestion
## 🔍 Search Terms
- uncalled
- function
- type
- parameter

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Type parameters can be explicitly set for called functions
```typescript
f<A>(a)
```

Allow the same for uncalled functions (perhaps with different notation)
```typescript
f<A>
```

## 📃 Motivating Example
Type parameters for functions can be explicitly specified only in function calls.
```typescript
functionA<TypeA>(variableA)
```

If you want to specialize a generic function type without calling it, you'd have to cast the entire function type explicitly.
```typescript
<(parameter0: TypeParameter0<TypeA>, parameter1: TypeParameter1<TypeA>, ...parametersRemaining: TypeParametersRemaining<TypeA>) => TypeReturn<TypeA>>functionA
```

or
```typescript
interface InterfaceFunctionA<T> {
	(parameter0: TypeParameter0<T>, parameter1: TypeParameter1<T>, ...parametersRemaining: TypeParametersRemaining<T>): TypeReturn<T>
}
<InterfaceFunctionA<TypeA>>functionA
```

Gains from type inference are forfeit, as you may have to write out types explicitly & sometimes painfully work out explicit types that run into truncation limits of TypeScript's inferred type output.
The `typeof` operator offers no quick remedy for generics.
```typescript
declare const identity: <A>(a: A) => A
type IdentityBroken = typeof identity
<IdentityBroken<null>> // Type 'IdentityBroken' is not generic.
```

With specifiable function type parameters, you would no longer have to call the function to specialize its type parameters.
```typescript
functionA<TypeA>
```

## 💻 Use Cases
This regularly comes up with higher-order functions and generics.
```typescript
declare const trash: <A>(fa: (a: A) => null) => void
declare const compose: <A, B, C>(fab: (a: A) => B, fbc: (a: B) => C) => (a: A) => C
declare const identity: <A>(a: A) => A
declare const fNullVoid: (a: null) => void
type IdentityBroken = typeof identity
interface Identity<A> {(a: A): A}
trash(identity) /*
Argument of type '<A>(a: A) => A' is not assignable to parameter of type '(a: unknown) => null'.
  Type 'unknown' is not assignable to type 'null'.
*/
trash(<IdentityBroken<null>>identity) // Type 'IdentityBroken' is not generic.
trash(<Identity<null>>identity)
trash<null>(identity)
compose(identity, fNullVoid) /*
Argument of type '<A>(a: A) => A' is not assignable to parameter of type '(a: unknown) => null'.
  Type 'unknown' is not assignable to type 'null'.
*/
compose(<Identity<null>>identity, fNullVoid)
compose<null, null, void>(identity, fNullVoid)
```

It would be easy to remedy the type errors if I could specify the type parameters.
While I may sometimes do this in enclosing function calls, this again grows unwieldy, as that higher-order function may have any number of generic parameters of any level of complexity that would otherwise be inferred (last line).

<details><summary><b>Output</b></summary>

```ts
"use strict";
trash(identity);
trash(identity);
trash(identity);
trash(identity);
compose(identity, fNullVoid);
compose(identity, fNullVoid);
compose(identity, fNullVoid);

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "Latest",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?target=99&jsx=0#code/CYUwxgNghgTiAEYD2A7AzgF3hmU0AsAueAHgEEA+ACgDMoAjYqqYsgSngF4L4UBXCBA7d4ANyQBLYAChQkWAmTosyALYAHJGhDFyAGngAhAwGFqdRvGathPY-Br0wTFkdvwT76-HZceJ2XBoOERUTHgpEBQMCQwAT11Kb18RMkD5EKVwmgA5AQgANUlgF2J+QXdxKWl49QQASVBo2LjDGCQAayiubDi6pBoIppj46QlokBg6MAbhlvIeAG9ktlYAXxrcAipI5vi2Tbx8KhJGqJHW9q6UEnKICgpdi4OcI5Ozvbjb-IenlpetvhvoJqH99tI1JptDs5vEDLl8kUpAdIVoQO9YV87r9MfC8oIkcAUUgNGjgRADHcDFVgKDcQ58YVimwgA)

**Comment by jcalz** [comment]
TS4.7 will support [instantiation expressions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#instantiation-expressions) as implemented in #47607.
