### ISSUE TITLE
Array binding pattern with only OmittedExpressions does not check RHS of for-of loop

### ISSUE THREAD

**Issue by Fireboltofdeath** [microsoft/TypeScript#48630]
# Bug Report

### 🔎 Search Terms
array binding patterns for-of loop omittedexpression binding elements

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEBMHsFMGcDsDkAXU0BO7LoLACgAzbUACgGNJ5ZUBtAGgF1RICIYFkBRADwEtqSASlDAAvKABMwgN758AXzl4QbOGkzZ8RdKQpVaAfTrGmLVRx79kQkeKmhZeBfiA)

### 💻 Code

```ts
// doesn't error
for (const [,] of doesntExist() /= 2) {

}

// does error
for (const [_,,,] of doesntExist() /= 2) {

}

```

### 🙁 Actual behavior

The right hand side of the for-of loop is not checked at all. 

This appears to be because `OmittedExpression` is not actually a `BindingElement` and the right hand side's type is only checked whenever encountering a `BindingElement` in `checkVariableLikeDeclaration` or when there are no elements in the pattern.

### 🙂 Expected behavior

The right hand side of the for-of loop to be checked.

**Comment by wannieman98** [comment]
Can I give this issue a try?

**Comment by Fireboltofdeath** [comment]
> Can I give this issue a try?

Yes, feel free.

**Comment by wannieman98** [comment]
Can I get some help on where I should begin looking to tackle this issue? Thanks!

**Comment by Fireboltofdeath** [comment]
You should take a look in `checkVariableLikeDeclaration` which is where the right side of the for-of loop gets checked.

**Comment by wannieman98** [comment]
Hi, sorry for another question, but I had been trying to fix the problem but I am not sure whether the [,] counts as a variable declaration or array literal. Could I get a clarification on that?

**Comment by bentongxyz** [comment]
Hi there, if this is not being actively worked on right now, may I give this a try? 
Thanks!

**Comment by bentongxyz** [comment]
Hi there, if this is not being actively worked on right now, may I give this a try? 
Thanks!

**Comment by bentongxyz** [comment]
Hi @RyanCavanaugh @Fireboltofdeath, I made a PR for this issue, please check at your latest convenience!

Much thanks.
