### ISSUE TITLE
Manually add to SystemJS imports, just like <amd-dependency> does for AMD

### ISSUE THREAD

**Issue by migajek** [Microsoft/TypeScript#4863]
I'm developing with Aurelia which uses SystemJS loader. 
There are cases where I need to use special kind of "import" to load CSS dynamically.
while the code below is fine with Babel, it obviously doesn't compile with TypeScript
``import 'bootstrap/css/bootstrap.css!'``

To make use of this feature I had to switch to AMD module loader and use ``<amd-dependency path="bootstrap/css/bootstrap.css!">`` which emits proper code

I'd love to see similar feature for SystemJS

**Comment by mhegazy** [comment]
>  it obviously doesn't compile with TypeScript

this compiles fine for me. what version are you using?

```cmd
c:\ts>type c:\test\module3.ts
import 'bootstrap/css/bootstrap.css!'

c:\ts>tsc c:\test\module3.ts --m system

c:\ts>type c:\test\module3.js
System.register(['bootstrap/css/bootstrap.css!'], function(exports_1) {
    return {
        setters:[
            function (_1) {}],
        execute: function() {
        }
    }
});
```

**Comment by migajek** [comment]
@mhegazy my bad, I'm *really* sorry, this seems to be related to the (outdated) ReSharper I'm using.

**Comment by mhegazy** [comment]
No worries. Glad we got to the bottom of it.
