### ISSUE TITLE
EyeDropper API declarations missing

### ISSUE THREAD

**Issue by yisibl** [microsoft/TypeScript#48638]
The EyeDropper API enables developers to use a browser-supplied eyedropper in the construction of custom color pickers. 

- Spec: https://wicg.github.io/eyedropper-api/
- Chrome 95 shiped: https://chromestatus.com/feature/6304275594477568
- https://web.dev/eyedropper/

## 🔍 Search Terms

- EyeDropper
- EyeDropper API

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper

MDN says it's experimental and only implemented in Chromium-based browsers right now.  TS as a rule doesn't include typings for browser APIs until at least two engines (*engines*, not browsers) support them.

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator#when-the-type-is-missing

**Comment by bkrmendy** [comment]
if you still want to use EyeDropper (despite the lack of support), this `.d.ts` can be a start: https://gist.github.com/bkrmendy/f4582173f50fab209ddfef1377ab31e3
