### ISSUE TITLE
Debug Failure. No error for last overload signature

### ISSUE THREAD

**Issue by pfgithub** [microsoft/TypeScript#48636]
# Bug Report

### 🔎 Search Terms

"Debug Failure. No error for last overload signature"

Also, for anyone in the future finding a minimal reproduction for an error like this: edit `node_modules/typescript/tsc.js` in order to find out which line is causing the crash

```diff
- ts.Debug.fail("No error for last overload signature");
+ ts.Debug.fail("No error for last overload signature. Call:\n" + ts.getTextOfNode(node));
```

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Workbench link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAIhFgEoQIYBMD2A7ANiAPACoB8UAvFAAxQQAewEWaAzlAIxQBkUhUA-DygAuKAG8AUFClQATqky4QUANoBpKAEssUANYQQGAGY8AuiLgJk6bHiJqTxANziAvs7QQAxjhRyohgFcsT2ANbFkvbE8NHAgiGnpGFigAVQAaVOIACgA3FBwAiBFCAEoRLOZgFAYRFJLyUkJncVBIKABlYAw5dohgBhkiUgosrLA5HM7qoth4JHkbAhJ6slILeetFIZLm1uhe4E7uiAAxIJCwrCHyKAq+gZEjnvuIQeWGqByMDTRmujBusB-OdQuE9sxPDINGBgABhGQoZgACyGWUk0jyBRm6ysClsJDS6KkzD6ADV8oVHn0nqcQZd4gAfKBYAI4HDEQn1CTSKAk4DkrFZOSeKIxCC5CkQEo7VxAA)

### 💻 Code

```ts
type DeepReadonly<T> = 0 extends 1 & T ? T : {
    readonly [K in keyof T]: DeepReadonly<T[K]>;
};
declare function reconcile<T extends U, U>(value: T): (state: U) => T;

type StoreSetter<T> = ((prevState: DeepReadonly<T>) => DeepReadonly<T>);

type SetStoreFunction<T> = (setter: StoreSetter<T>) => void;

export function typescriptCrash<T>(
    value: DeepReadonly<T>,
    setValue: SetStoreFunction<T | null>,
) {
    setValue(reconcile(value));
}
```

### 🙁 Actual behavior

Typescript crashed.

```
Debug Failure. No error for last overload signature

fail@https://typescript.azureedge.net/cdn/4.7.0-dev.20220408/monaco/dev/vs/language/typescript/tsWorker.js:2468:17
resolveCall@https://typescript.azureedge.net/cdn/4.7.0-dev.20220408/monaco/dev/vs/language/typescript/tsWorker.js:62458:27
resolveCallExpression@https://typescript.azureedge.net/cdn/4.7.0-dev.20220408/monaco/dev/vs/language/typescript/tsWorker.js:62780:16
resolveSignature@https://typescript.azureedge.net/cdn/4.7.0-dev.20220408/monaco/dev/vs/language/typescript/tsWorker.js:63097:20
…
```

### 🙂 Expected behavior

Typescript should not have crashed. Also, I think the code should compile with no errors, but I'm not sure.

**Comment by eemeli** [comment]
I think I hit this same crash, with a React `useState()` call and a value with a `Readonly<Type>` wrapper: [Playground link](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220515&ssl=11&ssc=12&pln=11&pc=20#code/JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC+cAZlBCHAERTo4DGMVA3AFCswCeYBAInjjgBeOACU6AEwgA7ADacAPAlZw4ANxyzk6AFxxpyEACN0UNqpIQIAChxQA5npzTOASj1qIwCebhG7tg5OLu7qXj6shAB8bKzoAB6QsKTI0ozAMnAAwhSQ0ujSMNauiCpw9DKo8ADaVXjoADRwGDDY9QC6wigYbfgK-LhR1sXCUXDWyqqqGlq61FVQwNL2VE0A9GtwMAAWwKjN2xDIshJ+BIIGxqZlFlZ6gfYlQmMtvejDYLRqT2MTcAB0gM+6DUTTs9iIrlcDRufjs93BP2a6FauHwHy+SL+gP+wNBcHBkOhZUIULYhCAA)

Same results as in the original description also with TypeScript 4.6.4 and `@types/react` 16.14.25.
