### ISSUE TITLE
'Router' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Mahlyjan** [microsoft/TypeScript#48649]
# Bug Report

<!-- When did you start seeing this bug occur?
Well it started on 8th April 2022. Could not see the issue in my local but could it happens everytime we run jenkins with typescript@4.6.0. However now that i re-installed my node modules in my local, I am experiencing this issue.

### 💻 Code
 Its instance type 'Router' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/Users/najmah/Desktop/DevCloud_Air/digitrade/digitrade/digitrade-web/node_modules/@types/hoist-non-react-statics/node_modules/@types/react/index").ReactNode'.  TS2786

    36 |       <ThemeProvider theme={theme}>
    37 |         <CssBaseline />
  > 38 |         <Router history={history}>
       |          ^
    39 |           {isMobileOnly ? <Routes routes={RoutesConfigMobile} /> : <Routes routes={RoutesConfig} />}
    40 |         </Router>
    41 |       </ThemeProvider>

**Comment by jbk75** [comment]
How did you resolve this?

**Comment by ritschwumm** [comment]
not sure why the description is gone, but to me it looks like there were two different version of ReactNode used, probably because of a dependency version mismatch
