### ISSUE TITLE
Missing syntax error for `new A?.b()`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#48653]
# Bug Report

### 🔎 Search Terms

syntax error optional chain new arguments parentheses

### 🕗 Version & Regression Information

Only tested with 4.7 Nightly in the playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/MYGwhgzhAECC0G8BQ1XQEYAoCUiC+SBSAdgKYDucA-AHRbZJA)

### 💻 Code

```ts
class A {
    b() {}
}

new A?.b()

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var _a;
class A {
    b() { }
}
(_a = new A) === null || _a === void 0 ? void 0 : _a.b();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/MYGwhgzhAECC0G8BQ1XQEYAoCUiC+SBSAdgKYDucA-AHRbZJA)
      

### 🙁 Actual behavior

`new A?.b()` is parsed as if it was `new A()?.b()`

### 🙂 Expected behavior

It should be a syntax error, because it's not valid JavaScript syntax.

**Comment by fatcerberus** [comment]
`new A()?.b()` is still invalid JS.  What's interesting is that when targeting `esnext`, the code is emitted as-is (and is a runtime error), but downlevel emit is doing the equivalent of `(new A)?.b()` instead.

**Comment by nicolo-ribaudo** [comment]
`new A()?.b()` _is_ valid JS (or at least, it's valid in Node.js and Firefox).

**Comment by fatcerberus** [comment]
Ah, you're right, I thought I had tried it and gotten an "invalid optional chain" error.  But yeah, really weird because the esnext emit preserves the runtime SyntaxError while the downlevel emit changes the meaning of the code.

**Comment by MartinJohns** [comment]
@fatcerberus I don't know what you mean. Under esnext it emits `new A()?.b()`, which is valid. There's no runtime error. Perhaps you can share a playground link?
