### ISSUE TITLE
Playground should note the version/flags that are in use

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#4866]
People are sometimes confused about exactly what is/isn't allowed and why. It would be simple enough for us to indicate this somewhere on the page. For example https://github.com/Microsoft/TypeScript/issues/4853

**Comment by aleksey-bykov** [comment]
is it feasible to be able to **pick** the version at playground?

**Comment by kitsonk** [comment]
or at least provide unique URLs for different versions, with the main one being the current stable release...

**Comment by mhegazy** [comment]
not at the time being. but we are planning on cleaning up the website soon, including the handbook, and the playground. and allowing multiple versions has been one of the top requests.

**Comment by petrkoutnysw** [comment]
Any updates on this? It would be really nice to be able to select other-than-latest version.

**Comment by mhegazy** [comment]
Hit F12 on the playground, you should see the version written to the console.
![image](https://cloud.githubusercontent.com/assets/8000722/25916568/f5a6daf0-3579-11e7-8d8f-120173a1be19.png)

**Comment by petrkoutnysw** [comment]
@mhegazy Okay, but how can I change the version that playground use? :)

**Comment by mhegazy** [comment]
> @mhegazy Okay, but how can I change the version that playground use? :)

That is tracked by https://github.com/Microsoft/TypeScript/issues/15662

**Comment by mhegazy** [comment]
closing in favor of #15662
