### ISSUE TITLE
Typescript infers generic incorrectly when function parameter have a generic type matching argument and argument is a union with duplicated type

### ISSUE THREAD

**Issue by mmis1000** [microsoft/TypeScript#48670]
# Bug Report

### 🔎 Search Terms
 infer duplicate generic

### 🕗 Version & Regression Information
Version: 4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/JYOwLgpgTgZghgYwgAgEoRgHgCrILzJwgCeAfMgN4BQytyAbnADYCuEAXMtgNxUC+VKqEixEKdDABMOfIRLlqdBszace-QcOjwkaDAGYZBImUo06jVhy68BVACYQETOFBQIA9iADOYZCxA3GE4cUgAKVwBzTglQ5AAfLgBKfHJsQUdnV3cXb29kAEEzJQAHKGBGSGQSzhAWJiYNKk8fPzgARk4iggCgujC6hsJ8k2HChL0sAvIlWbmlJOavX0JJLtlejH7BpjHRuHyi+dpEiWlp49pFlpW4ABZ1nsCt2gH63YO5YjGi04xMC5-KQAmbHFIAenByAAolAoB4oMgAIRUcEAKjRyAAesgwAALYD5PGfWHwqAAGi4yEJ1JAMGgbnsYwABr9JudSMzaZ44U4wExvhB6BAQMhmWcuTT8ShvHAALYoT7ijBctHgpatQgAVke-meU3COz2JB+E1igPZIMuyEW6MxOJgCN0bm8HlYYGAXmQAHcEQBrfJqjW3ABsus2MG272N30+R2OQI5ZoMINtGOxhCgkRYCvAuOJfnsXgA5H5icKxRIuT7-YHwUA)

### 💻 Code

```ts
interface Ref<T = any> {
    value: T;
}

interface Ref2<T = any> {
    value: T;
}

interface Ref3<T = any> {
    value: T;
}

declare const unref: <T>(arg: Ref<T> | T) => T

declare class A {
    private p: null
}

const a1: A = unref   (null as any as A | Ref<A>                    )
const a2: A = unref   (null as any as A          | Ref2<A>          )
const a4: A = unref   (null as any as A | Ref<A> | Ref2<A>          ) // Error !
/** ^ this has Error, T is inferred as `A | Ref2<A>` incorrectly even `Ref2` is the same as `Ref` */
const a5: A = unref<A>(null as any as A | Ref<A> | Ref2<A>          )
/** ^ force resolution works */
const a6: A = unref   (null as any as A          | Ref2<A> | Ref3<A>)
/** ^ argument that don't have `Ref`  works */
```

### 🙁 Actual behavior

Typescript infers `T` as  `A | Ref2<A>` when `Ref` definition is in the union even `Ref2` is completely the same as `Ref`

### 🙂 Expected behavior

`T` is `A`

### Note.

This is discovered during testing the vue framework.
The framework has two value wrapper interface that has a parent/child relationship and a function to conditionally unwrap wrapper.
And I try to unwrap a union of both wrapper

```ts
// Framework code (simplified)
interface Ref<T> { value: T }
interface ComputedRef<T> extends Ref<T> { readonly value: T }
declare function unref<T> (arg: T | Ref<T>): T
// user code
declare class Data { private p: null }
declare const input: Data | Ref<Data> | ComputedRef<Data>
const unwrapped: Data = unref(input)
```

**Comment by RyanCavanaugh** [comment]
This is a valid inference; there's nothing but heuristics to apply in the case of an unconstrained `T | Foo<T>` and the heuristics we have in place are not oriented around this case.
