### ISSUE TITLE
rename typescript default import will modify types under node_modules

### ISSUE THREAD

**Issue by tjx666** [microsoft/TypeScript#48681]
Does this issue occur when all extensions are disabled?: Yes/No
Yes.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/41773861/161397152-9b161bb1-13b5-414f-84ff-c2d6b0779318.png">

- VS Code Version: 1.67.0-insider
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. set "typescript.preferences.useAliasesForRenames": false
2. install package highlight.js
3. write ts code : `import hljs from 'highlight.js/lib/core';`
4. rename `hljs` to `highlightJS`

**Comment by mjbvz** [comment]
Minimal, self-contained example: https://github.com/mjbvz/ts-48681

**Comment by tjx666** [comment]
When I rename the url to urlLib, it change the module name in node_modules:

![image](https://user-images.githubusercontent.com/41773861/164955087-07fb9351-06a4-4221-aab4-28bf1dc0f12f.png)

![image](https://user-images.githubusercontent.com/41773861/164955095-03e5b7c3-741b-465c-8686-3aa8c1fc30f3.png)
