### ISSUE TITLE
destructuring cause compiler error  TS1008 and TS1005

### ISSUE THREAD

**Issue by codelegant** [Microsoft/TypeScript#4869]
I wanna use destructuring in typescript,example code:
```js
var {first, second} = { first: "one", second: "two" }
console.log(first);
```
my compile command `tsc --t es5  destructuring.ts`,
typescript version `1.6.2`,
IDE is `vs code`.
then cause error:
`destructuring.ts(1,5): error TS1008: Unexpectedtoken; 'identifier' expected.`
`destructuring.ts(1,21): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected.`
`destructuring.ts(1,45): error TS1005: ';' expected.`

**Comment by DanielRosenwasser** [comment]
Hi @codelegant, if you type in `tsc --version`, what is the specific output?

**Comment by codelegant** [comment]
`message TS6029: Version 1.6.2`

**Comment by codelegant** [comment]
In my desktop,command `npm -g list` ,show ` typescript@1.6.2 `,and command  `tsc --version` show `Version 1.0.3.0`:
![typescript 1.0.3.0](http://www.laichuanfeng.com/wp-content/uploads/2015/09/typescript.png);
But in my laptop,the command `tsc --version` show `message TS6029: Version 1.6.2`:
![typescript 1.6.2](http://www.laichuanfeng.com/wp-content/uploads/2015/09/typescript1.6.2.png)

**Comment by DanielRosenwasser** [comment]
Your `npm` version is being shadowed by one you probably installed through Visual Studio. If you open up `cmd.exe` and type in `where tsc` you'll see which one that is.

You'll need to amend your `PATH` variable so that `tsc` gets resolved to the correct one.

**Comment by codelegant** [comment]
@DanielRosenwasser  Thanks for your answer,I have solved this issue as your guidance .

**Comment by liu-ning** [comment]
@DanielRosenwasser  Thanks for your answer. I meet the same question and solved.

**Comment by DanielRosenwasser** [comment]
You're welcome!
