### ISSUE TITLE
Boolean properties are treated differently in conditional types (functions/methods)

### ISSUE THREAD

**Issue by bluebarcode** [microsoft/TypeScript#48696]
# Bug Report

Comparing conditional types containing boolean properties behave dififferent to other property types. But this only occures when the comparison takes place in a function/method.

### 🔎 Search Terms

conditional types, boolean, method, function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2&ssl=23&ssc=28&pln=1&pc=1#code/C4TwDgpgBAYghgSwDYGcAq5oF4oG8BQUUAZgPakBcUARuUhHAHYDc+Avq6JFAOqkBOAa3SYoOXFEIlyVFMH4JGAc3asAxkjgoUUNBDkBhTdoA8ABTj84AWwB8eKcH3AYAV0ZqqJtFAgAPJ0YAEx0LfmAEOCRzSxtbWwAKKSIwWOsqNCkASjF7XCc5M35SMAB+CjCbXwCIYNDLCKjve1KoAHIQfTaoKjbGUja2MSgE1KtrLKxE3DYs1jZ8LmhFJEUIPTlh+GQRbn9AkKgwxujt1AxIFvbOlG7e-rb1UkZNlbWN4AA1KNcICjfGOtnMMOl1WPgAPQQqAACQg-GWUFcKGgwAAFtA+EIdBcIPg1M9NgVgEYtCgscJhoCAO66Zyk0wU3YQRJzfGE4BQBEoVxIYBM4bEhnkgTCAB0xLcHgSEjIlHa1NFtygs1Y3N5-KVEucRRKWFBt3BUNh8MRyNRGNgiFQukw7JenKFxhQZx0OBpdMMzpMrtxrKeDq5+g1rsF9Odru1cilahl0nlxCiKJVbPVfMjxN1YH1N0e+CAA)

### 💻 Code

```ts
type FailsType = {
  foo: boolean;
};
type WorksType = { 
  foo: string
};
class TestClass<Param> {
  testFunc: <T extends Partial<Param>>(
    param: T
  ) => {testProp?:Param extends Partial<T> ? 'yes' : 'no'} = (param)=>({});
}
type inlineTest = FailsType extends Partial<FailsType> ? 'yes' : 'no';
const inlineTestValue:inlineTest = 'yes';

// Here i use the Works Type
const testClassWorks = new TestClass<WorksType>();
const resultWorks = testClassWorks.testFunc({ foo: 'works' });
resultWorks.testProp='yes';

// Here i use the Fails Type
const testClassFails = new TestClass<FailsType>();
const resultFails = testClassFails.testFunc({ foo: false });
resultFails.testProp='yes';
```

### 🙁 Actual behavior

The type of resultFails.testProp is not 'yes'

### 🙂 Expected behavior

The type of resultFails.testProp should be 'yes'

**Comment by whzx5byb** [comment]
It is similar to https://github.com/microsoft/TypeScript/issues/48363, which was fixed by https://github.com/microsoft/TypeScript/pull/48380. But it seems the PR doesn't fix the issue when a boolean literal is used as a property.

**Comment by RyanCavanaugh** [comment]
`boolean` is an alias for `true | false`, and when a primitive literal is contextually typed by a union containing that literal's corresponding type, then it retains its actual literal type instead of widening to its parent primitive. So the comparison here is `{ foo: boolean } extends { foo?: false } ? ...` which is correctly `false`

**Comment by bluebarcode** [comment]
Thank you for the explanation! 

This is not intuitive tho. But i assume it has a good reason to be as it is?
