### ISSUE TITLE
Show Inlay Hints for Tuple Labels

### ISSUE THREAD

**Issue by bmdelacruz** [microsoft/TypeScript#48704]
# Suggestion

## 🔍 Search Terms

inlay hints tuple label

## ✅ Viability Checklist

This only affects the language server and its clients.

## ⭐ Suggestion

Show inlay hints for tuple labels.

Currently, tuple labels can only be seen by hovering the index used to access the labeled tuple. Also, there is no direct way to see the labels when the tuple's type is behind an alias and the tuple is assigned to a variable (line 9 in screenshot); you need to navigate to the variable declaration and hover it to see the tuple labels. Same thing happens when the tuple is directly passed as an argument (line 6 in screenshot).

I did some digging and created a [minimal implementation](https://github.com/bmdelacruz/TypeScript/tree/feat-inlay-tuple-labels).

![Screenshot of the said minimal implementation](https://user-images.githubusercontent.com/11897772/163464539-b64bf75d-fa3e-4df2-8733-086cf8c024f9.png)

**Comment by ilogico** [comment]
I think it's a good idea, but they should be consistent with parameter names:
```ts
parseInt(/* str: */ '123', /* radix: */ 8);
useTuple([/* beep: */ 0, /* foo: */ 0]);
```

**Comment by ilogico** [comment]
This could also be handy for destructuring:
```ts
const [/* current: */ count, /* set: */ setCount] = useState(0); 
```

**Comment by RyanCavanaugh** [comment]
This seems like a good use of the feature; we can try it out

**Comment by wesbos** [comment]
No love for this? It would be very helpful to see the tuple labels in TypeScript

<img width="816" alt="image" src="https://user-images.githubusercontent.com/176013/207704827-babcc2b8-f38b-4fa7-a22f-8d344dd63ea5.png">
