### ISSUE TITLE
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'flags')

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#48706]
# Bug Report

### 🔎 Search Terms

Cannot read properties of undefined (reading 'flags')

There was a similarly titled, but completely unrelated, issue: #35021

### 🕗 Version & Regression Information

4.6.3

It might NOT occurr in 4.4.4 (the client code wasn't exactly the same).

- This is a crash 

### ⏯ Playground Link

It's transformed API related, cant do it in playground (I think).

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

This is the Typescript code which I think might be buggy, taken from 4.6.3 *typescript.js*
```
        function isReferencedAliasDeclaration(node, checkChildren) {
            if (isAliasSymbolDeclaration(node)) {
                var symbol = getSymbolOfNode(node);
                var links = symbol && getSymbolLinks(symbol);
                if (links === null || links === void 0 ? void 0 : links.referenced) {
                    return true;
                }
                var target = getSymbolLinks(symbol).target; // TODO: GH#18217
```
At the time of exception, `symbol` has value `undefined`. 
After
```
links = symbol && getSymbolLinks(symbol)
```
`links` is also `undefined`.
But that value of links does not pass the test 
```
(links === null || links === void 0 ? void 0 : links.referenced)
```
so the following line 
```
var target = getSymbolLinks(symbol).target; // TODO: GH#18217
```
is executed and within that call, 
```
        function getSymbolLinks(symbol) {
            if (symbol.flags & 33554432 /* Transient */)
```
the error is thrown.

The code logic appears (at first glance) to want to intend to accept `symbol===undefined`  
as a logic path to handle, by returning true. 

However, the possibility also exists that, despite the appearance of the code,
 a value of `symbol===undefined` should actually trigger an exception (although it could have a nicer error message).

In case the above code `isReferencedAliasDeclaration` is behaving as intended, then it could be that the client code is breaking a rule, so I show that code next.

The client code is a "before" transform that inserts statements into a source file.
Because these statements have not been type checked, it make would sense that they have no symbols (I think).
It is when typescript is processing these synthesized statements in a later transform of it's own that the error occurs,
(I.e., the error does not occur within the following client code).
The transform looks like this:
```ts

function sourceTextForRequire() {
  return `
import { createRequire } from "module";
const require = createRequire(import.meta.url);  
`;
}

function transformNode_rmPosEnd(
  sf: ts.SourceFile,
  ctx: ts.TransformationContext
) {
  const visitor: ts.Visitor = (node: ts.Node) => {
    if (typeof node.pos !=="undefined"){
      (node as any).pos = -1;
      (node as any).end = -1;
    }
    return ts.visitEachChild(node, visitor, ctx);
  };
  return ts.visitEachChild(sf, visitor, ctx);
}

export function createTransformBeforeAddESSpecial(
  absTsconfigPath: string,
  program: ts.Program,
  directiveForRequire: string | undefined = "@es-insert-require",
  directiveForFilename: string | undefined = "@es-insert-filename"
): ts.TransformerFactory<ts.SourceFile> | ts.CustomTransformerFactory {
  console.log(`transformBeforeAddESSpecial: ${absTsconfigPath}`);
  const options = program.getCompilerOptions();
  const target = options.target ?? ts.ScriptTarget.ES3;
  const dummyRequireSF = ts.createSourceFile(
    "",
    sourceTextForRequire(),
    target,
    true,
    ts.ScriptKind.TS
  );
  return (ctx) => (sf) => {
    const add: ts.Statement[] = [];
    if (
      directiveForRequire &&
      checkLeadingCommentRanges(sf, sf, directiveForRequire)
    ) {
      transformNode_rmPosEnd(dummyRequireSF, ctx);
      let statements = dummyRequireSF.statements.slice();
      const lastStatement = dummyRequireSF.statements.slice(-1)[0];
      if (lastStatement.kind === ts.SyntaxKind.EndOfFileToken)
        statements = statements.slice(0,-1);
      add.push(...statements); // omit EndOfFile token at end.
    }
    if (add.length===0)
      return sf;
    const sf1 = ctx.factory.updateSourceFile(
      sf,
      ctx.factory.createNodeArray([...add, ...sf.statements.slice()])
    );
    if (options.sourceMap) ts.setSourceMapRange(sf1, ts.getSourceMapRange(sf)); // is this needed/effective?
    return sf1;
  };
}
```

In my particular test case I can avoid the error by changing changing from a *before* transform to an *after* transform.
The code is almost exactly the same - the only change is using `ts.ScriptKind.JS` instead of `ts.ScriptKind.TS` in the call to `ts.createSourceFile`.

However, in the general case, I am concerned about the possibility of comment directives being stripped or moved by the time the *after* transforms are called - so I guess *before* is preferable. 

```

### 🙁 Actual behavior
Exception because a statement inserted by transform doesn't have a symbol.

### 🙂 Expected behavior
No exception.

**Comment by craigphicks** [comment]
It seems I can't edit my original post now.  All the code and comments about directive can be ignored  - it's not relevant to the problem.  Just assume every file is transformed.

**Comment by jwalton** [comment]
I just ran into this too, but in my case it's in `isAliasResolvedToValue()`:

```js
        function isAliasResolvedToValue(symbol) {
            if (!symbol) {
                return false;
            }
            var target = getExportSymbolOfValueSymbolIfExported(resolveAlias(symbol));
            if (target === unknownSymbol) {
                return true;
            }
            return !!(target.flags & 111551) &&
                (ts.shouldPreserveConstEnums(compilerOptions) || !isConstEnumOrConstEnumOnlyModule(target));
        }
```

Here `target` is undefined.

**Comment by gabritto** [comment]
@craigphicks I've finally had a chance to look into this (thank you for your patience). It seems the crash is expected, because inside a custom transformer, you should only either interact with the parse tree of the thing you're transforming, or with synthetic nodes (created via `factory`). In your transformer, you're creating a source file in `const dummyRequireSF = ts.createSourceFile(...);` and mixing the `dummyRequireSF`'s parse tree with the parse tree of the transformed file.
You should create the statements to be added with e.g. `ctx.factory.createImportDeclaration()`.

To provide more details about what's happening, the crash happens, like you said, because we expect the node to have a symbol, but it doesn't. We have a check that is meant to detect whether a node is synthesized or not (via `getParseTreeNode`), and skip calling e.g. `isReferencedAliasDeclaration` on a node that is synthesized, but in your case we end up calling `isReferencedAliasDeclaration` because the node is not synthesized, since it comes from a different parse tree.
