### ISSUE TITLE
Getters are inaccurately narrowed

### ISSUE THREAD

**Issue by suneettipirneni** [microsoft/TypeScript#48700]
# Bug Report

### 🔎 Search Terms

getters, narrowing
### 🕗 Version & Regression Information

TypeScript 4.6.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwILwN4Ch7wHMQAXeAMwHsKAKASgC55liYBLAOwPgB952BXCBADcOAL44cYCu2bwo8ALx8QAdwx1ROVmXjUoAOkoV4AQkXKBQ2tjzyjVeAHon8AJLtpMOGGIQAnvAAcrAwFKogwPDEJgAGzGycsfDiQA)

### 💻 Code
```ts
declare class A {
  get foo(): string | null;
}

declare function func(): string | null;

const a = new A();

if (a.foo !== null) {
  a.foo // Incorrectly Narrowed to `string` 
}
```

TypeScript seems to assume that the getter will always return a non-value after it's been verified that its initial call doesn't equal null.

The issue with this assumption is that it doesn't take into account side effects. A getter is never guaranteed to return the same value after `n` consecutive calls. Therefore the assumption that: *because one call yielded a non-null value, then subsequent calls will also yield non-null values* is incorrect. 

### 🙁 Actual behavior

Getters are narrowed based on the return type of a single call.

### 🙂 Expected behavior

The narrowing of getters should take into account side-effects and should not narrow getter types. Instead getter return values should be stored in a local variable and the local variable should be narrowed.

**Comment by dsherret** [comment]
This is one of the tradeoffs control flow analysis makes—getters are essentially treated the same as regular properties.

See #46771
