### ISSUE TITLE
Incorrectly inferred generic types in JSX

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#48709]
# Bug Report

### 🔎 Search Terms

jsx, inferred, generics, mapped type

### 🕗 Version & Regression Information

**Tested on latest version 4.6.2**, but has the same behavior even back to 4.0.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&pretty=true&ts=4.6.2#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDejUYCiANkiEgHZZwDCE4EFlMAKgJ5hLZpSoxIkyzOAF84AMyj04AIl7oYMgFBKYHJHAAKUsAGcAPIPJUAfHAC8uJXBtwkpYzAD8ALjhHhAHzgByACbAAG4+SmIAZHAAFB5UdgAe-BR+unAA1khsEOJwAFIAygAaAHQAklRQwBS6wGgxMClOuYWl5ZXVtQ7MugDadQC6cG518YnJtPSQTFTsnPqV4khQWmaNmoO4IgCUKuIArhQYwIz4CnQMUzCGnbFICZRj6ZnZ+cVlMBVVNXUp3meTzDMkPoUBQ2CYzJEcNZbPYhLFLP4gj5MNCbEV0WAdLpQm5tBA9Fc4TATJs3MgFMMobY4LwYLsoBQ4Dw+AJrjBIrDHNhMfjdNsRCo1JxaLtdDB6H9GMw8XoLFZqTywABBNxij4Ac1RcEVACE3BRdiAAEaLLWKmhuI0QCCkEGhHb7Q7HGii8UgSUXKKK3RuF1iiUTKVUGV8+W2Wn0xn6AKBOAAehM9qUcbjcAA6ggAPIAOQA4m4ymhoEgMMQ2HBKjAFlAUjAABYaIUaFApckYD3MfSPLJNV6tT4dIk-E4YIod6bqYGg8HJ1NG3bwSo01DEYBqOC6OsQXbEPxwE0jmDjy6I4KJotVeBKuX6NtHwOehOz6kvmwAPScKhT6azeYLB2LUty0ratawbOAmzgFtD2PLsMh7F4WneNovjZYc7zHB8AUnEEwUTb950XRl5FXddN23Xd9w0O9YNPHxz0YMU4B1G8aKwm42XMOj43w1NX2pD8v1TDMc3zOBC0AmAywrKhQIg8DIOgtjzk7btnmaN4Pnab44G8DDj0BKc8OfQiZOXFBSPLcidz3A9lP+Kh9B8FB6KUC8mJoViCHvFSOKJLiXJ459+NsQTnxoTMEAQQgaBYX1JOk+ZFjAxt1Cg1tvNgpsez9N1jwYy84AAES8052PgTlmHMHBcoDXyYDERUlS4nxtR0HVqoAJk6gBmRqdE8p9vxC98nCAA)

### 💻 Code

```tsx
import React, { ReactElement, ComponentType, createElement } from "react"

type Props<Element> = {
    element?: Element | 'div'
} & (Element extends keyof JSX.IntrinsicElements ? JSX.IntrinsicElements[Element] : Element extends ComponentType<infer P> ? P : {})

function ReactComponent<Element extends keyof JSX.IntrinsicElements | ComponentType<any>> ({
    element = 'div',
    ...props
}: Props<Element>): ReactElement {
    return createElement(element, props)
}

type CustomComponentProps = {
    propA: string
    propB: number
    propC: boolean
}

function CustomComponent (props: CustomComponentProps) {
    return <div />
}

// WRONG: Incorectly infers the type as ReactComponent<keyof JSX.IntrinsicElements | React.ComponentType<any>>
// but in reality should be ReactComponent<'div'>
const A = <ReactComponent />
//           ^?

// WRONG: Incorectly infers the type as ReactComponent<keyof JSX.IntrinsicElements | React.ComponentType<any>>
// but in reality should be ReactComponent<'div'>
const B = <ReactComponent element='div' />
//           ^?

// WRONG: Incorectly inters the type as ReactComponent<keyof JSX.IntrinsicElements | React.ComponentType<any>>
// but in reality should be ReactComponent<'a'>
const C = <ReactComponent element='a' />
//           ^?

// CORRECT: Corectly infers the type as ReactComponent<typeof CustomComponent>
const D = <ReactComponent element={CustomComponent} propA='' propB={223} propC />
//           ^?
```

### 🙁 Actual behavior

For examples `A`, `B` and `C` the generic type on the React component is incorrectly inferred as the generic constraint instead of the actual type of `element` prop.

### 🙂 Expected behavior

1) I expect the generic `element: Element` correctly infers the type of the component.
2) I expect the default value of `div` is inferred when no `element` prop is passed to component.

**Comment by RyanCavanaugh** [comment]
Several points of misinterpretation here

Parameter defaults are an implementation detail, not part of the public signature of the function. In other words,
```ts
function f(s: string = "hello") { }
```
and
```ts
function f(s?: string) {
  s = s ?? "hello";
}
```
are treated equivalently by the type system. So `A` cannot possibly be `"div"`. We can simplify the example, then:
```ts
declare function ReactComponent<Element extends keyof JSX.IntrinsicElements | ComponentType<any>> (props: Props<Element>): ReactElement;
```
The definition of `Props<Element>` isn't sufficient to create an inference site for `Element` the way you want it to due to the fact that `ComponentType` "might" resolve to some type where `element` is part of the resolved props.

A correct definition is
```ts
type ComponentPropsOf<T, Else> = T extends ComponentType<infer P> ? P : Else;
declare function ReactComponent<Element extends keyof JSX.IntrinsicElements | object>(props: { element?: Element } &
    ([Element] extends [keyof JSX.IntrinsicElements] ? JSX.IntrinsicElements[Element] :
    ComponentPropsOf<Element, JSX.IntrinsicElements['textarea']>)): ReactElement;

type CustomComponentProps = {
    propA: string
    propB: number
    propC: boolean
}

function CustomComponent (props: CustomComponentProps) {
    return <div />
}

// WRONG: Incorectly intfers the type as ReactComponent<keyof JSX.IntrinsicElements | React.ComponentType<any>>
// but in reality should be ReactComponent<'div'>
const A = <ReactComponent rows={0} />
//           ^?

// WRONG: Incorectly intfers the type as ReactComponent<keyof JSX.IntrinsicElements | React.ComponentType<any>>
// but in reality should be ReactComponent<'div'>
const B = <ReactComponent element='div' />
//           ^?

// WRONG: Incorectly intfers the type as ReactComponent<keyof JSX.IntrinsicElements | React.ComponentType<any>>
// but in reality should be ReactComponent<'a'>
const C = <ReactComponent element='a' />
//           ^?

// CORRECT: Corectly infers the type as ReactComponent<typeof CustomComponent>
const D = <ReactComponent element={CustomComponent} propA='' propB={223} propC />
//           ^?
```
shown here using `textarea` instead of `div` as the default so we can demonstrate the presence of the specific `rows` property
