### ISSUE TITLE
Proposal: Add a syntactic sugar for 'this' or/and optionally relax its usage when possible.

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/TypeScript#4871]
## Background
One of the things that I really dislike about TypeScript is that whenever I need to point to a field or a function I need to use *this.something*, the *this* keyword is used heavily whereas in other languages I can *avoid it* by doing *_something*.

*Clarification: by avoiding it I really mean that the compiler can figure it out for me and free me from having to type it.*

I fully understand the need for it but can't we do better than having to type it all the time? it's quite verbose.

So in order to reduce the amount of verbosity in the code I propose a syntactic sugar to it.

## Syntax
I thought of two syntactic sugars that can be *attractive*, it's very subjective but we can have a discussion about the style if you don't like it.

I've added a 3rd syntax that I know that many of us would prefer over any syntactic sugar where the compiler does the dirty work for us.

So here is an example to a class that does nothing *useful* but it's for the purpose of demonstrating the syntax. 

```typescript
class Message {
	constructor(public message: string = "Empy message.") {
	}
	
	public toLowerCase() {
		this.message = this.message.toLowerCase();
		
		return this;
	}
	
	public print() {
		console.log(this.message);
	}
}
```
#### 1st syntax (*at sign*):
```typescript
class Message {
	constructor(public message: string = "Empy message.") {
	}
	
	public toLowerCase() {
		@message = @message.toLowerCase();
		
		return @;
	}
	
	public print() {
		console.log(@message);
	}
}
```
#### 2nd syntax (*period*):
```typescript
class Message {
	constructor(public message: string = "Empy message.") {
	}
	
	public toLowerCase() {
		.message = .message.toLowerCase();
		
		return .;
	}
	
	public print() {
		console.log(.message);
	}
}
``` 
#### Notes
* When it's used before a variable it's going to be emitted as *this.*
* When it's used after a return statement then it's going to be emitted as *this*

#### 3nd syntax (*no this unless we need it.*):
This is the preferable syntax that we would like to write because it's close to how we would write this in other languages.

For this to be possible the compiler will need to be smarter so if *something* is not declared in the scope of the class/function then the compiler can assume we're accessing a global otherwise it can assume we're accessing a local and emit *this.* for it; if *something* is declared within a local scope but it also exists at the global scope then we will need to use the existing *this* keyword to access the local scope, once we use *this* to access *something* the compiler will assume that *something* without *this* is global and therefor it won't emit *this.* for it.

I'm sure that there are some challenges with this but this is really the desired syntax that many would prefer over any syntactic sugar.

```typescript
class Message {
	constructor(public message: string = "Empy message.") {
	}
	
	public toLowerCase() {
		message = message.toLowerCase();
		
		return this;
	}
	
	public print() {
		console.log(message);
	}
}
```

**Comment by lord-saumagen** [comment]
Dear Mr. eyalsk,

I'm sorry that I have to be the one who has to tell you. But 2 of of your 3 suggestions suck.
Your first suggestion (Using the "@" character) is a total disaster. Do you know where they did hide that character on a german keyboard? I bet not. I'm ten times faster in typing a "this" than entering the right key combination for the "@" character.

You second suggestion isn't much better. I can hear the programmers crying when they find out that the bug they hunted for days, was a tiny dot which they forgot somewhere in 5000 lines of code. By the way, did you ever try a search and replace for a dot? That's no fun, I can tell you that. If this dot has a special meaning in your code you have to do that some day. That's for sure.

So there is one suggestion left. (Using no this or that or whatever at all) That one looks fine to me. But as long as the 'this' keyword (the current context) is such a beast in javascript I don't expect that before the next millennium. But hey, there should always be a place for dreaming. 

Kind regars, Lord Saumagen

**Comment by eyalsk** [comment]
@lord-saumagen, you don't need to be sorry and if you read carefully, I intentionally used the word *can* and also noted that we can have a discussion about the style.

I'm not German so I couldn't possibly know anything about the layout of a German keyboard but if I was I'd probably picked something else that made more sense.

I agree that a period or at-sign isn't the most attractive and I might not be as creative as some people but it was just to have something instead of nothing.

I don't believe anyone in his right mind would use find and replace to change any code at this point in time! refactoring is much more reliable so I wouldn't worry about that.

Luckily TypeScript is a **superset** of JavaScript, so we can build concepts that don't exist in JavaScript and still emit valid JavaScript so I proposed two styles that *might* make sense and one that I know from experience that people would really like because it's closer to how we would write it in other languages.

p.s. Instead of telling me that my suggestions suck you could write about how you would improve them, you don't have to be rude.

**Comment by Pajn** [comment]
The third syntax would be a huge change in mental model.
Classes in js/ts is just a fancy syntax to put stuff on the prototype and the prototype is not in scope of the methods. By not requiring this the prototype would somehow look to be in scope without actually not being. That feels weird to me.

**Comment by lord-saumagen** [comment]
Dear Eyal Solnik,

I beg your pardon for the use of the rude expression. I didn't know that this expression might actually hurt somebodies feelings. My understanding of the English language is base on Hollywood action movies. May be that's not the best reference for a civilised conversation. 

My point is, that this feature you suggested wouldn't help anybody in anyway. (In other words, it's totally pointless.)

When you use a development environment which earned that name, you don't save that much typing.
I'll give you an example.

![untitled](https://cloud.githubusercontent.com/assets/9468599/9980588/2e414b1c-5f97-11e5-87b8-478f9c6904db.png)

So, its two keystrokes to type a this. First you type a "t" and than you hit the return or dot key. That depends on what you want to express. You can't shorten that much more. (Except for the two key strokes you still have to do.) Do you really think it's a good idea to add a compiler function to shorten that amount of work down to one key stroke? 

To be honest, I didn't type a complete keyword or classname for ages. Even the longest class name shows up after 3 matching characters. Code completion became my best friend. It did not only reduce the amount of keystrokes I have to do, it also reduced the amount of misspelled words in my code. 

How should a compiler function which can save you 2 keystrokes on only one keyword impress anybody who uses code completion? 

So you must agree that this is only a wast of time. You should try code completion yourself and you will see there is already a solution for your problem.

Kind regard, Lord Saumagen.

**Comment by eyalsk** [comment]
@Pajn, TypeScript already supports many things that are not part of the mental model that a typical JavaScript programmer understands, given that the programmer is programming only in JavaScript.

Many of the features in TypeScript, many of the features of ES6 and ES7 is already a huge shift in the mental model.

However, to programmers that are coming from other languages that supports multi-paradigms especially OOP it isn't so odd to ignore the *pointer* whenever it's redundant. 

What you're actually implying is that because classes are implemented through prototypical inheritance behind the scenes the programmer needs to use the exact same mental model but the truth is we shouldn't, unless again you're programming in JavaScript (ES5).

Now what I'm proposing is completely optional! if you will use *this.* the compiler will do the exact same thing as before, what I'm asking is basically for the compiler to be slightly smarter for these of us who want to *ignore* it possible.

Maybe we can add an explicit flag for it in the compiler for these of us who wants it.

@lord-saumagen, I understand, *no offense taken*. 

Okay, I understand where you're coming from but then when I proposed it I didn't really thought about intellisense and the amount of keystrokes but making the code more readable and reduce some of the noise that exists in the code.

A syntactic sugar usually means an *alternative* syntax or an addition to the current syntax not in place of the existing syntax, so you can always use the old syntax and it will work just fine!

I'm using many editors and many IDEs due to my work with multiple languages so I do know about code completion and intellisense but then again, my proposal is about making the code more readable, we can speak about the style to do it later.

I don't believe it's a *waste of time* but everyone is entitled to his own opinions, I have mine, you have yours. :)

**Comment by lord-saumagen** [comment]
Dear Eyal Solnik,

so it's not the keystrokes which give you that bad mood, it's a crusade against the keyword itself. (That's a joke). 

You are telling that you want to make the language easier to read and to understand. That's a noble motivation, but have you proof that reducing the verbosity, noise, ambiguity, redundancy or how ever you call it has that effect?

 Because every linguist in the world would tell you the opposite. The fuzziness and redundancy in human languages makes it easier for a human mind to understand a language. Because that gives your more options in the interpretation of a text or speech. New words are invented every day. Words come and go and some of them come back after ages. Others are in a constant change of meaning and every vocable can change it's meaning into the complete opposite depending on the context or situation it is used in. Even the grammatic, phonetic and the rhythm is changing. Human languages are in constant flux, but the human brain is able to handle that. 

But there is on thing a human brain can't do. As Wittgenstein pointed out, humans can only think of things they have a word for. The human brain needs words to focus thoughts, ideas, concepts or other abstractions. If you don't have a word for a thing or abstraction, you don't have a chance to get a grip on it. Your mind is simply not able to handle such a situation. That's the way a human brain works. 

So, if you eliminate the "this" keyword, you are also going to hide an important concept in the javascript language. That doesn't make it easier to understand the code. The opposite is true. Because without the keyword, you have to make assumptions about the current context inside a function class or program. But the anchor to fix that assumption and proof it is missing. So you will lose the track. You can't avoid that. As soon as the word leaves your sight, the abstraction it stands for is draining from your brain.

Programming languages are not made for machines, they are made for humans. A computer don't care what language you use to write a program. Computers interpret sequences of differences in electric voltage. 

Of course it seems to be a logical assumption that programs become easier to understand or read when you go to reduce the amount of sentences, words, characters or other building blocks of a language.  
But the human mind isn't working logical. That is the reason why your concept fails. You are ignoring the way a human mind works. You can't tell a story by simply listing the facts. There has to be noise in a human language, because that is the glue between the facts that give them meaning. What you are going to do is trying to make the language easier to understand for computers. But no computer asked for that. 

You may still disagree with my opinion, but at least you should look for a proof of your assumption. Changing the compiler because somebody things that may be a good idea is pointless. 

Kind regards, Lord Saumagen.

**Comment by kitsonk** [comment]
I think this proposal runs into some of the non-design goals of TypeScript.  In particular:

> 1. Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.

TypeScript is a superset of JavaScript.  Most of this proposal would be surprising to a JavaScript developer.  We have to deal with the reality of `this` in the underlying JavaScript and the way JavaScript behaves.  TypeScript tries not to break the way JavaScript operates, but provide a type safe way of which to develop JavaScript.

**Comment by eyalsk** [comment]
@lord-saumagen I'm not doing crusades here and I'm not against the keyword itself! you clearly missing the point of my post.

I don't need a proof to make a proposal, certainly not this kind of proposal, it bothers me that I know that the compiler can be smarter when it comes to again, do the dirty work for me and I need to type it again and again regardless to what you guys think.

It's plain logic, reducing the amount of repeated keywords in the code reduces its verbosity, you don't need to be a *genius* to know that although I agree verbosity does not necessarily mean readable code but in this case, in my opinion, it is.

I'm not eliminating or trying to eliminate anything, *this* still exists and you can still use it, what I'm proposing is completely optional! and like I said in my previous post it's possible to even add a flag to turn this feature for some of us who don't need the *pointer* to know where we are.

Please don't go off-topic here because what you said is purely philosophical and these discussions never ends, it's also not the place here, even though I understand what you're trying to say, it doesn't hold any water in this case.

I disagree with most of the philosophical things you said though because pardon my language it's *nonsense*.

@kitsonk, I don't think so because I'm not trying to mimic *exactly* the design of existing languages, I'm trying to relax the typing when it comes to the *this* keyword *whenever possible* in order to reduce some of the noise in the code and copy/paste JavaScript to existing TypeScript file should still work.

I wrote that the 3rd syntax is close to how we would write it in other languages but I never said it should or would behave the same.

**Comment by kitsonk** [comment]
@eyalsk I guess I am just wondering what the value is in making something more confusing to save 4 characters of typing which will have to be emitted anyways.  I am assuming you would propose what you are proposing as an opt in, which would make it only more confusing for those that choose to opt in and opt out.  If you propose it as mandatory, you will break just about everyones code and directly conflicts with TypeScript being a superset of JavaScript.

Option 1 directly conflicts with decorators.
Option 2 is confusing in my opinion.

Option 3, how do you propose to handle this?

```typescript
var message;

class Message {
    constructor(public message: string = "Empy message.") {
    }

    public toLowerCase() {
        message = message.toLowerCase(); /* which message? */

        return this;
    }

    public print() {
        console.log(message);
    }
}
```

**Comment by eyalsk** [comment]
@kitsonk, I think I've covered this in my post in case of ambiguity you will have to use *this* to make it work.

However, yeah, I see the place for confusion and even more when people share their code, if person A shares his code with person B and person B be didn't opt-in, it can cause some undesired side-effects so this feature need to be all in or all out to make it work and that ship has sailed long time ago.

*Admittedly, I proposed it to see whether people will like the idea or not, I didn't know people will take it so personally!*

**Comment by kitsonk** [comment]
@eyalsk I am not taking it personally.  Just because I don't like the idea and am trying to express reasons why I don't like the idea doesn't mean I am taking it personally.  Hopefully by asking peoples thoughts you didn't expect everyone to agree with you.

**Comment by eyalsk** [comment]
@kitsonk it was a general statement not directed at you, at all.

I don't mind people to disagree with me, in fact, I don't even mind to be wrong and I certainly respect people's opinion, so it's all good.

**Comment by DanielRosenwasser** [comment]
Thanks for the suggestion @eyalsk, it's always worth discussing. :smiley:
