### ISSUE TITLE
'await' has no effect on the type of this expression as compilation error

### ISSUE THREAD

**Issue by jozefchutka** [microsoft/TypeScript#48722]
# Suggestion

The compiler provides warning/quick-fix on hover on particular line, however it would be nice to have an compiler config option to fail on these across the whole project.

## 🔍 Search Terms

'await' has no effect on the type of this expression as compilation error

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Having a config option or such a rule by default would be helpful.

## 📃 Motivating Example

Having code strictly typed you can rely on helps you with refactoring. Recently, while working on a large codebase, I refactored a function which originally returned a Promise into returning a structure which contained the Promise somewhere inside (i.e. `{foo:"bar", promise}`). Now, around the codebase, in places where I originally `await`-ed the function result (Promise) I was now awaiting the new structure, which is wrong and Typescript does not help me much to spot it.

## 💻 Use Cases

following to yield compilation error ([playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true#code/BQQwzgngdgxgBMAlAXgHwG8BQcdxAdxAEsAXOARgG5MBfRJIA))

```ts
(async ()=>{
    await 1;
})()
```

**Comment by RyanCavanaugh** [comment]
Duplicate #35419. We don't consider this to be a type system error because it's a well-defined operation, and erroring on it would break union symmetry semantics for `Foo | Promise<Foo>` expressions

**Comment by jozefchutka** [comment]
Hi @RyanCavanaugh , whats yout take on provided motivatin example and how would you proceed in such cases?

**Comment by RyanCavanaugh** [comment]
I think the right way to address that would be #19255. It's the same general class of almost-error as `"foo".toString()` or `+alreadyANumber` where it's appropriate for the editor (or editor stand-in) to say something, but not proper for the type system to raise an error.
