### ISSUE TITLE
Typescript Quick Info Formatter Removes `parentheses ()` from declared type on hovering, for conditionally inferring types

### ISSUE THREAD

**Issue by ajitjha393** [microsoft/TypeScript#48729]
# Bug Report

Typescript Language Formatter function removes `parentheses ()` from the declared type on hovering over it.
Not a bug with the Typescript parser itself.

### 🔎 Search Terms
infer, conditional typing, parentheses, hover

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about  parentheses getting removed for conditionally inferring types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?isolatedModules=false&ts=4.6.2#code/C4TwDgpgBAKghgSwDYB4ZQgD2BAdgEwGco5cQBtAXQD4oBeKACkYDo3gAuWASntoDcA9gny8sOAsUYBYAFBQoACy6kQAGjkK2LAE4RCnKAlwAzCDqgAlObzoDh+TVAD8Vp11wR+5gNxz-snJAA)

### 💻 Code

![image](https://user-images.githubusercontent.com/42679346/163672806-b9a3443e-8913-479e-8140-c04d5577d27d.png)

```ts
type Tail<T extends any[]> = ((...t: T) => void) extends (
  h: any,
  ...rest: infer R
) => void
  ? R
  : never;


```

### 🙁 Actual behavior

Wrapped `()` gets removed on hovering from the declared conditional inferring type.
Because of this the hovered type shown is not the same as the declared type and they are not interchangeable and can cause bugs. 

Without parenthesis, the TS parses it as `a Type which returns a Function and the return type of the function is that conditional "void extends ..."` which is not what was declared.

Example - 
![image](https://user-images.githubusercontent.com/42679346/163673203-298fa7ba-c1ed-4b38-8f1e-019f9504101f.png)

### 🙂 Expected behavior

`()` should be preserved and shown while hovering so to prevent the errors that can arise because of missing `()` in the conditional inferring types

**Comment by RyanCavanaugh** [comment]
It sounds like you might be writing a tool that's taking some incorrect assumptions on how this can be used? FWIW text returned by quick info is not guaranteed to be something you can paste into a file. For example, we might in the future use placedholder text that is not legal code.

**Comment by fatcerberus** [comment]
To be fair, as long as what the quick info is displaying *is* syntactically valid, it probably shouldn't change the behavior of the type, otherwise you're asking a human to parse valid code differently than the compiler would, which is confusing.

**Comment by ajitjha393** [comment]
> It sounds like you might be writing a tool that's taking some incorrect assumptions on how this can be used? FWIW text returned by quick info is not guaranteed to be something you can paste into a file. For example, we might in the future use placeholder text that is not legal code.

Actually, I was moving the type definition from one file to another, so while hovering over the conditionally inferring type `Tail<T>`
I noticed that wrapping parenthesis was not present, the rest were the same 

Hence my obvious conclusion was maybe both are interchangeable so I tried removing it from my actual Tail definition and there wasn't even a syntax/type error 

I tried variadic tuples and extracting Tail and then I was able to narrow down the error to this Missing parenthesis and how the TS compiler sees it differently 

So I think as long as it is a valid TS syntax, quick info should resolve to the same or equivalent type!
Whereas in this case, the quick info type got resolved to `never`

**Comment by ajitjha393** [comment]
@RyanCavanaugh can you guide me on where does this transformation from type to string code might be happening that's used by quickInfo or any other pointers I should look into?

Maybe I can try to investigate it and fix it.

**Comment by DanielRosenwasser** [comment]
This was fixed by https://github.com/microsoft/TypeScript/pull/48112, but thank you @Andarist for the test case!
