### ISSUE TITLE
Types Wrongly Inferred as `any` and `never`

### ISSUE THREAD

**Issue by jeremybanka** [microsoft/TypeScript#48727]
### 🔎 Search Terms

- Call depth
- Depth exceeded
- Maximum depth
- Argument of type 'string' is not assignable to parameter of type 'never'.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about call depth

### ⏯ Playground Link

[Link](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220415#code/JYWwDg9gTgLgBAbzgJQKYGMLADYGUYCGMqANHACpQEB2AzgejMBNQJLXFQBmDqA+gFUAcrnIBBAEIAZAKJwAvnC5QIIOACIoGLNnUAoUJFiI4RVWTMgAYgRA4AnmQCutVGkw5KNeo2bVBIuLScorKqhpaHrp6egD0sQD1SckpqWnpGZlZ2VnxcbFwhUXFJaVlhcgyAMIA8qxScALk9azNMrjlnV1FefF8-QODQ8Mjo2PjE+N5eqgAHkbwMPZgqCjaOPhEqDZ22PYAPLhkANIAfHAAvHAAFGAEVCAAXHDHAJSX5+46m8SHpzFzBZwJYrChUOgMJgsGorKhQ6j7PSFMTIADilzgTmoABNUFxgNRUNiSEiUDJyAJkEIMQA3LDEvTnK4o9FzYg42iYnF4glE0kAfhuMHBPhg0Fozy8EN8LHYnB46H4wlEklk7wun3JlKEpOe12F3kh4slIshfjlqG4vACKuCFigAHMnCBUBxniz1ZqKVSYoUQasALJObBMGBOXEw+G0P4YhCkwoAa1Q9metGFBId8bguJ4wZgzw6AB8btdPXBcK9SfJSYDoItloG88Aw7jDicMWmoBmmXAANpZ-E4n6oZ5fDaEYg7Bxtl6nEnFAm42aj9Z4CeofbHXsAXTnpO3pJr8zrcEwdHgICbLdWV325HbbNd2M51GdACNLXBi53u9c48Uk0cLMcwIPNnhAvNIz8ecFGeIMQ2bcNUCglho3IU5Xjgq8kLvE4mXOf8ijPNM4EXOYMUsTcd1OP8s0TZNngAAwAEgQQD5HYJdGJg4oIJDZ4dx4hRK2KYj4EHbFhwosVrFsad71nWjSkAoTCj4-NszxUCQxQ6hVLgeI4DxLgMBgCUbjuB4y17AALYA02gewZC4EzGGuFi2OTRRWMs2x5EY15tyE+QRKKLQwygag+wk4cyDI2YD0Kat8hyVK0vSjK0l6ApulyspURkIQZGQVgqkEZopFaVh2jy2qDNifJJia5qWta4ZpjE7NgEVDFrlJGyIAAdwDGh7BsRVOSuAAmGCBuG0aABFupvOAAEYYPBbFwiuEaYBsgA6TbzD0TC4FfEAPygD5EFJTqVGwbBerLXaDsVHBriOkBSzgAAqOA5pG6gxt4WhK1JbBUHgB0VFoSa4Hu7BS3ByH4YgB64dW304EGuyIZuBHOX2f6hsB+wlsVd5CMKaGIFhuAAGorgRpHigJhmrkxpKsfCpxIrgGnYb0ZL4ky0WxfFpJsrq6XigKmoA3JZAAE0Zel7K2o1zWtf6aZa2Mf1y3QAgIam7FY1JQbnnOy7+qt99LSFgFj31hs4AABSwDhTfNwplzO+2oFJFN-Yuh3kr1+tQVwVAHRdL2zauQjqAgXFVuAbFU3TahM0KZPcSm9PM67bPHZmZ3I9WD29gdFhvcT0k89QVhnyLjMd1LiPSI4S0FVWdxCGzk2zcfDl3c9mBTbIXAjaHm7CigO3Q8D8Py+BV2hBT1A67HgkJ+xMugQNmRsQdLeE-LGO473g+TwN8az4xKv7Br6hTadoFOtPmBkBoLaQA93eT1ngAPjtdJScA-bYmWtcQai4hr7QJISKAAAJVAwAHQ2RgK8GCwcoGKhgXAwaCDqBINQegzB2ChZgxFhLWhdDMhS1VnlZANQahWD4AtdorBUTUiYXldW2tBFCLGLrVeBtkAQAgFwY+p9yCuyuIxVABAaSoEYl+OAjE7JgDUcWRiVAkw6I0V2E+qj1GMRpMbCG9hGLvxPLvHuvAUCSOkSYoysx2TPjgDIh+hEiSyIbKOZx3i5GgmLK+B6pIpFcFcBpa2YdbHGHsVaHqbsaCoEeiPTx-caAOlnoRQyNlYiDS7nAF0nBaCkkLnAH8JdCj2TEL4FRzw3ySIhjQDuYjXYyAhlfOGhEhA1E4c8De+d96FBkAtAqgSpHeNJG7MQRUpDALSdgR2ncDZiCBt01AV8hC2BWoBKRXiemujMjEGh9DLmXMYXw3KYgqjNBqCIW5tUBHCPee80Rh9XYNPhCElajEqiVDEOQGQhjGKcNkKC8FAg3YLRBWCm+LtQS-L8NGKwYgAz1CVnwIQmK5CZM5DUh0ZAMVYqkDihWAYJDFR7IRIFMgEXPCpmvFYTEGUIpscUHguxg5kuxbi-FWYqnEqrKSSF5IZDMqzP6JiEroUDjknsZ4-KKWCoVsKjO1Ss45wUKSWF8LQXSuKLKjRBrOWKt5SqzFAq8UaoXFq0VxQ7j2GwBAAgWrUmwGAMbfYqrKUyGpbSsV1Z1k-JlNQKw0A+CIkKP69VNVCXauLiS0k8aqU0uQBiLECZk6DT0mmm1lVE3uKfJyL4UBsSxqKPGu17QhLXBFTqssY41xbD9UWgNQbkD-EKD2CtVba34qODcJtKaW2rmHB28lXbM2nD3HS0kvYh0KxKSu9o253QRvRZ2hNpKi3VVwMu3ddbdxrM6SiiNUaoDkBsqgbZV8px7D4BiVFLBr0xsOVwY5OzTm0DIA+v9-ww2ghGagN91ByAQBfcyK90Bb33pORwJ99g+C9kYgMzhjEDwgdWAIaguahrUEAxwCDUGYNwAg9ehDJGYAobQ5spySGYB7JdDhi9eGCN5uoFR6A+HCP5toxifj3HaNkeg72MjDYDwpSuXJ2hNyXndBVKCpTuU3kfM01rL5J5Oq9gkmB2KZ1N6cTmNuDEl4ELXn2GByeybfyEUAkxRu3FSTqT1GWL+P8cSqBATAUsJIQoJPgJ1Ru0cIYRqklcSi0cYD7GJfO8BTmNFhfSaZPwrm1JaTAmdVAxTYsBaocF08qF4Bu2QWIXANUrjoZqE4GA2BeTcQ0W7bAvAr7YdMJyMSSKK7uxsgQVwGJ-RHPK5V9ovY4lQHYx-UrcAwADdcMOPgrAhCgqpGIBo0WZL7Ddot1ANFHMMQ0Qtwb-BVvrbxVITLmlcz8Ra21xUHXAtg07p1AzeWIO0Ci6YGSKHq0iaI7xqAgPBPMZ3Oo8J2AYJ7bO4yJLx3GJMBdI1wkfBCSDS+zd9z-sHovfOYkeTRPRaKbU8UGobtiogtYE8joZPyiGUAMrkgB1ckalp9nGsdPItWAtKgDpyD3C-hiGQsx0DYBwox2jrHSAaImQVRi-xeslfPNq+4MAAwQCaWCQ0EaYSWiIH4fYvOCD88F5DHsfVChM4oHZTkX9OSMVGmo-0ZA3z1dMOgTAlaMzAggNr6U8I9dwmgnAUkhkijNk5AbWgA1gxmw-BoqUopzTd2SUqQIqpEV+lNIwcUMFre3vsqYbAtA-f240U71lMu3fwGbHACATgMGLD9wniFfOBeOkhmotz7ezcwBJGWQinUkBfzIDEhQw2c9iigBUwooXN7hfSywDEX9ripYi-CYcoV5+4mbnDMQUAqD2H2mEL66+l-UG33NjHX3nig543BkHXGiO0Yh1cRue-9ogAIGAS3RRG3YinRgbiZoaMTmrQrmYag3Asp+gBJmpwqcr6Q8oOBMSYZgr6SGTM5eKH7QDPB0T1TFD-JwAADkOa3GxBpEL4EA8Ag2tA6C1ABAb4eMYoVeJBxKxB+0+B4efotA1wU0AAzFNFNKFA6vpC6m6h6s8KvgZgvuuAAa8JQsUCFDBFfirqdkNlcKvuoagMthdsVFdqoSRDftuj9h9pjiYXIdoaFDEmvp9hYVsGQMYVGJWMLITsTu4alKTvTqUMgqwscHTt4SUJgWzhzqEU1FziFnNi4DoYQLABriokAnAAAGr0hWBYgRofCkjRGtpJ5mgsA2hBCyDXD6hT7ihljfRQEsqYHYEqALxZjcGUaOjOinL17foGzEHsGUHGY0Gwz0GMHMF+6+RlKfhHLtGEgqJQAcH1E5Q8F8H8EAAsAArCIarnEZrqgCUTrtPv+homgQFKHklK8EAA)

This is the abridged content of several files in one example. I have inserted section labels to try to make reading it easier.

### 💻 Code

Below is the relevant section from the example, where I am seeing errors.

```typescript
//¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯//
//                                OPERATIONS                                  // ❓❗
//____________________________________________________________________________//

export type DragTarget = Exclude<AnyElementName, `EDGE`>

export const startMove: TransactionOperation<DragTarget> = (
  // ❓ This gets `any` type, but according to TransactionOperation, 
  //    its type should be `TransactionInterface_UNSTABLE`
  transactors,
  // ❓ This also gets `any` type, but it ought to be `DragTarget` 
  dragTarget,
) => {
  const { get, set } = transactors
  const nodeSelection = get(nodeSelectionState)
  const nodeIds = Array.from(nodeSelection)
  const newActions: UnknownActionForUnknownElement[] = nodeIds.map(
    (id): NodeActionTo_[`UPDATE`] => ({
      type: `UPDATE`,
      family: `NODE`,
      // ❗ Error: 
      //    Type 'unknown' is not assignable to type 'string'.
      //    ts(2322)
      id,
      payload: get(findNodeState(id)),
    }),
  )
  const phase = get(phaseState_INTERNAL)
  const newActionsState = findNewActionsState(phase)
  set(newActionsState, newActions)
}

//¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯//
//                                     HOOKS                                  // ❗
//____________________________________________________________________________//

export const useStartMove = (): VoidFunction =>
  useRecoilTransaction_UNSTABLE((transactors) => () => {
    // ❗ Error:
    //    Argument of type 'string' is not assignable to parameter of type 'never'.
    //    ts(2345)
    startMove(transactors, `NODE`) 
  })
```
### 🙁 Actual behavior

- The type of `transactors` is inferred as `any`
- The type of `dragTarget` is inferred as `any`
- The supplied argument `"NODE"` is not assignable to the second argument in `startMove`. TS unaccountably expects the type `never` for this argument.
- There is no further explanation for this behavior.

### 🙂 Expected behavior

- The type of `transactors` should be inferred as Recoil's [TransactionInterface_UNSTABLE](https://github.com/facebookexperimental/Recoil/blob/main/typescript/index.d.ts#L139)
- The type of `dragTarget` should inferred as `DragTarget`—given in the example as `Exclude<AnyElementName, "EDGE">`—which means `"NODE" | "PANEL"`
- The supplied argument `"NODE"`should be valid the second argument in `startMove`.
- If I have reached the depth limit in TypeScript, I should get an error explaining this.

**Comment by whzx5byb** [comment]
```ts
export type TransactionOperation<
  ARG = undefined,
  RETURN = void,
> = ARG extends undefined
  ? (transactors: TransactionInterface_UNSTABLE) => RETURN
  : (transactors: TransactionInterface_UNSTABLE, argument: ARG) => RETURN
```

It is not recommended to write function signature like this, because `ARG` is lazy-evaluated and the compiler doesn't know which branch to choose to infer argument type.
Instead, you should write:
```ts
export type TransactionOperation<
  ARG = undefined,
  RETURN = void,
> = (transactors: TransactionInterface_UNSTABLE, ...rest: ARG extends undefined ? [] : [argument: ARG]) => RETURN
```

**Comment by jeremybanka** [comment]
> It is not recommended to write function signature like this, because ARG is lazy-evaluated and the compiler doesn't know which branch to choose to infer argument type.

I'm impressed, @whzx5byb! Thanks for the great advice!
