### ISSUE TITLE
what js file package order base on?

### ISSUE THREAD

**Issue by lusess123** [Microsoft/TypeScript#4872]
in vs2013, we  set Combine Javascript output into file  ,
my question is: what  each js file  order base on ?

**Comment by DanielRosenwasser** [comment]
My understanding is that your `tsconfig.json` or your file list in your project file will be processed in that order. If any of your files have a `/// <reference path="..." />` and the referenced file has not already been specified, then those referenced files will be concatenated before the contents of the current file.

**Comment by danquirk** [comment]
Correct. One last alternative is including a file named _references.ts in the root of your project directly with the set of /// references you want.

**Comment by mhegazy** [comment]
@lusess123 you might find my comment in https://github.com/Microsoft/TypeScript/issues/1066#issuecomment-61862011 has some more information; specifically the "Ordering output with --out" section.
