### ISSUE TITLE
Turn skipLibCheck on by default

### ISSUE THREAD

**Issue by astaninger** [microsoft/TypeScript#48737]
Turn skipLibCheck on by default

**Comment by JustFly1984** [comment]
That is actually a bad idea. I really want to know if there is some issues in dependencies by default as it is right now.

**Comment by Josh-Cena** [comment]
https://twitter.com/SeaRyanC/status/1515465823585902593

:(

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
