### ISSUE TITLE
Commit behavior is very awkward when navigating to beginning of word and entering quote

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4873]
1. Type in "function" in a place where it is a valid completion item. Do not dismiss the completion menu at any point.
2. Press `Ctrl`+ :arrow_left: to go back to the beginning of `function`.
3. Insert a `"` character.
4. End up with `function"function`.

![commitbehavioriswonky](https://cloud.githubusercontent.com/assets/972891/9974938/c4938c64-5e5d-11e5-9570-a672faf57a7d.gif)

**Comment by mhegazy** [comment]
looks like https://github.com/dotnet/roslyn bug. please refile.

![completion](https://cloud.githubusercontent.com/assets/8000722/10325669/4b947816-6c48-11e5-9eea-60275144eff6.gif)

**Comment by danquirk** [comment]
Gonna leave this open until it gets logged on the Roslyn side so it doesn't get dropped on the floor. @DanielRosenwasser please link the issue into this thread and then we can close this one.

**Comment by DickvdBrink** [comment]
Ah lol, I had this behavior multiple times but didn't know what triggered it xD Really annoying bug though; would be very happy to see this one fixed in a vs update!

**Comment by DanielRosenwasser** [comment]
The Roslyn-side issue is tracked by https://github.com/dotnet/roslyn/issues/5487

**Comment by danquirk** [comment]
If we're sure we'll get the fix here for free from Roslyn we can close this.

**Comment by DanielRosenwasser** [comment]
I don't think we will; I think it depends on us re-interpreting the behavior of where a context token and the current token are different.

**Comment by danquirk** [comment]
Ok, then we'll leave this open and I'll remove the External tag

**Comment by mhegazy** [comment]
closing in favor of dotnet/roslyn#5487.

**Comment by DanielRosenwasser** [comment]
Luckily this has a fix out for review.
