### ISSUE TITLE
Bug in  processing `@typedef` declarations

### ISSUE THREAD

**Issue by jackens** [microsoft/TypeScript#48738]
# Bug Report

### 🔎 Search Terms

`@typedef`, `.d.ts`

### 🕗 Version & Regression Information

Tested with Playground versions `4.6.2`, `4.5.5` and `4.4.4`.
It is probably present in earlier versions as well.

### ⏯ Playground Link

<https://www.typescriptlang.org/play?removeComments=true&target=99&filetype=js#code/PQKhCgAIUgBAXAngBwKYBNUDNIG9dQySQDaAlugFyQDO8ATmQHYDmAutSQGICuTAxvDIB7JgBpIvAUNFsA3IUgBfJZABKqGsIA2AN1QaAVqkEBZAIbJCwcOG2p4kCpAC8kAAy3QEaHGTn6cwBbPA0tPQNUYzNLVQALcyZ0e3oaRVh6Bx56Jho8AAV6YSCyGlQAHkTEAD4la3B+UTpaVCTXSASklLyXasgmVAB3SELi0tQACgnM8P0JTOj4AEpXPoJiTuTUVJIAal2KNnaSGZ05yAWTeDZwJSXwIA>

### 💻 Code

```js
/**
 * @typedef {{
 *   [id: string]: [Function, Function];
 * }} ResolveRejectMap
 */

let id = 0

/**
 * @param {ResolveRejectMap} handlers
 * @returns {Promise<any>}
 */
const send = handlers => new Promise((resolve, reject) => {
  handlers[++id] = [resolve, reject]
})
```

### 🙁 Actual behavior

The generated `.d.ts`:

```ts
declare let id: number;
declare function send(handlers: ResolveRejectMap): Promise<any>;
type ResolveRejectMap = ResolveRejectMap;
```

### 🙂 Expected behavior

The generated `.d.ts` file looks like the following:

```ts
declare let id: number;
declare function send(handlers: ResolveRejectMap): Promise<any>;
type ResolveRejectMap = {
    [id: string]: [Function, Function];
};
```

**Comment by MartinJohns** [comment]
Simplified example:

```typescript
/** @typedef {{ [id: string]: Function }} Test */
```

The error seems to appear when `Function` is used as the member type of an indexed type.
