### ISSUE TITLE
Improve error message when awaiting a promise that is setted in a switch statement

### ISSUE THREAD

**Issue by ElianCordoba** [microsoft/TypeScript#48732]
# Bug Report

### 🔎 Search Terms
- await promise switch 
- await promise default
- promise is used before being assigned 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsIwLbFRACgDdgAbBAUwC4YRkAnfAcwEoYBvAKBh5lIuQwADvXTZUIajAAKo8ZIA8wCGAB8Abk7deIAO6pkUABYEGlNl15WYUUBRgly9gLyuYAcjjp07qtuvWImISLjJyIQB09BQg6KREFAQsmgEBAEbRwADWKan+1raSDmSUMK7OHmnA9L75qcLhRRWywZJRMXEJSbn1PBkU2Zp1vAD0IzAAwmLYFBCCyEb2ACYUcMAIpIJppOhQWTDI6AeMTEwU9AeLMOeiFzMgIMBnwzwraxvIfr28QfKhLX92rF4olki9rP1BvkAL5aKzAXR4QS-EKcaFAA)

### 💻 Code

```ts
async function main(value: string) {
    let promise: Promise<any>;

    switch(true) {
        case value === 'foo':
            promise = Promise.resolve();
            break;
        
        case value === 'bar':
            promise = Promise.resolve();
            break;

        // Comment the default block to trigger the error message
        default:
            promise = Promise.resolve();
            break;
    }

    await promise
}
```

### 🙁 Actual behavior

The compiler is right about preventing you from awaiting in this case, since the default branch is not covered, but the error message is unintuitive.

### 🙂 Expected behavior

A more specific error code.

**Comment by Josh-Cena** [comment]
It looks pretty specific to me? `let promise: Promise<any>;` means you have declared the variable but haven't initialized it. If the switch is exhaustive, it will be definitely initialized and therefore `await`able, but if the `default` (or any other potential case) is not covered, `promise` may be `undefined`. This will be the same for cases like:

```ts
let a: string;
if (Math.random() > 0.5) {
  a = "foo";
}
const b = a + "a";
//        ^ Variable 'a' is used before being assigned.
```

**Comment by ElianCordoba** [comment]
Yeap the `Promise.resolve()` was just an example.

The error may be clear (not a lot in my opinion) but it could be improved. Instead of the generic uninitialized error, if you (only?) assing the value in a switch statement _that is not exhaustive_ you could get a recomendation like you see when you forget the await keyword on a if statement.

**Comment by RyanCavanaugh** [comment]
I don't see how to make this clearer in a way that adds more signal than noise without being extremely overspecific. The only thing the control flow analyzer knows is that there is *some* path from the usage to the declaration that doesn't pass through some initialization. You could equally have written
```ts
let foo;
if (something) {
  // 
} else {
  switch(...) [
    case x:
      foo = n;
      break;
    case y:
      // etc
  }
}
if (something else) {
  foo = m;
}
foo();
```
where it's not really clear where the "missing" initialization is. Obviously we can construct examples that are clear from *intent* where the mistake was, but it's not really generalizable.
