### ISSUE TITLE
[4.7-beta] Parsing failure for arrow function expr in conditional expr

### ISSUE THREAD

**Issue by sosukesuzuki** [microsoft/TypeScript#48733]
# Bug Report

### 🔎 Search Terms

- `conditional`
- `4.7 beta`
- `syntax error`

### 🕗 Version & Regression Information

- ~~This is a crash~~
- This changed between versions 4.6.3 and 4.7.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220416#code/BQMwhgNgzgpgBAfjsADmATmAtgSgFxxQAu6AlgHYDmcAvAHxxqZZwFzkCuEEOA3AFBA)

### 💻 Code

```ts
(false ? (param): string => param :  null);
```

### 🙁 Actual behavior

Parsing failure for arrow function expr that has type annotations for return type, but doesn't have type annotations for parameters, in conditional expression.

### 🙂 Expected behavior

Parsing successfull.

**Comment by MartinJohns** [comment]
> This is a crash

I can't reproduce this. Neither locally nor in the playground it crashes.

**Comment by sosukesuzuki** [comment]
> I can't reproduce this. Neither locally nor in the playground it crashes.

Sorry I forgot remove this from template.

**Comment by mcdonaldjc** [comment]
The OP's statement is accurate as the playground proves that there are no parsing errors in the version he mentions. However, if it helps resolve the problem, changing his code as follows resolves the error in the current version, leaving you with just the **any** type inference for **param**.

`(false ? ((param): string => param) :  null);`

**Comment by RyanCavanaugh** [comment]
I'd like @jakebailey to confirm but this seems like it might be intentional. Your code might terminate at the legal JS expression
```ts
false ? (param) : string
```
so parsing the `: string` as a type annotation might require "too much" lookahead.

**Comment by jakebailey** [comment]
No doubt this is #16241 / #47550, yes. The reason why the workaround in https://github.com/typescript-eslint/typescript-eslint/pull/4829 works is because the parser can see the `:` inside of the parens and says "that's definitely a parameter", and allows the colon before the return type.

When the (what I can only describe as) heuristics don't "prove" that it's an arrow function, my change disallows the `:` when parsing, preferring it to end the conditional.

The test case in the issue is similar to [one I wrote in my PR](https://github.com/microsoft/TypeScript/pull/47550/files#diff-a24856f00a74a5968f97ef389cac5b81a84f0ccaa269186d575b5a6a072dfd67).

I'd have to think about how I might fix this; the "heuristic" I described previously mainly checks things to do with parameters. It doesn't go and parse all the way past an error expression.

The gotcha with lookahead is when conditionals are nested, though I can't seem to produce an example that actually parses in JS. I thought the following would be a counter example, but this fails to parse when I run it in node.

```
true ? false ? (a) : b => c : null : null
```

**Comment by jakebailey** [comment]
Regardless, I think all of this is going to have to be figured out for the types-in-JS proposal, since all of these parsing choices will have to be made and our parser changed to fix any differences.

**Comment by sosukesuzuki** [comment]
FYI here is a case of how this bug caused problems in a real product https://github.com/typescript-eslint/typescript-eslint/pull/4829/files#diff-d9d4dc5af184a093e1caab204aa0ed6da56d008309ff90294561a64bec2e6663

**Comment by jakebailey** [comment]
@sosukesuzuki Can you try taking a peek using the build on my PR here? https://github.com/microsoft/TypeScript/pull/48788#issuecomment-1104516003

**Comment by jakebailey** [comment]
To link it here, here are various variations of "fixes" to this:

- Permissive (#48788): [Playground Link](https://www.staging-typescript.org/play?noImplicitAny=false&target=1&ts=4.7.0-pr-48788-2&filetype=ts#code/CYUwxgNghgTiAEYD2A7AzgF3lAXNlAngDTwBGeUhJYFV8wtx8IjJAZq-AOacAWjAbgBQGAgAcEUeAF58BAfFESyMuQqUIwqyvMXiEwbYXX7mR3RvhtzJ5Vxt7lvG0KEB6N-F4YMYtDg8uAEsMXgBXUgA6ZABbNxigsBgkNCQ2DDcAFX0AZSSgsQyxMIgINwAWAA4AdkrK1w94TN4QNAQMVow0LygANwRSEBAUeAB3GBCOkbC0IJR7WfmIBGWfEBh4FCgY1vxgd08QAA8MGCk0MSgwXYwkeDE4fpQsW7uYsLBnUiCobrmvJCjRQtAjYODwOBQYCRVxSAD88AAFKQAJTwPBaaQAPnowiE8KRqPRiBkOMRwDReAQ2KseIJpHgCK0eHJlLMNLYdMZhLRNMRYDZhhpIC5CMRvJxDPFxOlGNJuNhSLRYvIiBIwDhVJReGsNPssq8op5xMxOMMVKNDLFAuJQpxCB1xK4AiAA)
- Strict (#48791): [Playground Link](https://www.staging-typescript.org/play?noImplicitAny=false&target=1&ts=4.7.0-pr-48791-5#code/CYUwxgNghgTiAEYD2A7AzgF3lAXNlAngDTwBGeUhJYFV8wtx8IjJAZq-AOacAWjAbgBQGAgAcEUeAF58BAfFESyMuQqUIwqyvMXiEwbYXX7mR3RvhtzJ5Vxt7lvG0KEB6N-F4YMYtDg8uAEsMXgBXUgA6ZABbNxigsBgkNCQ2DDcAFX0AZSSgsQyxMIgINwAWAA4AdgBOAEZXD3hM3hA0BAx2jDQvKAA3BFIQEBR4AHcYEK6xsLQglHt5xYgEVZ8QGHgUKBj2-GB3TxAADwwYKTQxKDB9jCR4MThBlCx7h5iwsGdSIKhehZeJDjRRtAjYODwOBQYCRVxSAD88AAFKQAJTwPBaaQAPnowiEiJR6MxiBkeORwAxeAQuKsBKJpHgSK0eEp1LMdLYDOZxIxdORYA5hjpIB5SOR-LxTMlpNlWPJ+PhKIxEvIiBIwARNLReGsdPs8q84r5pOxeMMNJNTIlQtJIrxCD1pK4AiAA)
- Strict only on the left (#48792): [Playground Link](https://www.staging-typescript.org/play?noImplicitAny=false&target=2&ts=4.7.0-pr-48792-5#code/CYUwxgNghgTiAEYD2A7AzgF3lAXNlAngDTwBGeUhJYFV8wtx8IjJAZq-AOacAWjAbgBQGAgAcEUeAF58BAfFESyMuQqUIwqyvMXiEwbYXX7mR3RvhtzJ5Vxt7lvG0KEB6N-F4YMYtDg8uAEsMXgBXUgA6ZABbNxigsBgkNCQ2DDcAFX0AZSSgsQyxMIgINwAWAA4AdgBOACZXD3hM3hA0BAx2jDQvKAA3BFIQEBR4AHcYEK6xsLQglHt5xYgEVZ8QGHgUKBj2-GB3TxAADwwYKTQxKDB9jCR4MThBlCx7h5iwsGdSIKhehZeJDjRRtAjYODwOBQYCRVxSAD88AAFKQAJTwPBaaQAPnowiEiJR6MxiBkeORwAxeAQuKsBKJpHgSK0eEp1LMdLYDOZxIxdORYA5hjpIB5SOR-LxTMlpNlWPJ+PhKIxEvIiBIwARNLReGsdPs8q84r5pOxeMMNJNTIlQtJIrxCD1pK4AiAA)
