### ISSUE TITLE
"Indexed access types which immediately index into a mapped object type" infering improvement is unsound

### ISSUE THREAD

**Issue by jfet97** [microsoft/TypeScript#48730]
# Bug Report

### 🕗 Version & Regression Information

When did you start seeing this bug occur? From `4.6`, in which indexed access inference [was improved](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/#indexed-access-inference-improvements).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/JYOwLgpgTgZghgYwgAgCoE8AOECydPIDeAUMmcgEQgCuAtgEbQUBcyND0A3KeRQM5gooAOYtkAoSGHdylegHt5AGwhwQYhctUhuAX2LEwWFAFUQweSABKEBPKgATADwAFZBAAekEA77IA1hDo8jBoxniYAHzIALxEyADaANLIoMguALrMPGQksrL+oA6sSTL5ZABurBjYEckZZeUwrAAUmNXh+PUAlLHRFfLADo3I+roJmdzEMNQgCGAWIMiYUPJIfHw2do58Time3r4BQSFhtfiRLVC29g4AjKxmi1u3e5EANMjX2w4ATI-mSwvRxvXp5cjfW53AB0MCuN0cv2hFW6egMKzWEA2wN8LXBZEKPlY-EEIgo7xyyCqlAAFhAlEp5ABCcmU5pUuBKPpESmyOwgPhaaGM4QtCqc6FgeQmTDYKAAYTgfAgLW6qMpY0++ICRWJ7EYUFZsmpd1+AGYKbJ2eKuTFotq+ZZBSphfJRTbJfIAKIeTCWCDgYCclpmtUjMbdIA)

### 💻 Code

```ts
interface TypeMap {
    "number": number;
    "string": string;
    "boolean": boolean;
}

type UnionRecord<P extends keyof TypeMap> = { [K in P]:
    {
        kind: K;
        v: TypeMap[K];
        f: (p: TypeMap[K]) => void;
    }
}[P];

function processRecords<K extends keyof TypeMap>(record1: UnionRecord<K>, record2: UnionRecord<K>) {
    record1.f(record2.v); // <-- this is bad
}

processRecords({
    kind: "string",
    v: "hello!",
    f: val => {
        console.log(val.toUpperCase());
    }
}, {
    kind: "number",
    v: 123,
    f: val => {
        console.log(val.toExponential(3));
    }
})
```

### 🙁 Actual behavior

The code typechecks, but it breaks at runtime: `TypeError: val.toUpperCase is not a function`.

### 🙂 Expected behavior

I think `record1.f(record2.v);` shouldn't be allowed. 

### 🗒 Notes

I understand that the type parameter `K` isn't behaving like an existential type, so the correct way to type `processRecords` may be:
```ts
function processRecords<
    K1 extends keyof TypeMap,
    K2 extends keyof TypeMap>(record1: UnionRecord<K1>, record2: UnionRecord<K2>) {
        record1.f(record2.v); // <-- now this is an error
}
```
[Playground](https://www.typescriptlang.org/play?ts=4.6.2#code/JYOwLgpgTgZghgYwgAgCoE8AOECydPIDeAUMmcgEQgCuAtgEbQUBcyND0A3KeRQM5gooAOYtkAoSGHdylegHt5AGwhwQYhctUhuAX2LEwWFAFUQweSABKEBPKgATADwAFZBAAekEA77IA1hDo8jBoxniYAHzIALxEyADaANLIoMguALrMPGQksrL+oA6sSTL5ZABurBjYEckZZeUwrAAUmNXh+PUAlLHRFfLADo3I+roJmdzEMNQgCGAWIMiYUPJIfHw2do58TkkAjO5eED5+gcGhNbj4ADTISQBMR96+AUEhYbX4kS1QtvYOfasMyLLYAvb7SJ3P7bBwPYHmSxgxx7B6RXp5cgwgH7AB0MF+-0cD1xFW6nGQAHpKcgnABaOlseQAd2QYAAFsA-FzkGp3FBVlBiPpiCs1hANsjfC1MWRCj5WPxBCIKDccsgqpR2RAlEp5ABCVXq5oauBKPpEdWyOwgPhaXF64QtCpm3FgeQmTDYKAAYTgfAgLW65PVYzusoCRUV7EYUCNsk1+weAGY1bITS7zTFohHrZY7SoHfInZm3fIAKIeTCWE4LM0tZPBkZjbpAA)

I think that the main problem here is that the original definition:
```ts
function processRecords<K extends keyof TypeMap>(record1: UnionRecord<K>, record2: UnionRecord<K>) {
    record1.f(record2.v);
}
```
may suggest that the two nodes are related, because this whole feature was added to express correlation between things. But that may not be the case.

And what about a more general one?
```ts
function processRecords<K extends keyof TypeMap>(records: UnionRecord<K>[]) {
    records.forEach(r => r.f(r.v))
}
```
[Playground](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220416#code/JYOwLgpgTgZghgYwgAgCoE8AOECydPIDeAUMmcgEQgCuAtgEbQUBcyND0A3KeRQM5gooAOYtkAoSGHdylegHt5AGwhwQYhctUhuAX2LEwWFAFUQweSABKEBPKgATADwAFZBAAekEA77IA1hDo8jBoxniYAHzIALxEyADaANLIoMguALrMPGQksrL+oA6sSTL5ZABurBjYEckZZeUwrAAUmNXh+PUAlLHRFfLADo3I+roJmdzEMNQgCGAWIMiYUPJIfHw2do58Time3r4BQSFhtfiRLVC29r6sZotbt3uRCRm9eeQA9F-IFdDoZD0OAOHKpGBXG47AB0KikYAAFshogAGD5g2R2EACZChOLXba+BIojLQmAY8gUsgE258Mn2ACiiARLRahAqul6MWiEIq3W6YLGBhWawgGyeOxaCU+ZEKPlY-EEIgoABowVVKAiIEolPIAISqsHNP5wJR9IhU5BYvhaWHyYQtCqm6FgeQmTDYKAAYTgfAgLX5IzGKotBSKCvYjCghtkGoAjAAmADMatkxqdZu5ofKVssNpUdodGZd8gZHkwlgg4GAppaScDguIunexCAA)

How could I express the fact that each record is related only to itself? I don't even know if its possible to properly type it, I think variadic type arguments would be needed because I need a variable number of `K`s, each of which unrelated to others. Not sure. The above typing lets me do bad things as you can see in the playground.

I tried the following, but it is all broken:
```ts
type MapKeyofTypeMapToUnionRecord<K extends (keyof TypeMap)[]> = 
    K extends [infer H extends keyof TypeMap, ...infer REST extends (keyof TypeMap)[]] ? 
        [UnionRecord<H>, ...MapKeyofTypemapToUnionRecord<REST>] :
        []

function processRecords<K extends (keyof TypeMap)[] | []>(records: MapKeyofTypeMapToUnionRecord<K>) {
   records.forEach(r => r.f(r.v)) // broken
}
```
[Playground](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220416#code/JYOwLgpgTgZghgYwgAgCoE8AOECydPIDeAUMmcgEQgCuAtgEbQUBcyND0A3KeRQM5gooAOYtkAoSGHdylegHt5AGwhwQYhctUhuAX2LEwWFAFUQweSABKEBPKgATADwAFZBAAekEA77IA1hDo8jBoxniYAHzIALxEyADaANLIoMguALrMPGQksrL+oA6sSTL5ZABurBjYEckZZeUwrAAUmNXh+PUAlLHRFfLADo3I+roJmdwGRtjIEUlBITW4+KjyZhbWtvbOKZ7evsgtgcGhyxHdCRnRcTnIe14QPn4JoDDQyAAS7o-PAYtnTqYAA0yAAdBC3h8rABRADKqB+Bz8xwBYVq+EuGQyyAA-Mg7rIEhtLDY7I4nJ9IqCIWD5gDzqt1uZSdsKbCEZEcdlymQrgYYNQQAgwJtkJgoPIkHw+GSdnwnA9kUcTiF0StMFjIi0oGzfKx6adGZg1iStuTdpFenlZLqLXwEgAGHEAehdaGomBUyBmKAA5Fc-cg1SopGAABbIP2OoPhuB+EDydwqWhPMDIODpoqeKMxsGEt3IAB6uMJdvlYJg9hhiHDOr6yCglZ1YIq3W6xH0xAlUogMrljgVCX4ghEFFBVDojCgFGuLQSNrIhR8rBHklEwLuVUo4YgSiU8gAhOO7s1kBU4EoG4v8nYQHwtGCD8IWhelGCwOtMNgoABheMQC07YjGMoI3suxSUOw04nrI24AIwAEwAMybrIZ5vtehLkHeD4qE+8gvm+H7yDCHiYJYabAJeLTIcBdxjBkHZAA)

**Comment by whzx5byb** [comment]
I agree that `processRecords` is unsound. It is only sound when `K` is not a sub union of the constraint, but only "one of" the constraint union. This concept is described in https://github.com/microsoft/TypeScript/issues/27808.

**Comment by jcalz** [comment]
I think that TS has always had unsoundness on writes to generic indices:

```ts
function set<T, K extends keyof T>(obj: T, k: K, val: T[K]) {
    obj[k] = val; // no compiler error, but unsound
}

const obj = { a: 0, b: "" }
set(obj, Math.random() < 2 ? "a" : "b", "");
obj.a.toFixed() // runtime error
```

[Playground link](https://www.typescriptlang.org/play?ts=4.6.2#code/GYVwdgxgLglg9mABAZwKZQDwBUA0iDSiqAHlKmACbKIDWqAnnMIlgHwAUcARgFYBcLPDQH48ANwCGAGwFYA2vgC6ASkQBvAFCJtibjzk1FiALyJJUgNyIA9Nd00J9DQF8NGiAmRRdvE+sQSAgAMeFwCAEThiK5oUJy8eACyElAAFgB0AE4SlHAAtuyqGIgATIgA-IjhElERXOF4kcoWGnrpEulQcABiMMSoFIU2dpngsHmoRJmZcJlAA)

And presumably this is just another instance of that unsoundness?

I guess I was naively assuming this wouldn't be the case, since one of the points of #30581 was to encode such correlations correctly (not a trivial task, as described in [this comment](https://github.com/microsoft/TypeScript/issues/30581#issuecomment-476417974)). I'm not sure it's worth the refactoring involved in turning something into a *distributive object type* form as described in #47109 if you get behavior similar to using a type assertion.

**Comment by RyanCavanaugh** [comment]
This was an intentional trade-off. If you're using the mapped type lookup pattern, you should use multiple type parameters if the value can appear in multiple places
```ts
function processRecords<K1 extends keyof TypeMap, K2 extends keyof TypeMap>(record1: UnionRecord<K1>, record2: UnionRecord<K2>) {
    record1.f(record2.v);
}
```
