### ISSUE TITLE
Type 'T' is not assignable to type 'T extends Sub ? Sub : T'.

### ISSUE THREAD

**Issue by taralx** [microsoft/TypeScript#48746]
# Bug Report

### 🔎 Search Terms

variance, conditional, subtype, limit

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about variance and conditionals.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220417#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChkHIBGmEAXMgK4gDWIA9gO4gDcuAvrrqJLIigGVKRZBAAekEABMMaUsjyFkGYRWp0mrDlxjUEYYPRDIwUOCAwx6UALYAeACqiJEabPRYAfAAowFBwCU-s6SMshCIgD84cLIwYqEUBBglFDGYGzsQA)

### 💻 Code

```ts
interface Base {
    base: unknown;
}

interface Sub extends Base {
    sub: unknown;
}

function transform<T extends Base>(t: T): T extends Sub ? Sub : T {
    return t;
}
```

### 🙁 Actual behavior

"Type 'T' is not assignable to type 'T extends Sub ? Sub : T'."

### 🙂 Expected behavior

No errors. Either T extends Sub, and so is assignable to it, or it doesn't, and so is assignable to itself.

**Comment by MartinJohns** [comment]
See #48243, #47633 and probably many others.

Resolving of conditional types involving unbound generic type arguments is deferred. The compiler doesn't know what type `T extends Sub ? Sub : T` resolves to, because it doesn't know what type `T` is.

**Comment by taralx** [comment]
Any recommendations on how to express this differently that doesn't run into this problem?

**Comment by taralx** [comment]
FWIW I tried using `[T] extends [Sub]` to avoid distributive behavior but it doesn't help.

**Comment by taralx** [comment]
Maybe syntax-driven? Would make sense.
