### ISSUE TITLE
貌似Function类型会影响数组项中的其他类型的校验

### ISSUE THREAD

**Issue by 4xii** [microsoft/TypeScript#48747]
# Bug Report

貌似Function类型会影响数组项中的其他类型的校验

### 🔎 Search Terms
Function Type ,Array

### 🕗 Version & Regression Information
4.6

### 💻 Code

```ts
const func: Function = () => {

}

const arr: Array<number> = [func(), '123'] // no error


const arr1: Array<number> = ['123', '123'] // error
```
<img width="592" alt="image" src="https://user-images.githubusercontent.com/73146951/163800940-6f82f45a-bc34-4d20-a16b-668c20e3b41f.png">

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

I don't see any defect here. Calling `Function` returns `any`. Having `any` within an array causes it to be typed `any[]`, which is assignable to `number[]`.

**Comment by 4xii** [comment]
> 

sorry～，I'm not very good at submitting issus。 Error will be reported vue2 because this error。
<img width="592" alt="image" src="https://user-images.githubusercontent.com/73146951/163802514-62a8ccda-32df-44b8-b05e-4365e172eccf.png">

**Comment by 4xii** [comment]
> You forgot to fill out the issue template.
> 
> I don't see any defect here. Calling `Function` returns `any`. Having `any` within an array causes it to be typed `any[]`, which is assignable to `number[]`.

sorry～，I'm not very good at submitting issus。 Error will be reported vue2 because this error。
<img width="592" alt="image" src="https://user-images.githubusercontent.com/73146951/163802687-1418a8dc-af21-4c58-bdb6-59ac750271be.png">

**Comment by MartinJohns** [comment]
Like I said: It's not a bug, it's working as intended.

You shouldn't use `Function` in the first place, as it lacks any type-safety. You should use properly typed functions instead. See the [documentation on functions](https://www.typescriptlang.org/docs/handbook/2/functions.html) for more information. The `Function` type will return `any`, which will propagate and hide type-issues like yours.

**Comment by 4xii** [comment]
> Like I said: It's not a bug, it's working as intended.
> 
> You shouldn't use `Function` in the first place, as it lacks any type-safety. You should use properly typed functions instead. See the [documentation on functions](https://www.typescriptlang.org/docs/handbook/2/functions.html) for more information. The `Function` type will return `any`, which will propagate and hide type-issues like yours.

thank you～～～～
