### ISSUE TITLE
Ability to map functional component props type

### ISSUE THREAD

**Issue by rosostolato** [microsoft/TypeScript#48750]
# Suggestion

When working with JSX components, the attributes will always be the type of the first parameter of the function plus the declared `IntrinsicAttributes` type and there's no way to override it (at least I didn't find how).

It should have an option to overwrite the type of JSX attributes based on the component function type.

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

`Jsx`, `IntrinsicAttributes`, `override component props type`.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Take this example, I have a component that receives props of type `State<T>` that are mapped within the `Component` interface.

```ts
const MyComponent: Component<{ item: number }> = ({ item }) => {
  // item is of type "State<number>"
  return <div>{item}</div>
};

// try to use it in another component
...
<MyComponent item={0} />
...
```

Here, the attribute value is of type `number`, so the library will automatically wrap the input value under the hood into the `State<T>` interface and will provide it in props object for `MyComponent` function. But the issue is that typescript will only expect type `State<number>` for the `item` attribute and will throw this error:

```
Type 'number' is not assignable to type 'State<number>'.ts(2322)
[main.tsx(12, 32): ]()The expected type comes from property 'item' which is declared here on type 'IntrinsicAttributes & Inputs<{ item: number; }>'
```

I believe that if we allow `IntrinsicAttributes` to have a generic type and assign the type of the component, we can take control of it. 

`IntrinsicAttributes` type for React would be like this:
```ts
type IntrinsicAttributes<Component> = Component extends (props: infer P) => JSX.Element ? {
  [K in keyof P]: string;
} : never;

const attrs: IntrinsicAttributes<typeof MyComponent> = {
  item: // still is `State<number>` type here.
};
```

And, in my scenario, I would use `IntrinsicAttributes` like this:
```ts
type IntrinsicAttributes<Component> = Component extends (props: Inputs<infer P>) => JSX.Element ? {
  [K in keyof P]: P[K];
} : never;

const attrs: IntrinsicAttributes<typeof MyComponent> = {
  item: 0 // correct type `number`,
};
```

## 📃 Motivating Example

It would allow JSX to be used in more edge cases. For example, I have another scenario I want to implement for my library. I want to have a second parameter as "output" props. So this is my example:

```ts
const GithubCard: Component<Inputs, Outputs> = ({ item }, { remove }) => {
  // "item" is of type `State<GithubItem>`
  // "remove" is of type `EventEmitter<GithubItem>`
  return (
    <div class={styles.card}>
      <div>
        <a href={item().html_url} target="_blank">
          {item().full_name}
        </a>
        <strong>{item().stargazers_count}</strong>
      </div>
      <p>{item().description}</p>
      <button on:click={() => remove.emit(item())}>Remove</button>
    </div>
  );
};
```

And this would be my `IntrinsicAttributes`:
```ts
type IntrinsicAttributes<Component> = Component extends (
  inputs: Inputs<infer I>,
  outputs: Outputs<infer O>
) => JSX.Element
  ? {
      [K in keyof I]: I[K];
    } & {
      [K in keyof O as `on:${string & K}`]: O[K];
    }
  : never;
```

These examples are working in plain JavaScript, the only problem here is wrong type checking. 

## 💻 Use Cases

In libraries that don't work in the same way as React does, which implement their own features.

**Comment by RyanCavanaugh** [comment]
Can I get a more complete example of what you're trying to do? What is `State<T>` ? What is `Component` ? etc.. I suspect this can be made to work today but I don't have enough context on what's going on here.

**Comment by rosostolato** [comment]
@RyanCavanaugh This is a frontend library I'm working on just like React but with reactivity props like `RxJs` observables and with inputs and outputs just like Angular. Here are the interfaces descriptions:

```ts
export interface Component<I = {}, O = {}> {
  (inputs: Inputs<I>, outputs: Outputs<O>): JSX.Element;
}

export type Inputs<P> = {
  [K in keyof P]: State<P[K]>;
};

export type Outputs<P> = {
  [K in keyof P]: EventEmitter<P[K]>;
};
```

`State<T>` and `EventEmittes` are just like `RxJs` Observables:

```ts
export interface State<T> extends Observable<T>, Completable {
  /** Current state value. */
  (): T;

  /**
   * Updates the current state.
   * @param value next value.
   */
  next(value: T): void;

  /**
   * Updates the current state based on the last value.
   * @param updater callback function to update current state.
   */
  update(updater: (value: T) => T): void;
}

export interface EventEmitter<T> extends Observable<T>, Completable {
  /** Returns true when emitter is being observed. */
  get observed(): boolean;

  /** Emits event with the given value. */
  emit(value: T): void;
}
```

And this is an implementation of a functional component:
```ts
interface MyInputs {
  item: GithubItem;
}

interface MyOutputs {
  remove: GithubItem;
}

const GithubCard: Component<MyInputs , MyOutputs > = ({ item }, { remove }) => {
  return (
    <div class={styles.card}>
      <div>
        <a href={item().html_url} target="_blank">
          {item().full_name}
        </a>
        <strong>{item().stargazers_count}</strong>
      </div>
      <p>{item().description}</p>
      <button on:click={() => remove.emit(item())}>Remove</button>
    </div>
  );
};

export default GithubCard;
```

My intention is to make typescript understand that `GithubCard` has attributes of type `MyInputs & MyOutputs` (MyOutputs prefixed with "on:").

My library already does it under  the hood on Javascript side, so you only need to provide data like this:
```tsx
const item: GithubItem = {
  full_name: 'name',
  stargazers_count: 0, 
  description: 'description'
};
...
<GithubCard item={item} on:remove={() => /* some logic */} />
```

**Comment by rosostolato** [comment]
What I doing today is a workaround function to force the "expected" type from typescript:
```ts
export interface JSXComponent<I = {}, O = {}> {
  (props: I & Emitters<O>): JSX.Element;
}

export type Emitters<T> = {
  [Key in keyof T as `on:${string & Key}`]: (value: T[Key]) => void;
};

export function component<I = {}, O = {}>(
  fn: Component<I, O>
): JSXComponent<I, O> {
  return fn as any;
}
```

So to make it work, users need to wrap their component with the `component` function, which is really bad:
```ts
export default component(GithubCard);
```

**Comment by andrewbranch** [comment]
Are you sure you can’t use `LibraryManagedAttributes<C, P>` for this?
