### ISSUE TITLE
bigint not loosely comparable to number

### ISSUE THREAD

**Issue by Trevor-Strong** [microsoft/TypeScript#48767]
# Bug Report

Currently, tsc sees this as an error stating
> This condition will always return 'false' since the types 'number' and 'bigint' have no overlap.
which is not the case. The spec for bigint, which states that an expression like `1n == 1` would 
be true since, conceptually, `1` and `1n` are the same value. 

### 🔎 Search Terms

number, bigint, loose equals

### 💻 Code

```ts
console.log(1 == 1n);
```

### 🙁 Actual behavior

This creates an error at compile time since tsc thinks that `1 == 1n` will never be true, which is simply not the case.

**Comment by MartinJohns** [comment]
Duplicate of #30540. Used search terms: `bigint number in:title`

**Comment by Trevor-Strong** [comment]
@MartinJohns Thank you for the tip. My bad
