### ISSUE TITLE
 Typescript Extensibility / Plugins

### ISSUE THREAD

**Issue by nbellowe** [Microsoft/TypeScript#4876]
I think typescript could benefit from some sort of plugin/extensibility system. This would allow for people to design language features that are helpful to their particular needs, without requiring a change in Typescript.

Here are a few examples of possible extensions:

  1. Add language support for defining properties with getters and setters.
     - Too big of a change, possibly not useful enough to warrant a change in Typescript, but it would be super cool if I could make a seperate npm package called typescript-properties, and anyone could pull that, and utilize it in there apps. This could maybe be an example that decorators could take care of, not sure.
            
   ```
property hello:T
            compiles to
_hello:T
get hello():T { return this._hello }
set hello(v:T){ this._hello = v }
```           
 
  2. Add preprocessing to the code that doesn't break source mapping.
    ```
            #IF(DEBUG)
               expr;
            #ENDIF
```
    While this can be accomplished with external tools, it breaks source mapping. With a complex build, like:
    1. Original TS
    2. Post-pre-processed TS
    3. Compiled TS (Javascript) and sourcemaps to PPP-TS
    4. Single-file JS (may need to be ordered in optimal way) & source map to PPP-TS if the tool supports input source mapping.
    5. Minified Javascript & source map & source map to PPP-TS if the tool supports it.

    -- note(UglifyJS can optimize out constants, so defining a `const DEBUG=true|false` can optimize out debug code as well.  `if(DEBUG) expr;`)

**Comment by RichiCoder1** [comment]
:+1: A system that could allow plugins to perform their own passes during stages of analyization and compilation would be excellent. Babel is already proving the value of this.

**Comment by eyalsk** [comment]
:+1: Yup, this can be really awesome, there are many features that can turn into extensions and shouldn't or won't ever be part of the language but people still need/want them.

**Comment by kitsonk** [comment]
This is similar to #2900 and #3003.  In particular #3003 discusses why a [pluggable compiler/analyzer is a challenge](https://github.com/Microsoft/TypeScript/issues/3003#issuecomment-98610636) for TypeScript at the moment.

**Comment by RichiCoder1** [comment]
Definetly agree that analyzers or things that have to plug into typescript in a high fidelity way are unlikely. But this that simply operate over the raw text would still be useful.

**Comment by tinganho** [comment]
If there can't be super high fidelity. I don't think people mind creating analyzers based on low fidelity either?

**Comment by kitsonk** [comment]
@RichiCoder1 then you don't need that integrated to TypeScript...  This seem to be asking for some level of integration to change what is emitted at certain points as the code is processed.  If all you needed to do was run over the raw text, why would you need that integrated into TypeScript?  You would just use a pre-processor or a post-processor, which a lot of people do already.

**Comment by jbondc** [comment]
Ya my interest in this is deep integration with the language service. So you could ```re-write``` any object in the compiler or language service by wrapping a proxy around it. Maybe something like this: https://github.com/Microsoft/TypeScript/commit/a2f40627fc36aa7f42826f204270ffeef67bdac0

There's lot of parts of TypeScript that could go in the 'extendable' scope.

**Comment by danquirk** [comment]
I think #3003 covers this topic well enough. Let's just discuss it over there. A large proposal of some particular design/implementation might warrant a new issue but we already have a place to +1 this idea and chat about it.

**Comment by nbellowe** [comment]
Thanks!
