### ISSUE TITLE
`Parameters<T>` can't get the parameters in overloaded function

### ISSUE THREAD

**Issue by EralChen** [microsoft/TypeScript#48760]
# Bug Report

(English isn’t my native language. I apologize for my mistakes. );

Context: I want to get all useable  parameters  in overloaded function.  use `Parameters<T>` , but it just get the last function prameters.

### 🔎 Search Terms

Prameters

overloads

### 🕗 Version 

- ^4.6.2

### ⏯ Playground Link

[[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDLID2IAFGAJ4AOEAXMgORZSgDmDANMhrc2wJT0AbkWAATAsTKUa9BiACuAWwBG0TshC1Fq6IOQjxkkuWp1GcKFDgUNcenBAUA2gF19hiQF88MlAEFkAF5kAAVLOCUISCgMAB50LGcGEgZXAD5nAAZXPDwEEixke0CQpjAWEHY8IA)](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDLID2IAFGAJ4AOEAXMgORZSgDmDANMhrc2wJT0AbkWAATAsTKUa9BiACuAWwBG0TshC1Fq6IOQjxkkuWp1GcKFDgUNcenBAUA2gF19hiQF88MlAEFkAF5kAAVLOCUISCgMAB50LGcGEgZXAD5nAAZXPDwEEixke0CQpjAWEHY8IA)

### 💻 Code

```typescript
interface Test {
  on(type: 'string', s:string): void
  on(type: 'number', n:number): void
  on(type: 'array', a: any[]): void
}
type A = Parameters<Test['on']>[0]

const a:A = 'string'

```

### 🙁 Actual behavior

```typescript
interface Test {
  on(type: 'string', s:string): void
  on(type: 'number', n:number): void
  on(type: 'array', a: any[]): void
}
type A = Parameters<Test['on']>[0] // A: 'array'
const a:A = 'string' // Error 
```

### 🙂 Expected behavior

```typescript
interface Test {
  on(type: 'string', s:string): void
  on(type: 'number', n:number): void
  on(type: 'array', a: any[]): void
}
type A = Parameters<Test['on']>[0] // A: 'string'|'number'|'array'
const a:A = 'string'
```

or  can I get it any other way ?

**Comment by MartinJohns** [comment]
This is a documented design limitation:
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html
