### ISSUE TITLE
[Not really a bug] change in es5 output from string interpolation

### ISSUE THREAD

**Issue by bigopon** [microsoft/TypeScript#48776]
# Bug Report

### 🔎 Search Terms

string concat

### 🕗 Version & Regression Information

4.5.x

- This is not a crash
- This changed between versions 4.4.x and 4.5.x

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=1&ts=4.5.5#code/G4QwTgBCELwQBgEgN4CMC+AHAHvIA

### 💻 Code

```ts
var a = `${b}px`
```

### 🙁 Actual behavior

output:
```ts
"use strict";
var a = "".concat(b, "px");
```

### 🙂 Expected behavior

```ts
"use strict";
var a = b + "px";
```

**Comment by Josh-Cena** [comment]
This is expected. See https://github.com/microsoft/TypeScript/pull/45304

**Comment by bigopon** [comment]
@Josh-Cena I see. thanks for the pointer. I guess if anyone is concerned by `.concat()`, they can use `+` instead of template literal.
