### ISSUE TITLE
Reflect-metadata broken in 1.6.2: TS2306: File 'node_modules/reflect-metadata/reflect-metadata.d.ts' is not a module.

### ISSUE THREAD

**Issue by mattyork** [Microsoft/TypeScript#4877]
To reproduce:
1. Update to Typescript v1.6.2 and reflect-metadata v0.1.1
2. Compile this:

    /// <reference path="node_modules/reflect-metadata/reflect-metadata.d.ts" />
    import 'reflect-metadata';

**Expected**: compiles just fine
**Actual**: compile error:

    index.ts(3,8): error TS2306: File 'node_modules/reflect-metadata/reflect-metadata.d.ts' is not a module.

I created a [git repo](https://github.com/mattyork/TypescriptReflectMetadataBug) to demonstrate:

    git clone https://github.com/mattyork/TypescriptReflectMetadataBug.git
    cd TypescriptReflectMetadataBug
    npm install
    ./node_modules/.bin/tsc

If I delete the [`typings` field in package.json](https://github.com/rbuckton/ReflectDecorators/blob/master/package.json#L6) this error goes away. What is this `typings` field for and why is it causing this bug?

**Comment by mhegazy** [comment]
we either need to remove the `typings` field, or make it an empty module, e.g. 
```
interface reflect_metadata {}
export = reflect_metadata;
```

**Comment by rbuckton** [comment]
I'll have to remove "typings", as making it an external module will prevent the library from introducing globals.

**Comment by rbuckton** [comment]
I removed "typings" from the reflect-metadata polyfill and published a new version to npm.

**Comment by rtm** [comment]
/// <reference path="node_modules/reflect-metadata/reflect-metadata.d.ts" />

What is the way to modify `tsconfig.json` to accomplish the same effect?

**Comment by kitsonk** [comment]
Include the file in the `"files": []` property.
