### ISSUE TITLE
`@types/node` can't be excluded in `types` or `typeRoots`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#48795]
# Bug Report
i have repo where some code is executed in node (config files, etc.) and the rest is executed within the browser, so i need to have `@types/node` installed but only available within the files that are actually executed by node.

however, it seems that `@types/node` is available regardless of what you specify in `types` or `typeRoots`, so it doesn't seem to be possible to do this.

### 🔎 Search Terms
@types/node types typeroots

### 🕗 Version & Regression Information
4.7.0-dev.20220420

### ⏯ Playground Link
n/a no `types` or `typeRoots` options in the playground

### 💻 Code
here i have two `@types/*` packages with globally declared symbols. when i set `types` and `typeRoots` to `[]`, it correctly removes `@types/openui5`'s globally declared types but not `@types/node`'s

code:
```ts
export {}

sap // error
__dirname // no error
```
tsconfig:
```json
{
    "compilerOptions": {
        "typeRoots": [],
        "types": []
    }
}
```

package.json:
```json
{
    "devDependencies": {
        "@types/node": "14.14.20",
        "@types/openui5": "^1.100.0",
    }
}
```
### 🙁 Actual behavior
no error when attempting to use globally declared types from `@types/node`

### 🙂 Expected behavior
error: `Cannot find name '__dirname'.`

**Comment by andrewbranch** [comment]
Would you mind running tsc with `--explainFiles` and posting the output? Is the input file TS or JS? Does this repro with tsc or just in the editor?

**Comment by DetachHead** [comment]
this is strange, i can't reproduce it anymore...

will re-open if it happens again. for the record it was a `.ts` file and it occurred in both the editor and `tsc`

**Comment by DetachHead** [comment]
@andrewbranch had this happen again, but this time it only occurred in the editor. deleting `node_modules` and re-running `npm install` fixed it though, no idea how or why.

for future reference is there a way i can pass `--explainFiles` to the language server so i can see what's happening in the editor?

**Comment by andrewbranch** [comment]
I believe you get the `explainFiles` output in the TS Server log if you set the log level to verbose. Send me whatever log you can get and I’ll take a look!

**Comment by DetachHead** [comment]
still can't get it to happen reliably, but i think it may have been something to do with my IDE using the wrong `tsconfig` file because it was named something like `tsconfig.node.json` instead of `tsconfig.json`. https://github.com/microsoft/vscode/issues/3772
