### ISSUE TITLE
Unintuitive error message when some JSX children is invalid

### ISSUE THREAD

**Issue by Josh-Cena** [microsoft/TypeScript#48796]
# Bug Report

### 🔎 Search Terms

JSX children error message

### 🕗 Version & Regression Information

This can probably go all the way back when better JSX children error messages were added, but it went away unnoticed until `@types/react` has stricter `ReactNode` typing.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoctCAOwGd4U4BeOACnLjgB4QVgaAPk5c4AbzbcAJsABucAPSCAlHBR04AVxoBrGhADuNAL4iu3OmBQ1Fw8wr4DhyikA)

### 💻 Code

```tsx
import React from "react";

const a = (
  <main>
    {(<div />) as unknown}
    <span />
  </main>
);
```

### 🙁 Actual behavior

Error message: "This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided." This is weird, because when you remove that `as unknown`, it's still technically "multiple children".

### 🙂 Expected behavior

When there's only one child (by deleting the `<span />`), the error message is "Type 'unknown' is not assignable to type 'ReactNode'.". In this case, we could give an error like "some of the children have incompatible types with `ReactNode`"

**Comment by donaldpipowitch** [comment]
@Josh-Cena , thank you so much. I had no clue what this error was about. As soon as you gave me the hint with type `unknown` I could immediately fix all errors. ❤️
