### ISSUE TITLE
Arrow function doesn't introduce new 'this' context

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TypeScript#4879]
Dear ladies and gentlemen, 

recently I stumbled about an error in your "JSON.Stringify" implementation. 
That error appeared when I used the overload of the stringify function which uses a replacer function as one of its arguments. 
I created a test project which can be used to reproduce the error. You can download that project from [https://drive.google.com/folderview?id=0B5T7PycC4CqCSWlWOUVCZjE1TTg&usp=sharing](https://drive.google.com/folderview?id=0B5T7PycC4CqCSWlWOUVCZjE1TTg&usp=sharing "[JSONTest]").

The following part is a detailed description of the error.

First I got a compiler error for the "this" reference which I used in the replacer function. For some reason the compiler insists that the "this" reference is of the type of the surrounding object. At first I guessed that the compiler might not be aware of the context switch inside the replacer function. So I switched to the option to compile even in the presence of compiler errors.

//Compiler error showing the wrong "this" reference. (Wrong context)//

![compiler_error](https://cloud.githubusercontent.com/assets/9468599/9978831/92e9fdf6-5f43-11e5-9793-e4f1a84357c2.png)

In a stringify replacer function the context gets switched to the object which currently gets serialized. Your can read about it here: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify "[Stringify Definition at MDN]")

//Stringify definition at Mozilla Developer Network//

![stringify_replacer_parameter_definition](https://cloud.githubusercontent.com/assets/9468599/9978837/a7061a04-5f43-11e5-9bf6-cdd0a1491c7d.png)

A debug session showed that the stringify functions was using the expected context. The context shown in the image below is not the context of the surrounding class but the context of a node class, which is part of the solution. 

//Degugger showing the right context.//

![debug_session_01](https://cloud.githubusercontent.com/assets/9468599/9978844/d9ff4598-5f43-11e5-9d23-e1b42c0190d5.png)

But for any reason the result was not what I expected. The resulting json string should show the fully qualified parent ID. (A concatenation of all parent IDs from the root of the tree down to the parent. Something like 0.2.5.) As you can see, the "parent" property in the json string is always empty. 

//Resulting json string with invalid parent property.//

![result](https://cloud.githubusercontent.com/assets/9468599/9978845/e1484a5c-5f43-11e5-8359-8c8cbbae5902.png)

A second debug session showed a strange behaviour. Even with the right context and condition, the program never hit the line 59. That's the line where the the "parent" property in the json string gets set. So it's not surprising that the resulting json string is invalid, but it's still mysterious that the program doesn't hit the line in the while loop as expected. For a short time I doubted my mental health.

//Right context, wrong logic]

![debug_session_02](https://cloud.githubusercontent.com/assets/9468599/9978854/3e3b54fc-5f44-11e5-8822-28a6ec7b7b04.png)

After that I guessed that somebody changed the rules of logic and forgot to tell me. But then I took a look into the compiled javascript code and found the reason for the described behaviour. 

//Compiled javascript code.//

![compiled_code](https://cloud.githubusercontent.com/assets/9468599/9978859/7ee107cc-5f44-11e5-9427-1899236ef65b.png)

You will notice that the compiler created it's own context reference in line 35. That reference is also used inside the replacer function. Effectively overwriting the expected context. So the debugger, which acts on the TypeScript source, shows the right context, but in the background where the compiled javascript gets executed, the program uses the wrong context. That behaviour is definitively wrong. So I'm going to flag that as a bug. 

### But wait, there is more! ###

There is nothing wrong in creating automatic generated code on the fly. But if you do so, you should triple check that your code doesn't interfere with with other code in an unexpected way. 
I can hear you thinking: "You already pointed that out, so stop boring me." But I'm not talking about the context switch, now I'm talking about the name you used to create your own context reference. 
That name is a 100% percent guarantee for naming collisions with other code. Today it didn't hit me, but will hit others, that's for sure. Try the search query "_this = this" at google and you get half a million hits. 
You might think about that pattern whatever you want. (I myself think it's an antipattern.) But it's undoubted very popular. (That might also be the reason why you used it in the first place.) The question is: Can you tell what will happen if a programmer already used that pattern in his own code? 
It's only a suggestion but it might help to save a lot of trouble. Don't use popular identifiers in automatic generated code. Use hash values guid's or something like hat. Automatic generated code doesn't care for human readable identifiers. So you shouldn't care either.

### Stop blaming! ###

Yes, you are right. I'm not all negative. You did a great job in making javascript a programming language which can now be used for serious programming. I'm a great fan of TypeScript, I love it, really. So don't be too depressed about what I wrote and have a nice day. 

Sincerely, Lord Saumagen.

**Comment by SaschaNaz** [comment]
You should use function expression instead of arrow function for `JSON.stringify`, [as latter doesn't have its own `this` value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this).

**Comment by kitsonk** [comment]
Yes as stated, the canonical `this` is only available in lambda/arrow functions, as per ES6/ES2015.  Also, TypeScript does handle the [name collision and warns you](http://www.typescriptlang.org/Playground#src=%0D%0Alet%20_this%20%3D%20%7B%7D%3B%0D%0A%0D%0A%5B1%2C%202%2C%203%5D.forEach(item%20%3D%3E%20%7B%0D%0A%09console.log(this)%3B%0D%0A%7D)%3B%0D%0A) if you have done something like this.

Pretty good rant though...  Sorry your efforts were futile though.

**Comment by DanielRosenwasser** [comment]
As @kitsonk and @SaschaNaz mentioned, arrow functions in ES6 don't introduce a new `this` context, and this was an intentional design decision for situations when you *don't* want to re-bind the `this` value at an invocation. Just use a plain-old `function` expression (e.g. `function () { }`).

**Comment by lord-saumagen** [comment]
Thank you for taking the time to answer my post. 

Your are a greater help to me than you can ever imagine. You showed me that I still didn't get that screwed up "this" concept in javascript right. May be it's because they chose the wrong name for that concept. In human language a this, that or me is a generalization for a unique entity. A this can't be a that or a me as much as a me cant be a this. But in javascript a "this" is everything but unique. A "this" can be a me or a that. 

For a person who isn't schizophrenic in the first place, that concept is hard to conceive. I really do have a mental blockade when it comes to a javascript "this". The "this" in javasript is like saying : "Pleas jump in front of that driving truck when you want to grow old." They chose an identifier which describes a well known concept in a human language and gave it an opposite meaning. No wonder that there are "1,400,000,000" hits at google when you enter "this javascript". It seems that I'm not the only one with hat mental blockade. 

But you set me back on right track. I wouldn't have understand where I went wrong with my assumptions, without your help. Thank you for that. 

Kind regards, Lord Saumagen

**Comment by DanielRosenwasser** [comment]
I'm glad we could assist you @lord-saumagen. If you'd like to learn more details on the matter, I suggest you look into Mozilla's Developer Wiki page on ECMAScript 6's arrow functions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by lord-saumagen** [comment]
Thank you very much,

I'm already studying that pages at MDN. I guess I didn't pay enough attention when I read them the first time. Surprisingly I didn't run into trouble with arrow functions for more than a year now. But this all has also a good side. Because you will never forget those lessons you learned the hard way. 
So I'm prepared for the next time I'm facing that kind of trouble.

Kind regards, Lord Saumagen.
