### ISSUE TITLE
Use the javascript-compatible "use ..." string call for referencing paths

### ISSUE THREAD

**Issue by adrianvoica** [Microsoft/TypeScript#488]
Why don't we just implement a javascript-compatible "use ..." string call, (e.g.: like the one used for "use strict";) for referencing paths, instead of using the /// <reference path="some-file.d.ts"/> comment notation?

It should look something like this:
"use 'some-file.d.ts'";
"use 'some-other-file.d.ts";

It's both compatible with js (ignored in js, if something goes wrong and the compiler does not include the file and remove the line in the output) and the code looks better. 
Relying on comments to do some language enhancement/feature is proven to be an unhealthy approach.

Both this notation and the current approach (comment-style) could go together nicely (to please everybody).

Just my 2 cents for this minor(major?) language annoyance (path referencing in comment-style).

**Comment by mhegazy** [comment]
As @CyrusNajmabadi mentioned, we can not remove existing syntax, and it is not clear that there is value in adding yet another variant.
