### ISSUE TITLE
TS 4.7 Beta: Object access should be narrowable after check

### ISSUE THREAD

**Issue by kyliau** [microsoft/TypeScript#48802]
If I read the release [blog post](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#control-flow-analysis-for-computed-properties) for v4.7 Beta correctly, the following test case should work, but it still produces an error.

```ts
interface Foo {
  [key: string]: number | string;
}

declare function generateKey(): string;

function fn(foo: Foo) {
  const key = generateKey();
  if (typeof foo[key] === 'number') {
    foo[key].toExponential(2);
    // Error: Property 'toExponential' does not exist on type 'string | number'.
  }
}
```

Is this a bug?

[TS Playground Link](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220420#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIDaA1hAJ4BcyAzmFKAOYC6VIArgLYBG0yAPjTqMA3LgC+uXABMICADZwoKGGxAIwwdCGQMIIaHEgBpcgAoAlFVr0QDUbhVqNW5DBCmYmKhnTmc+ZAQtWmRSMmQAXh09A2Mzc1ECYBhkUzAyAAcIdBTPdBJyJkiIqIBydm5oUr88AgI8grImADowdABRAA8MrT0NODlTACYEgIIAenHkdqgodCgqAAU5rKh05FK2rp79cGAB0uQpdAhqZBB0MGQITuAQl3SsjetGfnPOHihS5oCJCSA) v4.7.0-dev.20220420

If this only works for object access with `Symbol`, it should be clarified in the blog post.

FWIW, here's the example from the blog post (which works):

```ts
const key = Symbol();

const numberOrString = Math.random() < 0.5 ? 42 : "hello";

let obj = {
    [key]: numberOrString,
};

if (typeof obj[key] === "string") {
    let str = obj[key].toUpperCase();
}
```

_Originally posted by @kyliau in https://github.com/microsoft/TypeScript/issues/45974#issuecomment-1104464101_

**Comment by IllusionMH** [comment]
In your initial example there are no computed properties - `Foo` has just index signature. Only similar - both use indexed access to get value, but while it's know symbol in blog post, you just check for random string.

**Comment by andrewbranch** [comment]
I just reread @a-tarasyuk’s PR and the logic isn’t specific to computed properties (that was just the motivation for narrowing element accesses). The reason this isn’t narrowing is that the type of the argument expression (`key` in `foo[key]` in your example) has to be a unique symbol or string or number _literal_. In your example, it’s `string`. If you could know that its type was, say, `"this_string_in_particular"`, you would be allowed to narrow with that. [Here’s](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220420#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIDaA1hAJ4BcyAzmFKAOYC6VIArgLYBG0yAPjTqMA3LgC+uXAHopyAHLoA7sigQwbKCGqD6IBsgA2wSFDgHkYMgAcIuACYQEBuKuQw2IBGGDoQyBhAg0HCQANLkABQAlFQARAAWEAYG6LGiuO6e3r5uIBEwmFQY6FE4+MgIvrTIpGTIALz+gcFhkVGiBMAwyBGWNujdBegk5EwN9Y2x7NzQsaV4BARDI2RMAHRg6ACiAB5WvoHeZhEATO3lEhJAA) a modified playground showing the difference—obviously that’s not going to be adaptable to your use case, but hopefully it helps clear up the requirements.

I agree the release notes were not clear about this, though maybe the constraints mean that this is really only particularly useful for computed properties.

**Comment by andrewbranch** [comment]
I also noticed that the predicate on the name type [uses its declared type, not its flow type](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220425#code/MYewdgzgLgBA1gUwJ4RgXhgbQETgdgGhmygHcRDioALAJwXyIBYiBWAXRgENVRIoA3ACghAEwTAANl3ow+0GAFsuABwBcMAN5YA0jACWYGFCQqEIAGbxkETGACuigEYJa7dhr0AfGPbDiLQwRRGABfYTEJaVlJBFh9DQdnV2F5WEQkdGsUTH1OAHp87lRcMHwBGEKYclo4VH0rJBB7XzBQRUUEMFgafQgRBpgACgz0NAxS-ABKLSEYeYMrIeUVTAz2Gc05hZ2VteR2ADooEAAZEFJXAGEeBCGp7fnQoWegA). I’m not sure if there was a reason we couldn’t use the flow type or if there just wasn’t a strong reason to do it. I can’t really come up with an example that looks natural.

**Comment by lobotomoe** [comment]
> I’m not sure if there was a reason we couldn’t use the flow type or if there just wasn’t a strong reason to do it. I can’t really come up with an example that looks natural.

Hey, @andrewbranch , are you still can't come up with an example? I try to find some explanation for that behaviour. Possibly you can point me some docs?
