### ISSUE TITLE
Combining `Partial<>`, generics and conditional types in spread arguments causes TS2370.

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#48805]
# Bug Report

### 🔎 Search Terms

2370 generic conditional partial 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `partial`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAggNgdwIYgM4wE4ZQFXBAHhwD4oBeKHKCAD2AgDsATVKAVwYGsGB7BBqAG0AulAD8lKAC52XXvxEBuAFDKAZhwDGwAJY8BwABY7UAdR4ZOqIsQAUAOkdIMAc1Qz4yNJmwg8kGwBKKABvAF91LV19KCMTHB4eGwcnV3coAAVnXSQ4Ag5uPgYRYmDwyIZtPQEkZhxjdDMIODyqWnpmVgL5YuE7R3tnNxksjBzW0tCIiqqYgCM2YHqTABEeCFQGYGSBofTR8YJPFHQsXHwbSfKgA)

### 💻 Code

```ts
type AlwaysArrayType<T> = T extends unknown [] ? T : unknown[];

function thisWorks<T>(...args: AlwaysArrayType<T>) {}
function thisToo<T>(...args: Partial<unknown[]>) {}
function andThisAsWell<T extends unknown[]>(...args: Partial<T>) {}

function butThisDoesnt<T>(...args: Partial<AlwaysArrayType<T>>) {}
//                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^----- TS2370: A rest parameter
//                                                                  must be of an array type.
```

### 🙁 Actual behavior

TS2370

### 🙂 Expected behavior

No error, since the passed in type already is an array type.

**Comment by andrewbranch** [comment]
A `Partial` of some type assignable to `unknown[]` is [not necessarily an array](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAggNgdwIYgM4wE4ZQFXBAHhwD4oBeKHKCAD2AgDsATVKAVwYGsGB7BBqAG0AulAD8lKAC52XXvxEBuAFDLQkKAFkQAZQCWcOCEzYQAGT2doFAN7KoDoXua0ZDNgFsARhAzCZSAwgKo5COiDePHAAdHr02MA8fgFBIY6C4ZExHKgAxjxgSF5wEKj+UIHB9o4lDADmwAAWbp4+GGkOYGyojQAU0QNIGHWoKSAAlGMdUGAF-YPDoxVBk8tVofkMuUjA89FDI2OrldMAVjzOewdLlcep1Q4YEABuvqgQV4tHUw9QPXoAM12A32XzWd3WjlQcD0uQ+IOu3zW01QYBhcM+h3BP1CAIM8UxNxWOMcHiQYEJSJOvyeTDYGIRYNuJMeEDpcIASno6o1gQssczkb88cxKdihbjnEwAJIuGhiwXU0KoJJ80EC4kSxw5RqAtWI8VKxxS2gAeQBCs1RoccCQqGAsqYZotjI1ExZ1FeGBAlvdWocKo88P5RL91qgAKSAFEkLk+q7QxDpnjDL6k798mAQAB1OK6hhpj2MYAYPSlQv+qBWNAV8PPJBwNjlhNU+6hZy5RtO1C1+4AX1UanwlFKwBMKCI1DojBYaxEpAoOBUQ400uA6AY45A5CEOFHW4I2n0hmMWBQFisxAANCP7Qf4Mg0Fu8JBD7oDEYtxeIMRiMJl+o0AAKqNKajQ7nud5niABAAApDMAegNgQD4oOg0EvoQR4fqepjfr+xDKEAA).

**Comment by jespertheend** [comment]
Ah I see 😅 thanks!
