### ISSUE TITLE
lib.dom.d.ts Spellcheck type incorrect according to MDN docs

### ISSUE THREAD

**Issue by michaelwarren1106** [microsoft/TypeScript#48804]
## Missing / Incorrect Definition

The type definition for the `spellcheck` attribute in `lib.dom.d.ts` is incorrect according to MDN documentation of the attribute.

According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck), the `spellcheck` HTML global attribute is an enumeration, not a boolean type;

## Sample Code

https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L6397

```typescript
spellcheck: boolean;
```
should be changed to
```typescript
spellcheck: string;
```

OR

```typescript
spellcheck: 'true' | 'false';
```

## Documentation Link

[MDN Docs for spellcheck](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck)

**Comment by IllusionMH** [comment]
Looks like it's about requirement to explicitly have `<tag spellcheck="true">` instead of `<tag spellcheck>` (similar to `<input disabled>`) in HTML.

However in JS you should get `boolean` value.

**Comment by michaelwarren1106** [comment]
the problem is that when i'm making a web component, say with Lit in TS, and i try to add a spellcheck attribute on my web component so that i can pass the value down to some native element, i need to type that prop as a string, but TS complains

```typescript
class MyComp extends LitElement {
 // TypeError here because TypeScript's type is boolean not string
 @property({ type: String }) spellcheck!: string;
 
 render() {
  return html`<input spellcheck="${this.spellcheck}"`
 }
}
```

this syntax above will create a JS prop `spellcheck` AND an HTML attribute of the same name on my web comp and then pass down the value to a native one.

If I want the web comp API to match the native one, i need the spellcheck prop defined to be a string. So given the Typescript type as is, i would have to change my internal property name so that its something like 

```typescript
@property({ type: String }) spellcheckProp!: string;
```

so that it doesnt conflict with the HTMLElement type...but that just seems annoying when the TS type could be updated

**Comment by IllusionMH** [comment]
So you propose type to change type to something incorrect?

![image](https://user-images.githubusercontent.com/1312662/164515273-5d7a1d25-7c3d-4d36-9fef-77ae70bf3df5.png)

![image](https://user-images.githubusercontent.com/1312662/164516045-704e1d56-3a13-4c17-abfd-ec0a6171fe8a.png)

**Comment by michaelwarren1106** [comment]
it could be a union type?

`boolean | ('true' | 'false')`

**Comment by IllusionMH** [comment]
It will be wrong.
![image](https://user-images.githubusercontent.com/1312662/164517151-bf41a9a1-40dc-4bca-9213-59168cccc3d5.png)
you should really check docs/repo to see how to deal with this kind of properties, instead of trying to break lib definitions for everyone.

You can try to play with getter/setters or have [your own version of `lib.dom.d.ts`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#lib-node-modules) but I don't think it's optimal.
