### ISSUE TITLE
Language Service Plugin not working with javascript files

### ISSUE THREAD

**Issue by icetbr** [microsoft/TypeScript#48808]
# Bug Report

### 🔎 Search Terms

jsconfig plugins

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about plugins
  - ^4.7.0-dev.20220421, ^4.4.3
  
### ⏯ Playground Link

[The official sample project](https://github.com/orta/TypeScript-TSServer-Plugin-Template)
[A bunch of these language plugins as well](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#overview-writing-a-simple-plugin)

### 💻 Code

The same from the sample project. Here is my `jsconfig.json`.

jsconfig.json
```json
{

  "compilerOptions": {
    "plugins": [{
        "name": "tsserver-plugin"
    }]
  }
}
```

### 🙁 Actual behavior

With JS files, I can't make my custom code to work, like the debugger instruction in auto completion, or filter any kind of entry.

### 🙂 Expected behavior

Work the same as a `.ts` file, which works as expected.

**Comment by andrewbranch** [comment]
Can you describe exactly what you’re doing to repro this?

**Comment by icetbr** [comment]
Hi, exactly what is described in the README, reproducing here

```
git clone https://github.com/orta/TypeScript-TSServer-Plugin-Template
cd TypeScript-TSServer-Plugin-Template

# Install deps and run TypeScript
npm i
npx tsc --watch

# Set up the host app to work in
cd example
npm i
cd ..

# Or to hook up a debugger, use this command
# or use this to hook in later:
TSS_DEBUG=9559 code example
```

Then
`CTRL + SHIFT + P -> Typescript: Select typescript Version.. -> Use Workspace Version: node_modules/typescript/lib`

**To test**, turn on the debug (F5) in the **main project's VsCode** and in the **example's VsCode** you try out the auto completion

projects/TypeScript-TSServer-Plugin-Template/example/index.js:4
```
const anExampleVariable = "Hello World"
console.log(anExampleVariable)
a // here, test the autocompletion
```
You can also simplify sligthly this line like this

projects/TypeScript-TSServer-Plugin-Template/src/index.ts:7
```
      const whatToRemove: string[] = 'anExampleVariable';
```

And then test that the auto completion is not filtering the value.

This will show it not working. Do the same in the `example/index.ts` and you can see it works.

**Comment by andrewbranch** [comment]
The tsconfig.json in question doesn’t include JS files. Add `allowJs: true`?

**Comment by andrewbranch** [comment]
Well, I see the original post you said you had a jsconfig.json. The template repo only has a tsconfig.json. At any rate, you should verify with `tsc --listFilesOnly` that whatever configuration you’re using actually includes the files you want to operate on before proceeding.

**Comment by icetbr** [comment]
> allowJs: true

That did the trick, thank you! Should this be required? I'm fine closing this issue either way.

**Comment by icetbr** [comment]
Never mind, I deleted `tsconfig.json` and it worked. I didn't know they were mutually exclusive.

**Comment by fatcerberus** [comment]
> I didn't know they were mutually exclusive.

Yeah, in general the intent is that `jsconfig.json` is what you use when you only have JS code but you need to configure the language service for better IDE support.  If you have a tsconfig then it becomes a full-blown TypeScript project so the jsconfig is irrelevant (as tsconfig supports all the same options).
