### ISSUE TITLE
Record indexing type is not always fully reduced

### ISSUE THREAD

**Issue by nathsou** [microsoft/TypeScript#48810]
# Bug Report

### 🔎 Search Terms

Record indexing, type-reduction, mapped-types, indexed access types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/FAYw9gdgzgLgBDAprOBeOAeA0ognnRADyQgBMo5YAnASwgHMA+ACisXCtIC44AldsJ2x4ANHACMjMQGs8PHLgCUaRnADewOFoS4ADoj6J46fh1LDcYyQG0FAXQDccAPTPDZi1ca28dsVAALMABXABtSOAAjAzZSYJBECJgwCQB+TW02GGCqCDg2M2tZXEdgAF8HYGAYPQMAMWCIEAAVfHQa-TAAMwRkGCdXTAUCYkQyCmo6JlYBTh5TQXMFLxk5OAVlVFUFoWWJb3tq2sMYVrQTnIhW-QwGptbGAbdxMQgwAHc4GngaClj4xJwLqCShgAC2MUQAEMoJAgA)

### 💻 Code

```ts
const test = <Key extends string>(record: Record<Key, 1>, key: Key) => {
    type Ret = Record<Key, 1>[Key]; // Record<Key, 1>[Key], should be reduced to 1?
    return record[key];
};

type FuncTy = typeof test; // <Key extends string>(record: Record<Key, 1>, key: Key) => Record<Key, 1>[Key]
type RetTy = ReturnType<FuncTy>; // 1, now it is reduced for some reason
```

### 🙁 Actual behavior

```ts
type Ret = Record<Key, 1>[Key];
```

is inferred to be of type `Record<Key, 1>[Key]` where I would expect the type to be reduced to `1`.
This seems to only happen when using a type parameter.

`Record<string, 1>[string]`, `Record<'a' | 'b', 1>['a']` and `Record<'a' | 'b', 1>['a' | 'b']` all produce the expected and reduced type `1`.

### 🙂 Expected behavior

I would expect `ReturnType<typeof test>` to be consistent with the type on the rhs of the `=>` symbol of the `typeof test` type, i.e. the fully reduced form.

**Comment by IllusionMH** [comment]
Is it just about type displayed in hover?

Because you can't assign `'1'` or `2` to `Ret`, only `1` can be assigned.

**Comment by nathsou** [comment]
Well it's not just about the display, since `Record<Key, 1>[Key] extends 1 ? true : false` should be `true`, but here we get the full type back. Does this answer you question?

**Comment by nathsou** [comment]
I see,

**Comment by andrewbranch** [comment]
It’s not safe to do the kind of eager reduction you’re looking for in general. I think in your example there’s not a strong counterexample specifically because the record value of `1` is a unit type. But in general, we _lose_ information when the type parameter `Key` goes away so we try to avoid that. The reduction you’re seeing with `ReturnType` is actually a much-bemoaned design limitation—it _can’t_ preserve the genericness of the type passed to it, which in many cases would be preferable.

**Comment by nathsou** [comment]
Makes sense, thanks for clarifying! I am closing the issue then as this is intended :)
