### ISSUE TITLE
Incorrent return type inference when using infer with generic function

### ISSUE THREAD

**Issue by user753** [microsoft/TypeScript#48820]
# Bug Report

```typescript
type ApplyFn<Fn extends (item: any) => any, T> =
  Fn extends (item: T) => infer R ? R : never

type X = ApplyFn<(x: number) => string, number>

```
type X is `string`
```typescript
type Fn = <T>(item: T) => {foo: T}
type Y = ApplyFn<Fn, string>
```
type Y is `{foo: unknown}` but I have expected `{foo: string}`

### 🔎 Search Terms

infer generic function return type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAgmYBsQDEB2AeNUIA9gVQBMBnKACgEt8BbALigENUQBKKAXgD5HmAaKACrd2AWABQUKFlz4ipSjXoC2XKBVQAzCACcoAJSgB+fVHqoIANx3jxoSFAAaHWPCRp0ZHGYCu1AEY6KtzEwNrqAOb8qL4B2py24NBY7FDoQgoQdIJBUADeGgD2BUoAvgn2AJrOcIgoGGj8IWGo4fFiQA)

Is there any workaround to solve this problem?

**Comment by craigphicks** [comment]
Probably not the level of generality you were hoping for but - 
```
type F1<T> = (item:T)=>{foo:T}
type Z = ReturnType<F1<number>>
```

**Comment by user753** [comment]
@craigphicks thanks. But I don't think it can help me. I want to create map function for tuples
```typescript
type ApplyFn<Fn extends (item: any) => any, T> =
  Fn extends (item: T) => infer R ? R : never

type Mapper<Tuple extends ReadonlyArray<any>, Fn extends (item: any) => any> =  {
  [Index in keyof Tuple]: ApplyFn<Fn, Tuple[Index]>
}

function tupleMap<T extends ReadonlyArray<any>,
  Fn extends (item: any) => any>(a: T, fn: Fn): Mapper<T, Fn> {
  return a.map(fn) as any
}
```

**Comment by harry0000** [comment]
@user753 

[playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFEAHANgUwLIENUA8AKopgB5SZgAmAzouANZhwDuYANIgGKkVV1EAChiUAtgC5ERAJSIAvAD5EuMAE9FQgLAAoRMjRYpAJUy5qCdGoCCAJ1u41xRR137gU7rpkmzFsFZ2Dk6mKLZgRGqomATcisoA3m6ItphhSCgYmAB0YvhCwDIA3LoAvrq6EAi0UIh5qPqNCgZZeKhCANoAjFwATFwAzAC6XEJgckrCCYjAcHBSSKUyxZXVtVVgNW3NmVhtnT2I-YjDKvQbNaPjCspC07PziIvLRUA)

```ts
function tupleMap<T extends unknown, F extends (item: T) => any>(
  tuple: ReadonlyArray<T>,
  f: F
): ReadonlyArray<ReturnType<F>> {
  return tuple.map(f);
}

const map      = tupleMap([1, 2, 3], (n) => ({ foo: n }));
const constMap = tupleMap([1, 2, 3] as const, (n) => ({ foo: n }));
```

**Comment by user753** [comment]
@harry0000 thanks, but I want it to work like this
```typescript
const tuple = ["foo", "bar"] as const
const convert = <T>(x: T): {item: T} => ({item: x})
const convertedTuple: [{item: "foo"}, {item: "bar"}] = tupleMap(tuple, convert)
```

**Comment by harry0000** [comment]
@user753 I recently answered the exact same question on Reddit, and my conclusion is no different than the answer to that question.

https://www.reddit.com/r/typescript/comments/u7qcdv/is_it_possible_to_map_an_array_literal_to_another/

> You can create such a type definition, but the type information of the order of the constant array will be lost when you use `Array.prototype.map()`, so you will have to cast it with `as` in the end.

[playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCuAHANgUxgXhgbQEQDMQRcAaGXAIwEMAnXAXRiohlEigG4BYAKF6gCeidABUkaALJVEAHhExUADyiowAExYAlVFTXhkAgII0aVATPhgA1mBAB3MAD4ymhctUaYx0+cs37Tpg49I6YvDAw8koq6iw0OnpgBjgAlmD4qDSRABJkAHQFaRlZIiL04REwAPyR4qhSsqVkItluMZ7QNGkA5jAAPjBg8AC2FJnVOAV5mmQA3jApKsMAXDAABgAksy0AvmswO4yrmo4VEce8-ELoAGJEAEK0AJJLQWIo9dIygsIg+HB1U48AD0wJws0WqBW5EIxB2c0h0MotFwh0uPDY0FY4AAbpkVGp3mhVncQI8aC8oUFsBV5ojVggPtgAAyMeG0hZLBl1bAARjZvHo3D4GPAWMSUBJD2erywjLQeWG0gAFCwMKFlXSuTAWDsAJR64WgyLXGAAci1UNWBCIuH65GodA4B2w9DNCxYtlgzAgKW6YCoFDQcBAcFNZviun0AnBnKtMNtzvhMEtSMduCTbryvGNkVo3VQsHiAEd4Cl4iwAEwKNDDVRQVV6mAUeCwCAgeA0YDoJUxgAWVDxMAydkyeWVlYAzJXK3qgA)

```ts
const tuple = ["foo", "bar"] as const;

type TupleMap<T extends ReadonlyArray<unknown>, R extends Array<unknown> = []> =
  T extends readonly [infer TH, ...infer TT]
    ? TupleMap<TT, TH extends string | number ? [...R, { item: `${TH}` }] : R>
    : R

type FooBar = TupleMap<typeof tuple>
// [{item: "foo"}, {item: "bar"}]

const convertedTuple: FooBar = [
  { item: tuple[0] },
  { item: tuple[1] }
];

const dont: FooBar = tuple.map(s => ({ item: s }));
// Type '{ item: "foo" | "bar"; }[]' is not assignable to type 'readonly [{ item: "foo"; }, { item: "bar"; }]'.
//  Target requires 2 element(s) but source may have fewer.(2322)
```

**Comment by user753** [comment]
@harry0000 Could you explain why we need Higher Kinded Types in this case? 
Why it's not possible to infer correct type?
```typescript
type ApplyFn<Fn extends (item: any) => any, T> =
  Fn extends (item: T) => infer R ? R : never
type Fn = <T>(item: T) => {foo: T}
type Y = ApplyFn<Fn, string>
```
The compiler knows that `Fn` type is `<T>(item: T) => {foo: T}` and when it `extends (item: T) => infer R` it could substitute string into it and get a correct type `(item: string) => {foo: string}`

**Comment by harry0000** [comment]
> The compiler knows that `Fn` type is `<T>(item: T) => {foo: T}`

This definition of `Fn` is the definition of a function that takes any type as an argument. Therefore, it must be guaranteed to execute no matter what type is passed as an argument based on its own constraints (definition). `T` is inferred to be `unknown` within the type definition, but this is unknown because we do not know what is actually passed to the function. Also, it actually can take any types to the function argument.

```ts
declare const f: Fn;

f();
// Expected 1 arguments, but got 0.(2554)
// const f: <unknown>(item: unknown) => {
//   foo: unknown;
// }

type P = Parameters<Fn> // type P = [item: unknown]
type R = ReturnType<Fn> // type R = { foo: unknown; }
```

What you are actually trying to do is pass `string` to `T` in `Fn`, but writing `Fn extends (item: string) => infer R` does not pass `string` to `T` in `Fn`, so `infer R` returns `{ foo: unknown; }`.

```ts
type Fn = <T>(item: T) => { foo: T }

// Since Fn can be executed even if a string type is passed, this "inheritance relationship" is valid.
type Y = Fn extends (item: string) => infer R ? R : never;
// type Y = { foo: unknown; }
```

Since the inheritance relation check only checks whether the inheritance relation is satisfied, in order to determine `T` in `Fn`, a type parameter must be passed to `Fn`, which is not possible because there are no Higher Kinded Types.

```ts
type Fn<T> = (item: T) => { foo: T }
```

**Comment by user753** [comment]
@harry0000 Thanks. Now I get it. The `<T>` was on the wrong side of the type and it should be
```typesctipt
type Fn<T> = (item: T) => {foo: T}
```
And it is possible in some way to solve `ApplyFn` problem
```typescript
type ApplyFn<Fn extends (item: A) => R, T, A = any, R = any> =
  Fn extends (item: T) => infer R ? R : never
 
type Y = ApplyFn<Fn<string>, string> 
```
Do you know by any chance if it is possible to write `tupleMap` with HKT emulation? Like
https://github.com/gcanti/fp-ts/blob/master/src/HKT.ts

> Why did you mistakenly think that you could pass any type to the type parameter of a generic function by checking the inheritance relationship with extends? From your experience with other programming languages? (just my interesting)

I thought `type Fn<T> = (item: T) => {foo: T}` is the same as `type Fn = <T>(item: T) => {foo: T}` but I'm not sure why.

**Comment by harry0000** [comment]
@user753 

> Do you know by any chance if it is possible to write tupleMap with HKT emulation?

Unfortunately, no. 

If you use fp-ts, you can simply write the following, but as I mentioned before, the type information of the tuple order will be lost, so you will have to cast it with `as` in the end.

[playground](https://www.typescriptlang.org/play?jsx=0#code/JYWwDg9gTgLgBAKjgQwM5wGZk1CI4BEWAtDKgQNxwD01m0cAJhAO4B2ANhMo8GwOaESZAnBARGAVw4BTODACeYOYxkY+wGMAhtUAWABQoSLEQp0AJQDyAQRx4hYUqmodgAI2oWZPHRwU2UFDICpSGhgDGOqjwMJJgsnAAvHAA2kQQEAQANITuyFA5eZIAXgQAuuZwUbowFOEGNTFwwKpsWorJcAA8ACoAfAAUwABccL0AlMn9LfWN0fCt6CnWNgB0IMhgw20dChODcQkyE3O01QstjKhjUD7MnApwgxlZcAA+eQWinwTupQQJqlyg0mosYDIQABZLbKKBdPpDTSQsaTabPADeLQh+AAvqdIpdkSBlnBVhstsMcTCwHCDkdZASDOcwdjITc4HdfI84BjiWNXj8voUPsUyrjgUA)

```ts
import * as ROA from "fp-ts/lib/ReadonlyArray";

const tuple = ["foo", "bar", "buz"] as const;

const identity = <T>(i: T) => i;
const ids = ROA.map(identity)(tuple);
// const ids: readonly ("foo" | "bar" | "buz")[]

const itemMapper = <T>(item: T) => ({ item });
const items = ROA.map(itemMapper)(tuple);
// const items: readonly {item: "foo" | "bar" | "buz"}[]
```
