### ISSUE TITLE
how to import without type checking

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#4882]
I have a bunch of modules which are auto generated.
For these modules, obviously there is no separate typescript declaration file. So when i try to import them in my typescript file, the compiler give an error msg.

Sample directory structure:

```
src
- main.ts
- templates
- - test.html.js
```
Sample code:

```
import React = require('react');
import test = require('../templates/test.html');
```

Here line 2 will give an error cause there is no typescript definition for `'../templates/test.html'` module.

How do i use the module inside typescript?

The modules are in common-js format and I am generation ES5. Using typescript 1.6

**Comment by DanielRosenwasser** [comment]
You can use

```TypeScript
declare var require: Function;
var test: any = require("react");
```

**Comment by pdeva** [comment]
Did you even read the question?
First off, the issue is not with `require("react");`, its with ` require('../templates/test.html');`.
Also the issue is not with the type of 'test', its with typescript not finding a declaration for  `'../templates/test.html'`.

**Comment by pdeva** [comment]
Even after modifying with your code:

```
import React = require('react');
declare var require: Function;
import test = require('../templates/test.html'); 
```
I still get the error

`Cannot find module '../templates/test.html'`

**Comment by kitsonk** [comment]
These sorts of general questions are probably better on StackOverflow...  Especially since you are trying to combine React and TypeScript, you need a broader audience of people to help you.

I suspect you will need to declare an ambient module for your project.  So somewhere as part of your project, you should have a `.d.ts` that would contain something like this:

```typescript
declare module '../templates/test.html' {
    export var index: any;
}
```

Or some sort of type that is meaningful in your code.

**Comment by DanielRosenwasser** [comment]
> `import test = require('../templates/test.html'); `

It looks like you didn't read my answer. I used a `var`, not an `import`.

> `'../templates/test.html'

I suspect that if you're trying to get the textual content of a file, then you want to use [`readFile`](https://nodejs.org/api/fs.html#fs_fs_readfile_filename_options_callback). If there's something about `require` that I'm not aware of, then others might be able to help better.

> Did you even read the question?

Please watch your tone in the future.

And as @kitsonk mentioned, these sorts of questions are more well-suited for StackOverflow.
