### ISSUE TITLE
Unable to resolve self-reference imports in js files

### ISSUE THREAD

**Issue by conartist6** [microsoft/TypeScript#48826]
# Bug Report

It does not seem to be possible (that I can tell) to get typescript to understand a self-reference import in a `.js` file which is being checked, e.g. due to the presence of a `// @ts-check` comment.

### 🔎 Search Terms

Self-reference import js @ts-check

### 🕗 Version & Regression Information

Version: `4.7.0-dev.20220424`

### 💻 Code
`js-self-ref-test/package.json`:
```json
{
  "name": "js-self-ref-test",
  "exports": {
    ".": {
      "default": "./lib/index.js",
      "types": "./lib/index.d.ts"
    }
  },
  "devDependencies": {
    "typescript": "^4.7.0-dev.20220424"
  },
}
```
`tsconfig.json`:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "rootDir": ".",
    "moduleResolution": "nodenext"
  }
}
```
`test.js`:
```js
// @ts-check
import 'js-self-ref-test'; // Cannot find module 'js-self-ref-test' or its corresponding type declarations. ts(2307)
```
### 🙁 Actual behavior

`Cannot find module 'js-self-ref-test' or its corresponding type declarations. ts(2307)`

### 🙂 Expected behavior

No error

**Comment by andrewbranch** [comment]
Your JS file isn’t included by that tsconfig.json, so it’s just getting default settings from your editor, which doesn’t include `--moduleResolution nodenext` which is the thing that makes this work. If you add `allowJs: true`, I think it should start working.

**Comment by conartist6** [comment]
Thank you, it works!
