### ISSUE TITLE
Add `Array.prototype.findLast` and `Array.prototype.findLastIndex`

### ISSUE THREAD

**Issue by yume-chan** [microsoft/TypeScript#48829]
# lib Update Request

## Configuration Check

My compilation *target* is `ES5` and my *lib* is `ESNext`.

## Missing / Incorrect Definition

Missing `Array.prototype.findLast` and `Array.prototype.findLastIndex`

## Sample Code

```ts
[3, 2, 1].findLast(x => x > 2);
```

## Documentation Link

Proposal: https://tc39.es/proposal-array-find-from-last/ (currently stage ~~3~~ 4)
Can I Use: https://caniuse.com/mdn-javascript_builtins_array_findlast (Chrome and Safari already shipped it without flags)

**Comment by andrewbranch** [comment]
[Double checking with @DanielRosenwasser that stage 3 is the only criteria for adding to lib.esnext]

**Comment by DanielRosenwasser** [comment]
It is, but if I ask for stage 4 at an upcoming meeting we might as well add it to a stable version.

**Comment by fatcerberus** [comment]
Seems weird that Firefox hasn’t implemented it yet, that’s a bit unfortunate.

**Comment by Kingwl** [comment]
> Seems weird that Firefox hasn’t implemented it yet, that’s a bit unfortunate.

Sorry....My fault.

**Comment by DanielRosenwasser** [comment]
@fatcerberus, the context is that @Kingwl is contributing the changeset to Firefox.

By the way, we reached Stage 4 today! 🎉🎉🎉

I believe that means we should add this to `lib.es2023.array.d.ts`.

**Comment by monikams** [comment]
With which version of typescript I could use the method findLast?

**Comment by juniorbotelho** [comment]
@monikams I found a temporally solution for this problem, just create a `global.d.ts` file in anywhere of your project and type this code:

```typescript
export {}

declare global {
  interface Array<T> {
    findLastIndex(
      predicate: (value: T, index: number, obj: T[]) => unknown,
      thisArg?: any
    ): number
  }
}

```

Ready! You can use this approach without wrongs from your typescript linter.

**Comment by RedGuy12** [comment]
This is in Node LTS v18.0.0

**Comment by RamonBalthazar** [comment]
Is adding these methods a breaking change? Why has this been moved to the 5.0 milestone? Thanks
@DanielRosenwasser

**Comment by andrewbranch** [comment]
5.0 is just the next release.

**Comment by jez9999** [comment]
Has this been added for 5.0?  I'm really wanting to use `findLastIndex` and according to [this](https://caniuse.com/?search=findlastindex), all modern browsers support it.

**Comment by DutchKevv** [comment]
Any updates? 

Its a bit funky that we still have to include a custom typing for this...

**Comment by DanielRosenwasser** [comment]
It's in TypeScript 5.0 beta and the nightlies. The target release dates are available [here](https://github.com/microsoft/TypeScript/issues/51362).

**Comment by jez9999** [comment]
Well I upgraded my project to Typescript 5.0.2 today and hoped the errors would go away but nope, I still get:

> Property 'findLastIndex' does not exist on type 'MoveDelta[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2023' or later.

If I try setting that in my tsconfig.json:

```
	"compilerOptions": {
		"lib":["es2023"],
	}
```

I get the build error:

> Parsing error: Invalid value for lib provided: es2023

Can anyone help me out?  What am I doing wrong?

**Comment by DanielRosenwasser** [comment]
Given the error message, it sounds like you need to upgrade your version of typescript-eslint.

**Comment by jez9999** [comment]
> Given the error message, it sounds like you need to upgrade your version of typescript-eslint.

It seems to be TS itself giving the error.  In VS code, the error is suffixed with "ts(2550)".

**Comment by DanielRosenwasser** [comment]
I'm not sure - if you can validate that your editor is using the latest version of TS (you can select the workspace version)

![image](https://user-images.githubusercontent.com/972891/225742732-c042f455-8e2a-4eed-8a84-69d228ecec80.png)

and that you see the same errors when all other extensions/plugins are disabled, then I would file a separate bug.

**Comment by jez9999** [comment]
Well it's not using that dev version but it is using the 5.0.2 workspace version.  Should that have it?

**Comment by cristan** [comment]
It works on TypeScript 5 at least at the playground typescriptlang.org: [example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBADgUxHANgmBeGBtAUDAmAbwDMBLAJ2gDkBDAWwQC4YAiAQRTOAVYBp8hGLQDmzGAGYArIIIBfAUNKUaDcawBCIAEb9ZBUeIkAmfXNwBdXLlCRYJEAFcwAE0zwkqBADpyrgDK00AAUcJgAfPDehjCRAIwADACUgkA). It doesn't say much though: it also works just fine if you select Typescript 4.

Also note that you'll need at least Node.JS 18, as that's the lowest version that supports `findLast` ([source](https://node.green/#ES2023)).

**Comment by BR0kEN-** [comment]
It works only in TS 5 and only when the `target` is `ESNext`.

**Comment by juneate** [comment]
> It works on TypeScript 5 at least at the playground typescriptlang.org

Incorrect, as you can see here:
![image](https://user-images.githubusercontent.com/5200976/234355264-b0ac5259-830f-4cb0-b35d-06df74639ea9.png)

As @BR0kEN-  said, if you change the `target` in that environment, the issue disappears. But if you try to "Export" the example to CodeSandbox with the same settings, it triggers the issue again.

![image](https://user-images.githubusercontent.com/5200976/234356410-64fb769f-ef0f-4d67-a454-09a873a4a00f.png)

Tried also updating to the latest Typyscript `5.1` build, no change.

**Comment by cristan** [comment]
findLast was introduced in EcmaScript 2023. However, `es2023` isn't supported in Typescript 5. Maybe that's it?

<img width="1027" alt="es2023 not supported" src="https://github.com/microsoft/TypeScript/assets/490738/7f672ca7-fab4-47d2-abc5-4ae72e61a741">

**Comment by shakedhagag** [comment]
Is there any progress with this issue?

**Comment by jacobbogers** [comment]
Is there any progress on this issue?

**Comment by RyanCavanaugh** [comment]
There's not progress because it was fixed in 2022. If you're not seeing `findLast` / etc, you have a configuration issue. Seek support at StackOverflow, Discord, etc.

**Comment by cristan** [comment]
Ah, it indeed does work, but the problem is indeed that `findLast` was introduced in EcmaScript 2023. You'll [need](https://node.green/#ES2023) Node.JS 18 or higher for that, but that that isn't much of a problem. TypeScript is slightly more problematic:

Setting the target to es2023 even in TypeScript 5.3.3 yields [the same error I had before](https://github.com/microsoft/TypeScript/issues/48829#issuecomment-1607525476). However, `findLast` does work when setting the target to `esnext` ^_^

In [the handbook](https://www.typescriptlang.org/docs/handbook/modules/reference.html#summary-1), you'll see that `es2023` is indeed not an option. It also states: "esnext is a moving target that may include support for Stage 3 proposals to ECMAScript modules". So I would much rather set the target explicitly to `es2023` instead to this vague concept, but hey, it works.

**Comment by RuslanLeafio** [comment]
here is the solution

make the declaration under your code with findLastIndex

   Array.prototype.findLastIndex = function(predicate) {
      for (let i = this.length - 1; i >= 0; i--) {
        if (predicate(this[i], i, this)) {
          return i;
        }
      }
      return -1;
    };

and it will fix your issue

**Comment by traez** [comment]
> Compile Error Line 31: Char 32: error TS2550: Property 'findLastIndex' does not exist on type 'string[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2023' or later.

Got above on my LeetCode solution https://leetcode.com/problems/increasing-decreasing-string

MDN says 
> "Baseline 2022 Newly available Since August 2022, this feature works across the latest devices and browser versions. This feature might not work in older devices or browsers."

So I guess that's why. Leetcode yet to update their transpiler/compiler
