### ISSUE TITLE
Reduce breaks undefined check in upper scope

### ISSUE THREAD

**Issue by m1lk1way** [microsoft/TypeScript#48839]
# Bug Report

### 🔎 Search Terms

reduce breaks undefined check in upper scope

### 🕗 Version & Regression Information

4.6.2

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about reduce

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gW2gXigbwFBW1MBDEAGzjwBMAudLHGgMzjgH5LMa2cAjPAJ2agGdg3AJYA7AObV2AXwDcUqHIzSMAYzijBUPJXhIoqVjnxESFKu2z04LBZahdulAESPndnNIA0ClSrUaWuIQwABCPAZQABQAlAYAfBY4wrTReAB0JsRk6dZQAGT52pkE2aS5DOmOcUbs3CEArtyixVlmFXBVPPI0KjT1wE0tzqJwDjzu-uqawFDBYTwATJGxCUnYKWklpjl5ha2l7dZd3DUe2ANDUADaAIwAuun1pA2qEFGryIm19lCXzQcduVjo4epZvFBnM4YmDsNIoAp-sNRuNuJMgA)

### 💻 Code

```ts
type Some = {
    payload: {
        foo?: {
            bar?: string
        };
    };
}
const a: Some = {
    payload: {
        foo: {
            bar: "bar"
        },
    }
}

const getBar = () => {
    if (a.payload.foo && a.payload.foo.bar) {
        return a.payload.foo.bar;
    }
    return "no bar"
}

const getBar2 = () => {
    if (a.payload.foo && a.payload.foo.bar) {
        return [1].reduce(() => {
            return a.payload.foo.bar;
        }, "");
    } 
    return "no bar"
}
```

### 🙁 Actual behaviour

error a.payload.foo Object is possibly 'undefined'.

### 🙂 Expected behaviour
there is no error as it was checked inside of if statement;

**Comment by MartinJohns** [comment]
Another duplicate of #9998. See also: [Issue template 'types not correct in/with callback'](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/types-not-correct-in-with-callback.md)

**Comment by m1lk1way** [comment]
@MartinJohns Thx for pointing, problem appeared more wide. Will follow the issue there.
