### ISSUE TITLE
Merged declaration of construct signature does not work for function

### ISSUE THREAD

**Issue by 3axap4eHko** [microsoft/TypeScript#48830]
# Bug Report

### 🔎 Search Terms
```
typescript declaration merging function
```
[Please see Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)

### 🕗 Version & Regression Information
```
$ yarn tsc --version
Version 4.6.3
```

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about declaration merging

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=4.6.2#code/PTAEFEGUDZQYwDYEMDOLQFMAeSC2AHBDAKGIEsA7AFwwCcAzJODUAWQE9xoBhZNUAN7FQI0AAoAlAC5QANwD2ZACYBuUCFBEqAcnSoUAV1wsyO9HCQJkAIyKgkFJaFOgA7vNoBrdBlkYKzvSgAJLwDtpUYVbOVMQAvsSI+mycPHzoAqDCorjsrBhUABbyTgC8oAByRtZ0KvGJ8hQokblQafrBTVQOzKDlFBiuKVy8+pJ1pBoAYgYUcFRkjfDpmDgEROTUdIy9HDNzC42j-EKioAOukjJ7s-OLFMcoahpauvZoRiyFdCaRhaj2eCNZq0AzzDzZES5fJFEpXOSKVT1Yj0W6HAI3A73R5iIpkFDXdj7O5HdISQSQ0B4lAAOmhBWKZUq1VqyLgwJa7EenWaPRY-UGKWJ6JxEjqGm0F20q3wtAwaHuABo3MUUCxurQAOYFTRMbyA9ldUHzUAoMiaihIKgGOXKsjrMhwUwIdigf56ALaBzsaVUdj4DA0kLoFxUUEYAD8pGIGgAImRaH77I5zqgk2HHfqqPJQLgkJ5fm4PJ4Gl0UvHE+wAIKOCpprkrcqorFLDgVv01pR15oNsbUwnC7Fkilnal0vIMkp9Zm4Gq0OpnOXW2gBal1OLvZOugGYkkPdITQ3NXPsdvV2v17ldPnTi7lhMdi890UTIA)

### 💻 Code

```ts
// Function class example
interface MyFunctionClass {
    new(): MyFunctionClass; // let's assume here it has a constructor
    myMethod(): void;
}

function MyFunctionClass(this: MyFunctionClass) {
    this.myMethod = Number;
}

const myClassInstance = new MyFunctionClass();
// 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type
```

### 🙁 Actual behavior

displays error ` 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type`

### 🙂 Expected behavior

Since declaration merging should work because it's not the case in `Disallowed Merges` section.
I should be able successfully create my function class

**Comment by jcalz** [comment]
I don’t see any declaration merging happening here.  Function statements do not  bring type names into scope the way class statements do.  But maybe I’m just confused because the example is so strange.  What kind of class constructor produces instances which are also class constructors? Like, what specifically are you trying to accomplish here?  I think you need to spell it out because it’s not obvious.

**Comment by 3axap4eHko** [comment]
@jcalz exactly, I believe the declaration of the interface should be merged with the function declaration of the same name. Otherwise, there is no other way to create a function class as it is supported by javascript itself.

**Comment by 3axap4eHko** [comment]
Basically, I just need to make work only this part
```ts
function MyFunctionClass(this: MyFunctionClass) {
    this.myMethod = Number;
}

const myClassInstance = new MyFunctionClass();
```
But looks like typescript does not infer the inner methods of the function, so I need to define them through an interface

**Comment by fatcerberus** [comment]
@jcalz They’re expecting the function to act as the constructor for the interface.

**Comment by fatcerberus** [comment]
@3axap4eHko That `new()` signature won’t work there - that means that, given a `MyFunctionClass` *instance*, you can call it with `new`.

**Comment by 3axap4eHko** [comment]
@fatcerberus but in js, it is working as a constructor. A class even transpires to a function if you use something like es5 settings. 
```ts
class A {}
```
turns to
```js
var A = /** @class */ (function () {
    function A() {
    }
    return A;
}());
```
What is the solution to allow the function to act as a constructor?

**Comment by Josh-Cena** [comment]
Why not... an actual class declaration, if you don't need it to be callable?

```ts
declare class MyFunctionClass {
  constructor();
  myMethod(): void;
}

function MyFunctionClass(this: MyFunctionClass) {
  this.myMethod = Number;
}

const myClassInstance = new MyFunctionClass();
```

**Comment by DavidTDC3377** [comment]
- [ ] CLOSE
Duplicate of #48249

**Comment by jcalz** [comment]
Okay so then there's no bug here, right?  TS is working as intended.  It's certainly interesting to look at how to get a function statement to act as a constructor, but that's a question or maybe a feature request (if `declare class` is not acceptable for some reason).  So maybe @3axap4eHko should close this unless there's some evidence of a compiler bug here?

**Comment by 3axap4eHko** [comment]
@jcalz there is a bug, just take a look. Merged declaration works with `function` and `declare class`, it also works with `interface and `class`, but it does not work for `interface` ad `function`

**Comment by Josh-Cena** [comment]
@3axap4eHko Your code is invalid semantic. A constructor is fundamentally different from an instance, so you may want to update your example so as not to confuse others and hide away the real bug. For example, [this is a better example](https://www.typescriptlang.org/play?ssl=12&ssc=33&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgLIE8BiBXECzAD2IAwgDZwDOlyA3gFDLIgQDuyAFAJQBcaWufEVIVqASRCUwcPBADc9AL70YggsX4486kVUocwAC2CU+GLUOLk9EqTKRc6jZEZMA6ALbpUEI4QAmyAC8yABy2B4ARtAKyvSgkLCIKOZqwtbiktKyTkxePn7+3HwAboTA-rH09AjEUshwwcxsmmlWovpcCkA):

```ts
interface MyFunctionClass {
  new (): MyFunctionClassInstance;
}
function MyFunctionClass(this: MyFunctionClassInstance) {
  this.myMethod = Number;
}

interface MyFunctionClassInstance {
  myMethod(): void;
}

const a = new MyFunctionClass(); // 'new' expression, whose target lacks a construct signature,
```

**Comment by MartinJohns** [comment]
Interface declares a type. Function declares a value. There's no overlap.

**Comment by 3axap4eHko** [comment]
@MartinJohns 
```ts
function buildLabel(name: string): string {
  return buildLabel.prefix + name + buildLabel.suffix;
}
namespace buildLabel {
  export let suffix = "";
  export let prefix = "Hello, ";
}
```
`function` is a value and `namespace` is a type, so why does it work here?

**Comment by 3axap4eHko** [comment]
@MartinJohns thank you! Now I get it. `function` does not declare a type, but a value. So this shouldn't work
```ts
function A() {}
const a: A = () => {};
```
But how does it work, if `Function` is a function but it can be used as a type and it has construct signature?
```ts
const a: Function = () => {};
const b = new Function();
```

**Comment by 3axap4eHko** [comment]
@jcalz you are right it's not a bug, but just requires a lot of effort. So to make it work I need to define it like this
```ts
interface A {
    (): void;
}

function A() {
    const a = () => 'test';
    a.myMethod = Number;
    return a;
}

declare class A {
    myMethod(value?: any): void;
}

const a = new A();
console.log(a(), a.myMethod(123)); // 'test' 123
```
Thank you so much, gentlemen, it was a pleasure to talk with you!
