### ISSUE TITLE
Accessing base class field through super should be disallowed

### ISSUE THREAD

**Issue by Josh-Cena** [microsoft/TypeScript#48832]
# Bug Report

### 🔎 Search Terms

Super, class, field, property

Related: https://github.com/microsoft/TypeScript/issues/45712, https://github.com/microsoft/TypeScript/issues/42215, which are about allowing legitimate accesses, while this is about disallowing illegal access.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about classes

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=4.0.5#code/MYGwhgzhAECC0G8BQ1pmgXmgRgNxIF8klRIYAhaAUwA8AXKgOwBMZ5lVgwRgAKASkQpU0APSjoEAK4AHKgCcAdOgAWkaHQCec6IykBbAEYKANNENS6klQHspIZuarRmASwjcQNgO5VmwzhtGCCt0LGk5JXQAahx8VCIiJEYqb2hyAUUuHgF8IA)

### 💻 Code

```ts
class A {
  a = 1;
}

class B extends A {
  calc() {
    // super.a has type number, but should be disallowed
    const a = super.a + 1;
  }
}

new B().calc();
```

### 🙁 Actual behavior

I'm allowed to access `super.a`, which is undefined at runtime.

### 🙂 Expected behavior

It should be forbidden, because `super` is an alias for `instance.__proto__.__proto__`, which is `A.prototype`, not an instance of `A`.

**Comment by Josh-Cena** [comment]
I think this is due to the fact that TS has no concept (afaik) of the prototype chain. It thinks `super` means any instance of `A`.

**Comment by MartinJohns** [comment]
Duplicate of #35314. Used search terms: `super in:title`

**Comment by Josh-Cena** [comment]
Oh, oops, used too many keywords in my query. Thanks for pointing out.
