### ISSUE TITLE
Indirect narrowing of destructured discriminated union types works only for trivial cases.

### ISSUE THREAD

**Issue by DaviDevMod** [microsoft/TypeScript#48846]
# Bug Report

Narrowing destructured discriminated union types using [indirect control flow](https://www.refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html), works only for trivial cases in which the discriminant is a union of at most two types.

I found many issues related to discriminated unions, but they describe different problems.

### 🔎 Search Terms
discriminated 

### 🕗 Version & Regression Information

[Control Flow Analysis for Destructured Discriminated Unions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/#cfa-destructured-discriminated-unions) has been introduced (or fixed) in TypeScript 4.6

The bug has been tested with the currently most recent version in the TypeScript Playground, which is v4.6.2

### ⏯ Playground Link

The discriminant is a union of at most two types: [indirect narrowing works as expected](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAJlAvFA5AFQIIDkDiAogEoCSuh6UAPhgArYDKO6A3ALABQokUAwgFdgAGwgAnEKgwwA8sQDSVWukZ0ZM3Gy5ce0ALIQAhsKkBvKADMEiAFwYcBEuUqsoAYyGiJAfjsA7CAA3cSgAXxoocyskO3QGZmw2d09xEDtBEVSwjk4uCwE-N2AASzg-KCNgAAoo6wAaZMyJMLsDYwBKSK4oKGKLKCro5BQR+zwiMgp0TrEIYAExco8mkBye2fnFxq9VnoB6Pf44MVmi4Uk-QxO4AHcIRC5QoA).

The discriminant is a union of at least three types: [indirect narrowing fails](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAJlAvFA5AFQIIDkDiAogEoCSuh6UAPhgArYDKOVt6dpAWp9ugNwBYAFChIUAMIBXYABsIAJxCoMMAPLEA0qwyM6q1bn7Dho6AFkIAQxnKA3lABmCRAC4MOAiXKUa9Lj34oAGNpOUUAfjcAOwgANwUoAF9feyckN3YmFj5g0IUQNylZfKTBIWEHSSig4ABLOCioK2AAClTnABpc4sUktwtrAEooW2EoKFqHKBa05BR59zwiMgp0Yah5CGBJeUaQnpAy8cnp2dQF9n9edc3t3e6ww7GNrZ29vMUcqAB6b6hcODAKBRSzyeRwADuEEQwkSQA).

### 💻 Code

The discriminant is a union of at most two types and **indirect narrowing works as expected**:
```ts
type Food = 'TANGERINE' | 'PASTA';
type Cutlery = 'FORK' | 'SPOON';

type Meal = { food: 'TANGERINE'; cutlery?: never } | { food: 'PASTA'; cutlery: Cutlery };

function eat({ food, cutlery }: Meal) {
  if (food === 'TANGERINE') return cutlery;
  return cutlery;  // Correctly narrowed
}
```
The discriminant is a union of at least three types and **indirect narrowing fails**:

```ts
type Food = 'TANGERINE' | 'PASTA' | 'PIZZA';
type Cutlery = 'FORK' | 'SPOON';

type Meal = { food: 'TANGERINE' | 'PIZZA'; cutlery?: never } | { food: 'PASTA'; cutlery: Cutlery };

function eat({ food, cutlery }: Meal) {
  if (food === 'TANGERINE')  return cutlery;
  if (food === 'PIZZA')  return cutlery;
  return cutlery;  // Not narrowed
}
```

### 🙁 Actual behavior

Indirect narrowing doesn't work on destructured discriminated union when the discriminant is a union of at least three types.

### 🙂 Expected behavior

Destructured discriminated union should be narrowable indirectly, no matter how many types are involved in the discriminant.  
If an implementation for a discriminant composed by an arbitrarily large number of types is not possible, I hope it is possible to at least raise the bar to five or even twenty types.

**Comment by DaviDevMod** [comment]
Just noticed that removing `?` from `cutlery` makes the narrowing work as expected.

However there was a reason for having that optional `never`: if the property is required, calling the function becomes a mess.

Check this [Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAJlAvFA5AFQIIDkDiAogEoCSuh6UAPhgArYDKO6A3ALABQokUAwgFdgAGwgAnEKgwwA8sQDSVWukZ0ZM3Gy5ce0ALIQAhsKkBvKADMEiAFwYcBEuUqsoAYyGiJAfjsA7CAA3cSgAXxoocyskO3QGZmw2d09xEDtBEVSwjk4uCwE-N2AASzg-KCNgAAoo6wAaZMyJMLsDYwBKSK4oKGKLKCro5BQR+zwiMgp0TrEIYAExco8mkBye2fnFxq9VnoB6Pf44MVmi4Uk-QxO4AHcIRC5Q7U5KmstrWIcJ5ypQ9pzXrUYvQmCwGssdrFZAp0H8ckA), remove the question mark and watch the evil error unfold.

The problem here may not be the one I initially thought of. Should I modify the issue or open a new one?

**Comment by whzx5byb** [comment]
To create a discriminated union, you must have a common **literal** property. But `food: 'TANGERINE' | 'PIZZA'` is not a literal, it's a union. Separating them will make your example work.

```ts
type Meal = { food: 'TANGERINE'; cutlery?: never } | { food: 'PIZZA'; cutlery?: never } | { food: 'PASTA'; cutlery: Cutlery };

```

**Comment by MartinJohns** [comment]
See also: #43026

**Comment by DaviDevMod** [comment]
> To create a discriminated union, you must have a common **literal** property. But `food: 'TANGERINE' | 'PIZZA'` is not a literal, it's a union. Separating them will make your example work.
> 
> ```ts
> type Meal = { food: 'TANGERINE'; cutlery?: never } | { food: 'PIZZA'; cutlery?: never } | { food: 'PASTA'; cutlery: Cutlery };
> ```

Oh I see. But anyway it's worth noting that if you always use direct guard clauses `if (food === 'TANGERINE')` rather rely on `return`s, the union of literals as discriminant works fine and it's narrowed.

Since unions of literals as discriminant already work, under certain circumstances, wouldn't be reasonable to have them fully implemented? (Mainly to simplify the declaration of the discriminated union, which may get unnecessarily verbose if the discriminant is a union of many literals)

**Comment by MartinJohns** [comment]
> Since unions of literals as discriminant already work, under certain circumstances, wouldn't be reasonable to have them fully implemented?

See specifically: https://github.com/microsoft/TypeScript/issues/43026#issuecomment-789220358

**Comment by DaviDevMod** [comment]
@MartinJohns thank you for the link. That issue is marked as `Design Limitatoin` and though I find it hard to believe, I can't say anything regarding it's complexity and it surely is not a priority as one can work his way around the problem.

I am closing the issue.
Thank you so much for the support!

**Comment by fatcerberus** [comment]
The way to think about it is that, in this type:

```ts
type Meal = { food: 'TANGERINE' | 'PIZZA'; cutlery?: never } | { food: 'PASTA'; cutlery: Cutlery }
````

Logically, this type represents the disjunction `TangerineOrPizza | Pasta`.  The first member of this sum type *contains* a union type as a property, but is, as a whole type, indivisible.  So from there the logic goes:

```ts
function eat({ food, cutlery }: Meal) {
  if (food === 'TANGERINE')  return cutlery;
  // what is food?  it's not tangerine, but might be pizza.  therefore, still TangerineOrPizza | Pasta
  if (food === 'PIZZA')  return cutlery;
  // again, what is food?  it's not pizza, but (as far as TS knows) might be tangerine;
  // the fact that it isn't tangerine couldn't be preserved in terms of types alone (see above)
  // therefore, we STILL have TangerineOrPizza | Pasta
  return cutlery;  // end result: this is not narrowed
}
```

In order to deal with this problem, the type system would need to explode object types containing unions, e.g. `{ type: "foo" | "bar" }` becomes `{ type: "foo" } | { type: "bar" }` (essentially synthesizing `Tangerine | Pizza` from `TangerineOrPizza`), but this would be combinatorially explosive for objects containing multiple union-typed properties.  Hence the design limitation.

**Comment by DaviDevMod** [comment]
@fatcerberus thanks for the insight!

The problem of explosive types can be solved by setting a reasonable limit to the number of expanded types (like when your infinite recursion exceeds the maximum call stack size). 

Regarding the fact that the expanded types may not be an equivalent representation of the original union, how it comes? 
There would be a predictable algorithm to follow (which presumably is the same algorithm I use to get the job done manually). What are the troubles you are foreseeing?

**Comment by fatcerberus** [comment]
> What are the troubles you are foreseeing?

The main theoretical one is that "the quantifier is in the wrong place", that is, uncertainty about the nature of a container implies uncertainty about its contents, but the inverse is not true.  By analogy: `Tangerine | Pizza` implies we don't know whether have a bag of tangerines or a pizza box (but if you can figure it out then you also know what's inside), while `TangerineOrPizza` implies a more universal container that might contain either (you have to actually open it to be sure).  Whether that actually matters in practice depends on the nature of the program in question, but is a valid distinction, and sometimes matters to the type system too (e.g. distributivity of conditional types).

**Comment by DaviDevMod** [comment]
I think I get what you are saying. A possible solution to this problem may be making available a syntax that gives the expressive power to state whether a union is meant to be considered `Tangerine | Pizza` or `TangerineOrPizza`.

Something like `Atomic<'TANGERINE' | 'PIZZA'>` would be treated as an indivisible unit during the expansion, while a regular union type `'TANGERINE' | 'PIZZA'` would be recursively expanded to its atomic constituents.

**Comment by fatcerberus** [comment]
Putting aside the nerdy theoretical details, I agree it’s a bit confusing that type guards don’t always compose in the obvious way.  They only compose if each individual guard is able to eliminate some member of a union.  Hence the seemingly contradictory situation of `meal.food` being correctly narrowed while `meal` itself isn’t.

Good news is that it might be possible to make a utility type that does the necessary expansion to make this work.  If I come up with something I’ll report back.

**Comment by DaviDevMod** [comment]
@fatcerberus I'm rooting for you.
