### ISSUE TITLE
Two dianostic information objects have the same code 5053

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#4884]
`Option_0_cannot_be_specified_with_option_1` and `A_tsconfig_json_file_is_already_defined_at_Colon_0` currently have code 5053 together, is this intended?

**Comment by jbondc** [comment]
Hmm probably not, I've been thinking recently it would be nice if ```diagnosticInformationMap.generated.ts``` would be generated & typed as:

```
        // All diagnostics codes
	const enum DiagnosticsCodes {
		Unterminated_string_literal = 1002,
	}

	export interface DiagnosticItem {
		code: DiagnosticsCode,
		category: DiagnosticCategory,
		key: string
	}

    export var Diagnostics: { [x: string]: DiagnosticItem } = {
```
Would be easier to visualise which codes are used by what.

**Comment by DanielRosenwasser** [comment]
Thanks guys!
