### ISSUE TITLE
Losing types when importing cjs module using default export with nodenext modules

### ISSUE THREAD

**Issue by wight554** [microsoft/TypeScript#48845]
# Bug Report

### 🔎 Search Terms

cjs typescript nodenext default export

### 🕗 Version & Regression Information

4.7.0-dev

While using nodenext with pure cjs modules, such as https://github.com/fastify/fastify-cookie or https://github.com/fastify/fastify-static , types are lost when using default export and cjs named export is prohibited

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
import fastifyCookie from 'fastify-cookie';
import fastifyStatic from 'fastify-static';

app.register(fastifyCookie);
app.register(fastifyStatic);
```

### 🙁 Actual behavior

```
import fastifyCookie
Argument of type 'typeof import("/.../node_modules/fastify-cookie/plugin")' is not assignable to parameter of type 'FastifyPluginCallback<any, Server> | FastifyPluginAsync<any, Server> | Promise<{ default: FastifyPluginCallback<any, Server>; }> | Promise<...>'.ts(2345)
```

### 🙂 Expected behavior

Type should not be lost while import
Can be workaround by 
```
import { default as fastifyCookie } from 'fastify-cookie';
import { default as fastifyStatic } from 'fastify-static';
```
But i'm not sure if that's expected or not

**Comment by andrewbranch** [comment]
Is your file a CJS or ES module? (If you’re not 105% sure: what is its file extension and what is its nearest package.json’s `"type"` key?)

**Comment by wight554** [comment]
> 

Fastify plugins are definitely CJS, the project I'm importing those to is ESM (type: "module", module: "nodenext", moduleResolution: "nodenext")
You can see in this PR: https://github.com/wight554/blog-template/pull/50

**Comment by wight554** [comment]
When using named import, TS successfully compiles, but node throws error:
```
file:///.../blog-template/dist/server/server.js:9
import { fastifyStatic } from 'fastify-static';
         ^^^^^^^^^^^^^
SyntaxError: Named export 'fastifyStatic' not found. The requested module 'fastify-static' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

**Comment by andrewbranch** [comment]
> Fastify plugins are definitely CJS

Yes they are, but their own types incorrectly declare a default export:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/3277153/165355276-485520a3-ccb6-4648-a511-03b93838d6cc.png">

**Comment by wight554** [comment]
> > Fastify plugins are definitely CJS
> 
> Yes they are, but their own types incorrectly declare a default export:
> 
> <img alt="image" width="690" src="https://user-images.githubusercontent.com/3277153/165355276-485520a3-ccb6-4648-a511-03b93838d6cc.png">

I see https://github.com/microsoft/TypeScript/issues/13626 is still open, so there's no way to specify type of default export
What's recommended way to do this for cjs modules?

**Comment by andrewbranch** [comment]
#13626 is not related to this. Fastify just wrote wrong types. Unfortunately the only thing to do is open an issue, fork and fix, or `@ts-ignore`.

**Comment by wight554** [comment]
> #13626 is not related to this. Fastify just wrote wrong types. Unfortunately the only thing to do is open an issue, fork and fix, or `@ts-ignore`.

Uh, I see that in this case, the only "easy" fix is to support named import for fastify-static and follow nodejs error recommendation
Like this:
```
import cookiePlugin from 'fastify-cookie';
const { fastifyCookie } = cookiePlugin;
```

BTW, shouldn't TS compiler throw error when trying to make named import of CJS module like node does in runtime?

**Comment by scott-lc** [comment]
@andrewbranch 

> but their own types incorrectly declare a default export

Can't you clarify what you mean by this?  Are `default` exports not supported in `nodenext`?
