### ISSUE TITLE
Bypass excess property error by assigning object to an untyped variable

### ISSUE THREAD

**Issue by RPuffer** [microsoft/TypeScript#48852]
# Bug Report

### 🔎 Search Terms

`bypass known property error object literal`

### 🕗 Version & Regression Information

Tested with all versions on the TS Playground from `3.3.3` -> `Nightly`

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "common bugs that aren't bugs"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220426#code/C4TwDgpgBAKhDOwCCATFBLY6D2A7AhgDYAKATtpKVglALxQDeAUFFANa7YDuuAXFIlLpcAcwDcTAL4SmAYzyIoAM1wB1TAAsY4CCiSkRdKAApg-OIlQYseImQoQq6BAEp+AN2zoUdAHyMWVih5XHhsQggAOkJsEVMXCUkmOQVgKAARbBgNCAs0+mM3KE9vPwDWEMVsACMAK3VgDStMHAISckpQI2Yg9k4efgByMA7HUEGAGkDWfDQW20IhkYcqEEnA6WTWAHptwGVyKE4oYHgoR3JSKGqIWQBXfHhoLmgwW7TG6Bram7ThKHxcFBbrhQJAfO58EJ8NUIgB+WGBFQNLQ6PQGYxfZHNGxteydEAJLZQXZQQAy5MdTudsJclNT-nMcUQoMt8VAuNsoF8flBCJhHEREWpNNowfo4gw+tw+FBhqNVpN6dZWkQlnLxlBJITAiSAMr4AC20Fplwe8HQIlwhpBx2wx1RxUh6GhEXggW1+0OtpOZ1IFyuN3ujzZLzexxynLq3L+AKBIPtEKhMIg8MClXeqIA8pHZGZYAhkAzle0VtRTvRMZpsUW8WMQBJWO6yRSfX7jYr5m1mWqQGyOVyczy+aQBRVUnawVnvjmAEzmfNVhY1pw0egSjhS1UltYTduMxYylm1wYaxLJTLZXL5wpiIA)

### 💻 Code

```ts
type TestAdditionalProperties = {
  known: string;
};

const fnWithTypedArg = (t: TestAdditionalProperties): void => {
    console.log(t);
}

const DoTheTest = (): void => {
  const objWithAdditionalProperty = {
    known: 'property',
    additional: 'property',
  };

  //❓ no ts error becuase we put the object in an untyped variable??
  fnWithTypedArg(objWithAdditionalProperty);

  // ❌ ts error for additional property w/ object literal
  fnWithTypedArg({ known: 'property', additional: 'property' });

  // Same for assignment to typed variables
  
  //❓ no ts error becuase we put the object in an untyped variable??
  const typedObject: TestAdditionalProperties = objWithAdditionalProperty;
  
  // ❌ ts error for additional property w/ object literal
  const typedObject2: TestAdditionalProperties = { known: 'property', additional: 'property' };
}

DoTheTest();
```

### 🙁 Actual behavior

- when assigning an object to a typed variable or as a typed function param
- if the object is first assigned to an untyped variable
- then there is no error for additional properties on said object

### 🙂 Expected behavior

- when assigning an object to a typed variable or as a typed function param
- if the object is first assigned to an untyped variable
- then there should be an error if the assigned object contains additional properties

This is especially dangerous (and was originally found) when working with typed GraphQL mutations.  This allowed a bug to slip through where an additional property was being passed to the `variables` of a GrqphQL mutation, which then threw an error when invoked.

Obvious workaround is typing all variables, but I would have expected the inferred type to catch this.  It seems odd that one layer of abstraction (literal -> variable) can bypass the expected error.  Maybe i'm missing something where this makes sense to allow?

**Comment by andrewbranch** [comment]
https://github.com/microsoft/TypeScript/pull/3823 / https://github.com/microsoft/TypeScript/issues/16712 / https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks (apparently this section didn’t make it into the updated handbook 😕)

**Comment by MartinJohns** [comment]
> This is especially dangerous (and was originally found) when working with typed GraphQL mutations. This allowed a bug to slip through where an additional property was being passed to the variables of a GrqphQL mutation, which then threw an error when invoked.

You want #12936.

**Comment by RPuffer** [comment]
@MartinJohns our GraphQL `variables` are wrapped in an `Exact<>`, but it's not nested. Example: 
```ts
variables?: Exact<{
    typedObject: Type
}>
```

Would we need something like:
```ts
variables?: Exact<{
    typedObject: Exact<Type>
}>
```

**Comment by MartinJohns** [comment]
I actually meant real TypeScript support for exact types, not such workarounds.

**Comment by RPuffer** [comment]
@MartinJohns 
Gotcha, yeah that would be ideal. 

@andrewbranch 
I'm still stumped though, is there a use-case for allowing this behavior that I'm not seeing? I get it would be a major breaking change, but it seems like an unnecessary "workaround" (as it states in the handbook) when you can just use type assertions to the same effect

**Comment by andrewbranch** [comment]
The use case is being able to pass an array to an `Iterable`, a `Dog` to an `Animal`, an `HTMLInputElement` to an `HTMLElement`, a `Circle` to a `Shape`. Extra properties create subtypes. If subtypes were not assignable to supertypes, it wouldn’t just be a major breaking change, it would be a different programming language (and one not at all compatible with real JavaScript usage).

**Comment by RPuffer** [comment]
seems even more strange that the same thing _doesn't_ happen with `missing` properties:

[Playground](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220426#code/C4TwDgpgBAKhDOwCCATFBLY6D2A7AhgDYAKATtpKVglALxQDeAUFFALbrzzq4DmAXFFwBXNgCMIpANwsoAa1zYA7rkGJSPXjIC+MpgGM8iKADNcAdUwALGOAgokpXnSgAKYILiJUGLHiJkFJLU8ACUggBu2OgodAB8jLKshrjw2IQQAHSE2LzuoTpMBkbAUAAi2DBWEF6l9K7hUFEx8YnJJVDYYgBWlsBWALKc3HyBlKAuzKysCsqqUADkYOTjIAsANLK6RawA9LtQgDLkrMDwUJLkpFAS+sL48NBd3RD6pZzsw5pQ+FDLQVQgWRmPo2OwOJyuJ4goZcTRjYIgAo7KD7I5QU7nUiXa4vO4PTo9F5vM4cWF8b6-FYIoEWay2SDgvIMeSKFSCJZUgELKDaJGyVEAZXwbGgJmwV3u3F4uBFuFKwGw6LBTXwGnwYgy8Fk-IOx3RZwu4pxt3uj0Jryg71JI2cPz+q1kKWMoAZAHlzR5YAhkGhMDgCCROSEXFDrDCbfCATJWDq0frMdibnizc8LVbPuS7UHAe1UvKwe7U8AAEyeb0+P3+QP-YP0ZmzNmLe0I7nbbRFCpVGrehpSIA)

**Comment by MartinJohns** [comment]
TypeScript is structurally typed. Too many parameters is okay, too few parameters is not.

You should think of the "excess property checks" more as a linter feature than a type-related feature.

**Comment by RPuffer** [comment]
> Too many properties is okay, too few properties is not.

well, unless you use an object literal, then neither is okay.


> The use case is being able to pass an array to an `Iterable`, a `Dog` to an `Animal`, an `HTMLInputElement` to an `HTMLElement`, a `Circle` to a `Shape`. Extra properties create subtypes. If subtypes were not assignable to supertypes, it wouldn’t just be a major breaking change, it would be a different programming language (and one not at all compatible with real JavaScript usage).

See, I would expect that behavior with an `interface` vs a `type` but that's probably from experience with other languages.  If you're defining a supertype as well, it's just as easy to specify that extra properties are okay with the `[x: string]: any` pattern.  But, i think we'll just have to agree to disagree, and I can live with specifying `Exact` if/when that gets implemented.  I guess for now just gotta be real careful with how we implement GraphQL requests.

**Comment by fatcerberus** [comment]
> See, I would expect that behavior with an interface vs a type but that's probably from experience with other languages.

Indeed, most languages are nominally typed so that any subtype relation is expressed directly in the type definition.  TS is structurally typed so subtype relations are based on the actual contents of the type.  For example `interface A {}` and `interface B {}` are assignable to each other.

**Comment by andrewbranch** [comment]
> seems even more strange that the same thing doesn't happen with missing properties

Like I said, adding properties creates subtypes. Removing properties creates supertypes. If subtypes were not assignable to supertypes, the result would be an extremely unflexible and unergonomic language. If supertypes were assignable to subtypes, the result would be a language designed to produce as many `undefined is not an object` crashes as possible. If a supervillain ever took control of TypeScript, this is what they would release 😄

**Comment by RPuffer** [comment]
alright, that's fair. I'll accept it, but I don't have to like it 😅

**Comment by RPuffer** [comment]
> If supertypes were assignable to subtypes, the result would be a language designed to produce as many `undefined is not an object` crashes as possible.

Oh dear god no, I'm definitely not asking for that 😆
