### ISSUE TITLE
Object literal types with only optional properties break control flow narrowing

### ISSUE THREAD

**Issue by DaviDevMod** [microsoft/TypeScript#48858]
# Bug Report

If an object literal type with only optional properties is part of a union, the union can't be narrowed.

I expected the bug to be common enough to have been already discussed somewhere, but the most relevant issue I could find was [#31156](https://github.com/microsoft/TypeScript/issues/31156). I apologise in advance if I'm opening a dupe.

### 🔎 Search Terms

narrowing union

### 🕗 Version & Regression Information

The bug can be found in any version of the TypeScript Playground (currently from v3.3.3333 to 4.6.2, including the Nightly v4.7.0-dev.20220427).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/PTAECEEMGcFNQMY1gOlASQC6gO4HsAnAa2lBlFgA8AHWBTWAExQChMBPW0AYWQHkAdvAC8oAOQBBMaAA+oAN6g81TAEs8AyABsAXKABm2uKAC+LFgg3Rs+0KIAUkAgHM9vOINgBKOwD4FLKBBoCCgAAZOzmGgqqSaBAR4OEygmHjhEtHkVLT0TKzBMbaOLnbCopJiPpEA3CxmLKESAuxKAEYAVnTYWqoMBNoxAqkAFvAArgLqwyPkGlqtymoag9SJtARqsNCsHFzusAAq+HbiUrIKSirT2gD8epgE4-AmF4qQAniYYwSe96AAJlM5ksAmsoGcpxKrh4yGOeB8wn88kCwVCADl0vFEjhVAJIXgEAhxgQdqigqpipEyhUpNUXHUGqFDmNQJNpqBZqRID1YDBsBp4HhOt1QL1+oNcd8yLz+UohKACLAAI7jVRKxigNbKWCbdiNMAfTU8sV88GC9pdehivq6yV9EbyhZXZaaLRa9a6rZkvbwA4spUiM7SOSKJY3LT-R7PUxvMifb66v56IGvUOgRiqABeWfYejEsBG0gaoPBjockTccJGgcRyPJITAAFUBErepA2lp4NiknjId8TYxYLQBIxSBpOUlQOw8OMtVpIK0pY7E6BVdtXaAALZOEgFYKU0DQmnB+nORksIA)

### 💻 Code

```ts
// Base case. It works as expected.
type CaseOne = 'A' | { optional: false }

const f = (arg: CaseOne) => {
    // `arg` is narrowed to `A` as expected.
    if (arg === 'A') arg;
}

// Any object literal in the union has only optional properties.
type CaseTwo = 'A' | { optional?: true } | { anotherOne?: 2 }

const g = (arg: CaseTwo) => {
    // No narrowing occurs.
    if (arg === 'A') arg;
}

// The union has at least one object literal with at least one required property
// and at least one object literal with only optional properties.
type CaseThree = 'A' | { optional?: true } | { anotherOne?: 2 } | { dizzy: 'eh' }

const h = (arg: CaseThree) => {
    // Unreliable narrowing that depends on how you play with the question marks.
    if (arg === 'A') arg;
}

```

### 🙁 Actual behavior

Object literal types with only optional properties break control flow narrowing.

### 🙂 Expected behavior

It should be possible to narrow unions containing an object literal type with only optional properties.

**Comment by andrewbranch** [comment]
Hm, the issue stems from the fact that string literal types are comparable with `{}` and other weak object types. Comparability strikes again. @DanielRosenwasser do you know of a related/duplicate for this? Seems like the kind of issue that haunts you.

**Comment by DanielRosenwasser** [comment]
It's not really specific to comparability, this has been the behavior since literal types used assignability too.

This does feel like a bug since we already special-case literal types in the negative case.

```ts
// Any object literal in the union has only optional properties.
type CaseTwo = 'A' | { optional?: true } | { anotherOne?: 2 }

const g = (arg: CaseTwo) => {
    // Narrowing occurs.
    if (arg !== 'A') arg;

    // Narrowing does not occur.
    else arg
}

```

https://github.com/microsoft/TypeScript/blob/main/src/compiler/checker.ts#L24921-24929

![image](https://user-images.githubusercontent.com/972891/165587315-7e3cb43d-a68e-43e6-a8e6-ba203952843a.png)
