### ISSUE TITLE
Declaration emit fails to add visible alias statement for non-visible binding pattern

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#48868]
# Bug Report

### 🔎 Search Terms

declaration emit, object pattern, binding pattern, destructuring

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220427#code/GYVwdgxgLglg9mABAcwKZQGJzgCgJSIDeAUIogE7ojlKGLDYBcRiUqAzlMwCwBMiAX0HEBxYhAScWDOIMQBeFOiy48Y1AA8ADnHJRWATy2pEAQQA2MAIbsAKkZOKoDuMHrZiQA)

### 💻 Code

```ts
function getFoo() {
  return { foo: { test: 42 } }
}

const { foo } = getFoo()

// Exported type alias 'AliasType' has or is using private name 'foo'. (4081)
export type AliasType = typeof foo
```

### 🙁 Actual behavior

`.d.ts` can't be emitted

### 🙂 Expected behavior

`.d.ts` should be emitted by adding a visible alias statement

**Comment by MartinJohns** [comment]
Sounds like a duplicate of #30598.

**Comment by Andarist** [comment]
Yep, you are right - your search skills are stronger than mine 😅 gonna close this ticket then and reference the other in my fixing PR

**Comment by MartinJohns** [comment]
> your search skills are stronger than mine

I've got practice: https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+commenter%3AMartinJohns+%22duplicate+of%22
