### ISSUE TITLE
Ambiguous Result for Any Conditional Type Mapping

### ISSUE THREAD

**Issue by sinclairzx81** [microsoft/TypeScript#48871]
# Bug Report

### 🔎 Search Terms

- Conditional Type Mapping with Any
- Any Ambiguous

### 🕗 Version & Regression Information

Tested 4.1 > 4.7-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220428#code/C4TwDgpgBAKlC8UCGA7EUIA9gRQEwGcoBvZALihQFcBbAIwgCcAaKOi6+pqAXygH4owRlWgUAZkgA2BCAFgAUIoD0yoeGhxEdAPY6pEVFAC0GTJADGwISOg7GUSTIhA)

### 💻 Code

```ts
type T = any extends { a: number, b: number } ? true : false

// type T = boolean - expect either true or false
```

### 🙁 Actual behavior

type `T` is `boolean`

### 🙂 Expected behavior

type `T` should be either `true` or `false`

**Comment by MartinJohns** [comment]
This is working as intended. See #40049.

**Comment by sinclairzx81** [comment]
@MartinJohns Oh thank you. It appears the correct interpretation of `T` is that is effectively treated as a union, so the boolean makes sense in the issue. Also I note this is true for the following.

```typescript
type T = any extends { a: number, b: number } ? 1 : 2

// type T = 1 | 2
```
Will close this issue, thanks again for the quick help!
