### ISSUE TITLE
Can't use ES6 string methods when not targeting ES6

### ISSUE THREAD

**Issue by slikts** [Microsoft/TypeScript#4887]
Other ES6 features work when not targeting ES6, but methods like `String.prototype.startsWith` produce compilation errors. My expectation was that ES6 features would work regardless of the target version, and it's not clear what the distinction between the string methods and other features is.

**Comment by kitsonk** [comment]
Functional features are not polyfilled, it is (mainly) only language semantics that are supported when emitting to other targets.  For example, Promises don't exist, though they are part of ES2015.  You would need to polyfill them yourself or use a library like [core.js](https://github.com/zloirock/core-js) to polyfill them for you.

**Comment by DanielRosenwasser** [comment]
For the record, there's a [`core-js` definition file on DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped/tree/master/core-js). I think #4168 is the appropriate issue for discussion otherwise.
