### ISSUE TITLE
Default generic types are unused in `ReturnType`

### ISSUE THREAD

**Issue by onthecais** [microsoft/TypeScript#48870]
# Bug Report

### 🔎 Search Terms

`generic`, `default`, `unknown`, `infer`

#48480 looked similar, but it was talking about the type of a function parameter's default value not being inferred, whereas this ticket is about a *generic parameter with a default type* not being used by `infer`.

### 🕗 Version & Regression Information

I tested against v4.4.4, 4.6.3, and `nightly`.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220428#code/GYVwdgxgLglg9mABAWwJ4DFwQDwEFEC8iYIyARgKYBOANIgEKGIDOUVMYA5gHwAUAhgC5EuOmWH0AlIgDeAWABQiRFQpQQVJAG1+YgLqJ+zRBAStFAX0WKoqAA4UUGLABV7jorYdxgTzJGsFL0c0fwgAJTUNMDcHJkj1TViKbD9Xd0RuIA)

### 💻 Code

```typescript
function myFunc<A = number, B = string>(a: A, b: B) {
  return [a, b] as const
}

type myFuncType = typeof myFunc // <A = number, B = string>(a: A, b: B) => readonly [A, B] 

type myFuncReturnType = ReturnType< myFuncType > // readonly [unknown, unknown]
```

### 🙁 Actual vs Expected behaviour

I expect the type of `myFuncReturnType` to be `readonly [number, string]`, but it's actually `readonly [unknown, unknown]`, because the default generic type was not used.

**Comment by MartinJohns** [comment]
This is working as intended. See https://github.com/microsoft/TypeScript/issues/42064#issuecomment-750495482.

**Comment by Harpush** [comment]
I believe typescript 4.7 will solve it with the new Instantiation expressions? 
https://github.com/microsoft/TypeScript/pull/47607
