### ISSUE TITLE
MediaQueryList.Addlistener

### ISSUE THREAD

**Issue by tankez0r** [microsoft/TypeScript#48873]
https://github.com/microsoft/TypeScript/blob/61c3bfe484101cdabb6bf706c635122511b2574b/lib/lib.dom.d.ts#L9861

why this method are deprecated? Is usefull. 
https://developer.mozilla.org/es/docs/Web/API/MediaQueryList

MDN says this is experimental, but not deprecated.
Thank for your excellent job! greatings

**Comment by MartinJohns** [comment]
Because it's marked as deprecated.
![Screenshot_20220428-184358](https://user-images.githubusercontent.com/5269069/165802970-8ef0cb11-f15c-4e87-ba47-730f6927c363.jpg)
