### ISSUE TITLE
[Bug] strict takes precedence over disabled strictPropertyInitialization

### ISSUE THREAD

**Issue by CyberCookie** [microsoft/TypeScript#48872]
As mentioned in [official documentation](https://www.typescriptlang.org/tsconfig#strict) :
Turning **strict** on is equivalent to enabling all of the strict mode family options, which are outlined below.
**You can then turn off individual strict mode family checks as needed.**

[Here is](https://www.typescriptlang.org/play?strictPropertyInitialization=false&ts=4.6.2#code/GYVwdgxgLglg9mABADwBQEpEG8CwAoRQxAGwFMpEBPALkTBAFsAjUgJ3yMRmEVQBEAhlFIA6MHADuGRAF4ZiAIyZcBTkUqzEAJgAMHIgF98+wq3IhWSSvgNA) a small example from TS playground, where **strictPropertyInitialization** in TSConfig is set to false, but compiler still shows an error, that **variable is used before being assigned**

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template for bug reports.

> [Here is](https://www.typescriptlang.org/play?strictPropertyInitialization=false&ts=4.6.2#code/GYVwdgxgLglg9mABADwBQEpEG8CwAoRQxAGwFMpEBPALkTBAFsAjUgJ3yMRmEVQBEAhlFIA6MHADuGRAF4ZiAIyZcBTkUqzEAJgAMHIgF98+wq3IhWSSvgNA) a small example from TS playground, where strictPropertyInitialization in TSConfig is set to false, but compiler still shows an error, that variable is used before being assigned

`strictPropertyInitialization` refers to the strict initialization of (class) properties. You don't have a property in the playground you posted. You just have a regular variable.

**Comment by CyberCookie** [comment]
Ok thanks for the answer. I will close the issue.
