### ISSUE TITLE
Intl.DateTimeFormat.formatToParts() does not include part of type `fractionalSecond`

### ISSUE THREAD

**Issue by jordanmbell** [microsoft/TypeScript#48882]
# lib Update Request

## Configuration Check

My compilation *target* is `esnext` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Intl.DateTimeFormat.prototype.formatToParts`

## Sample Code

`new Intl.DateTimeFormat().formatToParts().find((val) => val.type === 'fractionalSecond')`

## Documentation Link

Added in ECMAScript 2021: [https://402.ecma-international.org/#sec-formatdatetimepattern](https://402.ecma-international.org/#sec-formatdatetimepattern)

Also mentioned in MDN: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts#description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts#description)

**Comment by jordanmbell** [comment]
I believe I have a fix for this issue in https://github.com/jordanmbell/TypeScript/commit/cc8230e61613b1b084dc8147f4122f3e39b9fe1e that I would love to contribute.

**Comment by lzcampos** [comment]
Hi!

I've seen that this sample sample code does not result on access to 'hours' or even a 'minutes' object. Is that the bug to fix or it should just include 'fractionalSecond' property too?
