### ISSUE TITLE
Type validations do not carry over when assigned to a const

### ISSUE THREAD

**Issue by oguzgelal** [microsoft/TypeScript#48891]
# Bug Report

### 🔎 Search Terms

- Object is possibly 'undefined' when it shouldn't be
- TypeScript fails to detect when a value is not undefined
- TypeScript fails to detect when a value is not null
- TypeScript fails to detect when a value is not nil
- TypeScript fails to detect non-falsy values

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBA8gRgKygXigbwLACgpWBAZ2AEYB+ALiiICcBLAOwHNtd8iAmSmhxqAHyj0ArgBsRLPIWABmLsDpN+UAGYBDEQQjYAvtmwBjAPb0iUQ4krwkqTDklFilAEQALCGMNOANBLbBOUK7uIp4+dn6ygW4e3jp6WMpC9PrAtMYq9AAUqtSMcgqMAJToEgD0AFTlUHAiqi5Q5aVxWNilpVAAglAAtFCAyORQre0QAB6QKRAAJpQQ1NSG1NjKWeYIAHR+xIVLK4gbUuzbCbvrEUdDUABCPf0Xo+P404KGULPzi1i0ylCZAIS-q32DmKy0ygM2Ry+P3+4IOIJOQP8kO+fwBezOGTB6Kk0nOWDaUAAwjcBncxhAJk96C83gtsFDMqBIIZvrCHChkKgnNwmE54VjTlItvSUUyICyzNiOByuTzGHzMWykSKfmKJUrpDLAnKFaCNXiCQARG4jMkPKaUamvOZ0-HtOAQFyqABuaWoMxtHyMJmAZgA1sQUFAYVKSAZjKZDH72EGQ4KOOGff7Nag44jpCqwQH+UrhZ8UVHDorQ4dM1HccX4zIDe0AKIms0Ux6Wmmei4Op2uhYe96JyN+gAsQbVrNDgc5svkPCcfd9UYArMPwOLR1WYxPtVPebP-QA2JfM1fprXcrfysuDnNj5E-BdXtc3rO7+-pwpAA)

### 💻 Code

```ts
type Obj = {
  test1?: string
  test2: string | null
  test3: string | false
}

const obj: Obj = {
  test1: "hello",
  test2: "hello",
  test3: "hello",
}

function fn(arg: string) {
  /** blah */
}

// A - ✓ 
// expected: error
fn(obj.test1)
fn(obj.test2)
fn(obj.test3)

// B - ✓
// expected: no error
if (!!obj.test1) fn(obj.test1)
if (!!obj.test2) fn(obj.test2)
if (!!obj.test3) fn(obj.test3)

// C - ✓ 
// expected: no error
if (typeof obj.test1 === "string") fn(obj.test1)
if (typeof obj.test2 === "string") fn(obj.test2)
if (typeof obj.test3 === "string") fn(obj.test3)

// D - x
// expected: no error
// behavior: error
const ok1 = !!obj.test1
const ok2 = !!obj.test2
const ok3 = !!obj.test3
if (ok1) fn(obj.test1)
if (ok2) fn(obj.test2)
if (ok3) fn(obj.test3)

// E - x
// expected: no error
// behavior: error
const ok4 = typeof obj.test1 === "string"
const ok5 = typeof obj.test2 === "string"
const ok6 = typeof obj.test3 === "string"
if (ok4) fn(obj.test1)
if (ok5) fn(obj.test2)
if (ok6) fn(obj.test3)
```

### 🙁 Actual behavior

TypeScript can tell when the value of a variable is not falsy inside of an if block where the validation is directly used as the condition. But it fails to carry it over when the outcome of the validation is assigned to a `const` and that variable is used as the condition of the if statement instead.

### 🙂 Expected behavior

As long as the outcome of the validation is assigned to a `const`, TypeScript should deduce that the value is not falsy.

**Comment by MartinJohns** [comment]
It's working as intended. See #44730.

> Narrowing through indirect references occurs only when the conditional expression or discriminant property access is declared in a `const` variable declaration with no type annotation, and the reference being narrowed is a `const` variable, a `readonly` property, or a parameter for which there are no assignments in the function body.

**Comment by oguzgelal** [comment]
@MartinJohns Thanks for pointing out the PR! Exactly the issue I'm facing with. 

In my code sample above, could you help me understand why there are errors in D and E when the expression is assigned to a `const` and `obj` is also const (and not re-assigned) ?

**Comment by MartinJohns** [comment]
Because of this part:

> and the reference being narrowed is a `const` variable, a `readonly` property, or a parameter for which there are no assignments in the function body.

`obj.test1` (and the other two) don't refer to a `const` variable, a `readonly` property or a parameter.

**Comment by oguzgelal** [comment]
Ah I see! Got it. Thank you very much! For reference, changing `Obj` like below solved the issue.

```ts
type Obj = Readonly<{
  test1?: string
  test2: string | null
  test3: string | false
}>
```
