### ISSUE TITLE
Type narrowing/assertion fails with ternary operator

### ISSUE THREAD

**Issue by Suyashtnt** [microsoft/TypeScript#48897]
# Bug Report

### 🔎 Search Terms

- type assertion ternary 
- type narrowing ternary 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `4.6.4`, `4.7.0-dev.20220430`
- I was unable to test this on prior versions because it makes no sense why older versions would have this

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/KYDwDg9gTgLgBDAnmYcAyEDGBDANsAZzgF44BIAKDjgB84ByAE2HorLvuADsBaAcwBGrCqEiw4mCFwLxcWPIQBc6efgIBtALok46tkxYAafd35CKmiiPDR4k6fAHYCwDDnzK3CoqU69BwvYycACWBF74OgAUcu7AyjJQIVx8tHBcAK64uACUyrEKoUQRhCQAfHAA3lRwUMAwGVBccAVqAHTJmLgZzAQxqqjOKnEEOQDcFAC+VtTUQbKqAMow0Nh8rgM6rcur623rMACSMMAAtlH0rSzjNXNSwVzYAG4hfNgrUCU6jy9vH224bApDJrYATWZwW4Se4LOKeAY+IolfruHZQUElHJQ6gAfhaSw+GIG2LgygyXGYADNksBGLQ6GFkT9Xu9oJiSXjmX82cSIdQyRTgNSuLT6XAnC4SmMgA)

### 💻 Code

```ts
export type Locales = 	
  | 'de'
	| 'en-gb'

export const locales: Locales[] = [
	'de',
	'en-gb'
]

export const baseLocale: Locales = 'en-gb'

const isLocale = (locale: string | null): locale is Locales => {
  return locales.includes(locale as Locales);
}

    const localStorageLocale = localStorage.getItem('locale');
    const navigatorLocale = navigator.language;
    
    const locale: Locales = isLocale(localStorageLocale)
      ? localStorageLocale
      : undefined || isLocale(navigatorLocale)
      ? navigatorLocale
      : undefined || baseLocale;
```

### 🙁 Actual behavior

Typescript does not correctly narrow the type and says that `Type 'string' is not assignable to type 'Locales'`

### 🙂 Expected behavior

It to correctly narrow down the type without error

**Comment by whzx5byb** [comment]
It seems that you expect `a ? b : c || d ? e : f` to be `a ? b : c || (d ? e : f)`, but it is actually `a ? b : (c || d) ? e : f`.

**Comment by Suyashtnt** [comment]
> It seems that you expect `a ? b : c || d ? e : f` to be `a ? b : c || (d ? e : f)`, but it is actually `a ? b : (c || d) ? e : f`.
> 
> Add the missing parentheses and your code will work.
> 
> ```ts
> const locale: Locales = isLocale(localStorageLocale)
>       ? localStorageLocale
>       : undefined || (isLocale(navigatorLocale)
>       ? navigatorLocale
>       : undefined || baseLocale);
> ```
I realized the library I used had this functionality builtin so I am not using this code anymore. However doing this in the [ts playground](https://www.typescriptlang.org/play?ts=4.6.2#code/KYDwDg9gTgLgBDAnmYcAyEDGBDANsAZzgF44BIAKDjgB84ByAE2HorLvuADsBaAcwBGrCqEiw4mCFwLxcWPIQBc6efgIBtALok46tkxYAafd35CKmiiPDR4k6fAHYCwDDnzK3CoqU69BwvYycACWBF74OgAUcu7AyjJQIVx8tHBcAK64uACUyrEKoUQRhCQAfHAA3lRwUMAwGVBccAVqAHTJmLgZzAQxqqjOKnEEOQDcFAC+VtTUQbKqAMow0Nh8rgM6rcur623rMACSMMAAtlH0rSzjNXNSwVzYAG4hfNgrUCU6jy9vH224bApDJrYATWZwW4Se4LOKeAY+OBRMIlfruHZQUElHJQ6gAfhaSw+WIGuLgygyXGYADNksBGDlaHRkeEBlEfq93tBsWSCRy-tzSRDqBSqcBaVx6YyaHQnC4SmMgA) did fix the issue. Thanks
