### ISSUE TITLE
TS looses previously determined type

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#48901]
See how `errorWithActions` becomes `any[]` because `Array.isArray()` is used:

https://github.com/microsoft/vscode/blob/cffd590665a0271a05ad90dbb3c708d156c3008b/src/vs/workbench/browser/parts/editor/editorPanes.ts#L155

https://github.com/microsoft/vscode/blob/cffd590665a0271a05ad90dbb3c708d156c3008b/src/vs/workbench/browser/parts/editor/editorPanes.ts#L162

**Comment by mjbvz** [comment]
Self contained example:

```ts
let errorActions: readonly string[] | undefined = undefined;
if (Array.isArray(errorActions)) {
    // check errorActions here
    console.log(errorActions)
}
```

**Comment by andrewbranch** [comment]
Duplicate of #17002
