### ISSUE TITLE
Keyword "as" for Destructuring Assignment

### ISSUE THREAD

**Issue by Worldwidebrine** [microsoft/TypeScript#48905]
# Suggestion

## 🔍 Search Terms

destructuring assignment as alias :

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add `as` as the alias of `:` in destructuring assignment.

## 📃 Motivating Example

`:` is confusing.
```typescript
const {myProperty: alias} = {myProperty: value};
```
I think `as` should be allowed to replace `:` here and `as` is less confusing.

This should be no more than a simple syntax sugar that doesn't break anything, since type casting `as` is only on the right side of an assignment expression and we have already had `as`.
```typescript
import { old_name as new_name, name as alias } from
```

## 💻 Use Cases

```typescript
const {r as x, g as y, b as z} = obj;
```

**Comment by jcalz** [comment]
I'm afraid this will be declined.  You checked this box

> * [x]  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

but you do note that using `as` in place of `:` would be "no more than a simple syntax sugar".  To be clear, you want the non-ECMAScript syntax `const {r as x} = obj` to produce the JavaScript output `const {r:x} = obj` as JavaScript.  TypeScript doesn't want to do that sort of thing (well, not *anymore*... I'm looking at you, `enum`).

**Comment by Worldwidebrine** [comment]
You're right.
This should be suggestion to ES?
Is it possible that ES will add this?

**Comment by MartinJohns** [comment]
> Is it possible that ES will add this?

Possible? Yes. Likely? No. There's simply not enough benefit from this feature to outweigh the disadvantages and costs.

**Comment by Josh-Cena** [comment]
> `:` is confusing.
>
> ```ts
> const {myProperty: alias} = {myProperty: value};
> ```

Isn't that example exactly why it's _not_ confusing, though? You can think of it as pattern-matching where the LHS and the RHS have the exact same syntactical construct.

```ts
// Construct `obj` with the variable `value` as value of `myProperty`
const obj = { myProperty: value };

// Destruct `obj` with the value of `myProperty` as the variable `value`
const { myProperty: value } = obj;
```

**Comment by fatcerberus** [comment]
FWIW I always find property-renaming in destructuring confusing, because I intuitively expect the order to be reversed vs. object literal syntax (the values flow in opposite directions - one is putting values *in*, the other is taking them *out*).  I always have to stop in my tracks to think about it.
