### ISSUE TITLE
Wrong module extending?

### ISSUE THREAD

**Issue by panhaozi** [microsoft/TypeScript#48903]
[Test.zip](https://github.com/microsoft/vscode/files/8587710/Test.zip)
Please import the vscode project in this zip, then check the file named “g.Test.ts”. I do not know why "test('p2')" is incorret
![image](https://user-images.githubusercontent.com/8217836/165876590-123684f6-8c75-415b-9912-48dda05b5ae9.png)
![image](https://user-images.githubusercontent.com/8217836/165892437-5078e6cb-33aa-452e-bab1-51bbd6174f2e.png)

**Comment by whzx5byb** [comment]
A simplified workbench repro

```ts repro
// @filename: index.ts
export * from './eventList';
export * from './test';

// @filename: test.ts
import { EventList } from "./eventList";

function test(arg: keyof EventList) { }

test('p0');
test('p1');
test('p2'); // Error here

// @filename: eventList.ts
export interface EventList {
    p0: [];
}

// @filename: foo.ts
declare module './index' {
    interface EventList {
        p1: []
    }
}
export {};


// @filename: bar.ts
declare module './index' {
    interface EventList {
        p2: []
    }
}
export {};

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKaiAm8APAOgBcBnAKEIAcB7AJxNACpRJ7bVQByI4eAG5ISAGWhkS3ANxUCdRizYcuvYCXgTpFCiAgwEKdFnUTSlaKnlMA3qACiQxKPFMAvks6gARH0HCxEl4yFJAArogAxiTQtIigJiQAFMj0AOZYANbwAJ60kPaOzhIAlKC2rtoJidzUAAzcxTJVNQCMDU0aSTUATO2gunb0HPSgABbw9PDaulBwSGiYoH5OASRmslbYThOQyBHwBf4uZRSgZ6B1WADaALoyFTpgswYLWJC0tOv4EbApB6i0XChBA8Pg4fAEbgnc5bdT0Xb7Q4rY7WU4w87UFrXG5os4VCo0Bg2VzBR56OaGRYAIxSX3gPz+oABQJBqnBhChqJhODhCIODiOEmh6LO1G62NxoHxGyJZRJFCAA)
