### ISSUE TITLE
`compilerOptions: noUnusedLocals` doesn't work in `jsconfig.json` in latest typescript

### ISSUE THREAD

**Issue by tjx666** [microsoft/TypeScript#48900]
Does this issue occur when all extensions are disabled?: Yes/No

No.

- MacOS: 12.3.1
- VSCode: 1.67.0-insider
- Typescript: 4.7.20220429
- Node: v16.15.0

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/166098797-aeff0d2d-883c-419f-8309-4d0f24d629f0.png">

@mattbierner

**Comment by MartinJohns** [comment]
1. You're confusing "locals" and "parameters". There's the flag `noUnusedParameters` for function parameters.
2. There is no error in your screenshot, so I don't see what the issue is. When you enable `noUnusedParameters` (turned off by default) you get two errors for the unused parameters, otherwise not.

**Comment by tjx666** [comment]
@MartinJohns 
check the red arrow in the screenshot, there is a ts error:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/41773861/166146070-a42b8127-470e-4a64-aa14-6a5e8966d057.png">

**Comment by MartinJohns** [comment]
It's a hint, not an error, and the hint is right. You can avoid it by prefixing your identifier with `_ `.

And you say "in the latest TypeScript" - can you name a version where this behaviour was any different? Like mentioned, `4.6.4` and `4.5.2` behaved the same.

**Comment by tjx666** [comment]
No this hint in typescript: 4.6.4

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/166148982-fb942694-42bc-4785-b25c-4d66fd1b7419.png">

**Comment by MartinJohns** [comment]
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#control-over-module-detection

In your 4.6.4 version your file is not considered module, but instead a script file, so it can't tell if the function is used anywhere. Only when the file is considered a module it identifies that the function is not used anywhere (as it's not exported).

**Comment by tjx666** [comment]
but in the 4.7 example above, there is no export or import, it is also not a module.

**Comment by Josh-Cena** [comment]
From the commented-out `export default`, I suppose you are using Node ESM (through `"type": "module"` in your package.json). In that case, your file will be a module even when there are no import/export.
