### ISSUE TITLE
Perf regression in object destructuring with default values referencing other destructured members

### ISSUE THREAD

**Issue by damienmortini** [microsoft/TypeScript#48902]
VS Code Version: 
- Version: 1.66.2 (user setup)
- Version: 1.67.0-insider (user setup)

OS: 
- Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Open this code

```javascript
class GLTexture {
  constructor({
    gl,
    width,
    height,
    target = gl.TEXTURE_2D,
    internalFormat = gl.RGBA8 || gl.RGBA,
    format = gl.RGBA,
    type = gl.UNSIGNED_BYTE,
    autoGenerateMipmap = false,
    minFilter = autoGenerateMipmap ? gl.LINEAR_MIPMAP_LINEAR : gl.LINEAR,
    magFilter = gl.LINEAR,
    wrapS = gl.REPEAT,
    wrapT = gl.REPEAT,
  }) {
  }
}
```

2. See that after switching tabs or hovering on a property that IntelliSense isn't working and `Loading IntelliSense Status` in status bar starts spinning forever

![Code_cb8oof7A1o](https://user-images.githubusercontent.com/1583101/164264672-3760d21b-432d-401d-9134-60eb048df4df.png)
![Code_k3e8RGnq39](https://user-images.githubusercontent.com/1583101/164264751-9b2cd059-17de-41a0-9c0c-afd3a43e5a0f.png)

I tried to isolate the issue that seems to be related to operators in constructor, but not always. Sometimes, it appears by commenting/uncommenting other lines.

**Comment by mjbvz** [comment]
Thanks for the self-contained example! Was able to confirm using `4.7.0-dev.20220430`

**Comment by andrewbranch** [comment]
Repro executes in ~1 second in 4.5 and earlier, ~120 seconds in 4.6 and later 😅 

Caused by #46266

**Comment by ahejlsberg** [comment]
Doesn't appear to have anything to do with class constructors. This suffers from the same issue:

```ts
function foo({
    value1,
    test1 = value1.test1,
    test2 = value1.test2,
    test3 = value1.test3,
    test4 = value1.test4,
    test5 = value1.test5,
    test6 = value1.test6,
    test7 = value1.test7,
    test8 = value1.test8,
    // ...
}) {}
```

Something appears to have exponentially rising cost. I'll research...
