### ISSUE TITLE
Typescript 1.6.3?

### ISSUE THREAD

**Issue by prabirshrestha** [Microsoft/TypeScript#4891]
In npm I only see typescript 1.6.2 when using `npm view typescript`

![image](https://cloud.githubusercontent.com/assets/287744/9983377/63ced44a-5fae-11e5-874f-46e82f19ed36.png)

But if I download the VS tools from http://www.typescriptlang.org/#Download I see 1.6.3.

![image](https://cloud.githubusercontent.com/assets/287744/9983381/856ef0e4-5fae-11e5-8461-d9faf6d5d203.png)

tsc.exe properties also shows 1.6.30.

![image](https://cloud.githubusercontent.com/assets/287744/9983394/a11b30aa-5fae-11e5-8faf-9ccd62dac9de.png)

Is the latest version VS Tools 1.6.3 equivalent to 1.6.2 in npm? Version number seems confusing.

**Comment by mhegazy** [comment]
1.6.3 is the same as 1.6.2, it is just the VS extension version. From the [release notes](https://github.com/Microsoft/TypeScript/releases):

> Note: This release has the version tag of 1.6.2.0 for Visual Studio 2013 and 1.6.3.0 for Visual Studio 2015.

The reason for the version differences is you could have two installations of VS on the same machine (VS 2013 and VS 2015), and if both have the same version, the setup may mess up some files as it is installing. to work around this, we always ensure that VS2015 has a higher version number than that of VS2013, but the two are identical, and the compiler version, `tsc --v` will be the same (1.6.2 in this case). 
VS2015: 1.6.1 -> matches VS2013 1.6.0 (release 1.6 Beta)
VS2015 1.6.3 -> matches VS2013 1.6.2 (release 1.6)
