### ISSUE TITLE
Type definition for `fractionalSecondDigits` in Intl.DateTimeFormatOptions has incorrect `0`.

### ISSUE THREAD

**Issue by mstssk** [microsoft/TypeScript#48912]
# lib Update Request

## Configuration Check

My compilation *target* is `es2016` and my *lib* is `es2021`.

## Missing / Incorrect Definition

`fractionalSecondDigits` in Intl.DateTimeFormatOptions should not have `0`.
However current type definition is `fractionalSecondDigits?: 0 | 1 | 2 | 3 | undefined;`.
https://github.com/microsoft/TypeScript/blob/v4.6.4/src/lib/es2021.intl.d.ts

## Sample Code

```ts
Intl.DateTimeFormat("en-US", { fractionalSecondDigits: 0 });
// RangeError: fractionalSecondDigits value is out of range.
```

This code throws RangeError on Chrome v101, Safari v15.4, Firefox v99 and Node.js v16,v17.

## Documentation Link

`fractionalSecondDigits` values are 1, 2 or 3 in ECMAScript® 2021 Internationalization API Specification.
https://402.ecma-international.org/8.0/#sec-datetimeformat-abstracts

Related conversation at https://github.com/tc39/ecma402/issues/590

**Comment by Uda-Titor** [comment]
I want to contribute this issuse

**Comment by mstssk** [comment]
@sandersn This issue seems to does not resolved. 

#49014 resolved only `ResolvedDateTimeFormatOptions`.
https://github.com/microsoft/TypeScript/blob/9236e39374c0ec9a1e3f9894af4fb9eb34ba0021/src/lib/es2021.intl.d.ts#L26

However `DateTimeFormatOptions` is not resolved.
https://github.com/microsoft/TypeScript/blob/9236e39374c0ec9a1e3f9894af4fb9eb34ba0021/src/lib/es2021.intl.d.ts#L8
