### ISSUE TITLE
Control Flow Analysis of aliased conditions on object properties not working

### ISSUE THREAD

**Issue by LorenzHenk** [microsoft/TypeScript#48929]
# Bug Report

### 🔎 Search Terms

Control Flow Analysis
type guard

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _type guard_ and _Control Flow Analysis_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-dev.20220503#code/FASwdgLgpgTgZgQwMZQAQFUDOtUG9iqGpgIC2UAXKphDOAOaoA+xArgDbvAC+wwcrMEgggA9mFRxRogBSsqWWAEo8BIiDhyAdCXKoAhAF5DbTkvxFLqVjrJQt7KGHoQAFmsK9e-QcLESAIwQYGVxdKG4FbBgVCyIkcRpUEEwANQR2EAATVBNwg2NTLksNGRT0zKzzDytwhycXd0svPgEhEXFUIIAvOSjlVUsEsCTyjOzc61s9IzyOYvVNMcrqqyIAenXUNxTqV1EOHIC0AHdRGABrBlQETFQTqE4ayxs6x2c3GpagA)

### 💻 Code

```ts
interface User {
    name: string | null
}

function baz(u: User) {
    const isValid = u.name !== null

    if(isValid) {
        // `u.name` should be `string`, but the following error appears:
        // User.name: string | null
        // Object is possibly 'null'. (2531)
        u.name.length
    }
}


```

### 🙁 Actual behavior

`u.name` is of type `string | null`

### 🙂 Expected behavior

`u.name` should be of type `string`

**Comment by MartinJohns** [comment]
This is working as intended. See #48891.

**Comment by LorenzHenk** [comment]
Ahh I see, thanks!
