### ISSUE TITLE
VS Code renaming default export from styled-components

### ISSUE THREAD

**Issue by nikitapryymak** [microsoft/TypeScript#48925]
Im using styled-components in a react app and when I try to import the default export ("styled"), my VSCode auto-import-suggestions keeps saying "styledComponents" is the default export. Even though when I open the styled-components source code in node_modules, it clearly says `"export default styled"`. I had it working before with the right name ("styled"), but then it randomly switched to "styledComponents". I don't know if I changed some setting by accident? I think it's something to do with an "alias"

![image](https://user-images.githubusercontent.com/78571763/163664713-6a2c5598-ff2d-4729-8102-8ac58a1e7521.png)

When I hover over the import at the top it shows this:

![image](https://user-images.githubusercontent.com/78571763/163664750-b74c0ae9-2e96-4f92-b201-1eecd28c091d.png)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: 12.3.1

Steps to Reproduce:

1. Open a react app and install styled-components
2. Try to import "styled" from "styled-components" and see if the auto-suggested-import is styledComponents

**Comment by andrewbranch** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/3277153/166346264-22b5d9d2-d9aa-41e7-a3aa-6380b68e502a.png">

Works for me. @nikitapryymak can you show me what you see when you ⌘-click on `styledComponents`?

**Comment by andrewbranch** [comment]
?

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/3277153/167183646-beda2a08-5f27-4a03-a89c-4587c8863190.png">

**Comment by nikitapryymak** [comment]
https://user-images.githubusercontent.com/78571763/167238925-0308129f-26fa-4f7b-99be-c400f60b4ad1.mp4

@andrewbranch sorry I was recording the wrong screen 🤦🏼‍♂️

**Comment by nikitapryymak** [comment]
@andrewbranch I'm using the "Use VS Code's Version" option, which is set to 4.6.3

**Comment by andrewbranch** [comment]
@nikitapryymak any chance you can make an example repo that demonstrates the problem, and/or [send a TS Server log](https://github.com/microsoft/TypeScript/wiki/Getting-logs-from-TS-Server-in-VS-Code)?
