### ISSUE TITLE
Awaited<T> missing from utility types documentation

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#48935]
# Bug Report

### 🔎 Search Terms

awaited documentation 

### 🕗 Version & Regression Information

- This changed between versions 4.4 and 4.5

### ⏯ Playground Link

https://www.typescriptlang.org/docs/handbook/utility-types.html

### 💻 Code
Release notes for 4.5. describe a [new Awaited utility type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements) but there's nothing about this on the [Utility Types documentation page](https://www.typescriptlang.org/docs/handbook/utility-types.html).  

### 🙁 Actual behavior

Spend a while looking through the Utility Types page and external resources to find something that provides this functionality, concluding it doesn't yet exist.

### 🙂 Expected behavior

Documentation on the Utility Types page of this utility types that happily does exist, and is just only documented on GitHub and in release notes.

**Comment by jcalz** [comment]
This probably belongs in [microsoft/TypeScript-Website](https://github.com/microsoft/TypeScript-Website/issues/).

**Comment by wbt** [comment]
Agreed, if someone can migrate it there that'd be great.
