### ISSUE TITLE
ECMAScript private member support in Constructor Parameter Properties

### ISSUE THREAD

**Issue by kfrancois** [microsoft/TypeScript#48944]
# Suggestion

When moving fields declared as Parameter Properties from the `private` access modifier to the `#` prefix, we should be able to do this in the constructor

**`private` example**
```ts
class Person {
  constructor(private name: string) { }

  sayHello() {
    return `Hello from ${this.name}!`;
  }
}
```

**`#` example, today**
```ts
class Person {
  #name: string

  constructor(name: string) {
    this.#name = name
  }

  sayHello() {
    return `Hello from ${this.#name}!`;
  }
}
```

**`#` example, suggested**
```ts
class Person {
  constructor(#name: string) { }

  sayHello() {
    return `Hello from ${this.#name}!`;
  }
}
```

## 🔍 Search Terms

constructor, private, parameter properties, class, members, fields, hash names

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

See examples above. I would like to see [ECMAScript private members](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) to be supported in TypeScript's Parameter Properties syntax.

## 📃 Motivating Example

The `#` class member prefix can be used in TypeScript, and serves as a superior alternative to TypeScript's `private` modifier which doesn't have runtime impact.

To promote adoption in TS codebases, the widely used syntax mentioned above should be easily replaceable without impacting readability or creating more code while developers are already used to using Parameter Properties.

## 💻 Use Cases

See examples above.

**Comment by MartinJohns** [comment]
Duplicate of #43678. Used search terms: `private field constructor in:title`

**Comment by kfrancois** [comment]
Thanks for finding that one! I'll close this.
