### ISSUE TITLE
Parsing+generating TypeScript? - à la Esprima

### ISSUE THREAD

**Issue by SamuelMarks** [Microsoft/TypeScript#4897]
Here's the closest thing I could find: https://github.com/Diullei/esprima-typeScript

But it hasn't been maintained for >2 years. I'm using TypeScript for one of my projects, but I need to develop code-generators to make everything flow correctly.

How can I:
  0. Parse a TypeScript file into an AST
  1. Manipulate that AST
  2. Emit a replacement TypeScript file

Thanks for all info :)

**Comment by DanielRosenwasser** [comment]
You should take a look at our wiki page on [the compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API).

Unfortunately, we don't have a solid facility for manipulating the AST. One issue is that it would invalidate parent pointers, and another is that much of the time we resort to the original source text of a file as a reference for emitting the AST. @rbuckton is working on some tree transformation stuff right now.

**Comment by SamuelMarks** [comment]
@DanielRosenwasser: Top secret project which I'll open-source in November :wink: 

No worries, will try and manage with that lower level compiler API.

**Comment by mhegazy** [comment]
We would love to get feedback here. give it a tree and let us know how it goes.

**Comment by SamuelMarks** [comment]
Sure thing, I'll post my thoughts in the most recent reply (as edits) of this thread.

Current thinking:

  - Esprima goes from JS=>AST and escodegen goes from AST=>JS. Their AST follows the [estree schema](https://github.com/estree/estree).
  - [typescript-closure-tools](https://github.com/fivetran/typescript-closure-tools) goes from JavaScript to TypeScript using Closure doc syntax as a way of figuring out which interfaces to generate. Don't yet understand how to replicate this, however should note that it uses some of the technologies from the first bullet-point.
  - Maybe I should stop trying to hack together a solution, and work on creating a new esprima-TypeScript implementation in the style of [esprima-typeScript](https://github.com/Diullei/esprima-typeScript), beginning from a fork of the latest [esprima codebase](https://github.com/jquery/esprima).

Not sure how feasible that last option is.

#end_thoughts_for_now

PS: That estree AST syntax is great!
