### ISSUE TITLE
npm link issue

### ISSUE THREAD

**Issue by milnerb96** [microsoft/TypeScript#48971]
# Bug Report

### 🔎 Search Terms
  npm link, duplicate type declarations

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about duplicate type declarations with npm link

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
The code is for an internal company project, however, I do not think it is required to get started in addressing the issue.
```

### 🙁 Actual behavior

My project is throwing "Types have separate declarations of a private property". I am testing a npm package I developed locally. I use npm link to link the package to my project and when I build the app, I get the error previously mentioned. It looks to be that the linked package is referencing the type definition in their own local node_modules folder. I have seen several issues created for this however it looks like the solution to the problem is a work around rather than a fix. All the work abounds that I've found do not work for me. The issue I found that I have been referencing to solve this problem is issue #6496 "Duplicate type declarations with npm link". 

### 🙂 Expected behavior

Linked package should be using the typings from the linked node_module

**Comment by RyanCavanaugh** [comment]
There are many specific ways you might have set this up and the correct fix depends on exactly what you've done. We'd need a concrete repro to proceed.
