### ISSUE TITLE
Use package.json exports for AutoImportProvider under `--moduleResolution node`

### ISSUE THREAD

**Issue by OnkelTem** [microsoft/TypeScript#48977]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Linux Kubuntu 20.04

Steps to Reproduce:

1. `npm init -y`
2. `npm i yargs`
3. create a js file and type there: `hideBin` (it's a function from the `yargs` module)
4. then open the "Quick fix..." context menu
5. it doesn't contain an import suggestion

![image](https://user-images.githubusercontent.com/114060/166916638-aecf5ab0-ec04-431c-bbdb-81438a1b7040.png)

**Comment by mjbvz** [comment]
@andrewbranch `hideBin` only is picked up once I add an import for `import { } from 'yargs/helpers';`

Not sure if if this is a bug or expected

**Comment by andrewbranch** [comment]
Does it get suggested if you use `"moduleResolution": "nodenext"`?

This is expected. `@types/yargs/index.d.ts` has no mention of `@types/yargs/helpers.d.ts` so there’s no reason we would find it before it’s specifically requested. The typings could easily add a reference to it so this would work. However, the package.json `exports` _does_ list `"./helpers"` and we should pick that up under `nodenext` via #47092. We could _possibly_ run that logic even under the older moduleResolution modes, but it’s a little fishy and we would run the risk of picking up files we shouldn’t in packages that ship CJS and ESM side-by-side, for instance.

**Comment by andrewbranch** [comment]
Actually, I think under `--moduleResolution node` it would probably be alright to look at package.json `exports` for auto-importable files as long as we don’t include `import` in our conditions. This might be a nice experience improvement, but it may apply to relatively few packages for now.

**Comment by andrewbranch** [comment]
I’ll plan to investigate.

**Comment by OnkelTem** [comment]
Hi @andrewbranch!

> The typings could easily add a reference to it so this would work. 

How could they properly do that?

**Comment by andrewbranch** [comment]
`import "./helpers"`

**Comment by PabloLION** [comment]
> Does it get suggested if you use "moduleResolution": "nodenext"?
> `import "./helpers"`

Hi, @andrewbranch I'm facing the same `ts(2691)` problem when trying to apply the [ESM support](https://www.typescriptlang.org/docs/handbook/esm-node.html). 


I read the [tsconfig docs](https://www.typescriptlang.org/tsconfig#module) and thought it could be the problem of `moduleResolution`.

However after I've installed the `typescript@4.8.0-dev.20220618` with `yarn add -D typescript@next` in the package, and also added it globally with `npm install -g typescript@next`.
My "./.vscode/settings.json" has: `"typescript.tsdk": "$(npm root -g)/typescript/lib"` (also tried absolute path, and relative path:`"./../node_modules/typescript/lib"`)
The `ts` is still complaining "Compiler option 'moduleResolution' of value 'nodenext' is unstable. Use nightly TypeScript to silence this error. Try updating with 'npm install -D typescript@next'."
And the importing `*.ts` files of `ts(2691)` was still there.

Could I get some help from you? TIA.

**Comment by PabloLION** [comment]
Should I start a new issue?

**Comment by patroza** [comment]
> Could I get some help from you? TIA.

Two things I can imagine:
1. VSCode does not respect the setting, and you must open a TS file, then open command menu (e.g on Mac Cmd+Shift+P) and do: TypeScript: Select TypeScript Version... and manually select the workspace version.
2. You are using plugins that don't respect this setting, e.g Vue Vetur / Vue Language Server don't out of the box. like they need a vetur.config with `  settings: {
    "vetur.useWorkspaceDependencies": true, }`

**Comment by andrewbranch** [comment]
I think I’ve convinced myself that this isn’t a great idea, as entrypoints in `exports` are unlikely to be usable by `--moduleResolution node` correctly. The issue should basically fix itself as we migrate people away from `--moduleResolution node` (#50152)
