### ISSUE TITLE
intellisense Support for NodeJS 12.7+ package exports for js-require()

### ISSUE THREAD

**Issue by JoernBerkefeld** [microsoft/TypeScript#48986]
as discussed in #33079 the system does not support package.json export statements.

apparently, this started working for typescript but it's not supported at all in javascript based on my tests

I tried out this and IntelliSense just stopped working altogether:
![image](https://user-images.githubusercontent.com/1917227/167101525-1b3bddef-3f0e-44a0-ac6c-33e05c4dff04.png)

**Comment by JoernBerkefeld** [comment]
fyi @dougmidgley

**Comment by RyanCavanaugh** [comment]
Please provide concrete repro steps. A screenshot plus "it doesn't work" is not a repro.
