### ISSUE TITLE
Multiline ES6 syntax import formatting

### ISSUE THREAD

**Issue by kuon** [Microsoft/TypeScript#4899]
I am now experimenting with the ES6 import syntax (at least I think it's ES6) and I noticed that the following is formatted, in my opinion, wrongly:

```typescript
import {
Controller as UploadController,
State as UploadState
} from './controllers/upload';
```

should be:

```typescript
import {
    Controller as UploadController,
    State as UploadState
} from './controllers/upload';
```

**Comment by SaschaNaz** [comment]
Should be fixed by #4609

**Comment by kuon** [comment]
Yes it seems to be fixed looking at the PR. Thanks!

**Comment by DanielRosenwasser** [comment]
Let's leave this open until the issue goes in.

**Comment by DanielRosenwasser** [comment]
Duplicate of #4516.
