### ISSUE TITLE
`"importModuleSpecifierEnding" : "js"` has no effect on import fixes from inside node_modules

### ISSUE THREAD

**Issue by vdegenne** [microsoft/TypeScript#48991]
https://user-images.githubusercontent.com/2827383/167141044-9c8f07c3-1ab2-48fb-ae55-4bed98942970.mp4

**Typescript** : 4.6.4
**VSCode** : 1.67.0
**NodeJs** : 16.13.0

I've tried to disable all extensions, but the issue persists.

If I use `"moduleResolution" : "NodeNext"` in my **tsconfig.json** file the `js` extension is attached to the import but it messes everything up.

**Comment by vdegenne** [comment]
@MartinJohns mind explaining the down vote ?

**Comment by MartinJohns** [comment]
Ignoring the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md). Posting a video instead of a concise example and description of the behaviour.

**Comment by vdegenne** [comment]
@MartinJohns I thought more interesting to catch the issue as is while I encountered it in my environment (I also made sure to provide an easy to understand video by showing the essential parts).
Additional information has been added below the video.
The title says it all.
The video shows the actual behavior, and I show the expected one by trying to find a temporary solution.
A video is worth thousands of words.
If I didn't care I wouldn't be posting here in the first place to help the community...

**Comment by xiBread** [comment]
The issue template exists for a reason.

**Comment by vdegenne** [comment]
@xiBread last time I followed the template, one dev asked me to provide a gif/video instead, so again, I did it with care in mind.

Can you be annoying elsewhere ?

**Comment by andrewbranch** [comment]
The GIF is great but ideally we would get it _in addition_ to the issue template. No big deal this time, just something to keep in mind for the future. That said, personal attacks won’t be tolerated here. It’s Friday morning and I’ve barely finished my coffee, everyone chill and be nice to each other.
