### ISSUE TITLE
Narrowing of generic type parameter index

### ISSUE THREAD

**Issue by Fryuni** [microsoft/TypeScript#48996]
# Bug Report

### 🔎 Search Terms

narrowing generic parameter

### 🕗 Version & Regression Information

- This changed between versions 4.4.3 and 4.6.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBAKglgWwgZ2AQwWAwgewDYCuCAdsgDwwB8UAvFAN4CwAUFG1ANoDSUcxUAawggcAM1gBdAFyxuEqBAAewCMQAmyKABE0KqAH4oPGcQgA3CACcWAXw5CR4mBIDcLFqILEAxsDg5+AHMIYAAZXRRgMgAlHAB3BWVVDShoiG8cSzUyVEs+QIAaKC8BYnjiSiKeJRV1TXgkVAxsfCJSGPjKSgAKS3jkGVi4jgkiv0b0TFxCEhkuAEpB+IYWNjhxXv6AOjxVQOAAC1oaOgAGeZXWdkO+hNMEgFFLPstugHIHzFAoNGe0EC2b3mbiuNncV12wCgeAiqCWCTot2QHFOrnBbFEmSg3QypChtygYigSIuTCubFxqCgagiMh0ekR8Q440izWmbTR5KglKhMJUqHpEDpEVo0NhwGZiFZU1aJE5q3Y62xNJUWzMaEIEAA8qJuhdqHzIoK1RqCNrdfNSQr2GL+VDGXEQTawaD0cSQgRLPxDagQS6WKBIFAAGI4HCislsFnClQFBWYnAyXL5OPMf3MHnE-oyUM4EaijgKyPXKUmCAJQXdACMp3OqZtCZkbwARr83vWoDYO8Wo6WoPdtBFugAmWvzDsYsNN1sAL3bCq7RetUGj-fLg5U3QArHXl42oG8AI4ERTz0Gp+XMAD0V6gAGUDjgCHg1NCcIEoLOWJT8BAdu-umCMJxU2OJkCKN4WSBLYE2BIA)
Changing the version to 4.4.4 works

### 💻 Code

Reduced example, the code on the playground is an actual function from our codebase that used to work fine.

```ts
type TimestampColumns<T> = {
    [K in keyof T]: T[K] extends Date ? K : never
}[keyof T];

function getTimestamp<Row extends Record<string, unknown>, K extends TimestampColumns<Row>>(
  row: Row,
  timestampColumn: K,
): number {
  const date: Date = row[timestampColumn]; // This used to work;
  return date.valueOf();
}
```

### 🙁 Actual behavior

The code should compile with no warnings or errors.

### 🙂 Expected behavior

Fails with error `Type 'Row[K]' is not assignable to type 'Date'.`

**Comment by RyanCavanaugh** [comment]
This used to "work" because it was actually completely broken, e.g. in 4.4 you can also write *without error*:
```ts
   const date: number = row[timestampColumn];
```

See #48992 for a possible feature to address this
