### ISSUE TITLE
Add support for Python-like decorators

### ISSUE THREAD

**Issue by csnover** [Microsoft/TypeScript#490]
Copied from CodePlex#1369

The current ES6 and TypeScript syntax for classes makes it difficult to perform any meaningful modifications to a function that is a member of a class without extreme effort. Libraries such as ember.js added additional properties to the Function prototype to augment the function with additional capabilities, but this is not feasible in the class syntax.

Something like Python decorators provide a possible mechanism to solve this problem. As per PEP-318, decorators allow you to define a function that can be applied to another function in place. For example, a naïve logging decorator might look like this:

```ts
// decorator
function log(fn: Function, metadata: DecoratorMetadata) {
  return function(...args: any[]) {
    console.log(metadata.name);
    return fn.apply(this, args);
  }
}

class A {
  // decorator application
  @log foo() {
  }
}

// execution
var a = new A();
a.foo(); // LOG: foo 
```

This provides a capability that allows for very expressive development against the class syntax that is far beyond C#-style attributes and allows for a number of uses including (but not limited to): logging, binding, composition, testing, control over ES5 property descriptors, AOP-like join-points, etc.

In addition to the general syntax borrowed from Python, a TypeScript decorator would accept an additional piece of metadata in the form of a DecoratorMetadata object, which contains contextual information about the target that is being decorated (such as a function, class, method, getter, setter, or even fields and parameters).

**Comment by csnover** [comment]
OK, I don’t know why this issues was never referenced from #1557 but apparently that one is the one that got all the attention so I’m closing this.

**Comment by DanielRosenwasser** [comment]
Sorry about that @csnover. I think it was distinct in that annotations are not necessarily the same as decorators, which is why we didn't file it as a duplicate.

**Comment by csnover** [comment]
No worries. Python decorators were mentioned in the first comment on that one so it seemed like there’s no reason to have it in two places. I talked to @mhegazy a few weeks ago and he described exactly what’s needed, so I know you guys know what’s what. :)
