### ISSUE TITLE
`NodeList#item(index)` should return a nullable.

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#49015]
# lib Update Request

Currently the result of `nodeList.item(123)` does not return a value with `| null` in its type, which is wrong because the result can be `null`.

## Missing / Incorrect Definition

`NodeList['item']`

## Sample Code

```ts
const el = document.querySelectorAll('.foo').item(9999999999999)

// no type error here (bad)
el.append(document.createElement('div')) // runtime error "Cannot read properties of null (reading 'append')"
```

[playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true#code/MYewdgzgLgBApgGxgXhgExMArgWzmKAOgEcs4AnATwGVE5goRyBBBBACgHJCAzEETgEpCASyhwc7AJwzZc2YIBQixIQCGABw3407DNjwFCwcnDXiAoggn4oXNCIBuQwTAD0bmOSwEReeOTkTDAARADCamBgILCmamgwGkHa5FAicBAwIDwwYFhsMOxxDmAA5jCcmtpgaEIhQA)

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/NodeList/item

**Comment by RyanCavanaugh** [comment]
Search for "nodelist item": #38529
