### ISSUE TITLE
Incorrect infer type of return function

### ISSUE THREAD

**Issue by snatvb** [microsoft/TypeScript#49018]
# Bug Report

### 🔎 Search Terms

I tried to write function that will be return size or empty object for use it with spread operator `{...size}`.
I wrote function what returns `? size : {}`, but I get incorrect type.

### 🕗 Version & Regression Information

4.6.2

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/ATBQFMA8AcHsCcAuwBmBXAdgY0QS1hqrLAPIYA2AngBQDOiAhouAFzADkKx7wAPhwCMG8dgEpgAb1AgQ8cIjTxC9JuGABeTRy6weAfm3dgbCQF8A3KFNA)

### 💻 Code

```ts
// returns `{}`
function fooOnly(state: 'foo' | 'bar') {
    return state === 'foo' ? 'foo' : {};
}
```

### 🙁 Actual behavior

Type output is `{}`

### 🙂 Expected behavior

Type output is `'foo' | {}`

**Comment by Josh-Cena** [comment]
`"foo"` is a subtype of `{}`. See https://github.com/microsoft/TypeScript/issues/48988 and a bunch of other linked issues. You would need `{} as Record<string, never>` to get around it.

**Comment by snatvb** [comment]
@Josh-Cena yep, I had the same assumption, so I guess I was right

Thank you for this workaround. But this code can play a cruel trick if the programmer does not notice.
