### ISSUE TITLE
`foo: string = null` does not throw error ONLY in `.spec` files

### ISSUE THREAD

**Issue by nemosmithasf** [microsoft/TypeScript#49019]
# Bug Report
In `.spec` files, `null` is not type checked correctly. *But* it works in `.test` files...

See Image below:
![Screen Shot 2022-05-08 at 8 01 20 PM](https://user-images.githubusercontent.com/14184529/167321275-c6b4641b-5862-405d-9bb5-54d2e2ff6b41.png)

Reproduction:
[jest_ts_nullBug.zip](https://github.com/microsoft/TypeScript/files/8648041/jest_ts_nullBug.zip)

**Comment by Josh-Cena** [comment]
>  `"exclude": ["node_modules", "**/__tests__/*", "lib", "**/*.spec.ts"]`

Your tsconfig excludes `*.spec.ts`, so spec files are type-checked in your editor with the default tsconfig, which has `strictNullChecks` off.

**Comment by nemosmithasf** [comment]
That's strange, I wonder how that got i there... thanks for the heads up
