### ISSUE TITLE
Distributive conditional types are not distributive when a compound type is used before `extends`

### ISSUE THREAD

**Issue by ansavchenco** [microsoft/TypeScript#49013]
# Bug Report

### 🔎 Search Terms
Distributive conditional types

### 🕗 Version & Regression Information
This is the behavior in every version I tried including nightly version of `v4.8.0-dev.20220507`, and I reviewed the FAQ for entries about distributive conditional types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2#code/C4TwDgpgBA8gdgGxAVTmATgewLYEsDOEAJgGJbYCC66AhiADwAqUEAHsBHEflDXCAG0AugD4oAXigBvKAIDSUXHCgBrCCEwAzKIyEAuHfKEt2nblAAK5AhHpLNEdFABKYgPwuoBuBABujqABfACgAY0w4fGBeaglZHwB3S2tCeij0JQBzEQAKHIBKCTEpQPyAGihE5JwbejgAV2wAI0dcgqLpUorgdHqIIWDQSBcARjj4JFQMGsJScipaBiGILRj0EWDN5dhEFDQU4jIcBboSXFZiJhMOLh4+QSEKizjGATUNbV0xSRl5RWV3qtdAZnmwbuYrDNbPYAq4oB5nF5Kn4AiFts4AEzjXZTA5zY7UU7nS7LVY0agiIA)

### 💻 Code

```ts
type OnlyUnpromisedFromArray<T extends any[]> = { [K in keyof T]: T[K] extends Promise<infer R> ? R : never }
const arr = [new Promise<string>(() => {}), new Promise<number>(() => {}), true]
type R1 = OnlyUnpromisedFromArray<typeof arr>


type OnlyUnpromisedFromArrayFixed<T extends any[], P = T[keyof T]> = { [K in keyof T]: P extends Promise<infer R> ? R : never }
type R2 = OnlyUnpromisedFromArrayFixed<typeof arr>
```

### 🙁 Actual behavior

Type `R1` is `never[]` and `R2` is `(string | number)[]`.

### 🙂 Expected behavior

Both `R1` and `R2` are `(string | number)[]`

### 🤔 Thoughts

Seems like the problem is the fact that in the `OnlyUnpromisedFromArray` distribution happens over `T[K]` which is kind of compound, whereas in the `OnlyUnpromisedFromArrayFixed` it is just `P`.

**Comment by fatcerberus** [comment]
That's expected.  Conditional types only distribute over a naked type parameter, which `T[K]` is not.  Same reason `[T] extends [U]` disables distribution.

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types
> Conditional types **in which the checked type is a naked type parameter** are called distributive conditional types.

**To TypeScript team:**
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html
The "naked type parameter" rule isn't mentioned in the current handbook, only that the behavior can be disabled by bracketing the types.  Ideally this rule would be explicitly documented, and IIRC it used to be in the original Handbook text?
