### ISSUE TITLE
Instanceof left-hand side check rejects Array Objects

### ISSUE THREAD

**Issue by JoelBonetR** [microsoft/TypeScript#49026]
# Bug Report

### 🔎 Search Terms

Closed issues related to this topic:
https://github.com/microsoft/TypeScript/issues/2775
https://github.com/microsoft/TypeScript/issues/19298

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBFQ4ZoeMheRDwPoMYHsGhfNxmZjsBjMSD8WDQdSJRnwPQiLwAIgAoqsGIgFvoxUlsWLwA5UAByYQAOUgEjFQRUAHkvmR3oIeVpIEdUI4FK5pHhQE46Tphlh9CgEIhocJLqyJPToiIDBxsQsmKwODwgskuLB6o0cfB4AAKRB4CpkMj5SqZpgAHkEqEonGYAD4AJTZjNkfOF4tl0AAb0UJRKCNAyYAhGnq6AAD590Dd9OZ0WFswWInVpjlx2W-FeADaAF0ANwt1tOVAL0A9zMBZKYhRkZPg6CgAC8pbPAQyfPY3H0ybV2Gg0HgavL5fXAF8gA)

### 💻 Code to reproduce

```ts
function foo(myArr: Array<string>): Array<string> {
    if (!myArr || !myArr instanceof Array) return [];
    return myArr.filter( el => el.includes('hello'));
}
```

### 🙁 Actual behavior

`The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.ts(2358)`

The error is claiming that the left-hand side of an instanceof expression must be of type any (no clue at all if I need to take this explicitly or implicitly, meaning that it can be literally anything or if it needs to be declared as any), an object (which is weird because Arrays in JS are objects. i.e. `typeof ['one', 'two'] // object`)...

### 🙂 Expected behavior

Array type can be evaluated using Instanceof.

**Comment by whzx5byb** [comment]
The `!` operator has a higher precedence than the `instanceof` operator.
You should use parentheses to make your code work:
```
if (!myArr || !(myArr instanceof Array)) return [];
```

**Comment by JoelBonetR** [comment]
> The `!` operator has a higher precedence than the `instanceof` operator. You should use parentheses to make your code work:
> 
> ```
> if (!myArr || !(myArr instanceof Array)) return [];
> ```

My bad always forget about this thing and assume `[left-hand + instanceof + Type]` as an expression😅

thank you!
