### ISSUE TITLE
Go to definition broken on Chrome Extension + tests

### ISSUE THREAD

**Issue by vict0rsch** [microsoft/TypeScript#49024]
# Bug Report

### 🔎 Search Terms

Go to definition

### 🕗 Version & Regression Information

VSCode `Version: 1.67.0`, TypeScript and JavaScript Language Features `v1.0.0`

I'm working on a Chrome extension and have a set of `.js` files imported in the extension's popup in `<script defer src="../utils/X.js"></script>` tags.

The folder structure looks like 

```text
src/
  utils/
    parser.js
    functions.js
    other.js
  popup/
    popup.js
    popup.html
```

`popup.js` uses functions from files in `utils/` and the files in `utils/` use each other's functions. 

All was going well and I could navigate to function definitions with `cmd+click`

As I integrated tests, and to be able to test my functions in a `node` environment (`mocha`) I added the following at the bottom of my util files:

```javascript
if (typeof module !== "undefined" && module.exports != null) {
    module.exports = {
        log,
        ...
    };
}
```

And that breaks VSCode's ability to `Go to Definition`, not sure why nor how to fix it and [could not get help on SO](https://stackoverflow.com/questions/72144266/javascript-vscode-function-definition-broken-with-module-exports).

For reference, here's my `jsconfig.json`:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
    },
    "include": [
        "src/**/*.js"
    ]
}
```

**Comment by sandersn** [comment]
I tried a simple repro with two files:

```js
// @filename: first.js
function f() { return 2 }
if (typeof module !== "undefined" && module.exports != null) {
    module.exports = { f }
}
// @filename: second.js
const { f } = require('./first')
f()
```

And this worked fine. I used a tsconfig.json but that's basically the same as a jsconfig.

There might be some other errors in your files; can you set `checkJs: true` in jsconfig.json as well?
If that doesn't fix it, can you provide a test repo or provide a complete test repro here?

**Comment by vict0rsch** [comment]
@RyanCavanaugh I'm not importing `log` without `module` _per se_, all those files are minified together to be usable from the extension's `html` page

**Comment by vict0rsch** [comment]
@sandersn I just added `"checkJs": true` and now I'm getting errors (but we may be getting somewhere 😅)

<img width="353" alt="2022-05-10 at 09 29" src="https://user-images.githubusercontent.com/9283470/167573428-b4160cce-5778-4276-bde1-37d48ccc1b5a.png">

**Comment by vict0rsch** [comment]
What's bugging me is I didn't have all those issues up until recently. 

Maybe I'm wrong in assuming it's the `typeof module !== "undefined" && module.exports != null` bit, maybe it's an update, maybe it's a setting I messed up with but I'm kind of stuck on debugging and where to look in order to get the `Go to definition` back

**Comment by vict0rsch** [comment]
_Actually_ removing that line _is_ the issue, removing the conditional `module` exports **does** bring back Go To Function Definition with my original `jsconfig.json`...

**Comment by vict0rsch** [comment]
I'm guessing VSCode is reading that line `module.exports = {` and assumes it's a module script when it's not

**Comment by vict0rsch** [comment]
I can confirm that 

```
var dummyModule = module;
if (typeof dummyModule !== "undefined" && dummyModule.exports != null) {
    dummyModule.exports = {
        log,
        ...
    };
}
```

both enables `Go To Definition` _and_ `node` tests

**Comment by sandersn** [comment]
1. Can you make small repo that isolates the problem?
2. re:
> I'm guessing VSCode is reading that line module.exports = { and assumes it's a module script when it's not

It's not a module? I thought the problem was that it *was* a module and its exports couldn't be imported elsewhere.

**Comment by andrewbranch** [comment]
If the file contains a `module.exports =`, we’re going to assume it’s a module. What you have written is a file that is usable as a module or a script. TypeScript (which powers JS IntelliSense) doesn’t really have a way to represent this; each file is either considered a script (with shared global scope) or a module. It seems like your files are first and foremost scripts, with a handy modulification feature tacked on for testing convenience. My recommendation would be to trick TypeScript into not seeing the `module.exports` by doing exactly what you did with `dummyModule`. You might find `module["" + "exports"] = ...` or `module[`${"exports"}`] = ...` a more palatable workaround.

**Comment by vict0rsch** [comment]
Ok that makes sense thank you @andrewbranch!

Sorry I missed your reply @sandersn, it's a script indeed for the browser extension. But testing individual functions with `mocha` requires importing them as modules' functions.
