### ISSUE TITLE
Add a second generic to `reduce`, for intermediate return value.

### ISSUE THREAD

**Issue by mimafogeus2** [microsoft/TypeScript#49028]
# Suggestion

## 🔍 Search Terms

reduce

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a secondary generic for the `reduce` function, to allow a different types for intermediate value (return value of each iteration) and the final value (return value of the final iteration). In practicality, this means that the second argument would define the type of the aggregator.
The default value of that second generic would be the first generic, so it'll be backward compatible and won't break anything.

## 📃 Motivating Example

Here's a simple example - sum all numbers in an array and add the biggest number again (the example I've given at https://dev.to/mimafogeus2/pure-reduce-functions-use-aggregator-as-a-state-32h6):
```typescript
interface IReduceState {
  sum: number,
  biggestNum: number;
}
const sumAndBiggest = arr.reduce<number, IReduceState>(
  (agg, val, index, sourceArr) => {
    const { sum, biggestNum } = agg as IReduceState
    if (index === sourceArr.length - 1) {
      return sum + val + biggestNum;
    }

    return {
      sum: sum + val,
      biggestNum: Math.max(val, biggestNum),
    };
  },
  { sum: 0, biggestNum: Number.NEGATIVE_INFINITY },
);
```

In the real world, this could be used when you:
- Count/group/aggregate elements into several categories, then choose one or some of them.
- Keep aggregation metadata but don't wish to return it.
- Work on items of a format that's friendly to the reduce function, but needing a differently formatted/constructed return value.

## 💻 Use Cases

Reduce is a powerful function, but developer often resort to defining variables out of the reduce function's scope to keep data between iterations. It is possible to write pure reduce functions by using the aggregator as a state, and returning a value depending on wether we're in the last iteration or not.
The current TypeScript implementation of reduce assumes that the final return value and the aggregator have the same value. This limits the user to using a union type, then assert the return value.

**Comment by jcalz** [comment]
How could the compiler understand or verify that the callback will correctly return the final type only in the last iteration, and the intermediate type for all other iterations?  It can't look at `if (index === sourceArr.length - 1)` and do anything useful with it. So this proposal wouldn't give us anything type safe; the compiler would happily accept any callback returning the union of intermediate and final types.

Do you have evidence that this is a common approach to using `reduce()`?  If I wanted to do this I wouldn't be checking the index inside the callback.  Rather I'd just apply the final transformation to the result of the normal `reduce()`.  You don't even need to declare new variables, and you get reasonable type safety:

```ts
const sumAndBiggest = (({ sum, biggestNum }) => sum + biggestNum)(arr.reduce(
  (agg, val) => {
    const { sum, biggestNum } = agg;
    return {
      sum: sum + val,
      biggestNum: Math.max(val, biggestNum),
    };
  },
  { sum: 0, biggestNum: Number.NEGATIVE_INFINITY },
));
```

And if I found myself doing this often enough to want a shorthand, I'd define a function for it and use the function multiple times later:

```ts
function reduceAndTransform<T, U, V>(
  arr: readonly T[],
  reducerCb: (agg: U, val: T) => U,
  transformCb: (agg: U) => V,
  init: U): V {
  return transformCb(arr.reduce(reducerCb, init))
}

sumAndBiggest = reduceAndTransform(
  arr,
  (agg, val) => {
    const { sum, biggestNum } = agg;
    return {
      sum: sum + val,
      biggestNum: Math.max(val, biggestNum),
    };
  },
  ({ sum, biggestNum }) => sum + biggestNum,
  { sum: 0, biggestNum: Number.NEGATIVE_INFINITY }
);
```

[Playground link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwQLhmArgWwEYFMEDaAujALwwECsANDACy0CMADLQMy0BMTRAsAFACANrlgQsAQTAATAEIBLAOaLc0MjAAUGgN4xxmWtiUroAOSwwAvgEoyAPj0WA1DCPLVUc5msbECAHQIuNLowLgaAjCacMq0AG5wQrakDtqRUTCgkLC6+obGHl5W6jGKANzpUUFQ6AhgMGn8GRn6qPowLglC1JUZbiaeWKgAsnBQABb+mHAAHhpd+e5mWNY9TRmWFeuWa1G5QzCsrgXLmKheeAGmAKIA4hIAKgCSAGrXAPpPpgBiX08PAE0rGtrNYtgIshAQCJ-EIQIoNPopHITlBbAB6dEwNiUAQCABm6DAwCg8nAMCCITCyIeCDgkHxIAQmAAPA9aABVWgvOwRdZ+VBBODScBCACeMAexF2FOCoXwAGFsKhfMpUFyYF1UA9kg4uekoHSGUzMEqVaV1bqYC8ZfIwPIoJbUC8GulqrV6ob6RBGcylb4kIE5WENJT5QglbQ7Q7QQJLHj+EiZAolrByGHqTJad7fZg+VE-DLVYp4okrY1mpCco4DMdU0VLCVlFtmu66q71s1WjWOprEjLmv1CgdRhMprN5v26wMvKtept0jt0joa4sZxYbPYey4h6cZfszoc18PDxd8P4bvdnm9Pj8-oCrAIwQnIdDcLD4YjJMnURisTigA)

**Comment by zsakowitz** [comment]
How would this be strongly typed? I see that your example could augment the `Array` interface like so:

```typescript
interface Array<T> {
  reduce<B>(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => B): B;
  reduce<A, B>(callbackfn: (previousValue: A, currentValue: T, currentIndex: number, array: T[]) => A | B, initialValue: A): B;
}
```

However, this just enhances the likelihood of mistyping. For example, both of these examples would validate through the new overload even though neither returns the correct type.

```typescript
let first = [1, 2, 3, 4, 5].reduce<string>((_, el) => el);
console.log(first); // 5, not a `string`

let second = [1, 2, 3, 4, 5].reduce<string, boolean>((a, b) => b && a || a, "hi");
console.log(second); // "hi", not a `boolean`
```

The second function arguably makes no sense and would be terrible to debug, but your idea is perfectly fine with it. To properly check the correct generic was the last value returned, TypeScript would need to execute your code, and it's implausible to check at runtime, not to mention that it also goes against TypeScript's design goals. I don't think this should be added to TS. If you need to transform the final value, use something type-safe such as @jcalz's idea above.

[Playground Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIJSnAngHgCoB8yA3gLABQyyUEAJgK5I4BCBAFAnADZcBGiAaxggAXMjYAHGgDdgAe3oBnAGrd6EMXgA0yBPQwRwqrus069B8AEkQtCAA8xIegFte0HXAzZNAbQC6AJTIALxEeMgAPsjMgWLMANwUVDQMTKg6rBzcfILCYpIy8krGpmjm+jRGahrI2rqVhmA2do7Izm4eyF6YWH5BoUSoUTE6oMBgwNyltahxMUnkAL4UFFwQYMgwwFCKmyHIvgCMOgBMOgDMOgAsOgCs-gB0qYwQOHtQoADm7GwA+joIFxgmFkEDAosEHIQIo5OtHlw5F82NtdmAIcgAPSY5B3HQgOSbODIAAGH2+JNW5HWm0UEChtlChxOyHOyCuyFuuKeLyY5JAXx0vDkcIgcBAvzgQpBRF4yAAZPLulFolLkAAiAAWwHVEIoDNh8MRyLpDNoGOxGu16vxhOVJOFovFlPIQA)

I also know we're not supposed to discuss anything outside of this, but @jcalz's code could be improved with [pipeline operators](https://github.com/tc39/proposal-pipeline-operator), so give that proposal a cheer. Thanks!

**Comment by andrewbranch** [comment]
Indeed, the suggestion is not possible to implement.
