### ISSUE TITLE
Callback argument of generic does not infer type

### ISSUE THREAD

**Issue by kcirtaptrick** [microsoft/TypeScript#49020]
# Bug Report

Callback **argument** of a defaulted generic does not infer its type even though the callback **function** has the correct type.
![image](https://user-images.githubusercontent.com/13372825/167322375-524074f3-eeaf-4610-b082-6c4cb4b2253a.png)

### 🔎 Search Terms

Generic, default, inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Generics](https://github.com/Microsoft/TypeScript/wiki/FAQ#generics)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220508#code/C4TwDgpgBAKhDOwA8MoQB7AgOwCbygCIBDQqAHyICMyBeI0gPinoG8AoKKYgLilagBjYgBsRVYoIDWACmIAnAOZ8ShAJR8AbgHsAlrigBfANycoVPgOFiJ0uUpU0NUHfqOnDAbRgBdU+wAzAFdsQWBdbWwoLEQUNEwcfAYySkIaFmTGe2VYBGQYRjV+Q3Z2GOAZDi5rcUlZBUUi1kMAGnZDNWMgA)

### 💻 Code

```ts
type Test<T extends "a" | "b" = "a"> = {
  a: { callback(arg: "a"): void };
  b: { callback(arg: "b"): void };
}[T];

function test<T extends "a" | "b" = "a">(arg: Test<T>) {}

test({
  // `callback` is correctly typed with `callback(arg: "a"): void`
  callback(arg) {}, // Error: Parameter 'arg' implicitly has an 'any' type.
});
```

### 🙁 Actual behavior

`arg` type is not inferred

### 🙂 Expected behavior

`arg` type should be inferred with type `"a"` in this example

**Comment by MartinJohns** [comment]
I'm fairly certain that this is a duplicate of #47378.

**Comment by kcirtaptrick** [comment]
Ah yes, you're right, closing this one
