### ISSUE TITLE
Irregular behavior of generic non arrow function that is typed via JSDoc import.

### ISSUE THREAD

**Issue by lillallol** [microsoft/TypeScript#49039]
# Bug Report

### 🔎 Search Terms

allowJs, checkJs, type imports via JSDoc, generic functions, no compile, inconsistent behavior, inline type, arrow

### 💻 Code

* `./privateApi.ts`

```ts
export type IFn = <T>(m : T[][]) => T[][];

const inTsArrow = <T>(m : T[][]) : T[][] => {
    return m;
}
inTsArrow([[1]]); // no error gets linted as expected

function inTs<T>(m : T[][]) : T[][] {
    return m;
}
inTs([[1]]); // no error gets linted as expected
```

* `./index.js`

```js
/**@type {import("./privateApi").IFn}*/
export function inJs(m) {
    return m;
}
inJs([[1]]); // lints error. Why?

/**@type {import("./privateApi").IFn}*/
const inJsArrow = (m) => {
    return m;
}
inJsArrow([[1]]); // no error gets linted as expected
```

* `./tsconfig.json`

```json
{
    "compilerOptions": {
        "checkJs": true,
        "allowJs": true,
        "target": "ESNext",
        "strict": true,
        "noEmit": true,
        "rootDir": "./",
        
        "skipDefaultLibCheck": true,
        
        "noUnusedLocals": true,
        "noUnusedParameters": true,
    },
    "include": [
        "./**/*.ts",
        "./**/*.js"
    ],
    "exclude": [
        "node_modules",
        "TBD"
    ]
}
```

**Comment by sandersn** [comment]
Looks like the code that applies `@type` to signatures doesn't recognise that the signature for `inJs` should be generic. `inJsArrow` uses the normal type annotation machinery and doesn't have this problem. 

Notably, for uncalled identifiers, quickinfo gives `function inJs(m: T[][]): T[][]`, but `const inJsArrow: IFn`. In the former, `T` is unbound, so there's no way for anything to be assignable to it.

**Comment by lillallol** [comment]
@sandersn 

Here is another bug, where optional function parameter is treated differently for arrow and now arrow functions:

* `./privateApi.ts`

```ts
export type IAdd = (a:number,b?:number) => number;
```

* `./index.js`

```js
/**@type {import("./privateApi").IAdd}*/
function add(a,b) {
    if (b === undefined) return a;
    return a + b;
}

add(1);//lints error because it wrongly requires the second optional parameter

/**@type {import("./privateApi").IAdd}*/
const addArrow = (a,b) => {
    if (b === undefined) return a;
    return a + b;
};

addArrow(1);//works correct
```

should I open a new issue about that?

**Comment by sandersn** [comment]
No, it's basically the same problem.

**Comment by lillallol** [comment]
So I am facing a new problem that I think is a bug.

[Here](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCSBxYMCywCGAdgBIQCuUANogDIT4AmAznALxwAU+UA5kwFxwA3gCg44uDhyCmMKAEtCPANxiJATU3qZcxSrXjC+ALbBBAIiOmAjObgAfOJZPAATHcfPTAZnOqAvgCUbAB8cIRkxgBGwFAA2gC6iaoiSCjoAMqx8viU8gBe+FGUwABquWSoEmyZ2bkFRSUASsAAZrHAhADGqI5oWQr1hcXAAAoKxvIw8gBuwKppqP11ecPNbR3dqOzLg6uNZRXAiQ7CcSBwOgpKCZe1ew0j5ZSV-gvISwM5+yPj8pPTOY1WTXHinKIQCAlIinCLRWKwsiUSgpUCQWAID7oPDGCAFbZwAA8BjgozgoBgnWY92+jxKz0qiQANCSmiIQhwSa1CHcOHAAHSCsDcFyUqAsQSjYKsMJs6VhPmC-nCqCi2IS0nyuBNVHgaDwBjALqUbioLoQQiyOCmXH4u5oHF4-LzOAiETmy3wHjYPBEUgUah0RhMAAiRug+EpDHtWFwBBI5CotHo1PY1uAtudHC4vCYWtE1Sg2AoPOSIiCyiAA) is the code that works on `.ts` file without any problem.

Now consider the previous example as a `memoizeBug.ts` file. I write the following code in a `.js` file like this:

```js
/**@type {import("./memoizeBug").IMemoize}*/
const memoize = (fn) => (...args) => fn(...args);

/**@type {import("./memoizeBug").IGetMeanHourlyLoads}*/
const getMeanHourlyLoadsDecorated =  memoize((args) => {
    return [];
});
```

and I am getting a linting error. The `.js` file does exactly the same thing as the `.ts` file. Why am I getting a linting error in the `.js` file and not the `.ts` file?

**Comment by sandersn** [comment]
@lillallol can you file a new bug? That code doesn't have any function declarations.

Also it would help to know what the error in the .js file is.

**Comment by lillallol** [comment]
@sandersn I submitted a new issue [here](https://github.com/microsoft/TypeScript/issues/52042).
