### ISSUE TITLE
Proposal: Infer function/method parameters as an object, not a tuple.

### ISSUE THREAD

**Issue by danfma** [microsoft/TypeScript#49038]
# Suggestion

Look at the following code:

```typescript
// An utility type that excludes functions from the type
type DataOnly<T extends object> = {
  [P in keyof T]: T[P] extends Function ? never : T[P];
}; 
// there is another suggestion for this kind of type, but I will let it to another issue! :D 

// Here we start:
// 1. define a type with self defined parameters
class Point {
  // 2. let the last one as optional by receiving a default argument value
  constructor(readonly x: number, readonly y: number, readonly z: number = 0) { }
  
  // 3. create a function that will receive the constructor parameters as an object and create it
  static from(data: DataOnly<Point>): Point {
    return new Point(data.x, data.y, data.z);
  }
}

// 4. try to create the point without the "optional" parameter.
const p = Point.from({ x: 0, y: 0 }); // this will cause an error, because DataOnly is inferring 
                                      // the optionality from the members, not from the parameters
```

[This example on TypeScript playground.](https://www.typescriptlang.org/play?#code/PTAEEEDtQVwFwJYBsFwJ6nQBwKaYBYCGcoOAHgMZIwAmOAzqAGYyQWID2kjTAThwFsCebDgBQo0ABFihAPKQkaADwAVUmTg5INRhwBGAKxzsAfKAC8oAN5jQoANoAFUAmgBrHGg5NQqgLoAXH7O-hpaOowAYqzsCFygAPygkDgAbji8oMGqoQDcYgC+eaBiIMK8eAiMhJAccPiZoPQwAOatDJzQTBxZDdWg7m40oD6YaLgANKD68KAAkqAA7shIoEg4JKiYHKC19Y1Z1S04AITZUqVlYAASmXhLePRwhLxwgdegAIwAdKB0TDceEI41wy1Q+GaOCQvgBQJGWFehAEm0y9DEVEI9EYTg4bhItns5QATH8NiQGngkFiSFxgXosF1CGt9BhKhQcAg0m5Wnt-jgmIQYEgSK9WjAUZASGlmTBxPYKFxnrwYOxegAKSqEGhcJSgMjBSAS-SZaZanWKDBoQ3G02gc26jAALxtAhNWSsAAYAJQ2UCFOylIlgADMfwoWq0fJYbC6BGI4KQa3ZnIywlAiu4cBVaqyiN4yNRvBqNWgBmM7D2OgzkaqcEDz2ICAozH4AnVNFkwRkLwUSmUuPxpm9wUHUpsgfslTgMF40FSS1AY7gHdkPzI007Lx+aE3a6d3oK9gDAc+ABY-tmMHBdhGcMQRI1QFg8eOVg0OHNKaAAEQcRnxJAzI-s+SIolovA-BiSokFglhLq+cA-HwgjqtY+rBJ60zWqAnr+oeoDlP0jArEmGZCvQwLQJk-C8NMJoUBReA9vIlquIwbhMDRPJBvYfH8QJglCcJwbpv+TIoOgraCOmKJumi0x1CQKFCN++aFhB6JiGIQA)

As expected, there is no way to use that definition because the field is not optional, only the parameter in the constructor is. And, also there is no way to extract the labeled tuple keys.

So, my suggestion is:

* Option 1: an utility type to extract the labeled names of a tuple (which I know that can be a problem because that probably will require a new way to work with those types);
* Option 2: a more feasible one, **just an intrinsic type that returns the parameters of a function/constructor as an object, not as a tuple.**

Something like:

```typescript
export type ParametersAsObject<T extends (...args: T) => any> = intrinsic;
export type ConstructorParametersAsObject<T extends new (...args: any[]) => T> = intrinsic;
```

> Because this type is just an additional type to the library, it should cause no compatibility issues. Also, I found some people 
> trying to do the same on StackOverflow too, so probably I won't be the only one interested in that kind of functionality.
>
> Functions and Constructors will force you to specify a parameter name, consequently, 
> they should be safe for this kind of an operation because each parameter will have a name and a type.

With that, we would be able to easily fix the code above:

```typescript
class Point {
  constructor(readonly x: number, readonly y: number, readonly z: number = 0) { }
  
  static from(data: ConstructorParametersAsObject<Point>): Point {
    return new Point(data.x, data.y, data.z);
  }
}
```

## 🔍 Search Terms

Labeled Tuple Extractor, Parameters as Object

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
We've been very intentional to not let parameter names "leak" into value positions (except when opted into, like parameter properties or parameter destructuring). Allowing this transform to exist would really raise the stakes for definition file authors in a difficult way without a sufficient uspide in terms of allowing developers to express common patterns.
