### ISSUE TITLE
Compile time comparison of accessors fails to differentiate on setter/getter

### ISSUE THREAD

**Issue by neirfeno** [microsoft/TypeScript#49046]
# Bug Report

### 🔎 Search Terms

- type check read-only accessor
- compile time check for setter

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type checking of accessors

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220510#code/MYGwhgzhAECSC28CuAXMAjEBTaBvAUNEdAOZYrQAOATgPaUAUAlAFzQQrUCWAdiXoWJDq5JNR7QA5ADNatSQG5BRAL741+UJBgBZVBmwChEclTqMAbmBBIsbDtz5M8ajVqjQA8igAWWakbEZBQ09ABMzPacvPwEQsKi4lKy8kpCrviatDwc0ChYuQC80AwWbHpomFjOhQB8Lkr4+RwMPFgA7l6+-sxMSgD0-QDCtPCUXIb+dAGQ0FgAHpRYwPkAJk0FKK0dcIj6Vb0D-QBytHPU0wA00Oio0O20SCCr0NYQZwtLK9DZWEA)

### 💻 Code

```ts
class Immutable {
    get prop(): string {
        return 'foo';
    }
}

class Mutable {
    set prop(value: string) {}
}

class Other {
    get prop2(): string {
        return 'foo';
    }
}

const test = (v: Mutable) => {};

test(new Other());
//Compile error as expected
test(new Immutable());
//No error, but would also expect one
```

### 🙁 Actual behavior

`Other` correctly causes a compile error as it does not have `prop` property. `Immutable` passes compiler check even though the `prop` property is read-only (just a `get`)

### 🙂 Expected behavior

I would expect both `Other` and `Immutable` to fail the typing of `test` as neither adhere to the structure of `Mutable`.

If inside `test` I try and set `v.prop` when `Immutable` is passed in I get a runtime error. I would expect the typing to guard against this.

**Comment by fatcerberus** [comment]
This isn’t specific to accessors and happens with `readonly` properties as well.  Unfortunately readonly-ness is a very weak guarantee in TS :(

**Comment by RyanCavanaugh** [comment]
Duplicate #21759 / #18770
