### ISSUE TITLE
Narrowing of this in the returned type of a parent method

### ISSUE THREAD

**Issue by fwolff** [microsoft/TypeScript#49047]
# Suggestion

I'd like to be able to narrow the 'this' type in a parent class, for example:

```typescript
class AnySchema<T> {

    isRequired = false

    required(): this<Exclude<T, null | undefined>> {
        this.isRequired = true
        return this // an explicit cast could be necessary here
    }
}

class StringSchema<T extends string | null | undefined> extends AnySchema<T> {
}

const schema1 = new StringSchema() // type is StringSchema<string | null | undefined>
const schema2 = new StringSchema().required() // type would be StringSchema<string>
```

Currently, I have to write this kind of code (which is ok but a bit cumbersome) to get the expected returned types:

```typescript
class AnySchema<T> {

    isRequired = false

    required(): AnySchema<T> {
        this.isRequired = true
        return this
    }
}

class StringSchema<T extends string | null | undefined> extends AnySchema<T> {

    required() {
        return super.required() as unknown as StringSchema<Exclude<T, null | undefined>>
    }
}
```

## 🔍 Search Terms

this narrowing, this parameterized

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Be able to narrow the 'this' type of the returned type of a method in a parent class. There is maybe other ways to achieve the same feature but I couldn't find any.

## 📃 Motivating Example

See 'Suggestion' above

## 💻 Use Cases

See 'Suggestion' above

**Comment by MartinJohns** [comment]
But how do you know that you actually do have a generic type argument? `this` could be `class Foo extends AnySchema<any>` as well, and then the type has no type argument.

**Comment by fwolff** [comment]
Yes, you're write, that would be an issue, but I guess the compiler could check for this kind of inconstancy.

I'm not actually sure that the syntax `this<...>` is the right way to go but I'm wondering if there is any way to achieve this kind of narrowing without overloading the function in the child class.

**Comment by fwolff** [comment]
Thanks for your answer. As a side note, do you see any other way than overloading the method in the child class like I did in my example?

```
required() {
    return super.required() as unknown as StringSchema<Exclude<T, null | undefined>>
}
```

I can perfectly live with that but I want to be sure I don't l miss something here.
