### ISSUE TITLE
Is this a bug? - Call Lambda 'super.method' in SubClass override method with [ TSC, ts-node, Quokka ]

### ISSUE THREAD

**Issue by m-fire** [microsoft/TypeScript#49068]
# Bug Report

### 🔎 Search Terms
TypeError: (intermediate value) is not a function

### 🕗 Version & Regression Information
$ tsc -v
Version 4.6.4

$ ts-node -v
v10.7.0

$ quokka -v
bash: quokka: command not found...em.. sorry

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/ko/play?#code/N4WAUOCQAuCeAOBTABAYQPYDNOMagrvMgLzKhiSQDOAFutFQFzIB2+AtgEaIBOUkAdwCG0Xs07p0AG0RCW-GkKoBZAJZSA1uMky5UAL7goqlqJ6YhAYxQZsuZUI1DOMsv3aO8WHIgAUteiZWDm4eAEpmWx8CeAMjCjgkZAdLGhMvFipoHnxLaHQeAB4AFQA+ElZEAWRfdHhoVXQWZgcNRAB5esaWMJJy4viYBBRWjq6mivJKS29cACFZTOY2Ll44iApnLJ4raGRLKSUqNFnEFLSWFFV2eBl2RFNjqPtHZ1cpyHgeVQA3ERQsiJVJZkDxZAATJpSWDIOYAUQAggA5ADKAH0AOIAJQRymUaIACnCsWiUQAJdrFZYhXgVADsg0++BcwP2TW2uXyPF8X1+-2QdQaTRank6Qp6bgokEMG0ogIaIIseQKMNIJWQiAAHqIWOCnqdzulSr4PKl0iKzZcMJlspyCiVSgAaAXjZrJUWuiLIYp9SWUSBg6D4HgsSrVU0XPyC7phfgy9yeZ4oUj+OgMamrcKRU4xX0fGBpKgAOgA5t9dQs5FRU4FY1KC6pi19EDRZNBfHX-YHg6HoIWi1rsrsawxO9L+Jh1FIk5XMhVfNwqxnQhUAAxen7oVTgvP8SCqTA1Rdzwqkdd+-19njoaqXapwnjX7kAciTyGPx3Y+Cy75QZbbtJ9nIyCrs+Y7jvWfaNkW0ZNEWMx2Igs7HAA1KQH5xvwByLPOvTEOU+YzJk0iIEWUjoCWvgAAaoLoLAmCWyARukRasVRY4ypQvJ-KIyBliY4LIfOATpsEmZ4QRe5EVQJFkRR1EYuW4IMb+VbIJgBTIAAJMAyAicc+jsXuB41FBxawSw8GnEJhR6WmxwAFQnIhhqXEW8LIui2K4viRIkuSlK9PmBbXreVTIA+T6+M+SL0BqLDoPgJY0GyiGqZkYF7pxlBmTBrpWYhQkALSkPpyBOUmrmkR5qKYjieKEsSpIUgMUrZdx-LNq2Ii4bu9bSbJ5GUVR3UNCwjGEKxrGALwbgBFO0ZbWMl89CIHkiA7lsQ55Bq2o7HkI5BCsoRekmMTrFABxHMgCL3N8lhyOgVU7TqerOT4T0fPAzJSKy0m2sq3IWSKbRijGF7UIQvC1J6mGyp816iGtO6Dntewpvpy68CdOaEH1-oDTIcnDQS+BSD943abpZX6HZgRTcggB8G4AyrsLV2iBBiG4PUPZzrCGYzC2ogzqKCo6haOpQhSFQQtZbDEEXYcVDHHCVDNkrj1WJGz0PK9lWa+kF5fSyIJ-TkAPQ+KwNjOKQV7lQkOAzDi1wx4bRvuj9mY+EePTOyexfWC7t6Q7Rau14iEHeB3ac7pU0B+HPi8-8PACzkQvICLaiaKn+AoNl8ZSstiOiMju27MJnticd2aIbm+HgwTpFDdRJNkypOm0wwyA0-p9PM6zlDR6GwX6Un-MS1L6eZ2LzAWJPjqy878sUJdSvIAAMiIohPYOOv6i5+uXIb32-X7Ztchb3RW6DTS2-W9tII7NuwwmbunBXgRexJDd+0xYsAGJggTrgCoD9eCh0TKcSOe4h5kGQFNdgACgFJjHmIZAgthZKCzuLQW3cX6FwRqtEuz1UYf1EkdLGNdoi43roRdkg15JUVbuTRiHdqad2LKxRmLMo7sx7FzUeyA+ZoIwRnLBM90FpwXvWfO50V6-yELdYED0qpUJeE4FwyY3ovEtKRJUXJYC+BurwZRCUqrOg+AhHwyFmAAEZVyrgMJ2P6GpVZgnVqo7RZxXiaIqHrXRRZ9Eql8CrNWMlzEXisfMRYQR7GOIoPoZxv9DjQG3ofRAajvEaNcKQfxkZAm7GCZvVJ3jdEWKwtZGJdiHFOMGC4xRJj7oJQqA0u6Kj0kQLfhHWxnZWmmPQBdX+iA3HDJkhUYZYSNYBLDkmXwAAmTsEz3EyUGTafYQgcDFN4qQFJaTpmQO6c4jZiAtmIHiDKIAA)

### 💻 Code
```java
abstract class CoffeeMachine implements CoffeeMakable {
	public makeCoffee = (shots: number): CoffeeCup => {...}
}

class AmericanoMachine extends CoffeeMachine {}

class EspressoMachine extends CoffeeMachine {
	public makeCoffee = (shots: number) => {
		const milkFreeCoffee = super.makeCoffee(shots)
		return { ...milkFreeCoffee, water: true, hasMilk: true }
	}
}

class LatteMachine extends CoffeeMachine {}
```

run code
```java
const americano = americanoMachine.makeCoffee(1)
americano
const espresso = espressoMachine.makeCoffee(2)    <<< CRASH
espresso
const cafeLatte = latteMachine.makeCoffee(1)
cafeLatte
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/58259968/167874391-3ce82403-c465-45b2-ae1f-eca09d6af7c0.png)

### 🙂 Expected behavior

![image](https://user-images.githubusercontent.com/58259968/167875161-33ba6854-2ea9-4c70-9f70-13a008f34a6c.png)

**Comment by MartinJohns** [comment]
It's better to provide a minimal example of the issue you're facing. Your example is full of non-relevant code.

Here's a simplified example:

```typescript
class Base {
    doStuff = () => {}
}

class Derived extends Base {
    doStuff = () => super.doStuff();
}

new Derived().doStuff()
```

---

This is not a bug. See #11575.

**Comment by m-fire** [comment]
Omg, thanks for your quick reply. 

I was fixing it, and the advice like `Flashman moved me`😈. 
By the way, I don't quite understand why. 

Maybe that's why? 
Is it why it changed to ES5 because of tsconfig.json settings?
