### ISSUE TITLE
Proposal: `ArrayValue` type

### ISSUE THREAD

**Issue by avaly** [microsoft/TypeScript#49060]
# Suggestion

## 🔍 Search Terms

array type
array value
array value type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

An utility type to obtain an array's items type.

```ts
type Value = ArrayValue<T[]>; // T
```

## 📃 Motivating Example

TS 4.5 introduced the `Awaited` utility type for promises. This proposals adds an utility type with similar syntax for arrays.

## 💻 Use Cases

When building components for a list UI and need to use some API generated types (e.g. GraphQL generated types):

```ts
type Item = ArrayValue<GeneratedResponse['nodes']>;
```

Current workaround: using `Foo[number]`, but it's less readable.

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388:

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.

---

Personally I don't see much value, when it's trivially done using `T[number]` already.

```typescript
type ArrayType<T extends any[]> = T[number]
type Foo = ArrayType<number[]>
//   ^?
```
