### ISSUE TITLE
Unable to get property 'failedTypeParameterIndex' of undefined or null reference

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/TypeScript#4906]
Having this, this is the second time, I update prematurly to see if 1.6 fix the problem, apparently not.

I have this error:
7>VSTSC : tsc.js(14169, 21) JavaScript runtime error : Unable to get property 'failedTypeParameterIndex' of undefined or null reference

And not more... how I found my problem when I've got more than 200 files in editiion.
Actually, without finding the source of the pb, I lost hour to compare with my last shelve.

**Comment by danquirk** [comment]
Can you share the affected project with us (privately if necessary)?

**Comment by sebdoucet** [comment]
My bad, the tool version was not updated, it's working now.

Sorry for convenience.

**Comment by danquirk** [comment]
Happy to help ;)
