### ISSUE TITLE
Missing import in generated declaration file

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#49065]
# Bug Report

### 🔎 Search Terms

emitted generated declaration file .d.ts, cannot find name, symbol, TS2304

### 🕗 Version & Regression Information

Reproduces with TypeScript <=4.6 ~ 4.8.0-dev

Minimum repro: https://github.com/vilic/bug-repros/tree/typescript-generated-declaration-missing-import

>

### 🙁 Actual behavior

Emitted declaration file contains symbols not imported.

```ts
export declare const timestamp: {
    [timestampSymbol]: true;
//   ~~~~~~~~~~~~~~~ Cannot find name 'timestampSymbol'.
};
```

### 🙂 Expected behavior

Emits valid declaration file.

Might be related to the way I work around TS4023: instead of `{[uniqueSymbol]: ...}` I use `{[TKey in typeof uniqueSymbol]: ...}`.

**Comment by DanielRosenwasser** [comment]
> Might be related to the way I work around TS4023: instead of `{[uniqueSymbol]: ...}` I use `{[TKey in typeof uniqueSymbol]: ...}`.

Is there a reason for this? Are you using it in a union type?

**Comment by vilic** [comment]
@DanielRosenwasser You may try to change that part in the repro I provided into the `{[uniqueSymbol]: ...}` way, and it will result in TS4023. And I didn't find other ways to workaround that, including explicitly `import * as x from` or `import {uniqueSymbol} from`.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/970430/167926668-a2ca8e5f-72f2-4bf0-bb54-7f47fc6b84c7.png">

The real world case is here: https://github.com/vilic/x-value/blob/d7941a94150858bab4593c1d99c457d20c446b1c/src/library/utils.ts#L23

**Comment by vilic** [comment]
It seems that using `Record<typeof someSymbol, SomeType>` can avoid this problem.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/970430/168916095-c069fe18-def8-4997-a364-f50b0b294ad8.png">
