### ISSUE TITLE
Boolean extends its subtype when evaluated trough a generic.

### ISSUE THREAD

**Issue by jasa-blad** [microsoft/TypeScript#49073]
# Bug Report

### 🔎 Search Terms
conditional type, generic, boolean, extends.

### 🕗 Version & Regression Information
v3.3.3 to v4.6.2 & Nightly
Bug was discovered in R&D. 

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs

### ⏯ Playground Link
https://www.typescriptlang.org/play?ts=4.6.2#code/PTAEBUFMGcBdQJYFsAOAbSTIDtYENYEB7bAWAChYBPFSUAZQFdaAnAUQA9YcATaASVjQmAI2q0APBQbNILADTTR4yNMhde0JbJYUAfAF4KTVqHXdsfGWJqQA-NIBEAIQCqAcUcUAXI4DyANKOANwUFCCgzgCC9Pz0oABifgBKoACyAJqgAMIAMlH8aQB04WAA6gAWOKBwLHgIAOYV8ABmRCwA7ngsPGhUoDyQLQjYkDzyiPAI0KAAxu0skLOwfQOQ3CxII2OgsBUE3qWgIkREGHjYA0QwoNhE8Oa8uyyMkCWUtjl40JDOp+fYfi4HCEEjCC4IagGE5nSAXMwaSwzWAvOh2UAuDyOUDeDGBEJHUCgAB6DnIYXIEQAImw0n4AHL0cDJKLgfgM0B+BKRDzvCLORjwDpVS6QABueDQjAIOxRREYTVAeFADRwcgQs12VVAi2gjDQsCOPGuMzurTOaCIHS1dBg+BEaGmVR4oEtDQ17xUXx+f1hFwMJjknAsfEEwkYNkkMIB8hRrz0hJJZIpRxpdMZzNZ7PpnO54DYTNAAAVkn5smwqa5kmxQAA1KK5fhU-jgDKlAwdztd7s93t97sUL3Zb6QegokYNIEWUHYcHYSFUAy1CcIkMzRz0WizBDDWZjlgTxx2TGeXz40KUsBE0mDz7Dn5+EQAKyWsCnIOIs-oEKhRGfr9XTRQAAb2gLcdw1R8X2WXwMhgRwAF9jzcU9-CCC8ImvMkhxHelGCQEQ5HfXBPznBcDGwfDCJYQCkVAAAWAAmZCsTPdDExvckPlob1R3HbAGgMGRWGDTQw2UWwJGXAT5A3cDd33Q8E0vIkk1vHj70gKDXyEwN2ERUMhAkyQ-2g2B5FA+TIP-GDHDg6BEOUzC1O4uhNLwgi5ADHRRKRcSIxUCRKM8hQmKcq8XIpEBnDYJJq0iasogCfh6XcCAAAkUvcehSjYWdGEWLUDiVXZPmmOYwQQQZFhdWAiFol1IR+NAxTeUp7iqTppjoKh5VADoEDQNBQAqBVIFWR0tngPY6D2CcZloIh0DoWZ4WNfrIQqCrLEhT9JVdIh3VmUoLhdFAWD-PAHX6ERFjwABrG0tXm0BFuWka8FapU0Dunh+lmO7uB4d51LoRSBO-ecoWkhoGpmGHQHRRxsgWV9sVxRwgXmFhFmWAkVKw0HORs2BIfI0yAMeOiKeWRGMRRnG0ZxDEsdRvGMIizivQ86iyahYLqLh24qLkOnkbZ2B0YxEZsdxyWOdU0kgA

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
```ts
// Test implementation
type SuperExtendsItsSubtype<
 Super,
 Subtype
 extends
 Super
>=
Super extends Subtype?
 "BUG"
:"OK";

// BASIS FOR MY CLAIM.
// When straight forwardly defined, it is correctly determined that:
// boolean does not extend true.
type CaseBooleanIntentionsSanity=boolean extends true ? "BUG" : "OK";
//   ^?type CaseBooleanIntentionsSanity = "OK"


// DEMONSTRATION OF BUG.
// But when evaluated trough a generic the result
// does not follow the established logic.
type CaseBoolean=SuperExtendsItsSubtype<boolean,true>
//   ^?type CaseBoolean = "OK" | "BUG"



// DEMONSTRATION OF TEST PROCEDURE VALIDITY
//=========================================
type CaseStringIntentionsSanity=string extends "SpecificString"?"BUG":"OK";
//   ^?type CaseStringIntentionsSanity = "OK"
type CaseObjectIntentionsSanity=object extends {specificObject:"Yes"}?"BUG":"OK";
//   ^?type CaseObjectIntentionsSanity = "OK"
type CaseNumberIntentionsSanity=number extends 42?"BUG":"OK";
//   ^?type CaseNumberIntentionsSanity = "OK"

type CaseString= SuperExtendsItsSubtype<string,"SpecificString">
//   ^?type CaseString = "OK"
type CaseObject= SuperExtendsItsSubtype<object,{specificObject:"Yes"}>
//   ^?type CaseObject = "OK"
type CaseNumber=SuperExtendsItsSubtype<number,42>
//   ^?type CaseNumber = "OK"
```

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior
type CaseBoolean evaluated to "BUG" indicating that boolean was considered to extend true.
This doe not occur when evaluated directly as demonstrated in the code nor does it happen in
other types regardless of how they are evaluated. 

### 🙂 Expected behavior
type CaseBoolean should have evaluated to "OK" indicating that boolean does not extend true.
This would have complied with how other types are evaluated regardless of procedure and how boolean was evaluated when
directly typed.

**Comment by MartinJohns** [comment]
This is working as intended. `boolean` is a union type `true | false`, so distributiveness kicks in. See also: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

**Comment by jasa-blad** [comment]
Thank you so much!
