### ISSUE TITLE
Clause `extends from empty class` breaks type narrowing

### ISSUE THREAD

**Issue by mayakwd** [microsoft/TypeScript#49097]
# Bug Report

### 🔎 Search Terms

type narrowing
extends breaks narrowing 
empty class

### 🕗 Version & Regression Information

- This is the behavior in every version I tried starting from 3.3.3 to nightly builds.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220513#code/C4TwDgpgBAwgNgQwM5IDwBUB8UC8UB2EA7lABQB0lCATgOZIBcUAgtdQiKgviJgJS5s6ANwBYAFASAxohSwA9gFsw8wvmDMoAbyhgArgCM4ASylQETfHsUGI1XFAAMwqAF9pspAuWqI6gELauoYmZgZMSMDUxvi0DgDk8S7u4jLIXjBKKmrAMEH6RqZQUkwG8vJwENwOAGYIcEgQyR7pUACiyqCZPjnaKRIIBpHsUsDFnu3qxqDaElDz5kNRCKNQtBDAGJikUlm+6vDpTIcoW3xM6FAAPlB6+AAmEDUxEPdi4v2pEwCKenaclwgAA9gH57l42lMZnhIcBprxZuIFsFCmZ1mM-HC4RAkKRzlB0ABtAC6iORyOoGz01HwUBJ72RKU+AHpmQSABbGLygSBQLm3Rr3KDAeRQGryahSaASx72eQ1YXgaBSdkQKQAazFEqgAANYfDyOidVBFBt2fJ7hJgSpqGMedAABLIbrZTFbBw6dGoABKUGBoIeXiwpHtx08Pv4TG9zUkX1av3+-j0xjgsowfpBYIhUJADn1oGwWjmCwKoSg7OQqAAqttdj1MQB5ajoBC0MPpauRqAJ6ggJMptNOpAu-abGtQABkBMLUGL5KglOA1NpwE5XmQ3b+vf7qbsqCHI5yncn05cc7c59LRQMydTeKYPYBhfPFKpNIIxE3-y2eIZCyZEjSKokRQAAjluIAAIwOIQJCPjusp4uQFa4oemLMHwyHIKQaEBJhN4Dr+EjivYOzARiOZQPKYEQZB5CYtMxg4gIRZIgsDGgIaGw4XsOQYeQCAOJBf7zBxIBccAPH1nh5AGAkCBJOerJQEQErquuXjWmqoL3AANOYDxQEg5pEOutJ2NQ2qrggYwAG71H8fJeCoKDGEYuZ3I8zyEJabGiTmElSa6ByYWYeB1A0TQSCybLMPc9wxHEHRgF0vGYlABiUgg6mKpAXj4DQllEIlQH4CB4H-AATDBn7wbeiGYShpDJal0nAI12G4RoHWoWlMkEXefDvCRZC7GVFFYrm1EVb2lX0VCTFICx55iYFXX8YJeDCStAXokFo7+Ph8mKX5UDKQAcvIJBEMq1Q6kaBkgJysTkO0tn-MUfVjEgSgQCZGYBglsTtJ0IBdQQV3kDtk1rV9MChbU9SNO8rhAA)

### 💻 Code

```ts
type Class<T> = new (...args: Array<any>) => T;

class ComponentA { public a: number = 0; }
class ComponentB { public b: string = ''; }
class ComponentC { public c: boolean = false; }
class EmptyComponent {}

abstract class Entity {
    abstract get<T>(componentClass: Class<T>): T | undefined;
}

class Query<T extends Entity = Entity> {
    public get entities(): T[] {
        return [];
    }
}

// This type is used to force order of type check for `Entity.get` method
export type HasComponent<T> = { get<R extends T>(type: Class<R>): R; }

class QueryBuilder<T extends Entity = Entity> {
    public has<U>(componentOrTag: Class<U>): QueryBuilder<HasComponent<U> & T> { 
        return this as QueryBuilder<HasComponent<U> & T>; 
    }
    public build(): Query<T> {
        return new Query<T>();
    }
}

const query1 = new QueryBuilder().has(ComponentA).has(ComponentB).build();
for (const entity of query1.entities) {
    entity.get(ComponentA).a = 1;
    entity.get(ComponentB).b = 'a';
    // works as expected, and shows an error that object is possibly undefined
    entity.get(ComponentC).c = false;
}

// Adding EmptyComponent breaks types narrowing
const query2 = new QueryBuilder().has(EmptyComponent).has(ComponentA).has(ComponentB).build();
for (const entity of query2.entities) {
    entity.get(ComponentA).a = 1;
    entity.get(ComponentB).b = 'a';
    // Now we can `get` anyhing. Every component somehow extending EmptyComponent now, and I won't get message 'object is possibly undefined'
    entity.get(ComponentC).c = false;
}
```

### 🙁 Actual behavior

I'm trying to force type checks priority and kind of 'override' `Entity.get` method for the components that exist in the Entity to return defined value instead of undefined.

Error message `object is possibly undefined` is missing when you try to access a field of a component that is not defined. 
This happens when you add HasComponent<EmptyComponent> to the union type (QueryBuilder constructs that. 

### 🙂 Expected behavior

As the `ComponentC` or `ComponentA/B` not actually extends EmptyComponent I should get an error.

**Comment by MartinJohns** [comment]
> As the ComponentC or ComponentA/B not actually extends EmptyComponent I should get an error.

But they do extend it. Everything that the EmptyComponent defines is present in the ABC components.

See also: https://github.com/microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely

**Comment by mayakwd** [comment]
Oh, that's why. Well, I have to check FAQ first. Thank you.
