### ISSUE TITLE
Optimize `JSXSpreadAttribute` JS emit when it contains `ObjectLiteralExpression`

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#49099]
# Suggestion

## 🔍 Search Terms

jsx spread optimization babel

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code (not for most of them)
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I've noticed that TypeScript emits a different JS output for some cases involving `JSXSpreadAttribute` that contains `ObjectLiteralExpression` than Babel. It seems that Babel has decided to optimize some of the situations and tries to avoid emitting unnecessary `Object.assign` calls/spread assignments.

```ts
// input
<Test {...{ foo: "test", bar: 42}} />;

// TS output
React.createElement(Test, Object.assign({}, { foo: "test", bar: 42 }));

// Babel output
React.createElement(Test, { foo: "test", bar: 42 });
```

So perhaps TS could follow the suite here and avoid this `Object.assign` call. This would come with minor bundlesize and perf gains.

**Comment by RyanCavanaugh** [comment]
@weswigham any concerns? Seems fine to me to match Babel

**Comment by weswigham** [comment]
It's not a safe transform to make if a property in the object is named `__proto__`.

**Comment by Andarist** [comment]
Sure, stuff like this can be detected in the algorithm and we might skip this optimization if there is `__proto__` in the spread object. It seems though that Babel doesn't quite care about this and applies this optimization regardless of that (might be a bug in their code, maybe it's worth reporting there).

**Comment by weswigham** [comment]
I'd definitely call it a bug in their code - I'm ok skipping the call when we statically know it's definitely safe, but there are definitely cases where it isn't.
