### ISSUE TITLE
Type guard on `unknown` provides incorrect or "stale" editor hints

### ISSUE THREAD

**Issue by alii** [microsoft/TypeScript#49093]
# Bug Report

When using type guard on `unknown` to narrow down a type, we can safely make assertions about an object, but the type information does not carry down for editor hints.

### 🔎 Search Terms

type, guard, editor, hint, incorrect, inlay

### 🕗 Version & Regression Information

- Version 4.8.0-dev.20220512
- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220512#code/GYVwdgxgLglg9mABACwIYGcAKAnOAHAHh30QFMAPKUsAE3UXSmxjAHNEAfRMEAWwCNS2TgwCeAuABsAfAAoAUAEgAbqkkhSALkTgA1mDgB3MABoleXHm3E88gJTbV60ohj0ASqQhxsNIpZMdMH0jMGlEAG8lGGBEWShRPFI4WKcNRABCAF4sxAByOH4AKy8oPLtIpUVsUigQbCRgNXRSAG4lAF95aNjZDLTSCqjFatr6xua2zu7RuobECxIWRAH2rvkaL0lUGsRvMEZEKkZtPQNjdvkYuLQsS3jSRkCAImA4OGeKgDIvlAwbB6MAB0bzgL34O0+iB+R0SyVixygIPeQIhwhyuWe-HeklIqDAUKiiGJR0eSNBqJ27RJiAA9LTEAA9AD88nWQA)

### 💻 Code
```ts
function hasProp<Prop extends string | number | symbol>(
	value: unknown,
	prop: Prop
): value is Record<Prop, unknown> {
	if (typeof value !== 'object') {
		return false;
	}

	if (!value) {
		return false;
	}

	return prop in value;
}

declare const test: unknown;

if (hasProp(test, "foo") && hasProp(test.foo, "bar") && typeof test.foo.bar === "boolean") {
    test.foo.bar;
    // ^? — this is typed as Record<"foo", unknown> when we actually know more info than it is telling us
}
```

### 🙁 Actual behavior

When hovering over `test` or using the `// ^?` syntax, it's visible that `test` is of type `Record<'foo', unknown>`, when really we have already asserted that there is more type information there available to us `(e.g. `.foo.bar` which is a boolean)

### 🙂 Expected behavior

The correct shape would appear, e.g. 
```ts
const test: {foo: {bar: boolean}}
```

**Comment by AlfieRan** [comment]
IT APPEARS YOU NEED TECH SUPPORT, FOR QUICK HELP CALL: 999

**Comment by fatcerberus** [comment]
All three of `test`, `test.foo` and `test.foo.bar` are narrowed correctly.  The fact that `test` doesn't become `{ foo: { bar: boolean } }` is expected - in general once you've arrived at `Record<K, unknown>` (whatever `K` happens to be), you can't infer anything further about its value type just by checking its individual properties.

**Comment by alii** [comment]
Ahh right, that makes perfect sense, thank you very much!

This comment was very useful:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/25351731/168438846-64186adf-ae5d-40b1-af6d-8aa7f75c5e40.png">
