### ISSUE TITLE
Suggestion: Remove generated code from repo

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4909]
After seeing #4884, I'd like to ask about this. Having `diagnosticInformationMap.generated.ts` in the repo seems fine since it's part of the build, but since we want to check if for duplicate IDs we should consider incorporating the generation of the code into the standard build process, rather than a script run by hand as-needed.

The only downsides I can see are that editor intellisense for the Diagnostic object won't work after a clean clone until after a build or pre-build is run, and we'll lose the ability to simply run `tsc` over the compiler folder and get a functioning compiler (you have to generate the generated code first).

As far as upsides go, adopting this strategy should result in fewer merge conflicts in diagnostic messages and, additionally, will add a warning in the form of a failed build in a PRs when someone tries to add a message with an identical message id to one in master.

To do this, we should remove the generated code file from the repo, add the filename to the `.gitignore`, and make the script to rebuild it run as part of the build process.

Does anyone feel strongly about this?

**Comment by danquirk** [comment]
Since one other downside would be increased build time for ```tsc``` it's worth noting that ```jake generate-diagnostics``` today takes a negligible amount of time, < 1s.

**Comment by mhegazy** [comment]
sounds reasonable to me. we can give it a try and if we find missing the file affecting the productivity we can always put it back, though i doubt it.
