### ISSUE TITLE
https://github.com/microsoft/TypeScript/pull/45054 toI think the tests are fine (as long as you have long paths enabled in Windows - maybe we want to suggest that too?) because my original names were even longer and everything worked fine until I tried to add the new baselines to git.

### ISSUE THREAD

**Issue by Stan783** [microsoft/TypeScript#49092]
I think the tests are fine (as long as you have long paths enabled in Windows - maybe we want to suggest that too?) because my original names were even longer and everything worked fine until I tried to add the new baselines to git.

_Originally posted by @amcasey in https://github.com/microsoft/TypeScript/issues/45069#issuecomment-881587942_

**Comment by RyanCavanaugh** [comment]
What?
