### ISSUE TITLE
Intl.NumberFormatOptions is missing the RoundingType option

### ISSUE THREAD

**Issue by ncg777** [microsoft/TypeScript#49102]
# Bug Report
Hi,

According to the [specification](https://tc39.es/ecma402/#sec-intl.numberformat.prototype.format) and if my understanding is correct, the RoundingType is missing.

### 🔎 Search Terms
Possibly related to #36533

### 🕗 Version & Regression Information
I have no idea.

### 💻 Code

```
const n = 22
n.toLocaleString("en", {minimumFractionDigits:2, maximumFractionDigits: 2})
```
The specification mentions this about MinimumFractionDigits and MaximumFractionDigits:
_**These properties are only used when [[RoundingType]] is fractionDigits.**_

Therefore, my number is not zero-padded...

### 🙁 Actual behavior

I cannot specify a RoundingType

### 🙂 Expected behavior

I can specify a RoundingType.

**Comment by RyanCavanaugh** [comment]
The notation `[[RoundingType]]` means it's the result of an internal operation, not a user-facing property name that you can specify. Use-facing docs like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/resolvedOptions are generally better for understanding the allowed API surface.

**Comment by ncg777** [comment]
You are right.

I actually found the source of my problem elsewhere, but I had already
posted this bug.

Very sorry for wasting your time.
