### ISSUE TITLE
error TS2318: Cannot find global type 'BigInt'

### ISSUE THREAD

**Issue by h-joo** [microsoft/TypeScript#49101]
# Bug Report

The provided code fails with compiler error:  `error TS2318: Cannot find global type 'BigInt'.` without any location information.

### 🔎 Search Terms

BigInt, Object.freeze

### 🕗 Version & Regression Information

This changed between versions 4.6.4 and 4.7-beta

### ⏯ Playground Link

No playground reproduce for this bug as it's not possible to set target and lib differently from the playground.

### Steps to reproduce

```
mkdir test_47rc
cd test_47rc
npm init
npm install typescript@rc
echo "Object.freeze({foo() {}});" > index.ts
./node_modules/.bin/tsc --target es2020 --lib es2019 index.ts
```
Note : `./node_modules/.bin/tsc --target es2020 --lib es2020 index.ts` does not print an error.

### 💻 Code

```ts
Object.freeze({foo() {}});
```

### 🙁 Actual behavior

TypeScript compiler prints `error TS2318: Cannot find global type 'BigInt'.`  without any source location. 

### 🙂 Expected behavior

I'm not sure what the actual behavior here needs to be, but at least the new additioal type definition of `Object.freeze` in [lib.es5.d.ts](https://github.com/microsoft/TypeScript/blob/release-4.7/lib/lib.es5.d.ts#L233) start to trigger this failure.
```
    /**
     * Prevents the modification of existing property attributes and values, and prevents the addition of new properties.
     * @param o Object on which to lock the attributes.
     */
    freeze<T extends {[idx: string]: U | null | undefined | object}, U extends string | bigint | number | boolean | symbol>(o: T): Readonly<T>;
```
I think the `lib.es5.d.ts` should not contain type definition that uses `bigint`

Please let me know if this should go to https://github.com/microsoft/TypeScript-DOM-lib-generator/issues instead.

**Comment by fatcerberus** [comment]
> I think the lib.es5.d.ts should not contain type definition that uses bigint

That's a necessary evil afaik because all the later targets reference `lib.es5.d.ts` and the function definition can't be modified once it's been declared.

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh 4.7.1, 4.7.2, or 4.8.0?

**Comment by RyanCavanaugh** [comment]
4.7.2

**Comment by sandersn** [comment]
I think there's an error when the target is less than es2020 too, but errors resolving `BigInt` are suppressed when target is less than es2020.

This happens in `getContextualSignature`, which only runs on object literal methods. So it's an error for `{ f() { } }` and `{ f: function () { } }` but not for `{ f: () => { } }`.

**Comment by sandersn** [comment]
Broken by #33767

**Comment by sandersn** [comment]
I'm not sure what the right long-term fix is, but the short-term fix is to remove `bigint` from es5.d.ts.

**Comment by sandersn** [comment]
The current behaviour for `BigInt` is to fall back to `{}` when `interface BigInt` is not declared globally. Additionally, issue an error when target >= es2020.

Some better fixes:

1. Issue a new error when the lib is older than the target. (newer? different?).
2. Issue this error when target >= es2020 AND target === lib.
3. Issue this error when target >= es2020 AND lib >= es2020.
4. Issue this error when lib >= es2020.

(1) is probably separate from (2-4). I don't know what *should* be allowed here -- for example, as long as the emit for es2020 doesn't rely on es2015 stdlib declarations, it should be fine to have target=es2020 and lib=es5.
