### ISSUE TITLE
why -? operator not effect in this case

### ISSUE THREAD

**Issue by hangaoke1** [microsoft/TypeScript#49114]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ___latest___ and ___latest___
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
type OptionalKeys<T> = {
  [P in keyof T]: {} extends Pick<T, P> ? P : never
}[keyof T];

type PickOptional<T> = {
  [P in keyof Pick<T, OptionalKeys<T>>]-?: T[P]
}

type PickOptional2<T> = {
  [P in OptionalKeys<T>]-?: T[P]
}

type SelectConfig = {
    name: string;
    age?: string;
}

// { age: string }
type T0 = PickOptional<SelectConfig>

//  { age: string | undefined }
type T1 = PickOptional2<SelectConfig>

```

### 🙁 Actual behavior

new type  { age: string | undefined }

### 🙂 Expected behavior

new type  { age: string }

**Comment by somebody1234** [comment]
`OptionalKeys<T>` is not an object type and so it has no keys at all - meaning they can't possibly be optional. and so the `-?` can never apply. and without `-?`, `T[P]` is `string | undefined`

**Comment by hangaoke1** [comment]
in this case 
> ```ts
> keyof Pick<T, OptionalKeys<T>> === OptionalKeys<T>
> ```

**Comment by somebody1234** [comment]
Hmm... I guess `in keyof` is specialcased for [homomorphic mapped types](https://stackoverflow.com/questions/59790508/what-does-homomorphic-mapped-type-mean)
