### ISSUE TITLE
Typeguard not working if checked against Exclude

### ISSUE THREAD

**Issue by qwelias** [microsoft/TypeScript#49118]
# Bug Report

### 🔎 Search Terms
typeguard exclude union

### 🕗 Version & Regression Information
v4.6.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about typeguards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAgnUF4oG8CwAoKWoGMBcUADBtlAEYECMGAvlAD4onb5QCiAHjgDYCuAJhAA8AO14BbMhABOAGiIA+Zlg5VaGDDgD2IgM7AoAQ0Qo6h3VF4iA1iK0B3EUYtwYG9AEsAZlAAUhgDocKABCBCRCAEojAI4gA)

### 💻 Code

```ts
type AAA = {
    c: 0
    b: 1
} | {
    c: Exclude<number, 0>
    x: 1
}

const a = {} as unknown as AAA

if (a.c !== 0) a.x
```

### 🙁 Actual behavior
error
```
Property 'x' does not exist on type 'AAA'.
  Property 'x' does not exist on type '{ c: 0; b: 1; }'.
```

### 🙂 Expected behavior
no error

**Comment by MartinJohns** [comment]
The type `Exclude<number, 0>` is exactly the same type as `number`. It does not do what you think it does. There is no way to represent a type "any number, except 0" in TypeScript. This would first require #29317.

**Comment by qwelias** [comment]
thanks, tho it's been open for 3+yrs now...

**Comment by MartinJohns** [comment]
It's a fairly difficult issue to solve.
