### ISSUE TITLE
Template string expression statement leading with object literal gives incorrect emit

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4912]
Something like

``` TypeScript
`${ { hello: 10; world: 20 } }HELLO`
```

will get emitted as 

``` JavaScript
{ hello: 10; world: 20 } + "HELLO"
```

As an expresssion statement, the former evaluates to `"[object Object]HELLO"` while the latter evaluates to `NaN`.

This is because the former gets parsed as:

``` TypeScript
// block body
{
    hello: 10;
    world: 20;
};
"HELLO";
```

**Comment by DanielRosenwasser** [comment]
Note this also applies to arrow functions, function expressions, and class expressions.

**Comment by weswigham** [comment]
Interestingly, we also output _extra_ parenthesis when doing a destructuring assignment within a template expression:
```ts
let x,y;
`${ {x,y} = {x: 2, y: 3} }HELLO`
```
emits as:
```js
var x, y;
((_a = { x: 2, y: 3 }, x = _a.x, y = _a.y, _a)) + "HELLO";
var _a;
```
Additionally, the declaration of the temporary variable is placed after the expression - there's nothing expressly wrong with that, but it seems like bad form.

**Comment by DanielRosenwasser** [comment]
I might have a fix for this, so let's leave it assigned to me for now.

**Comment by anirudhrb** [comment]
Is this still open? If yes, I would like to attempt a fix. :)

**Comment by kitsonk** [comment]
It doesn't appear to be.

```ts
`${{ hello: 10, world: 20 }}HELLO`;
```

...emits...

```js
({ hello: 10, world: 20 } + "HELLO");
```

Both result in the same string of:

```
[object Object]HELLO
```

So ultimately this issue should be closed as the ES6+ behaviour matches the down-emit behaviour.
