### ISSUE TITLE
Optional round brackets for loops and conditional expressions

### ISSUE THREAD

**Issue by lukjoh** [microsoft/TypeScript#49140]
# Suggestion

## 🔍 Search Terms

optional brackets, options parentheses, brackets, parentheses, loops, conditionals

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I am proposing that round brackets be optional for loops (while, for) and conditional expressions (if/else, switch). 

## 📃 Motivating Example

Typescript code is full of conditional expressions and loops. Other languages like Go and Python allow these statements to be written without round brackets. 

Allowing round brackets to be optional in Typescript would make code visually cleaner and easier to type.

For example, the following if/else statement:
if (x > 0) {
}
else if (x > 0) {
}

...would become:
if x > 0 {
}
else if x < 0 {
}

Other examples include:
while i < 10 {
}
for let name of array {
}
for let i = 0; i < 10; i++ {
}
switch x {
}

**Comment by MartinJohns** [comment]
This is in the same realm as #42695.

**Comment by lukjoh** [comment]
> This is in the same realm as #42695.

Hi Martin, I read your comment in the other post where you mention that changes should be valid JS, however my interpretation of the Typescript design goals is different.

Much of the Typescript syntax is not valid Javascript (including type annotations and imports without a .js extension). Typescript doesn't run in the browser as is. The compilation step is adding and removing text.

My interpretation of what should not be introduced is new syntax like (for example) Python array slicing "array[0:2]".

Are optional brackets really a violation of the Typescript design goals?

**Comment by MartinJohns** [comment]
> Much of the Typescript syntax is not valid Javascript (including type annotations and imports without a .js extension).

Imports without a js extensions are valid JavaScript. Types are exactly that what TypeScript aims to add: compile time type information. It's completely removed during compilation. It's not new JavaScript syntax.

> My interpretation of what should not be introduced is new syntax like (for example) Python array slicing "array[0:2]".

It's still new syntax. The compiler now suddenly needs to emit different JavaScript, depending on the expression.

> Are optional brackets really a violation of the Typescript design goals?

I'm not a member of the TypeScript team, so I can't say it. But yes, **definitely**.

**Comment by jcalz** [comment]
The checkbox for

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

should be unchecked.

**Comment by lukjoh** [comment]
Ok.
Do I close this issue?
