### ISSUE TITLE
Object.freeze overloads force the type to be recognized as an array (by the order of overloads)

### ISSUE THREAD

**Issue by aghArdeshir** [microsoft/TypeScript#49149]
# lib Update Request

## Configuration Check

My compilation *target* is `es5` and my *lib* is `["dom", "dom.iterable", "esnext"]`.
(Which I believe does not matter in this context as the definition of `freeze` is inside `lib.es5.d.ts` solely.)

## Missing / Incorrect Definition

`Object.freeze`
![image](https://user-images.githubusercontent.com/5755214/168795010-31b41fc1-6af9-481e-a7d3-39f9ec467cdf.png)
It is defined in a way that in IDEs it is always supposed the input is an array.
![image](https://user-images.githubusercontent.com/5755214/168795175-36f48727-7f6a-42f1-8778-e6704d9c4426.png)

## Sample Code

```ts
Object.freeze<{someKey: 'someValue'}>({/* the problem is with autocomplete here (in IDEs) */});
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

---

I believe the overload that forces arrays is defined in this PR:
https://github.com/microsoft/TypeScript/pull/12434/files

And I believe just removing it will suffice (and the user of Object.freeze needs to specify its an array in case its an array)

---

If it is confirmed, I would be happy to create the PR for it.

**Comment by Josh-Cena** [comment]
That seems to be an unusual development workflow though. Most of the time you only need to specify `Object.freeze({ someKey: "someValue" })` without duplicating the type argument.

**Comment by aghArdeshir** [comment]
@Josh-Cena I have a `SocialNetwork` type:
```ts
type SocialNetwork = { name: string ; url: string; }
```

I need this type to be a kinda centric type and reusable. So in different places I can have different functions that produce this structure:

```ts
function getFacebook() {
  return Object.freeze<SocialNetwork>({});
}
```

when I write the function above, I expect my IDE to help me completing the object with suggesting required keywords. And later: 

```ts
function getFacebook() {
  return Object.freeze<SocialNetwork>({name: 'Facebook', url: 'https://facebook.com/my-page' });
}
```

when I already have function above, I want any change in future to the actual `SocialNetwork` type, trigger errors all over the place, so I can easily refactor my code (e.g. change `url` -> `URL`) or add new keys and immediately know where to change (e.g. add a new key: `displayName: 'My Page'`)

**Comment by Josh-Cena** [comment]
I see. That makes sense.

**Comment by MartinJohns** [comment]
When you use an explicit type annotation you get much better support:

```typescript
function getFacebookExplicit(): Readonly<SocialNetwork> {
  return Object.freeze({  });
}

function getFacebookInferred() {
  return Object.freeze<SocialNetwork>({ });
}
```
![image](https://user-images.githubusercontent.com/5269069/168813303-594681f7-b20b-43ad-aba7-16ad85d1bcc8.png)
instead of
![image](https://user-images.githubusercontent.com/5269069/168813349-4014c04a-b716-405f-abf0-cf78fa6b714d.png)

![image](https://user-images.githubusercontent.com/5269069/168813406-ddc58b1d-6e1e-4b35-9f7f-6f665bb37e9c.png)
instead of
![image](https://user-images.githubusercontent.com/5269069/168813445-32010346-fda8-4419-afd3-94987cd2e753.png)

**Comment by aghArdeshir** [comment]
@MartinJohns thanks :+1:  That's actually very good. I agree with most parts.

Actually note that: 
![image](https://user-images.githubusercontent.com/5755214/168821090-64627575-c59d-4323-af7c-85eca58e73fc.png)

In the above screenshot you attached, the `url` is not autocompleted, IDE cannot suggest keys of the objects you pass into Object.freeze:
![image](https://user-images.githubusercontent.com/5755214/168821163-26749c47-66e6-4985-8517-99fa77147c72.png)

Also, from clean-code point of view and architecture point-of-view what you say is basically right, but the `getFacebook` is just an example.

The reason I opened this issue is to solve more complicated problems, e.g.: 
```ts
type SocialNetwork = {
  url: string;
};

type CommonProfileHandle = {
  handle: string;
};

function getSocial(): SocialNetwork | CommonProfileHandle | null {
  if (someConditionIsCorrect) {
    return Object.freeze({
      /* here it is not deterministic */
    });
  } else if (someOtherConditionIsCorrect) {
    return Object.freeze({
      /* here it is not deterministic */
    });
  }

  return null;
}
```

**Comment by andrewbranch** [comment]
I think it probably makes sense to move overloads with no constraints on the type parameter after overloads that do have constraints. But even then, you can’t disambiguate a call with explicit type arguments between `freeze<T>(o: T): Readonly<T>` and `freeze<T>(a: T[]): readonly T[]`. This is a general limitation of overloads.

Accepting a PR so we can try this out and run extended tests to see if real-world usage breaks. No guarantee it will be mergeable.

**Comment by aghArdeshir** [comment]
Thanks @andrewbranch . Great news. I'm on it then 😀

**Comment by andrewbranch** [comment]
> And I believe just removing it will suffice (and the user of Object.freeze needs to specify its an array in case its an array)

I missed this part of the suggestion by the way, but unless I’m missing something, I think you’re right. The array-to-readonly-array overload seems unnecessary, as it’s covered by `freeze<T>(o: T): Readonly<T>`.

**Comment by nicolas377** [comment]
Running [some playground tests](https://www.typescriptlang.org/play?#code/PQKhCgAIUgFAnApgN0QOwC4GdIYBaKQC2A9gCYCWAZhQMYCGGFJakJVkiAHhVk2gHNIAB3glhieBgCekRhngUARgFcMiHPTRlIyegBsVGgDRztIpKkw58hemUpMWbDmkQB3C+MlMNAOigYAAFhenh6IjZIAHklACtEWgw2Vnc8OjxcEkh9EloAa1wCOQwFZTV-QOBwMkT9MMIqFTQk5lYqJEQAL0QAHgAVTi51bRwAMWbWlgA+AAoqAC5IfoBKJf6AbnBwUAhoOEt0bCLCUkoaBidWdiHefiFRbylZeUVVdU1zPUMTMx1RFBHGzFeyONouSBuTyPCRSCiVfYhMIRKKxBJJFKQNIZLI5PKFWwlMrvBEgaq1Wj1JCQJotK40zo9AZzEjrNaQABKiHsLH00mZW3AtBYfAZJB6aAAgvBwrIALwMxDdRCzADaAF0VltgMBIHrIAA9AD84CAA) shows that real world usage shouldn't break. I'll open a PR so the TS team can test further.
