### ISSUE TITLE
switch doesn't narrow object property for passing as function parameter

### ISSUE THREAD

**Issue by awinograd** [microsoft/TypeScript#49153]
# Bug Report

### 🔎 Search Terms

narrow switch, discriminate switch, refine switch

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type discrimination & narrowing in switches.

crashes  on 3.5.x and above. Before this I couldn't run the playground because `as const` wasn't available. However, similar behavior happens when using enums (will include 2nd playground)

### ⏯ Playground Link

[Playground link with relevant code using as const](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wNIEtkBM4C8cA3gFBxwBiA8tQFxwDkN1jANOXAEICCASg0a8+7UgF84AQ1SIU6ANylQkWHBgBPMMDjY8hNZuAQAZjpy4A2gGtg6kwa33duALqLSGrVQgR9xOFbmDJ5Gps4AdCxwYooh3JJQfgFBDqFmeOHC0e7GAK7ICDBYKHCgMFCShZQ+ABQQAEYAVgzVEACUDOhQOADmJJwUUMAwuVDITMY+jIpipKR5BUUlZRWFXAl1TQzrUB1wXb39FIPDo+OM9QnT4nMLhcXjALaSODVtRxRIaPAJUAw8UAq6gAPP5AngGM5ogA+fQWNxzY5fdBwABukgANrlgDIiL9ws8wDUsDBgI9CLCyMdqagAO4khAACzgxNJj3C4Nw7yp1N5iGk2giLAYPL5YuR8E5wUMTnMFmYtEYLn0JLJHPMijFWqGIzGpRA5UqMFarLJbU1Woos0tnwF6VwmX4IoGNpOuvGKyNO1Nj3NLrF1r5geibXEQA)
[Playground link with relevant code using enum](https://www.typescriptlang.org/play?ts=3.3.3#code/KYDwDg9gTgLgBMAdgVwLZwNIEtEBM4DeAUHHAGIDyFcAvHAOSUX0A0JcAQgIIBKtD3HqyIBfANxEiMAJ5hg5CBH4E4Aaxy4AXJg0A6JnHFTZ8jgEMoytRu3Y8uwYYlEAZskQBjGFgiIEIGCgzLzJFAAoIACMAK21QiABKbQBnQJwAc0J2UihgGGQoP3oXRXoJEUk3T29ff0DgmHMoCJjtJqS4VKgMrNIcvIKiyIsy0Ur3Lx8-VDMcMITe0g9fVLgLKG0uKCDpAB4VdTxbDUMAPn4AbQBdZz7lxFWANzMAG2RgZP513RmwMKwYMB0DRzsQ+uDkgB3AEeAAWcH+gNQukOuAWYPBmLgHjMyXkdlw+io2gxWLJuXyhTqQRC4QBQISEjJ4IqzLuuPxekEJOybL6FMG1IaTURDKZfNZWMlhgSoiAA)

### 💻 Code

```ts
export const Kind = {
  FOO: 'FOO',
  BAR: 'BAR',
} as const;
export type Kind = typeof Kind[keyof typeof Kind];

type Foo = { kind: typeof Kind.FOO };
type Bar = { kind: typeof Kind.BAR };

function extractFoo(obj: Foo): string {
    return 'foo';
}

function extractBar(obj: Bar): string {
    return 'bar';
}

function main() {
   const arr: Array<{ kind: Kind }> = [];

   const values = arr.map(item => {
       switch (item.kind) {
           case Kind.FOO: {
               const kind: typeof Kind['FOO'] = item.kind; // no error
               return extractFoo(item); // error
           }
           case Kind.BAR: {
               return extractBar(item); // error
           }
       }
   })
}
```

### 🙁 Actual behavior

Error on extractFoo & extractBar
```
Types of property 'kind' are incompatible.
    Type 'Kind' is not assignable to type '"FOO"'.
      Type '"BAR"' is not assignable to type '"FOO"'
```

### 🙂 Expected behavior

`item` should be a valid parameter to extractFoo/extractBar because the `kind` property should be narrowed/refined by the switch statement.

**Comment by jcalz** [comment]
This is working as intended: `item` is not of a discriminated union type (it's not of a union type at all), so checking `item.kind` only narrows the type of `item.kind` itself; it does not narrow the type of `item`.  See #31755.  There is also an open feature request at #42384 asking for this sort of behavior.

**Comment by whzx5byb** [comment]
As @jcalz says, you must make your array item type a discriminated union: `{ kind: 'Foo' } | { kind: 'Bar' }`, instead of `{ kind: 'Foo' | 'Bar' }`.

A workaround could be:
```diff
export const Kind = {
  FOO: 'FOO',
  BAR: 'BAR',
} as const;
export type Kind = typeof Kind[keyof typeof Kind];

type Foo = { kind: typeof Kind.FOO };
type Bar = { kind: typeof Kind.BAR };

function extractFoo(obj: Foo): string {
    return 'foo';
}

function extractBar(obj: Bar): string {
    return 'bar';
}

function main() {
-   const arr: Array<{ kind: Kind }> = [];
+   const arr: Array<Kind extends infer U ? U extends unknown ? { kind: U } : never : never> = [];


   const values = arr.map(item => {
       switch (item.kind) {
           case Kind.FOO: {
               const kind: typeof Kind['FOO'] = item.kind; // no error
               return extractFoo(item); // no error!
           }
           case Kind.BAR: {
               return extractBar(item); // no error!
           }
       }
   })
}
```

**Comment by awinograd** [comment]
Thanks to you both for pointing me in the right direction. I guess I need to work on my "GH issue"-foo.
