### ISSUE TITLE
Incorrect type narrowing in function when taking an union of string values for a string argument

### ISSUE THREAD

**Issue by romain20100** [microsoft/TypeScript#49166]
# Bug Report

A function taking a string argument and returning whether this argument is of a specific set of string values,
returns incorrect type narrowing when the value passed to the function is not exactly string but a type extending string instead.

### 🔎 Search Terms

I searched "string", "narrow" but...
I could not figure out relevant search terms for what is probably a more general problem that I don't know how to name.

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I just happened to write this today.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEElQCwQwNwKagHYHtQGNXIC4CdUAbUVRPUHKJAB1QGc6BLAI0KThkIFcE6SAzUAHECXagFgAUDgCe1JCNRjQAXlAAiGOtAAfDc2171GQxoDCp9QBNLCSwFF1UkKABCXHBFABrNAHdQOlQAW3ZOHj4YPCRGXARouhxYgHMKdFDnMCCKKmjQRkjkfLi8OgQMJOxQZgQcPwQEIsVlGGQrUDMYHARk1DwZKUauYI6unr6ZUABvKVA50ABBVQ0tABpZ+ddl9QN1yXmO7ZMpAF8pKX4uZArGKoLO7t7+gAo6AC5A-BSASg++AtGjwm0w2c2iOC4eCKAHlmAArco4AB0HG4vAAPIk8CkAHzPB7jfrfJGxDDcKy8V7fU7nSQuISMRBFGCYeI4GCxUDJUTUUConirLx+JSEdqERjeJA4dBcMr5TyMQSMBWRPmcRjtAlPAZ0sB9UD8TiEZgwDDeNKgFnJRrxRgYQGEmRIzJuDw5AEAoKhPywTzBPpILDBajijBjdqUVqgBAAD3kFQQVikWGQiS5PI+zV5ah2TkkLoAcuh4gRyLkEILmG7KB6+BT+LFaghCJM-ARkMkXbJ5HQMNjqJ4w8gAOSebqEYhZ-KRQjZLEpQWtCNQWLePiUeJIPyMCcoBBkapIGAusNyn2b9NKXkA1CCbtILUTZPYNPJLhRVrdROP-oARmW9xjNqzzcle3ygAA-JeygfD+ToLC6b4fnE35ARMv6wWh-RIgh+a6qAAAqK51qgvAoKgnhUIQEiSCmr7vngn4NFYcEAEwAXQcEgTylp8POHbgVBoEwQ62o4YhDFMahQL9KxHy5rookTOJeEuO4Y7EaAVikXQzr4QAEqg9QHhu0YxvgLIUmSH6VEUiQILyZQIMEfDREakyoFYVh6XRnjCdQADK+B-F8HbLP5z6pn5kkoSxWEyAAzBxXH+UFeCCdBgX4KAmEyfBEnIV+cV5QluWOlIQA)

### 💻 Code

```ts
// I have no control over the possible values of Group
type Group = "a" | "b" | "c" | "C" | "d" | "e" | "E"
// But I know some values are interesting to me
// so there is an intersection between Group and Category
enum Category {
    A = "a",
    B = "b",
    C = "c"
}

function isCategory(s: string): s is Category {
    return Object.values<string>(Category).includes(s)
}

// Given a certain group value, I would like to use it if it is a valid Category
// or fallback to a generic Category.
// But this is somewhat more complicated than expected
const group: Group = "b"

// No error here, but this is definetely wrong
// typescript can't tell Group is also string, and thinks there will never be a
// case where group is of type Category
const guaranteedCategory1 = isCategory(group) ? group : Category.A
// guaranteedCategory1: Category.A

// This does not help
const guaranteedCategory2 = isCategory(group as string) ? group : Category.A
// guaranteedCategory2: "b" | Category.A

// But this does.
// However the extra declaration step seems really odd.
const groupStr: string = group
const guaranteedCategory3 = isCategory(groupStr) ? groupStr : Category.A
// guaranteedCategory3: Category
```

### 🙁 Actual behavior

`group` is not generalized as a string when passed to the function `isCategory`.
Hence the resulting type narrowing is wrong.

### 🙂 Expected behavior

`group` is a string union and it should be properly interpreted as a string when passed to a function accepting a string as argument.

It may not be a major issue, but I think it's problematic that you won't see an issue if you don't double check yourself, because there is no "type error".
I happened to immediately check the type and see it was wrong.

**Comment by MartinJohns** [comment]
> // typescript can't tell Group is also string, and thinks there will never be a
> // case where group is of type Category

TypeScript can tell the only value ever assigned is `"b"`, which is a valid `Category`. You can avoid this type of narrowing by using a type assertion: `const group = "b" as Group;`

**Comment by RyanCavanaugh** [comment]
This is the correct behavior because `isCategory` is an incorrect type guard. `"b"` is *not* a `Category` because `Category` is a subtype of string. Only `Category.B` is a `Category`, so it's incorrect for `isCategory` to say it can narrow to `is Category` (in reality, there's no way for this to be written correctly).

The non-enum equivalent works as expected because it doesn't suffer the same misapprehension:
```ts
const Category = {
    A: "a",
    B: "b",
    C: "c"
} as const;
type Category = (typeof Category)[keyof typeof Category];
```

**Comment by forivall** [comment]
Also, `const enum` will treat strings as the same as the enum value, such as
```ts
const enum Category {
    A = "a",
    B = "b",
    C = "c"
}
```
but not all environments support const enums (such as babel)

You can also use this [`LiteralToEnum`](https://gist.github.com/forivall/8968ec4ef450ceac9949b3a25583ca6d) as follows:
```ts
const toCategory = literalToEnum(Category);
const groupCat = toCategory(group);
const guaranteedCategory4 = isCategory(groupCat) ? groupCat : Category.A
```
[Playground Link](https://www.typescriptlang.org/play?#code/PTAEElQCwQwNwKagHYHtQGNXIC4CdUAbUVRPUHKJAB1QGc6BLAI0KThkIFcE6SAzUAHECXagFgAUDgCe1JCNRjQAXlAAiGOtAAfDc2171GQxoDCp9QBNLCSwFF1UkKABCXHBFABrNAHdQOlQAW3ZOHj4YPCRGXARouhxYgHMKdFDnMCCKKmjQRkjkfLi8OgQMJOxQZgQcPwQEIsVlGGQrUDMYHARk1DwZKUauYI6unr6ZUABvKVA50ABBVQ0tABpZ+ddl9QN1yXmO7ZMpAF8pKVl5UAA1cIQAeX4AHgAVAD5ll4BtbwQZVEELwAugBuc6SBAAD1oeE8WGQiVAhEY3TwnBeqHsyGGyyeWJxUO6bT4ACVyn0rE9EngUqtAvgUroUMMang3m8ABQbFy8ZG4AC0VgKMFYCH5yEJ-L5SAAApdeBgadQcPzebEcMA0PyuNiylZ+RxShshsF3DgAFJcRIAMT6LzkKQAXKB8cEpABKVQfJ6dNqMKxjUCExpWPiugAyKPi6LkCDx2OC7I5cGdvqFAe6npUbw2ydAMD41JSnoLoEjqPRmIT8eGdLT-rGbzBkkG0L6nnlZajaMIGNdTw2rqDkKJodAZKweEpReQyTpM9SegTrLeezmLyiyVqw9HhYZs6Zy-iUg+agACgl4ogAKrIYJdDBUSkbW7cB7PKagL4AaWKPj+AIugmQLOgAsg+UD9hueBbjgdKuj+QIfCcq4bNBsEns2UIwh2sZdhWhALHQ-aDgmr48DuIZ7jSB5Liy8RrqA6HbsGxL0jRi7MsErInssF68FeCC3veOCPggz77EBwzkUgrFjq0kwAPygOBomQdWzFwVJwQyR8zoSmQjGaZhFx4apj4kZJ9YZrJI5UexjJ0dxDFoZuLF2WxC6HvReC8Wo1mBnJhQDJJymfgADPpCBkCCoAAIzOl8AXdHSmlAqAJxfJplFsclSDKXFoDOuFQIbFFMWmVc-FlHgN53hB4mvDlY5fApdIKUCdLXqeoDXs1fDfCVoDKd8cXpc617Np2EbdjG8h4v147klOVL7nODm0VxK49TJjwDpJn4-n+vz-II9ggaAADq-qNAAymtAByPl4ohyEmdIeHXVYd2Pc97yfItC4bMpQOSc6LyLUevmhVtx5gyg0XxM2Uj8DqFSMFUBSdN0vT9BydDOgu7qE-kfDY+M-TTBsczRDgXB4EU9zMAAVuUOAAHQcG+dCrRxnLk7jMjuuzsQYNw310Pj7qnFI8KIjgqACxMyzIgRfYJhySv9O6yOSC4QiMIgRQwJg8Q4DAsSgMkojUKAXM8HSkB+EohDtMivxpKAVoxJ4jCCCipP5nbnD+qMOMTJkJDkPwnCEMwMAYN4nsm1uEo0hgYcUzI7OR2aOQFIHQShH4sCeMEfRIFgwTUMiGBjO0lCtMO8gVOJsvYIi1tKNQzrNLbag7E4LZ62AD3oPEBDkLkCB0swHj53wBfffwsS1AghCTH4BCzpH8p0IqjDKpgrQAOQduvxB94HnDZAu7VtPnyDeHwlDxEgfiMIQxAGfE1RIDAkc65lFACXN+VsbaB0Ap2LWIU5aeGSFwKIrRujiRgYVNQWMxiCw5F3MQnplK4NtqmLBEx2YLEjggpBcRUEkP6AlTOgsyHghcC8KAS9UC8BQKgTwVBCASEkHAq2iC0TUKsDAgATMsTB4c8aEPzNRYsw1wHdyKgw0h5CR5CKoSgsRtCZDiOdIPJkMCmHDxcHnSg7DeA500QACVQPUMgORbL4BNt9MWSDKhFESAgW2ZQEDBD4NEWOkxUBWCsDYwRhD7p4EJmtZYhD24IngcI5BDRdEyJkAAZikXQGBOCbYxPwcosQMTVEmI0S4ShIidEwKycQzJzCwCsILs7PAz8kmdxttjZYCt8mEJ1p0lJ2j0kwIACy5P6d0roxTCE9IaVnUxQA)

**Comment by romain20100** [comment]
@RyanCavanaugh  I see, the type guard is not correct.
And typescript (preemptively?) concludes that "b" cannot possibly be Category.

However, if group is not over simplified in the example context, then example 1 works.

[Updated playground][1]

And then, the code works, while it should not?

It's hard for me to fully grasp how strict enums really are.
I see them as useful aliases that cannot be easily used interchangeably.
But I would have thought `isCategory` would either work or trigger some kind of type error (type incompatibility or similar).

I have solved my problem entirely differently since then, so I don't need a solution.
The issue could be closed, I guess.
Thanks for your answer.


[1]: https://www.typescriptlang.org/play?#code/C4TwDgpgBA4gTgewK5igXigIgIaagHywCM9DMBjUrAYSswBM6I6BRTAWACguIA7JALZRq2YBADmCOCCgBvLlEVQAguiy4ANAqUAhNZhJbOS4fspcAvlwBmSXuWABLBLyiOAziLGTpACncAXFDuwHCOvOIAlEHubrFeElIy8sZKcBDASHCuAPJEAFYQDgB0AG7YADZIEO4APCFhEQB8vgk+IJHF4eRV9DX+kZZcXAD0I7AZUNhQcNi89AhC8Mio5VXQwAhQYOmlfMBQCHtwwY4CYBWO1o7kos6uCNZQoJDuXOQuIVDiiCiBsL8wABtAC6aiBOEwGmIUKwlGhmFoCMYCOYCLYIPenwOPxWQWWKDUuL+QIAsqIABbFawVBBSXzk4BU2bzRa+SJQABU30B7mKFT44iZkUx3E4Yx5eIBKyggFByLG8L7iJDYFliCD0NpJACMag8Wr8xLAHIA-JLCUEDSBispRuNlaq5urNaJEtJtZbXe05VBfAgANbQ3gIADubgOIak-r5xWKgzFEoAklBg2JnhTRObUB4U6HnuANVN-gTUIQrVBAHwbgApdu1QFh7VxXKDJ8STEMUkDQxwHdwQCACWLpSoVGQhiCOOD0YrDTgfRU4lVqvsu7xJABMes8XqSviNReCoXCUSgZr3ntX0httYdS41VrX+MBBGE2+ktYAKhSc+l3EgKgccwEDwBWwegjygIgimwJBe0OJ4KTzPccxeQt3G6aBsGsMQTkuXhoG1AB2Gc5yVQEAGVQhiQ8IiJQEFSVRcnWXK0AGZNytXdyNCU0swok5zzda1bXFe1GN4Z1WIE71ZV9EJHAqCpDn9eMgA

**Comment by fatcerberus** [comment]
> But I would have thought isCategory would either work or trigger some kind of type error (type incompatibility or similar).

UDTGs aren't checked, as generally the reason you're writing one is because the type system *can't* natively check the type in question.  That said, it'd be nice for the compiler to tell you that a particular UDTG is always going to result in `never` types, based on the type given as input (as in this case--`string` and `Category` have no overlap).
