### ISSUE TITLE
.js and .d.ts files are no longer included in out-folder after 4.4.4

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [microsoft/TypeScript#49163]
# Bug Report

Previously .js and .d.ts very included in the out-folder, they are not anymore after 4.4.4.

### 🔎 Search Terms

js, d.ts, javascript, declaration

### 🕗 Version & Regression Information

Last version it worked was 4.4.4, since then it doesn't. Does not work on nightly version.

This changed between versions 4.4.4 and 4.5.0 (probably, I can only test from 4.5.2 again)

### ⏯ Playground Link

Create a test repo just for this:
https://github.com/MajorMeerkatThe3rd/TSTest

### 🙁 Actual behavior

.js and .d.ts files are not included

### 🙂 Expected behavior

.js and .d.ts files are included

**Comment by RyanCavanaugh** [comment]
Your tsconfig picks up both the inputs and outputs of the build. We made an intentional change to exclude any file if it was the output of another file.
