### ISSUE TITLE
Support for ES5 class patterns

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#4916]
Many libraries have functions like `React.createClass` which create classes that are "subclasses" of some main abstract class from that library. Although React now has ES6 class support, for other libraries we aren't that fortunate. It would be awesome to have some way to use these functions in a type safe way. This might come pretty close to being solved by #3694, but I don't think it will completely work:

```typescript
interface ClassSpec<Instance> { [name: string]: ()<this: Instance> => any }
declare function createClass <Instance extends ClassSpec<Instance>>(spec: Instance); // Recursive type parameters don't work

**Comment by kitsonk** [comment]
Actually, I think you can do it.  In 1.6 it is [possible](http://www.typescriptlang.org/Playground#src=interface%20GenericClass%3CT%3E%20%7B%0D%0A%09new%20(...args%3A%20any%5B%5D)%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Afunction%20createClass%3CA%2C%20B%3E(baseClass%3A%20GenericClass%3CA%3E%2C%20extensionClass%3A%20GenericClass%3CB%3E)%3A%20GenericClass%3CA%26B%3E%3B%0D%0Afunction%20createClass(baseClass%3A%20GenericClass%3Cany%3E%2C%20extensionClass%3A%20GenericClass%3Cany%3E)%3A%20GenericClass%3Cany%3E%20%7B%0D%0A%09%2F*%20do%20mixin%20*%2F%0D%0A%09return%20baseClass%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Foo%20%7B%0D%0A%09foo%3A%20string%20%3D%20'bar'%3B%0D%0A%7D%0D%0A%0D%0Aclass%20Bar%20%7B%0D%0A%09bar%3A%20number%20%3D%201%3B%0D%0A%7D%0D%0A%0D%0Alet%20FooBar%20%3D%20createClass(Foo%2C%20Bar)%3B%0D%0A%0D%0Alet%20foobar%20%3D%20new%20FooBar()%3B%0D%0A%0D%0Afoobar.bar%20%3D%202%3B%0D%0A) to infer and intersect that types:

```typescript
interface GenericClass<T> {
	new (...args: any[]): T;
}

function createClass<A, B>(baseClass: GenericClass<A>, extensionClass: GenericClass<B>): GenericClass<A&B>;
function createClass(baseClass: GenericClass<any>, extensionClass: GenericClass<any>): GenericClass<any> {
	/* do mixin */
	return baseClass;
}

class Foo {
	foo: string = 'bar';
}

class Bar {
	bar: number = 1;
}

let FooBar = createClass(Foo, Bar);

let foobar = new FooBar();

foobar.bar = 2;
```

**Comment by Gaelan** [comment]
@kitsonk That's a slightly different problem than the one I'm facing.my problem is that many libraries designed for ES5 require you to say `var Person = SomeORM.createClass({...})` instead of `class Person extends SomeORM.Model {...}`. TS supports the latter, but not the former.

**Comment by kitsonk** [comment]
Ok, I guess why wouldn't [this work](http://www.typescriptlang.org/Playground#src=interface%20GenericClass%3CT%3E%20%7B%0D%0A%20%20%20%20new%20(...args%3A%20any%5B%5D)%3A%20T%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20CreateClass%20%7B%0D%0A%09%3CT%3E(proto%3A%20T)%3A%20GenericClass%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20var%20createClass%3A%20CreateClass%3B%0D%0A%0D%0Alet%20Foo%20%3D%20createClass(%7B%20foo%3A%20'bar'%20%7D)%3B%0D%0A%0D%0Alet%20myFoo%20%3D%20new%20Foo()%3B%0D%0A%0D%0AmyFoo.foo%20%3D%20'bar'%3B%0D%0A)?

```typescript
interface GenericClass<T> {
    new (...args: any[]): T;
}

interface CreateClass {
	<T>(proto: T): GenericClass<T>;
}

declare var createClass: CreateClass;

let Foo = createClass({ foo: 'bar' });

let myFoo = new Foo();

myFoo.foo = 'bar';
```

**Comment by DanielRosenwasser** [comment]
Really what would help here is being able to return the value of `this`, which has a pull request out and is slated for TypScript 1.8 (the next version).

**Comment by Gaelan** [comment]
Come to think of it, this is completely solved by `this` typing. Yay!

P.S. Why is TS 1.7 going the way of Windows 9?

**Comment by danquirk** [comment]
It's running around in a sunny field somewhere with TypeScript 1.2 :wink:

**Comment by mhegazy** [comment]
based on popular demand 1.7 is back... :D
