### ISSUE TITLE
Mis-identification of Incompatible Function Signature Overload for Variadic Overload

### ISSUE THREAD

**Issue by jjorissen52** [microsoft/TypeScript#49170]
# Bug Report

### 🔎 Search Terms
`This overload signature is not compatible with its implementation signature.` 

### 🕗 Version & Regression Information

- ~This is a crash~
- ~This changed between versions ______ and _______~
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about overloads.
- ~I was unable to test this on prior versions because _______~

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.2&ssl=23&ssc=2&pln=1&pc=1#code/PTAEHUAsFMDtQC41ASwLYAcA201wQIYIoD28AZgK6wDGxZoBATgOaoDOoAbsygQCYoaAGkTISXaEywkBHUJAIYMATwCwAKGgAPDCSYJQVWvXgAvFBgAUzJgRXsAXKABK0Gvv4AedgiYpYFlECWBUAPgBtAF1ogEpnNw8mb19-QODQyKiAbk0dPQMjajpSc0srADoq23snV3dPHz8AoMZM6LiEhuSmtNaQ8OjcrV19Q2MShgtrKoqahy6klOb0tsGYqPj6pd6WjPXQAG9NUFAPWF9QCIJRWYAjdijQAF5GJjsHYdOcQ34iAhejC+oAeFXI+gAogQaJArHcXmEjidTqA-oRAXcKmglFYrAB9UQofjaWII0BWQ6gWZoggRInaKK3Kp3OnEp4AX1isWBnOBTGgCEoTHgNOG7M0mhAEBg8CQ0FQmBweFghFMRRMpTebBQnFgJEMPH8AiEojloAkUhkch1oHYAjyo0KEzV0wAjDZ3rVFo1Uns1llOtsfSt+u0cg6CuNii7LO7ZvM6olg319gHNt6er7VgMssN8mN1ZMyhh3QmM8sU-6Oumg5mQ6nokiNKdzpdrkyKg8nq8E8Cfqj-oCCMDQeCmFCYXCycdmyiaRisTj8YTiaTnoiKVSqjTWQyOyz6RyuTzucj+YLhQPCGKgA)

### 💻 Code

```ts
// When the implementation function arg is variadic, the overload is happy
export function zip(arrays: Record<string, any>[][]): Record<string, any>[];
export function zip(...arrays: Record<string, any>[][]): Record<string, any>[];
export function zip(...arrays: Record<string, any>[][]): Record<string, any>[] {
  const [a, ...bs] = arrays;
  let data = a;
  bs.forEach(b => {
    data = b.map((_, idx) => ({ ...data[idx], ...b[idx] }));
  });
  return data;
}

// When the implementation function arg is not variadic, the overload is sad
export function zip1(arrays: Record<string, any>[][]): Record<string, any>[];
export function zip1(...arrays: Record<string, any>[][]): Record<string, any>[];
export function zip1(arrays: Record<string, any>[][]): Record<string, any>[] {
  const [a, ...bs] = arrays;
  let data = a;
  bs.forEach(b => {
    data = b.map((_, idx) => ({ ...data[idx], ...b[idx] }));
  });
  return data;
}
```

### 🙁 Actual behavior

When overloading a function to take an array as an argument or from a variadic argument, typescript throws an error unless the implementation function uses a variadic argument.

### 🙂 Expected behavior

 My expectation is that the implementation function could use either a single array argument or a variadic array argument with no complaints from TypeScript, because the types involved are equivalent (to my understanding).

**Comment by MartinJohns** [comment]
`f(array)` and `f(item1, item2)` are two **very** different calls. The correct type for the first overload would be `Record<string, any>[]`, not `Record<string, any>[][]`. When you call `f(array)` you're not passing an array of elements (as you do with the second call), instead you pass a single element that is an array, which is then wrapped in an array.

**Comment by IllusionMH** [comment]
These implementations are not equivalent. Just pass data, log `arrays[0]` and see the difference.

I'd rather expect error in first overload as `zip([[{a: 1}]])` is not that actually expected in implementation but `any` hides error in first case because
```ts
const example: Record<string, any>[] /* what is expected for arrays[0] in implementation */ = [] as Record<string, any>[][] /* type in first first overload */;
```

If you replace `any` with `unknown` you would see that first overload of `zip` is actually not compatible with implementation.

**Comment by jjorissen52** [comment]
I don't fully understand your explanation, so I still don't understand how this isn't a bug in TS. I've reduced the problem down just to its essentials, and followed your advice to simply log the inputs:

```typescript
// This overload signature is not compatible with its implementation signature.
export function one(arrays: number[]): void;
export function one(...arrays: number[]): void;
export function one(...arrays: number[]): void {
  console.log(arrays)
}
```

```javascript
function one(...args) {
  console.log(args)
}

function two(args) {
  console.log(args)
}

one([1],[2],[3])
two([[1],[2],[3]])
```

![image](https://user-images.githubusercontent.com/12461302/169158659-c92b72e5-4cb1-42ae-809e-84db2975a2ec.png)

It really looks like `args` has the same type in both implementations. What am I missing?

**Comment by IllusionMH** [comment]
You need to log `args[0]` for same implementation function but pass different values that you declare in overloads, not different values to different implementations.

Maybe requirement to have rest argument as array makes them look same, but in reality they are expected as different types if you look on types expected for each argument. For example if you replace rest parameter with exactly 3 items of corresponding type it should be more obvious:
[Playground](https://www.typescriptlang.org/play?ts=4.6.2#code/PTAEHUAsFMDtQC41ASwLYAcA201wQIYIoD28AZgK6wDGxZoBATgOaoDOoAbsygQCYoaAGkTISXaEywkBHUJAIYMATwCwAKGgAPDCSYJQVWvXgAvFBgAUzJgRXsAXKABK0Gvv4AedgiYpYFlECWBUAPgBtAF1ogEpnNw8mb19-QODQyKiAbk0QUB09AyNqOlJzSysAOhrbeydXd08fPwCgxkzouISm5Ja09pDw6NytXX1DYzKGC2s6hwBGHqSU1vSO4ajgpjsHACZl5tS2jM3t3fYAZkO+4-WhrPjGlf6TjazRwomSk3LQWZsO3qS2eRzWg06W0YQP2N1WA1OWXO9WuoNu4MR3TR8LeD2ioAA3ppQKAPLBfKAIgRRDUqgAjdhRUAAXkp83YC2R+y5VxyxNAOEM-CIBBZjFGJIZVXI+gAogQaJArHSWWFCfyScLCGK6VU0EorFYAPqiFD8bSxVWgKwE0C0rUECJm7RQ2l0p3mpkAX1isQloB9-qY0AQlCY8Adoy9mjyYCgcDE0FQmBweFghFMP2m8GYbBQnFgJEMPH8AiEoiQSYkUhkcnzoHYAk0X2KU0zswWgIucNe90hWMSYIR7xGsYK41bpXblk7tPZPbuEM2A96OL7m0+E8mU7+Ha7wIXGJHUPZB2xvaXSOhF1Rg-Rw7xUSed7Xl+iza3WenGE78-Pi8xGIn0PB9IXVDQSTJCkqRpGoGSZVl2X9QVQAdMUCH9KUZSYeVFWVK0iQgklUJFHU9QNY1TXNS1mTVG07RqB0PRdWD6WY71fX9QN+WDUNwxIwgoyAA)

```ts
export function zip(arrays: Record<string, any>[][]): Record<string, any>[];
// export function zip(...arrays: Record<string, any>[][]): Record<string, any>[];
export function zip(arrays1: Record<string, any>[], arrays2: Record<string, any>[], arrays3: Record<string, any>[]): Record<string, any>[];
export function zip(arrays1: Record<string, any>[], arrays2: Record<string, any>[], arrays3: Record<string, any>[]): Record<string, any>[] { /*...*/ }
```

As you can see - there is obvious mismatch in expected first parameter between one of overloads and implementation.

**Comment by jjorissen52** [comment]
Ahhh ok... I was experiencing temporary insanity.
