### ISSUE TITLE
Computed properties in destructuring patterns are not recognized

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#4917]
We compile this:
```ts
let foo = "bar";
let {[foo]: bar} = {bar: "bar"};
```
to this:
```ts
var foo = "bar";
var _a = [foo], bar;
{
    bar: "bar";
}
;
```
(and error on the syntax)
whereas babel compiles it cleanly to this:
```ts
"use strict";

var foo = "bar";
var _bar = { bar: "bar" };
var bar = _bar[foo];
```

Babel's output functions as expected, ours does not.

There's a section on this on the [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) on destructuring.

**Comment by DanielRosenwasser** [comment]
This is indeed an ES6 feature; follow from http://rbuckton.github.io/grammarkdown/es6.html#ObjectBindingPattern
