### ISSUE TITLE
Declaration merging namespace with function 

### ISSUE THREAD

**Issue by olegdunkan** [microsoft/TypeScript#49184]
# Bug Report

### 🔎 Search Terms

Declaration merging

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMAFASkQbwL4FgBQBYAhgLYCmAzgA7ETnJYGIuLkAe1cATlIhAkp8SFRAF5EARgLYgA)

### 💻 Code

```ts
function f() {}

namespace f {
    export const name = 1
}
```

### 🙁 Actual behavior

No error in compile time, error in runtime 
[ERR]: "Executed JavaScript Failed:" 
[ERR]: Cannot assign to read only property 'name' of function 'function f() { }' 

### 🙂 Expected behavior

Error in compile time

**Comment by MartinJohns** [comment]
Note: This only applies to special properties existing on functions, such as `name`. In general this works fine.

**Comment by olegdunkan** [comment]
@MartinJohns how do you think it is possible to detect by the type checker that assignment `export const name = 1` inside namespace f is not valid?

**Comment by Josh-Cena** [comment]
Quite surprising that TS doesn't even forbid assigning `f.name` directly when `name` has been marked as `readonly` in `interface Function`.

**Comment by RyanCavanaugh** [comment]
AFAIK this is the first time someone's noticed this since TypeScript 0.8. The fix here would be rather involved (we'd have to look up the merging symbol and compute its readonyliness ahead of time) so I don't think this is worth fixing if the only observable symptom is this and `length`.

**Comment by RyanCavanaugh** [comment]
Aside: it's possible a fix to #49113 (assuming a good fix exists) might fix this as a side effect

**Comment by olegdunkan** [comment]
@MartinJohns of course
