### ISSUE TITLE
TS 4.7.1-rc cannot resolve `default` CJS or ESM exports with module `nodenext`.

### ISSUE THREAD

**Issue by scott-lc** [microsoft/TypeScript#49189]
# Bug Report

In React development the NPM packages classnames and clsx, are extremely popular, but TS 4.7.1-rc cannot resolve their default export:

```
import clsx from "clsx";
import classNames from "classnames";

console.log(clsx("a", "b", "c"));
console.log(classNames("a", "b", "c"));
```

Results in the error(s):

```
This expression is not callable.
  Type 'typeof import("...")' has no call signatures.ts(2349)
```

Looking at the `package.json` files for both the `clsx` and `classnames` packages, they each specify the `types` property.  

### clsx/package.json
```
  "module": "dist/clsx.m.js",
  "main": "dist/clsx.js",
  "types": "clsx.d.ts",
```
### clsx/clsx.d.ts
```
...
declare const clsx: (...classes: ClassValue[]) => string;
export default clsx;
```

### classnames/package.json
```
  "main": "index.js",
  "types": "./index.d.ts",
```

### classnames/index.d.ts
```
export default function classNames(...args: Argument[]): string;
```

### 🔎 Search Terms

`nodenext`, `node16`, `default export`, `expression is not callable`

### 🕗 Version & Regression Information

Exists in TS `4.7.0-beta`, `4.7.1-rc` and `4.8.0-dev.20220520`.

- I was unable to test this on prior versions because `nodenext` is a new feature.

### ⏯ Playground Link

Playground link - N/A requires external dependencies.

Sample repo - https://github.com/scott-lc/tsc-issue-220520

### 💻 Code

```
import clsx from "clsx";
import classNames from "classnames";

console.log(clsx("a", "b", "c"));
console.log(classNames("a", "b", "c"));
```

### tsconfig.json
```jsonc
{
  "compilerOptions": {
    "esModuleInterop": true,
    "alwaysStrict": true,
    "module": "NodeNext",
    // "moduleResolution": "NodeNext",   # works with `node` but not `nodenext`
    "target": "ESNext"
  },
  "include": ["./index.ts"]
}
```

Also see [this repo](https://github.com/scott-lc/tsc-issue-220520).

### 🙁 Actual behavior

Code fails to compile with `module: nodenext`.  Works fine pre 4.7 with `module: esnext`.  

### 🙂 Expected behavior

`nodenext` module resolution to not require changes to popular third-party NPM code.

**Comment by scott-lc** [comment]
Possibly related to #48845

**Comment by scott-lc** [comment]
Thanks @andrewbranch.  Similar to what you mentioned [here](https://github.com/microsoft/TypeScript/issues/49160#issuecomment-1137482639), I think the community will need to open PRs with these individual libraries to update their types.

**Comment by scott-lc** [comment]
To those that run into this issue, I'd like to give a shoutout to In the interim @JacobLey who published  [default-import](https://www.npmjs.com/package/default-import) as an interim workaround as described [here](https://github.com/styled-components/styled-components/issues/3601#issuecomment-1133767683).

**Comment by Edweis** [comment]
On my side, I hacked my way by redefining the import explicitly:

```js
import _useSWR, {  SWRHook } from 'swr';

const useSWR = _useSWR as unknown as  SWRHook
```

**Comment by wojtekmaj** [comment]
This issue can still be reproduced with TypeScript 5.1.3.
