### ISSUE TITLE
Invalid enum value inference on a class property.

### ISSUE THREAD

**Issue by notaphplover** [microsoft/TypeScript#49183]
# Bug Report

### 🔎 Search Terms

- This condition will always return

### 🕗 Version & Regression Information

- This is the behavior (at least) on versions:
  - `3.9.7` 
  -  `4.0.5`
  - `4.1.5`
  - `4.2.3`
  - `4.3.5`
  - `4.4.4`
  -  `4.5.5`
  - `4.6.4`
  - `4.8.0-dev.20220519` 

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Type System Behavior](https://github.com/Microsoft/TypeScript/wiki/FAQ#type-system-behavior)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

- [Nightly](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220519#code/KYOwrgtgBAYg9nKBvAUFKAjAhgJwIwA0amuATEetjgMxEC+KKWGAzgC45YDGbUXANlhYsoAFRYAhMAHNkxAMQAzBAC5YCANyN0XOCHY4wPODgAUASjnp0bABYBLFgDolCKAF51cJ1Txb0DMQADmAY-PZcUAAmcADKbGCKihZqAG5w9lFW1naOLsqInvDevlrENg7OAPoxsUHAXPaKEfGJyeZl1lBNUKa5zq6IAITuRQg+ZJaoXQwB2lBBOHBsDStZzAbcvDVx9Y3NXK1JKVDpmZ0LSys8wFlVEACexbHAbCtm5mkZWdM5lfluMYlXDUfxQBgMIA)

### 💻 Code

```ts
enum Foo {
  bar1,
  bar2,
  bar3,
}

abstract class TsBug {
  #foo: Foo;

  constructor() {
    this.#foo = Foo.bar1;
  }

  public doStuff(): void {
    this.#foo = Foo.bar1;

    this._doSpecificStuff();

    if (this.#foo !== Foo.bar2) {
    }
  }

  protected abstract _doSpecificStuff(): void;

  protected _myFooSetter(): void {
    this.#foo = Foo.bar3;
  }
}

```

### 🙁 Actual behavior
```
19:9 - error TS2367: This condition will always return 'true' since the types 'Foo.bar1' and 'Foo.bar2' have no overlap.

19     if (this.#foo !== Foo.bar2) {
           ~~~~~~~~~~~~~~~~~~~~~~
```
Since there's a call to the `_doSpecificStuff()` protected abstract method, there's room to call `this._myFooSetter()` and update the private `#foo` property

The same happens if we refactor this code with a public or protected `foo` property instead of `#foo`:

### 🙂 Expected behavior

I expect no compilation errors for the reason above.

**Comment by RyanCavanaugh** [comment]
Duplicate #9998

**Comment by notaphplover** [comment]
Closed as duplicated
