### ISSUE TITLE
The '/ * *' snippet should support parameter deconstruction of typescript interface member functions

### ISSUE THREAD

**Issue by tuchg** [microsoft/TypeScript#49196]
The '/ * *' snippet should support parameter deconstruction of typescript interface member functions as   deconstruction of  the normal function parameters
![image](https://user-images.githubusercontent.com/24775733/169428556-7e5081a1-41c2-40d7-8e64-4d06510e9667.png)

after enter:

## in normal function behavior:
![image](https://user-images.githubusercontent.com/24775733/169428007-ac5d7cea-6e74-4f1e-bfe3-d50bd3a5d981.png)

## in ts interface declaration:
![image](https://user-images.githubusercontent.com/24775733/169428238-00030321-98f7-4fe5-ad47-442e7fb3d55e.png)
should be:
![image](https://user-images.githubusercontent.com/24775733/169428439-575a6acf-23f3-490a-9caf-4cf26c474534.png)

**Comment by tuchg** [comment]
@mjbvz This has nothing to do with the typescript programming language itself

only editor problem

**Comment by andrewbranch** [comment]
Actually, it’s more than just the snippet. The snippet isn’t there because we don’t pick up these `@param` tags on property signatures at all:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/3277153/171301502-28cecd49-0119-4943-b172-6c0e0133863f.png">

Compare with a method signature:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/3277153/171301570-d7718d67-fca5-4abe-8cb4-1233621dbc48.png">

**Comment by andrewbranch** [comment]
@sandersn I know we’ve made JSDoc container searching fuzzier in the past, but I think that was mostly for applying comments to JS declarations, not TS declarations. Any good reason why `@param` shouldn’t apply here?

```ts
interface I {
  /** @param x */
  prop: (x: string) => void;
}

**Comment by andrewbranch** [comment]
They are connected—the `@param` snippet should work if and only if it will be recognized after writing it. I wasn’t sure if this case of “this JSDoc should apply here” was a bug or suggestion, but from your feedback I’m happy to relabel it a bug. AFAIK the snippet will not automatically start working as soon as the `@param` tag is picked up on property signatures, but I expect a complete fix to include the necessary change to make the snippet work.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
