### ISSUE TITLE
Missing definition for Atomics.waitAsync

### ISSUE THREAD

**Issue by Eyal-Shalev** [microsoft/TypeScript#49198]
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `[ "deno.window", "deno.worker" ]`.

## Missing / Incorrect Definition

Missing definition for [`Atomics.waitAsync`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/waitAsync)

## Sample Code

```typescript
const sab = new SharedArrayBuffer(Int32Array.BYTES_PER_ELEMENT * 1024);
const ia = new Int32Array(sab);
await Atomics.waitAsync(ia, 0, 0);
```

## Documentation Link
[Atomics.waitAsync() - JavaScript  | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/waitAsync)

[Atomics.waitAsync implementation · Issue #14687 · denoland/deno](https://github.com/denoland/deno/issues/14687)

**Comment by MartinJohns** [comment]
According to the MDN compatibility list "Deno" does not support this feature.

**Comment by Grubba27** [comment]
Hello @Eyal-Shalev I was this issue... could you give some more details on this return ? the docs are not as clear as I wanted them to be. 
Does waitAsync when has async flag set as true return a "promise" i could not find what this promise means.
Also I was not able to run the sample code.

**Comment by Eyal-Shalev** [comment]
The `Atomics.waitAsync` function will return one of these options:
```
{ async: false, value: 'ok' }
{ async: false, value: 'not-equal' } 
{ async: false, value: 'timed-out' }
{ async: true, value: promise }
```
Where the promise can contain either "ok", "not-equal" or "timed-out".

**Comment by Eyal-Shalev** [comment]
See [this](https://v8.dev/features/atomics) for more documentation on the issue

**Comment by Grubba27** [comment]
Awesome! updated the PR with this sample as you have sent me thx a lot :)
