### ISSUE TITLE
Inconsistencies in type parameter error messages: type 'arguments' vs 'parameters'

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#49202]
# Bug Report

### 🔎 Search Terms

generic type argument parameter error consistency

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDMAVAFgUwKJgCYA8AYjAE4DOUiAvImCALYBGmpANIgMqYQJ4B8ACgCUiAN4BfAFAB6GYgWKlylasRzEAP207Z87KVJxSALkQAlTAEcQZTHkRQAngAdMiAIakA5o0xgockQGDyc6OCpgOAAbaLgAd0Q4F1gED2jHV3cvXwZ-QIA6IA)

### 💻 Code

```ts
function inTheEnd<First = number, Second>() {}
//                             // ~~~~~~
// Error: Required type arguments may not follow optional type arguments.
```

### 🙁 Actual behavior

The error refers to `Second` as a type _argument_.

### 🙂 Expected behavior

The AST node type is _Parameter_. The error message should refer to it as such, I think.

https://www.typescriptlang.org/docs/handbook/2/generics.html also generally refers to the declaration sites as _parameters_ and to provided types as _arguments_.

**Comment by fatcerberus** [comment]
Yes, in general a *parameter* is a variable, an *argument* is the value the caller provides for that variable.

**Comment by JoshuaKGoldberg** [comment]
Hmm, looks like this has since been fixed in TypeScript. Darn - I was hoping to contribute this 😄.

I took a peek through diagnostic messages that mention `type (argument|parameter)` and didn't spot any that seemed immediately wrong. If anybody spots one, I'd be happy to send a PR to fix.
