### ISSUE TITLE
Array map does not carry tuple size

### ISSUE THREAD

**Issue by ilibar-zpt** [microsoft/TypeScript#49201]
# Bug Report

### 🔎 Search Terms
array map tuple size type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about tuples

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhjAvDA2gRgDQCYC68KpgCuAtgEYCmAThjMedTgFCiSxlLwB0JcADgAoAbkgB8MAMpQqASzABzYQEolQA)

### 💻 Code

```ts
const a = [1,2] as [number, number]
const b = a.map(v => String(v))
```

### 🙁 Actual behavior

type of `b` is `string[]`

### 🙂 Expected behavior

type of `b` is `[string, string]`

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/29841

**Comment by ilibar-zpt** [comment]
nice
