### ISSUE TITLE
Typescript 1.6 in vs2015 don't compile .ts files .

### ISSUE THREAD

**Issue by saeedtabrizi** [Microsoft/TypeScript#4920]
I have a problem with typescript 1.6 in vs2015 .
I'm using vs2015 & typescript 1.6 in nodejs project .
when i write in .ts files and save my file the generated output (.js files) is a valid javascript file but when i rebuild my  project all generated file be clean and replaced with invalid javascript files as below :

1) my .ts file :

![sar ts](https://cloud.githubusercontent.com/assets/10245423/10011032/570301e2-6101-11e5-8dc6-aea44c18edd9.jpg)

2) when i save .ts file generate this output in .js file 
![sar onsavefile](https://cloud.githubusercontent.com/assets/10245423/10011038/7d2cb2a0-6101-11e5-9cf8-7d3ff573476a.PNG)

3) when i rebuild my project the output is :
![sar afterrebuild](https://cloud.githubusercontent.com/assets/10245423/10011046/92d96b52-6101-11e5-8009-9f203c05aca5.PNG)

and my project setting is here :
![project settings](https://cloud.githubusercontent.com/assets/10245423/10011073/fcbff090-6101-11e5-8206-1e69c8fe6e90.PNG)

Is there any idea ?

**Comment by mhegazy** [comment]
your target is EcmaScript 6, you need EcmaScript 5 instead. also you need to set the module to commonjs if you are building for node:

![image](https://cloud.githubusercontent.com/assets/8000722/10011597/b4495342-60b1-11e5-8270-960c61b4763d.png)

**Comment by saeedtabrizi** [comment]
many thanks but i solved my problem by https://github.com/Microsoft/TypeScript/issues/4748 . now everythings working good ,but when i run some build after the 5 or 6 compilation this problem appears again .

**Comment by mhegazy** [comment]
glad it was resolved.
