### ISSUE TITLE
Getting unexpected results with readonly parameter in class constructor

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#49212]
# Bug Report

### 🔎 Search Terms
- Class Constructor
- Readonly Parameter
- Parameter Properties

### 🕗 Version & Regression Information

all(from 3.3.3 to 4.6.4 and 4.7.0-beta)

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.4#code/MYGwhgzhAEBiD29oG8BQ0PWPAdhALgE4Cuw+8hAFIQKZgAmuIAntAEZiEBc0BhAljgDmAShTQAvqglA)

### 💻 Code

```ts
class Foo {
    constructor(readonly bar: string) { }
}
```

### 🙁 Actual behavior

```ts
"use strict";
class Foo {
    constructor(bar) {
        this.bar = bar;
    }
}
```

### 🙂 Expected behavior

```ts
"use strict";
class Foo {
    constructor(bar) {
    }
}
```

**Comment by MartinJohns** [comment]
This is working as intended. See the documentation: [Parameter Properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties)

**Comment by MartinJohns** [comment]
I'm surprised as well, but `readonly` is listed.

> These are called parameter properties and are created by prefixing a constructor argument with one of the visibility modifiers `public`, `private`, `protected`, or `readonly`.

It's probably read as "one of the modifiers (public, private, protected) or alternatively readonly."

**Comment by MartinJohns** [comment]
See also: https://github.com/microsoft/TypeScript/issues/7590#issuecomment-199094100

**Comment by magic-akari** [comment]
It makes sense. Close this issue.
