### ISSUE TITLE
language server ignores multiple tsconfig files

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#49210]
# Bug Report
if a project has multiple tsconfig files (eg `tsconfig.json` and `tsconfig.other.json`) then the language server seems to ignore the one that isn't named `tsconfig.json`

### 🔎 Search Terms
language server multiple tsconfig 

### 🕗 Version & Regression Information
4.8.0-dev.20220522
### ⏯ ~~Playground~~ github Link
https://github.com/DetachHead/typescript-nodejs-project/tree/global-types-issue

#### main config
```json
// tsconfig.json
{
    "compilerOptions": {
        "target": "es3"
    },
    "include": ["src/main.ts"]
}
```
```ts
// src/main.ts
export {}

"".replaceAll // error
```

#### other config
```json
// tsconfig.json
{
    "compilerOptions": {
        "target": "es2021"
    },
    "include": ["src/other.ts"]
}
```
```ts
export {}

"".replaceAll // error ???
```

### 🙁 Actual behavior
the following error in `other.ts`:

> Property 'replaceAll' does not exist on type '""'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.

![image](https://user-images.githubusercontent.com/57028336/169767172-ec7d0140-a1a3-42db-a789-899b03ad1558.png)

### 🙂 Expected behavior
no error when accessing the globally defined `pm` object in either file

**Comment by DetachHead** [comment]
looks like its not just `"types"`, it seems to ignore other compiler options too such as `strictBindCallApply`:

![image](https://user-images.githubusercontent.com/57028336/169762488-c1b060d1-9c36-4925-a76d-2f52571ff62d.png)

**Comment by MartinJohns** [comment]
See #33094.
