### ISSUE TITLE
Allow overriding folding ranges

### ISSUE THREAD

**Issue by icetbr** [microsoft/TypeScript#49219]
## 🔍 Search Terms
folding
getOutliningSpans
foldingRanges

## ⭐ Suggestion
Allow override getOutliningSpans in Ts Language Server

## 📃 Motivating Example

- people want easy to custom folding ranges, see extensions like [Region Folder](https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder)(47k installs) and [Explicit Folding](https://marketplace.visualstudio.com/items?itemName=zokugun.explicit-folding)(7k installs).
- these extensions could in some cases avoid an extra parsing of the document if already identified folding regions were provided.
- VsCode doesn't have a way to prevent overlapping conflicts of folding ranges
- it would be consistent with the example provided in [Writing a Language Service Plugin](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) that if you would be able to override `getOutliningSpans`, but it is never called. Don't know if this is a bug or as designed

## 💻 Use Cases

For me, I want to reduce the start index of every `jsdoc` comment so that comments would in practice be "invisible", not taking up a dedicated line.

Short of creating a **client** extension, there is no way around it, but that incurs in extra parsing.

**Comment by andrewbranch** [comment]
I have no idea what specifically is being suggested. The Suggestion section is blank 🤔 

<img width="307" alt="image" src="https://user-images.githubusercontent.com/3277153/171302667-717e7a1a-1cd8-4980-a02a-392281ebcb38.png">

**Comment by icetbr** [comment]
I updated it

**Comment by RyanCavanaugh** [comment]
Outlining spans are controlled by the syntax server, which doesn't support plugins.

I think this belongs in the realm of VS Code, or as a configuration option to TS Server if this alternative folding behavior is popular enough to warrant spending time on.

**Comment by icetbr** [comment]
Understood, thanks. It's a bit confusing when creating the proxy for `info.languageService` to see ~70 public functions, but be able to "intercept" just some of them. I didn't know if I was doing something wrong.

getCompletionsAtPosition: interceptable
getOutliningSpans: not interceptable
