### ISSUE TITLE
`checker.getTypeAtLocation` for `ExpressionWithTypeArguments` returns an error any type

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#49223]
# Bug Report

### 🔎 Search Terms

`ExpressionWithTypeArguments`, `getTypeAtLocation`, `checker`, api, error any.

### 🕗 Version & Regression Information

- This is a bug in the `@next` version of TS.

### ⏯ Playground Link

Because this is a bug with the API specifically, here is a link to the ast explorer.
https://ts-ast-viewer.com/#code/GYVwdgxgLglg9mABAWwIYGsCmAhOAPAHgBUA+ACgDdUAbETALkSIEpEBvAKEUQCdMoQPJG0RVamRAF8A3B0kcOEBAGcoKDJgDKUHjDABzXHkQBedViMFVugyWlA

![image](https://user-images.githubusercontent.com/7462525/169940192-d7a9334e-aec9-4963-946c-0d67425cb396.png)

### 💻 Code

```ts
function makeBox<T>(value: T) {
  return { value };
}

const makeStringBox = makeBox<string>;


const sett = Set<string>;
```

### 🙁 Actual behavior

`checker.getTypeAtLocation` for the `ExpressionWithTypeArguments` node returns an error `any`.

### 🙂 Expected behavior

`checker.getTypeAtLocation` for the `ExpressionWithTypeArguments` node returns the relevant type of the expression, which would be `(value: string) => {value: string}`

**Comment by a-tarasyuk** [comment]
@bradzacher Do you mean calling `checker.getTypeAtLocation` on the variable _initializer_ node?

```ts
const makeStringBox = [|makeBox<string>|]
      
```

**Comment by bradzacher** [comment]
specifically on the `ExpressionWithTypeArguments` node.
it does not matter if it's part of a variable, call, or an expression statement.

You can repro in ts-ast-viewer by selecting the `ExpressionWithTypeArguments` node in the middle column. The right column should show the correct type under the "Type" heading (which shows the result of `getTypeAtLocation`).

In the case of a variable declaration - the `VariableDeclaration` node and the variable's `Identifier` node both show the correct type (`(value: string) => { value: string; }`), but if you select the `ExpressionWithTypeArguments` it'll show an `any` type.

**Comment by a-tarasyuk** [comment]
@bradzacher Thanks

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
