### ISSUE TITLE
augmenting a module when not using any `import` or `export` statements overwrites the module instead of extending it

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#49227]
# Bug Report
when augmenting a module and not using any `import` or `export` statements (except the dynamic import one which i guess doesn't count), it overwrites the existing module instead of extending it

### 🔎 Search Terms
augment module overwrite 

### 🕗 Version & Regression Information
4.8.0-dev.20220524
### ⏯ Playground Link
can't seem to reproduce it in the playground for some reason https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&jsx=0&module=1&isolatedModules=false&ts=4.8.0-dev.20220523#code/CYUwxgNghgTiAEBbA9sArhBByADsgzgC6JQB2AtGMhJmIQJbKlbwDeAvgLABQPA9H3ilk8EDBjIYAGngAjNIXiEAFgnxRECKqFHjJ+ePVJLl9AzgkArcIQBc8ZYUI58tgQHN6KtLIB0VRD4AERBCKDBlAAkQKGA+QgBPHBB8MBh6HEJyYVBLfHILZGs6eLgQPjN8NBAAfThCnlBIWC0mIngAM2Rke3pEPBhCAApcAmIySmpaBiYsAEpfADVYeihZTABlKmSgA

but here is a repro project https://github.com/DetachHead/typescript-nodejs-project/tree/issue_repro
### 💻 Code

```ts
declare module 'postman-collection' {}

// TS2694: Namespace '"postman-collection"' has no exported member 'VariableScope'.
declare const foo: import('postman-collection').VariableScope
```

### 🙁 Actual behavior
> TS2694: Namespace '"postman-collection"' has no exported member 'VariableScope'.

### 🙂 Expected behavior
no error as the module is extended, not overwritten

**Comment by andrewbranch** [comment]
Yes, it is awful, but this is the difference between an ambient module declaration and a module augmentation.

**Comment by DetachHead** [comment]
In that case do you know why I can't seem to recreate this behaviour in the playground?

**Comment by andrewbranch** [comment]
Hmm... I have no idea 😅
