### ISSUE TITLE
Using alias in Mapped Types will not work with string literal type infer

### ISSUE THREAD

**Issue by misuken-dw** [microsoft/TypeScript#49238]
# Bug Report

### 🔎 Search Terms

`Function` `Generic Type` `Infer` `String` `Literal`  `Mapped Type` `alias`

### 🕗 Version & Regression Information

This is a bug in the `4.7.x` version of TS.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwEYAeAFXhAA8MRVgBneAb3gG0AFeLfAaxACeORPApQmAYSgAHLBigQsALxAkuAMngMMMHgHMAfAF0AXPABq8AL4AaC5Rp1GWnfoMAKKGbIBKbwG4AKFBIWAQUdGw8AhwAJnIHWnomVk5uPkFhUXhNbV1UPXhxeClZeUUVNWMzS1t7aiTnPLdPbz9RIJDoOCQ0TFx8REIAZgSGpxT2Lh54fiERMlN7Ostx5Jd8w1bRdrJO8G7wvqjBwgAWMcd11On8UrkFZVU5rIpc1wLq5btVq6aPrZeHYBQKBajSHAwDDwMB4bTwGBEeAAXhiRHczAAgmYAERQHFWHz+eAAehJogAymcAHQANhY8Gx8DxOOJVngAB9KTSAOzwBlM5oFNlgqgQqEwuHQmCxFExWIYpkswnEsncukC3H4tmc9V8oqoATwAC0BngAHIZebuABbaSKMByCBGgAWxQwAmkCHNUEN1oARuAoMgGAg5PBgDgQExUDhoW6AG4IKDwD1eg2x+QnA3AbhMOCIEBwdAgXPALBwTDO+CQ9LlysYaszORMHAAd3wPDkWEeKhg1PcPIADLFYj5ReLobDUPCYMM5UMcMNFVqCUTSeSyFSNawldrrLqt7z+bvVyLwZCp1KEWcF+cV8z8SqN+r6afH6yD1yj9T9e+WSKQA)

### 💻 Code

Using `as` in Mapped Types seems to cause the value to be incorrectly inferred in the Literal Type of the value.

```ts
declare function foo1<T extends { [P in keyof T as Capitalize<P & string>]: V }, V extends string>(a: T): T;
declare function foo2<T extends { [P in keyof T & string as Capitalize<P>]: V }, V extends string>(a: T): T;
declare function foo3<T extends { [P in keyof T]: V }, V extends string>(a: T): T;
declare function foo4<T extends { [P in Capitalize<keyof T & string>]: V }, V extends string>(a: T): T;

export const r1 = foo1({A: "a"}); // TS4.6 { A: "a"; } | TS4.7  { A: string; }
export const r2 = foo2({A: "a"}); // TS4.6 { A: "a"; } | TS4.7  any -> 'r2' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)
export const r3 = foo3({A: "a"}); // TS4.6 { A: "a"; } | TS4.7  { A: "a"; }
export const r4 = foo4({A: "a"}); // TS4.6 { A: "a"; } | TS4.7  { A: "a"; }
```

### 🙁 Actual behavior

```ts
declare function foo1<T extends { [P in keyof T as Capitalize<P & string>]: V }, V extends string>(a: T): T;
declare function foo2<T extends { [P in keyof T & string as Capitalize<P>]: V }, V extends string>(a: T): T;
declare function foo3<T extends { [P in keyof T]: V }, V extends string>(a: T): T;
declare function foo4<T extends { [P in Capitalize<keyof T & string>]: V }, V extends string>(a: T): T;

export const r1 = foo1({A: "a"}); // ❗ { A: string; }
export const r2 = foo2({A: "a"}); // ❗ any -> 'r2' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)
export const r3 = foo3({A: "a"}); // ✅ { A: "a"; }
export const r4 = foo4({A: "a"}); // ✅  { A: "a"; }
```

### 🙂 Expected behavior

```tsx
declare function foo1<T extends { [P in keyof T as Capitalize<P & string>]: V }, V extends string>(a: T): T;
declare function foo2<T extends { [P in keyof T & string as Capitalize<P>]: V }, V extends string>(a: T): T;
declare function foo3<T extends { [P in keyof T]: V }, V extends string>(a: T): T;
declare function foo4<T extends { [P in Capitalize<keyof T & string>]: V }, V extends string>(a: T): T;

export const r1 = foo1({A: "a"}); // ✅ { A: "a"; }
export const r2 = foo2({A: "a"}); // ✅ { A: "a"; }
export const r3 = foo3({A: "a"}); // ✅ { A: "a"; }
export const r4 = foo4({A: "a"}); // ✅ { A: "a"; }
```

**Comment by ahejlsberg** [comment]
Following #47889 the example is typed as follows:

```ts
export const r1 = foo1({A: "a"});  // { A: string; }
export const r2 = foo2({A: "a"});  // { A: string; }
export const r3 = foo3({A: "a"});  // { A: "a"; }
export const r4 = foo4({A: "a"});  // { A: "a"; }
```

This is the intended behavior since mapped types with `as` clauses aren't supposed to provide contextual typing as it would require reverse-mapping the `as` clause. It sometimes worked before, but that was just happenstance.
