### ISSUE TITLE
installer - add option to update system path to latest Typescript

### ISSUE THREAD

**Issue by voltcode** [Microsoft/TypeScript#4923]
It would save a bit of hassle (especially when updating all PCs in a team) if Typescript VS installer asked about PATH update to the latest Typescript bin directory (ie. remove old Typescript from PATH , add new Typescript to PATH).

Managing all developers and asking them to update the PATH manually leads to problems - incoherent versions of command line tools can lead to erratic compilation errors between team members.

**Comment by DanielRosenwasser** [comment]
Looks like a duplicate of #2068.
