### ISSUE TITLE
Some way to refer to the type of a generic class

### ISSUE THREAD

**Issue by bakkot** [microsoft/TypeScript#49234]
# Suggestion

## 🔍 Search Terms

type typeof generic class parameter interface

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like a way to refer to the type of a generic class - the class itself, not of its instances.

## 📃 Motivating Example

I have a generic factory which produces classes. I want to export the (generic) type of the resulting classes, and declare that my function returns classes conforming to that type. But I can't refer to type of the top-level declaration, only of its instances.

Here's an example of what I'm trying to write:

```ts
declare class A<Brand> {
  brand: Brand;
  method(x: Brand): number;
}

function mkClass<T>(brand: T) {
  let klass = class <T> {
    brand = brand;
    method(x: T): number {
      return 0;
    }
  };
  // how do I say this is specifically a class conforming to the definition of A?
  return klass as (typeof A)<T>; // currently a syntax error
}
```

([Playground link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwIIB4BCMoDtgA+eAbwCh54AjPQgLnlwOAG5L4BbEAFwAsA9sAAUAD0bNCASkb4Arp2ogY7AL7lyAMzn4wPAJYD8XANYBhaKkwAVIsNotG1qWQ4Re8E5bQBeRN-gbEgoqKgdCeD9wtg4qbn4hMScZeHlFZVdQ0LgeORhjAAZ2LPUqVWL4AHpK+EEAd3hgAXgASXhkKABPeH59ND72gAdwfU19MCgICG6ofxQ0MCNNARhOfXwAcx7m-gRQMfx9AyN4AU0MAH4OHLzjL3n4FHhhHk7hs4wpINYqmrA8uD4HjTR7tTpAqCieDKGArciqIA).)

On discord (in [this thread](https://discord.com/channels/508357248330760243/978732143800893511) and [this thread](https://discord.com/channels/508357248330760243/978802104850346046)), @webstrand very kindly helped me work around this problem through judicious use of interfaces. But it ultimately leads to needing to declare _three_ interfaces per class, with two copies of the inheritance hierarchy. It seems a shame that I can't just use the `class` keyword, which correctly reflects the actual structure I'm trying to use, just because I don't have a way to actually talk about the type of a generic class.

Specifically, when I have a three-level hierarchy, this is the best I can do:

```ts
interface A<T> {
  brand: T;
  a(): void;
}
interface ACtor<T> extends AStatic<T> {
  new (): A<T>;
}
interface AStatic<T> {
  a_s(): void
}

interface B<T> extends A<T> {
  b(): void;
}
interface BCtor<T> extends BStatic<T> {
  new (): B<T>;
}
interface BStatic<T> extends AStatic<T> {
  b_s(): void;
}

interface C<T> extends B<T> {
  c(): void;
}
interface CCtor<T> extends CStatic<T> {
  new (): C<T>;
}
interface CStatic<T> extends BStatic<T> {
  c_s(): void;
}


function factory<T>(brand: T) {
  let AImpl: ACtor<T> = class {
    brand = brand;
    a() {}
    static a_s() {}
  };

  let BImpl: BCtor<T> = class extends AImpl {
    b() {}
    static b_s() {}
  };

  let CImpl: CCtor<T> = class extends BImpl {
    c() {}
    static c_s() {}
  };

  return {
    A: AImpl,
    B: BImpl,
    C: CImpl,
  };
}
```

([Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIIB4AqA+ZBvAKGWQCMo4QATALmUwG4jk4AKASloDcB7YSxgL4FQkWIhSoAwmG5QsuCAA9IVAM5oAymDhhgCefiYgIAd2TtaGHIOHho8JJu279OQ8TgB9VReQ8+BEK2og4oAEIGSiqU6la4hMQkvv78gcH24shh0rKRyhBqWVo6egYJyMZmvhHWaSIZjmHFLnnRsc2lbuUk3sm8qUH1Yo6SrQUxWWVMCH18NkOhyJI5cm5R4+qSHa7xRqbmHEvy83bDKFvOnQr5hU2XO+7ICL2HKTYEBDAAriAIutwgZAOGRQACe8hYZAoNDobEeABsIGA0ABJAC2AAd4ZYVgYALxPeFwVTqcqJchUZAEqFURjEDzsfBCenIVT3ZgvJlMASMJiI5FhdFY2jZEH4wnE9TrQqoIXwx6JRl4Zn0tklBCkTnK7m84j8pZy2jLMVuAkIIkk5DSiaCzHyslPJUq4hqlxPLUqnkfYhQJFfKCAh2oSxygA0TGIYRFYYjSyNMeIXoEQA).)

That's a lot of repetition.

## 💻 Use Cases

This would be useful anywhere you're working with generic classes.

**Comment by whzx5byb** [comment]
In 4.7.0 beta you could write `return klass as typeof A<T>`. See https://github.com/microsoft/TypeScript/pull/47607.

**Comment by bakkot** [comment]
Nice! That's exactly the thing I wanted.
