### ISSUE TITLE
Error while Compile TS 1.4 on TS 1.5 

### ISSUE THREAD

**Issue by mt406** [Microsoft/TypeScript#4924]
I wonder if TS has backward compatibility as when I am trying to compile my older version ts files (ts 1.4) on TS 1.5 compiler , getting a lot of errors

**Comment by plantain-00** [comment]
You may show some messages of the errors.
And you can ask this at [gitter](https://gitter.im/Microsoft/TypeScript) to get faster answers.

**Comment by mhegazy** [comment]
Here is a list of changes between versions that may cause errors: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes

**Comment by mhegazy** [comment]
we will need the error messages to be able to help more though. and as @plantain-00 noted, SO or gitter would be a great place for these questions.
