### ISSUE TITLE
Embed media

### ISSUE THREAD

**Issue by Klaider** [microsoft/TypeScript#49249]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- include bytes
- embed file

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Similiar to Rust language (`std::include_str!` and `std::include_bytes!`) and ActionScript (`[Embed]`), allow to load static content, such as plain text and binary files, via a context keyword `embed` (it's contextual because it's followed by a string literal).

For example:

- Plain text (UTF-8)

```typescript
let x = embed './thing.txt' as 'text/plain';
typeof x; // 'string'
```

- Binary

```typescript
let y = embed './thing.bin' as 'application/octet-stream';
y.toString(); // '[object ArrayBuffer]'
```

- Plain text (omiting MIME type)

```typescript
let z = embed './thing.txt';
typeof z; // 'string'
```

More information on [es.discourse.group](https://es.discourse.group/t/embed-media-expression/1352).

## 📃 Motivating Example

This feature allows embedding content without the use of HTTP request or file system, and also helps skipping unnecessary parsing of content (for example, when embedding JSON, it doesn't need to be parsed by the compiler). So that means that just the `import` directive doesn't work efficiently.

## 💻 Use Cases

I might use this in a library. Workaround is to use `import` in general, but it doesn't work with binary and is inefficient for JSON, or `import` actually merges the content with the final JavaScript output, being inefficient as well.

**Comment by jcalz** [comment]
How is this not a runtime feature?

**Comment by fatcerberus** [comment]
> closed this as completed

Why do I feel like GH's new issue closure reason feature is getting in the way more than it's helping?

**Comment by RyanCavanaugh** [comment]
If there's one thing us maintainers have been clamoring for, it's yet another bit we have to set when
