### ISSUE TITLE
Property 'zoom' does not exist on type 'CSSStyleDeclaration'

### ISSUE THREAD

**Issue by milyzc** [microsoft/TypeScript#49253]
# Bug Report

### 🕗 Version & Regression Information

- Typescript version: 4.6.4

### 💻 Code
```ts
const element = document.createElement("div");
element.style.zoom = "xx%"; // error here, property doesn't exist
```

### 🙁 Actual behavior

Since the property all actually exist on style, should be an option.

### 🙂 Expected behavior

TS compile error: Property 'zoom' does not exist on type 'CSSStyleDeclaration'
It works as expected by using // @ts-ignore before the line.

**Comment by MartinJohns** [comment]
It's not added because it's not standard.

https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

> **Non-standard:** This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

**Comment by GreyTeddy** [comment]
As of today, it seems like it has been introduced on [version 126 of Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom#browser_compatibility)

![image](https://github.com/microsoft/TypeScript/assets/38925592/d640947e-4c5a-45ff-b6b0-22010290338c)

I have also tested this today, after upgrading to version 126.

**Comment by ryanswanson** [comment]
Please consider re-opening this issue as the standards have shifted back and CSS zoom now has full support across recent versions of major browsers ([Baseline 2024](https://github.com/web-platform-dx/web-features/blob/main/docs/baseline.md)).

**References**

**CSS zoom (MDN)**: https://developer.mozilla.org/en-US/docs/Web/CSS/zoom
**CSS zoom (caniuse)**: https://caniuse.com/css-zoom
**Chrome 128 (Aug 20, 2024)**: https://developer.chrome.com/release-notes/128
**Standardized CSS zoom (Chrome Platform)**: https://chromestatus.com/feature/5198254868529152
**DOM APIs affected by CSS zoom**: https://docs.google.com/document/d/1AcnDShjT-kEuRaMchZPm5uaIgNZ4OiYtM4JI9qiV8Po/edit
