### ISSUE TITLE
Question: Any way to get result/merged interface

### ISSUE THREAD

**Issue by lazutkin** [Microsoft/TypeScript#4926]
I often want to get a form of interface after all declarations merging and `extends` clauses applied to it. That is I mean to get a final form of an interface. It would be very useful for documentation writing or communication with teammates.

So are there any way to get such info?

**Comment by mhegazy** [comment]
how do you want to represent this? is it typescript still, or jsdoc for instance? if it is the earlier, why is not looking at interface hierarchy sufficient? if it is the later, have you considered using the [compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) to achieve this?

**Comment by DanielRosenwasser** [comment]
Pinging @lazutkin - can we close this?

**Comment by mhegazy** [comment]
Closing. please reopen if the issue has not been resolved.
