### ISSUE TITLE
Typescript 4.7 thinks keyof interface may contain a symbol

### ISSUE THREAD

**Issue by bschlenk** [microsoft/TypeScript#49261]
# Bug Report

### 🔎 Search Terms

Implicit conversion symbol fail runtime

### 🕗 Version & Regression Information

- This changed between versions 4.6.* and 4.7.*

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/JYOwLgpgTgZghgYwgAgApQPYAdpgJ4A8AKgHzIDeAUMsiHALYQBcyA1hHhjMkZQL6VKoSLEQoiAC1ABzAIIVqyOCwDOYKDMUAjVes0Ch4aPCQ8pIaQCEFNBLo0XFAE3v7BMAK4gEYYBhDIAGLAADYixMgQAB6QIE4qZjLyAD6JFpYkABRYmDhQvhAqLOjYuISkANoAugCUNshQEGAeUAE5pfnAhQB09HBYmdm5ZXUAvGQABqBYHmAAtAAk5O15+N10jHwTNfyUQA)

### 💻 Code

```ts
interface Property<T> {
  name: keyof T
}

interface ThingA {
  a: string
  b: string
}

interface ThingB {
  c: string
  d: string
}

function Filter<T extends ThingA | ThingB>(properties: Property<T>[]) {
  return properties.map((property) => `input-${property.name}`) // <-- Implicit conversion of a 'symbol' to a 'string' will fail at runtime. Consider wrapping this expression in 'String(...)'.(2731)
}
```

### 🙁 Actual behavior

Typescript thinks that `property.name` here may be a Symbol. I guess maybe this makes sense since `T extends ThingA | ThingB` wouldn't prohibit a `ThingC` interface that extends ThingA with a symbol property. But I'd expect this new error to pop up in a _lot_ more places in my codebase, but I only see it in this one spot.

I'm not sure in what circumstances this error is triggered, or how to work around it. I'd rather not add `String(...)` around the property because that's unnecessary extra runtime code.

### 🙂 Expected behavior

Because this doesn't fail in TS < 4.7, I'd expect it not to suddenly start failing.

**Comment by RyanCavanaugh** [comment]
This is a correct error because this function crashes on legal inputs:

```ts
const m: { a: string, b: string, [Symbol.iterator]: ""} = { a: "", b: "", [Symbol.iterator]: ""};
Filter<typeof m>([{name: Symbol.iterator}]);
```

```
Uncaught (in promise) TypeError: Cannot convert a Symbol value to a string
    at <anonymous>:2:59
    at Array.map (<anonymous>)
    at Filter (<anonymous>:2:23)
    at <anonymous>:5:1
```

**Comment by bschlenk** [comment]
Thanks @RyanCavanaugh that makes sense! And thanks for the `string & keyof T` suggestion Martin, that works for me.
