### ISSUE TITLE
Circular reference error for some structures involving Array<T> and the tuple spread operator

### ISSUE THREAD

**Issue by hamish-milne** [microsoft/TypeScript#49263]
# Bug Report

First off, I'd like to apologise for torturing the TS type system so completely!
(For context, I'm creating a system in which stateless function objects are defined in one file, and are referred to in a serializable way by using nested arrays, e.g. `["Add", [5, 4, ["Negate", 3] ] ]`. I've made the names generic in the code sample, but the goal is essentially a type-safe nested array structure)

### 🔎 Search Terms

circular, array

### 🕗 Version & Regression Information

- Issue present on 4.7.0-beta, 4.6.4, 4.5.5, 4.3.4
- Issue partially present on 4.2.3, 4.1.5, 4.0.5 - see code sample for details
- Earlier versions don't support these structures at all

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.0-beta#code/PTAEDEEsA9QQQFygEoFMC2B7AbpAdgOagDkq0ALqngCYDOoArngNZ6YDueA2gLrECwAKHIBPAA6oImTAB4ACgEMATgvT0ylGvSasO3HgD5QAXlABvIaCuhoSRSrUBuUCAgxQAISQBhABYLCfCJie1VaYlByTFBaTHRUcl8g0FQAG1pUIQBfRyEhUQlPZXllMJSKKjpGFjZOXiNTcGkZS2tXKFhvJDQsXEJI30laMSVUBWpQTAkVKKVWqy4AOmXQtQAaUABFBmg4JRURHiEDXMF88UkPBQAvE3N50AAzaSQrpRl67LzhC6LyO4sgmsLjAHVAABEkAA5TD-Bi0ZLEfCPVBKCKDUYPLjMVAiUD4UA4kSYR5Fa48V43bG4njlTRVJqyZGo0CrWgGB7AgD8kSUDEyQOB1iQjwU6VQpxy3wKkm2sFMV3I1OJpMVPFOQlc3gUGVAAEYfJAlABjBipZSgUYo0Z4Y2SVFKTBKACEmrAMq2Oz2Bzu3oUIhkcpO3y1OskACZDSazRaraiqHaUvsnfi8KAACyLADMkzw7GUdA2ACMGP92E7mPQCZmAAyRaKZ8Nu8piJ3-fCUJSixNyv14jSVeh9wM7IyA1xZENgbW6rNIADqFfoAFoUtgqKB2IM06h10o8fF0EWWSSSMOgxFIPRjVNIKgJvhXYIO6ju7Kvft-fdBQsiUg8AwR6ohSnrQJKQA)

### 💻 Code

```ts
// Fix A: Removing 'extends unknown[]'
type Foo<Params extends unknown[]> = {
    x: Params; // Fix B: Changing 'Params' to something else
};

type Bar<Params extends unknown[]> = Foo<
    // Fix C: Removing the spread operator
    [...Params, QuxArray]
>;

type Baz = {
    foo: Bar<[]>
}

type Bat = {
    // Fix D: Not using 'infer' here
    [key in keyof Baz]: Baz[key] extends Foo<infer Params>
        ? true
        : false;
};

type Qux = Bat[keyof Bat];

// Case 1: Circular reference error!
// type QuxArray = Array<Qux>;

// Case 2: Circular reference error in 4.3 onwards, but works in 4.0 to 4.2
// export interface QuxArray extends Array<Qux> {
// }

// Case 3: Works - even when every member of 'Array<Qux>' is copied in!
interface QuxArray {
    [key: number]: Qux;
}
```

### 🙁 Actual behavior

A circular reference error of some description when Case 1 or Case 2 are uncommented.

### 🙂 Expected behavior

No errors :)

I've noted in the code sample places where modifications can be made such that the code compiles, in a way that doesn't remove the inherent circularity of the type structure. I don't know if there's something about Case 3 that makes it work, but it seems at the very least pretty unintuitive why some structures work and some don't.

**Comment by RyanCavanaugh** [comment]
Supporting circular types is done through great effort -- we have many safeguards in place to try to prevent witnessing a type during its creation in a problematic way. It's not always possible to cover every possible way that a circularity might occur, as observed here. If you hit one of those cases it's generally possible to restructure the code slightly to avoid it.

This support doesn't cover 100.0% of cases, and the exact boundaries of where it stops working aren't easy to describe.
