### ISSUE TITLE
There is no wrapping in --help message

### ISSUE THREAD

**Issue by esdnm** [microsoft/TypeScript#49278]
`Version 4.1.3`

Help message should (or must) be warped, either statically at a reasonable width like 80 to 100 char/line, or dynamically by examining the terminal width.

**Comment by MartinJohns** [comment]
1. You forgot to fill out the issue template.
2. The help output of the CLI got a major rework in version 4.4 and correctly wraps the lines, depending on the terminal width.

**Comment by esdnm** [comment]
> 1. You forgot to fill out the issue template.

I didn't forget. I just didn't do it.

**Comment by esdnm** [comment]
> 2. The help output of the CLI got a major rework in version 4.4 and correctly wraps the lines, depending on the terminal width.

4.4? Are you guys on drugs?

**Comment by fatcerberus** [comment]
> 4.4? Are you guys on drugs?

what

**Comment by Josh-Cena** [comment]
News from earlier this week was 4.7 just released: https://github.com/microsoft/TypeScript/issues/48027

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
