### ISSUE TITLE
Array.prototype methods return wrong type for extended arrays

### ISSUE THREAD

**Issue by lukjoh** [microsoft/TypeScript#49286]
# Bug Report

### 🔎 Search Terms

array prototype return type
array filter wrong return type
Array.prototype

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Array.prototype return types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

https://www.typescriptlang.org/play?ssl=9&ssc=66&pln=9&pc=1#code/MYGwhgzhAEByCuBbARgUwE41QDwC6oDsATGAQXXTAE8AeApNdAPmgG8BYAKAEgAHdAJYFcACgCUbLt27AA9gQiyQqAHQhZAcxG4AFgIhipAXy4nOy3NHooMEAIzQAvFdQB3OA1siADABpodv4ATIbmqJbWjBBBTlaemHYqECACwKgidhLQAPTZ0ABSYABukMCCvJbo4fDoBNC4VLyo0PrQAEQINpht0MjwlgAqjagQZQIV0FW4NXUNTS0wbZEYANoAum1cy5hBKvxCohK50AN6MK6y6ADWMELQJQQCIOAFxaXluCpccgpKqupabbRFoKXBgAhpWQAMw8XQM0ByeTauHQ8FQPTuhRKow+QA

### 💻 Code

```ts
class Numbers extends Array<number> {
   print() {
      console.log(this)
   }
}
let numbers1 = new Numbers(0, 1, 2)
let numbers2 = numbers1.slice(1)  // Javascript return type is "Numbers" but Typescript return type is "number[]"
numbers2.print()  // This works in Javascript but Typescript says: error TS2339: Property 'print' does not exist on type 'number[]'.
console.log(numbers2 instanceof Numbers)  // "true" in Javascript
```

### 🙁 Actual behavior

Typescript says: error TS2339: Property 'print' does not exist on type 'number[]'.

This is wrong because "new Numbers(0, 1, 2).slice(1)" should return type "Numbers" not type "number[]"

This is also applicable to the ".filter()" method and probably others.

### 🙂 Expected behavior

Return type should be "Numbers" not number[] because this is true for vanilla Javascript.

The correct return type allows method chaining.

**Comment by RyanCavanaugh** [comment]
The only way to fix this would be to make the array methods generic in a way that would incur a very large performance penalty in all array calls, but subclassing array like this is very rare and you can shim out the types yourself if this is idiomatic in your codebase.

**Comment by lukjoh** [comment]
> The only way to fix this would be to make the array methods generic in a way that would incur a very large performance penalty in all array calls, but subclassing array like this is very rare and you can shim out the types yourself if this is idiomatic in your codebase.

Ok. Thanks.
Do I have to close this issue then?
