### ISSUE TITLE
Conflict between @types/node and lib.webworker.d.ts: AbortSignal

### ISSUE THREAD

**Issue by swiing** [microsoft/TypeScript#49283]
# Bug Report

### 🔎 Search Terms

`AbortSignal`

### 🕗 Version & Regression Information

- This changed between versions 4.6 and 4.7

### ⏯ Playground Link

See Code below instead.

### 💻 Code

The issue arises when used in combination with `@types/node`:
```sh
npm init -y
npm install --save-dev typescript @types/node
```

```ts
// index.ts
// Anything will demonstrate the issue
const dummy = 1;
```

Including the library `WebWorker` results in error:
```sh
./node_modules/.bin/tsc --lib WebWorker  index.ts
```
### 🙁 Actual behavior

```sh
node_modules/@types/node/globals.d.ts(72,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
```

### 🙂 Expected behavior

Code to compile without error.

### Additional information

This is not brand new. There has been [47507](https://github.com/microsoft/TypeScript/pull/47507) and [48580](https://github.com/microsoft/TypeScript/pull/48580). Those PRs manually edit the .generated.d.ts files, which seem to be discouraged [here](https://github.com/microsoft/TypeScript/tree/release-4.7/src/lib#generated-files).

As commented [here](https://github.com/microsoft/TypeScript/pull/48580#issuecomment-1113095216), the error disappears if I comment out this [line](https://github.com/microsoft/TypeScript/blob/6e0328af6aef8ae85778d142336296e4ae02e9ee/lib/lib.webworker.d.ts#L754).

**Comment by Josh-Cena** [comment]
You should not compile a file with both Node and worker defs—you can disable the Node types with `types: []` in your tsconfig.

**Comment by swiing** [comment]
Thanks for the tip with `types: []`. It does solve the issue indeed (also adding e.g. `es2015` to the list of `lib`, to make sure the basic types are defined).
