### ISSUE TITLE
Add Navigation API

### ISSUE THREAD

**Issue by bershanskiy** [microsoft/TypeScript#49281]
# Suggestion

## 🔍 Search Terms

Navigation API, Navigation, Chrome 102, Chromium 102.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Extend type definitions with declarations for Navigation API.

## 📃 Motivating Example
The following code is considered invalid right now:
```
window.navigation.addEventListener("navigate", console.log);
```
instead one needs to write this:
```
(window as unknown as { navigation: EventTarget }).navigation.addEventListener("navigate", console.log);
```

## 💻 Use Cases
Develop software for Chrome/Chromium 102+.

**Comment by MartinJohns** [comment]
From https://github.com/microsoft/TypeScript-DOM-lib-generator:

> If there is, see the browser compatibility section and check whether it's supported by two or more browser engines. (Note that Chromium-based browsers use the same browser engine and thus support from them counts as a single support.)

This feature seems to be supported only by a single browser so far.

**Comment by bershanskiy** [comment]
Thanks for that comment, typescript-bot also left two other relevant comments in #49282 directly.
