### ISSUE TITLE
typescript-bot should close issues as "not planned" instead of "completed"

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#49287]
sorry if i'm raising this in the wrong place

https://github.com/microsoft/TypeScript/issues/49227#issuecomment-1139989960
![image](https://user-images.githubusercontent.com/57028336/170806945-e44cf18c-61d8-45c3-9721-9bee91e67408.png)

there's now an option to pick the reason for closing an issue, which the bot should probaly use when closing issues:

![image](https://user-images.githubusercontent.com/57028336/170806900-4b57cdcf-cae4-4937-8922-7b9b1788bce1.png)

# search terms

not planned completed typescript bot

**Comment by RyanCavanaugh** [comment]
We didn't write this part of the bot and I can't find the code for it to update it myself -- I've pinged the owners and have asked for the ability to configure it (or at least set the default to "not planned", as I wish the GitHub API had done).

**Comment by jakebailey** [comment]
This is now fixed as of #54566, where GHA + the `gh` CLI are used to auto close issues.
