### ISSUE TITLE
Complex Generics and conditionals

### ISSUE THREAD

**Issue by KirAmp** [microsoft/TypeScript#49295]
# Bug Report

### 🔎 Search Terms
`generic` `generic expressions`

### 🕗 Version & Regression Information

All tested versions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgggHgFAIKwH0BxAUQDkyAlASQGEEBTADwiYDsATDTKGAJ7ZgHAQD4EAHwTUmsAPZQu2SFACWHAOYAaBCPEIAvDLmLlqjTr2ixuCQG98hBR1UBXeIoAUXNWAAOqAIAKgL+TABcxORUdIys7Ny8-MBC+hIA-AgA5MApAtkIUdmcEGoQBQCUCI5OBAC+uI24KGgYAELY7aSUNAzMbJw8JgpKKtCWuulGI2bj6lpTNhIJQ7xdPbEMDnVI8q7QHhDe1Y6E5whgbuFQXiUcZRXZlQDcu42NQA)

### 💻 Code

```ts
class A<
    A_GENERIC extends Array<any> | Record<string, any> = Record<string, any>
> {
    constructor(displayType: A_GENERIC extends Array<any> ? 'array' : 'entity') {

    }
}

class B<B_GENERIC extends Record<string, any> = Record<string, any>> extends A<B_GENERIC> {
    constructor() {
        super('entity');
    }
}

```

### 🙁 Actual behavior

TSError: 
```
Argument of type '"entity"' is not assignable to parameter of type 'B_GENERIC extends any[] ? "array" : "entity"'.
```

### 🙂 Expected behavior

No TS Errors because B_GENERIC extends {}

**Comment by MartinJohns** [comment]
It's a design limitation. See https://github.com/microsoft/TypeScript/issues/34634#issuecomment-545415219.

**Comment by KirAmp** [comment]
@MartinJohns ohhh, thanks! You don't know any workarounds for this?
