### ISSUE TITLE
Not valid when inferring return value types from function parameters of nested array types

### ISSUE THREAD

**Issue by fxioi** [microsoft/TypeScript#49296]
# Bug Report

A function that passes in a custom schema that constrains the values of the properties of the returned object.

But when the parameters are nested arrays, the type constraint does not take effect.

### 🔎 Search Terms

nested array, nested tuple, type Inference, type constraints

### 🕗 Version & Regression Information

v4.6.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIhC2B7A8lAvFAShAxogTgCYA8AzsPgJYB2A5gDRTlV1QA+sCKA2gLoB8AbgBQoSFADKEADa5gEnAAsEAQwAq4aBgAUzGrXZRdFfYamyc8pao2QAlHwe8RozVDUqDGAN7CoUSkIALiYTOhF-ahV4CBC9cL8oQghSHCowYEpEajiw2gioNIgVYAhCAEFgXJZ84QBfFzFoAAVEcnQoX39A6v0CzOBZXoT-ACNEQhBh2v9gT1IQj1o+EQbhYTxqdrnaRc8OroDgqAAiFQAzaQBrACtzk-pEqJiQk6bU9OAHxOSPygysjlEv4TrYIApPgFSFAVFAmoQmABXSD4UgQYBQRDnKAAKRUADcVBD-hjgIoSoVEPAwJRZNDgIgoGBpCoaLiCUS0iTvv4iiUypVXgAmAAMooAtCKAIySqVqEUioIKpUigB0CpFAC1vmsNtl2mA2lUoK12j5Ej1ThdrnceXDKINYqdTaSHbI7eNJq8XVBPSA7TsFlBuMDOqHusczpdbvdHv541Bnk63po-hk7QnflyAdkguH46DNMSMlCYXDNAjSMiIKj0ZjsXjCcXSeSMXhqbSUnDGczWdR2U3s184wnCvhiqUKsaTqKJdLZfLFcqFeqFdqR-46iPeI9dQB6Pdhg-xy3xWrH2Zup1nkQX30TKahGq3w+zeZ7ZbOYTHtbHtBofhv0PbgAHJAhAxgQIGWQIKgEC-Vg0DA0QsDCFgkCk3QrNPkBdC+UnSoQN4YjXHENREAUZR4HUTRiDUKAIAAD1KahCGhOAkGQfgOnKfB8BUEBiESQ5-G4ABpAJ+yuCAQCxdxeBCCSmJYtin30fMAH53HE3gGOYiBWOhM9838LSxJMqBFh0vSVOhbQaHOGtYGQJwLK0mBUGUgzVI4lALNM4MxMYcjKJsWiPP4Xh-MsxMIHxGsLJCag4oS0cYuS+L8AKOpuGk2TsTUKKhHWY8AHF0QAORSSdQuo4huBOQIHmDN55mahqmsYE4kxOYid1OQMTkAv8AKAlrOtOHqoqaKByuAKryDKWqVCE-wJBs7zoXMORlrBEclP0wy1LoYRuIwdavKO+zqEc-AoAASVcgL7o2o7uAcpz7qlRgPru+6hSihMtK+17VPMtLgaFUGtpkHbrGosE3IeoVEtizL8ySlL8FDTH0f8XGa0aNxmkoHArgAIRAZa6OhzhOMYABVWmQvhmjIDo-gzrDUSJLZJnLtU67bqgBmpSe+MtNF2njIhkWpQxuXafem6nIZoVGG2yxds0QHR0lqGBaMvIkbV1GMtS0cCexhMrYU7SxN0w3jtoUMtLUHScftx3DsF36oBcvhXf92nfOQTSTVJimqdZ4hkEYOaFpqmOGcYMTOcDtKrc982svqFxjwAdwIaSEQLh1FEQREMXORFqEsQFSJaI1kGoaQQHuhEMBJsnKepl1GA6wh2ta2hSGHibuuiCBeuI4rhBruvMmyJlI4AMVrnAaad0PGeZijWbBDn+G0RJEFGG5FhHVIqJUEIGeEOwQm7qPqbURnuMOMl8EQAvJsQDEQB1koNSWQMRqCThOKsdYmx2jjlIFKDoNIybrzrtoQ05AB6NSHl1P0vU7AiDgVKVUgQXzuGUFAGIpBSCeGgG8K8SREBdmoP-PSlByAnCgAXFQRlEQ4BwCkUgNdpBtySGw3sgDCDCEIaqaCEBBBQGPMgcy0i-QuBgRiOBUMMBIKuCgnAaCjSYImg1QamCprEXwVIlIQpiGEFIQAUUYpASwMJ+w1m-ndSh1DaAQCsaQGxsj5GKMQGAUgY1HHOIxCoNxfECAUIETQvxAT5jcBFLwWxCjDzIBCWEzRMiUlpNVEmIAA)

### 💻 Code

```typescript
function pickFunc<T extends DemoO, U extends ToSchemaType<T>>(
  obj: T,
  schema: U
): PickBySchema<T, U> {
  throw "not yet implemented";
}

const res = pickFunc(post, ["id", "body"]);
res.id;
// The message "title does not exist" was successfully displayed
res.title;
res.body;

// When using nested schema, the type constraint does not take effect
const res = pickFunc(post, ["id", ["tags", ["name"]]]);
res.id;
// Expect an error message
res.title;
// Expect an error message
res.tags[0].id
res.tags[0].name
```
I created the `PickBySchema` type to generate attribute field constraints for the object.

It is effective when used alone.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/7747725/170852945-3518a120-a2c1-41a8-93d6-37e4a0808cfd.png">

```typescript
type PickBySchema<T extends DemoO, U extends ToSchemaType<T>> = {
  [K in U extends (infer U1)[]
    ? U1 extends string
      ? U1
      : U1 extends [infer U2, SelectSchemaType]
      ? U2 extends string
        ? U2
        : never
      : never
    : never]: T[K] extends string
    ? T[K]
    : T[K] extends (infer O)[]
    ? O extends DemoO
      ? PickBySchema<O, GetNestedSchema<U, K>>[]
      : never
    : never;
};

type PostOnlyId = PickBySchema<Post, ["id", ["tags", ["id", "name"]]]>;
```

### 🙁 Actual behavior

When passing nested arrays in function parameters, the return value does not get the expected type constraints

### 🙂 Expected behavior

When passing a one-dimensional array or a nested array as a function parameter, the return value is expected to be bound by the specified field

**Comment by jcalz** [comment]
That's quite a long reproduction; could you demonstrate the issue with less code?  

I think this might be related to #30680; the compiler is inferring wider array/string types than you want.

**Comment by RyanCavanaugh** [comment]
This repro is long enough that it's unlikely to represent a bug in TypeScript. If you can provide a shorter one (5-10 lines is sufficient to reproduce almost any defect) we can investigate, but we don't have the resources to dig in to things this large.

**Comment by fxioi** [comment]
First of all, thank you very much for your replies, and I apologize for providing a slightly longer reproduction. Since this problem was discovered during debugging nested arrays, I'll close the issue before I provide a parsimonious reproduction.
