### ISSUE TITLE
Arithmetic logic support

### ISSUE THREAD

**Issue by szeredaiakos** [microsoft/TypeScript#49292]
# Suggestion
Should be self-explanatory. But:

In short:
`aNumber += (a<b) * 12 - (a>=b) * 14 `
Is significantly faster than:
`if (a<b) { aNumber += 12} else {aNumber -= 14}`

The first method ends up in error yet most major languages and runtimes handle it correctly.

## 🔍 Search Terms
arithmetic logic
ALU
arithmetic logic unit
performance

**Comment by MartinJohns** [comment]
This is not self-explanatory at all, we're not mind readers. And TypeScript officially has no spec, so there's nothing to update.

**Comment by szeredaiakos** [comment]
> This is not self-explanatory at all, we're not mind readers. And TypeScript officially has no spec, so there's nothing to update.
> 
> A wild guess is be that you want #26382.

It is unrelated.
Apparently is not so explanatory. Updating...

**Comment by szeredaiakos** [comment]
> Unfortunately you still didn't fill out the issue template after updating. :-(
> 
> From that brief example it now looks like a duplicate of #27501. This is intentionally not supported: [#27501 (comment)](https://github.com/microsoft/TypeScript/issues/27501#issuecomment-426342152)
> 
> It works fine if you add an explicit type conversion using `Number()`, which also makes your **intent** much clearer in the code.

Yes, casting is competitive, not quite the same tho. We may not argue about the clarity of code which uses logic arithmetic :).
Yes, thx, Martin!
Yes, this is a copy of #27501
