### ISSUE TITLE
Module: Node16 in Typescript 4.7 outputs CommonJS code in "type": "module" package

### ISSUE THREAD

**Issue by jonasb** [microsoft/TypeScript#49291]
# Bug Report

### 🔎 Search Terms

* node16 ESM output
* module node16 results in CommonJS output

### 🕗 Version & Regression Information

- This is unexpected module output from compilation
- This was first observed in version 4.7.2 (and is the same in nightly Version 4.8.0-dev.20220528)
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ESM and node16
- I was unable to test this on prior versions because "node16" was introduced in 4.7.2

### ⏯ Playground Link

[Github link with relevant code](https://github.com/jonasb/typescript-error-repro/tree/typescript-4.7.2-esm-node16)

### 💻 Code

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "module": "node16"
  }
}
```

`package.json`:
```json
{
  "type": "module"
}
```

`main.ts`
```ts
import { equal } from 'node:assert'

equal('Hello', 'He' + 'llo')
```

`main.js`
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const node_assert_1 = require("node:assert");
(0, node_assert_1.equal)('Hello', 'He' + 'llo');
```

### 🙁 Actual behavior

The output is CommonJS code. When running the compiled file with Node I get:

```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'typescript-error-repro/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

### 🙂 Expected behavior

I expect the output to be ESM code when setting "module": "Node16" in `tsconfig.json`  and "type": "module" in `package.json`.

**Comment by Jamesernator** [comment]
I'm not seeing the same behaviour trying to replicate this.

I notice in your issue comment you say:

> typescript.json:

This should be `tsconfig.json` which you do mention later, so I'd check that your file names and TS versions are all correct.

**Comment by jonasb** [comment]
@Jamesernator Thanks for looking into it. Did you try my repro: https://github.com/jonasb/typescript-error-repro/tree/typescript-4.7.2-esm-node16 ?

(That was a typo, have changed `typescript.json` to `tsconfig.json` above)

**Comment by Jamesernator** [comment]
> @Jamesernator Thanks for looking into it. Did you try my repro: https://github.com/jonasb/typescript-error-repro/tree/typescript-4.7.2-esm-node16 ?

It's because you're using `"moduleResolution": "node"` rather than `"moduleResolution": "nodenext`". If you specify `"moduleResolution"` it always wins over `"module"`, in general unless you actually want a differen `"moduleResolution'` value there's not really any reason to specify it when using `"module"`.

**Comment by jonasb** [comment]
@Jamesernator Thanks! That did the trick! Thanks for taking the time! 🙇
