### ISSUE TITLE
Feature request: static var

### ISSUE THREAD

**Issue by errorx666** [Microsoft/TypeScript#4930]
I would like `static var` within a function to create a variable scoped outside the function which can only be accessed from within the function.  The intent is to act as a variable within the function that retains its value between invocations.

An example is below:

Input:
```js
function newId() {
    static var id = 0;
    return id++;
}
```

Desired compiled output:
```js
var newId = ( function() {
    var id = 0;
    return function newId() {
        return id++;
    };
}() );
```

Usage:
```js
newId(); // 0
newId(); // 1
newId(); // 2
```

I don't believe `static let` or `static const` make sense or would be useful; `static var` should be sufficient.

**Comment by GoToLoop** [comment]
Very good syntactic sugar idea for declaring closures!
Indeed closures are `static` in nature since there's only 1 copy of it and it's scope shared.
Although I don't see why a scope couldn't be `let` or `const` since JS allows those to be closures as well.

**Comment by errorx666** [comment]
@GoToLoop Thank you.
I suggested not supporting `let` and `const` because it occurred to me that block scoping could be problematic for a variable that is actually scoped outside (and therefore across) the function.  This might be solvable with name mangling (as when block-scoped variables compile down to ES3 or ES5) but I thought it might be easier to get a feature passed if the use-case was kept as simple as possible.  Beyond that, I really couldn't think of a place where a static variable would be useful scoped to a block within a function.
It would be really useful for methods as well, but unfortunately due to the prototypal nature of methods, a static var would end up being shared across all instances (just like a static property).  This might be useful for some scenarios, but none I can think of.

**Comment by GoToLoop** [comment]
All those 3 declaration styles: `var`, `let` & `const` create a scope which exists not only for the declared current scope, but for any inner scopes created below them. That's how closure works btW.

And since both `let` & `const` create closures just like `var`, I don't see why they couldn't be allowed.
Even if it might  make the whole feature implementation a little more complex.

Of course `var` is hoisted to the top of the function no matter where it was declared within that.
While `let` & `const` respects the `{}` limits where they're declared in.

**Comment by errorx666** [comment]
The implementation I suggested performs a similar "hoist" as `var`, it just hoists outside the function, inside an implicit closure surrounding it.  That's why it seems to make more sense as with `var`, because the behavior is more similar to how `var` works.

**Comment by GoToLoop** [comment]
Your excerpt but replacing `var id` w/ `let id`:  

```js
var newId = ( function() {
    'use strict';

    //var id = 0;
    let id = 0; // static closure
    
    return function newId() {
        return id++;
    };
}() );

for ( var i = 3; i--; console.log(newId()) );  // 0 1 2
```

As you can see, it works regardless _id_ is declared as `var` or `let`.
That'd the point I'm trying to make that if JS itself allows closures w/ `let` & `const`, they shouldn't be left out!

**Comment by errorx666** [comment]
The example is too simplistic for `let` or `const`, and your example output is ES6.  The example function does not contain any blocks.  Try a more complex example:
```
function newId( flag: boolean ) {
    if( flag ) {
        let static id = 10000;
        return id++;
    } else {
        let static id = 0;
        return id++;
    }
}
```

This would become in ES5:
```
var newId = ( function() {
	var id_1 = 10000,
		id_2 = 0;
	function newId( flag: boolean ) {
		if( flag ) {
			return id_1++;
		} else {
			return id_2++;
		}
	}
}() );
```
You end up with a variable name clash that needs to be resolved by mangling (even in ES6, because these end up in the same scope after hoisting).

**Comment by GoToLoop** [comment]
* Indeed a good point. Although it seems a road block, it's actually easy to solve!
* No matter how many times a closure `static` variable w/ the same name happens to be redeclared, it still should exist only 1 declaration in some scope above them.
* That is, all `static` declarations are erased and hoisted into the parent scope.
* No matter whether they're `static var`, `static let` or `static const`, if they're the same name, they'll all be hoisted as 1 unique closure declaration.
* When emitting for ES6, the parser gonna honor the `static` declaration type.
* That is, if they happen to be `static const id`, it's gonna be hoisted as `const id`.
* Now for ES5 & ES3, that's even easier: they're all hoisted as a simple `var` no matter whether they're happen to be `let` or `const`.

**Comment by RyanCavanaugh** [comment]
While this is clearly useful for the "make a counter" function, it doesn't seem more broadly useful enough to justify adding a new runtime feature to the language. If this actually has a bunch of use cases I'm not aware of, it's probably worth taking it to the ES Discuss group as a proposal for ES7+ since it's a runtime feature rather than a type system feature.

**Comment by GoToLoop** [comment]
Indeed it's just syntactic sugar to make easier to create closures w/ a more simple syntax by declaring a local variable as `static`.

I'm not the OP, but I pretty knew it wouldn't be approved. But I'm not getting the reason given to it.
This feature is costly prohibitive for runtime. In no way I'd ask such feature for the JavaScript language!

This is merely a smart pre-compiler text replacement that only a transpiler such as TypeScript would be fit to do it.

**Comment by RyanCavanaugh** [comment]
If it's as simple as a text replacement, I don't see how it could be prohibitively costly for runtimes to implement.

The set of expression-level features that should exist in compile-to-JS languages that *don't* belong in the JS language itself ought to be very small. Outside of the type system, we have a very short list of runtime syntax sugar: namespaces, enums, class property initializers, and JSX. If there's a runtime feature proposal, the ES committee should usually be the first to take it.

It's been discussed a few times (as early as five years ago) there without any concrete action being taken, which generally confirms that this isn't necessary sugar.

https://esdiscuss.org/topic/static-keyword-from-c-c-as-own-closured-var-declaration
https://esdiscuss.org/topic/static-local-variables

**Comment by GoToLoop** [comment]
I had no idea that would be also an old JS proposal feature.
Nonetheless, I still think doing it at compile time is much more efficient performance wise.
Analyzing the whole scope looking for local `static` declarations and replacing them as 1 parent closure seems a daunt job for me.

**Comment by errorx666** [comment]
@RyanCavanaugh I concede your argument that this feature may not be appropriate for TypeScript.

I do, however, think that the applications are much more broad than "make a counter" functions.  It can be used for any function that maintains an internal state.  (Though some may argue a class would be more appropriate; I like that it can keep its internals hidden from external view.)

For example, memoization:
```js
function fibonacci( n: number ) {
	type Memo = { [ input: number ]: number; }
	static var memo: Memo = { 0: 1, 1: 1 };
	if( n in memo ) return memo[ n ];
	return memo[ n ] = fibonacci( n - 1 ) + fibonacci( n - 2 );
}
```

I respect your decision for not including it in the language, but I think that there are many such uses.   Luckily, the feature request is just sugar.  I can still accomplish this by using a closure.
