### ISSUE TITLE
ternary operator type narrowing is inverted (forced to put not null assertions in the wrong places)

### ISSUE THREAD

**Issue by vedantroy** [microsoft/TypeScript#49304]
# Bug Report

### 🔎 Search Terms

"ternary operator", "type narrowing"

### 🕗 Version & Regression Information

The version of Typescript in my package.json is: `"typescript": "^4.5.4"`, but the bug is in whatever is bundled with VsCode.
My VsCode version is:

```
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```

Seems like it is not fixed on nightly.

### ⏯ Playground Link
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKwA2wDGMCWEAdnALxwDecIAXHEQK4C2ARsFANxyJ2OvtcAzu3wBDTPgBewACYAlUUQDmwOoJhR8yuAF8OAKABmDInkIkoimRCYAKAJSV9cF3CjAYDKCQCyomAAWAHSWRNZ2jgA8cAAMQQCscAD8lNR0MQA03OlZwpriUrIKyqpwAERlunC8DJiY+jr6OMTqcMLYZsR0GB0ExHAAPvS1mGRuVjYO+k0t8ACOAExkzm1YuH1ESUF5YhLS8ooqcACEpOSMdSsuKRRXri4A9A9wAJJtARC1MkQA5PBEwFkcFE9GIAFoLqNRII8hs4AF2MA7vdQio1GtOkRjsdtiICvtiioMsjdCSnq93p9MDJ6ICaSCiODIcCYew4Qj3Hc6FRxiV0b1zLj8nsiodUHppjMiK05ssXO11uYtjt8aKSmQzsNLvcbiTHs83oIPl9aUCGUyRizYeZ4Yi9by0asBcQhbtCgcSsT7i5Gt64OTDcbqb9-nTgaCiBDLdDrf0OUj7tyXKjSgrMdjXaqPUcJUA

### 💻 Code
```ts
export type Selection = { x: number; y: number; serializedRange: string };
function random() {
    return Math.random() < 0.5 ? { x: 0, y: 0, serializedRange: "" } : null
}
const selection: Selection | null = random()

const q2 =
  selection?.serializedRange !== null
    ? {
        // I shouldn't need a non-null assertion here
        range: selection!!.serializedRange,
      }
      // I should need a non-null assertion here
    : {  range: selection.serializedRange };


const q =
  selection?.serializedRange === null
    ? {
        // I should need a non-null assertion here
        range: selection.serializedRange,
      }
      // I shouldn't need a non-null assertion here
    : {  range: selection!!.serializedRange };

```

### 🙁 Actual behavior
I am forced to use a not-null assertion inside of the first part of the ternary expression for `q2`, even though I should not have to because of type narrowing. Furthermore, I do *not* have to use an assertion in the second part of the ternary expression for `q2` even though I should have to because in this branch we know that `selection` must be null.

### 🙂 Expected behavior
The above does not happen.

**Comment by fatcerberus** [comment]
`selection?.serializedRange !== null` will be true if `selection` is `null`, because the optional chain resolves to `undefined` in that case.  Thus if you hit the false branch of the ternary, `selection` must be non-null.

**Comment by vedantroy** [comment]
> `selection?.serializedRange !== null` will be _true_ if `selection` is `null`, because the optional chain resolves to `undefined` in that case. Thus if you hit the false branch of the ternary, `selection` must be non-null.

Ah, I see Typescript is smarter than me 😂
