### ISSUE TITLE
TypeScript 4.7 incorrectly assume type of partial object value

### ISSUE THREAD

**Issue by orad-sa** [microsoft/TypeScript#49319]
Since TypeScript 4.7, the code below fails to build:
```
type MachineType = 'type1' | 'type2'

type MachineOptions<T extends MachineType> = T extends 'type1'
  ? {
      Type1Option: string
    }
  : T extends 'type2'
  ? {
      Type2Option: number
    }
  : never

const machineOptionsByType: Partial<{ [T in MachineType]: MachineOptions<T> }> = {
  type1: { Type1Option: 'blah' },
  type2: { Type2Option: 1 },
}

function getOptionsByType<T extends MachineType>(type: T): MachineOptions<T> {
  return machineOptionsByType[type]
}
```

The returned error is the following:
> TS2322: Type 'Partial<{ type1: { Type1Option: string; }; type2: { Type2Option: number; }; }>[T] | {}' is not assignable to type 'MachineOptions<T>'.
>   Type 'Partial<{ type1: { Type1Option: string; }; type2: { Type2Option: number; }; }>[T]' is not assignable to type 'MachineOptions<T>'.
>     Type '{ Type1Option: string; } | { Type2Option: number; }' is not assignable to type 'MachineOptions<T>'.       Type '{ Type1Option: string; }' is not assignable to type 'MachineOptions<T>'.

If in the `machineOptionsByType` variable declaration we remove the `Partial<..>` - everything works as expected.

My expected behavior is that it will continue to work even when the object is partial, in the same way as it did in TypeScript 4.6 for example.

**Comment by fatcerberus** [comment]
Why is this tagged as duplicate?

**Comment by MartinJohns** [comment]
@fatcerberus He most likely used the [types-not-correct-in/with-callback issue template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/types-not-correct-in-with-callback.md), which he then ignored.

**Comment by orad-sa** [comment]
> Why is this tagged as duplicate?

Not sure, it was done automatically for some reason.

> @fatcerberus He most likely used the [types-not-correct-in/with-callback issue template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/types-not-correct-in-with-callback.md).

Indeed. Should open via bug template instead I guess..

**Comment by orad-sa** [comment]
> This isn't a bug. You could have legally initialized `machineOptionsByType` to
> 
> ```ts
> const machineOptionsByType: Partial<{ [T in MachineType]: MachineOptions<T> }> = {}
> ```
> 
> in which case `getOptionsByType` really could have returned `undefined`

@RyanCavanaugh, not sure why that means it's not a bug.
Even if I change the `getOptionsByType` function return type to `MachineOptions<T> | undefined` - the same error would still occur.
