### ISSUE TITLE
Remove Comments From SourceMaps

### ISSUE THREAD

**Issue by jwilliams-met** [microsoft/TypeScript#49331]
I have the following tsconfig 
```js
    "removeComments": true,
    "sourceMap": true,
```
However the sourcemaps still contains comments. 

REQUEST

remove comments from sourcemaps if removeComments is set to true

**Comment by RyanCavanaugh** [comment]
Source map files are JSON, which doesn't even allow comments. Can you clarify?

**Comment by RyanCavanaugh** [comment]
The option `inlineSources`, which is off by default, controls whether or not there's an inline copy of your sources in the sourcemap. Turn it off if you don't want that behavior.

**Comment by jwilliams-met** [comment]
Hi Ryan, thanks for you work and I appreciate your response on this. 

The option` inlineSources` does not resolve my issue. 

I do not want to inline sourcemaps in a production environment. I would ideally like seperate sourcemaps which are only downloaded when the developer tools are used. This reduces the size of my bundles as much as possible. 

I would like a seperate sourcemaps file but with an option to not include comments. 

I would imagine there would be similary situations where developers would like to use sourcemaps in production, but would like to omit the comments within these files.

**Comment by RyanCavanaugh** [comment]
The level of control over exactly what does and doesn't go into the sourcemap sounds like a job for an external processing tool. This isn't something we would need to do ourselves and would greatly complicate the emitter code.

**Comment by jwilliams-met** [comment]
Is there a general library that you guys use to generate sourcemaps as I could maybe contribute?

**Comment by fatcerberus** [comment]
> I do not want to inline sourcemaps in a production environment.

To be clear, TypeScript doesn't do this unless you actually specify `"inlineSources": true`.  If you're getting the source code inlined into your sources *without* that option being set (as implied by your above comment), something else in your toolchain must be responsible.
