### ISSUE TITLE
Ordering for lib.es6.d.ts should have ES6 components defined first

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4933]
Signature help has become pretty bad for anything that takes objects with symbol methods now:

![image](https://cloud.githubusercontent.com/assets/972891/10033831/b40c82f2-6140-11e5-8513-b1f87385fe4b.png)

This could be fixed if we amended the ordering for lib.es6.d.ts

**Comment by mhegazy** [comment]
so the proposal is to put the es6.d.ts before core.d.ts.

**Comment by mhegazy** [comment]
the change should be limited to JakeFile.js

**Comment by kenhowardpdx** [comment]
Maybe I'm not doing this right, but changing the order of the sources is not making a difference in the order of signature help overloads.

I changed line 167:
```
{ target: "lib.es6.d.ts", sources: ["core.d.ts", "es6.d.ts", "intl.d.ts", "dom.generated.d.ts", "dom.es6.d.ts", "webworker.importscripts.d.ts", "scriptHost.d.ts"] }
```

to be:
```
{ target: "lib.es6.d.ts", sources: ["es6.d.ts", "core.d.ts", "intl.d.ts", "dom.generated.d.ts", "dom.es6.d.ts", "webworker.importscripts.d.ts", "scriptHost.d.ts"] }
```

Any tips you can give?

**Comment by DanielRosenwasser** [comment]
Hey Ken! Can you tell me a little about how you're testing this out?

**Comment by kenhowardpdx** [comment]
@DanielRosenwasser So.... I missed the part about `jake LKG` :) I'll submit a PR.

**Comment by DanielRosenwasser** [comment]
Awesome - somehow I had a feeling about `jake LKG` being a problem. :wink:
