### ISSUE TITLE
Faulty Behavior of Number-keyed Member Inference in Class

### ISSUE THREAD

**Issue by harrysolovay** [microsoft/TypeScript#49339]
# Bug Report

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDqD2AnA1jA3gKGt6AGA3BljsPAHYQAuiArsJUgBQBGAnpQKYQBc0AqgEsylABwBBRIjCsAlNEw5F0SgAsBEANq4AutAC80NpwiFFAXwwWMoSDAAi8LgDl4lecWwEii0hWp0GRBZ2Ll5BYXFJaTkFJWxVdS1dAw0AOnSjLm1THAsrGyhoB2d4AHd3RS8PaF8qWnomTJ5+IVEJKVkKuJryKmgAD31oNIyQiGzqxQTNHSH+nOw8oA)

### 💻 Code

The following produces an implicit any error:

```ts
class DoesNot {
    0;

    constructor(bytes: Uint8Array) {
        this[0] = [...bytes];
    }
}
```

When broken into two steps, it does not:

```ts
class DoesNow {
    0;

    constructor(bytes: Uint8Array) {
        const x = [...bytes];
        this[0] = x;
    }
}
```

Is this the intended behavior?

**Comment by fatcerberus** [comment]
```ts
this[0] = [...bytes] as number[];
```
makes the error go away.  My first instinct is that this has something to do with contextual typing (i.e. the array literal `[...bytes]` is contextually typed by `this[0]` which in turn depends on the type of `[...bytes]`, creating a circularity).  This is not specific to numeric properties; rather it seems to be connected to initializing properties via indexed access where the initializer is context-sensitive.  The same error occurs here:
```ts
class DoesNot {
    x;
    constructor(bytes: Uint8Array) {
        this['x'] = [...bytes];  // same error
        // this.x = [...bytes];  // ...but this would be fine
    }
}
```

**Comment by RyanCavanaugh** [comment]
Scooped by @fatcerberus 

We get the contextual type when doing spreads to determine if we need to apply tuple logic or not. There might be some carve-out we could apply here but I'm not sure what.

**Comment by fatcerberus** [comment]
The thing that confuses me is why `this.x = [ ...y ]` is fine but `this['x'] = [ ...y ]` isn't.  Contextual typing comes into play either way, so I'm not sure why only one produces a circularity.
