### ISSUE TITLE
Syntax Error for `let` var declaration under semicolon-less instantiation expressions

### ISSUE THREAD

**Issue by sosukesuzuki** [microsoft/TypeScript#49348]
# Bug Report

### 🔎 Search Terms

- `instantiation expression semicolon`

### 🕗 Version & Regression Information

- This is a bug of new syntax that is landed in TS 4.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC88CuZgB5oCcCWYA5gHwBQZANgKawBGAhrgNxlA)

### 💻 Code

```ts
const foo = func<string>

let bar;
```

### 🙁 Actual behavior

Syntax error `Cannot find name 'let'.(2304)`

### 🙂 Expected behavior

Parsing successfully

**Comment by ahejlsberg** [comment]
Hmm, yeah, it seems were not doing the right thing when an instantiation expression is immediately followed by a strict mode reserved word (which includes `interface`, `let`, and `yield`).
