### ISSUE TITLE
Promise.allSettled type problem

### ISSUE THREAD

**Issue by dogukanakkaya** [microsoft/TypeScript#49344]
This code gives me some null errors even though i filtered the array. `Type 'HistoryItem | null' is not assignable to type 'HistoryItem'.`
```ts
txDatas.map(txData => txData.status === 'fulfilled' ? txData.value : null).filter(Boolean)
```

And also below code gives me `Property 'value' does not exist on type 'PromiseRejectedResult'.` even though i filtered for fulfilled promise results.
```ts
txDatas.filter(txData => txData.status === 'fulfilled').map(txData => txData.value)
```

**Comment by SPGoding** [comment]
See also #16655 for `.filter(Boolean)`.

**Comment by dogukanakkaya** [comment]
I already have some workaround for those, but i am still not convinced that this is not an issue (especially for filter if not for Promise Result types)? Shouldn't Typescript compiler already infers the types for filtering with `var !== null`.

Some of those workarounds for filter are below code and i can make it work also with `as PromiseFulfilledResult` for Promise thing.
```ts
const numbers = [1, 2, 3, 4, null];
numbers.filter((num): num is number => num !== null);
```

**Comment by MartinJohns** [comment]
> Shouldn't Typescript compiler already infers the types for filtering with `var !== null`.

See #38390.
