### ISSUE TITLE
Function type references with unknown generics not assignable

### ISSUE THREAD

**Issue by squidfunk** [microsoft/TypeScript#49351]
# Bug Report

When I define an interface with a member that refers to a generic function type, TypeScript errors, saying that `unknown` is not assignable to the concrete type. Funnily, when defining the function signature on the interface itself, the error goes away and everything works as expected:

### 🔎 Search Terms

Generics, Type inference, function types, interfaces, assignable, unknown

### 🕗 Version & Regression Information

Reproducible on the playground with 4.7.2, 4.6.4, 4.5.5, 4.4.4, 4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/C4TwDgpgBA8gTgEwnAYgOwDwBUB8UC8UAFAIYBcUWANFAEYVYCUBeaArgLa3ICwAUPwCWaYMgBmJAMbQUAe1kBROHFlxsBKGzQBrNLIDuaPAG9+Uc1FVI4FeNfTYc-AL79+SSQBsScaGK2SwIKyaFBi8koqalhQEAAeomgIAM5QcorKqjhEYgyMFABusoII7hBePtCSIcnAYZGqFOkNauxcyE584RlROS3MAPQDUBiEWODQAORaugZok1CCqXp1JMnJggDmaCS0ntDAslBt3HBufMKicBLSafIAaiSeJeqEM3qGJmYWVsikDDR6JR8sdOKcXOcPN5fGEAkEQmEHk8XjF4okUndZI9nghsrlgYViqU+FDKlBqmhamFsSUmkicRgTh1+N0aQgcmzGPwgA)

### 💻 Code

``` ts
type OrderFn<T> = (a: T, b: T) => number

interface FooError<T = unknown> {
    order: OrderFn<T>
}

declare function fooError<T extends FooError>(f: T): void
declare const fError: FooError<number>
fooError(fError)
```

### 🙁 Actual behavior

``` ts
fooError(fError) // <= Type 'unknown' is not assignable to number
```

### 🙂 Expected behavior

``` ts
fooValid(fError) // <= inferred correctly as FooValid<number>
```

### 🐛 Temporary (?) workaround

``` ts
interface FooValid<T = unknown> {
    order(a: T, b: T): number
}

declare function fooValid<T extends FooValid>(f: T): void
declare const fValid: FooValid<number>
fooValid(fValid)
```

**Comment by squidfunk** [comment]
@RyanCavanaugh thanks!

**Comment by fatcerberus** [comment]
Better workaround:
```ts
type OrderFn<T> = (a: T, b: T) => number

interface FooValid2<T = never> {
    order: OrderFn<T>
}

declare function fooValid2<T extends FooValid2>(f: T): void
declare const fValid2: FooValid2<number>
fooValid2(fValid2) // ok
```

Function types are properly contravariant in their parameters, so `OrderFn<never>` is the top type you want, not `OrderFn<unknown>`.

**Comment by squidfunk** [comment]
@fatcerberus thank you! I'll give that a try.
