### ISSUE TITLE
[refactoring] Move to a new file should pick a name based on exported names rather than the first named thing encountered

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/TypeScript#49358]
# Bug Report

### 🔎 Search Terms

"move to new file"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about move to new file

### ⏯ Playground Link

This is a multi-file refactoring issue, so playground is N/A.

### 💻 Code

As an example consider the following code:

```ts
// SELECTION START
type FooInit = {
    bar: number,
}

class Foo {
    readonly bar: number;

    constructor({ bar }: FooInit) {
        this.bar = bar;
    }
}
// SELECTION END

export default function mkFoo() {
    return new Foo({ bar: 42 });
}
```

Select the text between `SELECTION START` and `SELECTION END` and use Refactor->"Move to a new file".

### 🙁 Actual behavior

Currently TS chooses the name `FooInit.ts` for this new file.

### 🙂 Expected behavior

The choice of name doesn't really make sense as `FooInit` in this example is just an internal utility type that isn't even exported. It would make more sense for TS to choose a name based on an item that is actually exported.

i.e. In this example the output file is:

```ts
type FooInit = {
    bar: number;
};

export class Foo {
    readonly bar: number;

    constructor({ bar }: FooInit) {
        this.bar = bar;
    }
}
```

It would make more sense for the file to be called `Foo.ts`. (But at present it calls it `FooInit` even though this value is internal to the module).

**Comment by RyanCavanaugh** [comment]
> The choice of name doesn't really make sense as FooInit in this example is just an internal utility type that isn't even exported. It would make more sense for TS to choose a name based on an item that is actually exported.

`class Foo` isn't exported either, though - was it supposed to be in the example?

**Comment by Jamesernator** [comment]
> `class Foo` isn't exported either, though - was it supposed to be in the example?

It is exported? It's used by `mkFoo` which makes it get exported when moved to a new file.

**Comment by Jamesernator** [comment]
> It is exported? It's used by `mkFoo` which makes it get exported when moved to a new file.

What I mean is, while `Foo` is not exported in the original file. It does gain `export` in the generated file.
