### ISSUE TITLE
Instantiation expressions not allowed in logical/coalescing expressions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#49362]
```ts
declare let f: undefined | (<T>(x: T) => T);

let g = f<string> || ((x: string) => string);
```

> **Maybe OT** Since you are fine-tuning how instantiation expressions are parsed: it's weird that `a<b> ?? c` is not valid code, from a syntactic point of view.

_Originally posted by @nicolo-ribaudo in https://github.com/microsoft/TypeScript/pull/49353#issuecomment-1145392217_

**Comment by ahejlsberg** [comment]
Right, for error recovery reasons we currently consider binary operators to be expression starters. We definitely shouldn't when they follow a (potential) instantiation expression.

**Comment by ahejlsberg** [comment]
Also, a compelling reason to parse as an instantiation expression when the `>` is followed by a line break and an identifier is:

```ts
let x = foo<string>
bar(10, 20)  // Function call
```

Though obviously JavaScript would parse it differently.

**Comment by ahejlsberg** [comment]
Honestly, the more I look at this the more I think the rule should be that a potential instantiation expression immediately followed by a line break is actually considered an instantiation expression followed by ASI. Consider:

```ts
let x1 = foo<string>
this.bar()

let x2 = foo<string>
function bar() {}

let x3 = foo<string>
class C {}

let x4 = foo<string>
delete obj.x

let x5 = foo<string>
void bar()
```

For all of the above we currently parse the `<` and `>` as relational operators. Messy!
