### ISSUE TITLE
Overloads shouldn't gain `@deprecated` tags of other overloads in quick info

### ISSUE THREAD

**Issue by brplatinum** [microsoft/TypeScript#49368]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Windows 11 Pro 21H2, also reproducible on macOS Monterey 12.4

Steps to Reproduce:

1. Create a file that contains a list of exported, consecutive, overloaded functions, with a single `@deprecated` tag at the top of the first one.

**api.d.ts**
```typescript
/**
 * @deprecated Use the new method instead.
 */
export function getArrayLength(arr: string[]): number;
export function getArrayLength(arr: number[]): number;
export function getArrayLength(arr: boolean[]): number;
```
2. Create a file that imports the overloaded function

**test.ts**
```typescript
import { getArrayLength } from "./api";

getArrayLength(["1"])
getArrayLength([1])
getArrayLength([true])
```
3. Only the first function is striked-through, the other two overloaded functions aren't, even though they are all marked as `@deprecated` when hovering over them.
![image](https://user-images.githubusercontent.com/23620781/171749515-6e1dfdac-bfa7-46be-8fd8-e073f74c6291.png)
![image](https://user-images.githubusercontent.com/23620781/171749860-1db67e24-0d54-4ce7-af5e-d95b0904687e.png)
![image](https://user-images.githubusercontent.com/23620781/171749998-a68669e4-23f7-4321-9afa-e07280b6065f.png)
![image](https://user-images.githubusercontent.com/23620781/171750138-76a5fdea-b26b-43d8-91ac-984640daf4ee.png)

Either the bottom two overloaded functions shouldn't be marked as `@deprecated` when hovering over, or all three functions should be striked-through.

**Comment by DanielRosenwasser** [comment]
This is working as intended. If we made all of them deprecated, there would be no way to convey that you want someone to use a different *overload* instead of a different function entirely, so we had to opt for a more granular approach.

**Comment by fatcerberus** [comment]
@DanielRosenwasser In that case, the hover text shouldn't show `@deprecated` for all of them.

**Comment by DanielRosenwasser** [comment]
Agreed, I think I missed that. Sorry about the incorrect triage.

**Comment by a-tarasyuk** [comment]
I think we can exclude only `@depracated` tag, however, does it make sense to show other tags/docs for overloaded signatures from the root declaration? Maybe we should inherit docs, however, tags seem to add confusion in the following cases.

```ts
/**
 * comment
 *
 * @param {string[]} a
 */
export function a(a: string[]): number;
export function a(a: number[]): number;
export function a(a: number[], b: number[]): number;
```

```ts
a/*1*/([1], [1]) 
a/*2*/([1])
```

/cc @DanielRosenwasser @RyanCavanaugh @sandersn

**Comment by sandersn** [comment]
@a-tarasyuk one of our oldest issues tracks that: #407

I don't think anybody's made a complete proposal, but I have to admit I haven't paid attention in several years.

**Comment by ValerianClerc** [comment]
@sandersn @DanielRosenwasser I've made a PR (#50904) which filters out the `@deprecated` tag from being passed on to other signatures of an overloaded function. Please let me know your feedback on it 😄
