### ISSUE TITLE
`Partial` is not composable with generics

### ISSUE THREAD

**Issue by safareli** [microsoft/TypeScript#49376]
# Bug Report

### 🔎 Search Terms

Partial generics record

### 🕗 Version & Regression Information
Tested on 4.5 4.6 4.7

### ⏯ Playground Link
 
[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.5.5#code/FAehAIBUE8AcFNwHIAKBDATgFwJZoDYA8kAfEuDgM7gB2A9luGpZTgOY1oBG+iWd4LHESpMuAsXAAycAG9wAMzp0AXOEpYMOGmwDc4AL5kAdKAjgow5JADaKALrgAPuACuNACbwF2+B-JUtAxMLOycPHwCQgjIABSQ0nKKymoaWjr6BgCUdo4u7l4+NH5IpmAWFTAxSLYOAdT0jMysHNy8glFWSPGJ8kqq6praeoY5Ds5unt6+-mXmFRZVIrYA1vDQdApQeVA2AET9e-b1QU2hrREdgl09Mn0pg+kj2bkTBdPFs2YLP0vWNmsNltIMcKA1gs0wm1Itdqrckv1UkMMqNXvkpkUSnMfji-jUbGlhjtbDRXABbLjwDDEgnQCl0fCgwKNEItcLtfiwkTw+4DQkol7jdGFGalb443FdWz8thM8FnNnQq7RbkJO7JPnI55jHbvTFfcoSiV49wregAdxoJxZkIuHM6cLVCIeMsyOreGNFxliACYAMw+n1ZYAAYzoNA0gngGgAjBYALzgSTwAAeWHgnmoACV4GGMB5CDKADSTM10S0kEixFMqdDYPBEUhZNR18SNo0LO6ImVGcDxkjgFOh8OR9OxgD6faTCVT6cz4BzeYLxdLFpolertbEDeIJGb4FbO9k3a1BkSCQ74AH-cHwG+eMPElI1oh53ZMJVyEf7fViMew0yExxUsaoDmUPYJkBTYoBfBUoUuTlPyQKDgTFQ1Ki6GVYNZeD7S5ZAUJg71-UDYMwwjRgxywH0E2nKsa2-Xd90Yi9Ly7FIe2vAch3I0do2oydE13TcWL3FttwkY8ONPc9LyvPtuOACx7y6UTEkY3kkSeQDsNtd9lVUiSf2dTVtMMExfQDINhwoqMND9WjhIYozd3UlypNUTjmJc1iO3YzzTy429eMo-i-UEuiRJ8gcZA0k8niMbz60k+LhjPGRfIlIKhyAA)

### 💻 Code

```ts
const test1  = <T extends Record<string, unknown>>(x:Partial<T>): Partial<T            & {foo:string}> => x
const test1_ = <T extends Record<string, unknown>>(x:Partial<T>): Partial<{foo:string} & T           > => x
const test2  = <T>(x:Partial<T>): Partial<T            & {foo:string}> => x
const test2_ = <T>(x:Partial<T>): Partial<{foo:string} & T           > => x
const test3  = <T>(x:Partial<T> & Partial<{foo:string}>): Partial<T            & {foo:string}> => x
const test3_ = <T>(x:Partial<T> & Partial<{foo:string}>): Partial<{foo:string} & T           > => x
```

### 🙁 Actual behavior

I get type errors for all this examples, 

### 🙂 Expected behavior

I should not get errors at minimum for test1_ test2_ test3_ if not for all. My expectations come from looking at similar code without use of generics working just fine: 

```ts
type T= { baz: number }
const _test2  = (x:Partial<T>): Partial<T            & {foo:string}> => x
const _test2_ = (x:Partial<T>): Partial<{foo:string} & T           > => x
const _test3  = (x:Partial<T> & Partial<{foo:string}>): Partial<T            & {foo:string}> => x
const _test3_ = (x:Partial<T> & Partial<{foo:string}>): Partial<{foo:string} & T           > => x
```

**Comment by MartinJohns** [comment]
The generic type could have a property named `foo`, which results in an intersection forming with the two types. This can result in the type `never`, which the object you return does not fulfill.

**Comment by safareli** [comment]
If so then shouldn't this work?:
```ts
const test1  = <T extends Record<string, unknown>>
  (x: Partial<Omit<T,"foo">>)
  : Partial<Omit<T,"foo"> & { foo: string }>
  => x
```

**Comment by MartinJohns** [comment]
No. `Omit<>` is a conditional type, and resolving of conditional types that involve unbound type arguments (like `T`) are deferred until the compiler has an actual type. This is a design limitation.
