### ISSUE TITLE
Assigning to a member variable named interface makes syntax highlighting break

### ISSUE THREAD

**Issue by Pajn** [Microsoft/TypeScript#4938]
See image:
![](http://s15.postimg.org/t6dosweaj/bad_highlighting.png)

**Comment by DanielRosenwasser** [comment]
Confirming, is this in Visual Studio?

**Comment by Pajn** [comment]
Sorry, it's in VS Code

**Comment by mhegazy** [comment]
@Pajn,do you mind filing this under the VSCode issues instead? https://code.visualstudio.com/Issues/List

Do we know if it repros for Sublime as well?

**Comment by mhegazy** [comment]
if so we need an issue on https://github.com/Microsoft/TypeScript-Sublime-Plugin as well

**Comment by Pajn** [comment]
Reported as https://code.visualstudio.com/issues/detail/19543
I can not reproduce in Atom. Can't test with sublime as I doesn't have it.

**Comment by DanielRosenwasser** [comment]
@hoanhtien @zhengbli

**Comment by zhengbli** [comment]
This is the same with https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/353
we are aware of it and will fix soon
