### ISSUE TITLE
Inlay hint for type of literal-initialized constant is unnecessary

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#49385]
Given

```ts
const foo = "foo";
```

An editor will make this appear like

```ts
const foo: "foo" = "foo";
```

This gets worse for longer strings. For example:

![image](https://user-images.githubusercontent.com/972891/171965316-8e3c4fcc-27e0-40f4-ba6e-5b84ee22afa5.png)

This really doesn't need a type annotation.

**Comment by DanielRosenwasser** [comment]
I've marked this as help wanted because I think it's uncontroversial, but still haven't gotten others' thoughts on it.

**Comment by fatcerberus** [comment]
A case could be made that this is useful so you know it’s inferring a literal instead of the base type (`string` in this case), but yeah, this becomes unnecessary noise once you know that `const` prevents widening of literals as a rule.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
