### ISSUE TITLE
Exclude<T, null> causes type errors when T is a generic type parameter.

### ISSUE THREAD

**Issue by dimfeld** [microsoft/TypeScript#49382]
# Bug Report

Using `Exclude<T, null>` on a generic type in a way that should resolve to `T` causes type system errors instead.

### 🔎 Search Terms

generic, exclude

### 🕗 Version & Regression Information

This is the behavior in every version I tried (4.0.5. 4.7.2, nightly), and I reviewed the FAQ for entries about Type System Behavior, Generics.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/GYVwdgxgLglg9mABBOBbADgQwE4FMCSUAPACqK4AeUuYAJgM6IDeA+jLQFyL1TYxgBzAL4A+ABQJcXEgEpmAKERLEUAJ7pciAHIItIADb7ctRAF5EAUQoR9IWrlIAaRGAP6RAbkXKUYHokwuHTA9Q2MzREkvISA
)

### 💻 Code

```ts
function compareIt<T extends {_id: string}>(one: T) {
    type NonNulled = Exclude<T, null>; // or string, number, etc.
    const a: NonNulled = one;
}
```

In my actual use case, I'm passing `T` into [this function](https://github.com/angus-c/just/blob/master/packages/collection-compare/index.d.ts) rather than having the Exclude in my own code. I've also opened a [discussion](https://github.com/angus-c/just/issues/460) on that repository since I believe the Exclude to actually be unnecessary in this particular case.

### 🙁 Actual behavior

Type error when trying to assign `one` to `a`.

```
Type '{ _id: string; }' is not assignable to type 'Exclude<T, null>'.
```

The same behavior occurs using `number`, `string`, or other types as the second parameter to `Exclude`.

Note that this also works fine, so there's something specific to generics going on here:

```ts
function compareIt<T extends {_id: string}>(one: T) {
    type NonNulled = Exclude<{_id: string}, null>;
    const a: NonNulled = one;
}
```

### 🙂 Expected behavior

I believe `Exclude<T, null>` should just resolve to something equivalent to `T`, since the type constraint in the function definition already prevents it from being `null`.

**Comment by MartinJohns** [comment]
`Exclude<,>` is used to exclude specific types from a union type. You try to remove the type `null` from the generic type argument `T`, but this is not a union type. You can't remove `null` from it, because the compiler doesn't know what type it actually is.

What you request would require the possibility to say "any type, except `null`", but this is not possible in TypeScript.

**Comment by RyanCavanaugh** [comment]
What you actually want here `T & ({} | null)` -- this will broadly "do the right thing" as of TypeScript 4.8.

**Comment by dimfeld** [comment]
Thanks for the feedback!
