### ISSUE TITLE
 Change Typescript's language color on GitHub

### ISSUE THREAD

**Issue by DarkGuy10** [microsoft/TypeScript#49389]
### What problem does this feature solve?

Currently, Typescript's language color on GitHub is `#2b7489`, which seems to be completely arbitrary. 

As you can see in the palette on [typescript branding](https://www.typescriptlang.org/branding/), the Typescript blue is `#3178c6`

![image](https://user-images.githubusercontent.com/62807269/171998692-30cc5d66-7b07-48a1-b30e-56cf192d5e15.png)

Can we consider changing `#2b7489` to `#3178c6`?

According to [Changing the color associated with a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-color-associated-with-a-language), we have to reach a consensus to make such change.

Proposed change: `#2b7489` to `#3178c6`

----

A [similar change](https://github.com/vuejs/core/issues/3674) was made for Vue's language color last year, so I'm hoping this works too!

**Comment by RyanCavanaugh** [comment]
I love that someone noticed this 🙂. Opened https://github.com/github/linguist/pull/5930

**Comment by DarkGuy10** [comment]
Lets go, the PR got merged!! :sparkles:

I think this issue can be closed now

**Comment by param373r** [comment]
Ayee, Congrats 🔥

**Comment by fatcerberus** [comment]
> Lets go, the PR got merged!! ✨

lessgo \*turns into a convertible\*
