### ISSUE TITLE
TypeScript extension is not picking up my virtual project scope Visual Studio 2015

### ISSUE THREAD

**Issue by cveld** [Microsoft/TypeScript#4939]
I am experiencing some unclear behavior within Visual Studio 2015. 

Somehow the Visual Studio TypeScript extension is not picking up the files within my project.

![image](https://cloud.githubusercontent.com/assets/6196260/10042026/0b2abb28-61e9-11e5-839f-c087901d8986.png)

It is a project.json based project. It looks like there is some conflict with the gulp-typescript package?

Setup a repo on GitHub: https://github.com/cveld/angular-typescript

**Comment by DanielRosenwasser** [comment]
Try removing the `tsconfig.json` file (just rename it to something like `tsconfig.json.bak`) and see if that helps.

**Comment by cveld** [comment]
Yes that works! What to do next?

**Comment by DanielRosenwasser** [comment]
Glad you found the issue!
