### ISSUE TITLE
Class inheritance prototype chain corrupted when targeting es5?

### ISSUE THREAD

**Issue by fengzhenqiong** [microsoft/TypeScript#49399]
# Bug Report

Actually I'm not sure whether this is the designed behavior.

When define parent classes which **explicitly extends Object** and sub-class it, then compile the code against **es5** and the prototype chain will be broken and it becomes not possible to access the methods defined in the parent class using an instance of the sub class. Following is the sample code:

```TypeScript
class Person extends Object {
    public say(msg: string): void {
        console.log(`Says ${msg}`);
    }
}

class Student extends Person {
}

var student = new Student();
// When compiled against es5 it says the method say is not defined, but it works in es6.
student.say("I'm a student");
```

I find following code in the compiled result JS code:

```JavaScript
var Person = /** @class */ (function (_super) {
    __extends(Person, _super);
    function Person() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Person.prototype.say = function (msg) {
        console.log("Says ".concat(msg));
    };
    return Person;
}(Object));
```

The code ```_super.apply(this, arguments)``` will change the ```__proto__``` property of the instance to ```Object.prototype``` when the ```_super``` is actually ```Object```.  So if I make ```Person``` extends ```Object``` **implicitly** instead, there will be no problem, as the problematic code will be removed and the constructor will return ```this``` directly.

There will be no problem is compile the above source code against es6, either.

### 🔎 Search Terms

I did not find any relative information about this same issue.

### 🕗 Version & Regression Information

I tried several versions (4.5, 4.6 and the latest 4.7.3) of TS and this problem exists in every of them (because the generated JS code are all the same).

### 💻 Code

Shown above and I'm pasting it here again.

```TypeScript
class Person extends Object {
    public say(msg: string): void {
        console.log(`Says ${msg}`);
    }
}

class Student extends Person {
}

var student = new Student();
// When compiled against es5 it says the method say is not defined, but it works in es6.
student.say("I'm a student");
```

**Comment by fatcerberus** [comment]
That FAQ entry really needs to be clearer that it doesn't apply when targeting ES2015 or higher (where subclassing builtins works as expected).

**Comment by fengzhenqiong** [comment]
> https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work

Thanks for the link, it really helps.
