### ISSUE TITLE
Request: Compiler option to specify an alternate lib.d.ts

### ISSUE THREAD

**Issue by sedwards2009** [Microsoft/TypeScript#494]
The compiler has an option noLib which disables the default inclusion of lib.d.ts during compilation. Unfortunately there is no compiler option to specify a .d.ts file or files to automatically include before compiling each .ts file. Such an option would make it much easier to use an alternate lib.d.ts.

The work around now is to use the noLib option and then to add a line to each source file to manually pull in your alternate lib.d.ts.

**Comment by mhegazy** [comment]
this should be covered by the proposal in https://github.com/Microsoft/TypeScript/issues/6974
