### ISSUE TITLE
in operator has different behavior in ES2022 and ES2021

### ISSUE THREAD

**Issue by Exifers** [microsoft/TypeScript#49404]
# Bug Report

### 🔎 Search Terms

ES2022 in class attribute

### 🕗 Version & Regression Information

- This is a crash **no**
- This is the behavior in every version I tried : **4.7.3** and nightly build (**4.8.0-dev.20220606**)
- I reviewed the whole FAQ

### ⏯ Playground Link

Somehow this is not reproducible in the playground. Below it logs `false` but when compiling in local it logs `true` (with both set to target: ES2022).

[Playground link with relevant code](https://www.typescriptlang.org/play?target=9&ts=4.8.0-dev.20220606&ssl=1&ssc=1&pln=2&pc=1#code/MYGwhgzhAECC0G8BQ1XQEYC5oQC4CcBLAOwHMkBfJJYAe2L2jGgF5piBTAdzgAoBKanQa0QHAHQhapXgHJ0s6CSb8gA)

### 💻 Code

```ts
class A {
    b: string
}

const a = new A()

console.log('b' in a)
```
with target: **ES2022**

### 🙁 Actual behavior

it logs **true**, while the same code compiled with  target: **ES2021** logs **false**.

### 🙂 Expected behavior

The behavior between ES2022 and ES2021 are the same.

**Comment by DanielRosenwasser** [comment]
Thanks @IllusionMH!
