### ISSUE TITLE
[RFC] Enforce safely handling error-throwing function calls with extended declaration syntax

### ISSUE THREAD

**Issue by 3x071c** [microsoft/TypeScript#49402]
# Suggestion

## 🔍 Search Terms

- RFC
- Error handling
- Exception handling
- RFC throw error

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code -> **Optional for existing function declarations** (unless new strict flag is on)
* [X] This wouldn't change the runtime behavior of existing JavaScript code -> **Only compilation errors, no runtime overhead**
* [X] This could be implemented without emitting different JS based on the types of the expressions -> **No runtime changes**
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.) -> **No runtime changes**
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals)

## 📃 Motivation

TypeScript's purpose has always been to **"identify constructs that are likely to be errors"**. This objective isn't only seen as the [number 1 TypeScript design goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals), but also on the [website](https://www.typescriptlang.org), where it is advertised to **"catch errors early"**. And while its core type system has made great leaps forward striving to make this a reality, there is a common JavaScript programming pitfall that still causes unintended or unexpected production accidents at runtime to this day: (inadequate) error handling. Consider this code:

```ts
function first<T>(arr: T[]): T {
	if (!arr[0]) throw new RangeError("Array is empty");
	return arr[0];
}

// ... somewhere down the road ...

function main() {
	first([]); // Oops!
}
main(); // Uncaught RangeError: Array is empty
```

The code above leverages JavaScript's built-in error handling system to throw an error if the array passed to the `first()` function is empty. However, (up until now) TypeScript won't warn us about this when we invoke the function without proper error handling. One missing try-catch block, one missing `.catch()` handler can take down the entire application, causing a hard-to-debug crash somewhere in the stack.
In certain cases, this could've been handled up-front with proper typings. For example, for the code snippet above, one could use a special array type that requires a minimum length of 1 array element (_anecdotally, this is currently not possible to enforce for arbitrary-length arrays with TypeScript_). One could've also opted for a different error handling pattern, returning `undefined` using TypeScript's conditional type support, or returning a `{ data, error }` object that can be destructured by the caller. In many cases, however, this is not viable, and introducing workarounds just piles on more overhead, anti-patterns and error surface on top of JavaScript's well-functioning native capabilities. There are countless libraries that expose functions which might `throw` for one reason or another, and unless it can be explicitly ruled out using type heuristics only, the developer is required to dig through (sometimes terrible) documentation or the raw source code itself to figure out if (and what!) error handling is required for a certain function call. Let's be honest - most of the time, this mind-numbing research is often left out for far too long, until it hits hard with unhandled errors in production. In an effort to advance TypeScript's stated goal of eliminating ever-so-subtle JavaScript issues before they happen, this RFC proposes a new function declaration syntax to fix just that - no runtime overhead attached.

## ⭐ Suggestion

```ts
function first<T>(arr: T[]): T / RangeError  {
	if (!arr[0]) throw new RangeError("Array is empty");
	return arr[0];
}
```

That's it. Using a `/` (forward slash) literal to separate the preceding function declaration from the thrown type (`RangeError`), TypeScript can now help the developer prevent a fatal bug:

```ts
function main() {
	first([]); // error TS????: Unhandled RangeError: Array is empty
}
main();
```

Of course, we might intentionally want the unhandled error to bubble up. Using the proposed extended function declaration syntax, this can be expressed intuitively:

```ts
function main() / RangeError {
	first([]);
}
main(); // error TS????: Unhandled RangeError: Array is empty
```

We can now handle the error at the top-level. The `/` (forward slash) character is reserved to define regular expressions, however I have not found a syntactically valid case where it can be used in a TypeScript function declaration.
The proposed change has a few implications:

- All existing `lib`/native type definitions will have to be extended with the error types they throw, if any
- The error parameter in `catch` blocks can now be strictly typed using the gathered type information
- Existing function definitions (without explicit error type declarations) imply no behavioral changes (i.e. they are expected to not throw)
- Adding a new strict flag to enforce strict handling of errors

**Comment by RyanCavanaugh** [comment]
This is a syntactic variation on #13219

**Comment by 3x071c** [comment]
Looks like I missed that one during my research 😅 (would've saved both of us some time).
Should this be kept open?

**Comment by 3x071c** [comment]
@RyanCavanaugh After looking into it, this is more about having TypeScript enforce proper error handling, similar to how it does type checking, while the referenced issue is about typing the `catch` clause. This issue does depend on #13219 being implemented, and it does overlap in suggesting a new function declaration syntax to include (possibly inferred) thrown error types. I think this should stay up.

**Comment by fatcerberus** [comment]
This is essentially a feature request for Java-style checked exceptions.  I’m almost positive there’s already an issue for this.

**Comment by 3x071c** [comment]
From how I see it this is not a duplicate, as elaborated above. Please reopen.
