### ISSUE TITLE
Function return type inferrence expecting `() => undefined` may refine impl to `() => void` which breaks

### ISSUE THREAD

**Issue by paul-marechal** [microsoft/TypeScript#49400]
# Bug Report

When defining interfaces with methods returning `undefined`, it would help if TypeScript could properly infer that the implementation does return `undefined` and not just `void`.

Maybe related: TS2355 `A function whose declared type is neither 'void' nor 'any' must return a value.` should include return types including `undefined` in its exception set for functions that don't require an explicit return statement.

### 🔎 Search Terms

undefined function void

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDKHIC2EYAFgPYAmAjABQCUAXMgApSXHAYQA8WKKADmyAD7IAriGoQYoCNQB8BIqQo0ATE1aCR4qTLkLqeAL548CSiCzJgxAA4AbVujsBeXKsLqqdVjgMAE8QBGQmZA8lbyI45GtbSmcIADpnSmF6AHIAd3Jg5AAjSVFabMYfZDMAGiq-LVZI6Nj4wkSMZLSMrLyC4tLkTQqqiwsrZyCMZABJJ2d7eYhScGn3bHw4oNDwhroddk5uXj5pWXkQRRjNtoSbTpT0zJz8wpLRAGYRuIs4ve0WIZziZWm0Ol0nr1XgNRAAWb5EMZ4IA)

### 💻 Code

```ts
interface Test {
    method1(): Promise<string | undefined>
    method2(): string | undefined
}

const impl: Test = {
    method1: async () => {
        console.log('why bug 1')
    },
    method2: () => {
        console.log('why bug 2')
    }
}

class Impl implements Test {
    async method1(): Promise<undefined> {
        console.log('why bug 3')
    }
    method2(): undefined {
        console.log('why bug 4')
    }
}
```

### 🙁 Actual behavior

The `impl` assignment fails because it evaluates `impl.method1` as `() => Promise<void>` and `impl.method2` as `() => void`.

For the snippet to work we have to write unnecessary boilerplate:

```ts
const impl: Test = {
    method1: async (): Promise<undefined> => {
        console.log('why bug 1')
        return
    },
    method2: (): undefined => {
        console.log('why bug 2')
        return
    }
}
```

### 🙂 Expected behavior

I would expect TypeScript to type `impl.method1` as `() => Promise<undefined>` and `impl.method2` as `() => undefined` based on the expected type of `impl` being defined and the fact that the implementations do in fact return `undefined` written as is.

Moreover, we get error 2355 in the class `Impl` saying `A function whose declared type is neither 'void' nor 'any' must return a value.`

I would argue that TS could expand the explicit return value exception to return types including `undefined`.

**Comment by fatcerberus** [comment]
`() => undefined` can't be treated as synonymous with `() => void` because the latter allows a function with any return type to be substituted for it.  For example if you ask for `() => void` then I can give you a `() => number` since `void` acts as a promise that you're going to discard the return value.  On the other hand if you ask for a `() => undefined`, then I can only give you something that explicitly returns `undefined`.

**Comment by paul-marechal** [comment]
After reading https://github.com/microsoft/TypeScript/issues/36288 in more detail it looks like what I was after, sorry for the duplicate.
