### ISSUE TITLE
Class property type is not accurate .

### ISSUE THREAD

**Issue by Archsx** [microsoft/TypeScript#49413]
# Bug Report

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/ATCWDsBcFMCcDMCGBjawCSBVAznACrAPYAO2wA3gFAgjiIC20AXMNpLBAObU2KfPBwAV3oAjODwC+PZABtE2MgFlCAE2iyAPABUAfBR4hkhcG1hDkkQrAAUxIaNmhkwVYkiIW2gJQVpIf2A5BTIcOGBoAA8YcFVlNQ1NLFxYAhJsfSoaVmhIADkGaBtwaAB3AsYWMy5vFgA3QlBVA2yQSAALUGwAOjcPbrpGYABeQTKK6ENgQMDgxWAANVAynUyp41N2Cytbe0dnYHoE2RYVdS09X3IZmXl5sNh0cHhCPD40KJi4xeXSpIe0qQ1tkNmZttYbEdziwHlcpiBsEJiHBIcdvFNAgjCIwlLl2mobHDWsAAPQkiKwIiwYDw4AdLrdKEabq4fKFGwAchehA56OyMyAA)

### 💻 Code

```ts
  interface IUserProps {
    name: string
    age: number
  }
  class Model<T> {
    constructor(public data: T) {}
  }
  class User extends Model<IUserProps> {
    setName(newName: string): void {
      this.data.name = newName
    }
  }
  class View<T> {
    constructor(public model: Model<T>) {}
  }
  class UserInfoPage extends View<IUserProps> {
    constructor(model: User) {
      super(model)
    }
    someMethod() {
      // error 
      this.model.setName('foo')
    }
  }
```

### 🙁 Actual behavior

Error: "Property 'setName' does not exist on type 'Model<IUserProps>'.ts(2339)"

in `UserInfoPage` class constructor I pass the param `model` which is a `User` type while TS can't infer that. it is inferred as type `Model<IUserProps>`

### 🙂 Expected behavior

More accurate.

PS: I got a workaround while it is a little verbose. use `public` keyword

```ts
  class UserInfoPage extends View<IUserProps> {
    constructor(public model: User) {
      super(model)
    }
    someMethod() {
      // error
      this.model.setName('foo')
    }
  }
```

**Comment by fatcerberus** [comment]
That's not merely a workaround; that's the correct way to do it.  In the original code it's `Model<IUserProps>` because that's how the property is declared in the base class (via parameter property shorthand, i.e. the `public` keyword) and you didn't override it in the subclass.

**Comment by RyanCavanaugh** [comment]
It *happens* to be the case that you pass `model`, which is a `User`, to `super`, but there's no contract enforcing that fact.

**Comment by Archsx** [comment]
> contract

so 
```
constructor(model: User) {
    super(model)
}

```
model is marked as User type can't make TS infer that in fact the model property is  a User type because code isn't invoked when I define the class `UserInfoPage` ? so TS statically check the type from the Model<IUserProps>?

and when I check the code compiled to ES5 I find the result 
```
var _this = _super.call(this, model) || this;
_this.model = model;
```
which means actually the model property assignment is invoked same way twice. is there any approach more elegant when  define a  derived class's  property with a subtype?(eg: `User` is a subtype of `Model<T>`)

**Comment by fatcerberus** [comment]
Just because you pass a `User` to `super()` doesn't automatically imply you want to change the type of the property it ultimately gets assigned to.  It just means it's a valid thing to pass to `super()`

Note that
```ts
constructor(public model: User) {}
```
is just shorthand for
```ts
public model: User;
constructor(model: User) {
    this.model = model;
}
```

So just do the latter if you want to avoid the double assignment.
