### ISSUE TITLE
Type '"ABC123"' is not assignable to type '`${string}${number}`'.

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#49411]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/G4QwTgBAHgXBAGASA3gZwC5gJYDsDmAvijgK4C2ARgKZgHwQC8EARAIIBCAwgIwBMAzMwDcAKCA

### 💻 Code

```ts
var x: `${string}${number}` = "ABC123";
```

### 🙁 Actual behavior

```
Type '"ABC123"' is not assignable to type '`${string}${number}`'.
```

### 🙂 Expected behavior

```ts
var x: `${string}${string}${string}${number}` = "ABC123";
```

=> 

```ts
var x: `${string}${number}` = "ABC123";
```

**Comment by jcalz** [comment]
This is working as intended. Duplicate-ish of #47048
