### ISSUE TITLE
Unable to use F2 Rename Symbol, Error: "No result. Delegating rename to the Angular Language Service."

### ISSUE THREAD

**Issue by Omzig** [microsoft/TypeScript#49417]
# Bug Report

### 🔎 Search Terms
- F2
- "F2 failed"
- "No result. Delegating rename to the Angular Language Service."
- "Symbol Rename Failed"

### 🕗 Version & Regression Information
tsc --version
Version 4.7.3

angular devDependencies: 4.3.5

vscode: 1.67.2
node: 16.13.0
"@angular/cli": "~12.2.13",
JavaScript and TypeScript Nightly ext v4.8.20220606

I just noticed the problem today. I use rename symbol a lot, so...

- I was unable to test this on prior versions because i do not have a test dev system, just my production dev laptop.
- Interesting enough, when i use vscode insider 1.68.0-insider it F2 works.... 
- `code --disable-extensions` will allow the F2 to work. so it must be some conflict with an angular extension?
- extension bisect has narrowed it down to a conflict with Typescript and the Angular Lang Server: https://github.com/angular/vscode-ng-language-service/issues/1686
- parent extension https://github.com/angular/vscode-ng-language-service/issues/1685

### 🙁 Actual behavior
- Failed rename plus an error notification.
- ![image](https://user-images.githubusercontent.com/1987296/172393064-67b61505-6ee1-4817-9fb7-535f1fff34fa.png)

### 🙂 Expected behavior
- A successful rename.

**Comment by atscott** [comment]
This is due to the Angular VSCode extension, not TypeScript so the report here should be closed.

**Comment by awoerp** [comment]
Pretty sure it is related to this issue:

https://github.com/microsoft/vs-ng-language-service/issues/36

**Comment by fatcerberus** [comment]
@awoerp That link seems to be broken.

**Comment by awoerp** [comment]
@fatcerberus Thank you, should be corrected now.

Also, found this issue which seems like "_the_" ticket for this issue:
https://github.com/angular/vscode-ng-language-service/issues/1685

**Comment by awoerp** [comment]
Note that as a temporary work around, you can downgrade your extension version as described in this issue:

https://github.com/microsoft/vs-ng-language-service/issues/36

**Comment by Omzig** [comment]
Closing due to the extension fixing the problem and not typescript.
