### ISSUE TITLE
Object method snippet completions incorrectly add this parameters 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#49426]
# Bug Report

### 🔎 Search Terms
- suggest / suggestions
- completions
- IntelliSense

### 🕗 Version & Regression Information
4.8.0-dev.20220606, not a regression

### 💻 Code

Try using a method snippet that uses a `this` parameter 

```ts
interface IFoo {
    bar(this: IFoo): void; 
}

const foo: IFoo = {
    // Trigger completions here    
};

foo.bar();
```

### 🙁 Actual behavior

The `this` parameter is also inserted:

```ts
interface IFoo {
    bar(this: IFoo): void;
}

const foo: IFoo = {
    bar(this) {

    },
};

foo.bar();
```

### 🙂 Expected behavior

The this parameter should likely be omitted in this case

**Comment by gabritto** [comment]
Why should we omit the `this` parameter in this case?

**Comment by RyanCavanaugh** [comment]
Honestly I was shocked that `this` parameters can get contextually typed; I thought this would be an implicit any. Anyway, it's not needed:
```ts
const foo: IFoo = {
    bar() {
        this.bar() // <- correctly typed
    },
};
```
