### ISSUE TITLE
More granular CanvasRenderingContext2D style typing

### ISSUE THREAD

**Issue by dylanscott** [Microsoft/TypeScript#4942]
I noticed that the typing for [`CanvasRenderingContext2D`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L5109) has the `fillStyle` and `strokeStyle` properties typed as `any`. The [Canvas 2D context specification](http://www.w3.org/TR/2dcontext/#fill-and-stroke-styles) seems to suggest that this type could be narrowed to `string | CanvasGradient | CanvasPattern`. I'm not sure if the type was kept at `any` for a specific reason or if perhaps it just hadn't been updated since union types were introduced, but I'm happy to submit a PR if this would be a reasonable change.

**Comment by DanielRosenwasser** [comment]
These are actually generated from another data source, so we need to change that. @zhengbli might know more.

**Comment by zhengbli** [comment]
I agree it would be better to make it an union type instead of `any`, MDN said so too. Will fix soon.
