### ISSUE TITLE
Type of `this` is not preserved when class method is used as a value

### ISSUE THREAD

**Issue by zawodskoj** [microsoft/TypeScript#49438]
# Bug Report

### 🔎 Search Terms

this type, class, bind

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE7QF5oBGAJgGYBuVdTAWwFMAXAC3gBMAKAShVs0zB4AOwjwQDAHQh4Ac06sAlhEk5c3agIC+qHaiGim0RYbDDgDQtGEMA7nEQ9qBiEYBmw4lZOuzFyYysHNQexE7QAPQR0EJ0AA6KEhAANNgAru5giTAm0LhpwkyKjDQu7sKkAFzQCizK1QjwvAQAfNAAbvCK7N6m5lKBbOwhFeFR0OzwDDDC8EaxCRLVACoslgDkShDrMSJMDAAeRvBu0EwAnnEbnd07ytZz0JAQirLCYFgSZ0iDHOswmzq22gJzOlw2jXWkho42WAGUniAZLYYEwkEIGLgLNAAAZbHHGYRPYTnGpmHoFCBgNwMXi2MDnfQiVzQDzkaq1erWNJ0LCY5ptG49Ig+Jh+AbMIYjciqExcMjkbhjaILRLTVJYDKsrIgHJE-KFYoMIA)

### 💻 Code

```ts
class Foo {
    bar = 123;

    method() {
        console.log(this.bar);
    }
}

const instance = new Foo();
const fn1 = instance.method;
fn1(); // compiles, but fails in runtime

const fn2: (this: Foo) => void = instance.method;
fn2(); // does not compile: The 'this' context of type 'void' is not assignable to method's 'this' of type 'Foo'.

// TS allows to coerce `this` in any (and unsafe) way
const fn3: (this: number) => void = instance.method;
fn3.bind(123)(); // compiles, but fails in runtime
```

### 🙁 Actual behavior

TS assumes `this` as any

### 🙂 Expected behavior

TS should preserve `this` type when class method is used as a value

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/10288 and https://github.com/microsoft/TypeScript/issues/7968
