### ISSUE TITLE
importModuleSpecifier shortest vs relative

### ISSUE THREAD

**Issue by artola** [microsoft/TypeScript#49439]
# Suggestion

## 🔍 Search Terms

VSCODE related from issue: https://github.com/microsoft/vscode/issues/151532#issuecomment-1150166535

This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

- VS Code Version: 1.67.2
- OS Version: Darwin arm64 21.5.0

Steps to Reproduce:

Having this path alias in `tsconfig.json`:

```
    "paths": {
      "@/*": ["src/*"]
    }
```

And using `"typescript.preferences.importModuleSpecifier": "shortest"` and with this file structure:

```
src/
  - foo.ts
  - bar.ts
```

Working on `foo.ts` the  import suggestion same level file is `@/bar` when it will make more sense to use the relative `./bar`.

In my opinion, it is not "shortest" the `@/bar` that `./bar` therefore the last one should be used.

**Comment by RyanCavanaugh** [comment]
I don't see how one of these is unambiguously preferable over the other in this situation. And as a sort of proof-by-contradiction, if you wanted `./bar`, you could have set `importModuleSpecifier` to `relative`, but you didn't, therefore you must have wanted `@/bar`.

**Comment by andrewbranch** [comment]
What does it do when you set it to `project-relative`?

**Comment by artola** [comment]
> What does it do when you set it to `project-relative`?

@RyanCavanaugh @andrewbranch Sorry guys. It seems that I did something wrong with my settings, because IT WORKS as I expected.

Having 2 files in the `src/` folder:

```ts 
// foo.ts

export const Foo = 123;
```
```ts 
// bar.ts

const bar = Foo;
```

With `relative` the import suggestion is:

![image](https://user-images.githubusercontent.com/11500763/172999572-fe0f11de-4297-4ccd-b88e-2e2f8794244c.png)

With `shortest` the import suggestion is:

![image](https://user-images.githubusercontent.com/11500763/173000403-b972e50a-d74d-4881-a5f0-d445f1d385d4.png)

I close this issue because everything works fine. Thanks for your support.
