### ISSUE TITLE
C# Style Static Extensions

### ISSUE THREAD

**Issue by electricessence** [Microsoft/TypeScript#4944]
I know this topic has be brought up before, but I can't find the thread from long ago...

Could it be possible to:
```typescript
module Extensions {
    export function toArray<T>(this:IEnumerable<T>):T[] {
        // code that returns an array...
    }
}
```

After importing this module, you could:
```typescript
import Extensions = require('Extensions');
// As in C#, you could:

// A)
var myArrayA = Extensions.toArray(myEnumerable);

// or B)
var myArrayB = myEnumerable.toArray();
```

Under the hood in JS, you would simply see the the 'A' version if you typed it like 'B'.

The benefits are somewhat obvious, but it would be extremely nice to allow for extending an interface this way as well as LINQ style syntax.

**Comment by electricessence** [comment]
The benefits are somewhat obvious, but it would be extremely nice to allow for extending an interface this way as well as LINQ style syntax.

**Comment by SaschaNaz** [comment]
#9 has similar discussion, so you will want to take a look ;)

**Comment by DanielRosenwasser** [comment]
Yup, discussion should continue on #9.

**Comment by electricessence** [comment]
thanks for finding #9.  I couldn't find it.
