### ISSUE TITLE
create new objects from existing ones using their types.

### ISSUE THREAD

**Issue by RahulGautamSingh** [microsoft/TypeScript#49445]
# Suggestion

## 🔍 Search Terms

1. extract

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example
Can we add a feature that let's you extract smaller object from a larger one. ie.
```js
interface A{a:string,b:string,c:string}
interface B{a:string,c:string}

const A_EX:A = {a:"a", b:"b", c:"c"};
const B_EX:B = A.extract(B);
```
It will really help when extracting from bigger objects.

## 💻 Use Cases

- I want to use this when I have to get smaller objects(like 7+ fields) from a object that is significantly bigger.
- I don't think there is any implementation for this.
- Currently I just have to create a function which take bigObj and then uses required fields to create a new smallObj.

**Comment by jcalz** [comment]
I assume you already realize this, but just in case, the template says:

> ✅ Viability Checklist
>   Suggestions that don't meet all these criteria are very, very unlikely to be accepted.

That's two whole "very"s, so we can expect this issue to be swiftly declined.

**Comment by fatcerberus** [comment]
Also worth noting, you currently have this checked:

> - [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

but this very much *is* a runtime feature, **and** requires type-directed emit, which pretty much excludes it from consideration outright.

**Comment by fatcerberus** [comment]
The entry you linked describes the *removal* of a type-directed feature.  (There are still some type-directed features, like `const enum`, but they all fall under grandfather clause)
