### ISSUE TITLE
How to extend lib.d.ts without modifying this

### ISSUE THREAD

**Issue by lovedota** [Microsoft/TypeScript#4945]
hi all
While I use it causes error
``` ts
interface Navigator {
  id: any
}

navigator.id.request();
```

```
 Property id is not existed in type Navigator
```

So how can i extend an existing lib.d.ts ? Thanks !

**Comment by basarat** [comment]
It works fine as shown : 

![image](https://cloud.githubusercontent.com/assets/874898/10066016/50f9cbc4-62d1-11e5-99b9-af309ab70b07.png)

You probably put the *extension* inside a file that is an external module e.g. the following is an error 

![image](https://cloud.githubusercontent.com/assets/874898/10066025/6e839710-62d1-11e5-98cd-b394405bd9e7.png)

Recommend creating a `globals.d.ts` file within your project. 

I have this documented here : https://basarat.gitbooks.io/typescript/content/docs/types/lib.d.ts.html

**Comment by lovedota** [comment]
Thanks it works well if i put this into a global.d.ts !!!
