### ISSUE TITLE
nullish check for multiple values.

### ISSUE THREAD

**Issue by Qlio** [microsoft/TypeScript#49452]
# Suggestion

## 🔍 Search Terms

typescript null check for multiple values
typescript undefined check for multiple values

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'm not sure how to explain it in English, so I try to explain using code:

```typescript
const f1 = (a: number | null, b: number | null) => {
    if (!a && !b) return; // if both is falsy then return.

    const c = a ? a : b; // one of them must be truthful.
    c.toString();  // <-- here it says  Object is possibly 'null' but it can't be null.
};
```

thank you.

**Comment by RyanCavanaugh** [comment]
Doing this would require a wholesale rearchitecting of how we do narrowing, but this kind of code doesn't come up all that often. It's straightforward to use `!` or tweak the code to have more obvious control flow, e.g.
```ts
    const c = a ?? b;
    if (!c) return;
    c.toString();
```
