### ISSUE TITLE
Inconsistent property type inference

### ISSUE THREAD

**Issue by tippfelher** [microsoft/TypeScript#49463]
Section A causes no TS error in the source code below.
Section B causes a TS error in the source code below.
Both sections do the same thing and section B shouldn't yield any errors. (?)
The message "Type 'boolean' is not assignable to type 'string'" also makes no sense because `prop` is clearly a `boolean` now. (?)

(?) means: I am pretty sure, but not entirely sure, as I am new to Typescript. ^^

```ts
type Template = {
  prop: number;
}

type Keys<Type> = keyof Type | (string & Record<never, never>);

type SomeType<T> = {
  [Property in Keys<T>]?: Property extends keyof T ? boolean : string;
};

// section A: no TS error
let something: SomeType<Template> = {};
something.prop = true;
something.anotherProp = 'value';

// section B: TS error
// Type '{ prop: true; anotherProp: string; }' is not assignable to type 'SomeType<Template>'.
//   Property 'prop' is incompatible with index signature.
//   Type 'boolean' is not assignable to type 'string'
something = {
  prop: true,
  anotherProp: 'value',
};
```

[Here is the playground.](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhC2YA2BDY0C8UDeAoKUYATgPZgBcUAdgK7wBGERA3LgL666iRQDSEIAM4AeGOAgA+KFgDWAkgDNY4qAB8oACkHAiASyoBzKADIoAJQgBjEkQAmwqhABuTADTVnTCQEpWXFQDKJPAQYpCiUlh4BADaAAqkkESgUPp8AiIwEgC6APyUCWRMKRAAHuhUtoJQciCKsFC5UPQkJEgQKFRQlNp6hqxsfgD0Q1CCVsC6JF0AgpRUJLABUEykRLjtwGPBEMAAFvoGlEEhYRCiCMhoktI4g7iCO-uHAHTEZLc6NBCsjyHPhhenRI+yYhTAtwA5E4UEhvpDhqNxpZJtMoAAhSgwZarGy4EbKHiQ7CERKUL4-KDA0FEcE9HSHZhQNiQ1LVBZbFCCQS6AxUFD0dpQYCLbjQSEnULiC6IVDoCSQl740YEcHFEBQSHvMCs3TVfTWRBoXSC6AAd10+1SlTKY15-OANCIECVBIIZ01LTaHSouvZIKp3PtAqFIuFKkhvUOkIeTwOhlu0VJZHJRG+rnwVI5ezBZM1MLhEEhGcGQA)

**Comment by RyanCavanaugh** [comment]
Simpler version:
```ts
type Template = {
  prop: number;
}

type SomeType<T> = {
  [Property in keyof T]?: boolean;
} & { [s: string]: string };

// section A: no TS error
let something: SomeType<Template> = {};
something.prop = true;
something.anotherProp = 'value';

// section B: TS error
// Type '{ prop: true; anotherProp: string; }' is not assignable to type 'SomeType<Template>'.
//   Property 'prop' is incompatible with index signature.
//   Type 'boolean' is not assignable to type 'string'
something = {
  prop: true,
  anotherProp: 'value',
};
```

It seems like you're trying to emulate rest index signatures, which aren't really supported. See #7765.

**Comment by tippfelher** [comment]
That's very, very sad because this sounds like a very useful feature when working with types. (at least in my use cases ^.-)

So basically, in order to achieve this, I have to generate a separate file with type definitions from runtime information [as relay does](https://relay.dev/).

Thank you very much though.

**Comment by fatcerberus** [comment]
The problem with “rest” properties is, given you have ` { [x: string]: string, foo: number }`, what should the type system do when given an arbitrary `string` key that happens (at runtime) to be `"foo"`?  That’s not something the type system can verify at compile time, so TS doesn’t even try to model this case and instead treats the index signature as universal.

**Comment by tippfelher** [comment]
I am not saying `{ [x: string]: string, foo: number }` should work because this would obviously be bad design. But if you write it as

```
{
  [x in any string but 'foo']: string; // (pseudo syntax)
  foo: number;
}
```
then there would be no problem to determine the type for property `baby` or `foo`. (This prolly cannot be implemented in the current TS architecture)

**Comment by fatcerberus** [comment]
Well, `{ foo: number } & { [x: string]: string }` (roughly what you have in the OP) is basically the same type as `{ [x: string]: string, foo: number }` and neither one is safe for the above reasons, is what I was getting at.  Your pseudocode above would indeed be a solution, but there's currently no way to express "any string except 'foo'" - that would require [Negated Types](https://github.com/microsoft/TypeScript/pull/29317), which, judging by the fact that PR was recently closed, looks like have been taken off the table. 😢

**Comment by fatcerberus** [comment]
> I am not saying `{ [x: string]: string, foo: number }` should work because this would obviously be bad design. 

Yep, I agree - but you'd be surprised how many people still want that *exact type* to work, and will argue vehemently with you when you try to tell them it's unsafe.  It's refreshing to see somehow who recognizes that. 😄
