### ISSUE TITLE
Unable to use one overload because another overload locks the generics of the parameter

### ISSUE THREAD

**Issue by voliva** [microsoft/TypeScript#49465]
# Bug Report

### 🔎 Search Terms

overloads generics

### 🕗 Version & Regression Information

Checked on 4.7, but by trying older versions it seems it's been there for a long time. It's not listed on the FAQ though

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/LAKFEsDsBcFMCcBmBDAxrABAIQPYA8AeAFQD4MBvUDDAc1mgDVkAbAV1gAoBKALgyKoYADuCGw+ABVGxiJANygAvqAgwEKdBiljZFQQQBKJDokh8OAI3x9chUlwwBeMreIYAPhiO9s+N56N9IxMzDEtrXzsSB2dIw2ibP0CQZTAQVBxIAGdoDCgc5Eh0RMJIVgBbCwQPDDLmZjJHWtZ6jGQstsgATwU0xFYi6HBMjFhIAAtC9HhZDgA3FnY+OuYfDnC8EtkYlz8iGpXovRBqeHpWeEgMHAsAKycyFbaOwp6lFRB86CnYADoRMQcMaTIoIDgrLhcXpAA)

### 💻 Code

```ts
interface Box<T> {
  getValue(): T
  pipe: Pipe<T>;
}

interface Pipe<T> {
  <R>(fn: (box: Box<T>) => Box<T | R>): Box<T | R>
  <R>(fn: (box: Box<T>) => Box<R>): Box<R>
}

const instance: Box<number | null> = null as any;

function enhancer<T>(value: null): ((box: Box<T>) => Box<T | null>) {
  return obj => null as any;
}

instance.pipe(enhancer(null)); // Error! enhancer can't be used here

// If you comment out the first overload of `Pipe<T>`, then
// `enhancer(null)` can be used inside of pipe without any error.
```

Sorry for the contrived example, it's a simplification of something much bigger.

This surfaced when building types around something similar to Observable of `rxjs`, but that has a subclass of Observable, and a special operator that adds a new overload to the `pipe` function (which is the first one).
In this case, `enhancer` is essentially one of the overloads of `startWith(null)`, that breaks if the `instance` is an `Observable<something | null>`.

### 🙁 Actual behavior

`enhancer(null)` can't be used inside `instance.pipe`. It gives the following error:

```ts
No overload matches this call.
  Overload 1 of 2, '(fn: (box: Box<number | null>) => Box<number | null>): Box<number | null>', gave the following error.
    Argument of type '(box: Box<number>) => Box<number | null>' is not assignable to parameter of type '(box: Box<number | null>) => Box<number | null>'.
      Types of parameters 'box' and 'box' are incompatible.
        Type 'Box<number | null>' is not assignable to type 'Box<number>'.
          Type 'number | null' is not assignable to type 'number'.
            Type 'null' is not assignable to type 'number'.
  Overload 2 of 2, '(fn: (box: Box<number | null>) => Box<number | null>): Box<number | null>', gave the following error.
    Argument of type '(box: Box<number>) => Box<number | null>' is not assignable to parameter of type '(box: Box<number | null>) => Box<number | null>'.
      Types of parameters 'box' and 'box' are incompatible.
        Type 'Box<number | null>' is not assignable to type 'Box<number>'.
```

What I think it's happening is that the typechecker tries to match the `enhancer` call to the first overload as closely as posible. It sets `<number>` as the generic for the first overload, but fails to apply it.

However, when it moves on to the next overload, it's like it keeps the decision it made on the first one, so the check still fails, because if you remove the first overload, then it accepts the second overload by assigning `<number | null>` to the generic.

### 🙂 Expected behavior

Typescript should accept the second overload as valid regardless of what happened on the first overload.

**Comment by RyanCavanaugh** [comment]
This is a design limitation of the inference process, but it's nearly always avoidable.

What kind of call is the first overload there to try to allow?

**Comment by voliva** [comment]
@RyanCavanaugh thanks for looking into this - I have created a longer but more complete example [on this playground](https://www.typescriptlang.org/play?#code/PTAEDECcHsFtUgDwFYGcB0mBQBLAdgC4CmkAZgIYDGRoA8gEaokBu59ANkQDwAqAfKADeWUKFQBXRpUg56RABSV6ALlDzmqngEpQAXgHNoOACZbVhk1gC+WXIRIVqoAKp5ykAJ7hxeSgRzQeLwANKAASgLCovKo0OKQ1Jpm4dYA3HbEZFQ0tAAOJOQE0JDevv6BIeECRIjEeMaoLm6epX4BQQxMkKwc3PyhnSxsnFwRkVbpBB75oABq5OziRFBwAIKQkOQeXKugNXUNCETkxoHsHqA+ANZ40ADueADaALoCuqC7+0T1jeub2-hSCRQPxQAB+EGgVR4IjMEjpLCkHxtQJiAjuAgAdRwBAAFrw+OoFktoeJ2OxknkCkUSsjykEeKEeKAAD6gPBk9h8dJIsrtNEY7F4yqfWrfQ6QY6nPDnS54G73J7PPQgl6EzDoViLIioVSrSn5TY01r0yrMtnzbUrWB-LY7PjcxF0-modGQLE4-GM0AAEXVmC1S11vpeBupxRN7TNrN9kRERwI8Tw7M5oHIjXIeA86RsWBACEQAFpXYUiBkHNlQABldHEQbdYZ9apin50RhDXoEoTxgDmRAIlqW8mS5tAAAUYLAcEwCfHcjh8qoxwumzny1knD6iBQycRjDXS-WeiNQV9Wwe6+2G53QVFQH2B8SFCPrLZ8JlHDRl-ku3f83dPS3Hd2AIUBoDhSB2GgE5UHje15HjURjG3chdzyVQYjiBIiAAElUI9GwJHR9F9FDdyIfdayIAibxjVY+GCeNkiA1CQIoi9qKvY8+jovg4NWUIACFCUQsDcgARgw2J4moPC2y6biiL0AQaJGejGNEJCyJA9C1Gk7C5NU7h6OIgQWPIyjDy4wjdjZYSNNAZjtL3DijJ2GNhNsUR8xLYgwIgqCYP4kTNLEyS9Kw2T8Osm8+FM+SOzUhimNUVyYqS-ihJCzToAkqTItw6KFMI-h4rc9TRNygAmfKZMKhLrySsr0u4eyUurKi3M83NeRRZMALxcyQMqP15GQ4DH21VQfR0O9JUTSBk0wurDJaojpuc9jOrW0c-WUsQCpwtMMyzV88zAXJ2C2HsYB8YwsEoQJXVAfAS18IhUu24rOw5WA5EgGMOXJN4U3JY60yzBFHrwZ7IAABhVV70Xe9B53yGI3Q9PF5CBiktFSUB8wAUQ2YoAEIBXdIVcRxzkdEoTMAHJQLkS4mGMUBcRIMsHqe0DIHExGYeR6hUZXeQBtxIaCFp8ktHxwmwFoABpUBCwQQXp1Iiatqs77OCwIA) (less than 60 lines)

## More context
In [rx-state](https://github.com/rx-state/core) we're extending `rxjs` including the concept of `StateObservables` - Observables that are multicast that when they have an active subscription they have a state, that you can get by calling a function. This is the core of [react-rxjs](https://github.com/re-rxjs/react-rxjs), it lets React integrate well with observables to use them as state.

We also have `DefaultedStateObservables`, these are StateObservables that they have a default value in case no one is subscribed to that observable, or if the observable hasn't emitted anything yet you are guaranteed a value. This is also really helpful in the context of react.

We're adding a new feature where pipeing a `StateObservable` to compose it with others will directly create a `StateObservable` without needing to wrap it through a function. For this, we're overriding the `pipe` method of rxjs' Observable, this works just fine.

To create a `DefaultedStateObservable` from this pipe method, we're also creating a new operator `withDefault(defaultValue)` so that if placed as the last operator in `pipe`, then it will return a `DefaultedStateObservable` instead. So this adds this other set of overloads.

## Possible fix found

When working on that playground, I've found that if the definition of the set of overloads for `withDefault` changes slightly, the test does pass:
```ts
// Overloads that don't work
  <A>(
    defaultOp: (source$: Observable<T>) => DefaultedStateObservable<T | A>,
  ): DefaultedStateObservable<T | A>
  <A, B>(
    op1: (source$: Observable<T>) => Observable<A>,
    defaultOp: (source$: Observable<A>) => DefaultedStateObservable<A | B>,
  ): DefaultedStateObservable<A | B>

// Overloads that do work
  <A>(
    defaultOp: (source$: Observable<T>) => DefaultedStateObservable<A>,
  ): DefaultedStateObservable<A>
  <A, B>(
    op1: (source$: Observable<T>) => Observable<A>,
    defaultOp: (source$: Observable<A>) => DefaultedStateObservable<B>,
  ): DefaultedStateObservable<B>
```

What changes is the return value of the `defaultOp` from `DefaultedStateObservable<T | A>` to `DefaultedStateObservable<A>`, and the returned value of the overload to match semantics.

But I'm not sure why it passes with this and not the other. The reasoning behind that union is that `withDefault` takes in the the default value as a generic `D`, and returns the union `T | D` - So now I'm afraid that if I don't use a union in there, then typescript could complain on some cases where you have e.g. an `Observable<number>` and you try to put `withDefault(something that's not a number)`.

**Comment by Andarist** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/46312

**Comment by voliva** [comment]
Thank you, I didn't find it when I searched. Closing it as duplicate
