### ISSUE TITLE
TS declare method produces compile errors with noImplicitAny enabled

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#49478]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.8.0-dev.20220606

**Search Terms**
- quick fix
- code action
- noimplicitany

---

![Recording 2022-06-10 at 10 38 38](https://user-images.githubusercontent.com/900690/173026662-aee9b7b8-1028-48fd-94b2-b6fa1bb1f325.gif)

**Comment by mjbvz** [comment]
Minimal repo:

1. Enable `noImplicitAny`
2. Trigger declare method here:

```ts
interface IFoo {
}

const foo: IFoo = {}
foo.bar()
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
