### ISSUE TITLE
Request Feature: Ability to declare optional variable with '?'

### ISSUE THREAD

**Issue by joe88ds** [microsoft/TypeScript#49477]
## ⭐ Suggestion
Let us declare local variables as optional

## 💻 Use Cases
`const x: Type? = y;`
`let x: Type?;`
and this would translate to:
`const x: Type | undefined = y;`
`let x: Type | undefined = undefined;`

## 🔍 Search Terms
optional variable

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

Duplicate of #41901.

**Comment by joe88ds** [comment]
> You forgot to fill out the issue template.
> 
> Duplicate of #41901.
