### ISSUE TITLE
Spread is allowed when target type has no properties matching spread source

### ISSUE THREAD

**Issue by jtbandes** [microsoft/TypeScript#49471]
# Bug Report

### 🔎 Search Terms

spread missing props

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about spreading

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.7.2#code/GYVwdgxgLglg9mABAMTnAFABwE50wZwC5EBvAD2PymxjAHMBfASlIChFEAhAQ23RICexAEQALGMIA0iAHRycefMwDcrBq1CRYCLr3QB9BQWKDCVGvWZt1rIA)

### 💻 Code

```ts
function Foo(props: {x: string}) {
  Bar({y: "hi", ...props});
}
function Bar(_props: {y:string}) {
}
```

Or the React version of the same thing:

```ts
import React from 'react';

function Foo(props: {x: string}) {
  return <Bar y="hi" {...props}/>
}
function Bar(_props: {y:string}) {
  return <div/>
}
```

### 🙁 Actual behavior

Spread is allowed

### 🙂 Expected behavior

This should be an error because the spread source `{x: string}` does not overlap with the destination type `{y: string}`.

**Comment by jcalz** [comment]
See #38657
