### ISSUE TITLE
No documentation for Map and Set types

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#49472]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `the default`.

## Missing / Incorrect Definition
`Set` and `Map`

## Sample Code

The `Map` and `Set` types don't appear to have any documentation. This makes it difficult for a beginner to work with them

```ts
const x = new Set();
x.clear() // no docs here
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by orta** [comment]
For someone interested, this is accomplished by adding JSDoc comments to https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/src/lib/es2015.collection.d.ts ( and other .d.ts files )
