### ISSUE TITLE
Function variance unsoundness

### ISSUE THREAD

**Issue by iluuu1994** [microsoft/TypeScript#49484]
# Bug Report

Found while thinking about ways to implement closure types in PHP. I'm not sure how much code out there is written like that but I thought it was an interesting find.

```typescript
class A {
    test(x: () => number|string) {}
}

class B extends A {
    // No error but this is unsound, callers of A.foo() through polymorphism might pass a function that returns more than `number`
    test(x: () => number) {
        // 1. This receives a string from 2, a number is expected 
        const n: number = x();
        console.log(n); // "foo"
    }
}

function doSomethingWithA(a: A) {
    // 2. This passes a function returning a string, as A allows it
    a.test(() => 'foo');    
}

doSomethingWithA(new B());
```

### 🔎 Search Terms

function variance closure sound unsound

### 🕗 Version & Regression Information

This happens on nightly and 3.3, so sounds like a longer-standing issue.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220609#code/MYGwhgzhAECC0G8BQ1XQC4FMLoBQA8AuaXASmgF4A+aAOwFcBbAI0wCcAfHNgS1oHNyCAL5JRSUJBgAhaJnxZaAExjxkaaAHpN0AHIB7OWzb620ZvXQYAFjxh3o9WhH1OlAGmjAwIEOxj6AGZwAHSB+vpkNq781tAADvogAJ6MpvG2EIzQjDyxVvFS0GDQgU7A6Dz6tDZgVmyY6PRszjmmmLU1AAYMLOxdKGhYOATEUdR0TKxsQoMaqNrQAIwh0AAqmdANwJg8AG7YxdDcfPylJtkATJ4lvdPQDvLxmBWYStBz88DVOHTEd+xKNB8GQANyfDTfZxJTAhED6fi4WikcEaUTiMq0CpVGpKfQAZX0jEatgEAHUeOhrLBcGBiLBZhpFpdVhsHIUoIcSpjsdUto1mrRTkcTgIbqpir59AB3ezoT5gELDPDjGgAcnC+jVKI0YiQSDxhOJVNOFKpNNomGl0GkZBRQA)

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

> Type 'string | number' is not assignable to type 'number'.

**Comment by MartinJohns** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

This is by design. Use properties instead of methods to achieve the behaviour you want.
