### ISSUE TITLE
Feature: Add Generics to Event target

### ISSUE THREAD

**Issue by TheColorRed** [microsoft/TypeScript#49504]
# Suggestion

## 🔍 Search Terms

 * Event target generics 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

This would add the ability to use generics to `type` the `target` of an `event`.

## 📃 Motivating Example

This would remove the requirement of having to cast it each time you use it or assigning the target to a variable.

```typescript
function myEvent(evt: KeyboardEvent) {
  // Option "A" save to variable and cast (Still good for large blocks of code)
  const input = evt.target as HTMLInputElement

  // Option "B" cast target every time
  if ((evt.target as HTMLInputElement).value === 'a') {
    // Do something
  } else if ((evt.target as HTMLInputElement).value === 'b') {
    // Do something else
  }
}
```

## 💻 Use Cases

With a generic type, you get a cleaner more readable result:

```typescript
function myEvent(evt: KeyboardEvent<HTMLInputElement>) {
  if (evt.target.value === 'a') {
    // Do something
  } else if (evt.target.value === 'b') {
    // Do something else
  }
}
```

```typescript
function myEvent(evt: KeyboardEvent<HTMLInputElement | HTMLDivElement>) {
  if (evt.target instanceof HTMLInputElement && evt.target.value === 'a') {
    // Do something
  } else if (evt.target instanceof HTMLDivElement && evt.target.innerText === 'b') {
    // Do something else
  }
}
```

**Comment by MartinJohns** [comment]
The `target` doesn't has to be the element you attached your event handler onto. TypeScript can't ensure that the generic type argument matches, and generated runtime checks are a no-go.

So the only *benefit* is that you don't have to use the type assertion, which is actually a huge drawback. It shows a wrong sense of safety where there is none.
