### ISSUE TITLE
Partial removes readonly modifier on index signatures

### ISSUE THREAD

**Issue by eranhirsch** [microsoft/TypeScript#49512]
# Bug Report

For types which have an index signature (e.g. ```{ a: string, [key: string]: string }```, The order in which Readonly and Partial are composed on the type change the resulting type; when Partial is composed on the result of Readonly, the `readonly`-ness of the explicit prop remains, but the index-signature becomes writable. When composing the Readonly after Partial the resulting type is fully readonly. At least in essence, as they touch different modifiers of the prop, the order of composition shouldn't matter.

```Partial<Readonly<T>> !== Readonly<Partial<T>>```

### 🔎 Search Terms

partial

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (this goes all the
-  way back to the earliest version in the playground)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/C4TwDgpgBAsiAq5oF4oG8oEMBcUDOwATgJYB2A5gNxQDaA1hCLgSRQLrNFnlQC+lAKAEB6YbACuwTACMANtADUUAEoQAjuOKEIAEygAxYhFk6BAYwD2pAlG3lxszIVxxEkKKgw4oAIgAWxrIWPnyCdg5OAHSYHr4A7haEJj5hEPaOhDQ+0j5ssT4JSTopQqIqEJg6VrIgUEqqGlq6BkYm5lY2mHiqldVM5b2kNQA8rkgAfLFeuP6BwaECXT1VQyDR+YXJgksVKzVZOXmoBYlbpWIwkjLydVAAgrKyUBZgwMRWmLLt1sBYeAAKTjen1wgMIwNkowQEym-EWAKBxE+62Om2K2wR4KRsgOuQ2p3R5wGe1qSgeTwA8q93qRPt8bBAAB6QMzAXQARlwyz6wzBEKhbgg40mnjhTJZbJ07JR8QJJXFEFZHNxR1lRRK9N+CqVOgATFzdjy+diBRMRegoNIZgFHvMxczFZLdTKTurBNqnSr8W6iQ88BZiX1buSoFS3h8ngAKAD8AEpNVAwBY8HhiHIIAAhcTkTlQY2fYbc1amyDC2GCJMptPyLM5l1okpleB+Yh4KCtrC2Q2rZ7SABWjoANFA-BY4u228RfgBbK7p6MCSup9O19le1FywQJpfVzPZ-V5xEFosjMal80YK2+G1BEJwncr-f1zciMTNjsdmLaQY1XsD1nDqO44fjOc7yAuD41vu65qmcQA)

### 💻 Code

```ts
type MyType = { a: string; [key: string]: string };

// Mutable + Required Field
const regular: MyType = { a: "hello" };
regular.a = "world";
regular["b"] = "world";

// Readonly + Required Field
const asReadonly: Readonly<MyType> = { a: "hello" };
asReadonly.a = "world";
asReadonly["b"] = "world";

// Mutable + All optional
const asPartial: Partial<MyType> = {};
asPartial.a = "world";
asPartial["b"] = "world";

// Readonly + All Optional
const expected1: Readonly<Partial<MyType>> = {};
expected1.a = "world";
expected1["b"] = "world";

const expected2: Readonly<Partial<MyType>> = { b: "hello" };
expected2.a = "world";
expected2["b"] = "world";

// Also Readonly + All Optional (?)
const possibleBug1: Partial<Readonly<MyType>> = {};
possibleBug1.a = "world";
// This is a readonly object, how is it mutable?
possibleBug1["b"] = "world";

const possibleBug2: Partial<Readonly<MyType>> = { b: "hello" };
possibleBug2.a = "world";
// This is a readonly object, how is it mutable?
possibleBug2["b"] = "world";
```

### 🙁 Actual behavior

Index signature props are writable for an object which is composed with Readonly.

### 🙂 Expected behavior

The whole object should remain readonly

**Comment by RyanCavanaugh** [comment]
Mapped type retain their mapped-over-types' property modifiers if and only if they're "homomorphic", which is a not-yet-website-documented aspect of a mapped type. I don't have a definition handy, but `Partial` is not homomorphic but `Readonly` is, so only one of them retains the source type's modifiers.
