### ISSUE TITLE
[Feature Request] Add types to specify nullable/maybe values

### ISSUE THREAD

**Issue by ThaFog** [microsoft/TypeScript#49530]
# Suggestion

## 🔍 Search Terms

- nullable type
- defined type
- maybe type
- nullable values
- defined values
- undefined values

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'd like to have type aliases that specify whether type is nullable or probably undefined. Something like:

```typescript
type Nullable<T> = T | null;
type Maybe<T> = T | undefined;
```

Just in case - I wouldn't compose those two unless it's a third type (`MaybeNullable`?). Lot of projects try to omit `null` and use `undefined` instead. Having type which says something can be both would be useless in such projects.

## 📃 Motivating Example

TypeScript has `NonNullable` type which is mostly useless with `strictNullChecks` option enabled. On the other hand there are no types to specify nullable or probably undefined type aliases. While we can just type `type | null` or `type | undefined`, it's more readable, faster and cleaner to do that with type aliases.

## 💻 Use Cases

Instead of:

```typescript
let nullableValue: string | null;
let maybeValue: number | undefined;

function getDisplayName(): string | undefined {
  // ...
}
```

We can have more readable alternatives:

```typescript
let nullableValue: Nullable<string>;
let maybeValue: Maybe<string>;

function getDisplayName(): Maybe<string> {
  // ...
}
```

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/41901#issuecomment-742660337 for why this likely won’t be implemented.

**Comment by ThaFog** [comment]
> See [#41901 (comment)](https://github.com/microsoft/TypeScript/issues/41901#issuecomment-742660337) for why this likely won’t be implemented.

What you referenced is totally different thing. I'm not requesting for `?` type extension to cover `| null` or `| undefined` as I understand:

1. It's not obvious whether it's "nullable" or "undefinable"
2. It can be confusing taking TypeScript's syntax into account (`?` is used next to variable name in some cases like interface fields hence it would be confusing to use it next to type name in other situation). 

The thing I'd like to see are simple type aliases which don't add anything new to TypeScript syntax. It would be the same thing as `NonNullable`, `Record`, or `Partial` type aliases. And still if TypeScript has `Nonnullable` that is used in non-strict environment, why not have equivalent types for strict one?

**Comment by MartinJohns** [comment]
> The thing I'd like to see are simple type aliases which don't add anything new to TypeScript syntax. It would be the same thing as `NonNullable`, `Record`, or `Partial` type aliases. And still if TypeScript has `NonNullable` type that is used in non-strict environment, why not have equivalent types for strict one?

See https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388:

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.

**Comment by fatcerberus** [comment]
It’s not exactly the same, but the same concerns apply, namely that people will argue endlessly over whether `Nullable<T>` should be `T | null`, `T | undefined`, or `T | null | undefined` and each side will insist theirs is the “right” way.  Better to just be explicit about which one you want than to force the language to commit to one canonical definition of “nullable” when none of the options is clearly better than the others.

**Comment by ThaFog** [comment]
> It’s not exactly the same, but the same concerns apply, namely that people will argue endlessly over whether `Nullable<T>` should be `T | null`, `T | undefined`, or `T | null | undefined` and each side will insist theirs is the “right” way. Better to just be explicit about which one you want than to force the language to commit to one canonical definition of “nullable” when none of the options is clearly better than the others.

Yes, I'm aware of that, hence I've proposed two separated type aliases and optional third which would be a compound. Anyway sure, it's more clear now. Also @MartinJohns's addition expleinaed some cases so I understand you guys had endless debates about that and decided you'll go this way. I'll close that as not planned. Thanks for answers!
