### ISSUE TITLE
ts sequencing

### ISSUE THREAD

**Issue by icefapper** [Microsoft/TypeScript#4953]
hi
does ts have any notion of <a href='https://en.wikipedia.org/wiki/Sequence_point'> sequening </a>? i.e, in an expression like l()+L(), what is the order of _execution_? is it l() then L()? or there is no ordering ?

**Comment by danquirk** [comment]
The order will be whatever the ECMAScript spec defines for how the emitted JavaScript behaves as that is what actually gets executed. If you run code like this in Chrome today you'll see I() execute then L() execute.

**Comment by icefapper** [comment]
thanks for the response; i actually knew the underlying js is what is actually run, still i thought ts enmforces it own rules by using, e.g, ',' operator, wherever it wants to impose an order of execution i.e, i thought it had a facility to rewrite l()+L() as var _l, _L; _l = l(); _L = L(); _l + _L (the ',' is by far the sole seq point i've come across in js)    . what made me ask was that i could not get to find(neither in js spec nor in that of ts) a clear explanation of what will happen in cases like above

**Comment by DanielRosenwasser** [comment]
When downleveling newer/future JS constructs, the order of operations is intended to be the same as those specified by the ECMAScript spec despite the target to which we are downleveling.

Try the following out in [our playground](http://www.typescriptlang.org/Playground) to experiment with our emit:

```TypeScript
let i = 0;
function f() {
    return { a: i++, b: i };
}

let { a, b } = f();
let c, d;
({a: c, b: d} = f());

**Comment by icefapper** [comment]
@DanielRosenwasser thanks a lot :)
