### ISSUE TITLE
Inconsistent 'keyof' keyword in Record type and Object literal type

### ISSUE THREAD

**Issue by toy0605** [microsoft/TypeScript#49540]
# Bug Report

### 🔎 Search Terms

- keyof
- Record
- Object literal

### 🕗 Version & Regression Information

testing in 4.7.3. but it occured every version.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UBKEDGB7ATgEwDwGdhMBLAOwHMAaKAV1IGtT0B3UgPgG4AoUSKAIQRQA3lADaADwBcUQiQoBdGXUYtSUAL7de0AMJDRkqGVlEy5JbQZNWm7lwylCUAIYz6EEOgBmsIQEZuR2cAI3dPHwEAoPQnYChUcK9ffURAoA)

### 💻 Code

```ts
type A = Record<string, unknown>;
type B = { [x: string]: unknown };
type C = { [x in string]: unknown };

const a: keyof A = 1; // Type 'number' is not assignable to type 'string'.
const b: keyof B = 1; 
const c: keyof C = 1; // Type 'number' is not assignable to type 'string'.
```

### 🙁 Actual behavior

keyof A is string.
keyof B is string | number
keyof C is string.

### 🙂 Expected behavior

Every keyof A, B, C types should be string | number OR string.

----

https://www.typescriptlang.org/docs/handbook/2/keyof-types.html

> Note that in this example, M is string | number — this is because JavaScript object keys are always coerced to a string, so obj[0] is always the same as obj["0"].

Honestly, I don't know what is difference using 'in' keyword at key of this code. but it makes different result so I post this issue.

**Comment by toy0605** [comment]
> The case `A` and `B` are working as intended. See [#48269 (comment)](https://github.com/microsoft/TypeScript/issues/48269#issuecomment-1068278045). Case `C` is essentially a mapped type as well, so the same as `A`.

Record<K, T> is equivalent to `{ [P in K]: T }`. so Record<string, unknown> is equivalent to `{ [P in string]: unknown }`.

but I can't understand `{ [P in string]: unknown }` and  `{ [x: string]: unknown }` is difference. Why Record Type needs P?

**Comment by MartinJohns** [comment]
These are different syntaxes for different things. https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#handbook-content & https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html

**Comment by toy0605** [comment]
```ts
type A = { [x: string] : unknown}
type B = Record<string, unknown>;

const a: A = { 0: "test", a: "test" };
const b: B = { 0: "test", b: "test" };

function testA<T extends A>(a: T) {
    return a;
}

function testB<T extends B>(b: T) {
    return b;
}

testA(a);
testA(b);
testB(a);
testB(b);
```

It absolutely works same. but using 'keyof' is difference. is it as intended? but why?

**Comment by MartinJohns** [comment]
Because these are different features with different purposes. With `Record<>` you can limit the keys, e.g. `Record<"a" | "b", unknown>`, but this is not possible for types with index signatures. A record means "for every key specified" (just that you use `string` to say any `string` key), whereas with index signatures you say "for any `string` key".

**Comment by toy0605** [comment]
> Because these are different features with different purposes. With `Record<>` you can limit the keys, e.g. `Record<"a" | "b", unknown>`, but this is not possible for types with index signatures. A record means "for every key specified" (just that you use `string` to say any `string` key), whereas with index signatures you say "for any `string` key".
> 
> 
> 
> I'm not sure why you expect different features with different functionality to behave exactly the same.

I didn't understand clearly but I got to understand it is different features.

Could you show me example code how different is? it makes me understanding clearly.

Thank you for reply!
