### ISSUE TITLE
Function involving FlatArray is transformed in declaration in an incompatible type.

### ISSUE THREAD

**Issue by Lucas-Mercier-tech** [microsoft/TypeScript#49572]
# Bug Report

### 🔎 Search Terms

FlatArray declaration unknown
### 🕗 Version & Regression Information

- This changed between versions 4.7.0-dev.20220406 and 4.7.0-dev.20220408 (still present in 4.7.3)

### ⏯ Playground Link

[Playground link with relevant code (target: es2019)](https://www.typescriptlang.org/play?target=6&ssl=18&ssc=32&pln=1&pc=1#code/PTAEBUAsEsGdQGYFcB2BjALtA9ig5PBgJ4AOApqHKGpAIYoDmZAJqLqM2WgDa0BOtLLgBQZAB4lsfDNVywZyFKAC8oABTCAkLCQAjAGKoAXKAA8AYWzduXISgA0ofdDLdW4jGRTN4AazJE2Aiglta2OCgAfGoAlFqaypFOvBgAgnwCRBZWNpgRANrOrswAuo4ADJH5JTEqSQDeoAC+ANzCwiAQMPD8DEgAtl4ysJDYSG6g-YI0oBiQFMTkbMG9A0OgSLAsoLpEiKjCaHLDeoYoAKJitP0kNipmobl2jkUTHl4+oP6BwY-huNE4ppNCZ9Cl0plsmE8rhCi43GVQJVqnVQNU2h0wOBSGRYGg+NASDJmNhcaAUNgZHM+NgAO6geh7MgZKSzeZ8MjCRRqHQGVCXa63MgxDGdKBUKhzBY4xBjbyyvj7JTQJRSjhcXgCOyIaA2AB0oAAksNRuNWLoKGQAI5IaAAN1oNhQVOwbOlSwQrMUesOxyVAH1ODx+IIIiYeadjA8cv8HE54e4xJ5vH4AkEQjGYVFYqi1H8s3DiiVQO8U5QUAhmRBQAB+aulz75uyFhG1+tJj7wDm0Ekobh7VC+Cm0lAouuD4dKEzgUAmFBkO1VucL5kxaq1RKgO3YaCsLSqNT+jcNVrtMU4vEEolsmm0npKZk0xVSjk+xSBjUhuwRvkXK43GwRWEIA)

### 💻 Code

```ts
// This function's type is changed on declaration
export const fun = (
	subFun: <Collection, Field extends keyof Collection>()
		=> FlatArray<Collection[Field], 0>[]) => { };

// This argument should match the type of argument used by fun
const subFunExample = <Collection, Field extends keyof Collection>()
		: FlatArray<Collection[Field], 0>[] => [];

// Typescript does not throw any error there
fun(subFunExample);

// This is the type found for fun in the declaration file. It should be equivalent to the type for fun.
const fun_declaration: (subFun: <Collection, Field extends keyof Collection>() => (Collection[Field] extends infer T ? T extends Collection[Field] ? T extends readonly unknown[] ? unknown : T : never : never)[]) => void 
	= (_) => {};

// Typescript throws an error there.
fun_declaration(subFunExample);
```

### 🙁 Actual behavior

When the declaration is created, the type of fun is transformed to `(subFun: <Collection, Field extends keyof Collection>() => (Collection[Field] extends infer T ? T extends Collection[Field] ? T extends readonly unknown[] ? unknown : T : never : never)[]) => void;`.

This declaration type does not recognize arguments that were matched by the original type.

### 🙂 Expected behavior

No error. Declaration type should be equivalent to the original type: if typescript does not raise an error with the original type, it should raise an error for the declaration type.

I've tried to find a simpler type exhibiting this behavior, but didn't find any.

**Comment by weswigham** [comment]
Hm, so our old emit was compatible, true, but it didn't execute over unions correctly. The new emit was introduced to distribute over unions correctly, but what I find most concerning is that `unknown[]` has appeared out of thin air. It used to be
`export declare const fun: (subFun: <Collection, Field extends keyof Collection>() => (Collection[Field] extends readonly (infer InnerArr)[] ? InnerArr : Collection[Field])[]) => void` which was correctly generic, if not distributive, however the inner `infer` and indexed access have suddenly evaporated now - that's definitely not right. I'm guessing something is being over-instantiated during construction of the new wrapper in this recursive type alias case.
