### ISSUE TITLE
Seemingly-fine code produces an error in 4.7 but not 4.6

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/TypeScript#49577]
# Bug Report

I don't know if this is a real problem, or if it's the expected result of increased strictness. I can also work around it. I just wanted to share for visibility. Feel free to ignore/close if it's not useful.

### 🔎 Search Terms

symbol 4.7 4.6 error

### 🕗 Version & Regression Information

- This changed between versions 4.6.4 and 4.7.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/C4TwDgpgBAwg9gOwM5wDYEsAmBDYFMAycA5segsQMoDGAFhALbZQC8UA3gFBQ9SURIk6RAC4O3XpIAiEAEYBXKgKGiO2MbLhoI2BAF8JPA3oDcnUJCgBRAG4QEwACrhobAOT9BwhG7OcAZvII1MDeUAD6-gA8tvbAANLkmFAQAB54CJhI1nYOzpAANLCIeOn50GkZWVAA1hAgcP7FyGhYuPhEpORUdIzYANqxDomZALoAfAAUhlAWEGLwDpXlBZwAlOKSAPRbUOUpAE4HcAdQ5FAALAB0AOxFCsBQCHBQYMeyqIxnCJdXAGwzHZ7egHCBubKYdBIajyLyIKCNKBIEAMTSobLnYD0X43KCgz7YJDQZ54JBFFCzWhQs5IHyPJC0ODUGrdK5QEQbWjAYBgJAiHaYCA2D4kJBXBjoajHFD+YBXahwBhbObQg7oMDALa6Z5BajdAC0Kql6uA+ou+puWxmCpanyuqBIkzmUAA1FA3ITMP43Gs-NtdgB1aDUXRQADuJxqUGwxyCyXQjzDCdo0Z+aTAGD1jxtdgOKgQ93kj2pWNwr2wkDVFARuejUEFEErNKQ8ggAH4oNbECg7Q7iJNKMAq-25hs3R6kF6fWYDJwgTB5Gq4LDUCAiugmmHoKCGHA7FAAAZDBJJA9FLHQKEt6DEOACaNh7AgNkASTcDCecHpi+gYdoIEpakGWXVBkloCtIB+QBkAjOJoj1yE9MhSdJ7GqY9ygPb4EUXZDsAYDNoGwTQ7FWIFdGSeC4gwmkoAAK1hR5mCQIduigDA8AObBUHJRl5FAulKWgRBV1eOAvA+aBKOGU9o3RF5ZGgUt6RY6t2IgTjUA7AN-3DED40eJg6jrSF-H8dT7GoRSXlBDNsEszsyNmFwoBsGN0CIz5w2TQSEQQESsVYhMoAVPjkjAMShA+ACFLbAJdVCeFIgAJiiRZSicZzKlQ7I6gaJpFh7No8EIEgyAoGh6CYfoPGUbw3AmaZJDmBYSmWFxVg2LhJBtHsIHtR1nXHT1vV9ThZyAA)

### 💻 Code

Copying the contents of the TS Playground link above:

```ts
type ConsolidatedLoggingSchema = {
    Session: {
        DebugSession: {a: boolean}
    }
};
type EventType = 'Session';

function _f<EventKind extends EventType, ContextType extends keyof ConsolidatedLoggingSchema[EventKind]>(
    type: ContextType,
) {
    // Type error in 4.7, but no problem in 4.6
    // There's discussion of symbols in the 4.7 release notes, so this isn't shocking. :) https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/
    console.log(type + 'asdf');

    // We can work around it with an explicit conversion, but is that papering over a deeper issue? 
    console.log(String(type) + 'asdf');
}

// Curiously, if we remove `EventKind`, the issue goes away. I'm not sure why this should happen – if `EventKind extends EventType` in our example above,
// and `EventType` is just a string literal, shouldn't the only possible `EventKind` also be that string literal? Why would it make a difference to replace 
// a type variable with the only thing it could possibly be?
function _f2<ContextType extends keyof ConsolidatedLoggingSchema['Session']>(
    type: ContextType,
) {
    console.log(type + 'asdf');
}


```

### 🙁 Actual behavior

This continued working between 4.6 and 4.7.

### 🙂 Expected behavior

It stopped working.

**Comment by fatcerberus** [comment]
This is possibly relevant.

For `_f()`:
```
(parameter) type: ContextType extends keyof ConsolidatedLoggingSchema[EventKind]
```

But for `_f2()`:
```
(parameter) type: ContextType extends "DebugSession"
```

So the difference in behavior is down to the fact that in `_f2` the `keyof` gets evaluated eagerly while in `_f` it's deferred.

**Comment by fatcerberus** [comment]
@RyanCavanaugh How hard would it be for the compiler to detect that `keyof ConsolidatedLoggingSchema[EventKind]` can never be a symbol?  It seems that it could simply reduce `EventKind` to its constraint, and indeed the compiler already does that in other cases.

**Comment by RyanCavanaugh** [comment]
I'd be very worried about the performance implications of doing that, since it's common to have constraints that resolve to huge unions (think `T extends keyof JSX.IntrinsicElements`), so doing anything iteratively would be quite expensive.

Then there are some other challenges. It'd have to be implemented as a new kind of specific higher-order operation, since neither union nor intersection of each possible resolution of `CLS[EK]` produces the correct set. If you imagine something like
```ts
type Foo = {
  a: { x: number },
  b: { y: number }
}
```
then for `K extends keyof Foo, T extends Foo[K]`, `keyof Foo[K]` is neither `"x" | "y"` (since `K` could just be `"a"`) nor `"a" & "b"` (since this is `never`). It's some other kind of type that does have relations to its output but is just a new kind of type.
