### ISSUE TITLE
Give a helpful error when tsconfig.json has "excludes" without "exclude" property

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#4957]
There's definitely always going to be people who type in 'excludes' instead of 'exclude' (https://github.com/Microsoft/TypeScript/issues/4939#issuecomment-1430313820), so let's actually be helpful in that case.

In addition, in a language service context, maybe we should still figure out what the user means and just pretend they wrote 'exclude' in addition to showing the error.

**Comment by mhegazy** [comment]
Thanks @YuichiNukiyama
