### ISSUE TITLE
Class extends error has wrong result with `instanceof` (in ES5 target)

### ISSUE THREAD

**Issue by 07akioni** [microsoft/TypeScript#49587]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- **This is the behavior in every version I tried, and I reviewed the FAQ for entries about error inheritance**.
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=1#code/MYGwhgzhAEAiCmAnAlgN3gE2vAHgF3gDsMYBRRRAe0WgG8BfAKGEsIj2gyTU2gF5oheAHc43dBgAUASkbNWESiHgA6EJQDmkgOSkAygFZtslmyWr1WrignRkbPGELB4lAGbRyVRCYXm1mpLWPFj27E4u7mI2mNJAA

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```
class Derived extends Error {}
const derived = new Derived()

console.log('ES5')
console.log(derived instanceof Error)
console.log(derived instanceof Derived)
```

### 🙁 Actual behavior

```
ES5
true
false
```

### 🙂 Expected behavior

```
ES5
true
true
```

**Comment by 07akioni** [comment]
In es6 runtime it works fine.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/18677354/174220406-f746e314-99de-4278-a073-eebf8adf440d.png">

**Comment by Josh-Cena** [comment]
> and I reviewed the FAQ for entries about error inheritance.

It's right in the FAQ, though.

https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-extending-built-ins-like-error-array-and-map-work

**Comment by 07akioni** [comment]
> 

Thanks for answering 😁
