### ISSUE TITLE
Typescript 4.7.3 bracketed class property compilation error strictPropertyInitialization:true

### ISSUE THREAD

**Issue by BzenkoSergey** [microsoft/TypeScript#49594]
# Bug Report

### 🔎 Search Terms

strictPropertyInitialization bracketed class property

### 🕗 Version & Regression Information
Typescript 4.7.3, 4.7.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/KYOwrgtgBAglDeBYAUFWUC8UDkNsBoU0AhTHY7FAXxRQGMAbAQwGcWpSlUoBtGAOhgBdAFxQWAFwBOASxABzANy1udAPYhJUsHQlqpACgCUCImigSAFjJZ9BQstgCM2ZdzRWbgxy7fmL1ra42A5Yzq5mNMhUQA)

### 💻 Code

```ts
enum A {
  A = 'A',
  B = 'B'
}

class B {
  [A.A]: string;

  constructor() {
    this[A.A] = '1';
    this.A = '1';
    this['A'] = '1';
  }
}
```

### 🙁 Actual behavior
Compilation error:  
Error: Property '[A.A]' has no initializer and is not definitely assigned in the constructor.

### 🙂 Expected behavior
Seems it should be compiled without errors.

**Comment by jcalz** [comment]
Probably related to #45974 aka ["Control-Flow Analysis for Bracketed Element Access"](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#control-flow-analysis-for-element-access).  Could you please edit your post to fill out the [bug report template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md) to help the TS team?

**Comment by BzenkoSergey** [comment]
@RyanCavanaugh still not working

https://www.typescriptlang.org/play?ts=4.8.4#code/KYOwrgtgBAglDeBYAUFWUC8UDkNsBoU0AhTHY7FAXxRQGMAbAQwGcWpSlUoBtGAOhgBdAFxQWAFwBOASxABzANy1udAPYhJUsHQlqpACgCUCImigSAFjJZ9BQstgCM2ZdzRWbgxy7fmL1ra42A5Yzq5mNMhUQA

**Comment by RyanCavanaugh** [comment]
It works in nightly. You have the Playground set to a build that was produced before the PR was merged.
