### ISSUE TITLE
Invalid declarations for inlined distributive types in 4.7

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#49591]
# Bug Report

### 🔎 Search Terms

invalid declaration distributive types

### 🕗 Version & Regression Information

- This changed between versions 4.6 and 4.7

### ⏯ Playground Link

[Workbench](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKALgTwA7wDOAdNkQFB6GgBiiRoAvKKAErwDGA9gE4AmAHiLZe0RAHMANKAAUJBfmS80RLAFdEAa0TcA7ogDaAXQCUzAHyhNO-YgsUqBeKACyyfIIAqoeAA9sJH5GeiIrFgBvUEMAaVBxUC14XG5IUC9jLC9Y4wBuUABfXMdqFwBBWFgy3glvXwCgkIZw0CjY+MRE5NT0zNAABWU0eEDeIm8cqyLHSE1ObGhuTshEOv9AxGDW0D8sd09sgHI-Q+Mpi1kiWGhOeABJTf8s0ywKqpqJ49OrCIpWVl4I3UvE6iHUlQAhMUCo5-Pg+NhQPx4JBkODEVEVoVihQQBAYAgUOgsIC4QiyJQKNBUPDeIjAiJQJBeNxUKAAEQkYClIjsnFkulIlFo2AYnDERFFIA)

[Playground Link For resulting declarations](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gfVAMygFcIMAueAbwCh5b4MRNzq7X48VyAeAFWwEZ4IAB4MUwNJRpsZw8n34BtAETDlAXSGiQ4yQEsUeEDHg94AfkrxFAaXgH4AaxABPJHlPr5AlWvW31AG54AF94chQQADdjQOkZEIA+AAo0CD0wEABJcRFvfgBKeABeRNMfVQ0tMQl7Q2NygCYLK1sBOqdXdyaveAAFWCgAWxAGGDReCr82-nVE4LCI6Nj40LiQuJEAByQYLHwiEhwD4gxAoA)
### 💻 Code

```ts
// @filename: types.ts
type Fns =  Record<string, (...params: unknown[]) => unknown>

type Map<T extends Fns> = { [K in keyof T]: T[K]; };

type AllArg<T extends Fns> = { [K in keyof T]: Parameters<T[K]> };

function fn<T extends { x: Map<T['x']> }>(sliceIndex: T): AllArg<T['x']> {
    return null!;
}

export default { fn };

// @filename: reexport.ts

import test from "./types";
export default { test };

```

### 🙁 Actual behavior

TypeScript generates this declaration: 

```ts
declare const _default: {
    test: {
        fn: <T_1 extends {
            x: T_1["x"] extends infer T ? { [K in keyof T]: T_1["x"][K]; } : never;
        }>(sliceIndex: T_1) => T_1["x"] extends infer T_2 ? { [K_1 in keyof T_2]: Parameters<T_1["x"][K_1]>; } : never;
    };
};
export default _default;
````

In the declaration above the expression `Parameters<T_1["x"][K_1]>` doesn't type check. The `T_1["x"]` is not constrained anymore to be `Record<string, (...params: unknown[]) => unknown>`

TypeScript could include the constraint of the original type in the declaration: 

```ts
declare const _default: {
    test: {
        fn: <T_1 extends {
            x: T_1["x"] extends (infer T extends Record<string, (...params: unknown[]) => unknown>) ? { [K in keyof T]: T_1["x"][K]; } : never;
        }>(sliceIndex: T_1) => T_1["x"] extends (infer T_2 extends Record<string, (...params: unknown[]) => unknown>)
             ? { [K_1 in keyof T_2]: Parameters<T_1["x"][K_1]>; } : never;
    };
};
export default _default;
```

### 🙂 Expected behavior

Resulting declarations for `reexport.ts` are valid

**Comment by MartinJohns** [comment]
Possibly related? #49572
