### ISSUE TITLE
Assigning to same interface and same key fails

### ISSUE THREAD

**Issue by orgads** [microsoft/TypeScript#49604]
# Bug Report

### 🔎 Search Terms

same key "is not assignable" bracket 
same key "is not assignable" literal

### 🕗 Version & Regression Information

- This changed between versions 3.3.3 and 3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIyYD8AXMgM5hSgDmA3PsgEZxRnIgCuAts9AG0AuowKsAXhwBKEBOigATADxUaIWgBpkXEAGsQ6AO4gAfIwC+uXDB0IwwdCEK2AFDHIZ0AShxM5IKmRgHgAHD0xkAF4cc1FCeWQXf0DdCABPZHQYZAEAciJ0XK1c1ihcoWQ4CkTUtKy0TC9hLyYCYJCBWoromE70kVxLIA)

### 💻 Code

```ts
interface Foo {
  foo?: string;
  bar?: number[];
  baz?: Record<string, unknown>;
}

function func(f: Foo) {
  const imp: Foo = {};
  for (const key of ['foo', 'bar'] as (keyof Foo)[])
    imp[key] = f[key];
}
```

### 🙁 Actual behavior

I'm getting this error:
```
Error: Type 'string | number[] | Record<string, unknown> | undefined' is not assignable to type '(string & number[] & Record<string, unknown>) | undefined'.
  Type 'string' is not assignable to type 'string & number[] & Record<string, unknown>'.
    Type 'string' is not assignable to type 'number[]'.
```

If I understand correctly, since `key` can be any of `Foo`'s keys, the type of `f[key]` is considered the intersection of all options.

But since the key is known in advance, I'd expect it to resolve it for each iteration separately. Is that too much to ask?

This is possibly related to #45390, but I do cast to `keyof` explicitly, so I'd expect it to work.

It looks like I'm missing something here...

### 🙂 Expected behavior

The assignment should succeed.

**Comment by jcalz** [comment]
Duplicate of #32693

**Comment by orgads** [comment]
Thank you
