### ISSUE TITLE
TypeScript doesn't detect constructor's private params' usage when passed to `super()`

### ISSUE THREAD

**Issue by DamianGlowala** [microsoft/TypeScript#49605]
# Bug Report

### 🔎 Search Terms

- is declared but its value is never read
- 6138

### 🙁 Actual behavior

Constructor's params are not detected when passed to the `super()` constructor, as shown below:

![image](https://user-images.githubusercontent.com/48835293/174496720-b3f217eb-eaa8-421b-9ffb-9462ec1d2197.png)

### 🙂 Expected behavior

I would expect TypeScript to detect the usage of the constructor's param in the call to `super()`.

**Comment by fatcerberus** [comment]
It's actually detecting that the *property* isn't used, not the parameter.  Because you're using constructor property shorthand (`private`)

**Comment by DamianGlowala** [comment]
If it's private and yet the value is passed correctly (it does work), shouldn't TypeScript detect the usage?

**Comment by fatcerberus** [comment]
`private` makes it create a private property with the same name on instances of the class (`this.configService`), which you never use and because it's private, can't legally be accessed from outside.  The error message is correct.

**Comment by DamianGlowala** [comment]
Thank you for the above explanation. Closing! :)
