### ISSUE TITLE
Extract does not properly narrow template literal to string literal

### ISSUE THREAD

**Issue by sam-goodwin** [microsoft/TypeScript#49617]
# Bug Report

### 🔎 Search Terms

Extract, template literal, narrow, string literal, narrow

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: **template literal types**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcghgJwQewO4QCZQLxQKIAewCcAxsADwAGAggMJ0DyAqjACoDEAJAN4DOxAJYA7AOYBfKgBootBi3Yc4AI1JUAfACgA9Nqj6AegH4de4AAtBfKKEhQ+55AFcANlmXQ5TVpxVqZwsjAssIQAG4QCFRAA)

### 💻 Code

I think there is a bug/limitation with `Extract` and template literal types. In the below example, I am trying to narrow a template literal type, `ACCOUNT#${string}`, to a literal string type, `ACCOUNT#abc`, but it is narrowing to `never`.

```ts
type Narrowed = Extract<`ACCOUNT#${string}`, `ACCOUNT#abc`>
//   ^? never
```
Interpreting the tsdoc of `Extract` (below):

```ts
/**
 * Extract from T those types that are assignable to U
 */
type Extract<T, U> = T extends U ? T : never;
```

... it should narrow to the literal string `"ACCOUNT#abc"` as that is the only type in `T` (`ACCOUNT#${string}`) that extends `U` (`ACCOUNT#abc`)

### 🙁 Actual behavior

Type narrowed to `never`

### 🙂 Expected behavior

Type should narrow to `"ACCOUNT#abc"`.

**Comment by RyanCavanaugh** [comment]
It's admittedly confusing that you have to know whether something is a finite union or infinite union to correctly predict `Extract`'s behavior, but that's indeed what it does. Intersection is usually the better operation.

**Comment by sam-goodwin** [comment]
So, I tried migrating to intersection types instead of Extract, but it does not seem to work with template literal types. 

Intersection types seem to work for `Infinite & Finite` but not `Infinite & Infinite`.

Extract works for `Extract<Infinite, Infinite>` but not `Extract<Infinite, Finite>`.

Does the below look like a TS bug or an accepted limitation?

[TS Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKrIN4ChnINIQCeAXMgAaoDKAogEoDEAJBgM5hSgDmAvmQNw40LaCDgBbCKTYcQnAdyyhIsRCgDymQQRLk1tACJ0mrdl14DcaqABNoASX1TTs+VixhCABxTUAHu0QwOxAYUGBIZABeZD8AhDAAHkF0AB9kNQAaQWxcXG1SMj1DBmZpM35BBQA+AVsEABs4KBQEAHsQNmQIfyhA4NCQcMkYnr6QsMgBbrig8cHIADorWygHAXcvFGDlYXj+iZRogApU9IBKZAAyTTyiAqKjUuceCu5aiAamlvbOpWhd2YDIakbb-D6Ag4CP5QAH7eYQJY2ez6PjIAD0aOQLAAFq0AK71azIECtMDIABGKDgIC6UCgrSgbg83hGMwAYgcoqzevEkrhTplsoJbjpCgYjHByQgKrhqu9Ps1kG0OmTpjywBz4aRYurNUMpqN4nrFstketmVtwGCjZzjgKLtccvg7rpxQxJdL5PLGorlb8rTDwcbhqDAzb4VCAwDg4iVmt0ZicfjCcTSRSqTToPSoEA)

```ts
interface U {
  Key: `USER#${string}`;
  Username: string;
}
interface O {
  Key: `ORDER#${string}`;
  OrderID: string;
}
```

- ✅ `Extract<Infinite, Infinte>`
```ts
type ExtractInfinite = Extract<
  U | O,
  {
    Key: `ORDER#${string}`;
  }
>;
declare const extractInfinite: ExtractInfinite;
extractInfinite.OrderID;
```

- ❌ `Infinite & Infinite`
```ts
type IntersectInfinite = (U | O) & {
  Key: `ORDER#${string}`;
};
declare const intersectInfinite: IntersectInfinite;
intersectInfinite.OrderID; // should not be an error
```
- ❌  `Extract<Infinite, Finite>`
```ts
type ExtractFinite = Extract<
  U | O,
  {
    Key: `ORDER#abc`;
  }
>;
declare const extractFinite: ExtractFinite;
extractFinite.OrderID; // should not be an error
```

- ✅ `Intersect & Finite`
```ts
type IntersectFinite = (U | O) & {
  Key: `ORDER#abc`;
};
declare const intersectFinite: IntersectFinite;
intersectFinite.OrderID; 
```

**Comment by fatcerberus** [comment]
Your `ExtractInfinite` really shouldn’t work since the type given isn’t assignable to either `U` or `O` (it’s missing a property).

**Comment by fatcerberus** [comment]
On the above note, `ExtractFinite` fails because neither `U` nor `O` is assignable to ``{ Key: `ORDER#abc` }``, so both get filtered out.  The only one that baffles me is `Infinite & Infinite` - that seems like it should work.
