### ISSUE TITLE
infer function generic signature from actual function's return type

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#49618]
# Suggestion

```js
function test<T>(fn: (prev: T) => T) { }
test((prev) => ({ a: 1 })); // T is inferred as "unknown"
```

## 🔍 Search Terms

Maybe an issue exists, but I wasn't sure what to search for. "Infer generic function type from return value" didn't really help.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code. _not sure_
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`T` should be inferred as the type of the returned object, `{a: number}`

## 📃 Motivating Example

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygHgCoD4AUwYAXIvgA4BOKAbqdgJSIC8uijiA3ogL4BQqDPgrUaTVmW4BDUgEZeDBgG4+QA

## 💻 Use Cases

make life easier

**Comment by Retsam** [comment]
It's not that TS doesn't infer the generics, in general, but just that it's inferring it as `unknown` *in this specific case*.

```ts
test(() => ({ a: 1 })); // T is inferred as "{ a: number }" as you might expect
```

---

It looks like the issue here is the unannotated `prev`, since that's `unknown`, `T` ends up as `unknown`.  

In this very simple case (where `prev` is unused), it's fairly easy to see what the right behavior would be, but I suspect that evaluating the return type of a function and using that to infer the type of its arguments (which usually *affect* the return type) is not a simple thing to do.

**Comment by RyanCavanaugh** [comment]
Yeah, I'll reopen #47599 since it's not fully covered

**Comment by fatcerberus** [comment]
Yeah, I understand.  What bothers me is mostly theoretical - the fact that the current behavior basically amounts to:

1. What is `T`?
2. Ooh, `prev` is a `T`, we can infer `T` from the callback the caller passed in...
3. ...except `prev` has no type annotation!
4. Contextual typing says `prev` is a `T`, but we don't know what `T` is yet...
5. Screw it, we'll say `prev: unknown` (i.e. the constraint of `T`).
6. Therefore, `T` is `unknown`.

**Comment by fatcerberus** [comment]
To be clear, my problem isn’t the `prev: unknown` part (that part makes sense), but the fact that `T` ultimately has its own constraint as its inference site.  I guess there’s no mechanism to fix the latter without compromising the former, though.

**Comment by RyanCavanaugh** [comment]
I believe what actually happens is that we collect candidates for `T`, find out there are none, so default it to its constraint, which is `unknown`, and then process the call as if you had written `test<unknown>(`.

It's weird since if you had written `test<unknown>(`, that definitely shouldn't be an implicit `any` error. Maybe we need to make a marker `unknown` to use in zero-candidate inference that isn't allowed to contextually type a parameter - worth experimenting with, probably.

**Comment by RyanCavanaugh** [comment]
@weswigham pointed out this example
```ts
type Box<T> = { contents: T };
function test<T>(fn: (prev: Box<T>) => T) { }
test((prev) => ({ a: 1 })); 
```
It's not clear how we'd turn this into an error -- somehow it's (speculatively) a "`Box<implicit any>`" which isn't really a thing - implicit any arises when a binding should have a contextual type but doesn't, but that's not what's happening here. And zero-candidate inference is not a manifest error either:
```ts
function test<T>(x?: T): T;
test();
```
So there seems to be some difficulty in establishing what rule exactly would turn the OP example into an error without either breaking something that shouldn't be broken (benign zero-candidate inference), failing to break something equally suspect (`Box<`), or both.

**Comment by blaumeise20** [comment]
Does TypeScript have a Hindley-Milner type system? Because I'm pretty sure it would work with that kind of type inference.

TypeScript would see that the return type and first parameter have to be the same, so it could check for return type and see "oh it's an object literal with type `{ a: number }`". And because it knows that `prev` must be of the same type, it can say that `prev` is of type `{ a: number }` too.

It seems like it doesn't work like that now, right?

**Comment by fatcerberus** [comment]
No, TS's type system is not H-M.  Type inference is done locally.  See https://github.com/microsoft/TypeScript/issues/30134.

Your example of inferring `prev` based on the return type was [discussed above]:(https://github.com/microsoft/TypeScript/issues/49618#issuecomment-1162391274)

```ts
function test<T>(fn: (prev: T) => T) { }
test((prev) => {
  return prev ? 0 : 1;
});
```

would infer `T = 0 | 1` under your proposed behavior, which isn't ideal (`number` would be more useful).  In general this behavior would tend to infer types that are too narrow.

**Comment by trusktr** [comment]
Interesting points above. I can describe a real-world use case. Suppose we have a `memo` function that is reactive, and re-runs any time dependencies used inside of the function body change. The `memo` tool can be called in two ways:

```js
const fname = reactiveVar('John')
const lname = reactiveVar('Doe')

const fullname = memo((prev) => {
  return fname.get() + ' ' + lname.get()
})

fullname() // string, combination of fname + lname
```

In this first case, `prev` arguments can *only ever be* `string | undefined`, where on the very first run of the reactive expression the initial `prev` value is `undefined`. It can *never* be anything.

Any time that `fname.set(string)` or `lname.set(string)` are called, it causes the function passed to `memo` to re-execute to evaluate the new `fullname` and trigger other reactive expressions elsewhere that depend on `fullname`.

The second way to use the `memo` API is like this:

```js
const fname = reactiveVar('John')
const lname = reactiveVar('Doe')

const fullname = memo((prev) => {
  return fname.get() + ' ' + lname.get()
}, "Godzilla Kong") // <--------------------------- HERE, new movie idea

fullname() // string, combination of fname + lname
```

In this case, `prev` arguments will *only ever be* `string`s. They will *never* be anything else, because the initial value use for `prev` will be `"Godzilla Kong"`.

This works totally fine in plain JavaScript, but the main issue is that in TypeScript, it currently requires too much superfluous type annotation.

**Comment by RyanCavanaugh** [comment]
@trusktr did you mean to use `prev` in these examples? Again we have the problem of "you can just omit the parameter".

**Comment by btakita** [comment]
I have a real-world use case related to [a PR](https://github.com/nanostores/nanostores/pull/203) in nanostores.

I'm adding a `cx` function into the `computed` function. The `cx` function takes a callback & auto-subscribes to dependencies by adding itself to a global stack while the callback executes. I'd like to have the return type of the `cx` function be the return type of the callback.

Here is a contrived example to keep it simple. The real use case involves async, but I'm keeping it synchronous for brevity.

```ts
let $firstName = atom('')
let $lastName = atom('') 
let $fullName = computed(cx => {
  return cx(() => `${firstName()} ${lastName()}`) // How do I infer the return type being a string here from it's usage?
})
declare function computed(cx: ComputedCx)
type ComputedCx<R = any> = // <R> will cause a type error in the computed declaration
  (cb: () => R) => R
```

**Comment by alissawix** [comment]
is there a workaround?
is there some way to tell typescript to infer the type from the returned value of `fn`?

`function test<T>(fn: (prev: T | undefined) => T) { }`
