### ISSUE TITLE
Respect project's path aliases for its internal imports when importing from it externally

### ISSUE THREAD

**Issue by DamianGlowala** [microsoft/TypeScript#49611]
# Suggestion

## 🔍 Search Terms

- multi repo
- path aliases
- import

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I am working with a multi repo setup consisting of two different folders and their respective `tsconfig.json` files:

- backend
- frontend

Backend and frontend repos rely heavily on path aliases to avoid relative imports and make the paths cleaner/shorter. Backend folder stores its TypeScript class DTOs in various folders, organised by the database entity type. I would ideally want to import these files directly from the frontend repo. A simple example does work correctly:

Import in one of the frontend's Vue.js components:
```
import type { GetSampleDto } from "@backend/types/dtos/sample-entity/GetSampleDto";
```
Backend's `GetSampleDto`:
```
export class GetSampleDto {
    sampleFieldA: string;
    sampleFieldB: number;
} {}
```

However, this no longer works when `GetSampleDto` extends from e.g. other classes imported using the backend's path alias:

Backend's `GetSampleDto`:
```
import { PaginatedResponseDto } from "#types/pagination/PaginatedResponseDto";

export class GetSampleDto extends PaginatedResponseDto<{
    sampleFieldA: string;
    sampleFieldB: number;
}> {}
```

## 📃 Motivating Example

It would allow sharing TypeScript files in a multi repo setup by respecting the path aliases specific to the repo from which types are imported. Currently types are lost for any internally imported types (e.g. `PaginatedResponseDto` in the above example).

Instead, I need to specify the same path aliases across both repositories so that they line up... a bit verbose. Are there any other obvious solutions that I am missing?

**Comment by RyanCavanaugh** [comment]
Acknowledging that it's a pain, this is the intended behavior. It's not "safe" to use the target project's path mappings because we don't know what the path relationship between the incoming and outgoing projects. There's also the issue of finding *which* tsconfig is responsible for the target's path mappings, which might be ambiguous or even absent in some cases.

**Comment by DamianGlowala** [comment]
Appreciate the above explanation Ryan. Knowing how many potential edge cases are there to cover, I do understand why it is not a feasible feature to implement. Closing :)
