### ISSUE TITLE
Can't check and maping types by string keys

### ISSUE THREAD

**Issue by instant1100** [microsoft/TypeScript#49628]
# Bug Report

### 🔎 Search Terms

Can't check and maping types by string keys

### 🕗 Version & Regression Information

This appeared in TS 4.7.4 when the feature was introduced.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.2#code/C4TwDgpgBA0hIGcoF4oHIA2B7A5gSwDs0oAfdAMywCcctg0BuAWAChRIoBZAQzABVw0VAG8A2jCiFY8BAF0AXFGGsoUdhEUxWAX22sAxlgIJgUHBGBwQKKAAoAlJpkoAfEpVQqFgK5UC6bHwiHVYDIxMoAFteRR5+QRtlFlVAwkUk1VV1RUxcQjQPbQAaD0oaOnSPLMEcstp6Qp1mFjDjUwBreBtzS3gHZuiwUU6QWUSPbKgRkpZtBiA)

### 💻 Code

```ts
type Keys = 'login' | 'forgot';
type MapType = {[K in Keys]: {
  type: K
}}
const getKey = (): Keys => {
  return 'login'
}

const map: MapType = {
  login: {
    type: 'login'
  },
  forgot: {
    type: 'forgot'
  }
};

const key = getKey();
map[key] = {
  type: key,
};

```

### 🙁 Actual behavior
I have got error: Type 'string' is not assignable to type 'never'.   Type 'string' is not assignable to type 'never'.
in:
```
map[key] = {
  type: key,
};
```
### 🙂 Expected behavior
Obviosly, `key` in this case can be only one of `Keys` type  or 'login', or 'forgot' (not both in same time).
I expecting what typescript understand this moment and check types for every key separately

**Comment by RyanCavanaugh** [comment]
TypeScript can't tell this code (which is OK by construction) apart from this code (which is unsafe):
```ts
const getKey = (): Keys => {
  return Math.random() > 0.5 ? 'login' : 'forgot';
}
const key1 = getKey();
const key2 = getKey();
map[key1] = {
  type: key2,
};
```
