### ISSUE TITLE
`node16` module resolution bugs

### ISSUE THREAD

**Issue by jpzwarte** [microsoft/TypeScript#49631]
# Bug Report

See https://github.com/jpzwarte/typescript-node16-bug

That repo contains a simple `index.ts` with a little bit of code.

Turning on `node16` module resolution will suddenly cause typescript to generate errors:

```
index.ts:2:50 - error TS1471: Module 'lit' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.

2 import { html, LitElement, TemplateResult } from "lit";
                                                   ~~~~~

index.ts:4:14 - error TS2742: The inferred type of 'Foo' cannot be named without a reference to './node_modules/@open-wc/scoped-elements/types/src/types'. This is likely not portable. A type annotation is necessary.

4 export class Foo extends ScopedElementsMixin(LitElement) {
               ~~~

index.ts:4:14 - error TS2841: The type of this expression cannot be named without a 'resolution-mode' assertion, which is an unstable feature. Use nightly TypeScript to silence this error. Try updating with 'npm install -D typescript@next'.

4 export class Foo extends ScopedElementsMixin(LitElement) {
               ~~~
```

I originally wanted to create this issue for a different reason. See the `README.md` in the reproduction repo for that information.

### 🔎 Search Terms

node16, moduleResolution

### 🕗 Version & Regression Information

Typescript 4.7.4

**Comment by weswigham** [comment]
Your `package.json` doesn't have `type: module` - `lit` does. `lit` is esm-only, so in node, will only resolve correctly in esm files unless you use dynamic imports. That's why the error says it can't be imported - you can't consume esm through cjs imports directly. That's what the `node16` module mdoes check - for if the TS output will actually run, unmodified, in _node_. You're probably using a bundler of some kind - you probably _don't want_ the format checks `node16` provides, since node's builtin esm interop is honestly painful to use.

**Comment by weswigham** [comment]
Or you can just write `type: module` in your own `package.json` and stuff'll _probably_ work like you want, depending on how whatever tool you're building with is ocnfigured.

**Comment by jpzwarte** [comment]
@weswigham thnx, I can confirm it works. But with `"node16"` module resolution I then get this: 

```
index.ts:4:14 - error TS2742: The inferred type of 'Foo' cannot be named without a reference to './node_modules/@open-wc/scoped-elements/types/src/types.js'. This is likely not portable. A type annotation is necessary.

4 export class Foo extends ScopedElementsMixin(LitElement) {
               ~~~
```

Which seems to be a new type of error (no errors with `"node"` resolution). My guess is that not all types are public API and that's where the error is coming from?

**Comment by weswigham** [comment]
Yeah, some named types used in the inferred type of the expression can't be accessed directly by the modules exported in the package's export map. There's no uniform way to fix this (sometimes compatible types _are_ exported but aren't exactly the same, sometimes you need to write a structural equivalent), so the error suggests you manually annotate the types. In this case, the type of the `extends` clause - if you extract the extends clause expression to a separate variable declaration and annotate its type explicitly (which is what declaration emit would normally try to do for you in the output when this error doesn't occur), you can resolve the error.

**Comment by smaye81** [comment]
I am running into this issue also and only with `moduleResolution` of `NodeNext`.  `Node` works fine for us.  The explanations make sense to me as to why this is an error but just for my own edification, why is this not an issue with `moduleResolution` of `Node`?
