### ISSUE TITLE
exported const arrow function returning `never`: no CFA

### ISSUE THREAD

**Issue by ryanrhee** [microsoft/TypeScript#49640]
# Bug Report

Unable to type an exported const arrow function as returning `never` and have it participate in control flow analysis (CFA)

This is similar to https://github.com/microsoft/TypeScript/issues/37998 but notably different in 2 ways:

1. it deals with exporting a const function for consumption by another module
2. the workaround of adding type information to the `const` isn't possible, since it's exported

### 🔎 Search Terms

unreachable code, return never, arrow function, CFA

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about returning `never`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEDMEsBsFMEYB0AXAzgWAFBcgWwA4D2ATsqPsYQMayqoSW6gBEF1tqzWOAdsrMXABDGqACiADyKlYAEwDyAIwBWsKmQDeWUDtCoAFoQDuACVjR8ALlAAKAJSgAvAD5QPWADcBWAL7dMVIQ8qGSwUiT8CipqyNaS0pFKqupOoFqYunqGpuZWtg4uaaCBwYRwiNCEAOY2zPq5oPwSyMx2ANzklDR0iGGQyPagfpjDWGEJoLKwwgCu0KHhMlHJyP4goAC0W9s7u3v722tgUHAATCgY2JjreBPjEXJJMQyETMyIwCcIXFclIUUGYxmCxDVL3JZPdRYQE5Cz2fx-MqwCrVGwAcmQ+kg9EBc1koEUsFAMx4xFgIn0QkUcAJMzI2LchGQaLsR1ARhIAGshJQSbIsH8yDDgfhTtZkABPfCwQjgLJAhqOeWw-DQ7Ii07wgJBVBIlE1DFY+jQSDuAA0jUMMyq+gtskItFAVVgZFwPM5clAQnoJLJFKpcBZWCAA)

### 💻 Code

```ts
// file1.ts

import process from "process"

interface ExportedObject {
    showHelp: () => never
}

const exportedObject: ExportedObject = {
    showHelp: () => { console.log("help text"); process.exit() }
}

export default exportedObject

// -------------------------------

// file2.ts

// import exportedObject from "./file1"

const { showHelp } = exportedObject
showHelp()

console.log('this should be unreachable but is not')

// workaround
const showHelp2: typeof showHelp = showHelp
showHelp2()
console.log('this line, though, does get marked as unreachable')
```

### 🙁 Actual behavior

`Unreachable code detected. (7027)` warning

### 🙂 Expected behavior

No warning

**Comment by fatcerberus** [comment]
```ts
const { showHelp } = exportedObject
```

This line is the problem: `showHelp` has no type annotation, which violates

> each identifier in the function name references an entity with an explicit type

per https://github.com/microsoft/TypeScript/pull/32695.

In line with the above, this works:
```ts
exportedObject.showHelp();
```

**Comment by MartinJohns** [comment]
> but how would you type `showHelp` in that line?

Just as you would type any variable declaration.

```typescript
const { showhelp }: { showhelp: TypeBeHere} = ...
```

**Comment by ryanrhee** [comment]
I am still unable to get this to work. I think I need to show a fuller example that more closely mirrors what I have.

FYI the real-world example I opened this issue from is shown here https://github.com/sindresorhus/meow/blob/main/index.d.ts#L271 : using this library, calling `showHelp` doesn't tell typescript that execution ends.
