### ISSUE TITLE
Omit on a discriminating union with intersection remove the properties of accessing the union elements

### ISSUE THREAD

**Issue by akhilmhdh** [microsoft/TypeScript#49659]
# Bug Report

### 🔎 Search Terms

- Omit
- Discriminated union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 4.75 or anything above 4.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/PTAEBMEsGcGMCdIFtIDsAuBTcoCurIB7VUScTDSAM0k3gCgLclQApQgI1AG97R+2nAIygAvKABEAK04BaIRIA0fAew4AmMZJkdZ6ifQC+9eiDwFioGvGjpQmADaYkFdPXQBPAA6ZBHEeK8AqCePgBcfgB0akLKwV4Ahh4OhAngERIAFpAGxqZg+EQk0JiwxDiOzq7u3r5qmoEq-KGYEWrRnOpxAonJqeDqGdm5JmaFloRUIQDuhCG10DU+ftBaMaAAPn7qo2AJ88tlSEiW6HMchOiZ5kVLdZwAQgklWkECtgnwWOmgACIJWG6-Ao5B+-ywRl2pAwdBKsHQtxaoAAYmgEg41GtOKsAGR+J4lADcUKuFFAhBQdmgFN8NEc4FWVHgFOhWBspQRp1qihCmVwqzQbLhnJIsgAfOTKXdQAAVTC2NQAdUgVwA8pStOqVQAeVGodFqRQSD5fbASTaSEFmsUk7KrYi+Ckq0ircAO8kkDjPXywBzPVakkiC2Ecoo8q78yXO8WskPwxG1WXy9BKwjwADWaAA5liOLjQFr0Nq1ATMEaTd9zVsJFbwBIbflQLMMKBoJlCNNebTaA4GeSplA4IgUDCcONUPQyqhbCFk9m1DLE+IABQJMJyhWcZVqykASjEEre-Goq8iSNEF6iMV3R+CoDM+xgoFQl1b7em2fJpPg5I4Ug5Vg9jgDiQOmvi9CkaT2OgsBNHeU7Uk4kQpFmp4tLucHGHkCF2FgtjzpwMqZACippumqwrmuG4pluZHZvuoiHnBJ4JGeS6Xu0163sED4us+HZvh2n4AG6fEQkZ0r2AokIOCDIMGY4WBOd4CAhhBIShp4Qf0GHBFhJhAA)

### 💻 Code

```ts

// discriminted union identifier
enum Job {
    Job1 = "job-1",
    Job2 = "job-2"
}

// union first element
type Job1 = {
    type: Job.Job1,
    payload: "hi"
}

// union second element
type Job2 = {
    type: Job.Job2,
    payload2: "hi"
}

// union of two types
type Jobs = Job1 | Job2

// a type common to both union
type JobBase = {
    started: Date,
    ended: Date
}

// intersection
type FinalJob = Jobs & JobBase;

// then omit some fields from intersection type, thus intersection -> omit
type TestJobWithOmit = Omit<FinalJob,"started" | "ended">

// this one omit is done on base class then intersection, thus omit -> intersection
type TestJobWorking = Jobs & Omit<JobBase,"started" | "ended">

// wont show the fields of discriminted union
const testingJobType = (a:TestJobWithOmit) => {
    if(a.type === Job.Job1){
        // a is not showing other object field like payload etc
        console.log(a.type)
    }
}

const testingJobThatWorks = (a:TestJobWorking) => {
    if(a.type === Job.Job1){
        // a is now showing various fields in discriminted union
        console.log(a.payload)
    }
}

```

### 🙁 Actual behavior

When omit is applied over a  discriminating union with intersection, the discriminating property is lost. This happens only when the omit gets applied over this combination.

<img width="1080" alt="Screenshot 2022-06-24 at 12 11 48 AM" src="https://user-images.githubusercontent.com/31166322/175377025-abf418c1-7554-45c8-84fc-aeb8680916d5.png">

As I shared above `TestJobWithOmit` when i conditionally pick the union element, it doesn't show the values of the discriminated ones. But as i shown in codebase if i apply omit before intersection with union it works fine

### 🙂 Expected behavior

I should be able to omit fields of an intersection applied discriminated union.

**Comment by RyanCavanaugh** [comment]
This behavior follows from the definition of `Omit`, which is a mapped type. A mapped type operates on `keyof` the mapped type, which for a union is only the common keys, so the output is a new type containing only the common members.

What you want here is to distribute over the union and omit on each constituent:
```ts
type DistributedOmit<T, K extends keyof never> = T extends unknown ? Omit<T, K> : never;
// Works
type TestJobWithOmit = DistributedOmit<FinalJob,"started" | "ended">
```
which works as expected

**Comment by akhilmhdh** [comment]
My bad, I should have understood more in depth on how omit works. Closing this issue.

Thank you @RyanCavanaugh  for taking your time resolving my issue.

**Comment by ducminh-phan** [comment]
@RyanCavanaugh Could you explain how `DistributedOmit` works for union types?

**Comment by MartinJohns** [comment]
@ducminh-phan See the documentation: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

`DistributedOmit` is a conditional type, so the type argument `T` is distributed. This means if `T` is typed `A | B`, then you end up with `Omit<A, ..> | Omit<B, ..>`.
