### ISSUE TITLE
Omit outputting incorrect types for types with mixed `[key: string]: string | undefined` and defined field types

### ISSUE THREAD

**Issue by james-reed-toshi** [microsoft/TypeScript#49656]
# Bug Report

Using `Omit` and `[key: string]: string | undefined` together can result in Typescript not preserving the types of fields on the original type. Playground link here to display the issue: [playground link for issue here](https://www.typescriptlang.org/play?ts=4.7.2#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBDIKMjJBhLCrcbgE4QAb0UJRKAG14pA8PkrqhKJxmABdXmCfnDUAAH1AXG4kGSGUg3AA3Ky2dBFQBGUXiwWqtluRUAJh1AuY+rZBHgYoQctNw0UAF9ydtvtSlrQbqiWQaKNx7Xq1SUCI5UDzxvB4C1OBaSgx6YzeQB5RDyAA8dIZ+kE-AA5BrOJAjbmAHyq52KBCcMXzL2oABiFB+qF5nqcqIAvKAfWy-bzc7neEHa2Qw7zqdBBJAhwb41nBAVu8ODQXINrQAOZwbLdbULbIP3B8PHUPHarK40awrOAxoJnE5UE9nQF2eyVV+uQ+2G02xQE54yAQfluwa7vuvJfiiP7Nv+T4LgEVo2vAcogYahYmhuR4VioODNB4ZBeIg8B9AwwLsDQXxuGYzDsAwzDTiYGqwIkpHwHoIheAARAAoqsDCIAs+icUk2KceADioLmwgAHKQBInFBCoSZfGQ7xTvw9FHKgoZKuMeCgE4RE6BKXxTmiiDQsIlyURIxHRCIBgcNiCxMKwHA8EEJRAA)

The issue is that the fields that were previously defined as strings, are now returning as `string | undefined`, even though there's no reason they should, type-wise. If you remove the `[key: string]: string | undefined` the problem goes away, and typescript is obviously clever enough to know that the fields `line1`, `line2` and `postcode` are just of type `string`, not `string | undefined`.

### 🔎 Search Terms

`omit`, `omit undefined`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Omit

### ⏯ Playground Link

Link given above

### 💻 Code

```ts

interface Address {
    [key: string]: string | undefined;
    line1: string;
    line2: string;
    postcode: string
}

interface Parent {
    id: string;
    party: boolean;
    address: Omit<Address, 'line2'>;
}

const parentFirst: Parent = {
    id: '',
    party: false,
    address: {
        line1: '',
        postcode: '',
    },
};

const finalAddress: Address = {
    line1: parentFirst.address.line1,
    postcode: parentFirst.address.postcode,
    line2: '',
}
  
// (property) Address.line1: string
// Type 'string | undefined' is not assignable to type 'string'.
//   Type 'undefined' is not assignable to type 'string'.(2322)

// Same error happens for poscode
```

### 🙁 Actual behavior
Omit does not preserve the types of the named fields

### 🙂 Expected behavior

Omit should preserve the types of the named fields

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/issues/45367#issuecomment-894824726

**Comment by RyanCavanaugh** [comment]
> why is this not how Omit is coded

`Omit` is a type alias for a thing whose code you can read; it isn't a higher-order operation that understands what it's doing at a higher level.
```ts
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
```

It's generally pretty hard to work with types that have index signatures along with their declared types; I would rewrite this as
```ts
interface Address {
    line1: string;
    line2: string;
    postcode: string
}

interface Parent {
    id: string;
    party: boolean;
    address: Omit<Address, 'line2'> & { [key: string]: string | undefined };
}
```

**Comment by james-reed-toshi** [comment]
@RyanCavanaugh This is unfortunately a more legacy codebase and I can't remove the index signature without a lot of work elsewhere.

**Comment by james-reed-toshi** [comment]
> Omit is a type alias for a thing whose code you can read; it isn't a higher-order operation that understands what it's doing at a higher level.

I understand that, but if it can do that _and_ do better for the user, what's the downside with defining it as I did above with `FieldTypePreservingOmit`?

**Comment by RyanCavanaugh** [comment]
Ah, good question.

`FieldTypePreservingOmit` uses the key remapping feature that didn't exist when `Omit` was written, and changing the definition of `Omit` after the fact would be a breaking change. One of the reasons we don't like adding type aliases to the built-in lib -- we can't "upgrade" them!

**Comment by RyanCavanaugh** [comment]
We don't issue large breaking changes, regardless of version numbers, unless there's a very identifiable concrete upside. I don't think tweaking `Omit` for this scenario would meet that bar.

**Comment by JamesZoft** [comment]
That’s unfortunate - how would I go about overriding Omit with this improved version then?

Thanks,
James

**Comment by RyanCavanaugh** [comment]
`--noLib` + provide your own copies of the lib files

**Comment by JamesZoft** [comment]
I see - is there no way to override it in a namespace like you can with other types in libraries?

**Comment by RyanCavanaugh** [comment]
You can lexically shadow it (including at module scope), but you can't globally clobber it

**Comment by JamesZoft** [comment]
So I’d need to define/import the type override in every file where I want it?
