### ISSUE TITLE
`keyof never` changed between TS 3.3 and 3.5

### ISSUE THREAD

**Issue by lorefnon** [microsoft/TypeScript#49651]
# Bug Report

### 🔎 Search Terms

keyof never

### 🕗 Version & Regression Information

- This changed between versions 3.3 and 3.5

### ⏯ Playground Link

[TS 3.3](https://www.typescriptlang.org/play?ts=3.3.3#code/C4TwDgpgBAKlC8UDWEQHsBmUB2EBuEATgNxA)
keyof never evaluates to never

[TS 3.5](https://www.typescriptlang.org/play?ts=3.5.1#code/C4TwDgpgBAKlC8UDWEQHsBmUB2EBuEATgNxA)
keyof never evaluates to string | number | symbol

### 🙁 Actual behavior

keyof never is string | number | symbol

### 🙂 Expected behavior

keyof never used to be never, and that IMHO was correct behavior. 

This change happened in a minor version but it introduces a breaking change in libraries which relied on the older behavior 
Ref: https://github.com/juanluispaz/ts-sql-query/issues/40

**Comment by MartinJohns** [comment]
Duplicate of #33025. Used search terms: `keyof never in:title`

**Comment by lorefnon** [comment]
@MartinJohns Thanks for sharing. The reasoning is a bit mind bending for me, but good to know that this was an intentional change.
