### ISSUE TITLE
Automatically deduce the parameter type in the callback function

### ISSUE THREAD

**Issue by Sylvenas** [microsoft/TypeScript#49665]
# Bug Report
Automatically deduce the parameter type in the callback function

### 🔎 Search Terms
callback, object deconstruction, type deduction

### 🕗 Version & Regression Information
Playground version V4.7.4

### ⏯ Playground Link
[Typescriptlang Playground](https://www.typescriptlang.org/play?ssl=19&ssc=53&pln=1&pc=1#code/C4TwDgpgBAwghgGwQITgYwNZQLxQBQD6AXFAHYCuAtgEYQBOAlDgHxlW10BQnAZuaWmABLAPakoAZwCOGPAG8AHgF8iiohRr0lDEgAU6IykIkQAPBo7MA3FCi9+g0eOmzFAGjSIE1dBhVqLeg8vH0wieCRUTG0SADcRIQATK3sBYTFJGXkFYKRQv1UFdXYgzzzfAH5wryi-HSh9Q2MzQLpmAB94pNs5TlshHjwy718GXtsoYfz8BSgAKigFBhTbJT6oOghgcjpxRqMTADpNiREEWIg8Jc41zgB6O6hAGXIoAAt6aBEdyZDfKAB3IRIDYQNAQIQXKBwNiaOhuKDUcjAKDAd5QAAGCnRP1IgAwCZEI6CJCCJchgxKcNBiCTItDUHCZVxFACs8KmviIfDSTiuTHGk2pZwghwQIgA5ryViDtrtFjYJrYbtoUvdHoBQckp1ORYAMB2guBc2SIzO0h1REFIV2wzDkVNIpwQwtFEqW2iAA)
### code
``` ts
type CallBack = (_: number) => number

function sqk({x}:{x:number}): Promise<number>;  
function sqk({x,callback}:{x:number,callback:CallBack}): void;
function sqk({x,callback}:{x:number,callback?:CallBack}): Promise<number>|void  {
  if(callback){
   callback (x * x);
  }
  return Promise.resolve(x)
}

// ❌ here our callback will receive a number, but the `x` can‘t  be deduced
const cb = sqk({x:5, callback:function(x) {
  console.log(x);
  return x;      
}});

// ✅
const promise = sqk({x:5}).then(x=>{console.log(x)})
```

### 🙁 Actual behavior
Callback will receive a number, but the  type of `x` can‘t  be deduced

### 🙂 Expected behavior
A possible solution is to remove the callback from the object as the second parameter，as follows：
``` ts
type CallBack = (_: number) => number

function sqk(x:number): Promise<number>;  
function sqk(x:number,callback:CallBack): void;
function sqk(x:number,callback?:CallBack): Promise<number>|void  {
  if(callback){
   callback (x * x);
  }
  return Promise.resolve(x*x)
}

// ✅
const cb = sqk(5,(x)=> {
  console.log(x);
  return x;      
});

// ✅
const promise = sqk(5).then(x=>{console.log(x)})
```
But this doesn't answer my question, why the first solution doesn't work？is it a bug?

**Comment by RyanCavanaugh** [comment]
Overload resolution always picks the *first* overload that matches, so the second overload won't ever get picked. You need to reverse the order of them:
```ts
function sqk({x,callback}:{x:number,callback:CallBack}): void;
function sqk({x}:{x:number}): Promise<number>;  
```

**Comment by Sylvenas** [comment]
Thanks for your help, pointing out the key points, I think I need to read the docs more confidently, this question can be closed.
