### ISSUE TITLE
Object literals allow duplicate `[Enum.member]: ...` keys

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#49666]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDA3gWAFA2zA2gRgF0AuGAJgBpMc8jTLMB6R7APXZgFEAlbgeW6kAgmBggARgCsApsFgAbAJZRpAJwCG8mMHVgwIWAAt1AN2kwAtgFd5URQAd55+6pD21d6RBgB3ZYZgoQ3MIdQtzMDDpADoYAAp8RIB2AEpMAF8AbkxMaTArCy58wpQYADMQECQYfAoYdJyMUEhYAE9q9CwcXE5i6IqQEnIqLuwevoGhhgxmNnZ5hZgAOSrOVVdVDMygA)
    
### 💻 Code

```ts
const x = {
    [1]: 2,
    [1]: 2,
//  ^^^ ERROR: An object literal cannot have multiple properties with the same name. (1117)
};

enum Enum { foo = 1, }

const y = {
    [Enum.foo]: 2,
    [Enum.foo]: 2,
//  ^^^^^^^^^^ No Error
};
```

### 🙁 Actual behavior

Defining an object literal with duplicate keys throws an error for literal `1` but not for enum member `Enum.foo`

### 🙂 Expected behavior

Defining an object with duplicate keys from enum members throws an error
```ts
    [Enum.foo]: 2,
    [Enum.foo]: 2,
//  ^^^^^^^^^^ An object literal cannot have multiple properties with the same name
```

**Comment by Andrew-Martin1** [comment]
Note: This issue isn't specific to enums, it happens with string variables as well

```ts
const myString = "foo";

const y = {
    [myString]: 1,
    [myString]: 2,
//  ^^^^^^^^^^ No Error
};
```

**Comment by nnguyen01** [comment]
Is this released yet? Still seeing the error 

```const myString = "foo";

const y = {
    [myString]: 1,
    [myString]: 2,
//  ^^^^^^^^^^ No Error
};```
