### ISSUE TITLE
Unable to infer array type information from generic

### ISSUE THREAD

**Issue by joshuat** [microsoft/TypeScript#49660]
# Bug Report

### 🔎 Search Terms

array infer generic

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about array inference from generic types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAggTnAhiAogGwgWwgO2AHgBUA+KAXigDkB7HSgVzTUQCMMjSIAPYXAEwDOsBMnwBLHADMIcKClIB+OVABcUQgG4AsAChdoSFVoBxXDLEBjGMGCyKAb11Qok6tTUs3GRDm07nLIhwavBIIPie1N44xH4Avrq63GDUcMBQFrQC6ZL0OBbkUPhOsDZwQty8OIJGOKY45lZlADS6xAAUAJTkpI7+UAD0A1AA7qkA1kKIFVyQFrx8JZk42VC82QCMIWUCANoA5K7U+wC6hZKIaAIQfiVDUDjU6WNw4xIA5lACEhbQ1rZCMRCAT0MBgNBiCB8KAANzEiCg7zMcEsSyy6XWwAATCERKgMNg8Ph-uUDkdTqQKBcrjc0SsMRBsgBmXFhdBYXAEEl7faBOAU86Xa63fr3bJiJijCYfKDTKDJCDzKF01aYgAsahodWRlhJZLcp0FNJFznujxGUteMu++Wg9Btny19UaJJVDOyAFZWch2YSCE6dU1bPrjidKS4hbT+stVYzgAA2b34jlEgMNFFBuAHPkCqmR+J+IA)

### 💻 Code

```ts
type ArrayElement<T> = NonNullable<T> extends Array<infer E> ? E : T;

type NonGenericAttr = {
  foo: boolean;
  bar: Array<boolean>;
}

export const func = <
  Attrs extends NonGenericAttr,
>() => {
  // works as expected
  const test1: Attrs['foo'] = false;

  // not working since Attrs is supplied via generic
  const test2: ArrayElement<Attrs['foo']> = false;
  const test3: ArrayElement<Attrs['bar']> = false;

  // still working as expected
  const test4: NonGenericAttr['foo'] = false;

  // now working since using NonGenericAttr
  const test5: ArrayElement<NonGenericAttr['foo']> = false;
  const test6: ArrayElement<NonGenericAttr['bar']> = false;
};
```

### 🙁 Actual behavior

When attempting to infer the Array type from a generic-supplied type it fails, saying the specified type (in this case boolean) is invalid

### 🙂 Expected behavior

Have similar behavior for both generic and non-generic types (assuming the generic is constrained)

**Comment by joshuat** [comment]
Hey @RyanCavanaugh - thanks so much for the super fast response, I know these tickets pour in and responding to all of them is really remarkable.

I'm curious why in your supplied example `ArrayElement<Attrs['foo']>` evaluates to `true` while `Attrs['foo']` evaluates to `boolean` despite both reading from the same property. This might be a gap in my understanding of how infer works here.

**Comment by RyanCavanaugh** [comment]
Basically, some operations defer, and some don't. It's a bit inconsistent since *always* deferring makes it very difficult to write any code that works at all, and *never* deferring is impossible.

**Comment by joshuat** [comment]
Ah - I see. I appreciate the clarification, what really threw me was that inconsistency between directly accessing the property from the generic and accessing it via `infer Array<>`. Glad to hear that's at least well known. Thanks again for taking the time to help me out!
