### ISSUE TITLE
error TS2365: Operator '+' cannot be applied to types 'string | number' and 'string | number'.

### ISSUE THREAD

**Issue by borisovg** [microsoft/TypeScript#49661]
# Bug Report

Code does not compile.

### 🔎 Search Terms
"Operator '+' cannot be applied to types".

### 🕗 Version & Regression Information
4.7.4

### 💻 Code

```
const foo = { foo: 123, bar: 'bar' };

for (const k of ['foo', 'bar'] as const) {
  const val = foo[k];
  console.log(val + val);
}
```

### 🙁 Actual behavior
```
src/test.ts:5:15 - error TS2365: Operator '+' cannot be applied to types 'string | number' and 'string | number'.
```

### 🙂 Expected behavior
No error.

**Comment by RyanCavanaugh** [comment]
Operations are evaluated according to the types of their operands, not their identities. The left-hand type is `string | number`, the right-hand type is `string | number`, and the rules for `+` disallow an ambiguous operation like that. Whether or not the LHS and RHS refer to the same variable (or what "same" would even mean apart from bare identifiers) isn't an input to the algorithm, nor is it clear how that could be generalized.

**Comment by kelvinsekx** [comment]
Experienced something similar.
```js
function universalAdd(monoid1: string|number){
  return monoid1 + monoid1;
}
```

It took me sometime to understand your statement **"types of their operands, not their identities"**. But I got it thanks @RyanCavanaugh

**Comment by kelvinsekx** [comment]
can we close this issue already?

**Comment by haptn** [comment]
> Operations are evaluated according to the types of their operands, not their identities. The left-hand type is `string | number`, the right-hand type is `string | number`, and the rules for `+` disallow an ambiguous operation like that. Whether or not the LHS and RHS refer to the same variable (or what "same" would even mean apart from bare identifiers) isn't an input to the algorithm, nor is it clear how that could be generalized.

I'm sorry but I'm still not clear on the problem here. If I replace the union type of `string | number` to type `any`, things will work normally.
So what I'm confusing here is that does the `+` operation only accepts input with _single types_ (`number`, `string`, `any`), but not _union type_ (`string | number`)?

Thank you!

**Comment by nishat-md-r-rafi** [comment]
If you are sure about the type by type guard operator "typeof". and then assume the type using "as"
