### ISSUE TITLE
Type of a generic is not narrowed

### ISSUE THREAD

**Issue by valya-smoryakova** [microsoft/TypeScript#49676]
# Bug Report

### 🔎 Search Terms
discriminated type union, narrowing, generics

### 🕗 Version & Regression Information

- This changed between versions 3.3.3 and 3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.5.1#code/C4TwDgpgBAglC8UDeAoK6oGcBcXgCcBLAOwHMBuNDY3YgVwFsAjCfSgX0pQHpuoBpKAAtW0BgEMQUFlADkmWQB9ZxWVAD2+OQo1aVagBRM6wKMXWniEAG6so4zFACSUOsQAmrTMHEeANPaOAGZQAMa+5qbioaEQYFH4pIwQxKbqIaCQZjZ2JFD4bsCEDBAAlChBbqFF6sRQQQA8ghAAHsAp7o4A1hAg6bAAfAY9ILj8pbgwANr8ALrIVOihtd5QXQCMuJkQ-SMI2rLkGFC8zqaEjssMYAA2EO03UkEk0EGaUMBCF1A3Lx-qwnEtnsdVY+HeBgcUEI50c6hMmEInmhIVCIlCXRB7gEUAkUhk+nKixRUGGvQQ8EQ8lkpQWx2OpycdSC0VMAHdoF1zGyPkJxKZthoQi0KVSdCJ8BAAHTEhl8AAqQjojklwDo+Dqgol0EwQnhN2xMmm1PmeQsEqgbM0nWhpl1+sN0HEeCIZFlGFOACETFB5eAIABlUJEeJ4Qg3G68khdRww6FwjL+2AzWbu9BpsIrUxdABMW39u3JYsOHr47nUEEckUtmi6UqgAAlRM4oK1INUPgWQntgACCQoM8tiKtQpMUxgqe1vCW5VBy5WzBYa-g643my42xAO9MuvNe9IdQQSKRB1m52OTftZFPgDPS8uYxmM6r1XVr5Xb0d6d-Z-Oq0urRXesm0lFtNw7d9p3+A9AkIUhiHEJg7mg6Y5mJdhiWJQggjJKRKSpVRaVQH98nuV8oHWAAGL8SNok4+E+HVxBKdCUGJT5wR5KweQAUXwcF8AMUoOBQIA)

### 💻 Code

```ts
type A = {
    s: string;
    n: number;
};

// K here may be 's'|'n' or 's' or 'n' (but not never as I understand, as f cannot accept argument of type never in runtime)
function f<K extends keyof A>(key: K): A[K] {
    const k1: typeof key = 's';    // It is completely fine for this line to have an error (as it is outside if check and K may be 'n')

    if (key === 's') {
        // In fact we know that type of x === 's' here.
        // Thus return type here should be A['s'] in other words it should be a string
        // But TypeScript still thinks it is of type A[K]
        
        const k2: typeof key = 's';   // does not work. Here I expect typeof key to be 's'
        const c: A[K]   = 'test';     // does not work. Here I expect A[k] to be string
        const d: A['s'] = 'test';     // works
        
        return 'test';                // does not work. Here I expect 'test' to be asignable to A[K]
    }
    
    if(key === 'n') {
        return 10;                    // the same
    }

    throw new Error();
}
```

### 🙁 Actual behavior
Typescript ignores the check on the variable typed with a subtype of union type and is unable to narrow type

### 🙂 Expected behavior
Typescript narrows the type

My guess is that this behavior may somehow be related to https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/#fixes-to-unsound-writes-to-indexed-access-types

**Comment by gerich-home** [comment]
Looks similar to https://github.com/microsoft/TypeScript/issues/49676

**Comment by jcalz** [comment]
Or #33014
