### ISSUE TITLE
Typescript 4.7 package.json exports

### ISSUE THREAD

**Issue by stoivo** [microsoft/TypeScript#49670]
# Bug Report

After reading about exports in [4.7 realeasenotes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#package-json-exports-imports-and-self-referencing) I wanted to test it out, but I can't make it work.  
I created an [example app](https://github.com/stoivo/test-typescript-package-exports) of something I think should work. I would very much appreciate some help to make it work. Or understand why it should't work.

I get errors like `Cannot find module 'dep' or its corresponding type declarations`. If I open a node session It ut can import dep just fine. 

### 🔎 Search Terms

typescript package.json exports  
typescript package.json exports types definition
package.json exports types
package.json exports map  with types

### 🕗 Version & Regression Information

I think it has never worked... not sure

### 💻 Code

I make a repro case https://github.com/stoivo/test-typescript-package-exports

### 🙁 Actual behavior

Checkout the readme in example app

```
> tsc -p tsconfig.json

src/lol.ts:1:19 - error TS2307: Cannot find module 'dep' or its corresponding type declarations.

1 import {add} from 'dep';
                    ~~~~~

src/lol.ts:2:17 - error TS2307: Cannot find module 'dep/sub' or its corresponding type declarations.

2 import sub from 'dep/sub';
                  ~~~~~~~~~


Found 2 errors in the same file, starting at: src/lol.ts:1

```

### 🙂 Expected behavior

It to work

**Comment by olivier-martin-sf** [comment]
Just my two cents here but have you tried to set `moduleResolution` to `nodenext` in your `tsconfig.json`?

**Comment by stoivo** [comment]
Yes it worked! Thaks, node16 also work.

**Comment by stoivo** [comment]
Thanks alot. 
```
src/lol.ts:1:19 - error TS2792: Cannot find module 'dep'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

1 import {add} from 'dep';
                    ~~~~~
```

Maybe the error message should be improved since it seam to recommend `node`. probably where I got it from.

I can't find much information about moduleResolution, do you have any links. I found the official https://www.typescriptlang.org/tsconfig#moduleResolution but I find it a bit lacking. How would I knoe that I need to switch to if to suport exporting?
