### ISSUE TITLE
Cannot export class expressions

### ISSUE THREAD

**Issue by Back-io** [Microsoft/TypeScript#4968]
```
var SomeClass = new (class
{
	
});
```

Yields:
Exported variable 'SomeClass' has or is using private name '(Anonymous class)'.

Bug? Spec?

(My goal was to use this structure as a singleton class of sorts, rather than making a class and remembering to mark all members as static)

**Comment by mhegazy** [comment]
This error is generated as the compiler is writing the declaration file; it could not write a type annotation for your variable; generally a class types can not be inlined as  an object type literal, and the winter does not introduce new named declarations that were not in the file. One possible change is to allow for class expressions to be used at type position. 

To Silve this issue, either make it a class declaration or give your variable an explicit type annotation so the .d.ts file can use it instead.

**Comment by Back-io** [comment]
Ok, so I guess this doesn't work then. I was hoping for an improved syntax for static classes that doesn't involve exporting two members (Thing and ThingStatic), or remembering to make every member static.

**Comment by ahejlsberg** [comment]
Just as an aside, a simple way to make a singleton is to export a namespace:

```typescript
export namespace Utils {
    export function foo(...) {...}
    export function bar(...) {...}
}
```
