### ISSUE TITLE
`Omit` utility type throws away details of union types

### ISSUE THREAD

**Issue by ducminh-phan** [microsoft/TypeScript#49688]
# Bug Report

### 🔎 Search Terms

omit union broaden types

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about union types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAygxgCwgEwK4BtoF4BQUoA+UA3nvuQM6IoYoBcUwATqhANxnlRVJqYAqASwC2EBgDtUwgEYQmHLgF8yRUl3w8amZAwBmAQ3QV2nStT4QhoiRnQLyijjlCQoASWARhULCTKCdKEkZOXtxfWtuZkFxAHMORSgAMlhzWicAegyoAJyKKH1UYAB7AFpYiHE5fU9kHCyoeuyAMSZi7xiKSDhgQWLxABooAGEmCBqIDy8AERr9PKgIAEdUQQA3Q0rgRmKmxnBoUfHPKeFZ4HnfUgb8cMiKaLiOG+407QZpYuLMfXFn7I0b0sIjEQSksiYhDB6Dse2ULkOYwmp3OlygAHlhIJgAAeU5DABEAQJAD4nHB+g8oMg5gwjsjPGc5j4-LcIqCiYyguyCQMyJoLIFmKw+YDeLQrKDJDC+Y4cPKGgABYAUUoQAAe3WAaqYbSYDH4CEE+QA7sUmABrfIU3UQHroEA4CniKkC2iohjwcWYFlqV7e+iMFgQUX+rTAyLS9CyjhAA)

### 💻 Code

```ts
type Schedule =
  | {
      scheduled: true;
      scheduleTime: number;
    }
  | {
      scheduled: false;
      scheduleTime: null;
    };

type Item = {
  id: number;
  name: string;
} & Schedule;

// id is auto-generated
// 
// From inspection, CreateItemData is equivalent to
// type CreateItemData = {
//   name: string;
//   scheduled: boolean;
//   scheduleTime: number | null;
// }
type CreateItemData = Omit<Item, "id">;

const data: CreateItemData = {
  name: "item name",
  scheduled: true,
  scheduleTime: null,
};


// @ts-expect-error: This works correctly
const scheduleData: Schedule = {
  scheduled: true,
  scheduleTime: null,
};
```

### 🙁 Actual behavior

The line `const data: CreateItemData = ...` typechecks, as `CreateItemData` throws away some important data about `Schedule` type.

### 🙂 Expected behavior

The line `const data: CreateItemData = ...` should not typecheck, `CreateItemData` should be equal to
```ts
type CreateItemData =
  | {
      name: string;
      scheduled: true;
      scheduleTime: number;
    }
  | {
      name: string;
      scheduled: false;
      scheduleTime: null;
    };
```

**Comment by fatcerberus** [comment]
`Omit` does not distribute over unions.  See https://github.com/microsoft/TypeScript/issues/49659#issuecomment-1164773544

**Comment by ducminh-phan** [comment]
Thanks for pointing me to #49659. @RyanCavanaugh Should we bring `DistributedOmit` into TS's core utility types?

**Comment by MartinJohns** [comment]
> Should we bring `DistributedOmit` into TS's core utility types?

See https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388:

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.

Also https://github.com/microsoft/TypeScript/issues/49656#issuecomment-1164655820:

> One of the reasons we don't like adding type aliases to the built-in lib -- we can't "upgrade" them!
