### ISSUE TITLE
Type-level function's lost return type

### ISSUE THREAD

**Issue by IhostVlad** [microsoft/TypeScript#49690]
# Bug Report

### 🕗 Version
4.7.4

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?strictPropertyInitialization=false#code/CYUwxgNghgTiAEkoGdnwCoE8AOIAyIAbiBALJTYASJuMAPAGLwgAeALiAHbBp3oB8ACgCU8ALz94UTpgA0GSQG8AUPHigkceNhgBLQlA7wAZpwBc8BgG5V68NC079hhHGQWASiDYBXGJyxcOjYcEAB7Y3g2AAtdZAA6Uz5+fhsAX2VlENwMUIJiMgpGZnYuHnhkkXFJaTkMEo5uNFqAbQBdSTF4W3QGsrR2+AB+eEGLQVs1XtZG8pbdTmMQGHhKeXiNhaWV9DbJtWHRwPwiEnIqGmXGeUp+FoAiN3u29Y3j-LOihnkBPYODiycU4wWzCTLZBDHdBhACq2FoAGEUAgupVRBJ6jN+vBkGw9JwAOaHOG0MDI5LwCzocGheAASU42B8bGOaC6DwAggAjMD3eScHwQCDye4I0B8+ACoV7LK0gDyzKZLNCbNyuA+hWwfFC0JJyyRyBA8gZStZ-EyFsyQA)

### 💻 Code
```ts
declare class TypeLevelMapHelper<F extends <T>() => any, T> {
  declare private fn: F;
  declare private res: ReturnType<typeof this.fn<T>>;
}

type TypeLevelMap<F extends <T>() => any, T extends any[]> = 
  T extends [] ? [] : (
    T extends [infer H, ...infer T]
      ? [TypeLevelMapHelper<F, H>["res"], ...TypeLevelMap<F, T>]
      : never
  )

type TypeToUpperCase = <T>() => T extends string ? Uppercase<T> : T

type InputTypes = ["Abc", null, "Cde", null]

type OutputTypes = TypeLevelMap<TypeToUpperCase, InputTypes>

```

### 🙁 Actual behavior

`OutputTypes` is equal to `[any, any, any, any]`

### 🙂 Expected behavior

`OutputTypes` should be equal to `["ABC", null, "CDE", null]`

Typescript's recent version introduce functionality for deducing template function return type via `ReturnType<typeof FUNCTION<TEMPLATE_ARGUMENT_VALUE>>` syntax

For some reason this functionality does not work in example above, however type `F` in `TypeLevelMapHelper` deduced correctly without `any` return type

**Comment by mkantor** [comment]
[Here's a simpler demonstration of the core reason that this doesn't work](https://www.typescriptlang.org/play?ts=4.7.4#code/CYUwxgNghgTiAEkoGdnwKIA8oFsAOEIAPAGLwiYAuIAdsGkQCoB8AFAHSewDmyAXPBogAbiBgBtALoBKeAF5m8AK40A1jQD2AdxoAaeC3gBvAFDx4oJHHh4YAS2FRq8AGY0BJANxmL4aNdsHJwQ4ZCUISgFKAE88EA0XeEoACztkdjcmZhMAXxMTGLj4AElQGko7GJIaeXgs1kwBRlkFAwLYhGLKAHUNcOAAIRAAOTswEGKXRlTkbpRhpRwAIzFGDQXlsVqsXAJiUtoKqr1BRZWYZnEAclDwyivJEwB6J-N4AD0AfhMgA), in case it helps:

```ts
declare class Example<F extends <T>(...args: never[]) => unknown, T> {
  declare private fn: F;
  declare private result: typeof this.fn<T>
}

type IdentityFn = <T>(x: T) => T
type ItWouldBeNiceIfThisWasNumberToNumber = Example<IdentityFn, number>['result']
//   ^? - type ItWouldBeNiceIfThisWasNumberToNumber = (...args: never[]) => unknown
```

**Comment by RyanCavanaugh** [comment]
I don't think our inference system is capable of computing this result - during the relevant inference process, we're dealing with a partial instantiation of `TypeLevelMapHelper` with marker types. Higher-order generics is not really supported at all.

If it turns out I'm wrong and there's a simple PR to fix this, please do 😅
