### ISSUE TITLE
Intersection types with arrays and array methods cannot find all fields

### ISSUE THREAD

**Issue by Balastrong** [microsoft/TypeScript#49699]
# Bug Report

Intersection of arrays cannot find all fields when using array methods, while the fields are working fine if a single element is directly accessed from the array.

### 🔎 Search Terms

type, intersection, array methods

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about intersection

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=10&ssc=1&pln=1&pc=1#code/G4QwTgBA9gRgVgLggbwFAQgMylA-EgZwBcwBLAOwHMBuVAXwG0BdCAMhXQhnHy5wBsApiHK1GLALwQGybFCQAiEAoA0XcEhIBXQXSa1UsOADpsYAKIgAxgAsAFHYCOASggSAfBEfHuYZ9QgAekD1SAATKEECCHIoIghBAA9SYkN4YwBbEAAHBxc3T29fV2DQiAiomLiE5NSjBgAGJh9wANKAeQBpVCA)

### 💻 Code

```ts
var obj: {
  foo?: string;
}[] & {
  bar?: boolean;
}[] = [{foo: "a", bar: true}];

obj.forEach((q) => q.bar); // bar does not exist
obj.map((q) => q.bar) // bar does not exist
obj[0].bar; // OK
```

### 🙁 Actual behavior

When using array methods (forEach, map, filter etc) only the first type is recognized in unions - field from the second type are not recognized.

### 🙂 Expected behavior

All fields are considered valid in an intersection of arrays.

**Comment by Balastrong** [comment]
I kept investigating and I found #11961 from 2016. I assume it is still valid, right?

**Comment by RyanCavanaugh** [comment]
Correct
