### ISSUE TITLE
Rename `NonNullable` to `NonNullish` or add an alias to preserve compatibility

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#49698]
# Suggestion
`null` or `undefined` is widely referred to as "nullish"

https://developer.mozilla.org/en-US/docs/Glossary/Nullish
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment

Developers can easily confuse `NonNullable` as just meaning `NonNull`.

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [~] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by AlCalzone** [comment]
**nullish** includes `false`, `""`, `0`, and likely something else I just forgot, so that would be wrong.

**Comment by RyanCavanaugh** [comment]
This name has been present for a very long time and honestly can't ever recall seeing someone be confused by it. Introducing a second name could only make the situation worse, since if `NonNullish` exists then `NonNullable` would be expected to retain `undefined`.

**Comment by ritschwumm** [comment]
just for the record: i _was_ confused when i first encountered it

**Comment by xprommer** [comment]
It makes sense to make `NonNullish` as an alias of `NonNullable` and mark the latter deprecated.
