### ISSUE TITLE
Add Missing Function Declaration: Does Not Correctly Declare Generic Function

### ISSUE THREAD

**Issue by Jutanium** [microsoft/TypeScript#49693]
# Bug Report

The "Quick Feature" allows us to generate a missing a function, but doesn't correctly declare that function when its parameters include a type parameter.

See also [unexpected behavior when type narrowing in this example](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKAZzQBtgAuRfASkQG8AoRNxAek7rkQCc0AB35wUICGkRQAFlIBGIAOYAaRAEUQMCAGtEAMRgAPRIUQBBFCkQBbGKVIwwSxKEiwEidBAoBDfr4eYBwwwIjEOEJocGHkVIgAvEmIAERgIDbyaPwpjKyIBYX84ACiAG4wFADKqGglwMBo0GSUwPQA3BwAviwcglAg-EhxwJ09LNyu4NDwSMVg5ZU16PWN0OEjtPiIAGSI6ZnZeRM8BbKiAO77aFcl-KL8xCn600H7cFDINkIUaDYYUDQKAAdLlOpMekA).

### 🔎 Search Terms

- add missing function declaration
- generic type parameter

### 🕗 Version & Regression Information

I am unable to find a version of TypeScript where this was not a problem. 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKAZzQBtgAuRfASkQG8AoRNxAek7rkQCc0AB35wUICGkRQAFlIBGIAOYAaRAEUQMCAGtEAMRgAPRIUQBBFCkQBbGKVIwwSxKEiwEidBAoBDfr4eYBz84ACiAG4wFADKqGhhwMBo0GSUwPQsIWhQIPxI5FQA3CwAvlks3K7g0PBIoWCR0XHoicmphTR0jKxVsqIA7ohgaENh-KL8xABE+jVBw3BQyDZCFGg2GFBoKAB00-QlVeVAA)

### 💻 Code

```ts
function identity<T>(self: T) {
 
  // To reproduce the bug, Quick Fix > Add missing function declaration
  runEvilSideEffect(self)

  return self;
}
```

### 🙁 Actual behavior

TypeScript generated this function, which is an invalid function declaration:

```ts
function runEvilSideEffect(self: T) {
    throw new Error("Function not implemented.");
}
```

### 🙂 Expected behavior

```ts
function runEvilSideEffect<T> (self: T) {
    throw new Error("Function not implemented.");
}
```

**Comment by fatcerberus** [comment]
No doubt the current behavior is bad, but the question is which "correct" behavior is more useful: making the generated function generic as suggested here, or to just use the constraint of `T`?

**Comment by RyanCavanaugh** [comment]
> making the generated function generic as suggested here, or to just use the constraint of T?

🤷‍♂️
