### ISSUE TITLE
...arguments parameter name mistaken for arguments

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#4969]
```typescript

export module bar {
	function foo(): {
	    (...arguments: any[]): any; // <-- problem
	} {
	    return undefined;
	}
}

```
![image](https://cloud.githubusercontent.com/assets/937933/10106139/e5517182-6380-11e5-8517-e1bd3446aafc.png)

see at [playground](http://www.typescriptlang.org/playground#src=export%20module%20bar%20%7B%0D%0A%09function%20foo()%3A%20%7B%0D%0A%09%20%20%20%20(...arguments%3A%20any%5B%5D)%3A%20any%3B%0D%0A%09%7D%20%7B%0D%0A%09%20%20%20%20return%20undefined%3B%0D%0A%09%7D%0D%0A%7D)

**Comment by vladima** [comment]
this is by design: 
- presence of `export` makes the whole file external module which are parsed in strict mode in ES6
- per [Annex C](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-strict-mode-of-ecmascript) of ES6 spec: 

  > It is a SyntaxError if the IdentifierName eval or the IdentifierName arguments occurs as a BindingIdentifier within strict mode code
