### ISSUE TITLE
"Spread argument must either have a tuple type" err even when spread arg has a tuple type

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#49700]
# Bug Report

### 🔎 Search Terms

tuple type union 2556 

### 🕗 Version & Regression Information
- This changed between versions 4.2.3 and 4.3.5.
- Playground versions 3 through 4.2.3 reported "Expected 1-2 arguments, but got 0 or more." That looks more like #43429.
- 3.3.3 additionally reported a lack of `readonly`.

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJgUwLbmgJwIZQTAvDAMwFcxgoBLcAHgCEYEAPbMOCGAIxBABsEMwAfAAoAUDHEwiEBAGUoacmADmANQRoIlMAC4YNADRiJABwyYkEACpFjvGLrqNmrGPKI4A-DDR844bgCeMADa6IpKALr23r7+QcFgREjs6vowicnqESIAlDAA3kbiAPTFAKJoaCAaMOD0GMAAFoQkZFowwBjc3NpFMKUAgjAQxj4YcDBmSkkIYLBIUrAI5FCN6jCNGABuOBiuNnZQAcY41Rw4phDSE1AgkzHQMKbmCNhoAHSuEEIATACsfwAbDk+qVLGt6JUzn4EBAwAByeYYADWOGkkBwKU6UguZgwFmsthw5DYeygBwQ71BxQAciBsK5NrAAAarEnMmAAdxWjUUjJwnW6CAmxFIFDqEEaICI3AmYHp51qO0q5DgiDAVIk-WK4JworadUQBEUKy0pJ8MD5-HoTHUYC6MG45HYmDQATSfnSCqgKN2D1gz3xr1SkxYHX48tgKRgKDg5GNws1EnjQhxcgUyjUGi0eUKWq1PnJaDAw3k4QAYq1xWAhO864GCRScgBuPoAX3o3GkBT6BdeRGL6SSKQ0lbFWlr9bxjaJLfb1PBJMtbEUzmFk1JMZNSAdjHxRMIVSQ9xQFC2WHC4e73NWMeqF3pswoDv11Yg1P4Ez2KAtoCQRIYYYEF4A0S1GEBgFhNgCDOTleSaWowGJNhBV4OA0nYIhYFWLBwwRWAlFeS05juDBqU5apkUvaAsBwG8pSw4ZyCUMB43ITo5hacdwC6FYgh8OAiFAyQwF4K5GSXTR-14NAbX3OwOMmLs7gotBkSpNsRFASBYAyEcIDHYT8FfCduBATldD0kNeSURpLOHdRc36AAqOt3mc4oYE07THjCZRDOrPAuNAoQkACdNwl0PylCc4pXLrDyvKAA)

### 💻 Code
```ts
const demonstrate = function<B extends boolean>(
    useStringVersion: B,
    paramsTuple : B extends true ? readonly [string] : readonly [number, number]
) {
    //Errors on each function call:
    //A spread argument must either have a tuple type or be passed to a rest parameter. ts(2556)
    //The error doesn't make sense because paramsTuple is a tuple.
    //Note that `this` within the called function should not be overridden.
    //The function definitions are in an external library, do not take a rest parameter, and cannot be modified.
    if(useStringVersion) {
        return stringFunction(...paramsTuple);
    } else {
        return numbersFunction(...paramsTuple);
    }
    //This is intended as a minimal example from a motivating case with more potential functions
    //and a more complex selection process for which one is called, but that can't get into a
    //working state without significant functionality reduction unless this simpler example can also work.
    //Writing function overrides also introduces undesired maintainability-reducing repetition 
    //& brittleness which would require active maintenance when the external library is updated, 
    //instead of the benefits of passing on a call directly.
}
const numbersFunction = function(low: number, high: number) { /*...*/ }
const stringFunction = function(myString: string) { /*...*/ }
```

### 🙁 Actual behavior
Each of the return lines throw an error:
>A spread argument must either have a tuple type or be passed to a rest parameter. ts(2556)

The error doesn't make sense because paramsTuple is a tuple.

Though it is the same error code reported in #43787, I don’t think it’s a duplicate of that because in this case, for any given call to the `demonstrate` function, the `paramsTuple` is one kind of tuple.  It seems like this should work. 

The same issue is observed when using the `Parameters` approach to generating the tuple types (playground link [here](https://www.typescriptlang.org/play#code/MYewdgzgLgBAJgUwLbmgJwIZQTAvDAMwFcxgoBLcAHgCEYEAPbMOCGAIxBABsEMwAfAAoAUDHEwiEBAGUoacmADmANQRoIlMAC4YNADRiJABwyYkEACpFjvGLrqNmrGPKI4A-DAAKZjEgRsDSooAE9jBBACGHRFJQAxEjItAXsfPwCgiBDwyOiwIiR2dQhE0gpwAREAShgAbyNxAHomgFE0NBANGHB6DGAAC0IkirAYYAxubm1GmBaAQRjjND44GDMlQoQwWCQpWARyKAH1GAGMADccDFcbOzCInrQOHFMIaTWoEHWYFegYUzmQLqAB0rggQgATABWaEANmqsxalhO9A6XXgIAQEDAAHJdhgANY4aSQHDFCZSV4ZKx3HDkNg3KB0kFIpoAORA2Fc51gAANjgy+TAAO5HAaKHk4CZTBBrYjlLQxAYgIjcNZgLkvHpXDrkOCIMCsiRzJoonAK5K9RAERRHLSMlYwSX8ehMdRgSYwbjkdiYNChfSYmCa2BQInXX7Y2CA-zAtBB-hrCZgUPalBwci2uXGiRZoRUuQKZRqDRaWoNE0mlbMtBjWLKMpWsBCEFt2MWay2BDVADcswAvvRuNJ6rNq4EiHWQ4Vihom6NW+2aV3eH3B2yUQznWxFM45etGTAkHakF7GP5u4ROkgfigKBcsHFxhhR2Ljseuq8udsKF7LaMEBskmd5fuMIBIN2DAxAgvDNgCnTANibAEBiIoSoMPRgPSbAyrwcBBuwRBhryL54rASiBM6OzfBgbIil0hLPtAWA4O+KrETE5BKGAWbkCmsAAVokxHKEUZwEQ8EkLw7w8tumiQbwzwXop0qupMEDfAxaCErmzRNAA6goFDKMMiq9CAuoKIgjIjt8e6dBJSFsCQNnkCsaxnnuGCKBg7DkD6YQALQeZJz4rBEFCjDAbIAGQcMZUC8NhsnofxQwMWqawrAAjkQ7nXMkVzHj5OzbPwSGiicYzHDgTgel6Pp+mYYnbjYcCsQRMUmi0ijQKsPTRLVLzYbaUBsFEAKvpopm9DceHwAVZDcKErIDiIoCQLABRFCUC5KvgQngEI3AgCKug7XOQYSkoAwXbO6gVnMABUbYgs9TQwOtm3-A2CQjAdZnNkISChEWcS6H9T1NK9bYfV9QA)).

### 🙂 Expected behavior

No errors and no need to rewrite valid JavaScript beyond adding type annotations; Typescript can validate proper typing.

The motivating use case here is part of a generic caching queue for calling functions from an externally defined set across a noisy &  narrow network pipe. Each function in the set might require a different tuple of parameters, but the types are well defined and the right tuple type corresponding to which function is being called is always paired with the function identifier.  Without type annotations, the code works just fine as JavaScript.

**Comment by RyanCavanaugh** [comment]
A conditional type isn't a tuple type; the error means what it says and means it correctly.

This is a correct error; you could legally call
```ts
demonstrate<boolean>(true, [1, 2]);
```

**Comment by wbt** [comment]
When both sides of the conditional are tuple types, it seems like the conditional should itself be at least considered a tuple type.

**Comment by wbt** [comment]
Thanks for your patient explanation @callionica!

However I think there might be some over-focus on an artifact of the simplification to the example above, and my most recent comment is about an even more basic point: Regardless of what B is, `paramsTuple` **should still be a Tuple type**, and the error message saying it's not a Tuple type doesn't make sense. 

For example, consider [this variant of the same code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJgUwLbmgJwIZQTAvDAMwFcxgoBLcAHgCEYEAPbMOCGAIxBABsEMwAfAAoAUDHEwiEBAEFuABwAWGAGoI0ESmABcMGgBoxEiPITByBcsADKUNOTABzGLrqNmrGHaI4A-DAByDAVlAJdA9kwANxAAkQBKGABvI3EAejSAUTQ0EA0YcHoMYEVCEjItGGBg7m1UmAyZGBM0PjgYDDRHIiQEMFgkKVgEcihFdRhlKJwMLyJ5Xi8AT1MCtA4ceQwIaXaoEA6YVugYLcxe7DQAOi8IIQAmAFZHgDZ4+oyAFXH6HLz4EAICBgAIDDAAaxw0kgOHYZgwUk2nQwSAgn3mi3IbFmUAxCCuHzSADkQNgvMpYAADMZYykwADuo0UDnJOGq3F47WIpAohQgihARG47TApI2BWmOXIcEQYAJEgaaW+OG5FUKiEsYFGWmxrRgLP49CY6jAwRg3HIkU6S30AJgotgUAhMyOQNgZxRCEutv47WqYAd4pQcAs5AQcHlEgsQkRciUqnUmnAiRSCoVrVxaDAzTsDkcADFyrywHHlEITGZQzZc054gBueoAX3o3GkyXq6a9RCzOfsTkLPK0NGiIHLpnMlmrfcc9abhO+WP1bAcHnDHWxMCQDnISDNjBRCxVuSQhxQFCiWDzVW2OEZY03eU2pL6FDNquLEEJvtPj6qICQh4MM0CC8Gq2byLkwBAmwBD-PSzIlAUYA4Iu7Kcra7BEI6FLXiCsCOF6+r9AcGCEvSeTgle0BYLeTKCrAmiOFqk78LA75aMEoxLK6cBEGBkhgLwOzkoumgAbw6z7uJbKGsEEAHORaDggSjYiKAkCwGAPRwhoA78fg7HgEI3AgPSuhaUgOm2syjiKOZ2nqCmDQAFRXG5zlpDAqnqSc6B5npxalrMBlFloQhIEstjTrofm1skLluVcHleWpqAMTWBaheAw4YDEeBlIORkRVFeYxRlTlpK57meY2QA). The second parameter is of type `B extends true ? 'alpha' : 'bravo'` but because both `'alpha'` and `'bravo'` (i.e. both sides of the conditional) are `string` the parameter value can be used anywhere that requires a `string` type.   The expected behavior is the same: when `paramsTuple` is going to be a `tuple` no matter what, TypeScript saying it's not a tuple creates frustrating confusion.

**Comment by callionica** [comment]
I agree that the error message is confusing and could be improved with a better message even if the behaviour stays the same.

It would also be desirable to be able to spread a union of tuples.

```
type T = [number, number] | [string, string];

function takesNumbers(n1: number, n2: number) {
}

const t : T = Math.random() > 0.5 ? [1,2] : ["a", "b"];

// ACTUAL: Produces an error saying "spread argument must .. have a tuple type .."
// DESIRED: This should produce an error, but not because spread is invalid on this type
// It should fail because takesNumbers cannot take arguments of string, string
takesNumbers(...t); 

function takesEither(n1: string, n2: string) : void
function takesEither(n1: number, n2: number) : void
function takesEither(n1: number | string, n2: number | string) : void {
}

// ACTUAL: Produces an error saying "spread argument must .. have a tuple type .."
// DESIRED: This should not produce an error because takesEither can handle any result of spreading the tuple
takesEither(...t);
```

[Playground](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAKlC8UDaA7ArgWwEYQE4Bop1s8BdKAH2QGdhcBLFAc0NoedIG4AobgMzQoAxsHoB7FFGABDANYRqAOUw5c1ABQoAjAC4iKvIRQAmPcVUBKKAG9uAX15CJtKVD1xEAWWnAAFgDpcaRQAEzEMdSsAPigABn8AVigAfmQtfGNyPSQAImkcwhysHK5eAHoyqABBAGEYAFUqgBk9AAVcMRC0IQUoYKg8DtwoamkQRiYoHOowXAhpEL7cJkwIFGAoDDQXf38oX2kAN2hpKTQwABtoUEgoXZzuCqgAEQBRAGUASQAlV+f3Xz0agjXxiNAXRazTrdE6SQZiAhQLBoDYoMQbHBCaTbaAzOYLKBAwkoQ7SC70RYSKSA4E3CCPSqfDbUUHgxZ8aT0C5IiBYnFSOQKZQkNRQLEoNEbGTyJYrDBrYDAsR8EZ0CasNXMbjSoUGNTqXb+YAWThQXgCYSiKk66iveh+PCaXSq9gsIimF0TKx6Q5iCn8QQicSSG12h24J1mPVGD3mPDeqC+-0WoPWwW2+2+R3aKMiyie5gx3OqfNsL1uRN+xa2BwM6p1RotKDtaE9YH9eHDUbjZhTPHzRbSZardabbYbXb7I4nM6Xa7gaD3OtvL6-f6wGkgsEQojoqBQro9Ppw3BDHl86jXdNhrPDcVT0JXY8gKBzajgjbKkazAcTanXc4rm1a9M0dQ1jU4IA)

**Comment by fatcerberus** [comment]
Regardless of the suitability of the error *message*, the *error* is correct.  When `B = boolean`, then `typeof paramsTuple = [string] | [number, number]`, meaning it's unsound to use `...paramsTuple` in either call (making this typesafe would require [`extends oneof` constraints](https://github.com/microsoft/TypeScript/issues/27808)).  It also means `B` can be a union, and a union of tuple types is not *itself* a tuple type (in the same sense that `"foo"` is a unit type while `"foo" | "bar"` is not; admittedly this is squabbling over semantics though)

**Comment by callionica** [comment]
I think the point that OP was making is that spreading a union of tuples can and should be supported, which in the original code would produce different errors and in other code would eliminate errors. I produced a new repro that hopefully eliminates some distractions from the original.

**Comment by RyanCavanaugh** [comment]
Repeated overload resolution using every possible constituent of a union is going to be combinatorially explosive in many real-world situations. This isn't something we could plausibly do.

**Comment by wbt** [comment]
TS resolves `B extends true ? 'alpha' : 'bravo'` as being validly assignable to `string` - why is it that different and more feasible than resolving a conditional on Tuple types as being a Tuple?

**Comment by RyanCavanaugh** [comment]
Because the very next thing that happens after we determine that it's a tuple type is to *look inside the tuple* and apply its contents to the function overload algorithm.

**Comment by fatcerberus** [comment]
> Because the very next thing that happens after we determine that it's a tuple type is to look inside the tuple and apply its contents to the function overload algorithm.

Ah ha! So my comparison to unit types was appropriate after all (i.e. that a union of unit types is not itself a unit type, and this is the same capacity in which TS cares about something “being a tuple type” here)

**Comment by callionica** [comment]
It is surprising to me that the reason for not making a fix in this area is a complexity concern (about overloads specifically?) given that TS appears to already handle type checking for union-of-tuple types for variable assignment and for calling single argument functions. In both those cases TS produces pretty reasonable error messages when the types don't match. It feels like there is a fairly straightforward mapping between a function that takes separate arguments and a function that takes a single tuple argument (and overload sets is just an extension of this mapping to a single union-of-tuples argument), so it's not obvious to me why the line is drawn here. If overloads is the step too far, would it not be preferable to detect the overloads (at presumably minimal cost) and only fail those cases? But still, the mapping between overload sets, functions with multiple arguments, and a function with a single union-of-tuples argument (which TS handles) is so strong in my mind, that I must be missing something.

**Comment by callionica** [comment]
Here's another repro showing the strangeness of the spread failure (no overloads involved). We can get type checking if we use `apply`, but we just get a failure if we use `...`. It's a strange inconsistency.

```
// A function that takes two arguments:
function fn(a: string | number, b: string | number) {
    console.log(a, b);
}

// A union-of-2-tuples type
type T = [string, string] | [number, number];

// A union-of-tuples variable
let t : T = Math.random() > 0.5 ? ["A", "B"] : [1, 1];

// Can we call the fn member-wise with a union-of-tuples? Yes.
fn(t[0], t[1]);

// Can we call the function through apply with a union-of-tuples? Yes.
fn.apply(null, t);

// Note that in both cases above type checking is happening! 

// Can we spread the variable? NO!
fn(...t); // ERROR: A spread argument must either have a tuple type or be passed to a rest parameter.
```

[Playground](https://www.typescriptlang.org/play?#code/PTAEEFQMwVwOwMYBcCWB7OokAsCGStcBrAUwGcsB3NUXAJwHMYBbEuJMgLgChZFUM0OAApcnUGSR0UcBqAA+oOCwBGJOgBpQK8ZOmyFS1eoCUoAN7dQ10Agxk0AGxIA6R2gaitKkwG5uAL7c3CAQoPDocAC0aFBRAExRSDAADs4USACeKSTcWTmgACqgALygANp6MgxaVbIAuoblysxqmkat6vX+IWCQERgxcclp5KAAbvQouCrO3M4EBOLFZQCy+NgudLhwACZozMJmAHygAAwuAKygAPwVAETg91r3AEL3jeLlAIxa393BUIAYR2oEoJFsuEcjiw2AhUEwrE6dCilBQZAhaJwtHCcEiQySqXSdwAmuQXLwREhymd6lpqf8-ICwCDMODIdDYfD4MhIrC6GgYAxsLQUmlMmCUNjcLj8bFCaMyKTyZSXLgxY5MsJlND6UzeqAAHJoJAQnD4UAybQmkUIXAYigzNDjM3ZCEIOEIIjVS0UPBitjVACEoGZoFZYIhZBSdBIuF2XImUxmzjuhoA8kHKcIXLmkH5QKEAKIAJRL6ZL4kg0dj8dojBYbAIzBgklAJClcLooDwLpxI2cWDdoDQ3bUoBS9oxCaQNBlsbbk+2rFNdApQA)

**Comment by wbt** [comment]
I don't think the tag or closure is really appropriate here.

**Comment by callionica** [comment]
I'm still confused by the complexity argument, partly because "_the only correct thing to do is to multiply all out all the possible tuple values into an argument list_" doesn't seem correct to me, whereas I agree with "_Pretty much every operation needs to be done in terms of the category of inputs, not through combinatorial explosion of every possible inhabitant of the category. Otherwise typechecking never finishes._" But surely we must be talking at cross-purposes.

**Comment by imdavidmin** [comment]
How should this scenario be handled presently then? I don't think writing all overloads out by hand would be a clever way?

**Comment by wbt** [comment]
The error message can and should be improved, especially because other conditionals with the same type on each branch are usable as that type.  

I also don't agree with the argument that "because the worst case is slow, it's definitely better to not handle more common reasonable cases and instead require hacky workarounds or disabling of type-checking altogether."

**Comment by mbrittsess** [comment]
I think this is the same bug, but I got hit by it for an even simpler case, and I'm very frustrated at how long it took to figure out why it was happening (especially since it happened inconsistently, as in several places TS was able to infer a more specific version of the type, so the error didn't occur).

```typescript
declare function setColor ( gray :number ) :void;
declare function setColor ( red :number, green :number, blue :number ) :void;

declare const SomeColor :[number]|[number,number,number];

// Error: "A spread argument must either have a tuple type or be passed to a rest parameter."
setColor( ...SomeColor );
```

To make matters even more unintuitive, while the solution is to perform a cast:
```typescript
setColor( ...(SomeColor as [number,number,number]) );
```

In my real-world example (which I will show a simplified version of), this is even more unintuitive because it sometimes works and sometimes doesn't, again based on some unexpected narrowing inferences. Like so:
```typescript
declare function setColor ( gray :number ) :void;
declare function setColor ( r :number, g :number, b :number ) :void;

// Later maintainers are intended to be able to change this value, I'd like them to get automatic errors immediately if they define the wrong number of elements
const SomeColor :[number]|[number,number,number] = [ 0.2 * 255 ]; 

function foo ( ) :void {
    // Error is resolved here
    setColor( ...(SomeColor as [number,number,number]) );
};

// But trying the same solution here gives error:
// "Conversion of type '[number]' to type '[number, number, number]' may be a mistake because..."
setColor( ...(SomeColor as [number,number,number]) );
```

If it's still decided that TypeScript isn't going to make this feature work, then at least some much more explanatory error messages would be greatly appreciated.

**Comment by zhuzeyu22** [comment]
Look at this
[Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

`
const target = {
  message1: "hello",
  message2: "everyone",
};

const handler3 = {
  get(target, prop, receiver) {
    if (prop === "message2") {
      return "world";
    }
    return Reflect.get(...arguments);
  },
};

const proxy3 = new Proxy(target, handler3);

console.log(proxy3.message1); // hello
console.log(proxy3.message2); // world
`

I got a error
`
11:26 - error TS2556: A spread argument must either have a tuple type or be passed to a rest parameter.

11       return Reflect.get(...arguments);`

**Comment by controversial** [comment]
In the following snippet:
```ts
const directionVec = ({ horizontal: [1, 0], vertical: [0, 1] } as const)[direction];
//    ^ readonly [1, 0] | readonly [0, 1]
gl.uniform2i(this.blurProgram.uniforms.direction, ...directionVec);
```
typechecking fails with “spread argument must either have a tuple type ...”

However, if I coerce `directionVce` to the (wider) `[number, number]`, typechecking passes:
```ts
const directionVec: readonly [number, number] = ({ horizontal: [1, 0], vertical: [0, 1] } as const)[direction];
//    ^ [number, number]
gl.uniform2i(this.blurProgram.uniforms.direction, ...directionVec);
```

It seems like TypeScript should be at *least* able to handle the case where a union has a homogenous tuple type?

**Comment by pencilcheck** [comment]
I want to ignore this error, as it doesn't make any sense.

If I convert to ".apply" format it told me that it prefer spread argument so it is a circular error....

**Comment by prewar9** [comment]
@wbt https://typescripter.space/questions/what-is-the-reason-behind-a-tuple-union-requiring-the-argument-never-in-the-includes-method

**Comment by jails** [comment]
Personnaly I'm using a type assertion like so `myFunction(...args as Parameters<typeof myFunction>` to get rid of the error.
