### ISSUE TITLE
Errors in curried function with overloads in JsDoc

### ISSUE THREAD

**Issue by timonson** [microsoft/TypeScript#49708]
The following function with overloads with JsDoc throws two errors. Written in pure TypeScript it passes the compiler. Is there a way to do this in JsDoc?
If there is no way, can I expect a fix in the future maybe or is it just technically *impossible* at the moment?
Thanks!

```js
/**
 * @type {{
 *   (init: "a"): () => string;
 *   (init: "b"): () => number;
 * }}
 */
export const foo = (init) => {
  return () => {
    switch (init) {
      case "a":
        return "abc";
      case "b":
        return 10;
      default:
        throw Error("Invalid body method.");
    }
  };
};

console.log(foo("a")());
```

>2322 [ERROR]: Type '(init: "a" | "b") => () => string' is not assignable to type '{ (init: "a"): () => string; (init: "b"): () => number; }'.
  Call signature return types '() => string' and '() => number' are incompatible.
    Type 'string' is not assignable to type 'number'.
export const handleResponse = (init) => {
             ~~~~~~~~~~~~~~

>TS2322 [ERROR]: Type '() => 10 | "abc"' is not assignable to type '() => string'.
  Type 'string | number' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
  return () => {

**Comment by MartinJohns** [comment]
- You forgot to fill out the issue template.
- This is a duplicate of #47669. Arrow functions currently do not support overloads.

**Comment by timonson** [comment]
@MartinJohns it already works in pure TypeScript like I said in OP. So I am not sure why your link matters to my issue. I am asking about JsDoc.

**Comment by MartinJohns** [comment]
> it already works in pure TypeScript like I said in OP

It does not: [Playground link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wGYQgLjgbwFgAoOOACgEtlKY8AiAQ3oEo9yW4BeAPjnSjUA5gG4SZKjTpx6AI1btOvOMgCuAW1nAoY4gF9uFarSV8ipOFGAxVUZBVMFxZfgHdaCABZGpncy5cERlRgGWYcZwCyKxs7MNkEel0oxGDQuXoIixSY23sARgAGZKiAE2AMRlUAGzpIqJhPKAhXOABRKGaocnoASWQAN0ZqylK4WQhSgE84dWtPSYA6VhKyPWc9XU2SEiA)

**Comment by timonson** [comment]
OK, I didn't want to make my question about arrow functions in the first place but about how I can solve, if at all, my problem, what consists of typing the function in JsDoc.

This seems to work in pure TyperScript:

```ts
function bar(init: "a"): () => string;
function bar(init: "b"): () => number;
function bar(init: any): any {
  return () => {
    switch (init) {
      case "a":
        return "abc";
      case "b":
        return 10;
      default:
        throw Error("Invalid body method.");
    }
  };
}
```

**Comment by timonson** [comment]
Thank you!
