### ISSUE TITLE
Compiler error occurs from `@link` tag of comment

### ISSUE THREAD

**Issue by samchon** [microsoft/TypeScript#49706]
# Bug Report
After updating TypeScript version from 4.6 to 4.7, TypeScript compiler has started inspecting `@link` tag in comments.

However, I couldn't find that spec from the Wiki documents.

Therefore, I report it as a bug.

### 🔎 Search Terms
  - comment
  - link
  - compile error

### 🕗 Version & Regression Information

- This is a crash from `@link` tag in comment
- This changed between versions 4.6 and 4.7
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about comment

### 💻 Code
![image](https://user-images.githubusercontent.com/13158709/176070070-0a2d1b9a-4f04-403b-afc6-e40e649bc1f5.png)

### 🙁 Actual behavior
![image](https://user-images.githubusercontent.com/13158709/176070124-a1ae2ab2-852b-47e2-b7fc-f7006493f401.png)

Sorry for non-english comments.

Anyway, if non-imported or mis-written feature exists in the `@link` tag, it becomes compiler error.

### 🙂 Expected behavior
Do not inpsect comment or a new option that can turning on or off that feature

**Comment by sandersn** [comment]
I tried [a simple program with a dangling reference](https://www.typescriptlang.org/play?&filetype=ts#code/PTAEAEBcGcFoGMAWBTeBrAUAMwK4Dt5IBLAez1CxJIAoBKUAb1AF8NgAqdx8AGyLzSgAYlVCIioSCgBOyZqHbBs+QqXIAjAIbS6jDBmZA) and couldn't reproduce the error on 4.7.4:

```ts
function foo() { }
/** {@link Foo hi there} */
function bar() {

}
```

- Can you give me more detail about your tsconfig? Maybe there's some combination of settings that causes this error to be reported. 
- Are the identifiers with errors supposed to be resolvable at the point you used them? Maybe this error only happens for imports that *are* actually resolving, or some other weird combination.
- Can you give the text of an example comment in Korean? It's possibly (but unlikely) that this error only happens with hangul (or other non-latin characters).

**Comment by samchon** [comment]
![image](https://user-images.githubusercontent.com/13158709/180386273-85c47b96-6171-4a78-98b4-23210ea0ed2b.png)

The phenomenon comes sometimes in IDE when using the Korean characters.

However, the error becomes resolved when import some of the `@link` tagged interface and the error does not be appeared again when erasing the import statement. However, it's very hard to realize the error because the error does not being occured in everytime.

I'll come back if I find a clear rule occuring the bug.

**Comment by samchon** [comment]
Succceded to reproduce and found how to make the bug cleary:

https://github.com/microsoft/TypeScript/issues/52918
