### ISSUE TITLE
Typescript type assertion for private Instance class variables

### ISSUE THREAD

**Issue by nichita-pasecinic** [microsoft/TypeScript#49709]
# Bug Report

Unable to type assert a private class variable instance 

### 🔎 Search Terms
`assertion`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwDYEMDOa4EE4G8CwAUHHGFAJYBuKMwcAtgJ5ZRQqMBccaMFAdgHMA2gF04AHzgBXPgBNgAM3J9gsgNxEiJMlRp0EEPjyhSEMaAAoAlHgC+m4qQrVacdGmCwAss1btrXO6eMJgwABbkmJFw4dEAZHhaJAy+bJzcvMoCSbaJjiTkCnAWAISxaAB0TCxpNuFQEADucCrNAKKslgDk1X6McNF8EPDySiqyXVYajvaESToudLIQAMoQ9MCxgtZ5yTERlUHeqf5TSSQGRvBIwHxwALz7kVUnjBU3guHTJLO2QA)
[Playground link 2](https://www.typescriptlang.org/play?#code/FAYwNghgzlAEBiB7RAhCAnAPAFVgUwA8AXPAOwBM4AKKI9AS1IHNYAfWUgVzDAEpYAvLBp1GLdlx68AfLADewWEtgAHTgCMw9EAmQBGAFyxaDZmw7cwgizwDci5SoYA3CCV2IATEZNjzkqyEA+2VVFzc8DwBmI1wgy3sHJSd6V3cAfQAzZAAWWB9RMwlLa2Ck1Q0tHSY8Ig8cql4C03EbKwVQ0PRaznRSWCIAC3ooADos3JDlAF9ylLTIqFr6qlcrZr9iqXly0KGR8ezEPKE1qaVZufD3AFFSKF68JEQ9RqNoJfQiOH24EY80OhYAAyeQeQzGQosaY7TrKX6jZ56awAIhR51gs1C8wisDuD26z08b1gHzwXx+wz+cGegJBYKJGzMMI6cIGVMRyE8qPUEAAXujyljHNdIvjHs8oiSyRT2f9-rSMJhfMxZKy4QjJTyMILQsLkqK8fcJblpTByd85dSARh6XJ6kzobC2Zrctr0LqZsBvdjDSRaK9+OrOgjxYT9I0MaEQIh7nV-XVHdZXS8MZdfalcQniUHdvCOWGnlzI3mlDG4wM8LR8pCWsmOUS0z6RZn3Ampbm2VbRoXJSWu+XqwmayqWEIU1Em1dW5EEw1Oy6C8bw8d+2zB-Gq4na35xw3JkLgNMgA)

### 💻 Code

```ts
export class A {
  private myArray: string[] | undefined;

  private constructor() {}

  private assertMyArray(): asserts this is this & {
    myArray: string[]
  } {
    if (!this.myArray) throw new Error('myArray is not defined');
  }

  private doSomething() {
    this.assertMyArray();
    const len = this.myArray.length; // <-- error here
  }
}
```

### 🙁 Actual behaviour

TS evaluates the type assertion `assertMyArray` as `never`
```
TS2339: Property 'myArray' does not exist on type 'never'.   
The intersection 'this & { myArray: string; }' was reduced to 'never' because property 'myArray' exists in multiple constituents and is private in some.
```
If changing from `private` to `public` signature everything will work as expected 

### 🙂 Expected behaviour

I think the expected behaviour should be exactly as on `public` variables, so it would evaluate correctly and not resolve the assertion to `never` (while keeping the right `this` type)

**Comment by nichita-pasecinic** [comment]
Note: If using `#` instead of `private` keyword it works as expected 

```ts
export class A {
  #myArray: string[] | undefined;

  assertMyArray(): asserts this is this & {
    myArray: string[]
  } {
    if (!this.#myArray) throw new Error('myArray is not defined');
  }

  doSomething() {
    this.assertMyArray();
    const len = this.myArray.length;
  }
}
```

`#myArray` is private as previously and after type assertion `this` isn't `never`

**Comment by nichita-pasecinic** [comment]
> > If using `#` instead of `private` keyword it works as expected
> 
> Because `#myArray` and `myArray` are two different properties.

Ok, ts' `myArray` private is compile time annotation and js' `#myArray` is runtime safe too, how does it help in the described issue ?

**Comment by MartinJohns** [comment]
The error you see is because the resulting type has the same property name with two different visibilities (`private` from `this`, and `public` from the type you intersect with). This issue does not occur with the `#` properties, because in that case you refer to two completely different properties (`#myArray` and `myArray` are not the same property).

I'm merely pointing this out. Your example in https://github.com/microsoft/TypeScript/issues/49709#issuecomment-1168278953 will lead to an JavaScript error, because your type assertion says a property `myArray` exists, which is not true. Attempting to access this property will lead to a `myArray is not defined` error.

**Comment by nichita-pasecinic** [comment]
Oh, I see, it was a typo, sorry for not observing it. But now there is something else

```ts
export class A {
  #myArray?: string[] | undefined;

  constructor() {}

  assertMyArray(): asserts this is this & {
    myArray: string[];
  } {
    console.log(this.#myArray);
    if (!this.#myArray) throw new Error('#myArray is not defined');
  }

  doSomething() {
    this.assertMyArray();  // if commented 
    const length = this.#myArray.length; // then this should error
    console.log('never');
  }
}

const instance = new A();
instance.doSomething();
```

If I will comment the assertion method call `this.assertMyArray();` then TypeScript should error about the `this.#myArray.length` because `#myArray` could be `undefined`, but apparently ts compiler doesn't

Here is a stackblitz playground - https://stackblitz.com/edit/typescript-ptoabi?file=index.ts

**Comment by MartinJohns** [comment]
> If I will comment the assertion method call `this.assertMyArray();` then TypeScript should error about the `this.#myArray.length` because `#myArray` could be `undefined`, but apparently ts compiler doesn't

In your stackblitz you have `strictNullChecks` disabled. In this case there is no `undefined` type. If you enable `strictNullChecks` you get an error warning about `undefined`.

**Comment by RyanCavanaugh** [comment]
Someone more clever might be able to figure this out, but AFAICT there is no way to do this because there's no way to refer to the name of a `private` field in a way that creates the same kind of name as exists in the originating declaration.

**Comment by tech-meppem** [comment]
I've encountered this problem too.
I have a playground link which might be useful, as it's got a bunch of different methods I tried to get this working, with no success:
[Playground Link](https://www.typescriptlang.org/play?#code/FAYwNghgzlAEBiB7RAhCAnAPAFVgUwA8AXPAOwBM4AKKI9AS1IHNYAfWUgVzDAEpYAvLBp1GLdlx68AfLADewWEtgAHTgCMw9EAmQBGAFyxaDZmw7cwgizwDci5SoYA3CCV2IATEZNjzkqyEA+2VVFzc8DwBmI1wgy3sHJSd6V3cAfQAzZAAWWB9RMwlLa2Ck1Q0tHSY8Ig8cql4C03EbKwVQ0PRaznRSWCIAC3ooADos3JDlAF9ylLTIqFr6qlcrZr9iqXly0KGR8ezEPKE1qaVZufD3AFFSKF68JEQ9RqNoJfQiOH24EY80OhYAAyeQeQzGQosaY7TrKX6jZ56awAIhR51gs1C8wisDuD26z08b1gHzwXx+wz+cGegJBYKJGzMMI6cIGVMRyE8qPUEAAXujyljHNdIvjHs8oiSyRT2f9-rSMJhfMxZKy4QjJTyMILQsLkqK8fcJblpTByd85dSARh6XJ6kzobC2Zrctr0LqZsBvdjDSRaK9+OrOgjxYT9I0MaEQIh7nV-XVHdZXS8MZdfalcQniUHdvCOWGnlzI3mlDG4wM8LR8pCWsmOUS0z6RZn3Ampbm2VbRoXJSWu+XqwmayqWEIU1Em1dW5EEw1Oy6C8bw8d+2zB-Gq4na35xw3JkLgNMgA)

**Comment by VolDr** [comment]
Any updates?
