### ISSUE TITLE
Upgrade TypeScript lockfile to v2 (upgrade to NPM v7 or higher)

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#49726]
# Suggestion

https://github.com/microsoft/TypeScript/blob/main/package-lock.json

This file should be upgraded to use NPM lock file V2 (needs NPM v7 or higher).

## 🔍 Search Terms

lock file

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ⭐ Suggestion

Upgrade to NPM v7

## 📃 Motivating Example

Since there is no way to disallow NPM v7 or higher to not update the lock file to v2, it is very annoying when working on the TypeScript repo.

```
TypeScript > npm install

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```

![image](https://user-images.githubusercontent.com/5390719/176380011-dae5bac7-88a1-4912-a3d2-e9a8360d61e0.png)

Every time you run `npm install`, this will happen.

Upgrading to npm v7/8 is a good way to solve this problem.

**Comment by RyanCavanaugh** [comment]
@jakebailey want to?

**Comment by jakebailey** [comment]
I'm OOF but before I forget, this will be more involved than just rerunning npm as newer versions of npm don't have some of the weird side effect-y behavior that old ones do, so we'll have to fix some pipelines like the auto upgrade one.

We can at least pin a version in the Volta config, but it's going to be a little annoying for those of us who are sticking on node 14 (which ships with npm 6) for one reason or another (for example, for frame restart, but that's not the only reason).

**Comment by jakebailey** [comment]
(but yes this is in my wheelhouse of fun build changes)

**Comment by Jack-Works** [comment]
Another solution (to me, since I'm using corepack), is to request corepack support shimming npm so https://github.com/microsoft/TypeScript/blob/f8aa570b23bd094798a98cef307038b1da9101a7/package.json#L31 will automatically provide the correct version of npm 6.
