### ISSUE TITLE
'type' can declare unreferencable type

### ISSUE THREAD

**Issue by strager** [microsoft/TypeScript#49724]
# Bug Report

A `type` alias declaration can be named `keyof`, even though such a declared type cannot be referenced. See code example.

### 🔎 Search Terms

"type keyof"  Type alias name cannot be 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (3.3.3 through 4.8.0 (beta)), and I reviewed the FAQ for entries about `keyof`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBA1hIHsBmUC8UDOwBOBLAdgOYDcAUADYTBQAeAXLPMmlAEQAWurxQA)

### 💻 Code

```ts
type keyof = string;
let x: keyof  = "hi";
//            ^ error: Type expected.
//          ^ error: Exported variable 'x' has or is using private name ''. (4025)
```

### 🙁 Actual behavior

Two compile-time errors:
* "Type expected. (1110)" (second line)
* "Exported variable 'x' has or is using private name ''. (4025)" (second line)

### 🙂 Expected behavior

Three compile-time errors:
* "Type alias name cannot be 'typeof'. (2457)" (first line)
* "Type expected. (1110)" (second line)
* "Exported variable 'x' has or is using private name ''. (4025)" (or maybe not this one...)

**Comment by Josh-Cena** [comment]
Actually, it is referencable, just only as a qualified name instead of an identifier (similar to how JS handles reserved names):

```ts
namespace Foo {
  export type keyof = number;
}

const a: Foo.keyof = 1;
```

**Comment by strager** [comment]
@Josh-Cena Good point.

Should the expected behavior be no errors?

**Comment by Josh-Cena** [comment]
I don't know—from a syntactical perspective there's nothing wrong with `type keyof = string`. And you can easily create qualified references with `import * as Foo from "somethingThatExportsThisType"`, so I'll say it's working as expected.

**Comment by vegerot** [comment]
> I would consider this to be on par with `let if = 42;` which is a syntax error despite that you can have other things with keyword names.

This is what I was thinking of as well
