### ISSUE TITLE
Create an object, the value of the enumeration is used as the key of the object, the object point value is a literal type, but typescript does not generate an exact type for the object

### ISSUE THREAD

**Issue by PlayGuitar-CoderQ** [microsoft/TypeScript#49722]
# Bug Report

### 🔎 Search Terms

typecript does not automatically generate the correct type、enum、Object  key in enum

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ___4.3.4___ and ___4.7.4____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ___enum______
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQRSAHgA5z4AuoSAdgK4C2oA8hYwIIUCWANQKY+cBqADeRUKADkcLgwCG-AEyzQAXjkLGKvuoA00nYv0BmAAwbt8s-yuzjMu3ocBGG6bd9zn4wC+JMHB5FS0sGKYdJw8-EL4ImIAopTUNABySiwo2lIyANqxDLyCwqIMAHS6yh4AugBc3rV8TiZFiqUJSVU1FpaNzfpthcVd5WLV9gaDspgA7kqoqARtAQDcQA)

### 💻 Code

```ts
export enum OpenApiVersion {
  'openapi2' = 'openapi2',
  'openapi30' = 'openapi30',
  'openapi31' = 'openapi31',
}

export const OpenApiVersionExportName = {
  [OpenApiVersion.openapi31]: 'openapi',
  [OpenApiVersion.openapi30]: 'openapi',
  [OpenApiVersion.openapi2]: 'swagger',
};
```

### 🙁 Actual behavior

Typescript Generated Types 👇

```ts
const OpenApiVersionExportName: {
    openapi31: string;
    openapi30: string;
    openapi2: string;
}
```

### 🙂 Expected behavior

This is my expectation 👇

```ts 
const OpenApiVersionExportName: {
    openapi31: 'openapi';
    openapi30: 'openapi';
    openapi2: 'swagger';
}
```

**Comment by RyanCavanaugh** [comment]
This didn't change between 4.3 and 4.7 as far as I can tell. The current behavior is the expected behavior; if you want the "expected" behavior use `as const` either on the strings themselves or the entire object
```ts
export const OpenApiVersionExportName = {
  [OpenApiVersion.openapi31]: 'openapi',
  [OpenApiVersion.openapi30]: 'openapi',
  [OpenApiVersion.openapi2]: 'swagger',
} as const
```

**Comment by PlayGuitar-CoderQ** [comment]
> 我这如果真的，你是在和 4.3.7 之间变化。当前行为是没有行为；“潜在”行为`as const`，在字符串本身就是对象上使用
> 
> ```ts
> export const OpenApiVersionExportName = {
>   [OpenApiVersion.openapi31]: 'openapi',
>   [OpenApiVersion.openapi30]: 'openapi',
>   [OpenApiVersion.openapi2]: 'swagger',
> } as const
> ```

oh ！！    I am very sorry for wasting your precious time, it is my negligence that caused. 😖
