### ISSUE TITLE
Symbol Indexer Don't Work Properly using `--build` (Build Mode)

### ISSUE THREAD

**Issue by manuth** [microsoft/TypeScript#49739]
# Bug Report

### 🔎 Search Terms
  - build
  - `--build`
  - `-b`
  - Symbol
  - not assignable to symbol
  - not assignable
  - property

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _symbols_
- I was unable to test this on versions prior to `4.4` because _the `symbol` type didn't exist back then_

### ⏯ Playground Link

_This issue can't be reproduced using the TypeScript Playground._

### 💻 Code

***tsconfig.json***
```json
{
    "compilerOptions": {
        "module": "CommonJS",
        "target": "ES2015"
    },
    "include": [
        "./index.ts"
    ]
}
```

***tsconfig.build.json***
```json
{
    "include": [],
    "references": [
        {
            "path": "."
        }
    ]
}
```

***index.ts***
```ts
class Test extends Array {
  [key: symbol]: string
}
```

Run the following commands:
```
npx tsc -b tsconfig.build.json
```

### 🙁 Actual behavior

Following errors are emitted:
```
node_modules/typescript/lib/lib.es2015.iterable.d.ts:60:5 - error TS2411: Property '[Symbol.iterator]' of type '() => IterableIterator<any>' is not assignable to 'symbol' index type 'string'.

60     [Symbol.iterator](): IterableIterator<T>;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:99:5 - error TS2411: Property '[Symbol.unscopables]' of type '() => { copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: boolean; values: boolean; }' is not assignable to 'symbol' index type 'string'.

 99     [Symbol.unscopables](): {
        ~~~~~~~~~~~~~~~~~~~~~~~~~
100         copyWithin: boolean;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
106         values: boolean;
    ~~~~~~~~~~~~~~~~~~~~~~~~
107     };
    ~~~~~~
```

However, `npx tsc -p .` works, so the TS code has to be correct.

### 🙂 Expected behavior

Just like `npx tsc -p .`, `npx tsc -b tsconfig.build.json` should run through successfully.

**Comment by sheetalkamat** [comment]
Investigating but overall, this looks like something to do with getting per file errors vs `program.getSemanticDiagnostics()`

**Comment by manuth** [comment]
Awesome! Thanks for the rapid fix 😄
