### ISSUE TITLE
Load declarations for dynamic imports

### ISSUE THREAD

**Issue by LabEG** [microsoft/TypeScript#49731]
# Suggestion

## ⭐ Suggestion

Now the typescript import declaration files only from node_modules.
I also suggest importing declaration files for dynamic imports.

## 📃 Motivating Example

In the current version of the typescript, the widget will have the type `any`.
After the implementation of this feature, the widget must have a type from declarations, check types, and help the developer write code.
```typescript
const widget = await import("https://some-site/widget-microfront.esnext.min.js");
widget.render(this.microfontElement, {app: {serverUrl: location.origin}});
```

## 💻 Use Cases

Development of distributed microfrontends.
This feature will allow you to make much larger distributed applications.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
This sounds like #24550.

**Comment by fatcerberus** [comment]
#24550 specifically mentions dynamic import from a domain in the OP, just like this issue.

**Comment by MartinJohns** [comment]
Then it sounds like #35749.
