### ISSUE TITLE
Allow to infer tuples from const objects

### ISSUE THREAD

**Issue by Fuzzyma** [microsoft/TypeScript#49734]
# Suggestion

## 🔍 Search Terms

const literals, infer tuples

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Const objects should allow to be converted to other const expressions (e.g. mapping or Object.keys)

## 📃 Motivating Example

If you have a const object, all keys and values of this object are readonly. The order is fixed as well.
Sometimes it becomes useful to convert the const object to their const tupel counterparts:

```ts
const a = { a: 1, b: 'foo' } as const

const b = Object.values(a) // should be of type ['1', 'foo']
const c = b[0] // typed as 1
```

This feature helps to narrow types as much as possible. The information is already there. It is just not utilized by typescript.

## 💻 Use Cases

Allows stricter typing and better checks for order of keys or values in objects

**Comment by RyanCavanaugh** [comment]
We don't have any way to do this; any two `{ readonly a: 1, readonly b: "foo" }` objects are interchangeable regardless of their property order.

**Comment by fatcerberus** [comment]
There's also this little issue:

```ts
let a = { a: 1, b: 'foo' } as const
const b = { a: 1, b: 'foo', c: 'what' } as const
a = b  // ok, extra properties are legal

const c = Object.values(a) // ['1', 'foo', 'what']
```

It can't be typed as `[ '1', 'foo' ]` because unlike object types, tuple types don't allow excess elements.  `as const` doesn't create a sealed type, it's just a hint to the type inference machinery not to widen things.

**Comment by k644606347** [comment]
> There's also this little issue:
> 
> ```ts
> let a = { a: 1, b: 'foo' } as const
> const b = { a: 1, b: 'foo', c: 'what' } as const
> a = b  // ok, extra properties are legal
> 
> const c = Object.values(a) // ['1', 'foo', 'what']
> ```
> 
> It can't be typed as `[ '1', 'foo' ]` because unlike object types, tuple types don't allow excess elements. `as const` doesn't create a sealed type, it's just a hint to the type inference machinery not to widen things.
> 
> Note also that `readonly` is a very weak guarantee - `{ readonly foo: string }` is assignable to `{ foo: string }` so the object could still be mutated despite the `as const`.
> 
> ```ts
> // all of this is well-typed in TS
> const a = { a: 1, b: 'foo' } as const
> const b: { a: number, b: string, c?: boolean } = a;
> b.a = 42;
> b.b = 'bar';
> b.c = true;
> 
> const c = Object.values(a) // [42, 'bar', true]
> ```

why readonly can mutate?

**Comment by RyanCavanaugh** [comment]
`readonly` isn't immutable. In most languages, for example, the length of an array is read-only, but it can still change -- different observations of it may produce different values.
