### ISSUE TITLE
TS generics fails to inherit type once .notation is used

### ISSUE THREAD

**Issue by vadimvar** [microsoft/TypeScript#49747]
# Bug Report

### 🕗 Version & Regression Information

This is always the case.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5#code/PQKhAIBUAsEsGdwBcCeAHApuB4Cu8MATZAe3AGMSA7eJAJwENYrwBBABQElsqkM6AZg3JYkZaAwBuWagBsUFBrNkMARrKyEMA5rCSxqiEMABQGAB5oSdJMnRYAYrirl91JQB4OnAHzgAvOAA3ibg4ADa7DzgANYYKCQCbFwAugBc4ADCSirqGE4ublQA3CYAvqUmoBAAoub0wkiIAs6uBjTg8LAA5lQMSLh0ovbgAnQkALZQ4MYmqJjgBW3UAMo9fQNDHpDgFnxUhIjZymoaS0V+gTt7GAeIABSh4AB0rwx03fAZzAL84OwmACUAT8khIsEITwA-P8nhkqBhpHRKtUoCMxBRDPRcK4eHw6LApiRVAArDC4pASWzMaD8PSIbyjVpFTrrfqDLCzeZYTJYug4pCQezbXb1W6HLI5U75ZntS7gR5hV7Pd6fDLndprXrsraQHxAkHBComKpgcAAWQUjK0OioenaM1M3ItKEZgRCYTCDDQsAy9zQAEYMrQCVRugAacBoABM8NwE1U-GB-lB4MhZRNqIAItpmBhEBMSFpZKRwEM0EMCLxktwJhhKUXHXMRuaixhZCKbndJSc8hrqPKPZ7KDRsa4MrzR-zXELMNt9Z7wDkSAB3KFxhP8cIpcqZs0revgRLgQvF5rWF01pvO1tnrxcUX7CX9vod7w+QdPMKRaJxBJJbx0gtNs3y4SIUn1DNTQgSAVzIEcQwFE962gItEBXPRoHAQhYAEX4hmrLptU2fMmwQ2xvVgSdENxQJ-SDTp6GYCMo1jcAqHjRM6GTPx7iCMpARMcilx9aixyQaMAgVQMNy4yMY1kpNDT4+B4wyQMAGoYwEvcIEyIZ+lI2921GcYpnI6dbDrBtiAYA5H3FRA9HADDKRczDWGUVcTyLXDYD+WZhNPdsHEaawFECTsxW7Y5cjOWUB3uCyBQnPkBVnDB5x44Iv0xUcfOLNJjI7PUpKCZLXGNRdhK7LRiECAB5UlySQFV4CIqh7mC2RwyHRcwlc6BPNkVc-WXFdFLobdstqohcsXATSkXIZNhYWbCFKKDUQAcRIRtyAYAhwAAWjLHpoFsCrqUQfAiFGC8AHJKIewKsRPFBiq+YC70td8ytyyiMm60LXHC+5KLEyzBK2s1dv2w6sFOygJh9DQ6GwkhSKoEgKK8lcXPGMM8po2xXvyiYPpA+A2M+jxfq4T9F0BgqQrCugUHB0S0tcaNod08AACEGGIA6jtO6gRAKvy-hwW7iEgFZwBGkgCEQZ0fjIOzbLx9DCe6YnxNLRM8AIYgydod7PoAZgyWn6d8f6mZ9IGQJBsR2c5qjuYkwFnkG4bV3ucIA3DaMUj5kwgA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

See playground link...
We want generics to guard model properties so the models correctly define callbacks after API method signature it is used for. At the same time we want to use . notation to modify model properties - aka `model(myRequest).withTransform(myTransform)` This is very valuable for readability and helps to reduce complexity a lot. However, once .notation is used TS looses type information and requires to provide type explicitly which is quite annoying taking that interfaces and its methods have long names - `model<MyVerySmartInterface["myVerySmartMethod"]>(mySmartRequest).withTransform(mySmartTransform)`
### 🙂 Expected behavior
`model(myRequest)` and `model(myRequesty).withTransorm(myTransform)` work the same and inherit the type from property they are used for.

**Comment by RyanCavanaugh** [comment]
The inference setup here is too complex and we end up measuring the wrong variance. You need a variance annotation here:
```ts
type ConstructType<out T extends CallableFunction> = (
  ...args: FunctionSignature<T>
) => {};
```

**Comment by vadimvar** [comment]
> You need a variance annotation here
out? This will not compile.
