### ISSUE TITLE
`composite` projects and `ts-expect-error`

### ISSUE THREAD

**Issue by vitch** [microsoft/TypeScript#49741]
# Bug Report

`composite` TypeScript projects with `allowJs: false` and using `@ts-expect-error` to allow importing a `.js` file behaves unexpectedly.

The set up for this is kinda complex and I've put together a stripped down repository demonstrating it:
https://github.com/vitch/ts-composite-error

In this setup we have three packages:

 *  `package-a` - imports a class from a `.js` file from `package-b` with `@ts-expect-error` and exports a subclass of it
 *  `package-b` - provides that `.js` file for import
 *  `package-c` - imports the subclass exported from `package-a`

When you try to build this app you get an error:

>    packages/package-a/declarations/src/index.d.ts:1:21 - error TS2307: Cannot find module 'ts-composite-error-b/foo' or its corresponding type declarations.
>
>    1 import { Foo } from 'ts-composite-error-b/foo';

Note that the error is present because the `.d.ts` from `package-a` is being type checked and it doesn't contain the `@ts-expect-error` comment that the source `.ts` file does.

### 🔎 Search Terms

`@ts-expect-error`, `composite`, `.d.ts`, `comments`

### 🕗 Version & Regression Information

I've reproduced this in `4.5.4`, `4.7.4` and `@next`. I have no reason to believe that there was an older version where it wasn't a problem.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about modules

### ⏯ Playground Link

Sorry - I couldn't figure out how to model the interaction between modules in a playground link so I made a repository:
https://github.com/vitch/ts-composite-error

### 💻 Code

I stripped it down as much as I could in:
https://github.com/vitch/ts-composite-error

### 🙁 Actual behavior

An error fired on the import

### 🙂 Expected behavior

The `@ts-expect-error` to be respected despite the additional "module hop"

**Comment by RyanCavanaugh** [comment]
This isn't a provided behavior of `ts-expect-error`. It can't prevent downstream consequences of the error you're suppressing.

**Comment by vitch** [comment]
Thanks for the quick response. It's the same with `ts-ignore` by the way but I guess that's also intentional...

Is there any workaround for this? It's something we're running into while incrementally converting a large monorepo to TypeScript...

**Comment by RyanCavanaugh** [comment]
What you'd want in this case is some commonly-referenced package declaring all the package paths you want to silence the error on
```ts
declare module "ts-composite-error-b/foo";
```

**Comment by vitch** [comment]
Thanks!
