### ISSUE TITLE
General object type is not assignable/equivalent to an object with specific properties

### ISSUE THREAD

**Issue by eliasm307** [microsoft/TypeScript#49758]
# Bug Report

### 🔎 Search Terms

general type missing properties

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Type System Behavior" 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/MYGwhgzhAEBiD29oG8CwAoaXoBMCmoYATntAGYCMAXNBAC5ECWAdgOYDcG2uB4J5AJhrMArgFsARniKd0AXwwZCUOIgBCxaHgAedPMxwwESNJmz5C-CdVoMWHLud7FSEodFGTpshegx0ATwAHUg0iAHlmEADoAF4Uaxp6JjYAGmg3YXEpIl9oJXhmemgANzAQG2MwrHjkOWhIVXh2aAB6Vtx4PAhmOmgAd3giAGt0sjBGIi1meBFWAAtFdGBC4rKQdyrNOJR6xuNoADJoMMjoto7BkYh0kQNpejADMAkQPCWVor71gGYaLamOzqDSMiCO0AASgQhjgADxPALpBEAPgunW6vQGQ2GAH50TAoSsiHCEUjmAFUTM+skRMA6CIiOVzisStIGuS6PN7CdiGcYmJGAs+vMwKycR9Vt9ygAWf7qba1PYE6HE+HkskUtE4Lo9PpXXH4yEqknq9maqm2Ii0+mMkDM+CsqYIznc05RfmC+bC0V4cV+dCBEJNChAxxYShJOxsWTcMjuTw5DC+fzBUgAkPxYwh46mbiJS32GPYTIebLeJMSr6lcoUSryoghoFK4Mtdr4zH6sYTKb6WYLStrGubeuNxUg4Pgt3nNv6m7QO74IiPZ6vd7+z6Dip-JphUe7ccHY6EmFqxFm1Ft7UYvXYvFX5VEk1nlEeeDUhjWhlMmIstnOrlsDyETutAApCtAIpigOUoVLKO7EHuwKNMeqqkueWo6h2t6GihT4apSb6Wp+tr2o6WiOjE8ASAAVgQfQgIwwykDSdIMr6QA)

### 💻 Code

```ts
class Foo {
    declare f1: string;
    declare f2: number;
}

class FooBar extends Foo {
    declare b1: string;
    declare b2: number;
}

type BarOnly = {b1: string, b2: number}
 
const val1: FooBar  = {} as Foo; // doesnt work, fair enough

const val2: FooBar  = {} as Foo & BarOnly // works, understandable

const val3: FooBar  = {} as Foo & Record<any, any> // doesnt work? does Record<any, any> not structurally cover anything BarOnly might have?

const val4: FooBar  = {} as Record<any, any> // doesnt work? does Record<any, any> not structurally cover anything BarOnly might have?

type Foo1 = {
    f1: string;
    f2: number
}

type FooBar1 = Foo1 & {
    b1: string;
    b2: number;
}

const val11: FooBar1  = {} as Foo1; // doesnt work, fair enough

const val12: FooBar1  = {} as Foo1 & BarOnly // works, understandable

const val13: FooBar1  = {} as Foo & Record<any, any> // doesnt work? does Record<any, any> not structurally cover anything BarOnly might have?

const val14: FooBar1  = {} as Record<any, any> // doesnt work? does Record<any, any> not structurally cover every object like structure?
```

### 🙁 Actual behavior

A general object type, with all keys and values allowed, is not structurally equivalent to an object with specific properties, the error says the general object type is missing properties from the specific object type.

### 🙂 Expected behavior

In the FAQ structural typing is summarised as 
> two types are compatible if their members are compatible

If I understand this correctly, `Record<any, any>` should be compatible with any object-like type as it supports any members. 

Also, an intersection of `Record<any, any>` with any other object-like type with specific properties should be compatible with any object-like type, but hopefully with IntelliSense etc for the explicitly defined properties (IntelliSense currently works like this but mentioning it to make sure it is maintained).

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. See https://stackoverflow.com/questions/58458308/what-does-a-typescript-index-signature-actually-mean for an in-depth explanation

**Comment by eliasm307** [comment]
I see, so it was a design decision for safer assignments. Unfortunately its incompatible with my use case, would you be able to provide any tips of any alternatives if possible?

My use case for this is that I'm working on typing some existing code where some class instances are kept in a map, which is dynamically populated so cant be statically typed, where some id is the key and the instance is the value. The class instances all extend some base class, so I was hoping to have atleast the members of the base class available via intellisense and type checked, and the existing code doesnt need to be touched (if its not using the base class members incorrectly). However, with this limitations, it means typing the map would require every usage of objects from the map to be casted so something like:
```ts
class BaseClass {}
class SomeClass extends BaseClass {}

const classMap: Record<string, any>;

function(someId): SomeClass {
  return classMap[someId];
}
```

needs to be changed to:
```ts
class BaseClass {}
class SomeClass extends BaseClass {}

const classMap: Record<string, BaseClass>;

function exampleFunction(): SomeClass {
  // ... some code
  return classMap[someId] as SomeClass; // type cast now required
}
```

This is a core aspect of the code I'm working with and its used everywhere so the effort to add these casts in is significant, and it doesnt really add a lot of value for existing usages.  However, any new usages suffer as they just have an `any`, is there any way to get around this without having to change existing code?

If its not possible my fallback is to have new code use a utility which does the casting e.g.
```ts
function getItem<T extends BaseClass = BaseClass>(id: string): T {
  return classMap[id] as T
}
```

And I think this should provide the typing and flexibility, as I think Typescript can also infer generics from the expected return, e.g.
```ts
function exampleFunction(): SomeClass {
  // ... some code
  return getItem(someId); // casts it to SomeClass
}
```

see [playground example](https://www.typescriptlang.org/play?ts=4.7.4#code/MYGwhgzhAEBCkFMDC4rQN4FgBQ0-QBMFQwAnBaAI0QFkEBbShUgLmggBdSBLAOwHMcAXxwk0AZQD29ZKhgIAHhwS8CMeBFmQYWXPiIly7aVqh1GzNrwCuF0sJyjJvTtDEQaYAA5sASsUlSAgAeTh4BABo4RBRtaAAyaH9gQJCwXgBPKPSMgD5c6ABeDCEAbkdsADNrXmAObmdoRTB6LxAEADEauobeAAoASjYpGVi0XTwUlw5obgIi6AByCBMAWjnFnEnnVz5OdOAKYvdPLwBtOYBdcr09jgOEADpqTXMme1vph8eV0bk35ilaAAemBTQU3E4fH4bkkRDc6Wg1k00By0BkdggWxBYMeeOMMlhRGx5A41lIvFmX1qFEg0BGpggQNB0A4GS8FGAkBmvEkAHdoOQAI7WbjkAjZaAgSQzSSVJEQMD8BAwDiSNwAC3Syoc2BwLL53A4GqR9RAUWcIAy0EqgWgvAQApSxL1VW69Uayo4AEllPRggAVcHKVTqGJyBYaRm5PpzNhhaFDaBBiaChBkiluf7eC4ES6omAB3U4aq1D2U5qtdpdMu9ABMg2GJjGOmxU1282KyzWG2xLLxjwJnLhCBJ6fJlK9voYsYIA2ZYOVDp4wCplWYpHFwiAA)

But not sure if this will have limitations when we start using it. Is there a better way?
