### ISSUE TITLE
"Extending expressions" feature in TypeScript 1.6 leads to inconsistent compiler behaviour.

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TypeScript#4975]
**"Extending expressions" feature in TypeScript 1.6 leads to inconsistent compiler behaviour.**

Dear ladies and gentlemen, 

I have a question regarding the compiler behaviour change for the new TypeScript 1.6 feature: 
"Expression extending".

[Description at: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript]
![featuredescription](https://cloud.githubusercontent.com/assets/9468599/10109332/3452fb2e-63be-11e5-9c5a-828b24d4fe0e.png)

Before V1.6 I wasn't able to drive from the built-in classes and got a compiler error at design time. 
The compiler simply didn't let me do it. 

[compile-time error]
![compilererror](https://cloud.githubusercontent.com/assets/9468599/10109359/54278f50-63be-11e5-87ce-17da70081210.png)

Now I'm able to drive from the built-in classes and I'm very happy about that. But unfortunately that also has the effect that I don't get any warning when I'm going to derive from unsupported classes. 
Here is an example where I drive from the "HTMLElement" class.
The compiler let me do that, but afterwards I get a runtime error.

[runtime error]
![runtimeerror](https://cloud.githubusercontent.com/assets/9468599/10109390/859e77d8-63be-11e5-9cc0-06ac2ee62ce9.png)

The powerful error handling system of the TypeScript compiler is one of the features I like most. Before, I was able to make any stupid mistake in JavaScript and could only hope that such errors would reveal themselves at runtime. Hopefully before my code went into production. With the 1.6 release you relaxed the error handling system of the compiler. An error which was a compile-time error before became a runtime error with this release. 

My question is, did you do that by purpose or was it an unpredicted side effect?

Before you ask, I'm aware that the "HTMLElement" class is not a built-in class but a WebAPI class. But before 1.6 I didn't have to worry about that in any way. WebAPI or built-in, the classes were all handled the same way. 

I would appreciate if you could clarify that for me.

Kind regards, Lord Saumagen.

**Comment by weswigham** [comment]
You should be able to subclass `HTMLElement`, according to the information available on custom elements. If you cannot, it's potentially an issue in the browser you're targeting which you'll need to work around, such as [here](https://github.com/babel/babel/issues/1548).

**Comment by mhegazy** [comment]
also see https://github.com/Microsoft/TypeScript/issues/1168#issuecomment-107833988 for related discussion.

**Comment by SaschaNaz** [comment]
Out of curiosity, was it working *in runtime* on TS 1.5?

**Comment by lord-saumagen** [comment]
@SaschaNaz

Dear Sacha Naz,

I'm sorry, but I can't answer that question. I made a jump from TS 1.3 to TS 1.6. I never used the 1.5 compiler version. 

Kind regards, Lord Saumagen

**Comment by lord-saumagen** [comment]
@weswigham, @mhegazy

Dear eswigham and mhegazy

thank you both for your suggestions. You saved my day.

Kind regards, Lord Saumagen.
