### ISSUE TITLE
[ERR]: "执行 JavaScript 失败:"  [ERR]: Cannot read properties of undefined (reading 'replace') 

### ISSUE THREAD

**Issue by masx200** [microsoft/TypeScript#49752]
# Bug Report
```
[ERR]: "执行 JavaScript 失败:" 
[ERR]: Cannot read properties of undefined (reading 'replace') 
```

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions _4.7.4_____ and ___4.7.4____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/zh/play?removeComments=true&target=99&ssl=25&ssc=10&pln=25&pc=22#code/GYVwdgxgLglg9mABAExsYB1AhgTwM4AqcAwnALYAOIUApgBQ0AeFATjXnvGAFyJ5QsYYAOYBKXmBBkARjRYBtALqIA3gChEmxGkR0A9AD0AOsgDUAEj3CAdLX4NmbDl1GjVGrZ7ZQQLJPIA5KVkWB1Z2TgRRRQBuD00AX3jECAR+RDZhJgpEAF5EPToAfgAeOAo5LCg4FgA+eSNTIwBaIwAqRVEAH2KS1GEYKFqTU1ErOM9UsHThFjgQCjw8xABBFhZca2A5sjCnSLBrMiqIAAsVgBsLukzs1yOsCjpkzzosN1zaxCxrWfnF5JuLBLcAAazAcAA7khgboXlouu5PMjkf1Brx+IIRBMUbjypVqiwirxwMgaMAhDRkDjcYgkrTEepaSi0VBiYhSeTKdT4bT8RtCRiBEJhDTcfStKIlGKpuksNMJME5EpltLkrKoIh5lAqJr8nRJGRFTI5B8vkzcfK8NYqHhTgapKIxQkxah0Nh8MQsBcIHQ-gs8AAaLXUXVO5LeXww6ZxJKgSCwBAoNCYXB4L0+56ef2LXhZ3GM3m41nGkKIRGYkVi5laioCmrszkUsBU6vIiUows1zysxtgMnN1tFlH8qo1IVY0XDumApSB5La3V5w2l015L4ANzgMGQajcFs0srgFxo1gucGEfrmAdEyR0V-+1pPIigpzyuXyAEZ90XF9Q6EEJqhDmeDyAADIo1isq4baaJGfjOnewC6CBZ40C+b4fvkADMP60hqiDyFgwbSMGEDKPkIGwdoyF0NI1ijoS775AARKYLF4d2f5QABSqhD80GIKYiCASEdAQFBMADFAMHTnBNA+AhRYdsi970YxNTMYgLHNBxSJcaG-6iXIbySdJbjNCJfHiWZgyyd2GQKVG1EqZ4akMXWY4sFpLFtHpB7MtxvFAaZgltFZIUSdB4YOfBYAuUWcWIZMaSavIFIsPwwZ4DQUzIMGr4wCw+WINYZVOFAFGIFRyRuqmnrer66VFVlfC5QgJWFcVijBg6RqIIaIRmkWdUeumjV0PIKjJtJxp0sGZXWBVPUhjq1C3p4MVaKNaYZk1XUlYty29SuA18cNtI7Q1mbNZlUDZe1-bBtNJZnWQdIrdxG2SrGahHieZ4XnQV2ECQ5C6vQLEAExtJ+bQAKwcaIQA)

### 💻 Code

```ts
function diffWaysToCompute(expression: string): number[] {
    if (/^\d+$/g.test(expression)) {
        return [Number(expression)];
    }
    const regexp = /(?<operator>[\+\-\*])|(?<digit>\d+)/g;
    const groups = Array.from(expression.matchAll(regexp)).map(
        (a) => a.groups
    ) as unknown as (
        | {
              digit: string;
              operator?: undefined;
          }
        | {
              digit?: undefined;
              operator: string;
          }
    )[];
    const ans: number[] = [];
    const output = (num: number) => {
        ans.push(num);
    };
    diffWaysCalc(groups, output);
    return ans;
}
function diffWaysCalc(
    groups: (
        | {
              digit: number | string;
              operator?: undefined;
          }
        | {
              digit?: undefined;
              operator: string;
          }
    )[],
    output: (num: number) => void
) {
    console.log(groups)
    if (groups.length === 1) {
        output(Number(groups[0].digit));
        return;
    }
    if (groups.length === 3) {
        const [a, b, c] = groups;
        if (b.operator === "+") {
            output(Number(a.digit) + Number(c.digit));
            return;
        }
        if (b.operator === "-") {
            output(Number(a.digit) - Number(c.digit));
            return;
        }
        if (b.operator === "*") {
            output(Number(a.digit) * Number(c.digit));
            return;
        }
        return;
    }
    const [first, second, third, ...rest] = groups;
    diffWaysCalc([first, second, third], (num: number) =>
        diffWaysCalc([{ digit: num }, ...rest], output)
    );
    diffWaysCalc([third, ...rest], (num: number) =>
        diffWaysCalc([first, second, { digit: num }], output)
    );
}
console.log(diffWaysToCompute("2*1*5"))
```

### 🙁 Actual behavior

```
[ERR]: "执行 JavaScript 失败:" 
[ERR]: Cannot read properties of undefined (reading 'replace') 
```
### 🙂 Expected behavior

no error

**Comment by jcalz** [comment]
This looks like a TS Playground bug with its `console.log` and therefore belongs on TypeScript-Website instead of here.  More minimal repro is:

```ts
console.log("str".match(/(?<x>.*)/)?.groups); // "str is undefined" in Playground
```
[Playground link](https://www.typescriptlang.org/play?target=7#code/MYewdgziA2CmB00QHMAUAiCAXATu+AtgIZbAAWqA9KgPwA8AHgHzwBUAlJezfMjiAFcADhHZA)

**Comment by jordanmbell** [comment]
This was an issue with assuming all objects have the `constructor` property, but those created with `Object.create(null)` do not.
