### ISSUE TITLE
Throw type error while working with reflect-metadata.

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#49753]
# Bug Report

### 🔎 Search Terms

metadata, decorator, reflect-metadata

### 🕗 Version & Regression Information

Import `reflect-metadata`.

Decorate a class by a function returns an object.

TS allows decorator returns any value. When Reflect.decorate defined by reflect-metadata, TS will use this function to define metadata instead of TS implements. Reflect.decorate couldn't process un-class return value returned by a class decorator.

### 💻 Code

```ts
import 'reflect-metadata'

function Deco(){
  return {}
}

@Deco()
class Foo{}
```

### 🙁 Actual behavior

Throw type error by reflect-metadata.

### 🙂 Expected behavior

No error thrown and class decorated correctly.

https://github.com/rbuckton/reflect-metadata/issues/139

**Comment by ruojianll** [comment]
According to decorator stage 3, class decorator must return a class constructor.

> Class decorators receive the class that is being decorated as the first parameter, and may optionally return a new class to replace it. If a non-constructable value is returned, then an error is thrown.

Is there any plan for decorator api in the future?

**Comment by rbuckton** [comment]
> TS allows decorator returns any value.

Class decorators should return either a `function` or `void`/`undefined`. Returning an object isn't supported and results in compiler errors:

![image](https://user-images.githubusercontent.com/3902892/185686833-8d50ed55-06e8-478e-9799-fc64fec5d42a.png)

The TypeScript `__decorate` helper avoids some runtime checks that the compiler detects at build time as errors to reduce the size of the helper. The `Reflect.decorate` helper in `reflect-metadata` does not avoid those runtime checks.
