### ISSUE TITLE
Types are inferred too narrow from template strings in a readonly object starting from TypeScript 4.7

### ISSUE THREAD

**Issue by graphemecluster** [microsoft/TypeScript#49762]
### Bug Report

**Credit:** Translate from [this tweet](https://twitter.com/MH4GF/status/1542443055298449408) by @MH4GF

**Version & Regression Information:** This changed between versions 4.6 and 4.7

**Code:** [Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBADgJwKYDMCWAPGBeGByRVTPAKBIHpyYBJMFJBZAExgEMI2w3HWBPGEChgQ4SYGnTBhUBGjABzGAHcAFki5wArlChzFUNTADWSXuQBurADaakMANqDOAgEYArMVAC6ytAZgA8u6eAHQoyEgAXnasYCxQSAC2cFasCdKyCjByUCDOrDy8JKCQsOFIUUgA6n4qACopQW44gcHAUGER0QAUAN4kMIMwKCAgAFwwAAYAJL2E6BgAviMgkySLAJTF4NDcvACMLfbllTUGDVZNYaNeANwUVNgAfHv7EwBE85gr7-ZeDw46ghYhArCEYAA5EAJHwAVQgSHieRcdmgmXkf3gshACBguRgABYQgB2MiUBy0eiMRFsCA+VgZPTcYH8JS1ARgKz8BLJVLpNF6balPGNdwtfpDYajCYzObIBbLUZrRZC3YFXgAJiOUFFbmuIDuAOeew1EwFCj+ZKo9kpDGYtPpjKyBRZvn84C5rQ87U6FWiqrKXSQTRaTVCJx6EqGKw+P3WWxKaoQvAAzEcI8H3PrDeTjeqU2aZHpLQCbXQ7TT2I7zYoXXw3SoYGAkLUGF7w0Gmzi8UkUmlUUWFAHXM1cFHBjGYO84yrE7B1QSjiAsysc48XgvC+iS0A)

```ts
const prefix = 'prefix'

// Inferred as an array of specific string when putting the key/value [of an object] with Object.freeze and template string into an array
const freezeWithTplObj = Object.freeze({
    foo: `${prefix}foo`
})
const ary1 = [freezeWithTplObj.foo];
// => ary1: "prefixfoo"[]
// [Transl. Note] Used to be string[] prior to 4.7

// [Inferred as] a string array with only template string
const tplObj = {
    foo: `${prefix}foo`
}
const ary2 = [tplObj.foo];
// => ary2: string[]

// [Inferred as] a string array with only Object.freeze
const freezeObj = Object.freeze({
    foo: "foo"
})
const ary3 = [freezeObj.foo];
// => ary3: string[]

// [Inferred as] a string array with neither Object.freeze nor template string
const obj = {
    foo: "foo"
}
const ary4 = [obj.foo];
// => ary4: string[]
```

**Actual behavior:** `ary1` inferred as `"prefixfoo"[]`

**Expected behavior:** `ary1` inferred as `string[]`

**Comment by RyanCavanaugh** [comment]
e.g. https://github.com/microsoft/TypeScript/issues/10725#issuecomment-353802406
