### ISSUE TITLE
Can the compiler be configured to resolve modules relative to a search path?

### ISSUE THREAD

**Issue by mylesmegyesi** [Microsoft/TypeScript#4976]
First off, sorry if this isn't the appropriate place to pose this question.

After digging through the documentation, I wasn't quite sure if this was possible or not. I would like to be able to specify a list of "search paths", similar to Ruby's load path or Java's classpath from which modules get resolved.

If this isn't possible currently, is there a way to do this by working directly with the Compiler API and writing a custom module resolver?

**Comment by DanielRosenwasser** [comment]
You can use the [compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) for TypeScript 1.6 and supply a custom `resolveModuleNames` method in your compiler host.

Here's the signature for `CompilerHost` if it helps:

```TypeScript
    export interface CompilerHost extends ModuleResolutionHost {
        getSourceFile(fileName: string, languageVersion: ScriptTarget, onError?: (message: string) => void): SourceFile;
        getCancellationToken?(): CancellationToken;
        getDefaultLibFileName(options: CompilerOptions): string;
        writeFile: WriteFileCallback;
        getCurrentDirectory(): string;
        getCanonicalFileName(fileName: string): string;
        useCaseSensitiveFileNames(): boolean;
        getNewLine(): string;
        
        /*
         * CompilerHost must either implement resolveModuleNames (in case if it wants to be completely in charge of 
         * module name resolution) or provide implementation for methods from ModuleResolutionHost (in this case compiler 
         * will appply built-in module resolution logic and use members of ModuleResolutionHost to ask host specific questions).
         * If resolveModuleNames is implemented then implementation for members from ModuleResolutionHost can be just 
         * 'throw new Error("NotImplemented")'  
         */
        resolveModuleNames?(moduleNames: string[], containingFile: string): ResolvedModule[];
    }
```

Sorry to say we don't currently have an example for this on the wiki though. If you have one that you'd like to contribute, that would be helpful. :smile:

**Comment by vladima** [comment]
Currently compiler does not expose any standard ways to resolve modules in the way you've asked. The only two options that are bundled with 1.6 are:
- node module resolution
- 'classic' resolution which is effectively walking from the file containing the import up to the root and try to resolve name of imported module at current step.
#2338 discusses adding of 3rd way of module resolution which is a slightly augmented version of RequireJS\SystemJS and it should allow you to specify multiple locations

**Comment by vladima** [comment]
[ts-loader](https://github.com/TypeStrong/ts-loader/blob/master/index.ts#L305) has an implementation of `resolveModuleNames`

**Comment by mhegazy** [comment]
@vladima can you add an example to overriding the resolution in the [compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) wiki page.

**Comment by vladima** [comment]
sure, I'll do this later tonight

**Comment by vladima** [comment]
[Customizing module resolution](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#customizing-module-resolution)

**Comment by mylesmegyesi** [comment]
Wow! Thanks all!

One question about the code example, what is the first parameter (`rootFiles`) to the `compile` function used for?

**Comment by vladima** [comment]
@mylesmegyesi this is the set of source files to be compiled. I've renamed them in the sample, sorry for confusion.

**Comment by mhegazy** [comment]
thanks @vladima
