### ISSUE TITLE
Types not matching when use destructuring assignment, but the hint error is ignored

### ISSUE THREAD

**Issue by hxse** [microsoft/TypeScript#49761]
# Bug Report

### 🔎 Search Terms
Types not matching destructuring assignment hint error ignored

### 🕗 Version & Regression Information
ts version: 4.6.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAhgKuaBeKBvWAuKA7ArgWwCMIAnKAXwFgAoAYwHtsBnYTWBSKFdGLARgBMAZgA0UQlgAsAVgBsFGg2asJ7RFzRtBoqADp96VTPnkF1IA

### 💻 Code

```
type aType = { a: number }
const a: aType = { a: 123, b: 456 } // ✅ hint error 
const b: aType = { a: 123, ...{ b: 456 } }// ❌ not hint error, why?
```

### 🙁 Actual behavior
const a hint the error
const b not hint the error

### 🙂 Expected behavior
const a hint the error
const b hint the error too, beacuse aType don't match "{ b: 456 }"

**Comment by Josh-Cena** [comment]
See https://github.com/microsoft/TypeScript/issues/39998

There's no type-safety loophole here, to say the least... Excess property checks is more of a linting feature.

**Comment by hxse** [comment]
Let me add two lines
```
type aType = { a: number }
const a: aType = { a: 123, b: 456 }
const b: aType = { a: 123, ...{ b: 456 } }

const c: { c: number } = { c: 789 }
const d: aType = { a: 123, ...c }
```
The type of const c is certain, but still no hint the error, when it on the deconstruction assignment, Isn't this so strange?

**Comment by Josh-Cena** [comment]
Excess property checks only kick in when the RHS is an object literal, because otherwise there's a non-negligible possibility that you are reusing an object value from elsewhere.
