### ISSUE TITLE
`Parameters<>` utility type does not respect `exactOptionalPropertyTypes`

### ISSUE THREAD

**Issue by nemosmithasf** [microsoft/TypeScript#49765]
# Bug Report

### 🔎 Search Terms
- exactOptionalPropertyTypes
- Parameters
- Utility Type

### 🕗 Version & Regression Information

4.7.4

### ⏯ Playground Link
[Playground link with relevant code](
https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/MYewdgzgLgBFCmBbADjAvDAZgVzMKAluDABTICGATuYgPwBcM0lBYA5gJQwDeAvgNwwA9ENIVqdRs1ad0APhgA3EAQAmAWABQWqAE9k8OElQYAClRrwElCAB49BkJiMo5gkTADa4mgyZQWdhgAHxhcVXhMVnhVAF0tGESk5JTUtPSMzI8APVy8vJgAZQALEGwAG1UwAHJYACNDYvhKeCA)

### 💻 Code

```ts
const temp = function (param?: string) {}; // (param?: string) => void

type temp = Parameters<typeof temp>; // [param?: string | undefined]
                                                       // ^^^^^^^^^ Shouldn't be here
```

### 🙁 Actual behavior

`undefined` is included in the `Parameters<>` output even when `exactOptionalPropertyTypes` is on

### 🙂 Expected behavior

The output should match the function parameters exactly, so no `undefined` value

**Comment by MartinJohns** [comment]
That's a parameter, not a property. `exactOptionalPropertyTypes` does not matter here. Also, `undefined` is currently a valid value for an optional parameter, unless #12400 is implemented.

**Comment by nemosmithasf** [comment]
Hmm, strange. It seems 4.7.4 will not automatically append `| undefined` to optional params in the function type; but 4.6.4 does. 

I also see where you're coming from, but if you think about it: if you want a tuple representation of a parameter, then optional parameters would translate to optional properties... in which case `exactOptionalPropertyTypes` should carry over.ss
