### ISSUE TITLE
JSON.stringify space (third) argument should allow nulls

### ISSUE THREAD

**Issue by ericcornelissen** [microsoft/TypeScript#49766]
# lib Update Request

## Configuration Check

My compilation *target* is `es2019` and my *lib* is `the default`.

## Missing / Incorrect Definition

The [`JSON.stringify` method](https://github.com/microsoft/TypeScript/blob/1b9c8a15adc3c9a30e017a7048f98ef5acc0cada/lib/lib.es5.d.ts#L1060-L1073) does not allow for the `space` option to be `null`.

## Sample Code

```js
   JSON.stringify({ foo: "bar" }, null, null);
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// No overload matches this call.
// ...
// Argument of type 'null' is not assignable to parameter of type 'string | number | undefined'
```

## Documentation Link

- [`JSON.stringify()` at MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#parameters): States it should be a `Number`, `String` or the value `null` (or omitted).

- [`stringify(value [, replacer [, space]])` in the spec](https://262.ecma-international.org/5.1/#sec-15.12.3): Is even more lenient as it states

  > [...]
  > 5. If [Type](https://262.ecma-international.org/5.1/#sec-8)(space) is Object then,
  >   a. If the [[Class]] internal property of space is "Number" then,
  >     i. Let space be [ToNumber](https://262.ecma-international.org/5.1/#sec-9.3)(space).
  >   b. Else if the [[Class]] internal property of space is "String" then,
  >     i. Let space be [ToString](https://262.ecma-international.org/5.1/#sec-9.8)(space).
  > 6. If [Type](https://262.ecma-international.org/5.1/#sec-8)(space) is Number
  >   a. Let space be min(10, [ToInteger](https://262.ecma-international.org/5.1/#sec-9.4)(space)).
  >   b. Set gap to a String containing space space characters. This will be the empty String if space is less than 1.
  > 7. Else if [Type](https://262.ecma-international.org/5.1/#sec-8)(space) is String
  >   a. If the number of characters in space is 10 or less, set gap to space otherwise set gap to a String consisting of the first 10 characters of space.
  > **8. Else**
  >   **a. Set gap to the empty String.**
  > [...]

**Comment by jcalz** [comment]
Note that the spec is always going to be more lenient than TypeScript: see [What does "all legal JavaScript is legal TypeScript" mean?](https://stackoverflow.com/q/41750390/2887218) for more information.

**Comment by RyanCavanaugh** [comment]
This doesn't seem like it would improve the definition.

**Comment by ericcornelissen** [comment]
> Note that the spec is always going to be more lenient than TypeScript: see [What does "all legal JavaScript is legal TypeScript" mean?](https://stackoverflow.com/q/41750390/2887218) for more information.

That makes sense. I primarily included it as a reference to show that what I suggest is indeed valid.


> This doesn't seem like it would improve the definition.

Fair enough.
