### ISSUE TITLE
Incorrect behavior of `ArrayLike<infer T> | Iterable<infer T>`?

### ISSUE THREAD

**Issue by graphemecluster** [microsoft/TypeScript#49764]
### Bug Report

**Search Terms:** assignability, extends, generics, array like, iterable

**Version & Regression Information:** This is the behavior in every version I tried

**Code:** [Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/PTAEDkHsDsFoBMCWBnALgJ0QIwK6sQG4CmAXAFCoCeADkaAGKSQAMoAvKAILroCGlAGUQBrIgB40maAHMAfKAA+oAJKoifLABtxkxDPlLoOALZZ1AbQC6oIgA810eMi49+Q0WN7RKBlWo3ant7yAPygGDh0JKAAZryayERkIKCpAHohFDR0AEK86Kwc3HyCIjoYenKKfuq8WuVSVYYmZuhWNvZEjs7FbmViejHqoAAqvqq19QPQQ+ijoaPt0dBExOjJYOmZVLSgeQBehS4l7g2V4-51gbr61UamFtZ2Dk7HfR6Dw2PVEwHin3MAKoLEbtJSApagFZrDapUAZMiwgAiKAquHwxHIOzojEgAEYRmJvhwRh0Xj1XKUPF4fD9LlMaQsIlFYvFElldri8ewGEwCWJelSzrclL8rsKmlCWo9ZLCthzcvl+cTRmSuq9BadprN5nTJoEAbqwqDrMtVuoFXslTy8uh+Zr+jdJWKpk7fPdWlZZSl5dirftlfISWrum8hdqvhd9f8ZsNgaBjWDQBDTVDzes-QduRws4SHR43Xq-hIKiKpQ82pZvZt4ZkgA)

```ts
// Non-distributive:
type Foo0 = ArrayLike<string> | Iterable<string> | number[] extends ArrayLike<any> | Iterable<any> ? true : false
//   ^?: type Foo0 = true
type Bar0 = ArrayLike<string> | Iterable<string> | number[] extends ArrayLike<infer T> | Iterable<infer T> ? T[] : never
//   ^?: type Bar0 = never
type Baz0 = ArrayLike<string> | Iterable<string> | number[] extends ArrayLike<infer T> | Iterable<infer U> ? T[] | U[] : never
//   ^?: type Baz0 = never

// Distributive:
type Foo1T<T> = T extends ArrayLike<any> | Iterable<any> ? true : false
type Foo1 = Foo1T<ArrayLike<string> | Iterable<string> | number[]>
//   ^?: type Foo1 = true
type Bar1T<T> = T extends ArrayLike<infer T> | Iterable<infer T> ? T[] : never
type Bar1 = Bar1T<ArrayLike<string> | Iterable<string> | number[]>
//   ^?: type Bar1 = number[] | string[]
type Baz1T<T> = T extends ArrayLike<infer T> | Iterable<infer U> ? T[] | U[] : never
type Baz1 = Baz1T<ArrayLike<string> | Iterable<string> | number[]>
//   ^?: type Baz1 = number[] | string[] | unknown[]
```

**Expected Behavior:** Types `Bar0`, `Baz0` and `Baz1` being `number[] | string[]`.

**Comment by RyanCavanaugh** [comment]
This all looks correct to me. Can you make a more explicit case for why you consider this wrong?

Aside: it's very confusing to have same-named variables in the same small repro

**Comment by graphemecluster** [comment]
I was digging into the behavior of the `Array`-related types when I was making up a good definition of `Array.isArray` for, again, [uhyo/better-typescript-lib](https://github.com/uhyo/better-typescript-lib).

I've edited the comment. Hopefully it's clearer now.

For the first 3 types, if `Foo0` holds, I suspect that `Bar0` and `Baz0` also hold.

For the last type, `Baz1`, I can't understand why it consists of an `unknown[]`.

**Comment by RyanCavanaugh** [comment]
I see. I believe this misunderstanding is what `infer` does when the same type variable appears in multiple positions.

What you're expecting is that these utterances act as *separate* paths that the checker can take, but that's not how it works. When you have the same `infer T`, TS is trying to find a type that fits both instances *at once*. It's effectively the same as if you had written
```ts
function check<T>(x: ArrayLike<T> | Iterable<T>) { }
// Fails
check(null as any as ArrayLike<string> | Iterable<string> | number[]);
```
which fails because there are three candidates collected for `T` - `string`, `string`, and `number`.

`Baz1` includes an unknown because when zero candidates get collected for `T` or `U` respectively, the resulting inference is `unknown`
