### ISSUE TITLE
[DRAFT/RFC] `Uncertain` type

### ISSUE THREAD

**Issue by stevefan1999-personal** [microsoft/TypeScript#49781]
# Suggestion

## 🔍 Search Terms

uncertain typecheck runtime

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add `uncertain` type to notify there is a chance the input won't be exactly the type as you wish.

## 📃 Motivating Example

Here's an example:
```ts
// in ts code, this is normal and well
export function foobar(x: number) {
    return x % 2 ? "foo" : "bar"
}

// in js code, however
foobar("2")
// but the error message does not help

```

Here's how you could solve it:
```ts
// in ts code, this is normal and well, Uncertain accepts any type except unknown, undefined and null
export function foobar(x: Uncertain<number>) {
    if (!Number.isInteger(x)) {
        throw "x is not a number"
    } else { // x must be a number (and an integer)
        return x % 2 ? "foo" : "bar"
    }
}

// in js code, now we will get a better error message
foobar("2")
```

However, if you have multiple other checks, they might fail as well. Thus, even after strong runtime assertion, we still consider the uncertain variable to still be uncertain:
```ts
// in ts code, this is normal and well
export function foobar(x: Uncertain<number>) {
    if (!Number.isInteger(x)) {
        throw "x is not a number"
    }
    // Error: x is uncertain
    return x % 2 ? "foo" : "bar"
}

// in js code, now we will get a better error message
foobar("2")
```

For this situation, you use `!` postfix operator to assert certainty:
```ts
// in ts code, this is normal and well
export function foobar(x: Uncertain<number>) {
    if (!Number.isInteger(x)) {
        throw "x is not a number"
    }
    
     // force x to be one of the type in Uncertain<number> which is number
    return x! % 2 ? "foo" : "bar"
}

// in js code, now we will get a better error message
foobar("2")
```

## 💻 Use Cases

It's very simple: sometime you aren't so sure whether your input really is the right type in runtime, especially for JS to TS interop. Sometimes due to lack of information you might have entered a string equivalent of the number while TS "expects" number. This would of course fail, but the error message could be cryptic, and also we should be able to take care of this bad expected type situation by hand preemptively.

## Prior Art

[fabiandev/ts-runtime](https://github.com/fabiandev/ts-runtime)

[janjakubnanista/ts-type-checked](https://github.com/janjakubnanista/ts-type-checked)

#1573

**Comment by Josh-Cena** [comment]
What about:

```ts
function validateX(x: unknown): asserts x is number {
  if (!Number.isInteger(x)) {
    throw new Error("x is not a number");
  }
}

export function foobar(x: unknown) {
  validateX(x);
  return x % 2 ? "foo" : "bar"
}
```

**Comment by MartinJohns** [comment]
- How would intersections behave?
- How would unions behave?
- How would you distinguish between the existing `non-null assertion operator` and your hypothetical "make certain operator"?
- How would you deal with code bases that already have a `Certain` type?
- What's the type-definition of the `Certain<T>` type?

This overall feels like a very bad approach, that adds uncertainty to the type-system where it does not belong. We already have a working solution with `unknown` and type-guards. Of course this only works within the type-system of TypeScript and fails when you validate external input, but there you should simply validate your data whenever you receive this external input.

**Comment by Josh-Cena** [comment]
I like this idea overall. `Uncertain<T>` means to the outside the type is `T` (i.e. TypeScript users get strong compile-time validation), while to the inside the type is `unknown` (i.e. forces runtime validation).

In the status quo, you have to do some weird things to achieve this.

```js
function validateX(x: unknown): asserts x is number {
  if (!Number.isInteger(x)) {
    throw new Error("x is not a number");
  }
}

export function foobar(x: number): string;
export function foobar(x: unknown) {
  validateX(x);
  return x % 2 ? "foo" : "bar"
}
```

**Comment by RyanCavanaugh** [comment]
I don't see how this is a type that can be reasoned about meaningfully apart from `unknown`.

One way to reason about a type is that it's a set of values... but what we're saying here is that an `Uncertain<T>` explicitly includes values that aren't `T`s. It's the same as `unknown`; the Venn diagram of those two sets is a circle.

Another way to reason about a type is that it's a predicate on a value, but this predicate always produces "yes"? Again, it's the same as `unknown`.

The missing feature to make just using `unknown` everywhere is probably #15048, since `isInteger` can't be correctly written to narrow to `number` without it.

**Comment by Josh-Cena** [comment]
Could it be a declaration emit feature? For example, all `Uncertain<T>` gets re-written to `T` in the emitted declaration, but during compilation, it's treated as `unknown`.

**Comment by Josh-Cena** [comment]
I was thinking for one moment whether `uncertain` would be useful outside function parameters—but can't find a valid use-case.

**Comment by RyanCavanaugh** [comment]
I can't imagine writing this style of code for more than a handful of functions in my codebase. It seems like using the overload pattern Josh-Cena mentioned would be sufficient in those cases.

**Comment by AlCalzone** [comment]
@RyanCavanaugh We actually have a use case for this in ioBroker.

The core package has quite a big API surface which can be called from lots of different sources, including external packages by other developers. Some of those are typescript, but a large amount are Javascript with type checking disabled. Historically, a LOT of type errors in the package come from incorrect external code.

Our current approach while migrating the core package to TS is what was proposed above as a workaround:
- Overload all externally visible methods with a single overload with the "official" signature
- Use `unknown` in the implementation signatures and check all parameters
- After checking all parameters, call an internal variant of the method which matches the "official" signature.

This is pretty unergonomic and having a built-in way of defining the expected signature while still forcing checks on all arguments would be welcome.

**Comment by forabi-cosuno** [comment]
Maybe a better alternative is to allow a function to define whether it could throw, and if so, what type of errors:

```ts
function validate(): number, throws RangeError {
  if (Number.isInteger(x)) {
    return x;
  }
  throw new RangeError() // Works
  // throw new TypeError() // Does not work. TypeError is not assignable to RangeError
}
```
