### ISSUE TITLE
Some name is not exported when targeting System.js

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#49787]
# Bug Report

### 🔎 Search Terms

- Systemm, SystemJS, System.js
- export, `export import =`

### 🕗 Version & Regression Information

all

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=1&module=4&sourceMap=true#code/KYDwDg9gTgLgBASwLaVnASsAhgY3gXjimAEcBXBYgCgCJjcYaBKAbiA)

### 💻 Code

```ts
export import React = require("react");
```

### 🙁 Actual behavior

```JavaScript
System.register(["react"], function (exports_1, context_1) {
    "use strict";
    var React;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (React_1) {
                React = React_1;
            }
        ],
        execute: function () {
        }
    };
});
```

### 🙂 Expected behavior

```JavaScript
System.register(["react"], function (exports_1, context_1) {
    "use strict";
    var React;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (React_1) {
                React = React_1;
                exports_1("React", React_1);       // <--------------- We should export it
            }
        ],
        execute: function () {
        }
    };
});
```

**Comment by sadokjbenyeni** [comment]
Hello, I would like to fix this bug is it still available, thank you .
