### ISSUE TITLE
await of class with then function can compile in some situation

### ISSUE THREAD

**Issue by Mirokko** [microsoft/TypeScript#49780]
# Bug Report

### 🔎 Search Terms
then, executes, autoexecution

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about async/await.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/MYGwhgzhAEAqCmEAu0DeAoaXsAcCuARiAJbDRIAW8AdgBQAmiSx1YzA9tQFzS0CUAXgB80MNQCefHmPFpM2AE7wkeBdWiNkLNsU7yAvunSHMtSOOpl+0YXOxYwAdzDEU1eI7hN+mfX35AA)
### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

Cannot "compile" with error "Type of 'await' operand must either be a valid promise or must not contain a callable 'then' member.". Like you can see [here](https://www.typescriptlang.org/play?ts=4.7.4#code/MYGwhgzhAEAqCmEAu0DeAoaXsAcCuARiAJbDRIAW8AdgBQAmiSx1YzA9tQFzRjUCeASh59+aTNgBO8JHknVojZCzbFOEgL7p0WzLUj9qZWoOgBeAHzjsWMAHcwxFNXh24TE5g2CTQA)

**Comment by fatcerberus** [comment]
> Actual behavior: No error

Your playground example does have an error.

**Comment by Josh-Cena** [comment]
> Your playground example does have an error.

No errors for me, though. And the signature of `then` is `(destination: () => any): any`, which is a valid thenable, so it would be hard to say why there _should_ be an error.

**Comment by Mirokko** [comment]
okay. if support for custom thenable entities (not promises) is something expected, you can safely close this issue (and it would be nice to mention it somewhere in docs so people are aware of this). I really did not expected await to call my `then` function in my class and it was a good amount of time to figure out what is really going on.

**Comment by Josh-Cena** [comment]
This is a JS feature, not a TS one. `await` resolves all thenable chains, and TS has to respect that behavior.
