### ISSUE TITLE
wrong or missing namespace declaration when generating the `d.ts` file out of Javascript source

### ISSUE THREAD

**Issue by obiot** [microsoft/TypeScript#49795]
# Bug Report

### 🔎 Search Terms

missing namespace export declaration when generating d.ts file from Javascript source

### 🕗 Version & Regression Information

currently on version 4.7.4, but it has been there since we started using Typescript 6 months ago to generate the `d.ts` file.
we initially assumed this was due to the previous es5 syntax being used, but after converting to a proper es6 syntax the issue is still there

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about missing namespace export declaration when generating d.ts file from Javascript source file

### ⏯ Playground Link

there is no playground this is a compilation (d.ts generation) issue when using:
[`tsc dist/melonjs.module.js --declaration --allowJs --emitDeclarationOnly`](https://github.com/melonjs/melonJS/blob/3c433f4e9a99ba053173a7bb94ace58b12acffd3/package.json#L98)

### 💻 Code

Javascript source declaration of the `device` namespace:  
https://github.com/melonjs/melonJS/blob/master/src/system/device.js

### 🙁 Actual behavior

generating :
```
export var device: any;
```

see corresponding generated typescript declaration here : https://github.com/melonjs/melonJS/blob/3c433f4e9a99ba053173a7bb94ace58b12acffd3/dist/melonjs.module.d.ts#L9743

### 🙂 Expected behavior

```
export namespace device {
    const myProperty: number;
    myFunction(...);
    ...
}
```

**Comment by sandersn** [comment]
Can you give more detail, and perhaps a smaller example, for what you want to happen? I looked at device.js but melonjs.module.d.ts is too large for github to display.

Inferring from device.js and what you've said, it sounds like you want to write a .js file and then generate a .d.ts that matches it. However, it seems like you want to it to match not the source .js but some bundled version, based on your tsc version and the link to melonjs.module.d.ts. This
Instead you need to generate a .d.ts file for each .js file and then bundle those. I'm not sure, but I think you need API Extractor for that.
