### ISSUE TITLE
Optimize rest arguments.

### ISSUE THREAD

**Issue by mbebenita** [microsoft/TypeScript#498]
The TypeScript compiler generates the following code for rest arguments:

```
function foo(x, y, z, ...rest) {
  return;
}

function foo(x, y, z) {
  var rest = [];
  for (var i = 0; i < arguments.length - 3; i++) {
    rest[i] = arguments[i + 3];
  }
  return;
}
```

Although `rest` is unused in the body of the function, JS engines can't easily dead code eliminate the allocation of the `rest` array and the subsequent for loop due to the possibility of Array.prototype being mutated:

```
Object.defineProperty(Array.prototype, 42, { set: function() { alert(this[41]); }});
```

It's much easier for the TypeScript compiler to avoid emitting this code when it is not necessary.

See more details:

https://bugzilla.mozilla.org/show_bug.cgi?id=1056446

**Comment by begincalendar** [comment]
As asked by @andy-ms ([here](https://github.com/Microsoft/TypeScript/pull/19330#issuecomment-351089321)), what are the use-cases for having unused rest parameters?

**Comment by RyanCavanaugh** [comment]
This doesn't really seem needed - the overload trick is sufficient, and most people are not downleveling rest args anymore.
