### ISSUE TITLE
Code completion should suggest the enum name when typing the name of an enum member

### ISSUE THREAD

**Issue by boriskrisanov** [microsoft/TypeScript#49800]
# Suggestion

## 🔍 Search Terms

code completion, enum

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Code completion should suggest the enum name when typing the name of an enum member.

## 📃 Motivating Example

In the code below, code completion should suggest Test.TEST_1 when TEST_1 is typed.
```typescript
enum Test {
	TEST_1
}

TEST_1
```
## 💻 Use Cases
It makes it easier to use enums because the name of the enum can be autocompleted if you type the name of a member of that enum.

**Comment by RyanCavanaugh** [comment]
This hasn't seen any other feedback and would substantially pollute the global completion list.
