### ISSUE TITLE
Implement mapped type

### ISSUE THREAD

**Issue by sant123** [microsoft/TypeScript#49811]
# Suggestion

## 🔍 Search Terms

+ implement mapped type
+ class implements mapped type
+ interface extends mapped type
+ autocomplete for mapped type in class
+ intellisense for mapped type in class

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to implement a mapped type from a class and let Typescript/VS Code implement the methods I just created using template literal types.

``` typescript
export const methods = [
  "GET",
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
  "OPTIONS",
  "HEAD",
] as const;

export type Method = typeof methods[number];

type MethodMapper = {
  [P in Method as ${Lowercase<string & P>}]: () => void;
};

class Router implements MethodMapper {
}
```

![image](https://user-images.githubusercontent.com/7959437/177584751-be07ad89-9622-47e7-b896-c5ad8f587f79.png)

Currently the Typescript Playground and Visual Studio Code doesn't implement my new type:

![image](https://user-images.githubusercontent.com/7959437/177584914-5ecadb3f-d976-4fb3-b435-6cc8fac8488e.png)

## 📃 Motivating Example

Implement a mapped type into a class using template literal types.

## 💻 Use Cases

Currently I'm working in a new routing library and want to type check new methods added in `methods` array. For now the workaround is implement the methods by hand in my class.

Thank you in advance.

**Comment by babakks** [comment]
@RyanCavanaugh I traced the problem (i.e., why `Implement inteface` code fix does not show up) and this is the result.

## Problem

When there's no explicit `keyof T` in the mapped type definition, there'll be no declarations available for the corresponding symbols (i.e., `symbol.getDeclarations()` returns `undefined`), hence, no "Implement interface" code fix appears.

Take this simplified case as an example:

```ts
type Base = { ax: number; ay: string };
type BaseKeys = keyof Base;
type MappedDirect = { [K in keyof Base]: boolean }; // Has explicit keyof T
type MappedIndirect = { [K in BaseKeys]: boolean }; // Implicit keyof T via BaseKeys
class MappedImpl implements MappedDirect, MappedIndirect { }
```

Here in `MappedDirect` definition there's a `keyof Base` whereas in the `MappedIndirect` the keys are read indirectly from the `BaseKeys` intermediate type. If you open this code segment in VS Code, then you'll see the "Implement interface" code fix is just available for the `MappedDirect`:

![Screenshot from 2022-07-21 23-19-35](https://user-images.githubusercontent.com/36728931/180293752-9bdc1dc4-9608-4d3d-9a3b-daaba98873b7.png)

From the parser/type-checker point of view, the difference lies at `checker.ts:11717` where `modifiersType` is set to `undefined` for the `MappedIndirect` type:

```ts
//checker.ts:11714
const modifiersType = getApparentType(getModifiersTypeFromMappedType(type)); // The 'T' in 'keyof T'
```

This results in `modifiersProp` set to `undefined`:

```ts
//checker.ts:11745
const modifiersProp = isTypeUsableAsPropertyName(keyType) ? getPropertyOfType(modifiersType, getPropertyNameFromType(keyType)) : undefined;
```

And with `modifiersProp` being `undefined`, the `declarations` property is not assigned:

```ts
//checker.ts:11757
if (modifiersProp) {
    prop.syntheticOrigin = modifiersProp;
    // If the mapped type has an `as XXX` clause, the property name likely won't match the declaration name and
    // multiple properties may map to the same name. Thus, we attach no declarations to the symbol.
    prop.declarations = nameType ? undefined : modifiersProp.declarations;
} 
```

## Solutions

I can think of two solutions:

- Update the type checker and see if the `ConstraintType` (i.e., `X` in `K in X`) is itself defined as `keyof T` then assign `modifiersType` with `T`. However, this might work for only one level of indirection and will probably fail (i.e., keep the existing behavior) in cases like this (although I didn't really check that):

  ```ts
  type Base = { ax: number; ay: string };
  type BaseKeys = keyof Base;
  type BaseKeysIndirect = BaseKeys;
  type MappedIndirect = { [K in BaseKeysIndirect]: boolean };
  class MappedImpl implements MappedIndirect { }
  ```

- Do not modify the checker, and fix this case at the language services level. That is, when there's no declaration available for a symbol, just assume it as a simple property. This needs modification of `addNewNodeForMemberSymbol` function defined in `src/services/codefixes/helpers.ts`. I've already pushed an implementation of this solution to be used if maintainers deemed fit.

@RyanCavanaugh What's your opinion?

**Comment by RyanCavanaugh** [comment]
You generally don't want to touch the checker to fix a LS issue unless it's returning something manifestly wrong, which in this case it's not. I think the fix in the PR is likely the appropriate path.
