### ISSUE TITLE
Overload is not recognized correctly in some cases

### ISSUE THREAD

**Issue by mochiya98** [microsoft/TypeScript#49820]
# Bug Report

### 🔎 Search Terms

generics overload

### 🕗 Version & Regression Information

- 4.7.4(current), 4.8.0-beta(beta)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAggjAHgCoD4oF4oG8qkgLigCIBDOIgGigDdCkoBfAbgCg9oAhRVDbXcCISIAjclVpR6zNgNgAmXjhJzCAZ2AAnAJYA7AOaNW7KBwWYcwlVHXb9hliwBmAVx0BjYFoD2OqI53IKAAUYHCEIaGEAAwAlBho8IFUYFYRVjBycehosYTUXloAJqwu7p4+fgGoIWFQEbWx8SbcKMmpYCmEplk5MXkFxU6uHt6+-oFBLFBQkVPTUAA+dfXRPbAtMXPTS0ErUI3ZzYExFHOdW4vLHemZTbEXO2ldt4f3cVgMDm4+6jQkADbwQiJGy6PRoTBBHDsIRkSg0IRERgxVjfHS-agArhdRCg-QQurQgRCUTwiREJEMFEOAD0NKgEAAHpAPLAnDpdiRQmtMYC4FQglyXr0ShzBdymrz4AKhcDhfsUVB2ZyJYcpfy6rKoCQdCA1rFRSq4DyAdLNZ0oK4ANY6LwAdx0+up-iNq0lpo14vlBpYdIZzIgrI4yqCwlVaF5XAFYe9ir9wmcwCgWiTdq0-3+UGE0BgVB8-xAuAAFlpVFA0xmoBoIKpnP8k7ptb4IBoNF4NCGw8b3f8o3UY88nUwlS7Q+G-r3PQOm3q7s6xV2TZPoxbrbaHUPO5EFT2+2PY6wgA)

### 💻 Code

```ts
type A1<T> = { type: "a1", v: T };
type B1<T> = { type: "b1", v: T };
type A2 = { a2: string };
type B2 = { b2: string };

function fn<T>(p1: (pp1: 0) => A1<T>, p2: (pp2: A2) => 0): void;
function fn<T>(p1: (pp1: 0) => B1<T>, p2: (pp2: B2) => 0): void;
function fn<T>(
  p1:
    | ((pp1: 0) => A1<T>)
    | ((pp1: 0) => B1<T>),
  p2:
    | ((pp2: A2) => 0)
    | ((pp2: B2) => 0)
) {}

const valA1: A1<string> = ({ type: "a1", v: "" });
const valB1: B1<string> = ({ type: "b1", v: "" });

// expect A
fn((ap1) => valA1, (ap2) => 0);
fn((ap1) => valA1, (ap2: A2) => 0); 
fn((ap1) => valA1, (ap2: any) => 0);
fn((ap1) => valA1, (ap2: unknown) => 0);
fn((ap1: 0) => valA1, (ap2) => 0);
// expect B
fn((bp1) => valB1, (bp2) => 0); // but it will be A, only this will result in an error
fn((bp1) => valB1, (bp2: B2) => 0); 
fn((bp1) => valB1, (bp2: any) => 0);
fn((bp1) => valB1, (bp2: unknown) => 0);
fn((bp1: 0) => valB1, (bp2) => 0);
```

### 🙁 Actual behavior

```
No overload matches this call.
  Overload 1 of 2, '(p1: (pp1: 0) => A1<string>, p2: (pp2: A2) => 0): void', gave the following error.
    Type 'B1<string>' is not assignable to type 'A1<string>'.
      Types of property 'type' are incompatible.
        Type '"b1"' is not assignable to type '"a1"'.
  Overload 2 of 2, '(p1: (pp1: 0) => B1<string>, p2: (pp2: B2) => 0): void', gave the following error.
    Argument of type '(bp2: A2) => 0' is not assignable to parameter of type '(pp2: B2) => 0'.
      Types of parameters 'bp2' and 'pp2' are incompatible.
        Property 'a2' is missing in type 'B2' but required in type 'A2'.(2769)
```

### 🙂 Expected behavior

No errors

**Comment by RyanCavanaugh** [comment]
See #30134 - inference only does a fixed number of passes, which isn't an algorithm capable of resolving this.

**Comment by PabloLION** [comment]
Here's a shorter MRE to address the problem:

```ts
type Fruit = "apple" | "banana";

function printFruit(fruit: "apple");
function printFruit(fruit: "banana");
function printFruit(fruit: Fruit) {
  console.log(fruit);
}

function callPrintFruit(fruit: Fruit) {
  printFruit(fruit); // Error here: No overload matches this call.
}
```

Playground: https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAYgTgVwJbCgXigIgIZjAGwkygB8sAjbAO2u0wG4AoRgMwSoGNgkB7KqMHCRVg8ZMAAULRCgBcWXASIBKJm07c+AoSLEopM4PMyUaNTKtbsuvfoOGjDB8fL3BlUAN6MoUDnwBnHkIAOnweAHNnFEsAX2Z1Gy0ObHx8AAUdR3Foo1hDD29fe10naXFVKAB6KqgAUTg4HjgoAAsIOAh5ADkeKB4ANw7w7AATKABbbGAOdoCoYFakeZS0kMZ4oA

**Comment by Septh** [comment]
I was about to file a similar issue but found this one. To build on @PabloLION's [comment](https://github.com/microsoft/TypeScript/issues/49820#issuecomment-1263167686), the following variation compiles OK ([playground](https://www.typescriptlang.org/play?ts=5.3.2#code/C4TwDgpgBAYgTgVwJbCgXigIgIZjAGwkygB8sAjbAO2u0wG4AoRgEwgGN9s5oAzBKu2BIA9lShg4SKsHjJgACl6IUALiy4CRAJTqAbiKQsmbTtz4Cho8ZOmyVi5fPWZKNGpl1QDRkxy48UPyCwmISUjJyKEoO6lHAXj7GzMFWYezY+PgAChH28jHOsA7aUADejFDhdvGFKNr0UAD0TVAAciJQEHBwInBQABbdEACEjAC+jEA)), which seems strange to me because the error is on the function _call_, not the function's body:

```typescript
type Fruit = "apple" | "banana";

declare function printFruit(fruit: "apple"): void;
declare function printFruit(fruit: "banana"): void;
declare function printFruit(fruit: Fruit): void;

function callPrintFruit(fruit: Fruit) {
  printFruit(fruit); // No error here!
}

```
