### ISSUE TITLE
Typescript doesn't see types from d.ts file inside dependent js file.

### ISSUE THREAD

**Issue by Vanesstalkers** [microsoft/TypeScript#49829]
# Bug Report

### 🔎 Search Terms
d.ts

### 🕗 Version & Regression Information
This is the behavior in version 4.7.4

### 💻 Code
```js
# myClass.js
export class myClass {
    sum (a, b) {
        return a + b;
    }
    printSum () {
        return this.sum('111', 222);
    }
}

# myClass.d.ts
export class myClass {
    sum(a: number, b: number): number;
    printSum(): number;
}

# tsconfig.json
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "noEmit": true
  }
}
```

### 🙁 Actual behavior

Typescript compiler does not find an error if a class method with incorrect variable types is called inside the module in which the class is declared.

### 🙂 Expected behavior

Typescript compiler learned to detect the error only after imports were added for class methods in the dependent js file (see code below).
```js
# myClass.js
/**
 * @type {import('./test').myClass}
 */
export class myClass {
    /** @type {import('./test').sum} */ 
    sum (a, b) {
        return a + b;
    }
    /** @type {import('./test').printSum} */ 
    printSum () {
        return this.sum('111', 222);
    }
}

# myClass.d.ts
export type sum = (a: number, b: number) => number;
export type printSum = () => number;
export class myClass {
    sum: sum;
    printSum: printSum;
}
```

**Comment by RyanCavanaugh** [comment]
Adding a `.d.ts` file isn't a method for ensuring that a JS file conforms to some interface. See #29056
