### ISSUE TITLE
Incorrect parsing JSDocSeeTag with url string only

### ISSUE THREAD

**Issue by rwnkl** [microsoft/TypeScript#49826]
# Bug Report

### 🔎 Search Terms

ts.JSDocSeeTag

### 🕗 Version & Regression Information

Typescript 4.7.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJLIN4FgBQuCQ+A9AFQkH7InICCyAzsAA4A2KTUA9k9GAJ4NgAcxBwwAVygQKVGSQAC9CCgAWYME3oAuIkTgAjBADoAHnwBecohQ7ctyOCD4BuXBVwBfXEA

### 💻 Code

interface I {
		/**
		 * A siple property signature
		 *
		 *@see https://abc.xyz
		 */
		prop: any;
}

### 🙁 Actual behavior

tag.name = https 
tag.comment = ://abc.xyz

### 🙂 Expected behavior

tag.name = undefined 
tag.comment = https://abc.xyz

**Comment by sandersn** [comment]
The syntax of `@see` is

`@see` [ `{` ] *QualifiedName* [ `}` ] *Comments*

Given that many people put urls after `@see`, the language service displays unresolved identifiers named 'https' like a url. Other consumers of the compiler API can do the same if they want, or do even more post-processing, eg supporting markdown

**Comment by gordonmleigh** [comment]
@sandersn I think you're wrong though? [TSDoc](https://tsdoc.org/pages/tags/see/) and [JSDoc](https://jsdoc.app/tags-see.html) both say `@see` should support links, possibly via the `@link` tag.

**Comment by sandersn** [comment]
This syntax works in Typescript, and matches the documentation of JSDoc and TSDoc: `/** @see {@link https://abc.xyz} */`
