### ISSUE TITLE
instanceOf does not work when one class implements another.

### ISSUE THREAD

**Issue by jonataslaw** [microsoft/TypeScript#49823]
When a class extends another, instanceof works, but not when a class implements an interface or abstract class, you cannot use it.

It would be nice to have an operator of its own that allows this (like "is" from C#, Dart, etc), or that instanceof allows this (like java)

### 💻 Code

```ts
// check if TypeScript abstract classes
// are checkable using "instanceof"

abstract class Animal {
  abstract sound(): string;
}

class Cat extends Animal {
  sound() {
    return "Meow";
  }
}

class Dog implements Animal {
  sound() {
    return "Woof";
  }
}

const dog = new Dog();
const cat = new Cat();

console.log(cat instanceof Animal); // true
console.log(dog instanceof Animal); // false
```

**Comment by MartinJohns** [comment]
`implements` does not mean your class extends the other. It means the class implements all public members of the other class. But the `instanceof` operator in JavaScript checks the prototype chain of your object, and because your `Dog` class does **not** extend `Animal` it returns `false`.

This behaviour is correct.

**Comment by jonataslaw** [comment]
You are right on this point.
I'll actually go into more detail about this, which might fall under a feature request.
Currently, instanceof works for class extension, however it doesn't work for interfaces.

In languages like Java, this is possible:


```java
public class MyClass {
    public static void main(String args[]) {
     Dog dog = new Dog();
     boolean isAnimal = dog instanceof Animal;
     System.out.println(isAnimal); // TRUE
    }
    
}

 public interface Animal {
    public void eat();
 }

 public class Dog implements Animal {
    public void eat() {}
 }

```


In languages like Dart and C#, the "is" operator is used to check when a object implements another

```dart
void main() {
  final dog = Dog();
  print(dog is Animal); // true
}

abstract class Animal {
  void eat();
}

class Dog implements Animal {
  void eat() {}
}
```

If this is not a javascript limitation, it would be preferable to have an operator (or even instanceof, as in java) to check if an object implements another.

Currently, the only way to check this is by checking the object's properties, something like:

```typescript
function instanceOfAnimal(object: any): object is Animal {
    return object?. sound != null;
}
```

However this seems like a workaround, and it seems impossible to check in classes with 80 elements, so maybe it would be preferable to have a solution at the typescript level

**Comment by MartinJohns** [comment]
That's out of scope for TypeScript. See the language design goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
