### ISSUE TITLE
Typescript incorrect types

### ISSUE THREAD

**Issue by MikeJerred** [microsoft/TypeScript#49825]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open VSCode and create a new text file (Ctrl+N)
2. Set the language to Typescript
3. Paste this code into it:

```typescript
export interface Foo {
  objs: { id(): string; }[];
}

export class Test {
  private foo: Foo | null = null;

  doSomething(ids: Record<string, boolean>) {
    if (!this.foo) return;
  
    for (let i = 0; i < this.foo.objs.length; i++) {
      const obj = this.foo.objs[i];
      const objId = obj.id();

      if (!ids[objId]) return;
    }
  }
}
```

4. The type of `obj` on line 12 is incorrectly identified as `any` rather than `{ id(): string; }`. This can cause errors in a project with `noImplicitAny` set to `true`
5. The Typescript compiler compiles the code without issue, so I believe this is a bug only with the intellisense.

**Comment by MikeJerred** [comment]
@RyanCavanaugh how so? `obj` is defined simply by:

```typescript
const obj = this.foo.objs[i];
```
It's type is determined from the type of the interface `Foo` which contains no circularity. Also I do not see any error message about a circularity, the problem is that the type of `obj` is determined to be `any`.

Although it doesn't look like it, the code is actually a minimal reproducible example. Removing for example line 15 (`if (!ids[objId]) return;`) which does nothing whatsoever causes the type of `obj` to be correctly identified.

**Comment by fatcerberus** [comment]
> Also I do not see any error message about a circularity,

```
'obj' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)
```

[Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQgjgG8AoOOCAIwCsBnALlMQBMAKASmfpimQDmAbjgBfANoBdIWVFkyoSLDjYANpnr04AFWC9SFOGH4A3TKjjoizQsQA+cJAFdVquAF5HL1TMOsIAMoQALbAMAAWguwIrExwAErA2NCsADy8-EgCADRw1ESqwJhIAHycBpSUCOhw7ACEEQj0AHRWEOVQYU5QSDKUhpRWULWF8AgecAAMIuOpcI0tbc00DM2FWREzANRb5eSVlclI+isTC61Ey3T04gjSA4cQx-ArAJKsEyvNMVy+B1U1eoxG5vViSDpdHp9SpyShyORAA)

**Comment by fatcerberus** [comment]
> That depends on whether this.foo is initialized or not. Is it?

seems like this is where it goes wrong, since `this.foo` is checked for truthiness before the loop and is not reassigned at any point afterwards.  It’s just that TS never gets to the point of realizing it’s not reassigned since it tries to find out if the loop is reentrant first, leading to the circularity.  Feels like a design limitation, since it’s not obvious where the circularity is without knowing what the compiler is doing under the hood first.

**Comment by MikeJerred** [comment]
Perhaps upon failing to determine if the rest of the loop body needs checking, the analyser should proceed to check the rest of the loop body?

**Comment by RyanCavanaugh** [comment]
It certainly *can* be improved, it's just a circularity per the rules that are currently in place. We can't eliminate 100% of surprising circularities so I generally don't triage these as bugs per se.

**Comment by MikeJerred** [comment]
I'm not entirely convinced by the analysis above actually.

Doing this: [playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQgjgG8AoOOCAIwCsBnALlMQBMAKASmfpimQDmAbjgBfANoBdIWVFkyoSLDjYANpnr04AFWC9SFOGH4A3TKjjoizQsQA+cJAFdVquAF5HL1TMOsIAMoQALbAMAAWguwIrExwAErA2NCsADy8-EgCADRw1ESqwJhIAHycBpSUCOhw7ACEEQj0AHRWEOVQYU5QSDKUhpRWULWF8AgecAAMIuOpcI0tbc00DM2FWREzANRb5eSVlclI+isTC61Ey3T04gjSA4cQx-ArAJKsEyvNMVy+B1U1eoxG5vViScpHegQQprCACdgAcmo6nCCM4fUqckocjkQA) i.e. replacing `if (!ids[objId]) continue;` with `if (!ids[objId]) console.log('blah');` still has the same error.

Also this code works correctly:

```typescript
function blah(fooArg: Foo | null, ids: Record<string, boolean>) {
  let foo = fooArg;

  if (!foo) return;
  
  for (let i = 0; i < foo.objs.length; i++) {
    const obj = foo.objs[i];
    const objId = obj.id();

    if (!ids[objId]) continue;
  }
}
```
So somehow in this situation it has figured out that `foo` is never set back to `null`.

**Comment by fatcerberus** [comment]
This is just an educated guess, but I'm assuming that obtaining `objId` from a function call short-circuits the check here:

> That depends on whether `objId` is a statically-knowable index. Is it?  [No, because it came from a function call.]
