### ISSUE TITLE
Generic function with two or more types cannot infer type provided as function parameter

### ISSUE THREAD

**Issue by HaukeSchnau** [microsoft/TypeScript#49849]
# Bug Report

### 🔎 Search Terms
- infer generic type
- multiple type parameters

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJiAyiAtgUygCwJZgOYwC8MAPAEIA0AfABQCGATnmQFwxkCURVMA3gL4BuAFAJk6LLjw0ARADMQIGR0EwA9GpgB1EAwDWEGHUNoAHgAc0wKGjjDhoSLDGoMOfAFEANhDRFSAIIU7LSMzGyc3HxCokiukp4+aCQyAEaMMrTyisqqGjAeDAy6bB4WVjZwMABMMFAAnpZGTACu6GBQEMGpLbB4ILAAjEA)

### 💻 Code

```ts
const doSomething = <B,>(argB: B) => {};
doSomething("foo"); // Works as expected

const doSomethingElse = <A, B>(argB: B) => {};
doSomethingElse<"bar">("foo"); // Error: Expected 2 type arguments, but got 1
```

### 🙁 Actual behavior
TypeScript throws an error in the second example despite being able to infer the type in the first one

### 🙂 Expected behavior
No error, TypeScript infers the second type as "foo", since it is provided as an parameter

**Comment by MartinJohns** [comment]
This is working as intended / a design limitation. Type argument inference is all or nothing. You want #26349.

**Comment by HaukeSchnau** [comment]
Alright, thanks for the heads up :)
Will follow the issue and PR
