### ISSUE TITLE
How to distinguish a method property from a bound callback property?

### ISSUE THREAD

**Issue by dko-slapdash** [microsoft/TypeScript#49847]
# Suggestion

I expected `ThisParameterType` helper to be able to distinguish between methods (unbound function properties) and callbacks (bound functions), but it doesn't want to do it:

```ts
class Cls {
  method() {}
  callback = () => {}
}

type aaa = ThisParameterType<Cls["callback"]>;
// Aaa = unknown

type Bbb = ThisParameterType<Cls["method"]>;
// Bbb = unknown -- WHY? How to distinguish?
```

[Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDCIwN4ChrQLYFMAuALA9gCYAUAlNIgL6rTBgggBGYwA1tALzRmcB8F1asmwBPAA6ZoYaZ2gAVXAEsIABTAAnMFmyZ1c8ZgA88CAG0ARHQbM25gLq8A3MgD0L6AEEZXAK4A7Vj98AHc-ZHDhA2gAIUZGWQVlNU1tXX0JYwQLbQJCeydXd1j43wCg0OgAWkroAHUACQBNAH5oepDobHxoQmVsRT8Acx9lXGaIoA)

<img width="621" alt="Screen Shot 2022-07-10 at 1 22 10 AM" src="https://user-images.githubusercontent.com/46383452/178137366-55e4137c-6d0c-4e94-bafd-50267dc2bfaa.png">

## 🔍 Search Terms

method property from a bound callback property this

## 💻 Use Cases

I want to enumerate all plain properties of some type (e.g. a class instance), but skip methods. Currently I do it with:

```
export type NonMethodPropertyNames<T> = {
  [K in keyof T]: T[K] extends Function ? never : K;
}[keyof T];

export type NonMethodProperties<T> = Pick<T, NonMethodPropertyNames<T>>;
```

but unfortunately, this `NonMethodProperties` also skips callback properties. E.g. in this example:

```
class Cls {
  constructor(public a = 10, public callback: () => void) {}
  method() {}
}
```

...I would expect `NonMethodProperties<Cls>` to return `{ a: number; callback: () => void }`, but unfortunately it skips not only `method`, but also `callback` since I couldn't find a way to distinguish them.

**Comment by MartinJohns** [comment]
The method in your class don't have a `this` argument, so `ThisParameterType<>` does not work on them. There's the open issue #28548 to automatically add a `this` argument to class methods.
