### ISSUE TITLE
tsconfig noEmit error: Cannot reference tsconfig if it extends other tsconfig.

### ISSUE THREAD

**Issue by ZerdoX-x** [microsoft/TypeScript#49844]
# Bug Report

### 🔎 Search Terms

 - tsconfig.json
 - noEmit
 - extends
 - reference
 - Referenced project may not disable emit.

### 🕗 Version & Regression Information

Tried `4.8.0-beta`, `4.7.3`, `4.7.4`, and `4.6.3`

### 💻 Code

Couldn't reproduce this in Bug Workbench, but here is my minimal reproduction repo:
https://github.com/ZerdoX-x-issue-reproducer/microsoft-TypeScript-49844

tsconfig.json:
```jsonc
{
  "references": [{ "path": "./tsconfig.test.json" }],
  "compilerOptions": {
    "noEmit": true
  }
}
```
tsconfig.test.json:
```jsonc
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "composite": true,
    "noEmit": true
  }
}
```
tsconfig.base.json:
```jsonc
{
  "include": [
    "src/**/*.d.ts",
    "src/**/*.js",
    "src/**/*.ts",
  ],
  "compilerOptions": {
    "noEmit": true,
  }
}
```

### 🙁 Actual behavior

<img width="959" alt="image" src="https://user-images.githubusercontent.com/49815452/178122283-77e20cb4-6fa8-49ac-8739-9852907830f9.png">

### 🙂 Expected behavior

<img width="657" alt="image" src="https://user-images.githubusercontent.com/49815452/178122318-1205ac38-d28d-437f-bdf0-70f26e82e6e4.png">

### 🤔 Other info

[SO question](https://stackoverflow.com/questions/71704754/typescript-yarn-workspaces-referenced-project-may-not-disable-emit)

**Comment by Markkos89** [comment]
facing the same issue and is driving me crazy :(

**Comment by ZerdoX-x** [comment]
> facing the same issue and is driving me crazy :(

For me it doesn't affect anything. Just a visual error in vscode, so it's fair enough to place a comment with linking this issue above `"references":` (glad typescript.json is JSONC) and ignore it without remorse.

**Comment by Josh-Cena** [comment]
Question: is there an easy way to type-check with a single `tsc` run, without emit, and with different sets of files using different libs? Or do we have to use multiple `tsc` runs?

**Comment by RyanCavanaugh** [comment]
> Question: is there an easy way to type-check with a single tsc run, without emit, and with different sets of files using different libs

No

**Comment by RyanCavanaugh** [comment]
That doesn't really answer my question, I guess.

Referencing a project does the following:
 * Changes imports of `.ts` files to their corresponding `.d.ts` files (under `noEmit`, those .d.ts files don't exist)
 * Causes `tsc -b` to rebuild the upstream project if it's out of date (if it doesn't emit, this question doesn't make any sense)
 * Adds any declaration `outFile` to the current project (under `noEmit`, those .d.ts files don't exist)

**Comment by ZerdoX-x** [comment]
If I don't reference `tsconfig.test.json` in `tsconfig.json` I will end up with errors like this while trying to import from `$lib` (alias is set in `tsconfig.base.json` which is inherited in `tsconfig.test.json`) in files which are excluded in `tsconfig.json`
<img width="934" alt="image" src="https://user-images.githubusercontent.com/49815452/178342534-c73ad333-5894-4888-a284-b7bb329198cf.png">

And also I noticed that vscode says I don't have tsconfig loaded for this file (and that's the reason why aliases doesn't work). Is this an issue with vscode?
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/49815452/178344037-a56c481a-caa2-490a-8273-a41aac23b352.png">

But when I do reference, vscode shows loaded `tsconfig.test.json` as expected for this file.

**Comment by tylim88** [comment]
add
```
"include": [],
"files":[]
```
in base config get rid of the error message

**Comment by ITenthusiasm** [comment]
> What are you trying to achieve?

@RyanCavanaugh, based on @ZerdoX-x's other comments, I'm assuming that the goal is to have type checking for test files _without_ including them in the project's output. At least, that's what I need, and that's how I stumbled upon this issue.

TypeScript's [Project Reference Documentation](https://www.typescriptlang.org/docs/handbook/project-references.html) suggested to me that Project References were the way to handle monorepos in NPM, keep TS working with tests, and keep the test files _out_ of the build directory simultaneously. (Developers shouldn't need to include a `rm -rf` command in their build step. The compiler should simply exclude all undesired files from the build output.) I haven't found any clear documentation on how to handle this use case.

If you aren't going to reopen the issue, would you be willing to give a reasonable alternative? Maybe there's something we're missing?

**Comment by ITenthusiasm** [comment]
What also might be coming out is a desire for simplicity. To expound a little more, many people want the ability to say, "Type Check my entire monorepo" in one command. But that gets difficult when there are files intended to be included in the output (regular files from several scoped packages) and files not intended to be in the output (such as test files and configuration files).

Maybe clarity on what the recommendation is for monorepos would also be helpful? My goal is to avoid getting caught up in the chaos of `turborepo`, `yarn workspaces`, etc. I just want to work with simple NPM and TS for my monorepo.

**Comment by audunolsen** [comment]
In my head the ideal solution is just having an option to make `tsc` just hold the necessary reference declaration output in memory or in an internally handled temporary scratch/cache dir for the entirety of the command's run without any reading or writing to the file system of the monorepo. An ever increasing size of devs are only using ts for intellisense in their IDE and as a CI test step or commit hook, no compiling. Can't really find any solution to this myself 👀

**Comment by karlhorky** [comment]
Solution for us was to configure a base `tsconfig.json` with:

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "files": [],
  "references": [
    { "path": "./tsconfig.root.json" },
    { "path": "./scripts/tsconfig.json" }
  ]
}
```

Then the error message `Referenced project may not disable emit` goes away.

Check out some examples:

- @RyanCavanaugh 's example demo repo for TypeScript Project References: https://github.com/RyanCavanaugh/project-references-demo
- Our example with [the `@typescript-eslint/*` packages](https://typescript-eslint.io/) https://github.com/typescript-eslint/typescript-eslint/issues/2094#issuecomment-1820936720

**Comment by atollk** [comment]
Came here through Google, none of the suggested solutions so far helped me out. For me, I had to add `"compilerOptions": { "declaration": true }`.

**Comment by codethief** [comment]
@tylim88 @karlhorky Unfortunately, your solution seems to fall flat in a "triangular dependencies" situation, i.e. when my main `tsconfig.json` references two projects A and B, and B also references A. See https://github.com/codethief/tsconfig-test/tree/master/2024-07-triangular-project-references for example code.

**Comment by codethief** [comment]
@atollk `"declaration": true` is already the default for [composite](https://www.typescriptlang.org/tsconfig/#composite) projects, compare https://www.typescriptlang.org/tsconfig/#declaration

**Comment by hyunbinseo** [comment]
@ZerdoX-x Have you found a solution for SvelteKit projects?

> I don't suffer from this issue anymore, but reproduction will be opened as long as my account exists :) Afair I was using SvelteKit and I just wanted to get proper type checking for all of my files

I am attempting to differentiate tsconfig(s) for universal and server modules, but cannot enable `noEmit`.

- https://github.com/sveltejs/kit/issues/12537
