### ISSUE TITLE
`Record<symbol, any>` assignable to `Record<string, any>`

### ISSUE THREAD

**Issue by MathisBullinger** [microsoft/TypeScript#49841]
# Bug Report

Assigning an object of type `Record<string, any>` to an object of type `Record<symbol, any>` and vice-versa does not result in an error. 
This is also the case when the values are of different types, e.g. assigning `Record<string, number>` to `Record<symbol, string>` is not an error. Note: this is an error as expected when the keys are of type `string` and `number` respectively.

### 🔎 Search Terms

- symbol keys
- symbol record
- symbol key coercion
- object keys symbol string

### 🕗 Version & Regression Information

Same behavor in `4.7.4` and `4.8.0-beta`. All earlier versions I tried show the same behavior.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/N4KABBYMYPYHYGcAuYBmMYC4wCUCmsATgCYA8yhAlnAOYA0YAhnAJ4B8YAvGMAL7iRYiFACNGhbPiJkELALYiYAGwbN2XNBhD8QoSNHjJNWXARglySKrQZwArgryEO3PgIgB6D2ADuMO0rEYHgAHgAOBCjMwYSE5u4GwmBiEqbS5PKKKmAU1DQuxgleYHAwSHjYSAAWlAhgtUxwMXGETHWhEVDlxJgJQkZiAF6SZha5NjlWeQXoMNpAA)

### 💻 Code

```ts
const foo: Record<string, any> = {}
// not an error
const bar: Record<symbol, any> = foo
```

```ts
const foo: Record<string, number> = {}
// also not an error:
const bar: Record<symbol, string> = foo
// but this is an error as expected:
const baz: Record<number, string> = foo
```

### 🙁 Actual behavior

`Record<string, any>` can be assigned to `Record<symbol, any>` without an error.
While this behavior makes sense for string and number keys because Javascript will coerce numbers used as keys to strings, symbols are valid keys and will stay a different type than strings when used as such.

### 🙂 Expected behavior

I would expect an object with keys of type `string` not to be assignable to an object with keys of type `symbol`.

**Comment by MartinJohns** [comment]
> I would expect an object with keys of type `string` not to be assignable to an object with keys of type `symbol`.

Why do you expect this? There is no overlap between an object with `symbol` keys and an object with `string` keys, so there's nothing making them structurally incompatible.

**Comment by fatcerberus** [comment]
`Record<string, any>` doesn’t mean “an object which only has a string keys”.  It means “an object for which all string-keyed properties are typed as `any`”  Since there are *no* string keys in `Record<symbol, any>`, it satisfies that condition, and it is therefore assignable.

**Comment by MathisBullinger** [comment]
@MartinJohns Yes, I guess you have a point that since there is no overlap between `string` and `symbol`—in a structural type system—these objects aren't incompatible.

Though TypeScript has extra checks when assigning weak types. E.g.
```ts
const a: { foo?: string } = {};
const b: { bar?: string } = a;
```
will result in an error `Type '{ foo?: string | undefined; }' has no properties in common with type '{ bar?: string | undefined; }'.`.

Shouldn't `Record<string, any>` and `Record<symbol, any>` be considered weak types, only that their optional properties are the sets of all strings and symbols respectively, and therefore impose the same checks?

**Comment by Josh-Cena** [comment]
TS has different handling for mapped types. You can see my exploration in https://github.com/microsoft/TypeScript/issues/48906
