### ISSUE TITLE
Trailing whitespace is not removed by formatter on 'empty' lines

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#4984]
The following test fails:

```typescript
/// <reference path='fourslash.ts' />

////    /*1*/
////	/*2*/

format.document();
verify.currentFileContentIs("\n");
````

_(where the contents before marker 2 are a `\t` character)_

I notice trailing whitespace is not removed from comments; whilst I would argue trailing whitespace should be removed across the board, I think it should at least be removed from lines only containing whitespace. 

Thoughts?

**Comment by mhegazy** [comment]
We do not touch comments, and this is by design. comments are not code, and should not be formatted.
as for empty lines, this is more of an optimization, and can be removed.

**Comment by myitcv** [comment]
> comments are not code, and should not be formatted.

Thanks for confirming this is the position as far as TypeScript is concerned.

**Comment by mhegazy** [comment]
thanks @SaschaNaz!
