### ISSUE TITLE
Wrong type assertion in classes using "this" keyword

### ISSUE THREAD

**Issue by nicolasmelo1** [microsoft/TypeScript#49851]
# Bug Report

### 🔎 Search Terms

this, assertion error, generics, type inference, automatic intersection

### 🕗 Version & Regression Information

Looks like it's above version 3.3.3333

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/PTAEFpKzQIQQQMoFFQGEAySWItf+AUAMYA2AhgM6WgCyA9gCYCmpoA3oaKAGYCWrRpQCEALjpNWAMQGkhAbi6h6ABwAufegDsR4hi1IB5dZp0AeNQAs+lAHyKAvoRIVqEgwHU+V+gFc1AJJaLAAeHEr8grru0rIKSqoa2tH6rMZJOl4+-kGhFtZ2js5kVDSppFmWucwhAHL0gVqwAE7kxADWzGo0nNyRcimSpDJRityJpoMG6ZP1jS1tnWr5NvaETi6lMaQAIswARr4A5h6WAJ4AKgUAEuQqKszB4X1xU7GjCSbJYtszyXuHI4rQrrZwgPD4OAAVQA4hCCAjEZs3FDKMxmqAampHkJts9eK9QABefHccjiEZyC5nB6UAB0sEMhgwSic4O4HM5XO5HIAahBQNdkAAlVABXAXIXQmHCWXCUCnM4AflA5CelnoAHdQGp6KBKPRSAA3ZigbxKz4ZSh6IZ-cxWVbE0lm4I1ZjW0AAbV6XN8Wj4AEdfMxxGpmsGADRKTn9ITiT0AcnICYAuqBwWZwKArjZQJr6M12jQqJiQg9iNjGDqNcdLNHQA4U6zQciaKj0ZU-I1QqXscEykNOzlXWEfbGaCSfWSKXFqbSGUyWdw2WAeWv1xv+VmczR84XKBG8+clSeVQBNPygdpaLVH8hqBM0ShhtVHZiH7ygABWvmfoEY2gJmoeYFu0oD7MwxDkL+prlNUYS5mqoCGPsX6QcBLD8FozBVnwWgcE44xfDoNrTMRlBDt2NTArYTo+k4GwlCiaLNJU8FzEECwdF0NBYjiA6eN4VQjhxTStNx3T4uOdH1uSoCUowc7uguzLNuyG4aZpW6gPANB8Pq5B8Iwh6auc1a5nuRZKoeO7-vQ7paEBoAALbkJ0+qPGiOp6s5zCWpMpFpORolcUsNEyZyeGhO68ZJqmzYbIQ4KItA2ZngACsguApQihCPL4znybONLuviaDXPAwpOgm5WVQmUbcIyzLVU1GD1UoAS1Bc1WdRcCYtmoJXbPBZi0L2-HbLRk5KH6gbBqG4bMGMBJROIAAUnRnPQPB0J6ABE457SmACUnopkUhCDQ8w0ju6IXiWFY18f22xsSJDScQ9PFTVezBbTttD7Yd53OFdsFDPB7oAsco0-T6s1BiGOqLRErx6ONL3lNDJznDutz3DioAqhtf3bbtB2vEdp1puIz7NHhRxnS24LaQ6NBg2aNA3sBMHGWaD40NopBnN5+oatqVj3vzIH7oeVimiozT0PspDMIVubaDdoSXUNhjNCw9NaEchg8OUdqUKNGO4uUoAAD6vUJXbwXbDtWOxH1iYsPEu1jBzHIqeN3A8wQ-ZtZOAxTURHbbShhzt7BelILq-f95PA6qNBJ89uJ0wzROgAABuAAAk7BSA4BegOI2Ems0NOgAAjIlHNm+R2OW9nAmsNjAc3EHOJw0oUVupQSqBaQkOUO3tC2Gdy0FgbDNj8h+vogzJut1asNz84Gwt7awUe6FXQdyEfbW4OQnu-MX3dIP3DDyE7rL3Bt2UPdXvLDPO-jKvhtHMvPWi8jYbwPlvb+IM95DU3pMSiI0npnwmuUOBI577KD-kvcQQC14gNNmAyY29IE62ujA5Ip9z5d1IGgx+z9x7wNniDX+wCAFYIwbg0h5gIEXX3gYBSE58SeljLTMMDMUwzkEEpSgoIgA)

### 💻 Code

```ts
// -------- BASE CLASSES ---------------
class Model {
  fields!: ModelFields;
  options!: ModelOptions<this>;
}

// ------- BUG ------------------------
class User extends Model {
  fields = {
    a: FieldTypes.BOOL
  }
//                        V - ⛔️ HERE IS THE BUG!!!! Why? and how to solve it?
  options: ModelOptions<this> = {
    indexes: [{
      unique: true,
      fields: ['a'] // <- ✅ This works as expected though
    }]
  }
}

// ------------ TYPES ----------------
enum FieldTypes {
  CHAR = 'CHAR',
  BOOL = 'BOOL',
  INT = 'INT'
}

type ModelIndex<M extends Model> = {
  unique: true;
  fields: (keyof M["fields"])[];
}

type OrderingOfModelOptions<M extends Model> = keyof M["fields"]|
  keyof { [F in keyof M["fields"] as F extends string ? `-${F}` : never] : 1}

type ModelOptions<M extends Model> = {
  indexes?: ModelIndex<M>[];
  ordering?: OrderingOfModelOptions<M>[];
}

type ModelFields = {
  [field: string]: FieldTypes
}
```

### 🙁 Actual behavior

Although i'm passing the correct arguments, it just don't work. It just don't work because the type ModelIndexes is an object, which is really strange to me. 

- I've tried changing the name of the `fields` to something else like `attributes` but no success, so **it does not seem that the problem is the name**.
- I saw that on `ModelIndexes` it looks like `M` and `Model` are having an automatic intersection like `M & Model`, but it needs some further investigation.
- I've tried doing conditional like `M extends Model ? (keyof M["fields"])[] : never;` but no success, the condition actually works but the problem then will be something like `Type '"a"[]' is not assignable to type 'this extends Model ? (keyof this["fields"])[] : never`

### 🙂 Expected behavior

in this example `indexes: { union: true, fields: ['a']}` should work because 'a' is defined in the User model `fields` object and `indexes: { union: true, fields: ['b']}` should not work because 'b' it's not defined inside of `fields` in User model

The expected behavior is to just work as 3.3.3 worked, so it accepts a union of all of the keys of the object not as all of the above versions works.

**Comment by MartinJohns** [comment]
Your property `fields` has the type `{ a: FieldTypes }`, but your generic type `ModelOptions<>` requires the type argument to extend `Model`. But the type of `this` is `{ fields: { a: FieldTypes } }`, and it does not extend `Model` (which is `{ fields: ModelFields; options: ModelOptions<this> }`).

When you type your property `fields` correctly it works:

```typescript
class User extends Model {
  fields: ModelFields = {
    a: FieldTypes.BOOL
  }
  // ...
}
```

**Comment by nicolasmelo1** [comment]
Whoa, nobody was being able to solve this, yeah, it works as expected now, and now i understood why this error happens.

Thanks a lot for the help and explanation, closing the issue now.
