### ISSUE TITLE
add more refactoring tools 

### ISSUE THREAD

**Issue by regisp** [Microsoft/TypeScript#4985]
Hi, 

I'd really love to see refactoring tools such as
- implement interface
- extract method

come in typescript (at least for visual studio 2015). 

Many thanks for your work!

Régis

**Comment by frederikschubert** [comment]
I would also like to see this as it would make the development experience much better.

**Comment by amirbaron** [comment]
Can we also have move method?

**Comment by DustinWehr** [comment]
I asked a question on reddit related to this. Would be very grateful to get a response from someone at Microsoft. https://www.reddit.com/r/typescript/comments/54bzah/friendly_typedclassbased_representation_of/

**Comment by reddyBell** [comment]
What I'd love for VS2015 is refactoring tools for:
-  Implementing abstract classes
- Generating the constructor of subtypes

These are basics that would bring a massive improvement to the development experience.

**Comment by mhegazy** [comment]
Implement abstract class is covered by https://github.com/Microsoft/TypeScript/pull/11547

**Comment by mhegazy** [comment]
Please file new issues instead of adding new items to this issue.

**Comment by reddyBell** [comment]
Thanks for the info. Sorry I thought this was a sort of catch-all issue for refactoring tools requests.

**Comment by DanielRosenwasser** [comment]
these should have been implemented in 2.5.
