### ISSUE TITLE
Object.values creates variables implicitly typed as `any` with no warning, even with `noImplicitAny`

### ISSUE THREAD

**Issue by guillaumebrunerie** [microsoft/TypeScript#49857]
# Bug Report

In some cases, `Object.values` creates variables implicitly typed as `any` without any warning, even though `noImplicitAny` is set to `true`.

### 🔎 Search Terms

Object.values, any, noImplicitAny

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (including 4.8.0 beta in the Playground), and I reviewed the FAQ for entries about any/unknown/Object.values

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99#code/CYUwxgNghgTiAEYD2A7AzgF3kgRgK3gC54BvAbQGsQBPYzGASxQHMBdOjRlgX3gB9SlGhy5tiKAK4BbHCBjcAUAoBmSGPAAUydFgBu2ZfADy+cBgB0uqBAkg0G3HgCUT0gvgf4u81HM5zYPAAvPAALABMANzwAPQx8ABySPByMGrY6gDusChMzAA0XvAAFlBo8BjUAA4IUCjUCtxAA)

### 💻 Code

```ts
declare const obj : {[key: string]: string} | {[key: string]: number}

for (const v of Object.values(obj)) {
    v.a.b.c = 42; // No error or warning, v has type any
}
```

### 🙁 Actual behavior

`v` has type `any` even though I never wrote `any` myself and set the `noImplicityAny` option to `true`.

### 🙂 Expected behavior

Ideally `v` should have type `string | number`, but at the very least it should either have type `unknown` or trigger an "implicit any" warning.

**Comment by MartinJohns** [comment]
The signature of `Object.values()` returns an explicit `any` (intentionally), there's nothing implicit. Changing it to `unknown` would be a massive breaking change, which IMO would be pointless, as this method is explicitly for dealing with dynamic data.

**Comment by MartinJohns** [comment]
> Note that `Object.values` does not always return an explicit `any`. For instance if its argument is of type `{[key: string]: (string | number)}` (to which the type in my original example is assignable), then it does return `(string | number)[]` as I would expect:

That's true, I always forget that, because it really shouldn't do that. It **should** always return `any` or `unknown`. See #38520.

**Comment by guillaumebrunerie** [comment]
Ah, thank you for the link, makes perfect sense now, I didn’t realize this type was actually inconsistent. I guess I'll try to avoid `Object.values` from now on 😄
