### ISSUE TITLE
No error in JavaScript on optional binding pattern parameter

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#49869]
# Bug Report

### 🔎 Search Terms

TS2463 javascript 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `default`

### ⏯ Playground Link

- [TypeScript link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAUAJAC2cAngEYQCqIAJhDKBEwFzJ5hSgBzANzEAvsWIwAriARZcySLwAUJCtTqMWbEB2QBeZACJeUIwBoxAfm4Z5+AJREyYOAGsIeAMp9ByyrQMzKzsTA4i4pIycjggiu6ePvwgAsqm3KaCTmoIuHjYADYQAHQF2Kmm4WISSmDK4UA)
- [JavaScript link](https://www.typescriptlang.org/play?strictNullChecks=true&noUnusedLocals=true&noUnusedParameters=true&noFallthroughCasesInSwitch=true&ts=4.0.5&filetype=js&noUncheckedIndexedAccess=true&exactOptionalPropertyTypes=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&useUnknownInCatchVariables=true#code/PQKhCgAIUgBAXAngBwKYBNUDNIHlnwCWA9gHYDOUMsyATsWrUpAN7ny2GkDmAvpAFsAhogBGqAKqlMWLhirBw4UBGhxkQ2kIGt8RMuX4BtBvooBdBeCwBXUgGMzkeKnYAKFuACQwsZOnYcuiQALyQAETstOEANOC8AJSs3vBCANauAMocXNxuvuJSMkEJANzxSipU6prarFG5-FFWtg5OqRnk2Zw8blFJnl72BsQANqgAdKPEef3lvEou7mVAA)

### 💻 Code

```ts
/**
 * @param [options]
 */
function test({ x = '' }) { x }
```

### 🙁 Actual behavior

No error on `{ x = '' }`.

### 🙂 Expected behavior

Error 2463: "A binding pattern parameter cannot be optional in an implementation signature."

The equivalent Typescript has the correct error:

```ts
function test({ x = '' }?) { x }
```

Note that in the playground link I have checked all options that are supposed to make types more strict. Also note that when this code is run, you'll end up with a runtime error. The same is true for the TypeScript equivalent, but in that case you get an error in advance warning you that the code you wrote will cause issues.

**Comment by sandersn** [comment]
`@param {Options} [options]` declares the parameter as optional. The equivalent in typescript is `{ maybeUndefined = 'str' }?: options`, which also gets rid of the error. (Although it adds an error at the declaration site since this combination isn't legal -- and should probably be illegal in javascript too.)

Instead, use `@param {Options} options`

**Comment by jespertheend** [comment]
Thanks for looking into this @sandersn!
I'm not really sure why this got closed as working as intended, since you mentioned

> and should probably be illegal in javascript too.

Should I create a feature request / new issue for this?

**Comment by sandersn** [comment]
Oh, I misread the whole thing. I'll re-open.

**Comment by JE-lee** [comment]
I supposed that it's working as intended.
`function test({ x = '' }) { x }` means that the first argument is required.
You'll get the error of `missing arguments` when you attempt to call this `test()`.

**Comment by jespertheend** [comment]
That's true, but with
```js
/**
 * @param [options]
 */
```
added to the JavaScript function you can suppress type errors that would otherwise warn you about the potential runtime error.
Have a look at the two playground links in the first comment. The emitted code from both JavaScript and TypeScript are the same, and both trigger a runtime error, but the JavaScript equivalent doesn't warn you in advance.
