### ISSUE TITLE
Object.entries behaves differently for interfaces and types

### ISSUE THREAD

**Issue by phryneas** [microsoft/TypeScript#49872]
# Bug Report

When using types, `Object.entries` returns a union of possible values as `value`, while a similar interface, it returns `any`

### 🔎 Search Terms

Object.entries union any

### 🕗 Version & Regression Information

This seems to go back at least until TS 4, I didn't test further.
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/PTAEEsDsDMFMCd6wCagC4E8AOtQAsBDAZ1AFdJwB7SUY0ANwIBtTdMcAoAbw9D9Caw0oAB6gAvKC6gA1rAwAuUACJGLWMoA0tSJTR4EAaXlKAzKAC+HXvwDG1IsNiQ08cLBKSA8gCMAVrC2aAB0zq7uRAAUIgCUNnwg-PwAegD8HFYcibAiWEzgtuDC7LiEJORUNHRqrOjYsNzxdTigAGKUlBJSTUlyiio1Gpo9-AS6+kYmoJCkALY+CE2ZSYLCIkrtnZLSfUqqzKxaOnoG8Mb95st2Dk4ubh5dvgFBoXcR0XFJiUmgaRnW2Vy+UKwigaAQ0AItlKdAABmMMLDaCRBs0GjwkmCIVDcJtuj9+LsBgchiM+GMTpN+jN5osklc+KtRBsOl0dlN9uojhSJmcppdrEl7JBHKAwvdPKAnoEQuL3rEmt8kn8rEA)

### 💻 Code

```ts
// explicit type has union as value type
{
    type Foo = {
        key: "value",
        anotherKey: number
    }

    let x: Foo = { key: "value", anotherKey: 3 }

    //const entries: [string, number | "value"][]
    const entries = Object.entries(x)
}

// explicit interface has `any` as value type
{
    interface Foo {
        key: "value",
        anotherKey: number
    }

    let x: Foo = { key: "value", anotherKey: 3 }

    //const entries: [string, any][]
    const entries = Object.entries(x)
}

```

### 🙁 Actual behavior

Object.entries behaves differently for types and interfaces

### 🙂 Expected behavior

Object.entries behaves the same for types and interfaces.

I am aware that the general argument is "interfaces could be extended" - but pretty much the same goes for a type here as well, right? 
Is this an oversight or intended behaviour?

**Comment by MartinJohns** [comment]
> I am aware that the general argument is "interfaces could be extended" - but pretty much the same goes for a type here as well, right?

Interfaces are subject to [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), whereas type aliases are not.

**Comment by Josh-Cena** [comment]
> `Object.entries()` should really always return `any` or `unknown`.

You mean `[string, any][]`?

**Comment by phryneas** [comment]
@MartinJohns yeah, but the basic logic that applies for both is equally (un)sound. 
Breaking this is possible with both an `interface` and a `type` ([playground](https://www.typescriptlang.org/play?#code/N4WAUABFEC4J4AcCmEBiB7dEC8FSWkIGsk4AuCAZxgCcBLAOwHMAacQwgQwfRgAskNANKkKDAK4BbAEaD20AL7h5UAGbiGAYxh10DCKswAKAB4UM6AJR4VHTXuoQkDWnSSUcEAPLSAVkm0AOmdXd1NLW0IAeiiOCAA9AH5bJTBbewZHADdOABtPfDioEnIIACIc3PEkMrYCOO5eAWFRCABWOqKIOCQYAEEefkERUtpqlNtDdCNKiLBU8BinEwRcuk06GAhGGEFVTk0UPk4PAANuOFOIE4hK6thEJHBC6B29g5QLG3qOEopqejMTpFRpDFqlCQyOQ-BY-dRaHR6AzGMxoTDWF5xDKOEL0dyeHz+IK4tyUcKRaBLDhJCZpOmEbFbSoFCnFVoVPLVWqs66DZojCgdHk9fp84atMZPGGTYyzcAKIA)), so it is very unintuitive that they would behave so differently.


Tbh., I'd be fine with either behaviour (although personally I prefer the "unsound, but usable" behaviour over `any` and would argue that if it's the `any` behaviour, it should be `unknown` instead) - but having a difference between a `type` and an `interface` here just adds more confusion on top.

**Comment by Josh-Cena** [comment]
The issue is still because interfaces don't have implicit string index signatures, causing it to fail to match the `entries<T>(o: { [s: string]: T } | ArrayLike<T>): [string, T][];` overload. Last time it was brought up at https://github.com/microsoft/TypeScript/issues/49751

**Comment by phryneas** [comment]
Ah, that's at least a puzzle piece that explains it.
