### ISSUE TITLE
Allow comments in tsconfig.json

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/TypeScript#4987]
Comments don't seem to be allowed in the tsconfig.json file. See [this](http://blog.getify.com/json-comments/) article for why it is ok according to Douglas Crockford to add them to json config files.

I initially raised [this](https://github.com/ivogabe/gulp-typescript/issues/210) issue with gulp-typescript as I'm trying to use that Gulp task in my ASP.NET 5 project to compile my .ts files to .js but I'm getting errors and the developer has pointed me here.

My goal is to add TypeScript support to [ASP.NET MVC Boilerplate](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate) which provides an ASP.NET 5 project template with lots of helpful comments and features built in. I'm currently having to resort to a separate tsconfig.html file to write comments about the file. The comments include a little info about what the file is for, a useful link to the tsconfig.json documentation and a few reasons for the chosen default settings.

Many other similar json config files already support comments. Examples are: JSHint (.jshintrc file), JSCS (.jscsrc file), TSLint (tslint.json file). The first two do not use a file with a .json file extension which may have something to do with the use of comments.

**Comment by mhegazy** [comment]
@tinganho had a pull request for this. @tinganho feel free to resubmit the comments PR.

**Comment by tinganho** [comment]
I will do, just a little bit busy with other things right now.

**Comment by slikts** [comment]
Having comments in the configs would be very helpful, and JSON as a config format is an exception in not having them. It would also be nice to add support for trailing commas in the same way to make editing JSON less fiddly.

**Comment by sarod** [comment]
:+1:
This would be very useful to document excludes for instance

**Comment by mhegazy** [comment]
PRs are welcomed here.

**Comment by mhegazy** [comment]
thanks @sarod!

**Comment by ironside** [comment]
It would be great if this format followed the popular [HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md) format

I realize this is merged, but its the most relevant ticket I found to mention it.
