### ISSUE TITLE
Expose `program.emitBuildInfo`

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#49871]
# Suggestion

In Deno, I am making a change for `deno check` to not emit using the TS compiler anymore (waste of time because this command is just about type checking), but as part of this I still want to emit the build info to speed up future checks. Right now, I'm just calling the internal function like so:

```ts
program.emitBuildInfo(host.writeFile);
```

...but it would be nice if this was officially exposed in the declaration file.

## 🔍 Search Terms

* emitBuildInfo

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Added to the declaration file. Perhaps the parameter could be made optional (if it's not) since the program has a host? **I can submit a PR?**

## 📃 Motivating Example / 💻 Use Cases

In Deno I want to store the build info file without emitting because we have a `deno check` command.

## Related Issue

Previous issue that was closed because it was marked as a duplicate of the emit API: https://github.com/microsoft/TypeScript/issues/30886

**Comment by sheetalkamat** [comment]
If you run same config with `noEmit: true`, it should write only buildInfo as part of emit

**Comment by RyanCavanaugh** [comment]
@dsherret does that solve your use case?

**Comment by dsherret** [comment]
Probably. I just haven't gotten around to test it out to see if it works. I would say if you know that works then feel free to close and thanks! :)
