### ISSUE TITLE
make `getImportModuleSpecifierEndingPreference` default to `.js`

### ISSUE THREAD

**Issue by jimmywarting** [microsoft/TypeScript#49885]
Why?

1. This is what NodeJS docs has to say about extension:

> Mandatory file extensions [#](https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#mandatory-file-extensions)
A file extension must be provided when using the import keyword to resolve relative or absolute specifiers. Directory indexes (e.g. './startup/index.js') must also be fully specified.
>
> This behavior matches how import behaves in browser environments, assuming a typically configured server. 
A file extension must be provided when using the import keyword to resolve relative or absolute specifiers. Directory indexes (e.g. './startup/index.js') must also be fully specified.
>
> This behavior matches how import behaves in browser environments, assuming a typically configured server.

In summary if you decide to build something as ESM, then you can't and should not be using extension-less paths
It can't simply just guess what you meant to import if it where a remote http import...

---

2. it dose not hurt if cjs uses explicit path as well... in fact it's slightly faster to resolve the paths rather than having to scan the folder to find any match within a application that loads lots of dependencies and having to resolve 5000+ files that it has to lookup by 2nd guessing what `require('./foo')` meant: is it a file? is it a folder? is it a json? [#](https://nodejs.org/dist/latest-v18.x/docs/api/modules.html#all-together) 

```
LOAD_AS_FILE(X)
1. If X is a file, load X as its file extension format. STOP
2. If X.js is a file, load X.js as JavaScript text. STOP
3. If X.json is a file, parse X.json to a JavaScript Object. STOP
4. If X.node is a file, load X.node as binary addon. STOP

LOAD_INDEX(X)
1. If X/index.js is a file, load X/index.js as JavaScript text. STOP
2. If X/index.json is a file, parse X/index.json to a JavaScript object. STOP
3. If X/index.node is a file, load X/index.node as binary addon. STOP
```

All this stat-ing the fs from looking up the correct paths adds a slightly unnecessary delay that can totally be avoided if you simply just add a `.js` at the end [#](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/)

---

3. Using explicit paths also means it will be easier to refactor to ESM at some point later in the feature if you ever decide to switch to ESM that demands that you use explicit path.

---

4. Even if you use something like ESM syntax with explicit path and using webpack/babel or whatever to bundle your package then you should also be using explicit path. there are folks who just wish to simply load the original files that arn't bundled cuz the bundle is not that well splited / lazy loaded and you don't want to import the hole application.

In fact it can be quite easy to simply just remove the bundler all togheter when you decide that you no longer need a bundler anymore and solo rely on built in features. node-fetch is one such example where they stop using babel and no longer wanted to bundle files anymore. if you have used explicit path then the refactor would have been a loot smoother.

---

5. https://youtu.be/M3BM9TB-8yA?t=836 (10 things ryan dahl regrets)

---

6. all this extension less paths only makes it tuffer for others who wishes to build some form of build tool (in other languages) that now also needs to follows now node's considerable bad anti-patern for resolving extension-less files

**Comment by RyanCavanaugh** [comment]
The default setting today is `auto`, which means "Match whatever the current file is using". Moving to `.js` is just strictly worse because it's going to make everyone who is perfectly content with their current paths go in and change it back to `auto`. For people who are using extensionful imports already, they will get correct (from their perspective) imports too.

**Comment by jimmywarting** [comment]
in that case for new project when auto can't determinate what to use then it should be `.js`

**Comment by RyanCavanaugh** [comment]
AFAIK the fallback default depends on the project settings, so it's going to suggest `.js` if the module resolution supports it and no extension if not.

**Comment by jimmywarting** [comment]
And what if you don't have a project settings and working from a clean slate and not doing any typescript stuff?

**Comment by RyanCavanaugh** [comment]
With some probability regardless of the default, you'll encounter a path other than the one you expect and will have to change your settings.
