### ISSUE TITLE
Incorrect type inference of common generic method over union type

### ISSUE THREAD

**Issue by dustbort** [microsoft/TypeScript#49893]
# Bug Report

### 🔎 Search Terms

generic method union type

### 🕗 Version & Regression Information

- This changed between versions _4.1.5_ and _4.2.3_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/JYOwLgpgTgZghgYwgAgJIEEBqwDOwwD2UAPACoB8yA3gFDL3IBuu+6AFAJQBcypA3DQC+NBABs4OHMnTU6DAA4BXAEajgCZFAhwAJgRCiAnrwCaABQCiyALzIA5OjsC59REnlgy5NszyEoPBjYfkRe3LyyDFGaEGCKUCBMLP4AdL6snAJRwsI0oJCwiCioAELB+KEUkQzpYCWcPPxCIuKSyCXV9Eqq6jG6+kamljb2JU40LshuEB5ePslEgWULJBThpJ3RWnEJSSFQacn1HFkMORP50PBIaADC5f5em7W3bHBQUHCGPGzoAD4lDgAbQAuusBMIxBIpLdNt01BotP0DMZSOYrLY7LdxpMEPocGAoIoEP42PIoMBGHBIFMPl8fv9AaCONRBM4otNZhR5vtAvcVmFGpsott4olakRDn5XmAABa4FLvT6GE6Tc4taHIB5EACMyGAAFt5KIIAaIOApEEBQSKSAAObkAA0aGW+2IIEUBuU0Cdd21JGUBAIJrgIEotCitXY4RtoDtwoYot2ACJZRBRKICMnTvRcpGjg1kB6vdAE-Qk4kACwAJhzyDzNWSryV9OQvwBwLBPEDwe0iQj0XoeJABJiOEUojAP1j9r+xe9UE7IxbhhSBrg8jY+FNNko24NioQ7jAbDluA4qsH5diYuQhMUEDr6qhbX91f1RpNZotaCw1sJca+qU-rup6C5Afybo9iGYbPMk0Y8DO8YDoOFbIKm6aZtmaoTPmfjHDw86lihWw3rsNZPrhjbSm8dLfG2jKduE0F9mWyDDqOWjjpO04AbORGLqCy50WuG5bpABq7mxUQ4AA7vgCCym2+4pGilgsiRV7RAgEgoA4dg8GhKmcieZ44JeWlXjpOB6WMhlkYkxlHjMpnyuZdZacInkWahDl3kSj44YIQA)

### 💻 Code

```ts
class Visitor1 implements IAVisitor<string>, IBVisitor<number>, ICVisitor<boolean> {
    visitA(): string {
        return "hello";
    }

    visitB(): number {
        return 42;
    }

    visitC(array: (A|B)[]): boolean {
        const result: (string|number)[] = array.map(item => item.accept(this));
        return true;
    }
}
```

### 🙁 Actual behavior

In Visitor1#visitC, in the call to `accept` there is an error on `this`: `Argument of type 'this' is not assignable to parameter of type 'IAVisitor<string> & IBVisitor<string>'.`

The Typescript compiler seems to arbitrarily choose the first generic type of the first interface implemented by Visitor1 to infer a type T on a _single_ aggregated function type for `item.accept`. This is simply incorrect.

In TS version 4.1.5, the Typscript compiler refused to aggregate the function types at all: `This expression is not callable.
  Each member of the union type '(<T>(visitor: IAVisitor<T>) => T) | (<T>(visitor: IBVisitor<T>) => T)' has signatures, but none of those signatures are compatible with each other.`

So it seems that in version 4.2.3 some kind of incorrect type logic was applied to aggregate the union of function types.

### 🙂 Expected behavior

The JavaScript semantics of this call will use the `accept` method of the respective instance, returning `string` or `number` respectively, and the call to `map` will return type `(string | number)[]`. So, the type inferred on `accept` should be an overloaded function or a union of function types, whose members are generated by applying type inference on the argument `this` in a distributive manner:

- Before type inference:
```
item.accept: (<T>(visitor: IAVisitor<T>) => T) | (<T>(visitor: IBVisitor<T>) => T)
```
where keeping in mind that generic `T` is _independently_ free in each union member.

- The type of `this` should be treated as an invariant in the type inference, e.g.:
```
this: IAVisitor<string> & IBVisitor<number> & ICVisitor<boolean>
```

- The proper way to infer the concrete type of `item.accept` is to distribute the type of `this` over each generic member of `item.accept`, then unify the parameter type with the argument type, over the generic parameters. After type inference:
```
item.accept: (<T extends string>(visitor: IAVisitor<string>) => string) | (<T extends number>(visitor: IBVisitor<number>) => number)
```

- The type of `this` obviously distributes over the union type of `item.accept` to produce the return type `string | number`. This matches the JavaScript semantics and the actual return type.

- The code in Visitor2 shows that if we explicitly narrow the type of `item` before calling `accept`, the aggregated return type is as expected. Having to explicitly narrow the types this way defeats the purpose of using the visitor pattern.

**Simplifying the union of function types into a single function type is problematic when generics are involed:**

I guess if you wanted to simplify the union type of `item.accept`, a naive attempt would look like
```
item.accept: <T extends string | number>(visitor: IAVisitor<string> & IBVisitor<number>) => string | number
```
but this might be problematic if the generic functions `accept` had different numbers of generic arguments. Technically each generic parameter in the union needs to become a separate generic parameter on the aggregated function type and unified independently:
```
item.accept: <T0 extends string, T1 extends number>(visitor: IAVisitor<string> & IBVisitor<number>) => string | number
```
so it may be better to avoid this type of simplification.

**Comment by RyanCavanaugh** [comment]
The proposed mechanism would be potentially explosive in terms of performance -- there are *often* unions like this where there are hundreds of different constituents with a common method whose signature can be correctly unified into a single call, and we do do that.

> to infer a type T on a single aggregated function type for item.accept. This is simply incorrect.

It isn't incorrect, rather it rejects some programs that otherwise could be accepted, but no typechecker is capable of accepting every correct program.

**Comment by dustbort** [comment]
So I can write a program to explicitly switch over each type in the union and that doesn’t explode. Yet the compiler, which can easily  enumerate the same types in the union, will somehow explode? Not a compelling explanation.
