### ISSUE TITLE
Type inference of method argument from decorator does not work

### ISSUE THREAD

**Issue by jirihybek** [microsoft/TypeScript#49896]
# Bug Report

Method argument type is not inferred from a context when a decorator is used.

### 🔎 Search Terms

decorator type inference
infer method argument type from decorator

### 🕗 Version & Regression Information

Version 4.7.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type inference

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220713#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwCLBrQCGM0APACoB8AFAJRwDeAsAFACQUwMSUutGMSgBzHgC44qANYoIAdxQAaOGCgQwwWAE8A0sG2SAzjCiYUIlQBNgRtGbBkokyts1WACus06Cdh07ktABGwi6MALzUcMEQEAA2wMQo1JHRrGxwWXAA9Dn4EHBGEAC2PAAW5iLsHAC+7PVs7GjxxEZGcABiccw1AAIERFCkFCZmFnT0NWBIwfGYaHAl2gCyFRBWIcKMTLn5ABJawHAw5ccA5KFQ53DlbXDJcJglYPNomPDJ2iduwDVcPD4uFMSGAAG4ao1GuxBiRAmMqpNaChgPIunEGCoAETLNanDZYlQZLIAN2I8VBki2UDSiHJRmOeTgh24JzOcEuwhudw6Q24GB+mgeHQRFga9DBQA)

### 💻 Code

```ts
export function Decorator<T>() {
	return (target: unknown, propertyKey: string, descriptor: TypedPropertyDescriptor<(bar: T) => boolean>) => {
    // Do something
	}
}

class Foo {
	@Decorator<string>()
	public myMethod(bar) { // Here the 'bar' has an implicit 'any' type, should have 'string'
		return true;
	}
}

Decorator<string>()(new Foo(), "myMethod", {
  value: (bar) => false // Here the 'bar' has correct type as 'string'
});
```

### 🙁 Actual behavior

When the method argument has no type specified its implicitly set to `any` even when decorator is used and requires specific type.

### 🙂 Expected behavior

I expect the type inference to work the same as for callbacks, eg. when no type is specified for the argument it is inferred from the context - means the type expected by the decorator is used.

When I call the decorator as a normal function, a type for a property descriptor value is resolved correctly. Also type checking works correctly - when I set method argument to something else than the decorator expects, it reports an error.

**Comment by MartinJohns** [comment]
Decorators are unable to change the type of whatever they're attached to. You need #4881 for this.
