### ISSUE TITLE
Go to definition is missing references as of TypeScript 4.7.4

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#49899]
# Bug Report

### 🔎 Search Terms

"go to definition" javascript

### 🕗 Version & Regression Information

- This changed between versions `4.6.4` and `4.7.4`

### ⏯ Playground Links

- [4.6.4](https://www.typescriptlang.org/play?ts=4.6.4&filetype=js#code/MYGwhgzhAEAqCmEAu0DeAoAkMA9gO2QCcBXYJHQgCgEo0tMB6B6AJQEsBzACxVDeADW0MHgAm0YFxw4I8aAHIA4jmjloAEXgAzNnjZI2+efSbQz0AD4nm5gGr0kXNhAB0W6dAC80PMRAgAbiwAX3QsWSQAMWkaOkxMR2c3D28AIjwcFF9-VKDMUKxiWQhonFiMeLYtaEpE13ccWgr43AIUEBwAd3hCL1UneukXcgAZHGAwEHgx7sIAYUh4GjyW-AgcKZcOjkoO2eoV0Pz0YKA)
- [4.7.4](https://www.typescriptlang.org/play?ts=4.7.4&filetype=js#code/MYGwhgzhAEAqCmEAu0DeAoAkMA9gO2QCcBXYJHQgCgEo0tMB6B6AJQEsBzACxVDeADW0MHgAm0YFxw4I8aAHIA4jmjloAEXgAzNnjZI2+efSbQz0AD4nm5gGr0kXNhAB0W6dAC80PMRAgAbiwAX3QsWSQAMWkaOkxMR2c3D28AIjwcFF9-VKDMUKxiWQhonFiMeLYtaEpE13ccWgr43AIUEBwAd3hCL1UneukXcgAZHGAwEHgx7sIAYUh4GjyW-AgcKZcOjkoO2eoV0Pz0YKA)
- [TypeScript equivalent](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBAYwDYEMDOa4BVhpgbwCgB6YuAJQEsBzAC3mUoQGs4UA7AE0VogjWBwA5AHEIcGOIAiwAGaV2lGJQjshJMnDgAfDVrgA1QgEhZfAFxw8UBdR1x2AVyRIA3IRMJV1xwklQACgBKOCJjYxhaSjQAOjNxAF4HZzcTAF8PYwEYADE+YNCTCKjY+LgkgCJ2CHgnFwr3YwyTRwE0PIgCsONKWTgAyOi4vhDu4y92PDgkCAB3YChyiRLhiBjJABkIBBQkYC35qABhdGBgxvCJtAg9mJnqAJnDoIuMpsI0oA)

### 💻 Code

```js
class Test {
	constructor() {
		// Right click and choose 'Go to Definition'
		//    |
		//    V
		this.foo = null;
	}

	setFoo() {
		this.foo = "not null";
	}

	usesFoo() {
		if (this.foo) {
			const lower = this.foo.toLocaleLowerCase();
			console.log(lower);
		}
	}
}
```

### 🙁 Actual behavior

Only the first two references are shown

### 🙂 Expected behavior

All references are shown, including those in `usesFoo()`. This was the behaviour in 4.6.4, and is currently still the behaviour when using the TypeScript equivalent of this code.

**Comment by jespertheend** [comment]
Hmm I reckon this might actually be intentional in a way. After all the TypeScript equivalent works exactly the same, using 'Go to Definition' on one of the references goes to the only definition available, which is the one on line 5.

The only difference is then, that in JavaScript there are two definitions. One where it is set to `null` and another where it is set to `"not null"`.
You can see the behaviour is in fact the same by adding a second definition to the TypeScript version: [playground](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBAYwDYEMDOa4BVhpgbwCgB6YuAJQEsBzAC3mUoQGs4UA7AE0VogjWBwA5AHEIcGOIAiwAGaV2lGJQjshJMnDgAfDVrgA1QgEhZfAFxw8UBdR1x2AVyRIA3IRNmIl67ftOXdxMEVWtHBEkoAAoASjgiY2MYWko0ADovOABeB2c3EwBfD2MBGAAxPlj4kySU9MycgCJ2CHgApEb3YyKTRwE0CogqhONKWTgo5NSMvjiR4xD2PDgkCAB3YChsiTqZiDTJABkIBBQkYGONqABhdGBYrsTFtAhztNXqKNWrmMei7sIBSAA). It shows an error because there are now two `foo` definitions, but 'Go to Definition' functionality still works and you can see the behaviour is exactly the same as what is happening in JavaScript.

So I suppose there are two possible expected behaviors that would fix this:
- Using 'Go to Definition' on something that is already a definition, causes all references to get shown, both references and definitions.
- When 'Go to Definition' is used on something with multiple available definitions, only a single definition would get listed. In the case of TypeScript this would be whichever doesn't have a 'Duplicate identifier' error, and in the case of JavaScript this would be the one that is inside a `constructor()`. Though I'm not sure what should happen if in JavaScript the constructor doesn't contain a definition at all.

**Comment by RyanCavanaugh** [comment]
There are two different verbs available here:
 * Go to Definition
 * Find All References

Go to definition attempts to go to "the" definition, but will show multiple results if multiple are present. In a JS file, every *assignment* to a `this.` property is considered a definition, so you see both assignments but not the use site. The fixed bug was that we were showing a non-definition result in a use site.

**Comment by RyanCavanaugh** [comment]
Or to put it another way, the invariant we chose to preserve is that adding an additional "declaration" will not hide an existing declaration from the Go To Definition results

**Comment by jespertheend** [comment]
Yeah that makes sense, I think what confused me is that VSCode has a setting for a fallback method when the result is the current location.
Ideally I'd want to get a list of all references *and* all definitions. But I think that would be easier to achieve by making a change to VSCode rather than to TypeScript.
