### ISSUE TITLE
Conditional return type wrong on function, but correct on caller

### ISSUE THREAD

**Issue by metehus** [microsoft/TypeScript#49897]
# Bug Report

I'm working on a function, that should return `ResponseA` when a parameter is true, or `ResponseB` otherwise. The return on the execution works fine, but when returning it inside the function, there's a type error, needing to use `as any` to fix it

### 🔎 Search Terms

I've tried to search about conditional returns by functions, but didn't find any regarding this issue

### 🕗 Version & Regression Information

Tried on 4.7.4 and the nightly version
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&useDefineForClassFields=true&noUnusedLocals=true&noUnusedParameters=true&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=99&jsx=0&pretty=true&noErrorTruncation=true&isolatedModules=false&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&ts=4.7.4#code/JYOwLgpgTgZghgYwgAgEoQM4AcD2IMQCCyA3gFDKXIw44BCcUAXMhmFKAOZkC+ZZoSLEQp02PATqkKVbBATA4AGwByAVwC2AI2gsQmnVF78yYAJ5YUAZQAWONUoAmAcQhgAYsChsAPKmQQAB6QII4YyADaaiAA1iA4AO4gADTI0XGJIAC6qVYAEgDyAKoAMgAiAcEQoeFatEoQcCAAfDKUALzI+cXllSFhyOxqKAD8aBEADFnILKgRAIxZJjDRCGDAeMicbgCSIDQ+UkH9tfWNLQAUNFAacGAsdACULLb2Tq4eXr4RYrj4RKlfhIIHQcsg6M1pFRkMAYMgrjgbndHlDoVQoG41FAQKi0WiaPRGCwAOQ2CBKJQ4ZAJRFOYltNF8aE8AJKAi4tEYsBYnHkPF4uQKZTqbS6ZAAFgATAzmQy+HwyAgJGBkHBkJ1tmA9jQLkMII9FcrkFp1VtdvscFdlAQDUA)

### 💻 Code

```ts
interface ResponseA {
    fooBar: string
}

interface ResponseB {
    specialNumber: number
}


type ShouldGetFirst<R extends [unknown, unknown], SHOULD extends boolean>
    = SHOULD extends true ? R[0] : R[1]


function getInfo<B extends boolean>(format: B): ShouldGetFirst<[ResponseA, ResponseB], B> {
    if (format) {
        return {
            fooBar: 'hello world' // Type '{ fooBar: string; }' is not assignable to type 'ShouldGetFirst<[ResponseA, ResponseB], B>'
        }
    } else {
        return {
            specialNumber: 42 // Type '{ specialNumber: number; }' is not assignable to type 'ShouldGetFirst<[ResponseA, ResponseB], B>'
        }
    }
}

const a = getInfo(true) // a is ResponseA
const b = getInfo(false) // b is ResponseB
```

### 🙁 Actual behavior

The return statements are returning an not assignable error, even that, when executing the function(as seen on the end), the response types are correct.

### 🙂 Expected behavior

The problem should not exist, so it's not needed to use `as any`

**Comment by MartinJohns** [comment]
Resolving of conditional types involving unbound generic type arguments is deferred. At that point the compiler doesn't know what `ShouldGetFirst<[ResponseA, ResponseB], B>` resolves to, because the compiler doesn't know what type `B` is. Constraints are not taken into consideration. Same as https://github.com/microsoft/TypeScript/issues/48243.

When actually calling the function the type argument is not unbound anymore, so the conditional type can be resolved.

**Comment by RyanCavanaugh** [comment]
Also #33014
