### ISSUE TITLE
type inference fails with conditional type 

### ISSUE THREAD

**Issue by lizi002** [microsoft/TypeScript#49900]
# Bug Report

### 🕗 Version & Regression Information

TypeScript version prefix: 4.7.4

VSCode version: 1.68.0

### 💻 Code

```ts
interface HKT1 {
    K: "* -> *"
    0: unknown
    R: unknown
}

//type Kind1<F extends HKT1,A> = { value : ({readonly 0 : A} & F)["R"]}
type Kind1<F extends HKT1,A> = unknown extends unknown ?  { value : ({readonly 0 : A} & F)["R"]} : { value : ({readonly 0 : A} & F)["R"]}


interface Algebra1$<F extends HKT1> {
    readonly null: Kind1<F, null | undefined>;
  }
  
  export interface Program<A> {
    <F extends HKT1>($: Algebra1$<F>): Kind1<F, A>;
  }
  
  export const make = <A> (P:Program<A>) => P;
  
  export interface ProgramK1 extends HKT1 {
    readonly R: Program<this[0]>;
  }
 
  const b0 = make($ => $.null)
```

### 🙁 Actual behavior
By checking the code posted here, and check the definition of type "Kind1".
If we let 
type Kind1<F extends HKT1,A> = { value : ({readonly 0 : A} & F)["R"]}
the function make will infer the correcet type as expected
![image](https://user-images.githubusercontent.com/60492046/178938230-3dafbe3b-e0be-4c80-8a50-a22307b1c1e8.png)

If we let
type Kind1<F extends HKT1,A> = unknown extends unknown ?  { value : ({readonly 0 : A} & F)["R"]} : { value : ({readonly 0 : A} & F)["R"]}
the function make will infer the type as unknown
![image](https://user-images.githubusercontent.com/60492046/178938507-5ef8264f-88eb-4f01-b2de-cc48528054e0.png)

However, these two "Kind1" looks same, as '''unknown extends unknown''' must always be true.

### 🙂 Expected behavior
If we let
type Kind1<F extends HKT1,A> = unknown extends unknown ?  { value : ({readonly 0 : A} & F)["R"]} : { value : ({readonly 0 : A} & F)["R"]}
the function must infer the correcet type

**Comment by MartinJohns** [comment]
[Playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgBIGkAqBGZBvAKGWOXQC5kAiAKmQFoA+ZayokgBgoFcQBrEAPYB3EG2IAlbn0EiCAXwIEA9ErABPAA4p0oACbYAPADFkEAB6QQugM5os2ADQBBJgF58yAG5wANlxQUABR4UBBwugIgPmrI7MgUTnLIAGTIRgCUANqU4pQAugrqWqR6hibmljZ2OM5uyDz8wiCmFhBWtg0yzQD8xHhevv7xyMGh4ZHRscOJKWlZOflJFP3efgEjIWERUTFxCUmpGdm5BYoEoJCwiChOPgDmEABGUHDYACTGLZW2GDhMhCRkGNtpMQFwfD4KDorGUHMgwRDkAAfepWCAwUAQXQMADc8kU5g0AigYGQF2g8CQyAAClABHcXgBbAwufBiZCfCptKq-bAMQJvBL3J4vd7GBjpKGlYxwlx4hQEQnE0kISLWUmMuC8FDuFkOJiBalkWn0pksiXIVxMal4xVmIkksngCnXGl0hlwRnoXBc9rVXAAkjAiYxSRu02egxgAAWwGsmXYeVx+IIqpA6uQjzi7k12oFlqYbwAdAifOllEpAVWAHrdAhAA)...

**Comment by RyanCavanaugh** [comment]
That definition of `Kind1` doesn't seem like something that needs to be written.

If you have a repro that involves a more realistic definition of `Kind1`, please open a new issue. Thanks!
