### ISSUE TITLE
LS OOMs during FAR in aws-sdk

### ISSUE THREAD

**Issue by david-987** [microsoft/TypeScript#49908]
Follow-up to #49633 @amcasey 

OS: Windows 10
TS 4.7.4
VSCODE 1.68.1

Repro: https://github.com/david-987/ts-aws-slow-repro - sorry if it's a bit messy, I was trying to mimic a real project.

From the repro go to `src\packages\util\src\util.ts` and find references to the UtiLClass, notice the slowness. Silently crashes + restarts without ever finishing the task.
80% of tsserver.log are references to `node_modules/aws-sdk`. Manually deleting unused files from the `node_modules/aws-sdk/client/` directory helps.

**Comment by amcasey** [comment]
@david-987 Thanks!

**Comment by amcasey** [comment]
@david-987 Unfortunately, I think there may be some hidden steps in your repro.  I tried opening exactly that file and triggering find-all-references at line 10, column 7 and I got 4 results in 20 ms.

Now that there's no "real" code in the repro, can you share your tsserver log?  That should indicate if we have different editor settings or anything.

**Comment by david-987** [comment]
Here's my tsserver.log after restarting vscode and 'Go To References' on the UtiLClass.
Loads for around ~1minute, consumes up to 3GB of memory, crashes,
[tsserverlog.zip](https://github.com/microsoft/TypeScript/files/9116832/tsserverlog.zip)

**Comment by amcasey** [comment]
One difference I notice from my repro is that you don't have this VS Code setting:

```json
"editor.semanticHighlighting.enabled": false,
```

Can you (temporarily) set that and see if it helps?  It's been known to cause perf problems, but it's not obviously doing so in your log.

That looks very similar to what I'm trying locally, but I'll keep poking around to see if I can figure out why yours is running out of memory.

**Comment by amcasey** [comment]
Sorry, it's not running out of memory, even if I reduce the heap size.  From your log, it looks like you might have still been using your original version of the repro project?  I tried that, but I still can't build it - there's an error about not being able to find `@packages/aws` (i.e. a path mapping issue).  Are you also seeing the OOM with the revised version?  If so, can I see that server log?  Thanks!

**Comment by david-987** [comment]
@amcasey Yes this log is from the original repo (initial commit) - your suggestions fixed it for the repro repo.  Am still trying to implement them in my real repo.. one step at a time. So far it's still running OOM. What I find odd is you can't repro from my original version - didn't have issues with `@packages/aws`

**Comment by amcasey** [comment]
> didn't have issues with `@packages/aws`

It's pretty easy, when you're editing composite tsconfig files, to end up in a state where `tsc` doesn't know which files to delete on a clean build (it only deletes known outputs and tsconfig changes can move those), so it can be helpful to `git clean ` to get back to a really clean state when investigating build portability issues (i.e. when it only works on your box).

> "editor.semanticHighlighting.enabled": false, did not seem to help.

Thanks for confirming.  That makes sense, based on your log.

**Comment by amcasey** [comment]
@david-987 Anything else you want to investigate before closing this?

**Comment by amcasey** [comment]
(Context: on various side threads, we've revised the configuration of the repro project, mitigating the OOM.)

**Comment by david-987** [comment]
@amcasey can close thanks, anyone else running into similar misconfig issues can follow our discussions in the linked repo. Thanks!

**Comment by amcasey** [comment]
Thanks for your collaboration on this!
