### ISSUE TITLE
Emit declaration `d.ts` adds `declare` on `type` declarations

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#49903]
# Bug Report

### 🕗 Version & Regression Information

ts stable `4.7.4` & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBiEJwLxwIwDcQA)
    
### 💻 Code

```ts
// file.ts
type Foo = 1;
export type Bar = Foo;
```

### 🙁 Actual behavior

```ts
// file.d.ts
declare type Foo = 1;
export declare type Bar = Foo;
export {};
```

### 🙂 Expected behavior

```ts
// file.d.ts
type Foo = 1;
export type Bar = Foo;
export {};
```

`declare` has no effect on `type` declarations and is therefore code bloat

**Comment by RyanCavanaugh** [comment]
@weswigham is there a reason we do this?

**Comment by RyanCavanaugh** [comment]
Discussing internally, [no one can find a reason for this that still applies anymore](https://www.psychologytoday.com/us/blog/thinking-makes-it-so/201402/the-pot-roast-principle). We can take a PR and see what unexpected stuff breaks (maybe nothing??); should be easy enough.
