### ISSUE TITLE
[Syntax Highlighting: NodeJS] Double `export` of `var` or `const` (or any other exportable object) not properly flagged

### ISSUE THREAD

**Issue by Creative-Difficulty** [microsoft/TypeScript#49911]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.69.0 (Universal)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:41.511Z (1 wk ago)

- OS Version: Darwin x64 21.5.0 (macOS Monterey)

Steps to Reproduce:

1. Initialise a new NodeJS project 
2. `export` any type of exportable object twice
3. No error is being thrown
4. When running the program I get this output: ```SyntaxError:
Duplicate export of 'Argvchecked'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:117:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:361:14)
    at async link (node:internal/modules/esm/module_job:70:21)```

**Comment by Creative-Difficulty** [comment]
@mjbvz Im not using TypeScript! Just plain JS! This is an issue with VSCode Syntax highlighting not TypeScript!!

**Comment by mjbvz** [comment]
@Creative-Difficulty TS handled error reporting for js files too

But also, this works fine for me:

![Screen Shot 2022-07-15 at 10 15 04 AM](https://user-images.githubusercontent.com/12821956/179274698-97c9bf02-dce8-4080-b457-d5527fd7b1ea.png)

Are you using `export` or the old `exports.abc = 123` syntax?

**Comment by Creative-Difficulty** [comment]
@mjbvz Weird... Its still broken for me on macOS, but if it works for you ill close it!
Thanks anyways!
