### ISSUE TITLE
Array.prototype.find not typing input as possibly undefined

### ISSUE THREAD

**Issue by ChrisMcD1** [microsoft/TypeScript#49913]
# Bug Report

### 🔎 Search Terms

Array, find, holes, sparse array

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Array.prototype.find

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydaiKVDtUAAMXgGAAvKAAN6KErSRz5frsRDSb4AbkUAF9+Yp3DRHGQORUyGQmAAeGnwAB8oAZAG0ALrC8WqgDM6pVTJZ43ZoAAjLxBcKEJxBDRkhweAA1BjQdgoBnigLJDLcAAUvsgAEoVcrIAE2di6VGzYHhSocM0PGQvIh4H0GMD2DQvm4zMx2AxmJB+LBoOpEhn4HoRF4AEQAUVWDEQC30taS2Nr4AcqAA5MIAHKQCS1oIqADyXzI70Exa0kCOqEcClc0jwoCcqZ0wyw+hQCEQ0OElxzEjT0REBg42IWTFYDu4QRKQA)

### 💻 Code

```ts
type Foo = {
  bar: number;
};

let arr: Array<Foo> = [];

arr[3] = {
  bar: 1,
};

const foundValue = arr.find((e) => e.bar === 1);

```

### 🙁 Actual behavior

TypeScript doesn't indicate that find has unique functionality among the Array.prototype methods in that it does not skip holes in an array. This seems to be [intended behavior](https://stackoverflow.com/questions/42103761/javascript-array-find-has-problems-with-sparse-arrays) from what I have seen.

### 🙂 Expected behavior

TypeScript should mark that `e` could be of type `Foo` or `undefined`.

It doesn't make sense in my opinion to type `arr` as an `Array<Foo | undefined>` if it is known that you will never explicitly insert undefined into the array. Other javascript iterator functions like `forEach` will only go through the single defined element of `arr`, so the line `arr.forEach((e) => e.bar ===1)` would not throw a runtime exception. However, typing the array as `Array<Foo | undefined>` would result in a TypeScript error on that forEach statement.

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't acknowledge the existence of sparse arrays; this particular function is only one of many which can get you into trouble. e.g. given the `arr` above, you could write `for (const e of [...arr]) { e; }` and have the same problem.

**Comment by ChrisMcD1** [comment]
Oh, okay! Thank you for informing me.
