### ISSUE TITLE
Inferred type parameter is too narrow with strictFunctionTypes enabled and branded types

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#49924]
# Bug Report

### 🔎 Search Terms

strictFunctionTypes inferred type parameter too narrow branded types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVxlATwGEBDAZxgB4AVAeSXlBmBQBMy5qBJFAGk55wAvHBIoCAPgAUANxIAbJMABcA3AB84qVsASYUwVv2YVVshUtXcUASmES4cxcDiYOdBjav14m7bv1DAG4AKFBIWERUDGxcfGJyKmppJ0tOY2BTOHNnKzshBwAjCAh5YDEvTjg-NgCDVlDw6HhkdCwcPEJSChoUixV0vEyYM1SB6nyikrKKq2qtWr16uABvELgNuChgGCQoXDG4AEIhEX8lwzgAMiuhihylOwB+R364VXPAhpCAXxCQtA4ChwFhIAC2cAAygQUDASCAANL6VirdabIjychkACi4G2ZDIsV4aI2GKxkLhzDBLBgxL+IX0zCgCBIaBcADkIDpUZs4ABrZGqaGw+FItihemM4DM1kuCkkKk0kEgZhsDic7lrXkAfQoCuA1NhACEoGJWKoxAQJf8pTK2XAyQTcWB8YSOkwWOw4BqXFrNgK2EKYXDEciAHSOnF4zJulDWhmw6Us+2R+WK2HK1VetMGpV+jYB81Q4Oi8Opym52HxmAEMAuSMAGUwfJcIkjztdsXm5f1hpgoRCOjQmO2UTaXbcjebwCkKC5Ax9lTn3LcDsxBKbLYHQ5HLkBKGBevTIyhFb780+9QH++BYJIBEKwB7x+EnQS9yPldprjIU5bNlCG94DvB8n3XMgcz7AAmV94m6Kg-2AfgfWkT8+34SdwM3YAAJCIA)

### 💻 Code

This is basically what I see in the TS repo.

```ts
export function tryCast<TOut extends TIn, TIn = any>(value: TIn | undefined, test: (value: TIn) => value is TOut): TOut | undefined;
export function tryCast<T>(value: T, test: (value: T) => boolean): T | undefined;
export function tryCast<T>(value: T, test: (value: T) => boolean): T | undefined {
    return value !== undefined && test(value) ? value : undefined;
}

const enum SyntaxKind {
    ClassExpression,
    ClassStatement,
}

interface Node {
    kind: SyntaxKind;
}

interface Statement extends Node {
    _statementBrand: any;
}

interface ClassExpression extends Node {
    kind: SyntaxKind.ClassExpression;
}

interface ClassStatement extends Statement {
    kind: SyntaxKind.ClassStatement;
}

type ClassLike = ClassExpression | ClassStatement;

declare function isClassLike(node: Node): node is ClassLike;

declare const statement: Statement | undefined;

const maybeClassStatement = tryCast(statement, isClassLike);
const maybeClassStatement2 = tryCast<ClassLike, Node>(statement, isClassLike);

```

### 🙁 Actual behavior

The second type parameter to `tryCast` is inferred to be `Statement`, which is too narrow.

### 🙂 Expected behavior

The inferred type should be `Node`. This helper is used in the TS repo, but can't be used in some conditions because inference is wrong.

**Comment by ahejlsberg** [comment]
This is working as intended. We infer the more specific `Statement` type for `TIn` because it satisfies both occurrences of `TIn` (the co-variant occurrence in the first parameter and the contra-variant occurrence in the second parameter), and we infer `ClassLike` for `TOut` based on the return type of `isClassLike`. `TOut` then fails its `extends TIn` constraint check because `ClassLike` doesn't extend `Statement`, so we default to the constraint, `Statement`. You need an extra type parameter to make this all work out:

```ts
declare function tryCast<TOut extends T, TIn extends T, T = any>(value: TIn | undefined, test: (value: T) => value is TOut): TOut | undefined;

// ...

const maybeClassStatement = tryCast(statement, isClassLike);  // infers tryCast<ClassLike, Statement, Node>(...)
```

**Comment by jakebailey** [comment]
Cool, I'll give it a try on my branch.

**Comment by jakebailey** [comment]
Unfortunately that has a bad interaction with generic type guards.

For example, this also from the TS repo for our parenthesizer rules:

```
declare function cast<TOut extends T, TIn extends T, T = any>(value: TIn | undefined, test: (value: T) => value is TOut): TOut;

interface Node {
    kind: number;
}

interface TypeNode extends Node {
    typeInfo: string;
}

interface NodeArray<T extends Node> extends Array<T> {
    someProp: string;
}

declare function isNodeArray<T extends Node>(array: readonly T[]): array is NodeArray<T>;

declare const types: readonly TypeNode[];


const x = cast(types, isNodeArray); // bad: NodeAray<Node>


declare function oldCast<TOut extends TIn, TIn = any>(value: TIn | undefined, test: (value: TIn) => value is TOut): TOut;

const y = oldCast(types, isNodeArray); // good: NodeArray<TypeNode>
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzCgGcMAeAFQHlkN4QAPDEVYI+cgGnYEl8GmWbTu3gBeeFFQBPAHwAKAG5QIyEAC4e+AD7w0oRFlQhgXJiQ2LlqjeQCUYmfCUqEWIdQy2bHgNwAoP0MmGEQoMAQAORxQeABvP3hE+ABrQ2ANVGQAWwAjEBh-AF8AoPzQ8PYpAAcQKJj+ZlZ4OoR4pPgMapBeRBwNEhhDAHMiktRg8sjokABBGBgoKQo6Rka2FscGwXg5haXyRzakohwskAAFGBwq-oxB1BG-Yr9QSFgEFHRsPHg3Ft3Fsstk0NnJYHsNHAoMA8BApOwANoAXS8Enmi1+62mAP2Mn8L3A0DgBDwJA6XSIkJA0Nh8PIXRayPxfjApNo9DEBGIGDknRqRC4f2x6Kktn8AHpxe0AHoAfgCBLexM+mFw+BwEGAAGFuRQPCsBE1yLwuMb8OJJLJLC4bLx4Do9CADEYTB0QOZ4NbrJp7KJHM5VJj2B5UVQaPjWagyfDxBrtdzeRTBUR-iKxX5JTL5UA)
