### ISSUE TITLE
Array.prototype.includes

### ISSUE THREAD

**Issue by aaronshaf** [Microsoft/TypeScript#4992]
The proposal is in "stage 3 of the TC39 process"

https://github.com/tc39/Array.prototype.includes

**Comment by mhegazy** [comment]
PRs are welcomed. We will need to create a new es7.lib.d.ts along the lines of https://github.com/Microsoft/TypeScript/blob/master/src/lib/es6.d.ts

**Comment by mhegazy** [comment]
thanks @YuichiNukiyama!
