### ISSUE TITLE
Why does `Object.values` return exact property types?

### ISSUE THREAD

**Issue by iyegoroff** [microsoft/TypeScript#49921]
# lib Update Request

## Configuration Check

My compilation *target* is `esnext` and my *lib* is `es2017`.

## Missing / Incorrect Definition

`Object.values` returns exact property types instead of `unknown`s. This leads to errors in runtime.

## Sample Code

```ts
type Foo = { x: string, y: string }
type Bar = { x: string, y: string; z: number }

// 'x' is considered a 'string' here
const processFoo = (foo: Foo) => Object.values(foo).map(x => x.endsWith('1'))

const bar: Bar = { x: '123', y: 'abc', z: 10 }

// throws "TypeError: x.endsWith is not a function. (In 'x.endsWith('1')', 'x.endsWith' is undefined)"
processFoo(bar)
```

[playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/C4TwDgpgBAYg9nKBeKBvKAPAXFAzsAJwEsA7AcwBooQd9jyoBfAWAChRIoAhAQwOTSZahUpWrD6ZANxQAXjhIBXALYAjCPxas2Aeh1QA5BgNQiuKAGM4JXEQAmGiHcN1RJgBaO2Vm8ChgCOAsIXFx4RBQACgAzBBxwgEpkAD4oAHlVACsIC2AAOgA3HgAbRRCYhAS85R4wSIwUzDyIEjtcAHUiYHdIgwBGAwSEtm9rfChVPhxefhR0bEM+gCYAZgMqGkMeVQt1uRw+gAYmEdY9KG7AgHdzACIAFXAIAFECQIIcDGbWjq73U3MJDgfh4UGiihIuSI1jyUEiAEkSIYvi02p1ur0Bgk9kZvmi-iYzFAIQ5oqQnAlbmwAkEQmEEJFJgQEkA)

## Documentation Link

not related

**Comment by MartinJohns** [comment]
See #38520.

**Comment by iyegoroff** [comment]
Thanks for the quick reply!
