### ISSUE TITLE
Allow ".ts" in include/require statements.

### ISSUE THREAD

**Issue by tracker1** [microsoft/TypeScript#49926]
# Suggestion

In order to align with Deno usage, as well as potentially future support for a browser loader, it would be beneficial to be able to include files with the `.ts` extension included.

The option should be able to be configured. When enabled output of ".ts" extension should be omitted on the output. 

If a module reference begins with `http:`, `https:` or `//` then the default behavior should be left in place. Possibly use separate option to download/process such modules placed in `(outdir)/_cache/https__www.foo.com/path/to/mod.js`.  where the protocol followed by two underscors is presented... preference for https, fallback to http in case of `//` at the front.

There's a pretty deep rabbit hole this could go down... that said, it would be really nice if it were easier to support Deno along with node and browser, and this would go a long way toward doing that.  Since Deno can reference project code directly in typescript, it would allow projects to be Deno first, but still allow for build targets for node and browser usage.

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- deno
- ".ts"
- extension

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
#38149?

**Comment by tracker1** [comment]
@MartinJohns thank you...

**Comment by tracker1** [comment]
While there are other references.. the #38149 was closed along with other mentioned issues.

https://github.com/microsoft/TypeScript/issues/38149#issuecomment-1185887354

To me, given that part of the purpose of TS should be to support browser usage, that explicitly requires an extension... it makes far *MORE* sense to include the output extension for files that TSC processes, not less.  Just because it's easier to ignore the issue, does emphatically *NOT* mean it's not an issue.  In fact, TSC should *ADD* the extension where none was specified but it will be transpiling the referenced location via magic extension detection.

**Comment by MartinJohns** [comment]
> the #38149 was closed along with other mentioned issues.

No idea what you're talking about. It's still open.

> TSC should _ADD_ the `.js` extension where none was specified when it will be transpiling the referenced location via magic extension detection.

Rewriting paths has come up again and again, and the TypeScript team called this a huge no-go. Just check this issue: https://github.com/microsoft/TypeScript/issues/49083 This is also something different from your initial issue.

**Comment by tracker1** [comment]
@MartinJohns it's pretty much the same issue... Being able to use the `.ts` file extension and outputting `.js` for reference where the reference was outputted with a different extension.

Those is for better compatibility with the browser and deno, while it also would not break node.

**Comment by DanielRosenwasser** [comment]
We're not likely to transform paths, but the closest thing we may be considering is https://github.com/microsoft/TypeScript/issues/37582.
