### ISSUE TITLE
Improvements to "Upgrade project's Tools Version" dialog in VS

### ISSUE THREAD

**Issue by lvita** [microsoft/TypeScript#4993]
For solutions with multiple projects, it would be useful to get the name of the offending project.

Even better, to offer the option to remove the TypeScriptToolsVersion tag from the .csproj, rather than updating to the latest.

**Comment by paulvanbrenk** [comment]
My current thinking is to make this a single dialog for all the projects in the solution. Do you think you'll always want to update all projects in a solution or do this one project at a time?

**Comment by lvita** [comment]
All projects would be best ☺

**Comment by RyanCavanaugh** [comment]
Closing due to lack of other interest
