### ISSUE TITLE
Type resolver does not follow path aliases of installed modules

### ISSUE THREAD

**Issue by ngregory-rbi** [microsoft/TypeScript#49940]
# Bug Report

The type resolver does not follow path aliases of installed modules, instead simply typing anything that relies on a type imported from an alias as `any`.

### 🔎 Search Terms

resolver
paths
module

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about paths.

### ⏯ Playground Link

N/A

### 💻 Code

Repository: https://github.com/ngregory-rbi/tstest

### 🙁 Actual behavior

Both types have the same shape.

### 🙂 Expected behavior

`FooBar1` is typed as `any`.

**Comment by RyanCavanaugh** [comment]
TypeScript is doing what you told it to do. What you have here is a single compilation unit controlled by the root tsconfig. `tsconfig.json`s in intermediate directory paths aren't even looked for.

**Comment by ngregory-rbi** [comment]
> TypeScript is doing what you told it to do. What you have here is a single compilation unit controlled by the root tsconfig. `tsconfig.json`s in intermediate directory paths aren't even looked for.

Understandable. However, this seems to indicate that anyone wanting to publish a TS library will have to get rid of all the path aliases if they want it to be consumable. Feels like one more thing that necessitates compiling TS first. I don't entirely mind, I just do thing it would be a cool feature.

**Comment by RyanCavanaugh** [comment]
Correct. You generally shouldn't use path mapping in a library context unless they're the kind of maps that your consumers will necessarily have (e.g. installed modules).
