### ISSUE TITLE
Comments are not indented properly in switch case statement

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript#4995]
Expected:
```typescript
switch (node.kind) {
	case SyntaxKind.ClassDeclaration: return SyntaxKind.ClassKeyword;
		if ((<MethodDeclaration>node).asteriskToken) {
			return SyntaxKind.AsteriskToken;
		}
		// fall-through

	case SyntaxKind.PropertyDeclaration:
}
```

Actual:
```typescript
switch (node.kind) {
	case SyntaxKind.ClassDeclaration: return SyntaxKind.ClassKeyword;
		if ((<MethodDeclaration>node).asteriskToken) {
			return SyntaxKind.AsteriskToken;
		}
	// fall-through

	case SyntaxKind.PropertyDeclaration:
}
```

**Comment by vladima** [comment]
Copying the [note](https://github.com/Microsoft/TypeScript/pull/4994#discussion_r40518517) from the original PR that raised this issue:

> technically it is a leading comment for case clause, not a trailing comment for a block. Current behavior is preferable for cases like the one below. Here I definitely don't want comments for cases to be aligned with statements in previous case clause.
```ts
switch(a) {
    // handling Value.A 
    case Values.A:
         break;
    // handling Value.B 
    case Values.B:
         break;
    // handling Value.C 
    case Values.C:
         break;         
}
```

**Comment by zhengbli** [comment]
Then it shouldn't be a bug. Though the `case` statements feel kind of like a block, and in blocks the last comments preceding the closing bracket are indented the same way as other elements in the  block.

**Comment by mhegazy** [comment]
The problem is it is hard to know the intent,  i.e. commenting the next case label, or the last line in the block. the simple solution, either way you park it, will break one group of comments.

**Comment by DanielRosenwasser** [comment]
Wait why is it a leading comment for the block? It's not immediately above the `case` clause
