### ISSUE TITLE
Empty Object type hides other types when mixing them with statements or expressions

### ISSUE THREAD

**Issue by pyBlob** [microsoft/TypeScript#49952]
# Bug Report

### 🔎 Search Terms

- object hides string, inferred return type

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried. The documentation does not say what should happen when {} is combined with other types during control flow inference.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKgBAIgpgZglgOzgFzgewQZzCYAoPYYMNAawC4wAiAIzRqrwGMNNkw6bLb6qwBeap0aFiZSgG8Avs1bsoAWwAOyAJ6SpAsNIJESFbZoA+Q3njVKoYAEIB5LTwZgTO0fo3PTDc6stgAKnZaFlBoMBz0niFhYIoqqrpiBo6MIWAAGoH2ggCiAB7IAE4AhkzIADxZADRgbIWIAOYAfLrgAKqYjWDFhSWqOPhuNMUAJhoA2gC6NZgAFmgArgA2IxxQlAAU0p4pAJRTsljsPX1a45w1cWqTiRyjGjPzy6s064Y7wj5+AILBvqHhE7FVTjBALBSvQo3Ib3MAIKAANyghUeixWa24nzS6V+uQKJTK5WigN6wNB4Mh01qRUaLRhY0MU1RzwxYA2EGKyCsLik+xuemsoxqryYxQWmCsqkWYFFCGpcCWSzAhSgLCRhUgnLeG2KAAZxogRlA8pMwIg2MUEEwAZqubszcolnAoNhkLNOWb2Crior+nBsMVbVBDmxurqzvCAO5Bja7S7Ka63cRs7YmDl2g5pb7hwTsrWeaR827DBnSJm1J7o16bVNgAAsACY+TU0BqtsY4RTkUWWEdugBGM6N+PxaF6ZPtzyNotZwe52vTg5uZNl-nEWykYWqsUStlUEKYJj1FR8RDdBsGhBGk32kZoF1wtDsOCO-puj06i+G42TAB0B6POAVAEfhBCoQo0CYUhMCoXYQ2OBszgkMAAOPZBuAgqCYLAKQR0TZcDEnFwUP+Q80IwyDoL4XlM3+MBvkQ+cSMsMigPQ6hMKonCCxosd2k6BAGjNcJcAIGAFitVAMGE74ynQBANgQYoFBdSg6DQJYoEte0JDwMB9OEtklJUzAdL0gyLJVZAFkKOVOHM-TNCgJZd10izLKgazbPeYpsF7NgHJwvAZHpB4KzRF43lrFIvisABJLQACVPJshB-H+Il-hiOAYFkqSEDpPQS0oeF1WZKs3hi7EErxIpSgqZKvLSjLiRkuSMCaGYaUEwr+K6TBIxQJhZgAWlFXcAGoZR9JVkDQMBxMk+S2UwZSrBVTBlnYSNZigOURjgFUyiWforNSlDdplORLWQUyBgIY0lFbdgs3auVBAAOTW7ATAAGWKV4lgevInsKF66K+kyHEhl0REe57mKsf7AYcZHnJERa3u6N6dTeyg8vksyAEgBqG2Y2XqwntDwImifGqwqBhmDyBp2mzu8ymMCZ3H8rg2n6eoNGlioFnaaJ9m5U5hAhZ5wmaZkELMfy7H8u5qXKCZ4mJYiGhgrEiSsalmX1bAIWtZS7yrgSELx2SLEIaSi3mssTLLBiKWmcKpINFi03Haa9KXdao2Aecr27lLXDwpZat3hMKq6MS-3UsDqBXZtKXw+KuFEWRcrIsxMxsQAZS0fI6sJRqU5arLATezrqXqHq8CAA)

### 💻 Code

Definitions:
```ts
// ok: "bob"
const bob: "bob" = "bob"

// ok: {}
const empty: {} = {}

// ok: {} | "bob"
type BO = "bob" | {}

// ok: {} | "bob"
type TBO = typeof bob | typeof empty

// ok: "bob"
type XTBO = Extract<TBO, string>
```

Using Array:
```ts
// bad: {}[], should be: ({} | "bob")[]
const array = [bob, empty]

// bad: {}, should be: {} | "bob"
type A = typeof array[number]

// bad: never, should be: "bob"
type XA = Extract<typeof array[number], string>

// bad: {}[], should be: (Date | {})[]
// Bad, because you can still recover Date: (a0[index] instanceof Date) implies that it really is a Date
const a0 = [new Date(), empty]

// ok: ({} | Date)[]
type A0 = (Date | {})[]

// bad: {}[], should be: ({} | 42)[], or ({} | number)[]
const a1 = [42, empty]

// ok: ({} | 42)[]
type A1 = ({} | 42)[]

// ok: {}[]
// Ok, because ("typescript" in a2[index]) does not imply that (a2[index].typescript === "rocks")
const a2 = [{ typescript: "rocks" }, empty]

// ok: ({} | { typescript: "rocks" })[]
type A2 = ({ typescript: "rocks" } | {})[]
```

Using if:
```ts
function ifAction(names: boolean) {
    if (names) {
        return bob
    } else {
        return {} as const
    }
}

// bad: {}, should be: {} | "bob"
type I = ReturnType<typeof ifAction>

// bad: never, should be: "bob"
type XI = Extract<ReturnType<typeof ifAction>, string>
```

Using switch-case + call to function (same result when directly return the constants) 
```ts
export type Action = Names | Label

export type Names = "Names"

export type Label = "Label"

function action(action: Action) {
	switch (action) {
		case "Names":
			return actionNames(action)
		case "Label":
			return actionLabel(action)
	}
}

function actionNames(action: Names) {
	return bob
}

function actionLabel(action: Label) {
	return empty
}

// ok: "bob"
type N = ReturnType<typeof actionNames>

// ok: {}
type L = ReturnType<typeof actionLabel>

// bad: {}, should be: {} | "bob"
type R = ReturnType<typeof action>

// bad: never, should be: "bob"
type XS = Extract<ReturnType<typeof action>, string>
```

### Actual/Expected behavior

It should not hide the string-type, see comments in code

**Comment by MartinJohns** [comment]
This is the expected subtype reduction behavior. Note that `{}` does not mean "empty object type". It means any type except `null` and `undefined`.

**Comment by pyBlob** [comment]
Right, as everything except `null` and `undefined` is an object in javascript, this actually makes sense.

What doesn't make so much sense, is that typescript does not always do the reduction, e.g. when explicitly taking the union of both types like in the `TBO` type above.

As a second thought, the same reasoning should apply `{ toString(): string }`, which it does most of the time. Inconsistencies only get worse/change when adding generics into the mix (see type-hints / .d.ts outputs):
[Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gfSQIwCtwMAueAbwF8BYAKFElgWXS20xgEsUBzMj7jzoNocRKkw4UAVwC2eEDDIz5i4eFHMJbYFAwgyAET0h1jMS0nYMSAMoYuvMuXg37jngAoAlPweD4Glo6DABPAAcEMMi0eABeCjp4ZJx8IjBSVwiQJAAzVMJiABoklPZ-JyzIvJwBXhLaFKk5BSUqnPzsFVaGpuxdfTJojpwBkF6ytwq+dprrO2mGoOH4ABUAUQAeVYA+eMTGlIBtAGsQUPhueDPQmuG0AF0yVfgQAA99FGBY+9Pzh-gAH5XDBpAgyLkoBA0KZaMtsgV0hhsO9Pt99htNsM5mliDsQgjyh4UR8QF9YglMdjOnUePjaCsui1FCS0RS1ltqc1VDB6YyxqyyejKZzsnMxnzCVNiaiheyqWLOtLBPS6LlpCgMpxUPBZIoeCBtjtPAA3KFg57eA5NOAYaQwFDWpplXEZMhHM0QMFFRHEB4+gD0Ad1+pAwHgXB4AAssFAAO5QC4AWgAdEnSs7atN3Z7vVmPP6M86mTyc+bxtzWoXDpn+iYy16K3X9NXM8l5u5BA28x3pv74EGQzADeHIzH4PHE-BU+ma4E6EFLGxXci9cOEAk1wbPLhChlvHQl-nBNgtxuh9uiYID7QjyXWqfQ-szzvuoob3eBWfn6Gd2MP9oODKrwj7rj+647sBPA3oegG7kioEGgAjPs5BFvBxDuhhGQ+thGCtmUtJYSuuG0gR7Zvm0Rx4bhlHkaM9bwNRJEMS2EztlBxF7hguFQdWi5wbSiEgChCRoXOeFYbSuErvRV6VNR0nHrwcmUVJiyVoocljOpHi4WMcmcUx8k8LxCwFkssGsJpMDCaJTrtiuWGUTJ3FyURxkucpPCqcyVH3ootF+dpjHUV5zYgIZ5ldp5flmZ2KmWbecFfqG9niX0TnGWMrlIu52bZSYpF9uxNlYTlNkhYMhX6PpJhRQlMzURVvYWQuVlWFBdmoehWXUVBuV+qVJlYQN3m+aWxljQFMBVQYU3RfUrGRcNRn9YtplARt-F0EAA)

**Comment by RyanCavanaugh** [comment]
Subtype reduction happens "sometimes" where "sometimes" is largely determined by performance constraints. It's never *wrong* to subtype-reduce so any observed behavior is from an equally-valid set of behaviors.

**Comment by pyBlob** [comment]
> It's never wrong to subtype-reduce so any observed behavior is from an equally-valid set of behaviors.

I agree. I tried expressions `[a, b]` and observed the inferred types:
- Only those expressions where the type of one variable is a proper subtype of the other have been reduced to a single type. After looking at those cases, this really prevents errors.
- For other cases, the item type of the array was the union of both types.
  - When there is a discriminant property, you should be fine.
  - When both types only overlap without a discriminant property. By definition, it is only safe to use common properties. There will be dragons when you use conditional types or control flow analysis on properties defined only in one of the types. It would definitely help, if the effective type would be more general -> only allow to observe and type-filter on properties common to both types (like with member access).
