### ISSUE TITLE
Reassigning a value removes the evaluated type.

### ISSUE THREAD

**Issue by infacto** [microsoft/TypeScript#49954]
# Bug Report

### 🔎 Search Terms

typescript reassigning a value removes the evaluated type typeof

### 🕗 Version & Regression Information

Not sure, I just see this now and use TypeScript 4.6.4

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.6.4#code/MYewdgzgLgBADgQwE4QKYGUQFtVQBYCWYA5jALwwAUAbggDYCuqAXDA2ANZggDuYAlKzAMsAI1RJyAPhgBvAFAwlMAgDMqUAJ5xUIdbUapyZCgHJhYiaf5zFy+0lwMkYGAaYBuO0oC+87yrqlFo6em70TDAAhCYwptBIRMTWtvYOTi4wAHIIWV72fgHuRhTFMAD05TAAdI5wdAjAqJSmADRtcdXWXgGOUM6uiCioAGJ0IAhQNBGo-F5+QA)

### 💻 Code

```ts
const parseSomething = (value: unknown): number => {
    if (typeof value === 'number') {
        return value;
    }

    if (typeof value !== 'string') {
        return NaN;
    }

    value = value // .replace(',', '.');

    return parseFloat(value);
}
```

### 🙁 Actual behavior

Behind the typeof checks, the type of `value` is `string`. But assigning the same value again replaces the type to the initial type defined above on declaration. 

> Argument of type 'unknown' is not assignable to parameter of type 'string'. (error 2356)

### 🙂 Expected behavior

The `value` is string at this section. Regardless of self asign. Use case, for example: 
We ensured a string type by type-guards and just want to replace it with the method `replace` which also returns `string`.
Regardless of the method, using `value = value` replaces the evaluated type.

**Comment by MartinJohns** [comment]
Duplicate of #42821 / #27706. Used search terms: `unknown reassign`

**Comment by infacto** [comment]
Sorry, yes it seems to be an duplicate.
