### ISSUE TITLE
Using a literal constant that is not declared using "as const" widens on use

### ISSUE THREAD

**Issue by pyBlob** [microsoft/TypeScript#49953]
# Bug Report

### 🔎 Search Terms

- inconsinstent type hint, const declaration, const literal is widened

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/PTAEHsGsC5QIgEbgQBjgKAMbgHYGcAXUJVUAXnhLXXRAhkuQEYNt8iSnzGEXQBDPKDaEadKLETIATK1yFiMySVncpCWWLATQAZizyiOAK4BbXd321tDddQIBPAA4BTUARTdHr8ADNFqFr0yswY3m4EXBThfgFMQTrqmuHu0l7OLrEqCQz6KQQW0RmxJuZBCPwAJrAA5L7GOJgEAJa4oL4oABQAlLCEAE7NOADmNQA0oHgAFuDGADaVxC619Y0tbR09IahwNeirTa047V3doADeoP0uBMb9x1SgAL45Kw2HG0xbPCx7B+vHXxfM6Xa63e5xZ6vUB1d4A9rSb5JXb7OFHBE9C5XG53B4yKHWUDEKpvNbo3y6b6lBAufrjSYzeaLGmkj6Aym9PR-NEbDlYsG40ClCwvQkVaqTAiDEYAbQAuhNprMFkttmh5RNwP1QDK7HA5QZ2AJPBQZVQDYTElQ4PLDQp+FEdZwDUA)

### 💻 Code

```ts
// ok: "bob0"
const bob0 = "bob0"

// ok: "bob1"
const bob1 = "bob1" as const

// ok: "bob2"
const bob2: "bob2" = "bob2"

// ok: 3
const num3 = 3

// ok: "bob0"
type t0 = typeof bob0

// ok: "bob1"
type t1 = typeof bob1

// ok: "bob2"
type t2 = typeof bob2

// ok: 3
type t3 = typeof num3

// bad: 'function f0(): string', should be: 'function f0(): "bob0"'
function f0() { return bob0 }

// ok: 'function f1(): "bob1"'
function f1() { return bob1 }

// ok: 'function f2(): "bob2"'
function f2() { return bob2 }

//  bad: 'function f3(): number', should be: 'function f3(): 3'
function f3() { return num3 }

// bad: string[], should be: "bob0"[], or ["bob0"]
const a0 = [bob0]

// ok: "bob0"[]
const a1 = [bob1]
```

### 🙁 Actual behavior

Note, how the literal constants that are not explicitly declared using "as const", or ": <type>" are widened on use. This is really unexpected, because the type-hint (when hovering the constant name) shows the literal type in all cases.

Note, that the emitted .d.ts also differs:
```ts
declare const bob0 = "bob0"; // assignment instead of ": <type>"
declare const bob1: "bob1";
declare const bob2: "bob2";
declare const num3 = 3; // assignment instead of ": <type>"
declare type t0 = typeof bob0;
declare type t1 = typeof bob1;
declare type t2 = typeof bob2;
declare type t3 = typeof num3;
declare function f0(): string;
declare function f1(): "bob1";
declare function f2(): "bob2";
declare function f3(): number;
declare const a0: string[];
declare const a1: "bob1"[];
```

### 🙂 Expected behavior

The constants bob0 and num3 should emit the same code and behave like their cousins "bob1" and bob2".

Does fixing this behaviour cause `[bob0, bob1].includes(bob2)` to be a type-error, because the array is inferred to be of the specific types?

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. A good explainer is at https://mariusschulz.com/blog/literal-type-widening-in-typescript

**Comment by pyBlob** [comment]
I see, so it is really for those uses that require the wide type: e.g. for array mentioned above `[bob0, bob1].includes(bob2)`.

Then I amend my expected behavior:

The type-hints for bob0 and num3 should be more obvious, they should tell explicitly that references will widen on use.

Possible options for bob0 and num3:
1. "const bob0: string", and "const num3: number"
This makes it clear, that using those variables will introduce the widened types. However, it hides the fact, that you could use them without a cast.

2. Match the declaration of the .d.ts, `const bob0 = "bob0"` instead of the actual type hints `const bob0: "bob0"`
This is really suble and easy to miss, but at least it is there.

**Comment by pyBlob** [comment]
Your explainer also referenced the implementation + duplicate:
- https://github.com/Microsoft/TypeScript/pull/10676
- https://github.com/Microsoft/TypeScript/issues/10938

**Comment by pyBlob** [comment]
1. Aren't the type hints that are shown in the IDE merely user-facings outputs?

>  > Match the declaration of the .d.ts,
> 
> This would be a fairly large breaking change without much concrete upside IMO.

2. I still think that this silent widening is a bug. Though, would you consider a pull-request that adds a small section to the literal types/inferenece that details the widening?

Reading through the docs again, this is lightly mention in (literal types and literal inference): https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types
At least it gives another example, why you would want the widening behavior.

My concern is, that the given examples show that "let" does the widening immediately:
```ts
// let changingString: string
let changingString = "Hello World";
```
While "const" initially preserves the literal type:
```ts
// const constantString: "Hello World"
const constantString = "Hello World";
```
It does not mention that the preserved literal type is widened silently on use (requiring explicit the "as const", or ": <type>").

The section on literal inference actually shows an example and three workarounds to preserve literal types. Note, that in the initial example, the type of const is already widened:
```ts
// const req: { url: string, method: string }
const req = { url: "https://example.com", method: "GET" };
```


The sentence  `It’s not much use to have a variable that can only have one value!` only presents one side of the coin. It's true that a *variable* (var/let) should be able to change values. However, it is also important that *constants* are literally constant, which is a good thing. This allows you to refer to the constant by name instead of the value behind the constant. The added documentation should mention that if you intend to use constants that way, you have to add "as const", to prevent widening.

**Comment by RyanCavanaugh** [comment]
> Aren't the type hints that are shown in the IDE merely user-facings outputs?

Yes. In that context, we think that, on net, showing this information would create more confusion than it would remove. There are many more subtle facets of types out there that are hidden from the "quick info" view.

> I still think that this silent widening is a bug. 

It really really really isn't; this behavior was added on purpose. The motivating scenario looks like this, which should have zero errors:
```ts
const DefaultUserName = "mylogin";
acceptMyLoginOnly(DefaultUserName);
const names = [DefaultUserName];
names.push("admin");

function acceptMyLoginOnly(n: "mylogin") { }
```

The docs you linked are meant to be an introductory overview of the concept space without explaining every possible nuance; the omissions you pointed out are largely intentional for the sake of brevity.

**Comment by pyBlob** [comment]
Well, so lesson learned is: Use "as const" in the definition when you intend to always keep the literal type (e.g. for kind properties).

Thanks for your time and fast responses.
