### ISSUE TITLE
Incorrect inference when using the `return` keyword in an identity function, or when using an optional argument

### ISSUE THREAD

**Issue by ShayDavidson** [microsoft/TypeScript#49951]
# Bug Report

I'm running into very weird behavior when using identity functions. I'm writing a wizard system with schema (attached is a playground link with a very simplified version), and using constrained identity function to get inference.

The problem occurs in an argument of one property which is a function, when either of these occur:

- When the returned value from the identity function is using the `return` keyword (rather than a single-line return wrapped with parentheses). 
OR
- When declaring an optional argument in the identity function. The argument is declared in the type definition of the identity function, and when using `Parameters<typeof myFunction>` it's inferred correctly both when declaring the argument and when I not.

Both these issues are super weird to me, which means I'm either missing something very fundamental or I have found 2 rare bugs. 

### 🔎 Search Terms

Inference, Return, Arguments, Parentheses, Identity Function.

### 🕗 Version & Regression Information

This reproduces in all available playground versions (tried down to 3.3.3), and also in 4.8.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.4#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPigB6QVGT5i1AGbUIxKJML5kUItXp1UAG3lEowJFHKp20fJL0GIAD1TIwmiMylRqwKMXwRytAORu0JoYQtOQQAFBhoJCwwBBgAGJscMDU+LSkYVBQACrwSGhQ1rG0xOSwiCjoWHmVjGECWAAUqLQg+nT0AFysHFy8AJSYAgDemVCEEKgetJoghhVo3bkLqGMTU2mzevgAgiHcEITkAPzdjSYg5N0XZjk1aIMYAmycPLRhAL4RkkkpaYaxMCkZb5dBFYKlcqgzBQyp8RpjLKUOIANS03RggMStGSqXSILhdSy-QxWN+eOB91QI0R4wgwBYhFoANRWjGXzCwigAFEABo7ACyAAUADLcmBQABC3JFAHkAOqdTkiABy+BScGg+mgEwZTNkKgARgArPBuW5abQ-HF-EIuMrawy2CAAQhyBgkkkkh2CmrKqAmLloSq5AFooNwkNrCBHoCxQhZoAADXWM2hJqAXbhEOS6LhuRrHF1F-rKqDhyP0pAxg5QBCoABuWoMAfoLGQwTckl0jqTyLAGetuP+efVADooGrYhZUG5nABJdz4KBJoUB52xI6kKIQW7IECY1maFgQPgZiBN5mV5mO1vtzv20TUcjkDpOYA+Mp0b2ECZyAi-maWyNC6pZlvKsrYAA0jA3RJhc5AZs+QY-n+UCGqgoS5jeBh9isSZluGXBQHeHa0F2uh9oCg7kmkhFQMRKb0mmGZZjmYQECEbjZoQ7AdNyNh2A4ML9o0jSPAIjSjEiKzdNJWQkcAVDUIaLCxN0PgtG0CAdD4RJQB8+nALs+yHFcmYQJcQxQPJWRctg4oAKoitkcEIRm5AsHAmqyF+tA-r60CYSus7KapsQEQpejgNA2ReG4WCUDQDCFFYxSQjutwIVAxwMRehxQBpVAnj4tKcZQejxUs8Uwn4hAlbSqZMjZlUVV8WSGZ8-RgVy8Q7POIqwSu7mPvmKGHGhGFYSoOHJuQ+H0fW-qEG2ZEUTGVFxDRNp4hxaQVVwtDykQfEMDsImAo0AD65BKFWHTWVJYzzaCcm0qFNDhRAGlae0DB6eyRkmeQBxHNclllE8Nm0vZTkuW5EODqg1CaH5AU4tASAY+4ECSKgLCaMADrLlRyX0JFCk7jkNWJcpKXgiUDoxVlEM5XlTYxkV9UQKVUXlW4sSUNVFVYHVDVRU1zLDK1bjtQZdQfN1ES9f1g0I5cSFlGN34TQaU0Gv8vYvZUBFhnWwVMXq6YWSAPFyIQs7VjOzLoAARK+DAOKGkuu3SVsRq4CBQGAAadkgoTkHtXEMWkx28R0koXXEYkSdDWSS2nCnG4smdRR9Klqd9UCaa0f30ADUWdVFxl7CDZng1ZUO2QpsMwM5rnDYj8jI6j40TNjWOajjeME0T2wrklHQU9XMXUyLAJk6l6VM5ALNWbltD5ZzxfFTztJZPzMvCwlO-c7zUV+2mLWC7LtJVwZXVhEAA)

### 💻 Code

Probably better to check the playground for code examples, but there:

TYPES DECLERATIONS:
```typescript
type Schema = Record<string, unknown> // modified from original for the sake of the example, if it doesn't make sense

type StepFunction<
  TSchema extends Schema = Schema,
> = (anything: unknown) => {
  readonly schema: TSchema
  readonly toAnswers?: (keys: keyof TSchema) => unknown
}

function step<TSchema extends Schema = Schema>(
    stepVal: StepFunction<TSchema>,
  ): StepFunction<TSchema> {
    return stepVal
  }
```

EXAMPLES:
Notice the returned object of all functions is the same! The differences are in:
- whether we use the `return` keyword or not (?!?!)
- whether we have the argument for the `step` function or not. Note that if I do `Parameters<typeof myStepValue>` even when the argument is missing, it's inferred correctly (!)

```typescript
// WORKS: `keys` is inferred based on the `schema`
// - no argument for `step` function
// - no `return` keyword
const workingExample = step(() => ({
  schema: {
    attribute: 'anything',
  },
  toAnswers: keys => {
    // RESULT: `keys` inferred successfully as `attribute`
    type Test = string extends typeof keys ? never : 'true'
    const test: Test = 'true'
    return { test }
  },
}))
```

```typescript
// FAILS: `keys` is not inferred based on the `schema`
// - has argument for `step` function
const nonWorkingA = step(_something => ({
  schema: {
    attribute: 'anything',
  },
  toAnswers: keys => {
    // RESULT: `keys` failed to be inferred hence defaults to `string`
    type Test = string extends typeof keys ? never : 'true'
    const test: Test = 'true'
    return { test }
  },
}))
```

```typescript
// FAILS: `keys` is not inferred based on the `schema`
// - has `return` keyword rather than a "single-return" return with parentheses
const nonWorkingB = step(() => {
  return {
    schema: {
      attribute: 'anything',
    },
    toAnswers: keys => {
      // RESULT: `keys` failed to be inferred hence defaults to `string`
      type Test = string extends typeof keys ? never : 'true'
      const test: Test = 'true'
      return { test }
    },
  }
})
```

### 🙁 Actual behavior

Nested value's function argument cannot be inferred correctly.

If I change the property (`toAnswers`) from a function to a simple property, there are no inference issues.

### 🙂 Expected behavior

Nested value function argument should be inferred correctly regardless of the `return` keyword or declaring the arguments.

**Comment by ShayDavidson** [comment]
Possible related issue for the argument case: https://github.com/microsoft/TypeScript/issues/25092

**Comment by ShayDavidson** [comment]
If someone ever encounters this issue, found a temp solution!

By wrapping the returned value with an identity function, both the edge cases are working, see in this [playground](https://www.typescriptlang.org/play?ts=4.6.4#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPigB6QVGT5i1AGbUIxKJML5kUItXp1UAG3lEowJFHKp20fJL0GIAD1TIwmiMylRqwKMXwRytAORu0JoYQtOQQAFBhoJCwwBBgpAAq8EhoUNaxtMTksIgoqAIYAN5hUFCEEKgetJoghrloAFxQSfWoJWUVVTV6+ACCIdwQhOQA-E0AFCYg5E1TZs3JeQCUmAJsnDy0YQC+EVHQMLFgAGJscMDU+LSk7S0p6OnBWTn3mC95jGEFUOOotCD6Oj0JrrLi8FYYASHOKJRZoPgRSRnC5XQxHWGtNJWDLPOHoLB4vjjdqlShxU60c6XWgANS0TWhJ2R1Ix9z4n1KSwZRwpVKurLyAmKpVK5WALEItDR5OZVzpmnauzCSMpKKlZLAAEliMELqBeWqBalHplsni3oTiSLpWB5dyYXdBRyoFyYg7CVBhSKxRL1Ud5YqImFhFAAKIADV6AFkAAoAGVDMCgACFQ3GAPIAdQawZEADl8Bc4NB9NAfZLZCoAEYAKzwbnmWm0Kr5IRc2VLhlsEAAhM0DBJJJIhsFi9lUOUXLQcyGALRQbhIUuEBfQFihCzQAAG5doW6gU24RDkui4bnGIx7l6Wuag88XEGXq6gCFQADcSwYJ-QWMhdToV07LcNX3Fs1RUFczwAOigAtYgsVA3GcTV3HwKAtxjCdu1iYZSH2eZkBARl5RYCA+H3CAPylB8pU7b9f3-ahsmQJjyCBJxgB8bI6GHQhyjkAg+Prbpxh7G9b0zdNsAAaRgJotymch9yYqdeP4qAq1QUIT1ogxgNaLdb3nLgoHov9aDcSRdGAo5QNlLY5ygEyd0fX190PY8wgIEI3CPQh2CBUMbDsBw3g1cZxghARxi9chWiaL1SkQqhqCrFhYiaHw-gBBAgR8Z1tmdYA+gGIYZgPCBplWT0SSEERsETABVOMEnkxT93IFg4GLWRuNoXjR2gLT0OSmg0tiQzrX2ZovDcLBKBoBgsRxDtwAgeZFKgEYnMooYoEyqhSJ8WrvMoPRZqaBJZrePxCCO2rd09c6zt2UpCp2JZxJDY5ek1OM5PQ9r2ycwtVKGdTNO0lRdO3OL7kMxzX3HQgf3MyzrJA+R7K8q4zq4WhMyIAKGF6MKjnGAB9cglEfXKlshH5YvimrrVG1L0ogTLssBBh8sVIqSvIQZhlmSrsgZxK6pwJqWrasXQNQahND6gbKWgJA1fcCBJFQFhNGADs0Jsxb6EmkVpqus75pSpaTWefDzE27baF2lcDruiBjutU63FiShLuurBbvu61HsKZ63FeqB3u2T6Im+37-rl6ZlOyM8waEuRIcrVEgLhvIEZEeckfQ3d3Mqvy5EIRCkEA18pXQAAiNiGAcWdd0bjpxUlBdXAQKAwAnXUkFCcgcZ8kGCaJoFkzJuIIqilmu99JfSWZyWkuAFLxs5qAsv+Hn6D5613qmwXhfKzaJdq0oQwamBmtawH5fkRXlYzwaX0-nUdb1g2enQgtIEZspprRmlbNEJtlpPFWpADaYsto7Q-G7Peh1PY3ygD7COAcIHB3QdaUUrke7hz9pHWqp9o4fXjiISSMlNR5gAOJGRfMNMy-4rIrhsnEOyqpqTjzOn5Ym9BMx921LqVwIADTUlJtbeeVMaaH2quMDUYiLISKkVcGK7R86NFXqZLeY0OZcwPnTI+BUBb9CFmVUWVVr7WjvjLJ+CkX46yVirEcmsNbFi1r-fWhtAE21NrVC2gdIFAmgaaPQa14FVWdq7faqCPZexFFg0hOC5qJJDt6IhUoSHXSjjHT64ksGCKBCI-Qqi9SSPsrPWRYAF7VS9I9FROo1H6nslo60OjUAJQwWzHexicp5WdG9EZPRLEXxseLIUGCHEP1ls-FOr83Ef08d-bWus-EAONsAjBISIFANttiGBUS4GOwQXE5BCS8HJO9rjX2F1wEZJuRgsOEdKEnwKjeWOQA)

**Comment by Andarist** [comment]
Note that `nonWorkingB` might get fixed if https://github.com/microsoft/TypeScript/pull/50903 lands but `noWorkingA` still errors there

**Comment by Andarist** [comment]
I think that this [`noWorkingA`](https://www.typescriptlang.org/play?#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPgDcAKCGhIsYBDAAxNnGDV8tUgBV4SNFAgAPSbWLlYiFKj6YoACiFQoqWiGAI69AFysOXXkICUmMwG9rKEIIVGIlABsQKHJjNDc1ONRhGxCwyOjgfABBWnJuCEJyNwt2CBBiqDKQfAAzKESNVF8MMzZOHlphAF9hIWI8CNQQqFq5BSUYyTBVdRMtXQh9Qzm0PisbSikANVQItxhp2Vp5RWVGkz4fA6Pxs9mkwRECPOAoLloAdSJ2Z2zzLZgCwWAD6bBY5AgxFyxAAcvhgLghpJiCp8Bc0C0zBZApskm5cTZbMAqNQAEYsSRuABEdgcTgY1MYQW6zJsWVy+UKlVK5XIWKghJsAHphTgAKIwACqABkVG4AAbVcgK0aoagRKFQLJQMnQOi1QohYhQJAnaADWqoFgRYCGHUKyg0BgKoLs8DQFQQSgA0kMBZ6Azaj11Kp8qAAfneEAAboUoDSqCwINSUkSXj7JJQEt63lhqUmU2nUhBgCxCLRBdrc1Beizmd1vN5hEA) is worth a separate issue. It feels different (to me) than the other case. Ping me there and I can try to look for a fix.

**Comment by ShayDavidson** [comment]
Hey @Andarist! A year and a half later I've encountered `notWorkingA` again and now I cannot fix it with my temp solution described above. 

Would you like me to open a separate issue?

**Comment by Andarist** [comment]
This likely falls into the https://github.com/microsoft/TypeScript/issues/47599 bucket (just like Ryan mentioned above). So it might be hard to get this fixed (that umbrella ticket isn't trivial) but maybe some carveout can be figured out for your case here, I'm not sure. I might take a look at it sometime later - and a fresh issue would definitely help me to remember about this.

**Comment by ShayDavidson** [comment]
Thank you @Andarist - here's the followup https://github.com/microsoft/TypeScript/issues/57021
