### ISSUE TITLE
For-loop breaks control flow analysis - widening type that was narrowed

### ISSUE THREAD

**Issue by soanvig** [microsoft/TypeScript#49969]
# Bug Report

### 🔎 Search Terms

Google -> typescript issues for loop control flow

### 🕗 Version & Regression Information

It happens on every version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAIgqlAvFA3gWAFBSqSAuKAcgEZCBuTbAWwEMA7GgcwgCcDDaHmXzMBfKAB9UlHOAjsATLyxROTVgToBXADaqKGPph0YAxgHs6AZ2BQAZnSRQAFGBosaVAvACUSAHwjZhk2ZRikAA0cvQKLFACyPaOVJqiAJbmtrjQiOlE0u7ostgsEMDKLHSa2AK61GHcFRYGETaqBVAJ1gAMZM1QADxQAKwdCQDUg9naGKLy1eNaQA)

### 💻 Code

```ts
type DU = {
  type: '1';
  manager: 'manager';
} | {
  type: '2';
  manager: null;
}


const fn = (param: DU) => {
  const { type, manager } = param;

  if (type === '2') {
    return;
  } 

  manager // <-- 'manager'

  for (let i = 0; i < 5; i++) {}

  manager // <-- 'manager | null'

}
```

### 🙁 Actual behavior

The for loop (and it applies to `for-of` loop as well) breaks the control flow analysis, making type, that was narrowed, widen again.

### 🙂 Expected behavior

For loop should not modify already narrowed type if it's not modyfing the type in any way.

**Comment by RyanCavanaugh** [comment]
I don't have the issue offhand, but this was recently fixed. Works as expected in the nightly build

**Comment by soanvig** [comment]
@RyanCavanaugh thanks for the response. You marked this as duplicate: can you point me to the duplicated issue? It's not necessary though, if you don't know it :)

I will close this issue, as it was fixed.

**Comment by whzx5byb** [comment]
I think the duplicated issue is https://github.com/microsoft/TypeScript/issues/49772
