### ISSUE TITLE
`importsNotUsedAsValues` prevents importing an `enum` type to use only for declaring another `enum`

### ISSUE THREAD

**Issue by cpcallen** [microsoft/TypeScript#49974]
# Bug Report
### 🔎 Search Terms

importsNotUsedAsValues, enum, import type

### 🕗 Version & Regression Information

- This is the behaviour in every version (≥3.8) I tried, and I reviewed the FAQ for entries about `importsNotUsedAsValues`.

### ⏯ Playground Link

[Bug workbench link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?importsNotUsedAsValues=2&ts=4.7.4#code/PTAEAEFMCdoe2gZwFygIwGYDsaBQIIBLAWwAcEAXRAOTgoFVFIATAQUQDUBDAGwFdIKUDHjRcuEuWgVQAbwBicOAF9QAM3jFQAcgB0wNUt0ArRNoDc4yAA8pMyADs+WgEJdoc3KG+guoALyginC6XAA0Xj4AxgFBRlERPsKxAKwRyuIE4GqEPI5cxJCohiFUuDZ2wk5awZ5JfoFoiT4ARs3eCbgZQA)

Or paste the code snippets below into [the TypeScript Twoslash tool](https://www.typescriptlang.org/dev/twoslash/)—note that they do not work in the regular playground because (contrary to its own documentation) it apparently does not actually support twoslash markup.

### 💻 Code

A module which uses an `enum` `import`ed from another module in the definition of a new enum is treated as if it does not use the enum object, producing the error "This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'":

```ts twoslash
// @importsNotUsedAsValues: error
// @errors: 1371

// @filename: foo.ts
export enum Foo {
    a = 1,
    b,
    c,
}

// @filename: bar.ts
import {Foo} from './foo.js';

export enum Bar {
    a = Foo.a,
    c = Foo.c,
    e = 5,
}
```

On the other hand, if the `enum` is obtained via `import type` then the error "'Foo' cannot be used as a value because it was imported using 'import type'" is generated.

```ts twoslash
// @importsNotUsedAsValues: error
// @errors: 1361

// @filename: foo.ts
export enum Foo {
    a = 1,
    b,
    c,
}

// @filename: bar.ts
import type {Foo} from './foo.js';

export enum Bar {
    a = Foo.a,
    c = Foo.c,
    e = 5,
}
```

### 🙁 Actual behaviour

Neither `import` nor `import type` can be used to import an `enum` used only to define another `enum` when `importsNotUsedAsValues` is set to `'error'`.

### 🙂 Expected behaviour

The first example should not generate any errors, because it explicitly references the imported `enum` as an object.

Failing that, the second example should not generate any errors.  This would be confusing and counterintuitive because it depends on the (to me surprising) fact that the generated code for `Bar` does not actually reference `Foo` but instead directly inlines values from `Foo` despite `Foo` not being a `const enum`.  Nevertheless, it would be an acceptable since the error message from the first example specifically directs one to use `import type`.

**Comment by andrewbranch** [comment]
I think I `wontfix` this now that `importsNotUsedAsValues` is deprecated. Its replacement, `verbatimModuleSyntax`, implies `isolatedModules`, which implies `preserveConstEnums`, so the import is unambiguously used as a value and doesn’t error. It doesn’t seem worth making a separate fix for `importsNotUsedAsValues` that will only survive for two TypeScript versions.
