### ISSUE TITLE
New Website Logo: ubet.com

### ISSUE THREAD

**Issue by codeandcats** [Microsoft/TypeScript#4997]
Name: UBET
Homepage: http://ubet.com
Logo: http://s12.postimg.org/gy9u95bwt/ubet_mainlogo_dark.png

On a personal note, I would like to offer a special thanks to the TypeScript team.

The ubet.com team were early adopters using it in a large team on a large project and although we had some early problems with limited tool support and a mixed view from the team on whether the benefits were worth the compiling 'overhead', most members appreciated the intelisense, additional language features and compile-time error checking. I still think the TS overhead outweighed the cost of working without intelisense and compile time error checking. And these days the overhead is extremely minimal and I personally don't see myself going back to JS anytime soon.

Big thanks and keep up the good work!

Cheers,
Ben
ben.daniel@tattsgroup.com

**Comment by DanielRosenwasser** [comment]
We're glad you gave us a shot! We always love hearing positive experiences, so thanks for the personal note. :smiley:

**Comment by codeandcats** [comment]
Ping :smile:

**Comment by RyanCavanaugh** [comment]
We do website logo updates in batches, so this will get picked up at the next refresh. Not sure exactly when that will be since the guy who usually did that just left the team.

**Comment by codeandcats** [comment]
Hey guys, I just got a reminder to check up on this. Is there anyone assigned to updating the website logos yet? Would be nice to close this. :)

**Comment by mhegazy** [comment]
i update them in batches. they should be updated by the time TS 1.7 ships (i need to update the download links on the site anyways).

we are also working on a better workflow here to allow partners to send us PRs instead of me being the bottle neck.
