### ISSUE TITLE
Using variable defined by array destructuring assignment in default value of variables defined afterwards.

### ISSUE THREAD

**Issue by farazsa88** [microsoft/TypeScript#49989]
# Bug Report

### 🔎 Search Terms

Array destructuring assignment default value 7022

### 🕗 Version & Regression Information

Exists in 3.3.3 - 4.8.0-beta
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this behaviour

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=8&ts=4.8.0-beta#code/MYewdgzgLgBA2gQwDQwEYwLwwTA1DARgF1N4AmIgbgFgAoUSEAGwFMA6JkAcwAoADBAC4YAEgDeCAL4pUw8akl8AlDVpA)

### 💻 Code

```ts
const [a, b = a + 1] = [2];
console.log(`a: ${a}, b: ${b}`);
```

### 🙁 Actual behavior

Types of `a` and `b` inferred as `any`, or if `noImplicitAny` enabled, shows error: `'a' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)`

### 🙂 Expected behavior

Types of both `a` and `b` should be inferred as `number`.

**Comment by babakks** [comment]
@RyanCavanaugh I've submitted a PR for this issue. Would you please check it later?

**Comment by jcalz** [comment]
Not sure if the issue reported [this SO question](https://stackoverflow.com/q/77647742/2887218) with the code:

```ts
declare const o: { a?: number, b?: number } | undefined
const { a, b = a } = o ?? {}; // error!
// ---> ~  'a' 
// implicitly has type 'any' because it does not have a type annotation and is 
// referenced directly or indirectly in its own initializer.(7022)
```
[Playground link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3kgXPA3vFAPx4oCuAtgEYgwA081p8FNd8AvvAD7zkpQAMwCWKEMACwAKGToshKI2rwAvES5rs8YsQKcA3DJlA)

is the same issue or not.  Waiting to see if any fix for this addresses it; if not, I might open a new issue for it (unless someone can point to a more appropriate existing issue)

**Comment by babakks** [comment]
@jcalz I think the issue you mentioned is solved by the PR. You can check it via [this](https://www.staging-typescript.org/play?ts=5.4.0-pr-56753-16) custom-build playground. As I checked the type inference is now showing `number | undefined` for `a` and `b` symbols.

**Comment by jcalz** [comment]
Indeed, looks like it.  And since that got merged it's also visible in the nightly build.
