### ISSUE TITLE
Checking if an element exists in the if statement, still shows ''Object is possibly 'undefined'"

### ISSUE THREAD

**Issue by PointSingularity** [microsoft/TypeScript#49983]
# Bug Report
I enabled noUncheckedIndexedAccess  in the tsconfig, but then I encountered some unintuitive behavior.
TypeScript shows an error about the object being possibly undefined, even though there is a check in the if statement.

### 🕗 Version & Regression Information

Tried every version available on TS Playground above version 4.1 (where the noUncheckedIndexedAccess was first introduced), and the error was the same for each version.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.8.0-dev.20220721#code/JYOwLgpgTgZghgYwgAgNIQJ7IN4ChnLAAmAXMiAK4C2ARtANz7IID2ANi1GQM5hSgBzRgF9cuViF7JecSGTwEA1pm5l0GANoBdEcgC8OJsoyrkGpgWyFSyAAwAaZu05kA5AGI4X76+TD7FjjWZACMjqwcXMgeNLFxvv6BVsRkAEzhzlEeCDm5CQEElsHIAMwZkW7uRNU1+UnFACzlLtHuEO0ddYVBKcgArM1Z7jAjo13IWgHCjOIskmDIcNzcwAIgAHIQAO4AwpkAKizq+sgAFMYAkjaUtNCDPHyCAJT6AHyGBBJSoEQQAB4nGSQAB0xm4wJgPwuIF+f1O50wLz072MwOI+j0BkuRCejAIwBgZx+-2QrwMtmQADJKdIwLIIKCVFSaUCGWCNMS-loXqzGSYOTD-lpgRFOCdRVARIwgA](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=4.8.0-dev.20220721#code/JYOwLgpgTgZghgYwgAgNIQJ7IN4ChnLAAmAXMiAK4C2ARtANz7IID2ANi1GQM5hSgBzRgF9cuViF7JecSGTwEA1pm5l0GANoBdEcgC8OJsoyrkGpgWyFSyAAwAaZu05kA5AGI4X76+TD7FjjWZACMjqwcXMgeNLFxvv6BVsRkAEzhzlEeCDm5CQEElsHIAMwZkW7uRNU1+UnFACzlLtHuEO0ddYVBKcgArM1Z7jAjo13IWgHCjOIskmDIcNzcwAIgAHIQAO4AwpkAKizq+sgAFMYAkjaUtNCDPHyCAJT6AHyGBBJSoEQQAB4nGSQAB0xm4wJgPwuIF+f1O50wLz072MwOI+j0BkuRCejAIwBgZx+-2QrwMtmQADJKdIwLIIKCVFSaUCGWCNMS-loXqzGSYOTD-lpgRFOCdRVARIwgA))

### 💻 Code

```ts
interface Key {
  id: number;
  color: string;
}

const state: {
  keys: Key[];
} = {
  keys: [
    { id: 0, color: '#aaaaaa' },
    { id: 1, color: '#bbbbbb' },
    { id: 2, color: '#cccccc' },
    { id: 3, color: '#dddddd' },
    { id: 4, color: '#eeeeee' },
    { id: 5, color: '#ffffff' },
  ],
};

const assignNewColorToKey = (keyId: number, color: string) => {
  const index = state.keys.findIndex((key) => key.id === keyId);
  if (index >= 0 && state.keys && state.keys[index]) 
    // error here
    state.keys[index].color = color;
};

```

### 🙁 Actual behavior

If statement had a check for the property, but still shows as possibly undefined.

### 🙂 Expected behavior

No undefined error should be thrown, because it was checked in the if statement.

**Comment by MartinJohns** [comment]
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

Just store it in a variable (which IMO is much cleaner anyway).

**Comment by fatcerberus** [comment]
`state.keys[index]` isn't narrowed because `index` is not a literal.  You can work around by first assigning it to a local and narrowing that:

```ts
const assignNewColorToKey = (keyId: number, color: string) => {
  const index = state.keys.findIndex((key) => key.id === keyId);
  const key = state.keys?.[index];
  if (index >= 0 && key)
    key.color = color;
};
```

**Comment by fatcerberus** [comment]
Oops, got sniped by @MartinJohns 😅

**Comment by PointSingularity** [comment]
> Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.
> 
> Just store it in a variable (which IMO is much cleaner anyway).

Thank you for your quick answer!
I will do that, was just confused about the type narrowing.

**Comment by PointSingularity** [comment]
> `state.keys[index]` isn't narrowed because `index` is not a literal. You can work around by first assigning it to a local and narrowing that:
> 
> ```ts
> const assignNewColorToKey = (keyId: number, color: string) => {
>   const index = state.keys.findIndex((key) => key.id === keyId);
>   const key = state.keys?.[index];
>   if (index >= 0 && key)
>     key.color = color;
> };
> ```

Thank you for the solution! I was confused why it didn't work 😅

**Comment by fatcerberus** [comment]
btw this isn't directly related to the issue, but unless you actually need the index for something you could skip a step and just use `.find()`.

```ts
  const key = state.keys?.find((key) => key.id === keyId);
  if (key) key.color = color;
```

**Comment by PointSingularity** [comment]
> btw this isn't directly related to the issue, but unless you actually need the index for something you could skip a step and just use `.find()`.
> 
> ```ts
>   const key = state.keys?.find((key) => key.id === keyId);
>   if (key) key.color = color;
> ```
My actual code is more complex, this was just a short version. 
Yeah, this would work too and is even more concise 👍

**Comment by Therealskythe** [comment]
TypeScript should never force you to change your code only because of its own limitations. What if adding that extra code is bad for performance? Or readability?

I'll disable `noUncheckedIndexedAccess` until this is fixed.

**Comment by jhwheeler** [comment]
Why are people downvoting @Therealskythe 's comment? This seems quite reasonable to me.

**Comment by RyanCavanaugh** [comment]
The point of options is to be disabled if you don't like their behavior, so... go ahead and do that? It's basically saying "Why is 'dark blue' paint so dark? It's harder to see objects painted this color. I will get light blue paint until then". Yeah that's why there are multiple colors, so you can choose.

**Comment by Therealskythe** [comment]
> The point of options is to be disabled if you don't like their behavior, so... go ahead and do that? It's basically saying "Why is 'dark blue' paint so dark? It's harder to see objects painted this color. I will get light blue paint until then". Yeah that's why there are multiple colors, so you can choose.

No, it's like your paint brush forcing you to paint in red because it's bad at blue. It's a tool. It should not get in your way and make your result worse.
