### ISSUE TITLE
Intellisense String Unions autocomplete inconsistent with ts

### ISSUE THREAD

**Issue by dereekb** [microsoft/TypeScript#49996]
# Bug Report

### 🔎 Search Terms

Intellisense
String Unions
Incorrect Autocomplete
Types
Typing

### 🕗 Version & Regression Information

This bug seems like it has been around since the introduction of String Unions. 

The following example is of a type that will merge the keys of the input object into an ascending order (which as I write this bug template I notice it is not lexicographical order), since that's how Typescript uses the individual types in the unions of types. This ordering is desirable since it is predictable. Without this order, the following StringConcatenationOrder type would be unusable, as would [the other related types](https://github.com/dereekb/dbx-components/blob/9d85127620c68ab746459778251082bee9fd8de1/packages/util/src/lib/type.ts#L179).

### ⏯ Playground Link

```ts repro

export declare type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;

export type UnionToOvlds<U> = UnionToIntersection<U extends any ? (f: U) => void : never>;
export type PopUnion<U> = UnionToOvlds<U> extends (a: infer A) => void ? A : never;

export type StringConcatenationOrder<S extends string, SEPARATOR extends string> = PopUnion<S> extends infer SELF
  ? //
    SELF extends string
    ? Exclude<S, SELF> extends never
      ? `${SELF}`
      : // This works because the values of S are always interpreted in ascending lexiographical order
        `${StringConcatenationOrder<Exclude<S, SELF>, SEPARATOR>}${SEPARATOR}${SELF}`
    : never
  : never;

export type KeyCanBeString<K> = K extends number | boolean | string | null | undefined ? K : never;

export type OrderedCommaSeparatedKeysOfObject<T extends object> = OrderedCommaSeparatedKeys<`${KeyCanBeString<keyof T>}`>;
export type OrderedCommaSeparatedKeys<T extends string> = StringConcatenationOrder<T, ','>;

// @showEmit
const object = {
  _: 0,
  b: 0,
  a: 0,
  c: 0,
  1: 0
};

const replaced: OrderedCommaSeparatedKeysOfObject<typeof object> = '_,a,b,c,1';

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.7.4#code/LAKApgHgDg9gTgFwAQBMwGMA2BDOYkICeU+AqgHYCWM5AKjAJLkJhwDOGC15APKQHxIAvEgAUpJJBbkUbJNnKEkAfjEBrAFxJSASmGCAbjEookW8mAOs9UsDLmjNSSuQBmrJAz1DDxlKCQVTwCzJAsrOABuUFBIWEQCYjIqGnoAeQNMWT5BEQpueiYWdk5uPkkIaVl5RSDRVy1dfSQjE1Dw1n5o8Gh4ZCISJAAFGCh8mhzhbRS6GAystknbezFsLRd3OCQAQW9fNtVt9stWbtjehIH8AGUEOBcAcwBhGnRsaXfuNLg0OB5ripVORsO6PAA0SGuAFEhtsAErbWhpOGAuzVEH3cgPXLDUbjXjXQTLaobDzQgAyADEQqoAPS0kKBCmU1ErDGPRlBKEQLAAVzQ-whzKJlTRcg6cE5gVUAAMACQAb2ZAF8ZVLQvSkLQABaUOQAd3gajkACMMNheRwCNr8AZsJheWA5DBXJD5Hh5Jh9dhCHIXMUoHgWKYXPI2Og0Y8kJhINQHnBsFBdW9MEh4L91YF5UrQViXuQ3h8uDRvr8eNy+QLrkKoVT+DXYQikXD+MrFdDG4jkW2lbXKarOeYTpKQIEhxEzj14v0kkgANJgQhPBQAITAt0xDx4c5xc9Z1XIvIAtmatgAfJAmmAwGMKJAX9lY+9hXmYVMX3kyMCuFxgUyqPdx1OGIpz6RJBlLVg-xeI8j2wa4wCgXB3j-BdfTSVw0hNAArTgeFofdnRwzgcUgvAUBguCEKQhNgzQxZszQ5dyDXDdHh4NRFxdLVWxlLpzmncD8DI6CYFg+DEOQujF0WAjiWBXNsSmNi81eFDyE+EsflYfCIQAcjBPT+JAUBNQAATYbUYH1KEj0oBBQHQGgQTTYj0GQEQFRCAB9LQAAYwRCE1-MC0d5BCkJ0AisKAEZ-NAZVJyc8gXLwKAcAjFAtBEiixKoyTaNQmSMKw3D3J4K5uJgNyEBxPTvLBbAwRNMF0DBGK9O6IA)

### 🙁 Actual behavior

<img width="536" alt="Screen Shot 2022-07-22 at 1 28 41 AM" src="https://user-images.githubusercontent.com/3586580/180385031-6c7b4490-e0ae-4f80-89cb-e66e0ec0a582.png">

In VS Code Intellisense looks at the object's variable declaration order (`_`, b, a, c, 1), but `ts` will look at the ascending "lexicographical" order of the object keys (`_`,a,b,c,1).

In the workspace you can see it give an error, but ts compiles it. This throws me off sometimes since intellisense will present invalid completions that typescript will reject (correctly). Here's the `ts` error thrown by Jest:

![Screen Shot 2022-07-22 at 2 41 52 AM](https://user-images.githubusercontent.com/3586580/180389419-4af1cba6-368a-438e-b82c-5abbe5efcb4b.png)

### 🙂 Expected behavior

Intellisense should evaluate the object's keys in the ascending order consistent with `ts`.

**Comment by dereekb** [comment]
I noticed my [CI failed](https://app.circleci.com/pipelines/github/dereekb/dbx-components/1418/workflows/134d835c-3724-42d7-8c15-310d2a003b37/jobs/3871/parallel-runs/0/steps/0-109) with a case that shows that ts isn't consistent either with how it handles union of string keys.

![Screen Shot 2022-07-22 at 3 07 28 AM](https://user-images.githubusercontent.com/3586580/180393882-ee12c79d-529e-4da1-9bf9-7f04a9674ce4.png)

I assumed the variables came back in a consistent order but I suppose they don't. Ideally I would expect the keys to be in some order, but it's possible that the UnionToIntersection type and inferences do weird things.

In any case, having a consistent result between `ts` and Intellisense is necessary.

**Comment by fatcerberus** [comment]
The order of types in a union is essentially arbitrary (based on the internal ID numbers of the types involved); type unions should generally be treated as unordered sets.  Consistency between TS and IntelliSense is a moot point as the observed order of union constituents may change just by changing your code, or even just by *renaming files* so they get compiled in a different order.  Any code that relies on a specific union order is indeed going to be very fragile, as you've observed here.

All may not be lost however - see #17944.

**Comment by MartinJohns** [comment]
Since I see the type here again, FYI: https://github.com/microsoft/TypeScript/issues/41857#issuecomment-740102743

> We don't support anything that involves `UnionToIntersection`; this is an ill-defined and will frequently produce "surprising" results.

**Comment by dereekb** [comment]
Thanks for the responses. I found another response while digging through the similar threads.

https://github.com/Microsoft/TypeScript/issues/13298#issuecomment-468375328

It seems like until there is a type that can sort the input union of keys it can't be safely achieved with the typings provided above.

My main need for these types is to allow any combination of the input and combine them with a separator (comma):

```
 'a' | 'b' | 'c' w/ ',' -> 'a' | 'b' | 'c' | 'a,b' | 'b,a' | 'c,a,b' | etc...
```

And any combination of the input that uses each key once and combine them with a separator (comma):

```
'a' | 'b' | 'c' w/ ',' -> 'a,b,c' | 'a,c,b' | 'b,a,c' | etc...
```

The use case [example is here](https://github.com/dereekb/dbx-components/blob/c3069825dd62ca08dc2942c299284953ec2f0b33/components/demo-firebase/src/lib/model/profile/profile.api.ts#L45):

```
...

export type ProfileModelCrudFunctionsConfig = {
  profile: {
    update: {
      _: UpdateProfileParams;
      username: SetProfileUsernameParams;
      onboard: [FinishOnboardingProfileParams, boolean];
    };
    delete: UpdateProfileParams;
  };
  profilePrivate: null;
};

export const profileModelCrudFunctionsConfig: ModelFirebaseCrudFunctionConfigMap<ProfileModelCrudFunctionsConfig, ProfileTypes> = {
  profile: ['update:_,username,onboard', 'delete']
};

...
```

ProfileModelCrudFunctionsConfig is a type I use as a map to enforce type safety, but it is unavailable at runtime. I use the config object to generate the corresponding interface as an object at runtime:

```
/**
 * Declared as an abstract class so we can inject it into our Angular app using this token.
 */
export abstract class ProfileFunctions implements ModelFirebaseFunctionMap<ProfileFunctionTypeMap, ProfileModelCrudFunctionsConfig> {
  abstract [profileSetUsernameKey]: FirebaseFunctionMapFunction<ProfileFunctionTypeMap, 'profileSetUsername'>;
  abstract profile: {
    updateProfile: {
      // full names
      updateProfile: ModelFirebaseCrudFunction<UpdateProfileParams>;
      updateProfileUsername: ModelFirebaseCrudFunction<SetProfileUsernameParams>;
      updateProfileOnboard: ModelFirebaseCrudFunction<FinishOnboardingProfileParams, boolean>;
      // short names
      update: ModelFirebaseCrudFunction<UpdateProfileParams>;
      username: ModelFirebaseCrudFunction<SetProfileUsernameParams>;
      onboard: ModelFirebaseCrudFunction<FinishOnboardingProfileParams, boolean>;
    };
    deleteProfile: ModelFirebaseCrudFunction<UpdateProfileParams>;
  };
}
```

I need to make sure that `_`, `username`, and `onboard` are in that string so that I can create the above functions (updateProfile, updateProfileUsername, etc.).

What I have works most of the time, but the more items in the combination, the greater the chance of Typescript and Intellisense not being on the same page and one of them having an error.

**Comment by MartinJohns** [comment]
> My main need for these types is to allow any combination of the input and combine them with a separator (comma):

Given the limit of 25 types in a union this sounds... suboptimal.

**Comment by dereekb** [comment]
> > My main need for these types is to allow any combination of the input and combine them with a separator (comma):
> 
> Given the limit of 25 types in a union this sounds... suboptimal.

You're right, the combinations aren't great, since would create n! of type combinations. Since the typings bail out around 2^16, that means the max number of types we could have would be up to n=8, but n=7 is the highest that I'd even bother recommending due to speed. I was [exploring it as an option](https://github.com/dereekb/dbx-components/blob/9d85127620c68ab746459778251082bee9fd8de1/packages/util/src/lib/type.ts#L216) since it would successfully reproduce every combination for each type in the union.

For the example above I really just need to ensure each string is in there, which means if the keys were ordered consistently through each variation, I could rely on the following:

`'a' | 'c' | 'b' w/ ',' -> 'a,b,c'`

But since Typescript doesn't order the keys in the union in any particular order during evaluation, I can't rely on that.

I have another function that creates an "approximation" that contains each entry that is in the order that typescript ordered the types and it works the best right now in terms of flexibility for the inconsistencies.

**Comment by RyanCavanaugh** [comment]
Ordering of a union is not supposed to be observable from a type system perspective, and if you find yourself observing it, you've wandered off the trail and need to find your way back 😅

#17944 will not fix this because that would only be plausibly be addressed during the type-to-string process; internal ordering would remain unchanged for performance reasons.

**Comment by dereekb** [comment]
That makes sense to me.

I guess this is out of scope for the time being. I'd put in a feature request for adding some Template Literal Types that can merge the union and compare it unordered but since the existing types are all mappings of types it might not be doable right now because this is a joining of types.

https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html

This can be represented currently:
```
Object.keys(passedObject).map(x => `${x}Changed`)
```

This cannot:
```
Object.keys(passedObject).join(',');
```

Even if implemented for type-checking performance it isn't feasible since it's not trivial to know if a certain string matches any of the possible combinations without actually calculating them all, and working backwards isn't predictable either if a type contained the separator.

My feature request would instead be to support the equivalent type of:

```
Object.keys(passedObject).sort().join(',');
```

I'd be open to creating a PR for it if you believe it would be feasible to implement and is inline with Typescript's design goals.

**Comment by RyanCavanaugh** [comment]
This seems like an XY problem; what are you trying to do?

**Comment by dereekb** [comment]
Example use case in more detail is above/here:

https://github.com/microsoft/TypeScript/issues/49996#issuecomment-1192786267

I have keys on a type (ProfileModelCrudFunctionsConfig above) I want to make sure are all comma-separated in a string, so that if I add any fields the type system provides additional guarding. The proper string is needed so I can generate an object that fits the ProfileFunctions interface at runtime.

I'd like a type that is the equivalent of `Object.keys(...).sort().join(',');` so the typing system can assert that the string contains each of the types (`_`, `username`, `onboard` in the example).

So if I added "newCrudFunction" there, it reminds me to add it to the string.

![Screen Shot 2022-07-31 at 12 37 06 AM](https://user-images.githubusercontent.com/3586580/182011864-bcf4eb36-fe1d-4882-b292-ebe1954725cd.png)
