### ISSUE TITLE
HTMLLinkElement type definition is missing `download` attribute

### ISSUE THREAD

**Issue by evanwills** [microsoft/TypeScript#49994]
# Suggestion

## 🔍 Search Terms

"download", "lib.dom.d.ts", "HTMLLinkELement"

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [yes] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [yes] This wouldn't change the runtime behavior of existing JavaScript code
* [yes] This could be implemented without emitting different JS based on the types of the expressions
* [yes] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [yes] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Interface definition for [HTMLLinkElement](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#LC7289) is missing the `download` attribute.

`download: string,` should be added to the [HTMLLinkElement](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#LC7289) interface definition. (At line 7298)

## 📃 Motivating Example

The `downaload` attribute is a standard part of the HTML specificaition for `<a>` tags (see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) and [WhatWG docs](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) for more info). The HTMLLinkElement interface definition should include it becuase it's part of the HTML standard and it `download` provides useful functionality for ECMAscript generated `data:` URLs.

## 💻 Use Cases

I'm writing a [custom element](https://github.com/evanwills/filter-sort-table) that enhances HTML tables. One of the features of this custom element is that it allows users to filter & sort the contents of the table then download the data as a delimited text file (using a `data:` scheme URL) regardless of whether they have an internet connection. The once downloaded can then be opened in a spreadsheet application. 

By specifying the text file's file name in the link's download attribute the default file name will be meaningful rather than whatever the browser decides is appropriate.

Currently VSCode's intelisense shows the `link.download` attribute as an error (*Property 'download' does not exist on type 'HTMLLinkElement'. Did you mean 'onload'?ts(2551)*)

**Comment by Josh-Cena** [comment]
You are looking in the wrong place—an `<a>` tag's attributes is different from the `HTMLLinkElement` interface. https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement doesn't mention `download`, and it's not part of the spec-defined IDL attributes either. You can read https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#content_versus_idl_attributes

**Comment by fatcerberus** [comment]
`<a>` is `HTMLAnchorElement`, for what it's worth.

**Comment by evanwills** [comment]
@fatcerberus thanks for the pointer to the `HTMLAnchorElement`
