### ISSUE TITLE
Very confusing message when user doesn't realize they're in a CommonJS context

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#50009]
Found from an issue I was diagnosing for @mpodwysocki.

Today, if you use `"module": "nodenext"` or `"module": "node16"`, you might try to import from a package with ESM files and get the following error message

```
Module 'yadda/file.js' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.
```

This is extremely confusing. The fix is typically to add the following field to the `package.json` that corresponds to the importing file with the error:

```json5
    "type": "module"
```

**Comment by fatcerberus** [comment]
This becomes especially confusing because it’s an ESM import you’re writing (so the error is actively *wrong* to say it “cannot be imported using this construct”—it can, with the right package configuration).  The error only makes sense when you know the import is being transpiled to `require()`, and even *that’s* confusing because it’s not actually a problem with the source code as written but instead the JS output.

**Comment by DanielRosenwasser** [comment]
How about this.

_____

If the file is `.cts` or .cjs` extension:

```
The current file is a CommonJS module whose imports will produce require() calls; however, the referenced file is an ECMAScript module and cannot be imported via require(). Consider writing a dynamic import() call instead.
```

Related diagnostics:

```
The specifier {0} resolved to this file with the path {1}.
```

_____

If the file **does not** have an `.mts` or `.mjs` extension:

```
This {0} statement references an ECMAScript module, but the current file is a CommonJS module and cannot use this syntax. It is likely that your 'package.json' needs a 'type' field set to 'module'.
```

Related diagnostics:

```json
Consider adding `"type": "module"` to this 'package.json' file.
```

```
The specifier {0} resolved to this file with the path {1}.
```

**Comment by DanielRosenwasser** [comment]
It's possible we could just have the related info be "resolved to this file".

**Comment by andrewbranch** [comment]
> The specifier '{0}' resolved to this file with the path '{1}'.

Is this useful? In an editor scenario you can already go-to-definition on it, but I don’t see what you’d need to do in the resolved file as part of addressing the error.

**Comment by andrewbranch** [comment]
I don’t think it’s appropriate to rule out dynamic import in any of these scenarios. I’m planning to use a single head message for all of them:

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import(\"{0}\")' call instead.
```

and optionally attaching either 

```
To convert this file to an ECMAScript module, change its file extension to '{0}'.
```

or

```
To convert this file to an ECMAScript module, change its file extension to '{0}', or add `\"type\": \"module\"` to its package.json file with path '{1}'.
```

(We cannot place a related diagnostic on the package.json file itself because it’s not a source file.)

**Comment by DanielRosenwasser** [comment]
Sad - okay, what about

```diff
- or add `\"type\": \"module\"` to its package.json file with path '{1}'.
+ or add the field `\"type\": \"module\"` to '{1}'.

**Comment by andrewbranch** [comment]
Actually, there is a `createDetachedDiagnostic` which looks like it might work. But is using that and splitting the one related info into two better than having them combined?

**Comment by DanielRosenwasser** [comment]
> I don’t think it’s appropriate to rule out dynamic import in any of these scenarios. 

I don't know if there's ever been a context where I could truly use a dynamic import in the context where I needed it. That's why I'm doubtful that it's helpful in the first place as a suggestion.

That said, the related diagnostics can be smooshed.

**Comment by andrewbranch** [comment]
That may be true, but converting everything to ESM is a more consequential change and may be even more of a hassle. I also considered moving the dynamic import suggestion to a related diagnostic so it feels more like it has equal weight with the other suggestions:

- The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'.
  - To import "{0}" into this CommonJS module, use a dynamic 'import("{0}")' call.
  - To convert this file into an ECMAScript module, change its file extension to '{0}'.

**Comment by fatcerberus** [comment]
> Consider writing a dynamic 'import(\"{0}\")' call instead.

Note that this isn't a valid fix if the tsconfig specifies `"module": "node"` - then the dynamic import gets converted to `require()` too.

**Comment by luongjames8** [comment]
I'm on Typescript 4.9.3 and this doesn't seem to be fixed yet. 

It is VERY confusing. I am glad that I found this thread, and hope the head message can be updated soon.

**Comment by alexherrera42** [comment]
It would be great if there was an option I could specify to silence this error.  I'm importing ESM modules that I want typescript to recognize and process, but I'm not building with typescript.  I'm using webpack, which handles all the import statements, which makes this error irrelevant noise.

**Comment by andrewbranch** [comment]
[`--moduleResolution bundler`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler)

**Comment by Jood80** [comment]
```ts
 "compilerOptions": {
    "moduleResolution": "node",
    }
```
  Should do the trick too.

**Comment by alexherrera42** [comment]
That will not do the trick when importing ESM.
