### ISSUE TITLE
Is it possible to get the type I pass to callback function using generics?

### ISSUE THREAD

**Issue by jon9090** [microsoft/TypeScript#50000]
Is it possible to get the type I pass to callback function using generics?

```
const create = (callback) => { return callback(); }

const shouldBeTypeOfNumber = create(() => 1); // the type now is any

const shouldBeTypeOfString = create(() => 'foo'); // the type now is any
```

I did ask stackoverflow but got no answer.

**Comment by fatcerberus** [comment]
This isn't a support forum but I'm feeling nice today

```ts
function create<T>(callback: () => T): T {
    return callback();
}
```

[Playground](https://www.typescriptlang.org/play?&code/GYVwdgxgLglg9mABBATgUwIZTQHgCoB8AFBBgDZkBGGEA1gFyJECUiAvAYns43ogN4AoRCMTooIFElIVqdFgG5BAX0GCICAM5REmgBZwQZACYAhNHgCeABzQB5YADkQAW0poU7ZOixoiLdk4ARmYlAHow0UQAPQB%20dS0dfUMTcytbBwBlKBQYMABzL1RMbH9WDkQAcmA4OErQwQiouMEgA=#code/GYVwdgxgLglg9mABBATgUwIZTQHgCoB8AFBBgDZkBGGEA1gFyJECUiAvAYns43ogN4AoRCMTooIFElIVqdFgG5BAX0GCICAM5REmgBZwQZACYAhNHgCeABzQB5YADkQAW0poU7ZOixoiLdk4ARmYlAHow0UQAPQB+dS0dfUMTcytbBwBlKBQYMABzL1RMbH9WDkQAcmA4OErQwQiouMEgA)
```

In the future, there's a Discord server you can join to ask questions like this.

**Comment by jon9090** [comment]
@fatcerberus what is the Discord link plaese?

**Comment by fatcerberus** [comment]
It's linked from the TS website here https://www.typescriptlang.org/community
Direct link to Discord server is https://discord.gg/typescript
