### ISSUE TITLE
TS server returns wrong type if narrowed within the same line

### ISSUE THREAD

**Issue by m1cm1c** [microsoft/TypeScript#50002]
# Bug Report

### 🔎 Search Terms

type narrowing same line

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing same line

### ⏯ Playground Link
The playground does not seem to support displaying types, but anyway ...

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsL3egFAI2ACcAuGEZI1CAcxgB8YAFI9AW1RAFMAeCq2gD4AlGRbtOvAG7pUAE0EwA3gCgYMQkRgBeGMADuwVMg3EA3GphRMIdABsuAOjvoaBYsIsBfFUA)

### 💻 Code

```ts
async function foo(bar: string | Promise<string>): Promise<void> {
  bar = await bar;
  console.log(bar);
}
```

### 🙂 Expected behavior

When requesting the type at the location of `bar` in line 2 from TS server, the returned type should be `string` because `await bar` can only return `string`.

### 🙁 Actual behavior

The type is returned as `string | Promise<string>`:
![Screenshot_20220722_163120](https://user-images.githubusercontent.com/11382432/180461578-dc91ac1e-fb75-4ebb-a965-c98837645438.png)

In the next line, it works correctly:
![Screenshot_20220722_163143](https://user-images.githubusercontent.com/11382432/180461604-aa88a224-b343-4575-b871-7a8fcafc70b9.png)

This only happens if the variable on the left pre-exists, i.e. `let baz = await bar;` or `const baz = await bar;` does not exhibit this behavior when the type at location of `baz` is requested.

### Additional info

[According to Tide's author](https://github.com/ananthakumaran/tide/issues/449#issuecomment-1192621907), the types displayed in the minibuffer are the types returned by TS server: "Tide sends the cursor location to the tsserver and doesn't know much."

**Comment by MartinJohns** [comment]
But at that point the type of the variable is still `string | Promise<string>`. Narrowing happens after the assignment.

**Comment by m1cm1c** [comment]
> But at that point the type of the variable is still `string | Promise<string>`. Narrowing happens after the assignment.

The variable on the left-hand side of an assignment should have the type that's correct after the assignment because when that variable is used (e.g. `bar = (bar = await bar);` or `console.log(bar = await bar)`) it can only take the values that the right-hand side of the assignment can return. Why would you want it to be of a type that includes values that it cannot possibly take? The only sane definition of a type is the set of values that something can take.

Even if for some reason you still disagree, this makes my minimal example of the broken type inference at most 1 line longer.

```ts
async function foo(bar: string | Promise<string>): Promise<void> {
  bar = (bar = await bar);
  bar = bar + 'aa';
  console.log(bar);
}
```

Here, it should be super obvious that the position I requested the type for is after the assignment.
![Screenshot_20220723_154958](https://user-images.githubusercontent.com/11382432/180608030-b41efd4e-7582-47da-8db1-f22af1a9e87b.png)

In fact, in the same line, TS server knows the correct type on the right-hand side of the assignment even though the right-hand side of the assignment lives at an earlier point in time than the left-hand side:

![Screenshot_20220723_155401](https://user-images.githubusercontent.com/11382432/180608142-7598db2e-286a-46ff-9943-7329d3e50770.png)

**Comment by MartinJohns** [comment]
On a second thought, I think it makes most sense to show the declared type (as it currently does) when assigning. After all, that's the type that determines compatibility.

**Comment by m1cm1c** [comment]
> On a second thought, I think it makes most sense to show the declared type (as it currently does) when assigning. After all, that's the type that determines compatibility.

Okay, this is a fair point. TS server actually seems to behave consistently when setting this as the goal. At least I wasn't able to find any inconsistencies with this. Closing the issue. Thank you for this comment.
