### ISSUE TITLE
Ama Vira Kian

### ISSUE THREAD

**Issue by alirezatc** [Microsoft/TypeScript#5000]
Please fill the following out:

- Name: Ama Vira Kian
- Homepage url: http://amasystem.ir
- Brand Guidelines/Licensing: http://amasystem.ir
- Logo: http://amasystem.ir/Assets/Image/ama-vira-logo-b.png

**Comment by DanielRosenwasser** [comment]
Hey @alirezatc, I think some people might [misunderstand](https://en.wikipedia.org/wiki/Swastika#As_the_symbol_of_Nazism) your logo and potentially take offense. To avoid that confusion, and in the interest of being sensitive to all members of the community, do you have an alternate logo that we could use that just uses your company name?

**Comment by mhegazy** [comment]
@alirezatc as per https://github.com/Microsoft/TypeScript/issues/5000#issuecomment-143848090, please resubmit with an alternate logo.

**Comment by alirezatc** [comment]
Dear Daniel and Dear Mohamad,
Thanks for your feedback. Actually this is my company's logo and it includes 4 ama typography in Farsi. But as you say I'm going to upload another photo for MS typescript.

**Comment by mhegazy** [comment]
Thanks @alirezatc for understanding, and sorry for any inconvenience.
