### ISSUE TITLE
Allow Overloads that are smart about Union Discrimination in the function's parameters

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#50003]
# Suggestion

## 🔍 Search Terms

discriminating unions function overload 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow Overloads that are smart about Union Discrimination in the function's parameters

## 📃 Motivating Example

```ts
interface SpanRequestUnignorable {
  readonly title: string
  readonly ignore?: never;
}

interface SpanRequestIgnorable {
  readonly title: string;
  readonly ignore: boolean;
}

type SpanRequest = SpanRequestUnignorable | SpanRequestIgnorable;

/* This top overload is compilation error. "This overload signature is not compatible with its implementation signature." */
function collectSpan<T>(
  request: SpanRequestUnignorable, 
  behavior: (spanContext: Record<string, string>)=> T) : T;
function collectSpan<T>(
  request: SpanRequestIgnorable, 
  behavior: (spanContext: Record<string, string> | undefined)=> T) : T;
function collectSpan<T>(
  request: SpanRequest, 
  behavior: (spanContext: Record<string, string> | undefined)=> T) : T {
    if(request.ignore){
      return behavior(undefined);
    }
    return behavior({});

}

collectSpan({title: "should always have spanContext"}, (spanContext)=> {
  spanContext.requiresExtraneousIf = "false";
})
collectSpan({title: "should never have spanContext", ignore: true}, (spanContext)=> {
  if(spanContext) {
    spanContext.extraneousIf = "false";
  }
})
let dynamicFilter: boolean = true;
collectSpan({title: "should sometimes have spanContext", ignore: dynamicFilter}, (spanContext)=> {
  if(spanContext) {
    spanContext.extraneousIf = "false";
  }
})
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function collectSpan(request, behavior) {
    if (request.ignore) {
        return behavior(undefined);
    }
    return behavior({});
}
collectSpan({ title: "should always have spanContext" }, (spanContext) => {
    spanContext.requiresExtraneousIf = "false";
});
collectSpan({ title: "should never have spanContext", ignore: true }, (spanContext) => {
    if (spanContext) {
        spanContext.extraneousIf = "false";
    }
});
let dynamicFilter = true;
collectSpan({ title: "should sometimes have spanContext", ignore: dynamicFilter }, (spanContext) => {
    if (spanContext) {
        spanContext.extraneousIf = "false";
    }
});

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoAc4gEoQI4CuEAzmAKojADmIA9lHAEYA2KA3gFDLJQRwAmtEMwCeyMMDCsAXMlJRQVLjz6DhY6nV4B+WSAgA3aAG4OAXw4dQkWIhQYsuQiTABJGvSatknbrwFCouKSMnJgCiBUpn6qgRoevLKMtLSsWKYWHGAi6PaYOPhEpMgAvGj5TkXklAleKAA+5Y6FLu5adaYcMAQgCBJCyAiprH0OIAA8ACoAfAAUyrzOpLJjlS4Ump4sEAA0yMqMEAAWcAbA9LKzxPkAwkKQAB5gsrhDUPzj8op7X5HTAJQlabISb-ZCySambq9fogQbDCCjfJTOYLFrLJoFJZuWrbPYHY6nc5QS7XLB3cAQJ4vRH0D6-Kg-cKKYGNHr8CAwUAQfiA4Gg8EgqE9PrnOFDZgjMBjFHzGLYlYVdFgfHcQ4nM4XZBXW73KnPZCvOmfZmRJkRKis5Dsznc3lAkFgiE+ZTcYAwWaLKoAOk2vH+vm4Qd4YAIUDh6qJ9FmNq5+l50SDFiDKlD4eQkc1UFmbDM-06mQlUrGOYkUggsgARMQjrQCMx+Mg4MwAO5wETEZAalBkkAUx5gStmPY68l6p58l3cXv9-Xer3AXjEACiTwY+jrxFcMFKyEr8GYxAglYy-w4RcR0vypZCFb3NbrDeQ+iMUC7px7uspT0rez9d-CIhh21GdxzASdA3dUc+zAsFA2nL8B29fV1wgTdt13fdmyPE9lAsPMOFYMBkH4EQQDgABbYAEAAMWAZgbCSFI0jhMpAIgUwLyRLAb3LKsH3rRtiFoCiIAkUTO27OREP1X9kH-WRSPIqjaPomxgOg2cJwdSCPVA79wKnIN9KQlCsDQggtx3MosMPY9E3w-4gA)
      
      

## 💻 Use Cases

This allows callers of the function to remove a branch if it can be statically shown that that check is unneeded

**Comment by MartinJohns** [comment]
Here's a simplified version:

```typescript
function fn(discriminator: 1,     cb: (ctx: string            ) => void): void;
function fn(discriminator: 2,     cb: (ctx: string | undefined) => void): void;
function fn(discriminator: 1 | 2, cb: (ctx: string | undefined) => void) {}
```

**Comment by RyanCavanaugh** [comment]
This is already very much possible using conditional types

**Comment by kwasimensah** [comment]
The simplified version by @MartinJohns has the same error in the playground 


```ts
function fn(discriminator: 1,     cb: (ctx: string            ) => void): void;
function fn(discriminator: 2,     cb: (ctx: string | undefined) => void): void;
function fn(discriminator: 1 | 2, cb: (ctx: string | undefined) => void) {}
```



<details><summary><b>Output</b></summary>

```ts
"use strict";
function fn(discriminator, cb) { }

```


</details>


<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```


</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMMAKAJjAzhATjAWxjAEMo5cAuRARgBpFHGIAja1aAD2qynzADmTYSICUiALwA+RADc4MdKOrzFAbgBQoSLATI0mHPiKlyVRACYGw1uy48+xIQB9E4dAFNgxD0skzVJRUFdE1taHgkFAxsPEJiMgpqGkRXK0RbRA4obkRefhc3ME9vMF9xaTkQ8QBvAF8gA)

**Comment by kwasimensah** [comment]
I tried a a more complicated version using conditional types and couldn't get it to work, but it would be great if the simplified version worked right out of the box

**Comment by RyanCavanaugh** [comment]
@MartinJohns was demonstrating a simplified version of the problem, not of the solution

**Comment by kwasimensah** [comment]
It’s actually still not clear what the right way to spell this should be, if there’s an existing solution to this

**Comment by MartinJohns** [comment]
@kwasimensah If I understand Ryan, he probably means this (using my simplified example):

```typescript
function fn<D extends 1 | 2>(
    discriminator: D,
    cb: D extends 1
        ? (ctx: string) => void
        : (ctx: string | undefined) => void
) {}
```
