### ISSUE TITLE
Heya @ahejlsberg, I've started to run the extended test suite on this PR at c7b2942acc31b4e467a9b28800d31d9976827b35. You can monitor the build [here](https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_build/results?buildId=1302

### ISSUE THREAD

**Issue by Azooz2538** [microsoft/TypeScript#50015]
Heya @ahejlsberg, I've started to run the extended test suite on this PR at c7b2942acc31b4e467a9b28800d31d9976827b35. You can monitor the build [here](https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_build/results?buildId=130251).

_Originally posted by @typescript-bot in https://github.com/microsoft/TypeScript/issues/50013#issuecomment-1193010785_

**Comment by fatcerberus** [comment]
what
