### ISSUE TITLE
Case of generating incorrect declarations

### ISSUE THREAD

**Issue by BzenkoSergey** [microsoft/TypeScript#50020]
# Bug Report

### 🔎 Search Terms

declaration

### 🕗 Version & Regression Information

Typescript version: all

### ⏯ Playground Link

See .D.TS tab
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/KYOwrgtgBAQlDeBYAUFNUCGUC8UDkGeANCulAEY77l4oC+KKAxgDYYDO7UAggqegAcATgEsAbhgAuwKEOAYAJgHsQLAJ6YBIqklRl0AbRgA6DAF0AXHz379GK3gCMxfrbLkHAJlo39dEr5kRsbkltZu+gDmXi6BbgAWDgDMPhEMvnSYXEwq7JIA3Iy+kcCSADwAKlDAAB7SIApcMAB8ABQA1lYVAJRW3AYEWnhmBhVm4W5ykmBCIFCS8SLsploG7WaFGfQoQA)

Correct declarations generating:
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/KYOwrgtgBAQlDeBYAUFNUCGUC8UDkGeANCulAEY77l4oC+KKAxgDYYDO7UAggqegAcATgEsAbhgAuwKEOAYAJgHsQLAJ6YBIqklRl0AbRgA6DAF0AXHz379GK3gCMxfrbLkHAJlo39dEr5kRsbkltZu+gDmXi6BbgAWDgDMPhEMvnQA3Iy+kcCSADwAKlDAAB7SIApcMAB8ABQA1lZFAJThbnKSYEIgUJLxIuymWgaNZtkZ9ChAA)
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/KYOwrgtgBAQlDeBYAUFNUCGUC8UDkGeANCulAEY77l4oC+KKAxgDYYDO7UAggqegAcATgEsAbhgAuwKEOAYAJgHsQLAJ6YBIqklRl0AbRgA6DAF0AXHz379GK3gCMxfrbLkHAJlo39dEr5kRsbkltZu+gDmXi6BbgAWDgDMPhEMvnSYXEwq7JIA3Iy+kcCSADwAKlDAAB7SIApcMAB8ABQA1lYVAJThbnKSYEIgUJLxIuymWgbtZlk8BgRaeGYGFWaFGfQoQA)
### 💻 Code

```ts
enum B {
    a = 'a',
    b = 'b'
}

class A {
    private readonly api = {
        [B.a]: {
            a: '1',
            b: '2'
        },
        [B.b]: {
            g: '2',
            h: '3'
        }
    } as const;

    get<T extends B>(k: T): A['api'][T] {
        return this.api[k];
    }
}

const a = new A().get(B.a); // will be any based on generated declarations
```

### 🙁 Actual behavior

```ts
declare enum B {
    a = "a",
    b = "b"
}
declare class A {
    private readonly api;
    get<T extends B>(k: T): A['api'][T];
}
```

### 🙂 Expected behavior

```ts
declare enum B {
    a = "a",
    b = "b"
}
declare class A {
    private readonly api: {
        readonly a: {
            readonly a: "1";
            readonly b: "2";
        };
        readonly b: {
            readonly g: "2";
            readonly h: "3";
        };
    };
    get<T extends B>(k: T): A['api'][T];
}
```

**Comment by MartinJohns** [comment]
I would expect the `A["api"]` to be substituted by the actual type. `private` members not having types in declaration files is intentional.

**Comment by BzenkoSergey** [comment]
> I would expect the `A["api"]` to be substituted by the actual type or this being an error. `private` members not having types in declaration files is intentional.

Make sense, but unexpected if you develop a library for external use and it doesn't provide correct types.
I changed my code from:
```ts
getApi<T extends Type>(type: T): CronQuartzUIService['api'][T] {
  return { ...this.api[type] };
}
```
to
```ts
getApi<T extends Type>(type: T) {
  return { ...this.api[type] } as CronQuartzUIService['api'][T];
}
```
and it generated correct declarations, but there is one more case I don't know how to be with:

```ts
getApi<T extends UnixType>(type: T): CronUnixUIService['api'][T];
getApi(type: UnixType) {
  const api = this.api[type];
  return api ? { ...api } : null;
}
```
