### ISSUE TITLE
Module path mapping

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#5003]
Many module libraries/tools(requirejs, systemjs) has a feature for module path mapping. They want to map module path to module name. Sometimes it is little bit annoying to specify a long relative module path when you can just specify the name of the module.

```typescript
import lib1 from 'my-custom-lib1';
```

Instead of:

```typescript
import lib1 from '../libs/my-custom-lib1';
```

I recommend it being configurable in `tsconfig.json`:
```json
{
  "paths": {
    "lib1": "libs/my-custom-lib1"
  }
}
```

Prior Art:
[RequireJS](http://requirejs.org/docs/api.html#config-paths)
[SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#map)

**Comment by mhegazy** [comment]
@vladima is working on adding this as part of #2338. we should close that one and open a new issue just for this part.

**Comment by tinganho** [comment]
Oops, sorry missed that.
