### ISSUE TITLE
Extended arrays act more like objects

### ISSUE THREAD

**Issue by johnfn** [Microsoft/TypeScript#5004]
Here's some code to explain what I'm seeing:

    class MyArray<T> extends Array<T> { }

    var specialArray = new MyArray();
    specialArray.push("value");

    var normalArray = ["value"];

    for (var i in specialArray) console.log(i);
    for (var i in normalArray) console.log(i);

The first loop prints out `0`, `length` and `constructor`. The second loop just prints out `0`. 

This ends up causing issues in other code that expects a normal array when I pass in an extended array. For example, if we put `<div> Hello! </div>` into `specialArray`, then `React.render(<span> { specialArray } </span>, someDiv)` will output `Hello! 1` because it iterates the keys of `specialArray` and prints out the length.

I can't seem to find any documentation on how extended arrays are supposed to work, so I'm not sure if this is expected or not, but I figured I'd bring it to your guys' attention. 

Thanks!

(By the way, I want to take this opportunity to tell you guys that TypeScript is quite seriously the best technology I've ever used. Keep it up!)

**Comment by RyanCavanaugh** [comment]
This is the expected runtime behavior according to the ECMAScript spec.

The root problem is that `length` on a normal `Array` object is a non-enumerable property, but when `push` sets the new `length` on the derived `Array` class, there is no own property for `length`, so the setting creates a new property slot on the derived object using the default configuration (which is not non-enumerable).

**Comment by johnfn** [comment]
Ah, I see. Thanks!

**Comment by weswigham** [comment]
If this is expected behavior by spec, this is _not_ the observed behavior as actually implemented by classes in node/v8.

Drop this into node 4:
```js
class MyArray extends Array { }

var specialArray = new MyArray();
specialArray.push("value");

var normalArray = ["value"];

for (var i in specialArray) console.log(i);
for (var i in normalArray) console.log(i);
```

See printed:
```js
0
0
```
as would be desired, I expect.

Would you happen to know the relevant portion of the spec, so we can file a bug against v8?

**Comment by RyanCavanaugh** [comment]
Unless there's some overriding language, step 9 of 'push' should be setting a property on the object

http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.push

> . 9. Let setStatus be Set(O, "length", len, true).

This should be roughly equivalent to:
```
 > var x = {};
undefined
 > Array.prototype.push.call(x, 10);
1
 > Object.getOwnPropertyDescriptor(x, 'length');
Object {value: 1, writable: true, enumerable: true, configurable: true}
```

**Comment by weswigham** [comment]
The 'set' spec operation will set the property on the parent property descriptor before creating a new one with defaults (9.1.9). Arrays have length as a nonconfigurable member (as mentioned 9.4.2), so it would make sense that length exists on Array subclasses and correctly inherits the base class's length property's behavior.

**Comment by kitsonk** [comment]
`Array.length` is an auto magical part of JavaScript.  The property doesn't conform to standard properties and it is impossible to create a subclassed Array in ES5 that behaves like an Array (you can sort of come close, by intercepting all the mutating functions and creating a accessor `.length`, IIRC there are still holes).  Many man have been lost about the rocks of subclassing Array in ES5.  It would seem logical to throw if someone is subclassing Array and targeting ES5.
