### ISSUE TITLE
TypeScript - Mistype with infered generic on multiple types type

### ISSUE THREAD

**Issue by quantumsheep** [microsoft/TypeScript#50045]
Does this issue occur when all extensions are disabled?: Not tested

- VS Code Version: 1.69.2
- OS Version: macOS Monterey 12.4

Steps to Reproduce:

1. Write the following code:
```ts
type Demo<T> = { a: "b" } | { b: "C" }

function example<T, U = T extends Demo<infer X> ? X : T>() { }

example<Demo<string>>();
```
2. Hover `example` on the last line
3. You should see the following:
```ts
function example<Demo<string>, unknown>(): void
```

`U` is mistyped as `unknown`. This only occurs with multiple types and intersections (`|` and `&` types).

**Comment by MartinJohns** [comment]
This is working as intended.

Type parameter inference is all or nothing: Either all type parameters are inferred, or none are. Since you already provided one type parameter yourself, no second type parameter is inferred.

You want #26349 / #26242.

**Comment by RyanCavanaugh** [comment]
`Demo<T>` doesn't reference `T`, and this is a location where TS uses structural inference. Therefore no candidates are collected.
