### ISSUE TITLE
`<out A,>() => {};` is parsed as JSX

### ISSUE THREAD

**Issue by thorn0** [microsoft/TypeScript#50043]
# Bug Report

### 🔎 Search Terms

variance jsx ambiguity

### 🕗 Version & Regression Information

Tried versions 4.7.4 and 4.8.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/MYewdgzgLgBAZiEMC8MA8ICusCCAaAPgAoBKFAmAbwF8BuIA)

### 💻 Code

The ambiguity between generic arrow functions and JSX is normally resolved by a trailing comma:
```ts
const foo = <A,>() => {};
// all is good
```
However, that trick doesn't work if there is a variance annotation:
```ts
const foo = <out A,>() => {};
// error: Identifier expected.
```

**Comment by DanielRosenwasser** [comment]
Variance annotations are only allowed on type parameters of type declarations - for example, this also doesn't work:

```ts
function foo<out A,>() {};
```

At best we could say that this is an error recovery bug, right?

**Comment by thorn0** [comment]
Oh, right. Closing then
