### ISSUE TITLE
Make use of type guards to allow returning narrowed values in a generic with conditional return type 

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#50059]
# Bug Report

### 🔎 Search Terms

generic narrow conditional return type guard

### 🕗 Version & Regression Information

4.0 and earlier

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAYg9nKBeKBvAUFLUBmCBcUwATgK4ToC+66okUAQgIbHJqbYBGLhJ5VNAMZwAdgGdgUbsQDKEADYRBwOMTFsA2gHImWgDRQtnfYcFaAulCbrh44OlsTcCOYuWqxKbQBMTWiH44FlY2ohI0dNDMsgpKKqwokXA4UiyucR4aIqQAtpwQxOYR4NDwcOnuCUQlyc7lsZViWbn5hcX0AOIQwACSwBA5AColADyDUBAAHv0i3urRFfFQAD6wLg3xAHxs41Mzc4xpG6pQAPyHrIRlANzt0P0SAIxsXb39Q6M6WpvXUAD0fwutBKRAgEgATC9un0BsNICMtL5tgC1nAaDhSCJlABLURQbFiBbHYgACg4WDExMIRLcS1WZUWqj0HAAlIRKbSTgSLozWBhsP9AQAJJgAN2xIgA5kRELZRQVJCooJiANYiOAAdxE+PUTHVwAAFgUdWJyAZOKRJNjgFp1PqiEaZWBsYIAHRQHrK2YFCR67wOphWyQ5UhODWqFXkwVQeTYlX3A2BqSWh0FaAsaBiOA5aBTQQQMDAXHiKAao3EaDWqDeOBgqD2nJMeNQSniCCuqMV4CkYjaknSXm69Sq9VakItkgSyUacws10SwTyUjeMEkjkZYgs27UdAYrFFvGS6HvMYTaYQWbzI6c1j09Y3zZrqlQQZsqCvGEfeGDbb87COSQ8DgK4EDYP8BSwIDeDICBmQFShbijADUmIakWDAqMBWkaCzSjHcBWxFISQJGkNyfG8WRZdgIOwSIoEmNgkhSddKl+FE6O5EQWGITUIG8TDsBRQYDW5blDUrMRTUrbUAEdyAkYt3ThCT6243j-QtSRBhkataztOBgybaBQ2gWpDVEkQ8GIRsDxEOCaOjKsazre0mHkeRNRlKAux7bUmCgUU3PIUsRMEA0oBssK63E3BMRxPEVxwCVrUUgSsB83sULYwECh44g8JoAUUQAeRwFIVGdQQDA8uAVXUWNm3EitbSsFsCxYQMJKkqBy3TdQYo4-TJDAHjIGIeQQFU4geI1PirBwfpWH8jLtV9d4L2ADsisBHotByKARu6UAWx7BMk3M9RE3UfIL28gtVH6f1GxESaixzMQttokFJsSGpmOJW4BRWuptyAA)

### 💻 Code

```ts
type Foo = {
    foo: true
}

type Bar = {
    bar: true
}

const barSelectors = ['a', 'b', 'c'] as const
const fooSelectors= ['d', 'e', 'f'] as const

type BarSelector = typeof barSelectors[number]

type FooSelector = typeof fooSelectors[number]

type GetItemType<T extends BarSelector | FooSelector> = T extends BarSelector ? Bar : Foo;

type test1 = GetItemType<'a'>; // Bar
type test2 = GetItemType<'d'> // Foo

function isBarSelector(
    selector: BarSelector | FooSelector,
  ): selector is BarSelector {
    // Having to convert to unknown is another issue, but it's not the topic. I understand that it must work
    // like that but there are some exceptions where it does not make sense.
    return (barSelectors as unknown as string[]).includes(selector);
}

function getItem<T extends BarSelector | FooSelector>(selector: T): GetItemType<T> {
    const foo: Foo = {
        foo: true,
    };

    const bar: Bar = {
        bar: true,
    }

    if (isBarSelector(selector)) {
        type x = typeof selector; // type is narrowed
        // This is the issue in question. Type is narrowed but TS does not make use of this information,
        // it does not allow to return a value which matches the function definition.
        return bar; // error
    }

    // Off topic, looks like there's a separate issue here as the type is not properly narrowed after a return statement.
    // I'm pretty sure that this has been reported many times.
    type y = typeof selector;
    return foo;
}
```

### 🙁 Actual behavior

TS recognizes that the type is narrowed in the scope, however, it does not allow to return a narrowed type which matches the definition of the function.

### 🙂 Expected behavior

There should be no error when returning the value.

**Comment by fatcerberus** [comment]
For `.includes()`, see https://github.com/microsoft/TypeScript/issues/26255.  Personally I would prefer to cast the selector there, not the array.  Then you don’t need to cast through `unknown` first (which is always questionable).

**Comment by mckravchyk** [comment]
@fatcerberus Thanks for linking the issue. Casting the selector does not  work, I tried that already: https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAYg9nKBeKBvAUFLUBmCBcUwATgK4ToC+66okUAQgIbHJqbYBGLhJ5VNAMZwAdgGdgUbsQDKEADYRBwOMTFsA2gHImWgDRQtnfYcFaAulCbrh44OlsTcCOYuWqxKbQBMTWiH44FlY2ohI0dNDMsgpKKqwokXA4UiyucR4aIqQAtpwQxOYR4NDwcOnuCUQlyc7lsZViWbn5hTQ4pCLKAJaiUN1i0RXxABQcWGIN8YRDU6pQAD6wLnPEehwAlISTbvH96rO78xjYUAD0Z1AAEkwAbt0iAOZEiLa3BZIqUJ0A1iJwAHcRPsrP9gAALAr7MTkAycUiSbrALTqMFESEvMDdQQAOigAElviJvAUJExieimIjJDlSE4AaofuNzpd5N0ftAIVSpAj0QVoCxoGI4DloBAAB6CCBgYC9cRQAGQ4jQJFQbxwCCouA0pgcqCTcQQHHM5XAUjEYEjaTDDwbHEPQTyUgksQjHYZVjWfUkB6PDYAbgEQA

**Comment by fatcerberus** [comment]
This works:
```ts
function isBarSelector(
    selector: BarSelector | FooSelector,
  ): selector is BarSelector {
    return barSelectors.includes(selector as BarSelector);
}
```

You have a `BarSelector[]`, and `.includes()` doesn't currently allow you to pass a wider type than the array.  So you need to cast the selector to a `BarSelector`, which is an allowed downcast because `BarSelector` is a subtype of `BarSelector | FooSelector`.  This is much cleaner IMO than casting the whole array to `string[]`.

**Comment by mckravchyk** [comment]
Oh, so it's like that. Thank you.

**Comment by RyanCavanaugh** [comment]
Duplicate #33912
