### ISSUE TITLE
Lambda parameters of interface implementation are unexpectedly considered different than those of the base class.

### ISSUE THREAD

**Issue by alexisthedev** [microsoft/TypeScript#50055]
# Bug Report

This might be related to the fixed issue #30071

### 🔎 Search Terms

error TS2416: Property * in type * is not assignable to the same property in base type *

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Common Bugs that aren't Bugs" and "Type System Behavior"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIIB4AqA+ZBvAKAEgBbATxIjAAsB7AE3QDEBGAGmSYCZkIAPSCHoBnTi2wAKADZwSAI3pwAXMgkAHFitYc1XLVwCUyALy5MBlQDdawegQC+BQNAEBBDOGiAQsmAk1UiEpwUQwAZTAoUABzXEJSCio6Rm1OHn5BETFJGXlFFXVNMR09VKNTZHDIkCiLZGtbZHxkKCoAVygQAG5kR3sgA)

### 💻 Code

```ts
interface A<T> {
	mymethod<F1, F2 extends F1>(lambda: (p1: F1, p2: F2) => T): void
}
​
class B implements A<String> {
	mymethod<F1, F2 extends F1>(lambda: (p1: F1, p2: F2) => String): void  { return; }
}
```

### 🙁 Actual behavior

The compiler rejects the program with the following error message

```
test.ts:6:2 - error TS2416: Property 'mymethod' in type 'B' is not assignable to the same property in base type 'A<String>'.
  Type '<F1, F2 extends F1>(lambda: (p1: F1, p2: F2) => String) => void' is not assignable to type '<F1, F2 extends F1>(lambda: (p1: F1, p2: F2) => String) => void'. Two different types with this name exist, but they are unrelated.
    Types of parameters 'lambda' and 'lambda' are incompatible.
      Types of parameters 'p2' and 'p2' are incompatible.
        Type 'F1' is not assignable to type 'F2'.
          'F2' could be instantiated with an arbitrary type which could be unrelated to 'F1'.
6  mymethod<F1, F2 extends F1>(lambda: (p1: F1, p2: F2) => String): void  { return; }
   ~~~~~~~~
Found 1 error in test.ts:6
```

### 🙂 Expected behavior

Compile successfully

**Comment by fatcerberus** [comment]
Not related to the issue but [don't use `String`.](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#number-string-boolean-symbol-and-object)

**Comment by alexisthedev** [comment]
@fatcerberus

The type of T does not matter for the bug to trigger. The result is the same even if we use 'string'.
I know that the boxed objects shouldn't be used in TypeScript, however it doesn't matter here, it is purely used for presentation.

**Comment by fatcerberus** [comment]
I know, that’s why I said it wasn’t related to the issue, I just wanted to let you know because a lot of people come from e.g. C# and think `string` and `String` are synonyms.

**Comment by RyanCavanaugh** [comment]
Duplicate #31570
