### ISSUE TITLE
Compiler strips comments from classes

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#50053]
# Bug Report

### 🕗 Version & Regression Information

ts stable `4.7.4` & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/PTAEGMHsFtoUwHYBcBQcAeAHSAnJEAbAQwGcTQBBUAbxQEgQIZ5kUBfIA)
    
### 💻 Code

```ts
// comment
export class A {
	// comment
}
```

### 🙁 Actual behavior

```ts
// comment
export class A {
}
```

### 🙂 Expected behavior

```ts
// comment
export class A {
	// comment
}
```

**Comment by RyanCavanaugh** [comment]
See https://github.com/microsoft/TypeScript/issues/32813#issuecomment-522147385
