### ISSUE TITLE
Bad autocomplete suggestions for unioned tuple types at specific positions

### ISSUE THREAD

**Issue by johnsonjo4531** [microsoft/TypeScript#50056]
# Bug Report

It appears Union tuple types give bad autocomplete suggestions (ones in which when I choose them they give me red underlines afterwards).

Say for example I have the following lines of code:

```ts
type Q =
	| ["foo"]
	| ["foo", "bar"]
	| ["baz"]

const q: Q = ["foo", ""]
```

[Playground link](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAilC8AoAkAHygbQEQDMD2eWAuiutvoQDRRYBGAhgE7GmZYCOArgB4uIDGeAHYBnYFHYAuWAjYUs1Djz5A)

If I autocomplete at the empty string on this line: `const q: Q = ["foo", ""]`. It will incorrectly suggest `"foo"` and `"baz"`. If I take the suggested autocomplete as one of these two however TypeScript will then recognize that it is incorrect and give me a red underline.

If I however, as below, remove the union type and just have one tuple the autocomplete correctly suggests only `"bar"` as the only proper value.

```ts
type Q =
	| ["foo", "bar"]

const q: Q = ["foo", ""]
```

[Playground link](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAilC8AoAkAHygbQEQDMD2eWANFFgEYCGATlgLqKIDGeAdgM7BQCOAXLAplwFipOgyA)

### 🔎 Search Terms

Union tuple autocomplete

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union tuple types giving bad autocomplete suggestions.

### ⏯ Playground Link

A more full playground link demonstrating the problem.

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAilC8AoAkAHygbQEQDMD2eWAuiutvoQDRRYBGAhgE7Gma4FbV30BeLabCpxrAAFowgR+ZdlRHjJw9gFdmJAdgCOygB7S22vVyFEA3IkQB6S5gDGwRgBsiAagwBnMPVsQiUesrAeLZ4ALZgjhDA0AAUAJYAdu5xACbQYtAQ4aBQ7g6JAOYAlLmieMqOKVC0jIVQymBQeAmOIDQMzFwMfFxiElIAdFY2AJJJ0fRVccDVtQkF7vWN3J3tvEpCXIZKfYpDIeNQmgBcsAiCHFwsw1AAYniMUBA69OGR-glQce7uytAA7tNRFAMv5aHgAG7Qb5HXRQABkUAoX0WASCITeUQgKWotECINEEDaTGgtkiTFaUASeBmEPojlSAyZNwACgMAMoDAkQdzpf54J4vTGLWgQRx4f7+CS5BpgPC8qpBJH0OKOLkjGYw0H0cFQ-yBYJhCJYgn0Gb08X-RYgcoggWihkQPUZXlS6B0hlVD1-dz7Zp5ZWqwoARlOcHgFzkWG2JAOAZwKoZ8wATGHzuRLjQTBZrFAAEL4sr-J0QR5iQqLBkAa2g3D4UHQKywDfk-Wb-MYVf8i2ekHs2L9hy8PxDaYjGaj3RYcZmw+SKbHkaUHWn-tn9BH8wAzIuJzsFFISIggA)

### 💻 Code

```ts
type Q =
	| ["foo"]
	| ["foo", "bar"]
	| ["foo", "baz"]
	| ["foo", "three"]
	| ["foo", "three", "four"]
	| ["qux"]
	| ["qux", "foo"];

// [ctrl]+[space] autocomplete (inside the empty string) should bring up only "bar", "baz", "three".
// Instead it brings up "bar", "baz", "foo", "qux", "three".
const q: Q = ["foo", ""]

// For example an issue with the above is qux & foo is autocompleted, but they are clearly not valid...
// P.S. these two examples below are supposed to fail. It is the above autocomplete that allows you to believe these are valid values.
const failing1: Q = ["foo", "qux"]
const failing2: Q = ["foo", "foo"]

// But however things like "baz" | "bar" | "three" work as expected.
const passing1: Q = ["foo", "baz"]
const passing2: Q = ["foo", "bar"]
const passing3: Q = ["foo", "three"]

```

### 🙁 Actual behavior

Autocomplete suggests the wrong type at a given position for unioned tuple types. It gives types that when chosen will then result in a type-error.

### 🙂 Expected behavior

It will only auto-complete types at a given position in the array in which no subsequent type-errors will be given i.e. it will autocomplete union types only when they are in the proper place in the tuple.

**Comment by RyanCavanaugh** [comment]
Duplicate #46457

**Comment by johnsonjo4531** [comment]
@RyanCavanaugh I agree this is a duplicate. I'm closing this issue now, thank you!
