### ISSUE TITLE
Unexpected Error for conditional type parameter if value is generic typed

### ISSUE THREAD

**Issue by DerZyklop** [microsoft/TypeScript#50066]
# Bug Report

### 🔎 Search Terms

generic
conditional type
error

### 🕗 Version & Regression Information

Happens in every version available in TS Playground, including Nightly.

- ~This is a crash~
- ~This changed between versions ______ and _______~
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _generics_ and _conditional type_
- ~I was unable to test this on prior versions because _______~

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noStrictGenericChecks=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=false&noPropertyAccessFromIndexSignature=true#code/MYewdgzgLgBAJiAyiAtgUygCwJZgOYwBcMAPACoB8AFAFAwy4AOArrMVWTGgB5RphwIMZgLQAzXGjgwA-DDBoAbmgBORGGQCUMAD7zmAGwM1tAXgoxFIbNNMwqTVmYsBvOjFCQQBtADoDIHgOYCxQmgDcNAC+NLEA9ABUGphowgrcjGjAfNIAoioqIGoJcbGe0DBiItnY4ADq2FgA4vyq2MBkAJ6ZMHbkXLz8gjDQKrgEemCGBtSObBrOMG70CMjoWOPBoREwcXEw+YUqxF09AOSj42cMQmAgsACGEBDYeGAPAEY+MFAgP92pM6cHh8ARCERwcSSaRyBTKNQnM6+aKxGiJGAAKWYFQgqFSfGgQl+MEYhRAyh+mAesCwqRUaAqIDEMBQnQ8IEhNxgAHcigBrcYwJ4DTLZKSAMgIYCUyuAKnh6RhBcRLvhdPojL0YABZamYXwqB4CVBUbQWAAMvgArLIYGcABJoIwga7EKZGSKrPEbfBUeVoRX4CIyyCwP0BvANLB1Qr4U6pZVQMaqvQQqEKWza3X6w0IFAmmDmq02+2OgIutKQiTpyJ7GAAASgEAAtDxRVAWwUijAm03kql0rBVEcuVW-DRPescD6w1BxpHMNHwHg4zta4ciicAbbU6O4NdsLd7kLnq93l98X8oFuLonBZNpkjYlUwDV6o1MC0FGMOgDfQrZ4GNb7A2zatlk7ZDl2PZ9vIIJcJ2agHpUkjIs+r5gPOn5tD+mR-v6AERu+i6xgCq5xAABeuxwwAAgioeDMOgYCwEy-znCqEwVmmUj7oejwnm8nzfMSjAPAa6yqDArFXuxt7JuqBiPkAA)

### 💻 Code

```ts
const doSomething : <T>(
  input : (T extends undefined ? never : T) | null
) => void = (input) => {
  console.log(input);
}


/* The unexpected Error */
const functionWithGenericType = <T extends string | null>(input : T) => {
  doSomething(input); // Error: Type 'string' is not assignable to type 'T extends undefined ? never : T'.
}

/* Just some test to proove that the rest of my code is working as expected… */
const greeting : string | null = Math.random() > 0.5 ? 'Hello' : null;
doSomething(greeting); // No Error. As expected.

```

### 🙁 Actual behavior

An error appears when calling `doSomething(input)` from inside a function with generic typed input.

### 🙂 Expected behavior

No Error appears.

**Comment by MartinJohns** [comment]
Resolving of conditional types involving unbound generic type arguments is deferred. At that point the compiler doesn't know what `T extends undefined ? never : T` resolves to, because the compiler doesn't know what type `T` is. Constraints are not taken into consideration. Same as https://github.com/microsoft/TypeScript/issues/48243.

When actually calling the function the type argument is not unbound anymore, so the conditional type can be resolved.
