### ISSUE TITLE
Object returned from a function can have keys not present in its return type

### ISSUE THREAD

**Issue by Dwlad90** [microsoft/TypeScript#50064]
# Bug Report

When a function is typed to return an object of a certain type, the properties of the object can be expanded, meaning extra properties can be added to the ones described in the type or interface.

### 🔎 Search Terms

function return object type 

### 🕗 Version & Regression Information
This is observable on the playground in all available versions.

Couldn't find anything I understood to be relevant in https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs

- This is a crash: No
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about interfaces and types of function return values

### ⏯ Playground Link
[Buggy example on `@next`](https://www.typescriptlang.org/play?ts=4.8.0-beta&ssl=9&ssc=22&pln=9&pc=6#code/JYOwLgpgTgZghgYwgAgEoQM4FcA2ZkDeAsAFDLnIwD2VAXMhmFKAOYDcpAvqaWAJ4AHFADEsIBMgC8yABQBKKQD40mXGB4kEVEI2QgqAUShQqUWqPFTZCycpnEylGvQDkjZiBYBGFwBpS5AD0gcgAAmAYALQQAB5CCGDRxqYByABGcGbIAEz+JJxyHCSkWjr40CZmFhLS8vTo2HhKsg7k1HTIbkysPnlBIeFRsfGJFSmOGVm5XIUapbpjUNnmYjXW9RBgWFAgACqCEAA81cq2Lantru49fqnBYRHRcRAJSZWpk-TT+YVAA)

### 💻 Code

```ts
interface Result {
    foo: string;
}

type Func = () => Result

const noError:Func = () => ({
  foo: 'string1',
  // @ts-expect-error
  bar: 2,
});

const error:Func = (): Result => ({
  foo: 'string1',
  // @ts-expect-error
  bar: 2,
});

const error2:Func = (): ReturnType<Func> => ({
  foo: 'string1',
  // @ts-expect-error
  bar: 2,
});
```

### 🙁 Actual behavior

Extra properties in the returned object, which aren't defined in the interface or type, do not raise an error.

### 🙂 Expected behavior

Extra properties in the returned object, which aren't defined in the interface or type, should raise an error.

**Comment by MartinJohns** [comment]
This is not a bug. The return type is not specified, so it's inferred. The inferred return type is then checked for compatibility, and it's compatible.

**Comment by RyanCavanaugh** [comment]
See also #241
