### ISSUE TITLE
`export {_default as default}` + `import x` results incorrect for `node16` resolution

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#50067]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAQwK4wgSXNeAzKERwDkSAdmADZIDmwJAtMqnaJLAPQBuwMApoQFAsscAN5wAJj2y0eAYQglpVOAF84ufES68AzjDYBjBUoH8eAD1bxJ2ZOWtSZ8xcCoAKEfzhwK1WjoAuOABtL29EFHRMWA8w8LghWECtbh49QgAaONUASizvAF18uF0YIM94ow4eKAQqHnLs7ygeKxqg4MJyKsyiACsdBUIi7JVisf4VHKA)

reproduction https://github.com/un-ts/lib-boilerplate/blob/main/vitest.config.ts#L8

### 💻 Code

```ts
import autoImport from 'unplugin-auto-import/vite'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [
    autoImport({
      imports: 'vitest',
    }),
  ],
  test: {
    coverage: {
      reporter: ['lcov', 'json'],
    },
  },
})
```

### 🙁 Actual behavior

```ts
vitest.config.ts:6:5 - error TS2349: This expression is not callable.
  Type 'typeof import("/Users/JounQin/Workspaces/GitHub/domiso/node_modules/.pnpm/unplugin-auto-import@0.10.1_2rke2oyl5nfm2lrwejsnq3sdfe_zhxiakfykinkigydwrmzev47um/node_modules/unplugin-auto-import/dist/vite")' has no call signatures.

6     autoImport({
```

### 🙂 Expected behavior

No error

**Comment by weswigham** [comment]
`unplugin-auto-import` [has a broken export map](https://github.com/antfu/unplugin-auto-import/blob/main/package.json#L49). Their export map defines all their entrypoints as cjs only - they need a nested `types` entry for both the `require` and `import` conditions that points a _different_ files with the correct module format. This is exactly the format confusion issue that arises when you use an incomplete export map.
