### ISSUE TITLE
`document.documentElement` could be `null` actually

### ISSUE THREAD

**Issue by JounQin** [microsoft/TypeScript#50078]
# Bug Report

### 🔎 Search Terms

`document.documentElement`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYewxgrgtgpgdgFwHSkrRBRANjdCAEA9IfgAYASAKgLIAy2u8BAPvnBFlqfjAB4AOMMAhjAAUGNTQmKcNMw48SAE64QANxgAKAJRESpKUqNMGebgEsAzmXaducEAHcxQA)

### 💻 Code

```ts
document.documentElement // `HTMLElement | null` expected

document.documentElement.remove() // `document.documentElement` is `null` now
```

### 🙁 Actual behavior

<img width="523" alt="image" src="https://user-images.githubusercontent.com/8336744/181451808-b060b290-a6d6-481c-b11d-80c1aa368285.png">

### 🙂 Expected behavior

```ts
readonly documentElement: HTMLElement | null
```

**Comment by JounQin** [comment]
I don't think they are same, `document.documentElement!` is very easy to handle the **impossible** `null` value.

**Comment by RyanCavanaugh** [comment]
I don't think this is a condition we need to make all programs concern themselves with. If you remove the element, please put it back before someone else notices it's gone 😅

**Comment by JounQin** [comment]
> If you remove the element, please put it back before someone else notices it's gone 😅

I'm working on a DOM sanitizer at https://github.com/un-ts/domiso/blob/main/src/index.ts#L68, and it could be a `parsererror` on parsing `svg`, I don't think I should add `document.documentElement` back?
