### ISSUE TITLE
I get a code action suggestion on every line of a method, when it affects the signature

### ISSUE THREAD

**Issue by roblourens** [microsoft/TypeScript#50077]
I'd only expect to see this when my cursor is on the method signature. This is https://github.com/microsoft/vscode/blob/4dc272701b0a6e5cf59cfc38d1e08f8862604b05/src/vs/workbench/contrib/notebook/common/notebookEditorModelResolverServiceImpl.ts#L164

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/323878/178034997-69dc8fbf-0fd7-4b97-bb3a-b94611c87b77.png">

**Comment by mjbvz** [comment]
Minimal example:

```ts
function foo(a: string): void;
function foo(a: number): void;
function foo(a: number | string): void {
    console.log(123);
}
```

We should likely only show this refactoring when you are on the function signatures themselves

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
