### ISSUE TITLE
string: value interface not assignable to Record<string,unknown>

### ISSUE THREAD

**Issue by mikeybinnswebdesign** [microsoft/TypeScript#50087]
# Bug Report

### 🔎 Search Terms

unknown record
Index signature

### 🕗 Version & Regression Information

Bug initially found in v4.7.4
Oldest found version with bug v3.5.1 in typescript playground
Bug found in nightly version v4.8.0-dev.20220728

- This changed between versions v3.3.3 and v3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/JYOwLgpgTgZghgYwgAgPIBsAmAFKB7ABwGdkBvAKAEgQ4BbCALmQFcQBrEPAdxAG5yAvuXJgAngRQA5CF1yESAXmQAlCAjxRMAHiJgooAOYAaFu048AfPwD015BvK3kYicmmz8xZEtLIA2mwQogy6+iAGALoMrBzcIMgC-OQwrAhgwHjxkLoAFHhYcsQMGDieRACUZOTINcjqILrIBGUM7oWK9gVl-LXIUBBgzFDxzfL8AkA)

### 💻 Code

```ts
interface OldProps {
  name: unknown;
}

type NewProps = Record<string, unknown>;
// or
// type NewProps = { [key:string]:unknown };

function test(oldProps:OldProps) {
  const props:NewProps = oldProps;
  return props;
}
```

### 🙁 Actual behavior

OldProps type is not assignable to NewProps.
Typescript returns the following error:
```
Type 'OldProps' is not assignable to type 'NewProps'.
  Index signature for type 'string' is missing in type 'OldProps'
```
Error is consistent with old style record syntax.
Error is consistent if OldProps["name"] type is `string` or `any`
Error not found if NewProps = Record<string, any>;
Error also not found if `[key:string]:[whatever type]` is added to OldProps (triggers different expected error if type conflicts with name).

### 🙂 Expected behavior

OldProps type is assignable to NewProps.

**Comment by jcalz** [comment]
This is working as intended.  Interface types don't get implicit index signatures as per #15300.  The behavior where `{[k: string]: unknown}` is [treated more strictly](https://github.com/microsoft/TypeScript/pull/30637/commits/5dce9909b63ce34925699910f74ee9f0de1aead4) than `{[k: string]: any}` was implemented in #30637, released with TS3.5, and was a [documented breaking change](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#-k-string-unknown--is-no-longer-a-wildcard-assignment-target).

**Comment by mikeybinnswebdesign** [comment]
Okay, looks like for my use case, I should be using a type alias instead of an Interface, and (i cut this from the reproduction) instead of extending the interface, I need to intersect two type aliases.
Thanks for your help 😄

**Comment by the0rem** [comment]
@jcalz we're trying to upgrade from typescript 4.3.5 to 4.6.4 and are now receiving this error.

Previously an interface like below would allow an interface to be passed in as the generic:
```
export interface IIntegration<
  T extends Record<symbol, unknown> = Record<symbol, unknown>
> {
  type: IntegrationType;
  data: T;
}
```

If this has been a breaking change since 3.5 I'm at a loss as to why this would be happening now?
