### ISSUE TITLE
Support "use strong"; prologue

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#5010]
v8 (and node 4) have an in-progress implementation of the proposed [use strong](https://developers.google.com/v8/experiments) mode. According to [this presentation](https://drive.google.com/file/d/0B1v38H64XQBNT1p2XzFGWWhCR1k/view) there are plans to make a formal proposal to the ECMA at some time in the future, but given that both chrome and node already implement much of it (albeit behind a flag) it could be used/useful already. Minimally, we could start by recognizing the "use strong" prologue as a form of "use strict".

**Comment by kitsonk** [comment]
For those who don't want to dig through the presentation, outside of run-time enforcement of typings (in the TypeScript style) strong mode enforces the following:

 - Remove support for <code>var</code>, instead <code>let</code> or <code>const</code> would be used.
 - No undeclared variables
 - No use before declaration, except for recursive function calls.
 - Accessing missing properties throws
 - Objects created in strong mode are not extensible
 - Non-configurable properties cannot be frozen
 - class prototypes are frozen
 - class instances are sealed
 - methods require proper instances
 - Array are non-sparse
 - `arguments` is eliminated (use `...args`)
 - calling with too few arguments throws (use optional args)
 - No implicit coercion (except toBoolean)
 - `==` and `!=` require compatible `typeof`

There is a lot more on the "StringScript" typing that the presentation doesn't make fully clear.  I also haven't (yet) tried to see what they have built so far.  There is clearly some parts of the second part of the proposal, around typing that wouldn't be fully compatible with TypeScript (for example they have nominal classes for structural typing, they allow explicit typing of `this`, etc.)

**Comment by weswigham** [comment]
The typing parts of their proposal are a separate "SoundScript" extension and are proposed to be used with the prologue `"use strong+types";`. For now, that part seems a longer way off than the simple strong mode semantic changes, so I don't think we need to worry about it yet. For a minimum amount of work, `"use strong ";` is supposed to include all use strict restrictions, so we could begin by recognizing it as a form of the use strict prologue.

**Comment by jbondc** [comment]
Seems a bit early, it's an interesting way "scaling up" complexity and stronger constraints.

I'd add remove ```delete``` and possibly other things. Would be nice to have a discussion on impacts to type system.

**Comment by sebilasse** [comment]
also: https://www.sitepen.com/blog/2015/10/08/stronger-javascript/

**Comment by ivogabe** [comment]
+1 on this one. The emit must change in some situations, for example an enum should use a `const` instead of a variable and (if I understand correctly) the whole enum should be written as one big object literal. Helper functions should be written using a `const` (or `let`) too and I'm not yet sure if decorators can be used.

**Comment by jbondc** [comment]
Hmm looks like they did remove ```delete```:
https://github.com/v8/v8/blob/b104a67ef0a50beab2dc85a6ac5732c696d07698/test/mjsunit/strong/delete.js

Elaborate list here:
https://github.com/v8/v8/search?p=2&q=strong&utf8=%E2%9C%93

**Comment by jbondc** [comment]
Probably would prefer if ```undefined``` was just a constant:
https://github.com/v8/v8/blob/163419e8fa20b5a6730f874ccdb092ef51739600/test/mjsunit/strong/undefined.js

Bikeshedding on the name:
```
use "safe"; // mode
use "programmer"; // mode
```
Then you could a third one just for more complexity:
```
use "system"; // mode
```
For low level-stuff.

**Comment by jbondc** [comment]
Good presentation here by Ben (strong mode at 27:23):
https://www.youtube.com/watch?v=z92Xm9VlPjM

**Comment by weswigham** [comment]
[Strong mode is dead](https://groups.google.com/forum/m/#!topic/strengthen-js/ojj3TDxbHpQ), so we don't need to worry about supporting it. Though I'd still keep an eye on what their type annotation plans are.
