### ISSUE TITLE
Compiler API: Incorrect number of type arguments for self-referential extends

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript#50105]
# Bug Report

### 🔎 Search Terms

type argument count, number, type parameters

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, no relevant FAQ

### ⏯ Playground Link

[ts-ast-viewer Playground link with relevant code](https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgGIHt0B4CCA+ZAbwF8AoUmAVxATGHRGRk12QgA9IQATAZzRb48ACnYAuZDgCUEnEVIB6BchWq16jQD1tOyQDoA5hDABhBrzBQ4oMMKl6wATwAOEHFAOUAthHC89ADa+BmAAFsgAvBHIAEyKyhqJiTq6OHoI5pbW4A4ubh7evmD+QSAh4VHIAIzIwjbQIHABUqQqUMaUUIzspGTxyADyrowARlDoAO680MjcEABuYJgBvP0AStRi-QihEAgA1tCGxgDKwAaNYJ0QqONeACJ7AXBWdAzCvOidSKjAQXoWOCQHx+ADaVQAui0lKpcq4AAovOA+SBQXiggAMEOOpkyVhsdjh+U8IOK5BhABVQsB+O0rl1+DFkE5XMgXiSirwADTIEDoMDVHlwfgcVy0CDcPRAA)

### 💻 Code

```ts
interface Foo<A> {}

function foo<A extends Foo<A>>(x: A): A {
//                     ^^^^^^ A.getConstraint().typeArguments.length == 2
//                     ^^^^^^ A.constraint.typeArguments.length == 1 (internal)
  return x
}
```

### 🙁 Actual behavior

The self-referential type parameter of `foo` appears to cause the number of type arguments to be incorrectly calculated. Getting the type arguments as shown in the code above returns an extra type argument.

### 🙂 Expected behavior

Return the number of type arguments actually present.

---

Originally reported in the `#compiler-api` channel in the TS discord, @sandersn requested a real bug report.

> **Gerrit0** — 07/23/2022
Why does the compiler API sometimes return extra type arguments?
https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgGIHt0B4CCA+ZAbwChlkZMAKMAC2AGcAuZHAGmQA9mcBKb4gL7FiMAK4gEYYOhDlMuZBA6QQAE3pp5+PJS4t2AT258WRUsigQwoqLI4A6CukoGeAbkFA
[TypeScript AST Viewer](https://ts-ast-viewer.com/)
Interactive viewer to help visualize the TypeScript Compiler API's AST.
Click on the FunctionDeclaration in the center, then run signature.typeParameters[0].getConstraint().typeArguments... which gives a length of 2, not 1
Interestingly, using .constraint instead of .getConstraint() returns the expected number of type arguments.
**cspotcode** — 07/23/2022
>Wait, ast viewer lets you type commands like that?
**Gerrit0** —  07/23/2022
Yeah, stick that in the browser console
**cspotcode** — 07/23/2022
ohhhhh
**Gerrit0** —  07/23/2022
but .constraint is marked @internal
**cspotcode** — 07/23/2022
wait and both items in that array are the same object
is this a case where two codepaths return the same constraint, and it was a performance hit to deduplicate?  total guess
**Gerrit0** — 07/23/2022
Yeah, it smells like a bug to me
https://github.com/microsoft/TypeScript/pull/20162/files#r152389634 ahhh, so I guess I want getConstraintFromTypeParameter... which isn't exposed
**Nathan Shively-Sanders** — 07/25/2022
I tried this and it didn't work. Is it a problem to have the console split out into a separate window?
**cspotcode** — 07/25/2022
I wouldn't think so; I assume ast viewer is just spamming global variables onto the window object to enable conveniences like this
**Gerrit0** — 07/25/2022
It depends on which AST node you have selected; the globals are tied to the same stuff shown on the right
**Nathan Shively-Sanders** — 07/26/2022
well, I got it to work by clicking FunctionDeclaration on the AST pane to select the whole function. Just clicking the keyword or the function name in the text pane didn't work.
**Nathan Shively-Sanders** — 07/26/2022
OK, I got it to repro and it 50% looks like a bug in getConstraint, which calls into getResolvedBaseConstraint. The confusing element is the this parameter, which shouldn't introduce a this type, but might by mistake?
**Gerrit0** — 07/27/2022
Sorry, I should have simplified this more before posting it. This does the same thing:
> ```ts
> interface Foo<A> {}
> function foo<A extends Foo<A>>(x: A, y: A): A {
>  return x
> }
> ```
> I believe the cause is the self-referential type parameter.
**Nathan Shively-Sanders** — 07/27/2022
Do you mind filing a bug for that?
**Gerrit0** — 07/27/2022
Will do

**Comment by sandersn** [comment]
`getResolvedBaseConstraint` returns 2 types in for resolvedTypeArguments for this program too:

```ts
interface Foo<A> {}

function foo<A extends Foo<{}>>(x: A): A {
//                     ^^^^^^ A.getConstraint().typeArguments.length == 2
//                     ^^^^^^ A.constraint.typeArguments.length == 1 (internal)
  return x
}

foo(100)
```

The constraint is not circular in this case.

**Comment by sandersn** [comment]
The 2-element array returned by `getConstraint()` is correct -- it includes the `this` type of `Foo` as the second argument on purpore. Internally, you have to know not use to `.constraint` but to call `getResolvedBaseConstraint`/`getConstraint` (depending on whether you're in the compiler or services). But this is true of most properties on the core types by now. It's likely a cause of bugs, and pain when learning to write compiler code, so we really need a way to indicate that properties have accessor functions that should be used instead.

I'm not sure how to document the `this`-type structure of type arguments to object type -- it's not specific to `getConstraint`, or even particularly relevant. The wiki contains some documentation on type structure, but I couldn't find anything on type parameters or instantiation of generic types.
