### ISSUE TITLE
tsc cli converts dynamic import to require

### ISSUE THREAD

**Issue by Dabada** [microsoft/TypeScript#50109]
# Bug Report

### 🔎 Search Terms
dynamic import

### 🕗 Version & Regression Information

```
[System Information]
OS Version     : Windows 10
NodeJS Version : v16.11.1
YARN Version    : 1.22.5 

typescript   : 4.7.4
```

### ⏯ Playground Link

[Playground link ](https://codesandbox.io/s/nest-cli-build-convert-dynamique-import-into-require-e2o24v?file=/src/app.service.ts)

### 💻 Code
```
import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  async getHello() {
    const queue = new (await import('p-queue')).default({ concurrency: 2 });
    queue.add(() => this.action(1));
    queue.add(() => this.action(2));
    queue.add(() => this.action(3));
    queue.add(() => this.action(4));
    queue.add(() => this.action(5));

    return 'Hello World! 1';
  }

  private async action(i: number) {
    return Promise.resolve(i);
  }
}
```

### 🙁 Actual behavior

When I use the dynamic import of commonJS, nest build converts it into a require inside a resolved promise.

My code
`const queue = new (await import('p-queue')).default({ concurrency: 2 });`

Code generated by nest buid:
`const queue = new (await Promise.resolve().then(() => require('p-queue'))).default({ concurrency: 2 });`

this conversion leads to the following error at runtime:

`Error [ERR_REQUIRE_ESM]: require() of ES Module .\node_modules\p-queue\dist\index.js from .\dist\mailer\mail\mail.service.js not supported.
Instead change the require of index.js in .\dist\mailer\mail\mail.service.js to a dynamic import() which is available in all CommonJS modules.`

### 🙂 Expected behavior

Keep the dynamic import as is. It works fine.

I've change the code generated by tsc build in dist directory, and replaced 

`const queue = new (await Promise.resolve().then(() => require('p-queue'))).default({ concurrency: 2 });`
BY
`const queue = new (await import('p-queue')).default({ concurrency: 2 });`

no more errors and everything works fine.

**Comment by Josh-Cena** [comment]
This is working as intended. Dynamic import is not part of the CommonJS module system, but is part of the ESM system which happens to available in scripts (hence in CJS modules). If you want to avoid downleveling dynamic import, use `module: "node16"` or `module: "nodenext"` instead.

**Comment by sorgloomer** [comment]
@Josh-Cena That's unfortunately not an option for many projects, as changing to `module: 'node16'` would require us to migrate the whole project including all static imports to ESM, which is more work and on top of that has the "TS2835 explicit file extensions" controversy. Because of that, I prefer to stay on `commonjs`, and occasionally rely on `import()` for esm-only dependencies.
