### ISSUE TITLE
Invert the order of Error reporting.

### ISSUE THREAD

**Issue by NullVoxPopuli** [microsoft/TypeScript#50107]
# Suggestion

## 🔍 Search Terms

better errors

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Invert the order of errors reported in a single error.  

## 📃 Motivating Example

**For example, this error, reported in some XState usage:**

Type '{ ROTATE: { target: string; actions: AssignAction<unknown, EventObject>; }; RESIZE: ({ cond: (ctx: { manualOrientation?: boolean | undefined; }) => boolean; target: string; } | { ...; } | { ...; })[]; }' is not assignable to type 'TransitionsConfig<{ container?: HTMLElement | undefined; observer?: ResizeObserver | undefined; maximize?: (() => void) | undefined; minimize?: (() => void) | undefined; manualOrientation?: Direction | undefined; actualOrientation?: Direction | undefined; }, ({ ...; } & ContainerFoundData) | ... 6 more ... | { ...; ...'.
     Types of property 'RESIZE' are incompatible.
       Type '({ cond: (ctx: { manualOrientation?: boolean | undefined; }) => boolean; target: string; } | { cond: (ctx: Context) => boolean; target: string; actions: string[]; } | { target: string; actions: string[]; })[]' is not assignable to type 'TransitionConfigOrTarget<{ container?: HTMLElement | undefined; observer?: ResizeObserver | undefined; maximize?: (() => void) | undefined; minimize?: (() => void) | undefined; manualOrientation?: Direction | undefined; actualOrientation?: Direction | undefined; }, { ...; }>'.
         Type '({ cond: (ctx: { manualOrientation?: boolean | undefined; }) => boolean; target: string; } | { cond: (ctx: Context) => boolean; target: string; actions: string[]; } | { target: string; actions: string[]; })[]' is not assignable to type '(TransitionConfig<{ container?: HTMLElement | undefined; observer?: ResizeObserver | undefined; maximize?: (() => void) | undefined; minimize?: (() => void) | undefined; manualOrientation?: Direction | undefined; actualOrientation?: Direction | undefined; }, { ...; }> | TransitionConfigTarget<...>)[]'.
           Type '{ cond: (ctx: { manualOrientation?: boolean | undefined; }) => boolean; target: string; }' is not assignable to type 'TransitionConfig<{ container?: HTMLElement | undefined; observer?: ResizeObserver | undefined; maximize?: (() => void) | undefined; minimize?: (() => void) | undefined; manualOrientation?: Direction | undefined; actualOrientation?: Direction | undefined; }, { ...; }> | TransitionConfigTarget<...>'.
             Types of property 'cond' are incompatible.
               Type '(ctx: { manualOrientation?: boolean | undefined; }) => boolean' is not assignable to type 'Condition<{ container?: HTMLElement | undefined; observer?: ResizeObserver | undefined; maximize?: (() => void) | undefined; minimize?: (() => void) | undefined; manualOrientation?: Direction | undefined; actualOrientation?: Direction | undefined; }, { ...; }> | undefined'.
                 Type '(ctx: { manualOrientation?: boolean | undefined; }) => boolean' is not assignable to type 'ConditionPredicate<{ container?: HTMLElement | undefined; observer?: ResizeObserver | undefined; maximize?: (() => void) | undefined; minimize?: (() => void) | undefined; manualOrientation?: Direction | undefined; actualOrientation?: Direction | undefined; }, { ...; }>'.
                   Types of parameters 'ctx' and 'context' are incompatible.
                     Type '{ container?: HTMLElement | undefined; observer?: ResizeObserver | undefined; maximize?: (() => void) | undefined; minimize?: (() => void) | undefined; manualOrientation?: Direction | undefined; actualOrientation?: Direction | undefined; }' is not assignable to type '{ manualOrientation?: boolean | undefined; }'.
                       Types of property 'manualOrientation' are incompatible.
                         Type 'Direction | undefined' is not assignable to type 'boolean | undefined'.
                           Type '"vertical"' is not assignable to type 'boolean | undefined'.

The top 95% of this error isn't worth reading, and the `--watch` cli truncates the error, so you can't even see what the problem is.

(I deliberately didn't put this in a codefence, because that would add horizontal scrolling, and prevent the wrapping that occurs in editors' pop-up / hover helpers)

I propose the order of errors are inverted, like in the ts-error-translator: https://ts-error-translator.vercel.app/?error=CoTwDgpgBA5A3lASgeWAQWAUQFxQQFwEMAnAcwn1wGd9iBLAO1IG4pCBjfOgewatzRUqdUgzSceDADwBXBgGsG3AO4MANFEwA3CA3zIARgCsInAHysAvq0SYAygEkAWjigAKBO14ATXG84AHrgIALaEDDKEADbI9LpEXLwA-LgG3NxREOFQAD5Qct4QAGaMEN5WAJRQALxmUGkZWQysRGQU1LSMLFCWuXhQAHRDVn0IQwOVANoAulYwUHRUUEr4bEIiDIQGmVD43Lvg0DDAxOHCiXwAwrwlpFKevESlxClQABLAALIAMpiZIfE+gViqVylBuAYqBBiDoXrhEBBhAAvCCGKEw6FAhiFEoMMqsMIBOghOgo15uNxVWpQLTcOjeKp5YG4-FQEkMYmkiDkyk1Oq0+mM-LYkF4sFhCLRWJ0eKEC6vAAidGIpguWJxoNYHHwkRicT0cskiuVqsk6tFrMsGg8g2GPSgADIoNcDc8AGLcAoKuWEIXjKAANjZ3BVtoGozDrHGMAGACgoAmE6BIEtuEUoGBiNxIMR8CBYLZHC55iRoIwvCEwIbthA44n68mjjavNi-IFgmzwrrpbL5al0plskyRSywZYqXUGoPmrsSORKFAaPQmCM8g9W+5287HhAAvgJ-UB00WnP2ovOiu2BJePxz8vSDNV-1WvOOvetde+G+uo+ehUZvMizLNwqyEOsohbDsewHJAsAnGcdAXC6tyxMAp74PcUAtk8eJwu8Xy-P8gLDhqYqsBC6Kwq8CLIqikLQrC5qjgShBEiSZJ+Ly1ICgyTGamyjCchx7hcfydK8SRFril2Ur6gkRq4EqKqfnxZFXjqskygafZQEppq8KploaGMdqWGYMbxvWDaHLAzY+G2+BBP0ErdnJhrJP2jRDsKpGWgeU7HrObQLkuXRPuuvibo5uAuvgu77nyh5eTOL5nqFl7apIt7pQ+sz2muQWvneYXqVl35ML+44AQsSwrGswgQTWuz7HmsEwG48F8IhkjISImHYYQzyvB8Px-BAAJ6IZYIUQx0LUYiXJorNxBTSxbFcjyB48UKzL8eyQncpxW3iTtI57TJepafJHm6SaKmScx6muVd7kMMaylqg9-FWv04xWHUeSdecPU3CIaHBVI4xmP+0wWVZ8ONrAEUOU5oQXT22kKUl06rX+iUBeEJ7BeV3SWIBtUgfVGyQdA0GtUcQPdbwvV3OuOFzbgI2EeNxE+VJ5H0RieE0YtguMV9amEgdm2JdtuP7exh0icdgry+jbk6Xp918492rPb2WNa59OvfcZkY9ADUCM0hoOkOD86Q0M5l1vDCOHKm6aZtm0J5rALbeCWobltwlbVpkLuu27bX+NFznqy9OkEwwuPjvjR7hOTwGgeBmxNXTNkwC63hM9IbODbhw0EWNE2rBLrIzUL820UtQtq+twkUirEkm5LgmKzL3EnWrkqXQbN1G2addgnrmlj29il3cbu1qT9JkTBbU1w5HkeI+1W5oyPGPXfP2NNCn-npwwmd1WBDW51BLUF0XJcAAoqsX7ByhA-WPOXHP4aNIik0p4C0ov-EWKIW7ix7qyKW-cjqyyHiAgSHJ4HK0QarZBLlZ6Y3HovSeMDp6cH1rgk+E8DLINXubMyW9t473duCT2JBCAAjisQJYMBAglmxH7Hce5A5lgYBWKsXAawRzofQtqZchqcyrkA2uhDQHLSbqLMBK0sGsWlggwemDFEoK0egnR3dl6wPjnPd6+lk7IJnqPUhFjtYmLHNfSmt9qZ50flIzsh8NZYyTinWhEjt6Ng9hmLMOZfYwGwbY4+AiFhCJDiIugYjLKBIkbvchVjCHOOznfGmzUYJHD8VPAJqS6G7wAESwi4J-KI5TslU0ag-ApsAilZLjEAA

I don't care for the "translation" part of this, but the most important part is on top, so an ideal error could make look like:

```
Type '"vertical"' is not assignable to type 'boolean | undefined'.
  Type 'Direction | undefined' is not assignable to type 'boolean | undefined'.
    Types of property 'manualOrientation' are incompatible.
      Type '{ container?: HTMLElement | undefined; observer?: ResizeObserver | undefined; maximize?: (() => void) | undefined; minimize?: (() => void) | undefined; manualOrientation?: Direction | undefined; actualOrientation?: Direction | undefined; }' is not assignable to type '{ manualOrientation?: boolean | undefined; }'.
      ... etc
```

This aligns with how JS stacks are printed as well, where the most relevant frame is on top.

**Comment by SarcevicAntonio** [comment]
Im pretty much always hunting for the last line when a type error pops up, so this would be very useful for me. Show me what isn’t assignable to what so I can fix it.

**Comment by RyanCavanaugh** [comment]
"Most relevant" is situational because it entirely depends on why the code is wrong. For example, you might have error stack that starts with
```
Cannot assign Role<Manager> to Role<Manager[]>
```
and ends with
```
Property 'push' is missing on type 'Manager'
```

Here, the first line is much clearer and the last line is a red herring
