### ISSUE TITLE
Class method assigned to a variable has incorrect inferred type

### ISSUE THREAD

**Issue by olehmisar** [microsoft/TypeScript#50113]
# Bug Report

### 🔎 Search Terms

class method function assignment variable this bind

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/MYGwhgzhAECqEFMBO0DeAoaXoDswFsEAuaCAFyQEscBzaAH2gFccATBAM2oVc20TIA5AggAUeQiXJVaASjR9s2MgAtKEAHQSE0ALy4Ri6AF90p9MAD2Ocs0Qp9OBAHc490bIvXbA4YQBiLMBklNZ6dsgavobRAUEh1qIA5ABGlilJskA)

### 💻 Code

```ts
class User {
    name: string | undefined
    setName(name: string) {
        this.name = name
    }
}

const user = new User()
const setNameFunction = user.setName
setNameFunction('bob')
```

### 🙁 Actual behavior

- the type of `setNameFunction` is inferred to be `(name: string) => void`
- code compiled successfully
- runtime execution failed: Cannot set properties of undefined (setting 'name')

### 🙂 Expected behavior

- the type of `setNameFunction` should be inferred to be `(this: User, name: string) => void`
- code should not compile because `setNameFunction('bob')` will fail in runtime

**Comment by whzx5byb** [comment]
See https://github.com/microsoft/TypeScript/issues/7968 and https://github.com/microsoft/TypeScript/pull/6739
