### ISSUE TITLE
Incorrect type inferring

### ISSUE THREAD

**Issue by kirchet** [microsoft/TypeScript#50115]
# Bug Report

A type of variable is inferreed incorrectly inside `if` block in case when it seems that it's possible to infer it as a more precise type (see the code below).

### 🔎 Search Terms

 infer type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCJzHAjMg3sgDwC8sAuZEAVwFsAjaAbmQF8AoUSWRFdTAJjyES5KnUZC+ImvShM2HaPCRoMcAMyDiZCtPHE1UsbJatWCAPYgAzmGQRRyACoBPAA4pcrAJAv3WADTevhB8gT5uEGqBbOzgitxOEY7mvHAAsnCueKzIucgA2sEAdMFYALrkqVgMOXmFESURfBUq-DV5BcXBai2pajUxMJQgCGDAlkJqADyOwXYEkCAAJlbIANYQzuYwie7JqRmuAHwAFGAR5LMR-shLqpdJKaqHhcFlAJTkAG7mwEvZHWAOzOEWQAF4IbsII0-O8AR08hZrOYADbQlHmADmJzumHeTAA9ATbqpkMBVqAYNAoBB-gALaAoOCrKrIAA+rTgAg5fVquTYzCAA)

### 💻 Code

```ts
interface Data1 { xz1: number; }
interface Data2 { xz1: number; xz2: number; }
interface Data3 { xz1: number; xz3: number; }

const enum Type {
	Type1,
	Type2,
	Type3,
}

interface TypeToDataMap {
    [Type.Type1]: Data1;
    [Type.Type2]: Data2;
    [Type.Type3]: Data3;
}

function xz3<TType extends keyof TypeToDataMap>(type: TType, data: TypeToDataMap[TType]): void {
    if (type === Type.Type1) {
        console.log(data); // data is inferred here as Data1 | Data2 | Data3
    }
}
```

### 🙁 Actual behavior

The type of `data` is incrorrect inside `if (type === Type.Type1)` - `Data1 | Data2 | Data3`

### 🙂 Expected behavior

The type of `data` is correct inside `if (type === Type.Type1)` - `Data1`

**Comment by MartinJohns** [comment]
Your assumption that `type` refers to `data` is wrong.  
This is a legit call: `xz3<Type.Type1 | Type.Type2 | Type.Type3>(Type.Type2, { xz1: 1, xz3: 1 })`

**Comment by kirchet** [comment]
Ah, OK, got it.

In other words we can use the type of the first argument `Type.Type2 | Type.Type3` and in this case the type of the second will be something like `Data2` & `Data3`

**Comment by kirchet** [comment]
We need a restriction like `<TType extends onekeyof TypeToDataMap>` 🙂

**Comment by fatcerberus** [comment]
@kirchet 

> We need a restriction like `<TType extends onekeyof TypeToDataMap>` 🙂

https://github.com/microsoft/TypeScript/issues/27808

**Comment by kirchet** [comment]
Added one more thumbs up
