### ISSUE TITLE
Array.prototype.at not type guarded

### ISSUE THREAD

**Issue by qwelias** [microsoft/TypeScript#50119]
# Bug Report

### 🔎 Search Terms
array at type guard

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type guards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=9#code/MYewdgzgLgBAhgJwQLhgQSXAngHgN4C+AfDALwwDaAugFAA2AprCAEYBWqhNNAlgGYwAFIgQUADFQCUMPDRjyYrNmXhJxtBYvYqRAOjhRBYyTQJA)

### 💻 Code

```ts
const arr: Array<{}> = []
let obj: {}

if (arr[0]) {
    obj = arr[0]
    obj = arr.at(0) // error
}
```

### 🙁 Actual behavior
`arr.at(0)` returns `{} | undefined`

### 🙂 Expected behavior
`arr.at(0)` returns `{}` because `arr[0]` returns `{}`

**Comment by whzx5byb** [comment]
See https://github.com/microsoft/TypeScript/issues/45551
