### ISSUE TITLE
Union with a mapped string template results in an unexpected type

### ISSUE THREAD

**Issue by cboar** [microsoft/TypeScript#50120]
# Bug Report

### 🔎 Search Terms

union template string literal unexpected behavior

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about unions leading to unexpected behavior.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.6.4#code/C4TwDgpgBAglC8UDeUDaAFKBLAdlABgPQAkSAzsAE64DmAvvgLoBcUF1ONUdA3ALAAoUJCgAhBMjSZcUAOQB7HBFlQAPnOAB3eSvWzgAC0oRlLKDgCuAWwBGESt35Dw0AMIS460U8EBjRRRQAIYAjKxwiEi8goSEUAACwGQAtBAAHpC+wKmUlPKUrADWECBQACbyEGQ4+lDpWIGKUMIQfgHAwQBM4RIoBhAANgPyrLLalANlKtEC-jiBQQDMPZFyhP1DOqPjk9M+ArEJSakZEFk5eQVQVg1ktFBgeZCUwFhVbfMdNmFivTOHiRS6Uy2Xsl1YNzId04Dye9le71m7SgNm6v1WiggrBCjg+gRsy3Rkkx2IANM1tKxOuTDMYsVBFriBHiOr4fu5Iv84oCTiCLvkiiVypVqrV6o08C0WVBfGiOZINsNtvldky5oFfIT5ShZOtBsNZMqJlMmTE4gARGAAOQA4gBRABKUAAWgB5K12gCEZqOQNO5zBArYBnkFkm5nkHSCm00DyCLyw0c9YgsHSwabIwV8vggYGAEDK5M0BhAAH5pb4ACysbVQElQHFc328s6g3JBsghsNlCNfaBBGwDaDAeTXLBpWDBHA90TJ0Sp7AZrM5vMFosl8tIz4ygCsNd6daUZLWiq2ch2JpmQA)

### 💻 Code

```ts
type A = { [P in `/${string}`]: string };
type B = { [P in 'one' | 'two' | 'three']: number };
type C = A | B;

// should not allow partial! But it is accepted, why?
const bug1: C = { one: 1 };
// should not be able to mix A and B! But it is accepted, why?
const bug2: C = { one: 1, '/hello': 'world' };
```

### 🙁 Actual behavior

Observe the mapped type A that uses a string template as an index, allowing only specific strings to be used as a key. When this type is used as part of a union, the resulting type exhibits behavior I found strange.

### 🙂 Expected behavior

I would expect the type assignment for `bug1` and `bug2` to not be permitted.

**Comment by MartinJohns** [comment]
Duplicate of #20863.

**Comment by cboar** [comment]
Thanks, I wasn't aware of this fact: `Unions without discriminant properties do not perform excess property checking`.
