### ISSUE TITLE
Wrong type of class instance if the constructor returns different class instance

### ISSUE THREAD

**Issue by Tomas2D** [microsoft/TypeScript#50126]
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XQOYCcCm2AuAFAJSIC+S5SokMAwoitMAPYB2EemArsHs5sQZo0OPF0ytorbAHc4xANyNylEPmgBLdnjCtg2AFxxoAXimzotYkA)

### 💻 Code

```ts
class A {
    greet() {}
}

class C {
  constructor() {
      return new A();
  }
}

let instance: A = new C() // error
```

### 🙁 Actual behavior

Property 'greet' is missing in type 'C' but required in type 'A'.(2741)

### 🙂 Expected behavior

I think that compiler should infer that the constructor will return an instance of a different class

**Comment by MartinJohns** [comment]
Duplicate of #27594 (IMO). Currently constructors can't have a different return type, and that's the issue to solve it.

**Comment by Tomas2D** [comment]
Sorry for that, you are right. It is a duplicate. Closing for now.
