### ISSUE TITLE
React onChange handler with function union argument causes onChange to show the wrong type

### ISSUE THREAD

**Issue by wbolduc** [microsoft/TypeScript#50127]
# Bug Report
The onChange in the given example seems to change types when you pass a function that also accepts a function
the handler 

[TS playground](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220801#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgMowoxJwC+cAZlBCHAORSoYsCwAUL78AB2lKHXRUAKkkIwAPAFFwcJAA9KggCaE4g-ABs9cAD478IAEZIoAPly8AkEnAwAngH0Abij34kAfgAuOEUwAG4HLx8kIN0LK2NTA3CeewhBAGEACxRBAHNouAAKSN8Ys0soBJCASjgAXlsPCGANZOp+HgB6TtcwaTgZCD0kQXpGZnZ0GBZtIQ1VADoNBZhCXl6qEiQYMgokAEEMYDTZEls6uBIEwsKwdg9dyiCSWobL6uSNuAARYEIwChoTKyfbnIolAr7V6NZqtDpoNIyOD7FCo+pwBTKNQjLSmOKVEy6Azool6ayFHARby+TAObpwAACqwAtMBcoJoEhmYJVDBmXohJJMn84AB3YDEyyJQz4QTDQjaGCZKhEeIAhX9FB4ipwIRi4VAuBoFDEOBKkUiiAeKxQFrzUY5FyilAuNYpJxgVyealUC6k2kpNJZHL5APUIJSGQKazQooOWRCMD4GAOewbOoAIliFQzqYhdRwELgfj8cAzGfaKVSGWyeSQBcKSGhqerwbrjZWKCg+RgCyLdQHZYzxeUzncRaCAGokJ3u9s+z7qqnK-ZOtZeB94Yj4AAhdGFWOUlIIwRIgDaEOwxBgADUfQBddGqx5IQoARk3fGP27gtY0wzbfIgl+f5AWBLYdnIShDhgY5BFkbMrGsMFikXep1yra87yiVCok-ewHBPJE-wA2t8gAJmAv4ARgIEEPKJD9whWMsJ9XDfCXL97HYGB8CgUZClTWQMPsUSQVRLV80LH1aCDMj6xwVioloD0vSkgAGWg1xbcS0SkiFZJrEMFJIpBAKQFSx29KIC00uBtKrewcE6AAqOAAEk6DgFwIHwX8rXiALKiVKg5OM3VRhCuAUHMAKzVFCAjSYSAeWEWZ4EIfBcnyGRFWyDL8A0e09BcOAwrrJL9A0aK9EIRL2DQYAkGtaLpTgIsXM6SsW2ctzPO83z-OtSogrNZUyqMiqIC8qK6CGPQIHFPIkvANIRlWbAovK-IzRcPporAPou20E0sT6DAkGqzqVzElE9J9AsDIm8yC1M8zyMsz1xwenA7Ic0T7F0ySfqe7aFOKFjtmw3wIc+tSfr+kTAf+z9qGSIA)

### 🔎 Search Terms

React, onChange

### ⏯ Playground Link

[TS playground](https://www.typescriptlang.org/play?ts=4.8.0-dev.20220801#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgMowoxJwC+cAZlBCHAORSoYsCwAUL78AB2lKHXRUAKkkIwAPAFFwcJAA9KggCaE4g-ABs9cAD478IAEZIoAPly8AkEnAwAngH0Abij34kAfgAuOEUwAG4HLx8kIN0LK2NTA3CeewhBAGEACxRBAHNouAAKSN8Ys0soBJCASjgAXlsPCGANZOp+HgB6TtcwaTgZCD0kQXpGZnZ0GBZtIQ1VADoNBZhCXl6qEiQYMgokAEEMYDTZEls6uBIEwsKwdg9dyiCSWobL6uSNuAARYEIwChoTKyfbnIolAr7V6NZqtDpoNIyOD7FCo+pwBTKNQjLSmOKVEy6Azool6ayFHARby+TAObpwAACqwAtMBcoJoEhmYJVDBmXohJJMn84AB3YDEyyJQz4QTDQjaGCZKhEeIAhX9FB4ipwIRi4VAuBoFDEOBKkUiiAeKxQFrzUY5FyilAuNYpJxgVyealUC6k2kpNJZHL5APUIJSGQKazQooOWRCMD4GAOewbOoAIliFQzqYhdRwELgfj8cAzGfaKVSGWyeSQBcKSGhqerwbrjZWKCg+RgCyLdQHZYzxeUzncRaCAGokJ3u9s+z7qqnK-ZOtZeB94Yj4AAhdGFWOUlIIwRIgDaEOwxBgADUfQBddGqx5IQoARk3fGP27gtY0wzbfIgl+f5AWBLYdnIShDhgY5BFkbMrGsMFikXep1yra87yiVCok-ewHBPJE-wA2t8gAJmAv4ARgIEEPKJD9whWMsJ9XDfCXL97HYGB8CgUZClTWQMPsUSQVRLV80LH1aCDMj6xwVioloD0vSkgAGWg1xbcS0SkiFZJrEMFJIpBAKQFSx29KIC00uBtKrewcE6AAqOAAEk6DgFwIHwX8rXiALKiVKg5OM3VRhCuAUHMAKzVFCAjSYSAeWEWZ4EIfBcnyGRFWyDL8A0e09BcOAwrrJL9A0aK9EIRL2DQYAkGtaLpTgIsXM6SsW2ctzPO83z-OtSogrNZUyqMiqIC8qK6CGPQIHFPIkvANIRlWbAovK-IzRcPporAPou20E0sT6DAkGqzqVzElE9J9AsDIm8yC1M8zyMsz1xwenA7Ic0T7F0ySfqe7aFOKFjtmw3wIc+tSfr+kTAf+z9qGSIA)

### 💻 Code
```ts
import React, { useState } from 'react'


interface Test<Emp extends null | number> {
	empty_value?: Emp;
	value: number | null;
	onChange: (value: number | Emp) => void;
}

//types stolen from react's index.d.ts
type SetStateAction<S> = S | ((prevState: S) => S);
type Dispatch<A> = (value: A) => void;

const Aaaa = <E extends number | null = null>({
	value,
	// @ts-ignore-next-line This will be null unless the user passes a number in which case this is overridden anyways
	empty_value = null,
	onChange,
}: Test<E>) => (
	<input
		type="number"
		value={value ?? ""}
		onChange={(e) =>
			onChange(e.target.value === "" ? empty_value : +e.target.value)
		}
	/>
);

const B = () => {
	const [value, setValue] = useState(1);

	const handleChange: Dispatch<SetStateAction<number>> = (value) =>
		setValue(value);
	
	const handleChange2: Dispatch<number> = (value) => setValue(value)

	return (
		<>
			<Aaaa value={value} onChange={setValue} empty_value={0} />
			<Aaaa value={value} onChange={handleChange} empty_value={0} />
			{/* If you hover over the onChange in the above two components it suggests that suddenly onChange could also recieve a null value */}

			{/* If you hover over the onChange of the following components, the onChange type appears as expected */}
			<Aaaa value={value} onChange={handleChange2} empty_value={0} />
			<Aaaa value={value} onChange={(v) => setValue(v)} empty_value={0} />
		</>
	);
};
```

### 🙁 Actual behavior

onChange does not accept handers and displays as possibly being called with null

### 🙂 Expected behavior

all onChanges in the ts playground should not produce errors

**Comment by MartinJohns** [comment]
I don't see a defect here.

The type of `onChange` comes from the props passed to `Aaaa`, which is of the type `Test<E>`. `E` is typed `number | null` (extending it), which makes `onChange` be `(value: number | null) => void`. The handler you pass along, `setValue` and `handleChange` are typed `(value number) => void` - this is not compatible.

According to the type definition of `Aaaa` the handler **can** be called with `null`, but the handler you try to pass along **can not** handle `null`.

**Comment by RyanCavanaugh** [comment]
This follows from the inference algorithm and is intended behavior. Zero candidates are collected for `Aaaa`'s `E` parameter because the `number` type gets "peeled off" during the inference step of relating `(arg: number | Emp) => void` to `(arg: number) => (doesn't matter)`, so TS falls back to the constraint, which is a union.
