### ISSUE TITLE
Have to suffix directory "." with "/" to import correctly.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#5012]
E.g.

```ts
// file index.ts
export function foo() { }

// file test.ts
// Have to change '.' to './' for TypeScript to recognise. 
import * as Foo from '.';
```

Is this the desired behaviour?

**Comment by vilic** [comment]
Oh it's actually working...

**Comment by mhegazy** [comment]
//cc: @vladima

**Comment by vladima** [comment]
Current module resolution logic for node follows [Modules all together](https://nodejs.org/api/modules.html#modules_all_together): module will be attempted to be loaded as file\directory if its name starts with './', '../' or '/', otherwise it will be loaded from 'node_modules' folder.

**Comment by vilic** [comment]
Hi @vladima @mhegazy currently I was working on something related to module path resolving recently, and found that the abstract logic in the documentation of Node.js is highly inaccurate and does not match its own implementation in many situations. So I hope you may reconsider this for a wider adoption.
