### ISSUE TITLE
tsserver: a closed document should be re-read from disk

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5015]
Due to the async nature of file events and the async communication channel to the tsserver a document close request should reread the content from disk. Consider the following steps:

- VSCode sends a document open for A.ts and therefore 'owns' the content
- VSCode sends changes to the content of A.ts to the tsserver.
- The file is saved on disk from another program.
- The file change event is processed by the tsserver and ignored because the file is open
- The user closes the file in VSCode. We send a close event to the tsserver
- VSCode receives the file event from disk. We ignore the event since the file is closed.

Regarding open/close semantic the protocol can only be speced as follows (don't know if this is the case already):

- the content of a open document is owned by the editor that send the open event. 
- the content of a closed document is on disk. There can't be any guarantee that an editor synced all changes done to an document either inside or outside of the editor to the tsserver before it closes the document.

Therefore the tsserver must reread the content of a closed document from disk. 

In addition we should change the protocol in a way that an open request always sends the content as well. Again due to the fact that file events are async it can happend that VSCode and tsserver start on different content of the same file.

**Comment by dbaeumer** [comment]
@zhengbli: any news on the suggestion to send the content on open?

**Comment by zhengbli** [comment]
@dbaeumer working on it. I'll update the issue at #5530 later.
