### ISSUE TITLE
Language Service API tries to resolve wrong/non-existing files

### ISSUE THREAD

**Issue by scanline** [microsoft/TypeScript#50160]
I'm using the Language Service API and discovered some strange things I can't find a reason for.
Say I'm using the following compiler options:
```
const compilerOptions = {
			target: ts.ScriptTarget.ES3,
			lib: ["dom", "es5"]  
};
```
As can be seen from the above I'm adding the **dom** and **es5** libraries.
If I now go further and implement a simple `getScriptSnapshot()` function for the languageServiceHost, which just traces the requested files - e.g.
```
function getScriptSnapshot(fileName) {
		console.log("getScriptSnapshot:", fileName);
		return ts.ScriptSnapshot.fromString("");
	}
```
I get the following output:
**getScriptSnapshot: dom.ts
getScriptSnapshot: es5.ts**

which stunnes me! Since dom & es5 are declaration files for TypeScript's own high level libraries, shouldn't it try to get **lib.dom.d.ts** and **lib.es5.d.ts** respectively?

Furthermore, if I set up some dummy function for the languageServiceHost's `fileExists()` method - e.g.
```
	fileExists: function fileExists(path) {
		console.log("fileExists", path);
		return false;
	}
```

I receive the following:
**fileExists /node_modules/@typescript/lib-undefined/package.json
fileExists /node_modules/@typescript/lib-undefined.ts
fileExists /node_modules/@typescript/lib-undefined.tsx
fileExists /node_modules/@typescript/lib-undefined.d.ts
fileExists /node_modules/@typescript/lib-undefined/index.ts
fileExists /node_modules/@typescript/lib-undefined/index.tsx
fileExists /node_modules/@typescript/lib-undefined/index.d.ts
fileExists /node_modules/@types/typescript__lib-undefined/package.json
fileExists /node_modules/@types/typescript__lib-undefined.d.ts
fileExists /node_modules/@types/typescript__lib-undefined/index.d.ts
fileExists /node_modules/@typescript/lib-undefined.js
fileExists /node_modules/@typescript/lib-undefined.jsx
fileExists /node_modules/@typescript/lib-undefined/index.js
fileExists /node_modules/@typescript/lib-undefined/index.jsx**

Well, what is the `undefined` it tries to check it's existence?

Here's a complete working example, showcasing the issue:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="">
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://cdn.jsdelivr.net/npm/typescript@4.7.4/lib/typescript.min.js"></script>
	<script type="text/javascript">
		const compilerOptions = {
			target: ts.ScriptTarget.ES3,
			lib: ["dom", "es5"]
		};

		const languageServiceHost = {
			getScriptFileNames: function getScriptFileNames() {
				return ["index.ts"];
			},
			getScriptVersion: function getScriptVersion(path) {
				return "0";
			},
			getScriptSnapshot: function getScriptSnapshot(fileName) {
				console.log("getScriptSnapshot:", fileName);
				return ts.ScriptSnapshot.fromString("");
			},
			getCurrentDirectory: function getCurrentDirectory() {
				return "/";
			},
			getCompilationSettings: function getCompilationSettings() {
				return compilerOptions;
			},
			getDefaultLibFileName: function getDefaultLibFileName(options) {
				return "lib.d.ts";
			},
			fileExists: function fileExists(path) {
				console.log("fileExists", path);
				return false;
			},
			readFile: function readFile(path, encoding) {
				return "";
			},
			readDirectory: function readDirectory() {
				return [];
			}
		}

		const registry = ts.createDocumentRegistry()
		const service = ts.createLanguageService(languageServiceHost, registry, ts.LanguageServiceMode.Semantic);
		const program = service.getProgram();
	</script>
</head>
<body>
</body>
</html>
```

**Comment by fatcerberus** [comment]
The compiler/language service API is kind of gnarly.

The thing is that, as far as I've been able to tell, it's expecting fully qualified paths(!) for `lib` there.  It's not like tsconfig where you just have to provide the names of the libs and TS figures the rest out.  That's because normally `tsconfig.json` is preprocessed through `TS.parseJsonConfigFileContent`, like this:
https://github.com/fatcerberus/ts-sphere/blob/master/cell/ts-tool.js#L145-L146

You'll need to implement `getDefaultLibFileName` properly too:
https://github.com/fatcerberus/ts-sphere/blob/master/cell/ts-tool.js#L71-L87

**Comment by RyanCavanaugh** [comment]
This ☝. You cannot take a raw JSON object and pass it as a compiler options and get the same behavior as you would if that JSON object were the contents of a tsconfig file. Many other things will break if you do this, e.g. relative paths in a tsconfig are relative to the containing file, `extends` arguments are supposed to be handled during this step, and others.

**Comment by scanline** [comment]
Thanks for sharing your insights @fatcerberus!
I figured, if I change the `lib` compiler option to:
`lib: ["lib.es2020.full.d.ts"]`

the **undefined** inside the `fileExists()` function is gone.
**fileExists /node_modules/@typescript/lib-es2020/full/package.json
fileExists /node_modules/@typescript/lib-es2020/package.json
fileExists /node_modules/@typescript/lib-es2020/full.ts
fileExists /node_modules/@typescript/lib-es2020/full.tsx
fileExists /node_modules/@typescript/lib-es2020/full.d.ts
fileExists /node_modules/@typescript/lib-es2020/full/index.ts
fileExists /node_modules/@typescript/lib-es2020/full/index.tsx
fileExists /node_modules/@typescript/lib-es2020/full/index.d.ts
fileExists /node_modules/@types/typescript__lib-es2020/full/package.json
fileExists /node_modules/@types/typescript__lib-es2020/package.json
fileExists /node_modules/@types/typescript__lib-es2020/full.d.ts
fileExists /node_modules/@types/typescript__lib-es2020/full/index.d.ts
fileExists /node_modules/@typescript/lib-es2020/full.js
fileExists /node_modules/@typescript/lib-es2020/full.jsx
fileExists /node_modules/@typescript/lib-es2020/full/index.js
fileExists /node_modules/@typescript/lib-es2020/full/index.jsx**

That brings up new problems though. In TypeSscript version <4.5 the declaration files were stored inside the `lib`
folder of TypeScript's own package - and are still there with v4.7.4!
But from the above output and this blog post from Microsoft itself:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#supporting-lib-from-node_modules
it now looks for it's own declaration files inside `node_modules/@typescript/lib-`*NAME*

Apparently there is no node package called @typescript so how should it ever find those declaration
files if those are still stored inside [https://github.com/microsoft/TypeScript/tree/main/lib](url) ?
