### ISSUE TITLE
"Find all references" does not work on memoized React components

### ISSUE THREAD

**Issue by mweiss9676** [microsoft/TypeScript#50164]
Issue Type: <b>Bug</b>

In some React memoized components, the component is declared separately from the memoization and then exported while being wrapped in the memo() call. Because of this, when you right click on the component (or the memoized reference) and select "Find all references" VSCode cannot find all of them. The only way to currently find references is to perform a global search for a unique part of the path. This is especially frustrating because module imports can be aliased so searching for the component by name does not work in all cases.

Example file that find all references does not work on any part of: 

```
import '../../../sass/reports.scss'

import React, { memo, useRef, useState } from 'react'

const CaseStatus = ({ form, description, firmId }) => {
     return (
        <></>
    )
}
const WrappedCaseStatusForm = Form.create({ name: 'case-status-form' })(CaseStatus)

export default memo(WrappedCaseStatusForm)
```

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800HS with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.42GB (10.64GB free)|
|Process Argv|--crash-reporter-id d80d49f6-5ace-4a90-a5f5-e8902ff0b205|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.6.0
vscode-custom-css|be5|6.0.2
prettier-vscode|esb|9.5.0
nodejs-repl|los|0.5.15
vscode-docker|ms-|1.22.0
csharp|ms-|1.25.0
remote-containers|ms-|0.238.2
vetur|oct|0.35.0
vscode-jest|Ort|4.6.0
autolaunch|phi|2.1.2
LiveServer|rit|5.7.5
slim|sia|0.1.2
highlight-matching-tag|vin|0.10.1

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by RyanCavanaugh** [comment]
We have no way to know which functions in the world should be referentially-transparent and which shouldn't.

This should work fine if you capture the `memo` call in a variable and `export default` that.

**Comment by windstranger** [comment]
well, you can download intellij and search for references for the "default" word, it shows all the references correctly, even dynamic. No idea why vscode not doing the same...
