### ISSUE TITLE
Empty object in ternary operator produces invalid type

### ISSUE THREAD

**Issue by olehmisar** [microsoft/TypeScript#50171]
# Bug Report

### 🔎 Search Terms
empty object, {}, inferred type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/MYewdgzgLgBAHjAvDKAnArgUxgfhgcgEkYBDAW1JmlQEswBzfGALhgG8BfGAem5QE8ADthAAzGAAM4EmDQitOQA)

### 💻 Code

```ts
const x = true ? 'I am a string' : {} // type of `x` is: {}
```

### 🙁 Actual behavior

Type of `x` is inferred as `{}`

### 🙂 Expected behavior

Type of `x` should be inferred as `"I am a string" | {}`. 

For example, if we try this code:
```ts
const x = true ? 'I am a string' : 5
```
...the type of `x` is inferred as `"I am a string" | 5`

**Comment by MartinJohns** [comment]
Strings are valid `{}`, so the type gets simplified. This is working as intended.

**Comment by jcalz** [comment]
See https://www.typescriptlang.org/docs/handbook/type-inference.html#best-common-type

**Comment by olehmisar** [comment]
> Strings are valid `{}`, so the type gets simplified. This is working as intended.

why isn't this code simplified?

```ts
type X = string | {} // `X` is string | {}
```

**Comment by RyanCavanaugh** [comment]
Subtype reduction isn't required to happen, but is allowed to happen at any point. There's not a bug here.

**Comment by Jack-Works** [comment]
but do you think this type reduction _is_ correct / meaningful to developers?

**Comment by poksme** [comment]
I encountered this issue when composing a dynamic object. For anyone seeing this and trying to find a workaround, couple things to note :
- Subtype reduction happens when assigned to a variable, so you might get away with inlining this code instead of storing it in a variable.
```typescript
(true ? 'I am a string' : {}) // Type is 'I am a string' | {}
const myVar = true ? 'I am a string' : {} // Type is {}
```
- In my case, both return values of the ternary were enumerable, and cloning it with a spread prevented the subtype reduction, even when assigned to a variable.
```typescript
const computeData = () => ({ foo: "bar"})

const subtypeReduced = true ? computeData() : {}; // Type is {}
const preservedType = {...(true ? computeData() : {}) } // Type is { foo?: string | undefined; }
```
