### ISSUE TITLE
"Declare missing function" codefix offered on arguments

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#50188]
# Bug Report

### 🔎 Search Terms

declare missing function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the moon

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIAoAPALnlWQFsAjEGASjKlQE8BuAWAChECoBnYIgFCo9NkA)

### 💻 Code

```ts
declare function f(x: number): any;
f(asdfasdfa);
```

### 🙁 Actual behavior

We offer to declare `asdfasdfa` as a function

<img width="401" alt="image" src="https://user-images.githubusercontent.com/3277153/182920480-a0fc68f7-26fc-4bc7-a961-c5e42b44f7dd.png">

### 🙂 Expected behavior

No codefix—the fix is intended to be given only when the unresolved identifier is the _expression_ of the CallExpression, not an argument passed to it.

Noticed by @danay1999 while working on ts-fix

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
