### ISSUE TITLE
Function not callable when using a generic type parameter and union types

### ISSUE THREAD

**Issue by lo1tuma** [microsoft/TypeScript#50182]
# Bug Report

### 🔎 Search Terms

* This expression is not callable.
* TS2349
* generic
* union type

### 🕗 Version & Regression Information

Problem happens in all recent versions of typescript.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/JYOwLgpgTgZghgYwgAgKIDcLlQW2GSKAHgFk4AHc0AcwD5kBvAKGVeQHsQiMswA5ODhQQAHpBAATAM7IA1hACe7GMjKUatABQRM4AUIBcaXf0EQAlEfTtgEgNxMAvkyahC8JMgAKcBQBt2OAkAQUYWNigIIM4-BWQYdnYjEABXHAAjaAc2ZEjokFjkdLgoIykwKBoHZ1dwaA8UH39AiQAhMJy8iRi4hKTkVIys8NYunqK4AC8jdMS-KJBqlzAFchRcfEJQgF5jXg2CaCImgKDg2gcVtbQ8Q6h23Z5sW8Jj31O2i5c3esQUEnYEhS81CzE6UW6BTiVwgRgA5HA4dkIhDxpwjActgBtOGcOEAXSWtXcf1UgOBEHaYJR+UKMPh6SRI1yqKhHBAGJe0FaOLxhKcLhgKRACDAwE4yG6AGUwCkYDBNDhAUYAUCQcgAD5ktWUyzIay2DpsYAqRWAgB0MOQ2xtyARcPMRpySok5s4mjhfQddmQAHpfcgAO7sKCyKTMxzICB+KQoanOi3uz2Jb1+gPB0PhnLOBOupNe8w+-2S9gQKQgQCYBGAgyHZE4gA)

### 💻 Code

```ts
interface EventEmitter<Mapping> {
    on<EventName extends keyof Mapping>(eventName: EventName): void;
}

interface PayloadA {
    readonly foo: number;
    readonly bar: string;
}

interface PayloadB {
    readonly foo: number;
    readonly baz: boolean;
}

type EmitterA = EventEmitter<PayloadA>;
type EmitterB = EventEmitter<PayloadB>;

interface ModuleA {
    readonly type: 'a';
    readonly on: EmitterA['on'];
}

interface ModuleB {
    readonly type: 'b';
    readonly on: EmitterB['on'];
}

function doStuff(mod: ModuleA | ModuleB): void {
    if (mod.type === 'a') {
      mod.on('foo'); // works
    } else {
      mod.on('foo'); // works
    }
    mod.on('foo'); // doesn’t work
}
```

### 🙁 Actual behavior

The following error is reported when calling `mod.on('foo');` without narrowing its exact type:

```
This expression is not callable.
  Each member of the union type '(<EventName extends keyof PayloadA>(eventName: EventName) => void) | (<EventName extends keyof PayloadB>(eventName: EventName) => void)' has signatures, but none of those signatures are compatible with each other.
```

### 🙂 Expected behavior

Since `mod.on('foo')` works in all possible branches when narrowing down the type I would expect it to also work without branching and narrowing.

**Comment by jcalz** [comment]
Duplicate of #30581, recommended solution is at #47109

**Comment by lo1tuma** [comment]
@jcalz thanks for pointing that out. I have troubles understanding the recommended solution and applying it for my use-case. I’ve posted the [question](https://stackoverflow.com/questions/73246386/how-to-use-correlated-union-types-for-a-strictly-typed-event-emitter) on stackoverflow.
