### ISSUE TITLE
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

### ISSUE THREAD

**Issue by Ramya-bs10** [microsoft/TypeScript#50181]
# Bug Report

### 🕗 Version & Regression Information

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.7.4

Please only submit bug reports when using the officially supported version.

**Comment by MartinJohns** [comment]
This is not a TypeScript issue. Most likely you should just update your eslint packages.
