### ISSUE TITLE
CFA doesn't work when using generics to associate two function arguments

### ISSUE THREAD

**Issue by k8w** [microsoft/TypeScript#50205]
# Bug Report

### 🔎 Search Terms
CFA generic function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about CFA and type inference

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEoHsCukAKcpwC2AzsgN4BQyyA5APSbHQ0Bc5yj0AkgCZvFgooAObIAvgBoqtOgAco6HpgRhW7eYuVhe-QSPFTq9ADbABassllxhEAMrAAXhDYhMhAEbQJyBJihQEOCu7l5QBhRiFBQwmCAqwOggyCBwAG7AwnCQACroADw5yBAAHpAgPKQA1hAAnugwaFi4+ETEAHwAFP7GbDk+1gQkbBjYEHhDxADaOQC6AJTk0nR0yAByAPJFAOobqADSyAASAKKoJ8gAhNfSwI3dUMbIALyvMpxQNIuU1NQIScR0MYIAA6YzoYSdQZtEEfXjzaRRKIUFbIXYHOxok4AGWxFFSGSyuXQnXoHxoPkscL4tAAjAAmADMNHE8wA3CjVgABMDEAC0pVkEBUAoC6Cg+PSmWyEDypIYTE+lOQJVVqrYNAZzNZbKAA)

### 💻 Code

```ts
interface RouteParams {
  '/user': { userId: string },
  '/product': { productId: string },
  '/list': { pageSize: number, current: number },
}

function navigateTo<T extends keyof RouteParams>(url: T, params: RouteParams[T]) {
  // NOT WORK HERE !!!
  if (url === '/user') {
    console.log(params.userId)
  }
}

// WORKS WELL
navigateTo('/user', { userId: '123' });
// @ts-expect-error
navigateTo('/user', { xxxxx: '123' });
```

### 🙁 Actual behavior
> Property 'userId' does not exist on type '{ userId: string; } | { productId: string; } | { pageSize: number; current: number; }'.
  Property 'userId' does not exist on type '{ productId: string; }'.(2339)

CFA works well outside the function call, but not works inside the function.

### 🙂 Expected behavior
Compile successfully.

**Comment by MartinJohns** [comment]
The error is correct. You wrongly assume that `T` will always only be one specific key, but this is valid code:

```typescript
navigateTo<'/user' | '/product'>('/user', { productId: '..' });
```

You want #27808.

**Comment by k8w** [comment]
@MartinJohns 
> The error is correct. You wrongly assume that T will always only be one specific key, but this is valid code:
> ```ts
> navigateTo<'/user' | '/product'>('/user', { productId: '..' });
> ```

Actually, `T` here is not `'/user' | '/product'`, because it is infered as `'/user'`:

![image](https://user-images.githubusercontent.com/1681689/183237186-5c33b47f-8c19-4917-86ab-26b27b3493da.png)

**Comment by MartinJohns** [comment]
> Actually, `T` here is not `'/user' | '/product'`, because it is infered as `'/user'`:

It's allowed to explicitly specify the type parameter, as I did. In that case the type parameter is not inferred anymore.

But even if you let it infer the type you can have the same issue:

```typescript
const path = '/user' as '/user' | '/product'
navigateTo(path, { productId: '..' });
```

**Comment by k8w** [comment]
> Within the implementation of the function the compiler can't know if the type represents only one key, or multiple. So it errs on the safe side.

`T` maybe multiple keys indeed, but when it checked by `url === '/user'`, shouldn't CFA narrowed the T to single key?

For example, this works well:
```ts
interface RouteParams {
  '/user': { userId: string },
  '/product': { productId: string },
  '/list': { pageSize: number, current: number },
}

let key!: keyof RouteParams;
if (key === '/user') {
  //@ts-expect-error
  if (key === '/product') {

  }
}
```

**So why it doesn't works inside the function ?**

```ts
function navigateTo<T extends keyof RouteParams>(url: T, params: RouteParams[T]) {
  if (url === '/user') {
    //@ts-expect-error
    if (url === '/product') {

    }
  }
}
```

**Comment by MartinJohns** [comment]
> `T` maybe multiple keys indeed, but when it checked by `url === '/user'`, shouldn't CFA narrowed the T to single key?

No. You're only narrowing the type of the specific variable.

`T` can be `"/user" | "/product"`, and `url` is `"/user"`, but `params` is `RouteParams["/product"]`. This is perfectly legit to call, as I demonstrated twice.

**Comment by k8w** [comment]
Actually `url` is not narrowed at all, see this:

```ts
// 【THIS WORKS !】
function test(v: 'a' | 'b') {
  if (v === 'a') {
    //@ts-expect-error
    if (v === 'b') {

    }
  }
}

// 【WHY THIS DOESN'T WORKS ?】
function test2<T extends 'a' | 'b'>(v: T) {
  if (v === 'a') {
    //@ts-expect-error
    if (v === 'b') {

    }
  }
}
```

**Comment by whzx5byb** [comment]
@k8w I'm not sure why `v` is still marked as `T extends 'a' | 'b'` but it is narrowed in fact. See the examples in https://github.com/microsoft/TypeScript/pull/43183.

**Comment by fatcerberus** [comment]
Union types strike again!  This recent comment of mine https://github.com/microsoft/TypeScript/issues/50145#issuecomment-1203337333 comes to mind, specifically the last part:

> I’ve found with TS that when generics fail to typecheck in cases where it looks like they should, it’s almost always because you’ve failed to account for the possibility of instantiating them with union types. Having two things typed as `T` sadly isn’t enough to guarantee they always hold compatible values… and the compiler will let you know about it
