### ISSUE TITLE
Typo in Type page of Typescript Cheat Sheets!

### ISSUE THREAD

**Issue by petervillaroman** [microsoft/TypeScript#50207]
# Typo Report

The typo can be found [here](https://www.typescriptlang.org/static/TypeScript%20Types-4cbf7b9d45dc0ec8d18c6c7a0c516114.png). 

The **second** bullet point for the heading "Type vs Interface" has a typo.

> Interfaces can be extended by declaring it **`mutliple`** times.

**Comment by adityasgit-hub** [comment]
Hi Peter and Ryan! It seems like a really small and easy issue which I can and would love to fix it as it will be my first contribution (i.e., pull request) too...

**Comment by petervillaroman** [comment]
Hey adityas, I have no authority on here, I just reported the typo. It looks like Ryan already assigned somebody for this.

**Comment by adityasgit-hub** [comment]
no worries peter and thanks for the concern, will be looking forward to help!
