### ISSUE TITLE
Duplicate emit when using amd-dependency and es6 ambient import

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#5021]
Hi,

I think that the `///<amd-dependency />` functionality exhibits odd behavior when combined with an ES6 import.

For example, this TypeScript code:

```typescript
/// <amd-dependency name="jquery" path="/jquery/jquery.min.js" />
import 'jquery';

$('#myDiv').html('Hello');
```

emits as this JS when using AMD module mode:

```javascript
define(["require", "exports", "/jquery/jquery.min.js", 'jquery'], function (require, exports, jquery) {
    $('#myDiv').html('Hello');
});
```

In the emitted JS, the string 'jquery' is included in the requirements for the module (causing an HTTP 404 error at runtime).  My expectation would be that 'jquery' here would be considered the same as the 'jquery' inside the amd-dependency comment, so it would be de-duplicated and that only "/jquery/jquery.min.js" would be passed along to the emitted JS.

I can simply remove the ES6-style import and the emit works as expected.

Am I crazy on this?

I know this will probably be moot once #2338 hits.

Possibly related: #4004.

**Comment by mhegazy** [comment]
this looks right to me. you have two imports one to `jquery` and one to `/jquert/jquery.min.js`. i would say remove the `amd-dependency` and just make the import:

```ts
import "/jquery/jquery.min.js";
```

**Comment by nycdotnet** [comment]
Interesting.

I wasn't aware of that minimalist import syntax, and it does work in this case.  However, I think maybe jQuery was a bad example because it's actually implemented as a UMD module and `$` and `jQuery` are in-scope in all files merely by including the `jquery.d.ts` file in the TypeScript compilation context.

Even if you don't think it's a bug that they are both emitted, do you believe that "jquery" in both the `amd-dependency` comment and the `import` statement in my example refer tot he same ambient external module declaration (as described in 12.2 of the spec)?

Is there a way to alias external modules in AMD compilation mode using the ES6 syntax only? For example what if I wanted an emit like this (`$` is aliased as `jq`, but somehow tied to the "jquery" ambient external module declaration  so the types work)?

```javascript
define(["require", "exports", "/jquery/jquery.min.js"], function (require, exports, jq) {
    jq('#myDiv').html('Hello');
});
```

If not, will this be supported in the future with #2338?  I know people were talking about syntax like `import * as foo: IFoo from "foo";` in #2709, but I think this would almost call for something like `import {$} as jq: typeof "jquery" from "/jquery/jquery.min.js";`, no?

Thanks so much, Mohamed.

**Comment by nycdotnet** [comment]
Thanks for the reply, Mohamed.  I wrote a response before, but I deleted it because I think this one is better.

I wasn't aware of the minimalist import syntax that you suggested, and it does work in this case.  However, I think maybe jQuery was a bad example because it's actually implemented as a UMD module so `$` and `jQuery` are in-scope in all files merely by including the `jquery.d.ts` file in the TypeScript compilation context.

Perhaps I'm just hitting up against #2338 again.  This new example may better-illustrate what I was expecting.  Let's say I want to *rename* `$` to `jq` inside my module, but still fetch jQuery from `/jquery/jquery.min.js`.  I wrote the following TypeScript code:

```typescript
///<amd-dependency name="jq" path="/jquery/jquery.min.js" />

import * as jq from 'jquery';

jq('#myDiv').html('Hello');

```

I was expecting this emit:
```
define(["require", "exports", "/jquery/jquery.min.js"], function (require, exports, jq) {
    jq('#myDiv').html('Hello');
});
```

But I got this emit:
```
define(["require", "exports", "/jquery/jquery.min.js", 'jquery'], function (require, exports, jq, jq) {
    jq('#myDiv').html('Hello');
});
```

Notice - two `jq` parameters, and both "/jquery/jquery.min.js" and 'jquery' are included.  I can't see a benefit to doing this emit versus the one I was expecting.

Am I just stuck until the mapping functionality is added to tsconfig.json as part of AMD support in #2338?

Thank you so much, as always!!!

**Comment by mhegazy** [comment]
What you describe was never the intended behavior of the 'amd-dependencey' tags, these were mainly Kent for importing non-code resources, and should not be used with imports.

**Comment by nycdotnet** [comment]
OK.  Thanks for your responses.  It's been very helpful.

As far as aliasing dependencies as a `.js` script name (instead of as an external module ambient declaration name) when using ES6-style imports and AMD compilation mode - is that impossible still without a post-processor until #2338 is complete for AMD?

Thanks.

**Comment by nycdotnet** [comment]
For posterity's sake, I've figured out a good technique to permit the TypeScript type system to be happy *and* to have an arbitrary path be emitted in the `define()` call when using ES6 import syntax that works today.  This technique assumes that the types for the module are available globally.  It involves using a supplementary ambient external module definition.  This technique eliminates the need to define paths in a call to `require.config` when using RequireJS in simple projects.

If I want to require jQuery as a variable `jq` using the ES6 module syntax and have this resolve to `/scripts/jquery/jquery.js` at runtime for loading by RequireJS, I can do the following.

  * Create a new definitions file called `amdMappings.d.ts`, or something similar.
  * This file will duplicate the ambient external module declaration for jquery - however it will do so with a different ambient module name:
```typescript
declare module "/scripts/jquery/jquery" {
    var $: JQueryStatic;
    export = $;
}
```
  * Now, jQuery can be imported into another module as so:
```typescript
import * as jq from '/scripts/jquery/jquery';
jq('#myDiv').html('hello');
```
The AMD emit from this code is:

```javascript
define(["require", "exports", '/scripts/jquery/jquery'], function (require, exports, jq) {
    jq('#myDiv').html('hello');
});
``
