### ISSUE TITLE
tsc  generates two duplicate js files

### ISSUE THREAD

**Issue by lsdbitrue** [microsoft/TypeScript#50232]
# Bug Report

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

https://github.com/lsdbitrue/tsc-bug-1

Run `npx tsc --build`

### 🙁 Actual behavior

![Screen Shot 2022-08-09 at 17 57 41](https://user-images.githubusercontent.com/88539015/183621291-44072af3-0b12-45b7-9534-b989f5ca9a45.png)

### 🙂 Expected behavior

![image](https://user-images.githubusercontent.com/88539015/183621389-2a128d55-2cf4-4fbe-839f-888814a95042.png)

**Comment by MartinJohns** [comment]
You're building **three** projects here: `tsconfig.json`, `packages/bob/tsconfig.json` and `packages/alice/tsconfig.json`. The first one does not specify a dist folder, so  the compiled files are placed next to the source files. That's where the `src/index.js` comes from.

When you add `"include": []` to your root tsconfig file you prevent this behavior.

> Run `npx tsc --build`

FYI, the correct package to use is `typescript`, not `tsc`.

**Comment by lsdbitrue** [comment]
@MartinJohns Thanks for reaching out! it works!

**Comment by MartinJohns** [comment]
This is briefly mentioned in the documentation: https://www.typescriptlang.org/docs/handbook/project-references.html#overall-structure

> Another good practice is to have a “solution” `tsconfig.json` file that simply has [references](https://www.typescriptlang.org/tsconfig#references) to all of your leaf-node projects and sets [files](https://www.typescriptlang.org/tsconfig#files) to an empty array (otherwise the solution file will cause double compilation of files).
