### ISSUE TITLE
Conditional type does not work with objects properly

### ISSUE THREAD

**Issue by ns-vpanfilov** [microsoft/TypeScript#50234]
# Bug Report

I am trying to infer function return based on value of object property
```
declare function getID2<T extends {a:boolean}>(fancy: T): T extends {a:true} ? string : number;
```

However, that returns inconsistent results depending on how parameter is passed

```js
declare function getID2<T extends {a:boolean}>(fancy: T): T extends {a:true} ? string : number;
// Then depending on how much the type-system knows about
// the boolean, you will get different return types:
let stringReturnValue2 = getID2({a:true}); // string, OK
let numberReturnValue2 = getID2({a:false}); // number, OK
let stringOrNumber2 = getID2({a:Math.random() < 0.5}); // number, should be string | number 
let p2 = {a:true};
let stringReturnValue2C = getID2(p2) // number, should be string
```

If, however, I do not use an object and T is a boolean instead of {a:boolean}, everything works fine:
```js
declare function getID<T extends boolean>(fancy: T): T extends true ? string : number;
// Then depending on how much the type-system knows about
// the boolean, you will get different return types:
let stringReturnValue = getID(true); // string, OK
let numberReturnValue = getID(false); // number, OK
let stringOrNumber = getID(Math.random() < 0.5); // string | number, OK
let p = true;
let stringReturnValueC = getID(p) // string, OK
```

### 🔎 Search Terms

conditional

### 🕗 Version & Regression Information

never worked

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.2.3#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMQMBJAEQB4AVeEADwxFWAGd4AjHHCEKVAPgAUiPmACeALnhUAlFJr1GzNhhjIEAfngtVWVAXhTUyALbsQMANwBYAFAB6e9IAWTeKAAOTYHoN54zjgA7vAmyGDO8BiuUWJeALQsYjogJvAA1qjBbFCcyBh2jlExnNy8qAA08GI4yPBBWBAQhMTuWIiIFkwY8HAYyDD4GHEgLBJ2PD06ML4ASsQDqABqUBDq8AC8LaRkgqrqMpbwRdO+VQDyANITrcZmFvP9gytrCFtEO8KrLCCHx053cwwC7XWyTbS6fTnGAAOVMQM223IggAslBogA6GB8YA4EyCGTwCjwAAMGIArH8TpCDAAfeCAiwgm49DyI-YgGxg1qnfSPRYvdQAYURH2RHkJ1Jm+mZtjsdlAkFgCBQ6Gw-jFZAATNRaAxvGwAN5QCSlHh8AC+QhE6Ek0jk0j1SlY8GNEg5FvgWl5BiM8IsXKKVFc+E83l88H8gRCYQixQQwwSSRSaUy2XguVqBQcTmiCDN5SqNTqDSa2zaHS6qB6fUWsS8YxZEOlBH5z1W6i1ouI5C1gjdHqpTh9svBjJgbeWHZAXfePe1-ZNIggPwtQ4Z-uB8CuTZ90Lh9xgs6RC7daMx2OYeIJRNJFLXRyK46qLECyAgwA4CB98Hp4-gTYeMeA5qCAFpcuCPqToKM4inOOx9kBkoApuL5vh+X7Nr4QA)

### 🙁 Actual behavior

```js
let stringOrNumber2 = getID2({a:Math.random() < 0.5}); // number, should be string | number 
let stringReturnValue2C = getID2(p2) // number, should be string
```

### 🙂 Expected behavior

```js
let stringOrNumber2 = getID2({a:Math.random() < 0.5}); // number, should be string | number 
let stringReturnValue2C = getID2(p2) // number, should be string
```

**Comment by RyanCavanaugh** [comment]
This is the correct behavior; the conditional type is doing exactly what you told it to do.

What you wanted to write was this
```ts
declare function getID2<T extends {a:boolean}>(fancy: T): T extends {a:true} ? string : T extends { a: false } ? number : string | number;
```

**Comment by whzx5byb** [comment]
> If, however, I do not use an object and T is a boolean instead of {a:boolean}, everything works fine.

When you pass a union type into a **naked** type parameter, it will become distributive. See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types. Also note that the type `boolean` is treated as `true | false`.
