### ISSUE TITLE
Assigning type interface to an instance of a class implementing interface with added properties

### ISSUE THREAD

**Issue by OGreeni** [microsoft/TypeScript#50230]
# Bug Report

### 🔎 Search Terms
Assigning interface type to a class instance implementing interface

### 🕗 Version & Regression Information
Using version 4.7.4. First noticed 8/8/22

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about implementing an interface
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8CS5rycgbwChlkBbdABSgHsAHARgC5kBnMKUAcwG4iBfIkQQAbOK1Zp0AYTETkwMnREQyEcJIzZIsRCmKkK1egCZkAXmQByE1b6kENEOygBXBGBpQAFHVcAjEWAEcipaRhYXbgBKQkFBIhUwBWcwOBAkFi0cXXxLEAgAdylZcVZvKwYraJ5kAHo65BAaZDB0OhRoWihhJ1YaFQA6ERoub1B2dKRBo3CTGvrGq1nTK2QAExoISWbkiAAPYHZkJ1b2lCtsnTwIK0HkABFgdeR0GldyCHTrFcYrAH4iEA)

### 💻 Code

```ts
interface MyInterface {
  myProp1: string;
}

class MyClass implements MyInterface {
  myProp2 = '2';
  constructor(public myProp1: string) {}
}

let instance: MyInterface = new MyClass('1'); // no type error
console.log(instance.myProp2); // 'myProp2' does not exist on type 'MyInterface'. Did you mean 'myProp1'?
```

### 🙁 Actual behavior
If a class implements `interface` and has added properties/methods (in addition to those required by the implementation), attempting to assign type `interface` to `instance` of that class would not result in an error. Instead, the error only comes up when trying to access an added property/method on `instance`.

### 🙂 Expected behavior
If a class implements `interface` and has added properties/methods (in addition to those required), attempting to assign type `interface` to `instance` of that class would result in a type error.

**Comment by OGreeni** [comment]
Is this the intended behavior here?

**Comment by fatcerberus** [comment]
This is how interfaces work in pretty much all languages that have them.  You've said that `instance` is typed as `MyInterface`, so there's no requirement that any object assigned to it has a `.myProp2`.  Therefore the compiler doesn't let you access it.

Also, if the assignment was a type error, that would be too restrictive since then you wouldn't be able to implement multiple interfaces.
