### ISSUE TITLE
Assignment of nested field accessed from union type indexed field expects union type instead of intersection type

### ISSUE THREAD

**Issue by mgmolisani** [microsoft/TypeScript#50249]
# Bug Report

### 🔎 Search Terms

assignment union intersection nested get set

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about field assignment versus access types specifically in the context of shared nested fields.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&allowUnreachableCode=true&allowUnusedLabels=true&noUnusedLocals=true&noUnusedParameters=true&noFallthroughCasesInSwitch=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&ts=4.7.4#code/PQKgBAQg9gLgFmeBTMAPMBDAdgEzATzADMBLJAGxwGcwq4MAnFZRfAByQC4AobmdlADEoUADwAVAHxgAvGADe3MMrBYkVGEhycw47gF9eIYNwDGULBuIjZCtDvmr1m7XYw6AjGH3eANAQcnDS1AgCMdACZvaMNzSxgwAGskQjkAWQx4ADoGbBwoAFsACgBKMGkABiyAVjAAfjAAA1RGsB1G-EazCytQxi85IhEAbWT8AF0wYGAwcwYmUwSAWjAAVywSC38Wfg4wAtXelAsUAHkAJUQ4Y+QGbviwPoYowZGx8ay1YLxp2ah5pCLMArdabLDba6sPYHI5gE5gC5XG7XO5DKCjFKTOSOL4uQLuMAefzhQkxKYzOYLZZgEhYTQMKiAmBgiHMAT7Q4JUIoDBUKgkADmWAwoXIzCgj1gCF26loJAO5Bg2CQUEO5Hw3DRGImn2cWlsjgJXh8v1plKZwLWGy2dlQOiwqwK3IY0Toqsoqlgjx5fMFwtFKBIRCSKVkMjkHVaoVWCXgJBo8cw5HIUAA7lpeEA)

### 💻 Code

```ts
/* Both the x and y fields share the type:

type Foo<T> = {
    nested: T
}

*/
const foo = { x: { nested: { a: 1 } }, y: { nested: { b: 2 } } }
const key = Math.random() > 0.5 ? `x` : `y`
const bar1 = foo[key] // correct - union, the type must be one OR the other
const bar2 = foo[key].nested // correct - union, the type must be one OR the other
foo[key] = { nested: { a: 1, b: 1 } } // correct - intersection, the type must be assignable to both types simultaneously
foo[key].nested = { a: 1 } // incorrect - union, { x: number } should not be assignable if key === `y` but this is allowed
```

### 🙁 Actual behavior

When accessing a field via any valid key that is unknown, the compiler correctly asserts that the type returned is the union of the possible types at the possible keys.

When assigning a field via any valid key that is unknown, the compiler correctly asserts that the type to be set must be the intersection of all the possible types. However, if you access a shared nested field and attempt to assign it, the expected assignment is a union type. This seems incorrect as the assignment again should be the intersection of the possible types that the shared nested property could be across all valid keys used to access the parent property.

### 🙂 Expected behavior

Discussed above, but again, regardless of if the field or its parent were accessed via an unknown but valid key, the expected assignment type should be an intersection, even if the intersection is `never`, as that would be the only valid way to ensure any property assigned has been given a valid value.

**Comment by RyanCavanaugh** [comment]
It's clearer what's going on here if you separate out the intermediate expression:
```ts
const m = foo[key];
m.nested = { a: 1 };
```
The type of `m` is `{ nested: { a: number} | { b: number } }`. To manifest any other behavior than what you see today, `m` would have to have some other type -- but *what* type? There isn't type that has the same behavior as what's needed to replicate what's going on in `e[k] = v` (an expression form which is special-cased to improve soundness over the default covariant behavior)

**Comment by mgmolisani** [comment]
@RyanCavanaugh 

So just to make sure I'm understanding (as this was also my assumption) - because the property is accessed first, we get the type as it was accessed and lose the ability to treat it like the special-case expression type that changes the type based on the presence of the assignment operator.

A follow up: is there any simple/obvious way to simulate that expression special case type (with or without runtime implication) to at least allow for a better programming interface to avoid gotchas on the end user side of the API?

**Comment by RyanCavanaugh** [comment]
Correct

Functions types will unify a bit better; demo speaks louder than words
```ts
const foo = { x: { nested: { a: 1 }, setNested(_a: {a: number}) { } }, y: { nested: { b: 2 }, setNested(_b: { b: number }) {} } }
// ...
const m = foo[key];
m.setNested({ a: 1 }) // Missing 'b'
```

**Comment by KotlinIsland** [comment]
Is this the same issue in #50386?
```ts
class A<in out T> {
    t!: T
}

declare let a: A<number> | A<string>
a.t = "a string?"
```
