### ISSUE TITLE
Is it possible to infer the data type of a variable when using `as`

### ISSUE THREAD

**Issue by Bistard** [microsoft/TypeScript#50255]
# Suggestion

## 🔍 Search Terms

possible   
infer type 
when using as

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Consider the following type:
```ts
/** Make all the properties mutable (remove readonly). */
export type Mutable<Immutable> = {
    -readonly [P in keyof Immutable]: Immutable[P]
}
```
In v4.7.4, I have code:
```ts
interface MyObject {
    readonly value: any;
}

const obj: MyObject = { value: 'hello' };
(obj as Mutable<MyObject>).value = 5;
``` 
Where I have to write the generic type `T` explicitly. In the perspective of design goals, is it possible to achieve this feature works like this?
```ts
const obj: MyObject = { value: 'hello' };
(obj as Mutable).value = 5;
```

## 📃 Motivating Example

Make code line shorter.

## 💻 Use Cases

Make code line shorter.

**Comment by RyanCavanaugh** [comment]
`(obj as Mutable<typeof obj>).value = 5;`
