### ISSUE TITLE
Difference in parameter inference between arrow functions and classic functions

### ISSUE THREAD

**Issue by knutkj** [microsoft/TypeScript#50258]
In the [example code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFs8sMcYAeAFXhAA8MRVgBneACgDovYBzZgLnhRUATwCU8ALwA+IaOlsAUPBr0YUTGUGduMPoIAKsKARAMYzKtIkz4AJXBlg5ZhhhZUPADTw0Aa1QcAHdUaS9lVXBkUhhBSnCxbS4OXgF4I3VTc0tKaylZBwxkGFRKEQAHECsAbkVFIlQSMjY2cptZNgBveHL4AF8xH1bBVGQCACMQGHaesVqGppgWtvz2bt6BnxR0bDx2cpGxyen4brgikp7q-rnFIA) below the arrow function has correct type inference while the function example is unable to infer the parameter type and falls back to `any`.

```ts
declare function monitor<T extends (...args: any) => any>(
  extractor: (...args: Parameters<T>) => Record<string, unknown>,
  executor: T,
): (...args: Parameters<T>) => ReturnType<T>;

monitor((p) => ({ p }), (p: number) => p);
monitor((p) => ({ p }), function (p: number) { return p; });
```

![image](https://user-images.githubusercontent.com/691727/183909659-032658b2-760a-420b-b8dc-d96f4ac393a0.png)

![image](https://user-images.githubusercontent.com/691727/183909783-dca5e90a-0fef-460e-8edc-cb8cbc110ac6.png)

**Comment by knutkj** [comment]
Note that if we specify type of this the function variant is also able to infer the type:

![image](https://user-images.githubusercontent.com/691727/183910516-c6444947-77cc-4477-b321-a85480bfdea1.png)

**Comment by RyanCavanaugh** [comment]
Duplicate #47599
