### ISSUE TITLE
Detect esm only packages and generate ems style import

### ISSUE THREAD

**Issue by sdrsdr** [microsoft/TypeScript#50253]
# Suggestion

There are some pure esm packages like node-fetch@3 that I am  having troubles using. When such module is imported in typescript the import is transpiled to regular require that fails at runtime. The node-fetch module has a `type:"module"` in it's package.json that clearly states that the package is esm module. This indication can be used and the import should be unmangled to allow smooth pure esm packages usage. As this seems like a breaking change it can be enabled via tsconfig.json option

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
