### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#50263]
# Bug Report

_Originally posted by @clhiker in https://github.com/swc-project/swc/issues/5433_

### 🔎 Search Terms

- generators
- JSON.stringify
- enumerable

### 🕗 Version & Regression Information

- This is a crash on runtime

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1#code/DYUwLgBAbgjBC8EDeAoC6IEMBcyIEsATXOAXwBo0MAjXAbQF0VSBuFAMwFcA7AYzHwB7bgCpoAJgAUsAJTIq6MACcAnvIwRSEXpjC8AFhGkw5qDaWYpewgM6QoAZgQQAUgGUA8gDkAdHaX43ADm+OwqxuQSMixAA)

### 💻 Code

```ts
let v1 = {
    a: { id: 1 },
    b: []
};
function* v2(v1) {
    try {
    } catch (v1) {
    }
}
const v3 = JSON.stringify(v1, v2);
```

### 🙁 Actual behavior

It crashes on runtime.

### 🙂 Expected behavior

run without crash. and v3 === `{}`

**Comment by Canvas856** [comment]
Could i do this task?

**Comment by rbuckton** [comment]
This doesn't seem to be an issue with the helper. Yes, making the methods non-enumerable will make this error go away, but that doesn't change that the code in question is using `JSON.stringify` incorrectly. There are plenty of other ways to trigger the same issue that have nothing to do with our downlevel emit for generators.

This same bug was [closed in swc](https://github.com/swc-project/swc/issues/5433#issuecomment-1210463752) for this same reason, I don't see a compelling reason why we should further complicate the generator transform to address this.
