### ISSUE TITLE
Self-reference / import of the current package doesn't work in an mjs file, but does in a ts file in src

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#50270]
# Bug Report

node16 nodenext esm mjs self reference referential module package name

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### 💻 Code

Repro here: https://github.com/jakebailey/self-reference-mjs

In short, I have a `mjs` file with:

```ts
// @ts-check

import * as index from "self-reference-mjs";

console.log(index.foo);
```

And a `package.json` like:

```json
  "name": "self-reference-mjs",
  "version": "1.0.0",
  "type": "module",
  "exports": {
    ".": "./dist/index.js"
  },
```

This code executes and does the right thing, but TS gives an error on the import. Writing the same code in a TS file works, but the emitted code is identical to the hand-written code.

### 🙁 Actual behavior

I can import the current package by name in an mjs file.

### 🙂 Expected behavior

I can only import the current package in TS, not in an mjs file.

I sort of expected this to work post #46762 or something, but the behavior is inconsistent.

**Comment by jakebailey** [comment]
@andrewbranch is this just "not a bug", then, per #50390?

I guess I'm surprised, as I had assumed we'd recognize that mjs can do this, but...

**Comment by andrewbranch** [comment]
This is totally separate from #50390—that repro was not showing what it looked like it was showing. It was just misconfigured.

**Comment by sheetalkamat** [comment]
This seems configuration error.. `tsc --explainFiles`  shows that it does not include `b.mjs` so you arent seeing errors.. The inferred project has which is why i think you have errors?
```
          "module": "ESNext",
          "moduleResolution": "Node",
```

**Comment by jakebailey** [comment]
Yes, I am opening this up in VS Code, so I suppose this is the default project. I guess I would have expected that `"type": "module"` would be enough information, but maybe that isn't the case because there's nothing that indicates that it's a node project?

**Comment by andrewbranch** [comment]
Then the question is, why isn’t `b.mjs` picking up `tsconfig.json` and opening a ConfiguredProject?

**Comment by andrewbranch** [comment]
Oh wait, you don’t have `allowJs` turned on.

I also don’t know if `.[cm][tj]s` files are in the default include glob? That may be something to look at changing under `nodenext` if they’re not.

**Comment by jakebailey** [comment]
> Oh wait, you don't have allowJs turned on.

Adding `allowJs` does work, yeah (so likely no glob changes needed), but I have it turned off because I don't want this file to appear in my `dist` output; in my case it's effectively a build script (like a gulpfile).

**Comment by jakebailey** [comment]
Specifically, once I enable the option and open the file, about 10 duplicate errors that say "cannot write file because it would overwrite input file" appear in my tsconfig.json.

So, maybe it's not trying to write to dist, and I just don't know how to configure my project. 😅

**Comment by andrewbranch** [comment]
In that case, I would call this a duplicate of https://github.com/microsoft/TypeScript/issues/49270 (I could update the title to include `.mjs` variants as well)

**Comment by jakebailey** [comment]
Sounds good to me.
