### ISSUE TITLE
Fix regression for optional JSDoc types which throws `TS2463` in `typescript@next`

### ISSUE THREAD

**Issue by voxpelli** [microsoft/TypeScript#50286]
# Bug Report

### 🔎 Search Terms

optional jsdoc regression

### 🕗 Version & Regression Information

This started occurring in nightly after #50094 was merged to fix #49869 and still happens (see these [cron job type checks](https://github.com/voxpelli/pony-cause/actions/workflows/ts-internal.yml) in `pony-cause` which retests against nightly three times a week).

This **_does not happen_** in 4.8 beta

- This changed between versions 4.8-beta and nightly

### ⏯ Playground Link

Since the Playground is for TS code, not JS code, here's a link to a piece of code: https://github.com/voxpelli/pony-cause/blob/4009048a41d772cb29673f1c45cc55e9717e523f/lib/error-with-cause.js#L5-L9

And more in this thread: https://github.com/voxpelli/pony-cause/issues/45

### 💻 Code

```js
   /** 
    * @param {{ cause?: string }} [options] 
    */ 
   function foo ({ cause } = {}) { 
```

### 🙁 Actual behavior

Explicitly specifying the `options` as  optional (`[options] `)  causes this error as it is already implicitly marked as optional by having been set a default value (`{ cause } = {}`):

```
error TS2463: A binding pattern parameter cannot be optional in an implementation signature.
```

### 🙂 Expected behavior

One of:

1. Preferably that TypeScript keep accepting arguments that's been explicitly marked as optional, even if that is redundant
2. At least change the error message to something that makes more sense in a JSDoc context than "`A binding pattern parameter cannot be optional in an implementation signature.`"

See more in this thread: https://github.com/voxpelli/pony-cause/issues/45 and in https://github.com/microsoft/TypeScript/pull/50094#issuecomment-1201502045, where @sandersn said that he is in favor the current new behavior.

**Comment by voxpelli** [comment]
Seems like this is actually affecting TS 4.8.2

**Comment by mohd-akram** [comment]
Any update on this?

**Comment by turadg** [comment]
Here is a [TS playground link](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220921&filetype=js#code/PQKhAIAEBcFMFsAOAbAhncBtAKgXgK4B2AJrAGYCWhsxAuuCMAFADGaAzu+AKIBOvAe14B1CtAAWAYVT52scLAAecElz6De4AN5Nw4UCF16IkRKl6p429tF5UA5gF9w8WJ1T3YRhlDMWrWlrgLDJyAPwAXODY4I7OmAKI0BQChOy03oxGLKk2vPgs0ELgABSu7p4ANNrBofLOuNqOAJTa3uDs+IiwvGVu7B6wzQDcTO0GUNAAnt3Wtg7OWXp6EhTsAHSElvKN6kKiEtKysJvbo8vgFGSlIcetOhd6EzAz8lrYi8yP4Ksbt3LgRr-WDnZaOcZgSavOZ2QhOBhfZa-dblAaeQEufqDUHg8FAA) showing it's still a problem in 4.9.0-dev.20220921 (Nightly). Also 4.8.2, and not 4.7.4.
