### ISSUE TITLE
Intellisense find wrong thirdparty path with yarn's nohoist in monorepo

### ISSUE THREAD

**Issue by l1shu** [microsoft/TypeScript#50284]
# Bug Report

### 🔎 Search Terms
nohoist
intellisense
monorepo

### 🕗 Version & Regression Information
**monorepo file structure**
<img width="316" alt="image" src="https://user-images.githubusercontent.com/48285873/184304594-842b79d6-cfb9-46be-a0d7-2616575be8be.png">

**/packages/aaa/package.json**
```json
{
  "sideEffects": false,
  "name": "aaa",
  "version": "0.0.1",
  "devDependencies": {
    "pinia": "^2.0.18"
  }
}
```

**/packages/bbb/package.json**
```json
{
  "sideEffects": false,
  "name": "bbb",
  "version": "0.0.1",
  "devDependencies": {
    "pinia": "^2.0.18"
  }
}
```

**/package.json**
```json
{
  "name": "monorepo",
  "version": "1.0.0",
  "private": true,
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/pinia",
      "**/pinia/**"
    ]
  }
}

```

don't hoist pinia and all of its dependencies.

**/packages/aaa/index.ts**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/48285873/184305412-9d0f013e-efe9-409a-9240-91eea6a92ece.png">

Intellisense find pinia from **packages/bbb/node_moduels/pinia** rather than **packages/aaa/node_modules/pinia**.

I think the behavior of intellisense path finding should be same as Node runtime

**/packages/bbb/index.ts**
<img width="752" alt="image" src="https://user-images.githubusercontent.com/48285873/184306682-a7d46119-a134-4ac0-9f5c-a15f00724c23.png">

### ⏯ Playground Link
[monorepo.zip](https://github.com/microsoft/TypeScript/files/9314515/monorepo.zip)

**Comment by RyanCavanaugh** [comment]
I don't see any tsconfig files here. In this scenario, you'd need separate tsconfigs to create separate "projects", since resolution of nonrelative names is cached per-project.

**Comment by l1shu** [comment]
> 

thanks fro replying.

But in general, for monorepo, there will only be one tsconfig file in the root directory. There doesn't seem to be a good solution
