### ISSUE TITLE
Generic function occurs parse error

### ISSUE THREAD

**Issue by cdpark0530** [microsoft/TypeScript#50281]
# Bug Report

### 🔎 Search Terms
generic function parse error

### 🕗 Version & Regression Information
4.7.4, since 4.0
4.8.0-beta as well

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generic function parse error

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=1&ts=4.8.0-beta#code/CYUwxgNghgTiAEBzCB7ARlC8DeBYAUPPAC4CeADggKIB2xMAliAM4A8AKgHzwC88VAD0gBXUKzyEi8ANoAFeAxrwA1iFIoAZvHYBdAFwzZAGm1ydOgNwEiAX2mr1W3SeE1QGxSGCdplgtZIKBFlYYgZMAHk0ACtwYg5uPgkpQwUlB01tHQB+A3YzeBABYhA3ZngAQRgYKFJWRQ0QGH5OAKJs-ngAH35fNvgDEJgwzA4zTitJG0mbf3wi8hRh+DAUGmZieCgAW1LgXngOI04ACnRYsGJB0PCIKIv4rhN3KGEIYnu4vIBKPN5uZLwODEYQwJQnT6XAB0pXoTGYZxicW+W3KtDhLAS336ULgwGEYBAJ36KROUDAYBM9jUJgAbpgdCieACSVJgaClOSwJMUikbEZWUQXm8PkjLgLJERvjNJgQFktNqt1psdnsAEIHI6nADuDGIAAtrsNbpDHpxniANK93qafn9mTgAuywfAIWLiDC6IwWCddQaUVA0V74VicXiCUTBa6uVSHHSGUyWZLec7ORSebzbBLM0LLdbRQ9s1JpQRpnN5cslRstrs3BVNewDlAaKQdXrDfAhiM7u6EharSLbdpftp-o7JKnXabPRiEX79QGg7PQ8ncV4I8Tk6SYzI4-B6RBGWPAZnJ1yM5n+VHhTb3UWpTLywJFssNK5Lgw1jW9gAxd8JREHiNbtTT7eAbwLL5hz+QFJzdB4Z29BFzmRVF+GDTEuGxVdw0JTcc2jClYxpfcE2PKMz3TKMry3KQINNe94BLfAy3wOVnwVeA3xoD8v1VNw-x4iotV9dtgJNXsnnAvNB3dO1R1gkAQRdeC4kQ+FRP9ND0SQlcUjXfE8KjMkiN3EiDyPB0TxTJSOS2KjaKza8ZNvQt+mY1j2JfTZuN4zla2AQSwDVDgmxbNsDXEyJJPNaSB1cqD2BHRtFOU8Fp1hJDNIXbSMLYLCw3XIzHMIykzNIeND0TccCMo7lqMYlJ6LvdzH3wIA

### 💻 Code

```ts
// works: first parameter named `object`
export const amend = <T,>(object: PartialObject<T>, defaultObject: T): T => {
  return (Object.entries(object) as Entries<T>)
    .reduce(
      (acc, [key, val]) => {
        return acc;
      },
      defaultObject,
    );
};

// doesn't work: first parameter named `with`
export const amendA = <T,>(with: PartialObject<T>, defaultObject: T): T => {
  return (Object.entries(with) as Entries<T>)
    .reduce(
      (acc, [key, val]) => {
        return acc;
      },
      defaultObject,
    );
};

declare global {
  type Entries<T> = Exclude<{
    [P in keyof T]: [P, T[P]];
  }[keyof T], undefined>[];

  type PartialObject<T> = {
    [P in keyof T]?: T[P] extends Array<infer E>
      ? E | E[]
      : Partial<T[P]>;
  };
}
```

### 🙁 Actual behavior
TS compiler fails to parse correct generic function. Somehow if I name the first parameter `object`, it succeeds to parse.

### 🙂 Expected behavior
TS compiler succeeds to parse correct generic function. Even if it's not correct, its success or failure shouldn't depend on the names of parameters.

**Comment by MartinJohns** [comment]
`with` is a reserved JavaScript keyword.

**Comment by cdpark0530** [comment]
@MartinJohns 
You're right, very thank you. I'm closing this issue.
