### ISSUE TITLE
Conditional type based on optional property

### ISSUE THREAD

**Issue by ns-vpanfilov** [microsoft/TypeScript#50287]
# Suggestion

Currently, writing a conditional type that checks for an optional property and returns appropriate type based on not very straight forward and unintuitive. Listed below are my initial attempts to do so. They have the following issues:
- Must use "as any" in function returns, as typescript gives cannot correctly infer type in function
- The two examples do not handle "undefined" value the same way - f1 with false returns results that are not expected, and f2 with undefined returns unexpected results

```js
const f1 = <T extends { isNum?: boolean; data: string[] }>(
	props: T
): T extends { isNum: true } ? number : T extends { isNum: true } ? string : null => {
	if (props.isNum === true) return '' as any // ERROR: does not work without "as any"
	else if (props.isNum === false) return 0 as any // ERROR: does not work without "as any"
	else return null as any // ERROR: does not work without "as any"
}

const f2 = <T extends boolean>(props: {
	isNum?: T
	data: string[]
}): T extends true ? number : T extends false ? string : null => {
	if (props.isNum === true) return '' as any // ERROR: does not work without "as any"
	else if (props.isNum === false) return 0 as any // ERROR: does not work without "as any"
	else return null as any // ERROR: does not work without "as any"
}

const undef_1 = f1({ data: [] })
const true_1 = f1({ data: [], isNum: true })
const false_1 = f1({ data: [], isNum: false }) // ERROR: returns `null`; should be `string`

const undef_2 = f2({ data: [] }) // ERROR: returns `string | number`: should be `null`
const true_2 = f2({ data: [], isNum: true })
const false_2 = f2({ data: [], isNum: false })
```

## 🔍 Search Terms

conditional

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [  ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x ] This wouldn't change the runtime behavior of existing JavaScript code
* [ x ] This could be implemented without emitting different JS based on the types of the expressions
* [ x ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

- Allow typescript to correctly infer return type within the function, so we do not have to use "as any"
- Make behavior of both examples consistent

This is a breaking change; to avoid this, we could introduce another keyword instead of "extends"

**Comment by whzx5byb** [comment]
> - Allow typescript to correctly infer return type within the function, so we do not have to use "as any"

See https://github.com/microsoft/TypeScript/issues/33912.

> - Make behavior of both examples consistent

The inconsistent here is caused by distribution behavior. You can write `[T] extends [true] ? number : [T] extends [false] ? string : null` to avoid that.

**Comment by ns-vpanfilov** [comment]
> > * Allow typescript to correctly infer return type within the function, so we do not have to use "as any"
> 
> See #33912.
> 
> > * Make behavior of both examples consistent
> 
> The inconsistent here is caused by distribution behavior. You can write `[T] extends [true] ? number : [T] extends [false] ? string : null` to avoid that.

` [T] extends [true] ? number : [T] extends [false] ? string : null` is an easy fix (it probably should be documented under conditional types section)

Any ideas on how to make pattern f1 work without complex hacks?

```
const f1 = <T extends { isNum?: boolean; data: string[] }>(props: T) : T extends { isNum: true } 
    ? number : T extends { isNum: true } ? string : null
```

**Comment by whzx5byb** [comment]
> it probably should be documented under conditional types section)

It has been. See the last paragraph in https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types.

> Any ideas on how to make pattern f1 work without complex hacks?

You wrote `{T extends { isNum: true }}` twice in `f1`. 
Also note that in `f2` the condition branches were written reversed by mistake.

**Comment by ns-vpanfilov** [comment]
thanks
