### ISSUE TITLE
Variable in "extends" clause ignored by services

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#5028]
In the following code:
```
var base = class {};
class C extends base {}
```
services does not recognize that the `base` identifier in the second line refers to the variable declared in the first. Rename, find occurrences, etc do not work on it.

The same problem also occurs with JSX spread attributes in .tsx code:
```
var props = {};
var div = <div {...props}/>;
```

**Comment by DanielRosenwasser** [comment]
I think the latter is a symptom of #4688. @RyanCavanaugh can you confirm?

**Comment by RyanCavanaugh** [comment]
That's correct.
