### ISSUE TITLE
Allow (fake) parameter initializer in overloaded functions

### ISSUE THREAD

**Issue by AgainPsychoX** [microsoft/TypeScript#50297]
# Suggestion

## 🔍 Search Terms

`A parameter initializer is only allowed in a function or constructor implementation.` `ts(2371)`
Parameter initializer in overloaded functions.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow (fake) parameter initializer in overloaded functions to improve readability and easier suggest how code works to users without additional overload and comment.

I call them _fake_ parameter initializers, because they won't initialize the values themself, the main function specification/declaration should must do it.

## 📃 Motivating Example

Expected to work: [Playground Link](https://www.typescriptlang.org/play?#code/FAegVGwARlDiBTAdggTgQwC4IM5Q0gOYJQBmqA9gLZQAMUmFUhAlgG7JQ6MAOUSAVyoAjNFADuLTAAsu2PhVJQAjADposAAI90GGtwp8NIYAgAePCqkxkBSAMaYWFJPnREEACgM8AXPyFRVABKf0QUDEZUAB5BETQAPgBuUAgNeGQ0LFw3DzJKfUxdG0Y5QwkpWVYOV24EHnUYKG1ddELiqHSWvTKjJu62uXrOmBNzS2tbBycXXOJvIut-OKCAGl7lwLR1ur8A+NQoAF4VUIyIrCtYrdRk0wsrG1I7R2ckWAJ57mKAeVQAZV4mwO60MMyQ6AANoDDAB+YFrIZ7FZiE7KM7hLJRa4HBJQADewAAkJCEDZvpMTmC3lCYXwjgyoHYACYIUgsFDMqCwuhQfwUzB-OkpIn2FzcXrHKDUly03jHRkstkchBcnkCoXy-wyiHQ3gigCeLAQkK5ApF4mkLFJUAWHWivWCnSJRKNJrNixsAGoTrsUgBfYBAA)

Current approach required: [Playground Link](https://www.typescriptlang.org/play?#code/FAegVGwARlDiBTAdggTgQwC4IM5Q0gOYJQBmqA9gLZQAMUmFUhAlgG7JQ6MAOUSAVyoAjNFADuLTAAsu2PhVJQAjADposAAI90GGtwp8NIYAgAePCqkxkBSAMaYWFJPnREEACgM8AXPyFRVABKf0QUDEZUAB5BETQAPgBuUAgNeGQ0LFw3DwkpWQATBFJ0AQAbG24EBSU1dO1ddH1MXRsGnT05QyhjUwsrG1I7R2dXAmJvVut-OKCAGm6-APiQsMzIq1jAxJTwSBgMiOy8CZJyajk2hiYffJlmdk5qnnVDxq7ua46mlp6fz7yXowEzmSzWWwOJwuXKTL4zFYLJazHaoRYvFGrUJHLJRbarZL9cFDEbQpCwM5TNoAeVQAGVeJikYYyehygzDAB+JlodHyHmoKAAXhU2PCuK2c0SUAA3sAAJDlBBVaY2EUssZsjl8IW6qB2YqkFgoQpQTl0KD+eGYWnalLy+wubhLYVQDUuLW8YV6g0lY0IU3m622r3+d1IT2Ge0ATxYCHKput9vE0hYSqgVIh0SWwV68vlsfjidVUAA1CKXikAL7AIA)

## 💻 Use Cases

The feature would allow to hint users what they an expect when skipping parameter of overloaded function. This is the case for other functions, but isn't yet for overloaded ones. Currently one would have to add overload and comment to do the same.

**Comment by AgainPsychoX** [comment]
BTW Could https://github.com/microsoft/TypeScript/issues/25710 be revisited by any means? Would be even nicer to have below working...

```tsx

/**
 * Generates range from 0 to given stop number with step of 1.
 * @param stop 
 */
export function* range(stop: number): Generator<number>;
/**
 * Generates range from start to stop with given step.
 * @param start 
 * @param stop 
 * @param step 
 */
export function* range(start: number, stop: number, step: number = 1): Generator<number>;
export function* range(startOrStop: number, optionalStop?: number, step: number = 1): Generator<number> {
	let start = optionalStop === undefined ? 0 : startOrStop;
	const stop = optionalStop === undefined ? startOrStop : optionalStop;
	yield start;
	while (start < stop) 
		yield start += step;
}
```
[Playground Link](https://www.typescriptlang.org/play?#code/FAegVGwARlDiBTAdggTgQwC4IM5Q0gOYJQBmqA9gLZQAMUmFUhAlgG7JQ6MAOUSAVyoAjNFADuLTAAsu2PhVJQAjADposAAI90GGtwp8NIYAgAePCqkxkBSAMaYWFJLALEAFAZ4AufkNFUAEo-RBQMRlQAHkERNAA+AG5QCA14ZDQsXHx0IhJyajldG0Y5QwkpWVYOJDkEHnUYKG1ddH1MYqg0lr0yoyaetrr+sBNzS2tbBycXN1zPbmK-WMCAGj7lgLR17nrNuNQoAF4VEPTwrCsYrdQk0wsrG1I7R2dXHLyvDusAeVQAZV4+zWUEMMyQ6AANoDDAB+YHbYYIw4nZRnMKZSLXA7xKAAb2AAEhIQgbItJicwW8oTC+Ed6VA7AATBCkFgoJlQWF0KB+cmYP605KE+wubh9Y6gnjgmm8Y4M5ms9kITnc-mCuV+KkuWWGYUATxYCEhnP5wvE0hYJKgX06UT6QS6hMJhuNpu+NgA1CddjxkgBfYBAA)

**Comment by RyanCavanaugh** [comment]
I appreciate the use case, but the proposed solution would be way too surprising. If you wrote
```ts
function foo(s: string, x = 0): void;
function foo(n: number, x = 1): void;
function foo(sn: string | number, x?: number) { }
```
the expectation that `x` would be `1` during the call `foo(42)` would be extremely reasonable, but not met.

JS Doc would be the better place to put that information.
