### ISSUE TITLE
Sparse array type reduced to (T | undefined)[] but they behave differently.

### ISSUE THREAD

**Issue by miguel-leon** [microsoft/TypeScript#50296]
# Bug Report

Easier to explain with a commented example:

```ts
function f(x = [, 1, , 3]) {
    const values = Object.values(x); // should narrow type to number[]
    return new Set(values);
}

const set1 = f(); // should be type Set<number>
// set1 -> Set(2) {1, 3}


const set2 = f([undefined, 1, undefined, 3]); // should not work as the behavior is different
// set2 -> Set(3) {undefined, 1, 3}
```

The problem persists with the (relatively recent) compiler option `exactOptionalPropertyTypes` turned on. Which description suggests solving the problem.

### 🔎 Search Terms

sparse array type

### 🕗 Version & Regression Information

Latest version as of date.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&exactOptionalPropertyTypes=true#code/GYVwdgxgLglg9mABMAFAD0QXkQbQDSICMBBAzALoCUiA3gLABQiziECAzlIgG4CGANiACm7LIgDyAIwBWQ6ADo+gkekoBuRAHpNidgAs4IfgBNEYXgCcLcAO6IoATwAOQ+3DMgAtpKEWc5RhZECyEoEAskMCE7AGVQlCVhdnVGAF9GRjYwTl1QwjFUdS0dfUMTRB97Z1c4qAAeMC8fCwA+Rm1cqHyAWhbEWpQAJmoaYkRSdIYMhiyc9lDBgpQccGMhYBgo4wIx1fXNoW3xqg0O0qNTMDguGzgLAGtEXlEoPVcfPV5ueAtEGFFjDBgMBfEIwFB2iUFohev14qRKAACmh7DZbHZkSZAA)

### 💻 Code

Same as in report description

### 🙁 Actual behavior

Unrestricted, no error.

### 🙂 Expected behavior

Restricted, compilation error.

**Comment by RyanCavanaugh** [comment]
TS doesn't attempt to model sparse arrays

**Comment by miguel-leon** [comment]
Oh.. sorry. Thanks for your response.

Is this something tentative for the future (should this be a feature request)?
Or should I just close the issue?

It would be a bummer though because currently there's no way to declare the function signature to accept arrays or sparse arrays without introducing allowance for `undefined` values.

It also feels like something that `exactOptionalPropertyTypes` should be concerned with.

The only way I can seem to solve this for now is with `@ts-ignore`s.

**Comment by RyanCavanaugh** [comment]
There's basically zero chance we'd do the work necessary to model sparse arrays. They are quite rare in practice, and having to traffic around sparse vs non-sparse information through the entire type system would be very cumbersome.
