### ISSUE TITLE
An unnecessary space is inserted in ${...} by the auto formatter

### ISSUE THREAD

**Issue by d180cf** [Microsoft/TypeScript#5030]
This is what I get after Ctrl+K+D in VS:

```ts
throw Error(`${JSON.stringify(this.value) } cannot be found in ${JSON.stringify(y) }`);
```

As you see, a space was inserted after `JSON.stringify(...)`. The bug doesn't appear if a plain variable is used: `${x}`.

**Comment by SaschaNaz** [comment]
Does this accept PR?

**Comment by vladima** [comment]
Sure! PR will definitely be appreciated

**Comment by mhegazy** [comment]
thanks @SaschaNaz !
