### ISSUE TITLE
This type inference of static property getter

### ISSUE THREAD

**Issue by avin-kavish** [microsoft/TypeScript#50301]
# Bug Report

It's possible to infer the `this` type contextually on a static method so inherited classes get their own type as `this` when calling an inherited static method. But in static property getters it's not possible to specify generic parameters, so it's not possible to get the `this` type of a derived class in a parent getter. 

In the example below, `Bar.default` returns an instance of Bar but it's type is inferred as Foo.

```ts
type Constructor<T> = { new (): T }

class Foo {
  static factory<T extends Foo>(this: Constructor<T>): T {
    return new this()
  }

  static get default() { // Not possible to specify type parameters
    return new this()
  }
}

class Bar extends Foo {}

const x = Bar.factory() // x is type Bar
const y = Bar.default // y is type Foo

// however, both are instances of Bar
console.log(x instanceof Bar) // true
console.log(y instanceof Bar) // true
```

Ideally, I think both getter and method should work without any extra type parameters needing to be specified. Static `this` type should be inferred contextually.

```ts
class Foo {
  static factory(): this {  // TS2526: A 'this' type is available only in a non-static member of a class or interface.
    return new this()
  }

  static get default(): this {
    return new this()
  }
}
```

Edit: I'm seeing some comments in other threads about `new this()` not being allowed because the caller's ctor signature isn't known in the parent class. That's understandable. This is a demonstration of the problem of type inference, this is not an actual use case. My actual use cases don't invoke any unknown constructors. So please don't dismiss this because you think the use case isn't viable.

### 🔎 Search Terms

- static property getter
- static property this

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/issues/5863.

**Comment by RyanCavanaugh** [comment]
The solution for the specified problem here *is* #5863.

> My actual use cases don't invoke any unknown constructors. So please don't dismiss this because you think the use case isn't viable.

We can't just do things and ignore their side effects...

**Comment by avin-kavish** [comment]
I must have missed it. I don't see a solution for static getters.
