### ISSUE TITLE
ternary expression in Omit not works

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#50317]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM7AQBQPYAOOUhGAPACrIQAekIAJhsgOQAW0eLyAPqwOZ48DbgF4BQkQD5kAbwBQyZGACeBCAH4AXMgoBuRcmABbOPwg6MYKKH4GlJ-gAkIwfmzA6qtek1YcSbg1kEABXYwAjaGQdUMYIGFAIBgMAX3l5AHpMkLwwZAB3PCgAawx5GDiEMGA8EGUIK0pqOghGZnZObj4WQWExCX6pAAoCEgIMHQB5Y2AwMnQsXEJiUgAaXRbfDr6RZGCWRxc3D24dFhYpAEo5QwQ6q2U1FHEx0gA6VXV5dKzMotKyQqVRqdQaVgAjM0fG0-J1ArxBntxL1JJdRuNJpsYe0kUFkDM5gtMNh8ERMRtWEdXO4wJcYmgSctyaQbgolPcQI8vi9kG8Jp9nj8gA)

### 💻 Code

```ts
interface BasicPopProps<T extends 'hero' | 'good' = 'good'> {
  type?: T;
  image: string;
  imgHeight: T extends 'hero' ? number : undefined;
}

// not works
function test<T extends 'hero' | 'good' = 'good'>(props: Omit<BasicPopProps, T extends 'good' ? 'imgHeight' : ''>) {
  const type = props.type
}

//worked
function test1<T extends 'hero' | 'good' = 'good'>(props: T extends 'good' ? Omit<BasicPopProps,  'imgHeight'> : BasicPopProps) {
  const type = props.type
}
```

### 🙁 Actual behavior

see playground

**Comment by RyanCavanaugh** [comment]
We don't have any mechanisms for selective non-deferral of a conditional type which would allow this to work, nor any good ideas about how to add such behavior at this time
