### ISSUE TITLE
There is no error when we have type alias enum + number

### ISSUE THREAD

**Issue by r2d20su** [microsoft/TypeScript#50318]
# Bug Report

### 🕗 Version & Regression Information
ts latest & stable

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBAyglgcxAFQJ4AdhQN4FgBQURUAggDQHFQBCFhxAwgQL4Fv4A2wALlAM6IQALliC0mKAB8oATgAMUALyy57LrwFIATCPhJxWaQHIAhkaVRTR9gQQ8ASgHsAZhwAUmkAEooAel9QII5QwABOoY6h7HbcTq4eglo+-iHhkezOYCAAxtxwjiBQMXHu3BjAumLlPnj0RKE8YKGFZRKK7aL65QB0JFAA-JYA1sBD5iJGEa7W+Kz4NvhAA)

### 💻 Code

```ts
enum SignType {
    A,
    B,
    C
}


let sign: SignType | 90 = 90

let sign2: SignType | 'a' = 'a'


getRofl(sign) // no error

getRofl(sign2) // error

function getRofl(type: SignType) {
    return type === SignType.A ? 'kek' : 'rofl'
}


```

### 🙁 Actual behavior

We have no error when we throw to function type alias (enum + number) and function's arguments has exactly enum type. When we have type alias (enum + string) we get error.

### 🙂 Expected behavior

We should see error when we try to use type alias (enum + number) if we expected exactly enum type

**Comment by MartinJohns** [comment]
This is intentional. See #48296.
