### ISSUE TITLE
Type inference broken when Parent and Children are both Generic.

### ISSUE THREAD

**Issue by mguerrero-ias** [microsoft/TypeScript#50323]
# Bug Report

When both the Children and Parent are generic, the children defaults to unknown, or the default implementation of the generic, when the parent is also generic.

### 🔎 Search Terms

- Generic Parent ignores Generic children React
- Generic Factory ignores Generic Children types.
### 🕗 Version & Regression Information

- Current

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFkBPONCAEyTgHMIkBnOABZIi5JAA9IsOMAB2MYZnQdkKVgHkZAGwYAFHGH4BvcnFPTOM6EhXqtDAPwAuOACMIETahkUzcVsF4UF09WJ1d3TxRvcgBfSnFJeBYZXngAdWAYARsNbTgAXjgAHgAVABoAPgAKAGFcSBkkOWcVDAA6OvAIRrkShjAkUoqAShbiGA767qaYPoHSuAAyRFRbbT0IAwqC7eNfZNSV1VyGToaZgrgqsH1eZxLhnbg93zMD+EM4Nu+iQ5jLm6bfgofglJZHNa6W4+V6mIgwACuUBkxTO0zkz2+bSqv3gILgD3+-kCwSQrHyhhgUARSH+VAqMNMMQoJjM8KRKJydjRPRgFGZlHecAAIvpWBAAO4owqlSrXW7OT6ZJAgO4EgDaAF1SHBujUBFFOEhnFVWCgYCh7o98tsAG4QYCsOAxa27VlwpCI5FXd2vIoIzQVX2w0yGQEGNrK1VtEAoMBVKpRsrSGTsMSu57BkO+dneoqaYC6mQ1AtoADWFKqGfDvDaeoNMiNifkIGGMQqhlkaZiRSoBYZWdhLri2d7AaDvmG-JZQtFm3FUq5eUKGSyS4YVTnYAXMinlBocDS0DLvHIRS3O+kLd4FPVnxkKBAxoIAGVcEhpvhncn74-n-g3yfaY4CQTReCQL8Yk1f560NJBKyjDMUE8WBmxVNoHyfNs4HpFkD2FHheBkfB4AlY8zwvSUZHXK8VRvQw7zgTD-0Aj9Gkgn8mL-ZwAPfYDQPAyDoKLfU4IQlskJQmA0JADC-2w3CcNoABJXheBpNogA)

### 💻 Code

```ts
export interface ReadOnlyProps {
    ignoreReadOnly?: boolean;
    disabled?: boolean;
}

export const WithReadOnly = <T,>(Component: React.ComponentType<T>): React.ComponentType<T & ReadOnlyProps> => {
    const ReadOnlyComponent = (props: T) => {
        const { ...rest } = props as T & ReadOnlyProps;
        return <Component {...(rest as T)} disabled={true} />;
    };

    return ReadOnlyComponent;
};

const Dropdown = <T,>(props: { items: T[]; onChange: (data: T) => void }) => {
    return (
        <ul>
            {props.items.map((item, index) => {
                <li onClick={() => props.onChange(item)}>{index}</li>;
            })}
        </ul>
    );
};

const DropdownReadOnly = WithReadOnly(Dropdown);

// Works
<Dropdown items={[{ name: 'Someone' }, { name: 'Someone else' }]} onChange={(item) => alert(item.name)} />;

// Doesn't work
<DropdownReadOnly items={[{ name: 'Someone' }, { name: 'Someone else' }]} onChange={(item) => alert(item.name)} />;
```
### 🙁 Actual behavior

The generic types get removed from the children.

### 🙂 Expected behavior

The generic type of the children is used to infer the generic type of the parent.

**Comment by RyanCavanaugh** [comment]
To make this work, TS would have to be able to "move" the type parameter from `Dropdown` to the return type of `WithReadOnly`, but basically it can't. There are places where it's possible to make a non-generic function generic again but this isn't a supported case.

**Comment by mguerrero-ias** [comment]
@RyanCavanaugh Any idea how  I should proceed anyway? :(
I'm sorry if this wasn't the proper way.
