### ISSUE TITLE
Union type not being generated correctly?

### ISSUE THREAD

**Issue by reggi** [microsoft/TypeScript#50330]
# Bug Report

### 🔎 Search Terms

union type

### 🕗 Version & Regression Information

na
### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.7.4#code/JYOwLgpgTgZghgYwgAgDIQOYB4AqyC8ycIAngHzIDeAsAFDLIhwC2EAXMgM5hSgZ0BfOnQQB7EN2S8MACzDoMHBVgDk0uSoqEa9Ri3bI1wWWGQAbTCsHDaYiaYsx5mJZlWOwmglToMmrDhUPc0trWhFxSQQ4U21fEIxODgBtdWcMABoQpwUAXUEgA

### 💻 Code

```ts
interface Leg<T = any> {
  name: string
}

const rightLeg: Leg<'right'> = {
  name: 'right leg'
}

const leftLeg: Leg<'left'> = {
  name: 'left leg'
}

const cat = {
  legs: [rightLeg, leftLeg]
}
```

### 🙁 Actual behavior

The type of cat.legs is be `Leg<'right'> []`.

### 🙂 Expected behavior

The type of cat.legs should be `(Leg<'right'> | Leg<'left'>)[]`.

**Comment by reggi** [comment]
Feel free to close if this is an incorrect assumption

**Comment by reggi** [comment]
this is the same:

```
interface Leg<T> {
  name: string
}

type Right = Leg<'right'>
type Left = Leg<'left'>

const rightLeg: Right = {
  name: 'right leg'
}

const leftLeg: Left = {
  name: 'left leg'
}

const legs = [rightLeg, leftLeg]

```

**Comment by fatcerberus** [comment]
Because TypeScript is structurally typed, `Leg<'left'>` and `Leg<'right'>` are in fact the same type.  You will find that they are even assignable to each other.  To avoid this, you need to actually use the type parameter in the definition of the type.
