### ISSUE TITLE
Unimplemented interface fields are not preserved in classes, allowing them to be overridden incompatibly by subclasses

### ISSUE THREAD

**Issue by c-harding** [microsoft/TypeScript#50335]
# Bug Report

Unimplemented interface fields are not preserved in classes, allowing them to be overridden incompatibly by subclasses. Specifically, an interface can define an optional field, which is omitted by an implementing class. Any subclasses can now introduce conflicting definitions of this field, without any warnings.

### 🔎 Search Terms

typescript override optional interface field in subclass

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (3.3 to 4.9.0-dev.20220817), and I reviewed the FAQ for entries about inheritance

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/JYOwLgpgTgZghgYwgAgJLmvJyDeAoZQ5YAWwAcAbCEiDAEwAoBnMKALmRalAHMBKDgDcA9sDoEiTYTTAALXgH4GAzq154AvnjwIKcJk2QBlAK5lou-YdKVqtMIfSRYiFPiLFyVGvWasOXLx8uBIehAjCIFJUAHQUwjx+UHyhyFpaOnoGxiYARpbZEAAekCB0hqbmUAWG7pLSEHK8yAC8yAAsmtoRUWDEvXAgSByVFlmGbSAQAO45+ePKOpEs-c5YEOgsg8NoGC7YbaBbQxDawDDIDKBrrptg2xAxUjLyIPzIqT3Rj-GJ15i3AYnJ4NJpvZQpIA)

### 💻 Code

```ts
interface Interface {
    implemented(str: string): void
    something?(): string
}

class Superclass implements Interface {
    implemented(str: string) {
        console.log(str)
    }
}

class Subclass extends Superclass {
    something = 4
}

const instance: Superclass = new Subclass()
const interfaceInstance: Interface = instance

if (interfaceInstance.something) 
    console.log(interfaceInstance.something())
```

### 🙁 Actual behavior

- `Subclass` was allowed to override `something`, despite it already existing in the inheritance chain.
- `Subclass` was allowed to be typecast to supertype `Superclass` then to supertype `Interface`.
- The optional function defined on the interface was allowed to be called (after a truthiness check; this also works with optional chaining `interfaceInstance.something?.()` for sufficiently new versions of TypeScript).
- The call fails at runtime, because `something` is truthy, but not callable.

### 🙂 Expected behavior

A type error should occur at the point of definition of `Subclass`. This should either be a result of checking the whole inheritance tree, or by the type of `Superclass` containing information about the field `something`.

I do not know whether it should be legal for Subclass to provide a conforming definition of `something`. If so, it would make sense for `Superclass` to inherit this as an optional field (i.e. `Superclass["something"]` = `Interface["something"]`), otherwise the type `Superclass["something"]` should be `undefined`.

**Comment by whzx5byb** [comment]
Optional fields are unsound.
See https://github.com/microsoft/TypeScript/issues/42479#issuecomment-767226743 and related issues.
