### ISSUE TITLE
result of "Exclude<unknown, undefined | null>" should be "{ }" in ts 4.8 ?

### ISSUE THREAD

**Issue by eczn** [microsoft/TypeScript#50334]
# Suggestion

``` ts
type T = Exclude<unknown, undefined | null>
```

`type T` above used to be unknown,  but in 4.8 it is close to `{}`

``` ts
// https://devblogs.microsoft.com/typescript/announcing-typescript-4-8-rc/
function f(x: unknown, y: {} | null | undefined) {
    x = y; // always worked
    y = x; // used to error, now works
}
```

<img width="450" alt="image" src="https://user-images.githubusercontent.com/13131724/185076287-8ed80abf-346c-486a-b68e-edd085fc2987.png">

[typescript playground](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAKlC8UCiAPAxgGwK4BMIB4sA7AayIHsB3IgGimLwDMBLIiHKAHyiKwwwB8AbgBQQA)

---

<img width="366" alt="image" src="https://user-images.githubusercontent.com/13131724/185078525-2ea881d8-2354-43d1-9a7e-2f4abc7696cb.png">

**Comment by fatcerberus** [comment]
`Exclude` works by filtering types out of a union and `unknown` is not a union type, so it can't do anything with it.  Same reason `Exclude<string, "foo">` doesn't work
