### ISSUE TITLE
Using `infer` on a tuple containing an object and its key does causes the `extends` expression to resolve to false.

### ISSUE THREAD

**Issue by ngregory-rbi** [microsoft/TypeScript#50342]
# Bug Report

### 🔎 Search Terms

infer
extends
false
key

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the `infer` keyword.

### 💻 Code

```ts
type ObjectAndKey<O = any> = [O, keyof O];
type DoesExtend          = [{ num: number }, string] extends ObjectAndKey          ? true : false; // true
type DoesExtendWithInfer = [{ num: number }, string] extends ObjectAndKey<infer U> ? true : false; // false
```

### 🙁 Actual behavior

Both should resolve to true.

### 🙂 Expected behavior

The latter type resolves to false.

**Comment by RyanCavanaugh** [comment]
I don't see a defect here. These lines of code mean different things and do different things as a result. The results are consistent with the equivalent expression type computations:
```ts
function fn<T>(arg: [T, keyof T]) { }
declare const x: [{ num: number }, string];
// Succeeds
const m: [any, keyof any] = x;
// Fails
fn(x);
```

**Comment by ngregory-rbi** [comment]
To clarify, how do the lines mean different things? All I did was add an `infer` statement. How does that ultimately make the line mean something else?

**Comment by RyanCavanaugh** [comment]
`ObjectAndKey` doesn't mean `ObjectAndKey<-- infer something here -->`. It means `ObjectAndKey<any>` because that's the default, and `ObjectAndKey<any>` means `[any, keyof any]`.

**Comment by fatcerberus** [comment]
`[{ num: number }, string] extends ObjectAndKey<infer U>` is false because there's no type you can infer for `U` (other than `any`, which TS tries not to do) that will make it be true.  `U` can't be `{ num: number }` because `string` is not assignable to `"num"`  When you leave out the type parameter you're then asking if it's assignable to `ObjectAndKey<any>`, which is true.

**Comment by ngregory-rbi** [comment]
Thank you for the clarification. I understand better now :)
