### ISSUE TITLE
Calling setter on variant accessors with function using type parameter errors

### ISSUE THREAD

**Issue by adeniszczyc** [microsoft/TypeScript#50355]
# Bug Report

### 🔎 Search Terms

- Variant accessors / generics / functions

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (4.35 -> nightly), and I reviewed the FAQ for entries about **variant accessors**.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/MYGwhgzhAEAqCmEAuAeAygPmgbwFDQOmAHsA7ZAJwFdgliKAKAShwF9d9CJ4loA3MCCrwGAofABc0SgEtSAc2gAfaAwYyk8ALZS0LALxZZCpi2ztOBeT36DhzKccV5Cr6BR5UKpaKSogQAEIAbktodlcwgHoo6AAleAAHcGA5RSQAC3hoayRNCmkaDOhMsF5M7Nz8qO48+AKkAE9ExGgtMuAMgBp3bWI+Voroeop6CWjY3NtxB2kkCjTlVXVNHWg9aEM5hZMcCbcPJC8fPwCQ-YjCfYB5Ch6PZLBUhRKs6R58ws7XsugwIjIwEO2SaLWgMhgVG4ABN7n0BjAhiMxvtatN7GJhI55osVGoNNopNhoIlRi0KE1sTtFKwDEYcSYzOwLCRyLx-vpfPAAO5wRCoFyEUnEcmU7ZpXCsDDMUK4MAAOkx2U5K20dPBq3lwtFjWgMWgAAUyfUmtAAOTak2NM3QaHEVqkYi8eAADwhvDIJWa2TNaDNQA)

### 💻 Code

```ts
class Test<S> {
    constructor() {}

    set value(value: string | ((item: S) => string)) {}

    get value(): string {
        return null!;
    }
    
    // -- Replacing the getter such that the getter/setter types match, removes the error:
    // get value(): string | ((item: S) => string) {
    //     return null!;
    // }
    
    // -- Or, replacing the setter such that a concrete type is used, removes the error:
    // set value(value: string | ((item: { property: string }) => string)) {}
}

const a = new Test<{
    property: string
}>();

a.value = (item) => item.property // Property 'property' does not exist on type 'S'
```

### 🙁 Actual behavior

Using variant accessors, with the setter taking a function with a class generic type as an argument, compilation fails with the
error `Property 'property' does not exist on type 'S'` (marked in code example above). This error does not occur if the type of the getter matches the setter, if the getter is removed, or a concrete type is specified instead of a type parameter in the setter.

### 🙂 Expected behavior

No error with support for inferring the generic type `S` when assigning with the setter.

**Comment by whzx5byb** [comment]
It seems that to make it work the type returned by `get` must have a reference to `S`:

```ts
class Test<S> {
    constructor() {}

    set value(value: S | ((item: S) => any)) {}

    get value(): S {
        return null as any;
    }
}

const a = new Test<{property: string}>();
a.value = function (item) { item.property } // it works
```
