### ISSUE TITLE
Numeric string key is being converted to a number in declaration file

### ISSUE THREAD

**Issue by tinytim84** [microsoft/TypeScript#50358]
# Bug Report

When TS converts a specific type into a static type in a `d.ts` file, it's converting numeric string keys into a number, e.g. `'1'` becomes `1`.  It seems similar to [the issue described here](https://github.com/microsoft/TypeScript/issues/37292), but my value is being re-mapped  with generics and mapped types, so it seems like it's a more complicated version of this. The `.d.ts` tab in the playground link shows what is happening.

### 🔎 Search Terms

numeric string key converted to number 

### 🕗 Version & Regression Information

TS 4.7.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQZTFYAOwGsAbNAZwBo4ATNAMyLQAUoIw1ZhK4BfOA3Yg4AcgACANwyFgpUhgC0aAB4woGZDAD0FfETKVRAbgCwAKAvIIhCvHR6bFYJNbtO3XgF46jZmw4uGB4KAAoECzgUG1pgYKcALkRIqLgQCAAjOTQkhD4qFKiYDAzyGFz8wt8KYhgOCoLzKMqm3wYMAFdSGABhGLjgGyTRdKzyUUao-EDPClyq7QAqRaq4RbgAWQwoAHMiOBs4GAALNCOOOGd6ADpVldbU9fF6dq74ACIABne77SqQbZ7QgAFXqyQeqVEn1ESU+k1SUVEAEYYXAAGzwhGiABMqKR2MxkIAzHiAByEloIpb3BFrOAACQgAHcjqc4BkICpLscIF1aOyzrE9AoAJ5oWi3CFrP4QoVgUVJADaolKEGQxAmYiIpGYogAuvCWnwAJRmSzmVSQWDRWzwDkqPAEEjkChwHyoTDYR0GF2hByQWwuNwzYKUU0WbTaWnRgB6AH4LJboPAYCLOHAAEKc73O7xwFjbDAgNDYKAUAA8qc4EAY7Oz+lzFAAfIrPnqzUA)

### 💻 Code

It's an issue with compilation, the playground link above shows it. 

### 🙁 Actual behavior

Conversion of a specific type with mapped keys to a static type is resulting in string numeric keys being converted to numbers. e.g. `'0'`, `'1'`, getting converted to `1`,`2`.

### 🙂 Expected behavior

Keys to remain as strings and not be converted to a number.

**Comment by fredericoo** [comment]
I’m facing this on `6.6.3`. Perhaps a regression?
