### ISSUE TITLE
Type inference should consider all function parameters

### ISSUE THREAD

**Issue by jeengbe** [microsoft/TypeScript#50376]
# Suggestion

## 🔍 Search Terms

Inference, Function, Generic, Parameters

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behaviour of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When inferring type parameters of a function based on parameters, TypeScript should consider all parameters that use the generic type.

```ts repro
// @errors: 2345
interface A {
  x: string;
  y?: string;
};

declare function fn<opts extends A>(
  opts1: Partial<opts>,
  opts2: Partial<opts>
): void;


  fn({ x: "x" }, { y: "y" });
//^?
  fn<{ x: string, y: string }>({ x: "x" }, { y: "y" });
//^?
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEFMCdoe2gZwFygEwGYAsBWAUAJYB2ALjAGYCGAxpKAIKgDeeooAHqoidMQOYBuVqACeAfi49+QgL5C8AE0jUANpWh1yAVyLUSBOEVDkiAHjgAHEolCR2ZIgpv0AfAAphl6wEZUABXV9ShVzK0QXABpPMLR-QIJg0OsXPABKVAA3OAIFeWETNyYOVAAidhLQGQjmUVKRCplUoRAAPTF8syLOUG5eIj5q8Uk+vkr3LtLyyuqikTqGprxWsSA)

In this example, in the first function call narrows `opts` down to `{ x: string }` based on the first parameter `opts1` only. However, as `opts` is used for both `opts1` and `opts2`, TypeScript should consider both parameters when narrowing a type for `opts`.
As seen in the second call, a solution does exist in which the constraint is met and neither parameter errors.

In the meantime, this can either be completely avoided by a different solution, or the generic type can be passed explicitly.

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript/issues/32596#issuecomment-516054244
