### ISSUE TITLE
Intl.ListFormat still shows error with target ES2021

### ISSUE THREAD

**Issue by blessanm86** [microsoft/TypeScript#50381]
# Bug Report

I am still getting errors that ListFormat types are not available. I followed this https://github.com/microsoft/TypeScript/issues/46907 and set the target as `ES2021` and still doesn't work.

### 🔎 Search Terms

TS2339: Property 'ListFormat' does not exist on type 'typeof Intl'

### 🕗 Version & Regression Information

I tested with version 4.6.2 and also tried with the latest version and include a link below

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220820#code/MYewdgzgLgBApgWwA4AsCGECWAvOATAGU2hgF4Yw4B3GASTCgBsA6I6AMRACcE0oAKAORwwggDQwA3gCgYcmNACejOAC4YgxuADm42fKiKkajaDAArAK5hgUTOD0BfAJTMAZt14CA2oLTjBACNBAF1nAG4gA)

### 💻 Code

```ts
const emphasizedList = new Intl.ListFormat('en', {
    style: 'long',
    type: 'conjunction',
}).format(['a','b']);
```

### 🙁 Actual behavior

Type information is not available

### 🙂 Expected behavior

Intl api types should be available when tartget is set to ES2021

**Comment by MartinJohns** [comment]
> I tested with version 4.6.2 and also tried with the latest version and include a link below

The changes were added in 4.7, and your link to the playground is set to ES2017. Change the target to the correct ES version and it works.

**Comment by blessanm86** [comment]
Thanks @MartinJohns  that worked.
