### ISSUE TITLE
Type narrowing doesn't work inside constant ternary operator

### ISSUE THREAD

**Issue by Noa-Ivix** [microsoft/TypeScript#50393]
# Bug Report

### 🔎 Search Terms

* Ternary narrowing
* Constant ternary
* Constant ternary narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220821#code/GYVwdgxgLglg9mABAdzgJwNYGcCMAKLALkTBAFsAjAUzUQB8SQAbJgSkQG8BYAKEUTRUoINEiyIAhAF4pjFogD8iLADoocAMpQ0MMAHM87YgCJjvAL69QkWAhTpsAJgLFSlGvTltOvfoOGiiNogVIqIeL78UeLSsqTySqrqWjr6hogmZnxRRoimANwWVuDQ8EgAJnBUWGBQAPqomFgujO60DPHe3Nn+IkjAAIZMWKFKEdlRypIyXmFJmtq6BrmmkZPr6wD0m4gAeogA8hQAVlTQiDDiAA5wWFgwFEwAnogA5J2va4grxoU85kA)

### 💻 Code

```ts
function works1(s: number | null) {
  return s !== null ? s.toString() : ""
}
function works2(s: number | null) {
  return true ? (
      s !== null ? s.toString() : ""
    ) : "";
}
function doesnt_works(s: number | null) {
  return false ? (
      s !== null ? s.toString() : ""
                // ^ Object is possibly 'null'
    ) : "";
}
```

### 🙁 Actual behavior

Function `doesnt_work` fails to compile because `s` is assumed to be `number | null` even though we just checked that `s !== null`.

### 🙂 Expected behavior

This should either compile successfully or maybe produce an error/warning about unreachable code.
The expression `s !== null ? s.toString() : ""` was correct when used on its own but became invalid once I placed it in a `false` branch of a ternary operator, for no apparent reason.

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/26914
