### ISSUE TITLE
package-self-reference types not works

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#50390]
I am trying to use `exports` to verify package-self-reference, it works fine but  the IDE can't find the package types like

![image](https://user-images.githubusercontent.com/49113249/185788625-cb935a51-c1e2-4fd5-b0fc-f8c9b6448082.png)

the package.json is :
```json
{
  "name": "test-entry-ts",
  "types": "index.d.ts",
  "exports": {
    ".": {
      "types": "./index.d.ts",
      "import": "./index.mjs",
      "require": "./index.cjs"
    },
    "./a": {
 "types": "./a.d.ts",
      "import": "./a.mjs",
      "require": "./a.cjs"
     
    }
  },
  "typesVersions": {
    "*": {
      "a": [
        "a.d.ts"
      ],
      ".": [
        "index.d.ts"
      ]
    }
  },
  "devDependencies": {
    "@types/node": "^18.7.8",
    "typescript": "^4.7.4"
  }
}
```

you can find the whole directories [here](https://github.com/HomyeeKing/test-entry-ts)

**Comment by HomyeeKing** [comment]
also typescript can't recognize `types` field in exports if using as self-reference but works as node_modules

**Comment by IllusionMH** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing

> Note that the `"types"` condition should always come first in `"exports"`.

**Comment by HomyeeKing** [comment]
@IllusionMH  I've notice that but still not works

**Comment by jakebailey** [comment]
This might be the same as #50270.

**Comment by HomyeeKing** [comment]
@jakebailey my situation is  neither `.ts` nor `.(c|t)js` works
btw both `module` and `moduleResolution` are `NodeNext`

**Comment by jakebailey** [comment]
I'm not sure what you mean; the issue I linked only shows the bug in an mjs file.

**Comment by HomyeeKing** [comment]
@jakebailey  
it's really wierd, I just got the same result as what you met, but it did not work(can't find type declaration) in `.ts` file before

**Comment by andrewbranch** [comment]
> btw both `module` and `moduleResolution` are `NodeNext`

Not for `test.ts` they’re not, because you put it in your tsconfig’s `excludes`. Errors in `test.ts` are coming from your editor’s default compiler options. It works when you remove that entry from `excludes`.
