### ISSUE TITLE
Typescript class inheritance does not inherit types correctly

### ISSUE THREAD

**Issue by Autumnlight02** [microsoft/TypeScript#50396]
# Bug Report

### 🔎 Search Terms

When did you start seeing this bug occur?
version: "typescript": "^4.7.4"

### ⏯ Playground Link

[link to test it out](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChnJgCeADhAFzIBEAglcgD7WpUDcuAvrrqJLIilTIIAD0ggAJhjSYc+QqQrM2nbggA2maQCNZyYAFsS6iAYjhp6LMjwESUAPaQEkCcgD6xMpSsQA2lReEFQAuuwECA4gGGBQAK4uDlAAFPYOJD6yAUGhAJQ28gRgABbAGAB0norIALzIaSThyFwEAOYQYApkyfm2BMhQHXFQIISlFVVkTVxcuBpayNrCYuZSi3qGxqbmYJYFEVEx8YkpvYXIGHFkKVQsyJgyWNmKedOqc4edkDG1yCAQAHdFj12JFog4TOV1A5WslvmBykFcqxkAB6VGpRzXYj5XRYRGKSi0ehMW5UXDo+EEsj3dQAuBEaSDMDDaJoC6gJBjFCXa7Idq7ZAIODqExuKLqIjIAHAErs7RxL6KDAIKDAEidGBJC4OMwDCCYKL3DCXMzSWVCuCjbQobROYoU1EASVGCGKjj1FpF9MZ+pZI2kZKAA)

### 💻 Code

```ts
interface Base {
  type: "A" | "B";
}

interface B extends Base {
  type: "B";
}

class base implements Base {
  protected _type: Base["type"];
  constructor(prop: Base["type"]) {
    this._type = prop;
  }
  get type() {
    return this._type;
  }
}

class b extends base implements B {
  constructor() {
    super("B" as Base["type"]);
  }
}

const test = new b();
console.log(test.type); //(property) base.type: "A" | "B"
//test.type always returns B since the super gets called only with B but typescript for some reason assumes it can be both
```

### 🙁 Actual behavior

The actual Behaviour is that typescript assumes that test.type is either "A" or "B", but in reality it can be only "B" since the prop withhin the class b is hardcoded. In addition a way of fixing this is to redefine type and the get type in class b but then the extension itself doesnt make sense anymore.

### 🙂 Expected behavior

I expect that typescript inherits from the super prop that this.type is "B" and so get type can be only "B" since "B" is a hardcoded prop.

**Comment by MartinJohns** [comment]
`b` implements `Base`, and `Base.type` clearly states it can either be `"A"` or `"B"`.

**Comment by Autumnlight02** [comment]
The thing is that Base.type states that its either "A" or "B" but when setting it to an value should it not be narrowed down? Or for example why does this then not work 
![image](https://user-images.githubusercontent.com/68244453/185846063-ca46e873-05b2-426e-9ee8-aa0fa0e6688f.png)

**Comment by MartinJohns** [comment]
Please post code, not screenshots of codes. It's inaccessible to a lot of folks.

Narrowing within a function has no effect outside the function.

**Comment by fwienber** [comment]
What @MartinJohns said. Actually, the `as Base["type"]` in the super constructor call has no effect at all, as `"B"` is already a valid value for the super constructor parameter type `Base["type"]`, which is `"A" | "B"`. It can just be left out.

To achieve what you intend, namely telling the type system that in subclass `b`, the value of
`type` is _always_ `"B"`, you must override the return type of the `type` accessor. But you are lucky, this can be done without adding any run-time code, just by declaring an interface of the same name `b`, which TypeScript then unites with the type declared by class `b` ("declaration merging"), like so:

```typescript
interface b {
  get type(): B["type"];
}
```

[Complete code in TypeScript Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4oN4ChnJgCeADhAFzIBEAglcgD7WpUDcuAvrrqJLIilTIIAD0ggAJhjSYc+QqQrM2nbggA2maQCNZyYAFsS6iAYjhp6LMjwESUAPaQEkCcgD6xMpSsQA2lReEFQAuuwECA4gGGBQAK4uDlAAFPYOJD6yAUGhAJQ28gRgABbAGAB0norIALzIaSThyFwEAOYQYApkyfm2BMhQHXFQIISlFVVkTVxcuBpayNrCYuZSi3qGxqbmYJYFEVEx8YkpvYXIGHFkKVQsudOqvNDwSIv7yO2dQT0+2Yqh7FmkWiXwgMVqyBAEAA7oseuxgRgHCZyuoHK1kpAYuUgvdkAB6fGpRzXYj5XRYHGKSi0ehMW5UXCErFgKlkZBwdTQuBEaSDMDDaJoC6gV4lFCXa4fDrSBCckxuKLqIjIaHAErC7RxL6KDAIKDAEidGBJC4OMwDCCYKIcjCXMzSdXIOWjbQobROYpM-EASVGCGKjgtTs53N5loFI2kDKAA)

Now, `test.b` is inferred to have type `(property) b.type: "B"`, which is what you wanted, right?

**Comment by Autumnlight02** [comment]
@fwienber THANK you, that was the solution I've been searching for!
