### ISSUE TITLE
.filter with typeof filter does result in filtered array on the type

### ISSUE THREAD

**Issue by PMLP-novo** [microsoft/TypeScript#50413]
# Bug Report
![image](https://user-images.githubusercontent.com/54025656/186122746-e3477491-69f8-4aae-9919-ef4203a29695.png)
Compared to the excepted behavior that the compiler would understand that the output array only consists of strings

### 🔎 Search Terms
filter, .filter, array filter, typeof

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link
[[

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)
](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhmAogDzgWwA4BsCmA1OAJwEs4AjXGAXhgG0AiAQXoBoAmFsAVyywF0AdADNiWKDkIAKAG5UAfFACeGHCCExp1KjXrQSYAOb0AlACggA)](https://www.typescriptlang.org/play?ssl=1&ssc=72&pln=1&pc=1#code/MYewdgzgLgBAhmAogDzgWwA4BsCmA1OAJwEs4AjXGAXhgG0AiAQXoBoAmFsAVyywF0AdADNiWKDkIAKAG5UAfFACeGHCCExp1KjXrQSYAOb0AlACggA)
### 💻 Code

const anExampleVariable = ["A",2,null].filter(v=>typeof v === "string")

**Comment by MartinJohns** [comment]
See #47194 and many many others.
