### ISSUE TITLE
Add the possibility to specify type arguments to arrow functions

### ISSUE THREAD

**Issue by corno** [microsoft/TypeScript#50417]
# Suggestion

Adding the possibility to specify type arguments to arrow functions would reduce redundant type specification (in our case, a lot): <T>(a) => { ... }

## 🔍 Search Terms
type inference arrow functions
type inference type arguments
arrow functions type arguments

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Adding the possibility to specify type arguments to arrow functions would reduce redundant type specification (in our case, a lot)

## 📃 Motivating Example
[playground example](https://www.typescriptlang.org/play?ssl=20&ssc=95&pln=20&pc=101#code/C4TwDgpgBAsiBiBXAdgYwCrmgXigCgEMAuKAZ2ACcBLZAcwEopsA+KANwHsqATAbgCh+qDsnJQAtghSoAkuLAk4SNJkhN8BRiygBvKAHp9UADwBaU1GAALaADMCqYJasEn1qqSgEKtROIjITh5QHLaWWGSUNLRQ3BwQnsgcTi5s0MAcUABG0BQJkKhUtlQQ3AA0UABWiGLW0N6+-oFQyAT+UMEBHIi0VvxQA14AdAHcpADqVNZ4AES2HBwz9PwAvoKGSQDulhQg0c7QpG3Qm1NW4Wpg3sfAEBSkRIKgakrSqhCT1u8ACtf+txR1MZ0MxCCRyNQ6FpWJweAJ1kZhKInJJlLJ5J8rD8-hAAQB9eAEKgAG2iiikKgiuGBoM0TFYekMJnMUBkUE23WJ3CgEAAHgVgPorBw1NZXM5gsJ5CSEhU6hcEiEwgBydDKrzIbnKgjq7zQADWW2Q-CZgygSLEkgAghQKAQQCR0ABtAC66ldAlNgwII01EzOs3mi2WTLWCLZyAgpUsmTiEs8GSgtFxHTcmRy5o40uJpTlVmCOYIYxjXigxOSSqgeUgwCmVBEHTC8qo8hzTWArnrokrtmktZEnj1ZDApKctgoWYOVEBpAKRSoqE7A4qm3zqHOwXli9I0BoIUQgOE3GgWQIO8EFpRFPRYEx2Lt-zueIAwlmwCTogAmclo953rC-A+uJ3OovZoP2yAdPINJgpEkIMCQsLcoyRhmBYeQtiOEDtgcUBgY4XaxBAqDEtcEH9IMhiYW2AQduRZqXhIIA2naDpQM6bq4B6FEDD6oz+tMcwLEsqxAA)

## 💻 Use Cases
In the code base that we have, we specify the function declarations with typed parameters in 1 file and the implementations in another file.
When functions have complex declarations (multiple type parameters and normal parameters, it is cumbersome to keep them in sync.
So far, we are re-specifying these parameters.

**Comment by corno** [comment]
sorry, the content was erased upon first submit. It should be okay now

**Comment by MartinJohns** [comment]
@corno You forgot to fill out the whole issue template.

@fatcerberus When a type argument is involved it won't infer the type for the parameter `a` in `const identifier: MyFuncType = <T>(a) => { ... }`

**Comment by corno** [comment]
@MartinJohns I updated the template. Besides the compiler not inferring the type for parameter 'a', it is also not possible to refer to the type parameter 'T' in the implementation.

**Comment by fatcerberus** [comment]
> it is also not possible to refer to the type parameter 'T' in the implementation.

Sure it is.  You just might have to specify the type parameter list as `<T,>` so it doesn’t get parsed as JSX.

**Comment by corno** [comment]
@fatcerberus  I see. Thank you for letting me know. That means that this feature request is no longer properly formulated. I will submit a new issue. Would you consider not inferring the type of 'a' a missing feature or a bug?

**Comment by MartinJohns** [comment]
> I updated the template.

My mistake, I really thought the "Code" section was part of the feature request template as well, and I didn't see any code. The playground quite often crashes my browser, so it's tough to see the relevant code there.

> You just might have to specify the type parameter list as <T,> so it doesn’t get parsed as JSX.

Or disable React.

**Comment by corno** [comment]
> > You just might have to specify the type parameter list as <T,> so it doesn’t get parsed as JSX.
> 
> Or disable React.
I can't find how to do that. Can you give me a pointer?

**Comment by corno** [comment]
I will file a bug report for the lost type info
