### ISSUE TITLE
interface with "new" member not working

### ISSUE THREAD

**Issue by chibisuke** [microsoft/TypeScript#50425]
# Bug Report

declaring an interface with a method named "new" is not working properly

### 🔎 Search Terms

interface new member
interface membername new

### 🕗 Version & Regression Information

Seams to effect all versions including nightly.

### ⏯ Playground Link

(https://www.typescriptlang.org/play?ts=3.3.3#code/JYOwLgpgTgZghgYwgAgJIBUIGczIN4CwAUMqciBAO4AUAlAFzkCuAtgEbQDcxAvscQgA2cLFmSQcyYCwAOgiCwjgxGbLkIkyFGrXzEyB5FAhgmUEMgCs3TaT5F7QA)

### 💻 Code

```ts
interface ITest {
    new(): number;
}

class test implements ITest {
    new() {
        return 5;
    }
}
```

### 🙁 Actual behavior

Error: 
Class 'test' incorrectly implements interface 'ITest'.
  Type 'test' provides no match for the signature 'new (): number'.

### 🙂 Expected behavior

Interfaces should allow the (in JS) non-reserved "new" to be used, so one can create interfaces for already existing classes.

**Comment by MartinJohns** [comment]
This is working as intended.

`new()` is TypeScript reserved syntax that declares a needed constructor. You have to write `['new']()` instead.

**Comment by chibisuke** [comment]
thx that works for me, but I still don't get the point of calling a constructor "new" in interfaces and "constructor" in classes? why does it need two different keywords for the same thing?

**Comment by fatcerberus** [comment]
Because `constructor` is not a keyword, and actually creates a property called that (even in classes).  JS just happens to treat it specially in classes, but not, e.g. in object literals, so TS needs a general way to express “this is a type you can call with `new`”
