### ISSUE TITLE
The optional chain operator has side effects

### ISSUE THREAD

**Issue by EtherDream** [microsoft/TypeScript#50426]
# Bug Report

TypeScript Version: 4.8.0

Search Terms: side-effects

Code:

```ts
Function.prototype.call = function() {
  console.warn('side effect')
}
console.log?.('hello world')
```

Expected behavior: Show only `hello world`

Actual behavior: Show `side effect` and `hello world`

Generated code:

```js
"use strict";
var _a;
Function.prototype.call = function () {
    console.warn('side effect');
};
(_a = console.log) === null || _a === void 0 ? void 0 : _a.call(console, 'hello');
```

Calling global methods directly is not rigorous enough, it is better to use the [primordial function](https://github.com/nodejs/node/blob/a957f7bd3701359591a1ca6d6debb6002e3ff256/lib/internal/util.js#L10) like Node.js

Expected generated code:

```js
"use strict";

function methodToFunction(method) {
    return method.call.bind(method)
}
var FunctionPrototypeCall = methodToFunction(Function.prototype.call)

var _a;
Function.prototype.call = function () {
    console.warn('side effect');
};
(_a = console.log) === null || _a === void 0 ? void 0 : FunctionPrototypeCall(_a, console, 'hello');
```

Or an even shorter implementation:

```js
"use strict";

var methodToFunction = Date.bind.bind(Date.call)
var FunctionPrototypeCall = methodToFunction(Function.prototype.call)

var _a;
Function.prototype.call = function () {
    console.warn('side effect');
};
(_a = console.log) === null || _a === void 0 ? void 0 : FunctionPrototypeCall(_a, console, 'hello');
```

In addition, compared to `fn.call(...) `, `call(fn, ...) ` has higher performance on v8:

```js
function add(a, b) { return a + b }

var methodToFunction = Date.bind.bind(Date.call)
var FunctionPrototypeCall = methodToFunction(Function.prototype.call)

console.time('t1')
for (let i = 0; i < 1e8; i++) {
  add.call(null, i, i)
}
console.timeEnd('t1')     // ~65ms


console.time('t2')
for (let i = 0; i < 1e8; i++) {
  FunctionPrototypeCall(add, null, i, i)
}
console.timeEnd('t2')    // ~48ms
```

**Comment by MartinJohns** [comment]
> var FunctionPrototypeCall = methodToFunction(Function.prototype.call)

Won't this depend on no other module having modified the prototype before?

**Comment by EtherDream** [comment]
> Won't this depend on no other module having modified the prototype before?

Even if the native method has been overridden before (e.g. shim), our program should always use the one at initialization, not the one overridden again later. 

This can cause some code to be executed unexpectedly, such as analyzing the number of native method calls.

**Comment by RyanCavanaugh** [comment]
We take reasonable trade-offs in terms of the simplicity of the generated code vs 100% spec compliance (which even the proposed code would not achieve). If your use case requires that `Function.prototype.call` not be seen to be invoked during an optional chain call, you'll need to use a different downleveler in your build chain.

**Comment by EtherDream** [comment]
This is not only a issue with `Function.prototype.call`, but also when using `Proxy`:

```ts
const obj = {
    log: new Proxy(console.log, {
        get(target, key) {
            console.log('intercept get:', key)
        },
        apply(target, ctx, args) {
            console.log('intercept apply')
            return Reflect.apply(target, ctx, args)
        }
    })
}

obj.log?.('hello')
```

Expected behavior: Show `intercept apply` and `hello`.

Actual behavior: Show `intercept get: call` and throw an error.

Reading the `call` property triggers the Proxy's callback.
