### ISSUE TITLE
Disable import organization on individual files 

### ISSUE THREAD

**Issue by ian-weir** [microsoft/TypeScript#50433]
# Suggestion

## 🔍 Search Terms

Organize Imports
Annotation
Disable per file

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Similar to prettier having // prettier-ignore or TypeScript having // @ts-expect-error it would be nice if we could have something like // disabled-import-organization.

## 📃 Motivating Example

This stems from an issue I had where the order of some imports in the project resulted in an error when the imports were organized alphabetically and it caused an error which was fixed by rearranging the import statements. Obviously the better fix would to be to change the structure of the system to eliminate this error regardless of the order. In the meantime it would be nice to ignore that individual file

## 💻 Use Cases

I would like to be able to have the rest of my imports organized without having to worry about dependency errors for a few select files. In the mean time we've had to disable import organization in the project.

**Comment by RyanCavanaugh** [comment]
Sounds like #23577 ?

In 4.7 you can solve this use case with just newlines, see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html

**Comment by ian-weir** [comment]
If I wanted the all the imports for a file to not be modified though I would have to have a space in between every import
