### ISSUE TITLE
Duplicate seeming Code Actions for convert const to let

### ISSUE THREAD

**Issue by justschen** [microsoft/TypeScript#50435]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

When there are multiple items that need to be quickfixed, seems like it creates duplicate `valdiCodeActions`

Accessible from both `ctrl + .` and from the hover to open the quickfix version of the code action widget.

See below: 

With only one instance of incorrect var:
![Screen Shot 2022-08-24 at 2 54](https://user-images.githubusercontent.com/54879025/186531549-874a04ef-7d5f-4f9a-ac0d-74f624489ff1.png)

With multiple instances:
![Screen Shot 2022-08-24 at 2 53](https://user-images.githubusercontent.com/54879025/186531544-239bdf8d-28c3-4e30-98d7-bf3072806a4f.png)

Gif!
![Recording 2022-08-24 at 15 00 12](https://user-images.githubusercontent.com/54879025/186531676-2d6d8420-a0a9-4579-a84f-4b93ccd1e568.gif)

Error message from Insider Console upon clicking the duplicated option:
![Screen Shot 2022-08-24 at 2 59 1](https://user-images.githubusercontent.com/54879025/186531798-0d77734a-c303-48ef-8121-45d5a9d318f3.png)

**Comment by mjbvz** [comment]
Minimal repo:

```js
//@ts-check

const a = 123;
a = 456;
a = 789;
```

The root cause is that this quick fix also indicates that a `fix all` version is available, however the fix all version has the exact same name (`fixAllDescription`) as the single fix:

```
 {
        "fixName": "fixConvertConstToLet",
        "description": "Convert 'const' to 'let'",
        "changes": [
            {
                "fileName": "/Users/matb/projects/san/x.jsx",
                "textChanges": [
                    {
                        "start": {
                            "line": 1,
                            "offset": 1
                        },
                        "end": {
                            "line": 3,
                            "offset": 6
                        },
                        "newText": "let"
                    }
                ]
            }
        ],
        "fixId": "fixConvertConstToLet",
        "fixAllDescription": "Convert 'const' to 'let'"
    }
```

In this example we should likely not include a fix all action since only a single change is needed to fix both errors

**Comment by DanielRosenwasser** [comment]
Everything about your repro feels bad.

1. If you pick a "good" fix, it removes the `// @ts-check` comment at the top. It's nuts that we would destroy all the trivia of the original code for what could effectively be a token swap.
2. If you pick the last one, yeah, there's a straight-up runtime error.

**Comment by fatcerberus** [comment]
> Everything about your repro feels bad.

I was confused by this at first because it sounds likes you’re implying the repro is suspect but then go on to describe why the buggy behavior itself is bad (which it is, based on that description).

**Comment by DanielRosenwasser** [comment]
Yeah, I just reread and it sounds pretty insulting - sorry for the emotional rollercoaster. 😅

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
