### ISSUE TITLE
`Object.entries` type-narrowing overload is used when called by a function, but not when passed as an argument

### ISSUE THREAD

**Issue by davidpcaldwell** [microsoft/TypeScript#50432]
# Bug Report

### 🔎 Search Terms

`Object.entries`, though I am sorry, I don't think it has anything to do with that declaration specifically. I don't know enough type-nerd terminology to even know how to describe the symptom below except as a failed inference.

### 🕗 Version & Regression Information

According to the [playground](https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBADgSzgUwFwwDwEEA0AhHAYQD4AKAQ3QvSwEoYBeYmAmAIyo5fqZkJ+bUYdRs0KMYFHOwGSEYOAFcosthVLylK2gCgdUAJ4oYAZSgAneQHMASslDmAJhIDeMANoAPdNEtgrALo+FtYwAL56AG7k5jDgaJLm9iBO6GZ+tslOsmCKALZsyLEM8EjIpDowVTAA8mwAVvZQAHTIYCHIEDiV1QBmimDAUAjgpJ70Lj3V1QD0M1XyvUVJzobGIL0wnjAIEB6+1tLkYAYB7gHsyjAQABYgigA2zoX7If7SB-5nF1YIkW07BRXXamN6ZByOKbTGBJKCKcxgLbNB5tKxQG4wABUMAATABuKERWgEnTRWJQADuICoSQhaTBdghOXyhWKpRQFWm-UGw1G5AmUOmsPhiLqjSGrXalk6FGJhO6XIGQxGYDGAuhs3mgKW5hWMDWyDim22IPcnysHzB30F1WFCKRKP86KxuIJ0yJOiAA), the issue occurs in every version since 3.9 (when `Object.entries` was defined) and in the 4.8 beta.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Object.entries`.

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBADgSzgUwFwwDwEEA0AhHAYQD4AKAQ3QvSwEoYBeYmAmAIyo5fqZkJ+bUYdRs0KMYFHOwGSEYOAFcosthVLylK2gCgdUAJ4oYAZSgAneQHMASslDmAJhIDeMANoAPdNEtgrALo+FtYwAL56AG7k5jDgaJLm9iBO6GZ+tslOsmCKALZsyLEM8EjIpDowVTAA8mwAVvZQAHTIYCHIEDiV1QBmimDAUAjgpJ70Lj3V1QD0M1XyvUVJzobGIL0wnjAIEB6+1tLkYAYB7gHsyjAQABYgigA2zoX7If7SB-5nF1YIkW07BRXXamN6ZByOKbTGBJKCKcxgLbNB5tKxQG4wABUMAATABuKERWgEnTRWJQADuICoSQhaTBdghOXyhWKpRQFWm-UGw1G5AmUOmsPhiLqjSGrXalk6FGJhO6XIGQxGYDGAuhs3mgKW5hWMDWyDim22IPcnysHzB30F1WFCKRKP86KxuIJ0yJOiAA)

### 💻 Code

```ts
const pipe: <A,B,C>(a: (a: A) => B, b: (b: B) => C) => (a: A) => C = (a, b) => (input) => b(a(input))

type StringRecord = { [x: string]: string }

var one: (record: StringRecord) => number = pipe(
    Object.entries,
    function(x) {
        //  inferred type of x is [string, any][] but should be [string, string][] given input is StringRecord
        return x.length * 2;
    }
);

var two: (record: StringRecord) => number = pipe(
    function(a) {
        return Object.entries(a);
    },
    function(x) {
        //  inferred type of x is [string, string][]
        return x.length * 2;
    }
)
```

### 🙁 Actual behavior

When `Object.entries` is used in the pipeline above, the inference allowed by the `Object.entries` overload for objects containing a single value type is not used, and the inferred type of entries is `[string, any]`. When `Object.entries` is wrapped inside a function expression that is semantically identical, the inference is made correctly.

### 🙂 Expected behavior

The inference should be made in both cases. See inline code comments.

**Comment by RyanCavanaugh** [comment]
The problem here is that `Object.entries` is overloaded, and TS can't do overload resolution on a bare reference during inference, instead defaulting to the last overload.

**Comment by slikts** [comment]
```ts
type Constr = {
  // Commenting out one of the identical overloads fixes the error
  new <A>(a: A[]): Set<A>
  new <A>(a: A[]): Set<A>
}
declare const Constr: Constr
const construct = <A, B>(a: A[], b: new (a: A[]) => B) => new b(a)
// Error: unknown is not assignable to number
const set: Set<number> = construct([1, 2, 3], Constr)
```
[Playground link][1]

Is this the same issue?

[1]: https://www.typescriptlang.org/play?ssl=10&ssc=1&pln=1&pc=1#code/C4TwDgpgBAwg9gOwM7AE5QLxQN4CgpQD0hscAtmRAsAJYIDmUcArsEwtHAGZTAAW0GgBMqtAMYBDADZMAbhFRS4EoUihcaADwhr+0Bajip8UDgHcoAHgCCAPgAUEgFxRrAbQC6AShcBlCMA2tibmVnaOLu7efgFBuAC+uCJiUhKo0GKIKKTIaC7wucaZuVDFKKjMYmxYNgA0UABCDs6unvUARi6hEa3emLaNXv2mEBbtjl64xFAAoqiGqC7MCADWCHBmCFA0autsEkhINPQIEu1S0MBwpsxk7Qq4ZWxIATGBCLf3qANYTxVV9jcAEZ6gAmeoAZg89QK5UmQA
