### ISSUE TITLE
Allow keywords in namespaces

### ISSUE THREAD

**Issue by BenjaminAster** [microsoft/TypeScript#50441]
When a variable or function is declared inside of a namespace, TypeScript doesn't allow names that are valid JavaScript keywords:
```typescript
declare namespace Foo {
	var for: "bar"; // Error: 'for' is not allowed as a variable declaration name.
};
```
---
## Personal concrete use case:
I maintain [type declarations for a lot of new JavaScript stuff](https://www.npmjs.com/package/new-javascript). The [CSS Typed Object Model specification](https://drafts.css-houdini.org/css-typed-om-1/) (which is included in these type declarations) defines the [`CSS.in()` function](https://drafts.css-houdini.org/css-typed-om-1/#dom-css-in) that converts a number into a CSS unit value (inches). TypeScript's default `lib.dom.d.ts` already defines the `CSS` object as a namespace, so I extend that namespace to include the CSS Typed OM functions ([see code](https://github.com/BenjaminAster/TypeScript-types-for-new-JavaScript/blob/6b3a411dffed989ad59300a16e5b88a813bbbb39/css-houdini/typed-om.d.ts#L237)). This works perfectly fine for all functions except for the `CSS.in()` function because `in` is a JavaScript keyword.

**Comment by DanielRosenwasser** [comment]
To support these cases, we started allowing named `export`s in ambient namespaces. They have the ability to rename a local to anything that qualifies as an *IdentifierName* (a.k.a. a property name)

```
declare namespace Foo {
    var _for: string;
    export { _for as for };
}
```

[Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA7KBbEBnADlMCBiA9gfAN4BQ8l8AbrPAPoBmBMAXPOgC4wCWiA5gG4KVEAA9MLTqQbMY8KOnhz4AX2GqyZQgQB0coA)

The caveat is that this statement turns off the magical auto-export anti-feature in namespaces.

```ts
declare namespace Foo {
    function nowInternal(): void;
    export function alwaysExported(): void;

    var _for: string;
    export { _for as for };
}

Foo.for // ✅
Foo.alwaysExported // ✅
Foo.nowInternal // ❌
```

[Playground Link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA7KBbEBnADlMCBiA9gfAN4BQ8l8AZgK6JgAuAlgYkgQO4CSijIMZBAAUASgBc8AG4FmwANwUqIAB6YCMRjXpNW7KBE5QAnugCiajf2BjJMuYqWUpseAH1qGyekYxmiAHNFKnhVdU1Sd08YeCh0Gg14AF9FJLIyQgIAOmj4AHo8+EBQcgyiLIMjUwtw63zCksysxC5efkEDOvhAGXJ0oA)

**Comment by DanielRosenwasser** [comment]
For some context on why this is declined beyond the existing option, it would just be a drastic departure to allow keywords as binding names in these positions but nowhere else in the language, and trying to introduce disambiguation rules is both a lot of scope and fraught with corner cases.

**Comment by BenjaminAster** [comment]
```typescript
declare namespace CSS {
	function _in(value: number): CSSUnitValue;
	export { _in as in };
}
```
does the trick for my use case; thank you. Closing this now.
