### ISSUE TITLE
Type info of arrow function arguments get lost when you parametrize that function

### ISSUE THREAD

**Issue by corno** [microsoft/TypeScript#50443]
# Bug Report

### 🔎 Search Terms

arrow function
type inference
type parameters

see also issue: https://github.com/microsoft/TypeScript/issues/50417

### 🕗 Version & Regression Information

the furthest back the playground allows is 3.3.3; in that version this was already an issue

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bugs that are not bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiBiBXAdgYwCrmgXigCgEMAuKAZ2ACcBLZAcwEopsA+KANwHsqATAbgCh+qDsnJQAtghSoAkuLAk4SNJkhN8BRiygBvKAHp9UADwBaU1GAALaADMCqYJasEn1qqSgEKtROIjITh5QHLaWWGSUNLRQ3BwQnsgcTi5s0MAcUABG0BQJkKhUtlQQ3AA0UABWiGLW0N6+-oFQyAT+UMEBHIi0VvxQA14AdAHcpADqVNZ4AES2HBwz9PwAvoKGSQDulhQg0c7QpG3Qm1NW4Wpg3sfAEBSkRIKgakrSqhCT1u8ACtf+txR1MZ0MxCCRyNQ6FpWJweAJBMJRE5JMpZPJPlYfn8IADFFIVBFcMCKqDNExWHpDCZzC0ONtSIhuNwAgAbEAHC7QUJQACCHU8KAA1ltkP1BgQRsgxhjZvNFss1kA)

### 💻 Code

```ts
type MyFuncType = (a: string) => void;

const myFuncImp: MyFuncType = (a) => { // <-- the fact that this argument is of type string does not have to be respecified, just the argument name is enough
    a.endsWith("foo")
}

//now trying the same with type parameters:

type MyFuncTypeWithTypeParameter = <T>(a: string) => void;


const myFuncImpWithTypeParameter: MyFuncType = <T, >(a) => { // <-- now suddenly the type of a is unknown
    a.endsWith("foo")
}

```

### 🙁 Actual behavior

the type of a is not known

### 🙂 Expected behavior

the type of 'a' is known by the compiler

**Comment by RyanCavanaugh** [comment]
Contextual typing doesn't apply to parameters when another parameter in the same parameter list has a type annotation. Since it never makes sense to have a generic function that doesn't use its type parameter in an argument position, this is effectively a "only matters in code that you should never write in the first place" situation.

**Comment by corno** [comment]
@RyanCavanaugh  I've tried to come up with a minimal example of when this might occur. I'm using 'map' as an example.
I have lots of occurences of these kind of things.
Can you explain what you feel is the issue with this code, why it should never been written in the first place?

[playground](https://www.typescriptlang.org/play?#code/FDAuE8AcFMAIFkCGkYCdYF5YB4AqA+ACkVVUXAC5ZcBtAXQBpYBjRAGzYCNFmBrKwgDd2AV2hVcASkz5YggPYBLACbSMs2nRAB6bQAtoqOLliKAzrBEA7XlfkB3K8GbyrZ0LAC2yNAEYqSCiGmLDEpORMrBzcfGqyAN7AsMksru6woNCekBL0IfRJKSRk4AB0AGbyqACiPHqEQqLQcbCJKe0ZWZClkCJm9cJsYpKFyQC+I+1GoCKoVp3ZwGM6+obGphZmMMyK5YrQykycIh6gBrAkAOYintBWoBYkcNYQMMrOaR7eQagATAE+YJYPAMIjFCIsdhcHi8FptFIuNynLq5Oj5LTtcFlSo1OoNQbDGStUYdTLZHp9AZNSYpCYk6azeZkyBLFauNjgDJ6cywexVXhmD5IryA1AAZgBPxCILB4Uo1HokShMX4oQJ4moLQUKjhJMR6WZqPRJKxFSqtWY9UaQ2aRPhHQW3V6-WtwxJdKm0Bmc0dSyAA)

**Comment by RyanCavanaugh** [comment]
I think those examples are actually pretty instructive as to the problem:
 * It's beyond comprehension to introduce `NT` as a type name on line 5; this is not how scoping works anywhere else in the language. So this can't be how it works. Plus you didn't write a generic function in that position, so it'd be a category error to make a generic function where one wasn't declared
 * On line 13, you've declared a generic function. But you're actually declaring *new* type parameters which might come in with a different order, different count, different meaning, different anything, from the type parameter list in the contextual type. You *happen* to have declared a type argument list with the same names and cardinality, but this isn't a requirement, and there's no way to tell the difference between a type argument list that intends to correlate with the contextual type's and one that doesn't
 * The last example works

**Comment by fatcerberus** [comment]
> On line 13, you've declared a generic function. But you're actually declaring new type parameters which might come in with a different order, different count, different meaning, different anything, from the type parameter list in the contextual type. You happen to have declared a type argument list with the same names and cardinality, but this isn't a requirement, and there's no way to tell the difference between a type argument list that intends to correlate with the contextual type's and one that doesn't

This seems to be the crux of the issue.  It's a catch-22: TS won't infer a type parameter list (case 1), but explicitly specifying the type parameters (case 2) makes new, unrelated bindings.

**Comment by corno** [comment]
> > On line 13, you've declared a generic function. But you're actually declaring new type parameters which might come in with a different order, different count, different meaning, different anything, from the type parameter list in the contextual type. You happen to have declared a type argument list with the same names and cardinality, but this isn't a requirement, and there's no way to tell the difference between a type argument list that intends to correlate with the contextual type's and one that doesn't
> 
> This seems to be the crux of the issue. It's a catch-22: TS won't contextually infer a type parameter list (case 1), but explicitly specifying the type parameters (case 2) makes new, unrelated bindings.

If I understand you correctly, this is indeed the problem I'm facing.

Here is an example that is closer to my actual code base. 
[playground](https://www.typescriptlang.org/play?#code/FAFwngDgpgBAKgJylAPHAfDAvMGeYA+MA2gEQDGA9gLYSUDOAliFKQDTxKobEC6vufETIAbKAEMAZjACC7eAOChIsABLiAdgBMxiZNhhp0AChBcAXJ2RGOSOghCXjAN3EiArlEtwOVdxpYESw13agAjKAQASmxMZ0pGLRisOIStJQB6DNVKAHcYAEkYAAtxZ1gQShhchGYK4thGWjFqKADxEEZKDUEqDXoQEs0dKD0vGHVtXS4DNDYTM2RvLhsYO0oHJ1cPcZ8YPwDI4NCI6NiYeMTkzABvGCyUAFpHkrzCofKYSuralhhmYBZPoDIZTUYWCbDab6LCGHwLGb4JEwWxQeyDZGYrHYnEwa4wO54J4vYpvIq5SjuERaGAiRgAawqVQiMHEYTEXyqNTq-xAgjwYkGB0CBgADPyYJJ-OROt19pSAjJtJMRmNTBCxkYYjcJUjGNJ1chiKLeNgsLDSGIpLJSNrdVjhZEYABqWEARntmPWDkNUGIbt4vgVgSinpgAF8YFARPRYDrcXhFn6AwA6SQbACi4nIxWMxmjUFaAXx8YTSOFSq0KuhUHzLTaIFDZfDTax4Yl7fLwcr1fByF9ofbQA)

I'm writing inner function because there is a recursive structure that needs to be visited. I want the inner function to use the outer function's parameter 'report' and I don't want to copy that parameter to the inner function.
This means that I have to be able to refer to the generic type 'T'.
If there is something intrinsically wrong with this approach, I would really like to hear that.

**Comment by corno** [comment]
I've waited a couple of months to reply because I wanted to be absolutely sure that I was not writing anti-patterns. And by now I am sure; The playground that I shared on august 28 still is a good representation of the problem I'm experiencing. It's of course not a show stopper. Just an inconvenience in a language that I feel is almost devoid of them.
