### ISSUE TITLE
Rewrite TSServer Crawler/Fuzzer

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#50456]
We have a (currently) private fuzzer/crawler which simply opens projects on GitHub, runs some language server operations on a project, and finds crashes. This helps pinpoint stability issues in TypeScript and the server so that we can improve reliability.

It has helped catch many issues over the years, but we believe that there are some opportunities to improve it:

1. Now that we have a better idea of the primary functionality, we would benefit from a rewrite - possibly where we can leverage [other infrastructure](https://github.com/microsoft/typescript-error-deltas)
2. The crawler continues to ping about the same issue over and over again. This is okay, and helpful for knowing what issues we've continued to encounter, but *maybe* a better approach is to have reports of new issues that have been introduced that *don't* repro in the last stable version of the language service (similar to the new errors detector we run weekly/on-demand)

**Comment by amcasey** [comment]
The language service exerciser now lives in https://github.com/microsoft/typescript-error-deltas and produces bugs like https://github.com/microsoft/TypeScript/issues/50764.  It can be invoked on PRs with `@typescript-bot user test tsserver` or `@typescript-bot test tsserver top100`.  There will be additional refinements, but it's usable and useful now.
