### ISSUE TITLE
Default function parameter type inferred inaccurately with generics constraint

### ISSUE THREAD

**Issue by ryym** [microsoft/TypeScript#50461]
# Bug Report

### 🔎 Search Terms

Combination of them:

- default parameter / optional parameter
- generic / generics / constraint / generic constraint

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about function parameters.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4&ssl=14&ssc=1&pln=14&pc=30#code/GYVwdgxgLglg9mABDAJgRgDwDEB8AKYALkSwEpitEBvAKEXsQCcBTKERpYAbhoF8aaUAJ4AHZogCCYIVnDR4SALyI8AOnUBDRgHMAzsQ3SA2gF1SiRTkSGhPUJFgJkKAEzZEzAB5RmYFLslpWQcFfCISchJqOgYWNg5Ebj4BAHoUxLRiPDAAfmIwEABbACNmRnNLRAKSspoIBF0oDItnNDxslrQKqzBSHho0xJcs3INpbutpOoam4BcW1Bd2pUQuix6+oA)

### 💻 Code

```ts
function id1<F>(f: F): F {
    return f;
}

type AnyFunction = (...args: any[]) => any;
function id2<F extends AnyFunction>(f: F): F {
    return f;
}

// f1: (n?: number) => number
const f1 = id1((n = 1) => n);

// f2: (n?: any) => any
const f2 = id2((n = 1) => n);
```

### 🙁 Actual behavior

The default function parameters type does not inferred accurately when a generics constraint exists.

### 🙂 Expected behavior

The inferred default function parameters type is consistent regardless of generics constraints.

**Comment by RyanCavanaugh** [comment]
Contextual typing takes precedence over parameter defaults, otherwise there's a compile error (or runtime crash) here:
```ts
type SomeFunction = (...args: (string | number)[]) => any;
function id2<F extends SomeFunction>(f: F): F {
    // Legal call    
    f("");
    return f;
}

// Alleged: This should be OK with n: string
// Reality: crashes at runtime, so this needs to error
const f2 = id2((n = 1) => n.toFixed());
```

**Comment by ryym** [comment]
I understood. Thank you for your reply with sample code!
