### ISSUE TITLE
Cannot be used to index type error for generic conditional type

### ISSUE THREAD

**Issue by pkudryashov** [microsoft/TypeScript#50465]
# Bug Report

### 🔎 Search Terms

Generic conditional type index

### 🕗 Version & Regression Information

- This is a regression
- This changed between versions 4.7.4 and 4.8.2

### ⏯ Playground Link

```ts
type Column<T = unknown> = (keyof T extends never ? { id?: number | string } : { id: T }) & {
    title?: string;
}

// no error if `key: keyof Column`
function getColumnProperty<T>(column: Column<T>, key: keyof Column<T>) {
    return column[key];
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// no error if `key: keyof Column`
function getColumnProperty(column, key) {
    return column[key];
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAwg9gGwK4FsB2AeAKlAvFJNAazTgHc0A+PKACiIhDgDMocIAPYCNAEwGcoaCADcIAJygB+KAG8oAS15SAXENQAjCVAA+UfsHEK0AcygBfKGvlK1OcwEooAMjkBYAFBRvUYAuAIEKr6hsYmANye5p6eAPSxQnBQEuJwkgqsAAYMIGo5LLCIqGiZnsyEAMZ+cGhQJhDA8MjoAAqpkOKg2JS0FUXoak3F3QA0UDl5jAVD6N1Osp4+UOINSOK1fc1oANo5ALqRHuZAA)
    

### 🙁 Actual behavior

Error:" Type '"title" | keyof (keyof T extends never ? { id?: string | number | undefined; } : { id: T; })' cannot be used to index type '({ id?: string | number | undefined; } | { id: T; }) & { title?: string | undefined; }'.

### 🙂 Expected behavior

No error

**Comment by RyanCavanaugh** [comment]
Bisected to #49119

**Comment by RyanCavanaugh** [comment]
Let's track at the simpler repro at #50462
