### ISSUE TITLE
`private` class property is unprotected if key is numeric

### ISSUE THREAD

**Issue by pushkine** [microsoft/TypeScript#50485]
# Bug Report

### 🕗 Version & Regression Information

ts stable & nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?suppressImplicitAnyIndexErrors=false&exactOptionalPropertyTypes=false&noPropertyAccessFromIndexSignature=false#code/MYGwhgzhAEBiD29oG8BQBIADgJwJYDcwAXAU2mxLABN4A7EAT3IEYBmVgdmgF5o3OA3BhwFiZCtTqM+7Lr34chAX1SpgdCEWgAzRD2i0SAdziIAFAEohq3fAB02BftQB6F9GgA9b949+-AMJgtLTwWpAQuADmtNBESADkjrIJ0ABGJMBgAK4QZLhauDBg5JRUALRSTDjwmCTYRAx2qB62Dk4A1HxCbv4+vv7QAArYtfWN0EkKqUXQIoSk0MFU0FVLwMAkULhpIGRGBQAWuLGgEZMI8AnNqLYA2goAus69Xj6D-kEhYUvbMXGJabpTI5PLQArg4qlaiVejVUZ1BpNFo6RAPWTPLrMHruPz9D7QMwAOSQ9VG2AsQA)
    
### 💻 Code

```ts
class Foo {
	private readonly r1337 = 1337;
	private readonly 1337 = 1337;
}

const foo = new Foo();

foo.r1337 = 
  foo.r1337 + 1;

foo[1337] = 
  foo[1337] + 1;
```

### 🙁 Actual behavior

```ts
foo.r1337 = 
//  ^^^^^        ERROR: Cannot assign to 'r1337' because it is a read-only property.
  foo.r1337 + 1;
//    ^^^^^      ERROR: Property 'r1337' is private and only accessible within class 'Foo'.

foo[1337] = 
//  ^^^^         ERROR: Cannot assign to  '1337' because it is a read-only property.
  foo[1337] + 1;
//    ^^^^       (No error)
```
Writing  `foo[1337]` is denied because it is a `readonly` class property.
Reading `foo[1337]` is allowed although it is a `private` class property.

### 🙂 Expected behavior

```ts
foo[1337] = 
//  ^^^^         Cannot assign to '1337' because it is a read-only property.
  foo[1337] + 1;
//    ^^^^       ERROR: Property  '1337' is private and only accessible within class 'Foo'.
```

Reading `foo[1337]` throws an error because it is a private class property.

**Comment by whzx5byb** [comment]
This is an intended behavior. See https://github.com/microsoft/TypeScript/issues/19335.

**Comment by pushkine** [comment]
> This is an intended behavior. See #19335.

I am aware of how the indexed access notation works, this issue is specifically about numeric properties.

I believe that the computed property notation is an escape hatch. It is not intended to forbid class properties from using the privacy feature when their key is numeric. 

A numeric property can only be accessed using the bracket notation. I am not opting-in to the indexed access, I'm not accessing it using `foo[i]` or `foo["1337"]` . I declared it using a bracket-less notation `private 1337 = 1337;`, not `private "1337"` or `private [1337]`. I did all that in a class without indexed properties and I tried every using related compiler option under the sun. Still that property won't be private. I do not think that Typescript intends to forbid number keys from being private.

**Comment by whzx5byb** [comment]
> A numeric property can only be accessed using the bracket notation.

Here is the limitation: Any property access inside square brackets will ignore `protected` or `private` modifiers. The compiler doesn't distinguish between `foo[i]` and `foo["1337"]` and `foo[1337]`.

**Comment by pushkine** [comment]
The fact that Typescript allows making that property private, but actually never enforces its privacy is a bug. 

It should either not allow privacy modifiers on numeric properties because they enforce privacy or it should enforce privacy when they're accessed with the bracket notation.

**Comment by RyanCavanaugh** [comment]
> It should either not allow privacy modifiers on numeric properties because they're defacto not supported or it should enforce privacy when accessing that property.

Numeric names are certainly very rare and breaking someone's program on purpose to fix the perceived inconsistency doesn't seem like a great trade-off here.

**Comment by parzhitsky** [comment]
As came up in https://github.com/microsoft/TypeScript/issues/60974#issuecomment-2593063109, `symbol` keys also suffer from the same thing. My intuition is that they are much more widely used than numeric keys. Do we have the same policy for them as well?
