### ISSUE TITLE
Isssue generating declaration files with object containing keywords as property

### ISSUE THREAD

**Issue by Mister-Hope** [microsoft/TypeScript#50483]
TS playground does not have 4.8.2 yet, but this issue can happends in 4.8 beta:

https://www.typescriptlang.org/play?moduleResolution=99&target=99&jsx=0&module=199&ts=4.8.0-beta#code/C4TwDgpgBAMg9gYwIYBsIBEnCVAvFAJQgTgCcATAHgGdhSBLAOwHMAaKRiANwlID4AUKEhQAwnEY9SweMjTjGAM3rNKAFSgQAHsAiNy1WIlQYsOfLJOZsfPIWJkqAqFFoMWrZ1DUC+AbiFwaEt5CWVVDW1dfUMQ02w7OOskW3wiEgoaOiY2KAAFJGl6VHU+fwEBbTAyYCgmXVJFJARoAHEIGWM0agB5MGB6CWp1TR09AyM5eJSoAG8vFyQwMAAuKABXRgBrRjgAd0YAlxdyCCb1lGA1hSlOqYVw0qPjkiUVAH41uIeVUqgAHw2+jOTAg5GeLkYSAAthBPq5siwAgBfCpVGpQV60KDMDpxQz4EZRcaxLrTPgACnmxygSzAnhpUNhDOOp3OlzWbKQFzuJmoPzYC0xYRUa3W1F4+IFdlmyM8yLW7V53T6AyGpQAlNcJLdviKIqlbNTjqQOutSIwoFyeVL9SiAkA

The DTS result is wrong because default is a keyword:

```ts
export declare const getLocales: <T extends LocaleData>({ app, name, default, config, }: GetLocalesOptions<T>) => ConvertLocaleConfig<T>;
```

Meanwhile older ts versions work well:

https://www.typescriptlang.org/play?moduleResolution=99&target=99&jsx=0&module=199&ts=4.7.4#code/C4TwDgpgBAMg9gYwIYBsIBEnCVAvFAJQgTgCcATAHgGdhSBLAOwHMAaKRiANwlID4AUKEhQAwnEY9SweMjTjGAM3rNKAFSgQAHsAiNy1WIlQYsOfLJOZsfPIWJkqAqFFoMWrZ1DUC+AbiFwaEt5CWVVDW1dfUMQ02w7OOskW3wiEgoaOiY2KAAFJGl6VHU+fwEBbTAyYCgmXVJFJARoAHEIGWM0agB5MGB6CWp1TR09AyM5eJSoAG8vFyQwMAAuKABXRgBrRjgAd0YAlxdyCCb1lGA1hSlOqYVw0qPjkiUVAH41uIeVUqgAHw2+jOTAg5GeLkYSAAthBPq5siwAgBfCpVGpQV60KDMDpxQz4EZRcaxLrTPgACnmxygSzAnhpUNhDOOp3OlzWbKQFzuJmoPzYC0xYRUa3W1F4+IFdlmyM8yLW7V53T6AyGpQAlNcJLdviKIqlbNTjqQOutSIwoFyeVL9SiAkA

```ts
export declare const getLocales: <T extends LocaleData>({ app, name, default: defaultLocalesConfig, config: userLocalesConfig, }: GetLocalesOptions<T>) => ConvertLocaleConfig<T>;
```

I think this is a critial bug and should be fixed in 4.8.3 asap

---

Also I was curious:

1. why could this happends? Is related test cases missing?  Maybe the team should check test cases and add some releated test into it.
2. When will you update your website? Hours passes after releasing 4.8 to stable, maybe the team can update ts playground faster, and that DOES help developers.

**Comment by Mister-Hope** [comment]
@MartinJohns So why thumbs down.

So you think this is a completed snippet? Or it's normal for a project with 83.7k stars and 676 contributors should keep the website outdated days after new version? I do open source too, 1 is probably ok if no one everr comes out the idea to add related test. But I don't think it's ok for 2.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/33315834/187074464-4e3b1989-233c-4d4c-a2b0-ad2a86b5c29e.png">

**Comment by MartinJohns** [comment]
I have the tendency to give the down thumb to issues ignoring the issue templates. Weird flex, I know.

**Comment by jakebailey** [comment]
I did a bisect, and #41044 did change this, yes.

**Comment by RyanCavanaugh** [comment]
I agree this is a 4.8 patch candidate. cc @andrewbranch
