### ISSUE TITLE
Strange behavior of function overloading and union type

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#50488]
# Bug Report

Strange behavior of function overloading and union type

### 🔎 Search Terms

function overloading union type

### 🕗 Version & Regression Information

- This changed between versions 3.5 (good) and 3.6 (bad)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBAbzgYQIYDsBuqDOAaFDbHAJQFN0ATMqYdAc2QnRjIA8YAmAETlzgByEamiy5yVGnUbNWHHnAC+cAGZQIIOAHIAxkVxaAUIYA2ZeDphsAXITGkK1WgyYt2XXgB9BwsqOISTtKuch5w3ugAriYmcAC8cFExxiqR6JbAzHCsODAAFHr2tgASACoAsgAy-rgAomYgFPDeNTgAlIiGcN1wlmzxvfo4AHT05iHueVqclFpthoqGqekwmejZZLmcBUMlFdVD9WSNLOF2xB0IXT3AKnA79nB0uRg6ZBB3ZVWtRycwl9cej0+gNCsRRuNZJNprN5kDlGQTDgyJ0gUCQQkwbgITAJhwpjM5oClAsgA)

### 💻 Code

```ts
import { Canvas, CanvasRenderingContext2D as NodeCanvasRenderingContext2D } from 'canvas'

let ctx: CanvasRenderingContext2D | NodeCanvasRenderingContext2D | null = null

function test(canvas: HTMLCanvasElement | Canvas) {
    ctx = canvas.getContext('2d')
    // error??
}
function test2(canvas: HTMLCanvasElement | Canvas) {
    // works!!
    if (canvas instanceof HTMLCanvasElement) {
        ctx = canvas.getContext('2d')
    } else {
        ctx = canvas.getContext('2d')
    }
}
```

### 🙁 Actual behavior

```
Type 'NodeCanvasRenderingContext2D | RenderingContext | null' is not assignable to type 'CanvasRenderingContext2D | NodeCanvasRenderingContext2D | null'.
```

### 🙂 Expected behavior

No error

**Comment by RyanCavanaugh** [comment]
Function type merging produces a single signature in this case, and that single signature doesn't keep around enough information.

The only way to process this "correctly" would be combinatorially explosive, so that doesn't happen.

**Comment by Jack-Works** [comment]
but why does it work on TS 3.5? 🤔
