### ISSUE TITLE
Union type of multiple interfaces must treat properties that exists only in some interfaces as optional (`| undefined`), not errors

### ISSUE THREAD

**Issue by tats-u** [microsoft/TypeScript#50495]
# Bug Report

JavaScript allows access to properties that are not present in objects (returns `undefined`). If the type of the object consists of an union of multiple interfaces and the property exists in at least one of the candidates, the access must be allowed and returns an optional type.

The current version treat the access as an error, which is so much annoying. Of course, TS can treat the access as an error if none of the candidates has the property.

```ts
type Foo = {bar: "aaa", baz: string} | {bar: "bbb"}
const test: Foo = {bar: "aaa", baz: "corge"}

// must be allowed (string | undefined)
console.log(test.baz)
// can be an error
console.log(test.qux)
```

### 🔎 Search Terms

undefined union

### 🕗 Version & Regression Information

See below

### ⏯ Playground Link

- [v4.7.4](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAYg9nKBeKBvAUFLUBmCBcUARAEYCGATkQDSbYCOArgB6EDOwFAlgHYDm6AL5QAPmjpY8cQqTIAvGkPTocjHgGNgXOD1xr1ACkp9C8OAEp2nXn1FQ1AEwg5eEB+OxQKEYIwq7jADomZgBuJXR1HTY4ABsIQLI2NggKYANVDQNUKRlyKmooEJkmFiJBc2QkFCJS5hpiAHkACygAWxAoPjg2ZqJzcKieGPjE5NT0zMMcgmJyBQqqlEdnVwdCojhWjq6EBx4IZP7woA)
- [v4.8.0-beta](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAYg9nKBeKBvAUFLUBmCBcUARAEYCGATkQDSbYCOArgB6EDOwFAlgHYDm6AL5QAPmjpY8cQqTIAvGkPTocjHgGNgXOD1xr1ACkp9C8OAEp2nXn1FQ1AEwg5eEB+OxQKEYIwq7jADomZgBuJXR1HTY4ABsIQLI2NggKYANVDQNUKRlyKmooEJkmFiJBc2QkFCJS5hpiAHkACygAWxAoPjg2ZqJzcKieGPjE5NT0zMMcgmJyBQqqlEdnVwdCojhWjq6EBx4IZP7woA)
- [v4.0.5](https://www.typescriptlang.org/play?ts=4.0.5#code/C4TwDgpgBAYg9nKBeKBvAUFLUBmCBcUARAEYCGATkQDSbYCOArgB6EDOwFAlgHYDm6AL5QAPmjpY8cQqTIAvGkPTocjHgGNgXOD1xr1ACkp9C8OAEp2nXn1FQ1AEwg5eEB+OxQKEYIwq7jADomZgBuJXR1HTY4ABsIQLI2NggKYANVDQNUKRlyKmooEJkmFiJBc2QkFCJS5hpiAHkACygAWxAoPjg2ZqJzcKieGPjE5NT0zMMcgmJyBQqqlEdnVwdCojhWjq6EBx4IZP7woA)

### 💻 Code

```ts
type Foo = {
    foo: "bar",
    qux: string
} | {
    foo: "baz",
}

function func(arg: Foo): string | undefined {
    return arg.qux;
}

console.assert(func({foo: "bar", qux: "quux"}) === "quux", "Oh my gosh");
console.assert(func({foo: "baz"}) === undefined, "oh my goodness");
```

### 🙁 Actual behavior

Line 9: Property 'qux' does not exist on type 'Foo'. Property 'qux' does not exist on type '{ foo: "baz"; }'.

### 🙂 Expected behavior

No errors

**Comment by MartinJohns** [comment]
> JavaScript allows access to properties that are not present in objects (returns `undefined`).

Just because the property is not part of the type definition doesn't mean it's `undefined`.

Your suggestion would be fairly unsafe. It's also been proposed several times already, but I don't have the issue at hand.

**Comment by fatcerberus** [comment]
This has to be an error because:
```ts
type Foo = {bar: "aaa", baz: string} | {bar: "bbb"}
const bar = { bar: "bbb", baz: 42 };
const foo: Foo = bar;
console.log(foo.baz);  // logs 42 (number), which is not a 'string | undefined'
```

**Comment by MartinJohns** [comment]
Found a relevant issue: #49933

**Comment by tats-u** [comment]
@fatcerberus Error in line 3: https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAYg9nKBeKBvARgQwE4C4oBEmxBANFFgF74DOw2AlgHYDmAvlAD5pZ6HoCCbAFABjOEzoUcyNNL4EB6MtOpQALACYobANxiJUgGYJ88RCl66gA
Your code does not satisfy the prerequisite of my issue.

**Comment by fatcerberus** [comment]
@tats-u Add an `as const` to the end of the assignment on line 3 and you'll see the issue.

**Comment by tats-u** [comment]
@fatcerberus What you say is correct... I wonder where errors have gone.

https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAYg9nKBeKBvARgQwE4C4oBEmxBANFFgF74DOw2AlgHYDmAvlAD5pZ6HoCCbAFABjOEzoUcyNNL4EB6MtOpQALACYoHTDSjjJwANxiJUgGYJ88RCl7GgA

Is it true that I should add `arg.foo ==="bar" ?` and `: undefined` after `return`?

**Comment by fatcerberus** [comment]
> I wonder where errors have gone.

I don't know what the solution in your particular case is, but `{ bar: "bbb", b: 42 }` is assignable to `{ bar: "bbb" }`, and that's true for object types in general (TS checks for excess properties but only on direct assignment of object literals).  It is by design, and you'll need to keep that in mind when writing type checks.

**Comment by tats-u** [comment]
I understood TS interfaces (or objects) allows extra properties.
I will replace `{ bar: "bbb" }` with `{ bar: "bbb", b?: undefined }`. This seems to work fine when trying to access the property `b` of objects of `Foo`.

**Comment by MartinJohns** [comment]
> I will replace `{ bar: "bbb" }` with `{ bar: "bbb", b?: undefined }`. This seems to work fine when trying to access the property `b` of objects of `Foo`.

Just be aware that this **can** be unsound as well.

```typescript
type Foo = {bar: "aaa", baz: string} | {bar: "bbb", baz?: undefined }
const bar = { bar: "bbb", baz: 42 } as const;
const temp: { bar: "bbb" } = bar
const foo: Foo = temp as Foo;

console.log(typeof foo.baz) // type is string | undefined, will log number
```

**Comment by tats-u** [comment]
Thank you for your advice, but you do not worry about it because I will not do such a dangerous thing like treading on a lion's tail.

**Comment by fatcerberus** [comment]
Eh… YOLO \*steps on lion’s tail\*

**Comment by 90dy** [comment]
This is DX issue
