### ISSUE TITLE
Allow simple expressions as type

### ISSUE THREAD

**Issue by rentalhost** [microsoft/TypeScript#50499]
# Suggestion

The `type` support is absolutely amazing. But I was thinking about the possibility of being able to define types through simple expressions, which do not have complex or runtimed dependencies.

## 🔍 Search Terms

type expression function

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When trying to create a slightly more complex `type`, for example, containing a datetime `HH:MM:SS`, for example, we can define it as follows:

```typescript
type HH = '00' | '01' | '02' | '...' | '23';
type MM = '00' | '01' | '02' | '...' | '59';
type SS = MM;
```

We can do various optimizations, for example typefy `MM` over `HH`:

```typescript
type HH = '00' | '01' | '02' | '...' | '23';
type MM = HH | '24' | '25' | '26' | '...' | '59';
type SS = MM;
```

However, the size of the generated string will still be large.

Other ways may end up being "more compact" (?), but generating greater reading complexity (worse maintainability, [eg1](https://stackoverflow.com/a/68526558/755393), [eg2](https://stackoverflow.com/a/67511209/755393), [eg3](https://stackoverflow.com/a/70937016/755393)):

```typescript
type D1 = 0|1;
type D3 = D1|2|3;
type D5 = D3|4|5;
type D9 = D5|6|7|8|9;

type HH = `${D9}` | `${D1}${D9}` | `2${D3}`;
type MM = `${D5}${D9}`;
type SS = MM;
```

My suggestion would be to allow `type` to be defined through simple expression, using Javascript's own resources. For example:

```typescript
type HH = Array.from({ length: 23 }, (x, i) => i.toString().padStart(2, '0'))
type MM = Array.from({ length: 59 }, (x, i) => i.toString().padStart(2, '0'))
```

Or even more optimized:

```typescript
const generate = length => Array.from({ length }, (x, i) => i.toString().padStart(2, '0'));

type HH = generate(23)
type MM = generate(59)
```

**Note:** this should not allow the `type` to be dynamic with runtime dependencies, only static dependencies if needed.

Other use cases would be to generate a list of letters:

```typescript
type LETTERS = 'a' | 'b' | 'c' | 'd' | 'e' | '...' | 'z';
```

Becomes:

```typescript
type LETTERS = Array.from({ length: 26 }, (x, i) => String.fromCharCode(i + 97))
```

I believe static dependencies can work well too. For example, a `.env` property:

```typescript
// .env: CODES_SUPPORTED: 200, 201, 202, 203, 204, ..., 300, 301, 302, ... 400, 401, 402, ... 500, 501, 502...
type CodesSupported = import.meta.env.CODES_SUPPORTED.split(',')
```

**Comment by RyanCavanaugh** [comment]
We can't run arbitrary JS as part of typechecking (security nightmare), and providing a mini-JS interpreter in TS isn't a great alternative compared to adding more type system expressiveness through regular means.

**Comment by rentalhost** [comment]
@RyanCavanaugh I had imagined Typescript to do this natively, something like a "javascript running in the backend" for error parsing and all that, so it would be possible to bring that to this feature also.

Well, it's really a little disappointing to think that we can't take a step in that direction. Perhaps a "meta language" (something like `Uppercase` and `Lowercase`) for generating types (really would be quite complex, but at least if there was this possibility, it would be something interesting to think about).

```typescript
type HH = Map(Range(0, 23), PadStart(this, '0', 2))
type MM = Map(Range(0, 59), PadStart(this, '0', 2))

type LETTERS = Map(Range(0, 26), Char(this + 97))
```

Actually, it would be really cool if we could create our own type converters (like Uppercase, Lowercase), but that would go back to the security nightmare problem.

**Comment by castarco** [comment]
> We can't run arbitrary JS as part of typechecking (security nightmare), and providing a mini-JS interpreter in TS isn't a great alternative compared to adding more type system expressiveness through regular means.

I'm not in favor of this specific proposal, as it feels too convoluted for too little gain, but leaving this aside:

Couldn't it be possible to detect at the binding stage (prior to type checking) if a function is "pure" (no side effects, it only depends on its input parameters)?

Similarly, although for completely different reasons, Rust has been increasing the subset of code that can be written in a `const` context (`const` as in Rust, not as in TypeScript). I can imagine a starting point where only very basic operations are accepted in this subset (for example, arithmetic and/or string operations; not even user-level function calls).
