### ISSUE TITLE
infer type from first assignment

### ISSUE THREAD

**Issue by timonkrebs** [microsoft/TypeScript#50490]
# Suggestion
## 🔍 Search Terms
inference of type in class property from constructor assignment.
inference of type in variable from first assignment in scope.

## ✅ Viability Checklist
My suggestion meets these guidelines:

* ✅ This wouldn't be a breaking change in existing TypeScript/JavaScript code
* ✅ This wouldn't change the runtime behavior of existing JavaScript code
* ✅ This could be implemented without emitting different JS based on the types of the expressions
* ✅ This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* ✅ This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
It would be extremely convenient if a property could infer its type from the first assignment (in scope or constructor). A possible syntax for this could be **infer** as type declaration:

``` typescript
class AppComponent {
  // type is:
  // profileForm: FormGroup<{
  //     firstName: FormControl<string>;
  //     lastName: FormControl<string>;
  // }>
  protected profileForm: infer;

  constructor(private fb: FormBuilder) {
    this.profileForm = this.fb.group({
      firstName: [''],
      lastName: [''],
    });
  }
}
```

## 📃 Motivating Example
Currently, type inference is only possible from direct assignment where the property/variable is declared.

``` typescript
class AppComponent {
  protected masterForm = this.fb.group({
      titel: [''],
      description: [''],
      .
      .
      .
      sharedField: [this.sharedField]
    });

  protected profileForm = this.fb.group({
      firstName: [''],
      lastName: [''],
      .
      .
      .
      sharedField: [this.sharedField]
    });

  private sharedField = 'shared initial value';

  constructor(private fb: FormBuilder) {  }
}
```

Inference on first assignment would allow for much more control and structure.
``` typescript
class AppComponent {
  protected masterForm: infer;
  protected profileForm: infer;

  constructor(private fb: FormBuilder) { 
    const sharedField = 'shared initial value';
    this.masterForm = this.fb.group({
      titel: [''],
      description: [''],
      .
      .
      .
      sharedField: [sharedField]
    }); }

    this.profileForm = this.fb.group({
      firstName: [''],
      lastName: [''],
      .
      .
      .
      sharedField: [sharedField]
    });
  }
}
```

https://stackblitz.com/edit/angular-ivy-ildwnj?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

## 💻 Use Cases

- Angular 14 Strictly Typed Reactive Forms. https://github.com/angular/angular/discussions/44513
- Other complex initialization logic.

**Comment by whzx5byb** [comment]
It is possible to infer member type from constructor [since 4.0](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#class-property-inference).

**Comment by timonkrebs** [comment]
I think it would still be convenient to be able to use this feature with noImplicitAny turned of.

**Comment by RyanCavanaugh** [comment]
This has been the behavior for a pretty long time without other requests for this feature, so I don't think this is going to be a priority for us any time soon.
