### ISSUE TITLE
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree

### ISSUE THREAD

**Issue by dhianica** [microsoft/TypeScript#50503]
Hey, i get this warning after updated my typescript version from 4.7.4 to 4.8.2.
Maybe is not effect for my code, but this warning has a bad look for me.

Can you help me for hide this warning, please?

this is my package.json
![image](https://user-images.githubusercontent.com/21213646/187120102-606a723b-021b-4579-94a4-6df43833f2ad.png)

and this a warning
![image](https://user-images.githubusercontent.com/21213646/187120054-7ef5d9d0-e558-4629-a4a9-3cca3de30eee.png)

**Comment by fatcerberus** [comment]
This is not something TypeScript can help with.  You should report this to the developers of typescript-estree.

**Comment by dhianica** [comment]
> This is not something TypeScript can help with. You should report this to the developers of typescript-estree.

Oh okay. Thanks

**Comment by MartinJohns** [comment]
You should **not** report this to the developers of typescript-estree, because there's nothing to report. They support specific TypeScript versions with each release, and you switched to a TypeScript version that is not supported by your typescript-estree version.

You should just update typescript-estree as well.

**Comment by fatcerberus** [comment]
I suppose it’s possible that they haven’t gotten around to supporting 4.8 at all yet, but that’s a good point.

**Comment by dhianica** [comment]
@MartinJohns Yes, I wont report this.  I just waiting update from the developers of typescript-estree

**Comment by dhianica** [comment]
Thanks all, and now the developers of typescript-estree has updated and the warning has been hide
