### ISSUE TITLE
TS 4.8.2 vs Eslint (no-unused-vars bug)

### ISSUE THREAD

**Issue by jonit-dev** [microsoft/TypeScript#50500]
# Bug Report

Hey there!

After updating my typescript from 4.7.4 to 4.8.2 some eslint issues started to pop-up, regarding the "no-unused-vars" rule.

![image](https://user-images.githubusercontent.com/30300459/187105797-349278b7-b1fd-4628-996f-e82068c2c6fd.png)

Note that it also detects the "provide" import as unused, but its being used as a decorator a couple of lines later.

### 🔎 Search Terms

ts 4.8.2 eslint

### 🕗 Version & Regression Information

Versions that came after 4.7.4
 
- This changed between versions 4.7.4 and 4.8.2

### 💻 Code

For a better, context, this is my:

- eslintrc.json

```
{
  "env": {
    "es2021": true,
    "es6": true,
    "node": true,
    "jest": true
  },
  "extends": ["standard", "plugin:promise/recommended"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module"
  },

  "plugins": ["@typescript-eslint", "unused-imports", "promise"],
  "rules": {
    "semi": ["warn", "always"],
    "quotes": ["warn", "double", { "avoidEscape": true }],
    "comma-dangle": "off",
    "no-trailing-spaces": "off",
    "no-multiple-empty-lines": "off",
    "no-unused-expressions": "off",
    "padded-blocks": "off",
    "keyword-spacing": "off",
    "camelcase": "off",
    "require-await": "error",
    "no-case-declarations": "off",
    "object-curly-spacing": "off",
    "space-before-function-paren": "off",
    "no-useless-constructor": "off",
    "@typescript-eslint/explicit-function-return-type": "error",
    "eslint-no-use-before-defining": "off",
    "no-use-before-define": "off",
    "no-var": "error",
    "no-unused-vars": "warn",
    "@typescript-eslint/naming-convention": [
      "error",
      {
        "selector": "interface",
        "format": ["PascalCase"],
        "custom": {
          "regex": "^I[A-Z]",
          "match": true
        }
      }
    ],
    "indent": "off",
    "no-new": "off"
  }
}
```

package.json
```
 "eslint": "^7.13.0",
    "eslint-config-standard": "^16.0.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-unused-imports": "^1.0.1",
    ...
    ...
  "@typescript-eslint/eslint-plugin": "^5.31.0",
    "@typescript-eslint/parser": "^5.31.0",

    ```

**Comment by fatcerberus** [comment]
This sounds like an eslint issue, not a TS one?

**Comment by afc163** [comment]
It came out after 4.8.x

**Comment by etoah** [comment]
same issue

**Comment by jonit-dev** [comment]
> trace [typescript-eslint/typescript-eslint#5551](https://github.com/typescript-eslint/typescript-eslint/pull/5551)

I'll try to patch it here!

**Comment by Sayakie** [comment]
Those who have the same issue after would be updated...

1. Remove your node_modules and lock file(`package-lock.json`, `yarn.lock`, or `pnpm-lock.yaml` whatever) and then clean install.
  I tried: `pnpm install -f`
2. Restart your IDE.
3. Profit!
