### ISSUE TITLE
Cannot type-narrow function without return as generic function in 4.8

### ISSUE THREAD

**Issue by oBusk** [microsoft/TypeScript#50512]
# Bug Report

### 🔎 Search Terms

`4.8` `assert function` `Function` `any void unknown`

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.8.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/GYVwdgxgLglg9mABDAzgMXNeYAUA3AQwBsQBTALkXAGsw4B3MASksJNORURwDo+CATgHMUlAmACeAbQC6TRAF4AfInETEAbwBQiXYgGkoIAUigSADqTjBEbMooULEAclCRYCZwG4tAXy1ablgIiFCkKFAAKhbhODp6BJQRAjBgQogAPtw4EpRgIAC2AEakAvLKiMmpQkwANPG6RXmFJQKZ2bmI+cWltYgAXklQKWnlKnhwMAAmdVry2g3INjioGO7YOARM84t6iAD0+4gABgTHlQAWcCBEU4glqigopWF3BFzHOc09ZYoqVWljgE9ntDogAAJQFAAWlIAA9LNBYQIBHA2gB1DgoK43O4XAh4DjvZ4CV6hfFQVScKlBDxgXZ6CAICKIAD6QxG6ScRR8DN0YMhMPhiKgyNRGNIzgMiHMxOq5I49FRaS6LVKiGsqmEhVIYChfNUOCYPj2vkQpCIz00BoFUNhCNISNK4sQmMu11uiHxhMeJLJUApVNQXTglIIiFp2ANBCNJr0-kWMGWq0wdJwRW21pBejBxyK52xHruhdx9yJTxepDeHy+qp+fUGlWG1TGtkmUyBNqOgvtIrFaNdWJxnu95b9VfJBEpRWp4cjCANTLALPZTc5inuvOz-O7duFjtFzoHmKlHFlT3lAcVyvS3VaGpsgiEOr1KANRVjizNFqt2m3B13IUHSdFFjyHIsvQJMdKzuAMp3uak6DDCNUyjf8P2NL8-CAA)

### 💻 Code

```ts
function isFunction(value: unknown): value is (...args: any[]) => any {
    return typeof value === 'function';
}

function testTypes(
    a: string | ((y: number) => string),
    b: number | ((y: number, z: string) => void),
) {

    if (isFunction(a)) {
      // `a` is correctly  inferred/asserted as `(a: number) => string`
    } else {
      // `a` is correctly  inferred/asserted as `string`
    }

    if (isFunction(b)) {
      // 4.7.4 - `b` is inferred/asserted as `(y: number, z: string) => void`
      // 4.8.2 - `b` is  inferred/asserted as `(...args: any[]) => any`
    } else {
     // `b` is correctly  inferred/asserted as `number`
    }
}
```

### 🙁 Actual behavior

Type-narrowing as a function without return (`=> void`) using generic function type definitions results in very generic types.

### 🙂 Expected behavior

Type-narrowing a function without return (`=> void`) should be possible.

### Further information

I'm not very sure about the vocabulary (inferring, type-narrowing, asserting, etc.) so I'll excuse myself if I'm unclear.

If the asserting method is specified as asserting `value is Function`, it works as expected, both in [4.7.4](https://www.typescriptlang.org/play?ts=4.7.4#code/GYVwdgxgLglg9mABDAzgMXNeYAUA3AQwBsQBTALkXAGsw4B3MASksJNORUQ0lgUQDeAKESjEAJ1JQQ4pFACeAB1JxgiNmUQBeHYgDkoXtj0BuIQF8hQw1n5RSKKABUlDnCLEFKj8TDABzRAAfRBwceUowEABbACNScSZtAD5EHz9-JgAaD1FYyJj48WDQ8IK4hKzEAC9vKF8ApK1UvDgYABNsoSThXOQ1HFQeW1wCJh6+sUQAemnEAAMCebSACzgQInbEeMQCFBQE+y29hbLEKIrElLT6jPmrKanZxAABKBQAWlIAD2VoL-E4jgxQA6hwUGsNlsVgQ8Bw9gdxEdEFAYVBdpwMTY+GBJmIIAhHIgAPp1BqBLTbMx40TPN6fH5-KAAoGg0h6SSIRQIjIolYcehAgLnQoJRCqXbifwxUhgd403Y4JhmKbmRCkIgHQQKunvL6-Uj-BKsxBg1brTaIGFw3b7Q6kLaogjogiYuguxDY7AKghKlViSx9GADIaYHE4WLjbWPMTPeaxZYQi1bJNQ7bwu1Ih2204REWXKq1G7kpotNrte46ub0-VMlnA03gyGW60ZxHIp3o2KY11ehAKglgImk4u8ymxakx2nVvWMw3M40NsEcjjc-a81ECoWBC5FcVqAhSmVylAK2J+vpqjVa4RTmYzhkGo2ApdN5NW2Ft+2OtHbN1wD0+1xO9z2VS8LCAA) and [4.8.2](https://www.typescriptlang.org/play?ts=4.8.2#code/GYVwdgxgLglg9mABDAzgMXNeYAUA3AQwBsQBTALkXAGsw4B3MASksJNORUQ0lgUQDeAKESjEAJ1JQQ4pFACeAB1JxgiNmUQBeHYgDkoXtj0BuIQF8hQw1n5RSKKABUlDnCLEFKj8TDABzRAAfRBwceUowEABbACNScSZtAD5EHz9-JgAaD1FYyJj48WDQ8IK4hKzEAC9vKF8ApK1UvDgYABNsoSThXOQ1HFQeW1wCJh6+sUQAemnEAAMCebSACzgQInbEeMQCFBQE+y29hbLEKIrElLT6jPmrKanZxAABKBQAWlIAD2VoL-E4jgxQA6hwUGsNlsVgQ8Bw9gdxEdEFAYVBdpwMTY+GBJmIIAhHIgAPp1BqBLTbMx40TPN6fH5-KAAoGg0h6SSIRQIjIolYcehAgLnQoJRCqXbifwxUhgd403Y4JhmKbmRCkIgHQQKunvL6-Uj-BKsxBg1brTaIGFw3b7Q6kLaogjogiYuguxDY7AKghKlViSx9GADIaYHE4WLjbWPMTPeaxZYQi1bJNQ7bwu1Ih2204REWXKq1G7kpotNrte46ub0-VMlnA03gyGW60ZxHIp3o2KY11ehAKglgImk4u8ymxakx2nVvWMw3M40NsEcjjc-a81ECoWBC5FcVqAhSmVylAK2J+vpqjVa4RTmYzhkGo2ApdN5NW2Ft+2OtHbN1wD0+1xO9z2VS8LCAA). Generally, I think `Function` should be avoided by all recommendations, however in the function example I've specified here, it would be correct since that's what `typeof value === 'function'` does.

I couldn't find any changes around `void`, but I assume this behaviour is related to the changes to [intersection reduction and narrowing](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#improved-intersection-reduction-union-compatibility-and-narrowing). However I can't really figure out a way to define a function that can return `any` _or_ `void`. None of these works in `4.8.2`

- `value is (...args: any[]) => (void | any)`
- `value is (((...args: any) => void) | ((...args: any[]) => any)))`
- `value is (...args: any) => unknown`

**Comment by oBusk** [comment]
Well `(...args: any[]) => any` reads to me as "function with any number of variables of any type, and any type of return", kind of "any function". So my thought is that if I have something that could be both a function and non-function type, the function can only really assure that it is a function, and it doesn't know what parameters or what it returns. I agree that `Function` is correct, and yes, eslint is the one complaining. 

`(...args: never)` is a weird definition.. Can it be read as "any function and we don't care about the parameters"?

**Comment by fatcerberus** [comment]
> Well (...args: any[]) => any reads to me as "function with any number of variables of any type, and any type of return"

There’s a subtle difference because of contravariance: It means “*accepts any number of variables* of any type as input, and returns any type as output”.  This obviously doesn’t cover all functions, because some arguments might be required.  So you need to put the bottom type (`never`)  in the contravariant position to catch everything.  The difference in behavior here is probably down to soundness improvements in 4.8.

**Comment by oBusk** [comment]
Ok that explanation of `(...args: any[])` makes sense to me, but how does `(...args: never)` not define a function as having no arguments, as `never` is supposed to be a type that should never occur?

**Comment by fatcerberus** [comment]
The way to think about it is that `(…args: never) => unknown` is the least capable function type, since you can’t actually call it (it’s only “callable” in the abstract).  Every other function is more capable, and therefore a subtype.  This is like `unknown` being the least capable value type, since you can only pass it around.

**Comment by fatcerberus** [comment]
I think `(...args: any) => any` might work, if you’re more comfortable with that (i.e. you want any `any`-like function type).

**Comment by andrewbranch** [comment]
Nice explanation by @fatcerberus. I have nothing to add.

**Comment by oBusk** [comment]
It was well explained yes, and `(...args: never) => unknown` works as a drop in fix! Thanks a lot @fatcerberus
