### ISSUE TITLE
according to DOM specs cancelBubble is a legacy alias of .stopPropagation()

### ISSUE THREAD

**Issue by Ahmed-Hakeem** [microsoft/TypeScript#50517]
# lib Update Request

## Missing / Incorrect Definition

according to DOM spec cancelBubble is a legacy alias of .stopPropagation()

## Documentation Link

https://dom.spec.whatwg.org/#interface-event

## Reference 
https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1384

**Comment by fatcerberus** [comment]
Not only deprecated, but also according to MDN, on Chromium-based browsers:
* Starting with Chrome 58 and Opera 45, setting this property to false does nothing, as per [spec discussion](https://github.com/whatwg/dom/issues/211).

**Comment by MartinJohns** [comment]
Needs to be fixed in https://github.com/microsoft/TypeScript-DOM-lib-generator. Modifying generated files as you did in your MR won't do it.

**Comment by Ahmed-Hakeem** [comment]
Fixed in [https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1386h https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1386h](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1394) @RyanCavanaugh

**Comment by jakebailey** [comment]
This was fixed in #50884.
