### ISSUE TITLE
Inferred return of a callback differs based on inline object literal vs variable assignment

### ISSUE THREAD

**Issue by andparsons** [microsoft/TypeScript#50516]
# Bug Report

### 🔎 Search Terms
multiple inline callbacks inferred type narrowing returns object literals

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about callback return type narrowing and subtype reduction

### ⏯ Playground Link
[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.7.4#code/PTAEAEGcBcCcEsDG0BQLEHsB2NSXlgOYA2ApqALygDeKo9oA+tAJ4AOpAXKAOT5FkeAGjoN+JUgEkAJtx4BXefGnCUAX1ABDSKEw5UKAGbysyeNlCGAjAApMJ6NyzyAtgCNSsAJQ0UIBgEAegD8ovTwhnYYDpQUVFY+tAEBsKTQ8rBYeAQSoGGgamgpaRlZScn0zOxcvC7yxNDwbIIiFfR1DU1kMnKKyqoBGtq62DDqaMamjRaGAExRDk6uHt6+-hUh+RELWNCx8Yn5AXq4kGypmtKUNAB0d+JkQzonqG2gqemZeOekl-mF+Q+pV8byqHDkHUazVIAzakK6UlkvD6KlaDCeI304yMJjMMwAzDtHKBnO5PId1slNgFtvZdvtQAkQW0gV9ym96Hcbg9SEcKv4AOKaAg6C7SbDEFigeHQmTBbgmaSkQwEUjSPn0DEvf5FBissoapiscG1epQlqGmXdJEKJSo-5aZ6jVAAyZ4rKGAAsRKWZNWtEpQVCNMidL2cQOzIq+qjHK57I5ATBNT4OQtiYqPJ6yLtsMTWudhoYguFOHev3FWEl0rNCLlCqwSpVWDVhoLWMGuvoMYTSeNKatMLRFUH2dt-WHBUdmLGrtx0w9AFYfSTluS1mANsGGLTovSI4zDm8e0WGMm5Dy8xyszaUVe2iWReXLhKpaPpPLQIrlar1W922MnaAiUbKGuepqdNC94MO+vS5pOASPmWYqvtkAiIp+37Nq2gzTtqAKkAAHmwGCwHs-Y0NYQhzNR+LUZ61GLmoQA)

### 💻 Code

```ts repro
// @strict

const single = {
    _type: 'single',
    singleId: 'uuid',
} as const

function f1(count: number) {
//       ^?
    if(count === 1) {
        return single 
    }

    return {
        _type: 'multiple',
        multipleId: 'uuid',
    } as const
}

function f2(count: number) {
//       ^?
    if(count === 1) {
        const spread = {...single} as const
        return spread
    }

    return {
        _type: 'multiple',
        multipleId: 'uuid',
    } as const
}

function f3(count: number) {
//       ^?
    if(count === 1) {
        return {
            ...single
           // Gains readonly multipleId?: undefined
        } as const
    }

    return {
        _type: 'multiple',
        multipleId: 'uuid',
    } as const
}

function f4(count: number) {
//       ^?
    if(count === 1) {
        return {
            ...{
                _type: 'single',
                singleId: 'uuid',
            } as const
           // Gains readonly multipleId?: undefined
        } as const
    }

    return {
        _type: 'multiple',
        multipleId: 'uuid',
    } as const
}

function f5(count: number) {
//       ^?
    if(count === 1) {
        return {
            _type: 'single',
            singleId: 'uuid',
           // Gains readonly multipleId?: undefined
        } as const
    }

    return {
        _type: 'multiple',
        multipleId: 'uuid',
        // Gains readonly singleId?: undefined
    } as const
}

export type {f1,f2,f3,f4,f5}
```

### 🙁 Actual behavior
I was noticing some of my logic expecting to infer the return type of a callback was failing, looking into it further I was seeing a difference around the behaviour of the inferred callback returns. 

When they conditionally return different object literals, conditionally returning a new object inline when the final return is inline adds an additional optional property to the type.

In the above example, the f1 & f2 callbacks have the minimal return type of a distinct union as they return a variable holding an object reference, whereas f3 & f4 add a property of `readonly multipleId?: undefined` to the first return type, and f5 adds such a property to both return types, with `multipleId` and `singleId` respectively.

Setting exactOptionalPropertyTypes changes the type of undefined for the additional property to never, but otherwise persists the behaviour.

I guess I'm after clarification on whether this is intended behaviour or not, specifically when using a const assertion.

I would also expect at least the return types of f4 and f5 to match as I read them as both being essentially inline declarations.

### 🙂 Expected behavior
Like the comment below

**Comment by andparsons** [comment]
Conversely, if the last return is a variable, all return types are consistant whatever the first return type setup is.

```ts repro
// @strict

const single = {
    _type: 'single',
    singleId: 'uuid',
} as const

const multiple = {
    _type: 'multiple',
    multipleId: 'uuid',
} as const

function f1(count: number) {
//       ^?
    if(count === 1) {
        return single 
    }

    return multiple
}

function f2(count: number) {
//       ^?
    if(count === 1) {
        const spread = {...single} as const
        return spread
    }

    return multiple
}

function f3(count: number) {
//       ^?
    if(count === 1) {
        return {
            ...single
           // Gains readonly multipleId?: undefined
        } as const
    }

    return multiple
}

function f4(count: number) {
//       ^?
    if(count === 1) {
        return {
            ...{
                _type: 'single',
                singleId: 'uuid',
            } as const
           // Gains readonly multipleId?: undefined
        } as const
    }

    return multiple
}

function f5(count: number) {
//       ^?
    if(count === 1) {
        return {
            _type: 'single',
            singleId: 'uuid',
           // Gains readonly multipleId?: undefined
        } as const
    }

    return multiple
}

export type {f1,f2,f3,f4,f5}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?exactOptionalPropertyTypes=true&ts=4.7.4#code/PTAEAEGcBcCcEsDG0BQLEHsB2NSXlgOYA2ApqALygDeKo9oA+tAJ4AOpAXKAOT5FkeAGjoN+JUgEkAJtx4BXefGnCUAX1ABDSKEw5U6bLgC284tHhsylGqPrN2XXqfOXBIhqBcWrU2b0VlVQ1tXSMDADN5LGR4bFAIgEYACkxo6G4seWMAI1JYAEpbEE8GAD0AfjtQeAjUjHTKCipEotpShlhSaHlYLDwCCVBqtTRPLp6+rzMfMnU0KJiLeIiAJnr0zOy8wuKwDsrq2o2saCaWturPPVxINi7NaRtqADo38TIQnRvUDvoJ3r9O4PaQjMadbqA6auXzzFCLWIrADMJwyoCyuXylxKByqnmOaVO51ArVsf1AAKm7XJDDeLw+pCuHRKAHFNAQdCDsMQWNDZn4KtxotJSBECKRQeSvmF9GDqpT+t43IzRvDooj+hEACyoraY3a0HGlQ74uqEs7NC5kv4K6000B06n2zwODhyBmqZ2lBkyOSBFQeZ3Sn5M0qs9k4CmkR7c3lK3wyQWgYWi8WSv7B8Jy8aQqbxuaqhHLTUAVl16O2WL2fxNDAJDSJlpJl3JtqdNNdTj4g3coe9Pb8fqUAb7DHDHKjMawPL5ysTQqwIrFWAlfczss8qpzk0VM2VcNIAA82BhYGdWBwaEkhGsb0ib1qbyW1EA)

**Comment by andparsons** [comment]
Conversely, if the last return is a variable holding an object reference, all the return types are now identical whatever the setup of the condition return.

```ts repro
// @strict

const single = {
    _type: 'single',
    singleId: 'uuid',
} as const

const multiple = {
    _type: 'multiple',
    multipleId: 'uuid',
} as const

function f1(count: number) {
//       ^?
    if(count === 1) {
        return single 
    }

    return multiple
}

function f2(count: number) {
//       ^?
    if(count === 1) {
        const spread = {...single} as const
        return spread
    }

    return multiple
}

function f3(count: number) {
//       ^?
    if(count === 1) {
        return {
            ...single
        } as const
    }

    return multiple
}

function f4(count: number) {
//       ^?
    if(count === 1) {
        return {
            ...{
                _type: 'single',
                singleId: 'uuid',
            } as const
        } as const
    }

    return multiple
}

function f5(count: number) {
//       ^?
    if(count === 1) {
        return {
            _type: 'single',
            singleId: 'uuid',
        } as const
    }

    return multiple
}

export type {f1,f2,f3,f4,f5}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?exactOptionalPropertyTypes=true&ts=4.7.4#code/PTAEAEGcBcCcEsDG0BQLEHsB2NSXlgOYA2ApqALygDeKo9oA+tAJ4AOpAXKAOT5FkeAGjoN+JUgEkAJtx4BXefGnCUAX1ABDSKEw5U6bLgC284tHhsylGqPrN2XXqfOXBIhqBcWrU2b0VlVQ1tXSMDADN5LGR4bFAIgEYACkxo6G4seWMAI1JYAEpbEE8GAD0AfjtQeAjUjHTKCipEotpShlhSaHlYLDwCCVBqtTRPLp6+rzMfMnU0KJiLeIiAJnr0zOy8wuKwDsrq2o2saCaWturPPVxINi7NaRtqADo38TIQnRvUDvoJ3r9O4PaQjMadbqA6auXzzFCLWIrADMJwyoCyuXylxKByqnmOaVO51ArVsf1AAKm7XJDDeLw+pCuHRKAHFNAQdCDsMQWNDZn4KtxotJSBECKRQeSvmF9GDqpT+t43IzRvDooj+hEACyoraY3a0HGlQ74uqEs7NC5kv4K6000B06n2zwODhyBmqZ2lBkyOSBFQeZ3Sn5M0qs9k4CmkR7c3lK3wyQWgYWi8WSv7B8Jy8aQqbxuaqhHLTUAVl16O2WL2fxNDAJDSJlpJl3JtqdNNdTj4g3coe9Pb8fqUAb7DHDHKjMawPL5ysTQqwIrFWAlfczss8qpzk0VM2VcNIAA82BhYGdWBwaEkhGsb0ib1qbyW1EA)

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; see #19513 for motivation

**Comment by andparsons** [comment]
Thanks for coming back to me @RyanCavanaugh

Would you also be able to point me to an explainer about how an object literal is affected by containing a spread?
