### ISSUE TITLE
Default generic parameter in function is ignored

### ISSUE THREAD

**Issue by Ni55aN** [microsoft/TypeScript#50526]
# Bug Report

The compiler isn't able to check assignment of generic function with default parameter

### 🔎 Search Terms

`generic function` `return type` ``

### 🕗 Version & Regression Information

Reproducible on all version (including Nightly)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBAMglgZ2FAvFA3gWAFBSgIgEN8AuKJAJzgDsBzHPfAI1KiYHt2AbCQ6nAL45QkKAGkIIBKigByQrKgAfOU1kBuHMPDQAgjIAUAOhOEKtBGT4gA2gF0AlKgB8UagFcAtkwgVtogCEARhkAHjEoCAAPYAhqABNpCSlnA2BCWjIxJxRXeCQbeVk7f2gAgCYwiOjYhKTJBFT0zLkFHLzEYBsxEuwRMoBmKsiYuMTxBqaMsiLlVVl22E7u3v6oAIAWYZqx+pS06fFF-K6e0vWAVnCR2vHkxsNmrOPls76ddYA2a526iZTHodsi4lgU3msAgB2H6jP73GT3VxoA4tYG5UGnVYfAIADm2sLuDQRkxRzxBJxWWmwAGN2NQkFBCIYDIsgk5CNJdDhafTkEwQsiWSDZAMFozpMFuXSGUxKoLFiKxRz1uUpby2EN5cLReyJQM1TKtlr0YrdesNga+RdmQqdeLLuFJpa2J8bdqlRLvtZnM6mJC3Sa7cqob68cbXKb7biqTyGdSORAgmR9Gh+c74wgIOVkzJZemEwMc6n9TTpcgMxANkW2BbS+qKxdq0wLvnM58m59WxBIU3IV2cU2cVSgA)

### 💻 Code

```ts
type List = {
  "a": string
  "b": boolean
}
type Keys = 'a' | 'b';

type A = (...args: any[]) => number
type B1 = <K extends Keys>(tag: K) => List['a']
type B2 = <K extends Keys>(tag: 'a') => List[K]
type B3 = <K extends Keys>(tag: 'a' | 'b') => List[K]
type B4 = <K extends Keys>(tag: K) => List[K]
type B5<K extends Keys> = (tag: K) => List[K]
type B6<K extends Keys> = (tag: K) => List[K]
type B7<K extends Keys = Keys> = (tag: K) => List[K]
type B8 = <K extends Keys = Keys>(tag: K) => List[K]

const a = (() => 1) as A
const b1 = (() => '3') as B1
const b2 = (() => '3') as B2
const b3 = (() => '3') as B3
const b4 = (() => '3') as B4
const b5 = (() => '3') as B5<Keys>
const b6 = (() => '3') as B6<any>
const b7 = (() => '3') as B7
const b8 = (() => '3') as B8

const case1: A = b1 // ✔️ Type 'string' is not assignable to type 'number'
const case2: A = b2 // ✔️ Type 'string | boolean' is not assignable to type 'number'.
const case3: A = b3 // ✔️ Type 'string | boolean' is not assignable to type 'number'.
const case4: A = b4 // ✔️  it's okay, doesn't throw an error because K becomes any
const case5: A = b5 // ✔️ Type 'string | boolean' is not assignable to type 'number'.
const case6: A = b6 // ✔️  it's okay, doesn't throw an error because K becomes any
const case7: A = b7 // ✔️ Type 'string | boolean' is not assignable to type 'number'.
const case8: A = b8 // ❌ should throw an error because K has to be `Keys` by default
```

### 🙁 Actual behavior

The assignment `case8` doesn't throw an error

### 🙂 Expected behavior

The assignment `case8` should throw an error

**Comment by Ni55aN** [comment]
The only workaround I've found is to explicitly check for `any` and substitute with a default type

```ts
type NoAny<T, Default> = T extends any ? Keys : Default

type B8 = <K extends Keys = Keys>(tag: NoAny<K, Keys>) => List[NoAny<K, Keys>]

```

**Comment by RyanCavanaugh** [comment]
B8 and B4 are not different from an assignability perspective. The default only comes into play during inference at a call site.

**Comment by Ni55aN** [comment]
@RyanCavanaugh then how to force the checker to use default generic parameter in B8?

**Comment by fatcerberus** [comment]
tbh I'm not really sure why *any* of these functions are assignable to `A` since they can never return a number according to their type signatures.

**Comment by tjjfvi** [comment]
`b4` is assignable to `A` because `b4<any>` is `(tag: any) => any` (the `any` comes from `A`'s `(...args: any[])`)

**Comment by Ni55aN** [comment]
@RyanCavanaugh do you now how to force the checker to use default generic parameter in B8?

**Comment by RyanCavanaugh** [comment]
@Ni55aN there's not a way to do that because generic defaults are not part of the assignability contract of generic functions (nor should they be)

**Comment by Ni55aN** [comment]
> generic defaults are not part of the assignability contract of generic functions

@RyanCavanaugh  seems like generic defaults work correctly in this assignment

```ts
type List = {
  "a": string
  "b": boolean
}
type Keys = 'a' | 'b'

type A = (...args: any[]) => number
type ANoAny = (a: Keys, b: Keys) => number
type B8 = <K extends Keys = Keys>(a: K, b: K) => List[K]

const case9: A = 1 as any as B8 // ❌ should throw an error, but different return types are ignored 
const case10: ANoAny = 1 as any as B8  // ✔️ Type 'string | boolean' is not assignable to type 'number'
```

Probably `...args: any[]` breaks the assignment. Can somebody confirm it?

**Comment by Ni55aN** [comment]
Returning to the `case4`, `case6` and `case8`

If I replace `...args: any[]` with `tag: string` it works correctly (only `case6` doesn't throw an error because `any` explicitly passed as generic parameter)

**Comment by Ni55aN** [comment]
up. It seems more like a bug though.

```ts
type List = {
  "a": string
  "b": boolean
}
type Keys = 'a' | 'b'

type FixType<T> = T extends (...args: infer P) => infer R ? [P, R] : never

type A = (...args: any[]) => number
type ANoAny = (a: Keys, b: Keys) => number
type B8 = <K extends Keys = Keys>(a: K, b: K) => List[K]

const case9: A = 1 as any as B8
const case10: ANoAny = 1 as any as B8
const case11: FixType<A> = 1 as any as FixType<B8> // ✔️ Type 'string | boolean' is not assignable to type 'number'
```

I think that this confirms the fact that generics in this case work quite correctly

**Comment by Ni55aN** [comment]
Another interesting example

```ts
type List = {
  "a": string
  "b": boolean
}
type Keys = 'a' | 'b'

type A = (...args: any[]) => number
type B8 = <K extends Keys = Keys, N = K>(a: N, b: N) => List[K]

// typecheck works correctly if the generic parameter used in the return type is not used in the parameters directly
const case9: A = 1 as any as B8 // ✔️ Type 'string | boolean' is not assignable to type 'number'
```

**Comment by Ni55aN** [comment]
flow.js also cannot to infer the return type correctly

```ts
type List = {
  "a": string;
  "b": boolean;
}
type Keys = 'a' | 'b'

type A = (...args: any[]) => number
type B8 = <K: Keys = Keys>(a: K, b: K) => List[K]

let n: List['b'] = true


let f: B8 = () => '45';
(f: A)
```

[link](https://flow.org/try/#0PQKgBAAgZgNg9gdzAZwC4CcCWBjVYTABQhqAngA4CmYAMpmmALxgDehYYARAIacBcKDJgB2AcwDc7LgCN+YaXDgxK3YZIC+JCtQDSlUsiZgA5N2NgAPienHiZKmACCRgBQA6D93SjkA1aQBtAF0ASiYAPjBhAFcAW2lKdC0HACEADiMAHh0BPQMjPORwl25cgBp5XLDGSLo0AJ0g4mU8YQE61ADjGyCjDGjKYkIWsCgBdNdqyOMAFgBWY0lCFzGnEOIgA)
