### ISSUE TITLE
`RegExpExecArray` should have explicit always-defined properties

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#50520]
\[L]ooking a little closely at the ECMAScript spec, I do think that there is a mismatch between what we have and what gets created in the runtime. [`RegExpBuiltinExec` says that the following are created unconditionally](https://tc39.es/ecma262/#sec-regexpbuiltinexec):

* an `index` property
* an `input` property
* a property at index `0`
* a `groups` property that *is always set*, but may be `undefined`

So `RegExpExecArray` should look something kind of like

```ts
// src/lib/es5.d.ts

interface RegExpExecArray extends Array<string> {
    // always present
    index: number;

    // always present
    input: string;

    // always present - helpful for '--noUncheckedIndexedAccess'
    0: string;
}
```

```ts
// src/lib/es2018.regexp.d.ts

interface RegExpExecArray extends Array<string> {
    // always present - helpful for '--exactOptionalPropertyTypes'
    groups: { [key: string]: string } | undefined;
}
```

*Derived from content posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/50211#issuecomment-1210008233*

______

In additionl to the above, it *seems* like `RegExpMatchArray`/`RegExpExecArray` are sometimes both returned from functions that undergo the same internal code paths. So we should probably ensure that one is compatible with the other, and have a test that ensures as much.

**Comment by DanielRosenwasser** [comment]
Relevantish because @DetachHead sent https://github.com/microsoft/TypeScript/pull/49682

**Comment by DanielRosenwasser** [comment]
Because people will come back to this issue, here's an example of where `RegExpExecArray` and `RegExpMatchArray` really should differ.

```
> "blahfoo".match(/(bar)?/g)
< (8) ['', '', '', '', '', '', '', '']

> /(bar)?/g.exec("blahfoo")
< (2) ['', undefined, index: 0, input: 'blahfoo', groups: undefined]
```

**Comment by TomasHubelbauer** [comment]
In your code sample I believe the last line should be this:

```
< (2) ['', { undefined, index: 0, input: 'blahfoo', groups: undefined }]
```

**Comment by fatcerberus** [comment]
@TomasHubelbauer No, he was right:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/4097841/187446367-4cb74c13-920b-4f13-be93-ede50d3c33c9.png">

**Comment by graphemecluster** [comment]
Actually there shouldn’t be anything like `RegExpMatchArray`. Because the spec states that `String.prototype.match` either returns either what `RegExp.prototype.exec` returns, or a string array with at least a single item, we should change the return type of `.match` to `[string, ...string[]] | RegExpExecArray | null`. And, please consider reverting #49682 since it breaks a lot of existing codes (#50633).

**Comment by DetachHead** [comment]
i think the solution is to add the `0: string` to `RegExpExecArray` as well instead of reverting #49682. i'm happy to make a PR for this
