### ISSUE TITLE
infer doesn't work correctly with type predicates

### ISSUE THREAD

**Issue by glevchuk** [microsoft/TypeScript#50524]
# Bug Report

### 🔎 Search Terms

infer type predicates

### 🕗 Version & Regression Information

- I've tested this in last 4 versions and i've got same behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.7.4#code/JYOwLgpgTgZghgYwgAgEoQM4AcD2IMQCiUUOUyA3gFDLJgCeWEAXMhmFKAOYDcNyAEzhg4AflboEZAQB52nEFwA0bDtwB8fAL5UqoSLEQoACnHoBbCOGKlyEAB6QQAjGky58REmUr8GTVgAiUwsrMBsyQL5aIRFWCmQoCDgMPFZ5bmQtbV0pfDBkYAwQy2tvcgBeZAAKaFsJdzwCCKgASlY6nyLkErCW5Ar1fk6oADp-FAqp5GCzUvDyqNymgqxSJAwMFtcqmX4AFUYIAHEAVzgoAWQHJxcakYbsJq9bVoH1ZAAjHBwAG2SQEp+C1DkwBshQSdzpdro4rHdauVHh5muU3oNruVCq5QDBoMgAKr8WiiQnE5CsU4gADWIBwAHcQFR1NVhuUMMjni0ANoAXSBtAmZwuAlYkOFlwFyAQcF+v0+iGprER9WQIKO6I+ADccMABFRNZRsro1jgNlt2azaHypUVemVbFKVWRDdRaAB6d3IAB6onJI1GsTgoySKTw5M9tCj0dovv4OlaPCAA)

### 💻 Code

```ts
interface ResponseError {
  type: string;
  data?: Record<string, string>;
}

interface PaymentError extends ResponseError {
  type: "PaymentError";
  data: { reason: string };
}

const isPaymentError = (error: ResponseError): error is PaymentError =>
  error.type === "PaymentError";

const processErrors = <
  TypeGuard extends (error: ResponseError) => boolean,
  ErrorType = TypeGuard extends (error: ResponseError) => error is infer U
  //  =============================================================^
  // A type predicate's type must be assignable to its parameter's type.
  // Type 'U' is not assignable to type 'ResponseError'.(2677)
    ? U
    : unknown
>(
  errors: ResponseError[],
  typeGuard: TypeGuard,
  callback: (error: ErrorType) => void
) => {};

processErrors(
  [],
  isPaymentError,
  (error) => {
  // ^? (parameter) error: PaymentError
    error.data.reason
    //           ^? (property) reason: string
  }
);
```

### 🙁 Actual behavior

Error on infer declaration, but types inferred correctly

### 🙂 Expected behavior

TypeScript doesn't throw an error

**Comment by shicks** [comment]
The error is saying that you're not allowed to declare a type guard where the narrowed type is _not_ assignable to the wider type.  Here's a [simpler example](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAzgORAWwEYFMBOAFAB4BciKU+MYA5gJTnHIqJhZ76IDeAUIony4oIfEmABDADYpcAbl4BfIA):

```typescript
function isNumber(x: string): x is number {
  return false;
}
```

You can fix it in your case by either [changing the argument type to unknown](https://www.typescriptlang.org/play?ts=4.7.4#code/JYOwLgpgTgZghgYwgAgEoQM4AcD2IMQCiUUOUyA3gFDLJgCeWEAXMhmFKAOYDcNyAEzhg4AflboEZAQB52nEFwA0bDtwB8fAL5UqoSLEQoACnHoBbCOGKlyEAB6QQAjGky58REmUr8GTVgAiUwsrMBsyQL5aIRFWCmQoCDgMPFZ5bmQtbV0pfDBkYAwQy2tvcgBeZAAKaFsJdzwCCKgASlY6nyLkErCW5Ar1fk6oADp-FAqp5GCzUvDyqNymgqxSJAwMFtcqmX4AFUYIAHEAVzgoAWQHJxcakYbsJq9bVoH1ZAAjHBwAG2SQEp+C1DkwBshQSdzpdro4rHdauVWKcQABrEA4ADuIDeg2u5UKrlAMGgyAAqvxaKJyZTkMi0RjsVR1NVhuUMI8PM1ygBtAC6QNoEzOFwErEhIsuguQCDgv1+n0QqNYiPqyBBR1xHwAbjhgAIqFrKNldGscBstuzWbR+dKir0yrZpaqyEbqLQAPQe5AAPVEtJGo1icFGSRSeFpXto0ZjtD9-B0rR4QA):

```typescript
    ErrorType = TypeGuard extends (error: unknown) => error is infer U
```

or else [using an intersection with the infer](https://www.typescriptlang.org/play?ts=4.7.4#code/JYOwLgpgTgZghgYwgAgEoQM4AcD2IMQCiUUOUyA3gFDLJgCeWEAXMhmFKAOYDcNyAEzhg4AflboEZAQB52nEFwA0bDtwB8fAL5UqoSLEQoACnHoBbCOGKlyEAB6QQAjGky58REmUr8GTVgAiUwsrMBsyQL5aIRFWCmQoCDgMPFZ5bmQtbV0pfDBkYAwQy2tvcgBeZAAKaFsJdzwCCKgASlY6nyLkErCW5Ar1fk6oADp-FAqp5GCzUvDyqNymgqxSJAwMFtcqmX4AFUYIAHEAVzgoAWQHJxcakYbsJq9bVoH1ZAAjHBwAG2SQEp+C1DkwBjVQSdzpdro4rHdqrVyo8PM1ym9BtdyoVXOgnp4WgAyaqgGDQZAAVVarX4tFElNpyFYpxAAGsQDgAO4gGnqarDcoYFHPFoAbQAukDaBMzhcBKxIbLLlLkAg4L9fp9EKzWEj6sgQUcMR8AG44YACKjGyjZXRrHAbLaC-m0CUqoq9Mq2FV6sjW6i0AD0geQAD1RIyRqNYnBRkkUnhGcHaCnU7Rw-wdK0eEA):

```typescript
    ErrorType = TypeGuard extends (error: ResponseError) => error is ResponseError&infer U
```

There may be a use case where we'd like to be able to put a lower bound on an inferred type variable, but I don't think this is it?

**Comment by whzx5byb** [comment]
You should declare a constraint for the inferred type: 

```diff
const processErrors = <
  TypeGuard extends (error: ResponseError) => boolean,
-  ErrorType = TypeGuard extends (error: ResponseError) => error is infer U
+  ErrorType = TypeGuard extends (error: ResponseError) => error is (infer U extends ResponseError)
  //  =============================================================^
  // A type predicate's type must be assignable to its parameter's type.
  // Type 'U' is not assignable to type 'ResponseError'.(2677)
    ? U
    : unknown
>(
```

**Comment by RyanCavanaugh** [comment]
@whzx5byb's suggestion is the preferable one

**Comment by polkovnikov-ph** [comment]
> not allowed to declare a type guard where the narrowed type is not assignable to the wider type

The type if inferred. It's assignable or not assignable only due to inner workings of TS's type checker. It was (hopefully) a conscious choice not to bound an inferred type automatically.

>  error is (infer U extends ResponseError)

Is that a valid syntax? I think it should be `error is Extract<infer U, ResponseError>`.

**Comment by whzx5byb** [comment]
> Is that a valid syntax?

Yes, it is introduced [since 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#extends-constraints-on-infer-type-variables).

**Comment by shicks** [comment]
> > not allowed to declare a type guard where the narrowed type is not assignable to the wider type
> 
> The type is inferred, not specified. It's assignable or not assignable only due to inner workings of TS's type checker. It was (hopefully) a conscious choice not to put a bound on an inferred type automatically.

I could see it going either way, but it takes a certain amount of smarts to recognize that it's actually OK because the rule about type predicates effectively adds an implicit lower bound on `U`.  It seems quite reasonable that the type checker doesn't have that kind of smarts built in.  Though it could be a delightful surprise, and potentially wouldn't cause any unpleasant surprises, if it could do it automatically.

> > Is that a valid syntax?
> 
> Yes, it is introduced [since 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#extends-constraints-on-infer-type-variables).

TIL.
