### ISSUE TITLE
[regression 4.8] type narrowed too far; valid cases considered unreachable

### ISSUE THREAD

**Issue by seansfkelley** [microsoft/TypeScript#50527]
# Bug Report

### 🔎 Search Terms

type narrowing assertNever never unreachable 

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.8.x

### ⏯ Playground Link

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/KYOwrgtgBACgTgewA7DgFwJ4BUMqgbwCgooBlNOASxAHMoBeKAcgGcLqamAaYqAOUgAjVA2bgIwuN14BVEAGsQCAO4hRTMAqWrpAX0KFqaVADMAhgGNgsRCnQYAPDjzAAHsZAATFjeSpMzsBcUABqZgA2YNZuHt5QmooqaowJ2iAAfAS8mCgAXFCBANy8AG4RUflhkcDF+oQ51uRUtPB+9qKtdpgOnf7YuMAAdE0cwWzNNOnFDfxCqL3tjAvdy-0ogwISqMHiklP1A1ByiaqrHbZ9PRf2gYPHacGpSfsHeKsA8oIAVsAWaAy8AA+ZHYLWumCBsy2cFWkPuSVhr2sH2+vzQ7zgAFEIEhMOc2phPj8-lBgfgoA18qsilAytV8ppPMATNRgJ4oLpioYQMY4OYrFBMZ5KGgHCEsFAYqA4ijif8luCMES0ZkiCRKcw2SKmMUSEhFZUsLUDEZTJZrABBTyeMUSqVeHyytEY7G4jD4rpK1F-F04zCq7IDfJMMzWnW8fUEjCG42EEyaP6UBBqMwsFj+PjAEqoAAUIHyICzqAAlAWi3AsuqABaIZRQQt1zFwRBwHNMJQoJjF2PxkCJ5NQTwIchgEwmHOWNBJ-OC4X-YFWzzFytQSgmKAT-sgQaRz2DOlRBiMcDhcLLtUkKAAeivg4QUBYCAgwDQVY4vF0kvC6dX683U+THdFUGGZ6DA3xPVueFVHPXgSBvO8HyfF831oL90w-dDrAveDb1fSgfHCVlVx8OBgEsKszEEcIgigQQwH+CwnyQSgaJ8ZQRSrBAGMlZsEDgABCOCoFTdN0EzbNW0nacgKjbsP0IOohxHMccwvDUmC1NBpD1A0V3VIMIL6W4RloHhL1pcpgGDKtgFPBBgmUfjwk8JgFN0YsgA)

### 💻 Code

```ts
enum PropertyType {
  String = 'string',
  Number = 'number',
  Unknown = 'unknown',
}

interface Property<Type extends PropertyType, Value extends unknown = unknown> {
  type: Type;
  value: Value;
}

type StringProperty = Property<PropertyType.String, string>;
type NumberProperty = Property<PropertyType.Number, number>;
type UnknownProperty = Property<PropertyType.Unknown, unknown>;

type PropertyObject =
  | StringProperty
  | NumberProperty
  | UnknownProperty

type PropertyObjectOrEmpty = PropertyObject | { type: PropertyType; value: undefined };

interface Edit<VT extends PropertyObject = PropertyObject> {
  type: 'edit';
  property: VT;
}

interface Add<VT extends PropertyObjectOrEmpty = PropertyObjectOrEmpty> {
  type: 'add';
  property: VT;
}

function assertNever(n: never): never {
  throw new Error('nope');
}

function doStuff(action: Edit | Add) {
  if (action.property.value == null) {
    // do something
  } else if (action.property.type === PropertyType.Unknown) {
    // do something else
  } else {
    // this line is reachable, but compiles without error!
    assertNever(action.property);
  }
}

doStuff({
  type: 'edit',
  property: {
    type: PropertyType.String,
    value: 'hello, world'
  }
})
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
var PropertyType;
(function (PropertyType) {
    PropertyType["String"] = "string";
    PropertyType["Number"] = "number";
    PropertyType["Unknown"] = "unknown";
})(PropertyType || (PropertyType = {}));
function assertNever(n) {
    throw new Error('nope');
}
function doStuff(action) {
    if (action.property.value == null) {
        // do something
    }
    else if (action.property.type === PropertyType.Unknown) {
        // do something else
    }
    else {
        // this line is reachable, but compiles without error!
        assertNever(action.property);
    }
}
doStuff({
    type: 'edit',
    property: {
        type: PropertyType.String,
        value: 'hello, world'
    }
});

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>
      
### 🙁 Actual behavior

Code compiles without error, but `assertNever` is hit at runtime.

### 🙂 Expected behavior

Compilation error: the type of `action.property` at the point it's passed to `assertNever` is not `never`. (4.7 does this.)

**Comment by whzx5byb** [comment]
A shorter repo:
```ts
type S = 
| { type: 'string', value: string } 
| { type: 'number', value: number } 
| { type: 'unknown', value: unknown }
| { value: undefined };

declare var s: S

if (s.value !== undefined) {
  s;
//^?
// 4.7: var a: S;
// 4.8: var a: { type: 'unknown', value: unknown };
}
```
4.7 doesn't narrow the type at all, while 4.8 narrows it incorrectly.

**Comment by andrewbranch** [comment]
@typescript-bot bisect good 8002369 bad v4.8.2

**Comment by fatcerberus** [comment]
The bot still gets hung up on 5aa0053... it looks like that's going to be an issue if the `good` is anything prior to that commit forevermore...

**Comment by andrewbranch** [comment]
I think the test runner can work around it by treating its array of root files as immutable. I’ll do that sometime this week.

#49736 is the alleged new culprit 😮

**Comment by andrewbranch** [comment]
At a glance, that makes no sense whatsoever

**Comment by jakebailey** [comment]
I'm not sure what the bot picked up on; when I do a bisect by hand, I get #49119 (which makes a lot of sense). @ahejlsberg

**Comment by berickson1** [comment]
I think I have a similar repro for this: https://www.typescriptlang.org/play?ts=4.8.2#code/JYOwLgpgTgZghgYwgAgMoFcAO0AqBPbZAbwChlkYB7SgLmRHQFsAjaAbhIF8SSwCUAYsCgBnMMgC8yAPKNgYADwZsUfNgA0yAORVKWgHzIAZMTLI4dMVFABzDt1780EBJRAATSTLmLlufpo61AbGpuQWyFa2HOS6lmDWIHZcPDDoIAhgwG7IjHgC6ZnZIAAUmFCUmCJ0QqJgAJR0AG6UwO4caRlZOXkFXcVlFVV0qC5u7o3ILW0dhd0guflzA+WV1ci1YgA+o64ek9OepOTAMMglABZwIgAKQ9B8g2uBulr19WHkyAD038h3a0iF0o6AANp5WPQ4FAKgB3CCeMCUZx7TxwcRgC7AETITCtcBmci-ZA4VDIAAsADoAByUgBMyAQoLgwEYONWVWQ2JR42QW3OsnkSiw-g0yAARLpxYYTERzPFEnZkJxQgAlMZQdwKSXUcWadIAaxAlFhIH0H35JUFvhFqgCEqlMuI8siCWiFGoCvdKpM6tcmoUlKD5sJPz+pIpNMpAAYALSsMBwRnM1nsoY47m7cah4kRqkAdkp5OTLLZuPTXJxWY8ob2YkiYw8I0bnikHJEbDDJNQZKptIZAFEYZQoHQ1BAcZQzhyHnhtK9zFAUKBXIxMOjgMxQRBKSSnFpDcbTVpK-RKOJriJgDYQHAtygkcg+IQtFEklpKbW3CJKNvKaDKBsEoRBbeoYi+JcwHQKAQHAhwiT+AFOREYEwQhFBb2HeFEWRTYLwxLF2XxMAzDrcQYGEMQako8Q23TTtc17KMGSZUscUxbluTwr8QB-P8AKAii6jAlISFzQiKGWHJuXQEDPCoKAn34WNMLhWwn2RdwIEgKA5BAZczjgBZoWYeQoGhOcZygPhkAgAAPbEwEnYyFkoZgACsXHEEojMRJx5HMHERHQBALnqEh7LxazJP6HIrlue5rLwBQcE0ABpWy7MgDwgrdJI+XoJhWEU-kRDwFhf30Eo3PcsdNA5Og0smGrTxwNUNS1NL9RAI0TTNT5IOg1yPOQABCCQpHSLSKP0zwjBMFrxqkBhQVBYwTGkDyvMpVYkWfHd4ukU0kNnSkEDgVbqo8+qhhE7ggA

Tracking issue status for this to drop in nightly

**Comment by andrewbranch** [comment]
@berickson1 I’m not sure exactly where that changed, but the new behavior is correct. `hasProperty(props, 'foo')` does not prove that `props` is a `Second`. It could be a `First & { foo: unknown }`.
