### ISSUE TITLE
Variable materialization with typeof

### ISSUE THREAD

**Issue by reverofevil** [microsoft/TypeScript#50530]
# Suggestion

## 🔍 Search Terms

typeof window

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`typeof undeclared_variable !== 'undefined'` should put `undeclared_variable` into scope.

## 📃 Motivating Example

```typescript
// module.js loaded by <script async src="module.js">
var foo = 'bar';

// index.ts
if (typeof foo === 'string') {
    console.log(foo.replace('r', 'z'));
}
```

## 💻 Use Cases

TS has a design goal of typing common JS patterns, and absence of such typing doesn't allow typing dynamically loaded modules without extending global interfaces. Global declarations are widely considered an antipattern.

**Comment by RyanCavanaugh** [comment]
This would have some serious unintended consequences, e.g.
```ts
function fn(something: string | undefined) {
  if (typeof someting === "string") {
    // Oops
  }
}
```

**Comment by polkovnikov-ph** [comment]
Yeah, I know, I just needed an official opinion on this.
