### ISSUE TITLE
`NonNullable` is accidentally simplified away from generic index accesses

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#50539]
# Bug Report

### 🔎 Search Terms

defer, index access, index signature, nonnullable

### 🕗 Version & Regression Information

- This **somewhat** changed between versions 4.7 and 4.8

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220830#code/JYOwLgpgTgZghgYwgAgMpjpVCAWEC2cyA3gFDLIDOGklA-AFwnkXIDaA1hAJ5PVSgA5gF0m6TBGx5CAbhYBfOfNKkAJhAQAbOFBRa4lSmhoQAcgHt1AHgAq4rLgJEIAD0ghVR+5MeEAfMwUlL5wTHYmUk5KKgD0McgA7uZQXKrIoMgALAB0AOzIAEYArmDIAA7QOHBlRogIwOrgcJqa3KRg3BXGEhbqlADC5iAwwIL9RVC64LbekYTIru6e3Q7ScAEAvIHsANLpIMhc3OYwyOESc3BsAETUEpTXwqIrZpYQMxEhN3e0j2w7wj8SjkpDiyDAOGARgA8jZoQAJKg4cxFTRpJIpZACQQ4UogcwJQoldKlVTmCCUEAAcjA7U6KG8vQpg2Go1MEASHwuIQWbggHi8nzWm22-32hx4JzOsy+txMDyeYhMTKsLAoFhAplR2gKmne51WTm+8sefn+whYQNIiiAA)

### 💻 Code

```ts
interface StateSchema {
  states?: {
    [key: string]: StateSchema;
  };
}

declare class StateNode<TStateSchema extends StateSchema> {
  schema: TStateSchema;
}

// worked in 4.7 but perhaps accidentally
type StateNodesConfigCurrent<TStateSchema extends StateSchema> = {
  [K in keyof TStateSchema["states"]]: StateNode<TStateSchema["states"][K]>;
};

// this OTOH should work right now but it doesn't
type StateNodesConfigNew<TStateSchema extends StateSchema> = {
  [K in keyof TStateSchema["states"]]: StateNode<
    NonNullable<TStateSchema["states"]>[K]
  >;
};
```

### 🙁 Actual behavior

`NonNullable` disappears when computing `getConstraintFromIndexedAccess`. Essentially this type:
```ts
NonNullable<TStateSchema["states"]>[keyof TStateSchema["states"]]
```
gets simplified/distributed to
```ts
TStateSchema["states"][string] | TStateSchema["states"][number] | TStateSchema["states"][symbol]
```

As we might notice here - `NonNullable` is gone from here because of the simplification rules:
```
// (T | U)[K] -> T[K] | U[K] (reading)
// (T | U)[K] -> T[K] & U[K] (writing)
// (T & U)[K] -> T[K] & U[K]
```

The third case applies here so we end up with something like this
```ts
TStateSchema["states"][string] & {}[string] | TStateSchema["states"][number] & {}[number] | TStateSchema["states"][symbol] & {}[symbol]
```

In here, those `{}[string | number | symbol]` are just reduced to `unknown` and `T & unknown` gets reduced to `T`. So that's how `NonNullable` "disappears" here.

Note that even though `T[number | symbol]`  is not valid for this `T` this indexed access is allowed based on this logic:
https://github.dev/microsoft/TypeScript/blob/488d0eebd0556fcc6e5f4cfc69c2ef7e5c2708ed/src/compiler/checker.ts#L16036-L16040

### 🙂 Expected behavior

`NonNullable` should be correctly retained/deferred in this case to preserve the correct constraint of the generic type.

**Comment by kasparkallas** [comment]
After updating from 4.7 to 4.8, I believe I'm running into a related issue. Unfortunately I'm not able to explain it in such technical detail but here's a reproducible: 
```ts
type Ordering<TOrderBy extends string> = {
    orderBy: TOrderBy
}

type Query<TOrderBy extends string> = {
    order?: Ordering<TOrderBy>
}

type QueryHandler<
    TQuery extends Query<TOrderBy>,
    TOrderBy extends string = NonNullable<TQuery["order"]>["orderBy"] // Worked in 4.7
> = {
    }
```
```
... does not satisfy the constraint 'string'.
... cannot be used to index type 'NonNullable...
```
[Playground Link](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/C4TwDgpgBA8gTgEwnAlgOwOYB4Aq8lwBCIUEAHsBGggM5Q3CqYB8UAvFAN4BQUfUAe0TJiALih5hRENwC+3bqEhQAigFdkIXPhElylanQZMMrDj36CpAfnE6T2qcWZyFS6Os0AJAIbUANshYvPw4nnB6FFS0qhoRjgTOADQhfJKJkQYxxugY7FAAcgJoBWr+-j4ARoG44SAA2gBEQgSNALrMTS267VAA9H1QAOpCANYQCFDoUAAsAHQA7NxmXKlQskA)

Disabling `strictNullChecks` makes the problem go away.

**Comment by Andarist** [comment]
I can confirm that this is also fixed by my PR. I'm gonna add this as an additional test case in a moment
