### ISSUE TITLE
Compile makes wrong assumption about a type

### ISSUE THREAD

**Issue by corno** [microsoft/TypeScript#50556]
# Bug Report

### 🔎 Search Terms

type inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bugs that aren't bugs

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/FAFwngDgpgBAYgewQeQE4CECGqYF4YBEAZkgTAD6EBG2BwwRArgHYDGIAlgszBKgqygBnIQApsqTGABcMKkgA2UTMwDaAXQCUMAN7AYBmEpAwAtmABqmBYyizEKDNjyESCOoZgSpAOhKoAUUxWAAtRUQA3a1ttXAA+XX1PQ3MrG1h8AhpUD0MAX00kgw4iGFFU6IzcTOyCbR0YAHpGmAAeAFp2mBAQjiEYIRCERgUAExhmBBMlTHGQBC8eKFR+VCLk5vW8mCgFIVg9LeA8oA)

### 💻 Code

```tsx

type FooOrBar = "foo" | "bar"

function process(array: boolean[]) {
    let myValue: FooOrBar = "foo"
    array.forEach((value) => {
        myValue = "bar"
    })
    if (myValue === "bar") { // <-- this should not lead to an error
        //
    } else {

    }
}
```

### 🙁 Actual behavior

the compiler says that 'myValue' cannot be "bar"

### 🙂 Expected behavior

the compiler realizes that 'myValue' can be "bar" as well as "foo"

**Comment by fatcerberus** [comment]
There’s a template for exactly this issue, but *sigh* people only seem to click it accidentally for unrelated issues…

Duplicate of #9998.

**Comment by corno** [comment]
I see. I missed that template indeed. Thank you.
Interesting how I never ran into that issue up until now.

**Comment by fatcerberus** [comment]
Yep, everyone hits it at some point.  It’s not great, but the alternatives aren’t necessarily any better, as covered in #9998.
