### ISSUE TITLE
Targeting ES6 not working for .njsproj projects.

### ISSUE THREAD

**Issue by LordFixer** [Microsoft/TypeScript#5055]
When working with .csproj project in Visual Studio I can set the target of ECMAScript version in Properties tab and it works correctly, so I can use generators and all this stuff. 
But when working with .njsproj project (node.js project) Visual Studio doesn't seem to care about these settings. I can see, that inside .njsproj file the target is actually set to ES6, but I keep getting "Generators are only available when targeting ECMAScript 6 or higher." message from intellisense (the code doesn't compile correctly, too).

**Comment by slikts** [comment]
You could try using `tsconfig.json` instead of `.njsproj`. IIRC VS uses `tsconfig.json` instead of project files in some cases. This is not an issue with TS but with VS.

**Comment by danquirk** [comment]
You'll probably want to file this issue specifically against NTVS: https://github.com/Microsoft/nodejstools
