### ISSUE TITLE
4.8 Regression - Array.isArray refines union to `any[] | object[]`

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#50561]
# Bug Report

### 🔎 Search Terms

Array.isArray any

### 🕗 Version & Regression Information

This regression was introduced in `4.8.2` - it was not present in `4.7.4`.
I also tested against nightly (`4.9.0-dev.20220830`) and it is still there.

### ⏯ Playground Link

- [4.7.4](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwCYQDKEAtsDABaYoDmAFBAEYBWAXHE88BnAD4ctuMANoBdAJTtGECABtgAQ1wBvAFBw4mBHDoBBKFAUBPAHSYAzvsNGGLceLhqNGzgG51cAPSe4APQD8HhpBcFDkSFC4nCbAAG7AUDYMDgC8AHyOIS7uzt5+gVn4RKTkVLTJIQC+4jlwlR5hMBG4MFBIwO6VQA)
- [4.8.2](https://www.typescriptlang.org/play?ts=4.8.2#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwCYQDKEAtsDABaYoDmAFBAEYBWAXHE88BnAD4ctuMANoBdAJTtGECABtgAQ1wBvAFBw4mBHDoBBKFAUBPAHSYAzvsNGGLceLhqNGzgG51cAPSe4APQD8HhpBcFDkSFC4nCbAAG7AUDYMDgC8AHyOIS7uzt5+gVn4RKTkVLTJIQC+4jlwlR5hMBG4MFBIwO6VQA)
- [nightly (4.9.0-dev.20220830)](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220830#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwCYQDKEAtsDABaYoDmAFBAEYBWAXHE88BnAD4ctuMANoBdAJTtGECABtgAQ1wBvAFBw4mBHDoBBKFAUBPAHSYAzvsNGGLceLhqNGzgG51cAPSe4APQD8HhpBcFDkSFC4nCbAAG7AUDYMDgC8AHyOIS7uzt5+gVn4RKTkVLTJIQC+4jlwlR5hMBG4MFBIwO6VQA)

### 💻 Code

```ts
export function doSomething(obj: object | object[]): boolean {
  if (Array.isArray(obj)) {
    obj;
  // ^? (1)
    
    return obj.every((o) => {
      o;
   // ^? (2)

      doSomething(o)
    });
  }
  return true;
}
```

### 🙁 Actual behavior

At marker (1) the type is `any[] | object[]`
At marker (2) the type is `any`

### 🙂 Expected behavior

At marker (1) the type is `object[]`
At marker (2) the type is `object`

---

This was reported to @typescript-eslint by a user - https://github.com/typescript-eslint/typescript-eslint/issues/5578

**Comment by ahejlsberg** [comment]
This is working as intended. `Array.isArray` returns `any[]` for an `object` (the object could be any array type) and `object[]` for an `object[]`, so it follows it should return `any[] | object[]` for an `object | object[]`. The pre-4.8 behavior was simply wrong.

**Comment by bradzacher** [comment]
Ah, I see what you mean. That's all good then.

Was this change mentioned in the release notes? I didn't see anything that seemed similar to this change mentioned.
