### ISSUE TITLE
`tsc --build` sometimes exits quickly without reporting errors, even when the TS being built is invalid

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/TypeScript#50568]
# Bug Report

This issue was originally posted as [a PR comment](https://github.com/microsoft/TypeScript/pull/48784#issuecomment-1232097847).

Possibly related: https://github.com/microsoft/TypeScript/issues/50545.

### 🔎 Search Terms

tsc build exit silent failure

### 🕗 Version & Regression Information

- This changed between versions ___4.7.3___ and ___4.8.2____

### ⏯ Playground Link / 💻 Code

This occurs in my 7.5k file monorepo. I'm able to work around this issue by using `tsc -p` instead of `tsc --build`, so I'm not going to invest in creating a minimal repro case. I know that makes it hard for you to investigate, so I don't expect much from filing this issue. I'm more doing it in case other people have the same problem. If enough people +1 it, then we can invest in finding a repro.

If you want to give me a `tsc` with additional logging to run, I'm happy to do that.

### 🙁 Actual behavior

When I run `tsc --build` on my TS project, I get no errors, even though they exist.

```
λ ./tools/tvui/node_modules/.bin/tsc -p packages/tsconfig.json 
# ... expected error messages omitted

Found 3 errors in 3 files.

Errors  Files
     1  node_modules/relay-hooks/lib/RelayHooksTypes.d.ts:56
     1  packages/@tvui/fx2-transition/src/utils.tsx:173
     1  packages/@tvui/redux/testing/unitTestingEnhancer.ts:8

tvui on  nth/ts-4.8 [!⇡] via  v16.16.0 took 10s 

λ time ./tools/tvui/node_modules/.bin/tsc --build packages/tsconfig.json --verbose
[3:52:58 PM] Projects in this build: 
    * packages/tsconfig.json

[3:52:58 PM] Project 'packages/tsconfig.json' is up to date but needs to update timestamps of output files that are older than input files


________________________________________________________
Executed in  550.41 millis    fish           external
   usr time  437.83 millis   50.00 micros  437.78 millis
   sys time  194.10 millis  616.00 micros  193.49 millis
```

I first noticed this after using yarn to update type-fest in node_modules.

### 🙂 Expected behavior

When I run `tsc --build` on my TS project, I get the same set of TS errors that `tsc -p` produces.

**Comment by sheetalkamat** [comment]
We really need more detailed information on how to reproduce this so we can investigate. Thanks

**Comment by NickHeiner** [comment]
Hi – as I mentioned in the original post, I don't intend to provide more details for this issue. I recognize that it's not actionable for y'all in the current state, but I'm leaving it here so if other people run into the same thing, we can consolidate observations and eventually converge on something actionable.

**Comment by sheetalkamat** [comment]
From your error it seems like it could be that build doesnt explicitly list that file so its not checked for uptodate ness check with `--b` and thats the known thing with `--build` so this very well could be working as intended and i am going to mark it as such. If and when you provide more information we could revisit this.
