### ISSUE TITLE
Allow to use value as type in some cases

### ISSUE THREAD

**Issue by buryndin** [microsoft/TypeScript#50564]
## 🔍 Search Terms
ts2747, Allow to use value as type

## ⭐ Suggestion

Allow to use value as type in some cases

## 💻 Use Cases

Sometimes it would be nice to have ability to use value as type:
```
class A {
    public static classname = 'A';
    public a: number = 2;
    classname = 'A';
    constructor (v: number) {
        this.a = v;
    }
}

class B {
    public static classname = 'B';
    public b: number = 2;
    classname = 'B';
    constructor (v: number) {
        this.b = v;
    }
}

const list = [new A(1), new A(2), new B(3), new A(4), new B(5)];

// first case
function findByType<T> (source: T[], type: Function): type { // 'type' refers to a value, but is being used as a type here.
    return source.find(e => e instanceof type);
}
console.log(findByType(list, A).a + findByType(list, B).b);


// second case
function isTypeOf<T> (source: T, type: Function): source is type { // 'type' refers to a value, but is being used as a type here.
    return (source as any).classname === (type as any).classname;
}
if (isTypeOf(list[0], A)) console.log(list[0].a);
```
This is a highly simplified example, but it shows how this feature can be used in real application.

**Comment by IllusionMH** [comment]
You should follow issue template.

There may be intersection between identifiers in types "scope" and values "scope", therefore it's not easier to get problems when values are used as types and vice versa.

Error message suggests correct fix - just write `typeof type` instead of plain `type`. Why it's problem to add explicit `typeof`?

TS would then report proper errors in your code In your code (after adding requested `typeof`).

**Comment by buryndin** [comment]
I need not a 'typeof'. I pass type as parameter and I want to use this type.
typeof A === 'function' - it is useless.
I understand that we cannot use type as value, because some kind of types ('type' or 'interface') does not exist in runtime(compiled js-code). But It seems using value as type is quite possible.

**Comment by IllusionMH** [comment]
Because you have explicit type `Function`. You should make that type generic (with constraint).

Also type of `type` is constructor type as you expect function and pass class constructor.
You should use `InstanceType<typeof type>` to get type you are looking for.

**Comment by fatcerberus** [comment]
> typeof A === 'function' - it is useless.

We're not talking about runtime `typeof`, we're talking about type-level `typeof`, which means "get the compile-time type of this variable":

```ts
let x: number = 42;
let y: typeof x = 812;
//  ^?
//  (number)
```

**Comment by fatcerberus** [comment]
```ts
function isTypeOf<T extends Function> (source: Function, type: T): source is typeof type {
    return (source as any).classname === (type as any).classname;
}
```

This works.  But of course at this point you might as well just write `source is T`.

**Comment by buryndin** [comment]
> You should use `InstanceType<typeof type>`
It is not working:
```ts
function findByType<T> (source: T[], type: Function): InstanceType<typeof type> { // error Type 'Function' does not satisfy the constraint ...
    return source.find(e => e instanceof type);
}
```
> ```ts
> function isTypeOf<T extends Function>(source: Function, type: T): source is typeof type {
>     return (source as any).classname === (type as any).classname;
> }
> ```

This is does not work also
```ts
function isTypeOf<T extends {}>(source: {}, type: T): source is typeof type {
    return (source as any).classname === (type as any).classname;
}
if (isTypeOf(list[0], A)) console.log(list[0].a); // Property 'a' does not exist on type 'B & typeof A'.
```

Please see my suggestion carefully: if predicate isTypeOf is true I expect that on the line 
```
if (isTypeOf(list[0], A)) console.log(list[0].a); 
```
typeof list[0]  = A

**Comment by MartinJohns** [comment]
```typescript
function isTypeOf<T extends new (...args: any) => any>(source: {}, type: T): source is InstanceType<T> {
    return (source as any).classname === (type as any).classname;
}
```

**Comment by IllusionMH** [comment]
> You should use InstanceType<typeof type>
> It is not working:

You've skipped first part where it should be generic, but as **wisecerberus** mentioned, in that case you can just use generic `T` type instead of `typeof type`. Or as posted above by **MartinJohns**

**Comment by fatcerberus** [comment]
> if predicate isTypeOf is true I expect that ... typeof list[0] = A

That's literally just `list[0] instanceof A`.  Martin's version is the correct way to implement your custom version.

**Comment by buryndin** [comment]
Sorry guys, I forgot about generic. Thank's a lot for your help. Issue can be closed.
