### ISSUE TITLE
Problem with "File name ... differs from already included file name ... only in casing"

### ISSUE THREAD

**Issue by akphi** [microsoft/TypeScript#50569]
# Bug Report

### 🔎 Search Terms

`File differs from already included file only in casing`, `only in casing`, `File differs`

### 🕗 Version & Regression Information

This changed between version `4.7.4` and `4.8.2`. I tested with `4.8.1-rc` and it still works fine, so maybe something happened in `4.8.2`

### 💻 Code

This is my repro branch
https://github.com/akphi/issue-repo/pull/9

> If I have to speculate, the particular thing about my setup is I use `module: NodeNext` and `forceConsistentCasingInFileNames: true` and in `src` folder, I have 2 files: (1) imports something from a library package (e.g. `serializr`) and (2) imports something from a package that has `serializr` as a dependency) (note that I already tested with other packages to make sure it doesn't only happen to`serilizr`).
> (2) imports from `@finos/legend-shared`, a package that ships ESM code. Really sorry about this complexity in the setup, I have tried my best to reduce the size of the repro 🙏. But this is crucial for our setup: basically, we have a codebase that publishes `@finos/legend-shared` - an utility only library and consume that in another codebase, hence when I bump into this error 

To reproduce the issue, run the following:

```sh
npm install && npm run dev:ts
```

### 🙁 Actual behavior

I got the error

```
src/index.ts:1:27 - error TS1149: File name '/Users/my-user/Developer/js/issue-repo/node_modules/serializr/lib/serializr.d.ts' differs from already included file name '/users/my-user/developer/js/issue-repo/node_modules/serializr/lib/serializr.d.ts' only in casing.
  The file is in the program because:
    Imported via 'serializr' from file '/users/my-user/developer/js/issue-repo/node_modules/@finos/legend-shared/lib/application/SerializationUtils.d.ts' with packageId 'serializr/lib/serializr.d.ts@2.0.5'
    Imported via "./serializr" from file '/users/my-user/developer/js/issue-repo/node_modules/serializr/lib/constants.d.ts' with packageId 'serializr/lib/serializr.d.ts@2.0.5'
    Imported via "serializr" from file '/Users/my-user/Developer/js/issue-repo/src/index.ts' with packageId 'serializr/lib/serializr.d.ts@2.0.5'
  File is CommonJS module because '/users/my-user/developer/js/issue-repo/node_modules/serializr/package.json' does not have field "type"

1 import { serialize } from "serializr";
                            ~~~~~~~~~~~
```

As you can see in my `src/index.ts` file

```ts
import { serialize } from "serializr";
export { default as hashObject } from "object-hash";
import { cloneDeep } from "lodash-es";
```

This also fails for `object-hash` and `lodash-es`.

### 🙂 Expected behavior

This should compile fine.

**Comment by fatcerberus** [comment]
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/50544

**Comment by MartinJohns** [comment]
Duplicate of #50544.

**Comment by akphi** [comment]
Just to point out a small difference, I looked at #50544 they claim this doesn't work for all versions they tried, I only see this manifesting post `4.8.1-rc`

**Comment by MartinJohns** [comment]
> they claim this doesn't work for all versions they tried, I only see this manifesting post `4.8.1-rc`

It's part of the issue template, and too many people don't fill it out correctly. It's safe to assume they just tried a single version.

**Comment by alecmev** [comment]
Sorry, indeed, I didn't test on earlier versions, assumed it was present in all relevant versions because it coincided with us enabling `moduleResolution: Node16`, but looks like it's a recent regression after all.

**Comment by akphi** [comment]
Closing this as https://github.com/microsoft/TypeScript/pull/50557 has been merged. Thanks @sheetalkamat !

**Comment by laplacetw** [comment]
Is this problem has been resolved ? Even though upgrade to the latest, here is the same problem on Rocky Linux 9 but running well on Windows 11.
