### ISSUE TITLE
Overloaded indexed type isn't initializable with an object literal

### ISSUE THREAD

**Issue by indutny-signal** [microsoft/TypeScript#50575]
# Bug Report

### 🔎 Search Terms

"Overloaded indexed type"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDeAoK6DaBrCIBcUAzsAE4CWAdgOYC6BSUAhgRQK4C2ARhCQNxQBfFAKgAyZGnRRO9aSw7cSA3sJQoANhGBQAHgTiJUUprOZQAjIIA0k9DORyL11UA)

### 💻 Code

```ts
type X = {
   [key: string]: { a: number; }
} & {
    b: { b: number};
}

let x: X = {
    a: { a: 1 },
    b: { b: 1 },
}
```

### 🙁 Actual behavior

Type error:

```
Type '{ a: { a: number; }; b: { b: number; }; }' is not assignable to type 'X'.
  Type '{ a: { a: number; }; b: { b: number; }; }' is not assignable to type '{ [key: string]: { a: number; }; }'.
    Property 'b' is incompatible with index signature.
      Property 'a' is missing in type '{ b: number; }' but required in type '{ a: number; }'.
```

### 🙂 Expected behavior

No type error

**Comment by jcalz** [comment]
The term "overloaded indexed type" doesn't really convey what you're doing.  The behavior here is working as intended.  

It looks like you're trying to write a "rest index signature" type as requested in #17867 (and mentioned [in SO here](https://stackoverflow.com/q/61431397/2887218)), and unfortunately there's not really any great way to do it.  An intersection is okay-ish to read from but you can't easily initialize it, as you can see.
