### ISSUE TITLE
jake local fails

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#5057]
Hi,
  since I have a few issues with tsx inside vs, I would like to use the latest language service instead of the packaged one to see if something is different.
  I updated my typescript clone and launched **jake local** (I have already done this in the last months) but this time fails:
  if I run from a command shell I obtain this error message

>jake aborted.
>Error: Cannot find module 'tslint'
>    at Function.Module._resolveFilename (module.js:336:15)
>    at Function.Module._load (module.js:278:25)
>(See full trace by running task with --trace)

if I run from powershell

>module.js:338
>    throw err;
>          ^
>Error: Cannot find module 'lru-cache'
>    at Function.Module._resolveFilename (module.js:336:15)
>    at Function.Module._load (module.js:278:25)
>    at Module.require (module.js:365:17)
>    at require (module.js:384:17)
>    at D:\GitHub\typescript\node_modules\jake\node_modules\filelist\node_modules\minimatch\minimatch.js:35:11
>    at Object.<anonymous> (D:\GitHub\typescript\node_modules\jake\node_modules\filelist\node_modules\minimatch\minimatch.js:1057:3)
>    at Module._compile (module.js:460:26)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)

This is the first time I see something similar. Am I missing something?

**Comment by danquirk** [comment]
Run 'npm install' to update the necessary dependencies.

**Comment by lucamorelli** [comment]
looks like it solved, but I don't understand why works fine from a powershell admin console and not from a cmd admin console

**Comment by DanielRosenwasser** [comment]
@weswigham does `&&` execute conditionally in PowerShell?

**Comment by weswigham** [comment]
`&&` was removed from powershell as a valid deliminator recently, I think. You have to use `;` instead.

**Comment by DanielRosenwasser** [comment]
Awesome. Is there anything we can do to fix this now?

**Comment by weswigham** [comment]
Cross-shell compatibility has never been easy... ahh... `|` I believe is supported on most shells, which could work if everything that needs to be run doesn't care about the output of the prior process...

**Comment by weswigham** [comment]
@DanielRosenwasser But his question why why it worked in powershell but not in cmd, so I'm not sure it's important.

**Comment by DanielRosenwasser** [comment]
Why wouldn't it have been important? This means that in PowerShell it wasn't explicitly failing because `tslint` wasn't present.

**Comment by weswigham** [comment]
Looking at his stack traces, the different is that in powershell he was never even able to load `jake` from the local node_modules dir whereas in `cmd` he had at least gotten `jake` installed and started to read the jakefile before it got to the missing tslint dependency.

**Comment by weswigham** [comment]
I don't see anything there that would have anything to do with a `&&` at all.

**Comment by weswigham** [comment]
@DanielRosenwasser Also, TIL `;` is a valid separator in bash. I've always used `&&`.
