### ISSUE TITLE
Type Union Throwing An Error For Optional Property

### ISSUE THREAD

**Issue by jvanderen1** [microsoft/TypeScript#50579]
# Bug Report

### 🔎 Search Terms

- Type Mixed with Different Objects
- Union with Optional Type
- Union with Optional Property

### 🕗 Version & Regression Information

I currently see this issue running `typescript: 4.8.2`. I also notice this issue on TS Playground version `4.8.0-beta`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/PQ1-AsAUCAEAVAngBwKZwMpoC4FcU4QYJTQYYdUMA1NAJwGcBLAewDs4BeOAbxjhwAbgxYcAXHEY56zdgHMYAXwrQq6OAGFWAWxQBDWYw4B5dPX05W9bnADkAPjtwAPva7O3jj6-sAeT38PVXUMADkUHTMGS2tbOwA9QLsAPzsQ6jg6JjZ2ACV9BQwuAV9ssU4AMlLBQQAKXjgAY10DIwktVsNmY3Zoiyt6ABpmrvb2THwAMymAfklpWQU4JV9G9kjJCKjzWOG4DZ1JvBn5qRk5eRWASlUye-JYYDgAIXpWAGs0TgBRAA99HoADYYYhPB5kVRTPDsJo4XJwKasVh1a6Scq5ApFPilei4PD0Tj8aC1YSiXKSOwARgAdAAGel2IY1UZ6bq9SkeZkklbKVQtdjSOAAI0MtiRKNu0GYUzgdVF9BpLTZ42uOJ58AAIqwpLpcAALS5wADuzBw+rgAANlW0ehxLco4GggYwMDK5QqaYc1cTBFqdcYdAajabzVbDg7oCpoEA)

### 💻 Code

```ts
////////////////
// Type Setup //
////////////////

type Version = {
  version: string
}

type ComparisonOperator = '>' | '=' | '>=' | '<' | '<='

type NpmOperator = '^' | '~'

type VersionRange =
  | Version &
      ({ comparison: ComparisonOperator, comparisonStuff?: string } | { npm: NpmOperator, npmStuff?: string })

////////////////////
// Broken Example //
////////////////////

function foo(): VersionRange {
  return {
    version: '1.0.0',
    comparison: '=',
  }
}

const bar = foo()
if (bar.comparison) {
  // Do something with `comparison`
} else if (bar.npm) {
  // Do something with `npm`
}
```

### 🙁 Actual behavior

There is an error on `bar.comparison` and `bar.npm`. While these don't exist on `Version`, one of them will exist on `VersionRange`, so I need some way to check for the existence of one of these properties.

If there is a utility or TS syntactic sugar I can add, I would be okay with that. But not even the [`non-null operator`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) is avoiding these errors.

### 🙂 Expected behavior

No errors on checks with `bar.comparison` or `bar.npm`.

**Comment by MartinJohns** [comment]
This is working as intended. You can only access properties that are present on all union types. See #50495 and others.

**Comment by jvanderen1** [comment]
@MartinJohns Thanks for the swift response 💯.

That's a bummer. I'm using some Regex to parse some strings using naming groups. Depending on if there's a Regex match for a `comparison` operator or an `npm` operator, I'd like to do different things.

I'll think about how to structure this. Much appreciated.

**Comment by fatcerberus** [comment]
@MartinJohns beat me to the punch on a 15-minute-old issue?  What is this sorcery?!

**Comment by guillaumebrunerie** [comment]
@jvanderen1 Discriminated unions usually make this kind of pattern much easier to work with in my experience.

Here is how your code could be rewritten, adding a `kind` field:
```typescript
type VersionRange =
  | Version &
      ({ kind: "comparison", comparison: ComparisonOperator, comparisonStuff?: string } | { kind: "npm", npm: NpmOperator, npmStuff?: string })

/////////////////////
// Working Example //
/////////////////////

function foo(): VersionRange {
  return {
    kind: "comparison",
    version: '1.0.0',
    comparison: '=',
  }
}

const bar = foo()
if (bar.kind === "comparison") {
  // Do something with `comparison`
} else if (bar.kind === "npm") {
  // Do something with `npm`
}
```
Another advantage is that there is no ambiguity anymore if an object would happen to have both a `comparison` and an `npm` field (in your original code the behavior would depend on the ordering of the `if` statements).
