### ISSUE TITLE
 TS1005: ',' expected  

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#50585]
# Bug Report

### 🔎 Search Terms
 TS1005: ',' expected

### 🕗 Version & Regression Information

version 4.6.4
- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

```ts
declare function useLocalStorage<T>(initialValue: T, storageKey: string | undefined, syncFromOther?: boolean): [
    localHistory: T,
    setLocalHistoryFn: (val: T) => void,
    updateLocalStorageKey: (key: string) => void  // TS1005: ',' expected.
];
```
### 🙂 Expected behavior
how to disable this kind of check, it's not useful  and has nothing to do with the logic

**Comment by MartinJohns** [comment]
Your issue does not reproduce. [Playgroud link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX2QGcQAZHMKCAZQxxigHMQAeAFQD4AKLVLbSgGqVkIAFzxWAGniFa9JgGkQAT3GyYPBvAA+BVKEQ8QwaYWXoAYjBwBbAPIYAFiBgB+cQCMcOCCCioASnEAbQBYACh4KPgIckoACSxZOlUJSQjomRAMMgoIROSYZQtUcU4AN0pxVgD4AF52eHKcLBMM6OQAB2AoDFI46jlGECVUzgBrFTUMDVQGWoamluAogHpViSoARgAGHYBWcQBySSP4EAAPTvA+4AA6CIBdAG4IoA) (which you omitted).
