### ISSUE TITLE
Extends behaves differently for generics than hard-coded union

### ISSUE THREAD

**Issue by NoelDeMartin** [microsoft/TypeScript#50584]
# Bug Report

### 🔎 Search Terms

extends, union, generics 

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about `extends`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogHsCA7AJgZwOoEtgAsDiyEATlgMYA8AKgHxQC8UVUECy6UAjFAPxTDEArtABcUAGYBDADZoIAbgBQoSFABKENIOnBujeIlSYcBIqUrcAPlABMUawGYaSldA1addxgAort+1AOAJQsbEZcvPxCohIyckqKAPSJTLhYaFBouAD22ihQSNnAsVjSyuDQVJrF+nCQZMAUMACOgnEU7tq6ADTqml02NM6KSSkAgoJwpViSxPwVGeLZc4howGgAdFvlqvD1jcyshhwCwnSMVC4VsK3tABq9AJrnilBvUN7UNN4h9HSHYQ4d0i3DENhCR3YaFe70+tB+DH+oWOGUeIKgYJCfFOMSksgUiiAA)

### 💻 Code

```ts
// This result yields "boolean", I guess from "true | false | false"
type ExtendsWithGeneric<T> = T extends 1 ? true : false;
type Result1 = ExtendsWithGeneric<1 | 2 | 3>;

// This result yields "false"
type Result2 = (1 | 2 | 3) extends 1 ? true : false;
```

### 🙁 Actual behavior

Results differ if a union is passed through a generic or hard-coded.

### 🙂 Expected behavior

I think both results should yield the same value.

In case this is not a bug, I'd appreciate understanding what's the difference here and maybe we can add it to [Common "Bugs" That Aren't Bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs).

**Comment by IllusionMH** [comment]
That's mentioned in docs https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

Conditional types are distributive only when used in generic type.

**Comment by NoelDeMartin** [comment]
I see! That does clear things up, hopefully if anybody else runs into this problem they'll find this issue :). Closing.
