### ISSUE TITLE
optimize optional chaining compile

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#50582]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

evaluate the type before optional chaining, if it's a `string` type for example, just generate code like `(a.b || '')`

avoid generate lots of ternary expression that make codebase bloated

## 📃 Motivating Example

![image](https://user-images.githubusercontent.com/49113249/187871976-99c036bf-f208-43c4-a6d5-69a9486f11c2.png)

## 💻 Use Cases

```ts
 const a= {
     b:''
 }
// 1. specific api call like String.prototype api
// maybe the most useful use case
 console.log(a.b?.slice())   --->  (a.b || '').slice


// 2. get value（maybe a breaking change since undefined --> '' empty string）
<div>{a?.b}</div>   ---> <div>{(a.b || '')}</div>  
```

**Comment by MartinJohns** [comment]
>  console.log(a.b?.slice())   --->  (a.b || '').slice

These have different results. `a.b?.slice()` results in `undefined` if `a.b` is nullish, and `(a.b || '').slice()` results in an empty string.

**Comment by HomyeeKing** [comment]
fair enough, maybe the developer should constraint it by self
