### ISSUE TITLE
Error.cause should have type unknown

### ISSUE THREAD

**Issue by Janpot** [microsoft/TypeScript#50583]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2022` and my *lib* is `the default`.

## Missing / Incorrect Definition

`cause` property on the `Error` object should have type `unknown` instead of `Error`.

## Sample Code

The [example from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#providing_structured_data_as_the_error_cause):

```tsx
function makeRSA(p, q) {
  if (!Number.isInteger(p) || !Number.isInteger(q)) {
    throw new Error('RSA key generation requires integer inputs.', {
      cause: { code: 'NonInteger', value: [p, q] },
    });
  }
  if (!areCoprime(p, q)) {
    throw new Error('RSA key generation requires two co-prime integers.', {
      cause: { code: 'NonCoprime', values: [p, q] },
    })
  }
  // rsa algorithm…
}
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause#providing_structured_data_as_the_error_cause

**Comment by MartinJohns** [comment]
Good news: It is `unknown`! At least in the nightly version. This issue is a duplicate of #48098 and it has been fixed already in TypeScript 4.9.

**Comment by Janpot** [comment]
Geat!

**Comment by MartinJohns** [comment]
Geat indeed!
