### ISSUE TITLE
@ts-nocheck does not disable TS language server for file

### ISSUE THREAD

**Issue by redbar0n** [microsoft/TypeScript#50587]
**The expectation when adding `// @ts-nocheck` to a file is that the TS language server stays completely away from that file.** Ideally it would do that regardless of file extension or no file extension, but at least for the extensions: .js .ts .jsx .tsx

Tested using the latest Insiders build: **1.71.0-insider (Universal)**

Does this issue occur when all extensions are disabled?:  **Yes**

- VS Code Version: 4.7.3
- OS Version: -

**Steps to Reproduce:**

Create a new file (CMD+N) and paste in either of these examples:

---
Example 1:

```
// @ts-nocheck

<Component someProp={true} />

<OtherComponent />
```

It gives the red squiggly error: `JSX expressions must have one parent element. ts(2657)`
If it is auto-detected (or saved) as a JS file. 

If it is saved as a TS file it gives the red squiggly errors: `'>' expected. ts(1005)` and `Unterminated regular expression literal. ts(1161)` and on the last line `Expression expected. ts(1109)`.

---
Example 2:

```
// @ts-nocheck

<Component someProp={true} />
```
It gives the red squiggly error: `'>' expected. ts(1005)` and `Unterminated regular expression literal. ts(1161)`
It's auto-detected as a TS file.

---

Potentially related issues: https://github.com/microsoft/vscode/issues/74151 and https://github.com/microsoft/TypeScript/issues/26887 and https://github.com/microsoft/TypeScript/issues/47315

But this bug seems to be related to how VS Code handles the TS server, not with TS itself.

Doing CMD+SHIFT+P then `>TypeScript: Restart TS server` in VS Code will have all the red squiggly lines disappear and reappear. 

Also, if there had been a `>TypeScript: Stop TS server` option in VS Code, then `// @ts-nocheck` not fully working as expected wouldn't have been so much of a problem... (I don't want to disable TS completely in my config, since I need it for other files/projects).

**Comment by RyanCavanaugh** [comment]
`ts-nocheck` doesn't mean that. It basically means "suppress type errors". You'd need to set the VS Code Language Mode to something else or otherwise tell VS Code to not treat this as something TypeScript should be providing errors on.

**Comment by redbar0n** [comment]
Ok, I thought `@ts-nocheck` meant that TS would not check and thus not give any errors..

The [ts doc](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#-ts-nocheck-in-typescript-files) simply says it would _"disable semantic checks"_, which I think is fair to assume includes any _errors, warnings and suggestions_ beside mere type errors.

But how do I tell VS Code to not treat a specific file as something TS should be providing errors on, then?

I do want to keep the normal syntax highlighting (from the auto detected Language Mode).

**Comment by fatcerberus** [comment]
The errors you say you’re seeing are syntax errors (unterminated expressions, invalid JSX tag structure, etc.), so don’t fall under “semantic checks” - the code is meaningless.  A semantic error would be one where the code has meaning, but makes no sense, most commonly a type error.

it’s sort of like the distinction between “you violated our contract” vs. “this can’t happen in our reality” 😄

**Comment by redbar0n** [comment]
Ok, how do I disable TS syntax checking for a specific file then?

**Comment by jakebailey** [comment]
You could change its extension to be not ts/tsx, if the files aren't valid code.

FWIW the TS project has certain test files which are syntactically invalid JS (they contain .ts and .dts contents), but have the extension .js; we just ignore the errors.

**Comment by redbar0n** [comment]
That's the thing, as per my listed examples, in a new window they don't even have a file extension (or are potentially saved without one). Also, the problem persists even when saving the extension to `.js` or `.jsx` because TS is generally set to check even JS files (which I generally want it to do as well, just not for specific files).

So how do I completely opt out of TS doing any kind of checking for a specific file? I thought that would be by virtue of `@ts-nocheck`, but it only gets me half-way there...

**Comment by fatcerberus** [comment]
I don’t understand why you’d want to opt out of checking for invalid/malformed code.  Unless you have `checkJs` turned on for your project (which `@ts-nocheck` would opt you out of), the only errors TS should pick up on in `.js` files are ones that would prevent the code from running *at all*.

**Comment by redbar0n** [comment]
It's for writing and experimentation. I often write some code out in VS Code when trying to test out ideas for myself, or for communicating something to others (code structure etc.). Bits and pieces of code interspersed with commented out lines. I benefit from the regular syntax highlighting, but not from the TS errors.

**Comment by redbar0n** [comment]
Other use cases:
_"Sometime, though, the language server can get it wrong. You are using a feature that's too new. You depend on a library unknown to the server. Or that you are writing buggy code intentionally."_ from https://github.com/microsoft/TypeScript/issues/47315

@RyanCavanaugh I'd say it's a pretty common conception that `// @ts-nocheck` and `// @ts-ignore` acts on the TS server as a whole, and  should affect all kinds of checking done by it  (syntactic or semantic, resulting in any kind of error or suggestion), not merely type checking.

Even the TS documentation often indicates that they let you ignore all TS errors:

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments

https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html#ts-check

**Comment by jakebailey** [comment]
> That's the thing, as per my listed examples, in a new window they don't even have a file extension (or are potentially saved without one). 

Are you in VS Code? Recent versions use AI magic to detect the language of new files based on their content. If you're pasting code into an untitled file, check the language that's detected at the bottom right.

**Comment by jakebailey** [comment]
Ah, yes, scrolling up, that is exactly what is happening.

**Comment by fatcerberus** [comment]
> Recent versions use AI magic to detect the language of new files based on their content.

It strikes me that modern AI is like [Clippy](https://en.wikipedia.org/wiki/Office_Assistant) but way pushier.  "It looks like you're writing a letter.  Don't mind me, I'll just go ahead and insert this whole letterhead for you..."

**Comment by redbar0n** [comment]
Yes, although I don't mind the language auto detection, as I enjoy the syntax highlighting. Just not all the red squiggly lines. So I'd like to turn them off for that file.

**Comment by jakebailey** [comment]
You could feasibly change the language back to plaintext, or disable the feature. I know I'm guilty of using tricks like pasting code into notepad first so VS Code doesn't know from which file/language the code I copied came from (which k often do when saving snippets for a rainy day).

**Comment by jakebailey** [comment]
To be clear, if you're copying code from an existing tab, VS Code will remember the language of the file the code was copied from, and then make the untitled file have that language on first paste. This behavior is older than the AI one I'm talking about. But, in any case, this is VS Code trickery, where normally these files would not be given to the TypeScript server at all.

**Comment by fatcerberus** [comment]
@jakebailey He wants the syntax highlighting without the error squigglies, so presumably setting the file to plaintext isn’t an option.

**Comment by redbar0n** [comment]
The problem is that plaintext loses the syntax highlighting, and disabling TS or JS validation altogether are config options I don't want to risk, due to needing it for other files in my projects.

**Comment by redbar0n** [comment]
Can someone please reopen? The intention behind the existing feature is causing problems, since it's arguably not well aligned with user intentions/expectations.

**Comment by timjdale** [comment]
Yep, very irritating.
Workaround:
Select "coffeescript" (or something silmilar to .js you don't use / lint) in the Select Language Mode.
Syntax highlighting's good enough (bracket pairs etc OK); red-squigglies gone.

**Comment by RyanCavanaugh** [comment]
This is still the intended behavior. Completely ignoring files with `no-check` would degrade other users' currently-working experiences -- for example, you wouldn't be able to auto-import, or get typing completion, from a file marked with this comment.
