### ISSUE TITLE
VSCode not respects the TSConfig & npm `exports` rules

### ISSUE THREAD

**Issue by dalisoft** [microsoft/TypeScript#50595]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.70.2
- OS Version: macOS 11.6.8 (20G730)

## Steps to Reproduce:

1. Clone https://github.com/dalisoft/vscode-workspace-bug
2. Open `backend` folder inside this workspace (**not `*.code-workspace` file**)
3. Try to import `getUserId` with IntelliSense

## Excepted

`import { getUserId } from "@shared/api/auth"`

## Actual 

`import { getUserId } from "@shared/api/src/auth"`

## Note

- This rule respects WebStorm and works their Smart IDE function fine with imports (hover info) and etc pluses, so cause bug only related to VSCode

**Comment by jakebailey** [comment]
The moduleResolution mode you have is "node", which IIRC doesn't do export mapping like this; that would imply that maybe you could use "node16" or "nodenext", however in your case, I don't believe that your project is targeting Node at all, but the browser, so setting those is likely to break your code.

It seems to me like this is something that'd be handled by a new resolution mode as introduced in #50152.

**Comment by dalisoft** [comment]
@jakebailey Yes, it is right. Changing to `node16` solves invalid `src` path and works. See [changes](https://github.com/dalisoft/vscode-workspace-bug/commit/5564696badac050c8a438ecb2589320ff3cff0ba#diff-daf10ced45c44425a4d2715a47ddb1f2899351e0c99fc52500233d3b5bd39b72R7-R16)
But there a catch, it requires always `/index.js` which is i am don't want always being added to imports. It's can be avoided?

**Comment by jakebailey** [comment]
Technically you could write your export maps explicitly to list out extensionless names, but this is why I said that it'd break your code; this resolution mode isn't really the right thing when you aren't expecting your code to run on Node.

**Comment by dalisoft** [comment]
@jakebailey Thanks for reply. My code from `api-shared` and `backend` expects to be runned on Node. Only `ui-shared` and `frontend` for browser so it is should not be issue. Can you give me examples how to add back again support for importing directory without `./index.js` suffix without manually specifing (like `require` and `old behavior`)?

**Comment by dalisoft** [comment]
@jakebailey Additional tests. Actually code works but IntelliSense does not works without `./index.js` suffix

**Comment by andrewbranch** [comment]
> But there a catch, it requires always `/index.js` which is i am don't want always being added to imports.

You are in the exact situation I described in th #50152 under the heading “Bundling with Webpack, esbuild, or Vite.”

You don’t want to use `node16` right now. Your workaround in the meantime should be to add `typesVersions` along with `exports`. So:

```json
{
  "exports": {
    "./*": "./src/*",
    "./auth/*": "./src/auth/*"
  },
  "typesVersions": {
    "*": {
      "./*": "./src/*",
      "./auth/*": "./src/auth/*"
    }
  }
}
```

That will allow the same mapping to work with `--moduleResolution node`.

**Comment by dalisoft** [comment]
@andrewbranch Thanks for reply but the workaround does not work and again i cannot get work "Go to Definition" function

**Comment by andrewbranch** [comment]
@dalisoft I meant to put the filenames in an array, my bad. But your config is all over the place. I fixed it for you. https://github.com/dalisoft/vscode-workspace-bug/compare/master...andrewbranch:vscode-workspace-bug:master

**Comment by dalisoft** [comment]
@andrewbranch Thank you a lot for writing these config for me. I see not required too much change but i'm better with `node16` rather than manually adding folders index.js as exports as on mid-level projects it's can be a lot (100+ if not more).

So, it's i don't know then close this issue or not as `node16` or manually adding to exports solving this issue (yep, workaround, but not non-fixable)

**Comment by dalisoft** [comment]
Marking this as solved and added [note](https://github.com/dalisoft/vscode-workspace-bug#intellisense-wrong-import-path) on repo
