### ISSUE TITLE
Narrowing works incorrectly when destructuring

### ISSUE THREAD

**Issue by tatomyr** [microsoft/TypeScript#50604]
# Bug Report

### 🔎 Search Terms

destructure, union, narrowing

### 🕗 Version & Regression Information

`v.4.7.4`, `v4.8.0-beta`.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBATgUwLYgG4IBowLwwDwAqANDBgHwAUA3gB4kB0ji0AvgFwwEwBkMtHGFgEoOXbGXgJoAKCA)

### 💻 Code

```ts
const removeX = <T, X>({x, ...rest}: T & {x: X}): T => rest
```

### 🙁 Actual behavior

It produces the following error:

```
Type 'Omit<T & { x: X; }, "x">' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'Omit<T & { x: X; }, "x">'.
```

### 🙂 Expected behavior

There should be no error since `Omit<T & { x: X; }, "x">` is essentially equal to `T`.

**Comment by IllusionMH** [comment]
Not if `T` contains property `x`. Then `rest` wont match `T` exactly.

**Comment by tatomyr** [comment]
Well, that's the part I'd expect Typescript to figure out for me that `T` does not contain `x` as I'm extracting it from whatever type is coming into my function.

**Comment by fatcerberus** [comment]
The return value is guaranteed not to contain property `x`.  This is *not* guaranteed of `T`, because you can supply type parameters explicitly.  It's a common mistake to write generic functions assuming the type parameter(s) are always inferred, but the compiler knows better.

**Comment by jakebailey** [comment]
Perhaps this is sufficient for your use case?

```ts
function removeX<T extends Record<string, any>>({x, ...rest}: T): Omit<T, "x"> {
    return rest;
}
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.4&ssl=1&ssc=28&pln=1&pc=47#code/GYVwdgxgLglg9mABAJwKYFs4DdUA0A8AKoqgB5SpgAmAzogEqoRzJX41TIxgDmANIgCGYAJ4A+MQAoA3qQEA6RWg4BfAFyJCASg0B5dDChEBAIlImxiaQChEdlKighkSZVADc1ldZ-cKyYEEIVEQAQStbexENDi5eT29rZjAOIUQAXgdMHAJQqWloxBMAC1QRExUtT0F5EU8fZNSAIwys7DwZQpKyiqrrJtr6pIRUiFa0bI7ZDQBGACYAZgAWAS7S8srPCHlSLcGfIA)

**Comment by tatomyr** [comment]
Thanks all for the explanations!
Now I see what the point is.
