### ISSUE TITLE
Completion inside interface has inconsistent behavior

### ISSUE THREAD

**Issue by yuit** [microsoft/TypeScript#5060]
There is no completion shows up on the first property declaration in an interface
![nocompletiononthefirstline](https://cloud.githubusercontent.com/assets/489742/10234261/2fd9146e-6848-11e5-84d9-08b73c7b1d9c.gif)

which is fine if it is consistent with the rest. However, we do give completion on the second property declaration.
![autocompletionafterparen](https://cloud.githubusercontent.com/assets/489742/10234585/75ea46d8-684a-11e5-849d-4ae494eca7de.gif)

**Comment by laluali** [comment]
This could be IDE dependent, I don't find this issue valid on 
WebStorm 2020.3.3
Build #WS-203.7717.59, built on March 15, 2021
