### ISSUE TITLE
Sharp notation do not allow decorator ..

### ISSUE THREAD

**Issue by anymos** [microsoft/TypeScript#50602]
# Bug Report

### 🔎 Search Terms

Sharp notation method decorator

### 🕗 Version & Regression Information

Trying to use decorators

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

@Decorator()
#method

### 🙁 Actual behavior

TS1206: Decorators are not valid here

### 🙂 Expected behavior

Decorators shall works

**Comment by MartinJohns** [comment]
You forgot to provide a valid playground link and a self-sufficient code example.

**Comment by Jamesernator** [comment]
> Sharp notation method decorator

Private fields/methods/accessors don't support decorators, because the current implementation of decorators in TypeScript is based on a **very old** version of the decorators proposal, that old proposal doesn't really integrate properly with private fields.

The [current decorators proposal](https://github.com/tc39/proposal-decorators) actually has implementers support, and does support private fields/methods/accessors. There's currently an effort to support the current proposal [in typescript](https://github.com/microsoft/TypeScript/issues/48885). However do note that old decorators can't be used in the new decorators proposal, so any such decorators would need be rewritten for the new proposal.

**Comment by jakebailey** [comment]
Here's an example for posterity: [Playground Link](https://www.typescriptlang.org/play?target=2#code/GYVwdgxgLglg9mABMGAnAzlAFASkQbwFgAoRRCBdOAGwFMA6auAcywCIUNscAuZAQ2hxUAT0S0Abv2oh+UWgBM2OANwkyqWlBCokoSLASIsUfqmZa+-MCIA0iAA6o4D2qigiA0rRF9MqGDBmewVadAgAhyhhPgAFZ1d3EQARMIiYKOE8IlIyckoaBiZWDjRMXD4IaTolVXVEAF81Ygb1En1oeCR0WgowBVwCer6qOkYWdh6+gd4BIVFxKRk5RWVmjS0dPXBOoxMzCygrG3snFzcPb19Ef0DgxFDwyOjUOISLlLTnrKHcshHCuMSlMEDNKtVVnVck0SK1SCQINR+Oh0IgAKIAD34AFsHHQAMJIlG-MgAAU45Rw9VJIP6uHq2K0AAs4DMCHDqRTuNTaTN6gBiRlQFls-BwuFAA)

Decorators as they exist now (we implemented an old spec and are stuck with it) don't work on private fields. I don't think this is something we're going to support. If we don't downlevel the private field to the `WeakMap` implementation, there's no way that we could put our experimental decorators on it.

There is #49705, which _does_ support `--experimentalDecorators` on _accessors_, which is different and possible, as the PR shows. Once the new, revised decorators spec is ratified, then we'll have a clear path.

**Comment by anymos** [comment]
understood, thank you very much fro the detailed answer, I was naively thinking that decorator would works ootb on private method.

A pity really as it limits the decorator fields a lot from my perspective.

**Comment by anymos** [comment]
By the way, it sounds lie it is working when using a // @ts-ignore, ofc it s probably kind of a luck and it works too on private method.

So now I am looking for a way to ignore the TS1206 - decorator not allowed here in tsconfig.json, is there a way to obtain this ? so I can use the feature that is not supposed to work ( lucky me) without having to add so many ts-ignore ? - finger crossed

**Comment by jakebailey** [comment]
If it's working, that's a fluke; my playground link above shows that the decorators are not applied to the method named with a private identifier, even when we downlevel it into a WeakMap. If you have it working, I'm curious, but `// @ts-ignore` is definitely a bad idea.

**Comment by anymos** [comment]
> If it's working, that's a fluke; my playground link above shows that the decorators are not applied to the method named with a private identifier, even when we downlevel it into a WeakMap. If you have it working, I'm curious, but `// @ts-ignore` is definitely a bad idea.

I agree it is a bad idea and probably not going ot work for ever, you can try it on your side just run a get started angular project and it works out of the box at least in angular 13, did not tried in angular 14 yet.

when it will stop to work, but you know like me that temporary and fluke thing can takes years to stop to works ;-) then maybe Typescript will have something to replace it, or who now maybe decorator on private methods will work - like it shall my only opinion here - In the mean time, could you kindly tell me if there is a way to globaly ignore the TS1206 maybe in tsconfig ? probably that it is not possible and that would make sense as a 'bad' thing to do - I agree again here, but I know and accept the risks in my case :)

In the man time is there a better way to replace the decorator on private method in 2022 ? maybe by coding a particular proxy on the class itself. The pb is that I use those decorator to provide extremely usefull logging capability so I need it for each of the method in the code, it is not just for one or a few of the private methods.

Making those method public would solve the issue, but I believe it is even worse than using the 'fluke' of it working on the private methods.

All ears to find a proper/better solution :)

**Comment by jakebailey** [comment]
The better solution is to just wait for ECMAScript decorators, i.e. #50820.

**Comment by anymos** [comment]
Agreed, do you have any idea of the timeline ? even years will not make me scared or cry do not worry ;-) just to have an idea, I was not following much the typescript evolutions until now as it was always fitting my needs until that edge case

**Comment by MartinJohns** [comment]
@anymos Decorator support is part of the 4.9 iteration plan, so likely in November. #50457

**Comment by jakebailey** [comment]
Not in November, no: https://github.com/microsoft/TypeScript/issues/50457#issuecomment-1253100246

Probably 5.0.

**Comment by anymos** [comment]
Cool thank you for the feedback, with some buffer, I believe in May it shall be possible, I will review around that time, thank you guys !
