### ISSUE TITLE
arguments are not working on target es5

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#50607]
# Bug Report

arguments are not working on target es5.

### 🔎 Search Terms

async es5

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[target es 2017 - ok](https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsL3egFASgG8AoGMmKTEdAGwFMA6G9AcweAAcOaxdkALVCAA0MYACcWCALZ0IyEPmIBfYnBy4AjMIBMwgMz4gA)
[target es 2015 - ok](https://www.typescriptlang.org/play?target=2#code/IYZwngdgxgBAZgV2gFwJYHsL3egFASgG8AoGMmKTEdAGwFMA6G9AcweAAcOaxdkALVCAA0MYACcWCALZ0IyEPmIBfYnBy4AjMIBMwgMz4gA)
[target es 5- error](https://www.typescriptlang.org/play?target=1#code/IYZwngdgxgBAZgV2gFwJYHsL3egFASgG8AoGMmKTEdAGwFMA6G9AcweAAcOaxdkALVCAA0MYACcWCALZ0IyEPmIBfYnBy4AjMIBMwgMz4gA)
### 💻 Code

```ts
async function foo(){
    console.log.apply(this, arguments)
}
foo(1,2,3)
```

### 🙁 Actual behavior

```
[LOG]: {
  "label": 0,
  "trys": [],
  "ops": []
} 
```
### 🙂 Expected behavior

```
[LOG]: 1,  2,  3 
```

**Comment by fatcerberus** [comment]
TS would need to generate a temporary for `arguments` to fix this.

Workaround (and what I would recommend writing anyway):
```ts
async function foo(...args) {
    console.log.apply(this, args)
}
foo(1, 2, 3)

**Comment by jakebailey** [comment]
I can see that the "actual" behavior is undesirable, but there is a diagnostic that warns you about this in your "error" case on the playground:

> The 'arguments' object cannot be referenced in an async function or method in ES3 and ES5. Consider using a standard function or method.

Which implies this is expected behavior.
