### ISSUE TITLE
Type definition get lost when use "infer"

### ISSUE THREAD

**Issue by biigpongsatorn** [microsoft/TypeScript#50605]
# Bug Report

### 🔎 Search Terms

missing type when use `infer`

### 🕗 Version & Regression Information

- I've tested this in `4.4.2` and `lastest 4` versions and i've got same behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHZQLxQN5QPp4DmEqAThAFxQDkAhgiqtVAL4BQokUAMsgG7QsuAsTKUaAG34Rm7DuGgA1CKQDOjTFFXBSiVISgAfKKgCuAWwBGK+VwDiJcpvhI0RntLZsIADzDJSYChOaAA5CGAAMwlEH01hPDAJWiiA8ypqVAjo2NkAbm8-AKCQqAAJACEAeXj8ROTU0nSaAAtLZHyvUoAFBsi0zXComLjjSqquhSgAWX5ECAAeNigoOyhfYBIAE1VVx0FYBjQAGmWoRXWfTdQd85V1NyxtXX1Tle7L69velP6mweyI1OAD5NGsAGTnKCQ7oFWzQAAqyHGC0UoKwFw2212sz48wWekiKlWxyghOJilJ5NI+FBAH4ZnNFnZSZTytVQVRTKgANaoZAAd1QcMi3KO6GAyHCV2UakYVVQ4wAFOZ+FRcfiHGJSc89IRgQBKHBncjAUykdBgWhqCAASVQwBV-CNAGooABGKC0XZIlEa5n7HU6PXA4FsORwNDaKCqvEHABEACZ416cUyFlryEGXvqCpHUNGsgL-ZpJdLgLKHqgFcrY-MjQB6BsmCDFpnq9OZiCs+6MUnjMNsJtQeNF-0p1QtZCmCRbKDWEf+jOBrTB17sqrAlOWUxBW1QQjIILxpddntyk4brdsIA)

### 💻 Code

```ts
// Nominal type
type Action = { __genre: 'action' }
type Love = { __genre: 'love' }

type Version = string | number
type Genre = Action | Love

// Nominal type
export type Netflix = { __platform: 'netflix' };
export type HBO = { __platform: 'hbo' };

type Platform = Netflix | HBO

type Movie<
  G extends Genre = Action,
  V extends Version = string,
  P extends Platform = Netflix,
> = G & V & P;

// I want to create a new type to replace `Platform` property to `HBO` by using `ToHBO<Movie>`
type ToHBO<V> = V extends Movie<infer G, infer V, infer _> ? Movie<G, V, HBO> : unknown;

function toNextVersionOnHBO(mov: Movie<Genre, string>) {
  // example of parsing type to `HBO`
  return parseInt(mov) + 1 as ToHBO<Movie<Genre, string>>
}

const movie = "2" as Movie<Genre, string>;
const newMovie = toNextVersionOnHBO(movie) // newMovie: Movie<Genre, Version, HBO>

// "newMovie" should be "Movie<Genre, string, HBO>" but I got "Movie<Genre, Version, HBO>"

```

### 🙁 Actual behavior

Type of newMovie is `Movie<Genre, Version, HBO>` but it should be `Movie<Genre, string, HBO>`.

### 🙂 Expected behavior

Type of newMovie is `Movie<Genre, Version, HBO>` but it should be `Movie<Genre, string, HBO>`.

**Comment by MartinJohns** [comment]
Simplified check:

```typescript
type Test = ToHBO<Movie<Genre, string>>
//   ^?
//   Expected: string, Actual: Version
```

**Comment by whzx5byb** [comment]
I think it is caused by the mechanism how intersection of union types are "flattened". Basically `A & (B | C)` will be considered the same as `(A & B) | (A & C)`, and the latter form will have a distributive behavior.

Consider the code below:
```ts
type Intersection<T, U> = T & U;
type Infer<R> = R extends Intersection<infer T, infer U> ? [R, T, U] : never;

type Union = { v: 'a' } | { v: 'b' };
type S = Infer<Intersection<0, Union>>;
```

You may expect `S` to be `[Intersection<0, Union>, 0, Union]` but it's actually `[0 & {v: 'a'}, unknown, unknown] | [0 & {v: 'b'}, unknown, unknown]` because of the distributive behavior mentioned above.

Note that when `Intersection<0, Union>` is distributed into `(0 & {v: 'a'} | 0 & {v: 'b'})`, the "shape" of the type is lost so you can't infer the generic parameters any longer and the default constraint type `unknown`(in your case it is `Version`) is used instead.

**Comment by biigpongsatorn** [comment]
@whzx5byb Thanks for the answer, do you have any suggestions for solving this issue?

**Comment by whzx5byb** [comment]
@biigpongsatorn A simple workaround could be wrapping the union types by a object or a tuple so that they can't be distributed.

```diff
type Movie<
  G extends Genre = Action,
  V extends Version = string,
  P extends Platform = Netflix,
- > = G & V & P;
+ > = string & [G] & [V] & [P];

...

function toNextVersionOnHBO(mov: Movie<Genre, string>) {
  // example of parsing type to `HBO`
-  return parseInt(mov) + 1 as ToHBO<Movie<Genre, string>>
+  return String(parseInt(mov) + 1) as ToHBO<Movie<Genre, string>>
}
```

**Comment by andrewbranch** [comment]
@whzx5byb is right about the problem but I suggest a slightly different workaround that achieves the same effect:

```ts
- type ToHBO<V> = V extends Movie<infer G, infer V, infer _> ? Movie<G, V, HBO> : unknown;
+ type ToHBO<V> = [V] extends [Movie<infer G, infer V, infer _>] ? Movie<G, V, HBO> : unknown;
```

This makes the conditional type itself non-distributive, and is a very common pattern for dealing with this sort of issue.
