### ISSUE TITLE
Completion shouldn't be completed by parenthesis when declaration method in an interface 

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#5061]
![autocompletionafterparen](https://cloud.githubusercontent.com/assets/489742/10234707/430331de-684b-11e5-9b7e-684a0a97de41.gif)

Typing parenthesis in this position shouldn't cause completion. The behavior should be the same to property declaration in class declaration instead. For property declaration in class declaration, completion is inserted when users press tab or enter only.

**Comment by DanielRosenwasser** [comment]
We just shouldn't be suggesting identifiers other than those found in heritage clauses.

**Comment by DanielRosenwasser** [comment]
Actually, this is a suggestion to avoid using `(` as a commit character. I think it makes more sense to do #5060, since that's the actual issue.

**Comment by yuit** [comment]
I have similar feeling that there shouldn't be any suggestion aside those found in heritage clause. Though if we decide to go down that route, we should do the same thing for class declaration

**Comment by DanielRosenwasser** [comment]
Yup, #3377 tracks that.

**Comment by yuit** [comment]
:cookie:

**Comment by mhegazy** [comment]
#5060 is the real issue here. it should be a builder. i do not think we need to change the commit characters here.
