### ISSUE TITLE
`tsc --init --help` generates foreign `compilerOptions: { help: true }`

### ISSUE THREAD

**Issue by amitdahan** [microsoft/TypeScript#50627]
# Bug Report

### 🔎 Search Terms

- `init`
- `--init`
- `--help`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `init`.

### ⏯ Playground Link

(Issue is with `tsc --init` so I'm no sure playground / bench is relevant here)

### 💻 Code

```sh
# the following generates `help: true` in `compilerOptions`
tsc --init --help

# while this works fine:
tsc --init --watch
```

### 🙁 Actual behavior

`tsconfig.json` is generated with `{ compilerOptions: { help: true } }`.

### 🙂 Expected behavior

`--help` is ignored, exactly like `--watch` or `-w`.

**Comment by fatcerberus** [comment]
Does a tsconfig containing `"help": true` cause tsc to print the help text?

**Comment by amitdahan** [comment]
Nope, it's gracefully ignored (unlike `watch: true`)
