### ISSUE TITLE
"Implicit any" when accessing a remapped key of a mapped type (but no error when accessing the whole mapped type)

### ISSUE THREAD

**Issue by turolla** [microsoft/TypeScript#50632]
# Bug Report

### 🔎 Search Terms

implicitly any, key remapping, filter object properties by type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/JYOwLgpgTgZghgYwgAgCIQM4KsADmAeygB4ANAPmQG8BYAKGWTAE9cIAuZUgbnoF969APRDkAYQIgAJsDDBJcADZNWKKBACOAV2DqpyOBgPIA7kQDWcKAS3TTACwghkMYIsg4QAc2S5rbKDlMZAAjZhU2YVF7MDBcDHYRL1l7LRCAOgQCAFshbOBsAgwCGDAhABVVAGVsPDLgDAwtTCEAZgAOADYAFk76FjZxHNwiiCkABX9oIIxicsoAXmRy5AgAD0hpIzgQcIB+amR6RgBtAGlkUGRzCGYS5YMjcvOAXVWNpykjdCwcfCJiDtmJQDhdOCAIAA3aAvTjHRjLV7vTZfNCYWr-EigGDQLggrjIcFQ6C8Oh8QnICHQqCk+igDzwJBDcDrMBzSi0Bi+fwJIbZEYYMaTAgBGbs0kCOj9VR8gXQdnIJacxjEABiyM+RgAFAgwGtOBIWRt2QBKRWUIHkLUwECcVVmzg-DGEEgAJQgYC0UBAlTYavI5AlgjoCEUhiMEn5RTgIUUKGVyCyUcFBuGoxIYHsDUWyFsUggrghUgAhNxkCJkAB5fKxMbpdL8YOh8PIVUEAgaray6Ox+PwuCKphZjCZNOCrVas0LSgAcgAgjOTaTGCFB5mGqPkxAJ1PKAAmJfwhCDmcIGdBqUhsONZAAISsndRbY7CbMUHMoB8S3XI6Tcp1ermomerpH4IoYGa5aiMQAC0MHIAAkuq5QABIIVUyAAOqVq6ZxVPWDaXowIAEGAmEWJ+a7Dpu-66msQF0aBPLpHAZoVrB8GYShACayxoRhqCVgAolUAByM4rHseyNnQQA)

### 💻 Code

```ts
interface Descriptor<X> {
  type: X;
}

// Conditional type required as a workaround when filtering properties by type
// https://github.com/microsoft/TypeScript/issues/38646
type ComposedProperties<T> = T extends any ? { 
  [K in keyof T as T[K] extends Descriptor<any> ? K : never]: 
    T[K] extends Descriptor<infer X> ? X : never;
} : never;

interface Context<T> {
  props: ComposedProperties<T>;
}

type Composer<T> = {
  <F extends (ctx: Context<T>) => any>(fn: F) : Descriptor<ReturnType<F>>;
}

class Composable {
  compose: Composer<this> = undefined!; // Omitted..
}

class Foo extends Composable {
  a = this.compose(() => 'A');
  b = this.compose(() => 2);
  c = 'c';
}

class Bar extends Foo {
  working = this.compose(ctx => ctx.props)  // <-- IF THIS WORKS...

  notWorking = this.compose(ctx => ctx.props.a) // <-- WHY THIS DOESN'T ??
}
```

### 🙁 Actual behavior

'notWorking' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)

### 🙂 Expected behavior

No error

**Comment by andrewbranch** [comment]
The `working` initializer works only because it doesn’t reach in far enough to force the constraint of `this` to be resolved. If you do `working = this.compose(ctx => ctx.props).type.a`, you hit the same circularity issue.
