### ISSUE TITLE
Squiggle error doesn't get update properly

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#5063]
The squiggle error persists even though the statement that causes the error is removed. The bug is quite hard to repo. I ran into it under two different scenarios: 1) toggle allow implicit any compiler setting on/off and remove the statement that causes an error while doing so (this one is a bit uncommon) 2) using the the project for a while and then the bug starts to creep in. These error do not show up when you build the project so you can still run the project just fine. But they accumulate as you will see from the screen shot below.

If you close the window and reopen, the bug will disappear, but can be reintroduce if you make a new mistake.

![seesquigglefromolderror](https://cloud.githubusercontent.com/assets/489742/10235989/1f2edfb4-6856-11e5-97d8-db47be7cc931.png)
![errorpersistance](https://cloud.githubusercontent.com/assets/489742/10236137/3fefe8f0-6857-11e5-8ae5-80eedcd05b7b.png)

**Comment by vladima** [comment]
I can repro this in the latest bits:
- create a new Html Application with TypeScript
- edit `app.ts` - add `export` before the `class Greeter` - error appear both in editor and in error list
- open project properties -> `TypeScript Build`  and set `Module system` to `AMD`, save the project - error is removed from the error list but still present in the editor. If I close and reopen file - everything looks as expected - no errors.

**Comment by dpoeschl** [comment]
@vladima - How long has this been happening? Does it repro in RTM?
 /cc: @heejaechang -- Are there any known issues with stale squiggles that might be relevant here?

**Comment by vladima** [comment]
no, AFAIR it did not repro in RTM

**Comment by heejaechang** [comment]
@CyrusNajmabadi probably due to recent tagger change. Cyrus? if error list doesn't have the error, then it probably means the error is removed from diagnostic engine, but tagger's internal cache somehow still hold on to it.

**Comment by vladima** [comment]
Initial state:
![before](https://cloud.githubusercontent.com/assets/8052307/10526211/5298b350-733e-11e5-9b5d-16521b4b71fc.PNG)
After setting module to `AMD`

![after](https://cloud.githubusercontent.com/assets/8052307/10526218/61a7db1e-733e-11e5-8436-d43417a47ac5.png)

**Comment by heejaechang** [comment]
@vladima and this is live error right?

**Comment by vladima** [comment]
yes

**Comment by vladima** [comment]
should be fixed in https://github.com/dotnet/roslyn/pull/6427

**Comment by vladima** [comment]
fixed in https://github.com/dotnet/roslyn/pull/6427
