### ISSUE TITLE
Type 'NodeListOf<HTMLTableRowElement>' must have a '[Symbol.iterator]()' method that returns an iterator.deno-ts(2488)

### ISSUE THREAD

**Issue by BlackAsLight** [microsoft/TypeScript#50636]
# Bug Report

### 🔎 Search Terms

NodeListOf<HTMLTableRowElement>
Symbol.iterator]()
Type 'NodeListOf<HTMLTableRowElement>' must have a '[Symbol.iterator]()' method that returns an iterator.deno-ts(2488)

### 💻 Code

```ts
[ ...document.querySelectorAll('tr') ]
```

### 🙁 Actual behavior

Typescript complains saying that I can't use the spread operator here because NodeListOf<HTMLTableRowElement> doesn't have [Symbol.iterator]() method. It probably doesn't, but I'd say it's wrong because javascript has no problem converting this and I'd prefer to not go the `Array.from()` route or do `as unknown as HTMLTableRowElementp[]`

### 🙂 Expected behavior

TypeScript not complain

**Comment by Jamesernator** [comment]
> Typescript complains saying that I can't use the spread operator here because NodeListOf doesn't have Symbol.iterator method. It probably doesn't

If you want iterables you'll need to include `"dom.iterable"` in your tsconfig, for deno instructions seem to be on this page: https://deno.land/manual@v1.25.1/typescript/configuration#targeting-deno-and-the-browser
