### ISSUE TITLE
JSDoc to Type Annotations Codefix And @typedef

### ISSUE THREAD

**Issue by chadhietala** [microsoft/TypeScript#50644]
# Suggestion

Currently the JSDoc to TS types codefix does not 

## 🔍 Search Terms

- jsdoc @typedef
- typedef codefix

Found https://github.com/microsoft/TypeScript/issues/19285 but after trying out the code action in the editor it doesn't seem like 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Currently the [`annotateWithTypeFromJSDoc`](https://github.com/microsoft/TypeScript/blob/main/src/services/codefixes/annotateWithTypeFromJSDoc.ts) codefix does a great job at handling many cases for converting JSDoc to types. However it seems that it does not follow type defs that have been introduced via `@typedef`, leaving you will unresolved references. Since the compiler is able to [emit type aliases](https://www.typescriptlang.org/play?filetype=js#code/PQKhCgAIUghBDAxgawOYCcD2BXAdgE0gEsBbeVAU0kU1wDMjVt14AXI2yTAIwCsLErKDAACrAJ4AHCvgp1IAbwDyfAawC+cVAEkSqAMK0GqYZBGSs09BMUA5bCW4V0mmrlbwiuZwAkKjAAtWSABaSABBSG4kNCw8QjcPL2cAcgBnSAD-VCDTc0tnGwV7R2dXWiTvdAB1InxWANCIqJiMHAJqCs8q9MgAdzqGvItMKyKSpxdiMkpbNmZ4ABs-QOCwyOiUNvjp8gpe3HmWRczs3OgzEbHxOwdJzVI9udYFxdr6xvWWrbiOx8oDkclv1BgFhMBwEA) from `@typedef` references it seems like there is some missing functionality in this codefix or that a code fix could be introduced for `@typedef` references in TS files to convert to a type alias.

## 📃 Motivating Example

Before:

<img width="596" alt="Screen Shot 2022-09-05 at 3 00 44 PM" src="https://user-images.githubusercontent.com/183799/188503038-ba20e6af-63d4-4e54-a304-5794d584d8a4.png">

After:
<img width="758" alt="Screen Shot 2022-09-05 at 3 01 28 PM" src="https://user-images.githubusercontent.com/183799/188503072-d13b8a18-f5e0-46c5-ae8d-9aba177c5f78.png">

## 💻 Use Cases

I think the uses cases are covered in #48982, but in general we are trying to convert millions of lines of JS to TS, being able to leverage as much of the static information we already in files to produce valid types would be very helpful.

**Comment by andrewbranch** [comment]
It’s intentional that JSDoc types are only resolvable in JS files. So to clarify, you’re suggesting an additional codefix/refactor to convert `@typedef`s to type aliases? It actually sounds like you probably want a CLI tool, though, i.e. #19285.

**Comment by chadhietala** [comment]
Currently the [annotateWithTypeFromJSDoc](https://github.com/microsoft/TypeScript/blob/main/src/services/codefixes/annotateWithTypeFromJSDoc.ts) codefix in the service leaves you with unresolved references. Why suggestion is to make a codefix/refactor for `@typedefs` and/or modifying `annotateWithTypeFromJSDoc` to leverage that same codefix.

**Comment by DanielRosenwasser** [comment]
This may not be super easy, but ideally beneath each `typedef` declaration, we would generate an equivalent `interface` or `type` alias. Do we already have a refactoring to convert a typedef to an alias?

**Comment by andrewbranch** [comment]
We don’t. I really thought we did.

**Comment by chadhietala** [comment]
I can try and take a stab at this. Should this be a refactoring or a codefix?

**Comment by andrewbranch** [comment]
I think a fix would be ok since the typedefs aren’t going to do anything in .ts files... using a codefix implies issuing a suggestion diagnostic, and we try to avoid doing that unless we think something is actually wrong. Having a `@typedef` in TS where it’s meaningless meets my bar for “actually wrong.” @DanielRosenwasser what do you think?
