### ISSUE TITLE
Type narrowing on a property does not narrow the type of the parent

### ISSUE THREAD

**Issue by Fryuni** [microsoft/TypeScript#50651]
# Bug Report

### 🔎 Search Terms

type narrowing
narrowing property
narrowing nested

### 🕗 Version & Regression Information

> When did you start seeing this bug occur?

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing, guards and common bugs

Locally I noticed this on versions 4.7.4 and 4.8.2.
It also happens on every version available on the playground, from 3.3.3 up to nightly (4.9.0-dev.20220905).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220905#code/C4TwDgpgBAYg9nKBeKBvAUFLUBGBDAJwC4oBnYAgSwDsBzAGk23wC8B+E8quxgXwG506UJFgIA6pWAALAEJ4WyMYgBkaJllYkAcnGraArgBsjeHEYgAeeHADaAclb2AugD4+g9ADMD1AMbAlHpQwHgA1hCkNgAUXiQ2AJTq2FCUXlCxAHSsyEgovgAmEF40EAVJGCkpBBDABgTUgim8QikA9G1QACrSlKRk0nDGBVAA7nAEYRoh4ZE2kjLyLLEJnu2dPX1jE2Gk9LgGwFB+NXjAkVB4UNQQo1BwOABWEAHToRFRElJyCtGVVVhMkCvIwAZoFCQvNkFKDsLxVugWt5fAEgtQZh95t8ltEAPrxL6LBQVXhAA)

### 💻 Code

```ts
type Foo = {
    bar: string,
    baz?: string,
};

type FooWithBaz = Foo & {
    baz: NonNullable<Foo['baz']>,
};

function takesFoo(f: Foo) {
    if (f.baz === undefined) {
        return;
    }

    // This should work
    takesFooWithBaz(f);

    // This works, but creates a new object
    takesFooWithBaz({
        ...f,
        baz: f.baz,
    });
}

function takesFooWithBaz(_: FooWithBaz) {}
```

### 🙁 Actual behavior

Type narrowing should happen on the property and the parent variable, allowing `f` to be passed to `takesFooWithBaz`

### 🙂 Expected behavior

The property `f.baz` is narrowed to not be undefined, but the property `baz` of the type of `f` remains as `string | undefined`.

**Comment by MartinJohns** [comment]
[Quoting @jack-williams:](https://github.com/microsoft/TypeScript/issues/31755#issuecomment-498669080)

> Type guards do not propagate type narrowings to parent objects. The narrowing is only applied upon access of the narrowed property which is why the destructing function works, but the reference function does not. Narrowing the parent would involve synthesizing new types which would be expensive. More detail in this [comment](https://github.com/microsoft/TypeScript/issues/30506#issuecomment-474802840).

Used search terms: `type guard property parent`

Duplicate of #42384.

**Comment by Fryuni** [comment]
Looks like it's not a bug then, thanks @MartinJohns

**Comment by fatcerberus** [comment]
Yeah, if you need to narrow-by-property, you should use a discriminated union.  Those exist as a trade-off, if this kind of thing worked in the general case, you wouldn't need them :wink: 

https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#discriminated-unions
^ in case you're not familiar with them.

**Comment by Fryuni** [comment]
My use case here was for a single type that has an optional property, so there is no need to make a discriminated union using a different property.

For a single property this can actually be solved [somewhat easily](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220905#code/C4TwDgpgBAYg9nKBeKBvAUFLUBGBDAJwC4oBnYAgSwDsBzAGk23wC8B+E8quxgXwG506UJCgBZPAGsIASWAAFAnDB5aeYBAA8AFXpQA0lAgAPDdQAmpKNJBwAZlG0A+ZFCZYAPlAAUAeQC2lMA6evouAGRQAEoQAMZwBOaa+nrUEABuEAROAJTuUF5+gcG6BhFo+dhQANr6MlA0BgC6ALQcUABycNQdAK4ANv14OP1a2rUyTU75vHnC4NDwcADqQQAWAEJ4LK5LUJEYVawkXT0DQyNaS9UA5Kw3U3yC6Ha91LHAlN1QwFIQpEtvHYSBJpHJFMpVOorgg9HdtjdchUqpQHECAHSsZBIFBvcwQOw0CDmHLIqrYAgQYC9AjUQRVXhCKoAemZjjWlCspDWcAG5igAHcEpJ8r9pACEKtgJttkCcs8WWztByrEKCJJSHocL1gFBYpToVY8FA0gKoHAcAArOLAUV-CUrdZbFjeQ7krDoz12RjurDHKB2THbH3YWaCRkvN4fL7UH72pZSmUugD6JATTu2pNQvCAA), but I thought this was supposed to work out of the box.

**Comment by ericbf** [comment]
Though not a bug, seems like a valid request still. Related to #42384, but slightly different. In the other issue, it’s talking about inferring (discriminating) the type of the parent based on type guards, while this one is talking about narrowing the type of the parent.

Seems a perfectly valid use case that _should_ work out of the box:

```ts
type Nest = {
    nested?: {}
}

function doSomething(n: Nest & { nested: object }) {}

declare const n: Nest

if (n.nested) {
    doSomething(n) // Error
    doSomething({ ...n }) // Error
    doSomething({ nested: n.nested }) // Works, but loses object identity
}
```

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAchDOwoF4oG8BQVtQHYOAgBMB+ALnQF8NqMAzAV1wGNgBLAe1yiI4GUOAWwjAAFm1wBzABS4KcRFABk6PAWIUOAIwBWEVlEoBKKhgxF9AGwCGAJ2jMuiubAJm2dKLIB0+RMRNMHB5+IRFxKVkTAHpoqABRW1sOWywcXgFhMQkZNChvAu5jKFiEpJS07Ayw7Mi8v0IiClxfdSJDGLiAdRSAa3gAGigtBiRLDngEKG09AzYLXHZQGiA)

It seems obvious that inside the `if` statement, `n.nested` is defined, so the call to `doSomething` should not be flagged as an error.

Whether this is working as intended or not, there’s obviously a gap there that at least can be explored.

I’d like to see this issue reopened, or another issue created (I can create it, if desired) to track this as a feature request instead.
