### ISSUE TITLE
No error when interface extends another interface and declares same method with a narrower type

### ISSUE THREAD

**Issue by njx** [microsoft/TypeScript#50662]
# Bug Report

### 🔎 Search Terms

method overload

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about substitutability, methods, and overloads

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.8.2#code/JYOwLgpgTgZghgYwgAgIJQOYDED2VXIDeAUMmcnJqgFzIDOYUoGA3MQL7HGiSyIoES5ZAFsIYABY4AJgApKGWumx5UASloA3HMGltO3cNHhI0mXFABCyCAA9IIaXTMr8RUuQWXaDJiFYcXDzG-MjWdg5OaO7CYpIy8phK5niWGsjauvpcCAA2cHTOlgDC+YXIwCIADrkQYuBFMeRxUnIKya5pTcJkCDggdDi1AHS5OBiJGMNeoxD+kmpswpwGfQNgFErIALzIIBAA7mGlBXSyi8QA9JfIACoSUDgHzgfAksgARMVwICA4G1AIHBpMgqo8qtAwMAIM4cDBkABXRwQGCgCAg2SA4HMZAAclq8wkuLUH2IcGGLQShAoVFoHxgOBwH2Q7AuQA)

### 💻 Code

```ts
interface ArgForA {
    argA: string;
}

interface A {
    method(arg: ArgForA): void;
}

interface ArgForB extends ArgForA {
    argB: string;
}

interface B extends A {
    method(arg: ArgForB): void;
}

class BClass implements B {
    method(arg: ArgForB) {
        console.log(arg.argB.length);
    }
}

const a: A = new BClass();
// Throws with "Cannot read properties of undefined (reading 'length')"
a.method({ argA: "foo" });
```

### 🙁 Actual behavior

No compilation error, even though B.method() specifies a narrower type for its argument than A.method(), which leads to being able to call B.method() through an A reference with a wider type that it doesn't expect.

### 🙂 Expected behavior

Compile error in the declaration of B.method().

**Comment by njx** [comment]
Found documentation on parameter bivariance. Never mind.

**Comment by fatcerberus** [comment]
@njx In case you missed it (because IIRC the current documentation doesn't mention it): enable `strictFunctionTypes` if it isn't already, then declare `method` as a property with a function type rather than as a method.  Then the parameters should be checked contravariantly.

```ts
interface A {
    method: (arg: ArgForA) => void;
}
```
