### ISSUE TITLE
Readonly<T> prevents private members from being accessed

### ISSUE THREAD

**Issue by shrinktofit** [microsoft/TypeScript#50668]
# Bug Report

### 🔎 Search Terms

private, readonly, remove, class, exclude

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8CwAoaXoAcCuARiAJbDQFgBO0AvNAAwDcG2ulxAbmAC4Cm0AfQrU6TFtgDEw2g2bpxWfEVLkwALwAU3ABY8AXHEQAaaJV5gAJvAB2IAJ4AVXdwMAlc1dt2APAngA+AEoUBVZoHWIIADphRmgAenjoAHkAaVDWCOihKjjElPTMMKwsqKlchKS0jAzsHR4YivzqouL67iicyjyqwuKS5zLYyoKa1rCzSxt7Jwbh5r7+yc8Zwa6e6ABRSkp4SlqsZenHQfLuke3d-fGAXwwboA)

### 💻 Code

```ts
class Foo {
    public bar = 0;
    private _bar = 0;
    #bar = 0;

    public baz(that: Foo, readonlyThat: Readonly<Foo>) {
        this.bar; // OK
        this._bar; // OK
        this.#bar; // OK

        that.bar; // OK
        that._bar; // OK
        that.#bar; // OK

        readonlyThat.bar; // OK
        readonlyThat._bar; // Error
        readonlyThat.#bar; // Error
    }
}
```

### 🙁 Actual behavior

Can not access private members from `Readonly<T>` version class, even within class body.

### 🙂 Expected behavior

Within `Foo.baz()`, all fields of objects with type `Readonly<Foo>` should be accessible.

**Comment by MartinJohns** [comment]
This is working as intended. Mapped types like `Readonly<T>` use the `keyof` operator, and the `keyof` operator intentionally does not include non-public members.

You might be interested in #35416 tho.

**Comment by shrinktofit** [comment]
> 

Well. Is there an alternative way to implement "readonly class object"?

**Comment by MartinJohns** [comment]
No.
