### ISSUE TITLE
Since 4.8.2, union discrimination fails with `(string & {})` when `noUncheckedIndexedAccess` is `true`

### ISSUE THREAD

**Issue by maxijonson** [microsoft/TypeScript#50683]
# Bug Report

### 🔎 Search Terms

noUncheckedIndexedAccess
string & {}
union
intersection reduction

### 🕗 Version & Regression Information

4.8.2

- This changed between versions 4.7 and 4.8
- Possibly related to this [PR](https://github.com/microsoft/TypeScript/pull/49119), where `(string & {})` should be an exception
- Only when `noUncheckedIndexedAccess: true`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.8.2#code/PTAEBUAsEsGdQCYHsCm8B2SAuoBmBDaAGwBpRZp0BjFUTAVWshSoGsUEBJdBFADw4BBKjVjw4efEVgoAUCFABlAO7QsVSHSSMNLdlx78hItPCxJQWAE4BXWufIp7zUCitWkV2bKwBPAA60gkTQAOboALYo6DgAvKAAFLDWlKGgAGSgAN4AvgCUoAA+oABERCi4WCVFpTQxbtXFJVZhkFUA3D4BQSHhUTHw8QBKLJ4IADzBYZHRWGTJLeihAHydslRI6Mmg+ABcoFN9s4PZsqDnoOWV+yVS0wC0V1UkZxd1WG43d+H37w0vF1ALVCbS+vXQ92BbRKAIu2GYVjBD3h-1kOTWGy2SHKADoiEhQgl8HiKlgSUssJA8u1QAooBJYJAkDYiAh0AByHAAI1omIovCsHB28H8SDE0C5RF8pRshlwlA4MPIlBopSe1Qk+EQFQVCAO4P6WHWm1g2JQeIJRJxKKs5NClOptLA9PgjOZrNAPNAfOgAqF+BFYookulJVlvHl6EViQ27hY3JQkHwADdoMyrHlvMAAFSWWCY+WhHEAK1N6FkWVeJQ2EX8xDcAHl-Fg01sSvtK4CSlh8FZQigqjcAKKKABy-Ger3OJQiSAQLJQ7dKI-HfEnXYW0Cog8sthQsOnDCYeg43F4AgQwlEsCX1jsrxyaNk2eAsiAA)

### 💻 Code

```ts
// TS 4.8.2
// This does not fail by default under strict mode, since noUncheckedIndexedAccess is false by default
// Switch noUncheckedIndexedAccess to true to see the error
// Then switch to 4.7.4 to see the error disappear

type Alignment = (string & {}) | "left" | "center" | "right";
type Alignments = Record<Alignment, string>;

const a: Alignments = {
    left: "align-left",
    center: "align-center",
    right: "align-right",
    other: "align-other",
};

console.log(a.left.length); // This shouldn't be considered as possibly "undefined", since "left" is a defined Alignment (incorrect behaviour under 4.8.2)
console.log(a.other.length); // This should be considered as possibly "undefined" (correct behaviour)
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "strict": true,
    "noUncheckedIndexedAccess": true
  }
}
```

### 🙁 Actual behavior

TypeScript 4.8.2 reports that an object's property is possibly "undefined", even for declared fields in the union.

### 🙂 Expected behavior

TypeScript 4.8.2 should only report that an object's property is possibly "undefined" for **un**-declared fields, as stated in the [documentation](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess)

**Comment by fatcerberus** [comment]
This seems to be the relevant difference:
```
// 4.7.4 hover
type Alignments = {
    [x: string & {}]: string;
    left: string;
    center: string;
    right: string;
}

// 4.8.2 hover
type Alignments = {
    [x: string]: string;
}
```

**Comment by maxijonson** [comment]
> ```ts
> // TS 4.8.2
> // This does not fail by default under strict mode, since noUncheckedIndexedAccess is false by default
> // Switch noUncheckedIndexedAccess to true to see the error
> // Then switch to 4.7.4 to see the error disappear
> 
> type Alignment = (string & {}) | "left" | "center" | "right";
> type Alignments = Record<Alignment, string>;
> 
> const a: Alignments = {
>     left: "align-left",
>     center: "align-center",
>     right: "align-right",
>     other: "align-other",
> };
> 
> console.log(a.left.length); // This shouldn't be considered as possibly "undefined", since "left" is a defined Alignment (incorrect behaviour under 4.8.2)
> console.log(a.other.length); // This should be considered as possibly "undefined" (correct behaviour)
> ```

Thanks for narrowing down the inferred type! You're right, `Record` isn't covered in that PR. It's worth noting that this issue is relevant for non-`Record` too. The same expected behavior (4.7.4) and actual behavior (4.8.2) happens here:

```
type Alignment = (string & {}) | "left" | "center" | "right";
type Alignments = {
  [key in Alignment]: string;
};

const a: Alignments = {
  left: "align-left",
  center: "align-center",
  right: "align-right",
  other: "align-other",
};

console.log(a.left.length); // Fine under 4.7.4. Error under 4.8.2
console.log(a.other.length); // Error for both versions (expected, however, in 4.8.2, I don't believe it's failing for the 'right reason')
```

**Comment by lll000111** [comment]
Not only unions. Here is a simpler example:

https://www.typescriptlang.org/play?ts=4.7.4#code/GYVwdgxgLglg9mABAZQKZgCYCEA2cBGAFBgIZQkBci4A1mHAO5gA0i6EcGMYA5lbfSYBKRAG8AsAChEMxDGCJC7Ttx6IAhAF5N1TKmDdUGRADITbSCt4btiAOQgowABx2RE6bK9QAFgCdGRDBUBkQAUT8Av0I7ZS5eNwBuKS8AXykU2QB6LMQAWTgQAGdURB84ADdUP0QoOEQS0oxUKFRoI1qATwAHUpgisVTEAB9dZoNgjEyZHMQAdR90aiLVRAAVZEQKgBYAOgB2Xe25KDkBgCJHF3ORsf1DKc8ZONVkyVS3oA

```javascript
function SendBlob(data: unknown, encoding: unknown) {
    if (encoding !== undefined && encoding !== 'utf8') {
        throw new Error('encoding');
    }

    // Mouse hover to see detected type is {} | undefined
    // When using TS v4.7.4 it is "utf8" | undefined
    encoding;
};
```

**Comment by maxijonson** [comment]
While this is not in fact an issue relating to `(string && {})` in declared union types or `noUncheckedIndexAccess`, I believe it could be related, since the conditions for `encoding` could create an "inferred" union.

**Comment by lll000111** [comment]
For the record, definitely related, now its own ticket: #50706
