### ISSUE TITLE
Generic of `Record<string, ...>` cannot be inferred correctly when passed down to callback

### ISSUE THREAD

**Issue by matzeeable** [microsoft/TypeScript#50682]
I want to create a function, which takes an `Record<string, ...>`, make the value type generic and pass down the generic to a "callback"-map:

```ts
type VarValue = string | number | boolean;

function mapObject<T extends Record<string, VarValue | VarValue[]>>(
    object: T,
    mapValue?: Partial<Record<keyof T, (val: T[keyof T]) => any>>
) {
    // Do something
}
```

This is the object I would like to pass to `mapObject`:

```ts
const myObject = {
    myProp1: "middle" as "middle" | "center",
    anotherProp: 100
};
```

Now, when using `mapObject` the `mapValue` parameters is a union type of all possible types of the `Record` value:

```ts
mapObject(myObject, {
    myProp1: (val) => {
        //    ^ number | "middle" | "center"         -> should be: "middle" | "center"
    },
    anotherProp: (val) => {
        //        ^ number | "middle" | "center"     -> should be: number
    }
})
```

Playground: [Click here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAaghgJ3gGwK7QLxQM7AQSwDsBzKAHykNQFsAjCBcqWgexeQjkIG4AoXgGapCAY2D4WhKNThgA8rQBWEMQB4AKlAgAPYBEIATbFABKKlggOrcBEgBpYiFOibwkcNBADaAXQB8fgAUvFChUCxKKsAAXFDqdiFhMmDOEAD8sQAKiOIeqmYiFlYA1hAgLAJxDoEAbh6x6l6l5ZXqPgCUUBh+UFwgAbydAN6JoQD0Y1AAIiw4LNQQwAAWRMS8AL78hYS40iAKymJdUCNhe5kILGAAjLEARNT4BgYcd73GD08vEG8UdyL6PQIO4JM5cFjLBgXK6xa4ABjhGz4vGSByigWo+0iYgcpySIGhN1itQ8nW6J1GZygEzOAD1KDR6Iw-o9nq8mP9AQw3lSwgBaHrYJYsVDIAzMCD3VnfX5QTmEIF3SnrUFhcGQhCE4l1ZBknp43k03lQelUOgMDnS9l-AEK7lUgU4YWi8X0WJmpnKjbtIA).

**Comment by MartinJohns** [comment]
You used the wrong issue template, that's why the label "Duplicate" was added. This is the issue template for bug reports: https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md

I don't see a bug here. The type of `T[keyof T]` is correct, because `keyof T` is a union of all keys.

You actually want a **mapped** type: `mapValue?: { [P in keyof T]?: (val: T[P]) => any }`
