### ISSUE TITLE
TypeScript's code formatting corrupts code containing a numeric literal

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#50686]
# Bug Report

### 🔎 Search Terms

formatter number tostring

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/IwagBATGB0AuD2BlWAnAlgOwOYAoCUYIAzEA)

### 💻 Code

```ts
1+ 2 .toString() +3
```

### 🙁 Actual behavior

When you run "Format Document" the code is changed to `1 + 2.toString() + 3`, which is invalid JavaScript.

### 🙂 Expected behavior

Several valid formatting outputs include the following:

```js
1 + 2 .toString() + 3
1 + 2..toString() + 3
1 + (2).toString() + 3
```

This is a problem for VSCode users because it means that saving a file in VSCode corrupts the file (if you have format-on-save enabled). And it's a problem for me as the author of esbuild because people are running VSCode's formatter on esbuild's output and then reporting the corrupted code as a bug in esbuild: https://github.com/evanw/esbuild/issues/2528.

### Side note: How to run TypeScript's formatter yourself

I had to manually run TypeScript's formatter to confirm that the problem was with the code in this repo. Running TypeScript's formatter on a string was unexpectedly difficult because the API is not exposed and is only available through the language server protocol, which seemed way too complicated to invoke manually. I instead used a hack that loads the code in `tsserver.js` to get to the formatter. Posting the hack here for posterity:

```js
const input = '1+ 2 .toString() +3'
const process = undefined
const addEventListener = () => {}
var ts = {}
const serverFile = require.resolve('typescript/lib/tsserver')
const serverCode = require('fs').readFileSync(serverFile, 'utf8')
eval(serverCode.replace('\n"use strict";\n', ''))
const sourceFile = ts.createSourceFile('in.js', input)
const options = ts.getDefaultFormatCodeSettings()
const context = ts.formatting.getFormatContext(options, {})
const changes = ts.formatting.formatDocument(sourceFile, context)
console.log('before:', input)
console.log('after:', ts.textChanges.applyChanges(input, changes))
```

**Comment by fatcerberus** [comment]
TIL `2 .toString()` is not a syntax error (I thought you either had to put the literal in parens or else write `2.0.toString()`).
