### ISSUE TITLE
Improve type inference by object parameters types

### ISSUE THREAD

**Issue by jozefchutka** [microsoft/TypeScript#50685]
# Suggestion

## 🔍 Search Terms

inference

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It would be nice if typescript could recognize/infer and apply safe guard for the following scenario:

```ts
type T1 = {foo:number | undefined}
type T2 = {foo:number}

const t1:T1 = {foo:123};
if(t1.foo !== undefined) {
    const t2:T2 = t1;
    console.log(t2);
}
```

Currently the compiler fails with the following ([playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgjFAvFA3gMwPYYFwDsCuAtgEYQBOUAPlPrgCYRoCWuEdAvgFCiSwBMSVJhwES5LpwDGGXAGdgUYHGzxB6LNjh8AzOwDcnJmgAUSgHTCoAQkTJaDZqzoBKVJygeo0uQuB8VAshKBp5eMrIYADYQZpEYAOamfM4G7EA))

```
Type 'T1' is not assignable to type 'T2'.
  Types of property 'foo' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.
```

**Comment by MartinJohns** [comment]
Essentially the same issue as #50651.

**Comment by ericbf** [comment]
> But this would easily lead to unsoundness. You could store `t2` somewhere, and set the property to `undefined` via `t1`.

The same can be said for almost any valid typescript.
