### ISSUE TITLE
TS 4.8 Generics completion is now weaker.

### ISSUE THREAD

**Issue by eretica** [microsoft/TypeScript#50680]
Bug Report
🔎 Search Terms
Generics completion is now weaker.

🕗 Version & Regression Information
This changed between versions 4.7.4 and 4.8.2
⏯ [Playground Link](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBAYwgOwM7wGYFdkLgXjgB4AVOUGYZAE1TnSgEtkBzAPgAoBvOAa2ACedAL4AuOD35DxJANoBdOMICUBNhICwAKG1xEKdHAyMo6ANKCCfQalkAGeQG5dcF1GAwsUZJq169UqgANC56xqYwFgIuwnAAhnRIaDDOWsKp2gD0mXAALAB0ABz5AExhJuaWDMwsWTkFAOz5ueURUXAARHFxHXAAPp0ARoMd2kmGkjZBRhWRlrGE2LjcgeKyXT3THcMd8ipAA)

💻 Code

```ts
export const func = <T extends string>({ keys }: { keys: T[] }) => {

  const firstKey = keys[0];
  
  return {
    keys,
    firstKey
  } as const;
};

// 4.8.2  firstKey string
// 4.7.4  firstKey "aa" | "bb"
const { keys, firstKey } = func({keys: ["aa", "bb"]})
```

🙁 Actual behavior

4.8.2 firstKey type of `string`

🙂 Expected behavior
firstKey type of `"aa" | "bb"`

**Comment by PindaPixel** [comment]
Desired behaviour can still be achieved by being more explicit:
```typescript
export const func = <T extends string>({ keys }: { keys: readonly T[] }) => {

  const firstKey = keys[0];
  
  return {
    keys,
    firstKey
  } as const;
};

// 4.7.4 & 4.8.2 firstKey "aa" | "bb"
const { keys, firstKey } = func({keys: ["aa", "bb"]} as const);
```

It kind of makes sense with the function's signature though, typescript cannot know if you modify keys or not unless you explicitly tell it you don't with readonly.

**Comment by somebody1234** [comment]
oddly enough, these both work perfectly fine...
```ts
const { keys } = func({keys: ["aa", "bb"]})
const x = func({keys: ["aa", "bb"]})
```

**Comment by Andarist** [comment]
On top of that the initial autocompletion for `firstKey` suggests that it will be of the union type - it just becomes `string` after the `firstKey` is being added to the binding pattern and when it becomes part of the contextual node~
<img width="594" alt="Screenshot 2022-09-08 at 11 53 13" src="https://user-images.githubusercontent.com/9800850/189092608-3d814ecd-0b36-4d5a-826f-dbf6e59c3539.png">

I've bisected this change to https://github.com/microsoft/TypeScript/pull/49887 by @jakebailey

**Comment by jakebailey** [comment]
That's... weird. I'll take a look.

**Comment by jakebailey** [comment]
Ah, so this is the test case that would have caught that we really did need to do something special in `getTypeFromBindingElement`. No test failed when I removed what I thought was redundant code, but it turns out that this was that case.
