### ISSUE TITLE
`strictNullChecks` does not get enabled for Maps when `strict` is enabled

### ISSUE THREAD

**Issue by Hurtak** [microsoft/TypeScript#50697]
# Bug Report

According to the documentation (https://www.typescriptlang.org/tsconfig#strictNullChecks), `strictNullChecks` is set to true when `strict` is set to true, but it does not seem be true for Maps.

The same code has different types with these two settings
- `strict=true` and `strictNullChecks=true`
- `strict=true` and `strictNullChecks` not set

But since `strict` is superset of `strictNullChecks`, it should behave the same

### 🔎 Search Terms

`strictNullChecks map`

### ⏯ Playground Link

`strict=true` and `strictNullChecks=true` -> type is correct `Foo | undefined`

https://www.typescriptlang.org/play?noImplicitAny=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=7&ts=4.8.2#code/MYewdgzgLgBAtgQwA4wLwzAUwO4wLLIAUA2gFAwzEBEA1pgJ5UA0MAjALpOnsCUA3KVKhIsAG4IANgFdMaeMgB0Ac0xRCVAB5aNVfkA

`strict=true` and `strictNullChecks` not set -> type is incorrect `Foo`

https://www.typescriptlang.org/play?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=7&ts=4.8.2#code/MYewdgzgLgBAtgQwA4wLwzAUwO4wLLIAUA2gFAwzEBEA1pgJ5UA0MAjALpOnsCUA3KVKhIsAG4IANgFdMaeMgB0Ac0xRCVAB5aNVfkA

### 🙁 Actual behavior

When enabling `strict=true` it should also enable `strictNullChecks`, but it does not seem to be true for Map property access, the return type is `Foo` instead of `Foo | undefined`

### 🙂 Expected behavior

When enabling `strict=true` it should enable `strictNullChecks` and Map property access has correct type of `Foo | undefined`

**Comment by MartinJohns** [comment]
In your second playground link you have set `strictNullChecks` to `false`. This overrides the setting `strict`. Please note that the playground does not have the ability to leave these flags "unset", it's either set to `false` or `true`.

**Comment by Hurtak** [comment]
Yea I just checked on regular repository and you are right, closing.
