### ISSUE TITLE
Interface and type with same shape treated diffrently when comapring to Record<string, unknown>

### ISSUE THREAD

**Issue by kbrilla** [microsoft/TypeScript#50700]
# Bug Report

### 🔎 Search Terms
interface, type, Record<string, unknown>

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about interfaces

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdEAlbCOAJyLRKhpjAHMAaRcAazDgHcwAPiEAKAA4BDGpIC2ALkQYAlIgDeAXwBQWqAE9x2RPsMBGRAF51kxY2ZsNAbh0sCNYJIhHX2d5+zmalqIIYg2iHYsrM6hiE46oJCwCMYA6jLihjSiAG6SADYg2IomAapBsShwuQVFys7aWonQ8Egw6ZKZvjWFxYg+fl6m5cGhVT11DQngLSlQHV00AKL4hETY9Fh4BMRkpaZieb2KKuqjIeNHk1qNzcltC1krO+ubOKu7-WBuHkOHtX1ThUxqgJth6jcdNQwIx+ooBr8ApZrIoAOQI-yo+LQ2FQEoGJFWNThVGlLHOXSPbpQCHzDJZUQwCHtenU5lU7JMil0zoM4loySSVGcABGaIgkhIWNpHOeaw2on5iFRguFiDFyolUo07NZ2SVKqFovFkulzhZvN8cuICoNquNmtNOscQA)

### 💻 Code

```ts
function foo<T extends Record<string, unknown>>(param: T) {}

type type1 = {a: string};

interface interface1 {
    a: string;
    };

function tWrapper(value: type1) {
    foo(value);
}

function iWrapper(value: interface1) {
    foo(value); //error 
   /*
     Argument of type 'interface1' is not assignable to parameter of type 'Record<string, unknown>
     Index signature for type 'string' is missing in type 'interface1'.(2345)
   */ 
}

const i: interface1 = {a: 'interface'};
const t: type1 = {a: 'type'};

tWrapper(t);
tWrapper(i);
iWrapper(t);
iWrapper(i);
```

### 🙁 Actual behavior

Even though type1 and interface1 have the same shape and variables of their types can be used interchangeably as see that there are no errors in 
```ts
tWrapper(t);
tWrapper(i);
iWrapper(t);
iWrapper(i);
```

### 🙂 Expected behavior

interface and type with same shape works the same

**Comment by MartinJohns** [comment]
This is working as intended. `interface` and `type` are not interchangeably.
