### ISSUE TITLE
Intersection of multiple type guard function types (or multiple overloads) has inconsistently inferred predicate types

### ISSUE THREAD

**Issue by lazytype** [microsoft/TypeScript#50708]
# Bug Report

### 🔎 Search Terms
type guard assertion function intersection predicate

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [type guards](https://github.com/Microsoft/TypeScript/wiki/FAQ#type-guards)

### ⏯ Playground Link
[Playground link with relevant code](https://tsplay.dev/WYZVzw)

### 💻 Code

```ts
type GuardIntersection = ((x: unknown) => x is number | string) &
    ((x: unknown) => x is number | boolean);

type AssertionIntersection = ((x: unknown) => asserts x is number | string) &
    ((x: unknown) => asserts x is number | boolean);

type GuardType = GuardIntersection extends (x: any) => x is infer U ? U : never;
//   ^?
//      type GuardType = number | boolean

type AssertionType = AssertionIntersection extends (x: any) => asserts x is infer U ? U : never;
//   ^?
//      type AssertionType = number | boolean

function example(guard: GuardIntersection, assertion: AssertionIntersection, x: unknown): number {
    if (guard(x)) {
        return x;
        //     ^?
        //        (parameter) x: string | number
    }

    assertion(x);
    return x;
    //     ^?
    //        (parameter) x: string | number
}
```

### 🙁 Actual behavior

When using `infer` to extract the predicate type of the intersection of type guard function types, the predicate type of the last item in the intersection is inferred. (`number | string`)
When calling a type guard function of the intersection type, the argument of the type guard function is narrowed to the predicate type of the first item in the intersection. (`number | boolean`)

### 🙂 Expected behavior

In both cases, I'd expect the inferred/narrowed type to be the intersection of the predicate types. (`number`)
At the very least I'd expect the two types to be the same. 

Aside: This is remarkably similar to the behavior of inferring the return type of function overload types (#26591). Coincidence?

**Comment by fatcerberus** [comment]
> This is remarkably similar to the behavior of inferring the return type of function overload types (https://github.com/microsoft/TypeScript/issues/26591). Coincidence?

Probably not. Overloads are represented internally as intersections of function types.

**Comment by DanielRosenwasser** [comment]
> Overloads are represented internally as intersections of function types.

As an aside, this is not quite true - each object type has some number of call signatures and construct signatures. When constructing an intersection, those lists of signatures are combined.

**Comment by DanielRosenwasser** [comment]
I do think that this is the same as #26591 actually - and @fatcerberus please feel free to correct me if you believe I've missed something.

Some explanation:

1. When you call a function, TypeScript tries to figure out the right overload. This process is a "first-success-wins" one, where the first parameter list that's compatible with the arguments gets picked. That's why you get the result of the first signature: `string | number`.

   As you can see, that has undesirable consequences in the case of an intersection type with some identical parameter types, since signature lists are just ordered consecutively.<br />
1. When you extract types out with a conditional type, we pick the *last* overload because the assumption is that it's the most general.

   As you can see, this has undesirable consequences when there are multiple signatures with the same parameter lists. That isn't common, but it comes up in intersection types - same as before. <br />

Deciding to *merge* signatures would be a pretty big change. The closest thing I can imagine is something we do when trying to access a method from a union type so that you can do something like `.map(...)` on an `Array<string> | Array<number>` - but I believe we only do that when the method originates from the same source. @weswigham knows more.

Changing the behavior now would be breaking; however, I don't know who relies on the conditional type ordering behavior for overloads because conditional types are fundamentally...just weird when operating on overloads (as described in those links).

**Comment by DanielRosenwasser** [comment]
Retitling the issue - the following code ([playground link](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220909#code/C4TwDgpgBA4grgQwE4BMCSA7YEkGcIDGwAlgPYZQC8UA3gFBSNQAUAHgFxRwYDWGpAdwwBKTqyjFcUDHAC2AIxxQAPlFzAkxDAHMA3AyZtO3PoJFiJUmQqWr5pUgBsICDPoC++uqEhQAgrj4SCTkmNh4hCEU1PRMLBxcvPxColAIgTjAUuKS0nKKSCpqGlp6BoxGiaYpnOlBWVA5Vvm2UPZOLm50nnTe4NDwyCgAKv1UsIioYTj4RGQUEKzYGChSla4gwlQAfI2WEhgAZkoAqlAA-FBnnBgQAG44+gD0T0wAeud0L3GMPgOTIzG1GsBSK7Wcrl6f38GWC81GvmoAXq82mETm5Cgi2Wq3itQwmx2aVhDSaB2OhTOl2u0nujy+r0YHwZPyg0ORmXhQLyNkKdgcEIwvUO3AxC1YCFkYGczG0AM4gymWBmkXmABpiSjyJwOXDQsr0VENQkTMlzDzQbEmMRDiw5UM2MItlbWUgIMA4EgKKx9KzGN84sy-VAA6zmGBkJL3Tgtgl1JodEUQThylB3L04nVOeRHb6mG6PV7Gnn-Yz3p84qGfuHI7Jo0hY5x46Uky0kN06EA)) has the same behavior regardless of intersections - it all comes down to multiple overloads.

```ts
type GuardIntersection = {
    (x: unknown): x is number | string;
    (x: unknown): x is number | boolean;
};

type AssertionIntersection = {
    (x: unknown): asserts x is number | string;
    (x: unknown): asserts x is number | boolean;
};

type GuardType = GuardIntersection extends (x: any) => x is infer U ? U : never;
//   ^?
//      type GuardType = number | boolean

type AssertionType = AssertionIntersection extends (x: any) => asserts x is infer U ? U : never;
//   ^?
//      type AssertionType = number | boolean

function example(guard: GuardIntersection, assertion: AssertionIntersection, x: unknown): number {
    if (guard(x)) {
        return x;
        //     ^?
        //        (parameter) x: string | number
    }

    assertion(x);
    return x;
    //     ^?
    //        (parameter) x: string | number
}
```

**Comment by DanielRosenwasser** [comment]
I guess `duplicate` is the wrong label - https://github.com/microsoft/TypeScript/issues/26591 is related, but this report is about the divergence between overload resolution and inference.

**Comment by fatcerberus** [comment]
@DanielRosenwasser I’m just going on @RyanCavanaugh saying many times in the past that the type of an overloaded function is equivalent to an intersection of the overload signatures.

**Comment by DanielRosenwasser** [comment]
Ah, gotcha - internally it's more of the opposite. When we need the "apparent members" of a type, the signatures naively get smushed into a single signature list.

**Comment by lazytype** [comment]
This isn't the original problem I was trying to solve, but just thought I'd share a use case where this can matter
```ts
function combineTypeGuards2<T, U>(p1: (obj: any) => obj is T, p2: (obj: any) => obj is U) {
    return (obj: any): obj is T & U => p1(obj) && p2(obj);
}

const combined2: (obj: any) => obj is number = combineTypeGuards2(
    (obj: unknown): obj is number | string => true,
    (obj: unknown): obj is number | boolean => true,
);

/**************************************************************************/

type GuardType<T> = T extends (x: any) => x is infer U ? U : never;

function combineTypeGuardsN<T extends Array<(obj: any) => obj is unknown>>(...args: T) {
    return (obj: any): obj is GuardType<T[0]> => args.every(arg => arg(obj));
}

// Doesn't work
const combinedN: (obj: any) => obj is number = combineTypeGuardsN(
    (obj: unknown): obj is number | string => true,
    (obj: unknown): obj is number | boolean => true,
);

/**************************************************************************/

type UglyGuardType<T extends Array<(obj: any) => obj is unknown>> = 
   T extends [(obj: any) => obj is infer U, ...infer Rest extends Array<(obj: any) => obj is unknown>]
        ? U & UglyGuardType<Rest>
        : unknown;

function uglyCombineTypeGuardsN<T extends Array<(obj: any) => obj is unknown>>(...args: T) {
    return (obj: any): obj is UglyGuardType<T> => args.every(arg => arg(obj));
}

const uglyCombinedN: (obj: any) => obj is number = uglyCombineTypeGuardsN(
    (obj: unknown): obj is number | string => true,
    (obj: unknown): obj is number | boolean => true,
);
```
https://tsplay.dev/m0A0RW
