### ISSUE TITLE
TypeScript 4.8 fails to auto import @preact/signals

### ISSUE THREAD

**Issue by motss** [microsoft/TypeScript#50705]
# Bug Report

TypeScript 4.8.3 is causing auto import in VSCode to fail for `@preact/signals`.

See similar reported bug [here](https://github.com/preactjs/signals/issues/111).

### 🔎 Search Terms

auto import, preact signals

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.8.3
- Environment:
   1. VSCode: 1.7.1
   2. macOS: Apple M1 Max, 12.5.1
   3. TypeScript: 4.7.4 and 4.8.3
   4. node: 18.9.0

### ⏯ Playground Link

N/A

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

The issue is replicable with the following steps to reproduce:

1. Create a new folder: `mkdir test-1`
1. Run `npm init` and hit Enter all the way to generate `package.json`
1. Run `npm i -D typescript` to install TypeScript 4.8.3
1. Run `$(npm bin)/tsc --init` to generate `tsconfig.json`
1. Run `npm i @preact/signals` to install `@preact/signals@1.0.3`
1. Run `touch test.ts` and open the file with VSCode then type `signal` to trigger VSCode's autosuggestion to auto import `signal` from `@preact/signals`
1. Observe the behavior above and repeat the steps above for `TypeScript 4.7.4` then compare the behaviors

### 🙁 Actual behavior

With TypeScript 4.8.3, auto suggestion does not show a list of possible paths to auto import `signal` from `@preact/signals`. However, that is not the case when using TypeScript 4.7.4.

<img width="442" alt="auto import fails" src="https://user-images.githubusercontent.com/10607759/189420860-2a0bf656-ab5a-459f-b587-6ab7f0139b68.png">

### 🙂 Expected behavior

You should be able to trigger auto suggestion to allow you to auto import `signal` from `@preact/signals` in TypeScript 4.8.3.

<img width="444" alt="auto import works" src="https://user-images.githubusercontent.com/10607759/189420895-5bc6a2d0-b622-40f5-a78c-1415308482f1.png">

**Comment by andrewbranch** [comment]
What’d you do to get the expected behavior screenshot?

**Comment by motss** [comment]
> What’d you do to get the expected behavior screenshot?

Basically downgrading to TypeScript 4.7.4 from 4.8.3. TypeScript 4.8.3 gives the actual behavior screenshot whereas TypeScript 4.7.4 gives the expected behavior screenshot.

**Comment by andrewbranch** [comment]
@motss I followed your instructions exactly and can’t reproduce.
