### ISSUE TITLE
Branch release-1.4 removed

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#5071]
I noticed the `release-1.4` branch was removed. The tests of gulp-typescript are now failing, as it cannot download typescript 1.4 from that branch. TS 1.4 is downloaded as a git submodule since npm cannot download multiple versions of the same version. Was this branch removed accidentally? Other release branches (1.0.3, 1.1, 1.3, 1.5, 1.6) still exist.

**Comment by DickvdBrink** [comment]
Can't you use the tag? https://github.com/Microsoft/TypeScript/tree/v1.4 That one still exists

**Comment by ivogabe** [comment]
@DickvdBrink Thanks for the suggestion, I'll try that later today

**Comment by RyanCavanaugh** [comment]
We periodically clean up branches. Tags are the intended release markers; please log an issue if there's a missing tag.

**Comment by mhegazy** [comment]
I have restored the branch. but as @RyanCavanaugh, the branches can disappear at anytime. please use the tags instead.

**Comment by ivogabe** [comment]
I'm now using the tag, the tests are passing again. Thanks!
