### ISSUE TITLE
import module from node_modules/@types/[module-name] path instead of actual module path

### ISSUE THREAD

**Issue by Miladxsar23** [microsoft/TypeScript#50722]
# Bug Report

TypeScript 4.8.3 is causing wrong import from node_modules/@types/[module-name] instead of actual path node_modules/[module-name].

### 🔎 Search Terms

import from wrong path,  resolve wrong actual module path

### 🕗 Version & Regression Information

Typescript: 4.8.3

Environment:

- VSCode: 1.70.2
- OS: Windows_NT x64 10.0.19044
- TypeScript: 4.8.3
- Node.js: 16.13.2

### ⏯ Playground Link
N/A

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

I have a problem about ugly imports when i use typescript and when i import a third-party library that made with Javascript and after install its declaration type file with @types/[library-name] in vscode.

actually i was importing the library to my app when i noticed something wrong.

the import is done from "node_modules/@types/[library-name]".

![index](https://user-images.githubusercontent.com/53997528/189616387-5775ed85-932f-4fdf-bf0d-7da7b5961837.png)
 
first i thought that was wrong tooltip of vscode but when i tried to compile my file i got an error:

![index2](https://user-images.githubusercontent.com/53997528/189617585-146b8a7a-1e7b-4e9f-842b-147e222c1648.png)

### 🙂 Expected behavior

Well, i wanna import modules from actual path not wrong path. in above example:

I expect -> path : node_modules/inquirer instead of node_modules/@types/inquirer

**Comment by fatcerberus** [comment]
You installed a JS package (presumably one without built-in type definitions) and its corresponding `@types/`.  Where else would TS get the types from?

**Comment by fatcerberus** [comment]
Incidentally, this is a great argument for why TS *shouldn't* try to do import path rewriting.

To be clear, OP: this is just TS showing you the full path where it loaded the types from, it's only for show and you still get the correct import, i.e. `from 'inquirer'` in the compiled output file.  So having this "wrong" path in the error message can't break anything at runtime.

**Comment by Miladxsar23** [comment]
@fatcerberus hi, in fact this library that i used it, has a api called prompt and i got an error even compile it.since the error tell me the import path is node_modules/inquirer/@types and isn't node_modules/inquirer so i think it can be for wrong resolve from ts compiler.

**Comment by fatcerberus** [comment]
tsc resolves to whatever path gets it the *types* for the library in question, since that’s all it cares about.

If there are functions missing according to the compiler then that just means the `@types` package is wrong (which should be reported to DefinitelyTyped) - but I’m assuming if you uninstall that, you get no types for this library at all.  The only way tsc could resolve to the original package itself is if it included its own typings, in which case you wouldn’t need to install the `@types`.

It’s completely normal that if you have installed the `@types` for a given library then that’s what its imports will resolve to according to tsc.

**Comment by Miladxsar23** [comment]
uh, i found my problem, in fact it seems just for IDE that tell me wrong path and isn't for tsc compiler.

**Comment by Miladxsar23** [comment]
first, i tried to remove node_modules and reinstalled my packages after that saw the problem resolved an there aren't any errors when compiled file again.

I think that the problem was for wrong import. when i tried to import all module with "* as inquirer" while this module export  its api with "default" keyword. so "prompt" function was just for the inquirer that exported with default keyword and doesn't belong to whole export object.
