### ISSUE TITLE
TS2300 when typescript is installed & run locally

### ISSUE THREAD

**Issue by gloomybrain** [Microsoft/TypeScript#5072]
I'm trying to use local installation of ts compiler and having lots of "TS2300" errors.
Step by step:
 - install typescript as a local npm module (`npm install typescript` **without -g**) 
 - create some .ts source files
 - create tsconfig.json file
 - use "rootDir" entry in tsconfig.json to make typescript compile everything inside some project dir
 - use "outDir" entry in tsconfig.json to point output somewhere inside project dir
 - run tsc from local installation (`./node_modules/typescript/bin/tsc -p ./`)  

As result I have lots of "TS2300", looks like tsc for some reason is trying to use some internal .d.ts files twice ore more.
As a workaround I've tried to add "exclude" section to tsconfig with the only "node_modules" inside it. And it worked! No "TS2300" errors anymore.

So the bug is (as it seems to me) that tsc is trying to use node_modules even when it's not inside rootDir.

PS
Please be aware that I'm new to typescript compiler and thanks in advance =)

**Comment by mhegazy** [comment]
If you have a tsconfig.json, with no "files" property defined in it, the whole folder is considered part of your "project". the compiler will load **all** .ts files in the folder and subfolders, this includes node_module (as you pointed in the original post). the correct thing to do is, again as you mentioned, to add node_modules to the "exclude" property.

one handy trick is to use `tsc --init`, that will build you a tsconfig.json file that has the correct shape to get you started

**Comment by mhegazy** [comment]
forgot to mention that once all files are included in the compilation, such as files in packages like the TypeScript package (e.g. lib.*.d.ts) will produce the TS2300 or duplicate identifier errors.

**Comment by mhegazy** [comment]
hope that helps. and welcome to TypeScript :)

**Comment by gloomybrain** [comment]
Ok, I've got it, thanks for your reply. But then what is the purpose to have "rootDir" defined in tsconfig (as I do have defined), if it doesn't tell the compiler where to grab the sources? Or am I missing something obvious?

**Comment by mhegazy** [comment]
The rootDir is used only when outDir is passed to detect the directory structure the compiler needs to recreate in the output.

Here is some more information about options: https://github.com/Microsoft/TypeScript/wiki/Compiler-Options

**Comment by gloomybrain** [comment]
Well, as being said in documentation (thanks for the link) the "rootDir" points to the directory with sources. In my case I have both "rootDir" and "outDir" defined. And I have a file tree like that:
```
project folder
|--out
|    |--main.js
|
|--src
|    |--main.ts
|
|--node_modules
|    |--typescript
|
|--tsconfig.json
```
I have "rootDir" pointing to "src" and "outDir" pointing to "out" in file tree.
So the problem is that even in theese conditions TS compiler somehow is looking through node_modules folder (unless it is explicitly excluded in tsconfig).
Looks like "rootDir" is ignored and always refers to the folder, where tsconfig.json itself is located. Is that true? If so, that behaviour should be either fixed or well-documented.

**Comment by mhegazy** [comment]
> Looks like "rootDir" is ignored and always refers to the folder, where tsconfig.json itself is located. Is that true? 

that is correct.

> If so, that behavior should be either fixed or well-documented.

I updated the docs, it now says:
> `--rootDir` :  Specifies the root directory of input files. **Only** use to control the output directory structure with `--outDir`.

**Comment by mhegazy** [comment]
dose this make sense to you?

**Comment by gloomybrain** [comment]
Being honest I'd loved to see the change in behaviour rather than in documentation =)
Current behaviour looks sophisticated and unclear to me. Let me suggest my opinionated sane behaviour:

1) Having `files` defined means that these (and only these) files should be considered as sources.
2) Having `rootDir` defined means that there is no any other place to get sources from, except this directory and all hierarchy inside it. It also means that we do not have `files` defined in tsconfig.json.
3) Having `--outFile` defined means that the compiler should store one .js file for all .ts files (compile each + combine).
4) Having `--outDir` defined means that the compiler should store one .js file for each .ts file (compile each). And of course it should use the same directory structure as we have for sources (otherwise we'll produce an undefined chaos).

Anyway, my particular problem was solved even before I've created this issue, so I think it might be closed =) Thanks again for your time

**Comment by mhegazy** [comment]
i think all of your suggestions work the way you describe, except for rootDir. and while i would agree that it can be better, i would not want to break existing user code by changing its semantics, let a side introducing yet another flag that has a better behavior.
