### ISSUE TITLE
Number.isFinite invalid

### ISSUE THREAD

**Issue by lucioroadtoglory** [microsoft/TypeScript#50727]
TypeScript is not respecting the callback of `Number.isFinite`.

### Example
```ts
type Product = {
    quantity?: number
};

const product: undefined | Product = {
    quantity: 34,
}

// TypeScript error! product.quantity > 3 returns error because can be undefined (?? what)
if(Number.isFinite(product?.quantity) && product.quantity > 3) { }
```

### Explanation
`Number.isFinite` always return false to every variable that is not `number` (or better, `typeof` equals `number`). You can try all the types (including objects) and will fail if the parameter to `Number.isFinite` is not a number.

### Expected return
```ts
// No errors is right-hand conditional because the left conditional need be a number to continue👇!!
if(Number.isFinite(product?.quantity) && product.quantity > 3) { } // ✅
```

### Solution (partial)
To resolve this for a while, can replace the 
```ts
if(Number.isFinite(product?.quantity) && product.quantity > 3) { }
```
to
```ts
if(typeof product?.quantity === 'number' && product.quantity > 3) { }
```

**Comment by fatcerberus** [comment]
There are no callback functions involved in this example…
