### ISSUE TITLE
Array.reduce prevValue is type of array and not of initialValue type when we return undefined

### ISSUE THREAD

**Issue by pkasarda** [microsoft/TypeScript#50729]
# Bug Report

Array.reduce is not using the proper type when working with prevValue, it should have type of initialValue  but it doesn't

### 🔎 Search Terms
reduce, array, initialValue, currentValue

### 🕗 Version & Regression Information

all versions also nightly

### ⏯ Playground Link

~[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwQLhmArgWwEYFMEDaAujALwwEAMANAIzUBM1AzNQCzUCsRA3ALAAoQVACeAB1wwAgkgDy2AFZkYAb0EwYEdNgBKIAO4RUMhPIXF+AgL6DBoSLESnFxuYuLKC61Zu17DqB5wENJu5iRW1N4qvroGRhQkwaHO4TCRgkS2AvbQMAi4WgA2sOROAHQFACbowLgAFPViBQBuAGpwRei41DDA6Ei4YFAdXbgAlGQAfKreMAD0830DBcOj3TAAliEYOPjlBzDY6LCbsBAAFiDoRVVHkiZmgpHwYVRE4zxAA)~

[undefined](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBAhgJwQLhmArgWwEYFMEDaAujALwwEAMANAIzUBM1AzNQCzUCsRA3ALAAoQVACeAB1wwAgkgDy2AFZkYAb0EwYEdNgBKIAO4QA-KhkJ5C4vwEBfQYNCRYic4tNzFxZcXsDH0GARcLQAbWHIXADoggBN0YFwACkSxIIA3ADU4EPRcahhgdCRcMCgsnNwASjIAPlV1QNwoIrAYdDAY3AAzAEswXBjrDRgAehGYVNxM7NyYHog0LDwESNWYbHRYHtgIAAsQdBCY9ckzC0EbfJcLKiJKniA)

[nullish](https://www.typescriptlang.org/play?ts=4.8.2&ssl=10&ssc=10&pln=10&pc=44#code/MYewdgzgLgBAhgJwQLhmArgWwEYFMEDaAujALwwEAMANAIzUBM1AzNQCzUCsRA3ALAAoQVACeAB1wwAgkgDy2AFZkYAb0EwYEdNgBKIAO4QA-KhkJ5C4vwEBfQYNCRYic4tNzFxZcXsDH0GARcLQAbWHIXADoggBN0YFwACkSxIIA3ADU4EPRcahhgdCRcMCgsnNwASjIAPlV1QNwoIrAYVNxM7NzIrV0DY0iCQuLS8tzeBpgAeim29LHJAEsINCw8BEjNmGx0WEXYCAALEHQQmO3JMwtBG3yXCyoiSp4gA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

it shows prevValue as number

### 🙂 Expected behavior

it should show prevValue as initialValue type

**Comment by fatcerberus** [comment]
initialValue is the initial value of *previousValue*, not currentValue.  currentValue is always an element of the source array, so the type looks correct to me.

**Comment by fatcerberus** [comment]
```ts
const arr: number[] = [0,1,2,3,4,5];

type ArrObj = {
  subRows: ArrObj[];
}

const arrObj: ArrObj[] = [
  { subRows: [] as ArrObj[] },
  { subRows: [] as ArrObj[] },
]

const result = arr.reduce((prevValue, currentValue) => {
   console.log(currentValue);
   return null as any as ArrObj;
}, arrObj[0]);
```

prints

```
0
1
2
3
4
5
```

`number` is the correct type for `currentValue` here.

**Comment by pkasarda** [comment]
sorry everyone... I was in rush :(  issue is/was with prevValue not with initialValue... and steps are [HERE](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBAhgJwQLhmArgWwEYFMEDaAujALwwEAMANAIzUBM1AzNQCzUCsRA3ALAAoQVACeAB1wwAgkgDy2AFZkYAb0EwYEdNgBKIAO4QA-KhkJ5C4vwEBfQYNCRYic4tNzFxZcXsDH0GARcLQAbWHIXADoggBN0YFwACkSxIIA3ADU4EPRcahhgdCRcMCgsnNwASjIAPlV1QNwoIrAYVNxM7NzIrV0DY0iCQuLS8tzeBpgAeim29LHJAEsINCw8BEjNmGx0WEXYCAALEHQQmO3JMwtBG3yXCyoiSp4gA) not sure but when object can be undefined then it's talking about `number` from somewhere...

**Comment by andrewbranch** [comment]
Through the edits and updates, I have no idea what the issue is here or if you still have one, but if you’re unsatisfied with `reduce` inference, it’s probably a duplicate of https://github.com/microsoft/TypeScript/issues/46438

**Comment by fatcerberus** [comment]
Yeah, I have no idea either - OP now says `prevValue` is the wrong type (`number` instead of `ArrObj`), but the playground links show `prevValue` correctly being inferred as `ArrObj`, so...

It seems like the actual problem is OP's mistake - `initialValue` is an `ArrObj` and so that's what the callback is expected to return, but it might in fact return something nullish, causing a type error.

**Comment by pkasarda** [comment]
@andrewbranch yes, it looks like a duplicate of #46438 

@fatcerberus forget to remove comment from playground, I updated the [link](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBAhgJwQLhmArgWwEYFMEDaAujALwwEAMANAIzUBM1AzNQCzUCsRA3ALAAoQVACeAB1wwAgkgDy2AFZkYAb0EwYEdNgBKIAO4QA-KhkJ5C4vwEBfQYNCRYic4tNzFxZcXsDH0GARcLQAbWHIXADoggBN0YFwACkSxIIA3ADU4EPRcahhgdCRcMCgsnNwASjIAPlV1QNwoIrAYVNxM7NzIrV0DY0iCQuLS8tzeQRt8lwsqIkqeIA) in my original comment...

**Comment by fatcerberus** [comment]
@pkasarda If this is a duplicate of #46438 then your issue was the type of the *result*, not the prevValue/currentValue (which seem to be inferred correctly in all of your examples).  Even more to the point, the inferred types don’t matter, since there was an *error* (“no overload matches this call”) on the callback that you didn’t mention.  So it wasn’t at all clear what you were even trying to do.
