### ISSUE TITLE
conditional type with `never extends infer` incorrectly resolves as `never`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#50721]
# Bug Report

### 🔎 Search Terms
never infer conditional type

### 🕗 Version & Regression Information
4.9.0-dev.20220912

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220912#code/C4TwDgpgBAYg9nKBeKA7CA3CAnKEAewEqAJgM5QCWqAZjlACp6HHloCuAtgEY4BQUQVAD8jZkVIVUXXtgFCFogIzyFggFxQATKqiaAzHz4BjOKjLAoNBJviIUSqAHonjcNADk0njg9UpcJYAhmRklADmqEHcADbQwIigkFBemL4AdHwuCgB6wkA)

### 💻 Code

```ts
type Foo = never extends infer T extends number
    ? T extends number
        ? 1
        : 2
    : 3

const foo: Foo = 1 // Type 'number' is not assignable to type 'never'.
```

### 🙁 Actual behavior
`foo` has type `never`, even though there is no `never` type in any of `Foo`'s paths

### 🙂 Expected behavior
type is `1`, since `never` extends `number`

**Comment by jcalz** [comment]
Isn't this just normal behavior of [distributive conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types)?  The checked type `never extends infer T extends number` infers `never` for `T`, which is reasonable (right?)  And then you have `T extends number ? 1 : 2` which is a distributive conditional type (because `T` is a generic type parameter) and so becomes `never` when `T` is `never`; it's distributed over *the empty union* as per #23182.  So I guess I'm not seeing any unexpected behavior here.

**Comment by MartinJohns** [comment]
At first I thought of distributive conditional types as well, but then got bamboozled because there's no generic type involved, not being smart like @jcalz and realizing that the inferred type `T` acts as a generic type.

To confirm this you can disable distributiveness and it works:

```typescript
type Foo = never extends infer T extends number
    ? [T] extends [number]
        ? 1
        : 2
    : 3

const foo: Foo = 1
```

**Comment by DetachHead** [comment]
yeah looks like you guys are right

```ts
// 2 | 1
type Foo = (number | string) extends infer T 
    ? T extends number
        ? 1
        : 2
    : 3

// never
type Bar = never extends infer T
    ? T extends number
        ? 1
        : 2
    : 3

// 2
type Baz = (number | string) extends infer T 
    ? [T] extends [number]
        ? 1
        : 2
    : 3

// 1
type Qux = never extends infer T
    ? [T] extends [number]
        ? 1
        : 2
    : 3
```

**Comment by DetachHead** [comment]
on a related note it seems that `infer extends` doesn't behave the same way:

```ts
type Foo = (string|number) extends infer U ? (U extends string ? 1 : 2) : never
// 1 | 2

type Bar = (string|number) extends infer U extends string ? 1 : 2
// 2
```
[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKAKAzsATgSwHYDmAPngK4C2ARhFgJRQQAewEeAJulPgGY1QCqUAPxpBTFu06ZchYVACMUAFxQATPRV4IANxoBYAFAB6I1DMA9IYcOhIUAEIBDLMjTT8xMlRr1xrDlx4vC5izP5S2B5yiiqqhiZmUJZAA)
