### ISSUE TITLE
import * as alias syntax doesn't work with export = function unless merged with namespace

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#5073]
```ts
declare module "foo" {
  function foo(): void;
  export = foo;
}
```

Can't be included via `import * as f from "foo";`.
(`test.ts(1,20): error TS2497: Module '"foo"' resolves to a non-module entity and cannot be imported using this construct.`)
Whereas
```ts
declare module "foo" {
  function foo(): void;
  namespace foo {}
  export = foo;
}
```

_Can_ be. The distinction seems artificial.

**Comment by mhegazy** [comment]
there is no way in an ES6 module to achieve this. the parallel in an ES6 module world is to `default` export. `import *` will import the namespace component of the export, if it exists, if it does not, it is an error. That you can call the alias as a function in the second case, is the bug i would say.

**Comment by radek-holy** [comment]
@mhegazy and the fact that `import f = require("foo")` works fine with the first example is a bug too?

**Comment by blakeembrey** [comment]
@mhegazy Have you considered enabling a flag for CommonJS interop in ES6 modules? It's inevitable that people will want to use CommonJS requires and have ES6 exports for a period of time.

**Comment by mhegazy** [comment]
what is the expected emit for `import x = require("x")` in ES6?

**Comment by blakeembrey** [comment]
I would say `var x = require('x')`, as you assume people using this would have a CommonJS-capable bundler and are already doing this with say, Babel. That said, in the future it would be possible to align this with the node-proposal as I imagine they'll have interop as well - it's unlikely node will drop an entire ecosystem of hundreds of thousands of modules when adding support for ES6 modules.

**Comment by mhegazy** [comment]
what about AMD/SystemJS/UMD?

**Comment by blakeembrey** [comment]
I'm not sure AMD/UMD or CommonJS would change here. It's all the same emit that already exists, I'm only proposing you enable a way to have these emits **combined** with ES6 exports because the import/export syntax doesn't need to be coupled.

**Comment by mhegazy** [comment]
sorry that was a stupid question.

the issue is we do not know if it should emit to `import * from "x"` or `import x from "x"` if we leave it as `require` then it is not ES6, it is commonJS. what does it mean for users who would want to run this in a non-commonjs engine? e.g. ES6 enabled web browser? `require` does not make sense here.

**Comment by mhegazy** [comment]
that was the main reason to prohibit this. we did not want to be int he business for up-compiling your commonjs to ES6

**Comment by blakeembrey** [comment]
> what does it mean for users who would want to run this in a non-commonjs engine? e.g. ES6 enabled web browser? require does not make sense here.

@mhegazy To follow up on that, the `namespace {}` hack proposed and used in every linked issue here enables the behaviour you describe. It seems there's enough people committing the hack (and having it merged) that it would warrant looking at whether you should enable `import x = require('x')`. If not, perhaps those PRs should start being rejected with proper guidance on how to use the import syntax in these cases (E.g. by recommending people use CommonJS modules instead of ES6).

**Comment by unional** [comment]
Notice that without the hack, TS code cannot target es6 if it consumes cjs module in this format.

**Comment by byrgvt** [comment]
I still can't tell if this was ever intended behavior or not (that using the namespace allows this to pass typecheck), or just a happy accident that now too many people rely on to change.n

It seems an empty namespace gets SymbolType NamespaceModule (1024) and the checker looks for the merged symbol. So basically
> function C {} // symbol type 16
> namespace C {} // symbol type 1024
> (1024 | 16) & SymbolFlags.Module == true (from `resolveESModuleSymbol` in `compiler/checker.ts`)

is what I think is happening?

The PR that added module support https://github.com/Microsoft/TypeScript/issues/2242 explicitly mentions:
> A module that uses export = to export a non-module entity in place of the module itself must be imported using the existing import x = require("foo") syntax as is the case today.

But I don't understand what typescript considers a non-module entity. The actual line in checker that flags these errors is: 
`(!dontResolveAlias && symbol && !(symbol.flags & (SymbolFlags.Module | SymbolFlags.Variable)))` 

So I can get away with pretty confusing stuff like:
```
a.ts
const x = () => 1;
export = x;
```

```
b.ts
import * as x from './a';

x()
```
Which passes compilation fine as with `./node_modules/.bin/tsc b.ts -t "es6" -m "amd"`.

Is a module entity related to https://www.ecma-international.org/ecma-262/6.0/#sec-module-namespace-exotic-objects, which is what the es6 grammar specifies is the type of `import * as foo`?

**Comment by qm3ster** [comment]
So, is this the hack?
And is it still the best way?
```ts
declare module 'nedb-core' {
	class Datastore {
		constructor(options?: {})
	}
	namespace Datastore {

	}
	export = Datastore
}
```

**Comment by LouisWayne** [comment]
@qm3ster I think so.. I don't like the consistency here..have you found any solution for this???

**Comment by qm3ster** [comment]
@LouisWayne well, the reason a hack might be the best we can do is because we are trying to ES6-import something that could never have been ES6-exported.

**Comment by ShiningRay** [comment]
`module.exports.default = Web3;`

**Comment by unional** [comment]
With `esModuleInterop` available, you should not need this hack anymore.
You should be able to do:

```ts
import x from 'cjs'

// instead of 
import * as x from 'cjs'
```

**Comment by aodinok** [comment]
Thanks! `esModuleInterop` works like a sharm!
