### ISSUE TITLE
Mistake in TS1.6 breaking changes doc?

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#5074]
[The doc](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-16) gives the following example:
```
let animalList: Dog | Cat | Turkey = [    // use union type instead of Animal
    {name: "Milo", meow: true }, 
    {name: "Pepper" , bark: true},
    {name: "koko", gobble: true} 
];
```

I think the type should be wrapped in an array.

**Comment by ahejlsberg** [comment]
You're right, thanks for catching this. I just fixed it.

**Comment by DanielRosenwasser** [comment]
Thanks @billccn. In the future you can send a PR at https://github.com/TypeScript-wiki
