### ISSUE TITLE
Recursive mapped conditional types not working when using interfaces (regression between 3.3.3 and 3.5.1)

### ISSUE THREAD

**Issue by ItsaMeTuni** [microsoft/TypeScript#50749]
# Bug Report

### 🔎 Search Terms

recursive mapped conditional types interface generic

### 🕗 Version & Regression Information

- This changed between versions 3.3.3 and 3.5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3#code/JYOwLgpgTgZghgYwgAgCJzHZBvAsAKGSOSgHtSwA1OAGwFcIAuZEOgWwCNoBuA4liAGdIAE2Z5C-YiCGjq9JsmFRQAc16SiAXwI78BAPQHkABTIcaENshrAhyABbQIBMAE8ADigAqsgDzeAHzIALw4fMQA2gDSyKDIANYQbqQwyN4AuszeyBAAHpAgIoLIAEoQCKRQIn7KagA0yHQgCSCkAO4gwQD86f7eMRnBzPA0ghAaWhqGxgDqTiBNgmrIcIugkLCIKGBOyGxwHl4iyO5eyDBVp3sywhAnMHY0J8AloJVQUBVgrp4os8BdgBJcDQeBIUJ9YR+dCYQIaM4oABysnuIIBwNBWwhYQxDhBm3BEEiAHJbqISRluMgjBdaOMCDNkAAJDoQABu0GQ7QWSxWWERyBEwC+CDANDccTA3KqCRKcDeoKK91+5zxJhocHiYV80Ik-DIFHkDGYrE4PAiRHJ93Elqk1pExsUdRA6jtei08NVyNRInRgIcGq1i1xAaDoFJDsp1Np2AEd0dcBNSjAKldyD0jPwtIAqst0wK-nEQHc4CdUqt1liiasxqQZVA5atFYURCr8ILYXBvEWwvriIaqLRk2auFANPwHbbNPbfU7mC63TOPVnBXie+cdf4uxuIF6O0WUQn-btd5D139I77ozTjHGHdRk4uM1mmQBBIp8gttXZcg5He5TiLXYMBJEoACs6GESs4jbcBAUlCtf2LDw6Glel63aWVBG9ZAgTgsAEICYI+ztGJi0SZIK0ybJBl0VcizxAkwW2fCIHg9xIV1MA-DYji3BhDA4ECfdBSPUQT3xatWIIhDzwDZjsQgPjCPcK8ExvWN4zkJNnVTFYtCAA) (version 3.3.3, working as intended)

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.5.1#code/JYOwLgpgTgZghgYwgAgCJzHZBvAsAKGSOSgHtSwA1OAGwFcIAuZEOgWwCNoBuA4liAGdIAE2Z5C-YiCGjq9JsmFRQAc16SiAXwI78BAPQHkABTIcaENshrAhyABbQIBMAE8ADigAqsgDzeAHzIALw4fMQA2gDSyKDIANYQbqQwyN4AuszeyBAAHpAgIoLIAEoQCKRQIn7KagA0yHQgCSCkAO4gwQD86f7eMRnBzPA0ghAaWhqGxgDqTiBNgmrIcIugkLCIKGBOyGxwHl4iyO5eyDBVp3sywhAnMHY0J8AloJVQUBVgrp4os8BdgBJcDQeBIUJ9YR+dCYQIaM4oABysnuIIBwNBWwhYQxDhBm3BEEiAHJbqISRluMgjBdaOMCDNkAAJDoQABu0GQ7QWSxWWERyBEwC+CDANDccTA3KqCRKcDeoKK91+5zxJhocHiYV80Ik-DIFHkDGYrE4PAiRHJ93Elqk1pExsUdRA6jtei08NVyNRInRgIcGq1i1xAaDoFJDsp1Np2AEd0dcBNSjAKldyD0jPwtIAqst0wK-nEQHc4CdUqt1liiasxqQZVA5atFYURCr8ILYXBvEWwvriIaqLRk2auFANPwHbbNPbfU7mC63TOPVnBXie+cdf4uxuIF6O0WUQn-btd5D139I77ozTjHGHdRk4uM1mmQBBIp8gttXZcg5He5TiLXYMBJEoACs6GESs4jbcBAUlCtf2LDw6Glel63aWVBG9ZAgTgsAEICYI+ztGJi0SZIK0ybJBl0VcizxAkwW2fCIHg9xIV1MA-DYji3BhDA4ECfdBSPUQT3xatWIIhDzwDZjsQgPjCPcK8ExvWN4zkJNnVTFYtCAA) (version 3.5.1, breaking)

### 💻 Code

```ts
interface Data {
    rootValue: number;
    nested: {
        nestedValue: string;
    }
}

// Problem lies here
type Test<T> = {
    [K in keyof T]: T extends Record<string, unknown> ? Test<T[K]> : false;
};

// When using an interface, the mapped type for the nested field is incorrect
type WithInterface = Test<Data>;
type NestedInWithInterface = WithInterface['nested']; // false

// However when using a type directly it works as intended
type WithPlain = Test<{
    rootValue: number;
    nested: {
        nestedValue: string;
    }
}>;
type NestedInWithPlain = WithPlain['nested']; // { nestedVaue: string }


// Using a type instead of an interface also works as intended
type DataType = {
    rootValue: number;
    nested: {
        nestedValue: string;
    }
}

type WithType = Test<DataType>;
type NestedInWithType = WithType['nested']; // { nestedVaue: string }


// And using another mapped type that's just an identity of the input also works
type Identity<T> = {
    [K in keyof T]: T[K]
}

type WithInterfaceIdentity = Test<Identity<Data>>;
type NestedInWithInterfaceIdentity = WithInterfaceIdentity['nested']; // { nestedVaue: string }
```

### 🙁 Actual behavior

When using a recursive mapped conditional type (not sure if I named it correctly), typescript breaks when using an interface as the generic parameter, but works when using inline types, type aliases and a mapped type.

### 🙂 Expected behavior

Expected `NestedInWithInterface` to be `{ nestedVaue: string }`, just like `NestedInWithPlain`, `NestedInWithType`, and `NestedInWithInterfaceIdentity`.

**Comment by whzx5byb** [comment]
See https://github.com/microsoft/TypeScript/issues/50087#issuecomment-1199411533

**Comment by ItsaMeTuni** [comment]
> See [#50087 (comment)](https://github.com/microsoft/TypeScript/issues/50087#issuecomment-1199411533)

Of course! It makes total sense, I can't believe I missed that and spend hours debugging this... Sorry about the trouble and thanks for the quick response.
