### ISSUE TITLE
Infer return type based on argument type

### ISSUE THREAD

**Issue by random42** [microsoft/TypeScript#50772]
# Bug Report

### 🔎 Search Terms

infer return type based on argument type

### 🕗 Version & Regression Information

4.8.3

### 💻 Code

```typescript
export type f1 = <T extends string>(s: `_${T}`) => `+${T}`;

export type ReturnTypeWithArg<
  F extends (...args: any[]) => any,
  A extends Parameters<F>[0],
> = F extends (arg?: A) => infer U ? U : never;

export type R = ReturnTypeWithArg<f1, '_a'>;
```

### 🙁 Actual behavior

type R is `+${string}`

### 🙂 Expected behavior

type R should be `+a`

I would like to infer the return type based on the argument. Is there a way I can do it?

**Comment by MartinJohns** [comment]
Weird, I can't find a playground link, I'm sure the issue template asks for it.  
Regardless, the described actual behavior is incorrect, as `R` resolves to `never`.

**Comment by fatcerberus** [comment]
You can't get the return type of a generic function based on a prospective call, but you can use an instantiation expression (4.7 and later) to get the return type based on `T`: [Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIEYAeAFXhAA8MRVgBneOjGLVAcwD4AKOgLngAGAfQAkAbxIBfAQEp+AgNTipAgNwAodZQAOOGBngYAntoQAlEBmQxUJEyADqWDAAsAgjDZF18eADFyKhp6eC4AOgjYNj54KFQjAG0AXRl4AF4OWPiAGh94N0DqWgYABVgoAFtLEBg6Ij8OBIAGJNzMtP9C4IYuKIB+fjdUjPhWRBr4AFV4Pqn4flQQADcajS0KXX1De3gzdN3La1t7ImNTHERCIgByKGuODg0AeiffN-f4AD0+9SA)

**Comment by random42** [comment]
Sorry, on my VSCode resolves differently. Regardless, why is that not possible? Typescript can infer the return type while writing code, so why can't I do that with a infer expression?

**Comment by fatcerberus** [comment]
Because type parameters are only inferred when calling the function.  It's just the way the compiler is designed.  When you feed a generic function type into an `infer` expression, it's looking at the generic signature itself, without instantiating the type parameters.

**Comment by random42** [comment]
Ok, I'll close this, if you wanna take a look at this I'll
