### ISSUE TITLE
TypeScript Handbook ---> Object Types ---> describe error

### ISSUE THREAD

**Issue by CaoXueLiang** [microsoft/TypeScript#50788]
`that its internal contents can’t be changed `  
  
 Should be changed to  

 `that its internal contents can be changed`

[![Snipaste-2022-09-15-20-19-46.png](https://i.postimg.cc/FRRzqMfX/Snipaste-2022-09-15-20-19-46.png)](https://postimg.cc/yJM73rXL)

**Comment by MartinJohns** [comment]
The text is correct. It's double negation: "doesn't imply contents can't be changed".
