### ISSUE TITLE
ES6 Promise definition has non-optional property [Symbol.toStringTag]

### ISSUE THREAD

**Issue by bgoerdt** [Microsoft/TypeScript#5078]
I am using TypeScript with AngularJs I am trying to cast Angular's ng.IPromise to an ES6 Promise, but I am getting the following error:

Type 'Promise<any>' has non-optional property '__@toStringTag' which is not present in the type 'IPromise<any>'
 
Can the [Symbol.toStringTag] property be made optional so that this Promise definition can interface with other definitions?

**Comment by rbuckton** [comment]
The `Promise` interface in lib.es6.d.ts matches the API for the specification for ES6. There is also a `PromiseLike` interface in both lib.d.ts and lib.es6.d.ts:

```ts
interface PromiseLike<T> {
    /**
    * Attaches callbacks for the resolution and/or rejection of the Promise.
    * @param onfulfilled The callback to execute when the Promise is resolved.
    * @param onrejected The callback to execute when the Promise is rejected.
    * @returns A Promise for the completion of which ever callback is executed.
    */
    then<TResult>(onfulfilled?: (value: T) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => TResult | PromiseLike<TResult>): PromiseLike<TResult>;
    then<TResult>(onfulfilled?: (value: T) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => void): PromiseLike<TResult>;
}
```

Are you targeting ES6?
