### ISSUE TITLE
Object literal method completions include `?` for optional parameters

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#50796]
# Bug Report

https://user-images.githubusercontent.com/3277153/190480953-1a3fd9d1-cc78-4983-9598-22b254137d23.mp4

### 🔎 Search Terms

object method completion

### 💻 Code

```ts
interface Foo {
  method(x?: string): void;
}
const foo: Foo = {
  /**/
}
```

### 🙁 Actual behavior

`method(x?) { }` is inserted

### 🙂 Expected behavior

`method(x) { }` is inserted

**Comment by magic-akari** [comment]
I am willing to fix this issue.

**Comment by magic-akari** [comment]
https://user-images.githubusercontent.com/7829098/190550769-0837a8fa-11e3-473e-b410-5f9d27578f8d.mov

I was thinking about why completion for object method  is differ from class method. Then I found this pull request.
- #48607

So it's an intentional design, right?

**Comment by gabritto** [comment]
> Screen.Recording.2022-09-16.at.11.28.56.mov 
> I was thinking about why completion for object method is differ from class method. Then I found this pull request.
> 
> * [Don't have type annotations on suggested object literal methods #48607](https://github.com/microsoft/TypeScript/pull/48607)
> 
> So it's an intentional design, right?

@magic-akari
Yes, you're right. It is intentional that object methods don't have the type annotations (they could have, but we opted for not having them in the completion we offer), and because of that we shouldn't mark the parameters as optional with a `?`. Thanks for fixing this! :)

**Comment by DanielRosenwasser** [comment]
Thanks @magic-akari!
