### ISSUE TITLE
If I search Typescript I find myself in the generated JavaScrpt

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#5079]
A number of times recently I've run into problems when I search for a function in TypeScript, deleted it and find that I'm not getting errors for the missing references. Turns out it found the generated .JS not the source. This is VS2015 fully updated. 

How do I prevent it from stumbling into the .JS code.

Or is this a bug one one of the addins for Visual Studio? If so which one?

**Comment by mhegazy** [comment]
when you trigger Search All dialog in VS, restrict the search to "*.ts" files:

![image](https://cloud.githubusercontent.com/assets/8000722/10252916/48f6f522-68ef-11e5-80c9-5de49f938835.png)


the other option, do not include the generated .js files in your project.

**Comment by BobFrGit** [comment]
That's not a real answer. Sure i can remember in this one case to use the long search but the generated .js file isn't included in the project so it shouldn't be searched by default.

**Comment by DanielRosenwasser** [comment]
You can use our **Navigate To** functionality. Trigger it with `Ctrl+,`.

**Comment by BobFrGit** [comment]
Thanks for the reminder of ^,

But still, searching for non-included items is a bug. And once we open that can-of-worms would be nice to get a fix to say that I don't want to search inside comments (similar to the options for replaceing names)

**Comment by danquirk** [comment]
I'm inclined to agree here. Why would people want the default search experience to include a duplicate result for every search result?

**Comment by BobFrGit** [comment]
Not just duplicate -- the problem is that you don't know you're in the JS which is generated code and that window should be readonly or at least marked so it is obvious that you aren't editing the source.

**Comment by danquirk** [comment]
Right, there're many reasons it's a suboptimal default. At various points we've debated the merits of having the JS files shown in Solution Explorer at all, which suggests the search results in those files are equally unimportant.

**Comment by mhegazy** [comment]
I am not sure i understand the issue.. My search all behavior is what you mention. if i search all with with the `look in` is `Entire Solution`, in a .csproj, created from the "HTML Application with TypeScript" template, and i hit `Find All` I only see .ts files.

The .js files are only included if you have them included in the project, or you are searching in a directory.

The generated files are not included in the project by default. if you do not want the generated .js files to not show up in search all, do not include them in the project. if you include them, how would we know you do not want them in there.

Moreover, this has nothing to do with TypeScript, this is a VS search dialog. the right place would be https://connect.microsoft.com/visualstudio

**Comment by danquirk** [comment]
@BobFrGit can you clarify what project template/setup you have that's making JS show up?

**Comment by BobFrGit** [comment]
I just use new or existing projects with as a blank typescript website. The Typescript build:
Ecma 5
JSX/TSX none
Compile on save, allo implicit any
CommonJS
keep comments
combine JS
Do not emit on error
generate source maps
JS is NOT included

What other settings might help?

**Comment by mhegazy** [comment]
if you are using a website, and your sources are emitted to the same location, they will always be part of the project. i would either search only in the sources directory, or limit the search to "*.ts".

**Comment by BobFrGit** [comment]
I'm not sure what you mean by "using". The project directory is the website and the .JS is emitted there. But it is not included so why would it be searched? In any case it's dysfunctional behavior whether it's a coding bug or a design flaw.

**Comment by RyanCavanaugh** [comment]
Can you post a screenshot of the 'Find' dialog as you have it configured?

**Comment by BobFrGit** [comment]
OK, I did more investigating and this may be my error. In one project i did have a .ts restriction and other I didn't but that is spurious for searching .js. What is really going on is that in one project I did a clone and accidentally included the .js in the project hence making it searchable.

So it's a user error but VS is not out of the woods because a generated file should be visually distinct from a source file because of these kind of errors. I've related problems with VS in finding that if I searched into a generated XML file or other code I'd get all sorts of error messages that occurred merely because the file had a tab.

**Comment by mhegazy** [comment]
>  a generated file should be visually distinct from a source file because of these kind of errors. 

I am not sure there is much we can do here. establishing the "generated by" relationship is not possible all the time, as it depends on your build scripts, and what MSBuild tasks ran when, etc.. marking all .js files as outputs would not be correct either.

**Comment by BobFrGit** [comment]
Perhaps this should be made a Visual Studio feature request -- an explicit way to mark such relationships in build files and by other means.

**Comment by mhegazy** [comment]
Do you mind filing this as a uservoice request for VS: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015
