### ISSUE TITLE
Unexpected circularly references error in VSCode

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#50795]
# Bug Report

### 🕗 Version & Regression Information

- This changed between versions 4.6.4 and 4.7.3

### ⏯ Playground Link

cannot reproduce in playground

### 💻 Code

```ts
function fn(Foo: number) {
    type Foo = typeof Foo;

    return 0 as any as {x: Foo};
}
```

### 🙁 Actual behavior

In vscode with TS version > 4.6.4 it reports `'Foo' is referenced directly or indirectly in its own type annotation.ts(2502)`. But it works well in the playground. 

This is first reported by @TechQuery in https://github.com/microsoft/TypeScript/issues/50792#issuecomment-1248587467, and I realize it may be related to https://github.com/microsoft/TypeScript/issues/50161 and https://github.com/microsoft/TypeScript/issues/50191 since the behavior is quite similar.

### 🙂 Expected behavior

No error.

**Comment by DanielRosenwasser** [comment]
I don't see this locally in TS 4.8. Do you have a single file and a `tsconfig.json` where this occurs?

**Comment by JoshuaKGoldberg** [comment]
I _think_ this is another symptom of the same issue, this time with a default value of a parameter: [[TypeScript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4hB2EBOBLAxgFXBAPBqEAHsAgCYDOU5wq8A5lALxU0r0B8TUArvKRADM2EUgG4AUOKJgA9kmBQ0M+NSh0EydAEEkSGQHcAYrzTAUyrngLEylarTrsAFOKhQZYM8vIAuWBtRMbDxOZgAiMKgAQ0pQSBkBd09zFXEASiZOXn4hRDFxIA)]

```ts
type GenericType<T extends string = string> = undefined;

export const genericArrowFunction = <T extends string>(
  options: GenericType<T> = "" as typeof options
) => undefined;
```

```plaintext
'options' is referenced directly or indirectly in its own type annotation.
```

**Comment by jakebailey** [comment]
Two words: semantic tokens.

This appears to have the same sort of problem that #50161 had, but thankfully can be tested in the same way as in #52373 as well, so I can reproduce it reliably.
