### ISSUE TITLE
Incorrect template literal type indexing for TS version below 4.4

### ISSUE THREAD

**Issue by huynl-96** [microsoft/TypeScript#50806]
# Bug Report

### 🔎 Search Terms

- Template Literal Type Indexing

### 🕗 Version & Regression Information

- This changed between versions 4.3 and 4.4

### ⏯ Playground Link

[Error on TS 4.2](https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBAYwgOwM7wObBgaWAT1TgF44AeAKDjgBU5QZhkATIgJWCSmbIAUoIYYLHx58AGjgBDZPgB84qnBz0QjFkQDWBCADNaJONvx7aFOQAolEAEYArTjABcZgJQucAbQC6JOXABvJShsAFcoZDgAeXtHADpjVAtbBwQYV2kiL28KAF8KCgBLZEYoXSkEYDgASQBZKTAwYowAMULgABtmQKUOqRtOl3QoZqUAWwam5AwhmBHpvIKkNHgJxuaAYVD0CDG2ztYXDi4eJQADBG2YXYB9VF0bxjGwPsYb3Xaum4ASAOHm3JnRTUOqTZr7LrmQwBfIULC4AhJNZTDBbHZ7T6sVxxXTQACiFQAFhYLMYMsR-EFqMjNlddhDWJ5jN44jTpoYAOQcvKuIA)

[Error on TS 4.3](https://www.typescriptlang.org/play?ts=4.3.5#code/KYDwDg9gTgLgBAYwgOwM7wObBgaWAT1TgF44AeAKDjgBU5QZhkATIgJWCSmbIAUoIYYLHx58AGjgBDZPgB84qnBz0QjFkQDWBCADNaJONvx7aFOQAolEAEYArTjABcZgJQucAbQC6JOXABvJShsAFcoZDgAeXtHADpjVAtbBwQYV2kiL28KAF8KCgBLZEYoXSkEYDgASQBZKTAwYowAMULgABtmQKUOqRtOl3QoZqUAWwam5AwhmBHpvIKkNHgJxuaAYVD0CDG2ztYXDi4eJQADBG2YXYB9VF0bxjGwPsYb3Xaum4ASAOHm3JnRTUOqTZr7LrmQwBfIULC4AhJNZTDBbHZ7T6sVxxXTQACiFQAFhYLMYMsR-EFqMjNlddhDWJ5jN44jTpoYAOQcvKuIA)

[Resolved on TS 4.4](https://www.typescriptlang.org/play?ts=4.4.4#code/KYDwDg9gTgLgBAYwgOwM7wObBgaWAT1TgF44AeAKDjgBU5QZhkATIgJWCSmbIAUoIYYLHx58AGjgBDZPgB84qnBz0QjFkQDWBCADNaJONvx7aFOQAolEAEYArTjABcZgJQucAbQC6JOXABvJShsAFcoZDgAeXtHADpjVAtbBwQYV2kiL28KAF8KCgBLZEYoXSkEYDgASQBZKTAwYowAMULgABtmQKUOqRtOl3QoZqUAWwam5AwhmBHpvIKkNHgJxuaAYVD0CDG2ztYXDi4eJQADBG2YXYB9VF0bxjGwPsYb3Xaum4ASAOHm3JnRTUOqTZr7LrmQwBfIULC4AhJNZTDBbHZ7T6sVxxXTQACiFQAFhYLMYMsR-EFqMjNlddhDWJ5jN44jTpoYAOQcvKuIA)

### 💻 Code

I'm having an issue related to TS versions below 4.4 (in my case are 4.2 and 4.3)

I created a function to get all object keys with their return types (since `Object.keys` returns `string[]` by implementation)
```ts
export const getKeys = <
  T extends Record<PropertyKey, any>,
  K extends keyof T = keyof T
>(
  object: T
): K[] => {
  return Object.keys(object) as K[]
}
```

Then I created an object accepting template literal keys with the following format `custom_sf_template_field_${string}`

```ts
interface IMappingField {
  label: string
  mapping: string
}

const mappingCustomFields: Record<`custom_sf_template_field_${string}`, IMappingField> = {}
```

### 🙁 Actual behavior

When I try to loop through the keys of `mappingCustomFields` to update each object, TS doesn't seem to compare template literal type for indexing correctly.

```ts
getKeys(mappingCustomFields).forEach((key) => {
  // Element implicitly has an 'any' type because expression of type '`custom_sf_template_field_${string}`' can't be used to index type 'Record<`custom_sf_template_field_${string}`, IMappingField>'.(7053)
  mappingCustomFields[key].mapping = ''
})
```
<img width="687" alt="image" src="https://user-images.githubusercontent.com/15758406/190650899-9583fdce-6c51-4fce-ae11-8dde516afb7a.png">

### 🙂 Expected behavior

I wonder if there is any way to fix this without upgrading TS version since I'm using other dependencies that running on TS 4.2

**Comment by MartinJohns** [comment]
Use a type assertion.

**Comment by jcalz** [comment]
This isn’t a bug in TypeScript; the feature you are trying to use was [introduced in TS 4.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures).

**Comment by huynl-96** [comment]
@jcalz Thanks for your helpful information
But I'm wondering if we could have some kind of workaround for this feature for the lower versions
Currently, I have to type the key back as `string`, but it doesn't look like a good practice 😢 
```ts
const mappingCustomFields: Record<string, IMappingField>
```

**Comment by MartinJohns** [comment]
@huynl-96 A type assertion is your only alternative until you're able to update your TypeScript version.

**Comment by huynl-96** [comment]
@MartinJohns Thanks for your suggestion, I'll try that approach
