### ISSUE TITLE
Difference in behaviour of inferred function argument when function is declared using arrow syntax vs object syntax

### ISSUE THREAD

**Issue by tankers746** [microsoft/TypeScript#50805]
# Bug Report

I am struggling to understand the behaviour of the inference here, what is the correct behaviour? 

```
type Fn<T> = (arg: T) => void;
type FnObj<T> = { fn(arg: T): void }['fn'];

type FromFnArray = [Fn<'a'>, Fn<'b'>] extends Array<Fn<infer U>> ? U : never; // never
type FromFnObjArray = [Fn<'a'>, Fn<'b'>] extends Array<FnObj<infer U>> ? U : never; // "a" | "b"

```

### 🔎 Search Terms
inferred function argument
arrow syntax
object syntax

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

**Comment by fatcerberus** [comment]
The difference in behavior is because methods are bivariant.  If you change the types to
```ts
type Fn<T> = (arg: T) => void;
type FnObj<T> = { fn: (arg: T) => void }['fn'];
```
then both conditional types resolve to `never`.

**Comment by tankers746** [comment]
I understand thanks

**Comment by MartinJohns** [comment]
Next time please fill out the issue template. :-)
