### ISSUE TITLE
Assert function can be used to change types, not narrowing down types.

### ISSUE THREAD

**Issue by Lunuy** [microsoft/TypeScript#50801]
# Bug Report

### 🔎 Search Terms
- Assertion
- Assert function
- Narrowing
- Type guard

### 🕗 Version & Regression Information

- I don't know when this started.
- My current typescript version is 4.8.3.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/LAKA9GAEAiCmBmBLAdrSBhA9sgLgQxVgCdJ5MSAVATwAdYAKAOUx1PMgDc8AbAV1gCUAOlARIAQQAyAdXEBNAMqQF4igEkFAMTUBRaAC5lsHADUe-ADziANJBMA+SLAAeOWMgAmAZzuRQoFDcieDwAYzQAIUxnSABvUEhEznNYQ3ocAAtELwBtAH0AcWNJPC8cAGlYKgtM7PsAXSdXd29IVA5iSAB+SF5kAGtkTAB3ZEhDWtzC4tKKqpqsrwaBAG5QAF81kFAcWjR0Ilg8NyjnCwdIAF4jUxSLU9sHLZ29yGmcErLK6opbPO+mm5PD4ykQUABzK6QADk0MclwSSQABgASWL-KrrAAMSMBLR8-SqmHgkAo3URSSS70+cx+tlR6O+2KR9gp4zZlIxVDxwMghKoxNJ5JAlNFVO+HKS+klYvaxGeIF2dEgRVufFgFjJLiBrVO8NJOWhXHV0PqWyVaAUxjM6s1j3hbIobIAZHFIDlypAUJAdM5QnwPBr+YLfjDjfw4fVDHKSOsXW6PV6xvRqbNvprHNr8W1YB0SD1oVjoeNIAzU195hR7MyBFHfJt-Nsm2IdAANcQAWQACpIdJAcJhel5ItFG2IsLgCKgSAPIKFsPhvaCIZB2MheABbABGxEb-tKPgUODByHBAHkiIxNzuiJq9qcebroo54iKkjQwVw3Ml1YZl6fIAAHzaa95UbSl52QUFeFCAciHocNUhVa07moOg9QEOIZX7RYhEQqF8NKSA8GQKgtkpOMm0pYc1X4ehQT-Y8IQEQwD2IHAfEmL1DyY08LyvbdiAsK1aI1NDYAeSB-3Bex7HIpIaJtOj1w3aNQKIFjiK8YciA4nDsm45RePPS91OElDbXEySVJvWT5MSRSUgQlJGJPSFgJs4hMNfMVEkmPCUgIlJ7MgSi2XBCy6M01UlLE+9nywt8xUOHBeCIMZ-MInwSLItlKLCkB4D6WDEGwSANynehvLZSCyjnBcp2IQwjzc-izIOI4TmiCxPKIWSoVQYYjNa0zBNvDrjgk7retk+gAEZVnApJatYFS5qhSDF2nIQItEqqVkgMRdtiyAUrSqCQLGpbEk2xqiCERz1XoaFxAidBoVWXzEjEChFjnDISIinxbsIGdXlnaSauwOrQXW64Qe246nM+o7IrQM70pBYzIHoIZVvUgRrvqydQYetH6AAJgAZgAFk+r7vqgX6DNCAHT1gYGGtB-twcHXqoag-GNwpjaucR8mUagJH1VO4xzp8XqcbxqTjMJqjlrF4gyb26FoB0TQPoOr6xCEU2cZUDsdEw02RCS4mYePEX4c1+7paihUIJd7XYvoABWAA2AB2Ra7ZWy6qdFknxb2kP1iAA)

### 💻 Code

```ts
// Define Container for Type(Not for value).
// ALWAYS SATISFIED: SetValue<A, V> is assignable to A 

interface Box {
    value: (this[_GetLastKey<this>] extends never ? unknown : this[_GetLastKey<this>]);
};

type CreateBox<V> = SetValue<Box, V>;

type _GetLastKey<T, _Key extends string = ''> =
    `${_Key}0` extends keyof T ?
        _GetLastKey<T, `${_Key}0`>
    :
        _Key extends keyof T ?
            _Key
        :
            never;

type GetValue<T extends Box> = T['value'];
type SetValue<T, V> =
    T
    & { [K in Exclude<keyof T, 'value'>]: never }
    & { [K in (_GetLastKey<T> extends never ? '0' : `${_GetLastKey<T>}0`)]: V };



// EXAMPLE to use Box

// Container to contain string or number

class StringOrNumber<TypeBox extends Box> {
    private value: string | number;

    constructor(value: GetValue<TypeBox>) {
        this.value = value as any;
    }

    setValue(str: string): asserts this is StringOrNumber<SetValue<TypeBox, string>>;
    setValue(num: number): asserts this is StringOrNumber<SetValue<TypeBox, number>>;
    setValue(value: string | number) {
        this.value = value;
    }

    getValue(): GetValue<TypeBox> {
        return this.value as any;
    }
}

function main() {
    const container: StringOrNumber<CreateBox<number>> = new StringOrNumber<CreateBox<number>>(1);

    const num1 = container.getValue(); // getValue returns number

    container.setValue('ABC');         // This changes container type to string
    const str1 = container.getValue(); // getValue returns string (not number)

    container.setValue(234);           // This changes container type to number
    const num2 = container.getValue(); // getValue returns number (not string)

    container.setValue('DEF');         // ... (SAME) ...
    const str2 = container.getValue();

    container.setValue(567);
    const num3 = container.getValue();
}
```

### 🙁 Actual behavior
Return type of `container.getValue` changes depending on each `container.setValue` calls. The type is not narrowed down, it's changed.

### 🙂 Expected behavior
```ts
container.setValue(123);
container.setValue('ABC');
container.getValue(); // Should return never
```
Assertion should only narrow down types, should not be able to change types freely. So after two different types of `setValue` function called, return type of `getValue` should be `never`.

**Comment by andrewbranch** [comment]
But the value _is_ changing in the implementation. The actual behavior is modeling your code, whereas your expected behavior would introduce errors on this perfectly working implementation. 😄 I think you _could_ come up with an example that demonstrates why your expected behavior could be desirable, but this one seems to support the actual behavior.

**Comment by andrewbranch** [comment]
Note that the behavior you expect does happen when the thing you start with is a union:

```ts
declare function f<T>(x: any): asserts x is T
declare const x: string | number;

f<string>(x);
x; // string
f<number>(x);
x; // never
```

Non-unions and type predicates / assertion functions are a little different. The only thing we could possibly do is take the intersection of every type you’ve asserted `container` is, which would probably render it unusable like you expect, but it would also be super expensive to compute those intersections. And, the current behavior correctly models what’s happening here. I think this is working as intended.
