### ISSUE TITLE
DateConstructor doesn't support null as a possible input

### ISSUE THREAD

**Issue by gergobergo** [microsoft/TypeScript#50804]
# Bug Report

In of the the implementation of or code we passed a `string | null` value to the Date object contructor. Based on the MDN documentation, this is a valid use case for Date object.

![image](https://user-images.githubusercontent.com/25322572/190572797-4d365497-38c2-460c-901a-ba28fcd541e4.png)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

### 🔎 Search Terms

- Date
- null
- constructor

### 🕗 Version & Regression Information
https://github.com/microsoft/TypeScript/blob/a7548745d78858f94f46f643b2a6edcec12e3a91/src/lib/es2015.core.d.ts#L69

It seems to me that Typescript never supported null as a possible input for `Date` object.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.9.0-dev.20220915&ssl=2&ssc=21&pln=2&pc=31#code/MYewdgzgLgBAJgQygUwEIE8DKUBOBLMAcxgF4YxkB3GAESWQAoAmABiaYFoWAODgZhYBKANwAoUJFiIUGAHIBXADaLS5KrXoMwSxSKA)

### 💻 Code

```ts
const dateByNull = new Date(null);
```

### 🙁 Actual behavior

The compiler doesn't allow to pass `null` as a value.

### 🙂 Expected behavior

The compiler should allow pass `null` as input to the `Date` constructor.

**Comment by MartinJohns** [comment]
Dupicate of #12034. Used search terms: `date null in:title`

**Comment by gergobergo** [comment]
Thank you @MartinJohns  this makes sense this way. I will close the issue.
