### ISSUE TITLE
tsc interprets glob patterns wrong

### ISSUE THREAD

**Issue by eng-dibo** [microsoft/TypeScript#50807]
# Bug Report

I try to run `tsc` against a set of files using glob patterns, but it seems that tsc interprets it wrongly.
for example this cmd `tsc config/**/*.{m,}js --declaration` should be interprets as all .mjs and .js files in the specified path
but tsc treats it as a single file with the extension `.{m,}js`.
this give me the error `File 'config/**/*.{m,}js' has an unsupported extension. The only supported extensions are ...`

I also tried `.{mjs,js}` and `{.mjs,js}`

the actual **full** command:
```
npx -p typescript tsc config/**/*{.mjs,js} --declaration --allowJs --emitDeclarationOnly --esModuleInterop
```

### 🔎 Search Terms
- tsc glob patterns
- tsc cli options
- tsc FAQ

### 🕗 Version & Regression Information
I use `npx` so the latest version is used

<!-- When did you start seeing this bug occur?
recently

### ⏯ Playground Link

it is a cli issue, playground wouldn't help us here.
is there a playground for CLI testing?

**Comment by MartinJohns** [comment]
These kind of glob patterns are not supported. See #47001.

You should be able to just pass both along: `tsc config/**/*.js config/**/*.mjs`

**Comment by jbarker47** [comment]
Ironic, this links to #47001 as duplicate and completed, which in turn links back to this as duplicated and closed. Way to pass the buck guys.

I love TypeScript, but it continues to amaze me how Microsoft adamantly refuses to consider adding even the most basic support for quality of life enhancements considered to be industry-standard by the rest of the development community.

**Comment by RyanCavanaugh** [comment]
@jbarker47 #47001 is not marked as completed
