### ISSUE TITLE
Improve line lengths for `tsc --init`

### ISSUE THREAD

**Issue by AlexWayfer** [microsoft/TypeScript#50819]
# Suggestion

I've ran `tsc --init` and got very large lines of (commented) config + comments.

I believe commented descriptions should be above (commented) configuration lines.

Also, as a notice: it seems very difficult to contribute into this thing:

https://github.com/microsoft/TypeScript/search?q=Opt+a+project+out+of+multi-project+reference+checking+when+editing

![image](https://user-images.githubusercontent.com/6510020/190878351-2cb6850c-3a53-4d0f-be78-786de5fe41f3.png)

(there are 2 pages of this, have you heard about DRY?)

## 🔍 Search Terms

"Opt a project out of multi-project reference checking when editing", for example. Or just `init`.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

You have nothing about configuration or initialization in the last point! Do you know? It's not okay when you have such features and asking for such checks.

## 📃 Motivating Example

Move comments above (commented) configuration lines at least, probably split them.

## 💻 Use Cases

Just use the EditorConfig with `max_line_length` configuration on your `tsc --init` output!

**Comment by fatcerberus** [comment]
> there are 2 pages of this, have you heard about DRY?

Those are baselines, they are the output of an automated test run (in this case, testing tsconfigs generated with different options), which is compared against the output of future test runs.  DRY doesn't apply because a human didn't write them.

> You have nothing about configuration or initialization in the last point! Do you know? It's not okay when you have such features and asking for such checks.

What are you talking about?

**Comment by AlexWayfer** [comment]
> DRY doesn't apply because a human didn't write them and they're not meant to be manually edited.

I've not seen description in the documentation what is original file and what are generated ones.



> > You have nothing about configuration or initialization in the last point! Do you know? It's not okay when you have such features and asking for such checks.
> 
> What are you talking about?

I'm about the last "check":

> [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

This issue is about configuration (or project initialization), and there are 0 founds for "init" or "config". But I have to check this mark somehow. How should I?

**Comment by fatcerberus** [comment]
Those are high-level guidelines used to steer the TypeScript project *as a whole*, they’re not meant to be a low-level specification for individual improvements.  It seems pretty safe to assume a small cosmetic/readability adjustment to the output of `tsc --init` (an already existing feature) isn’t going to violate the high-level design goals for the language.

**Comment by RyanCavanaugh** [comment]
Vertical space matters too. I don't really wait to paint the bikeshed blue just to have someone else tell us that it would be nicer in green.

**Comment by fatcerberus** [comment]
> I don't really wait to paint the bikeshed blue just to have someone else tell us that it would be nicer in green.

You're right.  It should have been pink with purple polka dots!

**Comment by AlexWayfer** [comment]
> Those are high-level guidelines used to steer the TypeScript project _as a whole_, they’re not meant to be a low-level specification for individual improvements. It seems pretty safe to assume a small cosmetic/readability adjustment to the output of `tsc --init` (an already existing feature) isn’t going to violate the high-level design goals for the language.

I don't get your answer. I mean… in details — yes, but… what is "a whole" if not a something containing a lot of "a small" parts? 

Here it's again:

I'm a newcomer to TSC. I love [EditorConfig](https://editorconfig.org/), for example. I've setup a new project, I've ran `tsc --init` and get a mess of lines, which _I don't say extra_, but _can be improved_ at least from the sight of alignment, especially according to your _general_ guidelines.

I hope you understand my frustrating.

I'll fix the `--init` output anyway in my project, according to my _and your_ guidelines. But I just wanted to improve the default output for everyone, and leave no questions behind.

**Comment by AlexWayfer** [comment]
> Vertical space matters too. I don't really wait to paint the bikeshed blue just to have someone else tell us that it would be nicer in green.

And please, let's try to avoid unacceptable analogies. I don't talk about bikes and colors, OK?
