### ISSUE TITLE
Inconsistent TS2345 error when using function generics

### ISSUE THREAD

**Issue by moshest** [microsoft/TypeScript#50818]
# Bug Report

### 🔎 Search Terms

- Inconsistent 2345
- function generics
- extends 2345
- generics 2345

### 🕗 Version & Regression Information

- This changed from version 4.7.4+ and above

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?pretty=false&ts=4.7.4#code/FAMwrgdgxgLglgewgAnNAPAFWQUwB4w4QAmAzsgN6oIIBcyAjMgL4B8AFAIYBOA5vZgCU9AG4I4xSs2ChIUdlRA16DADTIARjxUtBAbhnAgA)

### 💻 Code

```ts
function func<T extends { foo: 1 }>(arg: T): void {}

func({ foo: 1, bar: 1 });
```

### 🙁 Actual behavior

`bar` property sometimes displayed as valid and sometimes produce an error:

```
Argument of type '{ foo: 1; bar: number; }' is not assignable to parameter of type '{ foo: 1; }'.
  Object literal may only specify known properties, and 'bar' does not exist in type '{ foo: 1; }'.(2345)
```

When playing with the code live and change `bar` to `bar222` or `ba` sometimes the error shown and sometimes not. 
Refreshing the playground link with the changes always remove the error.

https://user-images.githubusercontent.com/534911/190869020-376ff387-56ff-48b3-83e4-43261b2b4d78.mov

### 🙂 Expected behavior

Always display as valid without any error. 

`{ foo: 1, bar: 1 }` is a valid subtype of `{ foo: 1 }` and so can legally be used to instantiate `T`.

-----

Maybe related to https://github.com/microsoft/TypeScript/issues/49490

**Comment by fatcerberus** [comment]
> Expected behavior: Always display an error for unknown properties.

The correct behavior is for there to be *no* error here: excess property checks aren’t intended to apply to generic constraints.  `{ foo: 1, bar: 1 }` is a valid subtype of `{ foo: 1 }` and so can legally be used to instantiate `T`.

**Comment by moshest** [comment]
@fatcerberus you are right, I've updated the issue description.

Although this case can make it harder to implement ORM projections ([like Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/select-fields)) where you need to selected type as `T` but also limit the allowed properties in the `select` object to allow only existing properties.

**Comment by RyanCavanaugh** [comment]
This looks similar to some other bugs we've seen reported where weird errors show up while typing

**Comment by JonathonChen** [comment]
I also encounter the similar situation when passing function paramter in different ways
```ts
interface AAA {
  hyYears: Array<any>;
}

function func(process: AAA) {
  console.log(process);
}

const unresolveParams = {
  hyYears: [],
  periodDataId: 1,
};


func(unresolveParams); // why this line can't detect the extra parameter

func({
  hyYears: [],
  periodDataId: 1, //  ts(2345) detect the extra parameter. Argument of type '{ hyYears: undefined[]; periodDataId: number; func(unresolveParams: any): any; }' is not assignable to parameter of type 'AAA'
});

```

**Comment by Andarist** [comment]
If I only bisected this correctly, the regression has been introduced by https://github.com/microsoft/TypeScript/pull/36747

**Comment by Andarist** [comment]
@JonathonChen your case is not a bug, you can learn more about this [here](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks)

**Comment by Andarist** [comment]
I was using the editor with TS built from different commits. I was doing that within the TS repo itself so I could pretty easily jump between commits/builds

**Comment by jakebailey** [comment]
Darn 🙁

I haven't yet found the right fourslash calls to get this reproducing, so into the server RPC logs I go...

**Comment by jakebailey** [comment]
Got it:

```ts
////declare function func<T extends { foo: 1 }>(arg: T): void;
////
////func({ foo: 1, bar/*1*/: 1 });

goTo.marker("1");
edit.insert("2");
verify.completions({ exact: undefined });
verify.noErrors();
```

(I spent all that time figuring out how to assert in fourslash that there are no completions so I cold perform the request.)

**Comment by OxleyS** [comment]
You may interested in a similar issue I filed in the realm of "errors that only show up while typing": https://github.com/microsoft/TypeScript/issues/51661

I don't know if it's the same underlying cause, or if my brief investigation into it was way off the mark or not, but food for thought.

**Comment by Andarist** [comment]
@OxleyS unfortunately, this looks like a different problem, especially given the call stack shared [here](https://github.com/microsoft/TypeScript/issues/51661#issuecomment-1361478725)

**Comment by moshest** [comment]
Amazing! 🙌
I can confirm it resolved on nightly build using the playground link.

**Comment by maxmezzomo** [comment]
I ran into similar issue, initially with generics, but the simplified to even without generics. I am still not sure what was causing inconsistencies in different situations, but I did find that having a property with the name "name" seemed to cause the error reporting, I dont know if word is reserved or something,  either way thought would share if its useful at all https://www.typescriptlang.org/play?#code/FAFwngDgpgBAsmA8gIwFZQMYhgXhgb2GBhgCcoBDAEwHsA7AGzBgDcKGBXKAZwC4DiJMpVqNmdCgFso-biFIBLOgHMA3IIC+6rUQz05MACIBBACrH+CFOiy4BJNpx79CQmBOn8ARI65eANJqBOrr62NxQIADCFNg4ggAUvjLwSGiYIADaPuxc3F4AugCUuAB8iRR0CpLsfKnWGUWWaTZxpTAJrkIAdL2V1bWBbsl1yUMwGkXqwHp0BgDuNKQA1tx2EdGxnR4yXnRQ8zAYsV6ToXPhABY0HAxUABIULFAAoqSkS+uRMSAJCSU4dr-ModAFA-DuKQpPYHGAANVyUC8EyKRQSJnMUyIQA

**Comment by jakebailey** [comment]
I see no error in the above snippet, so if you're having a problem and can reproduce it without generics, I would suggest making a new issue as that's very likely different.

**Comment by maxmezzomo** [comment]
Great thank you, before I create an issue I would appreciate if you could take a glance at 

https://www.typescriptlang.org/play?ssl=16&ssc=30&pln=15&pc=1#code/FAehGUAsEMAcFMAEB3AlgF0ogdtAtkgGarwA2AJsOgJ4KIDyARgFbwDG6A6hpAHL7wACgCcA9rEQBeRAG9cBAFwBndMNTYA5gF8A3MGBtR2FYlhrs6JsymIAFKJYKr7Lj34ER4gJSSAfIeNRUngAOlJRDXsWL30zdUsWWzkBBQAiADdoUgBXeFStGLiLK1tbH18k+Xg0yDJwxCVIUWzyREYkeGExYQB+fK8vRDBsUURO7v0wBoFEQ3IkUBBuTERoRHJUQkJO+AsGmAQqWiRnDmXIABFN7eFd9E8JaRlMnOqVc209AyMTIvQrrZWGxRZhOFguc4Am53B7lAJKIKhcKRBzMGLAP5QkrPLK5NIvXL9DHmf7XEplPxJAnVVJjLqiYT9QZTcYMoA

It's a little clearer than the above one but same thing. The fact there is no error is the issue as I understand, it should not accept function, but seems to when field is called 'name', just to make sure its not something already known. Thanks

**Comment by jakebailey** [comment]
This PR issue in particular is about inconsistent errors in the editor while modifying code, so your sample is definitely not related.

But, yes, I'm pretty sure your code behaves that way because functions have a `name` property and so satisfy the first object type in your example. e.g.:

![image](https://user-images.githubusercontent.com/5341706/223876749-7a5a4941-6714-4d51-922e-7498763427a8.png)

**Comment by maxmezzomo** [comment]
Nice, thanks for clarifying, feel free to hide or delete my posts if useful, cheers.
