### ISSUE TITLE
[macro] How likely TypeScript will consider adding macro in the future

### ISSUE THREAD

**Issue by Bistard** [microsoft/TypeScript#50815]
# Suggestion
I believe the team of TypeScript definitely has considered related topics about macro in the past. Since we do not have macro right now in TypeScript, there must be some concerns or flaws about macro. I am actually kind of curious and want to know a few reasons why not having macro today.

I can guess a few points so far:
1. It is against the design idea of TypeScript just like enum because it changes the actual behaviour.
2. It is hard to do type-checking while using macro.
3. macro used across different JavaScript files can resolve weird type-checking behaviours.

I personally wish to have macro to increase readability while writing TypeScript.

## 🔍 Search Terms
macro
## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example
TBD

## 💻 Use Cases
TBD

**Comment by jcalz** [comment]
Polo!

**Comment by xiBread** [comment]
Assuming you mean *macro*, then #4892.

**Comment by fatcerberus** [comment]
I initially assumed this is about macros too, but the phrasing is... very odd.

> related topics about Marco
> concerns ... about Marco
> having Marco
> using Marco
> I personally wish to have Marco

Given the commitment to this odd phrasing in an otherwise well-written issue, I'm left to ask either or both of these questions:
1. Who is Marco?
2. Is this a joke?

**Comment by Bistard** [comment]
> I initially assumed this is about macros too, but the phrasing is... very odd.
> 
> > related topics about Marco
> > concerns ... about Marco
> > having Marco
> > using Marco
> > I personally wish to have Marco
> 
> Given the commitment to this odd phrasing in an otherwise well-written issue, I'm left to ask either or both of these questions:
> 1. Who is Marco?
> 2. Is this a joke?

nah, I just typed everything wrong. Didn't mean't Macro Poll.

**Comment by fatcerberus** [comment]
> Macro Poll

Okay, now you're just doing it on purpose. :wink:

**Comment by fatcerberus** [comment]
> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

I think macros probably fall under "non-ECMAScript syntax with JavaScript output", but I'm not positive.  It does seem like a bit of a gray area w.r.t. the TS design goals.

**Comment by Bistard** [comment]
> Assuming you mean _macro_, then #4892.

Thanks for sharing (just realized the reason I didn't find related issues on macros is that I typed it as marcos). I read through the issue and found some related topics or comments on this one:
* inline function support #661
* comment 1 - https://github.com/microsoft/TypeScript/issues/4892#issuecomment-212919025
* comment 2 - https://github.com/microsoft/TypeScript/issues/4892#issuecomment-253626950
* existing plugin - https://github.com/LeDDGroup/typescript-transform-macros

**Comment by MartinJohns** [comment]
I'm confused. You correctly identified

> It is against the design idea of TypeScript

but then you check

> [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

in the viability checklist.

**Comment by RyanCavanaugh** [comment]
The most likely outcome, by a very large margin, is that macros are not happening. We've looked into this in the past and it doesn't seem like there's any tractable path that doesn't violate critical design constraints. If you macro with existing syntax (like how C's preprocessor works), there's a violation of the "all JS is TS" principle, plus it's super weird (what happens if you indirect a macro function?). If you macro with novel syntax, then there's a problem of how you even parse a file, especially in contexts like tooling where you expect to be able to open a TS file and get reasonable behavior without knowing the entire project context.

**Comment by alshdavid** [comment]
To be fair, built-in support for JSX is essentially a built-in macro that no more violates TypeScript's design constraints than compile time macros would.

Have you considered Rust-like macros that generate _TypeScript_? 

## Example Use Cases

These are just some use cases I can think of off the top of my head, some might be bad but you get the idea

### Supporting Front End Frameworks

That would enable front end frameworks (other than React) to add support for their template compilers without the need for custom file formats (`.vue`, .`svelte`) and external LSP implementations (Angular, Vue, Svelte).

#### JSX - React, Preact, Solid, etc

JSX could be taken out of the TypeScript core to be a macro supported by the React team

```typescript
import macro { jsx } from 'jsxc' // stripped at compile time

export function HelloWorld() {
  const value = 'World'
  return jsx!(<div>Hello {value}</div>)
}
```

#### Vue 

```typescript
import macro { vue } from 'vue-compiler' // stripped at compile time

export const HelloWorld = {
  tag: 'app-hello-world',
  template: vue!(<div>Hello {{value}})</div>),
  data: () => ({
    value: "World"
  })
}
```

#### Angular (or Vue, really)

```typescript
import macro { ngTemplate, ngStyles } from 'ngc' // stripped at compile time

export class HelloWorldComponent {
  static tag = 'app-hello-world'
  static template = ngTemplate!(<div>Hello {{ value }}</div>)
  static styles = ngStyles!(['./hello-world.component.css'])

  #[data]
  value = 'world'
}
```

### Performance 

#### Compile time evaluation

Front end code is performance sensitive and computing code at compile time can improve runtime performance (at the expense of compile times)

```typescript
import macro { sum } from 'mathc'
const value = sum!(4 + 5)
```
Expands to
```typescript
const value = 9
```

#### Embedding Externals

A macro could call the `node:fs` api to handle embedding external files without the need for bundlers

```typescript
import macro { include } from 'embedc'

const FOO_TXT: Uint8Array = include!('./foo.txt')
```

### Proc Macros

Derive macros enable an alternative to decorators, evaluated at compile-time, producing valid JavaScript

#### Auto Constructors

Perhaps we could see a macro that enables the ability to create struct-like initializers for classes

```typescript
import macro { struct } from 'structc'

#[struct]
class Foo {
  foo: string
}

const foo = Foo.new({
  foo: 'value'
})
```
expanding to something like
```typescript
class Foo {
  foo: string = ''

  static new(init: { foo: string }) {
    return Object.assign(new Foo(), init)
  }
}
```

#### Serialization / Deserialization

Sending complex objects across to Workers, iframes, native Nodejs modules and avoid manual casting for serialization/deserialization

```typescript
import macro { struct } from 'structc'
import marcro { serialize, deserialize } from 'serdec'
import proto from 'protobuf'

#[struct]
#[serialize]
#[deserialize]
class Foo {
  value: string
}

const foo = Foo.new({ value: 'hello' })
const bytes = proto.fromValue(foo) // calls foo.serialize()
worker.postMessage(bytes) // worker can deserialize the value on the other side
```

#### CLI Parser (like clap)

```typescript
import macro { command, target, arg } from 'clapc'
import clap from 'clap'

#[command]
class Command {
  /** @description File path to target */
  #[target]
  target: string

  /** @description Enable watch mode*/
  #[arg(short = 'w', long = 'watch')]
  watch: boolean = false
}

const cmd = clap.fromArgv(Command)
console.log(cmd.target, cmd.watch)
```

### Design goals

- [x] Statically identify constructs that are likely to be errors.
- [x] Provide a structuring mechanism for larger pieces of code.
- [x] Impose no runtime overhead on emitted programs.
- [x] Emit clean, idiomatic, recognizable JavaScript code.
- [x] Produce a language that is composable and easy to reason about.
- [x] Align with current and future ECMAScript proposals.
  - In this regard, it simply extends ECMAScript in the same way built-in JSX support does
- [x] Preserve runtime behavior of all JavaScript code.
  - It would generate valid TypeScript at compile time which then converts to valid JavaScript
- [x] Avoid adding expression-level syntax.
- [x] Use a consistent, fully erasable, structural type system.
- [x] Be a cross-platform development tool.
- [x] Do not cause substantial breaking changes from TypeScript 1.0.

### Closing Thoughts

Support for simple compile time macros in TypeScript enables many new use cases, does not violate the design goals of TypeScript any more than built-in support for JSX and allows the TypeScript core to offload support for built-in macros (jsx) to the maintainers of the projects who need them.

I would add support for macros myself however it's impossible to extend the TypeScript compiler or LSP without forking TypeScript. Doing so would result in a cool tech demo that nobody would use.
