### ISSUE TITLE
New Website Logo: Everlaw

### ISSUE THREAD

**Issue by ajshankar** [Microsoft/TypeScript#5081]
Please fill the following out:

- Name: Everlaw
- Homepage url: http://www.everlaw.com/
- Brand Guidelines/Licensing: none
- Logo: http://everlaw.com/presskit/images/everlaw-1600-square.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by ajshankar** [comment]
We've also written a pretty sweet TypeScript plugin for NetBeans, which includes code completion, error checking, etc.: https://github.com/Everlaw/nbts

We've released it as open source. Is there a place where you're collecting such resources for potential (and active) TypeScript users?

**Comment by jeffrey-easyesi** [comment]
@ajshankar @aflevin Do we want this logo or the one in https://github.com/Microsoft/TypeScript/issues/5117?

**Comment by ajshankar** [comment]
@jeffrey-easyesi This one, please. It matches their resolution requirements.
