### ISSUE TITLE
Incorrect return type of Object.keys

### ISSUE THREAD

**Issue by rafikalid** [microsoft/TypeScript#50830]
# Bug Report

### 🔎 Search Terms

- Object.keys

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Object.keys`

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBCBGArAvDA3gKBtmBHAXDAIwA0WOA7oQExk4wCmhAzHTgE6EAsGAvgNwYMAeSQNgUAHQBrBgE8IACgSIAlJIC2AQwAOi6TGQA+OEgDa0gLqr+MAPR2YAUQBKL4S8IBpGAEsIcABmMFByOgww0Oy+YADmMFpgACYwoACuADYpYCCw8BFpEAwpWgGyckEwAEQqVRhAA)

### 💻 Code

```ts repro
const obj= {
    q: 1,
    w: 2,
    e: 3,
    r: 4
};

Object.keys(obj).map(k => obj[k]); // ERROR: K is of type string and could not be used as key of "obj"

```

### 🙁 Actual behavior

Need to assert key type as follow
```ts
Object.keys(obj).map(k => obj[k as keyof typeof obj]); 
```

### 🙂 Expected behavior

"k" should be already of type "keyof typeof obj"
```ts
Object.keys(obj).map(k => obj[k]); 
```

**Comment by MartinJohns** [comment]
The object type is correct. See these issues: [Issue search for 'Object.keys in:title'](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+Object.keys+in%3Atitle+is%3Aclosed)

**Comment by rafikalid** [comment]
I see, thanks @MartinJohns
