### ISSUE TITLE
`instanceof` does not narrow when the class is intersected with `&`

### ISSUE THREAD

**Issue by ehmicky** [microsoft/TypeScript#50844]
### 🔎 Search Terms

`instanceof`, `narrow`.

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried (from `3.8.3` to to `4.9.0-dev.20220919`), and I reviewed the FAQ for entries about it.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&target=99&noPropertyAccessFromIndexSignature=true&exactOptionalPropertyTypes=true#code/JYOwLgpgTgZghgYwgAgJIgM5jiJB5EFAbwChlkB7QgCgEoAuZANwuABMSBfE0SWRFOiw4kAFQDuFZKXJhJdRi3ZcSCKlmShhuFAF5pnZHAxpM2HQRQAfU9rGSSq9WGQBhADbGMlgOpQqAObI+kSGxtLIhOLICrbm+ITIhgBkETAUFIxgUACuKNzAMDFa8SglIhAURR5evv4gAbTSZJpmFQB0VBB0yAD0vcgACv4ADtBgAJ7IAORd08hsFBAmIBQuEAAewFgANMgARhAIcDkYKAAG5TrnmitrkXBQ-uIQbAsU4iAqTmZunhjeQgAJWAAQAFi4QmETERIhBorEhKVLHt0plkNk8kkeEVqFckK07JVqv9ARAQeCwE0ZITSp0aE1+kNRuMprNCPNNtswCYcG9Lm1rrcHk8Pq93p8VEA)

### 💻 Code

```ts
interface InstanceOne {
  one(): void
}
interface InstanceTwo {
  two(): void
}
const instance = {} as InstanceOne | InstanceTwo

const ClassOneWrong = {} as { new (): InstanceOne } & { foo: true }
if (instance instanceof ClassOneWrong) {
  instance.one() // Property 'one' does not exist, because `instance` is not narrowed down
}

const ClassOneRight = {} as { new (): InstanceOne, foo: true }
if (instance instanceof ClassOneRight) {
  instance.one() // Property 'one' exists and `instance` is narrowed down
}
```

### 🙁 Actual behavior

`instanceof` does not narrow down the left side when the right side is a type using `&`.

### 🙂 Expected behavior

It should narrow it down to `InstanceOne`, and `instance.one()` should pass.

**Comment by ahejlsberg** [comment]
Another instance of the same issue:

```ts
class A { a = 0 }
class B { b = 0 }

function f10(obj: A & { x: string } | B) {
    if (obj instanceof Object) {
        obj;  // B, but should be A & { x: string} | B
    }
    else {
        obj;  // A & { x: string }, but should be never
    }
}
```
