### ISSUE TITLE
PrivateName does not permit escape characters

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#50851]
Discovered by @amcasey while running TS on test262.

```ts
export class IdentifierNameWithEscape {
    \u{78}: number;

    constructor() {
        this.\u{78} = 0;
    }

    doThing() {
        this.x = 42;
    }
}

export class PrivateIdentifierWithEscape {
    #\u{78}: number;

    constructor() {
        this.#\u{78} = 0;
    }

    doThing() {
        this.#x = 42;
    }
}
```

Currently `IdentifierNameWithEscape` parses and type-checks correctly; however, `PrivateIdentifierWithEscape` does not even parse.

**Comment by DanielRosenwasser** [comment]
Another thing to check

```ts
class IdentifierNameWithEscape {
    x\u{78}: number;

    constructor() {
        this.x\u{78} = 0;
    }

    doThing() {
        this.xx = 42;
    }
}

class PrivateIdentifierWithEscape {
    #x\u{78}: number;

    constructor() {
        this.#x\u{78} = 0;
    }

    doThing() {
        this.#xx = 42;
    }
}
```

The first case works perfectly. The second case correctly resolves `this.#x\u{78}`, but not `this.#xx` even though they're really the same.

**Comment by DanielRosenwasser** [comment]
Here are the problems to be solved:

1. The scanner doesn't know that a `\` can follow a `#`. That needs to be fixed.
2. The parser asks for the literal text of the token in source, as opposed to the "cooked" character values. This is wrong, and means that unless you wrote you private identifiers the same way throughout, they won't ever be looked up to the same symbol.
3. An *extended escape* is an ES2015-specific feature, and for some reason we make the scanner act differently instead of parsing and issuing a span. Fixing the behavior is awkward because it may differ between ES5 and ES2015+.

**Comment by fatcerberus** [comment]
Why are these escapes even a thing?  They're like a modernized version of C/C++ trigraphs...

**Comment by DanielRosenwasser** [comment]
I'm going to guess that auto-generated code was the use-case, and then extended escape sequences were added for parity.

**Comment by Jamesernator** [comment]
> I'm going to guess that auto-generated code was the use-case, and then extended escape sequences were added for parity.

I believe the main reason is for encodings where unicode isn't available (e.g. ASCII), i.e. if your system only supports ASCII then you can transform *any* JS source by replacing characters outside of the ASCII range by their escapes.

e.g. If you have:

```js
const π = 3.14;
const constants = { π: 3.14 };
const s = "π";
```

Then replacing all non-ASCII characters with their unicode escapes works in any syntatic position:

```js
const \u{03C0} = 3.14;
const constants = { \u{03C0}: 3.14 };
const s = "\u{03C0}";
```

Your conversion doesn't need to be AST aware, because the same escapes that work in string literals also work for identifiers or such, so a simple find and replace will work.

**Comment by DanielRosenwasser** [comment]
I'm prototyping ES3-ES5 extended escape support in #50918.
