### ISSUE TITLE
Default type in generic react component not inherited in callbacks

### ISSUE THREAD

**Issue by mc-petry** [microsoft/TypeScript#50858]
# Bug Report

### 🔎 Search Terms

React component default generic type

### 🕗 Version & Regression Information

- This is an error

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4BvUuOAYV0gDskWYAFHMAZwHVgMABbJMAGjpwAogBskIdjAAqATzBJJ9ZOhgA5CABNNpAL5xsuAkV1lSMdUjgAhAK4wYEFs5S8k3CD4AHmU4JAAPGHZDXhl5RQ41DQA+OABeKUZmLyUAvkERMRDUgDIaKTRhYFlDIhYAfgAuRGJ9IyQzUlJMVxYMYC8s8ByOELDI6Ni5BSUkpzSCXjAUFnxkgAowHl5mtw8vHz883mKASnL6IhhXKBY4IOSggHpkztI0L154ADcARnT7kxhmwOHAvAxZMA0ABrNLUeapJAAOi2SG+SgAIkhMChXLIYOtTuYXu9Pj8AEwAoJA1hKIL4JYrNZglgQqGw+HpREoojojhYnF4glEuAkoA)

### 💻 Code

```ts
import React from 'react'
import {
  ComponentPropsWithRef,
  ElementType,
  ReactNode,
} from 'react'

type ButtonBaseProps<T extends ElementType> =
   ComponentPropsWithRef<T> & {
  children?: ReactNode
}

function Component<T extends ElementType = 'span'>(props: ButtonBaseProps<T>) {
  return <></>
}

const v1 = <Component onClick={e => e.preventDefault()} /> // <- Error
const v2 = <Component<'span'> onClick={e => e.preventDefault()} /> // <- Ok

```

### 🙁 Actual behavior

Default generic type is not inherited in callbacks, but intellisense works fine:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/8122711/191250963-9fc6cbb0-d63c-4d37-8e91-a48524c6ce05.png">

### 🙂 Expected behavior

Should work both variants

**Comment by MartinJohns** [comment]
> This is a crash

It's not crashing for me, did you miss something?

**Comment by mc-petry** [comment]
@MartinJohns 
see link to [playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4BvUuOAYV0gDskWYAFHMAZwHVgMABbJMAGjpwAogBskIdjAAqATzBJJ9ZOhgA5CABNNpAL5xsuAkV1lSMdUjgAhAK4wYEFs5S8k3CD4AHmU4JAAPGHZDXhl5RQ41DQA+OABeKUZmLyUAvkERMRDUgDIaKTRhYFlDIhYAfgAuRGJ9IyQzUlJMVxYMYC8s8ByOELDI6Ni5BSUkpzSCXjAUFnxkgAowHl5mtw8vHz883mKASnL6IhhXKBY4IOSggHpkztI0L154ADcARnT7kxhmwOHAvAxZMA0ABrNLUeapJAAOi2SG+SgAIkhMChXLIYOtTuYXu9Pj8AEwAoJA1hKIL4JYrNZglgQqGw+HpREoojojhYnF4glEuAkoA):
<img width="607" alt="image" src="https://user-images.githubusercontent.com/8122711/191253049-11aa413e-21fe-47ad-9cfe-24b69ef46369.png">

**Comment by MartinJohns** [comment]
That's an error, not a compiler crash. :-)
