### ISSUE TITLE
Regression on 4.2+ when trying to infer generic function type parameter using a type alias

### ISSUE THREAD

**Issue by boconnell** [microsoft/TypeScript#50865]
# Bug Report

### 🔎 Search Terms
generic type parameter alias 4.2

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.3#code/KYDwDg9gTgLgBDAnmYcBKwDOBXANjAHgFEopoAVOUGYAOwBNM4AxAQwEtdspgMd8ANHABqrLsHIA+OAF44JMlEoAfEWOwSA3AFgAUEhRwA6lFZgU9PnkKjxU2eizWCbTt15PBau5L17QkLBwAMa4rJhMrlw8VvhwAN56cMlwYNgARrjswXA84RC0AFxwmDBQ7LQA5jq6KanlAG6sNHAA+q3smFHusTDFZRoOA8A1dcEFpVDYwTDQABR5mAXFkxWVAJQJSXUpMAAWnQB0iwUOJ7SjKQC+eje6egBm2LQz7KedAMrTwViYxKQUKggGgMSIcaIefgwIS2DRSObbZJQYq9f6Kcgw9QSXy6dbFKBwTreOFbWopHgwbi0OAAQgWhNopVYL2AEAeLHBPU8MHWNSuNT0AHpBXAHuDMI9nq9Tg8IBAFtziiYzBZUfFWMVaNgALbpYBQK6STaJMnJdjsuafb6-BVQ9bGxE7ClU3Lcw6sR13OrOqDUgDMtz8umFqXCmCwQnS2HgyvMwEs3II6s1Or1BukMjkqO6MW5QmTcC1uv1hslLxgb2p6VYUFt1hRiZzkOs+Y1hdTJaNpLq5rglswX2CPwidfw9u7OyRwEpvtdUPdnsdPv9tyAA)

### 💻 Code

```ts
export type Result<ErrorT extends FailureResult, ValueT> = ErrorT | ValueT;
type WrappedResult<ValueT> = Result<FailureResult, ValueT>

export class FailureResult {
    public reason: string;
    private __isFailureResult: true = true;
    constructor(reason: string) {
        this.reason = reason;
    }
}

function isSuccess<ErrorT extends FailureResult, ValueT>(
    r: Result<ErrorT, ValueT>
): r is ValueT {
    return !(r instanceof FailureResult);
};

// fails
function foo(result: WrappedResult<{a: number}>) {
    if (isSuccess(result)) {
        return result.a
    }
    return 3
}

// passes, but WrappedResult<{a: number}> == Result<FailureResult, {a: number}>
function bar(result: Result<FailureResult, {a: number}>) {
    if (isSuccess(result)) {
        return result.a
    }
    return 3
}
```

### 🙁 Actual behavior

In `foo`, the type params for `isSuccess` are being inferred as `FailureResult, FailureResult | {a: number}` but in `bar`, the type params are correctly being inferred as `FailureResult, { a: number}` which causes the type guard to work correctly

### 🙂 Expected behavior

`foo` and `bar` behave the same

**Comment by DanielRosenwasser** [comment]
These are just aliases of union types, and while sometimes we can match against the name of the alias, I believe it would be a lot of work to figure out every possible inference candidate for both `ErrorT` and `ValueT` while also keeping their constraints in mind.

During inference between two union types, we try to remove candidates that are assignable to other non-generic inference targets. In your example, `ErrorT` is unused, so you can discard it and take advantage of that behavior.

```ts
function isSuccess<ValueT>(r: Result<FailureResult, ValueT>): r is ValueT {
    return !(r instanceof FailureResult);
}
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.8.2#code/KYDwDg9gTgLgBDAnmYcBKwDOBXANjAHgFEopoAVOUGYAOwBNM4AxAQwEtdspgMd8ANHABqrLsHIA+OAF44JMlEoAfEWOwSA3AFgAUEhRwA6lFZgU9PnkKjxU2eizWCbTt15PBau5L17QkLBwAMa4rJhMrlw8VvhwAN56cMlwYNgARrjswXA84RC0AFxwmDBQ7LQA5jq6KanlAG6sNHAA+q3smFHusTDFZRoOA8A1dcEFpVDYwTDQABR5mAXFkxWVAJQJSXUpMAAWnQB0iwUOJ7SjKQC+eje6egBm2LQz7KedAMrTwViYBLYaKQLYq9FwcaIefgwIQAiSSdbFKBwTreQFbWopHgwbi0OAAQgWyNopVYL2AEAeLHBPU8MHWNTuegA9EzUuFMFhHs9XqcHhAIAtacUTGYLKD4qxirRsABbdLAKBXeHoursSlzT7fX6CqHrTaJDE7XLAbFQXE8KGHVjbZJ3OpYnFwADMtz8uhZbIiWCE6Ww8BF5mAllpBAlUtl8sV0hkclB3RitKEYbg0rlCqVXJeMDeuPSrCgOusIJD8ch1iTkpTEfTyoNqvVmuCPwihfwepVRuNpvNtKtNrgdsxJsdLt0VyAA)

You could also possibly have written this as

```ts
function isSuccess<T>(r: T): r is Exclude<T, FailureResult> {
    return !(r instanceof FailureResult);
}
```

**Comment by boconnell** [comment]
Thanks for the suggestion. Unfortunately, that still fails as soon as I introduce a subclass of `FailureResult`: [Playground link](https://www.typescriptlang.org/play?ts=4.8.2#code/KYDwDg9gTgLgBDAnmYcBKwDOBXANjAHgFEopoAVOUGYAOwBNM4AxAQwEtdspgMd8ANHABqrLsHIA+OAF44JMlEoAfEWOwSA3AFgAUEhRwA6lFZgU9PnkKjxU2eizWCAVVoBrWhADutIbY0pPT1QSFg4AGNcVkwmNk5uXid8OABvPThMuDBsACNcdgi4HhiIWgAuOEwYKHZaAHMdXSzs2oA3Vho4AH1u9kx4rh4rfEqajQdx4CaWiLLqqGwImGgAChLMMsqFuvqASjSMlqyYAAt+gDoNsodr2hmsgF89Z909KJimN08fWioQGgMOIcIZJfjwdLNLK0VgAW1QcgARN8vL4FNBEU1XnoAGbYWjLdg3foAZSWESwmAIUnWlXIe0qUDg-XkICi2HowGpQkGiRGMGkkJaPBg3D+AEJ1szaNVWATgBAcSwQXzkjA9ljgroAPTa7KfLC4-GEm44iAQdZqyomMwWfkEVKsSq0bCw3LAKCPSQHIVZdhK1ak8mUy3gvY+o7HYrAUVQP48cEXViRuCvYUxsVwADMLy1uv1sSwQly2HgNvMwEsaodTrgLrdHq9sjk9t5wzVQkdztd7s9kiNBJgRL+uVYUFD1kqrZV7fBndr9d7XojUMy-rggcwZIiFNiE-w4cOq+OIszCesSZTaayp7j2ZeQA).

I also think I need `ErrorT` to extend `FailureResult` for the implementation of a Result.map function with the additional definitions:
```
const isFailure = <ErrorT extends FailureResult, ValueT>(
    r: Result<ErrorT, ValueT>
): r is ErrorT => {
    return r instanceof FailureResult;
};
const map = <ErrorT extends FailureResult, ValueT, MappedValueT>(
    r: Result<ErrorT, ValueT>,
    f: (value: ValueT) => MappedValueT
): Result<ErrorT, MappedValueT> => {
    return isFailure(r) ? r : f(r);
};
```

[Playground link](https://www.typescriptlang.org/play?ts=4.8.2#code/KYDwDg9gTgLgBDAnmYcBKwDOBXANjAHgFEopoAVOUGYAOwBNM4AxAQwEtdspgMd8ANHABqrLsHIA+OAF44JMlEoAfEWOwSA3AFgAUEhRwA6lFZgU9PnkKjxU2eizWCAVVoBrWhADutIbY0pPT1QSFg4AGNcVkwmNk5uXid8OABvPThMuDBsACNcdgi4HhiIWgAuOEwYKHZaAHMdXSzs2oA3Vho4AH1u9kx4rh4rfEqajQdx4CaWiLLqqGwImGgAChLMMsqFuvqASjSMlqyYAAt+gDoNsodr2hmsgF89Z909KJimN08fWioQGgMOIcIZJfjwdLNLK0VgAW1QcgARN8vL4FNBEU1Xu95vB+oNEg5iKQKP9AYwWCDEiMYP51BJJKsjpkoJUacTFOQ6XZJHo9pUoHB+vISUpZNJIS0eDBuH9BXVqqxaBFgBAAGaUhLDZIwLFNOa0apwWFmInosXUOgUgna8HcwJCACyZgsAQZTKhLLZOo5FHtDIEzLgasqqw64kqbvIBxk0md5mA9CjfO94N9SidLsTUekscOnuKwBlUD++KpPHWBwA-MU4JU1ZW9cFdAB6FvBkGYPRq7DKmDsG5qiAQdY6yomLOWH2pViVWjYWG5YBQR6SA6SrImsCju1VJYq2LivcRA+YC6sPYvZtt7KfLBCXLYeAThNTtMzucLpcr3Nydk2sFrCED84HnRdl1Xbte2WAc-lyVgoB3axU2cACaWA2dQK-CC13zFotyQwRj1PI8cBPLAzwvF4gA)

your explanation goes over my head a little, but I'm still left wondering why these examples all work in 4.1.5 but not 4.2.3
