### ISSUE TITLE
"Implicitly has type 'any'" when type annotation is provided

### ISSUE THREAD

**Issue by turolla** [microsoft/TypeScript#50864]
# Bug Report

### 🔎 Search Terms
implicit any, filter object properties by type, key remapping

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/C4TwDgpgBAQg9nANhAhgOwAoCc6S8ASwgGcAeAFQD4oBeKcqCAD2AjQBNip0QoB+KAG8oAWABQUKAG0A0lAJooAawgg4AM3rcu5WQF1GLNpygAjBMnT8ocgFxQ0EAG4Qse++aSo0AbnEBfKHtHFyw-MXEAY0QUYi4AMQQhcUlPSzRiAHk0RBB7eC90bFxXQhJSYAALAmJqOgBXDgh1BQh2AEIfKAB6bqhMgFsCYFZ2ADoxlNEJKABzCGAAZWAsBVnSeMNWDi4ACmI4AYgAVWJm+sQAERRgFHseAEpaah5KXfU0e3in+2IVteSM0kWAW9Swika7GarQ6XV6-SGIzaEym-nCUxQBXStCgK3qEHCkimUJaaGGEFyAEFlqs0LMcVUamN5kt-nTdrsnjRqIziGM0t4sjkQGNMRZvA9wv5xEA)

### 💻 Code

```ts
type BooleanProperties<T> = T extends any ? { 
  [K in keyof T as T[K] extends boolean ? K : never]: boolean;
} : never;

class Foo {
  booleansOnly: BooleanProperties<this> = undefined!; // Omitted..
  
  getString<F extends (someUsefulData: any) => any>(fn: F) : string {
    return undefined!; // Omitted..
  };

  aBoolean = true;
  
  definitelyAString = this.getString(() => this.booleansOnly.aBoolean);
}
```

### 🙁 Actual behavior

Error: 'definitelyAString' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### 🙂 Expected behavior

Since "getString" method has an explicit return type (string), in my opinion "type annotation" is provided, and the error should not be thrown.

**Comment by MartinJohns** [comment]
The magic words are:
> is referenced directly or indirectly in its own initializer.

You're initializing `definitelyAString` with an expression calling `this.booleansOnly`, which requires the type of `booleansOny` to be known. This type is using the polymorphic `this` type, so the compiler must know what `this` looks like. For this it needs to know the type of `definitelyAString`.

**Comment by RyanCavanaugh** [comment]
The chain of circularity is as follows:
 * What is the type of `definitelyAString` ?
 * What is the type of the call to `getString` ?
   * Note: It's not sufficient to say "`string`, obviously!" -- the call needs to be processed to check for errors, contextually type the arguments, etc; this cannot be arbitrarily deferred
 * What is the type of `() => this.booleansOnly.aBoolean` ?
 * What is the type of `this.booleansOnly` ?
 * What is the type of `definitelyAString` ? <- circular

**Comment by turolla** [comment]
Thank you very much @MartinJohns and @RyanCavanaugh for your very kind and complete answer.
I hope in the future Typescript will provide a way to handle this kind of sistuations, in the same way nowadays it's possibile to write 

```
definitelyAString = this.getString(() => this.booleansOnly);
```

without getting errors.
Maybe adding some kind of syntax to provide Typescript instructions on how to handle circularity errors, for exemaple something like: 

```
type BooleanProperties<T> = { 
  [K in keyof T as 
    T[K] extends CircularType ? never : // <-- Typescript, if you you have circularity problems, then...
      T[K] extends boolean ? K : never]: boolean;
};
```

Have a nice day.

**Comment by MartinJohns** [comment]
> Maybe adding some kind of syntax to provide Typescript instructions on how to handle circularity errors

It mentioned the option to add a type annotation in the error message.

> I hope in the future Typescript will provide a way to handle this kind of sistuations

As far as I know the compiler would have to be rewritten basically from scratch, and introduce a two-phase type check. Very unlikely to happen.

**Comment by RyanCavanaugh** [comment]
There's a good discussion about this in #45213
