### ISSUE TITLE
Evaluate inference changes in reselect due to tuple type mapping changes

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#50870]
In #50831, we fixed a bug around ensuring that optional tuple elements always contain a missing/undefined type, even when a mapped type tries to remove them.

However, this had some impact on 2 calls to reduxjs/reselect. Occasionally `undefined` can spoil inference results, but it's not clear where that might be taking place in the library.

**Comment by ahejlsberg** [comment]
See [here](https://github.com/microsoft/TypeScript/pull/50831#issuecomment-1253830522) for a simplified version of the `MergeParameters` type that works with TS 4.7 and later.

**Comment by markerikson** [comment]
FYI I was able to successfully use the `MergeParameters` type from Anders, although the publishing step to make the package work from 4.2...4.9 was awkward:

https://github.com/reduxjs/reselect/pull/587

**Comment by Andarist** [comment]
This investigation was resolved. `reselect` shipped the type provided by Anders. I think that this issue could be closed now :) cc @jakebailey
