### ISSUE TITLE
Spread operator results in incorrect types when used with tuples

### ISSUE THREAD

**Issue by Zamiell** [microsoft/TypeScript#50875]
# Bug Report

### 🔎 Search Terms

generic spread operator tuple tuples

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFpK6fAoEoAKBBASgFVARgqAwgPJpoCi+GCYsNUccALgJ4AOApqALJMYCuLAGw4BeUAG04oKaABmvAHYBjAFygAFAGcA9gFs2KAE4BzVQCMtWoQEN5ASlDCAfKABuWgJYATADSTpV4wAmVXleHVM2A18AXQBuekUBKw0NLiZ8JJTcAG8-KR0efiENVW4+QTYxaIdxOPppUG09TjYGAAstTzV7XIaGmS0DdUUteQ0GUALyoVAtGVB29w0AOimitg0evL6GkbGJsUUrAQFTK0UAa29QZduAow1q0TWK+J2dxAAZCwvQKwn2hxmOxZvMAET3DRg5bbd6gRAASQmS1AIwMBjYigYAiYoHkAQMWgA7mxPDC4QBfbZUqlUCC0Bl01CYUCBPAIgByRBI5EoiAZjLpGDaKJRgMaVj0f1SLACE2w11MvAmJMmVguHHcEw0AncRja2NxOkGHBGOkE7iODFJoCJWradJsoHc8mtBhk5yBbX+apYqW4pFCOgWWgW61Sahd4zYVk8oNAACteONQMmXUY-o10zMGOtbDC4Gwg2lA2FQL1pAA1Y68NgK7bVgS1wK+Wkut0exQcbhIAKS1qRVIVqRiANB5aN2vYaKqCTvORKVSaXT6YxmCzWOwOZxuLy+d73YJ4sIRKLbOoNUdMUs6Cc1tiBGfiWHSBcqdRNVcmRoMAzp+xOK4Hg+C+UiHqoGhMOElj7tIdS0okyT+ukmQaIEAA8WBsAAHta8ieMhN7OMOkyFBUJSgIYBhWEw6E9n2ehuhoYgYNEziiFU8TbJ+LTtJ03TlqBsiDMMowpi8MxzAsIorBJGxbHCuxiQcRwnGclzXLcyyQk8pHTGwbyKVIXw-H8AJtECrAcFJELGFC5JGfCYBIo0HS8AIcYRKAYJBqeoAAD6NFB5gCGCsFGYgSrIsi+wxnGLpohiWI4s6ShNp4GzSRwb4MO4owLFZKxCVSDQ0nAQA)

### 💻 Code

```ts
// ----------------
// PART 1 - CORRECT
// ----------------

type MyTuple = [
    func: (someArg: boolean) => void,
    arg2: number,
];

class MyClass1 {
    myTuples: MyTuple[] = [];

    someMethod() {
        for (const myTuple of this.myTuples) {
            const [callback, ...args] = myTuple;
            // Look at the type of "args".
            // It is correctly narrowed.
        }
    }
}

// ------------------
// PART 2 - INCORRECT
// ------------------

// This is the same as part 1, but we make it slightly more complicated with
// an interface that maps MyEnum to tuples (instead of just using a single tuple).

enum MyEnum {
    Value1,
    Value2,
}

interface MyParameters {
    [MyEnum.Value1]: [
       func: (someArg: boolean) => void,
       arg2: number,
    ];
    [MyEnum.Value2]: [
        func: (someArg: string) => void,
        arg2: symbol,
    ];
}

class MyClass2<T extends MyEnum> {
    myTuples: Array<MyParameters[T]> = [];

    someMethod() {
        for (const myTuple of this.myTuples) {
            const [callback, ...args] = myTuple;
            // Look at the type of "args".
            // It should be "number | symbol",
            // but it instead incorrectly includes the function types.
        }
    }
}
```

The type of the variable attached to the spread operator is incorrect.

Furthermore, we can see that the bug is with the spread operator specifically, since accessing the tuple by a specific index returns the correct type.

## Other Issues

This is possibly related to #49802.

**Comment by Oblosys** [comment]
Here's an example without enums or classes that has the same issue:

```ts
const test = <N extends number>(singletons: (['a'] | ['b'])[], i: N) => {
  const singleton = singletons[i]
  // const singleton: (["a"] | ["b"])[][N]

  // Expected
  const [c] = singleton
  // const c: "a" | "b"
  // @ts-expect-error: (Property '1' does not exist on type '["a"] | ["b"]'.(2339))
  const [, err] = singleton

  // Slightly unexpected
  const [,] = singleton // type is no longer generic here
  // const singleton: ["a"] | ["b"]
  const ___ = singleton // but here it is generic again
  // const singleton: (["a"] | ["b"])[][N]

  // Unexpected
  const [, ...rest] = singleton
  // const rest: ("a" | "b")[]
  // Expected: const rest: []
}
```
[TypeScript playground](https://tsplay.dev/wRldEm)

**Comment by JoshuaKGoldberg** [comment]
_Even teenier_ of a repro for that last `// Unexpected` :smile:: 

```ts
const test = <N extends number>(singletons: ['a'][], i: N) => {
  const singleton = singletons[i]
  //    ^?

  // Unexpected
  const [, ...rest] = singleton
  //           ^?
  // Expected 👎: const rest: []
}
```

[TypeScript playground](https://www.typescriptlang.org/play?jsx=0#code/MYewdgzgLgBFCm0YF4YB4ByN4A8FgBMIYwBXAWwCN4AnAPgAoIBLMAcwBt4pwIAuGAG0A5AENhAXUESANDGYCMAShR0YAbwBQMGKEiwW7LjzAoYhzt16DmE7TAD0DnToB6Afk32nMAKphcAAd4YAQCez0kQTkAOjiaRCgJMwtjcG9nFyyXDwyYAFEcYND4AhhAXg3AOR2BSNgE6AFpTQBfTSA)
