### ISSUE TITLE
"import type { X }" with exported value with same name gives "Individual declarations in merged declaration 'X' must be all exported or all local."

### ISSUE THREAD

**Issue by mb21** [microsoft/TypeScript#50880]
# Bug Report

### 🔎 Search Terms

- Individual declarations in merged declaration 'X' must be all exported or all local.
- import type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, the latest being 4.8.3, and I reviewed the FAQ for entries.

### ⏯ Playground Link
cannot import other files in playground

### 💻 Code

```ts
import type { x } from './foo';

export const x = 7
```

### 🙁 Actual behavior

Running `tsc` gives:

```
Individual declarations in merged declaration 'x' must be all exported or all local.
```

### 🙂 Expected behavior

No error.

**Comment by RyanCavanaugh** [comment]
The error is exactly describing the situation that's happening.

You can write
```ts
import type { x } from './foo';

const x = 7

export { x };
```

**Comment by mb21** [comment]
Thanks, that works indeed!

I suppose I don't know enough about JavaScript module syntax to see the difference :P `export { x }` is not a declaration?

**Comment by mb21** [comment]
Actually, it doesn't work. There is no type error in the exporting file, but when I save what you posted to `bar.ts`, and in another file:

    import { x } from './bar';
    console.log(bar);

I get:

    'x' cannot be used as a value because it was imported using 'import type'

**Comment by whzx5byb** [comment]
@mb21 See https://github.com/microsoft/TypeScript/issues/40583#issuecomment-693542271

**Comment by mb21** [comment]
Thanks! This works indeed:

```ts
type x = import("./foo").x;
export const x = 7;
```
