### ISSUE TITLE
Incorrect completion in end tag of JSX element

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#5088]
We are able to give useful completion in opening tag of jsx element. We should be doing the same thing for closing tag. It will also be helpful to insert appropriate name when users type `</` 

![autocompletioninjsxelement](https://cloud.githubusercontent.com/assets/489742/10259004/6a196a90-6918-11e5-9704-af809d1f8ce7.gif)

In this case, the completion in the close tag should show `</div> and complete with that.

**Comment by mhegazy** [comment]
i would say, the completion list should only have the containing open tags

**Comment by danquirk** [comment]
Even better would be just automatically inserting the closing tag when you create an opening tag. Many other editors do this.

**Comment by yuit** [comment]
@danquirk I agree. that will be sweet :cookie:

**Comment by SaschaNaz** [comment]
Is there any open issue for the "HiHi" part? I think no completion should be there.

**Comment by DanielRosenwasser** [comment]
Just opened #5096, thanks @SaschaNaz

**Comment by RyanCavanaugh** [comment]
Fixed in #5184.
