### ISSUE TITLE
TypeScript aliases do not support accessing static members

### ISSUE THREAD

**Issue by ReeceSX** [microsoft/TypeScript#50897]
Given a `type X = MyClass` alias, TypeScript does not lookup static members of a class, throwing an error complaining about value usage.

### TypeScript

Reported Version: TypeScript v4.8.2

### Code

[Playground Link](https://www.typescriptlang.org/play?ssl=11&ssc=32&pln=1&pc=1#code/CYUwxgNghgTiAEkoGdnwComQF3gbwFgAoeU+HKbASzHgDkQB3AClgHMAGALngDsBXALYAjEDACUPKLwCeAbmIBfYsWwyADgkw4ATPAC8GLNhVEIIXFANGcAOgYsArAEYd44udzDr27DvtMzC5upp7wUHo8vnqGvgFOru5mFvDCkTZ+Psb+DkGJQA) 

```ts
declare class Test {
    static New(arg0: number): any;
}

type Test2 = Test

let a = Test.New(512) // works
let b = Test2.New(512) // does not
```

### Error

`<type alias> only refers to a type, but is being used as a value here.`

### Expected behavior 

`Test2` should be replaced with the full expression of the type alias

**Comment by MartinJohns** [comment]
This is working as intended. Classes are a special case that define a type **and** a value. Your type alias only refers to the type, but static members are accessed using the value.

You can store your class in a variable, that'll work.

**Comment by ReeceSX** [comment]
> This is working as intended. Classes are a special case that define a type **and** a value. Your type alias only refers to the type, but static members are accessed using the value.
> 
> You can store your class in a variable, that'll work.

That's literally not how aliases work on any other language

**Comment by ReeceSX** [comment]
[Playground Link](https://www.typescriptlang.org/play?ssl=11&ssc=32&pln=1&pc=1#code/CYUwxgNghgTiAEkoGdnwComQF3gbwFgAoeU+HKbASzHgDkQB3AClgHMAGALngDsBXALYAjEDACUPKLwCeAbmIBfYsWwyADgkw4ATPAC8GLNhVEIIXFANGcAOgYsArAEYd44udzDr27DvtMzC5upp7wUHo8vnqGvgFOru5mFvDCkTZ+Psb+DkGJQA)

**Comment by ReeceSX** [comment]
> You can store your class in a variable, that'll work.

and don't you tell me what will and will not work. no, this isn't an acceptable solution. in my application, consts and other such root variables share a global namespace like many other non-sandboxed runtimes. the whole point of using type aliasing is not to provide what would roughly be equivalent to a C++ inline of a singleton.

**Comment by MartinJohns** [comment]
TypeScript is not like every other language. It's dedicated to **only** add type information on top of JavaScript (despite some poor legacy decisions). From the [TypeScript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> Non-Goal 1:  
> Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.

What you suggest would either require the introduction of a temporary variable (violates goal 3), or replace the identifier in the emitted code (violates goal 7). The user also might have a value `Test2` already, in which case this would be ambiguous at the value level.

It's easy enough to work around the issue if you want:

```typescript
type Test2 = Test
const Test2 = Test
```

---

Whether you agree or not, it's not a bug. It's working as intended. You might want to rephase your issue as a feature request instead, but I heavily doubt it would be accepted.

**Comment by ReeceSX** [comment]
> Whether you agree or not, it's not a bug. It's working as intended. You might want to rephase your issue as a feature request instead, but I heavily doubt it would be accepted.

Control F, "bug", seems like you're the only one calling it a bug.

**Comment by MartinJohns** [comment]
> seems like you're the only one calling it a bug.

Your issue resembles the issue template for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md) more than the one for [feature suggestions](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Feature_request.md).

Anyway, I said my bits, I'm out.

**Comment by ReeceSX** [comment]
NOOOOO THE TEMPLATE!!!!!!!!!!!

**Comment by ReeceSX** [comment]
![image](https://user-images.githubusercontent.com/97978250/191739213-8e36864e-de9a-482c-be27-fdd9a2f88cec.png)
"heres your metaprogramming-language type-alias bro. saved you traversing a single object bc typescript"

**Comment by somebody1234** [comment]
hi @ReeceSX
let's go over your examples:
> C macros
a preprocessing step. C doesn't even know they exist at parse time
> C++ aliases
like c# (see below), C++ completely lacks types that are not classes.
> generics in almost all OOP languages
these are not even aliases.
> c# using
c# lacks types completely; everything is a class (or a struct or an interface if you want to be pedantic. regardless, it completely lacks types that are *not* classes.)

so it'd be *greatly* appreciated if you provide a valid example, thanks

**Comment by ReeceSX** [comment]
> so it'd be _greatly_ appreciated if you provide a valid example, thanks

I did... I even fucking explained the implementation details in V8 and proved how stupid this is of a requirement for aliasing any arbitrary type.

**Comment by ReeceSX** [comment]
> and don't you tell me what will and will not work. no, this isn't an acceptable solution. in my application, consts and other such root variables share a global namespace like many other non-sandboxed runtimes ^1. the whole point of using type aliasing is not to provide what would roughly be equivalent to a C++ inline of a singleton. i know the cost of what the final expression is, and i dont care what predetermined typescript language rule it violates ^2.
> 
> ^1: a well known defect in v8 is its clients' inability to scope evals. compilers builtin global eval, ast scoping, and such works; however, embedders have to wrap scripts with a `(function(module, filename, require, ...){})()`. although, other v8 users may use different contexts, requiring different script interop considerations and global proxy hackery. Node, for instance, uses this wrapper: https://github.com/nodejs/node/blob/main/lib/internal/modules/cjs/loader.js#L237 point is, there is no inline linkage. "tehe storage your class in variable," literally where? and why should i even care [to dirty up global with api references] for something i don't even intend to cache? this doesn't extend past decl files and metaprorgramming territory. if i wanted a variable defined a certain way, i'd demand that of the api exports.
> 
> ^2: aliasing a table lookup or two isn't that bad

**Comment by ReeceSX** [comment]
What in the fuck do you think a static member is of? A unicorn? Or a type? Are we seriously struggling to comprehend "typescript literally lacks class aliasing"?

**Comment by somebody1234** [comment]
by the way, i've fixed your original post by adding a single line. for anyone else that may be interested, hopefully this is at least a bituseful:

[Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwComQF3gbwFgAoeU+HKbASzHgDkQB3AClgHMAGALngDsBXALYAjEDACUPKLwCeAbmIBfYsWwyADgkw4ATPAC8GLNmJgA9rxxHdB6yaLEIIXFFvbsAOgYsArAEYdcUdneGE3Yx0vJmZ-QJUiJxc9Hnc9Q3co3wCghJDhZLs0wsyY7KA)

```ts
declare class Test {
    static New(arg0: number): any;
}

type Test2 = Test
const Test2 = Test

let a = Test.New(512)
let b = Test2.New(512)

let a2 : Test2 = Test.New(512)
let b2 : Test2 = Test2.New(512)
```

**Comment by m-rutter** [comment]
@ReeceSX Can you tone down the language and the hostile tone. People are just trying to help you, and are volunteering their own time to do so. If you can't consider taking your energy elsewhere.

**Comment by ReeceSX** [comment]
> > . if i wanted a variable defined a certain way, i'd demand that of the api exports.
 for the third time

**Comment by ReeceSX** [comment]
> People are just trying to help you, and are volunteering their own time to do so. If you can't consider taking your energy elsewhere

I'd suggest useless energy be diverted elsewhere. If the issue went over your head, leave it at that. I didn't ask for your time.

**Comment by MartinJohns** [comment]
Before any confusion comes up, I want to clarify:  
Despite [being addressed as "King"](https://github.com/microsoft/TypeScript/issues/50897#issuecomment-1254842604), I am **not** a monarch.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior; type aliases *only* create types. A class constructor is a value; you can use a `const` to alias it. The internals of v8 are wholly irrelevant here.

@ReeceSX the CoC has been linked above; the very next instant you again interact with folks like you have in this issue, you will find yourself blocked from the Microsoft GitHub organization. This is not acceptable tone or behavior..
