### ISSUE TITLE
@implements should not require deprecated properties

### ISSUE THREAD

**Issue by clshortfuse** [microsoft/TypeScript#50899]
# Bug Report

### 🔎 Search Terms

* deprecated implements
* deprecated implements missing properties

### 🕗 Version & Regression Information

Nightly, always exhibited

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.9.0-dev.20220921#code/JYOwLgpgTgZghgYwgAgILIN4FgBQz-ID0AVMbgfscgMoRgDOyA9lMlHVMBAG4SMAWTAO7Iw-FEwBGAKwgIwyYIzgAbYAHMQEACbIhwMcjjbpiCOFEQAHmAB05ClQAC2iAAd2COJG0OCxQj8jNU0ALmR6ME4QdQBuIJIqWgZmVnYorl5lSxtgyCgQb2BeUSZRcWR1KDg3fmAEW2QAoNUwcMjouNwAX1xcBBU4ekYAIUUAWzcVCHHzFPRsPAJW5ABeZAByDficXpxcIA

### 💻 Code

```ts
interface A {
    /**
     * Sets or retrieves how the object is aligned with adjacent text.
     * @deprecated
     */
    align: string;
    /** Sets or retrieves a text alternative to the graphic. */
    alt: string;
}

class B implements A {
    alt = '';
}

```

### 🙁 Actual behavior

>Class 'B' incorrectly implements interface 'A'.
>Property 'align' is missing in type 'B' but required in type 'A'.

### 🙂 Expected behavior

No errors.

---------

This stems from trying to `implement` HTMLImageElement with a Web Component. If properties are deprecated, it stands to reason authors should not implement them. If TS will emit an error that a deprecated property should be implemented, then the entire TS error need to be ignored. If this is done, then if/when a new property is added to the `HTMLImageElement` spec, no error would be reported. At best, they should be warning, not errors.

https://github.com/microsoft/TypeScript/blob/a9ecc675d636c3bbca697bc4881b019e8645a7a6/lib/lib.dom.d.ts#L6842

Conversely, the opposite may be true: an author should be warned against implementing deprecated properties. But that's another issue.

**Comment by MartinJohns** [comment]
But the interface says it should exist. :-/ The value might be passed to an old implementation that still uses the deprecated properties, letting the developer omit these properties would be unsound.

**Comment by clshortfuse** [comment]
>But the interface says it should exist.

Not by definition. By definition `deprecated` means it *may not exist*. 

>Programmers should not use or assume the existence of these features and behaviors when writing new ECMAScript code.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Deprecated_and_obsolete_features

Therefore typescript should not "assume the existence" of the property.

Also, practice, is TypeScript really going to just say all deprecated properties, even ones from HTML3.2, back in 1997 with IE4 should still be implemented? Should all `@deprecated` properties emit *errors* because they weren't implemented? Adding code just to appease TypeScript is wasted codespace. 

I understand it could be a wide breaking change, but the reality is, I also can't find a workaround. So what *is* the right solution? Remove them from the types? Add dates to deprecations and let the dev decide when old is old enough?

Right now there's only one "solution" and it's disable type-checking, which clearly has lasting negative effects. Maybe something in `tsconfig.json` like to relax the enforcement, and stay in-line with the definition of deprecated.

**Comment by HolgerJeromin** [comment]
> Not by definition. By definition deprecated means it may not exist.

You are mixing TS types and JSdoc information. Current typescript compiler treats TS definitions more important than jsdoc, which is IMO a valid behavior.

**Comment by clshortfuse** [comment]
I think I misunderstood @MartinJohns point about it being optional. I understood it as I should put them as optional properties in the implementing class.

But the reality is the `interface` is mis-typed. It means I should probably start a PR to fix all the lib.dom.d.ts deprecated properties that are not listed as optional.

It's contradictory to say something is required and deprecated, but I can see TS respecting what's written as taking preference.

**Comment by MartinJohns** [comment]
> Not by definition. By definition `deprecated` means it _may not exist_.

For me "deprecated" means something like "this will be removed in the future, do not use it anymore". But in the meantime, it may still be used by some implementations that haven't been updated yet. So, in order for code to not break, the property must still exist.

If it doesn't have to exist anymore, then you shouldn't use "deprecated", but instead remove the property entirely.
