### ISSUE TITLE
typesVersions should not have `4.9.0-beta <=4.8`

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#50909]
currently, a typesVersion entry of `"<=4.8"` will be satisfied by 4.9.0-beta.

That's because our semver code treats `"4.8"` as the range ">=4.8.0 and <4.9.0". It should actually be ">=4.8.0 and <4.8.Infinity". It should not include 4.9.0-*xxx*.

**Comment by fatcerberus** [comment]
I always forget semver treats x.y.z-suffix as an earlier version than x.y.z

**Comment by DanielRosenwasser** [comment]
Aside: this was found while working on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62375

**Comment by rbuckton** [comment]
Ah, it should be treating `<=4.8` as `<4.9.0-0`, not `<4.9.0`.
