### ISSUE TITLE
Restrict top-level expressions and add main function

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#5091]
If I import a module in TS I want to make sure that it doesn't do some top-level calls or evaluations before I use any of its method. It can be harder to debug if it doesn't follow a predictable execution order. By predictable execution order I mean blocks of code that could be traced back to a main function by following a call stack of functions you called(so excluding import statements).

I propose a compiler option that restrict developers from defining a top-level expressions. So the following won't be doable:
```typescript
function test() {
}
test(); // error a top-level expression
var a = 1 + 2; // error a top-level expression
var test = function() {} // error a top-level expression
...
```
All expressions must be inside a function body to not get a compile error.

And in order for any TS program to execute anything at all we must add a main function:
```typescript
function main() {
   ...
}
```
That gets compiled to:

```typescript
function main() {
   ...
}
main();
```
And we also need to enable a new compiler option for it:
```typescript
--restrictTopLevelExpressions
```

I think with this feature. It will add more structure to TS applications.

**Comment by mhegazy** [comment]
This looks like a [tslint](https://github.com/palantir/tslint) rule for me.

**Comment by tinganho** [comment]
@mhegazy this proposal is to add a main function to TS. I don't think a tslint rule makes so much sense?

**Comment by RyanCavanaugh** [comment]
I don't see the point of adding code in the compiler itself to simply append `main();` to the output of a script. You can safely do that as a trivial post-build step if you have the TSLint rules that prevent global statements.

**Comment by macdevign** [comment]
I find it useful for source file to have  its main method ( eg  java's main, ruby's __FILE__ == $0 check) so that we develop app piece by piece easily. The "main" concept allow for one to easily test and experiment with code related to the code in the file. Considering that Typescript is designed for large scale application development, having "main" as part of language feature to quickly run code is useful.
