### ISSUE TITLE
Type guard affects type of variable in surprising way

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#50916]
# Bug Report

### 🔎 Search Terms

type guard / fall through / narrow / change / lazy / evaluate

### 🕗 Version & Regression Information

- This changed between versions v4.7.4 and v4.8.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/C4TwDgpgBAkgJhAdsAlqAPAFQHxQLxQDeA2gNJQqJQDWEIA9gGZSYC6AXC2awL4DcAWABQw0JCgBlCABtGWXAUxQIAD2BI4AZygBXRNUT0A7lQD8sBMjQh5UToggA3CACdBIoYz0BjVPSoomvIAFI4AhtI6EJyYAJSc4ZHQgZIycjhEwlDZUC4QwDouVMAuUe48wqLg0ACqiCj++NmEYfY6ALYARq48UAA+RJ1tXT39RN7D3S78lZ4+flSqYe1g0hDBKpx1DYixmUI5FMzBgRuxe4QVBzkox6cq50RXh7dQJ5pnF883dx8PX1kfm97o9LoDsq93p8nuCjsC-qDvhDftCwR5DnkCkUoCp3IcAPT4w5QAB6pmEV1mYmgABFjIhvGFNMAAPKIaQgGCMAByEAgCDg6AkOkgLkw1QANJIdJ1xeJVOpEFppaK5RAFCrXGrlGoNNphbLqlBzMLVUbOAa1e5hF4GQsKJoAEwhRJRGLxKCu5LaOkmRnMtkcrm8-n8rBSqSyeS4QiwzGFYqlCDlWa23w7KBGeguahhFz0PRwDZber+C6wyGBR2opFw97V-4w67I+ENxEV35tgHNutVmsd1v9nuVp1Dl6dodx-IJnF4nKE4lkilAA)

### 💻 Code

```ts
type Identity<T> = {[K in keyof T]: T[K]};

type Self<T> = T extends unknown ? Identity<T> : never;

function is<T>(value: T): value is Self<T> {
    return true;
}

type Union =  {a: number} | {b: number} | {c: number};

function example(x: Union) {
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}
    if (is(x)) {}

    return x;
    //     ^?
}
```

### 🙁 Actual behavior

The type of `x` is "narrowed" to `Identity<Identity<Identity<Identity<Identity<Identity<Identity<Identity<{a: number;}>>>>>>>> | Identity<Identity<Identity<Identity<Identity<Identity<Identity<Identity<{b: number;}>>>>>>>> | Identity<Identity<Identity<Identity<Identity<Identity<Identity<Identity<{c: number;}>>>>>>>>`

It's as if a variable gets narrowed to the union of the types of both sides of the type predicate, e.g.
```tsx
if (isA(aOrB)) {
  // `aOrB` gets narrowed to `A`
} else {
  // `aOrB` gets narrowed to `Exclude<typeof aOrB, A>`
}

// `aOrB` gets narrowed to `A | Exclude<typeof aOrB, A>` but it should just be left alone
```

### 🙂 Expected behavior

The type of `x` doesn't change.

**Comment by ahejlsberg** [comment]
This is an effect of #50044. The issue here is that the argument type and the asserted type are subtypes of each other, and therefore appear interchangeable in control flow analysis. From the PR:

> Note that one issue with favoring the asserted type is that CFA continues with that type after the conditional block. Though undesired, that's an effect of how CFA works in the face of mutual subtypes. This behavior was already present for singleton types, but now also extends to union types.

So this is effectively a design limitation, but we'll continue to think of ways in which to improve it.

**Comment by MichaelMitchell-at** [comment]
Would it be possible to have TS more eagerly resolve `Identity<Identity<Identity<Identity<Identity<...` down to `Union`? A problem that we encountered is that given a more complex type and enough `if` blocks, the narrowed type becomes complex enough that it both slows down tsserver to a crawl and we start getting "type instantiation is excessively deep" errors.

**Comment by ahejlsberg** [comment]
The core issue is that `Union` and `Identity<Union>` are both subtypes of each other. If you change `Identity<T>` to always be a subtype of T, for example by intersecting with a tag type, things work as expected in your scenario:

```ts
type Identity<T> = {[K in keyof T]: T[K]} & { __tag__: void };
```

Fundamentally, when the argument and asserted types are subtypes of each other, the reason we favor the asserted type is that you must have written the assertion for _some_ reason. I'm not sure what the reason is in your example, but presumably there is some difference in behavior?

**Comment by MichaelMitchell-at** [comment]
Here's an example that is a lot closer (though still simplified) to actual situation that we had:
[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAiBLAzjKGBGArjMACYDSwiA8gGYA8AKgHxwC8cjcoJAdqVjiFeAa14QA7rzgB+OCKoRanOAC44vYADdgUANwAoA6EiwEyVACVgAR0IYowJgBo45biD4D5i5S3Zw1AC2GDAubqwAZHDWdg5k9AAKGADGIuHkzMyGBkgocAByAIZQUJIAQoiUiEweXoIQ+ABWwCkwru48wPyCiWUosFVUrBxcXT1CouJSBnCybnXd3gqISpyzc-Ox9o4ZzBtz6po6UBtH2ro5APQAVDezNzHAYAA2qUUkgmAl8GswABaoTQSOD4YD-IpaDDQOB-QFwAAGGF4CNhAw+MNoZSCDzg-xgMDAWFUVyuAHNQv9CPgAHQpCBBK4hFJlLBKGBXRgWADKLIwYA5YEILxeVwArAAGABsMtxrAAksoVhoikFgIIinAwP1dEgEBD4KBsDBBMi4Gy1XB6bwcKFCN1fsoAag8qg1o0ms45fqXRZYcoPXBsCrSpIyKCilhwxBpM6tY4o7wUm6oHAivhE8n-fqPvGIAMkDTvX1tNDCFgXog4BI3bxK3BSBhSPrg7QYTg8LwyXA3iQoEUXj5EFgi3AbldjOBoPBaMI2tDpBCsLVxt4Pa12gtV4JMB2CMQyNU6EwsgAKDYe9SML1zFbqcgGACU6kDweKoYklWqezgAG8No4MCEFA0jKmaHqGAAvkYrpwOUGBkgAqrwC4BAccAAD5-kURyEEEYL6KCuH4bo0GbJhf74MRBF6Fa1GkehWG-ik9GEaQrFkZsTHsRoeE0dwHGMX+wCsbRtCCeRTHibxJGEThMkEdBRizkmMCoaAqqvMAp4gOo8FIShMaPn+6EYMop5LjprgAORFNZj7Gb+nFzGZcAWZGVlwNZ+D2Y5zlBuZlkgDZKS+X+-mue5WCedZpBhU5pmBR5wVecA8URUl0UpdZtDpUY5GAcB0ggIY5GkuRcAAHoyAYkFAA)

**Comment by ahejlsberg** [comment]
I that last example, I'd recommend re-writing the `Require<T, K>` type to only narrow when necessary. This way the returned type is either `T` or a subtype of `T`, and therefore types property revert back as expected.

```ts
export type Require<T, K extends keyof T> =
    Pick<T, K> extends Required<Pick<T, K>> ? T : Omit<T, K> & Required<Pick<T, K>>;
```

**Comment by MichaelMitchell-at** [comment]
> I that last example, I'd recommend re-writing the `Require<T, K>` type to only narrow when necessary. This way the returned type is either `T` or a subtype of `T`, and therefore types property revert back as expected.
> 
> ```ts
> export type Require<T, K extends keyof T> =
>     Pick<T, K> extends Required<Pick<T, K>> ? T : Omit<T, K> & Required<Pick<T, K>>;
> ```

That's what we pretty much ended up doing (the playground link in the description actually has an example at the bottom of the code) and we added this optimization to our other utility types, but it was certainly an unexpected footgun as this was the first time we've ever had to optimize our types in this particular way.

**Comment by ahejlsberg** [comment]
Agreed about the footgun. We'll continue to think about ways to improve this.

**Comment by MichaelMitchell-at** [comment]
Thanks @ahejlsberg !
