### ISSUE TITLE
4.9.0-beta release is missing `lib` folder

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#50927]
# Bug Report

https://unpkg.com/browse/typescript@4.9.0-beta/

It looks like the `lib` folder is missing?

After installing I see this error in VS Code:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/921609/192063596-518be735-ab18-4c49-9384-40d2b28ffd7a.png">

**Comment by RyanCavanaugh** [comment]
Investigating!

**Comment by RyanCavanaugh** [comment]
Today we learned that npm 8 supports `./` as a leading path component when specifying a directory in the `package.json`'s `files` array, but not npm 6.

**Comment by DanielRosenwasser** [comment]
549b5429d4837344e8c99657109bb6538fd2dbb5 fixes it, #50930 fixes it for future releases.

**Comment by fatcerberus** [comment]
Why is Ryan's comment being 👎🏼'd given that the the fix in #50930 aligns with it?  Is there something I'm missing...?

**Comment by DanielRosenwasser** [comment]
We have nothing wrong with what Ryan said, we are just mad about the root cause. 😅

**Comment by RyanCavanaugh** [comment]
The 👎 is coming from inside the house (my own account)

**Comment by DanielRosenwasser** [comment]
4.9.1-beta is the new version. 😩
