### ISSUE TITLE
type narrowing wouldn't work properly for partial record with generic keys

### ISSUE THREAD

**Issue by ycmjason** [microsoft/TypeScript#50920]
# Bug Report

### 🔎 Search Terms

partial record, narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220921#code/DwaQpgngBGAeAuYB2ATAzlN8BOBLJA5gDRQBqAhgDYCuYAfABQD2ARgFYBcUACudvLirAASmADGTbClCQSFGvTokA1pC7gIASigBeOlADeAKChQJSLGYAW45bqgMAblVpd5tbXsMBfANwmzJgt4KGcFe1Y2AG1VCABdf1NcADMHeAgABzAmVLDaXR0dKAByalQwZPwwFGLtbDB4amwkROtbJxcwTV8oAHpemFgssRC8sCh4JigWcZyJzPGAA3cwRZICJhDlzqgAHygylAqqlEWofCwwchQjPyMjZnYuXn5BShFxSWksPEISH-wBDoSigsS4AMInn0xlM5ksYhsYjsRQYynBOEBUJ8rThox2RUiMUgCQCKTSCzmYwKRVK5UqSGqtSg9UazRxiOUHQU3T6A3gVlwGAk2HqI0o0CQfGwTAA7hMbPMshMposIQRFrdfEA)

### 💻 Code

```ts
<Key extends string, Value>(obj: Partial<Record<Key, Value>>, key: Key) => {
  const check = (value: Value) => {};
  const value = obj[key];
  if (typeof value === 'undefined') return;
  check(value); // expect value to be of type `Value`, got `Value | undefined` instead
};

(obj: Partial<Record<string, string>>, key: string) => {
  const check = (k: string) => {};
  const value = obj[key];
  if (typeof value === 'undefined') return;
  check(value); // this correctly narrow the type to `string`
};
```

### 🙁 Actual behavior

- the type of `value` is not narrowed correctly to `Value`, but got `Value | undefined` instead.

### 🙂 Expected behavior

- the type of `value` narrowed correctly to `Value`

**Comment by fatcerberus** [comment]
The error message is a bit misleading as to the actual problem with this code.  In the first example, `check()` doesn't want a `string` - it wants a `Key`, which is generic and therefore might be narrower than `string`.  However, `obj[key]` might be any arbitrary string, so it's not typesafe to use it as a key.  Hence the second part of the error message:

> 'Key' could be instantiated with an arbitrary type which could be unrelated to 'string | undefined'

For a concrete example, suppose the input to the outer function was a `Record<"foo" | "bar", string>` with both properties set to `"quux"`.  Now `Key` would be `"foo" | "bar"` but you'd be calling `check()` with `"quux"`.

**Comment by ycmjason** [comment]
@fatcerberus oh ya there is a typo, I've updated the original post to reflect this.

**Comment by RyanCavanaugh** [comment]
> the type of value is not narrowed correctly to Value, but got Value | undefined instead

What you actually have in `value` is a `Partial<Record<Key, Value>>[Key]`, which isn't something we recognize as narrowable-away-from-`undefined` since it's an indexed access into mapped type, rather than a union. That's recognized as assignable *to* `Value | undefined`, but it's different and isn't something we're currently capable of narrowing in the absence of negated types.

The function as written can't adequately demonstrate why that narrowing is difficult to do correctly, but it's also the case that the function can be written as
```ts
const fn = <Obj,>(obj: Obj, key: keyof Obj) => {
  const check = (value: Obj[keyof Obj]) => {};
  const v = obj[key];
  const value = obj[key];
  if (typeof value === 'undefined') return;
  check(value); // expect value to be of type `Value`, got `Value | undefined` instead
};
```
which works without loss of apparent functionality.
