### ISSUE TITLE
Object spread with ternary causes invalid union on property

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript#50922]
# Bug Report

Originally commented over here: https://github.com/microsoft/TypeScript/issues/48326#issuecomment-1256436955

### 🔎 Search Terms

spread, ternary, object spread, union, property

### 🕗 Version & Regression Information

- This changed between versions [4.1.5](https://www.typescriptlang.org/play?ts=4.1.5#code/GYVwdgxgLglg9mABMMAKAFgLkQb0QQ2wGcoAnGMAcwG5EAjAfmzAFMA3F02iJxVj0ogC+iAD64CxMhRr0p5Kt3kzhASlxCAUJoA2LKIgAm+KPkQBeRAHJ8VgkWu2xicIZbAKLQ9W0B6X4iAoOSIACroMA4A7nCkANYOFKEAypooqMamiAwShNZWADRyeYUQ2BlmIth4uVZ2Qqo+mv6IgDLkyYgQ+GBgcAYelCCkLIhQ4Q5wAA6wCIhwIFCF7CxIo3OU6IgwUFYO+DpEcIhsezCGqWg4moiSxVeIAHSP6SZm2Xh02LUlZS-CiFX1fKaeqNZrBMIRRDROIJJAhFJpS7XGoFO6Pe7PTJvIpfDo-TKVDT2XAAbViLAAnsoqABdZhLUiA4ENTRAA) and [4.2.3](https://www.typescriptlang.org/play?ts=4.2.3#code/GYVwdgxgLglg9mABMMAKAFgLkQb0QQ2wGcoAnGMAcwG5EAjAfmzAFMA3F02iJxVj0ogC+iAD64CxMhRr0p5Kt3kzhASlxCAUJoA2LKIgAm+KPkQBeRAHJ8VgkWu2xicIZbAKLQ9W0B6X4iAoOSIACroMA4A7nCkANYOFKEAypooqMamiAwShNZWADRyeYUQ2BlmIth4uVZ2Qqo+mv6IgDLkyYgQ+GBgcAYelCCkLIhQ4Q5wAA6wCIhwIFCF7CxIo3OU6IgwUFYO+DpEcIhsezCGqWg4moiSxVeIAHSP6SZm2Xh02LUlZS-CiFX1fKaeqNZrBMIRRDROIJJAhFJpS7XGoFO6Pe7PTJvIpfDo-TKVDT2XAAbViLAAnsoqABdZhLUiA4ENTRAA)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMMAKAFgLkQb0QQ2wGcoAnGMAcwG5EAjAfmzAFMA3F02iJxVj0ogC+iAD64CxMhRr0p5Kt3kzhASlxCAUJoA2LKIgAm+KPkQBeRAHJ8VgkWu2xicIZbAKLQ9W0B6X4iAoOSIACroMA4A7nCkANYOFKEAypooqMamiAwShNZWADRyeYUQ2BlmIth4uVZ2Qqo+mv6IgDLkyYgQ+GBgcAYelCCkLIhQ4Q5wAA6wCIhwIFCF7CxIo3OU6IgwUFYO+DpEcIhsezCGqWg4moiSxVeIAHSP6SZm2Xh02LUlZS-CiFX1fKaeqNZrBMIRRDROIJJAhFJpS7XGoFO6Pe7PTJvIpfDo-TKVDT2XAAbViLAAnsoqABdZhLUiA4ENTRAA)

### 💻 Code

```ts
function fn(h: { a: string; b?: never; c?: never } | { a: string; b: string; c: string }) {}

let data = 'a' as 'a' | undefined;

// ✅ This works in TS
fn(data ? { a: '', b: '', c: data } : { a: '' });

// ❌ TS cannot figure this option out, even though it's also valid
fn({
  a: '',
  ...(data ? { b: '', c: data } : {}),
});

// ✅ This works in TS
fn({
  a: '',
  ...(data ? { b: '', c: data } : {} as {[key: string]: never}),
});
```

### 🙁 Actual behavior

`b` was recognized to be a `string | undefined`, although it's only possible to be a `string`

### 🙂 Expected behavior

`b` should only be a `string`

**Comment by RyanCavanaugh** [comment]
We had to change this behavior in 4.2 to avoid an exponential explosion caused by repeated spreads in the same object.

**Comment by RyanCavanaugh** [comment]
[Thread with more context](https://twitter.com/SeaRyanC/status/1544414378383925250)

**Comment by karlhorky** [comment]
Ok thanks, closing :)
