### ISSUE TITLE
Missing properties on union types

### ISSUE THREAD

**Issue by pauhull** [microsoft/TypeScript#50925]
# Bug Report

### 🔎 Search Terms

- union type
- missing properties

### 🕗 Version & Regression Information

Typescript version: v4.9.0-dev.20220921

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220921#code/C4TwDgpgBAglC8UDeBYAUFTUwCcD2YMAXFAHYCuAtgEYQ4Dc6W2+YAQiRTXYxlrgQDCnKrQZN+rACIju4tAF906UJChsEyCZgGFZY3s10coAZ2A4AlqQDmhyUJLlSAEwgAzaxBe8laFeDQgppwAD7qvOgANhDAUMAQ5iSCkWiq0AAqAAqscIjpeO7xicAAdLow9FAA9NVQALQAfPGBUNm5mlwGAWrtBBr5gYXF5uWsbFW1Dc3pbTn9muZWtlDhXTw9mfNgwYOQwwmjuik1dU0tvdu7ZKJ0q1DObp6k3qlTGQDKAEwArD8AjCRtnRQFAAOS6KRgqAuPCJMh4OIQAAelnMUDwpAu0DBgjBpU2c2kmgKRUOZUhkzOzRRkAAxgkXCRZn0wFJOrccPdHh4vD4gA)

### 💻 Code

```ts
type A = {
    propA: number;
    propB: number;
    propC: number;
    propD: number;
}

type B = {
    propA: number;
    propB: string;
    propC: undefined;
}

type C = A | B;

let test: C;

type TPropA = typeof test.propA; // -> type TPropA = number;
type TPropB = typeof test.propB; // -> type TPropB = string | number;
type TPropC = typeof test.propC; // -> type TPropC = number | undefined;

// TS2551: Property 'propD' does not exist on type 'C'.
type TPropD = typeof test.propD; // -> expected: type TPropD = number | undefined;
```

### 🙁 Actual behavior

When defining union types of interfaces, properties will be missing on the resulting type if they are missing on one of the original types.

### 🙂 Expected behavior

The resulting type should contain the said property, either as an optional or as a union with undefined (-> see TPropC)

**Comment by MartinJohns** [comment]
This is working as intended. See the [documentation on union types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types):

> TypeScript will only allow an operation if it is valid for every member of the union.

Types in TypeScript are not sealed. Additional properties are allowed. Whatever object is typed as `B` **could** have a property `propD` that is **not** a `number` or `undefined`.

**Comment by pauhull** [comment]
> This is working as intended. See the [documentation on union types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types):
> 
> > TypeScript will only allow an operation if it is valid for every member of the union.
> 
> Types in TypeScript are not sealed. Additional properties are allowed. Whatever object is typed as `B` **could** have a property `propD` that is **not** a `number` or `undefined`.

But why isn't it safe to assume that an object of type B never has the property `propD` and it thus being of type undefined? If you strictly follow typescript definitions when writing your code this should never happen. You could just as well cast `test` to `any` and change whatever property you want to whatever type you want.

I dislike this behavior because it requires the developer to use weird workarounds (like casting the object to a type which contains said property) and it defeats the purpose of a static type checker.

**Comment by MartinJohns** [comment]
> But why isn't it safe to assume that an object of type B never has the property `propD` and it thus being of type undefined? If you strictly follow typescript definitions when writing your code this should never happen.

I mentioned the very exact reason.

Here's an example:

```typescript
const value = { propA: 1, propB: 'a', propC: undefined, propD: true } // has property 'propD' typed boolean
const asB: B = value // Assignment is legal, because the two types are compatible
```

**Comment by pauhull** [comment]
Okay, I didn't consider that, makes sense. Thank you for answering my issue, I'm going to close it now.
