### ISSUE TITLE
When the compilation target is different (es5, es2015), the running result is different

### ISSUE THREAD

**Issue by gsons** [microsoft/TypeScript#50937]
### 💻 Code

![QQ图片20220924224030](https://user-images.githubusercontent.com/15610655/192104087-ea829d3c-4b9c-4032-b37e-e585dfa68392.png)
![QQ图片20220924224046](https://user-images.githubusercontent.com/15610655/192104091-50991e16-72d0-4d9b-a61d-732e9e690cca.png)

```ts
class BaseErr extends Error {
    constructor(msg: string) {
        super(msg);
    }
}
try {
    throw new BaseErr('system error');
} catch (err) {
    if (err instanceof BaseErr) {
        console.log('custom error');
    } else {
        console.log('normal error');
    }
}

```

**Comment by whzx5byb** [comment]
> As part of substituting the value of this with the value returned by a super(...) call, subclassing Error, Array, and others may no longer work as expected. This is due to the fact that constructor functions for Error, Array, and the like use ECMAScript 6's new.target to adjust the prototype chain; however, there is no way to ensure a value for new.target when invoking a constructor in ECMAScript 5. Other downlevel compilers generally have the same limitation by default.

See the chapter of `Extending built-ins like Error, Array, and Map may no longer work` in https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by gsons** [comment]
> > 作为将此值替换为 super（...） 调用返回的值的一部分，子类化 Error、Array 和其他值可能不再按预期工作。这是因为错误、数组等的构造函数使用 ECMAScript 6 的新目标来调整原型链;但是，在 ECMAScript 5 中调用构造函数时，无法确保新目标的值。默认情况下，其他下级编译器通常具有相同的限制。
> 
> See the chapter of `Extending built-ins like Error, Array, and Map may no longer work` in https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

than you so much,
