### ISSUE TITLE
Type Hints - Inconsistent behavior with types being expanded in type hints on hover

### ISSUE THREAD

**Issue by mitchell-merry** [microsoft/TypeScript#50941]
(sorry for poor titling - not sure what it should be :) )

# Bug Report

### 🔎 Search Terms

type hints, templates, expanded types / expansion, intersections, conditionals

### 🕗 Version & Regression Information

This is the behavior in every version I tried (including the nightly build), and I reviewed the FAQ for entries about type hints.

Additionally, I observed it in both TS playground and VSC.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/PQKgBA7gFghgLmAkgcgLZgMYFcBOOCmAdnADYCeYAJgPYCWhA5gFybV74YIAOO1X+OOLXwBnMCVoi4+SgBowAIywI4ZfmCj04YmATD4AHlxiFKMsCGAAoVeoDiMVPgCCAHgCiqBecPTTYqRx6BjAAXjAAIgiAPjCwAG8rAEhaShZA4IBuZMJHfHS4IMZsgF8rADIwAApPb0p9Az9KMQiMeHwGNmERCLAAfgTMds6g0QKihgBtAF0wErAWeJKASmyrDGpCKTAYOKWdsQcnZ0ywM-OLy+BgMHoN9k4wAFoG-kfbfA0tMDhqRU+jvhXFFovIlAgRFBqBAxPFbmkwBlimBck5xlk5gBCKzXC4APT66022wUe3mMEOeTcrWGXVEMVOuPuBEeLw+X2IiKhMIOYEBwLa0hG3RiOJu5wJVisMAAdIKOnSRIybsyOAgXgJeDhqoQ-jw+AJVMsrAo5bTRkqwEy2Cz1Si-pq2NV5cLRA1JNodqZbgFCsEZsaxbdCKrWa8TGZKFYAGZYENCTZgBj4OCA5xVZYJIOSpIEOC4QgJcmU46lKWgSBsADWumocYRcE0Yhobt1CGj+HwJHEtCrn1oEKhWBI9Qg1atYGjtAMPyg-ZEIiwn0sNjUALyACEPF4fI0iM1EX7GHEQXtkql0cUcnlLwxSmAKoML4eJqcypUajv6r59y0XYregGOF-wtW8ZjmBYi1WKwziJLYEAwMleUBDdTkudDzmtB47XZTROUhaEdBLIEQSDCVCQ2eCqCQik+U3AVzRFaJlVYbDnh+NcOUHQjkLyBihQA6IyLOSV1jNASLRY0M7UdbUql1MB9X4QQyGNShxIVSSrRVG01XYhTZOdRi3UMD0dG9SQX39aZAyw212NwrQiLopwNxjONOFoRNk1TTcMyzXEczzAsi141yyxxcAAFVCAIEh2jkRRlB2KhRFoBhC2MOBpBwQtEErYd6h4fAO21Who1uBAIForhqAXWgFBIfILGsdlAQAYW3OoGiaX0JhPGIzxSBEkTva80Ssq8khA7oWFqXdesiGb6X6QZlpEMDZnmFhCHwAA3AQItxRziB0PQRDyML8Dcyjtk+cJ9lojrslxci4O2CqHuLFz8E6mkJKYl7xREwkYw011LTsvSXgMvAnSqdb3Skcz6ks0aAylfBwcVFi7l0sNYa1GUg3y+sBCkCNFIEDtOHISd6E+aAKEbSzYC4fgtnkfKACssG2CBJCgWcBEZ2iRGoJwWcYYSznyjZCqoP56CkfAYHqagKuQXaDpwZAfj+VAYD7Sr9Dh7UbnoShaHlE2WxEQhkAQGBOCwGASDp0ztkTRtPg+GUgA)

(Edited since initial issue to include functions and `^?`)

### 💻 Code

I have types that I want to change depending on a string literal that is passed in via a template argument. The actual details of how this string is parsed is being left out as it is not relevant.

The type hint (what shows when you hover over a variable in an editor / TS playground) has inconsistent behavior surrounding this. The actual type information is correct. I want the types following to show as their un-expanded forms (i.e. `Game<"">` and `Game<"categories">`)

What I'm currently doing / what I expect to work: `GameA<"">` shows expanded, but `GameA<"categories">` doesn't.
```ts
type GameA<Embed extends string = ""> = {
	id: string;
	name: string;
}
& (Embed extends "categories" ? { categories: string[] } : {});

const a = {} as GameA;               // incorrect - expect type hint to be Game<"">, but shows { id: string; name: string; }!
const b = {} as GameA<"categories">; // correct - type hint shows as Game<"categories">

a.categories; // correct - error (no property)
b.categories; // correct - no error (categories exists and is string[])
```

A workaround I have found:
```ts
type GameB<Embed extends string = ""> = {
	id: string;
	name: string;
} 
& { id: string; }
& (Embed extends "categories" ? { categories: string[] } : {});

const c = {} as GameB;               // correct - type hint shows as Game<"">
const d = {} as GameB<"categories">; // correct - type hint shows as Game<"categories">

c.categories; // correct - error (no property)
d.categories; // correct - no error (categories exists and is string[])
```

### 🙁 Actual behavior

Variables of type `GameA<"">` show up in type hints as `{ id: string; name: string; }` and variables of type `GameA<"categories">` show up in type hints as `GameA<"categories">`. This is inconsistent!

![image](https://user-images.githubusercontent.com/8567231/192140922-32e04891-d5a1-4be9-abed-b209abbbef60.png)
![image](https://user-images.githubusercontent.com/8567231/192140937-9992b266-e571-4a4d-97ca-fae5e2083a47.png)

Intersecting this type with an arbitrary non-empty object causes them to both show up as unexpanded, despite their type not actually changing. In this example the non-empty objects contains a duplicate property, but it does not have to be duplicate to fix it.

![image](https://user-images.githubusercontent.com/8567231/192141006-3afe8481-6f0f-4866-be90-bf2f68f48dd1.png)

`GameA` also is expanded as the return value for functions (when inferred):

![image](https://user-images.githubusercontent.com/8567231/192141301-3ac86f2b-c127-4372-a716-bde19c562b68.png)

### 🙂 Expected behavior

I expected variables of type `GameA<"">` and `GameA<"categories">` to both show up in type hints as just that. (i.e., I expected the behavior of `GameB` for `GameA`, and for `GameB` to be identical to `GameA` in all aspects)

And for return values of functions, same logic:

![image](https://user-images.githubusercontent.com/8567231/192141351-55a3bd3f-996d-4087-81ec-c7b4c790a5ce.png)

#

Note that I want the behavior of un-expanded form here, because I find it much more readable / useful! In my actual project, it looked something like this:

![image](https://user-images.githubusercontent.com/8567231/192128254-d8e0e2a9-d671-46ba-85d0-ddac14c338cf.png)

(I have fixed this in my project using the `GameB` workaround).

**Comment by RyanCavanaugh** [comment]
Both of these displays are correct: `Game<"">` and  `{ id: string; name: string; }` are two ways of naming the same type in this program. Quick info does not have a contractual obligation to show one particular form or the other, nor to *always* show one form or the other (and indeed it's possible to write types that *can't* be shown in certain forms).

Re consistency, we have heuristics in place to "try to do the right thing". In the case of a simple object type with a spelling in the code itself, showing the type's members is *generally* preferred, so that happens. In the case of a more complex intersection like `Game<"categories">`, the alias itself is *generally* preferred, so that happens.

Switching between various type printbacks in quickinfo is a feature request.

**Comment by mitchell-merry** [comment]
That makes sense to me.

While both are correct, one is infinitely more useful to me (i.e. Game<"">) so I do wish I could force it to show like that without the workaround I posted in the original post.

Would that be possible?

**Comment by brillout** [comment]
> Switching between various type printbacks in quickinfo is a feature request.

I created a feature request for it: https://github.com/microsoft/TypeScript/issues/56010.
