### ISSUE TITLE
wrong type when use template literals as object key

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#50945]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwPpSoCCANiQPJQDKm6wAPACpygzAoAmAznFzFLQDmAPgAUXNALAwAXHEYBKALAAoAN6qAkGhx84AQzJwAvHAAGAEjUSpMAL4zDJMwZ46UfANxb3errTRgE3MrG0xpB386F303XRhvFU0tKGAYJChcDSTNAG0nAF05MwBPfUyAWhgICBI4AHceQlxQyXD7OAqK9zQM1PQSuABGMwAaLTyowKLzMsy4ZrhW2wcnTor1qeAxrTtXOF8YVTsgA)

### 💻 Code

```ts
export function _runAllOrSince<T extends string>(script: T)
{
	const all = `${script}:all` as const;
	const since = `${script}:since` as const;

	return {
		[all]: `yarn-tool ws run ${script} --concurrency 1`,
		[since]: `yarn run ${script}:all -- --since`,
	} as const
}
```

### 🙁 Actual behavior

```ts
export declare function _runAllOrSince<T extends string>(script: T): {
    readonly [x: string]: `yarn-tool ws run ${T} --concurrency 1` | `yarn run ${T}:all -- --since`;
};
```

### 🙂 Expected behavior

```ts
export declare function _runAllOrSince<T extends string>(script: T): {
    readonly [`${T}:all`]: `yarn-tool ws run ${T} --concurrency 1`;
    readonly [`${T}:since`]: `yarn run ${T}:all -- --since`;
};
```

or

```ts
export declare function _runAllOrSince<T extends string>(script: T): { 
[x in `${T}:all`]: `yarn-tool ws run ${T} --concurrency 1`; 
} & { 
[y in `${T}:since`]: `yarn run ${T}:all -- --since`; 
};
```

**Comment by RyanCavanaugh** [comment]
The proposed typing is wrong: It implies that the call `_runAllOrSince<"foo" | "bar">("foo")` produces an object with a `bar:all` property, but it does not.
