### ISSUE TITLE
Can't infer from `this` type on static class method call in JS Doc

### ISSUE THREAD

**Issue by dead-claudia** [microsoft/TypeScript#50952]
# Bug Report

### 🔎 Search Terms

- js inference
- javascript inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about differing type inference for JS and TS

### 💻 Code

**JavaScript:**

```js
/** @template R */
export class Action {
    /**
     * @returns {R}
     */
    action() {
        throw new Error("This method is abstract!")
    }

    /**
     * @template {new () => Action<any>} C
     * @this {C}
     * @return {C extends new () => Action<infer T> ? T : never}
     */
    static run() {
        return new this().action()
    }
}

/** @extends {Action<number>} */
export class Foo extends Action {
    action() {
        return 1
    }
}

const handle = Foo.run()
```

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "checkJs": true,
    "allowJs": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?strictNullChecks=true&useUnknownInCatchVariables=false&ts=4.8.2&filetype=js#code/PQKhAIAEBcFMFsAOAbAhncAlcJgChYAPRAewCdpwBjNAZ1vAEEroBLEgO3AG89x-woEHwE4oZWNACuZDg26YAviIG4V4VC3YcAFAEoe60dAAWZEgHdwHWFYCiZc2R0AiAConWDeJJMkAJuBeGgBGtNBkmtAAhC566srqQkYQMAgo6LA8Nlb64AC8AHxMWpwAPKgcAJ6FiuAAwilQpsHc9cqiYpAS0rI89eBEcBz+DDngeUUlbOWsHABmsGTgbsUA-CvgAFzWsABuSx2iaqLh6KxU4GRSuga8nQI9MlzjLbT6AHRR2voJeIlCKBDWAjeTMGYcMocKTwEJLWo4fBEUgUah0BgAMRIJEGhGGo2m2kMom+nDy9weV0kz3AAEY-okqJxwuATJV-MgsvlwFiSB9rrcgA)
      

**TypeScript:**

```ts
export abstract class Action<R> {
    action(): R {
        throw new Error("This method is abstract!")
    }

    static run<C extends new () => Action<any>>(
        this: C,
    ): C extends new () => Action<infer T> ? T : never {
        return new this().action()
    }
}

export class Foo extends Action<number> {
    action() {
        return 1
    }
}

const handle = Foo.run()
```

<details><summary><b>Output</b></summary>

```ts
export class Action {
    action() {
        throw new Error("This method is abstract!");
    }
    static run() {
        return new this().action();
    }
}
export class Foo extends Action {
    action() {
        return 1;
    }
}
const handle = Foo.run();

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?&filetype=ts#code/KYDwDg9gTgLgBAQwEYGcZQQY3pgNglFOAQWwEsIA7AHgCUA+OAbwCg53FyqAKASgC44tZmw5iYACygQA7nErA5AUSjSo3AEQAVCWSIBbYJIgATOHsSp0WGAEINvUewC+LJ3DQIYZTHCgBXGgBhOFAYYEoTIgU5PjgAXkZSbypqBEoAT3p6bndxXRRBIIAadwE4ELCIqPlFODjEki4aMkoAM2AoOC1GAH5uuEEFADdOkTExKCN-KEpauUk9PgA6GwpKPndXVxZQSFg4PAIiADEICFCQcMiiZPXqSn99JE7GVjE1nl5xifYpmBmcwAjFsWDtMFQ0HAJOkTLhgAk4GcIMsAhteEA)

### 🙁 Actual behavior

The inferred type for `handle` to in the JS version is `any`, and the `--noImplicitAny` option is not respected.

### 🙂 Expected behavior

The inferred type for `handle` to be `number` for both, as the types are fully equivalent.

**Comment by RyanCavanaugh** [comment]
This can be vastly simplified:
```ts
export class Test {
    /**
     * @template C
     * @this {C}
     * @return {C}
     */
    static test() {
        return this;
    }
}
// p: any, should be p: typeof Test
const p = Test.test();
```

**Comment by dead-claudia** [comment]
@RyanCavanaugh Yeah, I tried simplifying it further, but wasn't quite able to get it *that* simple. 😅

**Comment by a-tarasyuk** [comment]
@RyanCavanaugh It seems that the problem is not limited to static methods.

```ts
export class Test {
    /**
     * @template T
     * @this {T}
     * @return {T}
     */
    test() {
        return this;
    }
}

const t = new Test();
const p = t.test(); // any?
p;
```

[Playground](https://www.typescriptlang.org/play?ssl=14&ssc=3&pln=1&pc=1&filetype=js#code/KYDwDg9gTgLgBAYwDYEMDOa4BVhvgbwCg4S4B6AKguNLgrgAEZgBbMVZ7G0+pgCwCWmfFgC+3EryjAYAVygA7OCPG06ZCczwAKAJTKJtaXMVwYgtAG4J48YQQQFeM3AC8cBcADu2XDD3WDk7wYG5mAHRa-rrWYJZAA)

I think it's because `getThisTypeOfSignature` doesn't try to resolve the `@this` tag. Do we need to handle the `The_this_context_of_type_0_is_not_assignable_to_method_s_this_of_type_1_2684` error in this case? Since `getTypeOfSymbol(signature.thisParameter)` can return instantiated `this` type, I don't know how we can do that for `@this` tag...
