### ISSUE TITLE
Adding d.ts to tsconfig.json wiki

### ISSUE THREAD

**Issue by DeanB2015** [Microsoft/TypeScript#5095]
https://github.com/Microsoft/TypeScript/wiki/tsconfig.json has great information.  Would be nice to see a `d.ts` in the files element in `Using the "files" property example.  It would demonstrate how d.ts files can be used instead of  reference path="angular2/angular2.d.ts" />   ???

Example:

"typings/tsd.d.ts"
"angular2/angular2.d.ts"
.....

**Comment by DanielRosenwasser** [comment]
Hey thanks for the suggestion @DeanB2015 - we're going to be focusing on documentation soon, so I've opened up a bug on our wiki's issue tracker: https://github.com/Microsoft/TypeScript-wiki/issues/35.
