### ISSUE TITLE
`Find References` doesn't find lazy loaded React components

### ISSUE THREAD

**Issue by buondevid** [microsoft/TypeScript#50957]
Does this issue occur when all extensions are disabled?: Yes
Does this issue occur in the Insiders build?: Yes
VS Code Version: 1.71.2
OS Version: MacOS 12.5.1 (MacBook Pro 2019)

**The problem is that Find References doesn't find React components that are lazy loaded**.

Steps to Reproduce:

1. Export a React component.
![Screenshot 2022-09-23 at 09 51 58](https://user-images.githubusercontent.com/36935593/191915937-083a9675-9e07-4a40-95f2-b97a814a5f4c.png)

2. Lazy load it somewhere.
![Screenshot 2022-09-23 at 09 52 06](https://user-images.githubusercontent.com/36935593/191915959-f5d8c9d2-09e2-459f-a22e-bb8813e55ed4.png)

3. Check that VS Code doesn't find any reference for the component.

Not sure if it's a bug or intended behavior (probably intended), but nonetheless it would be nice that finding references would also find lazy-loaded ones. This forces me to always use standard search (with all the downsides of it) to see if I've used the Component somewhere that references can't find.

**Comment by mjbvz** [comment]
Thanks @buondevid 

This is not related to react. Minimal example:

```ts
// a.ts
export default function foo() { }
```

```ts
// other.ts
const a = import('./a');
```

Find all references doesn't pick up the default export referenced through  the import extension

**Comment by laurensmartz** [comment]
I have the same problem in js file.

**Comment by altsanz** [comment]
> Thanks @buondevid
> 
> This is not related to react. Minimal example:
> 
> ```ts
> // a.ts
> export default function foo() { }
> ```
> 
> ```ts
> // other.ts
> const a = import('./a');
> ```
> 
> Find all references doesn't pick up the default export referenced through the import extension

Only if the import has that format. The following is working for me:

```ts
import a from './a';
```

See repro https://stackblitz.com/edit/react-ts-wtgage?file=App.tsx

**Comment by buondevid** [comment]
> Only if the import has that format. The following is working for me:
> 
> ```ts
> import a from './a';
> ```
> 
> See repro https://stackblitz.com/edit/react-ts-wtgage?file=App.tsx

But 
```js
import a from './a';
```
is not a lazy load import, isn'it? The issue is on lazy-load imports so `import()`.

**Comment by RyanCavanaugh** [comment]
`const a = import('./a');` is not a reference to the default export.

**Comment by buondevid** [comment]
Well my own example was with react components, shouldn't VSCode support finding references for lazy loaded ones? @RyanCavanaugh 

I'm gonna test tomorrow if it find references for `a.default` as in @mjbvz example.

**Comment by buondevid** [comment]
@mjbvz hey, they closed the issue here but the problem I opened the ticket for is actually not solved, could we move this back in VSCode? `references` still doesn't find React lazy-loaded components

**Comment by RyanCavanaugh** [comment]
Not really. This is the expected behavior because there's no programmatic way to know that `React.lazy`'s behavior is to unwrap default exports. It's the same as if you had written
```ts
// a.ts
export function foo() { }
export function bar() { }
```
```ts
const p = blah(() => import("./a"));
```
Is the `blah` call a reference to `foo`, `bar`, or neither? Who can say?

**Comment by laurensmartz** [comment]
why close this issue, the problem is not resolved!

**Comment by buondevid** [comment]
@RyanCavanaugh I understand your point: from a JS point of view the `lazy` React abstraction hides away the reference I guess. My ticket was more: is there some VSCode can do to recognize that and start supporting it? Or it's not VSCode duty because it's a React-specific thing?

**Comment by RyanCavanaugh** [comment]
VS Code asks TypeScript for the references, so the discussion best belongs here.

Unless TypeScript starts hardcoding the behavior of various library functions, which isn't something we're keen to do, there's not a feasible way to do this.

**Comment by buondevid** [comment]
> VS Code asks TypeScript for the references, so the discussion best belongs here.
> 
> Unless TypeScript starts hardcoding the behavior of various library functions, which isn't something we're keen to do, there's not a feasible way to do this.

I see, however, I notice that the lazy loaded component knows about the props on the component definition:
![image](https://user-images.githubusercontent.com/36935593/196771997-b2fce0dc-1455-4645-9d26-76d5c9bd253f.png)

So somehow TS knows about the original component definition and their connection (probably through a generic in the React types), but it doesn't enter the references tho... maybe TS could implement a low-level abstraction that Libraries like React could implement to make a step further and say "this is a reference to that function"? Just reasoning out loud 😄

**Comment by qulingyuan** [comment]
This problem has troubled me for a long time

**Comment by micktg** [comment]
> This problem has troubled me for a long time

It makes refactoring so much harder

**Comment by handsomepear** [comment]
Is there any solution?

**Comment by bingDBdu** [comment]
So should it be a cake of Vscode? OR Javascript? OR React?

Maybe we the `React.lazy` should be improved........or abandoned?

**Comment by sanjarcode** [comment]
Found a workaround.
Example
```jsx
// do named export
export const MyComponent = () => <>hello</>;
```

```jsx
// import using `lazily`

import { lazily } from "react-lazily";
const { MyComponent } = lazily( // right click and 'Find all references' on this works
  () => import("path_to_file")
);
```
---
Found by pure accident.
if u're OK with doing this ritualistic named exports for sake of DX.

**Comment by bubablue** [comment]
I just wanted to add that I’ve also run into this limitation, and it really affects developer experience when working with React.lazy or next/dynamic in large codebases — especially during refactoring.

For those still dealing with this, there’s a helpful VS Code extension:
🔗 [Dynamic Import References](https://marketplace.visualstudio.com/items?itemName=bubablue00.dynamic-import-references)
It adds support for finding references to components loaded via React.lazy and next/dynamic, which makes it much easier to track usage across a project.

The extension is open source and could benefit from suggestions or improvements — here’s the GitHub repo:
👉 https://github.com/bubablue/dynamic-import-references

**Comment by mfgabriel92** [comment]
> For those still dealing with this, there’s a helpful VS Code extension: 🔗 [Dynamic Import References](https://marketplace.visualstudio.com/items?itemName=bubablue00.dynamic-import-references) It adds support for finding references to components loaded via React.lazy and next/dynamic, which makes it much easier to track usage across a project.
>
Thank you!

**Comment by elliottAtTreatment** [comment]
I so want to start using this extension, but the publisher is not verified and there are hardly any releases or downloads. The developer doesn't have any established apps or company to speak of either. From a security perspective, we can't just arbitrarily download whatever extensions we want. It's too much of a risk.

PLEASE get verified! And someone get this developer a contract to integrate and maintain this code with Typescript. React isn't exactly a niche use case for it.
