### ISSUE TITLE
Several fields on CompilerOptions are unnecessarily internal

### ISSUE THREAD

**Issue by kwasimensah** [microsoft/TypeScript#50962]
I'm filing this bug because https://github.com/microsoft/TypeScript/pull/50961 asked me to

# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

Several fields in the CompilerOptions type are marked as internal but represent publicly available options.

## Sample Code

CompilerOptions.generateCPUProfile

**Comment by RyanCavanaugh** [comment]
Per offline discussion, this is the intended behavior. `CompilerOptions` is supposed to be the stuff you can usefully pass to `createProgram`; the fields marked `internal` are for `tsc.js` only and aren't useful from a programmatic perspective.
