### ISSUE TITLE
Property setSinkId does not exist on type HTMLAudioElement

### ISSUE THREAD

**Issue by 5r1m** [microsoft/TypeScript#50963]
# Bug Report

HTMLMediaElement supports setSinkId as per the spec. 
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId
- https://www.w3.org/TR/audio-output/#htmlmediaelement-extensions

How ever typescript doesn't support it in type checking as its missing in library:
https://github.com/microsoft/TypeScript/blob/63791f52d4e7a3bf461b974e94abd8cbb6b546c5/lib/lib.dom.d.ts#L7216

### 🕗 Version & Regression Information
Not supported even in latest version

### 💻 Code
const audioObj = new Audio();
audioObj.setSinkId('');

### 🙁 Actual behavior
Property 'setSinkId' does not exist on type 'HTMLAudioElement'.ts(2339)

### 🙂 Expected behavior
No errors expected

**Comment by MartinJohns** [comment]
It lacks browser support.

https://github.com/microsoft/TypeScript-DOM-lib-generator#when-the-type-is-missing

> When the type is missing. 
I> t's possible that the automated algorithm decided that it's not well supported by browsers and thus removed it. Say we want to add a new interface named Foo. Check if there is a document about that interface in MDN. If there is, see the browser compatibility section and check whether it's supported by two or more browser engines. (Note that Chromium-based browsers use the same browser engine and thus support from them counts as a single support.)

**Comment by 5r1m** [comment]
Thank you for your quick reply. Currently I see that its only supported in chromium based browsers (Chrome, Edge and Opera). Its available in Safari TP and in Firefox is enabled by changing pref(with limited support probably?):
https://bugzilla.mozilla.org/show_bug.cgi?id=1498512
