### ISSUE TITLE
Record in circular type alias

### ISSUE THREAD

**Issue by FStefanni** [microsoft/TypeScript#50967]
# Bug Report

### 🔎 Search Terms

circular type alias, record, json

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

In version 4.8.3 it does not compiles.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEDkHkBVQdwPYCcDWBLAdgcwFAFMAPAB2QBdRSBPIvUAKQGcENQBeHUT0AQSSQENKAHkbMAfBy4AfUACU8AY2QATIQ1JJMWADT0mGCV1AyARggQAbPPwyTOMjAFcAtibxI7x0Os3ZPDxwsLAG4cHBBQAHVkdD9CEiRyKho9ZgAmNk9eAWFRDDTDaVAzS2tbIwDXd39vDS0agG8AbSIkBBpEygAuWt8sAF0evLSAXxqnINCgA)

### 💻 Code

```ts
// NOT working
export type Json =
    Array<Json>
    | Record<string, Json>
    | boolean
    | number
    | string
    | null;

// Working
export type Json2 =
    Array<Json2>
    | boolean
    | number
    | string
    | {[property: string]: Json2}
    | null;
```

### 🙁 Actual behavior

Type alias Json does not compile.
This is due to the `Record` type, which if changed into an indexed map start to work.

### 🙂 Expected behavior

I was expecting this to compile, since a Record with `string` as key seems to me as a valid alternative syntax.
Actually, also some linting rules suggest to avoid indexed maps in favor of `Record<string,>`.

But I am not 100% sure this is actually something that should be considered as a bug, or if there is some underlying difference that I do not know.

Regards.

**Comment by MartinJohns** [comment]
Duplicate of #41164.

> I was expecting this to compile, since a Record with `string` as key seems to me as a valid alternative syntax.

Record is a mapped type, whereas the other syntax is an indexed type. It's not an alternative syntax.

**Comment by FStefanni** [comment]
Oh yes, right!
I just added to that, thank you.
Regards.
