### ISSUE TITLE
Use function return type as interface key

### ISSUE THREAD

**Issue by rnarcos** [microsoft/TypeScript#50968]
# Bug Report

### 🔎 Search Terms
"A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.";
"Use function return type as interface key";
"Return unique symbol from function";

### 🕗 Version & Regression Information

- This is the behavior in **4.7.4** and I also observed this behavior on **4.8.2**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBBCuAzRBLAHjAvDA5AIwEMAvHAbgCgoBPABwFMYBBAE2YGUlU0AeABQCc6XGHTRQ6YZhDhR+KMAHMAfFhgADACQBvAUPQBfALTbq9EIjicDaiuUTwwwKCnAwFdKG1nyFAdRRQABYcyOh8gsKi4pLS0HKKSgAUNBHoAFwwulwAlDBa5DAwglDw-GDq2il6aEbaCKE1ajAE0izsVjxZ6EoU+uTkoJCwALZUXvF+AcEdqu6e3or+QSFciTiIICA42aQwAPR7uBsghoQktgd5R5unxDgZcT67ffLi-IgEwAy+IPwA1j4AJJgN4fL55AowADao3GPiW0waAF0HgsFL1+oNoDBRj9-j4APJ4ABWdCcGTxAMUwNBnwY2HyhQARMdbkQmRl8AR+DgADTkPrkS6MGCgYY0eDiZgwFIgej8agwMAEYYMeTNcqvOjvOk4+DYiLamBQEAakRoKoQCAucoAd0CIAgDFMaukBBgABsAtqCB7jbQGL9mrgHCgAI7wBgQKjDPAgD04f30AB0iQAjGmAGwATmy5C1OvBADlwJSgSDtWCGIzoXM4Yspit0GtjtsUTIJhiBuBsaMS2Ay4oiaTyTB+4OFDTK7qGZCoXW0Qim2gW5s25zCDz+fogA)

### 💻 Code

```ts
const suffix = 'baz';
type AddSuffix<Prefix extends string> = `${Prefix}-${typeof suffix}`;

function getStringWithSuffix<Prefix extends string>(prefix: Prefix) {
  return `${prefix}-${suffix}` as AddSuffix<Prefix>;
}

const myStringWithSuffix = getStringWithSuffix('foo'); // 'foo-baz';

// { 'foo-baz': string; }
interface WorkingInterface {
  [myStringWithSuffix]: string;
}

const myWorkingObject: WorkingInterface = {
  "foo-baz": 'bar',
}

// A computed property name in an interface must refer to an expression whose type is a literal type or a 'unique symbol' type.(1169)
interface NonWorkingInterface {
  [getStringWithSuffix('foo')]: string;
}

const myNonWorkingObject: NonWorkingInterface = {
  [getStringWithSuffix('foo')]: 'bar',
}
```

### 🙁 Actual behavior

I'm only able to use the _type-safe_ return type of my `getStringWithSuffix` as the key of my interface(s) if I store this function's return type in a variable and use this variable as the key of my interface(s).

### 🙂 Expected behavior

I'd expect that both `WorkingInterface` and `NonWorkingInterface` would be possible, since the only difference between them, is that I'm creating a variable and using that variable as one of the keys of the `WorkingInterface`, while on the `NonWorkingInterface` I'm passing the function return directly within the `[]`.

**Comment by RyanCavanaugh** [comment]
You can't call functions from a type position. Instead here, you'd need to use a function instantiation expression.

One way to do this is:
```ts
interface NonWorkingInterface extends Record<ReturnType<typeof getStringWithSuffix<'foo'>>, string> {
}

// Demo - it does work
declare const nwi: NonWorkingInterface;
const m:string = nwi['foo-baz'];
```

**Comment by rnarcos** [comment]
Hi, @RyanCavanaugh. Thank you for the fast reply!

I do understand the
> You can't call functions from a type position
of your comment, but I can't seem to wrap my head around to why

```ts
interface PossibleAlternativeInterface {
  [AddSuffix<'foo'>]: string;
}
```

wouldn't be valid.

Regarding your suggestion: while
```ts
interface NonWorkingInterface extends Record<ReturnType<typeof getStringWithSuffix<'foo'>>, string> {
}
```

does work, it becomes cumbersome if I have to do this for more than 1 dynamically-keyed interfaces, especially when nesting are in place. Consider the following example:

```ts
interface DeeplyNested {
  foo: {
    baz: string;
    bar: string;
  } & Record<ReturnType<typeof getStringWithSuffix<'foo'>>, string>;
  bar: {
    baz: Record<ReturnType<typeof getStringWithSuffix<'foo'>>, string> & Record<ReturnType<typeof getStringWithSuffix<'bar'>>, string>
  }
}
```

Also, perhaps the error output could be more tailored to the mis-usage of function calls within the type declaration?

**Comment by RyanCavanaugh** [comment]
> [...] wouldn't be valid.

Computed property names always refer to values
