### ISSUE TITLE
Why can't we use the toLowerCase() and toUpperCase() string methods to solve the Lowercase and Uppercase utilities?

### ISSUE THREAD

**Issue by YadBro** [microsoft/TypeScript#50970]
# Bug Report
### 🕗 Version & Regression Information
- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIBUD2ATTyDeAUMicomMAG7BgCeAXMgDKYDu0CcAzhADxdgooAOYA+ADTFS2CFwRCADhUwhGAVQUKO3PgKEgxkgL6FCCFQORgcmRhhvIAvASklyVGg2QByAGLAuAAsRbwA6axZ2KABhHQAKAEpJUmQZOUVlVR9-IJFkVhpA5FpMAFcoZABbTEqw6w0tGPikwhNzEC5MABsIUK7MYTjrXASAbiA)

### 💻 Code

```ts
interface ITodo {
    activity: Lowercase<string>, // (Error) Type 'string' is not assignable to type 'Lowercase<string>'.
    description: Uppercase<string>, // (Error) Type 'string' is not assignable to type 'Uppercase<string>'.
}

const todo: ITodo = {
    activity: 'Fishing'.toLowerCase(),
    description: 'Fishing with your mom'.toUpperCase(),
}
console.log(todo);
```

**Comment by MartinJohns** [comment]
Because both `toLowerCase()` and `toUpperCase()` return a `string`, not `Lowercase<string>` or `Uppercase<string>`. Changing this would be a breaking change. The issue for this is still open: #44268

**Comment by YadBro** [comment]
I'm still confused, I think it should work. Well don't think about it. Thanks for the explanation. I will close this issue thank you.

**Comment by fatcerberus** [comment]
> I'm still confused, I think it should work.

`.toLowerCase()` is just another method that returns a `string`, like any other; the compiler doesn’t have any context to know this particular string is compatible with `Lowercase<string>`.

**Comment by wbt** [comment]
Another example use case is in https://github.com/microsoft/TypeScript/issues/50548#issuecomment-1329586849 where even what is supposed to be a highly simplified example still requires a casting function:

```ts
//Bonus issue(#44268): the cast in the return statement of the next line should be automatic & unnecessary:
const toUpperCaseTyped = function<S extends string>(strIn: S) {return strIn.toUpperCase() as Uppercase<S>;};
```
