### ISSUE TITLE
Can I package my dependencies typings in a way that snapshots the version?

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#5097]
I'm using the new 1.6 module loading for typings from https://github.com/Microsoft/TypeScript/issues/2338

I distribute my library with NPM and clients pick up the typings for my code magically from the path indicated by the "typings" field in the `package.json`. So great! The version of the typings will always match the version of the runtime code.

But, one of my files might try to import from a namespace like 'es6-collections'. What version will I pick up, and from where? There is no "typings" in https://github.com/WebReflection/es6-collections/blob/master/package.json so I will have to have this file presented to the compiler from the command line, or in the 'files' of my user's tsconfig.json, or a tripleslash ref in the user's code.

That means I can tell users to `npm install` my package, but then all my dependencies leak out when I tell them "now you need to `tsd install es6-collections/es6-collections.correct-version.d.ts`" and that is not so nice.

Is there already a way to do without that extra step? I could re-distribute the `es6-collections-correct-version.d.ts` in my NPM package but I don't see a way to depend on it.

**Comment by alexeagle** [comment]
From discussion with @rkirov

**Comment by weswigham** [comment]
#4913 - The package scope proposal - would loosen current restrictions and allow you to redistribute the types you require inside your package.

**Comment by alexeagle** [comment]
Cool, I hope we can get a solution for that, it's the biggest remaining issue with our new quickstart.
I have a working demo, see https://github.com/alexeagle/angular2-distro/blob/master/README.md

**Comment by xogeny** [comment]
This was closed, but what was the resolution?

**Comment by kitsonk** [comment]
#4913 #5269 #4166 and #5537 it was mentioned in #5657 that there is further movement.  I think the issue is so spread out that it was an effort to consolidate it.  #5537 is likely to be the central ticket that solves this meta problem.
