### ISSUE TITLE
Infer value types when indexing by generic key

### ISSUE THREAD

**Issue by jlachniet** [microsoft/TypeScript#50986]
# Suggestion

Consider the following code:

```ts
interface User {
    name: string;
    age: number;
}

function updateUser<K extends keyof User>(user: User, key: K, value: User[K]) {
    user[key] = value;

    if (key === 'age') {
        console.log(`You will be ${value + 1} next year.`)
    }
}
```

This code is functional at runtime, but an error occurs during compilation on line 10. The TypeScript compiler does not know the type of `value`, even though it can only be `number` due to the narrowing on the previous line. If the key is narrowed to `"age"`, then `User[K]` is really `User["age"]` which is `number`.

I suggest that this type of narrowing be possible to infer the value of the index.

## 🔍 Search Terms

N/A

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Infer these types at compile time.

## 📃 Motivating Example

The user example given above is similar to a function I have in my own code which updates user settings. The reason I update the object in such a way is because I need to run additional code based on how the settings are updated.

## 💻 Use Cases

Right now, it is necessary to manually cast this type of use, for example `value as number`.

**Comment by RyanCavanaugh** [comment]
> even though it can only be number due to the narrowing on the previous line

This isn't a correct assumption.
```ts
updateUser<keyof User>({ name: "me", age: 100}, "name", "bob");
```

**Comment by nopeless** [comment]
> > even though it can only be number due to the narrowing on the previous line
> 
> This isn't a correct assumption.
> 
> ```ts
> updateUser<keyof User>({ name: "me", age: 100}, "name", "bob");
> ```

Can you elaborate? I think it is a correct assumption

**Comment by RyanCavanaugh** [comment]
Yep, I messed up that example. I meant to write
```ts
updateUser<keyof User>({ name: "me", age: 100}, "age", "bob");
```

**Comment by fatcerberus** [comment]
This is a common mistake.  `extends keyof` can be a union of multiple keys, or even all of them - you’d need https://github.com/microsoft/TypeScript/issues/27808 to make this pattern typesafe.
