### ISSUE TITLE
File import ignored if the file containing the import statement doesn't explicitely reference a class deifined in the file

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [Microsoft/TypeScript#5098]
Class `MyClass` is defined in `my-class.ts`. The class is decorated with a custom decorator. The result of the decorator is some logic that will eventually cause `MyClass` to be instantiated.

Another file, `other-file.ts`, imports `my-class.ts` with:
```Javascript
import 'my-class';
```
`other-file.ts` has no explicit reference to `MyClass`, as it will automatically be instantiated and used as needed as a result of its decorator.

This works fine, until I try to import an interface, exported by `my-class.ts`

If I change the import within `other-file.ts` to:
```Javascript
import {ISomeInterface} from 'my-class'`;
```
 I can now reference `ISomeInterface` within `other-file.ts`, but now the contents of `my-class.ts` is never actually compiled.

I suspect this is due to some optimization by the Typescript compiler. In general it would make sense that if nothing but interfaces were referenced from a class, there's no reason to generate javascript for it; however, the use of decorators makes that assumption erroneous.

**Comment by mhegazy** [comment]
@SpenceDiNicolantonio can you provide more data, i can not get this to reproduce locally:

```ts
import {B} from "./module2";

export function decorate(c:any): void{
    // use the metadata from import B
}

@decorate
export class C {
    constructor(a: B) {
    }
}
```

> tsc module.ts --experimentalDecorators --emitDecoratorMetadata --m commonjs --t es5

```js
var module2_1 = require("./module2");

function decorate(c) {
    // use the metadata from import B
}
exports.decorate = decorate;
var C = (function () {
    function C(a) {
    }
    C = __decorate([
        decorate, 
        __metadata('design:paramtypes', [module2_1.B])
    ], C);
    return C;
})();
exports.C = C;
```

**Comment by mhegazy** [comment]
And to answer your question, the compiler will elide imports that are only used in a type position. see @danquirk's answer in https://github.com/Microsoft/TypeScript/issues/4717#issuecomment-139057640 for more information. if any of these imports are used by a decorator, the import will not be elided.

**Comment by mhegazy** [comment]
please reopen if https://github.com/Microsoft/TypeScript/issues/5098#issuecomment-145637425 does not answer the original question.
