### ISSUE TITLE
[Proposal] Typescript Overriding Type

### ISSUE THREAD

**Issue by mikoloism** [microsoft/TypeScript#50989]
# Typescript Overriding the Type

## 🔍 Search Terms

- typescript utility type override

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Sometimes we need to `override` the some property in same interface with another type; :wink: 

## 📃 Motivating Example

[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gbhAToglgEwgHgFAEgAqANHgNJQQAewEAdmgM5QAKAhosCiwDaYDeUAbSZQUNKAGsIIAPYAzKPgC6ALigsaIKAF8AfFAA+UesFQ0A5sT0BeKGUrU6jY6bN4A-LAC2KYJiK29ADIofiERMUkZeSVVfCFFAygAVxpxGmkAdzEtPFUYb19-SLkAqGCSAG5sbFFqRFkWAGNoAEkAVXokELwkzsQaFk8IVWdRMyqcmpo6huaoFoBRTzAuaRAIaHtaBlgEZHQsdr7CKAByXqQBodO9Xh6+q+HBDDA2YCHpkZMxk8bpDFUNCSngARkhFFVcMAWPRxPRVABBZAsECYdQgHQTaqgSDzADCvWA0iGiCgNngSFQGEwRyQJ34F36gyeQNBXV0VQA9AAqbBQTmcqDSRB8gAG4r5tSQs1aBOMxK6FP21NpiHpyQezMBwLBpN0IS0VSg4tF1X5guFYol4RmTVlhIVpKVVMOHTpZ0ZjxuIQ1ly1UFZuu0RpNfO5nOqAt9AFpGjCINg-jRjORlqt1hB4fMlis1hsyd1cJ7-QJTujo6NzKcTgBGABMAGYACyKYhQmFw1QCVvYQ2RwUXWPxxPSZPAKCNB0krMtOVEkkFu5FzVDVT15vEPtAA)

## 💻 Use Cases
We can have this type alias as Type Tools :

``` typescript
type Override<
	T,
	K extends Partial<{ [P in keyof T]: any }> | string,
> = K extends string
	? Omit<T, K> & { [P in keyof T]: T[P] | unknown }
	: Omit<T, keyof K> & K;
```

And, We have an interface alike below :

``` typescript
interface IUser {
    username: string;
    phone: string;
    // any else properties
}
```

Then, We need the same interface with some another type for `username` property

``` typescript
interface IEmployee extends IUser {
    username: [department: string, code: number]; // -> error
    tasks: Array<any>;
}
```

But If we use the `Override` type?

``` typescript
interface IEmployee extends Override<IUser, 'username'> {
    username: [department: string, code: number]; // -> work
    tasks: Array<any>;
}
```

Or This Syntax :

``` typescript
interface IEmplyee extends Override<IUser, { username: [department: string, code: number]; }> {
    tasks: Array<any>;
}
```

Or we have an `ICustomer` interface with same properties with `IUser` but for `username` property that should be given the `number` as the type

``` typescript
type ICustomer = Override<IUser, { username: number }>;
```

Also We can use alike below syntax :

``` typescript
interface ICustomer Override<IUser, { username: number }> {};
```

Work with Type Assignment :

``` typescript
// use-case
const employees: IEmployee = {
	username: ['any-string', 1234],
	tasks: [],
    phone: '09123456789'
};

// use-case
const customers: ICustomer = {
	username: 1234,
    phone: '09123456789'
};
```

Or any another example for this `Overidde` Utility Type, Thanks

### Exactly this is just a Concept and with Week Example (take it easy :wink:)

**Comment by fatcerberus** [comment]
You can already do `extends Omit<T, 'prop'>` so this type alias seems unnecessarily complicated (it has to do more than the bare minimum to even be useful as there's already a thing built-in that does its main job).

**Comment by mikoloism** [comment]
> You can already do `extends Omit<T, 'prop'>` so this type alias seems unnecessarily complicated (it has to do more than the bare minimum to even be useful as there's already a thing built-in that does its main job).

Yes Exactly but not for accept interface as generic type to overriding, `omit` just accept the `key` of interface` but this `Override` Type give `key` and `interface` also :wink:

**Comment by mikoloism** [comment]
> This will be declined, since it's only for developer convenience, and [not](https://github.com/microsoft/TypeScript/issues/49564#issuecomment-1156854960) needed [by](https://github.com/microsoft/TypeScript/issues/48697#issuecomment-1100261493) the [compiler](https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388) to [emit](https://github.com/microsoft/TypeScript/issues/50838#issuecomment-1250406557) .d.ts [files](https://github.com/microsoft/TypeScript/issues/49060#issuecomment-1123463050).

Hi @jcalz :wave:

Exactly :

### Any fool can write code that a computer can understand. Good programmers write code that humans can understand

**Comment by jedwards1211** [comment]
@DanielRosenwasser

> or intersecting with a new property

Intersecting with a new property doesn't work the way `interface`/`extends` does though... For example

```ts
// this type came from a library, I need to replace foo: any
type A = {
  foo: any
}

type B = A & { foo: number }

type T = B['foo'] // I need this to be number, but it's still any
```

`interface`/`extends` does get the desired behavior, but...if something is easier to do with `interface`s, I wish TS would engineer a way to do it just as easily with type literals.  Type literals are just way more convenient because they can be used inline.  For example, let's say I have

```ts
type Props = {
  b: A
}
```

And I want to constrain the type of `foo.b` to be `number`.  Do I want to break out a separate interface declaration just to do that?  No, that would be a hassle.  I would just:
```ts
type Props = {
  b: Omit<A, 'foo'> & { foo: number },
}
```

As such when there's more than one property to override, the `Omit` pattern becomes a pain because of the duplicated property names, and I find myself thinking I should declare an `Override` type that does what OP proposes.  But then, I think, this should really just be a builtin.

**Comment by mikoloism** [comment]
what if it's be a reusable keyword? :thinking: 

```typescript
// basic
interface One {
	property: number;
}

// replace
interface Two extends One {
	override property: string ;
}

// union mode
interface Three extends One {
	extends property: string;
}

// cases
assertTypeEqual<One, { property: number }>;
assertTypeEqual<Two, { property: string }>;
assertTypeEqual<Three, { property: number | string }>;
```
