### ISSUE TITLE
assertCompilerOptions

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#50980]
# Suggestion

## 🔍 Search Terms

- `compilerOptions`
- `assert`
- `exactOptionalPropertyTypes`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

```ts
assertCompilerOptions exactOptionalPropertyTypes
```

## 📃 Motivating Example

library.ts
```typescript
interface UserDefaults {
  // The absence of a value represents 'system'
  colorThemeOverride?: "dark" | "light";
}
```

app.ts
```typescript
const settings = getUserSettings();
settings.colorThemeOverride = "dark";
settings.colorThemeOverride = "light";
 
// pass when falsy exactOptionalPropertyTypes
// repoerted when truthy exactOptionalPropertyTypes 
settings.colorThemeOverride = undefined;
```
The library cannot control related linting.

## 💻 Use Cases

library.ts
```typescript
assertCompilerOptions exactOptionalPropertyTypes

interface UserDefaults {
  // The absence of a value represents 'system'
  colorThemeOverride?: "dark" | "light";
}
```

### When `exactOptionalPropertyTypes` is falsy

`app.ts` import `library.ts`
- `library.ts` line `assertCompilerOptions exactOptionalPropertyTypes` will be reported
- Or `app.ts` line `import library` will be reported

### When `exactOptionalPropertyTypes` is truthy
app.ts
```typescript
const settings = getUserSettings();
settings.colorThemeOverride = "dark";
settings.colorThemeOverride = "light";
 
// @ts-expect-error: exactOptionalPropertyTypes
settings.colorThemeOverride = undefined;
```

**Comment by loynoir** [comment]
```ts
function hanlder(x: { [K in string]: 42 }) {
  return x;
}

const y: { a: 42; b?: 42 } = { a: 42, b: undefined };
hanlder(y);
```

This assignment chain
- can be prevented by `exactOptionalPropertyTypes`  at line `const y: { a: 42; b?: 42 } = { a: 42, b: undefined };`.
- I'm also appreciated for any other suggestion cans prevent this assignment chain at line `hanlder(y)` , in another words, prevent assign ` { a: 42; b?: 42 }` to ` { [K in string]: 42 })`

**Comment by RyanCavanaugh** [comment]
We actively don't want this feature. It is not up to library authors to determine whether or not a consumer's compiler options are good enough.
