### ISSUE TITLE
"Disconnect" action missing its icon when accessed from menu

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/TypeScript#50982]
# Bug Report

(In VSCode php-debug, for example) the "Disconnect" action accessed through menu on the "stop" button is missing its icon.

### 🕗 Version & Regression Information

Version: 1.71.2 (system setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

- This is the behavior in every version I tried, where functionality is present.

### 🙁 Actual behavior

![https://user-images.githubusercontent.com/6532485/192517264-14ae565a-1d8e-451d-b322-92bd07f65d51.png](https://user-images.githubusercontent.com/6532485/192517264-14ae565a-1d8e-451d-b322-92bd07f65d51.png)

### 🙂 Expected behavior

I would actually expect seeing the same icon I see when holding down Alt over the button.

See xdebug/vscode-php-debug#841

**Comment by MartinJohns** [comment]
How is this TypeScript related?

**Comment by RyanCavanaugh** [comment]
This is a VS Code issue; you'll need to file it there.
