### ISSUE TITLE
transitive assignment

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#50981]
# Bug Report

### 🔎 Search Terms

- `optional property`
- `exactOptionalPropertyTypes`
- `omit property`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code
```json
"exactOptionalPropertyTypes": false
```

```ts
function hanlder(x: { [K in string]: 42 }) {
  return x;
}

const y: { a: 42; b?: 42 } = { a: 42, b: undefined };

// @ts-expect-error
hanlder({ a: 42, b: undefined });
hanlder(y);
```

### 🙁 Actual behavior

```ts
// @ts-expect-error
hanlder({ a: 42, b: undefined });
// no error
hanlder(y);
```

### 🙂 Expected behavior

```ts
// @ts-expect-error
hanlder({ a: 42, b: undefined });
// @ts-expect-error
hanlder(y);
```

When `"exactOptionalPropertyTypes": false`
- `{ a: 42; b?: 42 }` should not assignable to `{ [K in string]: 42 }`.
- but `{a: 42} | {a:42, b:42}` can

**Comment by loynoir** [comment]
### Additional
When
```json
"exactOptionalPropertyTypes": false
```

In another word, given
- A is `{ a: 42, b: undefined }`
- B is `{ a: 42; b?: 42 }` 
- C is `{ [K in string]: 42 }`

From
```ts
// @ts-expect-error
hanlder({ a: 42, b: undefined });
```
We know that, `A` is not assignable to `C`.

From
```ts
// no error
const y: { a: 42; b?: 42 } = { a: 42, b: undefined };
// no error
hanlder(y);
````
We know that `A` is assignable to `B`, and `B` is assignable to `C`.

In conclusion
- `A` is assignable to `B`, and `B` is assignable to `C`.
- `A` is not assignable to `C`

Thus, I think it's a bug, or bad design.

**Comment by RyanCavanaugh** [comment]
Assignability has never been fully transitive; that isn't a design goal.

> Thus, I think it's a bug, or bad design.

`exactOptionalPropertyTypes` is for enabling the desired behavior, yet you've turned it off. If you set your phone to silent and it doesn't make a noise when you get a call, that's not a bug.

**Comment by whzx5byb** [comment]
Note that the optional property itself is NEVER sound, no matter if you turn on `exactOptionalPropertyTypes` or not.

```ts
declare var a: { a: 42, b: string };
declare var b: { a: 42 };
declare var c: { a: 42, b?: 42 };

b = a; // OK. a is assignable to b.
c = b; // OK. b is assignable to c.
c = a; // Error. a is not assignable to c.
```

The only way i can think of is to prevent `{ a: 42 }` from being assignable to `{ a: 42, b?: 42 }`, and only allow an exact type `{| a: 42 |}` to be assignable to `{ a: 42, b?: 42 }`, which would need https://github.com/microsoft/TypeScript/issues/12936 to be implemented first.

**Comment by loynoir** [comment]
> Assignability has never been fully transitive; that isn't a design goal.
> 
> > Thus, I think it's a bug, or bad design.
> 
> `exactOptionalPropertyTypes` is for enabling the desired behavior, yet you've turned it off. If you set your phone to silent and it doesn't make a noise when you get a call, that's not a bug.

1. This phone default setting is silence. I did not turn it off, `exactOptionalPropertyTypes` default to false.
2. If  chain `A -> C` is wrong, would be nice to see **ZERO** chain `A -> B -> C` is OK, if possible.

**Comment by nopeless** [comment]
@loynoir I feel like you have two issues here

1. About transitivity

You could argue that `{}` acts like a `any`, and you would be right

```ts
const target: { a: 42 } = { a: '42' } as {} as { a: 42 };
```

But I don't think this is incorrect behavior.

2. About optional properties

An object of type `{ a?: 42 }` always have `42` as property values. If `a` exists, then it is `42`. If `a` does not exist, then there are no property values. This is different from `{ a: undefined }`
