### ISSUE TITLE
Type information incorrectly infered in certain scenarios with typescript >= 4.8

### ISSUE THREAD

**Issue by c4spar** [microsoft/TypeScript#50995]
# Bug Report

Since typescript version 4.8 i get some strange type errors in one of my projects. It seams that type informations are not correctly inferred in certain scenarios.

### 🕗 Version & Regression Information

- The below example is working with typescript <= 4.7.4
- And it is not working with typescript >= 4.8

### ⏯ Playground Link

* [Playground](https://www.typescriptlang.org/dev/bug-workbench/?#code/IYIwzgLgTsDGEAJYBthjAgQmgpgFQE8AHHAHjwD4EBvAKAQQHpGEBJAMwQEsEocBbAPYA3HAggALMaEgx4CfjkmCAJghU4UwGBC6CAdt0QB3QVADWGYMjCDuhiMRxhYULkUQUAvAgAsAOgAOf3oEIgBXEGQuWAQZaDhEIm0wHAAKAEoALgQ8AG5aAF9aWi10BABZAkIScgQcAA8IHH0VDFkufQBzBAAfBH1w-hAcKD6EEEFBZBxgfSpG5taMbFSaskoaUNgDWXD4MzSiN2FgZoRT5HDnHIBBKBgCcgoMrYYGMHCSKEyChmLQhEojEwil0tlcm93nwIOEoA4JFwwP5LtcwABtAAMAF0-ghigDmGxENZbAhTBYMJ1xE4XG4PAhvH4gtxODw+EJROIpPUmi02ghIGcBC0ILQiexwvp4HoHE5nmlHCQcngIXgtpLpboDDTaurFvyVrh1qQpeZ9IJjPMKIqnCq1VCYXC5SQCgCdvpIEhpmYED59DhjJVqk40uiAER8FThgA0CHDUWu4exGQKHq9O2QZgAjH7delM2ZUyUiXgeUqxIJOAADQtQABM1e4VOlZj48jAnVgYgrdPcnh8AWCpV2iDr9bzFbSAaDVXWYcjOGjcYTVxwyYyxaAA)

### 💻 Code

```ts
abstract class BaseType<T> {
  // If i remove the abstract method declaration it works also in typescript >= 4.8.
  public abstract parse(): T;
}

class MyType<T extends string | number | boolean> extends BaseType<T> {
  constructor(private values: Array<T>) {
    super();
  }

  public parse(): T {
    return this.values[0];
  }
}

// It also works in typescript >= 4.8 if i remove the extends statement
// function type<T>(type: T): T {
function type<T extends BaseType<unknown>>(type: T): T {
  return type;
}

const color = new MyType(["red", "blue"]);
const color1 = type(color);

// The type of `color2` is incorrect since typescript >= 4.8.
const color2 = type(new MyType(["red", "blue"]));
```

### 🙁 Actual behavior

- Type of `color1`: `MyType<"red" | "blue">`
- Type of `color2`: `MyType<string>`

The type of `color2` is wrong. It should be the same as `color1`. The only difference to `color1` is that the type is not assigned to a variable beforehand.

### 🙂 Expected behavior

- Type of `color1`: `MyType<"red" | "blue">`
- Type of `color2`: `MyType<"red" | "blue">`

**Comment by nopeless** [comment]
This is working as intended

The `type<T extends BaseType<unknown>>(type: T)` is casting the inner part to a `MyType<string>`. I'm pretty sure the `satisfies` operator deals with this exact issue.

Unfortunately I can't get the satisfies operator to work in dev atm

**Comment by RyanCavanaugh** [comment]
Being not as precise as expected isn't the same as wrong. `string` is a valid inference here and inference is free to choose from among valid inferences.

Adding the constraint of the contextual type to the candidate list, as occurred here, was needed to make other scenarios not outright fail.

As hinted to, you can use `satisfies` to safely remove the outer contextual type from the inference process:
```ts
const color2 = type(new MyType(["red", "blue"]) satisfies unknown);
```
