### ISSUE TITLE
JavaScript: when redefining builtin APIs, type resolution & autocomplete do not work as expected (a major issue for JavaScript runtime writers)

### ISSUE THREAD

**Issue by ytxmobile98** [microsoft/TypeScript#50992]
```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-47-generic
Sandboxed: No
```

My company is currently implementing a JavaScript runtime that is used internally by various departments, which includes WHATWG APIs and some internal APIs for the company. Implementing array buffers, web streams, etc., are part of this big project.

I am currently doing the work of implementing the `ReadableStreams`, `WritableStreams`, and `TransformStreams` APIs. **When I write the code in VSCode, I noticed that even I have defined `class ReadableStreams`, `class WritableStreams`, `class TransformStreams`, etc., VSCode is only able to recognize the symbols given by the *builtin* `*.d.ts` files, rather than recognizing my implementation details and show them up in tooltips & autocomplete accordingly.**

For instance, consider the following code (I am here providing some simplistic code to illustrate the problem & maintain confidentiality of my actual code):
```js
'use strict';

const kDetached = Symbol('[[detached]]');
const kReadRequests = Symbol('[[readRequests]]');

// 1. ReadableStream class
// What goes wrong: `isDetached()` call is not recognized as in `stream.isDetached()`

class ReadableStream {
    /** @type { boolean } */
    [kDetached] = false;

    isDetached() {
        return this[kDetached];
    }
}

const stream = new ReadableStream(1);
const detached = stream.isDetached();
console.info(detached); // false

// 2. ReadableStreamDefaultReader class
// What goes wrong: `defaultReader[kReadRequests]` is not recognized as an array when accessed outside

/**
 * https://streams.spec.whatwg.org/#read-request
 * @typedef {{
 *   chunk: (chunk: any) => void,
 *   close: () => void,
 *   error: (error: any) => void;
 * }} ReadRequest
 */

class ReadableStreamDefaultReader {
    /** @type { ReadRequest[] } */
    [kReadRequests] = [];

    get length() {
        return this[kReadRequests].length;
    }
}

let defaultReader = new ReadableStreamDefaultReader();
let defaultReadRequests = defaultReader[kReadRequests];
console.log(defaultReader.length); // 0
console.log(defaultReadRequests.length); // 0

// 3. Reader class (not in standard, used as contrasting example)
// This goes alright

class Reader {
    /** @type { ReadRequest[] } */
    [kReadRequests] = [];

    get length() {
        return this[kReadRequests].length;
    }
}

const reader = new Reader();
const readRequests = reader[kReadRequests];
console.log(reader.length); // 0
console.log(readRequests.length); // 0
```

This is perfectly valid code. The output is:
```txt
false
0
0
0
0
```

**Here are the problems:**

## 1. Resolving references

Whenever I define a class that has the same name as a class defined by WHATWG specs, VSCode only recognizes the standard API, but not the class I have defined, *even though it is in the same file*. (Recall that my work is to implement these API for my company, so this problem is really a big trouble for me)

Using **Find all references**, I have got:
* `ReadableStream`: the definition itself and no references. (Should have 1 reference)
    ![Screenshot from 2022-09-29 16-15-49](https://user-images.githubusercontent.com/5900105/192979376-693fbb00-dac7-42e6-b3e8-8dc295d4055a.png)
* `ReadableStreamDefaultReader`: the definition itself and also no references. (Should have 1 reference)
    ![Screenshot from 2022-09-29 16-16-09](https://user-images.githubusercontent.com/5900105/192979409-0a932fe7-f084-4ecc-969e-85c46fba7f3f.png)
* `Reader`: the definition itself and 1 reference. This one works because it is not a WHATWG-defined class.
    ![Screenshot from 2022-09-29 16-16-19](https://user-images.githubusercontent.com/5900105/192979427-a57c9d39-c521-423b-8ead-da4414ddb62f.png)

## 2. Type hinting tooltips

It looks fine when I mouse over the methods *inside* the classes. But once I reference them outside, everything about types goes wrong.

* What I got when moving my mouse over the methods inside the classes: **everything is in its correct type.**
    ![Screenshot from 2022-09-29 15-53-11](https://user-images.githubusercontent.com/5900105/192974024-0e71cf47-0c83-48ae-943b-4d45c095d0dc.png)

    ![Screenshot from 2022-09-29 15-53-24](https://user-images.githubusercontent.com/5900105/192973533-22b79ff2-e3e3-4033-871f-2a6ac02759d9.png)

    ![Screenshot from 2022-09-29 15-53-34](https://user-images.githubusercontent.com/5900105/192974222-a4964e33-a493-468b-bdd5-6bf862b15149.png)

* What I got instead when referencing them outside the class:
    * **VSCode treats the methods from `ReadableStream` and `ReadableStreamDefaultReader` classes as `any` type, and so are the returned values.**
    * **For the third class `Reader`, since it is not a builtin API, everything is resolved into the correct type.**

    ![Screenshot from 2022-09-29 15-59-42](https://user-images.githubusercontent.com/5900105/192975329-94856980-71b8-4ca5-aee5-bf7a52ee1a9a.png)

    ![Screenshot from 2022-09-29 15-59-57](https://user-images.githubusercontent.com/5900105/192975364-6e60d0cf-d651-4b0f-abb0-60b89c8d9358.png)

    ![Screenshot from 2022-09-29 16-00-05](https://user-images.githubusercontent.com/5900105/192975413-6c214f62-b560-4872-8f86-d903bde215b5.png)

## 3. Autocomplete

The problems I mentioned above also cause autocomplete to go wrong.

* For the `ReadableStream` and `ReadableStreamDefaultReader` class I have defined, it still shows the standard methods for the instances.
    ![Screenshot from 2022-09-29 16-30-36](https://user-images.githubusercontent.com/5900105/192981745-a85d0ac1-c747-4657-83ad-e566864253c4.png)
    ![Screenshot from 2022-09-29 16-05-37](https://user-images.githubusercontent.com/5900105/192977421-d746e4e6-3ecd-4c90-b5d8-2436d5edd1e7.png)
* For the `Reader` class, it shows the correct autocomplete.
   ![Screenshot from 2022-09-29 16-05-50](https://user-images.githubusercontent.com/5900105/192977606-88f0e551-aceb-4253-a3f1-25ee10c19cea.png)

This is really an irritating experience for me when I try to implement these APIs and debug them. I look forward to see these bugs fixed as soon as possible.

**Comment by DanielRosenwasser** [comment]
JavaScript editing in VS Code is powered by TypeScript. To make most projects work well out-of-the-box, we have VS Code configured to send some default options, and the default options include the `dom` libraries which contains conflicting declarations of everything you're defining. The language service always prefers the declarations in `lib.dom.d.ts` over others.

The best way to get around this is to introduce a `jsconfig.json` to configure these options.

```json5
{
    "compilerOptions": {
        "target": "esnext",
        "lib": ["esnext"],
    },
    "include": [
        "src/**/*.js"
    ]
}
```

The `lib` option here doesn't include the DOM libraries.

Note that if you had a `// @ts-check` comment at the top of your file, or you used `"checkJs": true`, you'd get an error about duplicate declarations.

![image](https://user-images.githubusercontent.com/972891/193122066-d45fba60-aa22-4692-881a-f724153786d3.png)

**Comment by ytxmobile98** [comment]
> JavaScript editing in VS Code is powered by TypeScript. To make most projects work well out-of-the-box, we have VS Code configured to send some default options, and the default options include the DOM libraries which contains conflicting declarations of everything you're defining. The language service always prefers the declarations in `lib.dom.d.ts` over others.
> 
> The best way to get around this is to introduce a `jsconfig.json` to configure these options. It might look something like the following:
> 
> ```js
> {
>     "compilerOptions": {
>         "target": "esnext",
>         "lib": ["esnext"],
>     },
>     "include": [
>         "src/**/*.js"
>     ]
> }
> ```
> 
> The `lib` option here doesn't include the DOM libraries.
> 
> Note that if prior to adding the `jsconfig.json`, if you had a `// @ts-check` comment at the top of your file, or you used `"checkJs": true`, you'd get an error about duplicate declarations.
> 
> ![image](https://user-images.githubusercontent.com/972891/193122066-d45fba60-aa22-4692-881a-f724153786d3.png)
> 
> This can be extremely useful (and is probably very important) as you're trying to provide a good editing experience for many other users. If that's your goal, checking your JavaScript would be advisable.

Hi,

I have created the config you have given in the same directory as my sample code.

However, when I went back to my company code base, it still does not work.

In the company code base I have written
```json
{
  "compilerOptions": {
    // ...
    "lib": ["ES2020"],
    // ...
  }
  // ...
}
```
and then the builtin items I have redefined are resolved to `any`.

![Q4qVjJPw8N](https://user-images.githubusercontent.com/5900105/193194044-eecc7db4-fd6f-4a3e-a69a-52515b0c755b.png)

I have checked that this is because in other files in the code base, we previously used a `builtIn` function to import the declarations. The `builtIn` function is a function that we have implemented by ourselves (with C++ binding) to locate the exact identifier and import it, so that the functions and classes can be used across various files.

```js
// readable_stream.js
class ReadableStream {
  // ...
}

// module_a.js
const { ReadableStream } = builtIn('path/to/readable_stream.js');

// module_b.js
const { ReadableStream } = builtIn('path/to/readable_stream.js');

// ...
```

And in .eslintrc file we have this config to make `builtIn` available across all of our JavaScript files: 
```json
"globals": {
  "builtIn": "readonly",
  "primordials": "readonly",
  "EventListener": true
  // ...
},
```

Because of this setup, VSCode is unable to resolve the references `ReadableStream`, `ReadableStreamDefaultReader`, etc. which we have defined in our code.

Any suggestions or solutions for this?
