### ISSUE TITLE
FnChain

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#50991]
# Suggestion

## 🔍 Search Terms

- `strict Parameters<T>`
- `associated ReturnType<T>`
- `curry function`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Given
```typescript
type MP2 = {
  a1: "a2";
  b1: "b2";
};
type MP3 = {
  a1: "a3";
  b1: "b3";
};
type MR = {
  a1: "ar";
  b1: "br";
};
function foo<K extends keyof MP2>(p1: K, p2: MP2[K], p3: MP3[K]): MR[K] {
  return { p1, p2, p3 } as any;
}
```

```typescript
type FooFnChain = FnChain<typeof foo>;

type FooFnChainExpected =
  | { params: ["a1", "a2", "a3"]; result: "ar" }
  | { params: ["b1", "b2", "b3"]; result: "br" };
```

## 📃 Motivating Example

```typescript
// [p1: keyof MP2, p2: "a2" | "b2", p3: "a3" | "b3"]
type FooParameters = Parameters<typeof foo>;
// "ar" | "br"
type FooReturn = ReturnType<typeof foo>;

// @ts-expect-error
foo('a1','b2','b3')

// no error
const a:FooParameters = ['a1', 'b2', 'b3']
void a

// no error
curry(foo)('a1')('b2')('b3')

// "ar" | "br"
const r = curry(foo)('a1')('a2')('a3')
```

## 💻 Use Cases

```typescript
// @ts-expect-error
foo('a1','b2','b3')

// @ts-expect-error
const a:FnChain<typeof foo>['params'] = ['a1', 'b2', 'b3']
void a

// @ts-expect-error
curry(foo)('a1')('b2')('b3')

// "ar"
const r = curry(foo)('a1')('a2')('a3')
```

**Comment by nopeless** [comment]
```ts
type anyFn = (...args: any) => any;
type Curry<F extends anyFn> = F extends () => any ? ReturnType<F> : F extends (arg: infer I, ...args: infer R) => any ? (arg: I) => (...args: R) => ReturnType<F> : never;
```

?

**Comment by nopeless** [comment]
I belive this issue is related to the other library not TypeScript itself

[quick demo](https://www.typescriptlang.org/play?ssl=2&ssc=36&pln=1&pc=1#code/FAFwngDgpgBAhgOzAMQTAvDAFAOj3AJwHMBnALniQEoMA+SsAbmFElgGEBXAgsAHmQwoADxBQEAExINU9TIJFjJ0rDXT1EYGAH4YAJSghuCACpsB9CgtHip2QkQoBLBADMoBGAEkANDDw4DuQwLu6eemoaSDr2xBRekdgBQRQRdPqGxmbQFjAUCFAAbh7MwK6cCADGIE4A9miV3LwCQjbKMgi0WK4IVlQUXDz8yPQA3sAAkASZBGgInAA2C-DSmswAvizlVTX18BISWHD5nAC2AEYefucnFx79MPN3nuNTM2hwMADUMOcbLJV6iQQDBPJhGkMjgcqMwAPSwmCImAAPW0wEBCGBvwwoKwAEYYcB4UiUWiMViiDjzlgAEyE4lI1HAIA)

**Comment by loynoir** [comment]
@nopeless 

```ts
type MP2 = {
  a1: "a2";
  b1: "b2";
};
type MP3 = {
  a1: "a3";
  b1: "b3";
};
type MR = {
  a1: "ar";
  b1: "br";
};
function foo<K extends keyof MP2>(p1: K, p2: MP2[K], p3: MP3[K]): MR[K] {
  return { p1, p2, p3 } as any;
}


type anyFn = (...args: any) => any;

type Curry<F extends anyFn> = F extends () => any ? ReturnType<F> : F extends (arg: infer I, ...args: infer R) => any ? (arg: I) => (...args: R) => ReturnType<F> : never;

function curry<F extends anyFn>(fn: F): Curry<F> {
	return null as any;
}

// Actual: no error
// Expected: error
curry(foo)('a1')('b2', 'b3')
```

**Comment by nopeless** [comment]
@loynoir 
```ts
// Actual: no error
// Expected: error
const fooc = curry<typeof foo<'a1'>>(foo)('a1')('b2', 'b3')
//    ^?
```

You need the explicit function type

However, I'm sure that making more types to allow `curry(foo)('a1')` to be inferred disrupts the purpose of currying
