### ISSUE TITLE
`instanceof Object` does not work with the `in` operator

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#51007]
# Bug Report

### 🔎 Search Terms

`instanceof Object` `in`

### 🕗 Version & Regression Information

- This changed between versions 4.9.0-dev.20220919 and 4.9.0-dev.20220920

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220920#code/FAUwHgDg9gTgLgAgGYFcB2BjOBLKaHYDOAEgCoCyAMqQIYBGANiABRz1MBcC6A1mlAHc0ASi50oUJjXwBvYAgUIYIOChj4AhBraMQCAGT6EOpgTSE2mEFCQIA8nQBWILAaMByABZwAtg3dmxuwgANzAAL5AA)

### 💻 Code

```ts

export function isHTMLTable(table: unknown): boolean {
    return !!table && table instanceof Object && 'html' in table;
}
```

### 🙁 Actual behavior

Error: Type '{}' may represent a primitive value, which is not permitted as the right operand of the 'in' operator

### 🙂 Expected behavior

Should type check 

### Notes

Seems to be introduced by https://github.com/microsoft/TypeScript/pull/50666 which correctly introduces an error if `in` is used on non objects. The issue is that it does not handle testing for objects with `instanceof Object`

**Comment by MartinJohns** [comment]
You can just use `typeof table === 'object'`, which will also work for objects without prototype chain (e.g. `Object.create(null)`).

**Comment by dragomirtitian** [comment]
@MartinJohns  That is the workaround I used, forgot to mention it.  I still think ideally it should work.

**Comment by RyanCavanaugh** [comment]
I think `instanceof` is preferable since `typeof` can return `"function"` for things that are still `instanceof Object`

**Comment by Andarist** [comment]
The `unknown` type gets narrowed down to `{}` thanks to `!!table`. Should we then allow a `{}` -> `object` (`Object`?) transition through this `table instanceof Object`?

**Comment by RyanCavanaugh** [comment]
I don't see why not -- narrowing should generally be transitive (i.e. if `A -x-> C` is ok then `A -y-> B -x-> C` should be as well)

**Comment by jcalz** [comment]
Should we open a new issue for [this problem](https://stackoverflow.com/q/74407066/2887218), or does it belong here?

```ts
export function isHTMLTable<T extends object | null>(table: T): boolean {
  return !!table && 'html' in table; // error!
  // Type 'NonNullable<T>' may represent a primitive value, which is not permitted as 
  // the right operand of the 'in' operator.(2638)
}
```
[Playground link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221111#code/KYDwDg9gTgLgBAMwK4DsDGMCWEV0wZwAkAVAWQBliBDAIwBtgAeYuUGYFAE3zghoCtgGOAB84KJHToA+ABQxaDAFxxiAShU0IEBlVwBvAFBw4UYDCRRcAQmsL6wOADIncAOQALGAFs6bvLj2DADccAD0YaxQUNDWxuGRxACeYI5uAHI46ZJ0ikzE0v7eVEmmwGBm+BzwVHAVmN6YWABujs1UdEjAADRwAO4emGgeeDwoEPCpUI0w7JxwVDzxEXAwHo5QmADmXrxTevMQCKvr7pgo-hD7MNAAdLIATABsAMwAHGqGAL5AA)

**Comment by Andarist** [comment]
@jcalz I'd say that this is a different problem as the issue here, at least from my PoV, was very related to `instanceof`. The issue in this playground is related to generics, this one works just alright:
```ts
export function isHTMLTable(table: object | null): boolean {
  return !!table && 'html' in table;
}
```
