### ISSUE TITLE
Confict with certain namespace in v-for of vue

### ISSUE THREAD

**Issue by Ryuuki6602** [microsoft/TypeScript#51006]
# Bug Report

### 🔎 Search Terms

**key words**: 

>  vue 

>  v-for

>  route

> namespace

> code intelligence in Vs Code

### 🕗 Version & Regression Information

- This is a namespace confict between Typescript and vue which is not a big problem.
- I found it accidently, so i'm confused as well.
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____10 minutes____
- I was unable to test this on prior versions because ___I am new to Typescript___

### ⏯ Playground Link

[None playground link available for it matters nothing]

### 💻 Code

```ts
// route is a preserved keyword in Typescript somehow, but here, it's just a name of parameter
<div v-for="(route,index) in routeList">{{ route }} </div>

```

### 🙁 Actual behavior

TypeScript alerts me in Vs Code that 
Could not find name 'route'. Did you mean 'router'?ts(2570)
Array element destructuring pattern expected.

### 🙂 Expected behavior
- No alert.
- In actual, everything works properly in browser even if it's error in Vs Code, which reminds me that this may be a misunderstanding, if you click Quick fix,  the parameter 'route' become 'router' as Typescript suggested, the error will disappear, then press Crtl + Z and 'router' turns back to 'route',  the error which showed before will disappear as well.

**Comment by nopeless** [comment]
@Ryuuki6602 For problems with Vue, it is most probable that the issue comes from the Vue language server that compiles whatever Vue syntax into TypeScript. So you should go there.

Also, for TypeScript related issues with frameworks, it is best to specify the version of the framework you are using, as well as relevant package versions ~~because web development is not pleasant to work with~~

**Comment by RyanCavanaugh** [comment]
I don't see anything TS-related here. Unbound identifiers are unbound identifiers?

**Comment by fatcerberus** [comment]
> This is the behavior in every version I tried, and I reviewed the FAQ for entries about 10 minutes

I don’t think this is how you’re meant to fill this field…
