### ISSUE TITLE
generic type cannot be inferred from the parameter at the type level

### ISSUE THREAD

**Issue by lsby** [microsoft/TypeScript#51008]
# Bug Report

### 🔎 Search Terms

genericity, inference, typelevel.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220921#code/C4TwDgpgBAgjUF4oB4YD4AUBDAXLAlImrAFCiRQBClis8EAHsBAHYAmAzlNniwK4BbAEYQAToQTEAliwBmYqAygB+RVF4QAbmKA)

### 💻 Code

```ts
type AA = <A>(a: A) => A
type BB = AA extends (a: number) => infer x ? x : never
```

It looks like typescript has recognized that the shape of `AA` is `(a: number) => infer x`, then it should know that `A` for generics is `number` (Because `a` has type `A`, when `a` is specified as type `number`, we can be known that the generic type `A` is `number`), then the inferred `x` should be of type `A`, which is the type `number`.

I expected `BB` to be evaluated as `number`, but in fact, it was evaluated as `unknown`.

**Comment by RyanCavanaugh** [comment]
In situations like this, a type parameter is erased to its constraint, so in this case it appears as `(a: unknown) => unknown`. I believe we've tried to do full inference here before and the results have been, to put it mildly, catastrophic in terms of both overall performance and not hitting various depth/circularity problems.
