### ISSUE TITLE
Infer Type Guard Return Values

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#5101]
If a function returns a type guard, either the result of an `instanceof`or the return value of another type guard function, it could be inferred as being a type guard itself. However, it is simply inferred as a `boolean`.

This change would allow the following code to work: 

``` typescript
// The interface below should probably be merged into lib.d.ts and friends.
interface Array<T> {
    filter<O extends T>(callbackfn: (value: T, index: number, array: T[]) => value is O, thisArg?: any): O[];
}

declare class Foo { bar: number }

declare var blah: Object[];

blah.filter(object => object instanceof Foo)[0].bar // Property bar does not exist on type object
```

**Comment by mhegazy** [comment]
We should add the overload to the library regardless of this suggestion. @Gaelan feel free to send us  PR for updating the library.

**Comment by RyanCavanaugh** [comment]
Accepting PRs for the lib.d.ts overload.

The more complex portion of inferring type guards based on `return` statements was declined based on complexity. It's fun and easy to write a curried version of this that works today:

```ts
declare class Foo { bar: number }

declare var blah: Object[];

function isInstance<T>(ctor: new(...args: any[]) => T): (x: any) => x is T {
	return <(x: any) => x is T>(x => x instanceof ctor);
} 
blah.filter(isInstance(Foo))[0].bar // Property bar does exist :)
```

**Comment by aleksey-bykov** [comment]
can't quite see how changing `libs.d.ts` is able to fix this problem, mind sharing idea?

**Comment by mhegazy** [comment]
This is not a general fix, this is only a fix for array.filter. By changing the declaration you get the contextual type for the the function expression at the call.

**Comment by mhegazy** [comment]
The overload for `Array.filter` should be in already. closing.

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/16069 now tracks inferring the type guard automatically.
