### ISSUE TITLE
InstanceType<(typeof this)["somefield"]> type issue

### ISSUE THREAD

**Issue by imsamurai** [microsoft/TypeScript#51013]
Hi, for inheritance purposes i need to type methods depending on class returned by getter, but i get  'is not assignable' error.
Is this a bug?

```typescript
class S1 {}
class S2 extends S1 {}


class A  {
   get x() {
    return S1
  }

  f(): InstanceType<(typeof this)["x"]> {
   return new this.x as InstanceType<(typeof this)["x"]> // no error
  }

  fError(): InstanceType<(typeof this)["x"]> {
   return new this.x // got error
  }
}


class B extends A {
  get x() {
    return S2
  }

  f1(){
    return this.f();
  }
}


const a = new A;
const s1test = a.f() // S1 type


const b = new B;
const s2test = b.f1() // S2 type
```

https://www.typescriptlang.org/play?#code/MYGwhgzhAEDKCM0DeBfAUKSNYCZoFMAPAF3wDsATbRVNOzKaAQWmTVegHN9jpCAKAJRJ2HAE48ArmLJx4o9KIBmQgFzQAkmQjEwZYPgAqATwAO+ADzEAFgEsIAbQBEhJwF0AfG3FSZ0MvgA7tA29gB0hNCQmtq6+kZmlqGOLu5eAPTp-gD2BGJi2WIKdKxKAKL5hWoxOnoGJuZWdimunt6sEsTSsgHByRHQmVzZvPiVRazoihjgjABCBCTkVMzt3LwCgu0dvrK4xcrwQiIc0J3dIc1hKoIA3MXTwNmxUdAAvP5BzPdPLxDwpB07yi1yEgyyCBCiToGGeQIARsDetA5j84bwIDhAbwPvDrkctkNcFDzEA

**Comment by nopeless** [comment]
There are too many things wrong with this code but I'll just leave a good solution
```ts
class S1 {}
class S2 extends S1 {}

class A<X extends new (...args: any[]) => any> {
  constructor(public cls: X) {}

  get x(): X {
    return this.cls
  }

  f(): X {
    const o = new this.x()
    return o;
  }
}

class B<X extends abstract new (...args: any[]) => unknown> extends A<X> {
  f1(){
    return this.f();
  }
}


const a = new A(S1);
const s1test = a.f() // S1 type
//    ^?

const b = new B(S2);
const s2test = b.f1() // S2 type
//    ^?

```

[demo](https://www.typescriptlang.org/play?ts=4.9.0-dev.20220930#code/MYGwhgzhAEDKCM0DeBfAUKSNYCZoFMAPAF3wDsATbRVNDcKaAQQB4ANAk8q6M-Ad2gAKAHRiwAJwDmEAFzQwZAJ4BtALoBKaAF4AfAuX6kaaNGAB7MhGISArsGLmJQgA62ARiACWwMyDnQbFq0JtBS+MTQhEIa8hzGpqYSEbYSZNDEABZeECKgEKHooQBmMXHIoaYWVpHmOrwCGdm50RqV0MnEqenmANyFaEWYjABC7JyklDBg7tYSYA4NgqLi0gGKqpo6+rZkANZk5vxk+kSTPKxsRiXwMQmJnd1NOSKlGv2m6EUYltYK9XxBEwhAh3j8atAIPBSH9tApXjFoAB6JFwRDEJQufBoFGJaAAPQA-HRqn93ADGiMQTgwaTIhAcDDInD3K9blpcbgMpjsbjEkS0EA)

**Comment by imsamurai** [comment]
thanks, but based on current architecture (including dependency injector) i can't accept your solution.
Also, your code have error (in extends of B) and produce types, not instances (s1test/s2test)
The question is why it not work as expected

**Comment by nopeless** [comment]
> thanks, but based on current architecture (including dependency injector) i can't accept your solution. Also, your code have error (in extends of B) and produce types, not instances (s1test/s2test) The question is why it not work as expected

@imsamurai 
You are correct

Here is the one that correctly returns the type

```ts
class S1 {}
class S2 extends S1 {}

class A<X extends new (...args: any[]) => any> {
  constructor(public cls: X) {}

  get x(): X {
    return this.cls
  }

  f(): InstanceType<X> {
    return new this.x();
  }
}

class B<X extends new (...args: any[]) => any> extends A<X> {
  f1(){
    return this.f();
  }
}


const a = new A(S1);
const s1test = a.f() // S1 type
//    ^?

const b = new B(S2);
const s2test = b.f1() // S2 type
//    ^?
```

(demo)[https://www.typescriptlang.org/play?ts=4.9.0-dev.20220930#code/MYGwhgzhAEDKCM0DeBfAUKSNYCZoFMAPAF3wDsATbRVNDcKaAQQB4ANAk8q6M-Ad2gAKAHRiwAJwDmEAFzQwZAJ4BtALoBKaAF4AfAuX6kaaNGAB7MhGISArsGLmJQgA62ARiACWwMyDnQbFq0JtBS+MTQhEIa8hzGpqYSEbYSZNDEABZeECKgEKHooQBmMfIAklbEisD4ACpKLvjsRqFJKWm8AhnZudEaANyFaEWYjABC7JyklDB8gqLi0gGKqpo6+qv6RDM8rGytpsXwMQmJycSp6Vk5IqWDw0UYltYKOl2CTEIIDxZV0BB4KRXtoFHcYtAAPSQuCIYiNfBoaGJaAAPQA-HQ-q93O95tBxt8cL8XpEIDhgZFQe47ictMjcBkEUiYYkMUA]
