### ISSUE TITLE
Structurally equivalent object types do not collapse when together in a union type, but array types and empty object types do

### ISSUE THREAD

**Issue by johncmunson** [microsoft/TypeScript#51019]
# Bug Report
I have noticed that when determining whether or not to collapse union types to a simpler yet equivalent type, Typescript seems to mirror Javascript's runtime behavior, where equality for primitive values follows the rule of pass by value, whereas object equality follows the rule of pass by reference.
```ts
5 === 5            //=> true, pass by value
{a: 1} === {a: 1}  //=> false, pass by reference
```
Therefore, it makes sense that the corresponding primitive types are equivalent to each other and therefore allowed to reduce...
```ts
type Num = number | number  //=> number
```
Whereas the corresponding object types are not equivalent to each other and therefore do not reduce...
```ts
type Obj = {a: 1} | {a: 1}  //=> {a: 1} | {a: 1}
```

This seems harmonious and in alignment with the [Typescript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals)...
> 7. Preserve runtime behavior of all JavaScript code.

But, there's a problem... array types an empty object types do not appear to follow this same logic, even though their runtime equivalents still adhere to the rule of pass by reference.
```ts
type Arr1 = [] | []               // Collapses to........ []
type Arr2 = number[] | number[]   // Collapses to........ number[]
type EmptyObj = {} | {}           // Collapses to........ {}
```

So, what am I to make of this? It would seem that Typescript is not following a hard-and-fast rule for deciding when to collapse a union type and I suspect that this is a bug or compiler quirk.

### 🔎 Search Terms

primitive union type, object union type, collapsing union type, simplified union type, compacted union type, supertype absorbs subtype, union types in a structural type system

### 🕗 Version & Regression Information

Typescript v4.7.3

The issue mentioned above makes no appearance in the [Common "Bugs" That Aren't Bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs) document.

This is the behavior in every version I tried, and I reviewed the [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ) for entries about union types. In fact, union types are hardly mentioned in the FAQ _at all_.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEAUCcEsFtoC7QG4FNQIJ4AdUGdQBBAGQHVCBNAZVAGMB7AG0YENs90B3AC1QDsM9AOaoEvSKGgCWoAK59o9AVlwA6AFAhQAeQBGAK1S0EGHPgA0oJRl5WxqCdxZ8AJpZF8HLZplAARbVAAOW0AFTomVnZUDS1Q21QAD1pUbCQlPEtEUE56WUYXUA5UWEsWSHRyyBZfFXxQZ0KStN96AyMETTA6vFVQUm5MAH5+pxNoAjx6ItxaaG8G3TyTKpqCRtBmrCt24zwh9XVQY5PTs-OL860oOEQUVBGLgGFItg59y5OAMSkF0LMjp8gcCTloALQQyFQy5Q2Fg4FwqHqOqgKgICQAXiK6KkQlAAB9sTA+HiLloKPUQccKQQqac8DiScizMFZLBQFi+GzdA4CaAubAeRIyWAaXTQGLxccBULmbhQAAhehMDkYSCydCE9Ea4HkylUyVS7WoOXoJVMABMquNfIAZt4OJ89bSDfrxUsmKhnKadAZVQBvFgALlAAEYAL58wMhiOXLRBabihNSk7RsORwlpiM+wiQSCh1UAbQAunyS+L44m6YbxSWc3mrZzuQ5y4SZS3S8dK1Ka3T25A6yiAKKwFp6fQBjOgf2RoHd8W9qkzw5aQiuUC2+gSITKwqwL14WQVVQnmz4SrMCLMN6VAicVDMDQogCqfAA1nx6JwBFj5B+vwIhJ-p+34+kE+SMKqXKXm2EE+q+LioLaUioIUv6uEhKGFEBGHIZ4Lg5nwvhYs4viEqRYGoGgmL8lRvJtnRkDqEAA)

### 💻 Code

```ts
// Primitive types ALWAYS collapse when together in a union type.
// Object types, on the other hand, generally DO NOT collapse.
// The exceptions, it would seem, are array types and empty object
// types. Why? What is so special about arrays and empty objects?

                                  // Primitive?        Collapses?           Final Type
                                  // ----------        ----------           ----------
type Str = string | string        // Yes               Yes                  string
type Num = number | number        // Yes               Yes                  number
type Bool = true | true           // Yes               Yes                  true
type Bool2 = true | false         // Yes               Yes                  boolean
type Obj = {a: 1} | {a: 1}        // No                No                   {a: 1} | {a: 1}
type Arr1 = [] | []               // No                Yes                  []
type Arr2 = number[] | number[]   // No                Yes                  number[]
type EmptyObj = {} | {}           // No                Yes                  {}

// And for good measure... these all collapse as well.
type Unknown = unknown | unknown
type Null = null | null
type Undefined = undefined | undefined
type Any = any | any
type Never = never | never
```

### 🙁 Actual behavior

Union types do not follow a uniform logic when deciding when to collapse to a simpler, yet equivalent, form.

### 🙂 Expected behavior

Typescript is consistent with itself and follows uniform logic for when it decides to reduce a union type.

**Comment by jcalz** [comment]
> I have noticed that when determining whether or not to collapse union types to a simpler yet equivalent type, Typescript seems to mirror Javascript's runtime behavior, where equality for primitive values follows the rule of pass by value, whereas object equality follows the rule of pass by reference.

To the extent that it's true at all, this similarity seems like it's just a coincidence.  And it isn't always true, as you've noted.  The rules for union reduction don't care about the possibility of reference equality of the corresponding values they represent.  That is, the fact that `x !== y` at runtime has almost no bearing on whether the type `typeof x | typeof y` is reduced or not.

**Comment by johncmunson** [comment]
@jcalz I came across two resources this morning, both interestingly enough published by you, that _really_ helped me understand the source of my confusion.
- https://stackoverflow.com/a/57683652/5265805
- https://github.com/microsoft/TypeScript/issues/16386

The lesson that I've learned is... do not make the mistake of thinking that the Typescript quickinfo box is always going to show you the most efficient, reduced, expanded, or whatever type. Internally, this is pretty much what the compiler is doing. But what quickinfo decides to show to the user is often guided moreso by ergonomics ([don't want to show a massively expanded type if you don't have to](https://github.com/microsoft/TypeScript/issues/16386#issuecomment-383189174)) and expectations ([users may get even more confused if quickinfo doesn't closely approximate how the types appear in the source code](https://github.com/microsoft/TypeScript/issues/16386#issuecomment-383186255)).

A type could exist in many different, but equivalent, forms.

This also got me doing a deep dive on what "equivalency" truly means in a structural type system like Typescript. Recently, I made the mistake of thinking that `type A` should reduce to `type B`...
```ts
type A = { a: string } | { a: number }
type B = { a: string | number }
```

My initial line of reasoning was...
> If you have two object types, and the “shape” of them is the same w.r.t. to their keys but not their values, then the keys should be able to reduce to a unified object shape and all the values will turn into unions.

However, I've since come to learn that this isn't really how type theory works. For types to reduce, they must be equal. And for types to be equal, they must be able to extend each other. In both directions. `type A` must be able to extend `type B`, and vice versa. If it only works going in one direction, then that means you’re working with a _supertype_ and a _subtype_.
```
                 Supertype
|------------------------------------------|
|                                          |
|         { a: string | number }           |
|                                          |
|                                          |
|                 Subtype                  |
|    |--------------------------------|    |
|    |                                |    |
|    |  { a: string} | { a: number }  |    |
|    |                                |    |
|    |--------------------------------|    |
|                                          |
|------------------------------------------|
```

This is why all squares are rectangles, but not all rectangles are squares. They have a parent-child relationship going on, but they are not equivalent.

**Comment by fatcerberus** [comment]
@johncmunson Speaking as someone who also found TypeScript to be a gateway drug into type theory (and eventually category theory)… another potential source of confusion with TypeScript in particular is that `extends` does not mean “subtype of”.  It means “assignable to”, which isn’t always the same thing (in fact, the compiler internally makes a distinction between them).  Two types may be mutually assignable without necessarily being equal, or even isomorphic, because mathematical soundness isn’t a design goal for the language.
