### ISSUE TITLE
[feat] MUST NOT exist property

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#51022]
# Suggestion

## 🔍 Search Terms

- `never property`
- `MUST NOT exist property`
- `JSON-RPC 2.0`
- `RFC 2119 MUST NOT`
- `forbid property`
- `without property`
- `omit property`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`{a: 1, b: never}` means 
- `{a: 1}` is always valid
<details>
  <summary>Current</summary>

```ts
{
  let x = {} as { a: 1; b: never };
  const y = {} as { a: 1 };
  // @ts-expect-error
  x = y;
  void x;
}

{
  // @ts-expect-error
  const x: { a: 1; b: never } = {a: 1};
  void x;
}
```
</details>

<details>
  <summary>Suggested</summary>

```ts
{
  let x = {} as { a: 1; b: never };
  const y = {} as { a: 1 };
  // no error
  x = y;
  void x;
}

{
  // no error
  const x: { a: 1; b: never } = {a: 1};
  void x;
}
```
</details>

- `{a: 1, b: 1}` is ALWAYS invalid.
- `{a: 1, c: 1}` maybe valid, depends on how you use, as same as current logic.
<details>
  <summary>Code</summary>

```ts
{
  let x = {} as { a: 1 };
  let y = {} as { a: 1; c: 1 };
  x = y;
}

{
  const x: { a: 1 } = {
    a: 1,
    // @ts-expect-error
    c: 1,
  };
  void x;
}
```
</details>

## 📃 Motivating Example

So, typescript can express `RFC 2119` `MUST NOT`.

Use JSON-RPC 2.0 Spec for example.

```ts
const invalid = {
  id: "foo",
  method: "foo",
  params: {
    x: new Uint8Array([1, 2, 3]),
  },
}
```

Above invalid data will bypass type check, because it sneak into union type
```ts
| { method: string }
| ...
| { id: string; method: string }
| ...
```

If use something like
```ts
// notification
| { id: never; method: string; params: never }
| { id: never; method: string; params: Record<string, number[]> }
// simple call
| { id: string; method: string; params: never }
| { id: string; method: string; params: Record<string, number[]> }
```

Above did forbid that invalid data, but also blocked
```ts
const valid = {
  method: "notification",
  params: {
    x: [1, 2, 3],
  },
};
```

<details>
  <summary>Code</summary>

```ts
function send_implement_not_stated(
  x:
    // notification
    | { method: string }
    | { method: string; params: Record<string, number[]> }
    // simple call
    | { id: string; method: string }
    | { id: string; method: string; params: Record<string, number[]> },
) {
  void x;
}

function send_implement_state_never(
  x:
    // notification
    | { id: never; method: string; params: never }
    | { id: never; method: string; params: Record<string, number[]> }
    // simple call
    | { id: string; method: string; params: never }
    | { id: string; method: string; params: Record<string, number[]> },
) {
  void x;
}

const invalid = {
  id: "foo",
  method: "foo",
  params: {
    x: new Uint8Array([1, 2, 3]),
  },
};

const valid = {
  method: "notification",
  params: {
    x: [1, 2, 3],
  },
};

send_implement_not_stated(valid);
send_implement_not_stated(invalid);

// @ts-expect-error
send_implement_state_never(invalid);
// @ts-expect-error
send_implement_state_never(valid);
```
</details>

## 💻 Use Cases

`{a: 1, b: never}`

## Else
I think `{a: 1, b: never}` might better than `OmitLater<{a: 1}, "b">`

**Comment by loynoir** [comment]
Related https://github.com/microsoft/TypeScript/issues/12936

**Comment by loynoir** [comment]
Ah, stupid me, because of open `Exact Types` issues, assume this is impossible in the first place.

`{a: 1, b?: never}` seems the answer.

**Comment by MartinJohns** [comment]
> `{a: 1, b?: never}` seems the answer.

But be aware that this does not guarantee that no property `b` exists.

```typescript
type Foo = { a: 1, b?: never }

const a = { a: 1, b: "abc" } as const
const b: { a: 1 } = a
const c: Foo = b
```

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvKBDAXFAjAGigCMB+HAOwgDcIAnKAXwCgmBjOcgZ2E2TUxwFiOAEQYirEY0yco7LsDYduw-tjzSUGJQrk54iFESZA)

**Comment by loynoir** [comment]
Ah, yes. Reopen now if this is easier to implement than that feature.

**Comment by fatcerberus** [comment]
#12936 would be the answer.  Changing the meaning of `{ a: number, b: never }` would be a breaking change and also unsound - the meaning of that type is that you can't construct one *at all* without throwing an error.  The product of any type with `never` is isomorphic to `never` itself (i.e. `x * 0 = 0` for all `x`).

**Comment by RyanCavanaugh** [comment]
Discussion above slightly conflates two issues - optional properties aren't sound and probably still wouldn't be sound in the presence of exact types, since the aliasing problem would presumably still exist: `exact { a: string, b: string; c: number }` -> `exact { a: string, b: string; c?: number }` -> `exact { a: string, b: string }` -> `exact { a: string, b: string; c?: boolean }`. It would depend on the interpretation of optional types in the definition of an exact type.

**Comment by fatcerberus** [comment]
@RyanCavanaugh Right, but the feature request as reported was a way to specify that properties must not exist.  Optional properties only came up later as a workaround in the absence of exact types (i.e. optional `never` props).
