### ISSUE TITLE
Circular dependency check gets into way of perfectly valid type

### ISSUE THREAD

**Issue by svatal** [microsoft/TypeScript#51025]
# Bug Report

### 🔎 Search Terms

7022, circular

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAhhBcEG8AOAnA9k+BnMKCWAdgOYC+EAPhAK4EAmIAZoSLRALzV2PO0DcAUAzQoIAClCQAHmwAMvCJIA8AJnmSA1OoCUifhAgBjNARwR6SdtHZsONekwIsIAfggAiKG7juARm4H6MBzI6JhmIEgk-FH8EtDK3iEY2LiEpBSc9jyWdtyOfPxGJpDmCRxQZTaZeU6uHl7wbn4CAPQt+voAes78FZZJYaVRQA)

### 💻 Code

```ts
let a : {prop: string} | undefined = undefined;
for (let x=0; x<2; x++) {
  const dep = a === undefined ? "a" : "b";
  a = {prop: dep}
}
```

### 🙁 Actual behavior

> 'dep' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

If not inside any type of cycle (e.g. `while (true)`), dep is correctly typed as `"a" | "b"` (see the playground link). So the actual value of `a` has not been used in the type information. Even if it has been the case, the cycle should break because `a.prop` is strongly defined and is not dependant in any case on the `a = {prop: dep}` assignment

### 🙂 Expected behavior

`dep` typed as `"a" | "b"` even in the cycle

### Similar issues
I've found few simillar issues (e.g. [49837](https://github.com/microsoft/TypeScript/issues/49837)), but not one as simple as this case.

**Comment by MartinJohns** [comment]
Duplicate of #43047.

**Comment by svatal** [comment]
you are right, this one is quite similar, closing
