### ISSUE TITLE
Interfaces don't guide inference for functions that end in throw

### ISSUE THREAD

**Issue by appreciate-devon** [microsoft/TypeScript#51027]
# Bug Report

### 🔎 Search Terms

`implements` doesn't influence `throw`
function that only throws implicitly returns void

(I did find #7538 but there were no associated issues)

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries. I tried `4.3.5` as well as `next`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIwCuICAFAJQBcyIRAtgEbS4C+uuEAHgA7pRhkCADZwAzmOQAhOFGTB6PYRHoRwkjFjwFipSjnwFkYABZR0Ad1oQrAUSjmoZAERT0AcyJjnFQ+1ZAA)

### 💻 Code

```ts
interface Foo {
  func(): number
}

class Bar implements Foo {
  func() {
    throw new Error("Bogus")
  }
}
```

### 🙁 Actual behavior

```
Property 'func' in type 'Bar' is not assignable to the same property in base type 'Foo'.
  Type '() => void' is not assignable to type '() => number'.
    Type 'void' is not assignable to type 'number'.
```

### 🙂 Expected behavior

I expected `() => number` to be used to inform `Bar`'s definition for `func()`, since the interface sets the lower bound for acceptable return values.

**Comment by fatcerberus** [comment]
Method types aren’t currently inferred based on `implements` or `extends`.  Related to https://github.com/microsoft/TypeScript/issues/32082

**Comment by MartinJohns** [comment]
And the function ending in a throw is irrelevant. This errors as well:

```typescript
interface Foo {
  func(): 1
}

export class Bar implements Foo {
  func() {
    return 1
  }
}
```

**Comment by blast-hardcheese** [comment]
Ah, thank you. Seeing as my issue is completely covered by the other issue, I'll watch that and close this.

Unrelated: I've been using TS on and off for close to ten years, thanks very much to everyone involved.
