### ISSUE TITLE
Node.js-like module resolution doesn't follow parent paths

### ISSUE THREAD

**Issue by heycalmdown** [Microsoft/TypeScript#5102]
When I have following environment

* parent
  * node_modules
    * my-proper-external-module
      * index.d.ts
      * index.js
  * my-application
    * index.ts (`import m_p_e_m from 'my-proper-external-module'`)

It couldn't resolve where the `my-proper-external-module` is.

It should work according the proposal (https://github.com/Microsoft/TypeScript/issues/2338) and the source code(https://github.com/Microsoft/TypeScript/blob/b95e1ff6d8656693c80ac54a15893c3ad4859762/src/compiler/program.ts#L125).

I think it's come from by the `directory` which the `loadModuleFromNodeModules` have is empty string. It is an empty so it can not follow recursively.

Below is my `tsconfig.json`
```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "moduleResolution": "node"
  },
  "files": [
    "./a.ts"
  ]
}
```

**Comment by heycalmdown** [comment]
Got it.

When if I compile like this

```
tsc --project .
```

doesn't work. But when if

```
tsc --project $(pwd)
```

works.

**Comment by mhegazy** [comment]
looks like this is fixed in master. can you give `typescript@next` a try?

**Comment by heycalmdown** [comment]
Doesn't work for me

https://github.com/heycalmdown/typescript-5102/tree/master

**Comment by alexeagle** [comment]
Same issue with some angular2 users who put their `tsconfig.json` under a `src` folder.
Workaround is to run `tsc` from the parent directory and use the `-p` flag.

**Comment by mhegazy** [comment]
should be handled by https://github.com/Microsoft/TypeScript/pull/5275

**Comment by vladima** [comment]
fixed in e811fecda645cd7905821d48fcf5f757dbedfa50

**Comment by mhegazy** [comment]
@alexeagle and @heycalmdown can you give tomorrow's `typescript@next` a try?

**Comment by heycalmdown** [comment]
Sure, I was waiting your go sign.
