### ISSUE TITLE
Combination of intersections/partials causes invalid nested object type to not report error

### ISSUE THREAD

**Issue by dlane-stripe** [microsoft/TypeScript#51043]
# Bug Report

### 🔎 Search Terms

partial nested object type

### 🕗 Version & Regression Information

- This changed between versions 4.5.5 and 4.6.4. It reproduces in all versions since 4.6.4 (including nightly)

### ⏯ Playground Link

[Playground link with relevant code](https://tsplay.dev/wRl4Ym)

### 💻 Code

```ts
type OverridesInput = {
    someProp?: 'A' | 'B'
}

const foo: Partial<{something: any}> & {variables: {
    overrides?: OverridesInput;
} & Partial<{
    overrides?: OverridesInput;
}>} = {variables: {overrides: false}};
```

### 🙁 Actual behavior

There is no error on the `overrides` field in the object. Changing the type of `foo` slightly (removing one of the intersections) causes the error to appear correctly, but this unique combination of types produces no error. Does not matter what the contents of `OverridesInput` is, nor what the content inside the outer partial (currently `{something: any}`) is. Additionally, the following all produce the error correctly:

```ts
type OverridesInput = {
    someProp?: 'A' | 'B'
}

const foo: {variables: {
    overrides?: OverridesInput;
} & Partial<{
    overrides?: OverridesInput;
}>} = {variables: {overrides: false}};
```

```ts
type OverridesInput = {
    someProp?: 'A' | 'B'
}

const foo: Partial<{something: any}> & {variables: {
    overrides?: OverridesInput;
}} = {variables: {overrides: false}};
```

```ts
type OverridesInput = {
    someProp?: 'A' | 'B'
}

const foo: Partial<{something: any}> & {variables: Partial<{
    overrides?: OverridesInput;
}>} = {variables: {overrides: false}};
```

### 🙂 Expected behavior

There should be an error on the `overrides` field of the object since `false` is not assignable to `OverridesInput | undefined`.

**Comment by DanielRosenwasser** [comment]
```ts
interface Unrelated { _?: any }

// Identical but distinct types.
interface VariablesA { overrides?: OverridesInput; }
interface VariablesB { overrides?: OverridesInput; }

const foo: Unrelated & { variables: VariablesA & VariablesB } = {
    variables: {
        // Should be an error here:
        overrides: false
    }
};
```

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts? This changed in #47738

**Comment by ahejlsberg** [comment]
The issue here is that when the target in a relation is an intersection, common property checks are only performed at the top level. For example:

```ts
type A1 = { x: { a?: string } };
type B1 = { x: { b?: string } };
type C1 = { x: { c: string } };

const ab1: A1 & B1 = {} as C1;  // No error

type A2 = { a?: string };
type B2 = { b?: string };
type C2 = { c: string };

const ab2: A2 & B2 = {} as C2;  // Error
```

We definitely should error in both of the examples above.
