### ISSUE TITLE
Compilation of TS files faster within Visual Studio as opposed to being run externally

### ISSUE THREAD

**Issue by djg07** [Microsoft/TypeScript#5105]
I am finding that when I run my typescript project from within Visual Studio 2013, compilation is extremely quick ( < 1s ) on save.

However, if I attempt to compile outside of Visual Studio using sublime text and grunt/gulp, the compilation can take 30s to 1 minute for the same change. Is this an issue with the compiler itself?

**Comment by alexeagle** [comment]
The difference is likely incremental compilation. Your command-line build has to parse the standard library (`lib.d.ts`), then your code, then run the type-checker globally, and emit everything. In the editor, it caches the library, does incremental type-checking, and emits only for the changed files.
If you want command-line to be similar, https://github.com/broccolijs/broccoli which is a much more capable input-tree-to-output-tree transformer and is capable of caching. Angular has written some extensions on top of broccoli to optimize inside each tree transformation by diffing.

**Comment by DanielRosenwasser** [comment]
If you use the `--watch` command line option (which is only supported under Node.js right now), we also cache source files that haven't been changed.

**Comment by weswigham** [comment]
I believe gulp-typescript with gulp.watch should also perform incremental builds.
