### ISSUE TITLE
--declaration exposes private members

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#5106]
```
// tmp.ts
import {Secret} from './baz';

export class Foo {
  private bar(s: string): Secret { return null; }
}

// baz.ts
export class Secret {}
```
`$ tsc tmp.ts baz.ts --declaration -m commonjs`
```
// tmp.d.ts
export declare class Foo {
    private bar(s);
}
```

I don't really want users of my library to know about `bar`, even though the type-checker will give them the red squiggle underline.
OTOH, it's really nice that you hide the type information for the parameter and the return type of `bar`, so my `Secret` isn't exposed to users, as @mhevery and I had thought might happen.

(Sorry there is probably a duplicate of this already but I didn't find it)

**Comment by DanielRosenwasser** [comment]
The thing is that your users *want* to know that a private member exists in case they subclass your class.

Check out the following [on the playground](http://www.typescriptlang.org/Playground#src=class%20C%20%7B%0A%09private%20a%3B%0A%7D%0A%0Aclass%20D%20extends%20C%20%7B%0A%09private%20a%3B%0A%7D):

```TypeScript
class C {
	private a;
}

class D extends C {
	private a;
}
```

It currently gives the error:

```
Type 'D' incorrectly extends base class 'C'.

**Comment by alexeagle** [comment]
Okay, that seems reasonable to me.
