### ISSUE TITLE
Allow union to do declaration merging

### ISSUE THREAD

**Issue by lsby** [microsoft/TypeScript#51060]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- type
- tuple
- union
- declaration merging

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I wish to add a new syntax to implement `union` that can be `declaration merging`.

## 📃 Motivating Example

I often use the `declaration merging` feature of `interface`, which allows me to extend type declarations at a later stage without modifying the original code.
But `interfaces` are in the form of `key-value pairs`, and sometimes I wish I had a `union` that could be extended instead of key-value pairs, because not all the time `keys make sense.

Can be written like this to get a union that can be `declaration merging`:

```typescript
interface arr [number, string]
interface arr [boolean]

type values = arr // number | string | boolean
```

or

```typescript
enum arr [number, string]
enum arr [boolean]

type values = arr // number | string | boolean
```

## 💻 Use Cases

I think this requirement is universal.
In many cases it is necessary to declare a type and then extend it elsewhere.
But not all the time you should use key-value pairs, when `key` is not important, it is more convenient to use `union`.

Consider a simple example, I want to create a function whose arguments must be of a given type, and these types can be extended later:

```typescript
interface T {}

type F<U> = { [P in U as string]: P extends keyof T ? T[P] : never }[string]
type M = F<keyof T>

function f(a: M) {}

// The following may be in another file
interface T {
  a1: number
}
interface T {
  a2: string
}

f(1) // ok
f('a') // ok
f(true) // err
```

While this works, `a1` and `a2` don't make sense and I can't omit them.

I hope it's possible:

```typescript
interface T []
function f(a: T) {}

// The following may be in another file
interface T [number]
interface T [string]

f(1) // ok
f('a') // ok
f(true) // err
```

This saves me from having to write redundant keys like `a1` and `a2`.

\* This is just a simple example, `declaration merging` is useful in many places. And adding this feature will write less useless keys.

**Comment by fatcerberus** [comment]
I'm a little confused by your examples - in all cases, you seem to intend `T` to be a *type union*, not a tuple.  A tuple would be `[number, string]`, i.e. an array where the first element is a number and the second is a string.

**Comment by lsby** [comment]
> I'm a little confused by your examples - in all cases, you seem to intend `T` to be a _type union_, not a tuple. A tuple would be `[number, string]`, i.e. an array where the first element is a number and the second is a string.

Ah yes, you are right.
There is something wrong with my statement.
Since tuple and union types can be converted to each other through some type manipulation, I accidentally mixed them up.
At the beginning I wanted to say tuple types, that is:

```typescript
interface arr [number, string]
interface arr [boolean]

type values = arr // [number, string, boolean]
```
But for the convenience of writing the example, I use the union type in the example.

Now I think union types are better and simpler than tuples, and don't need to consider ordering (because tuples are ordered, unions aren't).

I have revised the relevant places, thank your correction.

**Comment by fatcerberus** [comment]
> because tuples are ordered, unions aren't

I’m not sure how this is relevant since a union isn’t just an “unordered tuple”.  A tuple type refers to multiple distinct values; a union models a single value which can one of several types.  They are completely different kinds of types.

**Comment by lsby** [comment]
> I’m not sure how this is relevant since a union isn’t just an “unordered tuple”. A tuple type refers to multiple distinct values; a union models a single value which can one of several types. They are completely different kinds of types.

Ah, that's not the point.
I just want a `declaration merge` scheme that isn't a key-value pair, since useless `key` are redundant.
Either a tuple or a union is fine, because I just want to use it for type-level calculations, and the two types are convertible to each other, Although this involves some complex type calculations, Here is an [example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgSwPZwCpIJJ2BATgZwgGNhk4AeVAPigF4oAKVKCADxzgBN8oBDOEFAD8jVgC4oqAJR0a-QRLgQAbnhlsO3URIRwAZnlgzacgcNhRFKvAChQkKABle+YPDKUa9dynRYcBMSkKJQs7BBcPPLmDOKSxqYKUEqquDQaEVqxOvqGjgl8ZiKOlsnWuHbg0D5oSKgArmAANhCUADROLsB0na41nl5QANqoALphmjxDKXjjIkPjEkMAdKs16A3NrQCirERN9ZytqB3OrlRUp12jNpUOmy3o-dQ9zBmRhSAL5qjT9QC2ACNZqUZhU7tAAII9P5AvAdVy4XQAc3GEKgACFXo1Hkh+pCaAB6QlQREoqAAH2SAOBFXs0AAwj11nUca0MUSSUMyXBkR04DTZkA).

> because tuples are ordered, unions aren't

In this sentence, what I want to say is, after thinking about it I think union types are more reasonable.

Since I'm extending types all over the program, multiple files may be involved.
How to distinguish the "order" of the files?

If I write `interface arr [number, string]` in file A and `interface arr [boolean]` in file B, should arr be `[number, string, boolean]` or `[boolean, number, string ]` ?
Union types don't have this problem, `number | string | boolean` is the same as `boolean | number | string`.

**Comment by lsby** [comment]
> I should note that declaration merging as currently implemented always creates subtypes; adding properties to an interface makes a type which is assignable to the unmodified version. Your proposal, e.g., to turn `type T = number | string` into `number | string | boolean` would lead to unsoundness as it would let consumers widen types in-place without causing type errors.

You are right, I didn't notice that.
I can't think of any way to improve it.
I will close this issue until I have a better idea.
Thanks for pointing this out.
