### ISSUE TITLE
Inconsistent type narrowing with arrow functions

### ISSUE THREAD

**Issue by Ustice** [microsoft/TypeScript#51075]
# Bug Report

Let's start off with the code.

```Typescript
// Function
const variable: unknown = 'yay'

function throwError  (message: string): never {
  throw new Error(`Invariant faliure: ${ message }`)
}

if (typeof variable !== 'string') { // (1)
  throwError(`variable should be a string, not ${ typeof variable }`)
}

variable.toUpperCase() // No type error

// ------------------------------------------------------
// Arrow Function
const otherVariable: unknown = 'boo'

const throwErrorArrow = (message: string): never => {
  throw new Error(`Arrow faliure: ${ message }`)
}

if (typeof otherVariable !== 'string') {  // (2)
  throwErrorArrow(`otherVariable should be a string, not ${ typeof otherVariable }`)
}

otherVariable.toUpperCase() // 'otherVariable' is of type 'unknown'.ts(18046)
```

I see no reason why I should not be able to type narrow (1) and not type narrow (2). If there was to be a difference, I would expect that the function declaration wouldn't be able to type narrow due to how it interacts with hoisting, which could make it difficult to determine when it is being run.

### 🔎 Search Terms

type guard arrow function

### 🕗 Version & Regression Information

4.8.4

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about arrow functions and type narrowing.
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAbgQwE4EsECMA2BTAXDAVzAGswQB3MGAXhgEYAoBgMyOChXBigAskKAokn5IYMABQBbbBAgIA5nhjRUYeQEp8YbHGyiA3gzG9+5GNrNCR4gAYBJMIlQIwsZgkwoCSJQBJ9MNKyCtgwAL426gxhTCjMElAAngAO2CDxTmhYoQCE1LQA5CooagXqMIbGfILCIEi2mRg4yjwgBJgAJjDooQjKUKryADTmILD+3ClpGchZzRFRMQyN2QB0UCAAqsmpSADCCBDY4uUA9KcwAHIgk6kweiJMoJCwYzx6AGqzTUpEpBRUWiMBjPaDcarkKx1ACCtTMtCkMjkinwxTUmnMOj0NAAfBUjODTJjLLV6jZYUT3J5vH4AkFkaEFtFYvFxElUukYG9Pt9sjA8oU0fIyviqqYoUgKRRbNykF9nHyIK12l0ejA+kKRmRxgF2dMubweQr5pFmQxZfK5th1lsdnoDkcTjBzjAChbeTgCjAUBAufE9a6-mRKAV1hBxHQABwABgALAA2KJAA)

### 💻 Code
```Typescript

const otherVariable: unknown = 'boo'

const throwErrorArrow = (message: string): never => { // (1)
  throw new Error(`Arrow faliure: ${ message }`)
}

if (typeof otherVariable !== 'string') {  // (2)
  throwErrorArrow(`otherVariable should be a string, not ${ typeof otherVariable }`)
}

otherVariable.toUpperCase() // 'otherVariable' is of type 'unknown'.ts(18046)
```

### 🙁 Actual behavior
Type error due to not properly type narrowing `undefined` to `string`

### 🙂 Expected behavior
No type errors.

**Comment by RyanCavanaugh** [comment]
`never` function returns in control flow analysis generally require explicit type annotations *on the binding itself* in order to be detected, namely:
```ts
const throwErrorArrow: (s: string) => never = (message: string): never => { ...
//                     ^^^^^^^^^^^^^^^^^^^^
```
This was a trade-off because building up the CFA graph on the assumption that any function call might be resolved to return `never` had a very large performance impact, whereas the number of non-declaration `never`-returning functions in any program is usually zero.

**Comment by Ustice** [comment]
Is that the case when the function that is passed to the const is explicitly typed? I completely understand trying to account for `never` when doing so dynamically, but the type signature should be able to be accessed without having to analyze the internals of the function.

**Comment by fatcerberus** [comment]
It’s not about the type of the function, but the type of the binding (a `const` here).  My understanding of this situation is that the control-flow graph is constructed before type inference is done, so unless the `const` is explicitly typed, TS doesn’t know whether it refers to a `never`-returning function or not when it builds the CF graph.

 (It might intuitively seem like `const foo = explicitlyTypedArrowFunc` should also be considered explicitly typed, but this is not the case.)

**Comment by Ustice** [comment]
@RyanCavanaugh @fatcerberus Thank you both for explaining this. It was breaking my brain.
