### ISSUE TITLE
Cannot specify that a property is inherited when defining interface

### ISSUE THREAD

**Issue by vasyop** [microsoft/TypeScript#51073]
# Bug Report

### 🔎 Search Terms
interface inherited property

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about interfaces and classes

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/JYOwLgpgTgZghgYwgAgJIHkBGArZBvAWAChlTkATAewGUBbMACwAoBKALmQDdLhyBuYgF9ixBABs4AZ0nIsuYLQAOYiLQjgZGHPmJlkigK6YxwBBRr1mLHST1kElEJMoqAdGMoBzJgHJJlnxYBW1JhIjDRR0kwZEoOLVwAXmQQCAB3WRxWYMinGPFHFGS8ZFcyymRBYILU1yo6RmzkAHpm5ABVEAQ4A08GGIAVAE9FCABRKChKKA4aiDqLRmRgGRBKGLhkGAMusGBHIA)

### 💻 Code

```ts
interface IObj {
    doSmth(): void;
}

class Obj implements IObj {
    public doSmth() {
        console.log('smth');
    }
}

const o: IObj = new Obj();

const clone = { ...o };
clone.doSmth(); // Uncaught TypeError: clone.doSmth is not a function
```

### 🙁 Actual behavior

no tsc compiler error

### 🙂 Expected behavior

I expect `const o: IObj = new Obj();` to generate an error because `doSmth` is not an own enumerable property of `o` (it is inherited from the prototype). The spread operator seems to assume that `doSmth` is an own property of `o`, so, as a result, clone's type is `{ doSmth(): void; }` but the "actual" type is `{}`.

If we have 

```ts
const o = new Obj();
```
instead of 
```ts
const o: IObj = new Obj();
```
we get a `Property 'doSmth' does not exist on type '{}'` error which indicates that `IObj` and `Obj` are clearly not compatible. 
Perhaps we should be able to mark `doSmth(): void;` as "inherited"?

**Comment by RyanCavanaugh** [comment]
#9726

**Comment by vasyop** [comment]
I ran into this after using the spread operator on a `Promise` and the later calling `.then()` on it, which is apparently fine at compile time, but fails at runtime. 
TS behaved as if the type of `{ ...somePromise }` is `Promise` which is simply wrong.
I can imagine easily running into similar issues with other [standard built-in objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects).
