### ISSUE TITLE
Bad type inferring on big JSON file

### ISSUE THREAD

**Issue by Jeromearsene** [microsoft/TypeScript#51083]
# Bug Report

## Introduction

This problem is difficult to reproduce. I can't use Playground because I need to add external JSON files.
So, I'm sorry if I can't help you with more explicit context.

## Context

- **Typescript version**: `4.7`
- **Tsconfig**:

```JSON
{
    "compilerOptions": {
      "target": "ES2017",
      "module": "commonjs",
      "declaration": false,
      "declarationMap": false,
      "skipLibCheck": true,
      "sourceMap": true,
      "outDir": "./dist",
      "rootDir": "./",
      "allowSyntheticDefaultImports": true,
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
      "resolveJsonModule": true
    },
    ...
  }
```

## Problem

When I import an external JSON file, I want to have his type.

### No problem example

I can do this with simple JSON, no problem:

**JSON**

> test-with-array.json

```json
[
    {
        "a": 1,
        "b": 2
    },
    {
        "toto": "abc"
    }
]
```

**Typescript**

```typescript
import testWithArrayDatas from './test-with-array.json';

type JsonWithArray = typeof testWithArrayDatas;
```

**Result**

<img width="508" alt="Capture d’écran 2022-10-06 à 18 01 34" src="https://user-images.githubusercontent.com/9333686/194362351-3f6a1ed3-4e64-40a6-a96b-075a0293b73a.png">

### Problem example

But if I do the same thing with a big JSON file, Typescript does not find type:

**JSON file**

[test-with-big-array.json.zip](https://github.com/microsoft/TypeScript/files/9726645/test-with-big-array.json.zip)

**Typescript**

```typescript
import testWithBigArrayDatas from './test-with-big-array.json';

type JsonWithBigArray = typeof testWithBigArrayDatas;
```

**Result**

<img width="701" alt="Capture d’écran 2022-10-06 à 18 07 52" src="https://user-images.githubusercontent.com/9333686/194363633-8fc18c95-3356-4b08-9cf3-70634ac60e1a.png">

You can look the type seems to be `{}`. That's not true ! The minimum true type is `any[]`
 or `Record<string; unknown>`.

## Attempted

A choice:

- Find the minimum good type: `any[]` instead of `{}`
- Display a warning to prevent user that the type inferring can't analyze all because it's too important/large
- Purpose a property in `tsconfig` to set maximum size of variable type inferring analyze

## Note

I could see that between a minimum size of JSON and more bigger, the result is `any[]`.

In the idea:

| small JSON | big JSON | really big JSON |
|------------|----------|-----------------|
| good type  | `any[]`    | `{}`              |

**Comment by RyanCavanaugh** [comment]
> You can look the type seems to be {}. That's not true ! The minimum true type is any[] or Record<string; unknown>.

`42` and `"hello"` are valid top-level JSON results; those values are `{}` but are not `Record<string`s.

The current behavior is still correct. I think it's extremely unsurprising for TS to refuse to try to make sense of 38 megabytes of JSON.

**Comment by fatcerberus** [comment]
> Display a warning to prevent user that the type inferring can't analyze all because it's too important/large

I'm trying to imagine how an algorithm that works based on how "important" the data is would look like...

**Comment by RyanCavanaugh** [comment]
I assumed that was mistranslation of a word meaning "weighty" 😉

**Comment by MartinJohns** [comment]
> `42` and `"hello"` are valid top-level JSON results; those values are `{}` but are not `Record<string`s.

@RyanCavanaugh Although technically, `null` is valid top-level JSON as well, but not assignable to `{}`.

**Comment by Yurovskyy** [comment]
130 megabytes of json don't work either! This bug is real and I have github actions to prove it. Locally it works fine, but when I push it to github, it won't work no matter what. I'm going to try to break the json into smaller ones. If you guys are curios, go see "actions" on my repository called sitedeploy .
