### ISSUE TITLE
Type checking not working when mapping class methods/constructor args from type parameter

### ISSUE THREAD

**Issue by germanamz** [microsoft/TypeScript#51089]
# Bug Report

When mapping a class (with no nullable properties) from a type parameter into a new type filtering keys with `as` and value, type checking doesn't work.

This only happens when mapping arguments on a class method/constructor.

### 🔎 Search Terms

       is:issue, is:open, Mapped as

[Url](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+Mapped+as+)

### 🕗 Version & Regression Information

V^4.1.5 and newer

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs, for the holomorphic types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?ts=4.9.0-dev.20221006#code/PQKhCgAIUglBTAtgewG70gQwDbco+AFwAtkATAZ0gDMAnZRSAY20woqhGHEIE8AHDAAVWASwB2AYVbsAPJIB8kALyQA3lEgBtANaQJkHfF7JqkSViqTdAXUjwAHoXjjKkAGIBXcU0Kjk4pAA-JDi8Oi0kABchjZBMdY6do7OrlQAIpjOwea2kAA+kBSEtBIA5tG5SQDc4AC+teAsbFQAQmzwsgCy9k4ubu0UnZjivApKGpCQAPqiZACEMcWl4mW1U0y08FnwZACChIuQmc7rkJ78ZDv7hzEn8I0bAcuevsi0ABRXhJjxkCKYCTSFrdBQASnUmimJFEFAAdBJRIQvllMGCznVwJpEcjvr8YgCgTIKKCIZMppAAPIAIwAVvBfHCWqIyuIPjCKAAaSB49FYin6Mwon5BOGzMhkqEUjliuYqHmo2VkOGEZAAZRK5Q+fIFmKloiFeNFm22zhukoF0OIsLhJuuB3lYQA7scdsLMLatvbCDqKXqBQbIO7RRdvrsDhbLTLQ97HfAXfd3XCY2aI2cppiM-UsUxnoQsASxFJibJBsNRuN5eSU+HCDEAOT1zmaO2puuheOu5za5sNHPEjyiWjFXqpAYdWTuIfFCaacSYAhHZblM5keAUJh-ZerAqhTy4R5FTDobWQgW58QUZDYeBw7DIMofet0BhH9D132YvUXkfUQuA4sQSnYdCCUVRyXFBsmznBd4Cg5spjXDcYnEfdsAQ5gvTbeDNBrG4UM7RMwV7RpmnYSA1QZAIyFHfo2gnSiLzIWdoSRG8l01VYzgoUhaEILdOIqQpUIPbMmjzIp-yJEFGOosCzxmOYcNYwgb2UopePbET0JbLDawIhM3WI3DLm9HDvwk6hMDeWheHlbpaLSDsXQ+OE3MwWgygoGIRl4LQbAhZQlF8hQPkkVVaBiLpuSNBI81oV4IqEDzYOcYdQS0AAGAKVBYyAtkITxaECZ1zAi90+T7cTL2vW970fKybN4D5gOKbk1FCWCG3nAgm0UsgG0wIbMHrSA6jBPkf1qu8Hw+RqIua2TXHayA-FUuDIHrNab1G8a+SAA)

### 💻 Code

```ts
type PlainClass<C> = {
  [k in keyof C as C[k] extends Function ? never : k]?: C[k] extends Date ? C[k] | string : C[k];
};

class Base<M extends Base<any>> {
  _id!: string;
  createdAt!: Date;
  updatedAt!: Date;

  constructor(data?: PlainClass<M>) {
    this.init(data);
  }

  init(data?: PlainClass<M>) {
    Object.assign(this, data);

    if (data?._id) { // _id is not recognized in data
      this._id = data._id.toString();
    }

    if (data?.createdAt) { // createdAt is not recognized in data
      this.createdAt = new Date(data.createdAt);
    }

    if (data?.updatedAt) { // updatedAt is not recognized in data
      this.updatedAt = new Date(data.updatedAt);
    }
  }
}
```

### 🙁 Actual behavior

Type checking is not recognizing keys from the generated type, this only happens when mapping a type parameter into a method/constructor argument.

### 🙂 Expected behavior

Type checking should recognize mapped keys and types in class method/constructor.

**Comment by RyanCavanaugh** [comment]
This is correct behavior; given an arbitrary `PlainClass<M>` with a generic `M`, you cannot make linear predictions about whether a given key will be present in its output. For example, you could have
```ts
class Violation extends Base<any> {
    _id!: string & Function;
}
```
which can legally call with an unrelated `_id` since `_id` is not in `PlainClass<Violation>`:
```ts
const v = new Violation();
const obj = { _id: 32, createdAt: undefined }
v.init(obj);
```

**Comment by germanamz** [comment]
@RyanCavanaugh 
In class `Base` parameter M is extending itself therefore `init()` is expecting an object with at least the properties defined in Base class

**Comment by RyanCavanaugh** [comment]
Regardless, it's still the case that it's not sound to evaluate a mapped type in terms of its constraint.
