### ISSUE TITLE
False positive "'await' has no effect on the type of this expression" when in node_modules directory

### ISSUE THREAD

**Issue by dnicolson** [microsoft/TypeScript#51088]
# Bug Report

### 🔎 Search Terms
await has no effect on type
80007

### 🕗 Version & Regression Information

v4.9.20221005

### 💻 Code

```sh
npm i cpbitmap-to-png@1.0.1
code node_modules/cpbitmap-to-png/cli/main.js
```

### 🙁 Actual behavior

![PixelSnap 2022-10-06 at 21 29 09@2x](https://user-images.githubusercontent.com/2276355/194412056-60ac1183-1e15-499c-b7c5-360bea87b819.png)

### 🙂 Expected behavior

No `await` hint. The following commands open the same code without it:
```sh
git clone https://github.com/hthetiot/cpbitmap-to-png
cd cpbitmap-to-png
git checkout be73a50
code cli/main.js
```

**Comment by IllusionMH** [comment]
Looks like TS captured problem in your code. You are tryi g to `await` method that does not return promise(according to docs and types) and expects callback instead.

```ts
image.write(path, cb); // Node-style callback will be fired when write is successful
image.writeAsync(path); // Returns Promise
```

**Comment by dnicolson** [comment]
While that is true, the problem is the disparity in the code examples.

The code that is checked out via git does not have the same result.

**Comment by RyanCavanaugh** [comment]
I don't see a demonstrated defect. These are two different ways of editing code and, as the name might imply, "hints" are based on some heuristics. Different behavior under different environments is an expected aspect of that.

**Comment by dnicolson** [comment]
@fatcerberus I think you have it the other way around, the types are being picked up when inside the `node_modules` directory but not from a project directory.

In any case, the issue was that `npm install` had not been run in the project directory.
