### ISSUE TITLE
Fake error in TypeScript vscode validation

### ISSUE THREAD

**Issue by TribeLoop** [microsoft/TypeScript#51084]
Type: <b>Bug</b>

vscode say "Event dont get .deltaY" but it works in JS when event comes from "wheel" event

I just tried to access wheel events and determine up and down,
This code works when exported to js but print an error in typescript :

$("body").on('wheel', function(event: Event) {
console.log(event.originalEvent.deltaY)
})

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
![2022-10-06 17_06_20-UIZoom ts - Projects Maestro - Visual Studio Code](https://user-images.githubusercontent.com/99650975/194349144-01a6b46d-c29a-439a-a5fc-cbf0be8a9edf.png)

Sandboxed: No

**Comment by mjbvz** [comment]
This looks an issue with the jQuery typings, not VS Code: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/JQuery.d.ts

You can workaround it by telling us that `originalEvent` is a `WheelEvent` instead of a generic `Event`:

```
$(targetSelector).on('wheel', e => (/** @type {WheelEvent} */(e.originalEvent)).deltaY); 
```
