### ISSUE TITLE
Missing compiler warning on if-clause

### ISSUE THREAD

**Issue by HJoost** [Microsoft/TypeScript#5109]
Hi,

last week I made a mistake while typing an if-clause:

if(x === false);
{...}

When I debugged it, the code inside the brackets got hit every time. For many code runs I did not see the wrong semicolon after the if-statement.

For me, a compiler warning about the misplaced semicolon would be great, like the C# compiler does it.

Helmut

**Comment by DanielRosenwasser** [comment]
While I am dubious of any actual use case for that sort of code, a good workaround for now is to use TSLint: https://github.com/palantir/tslint

The `"curly"` tslint rule would have caught this for you.

**Comment by HJoost** [comment]
Thanks for your reply. 

Indeed this type of code should not be used, it was just a mistake and I wondered why the if path got hit independent of the value of x... (I think you how easy it is to overread such a little mistake while debugging ;-) ).

**Comment by RyanCavanaugh** [comment]
I'm not aware of any C-syntax languages that flag this as an error. +1 for TSLint.

 I remember spending a *long* time in college debugging this infinite loop :stuck_out_tongue_closed_eyes:
```ts
int x = 0;
while (x < 10); {
  x++;
}
```

**Comment by HJoost** [comment]
![c semikolon](https://cloud.githubusercontent.com/assets/13537894/10302804/757c41f6-6c0f-11e5-9836-1d9af66a374c.png)

This is the way how it looks in my Studio with C#, sadly it doesn't in typescript :-(

**Comment by mhegazy** [comment]
i do think there is room for making this an error. it is clearly wrong, or at best very bad pattern to follow,  in the case of the if statement, and can be detected in cases of while/for cases if we limit it to expressions with side-effects (let's say only assignments, and call expressions).

**Comment by DanielRosenwasser** [comment]
> i do think there is room for making this an error.

Yes, I somewhat agree; unlike a `while` loop, I don't see how this could ever be useful.

**Comment by RyanCavanaugh** [comment]
Accepting PRs. The only rule we want is that the "true" arm of an `if` cannot be the `EmptyStatement` production.

**Comment by mhegazy** [comment]
thanks @MartyIX!
