### ISSUE TITLE
import statements are transpiled even if output is set to ES6

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/TypeScript#5110]
Hi

Up until latest update my es6 imports were left the way they was when transpilig to es6.
From the latest update now they are transpiled to the module representation.

For example:

```
import TabControl from "../../components/tabs/tab_control";
```

is transpiled to 

```
var tab_control_1 = require("../../components/tabs/tab_control");
```

The worst part is, that it breaks the TSX transpilation as for example

```javascript
  <TabControl tabs={this.state.tabs}>
            {
              this.props.validations.map((validation: BoardValidation, index: number) => {
                return <BoardValidationView key={index} />
              })
            }
</TabControl>
```

is transpiled to:

```
<tab_control_1.default tabs={this.state.tabs}>
            {this.props.validations.map((validation, index) => {
            return <BoardValidationView key={index} />;
        })}
          </TabControl>
```

Note how the closing tag is not transpiled.

This is probably bug in transpilation, but can the transpilation of import statements be disabled? Up until today all was working well ... now none of my TS project runs ;((

For completeness, here is my tsconfig

```
{
    "compilerOptions": {
        "target": "es6",
        "declaration": false,
        "noImplicitAny": true,
        "removeComments": false,
        "noLib": false,
        "preserveConstEnums": true,
        "noEmitHelpers": true,
        "suppressImplicitAnyIndexErrors": true,
        "watch": true,
        "outDir": "../dist",
        "jsx": "preserve"
    },
...
}

**Comment by sandersn** [comment]
What version did the latest update give you? I tried the following code with 1.6.2:

```
import TabControl from "tab_control";
let t = new TabControl();
```

With a file named tab_control.ts:
```
class TabControl {
    // nothing here
}
export default TabControl;
```

And using your tsconfig, I got the below output:

```
import TabControl from "tab_control";
let t = new TabControl();
```

**Comment by basarat** [comment]
> What version did the latest update give you?

The version from master two days ago. 

Tracked from [atom-typescript package.json](https://github.com/TypeStrong/atom-typescript/blob/129187d2f5c098d8c71cfa0b849ef15b0bdea8f4/package.json#L56)  to [this version](https://github.com/TypeStrong/ntypescript/releases/tag/1.201510040223.1%2B331d26f40271c7a21c6fa74ffac633b45f653dda)

The bug was not in [this version](https://github.com/TypeStrong/atom-typescript/blob/b8c132d31ad4793fcd5e2c576e832a35ab740641/package.json#L56) : [git tag](https://github.com/TypeStrong/ntypescript/releases/tag/1.201509200205.1%2B92f5f59a075a08de32a43b3dc09f7f54751b471e) and not in 1.6 either (which is even older).

**Comment by mhegazy** [comment]
@basarat do you have a reproduction of this issue that you can share?

**Comment by basarat** [comment]
Original issue report https://github.com/TypeStrong/atom-typescript/issues/643 But I'll test more ... see below: 

> do you have a reproduction of this issue that you can share?

Quick test with `typescript@1.7.0-dev.20151006` yielded valid results : 

![image](https://cloud.githubusercontent.com/assets/874898/10303299/753af4cc-6c5e-11e5-875e-81f845f98868.png)

I'll investigate further the next time I upgrade and comment. Sorry about a possibly invalid issue :rose:

**Comment by basarat** [comment]
@tomitrescak can you share a sample ... Would save me some time as another user had the same issue 🌹

**Comment by tomitrescak** [comment]
Dears, unfortunatelly it only happened in that given verision of Atom Typescript.
I tried to replicate in console but no luck. Am glad that someone else experience the same issue so that I'm not crazey ... ;)

<img width="527" alt="screen shot 2015-10-06 at 20 03 22" src="https://cloud.githubusercontent.com/assets/2682705/10304500/5743501a-6c66-11e5-99e2-a69ca3900db5.png">

**Comment by Chocoloper** [comment]
Hello I got the same problem.
I'm using tsc 1.6.2 in terminal which is compiling fine but using atom-typescript 7.6.3 with the following tscconfig doesn't compile correctly to es6 (require instead of import):
```
{
    "version": "1.6.2",
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es6",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noLib": false,
        "outDir": "build"
    },
    "filesGlob": [       ...many.....    ],
    "files": [  ....many.....   ],
    "exclude": []
}
```

Previously it worked with an older version of atom-typescript on my laptop. On my pc i'm still using 7.4.3 and everything works fine.

**Comment by basarat** [comment]
Note: @Chocoloper tried with the command line (same version of ntypescript) and it works fine :-/

@Chocoloper can you share some simple files for my testing

**Comment by Chocoloper** [comment]
I made a small example. Take a look at the readme too see which versions I used and what the output was:
http://plnkr.co/edit/3ASb6cjkKf2CUJwhpp3p

**Comment by basarat** [comment]
@Chocoloper Cheers. I have a repro 

![image](https://cloud.githubusercontent.com/assets/874898/10836910/880ff4a6-7f07-11e5-9c6c-94a78e9eef1f.png)

I suspect its because of a recent change where ES6 module compilation and ES6 general compilation were split (I think I saw an issue or PR regarding this but search is failing me). 

In any case the sample project : https://github.com/TypeStrong/atom-typescript-examples/tree/master/bugs/643 if save in atom-ts a.js comes out with `require` instead of `import from` (since target is es6)

**Comment by basarat** [comment]
I've double checked that we are passing the right options to the language service: 

![image](https://cloud.githubusercontent.com/assets/874898/10840523/33793128-7f34-11e5-9e14-e4c841e84506.png)

`2` is ES6:

```ts
    enum ScriptTarget {
        ES3 = 0,
        ES5 = 1,
        ES6 = 2,
        ES2015 = 2,
        Latest = 2,
    }
```

**Comment by weswigham** [comment]
I see `module` is set to 1, though - and that would be commonjs.

**Comment by basarat** [comment]
> I suspect its because of a recent change where ES6 module compilation and ES6 general compilation were split (I think I saw an issue or PR regarding this but search is failing me).

Found it : https://github.com/Microsoft/TypeScript/pull/4811

> I see module is set to 1, though - and that would be commonjs.

@weswigham thanks for spotting that :rose:  I'll fix it.

@Chocoloper Use `"module": "es6",` as a quick workaround : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.7.0 

```json
{
    "transpiler": "typescript",
    "compileOnSave": true,
    "compilerOptions": {
        "target": "es6",
        "module": "es6",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noLib": false,
        "outDir": "build"
    }
}

```

**Comment by basarat** [comment]
From @tomitrescak's original comment 

> The worst part is, that it breaks the TSX transpilation as for example

would still be a bug if one does want to target ES6 but transpile modules to commonjs (perhaps others also) :rose:

**Comment by weswigham** [comment]
I think that bug is specific to the JSXClosingTag, by the looks of it. The rest of the example is correct. Possibly a kind of regression of what #4096 fixed?

**Comment by mhegazy** [comment]
@basarat is this still an issue?

**Comment by basarat** [comment]
@mhegazy nope, thanks! :rose:

**Comment by mhegazy** [comment]
thanks!
