### ISSUE TITLE
Expand JSDoc typedefs in return type

### ISSUE THREAD

**Issue by CostachescuCristinel** [microsoft/TypeScript#51121]
I usually have JSDoc `typedef`s declared away from the using point (often in separate, external files), and reused multiple times.

However, when using them like this, the VSCode JSDoc/intellisense popup description will include the exact name of the declared type - hiding away all that type's internals.

This is basically useless because requires people to lookup manually that typedef (consider when importing an API), before getting a sense of what is what.  
Consider the following code, and the information in the popup:

```javascript
/**
 * @typedef {{
 *   login: {
 *     user: User,
 *     token: string
 *   }
 * }} LoginResult
 */

/**
 * Logs-in users into their account
 * @param username {string} The username of the user account
 * @param password {string} The password of the user account
 * @returns {GraphQLPromise<LoginResult>} An object with `user` and session `token` details
 */
export function login(username, password) {
  // ...
}
```
<img width="543" alt="Screenshot 2022-10-09 at 18 46 13" src="https://user-images.githubusercontent.com/52235106/194766317-be61bf97-0112-4f96-9118-91e3baa7190c.png">

This does not happen if the return type is explicit in the `@return` declaration:

```javascript
/**
 * Logs-in users into their account
 * @param username {string} The username of the user account
 * @param password {string} The password of the user account
 * @returns {GraphQLPromise<{
 *   login: {
 *     user: User,
 *     token: string
 *   }
 * }>} An object with `user` and session `token` details
 */
export function login(username, password) {
  // ...
}
```
<img width="544" alt="Screenshot 2022-10-09 at 18 45 53" src="https://user-images.githubusercontent.com/52235106/194766330-8f9316fd-611e-42b6-95b0-5f5d9c449a94.png">

The examples above involve return types, but function parameter types are affected as well - and very often it is annoying to have to check them manually.

Is it possible to instruct VSCode to expand the types, at least at the root level? I basically want the second type of popup, no matter how the types are declared (inline, or as typedefs). 

Does VSCode already include some setting for this that I am not aware of?

**Comment by RyanCavanaugh** [comment]
There isn't currently a way to do this.

The preference for showing type names is that it's often the case that the structural expansion is less useful due to being unacceptable large, plus if you want to refer to the *same* type in the consuming code, knowing its name is more useful than trying to copy over its structural expansion.

**Comment by CostachescuCristinel** [comment]
Thank you for your answer and fast consideration!
However, I have to respectfully disagree with you. I actually believe that the reasons why structural expansion should happen are more useful than the counter-arguments for it:

1. As a developer using typed APIs (TypeScript/JSDoc), you are much more interested into the fields that type provides, not what that type is named. If the APIs accept an object parameter, I am pretty sure you want to copy that type's structure to make your own object.  
```javascript
/**
 * @typedef {{
 *   firstName: string,
 *   lastName: string,
 *   dateOfBirth: string,
 *   address: string
 * }} UserData
 * 
 * @typedef {{
 *   purchasedItems: [{ id: string, quantity: number }],
 *   deliverAllInOnePackage: Boolean,
 * }} DeliveryOptions
 * 
 * @typedef {{
 *   data: { purchaseItems: boolean },
 *   errors?: [{ message: string }]
 * }} PurchaseResultResponse
 * 
 * @param {UserData} user
 * @param {DeliveryOptions} deliveryOptions
 * @returns {Promise<PurchaseResultResponse>}
 */

function someAPI(user, deliveryOptions) {
	/* ... */
}
```
<img width="641" alt="Screenshot 2022-10-11 at 22 17 10" src="https://user-images.githubusercontent.com/52235106/195179898-5ec5de3f-42de-4fc5-ae89-8d00c18a958c.png">

The API information here gives absolutely 0 hints as to what the function parameters are made of, or what the returned result looks like. You are then forced to start typing a function call to that API, and checkout the fields in the suggestions/autocomplete popup before you can discover them:

<img width="399" alt="Screenshot 2022-10-11 at 22 30 33" src="https://user-images.githubusercontent.com/52235106/195181815-b52d8ff2-25f1-4db6-8033-8429e0304a98.png">
Compare the above with the ones below, if the root type was expanded, and you hovered over the function name or the result variable:
<img width="506" alt="Screenshot 2022-10-11 at 22 35 11" src="https://user-images.githubusercontent.com/52235106/195182854-3a0f5993-2eff-45b6-b3b9-693184367345.png"><img width="639" alt="Screenshot 2022-10-11 at 22 32 33" src="https://user-images.githubusercontent.com/52235106/195182878-c423037d-cf05-4f92-9850-c000c9556beb.png">

2. VScode will automatically trim long types when they exceed a reasonable limit of text length. I would argue that:  
   a) we should rely on the VSCode behavior to keep us sane by limiting such long texts, and
   b) if a type includes over a reasonable number of fields, it is an indicator that maybe the the code needs refactoring

3. I can understand your point in wanting to know the name of the type, as that may be more useful to you if you often deal with writing the actual types or JSDocs. But I also argue here that you don't use the informational popup for this purpose - you already have the type in the JSDoc signature, or TS definition, and you're hovering the mouse cursor over that type's name.

Finally, I am not sure if I explained myself clear enough, maybe this will help better understand:  
- I am asking for **an option to enable this**, not a default behavior. I believe that people would benefit from having this option, while others who are not interested will not even bother checking it.
- I am only asking about structural expansion of the **root type, not that of types used for the fields**.  
In the last screenshot of this post, notice how `[PurchasedItem]` is not expanded, as well as, the `User` type in my previous post. Maybe, the actual title of the thread here should be "Add an option to enable structural expansion of root types"?

Hopefully you'll be able to better understand my point of view, let me know your thoughts.

**Comment by RyanCavanaugh** [comment]
They're obviously both useful, but we have to pick one and changing the behavior back and forth every time someone doesn't like it isn't the right way to do it 😅

VS Code has a stickier Quick Info thing now and I was thinking of posting the suggestion to toggle between nominal and structural views. Please go ahead and file a suggestion issue for that if you like. Thanks!
