### ISSUE TITLE
Augmented enum correctly emitted in declaration, but missing in compiled code

### ISSUE THREAD

**Issue by jahudka** [microsoft/TypeScript#51134]
# Bug Report

### 🔎 Search Terms

enum, augmentation, extend

### 🕗 Version & Regression Information

Happens on v4.8.3.

### 💻 Code

Package `xyz` contains the following declaration:

```typescript
export enum Foo {
  A = 'a',
  B = 'b',
}
```

I can have the following in my application code:

```typescript
declare module 'xyz' {
  export enum Foo {
    C = 'c',
  }
}
```

### 🙁 Actual behavior

During compilation `Foo.C` is considered a valid case of the enum - meaning that on the type level the augmentation works - but the declaration in my application code doesn't emit anything, so in runtime code `Foo.C` is undefined.

### 🙂 Expected behavior

I'd either expect enum augmentation to be forbidden by the compiler, or to emit the appropriate code to augment the enum. Actually, the code into which enums compile would already work without any changes, because it reuses and alters any existing value at the point it is executed. But I'd understand why augmenting enums in this way might be considered a bad idea (there's no guarantee that the code augmenting the enum will imported at the appropriate time) - I just think that the type system should be consistent with that.

### Further notes

I've also tried importing the enum from package `xyz`, augmenting it and then re-exporting it, but this gives various other errors:

```typescript
import { Foo } from 'xyx'; // TS2440: Import declaration conflicts with local declaration of 'Foo'.

export enum Foo { // TS2395: Individual declarations in merged declaration 'Foo' must be all exported or all local.
  C = 'c',
}
```

```typescript
export { Foo } from 'xyx'; // TS2484: Export declaration conflicts with exported declaration of 'Foo'.

export enum Foo {
  C = 'c',
}
```

The last one is especially curious, because as far as the compiled code is concerned, this would totally work exactly the way you'd expect - if you import `Foo` from `xyz`, it won't contain `C`, but if you import it from this module, it will.

**Comment by RyanCavanaugh** [comment]
The `declare` modifier means "I, the developer am telling you, TypeScript, about a *thing which exists*". `declare`d things don't have associated emit.

**Comment by jahudka** [comment]
@RyanCavanaugh ok, seems logical. Sounds like my use-case can be solved by turning the enum into a `const enum`, which doesn't emit anything. I'll go that route for now. Thanks!
