### ISSUE TITLE
Typescript can not recognize indexed type properly

### ISSUE THREAD

**Issue by GuichiZhao** [microsoft/TypeScript#51147]
type X = {
      aa: string;
      bb: number;
    };
    
    const get = <Key extends keyof X, Value extends X[Key]>(
      key: Key,
      value: Value | ((v: Value) => Value)
    ) => {
      let newValue: Value;
      const x: X = {
        aa: '11',
        bb: 11
      };
      if (typeof value === 'function') {
        //Argument of type 'X[Key]' is not assignable to parameter of type 'Value'.
        newValue = value(x[key]);
      } else {
        newValue = value;
      }
    };

Why "Argument of type 'X[Key]' is not assignable to parameter of type 'Value'."? In my opinion, `X[Key]` is exactly what `Value` is defined, how come it is **not assignable**? From a human being's view i.e. I calculate the type myself, there is no way to get the type wrong, why typescript can not tell?

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

The error is correct, because this is a valid invocation of your function:

```typescript
get<'aa' | 'bb', string | number>('aa', 1)
```

**Comment by GuichiZhao** [comment]
I see someone comment like `get<'aa' | 'bb', string | number>('aa', 1)` is a valid invocation
I ignore the fact that `'aa' | 'bb'` is a valid for `extends keyof X`. My initial intention is to pass no generic param and use typescript to enforce the constraint. I did not check the case where generic param can be pass through
