### ISSUE TITLE
bug(d.ts): does not allow simple computed properties on declared classes

### ISSUE THREAD

**Issue by EisenbergEffect** [Microsoft/TypeScript#5114]
The error "A computed property name in an ambient context must directly refer to a built-in symbol." is produced by the following code in the aurelia-templating-binding.d.ts file.

```
declare module 'aurelia-templating-binding' {
  export class SyntaxInterpreter {
    ['one-time'](resources: any, element: any, info: any, existingInstruction: any): any;
  }
}
```

This code works fine in the TypeScript playground when used normally in a class, but not inside a declaration. This is a problem for us since it means we can't generate complete d.ts files for our api and also cannot generate the docs (which are based on the d.ts files).

**Comment by RyanCavanaugh** [comment]
I think you want to write this instead:
```ts
declare module 'aurelia-templating-binding' {
  export class SyntaxInterpreter {
    'one-time'(resources: any, element: any, info: any, existingInstruction: any): any;
  }
}
```
The bracketed syntax shouldn't be used for statically-named things

**Comment by EisenbergEffect** [comment]
@RyanCavanaugh  Is that a TypeScript-specific syntax rule? because it is valid ES6. Can you emit the brackets with ES6 too? or is this a divergence between ES6 and TypeScript.

**Comment by weswigham** [comment]
Actually method declaration with a string without square brackets is still valid es6, but not supporting square brackets in type definitions for any other primitives than symbols is a known limitation and has been discussed in #4653 (most recently, AFAIK).

**Comment by danquirk** [comment]
Yeah I think we can close this as a dupe
