### ISSUE TITLE
lib.dom.d.ts - DisplayMediaStreamConstraints is missing cursor property

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#51143]
The Type definition for DisplayMediaStreamConstraints is wrong.

It is missing "cursor" on the video property.
see:
https://udn.realityripple.com/docs/Web/API/MediaTrackConstraints/cursor

When I look at the type:

        interface DisplayMediaStreamConstraints {
            audio?: boolean | MediaTrackConstraints;
            video?: boolean | MediaTrackConstraints;
        }

I think the constraints for audio & video should be different.

**Comment by jogibear9988** [comment]
Oh, I think I've now found this api is not yet final.

**Comment by MartinJohns** [comment]
See: https://github.com/microsoft/TypeScript-DOM-lib-generator/#when-the-type-is-missing

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
