### ISSUE TITLE
Narrowing doesn't occur when using "in" operator

### ISSUE THREAD

**Issue by govindrai** [microsoft/TypeScript#51154]
# Bug Report

### 🕗 Version & Regression Information

When did you start seeing this bug occur?
I'm using TS 4.8.4. I recently started using typescript, so I haven't seen this before. 

I tried to test previous versions in the playground but I was unable to test because I wasn't able to get the typescript playground to work in a "node" environment (i.e. it doesn't recognize node globals, I got errors like `Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.(2580)` but wasn't sure how I could install those types into the playground)

### ⏯ Playground Link
I couldn't get the playground to recognize the node environment so process is not a recognized global..
[Playground link with relevant code](https://www.typescriptlang.org/play?&q=81#code/PTAEBUAsEsGdQCYHsCmsB2ByALqFAnfJfAWACgAzAV3QGNtol091Yr8UBRdANwDUAhvlicAHnGwAKAJQAuUAGVs+aOgDmoAN7lQu0NAqhJAByK00sAHQpel1bGwC6KAJIIbDCtALStOvQEc2OzMpkjmsFY2PHasjs5uHgbepGQBAL54ADawKH5pAXrYkEQA7qDoKOWchMSSAEQAsnC0TF5q7CgIoNw80EToALYe9dL+uunkk2TkIBAw8PgCcGgQAJ7GeZgOKuqgAD6gNO5elQiY+vDoSLgCkdBq6AIARll52Eig2BtbSrtqmEs-nAP1AmGOKFOXQucAqN1Ad1gDyer3en2+mzBf1UAKBlBo9EYzBsbA4vUEwjEEgATDJ5Ni9toCroDEZ6vZ4uZEuhPCl6vpQmYLNZeL4mYU9EEQqAwhEorYOU4ue4eckCONQJkUDk8uKJV8SkhypVqrV8A1mrBWuh2p1ur1+kxhjzRhrptMgA)

### 💻 Code
```javascript
// This doesn't error
function ensureEnvVarsExist(): String {
    if (process.env.instanceIdentifier) {
        return process.env.instanceIdentifier
    } else {
        throw new Error("Misconfigured Environment")
    }
}

// This raises Type 'string | undefined' is not assignable to type 'String'. Type 'undefined' is not assignable to type 'String'.ts(2322)
function ensureEnvVarsExist2(): String {
    if ("instanceIdentifier" in process.env) {
        return process.env.instanceIdentifier
    } else {
        throw new Error("Misconfigured Environment")
    }
}
```

### 🙁 Actual behavior

The latter function produces a typescript error.

### 🙂 Expected behavior

I expect both to narrow in the same way and not produce an error.

**Comment by MartinJohns** [comment]
Don't use `String`, use `string` instead. Also, `instanceIdentifier` is typed `string | undefined`. So, while the property may exist (which `in` checks for), it may be set explicitly to `undefined`.

**Comment by RyanCavanaugh** [comment]
`process.env` is defined as `[s: string]: string | undefined`, so this is the expected behavior

**Comment by govindrai** [comment]
Ah, I see.. learning lesson. Thanks folks!
