### ISSUE TITLE
`quick fix` to fill in missing properties not available on mapped type

### ISSUE THREAD

**Issue by snowpuddles** [microsoft/TypeScript#51163]
# Bug Report

### 🔎 Search Terms

"quick fix mapped type" "add missing properties mapped type"

### 🕗 Version & Regression Information

- Based on changing version with the playground below, `4.5+` when `quick fix` was added
- Behavior is still present on `Nightly`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM7AQFQJ4AOEA3gLABQyyIArgLYBGAXNfQ9ADQVUhx0QsMYKKADmXcgF8KMGiARhgAexDJIQgBRwW6LLkIQAlIOFiylZFAhgaUVXAB0vfgG4K08gHpPOABbAMZF9MZDhkAAMARxpsAGtkGGAAD3C1JQTgABtM5FBkOgCsEFFkAiglAgwOZABGAAZPeooEFSFkADc4HIBeNQhNYklDCgpvMfGJyanpmdm5+bGKUEhYRBQAeTBfaHwicyoGJSVMlkPjiDgQdyXwaHgkZABZOAICMV2SbmQGTGwdX-0RAkVCUW2gLE22ygH2u5Fk8kUKj6QgATAAeHDICBJSAgAAmgViEDwShgTxeb2KHwAfBowAYWDhqkoGAArFjPV7vAwAbRwAF1jEIRMV9pZrLZVAAiOBQBjAYSyvBS2HePwBZAAaQAcusAOoAZVyYECumwH2+NDAyDxSn61FByFJMGgEWicQyKQA-D7kBg+CgcAaUQBmAAsAFZmq1rZ1MijkL11GAURopT89FKOINDC4gA)

### 💻 Code

_See playground link for full example._
```ts
interface BasicType{
  numb: number,
  name: string,
}
interface OtherType{
  bool: boolean
}
interface MappingType{
  basic: BasicType,
  other: OtherType
}
function test2<T extends keyof MappingType>(type: T, obj: MappingType[T]):string{
  return "arbitrary"
}
//TS2345, understands `obj` is of type `BasicType`, `quick fix` not available
const val2 = test2("basic",{});
```

### 🙁 Actual behavior

- TS-2345 for both lines in the playground.

- `quick fix` is available for function call using type directly.

![image](https://user-images.githubusercontent.com/40185475/195655416-5e6fb1d8-3d38-4d41-a6a8-af1fd82b37a7.png)

- `quick fix` is not available for function call using mapped type even though TS does understand its type.

![image](https://user-images.githubusercontent.com/40185475/195655298-c70cc4c8-3873-475b-8706-a61e095f91e9.png)

Error message is the same for both:
```
Argument of type '{}' is not assignable to parameter of type 'BasicType'.
  Type '{}' is missing the following properties from type 'BasicType': numb, name(2345)
```

### 🙂 Expected behavior

- TS-2345 for both lines in the playground.
- `quick fix` for TS-2345 to "add missing properties" to be available on both empty function call parameters.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by RyanCavanaugh** [comment]
I believe this is a new speed record for community reported -> community fixed -> team merged??

**Comment by snowpuddles** [comment]
I'm incredibly impressed and thankful. ❤️ 

Especially for something super minor.
