### ISSUE TITLE
Typing ; replaces ()

### ISSUE THREAD

**Issue by roblourens** [microsoft/TypeScript#51169]
![Recording 2022-10-13 at 09 10 10](https://user-images.githubusercontent.com/323878/195649308-8d32ab3d-357b-4eea-94c9-9a7e8913ba80.gif)

- Type `()` to call a method
- Type `;`
- The `()` are replaced

Any idea what's going on here?

**Comment by mjbvz** [comment]
@roblourens Can you share some repo steps in the VS Code repo? I was seeing this pretty often yesterday but no longer seem to hit it

**Comment by roblourens** [comment]
Sorry, it was happening reliably here https://github.com/microsoft/vscode/blob/73e6a7e3d2eeca422018c212e83bcd6bcbdbe7a7/src/vs/workbench/contrib/notebook/test/browser/notebookExecutionStateService.test.ts#L104 and today it is not happening anymore
