### ISSUE TITLE
New Website Logo: Everlaw

### ISSUE THREAD

**Issue by aflevin** [Microsoft/TypeScript#5117]
Name: Everlaw
Homepage url: http://everlaw.com
Brand Guidelines/Licensing: N/A
Logo: http://everlaw.com/images/everlogo.png

**Comment by jeffrey-easyesi** [comment]
@aflevin @ajshankar Do we want this logo or the one in https://github.com/Microsoft/TypeScript/issues/5081?

**Comment by RyanCavanaugh** [comment]
Closing in favor of #5081
