### ISSUE TITLE
useDefineForClassFields/MinifyFriendly - fix object property minification / mangling

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#51178]
# Suggestion

## 🔍 Search Terms
useDefineForClassFields Terser property mangling minify properties

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a new flag (let's say `useDefineForClassFieldsMinifyFriendly`) which would change the behaviour of `Object.defineProperty` declarations as part of `useDefineForClassFields` that would be compatible with Terser (or other minifier) object property mangling.

So instead of

```js
Object.defineProperty(this, "foo", {
  enumerable: true,
  configurable: true,
  writable: true,
  value: 100,
});
```

do

```js
Object.defineProperty(this, Object.keys({ foo: undefined })[0], {
  enumerable: true,
  configurable: true,
  writable: true,
  value: 100,
});

```

or a more performant solution than Object.keys, if available.

This new `useDefineForClassFieldsMinifyFriendly` flag would be disabled by default.

## 📃 Motivating Example and Use Case

With the way it currently works, there's no way to minify / mangle class properties. Minification works so long as no string literals are used and the `useDefineForClassFields` flag breaks it.

**Comment by MartinJohns** [comment]
Why not make Terser understand the pattern instead of wanting to add yet another compiler flag?

**Comment by mckravchyk** [comment]
This could never be implemented in a sane way on Terser level, unless we are talking about mangling all string literals in the code, which is quite a different (hypothetical) feature than object property mangling and is actually undesired, as it greatly increases the surface of things that will be mangled, possibly introducing mistakes.

The second argument to `Object.defineProperty` is just a variable. A variable cannot be evaluated statically by Terser. The best that could be done is something like:
- Mangle the second argument to Object.defineProperty if it's a string literal

but it's just too messy. Besides inconsistency with variables, what if I make an alias for Object.defineProperty. This just does not feel right, as it's trying to make a static change to something which is a runtime feature. I would definitely not classify it as a Terser bug / missing implementation. Terser is pushing it to the limit with property mangling and the only step further from that would be string literal mangling, which again, may be undesirable.

**Comment by mckravchyk** [comment]
Ok, sorry. I guess I learned a lesson. I evaluated it theoretically but I did not bother testing if that's really the case. For whatever reason, I get minified literals in the output and it works. I don't know why yet. I will see what's going on and close the issue if everything is clear.

**Comment by mckravchyk** [comment]
Yes, despite Terser documentation saying:

> Avoid calling functions like defineProperty or hasOwnProperty, because they refer to object properties using strings and will break your code if you don't know what you are doing.

Terser will mangle string literals on Object.defineProperty

```
const o = { }

Object.defineProperty(o, 'mangleMe');
console.log(o.mangleMe);

const alias = Object.defineProperty;
alias(o, 'wontBeMangledInLiteral');
o.wontBeMangledInLiteral = 3;
```

Output:
`const o={};Object.defineProperty(o,"o"),console.log(o.o);const alias=Object.defineProperty;alias(o,"wontBeMangledInLiteral"),o.l=3;
`

so it's working like you suggested it should and there's no issue. I was pretty sure it's not the case when I looked at documentation and thought it's something that would not be implemented, but it turns out it is. Lesson learned to test everything first and not make theoretical assumptions :)

**Comment by MartinJohns** [comment]
> The second argument to `Object.defineProperty` is just a variable. A variable cannot be evaluated statically by Terser.

There's a difference between passing a variable and a string literal. The latter can absolutely be evaluated statically.

**Comment by mckravchyk** [comment]
Yes, agreed. I assumed it would be weird for Terser to do it like that though, but it does it and I'm glad. I guess mangling property names is a danger zone anyway and that's no place for perfect solutions, but whatever is most practical.
