### ISSUE TITLE
Type incompletion in FontFaceSet

### ISSUE THREAD

**Issue by unanmed** [microsoft/TypeScript#51185]
Missing types:
```ts
size: number
add: (font: FontFace) => FontFaceSet
clear: () => void
delete: (font: FontFace) => boolean
entries: () => Iterator<[FontFace, FontFace], undefined>
has: (font: FontFace) => boolean
keys: () => Iterator<FontFace, undefined>
values: () => Iterator<FontFace, undefined>
```

**Comment by MartinJohns** [comment]
You forgot to fill out the [issue template for lib change requests](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/lib_change.md).

`FontFaceSet` already has these types provided. You need to include the lib `dom.iterable`.

**Comment by unanmed** [comment]
> You forgot to fill out the [issue template for lib change requests](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/lib_change.md).
> 
> `FontFaceSet` already has these types provided. You need to include the lib `dom.iterable`.

Oh, I got it. Thanks
