### ISSUE TITLE
child resolution generic type not working

### ISSUE THREAD

**Issue by SrHuevo** [microsoft/TypeScript#51189]
# Bug Report

### 🔎 Search Terms
`child typing`

### 🕗 Version & Regression Information
- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECqEFMBO0DeAoAkABwK4CMQBLYaAOzAFsEAuaCAFySLIHNoBeaAcm6z0Il6uJBWp1GzNpx58cBYqTCta5XJXzIZARnQBfdKEgwAggBMzSBFDT8FQyQgQMJTFuy687g0tgD2jADCfmaqku4yXgaG4DYAYkQgDMgAPAAqAHxo0UbxiclIAKIAjrhgIOkANNAA0tAIAB7JZGYwANYIAJ5+AGbQmfVNCC0wCUmpAxiYwH5kkrjADH5IABQ9RAggZnQ11QKK0ABu5biqaQDaNQC6AJS2mJgQuNjIKzdYBjmxMIHMBURgdJZKYzOZMBZLVbrcZICB0MYFIHnW7ZfToGLGOCIJAAJQQ-ggREhnXu+wcCDASGAAAsVsA-sgAXRfkTGYD4MgMjc6BykMiMNBBULBVYGCIyNBzmQEAB3LGvG5XADc6GFn3RoMY0Fw2LxBKJyxJXGlct5eoCBqQnTe6B1yHNhOJADpEJSaSssCboCz-mAVlLZdAEcgSmUKuZLNYINVuI5nNwMitY0wnAxuDHuIqbpV0O8gA)

### 💻 Code
```ts
class User {
	public name: string = ''
	public surname: string = ''
	public age: number = 1
}
class Address {
	public street: string = ''
	public postCode: string = ''
}

class Filter<T> {}

class FilterEqual<T, K extends keyof T> extends Filter<T> {
	constructor(field: K, public value: T[K]) {
		super()
	}
}

class Criteria<T> {
	constructor(filters: Filter<T>[]) {}
}

class UserRepository {
	public search(criteria: Criteria<User>): User[]{
	        return [new User()];
	}
}

const userRepository = new UserRepository()
userRepository.search(
	new Criteria([new FilterEqual<Address, 'street'>('street', '')]),
)
```

### 🙁 Actual behavior
Typescript does not catch the error when a userRepository is passed a criteria with a street filter instead of users

### 🙂 Expected behavior
Typescript should report as an error if the user repository is sent a filter other than users

### Disclaimer 
I'm sorry for the chosen title, I really don't know how to explain this in one sentence, if someone comes up with a better title I will gladly change it

**Comment by MartinJohns** [comment]
> Typescript does not catch the error when a userRepository is passed a criteria with a street filter instead of users

Because this is valid. They're the same type.

From the FAQ: [Why is `A<string>` assignable to `A<number>` for `interface A<T> { }`?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at--)

**Comment by SrHuevo** [comment]
I'm sorry I do not understand it. I am using the types in the constructor, in fact I have tried to create a function that uses them too but the error still does not come out. In the documentation it says that the behavior is for not using them and in the example, indeed, they are not used

```interface Something<T> {
  name: string;
}
```

I have modified to:
```
class FilterEqual<T, K extends Extract<keyof T, string>> extends Filter<T> {
	constructor(private field: K, private value: T[K]) {
		super()
	}

    convert() {
        return `$eq('${this.field}', ${this.value})`
    }
}
```
But the behavior is the same.

I think I'm getting it wrong, could you tell me what I should do?

**Comment by MartinJohns** [comment]
> I have modified to:

That's not enough, because the other types are still compatible. `Filter<User>` is the same as `Filter<Address>`, and `Criteria<User>` is the same as `Criteria<Address>`. You must make all the types incompatible.

[Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAECqEFMBO0DeAoAkABwK4CMQBLYaAOzAFsEAuaCAFySLIHNoBeaAcm6z0Il6uJBWp1GzNpx58cBYqTCta5XJXzIZARnQBfdKEgwAggBMzSBFDT8FQyQgQMJTFuy687g0tgD2jADCfmaqku4yXgaG4DYAYkQgDMgAPAAqAHxo0NjMAG5gydAA+gwAhHRp0NFG8YnJSACiAI64YCDpADTQANLQCAAeyWRmMADWCACefgBm0Jn9QwgjMAlJqQsYmMB+ZJK4wAx+SAAUuUQFRTNECCBmdD3d55cI0AUguKppANo9ALoASlsmEwEFw2GQJwBWAMNViMECzAaRDA6SyWx2eyYByOp2ehVe13WSAgdDWDTR30BaFh6BixjgiCQACUEP4IERcZNgQJFPQEGAkMAABYnYBI5AouiIzmS1HwZAZAF0BVIKkYaCarWaqwMERkaDfMgIADujMhAL+AG50NraYZdoxoLgmaz2ZzjtyuMazaq3QEPUhJlD0C7kP6OVyAHSIQUik5YH3QGXIsAnI2m6Dk5AtNodcyWawQbrcRzObgZE6lphOBjcEvcS0AzroaFAA)

**Comment by fatcerberus** [comment]
For the record: constructor parameters don’t play into the type of a class.

**Comment by MartinJohns** [comment]
For the record to the record: [Parameter properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties) of constructors do play into the type of a class.

**Comment by fatcerberus** [comment]
Yeah, I thought of that after I said it, hence my rephrasing edit. :wink:  Technicalities…

**Comment by SrHuevo** [comment]
Thank you so much, now, I understand everoything, I forgot the Filter class!

I'm sorry I made you waste your time
