### ISSUE TITLE
tsconfig.json: Specify <root> in "include" and "exclude" for extends configs

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript#51213]
# Suggestion

As always, thanks again for all of your hard work on the TypeScript tooling and ecosystem! 🙌

Extends configs (configs referenced from `"extends"`) can specify `"include"` and `"exclude"`, but they are relative to the `tsconfig.json` file (which could be deep in `node_modules`) instead of the root of the directory, per the [`include` docs](https://www.typescriptlang.org/tsconfig#include):

> These filenames are resolved relative to the directory containing the `tsconfig.json` file.

This means that the following configuration would not work as expected:

**`tsconfig.json`**

```json
{
  "extends": "@upleveled/eslint-config-upleveled/templates/tsconfig.json"
}
```

**`node_modules/@upleveled/eslint-config-upleveled/templates/tsconfig.json`**

```json
  "include": [
    "**/.eslintrc.cjs",
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "**/*.cjs",
    "**/*.mjs"
  ],
```

(this would resolve relative to the `node_modules` deep path, which would be useless)

Removal of such broken config can also be seen in the wild here: https://github.com/tsconfig/bases/pull/41

## Suggestion 1: `<root>` directory specifier

It would be great to get a `<root>` capability to add to `include` and `exclude` paths to refer to the directory with the `package.json` file, like [Jest's `<rootDir>` option](https://jestjs.io/docs/configuration#rootdir-string):

```json
  "include": [
    "<root>/**/*.ts"
  ]
```

## Suggestion 2: `tsconfig.ts`

Another idea for implementation would be to have a code-based config (ideally `tsconfig.ts`, as @weswigham mentions in https://github.com/microsoft/TypeScript/issues/20110) - I'm guessing this would open up alternative ways to retrieve the root directory of the project.

Allowing TS / JS configs is a common pattern in developer tooling, and covers many use cases beyond this issue.

## 🔍 Search Terms

extends, extended, root directory, root folder, configs, tsconfig

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

In the description above

## 📃 Motivating Example

In the description above

### Workaround

Specify the paths using relative paths:

```json
  "include": [
    "../../../../**/.eslintrc.cjs",
    "../../../../next-env.d.ts",
    "../../../../**/*.ts",
    "../../../../**/*.tsx",
    "../../../../**/*.js",
    "../../../../**/*.jsx",
    "../../../../**/*.cjs",
    "../../../../**/*.mjs"
  ],
```

But here this encodes the directory structure of `node_modules` into the config as well, which is brittle.

**Comment by MartinJohns** [comment]
Related: #37227

**Comment by fatcerberus** [comment]
Using `include` in an `extends`’d config seems useless in general (or at least highly situational) because according to the docs:

> It’s worth noting that [`files`](https://www.typescriptlang.org/tsconfig/#files), [`include`](https://www.typescriptlang.org/tsconfig/#include) and `exclude` from the inheriting config file *overwrite* those from the base config file

**Comment by MartinJohns** [comment]
Related: #20110

**Comment by karlhorky** [comment]
> Using `include` in an `extends`’d config seems useless in general (or at least highly situational)

@fatcerberus Consider projects which do not need to update the config in the extends (eg. they just want to include all files of all extensions). These projects can be very common in situations where:

1. Companies create multiple projects based on their "boilerplate", with no customizations needed for `include` or `exclude`
2. Students create multiple projects based on a programming boilerplate, with no customizations needed for `include` or `exclude` (this is our use case)

So actually it would be best to have some feature to allow for merging from the extended config (ideally `tsconfig.ts`, as @weswigham mentioned - allowing TS / JS configs is a common pattern in developer tooling, and very useful):

- https://github.com/microsoft/TypeScript/issues/20110

But I think @mhegazy is against a code-based config `tsconfig.ts`

**Comment by nzaero** [comment]
I am using a monorepo, there is no way to control the output of relative file, I mean inclue, exclude, outdir, all of them are relative to the base conf. What I need is to have a base conf, that have settings that applies relatively to the current project. 
I do not have inheritence working for files's outputs with tsconfig.

**Comment by karlhorky** [comment]
Thanks @sheetalkamat for implementing the `${configDir}` template variable 🎉🚀

- Issue: https://github.com/microsoft/TypeScript/issues/57485
- PR: #58042
