### ISSUE TITLE
Go-to-definition on `await`/`yield` should probably jump to the containing respective async function/generator

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#51223]
Similar to #51222.

```ts
async function outerAsyncFun() {
  let af = /*END*/async () => {
    /*START*/await Promise.resolve(0);
  }
}
```

```ts
function* outerGen*() {
  /*END*/function* gen() {
    /*START*/yield 100;
  }
  return gen
}
```

We should probably do nothing in cases like top-level `await`, or where `await` does not have a direct corresponding `async` function, and `yield` does not have a direct corresponding generator.

**Comment by fatcerberus** [comment]
I would expect GTD on `await` to jump to the `async` keyword of the containing function, in line with how e.g. C# intellisense highlights the `async` keyword (and incidentally, all the other `await`s in the same function) when you place the cursor on an `await`.

**Comment by DanielRosenwasser** [comment]
I guess maybe there's a catch with

```ts
class Foo {
  /*END1*/public /*END2*/async yadda() {
    /*START*/await 10;
  }
}
```

I feel like the distance is not that big that it matters whether we pick `END1` or `END2`. I could go both ways.

Thinking about it some more, I wonder if it makes sense to always make the go-to-definition succeed, even if the containing function isn't async or a generator. If you're in the error case, it can be helpful to jump to whichever function contains the keyword.

**Comment by DanielRosenwasser** [comment]
Also, another fun test case.

```ts
function* gen() {
  class C { [yield 10]() {} }
}
```
