### ISSUE TITLE
Go-to-definition on `return` statements should jump to the containing function declaration

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#51222]
```ts
function foo() {
    return /*END*/() => {
        /*START*/return 10;
    }
}
```

Go to definition on `START` should jump you up to the containing function.

It should be resilient to questionable placements of `return` and do nothing, as in the following cases.

```ts
/*a*/return;


function foo() {
    class Foo {
       static { /*b*/return; }
    }
}
```

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!

**Comment by sheetalkamat** [comment]
@DanielRosenwasser Suggestion, we probably can get find all references to show all return statements and signature?

**Comment by DanielRosenwasser** [comment]
Agreed, I was thinking this last night too!

**Comment by DanielRosenwasser** [comment]
@sheetalkamat, I filed #51232 for that. I think the big question is whether it should just return whatever document highlights returns, or it should return a more-curated list.
