### ISSUE TITLE
Missing source map mapping for `return` keyword in single-statement lambda output

### ISSUE THREAD

**Issue by jvilk** [Microsoft/TypeScript#5122]
TypeScript 1.6.2 will fail to emit a source map mapping from the `return` keyword in the generated JavaScript back to a single-statement lambda *if* that lambda spans multiple lines.

Minimal test case:

```{typescript}
((item: string) =>
    item
)
```

Output with embedded source map / source code:

```{javascript}
(function (item) {
    return item;
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInRlc3QudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsQ0FBQyxVQUFDLElBQVk7V0FDVixJQUFJO0FBQUosQ0FBSSxDQUNQLENBQUEiLCJzb3VyY2VzQ29udGVudCI6WyIoKGl0ZW06IHN0cmluZykgPT5cbiAgICBpdGVtXG4pXG4iXX0=
```

You can reproduce this behavior yourself using that TS file alone; just run `tsc --inlineSourceMap --inlineSources test.ts`.

[Here's a visualization of the above test, demonstrating the missing mapping.](http://sokra.github.io/source-map-visualization/#base64,KGZ1bmN0aW9uIChpdGVtKSB7CiAgICByZXR1cm4gaXRlbTsKfSk7Ci8vIyBzb3VyY2VNYXBwaW5nVVJMPWRhdGE6YXBwbGljYXRpb24vanNvbjtiYXNlNjQsZXlKMlpYSnphVzl1SWpvekxDSm1hV3hsSWpvaWRHVnpkQzVxY3lJc0luTnZkWEpqWlZKdmIzUWlPaUlpTENKemIzVnlZMlZ6SWpwYkluUmxjM1F1ZEhNaVhTd2libUZ0WlhNaU9sdGRMQ0p0WVhCd2FXNW5jeUk2SWtGQlFVRXNRMEZCUXl4VlFVRkRMRWxCUVZrN1YwRkRWaXhKUVVGSk8wRkJRVW9zUTBGQlNTeERRVU5RTEVOQlFVRWlMQ0p6YjNWeVkyVnpRMjl1ZEdWdWRDSTZXeUlvS0dsMFpXMDZJSE4wY21sdVp5a2dQVDVjYmlBZ0lDQnBkR1Z0WEc0cFhHNGlYWDA9,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInRlc3QudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsQ0FBQyxVQUFDLElBQVk7V0FDVixJQUFJO0FBQUosQ0FBSSxDQUNQLENBQUEiLCJzb3VyY2VzQ29udGVudCI6WyIoKGl0ZW06IHN0cmluZykgPT5cbiAgICBpdGVtXG4pXG4iXX0=,KChpdGVtOiBzdHJpbmcpID0+CiAgICBpdGVtCikK) It lacks a source map for the `return` keyword. It *does* map the content of the statement, but not the `return` keyword.

If you remove the line break, [TypeScript appropriately maps the `return` statement to the lambda.](http://sokra.github.io/source-map-visualization/#base64,KGZ1bmN0aW9uIChpdGVtKSB7IHJldHVybiBpdGVtOyB9KTsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9ZGF0YTphcHBsaWNhdGlvbi9qc29uO2Jhc2U2NCxleUoyWlhKemFXOXVJam96TENKbWFXeGxJam9pZEdWemRDNXFjeUlzSW5OdmRYSmpaVkp2YjNRaU9pSWlMQ0p6YjNWeVkyVnpJanBiSW5SbGMzUXVkSE1pWFN3aWJtRnRaWE1pT2x0ZExDSnRZWEJ3YVc1bmN5STZJa0ZCUVVFc1EwRkJReXhWUVVGRExFbEJRVmtzU1VGQlN5eFBRVUZCTEVsQlFVa3NSVUZCU2l4RFFVRkpMRU5CUVVNc1EwRkJRU0lzSW5OdmRYSmpaWE5EYjI1MFpXNTBJanBiSWlnb2FYUmxiVG9nYzNSeWFXNW5LU0E5UGlCcGRHVnRLVnh1SWwxOQ==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInRlc3QudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsQ0FBQyxVQUFDLElBQVksSUFBSyxPQUFBLElBQUksRUFBSixDQUFJLENBQUMsQ0FBQSIsInNvdXJjZXNDb250ZW50IjpbIigoaXRlbTogc3RyaW5nKSA9PiBpdGVtKVxuIl19,KChpdGVtOiBzdHJpbmcpID0+IGl0ZW0pCg==)

**Comment by jvilk** [comment]
I just found a minimal test case; updating description...

**Comment by mhegazy** [comment]
PRs are welcomed.
