### ISSUE TITLE
Public compiler api only has way to set localized messages for language service and not in general

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#51239]
# Suggestion

Currently the LanguageServiceHost allows providing a `getLocalizedDiagnosticMessages(): Record<string, string>` method, which internally calls `ts.maybeSetLocalizedDiagnosticMessages`. I don't see anything in the public API to set this otherwise though (ex. when just using a program and getting diagnostics from that).

## 🔍 Search Terms

localized diagnostics

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Probably expose `ts.setLocalizedDiagnosticMessages`. I'm just using that for now and it works.

## 💻 Use Cases

I want to change the diagnostics that say to install `@types/node` packages to be Deno specific.

**Comment by sheetalkamat** [comment]
Wont you be able to use `validateLocaleAndSetLanguage` to set the correct locale?

**Comment by dsherret** [comment]
I didn't notice that function, but it seems to be possible to use that in a little bit of a roundabout way. I'll close this since it's possible, but the internal `ts.setLocalizedDiagnosticMessages` is much nicer.
