### ISSUE TITLE
extended class with different property type got type reset to base when using mixin

### ISSUE THREAD

**Issue by paul-thebaud** [microsoft/TypeScript#51252]
# Bug Report

### 🔎 Search Terms

- mixin
- parent
- property
- type

### 🕗 Version & Regression Information

Never tried before, so I don't know.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=24&ssc=32&pln=24&pc=50#code/JYOwLgpgTgZghgYwgAgMIHsQggsxPIDeAsAFAC+ZZoksiKAogB6QgAmEbGWOeBELCOwDOaTNlz4QRMpVJk4AI2FgoiMMgQAbOMNEBZdBy0zSyZAAcAroq3AEm8bykBCAFxiekzAG5ZVUiUVNVxNHT1kZlYONkNjU3NrW3tHLz4Qd0jBdk5uCXS-CgDtXVEAVWFoZAFo0SihGLiIExIi+VIAeg7kABUATwsUBHQoKF4tPuQOSFxOZDB0ZAAiepyuJ28QJYA6MmGQYXQtCG2tdABzAApL7AB3ZAroS4BKZ+39-Klnwr3wuuyYo8oNUAeVKsDWnIyF1egMhiMxrgJlMIDNIGx5osVgDcht0js9phDsdThdrncstFOECXm8Ps5MN8AjArCBNpYbHZhAALJTHS5NLSoP4eMBw9AwZCC54JZBBVTqMKlZAABU5wB5fJQNQaBiMzWFyta5kS6ocSS53M4AEEwJlgqBzoVzFCzMgxmArFBpGrkprbBBCq6ShEVegVCDahy-byA5dVo19VoZZCAjD+oNkCB0BphqNxpNprxONtkAARVHFjELZZ5BlbXakfbEk5nK43CD3MMqWnvPFfHxAA)

### 💻 Code

```ts
interface Connection {
}
interface ExtendedConnection extends Connection {
}
abstract class Model {
  public connection!: Connection;
}
abstract class ExtendedModel {
  public connection!: ExtendedConnection;
}

class User extends ExtendedModel {
}
// Type correctly detected to "ExtendedConnection".
console.log((new User()).connection);

function publishable(ModelClass: typeof Model) {
  abstract class Publishable extends ModelClass {
    public publishedAt!: string;
  }

  return Publishable;
}

class Post extends publishable(ExtendedModel) {
}
// Type not correctly detected. Detected to "Connection".
console.log((new Post()).connection);
```

### 🙁 Actual behavior

When declaring a property inside a class and creating a extended version of class with a different type for this property, if the extended class is merged using a mixin, the type detection of mixed class revert to the higher parent one.

### 🙂 Expected behavior

Type of property on mixed class should use the closest parent's one.

**Comment by MartinJohns** [comment]
TypeScript provides the type information you specify. `publishable` accepts and extends a `Model`. It has no information whatsoever when you pass something extending `Model` to it. You'd need to use generics.

**Comment by paul-thebaud** [comment]
Hi @MartinJohns, thanks for your quick reply ! Its working with generics. I think I missed one thing during my tries :cry:

For anyone searching, here's what I changed on the mixin function typings:

```diff
-function publishable(ModelClass: typeof Model) {
+type AbstractConstructor<T> = abstract new(...args: any[]) => T;
+function publishable<M extends AbstractConstructor<Model>>(ModelClass: M) {
  abstract class Publishable extends ModelClass {
    public publishedAt!: string;
  }

  return Publishable;
}
```

**Comment by MartinJohns** [comment]
Thumbs up for posting your solution. 👍
