### ISSUE TITLE
Incorrect return type from function union

### ISSUE THREAD

**Issue by kesupile** [microsoft/TypeScript#51259]
# Bug Report

### 🔎 Search Terms

Incorrect union of function return type, function incorrect union

### 🕗 Version & Regression Information

`v4.8.4` - This is the behaviour in every version I tried, and I reviewed the FAQ for entries about functions and unions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/MYewdgzgLgBAZiEMC8MAUBKFA+dBvGAdwC4YBmAFjIBoYAPUgcgREZgF8MBuAKFElgAjAIYAnFOizJcaAiXJVaDGIxGjGtAJ6k4wgDYQAprQBepAMqaAtoJB60jABaG9e1lk68+4aPEQAhMQk0AFlhKEcAOlFhMAATECtMGFwABkiKGAB+PyRSNQweIuLvARgQAFcoAAcqiRZA0UwigEs4dEZNNhawcqraqCw8HhhRvpqqyJMYAHoZmAAeAFolmEBeDcBBPZ52IA)

### 💻 Code

![image](https://user-images.githubusercontent.com/13475147/197196484-f394a947-9f93-4761-82b5-787615ae985e.png)

### 🙁 Actual behavior

`output` is `{ w: number; x: string; }`

### 🙂 Expected behavior

`output` is `{ w: number; x: string; } | { w: number; x: string; y: boolean; z: symbol}`

**Comment by fatcerberus** [comment]
This is due to subtype reduction: `bar`’s return type is a subtype of `foo`’s, so it’s eliminated from the union.  This is by design, e.g. see https://github.com/microsoft/TypeScript/issues/49710

**Comment by fatcerberus** [comment]
Closest thing to a canonical duplicate is probably https://github.com/microsoft/TypeScript/issues/46449

**Comment by kesupile** [comment]
Thanks for the quick response. Is there a document I can read that explains the reasoning for the design decision; I'm curious.

**Comment by fatcerberus** [comment]
No official documentation I could find, but here’s the original PR that implemented it: https://github.com/microsoft/TypeScript/pull/4537
