### ISSUE TITLE
Transpile into Babel/tcomb syntax

### ISSUE THREAD

**Issue by jedmao** [Microsoft/TypeScript#5125]
I know this is a stretch, but what if you could set a flag to transpile TS code into code that would be readable by [`babel-plugin-tcomb`](https://github.com/gcanti/babel-plugin-tcomb), which came out recently? This would enable runtime type checking, which I previously brought up in #1573, but it would require interfaces be transpiled into structs:

```ts
interface Point {
    x: number;
    y: number;
}

function foo(point: Point) {
    return point.x * point.y;
}
```

becomes...

```js
import t from 'tcomb';

const Point = t.struct({
    x: t.Number,
    y: t.Number
});

function foo(point: Point) {
    return point.x * point.y;
}
```

If not provided directly by the compiler, the same could be achieved by a 3rd party module, if only a concrete syntax tree #625 were provided.

Related issues:
- https://github.com/Microsoft/TypeScript/issues/2944
- https://github.com/Microsoft/TypeScript/issues/1573
- https://github.com/Microsoft/TypeScript/issues/625

**Comment by jedmao** [comment]
For the record, I already have node modules that transpile from TS into ES6 and then Babel transpiles it from there and [it works great](https://github.com/jedmao/postcss-center)! If only this last missing piece of the puzzle were implemented, we would have an awesome solution for both compile time and runtime type checking.

**Comment by mhegazy** [comment]
I think this is an interesting and useful proposition. I would say the best way this can be implemented is as an emitter extension; we first need to allow for an extension point in the emitter to allow for additional transformations. @rbuckton has a change to make this doable today: https://github.com/Microsoft/TypeScript/pull/4010 and some helper factory functions in https://github.com/Microsoft/TypeScript/pull/3762.

**Comment by DanielRosenwasser** [comment]
Related is #1573.

**Comment by mhegazy** [comment]
The TypeScript compiler should expose a transformation API that enable these scenarios. i do not think this belongs in the core though. We are working on enabling a plug-able emitter transformation system, so this, along with an extension should address the OP.
