### ISSUE TITLE
`NonNullable<T>` type does not have a corresponding `Nullable<T>` type

### ISSUE THREAD

**Issue by ctjlewis** [microsoft/TypeScript#51255]
*Pro forma* bug report for https://github.com/microsoft/TypeScript/pull/51254.

**Comment by MartinJohns** [comment]
This is intentional. Duplicate of #39522.

**Comment by DanielRosenwasser** [comment]
Explained at https://github.com/microsoft/TypeScript/pull/51254#issuecomment-1287390320
