### ISSUE TITLE
Getting Type '"shortOffset"' is not assignable to type '"long" | "short"' error in angular 12

### ISSUE THREAD

**Issue by akshaykatale99** [microsoft/TypeScript#51266]
Even types are available Getting `Type '"shortOffset"' is not assignable to type '"long" | "short"' error`.

![image](https://user-images.githubusercontent.com/12472207/197269063-844492b6-ae03-4132-9f3b-d059313ba042.png)

**Comment by MartinJohns** [comment]
Not a TypeScript issue. Probably an outdated TypeScript version or a misconfiguration.

**Comment by akshaykatale99** [comment]
TypeScript version is `~4.3.5`

tsconfig.json 

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2020",
      "dom"
    ]
}
```

**Comment by MartinJohns** [comment]
TypeScript 4.3 is **over a year old**. The `timeZoneName` `"shortOffset"` was added in TypeScript 4.7.

**Comment by fatcerberus** [comment]
> TypeScript 4.3 is over a year old

😮 
...okay, I've been hanging around here too long.  Even *TypeScript 3.x* feels more recent than that...
