### ISSUE TITLE
Fix documentation that seems to imply `baseUrl` does something it doesn't

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#51267]
> If you get tired of imports always looking like "../" or "./", or needing to change them as you move files, this is a great way to fix that.

This text is one of my biggest pet peeves in the documentation.  It's described as if it's some convenience feature that TS will take care of for you, but in reality it only works if your runtime environment also understands it, because TS emits the import paths you use verbatim.

_Originally posted by @fatcerberus in https://github.com/microsoft/TypeScript/issues/51260#issuecomment-1287045529_

**Comment by fatcerberus** [comment]
There are similar implications in the docs for `paths`, for what it’s worth.

**Comment by MAYANKpandey14** [comment]
*I think it implies creating a tsconfig.json file with the following contents:*
```{
  "compilerOptions": {
    "baseUrl": "./modules"
  }
}
```
So if a module is imported such as navBar it would be looked up in ./modules/navBar 
```import  A from navBar```

Although, what you are pointing out is correct and the use of baseURL can be explained more precisely and not in a way it is done already.

![Screenshot 2022-12-22 at 11 37 32 PM](https://user-images.githubusercontent.com/94740455/209198432-8f5f3a9c-e3c4-44e9-a793-c70a7e5c67a0.png)

**Comment by andrewbranch** [comment]
Why does `baseUrl` actually exist? Today, it could legitimately be useful for doing ESM in the browser, though we lack nearly every other option necessary to support that scenario. But I’m pretty sure `baseUrl` was made long before ESM in the browser was possible, or even a definite future. Was it made to pair with AMD?

**Comment by RyanCavanaugh** [comment]
Right, it's named after the RequireJS option which kinda does the same thing: https://requirejs.org/docs/api.html#config-baseUrl
