### ISSUE TITLE
JSDoc @enum {function type}

### ISSUE THREAD

**Issue by sineway** [microsoft/TypeScript#51272]
It would be nice if we could describe the type of such a structure with `@enum`

https://user-images.githubusercontent.com/23264894/197326449-b3e05925-8f43-4f1d-8378-eb5e18c832cc.mp4

**Comment by sineway** [comment]
@MartinJohns why not? :sweat_smile:

**Comment by MartinJohns** [comment]
The downvote is for ignoring the issue template for [bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md) or [feature requests](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Feature_request.md), as well as posting a video instead of code (inaccessible to a lot of people). From your title and text I have absolutely no idea what you want.

**Comment by fatcerberus** [comment]
Even with the video I *still* have no clue what you want.  What is this proposed `@enum` tag supposed to do, exactly?

**Comment by fatcerberus** [comment]
FWIW `@type {Record<string, SortFunction<Product>>}` will likely already do what you seem to want here.

**Comment by sineway** [comment]
@MartinJohns Okay, I will try to explain.

Here is the code sample from the video:

```js
/**
 * @template T
 * @callback SortFunction
 * @param {T} a
 * @param {T} b
 * @return {number}
 */

/**
 * @typedef Product
 * @prop {number} price
 * @prop {number} date
 */

/**
 * @enum {SortFunction<Product>}
 */
export const ProductSort = {
  PRICE: (a, b) => b.price - a.price,
  DATE: (a, b) => b.date - a.date,
};
```
Arguments of the `ProductSort.PRICE` and `ProductSort.DATE` are of type `any`, but the expected type is `Product`.

The only solution that I was able to find in [JSDoc Reference](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) is to use `@type` for each property:

```js
export const ProductSort = {
  /**
   * @type {SortFunction<Product>}
   */
  PRICE: (a, b) => b.price - a.price,

  /**
   * @type {SortFunction<Product>}
   */
  DATE: (a, b) => b.date - a.date,
};
```
Perhaps, the documentation should mention things like `Record`, since it wasn't obvious, at least for me :sweat_smile: 

@fatcerberus thanks for the solution, it worked:
```js
/**
 * @type {Record<string, SortFunction<Product>>}
 */
export const ProductSort = {
  PRICE: (a, b) => b.price - a.price,
  DATE: (a, b) => b.date - a.date,
};
```

**Comment by RyanCavanaugh** [comment]
No one's ever asked for a function-valued enum before, as far as I know. Enums are usually numbers or maybe strings.

**Comment by fatcerberus** [comment]
@RyanCavanaugh https://jsdoc.app/tags-enum.html

> The `@enum` tag documents a collection of static properties whose values are all of the same type.

Apparently `@enum` in JSDoc is really just a fancy alias for a `Record` type.
