### ISSUE TITLE
Assertions involving values from dictionary literals aren't properly checked

### ISSUE THREAD

**Issue by Rafer45** [microsoft/TypeScript#51270]
# Bug Report

### 🔎 Search Terms

`type assertion keyof`, `"type string is not assignable"`,`'string' as keyof`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about __type casting__

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBACglgJwIbGgXigcgDIFcBm+ImUAPlgFJIDGA1gMphIIID2A7ieZgEIA2NWgCMIzACaYA3AChp+XADtqwOKwVQ+rAObxkqABRhEKCAC5Yx1AEooAb2lRHUamoDOrPhAB0mrYcsQVjIAvrIA9GFQAMJIrtAADOagkNQAFhB0rs6sLBnAfCDSvrom+jgERJhBRdolBpgKrMBQSFBGehBVMhFh4ZExcVAAjObscGIQCllicMqqCswgUABuSHy40MmbrFCuwAhwCloANFBacMuHWlAQLDlQ+PdCTak1OgH6tmDm5YTEwV4wNVih8vj9Gs1Wu0TJgAUDuhE+tFYtAAEzmMSsCCuBSYZouAC2YAEh1OQlwzUx2NxkOUuDWBWc6ToD3uwHS2Sm+yQh2A0giUAAIkgjrcoAAvNQQACEbzqEE+3yweD+JFiFg6cOBtVBSoaTRabQCaqy8q1CN6-P6KKgAGYkuAMszaFkXLllAU5R9FT8VZVgi0smCNSZglZAdr3h19D6sBDDdDULDA3YlWbw-CkQNoAAWB0pZ2unIIPKekHR4O-Soplxc81eit6+NQ401tzAes9LM2gCsGKxOLx2SJJIUZIpUCpg9pwHpfEZaQytFZCCg7Ogtb2yF5VqFIq0YslChlDdKlb9xDbXJTZojMnLZ6bBpbHRNnL2N4C9d32agADZ8ydJci3dfJCgfAxYyrf4rw-dVg3TO9T0gytmyNV8A3VTdISDNMvwzaofxtAB2QDF0ybJQM9bD32AC8oAwaCpGkGjsIAOSaeUGLjZ90JhZCFWwi9I3lfR2M4gJCIFX8AA5RnGSYsmAHYtyuU4QDgCA+BmI4bjuVdHlXZ52V3fQACVRHcBYhE8KARFSJBLjZHYRCgVIpT2KwiggZoCQpJAbIgejGIvZjPF8-zAo44AuMYtDE06e8dWjPzgACzxhKSqNSlS9KIGi+UpOtQYAE4yMLSiSw9cCfKgXLAoAFUdMQL3MWLlQqYh71q+rPCayAxAKgI2oCbj9UhPikxkIA)

### 💻 Code

```ts
type Pirate = 'Luffy' | 'JackSparrow' | 'Blackbeard';
function logPirate(pirate: Pirate) { console.log(pirate); }

// Typechecks correctly
logPirate(({p: 'Luffy'} as {p: Pirate}).p);
logPirate(({p: 'not a pirate'} as {p: Pirate}).p);

// Doesn't complain, but doesn't actually check for the constraint
// Dangerous!
logPirate({p: 'Luffy' as Pirate}.p);
logPirate({p: 'not a pirate' as Pirate}.p);
```

### 🙁 Actual behavior

Casting a dictionary field that can’t be correct raises no compiler error nor warnings.

### 🙂 Expected behavior

Casting a dictionary field that can’t be correct raises a compiler error OR needlessly risky casts raise warnings.

**Comment by MartinJohns** [comment]
You're explicitly instructing the compiler to ignore the type issue.

**Comment by fatcerberus** [comment]
It seems like you either want `satisfies` or `as const` here.  `as` type assertions are definitely the wrong tool in this situation.

**Comment by Rafer45** [comment]
> You're explicitly instructing the compiler to ignore the type issue.

I understand -- my question isn't "how do I make this work and get it to typecheck?"; it's more like "is there a way to emit a warning for casting string literals into types they aren't?". It's a bit strange that logPirate(({p: 'Luffy'} as {p: Pirate}).p); is clever enough to typecheck, despite being a type assertion, while logPirate({p: 'Luffy' as Pirate}.p); isn't. The interaction with widening causes inconsistent typechecking behavior.

Put another way: as assertions don't seem to unconditionally instruct the compiler to ignore type issues, and this seems like an easy error, on the developer's end, for people to miss; I've seen many cases of `{foo: 'bar' as keyof SomeDict}` where `{foo: 'bar' as const}` would be a better choice -- is there a feasible warning that could be emitted, in the case of literals, for these bad casts?

**Comment by MartinJohns** [comment]
> it's more like "is there a way to emit a warning for casting string literals into types they aren't?"

As fatcerberus mentioned, in TypeScript 4.9 you can use the `satisfies` operator.

> as assertions don't seem to unconditionally instruct the compiler to ignore type issues, and this seems like an easy error, on the developer's end, for people to miss

Type assertions are a way to explicitly disable type checks. It's a way to instruct the compiler "my value is this type, even though you can't verify it, trust me on this". If you lie to the compiler, then it's not the compilers' fault things end up messy. There's only a rudimentary check if the two types overlap in some form, but this does not apply here.

The purpose of `as` is to disable type checks.

**Comment by Rafer45** [comment]
I understand that the problem with `as` abuse is that the developer is lying to the compiler; it just seems like there should be a warning when `as` is used for literals in this way, since it seems like a pretty common developer bug from what I've seen.

My specific context is here: https://github.com/Rafer45/experimental-extensions/blob/reao/storage-transcribe-audio/storage-transcribe-audio/functions/src/transcribe-audio.ts#L12

I've had some trouble replicating it in the typescript playground, but here, without the `as const` assertion, `'LINEAR16'` was getting widened to the type `string`, requiring a cast. I may be missing something obvious, though; thank you for your help so far.

**Comment by MartinJohns** [comment]
> My specific context is here:

Simply typing the `request` variable would have prevented the issue.

**Comment by RyanCavanaugh** [comment]
`as`'s intended behavior is to allow assertions that seem OK and disallow assertions that don't seem OK. There's no bright line here; in reality any assertion can be made OK by writing `e as unknown as T` so this is entirely a heuristical process designed to catch assertions that aren't plausibly correct.

In the case of literals from the same family, there's really no reason to ever write `"foo" as "bar"` -- you could always have written `"foo" as const`, or even usually just `"foo"` without loss of generality. There are some edge cases (usually around mutating side effects) where it's *really* useful to do this, and, as noted, any `as` really is as suspect as another. TS is just trying to hit the sweet spot in terms of only giving useful errors with this behavior.

**Comment by Rafer45** [comment]
> Simply typing the `request` variable would have prevented the issue.

But it's more intuitive to type the 'LINEAR16' field, since the other fields weren't complaining, no? My claim is just that this is an easy enough mistake to make that it could merit a warning.

> In the case of literals from the same family, there's really no reason to ever write `"foo" as "bar"` -- you could always have written `"foo" as const`, or even usually just `"foo"` without loss of generality.

Would it make sense to emit a warning when a literal is cast into its own family, then? Or to at least have a flag one could enable for that kind of warning? Since the cases where it's useful are edge cases?

**Comment by RyanCavanaugh** [comment]
You could write a lint rule to flag those cases if you find them objectionable in your own codebase.

**Comment by Rafer45** [comment]
Understood, thanks all for the discussion.

**Comment by MartinJohns** [comment]
> But it's more intuitive to type the 'LINEAR16' field, since the other fields weren't complaining, no? My claim is just that this is an easy enough mistake to make that it could merit a warning.

Typing your variable will also cause excess property checks to work, informing you about unnecessary properties. Helpful when you accidentally misspelled an optional property.

**Comment by fatcerberus** [comment]
Just as a final note for the record: there’s no fundamental difference to the type system between `randoString as "foo"` vs. `randoAnimal as Dog`.  In both cases you have a potentially unsafe upcast from a supertype to a subtype, and rejecting one in principle means rejecting the other, even if one might seem inherently more suspect.

That being said, the fact that `"foo" as "bar"` is directly allowed *does* surprise me, as it is very clearly a sidecast with no direct overlap between the types (they have a common supertype, but factorizing types isn’t generally something TS does).

**Comment by Rafer45** [comment]
Yeah, I understand why we would want to allow `<nonLiteralExp> as "foo"`, just not why we would allow `"non foo literal" as "foo"`, since there's no overlap.

But it's a developer error with `as`, not a compiler error -- I'll see what I can do to discourage it in my codebase.
