### ISSUE TITLE
object implements an interface, but failed to check the return type of function

### ISSUE THREAD

**Issue by ttthing111** [microsoft/TypeScript#51279]
# Bug Report

### 🔎 Search Terms

interface void return check ,void

### 🕗 Version & Regression Information

My version is 4.8.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEEkDtQFwCwJYGdQDMCukDGMEHtIAaULPAWwAcEAbAUwCcSBDaLOWrAa1HtpnXrQYATwq1QyUJDwxQZJjDaw8oAG54EAEwB0AKAzZcBWLSQGAFAEoAXOq0BvXaGe9+g0AGZdAX11+EkDAMqExY4gAqpjAATI7OzkFmmNagVgC8AHxqGpo+fiCgAELosvCSWExItMRI6ABGWNSVKKSUNAxoTO2aJOxcPHwCQqK0eqSQSKVRAPJ1AFYpkZPRoGmgcfGJBtbpGfauQ56+3kA)

### 💻 Code
<img width="723" alt="image" src="https://user-images.githubusercontent.com/39229831/197399789-7e6dca03-cebe-438d-bcb3-c0379d6c0f81.png">

### 🙁 Actual behavior
I find when I implents an interface, the `void` return type in interface maybe not checked in implemented objects. Actually I did return somthing, in my opinion, its should be noticed you shouldn't return anything.

### 🙂 Expected behavior
I defined this function return `void` in an interface, it should warn me when return something in subclass.

**Comment by MartinJohns** [comment]
See the TypeScript FAQ: [Why are functions returning non-`void` assignable to function returning `void`?
](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

**Comment by ttthing111** [comment]
> See the TypeScript FAQ: [Why are functions returning non-`void` assignable to function returning `void`? ](https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

hi Martin, thx for your reply. I accept the `"I'm not going to look at your return value, if one exists".`
But I still  confused about why in the first case it can checked
<img width="937" alt="image" src="https://user-images.githubusercontent.com/39229831/197451324-678b86f2-d982-49af-a92e-fb4b7f9fba15.png">

**Comment by MartinJohns** [comment]
Because a function implementation that returns `void` must not return anything. You have the same in your initial example if you make your function return `void`. Right now the return type is inferred, due to the missing type annotation. I'd post the adjusted code, but I'm on mobile and you didn't post the code for me to copy and adjust.
