### ISSUE TITLE
readonly keyword does not protect array fields from assigning indirectly outside of the constructor

### ISSUE THREAD

**Issue by panisir** [microsoft/TypeScript#51276]
# Bug Report

### 🔎 Search Terms
  We do not allow to assign a new array to our readonly array field.
   But instead of assigning it outside of constructor
   writing some additional functions we easily can do that indirectly
   and it can be done outside the constructor.

### 🕗 Version & Regression Information

v4.8.4

### 💻 Code

```
class Notebook {
    readonly notes: string[] = ['note1', 'note2'];
  
    constructor() {}

    public changeNotes (newNotes : string[]){
      this.notes = newNotes; // will give assign error since it is defined as readonly
    }

    public addNotes(note : string){
      this.notes.push(note);
    }
  
    public deleteNotes(indexStart: number, indexEnd: number): void {
        this.notes.splice(indexStart,indexEnd);
    }

    public deleteAllNotesUsingLength() : void {
      this.notes.length = 0;
    }
  }

  let notebook = new Notebook();
  console.log(notebook.notes);
  notebook.deleteNotes(0,1);
  console.log(notebook.notes);
  notebook.deleteAllNotesUsingLength();
  console.log(notebook.notes);
  notebook.addNotes('note3');
  notebook.addNotes('note4');
  notebook.addNotes('note5');
  console.log(notebook.notes);
```

### 🙁 Actual behavior

We do not allow people to assign a new array to our readonly variables.
   But instead of assigning it outside of constructor
   writing some additional functions we easily can do that indirectly
   and it can be done outside the constructor.

### 🙂 Expected behavior

so the official documentation says ;
   Fields may be prefixed with the readonly modifier. 
   This prevents assignments to the field outside of the constructor.
   https://www.typescriptlang.org/docs/handbook/2/classes.html#readonly

  It seems we have a like a logical mistake here, doesn't it ?
  If we want to mark the variable as readonly and protect it against modifications from outside the constructor
  we should prevent all the assignments and modifications to it.

**Comment by MartinJohns** [comment]
The documentation is correct: no assignment outside the constructor can be made. It does not mean the data structure is immutable. This is working as intended.

You can use `readonly string[]` for additional safety. But in the end you can't describe immutable data structures in TypeScript.

**Comment by panisir** [comment]
thanks for answering Martin, after your answer and going further on some inspections I see that by nature of JS mutate data structures is not possible for the TS as well. And you said we could add some extra check by modifying code as following : 

`notes: readonly string [] = ['note1', 'note2'];`

Just a suggestion ; the part of the documentation might be updated with a little warning about the immutability and by referencing readonly tuple types here 'cause it could be a little bit confusing for the new comers especially from programming languages from like JAVA if the subject is classes and fields.

I'm closing the topic. Thanks for sparing time again. @MartinJohns

**Comment by MartinJohns** [comment]
I'm not sure how the documentation can be any more clear than:

> This prevents assignments to the field outside of the constructor.

**Comment by panisir** [comment]
For example by referencing this piece of article :
[Read Only Object Properties](https://www.typescriptlang.org/docs/handbook/2/objects.html#readonly-properties) 
**Using the readonly modifier doesn’t necessarily imply that a value is totally immutable - or in other words, that its internal contents can’t be changed. It just means the property itself can’t be re-written to**. 

A more clear definition has already been written in docs. Referencing it could be useful. @MartinJohns

**Comment by MartinJohns** [comment]
Feel free to send a pull request to improve the handbook, I'm sure the TypeScript team will be happy about it.
