### ISSUE TITLE
missing font-display type

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#51286]
# lib Update Request
lib.dom.d.ts

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

`FontFace`'s `display`

## Sample Code

```ts
const font = new FontFace('name',url,{

 display: 'auto' | 'block' | 'swap' | 'fallback' | 'optional'
})

// or 

font.display = 'auto' | 'block' | 'swap' | 'fallback' | 'optional'
```
## Documentation Link

 https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

**Comment by MartinJohns** [comment]
Updates to the DOM libs have to be done in: https://github.com/microsoft/TypeScript-DOM-lib-generator/

**Comment by HomyeeKing** [comment]
@MartinJohns  I'm working on it
it's explicit I think
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

![image](https://user-images.githubusercontent.com/49113249/198536294-6441473f-5c7a-4c71-a93d-be016ead46c3.png)
