### ISSUE TITLE
checkJs emits on top of input file, error TS5055

### ISSUE THREAD

**Issue by alexeagle** [microsoft/TypeScript#51291]
# Bug Report

### 🔎 Search Terms

checkJs

### 🕗 Version & Regression Information

observed with:
4.8.4
4.9.0-dev.20221024
4.0.8, 2.3.4 (required `allowJs` as well)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about checkJs

### 💻 Code

`tsconfig.json`
```
{
    "compilerOptions": {
        "checkJs": true
    }
}
```

`one.js`
```
/** @type string */
export const a = 1
```

`two.ts`
```
import {a} from "./one"

console.log(a)
```

### 🙁 Actual behavior

```
$ ./node_modules/.bin/tsc
error TS5055: Cannot write file '/home/alexeagle/repros/ts_checkJs/one.js' because it would overwrite input file.
```

### 🙂 Expected behavior

I wouldn't expect one.js to be emitted since it's a source file

**Comment by fatcerberus** [comment]
TS also functions as a transpiler so it will still produce an output `.js` file even for plain JS.  This is intentional and the solution is to set `outDir`.

**Comment by gdh1995** [comment]
I also met this. I was using `import type aaa from "folder/with/a.js"` and `tsc` reported `error TS5055`.

I don't want to use `outDir`, because my project works well when I tell `tsc` to output `.js` files in same folders with ther source `.ts` files. So how can I avoid the error?
