### ISSUE TITLE
Type Guards with &&

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#5129]
```
var foo: number | string;
typeof foo == 'string' && foo.split(' '); // Property 'split' does not exist on type 'number | string'. 
```

**Comment by AbubakerB** [comment]
use the Strict Comparison Operator (===) instead of Equality Operator (==).

**Comment by danquirk** [comment]
It would be nice if we could make it clearer why this happened but as mentioned this is by design. Type guards support specific patterns only.
