### ISSUE TITLE
A mapped generic type does not work as intended in a generic function

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#51290]
# Bug Report

### 🔎 Search Terms

mapped types generic

### 🕗 Version & Regression Information

Not a regression.

This is the behavior in every version I tried, and I reviewed the FAQ.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAsiAKAnCAzAlgDwgEwCrggGkIQBnKAXigCgo6oByFAe2YagB9b6GAjAQ0QMA3NWqhIsBMnRY8BADzwoEDMAgA7bOVLBEaDQHMAfJSgBvbnQDahKAalJUmHPkjEyUfuQAGAEnN4AF8AwiCfAF0ALihdfSNqILEAemSoAHkAa3ECKHVdMzgnWVdFBjBkAH0GY2EoVIsoCohKlmYYuINDABomqoFEDr0uqCTqBoBJYChsZghyDWZpgHdmREz7DS8oFABXDQBjYDRmLeW0YAALbcNNCH0DpsF+AFsIdURqPcPj06gD5D8dTFFzySBKFRqTTaWLDIzGAAUzVkMXgAEoYkUZKC3BAlKZLPQoAAbd5QdqObFyXH4syEon0az+czIzBBNqRGIMBjdKwMhoAOSW0CuQPs01m8ygi2myAAjrs0Mg8pdoAM+sxIIhQAA6KBTGZzBZLKDyxXK-gaEAarW6nU6vljIkSaAYQrSZzUxTwWr1NL2nW8CAHfi7Ugi1V5XJoHQQTRecjmUZiInMJkBVkYIIDSJmbl1BoAUUQiDWMVxjE6RnYMelJu8pDQhg0-F4pLyzCjkgYWM9pXBPvTgWzgkiDB1CIATABmSeTtEp+jIYC7RBbZiiMZAA)

### 💻 Code

```ts
type MyPrefixedTypeKeys = 
    'foo' |
    'bar';

type MyPrefixedType<P extends string> = {
    [K in MyPrefixedTypeKeys as `${P}${K}`]: string
}

// Ok
type test = MyPrefixedType<'pre_'>; // { pre_foo: string, pre_bar: string }

// It does not work in a function with a generic parameter
function createPrefixedType<P extends string>(prefix: P): MyPrefixedType<P> {
    let o: MyPrefixedType<P> = {
        [`${prefix}foo`]: '',
        // Note that it does not require the bar property. It does not require any property...
    }

    type x = MyPrefixedType<P>; // ...because the type is seen as { }

    o[`${prefix}bar`] = ''; // Error: Type 'string' is not assignable to type 'MyPrefixedType<P>[`${P}bar`]'.(2322)

    return o;
}
```

### 🙁 Actual behavior

The mapped type becomes `{ }` in the generic.

### 🙂 Expected behavior

The type mapped type should work inside the generic.

### Workarounds

In this particular case, it's possible to use `Record` as a workaround.

```ts
type MyPrefixedType2<P extends string> = Record<`${P}${MyPrefixedTypeKeys}`, string>

function createPrefixedType2<P extends string>(prefix: P): MyPrefixedType2<P> {
    let o: MyPrefixedType2<P> = {
        [`${prefix}foo`]: '',
        [`${prefix}bar`]: '',
    } as MyPrefixedType2<P>;

    o[`${prefix}bar`] = '';

    return o;
}
```

**Comment by jcalz** [comment]
Specifically the issue here is *key remapping* involving generics.  Template literal types don't seem to be involved here:

```ts
type MyPrefixedType<P extends string> = {
  [K in "xxx" as P]: string
}

function createPrefixedType<P extends string>(prefix: P): MyPrefixedType<P> {
  type Z = MyPrefixedType<P>;
  // type Z = {};  
  return {}; // No error!
}

const x = createPrefixedType("XYZ");
console.log(x.XYZ.toUpperCase()); // typed as string!
```
[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiAKAnCAzAlgDwgEwCrggB54oINgIA7bAZyhuETUoHMA+KAXigG8AoKFADaAaSjMoAIgwzJUAIZ14AXQBc9RsxZ8Avnz4oArpQDGwNAHtKUE8nkUkqTDnyRipclVoamrNgAowZHQMdXgASnU4RxCXAmIOfkFQSCgALS5YBGDnPHj4NgBuASgAelKoFOgM7h4dQsES5GBDRGs6hvKoADkLUkREC0QAQl19EysGKAxM2wh7CBjc1wh-SQANAE00yXDiicoaCwAbCAA6Y4sWfwwzrbSz4AsAVTBIRABhRVXwvbKKqrYBR0Bi+FjDIA)

That's obviously a silly thing to do with key remapping, but it illustrates the same issue, I think.

**Comment by ahejlsberg** [comment]
This was fixed by #51050. The fix will be in the upcoming 4.9 release.

**Comment by mckravchyk** [comment]
@ahejlsberg Thanks! The object in the function has the correct type, however, the assignment still creates an error.

```
type MyPrefixedTypeKeys = 
    'foo' |
    'bar';

type MyPrefixedType<P extends string> = {
    [K in MyPrefixedTypeKeys as `${P}${K}`]: string
}

// Ok
type test = MyPrefixedType<'pre_'>; // { pre_foo: string, pre_bar: string }
let o: test = { pre_bar: '', pre_foo: '' };
o[`pre_bar`] = '';

function createPrefixedType<P extends string>(prefix: P): MyPrefixedType<P> {
    let o: MyPrefixedType<P> = { // Ok
        [`${prefix}foo`]: '',
        [`${prefix}bar`]: '',
    } as MyPrefixedType<P>;

    type x = MyPrefixedType<P>; // The type is correct now

    // but the error still is there
    o[`${prefix}bar`] = ''; // Type 'string' is not assignable to type 'MyPrefixedType<P>[`${P}bar`]'.(2322)

    return o;
}
```
[Playground](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221025#code/C4TwDgpgBAsiAKAnCAzAlgDwgEwCrggGkIQBnKAXigCgo6oByFAe2YagB9b6GAjAQ0QMA3NWqhIsBMnRY8BADzwoEDMAgA7bOVLBEaDQHMAfJSgBvbnQDahKAalJUmHPkjEyUfuQAGAEnN4AF8AwiCfAF0ALihdfSNqILEAemSoAHkAa3ECKHVdMzgnWVdFBjBkAH0GY2EoVIsoCohKlmYYuINDABomqoFEDr0uqCSAGwhgKHa8iAKqcz6WgZiGBl7m1tZV9iDRZmsfTYHIszXRahQAVw0AY2A0Zg0oW+R+dWKXeUglFTVNbSxYZGYwACmashi8AAlDEijIvm4IEpTJZ6FAJlMZvDnHIkSizIsGlkrOioIcAhDMEE2pEdt1SeiKeYqRggidoox1qSgl5yDiSt9kfBamJ0RJoBhCtJcaUfiK6g1cAALaAS+zkW7MRDIe5QDTMADuYvoDV4VymwFVKh12qBaDGYw1eVVyFJB38LIRbI5ZxE9TSSMYnSM7DQ5ANU28pDQhg0-F4EzyzDyuQYAsRihFzOCHIYADpQQAmADMRaL0JNdGQwCuiGezFESWoQA)

**Comment by mckravchyk** [comment]
@ahejlsberg Sorry for the late reply. I have found a workaround to express it in a Record type * (since in my particular case, all values in the type where strings)  which worked in the older version  and I somehow forgot about this thread. It's definitely good to know that it's possible though. Thank you, sir!

*
```ts
type MyPrefixedType<Prefix extends string> = Record<`${Prefix}_${MyPrefixedTypeKeys}`, string>
```
