### ISSUE TITLE
Merged ambient declaration issue

### ISSUE THREAD

**Issue by mikedon** [Microsoft/TypeScript#5130]
I'm trying to use the new capability of merging classes and interfaces to extend the definition of an ambient external module.  For simplicity I'll use the following example

foo.d.ts
```javascript
declare module "foo" {
	export class Foo {
		constructor();
		method1(): any;
	}
}
```

foo-ext.d.ts
```javascript
declare module "foo" {
	interface Foo {
		method2(): any;
	}
}
```

index.ts
```javascript
import * as foo from "foo";

class Test {	
	foo: foo.Foo;	
	constructor(){
		this.foo = new foo.Foo();  //This line results in a compile error: index.ts(10,3): error TS2322: Type 'Foo' is not assignable to type 'Foo'. Property 'method2' is missing in type 'Foo'.
	}
}
```

If I remove the constructor definition from foo.d.ts then the compile error goes away.  I've tried this with 1.6.2 and 1.7.0-dev.20150922.  

Am I misunderstanding this feature or is this a bug?

**Comment by mikedon** [comment]
Is this something the team would accept merge requests from a noob like myself?  It's blocking some refactoring I'd like to do on our internal project structure at work and I've been looking for an excuse to understand the internals more anyway.

**Comment by sandersn** [comment]
Sure. I am new to the team, so I don't know any more than you.

Also, #4579 seems related (although weirder). If I have time before you get a PR out, I'll take a look at that one.

**Comment by sandersn** [comment]
In my initial investigation, it looks like the left hand side, `this.foo`, gets the correctly merged type while the right hand side, `new foo.Foo()`, gets the unmerged class type.

**Comment by mikedon** [comment]
I've seen the same in my debugging.  I've also got a test case written if that helps.  I've also found out that if the class and interface are declared in the same file then it merges correctly.

Trying to understand the binding process now.  Is there an IRC channel or some type of way to get help from TS devs about understanding the source code?

**Comment by sandersn** [comment]
I think [gitter](https://gitter.im/Microsoft/TypeScript) is the primary way. As far as I know, the checker is actually the important piece here since it handles merging across files.

I'm working off a test case based on your example:

```TypeScript
// @module: amd 

// @filename: foo.d.ts
declare module "foo" {
    export class Foo {
        constructor();
        method1(): any;
    }
}

// @filename: foo-ext.d.ts
declare module "foo" {
    interface Foo {
        method2(): any;
    }
}

// @filename: index.ts
import * as foo from "foo";

class Test {
    foo: foo.Foo;
    constructor() {
        this.foo = new foo.Foo();
    }
}
```
