### ISSUE TITLE
TSDoc Nested member in `@link` does not work in VSCode

### ISSUE THREAD

**Issue by Tanimodori** [microsoft/TypeScript#51314]
# Bug Report

Nested member in `@link` does not work, which is valid according to [TSDoc docs](https://tsdoc.org/pages/tags/link) and works in playground.

### ⏯ Playground Link

https://tsdoc.org/play

TSDoc does not support share code links.

### 💻 Code

```ts
interface Foo {
  bar: Bar;
}

interface Bar {
  baz: number;
}

/**
 * {@link Foo.bar}
 * {@link Foo.bar.baz}
 * {@link Bar.baz}
 */
function foo();
```

### 🙁 Actual behavior

![Code_GhADsa31ub](https://user-images.githubusercontent.com/29478770/189542353-0ecc28fd-a9db-413d-858e-a614956f32b2.png)

### 🙂 Expected behavior

The nested member should be displayed as a link.

**Comment by RyanCavanaugh** [comment]
TSDoc is wrong to support this; it isn't a recognized TypeScript form at all.
