### ISSUE TITLE
wrong return type when `\\u{${hex}}`

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript#51313]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=5&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwPowQCqKmaEAJsABRoAWAhlAMKXABccKSAtgEbAoAGjgB3KAzAB+TnwgQANsAYoAlAFgAUAG8tASHIoAzvDqg4AXjj0mrKgDpCAZRhRMKAObUAjADZVANz6UMAwSFC41OKScAA+sXBmIPZKnjB0cAB8cAAsqnBScAAGADolSNoAJNpJAL61RXAMRtY4JnCcpeXVdY3NrcYwQZq1QA

### 💻 Code

```ts
export function _toUnicode(charCode: number, wrap?: boolean)
{
	const hex = charCode.toString(16);
	return (wrap || hex.length > 4) ? `\\u{${hex}}` as const : `\\u${hex}` as const;
}
```

### 🙁 Actual behavior

```ts
export declare function _toUnicode(charCode: number, wrap?: boolean): `\\u${string}`
```

### 🙂 Expected behavior

```ts
export declare function _toUnicode(charCode: number, wrap?: boolean): `\\u${string}` | `\\u{${string}}`
```

**Comment by IllusionMH** [comment]
`` `\\u{${string}}` `` is valid `` `\\u${string}` `` - type just simplified(reduced?) to most permissible type as they are compatible.
Same as `'{}' | string` where result type would be `string`
