### ISSUE TITLE
Double quotes in tsx are not escaped correctly in produced javascript

### ISSUE THREAD

**Issue by TomaszKucharzyk** [Microsoft/TypeScript#5132]
Double quotes in tsx are not escaped correctly in produced javascript

test.tsx
```
///<reference path="./typings/react/react.d.ts" />
import * as React from "react"

var a = (<div><h1>My "Quoted" Title</h1></div>)

```

compiles to:

```
///<reference path="./typings/react/react.d.ts" />
var React = require("react");
var a = (React.createElement("div", null, React.createElement("h1", null, "My "Quoted" Title")));
```

This is not valid javascript

I'm compiling it using typescript 1.6.2  using the following command ``` tsc  --jsx react --module commonjs test.tsx ```

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh you can look into the `escapeString` function.
