### ISSUE TITLE
Feature: Optional Return Types

### ISSUE THREAD

**Issue by lukeed** [microsoft/TypeScript#51332]
# Suggestion

Allow return-type syntax to accept a `?` suffix as a shorthand for `T | undefined`

## 🔍 Search Terms

optional return type, return undefined shorthand, return type or undefined

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When adding return types, I'm often adding `| undefined` or `| void` (less so in recent versions) due to my usage of early `return` statements. I think it'd be nice to borrow the `?` syntax from optional parameters and optional properties, which already expands to `T | undefined` when used.

## 📃 Motivating Example

```ts
// current:
//   declare function foo(): string | undefined;
// propose: 
//   declare function foo(): string?;
function foo() {
  if (exitEarly()) return;
  // expensive stuff
  return 'hello';
}

// current:
//   declare function bar(): Promise<Response> | undefined;
// propose: 
//   declare function bar(): Promise<Response>?;
function bar() {
  if (exitEarly()) return;
  return fetch('https://...');
}

// current:
//   declare function baz(): Promise<Response | undefined>;
// propose: 
//   declare function baz(): Promise<Response?>;
async function baz() {
  if (exitEarly()) return;
  return fetch('https://...');
}
```

## 💻 Use Cases

This is only a shorthand for defining return types. It affects nothing else & I imagine it could reuse the existing logic for `?` expansion.

The only possible shortcoming I can foresee is confusion wrt another instance where `?` has a meaning; however, it's roughly the same meaning it has everywhere else too. This would be solved by documentation anyway, and is opt-in.

The workaround is to continue writing return types in "longform" – including `| undefined` everywhere (which one could still do anyway).

_Edit:_ And as @lukeshiru [reminded me](https://twitter.com/lukeshiru/status/1585718875622354949), this also exists as a workaround, which I've used in the past too:

```ts
type Maybe<T> = T | undefined;

declare function foo(): Maybe<string>;
declare function bar(): Maybe<Promise<Response>>;
declare function baz(): Promise<Maybe<Response>>;
```

But as you can see, nesting multiple generics can get messy/confusing.

**Comment by RyanCavanaugh** [comment]
I don't see why this would be something that only works in return types; it seems odd - there isn't any other type syntax that only works in one position. In other places, the `?` is on the identifier, but return types don't have identifiers, so it's not really symmetric.

This was previously discussed at #7426 and we determined that not using `?` for this was the best path forward.

**Comment by lukeshiru** [comment]
I don't quite get the "inconsistent" argument when the `?` operator is used to signify "| undefined" in arguments as well. This:

```ts
declare function foo(bar?: string): string?;
```

Looks more consistent than this:

```ts
declare function foo(bar?: string): string | undefined;
```

**Comment by lukeed** [comment]
Well, asking for `string?` anywhere `string` can be placed seemed like a much larger ask, and not a can of worms I was looking to open. I find that 99% of the `| undefined` I'm writing are to do with function/method signatures, which tend to be the most complex points especially when overloading enters the equation.

So the motivation was to collapse those characters into a more compact form & cleanup the function signature space, specifically. Focusing on return types seemed like an acceptable "exception" to type-modifiers because (1) we already have the `?` -> `|undefined` relationship; (2) return type signatures are _already_ special in how/where they can be defined; and (3) to me, the existence of a `ReturnType` helper denotes that there's an ability to parse/understand return types separately from the rest of the definition, possibly allowing for "this place can add this sytanx modifier"

**Comment by MartinJohns** [comment]
> I don't quite get the "inconsistent" argument when the `?` operator is used to signify "| undefined" in arguments as well. This:

Arguments can be optional, return values not. Your method **always** returns something, even if it's `undefined`. This is not the case with arguments, when you don't pass any, it won't appear as part of `arguments`.

**Comment by RyanCavanaugh** [comment]
I think it's important to notice that you write
```ts
declare function foo(bar?: string): string;
```
not
```ts
declare function foo(bar: string?): string;
```
In all places where `?` is used today, it's on the name of something, not part of the type.

If it was allowed as part of the type in a return type, there's really no reason to not allow it everywhere. It'd be much less work, less error-prone, and much less confusing overall. So the question is really whether it makes sense to allow it everywhere, and I think the answer there is still "no".

**Comment by lukeed** [comment]
I just finished reading the linked issue. I think it's important to remember that it was from 2016 and TypeScript's handling of `null vs undefined vs void` is much stricter now, so your initial examples of allowing `null` to pass through a `x?: number` vs `x: number | undefined` [is no longer valid](https://www.typescriptlang.org/play?ts=4.8.4#code/GYVwdgxgLglg9mABMOcAUAPA-ALkWEAWwCMBTAJwEo8BnKcmMAc0QG8AoRLxc0qEckgyIAvGMTgAJqWCNSkxFkQByZYjwYAdFDgAxGBnloATJQDc7AL7t2oSLASJiAQ3KY8BEhUQAfCWGlZMHlqRDoGZjZObl5+QURhMRF-QLkFJVV1BO09AyNTC2t2AHpixABaSogQKErym1tUNABGc0b0AgAbTraUdCkZNLb2FzdWi1G0Lp6J1zQBoJCLdiA)

Separately, `bar?: string` expands to `bar: string | undefined` and makes the _position_ of that argument optional. Of course you know this, and so you also know that `bar?: string` and `bar: string | undefined ` **are not** the same thing.

I personally see no issue with `string?` being an alias for `string | undefined`. 
That means that `bar: string?` is an alias for `bar: string | undefined`, which **is still** semantically different than `bar?: string` --- nothing new there.

Users who choose to go the `bar?: string?` route are being a little redundant, sure, but the identifier's `?` is a unique condition/restraint so it persists.

**Comment by lukeshiru** [comment]
> In all places where ? is used today, it's on the name of something, not part of the type.

The maybe something like this?

```ts
declare function foo(bar?: string)?: string;
```

My point was mainly that we are already using the question mark to say "maybe", and I agree with lukeed that it would be great to have syntax for "maybe" for return values as well, being that's extremely common to return "something or undefined".

**Comment by RyanCavanaugh** [comment]
> I personally see no issue with `string?` being an alias for `string | undefined`.

Sure; personally I wouldn't mind this either since the codebases I happen to work in don't use `null`. But there are other users too. The linked issue also has many people (maybe a plurality or majority, even) commenting that `string?` is most-usefully an alias for `string | null`. For codebases that use `null` as their sentinel non-value, it'd be quite painful to have `T?` sitting around as a tempting-but-wrong type name.

I don't actually think anything meaningful has changed since #7488; `exactOptionalPropertyTypes` is the closest to moving the ball, but is sort of a niche flag and doesn't represent how many programs treat missing/present values in JS.

**Comment by lukeed** [comment]
I didn't really want to get into `null`, but `null` is not an implied value. Applications _opt into_ its usage & TS is smart enough to restrict & deduce `null` vs `undefined` usage. The presence of `undefined` is always implicit, which is why named optional arguments are `T | undefined` and not `T | null` or `T | null | undefined`.

That said, if we had to make the `null`-user camp happy, then – now that `??` operator exists in a post-2016 world (which is `null`-centric), I think `T??` should be explicitly `T | null` which allows `T?` to be `T | undefined` exclusively.

That means that if someone had the crazy idea to continue mix & matching null & undefined, they could:

https://www.typescriptlang.org/play?ts=4.8.4#code/PTAEBMFMGMBsEMBOlQDMCuA7aAXAlgPaZoEEAU8AXKJugLYBGkiANKA9bY8wPw8CU1AG4E84ANwAoKHCQoM2fERLkqNek1btOG5gB9asWINAixUySAgwEyNFlyFiDJBR3ctHdR75toPd00TMwlpGzl7RSd2VzUuTTYveP1DWD8A7yDhUVDLMBlbeQclZ3gALzdM5kTA3h502sQ+YJypAoiFR2UXCrjdT0aDdCMGqsQhoxbzSTzrWTtOkpicSuSBsfrQf0bm7On2heLolxW+jxqxvSwoVDxMSHBRtYnjPdzUUjIARjYAJn4pB9yD91JNAZ8QddILd7uAAZIgd94ZIXIhvn94aj0aDjFIsSDUmxUpjXAThmlQFCYQ8SWjIZgbncHmwqUy4RYetj-njytjiTyKmSRjiSYKieSWQzoWzRdjWbDJYzYciTlySSshbiUfANeLhfztbqcYrpcqeUb5czKVLqezDXKbWy9VqgA

**Comment by opensas** [comment]
I agree with @lukeed, and I like the idea of having `T?` expand to `T | undefined` everywhere, and also the `T??` to `T | null` (and of course, we are all thinking about `T???` expanding to `T | undefined | null`, right?) but it would be great if we could just have the `T?` as it seems a really intuitive option. I think that leaving null out of the discussion, at least for the time being, would make it easier to move on.

**Comment by fatcerberus** [comment]
> I think that leaving `null` out of the discussion, at least for the time being, would make it easier to move on.

You'd think so, but nobody really wants to have to write `T??` or `T???` in their code so defining `T?` upfront as `T | undefined` in practice alienates about half the potential userbase for nullable types, and they *will* argue against it.  So the conversation never gets off the ground, and the same thing has happened every time this feature request is brought up.  `T | undefined` and `T | null` might be more verbose, but at least nobody can argue about what they should mean.

**Comment by lukeshiru** [comment]
TBH [there](https://github.com/angular/angular/issues/42713) [are](https://hamednourhani.gitbooks.io/typescript-book/content/docs/tips/null.html) [several](https://writingjavascript.com/why-you-should-always-use-undefined-and-never-null) [arguments](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined) [agains](https://stackoverflow.com/questions/6604749/what-reason-is-there-to-use-null-instead-of-undefined-in-javascript/28825847#28825847) [the use of null](https://www.youtube.com/watch?v=PSGEjv3Tqo0&t=563s), and like it was mentioned before:

```ts
const aFunction (foo?: string) => {
  // foo here is not `string | null`, is `string | undefined`
}

type example = {
  property?: string;
};

example.property; // this is `string | undefined`, not `string | null`
```

So the "rule" is pretty simple: The question mark is a shorthand for `type | undefined`. So when you want to signify `null` for some weird reason, you can go verbose for that instead of being verbose for both using `null` and using the default nullish value of the JS, which is `undefined`.

So the argument in "favor of null" is not only outdated but is also kinda lacking.

**Comment by fatcerberus** [comment]
> So the argument in "favor of null" is not only outdated but is also kinda lacking.

Many people will disagree with you.  Vehemently.  I have no horse in this race, I'm just telling you what's likely to happen based on past experience.

**Comment by opensas** [comment]
honest question here, how to the ts team solve these situations, I mean, when community cannot reach an agreement?
just wait for things to settle down, do some kind of poll, they just decide by themselves? I thinks there's no TC-39 equivalent for ts, right?

**Comment by MartinJohns** [comment]
They take feedback into consideration and decide themselves. In this case they have already decided. They're not numb to new feedback, but it doesn't mean it's convincing enough to change their opinion.

**Comment by RyanCavanaugh** [comment]
Just as a reminder, the DOM (the environment that *most* JS runs in) uses `null` extensively as its non-value (e.g. `document.getElementByWhatever` will return `null` on a non-match). NodeJS also uses `null` all over the place (to indicate "no error here" in callbacks, the exit code of still-running processes is `null`, etc). There are no major runtime environments where you won't encounter `null` values as a matter of course. It doesn't really matter how many blog posts people write encouraging JS programmers to not use `null` in new places, nor how much people agree with them, given this situation.

In cases where there's disagreement about what some syntax should mean, simply not having introducing that syntax is by far the most attractive option.

**Comment by lukeed** [comment]
Yes, for this reason you treat null and undefined separately at the compiler level. I am not sure why you’re trying to say the existence of null negates all of this — it’s already dealt with & already explicit. You don’t fallthru null as undefined and vice versa, so making ? take on a new/shared meaning of null |undefined is wildly inconsistent.

**Comment by lukeed** [comment]
It’s the weekend @typescript-bot
