### ISSUE TITLE
Can access a variable before initialization in switch case in runtime

### ISSUE THREAD

**Issue by Rgvs** [microsoft/TypeScript#51334]
# Bug Report

### 🔎 Search Terms
switch, scoping, variable scoping, switch case scope

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _scoping of variables and did not find anything related to this.
- i tried in v3.9.7 to 4.6.4

### ⏯ Playground Link
https://www.typescriptlang.org/play?#code/DYUwLgBAzhC8ECYDcAoKB3AlmAxgCwAooBKCAbxQiohwEMoQIBGALkuo9EgDtaBbRvABEeEMGAB7Iag4ccE7lAmgAdJIDmBXgOIzqdBojazq2wRBFjJCaRAD0diAGFa3bhMi0cOEFBgByM38IACMQADMJACdGTG5sTFpgTAAvWjBMBQh2E3lFZRA1CU0zXRQAXyogA

### 💻 Code

let s = 2;
switch(s) {
    case 1:
        let name = "hello";
        console.log(name);
    case 2:
        name = "hello2"; // Runtime Error - Cannot access 'name' before initialization 
        console.log(name);
}

### 🙁 Actual behavior

The variable "name" is not declared and execution fails with error "Cannot access 'name' before initialization"

### 🙂 Expected behavior

The compilation of the code should fail since the 'name' is not a defined variable in case 2.
The current workaround is to put braces for each switch case.

**Comment by RyanCavanaugh** [comment]
Duplicate #19503
