### ISSUE TITLE
Emitted type declarations for private fields and methods seems wrong?

### ISSUE THREAD

**Issue by cristobal** [microsoft/TypeScript#51337]
# Bug Report

Emitted type declaration code seems to be wrong?

* Private fields and methods are emitted in the type declaration files if not marked as `@internal`.
* Private hash names fields and methods using pound sign emit an `#private` property field even when marked with `@internal`.

### 🔎 Search Terms

* type declaration emitDeclarationOnly private
* type declaration emitDeclarationOnly hash names

### 🕗 Version & Regression Information

When i started inspecting the generated typescript declarations generated.
I see the same error/behaviour when either `typescript@4.8` and `typescript@next`

This is the behavior in every version I tried, and I reviewed the FAQ for entries about emmited code and private fields and methods.

### ⏯ Playground Link
Heres the playground [link](https://www.typescriptlang.org/play?experimentalDecorators=false&emitDecoratorMetadata=false&target=99&stripInternal=true#code/PTAEGUAsHsFcBsAmA7A5AF1OyBTUOBbAS3XR0VAGNpE8cAPS+WWrXUABwCciA3AQzKgAZkRxIAzqH7IKBHNhoSA-ACgGHaF0xN+EqQAUeAsgGkcATwDuWxFIDeq0J2OC83Pm4BiYpAC4JdB5kAHNQAF5QACIPExwogG4nF08hWLcAWQUYRAAKAEpQe1AAX1VkjlgAI3giSh9xRACgolCI6MqausSK6trKLMU8wvsystUQUABRAmIyCmpWCRxCKWgAa1BAXg3AGR31ek1tKng9Q1czSxsuOwB1EkgASWQyLmR+eCLk4AAqb9AAAVaLzeH2+wAq53ckIa-lAgWCYUiMUhPWcPz+gOeOFe71AYIhqShhMGOQKRVK5WcnX6MKacJabSR1O6SSpfTqJJoZOKY3Kkxmc3IVBodEYzFoUmwRLiIl8dmkslA8iGUj0+AOOEo81AVVg6AmYH4oAAxOk0lxoBxsegLLLGqAiFJKFwcG4KI62B7qFwXVq1BotDoTvpQEZCQAJPSQABy-HkDmSpuhcr89IR7WRhNRJrNOE5wyK4zZXXqKbTrURHXZlGzzIG2S5AmYOGaCJGyWc2EdADo67T2k3YDhWRTxvzZiQhYtRUwWDhJexc3bJAq5A35WqNJrtbr9ZMjUnCS5LdbbaJ7V6XW6HVJAkR4B9na7tVZcMhQLAJBW2HggdiQVg-AhN2IH7IcQanKGkKRhIMZxvOdzYE8wK4o4aK-ACf44qC4LOIecS0qm8LfkyKIjuimFYtheK4TmkL5tyFK9CWhHloyVYlrW1YMSMo5AA) 

### 💻 Code

```ts
// Shouldn't the emitted code exclude the private fields and methods?
export class PrivateKeywords {
  private privateField:string = "private";
  private privateMethod() { }

  publicField:string = "public";
  publicMethod() {}
}

// Emmited code seems ok 👌
export class PrivateKeywordsWithInternal {
  /** @internal */
  private privateField: string = "private";
  /** @internal */
  private privateMethod() { }

  publicField: string = "public";
  publicMethod() { }
}

// Emmited code excludes the private fields and methods as expected but
// a #private property field is created is this correct?
export class PrivateHashNames {
  #privateField: string = "private";
  #privateMethod() {}

  publicField: string = "public";
  publicMethod(value:string) {
    this.publicField = value;
  }
}

// Emmited code excludes the private fields and methods as expected but
// a #private property field is created is still created when using the internal tag...
export class PrivateHashNamesWithInternal {
  /** @internal */
  #privateField: string = "private";
  /** @internal */
  #privateMethod() { }

  publicField: string = "public";
  publicMethod() { }
}
```

### 🙁 Actual behavior
Not sure if this is a bug or if its the expected behaviour.

### 🙂 Expected behavior
1. I would have expected that the emitted code would not include fields and methods marked with private
2. I would have expected that the emitted code would not include a generated `#private` property field when using hash names pounding sign.

**Comment by fatcerberus** [comment]
This is by design.

```ts
class A { private foo; }
class B { private foo; }
```

`A` and `B` here are not normally assignable to one another, which is a good thing because the meaning of `foo` may differ between the two classes.  Omitting private fields from declaration emit might make such classes cross-assignable under structural typing, which would be a pretty big footgun.

**Comment by cristobal** [comment]
> 
I see thanks for the explanation, this makes sense in terms of the what the typescript compiler does in the background as i can understand from what you describe.

**Comment by RyanCavanaugh** [comment]
`@internal` is not a supported flag; it doesn't handle `#private` fields simply because we don't use them. Please don't use `@internal` or take dependencies on its behavior, or even observe its behavior if you can help it.

**Comment by RyanCavanaugh** [comment]
The Playground shouldn't have `stripInternal` enabled; this is a website bug. `stripInternal` is an unsupported flag. I'll log a separate issue.

The rest of the behavior you see with `stripInternal` turned off is intentional per the above discussion.

**Comment by cristobal** [comment]
> The Playground shouldn't have `stripInternal` as something you can turn on; this is a website bug. `stripInternal` is an unsupported flag. I'll log a separate issue.
> 
> The rest of the behavior you see with `stripInternal` turned off is intentional per the above discussion.

@RyanCavanaugh thanks for the follow up and the rest of you guys here for the insight 👍🏽
