### ISSUE TITLE
Intersections and mutation together are unsound

### ISSUE THREAD

**Issue by camoy** [microsoft/TypeScript#51336]
# Bug Report

### 🔎 Search Terms

intersection, mutation, unsound

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, including nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.0-dev.20221025#code/PTAEFEA8EMFsAcA2BTUBGAUCgLqA9qAFygDeAbtIsQHYCusARsgE4C+oAZKRVaHYy1AAfUAGdszAJbUA5uwC83SsQAsAJlZZkuPGqJLe-Js2FiJ0uaEV4MugHQ8roAETOtuanmwB9aN6OCNPTGTngOlBgYIBAwCCigau6g0PoBzADaALqcZlKyWU5ZGNB28LSiABYAFK4AlEmePn5p3siS2BWBfMGCitDpAAyZkdFQcEioAMxJovoAytoAPGk54nkyAHxO1MgA7qAL2FX1OGJ6xIeLaxZbiqIYomp20AAmLzXOJ9p8bR0s3h1JLMggITHdwohaMhRMc7DtIEdahCoUA)

### 💻 Code

```ts
// Example 1
let o : {val: number} & {val: number | string} = {val: 42}
let o2 : {val: number | string} = o
o2.val = ""
let not_a_number : number = o.val

// Example 2
let a : number[] & string[] = []
a.push("")
let not_a_number_either : number = a[0]

// Example 3
let s : Set<number & string> = new Set()
let s2 : Set<string> = s
s2.add("")
let neither_this : number = s.values().next().value
```

### 🙁 Actual behavior

This seems like unintended unsound behavior. The interaction between intersection types and mutable values is, without suitable restrictions, unsound. (See [Davies and Pfenning, ICFP 2000](https://www.cs.cmu.edu/~fp/papers/icfp00.pdf).)

### 🙂 Expected behavior

A type error, somewhere.

**Comment by fatcerberus** [comment]
Since you've brought up soundness and linked a paper relating to type theory, for the record:
https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

Non-goal 3:
> [Do not try to] Apply a sound or "provably correct" type system. Instead, strike a balance between correctness and productivity.

Furthermore, mutation *in general* tends to produce unsoundness in TS, since the TypeScript compiler mostly pretends it doesn't happen, treating most assignments as covariant to model real-world code.  For instance, an object of type `{ foo: number }` is assignable to `{ foo: string | number }` despite that this can lead to a string unsoundly being assigned to a property of type `number`.  So this is hardly unique to intersection types and is pretty much a known quantity:

```ts
const x: { foo: number } = { foo: 42 };
const y: { foo: string | number } = x;
y.foo = "boom";
console.log(x.foo);  // type system says number; actually prints a string

const arr1: number[] = [ 42 ];
const arr2: (string | number)[] = arr1;
arr2.push("fooey");
console.log(arr1[1]);  // type system says number; actually prints a string
```

**Comment by camoy** [comment]
> Moral of the story: the TS type system doesn't model mutation well at all.

Ah. Sorry I didn't know this was a deliberate design decision, that's rather surprising. Of course I realized that TS made some soundness concessions, [as documented in the handbook](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#a-note-on-soundness), but I didn't know that mutation of any sort is generally unsound. I didn't see that mentioned anywhere.

**Comment by fatcerberus** [comment]
Yeah, `{ val: number } & { val: number | string }` reduces to just `{ val: number }` so the intersection is a red herring - `A & B` in TypeScript means “value which is simultaneously assignable to both `A` and `B`” so is not inherently unsound by itself - the real problem in this case is that object properties are compared covariantly by the assignability check.

**Comment by RyanCavanaugh** [comment]
Intersection isn't even interesting here; it's subtyping in general (!)
```ts
let o: { val: number } = { val: 42 };
let r: { val: number | string } = o;
r.val = "";
let not_a_number : number = o.val;
```
