### ISSUE TITLE
tsc 4.7 - 4.8.4 hangs indefinitely

### ISSUE THREAD

**Issue by TomMettam** [microsoft/TypeScript#51335]
# Bug Report

### 🔎 Search Terms

tsc hangs indefinitely

### 🕗 Version & Regression Information

- This changed between versions 4.6.4 and 4.7.2  (still occurs in 4.8.4)

### ⏯ Playground Link

It happens in a large project, I can't figure out exactly what is triggering the behaviour, can someone advise on how I can see what file it's getting stuck on? Or otherwise how to get some verbosity out of the compiler?

### 💻 Code

(See above)

### 🙁 Actual behavior

tsc hangs and never completes

### 🙂 Expected behavior

tsc 4.6.4 and below completes compilation after ~ 3 seconds.

**Comment by RyanCavanaugh** [comment]
I need to put this in the wiki...

The best way to start tracking these down is to attach a debugger and see which line of code is causing TS to hang:

 * Run `node --inspect-brk path/to/tsc.js --yourCmdLine` where `path/to/tsc.js` is an actual path to `tsc.js` and `--yourCmdLine` is what you would normally pass `tsc`
 * Attach with your debugger of choice (`about:inspect` in Chromium-based browsers works well)
 * Run
 * Wait for a bit, then pause the debugger to see what's going on. Depending on the stack frame, you'll have a few clues available to work from:
  * If you have a `node`, run `ts.getTextOfNode(node)` in the console to see its text. You can use `ts.getTextOfNode(node.parent)`, `ts.getTextOfNode(node.parent.parent)`, and so on, to get more context if needed
  * If something with a name that suggest it's a `symbol` is in scope, `symbol.valueDeclaration` and/or `symbol.declarations` will be a node or array of nodes (respectively) that can be inspected the same way
  * If it's crashing on a type, you can use `ts.typeToString(type)` to get more information about it. Types also usually have a `symbol` property which will in turn lead to you the node that declared them

Hope that helps!

**Comment by TomMettam** [comment]
Thanks, i'll get on that. 

(As an aside, could we consider adding a -vvv switch to get tsc to actually output what it's doing?)

**Comment by RyanCavanaugh** [comment]
TS spends a huge amount of its time running the same small handful of functions many times, so even a simple `if (verbose)` check in any one of those would have a measurable performance impact.

**Comment by C0t300** [comment]
I'm having the same exact issue on a new VM on azure. Running tsc on a (not so large) project hangs and stays 'running' for hours.

**Comment by TomMettam** [comment]
Okay, I don't know how useful this is going to be..

This code causes the infinite hang:

```
if (item.extraParams !== undefined)
{
    if (item.extraParams.lightImageData !== undefined)
    {
        if (item.extraParams.lightImageData && item.extraParams.lightImageData.texture && !item.extraParams.lightImageData.texture.equals(UUID.zero()))
        {
            const uuidStr = item.extraParams.lightImageData.texture.toString();
            if (this.textures[uuidStr] === undefined)
            {
                if (!UUID.zero().equals(uuidStr))
                {
                    this.textures[uuidStr] = new TextureAsset(this.bot, item.extraParams.lightImageData.texture);
                }
            }
        }
    }
    if (item.extraParams.sculptData && item.extraParams.sculptData.texture && !item.extraParams.sculptData.texture.equals(UUID.zero()))
    {
        const uuidStr = item.extraParams.sculptData.texture.toString();
        if (this.textures[uuidStr] === undefined)
        {
            if (!UUID.zero().equals(uuidStr))
            {
                this.textures[uuidStr] = new TextureAsset(this.bot, item.extraParams.sculptData.texture);
            }
        }
    }
}
```

If i remove either of the above blocks, e.g

```
if (item.extraParams !== undefined)
{
    if (item.extraParams.lightImageData !== undefined)
    {
        if (item.extraParams.lightImageData && item.extraParams.lightImageData.texture && !item.extraParams.lightImageData.texture.equals(UUID.zero()))
        {
            const uuidStr = item.extraParams.lightImageData.texture.toString();
            if (this.textures[uuidStr] === undefined)
            {
                if (!UUID.zero().equals(uuidStr))
                {
                    this.textures[uuidStr] = new TextureAsset(this.bot, item.extraParams.lightImageData.texture);
                }
            }
        }
    }
}
``

Then it does complete the compilation, albeit very slowly 

```
└─$ time tsc

real    41.11s
user    45.03s
sys     0.11s
cpu     109%
```

Without either block:

```
└─$ time tsc

real    4.05s
user    7.76s
sys     0.14s
cpu     194%
```

If i re-arrange the code a bit, it is fine:

```
if (item.extraParams !== undefined)
{
    if (item.extraParams.lightImageData)
    {
        const texture = item.extraParams.lightImageData.texture;
        if (texture && !texture.equals(UUID.zero()))
        {
            const uuidStr = texture.toString();
            if (this.textures[uuidStr] === undefined)
            {
                if (!UUID.zero().equals(uuidStr))
                {
                    this.textures[uuidStr] = new TextureAsset(this.bot, texture);
                }
            }
        }
    }
    if (item.extraParams.sculptData)
    {
        const texture = item.extraParams.sculptData.texture;
        if (texture && !texture.equals(UUID.zero()))
        {
            const uuidStr = texture.toString();
            if (this.textures[uuidStr] === undefined)
            {
                if (!UUID.zero().equals(uuidStr))
                {
                    this.textures[uuidStr] = new TextureAsset(this.bot, texture);
                }
            }
        }
    }
}
```

```
└─$ time tsc

real    5.52s
user    9.62s
sys     0.13s
cpu     176%
```

I ran `node --prof /usr/lib64/node_modules/typescript/lib/tsc.js` (left it running for five minutes, with the first code block I pasted above) and got the results as attached.

[profile.zip](https://github.com/microsoft/TypeScript/files/9894756/profile.zip)

(The report is incomplete because it ran out of memory even with a 64gb heap >.<)

**Comment by TomMettam** [comment]
I ran the profiler again with a much shorter (1 minute) run, and it completed the analysis

[processed3.zip](https://github.com/microsoft/TypeScript/files/9894767/processed3.zip)

**Comment by bdrazen** [comment]
For me the issue seems to be an infinite loop occurring within [`inferFromMatchingTypes`](https://github.com/microsoft/TypeScript/blob/v4.8.4/lib/typescript.js):

```
function inferFromMatchingTypes(sources, targets, matches) {
    var matchedSources;
    var matchedTargets;
    for (var _i = 0, targets_1 = targets; _i < targets_1.length; _i++) {
        var t = targets_1[_i];
        for (var _a = 0, sources_1 = sources; _a < sources_1.length; _a++) {
            var s = sources_1[_a];
            if (matches(s, t)) {
                inferFromTypes(s, t);
                matchedSources = ts.appendIfUnique(matchedSources, s);
                matchedTargets = ts.appendIfUnique(matchedTargets, t);
            }
        }
    }
    return [
        matchedSources ? ts.filter(sources, function (t) { return !ts.contains(matchedSources, t); }) : sources,
        matchedTargets ? ts.filter(targets, function (t) { return !ts.contains(matchedTargets, t); }) : targets,
    ];
}
```
No idea what's going on but seems to be resolved in v5.

**Comment by RyanCavanaugh** [comment]
We need a standalone repro we can test locally in order to investigate this. Please open a new issue if you have one. Thanks!
