### ISSUE TITLE
Cannot delete from inferred types without typing them first

### ISSUE THREAD

**Issue by gabriel-peracio** [microsoft/TypeScript#51340]
# Bug Report

### 🔎 Search Terms

Cannot `delete` from inferred types without typing them first

### 🕗 Version & Regression Information

- This changed between versions 3.9 and 4.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBBIFsCmB5ARgKycWBeGA3gLABQM5MAZiCAFwwDkaAhgE4MA0pFMLAXvSisArklIBfUqQAmSADZIoSOIlSZsUAHTUQMAPR6YAFQAWykAAckrZmGkwQlGM0ayFShg6s2oIVjARhaF5zCygAS3BmOU0ACgAmAHYATgAGAEopEiA)

### 💻 Code
```ts
const someObject = {
    foo: 'bar',
    baz: true
}

delete someObject.foo // The operand of a 'delete' operator must be optional.(2790)
```

### 🙁 Actual behavior

You cannot delete from a literal object without facing the error.
You are forced to type the object, marking the property you want to delete as optional, even though it is not optional up until that point.

### 🙂 Expected behavior

Since you never provided a type to the object, you should be able to delete from it, and afterwards it gets marked as optional.
Alternatively, the check should be divorced from `strictNullChecks` so it can be turned off separately

**Comment by fatcerberus** [comment]
This is intentional.  You also can’t assign *new* properties after the fact either.

**Comment by RyanCavanaugh** [comment]
This behavior was specifically requested; see #13783.
