### ISSUE TITLE
Control Flow Evaluation for Instantiation Expressions

### ISSUE THREAD

**Issue by sinclairzx81** [microsoft/TypeScript#51346]
# Suggestion

Hi. I was wondering if it was possible for TypeScript to evaluate function control flow when inferring via instantiation expression.

```typescript
const Foo = <T extends 1 | 2>(input: T) => input === 1 ? 'hello' : 'world'

type A = ReturnType<typeof Foo<1>> // expect 'hello', 
                                   // actual 'hello' | 'world'

type B = ReturnType<typeof Foo<2>> // expect 'world'
                                   // actual 'hello' | 'world'
```

## 🔍 Search Terms

instantiation expression control flow return type 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

I was actually experimenting to see if it were possible to replicate `{ [K in keyof T]: T[K] }` mapped types as runtime type constructs. 

The following is the general approach I had mind, but do note the requirement for instantiation expressions to factor control flow in evaluating the return type.

```typescript
const T = Type.Object({                           // type T = {
  x: Type.Number(),                               //   x: number
  y: Type.Number(),                               //   y: number
  z: Type.Number()                                //   z: number
})                                                // }

const M = Type.Mapped(T, (T, K) => {              // type M = {
  switch(K) {                                     //    [K in keyof T]: 
     case 'x': return T.properties[K]             //        K extends 'x' ? T[K] :
     case 'y': return Type.String()               //        K extends 'y' ? string :
     case 'z': return Type.Boolean()              //        K extends 'z' ? boolean :
     default: throw 1                             //        never
  }                                               // }
})                                                //
                                                  // where the callback is                                                  
                                                  //
                                                  //   (K, T) => { ... } is Func<T, K extends keyof T['properties']>
                                                  // 
                                                  // ... and where Func<T, K> should infer
                                                  //   
                                                  //   ReturnType<typeof Func<T, 'x'>> is TNumber
                                                  //   ReturnType<typeof Func<T, 'y'>> is TString
                                                  //   ReturnType<typeof Func<T, 'z'>> is TBoolean
                                                  // 
                                                  // ... and allow for the mapping
                                                  //
                                                  // {
                                                  //    [K in keyof T]: ReturnType<typeof Func<T, K>>
                                                  // }

type M = Static<typeof M>                         // type M = {
                                                  //   x: number,
                                                  //   y: string,
                                                  //   z: boolean
                                                  // }
```

## 💻 Use Cases

Am mostly interested in the feature for [this](https://github.com/sinclairzx81/typebox) library.

**Comment by RyanCavanaugh** [comment]
Generics aren't templates, so no. The inferred type of `Foo` is the only thing that matters, and it's `<T extends 1 | 2>(input: T) => ("hello" | "world")`. You'd need to make the return type explicitly `T extends 1 ? "hello" : T extends 2 ? "world" : "hello" | "world"`

**Comment by sinclairzx81** [comment]
@RyanCavanaugh Hi, thanks for the quick response!

Ah, I didn't think it was feasible but thought I'd ask. I was actually hoping to avoid the explicit `T extends 1 ? "hello" : T extends 2 ? "world" : "hello" | "world"` if possible (as this information would already be encoded in the function body).

I guess the hope was that there might be a way to use type narrowing within the function to derive that conditional mapping automatically (this by propagating the narrowed type within the body to the return type and setting up the `1 => 'hello'`, `2 => 'world'` mapping which could be used later for instantiation)

It doesn't sound like this is feasible, so will close off this issue.
Thanks

**Comment by fatcerberus** [comment]
@sinclairzx81 https://github.com/microsoft/TypeScript/issues/33912 is probably relevant.  It’s basically what you’re asking for, taken one step further (you want to infer the conditional type *ex nihilo* rather than just relating CF to an existing conditional type).

**Comment by sinclairzx81** [comment]
@fatcerberus Hey, thanks for the reference :) Will read up
