### ISSUE TITLE
Unable to use tab/enter to have intellisense complete let/const declarations

### ISSUE THREAD

**Issue by senseiweb** [Microsoft/TypeScript#5135]
In VS 2015, unable to use to tab/enter to select intellisense variables that have been declared as const/let. 

`const isExample = true;`

`isExample` will appear in the intellisense list; however, when pressing tab/enter/punct to select `isExample` nothing happens. Changing the variable declaration to var corrects the problem.

**Comment by senseiweb** [comment]
Fixed in 1.6

**Comment by senseiweb** [comment]
Further testing reveals the problem still in existing 1.6 beta

**Comment by mhegazy** [comment]
I can not get this to reproduce locally, though @DanielRosenwasser mentioned he ran into something similar yesterday. there should not be any functional difference between a variable declared as `const` and that as `var` except for the icon. can you share more context on when this happens?

**Comment by senseiweb** [comment]
So after more testing, expected behavior achieved in all scenarios except when used inside a exported default class. Will provide a video in a couple of minutes

Example
`export default class TestExample {
    constructor() {
        const isWorking = false;
        if (isW)
    }
}`

**Comment by mhegazy** [comment]
Can you try without resharper? i can not get this to repro.

**Comment by DanielRosenwasser** [comment]
The thing I ran into was actually the following:

![image](https://cloud.githubusercontent.com/assets/972891/11162758/31585a4a-8a65-11e5-879e-be1efb1d38ce.png)

where the const declaration is prioritized lower than the type even though the type's casing is less appropriate.

**Comment by DanielRosenwasser** [comment]
The same behavior appears if I use a `let` declared variable

![image](https://cloud.githubusercontent.com/assets/972891/11162777/b5e13c14-8a65-11e5-9b49-24f63446af6f.png)

however, with a `var`, things go as expected:

![image](https://cloud.githubusercontent.com/assets/972891/11162780/ca135f96-8a65-11e5-8d80-e1d4fa3bd6a0.png)

If this is the same behavior you're seeing, let us know, but otherwise I'll open up a new bug.

**Comment by DanielRosenwasser** [comment]
I opened up #5714 until we can get some detail from @senseiweb.

**Comment by senseiweb** [comment]
@DanielRosenwasser As requested...disabled reshaper and the problem does indeed resolves; after re-enabling reshaper the problem returns. So I am assuming the bug needs to file with the JetBean team, correct?

**Comment by senseiweb** [comment]
For completeness opened a bug with the JetBrains team ==> referenced: https://youtrack.jetbrains.com/issue/RSRP-451140

**Comment by DanielRosenwasser** [comment]
Thanks for the update! Glad we were able to identify the other bug though :smiley:

**Comment by zhuravlik** [comment]
To let others with the same problem know, this issue is fixed in ReSharper 10.0.
