### ISSUE TITLE
Overloading built-in methods of strings does not work

### ISSUE THREAD

**Issue by parzhitsky** [microsoft/TypeScript#51358]
# Bug Report

For a custom template literal type, defining and using a type guard overload of a built-in method of primitive strings does not narrow down the value.

### 🔎 Search Terms

template string literal override primitive method type guard

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about template literals

### ⏯ Playground Link

[Playground link with relevant code](https://tsplay.dev/w17eAm)

### 💻 Code

```ts
type Digit = `${0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}`;
type DigitStatusCodeGroup = `${1 | 2 | 3 | 4 | 5}`;

type StatusCodeBare = `${DigitStatusCodeGroup}${Digit}${Digit}`

// `this` type can be only used in class method definitions
declare abstract class StatusCodeMixinStartsWith extends String {
  public override startsWith<D extends DigitStatusCodeGroup>(
    this: StatusCodeBare,
    digit: D,
  ): this is `${D}${string}`
}

export type StatusCode = StatusCodeBare & StatusCodeMixinStartsWith
```

```ts
type StatusCode4xx = `4${Digit}${Digit}`

declare function expectsStatusCode4xx(statusCode4xx: StatusCode4xx): void
declare const statusCode: StatusCode

if (statusCode.startsWith('4')) {
    expectsStatusCode4xx(statusCode) // (1)
}
```

### 🙁 Actual behavior

Compiler error (not assignable): the type of `statusCode` is broader than the type of `statusCode4xx` parameter of `expectsStatusCode4xx(…)` function.

Note that [the approach of adding a _new, custom_ method](https://tsplay.dev/WKOYpW) (such as `.isClientError()` in this case) works as intended.

### 🙂 Expected behavior

The `statusCode` variable is assignable to the parameter of `expectsStatusCode4xx(…)` at the line `(1)`

**Comment by parzhitsky** [comment]
I suspect, that the root cause is that `this` is internally constrained to be a non-primitive value. But if so, it should be visible externally as well somehow.

**Comment by RyanCavanaugh** [comment]
This is one of the very small number of cases where intersection order matters, because intersection order controls overload order, and overload order matters because the first applicable overload is selected. You need to write
```ts
export type StatusCode =  StatusCodeStartsWithMixin & StatusCodePrimitive;
```
and everything works as expected

**Comment by parzhitsky** [comment]
Interesting. Is this a deliberate design choice or just an artefact of implementation?
