### ISSUE TITLE
Type narrowing with `throw` on some types

### ISSUE THREAD

**Issue by rostamiani** [microsoft/TypeScript#51369]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.
narrowing, typescript, throw, exception

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
throwing error can narrow down types. when throwing error prevents some types to exist

## 📃 Motivating Example
```ts
function errorIfNumber(input: string | number) {
  if (typeof input === "number") {
    throw 'error';
  }
}

function app(response: string | number) {
  errorIfNumber(response);
  const x = response; // This should be string
}

```

## 💻 Use Cases
Error handling.
When you have a `handleErrors` function and after that there is not any errors.

**Comment by MartinJohns** [comment]
You can write assertion functions for this. This feature already exists since TypeScript 3.7 (November 2019)
