### ISSUE TITLE
Support for multiple, root-level tsconfigs

### ISSUE THREAD

**Issue by kylemh** [microsoft/TypeScript#51382]
https://github.com/microsoft/TypeScript/pull/48189 and https://github.com/microsoft/TypeScript/issues/35395#issuecomment-1239843287 are really nice new additions, but ones that are incredibly limited by my inability to have VS Code be aware of the fact that some files are using a different TS Config.

Sure, I could use different TS Configs in different folders so findup resolves rules correctly; however, that's not always ideal!Imagine a typical `components` folder full of folders that house component source code, test files, and maybe Storybook files...

```txt
component
        ├── __tests__
        |       └ component.test.tsx
        ├── __stories__
        |       └ component.stories.tsx
        └── component.tsx
```

Different file suffixes and different contexts ripe for developer experience improvements; however, to actually provide different tsconfig contexts to these files, I'd need:

```txt
component
        ├── __tests__
        |       ├ tsconifg.test.json
        |       └ component.test.tsx
        ├── __stories__
        |       ├ tsconifg.stories.json
        |       └ component.stories.tsx
        └── component.tsx
```

This is untenable. Instead, I wanted to suggest the ability to map multiple TS Configs to VS Code where in-project collisions are checked for (so no 2 tsconfigs read the same file). If there are no collisions, VS Code will choose the correct tsconfig regarding the file in view. If there are collisions, then warn that VS Code isn't certain about which `tsconfig.json` to use and try to fail the compiler at top-of-file.

**Comment by mjbvz** [comment]
Related #33094
