### ISSUE TITLE
package.json `exports` field not respected in scoped packages

### ISSUE THREAD

**Issue by davewasmer** [microsoft/TypeScript#51381]
# Bug Report

It seems that scoped packages (i.e. packages with names prefixed by `@org/...`) within a monorepo have the `exports` field of their package.json ignored.

### 🔎 Search Terms

package.json, exports field, scoped packages, Cannot find module

### 🕗 Version & Regression Information

Tested on 4.8.4

### Reproduction

[Reproduction repository](https://github.com/davewasmer/scoped-package-exports-repro)

### 💻 Code

```ts
import add from 'shared'; // works fine
import scopedAdd from '@scoped/shared'; // identical package except for scope
// Cannot find module '@scoped/shared' or its corresponding type declarations
```

### 🙁 Actual behavior

Couldn't resolve the exports for the `@scoped/shared` package

### 🙂 Expected behavior

Both packages (`@scoped/shared` and `shared`) should resolve according to their `exports` field in their respective package.json files.

**Comment by bertho-zero** [comment]
I have the same error, `exports` is ignored in a monorepo but with or without scoped module.

I can work around this problem by adding `moduleResolution` to `nodenext`, but that gives me other problem: `export *` from another package which was not a problem so far gives me the error: `TS2305: Module '"@org/uikit"' has no exported member 'Box'`

I don't understand anything, I always have one or the other error.

**Comment by weswigham** [comment]
The package's [package.json](https://github.com/davewasmer/scoped-package-exports-repro/blob/master/packages/shared/package.json#L2) says the package name is `shared` and not `@scoped/shared`, which is the root of our confusion. A namespaced package usually has to list the namespace in the `name` in its `package.json`.

**Comment by davewasmer** [comment]
@weswigham thanks for looking into this!

Actually, [the line you linked to](https://github.com/davewasmer/scoped-package-exports-repro/blob/7f9e607028a66d3d902237856c93eccb5b938ccd/packages/shared/package.json?rgh-link-date=2023-01-04T20%3A40%3A10Z#L2) is from the [**non-scoped** `shared` package](https://github.com/davewasmer/scoped-package-exports-repro/tree/master/packages/shared) - there are two dependencies, one scoped and the other not. I probably should have named them differently to avoid confusion.

The [package.json you linked to](https://github.com/davewasmer/scoped-package-exports-repro/blob/7f9e607028a66d3d902237856c93eccb5b938ccd/packages/shared/package.json?rgh-link-date=2023-01-04T20%3A40%3A10Z#L2) is for the `shared` package, which was intentionally not scoped to show that it was working correctly.

[This package.json](https://github.com/davewasmer/scoped-package-exports-repro/blob/7f9e607028a66d3d902237856c93eccb5b938ccd/packages/scoped-shared/package.json#L2) is for the `@scoped/shared` package, which is not working (and correctly lists its own name as `@scoped/shared`.

Sorry for the confusing naming!

**Comment by weswigham** [comment]
Um, well, for starters, there's no `packages/app/node_modules/@scopes/shared` folder. Pretty simple way to not find any types is them just not being there. Rerunning `pnpm i` inside `app` gets it linked it and running.

**Comment by davewasmer** [comment]
Sorry @weswigham, not sure how I managed to mess that install up. Thanks for taking the time to investigate, much appreciated.
