### ISSUE TITLE
Type inference not working when assigning somewhere in the function chain

### ISSUE THREAD

**Issue by cveld** [Microsoft/TypeScript#5138]
Using TypeScript 1.6 in Visual Studio 2015 RTM, the following code does not provide intellisense:

```javascript
var x;

function init() {
    x = {
        color: "blue",
        height: "50"
    };
}

init();
x.???
```

Is this something on TypeScript's roadmap to solve?
Or what is the best way to refactor? Ideally I would have intelligent support in Visual Studio that lifts the assignment towards the variable declaration, e.g.:

```javascript
var x: { color; height };
function init() {
    x = {
        color: "blue",
        height: "50"
    }
}

init();
x.color = ...
```

**Comment by RyanCavanaugh** [comment]
We only infer from the initialization of a variable, not from other assignments. There is no plan to change that.

I would write the code this way given what's declared:
```ts

function init() {
    return {
        color: "blue",
        height: "50"
    }
}

var x = init();
x.color = ...
```

**Comment by glen-84** [comment]
Is this the same as:

![ts](https://cloud.githubusercontent.com/assets/261509/12005955/8c87ab72-abc7-11e5-810b-6cf3454f5cab.png)

Is line 11 an assignment and not an initialization? I suppose the property on line 8 gets initialized as `null` or something?

I know I could use `constructor(private http: HttpClient) {`, but I think that I prefer the more explicit declaration of the property.

I guess this means that I have to assign a type to the property in addition to the constructor argument.

**Comment by DanielRosenwasser** [comment]
@glen-84 yes, you need to specify the type on `http` itself.

You can also use parameter properties instead:

```ts
export class Index {
    // Notice the use of 'public' before 'http', which automatically
    // declares and initializes a property named 'http'.
    constructor(public http: HttpClient) { }

    async activate() {
        try {
            let x = await this.http.fetch("https://cors-text.appspot.com/test");
            console.log(x);
        }
        catch (e) {
            console.log(e);
        }
    }
}
```

**Comment by glen-84** [comment]
@DanielRosenwasser Thanks, that's what I suspected.
