### ISSUE TITLE
`"moduleResolution": "NodeNext"` Could not find a declaration file for module 'pony-cause'

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#51406]
# Bug Report

`"moduleResolution": "NodeNext"` Could not find a declaration file for module 'pony-cause'

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions __>=4.8.4____ and ___5.0.0-dev.20221103____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 🙁 Actual behavior

tsconfig extends `@tsconfig/node18-strictest-esm`

```jsonc
      "moduleResolution": "NodeNext",
```
```ts
// typescript error
import { ErrorWithCause } from 'pony-cause'
void ErrorWithCause
```

```
Could not find a declaration file for module 'pony-cause'. 'pony-cause@2.1.4/node_modules/pony-cause/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/pony-cause` if it exists or add a new declaration (.d.ts) file containing `declare module 'pony-cause';
```

### 🙂 Expected behavior

tsconfig extends `@tsconfig/node18-strictest-esm`

```jsonc
      "moduleResolution": "Node",
```

```ts
// OK
import { ErrorWithCause } from 'pony-cause'
void ErrorWithCause
```

### Additional
I want to package-self-reference.

To have `package/foobar/test.mjs`
```js
import {} from 'foobar'
```
instead of 
```js
if (isBrowser) {
 await import('./browser.mjs')
} else {
 await import('./node.mjs')
}
```
Any workaround are welcome.

Currently, 
- If I use `"moduleResolution": "NodeNext"`, I'm able to package-self-reference. But some modules cannot find dts.
- If I use `"moduleResolution": "Node"`, dts are correct. But cannot package-self-reference.

### Suggestion
- Fix `"moduleResolution": "NodeNext"` cannot find dts for some modules.
- Or backport package-self-reference to `"moduleResolution": "Node"`

**Comment by tpluscode** [comment]
Just found the same problem with my package `@tpluscode/rdf-ns-builders`. It comes with its own type declaration and with `NodeNext` and `Node16` the compiler complains that they cannot be found

**Comment by tpluscode** [comment]
@weswigham is there anything special required for double-target packages? So far I have been publishing them something like

```
module.js
module.mjs
module.d.ts
```

There was always one `.d.ts` for every compiled module. Is this different problem that that of pony-cause and I should create a new issue?
