### ISSUE TITLE
Implicit return type too generic

### ISSUE THREAD

**Issue by rentalhost** [microsoft/TypeScript#51408]
# Bug Report

### 🔎 Search Terms

implicit return type, return type incorrect array

### 🕗 Version & Regression Information

4.8.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQGoEMA2JUAUAlIgN4CwAUIjYgE7oh1IDaiAjAEwDMANIgHIAzlDowwyAYgC6VAL5UqAeiWIACnTgAHVHSgBPQVDgAxGAA9UAEylW4qIYjBwoiVOZgjECRAZ2CRMQlEAB8nEABbACNdAQA6ZVV1TR09QwFjM0sbRDsHJxc3Dy8fP1QA0XFJBMo0TFx8YhYABmk4zItrAmaiRUoVFHRsPEISMsRPRAJAqtDw6N0iFmkJsBFULCtvYEQWMEiYun4ZiWkgA)

### 💻 Code

```ts
function getValue() {
    return [ 123, 'string' ]
}

// Property 'toFixed' does not exist on type 'string | number'.
//  Property 'toFixed' does not exist on type 'string'.
getValue()[0].toFixed(0)

// getValue() type is (string | number)[] instead of [number, string]
```

### 🙁 Actual behavior

The return type of `getValue()` is clearly `[number, string]`, which mean that we can run `getValue()[0].toFixed(0)`, right? The problem is that Typescript will infer that the return type is `(string | number)[]`, which could be true, but not is precise.

For example, visibly our return is an array containing only two items only, which means that we can access `[0]` which is a `number` and `[1]` which is a `string`, and there is nothing beyond that. However, with the type inferred by Typescript, we can access other keys without error: `console.log(getValue()[123123])`.

A possible fix is to reinforce the type manually, only this situation is clear the return type and I believe it would be interesting for Typescript to determine this on its own:

```ts
function getValue(): [number, string] {
    return [ 123, 'string' ]
}
```

**Comment by fatcerberus** [comment]
`return [ 123, 'string' ] as const;`

**Comment by MartinJohns** [comment]
The inferred return type being widened is intentional. Changing this with the introduction of tuples would have been a **massive** breaking change. Using a const-context as mentioned by fatcerberus is the way to go.

**Comment by rentalhost** [comment]
Nice, @fatcerberus suggestion works pretty fine.
