### ISSUE TITLE
Automatic type guard

### ISSUE THREAD

**Issue by rentalhost** [microsoft/TypeScript#51409]
# Suggestion

## 🔍 Search Terms

automatic type guard, smart type guard

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Typescript can perform type narrowing in certain circumstances intelligently (and every day I am more surprised). However, `type`s are not JS compatible, so something like `instanceof SomeType` is not allowed, as during conversion the `type` is lost.

In this case, we can perform a _type guard_ manually, so that we can determine that the information we are receiving is compatible with the expected type.

For example (**[Playground](https://www.typescriptlang.org/play?ssl=17&ssc=43&pln=1&pc=1#code/C4TwDgpgBAggdgSwLYEMA2UC8UDeU4pIQBcUAzsAE4JwDmA3FCrSfgK5IBGElUAvvQBQoSFABqEABYIAxmmjY8BIqQrU6jTpRRwAJqqo1a-IYIBmbODOAIA9nCgIy8ZOgAUAD1I6QASlIejmSwiKgYOIJQUJQQwGyUDgBEzBCJjg4eQnzmltZ2Dk4S0nIQnt5wfgFB4lKy8riR0bHxSUi2uhBoaTRQmYLZOVY29lBotrRuCMAQSKQuYVAAPjXF8r4NUQhmUG4A5Cm76Y7TSOsy9mS28gB0YxNTM9cpvkJRnWTQWzu7Wjq6hz0HqcoOc4JcbndJidrr89C9+oJBJClIRWIkAEoQDyJAA0TBYpAAzPx4cj8KjSIkAMK2ShXNAoXFQWH6KCJAAqthAtmAjJJQiAA)**):

```ts
type Animal = { name: string; age: number };
type Vehicle = { name: string; brand: string };

function isAnimal(x: any): x is Animal {
  return "age" in x;
}
function isVehicle(x: any): x is Vehicle {
  return "model" in x;
}

function log(item: Animal | Vehicle) {
  if ('age' in item) console.log(item.age);
  else if ('brand' in item) console.log(item.brand);
}

log({ name: "Rex", age: 3 });
log({ name: "Corolla", brand: "Toyota" });
```

This will work perfectly. But suppose at some point I say that `Vehicle` will now have `age` and `Animal` will have `breed`.

```ts
type Animal = { name: string; age: number, breed: string };
type Vehicle = { name: string; age: number; brand: string };
```

In this case, our `isAnimal()` type guard will incorrectly interpret that a vehicle is an animal. Because the type guard works on top of information that is now common to both.

To solve the problem, we can change the way `isAnimal()` works, making it work by checking if it has `breed` instead:

```ts
function isAnimal(x: any): x is Animal {
  return "breed" in x;
}
```

However, whenever something similar happens, we need to be careful to make sure that our type guard conforms to the uniqueness of the type, while not conflicting with another possible similar type (not shown here).

So my suggestion is that Typescript could actually use `item instanceof <Type>`, and it could intelligently infer (whenever possible) a type guard for the expected type.

```ts
function log(item: Animal | Vehicle) {
  if (item instanceof Animal) console.log(item.age);
  else if (item instanceof Vehicle) console.log(item.brand);
}
```

In this case, even though `Animal` is a `type` (which in principle is impossible nowadays), Typescript would automatically check how it could safely type narrow inside this function, based on the type of data of `Animal` in relation to the union `Animal | Vehicle`.

So in our first example, the code would convert to something like:

```ts
function log(item) {
    if ('age' in item) console.log(item.age);
    else if ('brand' in item) console.log(item.brand);
}
```

And if the signature of `Animal` and `Vehicle` changes, as in the second example, the generated code would automatically change to ensure that the function has the same behavior:

```ts
function log(item) {
    if ('breed' in item) console.log(item.age);
    else if ('age' in item) console.log(item.brand);
}
```

Note: in this `else if()` we can use `'brand' in item` or `'age' in item` because although `age` belongs to both types, `if()` has already captured the `Animal` type.

**Comment by fatcerberus** [comment]
This violates the design goals of TS, in particular these two checkboxes in the issue template:

> This could be implemented without emitting different JS based on the types of the expressions

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

That TypeScript types are 100% invisible at runtime is by design.

**Comment by MartinJohns** [comment]
`instanceof` is a JavaScript operator that checks the prototype chain. There's no such thing for the types of TypeScript, only for classes.

**Comment by rentalhost** [comment]
@MartinJohns Yes, but that's exactly what I'd like to suggest. 

As `instanceof` is currently used exclusively for classes on JS, so `instanceof Type` would be currently invalid code, which would avoid any BC. 

Another option would be to make this clearer, for example allowing the use of `typeof` in this type of context (eg. `if(item typeof Type)`), but I believe it could generate BC and "cognitive conflict" with JS `typeof`. 

Or creating a new operator, for example `istype` or `is` only (eg `if(item is Type)`). 

Or as a method of `type` itself: `if (Animal.accept(item))`.

**Comment by MartinJohns** [comment]
It's against TypeScripts Language Design Goals and was rejected several times already.

**Comment by fatcerberus** [comment]
@rentalhost https://github.com/microsoft/TypeScript/issues/47658#issuecomment-1026298039

> Regarding design goals - we're extremely committed to the erasability of the type system. Keeping the type system erasable is a very strong invariant that allows us to do other important things. One of the reasons we're able to make the type system more powerful and expressive from version to version is that we have the flexibility to e.g. change type inference at a particular position from { x: string } & { y: number } to { x: string; y: number } without worrying about breaking the runtime behavior of anyone's programs.
>
> This isn't a theoretical concern: people already @ us about when we change declaration emit in ways that produce representationally-distinguishable but semantically-identical types. Taking this to the next level wherein one person's bug about a conditional type not immediately resolving becomes a breaking change in someone else's program, at runtime, in ways that are going to be much more subtle than type error vs not-a-type-error -- it's not a Pandora's Box we're keen to open.
