### ISSUE TITLE
[oninput ]: Which callback parameter should be?`Event  `or`InputEvent`

### ISSUE THREAD

**Issue by RSS1102** [microsoft/TypeScript#51413]
# Bug Report

### 🕗 Version & Regression Information

I read a lot of discussions about this,:https://github.com/microsoft/TypeScript/issues/39925
And this pr, I want to say what progress?:https://github.com/microsoft/TypeScript/pull/50039
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```html
  <input id="proxyInput" value="" oninput="onInput" />
```

```ts
const proxyInput = document.getElementById("proxyInput");
proxyInput!.oninput = (e:Event) => {
  console.log("1", e);
};
```
### 🙁 Actual behavior
When I `console.log (e)` is marked as `InputEvent`, and I get a warning error when I get the attributes below it.
![image](https://user-images.githubusercontent.com/81673017/200099705-8d5ed4bf-202b-4945-9da8-fb73c5cc9e7d.png)
![image](https://user-images.githubusercontent.com/81673017/200099761-af3ac1b2-7f13-4b71-8b31-132aec0c5e96.png)

### 🙂 Expected behavior
Its parameter type should be `InputEvent`, not `Event`
![image](https://user-images.githubusercontent.com/81673017/200099775-1547e018-9386-4871-9484-2e746f8d9e04.png)

**Comment by MartinJohns** [comment]
It should be `Event`. You can find an explanation here: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1174#issuecomment-933042088

**Comment by RSS1102** [comment]
> It should be `Event`. You can find an explanation here: [microsoft/TypeScript-DOM-lib-generator#1174 (comment)](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1174#issuecomment-933042088)

wuwu~~，thanks，i konw why use `Event`.But it seems that I can't use `Event` well, so I gave an `any`.:joy: 
Thank you again for your explanation.

**Comment by MartinJohns** [comment]
The safest option is to make sure you're dealing with an `InputEvent` using the `instanceof` operator. The alternative is to just tell the compiler to treat it as one using an type assertion with `as`.

I would avoid using `any`.

**Comment by RSS1102** [comment]
> 

ok,ok,Thank you very much for your advice. Thank you.
:satisfied:
