### ISSUE TITLE
Indexed array access type is not possibly undefined with noUncheckedIndexAccess enabled

### ISSUE THREAD

**Issue by bsssshhhhhhh** [microsoft/TypeScript#51419]
# Bug Report

### 🔎 Search Terms

noUncheckedIndexAccess, array

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about noUncheckedIndexAccess

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/MYewdgzgLgBAhgJwQLhtBBLMBzA2gXRgF4YCBuAWAChqoBPABwFMYBJMUJJ4KAQSTh0AKoxYl6zEADN4SXAAZ8ZGAHoVaKJhzVqamFAAWTBEwDkEeDADuIBAGtEIAK5gAJgBoYAIyewMfsAA3EAAbQKYLBBcoDABbFhBwhCM4V2pQSFhOEx5iWQQFJVpRGABhWxy+AWES8VFpGGzuKGU9dCxsGAAfGBdXJiksJlcgA)

### 💻 Code

With `noUncheckedIndexAccess` enabled:

```ts
const arr: string[] = [];

type IncorrectArrayType = typeof arr[0]; // string

// there's a workaround, but it involves runtime overhead
const correct = arr[0];
type CorrectArrayType = typeof correct; // string | undefined
```

### 🙁 Actual behavior

Indexing an array type doesn't include `undefined` with noUncheckedIndexAccess enabled

### 🙂 Expected behavior

`IncorrectArrayType` should be `string | undefined`

**Comment by whzx5byb** [comment]
This is by design and you could find more details in https://github.com/microsoft/TypeScript/pull/39560. See the last section: `Design Point: What's the type of T[number] / T[string]`.

**Comment by bsssshhhhhhh** [comment]
Okay. Thank you for the link
