### ISSUE TITLE
TSC 4.8.4 hangs up when compiling a small file

### ISSUE THREAD

**Issue by cassioarosa** [microsoft/TypeScript#51412]
# Bug Report

The issue can be seeing in playground by switching from .js tab to another tab, then switching back go .js tab. Image below.

<img src="https://user-images.githubusercontent.com/3159047/200093477-4abec0c0-b9ae-453f-af52-774355b2da59.png" width="400" />

When compiling the file via, ``npx tsc filename.ts`` the compilation takes to long to produce a result.

When using ``ts-jest`` was not possible to get a result, the test keeps running.

### 🔎 Search Terms

- TSC Hang up
- Version 4.8.4

### ⏯ Playground Link

[Link](https://tsplay.dev/WJX6DN)

### 💻 Code

``` typescript

import { Collection } from "mongodb";

function getCollection<TSchema extends Document = Document>(
  name: string
): Collection<TSchema> {
  const value: any = null;

  return value;
}

async function foo() {
  await getCollection("COLLECTION_NAME").deleteMany({});
}

```

### 🙂 Expected behavior

If possible, a faster response. 

### Possible related issues

- #51335
- #47810

**Comment by ahejlsberg** [comment]
Short story... The `mongodb` types are creating insane amounts of work when passed a relatively large type such as `Document`. The compiler eventually reports a "Type instantiation is excessively deep and possibly infinite" error, but with these particular types it takes a while to reach the 5M types required to trigger the type instantiation limiter.
