### ISSUE TITLE
typescript cannot write file because it would overwrite input file in yarn workspace

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [microsoft/TypeScript#51414]
# Bug Report

We're working on a really big monorepo where packaged depends on each other. 
Since dependencyA can depend on dependencyB while dependencyB depends on dependencyA we get into trouble running tsc.

There is no way to get rid of this issue.
This is the behavior in every version I tried

### 🙁 Actual behavior

It prints
`error TS5055: Cannot write file '/bla/bla/bla/projects/bla/source/packages/entity/build/graphql/Entity.d.ts' because it would overwrite input file.`

### 🙂 Expected behavior

It should be possible to have cycling dependencies as long as they are packages

**Comment by RyanCavanaugh** [comment]
There are definitely people out there using TypeScript with yarn monorepos who have configured them in a way that doesn't produce this error.

If you share a sample repo someone might be able to help you fix the misconfiguration.
