### ISSUE TITLE
TS understand a type change inside a boolean operation, but not when part of the boolean expression is extracted into a function

### ISSUE THREAD

**Issue by ninofiliu** [microsoft/TypeScript#51425]
# Bug Report

### 🔎 Search Terms

condition, assertion, boolean operation

### 🕗 Version & Regression Information

- ~This is a crash~
- ~This changed between versions ______ and _______~
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about everything
- ~I was unable to test this on prior versions because _______~

### ⏯ Playground Link

This

```ts
type A = { aa: 0 | 1 }
type B = { bb: 0 }

const f = (a: A, b: B) => {
  if (a.aa === 0 && (a.aa = 1, true)) {
    b.bb = a.aa;
  }
}
```

[Playground link](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAglC8UDeUCGqBcUAMUA+UAjFAL4BQokUAQgslAEYNa7lkDGA9gHYDOwUAGZ0AFJlgAaRlmoBKBAD5kZKFACWwsQDp0CeIlwAyQ1G27EhKcABOAVwiz5SFasZamdVDtQBuF+RIgA)

rightly throws a TS error on `b.bb = a.aa` because `a.aa` is rightly inferred to be always `1` which is not assignable to `0`. However if I extract the right hand side of the AND inside a function

```ts
type A = { aa: 0 | 1 }
type B = { bb: 0 }

const g = (a: A) => (a.aa = 1, true);

const f = (a: A, b: B) => {
  if (a.aa === 0 && g(a)) {
    b.bb = a.aa;
  }
}
```

[Playground link](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAglC8UDeUCGqBcUAMUA+UAjFAL4BQokUAQgslAEYNa7lkDGA9gHYDOwUAOZ0AFJlgBKBAD4oYgHTo6hADRRgAJwCuECQG4yHHvygAzUeJhrmNKfFlIyUKAEtzCpfC84oAMl9CYhJSjs7ODPJMdKiKqAbO5CRAA)

then TS wrongly infers `a.aa` to be `0` when `b.bb = a.aa` arises

### 💻 Code

See above

### 🙁 Actual behavior

See above

### 🙂 Expected behavior

See above

**Comment by ninofiliu** [comment]
Weirdly enough, this works fine, ie both case 1 and case 2 shows the _Type '1' is not assignable to type '0'_ error

```ts
type A = { k: 0 | 1 };

// case 1
(a: A): 0 => (a.k && (a.k = 1, true)) ? a.k : 0;
                                       // ^? (property) k: 1

// case 2
const g = (a: A) => (a.k = 1, true);
(a: A): 0 => (a.k && g(a)) ? a.k : 0;
                            // ^? (property) k: 1
```

[Playground link](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAglC8UDeUDWAuKAGKAfKAjFAL4BQpA9BVAMYCGAztAaQBR2YwCUmO8AfFHYA6VFABk4oXVEJCAGijAATgFcIXLlAD8UGWN4BuUlFNnzFy1etmqUAHrbyd+kygAmUjQD2AOwbAUADmcuycWgLSsogEiirqXMZhsDzYCIIiYpLB7Jo6erJGJjYl1naOQA)

**Comment by MartinJohns** [comment]
Duplicate of #9998. Modifications within a function are not recognized outside of it.

**Comment by ninofiliu** [comment]
Interesting. I just opened this issue because I thought it was a small bug and wanted to give yall a heads up, but it looks like it's more like a huge can of worms that's already been discussed for years, so I'm gonna close this and let the already-existing discussion go on
