### ISSUE TITLE
Spreading multiple objects into one doesn't type check correctly

### ISSUE THREAD

**Issue by mhanuszh** [microsoft/TypeScript#51433]
# Bug Report

### 🔎 Search Terms

spread operator
object types

### 🕗 Version & Regression Information

Version 4.8.4
Version 5.0.0-dev.20221103

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABABwE5wgUwM7YMpSoxgDm2AFMciFAFyIDeA2sQCaYAe92hxJAut16kAvgEpGAKACQAelmIAoh2SZofRAEMkcAEYArNVEQB3GFAAWiAG6aANiByI4wRDyKlEUAJ6rE5M0tEAAM7TFJLYJR0VVQfMRlgOFR-WxSAa0xvRGJEAHkDIwA6TO8KKhoxCQgEbDgwors4EkowaigmUv5G8JJLMQBuSRFJSVBIWAQvHChyZE1UTQBbTChMVGx6ZjZOIQ8BPY0AH0QwECXddfEpaTTEJe8CEGBXAF5GIs+GTWxWegAiACOJkw-xEABpEJ8ivNFis1hsREM5AoAHJwRDrdAbRAWdaYSEmCwwMIhB5PF5RCBhBZ2bIQbSIGpgKCaXJnC7rbAyNAYHD4YRkcjkqDPYAJUa3Bb3R6il4AJkQ7wY0Nhy1WXKRMnkiAA6nikDTrBo4DQvHjnJZ1s5CtBIVbMahsTlsKc4CYmclUEY6Yh2AilsRMKweegsLgCPsKCKxfKEiNJDqAAroY2sDSMvSGaCmcxWWwOTDOVwcy4pHyqSRrHjkBj-Ur-egARnlAGZxEMgA)

### 💻 Code

```ts
function processStrings(input: {[index: string]: string}) {
	// Expecting an object with values of string type (with `length` property)
	for (var key in Object.keys(input)) console.log(input[key].length);
}

function test(parameters: {[index: string]: string | number}) {
	var myStuff = {...{asd: "qwe"}, ...parameters};
	// No errors here, while `myStuff` clearly can contain numbers
	processStrings(myStuff)


	var myStuff2 = {...parameters};
	// When leaving out the other object, the error is now correctly determined
	processStrings(myStuff2)
}

// Providing an object with value of number type
test({"key": 123});

```

### 🙁 Actual behavior

The `myStuff` variable doesn't receive the predictable `{[index: string]: string | number}` type, therefore the script crashes at runtime

### 🙂 Expected behavior

The `myStuff` variable should receive the predictable `{[index: string]: string | number}` type, therefore the IDE or the compiler should show errors about this

**Comment by mhanuszh** [comment]
> See #50559 and, in particular, [#50185 (comment)](https://github.com/microsoft/TypeScript/issues/50185#issuecomment-1205549273).
> 
> Spread is currently modeled using intersection types, which sometimes produces the wrong type. To model this correctly TS would need a dedicated type operator for spread.

So, this is a known TS limitation. Thank you for the clarification!

**Comment by fatcerberus** [comment]
Yeah, specifically the limitation is that TS models `{ ...t, ...u }` as `T & U`, but this is wrong when `t` and `u` have overlapping properties (a `string` index signature is apparently considered to overlap with everything for this purpose).

The issue you want to follow is #10727.
