### ISSUE TITLE
JSON.stringify should have type string | undefined

### ISSUE THREAD

**Issue by markfields** [microsoft/TypeScript#51431]
# Bug Report

### 🔎 Search Terms

stringify, JSON.stringify undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `stringify`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDAUgZQPIDkB00BOAlmAOaEBmAngBQCuYAJgKbnFMMCUA3AFA8D0-GAAsQANyb4Y4yTADkcOQBoYhKHIgwolAA7sYAQ00FiJHD1CQQAGyY5rIEtW16Q5eBx5A)

### 💻 Code

```ts
// hover over 'x', it's typed as string.
const x = JSON.stringify(undefined);
console.log(typeof x)  // outputs "undefined"
```

### 🙁 Actual behavior

Return type of `JSON.stringify` is `string` but it can return `undefined`

### 🙂 Expected behavior

Return type should reflect actual set of values that could be returned:  `string | undefined`

**Comment by IllusionMH** [comment]
Duplicate of #18879

Ton of duplicates can be found with search for `JSON.stringify undefined`

**Comment by markfields** [comment]
Sure enough!  I adjusted my query to include quotes and found the one you linked right away.  Closing.
