### ISSUE TITLE
Set more specific function type to general function type

### ISSUE THREAD

**Issue by ObscurusGrassator** [microsoft/TypeScript#51448]
# Bug Report

- This is the behavior in every version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglA8AVKBeKBvAhgLigOwFcBbAIwgCcBfKAHygLwBMIAzASzwkYD5UpEA3ACghAYwD2eAM7AoOWPCy5CpCpV5RNW7Tt1901TFIVL8xMlW7CJ02SVxw0mAXtduA9O6gB5ANLaAWigASSgpCFkicXJoKUhRNnZRKFBIFPEoAHMITnJMABsU8AgRGxk5eQAKMEw8ogdFeRULdQBKVF4AN3E2Rh00AzljatrMepMm8zVudpQunsZrSXKSeygRuodZ+d6+TGcdTygAUQAlU+9TqCDJfJAoAHc8sEg+h+iAay4itLhgDJYDFEwDYkiEQA)

### 💻 Code

```ts
type A <T = {a: number} | undefined> = T;

const a: A<{a: number}>                       = {} as A<{a: number}>;
const b: A = a;                        // OK    - I set more specific type to general type

const aa: (param: A<{a: number}>) => void     = {} as (param: A<{a: number}>) => void;
const bb: (param: A) => void = aa;     // ERROR - only wrapped worked type A to function
/*
Type '(param: { a: number; }) => void' is not assignable to type '(param: { a: number; } | undefined) => void'.
  Types of parameters 'param' and 'param' are incompatible.
    Type '{ a: number; } | undefined' is not assignable to type '{ a: number; }'.
      Type 'undefined' is not assignable to type '{ a: number; }'.(2322)
*/
```

**Comment by ObscurusGrassator** [comment]
Did not forget. I studied the template. But I have no idea what type of mistake this is and how it could be searched.
There are two similar examples in the code, and in the first one it does not contain a mistake and the second mysteriously contains it. In the contents of the error, they were unexplainedly exchanged: "A is not assignable to B" for "B is not assignable to A".

**Comment by MartinJohns** [comment]
In the first one you have a value, and assign it to a variable that says "I might have a value". That's acceptable.

In your second example you have a function that requires a value as first parameter, but you try to store it in a variable that might not get a value. That's an error. One might call `bb` and provide `undefined`, but the function you assigned can't handle this value.

You can disable this behavior by turning `strictFunctionTypes` off.

**Comment by ObscurusGrassator** [comment]
OK, I think I have already understood it. I have to think about the concept again. Thank you very much for explaining :-) .

**Comment by MartinJohns** [comment]
`aa` is a function that requires an object with a `b` property, whereas `bb` does not require/provide such a property. Same thing.
