### ISSUE TITLE
What is the type of function generic type param 

### ISSUE THREAD

**Issue by zyf0330** [microsoft/TypeScript#51447]
# Bug Report
I cannot figure out what is the type of generic T in the below playground code.
The generic T param which extends a class in the function, seems to be the never type, but I think it shouldn't be.

### 🔎 Search Terms
function generic type  type param extends never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about extends and generic

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAUwHgDg9gTgLgAgMYBsCGBnDCDC6sCCCA3sAL7CiSyJwCeEICAKiBnMwDzMMgB8CALzAEolrwTg4IAHYATbACMoUFCDQyEAHwQyArgFtFIGNoTsYASxkBzBAH4EARhFi3ALnGNJYafOwAYnoySHCWUJqOAEyubnEInjzeUrIKCAQwMGh0nBp0Ao4AzLHxpYkSKf4IUIoAViChDggALCWl7QleTJVpeU0ArG0dw54A2kkgALo+fmmjMiAAbibTjgBsQ8NbnQDsANyUAGbBoeGa0uzcM6nYeJgYBHwAFACUJCUA9B8IAO4AFmhEJZsHA-kx6N4oIcWPYSkgIuwEHAnIk2BxuAJBM44QjaFFUewuMxMQgYm54TJEXBCgT0cShAhiuTcUjmrSiSTWszKbR+uyMQzBtyqWt+fSsRthbQdmKSTtKFKkcj+XdCCSXIq4HB8Sw0VxVQ8SWSxBSqdSVfhDQymSaWVq2brCZwDY8GVzbTylXzHeiXSShR6zaKffrLa6JTjPVqZSHnWG5eRgEA)

### 🙁 Actual behavior
The generic T seems to be `never` type.

### 🙂 Expected behavior
The generic T should be `object` or `any` type.

**Comment by MartinJohns** [comment]
The type of `T` within `test<>()` is **not known**, because it's a generic type argument. Within the function the compiler **does not know** what type `T` is, so it can't resolve your conditional type `TestT<T>`.

**Comment by zyf0330** [comment]
Actually, this is my actual type function which resolves key chain of type. And I don't know how to make it work for generic `T`.

```
export type NestedPaths<Type> =
// forbid access Function property
    Type extends Function ? never
        : Type extends string | number | boolean | Date | RegExp | Buffer | Uint8Array | {
            _bsontype: string;
        } ? [] : Type extends ReadonlyArray<infer EleType> ? ([ArrayIndexes<Type>, ...NestedPaths<EleType>] | [...NestedPaths<EleType>])
            : Type extends object ?
                (
                    {
                        [Key in Extract<keyof Type, string>]:
                        // forbid circular reference
                        (Type[Key] extends Type ? [Key] : Type extends Type[Key] ? [Key] : Type[Key] extends ReadonlyArray<infer EleType> ? Type extends EleType ? [Key] : EleType extends Type ? [Key]
                                : [Key, ...NestedPaths<Type[Key]>]
                            : [Key, ...NestedPaths<Type[Key]>]);
                    }[Extract<keyof Type, string>]
                    // allow to infer partial key chain, and ensure to infer the exact depth of key chain
                    | []
                    )
                : [];
```

**Comment by zyf0330** [comment]
To simplify it, use this code to explain.
```
class ClassA {c?: string}
function test<T extends ClassA>() {
    const ks: T extends any ? keyof T : keyof T  = "c" // TS2322: Type '"c"' is not assignable to type 'T extends any ? keyof T :   keyof T'.
    const ks1: keyof T  = "c" // ok
    const ks2: ClassA extends any ? keyof T : keyof T  = "c" // ok
}
```

How to make `ks` work?

**Comment by MartinJohns** [comment]
@zyf0330 You can't. The type of `ks` depends on the type `T`, but the type of `T` is not known within the function, because it's passed along from the outside.

**Comment by zyf0330** [comment]
I just find a related issue [#24560](https://github.com/microsoft/TypeScript/issues/24560#issuecomment-1067367324), so it seems that I cannot solve this problem.
