### ISSUE TITLE
Provide more information when module resolution fails but a '.js' file was found

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#5146]
If a `.js` file was found in performing module resolution, we should inform the user that they are missing a declaration file.

**Comment by BretJohnson** [comment]
+1 on this.   As a semi-noob I can attest that with all the vagaries around module loading logic, the more hints we can give the user about what's wrong (and what they may need to do to fix it) the better.
I also wrote up #5149, which is related.

**Comment by RyanCavanaugh** [comment]
We have this now
