### ISSUE TITLE
Publish TypeScript 1.6+ on VS Gallery

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#5147]
Right now if you search online through the VS Extension Manager for 'typescript' you'll see the latest thing we uploaded: TypeScript 1.5beta. We should continue to publish to the VS Gallery if only so that searching for TypeScript in the Gallery gets someone the latest bits.

Tagging @yuit

**Comment by yuit** [comment]
Version need to be published on VS Gallery:
- [X] TypeScript 1.6 for Visual Studio 2013
- [X] TypeScript 1.6 for Visual Studio 2015
- [ ] TypeScript 1.7 for Visual Studio 2013
- [ ] TypeScript 1.7 for Visual Studio 2015
