### ISSUE TITLE
`Number.is*` doesn't return const `false` if arg is not `number`

### ISSUE THREAD

**Issue by Rudxain** [microsoft/TypeScript#51476]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2022` and my *lib* is `the default`.

## Missing / Incorrect Definition

Most of `Number.is*`

## Sample Code

```js
const x = Number.isNaN('') // inferred as arbitrary `boolean`, not `false`

const y = Number.isInteger('') // same as above

const z = Number.isFinite('') // same as above
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

**Comment by MartinJohns** [comment]
Those are runtime checks, not compile time. Are you suggesting all string literals should be checked at compile time? Or just the empty one?

**Comment by Rudxain** [comment]
> runtime checks

Yes, but the type signature can be changed, such that any type that isn't `number` makes the return type `false`, while `number` makes it `boolean`. It can be done via fn overloads

**Comment by fatcerberus** [comment]
I feel like, in any situation where the compiler can statically prove the result is always `false`, there’s no reason to write the call in the first place.

**Comment by RyanCavanaugh** [comment]
Overloads generally make things slower and less ergonomic, and there's literally (ha!) no reason to call this if you know it's going to return false and hey fatcerberus just said that as I was typing it.

**Comment by fatcerberus** [comment]
Ideally, we would be able to express that `Math.isFinite(stringOrNumber)` is a legal call, but `Math.isFinite(alwaysString)` is a type error, but I don’t think that’s possible today.

**Comment by Rudxain** [comment]
@fatcerberus
> where the compiler can statically prove the result is always `false`

Nope, it can't, not even simple cases:
```ts
const x = () => Number.isInteger(0) // inferred as returning boolean

if (true) {
    console.log('ok')
}
else {
    console.log('unreachable') // detected as unreachable properly
}

if (Number.isInteger(0)) {
    console.log('ok')
}
else {
    console.log('?') // not detected as unreachable
}
```

> there’s no reason to write the call in the first place

What if I have a generic fn which uses a `Number` method to narrow types using `if` statements?


> `Math.isFinite(stringOrNumber)` is a legal call, but `Math.isFinite(alwaysString)` is a type error, but I don’t think that’s possible to express today.

I don't understand why you brought `Math` here. But yes, if `Math` had these methods, the args should only be `number`s. But that's not the case for `Number.*`


@RyanCavanaugh 
> Overloads generally make things slower and less ergonomic

I agree with that. But maybe it could be implemented in a similar way to `typeof`? (at least for VScode, not TS as a lang)

> no reason to call this if you know it's going to return false.

Yeah, my example was too simple. But that's usually the point of examples (I guess?)

**Comment by RyanCavanaugh** [comment]
An example using code you might actually write would be useful.

**Comment by fatcerberus** [comment]
`s/Math/Number`, it was a typo.  My comment stands: you’re proposing that these functions return the literal type `false` in cases where you know *based on the type of the argument* that it will always return `false` at runtime.  In that case, there’s no reason to ever call it.  Or are you suggesting you have values typed as e.g. `string` that you don’t know have that type?

**Comment by fatcerberus** [comment]
If the reason you want this is so you get unreachable code warnings when accidentally narrowing too far, it won't work:
```ts
declare function stuff(): void;
function alwaysFalse(): false { return false; }
if (alwaysFalse()) {
    stuff();  // no unreachable code error
} else {
    stuff();
}
```

[Playground link](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwGcNlFEAKASgC54A3HLYAbgCgV1s94oIB3KAJ4EAYjwIhKNRGIQBveHGIx80iOKbwAviyyJ4ZHvyGi1EihXiyW8G4WKlKG+AHpn8VDnggYMHDBaaXqaW1rZEJOQUrJpAA)

Like I said, this would work better if there was a way to say "this function accepts any type as long as it overlaps with `number`"

**Comment by Rudxain** [comment]
> An example using code you might actually write would be useful.

I was thinking of a generic fn, but I have no experience writing that kind of fns (in no lang, not even Rust lol). I almost always get errors that I have no idea how to fix.

> in cases where you know

But what if I (or anyone) makes a mistake in development? I know tests are supposed to catch this stuff, but it would be nice if the type checker noticed this before the tests.

> unreachable code warnings [...] it won't work

Oh... I thought it would work. Thanks for the info, now I know I was mistaken 😅

> "this function accepts any type as long as it overlaps with `number`"

It could be done by restricting the param type in all Number.* fns, but then it would be wrong because those fns are supposed to "work correctly" regardless of the input type, so it makes sense the params are `unknown`

Maybe we could have a tsconfig setting to narrow the param types as an opt-in (non-default)?

**Comment by fatcerberus** [comment]
I do understand what you're getting at - you want to see some kind of error when you pass a `string` to one of these functions (because it's always false and is probably a mistake) but not, e.g., a `string | number`.  The type system isn't currently powerful enough to model that, so `unknown` is the best you can do here for now.

If type narrowing is what you're after: unfortunately `Number.is*()` can't be declared as type guards because it would lead to unsound narrowing.  That feature has been requested before; see #15048.

**Comment by Rudxain** [comment]
I see. Thank you for the info
