### ISSUE TITLE
Union of `Record<string, string>` and interface can't be indexed by string

### ISSUE THREAD

**Issue by antonilol** [microsoft/TypeScript#51478]
# Bug Report

### 🕗 Version & Regression Information

error on all version ts playground let me choose

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.8.4#code/JYOwLgpgTgZghgYwgAmMg3gWAFDL8gawgE8AuZEAVwFsAjaHAXxxzGIAcUxkBeZAJQgIA9lAAmAHgDOYKKADmAGmQy5IeQD5kAH1QBuFtjFCANnCgoTEbsNoArcmANHT5y9cLlVC5zgD0fsgQAB6cCJBiyGycXrIKOhQ09FDKiGCUcCbkAKJW1BDgqNTsJsAIwGAmxMgAFnBSyHAgyADkTcQtURwo9AhwlFIoIewWUlLAws3CMF2crd7qnX0gLdz0yAMQkWDCqCDGwbMoqy0AdP6B+FfXN7d39wByu6AHKsDyIHDpFsgA7hU1RrIdjmOD5SBQZDTI7zOKLP71ZAwYSUfZQ5rRY5gM7IAAUAHYAAwAVgAzABKHAiEAyZAAN14UPsAG0CABdPRAA)

### 💻 Code

```ts
interface i {
    key: number
}

type t = Record<string, string> | i;

declare let obj: t;
declare let k: string;

// expected type: string | number, actual: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 't'.
//                                           No index signature with a parameter of type 'string' was found on type 't'. (7053)
const v = obj[k];
```

### 🙁 Actual behavior

```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 't'.
  No index signature with a parameter of type 'string' was found on type 't'. (7053)
```

`Record<string, string> | { key: number }` can be indexed with `string`

### 🙂 Expected behavior

`const v`'s type was successfully inferred as `string | number`

**Comment by fatcerberus** [comment]
`k` is an arbitrary string and `t` may be a value of type `{ key: number }`, which can't be indexed with arbitrary strings.  The error is correct.

**Comment by fatcerberus** [comment]
It would be wrong to infer `string | number` here, for the record.
```ts
const x = { key: 42, pigz: true }
const k = "pigz";
const obj: t = x;
console.log(obj[k]);  // prints true (a boolean) at runtime.
```

When you have something typed `X | Y` it means the value can be either of those types, but you don't know which one.  You probably want an intersection type instead.

**Comment by antonilol** [comment]
> When you have something typed `X | Y` it means the value can be either of those types, but you don't know which one. You probably want an intersection type instead.

ah you're right, what i want is probably `{ [k in string]?: k extends 'key' ? number : string }`, but it doesn't seem to work.
`{ [k in string]?: string } & { key?: number }` also doesn't seem to work, in both cases when indexed with `string` the resulting type is `string | undefined`, where did the number go?

**Comment by antonilol** [comment]
> Wait, so you're trying to represent a type which is otherwise a `Record<string, string>` except for a few named properties of a different type?

yes


> Based on your use case, this appears to be a duplicate of #15151/#17867.

thanks for pointing me in the right direction, closing this now

**Comment by fatcerberus** [comment]
@antonilol In this specific case, if all you care about is getting `string | number` when using an arbitrary string to index the object, you could just write `{ [x: string]: string | number, key: number }`.  That's what TS expects you to write anyway and isn't a problem.  The problem is only when you want `obj[k]` to just be `string`, which is of course unsound.
