### ISSUE TITLE
@internal on constructors incorrectly removes constructor completely from .d.ts

### ISSUE THREAD

**Issue by RedBeard0531** [microsoft/TypeScript#51486]
# Bug Report

Right now `@internal` on a constructor completely removes that constructor from the class, which makes it equivalent to the implicit constructor, either `constructor()` or passing through to the base class's constructor. This is in contrast to the intuitive meaning of that marker which is that this type should only be constructable from inside this module/library.  I noticed several instances of this pattern in our codebase from multiple authors, so it is clearly something that people think works and is meaningful.

### 🔎 Search Terms

internal constructor

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `@internal` and constructors

### ⏯ Playground Link

[link](https://www.typescriptlang.org/play?stripInternal=true#code/MYGwhgzhAEBiD29oG8BQBfVqB2BTA7nIgBQCUA3FqJDAEJgBOa0L0A9AFQfQACAltgAuuBtjAhoHNqlbRg8bBEEMArsEHwGxMAC5o2FQFsARiNIpMmHAWj0tFdm2iCAFnxj4FAckHQRDTWg+ADNoAE94FWgAKxUlaBBEAGtoMF9XXGgAOgATLMEIIA) (Make sure to click on .d.ts output tab)

### 💻 Code

```typescript
class Foo {
}

new Foo(); // allowed

class Bar{
    /** @internal */
    constructor(a: number) {}

    /** @internal */
    foo() {}
}

new Bar(); // this won't error if you just look at the .d.ts
```

### 🙁 Actual behavior

generated .d.ts:
```typescript
declare class Foo {
}
declare class Bar {
}
```

Note that they are the same, meaning that `Bar` has an implicit `constructor()`, even though it isn't valid to call it with no arguments (or at least it wouldn't be if the body wasn't slideware).

### 🙂 Expected behavior

Ideally it would output something to indicate that `Bar` is not intended to be constructed externally. Unfortunately marking it as `private` doesn't work in the general case because `tsc` will complain if you have any subclasses of `Bar`. `protected` is a possibly reasonable option which prevents directly constructing the class, but would allow incorrectly deriving from the class. I think the most "correct" option possible in today's TS is to generate a synthetic unexported enum type like `enum Internal_Do_Not_Call {}` and make all `@internal` constructors take that. That works because enums are nominally rather than structurally typed. But perhaps that is too magical and weird?

Really I think the best solution would be to have some sort of `fileprivate`/`moduleprivate`/`libraryprivate`/`internal` protection modifier so you could just write `internal constructor()`.

**Comment by MartinJohns** [comment]
Fairly sure it's the same as #51337.

**Comment by fatcerberus** [comment]
As hinted in the issue linked above, you're pretty much not supposed to use `stripInternal` at all -- it's intended only for internal use (no pun intended) by the TS team and isn't officially supported.

The documentation has this to say about `stripInternal`:
> Do not emit declarations for code that has an `@internal` annotation in its JSDoc comment. This is an internal compiler option; use at your own risk, because **the compiler does not check that the result is valid**. If you are searching for a tool to handle additional levels of visibility within your d.ts files, look at [api-extractor](https://api-extractor.com/).

Emphasis mine.

**Comment by RedBeard0531** [comment]
Ok, I'll work with my team to see if we can find an alternative to `@internal`/`stripInternal`. I had been told that this was the best mechanism we could use. Thank you for pointing out the references saying otherwise with alternative suggestions.

That said, I'd *love* something like a real `filePrivate`/`libPrivate`/`internal` protection level in the language proper, on par with `private`, but that is obviously a separate feature request, not a bug report.
