### ISSUE TITLE
TypeScript doesn't respect declared function argument type definition

### ISSUE THREAD

**Issue by jez9999** [microsoft/TypeScript#51487]
# Bug Report

### 🔎 Search Terms

argument type inconsistent respect function definition

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 4.8.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8CwAoaXrHgOwgBcAnAV2EPmIAoBKFDbJ6QgCwEsIA6AIzGOgBeaAEYATAGYA3I2wBfWVj7EAXNDykAtjwCmxGegXoMAM1J4K7fNE4BlAA47g7E+x0ATADwAVAHzV2PHtSQjVzdx1XPA9oAB91UhAQOOhvWjVA4MIbGG8GTGxiHUJSYjxoampCAE9HeBMbIJDoAEJBYQAicMjAjw76ADIBiszmtuENJNpaAyNTc0trADd+djAeEB0AQQgt4gBzAKbCADV+AH41DW09ejQCrFwCbJNEAElnsAsdIXUdAHc4Ig6AZFDYGgEIA4nC43O4jlkzsRpvlmNgnhB4JsuCB4IcAAZInLQCCOZyuDxqAAkyFGp34cnxMzBTFe8A+RC+wB0vH4vzpSIMTCMTB0IAgP3uaMe+Ex2Nxhw6KwEnGg5lJMIp7n6YKMc3QZgshCs5WVaw22wgAGFZYQ6Kj0bboGyOYQuT8JgCgfAQRgwRjsgL+FdEsl4t0ojF4tddAJhBHeu4hdgXCMoWTYR4ESEkSipdKMVieQrqIS+aqNeS4dTacckYzmQ9mAB6Zsuz7fXlxxqI-hSaCt6CeAC0w+gAFFiMQqLqwWKJQ60YX5XjqEryzB1RmtTqm3q-egAz2c8GEkkUgnou4UjG9L9Lx4DK2zetNjs9ocg8iDC+LTsbc8vroEAA)

### 💻 Code

```ts
class Foo {
    constructor() {
        this.bar = 123;
    }
    bar: number;
}

function isSpecified<T>(input: undefined | null | T): input is T {
    return ((typeof input !== "undefined") && (input !== null));
}

function variableAsArg(inputVar?: number) {
    const fooInstance = new Foo();

    if (isSpecified(inputVar)) {
        console.log(`Var is specified: ${inputVar}`);
        fooInstance.bar = inputVar;
    }
    else {
        console.log("var is unspecified")
    }
}

function variableAsConst() {
    const fooInstance = new Foo();

    const inputVar: null | undefined | number = undefined;
    if (isSpecified(inputVar)) {
        console.log(`Var is specified: ${inputVar}`);
        fooInstance.bar = inputVar; // <-- Error
    }
    else {
        console.log("var is unspecified")
    }
}

const inputVar: null | undefined | number = undefined;
//variableAsArg(inputVar);
variableAsConst();
```

### 🙁 Actual behavior

When a variable is declared in the same block and assigned `undefined`, even when its type is explicitly declared to have ` | number`, its type is treated as `null | undefined` rather than `number | null | undefined` when passed to a function.  I guess TS thinks it's being helpful here, but it seems to me like annoying inconsistent behaviour that breaks my type guard function when I've explicitly told TS that the variable type should be considered ` | number`.  Because of this behaviour, in that circumstance, my `isSpecified` function no longer acts as a type guard against `null | undefined` and I get an error from TS.

### 🙂 Expected behavior

TS should always respect the explicit type that the variable is declared to be whether it's a function argument or declared in the same code block as a `const`.

**Comment by MartinJohns** [comment]
Assignment narrows the variable. This is working as intended. You can use the new `satisfies` operator instead.

**Comment by jez9999** [comment]
Could you give an example as to how `satisfies` fixes this problem?

**Comment by MartinJohns** [comment]
Nevermind, I talked without verifying. `satisfies` does not help. But you can use a type assertion to prevent narrowing: `const inputVar = undefined as null | undefined | number;`

**Comment by jez9999** [comment]
Yep, that does fix it.  I still find it kind of odd that assignment narrow the type of a variable whose type is explicitly declared, but oh well.  I mean in C#, `int? foo = 2` wouldn't turn the variable into an `int` under any circumstances.

**Comment by MartinJohns** [comment]
C# doesn't have union types, so the argument is moot.

**Comment by RyanCavanaugh** [comment]
This used to not be the case, and people found that behavior very annoying and inconsistent, so we changed to this other behavior which is apparently also very annoying and inconsistent. Can't win 'em all 😅
