### ISSUE TITLE
enums showing double the amount of entries; "extra" key value pairs are the flipped versions of the original key-value pairs

### ISSUE THREAD

**Issue by kptevpro** [microsoft/TypeScript#51481]
# Bug Report

### 🔎 Search Terms
is:issue enum duplicate key value double extra entries flipped

### 🕗 Version & Regression Information
Found in v~4.7.2

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221110#code/KYOwrgtgBAKgTgQxAZwQYwC4EsD2IYCeADsMlAN4CwAUFHVAIJQC8UAjADQ31QBCLUAExda9AMICAzCJ4ARAQBYZ9AKICArMroAxAQDYtUAOICA7IYASAgBwiAvjUfU0eZDgA2wAHTucAcwAKAHIAaWACZAAuIKgAaigAeQAjACtgTC8Aa3DkAPgkVExcfGJSAEoymhcUD29fQKCANQR3MFJIqBj45LSMgDcWttz8lHRsPEISZAqnGgAzHDgAzwwoLAEABgBuNagAHkTU9IwsnLzEUaKJ0umfUD8MAAsdrFjYsopuemq3Tx9-AIAAwACggsHAOgAScg9Y6nCLnApjYqTcoAbSwAF07FAALRQaGw-qDUiIy7jEpTMoY7GAj40OxAA)

### 💻 Code
```ts
enum TransactionTypes {
    A = 1,
    B = 2,
    C = 3,
    D = 4,
    E = 5,
    F = 6,
    G = 7,
    H = 8,
}

console.log('Keys:' + Object.keys(TransactionTypes))
console.log('Values: ' + Object.values(TransactionTypes))

for(let i = 0; i < Object.keys(TransactionTypes).length; i++) {
    console.log(`Pair: ${Object.keys(TransactionTypes)[i]} - ${Object.values(TransactionTypes)[i]}`) 
}
```

### 🙁 Actual behavior
Enums shows double the amount of entries; shows key-value pairs twice where the second set (extra entries) are the original keys and values 'flipped'.

### 🙂 Expected behavior
Show key value pairs once; only one set of the key values declared.

**Comment by MartinJohns** [comment]
This is working as intended. Check the generated JavaScript.

**Comment by fatcerberus** [comment]
For the record the reason for this is so you can evaluate `TransactionTypes[x]` in the debugger to find out which enum member `x` (just a number at runtime) refers to.

**Comment by RyanCavanaugh** [comment]
It would be quite the interesting bug for a 100% accurate reverse map to appear in the output (and go unnoticed for ten years). But no, this is there on purpose.

**Comment by aitoraznar** [comment]
Hi, it happened to me when using UPPERCASE keys in the enum.

// Duplicated keys in uppercase && lowercase
enum TransactionTypes {
    A = 1,
    B = 2,
    C = 3,
}

// Correct keys
enum TransactionTypes {
    a = 1,
    b = 2,
    c = 3,
}

**Comment by RyanCavanaugh** [comment]
Please log a new issue with concrete repro steps if you think you've encountered a bug.
