### ISSUE TITLE
ES2020 not working in lib option

### ISSUE THREAD

**Issue by emilmuller** [microsoft/TypeScript#51485]
I'm using the Monaco Editor, so I'm unsure if this is a bug with Monaco or with TypeScript, but I'm guessing the latter. Sorry if this is a mistake :-)

Versions:

typescript 4.8.4
monaco-editor 0.34.1

-------------------

Incidentally, I'm going to run JS in an ES2020 environment which doesn't have a DOM ([QuickJS Javascript Engine](https://bellard.org/quickjs/)). So I have this code:

```
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ES2020,
    module: monaco.languages.typescript.ModuleKind.ESNext,
    strict: false,
    moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
    esModuleInterop: true,
    resolveJsonModule: true,
    lib: ["ES2020"]
});
```

, which does not seem to work correctly. Now I'm seeing this:

![image](https://user-images.githubusercontent.com/2487546/201312146-77e35bd0-23c5-4566-81be-adf1cdf1b1fc.png)

So `Error` and `parseInt` and `substring` doesn't get recognized and are getting some squiggly lines.

There are no errors getting logged. If I don't specify the 'lib' option, things work, but I get DOM, which I don't want.

**Comment by MartinJohns** [comment]
I can't reproduce this issue in TypeScript.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to indicate a TypeScript bug -- the Monaco editor definitely works if configured correctly (this is what the Playground uses)
