### ISSUE TITLE
Experiment with removing `originalKeywordKind` from every `Identifier`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#51496]
In our factories, every `Identifier` has an unconditional assignment to `originalKeywordKind`. This feels wasteful, but it's at the expense of reducing polymorphism. As an experiment, we should see

1. Whether we can conditionally set it at no cost, or
2. Whether we can just remove it entirely, computing the necessary information on the fly.

**Comment by DanielRosenwasser** [comment]
I think we shimmed this with a get-accessor.

**Comment by jakebailey** [comment]
Yep: https://github.com/microsoft/TypeScript/blob/main/src/deprecatedCompat/5.0/identifierProperties.ts#L28
