### ISSUE TITLE
Infinite type instantiation with a recursive conditional type, generic type constraints, and an async function. 

### ISSUE THREAD

**Issue by nitsky** [microsoft/TypeScript#51491]
# Bug Report

Hi! I am observing unexpected infinite type instantiation when using a recursive conditional type, generic type constraints, and an async function.

### 🔎 Search Terms

* Recursive conditional types.
* Generic type constraints.
* Async functions.
* "Type instantiation is excessively deep and possibly infinite."

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about, from version 4.1.5, and all versions up to 5.0 nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221111#code/C4TwDgpgBAaghgGwK7QLxQM7AE4EsB2A5lAD5QDCA9vsHARNgDzzIQB8A3AFBcDGCcDBgrVa9JgBUoEAB7AI+ACbCWKNlADeXKDqgF8DAFxQpZJEogAzeou4BfHqEhQAkvgOTpchctiI1UOhSsvJKwlQ0dB6MBJYMUACqbFwAkAD8ru4MjEmpxhLcXIIg+LxQlua8wLjUelmeIT4q-uwAFAD6AG4t+QCUxgAK2JQAtrgYEIxu0RJs6lopwAAWwwDuUAbrAKLYw9itAETmuCNgCBAjCvKKB7323EA)

### 💻 Code

```ts
type Value = string | Container<Value>;

class Container<T extends Value> {
  inner: T | undefined;
}

type Inner<T extends Value> = T extends Container<infer U>
  ? Inner<U>
  : T;

async function inner<T extends Value>(_value: T): Promise<Inner<T>> {
  throw new Error("unimplemented");
};
```

### 🙁 Actual behavior

I get the error "Type instantiation is excessively deep and possibly infinite.".

### 🙂 Expected behavior

I expect type checking to succeed. Very curiously, the error can be avoided by removing the `async` keyword from the function declaration, or by removing all the `extends Value` constraints. I do not understand why these changes would make a difference. Any ideas? Thank you!

**Comment by ahejlsberg** [comment]
This is working as intended. In order to determine if `Promise<Inner<T>>` is a valid async function return type, the checker attempts to examine the base constraint of `Inner<Value>`. This, however, is an infinite type:

```ts
type Infinite = Inner<Value>;  // Type instantiation is excessively deep and possibly infinite
```

**Comment by nitsky** [comment]
@ahejlsberg Thank you for the response. I understand now that the type I wrote is infinite, and the type constraint and async keyword were just exposing that fact. I will close this issue. Is it possible to express the intent in my code sample above? If not, are there any planned TypeScript features that would make this possible?

**Comment by ahejlsberg** [comment]
> Is it possible to express the intent in my code sample above?

Perhaps this:

```ts
type Value<T extends string> = T | Container<T>;

class Container<T extends string> {
    inner: Value<T> | undefined;
}

type Inner<T> = T extends Container<infer U> ? Inner<U> : T;

async function inner<T extends string>(_value: Value<T>): Promise<Inner<T>> {
	throw new Error("unimplemented");
};
```

**Comment by nitsky** [comment]
@ahejlsberg Using your code sample as a starting point I was able to express my intent completely. Thank you!
