### ISSUE TITLE
Missing `endsWith` method on strings in lib.d.ts ?

### ISSUE THREAD

**Issue by egeland** [Microsoft/TypeScript#5150]
Hi, I'm still very much a beginner with TS (and almost-a-beginner at JS), but thought I'd report what looks like a possible omission:

I was writing what I though was a pretty standard `mystringvar.endsWith('/')` line, but the `endsWith` method comes up as `Property 'endsWith' does not exist on type 'string'`.

I searched my typescript installation for `endsWith` and it didn't appear.

I'm using the Atom editor with the `atom-typescript` [plugin by TypeStrong](https://atom.io/packages/atom-typescript).

If I set the type of my variable to `any` rather than let it inherit `string`, the error goes away, as you might expect (but this is not really a good "fix"..)

Am I right in thinking the `endsWith` method should be included in `lib.d.ts` ?

**Comment by DanielRosenwasser** [comment]
`endsWith` is an ES6 string method. You'll either need to set your compiler target to ES6 in your `tsconfig.json`, use `lib.es6.d.ts` explicitly, or use the definitions for a polyfill library like core.js.

**Comment by egeland** [comment]
Aha, that explains it!

Thanks for the clarification! :smile:

**Comment by DanielRosenwasser** [comment]
No prob, glad that cleared things up!
