### ISSUE TITLE
Why TypeScript ReturnType returned sequence is unstable in vscode

### ISSUE THREAD

**Issue by Eve-Sama** [microsoft/TypeScript#51517]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.0 (Universal)
- OS Version: Mac 12.5.1

Steps to Reproduce:

```typescript
type A = () => 'a';
type B = () => 'b';
type Res1 = ReturnType<A | B>;
type Res2 = ReturnType<B | A>;
```
It's weird that above code run in vscode. I think the `Res1` and `Res2` is different. But they always keep same output. Sometimes they are `'a' | 'b'`, sometimes they are `'b' | 'a'`. I have to restart vscode window or restart ts server trying to get right output. Is this a vscode bug?

<img width="294" alt="图片" src="https://user-images.githubusercontent.com/30228406/201466370-1b8db121-75ec-4aa9-a5ea-f1f89121e106.png">
<img width="303" alt="图片" src="https://user-images.githubusercontent.com/30228406/201466373-1eaff816-2e4b-4699-bef6-6457bc8d97ff.png">

**Comment by Eve-Sama** [comment]
If it's ts's feature, Why it works fine in IDEA?

**Comment by fatcerberus** [comment]
I think IDEA uses its own language service that's based on the official one but with enhancements/customizations so it doesn't always behave the same.  Even so, this is just about display order - `A | B` and `B | A` are exactly the same type to the compiler.

**Comment by Eve-Sama** [comment]
```ts
const fnA: () => 'a' = () => 'a';
const fnB: () => 'b' = () => 'b';
const fnC: () => 'c' = () => 'c';
const fnD: () => 'd' = () => 'd';
const fn: TestFn = (requestList, thenCallback) => {
  console.log(requestList, `requestList`);
  console.log(thenCallback, `thenCallback`);
};

fn([fnA, fnB, fnC, fnD] as const, data => {
  console.log(data, `data`); // data: "a" | "b" | "c" | "d"
});
```

I have found how to make it works. Just need to add `as const`.
