### ISSUE TITLE
Bizarre Inferred Return Type of Generic Factory Method

### ISSUE THREAD

**Issue by mikepricedev** [microsoft/TypeScript#51512]
# Bug Report

### 🔎 Search Terms

return type inference, generics, nested generic inference, return type object inference

### 🕗 Version & Regression Information

- This is a crash ❌
- This changed between versions **N/A** and **N/A** 
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ✅ 
- I was unable to test this on prior versions because ❌

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/PQKhFgCgAIWhxApgO0QJwJYGNoDED2+UswUWANgIYDO1ehAPAKIAeALitRvsnYuygAmdAEqIs+NIIbU2mZAHMANNACuyANbJ8Ad2QA+fdADexaOYm85qrG0kAKNIkqCe5AJ7R+HXt14AuVh8uHmoAShMAXyhIgG4oKFAIGDgCfDxKW0l3ADpzAGEeQQw2P0pyaCwnSg46YoAzeqdkNnp8AHJqHOIQUkhLWUrqjjToAF5oe0o0BX8AI0JyZ2QIsaNphWgAfmhUHTb7UxhzaDnp-2hrRCUYiIu9g6OT0-PoevLqa7NzM4AvfwALAAmG6QSJheKQRLAaAASWQ9XQiEE0CcbFUaGQl3cAAdENB8PVoAADKrOEaEYlQNi4-EAFXG0DE6MxdNpDBpeMJQ3JiDS+khoGptOgAFVGWkGE8Tmc0BcFvglpRkJDIvooL0EpBgDCAHLTNC6DCKaA1DgAWxxbAu7ww5GoZFCrSc1FU5FaEzJNT5hHs73tiAhWow9XsACI-mHoMbUYhXe6ct5OH5wiZvpUnS9foyXW62ImBL5Qjk-pDnjroAAFQ14tA06DtP7taCuOO7fCtfgYQY8bF4hvGF5y06LZaxaCRdo5exAgDMs4AnGF0xWBq0-hd1FpdFiY8gMAoABZsDwxLUVgDqkg00AAgob1IJz2AeuZRrhMnY0LkCkUSmUKi9WpTWQdxzXwc1VDoCgaDoNhDxqLxC2ENoCSxZwsEPSpynIboUmgV86TQFw205fFjURTFlSwfF6kkWAQDOQQwGgAApABlPDYAI-Deh4tceW9NIrzQDRpnwR9GSmGZ5lHZVViMaVzBDaSFAiJTnljFksQeewYNoaBmELEJeCQnwULECQpBkORjWUNRNG0PRDDMoQ6ElIJk1CfRjHBQ5000mVXiuUFAvMcEyxOSIvADEweLCrSMR0xB9j0qgDKM4IU1c5ALPESRpFkeR7K3JyDCMJNcvcxhPKLXgfL8jSEtlG0Pi+Y4Ep+Sh-mBUKwoi9NopiSFoThBEkRRNEkr7fFuVJYYfXwESxIfXKqUgMixUZZkkrZPEOVpbkgMW5bxMfAVEmSaAADUpNvbRQPAqDKnS8IpXTFqR0VMcYiMAAfSZ7p4MCJOg16wgYHIofVSBNShbU9QNfA7NNNgLStC5XSwGjkQdfpMx0a97wk3KxHjD1BIpJbrzO3K-TaoNIBUiNuqjGNCdE4nHzJvMCyy0J1PTAS-kZDmNC50m415yqTK6UsVxhewcRrdAaQiDddlUc05nQM9ICAA)

### 💻 Code

```ts
class Foo<Extensions extends Record<string, unknown>> {
    constructor(readonly extensions:Extensions) {}
}

const createFoo = (arg:boolean) => arg ? new Foo({
    bar: true,
}) : new Foo({
    bar: false,
    baz:42,
});

const result = createFoo(false);

if("baz" in result.extensions) {
    const baz = result.extensions.baz;
    // Property 'baz' does not exist on type '{ bar: boolean; }'.(2339)
    // const baz: unknown in nightly
}
```

### 🙁 Actual behavior
Inferred return type of `createFoo ` is:
```ts
type T = Foo<{
    bar: boolean;
}>
```

### 🙂 Expected behavior
Expected return type of `createFoo ` to be:
```ts
type T = Foo<{
    bar: boolean;
}> | Foo<{
    bar: boolean;
    baz: number;
}>
```

**Comment by MartinJohns** [comment]
Look up "subtype reduction". It's working as intended.

**Comment by mikepricedev** [comment]
@MartinJohns Thank you! I never would have found "subtype reduction" on my own.

**Comment by fatcerberus** [comment]
I wish there was a well-known canonical issue for this we could dupe to, like we do with 9998.  People hit this all the time, and despite being by design, it's not always great (since it causes you to lose access to properties), so it'd be good to have a central discussion point to link to.
