### ISSUE TITLE
Generics narrowing not considering constraints when conditional is involved

### ISSUE THREAD

**Issue by Tiedye** [microsoft/TypeScript#51523]
# ~~Bug Report~~ Feature Request?

### 🔎 Search Terms

generics conditional types narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generics, Type System Behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221114#code/JYOwLgpgTgZghgYwgAgMpjpZBvAUMg5OALmQGcwpQBzAbn0ICNTtkA3OAGwFcJSKqIagF96hZAhbsuvfpRqjcw3GACeABxQA5CBQgATANIRVyALzIARI0vIAPlYSX6KjSgCCAHgAqAPnPI3i4w3CAIYMAA9iDIMD7IEAAekCD6ZMgA1iaRMGgYkL4AFFmqpN4ANOykXuiYEADa3gC6vgCUOEq4rprIAEI+-hbeCckQqemRjABWEOHIAPyByKQgEGzQwaHhUTHU8UkpaZnZubUFxSZllWyk-WcNzW0dyrgA9K-IYAAWwOkA7pEoBkyF0QmEItERgBGfajcbIHR6IwmIolMrtPDiGAXVSVbAcHh8ZAAcmJwla9Be70+P3S+kiuhAxLAoK2EJiSQATLDDulEZBkapUZdAhiGARqDi8QTZCSyRTkNTvr9yF9ItxOPpkCBImAaVBIn8iByoAaoMhGNw9cA9fTdEogA)

### 💻 Code

```ts
interface State {
    a: string;
    b: { value: string};
    c: { value: string};
}
type NestedKey = "b" | "c";

type A<T> = T;

function f<T extends keyof State>(key: T, v: A<State[T]>) {
}

type B<T> = T extends object ? T : never;

function g<T extends keyof State>(key: T, v: B<State[T]>) {
}

// this works

function ex1<T extends NestedKey>(key: T) {
    f(key, {value: ''});
}

// this doesn't

function ex2<T extends NestedKey>(key: T) {
    g(key, {value: ''}); // this should not throw an error but it does
}
```

### 🙁 Actual behavior

It seems when a conditional type is used, the compiler isn't evaluating the constraint of the given type parameter and instead falling back to the constraint defined locally.

### 🙂 Expected behavior

The arguments type should be narrowed using the most constrained generic regardless of conditional types

**Comment by MartinJohns** [comment]
It's a design limitation. The type of `B<State[T]>` can't be resolved, because the type of `T` is not known.

**Comment by RyanCavanaugh** [comment]
I don't think there's a sound way to compute the constraint-lookup interaction in the presence of arbitrary conditional types. `B` is effectively the same as the much more readily-reasoned-about `B & object` so I would use that instead.

**Comment by Tiedye** [comment]
> It's a design limitation. The type of `B<State[T]>` can't be resolved, because the type of `T` is not known.

Would it be possible to use the `NestedKey` type here?

**Comment by Tiedye** [comment]
Hope ts can do this one day!
