### ISSUE TITLE
TypeScript.transpile + TSX crazy outcome

### ISSUE THREAD

**Issue by andrewhathaway** [Microsoft/TypeScript#5152]
Hi there.

Using the TypeScript.transpile API and I'm getting some really weird outcome from the transpiler. I've looked around a lot and nothing helps, so this lead me to think this is a bug? Using TS 1.6.2.

Input:

```javascript
///<reference path="../typings/tsd.d.ts" />

import * as React from 'react';

export default class Test extends React.Component<any, any> {

  constructor(props: any) {
    this.state = {
      text : undefined
    };

    super();
  }

  handleClick(e) {
    e.preventDefault();

    this.setState({
      text : 'just testing'
    });
  }

  render() {
    return (
        <div>
          <a href="#" onClick={this.handleClick}>
            {'test'}
          </a>
        </div>
    );
  }
}
```

Output:

```javascript
///<reference path="../typings/tsd.d.ts" />
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var React = require('react');
var Test = (function (_super) {
    __extends(Test, _super);
    function Test(props) {
        this.state = {
            text: undefined
        };
        _super.call(this);
    }
    Test.prototype.handleClick = function (e) {
        e.preventDefault();
        this.setState({
            text: 'just testing'
        });
    };
    Test.prototype.render = function () {
        return href = "#";
        onClick = { this: .handleClick } >
            { 'test':  }
            < /a>
            < /div>;
        ;
    };
    return Test;
})(React.Component);
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Test;
```

Usage:

```javascript
TypeScript.transpile(src, {
  jsx: TypeScript.JsxEmit.React,
  module: TypeScript.ModuleKind.CommonJS,
  target: TypeScript.ScriptTarget.ES5
});
```

Notice issues around the onClick handler etc. Is this something I'm doing wrong, or is this a bug?

**Comment by kataras** [comment]
Same problematic output to mine .tsx files too, the output of the .js file is incorrect using meteor js and meteor-typescript package.

**Comment by ahejlsberg** [comment]
I think the issue is that you're not passing a `fileName` argument to `transpile`. Understandable, since you're supplying the text as a string, but we still need a (virtual) file name so we can check it's extension to see if you're transpiling a `.ts` or `.tsx` file (we default to `.ts` when no file name is specified). Try this:

```typescript
var options = {
  jsx: TypeScript.JsxEmit.React,
  module: TypeScript.ModuleKind.CommonJS,
  target: TypeScript.ScriptTarget.ES5
};
TypeScript.transpile(src, options, "module.tsx");
```

**Comment by andrewhathaway** [comment]
Hey @ahejlsberg!

Ahh I see. Yes that worked. Thanks for tip, appreciated. This should probably be documented somewhere?

I also feel like the transpile API isn't very well documented and results in a struggle to find information around it, even though reading the source is helpful.

Thanks again. @kataras - This works.

**Comment by vladima** [comment]
Currently if filename is not provided by user we'll [use](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L1854) `module.ts` as a filename. As an option in this case if value of `jsx` is either `React` or `Preserve` then we can use `module.tsx` instead.

**Comment by mhegazy** [comment]
you can find more documentation about transpile at https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#transpiling-single-file

**Comment by andrewhathaway** [comment]
@mhegazy I read this, but theres no mention of JSX/TSX compiling and the fact that you must supply the file name for it to be compiled in the correct way!

**Comment by vladima** [comment]
fair point, I'll update it

**Comment by andrewhathaway** [comment]
Awesome, cheers guys!

**Comment by mhegazy** [comment]
We should also fix the underlying issue, and if the name is not provided, a correct name (i.e. `module.tsx` should be generated)

**Comment by hydrotik** [comment]
Has anyone tried this when the TSX is importing another component in another file? I'm getting a cannot find module error.

**Comment by mhegazy** [comment]
@hydrotik this is an old issue. please file a new one and provide a code samples to help diagnose the issue.

**Comment by hydrotik** [comment]
@mhegazy thanks! I created here https://github.com/Microsoft/TypeScript/issues/6980
