### ISSUE TITLE
Import type from json file copies the json file to output directory

### ISSUE THREAD

**Issue by SzymonTMeniga** [microsoft/TypeScript#51537]
# Bug Report

### 🔎 Search Terms

resolveJsonModule, json, type, import

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about resolveJsonModule

### 💻 Code

```ts
import type * as a from 'pathToJsonOutsideSrcTree.json'
```

tsconfig.json
```ts
resolveJsonModule: true
```

### 🙁 Actual behavior

Json file was copied to the output directory

### 🙂 Expected behavior

Only compile-time checking and intellisense is provided, as the json file is not being directly used - only its type.

**Comment by RyanCavanaugh** [comment]
`import type * as a from 'pathToJsonOutsideSrcTree.json'`

Can you provide a concrete example? If the json is outside your `rootDir` then it shouldn't be copied
