### ISSUE TITLE
Weird behavior with type narrowing

### ISSUE THREAD

**Issue by ArthurKa** [microsoft/TypeScript#51539]
# Bug Report

### 🕗 Version & Regression Information

- This is a weird behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noImplicitReturns=false&noUncheckedIndexedAccess=true&jsx=0&exactOptionalPropertyTypes=true&ts=4.8.4#code/GYVwdgxgLglg9mABAGzgcwBQFMBciDkAhvogD4EBG+AlIgN4CwAUIohAgM5zJYB0qmLNQDczAL7NmMMFCwAnYIQhZEAeQoAres1bAYWZABMAjNjwcoc6Wmp4AbnBiGdiPQcMAmPGcQWrYG0QAXgA+RAcnUSYJJmZ2MAtEOE08dS0g7RZXfSNjPAEAGlYAemLEQBlyRAA5OER5OTg5FzcjLxR0IsRSxEBQckQAUTkGpujJJmSNXhaTDCIOQxoooA)

### 💻 Code

```ts
function log(e: 'a' | 'b') {
  console.log(e);
}

interface Obj {
  field1(e: string): void
  field2: (e: string) => void;
}

const obj: Obj = {
  field1: log,  // ❌ No error
  field2: log,  // ✅ Error
}

obj.field1('asd');
```

### 🙁 Actual behavior

They act differently.

### 🙂 Expected behavior
Should act the same.

**Comment by fatcerberus** [comment]
The short version is that methods are intentionally bivariant because otherwise `Array<number>` wouldn’t be assignable to `Array<string | number>`.
