### ISSUE TITLE
[4.9.2-rc regression] if/else narrowing with a branded string discriminant no longer eliminates matched constituents in later branches

### ISSUE THREAD

**Issue by seansfkelley** [microsoft/TypeScript#51538]
# Bug Report

### 🔎 Search Terms

assert never branded string literal union type narrowing

### 🕗 Version & Regression Information

This changed between versions 4.8.4 and 4.9.2-rc

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.9.2-rc#code/C4TwDgpgBAMhBmwoF4oHIA2DhoNwChRIoAlASwHMALJVNAJ0prSgDIoBvKR64ALnQ9mUAL4Ei0AKJlgVCPRSxsUAD6kmwAvngBXAHYBjYGQD2eqAEMAzlfnAAchABu8gBROBe5-ICUn7woc+FBQsvQmAO5QXlGS9OH0rmheLvRoPgQi+PgAJhAGGBb00AZmVkhOFhg6EALSsvJaZPBQ7lU1KMh0WIjpnMFQpXrlUPAmJgKY2CyoldUQmVAQGLZQza1zHV10Qjg+-SFDIwBGRZO7M1CbC1AA9LeDJvH5wBgg0UXhERA5UHlWYBk0GO9AsehyZD0FAAdLD8CIlitoEEQtZbPQHAE2vMMncHrDoccdEg9CYkMsyABbSEWYA-SxWSyDMEQnK0iDwoA)

### 💻 Code

```ts
type Left = 'left';
type Right = 'right' & { right: 'right' };
type Either = Left | Right;

function assertNever(v: never): never {
  throw new Error('never');
}

declare const value: Either;

if (value === 'left') {
  const foo: 'left' = value;
} else if (value === 'right') {
  const bar: 'right' = value; // correctly narrowed despite branding...
} else {
  assertNever(value); // ...but not eliminated as a candidate
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function assertNever(v) {
    throw new Error('never');
}
if (value === 'left') {
    const foo = value;
}
else if (value === 'right') {
    const bar = value; // correctly narrowed despite branding...
}
else {
    assertNever(value); // ...but not eliminated as a candidate
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>
      
      

### 🙁 Actual behavior

The compiler claims the `assertNever` is reachable (by virtue of only narrowing `value` to `Right` in the last branch).

### 🙂 Expected behavior

The `assertNever` is considered unreachable (that is, `value` is narrowed to `never`).

**Comment by MartinJohns** [comment]
[Working playground link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221115#code/C4TwDgpgBAMhBmwoF4oHIA2DhoNwFgAoUSKAJQEsBzACyVTQCdq60oAyKAbymduABc6PqygBfAsXDQAohWA0IjFLGxQAPuRbBJReAFcAdgGNgFAPaGoAQwDOtpcAByEAG5KAFK6GG3SgJQ+fspcRFBQCozmAO5QvrEyjFGMHmi+7oxo-pJiREQAJhDGGNaM0MaWtkiu1hj6EEJyCkq6hBTwUF619SjIDFiIWdxhUBWGVVDw5uZCmNhsqDV1EDlQEBgOUO2dSz19DCI4-sOE4WMTAEals4cLULsrUAD0T6PmSUXAGCBxpVHREHyUEKtjA8mgF0Y1kM+QohioADokUQxGsNtBQqcbPZHC4Ml1ltlnq8kQiLvokIZzEh1hQALZw6zAQHYmyjaGw-JMiAooA)
