### ISSUE TITLE
TypeScript can't infer type from union object type

### ISSUE THREAD

**Issue by SukkaW** [microsoft/TypeScript#51547]
# Bug Report

### 🔎 Search Terms

infer union property
union object property

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for any entries that contain `object`, `union`, or `property`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?pretty=true&exactOptionalPropertyTypes=false&ts=4.8.4#code/C4TwDgpgBAglC8UDeAoK6oEMD8AuKAZpgDYDO0APlAK4B2AJhAQJa0T1oYBG+pwATqwDmKAL5QqqDFnwDqETuh5Ra1ALZcI-MShQBjAPa0+UAEIIoACgP4YASgQA+KAYDcu05aQzCJcgBooZVE7RWlpAHoIqAA9bBRPb0x8OkYWNnpA4NDw3MjouISvHzkILPwQsNyo2PjEoPwoSqgawqA)

### 💻 Code

```ts
type A = {
    a?: false | undefined
    b: string
} | {
    a: true
    b: number
}

const B = (o: A) => o;

B({ a: false, b: })
           // ^?
// This can infer (property) b: string
B({ a: undefined, b: })
               // ^?
// This can infer (property) b: string
B({ a: true, b: })
          // ^?
// This can infer (property) b: number
B({ b:  })
 // ^?
// This will only infer (property) b: any
```

### 🙁 Actual behavior

```ts
B({ b:  })
 // ^?
```

TypeScript infers `(property) b: any`.

### 🙂 Expected behavior

TypeScript should be able to infer `(property) b: string`.

**Comment by RyanCavanaugh** [comment]
This is an interesting observation but an inferred type in the presence of syntax errors isn't something we can make any static guarantees about

**Comment by SukkaW** [comment]
> This is an interesting observation but an inferred type in the presence of syntax errors isn't something we can make any static guarantees about

I am looking for auto completion of the `b`, which is only possible when the type could be inferred.
