### ISSUE TITLE
Type 'Uncapitalize<Capitalize<S>>' is not assignable to type 'Uncapitalize<S>'.

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#51541]
# Bug Report

### 🔎 Search Terms

uncapitalize capitalize assignable 2345 intrinsic string manipulation types

### 🕗 Version & Regression Information

- This changed between versions 4.0.5 and 4.1.5, presumably because that is when [these](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#capitalizestringtype) intrinsic string manipulation types were added. 
- Nightly version as of test: v5.0.0-dev.20221115

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggNnA9gdwgEwMrAE4EsB2A5lALxQDkAhnGABaXlQA+FAQtpQG6KMvkDCACRgAlADIBJAKK8KaKWIAqMcgG4AsACg0EAMZxK2aADMArvl3BcifFCSps-SgGcIAMVzZnwMRGDAIbAAeDCgIAA8A-DRnKG88IgA+AAp4iXwALigMAEooLIBVC0owXGBqXAAvCBDEjU1dG28oXWo4QNIoMwsrGxCwyIho2Ph7dCwEwhTnLNCWJ1LyuCqajEScgG8tAEhWhHRa1JzVKAB6U4B5AGkdvfa0Q7HHF3dPb19-QKPjs9P8RGAUGuADpbm1xjhcJZAo8UIEnK4PF4fH4Athvidzv9ASCducAHIA6DAeiA5yQXS4YwgAjEEnQQhDQJQqCgSBQMCGSgAW1iyXItXIeTQiAgsWxUG5lAA1tBKFA0FTjIEhroIKDNNtzlJsNhENgoLhYsBnMkAEwAZgALABWHIZPGnGDYQimblDQGIYys8DQchFVqLCrVWrMKABkplYM1BZR5YhtaJRhGqASlzOXCEfCUABG7VZiEdnI47rRUC9PvZ5DmUFjSxWoZYEaD8dWSY1WtOil9FGbcYbdejtSThvFAKg6cz2bzxMQlb9NcHrcb4eKLYba3IHfOEjJEAgvLsuFlhrJtEQpjgaCgOeJ59MhFoAEIwfs0ISAOJMvC6ZJPBGvMiHxohivyElAjL4MyuhQMgpw5nqlA6AaRjAKY2C2Gy0Aptchq2PKwCICAAw8mA7QADSOjmpiAgQUBGNQJHcmRYrztko6pvuOjXoRLQ2DglB0QCtAdMWPJ+IEpyoehmG+s4GoAL71Do+iGCY5iWNYth3AcoQRFEMSwAgcKYJCSSpLMYZLhuiRhn29YJus+ThmAkDYK0ri1MpegGEYXQab02ngqZP5ov0+lDIZowmRMtLTIUa79o5eSFK5gQeW23mqX53SaTYLTBZ+35QhZRljCFtJWZGDk1NFqAVUkdmJTVQR1RCkxOVk8S0vUQA)

### 💻 Code

```ts
type AllowedString = 'alpha' | 'Bravo' | 'CHARLIE' | 'dELTA';
declare function lowerCaseFirstLetter<S extends string>(strIn: S) : Uncapitalize<S>;
const caller = function<S extends AllowedString>(s: S | Capitalize<S>){
	called<S>(s); //OK
	called<S>(lowerCaseFirstLetter(s)); //not OK.
	calledStricter<S>(lowerCaseFirstLetter(s)); //not OK.
	//Note that specifying the generic type params ('<S>') does not make a difference.
	//Error is ts(2345):
	//Argument of type 'Uncapitalize<S> | Uncapitalize<Capitalize<S>>' is not assignable to
	//parameter of type 'S | Capitalize<S> | Uncapitalize<S>'.
	//Type 'Uncapitalize<Capitalize<S>>' is not assignable to type 'S | Capitalize<S> | Uncapitalize<S>'.
	//It seems like it should be though!
	calledNoGeneric(lowerCaseFirstLetter(s)); //No generic w/broader return type is OK in a toy example,
	//but in real examples type S is needed to contrain other parameter/return types.
};
declare function called<S extends AllowedString>(s: S | Capitalize<S> | Uncapitalize<S>) : Uppercase<S>;
declare function calledStricter<S extends AllowedString>(s: Uncapitalize<S>) : Uppercase<S>;
declare function calledNoGeneric(s: AllowedString | Capitalize<AllowedString> | Uncapitalize<AllowedString>) : string;
```

### 🙁 Actual behavior

Error 2345: `Type 'Uncapitalize<Capitalize<S>>' is not assignable to type 'S | Capitalize<S> | Uncapitalize<S>'.`
I recognize that `Uncapitalize<Capitalize<S>>` is not assignable to S (example: `S = 'Bravo'`).
However, it should be assignable to `Uncapitalize<S>`.  

### 🙂 Expected behavior
`Uncapitalize<Capitalize<S>>` is assignable to `Uncapitalize<S>`. Inversely,
`Capitalize<Uncapitalize<S>>` should also be assignable to `Capitalize<S>`.

**Comment by Josh-Cena** [comment]
[`toLowerCase()` and `toUpperCase()` are not bijective](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UCqA7AxgQzAS2BgNtgF4QA8AwlrgcWQESCMgHQHzMDcAUAPRdR8B6Afg6hIUAEIIolHHkIlSqTLJoK6AfZbtuvAcKA)

```ts
type A = Uncapitalize<Capitalize<"ı">>;
//   ^? type A = "i"
type B = Capitalize<Uncapitalize<"ß">>;
//   ^? type B = "SS"
```

**Comment by Josh-Cena** [comment]
[`toLowerCase()` and `toUpperCase()` are not bijective](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwCMAeAylCAPYEB2AJvFIgE4CWeA5gHxQC8UA2gKp4DGAhmOcJwDbkAXhBQBhbrwHDRaGjQA0UNlx59BI9IuUdJ6meL3TNcutlyFiKoxtl0A-FGCkArtABcUAGYD4EALoA3ABQoJCwCMAATOiYOPhEJM6UtAzMEmrGotaZtlraGVJ5ckqF+po5RQamcRaJZVlaUI7OblCePvx+QcGh4NAAgmlwiKgARICMgGM0IQD0s1CLAHr2feEAQsOR4wD703MLy6tAA)

```ts
type Test1<S extends string> = [Uncapitalize<Capitalize<S>>, Uncapitalize<S>, Uncapitalize<Capitalize<S>> extends Uncapitalize<S> ? true : false];
type Test2<S extends string> = [Capitalize<Uncapitalize<S>>, Capitalize<S>, Capitalize<Uncapitalize<S>> extends Capitalize<S> ? true : false];

type A = Test1<"ı">;
//   ^?
type B = Test1<"ß">;
//   ^?
```

**Comment by wbt** [comment]
I suggest some documentation updates on this one, as I don't think I'm the only one likely to be confused by it.

**Comment by RyanCavanaugh** [comment]
We can't document the entirety of programming.

https://jeremyhussell.blogspot.com/2017/11/falsehoods-programmers-believe-about.html

> There's a one-to-one correspondence between upper- and lower-case characters.
