### ISSUE TITLE
Use explicitly versioned dependencies in package.json

### ISSUE THREAD

**Issue by bvlgah** [microsoft/TypeScript#51550]
## Background

I had been using an npm registry other than the default one (`https://registry.npmjs.org`).
Yesterday I encountered a problem when running test cases. It complained that
`Property 'isOk' does not exist on type 'AssertStatic'`. Finally, I found out the latest `@types/chai` was pointing
to the version `2.0.3` on the registry I used. The problem no longer exists after I changed to another registry.

## Suggestion

It is quite obvious the issue should not be blamed on `TypeScript`. I personally believe it will be nice to
declare a dependency on a package with its version in `package.json` for two reasons:

1. It makes registry-related issues appear earlier (such an error should occur while running `npm install`),
therefore it will be clear that the registry doesn't work.

2. The latest version of a package may contain breaking changes. With a version number specified (e.g.
`"@types/chai": "^4.3.4"`), it will be less likely to break backward compatibility.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
