### ISSUE TITLE
Feature request: publish git release tags during NPM package release process

### ISSUE THREAD

**Issue by jayaddison** [microsoft/TypeScript#51553]
# Suggestion

## 🔍 Search Terms

`git` `tag` `release`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

As part of the process for release of `typescript` packages to NPM, push a corresponding `git` tag to this repository.

## 📃 Motivating Example

Version 4.9.3 of `typescript` is currently available on NPM and it is not immediately clear what `git` commit version that corresponds to in this repository.

## 💻 Use Cases

This would be useful during dependency and upgrade review - for example, when looking for potential functionality, compatibility, performance, security and transitive dependency implications of a version upgrade.

With the current approach, `git` tags _are_ published, although that occurs some variable amount of time after package publication to NPM taken place.  It's possible that some users do upgrade before a `git` tag is published -- and it's also possible that they could review the contents of the release themselves to perform non-source-controlled review.

**Comment by freeatnet** [comment]
Something must have broken in the release process, as there seems to be no GitHub release and no [release notes.](https://www.typescriptlang.org/docs/handbook/release-notes/overview.html)

**Comment by RyanCavanaugh** [comment]
This is supposed to be automatic (you can see git tags for all the prior releases) but something must have broken recently.

**Comment by weswigham** [comment]
@DanielRosenwasser do you wanna add "Review and undraft the automatically made github release" to the release notes? 😂 We have a draft release over [here](https://github.com/microsoft/TypeScript/releases/tag/untagged-2a9e561006a6a360160b) just waiting for someone to check it over and undraft it, and I _believe_ publishing that triggers the git tag, too.

**Comment by weswigham** [comment]
(Actually, literally every 4.9 release is sitting in draft state, waiting for human review T.T )

**Comment by jayaddison** [comment]
Thanks @RyanCavanaugh @weswigham - I see the 4.9.3 tag now :+1: 

It depends on what works for your checklists and processes, but I've found that configuring GitHub Actions to publish-on-(tag|release) can be useful -- basically providing some level of linkage between the tag/release and the published package.

One tricky aspect is handling build/infrastructure failures gracefully, and/or testing the publication workflow before a 'live' package release.  I don't know what NPM offers there, but in the Python ecosystem, PyPi provides a ['test' instance](https://packaging.python.org/en/latest/guides/using-testpypi/) so that the entire package build and upload process can be checked before go-live.

**Comment by weswigham** [comment]
It's all really automated, it's just the UI on the release queue screen isn't great for editing a large blob of markdown, so the pipeline makes the release as a draft so a human can go edit the non-final GitHub release copy template with missing information and click "undraft". We now have a reminder on the job queue page that it needs to be done just after it's queued. 😅

If anyone from azure pipelines/GitHub actions is reading this by pure chance: queue time variable fields with configurable input box types and a markdown input box type would be a nice enhancement.

**Comment by jayaddison** [comment]
Thanks @weswigham - manual edits to the markup for releases displayed on GitHub makes sense -- and for a popular package, manual review steps in general seems sensible too!

Either way, if `git` tags could be pushed and made visible in the repository here during the package publication process to NPM, that could help users and developers to save time inspecting the differences between versions.

**Comment by per1234** [comment]
@weswigham please consider reopening. 4.9.5 was published hours ago and there still isn't a tag.

Related:

- https://github.com/microsoft/TypeScript/issues/43619
- https://github.com/microsoft/TypeScript/issues/41967
- https://github.com/microsoft/TypeScript/issues/39444
- https://github.com/microsoft/TypeScript/issues/34946
- https://github.com/microsoft/TypeScript/issues/34921
- https://github.com/microsoft/TypeScript/issues/33122
- https://github.com/microsoft/TypeScript/issues/31903
- https://github.com/microsoft/TypeScript/issues/31693
- https://github.com/microsoft/TypeScript/issues/26768
- https://github.com/microsoft/TypeScript/issues/17487
- https://github.com/microsoft/TypeScript/issues/11061

**Comment by per1234** [comment]
@weswigham please consider reopening. 5.0.3 was published hours ago and there still isn't a tag.

**Comment by per1234** [comment]
@weswigham please consider reopening. 5.1.6 was published days ago and there still isn't a tag.

**Comment by per1234** [comment]
Once again we have the problem of a package release having been published without the maintainers creating a Git tag.

@ahejlsberg @sandersn @andrewbranch @RyanCavanaugh @DanielRosenwasser @jakebailey please reopen this issue. There is clear evidence that your current system doesn't work.

**Comment by per1234** [comment]
Once again we have the problem of the 5.8.3 package release having been published without the maintainers creating a Git tag.

@ahejlsberg @sandersn @andrewbranch @RyanCavanaugh @DanielRosenwasser @jakebailey please reopen this issue. There is clear evidence that your current system doesn't work.

**Comment by RyanCavanaugh** [comment]
Locking. If we miss a tag please remind us in the iteration issue, not here. See also https://github.com/microsoft/TypeScript/issues/61023#issuecomment-2781955453
