### ISSUE TITLE
Cannot find module '../lib/tsc.js' when releasing typescript application to azure

### ISSUE THREAD

**Issue by paulsmithkc** [microsoft/TypeScript#51560]
# Bug Report

I am getting a build failure in Azure Devops to due a broken symlink, when using a Linux pipeline, to deploy a function app via zip archive.

See this thread for more information and a workaround:
https://stackoverflow.com/questions/57178989/cannot-find-module-lib-tsc-js-when-releasing-typescript-application-to-azur

### 🔎 Search Terms

Azure Devops, Linux, TS, Typescript, Build, ../lib/tsc.js

```
Error:***Cannot***find***module***'../lib/tsc.js'
***code:***'MODULE_NOT_FOUND',
##[error]Failed***to***deploy***web***package***to***App***Service.
##[error]Error:***Package***deployment***using***ZIP***Deploy***failed.***Refer***logs***for***more***details.
```

### 🕗 Version & Regression Information
- This is a crash
- This is the behavior in 4.8 and 4.9

### 🙁 Actual behavior

`npx tsc` fails to find lib/tsc.js due to a broken symlink

### 🙂 Expected behavior

`npx tsc` runs successfully and build pipeline succeeds

### Workaround

The following change in `package.json` solves the issue:

```
"scripts": {
  "build": "./node_modules/typescript/bin/tsc",
  ...
}
```

**Comment by RyanCavanaugh** [comment]
We don't have any control over this
