### ISSUE TITLE
Issue in conversion of Iterable collections to the Object using Object.fromEntries

### ISSUE THREAD

**Issue by mplekunov** [microsoft/TypeScript#51566]
# Bug Report

### 🔎 Search Terms

Object.fromEntries, Map.entries conversion to Object, property's name mapping in Object conversion.

### 🕗 Version & Regression Information
Versions: 4.8.4, Library: es2022

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about entry conversion... Unless I'm blind (which is possible), I can't find an answer or reasoning as to why this behavior should be expected.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?target=9#code/DYUwLgBAtghgDgIQK4HMIF4IDsQHcICy8APAM5gBOAlligDQQDe2MUIAXBOdbRAL4A+ABQBtALAAoCBBEAiAIyyGzLKw4RZAQVl8AunUnS5AJiVMWbTrIQ79hmbIDMZlWqsBhW5N0BKANySkqCQsHAA6gD2FADWNGiYOPhEcGSUccoW6txx-MLiUg4AxIoZqpYa2noGBXKFpqVuGjZV9rXODeWynnre-oESQeAQVGAgUKQYEJoUFDAAngB0AGYUEVBCocgoCyBYaSCkQj4+C6RRYEJCMAwARj4YAhAwIgAMugvAEQDGMKDua3AYBQQEIbq9fH0JCMxqQFsCAG4gCikEGQyRfCJYM6gD4RFBCADyNwAViAvmBlqsoABRPbUA5CaHjY79JkTTDTWaLFZrDbwSIxOI7OlUBnHU7nS7XCB3B5PcG4n5-AFAkFgt7HAJQ0bjOEgRHI1Fa9GY7EgXH4omk8mUta0-aHNksgYSIA)

### 💻 Code
```
let mapBug = new Map<string, { name: string }>([
  ["1", { name: "A"}],
  ["2", { name: "B"}],
  ["3", { name: "C"}]
]);

let mapWorking = new Map<string, { name: string }>([
  ["#1", { name: "A"}],
  ["#2", { name: "B"}],
  ["#3", { name: "C"}]
]);

let items = Array.from(mapBug.entries()).sort((a, b) => a[0].localeCompare(b[0]));
items.reverse();

console.log(Object.fromEntries(items))

items = Array.from(mapWorking.entries()).sort((a, b) => a[0].localeCompare(b[0]));
items.reverse();

console.log(Object.fromEntries(items))
```
### 🙁 Actual behavior

Returns an Object created from the map where "number" properties are placed in their value ordering (e.g. 1, 2, 3). 

```
{
  "1": {
    "name": "A"
  },
  "2": {
    "name": "B"
  },
  "3": {
    "name": "C"
  }
} 
```

### 🙂 Expected behavior

Should return an Object created from the map where properties are placed depending on their ordering after they have been sorted.

```
{
  "3": {
    "name": "A"
  },
  "2": {
    "name": "B"
  },
  "1": {
    "name": "C"
  }
} 
```
The only way to get this desired behavior is by appending something in front of the "key" name in order to make it look like a string and not a number.

**Comment by fatcerberus** [comment]
This is a runtime issue, TypeScript doesn't control what `Object.entries()` does at runtime.

**Comment by Josh-Cena** [comment]
FYI, this is because object properties that look like array indices are special-cased. See [OrdinaryOwnPropertyKeys](https://tc39.es/ecma262/#sec-ordinaryownpropertykeys): the keys are always sorted in the order of array index > string properties > symbol properties.

**Comment by fatcerberus** [comment]
Thanks @Josh-Cena, I figured this was expected behavior but couldn't find the relevant part of the ES spec.

**Comment by MartinJohns** [comment]
If order matters, use an array instead of an object / a map.

**Comment by Josh-Cena** [comment]
Technically speaking objects are unordered collections and relying on property order is unsafe—this behavior is only standardized for maximum determinism. I'm aware that JavaScript doesn't offer an _ordered_ key-value collection, so a map is probably the best you can have.
