### ISSUE TITLE
TS 4.9 Regression - cannot use "key in value" to search type variable

### ISSUE THREAD

**Issue by queengooborg** [microsoft/TypeScript#51568]
# Bug Report

### 🔎 Search Terms

- type variable
- type variables
- mutable type

### 🕗 Version & Regression Information

I started seeing this problem in TypeScript 4.9.3, updating from 4.8.4.  I also noticed this issue in 4.9.2-rc; other bugs prevented me from trying 4.9.0/4.9.1 beta.

### ⏯ Playground Link

The code that seems to be causing the error is here: https://github.com/mdn/browser-compat-data/blob/257f6f8973eaedd768ac06a6352cdb31bf57a099/scripts/fix/property-order.ts#L29-L35  (Since the TS playground doesn't have 4.9.x, I cannot link to it to show the problem there.)

### 💻 Code

```ts
const doOrder = <T>(value: T, order: string[]): T =>
  order.reduce((result: { [index: string]: any }, key: string) => {
    if (key in value) {
      result[key] = value[key];
    }
    return result;
  }, {}) as T;
```

### 🙁 Actual behavior

```
TSError: ⨯ Unable to compile TypeScript:
scripts/fix/property-order.ts:31:16 - error TS2322: Type 'T' is not assignable to type 'object'.

31     if (key in value) {
                  ~~~~~

  scripts/fix/property-order.ts:29:18
    29 const doOrder = <T>(value: T, order: string[]): T =>
                        ~
    This type parameter might need an `extends object` constraint.
```

### 🙂 Expected behavior

I expected the behavior to remain the same as in TS 4.8.4.  We know that "T" will always be an object (specifically, either `CompatStatement` or `StatusBlock`), but even so we should still be able to iterate the value's keys.

**Comment by MartinJohns** [comment]
[Playground link using nightly](https://www.typescriptlang.org/play?jsx=0&ts=5.0.0-dev.20221116#code/MYewdgzgLgBAJiA8gJzgU2TAvDAPAFQD4AKANwEMAbAVzQC4Z8AaGEVDB6ZASzAHMA2gF0AlA3zZCAWABQMVu2QA6ZGjjVgaYsVURqlKAwDeMAb3QAPTlB78hDcmACeMAL4sA1mifXbfEZIwRrLy8twAZjDEXi68MBQ0aAHBcqHyuvpQAjFC2PFUtNneQgDcIaGu5eloUNTIYDAZBmWp7kGuAeQQjCVAA)

https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#unlisted-property-narrowing-with-the-in-operator

> TypeScript 4.9 also tightens up a few checks around how in is used, ensuring that the left side is assignable to the type `string | number | symbol`, and **the right side is assignable to `object`**.

---

> We know that "T" will always be an object (specifically, either `CompatStatement` or `StatusBlock`)

The compiler doesn't know this. It just sees the unconstrained type parameter `T`.
