### ISSUE TITLE
when installed globally, tsc should check for ./node_modules/.bin/tsc

### ISSUE THREAD

**Issue by alexeagle** [Microsoft/TypeScript#5157]
If I am in a project directory where I've installed a particular version of typescript, I should get that version, even if it differs from whatever typescript version I may have installed globally.

This way, I get best of both worlds:
- short command to type
- the version of typescript that my project/team is currently using

**Comment by alexeagle** [comment]
@mprobst implemented similar in https://github.com/angular/clang-format/blob/master/index.js#L69

**Comment by alexeagle** [comment]
@mprobst you were looking for a first contribution to typescript, this seems perfect :wink:

**Comment by carlosdubus** [comment]
@alexeagle I would like to work on this issue. I'm new to Typescript codebase I added the code directly to bin/tsc so lib/tsc doesn't get loaded when is not needed. Would you rather have src/compiler/tsc.ts modified to look for node_modules/typescript? Also, tests are missing, not sure where to add the tests for this.

Let me know,
Thanks

**Comment by carlosdubus** [comment]
I also see there is a typescript version manager: https://github.com/watilde/tvm, not sure about the quality though.

**Comment by mhegazy** [comment]
We can not do this because of npm v3 flattening. see response in https://github.com/Microsoft/TypeScript/pull/5465#issuecomment-152669949
