### ISSUE TITLE
`Object.entries` assumes the key is always a string

### ISSUE THREAD

**Issue by 3dos** [microsoft/TypeScript#51572]
# lib Update Request

## Configuration Check

My compilation *target* is `ESNEXT` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Object.entries()`

## Sample Code

```ts
const obj: Record<'a' | 'b', string> = { a: 1, b: 2 };
const entries = Object.entries(obj); // is typed as [string, string][] instead of ['a' | 'b', string][]
```

## Fix

Possible fix would be to update the definition in lib.es2017.object.d.ts like this:

```ts
    /**
     * Returns an array of key/values of the enumerable properties of an object
     * @param o Object that contains the properties and methods. This can be an object that you created or an existing Document Object Model (DOM) object.
     */
    entries<K, T>(o: Record<K, T> | ArrayLike<T>): [K, T][];
```

**Comment by MartinJohns** [comment]
This is intentional. Objects are not sealed. See #38520 for more information.

**Comment by 3dos** [comment]
Well, I think the use case I stated here is a bit different than being based dynamically on keys. Instead of using string as the key type, there's a union type restricting the key type to a stricter one.

The fix I suggested is probably bad though :D but I don't see how this relates to the `{}` object becoming a `never[]` example.

Again, I probably miss something here and probably lack of understanding the underlying issue.

**Comment by MartinJohns** [comment]
You're assuming the keys can only be `"a" | "b"` because the object is typed `Record<'a' | 'b', string>`, but that's wrong. All it says is that the keys `"a"` and `"b"` are typed `string`, but not that there aren't any other keys.

**Comment by 3dos** [comment]
This is where I fail to understand what additional keys could possibly be there. As per the [MDN docs for Object.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) it seems only the actual keys are created. Is there a real life example of such divergence in the object/entries keys that could help me get this?

Anyway, is there a way aside from casting with `as [TheUnionTypeOfMyKeys, TheValueType][]` to get the stricter type as a result?

I'll read the whole thread again later on to make sure I didn't miss any crucial piece of explanation. Thank you for trying to explain this to me.

**Comment by alexburner** [comment]
> Is there a real life example of such divergence in the object/entries keys that could help me get this?

Here's a good example: https://github.com/microsoft/TypeScript/pull/12253#issuecomment-348026336

TypeScript uses structural typing, not exact types. So extra keys may be allowed on an object, outside its type.

**Comment by nandorojo** [comment]
For what it's worth, I sue these custom wrappers:

```tsx
export const entries = Object.entries as <T>(
  obj: T
) => Array<[keyof T, T[keyof T]]>
export const keys = Object.keys as <T>(obj: T) => Array<keyof T>
export const values = Object.values as <T>(obj: T) => Array<T[keyof T]>
```

Here's a [playground](https://www.typescriptlang.org/play?#code/FAUwHgDg9gTgLgAgMZQHYGdElXGBLEdBAXgQHkAjAKxCTgDptcCiBDIgHgBUA+ACmAIEUagC4EXYAEoSPBAEEYMVgE8OAbQDWIFVABmEgDQStO-RIC6FnqEixEKDIm0qipSjTr0XbTrz4iVOJcMsRyispqLua8ttDwyGiYCABurAA2AK6EJOTUtAxpWTnsCNz8gcGh4Uqq3Ka6BlzWwKA4+IR8AN6CQgguIAAm4rjZwAC+UvQAtqwQfHwNxkXZFtUIPX0IeAZ8LiSkAOSHMptbfb1C4xNSQA).

<img width="1000" alt="Screen Shot 2022-11-17 at 3 17 52 PM" src="https://user-images.githubusercontent.com/13172299/202550969-eb41b598-4d5c-41b3-aee9-241dd2cafc97.png">

**Comment by MartinJohns** [comment]
@nandorojo These wrappers are fairly common. Personally, I'd add the prefix `unsafe`, to make really clear that these wrappers are unsafe.

**Comment by KevinGervais** [comment]
just do this and the problem is gone
declare global {
  interface ObjectConstructor {
    keys<T>(o: T): keyof T
  }
}

**Comment by SanariSan** [comment]
> I added // @ts-ignore because ts would tell me this:

I don't have such issue, but you may try to use `PropertyKey` keyword, which is what used for indexing objects under the hood

Also your first example produces union of values from every key which gives poor type narrowing even when explicitly checking the property:

![image](https://github.com/microsoft/TypeScript/assets/76019273/60640ac5-eff0-4662-b2d6-691cf4f714ed)

You should instead follow the pattern above and use indexed access type instead of manually assigning union
