### ISSUE TITLE
spread of overloaded function rejected on generic components in JSX as of 4.7.4

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#51577]
# Bug Report

### 🔎 Search Terms

spread jsx generic overload

### 🕗 Version & Regression Information

- This changed between versions 4.6.4 and 4.7.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=4&ts=4.7.4#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA0AmWuANspXAQK4B2+wE3OCWAwAPABUANHADScLAA8YWbvXSoYUYNwDmAPgAU3ZCCyoAXHErJ6A5gE9ZAbQC60iACMAVpfEBKSwB5EBEJaRk9AG4GJlZ2Ll4YfkFhMTlFZVV1TW19IxMzS2tbbgdnFwC4CUNPHzh-OABePThg0KlZKLpGFjYsOFwBDSEYAAssKAAFYjALTCZoelENLV1pZG57FoAfOB5GAm0sejpB7mHtZShTemBkZWmIWaahEJgDJzICCAgyNxHxlMZqg-DQzsMwMCAOrQADWuQAktwrjc7soXgBvGhwHFwAB0BMuE1R9ywj1mNAAvtEAPQ0uAAZQKKHQAANIU9UDCoPDdKy4B5OPAAO4iUYQIUoQRE67HNH9ABuyGYnCwYKG8A5s25vJ0ABFgJR8JjsbiCXjUh8vj8-u4xhNySCqdEaAk+AI4ABhEiQbgqd5auYYjg-AD8lhWuTglL8cCxuKsWBgnCggm4nGYzCprp47sEAHEVBNgLhveABP7qgZA5Zg98IOG4JHdNHY-HcZRk6m4OnM9m6KIy77-XHzTKSQ9gZS4DSuqJC36tKWfRXkaPCcjiXLSY7p7PooOV361xjzZbPvXbQCHcC-Hu5wvi8vy8f4KeCefrb9-hB7UDOXeM5dI+S5Dqu7zvhabxWpeP5-o6d5+C6NBAA)

### 💻 Code

```ts
function GenericComponent<T>(props: { foo?: string }) {
    return null
}
function GenericComponent<T>(props: { foo?: string }) {
    return null
}
<GenericComponent {...omit(['foo'], otherProps)} />;
```

### 🙁 Actual behavior

`Spread types may only be created from object types.(2698)`
unless we save `omit(['foo'], otherProps)` in an intermediate variable and spread that instead (work around in playground).

### 🙂 Expected behavior

No error since it's valid at runtime. It's also accepted by TS without JSX or on non-generic components or if we save the value in an intermediate variable. All cases are explored in the playground.

**Comment by jakebailey** [comment]
#51580 and #51580 didn't play along, so the fix for this has been reverted.
