### ISSUE TITLE
Type check errors from typescript node_modules folder when upgrade typescript from 3.8.3 to 4.5.0

### ISSUE THREAD

**Issue by monicaricks** [microsoft/TypeScript#51576]
# Bug Report
I'm getting these errors after upgrading from typescript from 3.8.3 to 4.5.0 when running npx tsc --noEmit:

  node_modules/typescript/lib/lib.es2015.promise.d.ts:33:34
    33     new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'value' was not provided.

### 🕗 Version & Regression Information
This changed between versions 3.8.3 and 4.5.0

**Comment by RyanCavanaugh** [comment]
Please provide a reproducible sample using the latest (or at least recent) TypeScript version.

**Comment by fatcerberus** [comment]
This was a documented breaking change
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#resolves-parameters-are-no-longer-optional-in-promises
