### ISSUE TITLE
Feature request: pick a single way to represent Array<Item> / Item[]

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/TypeScript#51573]
# Suggestion

We have `Array<Item>` and `Item[]`:

- `Item[]` seems to be older
- `Array<Item>` seems to more consistent with the rest of TS, eg `Promise<Array<Item>>`, as well as reading better 'promise of an array of items'

TS right now seems to use the `Item[]` syntax. When the next major change to TS is released, it would be bice to prefer the more consistent, `of` style syntax.

![image](https://user-images.githubusercontent.com/172594/202502752-8c98fd02-76c9-44cb-b4f3-67ca69d0b22d.png)

## 🔍 Search Terms

Representation, Array, syntax.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

For TS errors, feedback etc. to represent `Array<Item>` as `Array<Item>`, consistent with the way TS represents other nested types.

**Comment by fatcerberus** [comment]
> TS right now seems to use the `Item[]` syntax.

The relationship between `string[]` and `Array<string>` in TypeScript is the same as that between e.g. `int` and `Int32` in C#.  One is syntax; the other is the userland type backing the syntax.

**Comment by MartinJohns** [comment]
I'm sure there's a linter rule for this.

**Comment by RyanCavanaugh** [comment]
This doesn't seem to solve any concrete problem. Both syntaxes are popular and a common theme in codebases is to mix and match depending on the element type.

**Comment by mikemaccana** [comment]
@RyanCavanaugh there's a few concrete problems consistency would fix. I pasted the vscode example in the feature request thinking they'd be obvious, but perhaps it's better illustrated with more complex types:  

 - Inconsistency makes errors and type annotations difficult to read. `Foo<Bar<Baz<Array<Item>>>>` and `Foo<Bar<Baz<Item[]>>>` are the same type, but it's difficult to compare them as they're using different syntaxes to represent the same thing.
 - Likewise  `Foo<Bar<Baz<Array<Item>>>>`  can be read as `Foo of Bar of Baz of Array of Item` whereas the other syntax cannot, since it mixes both `of` and a literal representation of an array. 
  - More people will use TS in future than who use TS presently, the unnecessary additional syntax requires additional mental overhead. 
  - Good design, [Exupery's Law](https://duckduckgo.com/?q=exupery%27s+law+perfection), etc.

**Comment by mikemaccana** [comment]
@MartinJohns the feature isn't asking TS to drop support for code using the old syntax, but rather for TS's error messages and type suggestions to use the newer syntax (eg, the suggestion in the screenshot above). There is no option to make TS itself use the newer syntax as far as I know.

**Comment by mikemaccana** [comment]
@fatcerberus "one is syntax" - this isn't correct, both `Array<Item>` and `Item[]` can be used interchangeably by code

**Comment by fatcerberus** [comment]
Yes, but `Array<Item>` is just a specific instance of the more general `Foo<Bar>` type instantiation syntax, referring to the userland `Array` type.  `[]` means something to the compiler on its own (even if it's ultimately aliased to the aforementioned userland type).  That's why I meant by "one is syntax".

**Comment by mikemaccana** [comment]
Got it @fatcerberus . I've edited the post to make it clearer that the feature request is to use the `Foo<Bar>` type instantiation syntax consistently.

**Comment by RyanCavanaugh** [comment]
That doesn't seem to solve any concrete problem either. `string[]` is a popular way to represent this type, and for good reason (it's short, and well-precedented in programming). Using `[]` notation also avoids potential problems in case the name `Array` is locally shadowed. And it's not like people won't continue to encounter `number[]` in declaration files for the rest of time - they'll still need to know what it does.

**Comment by fatcerberus** [comment]
I think there's also a case to be made that this aliasing mirrors the fact that in JS you can choose to write either `[ 1, 2, 3 ]` or `Array.of(1, 2, 3)`

**Comment by MartinJohns** [comment]
To be fair, they're not **entirely** interchangeably, when involving `readonly`.

```typescript
function f1(v: readonly string[]) {}
function f2(v: readonly Array<string>) {}
```

**Comment by mikemaccana** [comment]
@RyanCavanaugh I think we're optimising for different things. I don't think keystrokes particularly matter, code is read far more than it's written so it's worth optimising for consistency there. Likewise older syntaxes do tend to exponentially decay over time. Someone locally shadowing Array, doesn't seem worth harming everyone else's experience. But I don't feel additional discussion will change much so fair enough, two syntaxes it is.

**Comment by RyanCavanaugh** [comment]
I ran the numbers just to be sure - on DefinitelyTyped, there are 21,000 occurrences of `string[]` and 2,900 occurrences of `Array<string>`. For `number`, it's 6,700 vs 740. For `any`, it's 21,000 vs 600. So there's a fairly consistent ~9:1 preference for the `T[]` syntax.
