### ISSUE TITLE
Destructuring into a rest property breaks unused variable detection

### ISSUE THREAD

**Issue by Livven** [microsoft/TypeScript#51574]
# Bug Report

### 🔎 Search Terms

is declared but its value is never read, unused, rest, spread

### 🕗 Version & Regression Information

- This is the behavior in every version I tried on the TypeScript playground, including nightly, and I reviewed all [FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs) entries.
  - For versions before 3.7 the `noUnusedLocals` and `noUnusedParameters` options need to be turned on to surface the error, as there is no warning by default.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true#code/GYVwdgxgLglg9mABAdzgJwNYzAcwBQDeiAhgDSIBGiAvgFyIHH1ggC2FApmuRc2590QQ+7LtQCUDAFCJZiAPTzEAA2LKSYACYqK64mg6IDEODjAwAXh23EAzonAhb1qdSlTQkWAkRg4UAHV0LFwAmCgACwAlDlsoAEZCEh5yADp0gziaekYRAR48rnJhX34xSQIZOUUVTKh1GHtjU3MrG3tHZ00eECgVNQ1tZV1fOEQAGwQcLhIDV3dPaHgkP0Dg7BwwyJi4gCYksko0jNi+ugYmUtFBXiv8oUK0CWk5BSVVPS0dPQNEOJhxuNRn1mmZLNYSB0WF1EBwAG4cJDICKI2qnBodLpVWQmMBZCCIAC8DCMpxoAG55h5wEsfKsgpgNltoqcAMx4AAO+mIrFsOUuLGuBTuRQeIqeFWxb0QmlOaBA0BAaA2iEijRQxAAnrCAB4RGAUcL2SKGWw8wyNWwgDhS3FZIiHCjHVJ1GhExBctA82yUtxAA)

### 💻 Code

```ts
function working({ a, b }: {a: number, b: number, c: number}) {
    // `a` and `b` are recognized as unused
}

function notWorkingWithRest1({ a, b, ...rest }: {a: number, b: number, c: number}) {
    // `rest` is recognized as unused, but `a` and `b` no longer are
}

function notWorkingWithRest2({ a, b, ...rest }: {a: number, b: number, c: number}) {
    // `a` and `b` are still not recognized as unused even when `rest` is used
    const c = { rest };
}

function notWorkingWithRest3(params: {a: number, b: number, c: number}) {
    // destructuring this way exhibits the same issue
    const { a, b, ...rest } = params;
}
```

### 🙁 Actual behavior

See commented code above. Once an object is destructured with a `...rest` property, unused variable detection for the other (destructured non-rest) variables breaks.

This also seems to affect the [`@typescript-eslint/no-unused-vars`](https://typescript-eslint.io/rules/no-unused-vars) rule.

### 🙂 Expected behavior

Destructuring an object with a `...rest` property should not break unused variable detection for the other variables.

**Comment by fatcerberus** [comment]
Hmm, that's a good point, JS doesn't let you write `const { a: _, b: _, ...rest } = params`

**Comment by RyanCavanaugh** [comment]
I don't think we want to turn a boolean (used / not used) into a tristate (used / kinda-used / not used) just for the sake of this exact scenario. The *binding element* absolutely is used and the fact that only half of it (the input field but not the local name) is used is a distinction without a difference.

**Comment by MartinJohns** [comment]
@fatcerberus You can write `{ a: _a, b: _b, ...rest }`.
