### ISSUE TITLE
`in` keyword not inferring property when checked with string variable 

### ISSUE THREAD

**Issue by douugdev** [microsoft/TypeScript#51589]
# Bug Report

Hello! This is my first bug report, I do not deem this to necessarily be a bug, but I don't think it's a suggestion either since the correct behavior should be obvious.

### 🔎 Search Terms

in keyword operator inference 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221118&ssl=24&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgLIE8DyAjAVsgbwCgBIOOALmRAFcBbbaAbiIF8iiEB7EAZzGQAHKF0HQw6AHJw6EKvyigA5sgC8yAOTkNLTj37I6WPFQw5864mUrIAjLYA0bDsBjIAFMNHipMlKENjXABKQlIAenDkAGUACy4aABsAExANAS8xKAlpWWRGbjyAAwBrCHQuNyNzIoB+Um4+LkSIADpEriV3arwAbUyfXIgAXWCmZA4SSOQAFVjgXmQAdy4oEsXsGgE4ZOTFmhAQCCReXjgodHyuYBaoQUS4SGReUCRkMHnFiAAPY62IRY8RKXVxCERZHJ+ZALZBwZBlS6VQLmBr6ZptDpdHq4frgwZQuCLBFIsx4UYTdgcRoGKBwEDJLh0cxULh4Y4CSysXSg9xaOAaaEgZC0+mM8yhKwihlMvp8jTDcbTADqsUuDIB70+y1WJXyW1hzzAihAKkaYDgoAgyUFL2SKDhADdzsA4NgWsh1bw0mB6qwgA)

### 💻 Code

```ts
interface MyObj {
	aa: number;
}

const propertyName: string = 'aa';

const myObj: MyObj = {
	aa: 11,
}

if (propertyName in myObj) {
	// Shouldn't propertyName become `keyof myObj`?
	console.log(myObj[propertyName]); // Errors

	// This works but adds unnecessary boilerplate since this executes only if propertyName is a key of myObj
	console.log(myObj[propertyName as keyof MyObj]); // Works
}

const randomObj: object = {};

if ('aa' in randomObj) {
	randomObj['aa']; // Why does this work but a string contained inside a variable doesn't?
}
```

### 🙁 Actual behavior

`propertyName`'s typing continue to be `string`

### 🙂 Expected behavior

`propertyName`'s typing become `keyof myObj`

**Comment by RyanCavanaugh** [comment]
The problem is here
```ts
const propertyName: string = 'aa';
````
where the type annotation says, in effect, "Treat `"aa"` as an arbitrary string". Had you written
```ts
const propertyName = 'aa';
````
then the example works as expected.

Because object types are not sealed, given a value `myObj` of type `MyObj` and a truthy expression `s in myObj`, it is neither guaranteed that `s` is `keyof MyObj`, nor that `myObj[s]` corresponds to a value of a declared property type of `MyObj`

**Comment by douugdev** [comment]
Thanks for taking a time to explain that behavior better @RyanCavanaugh!
Firstly, the intention was really to treat `propertyName` as an arbitrary string, explaining my use-case better:

```typescript
const myObj: MyObj = {aa: 'bb'};

Object.entries(myObj).map(([key, _]) => {
    if (key in myObj) {
        console.log(myObj[key]); // Errors
    }
})
```
since `Object.entries` returns the type of each key as an arbitrary string, I can only access the property key if I typecast `keyof myObj`, so not only is it looping through exactly those keys, it's also doing an `in` check, adding a third operation to typecast it feels like adding too much boilerplate. 

Also I'm a little bit confused about what you said here:
> Because object types are not sealed, given a value myObj of type MyObj and a truthy expression s in myObj for an arbitrary string s, it is neither guaranteed that s is keyof MyObj...

I'm still confused about how would `s in myObj` return true and still not guarantee it's a keyof MyObj, and I'm also consfused about why TS won't even type-cast it as something like `keyof MyObj | undefined` even if I do `Object.seal(myObj)`, `Object.freeze(myObj)` or `myObj as const`.

**Comment by RyanCavanaugh** [comment]
> I'm still confused about how would s in myObj return true and still not guarantee it's a keyof MyObj

See https://stackoverflow.com/questions/55012174/why-doesnt-object-keys-return-a-keyof-type-in-typescript - the same logic explained in that post applies here

**Comment by fatcerberus** [comment]
I think it’s a common misconception for people to think of `keyof T` as a first-class concept meaning “any value which can be used to index `T`” but in reality it’s a type operator that evaluates to a union of the declared keys of `T` (which *can* index `T`, but this is almost incidental) - and structural subtyping means you can end up with keys that aren’t assignable to `keyof T`.
