### ISSUE TITLE
Union type in a generic method is not always properly validated

### ISSUE THREAD

**Issue by kugacz** [microsoft/TypeScript#51587]
# Bug Report

### 🔎 Search Terms

union literal generic method

### 🕗 Version & Regression Information

All versions including night build 5.0.0-dev.20221118

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221118#code/MYGwhgzhAEBiCWBTEATAPAETAFzAFQE8AHRAPmgG8AoaW6CXbeYaAJ0TBQHsA7EA6CHjZErMCATIUALjhJUaAOQBBRQB9FAIUXkAvNB6IA7nKlLVG7aQAUASgDcdaDToMczNh258BPAK4AtgBGopKosmHoAIxqAEx6BsamCjHxdvYutG5MLOycvPzQAfAAHogokRHy6CrqWupRCYYmkeZ12mqN6U5UAL5UVKCQMADqrLwA5pEIICKslD1OAGbws6KYOPjEZNYrUlVmWLiEJKQANNAAbuJ+iLJHWyS2spdc8CiUmU7QwLwQXCBEAA6EBcCbWa4gW4OL79fqDcBQaAAcS4XAq1Rmcw2x225GoTl+PAYrD8wGwXFY1iIrHg1xE0D24WS6AeJzItko8OWqzmEJud2gbO2zyubw+BO+tCJ-0BILB-KhiBhTjhAwA9OroGNJtNeaJoABacjYAAW8BgQyRpsg0CM4x4E2gIRtl3glIGMuwjMx+vm+ma2odU19aypMKZGLDQJWYeskRBwlE4kiF1qDmgmugAHkANKyWrQC1FnjQWqWRTQbDbKiRrGiGN++PVRNzFPVNMALUUGazAEJ7ZNnYhXe7WBcIKauH5UGwwBbENBRONWLJlKwJoFEDxvVwllXtmXu0WYDwuN7hvAJjwwEFAVWuNAiGAxAFEHNoHuDyQywAiZS-tAajQL+mi-ooQLWLEADMAAsACsti1qGcyNnGCZCG2Egdkela2l6vZagOwbDqOlITlOM4fGIC5LqwK5rhuW47p++7Vj+ijHsWZ4XlAV43nei4Uk+L5gG+H5fuxi6KP+gHAaB4GQTBCFIXWfpoXyGFJmI2FSBcsSxIROa5hceQLjAy6Uoxm5vixkmHooBmVtx57QJe163vewnPq+74GvZHGyUBIFgRBUFwYhAzIVI9asBpojNlIQL+MEoQ4VERl5rIUQniW0CpN+iDRagsXxVSCYpSErCptA0FGcRQ4umAbrkfQlGzjRECLpZq7QOuNnbrubEOdBzmnq57kCV5j4+WJfnzAF0k5cBsRhcpkVqdGsaaS2lVpXptVuZafzYPVg6OqRzVjhR04dfOXV0QxfVMbZQ2FWWo25TxR0QPxnlCTNonif5w0cct0CrUpEWqShDbbQlFWBFVNWcT2jhZnmpkcOZj1Wc9A12aD0m-p24FfRNfEeYJD4ib5ElE2W4OQ+FKkalq8D7kYi5+A9xRlB8fg8O6pZfnt8xgDwHwkvAF2YcmIAwGai5NS18zFr89GIOSfYDJtqHw+VLZ8+UNUZejWpZfluUy-lcSFcVUb602CbGxiB11ebxlY-diAWfReP9cxb1SR9Y0GBTv1U9NtNzfT70yQBwUKcFURrdDDulQbiWoECrso6omX5mWqjW6W5b1Pbetw87RulCbOGo4X3s4z11lB6x8ck2TLm8ZHU0AzHwMLQzCdySFY+p1DrNUFmqLonqYZGia5owBAQgTKa2CFCgHNLKIg0-IiMDFhLS4lGJRD3l+Exoh8Ktjp6J0+jFfoADLaeI0ABkkc9uyVNdJTljpSIRkuZuXYE+cYbod4XTAM-WcNslY-BOqScklISwMC8B3JB4kpwfGAOIEAGc34fxAGVaw6ZPaW0LMWG25dtCV1hqwd+WFyGNyoSZTwPs-ZPUDq9bBDku5h2+pNf6NNZpDwEYFRO8lQpTw2kwlh8tyEGSblwlu-tep8IPotMsTlya9z+tTbyQN5pSOJjI8eadp5engY7UQAA5JGBpv4mF-gvHaSUxYgM9mAl8i4aRcGgTLJ0cDIx5SQV6VBFI1bEhEJwbBppFy4PRD8QhxCwxONSnFLOZtMwWyLjlWhpYCpSQyXMLJVVyEe3yV7dRXUeEBxejoken0e4-SMdHCRZjdGKCZtYhRL9MnOJyU2dhtTMb1N9rjLRzTCad1JsIiOnSB7dLjiHPpwVmbrVsEAA)

### 💻 Code

```ts
class Field<DataType> {
    static readonly literalField: Field<'A'|'B'> = new Field<'A'|'B'>();    
    static readonly numberField: Field<1|2> = new Field<1|2>();
    static readonly mixedField: Field<'A'|'B'|1> = new Field<'A'|'B'|1>();    
}

class WrongFieldFilter {    
    filter<DataType>(field: Field<DataType>, value: DataType): void {
        console.log(value);
    }
}

class GoodFieldFilter<DataType> {
    constructor(private field: Field<DataType>) {}

    filter(value: DataType): void {
        console.log(value);
    }
}

// WrongFieldFilter -> this class has wrong behavior

const fieldFilter = new WrongFieldFilter();
fieldFilter.filter(Field.literalField, 'A'); // OK: 'A' is in 'A'|'B' type
fieldFilter.filter(Field.literalField, 'Z'); // !wrong behavior, should raise error: Argument of type 'Z' is not assignable to parameter of type '"A" | "B"'.(2345)
fieldFilter.filter(Field.literalField, 'Z' as const); // !wrong behavior, should raise error: Argument of type 'Z' is not assignable to parameter of type '"A" | "B"'.(2345)
fieldFilter.filter(Field.literalField, 22); // OK, reaises error: Argument of type '22' is not assignable to parameter of type '"A" | "B"'.(2345)


fieldFilter.filter(Field.numberField, 1); // OK: 1 is in 1|2 type
fieldFilter.filter(Field.numberField, 3); // !wrong behavior, should raise error: Argument of type '3' is not assignable to parameter of type '1 | 2'.(2345)
fieldFilter.filter(Field.numberField, 3 as const); // !wrong behavior, should raise error: Argument of type '3' is not assignable to parameter of type '1 | 2'.(2345)
fieldFilter.filter(Field.numberField, 'Z'); // OK, reaises error: Argument of type '"Z"' is not assignable to parameter of type '1 | 2'.(2345)

// if we use mixed union of number and string literals the behavior is correct!

fieldFilter.filter(Field.mixedField, 1); // OK: 1 is in 1|2 type
fieldFilter.filter(Field.mixedField, 3); // OK, reaises error: Argument of type '3' is not assignable to parameter of type '"A" | "B" | 1'.(2345)
fieldFilter.filter(Field.mixedField, 'A'); // OK: 'A' is in 'A'|'B' type
fieldFilter.filter(Field.mixedField, 'Z'); // OK, reaises error: Argument of type '"Z"' is not assignable to parameter of type '"A" | "B" | 1'.(2345)

// GoodFieldFilter -> this slightly different class is an example of good behavior

const fieldFilterLiteral = new GoodFieldFilter(Field.literalField); // we are providing a field in the constructor instead of the method call
fieldFilterLiteral.filter('A'); // OK: 'A' is in 'A'|'B' type
fieldFilterLiteral.filter('Z'); // OK, reaises error: Argument of type '"Z"' is not assignable to parameter of type '"A" | "B"'.(2345)
fieldFilterLiteral.filter(22); // OK, reaises error: Argument of type '22' is not assignable to parameter of type '"A" | "B"'.(2345)

const fieldFilterNumber = new GoodFieldFilter(Field.numberField); // we are providing a field in the constructor instead of the method call
fieldFilterNumber.filter(1); // OK: 1 is in 1|2 type
fieldFilterNumber.filter(3); // OK, reaises error: Argument of type '3' is not assignable to parameter of type '1 | 2'.(2345)
fieldFilterNumber.filter('Z'); // OK, reaises error: Argument of type '"Z"' is not assignable to parameter of type '1 | 2'.(2345)
```

### 🙁 Actual behavior

When we provide as a generic method parameter a union of literals of the same type (eg. strings) TS doesn't validate parameter values against this union literals, but wider against the literal's type.

### 🙂 Expected behavior

When provided a generic method parameter is a union of literals of the same type TS should validate this parameter against union literals and raise 2345 error when the passed parameter doesn't belong to this union.

**Comment by MartinJohns** [comment]
> fieldFilter.filter(Field.literalField, 'Z'); // !wrong behavior, should raise error: Argument of type 'Z' is not assignable to parameter of type '"A" | "B"'.(2345)

It's perfectly valid for the type argument to expand to `"A" | "B" | "Z"`, and `Field<"A" | "B">` is compatible with `Field<"A" | "B" | "C">`. This generic widening only happens with related types, that's why the `Field.literalField, 22` errors, but that can be made working as well: `fieldFilter.filter<"A" | "B" | 22>(Field.literalField, 22)`

This is working as intended.

**Comment by RyanCavanaugh** [comment]
There's a secondary issue of `Field` not using its type argument.

The definition that does what you want is:
```ts
class Field<DataType> {
    static readonly literalField: Field<'A'|'B'> = new Field<'A'|'B'>();    
    static readonly numberField: Field<1|2> = new Field<1|2>();
    static readonly mixedField: Field<'A'|'B'|1> = new Field<'A'|'B'|1>();    

    _instance!: DataType;
}

class WrongFieldFilter {    
    filter<T extends Field<unknown>>(field: T, value: T['_instance']): void {
        console.log(value);
    }
}
```

**Comment by kugacz** [comment]
Thank you both for the clarifications.

@RyanCavanaugh I've found your issue describing a similar problem https://github.com/Microsoft/TypeScript/issues/14829
Using one of the solutions from this topic I can achieve the validation I expect this way:
```ts
type NoInfer<T> = T extends infer S ? S : never;

class FieldFilter {    
    filter<DataType>(field: Field<DataType>, value: NoInfer<DataType>): void {
        console.log(value);
    }
}
```
I've created another option based on the above :
```ts
type FieldExactDataType<T> = T extends Field<infer U> ? U : never;

class FieldFilter {    
    filter<T extends Field<any>>(field: T, value: FieldExactDataType<T>): void {
        console.log(value);
    }
}
```
