### ISSUE TITLE
Consider parenthesized expressions with JSDoc to be a form of type assertions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5158]
To quote @weswigham on https://github.com/Microsoft/TypeScript/issues/4447#issuecomment-143099295:

> in [the] closure compiler you do inline casts with jsdoc comments like so:
> 
> ``` ts
> var x = /** @type {Foo.Bar} */ (y);
> ```

We should consider supporting this in Salsa.

**Comment by weswigham** [comment]
Also type assertions in the form:
```js
/** @type {Foo.Bar} */ var x = y;
```

and 
```js
/** @type {Foo.Bar} */
this._foo = undefined;
```

which I believe are also both recognized as type annotations by the closure compiler.

**Comment by DanielRosenwasser** [comment]
@rbuckton discuss which of you would like to take this on

**Comment by m1ck2** [comment]
@ikatyang fix(JavaScript): can you’ve  show me where to find this sub-menu please ;)
