### ISSUE TITLE
type | undefined not assignable to type regardless of null check from Record with noUncheckedIndexedAccess

### ISSUE THREAD

**Issue by DerHerrGammler** [microsoft/TypeScript#51582]
# Bug Report

### 🔎 Search Terms

- null check
- record
- noUncheckedIndexedAccess

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about noUncheckedIndexedAccess option and null check

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&target=7&jsx=0&module=1&ts=4.8.4#code/LAKAxg9gdgzgLgAgIYCcUC4ECUCmkUAmAPPCgJZQDmANAlAK4C2ARjigHwDaAuggLwIeoUADN6UMHDLRkBAgBEcIimSnQYACgJKYmXPmKkKNbHgiEScclVoMWbduwCUmAG4QyBBAG9QCfwgA8swAVnhwAHQA1jgAnpraIjBOESLmAKJIYAAWGhpwsQAOOJhGVC4I7p787D4A3H4BTWQiCFo6nAXFvACEAuKJFDgETj6NTRPIaBGF9DC5iTCdRTjcTuMTAL4bm04NINsgQA)

### 💻 Code

```ts

const arr: string[] = []

function addDefinitions(defs: Record<string, string>): void {
    Object.keys(defs).forEach((type: string): void => {;
        if (defs[type] != undefined) {
            arr.push(defs[type]); // ❌ ts error
        }
    });
}


```

### 🙁 Actual behavior

In my code i get a `Argument of type 'Definition | undefined' is not assignable to parameter of type 'Definition'.` error. But as you see i check the object value with `if (defs[type] != undefined)`. But at `this.addDefinition(type, defs[type]);` the error is thrown anyway.

The active option `noUncheckedIndexedAccess` will produces this error. But as you see there is a null check so that this error should not be thrown.

### 🙂 Expected behavior

Because of the null check this error should not be shown.

**Comment by RyanCavanaugh** [comment]
For performance/correctness reasons we don't narrow when the key is a variable (we can't tell if it's been mutated or not). This limitation was called out in the PR text: #39560. `noUncheckedIndexedAccess` is extremely conservative in this regard.

**Comment by fatcerberus** [comment]
Workaround: Assign `defs[type]` to a temp variable and narrow that.

**Comment by DerHerrGammler** [comment]
So in those cases best pratice is somethink like first assigning to a variable and checking the variable against null?  
Like this:
```typescript

const arr: string[] = []

function addDefinitions(defs: Record<string, string>): void {
    Object.keys(defs).forEach((type: string): void => {;
        const def: string | undefined = defs[type]
        if (def != undefined) {
            arr.push(def)
        }
    });
}

```

Or is there any better solution for this?

**Comment by DerHerrGammler** [comment]
I just found out, that i can use `Object.entries` like the following and there is no error thrown:  

```typescript
const arr: string[] = []

function addDefinitions(defs: Record<string, string>): void {
    Object.entries(defs).forEach(([, def]): void => {;
        arr.push(def)
    });
}
```

thanks you all for the quick help
