### ISSUE TITLE
TS2367 (no overlap) error even though when setting variable in e.g. setTimeout() scope

### ISSUE THREAD

**Issue by andsens** [microsoft/TypeScript#51586]
# Suggestion

[This code](https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsIwLbFRACgEoYBvAKAEgAbAU2RjFpAnQC4YByJkTmAHy6s+AXi49OAbnJUQ9ACqpstdAmQFiMEQD4yVSj1Zah6KVQC+AGhgBGAAxFplYAHc8DOPSgALAp2-IyAAObAD0obQAHsDYQXQAdFDo2JyOVKhwMASG6FoiYpzCJBSUlEkQIOgJ1OgA5n5FTubkzbj4xJJAA):
```
async function main() {
	let yesno: 'yes' | 'no' = 'yes';

	setTimeout(() => {
		yesno = 'no';
	}, 10);
	await fetch('http://example.com');
	if (yesno === 'no') {
		console.log('no');
	}
}
main();
```

will yield an error for `if (yesno === 'no') {` saying `This condition will always return 'false' since the types '"yes"' and '"no"' have no overlap.(2367)` even though `yesno` can in fact change.

## 🔍 Search Terms

"no overlap", "async", "2367"

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would love for TS to be able to detect that the variable might change.

**Comment by MartinJohns** [comment]
Another duplicate of #9998.

**Comment by andsens** [comment]
Ah apologies for the dupe, though "Trade-offs in Control Flow Analysis" was not really a something that would've pinged on my radar :laughing:  
Thank you for the solution!

**Comment by MartinJohns** [comment]
@andsens There's an entire issue template specifically for this case:
![image](https://user-images.githubusercontent.com/5269069/202704147-2efce4e8-cbc3-41e9-a9af-e32e7ec67093.png)

**Comment by andsens** [comment]
Oh wow. My eyes completely filtered out that template choice for some reason. Apologies for the time waster Martin. Have a great weekend :-)

**Comment by fatcerberus** [comment]
To be honest, it seems like when it comes to that issue template, it invariably goes one of two ways: 1) people with the problems it applies to overlook it, or 2) people use it for unrelated issues and wonder why their issue was automatically tagged as a duplicate 😝 

> I would love for TS to be able to detect that the variable might change.

Interestingly, your example is the inverse of most #9998 duplicates - most people do a type narrowing in the outer scope and then expect it to remain narrowed inside the callback.  I don't think both sides can be appeased.
