### ISSUE TITLE
class properties initialisation in constructor

### ISSUE THREAD

**Issue by gamertike** [microsoft/TypeScript#51598]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

class properties initialisation in constructor

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow to add types for properties inside the constructor instead of having to add the property types outside the constructor and then initialise the property values inside the constructor.

## 📃 Motivating Example

```ts
class Example {
    constructor(options: { name: string }) {
        /**
         * Some documentation 
         */
        public name: string = options.name;
    }
}
```

The `public` or `private` keyword would allow us to not need to add `this` at the start

## 💻 Use Cases

This could be used to slightly simplify code.

```ts
class Example {
    /**
     * Some documentation 
     */
    public name: string;

    constructor(options: { name: string }) {
        this.name = options.name;
    }
}
```

**Comment by RyanCavanaugh** [comment]
This would need to be a TC39 proposal since it's runtime syntax
