### ISSUE TITLE
Inference defaults to `string` instead of `never` when doing string interpolation inference

### ISSUE THREAD

**Issue by mhevery** [microsoft/TypeScript#51591]
# Bug Report

### 🔎 Search Terms

`infer`

### 🕗 Version & Regression Information

4.8.4

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[reproduction](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBiBLEwAmAlCAVxmAGVgBzAW2ADt4BeOAAwHoASAbwGcYoNaFAL7MA3AChQkWAmSoACgEMoimiX4AvXAWJlKNegB4AkgBFScUCVo5ucXv0EA+OE2YBtLmdJCAumPFJcGh4JBQ4UgAbQgoAaWBEbkN5AEEAFQAJFwZxODhUzMsQa1s4FKgVRENcvPQsbSIScmo6eAAffOVVYHUMLXxGvRajAQAzYCg4NKcamdq4AH4pmryALjhaYAA3CYkg6VC5KYBRUjSAfVTSUlYAKjhj8GAAYxh1gHJFd7b3gCN3uC3ViuCLROIJJLud6sL4AGjg73cv1873hiOeKN8TgkUhCsnCaVOFzQKWMABk7g8nq91psdpMAOqKbjrBwCCiA4FMKIxeKJQxQmHvLGiIA)

### 💻 Code

```ts
export type FixedRouteSegment = `/${string}`;
export type ParameterizedRouteSegment<IDS extends string> = `[${IDS}]`;

export type SlugKeys<PATH> =
  PATH extends Array<
    FixedRouteSegment | ParameterizedRouteSegment<infer T>
  >
    ? T
    : never;

export type TEST_PASS/* Expect: 'a'|'b' */ = SlugKeys<['/a', '[b]', '[c]']>;
export type TEST_FAIL/* Expect: never Was: string */ = SlugKeys<['/a']>;
```

### 🙁 Actual behavior

The inference engine incorrectly infers `string` type.

### 🙂 Expected behavior

I would expect that the resulting inference would be `unknown` as it does not match any of the possible answers. Instead the inference is `string`

**Comment by mhevery** [comment]
[workaround](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBiBLEwAmAlCAVxmAGVgBzAW2ADt4BeOAAwHoASAbwGcYoNaFAL7MA3AChQkWAmSoACgEMoimiX4AvXAWJlKNegB4AkgBFScUCVo5ucXv0EA+OE2YBtLmdJCAumPFJcGh4JBQ4UgAbQgoAaWBEbkN5AEEAFQAJFwZxODhUzMsQa1s4FKgVRENMbHwiEnJqOhgnXLy4AH44WmAAN2AoNryALnz0jKKSu3LKwyH2vKUVNQGMLTrdRoMYQwEAMwG4NJcAH3QsbXq9Jvp5vNaFha60u-bRnv6oCSDpULkjgCipDSAH1UqRSKwAFRwAHgYAAYxgowA5IoUScUQAjFFwKGsVwRaJxBJJdwo1jogA0cBR7ixvhRNLpCMZvicEikIVk4TSQNBaBSxgAMtDYfCke8+ocAOqKbijBwCCh4glMKIxeKJQzkyko9miIA)

```typescript
export type FixedRouteSegment = `/${string}`;
export type ParameterizedRouteSegment<IDS extends string> = `[${IDS}]`;

export type SlugKeys<PATH> =
  PATH extends Array<FixedRouteSegment>
    ? never
    : PATH extends Array<
        ParameterizedRouteSegment<infer T> | FixedRouteSegment
      >
        ? T
        : never;

export type TEST_PASS/* Expect: 'a'|'b' */ = SlugKeys<['/a', '[b]', '[c]']>;
export type TEST_FAIL/* Expect: never Was: string */ = SlugKeys<['/a']>;
```

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Inference collects zero candidates for `IDS`, so the constraint is satisfied by virtue of none of the inference candidates not-satisfying it, and the type parameter is instantiated with its default as a fallback.

Common question is "why not fail" -- zero-candidate inference is actually extremely common in practice and doesn't represent an error condition. No type violation has occurred.

**Comment by mhevery** [comment]
Thanks for letting me know. Bit surprising, but I will take your word for it. :-)
