### ISSUE TITLE
Constructor "undefined" when target ES2022 & decorator is used

### ISSUE THREAD

**Issue by GregOnNet** [microsoft/TypeScript#51604]
# Bug Report

The way how static fields are initialized seems to have changed in ES2022.
In previous module versions, it was possible to pass `constructor` of a class to a function that initializes a static field.
This still works in ES2022 as long the class has no decorator.
Once a decorator is applied, the constructor is `undefined`.

```ts
@decorate()
class A {
 static a = doSomething(A);
}

function doSomething(token: any) {
  console.log('TOKEN', token). 
   // ES2020 logs "TOKEN",  class A {} 
   // ES2022 logs "TOKEN",  undefined
}
```

### 🔎 Search Terms

- static
- constructor
- decorator

### 🕗 Version & Regression Information

- `4.8.4`
- It seems not to be related with the typescript version, but with the specified `target`

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=9&ts=4.8.4&useDefineForClassFields=true#code/PQKhCgAIUqYRgHSQJIDNIE8D2BXSAzgA4CmAxgJZqaQAuAhgE4DmJtAXJAKIDKATAAZBkbI278h8OgAsSkMtgB2BWo1xlaoyAHcKAGz2QARnL3ZmrACbI4kPsgCCaWiTHFyVTBUXM6TVhzignx8MnIKyqrqmmIUBJC4ipYkaN4k1nDA4OAAAskKjPQuAOoUtNIAYvQaopgAFACU4GR69ATxDpAA3lAqRRRkkPSQALyQltg82AC2bNLezHUODQDc4AC+2eBoiRoUSuPkokUkpeVVNYz1Dd1QkIxsuIyKkHUMLGyc9IqYNyMAfLdIMD7o9nn4PrQ1sDNpttrtaPsXhMprNygs3tgANYkRRfH43HrAiIEbB6EiIMyLADkABUAPIAaS4ADlqQAaOjY3FNdZAA

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
/**
 * 
 * 1. If you specify target: ES2020 or ES2021 the constructor will be logged. 
 * 2. After specifying target: ES2022 the constructor is undefined.
 */

@decorateWithFactory()
class A {
 static a = doSomething(A);
}


function decorateWithFactory() {
  return (target: any) => {
    return target;
  }
}

function doSomething(token: any) {
  console.log('TOKEN', token)
}
```

### 🙁 Actual behavior

The Library https://github.com/co-IT/ngrx-ducks makes use of extracting information from a constructor.
The function `useActions` does not work any more with `ES2022`.

https://github.com/co-IT/ngrx-ducks/issues/85

### 🙂 Expected behavior

Calling a function to initialize a static field by using its constructor should work.

Please let me know if I can provide further information. 🙏
Thanks for your help.

**Comment by fatcerberus** [comment]
More or less a duplicate of https://github.com/microsoft/TypeScript/issues/51570

**Comment by GregOnNet** [comment]
Correct, thanks a lot.
