### ISSUE TITLE
Contravariant error when using generic + interface + keyof

### ISSUE THREAD

**Issue by k8w** [microsoft/TypeScript#51608]
# Bug Report

### 🔎 Search Terms
Contravariant generic interface keyof

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _Contravariant_
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAglC8UDeUDaBrCIBcUDOwATgJYB2A5gLq4EkVQC+A3AFCiSwBCCyUAhjSJlyAGigAjQXXKNWbcNADKAewC2EAIwAeACoA+HphDKAZlB1z2StRABMug4iQsoUAG58ANgFcIuI6bmLMwsLAD0YeYAFsR4UADuyoToeACELJ4QwPg2GjCpuCrq2jB6rJnZeLkwnAVQRZpaNWUsVcVwiG2aNXIRUADqUSBQwDFxpMrZiclQAPwZWTnqtvmFNval5YtdK7Vry02cLTsdS3Y9oX06YwlJKeGRilHK3p4AJqQA5Nmj0FZQgS6AGYYGFgTUJH8otA8Hx1AliKMziswesavM+pxvFMhiNoVBCBA8K9srEoG9iCYTBBCaRgPMKmcQXUUB4fH4oAEzHAQozwXtkGzfP4sIEaiFwTx+UwgA)

### 💻 Code

```ts
type A = { [key: string]: string };
type AB = { a: string, b: string };

type Some1<T> = keyof T;

type Some2<T> = {
  value: keyof T
};

// This works!
let some1A!: Some1<A>;
let some1AB!: Some1<AB>;
some1A = some1AB;

// Why this not work ?
let some2A!: Some2<A>;
let some2AB!: Some2<AB>;
some2A = some2AB;

// This works
// Shouldn't the type of some3A/some3AB be the same with some2A/some2AB?
// But why the result is different?
let some3A!: { value: keyof A };
let some3AB!: {value: keyof AB};
some3A = some3AB;
```

### 🙁 Actual behavior

The result of the compilation depends on whether generic type is used or not

### 🙂 Expected behavior

The result of the compilation is the same for `Some1` and `Some2`

**Comment by MartinJohns** [comment]
Because that would be unsound. The type of `some2A.value` is `string | undefined`, so it's fine to assign an arbitrary string to it. But the object is a `Some2<A>`, where only the keys `"a"` and `"b"` are valid.

```typescript
some2A.value = 'some key'
console.log(some2AB.value) // Type is "a" | "b", but value is "some key".
```

**Comment by k8w** [comment]
@MartinJohns But why `Some1` works? Shouldn't they have the same result?

**Comment by MartinJohns** [comment]
Why would `Some1` be a problem? You're not modifying objects, just the variable. Changing the value of a variable does not change the value of other variables.

**Comment by k8w** [comment]
As what you said, this should get a compile error, but it doesn't.

```ts
let some2A: { value: string | undefined };
let some2AB: { value: 'a' | 'b' } = { value: 'a' };
some2A = some2AB;
```

Just because generic type is not used, it lead to the result be different.
As `T` is known already, shouldn't the result be the same?

**Comment by fatcerberus** [comment]
I believe this is a case where variance detection measures `Some2` as contravariant (due to the use of `keyof T`) and rejects the assignment where a normal structural check would succeed.  There’s a similar issue around here somewhere, I’m almost positive.

**Comment by RyanCavanaugh** [comment]
@fatcerberus is correct. The weirdness here comes because index signatures instantiated with string break the relational symmetry (since an object with a string index signature doesn't actually have every key that could possibly exist).
