### ISSUE TITLE
Organize imports doesn't keep imports in a vertical column

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#51615]
After reformatting this repo's imports as vertical sorted columns for better merge conflict handling, we noticed that running organize imports produced an odd result. Given this test:

```ts
/// <reference path="fourslash.ts" />

////import {
////    Type1,
////    Type2,
////    func4,
////    Type3,
////    Type4,
////    Type5,
////    Type7,
////    Type8,
////    Type9,
////    func1,
////    func2,
////    Type6,
////    func3,
////    func5,
////    func6,
////    func7,
////    func8,
////    func9,
////} from "foo";
////interface Use extends Type1, Type2, Type3, Type4, Type5, Type6, Type7, Type8, Type9 {}
////console.log(func1, func2, func3, func4, func5, func6, func7, func8, func9);

verify.organizeImports(
`import {
    func1,
    func2,
    func3,
    func4,
    func5,
    func6,
    func7,
    func8,
    func9,
    Type1,
    Type2,
    Type3,
    Type4,
    Type5,
    Type6,
    Type7,
    Type8,
    Type9,
} from "foo";
interface Use extends Type1, Type2, Type3, Type4, Type5, Type6, Type7, Type8, Type9 {}
console.log(func1, func2, func3, func4, func5, func6, func7, func8, func9);`
);
```

Organize imports gives:

```ts
import {
    func1,
    func2, func3, func4, func5,
    func6,
    func7,
    func8,
    func9, Type1,
    Type2, Type3,
    Type4,
    Type5, Type6, Type7,
    Type8,
    Type9
} from "foo";
interface Use extends Type1, Type2, Type3, Type4, Type5, Type6, Type7, Type8, Type9 {}
console.log(func1, func2, func3, func4, func5, func6, func7, func8, func9)
```

**Comment by jakebailey** [comment]
I suspect this to be something related to #51301, but for reorderings.

**Comment by andrewbranch** [comment]
Thanks for the fourslash test!

> there doesn’t seem to be any rhyme or reason for how it decides to add a line break or not.

The pattern of line breaks spells out “send help, formatting-aware code transforms are hard” in Morse code

**Comment by andrewbranch** [comment]
For the curious, it’s preserving the line break between elements that are consecutive both before and after the sorting.

**Comment by fatcerberus** [comment]
Ah, I was confused because I assumed the string passed to `verify.organizeImports` was the *input* string, not the expected output.  Everything was already in the expected order there so it seemed like it just randomly deleted some line breaks.  I now realize the input string is the fourslash comments and feel dumb.
