### ISSUE TITLE
incorrect handling of promise resolve vs return

### ISSUE THREAD

**Issue by vladmandic** [microsoft/TypeScript#51625]
# Bug Report

### 🔎 Search Terms

Looked at top-100 hits with keyword `resolve`

### 🕗 Version & Regression Information

Reported for 4.9, but not a new issue, don't know if TypeScript ever handled this correctly.  
I've tested in playground using pretty much all versions 3.3 - 4.9.
Nothing similar is noticeable in FAQ.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `resolve`

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsI2QUxMgCgEoYBvAKBhgCcdkFqsIcB3GABWvQFtUQcCBWiHQAbAG44SAXgB8ZSlRii62PMgBqwaqmAAjFQC4YEBNz05qMAD4wkAExxxUzewG5FVVHBgEAhLj4Wjr6KiTCYpIEyNQIUm4wAPSJ2AAWfDR4kXgwqNzcOPa6uKJgMKAw4tq6Bji5ICboyDCOzq6eSSnIYAAOeFA6Pc1QmGimOSyoyKkwUKk4UADWDcAQ9iY4AB7Noi51wgiiyA0uMJZcVsBHqegIAOYzUCrapWmWdRkQ6GfUFy1x2G+OBeZS2Uxgk2mMAABhEJAIiNCOslsCACABGAAcAAYACyYkjndBWADkgU01VCOBJ9RgPXQIBAqAMZRJDice3sJI63l85OCNRUMHk2JIIwgIhUADpROg7tF1AKqUQPEpOo02CpjjB+HUbmxwalVvYVA1aPRGLMrqIQDyfP5+ZTauE6AwIKqlCivj8-sBmtbykdbg9MhasFAA-NaBCKiNuD0tThXkhmFA8CBtGA7XzFU6hSKxZhJTgZXKFUE8-FFABfFXkatAA)

### 💻 Code

```ts
async function test() {
  return new Promise((resolve) => {
    let testVariable: number | undefined;
    if (!testVariable) resolve(true); // this resolves immediately as variable is not defined
    // typescript continues with checks and next line results in error although clearly there is no error due to early exit with `resolve()`
    // ts(18048) error 'testVariable' is possibly 'undefined'
    if (testVariable > 0) console.log(testVariable);
    // now lets see how it handles return calls
    if (!testVariable) return;
    // no error at all altough return call here was completely unnecessary
    if (testVariable > 0) console.log(testVariable);
  });
}
```

### 🙁 Actual behavior

TypeScript does not stop code checks after calls to `resolve` inside a promise

### 🙂 Expected behavior

TypeScript should treat resolve inside `promise` the same way it treats `return` inside a normal function

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/51624#issuecomment-1323916900
