### ISSUE TITLE
Props assigned to a generic don't retain their logic

### ISSUE THREAD

**Issue by Dan503** [microsoft/TypeScript#51629]
# Bug Report

### 🔎 Search Terms

props properties object generic logic type checking

### 🕗 Version & Regression Information

typescript version 4.9.3

- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQHEoQGoIDYCuUACjAPYAOAzgDwCSVAyhDOAOapQAe0YAJlVQAjMmTxQEYAHyoA3sFSLUAemWoQTFu1QVyFdYKRkwYKEmh9UEMlYAWaBs1ZgObKKdZIFSjU-YAuVEctF29FKhC2XEIoQIjnNjDUMAIAWyFYaKJAlPTYYABfYGA4AjBzEGNUNxx8InpNBM4edwFhUXFJKQAKeSUDPxcAGiT49iyoEf7cjJgJkYLAzFqY0kpaYISpAEpAze1uXjaWIlQAflQxl1QctNm5JNVUAEJn1ABRACVPgHlPl+ejzUABUAJ4UNAAciuHAAPsk7rBIQZkmQIKgEFQqCA2GAEEJxFYbBBwVD9tdDq1BCc0BcYTcEXkYJCAHRA1BgiGoaGRZEaVHozHY3H4wnWKyk7nkjiU-jUmCnOmRBkzJFs-owLAEGBgAbKpUJCYqxFzOpQQrFIxgCKXSLRVAAXmqWAmvT1CUCNKGtsNZsCkOMUEh3tVppigQAjKgCttgFabbl7U6aq7ZO6AqhEHgqJMfeM-dzA8HGbMJpHo7G48YqGIoCy8GQ2L1Rnb8N6ngAiQMdpKJ-AqNQRwqx1BAA)

### 💻 Code sample

```ts

interface GetValueProps<IsString extends boolean> {
    // isString prop is connected to the IsString generic
    isString: IsString
    stringValue: string
    numberValue: number
}

function getValue<IsString extends boolean>({
    isString,
    stringValue,
    numberValue,
}: GetValueProps<IsString>): IsString extends true ? string : number {
    // !! ERROR !!
    // Type 'string | number' is not assignable to type 'IsString extends true ? string : number'.
    // Type 'string' is not assignable to type 'IsString extends true ? string : number'.
    return isString ? stringValue : numberValue
}
 ```

### 🙁 Actual behavior

It doesn't recognize that the `isString` value is a variable representation of the `IsString` generic so `isString ? stringValue : numberValue` is not recognized as satisfying the `IsString extends true ? string : number` return type even though it should.

### 🙂 Expected behavior

The `IsString` type is connected directly to the `isString` prop so for type calculation purposes, `isString` should be treated as `IsString` when analyzing types for type checking purposes.

**Comment by MartinJohns** [comment]
Within your function TypeScript has **no** idea what type `IsString` is, because it's supplier to the function from the caller, so the compiler can't possibly know what the return type is.

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/33912
