### ISSUE TITLE
Please confirm the equivalent MSBuild tag for --jsx

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/TypeScript#5162]
This Wiki article is missing the MSBuild tag for `--jsx`:

https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects

I can add it if you're willing to just confirm it.  Thanks!  (Note I'm only asking due to the case-sensitive nature of it)

**Comment by DanielRosenwasser** [comment]
@paulvanbrenk

**Comment by paulvanbrenk** [comment]
The MSBuild element to use is `<TypeScriptJSXEmit>` with `React`, or `Preserve` as the value.

**Comment by nycdotnet** [comment]
Thanks!  I'll issue a PR on the Wiki.

**Comment by mhegazy** [comment]
the source of truth is your targets file at `C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets`..
look for the sections setting `TypeScriptBuildConfigurations`
