### ISSUE TITLE
Check for existence of a type in a set of types

### ISSUE THREAD

**Issue by stefc** [microsoft/TypeScript#51637]
# Suggestion

I want to know how if in a set of types like the following two the type ```null``` exists. 

```
type TransactionCategory = "B2B"| "SEZWP" | "SEZWOP" | "EXPWP" | "EXPWOP" | "DEXP" | null
type DutyStatus = "WPOD" | "WOPOD" 
```

```
console.log( null in TransactionCategory).  //  ==> true
console.log( null in DutyStatus) // === false 
```
  
## 🔍 Search Terms

type-system 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [?] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases

For the UI I want to use such types for an SELECT control to determine if the set contains the option of selecting ```null``` or not. For that case I use Generics to overgive the type.

**Comment by fatcerberus** [comment]
You can't do anything at runtime because the types are completely erased by the compiler, but you can check this in a conditional type at compile-time: `null extends Type ? true : false` ("is `null` assignable to this type?")
