### ISSUE TITLE
Possible to set all `node.parent` properties with `ts.factory`

### ISSUE THREAD

**Issue by PupilTong** [microsoft/TypeScript#51646]
# Suggestion

## 🔍 Search Terms

parent, ts.factory, factory, transform

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Consider the following code:
```javascript
/// create a statement
/// const example = 'this is an example'
factory.createVariableStatement(
  undefined,
  factory.createVariableDeclarationList(
    [factory.createVariableDeclaration(
      factory.createIdentifier("example"),
      undefined,
      undefined,
      factory.createStringLiteral("this is an example")
    )],
    ts.NodeFlags.Const
  )
)
```

However the `parent` properties of every ts.node is undefined, which is really confusing.

## 💻 Use Cases

I'm trying to create a ts2ts transformer. 
 However I'm stuck by the sourceMap issues.
In ts.transform function, I create some new ts.node and append them to a sourceFile.

However the node.pos and node.end properties are keeping -1.

I guess the sourceFile should be emitted to assign some values to those properties, but the created nodes has no parent, which caused an exception in typescript

Thank you sooooo much!

**Comment by RyanCavanaugh** [comment]
`forEachChild` is exposed, so writing this function yourself is very straightforward.

**Comment by ahungrynoob** [comment]
we can check the scope without parent like this: https://github.com/ahungrynoob/jotai-ts-transformer/blob/master/src/react-refresh-transformer.ts#L134

**Comment by tmcw** [comment]
forEachChild exists, but the node.parent property also exists. If you move a node from one place to another in a transformer, the parent reference becomes incorrect and there's nothing you can do. And downstream transformations don't know whether to rely on parent.

It'd be great if there was either a way to set the parent, or if ts.tranformer updated the parent, or the parent property didn't exist and there were simple ergonomic ways to work without relying on it. Right now, a lot of transformer examples and TypeScript compiler examples, [including the TypeScript wiki's examples](https://github.com/microsoft/TypeScript-wiki/blob/main/Using-the-Compiler-API.md#using-the-type-checker), which are as close to official docs as we're going to get, use the `node.parent` property. If it's not reliable and updatable, they probably shouldn't.

**Comment by iostreamer-X** [comment]
Hi @RyanCavanaugh!

It'd be great if you could shed some light here.

Thanks
