### ISSUE TITLE
[4.9 breaking change] hostOrText.readFile is not a function 

### ISSUE THREAD

**Issue by jeremy-coleman** [microsoft/TypeScript#51644]
# Bug Report

### 🔎 Search Terms

hostOrText
hostOrText.readFile

### 🕗 Version & Regression Information

When did you start seeing this bug occur?

today, after upgrading a project

I tried both 4.9.3 and next versions, both have the error.

- This is a crash
- This changed between versions <= 4.8x and 4.9.3

### 💻 Code

this is the source of the calling function https://github.com/microsoft/TypeScript/blob/main/src/compiler/utilities.ts#L6418

my code doesn't call hostOrText.readFile . I'm using a modified copy of rollup plugin typescript v2. It has worked for years, without change. I can copy/paste it here if wanted, but i think it'd be more clutter rather than providing anything useful.

for a little context, here is the project layout. its super simple. the rollup.bundles.js is just configured to export an array of rollup configs using the local typescript plugin. 
![image](https://user-images.githubusercontent.com/25135855/204063050-14faf774-511d-49ca-89bc-9370f653bf12.png)

Just Brainstorming: Possibly related to the new file watcher? I've written several cli tools and have experienced similar problems where chokidar would swallow errors but fs watch recursive would throw and exit. Another thought is maybe there is some change in logic for looking up the closest tsconfig file in a monorepo.

### 🙁 Actual behavior

error output when running rollup via an npm script

```
[rollups] [!] (plugin typescript) TypeError: hostOrText.readFile is not a function
[rollups] TypeError: hostOrText.readFile is not a function
[rollups]     at readJsonOrUndefined (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:19519:74)
[rollups]     at Object.readJson (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:19528:16)
[rollups]     at getPackageJsonInfo (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:44767:41)
[rollups]     at loadModuleFromSpecificNodeModulesDirectory (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:45316:27)
[rollups]     at loadModuleFromImmediateNodeModulesDirectory (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:45296:58)
[rollups]     at C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:45286:39
[rollups]     at Object.forEachAncestorDirectory (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:8224:26)
[rollups]     at loadModuleFromNearestNodeModulesDirectoryWorker (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:45280:19)
[rollups]     at loadModuleFromNearestNodeModulesDirectory (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:45272:16)
[rollups]     at tryResolve (C:\Users\jerem\Desktop\App\omnify-monorepo-starterkit\node_modules\typescript\lib\typescript.js:44358:34)
```

### 🙂 Expected behavior

output after downgrading to typescript 4.8.x or any other version
```
[rollups]
[rollups] rollup v3.4.0
[rollups] bundles packages\common\src\index.ts → packages/common/lib/index.js...
[rollups] created packages/common/lib/index.js in 114ms
```

**Comment by sheetalkamat** [comment]
can you please share project where i can repro this

**Comment by sheetalkamat** [comment]
Sample project i created seems to work correctly

```ts
// /src/math/index.ts
export function add(x: number, y: number): number {
    return x + y;
  }
  
  export function substract(x: number, y: number): number {
    return x - y;
  }
```

```ts
// /src/app.ts
import { add, substract } from './math';

const x = 20;
const y = 10;

console.log(`${x} + ${y} = ${add(x, y)}`)
console.log(`${x} - ${y} = ${substract(x, y)}`);
```

```jsonc
// /tsconfig.json
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",                     
    "outDir": "output",
    "rootDir": "./",
    "composite": true
  }
  ,
  "include": ["./src/**/*.ts"]
}
```


```js
// /rollup.config.js
import typescript from 'rollup-plugin-typescript2';

export default {
  input: 'src/app.ts',
  output: {
    dir: 'output',
    format: 'cjs',
  },
  plugins: [typescript()],
};
```

```jsonc
// /package.json
{
  "name": "typescript-rollup",
  "version": "1.0.0",
  "description": "",
  "main": "output/app.js",
  "type": "module",
  "scripts": {
    "build": " rollup -c rollup.config.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "rimraf": "^3.0.2",
    "rollup": "^3.5.1",
    "rollup-plugin-typescript2": "^0.34.1",
    "tslib": "^2.4.1",
    "typescript": "^4.9.3"
  }
}

```

Ran
```
npm run build
```

**Comment by jeremy-coleman** [comment]
@sheetalkamat 

https://github.com/jeremy-coleman/ts493-issue51644

**Comment by sheetalkamat** [comment]
Looked into this and it seems like issue with the plugin. It is passing host that has missing `readFile` on `ModuleResolutionHost`. It is required method.
![image](https://user-images.githubusercontent.com/8052792/205415240-2a721419-4707-4ee8-896e-404237e221bd.png)

```
   var result = tsRuntime.nodeModuleNameResolver(
        importee,
        containingFile,
        compilerOptions,
        resolveHost
      );
```

**Comment by jeremy-coleman** [comment]
closed over the weekend - harsh.

One last question @sheetalkamat

Was this a planned breaking change in the resolveHost? Like I mentioned in the post, this has worked for years.

**Comment by sheetalkamat** [comment]
This is not breaking change per say... The API always used `readFile` as non optional property but had try and catch statement that caught all the errors from reading file (unintentionally) while it was intending to catch json parsing errors. With the recent change we use our own json parsing which is more error tolerant and doesnt throw so now its actually error that was suppressed before.

**Comment by jeremy-coleman** [comment]
thank you!

**Comment by nicolaschambrier** [comment]
> btw, for any future readers, a simple noop for readFile in the resolve host is all that is required.

@jeremy-coleman thanks for the heads up, however I don't get where we're supposed to add this? I didn't correctly understand the root-cause here but I face the same issue when trying to add a custom `project.json` in a folder

**Comment by FishOrBear** [comment]
```
readFile("node_modules\\rollup-plugin-typescript\\dist\\rollup-plugin-typescript.cjs.js", "utf-8", (err, str) =>
{
    if (str.includes("readFile: () => { }")) return;
    str = str.replaceAll("var resolveHost = {", "var resolveHost = {\r\nreadFile: () => { },\r\n");
    writeFile("node_modules\\rollup-plugin-typescript\\dist\\rollup-plugin-typescript.cjs.js", str, err =>
    {
        if (err)
            console.log("hack ok");
        else
            console.log("hack error");
    });
});

readFile("node_modules\\rollup-plugin-typescript\\dist\\rollup-plugin-typescript.es.js", "utf-8", (err, str) =>
{
    if (str.includes("readFile: () => { }")) return;
    str = str.replaceAll("var resolveHost = {", "var resolveHost = {\r\nreadFile: () => { },\r\n");
    writeFile("node_modules\\rollup-plugin-typescript\\dist\\rollup-plugin-typescript.es.js", str, err =>
    {
        if (err)
            console.log("hack ok");
        else
            console.log("hack error");
    });
});
```

Modify the code of the plugin @nicolaschambrier
