### ISSUE TITLE
Partial<T> in Generic Class is not working properly

### ISSUE THREAD

**Issue by gearintellix** [microsoft/TypeScript#51645]
# Bug Report

### 🔎 Search Terms

Partial Generic Class

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (latest version v4.8.4)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mwEsD2A7AhgGwCJuGgogB7ABOaUAPACpQTEQoAmAzlAN4C+ANFPrfU1acoAXnYcAfKKgAFNCUSZqUAGS8JAbgBQWhCmAQSAMzQBjaFQjNgOPOy0BII0iQAuKNZJ6A5tocAjeXcUAFcAW39DbQ4dIxCUU0RUKANrADF4xOQUCj46A0FxCQAKRlw0dzgk9GxyolI0aisbcp58CQBKdwA3JARGewdTVGYkDAgAOgwkb1Lyjq0YrQB6ZagAdyQSAGtmLVTgDITq4rZHZzcoACIDq8WFrVMMNGZWS2tc-gKWIsHhlE8IUSW2KHUGDlWUBMCHGjEcDmAAAsEMwJgcjllUABJAH9CAAYWer1O8KcLncN2adwcDg4C1pOgRzQx1RxzDxhJezDmeEq8GymFsBGIZCa1iFbU6PT6AzONP+o3GUxmPLQ9JiSwVwBSzRg-gAVtIUBB1lB3sBQdoVmtNjs9gc9fq0czMqzcYwCUTuXLAiR3ABGLj3LRAA)

### 💻 Code

```ts
type OptionalDataExtra <T extends {}, E extends {} = {}> = Partial<T & E>;

interface TestData {
	foo: string;
	bar: number;
}

function testFunction<E extends {}>(data: OptionalDataExtra<TestData, E>): void {
	console.log(data)
}

// works
testFunction({
	foo: "test"
})

class Test<E extends {}> {
	constructor() {
		// doesn't work
		this.testFunctionInsideClass({
			foo: "test"
		})
	}

	testFunctionInsideClass(data: OptionalDataExtra<TestData, E>): void {
		console.log(data)
	}
}

const testObj = new Test();

// works
testObj.testFunctionInsideClass({
	bar: 1,
})
```

### 🙁 Actual behavior

This case Partial of **Generic Object** combined with **Known Object** properties is not working properly even though the **Generic Object** properties is not actually used
It's only happen while used inside generic class

### 🙂 Expected behavior

Since Partial is make object properties optional, it should works fine even though the generic object properties not visible yet but, in the end of the day the additional generic properties is optional

**Comment by jcalz** [comment]
See [Why can't I return a generic `T` to satisfy a `Partial<T>`?](https://stackoverflow.com/questions/46980763/why-cant-i-return-a-generic-t-to-satisfy-a-partialt).  The caller of the construct signature can specify `E` to be a type with a `foo` property narrower than `string`, so the compiler is technically correct to complain that `{foo: "test"}` might not be assignable to `'Partial<TestData & E>'`:

```ts
const n = new Test<{ foo: "bar" }>();
n.testFunctionInsideClass({ foo: "test" });
//Type '"test"' is not assignable to type '"bar"'.(2322)
```
[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mwEsD2A7AhgGwCJuGgogB7ABOaAPACpQTEQoAmAzlAN4C+ANFPjXYyw5QAvG3YA+EVAAKaEokxUoAMh7iA3AChNCFMAgkAZmgDG0ShCbAceNpoCQhpEgBcUKyV0BzLfYBGcm4oAK4Atn4GWuzahsEoJoioUPpWAGJxCcgo5Ly0+gJi4gAUDLhobnCJ6NhlRKQUFlY2aNz44gCUbgBuSAgMdvYmqExIGBAAdBhIXiVl7ZrRmgD0S1AA7kgkANZMminA6fFVRawOTq5QAET7lwvzmiYYaEwsjcA5fPnMhQNDKB7BBKbIrtAb2FZQYwIMYMBz2YAACwQTHG+0OmVQAEl-n0IABhJ4vE5wxzONzXSzAW72ezsea07TwynoqrYpi4gnPJizPAVeBZTDNOpkKiU5qtDrdXr9U40v4jMaTaY8tD06KLeXAZKUmB+ABWUhQEDWUDeIK0y1WG22u32ur1qOZGVZOIY+MJ3NlARIbgAjJw7toHsMtShDcbTZTyKxIWSrt7LlAJObNChHWlnVk2RyPSdYxcKVZE3StCtKOBoAByQtUytQZFQFBILVchBedB+MbJJDJCtQasJyvjIoAJgAzCOR-MgA)

**Comment by gearintellix** [comment]
@jcalz I see that make sense now
But, I think by reordering object combination logically should be solving the problem isn't it?

```ts
// old
Partial<T & E>

// new
Partial<E & T>
```

The `T` properties will override the `E` properties when conflict happen

**Comment by jcalz** [comment]
No, intersections of non-functions are not order-dependent.

**Comment by fatcerberus** [comment]
Yeah, that’s not how intersections work.  `T & E` means a value which is assignable to both types, neither type “overwrites” the other, they just merge.  e.g. `{ x: string } & { x: number }` becomes `{ x: never }`

**Comment by gearintellix** [comment]
i see thank for the explanation
