### ISSUE TITLE
Properly type `.constructor` for classes

### ISSUE THREAD

**Issue by hasezoey** [microsoft/TypeScript#51647]
# lib Update Request

## Configuration Check

My compilation *target* is `es2019` and my *lib* is `esnext`.

## Missing / Incorrect Definition

`.constructor` on class instances should return the proper `typeof Class` type instead of `Object.constructor: Function`

## Sample Code

```ts
class Test {}

const instance = new Test();
instance.constructor; // constructor should have the type "typeof Test"
console.log(instance.constructor === Test);
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor

---

i would need this as a opposite of `InstanceType<typeof Class>`, for example `type TypeofClass<T extends { constructor: new (...args: any[]) => any }> = T extends { constructor: infer S } ? S : never;`

**Comment by MartinJohns** [comment]
Duplicate of #32452.

**Comment by hasezoey** [comment]
> Duplicate of #32452.

weird, i tried searching for that, but didnt find it - though granted i did not search through all 14 (or with some terms more) pages

**Comment by hasezoey** [comment]
Duplicate of #https://github.com/microsoft/TypeScript/issues/32452

**Comment by MartinJohns** [comment]
I used this search term: `constructor type in:title`
