### ISSUE TITLE
Formatter does not treat destructured imports

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#5164]
Imagine an import like this:

```
import { IWorkbenchEditorService }  from 'vs/workbench/services/editor/common/editorService';
```

Format, I would love if it ends up to be 

```
import {IWorkbenchEditorService}  from 'vs/workbench/services/editor/common/editorService';
```

Or whatever you guys think should be the formatting of destructured imports.

**Comment by mhegazy** [comment]
I have seen users have strong opinions on weather this should have spaces or not. so looks like this can be a new option.

//CC: @SaschaNaz

**Comment by SaschaNaz** [comment]
Unmerged #4609 will format the code but with spaces. A new option for this will be good but maybe after #4757.
