### ISSUE TITLE
TS cannot find type (type is unknown) for extension of Map class

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#51655]
# Suggestion

Love TS! Here is a bit where type inferences seems to be lacking.

Here is the raw code:

```typescript
export class DESMap<K,V> extends Map<K,V> {

  constructor() {
    super();
  }

  toJSON(){
    return Array.from(Object.fromEntries(this)).map((v) => {
      return [v[0], v.value];
    });
  }

}
```

Here is the lack of inference:

<img width="606" alt="Screen Shot 2022-11-27 at 2 48 13 PM" src="https://user-images.githubusercontent.com/11139560/204158988-d5814910-9975-43ef-a762-b55de7b2548b.png">

Seems like just an improvement could be made here.

**Comment by ORESoftware** [comment]
if it's not clear, the type of `v` is unknown

**Comment by fatcerberus** [comment]
This code doesn't actually work:
```ts
const map = new DESMap<string, string>();
map.set("foo", "bar");
console.log(Object.fromEntries(map));  // prints { "foo": "bar" }
console.log(map.toJSON());  // prints []
```
