### ISSUE TITLE
Async function return type issue

### ISSUE THREAD

**Issue by jamiewinder** [Microsoft/TypeScript#5165]
There appears to be a typing bug with the return values from async functions, perhaps limited to tuples. Examples:

```javascript
// Works!
function test(): [boolean, number] {
    return [true, 1];
}

// Works!
function test2(): Promise<[boolean, number]> {
    return Promise.resolve([true, 1]);
}

// Doesn't work
async function test3(): Promise<[boolean, number]> {
    return [true, 1]; // Error here!
}
```

The error is:
> Type '(boolean | number)[]' is not assignable to type '[boolean, number]'.

**Comment by mhegazy** [comment]
we need to contextually type the return statement with the promise type in async functions, this way we get the tuple inferred correctelly
