### ISSUE TITLE
 Generic ignores constraints inside a class

### ISSUE THREAD

**Issue by shaharkazaz** [microsoft/TypeScript#51652]
# Bug Report

### 🔎 Search Terms

Generic ignores constraints inside a class
Generic inside class

### 🕗 Version & Regression Information

This is the behavior in every version I tried (latest version v4.8.4)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/MYGwhgzhAEDyBGECmAnAbmeIkB4AqAfNAN4CwAUNNBiAK5ICEAXNHgNwUC+FFSAHgAcA9igAu0AGa0AdsFEBLIdOgATeWICeAYQAWSYAGt8eDQKQAaVtAC8rE2ej9RSaSpgAlfSJU4w0jZZ+GkQA-NCiKPTQLBJgIMgEABQUVBBCtCjASCwIyOiY2MamSATmFACULHgkKVTQKEiiGcoAjNCQ7f5cPORqmrr6BonQ0kgA7nCIqBhYuMSSQkIsbZxJ5eU9-MJi7YgRYHLQoJAwAEKQSADKWdJgKIoAsn5gAOaoOACi0gqiGo58zlcMHm8hULAgEXk0he0FWNUodSh8lEiXK8LqdT6vwGhmSCIxVFGE1y0wKuC+P2CqMstQxG3xsK4QA)

### 💻 Code

```ts
class Observable<T> {
  value!: T;
}

export function dirtyCheck<TType, T = TType extends Record<any, any> ? true : false>(
  source: Observable<TType>,
): T {
    return 1 as any
}

dirtyCheck( new Observable<{ foo: 1 }>()) // return value is true

export abstract class BaseScenarioManager<Entity extends { id: string }> {
    init() {
      dirtyCheck(new Observable<Entity>()) // return value is undetermined
    }
}
```

### 🙁 Actual behavior

When calling `dirtyCheck` outside a class everything is working as expected, when I call it inside a class using a constrained generic, the return type is undetermined.
The call for the `dirtyCheck` function inside of the class should return `true` since the `Entity` generic has a constraint that it is extending an object and therefore should return `true` according to the `dirtyCheck` type signature.

### 🙂 Expected behavior

Resolve the type considering the generic and its constraints.

**Comment by MartinJohns** [comment]
See #51629 and many many others.
