### ISSUE TITLE
`delete()` method missing from FontFaceSet interface

### ISSUE THREAD

**Issue by frank-weindel** [microsoft/TypeScript#51668]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `["ES2018", "DOM"]`.

## Missing / Incorrect Definition

The `delete()` method of the FontFaceSet interface is missing.

It has been available in Chrome since v35, Edge since v79, FireFox since v41, and Safari since v10.

## Sample Code

```ts
const font = new FontFace("MyFont", "url(myFont.woff2)");
document.fonts.delete(font);
```

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/delete

**Comment by MartinJohns** [comment]
See #51185. You need to include `dom.iterable`
