### ISSUE TITLE
Overloading - inherit types

### ISSUE THREAD

**Issue by gamertike** [microsoft/TypeScript#51673]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

Overloading, inherit, types, parameter types, return type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

when declaring functions with overrides make the types inherit from the override declarations

## 📃 Motivating Example

```ts
function add(a: number, b: number): number;
function add(a: string, b: string): string;
function add(a/* : number | string */, b/* : number | string */) /* : number | string */ {
	return a + b;
}
```

## 💻 Use Cases

This would be better because then the default types wouldnt be `any` on the main declaration.

**Comment by jcalz** [comment]
Looks like #25352 to me
