### ISSUE TITLE
Type narrowing regression with switch + for in TypeScript 4.9

### ISSUE THREAD

**Issue by mtreder** [microsoft/TypeScript#51688]
# Bug Report

It is possible to generate a `"Variable 'X' is used before being assigned."` error on TypeScript 4.9 where it previously did not in TypeScript 4.8.  This seems to be when we have combination of `switch` statements and `for` loop.

### 🔎 Search Terms

switch
for
type check

### 🕗 Version & Regression Information

- This changed between versions 4.8.4 and 4.9.3
- This continues to error with nightly.

### ⏯ Playground Link

[TypeScript 4.8.4 Playground Example](https://www.typescriptlang.org/play?ts=4.8.4#code/GYVwdgxgLglg9mABKSsEEEAUBKAXIgInQMQB9CAhEgbwCgBIAJwFMoRGkiCBuWgX1q0U0eEmFowFTAGtmAT3wBnKIxhgA5nkTLVGxHSat2SWXN4DazAB4AHOIyjJwIhE9SiAwjnwA3ODAATfQYAG1ZEcFEANQBDEMQAXjcXMCxsXnpFAHcYKAgAC0RMSIRYkOxg+noIGMVmQmJ8AyqAIxYY6Qz6ASqA5mAYkBCoJoYqljYOLp6LemB7IrDHELV6pIBGbkQVsHqAHg2ABi2d5gBqM4rmpcRTJRU1dS7s3IKikrAyq7Hq2vquUZVKqmRINYhdVrtTo-HrdMbiURSUzpBgCPhAA)

[TypeScript 4.9.3 Playground Example](https://www.typescriptlang.org/play?ts=4.9.3#code/GYVwdgxgLglg9mABKSsEEEAUBKAXIgInQMQB9CAhEgbwCgBIAJwFMoRGkiCBuWgX1q0U0eEmFowFTAGtmAT3wBnKIxhgA5nkTLVGxHSat2SWXN4DazAB4AHOIyjJwIhE9SiAwjnwA3ODAATfQYAG1ZEcFEANQBDEMQAXjcXMCxsXnpFAHcYKAgAC0RMSIRYkOxg+noIGMVmQmJ8AyqAIxYY6Qz6ASqA5mAYkBCoJoYqljYOLp6LemB7IrDHELV6pIBGbkQVsHqAHg2ABi2d5gBqM4rmpcRTJRU1dS7s3IKikrAyq7Hq2vquUZVKqmRINYhdVrtTo-HrdMbiURSUzpBgCPhAA)

[Nightly Playground Example](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221129#code/GYVwdgxgLglg9mABKSsEEEAUBKAXIgInQMQB9CAhEgbwCgBIAJwFMoRGkiCBuWgX1q0U0eEmFowFTAGtmAT3wBnKIxhgA5nkTLVGxHSat2SWXN4DazAB4AHOIyjJwIhE9SiAwjnwA3ODAATfQYAG1ZEcFEANQBDEMQAXjcXMCxsXnpFAHcYKAgAC0RMSIRYkOxg+noIGMVmQmJ8AyqAIxYY6Qz6ASqA5mAYkBCoJoYqljYOLp6LemB7IrDHELV6pIBGbkQVsHqAHg2ABi2d5gBqM4rmpcRTJRU1dS7s3IKikrAyq7Hq2vquUZVKqmRINYhdVrtTo-HrdMbiURSUzpBgCPhAA)

### 💻 Code

```ts
function functionA(): "A" | "B" {
	return "A";
}

function functionB(key: string): string {
	return key;
}

export function functionC(): void {
	let unionVal = functionA();
	switch (unionVal) {
		case "A": {
			break;
		}
		default: {
			return;
		}
	}

	for (let line = 1; line <= 10; line++) {
		let key: string;
		switch (unionVal) {
			case "A": {
				key = "AA";
				break;
			}
		}
		functionB(key);
	}
}
```

### 🙁 Actual behavior

Variable 'key' is used before being assigned.

### 🙂 Expected behavior

No error

**Comment by jcalz** [comment]
bisected to #51095

**Comment by ahejlsberg** [comment]
Simpler repro:

```ts
declare function functionB(key: string): string;

function functionC(): void {
	let unionVal: "A" | "B" = "A";
	while (true) {
		let key: string;
		switch (unionVal) {
			case "A": {
				key = "AA";
				break;
			}
		}
		functionB(key);
	}
}
```
