### ISSUE TITLE
Type compatibilty of Record is evaluated differently when aliased

### ISSUE THREAD

**Issue by Fredx87** [microsoft/TypeScript#51687]
# Bug Report

### 🔎 Search Terms

record alias generic function argument type compatibility evaluation

### 🕗 Version & Regression Information

4.9.3

- This changed between versions 4.1 and 4.2

### ⏯ Playground Link

[Playground link with relevant code](
https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiDSERQLxQEQDMD231QB8MAjAQwCd0BuAKBtEigEEAbAS1IGdUoAlCAMbZyAEwA8cRCAA0UTsHJsAdgHMAfLRojBLCtEwBXJQOBtsSqJiUBGABRgKpALYAuPoOHjJSWfMWq1AEo3ADdsNhFabQFdcn0jEzMLKwAme0dXZnYuYKgwiM1o2OghJXkoAA83fiFRMT9lFV8FRo06AHp2qAB5AGsXGis7CsCOroBRcnJhAdTbEaA)

### 💻 Code

```ts
type MyKey = "foo" | "bar";

type Alias = Record<MyKey, string>;

declare function fn1(param: Record<MyKey, string>): void;
declare function fn2(param: Alias): void;

declare const x: Record<string, string>;

// Ok:
fn1(x)

// Error:
fn2(x)
```

### 🙁 Actual behavior

When a function has an argument with a Record with a generic key, it is possible to pass a `Record<string, string>` if the parameter type is declared inline, but the compiler returns an error if the parameter type is a alias.

### 🙂 Expected behavior

The behavior should be the same independent of how the parameter type is defined.

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/49852#issuecomment-1182097024
