### ISSUE TITLE
Ambient types not working for json import assertions with moduleResolution: Node16/NodeNext

### ISSUE THREAD

**Issue by dnalborczyk** [microsoft/TypeScript#51691]
# Bug Report

### 🔎 Search Terms

json import assertions ambient types 

### ⏯ Playground Link

n/a

### 💻 Code

locationData.json.d.ts

```ts
export interface Location {
  id: string
}

declare const locations: Location[]

export default locations
```

locationData.json
```json
[
  {
    "id": "loc-1"
  }
]
```

index.ts
```ts
import locations from './locationsData.json' assert { type: 'json' }
import type { Location } from './locationsData.json'
```

tsconfig.json
```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "NodeNext",
    "outDir": "dist",
    "strict": true,
    "target": "ESNext",
  },
}

```

### 🙁 Actual behavior

`locations` is untyped (any)

### 🙂 Expected behavior

`locations` should be typed

it works as expected with "moduleResolution": "Node"

**Comment by fatcerberus** [comment]
Does this even work at all?  I thought this required https://github.com/microsoft/TypeScript/issues/50133

**Comment by weswigham** [comment]
Yep, this never worked - your declaration file is actually for `locationsData.json.js`, which is commonjs often looks _close enough_, but in the case of native esm, won't cut it. You need #50133.
