### ISSUE TITLE
strange inheritance issue

### ISSUE THREAD

**Issue by serrique** [microsoft/TypeScript#51692]
```
abstract class Base {
  protected abstract testify:(source: this) => this;
}

abstract class Derived extends Base {
  protected abstract testify:(source: this) => this;
}

function foo(a: Derived): Base {
  return a;
}
```

this simple code brings an error: 

> Property 'testify' is protected but type 'Base' is not a class derived from 'Derived'.(2322)

If we change modifiers to public, it will go away

playground:
https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgQmgpgg3gFAIIAOUA9hDvDgCYKiQzwLWQCWAZgJ4BcACjAUArlFg4+bABYcwASgQBeAHwy5AbkIBfQoSbQ4iFGgwARHFA4A3eghwAPagDs6GbGDxES5KjWoMBiyI7BDc-EKi4pLqCspqELJgWrqEXCLO8BwUzghcFBQCwFIWVrZ08lIeXsQIUDgQYrnAKXp6QUZIqOhYuABMBLUdrKHhgsJiElKJcoqqsa364IasJj2lNvQDji5uvZ4D3ozLwWw4nLzjUVOxcwlJi+mZYTl5BX1FJZabdH2V+zhDrV6o0oM0UkA

**Comment by RyanCavanaugh** [comment]
This is a correct error. The surprising aspect comes because the classes are only nominal when they have a protected field, otherwise they would be structurally identical

**Comment by fatcerberus** [comment]
@RyanCavanaugh I’m a bit confused myself - even in a nominal type system `Derived` should always be assignable to `Base` if the former extends the latter and there are no errors in either class definition
