### ISSUE TITLE
Recursive type literals

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/TypeScript#517]
# Introduction

Currently, type literals are capable of representing any instantiated (non-generic) type except those that are recursive.  This is because, as an anonymous type, they do not have a name with which to create this type.

This proposal covers recursive type literals.  These type literals add the additional ability of the literal referring to itself.  This has one main advantage: emitting .d.ts files for expressions typed by class expressions now have a "flattened" representations.  As class expressions could easily have recursive components, we'd like to be able to emit a corresponding type representation into the .d.ts file without contaminating the namespace with additional fresh type names.  

# Design

```TypeScript
var x : <Node> { next: Node; value: number; };
```

The above acts similarly to this example:
```TypeScript
interface Node { next: Node; value: number; };
var x : Node; 
```
with one critical exception: in the first example the 'Node' name is **not** visible outside of the type literal.

# Typechecking

Typechecking of recursive type literals works just as recursive interfaces, with the exception (as mentioned above) that the name given to the recursive type literal is not visible in the lexical scope outside of the type literal.  Otherwise, these expand and are compared for equality structurally just as interfaces.

# Differences with other designs

This design differs from similar designs, named the 'self' type design where there is a specific keywords that the type can refer to its self.  This proposal is strictly more expressive, albeit at the cost of some additional syntax.  For example, embedded recursive types are possible:

```TypeScript
var x: <Node> { up: <Parent>{ up: Parent; node: Node}; next: Node; value: number};
```

**Comment by jbondc** [comment]
Any newer progress on this?

Stylistically I'd seem to prefer a cast in the object literal to give it a name:
```
// (a)
function foo(): <Blip>{ a: SomeType, b: Blip } {
}
// (b)
function foo(): interface Blip { a: SomeType, b: Blip } {
}
```
Think (b) made a lot of sense with the ```interface``` as the structural building block. 

With the addition of  ```type alias<T> = number | T;```, (a) starts to look natural too.

**Comment by JsonFreeman** [comment]
This issue is really out of date. It is from before we had generic type aliases, local types, and maybe even intersection and union types. I would recommend looking at #3496 for more current and relevant discussion.

**Comment by mhegazy** [comment]
As @JsonFreeman, there are ways now to enable scenarios. we wanted to add an `interface` equivalent to class expressions, but do not think this is required.
