### ISSUE TITLE
Generic return type of function is enforced inconsistently in some cases

### ISSUE THREAD

**Issue by NICHTJ3** [microsoft/TypeScript#51706]
# Bug Report

### 🔎 Search Terms

- record generic
- explicit return with generics

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221130#code/MYewdgzgLgBA5gUzAgTgS2AdTVAFgJQVBQBNCoBXFMAFQE8AHBGAXhgB4aYEAPKJEhBgBDMHQB8ACmEoUALgCCs4XU7iAlHMLES7MBQC2AI1QAaGuNbiA3gCgYDmKEiwUREKVYw7j3zBIIAGZoYDgIADZ0YCBQooYm8jIoANoADAC69o4AvgDcWQ5ulNQwbjr5eba2ztDwSKgY2HjaHmQIxbSMCABMXpzcfAJCohLSsorKqhaaLaR68WYWVj6ORVRg3gV+AcGh-JHRsfrGqHJJaZm+lZXV4LWIyOhYOATupOTr9Ew0uMJQmB4ANZCNj9Xj8MCCERiKRJCYoFRqGZvXTHBLmSwsKQrBw7EJhA4xOInRKyC62bLqXJAA)

### 💻 Code

```ts
const genericWithRecordReturnType = <T extends any>(arr:Array<T>):Record<number,T> =>{
    return {
        definitelynotanumber:arr[0]
    };
};

const genericWithRecordReturnTypeThatWorks = <T extends any>(arr:Array<T>):Record<number,T> =>({
    definitelynotanumber:arr[0]
});

function test<T>(arr:Array<T>):Record<number,T>{
    return{
    definitelynotanumber:arr[0]
}
}
```

### 🙁 Actual behavior

I receive no errors for the function definition for the function that explicitly returns the record infered in the assigmnet above but I do for returns without interum assignment

### 🙂 Expected behavior

I should receive errors for both cases or the behaviour should atleast be consistant

**Comment by fatcerberus** [comment]
The error is detected by excess property check, which only works for directly assigned object literals.  Outside of that, the object with a non-number property is otherwise assignable to the numeric record.  See https://github.com/microsoft/TypeScript/issues/48906.

**Comment by NICHTJ3** [comment]
Pretty similar to #51680. If you guys are okay with it I might close as a duplicate? 🤔

**Comment by fatcerberus** [comment]
Yeah, sorry I wasn’t clear above - this is working as intended.  Objects can have more properties than their type requires, the compiler just does an excess property check in certain cases as a kind of basic sanity check but you shouldn’t rely on it to enforce runtime safety.
