### ISSUE TITLE
"keyof T as ..." looses nested generic of T inside function body

### ISSUE THREAD

**Issue by dilame** [microsoft/TypeScript#51709]
# Bug Report

### 🔎 Search Terms

function body generic, keyof as clause

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about everything

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAMg9nAzhA4hAdhATgSwMYA8AKlBAB7AYAmiUcARgFYR7AB8UAvFAN5QDaAaSg50UANYQQcAGZQSAQ1pEhAXVIVqytVAD8UYQC4Dq4ysHqAvgG4AUAHp7UAHpQACgBsISiABp3CiBQCsCUwDhwYsBwUMAAFtB4kVQ44ZEKHrHg0AlY0IDIBCJQeAl44rQ4cqCQGpToNCLAyB5yCvVQecAArljotIgKALbQwqJQ9HDxxcmpEegZ41htJRCIttXQAGIKOB7EHNzwSKgY2PgEPLZQUADmp7h4ZnbXiMBYxq+46Dd2lmx2thkXXQrDmUBkOz2RDYAAosMDjNtdvsAJS8K4dCDdXodYG-Wy2JJ9YCxVYk7gQ3Ywnh3TAPYwARn8n2MAHJPqzLCiCZRXgA6WlnPAOezOXQiqDA8ToOAAd3QQA)

### 💻 Code

```ts
type LooseGeneric<T extends object> = { [K in keyof T as T[K] extends T[K] ? K : K]: T[K] };
// ^ Please, pay attention to the conditional type here – i checks if type extends itself and returns same K in both conditional branches
type Fail<T> = LooseGeneric<{
  generic: T;
  str: string;
}>;

function fail<T>(run: Fail<T>) {
  return run;
}

const test = fail({generic: 1, str: 'str'})

test.generic
//^?
// unknown
```

### 🙁 Actual behavior

`test.generic` is unknown type

The funny thing is if i define like this `type LooseGeneric<T extends object> = { [K in keyof T]: T[K] };` – everything works as expected.

### 🙂 Expected behavior

`test.generic` expected to be `number` type

**Comment by dilame** [comment]
Also, same applies for the [next code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gdgGxAJQgRwK4EsBOEAmAPACpQQAewEc+AzlAPYBGAVhAMbAB8UAvFAG8oAbQDSULHCgBrCCAYAzKMQC6ALmViVZStTpQAouXYIM+CCS0AaKBhoQFkgjwD8m0do1wIANwg4oAF8AblBIWEQQGDBgLAY4AEMEEh0qGnpmNk4efiExCSlZeSVVDWItVL16IxMzC3KPGztzR298VyhvPwCyrRCAKDDoAGVgHCwwADlffxSKNP1Mjm4+QRFxSRk5RWUoBPoG7XmqzpmAty7-KA0PXo8g-sHwaAAxBgYSHMF+qCgAc2o-iw7DKwR+UFoYw0kPGcD+YIGT3CLwSWGSxC+o3GUzOhHgSFQmFwBEIbw+GK4XDBQygkwYwBRaM+q3xKHQ2DwRDJnypjwUdk4cSkClR6K4AAocHYNIyxQBKb6-PDADA4KRSuAIvkC2LxTr02WfSXS2kG0WfBUCcHK1Xquxa-rseKQqBUSEAEQSwASqwEAO84xBUAAjDYYRoAOQwiOBPb0J1wSFg-oitHit3AT3euUAOn9QPY-QA9EWAHouYtF2xwaRwBgAdzgjzrDNF6YgHq9CVz+cDlfLlZD-SAA)

```typescript
type OnlyRequired<T extends object> = { [K in keyof T]: T[K] extends Exclude<T[K], undefined> ? T[K] : never };

type StripNever<T extends object> = { [K in keyof T as T[K] extends never ? never : K]: T[K] }

type Foo<T> = {
  generic: T;
  str: string;
};

type Fail<T> = StripNever<OnlyRequired<Foo<T>>>;
type NotFail<T> = OnlyRequired<Foo<T>>;

function fail<T>(run: Fail<T>) {
  return run;
}

function notFail<T>(run: NotFail<T>) {
  return run;
}

const testData = {generic: 1, str: 'str'} as const;

fail(testData).generic
//^?
// unknown

notFail(testData).generic
//^?
// 1
```

**Comment by dilame** [comment]
In the end of the day i just want to make a type that adds question mark to the ` | undefined`able property values.

Something like 
```
type AddQuestionMarks<T> = {.....}

type result = AddQuestionMarks<{a: number; b: string | undefined}>
// ^? {a: number; b?: string | undefined}
```

I need it to fix bug in [zod](https://github.com/colinhacks/zod) library. It already [contains code](https://github.com/colinhacks/zod/blob/master/src/types.ts#L1665-L1676) for it, but it looses generic inside function body.

Would you please help me to implement a solution that doesn't  loose generics? 😢 I tried everything i know about TypeScript, but no success yet.

**Comment by RyanCavanaugh** [comment]
I can't really tell what the example in the OP is trying to do, but the behavior is correct (there are no inference sites for `T`).

`AddQuestionMarks` exists and is called `Partial`.

**Comment by fatcerberus** [comment]
It seems like the intent is to do “`Partial` but only for certain properties”
