### ISSUE TITLE
Support generating .d.ts file which uses relative import from .ts that uses non-relative import

### ISSUE THREAD

**Issue by XieJiSS** [microsoft/TypeScript#51701]
# Suggestion

## 🔍 Search Terms

+ import in TypeScript `.d.ts` jumps to `.ts` but not `.d.ts`
+ import type generated in `.d.ts` has wrong path

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Consider adding a `--resolveType=as-is/relative/non-relative` option, which affect all non-dynamic import statements for input files. Won't affect normal imports from `node_modules`, etc. because they are in `"exclude"`. 

TypeScript supports specifying `outDir` and `declarationDir` to avoid overwriting input files when `.d.ts` are generated:

```shell
yarn -p typescript tsc --declaration --emitDeclarationOnly --outDir dts --declarationDir dts
```

However, if non-relative imports of user-created typescript files are used, generating `.d.ts` in a different directory other than the `baseUrl` directory causes resolve failure:

```ts
// file: dts/B.d.ts
import type { A } from "db/A";  // importing db/A.ts but not dts/db/A.d.ts
```

This causes bugs if the original typescript file is moved/changed. Consider the generated `.d.ts` as sort of independent released product, like some C-library's `.h` files bundled with `.so`'s, the generated `.d.ts` files of a project definitely should not rely on `.ts` to work.

Another problem is that, if another sub-project, as part of the code base (e.g. a monorepo), referenced this `dts/` directory in their `typeRoots`, then dts files that use non-relative import to import other modules will stop working completely. See "💻 Use Cases" for a detailed illustration.

## 📃 Motivating Example

If `--resolveType=relative` is specified, then:

```ts
// file: path/to/B.ts
import { A } from "../A"  // original 1
import { C } from "C"  // original 2

import { A } from "path/A"  // generated 1
import { A } from "C"  // generated 2
```

If `non-relative` is specified, then:

```ts
// file: path/to/B.ts
import { A } from "../A"  // original 1
import { C } from "C"  // original 2

import { A } from "../A"  // generated 1
import { A } from "../../C"  // generated 2
```

## 💻 Use Cases

In my VS Code which bundles typescript version `5.0.0-dev.20221117`, you can see that if module resolution path contains `.ts` files, the type check simply stops working:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/24671280/204892535-ae38bc61-5b32-47e5-9e0d-1a66a1a01e98.png">

The above issue happens with `outDir` is set to `dts`, under the following initialization code:

```ts
// this repo is placed in a subfolder of the project which generates .d.ts,
// so we need to use ../../../dts/ to access those .d.ts files.
import type { PanelAdminLinkRespData } from "../../../dts/panel/panel-server";
import type { AccessLinkModel } from "../../../dts/db/models/all-models";
```

and inside `panel-server.d.ts` is the problematic `import` statement which is resolved to a non-existing file (because `baseUrl` is specified by the sub-project now!) instead of the correct `.d.ts`, due to non-relative import:

```ts
import type { AccessLinkModel } from "db/models/all-models";  // resolves to a missing file, which breaks type check!
```

Changing the import path in the above statement to `"../db/models/all-models"` (relative import!) fixes the issue.

**Comment by weswigham** [comment]
`baseUrl` is meant to be used with old bower-style website root stuff. Generally speaking, the assumption is that if you're using `baseUrl`, your output is meant to be consumed with the same (or a compatible) `baseUrl` path. If that's not the case, you really shouldn't be using it, since, as you've noticed, it implies that nonrelative lookups from the base location are valid, just as with a website root.

**Comment by weswigham** [comment]
If you want to transform your project's declaration files to be more portable to other project setting configurations, without changing the quirks in your upstream project's settings, packing it all together into a single file with something like API extractor can work well, too, since that'll inline the internal structure.

**Comment by XieJiSS** [comment]
The information is useful, thanks :-) Seems like I should not enable the `baseUrl` options.
