### ISSUE TITLE
An import path cannot end with a '.mts' extension. Consider importing '.mjs' instead.

### ISSUE THREAD

**Issue by rtritto** [microsoft/TypeScript#51719]
# Bug Report

### 🔎 Search Terms

I'm creating a new Next.js project using TypeScript + ESM.
I'm using VSCode as IDE and Yarn Berry (latest version _4.0.0-rc.32_, Plug'n'Play enabled (_pnp_ loader), _@yarnpkg/sdks_ dependency) as package manager.

### 🕗 TypeScript Versions

- 4.9.3
- 5.0.0-dev.20221201

### ⏯ Playground Link

[Playground link with relevant code](https://codesandbox.io/s/typescript-forked-yupzti)

### 💻 Code
`package.json`
```json
{
  ...
  "type": "module",
  ...
}
```

`a.mts`
```ts
import b from './b.mts'
```

`b.mts`

```ts
// empty (not relevant)
```

`tsconfig.json`
```js
{
  "compilerOptions": {
    "target": "ES2022",
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "NodeNext",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "lib": [
      "DOM",
      "DOM.Iterable",
      "ESNext"
    ],
    "jsx": "preserve"
  },
  "include": [
    "*.mts"
  ]
}
```

### 🙁 Actual behavior

```console
An import path cannot end with a '.mts' extension. Consider importing './b.mjs' instead.
```

### 🙂 Expected behavior

Correct import of `.mts` file with no TypeScript parse error.

**Comment by RyanCavanaugh** [comment]
See #51669
