### ISSUE TITLE
Autocomplete should suggest concrete union values

### ISSUE THREAD

**Issue by alexreardon** [microsoft/TypeScript#51717]
# Suggestion

It would be great if unions that contained concrete values would have those values populated for autocomplete

```ts
type Value1 = 'first' | 'second'

// ↓ 'first' and 'second' will be auto-complete options
const a: Value1 = 'first';

type Value2 = 'first' | 'second' | string;

// ↓ no auto-complete options
const b: Value2 = 'first';
```
[TypeScript playground](https://www.typescriptlang.org/play?ssl=9&ssc=27&pln=1&pc=1#code/C4TwDgpgBAaghgGwK4QIxQLxQOQDMCWATgM7DZQA+OxEAxgPYB2AJtgFBsD0nUgyYQ4ESZKHBbU6TVlADu+BAigAjaHCTB6AWgYBbMAgjBo9MMHxNibBo1IiAXLEQp0WPEVLYA3B1CQHyCABMmAJuwlTYNFZSVKSE+IwA5l5cPPyM9CJqmjp6BkYmZtaW5sBK9vD+QS6C7h5AA)

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Autocomplete would suggest concrete values when the union contains a primitive type

## 📃 Motivating Example

I am creating a type to represent [MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). I would like to allow good auto-completion for predefined values, (eg `text/plain`) but also allow any string value (people can create their own MIME types)

```ts
export type NativeMediaType =
  | 'text/uri-list'
  | 'text/plain'
  | 'text/html'
  | 'Files'
// ↓ Currently ruining autocomplete
  | string;
```

## 💻 Use Cases

There exist a few workarounds, but they are a bit wonky

> ```ts
> type FooOrString = 'foo' | (string & {})
> ```
> 
> this is the most popular variant of this that I've seen. It kinda relies on the > fact that intersections are not reduced. `& {}` is nowadays an equivalent to > NonNullable (check its content). So conceptually `string & {}` is just `string`

- @Andarist [tweet](https://twitter.com/AndaristRake/status/1598449004962107393)

> TypeScript protip: accept any string, but suggest some specific values on > autocomplete.
> 
> ```ts
> type StringWithAutocomplete<T> = T | (string & Record<never, never>);
> 
> type Fruit = StringWithAutocomplete<"apple" | "banana" | "grape">;
> 
> const apple: Fruit = "apple";
> const banana: Fruit = "banana";
> const watermelon: Fruit = "watermelon";
> 
> const fruit: Fruit = "";
> ```
> 
> [TypeScript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBLAdgcwOqOACwIIFdgB7AYyIFswAbCYCAHgBUA+KAXikagB8oAKAM4IUqKADIoAJQhl4AE3rIIANwjwANFCWr4zAJQBuAFBHQkKADF4+LO1jC0mHAWJlKNOvQBEAQzDUILx4oLwAjH2QInyDeL1R4P0DmYyMyZCEoPwCALktrWw5ffxovYzSM8MjI3KsbYDswqMjS1KJ0+oB3Hzp4cggqNpr8+sKunr6B5BbW9qgAM2GhuobSoA)

- @diegohaz [tweet](https://twitter.com/diegohaz/status/1524257274012876801)

**Comment by fatcerberus** [comment]
Duplicate https://github.com/microsoft/TypeScript/issues/29729
