### ISSUE TITLE
JSX spread child can be a generator

### ISSUE THREAD

**Issue by corbane** [microsoft/TypeScript#51711]
# Bug Report

### 🔎 Search Terms

JSX spread child must be an array type.
JSX spread child generator 
JSX spread generator 
ts(2609)
2609 generator

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about &lt;Search Terms above>

### ⏯ Playground Link

[Playground code](https://www.typescriptlang.org/play?ts=4.9.3#code/GYVwdgxgLglg9mAVAAgOYFMzoE4EMroAUAlMgN4BQy1ywc2hAbrtsjALwAMA3G8gDwBGHmwDUo4lRrSAnjHQAbACbIlcCCAC2mKADoI2dPnQBRBem1gohAEQBnAA64wNyQF8KzVobsgFUZHYBJRhGAD4yXSiMLDwCEjd+AHoQ8KA)

### 💻 Code

```ts
function* generate() {
    for(var i=0; i <10; i++)
        yield document.createElement("span")
}
var result = <div>{...generate()}</div>
```

### 🙁 Actual behavior

An error is generated if a JSX.Element generator is used.
![image](https://user-images.githubusercontent.com/8430545/205106608-f8c4407e-26e6-4bbd-8e8a-2b2dd33c6679.png)

### 🙂 Expected behavior

The result of the compilation conforms to javascript and the code works. so the compiler doesn't need to fail in this case.
```ts
function* generate() {
    for (var i = 0; i < 10; i++)
        yield document.createElement("span");
}
var result = React.createElement("div", null, ...generate());
```

**Comment by MartinJohns** [comment]
Related: #51328

**Comment by RyanCavanaugh** [comment]
This is explicitly not allowed by React, see https://github.com/facebook/react/pull/13312

**Comment by Josh-Cena** [comment]
@RyanCavanaugh That patch is about rendering generators as _components_; this one is about spreading it as _children_. Each individual children is still a component or a tag.

**Comment by corbane** [comment]
OK I understand.
But Typescript only cares about React? React is not the only library available.
I used React in my example for the Playground, but personally I don't use React.
My createElement and createFragment functions are custom functions that directly return HTMLElement or SVGElement.
A kind of Jquery in JSX, there is no notion of state or keys.
the "Working as Intended" label is specific to a single solution.

**Comment by RyanCavanaugh** [comment]
> That patch is about rendering generators as components; this one is about spreading it as children. Each individual child is still a plain-function component or a tag. After spreading, it would not be observable to React.

This is a child spread, which is a JSX-specific feature, so we can't say for certain that it transforms to a runtime spread (as far as I know, React has not provided a spec for what any given JSX feature is truly a sugar for) Other transpilers, even as lately as this year, have not necessarily produced an ES iterator spread in their output when consuming this (favoring instead to present the argument as-is): https://github.com/evanw/esbuild/issues/2245, so it's not a settled question.

The unquestionably safe thing to write is this:
```
var result = <div>{[...generate()]}</div>
```

> React is not the only library available.

Sure, but it's what 98%+ of TS users are using. We can't possibly support any JSX framework anyone might come up with
