### ISSUE TITLE
[Regression] - Language Server fails to call into plugin from v5.0-20221108 onwards

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/TypeScript#51713]
# Bug Report

### 🔎 Search Terms

"language server", "language service plugin"

### 🕗 Version & Regression Information

- This changed between versions v5.0.20221103 and v5.0.20221108

This originated from: https://github.com/microsoft/vscode-typescript-next/issues/61 please see here for more context.

It has been [reported](https://github.com/microsoft/vscode-typescript-next/issues/61) that the [VSCode Styled Components](https://github.com/styled-components/vscode-styled-components) extension stops working when also being used with [TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next).

Our [typescript plugin](https://github.com/styled-components/typescript-styled-plugin) does use the latest version of typescript (4.9.3) and I have tested it with "next" (5.x) and it still happens so I think this bug is on the TypeScript Language Server side.

Version 20221103 successfully calls into the language server and receives completions
<img width="774" alt="working-20221103" src="https://user-images.githubusercontent.com/936006/205078344-7381a75d-a332-44f9-9202-6baa382bb48b.png">

Version 20221108 fails to call into the language server, so we don't get anything at all.
<img width="643" alt="notworking" src="https://user-images.githubusercontent.com/936006/205078331-c3b1aaf1-e29b-4eab-a932-077a23c96823.png">

## Reproducing

- You can install the VSCode Styled Components extension 
- Hover over some styled components, there are some [here](https://github.com/styled-components/vscode-styled-components/tree/main/src/tests/suite/colorize-fixtures)
- You should get some hover information for the CSS styles
- Add the TypeScript Nightly extension, reload VSCode, then try again

**Comment by sheetalkamat** [comment]
with typescript's export * set using getter and non cofigurable or writable i am not sure how to fix this. The `getSupportedCodeFixes` has multiple issues open against the API and inconvenience it causes.. #28966 #29051 #46249 for context

**Comment by jakebailey** [comment]
I'm out of the country and can't look at this until next week, but in general I don't see a way to fix this other than to get everyone off of assigning to the TS library; this isn't even an esbuild thing, it's just how modules work (rollup would produce the same errors).

We "fixed" this for sys by adding setSys. But that shouldn't really be even in our API. We could do something like that for this function, but I am really wondering if we can fix the API such that this kind of thing is not needed.

**Comment by jakebailey** [comment]
I am back and looking at this; just to be clear, is the offending code solely in the VS Code extension, and not replicated in any other place? Or is this a problem with any and all plugins?

If it's just VS code, then we can just use #51769 and be fine; we can get VS Code updated long before 5.0 makes it out.

**Comment by sheetalkamat** [comment]
any plugin would have a problem i think but i think https://github.com/microsoft/TypeScript/pull/51769 should be good enough for this.

**Comment by jasonwilliams** [comment]
Hey @sheetalkamat we're still [having issues](https://github.com/styled-components/vscode-styled-components/issues/409) with this, were the changes needed to make this work released?

It seems some fixes were made by @mjbvz but [not released](https://github.com/styled-components/vscode-styled-components/issues/387#issuecomment-1475273954).

Any help you can offer would be appreciated!

**Comment by jakebailey** [comment]
I don't know what work there is to do on our end; I'm surprised we didn't close this issue after #51769 was merged.

Given the upstream problem has been fixed, it seems like this is just a matter of whatever plugins which depend on `typescript-template-language-service-decorator` needing to update? That's still not something we (the TS team) has any control over besides bringing things to others' attention.

Are you saying @mjbvz just needs to bump something?

**Comment by jasonwilliams** [comment]
> Given the upstream problem has been fixed, it seems like this is just a matter of whatever plugins which depend on typescript-template-language-service-decorator needing to update?

it was fixed on the repo but no release was made, meaning plugins have nothing to update to. Also the dev-version of typescript that repo was using is now out of date.

You’re correct that it’s not directly a “TypeScript team” problem, but it is a project that falls under the Microsoft organisation for language servers.

**Comment by mjbvz** [comment]
@jasonwilliams Try picking up typescript-template-language-service-decorator 2.3.2 which should have the fix

**Comment by jasonwilliams** [comment]
Hey @mjbvz thanks that works, although most of the e2e tests you wrote no longer work. The TS Server sends an empty response: https://github.com/styled-components/typescript-styled-plugin/issues/9#issue-1652822653
