### ISSUE TITLE
Type information lost when checking if a Tuple is assignable to an Array

### ISSUE THREAD

**Issue by Vap0r1ze** [microsoft/TypeScript#51724]
# Bug Report

When you try to assign a tuple to an array type, it _seems_ as though the tuple elements are unioned before checking assignability?
See below code for an example

### 🔎 Search Terms

tuple any array flatten assignable

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about **tuples**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.3#code/MYewdgzgLgBAZiEAuGYCuBbARgUwE4DaAujALwwHoA2VANKmjSQIYQXV0NMwD0PqIWFACeABxwRmcHPXx4QeNgAoA5ogAmASgBQoSLCzM8KdNnzEy7Rpw4s2la-WZhhJPjAFCxEqTJgB3BQBrNhglQy1tIA)

### 💻 Code

```ts
const foo: number[] = [null, null] as [null, null] // not typesafe, errors (good)
const bar: number[] = [null, null] as [null, any] //  not typesafe, works  (bad)
```

### 🙁 Actual behavior

```ts
const foo: number[] = [null, null] as [null, any] // is allowed
```

### 🙂 Expected behavior

```ts
const foo: number[] = [null, null] as [null, any] // error
//    ^
//    Type '[null, any]' is not assignable to type 'number[]'.
//      Type 'null' is not assignable to type 'number'.
```

### Notes
I think this is only a notable issue when all of these are true:
  - One of the Tuple types is a supertype of all other tuple types
  - One of the Tuple types is not assignable to the Array element type
Because of that, I feel there might be another example that uses `unknown`, but I couldn't think of one

**Comment by jcalz** [comment]
I'm not following why this would be a bug.  Type assertions are supposed to allow some unsafe things, and `any` is supposed to allow some unsafe things, and a tuple `[T, U]` is supposed to be assignable to `(T | U)[]`, so... what's the issue here?

**Comment by fatcerberus** [comment]
@jcalz The type assertion is a red herring - the bug report is that `[ null, any ]` is assignable to `number[]`, which seems... questionable, since only one of the members of that tuple is assignable to `number`.

**Comment by MartinJohns** [comment]
```typescript
declare function f(): [null, any];
const bar: number[] = f();
```

**Comment by RyanCavanaugh** [comment]
`any` is "infectious" in this regard. The process for determining this check effectively goes:
 * Is the element type of the source assignable to the element type of the target (array covariance in a nutshell) ?
   * What is the element type of `[null, any]` ?
     * It's the union of `null` and `any`
     * That's `any`
   * Is `any` assignable to `number`?
     * Trivially yes (per the definition of `any`)

The same behavior can be seen in many other places. Asserting to `never` is generally safer for this reason:
```ts
const bar: number[] = [null, null] as [null, never] // errors (good)
const baz: number[] = [32, null] as [number, never] // ok (good)
```

**Comment by fatcerberus** [comment]
That makes sense, this is an interesting case where `any` becomes "viral" without directly participating in a union or intersection, because the compiler itself constructs a union as part of assignability checking.  Something to watch out for in general.

**Comment by Vap0r1ze** [comment]
This makes sense to mee. Another reason to stay away from `any` :D
