### ISSUE TITLE
npm module resolution not working when generating descriptors

### ISSUE THREAD

**Issue by grofit** [Microsoft/TypeScript#5172]
When I am compiling my typescript files, it works fine when compiling the normal outputs to js, but if I were to try and compile the descriptors it blows up saying it cannot find the modules.

So I have a build script like so:

```
var buildFor = function(module) {
    var tsResult = gulp
        .src([ paths.source, paths.typings ])
        .pipe(plumber())
        .pipe(ts({
            module: module,
            removeComments: true,
            target: "es5",
            declarationFiles: false,
            typescript: tsc
        }));

    return tsResult.js.pipe(gulp.dest(paths.output + "/" + module));
};

var buildDefinitions = function() {
    var tsResult = gulp
        .src([paths.source, paths.typings])
        .pipe(plumber())
        .pipe(ts({
            module: "commonjs",
            removeComments: true,
            target: "es5",
            declarationFiles: true,
            typescript: tsc
        }));

    return tsResult.dts.pipe(gulp.dest(paths.output + "/definitions"));
};
```

Now lets assume I have done an `npm install some-module` and that contains an `index.d.ts` which contains descriptor information and links to other d.ts files within this module.

Now if I had a typescript file like so:

```
import {SomeClass} from "some-module";

export class CampaignDescriptorFactory
{
   public blah: SomeClass;
}
```

When it is compiled with the `buildFor("commonjs")` works fine and no issues reported. However if I were to run the `buildDefinitions()` it blows up saying it cannot find `some-module`.

If it helps i have a SO question around this area which gives more info on the use case.
http://stackoverflow.com/questions/31983011/typescript-es6-module-syntax-with-ambient-d-ts-module

**Comment by mhegazy** [comment]
//CC: @vladima

**Comment by grofit** [comment]
Anyone have any ideas yet?

**Comment by DanielRosenwasser** [comment]
Sorry about the delay @grofit. Is there any change this could be an issue relating to gulp-typescript?

@ivogabe

**Comment by grofit** [comment]
Could possibly but as its the Typescript compiler which throws the errors under the hood and it works in all other contexts I would assume it is TSC not the gulp plugin, but this is easily proven, I will just run it through TSC shortly and get back to your with the results.

**Comment by ivogabe** [comment]
Module resolution should be working in gulp-typescript, also with declaration files. Which versions of gulp-typescript & TypeScript are you using?

**Comment by grofit** [comment]
TS - 1.6.2
Gulp - 3.9.0
Gulp-Typescript - 2.9.2

**Comment by grofit** [comment]
RIGHT! I think I have gotten the error to go away, I put in `moduleResolution: "node"` which I was not putting in before, but it is odd that the main compilation (ts -> js) worked fine without it, but the declaration did not.

**Comment by mhegazy** [comment]
@ivogabe do you know why `moduleResolution` is required? i can not get this to repro just using the commandline compiler.

**Comment by ivogabe** [comment]
@mhegazy I don't know.. When the user doesn't set `moduleResolution`, it also won't be passed to TypeScript. TS will then default to `node` (when `module` is set), or am I missing something? It's also strange that this only fails when the declaration option is set.

**Comment by mhegazy** [comment]
@grofit do you have a sample we can reproduce the issue on?

**Comment by grofit** [comment]
Sorry not really, but as mentioned the problem is solved now, I just needed to use the module resolution property.

**Comment by mhegazy** [comment]
i do not think `moduleResolution` is needed as long as `module: node`; if it does not work without this property then there is a bug somewhere that we need to address it.

**Comment by grofit** [comment]
is `module: node` a thing? I and compiling for `commonjs` and `system` but from a nodejs setting, so I would not expect to need to set the module type to node. (although the definitions are built against a `commonjs` module).

**Comment by mhegazy** [comment]
sorry.. too late at night, you are right, i meant `module: commonJS`. if you are using `module: System` then you need to specify `moduleResolution: node`.
