### ISSUE TITLE
.cts files use ESM mode for module resolution

### ISSUE THREAD

**Issue by IanVS** [microsoft/TypeScript#51737]
# Bug Report

### 🔎 Search Terms

"Resolving in ESM mode", ".cts", "NodeNext"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (4.7 - 5.0 nightly), and I reviewed the FAQ for entries about ".cts", "module resolution"

### ⏯ Playground Link

I tried to use the playground and the bug-workbench, but wasn't able to get it to emit type declaration files.  This is a minimal reproduction I created to clearly show the issue:

https://github.com/IanVS/mts-cts-reproduction

### 💻 Code

Here's my attempt at the bug workshop, but I suggest checking out my repo above instead.

```ts repro
// @moduleResolution: Node16

// @filename: node_modules/exports/package.json
{
  "name": "exports",
  "type": "module",
  "exports": {
    ".": {
      "import": {
        "types": "./index.d.ts",
        "default": "./index.js"
      },
      "require": {
        "types": "./index.d.cts",
        "default": "./index.cjs"
      }
    },
    "./package.json": "./package.json"
  }
}

// @filename: node_modules/exports/index.d.ts
export declare const value: "esm";

// @filename: node_modules/exports/index.d.cts
export declare const value: "cjs";

// @filename: package.json
{
  "name": "mts-cts-repro",
  "type": "module",
}

// @filename: src/foo.cts
export async function Foo() {
  return (await import("exports")).value;
}

// @filename: src/foo.mts
export async function Foo() {
  return (await import("exports")).value;
}

// @filename: src/foo.d.cts
// --- WHY IS THIS "esm"?---
export declare function Foo(): Promise<"esm">;

// @filename: src/foo.d.mts
export declare function Foo(): Promise<"esm">;


```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?moduleResolution=3&ssl=50&ssc=1&pln=1&pc=1#code/PTAEAEFsHsBMFcA2BTASsgztR8AuBLaAOwC5QA5OZARgDYAoekCAM3xSIENJkyiqA+jAQoMwZAA8ADtABOuMVM4BjANacA5sgB0AKyxF6Ab3qhQAIi49zZc5JnyM5gDSmLuAJ5TkNi8KQ+rmZ20nIKviZmwdoRblEW+JAOuLHx8eae3k622sD4RLCS2rDa4UFpwYUsnEgpOXkFRfrmcVEAvuXpssgAjvD43akV7l6Yvua5+YUSxdrKZa3pVTWIdRaTjTPKzYugba0drRPASmqaOvrE47mn6lp6Bi1m+-tMYOBsHNy8oPyFQnAAmJ7GExFMiiV5hh6CD5KBCspEJxuqBlMQMLhQAA3Tg4H7mbZOADcjGYH3YyCsPz+yABIkw4lCjga01mChhTMxCKRKLRRAx2Nx8HxmEg5hJb1YFKpZFu5wexGMbks33GkAUAFooRrulJZNAXMrMj5bP4UIbXmTPpTvmQMLJlMAWNBoHN2bDMZwMB4iMpQCx4L6CMRQAAxF0ACgAlKBIqBurh4LIiKAI5wAO6cfCYxLJCMhZJOKNR7Q4vEky3va0y0D2x3O13q6Ee0Ben1+gNBwgp8PQaOxtwJpMptOZ7OgXNhfMeoslsvCiukqvS221h1Ol2zKGSgDqAAkAJqgACSAGVQAAVPdniyi8wAfg5yXhyERyOQ-sD827YcjUbIAAK+qQPgGDIAAPHYGBigAfBKVorjwdrrg2sxNk+YQvm+KKdt+Ia9tGgHAaBEFQbBEpAA)

### 🙁 Actual behavior

`.cts` files are using the `import` condition, and getting esm types instead of the commonjs types from a node_module package defining `"exports"`.

Even stranger, in VSCode, intellisense is showing `"cjs"` as the type for `(await import("exports")).value` in both the `.cts` and the `.mts` file, which is the opposite behavior from `tsc`, which treats them both as `"esm"`.

### 🙂 Expected behavior

I expected `.cts` files to use the "require" condition by default (unless modified by the new [resolution-mode](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#resolution-mode), available only in nightly).

**Comment by weswigham** [comment]
Dynamic import always follows esm resolution rules in `node` - you'll find the esm file is loaded at runtime, too.

**Comment by IanVS** [comment]
Thank you, is this documented anywhere in the TypeScript docs?  I couldn't find it when I looked, and could submit a PR if desired.

Also, for the problem in the VSCode intellisense, where should I raise an issue for that?  Would that be a TypeScript issue, or a VSCode issue?

**Comment by phun-ky** [comment]
Is this related to: https://github.com/ezolenko/rollup-plugin-typescript2/issues/446 ?
