### ISSUE TITLE
Give more helpful error when trying to set default values on an interface

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript#5173]
Today I spent a moment scratching my head at the following snippet:

```
interface Foo {
	bar: number = 5;
}
```

*"Of course!"* I say now, I was trying to set a default value on an interface, which makes no sense. TypeScript didn't see that this might be something I would do, and instead gave me a syntax error:

```
Error TS1005: ';' expected.
Error TS1131: Property or signature expected.
Error TS1128: Declaration or statement expected.
```

Would it be possible to get a more useful error message for this case (and potentially cases like this?)

**Comment by delta-nry** [comment]
I am part of a group of students from the University of British Columbia looking to contribute to a bug fix. Is there anything we must do to get assigned onto this bug?

**Comment by DanielRosenwasser** [comment]
Nope, it's just good that you asked so others know you're working on it. Go for it. :smile:

**Comment by CyrusNajmabadi** [comment]
The correct way to handle this would likely be to just allow parsing a full on property inside an interface.  We can then report an error later on that an interface property cannot have an initializer.  That way the parse tree is well formed, and features like formatting/navbars/etc. all work property.

**Comment by jbondc** [comment]
@CyrusNajmabadi I'll try something else. 

Is there any reason a missing node doesn't have a flag?
https://github.com/Microsoft/TypeScript/pull/4878/files#diff-ead24f0f0f59c0ea9c1c511052e8884bR1027

That seems useful.

**Comment by jbondc** [comment]
It could be a single check here:
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/utilities.ts#L186
```
    export function nodeIsMissing(node: Node) {
        if (!node) {
            return true;
        }

        return node.flags & NodeFlags.Missing;
    }
```

**Comment by jbondc** [comment]
Oops, moving my comments to #4878

**Comment by delta-nry** [comment]
I've been looking at the parser.ts file. It appears that in parseTypeMember(), if we return parsePropertyOrMethodDeclaration() for string and numeric literals instead of returning parsePropertyOrMethodSignature(), this will allow parsing full properties inside an interface. In this case, parsePropertyOrMethodDeclaration() should return parsePropertyDeclaration(). What is the best way for parsePropertyDeclaration() to report the desired error if an initializer is present on an interface property?

**Comment by DanielRosenwasser** [comment]
Thanks @delta-nry!
