### ISSUE TITLE
Unlisted properties type narrowing seems to be working only for actual property access but the type is still incorrect on the object itself

### ISSUE THREAD

**Issue by TenkoSpirit** [microsoft/TypeScript#51739]
# Bug Report

With the release of TS 4.9 type narrowing was improved and we can use it to check for presence of some certain keys and their types in unknown objects, which works fine if we were to access the property like `foo.bar` and it would be, for example, a `string`. However, the type is incorrect for the object itself even after checking for the property's type and would result in `object & Record<"bar", unknown>`.

```ts
// the object
const foo = {
  bar: "string!",
}
```

### 🔎 Search Terms

* type narrowing with in
* property type narrowing
* "in" type narrowing

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because the type narrowing was introduced in the recent version.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIDED2nkG8BQyyARnFAFzIDOYUoA5gNz4C+++CmINyM2lGbMgC8eQiTKUARKShSANK2YcuPMAAsI6AK4gEYYFxHIAFAEoBWHMIB8Yop25hkAKypdgMYBAAmxgFIAygDyAHIAdDR0IPSeAJ4mfJhmzA6qzgAOZFS+lLoA1iCYAO4gASERWVA5Jm4eXr4p7ESepmBxGRCYMMhVOX4AhMKiUpjELhD6UsgAPjO92b4ioiDaADZrZvZEyBpQJcgAolD7UCZSAOoofUvuALYQGsD0ZWBw6s5woJ9lYxP6A2QABFyFImkQ2OJWiYBudZNNQAtqo0tgQdrt1PtikcTpgzjIyMhgFRkEVnIikoCQWDUshIS0eiZ2p1ukj+uFZMghiMogwwdsiHsDsdTucNCgkkTXpoJFAiSSycg4NRaAwqaDwXTmsgAPQ6jHE6jqTDrPzFPH5eTUUBIZDFFDqOAANxQcDWUAgcB8cWQCE0CHySxuPg5hOZKCMa1AKAATABGcSOHgeqjrZyiXDIcLZ4N06hwAxUBokwSYWlJzBrCDhNaYegmFNppriD1gbRQMqNtZgZgsZRJ5zi4LiqA6PQGIyicyWIS2bYD1zuECebx+URBMKRVUxeKJbCahfBvIgQolMrrirhG61JcrxrKBltDpdHq57nIUbjSZgaZzNlLYZSXWTYBQxLEcVFS5rkWPx7kedRnled5Pm+JVfi-AFgQ1Wl6SJRkCTkKV-z8AAyEjdmfVlg1DOVhh5bd6H5NEdgrKsazrExqNkFJdX1J4SUNZVeRicQiFbdsymDRheINASSWVAAlSY8R8AAeAiFGQAoilKOw+DlODkA9OAl3EXChWxEU8ThQlDUVClsHVGklHYcUx30QwQHMZghxHdyJy8lIgA)

### 💻 Code

```ts
interface IFoo {
  bar: string;
}

const foo: IFoo = {
  bar: "bar",
};

const theFunction = () => {
  const jsonified = JSON.stringify(foo);
  const parsed: unknown = JSON.parse(jsonified);

  if (typeof parsed !== "object" || parsed == null) {
    throw Error("We parsed somethign that aint an object! D:");
  }

  if (!("bar" in parsed)) {
    throw Error("bar is not in foo! D:");
  }

  if (typeof parsed.bar !== "string") {
    throw Error("the foo in the bar is not a string! D:");
  }
  // type error, "unknown" is not assignable to "string"
  const result = { ...parsed } satisfies IFoo;
};
```

### 🙁 Actual behavior

Object doesn't infer types after unlisted property type checking, i.e. `object & Record<"bar", unknown>`

### 🙂 Expected behavior

Object should know the type of a key after unlisted property type check, i.e. `object & Record<"bar", string>`

**Comment by TenkoSpirit** [comment]
Another interesting thing tho, is that when destructuring to a variable assignment it kinda works 50/50 here. VSCode seems to be able to tell the type after you write it, but it can't until you then.

Here's `bar` is `unknown`

![image](https://user-images.githubusercontent.com/103903444/205458477-dff51ec8-22f9-46a9-9089-8011b892f630.png)

And now here `bar` is a `string`

![image](https://user-images.githubusercontent.com/103903444/205458468-3a2913c0-81be-4fd5-9292-32f60e3cb7c5.png)

**Comment by Andarist** [comment]
It's a more general problem - not directly related to the new narrowing capabilities of `unknown`.

TypeScript only narrows down property types but this doesn't affect their parent object types at all. Notice how in [this playground](https://www.typescriptlang.org/play?ts=4.9.3#code/MYewdgzgLgBFAWBTAYgVzMKBLcMC8MAFFItAFwwDeMAZiCBWKgLYBGiATjAD4zQdYwAcxgBfAJT4AfFQBQMGFhpEoATwAOiEMpLQAdHRAwAhHgIAifoKHnJleQrikoDhQHo3MAHoB+V0-1Dfw9Hbz9Q0EhYUHVVfCoYPSTdWFFgz0dffwQOEAB3GABRDlyOQnEAbgc0hxSHEKyFFIN6eoyFRphI6C6QWPjqJL0UsTbQrIcAQ2BgRHUoYmdxWVEq2QATRGAAG0mORFp0TBwwGGnZ+cXyBMMKK2ExcQoANxAsdaA) the type of `test` stays always unaffected and that even `accept` is not happy about this object despite the fact that we already have narrowed down `test.foo`

**Comment by MartinJohns** [comment]
@Andarist That's intentional / design limitation. See #42384 for more details.

**Comment by fatcerberus** [comment]
On the other hand, see #50891, which is a duplicate of #42384 but notable for being posted by a TS team member.

**Comment by TenkoSpirit** [comment]
I see, thanks for details!
