### ISSUE TITLE
Inconsistent Partial Record definitions

### ISSUE THREAD

**Issue by rmanne** [microsoft/TypeScript#51736]
# Bug Report

Record<'some' | 'list' | 'of' | 'type' | 'literals', whatever> requires that all keys of this union be present in the Record.

However, the same isn't true for Record<string, whatever>, which accepts the empty object and sometimes behaves as if it's OK for not every possible string key to be in the record (which is definitely the sane approach), and sometimes behaves as if it enumerates every possible string key. The code examples below best demonstrate what I'm describing.

The definitions of a, f, and l below make me think Record<string, string> and Partial<Record<string, string>> are equivalent

The definitions of g and h below make me think Record<string, string> has a key for all values of string, which is directly contradicting the definition of a.

### 🔎 Search Terms

record string union
partial record string
partial record string error -> this finds a very unsatisfactory stackoverflow post: https://stackoverflow.com/questions/68494879/why-does-type-record-sometimes-complain-about-missing-keys-and-sometimes-not (it is relevant, but the answer isn't helpful)

### 🕗 Version & Regression Information

On the typescript playground, I attempted to and reproduced this on the following:
- 3.3.3333
- 4.4.4
- 4.9.3
- Nightly (v5.0.0-dev.20221202)

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Partial/Record

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.4#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCKhwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HUiQ58D0Ii8fLpDKZgj5SWxfPADlQAHJhAA5SASPlBFQAeS+ZHegmdWkgR1QjgUrmkeFATjNOmGWH0KAQiGhwkuNok4uiIgMHGxCyYrA4PCCJUUJQyCjIyQYSyqAG8xPkrqhKJwRgBfaWNKnT0CPSAIMjcAA8VPnzDsc+GAD4eaAJ4vQCpUO0NFv4r8ZTRpDPN9u95GGJHj4fz7yV43mAd5EOCZBsGQK6UjQsAzrQ+bstAu4fuKX4-n+Z4AZe163ve2CwE+0Frtw8GIQwyGoTu+4ngumELqe2FAXhRAPoRz6rjQkDvluaE0Ye9HMNhrgsSg3yQcRNDJDxn78cMgnYdIwFoPhj4cTBWhkWQ9QUShvHUd+v6zv+2HiKJbFES+oCYDJfGGQpF5mSBqnsZJIgzlUgG4c5YHieKbkAFZaTpyEVEx3kqaxBGWZxoDxMFSG7mFjnKaBW7Repa7QB5KWieBkFAA)

### 💻 Code

```ts
interface A { a: string }
const a: Record<string, string> = {} // typechecks
const b: Record<'a', string> = {} // type error
const c: Partial<Record<'a', string>> = {} // typechecks
const d: Partial<Record<string, string>> = {} // typechecks
const e: Record<string, string> = d // type error
const f: Record<string, string> = b // typechecks
const g: Partial<Record<'a', string>> = a // typechecks
const h: Record<'a', string> = a // typechecks
const i: A = {} // type error
const j: Partial<A> = {} // typechecks
const k: Partial<A> = a // typechecks
const l: A = a // type error
```

a, f, and l make me think Record<string, string> and Partial<Record<string, string>> are equivalent

g and h make me think Record<string, string> has a key for all values of string, which is directly contradicting a

### 🙁 Actual behavior

```ts
interface A { a: string }
const a: Record<string, string> = {} // typechecks
const b: Record<'a', string> = {} // type error
const c: Partial<Record<'a', string>> = {} // typechecks
const d: Partial<Record<string, string>> = {} // typechecks
const e: Record<string, string> = d // type error
const f: Record<string, string> = b // typechecks
const g: Partial<Record<'a', string>> = a // typechecks
const h: Record<'a', string> = a // typechecks
const i: A = {} // type error
const j: Partial<A> = {} // typechecks
const k: Partial<A> = a // typechecks
const l: A = a // type error
```

### 🙂 Expected behavior

If the correct behavior is Record<string, string> is equivalent to Partial<Record<string, string>>:
```ts
interface A { a: string }
const a: Record<string, string> = {} // typechecks
const b: Record<'a', string> = {} // type error
const c: Partial<Record<'a', string>> = {} // typechecks
const d: Partial<Record<string, string>> = {} // typechecks
const e: Record<string, string> = d // typechecks THIS IS DIFFERENT
const f: Record<string, string> = b // typechecks
const g: Partial<Record<'a', string>> = a // typechecks
const h: Record<'a', string> = a // type error THIS IS DIFFERENT
const i: A = {} // type error
const j: Partial<A> = {} // typechecks
const k: Partial<A> = a // type error THIS IS DIFFERENT
const l: A = a // type error
```

If the correct behavior is Record<string, string> is NOT equivalent to Partial<Record<string, string>> (where Record<string, any> enumerates all possible string keys of Record, which I think is a nonsensical interpretation):
```ts
interface A { a: string }
const a: Record<string, string> = {} // type error THIS IS DIFFERENT
const b: Record<'a', string> = {} // type error
const c: Partial<Record<'a', string>> = {} // typechecks
const d: Partial<Record<string, string>> = {} // typechecks
const e: Record<string, string> = d // type error
const f: Record<string, string> = b // type error THIS IS DIFFERENT
const g: Partial<Record<'a', string>> = a // typechecks
const h: Record<'a', string> = a // typechecks
const i: A = {} // type error
const j: Partial<A> = {} // typechecks
const k: Partial<A> = a // typechecks
const l: A = a // typechecks (or different type error) THIS IS DIFFERENT
```

**Comment by MartinJohns** [comment]
Don't think in terms of equivalence, it's about assignability. Also, TypeScripts type system is not completely sound. Sometimes due to a design limitation, sometimes intentional.

> const e: Record<string, string> = d // typechecks THIS IS DIFFERENT

`d` is an object where every value is either a `string` or `undefined`. You can't assign this to a type that says all values must always be `string`.

> const h: Record<'a', string> = a // type error THIS IS DIFFERENT

You have an object where arbitrary keys all have `string` values, but none of those keys must exist. You try to assign it to a variable that say "the key `"a"` must be of type `string`" - but your source object may not have such a key!

> const k: Partial<A> = a // type error THIS IS DIFFERENT

You have an object where every key has a value typed `string`, and assign it to a type where every value is either `string` or `undefined`. That's fine. Although unsound behaviour occurs when you modify your object via the partialled interface.
