### ISSUE TITLE
[Is it a bug?] Same type is evaluated differently

### ISSUE THREAD

**Issue by LuciNyan** [microsoft/TypeScript#51744]
# Bug Report

Why TS reminded the type of the last callback is `(parameter) callback: (key: never, value: never) => void`

### 🔎 Search Terms

forEach

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about forEach

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.3#code/C4TwDgpgBAwghgGwQIzgYwNYGcoF4oAUAsAFBSEEYQgBcUARAK4B2AThHACb0A0UAbokYQ6zRgFtkEVgEo8APgEB7AJac5AHwpVaDBEq4rmAc14ChIqMiVKEHZnNyL+q9aRkBtALqlSaJcxYwFBoiCjo2HTwSKiYOPjeviShMRFYAHQAZkqsAKLoABYEKeGYClAA3lAA9NWEYHCscOIQwNJyJbEYdAQEanRBrEbGfDp0TGwc3HyCCMKiElKy5S5qmhT9UIPDo9Tj+oYmZrPzVjZ2cA4rrjKk5J0RBADkB5zDT3wAjHK19Y3NrXaITCXR6m22Jl2umYEH40hmFlEsKBTmUalIAF8ZEA)

### 💻 Code

```ts
type Callbacks = (
  ((key: "unread", value: number) => void) | ((key: "loading", value: boolean) => void)
)[]

const callbacks: Callbacks = []

callbacks.forEach(callback => { // (parameter) callback: ((key: "unread", value: number) => void) | ((key: "loading", value: boolean) => void)
  callback('loading', true) // (parameter) callback: (key: never, value: never) => void
})
```

### 🙁 Actual behavior
![image](https://user-images.githubusercontent.com/22126563/205499518-331058d7-00d4-4e18-874e-85606987dfd2.png)

### 🙂 Expected behavior
```
type Callbacks = (
  ((key: "unread", value: number) => void) | ((key: "loading", value: boolean) => void)
)[]

const callbacks: Callbacks = []

callbacks.forEach(callback => { // (parameter) callback: ((key: "unread", value: number) => void) | ((key: "loading", value: boolean) => void)
  callback('loading', true) // (parameter) callback: ((key: "unread", value: number) => void) | ((key: "loading", value: boolean) => void)
})
```

**Comment by fatcerberus** [comment]
You have a union of two function types, you don't know which one you're actually calling, so the only `key` you can safety pass it is `"unread" & "loading"`, which of course is impossible, hence `never`.

**Comment by LuciNyan** [comment]
> You have a union of two function types, you don't know which one you're actually calling, so the only `key` you can safety pass it is `"unread" & "loading"`, which of course is impossible, hence `never`.

Thank you! @fatcerberus!
