### ISSUE TITLE
Objects constructed using spread have incorrect inferred types with optionals

### ISSUE THREAD

**Issue by Mike96Angelo** [microsoft/TypeScript#51755]
# Bug Report

### 🔎 Search Terms

- optional spread 

### 🕗 Version & Regression Information

Issue present v3.3.3333 through v5.0.0-dev.20221205 

- This is the behavior in every version I tried, and I could not find anything about it in the FAQ.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.3#code/MYewdgzgLgBATgUwI4FcCWiAmAuGBvGAQ12jjTAHMYBfGAXnyNwHIoFpmaAoUSWEAA5Q04QgBtcBQgH4SUMpRgAfGCjCYEAM3IJMNeo2Kr1WnXupce4aDEHDRYgGIYbDPFxgwAdD7siw4gA0Ht4+iKgYusEWAPQxMAB60oZyClS0lrwQIGIIXmIgFAAUfg7OcNAAlDBxjABEhHW4dWzQddxWfLZC-uIAMoSu+CE+XuHoWMGeo6UBYtFctUkpMKTk6TAARiiwEAAWIChiepsIhrKr8uvKxhraYLodWTl5BcWz-YNQ1bUEDU23UwPcxAA)

### 💻 Code

```ts
const required: { a: string } = { a: 'test' }
const optional: { a?: string | undefined } = { a: undefined }

const optionalFirst = {
  ...optional,
  ...required,
}
// ^? { a: string } Good

console.log(optionalFirst) // { "a": "test" }

const optionalLast = {
  ...required,
  ...optional,
}
// ^? { a: string } Bad -- Should be { a?: string | undefined }

console.log(optionalLast) // { "a": undefined }
```

### 🙁 Actual behavior

The inferred type of an object constructed using spread removes optional typing regardless of order

### 🙂 Expected behavior

The inferred type of an object constructed using spread should maintain optional properties that are in the last position

**Comment by MartinJohns** [comment]
This is solved by enabling the `exactOptionalPropertyTypes` compiler option.

**Comment by Mike96Angelo** [comment]
Is there a reason that isn't the default? It seems odd that one must choose not to have this bug.

**Comment by MartinJohns** [comment]
It was introduced later on and is quite a big breaking change, so it's not a default. The break was considered too big for it to be part of `strict` as well.

> It seems odd that one must choose not to have this bug.

It's technically not a bug, it's working as intended / a design limitation.

**Comment by Mike96Angelo** [comment]
Sure it works as it was first implemented (and thus became the design). I would still call it a bug or perhaps a design-flaw. However I understand that it would cause issues if it were fixed. Perhaps `exactOptionalPropertyTypes` could be set by default when starting a new project by using `tsc --init`?
