### ISSUE TITLE
NodeFlags.Ambient not declared

### ISSUE THREAD

**Issue by pierreglibert** [microsoft/TypeScript#51752]
Hi community :)

ts.NodeFlags.Ambient is not declared in node_modules/typescript/lib/typescript.d.ts file.
Is that a missing declaration ?

Thanks :)

**Comment by MartinJohns** [comment]
1. This repository is meant for bug reports and feature requests, not for general questions.
2. `NodeFlags.Ambient` is [marked as internal in the code](https://github.com/microsoft/TypeScript/blob/main/src/compiler/types.ts#L809), so it's explicitly omitted from the .d.ts file.
