### ISSUE TITLE
Nullish-coalescing assignment narrows type to assigned value

### ISSUE THREAD

**Issue by stwlam** [microsoft/TypeScript#51760]
# Bug Report

### 🔎 Search Terms

nullish, coalesce, coalescing, assignment

### 🕗 Version & Regression Information

- It appears to be present from 4.0 onward, when nullish coalescing assignment was introduced.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAEzgZSiYwAUqDyUAFgKYBOAKkTGAOYD8AXIgEZxwA2JAhmAJTMAbnBjJEAbwBQiGSjiFSlanUT16AXkRQyIEgG5J02TGCI884uSo1aidfcTBuHAM4k+ExAHoviQLwbgKU7iNYuiBBwALYADtxkMC4IiNxRUTxkoVBwrCSI4DRQJGCwCM7ZENwgblqkWgCeqaEA5Nq6jUlgYo1OriRtRNyCOWBZcINkHMkAdEaysuFgCVyTHHC0OABEEGS163wGswC+kkeSqBhYuN1ue0A)

### 💻 Code

```ts
function doStuff(doOtherThing?: boolean): void {
    doOtherThing ??= true;

    if (doOtherThing === false) { // 💥 This comparison appears to be unintentional because the types 'true' and 'false' have no overlap.
        console.log("cry");
    }
}

doStuff(false);
```

### 🙁 Actual behavior

Testing for a value other than the nullish-coalesced-assigned one throws a compilation error.

### 🙂 Expected behavior

No error thrown

**Comment by fatcerberus** [comment]
Thought this wasn't a bug at first but then I realized `false ?? true` is still `false`.  So I investigated a bit further out of curiosity, and it looks like it's incorrectly filtering out *all* falsy values, like `||=`:

```ts
let x: 0 | 1 | 2 | 3 = 0 as any;
x ??= 1;
console.log(x);
//          ^?
//             (1 | 2 | 3)
```
