### ISSUE TITLE
Add a Spread/Assign utility types -- Better type for Object.assign(), and spread type operator

### ISSUE THREAD

**Issue by Mike96Angelo** [microsoft/TypeScript#51761]
# lib Update Request

- OptionalKeys: Results in a union of keys that are defined as optional using `?:` syntax
- RequiredKeys: The inverse of OptionalKeys
- FlattenIntersection: Flattens an intersections. (e.g. `{ a: string } & { b: string }` becomes `{ a: string, b: string }`)
- Assign: Resulting type of applying types from left to right

[TypeScript Playground](https://www.typescriptlang.org/play?ts=4.9.3#code/PQKgBA8gDgLglgewHYEMA2BpApgTwM4A0YASlgI4CucATlgCbb5gjABQwwJWeFaMeYOEjAowFJImEIAZmADWuATAAWKGCNpg6WaUPoiBCWJPRi8QgOZgA-AC4weHEhgoAHqxg4oWSMeTpGPAAeABUAPjAAXjAAUVcAYzQKbSDWMDAAbzT0sABtDEFhBRwZMBCAXXsQsCxXGCwkOgFSeIRqOiCMIhD88ojrMCQsADcsajB7DABubIBfXOLSioJs8W1dIbpWMJn2ThDlHyFR6jwfUuh4f0xFDy8fUkoaekDQiOi4xOSsIMXZEKIlxMN3wbx2rHY4AAYmg1PUkABJZxjM7xK7CFh7MAwuENAQoYRCeqnLBoyR4AB0YAAFFgKRYqQADDIiex4GDUSxgWZgABkmTAACM2RyubNGULSQgALbcMDM1kOUVICxEYVKzkq7mMgCUd282NhMHhSOJqPRbyiZRqdQaTUK0jGYAAqtkBlkcjlcgAFQryXClZ2VF0+8ozT2zbJVXagMAAQTw5gsGLYHDAKjgAkzIjAhzQ3nG0ja8cTcGTYFavDoksKaD01cFFHUAHdOcaGunlNnmygcGAi+NEig2zh9T4APrjhNJpAAOVqMCCcfi8SI87q70NuMRyJJZOQqXSHpyaag1CMAmk5+l8ZXnbUGgaAHJ1EIwOuYNl0vk-X9INK4EXZdV39EpZA-MJg2A3pw25PlMi-MBT3PKBL2vd8F3vdRh2fV9hGAxCfzfP8IAAxcPyIP9gMg+wPxguZ4OPdI0yMdFTDPC9+3Qj8sLABATlhKAwA41CuJlW94kIgo3ziDkUDRX4A1kYDAT8VAQWCCDILsCTejAAAfDC6no9IeX5JikM4WgnloasRLQ8SeJUB9+LGQThJQhybwIz0iOEWTqHkxcqJXIhHioWzXi04M6IwMM5m2GNOFIHg+C5TwDVKFAoCgNAcHS+4vLANAdHUGAEDATkLGUT8Mp8acyyQJcbXhe0CRwXI+itOMWrtARciER1xmA8o3QkqN416xp+sGp0VIdJ0P1G9IBknBrkw-JdQqMmAwgmnqFz6vJZuG7aTp2ogKSu86UpgZabBLGcglyR7Gue+alrCS6rtuvoJqGE4Y3AdbhAoPAUAsHxMTq3w2LQCBBQAKytFkUB09lNSsSMYfC546AR5HolRkVMe5CEYaBa4oRodlutLZNnsp9SCbC8gIvoAm+hmNN0gAPWscn7lh4EABkUFp6IQee3HbJZ4Xrk58EebAfmISxSs0GrdA8Aq9Y9EgJHSRgClxZnMx0sOV7yybOA608dN7lsVgiTGaR5J8AmjYAYWQDGKDRYtj1Nt7qkO6bMlmIgAGUprapAOr6alEJcahIZgKoVk9K6KR1ihqHibh7Cj7IdXsKXcgBMBs6jrnWEjVhWiQWnWOBewmfQAmUcVNYdHrMnG9p6z2boewZY5pGu5QewX24GAnzJhvffUFuqZp9Rok9tETfppBqQySO+LU9AiCHvG9WVlWBYHhASopNAEAsakV-U6nThgHVLIFKewBn9l5-rgey8j5oDFhLA2iMjbbxnHvA+p9bJEGfugc+nAciq2vrfe+j9EEgPFu-T+xMxCNF7psbkQA)
## Sample Code

OptionalKeys, RequiredKeys:
```ts
// Results in a union of keys that are defined as optional using ?: syntax
type OptionalKeys<T> = Exclude<
  {
    [K in keyof T]: T extends Record<K, T[K]> ? never : K;
  }[keyof T],
  undefined
>;

// The inverse of OptionalKeys
type RequiredKeys<T> = Exclude<keyof T, OptionalKeys<T>>;
```

FlattenIntersection:
```ts
// Flattens an intersections. (e.g. `{ a: string } & { b: string }` becomes `{ a: string, b: string }`)
type FlattenIntersection<T> = T extends infer U
  ? {
      [P in keyof U]: U[P];
    }
  : T;
```

Assign:
```ts
// this is a helper for Assign could be inlined but written this way for clarity
type __AssignNext<Acc, Next> = FlattenIntersection<
  {
    // props from Acc that aren't in Next
    [K in Exclude<keyof Acc, keyof Next>]: Acc[K];
  } & {
    // optional props from Next that overlap props from Acc
    [K in Extract<keyof Acc, OptionalKeys<Next>>]?: Acc[K] | Next[K];
  } & {
    // required props from Next that overlap props from Acc
    [K in Extract<keyof Acc, RequiredKeys<Next>>]: Next[K];
  } & {
    // props from Next that aren't in Acc
    [K in Exclude<keyof Next, keyof Acc>]: Next[K];
  }
>;

// Resulting type of applying types from left to right
type Assign<A extends any[]> = A extends [infer Acc]
  ? Acc
  : A extends [infer Acc, infer Next]
  ? __AssignNext<Acc, Next>
  : A extends [infer Acc, infer Next, ...infer Rest]
  ? Assign<[ Assign<[Acc, Next]>, ...Rest]>
  : never;
```

Assign Usage:
```ts
type OptionalObj = { a?: string }
type RequiredObj = { a: string }

type OptionalFirst = Assign<[OptionalObj, RequiredObj]>;
//   ^? { a: string }

type OptionalLast = Assign<[RequiredObj, OptionalObj]>;
//   ^? { a?: string | undefined }


// could also define Object.assign using the Assign utility type:
interface ObjectConstructor {
  assign<T extends {}, S extends any[]>(
    target: T,
    ...sources: S
  ): Assign<[T, ...S]>;
}

const optional: OptionalObj = { a: undefined }
const required: RequiredObj = { a: 'test' }

const optionalFirst = Object.assign({}, optional, required)
//    ^? { a: string }
console.log(optionalFirst) // { a: 'test' }

const optionalLast = Object.assign({}, required, optional)
//    ^? { a?: string | undefined }
console.log(optionalLast) // { a: undefined }
```

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388:

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.

**Comment by Mike96Angelo** [comment]
I think this is a bit different in that it greatly improves the types for `Object.assign`

**Comment by MartinJohns** [comment]
For `Object.assign` see this comment and the linked issues: https://github.com/microsoft/TypeScript/issues/45215#issuecomment-888346586

**Comment by Mike96Angelo** [comment]
The Assign utility type I've provided here fixes the issue found: https://github.com/microsoft/TypeScript/issues/45215#issuecomment-888346586. I think that this proposal is worth consideration

**Comment by RyanCavanaugh** [comment]
Please consider it considered. We don't add utility types to the lib, and don't really want to mess with `Object.assign`'s type unless it's to adopt a proper spread type operator should that feature ever come to pass.

**Comment by Mike96Angelo** [comment]
> We don't add utility types to the lib

https://www.typescriptlang.org/docs/handbook/utility-types.html ?

The spread type operator is a neat Idea
```ts
type A = { a: string; };
type B = { b?: number ; };

type AB = { ...A; ...B; };
//   ^? { a: string; b?: number; }
```

My `__AssignNext<Acc, Next>` type though poorly named is logically equivalent to `{ ...Acc; ...Next; }`
Perhaps a better proposal would be to add a single utility type `Spread`
```ts
type OptionalKeys<T> = Exclude<
  {
    [K in keyof T]: T extends Record<K, T[K]> ? never : K;
  }[keyof T],
  undefined
>;

type RequiredKeys<T> = Exclude<keyof T, OptionalKeys<T>>;

type Spread<A extends any[]> = A extends [infer Acc, infer Next]
  ? {
      // props from Acc that aren't in Next
      [K in keyof Omit<Acc, keyof Next>]: Acc[K];
    } & {
      // props from Next that aren't in Acc
      [K in keyof Omit<Next, keyof Acc>]: Next[K];
    } & {
      // optional props from Next that overlap props from Acc
      [K in Extract<keyof Acc, OptionalKeys<Next>>]?: Acc[K] | Next[K];
    } & {
      // required props from Next that overlap props from Acc
      [K in Extract<keyof Acc, RequiredKeys<Next>>]: Next[K];
    } extends infer U
    ? {
        [P in keyof U]: U[P];
      }
    : never
  : A extends [infer Acc, infer Next, ...infer Rest]
  ? Spread<[Spread<[Acc, Next]>, ...Rest]>
  : never;
```

When/if **proper type spread operator** becomes a feature, we could replace
```ts
{
  // props from Acc that aren't in Next
  [K in keyof Omit<Acc, keyof Next>]: Acc[K];
} & {
  // props from Next that aren't in Acc
  [K in keyof Omit<Next, keyof Acc>]: Next[K];
} & {
  // optional props from Next that overlap props from Acc
  [K in Extract<keyof Acc, OptionalKeys<Next>>]?: Acc[K] | Next[K];
} & {
  // required props from Next that overlap props from Acc
  [K in Extract<keyof Acc, RequiredKeys<Next>>]: Next[K];
} extends infer U
  ? {
      [P in keyof U]: U[P];
    }
  : never;
```
with
```ts
{ ...Acc; ...Next; }
```
Making the `Spread` utility type:
```ts
type Spread<A extends any[]> = A extends [infer Acc, infer Next]
  ? { ...Acc; ...Next; }
  : A extends [infer Acc, infer Next, ...infer Rest]
  ? Spread<[Spread<[Acc, Next]>, ...Rest]>
  : never;
``` 

If **proper spread type operator** was a thing, I still think the `Spread` utility type would make for better typing for `Object.assign`
```ts
interface ObjectConstructor {
  assign<T extends {}, S extends any[]>(target: T, ...sources: S): Spread<[T, ...S]>;
}
```
instead of
```ts
interface ObjectConstructor {
  assign<T extends {}, S1>(target: T, s1: S1): { ...T; ...S1; };
  assign<T extends {}, S1, S2>(target: T, s1: S1, s2: S2): { ...T; ...S1; ...S2; };
  assign<T extends {}, S1, S2, S3>(target: T, s1: S1, s2: S2, s3: S3): { ...T; ...S1; ...S2; ...S3; };
  assign(target: object, ...sources: any[]): any;
}
```

Using `Spread` utility type gives us correct types for any number of argument where as just using **proper type spread operator** only gives correct types for some arbitrary length of arguments.
