### ISSUE TITLE
Type of readonly fields should be narrorwed in closure within narrowing if-check

### ISSUE THREAD

**Issue by upsuper** [microsoft/TypeScript#51773]
# Bug Report

### 🔎 Search Terms

readonly narrow closure lambda

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about classes and type guards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PWPAdhALgE4Cuw+8hAFOprQA6ECWAbmPgKbSHtgAmuIAJ7QAZogBc0AkxwBzaAB9oxHL3YjGOdrwA0NDAEoUAX1T7o-SkbS1ajEdEr4AFowgA6MUgCEAXmg4xCAg1ua2mNz4xIQ4jka+AHzQLm6eiO4QIIzA7JQADAYA3GGYpuEYLoTwAO4B7LUAooRVVEXmpsZAA)

### 💻 Code

```ts
class Foo {
    constructor(
        private readonly foo: string | undefined,
    ) {}

    do() {
        if (this.foo != null) {
            return () => this.foo.slice(0);
        }
        throw new Error();
    }
}
```

### 🙁 Actual behavior

`this.foo.slice(0)` reports error:
> Object is possibly 'undefined'.

however, since `foo` is a `readonly` field, it can't be `undefined` at this point, so it should be accepted.

### 🙂 Expected behavior

The code should compile without errors.

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/issues/50839#issuecomment-1251390252

**Comment by upsuper** [comment]
Does that case apply to private readonly?

**Comment by RyanCavanaugh** [comment]
Yes.

**Comment by fatcerberus** [comment]
Also falls under #9998 since there's an arrow function involved; in general, type narrowings aren't preserved across function boundaries.
