### ISSUE TITLE
Multiple post exclamation marks (`variable!!!`) do not occure any compile error

### ISSUE THREAD

**Issue by samchon** [microsoft/TypeScript#51776]
A post exclamation mark is used for explicit declaration of non-nullable type.

However, when the post exclamation mark being used over twice, there not be any compile error.

I can't sure it whether bug or spec. If it's a bug, hope to be fixed.

```typescript
const nullable: number | null = null;
console.log(
    "No errors",
    nullable!,
    nullable!!,
    nullable!!!,
    nullable!!!!
);
```

**Comment by fatcerberus** [comment]
`x!` basically means `x as Exclude<typeof x, null | undefined>`.  So `nullable!!` is just `(nullable!)!` and there's no reason for that to be an error.
