### ISSUE TITLE
Import assertions are only supported when the '--module' option is set to 'esnext' or 'nodenext'.

### ISSUE THREAD

**Issue by jwalton** [microsoft/TypeScript#51783]
# Bug Report

I'm trying to build a library as both a an ESM library and a CJS library.  In my code, I import a .json file.  When I tried to use the resulting ESM library in node 18, though, I get:

```
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///.../my-private-library/lib-esm/file.json" needs an import assertion of type "json"
```

Ok, no problem, I'll add the import assertion.  But now my CJS build fails with:

```
src/index.ts:10:58 - error TS2821: Import assertions are only supported when the '--module' option is set to 'esnext' or 'nodenext'.
```

At the moment, there seems to be no way to write valid typescript that imports a json file and will compile to both CJS and ESM.

### 🔎 Search Terms

import assertions commonjs cjs 

### 🕗 Version & Regression Information

Typescript v4.9.3.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?module=1#code/JYWwDg9gTgLgBAKjgQwM5zAawOZwGZQQhwDkAdAPRjIDGmy2ApmQFaoQB2JKqqjscAN5wYATzCMAXKTaduAXwDcQA)

### 💻 Code

```ts
import * as pkg from './package.json' assert { type: 'json' };
```

### 🙁 Actual behavior

tsc fails to compile this file.

### 🙂 Expected behavior

tsc should remove import assertions when compiling down to commonjs.  Commonjs doesn't support import assertions... but it doesn't support imports either, and we transpile those.  :P

Note that import assertions are largely not needed in commonjs.  It should be safe to just strip them out.  In ESM they [solve a security problem](https://github.com/tc39/proposal-import-assertions#motivation); if I `import 'https://example.com/foo.json'`, then example.com could malicously send me a "foo.json" with a "text/javascript" mimetype, and this gives them the opportunity to run arbitrary code when I'm expecting a plain json file.  But this isn't so much a problem in commonjs, since we can't `require` a URL in the first place.  In the node.js case specifically, node.js will also infer the content type from the extension, so if you try to `require('foo.json')` and foo.json is actually a javascript file, you'll get a SyntaxError.

**Comment by RyanCavanaugh** [comment]
Having the same codebase build to both CJS and ESM targets isn't in scope for us - a bundler step should be used instead.

**Comment by jwalton** [comment]
Typescript already transpiles imports to cjs.  Why draw the line at only some imports?

**Comment by RyanCavanaugh** [comment]
I don't understand the question. You can write code that targets CJS (in which case import assertions don't make sense). You can write code that targets ESM (in which case, import assertions are OK). Having some set of rules that tries to rationalize what an import assertion means when taking ESM code and producing CJS is outside the scope of the project; you'll need to use a different tool for that.

**Comment by fatcerberus** [comment]
@RyanCavanaugh The way I’ve read the issue it seems like the problem is that importing JSON files doesn’t work *at all* when targeting CommonJS, because TS demands an import assertion—which then raises an error that import assertions are illegal when targeting CommonJS.  So it’s a catch-22 situation.

**Comment by RyanCavanaugh** [comment]
`ERR_IMPORT_ASSERTION_TYPE_MISSING` is a node error, not a TS error.

**Comment by jwalton** [comment]
> I don't understand the question. You can write code that targets CJS (in which case import assertions don't make sense). You can write code that targets ESM (in which case, import assertions are OK). 

Well, sure.   But you can take that to it's logical conclusion which is that if you're targeting CJS, you can't write import statements at all, since CJS doesn't support import statements.  It seems very strange to me that tsc would transpile some imports but not others.  It seems like a very arbitrary place to draw a line.  But, if this is the position the tsc team is taking, then who am I to argue?  :)

If anyone else finds their way here and is looking for a workaround, [swc](https://swc.rs/) strips import assertions when transpiling typescript to CJS.

**Comment by RyanCavanaugh** [comment]
> you can't write import statements at all, since CJS doesn't support import statements.

We've seriously discussed banning this (under a new flag which would be recommended to everyone), actually. I think it was a mistake to allow this.
