### ISSUE TITLE
TS checks on jsx file

### ISSUE THREAD

**Issue by hieutranagi47** [microsoft/TypeScript#51805]
Type: <b>Bug</b>

I got this error hint on jsx file: Property 'instanceId' does not exist on type 'never'.ts(2339)

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (6.84GB free)|
|Process Argv|--crash-reporter-id 75e6461c-8ec0-468f-8325-599b80dbe0d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-javascript-snippet-pack|aka|0.1.6
jest-snippets|and|1.9.1
ng-template|Ang|15.0.2
angulardoc-vscode|Ang|6.1.3
atlascode|atl|2.10.12
vscode-python-docstring|aza|0.0.5
htmltagwrap|bra|0.0.7
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.3
path-intellisense|chr|2.8.3
vscode-ipaddress|Com|1.0.0
auto-header|Dan|1.0.1
dart-code|Dar|3.54.1
flutter|Dar|3.54.0
vscode-eslint|dba|2.2.6
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
vscode-go-syntax|dun|0.0.18
gitlens|eam|13.1.1
prettier-vscode|esb|9.10.3
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
go|gol|0.36.0
vscode-graphql|Gra|0.8.4
vscode-graphql-execution|Gra|0.1.6
vscode-graphql-syntax|Gra|1.0.5
todo-tree|Gru|0.0.220
kubernetes-snippets|ipe|0.1.9
search-node-modules|jas|1.3.0
Angular2|joh|13.0.0
solidity|Jua|0.0.141
vsc-python-indent|Kev|1.18.0
ng-bootstrap-snippets|ktr|1.0.0
angularjs-ngdoc-generator|Lui|0.1.4
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.36
code-beautifier|mic|2.3.3
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.23.1
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.40
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
makefile-tools|ms-|0.6.0
vsliveshare|ms-|1.0.5783
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
autodocstring|njp|0.6.1
nodejs|Pra|1.2.0
vscode-yaml|red|1.10.1
datetime|rid|2.2.2
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.1.1
solid-snippets|sol|0.1.3
python-extended-snippets|tus|0.0.1
lorem-ipsum|Tyr|1.3.1
vscode-icons|vsc|12.0.1
vscode-todo-highlight|way|1.0.5
vscode-nextjs-snippets|wil|0.3.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by mjbvz** [comment]
Thanks.

This is caused by the call:

```js
  const [tdata, setTdata] = useState([]);
```

There is no way for us to infer what the type of the array is in this case, so it defaults to `never[]`. This causes the error 

To fix this, you can provide a type using a JSDoc comment:

```ts
  const [tdata, setTdata] = useState(/** @type {YourTypeHere[]}*/ ([]));
```

**Comment by hieutranagi47** [comment]
Thank you so much for the info!
