### ISSUE TITLE
Boolean being passed as generic starts to extend both true and false

### ISSUE THREAD

**Issue by tech-meppem** [microsoft/TypeScript#51822]
# Bug Report

### 🔎 Search Terms

boolean, generic, true, false, opposite

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 4.9.4 & 5.0.0-dev.20221208

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAag6gCwgOwCoCcCuEA8qA0sAfFALxSpQQAewKAJgM5TBbQD8sUAXFMhADcI6ANwBYAFChIsRCgBiAQwA2jXAWJkKVWg2YAzFWqicYPPoOHiJkgPS2o6CI0zLgzAJbIoAcn5D0H0IAdwQPAGMEKA9mRWYaSHC6eklpaDpGYABGLQAjAHt85QhFbxo6ZCYWNhMoTPQvAHNzfytU8HTnYAAmPMLi0p0KqsNVDjrWJpbLUUk7BycXN09vH3qmoKhQiKiYqHywMHzGDzooOKhciH18p0JLb2AEfMxG3eA1liQ6xQBbaEiEHCAGsAHTtGQZYAAZi08CQaDYOAKRRKyEI62QjSI1jSLC6ABY4XJkEoxsj+miMZMsTigA)

### 💻 Code

```ts
type VWhenTrue<T, V> = T extends true ? V : never;
type VWhenFalse<T, V> = T extends false ? V : never;

// results in 'never', which is as expected.
type test1 = boolean extends true ? string : never;
type test2 = boolean extends false ? string : never;

// results in 'string', which is opposite as before, even though it's the same check.
type test3 = VWhenTrue<boolean, string>;
type test4 = VWhenFalse<boolean, string>;
```

### 🙁 Actual behavior

boolean being passed as a generic starts to extend both true & false, whereas when inline, it extends neither.

### 🙂 Expected behavior

boolean should not extend either true or false, because true & false both extend boolean already.
inline this works as expected, but when passing through as a generic, it breaks.

**Comment by RyanCavanaugh** [comment]
`boolean` is an alias for `true | false`, so in a distributive conditional type it is distributed.

**Comment by tech-meppem** [comment]
> `boolean` is an alias for `true | false`, so in a distributive conditional type it is distributed.

So is there a way that you check that T is true, but not boolean?

**Comment by RyanCavanaugh** [comment]
> So is there a way that you check that T is true, but not boolean?

`[T] extends [true] ? V : never`

**Comment by TGlide** [comment]
I really don't think this makes sense. It showcases contradicting behaviour.

![image](https://github.com/microsoft/TypeScript/assets/26071571/ddefa888-c046-4b62-8806-8da8884a0805)

**Comment by alissawix** [comment]
it seems the issue is with union types in general:

```
type Simple = 'a' | 'b' extends 'a' ? true : false; // false
type Generic<A, B> = A extends B ? true : false;

type Test = Generic<'a' | 'b', 'a'>;     //boolean (true | false)
type Other = Generic<string, 'a'>;    //false
```

I don't understand the idea behind this behavior
