### ISSUE TITLE
Generic type doesn't infer correctly without number type in function

### ISSUE THREAD

**Issue by wbolduc** [microsoft/TypeScript#51826]
# Bug Report
number annotation is required despite typescript correctly identifying that same type

### 🕗 Version & Regression Information
- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221208#code/JYOwLgpgTgZghgYwgAgIoFdoE8AyB7OAE1AHNkBvAKAEhgBnAZXQSTroC5l4AbOiAbhqE4YOJ3QhCEGKAiFBAX0qhIsRCgzZ8ROQB4AKgD4KNekxYQ2nMFEyDqw0Z32LKYLAAcUAVT6aoWABKlujcYAbGALxomAHaUoQRyAA+MVoExCAkgsrg0PBIyPoAFqQmtIScIOgAtgBG0PYgcDUQnHQ2pPZSdAhQwB5gwHgg7Z1ZrggjHcjofADiEGAlZdEAFMCVyNX10Cnbodz7ElIyIHIAlJy+EP5BIWEGpVlRhqaENNQA-OXUf2bMVgcZA2TAAGk+f0cYgoyE2YO2LTayAARPAANYoZqtFEInp9AZDEacNFwTHIfH9QbDEAo5AKCF-ZD0z6cchwxiAyzAnh8PEiGEnaSyQj0nIAeklyA8UCWEEkILwyAayFliDAAEdYlhkAA9XWUXKqAooABySIAkqKqBUqrUGlAmkixv0JpQlCp8upkAB1CDAKCEYKSaDQAAKUDwHjoBmQEAAHpBJHRkObWlaEQAxYAQbiENMoBNJwgpzFYPAwIrGG2bO27R00OYQRZgVScDZbHYOi7ISLGG53YJ0ULhIz2GS5wgAfWxyOzk4L9llIag7YAbnBuJhnABted5gsAXR7feQHVd2XdhqmIBmAHd-YHg1JZVBe8hY0X5SXU5bCFmcwPJE40Tb9SwgctKyMNYa3-RsFiWVRGQnPMZyRRllxfCEFE4P0AyDb9QygCMoxjfQAIXJFDBPasaBvGZ2WhBEAQsNh6XfJsW1UDsLiXJZ0CgEAOXMIFkB+TDoDWaEdxQ6dZ2PZA7W4bhFByBMPDwKAwGQejtIAQXfNYaJoB98OfIiYM+WtkAARkZahOMQ6B22AKcWjcmd7Wcg56xo2YEOWZ4SA2Nyag8rtoAueypWZWK4vihLEt1X1ih1Qg8EsOFtL4CAamQbhgHJAByCKoCKjlVQgLUAzkZBilDRVkBIJYQXqkFPEysAlTvTT0U+WS0NaElKUJGlcU+CTV2QNYNy3CA-NmzAADouoYcZgqimgFF4w11M07TdOQAAhQzjOoUyn0I19LP+LY7M+RzW28kL3LgTzfN7YxHpWLIXrCt7Ss2v4YsShLdS+frALk51URG6kRnGv5JvXTdMAW1GIBWvA1ovIzGW2tT4w0rSdOmbSAGFTs+kzHwIldJJtW1bPsx62385slh+kh7IG2dhssAl4dpezkemxb5s+5BxaxnHSDxradqAA)

### 💻 Code

```ts
interface QueryLoading {
	isSuccess: false;
	data: undefined;
}
interface QueryLoaded<T> {
	isSuccess: true;
	data: T;
}
type UseQueryResult<T> = QueryLoaded<T> | QueryLoading;

interface Thing {
	id: number;
	name: string;
	description: string;
}
const useGetThing = (id: number | null | undefined): UseQueryResult<Thing> =>
	id
		? {
				isSuccess: true,
				data: { id, name: "fake name", description: "fake description" },
		  }
		: { isSuccess: false, data: undefined };

/// pretend to be reactquery ^^

interface NameId {
	id: number;
	name: string;
}
interface WeirdRendererProps<T extends NameId, FieldName extends keyof T> {
	id: number;
	useGetter: (id: number) => UseQueryResult<T>;
	field_name: FieldName;
	render: (value: T[FieldName]) => string;
}

const weirdRenderer = <T extends NameId, FieldName extends keyof T>({
	id,
	useGetter,
	field_name,
	render,
}: WeirdRendererProps<T, FieldName>) => {
	const { data, isSuccess } = useGetter(id);
	return isSuccess ? render(data[field_name]) : null;
};

export const A = () =>
	weirdRenderer({
		id: 1,
		useGetter: (i_am_a_number: number) => useGetThing(i_am_a_number),
		//                            ^ Why does it seem like 'number' is required here to get the types to work
		field_name: "description",
		render: (value) => value.toString(),
	});

export const B = () =>
	weirdRenderer({
		id: 1,
		useGetter: (i_am_a_number) => useGetThing(i_am_a_number),
		//               ^?
		field_name: "description",
		render: (value) => value.toString(),
	});

export const C = () =>
	weirdRenderer({
		id: 1,
		useGetter: useGetThing,
		field_name: "description",
		render: (value) => value.toString(),
	});
```

### 🙁 Actual behavior

typescript is throwing an error off of the generic

### 🙂 Expected behavior

If typescript can correctly identify the type of the function arguments it should make no difference if I manually add or remove that annotation

**Comment by RyanCavanaugh** [comment]
The order of inference that would be needed here -- first check the return type of `useGetThing`, then check `field_name`, then figure out `render`'s parameter type -- is pretty far off from a supported ordering of inference steps. See #30134

**Comment by wbolduc** [comment]
What I don't understand here though is that in the playground it looks like ts is correctly identifying it as a number. If it can give me the intelisense on what that value should be why does it matter if I do or do not specify it explictily

**Comment by RyanCavanaugh** [comment]
Intellisense doesn't compute the entire type flow of the program -- instead, it tries to compute the minimum amount possible so that results can come back faster. In some cases like this, these shortcuts can produce slightly inaccurate results compared to what would be produced from a proper inference.
