### ISSUE TITLE
infer type assertion instead of boolean from "typeof" comparisons

### ISSUE THREAD

**Issue by danielrentz** [microsoft/TypeScript#51835]
# Suggestion

## 🔍 Search Terms

infer type assertion typeof comparison

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
_I am not sure abot this point, it may break some code..._
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

- The type of expressions `typeof x === "<type>"` will be inferred as `x is <type>` instead of `boolean` (`x is Function` for "function"; maybe `x is object | null` for "object"?).
- Type of expressions `x instanceof Class` will be inferred as `x is Class` instead of `boolean`.

## 📃 Motivating Example

Doing this would change the return type of custom type assertion functions, which in turn would help filtering arrays for specific type.

before:
```ts
const arr1: any[] = [];
const arr2 = arr1.filter(x => typeof x === "string"); // any[]
```

after:
```ts
const arr1: any[] = [];
const arr2 = arr1.filter(x => typeof x === "string"); // string[]
```

## 💻 Use Cases

Workaround is adding the type assertion manually:

```ts
const arr1: any[] = [];
const arr2 = arr1.filter((x): x is string => typeof x === "string"); // string[]
```

**Comment by MartinJohns** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/38390.

**Comment by danielrentz** [comment]
Thanks, must have slipped while searching with different terms through multiple pages of matches.
