### ISSUE TITLE
Suggestion: class Foo static implements FooStaticInterface

### ISSUE THREAD

**Issue by ajvincent** [microsoft/TypeScript#51833]
# Suggestion

I would really like to get type checking of static members up front:
```typescript
class Vehicle 
static implements VehicleTypeStatic
implements VehicleType
extends SomeOtherClass
{
// ...
}
```

## 🔍 Search Terms

is:issue static implements label:Suggestion 

Possible duplicates:
- https://github.com/microsoft/TypeScript/issues/1263
- https://github.com/microsoft/TypeScript/issues/17545
- https://github.com/microsoft/TypeScript/issues/27899

## ✅ Viability Checklist

I believe this is safe, as it would be new type-only syntax. Currently, the TypeScript compiler would treat it as a syntax error.

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add a static implements keyword pairing to specify a class's static members combine to implement a particular interface.  It could be the other way around:

```typescript
class Vehicle
implements VehicleType, static VehicleTypeStatic, static SomeOtherStaticInterface 
extends SomeBaseClass
```

## 📃 Motivating Example

https://github.com/microsoft/TypeScript-Website/pull/2636

I can directly use the `implements` clause to enforce the type contract on _instances_ of a class, but the class syntax gives no direct way to enforce a type contract on the _static members_ of the class.  The best we can currently do is to declare a short-lived constant embedded in the class:

```typescript
interface VehicleType {
  manufacturer: string
}

interface VehicleTypeStatic {
  readonly wheelCount: number;
}

class Vehicle implements VehicleType 
{
  static {
    const temp: VehicleTypeStatic = Vehicle;
    void(temp);
  }

  readonly manufacturer: string;

  constructor(maker: string) {
    this.manufacturer = maker;
  }

  static readonly wheelCount = 4;
}
```

This leaves behind a _little_ bit of run-time code, though, to enforce the type contract.  In particular, this constraint appears in neither the generated `.d.ts` or `.js` files.

## 💻 Use Cases

This really has only one: defining the type which a class must implement for its static members.

**Comment by ajvincent** [comment]
If the project management approves one of my ideas above, I could try to implement this... but no guarantees.

**Comment by jcalz** [comment]
Duplicate of #33892

**Comment by ajvincent** [comment]
So it is.
