### ISSUE TITLE
No JSX attributes snippets after curly

### ISSUE THREAD

**Issue by zardoy** [microsoft/TypeScript#51845]
# Bug Report

### 🔎 Search Terms

React, JSX attributes snippets, VSCode VS Code

### 🕗 Version & Regression Information

4.9

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[provided](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gJRFMGAXPFCgJ4DcAUFSlALYhoAO+CAUgMoAa8A3lXhD4IAB7MkMLAEsUGEDABmbeAEk5MWWmlgAohBCM5afoOHng0gG7FSlM0IC+VZ1UUBXFAWmp4nJIz6hgAUzDBIzGjEfIpISAD8xJiaKADmADTwomQAXonwybKpjgCUpuZwGO4wKPAAPAB8dQD0DS40Hl4YPrWKKACMwWUCFSBVNfWWVm3m5nX+gQb08LFIALwARBvwrQ71zVNtrp3evn0ATEPlwpXVtY17cwsgQcura3xbjjszwi1HVCAA)

### 💻 Code

1. `npm i @types/react`
2. jsx file: `;<span title={''} about| />` | - cursor position

### 🙁 Actual behavior

Completion without insert snippet.

### 🙂 Expected behavior

Completion with snippet like in following cases:

```jsx
;<span title={''} | /> // about completion with snippet
;<span title='' about| />
```

**Comment by RyanCavanaugh** [comment]
I'm not seeing what problem you're describing - everything I try seems to work according to my expectation. At the indicated `|`, what key are you pressing and what are you expecting to happen?

**Comment by zardoy** [comment]
Thank you so much for looking into that!

>I'm not seeing what problem you're describing - everything I try seems to work according to my expectation

@RyanCavanaugh can you please look at linked PR fixing it (#51855), I've added [failing tests](https://github.com/microsoft/TypeScript/pull/51855/files#diff-aaa26e38d74e8ef4a3bb5e5377bffd819a4db50e1b79cf6ec510e1675ed5b932). For example:

```tsx
;<Foo something={false} cla/*14*/ foo />
```

Should be completed with `className={$1}` and not just `className` when `preferences.jsxAttributeCompletionStyle` is "braces" or "auto"

**Comment by RyanCavanaugh** [comment]
I see; I was missing that you were specifically expecting the braces. Makes sense
