### ISSUE TITLE
Javascript object literal string values are collapsed to string type

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#51849]
# Bug Report

### 🔎 Search Terms

Javascript, object, literal, literal string, collapse

### 🕗 Version & Regression Information

4.9.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?filetype=js#code/PTAEFMCdIe0goAxjAdgZwC6gGYxqAXlAG95RQMBPAB3AC5QByAcQFEAVRgGjNAFdIAGwaNcMAHTIAtt3gBfeEgCGgwewAWASzQAKHHlABKANyKQoFPiiwEiFWq26SvKrRFtOPcgOFMxkmBkeORMzACowsjDQAAFqJUglKRJiV3omD0YAH0YABQB5AGVOY34hBkxITRQAczk5fRgo4HhsPhREDE1UUDtVDW09MSNneXggA)

### 💻 Code

```js
// error
const foo = {
  type: 'GET',
  url: 'foo.com',
}

callThis( foo );

// no error
callThis( {
  type: 'GET',
  url: 'foo.com',
});

/**
 * @param {{type: 'GET'|'POST'; url: string}} foo
 */
function callThis( foo ) {

}
```

### 🙁 Actual behavior

JS object is collapsed with literal strings to string type

### 🙂 Expected behavior

Don't collapse literal strings in Javascript objects

**Comment by MartinJohns** [comment]
This is working as intended, and changing this behaviour would be a massive breaking change.

You can get the behaviour you want by using a `const`-context. This is the intended way.

In TypeScript you'd just add `as const`, and in JavaScript you can use JSDoc for it:
```javascript
const foo = /** @type {const} */ ({
  type: 'GET',
  url: 'foo.com',
})
```
