### ISSUE TITLE
JSDoc comment inheritance of class property types

### ISSUE THREAD

**Issue by hdodov** [microsoft/TypeScript#51848]
# Suggestion

## 🔍 Search Terms

VSCode IntelliSense autocomplete property hover documentation inheritance propagation from class object property member type annotation JSDoc comment

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I believe it's extremely helpful for productivity when developers don't have to leave their IDE for documentation and could just hover something and see everything about it through the power of TypeScript and JSDoc.

The problem is that class members and function parameters may refer to the same thing, but don't use the same JSDoc annotations. This leads to either library authors having to copy-paste the comments, or users not being able to see them in some circumstances.

## 📃 Motivating Example

Let's say I have class `Test` with a documented property `foo`:

```ts
class Test {
  /**
   * It does foo things!
   */
  public foo: string;
}

let test = new Test()

test.foo
```

I can hover `test.foo` and see what it does:

![image](https://user-images.githubusercontent.com/5570098/206852698-d557040c-14e7-44b4-aa23-8cefac5aba04.png)

However, `foo` must gets its value from somewhere, so suppose I have an `options` object in the constructor where that value is provided:

```ts
class Test {
  /**
   * It does foo things!
   */
  public foo: string;

  constructor(options: {
    foo: Test['foo']
  }) {
    this.foo = options.foo
  }
}

let test = new Test({
  foo: 'hello'
})
```

Sadly, hovering `foo: 'hello'` doesn't display the comment:

![image](https://user-images.githubusercontent.com/5570098/206854201-db7f7781-84d6-47a7-a39b-9b513cb2bfe7.png)

My expectation is that when I specify that something is of type `Test['foo']`, it should inherit the comments associated with it. The only exception should be when I explicitly provide a separate comment:

```ts
constructor(options: {
  /**
   * This takes precedence.
   */
  foo: Test['foo']
})
```

## 💻 Use Cases

I want to use this for documenting my code for other people.

Currently, to achieve what I want, I need to copy-paste the comment in both places:

```ts
class Test {
  /**
   * It does foo things!
   */
  public foo: string;

  constructor(options: {
    /**
     * It does foo things!
     */
    foo: Test['foo']
  }) {
    this.foo = options.foo
  }
}
```

This is bad for maintenance and if you have a few more properties to document, it could hurt readability as well.

Maybe a downside of what I'm proposing is that I'd be forced to use `Test['foo']` as my type, if I wanted the comment to appear. This would make the constructor popup confusing:

![image](https://user-images.githubusercontent.com/5570098/206853642-cf4dc5e9-843c-403c-a15c-a83b907aa3a5.png)

---

So perhaps the best solution is somewhere in the middle - have a special JSDoc annotation, e.g. `@show`, that allows you to "attach" a comment from an existing type:

```ts
class Test {
  /**
   * It does foo things!
   */
  public foo: string;

  constructor(options: {
    /** @show {Test['foo']} */
    foo: string
  }) {
    this.foo = options.foo
  }
}
```

This way, whenever I want the comment to appear, I just add `/** @show {Test['foo']} */` above whatever I want to document. I can greatly improve the developer experience of everyone who uses this code, while not being forced to alter my type annotations.

Here's a [playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAu0DeBYAUNaB6AVPljtPtAJIoAmA9otAGY03RIAWAlgHYDmEAhMRz5cQgA4BXAEYgOwRswBc0ZACduPANxYhwGlzUTgSGqoAUNMUg76IyjNhJMayhMgDaAcmeeAukIBfAEo0IRx2DggAOmdoAF5oS2tbGOZArACdTBB4FCREFASueAB3OAKzBxxcXGgAORY9AFsm+C4UfWg2GgA3eFVFIWdlTzZ4EBAaTwygrJroAAlIaGbW9sSuLt7+wcx85FSaIA) to see the issue in action.

**Comment by andrewbranch** [comment]
why not

```ts
constructor(options: Pick<Test, 'foo'>) { /* ... */ }
```

the documentation is attached to the property, not the type, so to me the behavior kind of makes sense. If you make your `options` property something that is pulled directly off the source, rather than a new property with no documentation whose _type_ is copied from somewhere else, the documentation is pulled from the source too.

**Comment by hdodov** [comment]
Hm, I didn't know that `Pick` worked like that. It appears to do exactly what I want. Here's a [playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAu0DeBYAUNaB6AVPljtPtAJIoAmA9otAGY03RIAWAlgHYDmEAhMRz5cQgA4BXAEYgOwRswBc0ZACduPANxChBItmEVqdGFLCrWnXgKGlRByTLnQzq5VwkBbKfFXbMQsA0XGoSwEg0qgAUNGJIHMEQygAKcgDWADwIyAA00ADkTDT50AA+Ba75AHwAlGi2lhwQAHRF0AC80LHxia3MDexNza4dXXEJIcPmQgC+WHMBmCDwKEiIKJ1c8ADucOtRGAa4uNAAEpDQQZ6e8FwogKDkQkXK+WzwICDFOUKuygAsACZ5jUsFhjmcLlcbndoI9MGtkH0aEA) for anyone else wondering.

If you want to copy the type of a property, along with the documentation, use `Pick`. ✔️
