### ISSUE TITLE
`Type.isRestType()` function is required

### ISSUE THREAD

**Issue by samchon** [microsoft/TypeScript#51859]
```typescript
type X = [boolean, number, ...string[]]
```

When declare such tuple type, it is possible to check whether the last item is rest type or not, through `ts.isRestTypeNode()` function. However, its corresponded function `Type.isRestType()` does not exist. 

The more amazing thing is, when getting `Type` information from compiler API (`TypeChecker.getTypeArguments()`), no different between below two type exists:

```typescript
type X = [boolean, number, ...string[]];
type Y = [boolean, number, string];
```

I think this is werid and need revise on `Type`.

**Comment by RyanCavanaugh** [comment]
A type itself isn't rest or not. What are you trying to do?

**Comment by samchon** [comment]
@RyanCavanaugh 

I've developed TypeScript runtime validator library - [typia](https://github.com/samchon/typia).

In nowaydays, I understood that rest type can be declared in a tuple type like `[boolean, number, ...string[]]`. Thus, I'm developing to my runtime validator library support the rest type feature by detecting the rest type through `ts.isRestTypeNode()` function like below.

https://github.com/samchon/typia/blob/master/src/factories/internal/iterate_metadata_tuple.ts

Until the rest type comes, I'd developed the [typia](https://github.com/samchon/typia) only by using the `ts.Type`s. Detecting the rest type through `ts.Node` is very hard work for me and I can't sure whether my approach is exact or not. Also, I can't understand why `ts.Type` stores exactly same info about `string` and `...string[]` type.

**Comment by samchon** [comment]
Found solution by stc developer's help.

**Comment by samchon** [comment]
Oops, sorry, not solved.

Looking at definition of `ts.TupleType`, there's a property named `elementFlags`.

However, when run below code, the `ts.TupleType.elementFlags` become `undefined`.

```typescript
const checker: ts.TypeChecker;
const type: ts.TupleType;

console.log(
    (checker as any).isTupleType(type), 
    type.elementFlags
);
// true undefined
```

**Comment by samchon** [comment]
Oops, found another solution through `ts.TupleType.target`
