### ISSUE TITLE
interfaces aren't exported in 1.7.0-dev.20151006

### ISSUE THREAD

**Issue by SamuelMarks** [Microsoft/TypeScript#5186]
On `master` you have `export`ed `interface`s, e.g.: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts

For example, I need to use `ClassLikeDeclaration` in a project I'm helping maintain, but that isn't `export`ed in `1.5.3`, `1.6.2` or `1.7.0-dev.20151006`.

Can you release an `@next` style thing like `@master`? - Or something?

Thanks!

**Comment by DanielRosenwasser** [comment]
`Can you release an `@next` style thing like `@master`? - Or something?`

What do you mean by this? We already have `typescript@next` for our nightly builds on npm.

**Comment by SamuelMarks** [comment]
Okay, well then I'm not sure what's going on. In `types.ts` `ClassLikeDeclaration` is `export`ed.

In `typescript.d.ts` it is not `export`ed. Can we change that?

**Comment by mhegazy** [comment]
Not sure if this is what you mean, but in an ambient declaration all top level declarations are exported implicitly. no need for the `export` modifier..

so ClassLikeDeclaration should still be exported in:
```ts
declare namespace ts {
    interface ClassLikeDeclaration extends Declaration {
    }
}
```

**Comment by SamuelMarks** [comment]
Hmm, then why is this failing with an `Module "typescript" has no exported member "ClassLikeDeclaration"`?:

    /// <reference path="node_modules/typescript/lib/typescript.d.ts"/>

    import * as ts from 'typescript';

    function foo(node: ts.ClassLikeDeclaration) {
        console.log(node.heritageClauses);
    }

**Comment by jesseschalken** [comment]
You could just remove the `import * as ts from 'typescript';` line, and use the `ts` namespace directly.

If you want to use it as a module with the `import` syntax then `tsc` has to correctly map the `"typescript"` module name to the `typescript.d.ts` file. It's possible it thinks `"typescript"` is something else, depending on what the module loading rules are. You could force it by putting this somwhere:

```ts
/// <reference path="node_modules/typescript/lib/typescript.d.ts"/>

declare module "typescript" {
    export = ts;
}
```

**Comment by mhegazy** [comment]
are you writing a node app or is this in the browser?

**Comment by mhegazy** [comment]
if you are in node, what you are doing is correct.. you do not even need the `/// <reference>`

so this works for me:

> npm install typescript@next

```
C:\test\sb>npm install typescript@next
typescript@1.7.0-dev.20151006 node_modules\typescript

C:\test\sb>node_modules\.bin\tsc --version
message TS6029: Version 1.7.0-dev.20151006

C:\test\sb>type test.ts
import * as ts from 'typescript';

function foo(node: ts.ClassLikeDeclaration) {
    console.log(node.heritageClauses);
}

foo(undefined);

C:\test\sb>node_modules\.bin\tsc test.ts --m commonjs

C:\test\sb>test.js

C:\test\sb\test.js:2
    console.log(node.heritageClauses);
                    ^

TypeError: Cannot read property 'heritageClauses' of undefined
    at foo (C:\test\sb\test.js:2:21)
    at Object.<anonymous> (C:\test\sb\test.js:4:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by mhegazy** [comment]
Please reopen if this is still an issue.
