### ISSUE TITLE
skipLibCheck doesn't work with typesVersions

### ISSUE THREAD

**Issue by tjx666** [microsoft/TypeScript#51861]
# Bug Report

### 🔎 Search Terms

skipLibCheck, typesVersions

### 🕗 Version & Regression Information

"typescript": "^4.9.4"

Reproduce:

1. `git clone https://github.com/tjx666/ts-exports-development`
2. `git reset --hard d0eb57cdf0c1f8cdb5260dc2f6f9083479046d50`
3. `pnpm install`
4. `cd packages/app`
5. `tsc --noEmit`

### ⏯ Playground Link

[Reproduce Repo](https://github.com/tjx666/ts-exports-development)

### 💻 Code

monorepo project structure:

```txt
.
├── node_modules
│   ├── tsup -> .pnpm/tsup@6.5.0_typescript@4.9.4/node_modules/tsup
│   └── typescript -> .pnpm/typescript@4.9.4/node_modules/typescript
├── package.json
├── packages
│   ├── app
│   │   ├── node_modules
│   │   │   └── tools -> ../../tools
│   │   ├── package.json
│   │   ├── src
│   │   │   └── index.ts
│   │   └── tsconfig.json
│   └── tools
│       ├── dist
│       │   ├── index.js
│       │   └── index.mjs
│       ├── package.json
│       ├── src
│       │   └── index.ts
│       └── tsconfig.json
├── pnpm-lock.yaml
└── pnpm-workspace.yaml
```

In packages/app/src/index.ts

```typescript
import { add } from 'tools';

console.log(add(2, 4));
```

In packages/tools/src/index.ts

```typescript
export function add(a: number, b: number) {
    return a + b;
}

let a = 1;
// here error
a = '';
```

the package.json of package tools

```json
{
    "name": "tools",
    "version": "1.0.0",
    "description": "",
    "scripts": {
        "build": "tsup src/index.ts --format esm,cjs"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "exports": {
        ".": {
            "import": {
                "development": "./src",
                "default": "./dist/index.mjs"
            },
            "require": {
                "development": "./src",
                "default": "./dist/index.js"
            }
        }
    },
    "typesVersions": {
        "*": {
            "*": [
                "./src/*"
            ]
        }
    }
}
```

### 🙁 Actual behavior

When run `tsc --no emit` in packages/app, will check the ts file in tools/src

### 🙂 Expected behavior

Not check the ts file in tools/src

**Comment by RyanCavanaugh** [comment]
"lib" in "skip lib check" means "a .d.ts file". It doesn't mean "something that came in via node_modules" or other more nuanced definition.

**Comment by tjx666** [comment]
> "lib" in "skip lib check" means "a .d.ts file". It doesn't mean "something that came in via node_modules" or other more nuanced definition.

So, any way to skip check the ts files?

**Comment by tjx666** [comment]
I points the typesVersions to `src`, is this the correct usage？Maybe I should generate the `.d.ts`, and using the `types` field?

**Comment by RyanCavanaugh** [comment]
The preferred behavior is always for a unit of compilation to expose its .d.ts files rather than its source

**Comment by sneko** [comment]
On my side my storybook package was looking for types specific to another workspace package. I tried tons of "solutions" but none worked.

The only one working was to tell my package to look for types of the other package:
```
{
  ...
  "include": ["**/*.ts", "**/*.tsx", "../../apps/main/@types"],
  "exclude": ["node_modules"]
}
```

Hope this helps :)
