### ISSUE TITLE
JSX incorrectly infering types

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#51863]
# Bug Report

### 🔎 Search Terms

jsx, infer, createElement

### 🕗 Version & Regression Information

- This is a crash No
- The issue appears in versions 3.x, 4.x and 5.x

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBAbzgYQuCA7AphmAVATzCwBo4BjKLAQxiwFEAbLEHeAXzgDMo04AiKtXIx+AWABQkmESwo0kbLgAKvMAGcAPKnRKYZJurkBeONgBuWKAD44pnYrZwsADzoYAJuvm62hYprAGFxWcMq2APxhcABccIZY0rJwAHK0wJYOmGyqEBqaaawGjEZ2ZliWNmUA2oVYALrObjhecNUA1lgEEFxwAFIAygAaAHQAkrhQQerA5EwsbOqNUYOjEzBTGDNzzKy46rXUrI1xCUnEYWrqAPJcmvN7+vElJuWVtvYK2SpX97tsZDSMAyWCyely+QeAOeRms1kk5zkUNwqEm1CC8FMnW6vVW40m01myJg3gAPj5HLh-FhNNQMAR4VIJAB6ZnxFxHMDMOAARkkXAArhgRMBMHAAIJ-Ba4JruVrE1EbdEy0wAcg8GVV1gAFEgsP8VXB1Zq4NRvMSyCMrWArnB2HE9QaYBFTk67XAAGRwa4gYAwTQQm53YnWMiq-XSmBagCUiEkcATcCoMAFUAwFCEdGJ2ojjzINry6mjknYCIkguFwLFeCw6hg2oLGgdcDodbiqtbUbtsYQ8cTydT6c0GvM1hrdc0zJHjNLTIrIurtZgAHU-QALADiOCss00eB1jfUzYA5tupuQ4nhu3GJImk1gU2m4MOMmOl5PpyWy+RMHW4AAtQCyk0cVrEnUDJFZO9oITAA9CJILZQBQcjgABaFBrgAJUw+hkDwb9f3gABpEjgPFZwnWMVVqC1cDGSgmC73gxC4BQ9DkCwnC8IIrZ4CGfiyIoyNjAQccYE4TsqM7WjmQglk2UYxNmPk1i0Iw7DcPwpkf14uAAE0DME3M2BEsTVxgTcz1mThT2wc8qI3egUnoTCxmQGS5IYxS4GUqDAGfiNSAFlrgGPAABk9PUrir3Qn8BUYDw4CCEIoBbNdaDgK9gG8Rg-SsahGCNRznNc9yyyg+gOXAbkACZ+SFBd0wAISlR5ZRac0nUVKBlUxI0ACMBRgGBMC1XUhLatVBuG0bTU6yM7WbYzcBdZ5IzIEACAhVbVV9bBVXdL0fT9AMrluVq2FDI1lq7cldq2tQYxvO8ByfECJpMhAbs4MDZMZO8vKUhDb0TKDABlyNTl0w64Ug3NTxVVbxD1NKg4B6Ftkn4R1I1W4lDu9X1-TGFIADEXPoAARAB9ZRoeUAYwxurV+DQ2wbrgdQ1wgeLEoKgB3agCG8VxsvgOlEpAWhyDXPsEwq7CsMvZJVWxx5XUjABuO0DuyswIDF9QZmPDBqH67kRoxi5VWO-0wRyX4LVSdJMi+cEHadMgLCsOEyH4G7+GsVVZbgKC8AGOBGAgCAjG8Cy5Cxj6VvVtrOC9K0RhZsBqFgL9tMIgDAJ5YCmt+kuWO8nzgagtios0ni-xIoii9MTQmsTmAqJo0v6IU7zfOQtSOI07i890-ihmb5825u0ylwkpcpKXA7NohYx+D2rAA8nMuVIr-vVPYzi69Hv8DL0yfW-b2e63Myy7OsuBbJ3cgHKcly3OXh68jXjet+ZHfAaMX3gFdCwVQoRVrnhNScUEpJWCKECyGUso5Tyj1Qqqpirv3ckAA)

### 💻 Code

```ts
// see complete code in the TS playground

// Example 1
function A<Element extends ElementContraint = 'div'>({ element = 'div' as Element, ...props }: { element?: Element } & Omit<PropsOf<Element>, 'element'>) {
    return createElement(element, props)
}

// Example 2
function B<Element extends ElementContraint>({ element = 'button' as Element }: { element?: Element, myProp?: 'mine' } & Omit<PropsOf<Element>, 'element' | 'myProp'>) {
    return <A element={element} ></A>
    // ❌ - WRONG - A's props are of type "{ element?: Element } & Omit<INFERED_PROPS, 'element'>" -> element should always exist and match
    // ERROR: Type '{ element: Element; }' is not assignable to type 'Omit<ComponentProps<Element, NativeComponentProps<Element, never>>, "element">'
    // TS looses the "{ element?: Element } & ..." part
}
```

### 🙁 Actual behavior

TS reports error `Type '{ element: Element; }' is not assignable to type 'Omit<ComponentProps<Element, NativeComponentProps<Element, never>>, "element">'` 

### 🙂 Expected behavior

TS correctly infers the type to be `{ element?: Element } & Omit<ComponentProps<Element, NativeComponentProps<Element, never>>, "element">'`

**Comment by RyanCavanaugh** [comment]
This is a correct error, because nothing here prevents this unsound call:
```ts
declare global {
    namespace JSX {
        interface IntrinsicElements  {
            foo: { element: boolean }
        }
    }
}

const j = <foo />
// ^^^ correctly disallowed
const m = <B element="foo"></B>;
//  ^^^ does the same thing!
```

**Comment by alesmenzel** [comment]
Hi @RyanCavanaugh , thanks for the reply, but I still believe there is something wrong. Let me try to explain it better. The component A is generic component over `Element` which can be either string literal like `a`,`div`, `button` or it can be another component factory (= function component/class of a component) The outer element then merges their own props with the ones "composed" from the type of `element`. Here are some examples
```tsx
<A element='div' /> // -> infer props for div and allow them on A
<A element='a' /> // -> infer props for a and allow them on A
<A element='button' /> // -> infer props for button and allow them on A
<A element={(props: InnerComponentProps): ReactElement => <div>text</div>} />  // -> infer InnerComponentProps and allow them on A
```
So my point is that when I know that Element in A must be of type `'a' | 'div' | 'button' | ComponentType<any>` and component B has the same constraint on Element generic, shouldn't the type match?
```tsx
A<Element extends ElementContraint>
B<Element extends ElementContraint>

// when simplified, it is basically just wrapping the function and passing all props
// so the functions (= components) should have the same type signature?
function B<Element extends ElementContraint> (props) {
  return <A {...props} /> // A here should infer the type of element to be the Element generic from B, right?
}
```

Another supporting argument, I think, is that when I just keep the `element?: Element`, it works (so the problem lies within the inference of "element" props(?)), see [playground](https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBAbzgYQuCA7AphmAVATzCwBo4BjKLAQxiwFEAbLEHeAXzgDMo04AiKtXIx+AWABQkmESwo0kbLgAKvMAGcAPKnRKYZJurkBeONgBuWKAD44pnYrZwsADzoYAJuvm62hYprAGFxWcMq2APxhcABccIZY0rJwAHK0wJYOmGyqEBqaaawGjEZ2ZliWNmUA2oVYALrObjhecNUA1lgEEFxwAFIAygAaAHQAkrhQQerA5EwsbOqNUYOjEzBTGDNzzKy46rXUrI1xCUnEYWrqAPJcmvN7+vElJuWVtvYK2SpX97tsZDSMAyWCyely+QeAOeRms1kk5zkUNwqEm1CC8FMnW6vVW40m01myJg3gAPj5HLh-FhNNQMAR4VIJAB6ZnxFxHMDMOAARkkXAArhgRMBMHAAIJ-Ba4JruVrE1EbdEy0wAcg8GVV1gAFEgsP8VXB1Zq4NRvMS4Ow4nqDTAIqdbZaAJSISRwd1wKgwAVQDAUIR0Yna-XSmBOyTsBESQXC4FivBYdQwbVgK7WuB0JNxVWZmCq52uiQez1Yb2+uCaDXmawJpOaZlVxmRpkxkXxxMwADqwBgAAsAOI4KyzTR4HWpvLqdMAcyHU3IcTwBYQbo9Xp9fsrGRrHfrjYjUfImCTcAAWueyppxdZ69fJKzi4-3QA9CL3tmAUHI4ABaFDXABK-70MgeCHse8AANJQZe4rOLaxiqtQWq3oyD5PsWr7vnAX6-sgAFASBUYPvQHLgNyABM-JCm2foAEJSo8sotOatqKlAyqYkaABGAowDAmBarqcGhmUqo8XxAmmixIlWogwmPPazwyS6K5FmupYbhWsEho8xgIDpbCcDezJ3mp7poRhb4SM2khHls8DnqePKXrRxmuVh6EephLKfj+f6AcBoFMnZJ5QRBzmmJotHyWwCFIW5qFsp5L5WQ+OH+QRQVAA).


Lastly, regarding the error message
```
Type '{ element: Element; }' is not assignable to type 'Omit<ComponentProps<Element, NativeComponentProps<Element, never>>, "element">'
```
Why does it states that `{ element: Element; }` is not assignable to just part of the actual type? I think it should say that it cannot be assignable to `{ element?: Element; } & Omit<ComponentProps<Element, NativeComponentProps<Element, never>>, "element">` because thats the complete type of A, but the `{ element?: Element; }` is missing in the second part?

**Comment by RyanCavanaugh** [comment]
I don't really understand what you're getting at. If there is a bug here, it should be demonstrable through a much simpler repro.

**Comment by alesmenzel** [comment]
Hi @RyanCavanaugh, thanks for looking into this issue, I am sorry If the examples were not clear. I am trying to isolate the issue as much as possible while keeping the original idea. Here is the most minimalistic example I could make. I have completely removed the `react` dependency as it doesn't seem relevant. I have also written commentary to the code so it would be easier to understand maybe if I am making a mistake somewhere or I don't understand some TS concept.

[Playground link](https://www.typescriptlang.org/play?jsx=4#code/PTAEGEHsDsDMEsDmBXATgQwC7xqWlVQBTAGyIFsjpNRp1KBnUdaAE1EwAsj5CAHVJD5FU2IgwCwAKEwBPYaACiZStQAKgvkwC8oAN7TQR0K3gA3AFz7Dx26bMahIuVYDk9gLQChrgDQ3bIwZOdFQiVkc+N2DQ8NcA0ABffylbACNkTEwYKwNUwKMMrJhI51k3IuzoL00-BNsYsIjNaJCm+PyjROluqWkQCBgGTAx4ajwCUAB3EJpSCioaAGMWUDSiUGQGcNAPAD5Qd3NXUAAfQ8qYDrkFZQXqKGpR8d0AayJZSFglFUXIySkAwASuJICQzBsuBtvMJRPBxHhBORiL9xnRKL5iAA6RBYiaEVyXaAnfb6NaZKqlUTlC4UmA1HyYxrhSKtWKsE69G4bACScBE-wAPHdVJgDroRYtiAAPTBUVhMd6fb6S9SaJgAfh+90w-wA2qrMABdUBWaBECGoaT9MAAESICGg8GwuC+zFAiCoIngSzwyGgSxd0A4s1AYQYYIhTEgUP4mmc8KYsCRIY2ACJDf806AljBYCgMEGbdjcfjDvYSQc03oUTqNW4K5j7FSXOXzAy+H5QMzmkI2e0kmni0QcXj8ASiZXQNXa6L67TisTMUSWzTCXTqjCuz3WYce5yh4CwCPS+PNmwHWMdqTWA70MgSDRsm2zB0BgAVTjwJhTAivJiAKDk0iwP6gY4MGACCwqonMsrykwhqPCM6BjDQuhHK+ewABQ1vMoqgOhFbMAhMGYli5EwkwiS5LOizzoaSSgAAZKAADy5DOoKfKwAK6rQTqeyYq4eGLK4ewAJRWP6t6OjseS2Lm0ARmQWIkJAiBYSJ1CYpR4kJGEmBoMG0mXuarA9NaR6gPajrOuBoBuug0wYHwfBjIgfoBkGIZYKAABWWw0OgrAKsw0AxtwcZONS05pLuhIdq42YRSIUzfhszqgCETBQt29AbAwSB0IZYRhewAXDDm6AkCQTAQdMzqcKAMIJgiXC+fVwSQA+7DoEsSxEHwmDFgAEiIGU5dwoDfgwyC8iYVw0CZqDDCw7CADLkwGgd5ABC-H4UQcFsCROpIc8aELlUYk4bRLyXVcxHaqKy6RGRFHqkkNFaZg9GkWs8VpIljEsexnHcbxQgMPtiyCYc31iZJ54yVe7DycYAwAMr5c1oT5XKhDoEmkz1YdA1DdNQUhUwaZxZo2ZFBT01MOFNB8IT2zsM+EEJIpykjmpGm00Iel9J0oADDtrjU7hf3kVilGDjjDAcxwkCgJ1nDdSQ7AhBCqYyn1NAMNj3KPfVfVk5gDDAGMPErZiJ5YgkAwzFQoA8gtoAAHKse+3bIK5JCyLdrPxtSmJQsGuWm11PVrBse3rouYnTF+SxNbH2thuID5PmrM7ffOSdXcuG6rhUG6JUybQsi0e41xyg7O2AMw+k1lAsJNGz1SBXn2WMhW3t2mtx7bIg+U+U0ZjB2aeuaqA+hw8gTfdxK7AcUHF1cBxrcw-WDTQBcwUXk6l4u5er1Xw-svF+5N2L+lECVkE3d9b3yx9iQi7YAyKECQKsSBBYZuoB3zL0ODLHUVhDQAG5gZsQ4pgQUkC5zQJgmcJGplwhwKFlEWKHY0xwMSMxBBYN+SoCFIaWGaZvppmobQjBNNIh0JOCA78tAYzEUKogOgaQyCqyXgoVwoMkHgwoXxKhmIaEzz2B0WwICADqnBg7sK4OwlmzVIDK3gHwogGoehAA)

**Conceptually what I am trying to achieve:**
- have a function that accepts some form of "type" (e.g. in string form as `'div'` or `'button'`)
- have a configuration object that defines properties relevant for the given "type"
- infer the properties based on "type" passed to the function
- be able to define default "type"
- be able to wrap the function in a new function that adds own properties and can change the default value of "type" (e.g. from `'div'` to `'button'`)

```ts
// Configuration for element names and their properties
type ElementProps = {
    div: {
        divProperty: 'div-prop',
        sharedProp: 'shared'
    },
    button: {
        buttonProperty: 'button-prop',
        sharedProp: 'shared'
    }
}

// Constraint for what element can be used -> 'div' | 'button'
type ElementContraint = keyof ElementProps
// Resolve the properties from element name, e.g. for 'button' -> { buttonProperty: 'button-prop', sharedProp: 'shared' }
type InferProps<Element> = Element extends keyof ElementProps ? ElementProps[Element] : never

// Definition of a generic function that resolves other properties from the "ElementProps" confguration
// e.g. for 'div' -> "{ element?: 'div', divProperty: 'div-prop', sharedProp: 'shared' }"
// e.g. for 'button' -> "{ element?: 'button', buttonProperty: 'button-prop', sharedProp: 'shared' }"
// e.g. for undefined -> default to 'div'
// This works ✅
function A<Element extends ElementContraint = 'div'>({ element = 'div' as Element, ...props }: { element?: Element } & Omit<InferProps<Element>, 'element'>) {
  // return value is not relevant
}

// Definition of a wrapping function that just adds another property "bProp: 'b-prop'" otherwise it has the same signature and just calls A with properties that A should accept
// Here is the issue I don't understand ❌
function B<Element extends ElementContraint = 'button'>({ element = 'button' as Element, bProp, ...props }: { element?: Element, bProp: 'b-prop' } & Omit<InferProps<Element>, 'element'>) {
    // Same parameter as for A except it adds "bProp" but it is not passed to A

    // B's "{ element, ...props }" passed to A should have the exact same type as A accepts/infers, e.g.
    // when I do NOT supply element property, then the type should be B<'button'> which should result to "{ element?: 'button', buttonProperty: 'button-prop', sharedProp: 'shared' }"
    // which means the A function inside should infer that the "Element" generic type is 'button' -> A<'button'> and accept "{ element?: 'button', buttonProperty: 'button-prop', sharedProp: 'shared' }"
    
    A({ element, ...props })
    // ERROR:
    // Type '{ element: Element; } & Omit<{ element?: Element | undefined; bProp: "b-prop"; } & Omit<InferProps<Element>, "element">, "element" | "bProp">' 
    // is not assignable to type 'Omit<InferProps<Element>, "element">'
    
    // Why is this not possible?
    
    // return value is not relevant
}
```

**Comment by RyanCavanaugh** [comment]
Thanks for the pared-down example. Here's a demonstration of what TypeScript is trying to tell you
```ts
// Configuration for element names and their properties
type ElementProps = {
    div: {
        divProperty: 'div-prop',
        sharedProp: 'shared'
    },
    button: {
        buttonProperty: 'button-prop',
        sharedProp: 'shared'
    },
    other: {
      bProp: "b-prop"
    }
}

declare var React: any;
// OK
const j1 = <A element="other" bProp="b-prop" />;
// Correct error per definition of 'A'
const j2 = <A element="other" />;
// OK from the outside, but the implementation doesn't pass bProp through, this is an invalid invocation of A
const j3 = <B<"other"> bProp="b-prop" />;
```

It *happens to be the case* that none of the given `ElementProps` in your example have a ` bProb`, but TypeScript can't evaluate things by doing the combinatorial explosion of the program to see every possible union constituent's possible values. Things have to be showable to be OK via some means that isn't sheer enumeration.

**Comment by alesmenzel** [comment]
So if I understand it correctly the only issue is with "casting" the generic type instead of inferring it here `<B<"other"> bProp="b-prop" />` because B would have element defaulted to `'button'` inside and therefore break A because A would expect A<'other'> as well? So we would need some way to specify a generic as inferred so we cannot override it from the outside,e.g. something like below?

```
function A<infered Element extends 'div' | 'button' = 'div'>(...) {}

<A<'other'> ... />
// ^ this throw an error
```

**Comment by alesmenzel** [comment]
Aha! So the problem would be when the inferred props from configuration had the same prop that is defined on B, e.g. 

```js
type ElementProps = {
  other: {
     bProp: "b-prop"
   }
}

<B element="other" bProp='b-prop' />
// would call internally without "bProp", because that is used only in B
<A element="other" /> // bProp is missing, because it is required in ElementProps (making the prop optional should also fix the issue?)
```

But doesn't that mean if I remove the extra property an B, then it should work? e.g. 

[Playground link](https://www.typescriptlang.org/play?jsx=4#code/C4TwDgpgBAogNhAthAdsACgJwPZgM5QC8UA3gLABQU1UAJgJYBuAXKZTR3U1rhJqKwDkDRgFowOMIIA07TtTwALAIaYItHmCFLV6wXOoBfWVRoAjAK7Bg2FK3Kn5l67c18BUQc5spxkmQacOmoaktoqIfqOUIaUsRSUoJCwCMhoAMK2wJjK9GhEUADWECDYAGYpSKgYkniJ4NAAkihlfJp4ADzwVWgAfAXdacBQEAAewKi0BMWlFYPV7VAA-JVD7QDa82gAulCsKBCMfJSUAPSnUICg5JRlFigAxsD0tlAAgl2p1SPjkwRbwJk0Dk8sNiMImIJegAKEgjT75MEiQRQZR-eHAaRQAB0OIkuAIhnscJ6wCWrH+MSgADIoAB5RD0YAdZqtTDtD4k3qYwQQdGQgCUrDutAgZTy6jY0Xutjw2AQWLg2AA5lDeSTMXj8PzAmpgBZMCgoMLReLaHEThRzlBADLkNzuj2ehoAQhyht8JigpqtqoDsrkEZ5vLZITDiW6wUGUMjUd60JicVjNQSiWqhmTY8NDNS6QymSy2rVXdUuZ5U9UBULPSaDrRJRxdfrDa9Q2W49jcbUYtrolaACoNKCBK2CWGt4Dk9EAbkpNPpjI6o-R6YpAB8jVWxTXp1nZ7nmS0C-ii31MQAiMenkvn9GX5FDi70AgobDDVF4ehKlDKMwIKA2P8DoIc55gebKFv8V4Xr0USGEAA)

```ts
type ElementProps = {
    div: {
        divProperty: 'div-prop',
        sharedProp: 'shared'
    },
    button: {
        buttonProperty: 'button-prop',
        sharedProp: 'shared'
    }
}

type ElementContraint = keyof ElementProps
type InferProps<Element> = Element extends keyof ElementProps ? ElementProps[Element] : never

// ✅
function A<Element extends ElementContraint = 'div'>({ element = 'div' as Element, ...props }: { element?: Element } & Omit<InferProps<Element>, 'element'>): undefined {
    console.log(element, props)
    return undefined
}

// ❌
function B<Element extends ElementContraint = 'button'>({ element = 'button' as Element, ...props }: { element?: Element } & Omit<InferProps<Element>, 'element'>): undefined {
    return A({ element, ...props })
    // Type 
    // '{ element: Element; } & Omit<{ element?: Element | undefined; } & Omit<InferProps<Element>, "element">, "element">' 
    // is not assignable to type 'Omit<InferProps<Element>, "element">'
}
```
