### ISSUE TITLE
how to defined a typescript type which can check the string value is a valid hex string?

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/TypeScript#51860]
such as:

```ts
let str: ByteString = "01afe3"; // valid
let str1: ByteString = "0a1" // invalid, hex string length should be even
let str2: ByteString = "hello" //invalid, only hex allow
```

the value can be any string that is a valid hex.

i have try below:

```ts
type HexChar = '0' | '1' | '2' | '3' | '4' | '5' | '6'| '7' | '8' | '9' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
type HexColor = `#${HexChar}${HexChar}${HexChar}${HexChar}${HexChar}${HexChar}`;
let color: HexColor = '#123456';
```

but this only work when the value is fixed length.

we wants a type that can handle any length if the string value is valid.

**Comment by MartinJohns** [comment]
- You forgot to fill out the issue template.
- This repository is meant for feature requests and bug reports, not questions.
- You could try to make `HexColor` a union with different length strings, but you could possibly reach the limit of TypeScripts type-system here.

**Comment by zhfnjust** [comment]
Thank you. 

all solustion i found is below:

```ts
type HexChar = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';


type HexType<T extends string> = 
  T extends `${infer R1}${infer R2}${infer R3}`
  ?  R1 extends HexChar
    ? R2 extends HexChar
      ? `${R1}${R2}${HexType<R3>}`
      : never
    : never
  : T extends `${infer R1}${infer R2}`
    ? R1 extends `${HexChar}${HexChar}`
      ? `${R1}${HexType<R2>}`
      : never
  : `${T}`;

/**
 * Converts a hex literal to string.
 * @param {string} hexStr - should be in format of hex literal, i.e. `/^([0-9a-fA-F]{2})*$/`
 */
export function hexToString<T extends string >(hexStr: HexType<T>): string {

  return hexStr;
};


hexToString("00aa")
```

but this require a hepler function `hexToString` . I don't wants a hepler function , I just wants a type.

**Comment by zhfnjust** [comment]
> * You forgot to fill out the issue template.
> * This repository is meant for feature requests and bug reports, not questions.
> * You could try to make `HexColor` a union with different length strings, but you could possibly reach the limit of TypeScripts type-system here.

YEs , i reach the limit. can we remove it?

**Comment by MartinJohns** [comment]
The best option is to just deal with the limitations of the type system. I'd create a function that accepts the string and also validates it, then just returns a branded type.
