### ISSUE TITLE
The compiler ignores assignments inside array methods' callbacks

### ISSUE THREAD

**Issue by DaviDevMod** [microsoft/TypeScript#51869]
# Bug Report

Assignments inside array methods' callbacks are not taken into account for the purpose of typing variables.

There are many issues on array methods, eg: #16069, but I couldn't find a duplicate (original?). 

### 🔎 Search Terms

array method callback 

### 🕗 Version & Regression Information

The bug can be found in any version of the TypeScript Playground (currently from v3.3.3333 to 4.9.4, including the Nightly v5.0.0-dev.20221212).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZgSzAEwGIIG4FMYF4YAUAhgE4lECeAXDGAK4C2ARliQNoC6AlHgHwylyFAHSIUBAmB65+YPLnwBWLgG4AUGtCRYgyhDww2bAIwcANIYBMFgMznDAFguKLANg4d1agDZZYDShYAQXRsGnpmVhgAHxg6FCwxLGQDeOREpGSvAHpsmAADAIpg0Kx8mAR9FiQAcwEICAQasGSBAoiWEhi4hKTkcoB3BCgACyQBOV0KGAY-EZBkAHJ9YCJvbyYiYABrYTUpiFEkZAkp6X4CIpLMHHwxNBviMkouV5y8gElYSphoBHWYFAKAAHVpEfT5NIZFr9GDpCDA4Y4UY4cGNMA1WZgHRMEDYPZXLAhG7vGAfBig8hQG4wLAARzomDWWGxMBAcEBIxw+SO4i45VWAKIuPxajgIC6BC00AEz2m7NlQggPAA3moYDNAkTSgZ7qUnkJVOqKhzLlridgeEwSFgiNt1ABfDS5GAAFRBrXyHSisShfXyFnBtIAHqDgFBkgTzaUVEA)

### 💻 Code

```ts
const findFive = (array: number[]) => array.find((n) => n === 5);

const arrays = [[1], [2, 3], [4, 5, 6]];

let maybeAFive: number | undefined = undefined;

// `maybeAFive` is being assigned a `number | undefined` within an array method's callback.
arrays.find((array) => (maybeAFive = findFive(array)));

// It is still typed as `undefined` despite the assingment above.
maybeAFive;

// Imperative equivalent of the `.find()` call above.
for (const array of arrays) {
  maybeAFive = findFive(array);
  if (maybeAFive) break;
}

// Typed `number | undefined`, as expected.
maybeAFive;
```

### 🙁 Actual behavior

Assignments inside array methods' callbacks are not taken into account for the purpose of typing variables.

### 🙂 Expected behavior

Assignments inside array methods' callbacks should be taken into account for the purpose of typing variables.

**Comment by IllusionMH** [comment]
Duplicate of #9998
Repo even contains specific temple for this kind of issues.

**Comment by DaviDevMod** [comment]
@IllusionMH You are right, there is a "Types Not Correct in/with Callback" template.
That issue should mention "callback" somewhere in its title.
Anyway thanks for the answer.
