### ISSUE TITLE
Generics that extend any fail further type checks

### ISSUE THREAD

**Issue by zkldi** [microsoft/TypeScript#51872]
# Bug Report

### 🔎 Search Terms

Generics extending any, Generic constraints

### 🕗 Version & Regression Information

- This changed between versions 4.6.3 and 4.9.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.9.4#code/JYOwLgpgTgZghgYwgAgMIHsA2mILMdEAHgBVkIAPSEAEwGdk6wpQBzAPmQG8BfAKD5gAngAcUAEQjwArpjABlBAAsIAWzjIAvMjgghAbgGUR6KGGQJMcOg3EAjbn2TOLWHHgLESileq3JJGTkfNTh2AAonF2iQOFUIAC5GZjYAGijo5wQ4bDtEAGsAfiSMbFx8QlIQ9XZ06IBKbh5DHiA

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
interface Collection<T extends string> {}

type DefaultSchema = any;

export class Db {
    collection<TSchema = DefaultSchema>(
        name: string,
        callback?: Collection<TSchema>, // <- Type 'TSchema' does not satisfy the constraint 'string'.
    ) {};
}
```

### 🙁 Actual behavior

This no longer compiles as of (at least) 4.9.4. This code is found in `@types/mongodb@3.6.20`, which I have depended on and compiled perfectly fine for years.

### 🙂 Expected behavior

Since this generic extends Any, it shouldn't be able to fail any constraints since -- by definition -- it is *any* type.

**Comment by fatcerberus** [comment]
It doesn’t extend `any`, it extends `unknown`—which means it’s not guaranteed to be a subtype of `string`.

**Comment by fatcerberus** [comment]
For the record this is an error [at least as far back as TS 3.3.3333](https://www.typescriptlang.org/play?ts=3.3.3#code/JYOwLgpgTgZghgYwgAgMIHsA2mILMdEAHgBVkIAPSEAEwGdk6wpQBzAPmQG8BfAKD5gAngAcUAEQjwArpjABlBAAsIAWzjIAvMjgghAbgGUR6KGGQJMcOg3EAjbn2TOLWHHgLESileq3JJGTkfNTh2AAonF2iQOFUIAC5GZjYAGijo5wQ4bDtEAGsAfiSMbFx8QlIQ9XZ06IBKbh5DHiA).  The behavior is not new.

**Comment by zkldi** [comment]
This behaviour is identical when `extends any` is set.

```
interface Collection<T extends string> {}

type DefaultSchema = any;

export class Db {
    collection<TSchema extends any = DefaultSchema>(
        name: string,
        callback?: Collection<TSchema>,
    ) {};
}
```
https://www.typescriptlang.org/play?ts=4.9.4&ssl=10&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgMIHsA2mILMdEAHgBVkIAPSEAEwGdk6wpQBzAPmQG8BfAKD5gAngAcUAEQjwArpjABlBAAsIAWzjIAvMjgghAbgGUR6KGGQJMcOg3EAjbn2TOLWHHgLESilevJUIWgZdIS1kSRk5HzU4dgAKJxckkDhVCAAuRmY2ABpEpOcEOGw7RABrAH5MjGxcfEJSaPV2PKSASm4eQx4gA

*****
As for it being an error that far back, it's interesting that this was still compiling fine on my machine as of 4.6.3. Are there other settings that may affect this?

**Comment by RyanCavanaugh** [comment]
Defaults are just defaults. Someone can write `(new DB()).collection<number>("", {})`, which would create a constraint violation.

**Comment by zkldi** [comment]
Interesting. Any ideas why this code used to not be an error then? At the very least, [this repo](https://github.com/tng-dev/tachi)'s `common/` project seems to `tsc -b` fine on typescript 4.6.3 and not on 4.9.4.

**Comment by RyanCavanaugh** [comment]
Changing the version selector in the Playground, I don't see any historical difference with the given repro.
