### ISSUE TITLE
Add a Quick Fix to add an additional parameter to a method or function

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#51870]
See here:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/900690/206963266-72c2a629-278a-4c7c-9efb-48cc8ccbbe55.png">

```ts
openEditor(editor: EditorInput, didChangeActive: boolean): void {
	this.handleOpenedEditors(didChangeActive);
}
```

From: https://github.com/microsoft/vscode/blob/14f54b128dd5955db7a69e0aac760731d343e54b/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L417

I would have expected a way to add `boolean` to the method.

**Comment by a-tarasyuk** [comment]
@bpasero I'm unsure whether this issue will be approved. I've observed that a similar QF already exists in VS, and it would be nice to have it in VS Code as well. #56411 is this the intended behavior for the proposed QF?
