### ISSUE TITLE
Unexpected overload signature is matched with constructor type

### ISSUE THREAD

**Issue by markostanimirovic** [microsoft/TypeScript#51899]
# Bug Report

### 🔎 Search Terms

overload, constructor type

### 🕗 Version & Regression Information

I tested with different TS v4 versions. This bug does not seem like a regression.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAKuEB4YD4oF4oDsIHcoAoA6YgQwCcBzAZwC4oTMQBtAXQEp1UYBuAKF4BmAV0wBjYAEsA9pigTMAKwjikyfMDpxIqtpr7CxkmXMXLg6ugxC76jblAD0DqKKkBbNxEzAoUoT+AACwkqKAAbeWg0VCDoUEhfASgAA1EAJmSoHAkwsKgAI2hkgGEwkioqAHUJIOLgKTIAQUoqZMERcWlZeSVxC1trS0YoAG9eKAmoMghgITJZYD4AX35RMoqoUvLQkZXeNe3N9aqawLqG5upR8cnXTCpgMiFxBvwADzpMITdCsg5d3h7JxQeIQOhbDaAUHJ9jIHi4AIzoEy9cwQqhsPi8YGgoYgKCAGXIYfcfOkkT0zPg0dVavUmi0MbwgA)

### 💻 Code

```ts
type Type<T> = new (...args: any[]) => T;

function inject<T>(t: Type<T>): T;
function inject(t: any): any; // comment out this line => the type of `c2` will be `ClassWithCtorArgs`
function inject(t: any): any {
    return t;
}

class Class {}

class ClassWithCtorArgs {
    constructor(x: number) {}
}

// type: Class ✅
const c1 = inject(Class);

// type: any ❌
const c2 = inject(ClassWithCtorArgs);
```

### 🙁 Actual behavior

The type of `c2` constant from the example is `any`.

### 🙂 Expected behavior

The type of `c2` constant from the example should be `ClassWithCtorArgs`.

**Comment by RyanCavanaugh** [comment]
The overload resolution algorithm is deliberately very simple. It proceeds as follows:
 * Pick the first signature which matches according to the subtype relation
 * If none was chosen, pick the first signature which matches according to the assignability relation

One of the differences between subtype and assignable is how `any` gets treated in function parameters, as shown here, so the second overload gets picked during the first pass.

I recommend using a different definition of `Type<T>`:
```ts
type Type<T> = new (...args: never[]) => T;
```

**Comment by markostanimirovic** [comment]
Thank you so much @RyanCavanaugh! :)
