### ISSUE TITLE
'this' operator cannot correctly deduce the type

### ISSUE THREAD

**Issue by janryWang** [microsoft/TypeScript#51902]
# Bug Report

### 🕗 Version & Regression Information

4.9.4

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIG8CwAoZy4BcIArgLYBG0Oe5BAzmFKAOY4C+OOoksiKA0gB5UyCAA9IIACZ1kAe3IArCAjAA+LLmRgAngAcIBANYQdcmGmrIAbnAA2xQ2gDaYABbA6zgOS6D3gF0AqwQPOykoCBAAfgIhVDVnYOwObBwEORAGZDE44TUAXmRNPD9DbzhvABorWwdyujpq5AB6FpAICCltNyg5AHdRKD6oELCIqIJnKzwSvHmyggAiciWarXmbe0cCACZW9s7u9z7B6BGZ5FS8ZLYgA

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.

interface M{
  a:number
  b:string
}

interface K<M extends object>{
  type:keyof M
  value: M[this['type']]
  children?:K<M>[]
}

const x:K<M>= {
  type:'a',
  value:'ss', //need throw error
  children:[
    {
      type:"b",
      value:2 //need throw error
    }
  ]
}
```

### 🙁 Actual behavior

no error

### 🙂 Expected behavior

need error

**Comment by RyanCavanaugh** [comment]
A bare reference to a type isn't something that performs generic inference; `K<M>` is effectively the same as if you had written this type instead:
```ts
type KM = {
  type: keyof M;
  value: M[keyof M];
  children?: KM[];
}
```
