### ISSUE TITLE
Missing types for WebTransport API W3C Current Spec (as implemented in Chrome/Edge atm)

### ISSUE THREAD

**Issue by tchakabam** [microsoft/TypeScript#51912]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2017` and my *lib* is `["esnext", "DOM"]`.

## Missing / Incorrect Definition

See https://www.w3.org/TR/webtransport/ or https://w3c.github.io/webtransport/

and https://devblogs.microsoft.com/dotnet/experimental-webtransport-over-http-3-support-in-kestrel/

Knowing this is still a WIP Standard draft, what is the TypeScript projects policy with regard to such support in the built in libs? 

## Sample Code

For examples look at https://web.dev/webtransport/

## Documentation Link

As above

**Comment by MartinJohns** [comment]
Usually definitions are not added for experimental specs, and they wait for at least two major runtimes to support it (Chrome and Edge are the same).

**Comment by tchakabam** [comment]
Ok, that is understandable, especially since a draft spec is by def potentially subject to future changes.

I am maintaining some self-crafted (but complete and accurate) typings of the current WebTransport API on JS side, based on the W3C IDL code in the [spec](https://www.w3.org/TR/webtransport/). 

It was actually quite interesting having to perform a manually driven mapping process from the WebIDL to TypeScript :) 

Surely could be an interesting project of its own to automate that (which I am sure is fully possible as IDL easily supersedes TS/JS in granularity and adjectives amount). 

Anything already exists in this direction? Surely would eventually help generally keep TS decl libs of standard APIs coherent and vice-versa?

**Comment by MartinJohns** [comment]
> Surely could be an interesting project of its own to automate that (which I am sure is fully possible as IDL easily supersedes TS/JS in granularity and adjectives amount).

You might want to check out: https://github.com/microsoft/TypeScript-DOM-lib-generator

**Comment by tchakabam** [comment]
Cool, thanks for this also. Would have been surprised if MS didnt have something there already.

And btw, please let me know here anyone interested on the WebTransport decls I have in case collaborating/open-sourcing could make sense (would need to check with employer).

**Comment by tchakabam** [comment]
Seems https://github.com/giniedp/webidl2ts is the only tool out there really doing the WebIDL -> d.ts job. What @MartinJohns pointed at seems to be more like a central decl repo that gathers input from other sources that are not obvious... 🤔 see also what OP says here: https://github.com/emscripten-core/emscripten/issues/9674

**Comment by RyanCavanaugh** [comment]
Please file a new issue once this is out of experimental phase. Thanks!
