### ISSUE TITLE
proagram doesn't typecheck anymore in 4.9

### ISSUE THREAD

**Issue by sigmaSd** [microsoft/TypeScript#51910]
# Bug Report

### 🔎 Search Terms
  typeof

### 🕗 Version & Regression Information

typescript 4.9

- This is a compile error
- This changed between versions 4.8  and 4.9

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/ATCWDsBcFMCcDMCGBjawDyAjAVtZlgBvAKBBAHpzgATacAewFoAbCSR0AcwdjQcegAPAA6tkodonABPUmWGhh0ADwBVAHwAKeOABcwTYn1TpASmABedcFWn9qgNxyAvsWJZc+AHTDY9SP7SSj6KaBbA8ACu4Pig9ODAalo6+ob6kEHQ9PDAkAAWoADO5lY25iQgvJCRsAk6mvlFpk7OTkA)

### 💻 Code

```ts repro
  interface Object {
    pipe<U>(fn: (a: any) => U): U;
}

Object.prototype.pipe = function <U>(fn: (a: typeof this) => U) {
  return fn(this);
};
```

### 🙁 Actual behavior

errors with

```
error: TS2304 [ERROR]: Cannot find name 'this'.
Object.prototype.pipe = function <U>(fn: (a: typeof this) => U) {
```
### 🙂 Expected behavior
It used to typecheck in earlier versions

**Comment by RyanCavanaugh** [comment]
This never actually worked
```ts
const m = { foo: 3 }.pipe(j => j.baz);
// j: any
```

I think you want
```ts
Object.prototype.pipe = function <U, T>(this: T, fn: (a: T) => U) {
  return fn(this);
};
```

**Comment by sigmaSd** [comment]
It works, it seems like you have a typo there, baz instead of foo

**Comment by sigmaSd** [comment]
Maybe you mean the types not working ?

I can close this, if this is just all correct, I just want to bring to notice that 4.8 it had no error and 4.9 it does

[4.9](https://www.typescriptlang.org/play?ts=4.9.4#code/ATCWDsBcFMCcDMCGBjawDyAjAVtZlgBvAKBBAHpzgATacAewFoAbCSR0AcwdjQcegAPAA6tkodonABPUmWGhh0ADwBVAHwAKeOABcwTYn1TpASmABedcFWn9qgNxyAvsWJZc+AHTDY9SP7SSj6KaBbA8ACu4Pig9ODAalo6+ob6kEHQ9PDAkAAWoADO5lY25iQgvJCRsAk6mvlFpk7OTkA)
[4.8](https://www.typescriptlang.org/play?ts=4.8.4#code/ATCWDsBcFMCcDMCGBjawDyAjAVtZlgBvAKBBAHpzgATacAewFoAbCSR0AcwdjQcegAPAA6tkodonABPUmWGhh0ADwBVAHwAKeOABcwTYn1TpASmABedcFWn9qgNxyAvsWJZc+AHTDY9SP7SSj6KaBbA8ACu4Pig9ODAalo6+ob6kEHQ9PDAkAAWoADO5lY25iQgvJCRsAk6mvlFpk7OTkA)

**Comment by RyanCavanaugh** [comment]
It was just a bug that this was allowed in the first place. It doesn't "do" anything without a corresponding `this` parameter
