### ISSUE TITLE
vscode stuck on Initializing JS/TS language features on Apple Silicon.

### ISSUE THREAD

**Issue by kartikbhalla12** [microsoft/TypeScript#51927]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0, OS: Darwin arm64 22.1.0
- OS Version: Mac OS Ventura 13.0.1 (22A400) (Apple Silicon, M1 Pro)

Steps to Reproduce:

1.  Created a React-Native Project based of typescript, and have path alias added in babel.config.js and tsconfig.json
2. When project opens, it shows initialising JS/TS features and disappears normally
3. After some time (around 10 mins while developing in code, this randomly appears and never stops).
4. This, stops intellisense to work and have to manually restart TS server

I have tried all the possible solutions provided in microsoft/vscode#68896 and none of them seem to work. I have tried clearing cache and re-installing vscode but issue still seems to persist.

After manually restarting ts server, this message doesn't seem to persist and works normally but after sometime again this appears

Attaching TS server logs and babel.config and tsconfig

babel.config.js

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
        alias: {
          '@assets': './src/assets',
          '@api': './src/api',
          '@app': './src/app',
          '@components': './src/components',
          '@config': './src/config',
          '@constants': './src/constants',
          '@content': './src/content',
          '@hooks': './src/hooks',
          '@icons': './src/icons',
          '@interfaces': './src/interfaces',
          '@navigation': './src/navigation',
          '@screens': './src/screens',
          '@services': './src/services',
          '@styles': './src/styles',
          '@types': './src/types',
          '@utils': './src/utils',
        },
      },
    ],
    ['react-native-paper/babel'],
    ['optional-require'],
  ],
};

```

tsconfig

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "@api/*": ["api/*"],
      "@app/*": ["app/*"],
      "@assets/*": ["assets/*"],
      "@components/*": ["components/*"],
      "@config/*": ["config/*"],
      "@constants/*": ["constants/*"],
      "@content/*": ["content/*"],
      "@hooks/*": ["hooks/*"],
      "@icons/*": ["icons/*"],
      "@interfaces/*": ["interfaces/*"],
      "@navigation/*": ["navigation/*"],
      "@screens/*": ["screens/*"],
      "@services/*": ["services/*"],
      "@styles/*": ["styles/*"],
      "@types/*": ["types/*"],
      "@utils/*": ["utils/*"]
    },
    "skipLibCheck": true
  },
  "extends": "@tsconfig/react-native/tsconfig.json"
}
```

[tsserver.log](https://github.com/microsoft/vscode/files/10243090/tsserver.log)

**Comment by mjbvz** [comment]
Looks like the last message in the log is:

```
Info 1029 [11:37:16.996] Reloading configured project /Users/kartik.bhalla/Desktop/Projects/study-abroad-mobile-app/tsconfig.json
Info 1030 [11:37:16.996] event:
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/Users/kartik.bhalla/Desktop/Projects/study-abroad-mobile-app/tsconfig.json","reason":"Change in config file detected"}}
```

This suggests that TS may be trying to load the project when it gets stuck but it's hard to tell since nothing else is logged

**Comment by kartikbhalla12** [comment]
@sheetalkamat let me know if you need any further logs from my end.

Thanks.

**Comment by sheetalkamat** [comment]
Are you still able to repro this issue. 

In the logs I see that tsserver is getting notifcation that file: `/Users/kartik.bhalla/Desktop/Projects/study-abroad-mobile-app/tsconfig.json` is changed. There seem to be many notifications oif that which keeps reloading the project. Can you please share the complete project along with the repro tsserver log so i can try to run similar steps to try it out locally to see what could be causing this.

**Comment by kartikbhalla12** [comment]
Hi @sheetalkamat 

I'm still facing the same issue. I won't be able to share the source code for this project as this is for the company I'm working with (upGrad).

However, I'll create a new project with the same configuration and will share it with you this weekend. Hope that's okay with you.

**Comment by bennyk8y** [comment]
Our entire development team suffer from this issue as well. Not sure its related to Apple Silicon or not, but our setup is different as its pnpm monorepo (e.g without babel).
Iv'e shared our codebase with VSCode team.

**Comment by Ambroza888** [comment]
Any solution to the issue? I am having the same issue and it is breaking everything ... It keeps spinning and stopping 'Initializing JS/TS language features'

I reinstalled the Vscode, moved to a different folder repo, used the insider version, and followed the [comment](https://github.com/microsoft/vscode/issues/68896#issuecomment-465373515) in the logs it kept 'detecting change in the tscofing.ts'

It keeps happening ... ;/

**Comment by Ambroza888** [comment]
This one will fix your issue. https://www.codejourney.net/how-to-fix-visual-studio-code-intellisense-loading-infinitely/

Also if you open two repos in one folder for example MAIN FOLDER -> FE repo & BE repo make sure you enter inside of the BE or the FE and then follow the steps from the link I sent.

Happy coding.

**Comment by jakebailey** [comment]
Can someone provide the verbose logs? That's what was requested. A description of them like "keeps detecting changes in tsconfig" is helpful, but not as good as the logs, which is what was requested.

**Comment by kartikbhalla12** [comment]
@jakebailey these are the verbose logs only, I was not able to get more detailed logs than these. PS. still facing the issue.

**Comment by c0nf1gur4t0r** [comment]
Same problem here!

**Comment by sheetalkamat** [comment]
@kartikbhalla12 to me this looks like it should have fixed with #56403 
Can you try typescript nightly and see if this is fixed. Thanks

**Comment by kartikbhalla12** [comment]
@sheetalkamat this seems to working fine now. Was waiting for this for a long time. Thanks a lot!

**Comment by ssadel** [comment]
for me, deleting node_modules + ts compiled dir fixed my issue

**Comment by sadjow** [comment]
If you encounter this issue, go to the output tab next to the terminal, select the Extension Host option, and you will see which extension is causing the initialization to freeze. You will need to uninstall it until the extension is updated to fix the issue.

**Comment by iamgabrielsoft** [comment]
2025-10-08 14:45:46.403 [info] Starting TS Server 2025-10-08 14:45:46.403 [info] Using tsserver from: /Applications/Windsurf.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js 2025-10-08 14:45:46.403 [info] <syntax> Forking... 2025-10-08 14:45:46.403 [info] <syntax> Starting... 2025-10-08 14:45:46.403 [info] <semantic> Forking... 2025-10-08 14:45:46.403 [info] <semantic> Starting... how do i get to this path Using tsserver from: /Applications/Windsurf.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js

**Well @sadjow was spot on. In 2025, this is still happening unfortunatelly. But mine was my tsServer that's was crashing. This is how I resolved it**

1. Installed JavaScript TypeScript Nightly
2. Created a .vscode folder in root directory
3. Added a settings.json to .vscode directory with the following code:
`{
    "typescript.tsdk": "./node_modules/typescript/lib"
 }`
4. Developer: Reload window

**Comment by robeverett** [comment]
I'm suffering the same issue, when I try and run an Angular app in VS Code.

Node version 22.12.0
npm version 11.5.2
global Angular CLI version 20.3.4

**Comment by iamgabrielsoft** [comment]
Hey @robeverett,  what's have you done to make the error go away so far?

**Comment by robeverett** [comment]
It's gone away on its own, after updating VS code.

But I noticed in the output Extension Host tab I was getting:

[warning] DiagnosticCollection with name  'eslint' does already exist

**Comment by Qminn1199** [comment]
In my case, the issue was caused by the VS Code Atlassian extension.
Even VS Code updates weren't working, but everything was fixed immediately after I removed that extension.
