### ISSUE TITLE
`const` doesn't work with `extends`

### ISSUE THREAD

**Issue by diegohaz** [microsoft/TypeScript#51931]
# Bug Report

I'm not sure if this is intended behavior. If this is not a bug, I'd suggest supporting this as a feature.

### 🔎 Search Terms

const, args, generic args, extends

### 🕗 Version & Regression Information

v5.0.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221217#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVNQB4w8BnDeAFXhAA8MRVhT4pUBPAbQF0A+ACgB0w2AHNSALioBKKZQDcAKEUlU5VvAC8BfgCIougDRIoEUiGlKA9Ffh34APQD8ioA)

### 💻 Code

```ts
declare function fn<const T extends any[]>(...args: T): T;

const a = fn("a", false);
```

### 🙁 Actual behavior

The return type is `any[]`

### 🙂 Expected behavior

The return type should be `["a", false]`

**Comment by MartinJohns** [comment]
Just pointing out that `readonly any[]` does work.

**Comment by ahejlsberg** [comment]
This is working as intended. See the last part of the description [here](https://github.com/microsoft/TypeScript/pull/51865#issue-1492198208) for the rationale.

**Comment by Andarist** [comment]
Oh, that... it is somewhat unexpected at the first glance but in retrospect, I understand this reasoning. But in such a case - `const` modifier with a mutable array constraint doesn't make sense. Could we add a diagnostic about this?

Those two are also interesting but I don't have a clear understanding of what a spread does to a type parameter, so maybe both here are exped. Could you take a look?
```ts
declare function fn<const T extends any[]>(...args: [...T]): T;

const a = fn("a", false);
//    ^? [string, boolean]

declare function fn2<const T extends readonly any[]>(...args: [...T]): T;

const a = fn2("b", true);
//    ^? [string, boolean]
```

Should the second one benefit from `const`? The `readonly` modifier seems to be always lost when spreading (existing behavior predating `const`) and that's probably why the first one doesn't "fallback" to the constraint type but perhaps the inferred elements for the second one should be narrowed down here?
