### ISSUE TITLE
`const` type parameter modifier: Condition loses type

### ISSUE THREAD

**Issue by L13** [microsoft/TypeScript#51939]
# Bug Report
A condition loses the type. It seems to me like a bug, because it makes further operations impossible.

### 🔎 Search Terms
const, args, generic args, extends, array, tuple, readonly, condition

### 🕗 Version & Regression Information
5.0.0-dev.20221218

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221218#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVPwB4w8BnDeAFXhAA8MRVhT44pg8IBPeNAa1Q4A7qgDaAXQB88ABQA3KBGQhSALio16jZqxDtOPfoJET4Afg3rUIOSBgBKdZQDcAKFclU5eFHgBeAhlRAAYAGngARnCAJnF7NwB6BPgU+AA9C1RkAFsAIzsJIA)

### 💻 Code
```ts
declare function fn <const T extends readonly unknown[]> (values: T extends readonly unknown[] ? T : never): T;

const a = fn([0, 1, 2]);
//    ^? number[]
```

### 🙁 Actual behavior
The return type is `number[]`

### 🙂 Expected behavior
The return type should be `readonly [0, 1, 2]`

**Comment by andrewbranch** [comment]
Can you give a more realistic example?

**Comment by andrewbranch** [comment]
You need the `extends` type of the conditional to contextually type the argument too, so that something like this works:

```ts
declare function fn <T>(values: T extends { x?: [number, number], y?: "hello" } ? T : never): T;

// Needs contextual typing so we infer a tuple instead of
// number[] and "hello" instead of string
const a = fn({ x: [3, 2], y: "hello" }); 
```

That’s certainly what’s interfering with this—not sure off the top of my head whether it makes sense, or is easy, to combine that with the `const T` contextual type somehow.

**Comment by L13** [comment]
If I understand the description of the PR correctly, a function call can now be written like `fn([0, 1, 2])` without `as const` at the end, but it works in the same way like `fn([0, 1, 2] as const)`.

Here is an example from some actual code. The type for the second param should throw an error if a value is used more than once. If `as const` is used it works like expected. You find the code for the type below.

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221218#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVKwgxBgEEYBzAZ3gB4AVeEAD2NWBoCVwcZhaqGGFlQUANPDQBrVDgDuqAHwSweQfADSTViHY04UYHggBPeAAopIEzkTx6ASgDaAXUUXY1AFz2JVk1Q+ACJYgiKYtBqKDj4AClhgUgwSGk6oyAC2AEYkbgDcAFAFqqjqUPAAvAREJOTU5gDe8FA+AIwSWT4ATCo+AMzwAL4STgDkUKMS46MuDoUA9PPwyyura+sbm2sAegD88ADKABY4yBDA8BhHMPLN+CQ3MEUl6lmV1cRklFSNzW0d3V68AGw3gYwmUwmLmaNBeGDmBUWW2RKJRe3gAHVeFIaBAsFZtAAHcDEYBFDAmYnwADy6AQDG0bA48AMRlQpkkqBk8lQrgknEZumZ0lkClc7iqBWWjBYTJoThEiBI8AAYlgYIIJAA6HWK5XcQQuKXwfZqjUYQV6eCcNKZHIwI2rfa0sAgWgGjD8xTG5Y+F1uj0jHVazgSM2G72+lkgQzGMxOYOh+DB+guQoFClUkJhdAWhmyoX6GNsjkinni97+5Jg-JAA)

```typescript
declare function filterArgs <T extends Record<string, unknown>, const K extends readonly (keyof T)[]> (args: T, keys: Distinct<K>): Pick<T, K[number]>;

const a = filterArgs({ a: 1, b: 2, c: 3 }, ['a', 'a']);
//                                         ^? Should throw an error

const b = filterArgs({ a: 1, b: 2, c: 3 }, ['a', 'a'] as const);
//                                         ^? Works like expected
```

Here is the code of the `Distinct` type:

```typescript
type Once <T extends readonly unknown[], R extends unknown[]> = 
  T extends [infer First, ...infer Rest]
  ? First extends R[number]
    ? Once<Rest, R>
    : Once<Rest, [...R, First]>
  : readonly [...R, ...T];

type Distinct <T extends readonly unknown[]> = Once<T, []>;
```

I figured out that the condition loses the type. If the type is copied like `Distinct<[...K]>` or `Once<[...T], []>` before the condition, it works, but that doesn't seem intended to me.

**Comment by ahejlsberg** [comment]
This is working as intended. The `const` modifier only affects an argument if it directly types that argument or is a constituent of a union type that directly types that argument.
