### ISSUE TITLE
Internal npm package imports are conflicting/confusing TS with local imports

### ISSUE THREAD

**Issue by mzdr** [microsoft/TypeScript#51949]
# Bug Report

I am using TypeScript 4.8 and have basically configured everything to esnext/nodenext. When I have a npm package that uses/provides ES modules and has `exports`/`imports` declared in their `package.json`, TypeScript gets confused if I use the _same_ files and `imports`/`exports` configuration as the npm package.

I made a repository for reproduction: https://github.com/mzdr/package-imports-duplicate-name-issue
(I pushed everything, just run npx tsc in root folder).

The core issue is: If npm package `A` has `import … from "#abc"` and I have a `abc.mts` file in my project, TS tries to do the imports from my file instead of the npm package.

### 🔎 Search Terms

package imports exports fail
duplicate imports resolves incorrectly
imports fail

### 🕗 Version & Regression Information

- v4.8 and next (Gerrit0 from Discord tested on next)

### 🙁 Actual behavior

> mock_modules/my-custom-package/dist/index.d.mts:1:10 - error TS2305: Module '"#error"' has no exported member 'ErrorMessage'.
>
> 1 export { ErrorMessage } from "#error";
>           ~~~~
>
>
> Found 1 error in mock_modules/my-custom-package/dist/index.d.mts:1

But this is not true, as `error.d.mts` has `export declare const ErrorMessage = "This will not work";` but as I said, I think TS is trying to import it from my projects `error.mts` because I have `"#*": ["*.mjs"]`, and the same `error.mts` as well.

### 🙂 Expected behavior

Node itself doesn't have any issues running the transpiled  code, so `node dist/index.mjs` just works fine. Its just the compiler that hiccups.

So TypeScript should import `ErrorMessage` properly from its npm package, not from my local `error.mts`.

**Comment by andrewbranch** [comment]
It’s because of your `paths`/`baseUrl` setting in tsconfig.json. If you delete that it works correctly.

**Comment by andrewbranch** [comment]
Tip: `tsc --traceResolution` told me this, and is a handy tool for anyone trying to put together a package structure with these kinds of things.

**Comment by mzdr** [comment]
Interesting. 🤔 So if I go full pull on ES Modules `tsc` basically gets its information regarding resolving from `package.json` and doesn't need any configuration regarding resolving anymore in `tsconfig.json`? Good to know and awesome at the same time.

Thanks @andrewbranch.
