### ISSUE TITLE
No high order generics binding

### ISSUE THREAD

**Issue by MOZGIII** [microsoft/TypeScript#51947]
# Bug Report

```ts
type GenericBinding<
    F extends <T1>(value: T1) => any,  // take a generic fn with T1 parameter
    T2,                                // also accept a T2 parameter
> = F<T2>;                             // bind the generic of F to T2
```

This does not work, although https://github.com/microsoft/TypeScript/pull/47607 claims to have solved https://github.com/microsoft/TypeScript/issues/40542 which is essentially this.

Test:

```ts
function myfn<T1>(value: T1) {};

const assert1a: typeof myfn extends (<T>(value: T) => void) ? true : false = true;
const assert1b: (<T>(value: T) => void) extends typeof myfn ? true : false = true;

type Test = GenericBinding<typeof myfn, string>; // bind `T1` at `myfn` to `string`, should get `(value: string) => void`

const assert2a: Test extends ((value: string) => void) ? true : false = true;
const assert2b: ((value: string) => void) extends Test ? true : false = true;

const assert2c: Test extends (<T>(value: T) => void) ? true : false = false;
const assert2d: (<T>(value: T) => void) extends Test ? true : false = false; // broken
```

### 🔎 Search Terms

High order generics.
#40542
#47607
#37181

### 🕗 Version & Regression Information

4.6 till 4.9.

### ⏯ Playground Link

[Playground link with relevant code](
https://www.typescriptlang.org/play?#code/C4TwDgpgBA4hB2EBOBLAxgIRfAJtg5gDwCwAUFBVAGJQQAewCOAzlIQCoCMAfABQBuAQwA2AVwgAuKFwCUUALzcog+CAA0FAPSaowQQGtogqPgTJ0UAGbwoAdxTAAFtM5QwgpIIC2ERkjKU0gBMgaFh4RGU2srCzAD2ymhoEGDAysFuHt6+yGRK8tQcQdwA3JHl5dEARtg4uo7QpoioaFBxltS6CexBZGSWovBowChxNl4g1hw8AiLiUrJQAN4AviV9pGhjzGmCzMzIwJyCUqCQ7VAT1rQMTKy8HHxCYpLScopQ-HEoOHIA-LokOIoFJLCIDgpAeJ1pttrt9odOFUpA92E85q92O8lF8fnJ6IxcKwzhALlcbADgEDoKDwdAClToRsSdIIDtIXBmugsLgCIQSWTJvANDtUPB8KUoNValAAAZcWXKNKy8mK4AJWWigiykWOOKiYR1UzK2YvKRa8XYz7fHCyjZbeDsvYHJDAIInVnsgl3KC8U3zKAW-BW3G-KCU6kgqx0yGMiAwh1OhGuoLI33+15BkM2-G3ImetIR4G02L0qHxqU6KpIOKGeD2uHKZNutALNlpb351Hos1vBQ4nPh8tRsGlyGjg5lao1utkRPwl1unAox4ZhbZvE3QksAtDuMjmMFCfxshAA)

### 💻 Code

See above.

### 🙁 Actual behavior

Compiler error `Type 'F' is not generic.ts(2315)`.

### 🙂 Expected behavior

Actual evaluation of generics.

**Comment by andrewbranch** [comment]
`F` is a type, while #47607 and #40542 are about values.

**Comment by MOZGIII** [comment]
#40542 is clearly about types, #47607 only partially solves the issue described. If you follow what's going on at the code that is mentioned at #47607, the devs there were unable to meaningfully use the limited solution provided by #40542. I'd say that issue has to be reopened, as well as this one, which poses the same issue but in an explicitly broader sense.

This issue is marked with `Working as intended`, is it because it was submitted as a bug?
