### ISSUE TITLE
Error with `is` assertion when using `exactOptionalPropertyTypes` and indexed fields from another interface

### ISSUE THREAD

**Issue by hasezoey** [microsoft/TypeScript#51953]
# Bug Report

### 🔎 Search Terms

exactOptionalPropertyTypes
is
assertion

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDLKRYCeA-AFzJZSgDmA3HgL556iSyIoDyADmGAB7EBlwEimMFXRYA2gHJiYEgoC6TQgHotyEEOTQoQqMgDuACwghkAEyH0iV5DCEAbN0LP0JOyVioaek1kPxNfXWVKajBaEEYWNlsIBDc4KBQYAFcQBEERZFBUrOSMAEEPACUIAEcs4AzbfnzRAAohAWFRKgAFdME4NwAeZq6MAD4ASioOlrFgMVGRDCYgA)

### 💻 Code

```ts
interface Test {
  testy?: string;
}

interface Options {
  test: Test['testy'];
  // no error when doing the following
  // test: string;
  // or
  // test?: string;
}

declare function includesAllRequiredOptions(options: Partial<Options>): options is Options;
```

with tsconfig option `"exactOptionalPropertyTypes": true`

### 🙁 Actual behavior

Error:
```txt
src/test.ts:15:84 - error TS2677: A type predicate's type must be assignable to its parameter's type.
  Type 'Options' is not assignable to type 'Partial<Options>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
    Types of property 'test' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.

15 declare function includesAllRequiredOptions(options: Partial<Options>): options is Options;
```

### 🙂 Expected behavior

No error

---

i think this *may* be related to https://github.com/microsoft/TypeScript/issues/51638, though in this case it also happens on typescript 4.8 and nightly

Reproduction Repository & Branch: https://github.com/typegoose/typegoose-testing/tree/typescript49ErrorAssertion

**Comment by Andarist** [comment]
Looks like a bug to me since this is OK:
```ts
interface Test {
  testy?: string;
}

interface Options {
  test: string | undefined; // where the type of this property is the same as the type of `Test['testy']`
}

declare function includesAllRequiredOptions(options: Partial<Options>): options is Options;
```

**Comment by fatcerberus** [comment]
Definitely looks like a bug.  Interesting observation: when autocompleting `partialFoo.test`, its type is shown in the suggestions list as being `test?: string`, but if you trigger completions on it after it's already been completed, you see `test?: string | undefined`.  However, you can't assign `undefined` to it.  TS apparently can't decide which one it is.
