### ISSUE TITLE
Allow to remove keys from index type

### ISSUE THREAD

**Issue by Fuzzyma** [microsoft/TypeScript#51952]
# Suggestion

## 🔍 Search Terms

index type, omit keys

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It is not possible to create a type, that has an index type + properties of a different type:

```ts
type A {
  [key: string]: number;
  foo: string
} // error
```

However, this case is not unsual and should be considered.
To achive that, it is needed to remove certain keys from the index. 
In the definition above, this could simply be done by removing all defined keys (in this caseonly "foo") from the index automatically.

Removing keys from the index is also useful if you wanna add attributes with different type:

```ts
type A = Record<string, number>
type B = Omit<A, "foo"> & { foo: string }>
```

We could even go as far as making this work:

```ts
type A {
  [key: Extract<string, "foo">]: number;
  foo: string
}
```

A differen way of doing this without as much possibilities is to allow for negated matches in string literals:

```ts
type A {
  [key: `!foo${string}`]: number;
  foo: string;
}
```

(a similar issue for that example is here: https://github.com/microsoft/TypeScript/issues/49867)

## 📃 Motivating Example

I guess I cramped all infos into the summary, I am sorry 

## 💻 Use Cases

Atm, mixing index types with other types is almost impossible. If you know, that you get an object that has certain typed values but also know that ONE keys is always set and different, you cannot type this properly atm because you cant have an index type + a different other key.

**Comment by jcalz** [comment]
Also duplicate  of #17687
