### ISSUE TITLE
TS Server confusing files in monorepo with same package id due to multiple package.jsons with same `name`

### ISSUE THREAD

**Issue by FlandreDaisuki** [microsoft/TypeScript#51976]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.74.0 (Universal)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:43:37.594Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
```

```
版本: 1.74.1
提交: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
日期: 2022-12-14T10:35:03.979Z
電子: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
作業系統: Linux x64 5.4.0-135-generic
Sandboxed: No
```
- OS Version: MacOS BigSur 11.7, Linux Mint 20.1 

Steps to Reproduce:

1. Clone the [reproduce repository](https://github.com/FlandreDaisuki/reproduce-volar-syntax-highlight-bug) and install [volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar)
2. Run `Volar (Debug): Write Virtual Files` command
3. Disable Volar Extension in the workspace and reload vscode (or just open by `code --disable-extensions`)
4. Inspect `src/Hello/World/World.vue.js` & `src/Bye/World/World.vue.js`

There is a simple video to describe the issue:
https://raw.githubusercontent.com/FlandreDaisuki/reproduce-volar-syntax-highlight-bug/master/demo.mp4

**Comment by mjbvz** [comment]
Thanks @yume-chan! Confirmed this with TS 4.9.4

**Comment by andrewbranch** [comment]
Wow, this is bananas. I thought about it for a minute and think I know the cause, so I retitled it to emphasize the package.json similarity and the totally corrupted state.

**Comment by sheetalkamat** [comment]
This seems like intended behavior. In order for packages to be deduplicated and included only once, we identify them by name in 'package.json' and version. Thus, mentioning the path or any other information may make that impossible. Additionally, where should the line be drawn in path to incorporate the package name.

Based on repro if  `a/Foo` and `b/Foo` need to be distinct then you need to indicate so in `package.json` name so they are not confused with one another.

**Comment by johnsoncodehk** [comment]
@sheetalkamat Thanks for your answer, and I think it should at least be classified as a "design limitation" instead of "working as intended".
