### ISSUE TITLE
Empty array (`[]`) inferred to be `never[]` instead of `[]` or `undefined[]`

### ISSUE THREAD

**Issue by maranomynet** [microsoft/TypeScript#51979]
# Bug Report

I ran into this behavior where TypeScript infers that an empty array (literal `[]`) to be of type `never[]`, which it interprets to never happen and thus to be of no sigificance.

Runtime errors then ensue.

### 🔎 Search Terms

`"never[]" array`

### 🕗 Version & Regression Information

Affects all versions from 3.5.1 through 4.9.4 (and the nightly)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "common-bugs-that-arent-bugs"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/PTAEBUE8AcFMGUDGAnAltALqVA7AZrMgM6gYAWsosAtppKAAYDaAug6QPagBGlHepGJQY5YAN0Kt2AWABQIUAHcyqRGVCiJyUGQCG0ODhK6cAE1JkAriQxdeofhq5FUAc1R5VJxLAB0cxA4jLGRYLABeUABZXXJfZBNTDmoACgBKUAA+UAAGXwBWUAB+UCYAcjwODjKAGlAy7l1kMpZQXRJA4NAALlKWAG45BVARgD0iuSGwAAEMIgBaWAAPOEQMReRkDm1QFN5EXWthUIwmHLZQal16ewZLM1hPUVMGNICgoixKjl7PtBxXKBIicziwpiMIZCodCxhN5DM5osVrA1hstjs9ijDkRjmEmABGC5XG7Ce6mR64WAvN6yTqfHhNX4Yf6A4F4wngmFc6HjSbw0CAXg3AKS7wogKhIilQABspRYtoo2qBkPcMKhqJRCOidLopQJyJRVerfILAAJ77yMHClfilHFcKTkkO+vlsAFUDIQAMLtWDpGoOiGNZDOjgAGQ4BytYcUnu96TkNL5GCEoAAorQk0C+nJyYgpU1KHSsERqJZemm6KAAD6lP64Vx1WsAgbm+lMJquVqRYuWIA)

### 💻 Code

```ts
const ret = Math.random() > 0.5 ? ['foo', 'bar'] as const : [];
//    ^? const ret: readonly ['foo', 'bar'] | never[]

// @ts-expect-error  (because `ret[0]` may be `undefined`)
const foo: string = ret[0]
//                      ^? (property) 0: "foo"
// @ts-expect-error  (because `ret[1]` may be `undefined`)
const bar: string = ret[1]
//                      ^? (property) 1: "bar"

// 🔥🔥 This will throw a runtime error half the time. 🙀
console.log(
    foo.toUpperCase(),
    bar.toLocaleLowerCase()
)
```

### 🙁 Actual behavior

I get a TS error on the `@ts-expect-error` comment as the `ret` tuple is inferred to be effectively **always** `['foo', 'bar']`

...and then I get runtime errors once I try and do `.toUpperCase()` on the (sometimes `undefined`) values.

### 🙂 Expected behavior

I'd expect the inferred type of `ret` to be something like `readonly ['foo', 'bar'] | []` or possibly  `readonly ['foo', 'bar'] |  | Array<undefined>`.

To fix this I have to explicitly change the first line to either:

```ts
const ret = Math.random() > 0.5 ? ['foo', 'bar'] as const : [] as [];
```

…or:

```ts
const ret = Math.random() > 0.5 ? ['foo', 'bar'] as const : [] as const;
```

**Comment by fatcerberus** [comment]
Working as intended.  In this context `never` doesn’t mean “never happens” but rather indicates that the array contains only values of type `never` (which is trivially true—it’s empty).

The `never[]` typing for empty arrays is inconvenient, but is intentional because the alternatives are worse.  See https://github.com/microsoft/TypeScript/issues/51853#issuecomment-1347740712

**Comment by tylim88** [comment]
I am more concerned about array being any[]

```ts
const a = false || []
//    ^?
const b = []
//    ^?
```
![image](https://user-images.githubusercontent.com/5227509/208772802-c0b4c479-1485-4e92-a151-53efca81c972.png)

**Comment by fatcerberus** [comment]
@tylim88 It’s not really `any[]`.  It’s an evolving type, so if you `.push()` something into it, the compiler will infer the type of whatever value(s) you add.

**Comment by tylim88** [comment]
@fatcerberus 

I see

before evolve:
![image](https://user-images.githubusercontent.com/5227509/208778397-45fc8808-bc72-4692-aa52-1b5ed718579d.png)

after evolve:

![image](https://user-images.githubusercontent.com/5227509/208778467-0cfd156d-75ce-42fa-8c8c-d85fbdece768.png)

**Comment by maranomynet** [comment]
The JS code is obviously buggy, the conditional assignment to `res` is pretty straightforward, yet TypeScript fails to capture this and somehow this is fine?

Can anyone please help me understand why the runtime error is not a problem?

**Comment by fatcerberus** [comment]
That's completely unrelated to the `never[]` inference, though.  The runtime error still happens even if the inferred type is `any[]`, or `unknown[]`, because there's no bounds checking for array accesses, only for tuple types.  You might want to consider enabling `noUncheckedIndexedAccess` if that's a problem for you.

```ts
const ret = Math.random() > 0.5 ? ['foo', 'bar'] as const : [] as any[];
//    ^? const ret: any[] | readonly ['foo', 'bar']

const foo: string = ret[0]
const bar: string = ret[1]

// STILL throws a runtime error half the time.
console.log(
    foo.toUpperCase(),
    bar.toLocaleLowerCase()
)
```

**Comment by maranomynet** [comment]
In fact `noUncheckedIndexedAccess` makes no difference here, as the inferred type is to be *effectively just* `readonly ['foo', 'bar']`. Which is my point.

Not that I'm actively rooting for `any` but then the untrustworthyness of values pulled out of `ret` are at least somewhat more apparent

<img width="591" alt="image" src="https://user-images.githubusercontent.com/86827/209121296-bbcb105a-d71b-4c4a-b1ad-3437097a4df7.png">

[Playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ssl=10&ssc=1&pln=10&pc=67#code/MYewdgzgLgBATgU1gXhgWQIZQBYDo4ZgAmIAtgBQCUMAfDAAy4CsMA-DANoDkAZiCFwA0MLgCMMcLgF0YGCDFCRYALk4y5ssAE8OUgNwBYAFAB6EzAswAeu0XR4SVYR0yAPg4wkwAGy2de-EIi4pJSxsZ2sHwgMKiIUBz0Yabmlmnp1qwR4PYhsQ4JAIzJZhllmeEpMADKACoAkgAyjTA4cCAA7vIY8ACuYFAAlqQIMAhw7XAw2BjePK3Yo0MjuMalAEK9sFgw3ghysAAG0YeaRDCHIacSo6QgiDAgogBugyC9EL4wAET9UHAfKAde44LTfbKQEB7XDeEAAc3IxjS0VwUBAAFUAA6Y8YAYTkCCogjWqQqRjSIVRIEaIGAswQNI6eIJVBJlhsxkoxiAA)
