### ISSUE TITLE
Intersection of mapped type of with omit not compatible

### ISSUE THREAD

**Issue by robinchrist** [microsoft/TypeScript#51972]
# Bug Report

### 🔎 Search Terms

omit, mapped type, intersection

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, 3.5.1 up to 4.9.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAwg9gGwK4FsB2UC8UDeA3AQ2QgC4o1UAjCAJwF8AoJ0SKAJQhTjwgBUBLYAggBnADy9wEAHxZcDKFADaABRpxINUFH4YA1hBBwAZlEmQAumQDyKQRKmr1m0BYA0UAOTBBwz9IBuBjoghgBjBAIRETMCSmEAEQJgAgBxCDRaZLgaACYxBTMASQwIAA9gDIATGJxlMMQAOQIUUigRYBpdAHMrWERUDAAyXCgfITaOrrRuqDo5t0LeAEEqqqhyyrQa0aUGhGbWsimevvhkdCgRuvHhY86euafsHEZZHCZFBrQppDDgHIACkKijAXUIlSgYSICEoBDCejIwMUKJ023KZAoKGoNEWqMU6gA7mQOFweAIJuJeCVpCCoABKLCyNRwOwiCBiUncPi+UQSVZVaS0xSM16fKEACwIun5a1yGwq1Vq9SaLUmDxmZwGl2uY1592ms3mdGkyJRYUoSLpil0VQx5CotDx+KJJM43IpwipNKu7Hd5N5VIFwpRjMwzPUbI5XIDlNlVVyQsK9LIvDiiWSaQyWQBeQkJQ8KzWvqLCfedJoEGASBoGEyhNi8QgSRS6UyNGyeepaELApLAsTgKiIDQYSggNt5Q8ujASGAYfL+KhcB+wA2whQcgIhOla+AEv4IgAdNCELD4XoJ+iytO0LP50El98OuvOPLsNvd1DKFe7TfRkegEQBuHiAUeM5znM9KPi6VY1hgdRgcBb6gUBG5zDBih0NBhSMIwDBAA)

### 💻 Code

```
type Column = {value: number}


type RemoveTitles<Type> = {
  [Property in keyof Type]: Omit<Type[Property], 'title'>;
};

class TableDataGenerator2<
  TIn extends { [colName: string]: Column & { title: string } },
  TAdd extends { [colName: string]: Column & { title: string } } = {}
> {

  constructor(
    private callback: (
      index: number,
      row: RemoveTitles<TIn>
    ) => Promise<RemoveTitles<TAdd>>
  ) {}

  chain<TAdd2 extends { [colName: string]: Column & { title: string } }>(
    cb: (
      index: number,
      row: RemoveTitles<TIn> & RemoveTitles<TAdd>
    ) => Promise<RemoveTitles<TAdd2>>
  ): TableDataGenerator2<TIn, TAdd & TAdd2> {
    return new TableDataGenerator2<TIn, TAdd & TAdd2>(async (index, input) => {
      const elem = await this.callback(index, input);
      const elem2 = await cb(index, { ...elem, ...input });
      return { ...elem2, ...elem };
    });
  }
}
```
```
Argument of type '(index: number, input: RemoveTitles<TIn>) => Promise<RemoveTitles<TAdd2> & RemoveTitles<TAdd>>' is not assignable to parameter of type '(index: number, row: RemoveTitles<TIn>) => Promise<RemoveTitles<TAdd & TAdd2>>'.
  Type 'Promise<RemoveTitles<TAdd2> & RemoveTitles<TAdd>>' is not assignable to type 'Promise<RemoveTitles<TAdd & TAdd2>>'.
    Type 'RemoveTitles<TAdd2> & RemoveTitles<TAdd>' is not assignable to type 'RemoveTitles<TAdd & TAdd2>'.
```

### 🙁 Actual behavior
TypeScript does not detect that `RemoveTitles<T1> & RemoveTitles<T2>` is compatible with `RemoveTitles<T1 & T2>`

### 🙂 Expected behavior

`RemoveTitles<T1> & RemoveTitles<T2>` is compatible with `RemoveTitles<T1 & T2>` and should be treated as equivalent, [as can be seen in this example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShC2B7AbhAKgS2AGwgZwB41wIA+KAXigG8AoKKAbQAUAnRSV0KDAOygDWEEIgBmUYpAC6ALigB5eFiIkW7TqCkAaKAHJgWXLtIBuWgF8ztUJAn5gkiAEZKNAB5zqNiHN2jEiLo6-ohyvACu8ABGEKw6UQCGrHJ4wKx8AOY6Bjg+UABE2IjY+eY6IJ7evokAXkFQtSlpmdmGeYXFpebWJHapjgBMrtQ1lSS+CQAWCfVTCU3pvBnm3T22ACYQyC5UcEiomLmEaPaOTuQAZLAIKOhtx6ckA6Rr0JvIQ7s3B-dEj5AuK4nfpPF60AD04KgEDcYASvHWeCgiCiACsIABjYBQbxIxC8aC4VDYKCbCBgV5QACisPh6yI5CoaGhbmAEARSL4oliCigAH4aEwANI8fhCETieSyBSMIVSKDmKBhLaxKyQllwjnItGY7G4qCsTHhVh4DDEkCUmma9ZwDHG03mhmuZkwtlalHorH0fkSFluxGi7msXkC6jC0WCYRiBTSq10232s0QbAgAjyWVSciK5WoVjeuRoKzeUlbJyfam0hEJk1JlMEd7nSnvAbluNVo01x3N0hAA)

**Comment by RyanCavanaugh** [comment]
> TypeScript does not detect that `RemoveTitles<T1> & RemoveTitles<T2>` is compatible with `RemoveTitles<T1 & T2>`

It's not really clear how it *could*, either - the definition of this type is sufficiently complex that there isn't an obvious way to identify this fact apart from some very difficult counterfactual reasoning about possible inhabitants of `T1` and `T2`.
