### ISSUE TITLE
keyof of a second-order generic that extends `Record<string, unknown>`  is string | number | symbol 

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#51977]
# Bug Report

### 🔎 Search Terms

Narrowing  of record generic in a method of generic class  symbol 

### 🕗 Version & Regression Information

This is the behavior in every version I tried, including nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20221220#code/C4TwDgpgBAogbhAdsAzlAvFAShAxgewCcATAHhWEIEtEBzAGigFdEBrRfAd0QD4AoPqEhQAsiHhJgGKAG8+UBVEQBDALYQAXFArU6fAL4CAZi1zAq+RFGJUUYZcFwALUgBUoEAB7AkxNKwgQfCNYBGQUHgAKCDDgADk1TShXAEpZeUUCRAoPWK0xCWRpOUVSqAB6cuSnWyha-FYMsqVErRjJBPUmqENDPlwAG2UUNELgABFbe0cnCEJSGA9vX1HYiPTSsCYAIwGqXGsph2c3JZ9EPygAoJCYKPbkTqTUjeaoLJyH4HzxWOLut4VKqucDQADkOhotCgAB8lExVNs5rDtCBEfgBmC6mgOFJhigqLQVLtoMB8FAhODIXQwQA6AFvSpQADK5OAsygtCQc322DwRGI2KU+CkKkIhC4EEFYAlkEIAxAUFmhAgDOaKnUbViTzVPW6vQEg3xoUkkzsx2VADEqJ4FmcVibwjxXgomQBBYg2OjaShQurIOYoPDmSxQYZhqCcIisZQSljEbpbXa8mzmmanLznS7U6FQABkV0CwVg921rWSaRKbw+Ui+PzG-0BpQ1SS+OsBhlKvSAA)

### 💻 Code

```ts
type Events = Record<string, unknown>

type MyEvent = {
    name: string
}

function dispatch<T extends keyof Events>(eventName: T) {
    const event: MyEvent = {
        // This is ok
        name: eventName
    }
}

class EventDispatcher<E extends Events> {
    public dispatch<T extends keyof E>(eventName: T) {
        const event: MyEvent = {
            // Type 'string | number | symbol' is not assignable to type 'string'.
            // So the generic Record is not narrowed properly here
            name: eventName
        }
    }
}

class EventDispatcherFix<E extends Events> {
    // Adding string intersection as a workaround
    public dispatch<T extends string  & keyof E>(eventName: T) {
        const event: MyEvent = {
            name: eventName
        }
    }
}
```

### 🙁 Actual behavior

keyof of a second-order generic that extends `Record<string, unknown>`  is string | number | symbol 

### 🙂 Expected behavior

The type should be string.

**Comment by fatcerberus** [comment]
`extends` means “assignable to” so `E` might have numeric or symbol keys; extending a `Record<string, T>` doesn’t restrict you to only string keys.

**Comment by mckravchyk** [comment]
I got it, thanks.
