### ISSUE TITLE
Typescript docs clarify how to allow tree-shaking with `sideEffects`

### ISSUE THREAD

**Issue by konsalex** [microsoft/TypeScript#51983]
# Bug Report

Hey folks,

Recently I was struggling on finding the underlying cause of improper tree-shaking of a component library we are shipping with Neo4j.

Below you can see the tree-map that is generated from `rollup-plugin-visualizer`, and the website makes only those imports:

```
import { PlayIcon, ScaleIcon } from '@neo4j-ndl/react/icons';
import { Button } from '@neo4j-ndl/react';
```

![CleanShot 2022-12-21 at 10 00 44](https://user-images.githubusercontent.com/12672541/208863849-c9f7a9a8-03c0-4362-8003-2ea63065b23d.png)

All the packages are imported, which is not expected. I was trying to find info about how to set my `tsconfig.json` properly but everything was correct, until I stumbled upon [this article](https://www.smashingmagazine.com/2021/05/tree-shaking-reference-guide/) and found out that there is a property `sideEffects` and decided to give this a try.

Below you can see the updated tree-map and the tree-shaking is working as expected. Shouldn't this option be stated in the docs of Typescript `tsc`, for libraries that are not using `rollup` or `webpack` for compiling their source code?

![CleanShot 2022-12-21 at 10 05 59](https://user-images.githubusercontent.com/12672541/208865314-fb9a929f-1dca-4ab4-a7b4-1dd7648bdea4.png)

### 🔎 Search Terms

docs, tree-shaking, side-effects, tsc, typescript compiler

### 🕗 Version & Regression Information

Not a bug per se, just lack of documentation

### 🙁 Actual behavior

Tree-shaking was not enabled for a component library due to the `sideEffects` not being explicitly set alongside `tsc`.

### 🙂 Expected behavior

Working tree-shaking when web-app is bundled.

**Comment by MartinJohns** [comment]
`sideEffects` is not a TypeScript thing.

**Comment by konsalex** [comment]
@MartinJohns sure, but it affects the way `tsc` compiles code

**Comment by fatcerberus** [comment]
`tsc` doesn’t even *do* tree-shaking or bundling so this is not relevant to its documentation - even the article you linked said it’s something specifically for bundlers.  `tsc` just converts TS -> JS.

**Comment by MartinJohns** [comment]
> @MartinJohns sure, but it affects the way `tsc` compiles code

It doesn't. The term `sideEffects` does not appear in the source code anywhere.

**Comment by konsalex** [comment]
Yes @MartinJohns my bad thus closed the issue, the bundler was checking the package.json of the package
