### ISSUE TITLE
Generic of `keyof  { efg:[K: string]: number; }['efg']`  does not behave the same as Generic of `keyof  { [K: string]: number; }` 

### ISSUE THREAD

**Issue by tylim88** [microsoft/TypeScript#51982]
# Bug Report

Generic of `keyof  { efg:[K: string]: number; }['efg']` result in error but  Generic of `keyof  { [K: string]: number; }`  is fine

### 🔎 Search Terms

`keyof  { efg:[K: string]: number; }['efg']`  does not behave the same as `keyof  { [K: string]: number; }` 

### 🕗 Version & Regression Information

v4.9.4

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?#code/PTAEF5K6dh3A9gJwNYGdQDMCWA7AprEcSZAFB4Au+SmAhgMb6h0BGDA3qANoDSAXKDSUkeAOYBdQQFdcKXAji4A3KAC+ZMgwA2dNBgCCAIQDCAHgAqofAA9quACYY2DAHxkOZAJAB9AG6CFsqaXgwIuMJI0gyUyAAUAaAWAJSgnl5elAAW2GgAdP4QoH7BXhreALJxcIIo+ACeCJgs7KlcIKAIKN6ZOfn+3HAS3uVeFQBM1bUNTUltoB1dPdm5BX6Dw2UhFQDMU6B1jc2U9QAO+LMr-X7zi90ZV2sbI2TlmLIx2OGgNvUAXpZrHZ8I5nOxXHEroIuP5AuoADTFQJtbyPQrgYreMIRSigCpFfaHWYuVLgVxpBZgJYPPpPIYvULhYR48YEmoHGbNFIQcntKn3XqrAb0raMnF4nZs6ZHUAnc6XWn+Um8ymdAVo9YijTlDqkPXgGhIZAAQn1ZvAFFw1FojGYLgAjGlvPhMGJoTwBEIROIpKBZPJFCp1K9NDo9IZTPbAbZ7E4Wgx7e50rCksEsUyRNFYkgEsiKctFX4iiUXpVCZz4-buAByF1iasSW78gtCvx5OvPLaVSbsolcmt1htN0AAdQAEgBNAD8Leu7ddndGu3LMrlF2OhfnYmH1MFc47WpDZHeuE+31+fyjVhjILjDohUIpKasakRiW56Q1xfT4vxGJXxLsFWtaukOPIUncs5rFui4-syExShyMoWAOoGNuBfKjpOM40q2MGHmK8GSv+vYVmuCp4XWyoQc2uH7guh5qEAA)

### 💻 Code
```ts
// =====================works fine================================
interface abc{ [K: string]: unknown; }

class ABC<T extends abc>
{
	_v: T;

	constructor(v: T) {
		this._v = v;
	}

	M(w: keyof abc) { // ok
		this._v[w]
	}

	M2(w: keyof T) { // ok
		this._v[w]
	}

	M3(w: keyof typeof this._v) { // ok
		this._v[w]
	}
}

function xyz<T extends abc>(this: { _v: T }, v: T) {
	this._v = v
	const M = (w: keyof abc) => { // ok
		this._v[w]
	}
	const M2 = (w: keyof T) => { // ok
		this._v[w]
	}
	const M3 = (w: keyof typeof this._v) => { // ok
		this._v[w]
	}
}

// ======================error!==========================
interface abc1 {
	efg: { [K: string]: unknown; }
}

class ABC1<T extends abc1>
{
	_v: T;

	constructor(v: T) { 
		this._v = v;
	}

	M(w: keyof abc1['efg']) { // ok
		this._v.efg[w]
	}

	M2(w: keyof T['efg']) { // WHY?
		this._v.efg[w]
	}

	M3(w: keyof typeof this._v.efg) { // ok
		this._v.efg[w]
	}
}

function xyz1<T extends abc1>(this: { _v: T }, v: T) {
	this._v = v
	const M = (w: keyof abc1['efg']) => { // ok
		this._v.efg[w]
	}
	const M2 = (w: keyof T['efg']) => { // WHY?
		this._v.efg[w]
	}
	const M3 = (w: keyof typeof this._v.efg) => { // ok
		this._v.efg[w]
	}
}
```
### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/5227509/208794353-e7e61589-3c31-4e20-b4fa-43fda5749c4f.png)

above has no error

but after changing the type to `{ efg: {[k :string]: unknown }}` and trying to **get the same key**, it results in error

![image](https://user-images.githubusercontent.com/5227509/208794084-9b97a779-a7ba-4ea6-ba93-e95803ef6844.png)

### 🙂 Expected behavior

should not error

**Comment by nopeless** [comment]
I'm gonna say that typescript is right here

Example

T is {[K: string]: unknown}

efg can be {} (vacuously true)

keyof T is string

but keyof efg is never

**Comment by Andarist** [comment]
`never` is assignable to everything so that's not it - you can verify it by doing this (which type-checks just fine):
```ts
this._v.efg[w as never]
```

The problem in here is that `efg` can be `{ [k: string]: unknown; [k2: number]: unknown }`. The constraint defines the **minimum** - so yes, it has to have a string indexer, but it can also have more properties that are not strings. This one is totally valid per the required subtype relationships:
```ts
declare function fn<T extends Record<string, unknown>>(a: T): T;

const t = fn({
  foo: 1,
  42: "bar", // notice how this is using a key assignable to `number`, not to `string`
});
```

**Comment by nopeless** [comment]
> `never` is assignable to everything so that's not it - you can verify it by doing this (which type-checks just fine):
> 
> ```ts
> this._v.efg[w as never]
> ```
> 
> The problem in here is that `efg` can be `{ [k: string]: unknown; [k2: number]: unknown }`. The constraint defines the **minimum** - so yes, it has to have a string indexer, but it can also have more properties that are not strings. This one is totally valid per the required subtype relationships:
> 
> ```ts
> declare function fn<T extends Record<string, unknown>>(a: T): T;
> 
> const t = fn({
>   foo: 1,
>   42: "bar", // notice how this is using a key assignable to `number`, not to `string`
> });
> ```

I think I said the opposite

I was going between two examples where an additional number property was given or never being property. You are right
