### ISSUE TITLE
Typescript type guard not inferred string literal

### ISSUE THREAD

**Issue by itdolmatov** [microsoft/TypeScript#51980]
# Bug Report

### 🔎 Search Terms
string literal typeguard 

### 🕗 Version & Regression Information

 
- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/GYVwdgxgLglg9mABAcwKZQAqoE4FsYDOB8YBAFCATgFyIFTYxjICUA3gLABQiviMwRBSrZEAXgmIA5ACkAhhADWUlomzoQ2JFLkATfGCkBubnzUaticLtTAmqXSa4BfbhAT1EegwXGIA2lIAsjCKqFIANNIycOEAugB0uHIADmSo4gB8KOhYeITEHuksLEaIAPTlUACeKRlkAETeTA0APta29ros-nHc3KCQsAj8BAAinWAOADwAKplkcrSziK1WYDZ2U920cqOIK5w8fOpQmkh7AISSHVsOTq5cbh5QiMBw1gCC+ky+Yl4-UgJOwAGygODIhAmd26ZUqNTq+0azTAbVuXR6cUQACMQK9UAAPOrQByIJqAhq9Uz9LhAA)

### 💻 Code

```ts
function getPermissions(user: string){ //if change return type to :"admin"|undefined, the type guard works well. Function return type inferring could be a reason of a bug
    if (user === 'Jack') return 'admin';
    return undefined;
}
const admins = ['Mike', 'Joe'].map(e => getPermissions(e)); //type ("admin"|undefined)[]

function isDefined<T>(a: T | undefined): a is T {
    return a !== undefined;
}

const foundAdmins = admins.filter(isDefined); //type is ("admin"|undefined)[] but expected "admin"[]
```

### 🙁 Actual behavior

type of foundAdmins is ("admin"|undefined)[]

### 🙂 Expected behavior

expected type of foundAdmins is "admin"[]

**Comment by tylim88** [comment]
I think this is normal behavior, if we look at the type def of the native filter, they are
```ts
    /**
     * Returns the elements of an array that meet the condition specified in a callback function.
     * @param predicate A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array.
     * @param thisArg An object to which the this keyword can refer in the predicate function. If thisArg is omitted, undefined is used as the this value.
     */
    filter<S extends T>(predicate: (value: T, index: number, array: T[]) => value is S, thisArg?: any): S[];
    /**
     * Returns the elements of an array that meet the condition specified in a callback function.
     * @param predicate A function that accepts up to three arguments. The filter method calls the predicate function one time for each element in the array.
     * @param thisArg An object to which the this keyword can refer in the predicate function. If thisArg is omitted, undefined is used as the this value.
     */
    filter(predicate: (value: T, index: number, array: T[]) => unknown, thisArg?: any): T[];
```

which has nothing to do with the return of predicate

which mean you will get the same type regardless of the `predicate`
![image](https://user-images.githubusercontent.com/5227509/208795769-28afa364-f07f-405f-a66f-6deac327fcdf.png)

[playground](https://www.typescriptlang.org/play?ts=4.9.4#code/GYVwdgxgLglg9mABAcwKZQAqoE4FsYDOB8YBAFCATgFyIFTYxjICUA3gLABQiviMwRBSrZEAXgmIA5ACkAhhADWUlomzoQ2JFLkATfGCkBubnzUaticLtTAmqXSa4BfbhAT1EegwXGIA2lIAsjCKqFIANNIycOEAugB0uHIADmSo4gB8KOhYeITEHuksLEaIAPTlUACeKRlkAETeTA0APta29ros-nHcbh5QiMBw1gCC+ky+Yl6TpAl2ADZQOGRkLGKZbM6lFVW1GYRCTXNtHXZgDj1xiABGIEOoAB510A6IJwYNvdyVZogAPQA-KZ+lwgA)

**Comment by tylim88** [comment]
To solve this you can create your custom filter
```ts
function getPermissions(user: string){
    if (user === 'Jack') return 'admin';
    return undefined;
}
const admins = ['Mike', 'Joe'].map(e => getPermissions(e)); //type ("admin"|undefined)[]

function isDefined<T>(a: T | undefined): a is T {
    return a !== undefined;
}

const customFilter=<T,V extends (value: T, index: number, array: T[]) =>void >(array:T[], predicate:V ):Exclude<T,undefined>=>{

    return array.filter(predicate) as Exclude<T,undefined>

}
const foundAdmins = customFilter(admins,isDefined)
//    ^?
```
![image](https://user-images.githubusercontent.com/5227509/208797232-f26eb7e1-19e7-4c21-8b1e-f39047892ef5.png)

[playground](https://www.typescriptlang.org/play?ts=4.9.4#code/GYVwdgxgLglg9mABAcwKZQAqoE4FsYDOB8YBAFCATgFyIFTYxjICUA3gLABQiviMwRBSrZEAXgmIA5ACkAhhADWUlomzoQ2JFLkATfGCkBubnzUaticLtTAmqXSa4BfbhAT1EegwXGIA2lIAsjCKqFIANNIycOEAugB0uHIADmSo4gB8KOhYeITEHuksLEaIAPTlUACeKRlkAETeTA0APta29ros-nHc3KCQsAj8BAAinWAOADwAKplkcrSziK1WYDZ2U920cqOIK5w8fOpQmkh7AISSHVsOTq5cbh5QiBCUUHC4AGIwADZQHBiOYRABqiFQAA9ARtfGQAG5yP4gVDLKJMGyQ2hgEC4ABGOCicmw2Dk1WWvVUYky8LgMF0iAWxNJ5NmvSiKXUuhgEDkgOo4JY1AAopCIMibCDbl1MtSjqYThYLiSyQk7ACcGROQ4eXzUKo5L5ReKQJLZhFpdtMv0XM9SK9gHBrABBfRMXxiN4fL6-DXYRZu0gRQgTO7dbiVMwAPQA-DagA)

**Comment by jcalz** [comment]
> which has nothing to do with the return of predicate 

😕

> <code>filter\<<b>S</b> extends T>(predicate: (value: T, index: number, array: T[]) => value is <b>S</b>, thisArg?: any): <b>S</b>[];</code>


---

Here's the part that I find confusing about this behavior.  If you explicitly try to call the type predicate overload by manually specifying `"admin"` as the type argument, it fails:

```ts
const foundAdmins = admins.filter<"admin">(isDefined);
// Argument of type '<T>(a: T | undefined) => a is T' is not assignable to parameter of 
// type '(value: "admin" | undefined, index: number, array: ("admin" | undefined)[]) => value is "admin"'.
```

This is presumably caused by the same failure to infer as in the OP.  But that error message is... well, it's just not true, is it?  You certainly can assign `isDefined`  to that type:

```ts
const isAdmin: (value: "admin" | undefined, index: number, array: ("admin" | undefined)[]) => value is "admin" =
    isDefined; // looks okay to me
```

And if you do this then you get the correct narrowing:

```ts
const foundAdmins2 = admins.filter(isAdmin) // "admin"[]
```

So, uh, what's going on? 

[Playground link to code](https://www.typescriptlang.org/play?ts=4.9.4#code/GYVwdgxgLglg9mABAcwKZQAqoE4FsYDOB8YBAFCATgFyIFTYxjICUiA3gLABQifiMYIgpVsiALyTEAcgBSAQwgBraW2zoQ2JNPkATfGGkBuHv0TqompOF2pgTVLpPcAvjwgJ6iPQYITEANrSALIwSqjSADQysnARALoAdLjyAA5kqBIAfCjoWHiExJ4ZLCxGiAD0FVAAnqmZZABEPkyNAD42dg66LAHxPDygkLAIAgQAIl1gjgA8ACpZZPK0c4htiJ320z208mOIq1y8-BZW3ogAhFKb3c5u3O6eUIjAcDYAgvpMfuLeX6SJewAGygOBmzX+jUWhEmW0cZR4VUQ72wyBAuFQYGecCEtXqMnmi2WBzWGzAtjhPWy50IB2k+zAcGe8iIMGQYHkACMgZkoHBEKl5Nh5BjQWIcYhERVEHjMtIyAA3eRAkCoWgQgyNUk3bbRJi2AAetDA6M5OGiQuFNVoTRaYC16x18L6bHEOSVKsytI1rWkiQG3CRAElnoRDFAAPyPUihgifAw2j2q9V2h1kindPXk1BGxAm3Bm7AW7BWm0++3a7OU3rxV3u5Wq-blrXiUz8GFTRzlJFAuBwJR+fvyGoy-kYgMeGMvN7k+PfABM-jtBEBMBBYOb0Lj-xY0a8rw+-wIAGYl0fV+vsGRCHOwLvuJP9zPdLeCAAWM++C9i68TTu6cFUyyBFuCAA)

**Comment by tylim88** [comment]
~~oops~~
//================
some interesting thing I found, using example provided by @jcalz 

using type annotation get rid of the error

![image](https://user-images.githubusercontent.com/5227509/208825798-b357de21-acf9-4a7d-9b1d-020ae9b2daef.png)

[playground](https://www.typescriptlang.org/play?ts=4.9.4&ssl=5&ssc=13&pln=5&pc=38#code/GYVwdgxgLglg9mABAcwKZQAqoE4FsYDOB8YBAFCATgFyIFTYxjICUiA3gLABQifiMYIgpVsiALyTEAcgBSAQwgBraW2zoQ2JNPkATfGGkBuHv0TqompOF2pgTVLpPcAvjwgJ6iPQYK0yAEQ+TAGIAD6INnYOuiwA2gC6Eohx0gCyMEqo0gA0MrJw2QkAdLjyAA5kqBIAfCjoWHiExJ5VLCxGiDw8oJCwCAIEACLRYI4APAAqNWTytJPhkWC29mOxtPKDiAtcvPwWVt6IAIRSUauOzm7c7p5QiMBwNgCC+kwEycGkxfYANlA4cZBN5gAIzQgjC6xZy3Uj3QivAz+ABu8l+IFQtGBBlCEXOMTyTFsAA9aGAQLgAEY4PLybDYeQAT382JCi3xa3iCTY4jqqPR1UIiFZoIkpn4ENGl0QAHoZYhfnA4EoPsqmYgoHBELhUN1uB44Q8nstEe8AEyfEEEH4wf6AkVgsgIkEsHhysyIAB6AH5YV5Hi8rQBmS2+G127BOgimsCu7jusw+v33AMmq0AFlD73DAMjkqhQK+YI6bvlie9QA)

some other interesting observation:
![image](https://user-images.githubusercontent.com/5227509/208826358-8e0acc3e-e646-4ef8-9869-47f1a9e2448e.png)

[playground](https://www.typescriptlang.org/play?ts=4.9.4#code/GYVwdgxgLglg9mABDAzgEQKbBmDATAHgBUA+ACgEMAuRIxAH0XDyx3wEoaLkVbEBvALAAoRGMQAnDFBASk3AIQBeJUzAtsuPCIC+IkRAQooiAA40yUCSAwM1GtnnYBtALqJVbg0ZPdVpgDpsABsoDAkCKxtyVExNDkQAekTEKNsAN140u2ZWLRFk8UQAPQB+fWFDMGNEAA8LAEYAJgBmHPU8jjcPRC9Kn0QAIx7aoJhQ8IJmlpj0TqcklOnETMRlxlz47WFC8TKKqpqATwsAIgo8AFscU-aHLRd3T1dvapMIHqOxiYjzq5vZnFHOxFogLtckKs-hDbhsOlsCik9uVhK8agAvCxgECXQbhO7zR49Pq7MT7fpvRB4Hro75hCLTQGE0HLVbY3H4uH3fCIorkg4DKAWYwSHAAcwJWyJzzRJlsqigdMm0IBZFizMKKrAt1WIvFkscvORFVlTAsgzgcGCGAoSC5hO6MopNWAPRASoiaSZUtB2VWFqtNrt9nmRrJKN5gwoKBgEAowWCR0Q4QkcAkYJMwRg9PjK14AHcYCxUkdTBgADSpAAWtjgICgpnrJbLPEQxnGwUQhgkUmgQA)

**Comment by ahejlsberg** [comment]
The issue here is unintended widening (from `"admin"` to `string`) because we fail to detect when a type parameter in a type predicate occurs at top level in the predicate return type. I will put up a PR to fix.
