### ISSUE TITLE
Under module resolution NodeNext declaration file lookup does not use "types" property of package.json

### ISSUE THREAD

**Issue by ottokruse** [microsoft/TypeScript#51996]
# Bug Report

Under module resolution `NodeNext` declaration files (*.d.ts) need to be right next to the corresponding js files. It does not work to have them elsewhere but point to the right location with the "types" property of package.json.

For example, [aws-jwt-verify](https://www.npmjs.com/package/aws-jwt-verify) has the following installed directory structure, with both CJS and ESM files ([using `exports` to select the right file at runtime](https://github.com/awslabs/aws-jwt-verify/blob/ead6864b5f7844937516c8b33c7341376fcd0474/package.json#L31)), but 1 set of typings at the root:

```
.
└── node_modules/
    └── aws-jwt-verify/
        ├── dist/
        │   ├── esm/
        │   │   ├── index.js
        │   │   ├── package.json // type: "module"
        │   │   └── ...
        │   └── cjs/
        │       ├── index.js
        │       ├── package.json // type: "commonjs"
        │       └── ...
        ├── package.json // type: "commonjs", types: "index.d.ts", exports: { ... }
        ├── index.d.ts
        └── ...
```

importing `aws-jwt-verify` fails with:

```
index.ts:1:32 - error TS7016: Could not find a declaration file for module 'aws-jwt-verify'. '/private/tmp/nodenext-resolution-issue/node_modules/aws-jwt-verify/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/aws-jwt-verify` if it exists or add a new declaration (.d.ts) file containing `declare module 'aws-jwt-verify';`
```

<img width="837" alt="image" src="https://user-images.githubusercontent.com/6275520/209318612-16d384ed-9dd8-474b-b9d6-041bd37bae21.png">

Setting module resolution to "node" fixes this.

(Our library does work under NodeJS and ESM, so it works with NodeJS module resolution. I.e. this a typings issue only.)

### 🔎 Search Terms

moduleresolution nodenext

### 🕗 Version & Regression Information

moduleResolution NodeNext was introduced in TypeScript 4.7

### ⏯ Playground Link

I can't reproduce this in the playground (a different error is thrown), but this would be it:

```ts repro
// @moduleResolution NodeNext

import { JwtRsaVerifier } from "aws-jwt-verify";

console.log(JwtRsaVerifier);

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEFsHsBMFcA2BTASsgztR8AuBLaAO1ADk5lTkAPXAKDv0gAdoAnXUAb1ACkB3XKgwBDAGrI2+AGb5JoAL6hpbaJFAAiEfwwBaAFaDdAN0kyAnhoDcDAMbEsKAHSJoAcwAUAoaIlTZkgCUNkA)

### 💻 Code

Repo with code that reproduces the issue:

https://github.com/ottokruse/nodenext-resolution-issue

### 🙁 Actual behavior

Module declaration can't be found.

### 🙂 Expected behavior

Module declaration can be found.

**Comment by weswigham** [comment]
`exports` has priority over `types`. If a package has types and an `exports` map, it should have `types` entries in its export map.  It has to be this way or we can't respect export maps and their ability to block entrypoints from being accessible.

**Comment by ottokruse** [comment]
Makes total sense, thanks for the help.
