### ISSUE TITLE
Using type guards in conditional types

### ISSUE THREAD

**Issue by tintin10q** [microsoft/TypeScript#51999]
# Suggestion

## 🔍 Search Terms

conditional types, type gaurds, conditional type gaurds

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ x] This wouldn't change the runtime behavior of existing JavaScript code
* [ x] This could be implemented without emitting different JS based on the types of the expressions
* [ x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I suggest the ability to use type guards in conditional types. This means allowing type guards here: `T extends ... ? T is A : T is B`

## Use Case

This only tells you if the Promise is settled. 
```ts
const isFulfilled = <T>(input: PromiseSettledResult<T>): input is PromiseFulfilledResult<T> =>
  input.status === "fulfilled";
```

But it would be great if we could know that the promise was not setteled as well 

So this would work: 
```ts
result = Promise.AllSettled(....)
result.map((result) => (isFulfilled(result) ? result.value : result.reason));
```

## 📃 Motivating Example

Currently, you can't use the `is` keyword in the result of a conditional type. 

The use case the promted me to make this suggestion was PromiseSettledResult result.

```ts
const isFulfilled = <T extends PromiseSettledResult<unknown> | PromiseRejectedResult>(
  input: T
): T["status"] extends "fulfilled" ? T is PromiseRejectedResult<unknown> : T is PromiseRejectedResult => {
  return input.status === "fulfilled";
};
```

Something like this is possible however, 
```ts
type isFulfilled4<T extends PromiseSettledResult<unknown> | PromiseRejectedResult> =
  T["status"] extends "fulfilled" ? PromiseSettledResult<unknown> : PromiseRejectedResult;
```

Does it make sense to allow the `is` keyword in an conditional type?

**Comment by fatcerberus** [comment]
I don’t think this can work for the stated use case, because you have to do a runtime check on `result.status`.  The conditional type would be resolved at compile time, when you call the function, *before* `status` is known.

**Comment by yume-chan** [comment]
> So this would work:

This already works: [Playground](https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBAlhAYgVwDYDM6tQUwCYwC8MAPACow4AeUOYeEMyYA1mCAO5gB8AFHGAAOyKAC4YABQBOIALYIcAZRxQouPACUcENFHLcAlOIHDYCSTPkQcKDFnVadqPWW5FuAWABQMX-CEiAHTQAIZQyIyEUTAAROhomNj4MQDc3t6gkLBS2rpEMCEcIXCw0nIKgSHYyqrqvADaZVY4gTkQIKgAbji8ACwATAYANBbl1q04AFY4wFC8YDgcMACiUjJSvADkOGsgUpsGBgC6Bt5tuoGyIYK8vOfOBu4wvN5+8EgJ9vh3uQ+vb34APwwe5QQKdKrIHDeAD0MIBfgAeoD-gjxKCJiF2mBTl44QjfMjvAY0l5qII9rAAN4wAC+KSAA)

![image](https://user-images.githubusercontent.com/1330321/209377677-c967459b-b026-4455-81e5-91ada6498c08.png)

**Comment by fatcerberus** [comment]
Right, because that narrowing is associated with a variable which is checked inline.  It doesn’t make sense to express that logic as a conditional return type though because `T["status"]` isn’t narrowed as a result of the `input.status === "fulfilled"` check.

**Comment by RyanCavanaugh** [comment]
The alternate form is the thing you have to write. It doesn't make sense to allow the UDTG syntax to mix into the conditional type syntax, since thing you're `is`-ing is a function parameter in one case vs a type parameter in the other case.
