### ISSUE TITLE
Using decorators on class reports class is declared but never used

### ISSUE THREAD

**Issue by weareoutman** [microsoft/TypeScript#51992]
# Bug Report

### 🔎 Search Terms

"decorator unused"
"decorator declared but never used"

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because my project relies on auto-accessor which is only available since ts 4.9

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUnusedLocals=true&moduleResolution=99&target=99&module=100&ts=5.0.0-dev.20221221#code/GYVwdgxgLglg9mABAEwKbBmVBRANqgW1TCgAowBDIgLkQGcoAnTAcwEpaKwBPRAbwBQAXwECAAmgxY8hYmQBEBbgFpU+IiXlsBEXBTp1EAIUSoAHlGLJDACQAqAWQAyMjVH6iRQA)

### 💻 Code

```ts
function defineElement(name: string): any {
}

@defineElement("my-element")
class MyElement extends HTMLElement {

}
```

### 🙁 Actual behavior

TypeScript reports `'MyElement' is declared but never used.`.

And If I click "Quick Fix" in vscode, it removes my entire class declaration and decorator call.

### 🙂 Expected behavior

No error reports.

**Comment by MartinJohns** [comment]
I think it would be much better to either ignore the error, export the class or use it in an empty dummy function than to make this not an error. I believe in the majority of cases this legitimately considered unused.

**Comment by weareoutman** [comment]
But I would say "The class name 'MyElement' is unused, while the class itself is used", rather than "The whole class is not used, and can be safely removed".

I think the class decorator is supposed to *use the class* by its design.

**Comment by weareoutman** [comment]
Let me show 3 examples:

```ts
// 1)
function dec(clazz: unknown) {
  // May use clazz or not, not sure.
}
dec(class Bar {});
```

```ts
// 2)
function dec(clazz: unknown) {
  // May use clazz or not, not sure.
}
const Foo = dec(class Bar {});
```

```ts
// 3)
function dec(clazz: unknown) {
  // May use clazz or not, not sure.
}
const Bar = dec(class Bar {});
```

- 1\) `Bar` is used
- 2\) `Bar` is used, while `Foo` is not
- 3\) The latter `Bar` is used, the former is not

The problem here for decorators is that there is only one `Bar` in source code, I would think it is used when at least one of the two in de-sugared code is used.

```ts
function dec(clazz: unknown) {
  // May use clazz or not, not sure.
}
@dec
class Bar {}
```

**Comment by fatcerberus** [comment]
It's admittedly kind of a gray area, the class is only "used" in the same sense that `let x = 0; x++;` "uses" `x`.  Having decorators with non-local (to the class) side effects feels like an anti-pattern.

**Comment by andrewbranch** [comment]
It’s impossible to know whether a decorator constitutes meaningful usage, but I would argue that this pattern defeats the purpose of decorators and is the exception, not the rule. The whole point of a decorator is that you can observe or modify a declaration before it is accessed by other parts of the code. If `defineElement` simply consumes `MyElement`, and nobody else does, `defineElement` should probably just be a function call that accepts `MyElement`. I would be confused if I saw this code in the wild. Regardless, I think we would do more harm than good by counting decoration as a usage.

**Comment by weareoutman** [comment]
So you mean they should probably remove the `addInitializer` API of decorators proposal? 😕

The proposal says:

> Decorators have three primary capabilities:
> 1. ...
> 2. ...
> 3. They can initialize the value that is being decorated, running additional code after the value has been fully defined.

**Comment by MartinJohns** [comment]
> Edit: It also mentions that: "Decorators should affect the thing they're decorating, and avoid confusing/non-local effects", but I'm confused about what are _confusing/non-local effects_, since it also gives an example of `@defineElement`.

The "confusing/non-local" effects are also commonly called side-effects. If the class is not used anywhere, the "defineElement" decorator is pointless if it doesn't have any side-effect, for example storing the class in an array at module scope.

**Comment by jonlepage** [comment]
If the goal is to have some special files containing classes registered in a store through decorators, one solution is to implement this in top of each of these files.
`/* eslint-disable @typescript-eslint/no-unused-vars */`

and import those files in a index.ts for triggering.
