### ISSUE TITLE
Index signature for type 'string' is missing in type with Record<string, unknown>

### ISSUE THREAD

**Issue by dangreen** [microsoft/TypeScript#51994]
# Bug Report

```tsx
interface T {
    foo?: boolean
    bar?: boolean
}

const t: T = {}
const ok: Record<string, any> = t
const error: Record<string, unknown> = t
/* Type 'T' is not assignable to type 'Record<string, unknown>'.
  Index signature for type 'string' is missing in type 'T'.(2322) */
```

[Playground Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCrIN4Chm+TAewIH4AuZAIyIBsI4Qc8K4ozKa6GBfLLBAkAGcwyMOXQBeTD35CRBANbkAShH5QAJgB5hUUAHMANMnoBPAHzIpYPgOHJoUAlBVrn23QeMBXEApAEAO4gltZYQA)

With `Record<string, any>` works correctly, with `Record<string, unknown>` does not. 

### 🔎 Search Terms

> typescript record unknown Index signature for type 'string' is missing

### 🕗 Version & Regression Information

v3.3.3 - ok
\>=v3.5.1 - not ok

### 🙁 Actual behavior

Throws error

### 🙂 Expected behavior

Handle as valid types

**Comment by IllusionMH** [comment]
Looks like duplicate of #50087 and some other.

**Comment by dangreen** [comment]
@IllusionMH Thanks

https://github.com/microsoft/TypeScript/issues/50087#issuecomment-1199411533

Looks like the answer
