### ISSUE TITLE
node:readline Property 'history' does not exist on type 'Interface'

### ISSUE THREAD

**Issue by antonilol** [microsoft/TypeScript#52008]
# lib Update Request

@types/node/readline.d.ts

## Configuration Check

tsconfig:

```json
{
  "compilerOptions": {
    "target": "es2021",
    "moduleResolution": "node",
    "module": "commonjs",
    "esModuleInterop": true
  }
}
```

## Missing / Incorrect Definition

`history` (type string[]) is missing from `class Interface` of `module 'readline'` in @types/node/readline.d.ts

## Sample Code

```ts
import { createInterface } from 'readline';

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log(rl.history); // []
```

this gives a ts compile error, but runs fine

## Documentation Link

just nowhere to be found (does this mean this is an internal feature that should not be used, or did nodejs forgot to document it?)
not on nodejs.org/api and not on nodejs.org/dist/v16.18.0/docs/api (the exact version i use)

**Comment by RyanCavanaugh** [comment]
> just nowhere to be found (does this mean this is an internal feature that should not be used, or did nodejs forgot to document it?)

How would I know? 😅. If they chose not to document it, it almost certainly shouldn't be in the declaration file.

**Comment by fatcerberus** [comment]
It looks like the officially sanctioned way to access the history array is through the `history` event: https://nodejs.org/api/readline.html#event-history
