### ISSUE TITLE
compile ts to msil

### ISSUE THREAD

**Issue by furesoft** [Microsoft/TypeScript#5200]
can you make a ts to msil compiler to support .net?

**Comment by mhegazy** [comment]
Sounds like an interesting idea for some one to experiment with using the compiler API. But it is outside the scope of this project.

**Comment by DanielRosenwasser** [comment]
I'd suggest looking into [Edge.js](http://tjanczuk.github.io/edge) or perhaps interfacing with [JsRT](https://msdn.microsoft.com/en-us/library/dn249673(v=vs.94).aspx).
