### ISSUE TITLE
Iterating through a Record (especially a partial one) with `for...in` is an awful developer experience

### ISSUE THREAD

**Issue by exoRift** [microsoft/TypeScript#52001]
# Bug Report

### 🔎 Search Terms

`for in`
`for in record`

### 🕗 Version & Regression Information

- This occurs in version 4.9.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/JYOwLgpgTgZghgYwgAgPYCMBWyDeAoZQ5ABylWIC5kBnMKUAczwF888wBPYlAVxGFQhkAXmQByQRDEAfMWADuqMWwSDayKBAQUACnChhgcADYAeAEpbUUACam+AkABo0WAHxuRuAkUlV8RIEkZJTiABYQxsZKPoSsrHgw1sgAFKog6hDgUBzIoBpaAJTegenUqMYQAHTRDCmaCADaWXQcALpVpOSFLHhAA)

### 💻 Code

```ts
interface obj {
    prop: string
}

type union = 'one'|'two'

const rec:Partial<Record<union, obj>> = {
    one: {
        prop: 'hello'
    }
}

for (const entry in rec) {
    console.log(rec[entry].prop)
}
```

### 🙁 Actual behavior

- The compiler will complain that `string` cannot be used to index the record as `for...in` resolves the iterator to a string.
- Therefore, you have to declare a new variable
```ts
const actualEntry = entry as union
```
- The compiler will then complain that `rec[actualEntry]` is possibly undefined due to it being a partial record, regardless of the fact that it's iteration.
- So, ultimately, you have to declare another variable with a default even though you know it exists
```ts
const value = rec[actualEntry] || {} // note: this only works on interfaces where all properties are optional (which the one above is not)
```

### 🙂 Expected behavior

It'd be nice if the compiler were a tad bit smarter in this department, recognizing the iteration and existence checking.

#### Sidenote: Logical assertions don't affect type errors even though they should.
```ts
lib/structures/effect/command.ts:80:42 - error TS2532: Object is possibly 'undefined'.

80       if (locale in locales) console.log(locales[locale].description)
                                            ~~~~~~~~~~~~~~~
 ```

**Comment by fatcerberus** [comment]
You can write `obj[prop]!` (non-null assertion) to tell the compiler—and others reading the code—that you know it can’t be undefined in this case, instead of writing a useless default case.  That’s what the `!` operator is for.

**Comment by fatcerberus** [comment]
For the record you don’t need to declare any extra variables:

```ts
console.log(rec[entry as union]!.prop)
```
