### ISSUE TITLE
SVGElement is not inferred as Element

### ISSUE THREAD

**Issue by DaviDevMod** [microsoft/TypeScript#52009]
# Bug Report

`SVGElement` is not inferred as `Element`.

One could always ignore the harmless inferred signature `Element | SVGElement` or specify an `Element` signature.

### 🔎 Search Terms

svg element

### 🕗 Version & Regression Information

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/PTAEBUAsFNQJ2gFwK5wHakQTwA6wJYDOo+aAZtHAgCagCGxABgKIA20AttGoqAD6gAygDUA4m07deAtMlatGAKBAQYoAMYB7Djnzs4JcpSYAJcAFkAMhK49G9JjamMANMrAAjZL3y9qm6EI0AHJePDgyTTgOTDVCOi5DCgQ0dVhNDEYRcXZbREYAOkUtNEJeMlAAXlAACmhWAC5QZDQAazRNAHc0AEoqgD5QAG9FUBIKmoBCOtZDMrpU6E0KsysnHj6AMk3Qafq5xAW05aExdcQevpGxsZUAJSRUNFIAc1AWXKl+UFl5JRv4I90KB-OpkHkCnR1Ih8AA3aDnADco1AAF9FCj7kDnmg3oxVtZPjxvtlzv9AShgfVkajEUA)

### 💻 Code

```ts
// The return type is inferred as `Element | SVGElement | null`
// The compiler infers `HTMLElement` as `Element`,
// but it doesn't perform the same inference on `SVGElement`.
const f = (el: unknown) => {
  if (!(el instanceof HTMLElement) && !(el instanceof SVGElement)) {
    // Returning `Element | null`
    return document.activeElement;
  }

  // Returning `HTMLElement | SVGElement`
  return el;
};
```

### 🙁 Actual behavior

`SVGElement` is not inferred as `Element`.

### 🙂 Expected behavior

`SVGElement` should be inferred as `Element`.

**Comment by RyanCavanaugh** [comment]
I don't understand what you're trying to say here.

**Comment by DaviDevMod** [comment]
@RyanCavanaugh sorry, I see a few ways the example above can be hard to digest, hopefully this comment is going to be more clear.  

if a function returns an `Element | HTMLElement`, the return type is inferred as `Element` and that's fine.

If a function, instead, returns an `Element | SVGElement`, the return type is inferred as `Element | SVGElement` (even though an `SVGElement` is in fact an `Element`), which is not wrong but it's not consistent with how the compiler handles other similar cases.

For instance, [here](https://www.typescriptlang.org/play?ts=4.9.4#code/MYewdgzgLgBAZjAvDAFGAXDArmA1mEAdzAEokA+GAbwCgYYB6BmAJwFMosWwYBDGAAZgsAWwBGbFgLowAlnDQwAhImQAWGADJNMHiuQBWMu07cYAOVESWaEgG4ZMpqw5ceAjQB8YB6fRNuug4AvjQ0zgAqABZscmBwkuwAJi6mPFAAngAOsSAIAnACchCCwuKSAgA04cwsvFAxLDANvO5l1jDeXj4CAHRAA) is an example with numbers:

```ts
const f = (n: unknown) => {
  // return a `number`
  if(n !== 4 && n !== 5) return Number(n);
  
  // return `4 | 5`
  return n;
}

// The inferred return type of `f` is `number`,
// rather than `number | 4 | 5`.
```

**Comment by DaviDevMod** [comment]
> it's not a subtype due to its `className` property.

So how it comes that `Element | HTMLElement` is reduced to `Element`?

`HTMLElement` has a `className` property too, right?

**Comment by RyanCavanaugh** [comment]
`SVGElement`'s` `className` is `any`,

**Comment by DaviDevMod** [comment]
Oh I see, the `className` of an `SVGElement` is an [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString) object.
Please, forgive my ignorance.
