### ISSUE TITLE
High-order functions don't respect generic input type

### ISSUE THREAD

**Issue by leobastiani** [microsoft/TypeScript#52010]
# Bug Report

### 🔎 Search Terms

generic type inference, higher-order functions

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about generic type inference and higher-order functions.

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAsiAKAnA9mAzlAvFA3lAhgFxQB2ArgLYBGEiUAvgNwCwAUG6JFAIIAmvAOUo1EACWQAzLFAA8SVBggAPYBBK8MOegD4AFGBTpi89AEos2qCYwAyXFCrFy1WgxbtWnaNzBgANiAAKsjiEjJsUFChUMqq6hj6hmjE+CQg5piWqSAANBFWSWyW2NGxahpQiQrGSRmWAJYkEq4ASlAA-FBtThAAbrTuHODQcNYA6vXAABYAQtI+-kEhkjJ8gsK0oTmwCEnag6wAxsgkaMAxSvgU-hDEo0kT03PYOPlEUACMeayRjlAATGwmEA)

### 💻 Code

```ts repro
type MyProps = { a: number };

type AddNumberHof = <Props extends {}>(props: Props) => Props & { b: number };

type ApplyToHof<
  Hof extends (props: any) => any,
  Props
> = Hof extends (props: Props) => infer R ? R : never;

type MyPropsWithB = ApplyToHof<AddNumberHof, MyProps>;

const example: MyPropsWithB = {
  a: 1,
  b: 2
};
```

### 🙁 Actual behavior

Error at last line `Type '{ a: number; b: number; }' is not assignable to type '{ b: number; }'. Object literal may only specify known properties, and 'a' does not exist in type '{ b: number; }'.`

### 🙂 Expected behavior

Build successfully

**Comment by leobastiani** [comment]
This code below should give an error

```ts repro
type MyProps = { a: number };

type IdentityHof = <Props extends {}>(props: Props) => Props;

type ApplyToHof<
  Hof extends (props: Props) => any,
  Props extends {}
> = Hof extends (props: Props) => infer R ? R : never;

type SameAsMyProps = ApplyToHof<IdentityHof, MyProps>;

const example: SameAsMyProps = {
  c: 1
};
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAsiAKAnA9mAzlAvFA3lAhgFxQB2ArgLYBGEiUAvgNwCwAUG6JFAJIAmEJYAEtQACWQAzLFAA8SVBggAPYAN4Yc9AHwAKMCnTF56AJRYtUY2hbtWnaAEEwYADYgAKsnESZbKFG8oZVUSdSg9AzRifBIQM0wLGJAAGj9LSLYLbEDgtQwIhSNI+IshEglaKAAlKAB+aqhiEggAN1obDnBoAGV8CggHNDgraSdXDy9JGT4BYTFJZNgESK0O1gBjZBI0YCClPtcIYl7+weHI6Rw09eIARjYmIA)

**Comment by RyanCavanaugh** [comment]
Structural inference, which is what's happening here, doesn't perform generic instantiation like would be needed to resolve this. The performance implications of doing that would be, as far as I can imagine, catastrophic.

**Comment by leobastiani** [comment]
Ideally, I'd like to be able to transform `type IdentityHof = <Props extends {}>(props: Props) => Props;` to `type IdentityHofTwo<Props extends {}> = (props: Props) => Props;`. Is it possible?
