### ISSUE TITLE
A record value should be narrowed down to array when using Array.isArray

### ISSUE THREAD

**Issue by ficristo** [microsoft/TypeScript#52014]
# Bug Report

### 🕗 Version & Regression Information

TypeScript 4.9.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUMAmAuRBnKAJxjAHMBKRAbwFgAoRRCBAxQgU2cJ0QCVO43ADwFiZADSIwIALYAjdoUQAfRAEFChAIYBPIdPmKAfEcQBeagF8A3PXqNmYVls3m2A7gG0sAXVt17RBhgRDQNbR0AOhg8cN00F0JySloGRkQAegzEAHdBAGtAxkTIgAcQPAALNABGcn9GS0DA4NC4qJj2tA4uTG9MH2TqIszszDh2PDAAcihcgpGewT7fMorquobEJrodoA)

### 💻 Code

```ts
function foo(id: string) {
  const record: Record<string, number | Array<number>> = {};

  const arr = record[id];

  if (Array.isArray(arr)) {
    // work
    arr.push(1);
  }
  
  if (Array.isArray(record[id])) {
    // doesn't work
    record[id].push(1);
  }
}
```

### 🙁 Actual behavior

If the record value is used directly is not narrowed down to an array.

### 🙂 Expected behavior

The record value type should be narrowed.

**Comment by MartinJohns** [comment]
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by ficristo** [comment]
In fact using record.id does work, I didn't notice it before. Closing since it is a duplicate.
Thanks.
