### ISSUE TITLE
TSConfig throws an error when deleting files

### ISSUE THREAD

**Issue by EmiliaShiori** [microsoft/TypeScript#52012]
# Bug Report

### 🔎 Search Terms

tsconfig
tsconfig file delete error
matched by include pattern

### 🕗 Version & Regression Information

TSConfig throws an error when deleting a file inside of WSL debug mode when deleting a file matched by TSConfig

### 💻 Code

TSConfig.json
```ts
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext", "DOM"],
    "module": "CommonJS",
    "rootDir": "./src",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "outDir": "./dist",
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["./src/**/*.ts"]
}
```

### 🙁 Actual behavior

VSCode throws an error from TSConfig.json when deleting a file in WSL mode. This doesn't happen while outside on WSL mode

### 🙂 Expected behavior

VSCode and TSConfig to not throw an error

**Comment by RyanCavanaugh** [comment]
"throws" what error? In which interface? Is this commandline watch? Something in the editor? Which file did you delete?
