### ISSUE TITLE
`abstract` modifier keyword does not highlight(colorization) when using with protected/public keyword

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5202]
On Visual Studio and Playground.

```ts
abstract class Foo {
	protected abstract bar_()
	abstract bar()
}
```

Fixed by https://github.com/Microsoft/TypeScript/pull/3846 ?

**Comment by DanielRosenwasser** [comment]
You mean colorization, not occurrence highlighting. @mhegazy does Monaco use the lexical classifier?

**Comment by mhegazy** [comment]
No it uses a different classifier.

**Comment by DanielRosenwasser** [comment]
If they use the TextMate grammar, then https://github.com/Microsoft/TypeScript-Sublime-Plugin/pull/349 should have fixed this.

**Comment by mhegazy** [comment]
this should be working correctly now.
