### ISSUE TITLE
Import the latest changes from `typescript-DOM-lib-generator` repo to make the latest APIs available

### ISSUE THREAD

**Issue by ssym0614** [microsoft/TypeScript#52025]
# lib Update Request

I just want the latest changes from `TypeScript-DOM-lib-generator` repository to be applied to this repo so that I can use the latest APIs available.
In particular, I want `PublicKeyCredential.isConditionalMediationAvailable`, which is already available in the `TypeScript-DOM-lib-generator`'s baseline file: https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/0337998b669df62d10f3acb96cc2f7c2382bbfda/baselines/dom.generated.d.ts#L11245

I tried updating it myself using the scripts in `TypeScript-DOM-lib-generator`, but I had no luck: https://github.com/microsoft/TypeScript/pull/52024
I couldn't find the specific documentation on how to "import" the latest generated file to this repository. 

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Documentation Link

It's already available in the MDN docs too, and has support by more than 2 browsers https://developer.mozilla.org/docs/Web/API/PublicKeyCredential
(This shouldn't matter anyway, because the change is already in the `baselines/` folder of `DOM-lib-generator` repo.

**Comment by sandersn** [comment]
Typescript 5.0 beta now has `isConditionalMediationAvailable`.

I think your PR was rejected by the bot because it updated too many files. The only 3 I update are dom.generated.d.ts, dom.iterable.generated.d.ts and webworker.generated.d.ts. I need to take a second look as to why we don't update the others.
