### ISSUE TITLE
ts(2349) when trying to find an element of union arrays

### ISSUE THREAD

**Issue by SancheZz** [microsoft/TypeScript#52028]
# Bug Report

### 🔎 Array.find

lib.es2015.core.d.ts has added the new `find` method signature:
`find<S extends T>(predicate: (this: void, value: T, index: number, obj: T[]) => value is S, thisArg?: any): S | undefined;`
which breaks below code:
```
declare const array: string[] | number[]
array.find(Boolean);
```

### 🕗 Version & Regression Information
Typescript 4.8.4 & 4.9.4 & nighty

### 🙁 Actual behavior

```
This expression is not callable.
  Each member of the union type '{ <S extends string>(predicate: (value: string, index: number, obj: string[]) => value is S, thisArg?: any): S | undefined; (predicate: (value: string, index: number, obj: string[]) => unknown, thisArg?: any): string | undefined; } | { ...; }' has signatures, but none of those signatures are compatible with each other.(2349)
```

### 🙂 Expected behavior

No errors. The `find` method works and infers element type as `string | number`

**Comment by jfet97** [comment]
AFAIK is a well-known design limitation of the language. For union types, members which are functions will also be typed as union types, so the type of the `find` function in your example is the following union:

```ts
{
    <S extends string>(predicate: (this: void, value: string, index: number, obj: string[]) => value is S, thisArg?: any): S | undefined;
    (predicate: (value: string, index: number, obj: string[]) => unknown, thisArg?: any): string | undefined;
} | {
    <S extends number>(predicate: (this: void, value: number, index: number, obj: number[]) => value is S, thisArg?: any): S | undefined;
    (predicate: (value: number, index: number, obj: number[]) => unknown, thisArg?: any): number | undefined;
}
```

What I understand is that you cannot call something like that. Should the `predicate` callback accept a `number` or a `string`? You don't know.

A solution is to use the `(string | number)[]` type for `array`, maybe as a cast before calling the `find` method.

**Comment by fatcerberus** [comment]
Indeed, the problem becomes more obvious if instead of `find` you’re calling, e.g., `push` — which type are you allowed to push?  You don’t know, and you can’t mix and match.  So it’s not safe in general to pretend the element type is `string | number`.

**Comment by SancheZz** [comment]
The `push` method modifies an existing array, but the `find` method does not. I agree that I can't use the `push` method before narrowing type, but inside the `find` method, I can use type guard to properly use the element's type.

**Comment by fatcerberus** [comment]
Right, but my point is there’s no difference to the type system between a method that modifies the array and one that doesn’t - structural typing only cares about the method signature, not what it does once you call it.  It’s a fundamental design limitation.

**Comment by SancheZz** [comment]
@fatcerberus you can remove above `find`'s signature and example code will work. This limitation is used by `lib.d.ts`, not structural typing.
