### ISSUE TITLE
Project with references but no input files fails to report dependency problems

### ISSUE THREAD

**Issue by hpello** [microsoft/TypeScript#52030]
# Bug Report

### 🔎 Search Terms

project references
no / empty input / files
silently succeeds

### 🕗 Version & Regression Information

Tested on versions:
- 4.9.4
- next (5.0.0-dev.20221226)

Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "project references"

### ⏯ Playground Link

Link to reproducible issue: https://github.com/hpello/test-references-no-input
Not providing a playground link, as this is more of a tsconfig issue.

💡 **Reproduction explanation**:

1. Repro: **composite: false**
    - Project `b` has `composite: false`
    - Project `a/tsconfig.b.json` references project `b`
    - Project `a/tsconfig.b.no-input.json` references project `b` (**but has no input files**)

2. Repro: **circular dependency**
    - Project `c` has a dependency to project `a/tsconfig.c.json` (creating a circular dependency)
    - Project `a/tsconfig.c.json` references project `c`
    - Project `a/tsconfig.c.no-input.json` references project `c` (**but has no input files**)

### 💻 Code

```shell
npx tsc --build packages/a/tsconfig.b.json
npx tsc --build packages/a/tsconfig.b.no-input.json

npx tsc --build packages/a/tsconfig.c.json
npx tsc --build packages/a/tsconfig.c.no-input.json
```

### 🙁 Actual behavior

```shell
npx tsc --build packages/a/tsconfig.b.json # => ✅  error: TS6306: Referenced project '/Users/hippolyte.pello/lib/test-references-no-input/packages/b/tsconfig.json' must have setting "composite": true.
npx tsc --build packages/a/tsconfig.b.no-input.json # => no error ❌

npx tsc --build packages/a/tsconfig.c.json # => ✅ error TS6202: Project references may not form a circular graph. Cycle detected: ...
npx tsc --build packages/a/tsconfig.c.no-input.json # => no error ❌
```

### 🙂 Expected behavior

1. According to the [docs](https://www.typescriptlang.org/docs/handbook/project-references.html), "Referenced projects must have the new [composite](https://www.typescriptlang.org/tsconfig#composite) setting enabled". There is no mention of a specific treatment when no input files are specified `include == files == []`
2. In the same way, an error should be reported in case of circular dependencies, even with no input files are specified

```shell
npx tsc --build packages/a/tsconfig.b.json # => ✅  error: TS6306: Referenced project '/Users/hippolyte.pello/lib/test-references-no-input/packages/b/tsconfig.json' must have setting "composite": true.
npx tsc --build packages/a/tsconfig.b.no-input.json # => ✅  error: TS6306: Referenced project '/Users/hippolyte.pello/lib/test-references-no-input/packages/b/tsconfig.json' must have setting "composite": true.

npx tsc --build packages/a/tsconfig.c.json # => ✅  error TS6202: Project references may not form a circular graph. Cycle detected: ...
npx tsc --build packages/a/tsconfig.c.no-input.json # => ✅  error TS6202: Project references may not form a circular graph. Cycle detected: ...
```

### 🪄 Context, and what's more

I was confronted to this unexpected behaviour in an attempt to migrate a repo from classic TS to project references; and it took me some time to figure out why there was a special treatment made in the "no input" case.

For what it's worth, I saw this pattern in a generated [tsconfig.json](https://github.com/nrwl/nx/blob/d3ef0eaf7214a09709882240b736a5a50c970864/packages/create-nx-workspace/tsconfig.json) in the case of setting up a TS monorepo with nx:
```shell
npx create-nx-workspace@latest myorg --preset=ts
```

It seems odd and non-intuitive to me that `include == files == []` would trigger an "ignore" on dependency check. So I am wondering if this is a bug, or a hidden feature. 😉

Best regards!

**Comment by RyanCavanaugh** [comment]
Config files with explicitly zero input files are considered "solution files", IOW projects which only exist to build some set of other projects. The vast majority of invariant checks are skipped on them since they, by definition, don't "do" anything.

**Comment by DanKaplanSES** [comment]
I believe this is a duplicate of https://github.com/microsoft/TypeScript/issues/40766

**Comment by DanKaplanSES** [comment]
I believe this is a duplicate of https://github.com/microsoft/TypeScript/issues/40766#issuecomment-699073548 This link goes to @sheetalkamat 's comment:

> Solution is the project that has no own files so it doesnt need to be built. So it doesnt care if referenced project is composite or not. Non solution projects will use .d.ts output from the referenced project and knowing all input output files is also key to check upto dateness of your own project. hence composite requirement for those referenced projects

For my own understanding, is a "solution file" 1) a tsconfig.json with explicitly 0 input files or 2) a tsconfig.json with explicitly 0 files **and a `"references"` property**?

I ask because explicitly 0 input files errors unless you add a `"references"` property. e.g., `No inputs were found in config file './tsconfig.json'. Specified 'include' paths were '[]' and 'exclude' paths were '["."]'.` 

Setting the value to `[]` or `null` seems to fix the error. (Of course, `--build`ing a solution file with those values emits no files.)

---

re: solution files, @RyanCavanaugh said:

> Config files with explicitly zero input files are considered "solution files", IOW projects which only exist to build some set of other projects. The vast majority of invariant checks are skipped on them since they, by definition, don't "do" anything.

Am I correct in saying a solution file's purpose is to delegate to other tsconfigs? I'm not following how that relates to its invariant checks. 

Maybe the answer to a different question would help me: what benefits are there to skipping invariant checks in solution files?

Thanks!
