### ISSUE TITLE
Higher Order Instantiation Expressions don't resolve types correctly

### ISSUE THREAD

**Issue by Thundercraft5** [microsoft/TypeScript#52035]
# Bug Report

### 🔎 Search Terms
- higher order instantiation expression 
- instantiation expressions
- instantiation expression loses generic 
- nested instantiation expression doesn't resolve 
- nested instantiation expression
### 🕗 Version & Regression Information
TS 4.7+ (in every version I tried, it seems to be there from start this feature was added).
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.0.0-dev.20221220#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxilQGdEcYBbAHgCh4H4w8SN4BBeEADwxFWAl4cKMDwQAnvGISA2gF0ANPHqMAYl179B8Oo33wAapr4Ch7WamSUARiBhKVBxgGkT2oQGsQEnIg6KqgwAfAAUAG5QEMggAFxGylgCPPEuyrBEEvHsAJTwALzB0qgStGEZUFnwsgB0deyOKOjxajnxAN7Vbknw3r7+DfEASiAYyDCoACoSAA4g1BizIH5IaGDUFi6OLsFFAL4A3LS0zKRsACQATAUERKTkVKGyAEQ4NgBW4BjPys+sMEkAOY-eDPKy2ezPRyeApFUKdRZzeIwvY5HJHfQAekx8AAegB+ILwbHwADKAAscMgIMB4HZqgilvFXh8vs94HtlIykaD-kD2Zz4Ny4qDwXYYAL5EA)

### 💻 Code
```ts
declare function transform<
    const A extends readonly any[], 
    F extends <
        V extends A[number], 
        K extends keyof A,
    >(value: V, index: K, array: A) => any
>(array: [...A], func: F): { 
    [K in keyof A]: ReturnType<typeof func<A[K], K>> 
};

const $2 = transform(["object", "string", "number"], k => ({ type: k }));
    // ^?
    // Should be [{ type: "object" }, { type: "string" }, { type: "number" }], but is [any, any, any]
```

### 🙁 Actual behavior
- In the return type annotation of `transform()`, the instantiation expression (added by #47607) `typeof func<A[K], K>` reverts to it's generic constraint type of `F` (`<V extends A[number], K extends keyof A>(value: V, index: K, array: A) => any`) when it is invoked. This causes the return type of `transform()` to be a tuple of `any` instead of `{ type: A[K] }`. 
- [Using `ReturnType<F>` in place of a instantiation expression from above example results in unresolved generics leaking from the function type](https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.0.0-dev.20221220#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxilQGdEcYBbAHgCh4H4w8SN4BBeEADwxFWAl4cKMDwQAnvDQBrVDgDuqANoBdADTx6jAGJde-QfDqNT8AGr6+Aoe2WpklAEYgYGrWcYBpK4aEyQCRxEDk1tBgA+AAoANygIZBAALgtNLAEeFK9NWCIJFPYASngAXgjpVDlFVFpo3Kh8+GUAOlb2dxR0FJ1ClIAlEFFxCWoAbyafdPgAoJD2-pAMZBhUABUJAAcQah1ygF8IgG5aWmZSNgASACZSgiJScioo5QAiHCcAK3AMF80X1hg6QA5r94C8HM5XC93DJSuUouMMJtktNNCQtmAsIgsGAUgByCQgEh4+B7eBQIRnViFQrHAD0dNMAD0APxAA)
### 🙂 Expected behavior
- The instantiation expression `typeof func<A[K], K>` in `transform()` should resolve to `{ type: A[K] }`.
- `res` should resolve to `[{ type: "object" }, { type: "string" }, { type: "number" }]`.
- Functions used in higher order instantiation expressions should resolve correctly and not revert to their constraint types.

**Comment by Thundercraft5** [comment]
[Additional Repro Demonstrating this bug](https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.0.0-dev.20221220#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwBIAGAHgDEBGeEADwxFWAGd4AKcgPlYEp4BeDmx79BaANaocAd1TduAGngAVLinQAueJUUA3KBGQhNS7powBPAA4gciJGjABuAFDOL1wkX7wASiAzIMKhKViAk7jZ2xCTsZFy8AmwkStR0DMzwOABGAFbgGPEiyvAAZFpyigDaFAC6HBwuAJAA9M3wAHoA-K6t8ADqABYM8Bgw5lioAOYjOPDITAgTTBhQ2Ku4+LSWcExMG0yOI0MjofCWsFAAtv4gMCxQjEcIcAFBJx6wCGA4l5YQNxBzPAIDhls5QJBPvZ0Ng8IQKOQqLR6IwWLFColWMJEuJJDIKspVA5NNp4HoDEZlKZ3pFoWBkg0em0AMoDHDICDAeBZBAAA2SqRRGWyeUwGMEKTK1RqvLcpwIVD4vn8gWCoXCoVs8JinGxgnYKWR6RYIvy4uKZTIBOl9SavS6zkaQA).

**Comment by DarrenDanielDay** [comment]
It seems `TypeScript` currently has no support for `higher order types`, and it's a design limitation. That means, the following code, or other code with the same functionality (like the example in this issue), will not work as we expected.

```ts
type Mapped<Mapper, T> = Mapper<T>; // Type 'Mapper' is not generic. (2315)
```

It's common to make abstraction like this in `JavaScript`:

```js
function mapped(mapper, value) {
  return mapper(value);
}
function box(value) {
  return { value };
}
console.log(mapped(box, 'foo'));
```

That is, we might want to create higher order function called `mapped` that applies the `mapper` to the given `value`, and both `mapper` and `value` are not statically typed, and the type `Mapped` above is what we might want to.

Another situation is class instantiation with constructors and constructor parameters. Generic function works well with normal constructors, but it cannot infer generic instance type with generic constructors:

```ts
function create<T extends new (...args: any[]) => any>(ctor: T, ...params: ConstructorParameters<T>): InstanceType<T> {
  return new ctor(...params);
}

class Foo {
  constructor(public message: string) {}
  sayHello() {
    console.log(`hello from ${this.message}`);
  }
}

// Well typed, because `Foo` is not a generic type.
const foo = create(Foo, "bar");
foo.sayHello();
// Not well typed, because `Set` is a generic type, and its constructor parameter uses its generic parameter `T`.
const numberSet = create(Set, [1, 2, 3]);
//    ^^^^^^^^^ Inferred as `Set<unknown>` -- the generic parameter is instantiated with its constraint.
```

`TypeScript 4.7` introduced [`instantiation expressions`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#instantiation-expressions), which **seems to make that possible**: instantiate generic parameters of a generic function by instantiation expressions, and then get the return type of the generic function. But unfortunately, it didn't make it.

I know it's not the first time to introduce `higher order types` (or `higher order generics`) in the `TypeScript` community and it takes a lot of effort to implement this feature, but I still wish that `TypeScript` would support it, which would absolutely open a new world for the type system like the `template literal types` feature in `TypeScript 4.1`✨.

**Comment by RyanCavanaugh** [comment]
The thing you mostly need here is call types, not higher-kinded types per se. The very smallest problem is that `k => { type: k }` is not a generic function, and what needs to happen in this call to resolve as desired is to repeatedly perform separate generic inference rounds on calls to that function expression (once you make it generic, of course).

Tracking somewhat at #52295 (this would be a mapped type rather than a union type, but the logic is pretty similar) and to a greater extent at #6606, which I think we will revisit sometime to specifically think about (generic) functions' call types.

**Comment by Thundercraft5** [comment]
I don't think you understood my example; the issue is not strictly mapped or union types. Even though `k => { type: K }` is not generic, it should be "inhabited" by the generic constraint type (hovering over shows it already does sort of). This inhabiting behavior already happens with `satisifies`, as in this example:
```ts
type Func = <T>(value: T) => any;
const satisfiedFunc = (param => {
  return [
    param
  ] as const;
}) satisfies Func;

type $0 = typeof satisfiedFunc<0>; // outputs correctly as `readonly [0]`
```
[Playground Link](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9&ts=5.0.0-dev.20230125#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxilQGdEcYBbAHgCh4H4w8SN4BBeEADwxFWAl4cKMDwQAnvGISA2gF0ANPHqMAYl179B8Oo33wAapr4Ch7WamSUARiBhKVBxgGkT2oQGsQEnIg6KqgwAfAAUAG5QEMggAFxGylgCPPEuyrBEEvHsAJTwALzB8ADeBBIADnFG8AC+8AA+JTW0YRlQWfCyAHQ97I4o6PFqOfGlQZ1uSfDevv598QBKIBjIMKgAKhUg1BhbfkhoYNQWLo4uwUW0NQDctLTMpGwAJAAMBQREpORUobIARDgbAArcAYP7KP6sGBJADm4Pgfystnsf0cngKRVCpV2lXi6JqORyt30AHoSfAAHoAfnGZPgAGEKHBMJJ4HZmJQQEJZNitvEAcDQX9aspebiEVDYcKaqKyuLEdY7DBpY52VBkCQEBgABZarbwLBCHjlCBYMBYDCsnEgYAG-A6hAw-j2M1MFiEKBJDCqWigSCwBADTC4e2fMgUShPABMekYD1YHHcZmEIFE4ikMgUynGGh4ph0secxjzHg4lkV9kc430bhLyZm+3YgX0YUi0SqhkSyW4qXSMEy2TyhRKco7tQaTRaoTaHW6vX6hyGI1H+yDt3u7vgTwAjO8PV8I9HfgKQZh4ZDCFKIUilajlOjh1jR3jaoTiYw6dTaeS1IdsHhRwNIQkkQew4FtMBaGtLdd3yFd-B3agTyFZQXmCIJPxpKD9V-dB3modZWyiGJ4nWIcihkW54zYEgoGwMgsBtXCwHeUJylgKBKAxEpVDgFY1k6cZ2KIShVHkaQhGo24CXgWj6MQRihGY9doNePc9n8OTDQUpjDmoND4DpHBkAwcoTMkplQVZKAhAAAxEMRUFZWQXnkWygA)

To further illustrate the issue, the expected behavior actually happens when you explicitly type the return type of `F` (in this case `{ type: V }`:
```ts
 // ...
    F extends <
        V extends A[number], 
        K extends keyof A,
    >(value: V, index: K, array: A) => { type: V } | {}
// ...

const items = ["object", "string", "number"] as const;
const $0 = transform(items, k => ({ type: k }));
    // ^?
    // Correctly becomes [{ type: "object" }, { type: "string" }, { type: "number" }], because the type is explicitly typed in the generic constraint
    // It should go to resolve to the type of `F` though
```
[Playground Link](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9&ts=5.0.0-dev.20230125#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxilQGdEcYBbAHgCh4H4w8SN4BBeEADwxFWAl4cKMDwQAnvGISA2gF0ANPHqMAYl179B8Oo33wAapr4Ch7WamSUARiBhKVBxgGkT2oQGsQEnIg6KqgwAfAAUAG5QEMggAFxGylgCPPEuyrBEEvHsAJTwALzB8ADeBBIADnFG8AC+8AA+JTW0YRlQWcIgouJSsgB0A+yOKOjxajnxpUHwsm5J8N6+-kPxAEogGMgwqAAqFSDUGPt+SGhg1BYuji7BRbQ1ANy0tMykbFh8lEL5MwBEODYAFbgDC-ZS-VgwJIAczB8F+Vls9l+8mkQlerCeGLYABIAAwFAhEUjkKihD4gL7KTwFIqhUpHSrxGk1HI5J76AD0nPgAD0APzTbnwADCFDgmEk8DszEoICEsgZ+3i-yBIN+tWUSqZ8MhMI1NS1ZR1COsdhgBscMqgyBICAwAAt7ft4FghDxyhAsGAPlLGSBgK78I6END+PZvUwWIQoEkMEKeQBJNgkB04ZAQQPQnAEHNwEg4CDhe05kPGhAnAAGakrBDTyGhDqAA)

**Comment by RyanCavanaugh** [comment]
What you're seeing there is an illusion. Consider tweaking it to this variant:
```ts
interface Lookup {
    object: "obj";
    string: "str";
    number: "num";
}
declare function remap<T extends (typeof items)[number]>(k: T): Lookup[T];
const m = remap("object");
//    ^? 'obj'

const items = ["object", "string", "number"] as const;
const $0 = transform(items, k => ({ type: remap(k) }));
```
The correct type of `$0` would be `{ type: "obj" } | { type: "num" } | { type: "str" }`

**Comment by ntucker** [comment]
This is a problem:
https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.0.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxilQGdEcYBbAHgCh4H4w8SN4BBeEADwxFWAl4cKMDwQAnvGISA2gF0ANPHqMAYl179B8agDUAfAAoAblAjIQALnh6AlPAC8B6agm1jsIhJuyAdAHsSkhoYDZqdjYA3vCyANLwWPgA1iASOIgc8jYASiAYyDCoACoSAA4g1BjlIBkh6NTs8fIGLgC+ANy0tMykbJmOusXGyVbFDs7wRjHVFTbJ8G12PSxsACQATE4ERKTkVEayAEQ4AEYAVuAYR8pHrDBJAOY38EeoyJSnIDBHwYh2XUY8AA9MD4AA9AD8qgYoPgAGUABY4ZAQYDwL6xGY1GwnC5XI6LZTYuave5PQltYkEHGvd6fb6U+RAA

```ts
declare function transform<
    const A extends readonly any[], 
    F extends <V>(value: V) => any
>(array: [...A], func: F): { [K in keyof A]: ReturnType<typeof func<A[K]>> };

const f = <T>(k:T) => ({ type: k })
const $2 = transform(["object", "string", "number"], f);
    // ^?
    // Should be [{ type: "object" }, { type: "string" }, { type: "number" }]
```

When I change to:

```ts
declare function transform<
    const A extends readonly any[], 
    F extends <V>(value: V) => {type: V}
>(array: [...A], func: F): { [K in keyof A]: ReturnType<typeof func<A[K]>> };

const f = <T>(k:T) => ({ type: k })
const $2 = transform(["object", "string", "number"], f);
    // ^?
    // Should be [{ type: "object" }, { type: "string" }, { type: "number" }]
```

it works - but that assumes we actually know the return value - if we're having the entire F be generic - maybe it'll have a different return type!


```ts
declare function transform<
    const A extends readonly any[], 
    F extends <V>(value: V) => {type: V}
>(array: [...A], func: F): { [K in keyof A]: ReturnType<typeof func<A[K]>> };

const f = <T>(k:T) => ({ type: k })
const f2 = <T>(k:T) => ({ blarg: k })
const $2 = transform(["object", "string", "number"], f);
const $3 = transform(["object", "string", "number"], f2);
    // ^?
    // Should be [{ type: "object" }, { type: "string" }, { type: "number" }]
```

This simply makes the second call fail...but if we make the generic accept that, then it won't give us a return type
