### ISSUE TITLE
Type not inferred correctly in `false` branch of conditional when using type with union (javascript with types)

### ISSUE THREAD

**Issue by MarcellPerger1** [microsoft/TypeScript#52040]
# Bug Report

### 🔎 Search Terms

literal types, boolean, conditional operator, union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behavior

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&filetype=js#code/PQKhCgAIUgBAXAngBwKYBNUDNIG9cCWAzgMoEB2A5gDaoBqAhtQK6oBck8ATqwDSRdURZtXgdyzALYAjVFwC+kAD55iZKrUYt2kLEyKp+g4aPFTZXANoBdeYoAqUEMHCvQEaHEHxmXckTx7eScXLGZyAGN4AgB7ckhJBgBrVHsACgBKPChIXO9feMJSChp6JlYObj4BIRExSABmeQBucGDwADcGLk5IAF4E5NTM1s7uyA7+zgA6NRLNctRIAH4Z4zrISun10UsABmtWoA)

### 💻 Code

```js
/**
 * @typedef {{isSingleValue: true, result: number} | {isSingleValue: false, result: number[]}} T
 */


/**
 * @returns {T}
 */
function makeT() {
    return {isSingleValue: true, result: 3};
}

var t = makeT();

var v = t.isSingleValue ? t.result : t.result[0];

```
(javascript with type checking)
### 🙁 Actual behavior

Got an error:
```
Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'number | number[]'.
  Property '0' does not exist on type 'number | number[]'.
```
This is wrong because `isSingleValue` being `false` means that `t.result` must be `number[]` instead of `number | number[]`. 
This bug doesn't occur with just typescript:
[Playground link with typescript example (that works as expected)](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UDeBLAzgZRQOwOYBsIA1AQ3wFcIAuKYAJ0oBoo6I1z9gbtyBbAIwh0AvlAA+ydFjyFSFalABmZNBGat2nbn0F0A2gF1hAKGOLy2AMbAUAe2xReJANYQYACgCUNOEmNQAlghgcjoHVEwcAmIyShp6JiDNLigAZmEAbmMTYwA3EjpaBEcXNy8svIKoXOLgADopKNlY6AB+WjqNDmAoeM62br0ABgMsoA)

### 🙂 Expected behavior

No error, the type checker can infer that `t.result` is a `number[]` because `isSingleValue` is `false`. This is what happens with just typescript instead of javascript with types (see link playground link above for typescript example working as expected).

**Comment by fatcerberus** [comment]
Just for future reference: This is a discriminated union.  Conditional types are something different.

**Comment by MartinJohns** [comment]
You have `strictNullChecks` disabled. Once enabled the code works as expected. Without it, `true` is not the only valid value for the `true` case, but `undefined` and `null` are valid as well. If you don't want to enable it, you need to explicit check for `true` by writing `t.isSingleValue === true`.
