### ISSUE TITLE
"extending" internal namespaces

### ISSUE THREAD

**Issue by sccolbert** [microsoft/TypeScript#5205]
I'm attempting to use internal namespaces to provide some constants attached to a class. I'd like to be able to inherit those constants in a subclass by "extending" the internal namespace of a base class.

Something like the following:

``` typescript
class Base {
    a: number;
}

namespace Base.Names {
    export const Foo = 'Foo';
    export const Bar = 'Bar';
}

class Derived extends Base {
    b: string;
}

namespace Derived.Names {
    export import Foo = Base.Names.Foo;  // required
    export import Bar = Base.Names.Bar;  // required
    export const Baz = 'Baz';
    export const Ham = 'Ham';
}
```

In the derived namespace, the re-exports are required to make the compiler happy. I would prefer there be a way to extend a namespace, but I could live with this as it exists. However, a problem crops up with the generated code:

``` javascript
// <snip>
var Derived;
(function (Derived) {
    var Names;
    (function (Names) {
        Names.Foo = Base.Names.Foo;
        Names.Bar = Base.Names.Bar;
        Names.Baz = 'Baz';
        Names.Ham = 'Ham';
    })(Names = Derived.Names || (Derived.Names = {}));
})(Derived || (Derived = {}));
```

The issue is that `Derived` has already had its statics copied by the `__extends` function, so `Derived.Names === Base.Names` and the exports are actually added in the namespace of `Base.Names`, which is undesired (is it a bug?).

This can be worked-around using actual classes and statics, but that is more typing and doesn't come with `const` checking:

``` typescript
class Base {
    a: number;
}

namespace Base {
    export
    class Names {
        static Foo = 'Foo';
        static Bar = 'Bar';
    }
}

class Derived extends Base {
    b: string;
}

namespace Derived {
    export
    class Names extends Base.Names {
        static Baz = 'Baz';
        static Ham = 'Ham';
    }
}
```

Is there a better way to express this pattern?

**Comment by RyanCavanaugh** [comment]
Interesting use case. I'll discuss this with some people to see what we think the a) correct behavior is and b) what the best pattern to use is.

**Comment by mhegazy** [comment]
My recommendation is to use spread operator with static properties. I believe this matches the intended semantics more than a namespace. 

```ts
class Base {
    a: number;

    static readonly Names = {
        Foo: 'Foo',
        Bar: 'Bar'
    }
}

class Derived extends Base {
    b: string;
    static readonly Names = {
        ...Base.Names,
        Baz: 'Baz',
        Ham: 'Ham'
    }
}
```

This way `Derived.Names` gets a copy of the `Base.Names` and augments it, instead of using the same object.

**Comment by sccolbert** [comment]
@mhegazy I like that solution, with the exception that `Names` is mutable. It's not entirely the same as using `const` for each member in a namespace.

**Comment by mhegazy** [comment]
>  I like that solution, with the exception that Names is mutable. It's not entirely the same as using const for each member in a namespace

No it is not, you can use `static readonly Names: Readonly<{Foo: "Foo", Bar: "Bar"}> = {...};`.

Ultimately i think you want string enums, these have all the characteristics you are looking for, but these are not supported yet.

**Comment by sccolbert** [comment]
Any appetite for the `readonly` keyword in object literals?

```
const things = {
    readonly one: 1,
    readonly two: 2
};
```

The `Readonly<{ ... }> = { ... }` options seems like needless repetition.

**Comment by nevir** [comment]
I've been following this sort of pattern as well; but it becomes even more awkward when you want to hang additional types and values off of the namespace like enums, types, etc.

Having to `export import` every named thing gets pretty awkward.

Example:

```ts
class PublicUser implements PublicUser.Data {
  isActive() { return this.status === PublicUser.Status.ACTIVE; }
}

interface PublicUser extends PublicUser.Data {}

namespace PublicUser {
  export interface Data {
    id: string;
    name: string;
    createdAt: Date;
    status: Status;
  }

  export enum Status {
    UNREGISTERED,
    ACTIVE,
    INACTIVE,
  }

  export type CreateFields = Pick<Data, 'name' | 'status'>;
}
```

```ts
class InternalUser extends PublicUser {
  deletedAt: Date;
}

namespace InternalUser {
  export import Data = PublicUser.Data;
  export import Status = PublicUser.Status;
  export import CreateFields = PublicUser.CreateFields;
}
```

**Comment by RyanCavanaugh** [comment]
Preferred suggested workaround is `static Names = { ...Base.Names, Baz: "Baz" }`

**Comment by nevir** [comment]
For the `namespace` example, would it be reasonable to ask for something like a namespace spread? (that'd pick up types, too?)

**Comment by sccolbert** [comment]
@RyanCavanaugh  Suggested workaround is not equivalent to namespaces because of `const` and the verbosity of defining an object literal with all `readonly` properties.

**Comment by RyanCavanaugh** [comment]
Declining due to lack of additional feedback and general noninvestment in value-based `namespace`
