### ISSUE TITLE
A generic in a custom type guard is not considered for the return type

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#52051]
# Bug Report

### 🔎 Search Terms

generic custom type guard 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAkgEylAvFABgMwQfQBIBvAZ2ACcBLAOwHMBfLAKFEigCEBDClDbAEY8iZSrUYs20eHG69UmGXwA+nHigDczZrWAQKOLgGNpCKMWZo0VZAC5YCFJatT7Acjxw3zBtt37DEzUKc2drO2CnKyhXKDchCm9fVnBTWR5+GShVOS1mHABXGiNgKjgaKCpSGQAKG3sZORQASnsbStIHJFRiKGTC4tLyqDoIYFr6rpaGs17+opKyitHgOTqIpuRW4PM+7SkuuRgKOABbFAAeABUoCAAPPRpkTsb1ZAA+DGcb+8fnqdQAH4ulBbN9bg8IE9OpsoMC5KDnK8KHkBothitkdcIX8XghNu91vYrttkcczpcrp8LGgAPS0qBXVJxGRuDpQGhwYBQLikUhUOg0LgCAA20GAcBizLcZJO52Q13e3jQFDGBQoFSqEy2cJGY21zVBetWPHWzS0yXpUEQblOUAK-PoUFOBRFpTAYqgyAgRhFPC4QxonV5PKgAHc4BQANY8OBFZDaNGB43IokA0kILRJpYp-Gmyabba5fILZOYvMUNPI6aHHhZ0s58vpSuTatbGbN0IqtUajoG3VNs1GlZrGzmnzMIA)

### 💻 Code

```ts
type FooId  = `foo_${string}`
type BarId = `bar_${string}`
type FooBarId = FooId | BarId;

interface Foo {
    id: FooId
    type: 'foo'
}

interface Bar {
    id: BarId
    type: 'bar'
}

type FooBar = Foo | Bar;

function isFoo(id: FooBarId): id is FooId { }

function getFoo(id: FooId): Foo { }

function getBar(id: BarId): Bar { }

type FooBarFromId<T extends FooBarId> =
  T extends FooId ? Foo :
  T extends BarId ? Bar :
  FooBar;

function getFooBar<T extends FooBarId>(id: T): FooBarFromId<T> {
  // Type 'Foo' is not assignable to type 'FooBarFromId<T>'
  return isFoo(id) ? getFoo(id) : getBar(id);
}

// I'm using multiple declarations as a workaround

function getFooBar(id: FooId): Foo;
function getFooBar(id: BarId): Bar;
function getFooBar(id: FooBarId): FooBar;
function getFooBar(id: FooBarId): FooBar {
  return isFoo(id) ? getFoo(id) : getBar(id);
}
```

### 🙁 Actual behavior
I have a function that accepts a generic constrained argument and has a return type that depends on the generic. The return type of the implementation is not compatible with the return type in the definition.

### 🙂 Expected behavior
There should be no error in the return  statement. FooBarFromId<T> type and the return statement implementations are compatible, it's like the compiler is not considering the generic in the equation.

**Comment by MartinJohns** [comment]
It's a design limitation. Resolving of conditional types is deferred when unbound type arguments are involved. In order to resolve `FoBarFromId<T>` the compiler needs to know what type `T` is, but within the function it can't know what `T` is because it's externally supplied.

**Comment by fatcerberus** [comment]
See also https://github.com/microsoft/TypeScript/issues/33912.

**Comment by mckravchyk** [comment]
I see. Thanks for explaining this. I hope that some day it will be possible.
