### ISSUE TITLE
Class statics allow "private" types to escape into exports

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#5206]
This seems like it may be a bug:

```typescript
namespace Root {
	
	class Private {
		p: number;
	}
	
	namespace Names {
		export const Foo = 'Foo';
		export const Bar = 'Bar';
		export const priv = new Private();
	}
	
	export
	class Base {
		static Names = Names;  // this should error (?) but doesn't
		static priv = new Private();  // also allowed
		a: number;
	}
}

var foo1 = Base.Names.Foo;  // error, as it should be
var foo2 = Base.Base.Names.Foo;  // okay, but shouldn't be (?)
var priv = Base.Base.Names.priv.p; // also okay, but shouldn't be (?)
```

Since neither `Private` nor `Names` are exported, it seems that compiler should error on the statics which effectively exports those types.

**Comment by ahejlsberg** [comment]
This is by design. The `Private` and `Names` *members* are not exported and therefore you can't access `Root.Private` or `Root.Names`. But that doesn't imply that entities with the same type or value are also private--it just means that you can't name the type of those members (but you could still match it structurally).

**Comment by sccolbert** [comment]
Interesting. I thought I recalled similar patterns erring with a message indicating that a public property of an exported class is using a private name, and sure enough, I just threw the following code into an actual file and tried compiling it:

```typescript 
export
namespace Root {

  class Private {
    a: number;
  }

  export
  class Public {
    static priv = new Private();
  }
}
```

and got this error:

```
src/index.ts(28,5): error TS4028: Public static property 'priv' of exported class has or is using private name 'Private'.
```

The code in the original example was tested in the playground, the code which failed was running against `1.6.2`. Is the playground running on a newer version with newer features, or is there something else going on?

**Comment by sccolbert** [comment]
Ah, okay I see what's going on. The code which failed to compile was running with the `--declaration` switch, which must fail because it can't reasonably generate a declaration for the non-exported types. Fair enough.
