### ISSUE TITLE
Static variables inside functions

### ISSUE THREAD

**Issue by Teselka** [microsoft/TypeScript#52065]
# Suggestion

## 🔍 Search Terms
static variables inside functions

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Support for static variables inside functions.
Example:
```ts
function Example() {
    static x: number = 0xAABBCC00;
}
```

Will be transpiled into (Emitted variable name may be different):
```js
let __static_x = undefined;
function Example() {
    if (__static_x === undefined) {
       __static_x = 0xAABBCC00;
    }
}
```

## 📃 Motivating Example

This is really useful because sometimes you do not really want to expose your static-like variables into the global scope.
Or if you want to initialize some data before using it.

Use case:
```ts
function handler() {
   static firstHandle: number = Date.now();

   const currentDate: Date = Date.now();
   if (currentDate - firstHandle > 1000) {
       // do something...
   }
}
```

**Comment by jakebailey** [comment]
You checked:

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

But this is syntax sugar for JS.

**Comment by fatcerberus** [comment]
Moot point since this won't be implemented in the absence of a corresponding ES proposal, but I note that the proposed emit is problematic: Explicitly setting the static variable to `undefined` should *not* cause it to be reinitialized on the next call.
