### ISSUE TITLE
Unexpected type evaluation with generic conditional type

### ISSUE THREAD

**Issue by duanwilliam** [microsoft/TypeScript#52068]
# Bug Report

### 🔎 Search Terms

generic types, deferred conditional types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Common "Bugs" That Aren't Bugs`, `Generics`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAggdgEwDwyhAHsCiDOUBGA9oQDYQCGcANFAEJqbYJ5GkVwB8UAvFANowatALoMsufsABOAVwg1pc0QH4oi6AC4oAM3IkcEAFChIUAHKFgSACpimLYmUpdetjOOZrZ0Vbv2avOUNjcGgAUUZcFCEXWDsJelV1KC0-A2CTaABJHABlaQBLOABzABkCrCk9G1i06AB6erVQqAQIbSKKgsI4KEIAWwqsBChKEYNgNUIoAAM6magACnwZYqgcYAKSElGwSHIpHABKDJacsxl+-Agpcsrq6xdDKFhEJGeXqAiPHBsaOEu1ykHCoHxeFis33sSABVxuNEeHA+SJCpgA8lIUPFPKwnNQ6NiHGxnDx+II6KJ3PZ+HUaHUVDo9AYUoEjIZGlBlFyuajsjg7jcHrEMUgcvkpEUyhVBSQajRzoCbgKqrLEeymi8AHrKU6mWy8DYSkq8qBbUk5ZVC9WfbXBRpNYAAC2gAGMehsKnI4JMwAdgHgAO6EKQAaygbqkUggLuAJBAuug5HNeUKJUtqqRHK1OsyBGTFzht2lKpq1uzCfDpJFYtTUvuGflOALQPTNUzGqgtpNI14fBrRrrMrlUAVhdbj0pkU8fFpjP8DLqLPUZc7OuC6qaJGIIclo0mOAG0EszqkUAxpv6YDI-WwwHIm3dFYxAAZonQni9UFSJMkkt4Plo9Dfp4v6sgBc7pCaFrFnor6PFWUivv2krjiCI5NoqRb1m2K62rmwDPsm6avoakrtjaa65i++BvrQH5kpOPySN4DLLi8Wh8CIhLMUonJgexEFsrm0H1s+NHwbw1GiimA6oY2zZKjBGbkeW+FiURSliUgpElCpq5PlIACMtH0QIQiMdSfDqAoLF8WxLJmRS3FWd4dJMhArH-gJjlccBeAzu5Nm8X+QQCXUFYiTKxkSWeRnSeKKFKcOo4tklapZvp+GGRp9bGTpxR6V2VFSAATCZPAfF+U54OFnx8UB1WCWCny+O5zUCfZHX-lB-JKWVMUYmVyFpmlaEpYp2HpR2eEtMAJU5TKZX5YVlEtINNHknRFUvAIFkSAF87NaonF7dO9LtXxtV1UuXmfFoy49emJXicKpU0cNg4lo88mYahK0mnN+ALSqS21v9QA)

or: [a much more minimal example of the error, that _does not_ appear in 4.9.4 but does appear in earlier playground versions](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBA8gTgHgIJQgD2BAdgEwM5QBGA9sQDYQCGWANFAEKobb5GkXUB8UAvFANpI69ALpNMuAvwBmlMngh1Z8iGID8UZQqgAuKMDgBXCACgToSFACSeAMoGAllgDmCACrc+b8SwJ5HLlAaBsa6mnIKZgD0UUFq8Wrm4NA29nBOzgBM7p6wiKkBrh5KERCcJjFQVQB6iRWxAAbwDUwO-hlQOMQQeFgA5MBQChAAtvrERNDAABbQYHDEhBQjSZYF6S4AzDm8AusZOSUqYugSrDKlRwrq4SphIaaVNWpAA)

### 💻 Code

```ts
type Or<A extends boolean, B extends boolean> = [A, B] extends [false, false] ? false : true
type And<A extends boolean, B extends boolean> = [A, B] extends [true, true] ? true : false
type Not<T extends boolean> = T extends true ? false : true
type Extends<A, B> = A extends B ? true : false

type IsStringLiteral<T> = false // type definition omitted and set to `false` (bug still appears)
type IsNumberLiteral<T> =
  And<
    Extends<T, number>,
    Not<Extends<number, T>>
  >

// !!!!!!!!!!!
type IsLiteral<T> = Or<IsStringLiteral<T>, IsNumberLiteral<T>>
//   ^?type IsLiteral<T> = true
```

or much more minimal example of error for playground versions <4.9:

```ts
type Or<A extends boolean, B extends boolean> = [A, B] extends [false, false] ? false : true

type IsString<T> = T extends string ? true : false

// ?????
type IsString2<T> = Or<IsString<T>, false>
//   ^?type IsString2<T> = false

// `Or` existing doesn't seem to be the problem
type IsString3<T> = [IsString<T>, false] extends [false, false] ? false : true
//   ^?type IsString3<T> = false
```

### 🙁 Actual behavior

The `IsLiteral<T>` type is always `true`, which is unexpected. I'd expect it to be computable only when type parameter `T` is passed in, as the value of `T` can change which branch of the conditional type to follow. For instance, expanding `IsLiteral<T>` for a given `T`, e.g. `type IsStringTypeStringLiteral = Or<IsStringLiteral<string>, IsNumberLiteral<string>>` gives the expected and "proper" result.

A comment from user `xor_01` on the TS discord:
> This is just my guess as to what's going on here:
instead of "calculate" actual type of IsNumberLiteral<T> compiler decides for some reason to replace it with boolean and your implementation of Or returns true for boolean

### 🙂 Expected behavior

`IsLiteral<T>` shouldn't be replaced with `true`. Since the type parameter can affect the outcome of the conditional type, TS shouldn't determine the type to always follow some given condition.

**Comment by ahejlsberg** [comment]
We currently have logic to ensure conditional types of the form `[X] extends [Y] ? A : B` are deferred when `X` or `Y` are generic types. However, this logic only handles singleton tuples. We should extend it to handle tuples with multiple elements.
