### ISSUE TITLE
Intersection Type not merging objects in array properly

### ISSUE THREAD

**Issue by ErlendS** [microsoft/TypeScript#52073]
# Bug Report

### 🔎 Search Terms

intersection type, intersection type array

### 🕗 Version & Regression Information

- This changed between versions 4.8.4 and 4.9.4
- This bug also appears in version 3.5.1, 3.3.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/JYOwLgpgTgZghgYwgAgMIHsA27YFdPIDeAUMsgljgFzIDOYUoA5gNzEC+xoksiKqwKAkwoSZKHAAmwXLRohcAWwBG0Np2JgAngAd+lPJgFCRyALxoDMfAG0AusgBkaQcIj22xCiHrJI9GgxsQ2M3c2QbMXIDGgByKAhJWIAaUmQJaVkaACYOOyA)

### 💻 Code

```ts
interface Colorful {
  color: string;
}
interface Circle {
  radius: number;
}

type ColorfulCircle = Colorful[] & Circle[];

const test: ColorfulCircle = [{
  color: 'red',
  radius: 2
}]
```

### 🙁 Actual behavior

radius field gets type error:  `Object literal may only specify known properties, and 'radius' does not exist in type 'Colorful'`

It looks like it is treating it as a union type where only one of the fields can exist.

### 🙂 Expected behavior

I expected the merging of the types to make color and radius accessible (and required) in the  `ColorfulCircle` type.

**Comment by fatcerberus** [comment]
`ColorfulCircle` should be defined as `(Colorful & Circle)[]`.

**Comment by ErlendS** [comment]
> ColorfulCircle should be defined as (Colorful & Circle)[].

Thanks for replying. That would fix this, but it is a contrived example to show the issue. I can't use that fix in the real issue I'm having.

What I am wondering is if the error I am getting now is a bug introduced in TS 4.9 since that used to work. (and the issue also shows up in two other versions, and then seems to be fixed again)

[Looking at specs](https://github.com/microsoft/TypeScript/blob/main/doc/spec-ARCHIVED.md#35-intersection-types) (though depricated)  it looks like the intended behaviour of the intersection type would be to merge the two types to something like: `Array<{color: string, radius: number}>`

**Comment by jcalz** [comment]
Duplicate of #41874

**Comment by ErlendS** [comment]
Yes, sorry I didn't find that when searching. Will close this one then.

**Comment by ErlendS** [comment]
by the way @jcalz, any idea why my code example works on version 4.8, but not 4.9?
