### ISSUE TITLE
Add integer and float like an implicitly type

### ISSUE THREAD

**Issue by gusantoscode** [microsoft/TypeScript#52075]
# Suggestion

  Add an `integer` and `float` like an **implicity type**

## Code Example

```
const Home = (props: { age: integer }) => {
  return null;
}
```

`integer` value example: 1000
`float` value example: 100,25

## 🔍 Details

  Self-explanatory title

**Comment by xiBread** [comment]
Duplicate of #195, #28682, #30543, etc.
