### ISSUE TITLE
Intl.NumberFormatOptions options are missing

### ISSUE THREAD

**Issue by nick-korolev** [microsoft/TypeScript#52072]
# Bug Report

Hi. According to [specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#parameters) `Intl.NumberFormat` contains `numberingSystem` option, but typescript throws the error `Object literal may only specify known properties, and 'numberingSystem' does not exist in type 'NumberFormatOptions'`

### 🔎 Search Terms

Intl, NumberFormatOptions

### 🕗 Version & Regression Information

`"typescript": "^4.9.4"`

### 💻 Code

I have a monorepo with this structure

root
  - base.tsconfig.json
  - package.json
  - app1
     - index.ts
     - tsconfig.json
     - package.json

### base.tsconfig.json
```
{
  "compilerOptions": {
    "module": "ESNext",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "target": "ESNext",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "allowJs": true,
    "checkJs": false,
    "lib": [
      "esnext",
      "dom"
    ],
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "baseUrl": "."
  }
}

```

### app1/tsconfig.json
```
{
  "extends": "../base.tsconfig.json",
  "compilerOptions": {
    "module": "ESNext",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "target": "ESNext",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "allowJs": true,
    "checkJs": false,
    "lib": [
      "esnext",
      "dom"
    ],
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "baseUrl": "."
  }
}
```

### app1/index.ts
```
const amount = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  numberingSystem: 'latn'
}).format(1000);

console.log(amount);
```

### 🙁 Actual behavior

After type checking typescript throws error 
```
index.ts:4:3 - error TS2345: Argument of type '{ style: string; currency: string; numberingSystem: string; }' is not assignable to parameter of type 'NumberFormatOptions'.
  Object literal may only specify known properties, and 'numberingSystem' does not exist in type 'NumberFormatOptions'.

4   numberingSystem: 'latn'
    ~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in index.ts:4

```

### 🙂 Expected behavior

The typescript correctly checks the types that are specified in the specification

**Comment by sirbrillig** [comment]
I just ran into this issue myself. Weirdly it's not available in [the es2020 definition](https://github.com/microsoft/TypeScript/blob/cfd472f7aa5a2010a3115263bf457b30c5b489f3/src/lib/es2020.intl.d.ts#L272) of `ResolvedNumberFormatOptions`, even though it [is present in the es5 types](https://github.com/microsoft/TypeScript/blob/cfd472f7aa5a2010a3115263bf457b30c5b489f3/src/lib/es5.d.ts#L4310). It's hard for me to tell when it was added to JS, but [for a similar property in Intl.Locale caniuse suggests](https://caniuse.com/mdn-javascript_builtins_intl_locale_numberingsystem) that it is pretty well supported.

**Comment by ianschmitz** [comment]
Indeed i noticed `trailingZeroDisplay` is also missing.

**Comment by tiagofilipenunes** [comment]
Following up on this, according to the [specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#parameters), roundingMode should also be available, but typescript is throwing an error:

`Object literal may only specify known properties, and 'roundingMode' does not exist in type 'NumberFormatOptions'.`

[Caniuse](https://caniuse.com/mdn-javascript_builtins_intl_numberformat_numberformat_options_roundingmode_parameter) is showing it is widely available as well.

Multiple other options are missing as mentioned in https://github.com/microsoft/TypeScript/issues/43336

**Comment by sshmaxime** [comment]
For anyone having this issue add `ESNext` to your `lib` in your `tsconfig.json`.
