### ISSUE TITLE
Mobile UX improvement

### ISSUE THREAD

**Issue by Forseti93** [microsoft/TypeScript#52079]
# Suggestion
To add .preventDefault( ) for touch event if a user is scrolling the code editor.

# Location
[Here](https://www.typescriptlang.org/play?q=463#example/any) in the code editor touch event always opens the keyboard, if you'll try to scroll.

# Reason
It's uncomfortable to scroll on mobile. The keyboard pops up every time I try to scroll.

**Comment by RyanCavanaugh** [comment]
This is Monaco's logic, not ours. https://microsoft.github.io/monaco-editor/
