### ISSUE TITLE
tsconfig.tsbuildinfo not being respected

### ISSUE THREAD

**Issue by Lav39** [microsoft/TypeScript#52077]
# Bug Report
I am committing tsconfig.tsbuildinfo file in GitHub so that we can optimize ts check on CI build, however, it is not working as expected, in fact, it is taking more time on CI and other machines. 
However, if I run ts: check command twice on CI machines, the second build is extremely fast. 

Note: TS version is exactly the same for the machine where tsconfig.tsbuildinfo is originally generated and the CI machine

tsconfig.json

`
{
  "compilerOptions": {
    "baseUrl": ".",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "incremental": true,
    "target": "esnext",
    "module": "esnext",
    "jsx": "react",
    "noEmit": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitThis": true,
    "removeComments": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "allowJs": true,
    "paths": {
      "api": ["app/api/index"],
      "modules/*": ["app/modules/*"],
      "lib/*": ["app/lib/*"],
      "tests/*": ["tests/*"]
    }
  },
  "include": ["**/app/*", "**/tests/*", "**/@types/*"],
  "exclude": [
    "**/node_modules/*",
    "**/internals/*",
    "**/server/*",
    "**/public/*",
    "**/ci_scripts/*",
    "**/testOutput/*",
    "**/build/*",
    "**/app/**/__tests__/*"
  ]
}
`

What could be the possible reasons?

### 🔎 Search Terms
tsconfig.tsbuildinfo, --incremental, tsbuildinfo

### 🕗 Version & Regression Information
Typescript : 4.9.3

### 🙁 Actual behavior
TS check not respecting tsconfig.tsbuildinfo 

### 🙂 Expected behavior
TS check should re-use tsconfig.tsbuildinfo and execute check faster

**Comment by RyanCavanaugh** [comment]
We'd need more info about your project structure to speculate on why this might be happening.

**Comment by Lav39** [comment]
@RyanCavanaugh 
Here is tsconfig which exists at root

`
{
  "compilerOptions": {
    "baseUrl": ".",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "incremental": true,
    "target": "esnext",
    "module": "esnext",
    "jsx": "react",
    "noEmit": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitThis": true,
    "removeComments": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "allowJs": true,
    "paths": {
      "api": ["app/api/index"],
      "modules/*": ["app/modules/*"],
      "lib/*": ["app/lib/*"],
      "tests/*": ["tests/*"]
    }
  },
  "include": ["**/app/*", "**/tests/*", "**/@types/*"],
  "exclude": [
    "**/node_modules/*",
    "**/internals/*",
    "**/server/*",
    "**/public/*",
    "**/ci_scripts/*",
    "**/testOutput/*",
    "**/build/*",
    "**/app/**/__tests__/*"
  ]
}
`

**Comment by Lav39** [comment]
any update?

**Comment by chrisdothtml** [comment]
Also seeing this issue. Out of curiosity, does ts use file modified date (or some other heuristic that would change across CI builds), or does it cache based on file content?

I know eslint has a [--cache-strategy](https://eslint.org/docs/latest/use/command-line-interface#--cache-strategy) option to use file content for the cache for cases like CI (where the exact CWD and modified date of files is subject to change), I wonder if Typescript may need something similar

**Comment by chrisdothtml** [comment]
Okay I've been doing some digging and I think I found the problem (for our case at least). It's not to do with non-deterministic file hashes, it's to do with the fact that when a package uses `emitDeclarationOnly`, the declaration files are generated with `import` statements that use absolute file paths. Since the absolute path changes across CI builds, the hash of these declaration files also changes

**Comment by RyanCavanaugh** [comment]
Please log a new issue with complete repro steps if you have an actionable issue. We're not really able to help debug individual project configurations.
