### ISSUE TITLE
Using an array union type A[] | B[] gets evaluated to A | B when accessing an element of the array

### ISSUE THREAD

**Issue by jose-adalo** [microsoft/TypeScript#52084]
# Bug Report

Using an array union type A[] | B[] gets evaluated to A | B when accessing an element of the array

### 🔎 Search Terms

array union, 
union of arrays,
accessing an element,
union of custom typed arrays,
accessing an array element 

### 🕗 Version & Regression Information

V3.3.3 to
V4.9.4
(All typecript playground versions)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3#code/JYOwLgpgTgZghgYwgAgILIN4Chm7wgC2ABsATKCEALlQG0BdHPXOK5EAVwFsAjaLAL5YsoSLEQoAQpibNCJcpSqSGsvDzade-IVgQB7EAGcwyGBxAJkAXmQAKfTwBWbOvWQAfZCvoBKKgBu+sCkNgB8Msy4jk60AAz0AHTyZBQgNsi0MbQAjPSMUcjZCclEqZSJAA4cRgQOzrl+gkA)

### 💻 Code

```
interface A {
      children:A[]
      a: number
}

interface B {
      children:B[]
      b: number
}

const func = (obj: A[] | B[]):void => {
      obj[0].children = [obj[1]]
      obj[0].children.push(obj[1])
}
```

### 🙁 Actual behavior

This gives a compilation error
```
Type '(A | B)[]' is not assignable to type 'A[] | B[]'.
  Type '(A | B)[]' is not assignable to type 'A[]'.
    Type 'A | B' is not assignable to type 'A'.
      Property 'a' is missing in type 'B' but required in type 'A'.(2322)
```

### 🙂 Expected behavior

No errors, 
if obj is A[], then obj[1] is of type A and can be assigned to obj[0].children = [ obj[1] ], 
else the same applied but with B

**Comment by RyanCavanaugh** [comment]
From TS's perspective, there's no difference between this code and
```ts
const func = (obj1: A[] | B[], obj2: A[] | B[]):void => {
      obj1[0].children.push(obj2[1])
}
```
which is clearly unsafe. We don't track where objects "came from" to establish higher-order relations.

**Comment by jose-adalo** [comment]
@RyanCavanaugh 
I do agree that the second code, the one you provided, is unsafe and that is how it works now.

I know you don't track origin, 
the only thing that's clearly confusing from a development experience is that
in my example: 

obj: A[] | B[] can't have elements both A | B, 
so when using two elements from itself, they should both have the same type.

As it is now A[] | B[] is similar to (A | B)[] 

which is not what developers would expect.
Not even chatGPT lol
