### ISSUE TITLE
VSCode "go to definition" in TypeScript goes to node_modules instead of resolving symlink

### ISSUE THREAD

**Issue by rose-m** [microsoft/TypeScript#52082]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.74.2 (Universal), Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
- OS Version: OS: Darwin x64 22.2.0

I also reproduced it with Insiders Version: 1.75.0-insider (Universal) Commit: 42814d18a7d46adfb1c24e1349b7ab18833ec6a.

Steps to Reproduce:

See the code in the following repository and README to reproduce: https://github.com/rose-m/vscode-symlink-repo

The problem is that VSCode stopped to resolve symlinks from yarn workspace packages inside node_modules to the actual files in the repository.

[Excerpt from README]:
1. Run yarn to set up all dependencies (i.e. typescript).
2. Run yarn build inside packages/api and also in packages/app.
3. Open VSCode and navigate to [packages/app/src/index.ts](https://github.com/rose-m/vscode-symlink-repo/blob/main/packages/app/src/index.ts).
4. Place cursor inside the function call to testFunction() and hit go to definition.

**Expected Result**
VSCode opens the file packages/api/src/index.ts in the editor and also focuses it in the Explorer window.

**Actual Result**
VSCode opens the file path node_modules/api/src/index.ts which is actually symlinked to the expected file but VSCode does not resolve the symlink.

**Comment by andrewbranch** [comment]
Why does packages/api/package.json say `"main": "src/index.ts"`? Changing it to the expected `"dist/index.js"` fixes the issue. It seems like this is still our bug, but that’s the cause.

**Comment by andrewbranch** [comment]
Oh, never mind. You have `preserveSymlinks` enabled. This is working as intended.

**Comment by rose-m** [comment]
@andrewbranch Thanks a lot for your comment and indeed - sorry for not noticing the `preserveSymlinks`. Removing this fixes the the issue 👍 

I am curious however, when that behavior changed. We had this wrong setting in the `tsconfig` for 16 months now and it was bugged then for a very long time and now it got fixed and we noticed the change... 😅 But yeah - problem solved!!
