### ISSUE TITLE
Unexpected unknown value in the change from 4.9.3 -> 4.9.4

### ISSUE THREAD

**Issue by hansoksendahl** [microsoft/TypeScript#52098]
# Bug Report

The Slice type defined in this snippet stopped working in the change from TypeScript 4.9.3 -> 4.9.4.

The Add type called from Slice now reports an error.

```
Type 'Add<B, Length<D>>' does not satisfy the constraint 'number'.
  Type 'Length<[...AnyTuple<B, any, []>, ...AnyTuple<Length<D>, any, []>]>' is not assignable to type 'number'.
    Type 'unknown' is not assignable to type 'number'.(2344)
```

### 🔎 Search Terms

"4.9.4", "Type 'unknown' is not assignable to type 'number'."

### 🕗 Version & Regression Information

Immediately after 4.9.4 dropped.

- This is a crash
- This changed between versions _4.9.3_ and __4.9.4__
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/FAUwHgDg9gTgLgAjgTwiBBBAdsjMYCGyAPBguHCFgCYDOCBOCAvAzgHwuYDaAuggB8EMEAWpQsAG2Q9ewUJFiIUaBABkqAczgALUuTCUa9bLnxFOrMhSp0EAbwSStugFwIAllgBmIGAgAhBABfYAQEAH5AsIR3LBAANz95cGh4JFR0DVpaABUdRn0bYwQsAFcAWwAjPwAaQIMjO3Lqv0sEAGUoCpAALT8oUnqAzmK7OBgykBiogElaAFEARzKCSSHA0cNbegmpmPCo7zXaafDw92ttkoAGA8ikSbPz92PJU5j3bLyCrGIOspVCYEADGcA2AEZ2PUAUDCGDiAF6lD2ClFOkVOguj1+jBBlcmvQWjUYMNGjtSpUSe0APIwYgxea4-HQxm0ZmI1GohRpZSZBBMgZFa7NKltLjzZardYYeo3bmpJQZVSSlZrDYjLjYajESXXWgeCQa6ECxb6w1-JGYdgK9F81R04WEhBVKBQZyMMljeiu92iLDtAkUvbPKIhz4Nb2PfaHaPPV4naY8pWYzA0J0U30erBekU+t3ZwPkkrh2NBKOl85hp73BPveMIN4fZMY-l6owGo2yzZa4t2ILVqaxRuJtG85XoDDUHVBkrEuqRvOU1owQMiAByBDgZUI6xispiAWAW2dlaiGiw2j0AGEJCCt6QcLkyhBnKQTaZn6+QJybRH4kkMBjim-J4CAm7bruGZzmKpKLs686rlq6ZshBO7qhgrLhPMaFQSMx7Aa2Kq0LhGF9kSsGBumOESOuICaFuHhJO+9TzAA6jofrvra46pp+L5vvu5HLiStSHsJjAyKwklieE17CaYeCEFJCB8MeXDyVG9gxM4l5uJgwChLG14Rvx34avU3AAHQ2dewy8DxIHEeutH0YxzGzqKK7tC54I4W5cBMT+mGOUR6D+QxgUecJiHtO2VCdn8AAGAAk9gYMESX1ElAC0aWIZloX2ugvnQXYWb+kWFZPA8TboO44YtsVpocVxnkUd5XClfMAAiIAgh4FQYX+TUTqafUDUNMoxZREpmh2FoMuEqXpZlskICtBVWflsGZQRo2prCwIIu1IkLuWS6xVqG5buhe7hAe4RHiewY1rGZlvphwnWTZXi+P4dkIDZVkfT+IxyOcDwXlexDXqikNxIkyQXKUSNAYRzW3lg97gqdinmMgubOvjyntD9IP1MDARyPIB38h0kgeCCP5CVGJNEOtF0IbBXA3OtmmXTzrDQ7oLExD1Ck4EpRBcHw60LDNK5cCLeg9VyysgDk+SFFaKvccJZ7qJrPyFFOOq6y4qs2vUcMG29VZG1rvykNOiL1HrasmnrIV2zGkMPAzTPBcMNuWcDPX1Bg3Bm27Rt6Vb7C8A59woz1tYIGnKNqcAh2M8zuSa4grCB8zxDcAA5AQ5f1OXVTVwg5cgvX5fUM3IDl7w9QAEz1AALJwwBAA)

### 💻 Code

```ts repro
export type Slice<
  A extends AnyArray,
  B extends number = 0,
  C extends number = Length<A>,
  D extends AnyArray = [],
  E extends number = Length<D>
> = LessThan<B, Length<A>> extends true
  ? LessThan<Add<B, Length<D>>, C> extends true
    ? LessThan<Add<B, Length<D>>, Length<A>> extends true
      ? Slice<A, B, C, [...D, A[Add<B, Length<D>>]]>
      : D
    : D
  : []
```

### 🙁 Actual behavior

The Add type is reporting an error about returning type unknown when it should always return type number.

### 🙂 Expected behavior

The Slice type should work as expected.

**Comment by RyanCavanaugh** [comment]
This is a correct (or at least reasonable) error, since there's not a readily-observable guarantee that that `Length` returns a `number`. You'd need
```ts
export type Length<A extends AnyArray> = number & (A extends { length: infer B }
  ? B
  : never)
```
or
```ts
export type Length<A extends AnyArray> = (A extends { length: infer B extends number }
  ? B
  : never)
```
