### ISSUE TITLE
Add es2015 as valid target in tsconfig.json

### ISSUE THREAD

**Issue by dsebastien** [Microsoft/TypeScript#5209]
It would be nice to be able to set the following in tsconfig.json: `"target": "es2015",` rather than `"target": "es6",`. In practice the TypeScript compiler should just interpret both the same way.

Given that they've renamed the spec, it would make sense to try and stay aligned... although the ES6 name will surely stick around for a while :)

**Comment by RyanCavanaugh** [comment]
This seems reasonable to me. @mhegazy ?

**Comment by mhegazy** [comment]
yeah.. it is unfortunate though that some tsconfig.json files will have "es6" where others would have "es2015"..

moving forward we should not use targets like "es7" to avoid the confusion.

**Comment by mhegazy** [comment]
A PR would be welcomed.

**Comment by weswigham** [comment]
@mhegazy should the module kind names be updated as well? We have yet to make a release with the `es6` module kind.

**Comment by mhegazy** [comment]
:D i suppose so.

**Comment by dhusemann** [comment]
should a target of es2016 be added already? ??

**Comment by mhegazy** [comment]
The target ES6 and module ES6 are already supported. this issue is about the name of the target and module; in addition to `--target ES6`, `--target ES2015` should be allowed, and both will mean the same thing. this also applies to `--module ES2015

**Comment by dsebastien** [comment]
Great :)

**Comment by jods4** [comment]
It seems diagnostics messages were forgotten...
`Argument_for_target_option_must_be_ES3_ES5_or_ES6`
doesn't mention ES2015.
