### ISSUE TITLE
Import  is not considered as value when used in decorators

### ISSUE THREAD

**Issue by AlekhyaYalla** [microsoft/TypeScript#52093]
# Bug Report

### 🕗 Version & Regression Information

Version: 4.9.3
Regression: While a class has been imported using `import` and used in the decorator `@inject` or `@injectable`, we are seeing a lint error/warn saying -> ` All imports in the declaration are only used as types. Use "import" type `
And the decorators will not accept the types, else will show up error `'class' cannot be used as a value because it was imported using 'import type'.ts(1361)`

### 💻 Code

```
import { Foo} from "./MyModule"; // Throwing lint error "All imports in the declaration are only used as types. Use "import" type"

@injectable()
export class Bar{
  constructor(
    @inject(Foo)
...    
```

### 🙁 Actual behavior

Throwing lint error in import as shown there

### 🙂 Expected behavior

When using the foo class in decorator `@inject` it should identify it as "value" and shouldn't consider the `foo` as unused.

**Comment by RyanCavanaugh** [comment]
This isn't our code. See https://github.com/typescript-eslint/typescript-eslint/issues/5903
