### ISSUE TITLE
"Add missing properties" quick fix for calculated string values generate either empty string or undefined even when it knows the correct value is known

### ISSUE THREAD

**Issue by aurimasniekis** [microsoft/TypeScript#52097]
# Bug Report

The quick fix "Add missing properties" on objects with inferred/calculated strings produces either `undefined` or `""` values even then it knows what the exact value is supposed to be as it itself complains about incorrect value.

### 🔎 Search Terms

* Add missing properties
* quick fix
* undefined

### 🕗 Version & Regression Information

4.9

- I assume that this was never working correctly as I have tried several random versions

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHJwD8AXMgEaYA2EcIA3PoRWZTXY8wQuVerXpNCyACbkAzmCigA5sMIQ2-QVwC+uXGACeABxQBBZAF4cyANoBpZKGQBrCNvQw0mALoBaNtmQg4AWwhySwAaZAA3OGoAVyDkAAMMLAASbABVXX0oBDgJCAAeSwA+NXjkNQ0AekrCAD1iTQR0ECkiciNTPDUGIA

### 💻 Code

```ts
interface Foo {
    a?: boolean;
    b?: boolean;
    c: boolean;
    d: string;
    e?: boolean;
}

type A = { [K in keyof Foo]-?: { name: K, value: `Foo ${Uppercase<K>}` }}

const a: A = {
};
```

### 🙁 Actual behavior

The quick fix "Add missing properties" generates this code:

```ts
interface Foo {
  a?: boolean;
  b?: boolean;
  c: boolean;
  d: string;
  e?: boolean;
}

type A = { [K in keyof Foo]-?: { name: K, value: `Foo ${Uppercase<K>}` }}

const a: A = {
  a: {
    name: undefined,
    value: ""
  },
  b: {
    name: undefined,
    value: ""
  },
  c: {
    name: undefined,
    value: ""
  },
  d: {
    name: undefined,
    value: ""
  },
  e: {
    name: undefined,
    value: ""
  }
};
```

### 🙂 Expected behavior

The quick fix "Add missing properties" to generate this code:

```ts
interface Foo {
  a?: boolean;
  b?: boolean;
  c: boolean;
  d: string;
  e?: boolean;
}

type A = { [K in keyof Foo]-?: { name: K, value: `Foo ${Uppercase<K>}` }}

const a: A = {
  a: {
    name: "a",
    value: "Foo A"
  },
  b: {
    name: "b",
    value: "Foo B"
  },
  c: {
    name: "c",
    value: "Foo C"
  },
  d: {
    name: "d",
    value: "Foo D"
  },
  e: {
    name: "e",
    value: "Foo E"
  }
};
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
