### ISSUE TITLE
Passing concrete type to function breaks type with default initialization

### ISSUE THREAD

**Issue by GCastilho** [microsoft/TypeScript#52101]
# Bug Report

### 🔎 Search Terms

concrete type generic parameter fail default 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Generics`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&jsx=0&ts=4.9.4#code/MYewdgzgLgBA5gUygEQIZVQMQE4gLYDKGUCMAvDADwAqAfABQCU5tMA3gFACQ2SArtjDtuXAGYgQALhgByAEapsM7gF8YqCDD5gA1mBAB3IRpjUOKjhygBPAA6kAwuFEBLODVYVOXKNlSRxbDxMMAB+aXoAE3RUaWpmMlZtPUMwc0tRbWAoF3AtCARqBGgACQkdSm5qGAQADxIwSM0AJQRQbEjKaGwXMDgAGi1dfSNafu4HGvqERs0nMFd3OnIYecWPcYZvX38IQOCwcZVpB2Ztu1JqPwCQIIRItAwVhwBtGR2boJCZAF0phqaMCiMWk-msCVYvVECGwMAAqiJQvCRHFLFxQJBYNEnhRECgYjh8ER0AgPEw0RjoDAPntbnh7it6CIafsQiIuEiWXSQsCMIx2dJsahuMwTFddvt7o9hdxeFABEIuXdIukOJTYFAAIzSVrtTrdXoDIYpUYrPgFIqlcr0Ngqfnq6kAJmkBr6ZotxSgZRAOht3CVB2kADcWDAAAYAEjYQZUYfM9vAVKgAGZ3YVPd7fdtrrSvmBg6HvDx+IJhFxy+IpOGozG4+WLFwLHa1YmNcnpS7fIaVimAHSVyw2ewwABCigIAAtUMOvNwFNhpGA+Hg5DD0g6oAAWRfL1ewijm9NWn2UMfYSfThBbf051n5mAhxIP3vzo78oA)

### 💻 Code

```ts
type Config<T> = {
	transformFn?: (data: T) => unknown
}

function useTestHook<
	T extends Record<string, unknown>,
	C extends Config<T> = Config<T>,
>({ transformFn }: C) {
	type TransformedData = C['transformFn'] extends (data: any) => infer U ? U : T

	const data: T = getDataFromState<T>()
	return (
		transformFn
			? transformFn(data)
			: data
	) as TransformedData
}

const t2: string = useTestHook({
	transformFn: v => `${v}`
})

type BarShape = {
	bar: number
}
// t4 should have type number, but it has type BarShape
const t4: number = useTestHook<BarShape>({
	transformFn: v => v.bar,
})
```

### 🙁 Actual behavior

When using a generic function that has a type with a default value (C in this case) and that it's return value depends whether C has specific properties, then, if a concrete type is passed as one of the types, the "shape" of C is not correctly inferred and the return type is incorrect, something that does not happen if no concrete type is passed to the function (return type correctly inferred)

I've noted, using VSCode, that on t2 (no types), the type for C is correctly inferred to have a `transformFn` that returns a string
![image](https://user-images.githubusercontent.com/34466758/210595610-922720f8-cd75-47b3-a712-cba70afce56a.png)

But on t4 (passing the first type manually) C is inferred as just `Config<BarShape>` which explains why TransformedData is coming up as `BarShape`
![image](https://user-images.githubusercontent.com/34466758/210595946-8747db6e-a469-4806-8b59-ca80fb9a5f88.png)

### 🙂 Expected behavior

On my understanding, non passed type parameters should behave the same way if one concrete type is passed as when none is

So passing `BarShape` on t4 with a object containing a `transformFn` as parameter should return the transformed value (the type returned from `transformFn`) exactly like when no concrete type is passed on t2

**Comment by RyanCavanaugh** [comment]
> On my understanding, non passed type parameters should behave the same way if one concrete type is passed as when none is

This isn't correct.

If any type arguments are provided, then the remaining type arguments are fixed to their defaults rather than going through inference. This is the same behavior as if you wrote
```ts
const t4: number = useTestHook<BarShape, Config<BarShape>>({
	transformFn: v => v.bar,
})
```

**Comment by GCastilho** [comment]
Isn't that counter intuitive?

Like, if no types are passed, C will be inferred using the concrete object informed, but if I pass one type, letting C "blank" it will not infer from the object passed but use the default?

I think this is really weird, is it really the expected behavior?

If so, is it open to being discussed in a feature suggestion or something?

**Comment by fatcerberus** [comment]
Yes, this is the expected behavior, and you're definitely not the first person to hit it.

> is it open to being discussed in a feature suggestion or something?

See https://github.com/microsoft/TypeScript/issues/26242.

**Comment by GCastilho** [comment]
Ok... 😢

Should I close this one, then?
