### ISSUE TITLE
array.every not working consistently

### ISSUE THREAD

**Issue by damianobarbati** [microsoft/TypeScript#52107]
# Bug Report
`array.every` on union `string[][] | string[][][];` throws a `This expression is not callable.`.

### 🔎 Search Terms
- `array.every not callable`
- `.every not callable`
- `every not callable`

### 🕗 Version & Regression Information
TS 4.9

### ⏯ Playground Link
[Repro here on TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBACg9gGxAczgOygXigZ2AJwEs1kBtAXQqgB9cDizKmBuAKFYGN08owBGAFyxEKdFiilSAcj5SANDKnk5EqQCZ56pSukBmTbOWrZCw+TZc0PMGqHwkqDNknSTio9I0KNHqftPaxgZKHp6aPnKeAHQALOGx2npRZubs-FEQAG4Q+CAAFJY4iBBRCHDIAJTMUAD0NVCEwFAA7nD4ANY4UVAAcnBQXAC2YAgAhsRdrDYZ2bkF3MWl5VW19Y0tbZ3dfQNww2MTUeyFTQBmTlB5YCKOdjfoFUKZcIQAJlgAfFAA3qxQq1AZjkQLt9uMrC1GgALKAAImAUMIOCgEAAHmB8BAcDhCGIkVA0HAmhxRggxgAjBAQWF-BqnS7XBzoIFzK4VT68UoQEgIrCYbBqCrs37-f51WkAX1YErYQA)

### 💻 Code
```ts
type Polygon = string[][] | string[][][];

const p1: Polygon = [['1','1'], ['2','2'], ['3','1'], ['1','1']];
const p2: Polygon = [[['1','1'], ['2','2'], ['3','1'], ['1','1']], [['2','2'],['2.4','2.4'],['3.1']]];

p1.every(console.log); // it works. No complains.
p2.every(console.log); // it works. No complains.

const fn = (polygon: Polygon): void => {
  // .every complains with "this expression is not callable"
  if (polygon.every((p) => p.length === 2)) {
    //
  }
};
```

### 🙁 Actual behavior

TS throws an error.

### 🙂 Expected behavior

TS should not throw an error.

CC: @emiliosp

**Comment by MartinJohns** [comment]
It's working consistently. Your two variables are not actually typed `Polygon` because the assignment narrows the type. When you add an `as Polygon` behind your assignment it won't narrow and the behavior is the same.

**Comment by emilioSp** [comment]
Yes, I see, but why `.every` is not callable on union type?

**Comment by MartinJohns** [comment]
See #36390 and referenced issues. Or search for `this expression is not callable union`.
