### ISSUE TITLE
--isolatedModules should also ignore .d.tsx files

### ISSUE THREAD

**Issue by sedot42** [microsoft/TypeScript#52116]
# Suggestion

Hi, as per [documentation](https://www.typescriptlang.org/tsconfig#non-module-files), when `--isolatedModules` is set, TS ignores non-module files ending with `.d.ts`, but not ending with `.d.tsx`. 

> This restriction doesn’t apply to `.d.ts` files.

We are getting errors when trying to use ambient `.d.tsx` files in combination with the `--isolatedModules` option. 

In my opinion it would make sense to also ignore `.d.tsx` files.

## 🔍 Search Terms

isolatedModules .d.tsx ignore non-module files

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

When using `--isolatedModules`, TS should ignore ambient non-module `.d.tsx` files.

## 📃 Motivating Example

React Native enforces use of `--isolatedModules`, but also obviously requires .tsx files. We cannot use ambient declaration files right now because of the incompatibility between `.d.tsx` files and `--isolatedModules`.

**Comment by nmain** [comment]
> also obviously requires .tsx 

That's not obvious.  The difference between `ts` and `tsx` is with parsing of JSX syntax, but there's no way to use JSX syntax in a declaration.  Why are `.d.tsx` needed and what difference do they have from `.d.ts`?

See previous dicussion at https://github.com/microsoft/TypeScript/issues/4415

**Comment by RyanCavanaugh** [comment]
+1 to above comment. `.d.tsx` is just `.tsx` as far as we're concerned -- it's already the case that files with this extension are treated as `.tsx`. There's no need for a `.d.tsx` extension at all.

**Comment by sedot42** [comment]
Huh I _obviously_ didn't check my assumptions properly, thanks for calling me out on that. I was following [some docs](https://github.com/goatandsheep/react-native-dotenv#typescript) for a library we are using that instructs creating a `*.d.tsx` file. Since I'm not familiar with ambient declaration files I thought this is the way it's done.

I can get Typescript to parse my ambient declaration file if I place it in the root folder of my project (same level as tsconfig). However, I am still struggling to configure Typescript to parse the ambient declaration file if it is in e.g. `./src/types/modules.d.ts`. I tried setting `typeRoots` to no avail. But that's another issue, so I'm closing this one. Thanks.
