### ISSUE TITLE
Generic type is not correctly inferred from the function return type when it is a function expression type

### ISSUE THREAD

**Issue by markostanimirovic** [microsoft/TypeScript#52114]
# Bug Report

### 🕗 Version & Regression Information

Tested with different TS v4 versions. It does not seem like a regression.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCCBjGBLCA7AJWABMBXDYKAHgGUYBDGYAPjgF44AKAZwaYC44dRqgA+cUnmLAAZtjwkAlO1bCmAbgBQm0JFhwZkrLjxwMUYCKJkK1NS07zsOegBt7g+4sGYc+a+SUtHwscADemnBRcBYwpFCmYQC+cPTcqXiIWknautDwhnjG+GYWIgBilnEWwSLMnBj4cgDmghHRMSSBUD7FhF22tUzMADSR0dzArsBY0NyCPCGeIcpsrJIA1ngQAO54Y0nKydrmVcCVjPHAnO3RFjaUgqdWA5ScAOTvimMdAPS-CAAFqgAAa8EQghDIVDYdIgzbbPYg8ZRf5wbAyOA7VAWAC2EAAbqDwUxIfQoM1SLjgHh4DBgXBKFBoFjsK5XHBiLD6GAUOSUXBJtNZlB5lwScBVqwbocftE0UKZjA5gspVxkopNIctJo0Wx9XAAOrQDbkiCSYjpfVsbR6g3GqCm5kWuAARn4uoBABFZPIccBqqYkChUul6Nt6ZQ4M0aZRsBhcuB8gYjH5TM8mAFbAAmKjjexyrNR0BMKTpXwmIt2EKsDgV-yvat1TT1JwudxLIQrQRV8IC2LxRIpNIZLJak5lJgXarXW5Re7dJ6T4BV7OcV3ZgDM3wFaMjcDBIUhwZh6UaUAsWFciHReBkTJIXBBeCpACNKJD5EDYWY0pKBYqIpiosIhqjKmraraALWkaJpmi62YemiACi4CuPGzjXnAYBpHC9iQjGChQPGCAQAeGYro2kKFH0E5nNOVw3P2jZLmcVZUC+uLvlA9SujufwAvuh4QlCIY-uel4wFh8j3hej6cM+b4fre35nn+modIByqigsEpgRqByKDqdocA6TrmlIcCbkhAKoWA6EYJhN6THSDLCaSonAHRFRVIxc6dA8PSlGxjbrvxExTEqKrip2nHcfpspakZUHsPacHOpZAAsNlwAAwsuAXdHA5rwBAmIghRDEWNRqYmCc+C8IVtjsMFLyBZwMBQKQko6pVvkWExHQLrYcqooJbkSse0Lome0CSdJd4PsQT6vhAEDTOGn5BoC4nqQBkVAbpKwqOqhxJVoQA)

### 💻 Code

```ts
// === Reproduction ===

export type ActionReducer<State> = (state: State | undefined) => State;

export function createReducer<State>(initialState: State): ActionReducer<State> {
    return {} as any;
}

export function createFeature<State>(config: {
    reducer: ActionReducer<State>,
    selectors: (state: State) => unknown,
}) {}

createFeature({
    reducer: createReducer(''),
    // the `state` type is `unknown`
    // if we remove `state` argument the error will disappear
    selectors: (state) => ({}),
    // selectors: () => ({})
});

// === Workarounds ===

// === Workaround 1:
// Define return type as another generic

export function createReducer2<
  State,
  Reducer extends ActionReducer<State> = ActionReducer<State>
>(initialState: State): Reducer {
    return {} as any;
}

createFeature({
    reducer: createReducer2(123),
    // the `state` type is correctly inferred (`number` in this case)
    selectors: (state) => ({})
});
```

More workarounds are available at the playground link.

### 🙁 Actual behavior

A generic type is not correctly inferred from the function return type when it is a function expression type.

By the way, I noticed that the `State` type will be correctly inferred when the `ActionReducer` from the example above is not defined as a function expression type:

```ts
// `ActionReducer` is not a function type anymore
export type ActionReducer<T> = T | undefined;

export function createReducer<T>(initialState: T): T {
    return {} as any;
}

export function createFeature<State>(config: {
    reducer: ActionReducer<State>,
    selectors: (state: State) => unknown,
}) {}

createFeature({
    reducer: createReducer(''),
    // the `state` type is correctly inferred
    selectors: (state) => ({}),
});
```

### 🙂 Expected behavior

I'd expect the same behavior when `ActionReducer` is typed as a function expression.

**Comment by Nut41tank** [comment]
+1

**Comment by RyanCavanaugh** [comment]
See #47599

**Comment by markostanimirovic** [comment]
closing as duplicate
