### ISSUE TITLE
Parent classes ignore the signature of overridden methods

### ISSUE THREAD

**Issue by jf-paradis** [microsoft/TypeScript#52113]
# Bug Report

When a subclass overrides a method called by its parent class, the signature of the overridden method is ignored by the parent class. This is also the case with static classes.

In our example:
- A function, `type`, returns a constructor, `X`. 
- Another method, `make`, invokes it and returns a constructed object, `new X`.
- A subclass overrides the first function, `type`,  and returns a different constructor, `Y`.
- At runtime, calling the method `make` will create an instance of that second constructor, a `new Y`.
- Typescript reports that the instance type should still be `X`.

### 🔎 Search Terms

subclass overrides static method called parent class

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about override

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=5.0.0-dev.20230104#code/MYGwhgzhAEAa0G8C+AoUkYE1oFMAeALjgHYAmM8yKa4U0AgoitNALZgDWOAFAJRMsWwAPbEIBaCLEEATgFdgBYTOgBeaAQAWASwgA6AgE8ADj14BuZoJk4CcmcWjEcAd0mjx8xcr5XUVo1M+AWtbe0dYSxZUf3Q6ACFcQhJyBhDAsxCWGzsHaEwo6BjqKXFoMDUnVwY+PXYuPnNoAHpmjRMcaGEAM3LoXTg0DwkAI0rnN3ja+rMm1vbTLt6xgfgAHlV1bWIRGRtFEo9hEBw9EGEAc24wPVLZBSUZPWIwVhwLFrbhOQJjH5gAESwAFDMTHU7nK4jW7DLyPZ6vd5zL4-P4EQGYAFAA)

[Playground link with relevant code (static)](https://www.typescriptlang.org/play?jsx=0&ts=5.0.0-dev.20230104#code/MYGwhgzhAEAa0G8C+AoUkYE1oFMAeALjgHYAmM8yKa4U0AgoitNBAWAQJbDQC2YAaxwAKAJRMWLYAHtibaDLkEATgFdgBacugBeaAQAWnCADoCATwAOI0QG5mk5TgKrlxaMRwB3BbLZqNLTEHVAc2Dm59KxsJR2dXd1h7FlRQ9DoAIVxCEnIGWPCuHgtrMViWJxc3aExk6FTqRXkwXQYTfiExW2gAeh6o62hpADNoFuM4ND8CaAAjVoz2wRtuvoGcIdH5ifgAHh09TmIZZScNRr9pEBwTEGkAc2EwEyaVdU1lE2IwXhw7Xv60lUBEswJgACJYOCpnIrjc7o9Zi9pgEPl8fn9VoDgaCCBDMOCgA)

### 💻 Code

```ts
class X {}
class Y extends X {}

class A {
  static make() {
    const constructor = this.type();
    return new constructor()
  }

  static type() {
    return X;
  }
}

class B extends A {
  static type() {
    return Y;
  }
}

const a = A.make(); // type of a is X
const b = B.make(); // type of b is X <== incorrect

console.log(a.constructor.name); // outputs "X"
console.log(b.constructor.name); // outputs "Y"
```

### 🙁 Actual behavior

The type set by the overridden function is lost. 

### 🙂 Expected behavior

Same as JS, the overridden function sets the type.

**Comment by RyanCavanaugh** [comment]
See #5863
