### ISSUE TITLE
Support async/await in ES5

### ISSUE THREAD

**Issue by unicomp21** [Microsoft/TypeScript#5211]
Please support es5, like Google dart async/await in the browser.

**Comment by DanielRosenwasser** [comment]
Do you mean `async`/`await` for ES5, or do you mean ES5 in general?

**Comment by unicomp21** [comment]
For es5, typescript async/await which transpiles to existing es5.

**Comment by kitsonk** [comment]
The status of this is well covered on #1664.  This is a dupe.

**Comment by sheerun** [comment]
This will be implemented in #1564

**Comment by sheerun** [comment]
Implementation of this feature has been declined as mentioned in #3975 and #10307

**Comment by DickvdBrink** [comment]
What do you mean with declined?
https://github.com/Microsoft/TypeScript/pull/9175 says it is implemented and it is still on the [Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap)

**Comment by sheerun** [comment]
Indeed, I was confused by this chain of issues. You might also look at #11725
