### ISSUE TITLE
Property from Destructured Conditional Object not Correctly Matched to Mutually Exclusive Types

### ISSUE THREAD

**Issue by chezwicker** [microsoft/TypeScript#52126]
# Bug Report

I have defined mutually exclusive column data types (used to rendering dynamic cells in Angular):

```ts
interface ColumnDataBase {
  id: string
  action?: string
  link?: Array<string> | string
}

interface ColumnDataWithAction extends ColumnDataBase {
  action: string
  link?: never
}

interface ColumnDataLinked extends ColumnDataBase {
  action?: never
  link: Array<string> | string
}

interface ColumnDataInert extends ColumnDataBase {
  action?: never
  link?: never
}

export type ColumnData = ColumnDataInert | ColumnDataWithAction | ColumnDataLinked
```

I also have an interface each column implements which defines a transformation from row data to renderer input data:

```ts
export interface Column<ROW, DATA> {
  transform: (value: ROW) => { data?: DATA }
}
```

When I try to conditionally get one of these types, the compiler complains. Is there another way to accomplish what I want, am I simply missing something or is this a bug?

```ts
const column: Column<{ id: string, kind: "A" | "B" }, ColumnData> = {
  transform: (item) => ({
    data: {
      id: item.id,
      ...(item.kind === "A" ? { link: [ item.id ] } : {}),
    },
  }),
}
```

![image](https://user-images.githubusercontent.com/10724464/210990336-2647bbe3-732d-481b-ba2f-313d2e091fda.png)

### 🔎 Search Terms

mutually exclusive destructure

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.3 according to a quick test in the playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/FASwdgLgpgTgZgQwMZQAQGED2AbArgWzABEEIEAhBAZzQG9hVUQATALlSohnAHMHVkEEJjAB+dp25g+jbOADW41AEEYMBAE8APJN4A+VAB8OXXsAC+wUJFiIUGHAWKkEAdRAQAFsqRCRqKAAPaDBmKgc8QhIyShpUekZBYTAJU2l+OTBFdjAoADdYCytwaHhkNCxI5zIAGQUoZgDgqFDwyqdoimo6fiSRJVyCmAyFdlV1bV1pA2MpvktrUrsKxyiXAElcmAgmkLCIjpdYnsTfZIH8wtkFC6Gi4CCAB0xt1AgNR5WqztQAXgO1mRNrAdsZ2oC3B5vGd-GDVtUEHUsg0rEgRJxUGiquxwWAtLQmGwTFIeAAaVDycBEgBEympRlQ1PI9PM5NxnQM-wSb3UYCocBe+HYAAoPFB8ABKP4GYXcxjMFzsOWMQnsMX4AB0LFJ-BVqA1BtF0E1lNCf1+-1p9NE8VQmXk7AA2kxjVrGgBdVDmVBK8wSnV61n8P06yxPF47Eq2coAvEAJQA8q5yURlAAVZQGblcBB8gUwIWoYV5BB4KDsROuKW-LOoBVkJSpjNeopAA)

### 💻 Code

Posted above in the overview

### 🙁 Actual behavior

There's an error shown which seems to stem from ignoring the mutual exclusivity of the conditional destructured object types

### 🙂 Expected behavior

There should not be an error

**Comment by RyanCavanaugh** [comment]
From the checker's perspective, this is a correct error when you don't have `exactOptionalPropertyTypes` on, because the type produced by the spread is `{ link?: string[] }`, which might inhabited by the object `{ link: undefined }`, which (once spreaded into the parent object) is correctly not any of `ColumnData`'s constituents.

Unfortunately it's not practical to produce the union `{ id: string, link: string[] } | { id: string }` from the parent object because this is combinatorially-explosive (it's `2^N` on the number of possibly-present properties) in a way that actually occurs in real life.
