### ISSUE TITLE
"Expression produces a union type that is too complex to represent." but ONLY if there's exactly 1 required prop in otherwise all optional props- in a union of a certain size.

### ISSUE THREAD

**Issue by nemosmithasf** [microsoft/TypeScript#52130]
# Description
For the below code, you will get the `too complex to represent...` error if theres *ONLY ONE* required `map` property in the otherwise all optional props. 
- If it's all "optional", it's fine. 
- If there are two "required" props, it's fine.

This seems to require a union of a certain length to trigger.

Seems to occur in all versions of TS, including latest

[Playground Link](https://www.typescriptlang.org/play?#code/FAUwHgDg9gTgLgAjgTwiBBVAdgSylgFSgEks4QYBnEAYzjywH0CAeDAPgQF4EAKDBOHJYAJpQQBDLMgQB+PgGsAXJgCU3TgDcoOEQhVYQmiuqEhR43soQ4sAMwoJi6rlp0jgCOU8-6Eh4xgAbmBgFDRJShE7bkxcfCJScipaenxmFl8AHwQAb18vAHpChABZCQV0OAALHHEoCDSsCQAbJCgEGBAAWyhjQRgYWAKvBG6JCBV80ZmEOwBGKFkphEooeZV5hABfENmdvdHt7LyR4oQAeQAlMYqq2vEAKi6ARwBXHC6RR-bOnr70BQhjARl5xhBlqd9l4AEYAJhgKzWcMhW12oIOI2OXhy01m4MheP2dgAzEskWTUZj9uiZtiELiMQSphjYQBWRF5VZw8kINGHOkCnYnImjZlQ6F2ABsvNyq0pm2ps1pRxFTImhNZCBhAHZOXK1tVFSrBVi1ftxaKZnYAByy1Y6Y1Crwm4U4iUzS1amEATn1DqwlCdGNd9MZFo1LOhc0W9rWlCNfKVprp5vxkY9sxhEnm-vjIiprpdQrDmbBGatozsUCgKKRdhEUGDNJLac9Fa1LQkeYbvP5Idb7srXuj1agACtCasKE2k0Xk26GWXbhCo9Ds+Oe2tm8rB0vhx3RxO443C86F6WD6vl7Duy0kdu5+fQ22xYfJTXJ-XZ-2W2ah+q16VreMCJga1ZngOZrsEEQA)

```
export type UnionToIntersection_T<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;

type asdf = UnionToIntersection_T<
  | {
    // Make this optional to remove error
      map: {
        f1o?: { so1: 1 };
      };
    }
  | {
    // OR make this *required* to remove error
      map?: {
        b2r: { so2?: 1 };
      };
    }
  | {
      map?: {
        f3o?: { s3o?: 1 };
      };
    }
  | {
      map?: {
        b5r: { s2o?: 1 };
      };
    }
  | {
      map?: {
        f6o?: { s3o?: 1 };
      };
    }
  | {
      map?: {
        b7r: { soh: 1 };
      };
    }
  | {
      map?: {
        f8o?: { soi: 1 };
      };
    }
  | {
      map?: {
        b9r: { sons: 1 };
      };
    }
  | {
      map?: {
        f1oo?: { sosh: 1 };
      };
    }
  | {
      map?: {
        ba1r: { sosd?: 1 };
      };
    }
  | {
      map?: {
        foo2?: { sfdo: 1 };
      };
    }
  | {
      map?: {
        lar: { sfdo?: 1 };
      };
    }
  | {
      map?: {
        fooj?: { sero: 1 };
      };
    }
  | {
      map?: {
        bajr: { sfso: 1 };
      };
    }
  | {
      map?: {
        fojo?: { sdo?: 1 };
      };
    }
  | {
      map?: {
        barl: { sso: 1 };
      };
    }
  | {
      map?: {
        fooj?: { sfo: 1 };
      };
    }
  | {
      map?: {
        barh: { sfo?: 1 };
      };
    }
>;
```

# Workaround
You have to separate the "optional" and the "required" keys and "unionToIntersection" them as two groups, and then combine them together with an intersect. You also have to remove all `undefined` values from the "optional group", because you can't access paths where there's a potentially `undefined` value (e.g. `type A = {foo: 1} | undefined` means `A['foo']` returns `any`)
- e.g. `deeplyRemoveUndefined<unionToIntersect<onlyOptional<>>> & unionToIntersect<onlyRequired<>>`

**Comment by MartinJohns** [comment]
FYI, perhaps you should provide an example without `UnionToIntersection`.

https://github.com/microsoft/TypeScript/issues/43077#issuecomment-790758767

> We don't really support uses of `UnionToIntersection`; this operation is ill-defined.

**Comment by RyanCavanaugh** [comment]
If someone finds a fix for this they can send a PR, but this error message having a boundary isn't unexpected.
