### ISSUE TITLE
calling new on a class expression fails to wrap the expression in `()`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5214]
The following ts generates invalid js: 

```ts
let foo = new class {
    count = 0;
};

console.log(foo.count); // Expected 0, but got `undefined`
```

Generated JS: 

```js
var foo = new (function () {
    function class_1() {
        this.count = 0;
    }
    return class_1;
})();
console.log(foo.count); // Expected 0, but got `undefined`
```

Expected JS: 

```js
var foo = new ((function () {
    function class_1() {
        this.count = 0;
    }
    return class_1;
})());
console.log(foo.count); // Expected 0, but got `undefined`
```

# More 
The following TS [should work](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=let%20%7Bcalled%7D%20%3D%20new%20class%20%7B%0D%0A%20%20%20%20count%20%3D%200%3B%0D%0A%20%20%20%20called%20%3D%20()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20this.count%2B%2B%3B%0D%0A%20%20%20%20%20%20%20%20console.log(%60Called%20%3A%20%24%7Bthis.count%7D%60)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%3B%0D%0A%0D%0Acalled()%3B%20%2F%2F%20Called%201%0D%0Acalled()%3B%20%2F%2F%20Called%202) : 

```ts
let {called} = new class {
    count = 0;
    called = () => {
        this.count++;
        console.log(`Called : ${this.count}`);
    }
};

called(); // Called 1
called(); // Called 2
```

But doesn't because the js is invalid

Note: `this` is wrong as well ... but I have the issue : https://github.com/Microsoft/TypeScript/issues/5213 for that :rose:

**Comment by DanielRosenwasser** [comment]
Thanks @basarat, this is a dupe of #4630 though.
