### ISSUE TITLE
Generic return type seems to be inferred correctly but report an error

### ISSUE THREAD

**Issue by idoros** [microsoft/TypeScript#52147]
# Bug Report

### 🔎 Search Terms

- "does not exist on type", "error on correct inference"

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Generics".
There is a change between 4.7.4 and 4.8.4, but both produce different errors.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABHAbgUwE4ZgEzQSQFsAHAGwB4AVAPgAoBDYmALkUoBpl0tc0AxMKwZNWlAJSIAvNTZjRiAN4AoRKsQY0UEBiSpM2PAOEwxAbiUBfJUogIAzlEQAjenbQBBJlMUq19WhLKasHqmtpIAOT0Eb6qFuyxzgE+IWoaWjqIEU4xwVZWSno8eERktC5unjCctAD6EtIpaWGZQamI-oGJ7aEZSLUAdJ2IANRZAIwR5j3x3WpOyW09qunhiFAAFjB2Q8lj2VNzcYkW5hZmQA)

### 💻 Code

```ts
function overrideImpl<T>(api: T, overrideFn: (api: T) => T): T {
    return overrideFn(api);
}

const baseApi = {
    a() {
        return 'a'
    },
    b() {
        return 'b'
    }
}

overrideImpl(baseApi, (_) => {
    return {
        a() {
            return _.a() + '1';
        },
        b() {
            return this.a() + 'b'; /* Property 'a' does not exist on type '{}'.(2339) */
        }
    };
});
```

### 🙁 Actual behavior

Typescript seems to infer the type of `this` correctly, with both `this` and `a()` showing correct type information on hover, but report an error that property `a` does not exist on type `{}`.

![image](https://user-images.githubusercontent.com/574751/211215059-11cd5127-3ab1-47af-a691-831e96ac3271.png)

Prior to version 4.8.4, in 4.7.4, the error is not on the `a()`, but on the `this`, reporting: `Object is of type 'unknown'.(2571)`, while showing the correct type:
![image](https://user-images.githubusercontent.com/574751/211215041-d8e11d20-0dcd-47a1-9155-d505205b66c7.png)

### 🙂 Expected behavior

Not to error on types that seems to be inferred correctly

**Comment by RyanCavanaugh** [comment]
The `this` inference was previously wrong here, since the `overrideImpl` definition doesn't actually say what `this` will be. The language service can sometimes see the wrong `this` because it doesn't always go high enough up the tree (99.9% of the time, this doesn't matter)

You can write the function this way to get the desired behavior:
```ts
type MappedWithThis<T> = {
    [K in keyof T]: T[K] extends (...args: infer A) => infer R ? (this: T, ...rest: A) => R : T[K];
}
function overrideImpl<T>(api: T, overrideFn: (api: T) => MappedWithThis<T>): T {
    return overrideFn(api) as any;
}
```
