### ISSUE TITLE
Regression in distributed conditional types from 4.7 onward

### ISSUE THREAD

**Issue by kevinlul** [microsoft/TypeScript#52152]
# Bug Report

### 🔎 Search Terms

"distributed conditional types"

### 🕗 Version & Regression Information

- This changed between versions 4.6 and 4.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/JYWwDg9gTgLgBAbzgUQG4FMB2NkmDGdKOAXzgDMoIQ4ByTCAE3QC50NsBnWgbgCg+AekFwAyqDAAbYOWDpGFKjUbBOAY2iMAdACtOcABYEwnFsIDm+AwFcARlo0hBK9Zr3PVGqNr1xparAC4AEEwAEM1A3Q4ACYtAAY+YGwicgjogGFpLBwOGH0EPjg4AHcwqEwWOABtEHROTjDzVjhOGChk8wBdfmLOA3LGABFPCExMdDUYKuq1SQhOdDQcqqyFpbyAGlaB7wBJRirMaxBbIh6+EgE5sIa4ACFb9Cy5bDh0AA9CTEZ9ZexcPhCMRCsUwHZ-HANJg2lBrFNoAAKACUiCKxVa1jARBRvVI-CufBgAE9sSEyvgwrZJOgADwAFQAfHAALxwAAKSlU6AAMsAANZ0plwAA+cHp-D4zBuUGiNzuLxy7y+WF+DyeireoLg4OpwDUcDGtIA0srvmrBcSIOQ4JrcjlOIzEewVnBjdtpG0sEQqoitP7yuZTLbsgC8pxqsauqiWczghSYFSabTUBBgIxGciqjADKo8brIUbRGbVfpYZ1Ra1iacIJInejii7sFVkB85tZmLTRNtLdaQ697VxGZsG35VN8fXA-QGoEGqmFMMTqtHWXGE0m6an08P0Vm4Dm85cBMI4EN0CAxrCwjBgBgoUx0HxoW04LYIPA2RMSv2crihCIACV0BgawKlaRNCDqbAtDgAAxMJgEkfQYAge9wEQ9BtgPTB+WQgZ4CbeBVDgMI4GsTBgDGfdSWiPswkkSQKGAKAX0DE4HSnctMHMSs1kWf4YGRbZbGseADAgDAOm4w1JLgAADQi5J2CASn0HRrBfPiNhyLQ+DfGAtDGREACJ+kGEZXHGSYYGM7ZnS2HZBhjZln1rdAtHmcxETk0RdgUAASBAzO8MgXGhCYpnkKdAsIhwHxITYYryLQyk4LJ0AXEg9ySnTZVuMYSDk5FkX4E8ADl3xIuBZRAsC2mvc8dNtagwAwzhdP0wzMBM4LhlGKyplsqdCO2XrnLRYpXJpDyIC8ny-LgQLetC-qIsIBRERy6CNGYBKtoM1L0sy7KEFivLOAKoqCRK-84CA2rMHAhqoIM5r0Jpdq9PfLqer8izwusobCNXe8YTcma5v2uLdsW07ksOmlMths6MouzBCuKvggA)

### 💻 Code

```ts
import { EventEmitter } from 'node:events';

// Simplified from discord.js https://github.com/discordjs/discord.js licence Apache 2.0
interface ClientEvents {
  warn: [message: string];
  shardDisconnect: [closeEvent: CloseEvent, shardId: number];
}

class BaseClient extends EventEmitter {
  public constructor() {
    super();
  };
}

type Awaitable<T> = PromiseLike<T> | T;

declare class Client extends BaseClient {
  public on<K extends keyof ClientEvents>(event: K, listener: (...args: ClientEvents[K]) => Awaitable<void>): this;
  public on<S extends string | symbol>(
    event: Exclude<S, keyof ClientEvents>,
    listener: (...args: any[]) => Awaitable<void>,
  ): this;
}

// Demonstrative code
const bot = new Client();
// Return statement. Fails to compile, thinks that event is a union type of all first arguments (string | CloseEvent), but hovering over `event` shows just CloseEvent.
bot.on("shardDisconnect", (event, shard) => console.log(`Shard ${shard} disconnected (${event.code},${event.wasClean}): ${event.reason}`));
// Not a return statement. Compiles.
bot.on("shardDisconnect", (event, shard) => {
  console.log(`Shard ${shard} disconnected (${event.code},${event.wasClean}): ${event.reason}`);
});
// Return statement. Compiles.
bot.on("shardDisconnect", event => console.log(`${event.code} ${event.wasClean} ${event.reason}`))
```

### 🙁 Actual behavior

The indicated line fails to compile in TypeScript 4.7, 4.8, and 4.9, when it had compiled in TypeScript 4.6. Making the log statement not a return statement with curly braces, explictly typing `event: CloseEvent`, or dropping the second argument to the lambda function fixes the issue.

### 🙂 Expected behavior

All statements should compile.

**Comment by Andarist** [comment]
More minimal repro case: [TS playground](https://www.typescriptlang.org/play?ts=4.9.4#code/PTAEGUEsFsAcBtIDNIFMAmokCcD21R1IBnAY123QDoArY0ACwBcnZiAuEAc0iYYFcARlXLRgRMhXR1xJcpVr1EpVADsVoAIKwAhqQapQAJioAGAFCRVTVNiR7DAYURqmAUQBur+gG9zoUAB3HWxVdlAAbWhUYmIdLlRw4iZsKy4AXQBuf1BiBhD0ABE5XFVVVFImcIjSeFxiVE9XcOd6xq9rABpc-MoASXRw1X5oQVss8wBfc3N0CvgQw1qdWNBnNGtQPwDYIWVQUoAeAGlQVAAPG1V0egBrVABPXCQ1l2sm62IAPgAKVA6qqBjt1EMk1LZwj8qNCQlwOK8Nu4AcQIsd0gBKUAAXi+oA8uEg6HR4XxhOy03MIFAhVQ0FKyWwOiYkC8oHIc3M5FUyVAglwTGxoHKgQRrh+6OyVKYgVwhHmi0wukZ0GI5j5TCopR+ACI8gVipIyhUmNrun8Ad09ZRMTi2fTcPBUFQ6lwfgADcC9TAAEh8VvQk0IJSNlQwoB+vv+rhEuDmk06kYBVGCxGcqB0qkmxNAiej2HTxFKkzd6IllLAxDSjrly3zipCOmgav5mtUOv9Bq55UqprOAOxuK5hcdztwrrduesMbjOZ8UanKbTGcDk41+ZWRZL6PMQA)

**Comment by RyanCavanaugh** [comment]
For the bot
```ts repro
// Simplified from discord.js https://github.com/discordjs/discord.js licence Apache 2.0
interface ClientEvents {
  warn: [message: string];
  shardDisconnect: [closeEvent: CloseEvent, shardId: number];
}

declare class Client {
  public on<K extends keyof ClientEvents>(event: K, listener: (...args: ClientEvents[K]) => void): void;
}

// Demonstrative code
const bot = new Client();
// two declared params
bot.on("shardDisconnect", (event, shard) => console.log(`Shard ${shard} disconnected (${event.code},${event.wasClean}): ${event.reason}`));
// single declared param
bot.on("shardDisconnect", event => console.log(`${event.code} ${event.wasClean} ${event.reason}`))
```
