### ISSUE TITLE
Regression: class implementing `File` errors with "missing property 'prototype'"

### ISSUE THREAD

**Issue by pcattori** [microsoft/TypeScript#52166]
# Bug Report

Original issue in the Remix repo: https://github.com/remix-run/remix/issues/4371

<img width="1380" alt="Screen Shot 2023-01-09 at 11 28 39 AM" src="https://user-images.githubusercontent.com/1477317/211358013-0d6254cd-9038-4e1e-99b9-0768f20826f2.png">

### 🔎 Search Terms

lib.dom.d.ts, File, Blob, interface, declare var, implements, prototype

### 🕗 Version & Regression Information

This changed between TS 4.8.4 and TS 4.9.3. Typechecking passed in 4.8.4, fails in 4.9.3+

### ⏯ Playground Link

Hard to reproduce in a playground because the issue only occurs when the class type definition is within `node_modules/`.

Playground shows no errors 🤷: https://www.typescriptlang.org/play?ssl=18&ssc=2&pln=1&pc=1#code/KYDwDg9gTgLgBAE2AYwDYEMrDm9BnPOAOQiQHkA7AEQEs8BrAMRtWxoFsxX3gKZDmrOAG8AUHAlwwUGgDd0MbADMWwMAoAWAbnGSYATzDAAXHDwwZFAOY7JUmfMVnUNZMCgB+W5Iroep80sbXQkMcwBZUhoVYARTCgBXdgAjd28JAHdgZPoaGAAlYAwYOWAABU0AixprdJwICkCE5BhoAAoVVnUYDSqggBo4AyM+mqtBvBc3T1MxOztzTBh4pNSoOrteOLhElLSQuABfOAAfOASKJBUKWIBKOqtgeDwaAC9gNtuVvfWDydcPotYB5vmtBlsQTtVu5BsNgJDAmMvnAAEKoCDJOqYKDofQohJKJTuT6mMpQCDsOjAAA8AEEoDi8QSiVAAHx1QLAPwkuCFdAIdDJVgAZQsXPY1PQFH07IOihAMB5ZIpVOpiOssrsj3gAG1hfoUhBUAA6VqioIAFXQVgAujz1cFDqIgA

### 💻 Code

To reproduce:

1. `npx create-remix@latest`
2. Pick **Just the basics**, **Remix App Server**, **Typescript**
3. `cd` into project and run `npm install` if you skipped that in step (2)
4. `npm run typecheck`

### 🙁 Actual behavior

```sh
❯ npm run typecheck

> typecheck
> tsc -b

node_modules/@remix-run/node/dist/upload/fileUploadHandler.d.ts:47:22 - error TS2420: Class 'NodeOnDiskFile' incorrectly implements interface 'File'.
  Property 'prototype' is missing in type 'NodeOnDiskFile' but required in type 'File'.

47 export declare class NodeOnDiskFile implements File {
                        ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:2572:5
    2572     prototype: Blob;
             ~~~~~~~~~
    'prototype' is declared here.


Found 1 error.
```

The `prototype: Blob` code occurs within `declare var Blob`, _not_ within `interface Blob`.
From my understanding, it seems like TS is conflating the `Blob` var and interface and that's what's causing this issue.

<img width="2122" alt="Screen Shot 2023-01-09 at 11 30 15 AM" src="https://user-images.githubusercontent.com/1477317/211358303-ade48c2a-2603-459e-abf8-d0c85f7ad246.png">

### 🙂 Expected behavior

Typechecking succeeds

**Comment by MichaelDeBoey** [comment]
As @akomm pointed out in https://github.com/remix-run/remix/issues/4371#issuecomment-1378460377, we do get the error if we include types for _any_ built-in Node modules: https://tsplay.dev/WYeObW

**Comment by MichaelDeBoey** [comment]
@iisaduan @RyanCavanaugh Is there anything we can do to help to get this one fixed?

I'm happy to help out in any way I can

**Comment by akomm** [comment]
This problem would have been spotter early, if remix would actually type check out of the box when building. I don't get why its not, like for example in next. This is why nobody noticed this problem, as you only notice it if you fill the gap of missing typecheck and realize this failure. When you are in dev mode your IDE will only show you the problems in the currently working files. You actually have to manually run typescript. Another issue is that they use some internal version so the dependency of TS you install (and  the remix create adds) is totally de-sync with the actually used. So I had an issue using 5.1 features having ts 5.1 when I realized remix does not use it at all.

**Comment by RyanCavanaugh** [comment]
Something is wrong with the node .d.ts. It's basically saying, TL;DR

```ts
type __Blob = (the type of the global Blob value)
interface Blob extends __Blob { }
```
The implication here is that the *instance type* of `Blob` (`interface Blob`) has the *static-side members* of the value of the global `Blob` constructor. This isn't right. You can't write `new new Blob()`. The downstream impact of that is that when you say `class X implements File`, where `File` extends from `Blob`, that you're declaring that an *instance* of `X` is constructable; that you could say `new new X()` -- but no class works that way.

@iisaduan is investigating the right fix to the node .d.ts
