### ISSUE TITLE
Typescript file imports being appended with `.js` extensions intermittently

### ISSUE THREAD

**Issue by AaronMcCloskey** [microsoft/TypeScript#52167]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.74.2
- OS Version: macOS Monterey 12.6

Steps to Reproduce:

1. Commented out all of my `settings.json` file, so uses the default settings
2. Restart VSCode with Extensions Disabled
3. In certain `.ts` files in my project, when I go to import another `.ts` file the autocomplete option for the import adds a `.js` file extension.
4. The same import made in another `.ts` file in the same directory or another directory, does not append the `.js` file extension.
5. Sometimes in the `.ts` file(s) that appends the `.js` file extension on the auto import, when I remove all of the code and then try to import, it does not append the `.js` extension. But if I close the file and re-open it again, it will. But this is intermittent.
6. See Videos below for issue
  - Sorry, had to split in 2 due to file sizes

https://user-images.githubusercontent.com/20436343/210012132-a6682005-5d22-485b-9e1b-cf617f3ffd1f.mov

https://user-images.githubusercontent.com/20436343/210012161-49604216-5ff5-4ee9-b0f8-de3b83458857.mov

Not sure how much the `tsconfig.json` file can affect this but this is my ts config.

```json
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true /* Report errors on unused locals. */,
    "noUnusedParameters": true /* Report errors on unused parameters. */,
    "allowSyntheticDefaultImports": true /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["next-env.d.ts", "types/**/*.ts", "next-auth.d.ts", "**/*.ts", "**/*.tsx", "**/*.js", "**/*.cjs", "**/*.mjs"],
  "exclude": ["node_modules"]
}
```

**Comment by andrewbranch** [comment]
Can you share the project where this is happening?

**Comment by jespertheend** [comment]
I'm running into an issue that I think has the same root cause. I want .js endings but I'm not getting them, since I'm working exclusively with .js files already.

@andrewbranch You can find my project at https://github.com/rendajs/Renda, it doesn't require a whole lot of work to get it up and running, but you do need to have [Deno installed](https://deno.land/manual@v1.32.1/getting_started/installation) in order for it to automatically download TypeScript 5.0.2. Otherwise I think you might also be able to reproduce this by manually placing the TypeScript package in `./Renda/npm_packages/typescript/5.0.2/`.

**Comment by jespertheend** [comment]
Screen recording with steps to reproduce:

https://user-images.githubusercontent.com/2737650/227790834-8f952c60-05cb-4f87-943b-9b8b79181fbe.mp4

**Comment by jespertheend** [comment]
Seems like adding `"moduleResolution": "bundler"` and `"allowImportingTsExtensions": true` to the jsconfig fixes this issue for me. At least it does for now.

**Comment by Astarosa** [comment]
The Typescript documentation recommand to now use **module** and **moduleResolution** to `NodeNext`. But if you do so it generate the error with `.js` file extension required. 
The solution for me was to set this to `"module": "es2022"` and `"moduleResolution": "Bundler"`

**Comment by bkilrain** [comment]
I noticed this has started happening in the latest version vscode (1.88) despite the settings mentioned in this thread. Downgrading fixed the issue for me. Leaving a note here for others to find...

**Comment by hatealgebra** [comment]
> Seems like adding `"moduleResolution": "bundler"` and `"allowImportingTsExtensions": true` to the jsconfig fixes this issue for me. At least it does for now.

Hi, the `"allowImportingTsExtensions": true` did the trick for me.  Thanks a lot!

**Comment by bkilrain** [comment]
Coming back here because after upgrading to vscode 1.92, this behavior returned and I didn't want to stay stuck on 1.88 forever. I eventually figured out the `.js` extensions were being added because of an `imports` field in my `package.json`. When I removed that, auto import worked as expected. Example snippet:
```
"imports": {
    "#*": "./*"
  },
```

**Comment by theoludwig** [comment]
> Coming back here because after upgrading to vscode 1.92, this behavior returned and I didn't want to stay stuck on 1.88 forever. I eventually figured out the `.js` extensions were being added because of an `imports` field in my `package.json`. When I removed that, auto import worked as expected. Example snippet:
> 
> ```
> "imports": {
>     "#*": "./*"
>   },
> ```

Indeed, without `"imports"` in `package.json`, it auto impot correctly with `.ts` as expected. But this looks like a bug to me, it should also work with the `"imports"` field in `package.json`.
I've created an issue for this bug: https://github.com/microsoft/TypeScript/issues/59553
