### ISSUE TITLE
Type parameter on ts.some/ts.find is too narrow when called on union of arrays, works with explicit instantiation

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#52179]
This is a follow-up to #52111 and #52123.

In the below code, `every` works as expected, which is new as of #52123. However, the `some` function can't be called on the array type at all, even though reasonably there's a top type which works (`A`), just like it works for `every`.

```ts
interface A           { a: string; }
interface B extends A { b: string; }
interface C extends A { c: string; }

declare function isC(x: A): x is C;

declare function every<T, U extends T>(array: readonly T[], callback: (element: T, index: number) => element is U): array is readonly U[];
declare function every<T, U extends T>(array: readonly T[] | undefined, callback: (element: T, index: number) => element is U): array is readonly U[] | undefined;
declare function every<T>(array: readonly T[] | undefined, callback: (element: T, index: number) => boolean): boolean;

declare function some<T>(array: readonly T[] | undefined): array is readonly T[];
declare function some<T>(array: readonly T[] | undefined, predicate: (value: T) => boolean): boolean;

function foo(array: readonly B[] | readonly C[] | undefined) {
    if (every(array, isC)) {
        array;
        // ^?
    }

    if (some(array)) {
        array;
        // ^?
    }

    if (some(array, isC)) {
        array;
        // ^?
    }
    
    if (some<A>(array)) {
        array;
        // ^?
    }

    if (some<A>(array, isC)) {
        array;
        // ^?
    }
}

```

<details><summary><b>Output</b></summary>

```ts
"use strict";
function foo(array) {
    if (every(array, isC)) {
        array;
        // ^?
    }
    if (some(array)) {
        array;
        // ^?
    }
    if (some(array, isC)) {
        array;
        // ^?
    }
    if (some(array)) {
        array;
        // ^?
    }
    if (some(array, isC)) {
        array;
        // ^?
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230109#code/JYOwLgpgTgZghgYwgAgILI5ryDey4BcyAzmFKAOYDcyAvgFCiSyIoBCyEAHpCACbE0uZACMipciGp1G4aPCTIAwpx4R+g9HgTiylGg3p8ICADZwoKGAFcQCMMAD2IZMGJKAFFyKoAlES5XQSUqeiMTc0tkGzsHZ04AN2gATwAeABUAGmQAVVVeAWR0gD4PCyg4ZKJLOD5nU2SigG0AXWyEOFNTEUQAayIPCFMIAFt1MCIs135uIhBrEZFoX2QAXmLOYbHwINz-fCgKxrdkGrqQBtzW0OMzCytbeycXCCSoNKm87gLBErLDyrVCC1eqNdKtZAAH2QtmMMFAED47U63T6AyGo3Gk2yoGM3mQ80WyzWGwx2zAuxy+3KlV2Z1BVxaUJhM3hIERNwi92ijziLzeH1KNKqp2B50u4KZ0NhEDZiORXR6CH6yEGWyxRRxM3xhKWUBW61EjkcwzgIH2ImNppAoXCdyiMSe8WIjjGGSFAJF9IuYIh0tZCL41M9dLFDMlnPtD1izxIrog7v+RyBIJ9zSlLLhgeyAAdLHxgB1IAMEp1rBBJgaNpaTcDzUQa9bbY6+dFjUnAaLU5c2H6u+LGko+zK5UHcPQsMAYKrXikO8kce5fCscBPsBhhaF1xgAPQ75AAPQA-GuMIZJ9OPC6xvPl+Ptwcjlvt3vDyesOfMFPVdeIPPF0od6rg+m6ntgr7HmBDBYGB35XvGqSoB6RxAWBWCgQ+EHvpgn4YHBv6IchlQAahIGes+65YVB9AMEAA)

**Comment by jakebailey** [comment]
I will say that the first overload to `some` could be:

```ts
export function some(array: readonly unknown[] | undefined): array is readonly unknown[];
```

And function the same way (proving the array isn't undefined), but the callback case is the one that errors in the SFT branch.

**Comment by jakebailey** [comment]
This is another case on the SFT branch: [Playground Link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230109#code/KYOwrgtgBAygniALgQwB4GkCWIAmUDeAUFCVAEIA2A9gMYDWANMaQJI6iKYBmmwATk1JQAwsgDOwYRWRgJg0gDEwIGpyogAoqgAOfYGLGZ18kkpVqQAEWA1pfZBaYBfQoWyJ+XZDWBQAclTsBFB02DgAXLAIKBhhANxQLu6e3r5auvqG6lDAqB64Yv6BvvhQAPq5GQZGIGT2uJHIIHAJSUgpPlDWtsj2Fjl5oDiFAUGlZew9fTV1TRFQTS2Jbu18Xp2UtHQD+cNFYyFhkfBIaFi4AHSb9K2uk3a+XMqqNVA8uAA8ACoMUACqOyGhS+AD4ABS9exwSJ6ZA4dQUOBQL4AbQAulAAD5QZTsd7AHC-DI4TA0BzASJg4AUYAQDiRH5QMK5SLgCAAI34AEooABeEE5Gl0pBMwp-X5iFB8RAsXC5AD8rMgnL4XMiAOxuOA+JwcUI916j2e-XeOG+4MhyGhUFh8JAiOR6KxOLlOqJehJZI8lOptPpyN+zNQSo53L5AvZVCoNKaEqlMrlqEVUDZKrVyOdWp1esIT3Mry4UYhfChMOAcIRSO6dgcNSd2NtlfI1Ho9ZdeOwBJ5RCENHUkoWfLeYWLUN+YJAxR5-KgiD4YGAXL1QgA9CuhAA9eWuZgkPsgAfsoemj7V3q17LY650C0lq3jyfsacCucLpe7qBrzfbj-7gc0Y8wg+UZgFvMcoAnKdw1nedF2XUgv1ILdCBcIA)

```ts
enum SyntaxKind {
    Block,
    Identifier,
    CaseClause,
    FunctionExpression,
    FunctionDeclaration,
}

interface Node { kind: SyntaxKind; }
interface Expression extends Node { _expressionBrand: any; }
interface Declaration extends Node { _declarationBrand: any; }
interface Block extends Node { kind: SyntaxKind.Block; }

declare function find<T, U extends T>(array: readonly T[] | undefined, predicate: (element: T, index: number) => element is U, startIndex?: number): U | undefined;
declare function find<T>(array: readonly T[] | undefined, predicate: (element: T, index: number) => boolean, startIndex?: number): T | undefined;

function foo(array: readonly Declaration[] | readonly Block[] | undefined) {
    const a = find(array, (node) => true); // error!
    //    ^?


    const b = find<Declaration | Block>(array, (node) => true);
    //    ^?

    const c = find<Node>(array, (node) => true);
    //    ^?
}
```

**Comment by jakebailey** [comment]
So, this extends past `ts.some` and more into "array related helpers when passed unions of arrays"; maybe these are the cases that we don't expect to work.

**Comment by jakebailey** [comment]
@ahejlsberg for interest.

**Comment by jakebailey** [comment]
Then there's this...

```ts
// @strict: true

const enum SyntaxKind {
    Modifier,
    Decorator,
}

interface Node {
    kind: SyntaxKind;
}

interface Modifier extends Node { kind: SyntaxKind.Modifier; }
interface Decorator extends Node { kind: SyntaxKind.Decorator; }

declare function isModifier(node: Node): node is Modifier;
declare function isDecorator(node: Node): node is Decorator;

declare function every<T, U extends T>(array: readonly T[], callback: (element: T) => element is U): array is readonly U[];

declare const modifiers: readonly Modifier[] | readonly Decorator[];

function foo() {
    every(modifiers, isModifier); // error? (undesired)
    every(modifiers, isDecorator); // no error (desired)
}
```

[Playground Link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230109#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoHiB7AOxlCyIwFtQBlATyOgEMAPAaXiIBNQBvHUINABZAl3gAzeFlgAaAUIAiWQrCbQCcnAF88naDIlNEWUADkxp-kNABrTlzT1GrDtwDcOvY0PHTo8SkZMhYDbkhzSz47BycGZnYHADoAyWlYd1BdfV8TUGVVdU0QsK4Iiy4rGO44l0TuJILNIoysvErEABsmWFMJDCJkeGJQeEhUoNgACiJLNAqsAEo0WcrRiIn0zw7u3tB+wehhonWmtQ1p1ax5y2XQK-X8lWaLzxwdnr6BoZGsADcZHQADwAFVkoAAqiVyGVQCCAHxTHpqOhoXpMLjETp0OEAbQAuuDEExOp0AEbGWxoKZYTpYSjkVBwxagAC88LIdIZjEeELuyKYOLGoHRmKI2MhBLeHz2hBI0FAlDEaRkkDRWAxWJxmxkBNAAB8RRqxRKzi0pXgDj8ThICAQpizrEJ-oCpkrAulIOCxjrYItPDYXbA6G7lZMvadnudNP6vEA)

**Comment by jakebailey** [comment]
Unbelievably, I figured out what might be a fix for all of these cases... Will send a PR tonight/tomorrow morning.

**Comment by ahejlsberg** [comment]
Regarding the error with `find`:

```ts
function foo(array: readonly Declaration[] | readonly Block[] | undefined) {
    const a = find(array, (node) => true); // error!
    //    ^?
    const b = find<Declaration | Block>(array, (node) => true);
    //    ^?
    const c = find<Node>(array, (node) => true);
    //    ^?
}
```

It's not clear there's anything we can do here. Neither of the co-variant inferences we make for `T` is a supertype of the other, and there are no contra-variant inferences to help us out. The type `readonly Declaration[] | readonly Block[]` clearly indicates that we don't want to mix the two element types and therefore we don't infer `Declaration | Block`. This is a long standing principle that I don't think we want to mess with.

**Comment by jakebailey** [comment]
Yeah, I had found some more examples that already existed in the codebase pre-SFT like this.

I'm going to retest SFT with #52180 as LKG and see how far we get; I'm guessing it will turn out okay.

**Comment by fatcerberus** [comment]
`Array#find` feels like one of those cases like with `include` where you really want to allow bivariant inputs (#36352, #26255) but there's currently no mechanism in the type system to do so. 😿
