### ISSUE TITLE
`@linkcode` and `@linkplain` have no autocompletion

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#52171]
# Bug Report

### 🔎 Search Terms

linkcode autocomplete

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `linkcode`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhFgCgAIWgBANgSyrYQ)

### 💻 Code

```ts
/**
 * @li
 */
```

### 🙁 Actual behavior

It only autocompletes `@link`

### 🙂 Expected behavior

It lists `@linkcode` and `@linkplain` as well.

Admittedly `@linkcode` is required to be in brackets for it to work: `{@linkcode someVar}` but the playground doesn't do any autocompletion in this case. In VSCode it does though, so perhaps this is the wrong place to report this issue.

**Comment by RyanCavanaugh** [comment]
The icon you see next to `link` means it's provided by the hosting editor, not TypeScript.

So the bug here is that the TypeScript Playground editor host only has `link` instead of `linkcode` and `linkplain`, which... I don't really think is a big deal

**Comment by jespertheend** [comment]
Ah yeah makes sense, I don't mind it not being in the playground either. VSCode has the same issue though, I'll open up a new issue there.
