### ISSUE TITLE
Typescript uses any instead of union type for nested records

### ISSUE THREAD

**Issue by hungcs** [microsoft/TypeScript#52187]
# Bug Report
```
type SpecificModelMetrics = {
    [target: string]: {
        [metricName: string]:
            Record<MetricType, number>;
    }
}

// Same as SpecificModelMetrics, but null instead of metric, since we don't display it on the comparison table
type SpecificCompareModelMetrics = {
    [target: string]: {
        [metricName: string]:
            Record<MetricType, null>;
    }
}

```
i would expect TS to reduce `SpecificModelMetrics | SpecificCompareModelMetrics` to
```
type CombinedType = {
    [target: string]: {
        [metricName: string]:
            Record<MetricType, number | null>;
    }
}
```
<img width="820" alt="Screen Shot 2023-01-10 at 12 54 26 PM" src="https://user-images.githubusercontent.com/85463385/211660774-d1e275ac-00e1-4abf-9dbc-a979fdebbe65.png">

instead the map entry is `[string, any]`, requiring me to manually specify the type like `Object.entries(metrics).map((targetEntry: [string, Record<string, Record<MetricType, number | null>>])`

### 🔎 Search Terms

nested records

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAshwCcCWBjAKuaBeKAiRAhkgHYD6AtvMigM65QA+ewENwFVqdjeAbgQBskAEwLAkAezKVEXXAG4AUKEhQAypBRIAZqhgThEAXFm0oOAN6KoNqAG1gBBAHN4ALihtkxZwF0PVrZB9jLUAHIElB5eJH5u1sGJAEoQKBIIwgA8JtQYkAA0UMQAruQARhAIAHxKQQC+ig2KAPTN6pHQBDTqmjp6BkY5XIVlxcBFxQICUCRsEATCUBLaUKGohTQkKNAA7tDCUgDk48JINGACBCAz41JQwAAW0GnkYE5nd45lAhDKmD2pPooADCEleTgg+kMxk4ZksCRsDicrmA0VkPn8UECiRCsIiUU86LiCJxNhSaQy2VheQghRKUxqJIaTTSxDYqxUEA8Q3Q-xw+AQRGksLoSlZ7LWtAATOYsfhkfAAIy4AK4SXKgLkTkeAAsdX1UC6AK0uhQUMGIqUinF4xWOAAFJKaB4NIDTeaYaZukxXSb+tCeTQAJTmKpYkkAeTKACtUsAAHQQYiyViOkVB+PkAhge2OFzwACiyYQ1ywYexOJt9jzKMKNfgADVBMVWL5ZfXgEXECBaqSo7GUAmkymaLmFcAmwIW8HM9m06Yu8hWKHw6SglW7JL8bTVtTMDQ2zhJYukKxe2uoOKJD94wIJM557l9-HCCQOF6g+fgnUg0zf01tEfLgpU-IA
### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

**Comment by RyanCavanaugh** [comment]
The playground link uses ` SpecificModelMetrics | SpecificModelMetrics`, which seems like a typo, and changing it to `SpecificModelMetrics | SpecificCompareModelMetrics` produces `unknown` (and an error), not `any` as described here.

Please file a new issue with a working repro.
