### ISSUE TITLE
Union of 2 arrays leads to generic T=never inference

### ISSUE THREAD

**Issue by TruffeCendree** [microsoft/TypeScript#52186]
# Bug Report
### 🔎 Search Terms

array union never

### 🕗 Version & Regression Information

The bug was already present in typescript 4.0.5 and still occuring on 5.0.0 nightly.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/MYewdgzgLgBAhgJwXAnjAvDA2gcgII4C68EMCApnACbgA2aWARHo8QD5mU1j3aMBCrGAChEyFADoAlmGC0ArlXIQAFPhwBKIA)

### 💻 Code

```ts
const array = ['A'] as ["A"] | ["B"] 
array.includes('A')
```

### 🙁 Actual behavior

The following `includes` signature was infered:
`Array<T>.includes(searchElement: never, fromIndex: number | undefined): boolean`

### 🙂 Expected behavior

The following signature was expected:
`Array<T>.includes(searchElement: 'A' | 'B', fromIndex: number | undefined): boolean`

**Comment by MartinJohns** [comment]
Working as intended. When calling a function on a union you must provide an argument thag Matches with every possible type combination. The one requires A, the other B, so your argument must be A and B which is not possible and results in never.

Actually you'd want #14520.

**Comment by TruffeCendree** [comment]
@MartinJohns Thanks a lot. By reading the literature you pointed, I better understand the situation.

I will close this issue, considering another one already tracks it.
