### ISSUE TITLE
Error in ESM about no extensionless imports does not occur for import with only specifier

### ISSUE THREAD

**Issue by dsherret** [microsoft/TypeScript#52191]
# Bug Report

Doing `import "./other";` will not raise a `Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './other.mjs'?` error.

### 🔎 Search Terms

import specifier only side effects

### 🕗 Version & Regression Information

5.0.0-dev.20230110

### ⏯ Playground Link

Here's a repo: https://github.com/dsherret/tsc-issues/tree/importOnlySpecifier

### 💻 Code

```json
{
  "compilerOptions": {
    "moduleResolution": "NodeNext",
    "target": "ESNext",
    "module": "NodeNext",
    "declaration": true,
    "emitDeclarationOnly": true,
    "traceResolution": true
  }
}
```

```ts
// main.mts
import "./other";

// other.mts
export class Test {}
```

### 🙁 Actual behavior

Does not error unless I change the import to have a default, namespace, or named import. Output will fail at runtime.

```
======== Resolving module './other' from 'V:/tsc-issues/main.mts'. ========
Explicitly specified module resolution kind: 'NodeNext'.
Resolving in ESM mode with conditions 'node', 'import', 'types'.
Loading module as file / folder, candidate module location 'V:/tsc-issues/other', target file types: TypeScript, JavaScript, Declaration.
Directory 'V:/tsc-issues/other' does not exist, skipping all lookups in it.
======== Module name './other' was not resolved. ========
File 'V:/tsc-issues/node_modules/typescript/lib/package.json' does not exist.
Found 'package.json' at 'V:/tsc-issues/node_modules/typescript/package.json'.
File 'V:/tsc-issues/node_modules/typescript/lib/package.json' does not exist according to earlier cached lookups.
File 'V:/tsc-issues/node_modules/typescript/package.json' exists according to earlier cached lookups.
...etc...
```

### 🙂 Expected behavior

Should error because no extension used.

**Comment by andrewbranch** [comment]
Side-effect imports like this have never been checked that they resolve whatsoever. @DanielRosenwasser and I briefly discussed whether we could change this, but I don’t know if there was a consensus. It would definitely be a breaking change.

**Comment by dsherret** [comment]
Interesting. Well overall it's not really that big of a deal since people will get an immediate error when running the code and people rarely write these kind of imports.

**Comment by andrewbranch** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/50394

**Comment by dsherret** [comment]
Yeah, I should have search for "side-effects" 😅

**Comment by andrewbranch** [comment]
Added some new discussion in #50394
