### ISSUE TITLE
InstanceType not able to effectively narrow class union

### ISSUE THREAD

**Issue by rolivegab** [microsoft/TypeScript#52192]
# Bug Report

```typescript
export const isInstanceOf =
  <T extends abstract new (...args: any) => any>(e: T) =>
  (target: unknown): target is InstanceType<T> =>
    target instanceof e;

class Dog {}
class Cat {}

// const isDog: (target: unknown) => target is Dog
const isDog = isInstanceOf(Dog);

// this works
function THIS_WORKS(thePound: Dog | Cat) {
  if (thePound instanceof Dog) {
    return thePound; // Dog
  }

  thePound; // <------ Cat, as expected
}

// this not works
function THIS_NOT_WORKS(thePound: Dog | Cat) {
  if (isDog(thePound)) {
    return thePound; // Dog
  }

  thePound; // <------ never, it should be Cat, as it's not a Dog
}

```

playground link https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wJaoJJpgQ2QWAHkAzOAXgCg44AeAFTlBmGQBNU58AjdKPgTxkwAO5wAFADpZ+KAHNUALh7IAngEoqAPjXqdk4KsbbKO2lIKLgMVQFdkAa2QQxyTausLbcLHFx0QmJGdTBgJj1zSzpvXww8YOAICmAAbmpqBAAbfFRuABEIBTgAbwBfLNz8uABhfHgKzIB6ZsQUdD9UIoVVSTi7OEcXNw9dOAGuuB6sjsxu4qouwIIiUjJJHs0M6laJgAt-MWgnVGoyR2EMFDhGAAlsAGUAfQB1EgAlAGlH-v3gAAKEEcHFUPTgAB86g1tKVLDB-kCQZYMBQ-oDgZw-Ik1ilpsVYTE4FBbPYoMgDhiQWk4HsZnRKvDEZiODS9vQALRc7nQmAAGh43FA4WEwA41EZewR-lc8GOUFO50uMGuFPuT2eADkSIw3p8fuikZwwYsofUYIS6KipFgeoaWZpLXRiaTyZSjazaW16XBGbFmdSvQxuTzRAA3YBQAUYeCofbA7IcOC8YC8gV5PwwADk3FlPHxCglQA

**Comment by MartinJohns** [comment]
`Dog` and `Cat` the same type as far as the compiler concerns. Either have them structurally differ, or add a private member to make it nominally typed. There's an entry about this in the FAQ.

**Comment by MartinJohns** [comment]
`Dog` and `Cat` the same type as far as the compiler concerns. Either have them structurally differ, or add a private member to make it nominally typed. There's an entry about this in the FAQ.

**Comment by rolivegab** [comment]
Thank you, makes total sense.

So in this case, there's no way to correctly mimic instanceof behavior? looks that compiler do a different check when using this operator.

**Comment by MartinJohns** [comment]
That's correct.  `instanceof` is actually not really safe either, because you can assign object literals just fine that will pass the check at type level, but fail at runtime.

Rule of thumb for me is to never have classes without private members.
