### ISSUE TITLE
Inferred template type is unknown when complex types and marker interfaces are involved

### ISSUE THREAD

**Issue by alberto-schena-gizero** [microsoft/TypeScript#52193]
# Bug Report

### 🔎 Search Terms

marker interface generic template type inferred unknown

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about marker interfaces and complex types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/JYOwLgpgTgZghgYwgAgLJyga2gHgCoB8yA3gL4BQ5oksiKA8gEYBWJF5MAriAmMAPYhkMfv3wEAFPxYAuNBmxRxASjl4S5ZFuRQIYTlCFSWyOAGdTIAJ7KAdGFMW8AbnLsuPPoOSMM448xy6Fi4hMokyAD0kcj0ANJyoDDQugAmwty8AkK+SoQBQQqhBKrIeJrauvqGwqIBys5RMfGJIMlQaRme2bVi+dKB8iF5JWpulB5Z3r4AXv4DckysAGRDiioR0chx9K3tnZNeOXBz-bKxJqvB62Fy3Jgg-ADuIBVaVQZCIvz1jVs7exSEHShx63xw90eL0kCzWuEhzxAo2QCJebiAA)

### 💻 Code

```ts
interface Marker<T> {}

interface Obj {}

function foo<T>(obj: Marker<T>): T {
    return (obj as any).t as T;
}

function bar<T>(obj: Marker<T>) { // OK: inferred function bar<T>(obj: Marker<T>): T
    return foo(obj); // OK: inferred function foo<T>(obj: Marker<T>): T
}

function baz<T>(obj: Obj & Marker<T>) { // KO: inferred function baz<T>(obj: Obj & Marker<T>): unknown
    return foo(obj); // KO: inferred function foo<unknown>(obj: Marker<unknown>): unknown
}
```

### 🙁 Actual behavior

When complex type (&) with generics is used, template type parameter inference results in "unknown".

### 🙂 Expected behavior

I would rather have expected this:

```ts
function foo<T>(obj: Marker<T>): T { ... }

function baz<T>(obj: Obj & Marker<T>) { // inferred function baz<T>(obj: Marker<T>): T
    return foo(obj); // inferred function foo<T>(obj: Marker<T>): T
}
```

**Comment by fatcerberus** [comment]
See this FAQ entry: https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--.

TypeScript is structurally typed and `Marker` doesn't use its type parameter, so any `Marker<T>` is interchangeable with any `Marker<U>`.  This makes type inference in more complex cases inconsistent, since the compiler tries to "work backwards" to find the type argument.  If you actually use the type parameter in the definition of `Marker` then it all works as expected: [Playground link](https://www.typescriptlang.org/play?ts=4.9.4#code/JYOwLgpgTgZghgYwgAgLJyga2gHgCoB8yA3sgPoC2G2UAXMnsgL4BQLoksiKA8gEYArEqxYwAriARhgAexDIYMmfgIAKGYProsuQgEp6jYi2SnkUCGDFR56wcjgBnByACeegHRgHzvAG4WEXFJaTlkPgwVOwEtal0CPRITMwsrGwUlaL0AgHocswLTAD0AfkC2YKlZeQiALyiNGOR+IQAyNDioFUTjAtTreUUZLNz8wrNS8qA)

**Comment by alberto-schena-gizero** [comment]
@fatcerberus thank you for your reply.

I already tried the solution you suggested, and noticed it works.

However, I would avoid defining fields within `Marker<T>`, as the sole purpose of `Marker<T>` is to convey type `T` for further strong typing. In addition, a field in `Marker<T>` would force me to define such unwanted field within implementer classes.

Is there a way to actually "use" type `T` without defining a field (maybe referencing it in some type expression would work)?
e.g.

```ts
interface Marker<T> extends SomeUtilityToPinType<T> {}
```

Clearly, the problem occurs due to complex types (e.g. `X & Y`). Maybe they consider fields in a structure, and `T` is discarded as long as no fields are provided by `Marker<T>`?

**Comment by fatcerberus** [comment]
> Is there a way to actually "use" type T without defining a field

No.  This is a fundamental part of the design of the type system.  It's structurally typed, which means the type of something is ultimately defined by its contents, not how you invoke the type.  Therefore if you don't use `T` to type something inside the interface, then it effectively doesn't exist from the point of view of type inference.

> the sole purpose of Marker<T> is to convey type T for further strong typing

For the record, `Marker<T>` is *not* strongly typed for the exact reason outlined above - `Marker<string>` is assignable to `Marker<number>`, for example.
