### ISSUE TITLE
Description misunderstanding

### ISSUE THREAD

**Issue by Ninel314** [microsoft/TypeScript#52194]
## Missing / Incorrect Definition

Hi, 

although the issue is not critical, it creates some misunderstandings.
in lib.es5.d.ts (lines 767 - 797)  there is an incorrect description of the methods responsible for handling date and time.

I will attach a picture.

Thank you!

![image](https://user-images.githubusercontent.com/61876915/211801561-514b7cf5-dd5d-47cd-acdc-70b24e187557.png)

**Comment by MartinJohns** [comment]
I don't see what the issue is. Are you aware that the comment applies to the next line, and not the previous one?

**Comment by Ninel314** [comment]
It makes sense, thank you.
