### ISSUE TITLE
[Feature Request] Add compilerOption that validates ".js" extension is present in import path

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#52204]
# Suggestion

Previously, the TypeScript team have [made it clear](https://github.com/microsoft/TypeScript/issues/16577) that the compiler will not modify/rewrite import path extensions to convert TypeScript imports to valid ESModule imports - that's totally fine, this is not that discussion 

Currently, the TypeScript compiler does accept import paths to TypeScript source files with `.js` extensions. Despite the import saying `.js` it will resolve the relevant `.ts` file:

```typescript
import { foo } from "./foo.js"
// tsc will resolve "./foo.ts" but emit "./foo.js"
```

Can the TypeScript compiler include the capacity to enforce that extensions are present - (only a suggestion) perhaps via a new `moduleResolution` which respects the ES Module standard?

Perhaps:

```json
{
  "compilerOptions": {
    "moduleResolution": "ESNext",
    "moduleExtension": ".js | .mjs", // currently only .js is supported
  }
}
```

Where, when enabled:

```typescript
// File import
import { foo } from "./foo"    // Invalid - compiler throws
import { foo } from "./foo.js" // Valid

// Folder import
import { bar } from "./bar"          // Invalid - compiler throws
import { bar } from "./bar/index.js" // Valid
```

Pros:
- This will help with the creation of JavaScript packages that can be used directly in the browser without a bundler

Cons:
- Aforementioned libraries would need to ensure that all of their dependencies also included extensions

## 🔍 Search Terms

enforce typescript .js extension in import path

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
AFAIK this is already enforced when using ESM resolution modes, see e.g. https://github.com/microsoft/TypeScript/issues/52191

**Comment by alshdavid** [comment]
I think (correct me if I am wrong) `NodeNext` still carries over node-isms - like resolving packages from `node_modules`, resolving `./foldername` as `./foldername/index.js` and respecting import mappings from `package.json`.

My request is more about the validating your source against the minimal import capabilities present in browsers

**Comment by andrewbranch** [comment]
I think you’re looking for #50153. Have a look at the status update at https://github.com/microsoft/TypeScript/issues/50152#issuecomment-1349268988.

**Comment by andrewbranch** [comment]
Closing given this is pretty well tracked in https://github.com/microsoft/TypeScript/issues/11979 and #50152
