### ISSUE TITLE
[Feature request] "Object (or enum/whatever fits) of types"

### ISSUE THREAD

**Issue by hyoretsu** [microsoft/TypeScript#52200]
# Suggestion

Correct me if I'm wrong, but I don't think this is possible currently. My use case is that I created a function that receives an (API) URL as a parameter, and I can annotate its return. 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases

So I was trying to create an object with every route from my API that gave me its correspoding response type, like this:

```typescript
const APIMapping ={
    "/exp": Array<{ level: number; exp: number }>,
}
```

and further use it in the function like this:

```typescript
function useFetch(url: string, api: AxiosInstance) {
    const reqInfo = useSWR<APIMapping[url]>(url, async (url) => {
        const { data } = await api.get(url);

        return data;
    });

    return reqInfo;
}
```

Currently, neither does the value get recognized as a type, not does `url` get recognized as the parameter, but instead an undefined type. I tried using namespace, interface, enum, type, objects, nothing works.

**Comment by DanielRosenwasser** [comment]
[You can do this today](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggCgSQLIEMxgJYDsDmUC8UA3gFBTlQBEA9BAB5iUBcsATqyiADxFQA2EAG4Q+LLAFcAtgCMIrANxR6YMVNmsoAXwB8AGhKb5JEgDNxWAMbAMAeyxRxAZwgAxCMAsALLgGkldYAgsABNHKABrCBAbE1hEVHRsHG0ACnFWUSgfXSg0DBYYOltHBCxHYBRLCF8c+GQ0TFwAbR8AXW0ASmIyCgs7cqhWCABHUpMbAgdnAGUAdQAlNIyclEcQSyglvi78bW6KA6g+suBiKGCUCq1JlJQAdxQMU7yAOhx3LY6Oox7Dwfd0vYLhUjAdNN9jAchsBAf9RlhxkZNMZsIFWCYUBZoIViqVypUsTUoAA1PakA7vYApSIgFg+DosOCsGySDDOHjnS4oFjErTaJHGMyWax2KYQObzLgAFX8gRCYXKrCSqXSmSlK1YOAAjCwtiwpTs9kyWWzquZwlgbHcsJ19hRgJ5mXcoFgIM6AKLsGysFKUFzmKy2eyW04YSRgASSIKBYIvSgQ5FAA). What it seems like you're asking for might blur the line between types/values though, which is a line we try not to cross.

```ts
type APIMapping = {
    "/exp": Array<{ level: number; exp: number }>,
};

function useFetch<K extends keyof APIMapping>(url: K, api: AxiosInstance<K, APIMapping[K]>) {
    const reqInfo = useSWR(url, async (url) => {
        const { data } = (await api.get(url));

        return data;
    });

    return reqInfo;
}

interface AxiosInstance<K, V> {
    get(key: K): Promise<{ data: V }>;
}

function useSWR<T extends string>(url: T, arg1: (url: T) => Promise<unknown>) {
    throw new Error("Function not implemented.");
}
```

For future references, please fill out the issue template appropriately (or reconsider if the suggestion doesn't meet our criteria for new features).

**Comment by hyoretsu** [comment]
Thank you very much, that's a really ingenious way to do it that I didn't know was possible nor could find on Google. Retro-actively feeding a type parameter based on the type infered from a parameter value.

**Comment by hyoretsu** [comment]
By the way, `type` already supports the "object of types" I was looking for. But I had to index it using a type, so I had to retrieve a parameter value into a type using your solution so I could index it as `APIMapping[K]`.
