### ISSUE TITLE
Can't assign type of member of one object to type of same member of superset object

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#52218]
# Bug Report

### 🔎 Search Terms
 "not assignable" missing "following properties" 

### 🕗 Version & Regression Information

- This appeared between 3.3.3333 and 3.5.1, and changed between versions 3.5.1 and 3.6.3, and again between 4.2.3 and 4.3.5 in shortening the error
- Nightly version at time of test: v5.0.0-dev.20230112

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAqAsFMGdIAgGYEsBO0Aud0HcD2cBDFeAE0mQDtIS4kK4SkEFJiLMAHAGwIGMZCFGuijFa0QnC65MuBHF64yAKBDZwSXuDgBXWBICC6dCiQAjHekgBlSJnWbtJXAIozdsOEZPnLNnWaw6ADcqsAi8N6mFlbWAUEM5HRI6Ei49EgS0ByQvEgEXEgAXtSCNNDguDpc5am8ANZw2CngYREKSvAiBJh6AikANE0aWuJwbpj87CgFWPjtBBzcmj1pFAB0YQCS9lU1cGbwdIscKLin+VZziZTwAAZRvrF2cJAAHlZChsbRfnGBdjuYRiDFwvB0AFtIOxVulaEIVlYJKBrHAKnsaIdCGYuF18MgAOY6MQpOBVTB0LAaCS8AiwTYgAxcaC4IbdTDOGAUADkmBZXAAbl0oOJoDpIJs6FYUAg+JEfk9-ADMABvQgEyAALnGkMOKCGFAIUO1GFMFAJwTgAF9lFLWLL+F4FTEbC81QQNdqKLrWJbDca0T5zX7NPV-VrA2aLXAoEgCeB0F6fShLTayLweGIEDoKLxUnDFBCIekAApnfjQaB0AkAMVwKAMFAAno8XQAeAyvD7QkgSeqQJtyJ0+F22dAAPgAFMo4LPCM6-AA5I0RgwDGdznojvwANQK4u1rb+dgA2gYALrKACU2oIzdC7w49cm6QwaJyeQKxWoZbBMCr5p1ig1i4FCR5InAAC8iA5nmawdl2ny9nA-aDvI4FKkEU4brOW6-FYy5QnAh5wOuc7ztuVh7lw4rEcO+GYaeF7rlecAqjhcAgOs3HZLk+SFCUNCnH+lbVog9ZUpkaLxC8Q54YqEiiBK3EccQ6DEvQhbFhQv4VgBtb1o2LYLlY07keR8kuoRkBkeZs4gOg0CTgATAAzAALAArKxrBnCgZL0FQHxSHQWoceRjIoESULsGS8joE2ORwNyGH-EEZ7ntyYwTIQokEoaOJ4nAHBECu0pxVgiXwClJmuugGXcpsdn2WAVXJalMnoFlUkQpk+lUvACC4Fw0jNOaxVnDkKCpAICBnBClVJTVlF1dyXqhuGQyxvG6DhZutXUbRIAQFU8YKHSqTjSIUl3HS9GKmOGV3E0GJosNQoDa8KB+fCkkSHQGB3vwtl2Q5Iq0m+eDVDQBQsk0dA0DoHBokguK5mJ2bqWIhYcKjrBfX50B7S1d5CcQQqxe0hxUMgjkVQlOQALRaLk9RiQ4oxEEcEJPtNd6YOg+BkFYeZwMQBLEKJr7E5xwCUhDwpHEIkA5MrsVkJQKRrBIQ4dcqZTABJqUvIwQpRZAMsgJSYqc00BBNlSPT3aOnXZfg0jmvjBDSfruu1WOmqW+E4BO2zQgVabrAarm8DotD519IIBMSYLhBLJARAxqwEpBwAQg7ehiRKBLrJIEOyP5jmM3GbhiKnGqYEQVTh9dNLEmw6BcA7wu5FYNCysykCM0+VapB9vn1kMpJ4Dy6BNXOV6hFaoRAA)

### 💻 Code

```ts
//https://github.com/microsoft/TypeScript/issues/52218
//These first two are defined in different places and there is a lot of code
//which uses AttributeSet which does not use AttributeSubset;
//the AttributeSubset definition is specialized and should stick with
//the code that uses it, which is not central to the application.
//It would be inappropriate to define `AttributeSet extends AttributeSubset`
//but documentation indicates TS should be able to figure it out in this case.
//Also, that doesn't solve the issue.
interface AttributeSubset { age: number, name: string; }
interface AttributeSet { age: number; name: string; nickname: string; height: number; }
declare function commonProcessingForAnyAttribute<A extends keyof AttributeSet>(
    attributeName: A,
    attributeValue: AttributeSet[A]
): any;
export const specializedProcessingForSomeAttributes = function<A extends keyof AttributeSubset>(
    attributeName : A ,
    attributeValue : AttributeSubset[A],
) {
    //...specialized processing for this subset of attributes here...
    return commonProcessingForAnyAttribute(
        attributeName,
        //ts(2345) error on next line:
        //Argument of type 'AttributeSubset[A]' is not assignable to parameter of type 'AttributeSet[A]'.
        //Type 'AttributeSubset' is missing the following properties from type 'AttributeSet': nickname, height
        attributeValue //Though casting this `as AttributeSet[A]` would solve the error in this instance,
        //the cast would also wind up silencing future compiler errors
        //and prevent the benefits of type-checking which are important to detect regressions
        //in case the independent definitions of AttributeSubset and/or AttributeSet diverge
        //in such a way that AttributeSubset is no longer a subset of AttributeSet:
        //that kind of divergence should cause an error to appear here.
        //By using e.g. a cast or ts-ignore to get around this currently detected false-positive error, it won't.
    );
};
```

### 🙁 Actual behavior
Error as noted.

### 🙂 Expected behavior
No error: a specific type is assignable to a supserset; a set should accept subsets as assignable.

### Duplication discussion
I don’t think this is #43608 because the limitation discussed there focuses on index signatures, which aren’t present here.

**Comment by RyanCavanaugh** [comment]
FWIW 3.3 was just wrong, it allowed unsound calls:
```ts
interface AttributeSubset { age: string, name: string; }
interface AttributeSet { age: number; name: string; nickname: string; height: number; }
// Induced unsoundness
specializedProcessingForSomeAttributes("age", "foo");
```

I don't see an available argument for why this call should be legal: in general a `T[K]` is not ensured to be assignable to a `U[K]` unless `T` is a subtype of `U`, and `T` is indeed not a subtype of `U` here. You can counterfactually consider this definition, which would make the call unsound if subtyping in the other direction was sufficient:
```ts
interface AttributeSubset { age: number, name: string; }
interface AttributeSet { age: 0; name: string; nickname: boolean; }
```

You can make the argument that it's legal through sheer enumeration of possible values of `A`, but that's not an available means of analysis due to performance constraints. And *if* that enumeration would succeed, *then* this version of the function is effectively identical from the caller's perspective and does typecheck, so I don't see a per se defect here:
```ts
export const specializedProcessingForSomeAttributes = function<A extends keyof AttributeSubset>(attributeName: A, attributeValue : AttributeSet[A]) {
    return commonProcessingForAnyAttribute(
        attributeName,
        attributeValue //Though casting this `as AttributeSet[A]` would solve the error in this instance,
    );
};
```

**Comment by wbt** [comment]
The counterfactual in the response above should produce an error, as AttributeSubset would then not be a subset of AttributeSet.
Here, the type AttributeSet was being used only for the `keyof` union constraining the first parameter and the type of one specific member.  

On further reflection reading your comment, I see that in the example given, `AttributeSubset ` is not a subtype of `AttributeSet` for all purposes, and the fix is to change the type of the second parameter in `commonProcessingForAnyAttribute` to `Partial<AttributeSet>[A]`.  A prior version of real code had that in there (though it might not have been in exactly the right place) and it was removed in the simplification for issue demonstration.

Apologies for the false alarm, but hopefully having this problem and solution in the repo helps others who may encounter a similar hang-up.
