### ISSUE TITLE
Type not narrowed when putting `optional1 || optional2` condition in `if` statement and repeating it in its body

### ISSUE THREAD

**Issue by verhovsky** [microsoft/TypeScript#52210]
# Suggestion

## 🔍 Search Terms

```
type inference in repeated expression
repeated or condition
or condition
```

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

This code ([playground link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230112&ssl=10&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABAJwKYEcQzQEwBQAeAXImCALYBGqyAlCWVTYgN4BQiKqUIySBAbjYBfNqEiwEiOAAdJYAIYAbPAoD8DCtWQAaRJQ2ktNekabJWHRDGCJViAD4P9tS505oefLpmyp8Co7OlLRCnKIe3LxIAAxCokA)):

```ts
function required(x: number): number {
  return x;
}
function optional(a?: number, b?: number): number {
  if (a || b) {
    return required(a || b);
  }
  return 0;
}
```
produces this type error on the `return required(a || b)` line:

```
Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
```

but TypeScript should be able to infer that `a || b` can only be a `number` not `number | undefined` because the `||` expression must be true in the `if` block.

## 📃 Motivating Example

I am checking two optional properties of an object and using them interchangeably. Currently I have to use an `as` expression.

## 💻 Use Cases

See above.

**Comment by RyanCavanaugh** [comment]
Duplicate #35260
