### ISSUE TITLE
"Object literal may only specify known properties" doesn't work on arrays

### ISSUE THREAD

**Issue by Juknum** [microsoft/TypeScript#52219]
# Bug Report

### 🔎 Search Terms

`conditional typings` `vscode` `discriminated union`

### 🕗 Version & Regression Information

- This seems to be an unintended behavior of the compiler.
- This is the behavior in every version I tried (Latest release & nightly), and I reviewed the FAQ for entries about 

### ⏯ Playground Link

```ts

type TextureUse =
  | { edition: "bedrock" | "dungeons" }
  | { edition: "java"; type: "resource_pack"; assets: string }
  | { edition: "java"; type: "texture_pack" };

let uses: TextureUse[] = [
    {
      edition: "java",
      type: "texture_pack",
      assets: "foo",
      // OK, the error was expected
    },
    {
      edition: "java",
      type: "resource_pack",
      assets: "minecraft",
    },
    {
      edition: "bedrock",
      type: "resource_pack" 
      // NOT OK,
      // -> Shouldn't be allowed as TextureUse doesn't have a definition 
      //    for `type` when `edition` === "bedrock" | "dungeons"
    }
]
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
let uses = [
    {
        edition: "java",
        type: "texture_pack",
        assets: "foo",
        // OK, the error was expected
    },
    {
        edition: "java",
        type: "resource_pack",
        assets: "minecraft",
    },
    {
        edition: "bedrock",
        type: "resource_pack"
        // NOT OK,
        // -> Shouldn't be allowed as TextureUse doesn't have a definition 
        //    for `type` when `edition` === "bedrock" | "dungeons"
    }
];

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230112#code/LAKALgngDgpgBAFRgDzAVwE4wKoGd4C8occAPnAN5wwAmAlmHQPYB2AXHAEQBGtGTAYwDWnMlxpoWAcxitcogL7ExVWg2bsuAKwCGANx2cA3HEiwOnLLiaYBMAPpQdw43B258YXB1xgMdaTglEBJyVXpGVgtdA1czGAswFHQsR2cRIKNQUAAbGDA4NHxvRGTMHHwAbQBdOAI4SuUSCiaSagiNaP1DABpWknjEstSnFz6QtpJ3TxLOADMmJk5xyZIAejW4AHkAaR7TAAt4GAx+DDgAd3dqZFgBJJpWhRW2lonJtUjNThje-tNoAkuFYbBg7Gkxv9pvlZgBbAIwAQYHRzMDLJ4vZr-T6dLi8Gj8SHvNqDYEway2ByjDL-DZwAByWwQ2z2tM2AFoAHxwADKBxsORoLAA5AVeG4cjkmBdaG5cKVUOU8PAaExySKCgd9PAdHAaDA5gF1Kw4GzJgtzgADeKWy5HFhwS041i2ghuvF8QQZcicCTSWQseRPUDVIA)
      

### 💻 Code

```ts
// See the above playground code
```

### 🙁 Actual behavior

Visual Studio Code & The playground doesn't errors when unknown property is specified

### 🙂 Expected behavior

`Object literal may only specify known properties` should be thrown?

**Comment by Juknum** [comment]
On the community discord we found out a [workaround](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230112#code/LAKALgngDgpgBAFRgDzAVwE4wKoGd4C8occAPnAN5wwAmAlmHQPYB2AXHAEQBGtGTAYwDWnMlxpoWAcxitcnADRxIsAPwcWMAG4wMcAL7ExVWg2bsuAKwCGW65wDcy6DA6csuJpgEwA+lGthRzhrXHwwXA5cMAw6aQMjchN6RlY3GztglVcuMBR0LH9AkQMHUFAAGxgwODR8SMR8zBx8AG0AXTgCOFajEgo+kmoU83TbewVBkmy3PNRmoqDJkCGh0PCGzgAzJiZFKbgAekO4AHkAaSUwAAt4XX49AHdQ6mRYATyaQf1l1YGV1bDMxpKzjfYA1YzLgeLwYHyLES-QHraqbAC2cRgAgw1i2YHBqx+g3+gKBqQsPD4gkRByh7hgnm8fgCQTgB2OcAAcqcEGdLuyTgBaAB8cAAytcvBUaCwAOQ1XghCoVJiPWghXCNeZYPDwGhMBlymrXWzwaxwGgwLZxYEsNkQoYcoY7PQAA2yrrgj1udtdpnJnoIQa4vBo-FZ5E4EmkshY8m+oHaQA) :

```ts
type TextureUse =
  | { edition: "bedrock" | "dungeons", type?: never }
  | { edition: "java"; type: "resource_pack"; assets: string }
  | { edition: "java"; type: "texture_pack" };
```

Then trying to assign anything to `type` will throw an error letting only one possibility : do not declare it. 

![image](https://user-images.githubusercontent.com/49886317/212213842-3a06fb01-afc1-4d46-adac-0af4cf34f3b9.png)

**Comment by RyanCavanaugh** [comment]
This runs into limitations of the current excess property detection logic. When the target is a union, TS needs to find which type in the union is the one that should be used to mark properties as excess. The part of the algorithm that normally works here is to find the union discriminant, which is *almost* `edition` here, but not quite, because there's more than one type with `edition: "java"`. So EPC says "Well, there doesn't seem to be an obvious target type here".

When no such type can be found, the fallback behavior is that any property from any type in the union is valid, which is what's happening here.

**Comment by RyanCavanaugh** [comment]
If someone can concoct a PR that can fix this without perf downside we'd take it, otherwise this might just be a "wait for exact types" thing.

**Comment by Juknum** [comment]
Seems to have been fixed in [5.2.0-dev.20230704](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230704#code/LAKALgngDgpgBAFRgDzAVwE4wKoGd4C8occAPnAN5wwAmAlmHQPYB2AXHAEQBGtGTAYwDWnMlxpoWAcxitcogL7ExVWg2bsuAKwCGANx2cA3HEiwOnLLiaYBMAPpQdw43B258YXB1xgMdaTglEBJyVXpGVgtdA1czGAswFHQsR2cRIKNQUAAbGDA4NHxvRGTMHHwAbQBdOAI4SuUSCiaSagiNaP1DABpWknjEstSnFz6QtpJ3TxLOADMmJk5xyZIAejW4AHkAaR7TAAt4GAx+DDgAd3dqZFgBJJpWhRW2lonJtUjNThje-tNoAkuFYbBg7Gkxv9pvlZgBbAIwAQYHRzMDLJ4vZr-T6dLi8Gj8SHvNqDYEway2ByjDL-DZwAByWwQ2z2tM2AFoAHxwADKBxsORoLAA5AVeG4cjkmBdaG5cKVUOU8PAaExySKCgd9PAdHAaDA5gF1Kw4GzJgtzgADeKWy5HFhwS041i2ghuvF8QQZcicCTSWQseRPUDVIA) 👀

**Comment by jakebailey** [comment]
The fix bisects to #51884. Seems like that's intentional and good? I _think_ the tests cover this?

**Comment by jakebailey** [comment]
I'm gonna vote yes 😄

**Comment by Juknum** [comment]
Oops yeah I wasn't sure if your answer was for me or somebody else ^^"
