### ISSUE TITLE
Allow generic type narrowing using the `typeof` operator

### ISSUE THREAD

**Issue by blaumeise20** [microsoft/TypeScript#52223]
# Bug Report

### 🔎 Search Terms

`generic typeof`

### 🕗 Version & Regression Information

- This changed between versions 4.2 and 4.3 (the error cause changed)
- This is the behavior in every version I tried on the playground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/GYVwdgxgLglg9mABAZwI4gIYCcCmAeAFURwA8ocwATZRMEAWwCMctEAfWh5rAbQF0AfAAoAbhgA2IHAC5EBAJSyiAbwBQiDYhjBEQqAE8ADjjg6xknIgC8NxACI6TFnfmI1mj4lxQQWJOalEACpEAJwAbnVNAF8ojRxxZEt3Tw1vX38JKQA6egxDITRMXHlIj1jYoA)

### 💻 Code

```ts
function square<T extends number | number[]>(value: T): T {
    if (typeof value === "number") {
        return value * value; // error: `number` is not assignable to `T`
    }
    else {
        return value.map(square); // error: `number[]` is not assignable to `T`
    }
}

```

### 🙁 Actual behavior

These two lines show errors that the given type is not assignable to type T.

### 🙂 Expected behavior

I would expect this to work, because TypeScript can clearly see what type `value` has, and thus restrict `T` to that type.

**Comment by MartinJohns** [comment]
That would not be type safe. Just because `T` extends `number` doesn't mean your operation is valid. `T` can be a literal as well.

```typescript
const foo = square<2>(2)
// Typed 2, is actually 4.
```

**Comment by blaumeise20** [comment]
Oh yeah, you are right. Function overloading solves my problem!
