### ISSUE TITLE
Provide `lib`/`target` suggestions for `findLast`/`findLastIndex`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52220]
Once https://github.com/microsoft/TypeScript/pull/49636 goes in, we should ensure that a user gets suggestions for using `findLast`/`findLastIndex` when their output `target` or `lib` is too low.

```ts
function findLastZeroIndex(arr: number[]) {
  return arr.findLastIndex(0);
}
```

We already do this for other missing methods.

**Comment by OliverRadini** [comment]
Are you happy for anyone to take a look at this? Looking to find an issue to work on

**Comment by DanielRosenwasser** [comment]
Go for it. The code is in `getScriptTargetFeatures`. Add a new entry for `es2023` containing entries for `Array` and all the `TypedArray` variants.

https://github.com/microsoft/TypeScript/blob/cb4c7689e69203feeaa32f075c2cb8c7240c2c64/src/compiler/utilities.ts#L1180
