### ISSUE TITLE
Ambient modules declared with patterns are offered in path completions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52233]
```ts
// globals.d.ts
declare module "*.css";
```

```ts
// index.ts
import * as yadda from "$";
```

Request completions at `$`

**Expected**: Do not offer `*.css` in completions.
**Actual** We offer `*.css` in completions.

**Comment by fatcerberus** [comment]
Out of curiosity, if you *do* accept the completion and import from `*.css`, do you get the types from that declaration?  Because that should also be fixed if so 😉

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
