### ISSUE TITLE
`Array.filter` does not properly narrow down type

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#52247]
# Bug Report

### 🔎 Search Terms

array filter narrow down

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: x

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIDED2nkG8CwAUMsjNgFzIBG2ANhHCANxEC+RRoksiKqAQnCh4iJKkMo1M9Ri0LtCRBJhABnMMmCQAtqsoAKDNmQAfNIKgBKANoBdZAF5kduURgBXEAjDAVm1ViY+phUAFaUngDWIJgA7iCWlCGh-miBIsSaMMj6AITJlhkkJFAQYO5QIKRwtKoQciQKosjKahoIjAAmwJ1wkI7IychwqmnYDcil5ZXIYACeAA4QmNkdIN29kAB0ZDgO+8gABlIyIIdyTYSt6qTYqDqjTloQujvAtNz6z9qOAHz+gS+OksljkZGE+muGl29xeg2yMIehQImWu0ggW1omAA5vpES8dthQcgAPQk5DQKCYKCUAAKVKWUHmtxwnUwEFGMQ0EAAHsAbn55ksxjgzAIhGwgA)

### 💻 Code

```ts
interface IFoo {
  foo: boolean;
}

interface IBar {
  bar: boolean;
}

const items: (IFoo | IBar)[] = [];

function isFoo(obj: unknown): obj is IFoo {
  if (!obj) {
    return false;
  }

  const candidate = obj as IFoo;
  return typeof candidate.foo === `boolean`;
}

const fooItems = items.filter(item => isFoo(item));
for (const fooItem of fooItems) {
  console.log(fooItem.foo); // error: Property foo does not exist on type IFoo | IBar
}
```

### 🙁 Actual behavior

The `fooItems` is of type `IFoo | IBar`

### 🙂 Expected behavior

I would have expected `fooItems` to be `IFoo[]`.

**Comment by MartinJohns** [comment]
`filter()` only narrows when you pass a type guard function. You don't do this.

**Comment by bpasero** [comment]
How is `function isFoo(obj: unknown): obj is IFoo {` not a type guard function?

**Comment by MartinJohns** [comment]
The inline function `item => isFoo(item)` is not. It lacks a type annotation, so the type is inferred to be `boolean`.

**Comment by bpasero** [comment]
Cool thanks for the help! Very hard to figure this out though for me, even though having used TypeScript since 2012.

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/38390
