### ISSUE TITLE
Can't write instantiation expression with function operand of lookup type from module import

### ISSUE THREAD

**Issue by ineshbose** [microsoft/TypeScript#52248]
# Bug Report

### 🔎 Search Terms

`typeof`, `import`, `function`, `generic`, `literal`, `syntax`, `error`

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIJQOYB4AqyC8ycIAngDTIAKcUcAtgM7IQAekIAJkwEoQID2UDlgZgooDBWIkAfAWS8BQkWIlTSMuQG8AUMn3IARAH1jwBsZoYArnQjhThgPwAuZGOsQA3HoN2wcK7IOD4GyAAONPQMQdS0jD4Avjo6rOGCYMgw1iAIYMD8IMh0JABiOXkFILjy0hQAqsxs9lwKfILCouIgkkQa8oodKt290poAFFZu6Ng4DTIAlMhayFAQYNZQRZOYAHSR8UwAPkfLiUtwTI3JOgD0t8gAAjDAADb29BBuL+8ATLtgBh3B6ocLhKD8RAAC2QAEYdGASOEUOVcvlCjgkShCIjkfwYMhgHR0lAwOMAOS7W6gcLWMC7ABWDHJCwA2uSSqjKoVyQBdLB1ZbIBivawYNzkqEQV6vfjk5CJOT3YUkcBwFjMKAQqApZWg8GQhAw37A9xY5ClPA4rH4wnEjIUqk0umM5lsjllCrokB85DKy3CqH8ayvDjuOAAaxQoGQGHs0GACAYFAARnT3FKigB3CDktbIFOICPufhEMEQ6Fw024lCY5E4LOlwiWgWkCgrEViiVQ4DyxU6IA)

### 💻 Code

```ts
interface Arg<T = any, Params extends Record<string, any> = Record<string, any>> {
    "__is_argument__"?: true;
    meta?: T;
    params?: Params;
}

export function myFunction<T = any, U extends Record<string, any> = Record<string, any>>(arg: Arg<T, U>) { return (arg.params || {}) as U }

// @filename: file2.ts
// Approach 1
type FunctionType = typeof import('./input.js')['myFunction']<any, { slug: 'hello' }> // syntax error

// Approach 2
// type FT = typeof import('./input.js')['myFunction'] // FT should take in generics, but then we're back to approach 1
// type TypeTwo = FT<any, { slug: 'hi' }>
```

### 🙁 Behavior

`FunctionType` would be typed as `(arg: Arg<any, { slug: 'hello'; }>) => { slug: 'hello'; }`, but this can't be done due to syntax errors (starting with the generic arrows `<`).

**Comment by RyanCavanaugh** [comment]
@ahejlsberg what's the intended grammar here?

**Comment by ahejlsberg** [comment]
A `typeof import(...)` only permits member selection using dotted names (e.g. `typeof import(...).x.y.z`) and doesn't currently support specifying type arguments for an instantiation expression. We should probably lift the restriction on type arguments.

The repro above is parsed as:

```ts
type FunctionType = (typeof import('./input.js'))['myFunction']<any, { slug: 'hello' }>;
```

i.e. we end up with an indexed access type `(typeof import('./input.js'))['myFunction']` and it isn't possible to apply type arguments to that (by design).

The repro really should be written:

```ts
type FunctionType = typeof import('./input.js').myFunction<any, { slug: 'hello' }>;
```

but then of course it falls victim to the lack of support for instantiation expression type arguments.

**Comment by ineshbose** [comment]
Thanks for the input - it may be my intellisense that shows exports when using indexed access types and not during dotted names.

> We should probably lift the restriction on type arguments.

I do seem to require passing generics to functions like that (similar to the playground), so does this mean that this is planned? 🙂

**Comment by ahejlsberg** [comment]
@ineshbose I will have a PR up shortly that allows you to write

```ts
type FunctionType = typeof import('./input.js').myFunction<any, { slug: 'hello' }>;
```

I'm not seeing any issues with intellisense.

**Comment by darkbasic** [comment]
@ahejlsberg why is not possible to apply type arguments to an an indexed access type by design?

```
class Echo {
  echo = <T>(a: T): T => a;
}
type echoNum = Echo["echo"]<number>;
```

Is there any other way to achieve the same result as the (non working) previous snippet?
