### ISSUE TITLE
incorrect name mappings: last name index is used for unrelated entries

### ISSUE THREAD

**Issue by develar** [Microsoft/TypeScript#5224]
IntelliJ IDEA supports name mappings and currently typescript compiler produces incorrect name mappings (https://youtrack.jetbrains.com/issue/WEB-17717).

Typescript code:
```typescript
class Foo {
    public b = 3;
    bar(param1){
        var a = 5;
        return a;
    }
}

new Foo().bar(1);
```

Debug output: https://gist.github.com/develar/598a984f27bb92526094 

Project to get debug output: https://dl.dropboxusercontent.com/u/43511007/s/ts-name-mappings-bug.zip

IDEA sourcemap visualiser: ![screen shot 2015-10-12 at 14 56 21](https://cloud.githubusercontent.com/assets/350686/10428494/20556936-70f2-11e5-9f24-596820400938.png)

**Comment by develar** [comment]
Is it known issue? Or was not yet investigated and pull request is welcome?

**Comment by sheetalkamat** [comment]
We have decided that we wont emit the names since the sourcemap spec is unclear of its use. Browser tools don't use it either. We would be waiting to hear about symbol translation and then get to this.

**Comment by develar** [comment]
@sheetalkamat Answered in the linked ticket. It is a wrong decision to drop name mappings generation.
