### ISSUE TITLE
strictPropertyInitialization does not require initializer

### ISSUE THREAD

**Issue by arv** [microsoft/TypeScript#52259]
# Bug Report

If I have `strictPropertyInitialization` set to `true` in _tsconfig.json_ I expect that it would be an error if there is no initializer for a property.

### 🔎 Search Terms

strictPropertyInitialization
undefined
initializer

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useUnknownInCatchVariables=true&exactOptionalPropertyTypes=false&ts=4.8.4#code/KYDwDg9gTgLgBDAnmYcBSBlA8gOQGoCGANgK6oC8AUHHAD5wB2JRR1dcAzjFAJYMDmbegCMIEIsAIMhjEgFthwKDICCUKAUQAeTLkKlgAPhm6cWYQCtgAYxgBuSpVCRYCZKlPmrtuOTgAFAlgeYi0AbwBtAGtgRAAuTm4+fgBdBNN9MgBfQwcncGh4JBR0bHxiMgAmXxkmFhkuXgEZUXFJaRp6JgUlVXVNHTLM4ErjTtLcLxsYSrznQrcSz0tp6r9ImPjEptT0oYqRrLywtmLUADExXzgwuDYaYSCExuSAGnu4R4AvAH5npIE7xoWUcNAAZiQGLYeBAGHAwFAINZgBwOABGAAUYLECUuEAAlHtJisfCcaDQoMAYCQoHDsRAHMDQXAIVCYDC4QikSiOJUsTi4HjCRMzCSZjcPpTqbSWWJGXAQWwucjUZiwo8oAkAORorWvT4EL4JSEAE2AYL4wBNWXx8uVPL56qecC1lT1BqNcFN5st1ttlEVlDJiwuV3Wd3JBs12zeH2+-x27G9FoYVqBCuZrOhsPhiJV6P5EFxYmFy288GDFKpNLpcrYivBkOznLzDsLxYJRNF5eqlbgUprsoZ9eZ9tVGKd0Z17vjXoYZpTVptdtbqMdGu1bv1s+TvuXAcoQA)

### 💻 Code

```ts
class C {
  // @ts-expect-error Missing initializer
  x: number | undefined;
}
```

### 🙁 Actual behavior

No compile error 

### 🙂 Expected behavior

I expect there to be a compile error because instances of this class will not have an `x` property.

Always initializing properties in a fixed order is important to ensure all instances end up with the sam hidden class in a lot of JS VMs.

**Comment by whzx5byb** [comment]
Per https://github.com/microsoft/TypeScript/pull/20075:

> Strict property initialization checking verifies that each instance property declared in a class either **(a) has a type that includes undefined** or (b) has an explicit initializer or an assignment to the property in the constructor.

So it seems like the intended behavior.

**Comment by fatcerberus** [comment]
Also worth noting that in ES-compliant code (i.e. `useDefineForClassFields: true`), the `x` property *will* be created with the value `undefined` on all instances.
