### ISSUE TITLE
Key type not properly infered by `Object.entries` for Records

### ISSUE THREAD

**Issue by kuba-orlik** [microsoft/TypeScript#52260]
# Suggestion

## 🔍 Search Terms

Object.entries, inference, keys, string, Record

## ✅ Viability Checklist

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Make `Object.entries` better infer types of the keys for a Record type. 

## 📃 Motivating Example

The below throws a compile error, as the `permission` variable within `forEach` is assumed to be string. However, TypeScript has all the information it needs to know that the keys of the `s` object are of the `Permission` type.

```ts
type Permission = "view" | "edit";
type Settings = Record<Permission, boolean>;

const s:Settings = {edit: false, view: true};

Object.entries(s).forEach(([permission, enabled])=>{
    s[permission] = !enabled;
})
```

Playground link: https://www.typescriptlang.org/play?#code/C4TwDgpgBAChBOBbAlgZ1cg9gOygXigCIA3ZCAd0KgB8iIATZYQgbgChRIoBlCYYZNgDmqfFABKEAMaZ49ADxwkaDDgA0UAEaZMAGwgBDbAD52bGdlTAoqAFy9+gkWIDeDJragAzA7tQQNUgpPYHgAVwgAXzMAeU0AK2lgADoIbFCyVAAKVABKZK9ZAFEDKQALLKyAbUhldCxsDTSDTX16AF1cvGMXNih+mxqEFHqcdrEAQmbWhnZI3KA

## 💻 Use Cases

The current workaround is to manually add `as Permission` every time the `s` object is processed by `Object.entries`, and this causes more brittle code.

**Comment by MartinJohns** [comment]
Objects are not sealed. You wrongly assume the key can only be `"view"` or `"edit"`, but that's not the case.

```typescript
const a = { edit: false, view: true, foo: "hello" }
const s:Settings = a
```

**Comment by kuba-orlik** [comment]
Hm. Why is this allowed:

```
const a = { edit: false, view: true, foo: "hello" }
const s:Settings = a
```

But this throws an error?

```
const a: Settings = { edit: false, view: true, foo: "hello" }
```

It seems like when we make the first case throw an error, then we could have nicer key type inference with `Object.entries`?
