### ISSUE TITLE
Conditional type on union function is not applied uniformly

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#52265]
# Bug Report

### 🔎 Search Terms

conditional type intersect function

### 🕗 Version & Regression Information

TypeScript: 4.9.3, 5.0.0-dev.20230116

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogjgVwIYBsBiA7APAQQDRQBCAfFALxQ5QQAewEGAJgM5FQD8UAFIdXQy0ocoARigAuKACYAlBKgBmAFBLQkKACVysRKkxYuXAG6TmwAE4BLDAHM5ZUmau25AH27HJGBAFsARhDm9qTe-oEyeEpQHiZQTtZ25I4WCW4xXr4BQUlQoVkypAD0haJQ7lJKQA)

### 💻 Code

```ts
type EqualFn<A, B> = A extends B ? (B extends A ? 1 : 2) : 3

type R = EqualFn<
  ((v: string) => string) | ((v: number) => number),
  ((v: string) => string) | ((v: number) => number)
> // 1 | 2
```

### 🙁 Actual behavior

It resolves to `1 | 2`. Optimally it should resolve to `1`, but even if not, it should at least be `1 | 2 | 3`.

### 🙂 Expected behavior

Optimally it should resolve to `1`.

**Comment by MartinJohns** [comment]
There's no intersection here, it's a union, and conditional types on unions are distributive by default. You can prevent this by writing `[A] extends [B]` instead.

**Comment by unional** [comment]
Argh, can't believe I misused the term.

The issue is that it does not do it uniformly. You can see that it does not resolves to `1 | 2 | 3`, i.e. it only distribute at the second condition and not the first one?

If distribute uniformly, I assume:

```ts
type EqualFn<A, B> = A extends B ? (B extends A ? 1 : 2) : 3

type R = EqualFn<
  ((v: string) => string) | ((v: number) => number),
  ((v: string) => string) | ((v: number) => number)
>

// A extends B
// -> ((v: string) => string) | ((v: number) => number) extends ((v: string) => string) | ((v: number) => number)
// -> ((v: string) => string) extends ((v: string) => string) | ((v: number) => number))   // true
//      | ((v: number) => number) extends ((v: string) => string) | ((v: number) => number) // true

// -> true -> B extends A
// -> ((v: string) => string) | ((v: number) => number) extends ((v: string) => string) | ((v: number) => number)
// -> ((v: string) => string) extends ((v: string) => string) | ((v: number) => number))   // true
//      | ((v: number) => number) extends ((v: string) => string) | ((v: number) => number) // true
```
which will result `1` instead of `1 | 2`?

**Comment by fatcerberus** [comment]
The second condition *does* distribute, but it doesn't work like a cartesian product because distribution is only over the input type, not the check type.  This is what actually happens:

```ts
type T = Equals<U | V, U | V>
// T = | (U extends (U | V) ? (U extends U ? 1 : 2) | (V extends U ? 1 : 2) : 3)
//     | (V extends (U | V) ? (U extends V ? 1 : 2) | (V extends V ? 1 : 2) : 3)
````

You never hit the false branch.
