### ISSUE TITLE
Callback parameter inference using inferred generic fails within mapped type intersection argument

### ISSUE THREAD

**Issue by Hsifnus** [microsoft/TypeScript#52269]
# Bug Report

As the below picture shows, the mapped function properties appear to be correctly inferred within the generic object intersection parameter provided to the `bar` function. However, the parameters for those function properties do not implicitly infer the expected type based on the inferred property types.

![inferred-types-2](https://user-images.githubusercontent.com/25206472/212792485-b44c8f60-9eee-4f28-bea5-a7f8e186b0f8.png)

### 🔎 Search Terms

inference parameter generic function argument 

### 🕗 Version & Regression Information

This bug is a type error and appears to occur in the nightly version of TS as well as all past versions down to and including 3.3.3, and I reviewed the FAQ regarding the behavior of generics and functions.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230116&ssl=38&ssc=4&pln=1&pc=1#code/MYewdgzgLgBAtgTwLIgCYFMA2MC8MDeAUDDAIYBcMAjADTEwBGlA5A83ScJQNoC6hAXzIQYoSFADchQlAQAHdDACCAVwDmcdGCjpUKDJgA8+rFQB8uAvW4BpGAEswMANboEIAGYwTmKr0oAFHBoWJQ+VACUuBbhtvxCAGRWJMEGVGEhvlICUoQeKmDAUPbgjKQATsaZ5gEeICCUqhpaOnqZVWlmUUQk5ehQKuVOdSDZ0gwVAT0wAPQzMGAgsCoQjmpkYAgwchWkmjrlIgDuIOXOEPQUMAFROBaIPgB0pHRzAHoA-PRzDmAe6OVymsYB5yiA4L9MI5FMBSJhMBNgM4YKgQOgIGBmLATmd6ExfnIVFAfNECUSngxXjNPt95ugAB5yKHAexQTBbDDATAVYFQAAWih25T2-QBMFkChgOPO9C410chOJmUoEvQnngyEytwsCvJmUewCpNJS1UoD0ydAEEVyP0w9WcwNIsCFIoO4vk6MIE3KU0ugW1GqeLzxlF1SoMpLDFI4JHeX04gSjyvdCnV5oMAaTBgNMdm1Pj8FNgYtgmtQA)

### 💻 Code

```ts
const myModel = {
  a: 1,
  b: 'b',
  c: []
} as const;

type AugmentedModel<Model1> = {
  [K in keyof Model1]: (model: Model1) => Model1[K]
} & {
  model1: Model1;
};

function bar<Model1>(foo: AugmentedModel<Model1>) {
  return foo;
}

bar({
  a: () => myModel.a, // works
  b: inputModel => inputModel.b, // error: Parameter 'inputModel' implicitly has an 'any' type.(7006)
  c: (inputModel: typeof myModel) => inputModel.c, // works
  inputModel: myModel,
});
```

### 🙁 Actual behavior

The actual `inputModel` parameter for the `b` function property within the object argument of `bar` fails to implicitly infer the same type as the inferred parameter type for the `b` function property, i.e. `typeof myModel`.

### 🙂 Expected behavior

The `inputModel` parameter for the `b` function property within the object argument of `bar` should be able to implicitly infer said parameter type.

**Comment by whzx5byb** [comment]
Workaround:

```ts
type AugmentedModel<Model1> = never extends keyof Model1 ? {
  [K in keyof Model1]: (model: Model1) => Model1[K]
} & {
  model1: Model1;
} : never;
```

I don't know why but the new definition of `AugmentedModel` does make the type of `foo` resolved earlier. Hover the cursor on `bar` and you will see the difference.

**Comment by RyanCavanaugh** [comment]
Duplicate #47599
