### ISSUE TITLE
Insert new line between each method of "convert function to class"

### ISSUE THREAD

**Issue by jimmywarting** [microsoft/TypeScript#52266]
# Suggestion

I use this handy feature quite a lot:
![image](https://user-images.githubusercontent.com/1148376/212778768-60c80fa3-2110-47c8-816c-9862fe6581e8.png)
very useful, but i also wish that it could insert a new line between each and every method too.

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
It's very easy to add these lines with multi-cursor editing, but quite annoying to remove them if they were automatic. Without a more clear motivation / volume of feedback to change this, I don't really see a reason to.
