### ISSUE TITLE
Enforce `strictPropertyInitialization` for merged class/interface

### ISSUE THREAD

**Issue by Roosteridk** [microsoft/TypeScript#52279]
# Suggestion
As mentioned in #340, declaration merging allows us to avoid duplicating property names from interfaces to classes that are implementing them. However, there is a problem with that solution. 

## 🔍 Search Terms
declaration merging, duplicate properties, implements, strictPropertyInitialization

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
My suggestion is for the compiler with the `strictPropertyInitialization` flag set to treat the properties of an interface merged with a class the same way as if the properties were directly declared in the class. This would also align with TypeScript design goal 1. because it would identify an error that could potentially be overlooked.

## 📃 Motivating Example
Let's say we want `Bar` to have the same properties of `Foo` and forget to initialize one of them:
``` typescript
interface Foo {
  a: string;
  b: string;
}

class Bar implements Foo {
  a: string;  
  b: string;
//^
// Property 'b' has no initializer and is not definitely assigned in the constructor.

  constructor() {
    this.a  = 'a';
  }
}
```

Here, TSC would give an error due to `strictPropertyInitialization` so we know we forgot to initialize the property. Good thing we caught that early!

Now, what if `Foo` had lots of properties and we didn't want to duplicate each property from the interface to the class. We could use declaration merging to achieve that.
``` typescript
interface Foo {
  a: string;
  b: string;
  c: string;
  d: string;
// etc..
}

interface Bar extends Foo {}

class Bar {
  constructor() {
    this.a = 'a';
    this.b = 'b';
    this.c = 'c';
  }
}
```
Oops, we forgot to initialize `d`. Obviously the compiler would notice that, right? No, the compiler is perfectly fine when we use declaration merging to copy the properties from `Foo` to `Bar`. This is an issue. We could avoid this by going back to the old method of individually declaring every single property, but that's cumbersome! 

## 💻 Use Cases
Currently, one has to either abandon using declaration merging and use duplicate properties, or lose the ability to check for initializations.

**Comment by fatcerberus** [comment]
For what it's worth I don't think this is a supported use case for declaration merging.  Critically, this will behave improperly in codebases that have `useDefineForClassFields: true` (i.e. ES-compliant class fields) or that target an ES version with native class fields, because the class will be emitted without those properties in its definition:

```ts
interface Foo {
    a: string;
    b: string;
}

class Bar implements Foo {
    a: string;  
    b: string;

    constructor() {
        this.a  = 'a';
        this.b = 'b';
    }
}

interface Baz extends Foo {}
class Baz {
    constructor() {
        this.a  = 'a';
        this.b = 'b';
    }
}
```

`target: "esnext"` emit:
```js
class Bar {
    a;
    b;
    constructor() {
        // [[Define]] semantics
        this.a = 'a';
        this.b = 'b';
    }
}
class Baz {
    constructor() {
        // [[Set]] semantics
        this.a = 'a';
        this.b = 'b';
    }
}
```

Particularly in library code, this difference may matter and could surprise people extending your class.

**Comment by RyanCavanaugh** [comment]
The problem is that the declaration merging, like you're doing here, *is the way* you should tell TypeScript about properties which are initialized/created/etc outside the boundaries of your class definition. This code already has a meaning, and the meaning is "I don't want you to warn me about those fields".
