### ISSUE TITLE
TypeScript extension crashes

### ISSUE THREAD

**Issue by ben-at-soul-refiner** [microsoft/TypeScript#52275]
Type: <b>Bug</b>

# The JS/TS language service crashed 5 times in the last 5 minutes.

Using TS version 4.94

Running on WSL

code -v:
```
1.74.3
...
x64
```

tsconfig:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": "./",
    "rootDir": "./"
  },
  "include": ["./**/*.ts", "./**/*.tsx", "next-env.d.ts"],
  "exclude": ["node_modules"]
}
```

The extension either hangs or crashes, making intellisense unusable. 
This issues has been happening over the past few days.

I've tried removing all my installed extensions (rm -rf ./vscode-server), installing new extensions (https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next), and changing typescript version (upgraded to 5). 

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.41GB (17.06GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/ben/soul-refiner/Soul-Refiner-Admin --remote=wsl+Ubuntu --crash-reporter-id bb5d37f4-6f31-4d55-8064-43088f940e0b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 3193)|
|Memory (System)|15.33GB (12.63GB free)|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.72.0
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by mjbvz** [comment]
@ben-at-soul-refiner Thanks. Unfortunately the only error I see is `SIGABRT`  which isn't very helpful

Moving to TS to see if they have any ideas

@ben-at-soul-refiner If you are able to, could you also share logs when using TypeScript 5.0+ in your workspace?

**Comment by mjbvz** [comment]
It could also be an out of memory issue. @ben-at-soul-refiner When the crashes happen, do you notice memory usage being high?

**Comment by ben-at-soul-refiner** [comment]
Memory usage is not higher when crashes happen -- VS Code stays around 415MB

**Comment by RyanCavanaugh** [comment]
We'd really need a concrete repo to know what's happening here.

**Comment by ben-at-soul-refiner** [comment]
I'll try to create a replica of the problem in another project

**Comment by ben-at-soul-refiner** [comment]
I'm closing this because I cannot replicate this issue outside of this particular repo. I have a hunch that it is a memory issue like @mjbvz suggested
