### ISSUE TITLE
optionalReplacementSpan not update when hit a incompleteCompletionsCache?

### ISSUE THREAD

**Issue by jadestrong** [microsoft/TypeScript#52270]
https://github.com/microsoft/TypeScript/blob/8586c995b57747bcc9abdfed901bea776644b5fb/src/services/completions.ts#L667-L671
Here when hit a cache, will directly return the cached one, but in the `continuePreviousIncompleteResponse` function, not sync the `optionalReplacementSpan`' value, so there will always return the cached `optionalReplacementSpan` value.
https://github.com/microsoft/TypeScript/blob/8586c995b57747bcc9abdfed901bea776644b5fb/src/services/completions.ts#L995

But `typescript-language-server` and `volar` all use this field to calculate  CompletionItem's `textEdit` (InsertReplaceEdit) field.
https://github.com/typescript-language-server/typescript-language-server/blob/d8b4cb698b6b74f12edb0a19e6c28b391cc0e985/src/completion.ts#L104

https://github.com/volarjs/plugins/blob/3c62a892e334806d2b76cd66d9c4670179d21398/packages/typescript/src/services/completions/basic.ts#L51-L54

So,  should this field also be updated here? or is typescript-language-server need calculated in other ways?

Here is the first time hit a `isInComplete`, the `optionalReplacementSpan`' end is `{line: 100, offset: 18}`

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/18475217/212801083-b54072d2-137f-48f6-8104-ac5968a37a00.png">

Then the following inputs hit the cache, trigger position is changed, but `optionalReplacementSpan` are not updated 
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/18475217/212800140-1ec1dc76-012e-479b-aa35-5d2fc9cc76db.png">

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/18475217/212799955-48e39d83-7632-40f0-8faf-d721983d6ca1.png">

**Comment by andrewbranch** [comment]
Yeah, we should be updating that field. Thanks for the detailed investigation. Feel like opening a PR?
