### ISSUE TITLE
Type narrowing not working in else statements

### ISSUE THREAD

**Issue by mon-jai** [microsoft/TypeScript#52272]
# Bug Report

### 🔎 Search Terms

- Narrowing
- Else statements

### 🕗 Version & Regression Information

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBAYg9nKBeKAKAUFLUDeUB2AhgLYQBcUARIZVAD5UBGlA3FAJYDOAgnAE4AhCsD4BXaAF9M2BniKkKlAMasOnAMLCxk9AEp06ACYQlAG0J9opiMCgAzBBXhwD7O2gdwAdPOhIU1LR0DJ4+JH4BzLq40lhKcPiccNZepnAA5qihXLyC+hJQEKac0DixUPGJtr7I9ghhpFAA9E1QACrgEADKSnzsYLaW8en47ABe0MAAFoS2oTX+VCpQhPiGUNMQlg6WADQE4cgBKuWVSSlpmdka0S1QAKJ8fPxQlmD8wBCG+yA2UADu0AA1vg4P8NjM5vUuOojhttOgpEA)

### 💻 Code

```ts
type Foo = (
    { name: "a" | "b"; isAorB: true }
    | { name: "c"; isC: true }
)

declare let foo: Foo

if (foo.name == "a" || foo.name == "b") {
    console.log(foo.isAorB)
} else {
    const name = foo.name // TypeScript recognize that foo.name == "c" and therefore, name == "c"
    console.log(foo.isC) // Error reported, yet we know that foo.isC == true
}
```

### 🙁 Actual behavior

TypeScript failed to recognize `foo.isC`.

### 🙂 Expected behavior

TypeScript recognize that `foo.isC == true`.

**Comment by fatcerberus** [comment]
I’m not sure https://github.com/microsoft/TypeScript/issues/43026#issuecomment-789220358 applies here since that involves a `&&` in the initial `if` branch which can be decomposed.  The `else` here should be atomic.

**Comment by MartinJohns** [comment]
Fairly certain it does apply. When `foo.name == "a"` is falsy, there's nothing the type of `foo` can be narrowed to. Same applies for the other expression.
