### ISSUE TITLE
nonce property is missing, issue with Typescript from 4.6.3 to 4.8.4 

### ISSUE THREAD

**Issue by konsalex** [microsoft/TypeScript#52273]
# Bug Report

### 🔎 Search Terms

nonce, react, typescript upgrade, required property

### 🕗 Version & Regression Information

- This changed between versions 4.6.3 and 4.8.4

### ⏯ Playground Link

[Playground link with relevant code](https://codesandbox.io/s/zen-archimedes-s765zy?file=/src/App.tsx)

*Code-sandbox link works appropriately, the issue appears in the local environment

### 💻 Code

In local env install `@neo4j-ndl/react@1.0.0-alpha-5a0ff3c`  and then try to use in a react setup:

```tsx
<Checkbox
                      checked={onlineFilter}
                      onChange={() => dispatch("toggle_online")}
                      label="Online"
                    />
```

### 🙁 Actual behavior

Old type definition: https://cdn.jsdelivr.net/npm/@neo4j-ndl/react@0.17.1/lib/types/checkbox/Checkbox.d.ts
New type definition: https://cdn.jsdelivr.net/npm/@neo4j-ndl/react@1.0.0-alpha-5a0ff3c/lib/types/checkbox/Checkbox.d.ts

![CleanShot 2023-01-17 at 15 06 25](https://user-images.githubusercontent.com/12672541/212919659-4b569724-fe1c-4b79-8d0b-018a7a586af5.png)

```ts
Property 'nonce' is missing in type '{ checked: boolean; onChange: () => void; label: string; }' 
but required in type 
'Pick<RadioAndCheckboxProps, "name" | "role" | "id" | "min" | "max" | 
"onChange" | "form" | "label" | "slot" | "style" | "title" | "pattern" | "children"
 | ... 277 more ... | "labelBefore">'.ts(2741)
```
![CleanShot 2023-01-17 at 15 12 58](https://user-images.githubusercontent.com/12672541/212921165-7ad9312e-b6a9-4f43-84e6-d42993ff93f3.png)

### 🙂 Expected behavior

To avoid complaining about `nonce` as a property that is missing

**Comment by MartinJohns** [comment]
TypeScript is not responsible for the type definitions released in `@neo4j-ndl/react`.

**Comment by konsalex** [comment]
I get it @MartinJohns , I’m mainly concerned if there is away to avoid this type incompatibility, as in the component library we use TS`4.9`, and some consumers may use `4.5` which results in the warning I attached.

is there any way to avoid having a requirement for the consumers to upgrade their TS version or is it mandatory?

**Comment by RyanCavanaugh** [comment]
Consumers don't necessarily have to be using the same version of TypeScript you are. If you aren't using new features, there will generally not be any issues. You can use `downlevel-dts` tool and/or the `typesVersions` package.json field to provide backward-compatible .d.ts files.

**Comment by konsalex** [comment]
@RyanCavanaugh used the `downlevel-dts` but the issue still persist 🤔  And that makes sense as `nonce` is a property rather than a new TS feature. 

In that case the only solution I can think of is to compile with different `typescript` versions and include the `typesVersions` in `package.json`?
