### ISSUE TITLE
Syntax sugar - allow constructor without body

### ISSUE THREAD

**Issue by PLEEROCK** [Microsoft/TypeScript#5227]
With nice feature typescript has which allows to define class properties right from the constructor parameters Im facing one issue: ugly `) {  }` that makes code *ugly*

```typescript
constructor(
        private firstService: FirstService,
        private secondService: SecondService
    ) {
    }
```

Can we add some syntax sugar and allow to define constructor without body like this:

```typescript
constructor(
        private firstService: FirstService,
        private secondService: SecondService
    )
```

or

```typescript
constructor(
        private firstService: FirstService,
        private secondService: SecondService
    );
```

**Comment by RyanCavanaugh** [comment]
A signature followed by a semicolon is already the syntax for an overload signature. We don't want it to mean two different things.
