### ISSUE TITLE
`{}` does not satisfy the constraint `{ [x: string]: number; }` in js files but not in ts files.

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#52285]
# Bug Report

### 🔎 Search Terms

jsdoc TS2344 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `constraint`

### ⏯ Playground Link

[js playground link](https://www.typescriptlang.org/play?ssl=14&ssc=29&pln=14&pc=35&filetype=js#code/PQKhFgCgAIWgBALgUwLYAcA2BDF0De+A2gB4Bc0AzogE4CWAdgOYC6FDArqgEbI0C+-aABUosYFADGOSpWgAxAPaKCUKPzWRQcJAE90yAksUAefPwB8QkMGjBbAM0bIpihtWgloAXmgNkAO4KygAUAJQA3JqSbh66PgT8UZBQ2giI+ob4xiYZBooO0LpW4qm20BWVVRUAenX1dQC0zY0iAMoATADMACw9IpnQAOTmQ9AAJorIcgyKiFS4dJQO8YgAFi5a5dU7uzsx7rTYjPMj0KQU1PTMbH5cvDQR0PxDrofQAF4J-kHG4RFAA)
[ts playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28A8AVaBTAHgF3QOwBMYBvAbUwC5oJsAnASzwHMBdKvAVwFsAjdWgL4A+aMQEBYAFBTg8PDWiZoVBMjEiAvNDzoA7nEQAKAJQBuaAHoL0AGaN0UmXIUBPaFrGnHk2fOzQAL2UDZGwXAAd0eBtoF01tPRCTcytoMBAIeFt7IA)

### 💻 Code

```js
/**
 * @template {{[x: string]: number}} T
 */
class Foo {

}

/** @type {Foo<{}>} */ // fine
const x = new Foo();

const y = {};

/** @type {Foo<typeof y>} */
//             ^^^^^^^^---- TS2344 Type '{}' does not satisfy the
//                          constraint '{ [x: string]: number; }'
const z = new Foo();
```

### 🙁 Actual behavior

TS2344 Type '{}' does not satisfy the constraint '{ [x: string]: number; }'

### 🙂 Expected behavior

No error, because the equivalent TypeScript code doesn't emit an error either:
```ts
class Foo<T extends {[x: string]: number}> {}

const x : Foo<{}> = new Foo(); // fine

const y = {};

const z : Foo<typeof y> = new Foo(); // also fine
```

**Comment by MartinJohns** [comment]
Most likely because in JavaScript the object literal `{}` gets special behavior: its type can "grow" by assigning properties, e.g.

```typescript
// Works just fine!
const y = {};
y.abc = "test"
```

When your variable `y` is actually typed `{}`, then the code will behave as you expect:

```typescript
/** @type {{}} */
const y = {};
```

**Comment by RyanCavanaugh** [comment]
TS and JS checking are intentionally a little different in some cases, including this one.
