### ISSUE TITLE
Capture type info in a variable's type

### ISSUE THREAD

**Issue by Etchelon** [microsoft/TypeScript#52289]
# Suggestion

Would it be possible to capture type info on one variable inside the type of another one?
Most telling example:
```
const useNumber = (n: number) => { ... };
const obj: { number?:  number } = getObj();
const hasObj = obj.number != null;
if (hasObj) {
  useNumber(obj.number); // error: number | undefined not assignable to number
}
```
I often write variables like `hasNumber` to make the code more explicit, and it would be nice if the semantic meaning of their names was reflected in the type system by capturing type info on other variables.

## 🔍 Search Terms

capture type information variable

## ✅ Viability Checklist

My suggestion meets these guidelines:

* ❓ This wouldn't be a breaking change in existing TypeScript/JavaScript code
* ✅ This wouldn't change the runtime behavior of existing JavaScript code
* ✅ This could be implemented without emitting different JS based on the types of the expressions
* ✅ This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* ✅ This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
This should already work but `obj.number` must be defined as `readonly`.  See https://github.com/microsoft/TypeScript/pull/44730.

**Comment by Etchelon** [comment]
Great to know, thanks! I checked and it works, event more than 1 level deep [apparently](https://www.typescriptlang.org/play?ts=4.9.4#code/JYOwLgpgTgZghgYwgAgJIHkBGArCCzIDeAUMmciAK4C2A-AFwU2bQDcp5IEAzpACYNk6asDAAeDDjxgANMgBEXXhD7yAfOwC+xYggD2IXsgDmEMFmzIAvMgAUASkaTc+a2rslyTaowAsAJhkOMiV+RkJtTXt2XQMjUzAAJXQLaztHZESIOD4DABsATwkLaXcrd1tPTho-f2IomP1DAkpuCAA5GjTbEEYqahYoezciYOQm7j08iAA6PL1jSopkBvrGuII9NISLB3YJgig9LZsE5N3onQPkPQAJOG5O6jS9Gf7kAEIbKjy8-Y3kEc7g8nmkgW8ul8mL92MAYHZgY8aMNWh0aLZXv1LnC7ED7kjqCi2k9bOCsetmhQePx8aCbJjqSpaBDnlCfn9YpSju1GXxaV0bGTecz3mzKDDiDierz+YTkKiSQzlHwWdj4aS9DzlbKiWjqBqlfxVf8uZree09GB2sA8gBBEB8kECwHHN68z7fcV5ZAAMh9LsNKhZHuhHKl3PNlutdodOvlxPRQuVxquAMI3k0LxNRn6qEeUZtaVFnolUtz+atNt1JPJqcp6f6jCBoMzguO2cOxyeeYtle9bc1kJLYfVzZoPYLeWria7yNYQA)!
