### ISSUE TITLE
Wrong generic type parameter inference/calculation

### ISSUE THREAD

**Issue by TelephoneTan** [microsoft/TypeScript#52286]
```
TS2345: Argument of type 'number' is not assignable to parameter of type 'never'.
```

[Online Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogjgVwIYBsA8AVAjAGihgJgD4oBefLKCAD2AgDsATAZ3wKgH4oAKQq2hiwqcowAE4JoALigAzVMwgBKKDPkpFAbgCwAKFCQoAQXogAYgnoBjYAEsA9vTI8AdG6QykplaRJeQOvrg0AAiELK29BCMmMEk5BjB-HRMrJaM4ZHRIuqKqqISEIEG0ABy9sClCCjoiZDx+Ek0KULpmVGMelA5ChBd+XXQzYKs9NUo-Vy5fbrdMuKSxUlGADIVAPKymA0AShBW9mIx-ngYRIF6JVAAwo7MCzaHzgDeUFEA7q7uYgDmzJ7eAEgKAAXyWhlu9HuEkeYiMYjESGB5HhiJAaEh0IQsPOlySmIewEOK1sAGsIABlWwAWzAKAgg0YAAUxPYwGR+gAfG53QmHVFIrk8qF8sRCsY1IVtCIdcHQEwgdbAAAWEDEVNp9MZLLZzn8cqgGrpDOCzNZ7PIBJhRLEJPJRq1pp17O5CqVqvVNON2vNBudYXk1WAetMBtumpoPt15Ge-RKHBkDpNkDNbMC3QygZQwATUH94SQQfTUDEEEQtlLuYARvZ7PSvFBuRKUIEwXjDFGLYavY6U87GzyI9ROwaAKr0EqprvQyI-C5BDtO80k+7OVYbLad3EL6DjyfOlfBlEIpFoPdLtnb9vQA+2VcJC9gQ8D8995d34Bh3nW4lkyk95NomdQY0H6DBkhGYUsVhO1-wjTs9AacDhlSKDRQFEBJigABJEUvCsQDMAAbTGakqzVABdIh+hkZCBFQq1sRtLDcPufDCLOGioH1a9jFMd01STTsQLolpWDdFVBIArdnAwecrgANVQWxGAkj0A0LbNQNmRpDBQoQhMfHB+g0oMINQhULGsOxHEQ2SmnooQ1Kk+DHyw+BkHQPZgAQMR6BA0zsyIPBnM9Vy3zZES4hIfTWAWGZum6LgPNQNAmSQRFqQgOgxGYNBAuAYKoCIqj+jmORei46YDSUlAVMsywbAcegCu07pBnMgzpKMkyCzM2K+PMRqbPoOyHz0xzxNMKymtsnTksQVLvN8-zgnyvqgrwZa-Ki+oYsmgpJDKkQUvQdLMuytU8oKorzqQLKcrywYiGonTyumLjavq-jJLEVrBjwG6auUxhGJgv9WrAhyxO7cKgPNYydIKzqpqG6zmrG3ShgOsGbVgwyIrAdzFvQY7um21bIHWrNCsRxLEtx397W6wndogV76f2mH4uOhbPLSjL7su3Lqc02nitKt78g+nSZC+1TpuG5r-uCQGNsK4G6sYGaRsZv71barGUdh70eqR9XjYa9G5qQ6HIJ15q9awnnZageW9dglXIDVmnt0UkHBhMRhIZ0jqBoJ+HdW5aUskYOmoGRgb8xpgcY46TGA1j0Wgy5yCXaShOLYGq3ZtGqWuHKSpxliepjfz+mRHlh3HD1r2IB9sWOYbmRToFi7HuzzaJa797Ktd+LNZU8NjWHR9MGN6f6VnwmGnlwOmBD9qiIAIhKbeKPjjAd8zMX98QyfGE7eeBpkhIF-sIcEPmt2QcXyM58413RMgiOp2dwoqq9ANAAWQyqSGASArDKivkyY2nZDwNFjDpIi7JIhQHJCAewsg8wUTlgHOeTIUFUVbBfW89w0rGzIYVZwsCBqvkjk+D8-8jqu1oQdeBTDn7TGNqAsQ4DIHQIIUQIiGCsFQF4fwqBMCiAUV5hVDQCVErzAAa7aqvEMCFEsr0UoEAABuapr4HRrHWCAXgkJ10KCIfw+Qoj6LEAaHRdj1hwlMNsWSxtbFqhEJ4sQ+QeK6FkErRwUAwDmgoUnd89wiDcH6PYUkMhHFqmcQqTAmjpraL0QY+WVC0ovWCrEmQTI9BKEKVAJB3RSw+T8lAewrY9A0DAIcYMJ8zKhLZNwXAZT+hGBkOUxKJQZAACFaz1noPHCpZYEAVmiMoyQ4yoAtOzNwEpUBjGjK6VLCZVSnAT2OiCeO+z+iDN6cdAZhpxCznmYs4AyyZAznoD8DZDcSzZRWlAbeqoaj2G3sWbohydL-O6NcE5UszkUguQ8q56tblQHuY8vp9NKlvO3u8Q4KBGA-L2Qc+OIQQX0zBRCn42L+gwDxf04IiZCXzNLOWUsjBZnt36P8kEShAhAA)

Code:

```ts
type Equal<T1, T2> = T1 extends T2 ? (T2 extends T1 ? true : false) : false;
type AnyFunction = (...a: any) => any;
type Defined<Type> = Type extends undefined ? false : true;
type NotNull<Type> = Type extends undefined
  ? false
  : Type extends null
  ? false
  : true;
type ALotOf<T> = Record<any, T>;

type Constructor = { new (...args: any): any };
type ConstructorArray = Array<Constructor>;
type ConstructorLikeSimpleTypedProp =
  | ConstructorArray
  | Constructor
  | null
  | undefined;
type AnyOtherSimpleTypedProp = any;
type SimpleTypedProp = ConstructorLikeSimpleTypedProp | AnyOtherSimpleTypedProp;
type PropDefault = any;
type ComplexTypedProp = {
  type?: SimpleTypedProp;
  default?: PropDefault;
  require?: boolean | null;
};
type TypedProp = SimpleTypedProp | ComplexTypedProp;
type UntypedProp = string;

type TypedPropList = ALotOf<TypedProp>;
type UntypedPropList = Array<UntypedProp>;

type PropList = TypedPropList | UntypedPropList;
type ConstructorLikeSimpleTypedPropType<
  T extends ConstructorLikeSimpleTypedProp
> = T extends ConstructorArray
  ? InstanceType<T[number]>
  : T extends Constructor
  ? InstanceType<T>
  : any;
type AnyOtherSimpleTypedPropType<T extends AnyOtherSimpleTypedProp> = T;

type ValidAnyOtherDefault<
  Type extends SimpleTypedProp,
  Default extends AnyFunction
> = Type extends AnyOtherSimpleTypedProp
  ? Equal<ReturnType<Default>, AnyOtherSimpleTypedPropType<Type>> extends true
    ? Equal<Parameters<Default>, []>
    : false
  : false;
type ValidAnyFunctionDefault<
  Type extends SimpleTypedProp,
  Default extends AnyFunction
> = Type extends AnyFunction
  ? Equal<ReturnType<Default>, ReturnType<Type>> extends true
    ? Equal<Parameters<Default>, Parameters<Type>>
    : false
  : ValidAnyOtherDefault<Type, Default>;
type ValidConstructorLikeDefault<
  Type extends SimpleTypedProp,
  Default extends AnyFunction
> = Type extends ConstructorLikeSimpleTypedProp
  ? Equal<
      ReturnType<Default>,
      ConstructorLikeSimpleTypedPropType<Type>
    > extends true
    ? Equal<Parameters<Default>, []>
    : false
  : ValidAnyFunctionDefault<Type, Default>;
type ValidFunctionConstructorDefault<
  Type extends SimpleTypedProp,
  Default extends AnyFunction
> = Type extends FunctionConstructor
  ? true
  : ValidConstructorLikeDefault<Type, Default>;
type ValidTypeAndDefault<
  Type extends SimpleTypedProp | undefined,
  Default extends PropDefault | undefined
> = Defined<Default> extends true
  ? Default extends AnyFunction
    ? NotNull<Type> extends true
      ? ValidFunctionConstructorDefault<Type, Default>
      : Equal<Parameters<Default>, []>
    : false
  : true;
type ValidComplexTypedProp<T extends ComplexTypedProp> = ValidTypeAndDefault<
  T["type"],
  T["default"]
>;
type ValidTypedProp<T extends TypedProp> = T extends ComplexTypedProp
  ? ValidComplexTypedProp<T>
  : T extends SimpleTypedProp
  ? true
  : false;
type MarkEachTypedProp<P extends TypedPropList> = {
  [p in keyof P]: ValidTypedProp<P[p]>;
};
type ValidPropList<P extends PropList> = P extends UntypedPropList
  ? true
  : P extends TypedPropList
  ? false extends MarkEachTypedProp<P>[keyof MarkEachTypedProp<P>]
    ? false
    : true
  : false;
type TrueAnyFalseNever<T extends boolean> = T extends true ? any : never;
type NeverOrAny<T> = T extends never ? never : any;
function prop<P extends PropList>(
  ok: NeverOrAny<TrueAnyFalseNever<ValidPropList<P>>>,
  o: P
): P {
  return o;
}
export default prop(1, {
  A: {
    type: Boolean,
    required: true,
    default(): boolean {
      return true;
    },
  },
  B: {
    type: String,
    default(): string {
      return "hello";
    },
  },
  C: {
    type: String,
    default(): string {
      return "world";
    },
  },
  D: {
    type: String,
  },
  E: {
    type: String,
    required: true,
  },
});
```

**Comment by RyanCavanaugh** [comment]
There's no way for me to validate that you've written this entire program correctly vs found a bug in TS. Please file a new issue with a *short* repro that clearly demonstrates why you think there's a bug.

**Comment by fatcerberus** [comment]
@RyanCavanaugh At the very least this feels like a bug:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/4097841/213304165-b69b6add-f10a-4083-b6f3-28c2763c5df4.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/4097841/213304314-e85c6636-6433-49a9-94e4-b2b74e62f084.png">

**Comment by TelephoneTan** [comment]
> @RyanCavanaugh At the very least this feels like a bug: <img alt="image" width="423" src="https://user-images.githubusercontent.com/4097841/213304165-b69b6add-f10a-4083-b6f3-28c2763c5df4.png"> <img alt="image" width="636" src="https://user-images.githubusercontent.com/4097841/213304314-e85c6636-6433-49a9-94e4-b2b74e62f084.png">

I guess you are using WebStorm or any other JetBrains IDE, I am using WebStorm, and after digging a lot, I've found that it's an IDE-Bug, the TS online playground shows everything correctly, but WebStorm does not.

The `ok` parameter should really be of type `never`, but WebStorm thinks it should be of type `any`, so things get confused.

**Comment by fatcerberus** [comment]
@TelephoneTan Those screenshots were from the TS playground.

**Comment by TelephoneTan** [comment]
> @TelephoneTan Those screenshots were from the TS playground.

Emmm, then that must be a bug...🤣

**Comment by fatcerberus** [comment]
Yes... that's what I said.
