### ISSUE TITLE
False expression: Unsupported decorator target

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/TypeScript#5229]
Hi,

From 1.5 to 1.6 migration, we have a project that doesn't compile anymore and it give us only this tsc error message:
Debug Failure. False expression: Unsupported decorator target.

There is the faillure stack trace I get by adding a ts.sys,write of the stack where the error occur:

    Error: Debug Failure. False expression: Unsupported decorator target.
    at assert (:724:17)
    at fail (:729:13)
    at getEffectiveDecoratorFirstArgumentType (:16779:21)
    at getEffectiveDecoratorArgumentType (:16842:17)
    at getEffectiveArgumentType (:16855:17)
    at inferTypeArguments (:16660:21)
    at chooseOverload (:16985:33)
    at resolveCall (:16919:17)
    at resolveDecorator (:17144:13)
    at getResolvedSignature (:17160:21)
    tsc.js(29826, 17) JavaScript runtime error : Debug Failure. False expression: Unsupported decorator target.

I try to comment partially decorator to find the problem wihout success.

Can't share source to help. Maybe if it help I can share my decorator signatures.

Thanks.

**Comment by rbuckton** [comment]
I need more context to isolate the issue. Could you provide a simple sample that reproduces the bug?

The debug assertion is thrown when the declaration being decorated is not one of:
* A class declaration
* A class expression
* A parameter
* A property declaration
* A method declaration
* A get accessor
* A set accessor

However, if the declaration is not one of the above the error should be reported elsewhere without throwing an exception.

**Comment by sebdoucet** [comment]
Don't know... I search the problem and we use lot of class method decorators and it compile successfully randomly so I have to restart visual studio each time to ensure the problem is fixed and for the moment, no success.

I about to give up the migration to 1.6 and hope it works on 1.7 because I spent already to must time at finding the problem.

**Comment by mhegazy** [comment]
>  it compile successfully randomly so I have to restart visual studio each time to ensure the problem is fixed

so where did you get the tsc stack above? is this a compile on save only issue? when does it fail, and when does it work? would you mind trying an instrumented build, with some additional diagnostics code?


> I about to give up the migration to 1.6 and hope it works on 1.7

1.7 is available in `typescript@next`, if this does not work today, then it is not going to work when 1.7 goes out. we would appreciate your help diagnosing the issue.

**Comment by sebdoucet** [comment]
Compile on save are disabled in every of our project. I get this stack by adding that at (29826, 17):

    ts.sys.write(e.stack);

Give me the instrumented build then I try it immediatly.

**Comment by sebdoucet** [comment]
If this can toggle lights for you there is decorators signatures of this project:

    decorator1(channelType: SomeClassConstructor, ...args: any[]): ClassDecorator;
    decorator2(name: string, optionalDependency?: CustomType): PropertyDecorator;
    vproperty(type: CustomEnum, defaultValue: any, opts: CustomOptions, optionalCallback?: CustomCallback): PropertyDecorator;

Where:
    interface SomeClassConstructor{
        new ():CustonType;
    }
    interface CustomOptions{
        requiredOption: number;
        flag?:boolean;
        ...etc
    }
    interface CustomCallback { (sender: any, args: CustomArgs): void; }

I also can share one file privatly where I suspect problems where decorator are on static property and some refer to other property.

**Comment by mhegazy** [comment]
Thanks! Mhegazy at Microsoft

**Comment by sebdoucet** [comment]
In the file I sent you, it seem to work when only 9 decorators are uncommented. I try many scenario and it just fail when 10 decorators are enbled.

**Comment by sebdoucet** [comment]
After trying many combination, I confirm it build everytime when I have less than 10 decorators in this class and it fail at 10 and more.

**Comment by Wintermoose** [comment]
We've run into similar case (unfortunately I cannot share the full code, and my first attempt to isolate it failed - the error isn't triggered just on the source file itself). 

The offending decorator was applied to property of the class. The source in question contains 2 classes (the main one containing the decorator, followed by small angular factory that creates instances of the main class). After testing renaming the property and making another class with identical code and.. //fast forward//... it turned out the code will compile correctly if I swap the order of the classes (note: the factory refers to the main class, there is no reference the other way around).

Both classes contain some property decorators, and the factory has class decorator too. The main class includes one ES6 template string. We're compiling to ES5 target.

Maybe this will help a bit
