### ISSUE TITLE
organize import sort order is incorrect

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/TypeScript#52292]
Type: <b>Bug</b>

after installing the nightly extension and selection the vscode Typescript version the import organized in incorrect order
![image](https://user-images.githubusercontent.com/9264813/213179242-0a0549c1-39bc-4379-b340-c7b068ed8a90.png)

find the SS for the incorrect import statement.
![image](https://user-images.githubusercontent.com/9264813/213179517-2ee937e3-fb36-4ff8-9a9b-5a3a11fc3af9.png)

the issue does not appear when switched to workspace version of typescript
![image](https://user-images.githubusercontent.com/9264813/213179693-2f6a5058-5b86-4e4b-b4ca-c943a4154540.png)

![image](https://user-images.githubusercontent.com/9264813/213179386-2f4e18db-1dbf-45a3-bf0e-16d7df5d349b.png)

Extension version: 5.0.202301160
VS Code version: Code - Insiders 1.75.0-insider (1379f0375440df946adc62f7afb8375dd45d5adf, 2023-01-17T05:21:07.217Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (3.23GB free)|
|Process Argv|--crash-reporter-id e5294b27-02c9-4438-b8f3-90acb1091b3b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by RyanCavanaugh** [comment]
(comment from @andrewbranch) That's the new default—ASCII order—which matches what eslint enforces. The default is actually to auto-detect if you are currently case-sensitive or case-insensitive and match that. But if there is no detectable sort, we did switch the default to case-sensitive.

This will be a configurable option in VS Code in the near future

**Comment by fatcerberus** [comment]
I acknowledge this is entirely subjective but I do greatly prefer the original order where the `camelCase` imports came first.

@RyanCavanaugh Both sorts in the OP look to be case-sensitive - the difference seems to be whether the lowercase or uppercase imports come first.

**Comment by andrewbranch** [comment]
It’s just a coincidence in the old order that the lowercase letters are alphabetically before the uppercase ones. It was not case-sensitive before.

**Comment by sanket-bhalerao** [comment]
> 

how do i make it case insensitive?

**Comment by fatcerberus** [comment]
> This will be a configurable option in VS Code in the near future

**Comment by sanket-bhalerao** [comment]
:(
my team is habituated with the case insensitive organize, now every time I commit I get a review comment for the import not being in proper order :D

is there any ticket where created for this where it can be tracked?

**Comment by DanielRosenwasser** [comment]
I don't know, but in the meantime I think you can specify

```jsonc
{
  "typescript.unstable": {
    "organizeImportsIgnoreCase": true,
  }
}
```

**Comment by andrewbranch** [comment]
Yep, I totally forgot that was a thing (that I made 😄) until Ron was using it recently. That should work

**Comment by krisztianb** [comment]
In which file do I have to set the `typescript.unstable` option?
