### ISSUE TITLE
Generic type inference depends on how object method is declared

### ISSUE THREAD

**Issue by pawbor** [microsoft/TypeScript#52306]
# Bug Report

### 🔎 Search Terms

function parameters infer generic inference object method 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about function parameters bivariant

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/MYewdgzgLgBAbgQwDYwLwwN4CgYwPR664B6A-DjAB4CMAXDABRz0YwBmII90ATgJZgA5jAC+ASjQA+TKIA0FSgCZ6TFu07co-IQG4YAIwQ96YAK4BbfQFMeoiamnYiMUJBBIrAOiQhBDAOSGPP6y8J5BYhQiWCIwCBAu4NA6WFgEMADC8VYw1FhQAJ4ADjkAQiA0ADwACtLorDQMRfTVYvRwIHwAJnpKTS1t8J1doilYbKZgwFB84DBQ1DWSDPoV9OVVtRJOMDxWUKY8YAYVKdFYrtDw1Gjz1EzIYinpRGRYcNSefawcXDD+AHcABYIKBWOA2fx2PTpAAqAGUYBAgSBTEgRlAgTwQACYECbDl9KZYF0QFYEmAQLAICAYAAZADyAHF6AAiIKs0IwSZdKxsARWEapNKELIQHKKfLFMoVRRLW4NOiMZowVpSIbdXrKZUDdUdbqjVITKYzOZQOW1FZrGAbC2SbYUPYHI4nShnVKXWBwRS3c0PJBPEXON7er6KBg-DT-YGg8GQuz4QgI+ZYnEJeIwKyUErTQVAA)

### 💻 Code

```ts
const val = {
  x1: (v: { foo: string }) => { },
  x2: (v: { foo: string; bar: number }) => {
    console.log('bar', v.bar)
  }
} as const;

// Case 1
type Box1<P> = { x1(p: P): void; x2(p: P): void };

function t1<P>(box: Box1<P>) {
  return box;
}

const v1 = t1(val);
v1.x2({ foo: 'whatever' }); // TS should throw here but does not so LOG: "bar",  undefined 


// Case 2
type Box2<P> = { x1: (p: P) => void; x2: (p: P) => void };

function t2<P>(box: Box2<P>) {
  return box;
}

const v2 = t2(val);
v2.x2({ foo: 'whatever' }) // TS throws as expected
```

### 🙁 Actual behavior

The inferred generic type depends on how object methods are defined.

### 🙂 Expected behavior

The inferred generic type should be consistent. IMO it should be the type inferred in Case 2, since it catches the incorrect usage.

**Comment by MartinJohns** [comment]
That's working as intended. Depending on the syntax the function is covariant or contravariant.

**Comment by fatcerberus** [comment]
@Andarist *Contravariant* parameters.  Sorry, had to correct that 😜 

For the record it used to be that regular function types were bivariant too.  `strictFunctionTypes` was eventually added to make functions properly contravariant in their parameters, but an exception was left in for methods because otherwise it would have broken array subtyping--and a lot of actual, real-world code in the process.

If you disable `strictFunctionTypes`, you get the consistency you're looking for - but the cure is probably worse than the disease because then *neither* case is an error.

**Comment by Andarist** [comment]
> @Andarist Contravariant parameters. Sorry, had to correct that 😜

Those words are too much alike 🙈 my mind is thinking one thing but my hands are typing the other thing

**Comment by RyanCavanaugh** [comment]
>  I reviewed the FAQ for entries about function parameters bivariant

Erm, did you? It's [in there](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant)

**Comment by fatcerberus** [comment]
@RyanCavanaugh To be fair that FAQ entry talks about function types in general being bivariant and doesn’t mention the current distinction between functions and methods under `strictFunctionTypes`
