### ISSUE TITLE
satisfies operator incorectly working for array of records

### ISSUE THREAD

**Issue by Patrick-Beuks** [microsoft/TypeScript#52304]
# Bug Report

### 🔎 Search Terms

satisfies; array satisfies; object satisfies; record satisfies;;

### 🕗 Version & Regression Information

This is the behavior in every version (4.9.0+) I tried, and I reviewed the FAQ for entries about satisfy, Array, Map and Record

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230119#code/C4TwDgpgBAysBOBLAdgcwEoQMYHt4BMoBeKTXAgHgGcEVUAaKGpNAPgG4AoT3ZGqfIizAcyAIbwQAGUT8SAb05QoAcmAQaASXUBbFQC4oAbXljDKsSsYAjc9ZUBfRvKzmsjgLpMxwWQDNEDVhaNDI8fCMPTgdvXyoAoLDKZjpGOBYMbHDI1m5efnUtXWIBIRFxSRkaADpC4G0IHVj-QKpgjKSIj3YgA)

### 💻 Code

```ts
type StringRecord = Record<string, string>;

const dictonaryList = {
  'testItem': [{a: 'a', b: 'b'}, {c: 'c'}] satisfies StringRecord[]
} satisfies Record<string, StringRecord[]>

const testItem = dictonaryList.testItem satisfies StringRecord[];
```
```
Type '({ a: string; b: string; c?: undefined; } | { c: string; a?: undefined; b?: undefined; })[]' does not satisfy the expected type 'StringRecord[]'.
  Type '{ a: string; b: string; c?: undefined; } | { c: string; a?: undefined; b?: undefined; }' is not assignable to type 'StringRecord'.
    Type '{ a: string; b: string; c?: undefined; }' is not assignable to type 'StringRecord'.
      Property 'c' is incompatible with index signature.
        Type 'undefined' is not assignable to type 'string'.
```

### 🙁 Actual behavior

`const testItem = dictonaryList.testItem satisfies StringRecord[];` gives an type error
`testItem` is of type `({a: string, b: string, c?: undefined} | {a?: undefined, b?: undefined, c: string})[]` and should not satisfy `StringRecord[]`

### 🙂 Expected behavior

dictonaryList does not satisfy `Record<string, StringRecord[]>`
testItem does not satisfy `StringRecord[]`

**Comment by Andarist** [comment]
The interesting observation here is that it does work with `exactOptionalPropertyTypes: true` but probably a little bit accidentally. 

The problem is that each inferred member of the union here gets assigned all of the properties of all union members, so we end up with properties like `c?: undefined;` or `c?: never;` (depending on the value of `exactOptionalPropertyTypes`). 

It feels like this isn't quite the intention of this code and that TS shouldn't try to infer the keys like that. The expected result would be to infer:
```ts
typeof dictionaryList // {
    testItem: ({ a: string; b: string; } | { c: string; })[];
}
```

**Comment by RyanCavanaugh** [comment]
An intended design goal of `satisfies` is that it shouldn't negatively impact the inferred type of the expression.

Something you can do today is:
```ts
const dictonaryList = {
  'testItem': [{a: 'a', b: 'b'}, {c: 'c'}]
}

for (const p of dictonaryList.testItem) {
  if (p.c !== undefined) {
    // do something
  } else {
    // do something else
    p.a.toLowerCase();
  }
}
```
If we gave a different inferred type under `satisfies`, then `satisfies` isn't fulfilling its goal anymore.

**Comment by Andarist** [comment]
Hm, I see - it is surprising in cases like that but I guess that it's straightforward to workaround this by moving objects outside of this array and using `satisfies` on them there:
```ts
type StringRecord = Record<string, string>;

const obj1 = {a: 'a', b: 'b'} satisfies StringRecord
const obj2 = {c: 'c'} satisfies StringRecord

const dictonaryList = {
  'testItem': [obj1, obj2] satisfies StringRecord[]
} satisfies Record<string, StringRecord[]>

const testItem = dictonaryList.testItem satisfies StringRecord[];
```

It's more source code but doesn't actually introduce any more runtime code - which is nice.

@RyanCavanaugh a little bit offtopic - what should happen here?
```ts
type StringRecord = Record<string, string>;

const arrOrTuple = [{a: 'a', b: 'b'}, {c: 'c'}] satisfies [...StringRecord[]]
```

Should this end up being a tuple? or should it stay as an array? I guess it might need to stay as an array for the same reason that you have mentioned - OTOH, the `[...A]` seems to be quite an explicit "hint" that the user wants a tuple 🤔

**Comment by jcalz** [comment]
Wait, I think I hit this but I guess it's not a bug?  I'd expect that one goal of `satisfies` is that if
`const x = epxr satisfies Type` compiles without error, then `const y: Type = x`  should also compile without error.  That is, `const x expr Type` should guarantee that `typeof x` is assignable to `Type`.  But that expectation is violated here:

```ts
type Type = Record<string, string>[];
const x = [{ a: 'a', b: 'b' }, { c: 'c' }] satisfies Type // okay
const y: Type = x; // error
```

I suppose this is just the weirdness around optional properties and `undefined` and there's nothing much to be done here, but boy is it surprising.
