### ISSUE TITLE
[Bug] satisfies operator is not satify in compile time 

### ISSUE THREAD

**Issue by amm834** [microsoft/TypeScript#52300]
# Bug Report

### 🔎 Search Terms

No issue or answer

### 🕗 Version & Regression Information

Version : Nightly Release to test 4.9 `satifies` operator

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230118#code/C4TwDgpgBAwg9gGzgJwM5QLxQETIgE2ygB8cBzPCAOyNOwCMEBXCbAbgChRIoAlAcQBCmKAG08+AFxQqTALb0IyADRQKEatNkKlqxiy3zFyALqcAxnCqpgUMAEMEEYMGhYA3hyhQJ00QCYAVkDVAAYwk2UvNUoqaWwAYlDQgDMU5Owo730IP3CofKDAyI4AXyhUe2AAS1QU6oh0XghLZHwAHngkNFUbZGqqMhI+IQA+Tg4AekmoQSZbAHdoKjgFqAALewA3aHsqKCYqfEbq5HtGaCVkFA2laABaKAByBycXCAA6CSecSyYEQhQRRQewVYD9QYfDiWay2CTwORgKzUWxYV7OVxfAgfKoAClCAEpOEA)

Then, see error at line 10.

```
Property 'at' does not exist on type '[number, number, number]'.
```

### 💻 Code

```ts
type Colors = "red" | "green" | "blue";
type RGB = [red: number, green: number, blue: number];
const palette = {
  red: [255, 0, 0],
  green: "#00ff00",
  blue: [0, 0, 255],
} satisfies Record<Colors, string | RGB>;

// But we now have an undesirable error here - 'palette.red' "could" be a string.
const redComponent = palette.red.at(0); // this one

```

### 🥵 Actual behavior
should working fine 

### 🤨  Expected behavior
cannot figure out

**Comment by whzx5byb** [comment]
I think the error at line 10 has nothing to do with `satisfies`. If you want to use `Array#at` you should set the target to `ES2022` or above.

**Comment by amm834** [comment]
> I think the error at line 10 has nothing to do with `satisfies`. If you want to use `Array#at` you should set the target to `ES2022` or above.

Of course yes, I am testing official example from documentation
However, it revealed bug

**Comment by fatcerberus** [comment]
Based on your code comment, I’m assuming you’re expecting the `.at()` call to fail because `palette.red` is allowed to be a string.  This is a misunderstanding of how `satisfies` works.

There is no bug.  `satisfies` doesn’t change the type of an expression, it only checks assignability, so TS knows `palette.red` isn’t a string.

**Comment by fatcerberus** [comment]
I have no idea what you're talking about.  The error has nothing to do with the types.  You're just not targeting an ES version that supports `at`.  If you do this then it works:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/4097841/213512824-4a9cafec-4432-47cb-ab8d-05b0e68f3b4c.png">

**Comment by amm834** [comment]
Ok now it is working well in both of of local and ts playground. I just upgraded to next latest version to work well with that operator
