### ISSUE TITLE
`noUncheckedIndexedAccess` failed when destructuring from a tuple with rest elements

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#52302]
# Bug Report

### 🔎 Search Terms

noUncheckedIndexedAccess destructuring tuple rest elements

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/C4TwDgpgBAcg9gOwKIFsygMrAE4EsEDmAgttgIYhQC8UA2gM474EA0UAdJyeSADyN5CAPgC6AKDEBjRIygDm9AFyxEqdCCyDipCtToByRBH1t9wAO5wTUMwAtsEY+OkJZDAAxt6ARi8AmLwBmET15QnoAbjEAemioeITEpISAPQB+MXj6d3ZgOABVMEhsAGEyeggACgBKTLlA3IKiiFLyqtrY9KA)

### 💻 Code

```ts
type NonEmptyStringArray = [string, ...Array<string>]

const strings: NonEmptyStringArray = ['one', 'two', 'three']
const [s0, s1, s2, s3] = strings;
//                  ^? const s3: string | undefined
  s3.toUpperCase()
//^? const s3: string
```

### 🙂 Expected behavior

`s3.toUpperCase()` shows type error.

### 🙁 Actual behavior

`s3.toUpperCase()` shows no error.
Note that `undefined` is correctly included inside the assignment statement but then lost.

Related: https://github.com/microsoft/TypeScript/issues/40657

**Comment by Andarist** [comment]
> Note that undefined is correctly included inside the assignment statement but then lost.

It's probably cause hovering at that position shows you the "declared type" - but when hovering over the identifier after this assignment you see the "flow type" (the result of the control flow analysis). So my educated guess is that the problem is in the CFA
