### ISSUE TITLE
type is too wide after check (Element implicitly has an 'any' type because expression of type 'string' can't be used to index type)

### ISSUE THREAD

**Issue by antonilol** [microsoft/TypeScript#52311]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMBpEATwHlEAeAFXhAA8MRVhD5CMYsqAOYA+ABQBrAFy9+goQBp4OAEYArGQG8A2hPiD4jALoyoqKgF8AlKeKkMPPVh6MA3AFgAUF7B4+y9XgAXnhNJBwcGQByFVgopShE6JUUqPgLD08IEAx4CWpg+CjECKjMrwB6CrzqGT4BYS8sRHhJAoNVNStQr3g++Cqaqjq5Rs9++F9UQhxsgDoIHCExTt1qIytMiy9K6vzh2QahJpa2qn18Tu7NXv6iEjJKWkQzpSvMicH9mQAiEpwfvAAD7wH6JKA-W59KYzeaLZarfYbLZeIA)

### 💻 Code

```ts
declare function assertKeyOf<T extends string>(k: string, obj: {[k in T]: any}): asserts k is T;

const obj = { foo: 'bar', aaa: 'bbb' };
let key = 'foo';

// key: string
if (key in obj) {
    // key: string
    console.log(obj[key]);
}

// key: string
if (key in obj) {
    assertKeyOf(key, obj);
    // key: "foo" | "aaa"
    console.log(obj[key]);
}
```

is there a reason why `key` is string inside the first `if` block? the `if` statement checks if the key exists in `obj`, so i expect it to be `"foo" | "aaa"` (`keyof typeof obj`) inside the `if` block

### 🙁 Actual behavior

inside `if (key in obj) { ... }` `key` is `string`

### 🙂 Expected behavior

inside `if (key in obj) { ... }` `key` is `keyof typeof obj`

**Comment by MartinJohns** [comment]
Object types are not sealed. `key` can be a different value than `keyof typeof obj` is.

```typescript
const src = { foo: 'bar', aaa: 'bbb', example: 1 }
const obj: { foo: string, aaa: string } = src;
let key = 'example';

// key is "example",
// keyof typeof obj is "foo" | "aaa"
```

**Comment by antonilol** [comment]
i see, this actually made sense for me after [this](https://www.typescriptlang.org/play?ts=4.9.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygGdCQYMBpEATwHlEAeAFXhAA8MRVhD5CMYsqAOYA+ABQBrAFy9+goQBp4OAEYArGQG8A2hPiD4jALoyoqKgF8AlKeKkMPPVh6MA3AFgAUF7B4+y9XgAXnhNJBwcGQByFVgopShE6JUUqPgLD08IEAx4CWpg+CjECKjMrwB6CrzqGT4BYS8sRHhJAoNVNStQr3g++Cqaqjq5Rs9++F9UQhxsgDoIHCExTt1qIytMiy9K6vzh2QahJpa2qn18Tu7NXv6iEjJKWkQzpSvMicH9mQAiEpwfvAAD7wH6JKA-W59KYzeaLZarfYbLY7TyQe7wACCPXG-QADjAcHiAIyFADMKO8aOgxHgACEWOxONwsTiJgSiQAmQoAVkpPj8uSghVQIAA7lixJsBdNcioReL6VLMjC5ZyZNiQqKJXTlQNqnjSIhwBgIOcAG5QCBYYBKEDm0jnBnOAgQGYEfDYsSoHC5DAACwQvsDMHgYqg51gODQwHgAejQn9VlRqoCak1oXgc2zwoyMv8nQZITC2bm8rzaMFabp3OLWezKm5Fa8GCohvgjf2PBC+xwLVbhr71c5rn1oI5JMhVOarSiE85aQ66hr1yhkz8sxACyWYgABnPCXiF4znA4LsPd5sx1QQDwsLlgDhb15tp4gA) example with subclasses.

but still this error exists in valid code (checking if a key exists and then getting the value)

it would be useful to either
- give some sort of type to `key` that allows it to index `obj` without an error, because it has been checked that key exists
- have some way to create sealed objects, i think only for compile time constants because this would be impossible with objects that can change at runtime (see my linked example). the `in` operator will narrow the type of the key down to `keyof typeof obj` in this case

**Comment by MartinJohns** [comment]
> * give some sort of type to `key` that allows it to index `obj` without an error, because it has been checked that key exists

But what would be the type of that expression be? It could only be `any` or `unknown`. If you want this unsafe behaviour, just use a type assertion: `obj[key as keyof typeof obj]`

> * have some way to create sealed objects, i think only for compile time constants because this would be impossible with objects that can change at runtime (see my linked example). the `in` operator will narrow the type of the key down to `keyof typeof obj` in this case

There's an open issue about "exact types", but don't expect it to be available any time soon.

**Comment by fatcerberus** [comment]
> There's an open issue about "exact types"

For completeness’ sake: https://github.com/microsoft/TypeScript/issues/12936

**Comment by antonilol** [comment]
> But what would be the type of that expression be?

a new type that tells the compiler that it is a 1) valid index of a *value*, or a 2) key of an exact type

example:
```ts
// key: string
if (key in obj) {
  // 1) key: string & ValidIndexOf<obj>
  // 2) key: string & (keyof exacttypeof obj)
  console.log(obj[key]); // no error
}
```

1\) this needs a change that values can be passed as type parameters (value parameters?), because `typeof obj` does not have to include all its properties
or a 2) new keyword `exacttypeof` (the type in the example will look like `keyof exacttypeof obj` then) that cannot be evaluated ([yet](https://github.com/microsoft/TypeScript/issues/12936))

**Comment by fatcerberus** [comment]
That just moves the goalposts though because then what is the type of `obj[key]`?  The best you can say is that it’s `unknown` which doesn’t really help you in practice.

**Comment by antonilol** [comment]
> That just moves the goalposts though because then what is the type of `obj[key]`? The best you can say is that it’s `unknown` which doesn’t really help you in practice.

you're right, `unknown` in strict mode and `any` otherwise.
lets wait for exact types then
