### ISSUE TITLE
Consider consolidating general checking for TDZ 

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#5232]
As @rbuckton  point out in PR #4814, we have multiple ways for checking use before definition for many concepts such as `this` before `super`, use before declaration for `let` and `const`. We should consolidate the checking to be more general purpose that we can extend rather than continuously create new ways of checking

**Comment by mhegazy** [comment]
do you have a proposal?

**Comment by yuit** [comment]
@mhegazy  not yet. This is for keeping track for now.

**Comment by mhegazy** [comment]
if we do not have a suggestion for an immediate action, i would close this issue. keeping a backlog of engineering work items never worked in the past :)
