### ISSUE TITLE
JSDoc comment templates/scaffolding may not use formatter newlines

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52348]
Not that you should fix it in this PR, but it seems like a bug that we don't have this for JSDoc comments.

_Originally posted by @jakebailey in https://github.com/microsoft/TypeScript/pull/52298#discussion_r1083166870_

```ts
        return JsDoc.getDocCommentTemplateAtPosition(getNewLineOrDefaultFromHost(host, /*formatSettings*/ undefined), syntaxTreeCache.getCurrentSourceFile(fileName), position, options);

```

**Comment by jakebailey** [comment]
To clarify out of context, "this" is formatSettings. I think this is just a plumbing problem.
