### ISSUE TITLE
TypeScript Doctoberfest

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5234]
For a while now, we've felt like our documentation has needed a little bit of love, so tomorrow (October 13), the TypeScript team is going to be having a doc-a-thon!

Because TypeScript is extremely community-driven, we want to include others to help us in our efforts. While we're mainly focusing on sprucing up [our Handbook](https://github.com/Microsoft/TypeScript-Handbook), we're also looking for contributions to [our Wiki](https://github.com/Microsoft/TypeScript-wiki), [our Samples](https://github.com/Microsoft/TypeScriptSamples), and even code documentation for [our language service](https://github.com/Microsoft/TypeScript/tree/master/src/services). Even general review on content, grammar, and spelling is something we would appreciate a ton.

If there's a topic that interests you, consider asking us [in our Gitter room](https://gitter.im/Microsoft/TypeScript) or posting an issue. That way you can ask to claim a task or to collaborate with someone who's already working on something you're also interested in.

**Comment by RyanCavanaugh** [comment]
![image](https://cloud.githubusercontent.com/assets/6685088/10463124/8382f582-7197-11e5-8af1-72153c9444c9.png)

**Comment by RyanCavanaugh** [comment]
@bowdenk7 is really stepping up his Doctoberfest game

![image](https://cloud.githubusercontent.com/assets/6685088/10463166/b3450bd4-7197-11e5-9deb-9f85ec33ce89.png)

**Comment by jonathandturner** [comment]
That. is. awesome.

**Comment by DanielRosenwasser** [comment]
@jonathandturner feel free to join if you're up to it :wink:

**Comment by DickvdBrink** [comment]
Would love to help out with some stuff, not sure what though ;) but definitely with reviews and stuff :)

**Comment by DanielRosenwasser** [comment]
@DickvdBrink sure! You can proofread the PRs on the [Handbook](https://github.com/Microsoft/TypeScript-Handbook), and file any issues on it or the wiki if something could be written a bit better/clearer.
