### ISSUE TITLE
Report unnecessary calls to Number() constructor when type is a number already

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#52352]
# Suggestion

## 🔍 Search Terms

Redundant cast, unnecessary number cast

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Report unnecessary calls to Number() constructor when type is a number already.

## 📃 Motivating Example

https://www.typescriptlang.org/play?#code/FAYw9gdgzgLgBAMzGOBeOBtAugbmKSWOAIwEMAnNOAOQFcBbYgU3IApFkA6AGyYgHMYACzgBKPEA

```js
const foo = [];

const bar = Number( foo.length );
```

## 💻 Use Cases

Reduce amount of redundant code that was introduced when refactoring old code.

**Comment by MartinJohns** [comment]
That sounds like a linter rule would be better suited.

**Comment by Josh-Cena** [comment]
> because it requires types (number) to be available

That's exactly what typescript-ESLint does: using TS type information to power minting :)
