### ISSUE TITLE
generic instanceof

### ISSUE THREAD

**Issue by ken-blocklevel** [Microsoft/TypeScript#5236]
Automatically insert generic when using instanceof:

        private static success <T> (check: T | boolean) : boolean
        {
            return typeof check === 'boolean' ? check : check instanceof T;
        }

this now, gives an error "cannot find name'T'"

**Comment by jesseschalken** [comment]
What do you expect the compiled output to be in this case? If I'm not mistaken the right side of `instanceof` is an expression evaluating to a constructor function, not a type (`instanceof` being a real thing that exists in JavaScript). It's not going to work with an arbitrary type.

**Comment by ken-blocklevel** [comment]
@jesseschalken https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof

**Comment by robertpenner** [comment]
But `T` can be an interface, which doesn't exist at runtime.

**Comment by ken-blocklevel** [comment]
@robertpenner Is there a way to make T only be of class type? If not then requesting this as new feature or issue:

    private static success <T is class> (check: T | boolean) : boolean
    {
        return typeof check === 'boolean' ? check : check instanceof T;
    }

**Comment by jesseschalken** [comment]
The best you could probably do is change your function to take an extra parameter which is a  constructor function for type `T` and use that to do the `instanceof`:

```ts
class Foo {
	public blah() {
	}
}

function success<T>(check:T|boolean, constructor:{new ():T}):boolean {
	return typeof check === 'boolean' ? check : check instanceof constructor;
}

success<Foo>(new Foo, Foo);
```

**Comment by jesseschalken** [comment]
@ken-blocklevel You can do `T extends Object`, but you still can't do an `instanceof` without a constructor function for `T`.

**Comment by ken-blocklevel** [comment]
@jesseschalken Good solution, but one must admit not a very clean one. Memorywise making a new object isn't efficient, besides you don't know what parameter T's constructor takes seeing it is variable...

**Comment by jesseschalken** [comment]
@ken-blocklevel Yeah, you can probably do `new (...args: any[]):T` so any set of parameters will fit, or something.

**Comment by ken-blocklevel** [comment]
@jesseschalken Good one again, thank you. Do you believe this proposal is unnecessary or redundant?

**Comment by jesseschalken** [comment]
@ken-blocklevel If passing the constructor function around works, then I think so. TypeScript could probably do what you originally wanted with a lot of assumptions and complexity (like assuming `T` is a class, then stamping out a copy of the function for each `T` a la C++ templates or having some system of reified generics a la C#).

**Comment by RyanCavanaugh** [comment]
The type system doesn't provide a way to "work backwards" from a type to some constructor function for that type. Taking in a `new(... args: any[]): T` is the intended solution.

**Comment by jiaweihli** [comment]
@RyanCavanaugh 
With the release of abstract types, this solution no longer works in all scenarios.

```typescript
abstract class A {}

class B extends A {}

function isType<T>(value: any, key: typeof T): boolean {
  return value instanceof key;
}

console.log(isType((new B), A))
```

On a related note, interfaces and abstract classes feel a bit kludgey since I can't seem to verify that an arbitrary object actually conforms to them.  I can require them as parameter types and use user-defined type guards, but there's no generic equivalent to `instanceof`.
