### ISSUE TITLE
Add a setting for always including the file extension in import suggestions and autoimports

### ISSUE THREAD

**Issue by zocky** [microsoft/TypeScript#52378]
Add a setting for always including the file extension in import suggestions and autoimports:

By default, vscode doesn't include file extensions in suggestions for javascript imports and in autogenerated import statements. This produces broken code in some environments. 

The [previous issue](https://github.com/microsoft/vscode/issues/41304) was closed based on [this weird fix in typescript](https://github.com/microsoft/TypeScript/pull/20624), but that is still highly unsatisfactory because:
- it works only for .js files, and ignores other importable files like .jsx
- it doesn't work for autoimports, which is especially annoying since they are inserted at the top of the file, so you don't even see them when they are inserted
- it requires the user to manually correct one import in each file which is (a) unintuitive and (b) still breaks new files

**Comment by RyanCavanaugh** [comment]
I believe this is already implemented in the "Import Module Specifier Ending". What's not working?

**Comment by zocky** [comment]
It did not work at all, but started working after I removed/reinstalled some extensions. Will close.

**Comment by ron2015schmitt** [comment]
Can someone please look into this?  Many people have this issue. There are many examples of people having problems with this on stackoverflow.    Even the instructor in a udemy React course has this issue.  It works if I name the file `.js` but not for `.jsx`.  Could some look at the code for `.js` and `.jsx`?  Might be related to using Vite.

**Comment by RyanCavanaugh** [comment]
As far as we know, it's working. Please post an issue with repro steps.
