### ISSUE TITLE
Bug: incorrect tuple (array) type after changing in place

### ISSUE THREAD

**Issue by antonilol** [microsoft/TypeScript#52375]
# Bug Report

after you change an array in place (reverse, splice, push, pop, etc...) tuple types are unchanged and still reflect the type before the change

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/GYVwdgxgLglg9mABAcwKZQHIgLYCNUBOAFAJQBciA2ogM5QExjIA0iYO+BiAuogN4BYAFCJRiGMEREAsgEMoACwB0BWWAAmcbKUQAeRAAYlAVhL9hYy4gLoQBJNQDkABxiIICOmqiPWcxUoACgCSPADcFmIAvoioADY0qOYiVqI2UHYOiI6qGlpsHIS+iP7KuZraZtwRKaJRwvVCwnHoiLIU7HiENcIeYHS0iAC8KOhYXcQkPUKyw7SUAIzVwsIA9KuIAAJQNAC0qAAezqjQ+wQEcARrG9R0DEysnZw8orsAfKJEd4zIiAA+BQmJEo3GuiAAKgBPY7Zb5Mf6AziOcQ0NhwKBtGg0GDIMCyXAtRBQOBE6FJRxPIpKYSzEY0FSoABuhESpEoBmWTSE6y2O32RxOUDOFyu3I2AEFgFBCINkOjrEyWah1OIkM44rIIKhWDAMTBUbNqJSCKw4b9uKxcCAMVAyXBJKiRrd6D9HoUuKCxRCybCXUxkfq0RjZFicXiCUliaSYRT3Y5qTM5jR2ZyVkJbTCAEqKgiJXTg2IHaUaA1gSEgj5DYQFw7F9SoyiMYAygBqvAA-JFRJQ24gKEQuxDC3WG03W6wlJOx1xMx3B5ZKJOlNnmbnULpM29WL3+-OxDWi6gS1Ql9PEJmdWBm1xe53aqkxD2J5OV0qN29eGQ96lwd-ECRBymNMeVkc5ZEhaNUFRRR5EQdRUGARgklmDMkmAS5YlXCD4lQbAjygMEbFXbF4UUXC4LgKCgwUH4iRJMjIOEVCiQWOZXzXXRjQrGpmKgAAmNiczzL4-V+AFjWBbg3mmHkMnVSMyRoU0FDgEA4hVfAFWI5UmJ9KAAGZBO03QjXdU1RJ4aTdJhKAABYjLfShHBaKVkQBRwtTAaUbHUNzsgYZAFB8cz7hYAo4jiVg+CiN0JktOA4BaNQpJ4vTjAcjjuOAjY5MJVDUQAd11BQFQGHC8K81UiQUNCLi81hsBgdR1EJNQVVghij3UazIwANgyvNF0nETQr+XAEqSsBJNYRx8QgYpjRSnqiQAdgG9dKDNWLngBegQG1RAlzUcsLUQBYlF6pb0z0gAOdaTONELXUOyczRBEErrBdEaq4RQfhoZaoAATnuoblyEjbbNYYxWEurdEH01g+NYJYrOumyFgMfNK3PCGHrMxBxsS1A1FYcErqAA)

### 💻 Code

```ts
function getNumber(): [ string, number ] {
    if (Math.random() < 0.5) {
        return [ 'pi constant', Math.PI ];
    } else {
        return [ 'random number', Math.random() ];
    }
}

let a: number;

const s = getNumber();

a = s[1];

// @ts-expect-error
// [ string, number ]  ->  (string | number)[]
// Type 'string | number' is not assignable to type 'number'.
a = s.reverse()[0];

// @ts-expect-error
// After s got reversed in place, it is a [ number, string ], but typeof s = [ string, number ]
// Type 'string' is not assignable to type 'number'.
a = s[0];
```

### 🙁 Actual behavior

type is unchanged

### 🙂 Expected behavior

after Array.reverse() the type should update if the type specifies the order of the elements' types (like `[string, number]`)

I also was playing around with a type that reverses a tuple type with some usage examples. this worked out pretty well, this could be useful for the Array.reverse type declaration, see the linked ts playground code

**Comment by RyanCavanaugh** [comment]
The in-place mutation methods for arrays aren't supported from a control flow perspective. I recommend using `readonly [string, number]` in most scenarios.

**Comment by jcalz** [comment]
Cross-linking to #40316

**Comment by antonilol** [comment]
types can change because a different type is assigned ([example](https://www.typescriptlang.org/play?#code/DYUwLgBJC8ELIEMwAsB0AnBA7AJgewFsAKASggB4IAGVAVggH4IByAZwQIAdQoQAPMMwgAuCAEYATAGYA3AFgAUIoD0yiKzDoAllgDmEAD4QsAVwIAjEOkVgAnpxBQxEWHYd4AZlHlKFMKKhgeADKmjq6pD4qahraejb2jmASLlCJnt6KQA)), would it be possible to add some type annotation to class methods to tell what happens to the instance type?
