### ISSUE TITLE
Provide snippet completions for `@param` in JSDoc

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52370]
```ts
/**
 * @para$
 */
function printValue(value, maximumFractionDigits) {
}
```

Today, we provide the expected `@param` JSDoc tag completion.

However, if we're going by the book with JSDoc, the name of the parameter is already known. Can we provide snippet completions that contain the name of the parameter?

Thoughts:

1. This should work in both JS and TS.
  1. In TS it should have a placeholder by the comment
  2. In JS it should have a placeholder that starts on the type, followed by a placeholder at the comment
2. I don't know (/remember) how this should work with destructuring.

**Comment by ufukbakan** [comment]
snippet completors related to IDEs, not directly to typescript. However I guess you use VSCode and it already does what you want. 
Write your function, go to the line just before your function, type ```/**``` then hit enter, it should autocomplete params and names

**Comment by DanielRosenwasser** [comment]
> snippet completors related to IDEs, not directly to typescript. 

TypeScript provides certain snippet completions to IDEs, such as object and class member completions and `switch`/`case` completions.

> However I guess you use VSCode and it already does what you want.

It doesn't work if you have a preceding JSDoc comment declared using a `@typedef` or an `@overload` tag.

```ts
/** @typedef {string} Id */

/**<- No comment scaffolding here
function foo(x, y, z) {
}
```

**Comment by DanielRosenwasser** [comment]
I still think things like the `@type` tag and `@typedef` tag would be good as snippets, because I can never remember the names of these things.

**Comment by ufukbakan** [comment]
> > snippet completors related to IDEs, not directly to typescript.
> 
> TypeScript provides certain snippet completions for IDEs, such as object and class member completions and `switch`/`case` completions.
> 
> > However I guess you use VSCode and it already does what you want.
> 
> It doesn't work if you have a preceding JSDoc comment declared using a `@typedef` or an `@overload` tag.
> 
> ```ts
> /** @typedef {string} Id */
> 
> /**<- No comment scaffolding here
> function foo(x, y, z) {
> }
> ```

Best thing you can do right now is inserting the line ```_;``` after your type def when finished coding you can replace ```_;```  lines with empty string using CTRL+H, I still think its about vscode not typescript

**Comment by DanielRosenwasser** [comment]
Thank you for the suggestions; however, I am a maintainer of the product and am aware of the workarounds.

**Comment by DanielRosenwasser** [comment]
Things like

* `@type`
* `@satisfies`

and more might be worthwhile to offer as snippet completions here.
