### ISSUE TITLE
FileWatcher ignores files.watcherExclude in Visual Studio Code - Insiders, with nightly TS

### ISSUE THREAD

**Issue by bennyk8y** [microsoft/TypeScript#52383]
### 🔎 Search Terms

FileWatcher

### 🕗 Version & Regression Information

```
Version: 1.75.0-insider
Commit: 243854703b7fa371abb752ec0df7817a615a308b
Date: 2023-01-13T08:04:47.712Z (1 wk ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 21.3.0
Sandboxed: Yes
```

Hi, working on latest VSCode insiders with latests TS nightly.
This is my files.watcherExclude:
```
**/node/node_modules/*/**
node_modules
node_modules/**
```

Looking at TS Server logs, there are a lot of FileWatcher node_modules related paths:
```
Info 2989 [19:19:56.155] FileWatcher:: Added:: WatchInfo: /Users/bk/company/company/node_modules/.pnpm/runtypes@6.5.1/node_modules/runtypes/package.json 2000 undefined Project: /Users/bk/company/company/src/packages/business-event-actions-config/tsconfig.json WatchType: File location affecting resolution

Info 2997 [19:19:56.250] FileWatcher:: Added:: WatchInfo: /Users/bk/company/company/node_modules/.pnpm/@types+lodash@4.14.191/node_modules/@types/lodash/package.json 2000 undefined Project: /Users/bk/company/company/src/packages/business-event-actions-config/tsconfig.json WatchType: File location affecting resolution

```
We are working on a monorepo, not sure if that's related.
An example of `tsconfig.json`, as you can see there's no `exclude`, not sure if that's related:
```
{
  "compilerOptions": {
    "strict": true,
    "outDir": "dist",
    "target": "es2020",
    "module": "commonjs",
    "declaration": false,
    "moduleResolution": "node",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "pretty": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "skipLibCheck": true,
    "strictPropertyInitialization": false,
    "forceConsistentCasingInFileNames": true,
    "removeComments": true,
    "baseUrl": "./",
    "paths": {}
  }
}

```

**Problem**: Why TS server still watches files in `node_modules` although its excluded in `files.watcherExclude`?

**Comment by sheetalkamat** [comment]
You would need to be using `excludeDirectories` and `excludeFiles`option to tell tsserver to not watch some of the directories and files
 https://www.typescriptlang.org/tsconfig#watch-excludeDirectories

**Comment by bennyk8y** [comment]
@sheetalkamat but i'm not using `--watch` flag. Does vscode uses it?

**Comment by sheetalkamat** [comment]
You want to update editor preferences for `watchOptions`
![image](https://user-images.githubusercontent.com/8052792/214435718-5707a678-0492-4b10-b358-646cd393f4d8.png)

**Comment by bennyk8y** [comment]
@sheetalkamat can you elaborate on how it works? what should i update there? isnt it just settings that indicate which strategy vscode should be using to watch files/directories?
 
Again, i see in TS Server logs that it watches node_modules although its excluded `files.watcherExclude`.

**Comment by sheetalkamat** [comment]
![image](https://user-images.githubusercontent.com/8052792/214651893-44fed4a7-d3a8-4f84-8879-ed47594eff51.png)
