### ISSUE TITLE
Deep intersections stopped working in 4.9

### ISSUE THREAD

**Issue by SephReed** [microsoft/TypeScript#52397]
# Bug Report

### 🔎 Search Terms

Deep union no longer work

### 🕗 Version & Regression Information

- This is a crash: no
- This changed between versions ____4.8__ and ___4.9____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ____yes_____
- I was unable to test this on prior versions because __tested on prior versions, is regression_____

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBA4lC8UDeUwCcD2YDOAuKAFAFBTJQCG+KAZhhvgIxQC+zJUAZGZWQEblp8AJhZsAlM05l0WPNypQAjgFcAHvgDMrNkQDGGAHbZgUAOb44iJOxk4q7Uj2ukXUWvSgMANA5f9BUEI+rqQq6lAawS5spGzMQA)

### 💻 Code

```ts
type G = { props: (
  { a: { foo: 1 }}
  & { a: { bar: 2 }}
)} & { props: { a: { qux: 3}}}

const g: G = {
  props: {
    a: {
      foo: 1,
      bar: 2,
      qux: 3,  // gives error in 4.9, not in 4.8
    }
  }
}
```

### 🙁 Actual behavior

qux gives error:
> Object literal may only specify known properties

### 🙂 Expected behavior

Continues working as it had before

**Comment by SephReed** [comment]
This one still works:

```
type G = { props: { a: { foo: 1 }}} 
  & { props: { a: { qux: 3}}} 
  & { props: { a: { bar: 2 }}}  
```

**Comment by RyanCavanaugh** [comment]
Tracking at #52252 since the PR to fix that one also fixes this one
