### ISSUE TITLE
New Website Logo: Ubisoft

### ISSUE THREAD

**Issue by FMARTEL2** [Microsoft/TypeScript#5240]
Hi,

We would like to add Ubisoft to the list of Friends of TypeScript. Here are the info:

- Name: Ubisoft
- Homepage url: https://ubisoft.com
- Brand Guidelines/Licensing: 
- Logo: https://www.ubisoft.com/en-US/company/press.aspx. You must take the institutionnal color logo from the press kit (download).

Can you confirm that we can ask you to remove the logo at any time please.

Tx,

Francois Martel

**Comment by RyanCavanaugh** [comment]
> Can you confirm that we can ask you to remove the logo at any time please.

Yep, just log a new issue for that. Thanks!
