### ISSUE TITLE
tsconfig + schema + exclude description

### ISSUE THREAD

**Issue by DeanB2015** [Microsoft/TypeScript#5241]
The description in the "exclude" object appears to be inaccurate.  
Schema location: http://json.schemastore.org/tsconfig

Problem: Exclude Description 
Currently reads: "If no 'files' property is present in a tsconfig.json, but an 'exclude' property is present, the compiler will exclude the files and folders specified in the 'exclude' property.",

Solution: Update wording
The  "files"  property cannot be used in conjunction with the  "exclude"  property. If both are specified then the  "files"  property takes precedence.
Taken from the tsconfig wiki: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

**Comment by mhegazy** [comment]
A PR to http://json.schemastore.org/tsconfig would be appreciated.
