### ISSUE TITLE
`never` fails when return type of method and not a function

### ISSUE THREAD

**Issue by holtwick** [microsoft/TypeScript#52413]
# Bug Report

The return type `never` has no effect of methods.

### 🔎 Search Terms

never

### 🕗 Version & Regression Information

4.9.4
 
### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.9.4#code/MYewdgzgLgBANiA5ogpgJxgXhgbwFAwwBmAhlCXABQCUAXDGCgG7q4GExQAWaIA7gxQCAoml5pKAclLk4k6uwC+AGjyK8eIgFcwwKAEtwnFNEoATMiQD89aGn1hEdGHYeI2hfURjnLWbGBacHAKHPBIqGgAdDIUNOxoKFBaaGAwFuRqGgD02RraugZGsVTOjCwY+ITcvAKMImIgEtKWcgrqmjp6hmlQJlAATL7kNi5Q9o7Oro4eMF4+GST+DEEh7IQl8YSJyanplll4uRp9ppIk8ning1IARpdAA

### 💻 Code

```ts
const logger = {
  fatal(): never {
    throw new Error('fatal')
  },
}

function test(data?: string): string {
  if (data == null)
    logger.fatal()
  return data // Type 'string | undefined' is not assignable to type 'string'. Type 'undefined' is not assignable to type 'string'.(2322)
}

//

function fatal(): never {
  throw new Error('fatal')
}

function test2(data?: string): string {
  if (data == null)
    fatal()
  return data
}

//

test('a')
test2('b')
```

### 🙁 Actual behavior

Call to `never` returning method does not do the same as an identical function.

### 🙂 Expected behavior

Expect call of `never` returning method to have an effect of type checking.

**Comment by MartinJohns** [comment]
Duplicate of #50363.

**Comment by holtwick** [comment]
Thanks, seems to be indeed the same.
