### ISSUE TITLE
narrowingDestructuring test missing a 'typeof' operator

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#52410]
# Bug Report

_(sort of)_

### 💻 Code

https://github.com/microsoft/TypeScript/blob/2d0a00d45739d6344c4996f2b073580570de05e7/tests/cases/compiler/narrowingDestructuring.ts#L34-L39

### 🙁 Actual behavior

The code checks if `x[0]` is itself equal to `'number'`. `x[0]` is `number | string`, so the test is something one might feasibly do.

### 🙂 Expected behavior

I'm guessing the test author meant to check if `typeof x[0] === 'number'`, to trigger `typeof` type narrowing?

Spotted by @Andarist in https://github.com/microsoft/TypeScript/pull/51037/files#r987365768

**Comment by Andarist** [comment]
Ah, ye - I meant to PR this small change but forgot about it 😅
