### ISSUE TITLE
Assignment to object member requires all attributes of all possible members

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#52420]
# Bug Report

### 🔎 Search Terms

union attributes intersection assign object member

### 🕗 Version & Regression Information
- This changed between versions 3.3.333 and 3.5.1
- Nightly version at time of test: v5.0.0-dev.20230125

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play#code/JYOwLgpgTgZghgYwgAgEIHs5gJIgM5hwhLIDeAsAFDI3JQQCOArsPXgDLBL4QBcyAI3ToANhCIBuKrWQBbOAA8A4lHRMQAEwDKABwgQN-EE1kDoU6rQ0Q8CKMB1hg6EPwL2QAcwsyNwPDoiiBCyEOBGJmZQPrQgcKFuYB7eVAC+VKCQsMHIAApBIBC4BEQkFJY09MysNpzceHyCwmKS0rTyyqrq2noGEabmbTQdACpwANYQ6DAwAOoQwJ4AFmD9UTHDigDCUCx4oJ4AgiJOYEzWa4MVyHEJyO4HFumUmdDwJABqEEtcYnhkQzQmFWQKwxUIxAgGzyBUa+SIRXwEKQTyo1gQQXoyBg6gQThcyE8EDAXx+GKKMEOADc4MAggIxAAeEYAOWQEAUkE0-0mAE9pshSb8bAA+AAUgKp32FLPijVZABoqABKZD8XKqWT+CCMoXkvAAbVZAF1kAAfZDdCAwUAGEUWDk6dBQMDIBAuAiE4l6v7IAC8yDgeF5xGxuPxIAl1ylZLEstCeH4YoeXmQADJkHyBT6bMqDcalZRVeUZGJXWwmCd-uq4C7gHARLrpfqRf6yKloQB6TsjJYoJ3OgC07r8qZ0UEQThIUqg+wJAqWtY0I4O7JnvOQIltgO7YoA7s6Gsg932QMgwH3N-5XQKY8Lz7y9P9-JuXESoIHNJ3nee+zvOzixARseZJLF6hQTpA-wXiE54TDYgavl40BXp6Ao6LWcpZHg-5EBo34fjB9xMAIDSumA6CCP26A6JWWAGMgL4aCG8RcKqB5QOMOHXBWVYGgA5BgWD8aaAZwHutKukSJLNmI2CUjSdJwAyEBioJwL8cq0K8WAhr8fChQiW24mSV6MmxhS1K0vSYhqQZECaV2PaXrIzooNaNoIMAYRgAqm42Hgg6LlAy7oNYGh+QITCuiA6BgIODYiOge4GIOoCDiMWjIDOc6uICMA-mKZbZbJEDxigt6leVeDFoCMjukiJUWeVWweq6AZ3uS5XQjI3a6WKABMADMA0DaqACiUCqB+BKFJyV6FMg+59liSzoDOyDrShnVxnKdAQFKDb-AAREJYDHeayDHfZF1BuyCh6HiBjKrwdW0N2IyPig6lgkipQoBa9ngv9l1WjahQaPxjH-LFrpBvsnhxCp57oG9NB9V9yD8WKZ3A5C6YwgieNIKqFpg7akMAHRo8gH2Yz9OB-ZCUMvrDgZ4AjSNiCjD56FjuNMyQGZA4LDnU9cvWdmKsxLBuL7AORUC8quFHs5zPMXlgvMQAA-MqNN03zDPEw50NyP4+ypkRBUiEle6ruONHQE4CEwJq2tYyLJTM69EvvZ2ozwdMcwLMsvlyNsuz+AcxynOcEA0zpho7WVcqtUiomBhJCtmTm8lWUpKliinLVtVpgLPDI9BnFAZ5J6ilBAA)

### 💻 Code
```ts
interface BoatInstance {
    requiresLicense: boolean;
    maxGroundSpeed: number;
    description: string;
    displacement: number;
    name: string;
}
interface PlaneInstance {
    requiresLicense: boolean;
    maxGroundSpeed: number;
    maxTakeoffWeight: number;
    maxCruisingAltitude: number;
    name: string;
}
interface Vehicles {
    Boat: BoatInstance;
    Plane: PlaneInstance;
}
declare function getVehicleIfAvailable<TN extends keyof Vehicles>(
    vehicleName: TN,
) : Promise<Vehicles[TN] | undefined>;
export const getVehicles = async function(
    vehicleNames: (string & keyof Vehicles)[],
) {
    let results : Partial<Vehicles> = {};
    //The poor-coding practice version of hardcoding every line
    //(worse when the list of vehicle types is longer and/or the
    //function which generates them takes a longer list of parameters
    //and/or the subset to be populated is dynamic) works
    results['Boat'] = await getVehicleIfAvailable('Boat');
    results['Plane'] = await getVehicleIfAvailable('Plane');
    //The more efficient, less-hardcoded, but not-allowed-in-TS version:
    for (let vehicleName of vehicleNames) {
        const vehicleNameConst = vehicleName;
        //ts(2322) Error on next line (where hover over vehicleName reveals "Boat" | "Plane" as expected):
        //Type 'BoatInstance | PlaneInstance | undefined' is not assignable to
        //type '(BoatInstance & PlaneInstance) | undefined'.
        //Type 'BoatInstance' is not assignable to type 'BoatInstance & PlaneInstance'.
        //(Why is it trying to assign to that type?)
        //Type 'BoatInstance' is missing the following properties from type 'PlaneInstance':
        //maxTakeoffWeight, maxCruisingAltitude
        results[vehicleNameConst] = await getVehicleIfAvailable(vehicleNameConst);
    }
    return results;
}
```

### 🙁 Actual behavior
TS was successfully able to assign just a single instance of one kind of vehicle before the for loop,
but when assigning to `results[vehicleName]` for any variably-specified vehicleName (even when a holding constant is used, with the same constant value on the left and right sides of that final assignment line), it expects the type being assigned to have all the properties of all the types that a member of `results` could have, instead of just the specific type corresponding to the name of the key being assigned to. 

### 🙂 Expected behavior
The assignment inside the for loop does not expect the `&` combination of all the types that could be members of that object, just the type corresponding to the member of `Vehicles` corresponding to the `keyof Vehicles` in use in that particular line. TypeScript should be able to figure out that the type returned from `getVehiclesIfAvailable()` is the type that corresponds to the vehicleName given.

**Comment by RyanCavanaugh** [comment]
Locking this instead of a different issue is what I get for having too many tabs open.

From a static analysis perspective, there's nothing distinguishing this code from any number of unsound variants of it wherein the left utterance of `vehicleNameConst` and the right utterance refer to different variables with different values. In particular, our type system does not attempt to reason about this sort of relationship.

**Comment by wbt** [comment]
It *is* possible to do static analysis on *this example* to figure out that the RHS type, i.e. the resolve type of `getVehicleIfAvailable(vehicleNameConst);` is `Vehicles[TN]` where `TN` is `vehicleNameConst` and that this type `Vehicles[TN]` is the same type expected on the LHS for the same TN; static analysis *can* verify that it's the same. 

Yes, there is an infinite number of ways to write unsound code, but this isn't one of them.  

This is an example where "working as intended" seems to pit the actually-intended goals of Typescript *against* the nominal goals of being able to write clean, reusable code and/or easily transition JavaScript already written that way into functional TypeScript without having to rewrite code in a way that actively harms readability, scalability, and usability. 

By the presence of the issue, it seems like the TS compiler does not *currently* do the analysis needed to figure out that this assignment is sound; the Issue proposes that the TS compiler's static analysis capabilities be expanded to recognize cases like this as sound, instead of falsely reporting it as unsound, preventing compilation.

**Comment by RyanCavanaugh** [comment]
Yes, you can special-case anything. The point is that we don't want to make a type system built out of special cases, as much as we can help it.

**Comment by wbt** [comment]
I don't think it is a one-off special case; I think this is a reasonably common pattern that should behave correctly, even if not everybody who has code written like this has time to boil it down to a simple example for posting here.  With the logic of the last post, every correct program is a special case and we really should make a type system that can pass as many correct programs as possible.

"Working as intended" suggests that if the code didn't behave like this and actually let the sound case through, that should trigger effort to change the behavior back to prohibiting sound code like this.  If you want to know sources of where the impression comes from about TS work against good coding practices, here's one illustrative design decision.

**Comment by RyanCavanaugh** [comment]
Happy to clarify that.
