### ISSUE TITLE
Validation of variable is not undefined doesn't work if it's not done directly inside if statement

### ISSUE THREAD

**Issue by eliezra236** [microsoft/TypeScript#52429]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgQwA4wLwzAUwO4wLLIA80ATgJZgDmANBgK5wBGmJAfABQCUA3ALABQiJADoImKOwDkCSbQCMPAaEiwEaeMmGVxUmYv5Lw0GGQgBBAGoIANmQAm6gEIgQ1zAjDsE+gWQBmMOwAhKaWNvacMADeAjBxMFAAFiQguACiJCkkUmAgMHp8-AC+AoYq+QDCIEgAngBc9Ews6giFvgHB3tGx8Ukp6Zkg2ZK5+ZKcAiUG-MrGCFW1AEwNYAzMJC2FQA)

### 💻 Code

```js
const map = new Map<string, number>();
map.set('a', 1);
const a = map.get('a');

const isAValid = Boolean(a);

if (!isAValid) {
    throw Error('no a');
}

const aCopy: number = a;

if (!a) {
    throw Error('no a')
}

const aCopy2: number = a;
```

### 🙁 Actual behavior

In the first example aCopy gives error because it can be undefined according to typescript

### 🙂 Expected behavior

aCopy should be defined to be a number.

**Comment by DanielRosenwasser** [comment]
We don't *really* understand that `Boolean` is testing for truthiness. If you change your code to use `!!`, you do get the desired result.

```ts
declare const a: number | undefined;

const isAValid = !!a; // <- here

if (!isAValid) {
    throw Error('no a');
}

const aCopy: number = a;
```

If you really do want to use `Boolean` like this, I guess you could add a signature with a type predicate like this to the global state:

```ts
interface BooleanConstructor {
    <T>(x: T): x is Exclude<T, null | undefined | 0 | "" | false>;
}
```

**Comment by RyanCavanaugh** [comment]
#16655
