### ISSUE TITLE
Accessing a property of an object with index signatures should be inferred as possibly undefined

### ISSUE THREAD

**Issue by internalstability** [microsoft/TypeScript#52425]
# Suggestion

It would be good if TypeScript infers a type of a property of an object with index signatures as possibly undefined, i.e. `T | undefined`.

## Motivation

Given the code snippet below, it does compile, but it raises a runtime error because `a['c']` is inferred as `number[]` but it is actually undefined:

```ts
type A = { [k: string]: number[] }
const a: A = { b: [1, 2, 3] }

const sumC = a['c'].reduce((prev, curr) => prev + curr, 0)
console.log(sumC);
```

## 🔍 Search Terms

[Index signatures], Type Inference

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
  * **IT IS A BREAKING CHANGE in writing and compiling a TypeScript code**
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

It would be good if TypeScript infers a type of a property of an object with index signatures as possibly undefined, i.e. `T | undefined`.

## 📃 Motivating Example

```ts
type A = { [k: string]: number[] }
const a: A = { b: [1, 2, 3] }

const sumC = a['c'].reduce((prev, curr) => prev + curr, 0)
console.log(sumC);
```

See it on [TypeScript Playground].

## 💻 Use Cases

I believe it is very essential to ensure better type safety.

[Index signatures]: https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures
[TypeScript Playground]: https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeUDaBrAXFAzsATgJYB2A5gLrbECuAtgEYT6rlQC+AUAMYD2xeUAIbY4iFPWyoAjABooAJjkBmVp258BOOgGEEQ1AHIuB8gDp8EACbUuEABR2wFgG5yu1fPgCUCAHxQnCGcoAGood085AAYvdX4eABsIUwSeUjstWm0vAG4OIA

**Comment by whzx5byb** [comment]
You should turn on [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess).

**Comment by internalstability** [comment]
@whzx5byb Oh my gosh. Sorry for not reading a manual carefully. I will close this issue. Thanks for letting me know!
