### ISSUE TITLE
Missing types on DOM HTMLMediaElement with experimental web platform turned on

### ISSUE THREAD

**Issue by jonluca** [microsoft/TypeScript#52436]
# Bug Report

### 🔎 Search Terms

HTMLMediaElement, HTMLAudioElement, audioTracks, lib.dom.d.ts

### 🕗 Version & Regression Information

True in v4.9.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5IBQR8AdpgC6hIA2SAtkmdQLyhlIDuoAggK4IAlnAAUASgDcpOBTj0AdLTipRdRs0oKAhoJEAVfNpgBrTFKA)

### 💻 Code

```ts
const element = new Audio();
console.log(element.audioTracks);
```

### 🙁 Actual behavior

audioTracks is not found on HTMLAudioElement or in any form of lib.dom.d.ts

### 🙂 Expected behavior

audioTracks is found on HTMLAudioElement, per https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/audioTracks

Where do the types for experimental web media get generated?

**Comment by MartinJohns** [comment]
TypeScript does not provide types for experimental API. You have to write them yourself, wait for them to be stable, or look if someone else perhaps wrote them already.

**Comment by jonluca** [comment]
That makes sense. Thanks!

**Comment by yassernasc** [comment]
@jonluca have you written or found types for this? thanks
