### ISSUE TITLE
Function overloading merging implementation signatures

### ISSUE THREAD

**Issue by pedrodurek** [microsoft/TypeScript#52442]
# Bug Report

If I have a function overloading where the second argument depends on the signature of the first argument, it merges all implementation signatures for the second argument.

Ideally, I want to solve this problem with union type rather than overloads, but tuple "loses" its signature when using conditional types. For example:
```ts
type Options = 'a' | 'b'

declare function func<T extends Options | Options[]>(arg: T extends any[] ? [...T] : T): T;

const result = func(['a', 'b']) 
// result type: ('a' | 'b')[] instead of  ['a', 'b']
```

### 🔎 Search Terms
function overloading, implementation signatures

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about Function overloading.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBA8mwEsD2A7AzlAvFA5AQxygB9cAjHAKAoBMIBjAGzwCdoAzAVxTsVSk+4AeACpQIAD2AQU1DHF7oA2gF0AfAAoWAcwBcURQDojw5QBoo2gEx7higAzKAlDYDcNek1b8uPZCm9CohJSMnLwfmga2jbmVjbEuHQ4zlDCbhR0qGjAUKxoHAw52AJ06or4OOY45Ga4yRlZOXkFwJZYAaUVVclQQA)

### 💻 Code

```ts
type Options = 'a' | 'b'

declare function func<T extends Options[]>(arg: [...T], arg2: T[0]): T;
declare function func<T extends Options>(arg: T, arg2: T | 'c'): T;

const result = func(['a', 'b'], 'c') // Type inferred for the second argument should be 'a', but it's returning 'a' | 'b' | 'c'
const result2 = func('a', 'c')  // Type inferred for the second argument should be 'a' | 'c', but it's returning 'a' | 'b' | 'c'
```

At least with function overloading I can get the appropriate return type for `result` `['a', 'b']`

### 🙁 Actual behavior

Type inferred for the second argument is `'a' | 'b' | 'c'`.

### 🙂 Expected behavior

Type inferred for the second argument should be `'a'` in the first case and `'a' | 'c'`  in the second case.
```ts
const result = func(['a', 'b'], 'c')
// arg2: "a" as expected

const result2 = func('a', 'c')
// arg2: "a" | "c" as expected
```

**Comment by RyanCavanaugh** [comment]
This seems to all be working according to expectation.
```ts
type Options = 'a' | 'b'

declare function func<T extends Options[]>(arg: [...T], arg2: T[0]): T;
declare function func<T extends Options>(arg: T, arg2: T | 'c'): T;

const result = func(['a', 'b'], 'c'
// result: ["a", "b"] as expected

const result2 = func('a', 'c'
// result2: "a" as expected
```

**Comment by pedrodurek** [comment]
Sorry @RyanCavanaugh, there was a typo in the expected behaviour. The problem is not the return type, it's the second argument (`arg2`).
```ts
type Options = 'a' | 'b'

declare function func<T extends Options[]>(arg: [...T], arg2: T[0]): T;
declare function func<T extends Options>(arg: T, arg2: T | 'c'): T;

const result = func(['a', 'b'], 'c')
// arg2: "a" as expected

const result2 = func('a', 'c')
// arg2: "a" | "c" as expected
```

**Comment by pedrodurek** [comment]
Hey @RyanCavanaugh, do you still need more info?

**Comment by RyanCavanaugh** [comment]
Is this bug about what shows up in the completion list?

**Comment by pedrodurek** [comment]
Yes, the bug lies in the IDEs' code completion

**Comment by RyanCavanaugh** [comment]
As shown in #52516, it's not always the case that the best completion list is the one informed by the current inference of the call, so we have some logic that tries to be the most helpful. Since it's generally better to show more rather than less (since presumably the programmer knows how to write correct code), this is the intended behavior in this scenario.

**Comment by pedrodurek** [comment]
Hey @RyanCavanaugh, I'm not sure if this is related, but something is not right with the code completion for function overloading. Take a look at this different example [here](https://www.typescriptlang.org/play?ts=4.9.4#code/C4TwDgpgBA8mwEsD2A7AzlAvFA5AQxygB9cAjHAbgChRJZ5l0AmLXPA4s86m8aORKgBKENAFcANsAA8AaSgQAHsAgoAJhlJIkEiHhQA+VvKUr1GYACcx0APz1BzKAC4HjNDzUQAxhLyXoADMxFG9HKGDQ6QAVBWVVDTdhUUkZWQMAGigTePMoLR09QwAKJAZUV2iswO1XWQBKVzQrBBQAc2ovX38gkLDGCL6YuLNEgUYRcSk5TOyRhM1tXX0DUvKUSqyvQLxUgDU8CRsmlvbq2uzGqGbLVo6qKm9UZqgAqeBWSO9inBwsqxs9SAA), where the first argument depends on the second one. The code completion simply loses the inference of the second argument (`true` or `false`) and fallback to `boolean`, which affects the code completion for the first argument.

![Screenshot 2023-01-31 at 4 49 17 PM](https://user-images.githubusercontent.com/12190482/215909924-2d68a446-e8d2-4408-88de-062df7da8f91.png)

☝️ It's like if the second argument is inferring as the constraint value (boolean) rather than `true` or `false`, which will cause the first argument to be `Option | Option2`.

**Comment by pedrodurek** [comment]
Hey @Andarist, I'd love your input on this one if possible ❤️ !
Thank you in advance!

**Comment by pedrodurek** [comment]
Thank you @Andarist. I really appreciate that! That definitely solves my problem! I also managed to solve it using the new `const` operator, but since the changes that I'm applying are for an open source (lib), I don't want to force people to upgrade their TS version yet to leverage those changes.
 The only edge case that I have is [this one](https://github.com/microsoft/TypeScript/issues/52442#issuecomment-1411234429), which I think it's not exactly the same issue. I know that I'm asking too much ❤️, but do you think there is an workaround for it?

**Comment by Andarist** [comment]
[TS playground](https://www.typescriptlang.org/play?ts=4.9.4&ssl=20&ssc=40&pln=1&pc=1#code/C4TwDgpgBA8mwEsD2A7AzlAvFARAQxygB9cAjHAbgChRJZ5l0AmLXPA4s86m8aORKgBKENAFcANsAA8AaSgQAHsAgoAJhlJIkEiHhQA+VvKUr1GYACcx0APz1BzKAC4HjNDzUQAxhLyXoADMxFG9HKGDQ6QAVBWVVDTdhUUkZWQMAGigTePMoLR09QwAKKigoADoq-wBzNFcAbSQGVFdorMDtV1kAXU4mlpQ2rK9AvFSANTwJG1c0KwQUGo6u7J6qAEo5haWeAHo9qGAACwQMceAkbyQAWzBdFQwAAwBydhfOF9JSF6eqa-QwCgAXEUlYkW8xRwOCyVhsG32hxOZygFyut3uEEeUFeeA+JC+v3+qHmwJSUhY2AhUJhEWmaAgCKoVAOR1O5zEl2udweohxbzxn2+RIBpJBqQAzOCQpDoVkXvNLC9YdZGYi2Si0dzMdjcfioIS-qKgeKpAAWaWhGnyxXKukSBlMoA)
```ts
type Options = "a" | "b";
type Options2 = "aa" | "bb";

type OptionResult<K extends boolean> = K extends true ? Options2 : Options;

declare function func<T extends OptionResult<K>, K extends boolean>(
  ...args: [option: T, foo: K] | [option: T, defaultValue: string, foo: K]
): string;

// this autocompletes `'aa' | 'bb'`
const result = func("", true);

// this autocompletes `'a' | 'b'`
const result2 = func("", false);

// this autocompletes `'aa' | 'bb'`
const result3 = func("", 'str', true);

// this autocompletes `'a' | 'b'`
const result4 = func("", 'str', false);
```

Note though that I think it's moslty a weird requirement for the former argument to autocomplete based on the latter one. It's not how people type in the argument - they type from the left to the right so the ability to autocomplete based on the latter argument (that usually wasn't even typed in yet) doesn't really bring a lot to the table. Conceptually it can/should work - but in practice it's not that useful.

**Comment by pedrodurek** [comment]
thank you very much @Andarist ❤️ .
I know it's a weird requirement 😅 . In the [i18n](https://www.i18next.com/) library, we infer the translation keys based on the translation files and the given namespace, but users may change the namespace for a specific case, for example:

```tsx
const translations = {
  common: {
    key1: {
      key2: ''
    }
  },
  dashboard: {
    key3: {
      key4: ''
    }
  }
}

const {t} = useTranslation('common');
t('key1.key2');
t('key3.key4', {ns: 'dashboard'}); // Here
```
If we change the `ns`, it'll infer different keys. 

The library offers a lot of customisations which makes the types quite complex: https://tsplay.dev/WokvMW
