### ISSUE TITLE
"... is a type and must be imported using a type-only import ..." should have a quick fix

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#52444]
# Suggestion

## 🔍 Search Terms

verbatimModuleSyntax type quick fix

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I am trying out the beta, and got this message when enabling `verbatimModuleSyntax` (as expected). However, the only quick fix available to me was the one to convert the import to a namespace import.

## 📃 Motivating Example

```ts
import { ImAType, NotAType } from "foo";
```

Becomes:

```ts
import { type ImAType, NotAType } from "foo";
```

Or:

```ts
import { type ImAType } from "foo";
import { NotAType } from "foo";
```

I thought we had it (maybe it only works for `preserveValueImports`?)

## 💻 Use Cases

People switching these new stricter flags on.

**Comment by sultondev** [comment]
Thanks bro

**Comment by Hi99s** [comment]
Thanks
