### ISSUE TITLE
Can’t assign to member of type that uses generic parameter, though member is assignable to same type

### ISSUE THREAD

**Issue by wbt** [microsoft/TypeScript#52441]
# Bug Report

### 🔎 Search Terms
assign member of generic variance

### 🕗 Version & Regression Information
- This error changed between 3.9.7 and 4.0.5; v3 says ‘0’ is not assignable instead of ‘number’ is not assignable.
- Nightly version at time of test: v5.0.0-dev.20230126

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggNnAcgVwLYQE4EsDGNjDYBGywEAzlALxQDeA2lgHYAmEAHgFxTmHMDmAXW5M0RTAF8A3AFgAUGxxwAhhmgAzZExzAsAeyZRgygNYUUqcRgAUq-gAYRYzAEpuRPXrgRlTWXI4wPQxgKBwDXigAL0w9AHlSC0xcfD4SMkQ9AHEIJmScaihNbV0Da3koSqgANwgdYO54JDR81OJSCgAaCqryCG8dCBY2rHSIRGV0bl5sJn5uuRc6HsrjM3ILK2ta+ox6PoGyYYJ2jMmIQRd-Kpq64GD9-ruhkbGJ9EFC+2uqtWBkDCGHb3DD+CTyQLBULhJiRGIYeKJFrYPAnUYdACqfXIOTyKMKxR0+iYAB4ACpQDhkViUJpJFGvDrkAB85TkN2BDSgZIWNwOz2OaQ67wg3DMID06m5CyWtCgAHp5eQ9OhdOhKAB3aB5IbcqDKSjKKD8XL5Ix6MIRQjKZhQPTAAAWmCgYFU5zIGHInSgfwBhlAkG9EGAOAAdCsFfKyQBlMK+IpYfgA6B6Ui3XaPQ4vNFvc6fLCGqCiSzO9TBH0+FgCb3pIv2qAa7C6OacCNrczOGycvb8waC07jPNXCPdzMCxlnD5fKSRgCiGAw3AA5MWrEuoAW66EDeRE0xlERvOajOBoEuyfRxZLuYIlxHfYD0yCwfIgA)

### 💻 Code

```ts
type AllNumericAttributes = {[index: string]: number};
declare function takesNumber(arg0: number): boolean;
export const zeroOutNumericAttributeNoGeneric = function(
    vector: AllNumericAttributes,
    selectedAttributeName: string,
) {
    takesNumber(vector[selectedAttributeName]);
    vector[selectedAttributeName] = 0;
    return vector;
}
export const zeroOutNumericAttributeUsesGeneric = function<T extends AllNumericAttributes>(
    vector: T,
    selectedAttributeName: keyof T,
) { //sometimes we need T as a generic to constrain other parameters, return type, etc.
    //TS can figure out vector[selectedAttributeName] is a number for reading, but not writing:
    takesNumber(vector[selectedAttributeName]);
    vector[selectedAttributeName] = 0; //Err: 'number' is not assignable to type 'T[keyof T]'
    return vector;
}
```

### 🙁 Actual behavior
Can't assign a number to what static analysis should be able to determine is, in fact, a number, though the analysis can determine that it is a number for the purpose of assignability to a function parameter.

### 🙂 Expected behavior
No error here; can assign a number to a numeric type even when a generic type parameter is involved in determining that type.
I tried many versions of this, including other ways of specifying what the attributes were instead of by an index type, and this was the simplest version that demonstrated inability to assign.

**Comment by RyanCavanaugh** [comment]
This is a correct error; it is factually the case that `vector[selectedAttributeName]` is not necessarily assignable *from* `number`. In other words, you could have written
```ts
const p: { n: 3 } = { n: 3 };
zeroOutNumericAttributeUsesGeneric(p, "n");
```

**Comment by wbt** [comment]
Darn. I oversimplified an issue to the point of incorrectness, seeing that the issue was retained as simplification progressed but failing to complete analysis about the direction of `extends` testing on the final step.  Will have to try again.
