### ISSUE TITLE
Raw string literals

### ISSUE THREAD

**Issue by PieterjanDeClippel** [microsoft/TypeScript#52453]
# Suggestion

## 🔍 Search Terms

- typescript multiline string indentation
- angular multiline string indentation
- typescript multiline string tabs

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

- [New since .NET 7](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#raw-string-literals)
- Something similar could be implemented in Typescript, using a tripple-backtick rather than the c# tripple-quotes

```
export class Demo {
  public getMessage() {
    return ```
      Hello world
      Here is some text
      Spread over multiple lines
      ```;
  }
}
```

## 📃 Motivating Example

This would make the multiline strings (expecially if you'd mention code blocks) more readable in the typescript source code.

## 💻 Use Cases

![image](https://user-images.githubusercontent.com/9629574/215034414-8e4198b4-6d8c-424e-8468-8447fe0f5745.png)

**Comment by MartinJohns** [comment]
This is out of scope for TypeScript. It would first need to be supported by JavaScript. Check the viability checklist again.

**Comment by fatcerberus** [comment]
IIRC I think there’s actually already an ES proposal for this.  Don’t know what stage it’s at though.

**Comment by MartinJohns** [comment]
Apparently it's stage 2, but it's tucked behind a function without special syntax.
https://github.com/tc39/proposal-string-dedent

**Comment by PieterjanDeClippel** [comment]
> This is out of scope for TypeScript. It would first need to be supported by JavaScript. Check the viability checklist again.

Why would `tsc` not be able to process this type of string notation? It does not HAVE to be supported in javascript. `tsc` just has to transpile it to a concatenated string.

```
export class Demo {
  public getMessage() {
    return ```
      Hello world
      Here is some text
      Spread over multiple lines
      ```;
  }
}
```

CommonJS pseudo-code:

```
module.exports = (function() {
  return {
    getMessage: function() {
      return "Hello world" + "\r\n" + "  Here is some text" + "\r\n" + "    Spread over multiple lines";
    }
  };
})();
```

ES pseudo-code:

```
module.exports = class Demo {
   constructor() {}

   getMessage() {
       return "Hello world" + "\r\n" + "  Here is some text" + "\r\n" + "    Spread over multiple lines";
   }
}
```

**Comment by PieterjanDeClippel** [comment]
The .NET 7 compiler compiles the following:

![image](https://user-images.githubusercontent.com/9629574/215263202-cf0146d2-065e-40d5-8021-0e2f02a8a2a0.png)

To

![image](https://user-images.githubusercontent.com/9629574/215263219-a7e77640-c3a0-48ae-81f7-de0304ba093e.png)

**Comment by MartinJohns** [comment]
> Why would `tsc` not be able to process this type of string notation? It does not HAVE to be supported in javascript. `tsc` just has to transpile it to a concatenated string.

Because TypeScript chooses to not add features that are not supported by JavaScript, besides type related ones. Only exceptions are enums and namespaces, which unfortunately were added before this decision was made.

It's specifically mentioned in the viability checklist:

>  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, **new syntax sugar for JS**, etc.)

It's also part of the [Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) mentioned in the checklist:

> 8. Avoid adding expression-level syntax.

**Comment by PieterjanDeClippel** [comment]
So perhaps this should be drafted in the next ECMAscript spec?

**Comment by MartinJohns** [comment]
ECMAScript proposals are tracked in the tc39/proposals repository: https://github.com/tc39/proposals

A proposal for your requested feature already exists and was linked earlier: https://github.com/tc39/proposal-string-dedent  
The option of having this as a syntax feature was discussed plentiful as well: https://github.com/tc39/proposal-string-dedent/issues/40
