### ISSUE TITLE
can't assign object when use keyof object type, but uses generic parameter work correctly

### ISSUE THREAD

**Issue by Hental** [microsoft/TypeScript#52458]
# Bug Report

### 🔎 Search Terms

keyof

### 🕗 Version & Regression Information

- version at 4.9.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?experimentalDecorators=false&emitDecoratorMetadata=false&moduleResolution=99&target=7&module=6&ts=4.9.4#code/C4TwDgpgBAysCGxoF4oG8BQVtQGYHt8AuKAZ2ACcBLAOwHMscAjeCgfhJoFcBbJiCgG5G2JoQA2JMfnER4NYQF8MGAMb4a5KLSrA4iCCX1IoqTDjyESAcgCM1gDQioLCiQBMTi9MlRKXCCdlDFwuGlVgKg0oeFJSKjoaYwgACgQKOghgIwQkB20aMC5s2FyIAEp0Z3VNYCgAawgQUlMoAHkmACsICIA6RuaU2iLgStioAEEKCngQAB4B-FxSgwA+YWcB0l6CCgBReFUACxSU+srkVaqLC1k6gDd4cVbh4oBteoBdYRucAHo-tgAHpsZwWdKZYAfT4vQrvL4-HCKcpKFShcKRaKxeKJOYAFSgEAAHkgaAATFrJVZpViQkh4-KvEp4yrmHA1LRbVodbp9LZDOGjGItKYzeaLZZ49YqCxbHb4faHE5nC5XNm-O5QR7PVBM6GI34A4Gg37YCFZaGtbUGqDI1FqDRabEJGgAdV0R2SrWduKpKg5dXIBlaaEUwpWSGEPqSZRSQbyBV0yRRGGjcbKjJoSbKKej7uAntj8cCib0OY2oEgUDxEC0qGSHyaSwjEE+KiAA

### 💻 Code

```ts
type State = {
    foo: string
    bar?: number;
    bool: boolean;
}

const initState: State = {
    foo: '1',
    bar: 2,
    bool: true,
}

function assignState(target: State, input: State) {
    const keys = Object.keys(input) as Array<keyof State>;

    keys.forEach((k) => {
        let val = input[k];
        //  ^?  string | number | boolean | undefined
        // typescript treat  k as union type like "string | number | boolean | undefined" not keyof type，so target[k] type is `never` , can't be assign 
        target[k] = input[k];
    });
}

function assign<T extends State>(target: T, input: T) {
    const keys = Object.keys(input) as Array<keyof T>;

    keys.forEach((k) => {
        let val = input[k];
        //  ^?  T[keyof T]
        // work correctly
        target[k] = val;
    });
}

const assignWithState = assign<State>
const state = {} as State;
assignState(state, initState);
assign(state, initState);
assignWithState(state, initState);

```

### 🙁 Actual behavior

throw error `Type 'string | number | boolean | undefined' is not assignable to type 'never'.
  Type 'undefined' is not assignable to type 'never'.(2322)`

### 🙂 Expected behavior

don't throw error

**Comment by RyanCavanaugh** [comment]
Each of these behaviors is the intended one. Generic and non-generic code checking identically is not an invariant.
