### ISSUE TITLE
verbatimModuleSyntax not work with namespace at top level

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#52461]
# Bug Report

verbatimModuleSyntax not work with namespace

### 🔎 Search Terms

verbatimModuleSyntax

### 🕗 Version & Regression Information

5.0.0-beta

### ⏯ Playground Link

N/A because need a package.json

### 💻 Code

```json
{
    "type": "module",
        "dependencies": {
                "typescript": "5.0.0-beta"
        }
}
```

```ts
export namespace T {
        export enum A { a = 1 }
}
```

> npx tsc --moduleResolution NodeNext --module NodeNext --verbatimModuleSyntax .\index.mts

### 🙁 Actual behavior

```
index.mts:1:1 - error TS1287: A top-level 'export' modifier cannot be used on value declarations in a CommonJS module when 'verbatimModuleSyntax' is enabled.

1 export namespace T {
  ~~~~~~


Found 1 error in index.mts:1
```

### 🙂 Expected behavior

works

**Comment by jakebailey** [comment]
Based on the test, I'm pretty sure this is intended. https://github.com/microsoft/TypeScript/blob/main/tests/cases/conformance/externalModules/verbatimModuleSyntaxRestrictionsCJS.ts#L32

**Comment by DanielRosenwasser** [comment]
The error is not the `namespace`, it is the use of a top-level `export`. I'd expect you need to write the following:

```ts
namespace T {
    export enum A { a = 1 }
}

export = {
    T
}
```

**Comment by DanielRosenwasser** [comment]
Oh, but this is in a `.mts` file with `"type": "module"`

**Comment by andrewbranch** [comment]
Are you telling me there’s a more reliable way to determine the module kind than `Math.random() > 0.5`? I gotta go update a lot of code if so...

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/216756271-a97046ac-ebd2-4eff-b198-50a0e0a4e5eb.png)

does #52555 also fix this?

**Comment by andrewbranch** [comment]
What tsconfig settings do you have there?
