### ISSUE TITLE
Typo in diagnostic message for file exists

### ISSUE THREAD

**Issue by sroucheray** [microsoft/TypeScript#52462]
# Bug Report

When enabling `traceResolution`, there is a small typo with the message when a file exists. The `s` is missing in `exists`.

### 🙁 Actual behavior

> "======== Resolving module './a.js' from '/project/main.ts'. ========",
> "Explicitly specified module resolution kind: 'Bundler'.",
> "Loading module as file / folder, candidate module location '/project/a.js', target file types: TypeScript, JavaScript, Declaration, JSON.",
> "File name '/project/a.js' has a '.js' extension - stripping it.",
> "File '/project/a.ts' **exist** - use it as a name resolution result.",
> "======== Module name './a.js' was successfully resolved to '/project/a.ts'. ========",

### 🙂 Expected behavior

> "======== Resolving module './a.js' from '/project/main.ts'. ========",
> "Explicitly specified module resolution kind: 'Bundler'.",
> "Loading module as file / folder, candidate module location '/project/a.js', target file types: TypeScript, JavaScript, Declaration, JSON.",
> "File name '/project/a.js' has a '.js' extension - stripping it.",
> "File '/project/a.ts' **exists** - use it as a name resolution result.",
> "======== Module name './a.js' was successfully resolved to '/project/a.ts'. ========",

**Comment by sroucheray** [comment]
I have a branch to fix it but I saw that I should not submit PR for the only purpose of a typo. Not sure what I should or should not do then.

- branch: https://github.com/PerfectMemory/TypeScript/tree/fix/diagnostic-messages-typo
- diff: https://github.com/microsoft/TypeScript/compare/main...PerfectMemory:TypeScript:fix/diagnostic-messages-typo?expand=1

**Comment by fatcerberus** [comment]
AFAIK the ban on typo fix PRs mainly applies to typos in code/documentation (such as comments).  A typo in an error message on the other hand feels to me like a bona fide bug.  TS team has the final say, of course.

**Comment by sroucheray** [comment]
OK, then I submitted my PR #52464

**Comment by sroucheray** [comment]
Made another PR because some lib files weren't meant to be updated.

**Comment by DanielRosenwasser** [comment]
Thanks @sroucheray!
