### ISSUE TITLE
`@overload` doesn't work for constructors

### ISSUE THREAD

**Issue by anonbergine** [microsoft/TypeScript#52477]
# Bug Report

### 🔎 Search Terms

"jsdoc overload"
"constructor overload jsdoc"
"overload jsdoc example"

### 🕗 Version & Regression Information

I've only just tried using this feature. Specifically based on the recent merged PR https://github.com/microsoft/TypeScript/pull/51234 which is intended to fix https://github.com/microsoft/TypeScript/issues/25590

- I was unable to test this on prior versions because https://github.com/microsoft/TypeScript/pull/51234 was not merged.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=9&jsx=0&module=7&filetype=js#code/PTACBcGcFoGMAsCmsDWAoNwBUaCSACAdwEMA7cfAZnwAdiAnYgW31gHsmAjAS1OPG5tSkfADM29VkPD0ArrHAS0ACmL4yAE3yd19RPg3dRoxPXL5wATxqJIASgBcGUokL4AYmzbK7aF289vYl9-Dy9lThDXMKCAGkiMAhJzRQNEUV59NgA3UwAbNmINEVlIXgBzfAApAGUAETZYWPxuDURiPLzLWLROWQpCNlk8rUhEcHA8-UJucHh1AwA6KDFuKcX8AlgyAHIKDNINNDJLKSQ9c0QAD2YaKZE2OdMLeDIXrJcW0nwmU3LEI4ABQASs1CPBuAgDGxbPhSI98GNECxUoN6CgxBIpMIZPJFPRIIs0FhgBg0LA8sRICJAvgAN5ofBM-AAYmIjOZLM4GGZ+GwOF5+Cw+FAOXyhSOguFoHYOLkCiUUpFdEYLDpkBkFQAvuoOczpSrmPTSLIuKYddypSABbzpWL6AUinqmdLZRr5fjnULlQwjXSTWb6Dr2VbsF67bkHRLwyK3biFfQY6BDWr3drdaGbfrY0J3XjFbbSby4x6JKpmpF6V7mXNuIS2fgALwZwVM2v1nTNy3MrVoXtobIMBbN0KBHwDoeduHRMc7d07XyDySwJvTgLhABMi6HWhHM-Cc5kO2aW7QQA)

[screenshot of playground](https://user-images.githubusercontent.com/120770250/215263059-3c4f1ab2-ea09-4433-9aee-897ba568c4fa.png)

### 💻 Code

```es6
//@ts-check

/*
I want following overloads for contructor
(a and b are differnt types):

new Foo()
new Foo(a)
new Foo(b)
new Foo(a,b)

I want to define overloads using JSDoc, ideally,
but would settle with a d.ts file. I can't find
any coherent examples other than the one in merged
PR, which does not seem to work for constructors.
*/

class Foo {
    #a
    #b

    /**
     * @overload
     * @constructor
     * @param {string} a
     * @param {number} b
     *//*
     * @overload
     * @constructor
     * @param {number} a
     *//*
     * @overload
     * @constructor
     * @param {string} a
     *//*
     * @constructor
     */
    constructor(a, b) {
        this.#a = a
        this.#b = b
    }
}

var a = new Foo()
var b = new Foo('str')
var c = new Foo(2)
var d = new Foo('str', 2)
```

### 🙁 Actual behavior

Code hints are not indicating the presence of overloads, and type checking does not seem to be applied correctly based on parameter combination.

### 🙂 Expected behavior

While instantiating the class I would expect to see the "up/down" arrows in the code hint that indicates presence of overloads (and allows cycling through the hints for the various overloads). I would also expect type checking to be applied properly.

**Comment by sandersn** [comment]
Initial notes:

1. `@constructor` is unexpected in the middle of an overload, and is only useful to the checker for marking constructor functions.
2. All the but first comments start with `/*` instead of `/**`.

I'm trying to get it work after removing `@constructor` and adding asterisks.

**Comment by sandersn** [comment]
Yep, neither getReturnTypeOfSignature nor checkCallExpression recognised `@overload` and were returning `any` + an error.
