### ISSUE TITLE
isSourceFileDefaultLibrary does not return true for files loaded from `@typescript/lib-xxx`

### ISSUE THREAD

**Issue by uhyo** [microsoft/TypeScript#52480]
# Bug Report

### 🔎 Search Terms

isSourceFileDefaultLibrary

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _?_

### ⏯ Playground Link

N/A

### 💻 Code

1. Prepare a project that installs a custom `@typescript/lib-es5` package. (`npm i -D better-typescript-lib` is enough, for example)
2. Run below code.

```ts
import typescript from "typescript";

const program = typescript.createProgram({
  rootNames: ["src/ts-bug-check.ts"],
  options: {}
});

const sf = program.getSourceFile("node_modules/@typescript/lib-es5/index.d.ts");
if (!sf) throw new Error("!!!!")

// Should print true, actually prints false
console.log(program.isSourceFileDefaultLibrary(sf));
```

### 🙁 Actual behavior

`program.isSourceFileDefaultLibrary(sf)` returns false.

### 🙂 Expected behavior

`program.isSourceFileDefaultLibrary(sf)` should return true since that file is loaded in place of TypeScript's built-in `lib.es5.d.ts` file.

## 🗻 Context

https://github.com/typescript-eslint/typescript-eslint/issues/6207

TypeScript-ESLint uses `isSourceFileDefaultLibrary` to check whether an object is an instance of TypeScript's built-in `Error` class. However, if the rule is used with `better-typescript-lib` which installs `@typescript/lib-xxx` packages, it no longer works. 

> Then I guess that `isSourceFileDefaultLibrary` doesn't return true for the file because essentially its check boils down to `filename.startsWith('node_modules/typescript/lib/')`. IDK if that's a bug or intentional... regardless it's the behaviour!

**Comment by RyanCavanaugh** [comment]
Detecting things in `lib` vs anywhere else is the purpose of this function. Maybe you want `isSourceFileFromLibrary` instead? See also https://github.com/microsoft/TypeScript/issues/25225#issuecomment-400307897

**Comment by uhyo** [comment]
@RyanCavanaugh Thanks for reply, but unfortunaltely `isSourceFileFromLibrary` doesn't seems like what we want.

First of all, `isSourceFileFromLibrary` still returns `false` for above repro.

```ts
import typescript from "typescript";

const program = typescript.createProgram({
  rootNames: ["src/ts-bug-check.ts"],
  options: {}
});

const sf = program.getSourceFile("node_modules/@typescript/lib-es5/index.d.ts");
if (!sf) throw new Error("!!!!")

// Still prints false
console.log(typescript.isSourceFileFromLibrary(program, sf));
```

Second, the definition of `isSourceFileFromLibrary` is `program.isSourceFileFromExternalLibrary(node) || program.isSourceFileDefaultLibrary(node)` which isn't quite what we want.

As I understand, when TypeScript finds a `@typescript/lib-es5` in `node_modules`, TypeScript loads `@typescript/lib-es5` in place of TypeScript's built-in `lib.es5.d.ts`. That's why I expect `program.isSourceFileFromDefaultLibrary('node_modules/@typescript/lib-es5/index.d.ts')` to return true. It's not a random lib file in `node_modules`, but a special one regarding that TypeScript treats it as if it is a built-in default library file.

Hope above explanation makes sence 🥺

**Comment by RyanCavanaugh** [comment]
Looking through the code, it doesn't seem like we actually *track* that exact piece of information - it's used for reference resolution during program creation but then not needed after that. If I'm mistaken please let me know.

**Comment by RyanCavanaugh** [comment]
You may want to check to see if the source file contains `/// <reference no-default-lib="true"/>` - that might be equivalent to what you're trying to check for?

**Comment by uhyo** [comment]
Oh, two days is a little bit too rapid... 🥲 
Anyway I see that it's not a good idea to manipulate the current behavior of `isSourceFileDefaultLibrary`. As you suggested, I'll try to find alternative solution. Thank you.
