### ISSUE TITLE
Property 'contentVisibility' does not exist on type 'CSSStyleDeclaration'.

### ISSUE THREAD

**Issue by Ayc0** [microsoft/TypeScript#52497]
# Bug Report

When accessing `element.style.contentVisibility`, TS sends this error:

> Property 'contentVisibility' does not exist on type 'CSSStyleDeclaration'. (2339)

But according to https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration#css_properties, all supported CSS properties are injected in camel-cased.

> Dashed and camel-cased attributes for all supported CSS properties.

And `content-visibility` is standard: https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility

### 🔎 Search Terms

`contentVisibility`, `CSSStyleDeclaration`

### 🕗 Version & Regression Information

I don't know

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAJgSwG4wLzxMArgWwKZhQB0wATngIZR4CiANnvoQBQDkiSrAlANwBQfDkWgBPBiXDVCANQQQEAIwR0EUEWhiskcxQ1ZA)

### 💻 Code

```ts
const div = document.createElement('div');

div.style.contentVisibility = 'visible'
//             ^ throws: Property 'contentVisibility' does not exist on type 'CSSStyleDeclaration'
```

### 🙁 Actual behavior

`contentVisibility` isn't defined in the `CSSStyleDeclaration` interface

### 🙂 Expected behavior

`contentVisibility` should be added as `string`

**Comment by MartinJohns** [comment]
`content-visibility` is part of the CSS Containment Module Level 2 spec, which is still an editor's draft. Usually TypeScript waits for the spec to be done before adding types. You can add the types locally yourself using declaration merging.

**Comment by MartinJohns** [comment]
And fyi, the dom library lives in this repository: https://github.com/microsoft/TypeScript-DOM-lib-generator
