### ISSUE TITLE
Required<...> doesn't work anymore when using --exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by DerGernTod** [microsoft/TypeScript#52494]
# Bug Report

### 🔎 Search Terms

exactOptionalPropertyTypes, Required

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about exactOptionalPropertyTypes (didn't find any)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=5.0.0-dev.20230130#code/CYUwxgNghgTiAEYD2A7AzgF3mpBbEAalBAFzwBKIAjgK4CWcwAPAN4BQ8n8AZigPwAKANYgAnmUww6KAOYBKCRimz4AH3goaECAG42AXwB8enPiIQAdLwEAiG3J1A)

### 💻 Code

```ts
declare const someVal: Required<{
    fn?(key: string): string | null;
}>;
someVal.fn(""); // Cannot invoke an object which is possibly 'undefined'.(2722)
```

### 🙁 Actual behavior

TS shows the an error for the function call: Cannot invoke an object which is possibly 'undefined'.(2722)

### 🙂 Expected behavior

I expect no error because the type definition already makes clear that all functions in that type are required, none optional.

**Comment by Andarist** [comment]
It seems that the "method" syntax is somehow affected here because it works with properties:
```diff
declare const someVal: Required<{
-    fn?(key: string): string | null;
+    fn?: (key: string) => string | null;
}>;
someVal.fn("");
```

This is not an equivalent change so don't apply it blindly. Just mentioning this as an interesting fact that might help somebody to debug this.

**Comment by fatcerberus** [comment]
> This is not an equivalent change

In particular: [Method parameters are always compared bivariantly](https://github.com/microsoft/TypeScript/pull/18654) during a structural assignability check, even with `strictFunctionTypes` enabled.

From #18654:
> Methods are excluded specifically to ensure generic classes and interfaces (such as Array<T>) continue to mostly relate covariantly. The impact of strictly checking methods would be a much bigger breaking change as a large number of generic types would become invariant
