### ISSUE TITLE
VS2015 font is not used in TS window

### ISSUE THREAD

**Issue by WaldemarH** [microsoft/TypeScript#5250]
I've just installed the VS2015 for testing it out and there were two issues:
• [bug] TS windows doesn't respond to font changes.

For the test I've set it to 16, but TS window did not respond to size change.
Luckily if you close the VS and reopen it again TS uses the proper font.

![font](https://cloud.githubusercontent.com/assets/5547441/10481397/a2b0feb6-7270-11e5-9fe0-1eed71fb2ee2.png)

• [annoyance] Since I've installed VS2015, VS2013 lost the TS editor. So I'm forced to use VS2015, even if it was installed just to test it out.

Br
Waldemar

**Comment by MarcelDevG** [comment]
This also happens after installing update1/typescript version 1.7.4.0. However, restarting vs2015 sometimes helps....

**Comment by wgv-sethlivingston** [comment]
I was able to fix this by re-running the TypeScript for Visual Studio 2015 extension installer and selecting "Repair".

**Comment by xumix** [comment]
Same here, "Repair" does not help

**Comment by paulvanbrenk** [comment]
If after you change the font (size) you restart VS you should see the new font picked up.

**Comment by nicholashead** [comment]
Experiencing this same issue. I'm using the input font: http://input.fontbureau.com/ if that makes any difference/helps debug.

**Comment by paulvanbrenk** [comment]
@nicholashead does restarting VS after changing the font fix it for you?

**Comment by nicholashead** [comment]
@paulvanbrenk yes it seems to most of the time. Sometimes I have to restart more than once.

**Comment by nicholashead** [comment]
Perhaps my issue isn't exactly the same - but basically VS "text editor" font will be set, and will be working for .JS/.HTML/.CSHTML etc just fine -- but then I'll load a .TS file, and it will be showing a totally different size font; smaller than I set my "text editor" settings to (not sure if same font or not-- hard to tell at small size). If I go fiddle with font settings in VS options, save, then restart VS, usually the .TS editor will come up properly again. I have no idea what triggers it to be wrong font size/etc.

**Comment by paulvanbrenk** [comment]
@nicholashead we do some weird things with our colorization and fonts for perf. reasons and we haven't gotten the switching behavior quite right :(

We hope to have a better fix for Visual Studio "15", since it does require changes in the core of VS.

**Comment by MarcelDevG** [comment]
@nicholashead , @paulvanbrenk How many monitors are you using?
I've three, but mostly use vs2015 on only one (the main).
Since the latest updates, i've had it happen only once.

**Comment by nicholashead** [comment]
@MarcelDevG just one monitor - actually running VS inside a Parallels VM on Windows 10 Pro. Up to date VS 2015 (as far as the auto-update stuff is concerned anyway). And latest Resharper.

**Comment by xumix** [comment]
Mayby Resharper is the core of the issue? I use it.

**Comment by MarcelDevG** [comment]
@xumix , I do not use Resharper, so that's not it....

**Comment by apogee72** [comment]
I installed vs 2015 without any extensions, still got this issue. Restarting doesn't help

**Comment by ericop** [comment]
Same story here. Only happens with `*.ts` files and after restart the font jumps back to the larger size that matches every other file extension.

**Comment by RyanCavanaugh** [comment]
This seems to have not affected anyone in the last ~4 years, so I'm assuming it's either been fixed or only repros in some extremely limited set of circumstances that wouldn't warrant further investigation.
