### ISSUE TITLE
JSDoc Comment Template not provided when unrelated JSDoc with tag exists

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52517]
JSDoc comment templates don't work if you have a preceding JSDoc comment declared using a `@typedef` or an `@overload` tag.

```ts
/** @typedef {string} Id */

/**$ */
function foo(x, y, z) {
}
```

Request `docCommentTemplate`.

The following is expected:

```js
/** @typedef {string} Id */

/**
 * 
 * @param x 
 * @param y 
 * @param z 
 */
function foo(x, y, z) {
}
```

But instead we get:

```js
/** @typedef {string} Id */

/**
 * 
 */
function foo(x, y, z) {
}
```

_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/52370#issuecomment-1409159563_

**Comment by shogohida** [comment]
Hi @DanielRosenwasser , can I work on this? Should I change these lines?

https://github.com/microsoft/TypeScript/blob/main/src/services/jsDoc.ts#L201
https://github.com/microsoft/TypeScript/blob/main/src/services/jsDoc.ts#L243
