### ISSUE TITLE
[5.0] Unable to explicitly write type annotation for constant used as enum initializer

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#52510]
# Bug Report

### 🔎 Search Terms

enum const initializer type

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because this feature is only supported starting from TS 5.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?declaration=false&isolatedModules=true&ts=5.0.0-dev.20230130#code/MYewdgzgLgBAwuaBGGBeGSAMBuAsAKFElgFMwBXAWxgFELKUBvAmVmAMQEsAnaNeRFCQAaFmwDKJIgBMCAXwIEifBMQBMALgyZ+WPIUEwyVWvTUxm+Nhx590q6GtFWJU8LPwL8Sww6gBmXR0AQwgYZSh9CKN6UypAy2suXlh7QX9na0kZeUUDYgFiABYtegAjEm4gqMNjajoqIosxVmS7QugizNcczwIgA)

### 💻 Code

```ts
const Const1 = 10;
const enum Enum1 {
    First = Const1,
    Second
}

const Const2: 10 = 10;
const enum Enum2 {
    First = Const2,
    Second
}

const Const3 = 10 as const;
const enum Enum3 {
    First = Const3,
    Second
}

const Const4: number = 10;
const enum Enum4 {
    First = Const4,
    Second
}
```

### 🙁 Actual behavior

The first enum is valid. For all the other ones, TS reports `const enum member initializers must be constant expressions.`

### 🙂 Expected behavior

At least the second and third enums should be valid, because their initializer is a reference to a `const` variable with a fixed type. Maybe also the fourth one could work, but I wouldn't be surprised if it doesn't.

**Comment by liuxingbaoyu** [comment]
![image](https://user-images.githubusercontent.com/30521560/215513721-31d2b23d-0e95-4626-a87b-d9f826b9fc64.png)
It's weird, but probably not supported by a good method.
```ts
const a = 10;
const b = (a as 1);
const enum Enum1 {
     First = b,
     second
}
```

**Comment by nicolo-ribaudo** [comment]
Thanks for the explanation!

> Constant expression evaluation is performed independently of type analysis. To evaluate a constant expression we recursively evaluate the initializers of any referenced constants without paying any attention to type annotations.

I'm confused then to why adding a type annotation to the `const` variable makes the constant expression evaluation refuse to accept that variable. Adding a type annotation doesn't change the fact that it's value is constant and as much statically analyzable as not having the type annotation.

**Comment by ahejlsberg** [comment]
It would indeed be possible to ignore the type annotations and just evaluate the initializer expressions, but we then run into inconsistencies with `declare` and `.d.ts` files as I mention above.
