### ISSUE TITLE
Typescript loses constraint of `satisfies` on initial value/accumulator for Array.prototype.reduce

### ISSUE THREAD

**Issue by DesignByOnyx** [microsoft/TypeScript#52526]
### 🔎 Search Terms
- satisfies
- reducer
- nested array

### 🕗 Version & Regression Information

- v4.9.4 - I assume this affects `>=4.9.0` when the `satisfies` operator was introduced

### 💻 Repo

``` ts
type ParseResult = { errors: Error[] }

'foob@r'.split(' ').reduce((acc, part) => {
    if (/^\w+$/.test(part)) {
        acc.errors.push(new Error('Not a valid term'));
        //              ^^^^ Argument of type 'Error' is not assignable to parameter of type 'never'.
    }
    return acc;
}, { errors: [] } satisfies ParseResult)
```

[Playground](https://www.typescriptlang.org/play?ssl=18&ssc=46&pln=1&pc=1#code/C4TwDgpgBACghgJwM4QEoSQVwDbCgXigG8oIEEB7ZALigFFyqBtAXSgF8AoTgegCo+UACoALaADMK2bBQDuASwB2Acyji487EiiZFEAB6QAxsAgATbCCh8enAOSSKAIwACCOwDokYbPOAAKOyg7AEoPBHNMIwh-fzgjIwAaKDBEYBCCAD5iTig8qHlxKH8eAD0AHVkAagASHg9TJADUhHSMolz8rvijDzJKZA8wTCQRfz1ZekYEQIA5Cjw4KAA3OF8zKFMEAFtQkIBuTryuLojgTARFKB7D9mSSfqokWlYOKCQ4YHkkcXkMWEQKHQWFwIW4vAEwjEaikMgUKigsioAGskMknJg8MBoUo-PI1is1phoGYKP9FAt3p9vuIrPBkGgMDg8DZ7I5XO4vD4-IFgmEImYojE4glki10lkcl1CsUypVavVGs00iF2kcutcEn1pkghiMxhMpgM5pSlqt1psyLtVYcuid8mcLlcbpw7sRSDqXixko5aHYnIgguxrtp6UCmaCgA)

### 🙁 Actual behavior

The accumulator loses some of that information from the `satisfies` constraint, especially as it pertains to arrays. Typescript incorrectly thinks the `errors` array is type `never[]`. 

### 🙂 Expected behavior

The `errors` array should have the same type as asserted with the `satisfies` operator. As you can see in the playground, you can use the `as` operator, but you lose all of the benefits that `satisfies` provides. In my head, the `satisfies` operator is the same as `as`, but with actual type checking happening on the operands.

**Comment by DesignByOnyx** [comment]
I had too narrow of a search before I opened this. I see the duplicates now. Apologies for the noise.

**Comment by fatcerberus** [comment]
@DesignByOnyx Your issue got auto-labeled as a dupe because you probably used the template for 9998 dupes (“types not correct in/with callback”, which has to do with type guards and is totally unrelated), but it’s good that you found the *actual* dupe anyway. 😄
