### ISSUE TITLE
Get the type of the call signature from a literal object

### ISSUE THREAD

**Issue by cangSDARM** [microsoft/TypeScript#52528]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5&ssl=46&ssc=48&pln=45&pc=1#code/MYGwhgzhAECCBGB7ATgFwKLOSgwuK0ApgB6qEB2AJjJtstAN4C+AsAFDuoCeADodAHkeqAJaJyMALyN20OdGSFUyEYQgAuaOQCuAW3iFk7VhzaVCoMIujBxEVNB4AlJci6aG7AJAAeACoAfAAU3l4i5DzaqJpBYKhkusI4iNrk0Vp6BsgAlNCSAdAACti6IhCEADIiANaE-gUAPtB+ADShiMJiEgD8mkKidt7ZmsWIpeX1ANzs3ggoGFgomtx8iABmcEhotLj4ENNsXuZrYNog6SuE644uylwHTAczZhbg1rYSDgBi5B7esZp7CpyABzYbQIHhEHeHjYPhoETcQHKKHGZ4fezQADuyDAPGWvCuG2cri4eWgQVy+UYJgA9LT5HIAHrdZ7sekMiCIEBRLrQACMfVKqE4hOgAElyGtDDgwCAQPz6uSBML-C1oLUuNdAuyGViULVKNA1igbqT2BiHDi8QBlQUSqUyuUKnyXa4ku4BbzSSl5ArMXXQLhKLSIK0GwhGk30H4WuxW3E8O0-TSS6XIWXyxVujY-L2HaT8rz06DwSAiYDOrjqxEAchgYGgAAMwOQuE3oJddbSALR9-sDwdDwfPDkQ7m88TQABMmnC6c7hNFfAd6czIGnSukfiIpAo1BkhyCADpT1YQRpoPPDEUrGBdBBwdf6LdoMZoN0Kafj+fL4U7w+VIFK+mjkIQABuhijnqEZRqasZsJcxrkOu5Jpk68qbjm0B5oG5BhtisFmncy78B6bioZI3joRmzpYYS7q3G4ATFgyIIUIYFYNtYILiIQ7BAA)

### 💻 Code

```ts
// see playground
```

### 🙁 Actual behavior

I cannot get the type of its call signature

### 🙂 Expected behavior

Get the type of the call signatures from literal object

**Comment by MartinJohns** [comment]
You can just use: `Omit<typeof pRetry, keyof typeof pRetry>`

**Comment by cangSDARM** [comment]
This doesn't look very crisp, and it's a very odd workaround if you ask me.
