### ISSUE TITLE
tsserverlibrary.js includes reference to `require` that causes webpack to complain

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#52521]
# Bug Report

### 🔎 Search Terms

- webpack
- `require`
- `tsserverlibrary`

### 🕗 Version & Regression Information

5.0.0-dev.20230130

### Problem
The latest `tsserverlibrary.js` contains a line:

```ts
 var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
  }) : x)(function(x) {
    if (typeof require !== "undefined")
      return require.apply(this, arguments);
    throw new Error('Dynamic require of "' + x + '" is not supported');
  });
```

This causes webpack to complain:

```
WARNING in ../node_modules/typescript/lib/tsserverlibrary.js 21:75-82
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./web/webServer.ts 32:24-65
```

As far as I can tell, `__require` isn't used anywhere in the file either. Can we remove it?

/cc @jakebailey

**Comment by jakebailey** [comment]
The new build removes all references to this function, but I opted to not remove the function itself as that's a little more complicated than the simple regex replacement I'm doing now.

> Can we remove it?

Just to clarify, is this a request that we remove it from the TypeScript side, or are you only asking if it's safe to remove on your end? If the latter, yes, it's safe to remove or ignore entirely.

If the former, I can try and come up with something.

**Comment by mjbvz** [comment]
@jakebailey Thanks for the info. If possible, I'd prefer it be removed on the TS side so we don't have to monkey patch the code on the VS Code side

**Comment by jakebailey** [comment]
I'll send a PR which fixes this shortly. Wasn't actually that bad.

**Comment by jakebailey** [comment]
Sent #52522. Arguably, webpack should detect that this is an unused function and/or that it's `@__PURE__` but, this is a reasonable cleanup.
