### ISSUE TITLE
AMD emit fails to preserve temporal dead zone semantics for exports

### ISSUE THREAD

**Issue by dgoldstein0** [microsoft/TypeScript#52539]
# Bug Report

### 🔎 Search Terms

emit amd temporal dead zone

### 🕗 Version & Regression Information

This bug exists in every version of typescript.  Tested with the current nightly (5.0.0-dev.20230131), 4.9.4 and 3.3.3333 on the playground

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?module=2&ts=4.9.4#code/MYGwhgzhAEBiD29oG8C+AodBTAHgB3gCcAXaELUgM0WgF5oB9ASwDsniF4AKASgG50lAK4tgxJvBaNW7TrwBccGsnTRo1JPRZYA7ku79oAeiPQASlkpZCWUVgCihQkUUboAE3hYYLeKVxMEKQAnhTQABbWWB5ChKwA5tDEkdBgAEbwAG7RwGAgIElIzGwciAA0qTDJ0eSkQWDEWAC2tqThkCwA5FQyEJHu0LhYwELiLPGq0DbEsVIaAqgCwJIQ8OQAdCDw8Vwa-EA)

### 💻 Code

```ts
class Foo {}

export let foo = _initFoo();
function _initFoo(): Foo {
  foo = new Foo(); // ReferenceError: foo does not exist yet here during the above call to _initFoo, as the let statement hasn't finished executing
  return foo;
};
console.log(foo);
```

this code is compiled with `--module AMD` and `--target ES2017` (though as long as target is >= ES2015 I think the bug is the same). 
### 🙁 Actual behavior

The emitted AMD does not preserve the temporal dead zone semantics because the `export let` does not stay as a `let`, and thus generates code that does not throw the ReferenceError.  Note that it's important that `let foo` is `export`ed; without the export, the bug doesn't occur.

```
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.foo = void 0;
    class Foo {
    }
    exports.foo = _initFoo();
    function _initFoo() {
        exports.foo = new Foo(); // ReferenceError on `foo` should occur here, but doesn't.
        return exports.foo;
    }
    ;
    console.log(exports.foo);
});
```

However is we switch to generating ESNext, we get
```
class Foo {
}
export let foo = _initFoo();
function _initFoo() {
    foo = new Foo(); // ReferenceError: foo does not exist yet here during the above call to _initFoo, as the let statement hasn't finished executing
    return foo;
}
;
console.log(foo);
```

and in this case the ReferenceError occurs as expected.

### 🙂 Expected behavior

The AMD and the ESNext module output should behave the same.  Namely, this means that either both of them should raise the ReferenceError (most sane) or neither (less reasonable).

A possible solution would be to treat `export let foo = ...;` as `let foo = ...; export {foo};` which seems to result in emit that does include the `let` and thus the TDZ semantics.  [Playground link](https://www.typescriptlang.org/play?module=2&ts=4.9.4#code/MYGwhgzhAEBiD29oG8C+AodICmAXaAZotALzQD6AlgHaW4LwAUAlANzoECu1wul81CjToMWALjjFk6aIWJlq2AO6SmbaAHoN0AErYC2AE7Ye2AKKHD8QxKJIAJvGwxq8fNgAelCPgCeeaAALI2xoe05DGgBzaFxg6DAAI3gAN1DgMBAQWKQqWnpEABoEmDjQnHwfMFxsAFsTfEDIagByfAJhCGD7aE9sYE4+aiiZaGNcCME7dlR2YAEIeBwAOhB4KMY7NkxPAAdrfGQ7VCA)

I encountered this because we have a dev build which outputs AMD, and a prod build which outputs ESNext and then uses rollup to bundle and output AMD, and we ended up with a ReferenceError like above as a production-only bug.

**Comment by RyanCavanaugh** [comment]
I don't think we want to touch this with a ten foot pole. People might have taken unintentional dependencies on this behavior, which has been present forever. The question of what ES module code even *means* in an AMD output context is subject to some reasonable debate -- not 100% of the semantics can be preserved, especially under the constraint of having reasonable emit. The same problem can be observed in targeting ES3 - `let` turns into `var` and code that would have TDZ'd won't.

**Comment by dgoldstein0** [comment]
--target ES3 is at least consistent in using `var` no matter what --module is used, so it's not quite the same.

I think it's reasonable to expect `export let foo = ...` and `let foo = ...; export {foo}` tranpsile to something that behaves the same, which under --module AMD output, they clearly differ (with a new enough --target, `let` is preserved in the latter but not the former and therefore the TDZ behavior differs).

I also think it's reasonable to expect that if I compile typescript to module=AMD, or compile typescript to module=ESNext and use another tool to compile the output to AMD, that I'd get the same behavior.  And this bug is an exception to that.

That said I'm sympathetic that this would be a breaking change.  We could put it behind a flag to make it opt in (or opt-out?) though I don't love that answer as proliferating flags isn't ideal either.  But might be the only possible compromise.
