### ISSUE TITLE
Better auto import piority

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#52533]
Open `foobar.mts` and type `readFile`

current auto import piority
- `import { readFile } from "fs"`
- `import { readFile } from "fs/promises"`
- `import { readFileSync } from "fs"`

expect auto import piority, prefer modern async style over callback style when possible
- `import { readFile } from "fs/promises"`
- `import { readFile } from "fs"`
- `import { readFileSync } from "fs"`

**Comment by RyanCavanaugh** [comment]
99% of the time, the difference between `x from foo` and `x from foo/bar` is that `x` is a barrel re-export from `bar` and is the preferred import. We don't intend to special-case node libraries to get special treatment here; all options are displayed and you can pick the one you want.

**Comment by loynoir** [comment]
@RyanCavanaugh 

Ah, not sure why this editor feat is transfer to language scope.

I don't mean to let typescript add special-case, I mean something like **user config within editor**.

`.vscode/settings.json`

```json
  "vscode.typescript.autoImport.suggestions": [
    {
      "prefix": "readFile",
      "suggestions": [
        {
          "source": "fs/promises",
          "imported": "readFile"
        },
        {
          "source": "fs",
          "imported": "readFile"
        },
        {
          "source": "fs",
          "imported": "readFileSync"
        },
      ],
    },
  ],
```

**Comment by fatcerberus** [comment]
> Ah, not sure why this editor feat is transfer to language scope.

Because the functionality in question is implemented in the TS language service, not VSCode itself.
