### ISSUE TITLE
Wrong type when reassigning variable after type guard

### ISSUE THREAD

**Issue by franciclo** [microsoft/TypeScript#52547]
# Bug Report

### 🔎 Search Terms

wrong type guard undefined reassigning

### 🕗 Version & Regression Information

4.9.3

### 💻 Code

```ts
const fn = (x: number | undefined) => {
  let value = x;
  if (typeof value !== 'number') return null;
  value // value is number
  value = value - 1 // first value is number | undefined
}
```

### 🙁 Actual behavior

Value after substracting with number is of type number or undefined, after checking it for undefined type.

### 🙂 Expected behavior

Value should be number

**Comment by ahejlsberg** [comment]
This is working as intended. Quick info for a variable in an assignment position (write) always shows the declared type, whereas quick info in an expression position (read) shows the control flow type.
