### ISSUE TITLE
render not being found in ReactDom, but present in react-dom.d.ts

### ISSUE THREAD

**Issue by chrsmrtn-** [Microsoft/TypeScript#5255]
I'm currently getting my feet wet in working with react and typescript.  Super excited to see official support.  I'm working through the tutorial on react's website and writing it in TypeScript.  I hit a snag where ReactDom.render gets flagged:

app.tsx(61,10): error TS2339: Property 'render' does not exist on type 'typeof _
_ReactDom'.

I have my tsconfig.json file setup to look at a typings file which includes references to both the type files for react and react-dom.  I'm using tsd to grab my type files from the DefinitelyTyped repository.

I hope I landed in the right spot for this question.  Thanks in advance for any help you can provide.

**Comment by chrsmrtn-** [comment]
Here is the react-dom.d.ts that is being used:

https://github.com/borisyankov/DefinitelyTyped/blob/master/react-dom/react-dom.d.ts

**Comment by RyanCavanaugh** [comment]
The .d.ts file is incorrect. It's written as if you were supposed to write `(new ReactDom()).render(...)` instead of `ReactDom.render`.

**Comment by RyanCavanaugh** [comment]
I've merged in https://github.com/borisyankov/DefinitelyTyped/pull/6228 over on DT, so it should work now if you pull down the latest version
