### ISSUE TITLE
Where is the intellisense for Object.prototype methods that are available all the time everywhere?

### ISSUE THREAD

**Issue by qdirks** [microsoft/TypeScript#52563]
# Bug Report

### 🔎 Search Terms
intellisense Object.prototype

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about *Common "Bugs" That Aren't Bugs* and *Common Feature Requests*

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5ICwAUPAHaYAuoAHqALygDaAugNygigCumSCUAENyw-PiGQANKABGPGvB4AbQTiEA3FLKRJRAMx7kYVAJZxyMmMqGZMM6vlPlUM8jwC2O-DKRUYAHSktAHq2NwA6niEoKbYAAZhAPIA7uQACvhwAA4EVJDxsaJUeEVUSMrKcXr8APzBAVRwADJwMFxgABJwKcKycAqg8U2tMELKSADKVE4u8fUk3AAqePygHn44iKDkQhvYABQignAlBJgAlGIoym1C5SfFpUmyAFZIJgHZWU35uTIpHCmGA4UCYLYqQQ6IqgM6gb6nU6QXKwdTOUD6OD4OhBEikay2bAlZyoUAAbwAvqRiS5QrYOqBJnsUNEkAFQFECCg4kNkmlMjk8gUYXDnOVKtVKEgFjTUAE4gKGZyYjz4gqfkjckl9PEZJjsUhaHtshMZOjReRxVV+FKFqQXu9Pgjfsi2Qz9aBCPoucYkEA)

### 💻 Code

```ts
const x = []; // used an array, but could have been function, class, string, number, etc.
x.has // Where is `hasOwnProperty` in the intellisense?
x.toLoc // How about `toLocaleString`?
// These method names (and others) are located on the Object.prototype, which should be in the prototype chain for x.

class thing {}
thing.has // Same here. Where is `hasOwnProperty` in the intellisense?
thing.isPro // Where is `isPrototypeOf`, for example, in the intellisense?
```

### 🙁 Actual behavior

There's no intellisense for Object.prototype method names available to strings, arrays, functions, classes, numbers, and regexps, and any others that I may have missed.

Most built-ins, I think all of them, have Object.prototype in their prototype chain, and so do objects created with the `new` keyword. When I have a class like `class thing {}` and I do `let x = new thing()`, and then I want to do, say, `thing.hasOwnProperty("prop")`, there's no intellisense indicating that `hasOwnProperty` is available, and in my view, that's a bug. Someone thought this issue was better as a suggestion (#39068), but no one is assigned to it, and it has long been forgotten.

### 🙂 Expected behavior

When I do `class thing {}` and then I do `let x = new thing();`, then I should expect to be able to type `x.` and see in the intellisense window all the available methods that can be called on x, including those that are located on Object.prototype.

I can understand not having the intellisense whenever the reference is to a variable that you can't determine the type without a jsdoc hint or otherwise until runtime, or the type was determined to be null or undefined, but when you know the type is a primitive which has Object.prototype in its prototype chain, or you know that the type is a user defined class, then you should make the accessible Object.prototype methods on these objects available in the intellisense window.

I think this should be the expected behavior, because these methods are actually available, which is plain to see if you type in the console on any browser, you will see all the available Object.prototype methods when you are working with an object, an array, a function, a number, a string, etc. you can see, get yourself a value of a string, for example, and type `Object.getPrototypeOf(value).hasOwnProperty("hasOwnProperty")`, it will return false, because it's getting `hasOwnProperty` reference from the Object.prototype.

**Comment by MartinJohns** [comment]
They're intentionally not shown because in most cases they're unwanted noise. For example when accessing a type `{ a: number }` I'm in 99.9 % of the cases only interested in the property `a`, not all that stuff that comes along with it being an object.

Can't find an official statement on this right now, but I've definitely seen it.

**Comment by RyanCavanaugh** [comment]
This is the third time in ten years anyone's found it objectionable; I don't think this warrants a user preference. If this isn't the first time you've typed the name in the file (in other words, if you're really doing this often enough to want to see them) then you'll see a token completion (in VS Code at least) which is basically what you're asking for already.

**Comment by qdirks** [comment]
> This is the third time in ten years anyone's found it objectionable; I don't think this warrants a user preference. If this isn't the first time you've typed the name in the file (in other words, if you're really doing this often enough to want to see them) then you'll see a token completion (in VS Code at least) which is basically what you're asking for already.

Third time *to your knowledge*... filing a bug or feature request takes a lot of work and argument between you and the developers, and to most it's probably not worth the time or the effort to do that. I think most people, like myself and the two other people who have mentioned it, would like to have this in the intellisense.

I'm asking for the full intellisense experience on these methods, with descriptions, parameter signatures, where the methods originate from (on Object.prototype). If it's true that you're already sorting them out purposely, why not take my suggestion, sort them to the bottom of the list so that users like myself can just press up to see them?

Or take an unbiased vote. If people really don't want to see these methods in the intellisense, I would accept it, and accept only having token completion, but I think that decision was made based on how much these are used, and they don't get used that much in regular code, but there's a bias there as well... they might not get used much because they're not in the intellisense! Were they ever in the intellisense?

**Comment by qdirks** [comment]
Browsers don't filter them out in the intellisense during an interactive console session. Why do you think that is?

**Comment by qdirks** [comment]
Okay, Ryan. Well, that's your opinion. I didn't cuss you out, did I? Go ahead and close it then if that's the way you feel. Thanks for the talk. Have a good day brother.

**Comment by RyanCavanaugh** [comment]
You too!
