### ISSUE TITLE
Recursive type constraint sometimes causes type checking errors.

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#52570]
# Bug Report

### 🔎 Search Terms

recursive type constraint 

### 🕗 Version & Regression Information

- This changed between versions 4.9 and 5.0 Beta

### ⏯ Playground Link

Only happens in multi files projects in VS Code. Repo: https://github.com/dragomirtitian/recursive-type-constarint-bug-ts-5.0

### 💻 Code

```ts
/// types.ts
export type<T extends Record<string, (...params: unknown[]) => unknown>> = {
    [key in keyof T]: T[key];
};

/// index.ts
export declare const value2: {
    sliceSelectors: <FuncMap extends import('./types').SelectorMap<FuncMap>>(selectorsBySlice: FuncMap) => { [P in keyof FuncMap]: Parameters<FuncMap[P]> };
};

```

### 🙁 Actual behavior

When you first open the project in VS code you get the errors below. Any further editing of the file makes the error s go away.

```sh
Type parameter 'FuncMap' has a circular constraint.

Type 'FuncMap[P]' does not satisfy the constraint '(...args: any) => any'.
  Type 'FuncMap[keyof FuncMap]' is not assignable to type '(...args: any) => any'.
    Type 'FuncMap[string] | FuncMap[number] | FuncMap[symbol]' is not assignable to type '(...args: any) => any'.
      Type 'FuncMap[string]' is not assignable to type '(...args: any) => any'.

```

Also happens in a custom build tool using the compiler API

### 🙂 Expected behavior

The code either fails all the time or type checks all the time

Note: The circular constraint which is present above and seems to trigger the bug doesn’t seem to make much sense in our case, so we took the opportunity to clean up the types, so this is not blocking for us, but the behavior is still very strange.

**Comment by RyanCavanaugh** [comment]
> Also happens in a custom build tool using the compiler API

Would you be able to bisect this?

**Comment by dragomirtitian** [comment]
@RyanCavanaugh  First comit to error seems to be https://github.com/microsoft/TypeScript/commit/aa2781d44fb182c59a1698fcca2b3365619fb272 From this PR https://github.com/microsoft/TypeScript/pull/51766

The changes in the comin are a plausible cause. They impact type constraint checking, they are for a bug that manifests across files. The added diagnostic is lazy, which might explain some of the now you see it now you don't quality of the bug.

**Comment by DanielRosenwasser** [comment]
Should the code be declared as

```
export type SelectorMap
```

?

**Comment by jakebailey** [comment]
I sent #52861 to fix this; I _think_ this is the last of the issues reported on #52670, correct?

**Comment by dragomirtitian** [comment]
@jakebailey yup, is the last one. Thank you for the quick turn around :)
