### ISSUE TITLE
Contextual type for an array element doesn't filter out non-array union members

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#52588]
# Bug Report

### 🔎 Search Terms

array tuple contextual type inference union implicit any

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230203#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMAKAKHnlgHMAueAJXBxmAB4SYtUaAaeKVoMuPGgEp4AXgB88AG44swOQB94AQRgwoAT3ZCY9eKmQBbAEYgYk2QqUry4houUBucuUIlSAbUqCtLZyAN4BVLRu8AD00dSYyFAQDFCoulEgAB4ADuCEwAymltYBAL585AC64h5AA)

### 💻 Code

```ts
declare function test(
  arg: Record<string, (arg: string) => void> | Array<(arg: number) => void>
): void;

test([
  (arg) => {
    arg; // actual: any; expected: number
  },
]);
```

### 🙁 Actual behavior

The contextual type for array element is sourcing the information from the string indexer of the `Record` type. This makes the contextual type of this function to be `((arg: string) => void) | ((arg: number) => void)`. The contravariant position of `arg` makes its type reduce to `never` (since it's `string & number`) and prevents the expected contextual type to be provided.

### 🙂 Expected behavior

I'd expect this contextual type to only be sourced from the `Array` member

**Comment by jakebailey** [comment]
The fix has been reverted; per https://github.com/microsoft/TypeScript/pull/53280#discussion_r1138684984
