### ISSUE TITLE
Navigation Bar doesn't work correctly in class expressions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5258]
```TypeScript
var x = class Pnsndltn {
    foo() {

    }
}
```

![image](https://cloud.githubusercontent.com/assets/972891/10498673/ba7b0f40-7280-11e5-8bdb-5ee86c6ae485.png)

Compare with a class declaration:

![image](https://cloud.githubusercontent.com/assets/972891/10498683/cbfc0062-7280-11e5-8b62-c925be99e1b3.png)

**Comment by andy-ms** [comment]
Closed by #9220
