### ISSUE TITLE
place holder for tsconfig path

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#52607]
# Suggestion

place holder for tsconfig path

## 🔍 Search Terms

- tsconfig
- compilerOptions
- rootDir
- outDir
- tsBuildInfoFile

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`@my/tsconfig`
```jsonc
{
  "compilerOptions": {
    "rootDir": "${mainTSConfigDir}/src",
    "outDir": "${mainTSConfigDir}/dist"
  }
}
```

mono repo A, mono repo B mono repo C, mono repo D
```jsonc
{
  "extends": "@my/tsconfig/tsconfig.json"
}
```

## 📃 Motivating Example

Before feat

`@my/tsconfig`
```jsonc
{
  "compilerOptions": {}
}
```

mono repo A, mono repo B mono repo C, mono repo D
```jsonc
{
  "extends": "@my/tsconfig/tsconfig.json",
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist"
  }
}
```

**Comment by MartinJohns** [comment]
It sounds like you want #37227?

**Comment by loynoir** [comment]
@MartinJohns Yeah, had a glance, sounds like. but I don't agreed with `rootOrWorkspaceFolder`.

The concepts typescript have are
- an `entry/root tsconfig`
- and `tsconfig extends tsconfig`
Right?

So, typescript has no knowledge about `rootOrWorkspaceFolder`.
