### ISSUE TITLE
Weak behavior with union types and tuple

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#5260]
``` ts
var foo: [boolean, number] = [true, false]; // error
var bar: [boolean]|[boolean, number] = [true, false]; // should be error
```

related: #5237, #3842, #5203

**Comment by weswigham** [comment]
We don't consider extra elements in a tuple to be an error at present - so it's not an error because `[true, false]` matches the tuple type `[boolean]`.

**Comment by falsandtru** [comment]
Yes. So I said "weak". This is a suggestion related to those related issues.

**Comment by Igorbek** [comment]
related to #6229 (collecting use-cases)

**Comment by RyanCavanaugh** [comment]
Is error now.
