### ISSUE TITLE
Union types in then callback is not allowed

### ISSUE THREAD

**Issue by ywongau** [microsoft/TypeScript#52600]
The following line gives me a type error
```ts
(g: () => Promise<String> | number) => Promise.resolve().then(g);
```

Argument of type '() => number | Promise<String>' is not assignable to parameter of type '(value: void) => String | PromiseLike<String>'.
  Type 'number | Promise<String>' is not assignable to type 'String | PromiseLike<String>'.
    Type 'number' is not assignable to type 'String | PromiseLike<String>'

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by fatcerberus** [comment]
@RyanCavanaugh It likely *wasn’t* pre-populated with the template and instructions because it looks like OP used the issue template for 9998 duplicates 😉
