### ISSUE TITLE
Type guard for nullability is inconsistent

### ISSUE THREAD

**Issue by JPtenBerge** [microsoft/TypeScript#52619]
Hi there!

I have an issue with the default nullability type guard. I've reproduced it to this bit of code:

```ts
interface Foo { x: number; }

export class Demo {
	list = [{ x: 24 }, { x: 42 }];
	foo: Foo | null = null;

	work() {
		if (!this.foo) {
			return;
		}
	
		console.log(this.foo.x); // fine, no problem
		console.log(this.list.findIndex(val => val.x === this.foo.x)); // error, Object (this.foo) is possible null!
	}
}
```
I found it strange at first, as I'm checking the value right before. It's also easily enough fixed:
```ts
let x = this.foo.x;
console.log(this.list.findIndex(val => val.x === x));
```
It's just a bit annoying, really. But I get that the compiler doesn't fully check everything down because of performance reasons and whatnot. I'd get over it if wasn't for this strange inconsistency I ran into. If I remove the class from the picture:
```ts
interface Foo { x: number; }

let list = [{ x: 24 }, { x: 42 }];
const work = (foo: Foo | null) => {
	if (!foo) {
		return;
	}

	console.log(foo.x); // fine
	console.log(list.findIndex(val => val.x === foo.x)); // fine too!
};
```
Then everything works fine. No errors with that code, it's all good.

I think it's a bug? Should this inconsistency make sense somehow? Does the type guard differentiate between parameters, class members, `this`-references?

**Comment by fatcerberus** [comment]
Duplicate of #9998.  In general, type narrowings are lost at closure boundaries.  There are a few exceptions, like for function parameters that aren't reassigned to anywhere in the function, but that's the general rule.

There's actually an issue template explaining this, but weirdly, people who actually run into this seem to overlook it and it only ever gets clicked for unrelated issues:
https://github.com/microsoft/TypeScript/issues/new?assignees=&labels=Duplicate&template=types-not-correct-in-with-callback.md&title=

**Comment by JPtenBerge** [comment]
>Duplicate of https://github.com/microsoft/TypeScript/issues/9998. In general, type narrowings are lost at closure boundaries because the compiler doesn't know when or how many times a callback will run. There are a few exceptions, like for function parameters that aren't reassigned to anywhere in the function, but that's the general rule.

Ah, that makes sense. Between calls, another piece of code may change the class member where a local parameter cannot be changed like that. Fair enough, thanks!

>There's actually an issue template explaining this, but weirdly, people who actually run into this seem to overlook it and it only ever gets clicked for unrelated issues:

I was retracing my steps just now as to how I might've overlooked it. When I pressed the "New Issue" button half an hour ago, I went straight to the form to describe my issue, no templates on offer. Just pressing it now, I get a lovely page with templates to choose from, one of which is the one you linked. Maybe because this was my first issue?
