### ISSUE TITLE
Incorrect type checking for class extends by decorate in 5.0 beta

### ISSUE THREAD

**Issue by uasan** [microsoft/TypeScript#52618]
My class decorator function returns an extended class with a new `url` property

```TS
function decor(a, b){
    return class extends a {
        url = ''
    }
}


@decor
class A {
    
};

new A().url; // Error Property 'url' does not exist on type 'typeof A'.
```

but the typechecker doesn't accept the new property and throws an error

Playground
https://www.typescriptlang.org/play?experimentalDecorators=false&emitDecoratorMetadata=false&target=99&ts=5.0.0-dev.20230205#code/GYVwdgxgLglg9mABAEwKYTgJwBQEMA0iARgJQDeAUItYpqlCJkhADa4DO7iAcoqgB5RUYZF1yJKNKYkYtEAXkQByJVRoBfCpooUAAmgyYKrDlwCCEtdS0BuHWFQB3RGYB0sm0A

🙁 Actual behavior
`Error Property 'url' does not exist on type 'typeof A'.`

🙂 Expected behavior
class `A` has in prototype property `url` string type

Am I misunderstanding the decorators spec, or is it a feature of the type checking implementation??

**Comment by fatcerberus** [comment]
You probably meant to write `new A().url`, but either way, decorators can't currently be used to change the type information of a class.

**Comment by uasan** [comment]
The inability to change the type, is it a temporary implementation limitation or is it by design?
Type changes are one of the main use cases for decorators.

**Comment by MartinJohns** [comment]
Most likely temporary. The team first wanted to focus on shipping decorator support, before focusing on the integration into the type system.

**Comment by andrewbranch** [comment]
working as intended _for now_
