### ISSUE TITLE
Generic constraints cannot be refactored in some scenarios

### ISSUE THREAD

**Issue by dimitropoulos** [microsoft/TypeScript#52612]
# Bug Report

### 🔎 Search Terms

generic constraint constraints parametric replace variable storage refactored

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about https://github.com/microsoft/TypeScript/wiki/FAQ#generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230204#code/PQkAgUQDQQQWQAoBkJgIwC4wIIYGc8BTPMAFwAtCzjS8AoUgTwAcrcAnUgSxwBsAhRgGlCjPGgA8dMGAAqAGmlghYQgA9ShAHYATEgGtRAewBmcsAF4whxqbl0AfJbBxC7AOaEAkls3siAMbcRloSAN5KANoIYFxa1sZmsmD42Koa2nrKYAD8aVhahABubgC6OViy0aV0AL5gAGRgETLRsfE2dsmpMeqauiQqeYUl7GBYCKWV1XUOANx0dKDg0PDIqABME-hEJBRUmni0DCxsOJw8AsKieBtSMgpKKn2ZBonmVp1Jjs6uHt6+NyBYKhFpgcAAOQA8rIIFgVORUgAjQjaMDsQjMXg4AKEHRgADuXAoCVsSXaZHIXBIISoWJxVAAFDhdJSDjQSEcuLxeGBmDsAJRKcAyUVi8USsVFAB0stlRSiMTipK6KRIvQyAxV5LyMQKxTKFTkM3qTTBbWVX3MPXS-SyQzAIzc42wU2Nk1mC0Wy2AkFgiBQYAAzFgAPoAEShEAAymBobJQ3ydmzqEd6ExWNhztw+IIRGJ7vYZJCYXDstSwABXLSVog6eQpVmIkgotEYgC2RhKOh+Vj+nh8fmBXBC4UVFKt3XVtte2vMupdTvY5WmHtNzWFvvjZYRyNR8Qx9Nx+KJJMnFIoFdpfOxuM3kqRldIjqMBIb+1TtBfYF4IU8Y35AgwEZD8MTwSteG4LR3DIU5YhILRXzAAADFlGGQoVi19SUcNwmU5WlBVWiVDp3inNIXi1c9hgNMYJjdKo13mb1ljAAAJCAkAQCAACVYx9Oh1GYIxOFgzMIAAR0rPgJCgBsAE0nAsJRGQkWQHEZAVLCcZJKKyKBcnQF0Ni0vT6BkVT1M07TzDMsB5MMtBjMwwzSHYStCCULATD4IhBLUYTRIzKgIACwggjUmctTcjylPsOg4j8HzcTAABVIgxjBLQcHbQgsCOdg4ncJQcE8ApK3bFF2BKnQdDAvB8rcoq6kWYKwBgJyrA4HMrnzPAJHStwGwAcmy3LhuYtr+E6jcZDGwgjQK5qZFKvLHQqqqarq4gGrAJboLqBY2oAYRm0LWAiyTpN4CQOobaaHGYk5MxgDZnG6y48xuAaMpG+bhrAAAfMBhtWiajrg-g3qsLKcoWxrCoOlbPCNGtKrcLb6oR5raghzNjuhyAwsuqSZNe+6Nker02pgIN3uzT7rgLQb2EmyG6a6hmZJZtn8Y5omLtICQrrJoN7qDKmWLAAABWgAFohPC0gFfYdgRMZDYgwAFi1oU2ogGaPtzJn+pZv64YB4HhurfREIJLRwdauD+wBIclZHUJ1Occ0SLnWQGOqBZaiAA)

### 💻 Code

In it's most condensed form, the following single change will cause the tests to fail (see the [playground link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230204#code/PQkAgUQDQQQWQAoBkJgIwC4wIIYGc8BTPMAFwAtCzjS8AoUgTwAcrcAnUgSxwBsAhRgGlCjPGgA8dMGAAqAGmlghYQgA9ShAHYATEgGtRAewBmcsAF4whxqbl0AfJbBxC7AOaEAkls3siAMbcRloSAN5KANoIYFxa1sZmsmD42Koa2nrKYAD8aVhahABubgC6OViy0aV0AL5gAGRgETLRsfE2dsmpMeqauiQqeYUl7GBYCKWV1XUOANx0dKDg0PDIqABME-hEJBRUmni0DCxsOJw8AsKieBtSMgpKKn2ZBonmVp1Jjs6uHt6+NyBYKhFpgcAAOQA8rIIFgVORUgAjQjaMDsQjMXg4AKEHRgADuXAoCVsSXaZHIXBIISoWJxVAAFDhdJSDjQSEcuLxeGBmDsAJRKcAyUVi8USsVFAB0stlRSiMTipK6KRIvQyAxV5LyMQKxTKFTkM3qTTBbWVX3MPXS-SyQzAIzc42wU2Nk1mC0Wy2AkFgiBQYAAzFgAPoAEShEAAymBobJQ3ydmzqEd6ExWNhztw+IIRGJ7vYZJCYXDstSwABXLSVog6eQpVmIkgotEYgC2RhKOh+Vj+nh8fmBXBC4UVFKt3XVtte2vMupdTvY5WmHtNzWFvvjZYRyNR8Qx9Nx+KJJMnFIoFdpfOxuM3kqRldIjqMBIb+1TtBfYF4IU8Y35AgwEZD8MTwSteG4LR3DIU5YhILRXzAAADFlGGQoVi19SUcNwmU5WlBVWiVDp3inNIXi1c9hgNMYJjdKo13mb1ljAAAJCAkAQCAACVYx9Oh1GYIxOFgzMIAAR0rPgJCgBsAE0nAsJRGQkWQHEZAVLCcZJKKyKBcnQF0Ni0vT6BkVT1M07TzDMsB5MMtBjMwwzSHYStCCULATD4IhBLUYTRIzKgIACwggjUmctTcjylPsOg4j8HzcTAABVIgxjBLQcHbQgsCOdg4ncJQcE8ApK3bFF2BKnQdDAvB8rcoq6kWYKwBgJyrA4HMrnzPAJHStwGwAcmy3LhuYtr+E6jcZDGwgjQK5qZFKvLHQqqqarq4gGrAJboLqBY2oAYRm0LWAiyTpN4CQOobaaHGYk5MxgDZnG6y48xuAaMpG+bhrAAAfMBhtWiajrg-g3qsLKcoWxrCoOlbPCNGtKrcLb6oR5raghzNjuhyAwsuqSZNe+6Nker02pgIN3uzT7rgLQb2EmyG6a6hmZJZtn8Y5omLtICQrrJoN7qDKmWLAAABWgAFohPC0gFfYdgRMZDYgwAFi1oU2ogGaPtzJn+pZv64YB4HhurfREIJLRwdauD+wBIclZHUJ1Occ0SLnWQGOqBZaiAA)).

```diff
type PartialByKeys<T, K extends keyof T = keyof T> =
  Copy<
    MergeIntersection<Pick<T, keyof T>>
-    & Omit<T, K>
+    & Omit<T, keyof T>
  >;
```

No expert I ask seems to know _exactly_ why including two people that have written major books on TypeScript.  I have read all documentation on this subject as far as I'm aware and I'd really like to know what's going on here.

### 🙁 Actual behavior

The tests fail by making this change and the type returns `any`.

My best guess is that there's some kind of distributive behavior happening here when you make a constraint like `<T, K extends keyof T = keyof T>`, but that doesn't give me enough clarity on what the precise reason is why it is possible on the line above (the one with `Pick`) without failing the tests but not on the line below.  In the playground example I expanded Pick and Omit to make this clearer.

### 🙂 Expected behavior

I would expect either the tests to continue to pass when making a parametric refactor like this, **or** I would be very happy to simply just understand the reason of why the behavior is different here.

**Comment by RyanCavanaugh** [comment]
Sorry, I don't understand the Playground link. How is the presented `PartialByKeys` *supposed* to pass the tests without `K` ?

**Comment by dimitropoulos** [comment]
@RyanCavanaugh you're 100% right.  so sorry for wasting your time.  Talk about missing the forest for the trees....  I thought this was one that was a minimal test case to illustrate an issue I've hit a few times, but clearly it isn't.

I've seen that some people ([incredible example](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230204#code/PQKhAIChwgBAXAngBwKYBNUDNwGUA2AlgMarRzICGATpQLYDOeAKgIIBKzA+gAoDyuAPwAacAFEAcgBFeAweAC0LDs1GSp4YgHsAdgDdU1eBnDwt4ZFoaF4hA+EI70JVA3LhY1VPACu1HUzMAHQMRKQAFLhsnLK4atKxAJTkwJBIaHhhqAA80ODM4KgAHsZOTD46ANY6WgDuOgDaALrCkHlRKoUlqGXgOj50AEaG4AC84AAMrXnqXaXoTP1DI+PMDQBE+D0A5vAAFustbeDKMfy4cz0LfQPD1GN5JwCSDBK6EqjblLYG2R2cAD5Lr14NQfGQTid5P9mI9wAAuPA+QagyjEeDZNabHb7Q6iViDBhafA+Yx-aLMAEA6YndSxYHXJZ3B6Q8AvN46D5fH45dRA4rzJig8Fw6HI1HozEbLY6XYHFriaQAuGIglEklkvk08DsMS4ACqABkCqM4XxSXwsAAhLQVBa5VknGGxVqOxUyc6ux0NKb5aU4+VNOH87ogsEQyHyZoqvB7QhYDE8LTITHxD0CamnbjnamQIHjXUG40Abja6VQbJ08FYUhNN2W9wAPuAGKDHNtwM3BoRto54KW0igK7ge0tshIGUwnlWa5SxlATgADAAkAG8JABfReT8AAcgmu7y8gmeURK-XW53i4Ua9b1HbW9FigAjDHnwPy2zXp9vnYchOBSuKcZ1rfMFzwUcBnHENBRfI9THDU9wCwSh8AYVAPyHL8OS5X9fgA0NrmnatQPnPJ2R-HloJ3FC0IjeRhQjRFaPQzCMjVYlSX-HcmUMfM8nPTdt0A3przXRwsBGdgeNuQxHyhHUkIkNjhzjBMHXyHdKB0RBmi9AjYN4+5xlffiTgMoDJng2ETkRAoROuBoKmqOodFEIIPIkqTXHgINWWhNSMXYHzRFwcVaElCRRGfKkY2aFTwCTFM8nswimG03SjnMmSG3nUyWXACzehPfz8hjVLYIaDygi8+5gtbURnJqeo-MdeQkuyer4FC8K0QxKLwBi5U3UReKyywsKUQijE8gAWRyu4vQuBzFlk6g8wK4K0G+bJZpgyyqo8rbUB23BM2q2qdR81r5C6-1ZVxVrER0VADGoBLjp2vIisZNavQqyymtc+d+nwfAvXmla-SaedozM8BZvuuVDh3CR4NmpDPv60RVHAQ6glmnGmgBBLDVcBhmD2bTMQWwxRH1WnqDAmYAEcfFQ1NwH1fawxFBSWKYpEpr6znuZ417DCfRiYwFgdQBAdxPG8PwAgQ8EHBwJ5RAAKXAGgKxqeB6zuNwYEhLR7gaLXwG1xIHHKHRBltJwTEGRA8dYYhiB9BVPe958mmSGBUk-c14EtG07QYDTDT4RnOz6CXqC9AAJJ54+bF63q9dhWAkABxMRGbhgrY-Ft74Ol2zwDT8vJdKqvIURMmGApqmdGyWPRFzguxB9nnrkbhvEJG8AW7b6me8LhoA9ENOB6FEe3XABil9H2W2mALft533e9-34B8j1ZhcDaYpLCMUwsLENmOYADVEABNeHwkxAFwjt0YgQB3o75XwaETgAAEx2xWnkV+lIP5jG-juR+-9nyAJAZXJezFULoUgOfC2RtPxiCKGgSUP9B7hjArCQc7FqDGTxs+UQQDRAAGZRAABZRAAFYgyQC3uAQYlBrDEDIRWVgCDxgEBcNkVgFDRC+hiqWT8VohFUKaDIrCABheRuD8EYhvuzfAYjqHgDkVSBKrAgHzhEaQMREjJiSJJvw-RJjxhjU-Mo+x4g8GoElFojmxjRBWiAYY8a7E6GmKyBY5OwCmE2NkUEhxDDwCMMUbY5R0TXEaOyJ4nRrBYlWjof4jhh9ky2F0KhPW1BthuE-KwRhwTRHNEiVhK0VSHEJKcY0lJ7jNG3wycw-RjDckVJYdU8x4imZKIyFaAZ4xhmjIrMoiZbSPGdLESwnxLC+lYVYAANkGTkYZ1jpn6K2ZMih+zlGHPmR07RYiNk+I2Ws9iAB2bZoSaF1LGY8mJTDWHNJUe885aTFmsHuT4+5uTOEvW5H+BwLsii2NYAADiebsqxL5XkVitAihxejaHgFifEk5GK-npLEXCnxcK7kCIAJyIssQoWJChpG2KtFSj5cTvkZGUcywlAKKU+IpaCw+jg9CoUIOgWFz4JjUrCeK1F+jxWwzZTMuV4x1HtP+ZcwRvo5ETHJeAQR8izE7MsXo7V+y5HyMcSo58ai3ELPVVanxVqdWCJcQa55g1fRAJNYy58LiLXsp9fOFVtqvE+odX4mxQA)) are developing a style where a lot of the work gets done in generic constraints (because, you can use it as a means of sortof storing variables).  In these situations, you can sometimes (rarely) hit scenarios where you don't seem to be able to refactor things back out.  Again, apologies for not having a smaller test-case at the moment.  I'll close until I can dig one up.  Thanks for taking a look!

**Comment by RyanCavanaugh** [comment]
No problem -- if only every confusing Playground link I saw had such a simple explanation 😅
