### ISSUE TITLE
[4.9.5] Destructuring type inference fails on direct assignment, succeeds with intermediate variable

### ISSUE THREAD

**Issue by tminich** [microsoft/TypeScript#52629]
# Bug Report

Full details in the playground link / below, summary:
```ts
export function setupImages<R extends ImageHolder<K>, K extends string>(item: R, keys: K[]): SetupImages<K> {
    return <any>undefined
}

const test: TestInterface = <any>undefined

const two_steps = setupImages(test, ['image'])
const {prepare: prepare_two_steps, ...two_steps_rest} = two_steps

const {prepare: prepare_one_step, ...one_step_rest} = setupImages(test, ['image']) // Error on `test`
```
The two step version works, the one step version fails with
```
Argument of type 'TestInterface' is not assignable to parameter of type 'ImageHolder<string>'.
  Type 'TestInterface' is not assignable to type 'ImageRefHolder<string>'.
    Index signature for type '`${string}_ref`' is missing in type 'TestInterface'.(2345)
```
so apparently narrowing down `K` fails.

### 🔎 Search Terms
Destructure, Destructuring assingment

### 🕗 Version & Regression Information
- This is the behavior in every version I tried (down to 4.5.5)

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwM7AxJgCSAtgIYDmweAPAEpygzAoAmec51wAEhAA27YFDoBpAHwAaOOOYhWHLnhhRMKKpIAUmVmQBccBrIDWwAJ54j4gNoBdAJRGAyoWI8a9KXADeAKDgguCh3KFw6ChQLSVQRBA1gdn8AX39-NBxVOFZVIwAVWhgSFFYoBAo0YDgAXjhI6NiOYASUJPTMlGyYAHcIAH1VYDAuOoIiUkovbVyYWVsAckwp4AWnDKz4XzBQsApQox3h-eB+3oGhkdkAOlvzwdYR-tDVFNqcvofhvA7NvyO9gc4ACTv0cKdLjdbuCvmBnkU3mN3JNeHgZkV5ksVmtHOl-AB6ABUxJJxMChLg+QsYFo5PxeNAkFgcA0ZQqVWMECQrAYLT8gWCSCQmHYRlU6k0qXSjOg8FZonZ1QAYphBMASPp+cFEKrgEYVWqpf4YNTqp5gLyEAJhKIJAolJx8GoNFp3gFtbYAAos3AAAwAJL5xCl4QhffYjAwuTyWlKTTTuCsAKrC9jWkRieQsNiO8UuyRugVBL0+uABoMhoUi8Ni52StIy5nxs0rdO2rOKHMqOuuurmy1tzMFgBkid4KZFg4kkn8jfgzbHXk9uxO7DoJHtXcX-CEGensg7Du7Et7cAA8mQ9OvZOaL3pxJZvJJbCgkGQAEaiewj7cqlAUQQpykY1TW3O8YAfKw7WzZQnRPAs6m0cwLAgBBtyAyRHAcECE3NP8AINYBoM7WC800BCtWCEsNDkewAH59V1ONQLwjQAIAEWANVWGIo84PzQsPW9Gjy2Dfp+hEbjgHDBi4AARmY3CVnwwDd3bTdSJ7CjWP-QRCOnOBRx0jiuMIIjgPSBc3AmfsWjwDVgDIXitzI093So4TcHECM4EIhyyCNeVykqapl2OUJzW8DTcy0yighBIFGGirhzQwnR2AoGAKEjRxagLSKwsBJJGAPGc0hw6prI8FZLSimCYvg94qpRGhav86dLNA5rIuczTGrqbqarsgzR0Kk4eosucfTZELKSKEoZo5dygn-Mg9X4yVtWWXhQ0jaMLVjLaVn6KtRQ2qgpSAA)

### 💻 Code

Tried to slim it down, but unfortunaely it's still a bit complex
```ts
export function setupImages<R extends ImageHolder<K>, K extends string>(item: R, keys: K[]): SetupImages<K> {
    return <any>undefined
}

const test: TestInterface = <any>undefined

const two_steps = setupImages(test, ['image'])
const {prepare: prepare_two_steps, ...two_steps_rest} = two_steps

const {prepare: prepare_one_step, ...one_step_rest} = setupImages(test, ['image'])


/********
 * Types
 */


export interface RouteRef {
    uuid: string
}

export interface FileItem {
    file: File
}

type ImageRefHolder<K extends string> = {
    [P in `${K}_ref`]: RouteRef
}
type ImageUuidHolder<K extends string> = {
    [P in `${K}_uuid`]: string
}
export type ImageHolder<K extends string> = ImageRefHolder<K> & ImageUuidHolder<K>
export type ImagesPrepared<I extends ImageHolder<K>, K extends string> = Omit<I, ImageOmitKeys<K>[number]> & ImageFinalHolder<K>
type ImageOmitKeys<K extends string> = (keyof ImageHolder<K>)[]
type ImageFinalFile<K extends string> = {
    [P in K]?: File
}
type ImageFinalDelete<K extends string> = {
    [P in `${K}__delete`]?: 1
}
type ImageFinalHolder<K extends string> = ImageFinalFile<K> & ImageFinalDelete<K>


type SetupImageRefsItem<K extends string> = {
    [P in K]: FileItem
}

interface PrepareImages<K extends string> {
    prepare: <R extends ImageHolder<K>>(data: R) => ImagesPrepared<R, K>
}

type SetupImageRefs<K extends string> = SetupImageRefsItem<K>

type SetupImages<K extends string> = SetupImageRefs<K> & PrepareImages<K>

export interface TestInterface {
    name: string
    image_ref: RouteRef
    image_uuid: string
}
```

### 🙁 Actual behavior

Error on the indicated line

### 🙂 Expected behavior

No error as type resolution appears to work fine in the version with an intermediate variable. The one line version should imo be fully equivalent.

**Comment by Andarist** [comment]
Slimmed-down repro case:
```ts
type ImageHolder<K extends string> = {
  [P in K]: string;
};

type SetupImageRefs<K extends string> = {
  [P in K]: File;
};

type SetupImages<K extends string> = SetupImageRefs<K> & {
  prepare: () => { type: K };
};

interface TestInterface {
  name: string;
  image: string;
}

declare function setupImages<R extends ImageHolder<K>, K extends string>(
  item: R,
  keys: K[]
): SetupImages<K>;

declare const test: TestInterface;

const { prepare, ...rest } = setupImages(test, ["image"]);
```

**Comment by RyanCavanaugh** [comment]
Caveat emptor - tagging bug/backlog since Andarist's PR seems plausible, but I haven't actually read this through
