### ISSUE TITLE
Generic not widen when union and conditional are involved. 

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript#52620]
# Bug Report

I've read #10676, but I'm failing to understand why there is no consistent widening accross the 3 examples mentioned below. 

### 🔎 Search Terms

* literal 
* widening
* union
* generics

### 🕗 Version & Regression Information

AFAIK not a regression. 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD2AnAtgYXgOwC6PiAPACoB80A3gLABQ00wmEOArsFkgBRYBch0ApgA8sfDABMYTMXwBmASwx9R0APzQFANz6JoXaIQCU5AL7UTVehkbQw0ALxq+AdzhI0mHHnYByL-oDc1AD0gbS0AHrK1NSgkDAIKOjYuCAATESklDR0DMysHNyEAD6MiPIA5oZkZmYWVgBGdg7O8W5JeCnsAESd-kEhoRFR5uBQLgnuyQDM6eTUtLW5bIicPPxCIuLQkqIy8ooqDprauuxFJeX6ldXROXSNCs2uiR4gk109AVTBodCDVNRAA)

### 💻 Code

```ts
class FormControl<T> {
  constructor(t:T extends undefined ? never : T) {}
}
const a = new FormControl('');
//   ^? FormControl<string>

class FormControl2<T> {
  constructor(t:T|string) {}
}
const b = new FormControl2("");
//    ^? FormControl<string>

class FormControl3<T> {
  constructor(t:T extends undefined ? never : (T|string)) {}
}
const c = new FormControl3("");
//    ^? FormControl<"">
```

### 🙁 Actual behavior

Non consistant behaviour between use-cases. 

### 🙂 Expected behavior

Consistent behaviour.

**Comment by ahejlsberg** [comment]
The issue here is that the relatively simple check in `isTypeParameterAtTopLevel` doesn't recurse into conditional types since that would require guarding against infinite recursion. It would be pretty simple to at least allow a couple of levels of nesting.
