### ISSUE TITLE
Abstract mixins and generic this don't mix

### ISSUE THREAD

**Issue by ntucker** [microsoft/TypeScript#52626]
# Bug Report

### 🔎 Search Terms

abstract mixin generic 2416

### 🕗 Version & Regression Information

This starts in 4.2 (because abstract mixins we not a feature before this version)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about abstract mixins

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gOwM7AE4FcDGw6qgXigEMAjFVI7KBCAdygAoA6Fo1AcyQC5iEQBtALoBKAgD4oAbwC+AbgBQoSFACCZNJWABJZMCIJMEACrgIAHiMTCRqBAAewCAgAmSKVDCo4OJRB4BLBAAzCDwAVShpeSgoAH4oMOioHhoAN1CFeSD0A2B-RCgAW387QIsAISIkaHtHFzd4XQxsXDEGSuqeIw6IUUkk0nJNKEwAGyq3AFkQGHGkN1qnVygeqSSYwY0qQohCklCGYR5UuH9nBRiNhG8ACwOjqHJA9ndUCGB0VAQoAHIb-x+kXWUCCmlwIAstgcSzcvjgQSg01mEzawH+3CgRgeaiG2B0KH0hhMkAsEn6l0ubw+X2odEYaP8biqvBAwkOF0uURiXKgVM+3yRcyQCii8k2FCoYwmKy8AGsnFC6stiqUEAwpfMpNI+gNrmj7lI+TSfj8eaCWqgITZFvUoHCEeU5U5Ueiutj1BLtLpCcZTKS1hSjd8aPQGAymUy+GzhByolENW4AOq4WXPRUwoolQLqoVanUxHZ7A0yXW3YtB36mpLmnCWyE25b2qDJ1CphDsF2Mt08HFbL0Egy+kmWAOU9782mh8PESOs9lJONAA)

### 💻 Code

```ts
type Constructor = abstract new (...args: any[]) => {};
type AbstractInstanceType<T> = T extends { prototype: infer U }
  ? U
  : never;

function mixin<TBase extends Constructor>(Base: TBase) {
  abstract class MyClass extends Base {
    abstract member(): void;
    another(): string { return 'hi' }
    factory<T extends typeof MyClass>(this: T): AbstractInstanceType<T> {
      // please don't focus on use of 'any' here - it is not relevant to the issue
      return new (this as any)();
    }
  }
  return MyClass;
}

abstract class Broken extends mixin(class {}) {
  another() {return ''}
  factory<T extends typeof Broken>(this: T): AbstractInstanceType<T> {
    return new (this as any)();
  }
}
class Working extends mixin(class {}) {
  member() {}
  another() {return ''}
  factory<T extends typeof Working>(this: T): AbstractInstanceType<T> {
    return new (this as any)();
  }
}
```

### 🙁 Actual behavior

"Cannot assign an abstract constructor type to a non-abstract constructor type.(2416)" on the Broken.factory implementation line.

### 🙂 Expected behavior

Broken class should work with no type errors (just as `Working` does)

**Comment by ntucker** [comment]
I'm noticing the ambient output seems to indicate the problem:

## Actual behavior

```ts
declare const Broken_base: (abstract new (...args: any[]) => {
    member(): void;
    another(): string;
    factory<T extends any & {
        new (): {};
    }>(this: T): AbstractInstanceType<T>;
}) & {
    new (): {};
};
```


## Expected

```ts
declare const Broken_base: (abstract new (...args: any[]) => {
    member(): void;
    another(): string;
    factory<T extends (abstract new (...args: any[]) => {
    member(): void;
    another(): string;
    factory<T extends any & TBase>(this: T): AbstractInstanceType<T>;
}) & {
        new (): {};
    }>(this: T): AbstractInstanceType<T>;
}) & {
    new (): {};
};
```

**Comment by RyanCavanaugh** [comment]
This doesn't seem like a bug. The correct type to write here is
```ts
  factory<T extends { new(): Broken }>(this: T): AbstractInstanceType<T> {
    return new (this as any)();
  }
```
