### ISSUE TITLE
refs counter for each overloads [feature]

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#52643]
# Suggestion

hi, can we have refs counter and filter for each overloads ? ((per signature))
thanks

original post: https://github.com/microsoft/vscode/issues/173395

## 🔍 Search Terms

refs counter, overloads 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

current
![image](https://user-images.githubusercontent.com/24865815/217108139-0af5ac6b-6e58-46b5-b103-760f71c58284.png)

expected
![image](https://user-images.githubusercontent.com/24865815/217108180-594939e2-ee9d-49e7-9e03-4e8d40b42e76.png)

## 💻 Use Cases

debugging, tracking, visual productivity helper.

**Comment by fatcerberus** [comment]
…did you actually just say “sup” on a GitHub bug tracker 😝

**Comment by djmisterjon** [comment]
> …did you actually just say “sup” on a GitHub bug tracker 😝

i see a lot of English peoples use it so i use it for convenant :)
it mean `salut sa va` but also `salut what's up` 
sorry for the bad grammar i fix it.

**Comment by fatcerberus** [comment]
It’s not that it’s bad grammar, it’s just really, *really* informal. 😄
