### ISSUE TITLE
Can't import typescriptServices under node moduleResolution

### ISSUE THREAD

**Issue by Gaelan** [Microsoft/TypeScript#5264]
```
Exported external package typings file '[app-root]/node_modules/typescript/lib/typescriptServices.d.ts' is not a module. Please contact the package author to update the package definition.
```

I'm not sure how we should handle this.

**Comment by basarat** [comment]
Temporary workaround I've been using: 

* [`ntypescript` exports to `global` anyways](https://github.com/TypeStrong/ntypescript) ... so just `/// <reference path="../../node_modules/ntypescript/bin/ntypescript.d.ts"/>` it manually (works with `exclude` too) and then have a single `var/require` call to get the runtime semantics to match compile time inference (global)

Would love to see a proper workaround / discussion :rose:

**Comment by mhegazy** [comment]
you should not import `typescriptServices.js`, this is a file you would include in a webpage for instance. use `typescript.js` if you want to import it. simply use `import * as ts from "typescript"` and no need for the `/// <reference `

**Comment by mhegazy** [comment]
> Would love to see a proper fix / discussion

@basarat i am not sure i understand the issue here.. can you elaborate?

**Comment by Gaelan** [comment]
@basarat I used this:
```
/// <reference path='../node_modules/typescript/lib/typescriptServices' />
var TypeScript = require('typescript/lib/typescriptServices') as typeof ts
```
This lets me use plain TS.

**Comment by mhegazy** [comment]
@Gaelan so why is not  `import * as TypeScript from 'typescript');` working for you?

**Comment by Gaelan** [comment]
@mhegazy Weird timing. I started a reply to @basarat's comment, you commented, then I clicked Comment.

**Comment by basarat** [comment]
> you should not import typescriptServices.js, this is a file you would include in a webpage for instance. use typescript.js if you want to import it. simply use import * as ts from "typescript" and no need for the /// <reference

Got it :+1: . NTypeScript needs an update. `require('typescript')` works fine.

**Comment by basarat** [comment]
For reference : I had a single def file that exported both a module name + global. But I guess I will need to split them into two def files (like typescript does).
