### ISSUE TITLE
Make the type parameters or Record optional

### ISSUE THREAD

**Issue by KaanSD** [microsoft/TypeScript#52659]
## ⭐ Suggestion

We can make the type parameters of Record optional making it's signature: 

```ts
Record<K = string | number | symbol, T = any> 
```

## 💻 Use Cases

Sometimes we might have a function, method or constructor that accepts a parameter that we don't know too much about other than the fact that the following is true: `typeof param === "object"`. We might want to add properties to the parameter or perhaps we want to check the existance of a symbol like `Symbol.iterator`.

In these cases we can currently choose from one of the following: `Record<PropertyKey, any>` or `Record<keyof any, any>` or `Record<string | number | symbol, any>` or  `Record<any, any>`, or if I only care about string keys: `Record<string, any>`

But it would be much easier to write: `Record` or `Record<string>`

## 🔍 Search Terms

record optional type parameter generic object

## ✅ Viability Checklist

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code

Existing code would not be impacted because it is adding expressions that were previously disallowed.

* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

Strictly a type system change, should not impact JavaScript at all.

* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
I don’t even know what you’re asking for.  Please fill out the template.

**Comment by KaanSD** [comment]
Sorry, I submitted unintentionally early. I'll fill it out.

**Comment by RyanCavanaugh** [comment]
There's a very large contingent of people who would be extremely annoyed at the ability to accidently slip `any`s into their code, and there's in practice very little difference between `Record<string | number | symbol, any>` and `any` in the first place to motivate writing it as `Record`.
