### ISSUE TITLE
Formatting issues with tsx files

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5265]
*Note: Edited by team to support code fences*

See examples: 

##### Example 1

Before formatting
```
<p></p>
<p></p>
```

After formatting
```
<p></p>
< p > </p>
```

##### Example 2

Before formatting
```
<p>{ foo }</p>
```

After Formatting
```
<p>{ foo } < /p>
```

**Comment by mhegazy** [comment]
this is fixed in latest.
