### ISSUE TITLE
`verbatimModuleSyntax` and exported `const enum`

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#52669]
# Bug Report
`verbatimModuleSyntax` will be introduced in TypeScript@5.0 and `importsNotUsedAsValues` and `preserveValueImports` will be deprecated.
But there is a `const enum` export issue that has not been fixed.

### 🔎 Search Terms
- verbatimModuleSyntax
- export const enum
- importsNotUsedAsValues
- preserveValueImports

### 🕗 Version & Regression Information

TypeScript@5.0 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&verbatimModuleSyntax=true&ts=5.0.0-dev.20230207#code/PTAEAEDMEsBsFMB2BDAtvAXKSB7HA6AFwGcAoeADwAccAnQ0AYx0WIaQFdVQAxPUAN6lQoCqAC8oAIwAaUgF9SpEBBgIU6LKmTRERMtFQ16g3v3nZaObgCJ8wXAQBWxGwG5lYAJo4OTZIiIOAwA7rTQhPCgxNbwhAAWugDmoLDQANZRCVG4sLA4IcmeoIbGDIQAnlRRAmY4oBaQVrb2jvgu7krMrDgI+PlJABR8BBQAlB5AA)

Playground multi-file mode is broken.
Check this [gist](https://gist.github.com/magic-akari/e64fe199efbdd688747af250a1d86eb5)

### 💻 Code

```ts
// @filename: foo.ts
export const enum Foo {
  x = 1,
}

// @filename: main.ts
import { Foo } from "./foo.js";
// You cannot write something like the following
// import type { Foo } from "./foo.js";

console.log(Foo.x);

```

### 🙁 Actual behavior

SyntaxError: The requested module './foo.js' does not provide an export named 'Foo'

### 🙂 Expected behavior

TSC Report Error: const enum cannot be exported in `verbatimModuleSyntax` mode.

### 🔗 related issue
- #52469

**Comment by DanielRosenwasser** [comment]
I believe this is by-design unless you run with `preserveConstEnums`.

**Comment by andrewbranch** [comment]
`verbatimModuleSyntax` is supposed to be a superset of `isolatedModules` which is supposed to imply `preserveConstEnums`, IIRC.

**Comment by DanielRosenwasser** [comment]
I think it just errors when `preserveConstEnums` isn't enabled - I don't think it actually enables it.

**Comment by andrewbranch** [comment]
`isolatedModules` does imply `preserveConstEnum`, but there were many places in the codebase where I forgot to replace an `options.isolatedModules` with a check for `isolatedModules` or `verbatimModuleSyntax`.

**Comment by mrazauskas** [comment]
Would it be possible to mentioned in the documentation that `verbatimModuleSyntax: true` does influence `const enum`s?

I noticed that `const enum`s are not inlined at use sites with `verbatimModuleSyntax: true`. Looks like the behaviour is similar to `isolatedModules: true`, but it can be I missed something.

**Comment by andrewbranch** [comment]
`isolatedModules` isn’t deprecated 🤔

**Comment by mrazauskas** [comment]
Ups.. I got mixed up. Despite of that, it would be useful to mention in documentation how `verbatimModuleSyntax` works with `const enum`.

**Comment by andrewbranch** [comment]
I’m not totally convinced that `isolatedModules` should actually mess with const enum inlining. It’s supposed to be simply a set of checks that code _can be_ transpiled with only single-file info, but somewhere along the way I think someone got mixed up and decided it should emit as if it lacks whole-program info. But that principle isn’t consistently applied, and I don’t see why it would be desirable anyway.

**Comment by mrazauskas** [comment]
Are you trying to say that this is possibly a bug? I mean, it felt like `const enum`s should be inlined with `verbatimModuleSyntax`, but it can be I missed some detail.

Would it make sense to open a separate issue? I can do. Just didn’t want to create unnecessary noise.

**Comment by curiousdannii** [comment]
I had to add `verbatimModuleSyntax` to use Svelte, and now my const enums aren't optimised. This is quite unfortunate, and also seemingly undocumented.
