### ISSUE TITLE
[Playground] two slash `@filename` not work in typescript playground

### ISSUE THREAD

**Issue by magic-akari** [microsoft/TypeScript#52666]
# Bug Report

### 🔎 Search Terms

- playground
- two slash
- filename

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/PTAEAEDMEsBsFMB2BDAtvAXKGCC0B3aAFwAtd4APABwHsAnIgOiIGcAoS2h0AYxsRZFQJeLFg0A6vVgATUAF5QAIgCiFNFQShBdaIgDmStmxAQcSNJlB6ZlZu2iouQgN7DR4qXVmgAvtjoaVGVGYHMCYjJOeiIjPgEaBEZxfQAKETFJaRkASiA)

### 💻 Code

Code from https://github.com/microsoft/TypeScript-Website/tree/v2/packages/ts-twoslasher#import_filests

```ts
// @filename: file-with-export.ts
export const helloWorld = "Example string"

// @filename: index.ts
import { helloWorld } from "./file-with-export"
console.log(helloWorld)
```

### 🙁 Actual behavior

TS2307: Cannot find module './file-with-export' or its corresponding type declarations.

### 🙂 Expected behavior

It works.

**Comment by andrewbranch** [comment]
Multiple files aren’t supported on the playground.

**Comment by uloco** [comment]
@andrewbranch You should consider updating the help docs on ts-playground then, it has an extra entry regarding multi-file playgrounds: https://www.typescriptlang.org/play#handbook-15

**Comment by DerGernTod** [comment]
please consider reopening this. this used to work, otherwise it wouldn't be documented. it also behaves very weird if you use it by showing a default "/input.tsx":
![image](https://user-images.githubusercontent.com/19726130/228853705-def5de70-9c1a-45bd-9468-328d237adb7a.png)

**Comment by RyanCavanaugh** [comment]
> this used to work

We don't intend to support this in the playground. You can use the Bug Workbench to do multi-file repros.

**Comment by jsejcksn** [comment]
> We don't intend to support this in the playground. You can use the Bug Workbench to do multi-file repros.

@RyanCavanaugh Thanks for mentioning that. I wasn't aware of the [Bug Workbench](https://www.typescriptlang.org/dev/bug-workbench) before today.

I'm actually still not sure how to discover it: there are no search results for "workbench" in the docs:

<img width="1001" alt="Screenshot 2023-03-30 at 15 09 41" src="https://user-images.githubusercontent.com/868251/228953588-896dd96a-4995-433f-b87c-00e6aea04250.png">

**Comment by nyngwang** [comment]
@jsejcksn I searched for multi-file TS Playground and found your answer. I also didn't know about Bug Workbench before. Thanks for your sharing, it's very helpful for my debugging with the latest option `verbatimModuleSyntax`.
