### ISSUE TITLE
Missing NOTICE file makes it harder to satisfy terms of license

### ISSUE THREAD

**Issue by lucasgonze** [microsoft/TypeScript#52663]
# Bug Report

### 🔎 Search Terms

NOTICE file

### 🕗 Version & Regression Information

I encountered the problem in the 4.9.5 release. I also examined the latest code in the public rep.

I reviewed the FAQ for entries about NOTICE file.

### 🙁 Actual behavior

There are copyright, patent, trademark, and attribution notices from the Source form of the Work, and the work does not include a NOTICE text file as part of its distribution. 

The license used by the project is Apache Public License 2.0: 
https://github.com/microsoft/TypeScript/blob/main/LICENSE.txt

That contains these clauses:

`You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and

If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works`

### 🙂 Expected behavior

The work should contain a NOTICE text file per the convention documented here:

https://www.apache.org/licenses/LICENSE-2.0#apply

**Comment by jakebailey** [comment]
I'm confused; it says "if", and we include this notice text on top of all files in our package:

```
/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
```

**Comment by lucasgonze** [comment]
Yes, a file header does work. In that sense my bug description using the word "impossible" is inaccurate. And even if there is no file header the downstream user has no additional legal risk. Their (our) obligation is to forward any notices. If there are no notices to forward, it's not the fault of the downstream user.

The problem for downstream users is *knowing* there is no notice file to forward. We can't just copy /NOTICE. We have to manually investigate to be sure the file doesn't exist somewhere outside the root or under a slightly different name, like /foo/bar/License.md.

(BTW the header is missing in at least the files I checked, like https://github.com/microsoft/TypeScript/blob/main/src/cancellationToken/cancellationToken.ts. A low-maintenance way for you to fix that is a /NOTICE file.)

**Comment by RyanCavanaugh** [comment]
I'm not seeing a compliance problem here. Based on other issues you're filing around GitHub it seems like you're under the impression this is file a requirement, but it's not. The repo has shipped this way for a decade without issue, so creating a new file that implies novel behavior re: the licensing is not something we'd want to do without a better cause of action.
