### ISSUE TITLE
String literal completions right after quote

### ISSUE THREAD

**Issue by zardoy** [microsoft/TypeScript#52675]
# Bug Report

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgLhgcjsmBeFyg

### 💻 Code

```ts
// Trigger suggst after last quote
const a: 'a' = ''
```

### 🙁 Actual behavior

Suggests string literal completions (`"a"`)

### 🙂 Expected behavior

Doesn't suggest string literal completions

This is more general version of https://github.com/microsoft/TypeScript/issues/51667 (I also opened this issue to ensure `<input type='text'[||] />` case is captured)

**Comment by DanielRosenwasser** [comment]
Thank you @zardoy!
