### ISSUE TITLE
Cannot find 'this' after asserting condition inside class method in ts <= 5.0.0

### ISSUE THREAD

**Issue by robertojmm** [microsoft/TypeScript#52672]
# Bug Report

### 🔎 Search Terms

Assert, This, Class, Method

### 🕗 Version & Regression Information

All versions including current Nightly (5.0.0)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about  Assert and This

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=8&ts=5.0.0-dev.20230208#code/GYVwdgxgLglg9mABAQwM6oKYCcoAoBQiiECAJjLAgFyLgDWYcA7mADT4CUNamOqxZCvCQBvQohjBEuAIQkw5SmA6IxRIlAAWWZojAYmiAKJYdWXBwDc4gL747+CABseiALIBPAMIv0q8QAOWDAAbshQGIgAtsgBiAC8-urRHgD6dBgeNADkGAAeyFEBThipYU4gGNm2+OJY4AAqHgEYAGLIME6oFknq8qhQiAHIWIX8iWAgTk4o-MhgHrOqKDQiiBlZiAPBYADmiDYHiAA+elNO4kQ82HjDo1GoHLXJUM2RANKZCeuZcFKvLT+iC0MFQADoYnEAPRQxBeeaMQbAGAKPSFSLZEGobKITTYDCXYGaUEQ2IAbTuYzByDBGyWnw8AF1EDU6o03gB1OBYOioACMPTU6gBHy+iQ2QJFkuJ4MhiBhiC5PNQzz6CAGQxGY2+k2mS3mizQy2Qqx+m22KP2h0Op11F0J1xwuEpDyehKxpICFK1D2ptK+RoZjNZRHqYCaLSVvIATM6fahTSblhsaBa9kcbWdpioxA70Dc4-dHqqNG9EAzvhL-m9pSS5QqoyqXjLPd6i366YHMsGiHYHPggA)

### 💻 Code

```ts
function assert(
  condition: unknown,
): asserts condition {
  if (!condition) {
    throw new Error();
  }
}

class MyClass {
  private map = {
    my_key: 'example_value'
  }

  runTypeFails() {
    const params = null as any as { a: { key: string } } | null
    assert(params)

    type Key = keyof typeof this.map // Cannot find name 'this' here
    this.map[params.a.key as Key] 
  }

  runTypeWorks1() {
    type Key = keyof typeof this.map // Works

    const params = null as any as { a: { key: string } } | null

    assert(params)

    this.map[params.a.key as Key]
  }

  runTypeWorks2(params: { a: { key: string } } | null) {

    assert(params)

    type Key = keyof typeof this.map // Works
    this.map[params.a.key as Key]
  }
}
```

### 🙁 Actual behavior

Typescript cannot find 'this' after asserting local variable exists

### 🙂 Expected behavior

Should be able to fin any 'this' and run

**Comment by ahejlsberg** [comment]
Shorter repro:

```ts
class C {
  foo() {
    const x = !!true;
    if (x) {
      type T0 = typeof this;  // Error: Cannot find name 'this'
    }
  }
}
```
