### ISSUE TITLE
Type `any` passed in callback argument, when defined in type parameter that use another type param that is populated by parameter with different structures (array or object).

### ISSUE THREAD

**Issue by GabrielGorta** [microsoft/TypeScript#52674]
I have function example:

```js
/**
 * @template {string} N
 * @template {(obj: {
 *    [key in N]: Something
 * }) => unknown} F
 * @param {N[] | {
 *     names: N[],
 *     func?: F
 * }} opts
 * @returns {F extends () => infer R ? R : {
 *    [key in N]: Something
 * }}
 */
function example(opts) {
    const { names = [], func } = Array.isArray(opts)
        ? { names: opts, func: null }
        : opts || {}
    
    let something = createSomething(names)
    
    something = func ? func(something) : something;
    
    // this doesn't mutate `something` variable.
    some_more_logic(something);
    
    return something;
}
```

when I call it like:

```js
const test1 = example(["a", "b", "c"]);
const test2 = example({
    names: ["a", "b", "c"]
})
const test3 = example({
    names: ["a", "b", "c"],
    func: (obj) => obj; // this doesn't make sense, but for example it's fine
})
```

test variables 1 and 2 have correct type, but type 3 has type `any` (because `obj` is alredy type `any`), when I return something else in func, it will infer type correctly.

But when I change:

```diff
--- * @param {N[] | {
+++ * @param {
    *     names: N[],
    *     func?: F
    * }} opts
 ```
 
 and remove test1 example (because is invalid), both test2 and test3 have correct type, as well as `obj` in `func` callback.

**Comment by fatcerberus** [comment]
It’s because you used the issue template “types not correct in/with callback”, which only exists to explain behavior related to type narrowing that is by design and not to post the issue as it will be a duplicate of #9998.  Presumably you didn’t read that text before typing up your own issue (which is unrelated).

You should use the regular Bug Report template instead.

**Comment by GabrielGorta** [comment]
Then I don't understand why that template exist, when it always add "duplicate" label and bot close it because it was marked as "duplicate"? That template doesn't make sense.
