### ISSUE TITLE
Feature: Get the correct type of imported image

### ISSUE THREAD

**Issue by bytrangle** [microsoft/TypeScript#52671]
# Suggestion

## 🔍 Search Terms

"property does not exist on type"

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Suppose you have assets stored in the `public/` directory. When using these assets in components, we import them using relative paths so we can save time thanks to autocompletion.

For example:

```
import logo from "../../public/logo.png"

console.log(logo.src) // type error
```

The `logo` variable here is actually an object with properties `src`, `width`, `height`, `format`.

However, Typescript treats them as a string.

![typescript-identify-image-as-string](https://user-images.githubusercontent.com/28924121/217512942-470a4bf3-4c5a-49e2-887c-4128531bc332.png)

If you want to do something to this `logo` variable like resolve path, change dimension, Typescript will probably throw an error like 

> Property 'src' does not exist on type 'string'

![property src does not exist on type string](https://user-images.githubusercontent.com/28924121/217511680-d4f71323-29da-47bd-9ac4-e88dcba470ce.png)

It seems like Typescript is able to correctly identify the type of modules, so it would be nice if it can do the same thing to images.

## 💻 Use Cases

My workaround is to opt out of type checking.

```
import logo from "../../public/logo.png"

const logoObj: any = logo
console.log(logoObj.src) // no type error
```

Another use has reported a similar issue here [https://github.com/reactstrap/reactstrap/issues/891](https://github.com/reactstrap/reactstrap/issues/891)

**Comment by MartinJohns** [comment]
The type definitions for these imports are provided by React. What properties exists heavily depends on the surrounding tooling/loader you use. This is not really something specific to TypeScript.

**Comment by bytrangle** [comment]
@MartinJohns Thanks for the explanation. Closing it now.
