### ISSUE TITLE
`instance` keyword to create object or class factories

### ISSUE THREAD

**Issue by DeepDoge** [microsoft/TypeScript#52681]
# Suggestion
Maybe this is a bad idea, but just wanted to take it out.

Using a single object as a container for parameters has some advantages, such as, seeing the name of the parameters and being able to have optional ones randomly.
For example:
```ts
function foo(params: { foo: number, bar?: string, baz: string }) {}
```
But if you also wanna use default values it becomes painful really quickly.<br/>
This is also a problem with things such as React props.

I have been looking into the `namespace` keyword and i have found that you can actually do something like this:
```ts
function foo()
{
   namespace Foo
   {
      export const a = 123
   }
   return Foo
}
```
This ^ would actually compile correctly but typescript would just give an error, complaining that namespace is not at the root.
Compile:
```js
function foo() {
    let Foo;
    (function (Foo) {
        Foo.a = 123;
    })(Foo || (Foo = {}));
    return Foo
}
```
But this is not exactly what we want.
I would first suggest being able to use `export` keyword within the function. but this has been already suggested and rejected because it might have conflicts with the future javascript syntax. 
https://github.com/Microsoft/TypeScript/issues/9028

**So my suggestion is:**

A new `instance` keyword to compile a factory for objects.
(Or some other keyword)
```ts
instance Foo
{
   export let bar: number = 8 // default value is 8
   console.log(`Got ${bar} as input`)
   bar *= 2
}
const foo = Foo({ bar: 2 }) 
// or
const foo = new Foo({ bar: 2 })
foo.bar // 4

const fooDefault = Foo()
fooDefault.bar // 16
```
This is similar to how Svelte gets props for its components.
Like Svelte if export has a default value, it would be optional if not it would be required.
This has some advantages, such as you can randomly  decide what you need from outside directly within the code.

This would compile to something similar to (if i didnt make any mistakes):
```js
function foo(Foo = {}) {
    Foo.bar ??= 8;
    console.log(`Got ${bar} as input`)
    Foo.bar *= 2
    return Foo
}
```

But why not go further and add some options here?
What if you were be able to choose if you want `class` or `object` instance.
In some cases classes might have some advantages, such a being able to use `instanceof` keyword.

So what if we modified our syntax a bit like this.
```ts
instance object Foo // returns an object and creates a type Foo 
{
   export let bar = 123 // optional
   console.log(`bar is ${bar}`)
   export const baz: string // required
   console.log(`baz is ${baz}`)
}

instance class Foo // defines a class Foo and returns an instance of class Foo 
{
   export let bar = 123 // optional
   console.log(`bar is ${bar}`)
   export const baz: string // required
   console.log(`baz is ${baz}`)
}
```

So this is an easy way to define a `type` and a `factory` both together.

## 🔍 Search Terms

keyword, factory, object, class, instance, type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example
This is especially useful when you have a lot of parameters and you want to use default values.
```ts
instance object Foo // returns an object and creates a type Foo 
{
   export let bar = 123 // optional
   console.log(`bar is ${bar}`)
   export const baz: string // required
   console.log(`baz is ${baz}`)
}
```

Wanna define a class but don't want to deal with the `constructor`?
```ts
instance class Foo // defines a class Foo and returns an instance of class Foo 
{
   export let bar = 123 // optional
   console.log(`bar is ${bar}`)
   export const baz: string // required
   console.log(`baz is ${baz}`)
}
```

## 💻 Use Cases
This is just a syntax sugar to easily create a factory for objects and classes with many members.

Examples:
Object:
```ts
interface Foo {
	a?: number
	b?: number
	c: number
}

function Foo(foo: Foo) {
	foo.a ??= 1
	foo.b ??= 2

	console.log(foo.a, foo.b, foo.c)

	return foo
}
```
Can be written as:
```ts
instance object Foo
{
  export let a = 1
  export let b = 2
  export const c: number

  console.log(a, b, c)
}
```

Class:
```ts

class Foo {
	public a = 1
	public b = 2
	public c: number

	constructor(params: { a?: number; b?: number; c: number }) {
		this.a ??= params.a ?? this.a
		this.b ??= params.b ?? this.b
		this.c = params.c

		console.log(this.a, this.b, this.c)
	}
}
```

Can be written as:
```ts
instance class Foo
{
	export let a = 1
	export let b = 2
	export let c: number

	console.log(a, b, c)
}
```

This is not really a mature idea, but i wanted to share it and see if this gets any traction.
And gets improved and implemented eventually.

**Comment by DanielRosenwasser** [comment]
This isn't something that we would do, given that the last checkbox isn't ticked:

> This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

This really falls in the domain of runtime syntax that JavaScript would define, whereas TypeScript aims to overlay type-checking (with relevant syntax) over JavaScript.

**Comment by fatcerberus** [comment]
> This really falls in the domain of runtime syntax that JavaScript would define, whereas TypeScript aims to overlay type-checking (with relevant syntax) over JavaScript.

As for why `enum` and `namespace` are a thing despite this: grandfather clause, basically.
