### ISSUE TITLE
Type inference bails when encountering `any` in conditional expression

### ISSUE THREAD

**Issue by mhofman** [microsoft/TypeScript#52689]
# Bug Report

### 🔎 Search Terms

type inference any conditional expression

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMQMBZKATwCMQA5ZAW2pgAoBKALnilXIG4BYAFAB6YfFCRYCFOmx5CxMlVoMmbTqlUgY8AD7w0oRFlQhgAwUKEzMufGAAW4ANZ16zTfQD8GrTFbwAN5C8KHwWIjwzACEngHBgmFhnvAAvAqkFNRuagG6+gAsAEwWSaJhEVGxDAEp6cUhYQC+jaGVHgzwADzwAKwADKwJSUkYDjA4AO7wptMAojATLKyt8E0WTUA)

### 💻 Code

```ts
declare function getMaybeNumber(): any;
// declare function getMaybeNumber(): number | undefined;

function checkNum(num?: number) {
    if (!num) {
      num = getMaybeNumber() || 42;
    //   if (!num) num = 42
    }
    if (num < 50){
        throw new Error()
    };
}
```

### 🙁 Actual behavior

'num' is possibly 'undefined'.

### 🙂 Expected behavior

type of `num` narrowed to `number` or widened to `any`

### More information

The narrowing work correctly if the return type is not `any`.

The narrowing also works if using an `if` statement instead of a conditional expressions. Likely related to the design limitation that was mentioned in https://github.com/microsoft/TypeScript/issues/50739. However given that type narrowing works if the return type is not `any` there is obviously some type inference possible in conditional expressions.

**Comment by RyanCavanaugh** [comment]
The current behavior is the most-conservative since there's really no telling what is happening on that line of code, while still not completely wrecking type safety on `num` throughout the body of the function. I don't think a change in either direction as proposed is a net improvement.
