### ISSUE TITLE
Cannot read properties of undefined (reading 'length') has no userland code in stack trace

### ISSUE THREAD

**Issue by yankeeinlondon** [microsoft/TypeScript#52685]
# Bug Report

### 🕗 Version & Regression Information

I am using Typescript version `4.9.4` on a repo with TONS of types. I also have tons of "type tests" in the repo and it has always historically worked but at some point it stopped being able to be compiled with the following error:

> TypeError: Cannot read properties of undefined (reading 'length')
    at inferFromLiteralPartsToTemplateLiteral (/Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:58359:47)
    at inferTypesFromTemplateLiteralType (/Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:58340:41)
    at isTypeMatchedByTemplateLiteralType (/Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:58347:30)
    at /Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:52013:90
    at Object.some (/Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:663:25)
    at _loop_18 (/Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:52013:45)
    at removeStringLiteralsMatchedByTemplateLiterals (/Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:52018:21)
    at getUnionType (/Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:52070:21)
    at computeBaseConstraint (/Volumes/Coding/inocan/open-source/inferred-types/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsc.js:49982:85)
    at getImmediateBaseConstraint (/Volumes/Coding/inocan/open-source/inferred-types/node_modul

I have lost a week of trying to debug this because the error message is unclear and the stack trace has no userland code in it. For a while I thought maybe my use of _path aliases_ might be causing some issues so I fully removed them but the issue remains. 

This is easily reproducible by checking out: [inferred-types](https://github.com/inocan-group/inferred-types/commit/f463d22cec32d1f1e982d0488eec112ac5c55902) on the `f463d22cec32d1f1e982d0488eec112ac5c55902` commit. That [last npm release](https://github.com/inocan-group/inferred-types/releases/tag/v0.37.6) was fine but this is a substantial release.

Please keep and fill in the line that best applies:
-->
- This changed between versions v0.37.6 and #f463d22cec32d1f1e982d0488eec112ac5c55902

### ⏯ Playground Link

- check out [inferred-types on this commit](https://github.com/inocan-group/inferred-types/commit/f463d22cec32d1f1e982d0488eec112ac5c55902)
- run `pnpm install && pnpm build`

### 💻 Code

Well this is in fact THE ISSUE ... I have no idea what code is causing this issue. I did go into the `tsc` code and logged out the info available at the function point that is failing:

![image](https://user-images.githubusercontent.com/980757/217627314-54a39323-bb1b-44e7-90f3-77a4be782077.png)

This lead me to thinking possibly the _intrinsic_ `Lowercase` was the issue and I tried debugging it from that perspective but it led nowhere.

### 🙁 Actual behavior

Code compiles, types fail with no indication on why or where.

### 🙂 Expected behavior

Clear indication of WHERE the code is failing.

**Comment by fatcerberus** [comment]
TypeScript has crashed - which is always a bug - which is why it can’t tell you what code is causing the issue.  There’s likely *nothing wrong* with your TS code and you’ve just hit a bug in the compiler.

**Comment by ahejlsberg** [comment]
Super simple repro:

```ts
type Boom = 'abc' | 'def' | `a${string}` | Lowercase<string>;  // Causes crash
```

Issue is an unsafe cast we have in `removeStringLiteralsMatchedByTemplateLiterals` that causes us to treat `TemplateLiteralType` instances as `StringMappingType` instances. It's a simple fix, I'll put up a PR.

**Comment by ahejlsberg** [comment]
On another note, when I run `tsc -b -f -diagnostics` on a clone of the `inferred-types` repo, I get the following stats:

```ts
Files:               736
Lines:            154039
Identifiers:      146888
Symbols:         1792605
Types:           1218123
Instantiations:  6677012
Memory used:    1514933K
I/O read:          0.17s
I/O write:         0.00s
Parse time:        1.15s
Bind time:         0.28s
Check time:        9.20s
Emit time:         0.02s
Total time:       10.65s
```

That's an _insane_ number of types and instantiations in relation to the size of the codebase. Obviously the check time performance suffers accordingly. I'd _strongly_ recommend some dramatic simplification of those types. Any use of them makes the developer experience incredibly painful as all IDE services (like statement completion and red squigglies) slow to a crawl!

**Comment by yankeeinlondon** [comment]
@ahejlsberg thanks so much for looking at this. I did laugh a bit about your last comment (followed by a solid cry) ... this repo has been my "goto repo" for deep diving on TS for the past few years. I think recently a type or two got really slow and I'd like to start getting better at debugging these types of issues. Is there any way to isolate and report on performance on a _per file_ or _per symbol_ basis?

**Comment by yankeeinlondon** [comment]
Also, i'm assuming but don't know that a repo which consumes a small subset of types from this repo will not have to pay the performance penalty of the entirely `inferred-types` library but rather just for the types they are using in the library. @ahejlsberg wondering if you could weigh in on my whether this assumption holds or not.

**Comment by yankeeinlondon** [comment]
Also note that I tried to test using your PR:

- using `"typescript": "github:microsoft/Typescript#fix52685",` in my `Package.json`
- tsc version is `5.0.0-dev.20230112`

I still get the same error messages as before.
