### ISSUE TITLE
Why are `Object.create(null)` and `{}` treated differently regarding undefined-exclusion?

### ISSUE THREAD

**Issue by benjie** [microsoft/TypeScript#52698]
# Bug Report

### 🔎 Search Terms

- `Object.create(null)`
- POJO
- existence
- assertion
- undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Object.create(null)` but there doesn't seem to be any.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/N4KABGDGD2B2DOAXMBDAXGYAjA-B4kesArgLZYCmATgL41gC8mNA3COGAJYBmYAFAEIUAOiwBKTBwgisjZmwg0OM4ZDkBGNktAQYCZOky58hNCXLU6c4K3YQe-IaIk6IqUXIDyWAFYVIiKpUFCiIFHwkADaRYgpgStKiqhpaQA)

### 💻 Code

```ts
{
  const a: {b?: {c?:number}} = {};

  if (!a.b) {
    a.b = {};
  }
  a.b.c = 1; // Fine
}
{
  const a: {b?: {c?:number}} = {};

  if (!a.b) {
    a.b = Object.create(null);
  }
  a.b.c = 1; // TypeScript error: 'a.b' is possibly 'undefined'
}
```

### 🙁 Actual behavior

In the first block, everything is fine. In the second block, the `a.b.c = 1` line issues the TypeScript error `'a.b' is possibly 'undefined'`.

### 🙂 Expected behavior

Just as line 5 implies `a.b` exists, line 13 should do the same.

**Comment by MartinJohns** [comment]
Because `Object.create(null)` returns `any`.

**Comment by benjie** [comment]
Indeed, but why is it not treated as [`object`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#object-type) rather than `any`?

**Comment by benjie** [comment]
> it's likely not a very common use case.

When trying to avoid prototype pollution and similar issues, dealing with null-prototype objects reduces risks significantly. Any time I ever have `Record<string, any>` I always use `Object.create(null)` for it, for safety. And in performance sensitive code paths, if I know I have only used null-prototype objects then I do not need to perform `Object.hasOwnProperty` checks.

**Comment by MartinJohns** [comment]
Because `object` would not allow you to access any properties, and I guess the more common use case for this dynamic/"unsafe" object creation is to access the properties afterwards.

**Comment by benjie** [comment]
Maybe it should default to `Record<any, any>` or `Record<number | string | symbol, any>` then?

The current behavior seems suboptimal, and having to cast it when its type should already be implied via what it's being assigned to is undesirable. E.g. to change from POJO to null prototype object without affecting surrounding code we have to do quite a lot of typing:

```ts
// With POJO:
a.b = {};
// With null prototype (so verbose!):
a.b = Object.create(null) as object; // or Record<any, any>
```

Related issue from 2015: https://github.com/Microsoft/TypeScript/issues/3865

**Comment by MartinJohns** [comment]
I guess you could create an issue for that: [Lib change issue template](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/lib_change.md)

In the meantime you can simply use declaration merging to create an overload for your own code base. Just create a `.d.ts` file with this content:

```typescript
interface ObjectConstructor {
    create(n: null): {}
}
```

**Comment by fatcerberus** [comment]
Keep in mind that typescript will still treat the object (in the type system) as if it derives from `Object` - there is currently no concept of a null-prototype object type.

**Comment by NN---** [comment]
https://github.com/microsoft/TypeScript/issues/39882
