### ISSUE TITLE
TS Server stats files outside of project root when looking up modules 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#52702]
Related to #52695

# Bug Report

### 🔎 Search Terms

- fs.stat
- statSync
- performance

### Problem

While working on web project wide IntelliSense, I noticed that TS would try stating files outside of the current project root. Here's a trace of some `fs.statSync` on desktop. In this case the folder I have open is `/Users/matb/projects/san/`

```
/Users/matb/projects/san/node_modules/@nestjs/common
/Users/matb/projects/node_modules/@nestjs/common
/Users/matb/node_modules/@nestjs/common
/Users/node_modules/@nestjs/common
/node_modules/@nestjs/common
/Users/matb/projects/san/node_modules/@types/@nestjs/common
/Users/matb/projects/node_modules/@types/@nestjs/common
/Users/matb/node_modules/@types/@nestjs/common
/Users/node_modules/@types/@nestjs/common
/node_modules/@types/@nestjs/common
...
```

I know this is how node tries resolving packages, but is this something we could avoid? When opening files, we pass in a `projectRootPath` that I believe is intended to prevent TS from opening files outside of the workspace 

These calls are relatively fast on desktop but can be very slow on web as they hit the network. I had to add some extra logic to our virtual file system to avoid making these requests

**Comment by sheetalkamat** [comment]
Is this same as #52702

**Comment by fatcerberus** [comment]
Yes, this issue is the same as #52702… because that’s this issue :wink:

**Comment by sandersn** [comment]
Probably https://github.com/microsoft/TypeScript/issues/52637

**Comment by sheetalkamat** [comment]
Thanks @sandersn  thats what i meant to paste but copied from wrong tab...
