### ISSUE TITLE
Properties of type `unknown` incorrectly inferred as `string`

### ISSUE THREAD

**Issue by paleite** [microsoft/TypeScript#52700]
# Bug Report

### 🔎 Search Terms

Object spread, unknown, fallback, assertion

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwM6oKYCcoFUxYbIQAWyARgDYYAUwccAXImBgG7YCUzrHWiAbwBQiRFBJY4Ad0QBRLJKw0ABrIAeABwzQMAE0SooWGGADmAGkSm4URABIBUAJ5a4wRPTgBfZZwDcQl5CQhAIhlYYUADy5ABW2lAA6jDiAGLIlJTkxADWqXBY+XCIALyINGwZIBjM4Dlg0mCcpQB8giKIoWDhlZTVMfHQpWIuGG6IvdWlJWUARHBxCbOIAGQrE1UYiACEMywgmYgA-Bt9W8wCXgEdXeGEqAdQFx4MzIbGZohewwIvTIizbJYWaWAB04MmGAGCS+11EMHcNGcrnc90eoM8Oz2s3eJlMs2awlEokIUBAWCQaEwOHwhGIZCotDRlCgGIY-g6QQ6pPJSGZUACV2Ct1sUAwhgAaptUMMANodAD0CsQAAUqXjOmhxR1fiYNCAnohwLoMMATHpLBhNAk9FEDfrDb9PMxAchgV8vuYdYg9QaeAdKJbrTpdHaoA7ns6AUDlt8vF7RLqwBGxFhqkGtCGwymna9o27Y57vb7DcAMpgMzbQ-a-YI-i6Yx748Xk7WAAyVrM1x31-PuuMJusl5gARk7Yur4druf+rv7RcTPtbhtmIMQVszE+z097c8LzcXw4BuLMa43Ve3Paje6bg6TOfj6+DW+7kbzN4HLZzu4atkbj-PLspyvd9f0Qf8i0VZV0hgSgNQgLVUC-HcoyMKYAOfW1Xzra8IIPIdlzff5Lk9J9Nyw4CiIbAtb2QkDiIMOAAFsMBVSQNAuONSMAl9KJw988LvJdvyjEduMwycRIEmjPwAXRQGURWuMVJWlNksFkekaBoe8DXHCiHS+ZoSjaIlOjCWw4G7YZTEiaFoGSNIMiyXJ8kKBgaBLDkOgRcoACkAGUogAOVBE9TARJwaCs4Dml2MpApCsKjDxSKaB4gyDU4QkOlEW44GoUFsEUGhcuJZQHES0LwrSmKHU4b4YBlMCMAARxADIxGKSqguqlKzDSsriTIi9uyGxAGuUMqOVEIIvA5IA)

### 💻 Code

```ts
function assertUnreachable(x: never): never {
  throw Error(`Expected string, got ${typeof x}`);
}

const getObjectWithFallbackForFoo = (value: unknown) => {
  const valueObject = typeof value === "object" && value !== null ? value : {};

  // HERE'S THE BUG: valueObject is of type object, and spread like this, valueObject could contain type `{foo: number}` but would still be inferred as `{ foo: string }`
  const result: { foo: string } = { foo: "bar", ...valueObject };

  if (typeof result.foo !== "string") {
    return assertUnreachable(result.foo);
  }

  return result;
};
```

### 🙁 Actual behavior

It throws an error in `assertUnreachable`, but TS should've recognized that `foo` is of type `unknown`.

### 🙂 Expected behavior

TS should have given an error on the assignment of `result`.

**Comment by MartinJohns** [comment]
> This is a crash

This is not a crash.

This is a design limitation. The type of `valueObject` is only narrowed to `object`, the compiler has no clue what properties exists and (intentionally) assumes there are no overlapping properties.

I see only two options here:
- Avoid spreading of `object`.
- Assume that **all** properties of the object spread into are of type `unknown`.

Both more trouble than it's worth.
