### ISSUE TITLE
Specific enum value not comparable with number in 5.0

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#52701]
# Bug Report

### 🔎 Search Terms

operator cannot be applied enum number comparison

### 🕗 Version & Regression Information

- This changed between versions 4.9 and 5.0

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=5.0.0-dev.20230209#code/MYewdgzgLgBApmArgWxgYXNAhmKEYDeAUDKTACJwBmWiANlAHJbJwwC8MARFSCFwBoSZSjXpQAKgEtWIRLE4BGAAyqhZGAFksADwCSUOMnycATAFYhAXyJEAJnGB0sAJzYA3VzAghWANSw6RDgALhgkZAAjOBdbKSoYAAoff0DgmAA+dEwoHDwAOm19Q2MASkJhUhS4AKC2TgxIXNwIQt0DIwgAbiIrIA)
### 💻 Code

```ts
const enum Constants {
    DefaultName = "foo",
    DefaultTimeout = 1000,
    MaxItems = 25,
}

declare var someValue: number

if (someValue > Constants.MaxItems) {
    someValue = Constants.MaxItems;
}
```

### 🙁 Actual behavior

> Operator '>' cannot be applied to types 'number' and 'Constants'.(2365)

Removing the string-ish value from `Constants` stops the error.

### 🙂 Expected behavior

No error; even though `Constants` shouldn't be comparable thanks to #52048, this seems like it should work because it's only referencing a specific value.

/cc @Andarist @ahejlsberg

**Comment by jakebailey** [comment]
@jdom I filed this based on your TS discussion email.

**Comment by fatcerberus** [comment]
fwiw the example given feels like a misuse of enums.  If anything that should be a namespace instead.

**Comment by fatcerberus** [comment]
Generally the purpose of enums is that you have a set of symbolic constants whose exact value is unimportant (except maybe for debugging); all that’s important is that `Enum.A` is a different value from `Enum.B`

**Comment by Andarist** [comment]
The fact that this enum has mixed constant (?) values (`string | number`~) makes me believe that this code is misusing the relation operator. With my change this code errors as well (and that was "caught" and rechecked at the PR stage):

```ts
declare const val: string | number
declare var someValue: number

if (someValue > val) { // errors
    someValue = 100;
}
```

**Comment by jakebailey** [comment]
I generally agree that these "constant bags" are probably a misuse of enums, though I suspect in this case it's being used for the inlining provided by const-ness.

**Comment by jakebailey** [comment]
> makes me believe that this code is misusing the relation operator

I would disagree; this code example references a specific enum member which is a number and is interchangable with the literal 1000. It seems to me like this is a bad interaction of #52048 and #50528 where the freshness of this enum reference is being lost in the comparison check.

**Comment by Andarist** [comment]
Sure, but even with inlining - we end up comparing `number` and `number | string`. So the question is: is this something that TS considers to be safe enough to allow devs to rely on coercion here?

**Comment by Andarist** [comment]
> I would disagree; this code example references a specific enum member which is a number and is interchangable with the literal 1000. It seems to me like this is a bad interaction of https://github.com/microsoft/TypeScript/pull/52048 and https://github.com/microsoft/TypeScript/pull/50528 where the freshness of this enum reference is being lost in the comparison check.

Oh, I see what you are saying here - ye. I guess that perhaps this might be a bug worth fixing then. I would love to have some extra confirmation before I jump into fixing this though.

**Comment by jdom** [comment]
I can provide details about the reason for doing this, and is like @jakebailey mentioned: it's because it allows me to define some constants on the top of the file that I just reuse in my code, and will automatically be inlined in the generated javascript. Perhaps there's a better way to have such inlining without using `const enum`, but I have yet to find it (open to alternatives).

**Comment by jakebailey** [comment]
In this case, I think this might just be something we didn't have a test for, so wasn't caught. The error goes away if we don't `getBaseTypeOfLiteralType` the two sides before comparing them, as that function takes enum literals and converts them to their enum's base type, rather than considering the literal itself. It seems like it might be worthwhile in this case to have a variant which instead considers that specific literal's type.

But generally speaking, having a grab bag of random unrelated constants in an enum is not a super good idea; if you split them apart into smaller, related pieces, you would avoid this.

(I have further const enum inlining opinions but they're sorta moot and hypocritical given TS itself makes heavy use of them exactly for the perf of inlining...)

**Comment by jakebailey** [comment]
> The error goes away if we don't getBaseTypeOfLiteralType the two sides before comparing them

More correctly would be to have a variant of the above which checks `EnumLiteral` after all of the other literals.

**Comment by jakebailey** [comment]
I've sent #52703 for discussion.

**Comment by jakebailey** [comment]
Per design meeting, this is a bug and we should allow this code. Just need to get the above PR reviewed and fixed up.
