### ISSUE TITLE
TS Server stats odd seeming file names when resolving json import

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#52704]
Related to #52695

# Bug Report

### 🔎 Search Terms

- fs.stat
- statSync
- performance

### Problem

In a JS file, write:

```js
const a = require('./x.json');
```

This causes TS Server to stat some odd seeming file paths, such as:

```
stat /Users/matb/projects/san/x.d.json.ts
stat /Users/matb/projects/san/x.json.ts
stat /Users/matb/projects/san/x.json.tsx
stat /Users/matb/projects/san/x.json.d.ts
stat /Users/matb/projects/san/x.json.js
stat /Users/matb/projects/san/x.json.jsx
```

Could these calls be avoided? It seems unlikely that you'd want to resolve files with those names in this case

Discovered this while working on project wide IntelliSense for web

**Comment by sheetalkamat** [comment]
This is part of how module resolution works for json.
Related #51435
