### ISSUE TITLE
If-else-shorthand is executed before nullish coalescing operator 

### ISSUE THREAD

**Issue by sgohlke** [microsoft/TypeScript#52715]
# Bug Report

### 🔎 Search Terms
shorthand bracket 

### 🕗 Version & Regression Information
- Tested in playground with versions 4.9.5, 4.8.4 and nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/PTAEFEDsFcFtQJYGdTSQUwCagIYp5KOgB46wAOANuqABboBO6ANKAO40AuDCWin7BJ1qgAxpTwYUbWglEimSaJU58EhYTSRkayJegCwAKHQx44arFOcUAb2OhHoAGYIGSTswdOMogPaQmF5GTqCY6M44yp7ejpGUlABGOKIA1sYAvsbGIKAAYtCQopwIAWF+6CiQfgJoNIkMKanoNrgMfoXYCM4AtOiUGD1ItH4MwgTYMnIKldEo6uztkADmRMTootAlZaPhDAB0oDlgACr0oDAJyCL+ONRIouqrfuSMOJyjoMMdlNiSCMsNOd+ugrJABN1+IgqjVUIEIuosKxIcJkNCLrDuNAuOdun0BughiMxrQJl8RspsIkaOgAG53aDvLDGZyFYqlQjLFoWUHWADyDAAIhEoioAOpCCmcABCjTSLSQAAoQWDOAB+ABcEEs1iQwVCdTydySTU1oESfj81AIAEotTzVXZYqAmJxoAxCCrrKA1WrUBgjQlkmkfdreeCkPt4iaQ-adRH9uFItFMtkjLkCkVtoQ6igGk0FW0OoFEL1+oNviSJqxUfNpKNUk9cCgSK9isyjKysxzQFzOA7+UKRdEJcJZQWbMr4+q4+GbPqnIbjcHUmaLVb0LbZ47QPYQk5Xe7PdOfX7FUug01QwOE9GV6Bt7rE8OVDbU0ZjP5IEgN-tKH5lkVAByE5KhKFZe25acBWFZNxUlcd5VaTAKnrBhUmbNY21UTAgLfIwvx-ag-wAxU+xvTgYJfThR1oRDmknCjI1cdxOBtVgmKjNwPHwwjf3-QDyOgoc4JohC5QYpVON8AJMHYsNHX2GTAl4gIiPQEjBKgucqNE2j6IVc94VcSAkVALF0Hkzi7yaVTv340ihJ0kTRTEscJMMzoEVMoIXDuDArOnSMk1c-DPzUhzAJAsCmyc1VdNc2i+S2AzkNQjEBDYBtMNbDYcLw8L7OIgSyO0+KXJHSUOhlDzGKCrjWMCudmO4tjCvUzTSv7YTYMSqqUtqqT6uUuSOOGjZZLsjqSriwdesq4RqtSpUvJMsyLKaxSbLSKbIq6iiEoWqVlqMpNEV8+IArG5rn1Em0gA)

### 💻 Code

```ts
// Function does not use brackets around if-else-shorthand which results in wrong execution order. 
// The nullish coalescing operator should check if the element is undefined or not first, 
// if it is undefined then the if-else-shorthand should be evaluated
function getElementOrDefaultWithoutBrackets(element?: Elements,
    useFallback?: boolean): Elements {
    return element ?? useFallback ? Elements.fallback : Elements.default
}

// This should return Elements.first, but returns Elements.default
getElementOrDefaultWithoutBrackets(Elements.first)

// Function uses brackets around if-else-shorthand, this is working as expected
function getElementOrDefaultWithBrackets(element?: Elements,
    useFallback?: boolean): Elements {
    return element ?? (useFallback ? Elements.fallback : Elements.default)
}

// This correctly returns Elements.first
getElementOrDefaultWithBrackets(Elements.first)
```

### 🙁 Actual behavior

The nullish coalescing operator seems to be ignored and only the if-else-shorthand code is executed.

### 🙂 Expected behavior

The nullish coalescing operator should check first if the given value is undefined or not. If it is not undefined then the value should be used/returned. Only if it is undefined the if-else-shorthand should be evaluated. There should be no need to put brackets around the if-else-shorthand.

**Comment by whzx5byb** [comment]
`??` has a higher precedence than a ternary operator so `element ?? useFallback` is always evaluted first. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence.

**Comment by sgohlke** [comment]
Thank you for the clarification, I was not aware of that. Then I think I will go with the bracket solution as it seems to be the appropriate way to handle it.
