### ISSUE TITLE
DOMParser's parseFromString incorrectly replaces greater-than sign entity (&gt;) with >

### ISSUE THREAD

**Issue by violentorchid** [microsoft/TypeScript#52719]
# Bug Report

The HTML \&gt; entity is incorrectly being changed by the DOMParser.parseFromString method to >. This results in the content of the element being malformed is written to file.

### 🔎 Search Terms

searched for "\&gt;", \&gt;, DOMParser.

### 🕗 Version & Regression Information

"version": "4.9.5",
- I was unable to test this on prior versions because I'm using the build in VS Code Typescript module as part of QA testing.

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?allowJs=true&ts=4.9.5#code/MYewdgzgLgBFCmAPKAuaAnAlmA5jAvAOQA8ANgLYQoBuAhqQK7wzoAmAZiq7VDwJ4AHePgBEACyhQBKAPQyA7ooB08gMxKQ6HDIBMABj0BGGQA0AsgBkAysDHxytAMQZsOEQD4AZKSgBuAEaktGAA1p44fsQyFFR0jPDuhABQdOgwArToEPBp+DBg8PIwACIA8mYACpnZ6AAUAJRJpPCwiOSkKDDmFsUgwAzk8GCweRlZOUpj2QBi6CDkVlBYuLUIyAA0MIRrUDJtpISNzbCsfZ29-YPDBOnVE1Pws-OLyzirSFCb2x977YdJoEgIGaSlIIDeOyUUBAL1cDUagIgwPgoPBtX2UJhSzh9QR4CRILBb1OwExsJWuKAA)

### 💻 Code
```ts repro
const text:string ='<lms:value rdf:datatype="http://www.w3.org/2001/XMLSchema#string">&lt;blank&gt;</lms:value>'
var parser = new DOMParser()
let xml: XMLDocument = parser.parseFromString(text, 'text/xml')
let doc: Document = parser.parseFromString(text, 'text/xml')
console.log(text.toString())
console.log(xml.toString())
console.log(doc.toString())
```
### 🙁 Actual behavior
Console or any other string output contains
```<lms:value xmlns:rdf="" rdf:datatype="http://www.w3.org/2001/XMLSchema#string">&lt;blank></lms:value>```

### 🙂 Expected behavior

Console and other string output should contain:
```<lms:value xmlns:rdf="" rdf:datatype="http://www.w3.org/2001/XMLSchema#string">&lt;blank&gt;</lms:value>```

**Comment by fatcerberus** [comment]
This has nothing to do with TypeScript
