### ISSUE TITLE
CompilerOptions does not work when creating ts program

### ISSUE THREAD

**Issue by yviansu** [microsoft/TypeScript#52713]
# Bug Report

### 🔎 Search Terms

error TS2300: Duplicate identifier

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// project1/main.ts  
import ts from 'typescript';
const program: ts.Program = ts.createProgram(
            ["./sample.ts"],
            {
                module: ts.ModuleKind.ESNext,
                target: ts.ScriptTarget.ES2015,
                strict: true,
                exclude: [
                    "./node_modules/@types/mocha/index.d.ts"
                ]
            },
        );
 const sourceFileList = program
            .getSourceFiles()
            .filter(
                (sourceFile: ts.SourceFile) =>
                    sourceFile.fileName.match('mocha'),
            );
            
console.log(sourceFileList.length);
if (sourceFileList.length > 0) {
    console.log(sourceFileList[0].fileName);
}

// project2/sample.ts
function test() {
    return 1;
}

// project1/node_modules/@types/mocha/index.d.ts
declare var test: Mocha.TestFunction;

```

### 🙁 Actual behavior

Since `project1/node_modules/@types/mocha/index.d.ts` has a declared function `test`, other files in the project1 can not have a function named `test`. 

In project2, I can create a function named `test`, however, when I compile `project2/sample.ts` in `project1/main.ts` using compiler API, an error will be reported.
```
../../node_modules/@types/mocha/index.d.ts:2725:13 - error TS2300: Duplicate identifier 'test'.

2725 declare var test: Mocha.TestFunction;
                 ~~~~
../../../project2/sample.ts:1:10 - error TS2300: Duplicate identifier 'test'.

1 function test() {
           ~~~~
```

So I add `exclude:  [ "./node_modules/@types/mocha/index.d.ts" ]` in `CompilerOptions`. However, when I run code again, the same error happens, and the `console.log` will print:
```
1
/project1/node_modules/@types/mocha/index.d.ts
```

### 🙂 Expected behavior

Now that `exclude` field has been added to `CompilerOptions`, the ` Duplicate identifier 'test'` error should disappear, and the `console.log` should print:
```
0
```

**Comment by MartinJohns** [comment]
`exclude` can't be used to exclude global type definitions. You have to use `types` oder `typeRoots` instead. See this SO answer for slightly more information: https://stackoverflow.com/a/52621223
