### ISSUE TITLE
Type 'RemovePrefix<K, Prefix>' cannot be used to index type 'T' (regression in TypeScript 4.9)

### ISSUE THREAD

**Issue by hartbit** [microsoft/TypeScript#52714]
# Bug Report

The following piece of code I created stopped working between TypeScript 4.8.4 and 4.9.5.

It seems like TypeScript can't guarantee anymore that the `RemovePrefix` type returns a `string` key that exists on `T`.

### 🕗 Version & Regression Information

- This changed between versions 4.8.4 and 4.9.5

### ⏯ Playground Link

[Playground link in TypeScript 4.9.5](https://www.typescriptlang.org/play?ts=4.9.5#code/C4TwDgpgBAShC2B7AbhACgJwgMwJYA8AeAFSgn2AgDsATAZyjuA1yoHMAaKTHAsi6vUbNWbAHxQAvFFLlKtBgAMAJAG8eefAF81rbBAxQAYrggAbGlsVQA-MdMWoALihUIqDAG4AUKEjcsTQgaEi4NPjlBBiYWdglpVW8oKABtAGkoVigVdUCCHVUAawgQRGwZKAAyYVi2KwBdF2IUuCRUcKI0sLz8MXqfLU8gA)

### 💻 Code

```ts
type RemovePrefix<T extends string, Prefix extends string> = T extends `${Prefix}${infer Field}` ? Field : never;
type Prefixed<T, Prefix extends string> = {
  [K in `${Prefix}${keyof T & string}`]: T[RemovePrefix<K, Prefix>];
};
```

### 🙁 Actual behavior

It generates a `Type 'RemovePrefix<K, Prefix>' cannot be used to index type 'T'` error.

### 🙂 Expected behavior

It should work as before.

**Comment by whzx5byb** [comment]
The behavior in 4.8.4 seems unreliable since you can even write
```ts
type Prefixed<T, Prefix extends string> = {
  [K in keyof T & string]: T[RemovePrefix<K, K>];
};
```
and ts doesn't check whether `RemovePrefix<K, K>` is a valid index type. (obviously not)

**Comment by RyanCavanaugh** [comment]
I believe @whzx5byb; this only ever "worked" because it wasn't being correctly checked at all. There isn't support for detecting the sort of higher-order relationship you'd need to identify to allow this.
