### ISSUE TITLE
readline: `line` and `cursor` from `class Interface` are declared readonly but may be edited according to nodejs api docs

### ISSUE THREAD

**Issue by antonilol** [microsoft/TypeScript#52725]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

file: `@types/node/readline.d.ts`

current version: `"@types/node": "^18.11.19"`

`line` and `cursor` from `class Interface` are declared readonly but may be edited, in the description of rl.line (https://nodejs.org/api/readline.html#rlline) it mentions that you should control rl.cursor as well when editing. this implies both properties are not readonly

## Sample Code

```ts
import { createInterface } from "readline";

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.line += 'Hello';
rl.cursor += 5;
```

## Documentation Link

https://nodejs.org/api/readline.html

**Comment by fatcerberus** [comment]
`@types/node` isn’t maintained by the TypeScript team.  You should file this against DefinitelyTyped instead.

**Comment by antonilol** [comment]
thanks for pointing me in the right direction, found an issue from someone else on exactly this there so closing this

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60465
