### ISSUE TITLE
let getter Generics support... thanks..or we have a workaroud? THANKS.

### ISSUE THREAD

**Issue by zhangenming** [microsoft/TypeScript#52735]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 💻 Use Cases

```js
Object.defineProperty(Object.prototype, 'logOfFunc', {
  value() {
    console.log(this)
    return this
  },
})

Object.defineProperty(Object.prototype, 'logOfGetter', {
  get() {
    console.log(this)
    return this
  },
})

const x = ['']
const y1 = x.logOfFunc() // fine
const y2 = x.logOfGetter //  expect: string[], how we did this?

declare global {
  interface Object {
    logOfFunc<T>(this: T): T // fine
    // get logOfGetter<T>(this: T): T // oh no...here Generics are not supported
  }
}

```

**Comment by fatcerberus** [comment]
`logOfFunc<T>(this: T): T` is more-or-less equivalent to `logOfFunc(): this`.  Therefore you should be able to do this already by declaring the return type of the the getter as `this`.  Outside of this single use case it doesn't really make sense for a getter to have type parameters, which is why it's not supported.

**Comment by zhangenming** [comment]
so, Do we have a way to make it (`x.logOfGetter`) work right now ? thanks

**Comment by fatcerberus** [comment]
I just told you how to make it work
