### ISSUE TITLE
`{} | unknown` is assignable to Uppercase<string> and Co.

### ISSUE THREAD

**Issue by geoffreytools** [microsoft/TypeScript#52731]
# Bug Report

### 🔎 Search Terms

Intrinsic string manipulation types,Uppercase<string>, Lowercase<string>, Capitalize<string>, Uncapitalize<string>

### 🕗 Version & Regression Information

Since 4.8.4.
`Uppercase<string>` use to resolve to `string` between 4.1.5 and 4.7.4
The behaviour in 4.8.4 is not the same as in 4.9.5 / Nightly

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/C4TwDgpgBA8gRgKygXigbwL5QgD2BAOwBMBnKAVTEgCcBjAQxIgB4ThqBLAgcwD4oA-FHYBXaAC4oAM3oAbJgChQkCgQDWKKCPUEA9gHcC2PIVIUqEOoxZtOPfkNETpcpkA)

### 💻 Code

```ts
type Obj = {} extends Uppercase<string> ? true : false      // true
type Unk = unknown extends Uppercase<string> ? true : false // true
```

### 🙁 Actual behavior

The return value is `true`. It should not be, because intrinsic string manipulation types should resolve to subtypes of `string` (or `string` at the very least), and `{}` or `unknown` are not assignable to `string`.

### 🙂 Expected behavior

I expected the return type to be false.

**Comment by fatcerberus** [comment]
Just to double-check, yeah:
```ts
const x: Uppercase<string> = 42;  // no error
const y: Uppercase<string> = { foo: "bar" };  // no error
```

**Comment by jakebailey** [comment]
Bisects to #47050.
