### ISSUE TITLE
Revert 'hangup', 'togglecamera' and 'togglemicrophone' action handlers from MediaSession in TypeScript 4.9+

### ISSUE THREAD

**Issue by vatson** [microsoft/TypeScript#52743]
# lib Update Request

Action definitions that have existed for years have been removed with the latest LKG update for 4.9+
 https://github.com/microsoft/TypeScript/pull/51683/commits/3a6d7e9c8cbfae2739b572bc223c376432731c20#diff-796971dc74a3f3cd77ca0a3a776d6fe27ab224cd501d9652dbeffcf45ba0f058L18186 

When 4.8.3 still has these definitions https://github.com/microsoft/TypeScript/blob/v4.8.4/lib/lib.dom.d.ts#L18186

Media Session Standard specification has information about these types of actions  https://w3c.github.io/mediasession/#mediasession It is difficult to classify these things as experimental, because the standard itself is still Draft

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `the default`.

## Missing / Incorrect Definition

MediaSessionAction has lost `hangup`, `togglecamera` and `togglemicrophone` options.

## Sample Code
```typescript
 navigator.mediaSession.setActionHandler('togglecamera', () => {
   // toggle camera
 });
```

## Documentation Link

https://w3c.github.io/mediasession/#dom-mediasession-setactionhandler

**Comment by sandersn** [comment]
MediaSession is only implemented in one browser engine, but Typescript requires two implementations for draft standards to be included in the standard lib. See for example: https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/821

In 4.9 the parts of the standard that were mistakenly included were moved out of an upstream definitions repository and as a result, out of Typescript: https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1400
