### ISSUE TITLE
String and number properties are narrowed down to literals when using Generics + Partial

### ISSUE THREAD

**Issue by Sharcoux** [microsoft/TypeScript#52756]
The string and number properties are narrowed down to literals instead when using Generics + Partial. Here is a [link to illustrate](https://www.typescriptlang.org/play?ssl=7&ssc=100&pln=1&pc=1#code/MYewdgzgLgBFCm0YF4YB4AKAnEAHCANDAHwAUAwiALa7jxhQBcMpuO+z2eEAlCsTACGYAJ59kAgN4AoGDFCRYAUQAeCMABN4GyjRQs23Tu178Yu2mHpRWJnrJir1WndVwA6QVChYI+zIJYUEQASogArgA2sPBq9Bp+GIFQAJaCkQFBMABkMFz4AqhJQWkZxbC5+RDEZF4+EJzJpZkVeSbE4gK2RjBhEFFQnSyS7qN1vkSj7ob4MAC+9nJY8FDhWGCOcZraFtJz0gpIFvrdHDCScIhMMNBYKWAA5vNDMxDSCNAUbjye3r6kkg+1wA5CAANbAhYAy7QZjAsDgyF8AD0yPQAFoYAAVES4eAwYEAIgRYMJwJgKT8CNggggEBSDzAggARpF8VAQHBcfiieCye4gA).

In this code, we create a method to pre-configurate some props of a component

```typescript
const test = <Props, >(Component: (props: Props) => any) => {
  const ExtendedComp = (props: Props) => Component(props)
  ExtendedComp.attrs = <Part, Result extends Partial<Part & Props> = Partial<Part & Props>>(attrs: Partial<Part & Props>) => (props: Result) => ({...attrs, ...props })
  return ExtendedComp
}
const Comp = (props: { test: string }) => props
test(Comp).attrs({test: 'ok'})({ test: 'nok'}) // <- Type '"nok"' is not assignable to type '"ok"'.
```

As a comparison, [here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCm0YF4YB4AKAaAfACgGEQBbAB3HjCgC4Y9SAnEUiWjAShRxgEMwBPTsm4BvAFAwYoSLACiADwRgAJvGVEyKOo2asYHLjA3kwlKPSYt2EmAqWr1JUgDoeUKAwha0AFVx43Dz0fGAAyfR4GKABLHgAbTBwhbgtdNkiY+N8w-STDPBEYZ2LAzywi4p0WGABfa0kGeCgAVwYwW0VKB2MxGrFpJGMtVJZaQoRoWmgGaLAAc1rkmCqIMQnzY3ZXd08CuEQaGAByEABrI8W99dojsDOLupgAeif0AFoYADkQGHgGJgYQA) is another approach that gives the expected result:

```typescript
const test = <P,>(Component: (props: P) => any) => {
  const ExtendedComp = (props: P) => Component(props)
  ExtendedComp.attrs = <T,>(attrs: T & Partial<P>) => (props: Partial<T & P>) => ({ ...attrs, ...props })
  return ExtendedComp
}
const Comp = (props: { test: string }) => props
test(Comp).attrs({ test: 'ok' })({ test: 'nok' }) // <- No error
```

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by Sharcoux** [comment]
@RyanCavanaugh I believe that the template I used didn't have those instructions

**Comment by Sharcoux** [comment]
@RyanCavanaugh Just to confirm, I checked, and the template about callback functions doesn't contains the template questions. Also, when I read the instructions, it is not clear if that template should not be used at all or if it can be used but only not for the 2 topics mentioned. I say that just to hint you about the fact that, maybe, that template might need clarification.
