### ISSUE TITLE
String and number properties are narrowed down to literals when using Generics + Partial

### ISSUE THREAD

**Issue by Sharcoux** [microsoft/TypeScript#52758]
# Bug Report

### 🔎 Search Terms

string literal partial

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about string literal

### ⏯ Playground Link

Here is a [link to illustrate](https://www.typescriptlang.org/play?ssl=7&ssc=100&pln=1&pc=1#code/MYewdgzgLgBFCm0YF4YB4AKAnEAHCANDAHwAUAwiALa7jxhQBcMpuO+z2eEAlCsTACGYAJ59kAgN4AoGDFCRYAUQAeCMABN4GyjRQs23Tu178Yu2mHpRWJnrJir1WndVwA6QVChYI+zIJYUEQASogArgA2sPBq9Bp+GIFQAJaCkQFBMABkMFz4AqhJQWkZxbC5+RDEZF4+EJzJpZkVeSbE4gK2RjBhEFFQnSyS7qN1vkSj7ob4MAC+9nJY8FDhWGCOcZraFtJz0gpIFvrdHDCScIhMMNBYKWAA5vNDMxDSCNAUbjye3r6kkg+1wA5CAANbAhYAy7QZjAsDgyF8AD0yPQAFoYAAVES4eAwYEAIgRYMJwJgKT8CNggggEBSDzAggARpF8VAQHBcfiieCye4gA).

### 💻 Code

In this code, we create a method to pre-configurate some props of a component

```ts
const test = <Props, >(Component: (props: Props) => any) => {
  const ExtendedComp = (props: Props) => Component(props)
  ExtendedComp.attrs = <Part, Result extends Partial<Part & Props> = Partial<Part & Props>>(attrs: Partial<Part & Props>) => (props: Result) => ({...attrs, ...props })
  return ExtendedComp
}
const Comp = (props: { test: string }) => props
test(Comp).attrs({test: 'ok'})({ test: 'nok'}) // <- Type '"nok"' is not assignable to type '"ok"'.
```

### 🙁 Actual behavior

The string and number properties are narrowed down to literals instead when using Generics + Partial.

I get the error: `Type '"nok"' is not assignable to type '"ok"'.` because the `test` prop is inferred as string literal. If I had used a number, it would have been inferred as number literal.

### 🙂 Expected behavior

As a comparison, [here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCm0YF4YB4AKAaAfACgGEQBbAB3HjCgC4Y9SAnEUiWjAShRxgEMwBPTsm4BvAFAwYoSLACiADwRgAJvGVEyKOo2asYHLjA3kwlKPSYt2EmAqWr1JUgDoeUKAwha0AFVx43Dz0fGAAyfR4GKABLHgAbTBwhbgtdNkiY+N8w-STDPBEYZ2LAzywi4p0WGABfa0kGeCgAVwYwW0VKB2MxGrFpJGMtVJZaQoRoWmgGaLAAc1rkmCqIMQnzY3ZXd08CuEQaGAByEABrI8W99dojsDOLupgAeif0AFoYADkQGHgGJgYQA) is another approach that gives the expected result:

```ts
const test = <P,>(Component: (props: P) => any) => {
  const ExtendedComp = (props: P) => Component(props)
  ExtendedComp.attrs = <T,>(attrs: T & Partial<P>) => (props: Partial<T & P>) => ({ ...attrs, ...props })
  return ExtendedComp
}
const Comp = (props: { test: string }) => props
test(Comp).attrs({ test: 'ok' })({ test: 'nok' }) // <- No error
```

`test` is correctly inferred to string. The two codes are pretty similar and should probably behave the same, which is why I believe that this is a bug.

**Comment by RyanCavanaugh** [comment]
Getting more specific inference than expected isn't really "wrong", it's just not guessing what you wanted it to guess (that's why they call it inference, not determination 😉). Here we have a hint type of `string` from the `test(Comp)` that ends up fixing `'ok'` to a literal type, which in general is the intended behavior.

**Comment by Sharcoux** [comment]
Ok, but the problem with that is that it is very easy to convert a string to a string literal in typescript using `as const`, but I have no way to do the other way around. Or at least, I didn't find it in the documentation.

**Comment by RyanCavanaugh** [comment]
`as string` ?

**Comment by Sharcoux** [comment]
I was gonna reply about the issue with objects, but actually I can probably solve it with `x as typeof x`. It makes the function a bit annoying to use, though, but whatever. There is just one last weird detail before I close that thread. Check [this](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCm0YF4YB4AKAnEAHCANAHwAUAwiALa7jxhQBcMJuO+T2eEAlCkTAEMwAT17J+AbwBQMGKEiwAogA8EYACbx1FaimasuHNjz4wdNMHSgtj3GTBVrN2qrgB0AqFCwQ9mAVhQBDAASogArgA2sPCqdOq+GAFQAJYCkf6BMABkMJz4-KhJgWkZxbC5+RBEpJ7eEBzJpZkVecZEYvw2hqER0Z3MEjBuI3U+wSNuBvgwAL52sljwUOFYYA5xGlrmUrNS8kjmet3sMEMI0EzQWClgAOZzA9MQUvvgSM9hwPApAG5aADEcJRFJEIPAAO4AC3gSz00lkF0YMAA5GAQABrFEEXavJHkVzcDxeHwkBFwRDIlGY7G7bgnCBfH7-dRAqig8HQ2HwXgAel56AAtDAACrCXDwVHXW53FEwFK+dGwAQQCApO5gAQAI0ikqgIDg4slKIARJiTSi3HjKQTqESxhAyfYkUxqVicbNBL4oEaQAAzGCfeDfP6A4EcyEwpb0oMhllskFgyPcvkCtDCgDqICwGJlXpgsQlwAQ6mt0FtuHtJMdseZYfZSa50adiMprppHtTQpgWZzeYA-ABCQdSIA) out:

```ts
const test = <Props,>(Component: (props: Props) => any) => {
  const ExtendedComp = (props: Props) => Component(props)
  ExtendedComp.attrs = <Part, Result extends Partial<Part & Props> = Partial<Part & Props>>(attrs: Partial<Part & Props>) => (props: Result) => ({ ...attrs, ...props })
  return ExtendedComp
}
const Comp = (props: { test: string }) => props

const propsReceivedFromElsewhere = {
  test: 'nok',
}

test(Comp).attrs({
  test: 'ok',
})(propsReceivedFromElsewhere) // <- Type 'string' is not assignable to type '"ok"'.

test(Comp).attrs({
  test: 'ok',
} as typeof propsReceivedFromElsewhere)(propsReceivedFromElsewhere) // <- Working as expected

test(Comp).attrs(propsReceivedFromElsewhere)({
  test: 'ok',
}) // <- Working ?!!
```

This is the first time I see, in Typescript, a difference in the type between an object when used as a variable or when declared explicitly. Is this expected ?

**Comment by Sharcoux** [comment]
I was gonna reply about the issue with objects, but actually I can probably solve it with `x as typeof x`. It makes the function a bit annoying to use, though, but whatever. There is just one last weird detail before I close that thread. Check [this](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCm0YF4YB4AKAnEAHCANAHwAUAwiALa7jxhQBcMJuO+T2eEAlCkTAEMwAT17J+AbwBQMGKEiwAogA8EYACbx1FaimasuHNjz4wdNMHSgtj3GTBVrN2qrgB0AqFCwQ9mAVhQBDAASogArgA2sPCqdOq+GAFQAJYCkf6BMABkMJz4-KhJgWkZxbC5+RBEpJ7eEBzJpZkVecZEYvw2hqER0Z3MEjBuI3U+wSNuBvgwAL52sljwUOFYYA5xGlrmUrNS8kjmet3sMEMI0EzQWClgAOZzA9MQUvvgSM9hwPApAG5aADEcJRFJEIPAAO4AC3gSz00lkF0YMAA5GAQABrFEEXavJHkVzcDxeHwkBFwRDIlGY7G7bgnCBfH7-dRAqig8HQ2HwXgAel56AAtDAACrCXDwVHXW53FEwFK+dGwAQQCApO5gAQAI0ikqgIDg4slKIARJiTSi3HjKQTqESxhAyfYkUxqVicbNBL4oEaQAAzGCfeDfP6A4EcyEwpb0oMhllskFgyPcvkCtDCgDqICwGJlXpgsQlwAQ6mt0FtuHtJMdseZYfZSa50adiMprppHtTQpgWZzeYA-ABCQdSIA) out:

```ts
const test = <Props,>(Component: (props: Props) => any) => {
  const ExtendedComp = (props: Props) => Component(props)
  ExtendedComp.attrs = <Part, Result extends Partial<Part & Props> = Partial<Part & Props>>(attrs: Partial<Part & Props>) => (props: Result) => ({ ...attrs, ...props })
  return ExtendedComp
}
const Comp = (props: { test: string }) => props

const propsReceivedFromElsewhere = {
  test: 'nok',
}

test(Comp).attrs({
  test: 'ok',
})(propsReceivedFromElsewhere) // <- Type 'string' is not assignable to type '"ok"'.

test(Comp).attrs({
  test: 'ok',
} as typeof propsReceivedFromElsewhere)(propsReceivedFromElsewhere) // <- Working as expected

test(Comp).attrs(propsReceivedFromElsewhere)({
  test: 'ok',
}) // <- Working ?!!
```

This is the first time I see, in Typescript, a difference in the type between an object when used as a variable or when declared explicitly. Is this expected ?

**Comment by Sharcoux** [comment]
No, forget it. I think I understand why, and it more or less makes sense. Thanks for your answers.

**Comment by RyanCavanaugh** [comment]
> This is the first time I see, in Typescript, a difference in the type between an object when used as a variable or when declared explicitly. Is this expected ?

Yes; it's actually rather common but manifests in ways that only help or aren't readily observable.
