### ISSUE TITLE
v5 beta typescript support for export type * not working

### ISSUE THREAD

**Issue by tylim88** [microsoft/TypeScript#52755]
# Bug Report

### 🔎 Search Terms

v5 beta typescript Support for export type * not working

### 🕗 Version & Regression Information

v5.0.0 beta

### ⏯ Playground Link

none

### 💻 Code

abc.ts
```ts
export type A=1
```
src.ts
```ts
export type * from './abc'
```
### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/5227509/218805180-54acfada-37bd-4793-b49b-67c473592c28.png)

### 🙂 Expected behavior
no error

**Comment by RyanCavanaugh** [comment]
I guarantee the issue here is you're using TypeScript 4.9 or earlier. TypeScript 5.0 [removed that error entirely](https://github.com/microsoft/TypeScript/pull/52217/files#diff-fdf3f532dc2d3188ad1c05c8c9e064d0aa4143b8ba09b8f3313a0243f0a43effL1199)

**Comment by tylim88** [comment]
![image](https://user-images.githubusercontent.com/5227509/218809899-4b0898f9-cb97-46cc-8614-97376405b960.png)
This is the only thing in my package.json

any else potential cause?

**Comment by RyanCavanaugh** [comment]
In VS Code, run the "Select TypeScript Version..." command from the command palette. I believe it's called the "workspace version" in this case (it should be obvious when you see the list)

**Comment by tylim88** [comment]
```ts
{
	"compilerOptions": {
		"strict": true,
	},
}
```
my config

**Comment by tylim88** [comment]
> In VS Code, run the "Select TypeScript Version..." command from the command palette. I believe it's called the "workspace version" in this case (it should be obvious when you see the list)

ah I see, solved, thanks

**Comment by fatcerberus** [comment]
@RyanCavanaugh I honestly hate the UI for that now.  It used to be more obvious that "wrong TS version" was the problem as the TS version would be prominently displayed in the status bar and you could just click on it to change it.  Now you have to hover over the little curly-brace icon next to "TypeScript" in the status bar to even *see* which TS version is in use, and very delicately move the mouse to click "Select Version" (which about 50% of the time results in dismissing the hover tip).  It's not at all obvious that this is even a feature anymore.
