### ISSUE TITLE
Provide an API to convert tsconfig.json to CompilerOptions

### ISSUE THREAD

**Issue by IgorMinar** [Microsoft/TypeScript#5276]
Since IDEs like VS Code use `tsconfig.json` to figure out how to parse a project, it makes sense for all the other build tools (gulp, broccoli, webpack, etc) to pull the tsc config from `tsconfig.json` as well, instead of having their own custom way to configure tsc.

In order for this to be seamless, Typescript needs to provide a way to parse tsconfig.json to `CompilerOptions` object. `tsc` already does this internally, but all of the apis it uses are private.

I've put together my own converter for Angular/broccoli-typescript, but it will get stale with the next version of typescript until I update my option mappings. See `ts-config-converter.ts` added in https://github.com/angular/angular/pull/4779/

I believe that this task is so common that it should be part of typescripts public api.

cc: @alexeagle

**Comment by mhegazy** [comment]
here you go: https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L1536-L1555

use `ts.parseConfigFile` to parse the text. if you want to parse the JSON the same way as the compiler does as well (currently using JSON.parse, but possibly in the future do something more interesting allowing comments for instance) use `ts.parseConfigFileText`

**Comment by IgorMinar** [comment]
Awesome. That's what I need. 

Is the filename option significant? We also have a use case where the configuration is an object already in the tsconfig format, so I would just serialize it and pass it in as text with bogus filename. Will there be any problems with that?

**Comment by mhegazy** [comment]
in parseConfigFileTextToJson the name is used only for the error message.
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L401

in parseJsonConfigFileContent basePath is expected to be the location of the tscongfig, as all files path in the options are considered relative to the file location.
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/commandLineParser.ts#L416

**Comment by IgorMinar** [comment]
I tried using `parseJsonConfigFileContent` but it feels too heavyweight since it requires me to implement `ParseConfigHost`.

All I want is:

```
ts.convertConfigToCompilerOptions({
    emitDecoratorMetadata: true,
    experimentalDecorators: true,
    declaration: true,
    module: 'commonjs',
    moduleResolution: 'classic',
    noEmitOnError: true,
    rootDir: '.',
    sourceMap: true,
    sourceRoot: '.',
    target: 'es5'
})
=> CompilerOptions
```

Could that be a thing?

**Comment by vladima** [comment]
I don't see why not, we already have this code as nested function of `parseJsonConfigFileContent`.
Also as a temporary workaround for now you can use something like this
```javascript
function convertConfigToCompilerOptions(opts) {
	var parsed = ts.parseJsonConfigFileContent({
		compilerOptions: opts,
		// if files are not specified then parseJsonConfigFileContent 
		// will use ParseConfigHost to collect files in containing folder
	    files: []  
		},
		// we don't do any file lookups - host and base folders should not be used
		undefined, 
		undefined);
	return parsed.options;
}
```

**Comment by IgorMinar** [comment]
That worked! It's a bit awkward, but it works. Thanks Vladimir.

**Comment by vladima** [comment]
@IgorMinar `convertCompilerOptionsFromJson` will be available in todays nightly build

**Comment by wycats** [comment]
@mhegazy @vladima This is getting pretty frustrating; it just broke again.

Here's what we had to do to get it working on `typescript@next`: https://github.com/tildeio/broccoli-typescript-compiler/commit/ff874d99dbd2b691a5298c7061db134262d72dd0?w=1

Can you recommend a stable API we can use?

**Comment by wycats** [comment]
See also https://github.com/tildeio/broccoli-typescript-compiler/issues/7.

We're very eager to get on a supported, stable path here, but can't seem to find one.

**Comment by vladima** [comment]
@wycats apologies, this breaking change was not intentional. I'll revert `convertCompilerOptionsFromJson` to the shape it used to be in 1.8

**Comment by wycats** [comment]
@vladima is there any way we can get the tests of this functionality to be considered regressions, so people don't just change them at the same time as the functionality?

Maybe a note in the tests?

**Comment by vladima** [comment]
I'll add tests on our side to make sure that public surface of the API is not changed in an unexpected way

**Comment by MartinJohns** [comment]
@vladima Unfortunately the `host` can't be set to `undefined` anymore, as the type is not `ts.ParseConfigHost | undefined`. I don't see a way to use this function anymore.

**Comment by alexeagle** [comment]
You can just supply a simple ts.ParseConfigHost implementation, it's only a
couple methods.
