### ISSUE TITLE
Property setters with number | bigint don't allow to use +=, -=, *=, ... operators

### ISSUE THREAD

**Issue by SalvatorePreviti** [microsoft/TypeScript#52771]
# Bug Report

```ts
class A {
   get x(): bigint { return 100n; }
   set x(value: number | bigint) { console.log(value); }
}

const a = new A();

a.x += 100n; // causes Operator '+=' cannot be applied to types 'number | bigint' and 'bigint'

```

Expected that the compiler accept this code, is valid in JS and the intended result is clear.

const q = a.x += 100n; // q should be of type bigint

### 🔎 Search Terms

int, bigint, operators

### 🕗 Version & Regression Information

Tested it fails from Typescript 4.3.5 to 4.9.5

Setters with different types than getters were introduced in 4.3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=8&ts=4.9.5#code/MYGwhgzhAECC0G8BQ1UHMCmAXaAPAFAJQBc0ARgJZoUB2OC0ATtgK6M3QCMADNzQNzQAvilQRsefADcwIFhlI0WAWzIZG0AD7kqtLIUTRgAexoRjIDADoQxtNNnzCgkSKQmzOMNAC80GhgA7nBE-EhIYFa40ADUfjx8ggD0SUZgLOIwAPIADupgWMYaAORxxWk0NMY4atBgOTkgFBgAJtCF7QCeeTDFSqrqWjrUdOVgNG3FlCNYxUA)

### 💻 Code

```ts
class A {
   get x(): bigint { return 100n; }
   set x(value: number | bigint) { console.log(value); }
}

const a = new A();

a.x += 100n; // causes Operator '+=' cannot be applied to types 'number | bigint' and 'bigint' ts(2365)

```

### 🙁 Actual behavior

Operator '+=' cannot be applied to types 'number | bigint' and 'bigint'. (2365)

### 🙂 Expected behavior

No errors

**Comment by RyanCavanaugh** [comment]
Actually, duplicate #48292
