### ISSUE TITLE
Trigger Error on Impossible Extends Case

### ISSUE THREAD

**Issue by tylim88** [microsoft/TypeScript#52770]
# Suggestion

## 🔍 Search Terms

Trigger Error on Impossible Extends Case

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [?] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [?] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

![image](https://user-images.githubusercontent.com/5227509/218894101-4803606a-4797-4b0e-bc6b-c23df8e03801.png)

would be great if the compiler can notify us that the true case is impossible case.

## 📃 Motivating Example

libraries that use complex type

## 💻 Use Cases

improve dev experience of type level programming

**Comment by fatcerberus** [comment]
So the problem with this is that lots of people write “conditional types” that aren’t actually conditional just to get the distributive behavior; the proposed error would just get in the way.

**Comment by tylim88** [comment]
I see, that is a problem too

**Comment by RyanCavanaugh** [comment]
Don't post screenshots of code. Post code. If you must post screenshots, don't post screenshots with syntax errors in them.

Apart from the case of conflicting primitives, there aren't really cases of `type X<T extends U> = T extends V ?` where `U & V` is provably unhabitable. It's a difficult mistake to make in the first place, and an even more difficult mistake to *detect*.
