### ISSUE TITLE
`.d.ts` file is not a module when used from the language service

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5277]
# Test files 

tsconfig.json:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": false,
        "noLib": false
    },
    "compileOnSave": true,
    "filesGlob": [
        "./**/*.ts"
    ],
    "files": [
        "main.ts",
        "test/index.ts"
    ],
    "exclude": []
}
```

main.ts:
```
import {Test} from "./test";

let t = new Test();
```

test/index.ts:
```
export class Test {

}
```

# Error details 
Code compiles fine from command line. Errors in IDE `test.d.ts` is not a module. 

Refs https://github.com/TypeStrong/atom-typescript/issues/664

**Comment by mhegazy** [comment]
@vladima  any ideas?

**Comment by DeliciousPickle** [comment]
Is there any workaround for this?

**Comment by mhegazy** [comment]
@basarat do you know what files are passed to the language service?

**Comment by basarat** [comment]
> do you know what files are passed to the language service?

Good call. I see `test.d.ts`:

![image](https://cloud.githubusercontent.com/assets/874898/11105899/33d9241a-8926-11e5-8f22-747fed646864.png)

Don't know where its coming from. I'll investigate tonight and get back to you if this is not because of my code :rose:

**Comment by basarat** [comment]
Fixed : https://github.com/TypeStrong/atom-typescript/releases/tag/v7.9.0 :rose:
