### ISSUE TITLE
Unexpected `any[]` spreading `string` into `unknown[]`-constrained argument position

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#52781]
# Bug Report

### 🔎 Search Terms

any spread string

### 🕗 Version & Regression Information

- This changed between versions 3.9 and 4.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=6&ssc=1&pln=1&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwB4AVeEADwxFWAGd40BrVHAd1QG0BdAPgAoAdMNgBzOgC54JAJRSSAbgCwAKAD0a+AAcpUVAE8eAGnIUt4asHh0MMLKlE9VYPDe3wAvARxDhAIgALEAgIHD8ZZXVNAAEMOgBaSnNMRJgYHBhVLU4ABm5BACNoANUgA)

### 💻 Code

```ts repro
declare function foo<T extends unknown[]>(...args: T): T;
// p: any[], expected string[]
const p = foo(..."hello");
// @ts-expect-error
p[0].blah
```

### 🙁 Actual behavior

`p` is `any[]`

### 🙂 Expected behavior

`p` is `string[]`

**Comment by Andarist** [comment]
<img alt="Barney Stinson saying dibs" src="https://media.giphy.com/media/3oEdv6oYpOcg5lGYfe/giphy.gif" />
