### ISSUE TITLE
The typings can only be a `.d.ts` file. Contact package author to fix it

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5278]
Happens when using the latest compiler as a language service. Sample package : csx https://github.com/basarat/csx `npm install csx`. 

I suspect that https://github.com/Microsoft/TypeScript/pull/4911 broke it ... it now looks at the `csx.ts` file and errors :rose:

**Comment by mhegazy** [comment]
yup. that would be a side effect of #4911. the fix would be to add the full extension in the typings field (`"typings": "csx.d.ts"`).

We have got feedback about users wanting to include their `.ts` files and found the compiler changing its lookup rules to pick `.d.ts` files too restrictive. 

We should remove the error though.
