### ISSUE TITLE
Generic inference from property return type fails only if parameters exist and JSX attribute syntax is used

### ISSUE THREAD

**Issue by henry-bishop** [microsoft/TypeScript#52786]
# Bug Report

### 🔎 Search Terms
- Generics
- JSX
- Inconsistent
- Inference

### 🕗 Version & Regression Information

This is the behavior in every version I've tested including `4.7.4` up to `5.0.0-dev.20230215`
(Before `4.7.4`, the issue occurred regardless of whether JSX syntax was used)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4Aoc4AOxiSk3STgAUcwBnAHgBUA+OAG9yASBQAuOAAoAHpI4woNAOYBKOAF4BPCiIBGkqSijLJPdVrgA3CMAAmFAL6VMAV2oZgEanABiECF4+KTB2Dkk2CE4g9WERIhhXKB8uO2ArOAB6PidKTMy4AHVoAGsOOEwaJAAaOB44YHKaTHoiOzgUcoByalcQPXouuBgACxxXZRHhkeYEpJ8rFAAbV2YITDgulC7yLn8IURQNQSkLAQBGAAZnfWOjEzOhDpMAOhgIAGVFFVPSOEdnNkKOR8nAAJIbLZDGAoEpIcooagATzgYGMKBASDoUA4tWa9CQHmYCii5QA7qUVB1qO16gM0Lh4Zt3CVqBAydQdnsAoc7jJHlcbno7sY1JoBIJnso3p9vtRlL9-o4sgUAKIIBAAeQQki2JiGjTg62GSLAzC6LLZHJ2QLyBSkHBoaGYABYXgB2F4u9TFKBlCpVBobUZrPQAKyQGDgS2A2OWcA4SNoKBkDXKrg4SHaNAUqDsu32QhexbiEmk-PFcCu1VEBmkosektFMq+SnliscNYBWRydukjqJcDdnu9RVK5Uq1GYZJmPjQyyWWY6CIq7k83nI+ykpcMFcs1drhgblabr3erZ+qj+zkcqiAA)

### 💻 Code

```tsx
interface Props<T> {
  a: (x: string) => T;
  b: (arg: T) => void;
}

function Foo<T>(props: Props<T>) {
  return <div />;
}

// Works fine, T is inferred as 'number' through the return value of 'a'
<Foo
  a={() => 10}
  b={(arg) => { arg.toString(); }}
/>;

// If 'a' takes any parameters, inference stops working and T becomes 'unknown'
<Foo
  a={(x) => 10}
  b={(arg) => { arg.toString(); }} // ERROR: 'arg' is of type 'unknown'
/>;

// (since 4.7.4) Works fine if the object literal syntax is used instead
<Foo {...{
  a: (x) => 10,
  b: (arg) => { arg.toString(); },
}} />;
```

### 🙁 Actual behavior

`Foo<T>` **fails to infer** `T` from the return value of `a` if the function provided for `a` accepts any parameters, and the JSX attribute syntax is used.

### 🙂 Expected behavior

`Foo<T>` should infer `T` from the return value of `a` regardless of whether its signature has parameters, and regardless of whether the JSX attribute syntax is used or not.

**Comment by Andarist** [comment]
This is already fixed by https://github.com/microsoft/TypeScript/pull/52837 and awaits review 😉
