### ISSUE TITLE
Show better error message for unresolved references due to missing prefix

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#528]
```
module Foo {
    class X {
      public static F() {}
      public static G() { F(); }
    }
}
```
Current error is:  
> Cannot find name 'F'.

Suggestion:
> Cannot find name 'F'. Did you mean to prefix the static function invocation with the class name, 'X.F()' ?

**Comment by mhegazy** [comment]
thanks @ShyykoSerhiy!

**Comment by RyanCavanaugh** [comment]
This is awesome, no pun intended. I hope we can do more of this in the future.
