### ISSUE TITLE
`infer R extends` in template literal does not narrow correctly when extending union of literals 

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [microsoft/TypeScript#52801]
# Bug Report

### 🔎 Search Terms

template literal infer extends union narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about infer extends in template literals.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/PTAEHUHsCcGsGdQENEFMAeAHVBjALqgCYB0AsAFB4Ce2oA4qngwHarQCWOACtKgGbt0AHgDKeaKAwFmhRPHHtmAcwB8oALygxEqahmIABgBIA3or5tQmXpPTTZoeR2UBfUwHIAhO9AAfUO4A-O4uBqCBVjYAXAHuANwU1LTwkAC2qNqKShr0jCxsnDz8gkLufJCQwSpxoCCgACoAFqi22PhEoAA27ATQSJ2gSS1lFe5k5BR1AMJpmEj4ADSgAEYArnighJCo8MzuGwDuMLDjQ7l4ANLMkAfMIqt8AugAjKLitvZyCspqmtofegcxhMTiybjMzAsEngDwB+gC3j8AWCoXCjlhMXc8USNBasGut3uj0EzxyDEuBLuDyerxGlXc1VqYCaLVWzHYkGYCJ8-iCPkU8lQSEIoEgfEGzVauAIIu6vX6g1xyLGFEmYCgcHgSzWG2uG3gOH6SGWnVQpyV5KuNypxPQACY3jo7ICvs5VBoKKAtO9dPDgaDXKZzJYYeLfQ4vCEDJ60aGYzF-uHDKYA0pwcHobCk8rQjGInHyF7MdjKEr8daiU87WTGFbCdTBA66VUanUWVL2rKemwFWc+eMgA)

### 💻 Code

```ts
// Works as expected.
type GetGenericPrefix<Str extends string> = Str extends `${infer pre extends string}${'!' | '?'}` ? pre : '';
type someString = GetGenericPrefix<'foo?'>; // The expected literal type 'foo'.

// Compact, but doesn't work.
type GetKnownSuffix1<Str extends string> = Str extends `${string}${infer suf extends '!' | '?'}` ? suf : '';
type knownSuffix1 = GetKnownSuffix1<'foo?'>; // The union '!' | '?' instead of the expected literal type '?'.

// Works, but not scalable.
type GetKnownSuffix2<Str extends string> =
  Str extends `${string}${infer suf extends '!'}`
  ? suf
  : Str extends `${string}${infer suf extends '?'}`
  ? suf
  : '';
type knownSuffix2 = GetKnownSuffix2<'foo?'>; // The expected literal type '?'.
```

### 🙁 Actual behavior

Type `GetKnownSuffix1` returns the entire extended union (`'!' | '?'`) instead of the matching literal (`'?'`).

### 🙂 Expected behavior

Type `GetKnownSuffix1` should return just the matching literal (`'?'`), the same way `infer pre extends string` in `GetGenericPrefix` returns the literal type `'foo'` and not the extended type `string`.

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/issues/49839#issuecomment-1411863333

**Comment by whzx5byb** [comment]
Workaround: use distribution behavior to simplify the "not scalable" code

```ts
type GetKnownSuffix<Str extends string, Suffix extends string> = 
  (Suffix extends infer S extends string
    ? Str extends `${string}${infer R extends S}`
      ? R
      : never
    : never
  ) extends infer T ? [T] extends [never] ? '' : T : never;
    
type knownSuffix = GetKnownSuffix<'foo?', '!' | '?'>
//   ^?  "?"
type knownSuffix2 = GetKnownSuffix<'foo', '!' | '?'>
//   ^?  ""
```

**Comment by RyanCavanaugh** [comment]
This seems to be a manifestation of the same problem described at https://github.com/microsoft/TypeScript/issues/49839#issuecomment-1416418581
