### ISSUE TITLE
Function typechecking gets ignored

### ISSUE THREAD

**Issue by N1ghtSiren** [microsoft/TypeScript#52821]
### ⏯ Playground Link
**Playground Link:** [Clickable Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gWwgEQgGwgcwIbGgXigApsAuKAOwFcEAjCAJwBopbzq7GBKKfAPigA3OAEsAJgFgAUNIDGabAGdFUAIIAeACoCA3tKgGoYBnDyy8YqAwjYxcCmhBQ0IxcHKaA2gF1eUH9L6hmBUtC6yULZiJOYi9h48elKGKVDAABauAHQublkhiukxwHEUXEEGAL7S1TJS8koqAEJQEAAeeBRiKhrwSKgYOHh8SSkhYSIRIhTCANYQJOw09MysS5wMPOTC4qOpBhnZucBZAGZwDACi2LJFRILYaFQQ5H0o6Fi4EDz8UHv7KQeTwW2BYtHKyQBlQhKVqtWkpyoFFi9igACVsF1EAAxJGyIhbSjLRh-KAVKCyeyKOAYHJwTBEABE7QgsioFkZMMM1mAVAYFCgAAYyVJ4VIMMBWH4KBAAO5QJoEwJSWhZKJEDFYhC45E8AwAen1mKcoEgt1Zs2mmDS6UYEGVqumcwWAEYWAAmLhAA)

### 💻 Code
```ts
type SomeDelegate = (a: number, b: number) => void

class A<T> {
    protected readonly list: T[] = []

    public add(action: T) {
        this.list.push(action)
    }
}

class B extends A<SomeDelegate>{
    public invoke(a: number, b: number) : void{
        this.list.forEach((value: SomeDelegate) => {
            value(a, b)
        })
    }
}

function RandomFunc() : number { 
    console.log("executed")
    return 0 
}

let b = new B()

b.add(RandomFunc)   //any typechecking there

b.invoke(1, 2)
```

### 🙁 Actual behavior

Function type is fully ignored

### 🙂 Expected behavior

Error: type missmatch

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

**Comment by N1ghtSiren** [comment]
How do i make `SomeDelegate` to not ignore both `a` and `b` ?
Or any other way to get strict function checking there?

**Comment by fatcerberus** [comment]
The point is that you could just have easily have written this:

```ts
function RandomFunc(a: number, b: number) : void {
    // ignore both a and b
    console.log("executed")
}
```

So there's no reason the version in the OP shouldn't typecheck.  This is by design, as sometimes you *want* to ignore parameters, e.g. the `index` parameter of a `map` or `filter` callback, and it would be inconvenient to force every caller to declare them.
