### ISSUE TITLE
Which is the max size that typescript.js support?

### ISSUE THREAD

**Issue by danicomas** [Microsoft/TypeScript#5282]
I have tried system.js + typescript.js + angular2 with a file with more than 720 KB aprox and it doesn't works well. It works until 700 KB aprox.

**Comment by vladima** [comment]
can you please tell what exactly does not work? Right now it is a little bit vague.

**Comment by danicomas** [comment]
Sorry. If you add system.js, typescript.js, angular2.js and app.ts and you copy paste the code from app.ts inside the same file N times you will see when the file size > 710KB aprox the page scripting is executed in 700ms but with 700KB was in 3 seconds. Something wrong with >710KB. The console doesn't show errors.

**Comment by RyanCavanaugh** [comment]
Still not clear what you mean. The TypeScript compiler itself is around 4.5 MB of source and we compile in a few seconds. How are you invoking the compiler? Can you share a direct repro?

**Comment by danicomas** [comment]
@RyanCavanaugh I am in other computer and the results are very different I will check it out on Monday in the same computer. However I don't think that it is a typescript.js issue.
