### ISSUE TITLE
Truthiness narrowing does not work as expected with `&&`

### ISSUE THREAD

**Issue by Juneezee** [microsoft/TypeScript#52822]
# Bug Report

### 🔎 Search Terms

- Truthiness narrowing
- Truthiness narrowing with &&
- Truthiness narrowing with other conditional expressions
- Narrowing
- Control flow analysis

### 🕗 Version & Regression Information

Possibly related to https://github.com/microsoft/TypeScript/issues/52272

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMLCggNig3gKGWQGtQATALmQCIENsJqBuQ5ADypAFcBbAI2gsAvoXyhIsRCgDKARy5woeVqRCUaAZ3mLGLIh2Td+0ZAB9DXLFmH58YAJ4AHGQAs4z5AF409HGeRyCkos+DBcIAhgwAD2IMgwIACMABQabs5U0ukQAJTIBETAMMip2QB0qmRent7UWkGMyABkTchp7hBlbNXe3FZ5BUTICLEaYPkk5AA07MhCXm3ZyAD0yxOVVHXaStQzBkYCUHPIcBrIEGzOkRBktkPISmBcUCCsIqyryACCMBLIYC4UCM1MAorE4FhkHwoHAIi4TnxogA3CAzADuKGIIGiaP+bnGAAN2s4ugThrDDNFkFhYgBzaAfNYCZAEvpYAllO7IIolYmdSo9TTbRgDVhEYFjdbTWbzbx8lZrXCTNSbeo6XbsTi8Q7+NlzMX3Q1G42Gz4ODzRYoEthktLRSxVZms7XQMmxLD2N5ciXjEAQNEAaXICz5FWDZqcKGAZwJtF8jXMWwa1DJp3Olwg11u4tGvv9AA0Q+VukaIxaraGbYt7VhHSgQIooDibv8qc7jFA3SAPfh3mEImC4gkAEylDqZbKioifUHINHRKDEM5owFxDGGRs4vEoc0oNGglz28bRAEmYFkUHgyEXRxKDQaGIgDSsHljkndGq9SxYKdDH1StQ9mOOUlk+JUNiFZM9i1DtjjTG9M0gW4DUeZ5XiId5CmKN9+WDT9IPVX8cyfcZwOlbpZUWDoFQA9Qk3VaCLFg+Z4IzLMvVYf8-UDPCqJJAUyyjGM40wHBqH8eidlTM4EPY4jJW4wsQI6LoaN3bkYwOV1kHdewThktikN7IA)

### 💻 Code

```ts
interface Circle {
  kind: "circle";
  x: number;
}
 
interface Square {
  kind: "square";
  x: number | null;
}

type Shape = Circle | Square;

function fn1(shape: Shape) {
  if (shape.kind === "square" && shape.x === null) {
    const { kind, x } = shape // { kind: "square", x: number } as expected

    return
  }

  // After the conditional branch above, we know that `shape.x` can no longer
  // be `null`.

  if (shape.kind === "square") {
    const { kind, x } = shape // { kind: "square", x: number | null }
                              // type of `x` should be `number` only
  }

  const newKind = shape.kind // type is `"circle" | "square"` as expected
  const newX = shape.x       // type of `shape.x` should be narrowed to `number` only
}

function fn2(shape: Shape) {
  // it works when we narrow the type without other conditonal expressions
  if (shape.x === null) {
    const { kind, x } = shape // { kind: "square", x: number } as expected

    return
  }

  if (shape.kind === "square") {
    const { kind, x } = shape // { kind: "square", x: number } as expected
  }

  const newKind = shape.kind // type is `"circle" | "square"` as expected
  const newX = shape.x // type is `number` only as expected
}
```

### 🙁 Actual behavior

TypeScript fails to narrow the type of `shape.x` to `number` only in `fn1` after the first conditional branch `if (shape.kind === "square" && shape.x === null)` :confused: 

### 🙂 Expected behavior

After the first conditional branch `if (shape.kind === "square" && shape.x === null)` in `fn1`, `shape.x` can not be `null` anymore.

However, doing just `if (shape.x === null)` in `fn2` works fine

**Comment by fatcerberus** [comment]
After the first check, `shape.x` might still be `null`, if `shape.kind` is something other than `square`.  While that possibility is precluded by the second check for `shape.kind === "square", the compiler isn't capable of counterfactual reasoning like "X or Y; X is false, therefore Y".  At any given point, type narrowing either happens or it doesn't and subsequent checks can only work from there.

**Comment by RyanCavanaugh** [comment]
> the compiler isn't capable of counterfactual reasoning like "X or Y; X is false, therefore Y"

I've been trying to state this in a reasonable way for years and you finally provided a phrasing that makes sense 💖

**Comment by guilhemheinrich** [comment]
I posted a similar issue here: https://stackoverflow.com/questions/78287716/is-there-an-explanation-to-the-following-typescript-snippet-not-correctly-inferr
