### ISSUE TITLE
Rollback `tsconfig.base.json`'s target to `es5` for transformer libraries

### ISSUE THREAD

**Issue by samchon** [microsoft/TypeScript#52826]
# Suggestion
## 🔍 Search Terms

  - target
  - tsconfig.json
  - v5
  - ttypescript
  - ts-patch
  - transformer

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
Hope to keep `es5` taget build for transformer libraries.

Until v4.9, TypeScript had been built as `es5`. However, after v5 update, it has been changed from `es5` to `es2018.

https://github.com/microsoft/TypeScript/blob/ccf3d3c5f9b4bc2883d700870ed2dac454050f1f/src/tsconfig-base.json#L5

https://github.com/microsoft/TypeScript/blob/ddfec78f55bfedd690708c429f803346555e31c4/src/tsconfig-base.json#L8

I understand the reason why updating the build target, however, it may be a critically damage on transformer libraries. 

Looking at source code of transformer libraries like [ttypescript](https://github.com/cevek/ttypescript) and [ts-patch](https://github.com/nonara/ts-patch), they are supporting transform plugin through hacking TypeScript source code like below. They're utilizing and strongly dependent on characteristics of `es5` target build.

```typescript
// HACKING CODE FROM TTYPESCRIPT
fs
    .readFileSync(tscFileName, 'utf8')
    .replace(
        major >= 4 && minor >= 9
            ? /^[\s\S]+(\(function \(ts\) {\s+var StatisticType;[\s\S]+)$/
            : /^[\s\S]+(\(function \(ts\) \{\s+function countLines[\s\S]+)$/, 
        '$1'
    );

// HACKED CODE IN LIB/TSC.JS
var ts;
(function (ts) {
    var StatisticType;
    (function (StatisticType) {
        StatisticType[StatisticType["time"] = 0] = "time";
        StatisticType[StatisticType["count"] = 1] = "count";
        StatisticType[StatisticType["memory"] = 2] = "memory";
    })(StatisticType = ts.StatisticType || (ts.StatisticType = {}));
    function countLines(program) {
        var counts = getCountsMap();
        ts.forEach(program.getSourceFiles(), function (file) {
            var key = getCountKey(program, file);
            var lineCount = ts.getLineStarts(file).length;
            counts.set(key, counts.get(key) + lineCount);
        });
        return counts;
    }
```

## 💻 Use Cases
Threfore, I hope you TypeScript language developers to keep the `es5` target build. 

As you know, so many TypeScript lovers are enjoying transformeer libraries like [typescript-transform-paths](https://github.com/LeDDGroup/typescript-transform-paths). I am also developing transformer based libraries like [typia](https://github.com/samchon/typia) and [nestia](https://github.com/samchon/nestia) for many years. I do not want to lose transformer API, and do not want to give up maintaining my open source libraries, either.

Please keep the target build option as `es5`.

**Comment by samchon** [comment]
p.s) If hard to rollback the build option, is it possible support the transform plugin by TypeScript itself? - @DanielRosenwasser

**Comment by jakebailey** [comment]
The change in the output has nothing to do with the target being changed from ES5 to ES2018; the code you have above only works because TypeScript used to be authored using namespaces, which produced a series of:

```js
var ts;
(function (ts) {
  ts.something = ...
})(ts)
var ts;
(function (ts) {
  ts.somethingElse = ...
})(ts)
```

But now we're modules, which simply do not produce that code, and we further bundle the output. I don't see us reverting that change.

Any package which patches typescript is already fragile, because any aspect of our output could change. This change is just one potential way that this could have broken.

Those who have to patch typescript will likely have better luck:

- Finding another way to do it, i.e. use our API.
- Take the approach used by yarn and fork this repo, producing patches from the two outputs.
- Take the approach used by prettier (in an upcoming version and the patching code into some other potentially fragile code.

**Comment by samchon** [comment]
@jakebailey Thanks for fast replying. I just hope `ttypescript` and `ts-patch` to support TS 5.0 following your guide.

**Comment by samchon** [comment]
@jakebailey Thanks for fast replying. I just hope `ttypescript` and `ts-patch` to support TS 5.0 following your guide.

This question is by just my curiosity. Is there any reason that TypeScript is not supporting transform plugin by itself?

**Comment by jakebailey** [comment]
See #14419 and #16607.

**Comment by samchon** [comment]
As a developer of [typia](https://github.com/samchon/typia) and [nestia](https://github.com/samchon/nestia) utilizing transformation, whenever there is a critical patch for the TS compiler API, the libraries break and stress me out. 

Quietly vote yes and go.

**Comment by nonara** [comment]
@samchon Jake is correct. This issue can be closed. 

`ts-patch` will continue to support TS5+; however, I have been holding off until we were closer to the release date due to being personally backlogged and to avoid having to redo work while there are still moving parts.
