### ISSUE TITLE
Index Signature Parameter of type symbol

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#5283]
It would seem like the following should be valid:

```typescript
interface A {
  [a: symbol]: any;
}

interface B {
  [a: symbol | string]: any;
}
```

But it errors with `An index signature parameter type must be 'string' or 'number'`.

**Comment by mhegazy** [comment]
Symbol indexers was not added along with other symbol support. here is the issue tracking adding it: #1863
