### ISSUE TITLE
The type of the function cannot be inferred.

### ISSUE THREAD

**Issue by MauroTaliente** [microsoft/TypeScript#52830]
# Bug Report

Writing a tailwindcss inspired library but for jss I found myself needing to infer many types.
 I am trying to infer the return value of a function whose parameter is known.

### 💻 Code

```ts
// THEME EXTENDS
// user provide =>
const theme = {
  name: 'theme',
  colors: {
    acent: '#9D84B8',
    primary: '#FFFFFD',
    secondary: '#A8A7AC',
  },
  fontFamily: {
    display: 'Unbounded',
  },
};

const extended = {
  extra: (current: any) => [current.colors, { unique: 'blue' }], // ideal
  titip: <T extends BaseTheme>(current: T) => [current.colors, { unique: 'blue' }] as const, // test
  other: () => [{ unique: 'pink' }], // test
};

// lib logic =>
type BaseTheme = {
  name: any;
  colors: any;
  fontFamily: any;
};

type Theme<T> = T extends BaseTheme
  ? {
      name: T['name'];
      colors: T['colors'];
      fontFamily: T['fontFamily'];
    }
  : never;

type Hook = <T>(theme: Theme<T>) => (T[keyof T] | { [K: string]: string } )[];
type BaseExtended = object | Hook | readonly any[] | unknown;
type Extended<T> =  T extends BaseExtended ? T : never;

type Build<T extends BaseTheme, A extends BaseExtended> = A extends (current: T) => infer R
  ? R
  : A extends object
  ? { [K in keyof A]: Build<T, A[K]> }
  : A;

const build = <T, A>(theme: T, ext: A) => {
  type G = Theme<T>;
  type J = Extended<A>;
  let go = {} as any;
  if (typeof ext === 'object') {
    for (const key in ext) {
      go[key] = build(theme, ext[key]);
    }
  } else if (typeof ext === 'function') {
    go = ext(theme);
  } else {
    go = ext;
  }
  return go as Build<G, J>;
};

const example = build(theme, extended);
console.log(example.extra); // expected type => [ { acent: string, primary: string, secondary: string }, { unique: string } ];
```

### 🙁 Actual behavior
(property) extra: any[]

### 🙂 Expected behavior
(property) extra:  [ { acent: string, primary: string, secondary: string }, { unique: string } ]

Both the parameter current('theme') and the object { unique: string } are declared however the return of the "extra" function cannot be inferred

**Comment by RyanCavanaugh** [comment]
Please provide a reduced example; if there's a bug here it should be clearly demonstrable with a sample small enough to readily observe the defect.

**Comment by MauroTaliente** [comment]
@RyanCavanaugh  
Sorry for not being entirely clear with the example.
I think I managed to isolate the main cause of my problem here:

```ts
const theme = {
  colors: {
    acent: '#9D84B8',
    primary: '#FFFFFD',
  },
};

type BaseTheme = {
  colors: { [K: string]: string };
};

const funA = <T extends BaseTheme['colors']>(colors: T) => [colors, { unique: 'blue' }];
const resA = funA(theme.colors); // OK

const funB = <T extends BaseTheme>(theme: T) => [theme.colors, { unique: 'blue' }];
const resB = funB(theme); // Missing dynamic type
```

**Comment by RyanCavanaugh** [comment]
That's a correct inference. You have two entries in the array, both of which can be correctly described as `{ [K: string]: string }`

**Comment by MauroTaliente** [comment]
el comportamiento que espero es que el tipo de funB coincida con el  tipo de funA.

**Comment by RyanCavanaugh** [comment]
They're different calls; having different types as a result of the input types being different is not a bug.

**Comment by MauroTaliente** [comment]
Is there a way to do deep extends, or something similar for those cases where you want to infer each property within the object that is sent as a parameter?

**Comment by RyanCavanaugh** [comment]
In this example, you could write
```ts
const funB = <T extends BaseTheme>(theme: T) => [theme.colors, { unique: 'blue' }] as const;
```
or
```ts
const funB = <T extends BaseTheme>(theme: T): [T['colors'], { unique: string}] => [theme.colors, { unique: 'blue' }];
```
depending on what you're going for

**Comment by MauroTaliente** [comment]
382 / 5.000
Resultados de traducción
Resultado de traducción
thanks for the time.
The simplest solution I found is this;
```ts
const funB = <T>(theme: { colors: T }) => [theme.colors, { unique: 'blue' }];
const resB = funB(theme);
```
where I have to create a generic type for each property that I want to infer. I think this way will allow me to type the functions after the user of the library defines them even with theme: any.
