### ISSUE TITLE
Types for Response.json() Static Method

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript#52841]
# Suggestion

## 🔍 Search Terms

response, responses, static method, json, `Response.json()`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Now that multiple JavaScript runtimes (Chromium, Node.js v18 LTS, Bun, etc) have implemented it, it would be great to get types for [the `Response.json()` static method](https://github.com/whatwg/fetch/issues/1389) ([Chrome Platform Status](https://chromestatus.com/feature/5197912798658560), [Mozilla Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1758943), [`Response.json()` section in Fetch spec](https://fetch.spec.whatwg.org/#ref-for-dom-response-json)).

Since `Response` objects are more commonly used on the backend, maybe backend runtimes can be considered as valid signals that this is ready for inclusion in TypeScript.

## 📃 Motivating Example

```ts
Response.json({abc: 123}, {status: 400});
```

[Playground](https://www.typescriptlang.org/play?#code/EoUwzgDg9gdmIDoBWZYAoDeBDARgYwC4ACARgCYBmAXwBoiMwAXLRgVzGIBYAGbqgSgDcQA)

![Screenshot 2023-02-18 at 15 33 32](https://user-images.githubusercontent.com/1935696/219871450-616b7b73-7574-4a44-b636-4b11e1b1edb5.png)

## 💻 Use Cases

A shortcut for the following code (more verbose / error prone):

```ts
new Response(JSON.stringify({ abc: 123 }), {
  status: 400,
  headers: {
    'Content-Type': 'application/json',
  },
});
```

## 👀 See also

This has a companion issue + PR in the `microsoft/TypeScript-DOM-lib-generator` repo over here:

- https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1444
- https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1462

cc @lucacasonato @balazsorban44 @leerob @cramforce @jasnell

**Comment by balazsorban44** [comment]
Just pointing out that the shortcut is in fact so error prone, that you forgot to add the `"Content-Type": "application/json"` header.  😜

This would be a great addition! 👍

**Comment by lucacasonato** [comment]
> Just pointing out that the shortcut is in fact so error prone, that you forgot to add the "Content-Type": "application/json" header. 😜

`Response.json` automatically sets the content type header to json.

**Comment by karlhorky** [comment]
> you forgot to add the `"Content-Type": "application/json"` header. 😜

haha indeed oops, added!

**Comment by lucacasonato** [comment]
No, the header is added by `Response.json` already. The previous example was correct 😃

**Comment by cramforce** [comment]
@lucacasonato the comment was about the long-form non-helper version which was originally missing it. Was important to add to show that the helper does more work!

**Comment by karlhorky** [comment]
Oh nice, it looks like https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1462 was merged! 🙌

@RyanCavanaugh does this mean that this issue can be closed now? (will this be a part of TypeScript in one of the next versions like 5.2?)

**Comment by RyanCavanaugh** [comment]
This would be in 5.2 as soon as we do the next regular lib update, yes. Marking closed. Thanks!

**Comment by karlhorky** [comment]
Great, thanks!

**Comment by TemoSulava** [comment]
I don't know if i am doing something wrong, but, i am running ts version 5.2.2 and i still can't use Response.json
![image](https://github.com/microsoft/TypeScript/assets/72650579/77ea14df-a343-4e11-9d1a-472765c6ac99)

**Comment by RyanCavanaugh** [comment]
Please file a new issue. No screenshots please.
