### ISSUE TITLE
Unnamed generic type parameters

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#52855]
# Suggestion

## 🔍 Search Terms

generic, covariance, variance, assignable, constraint, instantiated, subtype, unrelated, strictFunctionTypes

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I just realized that I had never enabled `strictFunctionTypes` and once I decided to enable it for better type safety, I had a lot of trouble migrating existing code.

We have a lot of non-elementary generics. By "non-elementary" I mean generic that `extends` another type with generics. Before enabling `strictFunctionTypes`, things were not beautiful but still working. But with `strictFunctionTypes`, things become troublesome.

The simplest way I can think of is to use `any` for the nested generics:

```ts
interface Foo<
  TBar extends Bar<any>
> {}
```

I believe that's not optimal. But I do not want to add an extra generic for `Foo` as that doesn't give the user any benefit. So I am thinking about adding unnamed `generic` type:

```ts
interface Foo<
  TBar extends Bar<generic>
> {}
```

---

Example ([Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJygHgCoGUEAWEAtnMhAB6QgAmAzsgPYBGAVhAmAHzIDeAUMmQJGIOgFdiEAFzIAFHUIk4svEtIBKZAF4eAN0bAaAbn4Bffv1CRYiFAEEA7hDqMp+IqT6DkcZ66lZMChxCFMLK3BoeCRkJxc3CHQocioIWgZkzHiAiA9lHl4I62i7ZAAxRkZMHzVPMkpqeiY2DjB+QoiwAE8ABwd-RMrGHQqq7MH3dTguU0ibGJRhgCYaoWxk1KbMjEwWdk4eAHoj5EwAWmRHRigAawZHYDACRnEwZDpg4E5y8RBOYCibB9FwAOg6fC6ILikwgK1GKwmCSkyVm-BOQkxWOxOKEAD8CYSiZYSrZYsMAMxrZAbDBbdLNLJwEDdY6nC5XG73ZDMN7IcQAcwANt1wZ1LD1+jDkXCqhSEXKkblUaYgA)):

```ts
interface Bar<TSchema extends object> {
  consume: (schema: TSchema) => void;
}

interface AwesomeSchema {
  awesome: true;
}

interface AwesomeBar extends Bar<AwesomeSchema> {}

interface Foo<
  TSchema extends object
> {}

type AwesomeFoo = Foo<AwesomeSchema>;

interface Foo2<
  TBar extends Bar<object> // <- works without strictFunctionTypes.
> {}

type AwesomeFoo2 = Foo2<AwesomeBar>;
//                      ~~~~~~~~~~

interface Foo3<
  TBar extends Bar<any> // <- works but ugly.
> {}

type AwesomeFoo3 = Foo3<AwesomeBar>;
```

**Comment by RyanCavanaugh** [comment]
This just seems like spinning up the euphemism treadmill, unless you had some concretely different behavior in mind here. People are allergic to saying `any`, so introduce a new keyword that behaves like `any`, and people will eventually become allergic to that keyword and request a new one.

For a generic type that isn't invariant, `unknown` or `never` (depending on variance) work equally well here.

**Comment by vilic** [comment]
@RyanCavanaugh Thanks for the suggestion anyway. Actually, I am neither a fan of introducing another keyword, just providing a use case and some ideas popped out.

However, as you suggested using `unknown` or `never` for non-invariant cases, you must have noticed that there might not be a way to achieve that for invariant cases without `any`. I wouldn't mind a workaround without changing the usage of the type if there is a future generic parameter feature that could magically achieve the same goal.

**Comment by fatcerberus** [comment]
Yeah, `any` is usually too permissive so there's currently no variance-agnostic and typesafe way to ask for a top type of an arbitrary generic.  I've often daydreamed about having something like `Foo<?>` myself.  That does skirt dangerously close to the can of worms that is existential types, though.
