### ISSUE TITLE
Labeled variadic tuples should not require labeling spreads for tuples that are already labeled

### ISSUE THREAD

**Issue by btoo** [microsoft/TypeScript#52853]
# Suggestion

## 🔍 Search Terms

variadic tuples name label element named labeled tuple elements

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Variadic tuples will inherit the labels of the tuples they're spreading

```typescript
type LabeledTuple = [first: string, second: number]

type VariadicTuplesCanInheritLabels = [...LabeledTuple]
//  ^? type VariadicTuplesCanInheritLabels = [first: string, second: number]
```

However, once a variadic tuple adds unlabeled elements, the variadic tuple loses the spread tuples' labels and compilation fails

```typescript
type VariadicTuplesWithoutLabelingALabeledTuple = [...LabeledTuple, third: boolean]
//  ERROR: Tuple members must all have names or all not have names. (5084)
```

As a workaround, we can label the spread, but this label never gets used. Even worse (and potentially a bug), this label's type is inferred as `any`

```typescript
/** `unusedLabel`'s type is incorrectly inferred as `any` */
type VariadicTupleWithUnusedLabel = [...unusedLabel: LabeledTuple, third: boolean]
//  ^? type VariadicTupleWithUnusedLabel = [first: string, second: number, third: boolean]
```

Following up on https://github.com/microsoft/TypeScript/issues/39941#issuecomment-778868736, a better DX might be to _not_ require that `Tuple members must all have names` if the spread elements are already labeled, which would be consistent with the fact that variadic tuples already inherit the labels of their spreads.

## 📃 Motivating Example

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAMghgIwgGwgEwCoFcyqgXigG0AzASwCcBnYALihorIDsBzAGgYgGMB7ZtPWZYAtkgoBdAFBTQkKADU4TOGjLdsuCFQDCcZgElmACwhNg8JMioFiAOgeWU6TamkB6d1CgA9APwy7gBUQVBYzCS8FMDhcMAoIJz83NBwUABuymSq6lAxWlDIiCg2ZMA2vADuzFDOIhDMwJxlhbxU2nmmDGAUEKp5OKgA5DZFVlAspub6KVBB7rLg0EoqahqD2gDqZca8WBbFyCysAIJOqJgbtkQOducuG5zAxpSCUAi8vKj6Hl6+AVJgkEpHM8rwoOQAB6dMhUTiVaDMCDoMGFQ6daBUHp9NADLTsEGhBD7GGjdGwqC9NDhND6YBQAAU+lxYDaVDICGQICgaWJrD8UAABuEsO00OdBSM8ksJqVmHwKL1uMAuRMImYqTybIL9CBBQBKQkLOTLLI5dZabbPACqwjF52utxF9sO9Hul3xMIobw+Xz6zF+3n8UiAA)

## 💻 Use Cases

Not having to redundantly label variadic tuple spreads

**Comment by RyanCavanaugh** [comment]
Discussed and we're OK removing this restriction for all tuple elements. However, #53011 would need to be fixed first, otherwise we might break currently-working declaration emit

**Comment by JoshuaKGoldberg** [comment]
> removing this restriction for all tuple elements

@RyanCavanaugh just to be clear, are you suggesting that the _Tuple members must all have names or all not have names_ restriction is clear to be removed altogether?

**Comment by RyanCavanaugh** [comment]
Yeah, though we should make the declaration emitter more resilient to this. Sample:
```ts
function fn() {
    type M = [a: string, number];

    return f;

    function f(...args: M) { }
}
```
I think we want the function type in the `.d.ts` to be something like `(a: string, arg_1: number) => void`
