### ISSUE TITLE
Union and Intersections of Interfaces are Inconsistent

### ISSUE THREAD

**Issue by joshuaharry** [microsoft/TypeScript#52856]
# Bug Report
The type checker seems to display inconsistent behavior when faced with the intersection of one interface and the union of two separate interfaces.

### 🔎 Search Terms
Intersection types, type soundness

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries

### ⏯ Playground Link
https://www.typescriptlang.org/play?ssl=25&ssc=84&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgBJwM4Dk4FsUDeAUMsiHhAFzIZhSgDmA3EQL5FGiSyIroYBBBoRLI4w6iACuuAEbQW7TuGjwkaTOmBQAwgHsANnqjJipABZxt+o1Gq16IZmw5gAngAcUABWgY9IMgAvBrYFMgAZMgAFPxCKAA+oVq6hsYAlCxECAG0yABWehjm1L5Q-oEhZmQU1ADkAFJF5nUANKLiVMgATACs7RZWqbb1slB6AO4gbS6cMDF1nXXIoAXN6aaiOSD+BhAAdEYM0YXF+5bWaVCZswD0t8gAMqAoAIy9NOZ6UgYAJmR6MDIdxeZAIcwQBAAa1ayAgGC8CGAcAMBjcYNywF+0EYwIhwM8KGg4xMAWQBhePW6+yAA

### 💻 Code
```
interface HasName {
  name: string;
}

interface HasAge {
  age: number;
}

interface HasHairColor {
  hairColor: string;
}

type Person = HasName & (HasAge | HasHairColor);

const josh: Person = {
  name: 'Josh',
  age: 25,
  hairColor: 'brown',
}

if ('age' in josh) {
  console.log(josh.hairColor);
}

// Line 15 should not type check, especially considering the type error on line 22.
```

### 🙁 Actual behavior
Line 15 passes the type checker.

### 🙂 Expected behavior
Line 15 should not pass the type checker.

**Comment by fatcerberus** [comment]
I’m not sure why you expect a type error on L15.  Any given `Person` is not guaranteed to have both an `age` and a `hairColor` (hence the error on L22), but `HasAge | HasHairColor` is also not mutually exclusive.

**Comment by joshuaharry** [comment]
Ah, thank you! Apologies, I misunderstood the semantics. Closing.

**Comment by fatcerberus** [comment]
@joshuaharry If you want mutually exclusive types, the closest you can get is probably to use a [discriminated union](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions), though it may not be perfect, because types still allow extra properties.  Anything stricter requires exact types (https://github.com/microsoft/TypeScript/issues/12936).
