### ISSUE TITLE
"Move to a new file" refactoring does not maintain "import type" semantics

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/TypeScript#52852]
# Bug Report

### 🔎 Search Terms

"Move to a new file"

### 🕗 Version & Regression Information

@andrewbranch told me it was a bug and I believe him!

https://twitter.com/atcb/status/1627351253742399490

### ⏯ Playground Link

N/A

### 💻 Code

N/A

### 🙁 Actual behavior

Here we're refactoring in VS Code.  Moving to a new file - see how before we have `import type` semantics?

![image](https://user-images.githubusercontent.com/1010525/219967079-4e49a94b-45b3-407e-bb5d-7aa412c91c77.png)

Oh no!  Post refactoring they're gone!

![image](https://user-images.githubusercontent.com/1010525/219967100-46f9bc7a-a3c0-4cf8-ae17-bd36bb816c76.png)

### 🙂 Expected behavior

Imagine it was this instead:

![image](https://user-images.githubusercontent.com/1010525/219967079-4e49a94b-45b3-407e-bb5d-7aa412c91c77.png)

See how we've got `import type` here and not just `import`?

![image](https://user-images.githubusercontent.com/1010525/219967121-feef2d15-188b-459c-9803-621466bd9965.png)

That's the issue; ideally `import type` would be maintained across the refactoring.

**Comment by DanielRosenwasser** [comment]
Props to @a-tarasyuk for sending a fix in less than an hour and a half after this bug was filed 😄

**Comment by johnnyreilly** [comment]
Thanks @a-tarasyuk !

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser I need to ask the electricity supplier to increase the blackout time, then the productivity will improve even more 😄
