### ISSUE TITLE
share class constructor documentations in others files

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/TypeScript#52857]
# Suggestion

share class constructor documentations in others files

## 🔍 Search Terms
jsdoc share classes

if i mouse hover a ->imported<- class (alias), i cant get documentation when mouse hover!
![image](https://user-images.githubusercontent.com/24865815/219973642-51084efc-3e70-4b3f-98de-ae6b23135abb.png)

it work only if we are in same file !
![image](https://user-images.githubusercontent.com/24865815/219973651-1cfc5b3e-81b1-4569-ae09-55b6024df0f7.png)

It there a options or features to share documentations on imported class ?

**Comment by RyanCavanaugh** [comment]
Sorry, we can't work with posts with screenshots of text unless the text is also present.
