### ISSUE TITLE
Pipe character rendered when using TSDoc @link with url and custom link text

### ISSUE THREAD

**Issue by nero120** [microsoft/TypeScript#52868]
*TS Template added by @mjbvz*

**TypeScript Version**: 5.0.1

**Search Terms**
- quickinfo
- JSDoc
- `@link`

---

Currently VSCode renders the pipe character (`|`) as part of the link in a TSDoc comment when using an @link tag with a url and custom link text. Note that this is not an issue when using an @link tag with an internal reference, only with a url.

Expected:
![image](https://user-images.githubusercontent.com/4236238/219614688-b2289012-d11b-4a63-966a-31371c4f5914.png)

Actual:
![image](https://user-images.githubusercontent.com/4236238/219614742-c4e55922-71a8-45a4-ae0e-3c0afd5cf752.png)

Code:
```
/**
 * A nominal type that we use to links objects together in a way stronger than primitive types will
 *
 * @remarks
 * Found this convention {@link https://michalzalecki.com/nominal-typing-in-typescript/ | here}
 */
type NominalUID = string & { readonly __uid: unique symbol }
```

**Comment by RyanCavanaugh** [comment]
I'm not seeing this

![image](https://user-images.githubusercontent.com/6685088/221031827-dccad062-2dfa-4977-b2d2-a61358fa0d86.png)

Can you try using the "TypeScript nightly" extension to see if that resolves it?

**Comment by nero120** [comment]
Thanks @RyanCavanaugh, yes when I using Typescript v5.1.0 it does indeed resolve the issue!
