### ISSUE TITLE
Possible bug with undefined narrowing via type guards with conditions

### ISSUE THREAD

**Issue by ngouy** [microsoft/TypeScript#52877]
# Bug Report

### 🔎 Search Terms

Typeguard narrowing undefined conditions

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type guards

### ⏯ Playground Link

```ts repro
// Welcome to the TypeScript Playground, this is a website
// which gives you a chance to write, share and learn TypeScript.

// You could think of it in three ways:
//
//  - A location to learn TypeScript where nothing can break
//  - A place to experiment with TypeScript syntax, and share the URLs with others
//  - A sandbox to experiment with different compiler features of TypeScript

type rankedObject = {
    rank: number | undefined
}

const foo: rankedObject[] = [
    {rank: 1}, {rank: 4}, {rank: -1}, {rank: undefined}
]

const sortRanks = (element1: rankedObject, element2: rankedObject) => {
    if (element1.rank !== element2.rank) {
        if(element1.rank && !element2.rank) return -1;
        if(!element1.rank && element2.rank) return 1;
        // error here saying: element1|2 is possibily undefined
        return element1.rank - element2.rank;
    }
}

// To learn more about the language, click above in "Examples" or "What's New".
// Otherwise, get started by removing these comments and the world is your playground.
  
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBVDtUBkMzxSDcADy0gAVpBYDQALygADeihKJWpCXy-XYiGk31AAB9QFxuJBkhk6YoAL7BBCcQQ0ZLweBCgW0hnM1moADaAF1QJzjby+Vy9UKAIxK-i2mlCgAsTu5drKjud3plcoV3BVptVjQ1V3gZFQjxpwk5AAoYJBofbdTS6YyWWz+MnoQAmdMJTOGtkASgtAD5udaSgjQEn3KmAnrQABCdmcvMo1D5ls0is8vnDkTJRspnv2-sJUAAMln7e72z7eorTlQ+K8pXtAG5ayOEQm20vUFPW-PwU2eyuB1TIBuyF5d-vhypvmxsb0UIC8MMhSf7QlfMRGEAh4EEORpExPBpR4QNOEVEc+XXTdLwnbYzxpWYTxvBI92HFUVWKHBmg8R9QEQKNnGBdgaC+NwzGYdgGGYSB+FgaB1ESBhgT0EQvAAIgAUVWBhEAWfQBKSbEBPABxUAAcmEAA5SAJAEoIVHpL4yHeQQ2K0e8rlQRwFFcaQYKcSidGGLB9BQBBEGhYRLnoiQo2iEDQEMfF5kYFg2BlIISiAA)

### 💻 Code

```ts
type rankedObject = {
    rank: number | undefined
}

const foo: rankedObject[] = [
    {rank: 1}, {rank: 4}, {rank: -1}, {rank: undefined}
]

const sortRanks = (element1: rankedObject, element2: rankedObject) => {
    if (element1.rank !== element2.rank) {
        if(element1.rank && !element2.rank) return -1;
        if(!element1.rank && element2.rank) return 1;
        // error here saying: element1|2 is possibily undefined, which is not possible
        return element1.rank - element2.rank;
    }
}
```

### 🙁 Actual behavior

I have an error saying element1.rank and element2.rank could  be undefined
Which is not possible given:
1 - they are not the same
2 - we rulled out (!A && B) and (A && !B)
so the only possibility that left is that A and B are both not undefined

### 🙂 Expected behavior

no error, given rank are both defined at this point

**Comment by fatcerberus** [comment]
That this doesn’t work falls under the same reasoning as https://github.com/microsoft/TypeScript/issues/52822#issuecomment-1434063410.  `tsc` is not a proof solver.

**Comment by ngouy** [comment]
My bad
Anyway I kida forgot that the ! was ruling out not only undefined stuff, but also falsy stuff
Sorry

**Comment by ngouy** [comment]
Thank you for your help @MartinJohns and @fatcerberus
