### ISSUE TITLE
Watch mode: `git diff` on macOS triggers rebuild

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#52876]
# Bug Report

### 🔎 Search Terms

- watch

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [configuring watch](https://www.typescriptlang.org/docs/handbook/configuring-watch.html)

### ⏯ Playground Link

N/A

### 💻 Code

Steps to reproduce:

1. In a Git repository with the following files: `main.ts` and `tsconfig.json`:
   ```json
   {
     "files": ["./main.ts"]
   }
   ```
2. Modify `main.ts` so Git has unstaged changes and then run:
   ```console
   $ tsc --project tsconfig.json --watch --diagnostics
   ```
3. Finally, run `git diff`.

### 🙁 Actual behavior

`tsc` rebuilds because `git diff` bumps the access timestamp (see `stat -x main.ts`).

This is particularly problematic for me because I use [`lazygit`](https://github.com/jesseduffield/lazygit) which refreshes the Git diff every few seconds.

https://user-images.githubusercontent.com/921609/220190714-de196ad4-baa9-4917-8afc-b4963682ddd5.mov

--

Output from `tsc`:

```
FileWatcher:: Triggered with /Users/oliverash/Development/temp/lazygit-refresh-tsc/main.ts 1:: WatchInfo: /Users/oliverash/Development/temp/lazygit-refresh-tsc/main.ts 250 undefined Source file
Scheduling update
Elapsed:: 0ms FileWatcher:: Triggered with /Users/oliverash/Development/temp/lazygit-refresh-tsc/main.ts 1:: WatchInfo: /Users/oliverash/Development/temp/lazygit-refresh-tsc/main.ts 250 undefined Source file
Synchronizing program
```

### 🙂 Expected behavior

`tsc` should not rebuild when the _access_ timestamp changes.

I suspect this is due to the behaviour of `fs.watch`. In that case, is there anything else we can do to improve the default behaviour for macOS users? (Assuming this issue only occurs on macOS because I haven't been able to test on other platforms.)

Note I am able to workaround by setting any of the following variables in my shell RC file:

```sh
export TSC_WATCHFILE=DynamicPriorityPolling
export TSC_WATCHFILE=PriorityPollingInterval
export TSC_WATCHFILE=UseFsEvents
export TSC_WATCHFILE=UseFsEventsOnParentDirectory
export TSC_NONPOLLING_WATCHER=true
```

**Comment by jakebailey** [comment]
#52535 feels related, if Windows suffers from the same problem with the new watching (though that example is `node_modules`).

**Comment by FDIM** [comment]
There is something odd going on with watching after update to typescript 4.9.5 from 4.8.4. VScode became barely usable (due to tsserver being used in multiple extensions) and after some debugging I managed to track down that it is file system changes that causes tsc to recompile/update.

More specifically it is `fs.watch` emitting a change event in `node_modules/**/package.json` when `tsc` runs. Why that happens I have no idea.

Coincidently I was working on a little related feature in the project, and just for fun added `fsPromises.watch('./node_modules/htmlparser2/package.json')` and got quite surprised that I started getting events when tsserver inside vscode extension was running!

Now solution was to add this in the config:
````
    "watchOptions": {
        "watchFile": "dynamicPriorityPolling",
        "excludeDirectories": ["**/node_modules", "**/.angular", "**/.git"],
    },
```

Let me know if I can debug something more specifically. I'm experiencing this issue on Windows 10 and Node 16/18.

Now I only have to figure why lint takes 18min instead of 4min.

**Comment by Codex-** [comment]
I can confirm this behaviour too, unfortunately, thanks for raising this already

**Comment by llllvvuu** [comment]
> tsc rebuilds because git diff bumps the access timestamp (see stat -x main.ts).

`git diff` doesn't bump the Modify timestamp so maybe that would be the right thing to use

**Comment by llllvvuu** [comment]
Actually, part of the culprit in my instance is `--pretty`. Removing that fixes it for some reason, although the output is still pretty :thinking:

**Comment by evelant** [comment]
Thanks for raising this issue, it was driving me crazy and it's nice to finally know the cause. It was driving me crazy, if I tried to use watch I'd get seemingly random rebuilds and ~4 rebuilds on every change. 

This can get triggered by so many things. Even default vscode git integration refreshing its list of changed files causes the watcher to recompile. Or using the `starship` shell prompt that indicates git status, every command entered into a terminal will cause a recompile.

**Comment by sheetalkamat** [comment]
@OliverJAsh can you please try out https://github.com/microsoft/TypeScript/pull/56403#issuecomment-1811602526 to see if that helps

**Comment by OliverJAsh** [comment]
I just gave it a go and unfortunately I'm getting an out of memory error.

For reference I'm coming from v5.2.2.

**Comment by OliverJAsh** [comment]
I just tested this in my reduced test case and it does seem to fix the problem.
