### ISSUE TITLE
Better typings for AsyncIterableIterator

### ISSUE THREAD

**Issue by llucasll** [microsoft/TypeScript#52888]
# lib Update Request

Fixed in #52887

## Configuration Check

My compilation *target* is `ES2018` and my *lib* is `esnext`.

## Missing / Incorrect Definition

`AsyncIterableIterator` interface is missing `TReturn` and `TNext` optional type parameters to pass to `AsyncIterator`

## Sample Code

```ts
async function * AsyncIterableWithAllTypeParams(): AsyncIterableIterator<number, string, boolean> {
    const bool: boolean = yield 3;
    
    return 'abc';
}
```

**Comment by llucasll** [comment]
I tried to do the same improvement on the IterableIterator interface, but unfortunately I ran into a conformance error that I couldn't fix.

The code can be found in:
https://github.com/llucasll/TypeScript/tree/IterableIterator

**Comment by rbuckton** [comment]
Closing this, per the above recommendation.
