### ISSUE TITLE
Extend Conditional Logic of `in` operator from 4.9

### ISSUE THREAD

**Issue by chukwumaokere** [microsoft/TypeScript#52894]
# Suggestion

## 🔍 Search Terms

`else`, `in`, `TypeScript in operator`, `4.9`, `property narrowing`,

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

With the latest `in` operator in 4.9, [we can determine the type of an object based on `if` a property from an interface or type is `in` the object](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/#unlisted-property-narrowing-with-the-in-operator). 

But conditional `else` doesn't really work here, it just assumes the original Union from the argument still: 

I would like to see it automatically infer the resulting type based on the conditional statement i.e, if we're in the `else` block, the resulting object can only have a smaller subset of the original Types given in the argument. 
## 📃 Motivating Example

TS Playground Link to example: https://tsplay.dev/infer-type-from-leftover-union
```tsx
import React from 'react';

interface ButtonOrLinkProps {
    className: string;
    children: React.ReactNode;
}

interface Button extends ButtonOrLinkProps {
    onClick: () => void;
}

interface Link extends ButtonOrLinkProps {
    href: string;
}

// This is a utility component that decides if a button or anchor link should be rendered based on the props passed to it.
function ButtonOrLink (props: Button | Link) {
    if ('href' in props) {
        // `props` now has type Link. This is great
        return <a href={props.href} className={props.className}>
            {props.children}
        </a>;
    } else {
        // However, `props` should have type Button here since the union operator had 2 type args. 
        // The only other type possible in this else condition is "Button" 
        // Or if it has 3 or more, in which case TS should infer that the type must be "Button | SomeOtherType" as the type for this resulting object
        return <button className={props.className} onClick={props.onClick}>
            {props.children}
        </button>;
    }
};
```

Example of Error
![example of error](https://user-images.githubusercontent.com/16673873/220335369-508b3d3e-a80b-4c36-a98c-927e893e5bb5.png)

## 💻 Use Cases

I use it for determining which component to render in React, but it can be used for a large set of conditionals. 
If we're doing chained else ifs to check against an argument that can have 2+ types, allowing else to catch the remaining types would allow us to write slightly less code. 

We could just catch every possible `if` condition exhaustively, i.e., my code above would just change to 
```tsx
...
// This is a utility component that decides if a button or anchor link should be rendered based on the props passed to it.
function ButtonOrLink (props: Button | Link) {
    if ('href' in props) {
        // `props` now has type Link. This is great
        return <a href={props.href} className={props.className}>
            {props.children}
        </a>;
    }
     if ('onClick' in props) {
        // This works per the example provided in the patch notes for 4.9 but it can be simplifed.
        // The only other type possible in this condition could be "Button", so why not let `else` cover it?  
        // Or if it has 3 or more, in which case TS should infer that the type must be "Button | SomeOtherType" as the type for this resulting object
        return <button className={props.className} onClick={props.onClick}>
            {props.children}
        </button>;
    }
};
```
But when I was testing out TS 4.9, I intuitively used the `else` condition here (because this component can only be one of two things, but I could make a fallback class to render something like "MISSING PROPS" so my engineers don't miss out on a prop when creating a new component), and it would be nice if TS could infer the type on this kind of conditional logic

**Comment by fatcerberus** [comment]
For what it's worth, the type narrowing you describe (e.g. from `Button | Link` to `Link`) already existed prior to 4.9 - what's new in 4.9 is the ability to check for the properties that *don't* exist on the type.

**Comment by RyanCavanaugh** [comment]
The provided example and the linked example don't match. The provided example works as you expected. The linked example correctly, IMO, raises an error, because you write
```
    if ('href' in props && props.href !== undefined) {
```
CFA doesn't assume you wrote code for no reason, so the `props.href !== undefined` check means that you thought it was possible that `href` was undefined, so you might enter the `else` clause with a `Link`

**Comment by chukwumaokere** [comment]
Huh, you're right. That is odd... My IDE threw an error on the line which is why I tried adding `&& props.href !== undefined` because I had an issue implementing a button.
For instance: you have a Login button that can either fire an onClick event or can route to a URL for auth. The reason for these 2 actions is because one auth is google, the other is some in-house oAuth flow:

So you have this component that will render a LoginButton with some styling and under-the-hood uses the `ButtonOrLink` component which is using the Union and `in` operator

```tsx
import React from 'react';
import ButtonOrLink from '@/components/ButtonOrLink';

function LoginButton ({href, onClick, icon, iconAlt, colorClasses, children}: 
{href?: string, onClick?: () => void, icon: string, iconAlt: string, colorClasses?: string, children: React.ReactNode}) {
    const buttonClasses = "...";
    const imgClasses = "...";
    const spanClasses = "...";
    return (
        <ButtonOrLink onClick={onClick} href={href} className={buttonClasses}>
            <img className={imgClasses} src={icon} alt={iconAlt} />
            <span className={spanClasses}>{children}</span>
        </ButtonOrLink>
    );
}
```

The IDE is a bit upset that href can be undefined:
```
(property) Link.href: string
Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2322)
```
So when we make the props `href`/`onClick` optional in the ButtonOrLinkProps
```tsx
interface ButtonOrLinkProps {
    className: string;
    children: React.ReactNode;
}

interface Button extends ButtonOrLinkProps {
    onClick?: () => any;
}

interface Link extends ButtonOrLinkProps {
    href?: string;
}
```
thats when you trigger the TS error: 
```
Property 'onClick' does not exist on type 'Button | Link'.
  Property 'onClick' does not exist on type 'Link'.ts(2339)
```

And thats how im stuck in a loop. If the props: `onClick` and `href` are optional in the ButtonOrLink component, the `else` condition's union does not work as intended. 

If they arent optional, I get an error that I cant provide a potentially undefined prop to the ButtonOrLink component, so I added the `&& props.href !== undefined` snippet to try to just catch a potentially undefined snipped, but that makes the `else` union not work
