### ISSUE TITLE
default object parameter does not respect optional fields

### ISSUE THREAD

**Issue by chadaustin** [Microsoft/TypeScript#5289]
This typechecks:

```
function f({a = 1, b = 2}) {
}
f({});
```

But this does not:

```
function f({a = 1, b = 2} = {}) {
}
f();
```
with an error `Type '{}' has no property 'a' and no string index`.

I'd expect both to behave the same way.

This idiom is pretty convenient in ES6-style code and I don't see why a passed parameter would be treated differently from a default value here.

**Comment by ahejlsberg** [comment]
This is fixed by #4598. The fix is already in the nightly builds and will ship in the 1.7 release.
