### ISSUE TITLE
Unexpected infer result when using enum to union literal keys 

### ISSUE THREAD

**Issue by Dimitri-WEI-Lingfeng** [microsoft/TypeScript#52905]
# Bug Report

### 🔎 Search Terms

enum as key, enum union to other keys

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBAog0sAngQSgbwLACgpQOQCGeANHgEYn4DGJeAJntgL7bAAeADgPYBOALlDrAqAGwI9gUPog6SAksip8AllxAJEUALywNqAD752fHgWSMs7bv0HCxEqTPkBZUGDl9gEADxwox0DoAZygFJVV1JAA+bXQAa2UQOgAufGVPCEo4pFS4FixsVk5eASFRcUlpWVDXcF8kEICkkLCVNQ0YnQAKOVr3DPrEIKiASgBtAF0oQstimwAzMBBwtSgqCQJPPsHGtk9m0MU2yMQorvSvINTetx3R6+2NYcwcXCgJPjAeECgLiCDmDMrCUoItlsc1hstm4PF5Bv49oEWkcIh0utlELkkFARg8YQMOuhsLgPl8fi83lAEklUng-iRiW8MakMYz8vlsFQ1EEBLCIKgdOtgJtgH0+V14EhkAA6AgjTnc3kZABCsSFIrFGQlemlZHlWC5IB5oQyMD2pjVUNF+K8XTwxlM5n1CqNAggbgAjJbhdDwF0xnzkMQTV5lcQJvrDcb3eAAEzejVuf2B4N8sMhiBmkwECPYIA)

### 💻 Code

```ts
enum EKeyA {
  'a','b', 'c','d'
}
export declare type IActionKey = EKeyA | 'extraA'
export declare type IMenuItem<K extends IActionKey> = {kind: 'item', key: K}


export declare type IMenu<Keys extends IActionKey> = (IMenuItem<Keys>)[] 

export function createMenu<Keys extends IActionKey>(items: IMenu<Keys>): IMenu<Keys>{
    return items
}

export function createMenuItem<Key extends IActionKey>(key: Key ): IMenuItem<Key> {
  return {
    kind: 'item',
    key: key
  }
}

const ItemA = createMenuItem(EKeyA.a)
const ItemB = createMenuItem(EKeyA.b)
const ItemExtra = createMenuItem('extraA')

const menu1 = createMenu([ItemA, ItemB,])
const menu2 = createMenu([ItemA, ItemB, ItemExtra])

```
<img width="959" alt="image" src="https://user-images.githubusercontent.com/42238241/220512620-18c9bb01-3da2-42f1-80b0-181bf3cbcd72.png">

### 🙁 Actual behavior

ts infer that menu2's type is IMenu<EKeyA.a>

### 🙂 Expected behavior
ts infer that menu2's type is IMenu<EKeyA.a | EKeyA.b | 'extraA'>

### Alternative
replace enum to literal solve this problem but losing convinient in refencing and future refactoring.
```ts
// replace enum to literal
export declare type IActionKey = 'a' | 'b' | 'extraA'
export declare type IMenuItem<K extends IActionKey> = {kind: 'item', key: K}


export declare type IMenu<Keys extends IActionKey> = (IMenuItem<Keys>)[] 

export function createMenu<Keys extends IActionKey>(items: IMenu<Keys>): IMenu<Keys>{
    return items
}

export function createMenuItem<Key extends IActionKey>(key: Key ): IMenuItem<Key> {
  return {
    kind: 'item',
    key: key
  }
}

const ItemA = createMenuItem('a')
const ItemB = createMenuItem('b')
const ItemExtra = createMenuItem('extraA')

const menu1 = createMenu([ItemA, ItemB,])
const menu2 = createMenu([ItemA, ItemB, ItemExtra])

```

**Comment by RyanCavanaugh** [comment]
It's intentional to not always resolve to a union when multiple differing candidates are present, since otherwise generic inference would be unable to indicate most things that people consider to be errors. It *is* allowed to infer to a union when all constituents of that union have the same "base type".

**Comment by Dimitri-WEI-Lingfeng** [comment]
> 

Could you please give me an example that make it intentional. As a user, I really want to use enum in my case above. Otherwise, if I want to change action 'a', I should change it's usages one by one by searching them. In contrast, it only needs to use refactor feature like press `F2` in vscode or `shift+F6` in webstorm  to change all usage or this action.,

**Comment by Dimitri-WEI-Lingfeng** [comment]
> Could you please give me an example that make it intentional. As a user, I really want to use enum in my case above. Otherwise, if I want to change action 'a', I should change it's usages one by one by searching them. In contrast, it only needs to use refactor feature like press `F2` in vscode or `shift+F6` in webstorm, idm, change its definition, all usages would be changed automatically.



> It's intentional to not always resolve to a union when multiple differing candidates are present, since otherwise generic inference would be unable to indicate most things that people consider to be errors. It _is_ allowed to infer to a union when all constituents of that union have the same "base type".

**Comment by fatcerberus** [comment]
@Dimitri-WEI-Lingfeng People tend to write functions like

```ts
function foo<T>(x: T, y: T) {
}
```

Clearly the programmer's intent here is that both `x` and `y` are the "same type", otherwise they'd use separate type parameters.  But "same type" is a very loose constraint in the presence of untagged union types; If TS were to automatically infer unions across disparate parameters then *all* calls of this function become legal, regardless of the types involved.

**Comment by Dimitri-WEI-Lingfeng** [comment]
> @Dimitri-WEI-Lingfeng People tend to write functions like
> 
> ```ts
> function foo<T>(x: T, y: T) {
>     /* ... */
> }
> ```
> 
> Clearly the programmer's intent here is that both `x` and `y` are the "same type", otherwise they'd use separate type parameters. But "same type" is a very loose constraint in the presence of untagged union types; If TS were to automatically infer unions across disparate parameters then _all_ calls of this function become legal, regardless of the types involved.

@fatcerberus I understand your scenario. But the `Keys` I've shown is a generic paramater type of `IMenu`. I think it could be distinguishable. Is there any problems when ts unions the input keys when the generic a parameter?

>```ts
>export function createMenu<Keys extends IActionKey>(items: IMenu<Keys>): IMenu<Keys>{
 >   return items
>}
>```

Another question: why literal keys works but not enum?
```ts
// dont work
enum EKeyA {
  'a','b', 'c','d'
}
export declare type IActionKey = EKeyA | 'extraA'
```

```ts
// work
export declare type IActionKey = 'a' | 'b' | 'extraA'
```
