### ISSUE TITLE
Fail to check types when extending class that contain object with function that reference to "this"

### ISSUE THREAD

**Issue by sviat9440** [microsoft/TypeScript#52911]
# Bug Report

### 🔎 Search Terms

Type checking

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/JYOwLgpgTgZghgYwgAgMIHtx1NAPAFQD5kBvAKGWQAcp0qAuZfAbmQHo3kwALYAZ2QB3dFADWfCtVpUATIx79WHLrwHCxEypJghGACgBucADYBXCI3wBKZAF5iB9MAAmSzsBjJgyBOgC2fhDgKvzIxjjIALTIJsZeAuiikso6+kZmFiF8NvbIji5uWTHGfOjIIOhgQiJJAL5kZBAAHlQiVQjGcHwCAGLAEMbOpJK+WDhQAISMGGMgeAp8hMxk9Y0tbT6d3cgAok2QIM4Qzn0DQ80Hzr39g8OUldzQAPI0dIx8YFCgAOZ2yADk-0KHi8Pn8gWCCzCEWisXiyESKwaylsqLRtgacAARh8oIh2lsBABBO4xHGffHIGA3ZyMU6DZarDpdAQAIWQFyCV2QJPIlGpZymu32XOO9NcKyAA)

### 💻 Code

```ts
interface Container<T> {
  prop: T; // this works
  prop2: this; // this works
  
  fn: (value: T) => void; // if i comment this line - all is ok
  // fn: (value: this) => void; // this also not work
}

export class Field {
  container!: Container<this>;
}

export class ExtendedField extends Field {
  otherOprop: string = ''; // if i comment this line - all is ok
}

// =======

abstract class A {
  abstract field: Field;
}

class B extends A {
  field!: ExtendedField; // error is here
}
```

### 🙁 Actual behavior

```
Property 'field' in type 'B' is not assignable to the same property in base type 'A'.
  Type 'ExtendedField' is not assignable to type 'Field'.
    The types of 'container.fn' are incompatible between these types.
      Type '(value: ExtendedField) => void' is not assignable to type '(value: Field) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'Field' is not assignable to type 'ExtendedField'.
```

### 🙂 Expected behavior

```
All is ok
```

**Comment by MartinJohns** [comment]
> otherOprop: string = ''; // if i comment this line - all is ok

If you comment this line then `ExtendedField` is absolutely the same as `Field` and will be treated as such. So having the derived class makes no difference.

> fn: (value: T) => void; // if i comment this line - all is ok

This is due to the variance. If you change it to `fn(value: T): void` it will work as well.

**Comment by sviat9440** [comment]
```
interface Container<T> {
  fn: (cb: (value: T) => void) => void; // this works 
}

...
```

**Comment by sviat9440** [comment]
> If you change it to `fn(value: T): void` it will work as well.

1. I can't understand why?
2. I can't make any changes if type like `Container` is places inside third-party library.

More real example:

```
import { Subject } from 'rxjs';

export class Field {
  onChange$!: Subject<this>;
}

...
```

Class `Subject<T>` has property `observers: Observer<T>[];`;
Observer is: 
```
interface Observer<T> {
  next: (value: T) => void;
  error: (err: any) => void;
  complete: () => void;
}
```

So i cant use Subject with <this> by this bug

**Comment by sviat9440** [comment]
Hm, `fn: (value: any) => T` also works. It fails only if `T` is in function parameters.

**Comment by sviat9440** [comment]
`fn: (next: (value: T) => void) => void` also works

**Comment by whzx5byb** [comment]
@sviat9440 

> I can't understand why?

This is not a bug. Generic parameter `T` in `Container<T>` is invariance, and use `this` in a invariance position like `Container<this>` will make the class itself also invariance. That means if you try to assign a instace type of the extended class to the super class you will violate the [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle).

`fn(value: T): void` will work because it will remove the contravariance behavior for `T` due to [Function Parameter Bivariance](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#function-parameter-bivariance) and make it only covariance.

> I can't make any changes if type like Container is places inside third-party library.

I don't know what does your real code look like but if you must use it like this you should transform all function properties to methods:
```ts
interface Observer<T> {
  next: (value: T) => void;
  error: (err: any) => void;
  complete: () => void;
}

type TransformFunctionPropertiesToMethods<T> = { [K in keyof T]: 
    T[K] extends (...args: infer A) => infer R 
        ? { _(...args: A): R }['_']
        : T[K]
}

type _Observer<T> = TransformFunctionPropertiesToMethods<Observer<T>>
```

**Comment by RyanCavanaugh** [comment]
This is a correct error; a rough sketch of why:
```ts
abstract class A {
  abstract field: Field;

  foo(f: Field) {
    this.field.container.fn(f); // <- legal call
  }

}

class B extends A {
  field!: ExtendedField = {
    container: {
      fn(e) {
        console.log(e.otherOprop); // <- undefined read
      },
      prop: null as any,
      prop2: null as any
    }
  }
}
```

**Comment by sviat9440** [comment]
Ok. thank you
