### ISSUE TITLE
Google Feedback on TypeScript 5.0-beta

### ISSUE THREAD

**Issue by h-joo** [microsoft/TypeScript#52913]
This GitHub issue contains feedback on the TS 5.0-beta release from the team that is responsible for keeping Google's internal software working with the latest version of TypeScript.

## Executive summary

*   Small changes to our TypeScript code are required to make it compile with TS  5.0.
*   Detail sections below explain the changes to our code we expect to make to  unblock the upgrade.

## Impact summary

| Change description                         | Announced | Libraries affected |
| ------------------------------------------ | --------: | -----------------: |
| All enums are union enums                  | yes       | 0.056%             |
| Forbidden Implicit Coercions in Relational Operators    | yes       | 0.037%             |
| lib/d.ts changes                           | yes       | 0.011%             |
| Type inference for declared enum member assignment  | no        | 0.004%             |
| Others                                     | -         | 0.004%             |

The **Announced** column indicates whether we were able to connect the observed change with a section in the [TS5.0-beta announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/).

The following sections give more detailed explanations of the changes listed above.

### All enums are union enums

This was part of the [release announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#all-enums-are-union-enums), and the majority of this failure was coming from test codes that was passing in ill-typed value and was caught by the new change.

We expect to add `// @ts-ignore` to get around with this issue.

### Forbidden Implicit Coercions in Relational Operators

This was part of the [release announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#forbidden-implicit-coercions-in-relational-operators), and uncovered many code that were doing implicit coercions.

To be safe to have no implication on the runtime, we expect to ts-ignore this warning for existing code.

### lib/d.ts changes

We support the typing improvements. Generally it's clear what's changing and the changes seems minimal this time. The majority of the change is coming from the change in TSC API, that `modifier` property is now gone from `Node` type.

For the TSC changes, we expect to fix our codebase to comply to the new API and for other typing changes, we expect to `// @ts-ignore` to silence the errors.

### Type inference for declared enum member assignment

We saw the same issue that was reported in [this bug report](https://github.com/microsoft/TypeScript/issues/52531), but it already seemed to be fixed.

### Others

There was a runtime failure in our internal tooling caused by the change in the behaviour of `ts.getJSDocTags`. Before, it was blindly traversing up in the AST to find a valid JSDoc, but now it first checks whether a node can have a JSDoc,
otherwise returns an empty array. 

[This](https://github.com/microsoft/TypeScript/pull/51682/files#diff-605cd83dbc128129ef69a4dba9b967fbd56d7d1c2d34fc59348cda739f8e8d11R1147) is the change that caused our failure, and we have a fix which now queries JSDoc only on specific nodes.

There were other small failures that all looked reasonable such as disallowing ill-formed type annotation (using '?' or '*') in catch statements. ([playground in 4.9](https://www.typescriptlang.org/play?ts=4.9.5#code/LAKALgTgngBA3qUBfGBjAhmVALGAKAUwggC4YAqASnkRCSA), [playground in 5.0-beta](https://www.typescriptlang.org/play?ts=5.0.0-beta#code/LAKALgTgngBA3qUBfGBjAhmVALGAKAUwggC4YAqASnkRCSA))

We also noticed some errors around [inappropriately narrowing types](https://github.com/microsoft/TypeScript/issues/52571) to `never` in case of `instanceof` operations on `Function` types, but was also fixed

**Comment by DanielRosenwasser** [comment]
Thanks for following up here! It sounds like these are mostly reasonable. What sorts of things on our API are you planning to `// @ts-ignore` to get through?

**Comment by h-joo** [comment]
I apologize for making it a bit confusing. I mixed up the d.ts changes as a whole(regular typing changes which involves lib.d.ts changes + typescript.d.ts changes) so it was a bit confusing when I read it again.  We don't intend to `ts-ignore` any TypeScript Compiler API changes as it'll most likely cause runtime failures, but we only will `ts-ignore` the regular changes coming from `lib.d.ts` changes and depend on the code owners of our codebase to fix for themselves correctly with accordance to the new type.
