### ISSUE TITLE
Boolean wrapped values don't refine that value to not be undefined

### ISSUE THREAD

**Issue by lukeapage** [microsoft/TypeScript#52910]
# Suggestion

## 🔍 Search Terms

Boolean refine wrapped

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

if you wrap a value in `Boolean()` and use it in a conditional, it should still refine it to be not null or undefined.

## 📃 Motivating Example

In JSX its common to do the following
```
x && <Component x={x} />
```

but we have issues where if x is falsy but not accepted as a non value in jsx it can leak the type, so there is a lint rule to protected against it

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-leaked-render.md

the least invasive fix of the lint rule is to wrap x in Boolean

```
Boolean(x) && <Component x={x} />
```

but that breaks typescripts ability to refine x.

example:
```
function a(x: undefined|null|{a: boolean}) {
    Boolean(x) && b(x);
}

function b(x: {a: boolean}) {

}
```

It is possible to fix this with something like this

```
interface BooleanConstructor {
    <T extends {} | string | number | boolean | Array<any>>(
        value?: T | undefined | null | '' | false,
    ): value is T;
}
```

**[playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEIHt0BsJxAYXRAGcwoBXBMdKZAbwChlnkAeAFWQgA9IQATYvQC+yAD7JSUUAHNxyEOQC2AI2jyVmHHnkBBKFDgBPVniMA+cwAomLOwDc4WchAD8ALmScJ5ARBigEPzyilhY8gDkEfLwWMQQADS2zACUno7OKMBC7ADcDMIMRTC+VMBEyHBW3J6+-P6B-GKhWGJ0cJ6a2Lggwin0yWhaPdX9AGRjyCqj+YUMJSBlFdM19B1Tw3h9AwVAA)**

Is there a reason to not have the above in the library - does it make typescript slower?

**Comment by MartinJohns** [comment]
Another duplicate of #16655.

**Comment by lukeapage** [comment]
Thanks, I did search and didn't find that one.
