### ISSUE TITLE
TypeScript tries to compile `@link` tagged comments and occurs error

### ISSUE THREAD

**Issue by samchon** [microsoft/TypeScript#52918]
# Bug Report
### ⏯ Demonstration Link
![Bug](https://raw.githubusercontent.com/samchon/report-comment-compile-error/master/images/bug.png)

  - Repository: https://github.com/samchon/report-comment-compile-error
  - Github Actions Result: https://github.com/samchon/report-comment-compile-error/actions/runs/4245549822/jobs/7381209175

### 💻 Code
```typescript
import { IBbsArticleSnapshot } from "./IBbsArticleSnapshot";
import { IBbsComment } from "./IBbsComment";

/**
 * Article of BBS.
 * 
 * Note that, main content of article is stored in {@link snapshots} property.
 * The {@link IBbsArticleSnapshot} records would be accumulated whenever updating
 * current article. It is to keep the history of article.
 * 
 * In the same reason, {@link IBbsComment} also stores {@link IBbsCommentSnapshot} 
 * records whenever update it.
 * 
 * -------------------------------------------
 * 
 * Let's link that never exists
 * 
 *   - {@link NeverExistDto}
 *   - {@link Nothing}
 *   - {@link NoWhere}
 *   - {@link NoOne}
 * 
 * @author Samchon
 */
export interface IBbsArticle {
    ...
}
export namespace IBbsArticle {
    // THIS IMPORT STATEMENT OCCURS BUG
    export namespace Comment {
        export import IStore = IBbsComment.IStore;
    }
}
```

### 🙁 Actual behavior
I succeded to reproduce https://github.com/microsoft/TypeScript/issues/49706 bug. The bug was not occured by Korean characters. The error was occured by type `import` statement in a `namespace` declaration that has same name with a `interface` type.

When there's an interface that declared namespace with same name, and imports another type in the namespace. Also, the error occurs only when importing TypeScript file (`await import("file")` statement) after composing `ts.createProgram()` with `ts-node`. 

I can't sure that this is a bug of TypeScript or `ts-node`. Therefore, I report this issue both in TypeScript and `ts-node`.

### 🙂 Expected behavior
No error by `@link` tagged comments.

**Comment by RyanCavanaugh** [comment]
I'm not going to run arbitrary npm commands in your repo. Running `tsc` there, I don't see any errors.
