### ISSUE TITLE
function-arguments sharing the same generic should share typeguarded types.

### ISSUE THREAD

**Issue by bigmistqke** [microsoft/TypeScript#52935]
# Suggestion

How arguments sharing the same generic is treated differs in regards to calling the function and the function's implementation. 
This request would not break existing code, since `func` can not be called with two different types without type-error anyway.

(most likely a duplicate, but couldn't find it)

## 🔍 Search Terms

generic shared argument arguments type-guard type-guarding

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

```ts
const func = <T extends string | number>(arg1: T, arg2: T) => {}
func(0, "a");
```

In above example, `func` will type-error as expected, since `arg1` and `arg2` do not share same type.
However, inside the implementation of `func`, the same type-relation is not considered:

```ts
const func = <T extends string | number>(arg1: T, arg2: T) => {
  if(type arg1 === "string"){
     arg1;  // T & string 
     arg2; // string | number
  }
}
```

My proposal is to update the `T`'s type as 1 of its values which are typed with `T` are type-guarded.
Ideally I would like to see something like: 

```ts
const func = <T extends string | number>(arg1: T, arg2: T) => {
  if(type arg1 === "string"){
     arg1;  // T & string 
     arg2; // T & string
  }
}
```

## 📃 Motivating Example

Since the function-signature already prevents different types to be passed in as arguments, it only makes sense to have the same logic within the function-implementation. This could simplify a lot of code, remove unneeded checks and remove the need for unwanted `any`-casts.

## 💻 Use Cases

I faced this friction when implementing overloaded functions, but the use-cases would be widespread.

**Comment by fatcerberus** [comment]
It still possible to pass different types by passing in a `string | number`, it’s just that TS won’t *infer* a union automatically.  Therefore it’s not safe to narrow all the `T`s based on a single type guard.

**Comment by bigmistqke** [comment]
True. Thx for reply.
