### ISSUE TITLE
Regression: Alias of `InstanceType<(typeof A)['B']>` causes circular reference error in 3.7

### ISSUE THREAD

**Issue by whzx5byb** [microsoft/TypeScript#52930]
# Bug Report

### 🔎 Search Terms

nested class InstanceType alias

### 🕗 Version & Regression Information

- This changed between versions 3.6.2 and 3.7.5

### ⏯ Playground Link

Work: [3.6.2](https://www.typescriptlang.org/play?declaration=false&ts=3.6.3#code/PTAEGUEsBcFcENqQPYDtQEEBcAoaBPABwFNQBJVVYgJ1AF5zUBnaeVAY2IBUjiAeABQESyAGagA8rGg0AlAG0A5BSrVFAXQB8AbhzsANvCZNJ0mqADeOUDdABzYtADCAC0j6AJgNlZGqy6DWtsHUjrDU6AAMoEYxqPiBwQC+OEE2LIiQ7H7mDAZGJirmVsHBAB6+qLAAtgBG5iAMkdqJpTYgbTYAeqAA7u76fcjUANZ9LsTohNTIAG6QHqSLovCw+tCgs-D6sMSpnaDsaCzUsOzQwwLTyDLnxB6ghPChqNC+UjLUspZpB6DQbiYADoyvRQABGXS-A4AyDAp4vaBAhzONyeby6P62DqdHr9fSDXrDMa9CboI7VaqTDYwaG2FLJHApHAdKBwTJoUAAIVwwlIRWoACYwRQMhxuLxBHyxKZPoKFMpKDRBRodHpDMZZcq+FxND9gjjgniBkNRuNJqBQtU5qQAaRYFUmPd-rxHs94FTPvtbE7Ue4PL4BOw0QGckLvnQ9bNkAswaIHecUKhvJYkpjscBfa5-UGQ74BfKAgyM8aCaaSWTDmhZjQNhcYqBPS5kB5ft70qwkNkC2D8pqeyVOhVQFU6g1gE0WnT2mBcX0TUSzaSLdd5otQMtVutNttdu3SkdmNBTudLtdbjIHgjqe8zEK+Gx8JpvoOsbDgaCGJD9zDAUDr68QJZiGAjRLEj6yOmWKGqUpaEsS5rksglLUqAtIHMWNgpEkQA)

Break: [3.7.5](https://www.typescriptlang.org/play?declaration=false&ts=3.7.5#code/PTAEGUEsBcFcENqQPYDtQEEBcAoaBPABwFNQBJVVYgJ1AF5zUBnaeVAY2IBUjiAeABQESyAGagA8rGg0AlAG0A5BSrVFAXQB8AbhzsANvCZNJ0mqADeOUDdABzYtADCAC0j6AJgNlZGqy6DWtsHUjrDU6AAMoEYxqPiBwQC+OEE2LIiQ7H7mDAZGJirmVsHBAB6+qLAAtgBG5iAMkdqJpTYgbTYAeqAA7u76fcjUANZ9LsTohNTIAG6QHqSLovCw+tCgs-D6sMSpnaDsaCzUsOzQwwLTyDLnxB6ghPChqNC+UjLUspZpB6DQbiYADoyvRQABGXS-A4AyDAp4vaBAhzONyeby6P62DqdHr9fSDXrDMa9CboI7VaqTDYwaG2FLJHApHAdKBwTJoUAAIVwwlIRWoACYwRQMhxuLxBHyxKZPoKFMpKDRBRodHpDMZZcq+FxND9gjjgniBkNRuNJqBQtU5qQAaRYFUmPd-rxHs94FTPvtbE7Ue4PL4BOw0QGckLvnQ9bNkAswaIHecUKhvJYkpjscBfa5-UGQ74BfKAgyM8aCaaSWTDmhZjQNhcYqBPS5kB5ft70qwkNkC2D8pqeyVOhVQFU6g1gE0WnT2mBcX0TUSzaSLdd5otQMtVutNttdu3SkdmNBTudLtdbjIHgjqe8zEK+Gx8JpvoOsbDgaCGJD9zDAUDr68QJZiGAjRLEj6yOmWKGqUpaEsS5rksglLUqAtIHMWNgpEkQA)

### 💻 Code

Situation A:
```ts
type Inner = InstanceType<(typeof Outer)['Inner']>;
class Outer {
    getChild(): Inner { 
        return 0 as any 
    }

    static Inner = class Inner {
        x: number //= 0; 
        //        ^ will work when provide default value

        constructor(protected parent: Outer) {
            this.x = 1;

            this.parent.getChild();
            //        ^ will work when comment it
        }
    }
}
```

Situation B:
```ts
type Inner = InstanceType<(typeof Outer)['Inner']>;
class Outer<T> {
    //      ^ will work when remove the type parameter, even it is unused

    setChild: (child: Inner) => void = function() {};
    //setChild(child: Inner) { }
    //^ will work when convert to a method
    

    static Inner = class Inner {
        x: number //= 0; 
        //        ^ will work when provide default value

        constructor(protected parent: Outer<any>) {
            this.x = 1;
            
            this.parent.setChild(0 as any);
            //        ^ will work when comment it
        }
    }
}
```

### 🙁 Actual behavior

Error: Type alias 'Inner' circularly references itself.

### 🙂 Expected behavior

No error.

**Comment by whzx5byb** [comment]
I tried to not use an alias, but found the code in situation A [still breaks](https://www.typescriptlang.org/play?declaration=false&ts=3.7.5#code/MYGwhgzhAEDyCuAXApgJ2gbwFDV9A5sogMIAWAliACYAUAlAFzQCSAdhImK8MgCoCeAB2QAeGoiHIA9gDM4SNHQDaAcjas0KgLoA+TNBx4jqIvFStoABmiQbrfgaMBfLIdwcwicsBasN6AF5oUEgYdTRMNyNoAA8mVngAWwAjNFdovGApdkRUeGBEKVQaQVQpFALkKmhBMBNWRCYEFFQ6SIyMxAoIADoY6CCARgBudI6jLvJe2vrEHsISCmp6UfGXZywXIA), which prevent me from using nested class. 

```ts
class Outer {
    getChild(): InstanceType<(typeof Outer)['Inner']> { 
        return 0 as any 
    }

    static Inner = class Inner {
        x: number

        constructor(protected parent: Outer) {
            this.x = 1;

            this.parent.getChild();
        }
    }
}
```

At the moment the only workaround I can come up with is to provide an evil default values like `prop: SomePropClass = null as any`...

**Comment by RyanCavanaugh** [comment]
This *is* circular, though, right? What am I missing?

**Comment by whzx5byb** [comment]
@RyanCavanaugh 

I don't think so. I have a simplied repo and let's see the code below:
```ts
class Outer {
    foo!: () => typeof Outer.Inner;

    static Inner = class {
        parent!: Outer;
        bar: number;

        constructor() {
            this.bar = 1;
            this.parent.foo();
        }
    }
}
```

You may argue that there is a circular because:

- What is the type of `typeof Outer.Inner`? It is `{ new(): {parent: Outer, bar: number} }`
- What is the type of `Outer`? It is `{ foo: () => typeof Outer.Inner}`;

It seems like a circular but it is just a trival case nothing more like `type A = () => B; type B = () => A` and [is correctly resolved in 3.6](https://www.typescriptlang.org/play?declaration=false&ts=3.6.3#code/MYGwhgzhAEDyCuAXApgJ2gbwFDV9AZgPaECEAXNABQCU0AvAHzSICeADsofnEmgHQBJAHZC0Abiw48ERGEQBLYNGGj0daKEgxseXdDZhUyIYnI8UqKXugAjQxSHwAtjbSTruYISEzU8YIiEqDSYVh64iAAW8hB8dmrQAIwS4bpRMXwGRiZ8RIQ0KR4AvmElRUA). 

Also note that in 3.7 when add a definite assertion `!` to `bar: number` or delete the call operator `()` in `this.parent.foo()`, which will not change the type of `Inner` but every thing will be ok ([try it here](https://www.typescriptlang.org/play?declaration=false&ts=3.7.5#code/MYGwhgzhAEDyCuAXApgJ2gbwFDV9AZgPaECEAXNABQCU0AvAHzSICeADsofnEmgHQBJAHZC0Abhx5JuCIjCIAlsGjDR6OtFCQY2PHuhswqZEMTkeKVNP0AjIxSHwAtjbRYA9O-16AetDAAJgH+0ADkJKHQABZoyFjWesCEQrKo8MCIhKg0mAnezFEKEHx26tAAjHneiIXFhsamfESENFX6nvnefgHIIMgoBcjQAEQ0w20AvtZTU0A)) so there must be something wrong.

**Comment by RyanCavanaugh** [comment]
I don't see a defect here. Being able to avoid *some* circularity errors, through cleverness, doesn't mean we can guarantee to avoid *all* circularity errors, and sometimes that cleverness leads to correctness or performance problems elsewhere and needs to be removed.

If someone wants to send a PR to improve this without side effects they can, but this isn't a bug even if it did work for some reason in 3.6.

**Comment by whzx5byb** [comment]
Workaround: just add a pair of parentheses and everything is OK.
So I still believe it should be a bug.

```diff
class Outer {
    foo!: () => typeof Outer.Inner;

    static Inner = class {
        parent!: Outer;
        bar: number;

        constructor() {
            this.bar = 1;
-            this.parent.foo(); //<- error
+            (this.parent.foo()); // <- ok
        }
    }
}
```

**Comment by RyanCavanaugh** [comment]
My prior comment stands. Again, PRs welcomed, but issuing circularity errors in the presence of circularities is not a bug.
