### ISSUE TITLE
for await of loops don't call AsyncIterator.return() on early exit

### ISSUE THREAD

**Issue by martinbirks** [microsoft/TypeScript#52936]
# Bug Report

### 🔎 Search Terms

Async return AsyncIterator

### 🕗 Version & Regression Information

- This changed between versions 4.8.4 and 4.9.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/MYewdgzgLgBAMgSQLIICowLwwMwG4CwAUEaJLAIYQCeYwCUApgE7kBGANg5jAN5EwwA2gGUqAW1Yh2AOko06jFlBBMAugAoAlL34CYnWAEtuABgKE9MJgygBXJmB0XLMMAwAeULU5d7S0GAATcC4sYwwI+GQ0c18Bf1gAN3J2W1CgkJgAfhhbMECGADNDN0CYAC4YQwBqati46zsHGAAFJhAxQwgGaWsIKUSGdR4YZNSGABoMtxgAX016y1mJ3UtG+zBvPmdffyke9hAAc3UAIgAlAFFUAFVzgDlThdWXAHpXmFQACy6YAHdDOx2DBWFxrORgF8GGVDIUYFAoTB-LYxMwkSlOGUAOSscEAayxMBUMCx6wchIY5CY7CoVUcCK4hxAAAdpC81jYNrxpgxKlAmGkpmM0pU8gViqU5os9MsXrN6rLCPKiER1HJaDBvBgAHw+GCFYnkP7kQywdQJVwoolw9UKZhsTjabaWPacaSHE5gFHPHYg-EKojzLS4IA)

### 💻 Code

```ts
const LIMIT = 3;

const asyncIterable = {
  [Symbol.asyncIterator]() {
    let i = 0;
    return {
      next() {
        const done = i === LIMIT;
        const value = done ? undefined : i++;
        return Promise.resolve({ value, done });
      },
      return() {
        console.log("RETURN");
        // This will be reached if the consumer called 'break' or 'return' early in the loop.
        return { done: true, value: undefined };
      },
    };
  },
};

(async () => {
  for await (const num of asyncIterable) {
    console.log(num);
    break;
  }
})();
```

### 🙁 Actual behavior

Outputted "0", the return function of the async iterator was never called.

### 🙂 Expected behavior

Output "0" and "RETURN" to the log. This would show that the return() function was called.

**Comment by fatcerberus** [comment]
Possibly related to https://github.com/microsoft/TypeScript/issues/50525
