### ISSUE TITLE
`Array.indexOf` on an array of functions is incorrectly typed

### ISSUE THREAD

**Issue by jacobchrismarsh** [microsoft/TypeScript#52942]
# Bug Report

### 🔎 Search Terms
* Array.indexOf wrong type
* Improper typing array of function

### 🕗 Version & Regression Information
This is happening on Version 4.9.5, but I first observed it in Version 4.6.3.

This is the behavior in every version I tried, and I reviewed the FAQ for entries about common errors that aren't actually errors.

### ⏯ Playground Link
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHgLhgCmQNwIYBsCuBTJMHAWwCM8AnAShgF4A+GNEASwBMqBtAXTph4BQAgPTCYACUp4ANDAAGAMxxhgcmCwgwADhRBbKWAJ4woh-WwFwAdApZg2yJSrqMnwKkNESpsxctXqmqbmMBiaGPJEZJRyllZ2bHhwAPIKjv4uMG4eImIA6ngwwBhgReC2FMQmABYYsH4qahowOBB2AOY1hRAYxIXBhWHymLh4atVSVgKgkLCGSKgj+EjQFB00DEysHDx8grkwAHIgAO7ybk1BZnhsoeHyqx2xhvH2SanpzpvZAkA

### 💻 Code

```ts
const x: ((value: number) => void)[] = []

// Here, `func` is properly typed as `(value: number) => void`
x.find(func => func)

// Here, `func` is typed as a `number`
x.indexOf(func => func)

// We can confirm that `func` is using the same type as `value` here.
const y: ((value: string) => void)[] = []

// Now `func` is typed as a `string`
y.indexOf(func => func)

```

### 🙁 Actual behavior
In `indexOf`, the searchElement argument is not typed correctly when you are using an array of functions. Instead, it has the same type as the first parameter of the function. 

### 🙂 Expected behavior
I would expect `indexOf` to behave the same as `find`, and that the `searchElement` would be typed as `(value: number) => void`.

**Comment by Andarist** [comment]
This works correctly now. `indexOf` doesn't accept a callback, it doesn't work like `find`. Those observed parameter types are just typed using contextual typing based on the type of the array (since those are arrays that contain functions).

**Comment by fatcerberus** [comment]
To clarify on the point above:

```ts
x.indexOf(func => func)
```

…is not actually passing a callback.  It’s searching the array for the arrow function you passed in.  You will find that as a result the check always fails (i.e. returns `-1`) at runtime, regardless of what the callback does.  In fact it will never actually be called.

In other words: `indexOf` is expecting a value of type `(value: number) => void`, because that’s what the array contains, so that’s what it infers.

**Comment by fatcerberus** [comment]
You’re probably looking for `findIndex`

**Comment by jacobchrismarsh** [comment]
> This works correctly now. `indexOf` doesn't accept a callback, it doesn't work like `find`. Those observed parameter types are just typed using contextual typing based on the type of the array (since those are arrays that contain functions).

Ah, of course. You're right, I totally misinterpreted it. Like @fatcerberus, I am indeed looking for `findIndex`.

Thanks for the corrections! I'll close this since it isn't an issue.
