### ISSUE TITLE
Typescript adds `export {}` at the end of cts/cjs files

### ISSUE THREAD

**Issue by jonaskello** [microsoft/TypeScript#52948]
# Bug Report

`.cjs` are always treated as CommonJS so typescript should never add `export {}` to them because then node cannot load them as CommonJS.

### 💻 Code

**myfile.cts**

```ts
async function foo() {
  const x = await import("bar")
}
```

### 🙁 Actual behavior

Compiles to **myfile.cjs**

```ts
async function foo() {
  const x = await import("bar")
}
export {}
```

It added `export {}` to the end so it cannot be loaded by node as CommonJS.

### 🙂 Expected behavior

Compiles to **myfile.cjs** without any `export {}` added.

**Comment by RyanCavanaugh** [comment]
We definitely need to see the tsconfig here

**Comment by jonaskello** [comment]
This is in a monorepo so this is `tsconfig.settings.json`:

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node",
    "isolatedModules": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "composite": true,
    "esModuleInterop": true,
    "jsx": "react",
    "newLine": "LF",
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "noErrorTruncation": true,
    "skipLibCheck": true,
    "lib": ["esnext"]
  }
}
```

And this is `tsconfig.json` at the package level:

```
{
  "extends": "../tsconfig.settings.json",
  "include": ["src"],
  "compilerOptions": {
    "outDir": "lib",
    "rootDir": "src",
    "lib": ["dom", "es2015", "es2017.object", "ES2019.Array", "esnext.asynciterable", "esnext"]
  },
  "references": [
   // ...
  ]
}
```

Typescript version is 4.9.5.

**Comment by jonaskello** [comment]
The `package.json` file has `"type": "module"` and I tried with all different settings for `moduleDetection` i tsconfig.

**Comment by RyanCavanaugh** [comment]
@weswigham thoughts?

**Comment by jonaskello** [comment]
I also tried with `"module": "NodeNext",` but that caused all `.ts` files to be compiled to CommonJS format (tried all settings for `moduleDetection`). My scenario is that I have a package with `type: module` where I want everything to compile to ESM except for one file that needs to be CJS because it is loaded by an external system that only supports CJS ([bull](https://www.npmjs.com/package/bull) queue system). So in the one CJS file I use dynamic `import()` to import other ESM files from within the package.

Currently to achieve this I use the tsconfig posted above and then after compile I do `sed -i 's/export {}//g' packages/xxx/lib/queue/delegate.cjs`. It would be nice to get rid of this hack :-).

**Comment by fatcerberus** [comment]
I don’t know if this helps but fwiw if you set `module` to nodenext then `moduleResolution` should be the same.  I don’t think `nodenext` module + `node` resolution (i.e. pre-ESM node module resolution behavior) is a supported configuration.

**Comment by gomain** [comment]
This came as a huge surprise for me too.

My use case in transitioning a code base from javascript using CommonJS to typescript ESM. An intermediate step I want to do is first `"allowJs": true` in tsconfig.json. With `"type": "module"` already set in package.json, I rename all source files from `.js` to `.cjs` to be explicit. Then boom, where did this extra `export {}` come from!?!. The plan was to, bit by bit, rewrite each module to typescript ESM - renaming them to `.mts`.

**Comment by jonaskello** [comment]
@weswigham Just to clarify, does this mean that:

1. The setting ` "module": "ESNext"` will treat `.cts` files as ESM?
2. The only setting that will treat `.cts`  as CJS is  `"module": "node14"`?

**Comment by weswigham** [comment]
Yes and no. `cts` (and `mts` for that matter) will be transpiles to cjs when `module: commonjs`, same as a `ts` file. `module: node14` (and nodenext) is simply the only module target which has a distinction between the file extensions (and it uses `moduleResolution: node14` data to accomplish that, so you need that set, too).

**Comment by CarlUdo** [comment]
I’ve been pulling my hair with this myself and have found a workable solution. The trick is to use flag **--isolatedModules** during build. 

As an example say that you in your TypeScript project have a _main.ts_ file in your static folder to serve the client (browser) with functionality; _src/static/scripts/main.ts_.

This is what _main.ts_ file looks like:

```
const logger = () => {
  console.log('Hello browser console!');
};
```

Having property _“type”: “module”_ set in _package.json_ and building (compiling) your project with tsc will generate the following file _dist/static/scripts/main.js_:

```
const logger = () => {
    console.log(' Hello browser console!');
};
export {};
```

This won’t work in browser. Building _without_ property _“type”: “module”_ set in _package.json_ will generate the following _main.js_ file:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const logger = () => {
    console.log('Hello browser console!');
};
```

That doesn't work either in the browser. The trick is to build the _main.ts_ file by itself using the **--isolatedModules** flag. The rest of the files can be built in normal way.

In _package.json_ make the following build script:

`"build": "tsc && tsc --isolatedModules ./src/static/scripts/main.ts --outDir dist/static/scripts"`

In _tsconfig.json_ exclude _main.ts_ file from ordinary build:

`"exclude": ["node_modules", "dist", "src/static/scripts/main.ts"]`

Then run your build script and you will receive this _main.js_ file:

```
var logger = function () {
    console.log(‘Hello browser console!');
};
```

And voila – it works like a charm in the browser. Hope it helps.
