### ISSUE TITLE
Functions on mapped object types with inlined computed keys don't infer correctly

### ISSUE THREAD

**Issue by MiracleBlue** [microsoft/TypeScript#52954]
# Bug Report

### 🔎 Search Terms

object type, type inference, mapped type, computed keys

### 🕗 Version & Regression Information

Issue occurs in the same way on  *all* TS versions in playground.  

Tested on all from ver 3.3 -> 4.9.5 -> Nightly

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about Type System Behaviour

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.9.5#code/C4TwDgpgBA8gTgSwOYIHYEMA2UC8UDeUAZgPYkBcUA5BAB6QDGwAzlOlM8IqklJgsAhwsVADRQARugBelCWUwR0qcVLiVUAVwC2EoVAC+AWABQoSFACy6MJAAmuAqahQA9K6gB3CFTjRtNmBovMAAFtAA1hAgrCREsIgoGNjAJMSaqEwIJKisnqEkzNDocEg6EKjAbKgOfsCacKhQ5hCsJRDObh5h0Mzo2sWsPVAAblia0C2spHAJyGhYne4caTNQAAZqGjp6cOvi3lABYM1pmyXbuvo4AHxQWld7nQDaYHAkJ2hQUSBxc0lYAC6lAAFCUkJR4PNkq93mBAQBKXB3KEAzCwj6A0zGEymZYAFVCCGmGSyOSgxOaEAYoVQCAYWEwICgfjsGTsymAqk0VXCmDArAQmEwmk4wkEzXCkk0SFMDBynCgbw+AGUIIomCRZngoAAeZVgABy-WgdEENVYYuCNxBBuNA0odpNCMdcPt0FuSrdJoA3KY8R4AOpC7AAK1FVT0kt6XGC1DUVDlCsjJQA0tFHAa1RrUnAQVQEwi-biTPLclVPFqIsF8a1gDAJKHqcBKNZbBAHHh8J1SBQoGDSkjPTR6M22hxYzw+AIhCJRJ0pLJ++Ch3cuBN5yYXMtK3AIqxw4qiGhBmwoGXOOJ1uD1hTUEQhEMzg9drf0Hl1ZgXmp0yBgcvB2RKAAFYAEYAGYABZgOxf1S2TKAMjoRhBDsJkADF0CFYIAFFaH6MBFFbQIO0cbst2IMhQRXICRxQ8crSnfhBGETAxAXGRqMAz11wgTdtw8JDRyYUiWnPcIGAiKAhHedQNhvClBW0Qj6QEJl5NQEB1gAfhcAAhHkWQgepGmacBoEpY9UAgbSlg8CARgqSUSBlUJo2ZZgCk0TAHHkMJJEmKU+gGMzIAAOhcOyoDwlDSL0UJ0BGbIGg4LyfICik7AqYB6SwU4ouGAs02iKhpPw5TFDvahd2rHha04BsmyYRMKIxMBs2bLV80Lf8ByQVcQIg6DYJLZY8IIxRYnieU4D8JhpNmrVmHIJNy3PLU5uAHDFrgZarBIzsnAosadtYGbNvUtY0HO5sjJMpopi8cImh+RSz0Y3gtXW8tOioXsqC4-qgOAkGACZ+PjGQAYAoHh1A0GoPY1qf2iXqaJ4uAJhGgNpMcpoZKW9bZubS6vuujbbrqBoHvMp6nNFOMs3VTq4G5KpwTezgQzvB9iYcd9qhAVbFRupgAElUH4ay7G22S9rbewyJeJmcy6v6yCoBE0e4u4QeA8HlbhDrNTzIrpE17XYbuKh4cRiG2uN3NupKC3AYG3jsZMMb6H4Bg1I8xgECIEA42Ga9SlvMSarad52QpLkoD+eUGiKYWKyrEoXJqcaKtaYj20O8iXAd5mTed82tcBuQFCUVB3cxvjDdVUunaKuBXZhy5dgG23oIh5YVS4ZQkHVEBxDD3tbwZIooHCPwvAQLLcnj1gqdMsTUg2D79nPdAGandgxIJuAouYa6LKqSlkObUS0ijdhmNnTAIoAQSQLCVETyXmQS9tl-yJy8plI8lIq9SkaApYdjCk3dqLc1b-Urp3ag18mAMUnLwR+rFNa0RQSwd66DpwsTnNiIAA)

Further information and discussion [from my StackOverflow question.](https://stackoverflow.com/questions/75550379/why-do-functions-on-mapped-objects-with-computed-keys-not-infer-correct-types)

### 💻 Code

```ts
type Original = { foo: 'expects a string literal', baz: boolean, bar: number }
type Mapped = {
  // we're mapping the keys of Original to functions whose argument and return types are
  // the same as the value types for Original
  // so for `bar: number`, we map to `bar: number => number`
  [prop in keyof Original]: (arg: Original[prop]) => Original[prop]
}

// This function is technically redundant, but helps illustrate the bug
// the `propName` type should be the literal string
const propSelector =  <propName extends string>(propName: propName): propName => propName;

// Will just be the string 'bar'
const barKey = propSelector<'bar'>('bar');

const workingTestObject: Mapped = {
  foo: (arg) => 'expects a string literal',
  baz: (arg) => true,
  // works just fine referencing the computed key as a const , 
  // `arg` infers to `number` as it should
  [barKey]: (arg) => 51345
}

const unexpectedlyFailingExample: Mapped = {
  foo: (arg) => 'expects a string literal',
  baz: (arg) => true,
  // unexpected type check error: `arg` is implicitly `any`?  But return type is fine?
  // even though they should both be the same type.  
  // Expected behaviour should be identical to the 'barKey' example in 'workingTestObject', 
  // so `arg` should be inferred as `number`
  [propSelector('bar')]: (arg) => 51345
}
```

### 🙁 Actual behavior

When an object with a mapped type has a computed property key whose expression is inlined (e.g `[returnsSomeKey(arg)]: etc`), when the value is a function with a mapped argument type, typescript fails to infer it and reverts to `any`, but simply assigning the expression to a const (e.g `const someKey = returnsSomeKey(arg)`) and referencing the const as the key (e.g `[someKey]: etc`) works just fine, and the argument type is properly inferred.

### 🙂 Expected behavior

The behaviour should be the same for either inlining the computed expression or assigning to a const and referencing it as the key, that is, the argument type should be inferred correctly in both cases.  This is because both cases are effectively equivalent, and should be equivalent as far as the type checker is concerned. It seems that the inlined computed key is resolved in a different order than in other cases, perhaps?

**Comment by RyanCavanaugh** [comment]
There might be some subtle reason this is harder than it looks, but given that `barKey` works I can't think of one.

**Comment by MiracleBlue** [comment]
Yeah, logically one would think it to be fairly straight forward, but this bug being a thing feels like there is a much more complex system than you'd expect, perhaps to do with the order at which certain kinds of expression are inferred or something like that.

**Comment by MiracleBlue** [comment]
@RyanCavanaugh if one wanted to go looking for it (particularly one without previous experience messing with the type checker), where would you suggest as a starting point/points?  I had a perusal through the structure to see if anything obvious stood out, but there is a *lot* in there!

**Comment by Andarist** [comment]
This is already fixed by https://github.com/microsoft/TypeScript/pull/51915 and awaits review 😉

**Comment by MiracleBlue** [comment]
Wow, that was fast.  You're amazing @Andarist :) thank you for that fix, and thank you to the TS team for merging it!
