### ISSUE TITLE
ECMAScript Explicit Resource Management & `using` Declarations

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#52955]
@rbuckton's proposal for [Explicit Resource Management](https://github.com/tc39/proposal-explicit-resource-management) has reached stage 3 in TC39!

As such, it's time for TypeScript to look into its implementation. This proposal carries a few new features that TypeScript should have

* [`using` declarations](https://github.com/tc39/proposal-explicit-resource-management/tree/22f80f76fe9ed4bd08faff076520fb08b0bf87f9#using-declarations)
* [`Symbol.dispose`](https://github.com/tc39/proposal-explicit-resource-management/tree/22f80f76fe9ed4bd08faff076520fb08b0bf87f9#additions-to-symbol)
* [`SuppressedError`](https://github.com/tc39/proposal-explicit-resource-management/tree/22f80f76fe9ed4bd08faff076520fb08b0bf87f9#the-suppressederror-error)
* [`Iterator.prototype[Symbol.dispose]`](https://github.com/tc39/proposal-explicit-resource-management/tree/22f80f76fe9ed4bd08faff076520fb08b0bf87f9#iteratorprototypedispose)
* Possibly [a new interface called `Disposable`](https://github.com/tc39/proposal-explicit-resource-management/tree/22f80f76fe9ed4bd08faff076520fb08b0bf87f9#the-common-disposable-and-asyncdisposable-interface) ([which I think we should consider calling `DisposableLike`](https://github.com/tc39/proposal-iterator-helpers/issues/116))
* [`DisposableStack`](https://github.com/tc39/proposal-explicit-resource-management/tree/22f80f76fe9ed4bd08faff076520fb08b0bf87f9#disposablestack-and-asyncdisposablestack-container-object)

We are in a slightly weird spot here since downlevel emit of `using` is possible, but will require a `lib` of `esnext`.

Given that the 5.1 timeframe will be shorter, it would be reasonable for our first stab at this feature to include only support for `--target esnext`.

Note that since [Async Explicit Resource Management](https://github.com/tc39/proposal-async-explicit-resource-management) has been split off into its own proposal, I'm not suggesting we add it here.

**Comment by Kingwl** [comment]
Does this one accept PRs? Happy to work on this.

**Comment by rbuckton** [comment]
I have already started this effort, but thanks for the interest!

**Comment by rbuckton** [comment]
> * Possibly [a new interface called `Disposable`](https://github.com/tc39/proposal-explicit-resource-management/tree/22f80f76fe9ed4bd08faff076520fb08b0bf87f9#the-common-disposable-and-asyncdisposable-interface) ([which I think we should consider calling `DisposableLike`](https://github.com/tc39/proposal-iterator-helpers/issues/116))

I'm hoping we shouldn't have the same kind of conflict in the future given that `DisposableStack` is the name of built-in class related to this feature. You generally don't perform other operations generically on a disposable like you do for iterators.
