### ISSUE TITLE
Constructor overload not working as expected

### ISSUE THREAD

**Issue by saby22** [microsoft/TypeScript#52965]
# Bug Report

### 🔎 Search Terms

constructor overload type error

### 🕗 Version & Regression Information

Tested between 4.0.5 to 4.9.5 in TSPlayground

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/MYGwhgzhAECCDeAoR1XWAewHYQC4CcBXYXDfACgDMBLfPaALmj32qwHMBKFNTHA4qQo06uRswJt2AGmYBTPgBMA-OJZTOSNNvTYIGEHIB0IDOyq080iAuyLu2gL7IXzxFjkB3OOQBEACzkQU19pX08yEEVfTiA)

### 💻 Code

```ts
class A{

    constructor(first : string)
    constructor(first : string, second? : string){
        console.log(first,second)
    }
}

new A("hello","world")
```

### 🙁 Actual behavior

Got an error saying ``` Expected 1 arguments, but got 2. ```

### 🙂 Expected behavior

Expected the object to be initialized

**Comment by fatcerberus** [comment]
The implementation signature is not used in overload resolution.  You should have written

```ts
constructor(first: string)
constructor(first: string, second: string)
constructor(first: string, second?: string) {
    console.log(first, second)
}
```

Of course in this example you don't need the overload at all.

**Comment by saby22** [comment]
Got it @fatcerberus !

Yes, I agree overload was not really necessary in this example
