### ISSUE TITLE
Enums could have functions

### ISSUE THREAD

**Issue by karlgama** [microsoft/TypeScript#52962]
# Suggestion
## 🔍 Search Terms
enum

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
allow enums when implementing an interface to each value implement the interface individually. But obviously this would be optional if an enum needs to implement the function of the interface only once would it be valid for all values, and only when needed, would each value of the enum implement the function differently
For example, I have a Calculation interface and a tax enum:
```
Calculate interface {
    calculate(value:number):number;
}

enum Tax implement Calculate{
    TAX1{
        calculate(value:number){
            ...calculation logic for tax 1
             },
    TAX2{
        calculate(value:number){
            ...calculation logic for tax 2
            }
        }
    }
```

## 📃 Motivating Example

It is very common in my view to have situations where we will use a String to do something.
For example, a String "Role" that has an authenticate function, and each role, Admin, Support, among others, implements this method differently. However, as it is only one function, creating a whole class just to avoid ifs is strange. In Java, I usually create an interface and an enum that implements this interface, and I only call these enum functions, the classic strategy pattern.
 The Role example is a bit silly, but it's just to illustrate. There was a case where I was working with TypeScript and, in fact, I needed each enum value to implement the same function differently, and that was not an option. So the solution was to create an object where the values were the String that the enum represented and, through toString, search for the key that had the function I wanted in the object. If enums could have different functions for each value, this would not be necessary.

## 💻 Use Cases

In the meantime what I have been doing is receiving a normal typescript enum in the request to avoid typing errors as they are fixed values. And where I really need each value of the enum to implement my interface in a different way, I transform the enum into a string and use it as the key of an object, maybe it's not the best way but it's what has worked

**Comment by jakebailey** [comment]
You checked:

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

But this is non ECMAScript syntax and sugar.

**Comment by fatcerberus** [comment]
> But this is non ECMAScript syntax and sugar.

(so are TS enums but shhhhhhh don't tell anyone :wink: 😄)

**Comment by jakebailey** [comment]
Correct! Which is why we aren't adding anything to them until ECMAScript gets enums, if ever.

**Comment by fatcerberus** [comment]
(I was just joking around in case it wasn't clear)

**Comment by RyanCavanaugh** [comment]
For better or worse, this is already possible
```ts
enum A {
    b, c, d
}
namespace A {
    export function fn() {
        
    }
}
```
We wouldn't consider adding the method syntax to the enum declaration itself for the reasons stated above.

**Comment by fatcerberus** [comment]
@RyanCavanaugh just fwiw it seemed like the feature request was more about putting methods on the enum members themselves (i.e. `A.b.fn()`), which AFAICT is not possible.
