### ISSUE TITLE
Mixin with a Generic Constraint on a constructor argument not working as expected

### ISSUE THREAD

**Issue by akshatdubeysf** [microsoft/TypeScript#52971]
# Bug Report

### 🔎 Search Terms

- mixin
- generic constraint on mixin
- mixin type inference

### 🕗 Version & Regression Information

- This issue is present at least from version 4.0.5 up to 4.9.5.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.0.5#code/MYGwhgzhAEAqCmEAuBZA9gE3iaBvAUNEdAHZgC28A-AFzTIBOAliQOYDc+AvvvkgJ4AHeNADCaEowCuwJGgYAeWAD5oAXlLwA7tAAUAOkNgGrCHTAl+AbQC6ASnWrYnfADMpJWUwnRyTAB4sAIJK0PD+SPAkGDAIyOhYIMq6AEaQ8HTikkgMMnKKKnaZEtKy8qEAZHhMGLT0OSysXKp4hMSgkDAAIlLk5PxhEVEx0GkQIgTEU9A1dYyNnFM8UwzwSFIMJNA9fQOQYiU5eeWw0FW4s3TzbM2cXEA)

### 💻 Code

```ts
class TestModel {
    name?: string;
}

type Constructor<T> = new (...args: any[]) => T;

function mixinA<T extends TestModel>(base: Constructor<T>)  {
    class Dummy extends base {
        id?: string;
    }
    return Dummy;
}
```

### 🙁 Actual behavior

This throws the following error - 
```
Class 'Dummy' incorrectly extends base class 'T'.
  'Dummy' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'TestModel'.
```

But if I change the code to the one below, it works fine ->

```ts
function mixinA<T extends Constructor<TestModel>>(base: T) {
    class Dummy extends base {
        id?: string;
    }
    return Dummy;
}
```

### 🙂 Expected behavior

T could be instantiated with a different subtype should not affect the Dummy extending constructor of Class T, and if it did, the second code sample should also not work

**Comment by RyanCavanaugh** [comment]
This is a correct error; it's effectively warning you about this case
```ts
class Other extends TestModel {
    id: number = 42;
}

const p = mixinA(Other);
```
If you want to proceed anyway, I would write
```ts
    class Dummy extends (base as typeof TestModel) {
        id?: string;
    }
```

**Comment by akshatdubeysf** [comment]
@RyanCavanaugh thanks, I think I get why it could be wrong, but then isn't that true when I am using it like this as well -

```ts
function mixinA<T extends Constructor<TestModel>>(base: T) {
    class Dummy extends base {
        id?: string;
    }
    return Dummy;
}

class Other extends TestModel {
    id: number = 42;
}

const p = mixinA(Other);

```

**Comment by akshatdubeysf** [comment]
@RyanCavanaugh I think the original problem remains, right? Why is this marked working as intended?

**Comment by akshatdubeysf** [comment]
@RyanCavanaugh or any one else in the team, can anyone please help 🙁
