### ISSUE TITLE
Declaration files wrong generated import for indirectly referenced types

### ISSUE THREAD

**Issue by ernestostifano** [microsoft/TypeScript#52970]
# Bug Report

### 🔎 Search Terms

- `monorepo`
- `wrong generated import path`
- `broken declaration files`
- `generated relative import`

### 🕗 Version & Regression Information

- This issue is present at least from version `4.8.3` up to `4.9.5`.

### ⏯ Playground Link

[Reproduction Repository](https://github.com/ernestostifano/typescript-generated-import-issue)

### 💻 Code

***(NOTE: See more examples and detailed reproduction instructions in linked repository.)***

### `@scope/package-a-export`

***defines/types.ts***
```ts
interface IEntity {
    propA: string
    propB: number
    propC: boolean
}

export type {IEntity};
```

***utils/create-entity.ts***
```ts
import type {IEntity} from "../../defines/types";

function createEntity(): IEntity {
    return {
        propA: '',
        propB: 0,
        propC: false
    }
}

export {createEntity};
```

***index.ts***
```ts
import {createEntity} from "./utils/create-entity";
import type {IEntity} from "./defines/types";

export {createEntity};
export type {IEntity};
```

### `@scope/package-a-import`

***index.ts***
```ts
import {createEntity} from '@scope/package-a-export';

const entity = createEntity();

export {entity};
```

### `RESULT`

***types/index.d.ts***
```ts
declare const entity: import("../../package-a-export/types/defines/types").IEntity;
export { entity };
//# sourceMappingURL=index.d.ts.map
```

**The following statement `import("../../package-a-export/types/defines/types")` is broken. Will only work locally, but not if the package is installed elsewhere.**

### 🙁 Actual behavior

See `RESULT` above.

### 🙂 Expected behavior

See `README.md` file in linked repository for additional details.

**Comment by RyanCavanaugh** [comment]
The linked repo doesn't build for me under the provided instructions, and seems to be relying on third-party build tools (Babel). Can you post an isolated (and, ideally, smaller?) repro?

**Comment by ernestostifano** [comment]
Hi @RyanCavanaugh! Actually that is the minimum reproducible example I could create (I did it from scratch just for this issue). Just added multiple examples of the same issue.

Why isn't it building? Are you running the `build` command on a `bash` like environment? If not, you'll need to go through each package and run `yarn build:code` and `yarn build:types` separately (or maybe replace `&&` with `&`).

I could remove `Babel` and use `TypeScript` to generate JS files if you want, but it should not interfere with the issue (the issue is on emitted declaration files).

I can't avoid the monorepo altogether since the issue presents when importing from a different package, so I would need to create multiple repositories to do the same. I remember seen a similar issue when imports from other installed packages got relative imports like `import(../../node_modules/some/dir/file.js)` instead of the package alias (will link it if I find it), which could be related.

**Comment by ernestostifano** [comment]
@RyanCavanaugh mmm, that's really strange...

None of that is part of the repo. You should not even have a `node_modules` directory, since it uses `pnp`.

Maybe TypeScript is trying to acquire those types from somewhere else?

After cloning, you should just do `yarn` + `yarn build`.

**Comment by RyanCavanaugh** [comment]
I guess yarn was getting confused by a stray package.json in a parent directory.

OK, so the root cause here is a few levels deep

When synthesizing names for declaration files, TS has a few rules:
 * Use an existing name for a type if possible
 * Don't synthesize module names which we aren't very sure are OK
 * Importing a (reachable) original type definition is better than importing a re-export of it

The first rule is why, in general, if you have a strongly-preferred name for a type, you should always import it.

Regarding the second rule, TS isn't sure if `@scope/package-a-export` is an OK name to use or not. You're "missing" this from your tsconfig.base.json to enable it:
```
        "baseUrl": ".",
        "paths": {
            "@scope/*": ["packages/*"]
        }
```
In fact, this project doesn't even build under normal `tsc` without this entry; I suspect yarn might be messing with something since I know yarn does patch tsc to cause behaviors not under our control (probably including this one). So tsc is trying to synthesize a name for something it couldn't resolve in the first place (this is why I didn't want to look at a build involving Babel -- it can hide other errors, including important ones).

The third rule is basically a blocker if you want to prefer the re-export over the original, so really the whole thing here is moot and you should probably just write the import.

**Comment by ernestostifano** [comment]
@RyanCavanaugh thank you for your detailed explanation, it is nice to get some hints about the underlying logic.

Inspired by you, I am now using `tsc` (with `references` and `paths`) in parallel just to check that nothing is broken between packages.

I have thought about it for some time and now I have the following doubts. I would be very grateful if you had some time to share some inputs.

## **1**

Now relative imports like `import("../../package-a-export/types/defines/types").IEntity` have disappeared from generated declaration files. New imports looks more or less like this: `import("@scope/package-a-export/types/defines/types").IEntity` which is better, but I wonder, **is this compliant with ESM specifications?** In theory, it should be forbidden to import something from a file that is not explicitly defined in the `exports` property of the `package.json`.

## **2**

There are situations (not in the linked repository) in which a certain package `B` imports from a certain package `A` as follows:

`@scope/b`
```ts
import {somethingA, somethingB} from '@scope/a';

const somethingC = {
    content: [somethingA, somethingB]
};

export {somethingC};
```

Now, imagine that `somethingA` and `somethingB` were typed inside `@scope/a` using a type from an external library:

`@scope/a`
```ts
import type {ExternalType} from 'external-library';

const somethingA: ExternalType = {};
const somethingB: ExternalType = {};

export {somethingA, somethingB};
```

The thing is that when you build `@scope/b`, the generated declaration files now include an explicit import of `ExternalType` from 'external-library'. The problem is that 'external-library' is a dependency of `@scope/a`, not of `@scope/b` (not included in package.json). This makes `@scope/b` not usable, because `external-library' cannot be found.

I understand that there is no simple way to fix this without tweaking the produced declaration files in `@scope/a`, which I understand goes against TypeScript philosophy, to include an export that originally didn't exist, but it worries me that this error can only be caught when consuming `@scope/b` and not when building it (**the output is technically broken, but the build does not fail**).

Am I missing something?

## **3**

I was trying to make the monorepo work even when packages are not built. So, if I import something from another package and the source code of that package changes, I will get immediate feedback on the importing package, without needing to build the other package again.

Now, it seems that with a combination of `references` and `paths`, I've managed to achieve my goal. Specifically, I'm using the following configuration for `paths` as suggested:

```json
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "@tppm/*": ["./packages/*"]
        }
    }
}
```

However, when packages are not built, I'm having some issues with WebStorm (I only get partial information about imported stuff), and sometimes I even get some errors from TypeScript itself complaining that some imported stuff has type `any`.

Now, if I add this:

```json
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "@tppm/*": ["./packages/*", "./packages/*/src"]
        }
    }
}
```

Everything seems to work seamlessly.

Would this make any sense to you? Can be considered a safe pattern?

Thank you very much for your time, I am really looking forward to learn more about TypeScript internal mechanics.

**Comment by RyanCavanaugh** [comment]
Honestly, I appreciate the feedback but these are all very very involved questions that I don't personally have time to address right now.

**Comment by ernestostifano** [comment]
@RyanCavanaugh I perfectly understand. Thanks for your reply. See you around!
