### ISSUE TITLE
using "throw" to prevent undefined but ts still says it is possibly undefined

### ISSUE THREAD

**Issue by oniiichannnn** [microsoft/TypeScript#52977]
# Bug Report

### 🔎 Search Terms
typescript throw doesn't return

### 🕗 Version & Regression Information

Typescript: Version 4.9.3
Node: v16.16.0

### ⏯ Playground Link

The code required will be too long, github source: https://github.com/oniiichannnn/Seika/blob/main/src/Util/Discord/Basic%20Utils.ts#L363

### 💻 Code

Reproduced code:
```ts
function dosumthingpls (v:number|string|undefined, options: {d: boolean}):number {

    if (v === undefined && options.d) {

    } else
    if (v === undefined) throw internal({m:"undefined"});

    return dosumthing(v);

    function dosumthing (value: number|string):number {
        return 0
    };

    function internal (e: {m: string}) {
        return new Error(e.m);
    }
}
```
If you remove the `else` then the error goes away

### 🙁 Actual behavior

Typescript is saying that `source` will be undefined despite there being a if statement to validate if source is undefined. It ignores the throw.

### 🙂 Expected behavior

The error is supposed to not happen because `if source is undefined` then the code will be `throw`ed and not executed further. So theoretically there shouldn't be a possibly of `source` being undefined.

**Comment by fatcerberus** [comment]
```ts
if (v === undefined && options.d) {
    // no throw here
} else if (v === undefined) throw internal({m:"undefined"});
return dosumthing(v);
```

Assuming this repro code is representative, then if `v` is `undefined` and `options.d` is truthy, the `else` case will not be reached and control will fall through to `dosumthing(v)` -- with `v = undefined`.  The error is correct.
