### ISSUE TITLE
Bad path joining for error message on existing 'tsconfig.json'

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5298]
Expected:

```
error TS5054: A 'tsconfig.json' file is already defined at: 'C:\Users\drosen\foo\tsconfig.json'.
```

Actual:
```
error TS5054: A 'tsconfig.json' file is already defined at: 'C:\Users\drosen\foo/tsconfig.json'.
```

**Comment by eimfach** [comment]
I will fix it :)

**Comment by eimfach** [comment]
Okay seems to be fixed by @brettm523

**Comment by DickvdBrink** [comment]
the PR is merged, so this one is fixed and can be closed?

**Comment by mhegazy** [comment]
Thanks @DickvdBrink!

**Comment by gcamana** [comment]
error TS5054: A 'tsconfig.json' file is already defined at: 'D:/Frontend/TypeScript/1.Intro_TS/tsconfig.json'.
OS Windows 10

as I fix it? I have the same problems
