### ISSUE TITLE
Emitter emits empty statement loop bodies on new line

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#5299]
http://www.typescriptlang.org/Playground#src=while(true)%3B%0D%0Aif%20(true)%20%7B%0D%0A%09%0D%0A%7D 

While I conceptually understand why it emits like it currently does, It's odd formatting to place the semicolon alone on a new line.

**Comment by mhegazy** [comment]
We have almost always rejected output formatting issues. The guidance is to use a js bueatifier if output formatting is important to you.
