### ISSUE TITLE
Missing interface definition for Highlight API

### ISSUE THREAD

**Issue by eladsadeh** [microsoft/TypeScript#53003]
# Bug Report

### 🔎 Search Terms

- Highlight
- Highlight API
- CSS custom highlight api

### 🕗 Version & Regression Information

Version 4.9.5

This happen in the 'Nightly' version as well.

Please keep and fill in the line that best applies:

- This is a crash
- This changed between versions ______ and _______
X This is the behavior in every version I tried, and I reviewed the FAQ for entries about: Could not find anything relevant.
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

  A link to a TypeScript Playground "Share" link which shows this behavior: http://www.typescriptlang.org/play/?ts=Nightly

### 💻 Code

```ts
const hl = new Highlight()
```

### 🙁 Actual behavior

`Cannot find name 'Highlight'.(2304)`

### 🙂 Expected behavior

Should return a newly created `Highlight` object.

[Constructor](https://developer.mozilla.org/en-US/docs/Web/API/Highlight#constructor)
[Highlight()](https://developer.mozilla.org/en-US/docs/Web/API/Highlight/Highlight)

```
let hl = new Highlight();
console.log(hl) // Highlight {priority: 0, type: 'highlight', size: 0}
```

**Comment by RyanCavanaugh** [comment]
Experimental features are not included in the built-in DOM

**Comment by eladsadeh** [comment]
Thanks for the fast reply!

**Comment by Emberfire** [comment]
My understanding is the Custom Highlights API has left the experimental stage, with only Firefox for desktop and Android lacking support for it in their respective official versions. Are there any plans to add it to the DOM definitions?

**Comment by Micka33** [comment]
Looking for it as well.

Is there anyway to get it working until it is officially supported?

**Comment by Kreash** [comment]
You can create a d.ts file for you project

```typescript
declare class Highlight {
  constructor(...range: Range[]);
}

declare namespace CSS {
  var highlights: Map<string, Highlight>;
}
```

**Comment by acherkashin** [comment]
@RyanCavanaugh I guess this issue should be reopened, as this API has really good support in browsers now.

https://developer.mozilla.org/en-US/docs/Web/CSS/::highlight

<img width="1423" alt="image" src="https://github.com/microsoft/TypeScript/assets/9947582/1741df9f-c003-4eab-8895-b442d581f946">

**Comment by Momomash** [comment]
> @RyanCavanaugh I guess this issue should be reopened, as this API has really good support in browsers now.
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/::highlight
> 
> <img alt="image" width="1423" src="https://private-user-images.githubusercontent.com/9947582/318734006-1741df9f-c003-4eab-8895-b442d581f946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDIzMzEsIm5iZiI6MTcxMjE0MjAzMSwicGF0aCI6Ii85OTQ3NTgyLzMxODczNDAwNi0xNzQxZGY5Zi1jMDAzLTRlYWItODg5NS1iNDQyZDU4MWY5NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTEwMDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJhNjU5YzIwZmQ2OWU1ZGRhMDM5ZmRmNzgyMGVlN2NhMjM0ZDkwM2Y3NmYwOGVlMzVhZTY2YmIwODFkOTFkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gY8B2ujIbGXqr1Do4bK0WiqNSB_7T1kX_v2OGQd0oes">

@ acherkashin  https://github.com/microsoft/TypeScript/issues/58051

**Comment by acherkashin** [comment]
@Momomash Спасибо) Thanks!

**Comment by yg-i** [comment]
All the "set-like" methods/properties (size, add, delete, clear, entries, ...) are still missing from the interface.

```
/** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Highlight) */
interface Highlight {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Highlight/priority) */
    priority: number;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Highlight/type) */
    type: HighlightType;
    forEach(callbackfn: (value: AbstractRange, key: AbstractRange, parent: Highlight) => void, thisArg?: any): void;
}

declare var Highlight: {
    prototype: Highlight;
    new(...initialRanges: AbstractRange[]): Highlight;
};
```

See: https://developer.mozilla.org/en-US/docs/Web/API/Highlight
