### ISSUE TITLE
Uncaught Error: Debug Failure. False expression: Unexpected multiple outputs for the file: module.d.ts

### ISSUE THREAD

**Issue by tommyZZM** [Microsoft/TypeScript#5302]
````typescript
var result = ts.transpile("export function haha(){}"
                  ,{ module: ts.ModuleKind.CommonJS , declaration:true});
 console.log(result);
````

i want to use transpile api to generate a d.ts only,how can i do this?

it just show the error as title

**Comment by mhegazy** [comment]
`transpile` is only for transforming a .ts to a .js. This is a syntactic trnasformation, with no type information available, i.e. no need to have your dependent modules, types, even no lib.d.ts. if you are emitting a .d.ts you need to have all the types, for this you need to go through the normal compilation, using `createProgram`, see https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler for more information.
