### ISSUE TITLE
[request] Empty array failure at compile time as opposed to runtime

### ISSUE THREAD

**Issue by osfprieto** [microsoft/TypeScript#53021]
# Suggestion

I've been involved in livesite investigations in our product a couple of times this year that turn out to be rooted in gaps in the code that are flagged at runtime as opposed to compile time. Having these would help prevent these from turning into livesite issues for us.

Here's a sample of code that compiles properly but has runtime issues

https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQA4FcBGIAlsNHmAE4Bc0EALuYQHYDm0AvNAEScDcqAvqlTB4jOtAC2ATwCC5cmCnUE8ANoBddtA18RY+CACmAOhDxmACmlyFU1QAZ1xsuQCUPIA

## 🔍 Search Terms

empty array failure at runtime

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code (NOT SURE)
* [X] This wouldn't change the runtime behavior of existing JavaScript code (NOT SURE)
* [ ] This could be implemented without emitting different JS based on the types of the expressions (PROBABLY NOT SINCE LOTS OF ASSUMPTIONS AROUND ARRAYS MAY NEED TO BE UPDATED)
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'd like this to fail at compile time rather than runtime:

https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQA4FcBGIAlsNHmAE4Bc0EALuYQHYDm0AvNAEScDcqAvqlTB4jOtAC2ATwCC5cmCnUE8ANoBddtA18RY+CACmAOhDxmACmlyFU1QAZ1xsuQCUPIA

## 📃 Motivating Example

Had several livesite issues that reflect gaps in our code show up only at runtime instead of dev time.

**Comment by fatcerberus** [comment]
https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

**Comment by osfprieto** [comment]
Thank you!

**Comment by osfprieto** [comment]
Enabling the rule on the playground does in fact address my request just as I'd expect it.

https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/MYGwhgzhAEBiD29oG8BQ0PQA4FcBGIAlsNHmAE4Bc0EALuYQHYDm0AvNAEScDcqAvqlTB4jOtAC2ATwCC5cmCnUE8ANoBddtA18RY+CACmAOhDxmACmlyFU1QAZ1xsuQCUPIA
