### ISSUE TITLE
Assertion fails when conditional on other variable

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#53023]
# Bug Report

### 🔎 Search Terms

Conditional assertion, flag, type guard

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAgBYFMA2mEAoCUyA3sAJBRIDOMycEADmDQLzIAmCUYAtuhDADoA5uhgBRTOl78AQgE8Akm1zIA5JQS8AtHUYxVyfAG5gZChGrIAbgENMYdMla6mtCzBvR0CEMgASACoAsgAyCgxMElJ8NAD8bnoCtvaOAFxqqibkVDTJDjIICJhO1nYOTsysqgbxIHaUacgwAE4OJmY5yABGNs0lHFzSgiLikkPySiqqCDAYzToR+oZkcL4qeegFRRWsdZgNyABkh8gAhLg9fXTUnlDevoGh4XpRQ4SEJKSkzaJgzRBZAC+plIq2Q6zKm0KxUqu3qjg+ZFIlySkJKqgA7ghmpg2JkyMDgUA

### 💻 Code

```js
function hello() {
	const input = document.getElementById( 'some-input' );

	const value = input instanceof HTMLInputElement ? input.value : '';
	const valueBool = value === '' ? false : true;

	const bar = document.getElementById( 'other-input' );
	if ( valueBool === false && !(bar instanceof HTMLInputElement) ) {
		return;
	}

	if ( valueBool === false ) {
		bar.value = 'world';
	}
}
```

### 🙁 Actual behavior

'bar' is possibly 'null'.(18047)

### 🙂 Expected behavior

No error

**Comment by RyanCavanaugh** [comment]
There isn't special logic in place to recognize repeated checks for the same variable as being irrelevant to CFA

**Comment by RyanCavanaugh** [comment]
The clearer version of this code checks as expected
```ts
function hello() {
	const input = document.getElementById( 'some-input' );

	const value = input instanceof HTMLInputElement ? input.value : '';
	const valueBool = value === '' ? false : true;

	const bar = document.getElementById( 'other-input' )
	if ( valueBool === false ) {
		if (bar instanceof HTMLInputElement) {
			bar.value = 'world';
		} else {
			return;

		}
	}
}
```

**Comment by RyanCavanaugh** [comment]
It'd complicate CFA quite a bit and would hurt performance overall, so I don't think it's in the cards.

Honestly I've never seen a sample where the real clearest version of the code involves a repeated check like this.
