### ISSUE TITLE
Mechanism for package authors to give auto-import hints

### ISSUE THREAD

**Issue by Twipped** [microsoft/TypeScript#53037]
Apologies if this exists and I just couldn't find documentation on it. We have several in-house npm packages to offer common functionality across our codebases. Each of these packages defines subpath `exports` entries to directly target individual functions and components, in addition to getting everything from the root entry. To use an example with MUI, you can do either of these:

```js
import { Grid } from '@mui/material';
```
or
```js
import Grid from '@mui/material/Grid'`
```

The problem is, the auto-import completion rarely even lists the later, just the former, or sometimes, when it does go deeper, it tries to import the direct file (eg, `@mui/material/node/Grid/Grid.js`) instead of using the subpath export.

It would be very helpful if I, as a package author, could give weight to the exports so that I can tell vscode "this is actually the better path to use for suggesting this export."

**Comment by DanielRosenwasser** [comment]
Something in the same vein that I've been considering is the ability for package authors to specify a default name for namespace auto-imports (#52527, #23830).

**Comment by Andarist** [comment]
> Something in the same vein that I've been considering is the ability for package authors to specify a default name for namespace auto-imports (https://github.com/microsoft/TypeScript/issues/52527, https://github.com/microsoft/TypeScript/issues/23830).

Oh yes 🙏 this would be super awesome. In a similar vein... some consumers prefer namespace-based imports so it would be cool to have that configurable from the consuming side of things as well.

**Comment by DanielRosenwasser** [comment]
Is there any reason that you prefer the subpath export?

**Comment by Andarist** [comment]
Hm, I didn't exactly have subpath exports/imports in mind. Just that in some codebases `import * as React from 'react'` is preferred. It would be cool if auto-importing `useState` could result in this:
```ts
// pre
useStat/*cursor*/

// post
import * as React from 'react'
React.useState/*cursor*/
```

**Comment by DanielRosenwasser** [comment]
Sorry, not you @Andarist, I meant that more as a question for @Twipped.

**Comment by Twipped** [comment]
You know what, I just realized I opened this on the TypeScript repo, when I meant to open it on vscode... I really don't know how that happened. I guess it still kinda applies, however.

@DanielRosenwasser Importing from root exports increases overhead in testing and build processes due to increased IO churn and tree-shaking. We actually have a linting rule to prevent importing from several root packages, like `@mui/icons-material` where the root has HUNDREDS of named exports. We saw a significant reduction in CI execution time after adding that rule to our codebases.

So vscode's auto-import always grabbing the root increases development time, since it immediately gets flagged by eslint.

**Comment by Twipped** [comment]
@RyanCavanaugh ohh, that might indeed solve it. I'll take a look today

**Comment by Twipped** [comment]
I figured it out! I can actually solve for this, by defining a `typesVersions` entry in my package.json.

```
  "typesVersions": {
    "*": {
      "*": ["./dist/*.d.ts"]
    }
  },
```

This gets vscode to properly recommend the subpath export instead of the root export. Problem solved!

**Comment by joshjg** [comment]
> I figured it out! I can actually solve for this, by defining a `typesVersions` entry in my package.json.
> 
> ```
>   "typesVersions": {
>     "*": {
>       "*": ["./dist/*.d.ts"]
>     }
>   },
> ```
> 
> This gets vscode to properly recommend the subpath export instead of the root export. Problem solved!

I'm not sure how that would solve the issue (it doesn't for my case)
