### ISSUE TITLE
Bad type inference in union type

### ISSUE THREAD

**Issue by andresmatasuarez** [microsoft/TypeScript#53033]
# Bug Report

I'm defining a type which is a union of 4 different combinations of the same object and its properties. Sadly, when using it, I'm getting inaccurate type inferences, at least not as accurate as I would expect.

### 🔎 Search Terms

union, discriminated union, discriminator, type suggestion for union types

### 🕗 Version & Regression Information

This is the behaviour in every version I tried, and I reviewed the FAQ.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA4hwGEIBtkDUCGyCuEA8AKgHxQC8UAFBgE4DmAXFAQJRkkYB2IA3AFC8B6AFRDeUIVADKAewC20AMbSOwCAA9gjYAAsAlgGcooSFAAmEAGa6OEQ5yjXV1CxgXQL06lCU5ZHQ9ZQGEYYAEbI0DoYwEHU0PqewGERAHRiouJMeobGivah0HEYpkF2UNgcuspQ0hbiQsrIIFAe2F61QagiRtrQproWFhBxKlD62hiQ+uk90NKhAFYQCjGyurTaMRMAbhAANFCyGNZNUKEY+hAl1TrQYHGXHG41dTrSl1AAzFD30pDUwF0tjSmXSAl4uSkiWSEAQ0l8HEkCl6R0IBzQJFIYigAB8oABvbFQYlQWjwTA4CAAfkYNl21D4JJJZOAMgBFNwjAo1GkAHdGCw2OUOABrDh8jiMplQJCoRhwRAodBYXB4fE1ajraxYAXcKDbFUQRgVcxWGwlAC+RClxIt2LxhOlpPJhq5PP5TFYpBIaBtzPgbOAHKNlHdAq9JAqYolfuJsuQNKgdOGfrtxIdRP9Qddob54aFvszxJZgeDieTDKLMqV8vg8eDao1Wo4OqYeoNlMYaCgVtT9oJVZZwbdec9BdjztZiTLtIg9In8fLc5TmYtfEEIhmBHA7k8UAABp5m1h90EOCV9x3cKeaNBrENqHEShczhBrLQXgfOCBT5Deb0OFmEAZnGaRsGQEoClKFp4WQPlDCoQx-mdGxNQUQwCDPEo0GYegZmJQ9NVobVkFPUhvQJIJGH0YBNQ4Wg9VCWlsFkAovDTCQCKvCBTxJciSA4Fi2JmGYAAUIguaBxVUHpoliWgWIgUZD0WU8On3IdDQoeYFmYU8DFfd8HA4B8n28Tw4hWU5AD4NwAUXbBXglH8GIDU1GEAH1eV0HR3Ok9zpBFdzcn0RhAxhOEESRFEMEbDBqNo99GOY1jhh7A5BJS6hMQHYsXU7SgdIjL49mxeMuXVI9iJbZADm4nsisE1ASrXfgBAEMhyM6rrup6nrBHagAhFA+QcMpeU8EUjPUDBZDACJP0he9hiU54wOAfRdHMWZ+uFKpAMhCh9zC8JYXhFjEWRCAjn3Zgdt6+6Hs61r2oIbJRtmMZlmUEonJo7zcFGdTjoiCLzqiq6MFPU1rCuaDvMMCUjB3HbgGkMZtBGqIYluH4eRO2R3qUNZ6JaHkCZxio9ocdaUAsdLpGx3pjP6bZNuwLAkamNJIVeiBJC+884Wc-6lOAABBOCbDRKAMTIHLJ2HXMPUFCjC1yqd2UNJd51KmtYDrJUGwqoiSN1fUc27XteBanaAEl9rehRJIOYLYjvEzhjMojNkc5QaPNtyTs87ztH8wLgoFXp+ac0whb+4AAfFyX8HVOKxgS+ikqTITUotdKc6yuXHQVnNtMWIrPhKuM9YoY3jxq83KXqoVGpq63uCAA)

### 💻 Code

Code looks bigger than it actually is because I left some comments explaining things as clear as possible and also because I included an example in which type inference works as expected (`TheSecondConstituentAlone` and `variable_with_ok_types` near the end of the snippet)

```ts
type GetCellValue<T> = (arg: T) => any;

/**
 * Some context: this type defines an interface for columns in a table that are sortable.
 *
 * This type can be read as a union of **only four of all** the different shapes
 * the object might have, mainly based on the presence of those 3 properties.
 * 
 */
type SortableColumnSchema<T, V> =
  | {
      getValue?: never;
      getSortValue: (row: T) => unknown;
      Cell: GetCellValue<{ original: T; value: undefined }>;
    }
  | {
      getValue: (row: T) => V;
      getSortValue: (row: T) => unknown;
      Cell?: never;
    }
  | {
      getValue: (row: T) => V;
      getSortValue?: never;
      Cell: GetCellValue<{ original: T; value: V }>;
    }
  | {
      getValue: (row: T) => V;
      getSortValue?: never;
      Cell?: never;
    };

/**
 * Type for `original` and `value` are inferred as being of `any` type when they
 * should be as follows (as per generics T and V):
 *   `original` ==> { a: string; b: number }
 *   `value`    ==> number
 * 
 * Please note that argument `obj` of `getValue(obj)` is being inferred correctly 🤔
 */
const variable_with_not_ok_types: SortableColumnSchema<{ a: string; b: number }, number> = {
  getValue: (obj) => 3,
  Cell: ({ original, value }) => null,
};
```
Below is a working example of type inference outside the union type (`SortableColumnSchema`)

```ts
// This is the second constituent of `SortableColumnSchema` defined as its own type
// to show that the problem is coming from the union itself, not the individual types.
type TheSecondConstituentAlone<T, V> = {
  getValue: (row: T) => V;
  getSortValue?: never;
  Cell: GetCellValue<{ original: T; value: V }>;
};

// In this case, types are inferred right
const variable_with_ok_types: TheSecondConstituentAlone<{ a: string; b: number }, number> = {
  getValue: (obj) => 3,
  Cell: ({ original, value }) => null,
};
```

### 🙁 Actual behavior

In the snippet above, types for the arguments of `variable_with_not_ok_types.Cell` are inferred as `any` and `any`, respectively, when `obj` in `variable_with_not_ok_types.getValue(obj)` is correctly inferred as `{ a: string; b: number }`. 

### 🙂 Expected behavior

In the snippet above, types for the arguments of `variable_with_not_ok_types.Cell` should be inferred as `{ a: string; b: number }` and `number`, respectively.

**Comment by RyanCavanaugh** [comment]
Duplicate #47599, specifically the fourth suggestion bullet point there

**Comment by ahejlsberg** [comment]
@RyanCavanaugh I think the issue here is that the union in question has no discriminant property, so contextual typing doesn't pick out a specific case. The example works as expected if I manually add a discriminant property.

**Comment by ahejlsberg** [comment]
When analyzing the declaration

```ts
const variable_with_not_ok_types: SortableColumnSchema<{ a: string; b: number }, number> = {
  getValue: (obj) => 3,
  Cell: ({ original, value }) => null,
};
```

we attempt to discriminate the contextual type `SortableColumnSchema<...>` by the property values specified in the object literal. Because of the potentially circular nature of the analysis (the property values are contextually typed by the same type we're trying to discriminate based on them), we limit this to only consider literal values (e.g. `"foo"` or `123`), so in this example nothing qualifies as a discriminant. When I add an explicit discriminant property with a literal type it works as expected, but of course that requires the user to explicitly include that discriminant in the object literal.

**Comment by andresmatasuarez** [comment]
so what I'm trying to achieve here is only possible by means of an explicit literal discriminant property? will the referenced issue https://github.com/microsoft/TypeScript/issues/47599 not address this?

**Comment by andresmatasuarez** [comment]
@ahejlsberg so what I'm trying to achieve here is only possible by means of an explicit literal discriminant property? will the referenced issue https://github.com/microsoft/TypeScript/issues/47599 not address this?
