### ISSUE TITLE
"moduleResolution": "node" usage and absolute/relative imports

### ISSUE THREAD

**Issue by rolandjitsu** [Microsoft/TypeScript#5304]
I have recently ran into some issues after having added `"moduleResolution": "node"` to my `tsconfig.json`:
```js
{
	"compilerOptions": {
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"module": "system",
		"moduleResolution": "node",
		"noImplicitAny": false,
		"outDir": "dist",
		"rootDir": "./src",
		"sourceMap": true,
		"target": "es5"
	},
	"exclude": [
		"node_modules"
	]
}
```
The folder structure of the project looks like:
```
src/
    app/
        components/
            app/
                app.ts
                app.html
                app.css
        components.ts
        ...
    common/
        animation.ts
        ...
```
The problem is that when I `import { Animation } from 'common/animation';` it tells me that it cannot find the module, so I have to use `import { Animation } from '../../../common/animation';`. Is it really necessary to have the path as such? And why does it not try to resolve the `common/animation` relative to `rootDir`?

**Comment by vladima** [comment]
node module resolution mimics the way how node looks for modules in runtime (resolution algorithm can be found [here](https://github.com/Microsoft/TypeScript/issues/2338)). In your case name is not relative - module will always be searched as node module using folder walk and lookup inside `node_modules` folder. In your case you can specify `moduleResolution` as `classic` to use pre-TypeScript 1.6 module resolution logic. Also we have a proposal for [path mappings based resolution](https://github.com/Microsoft/TypeScript/issues/5039) which I think should do exactly what you need. 

Out of curiosity, why do you want to use `node` module resolution in the first place?

**Comment by rolandjitsu** [comment]
I see, makes sense. It is because of Angular 2, it looks like the type definitions work better if I use this option, whereas every time I use the classic resolution I get into trouble with some typings. But it looks like [5039](https://github.com/Microsoft/TypeScript/issues/5039) will solve my issue. Is there a eta on that? Or is it available on the nightly builds?

**Comment by vladima** [comment]
we planned to start working on this issue quite soon

**Comment by rolandjitsu** [comment]
That sounds great. Looking forward :+1:

**Comment by meriturva** [comment]
Any news here? With angular2 success i think will be really important to resolve modules starting to rootDir with node moduleResolution setting.

**Comment by amb-it-ion** [comment]
Same here - we are doing really fancy stuff and need more flexibility regarding import paths. Your suggestion regarding paths similar to systemjs import settings in 2338 would help a lot!

**Comment by sanex3339** [comment]
Same problem. Any solution?

**Comment by mhegazy** [comment]
please see the documentation in  #5039, and the implementation should be in `typescript@next`.
