### ISSUE TITLE
TS syntax highlighting messed up in VS2022 after update to 17.5.x

### ISSUE THREAD

**Issue by jbertagnolli** [microsoft/TypeScript#53046]
After taking the VS2022 update 17.5.0 on 2/28/2023, syntax highlighting in Typescript became wonky, as can be seen in this screenshot from an Angular component:

![2023-03-01 12_00_04-ClientApp - Microsoft Visual Studio](https://user-images.githubusercontent.com/94921837/222223731-83afdadb-0b3b-4acc-986e-3f57f4bc55b2.png)

The issue is still present after taking the 17.5.1 update today (3/1/2023).

My coworker who didn't take the 17.5.1 update was able to rollback to 17.4.x to confirm that everything works fine there.

**Comment by sheetalkamat** [comment]
This seems to work correctly

![image](https://user-images.githubusercontent.com/8052792/222236233-c53f0c12-b6c4-44a9-9a5e-08e936c3a649.png)

**Comment by jbertagnolli** [comment]
> This seems to work correctly
> 
> ![image](https://user-images.githubusercontent.com/8052792/222236233-c53f0c12-b6c4-44a9-9a5e-08e936c3a649.png)

Yeah it's definitely not working correctly. Both me and my coworker have extensive syntax highlighting issues that started with 17.5.0. I'll try and see if I can come up with steps to reproduce.

**Comment by jbertagnolli** [comment]
Okay, I've reproduced it within a new Angular project. It seems that type casting with `let myVar = <string>someThing` sets it off.

Steps to reproduce:

1. Create new angular project `ng new proj-name`
2. Open directory in Visual Studio 2022 v17.5.0+
3. Open `app.component.ts` and replace it with the following code:

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'new-ang-2';
  public myProperty: any;

  constructor() {
    let myVar = <string>this.myProperty;

    // some comments
    // some more comments
    // or whatever
    // all code beyond this will have wonky highlighting

    for (let i = 0; i < 100; i++) {
      let myString: string = i.toString();
    }
  }
}
```

Notice incorrect syntax highlighting here:
![2023-03-01 13_24_49-new-ang-2 - Microsoft Visual Studio](https://user-images.githubusercontent.com/94921837/222244148-b7b77a64-5928-4e7f-8a7f-ad5761f578f1.png)

But if I change `let myVar = <string>this.myProperty;` to `let myVar = this.myProperty;`, the issue goes away:

![2023-03-01 13_28_50-new-ang-2 - Microsoft Visual Studio](https://user-images.githubusercontent.com/94921837/222244444-345bef46-808c-4ad2-858a-e82d79fd9e19.png)
