### ISSUE TITLE
"Special" intersections (such as `string & {}`) are no longer order-independent since 4.8

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#53043]
# Bug Report

### 🔎 Search Terms

string autocomplete catch all intersection special

### 🕗 Version & Regression Information

- This changed between versions 4.7 and 4.8

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4&ssl=4&ssc=37&pln=1&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXygApYBzALngHIMQBnDS+AH3kPpi1RPgDJ4BvAL4BKYRQBuOLMABQRSpWHwA9MvgYYAT3jtO3MDgC2ABwghseWvAAWIODNCRYCFOgv4ARsRjkqNeowshEK8Ohp6ohJSsl4KSqrqWmEcXPAGJmbuVrZwQA)

### 💻 Code

```ts
declare function a(arg: 'test' | (string & {})): void
a('') // try string completions here
declare function b(arg: 'test' | ({} & string)): void
b('') // try string completions here
```

### 🙁 Actual behavior

Since 4.8 the second function doesn't provide completions despite using an intersection with the same members as the first one. 

### 🙂 Expected behavior

I would expect both to behave the same, regardless of the order of the intersection members.

**Comment by fatcerberus** [comment]
Was looking for the dupe for like 10 minutes because I *knew* this had come up very recently.  Felt stupid when I finally realized it was your own PR.

**Comment by andrewbranch** [comment]
I’m pretty sure I recall Anders saying this was intentional, though https://github.com/microsoft/TypeScript/pull/49119 doesn’t say outright.

**Comment by Andarist** [comment]
Ye, at the end of the day - I don't think this is a big deal. However, I actually lost like 15 minutes of my life, scratching my head why this thing doesn't work - only to realize later that I've written those two in reverse order. A general rule of thumb is that the order of the intersection shouldn't matter, right?

**Comment by RyanCavanaugh** [comment]
@ahejlsberg any specific thoughts?

**Comment by RyanCavanaugh** [comment]
Very close to making a specific "Not sure if bug, but Andarist can certainly send a PR if interested" label...

**Comment by jakebailey** [comment]
Too late: https://github.com/microsoft/TypeScript/pull/52782

**Comment by ahejlsberg** [comment]
I don't feel strongly about fixing this, but the fix certainly looks fine to me.

**Comment by ahejlsberg** [comment]
That said, we should of course run the full battery of tests on the fix to make sure it doesn't break anything.
