### ISSUE TITLE
Unable to recover type information across spread infer followed by rest infer?

### ISSUE THREAD

**Issue by andrueandersoncs** [microsoft/TypeScript#53050]
# Bug Report

### 🔎 Search Terms

Unknown
Infer
Rest
Spread

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed all the FAQ entries

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230301#code/C4TwDgpgBAQglgOwCYB4AqA+KBeAUFAqNKCAD2AmQGcoBtAOkakQDMIAnKAQXYHMqAuvkIiA-Nz5VhIggC4oCCADcOAbly5QkKAFUEAI0SpMOaURLlKSGvGQoGTVhwn8BGM2JdSZheYpXs6prg0DAA9gCuyACMAEwAzDiwRvbRADRQsRnxbhpa0Hr6kTEJSYUp4VFIcfFYAPR1UFEA1ghhAO4ItEJAA)

### 💻 Code

```ts
type Bind<T> =
    T extends [... infer Args]
        ? Args
        : never;

type Unbind<T> =
    T extends Bind<[... infer Args]>
        ? Args
        : never;

type Bound123 = Bind<[1, 2, 3]>

type Unbound123 = Unbind<Bound123> // unknown[]
```

### 🙁 Actual behavior

```ts
// ...
type Unbound123 = Unbind<Bound123> // unknown[]
```

### 🙂 Expected behavior

```ts
// ...
type Unbound123 = Unbind<Bound123> // [1, 2, 3]
```

**Comment by RyanCavanaugh** [comment]
The double-`infer` here is very weird and I'm not sure if that can be supported.

I can't construct a reason where you'd need to write the types this way. The equivalent version
```ts
type Bind<T> = 
    T extends [...unknown[]]
        ? [...T]
        : never;
```
works as expected.

**Comment by andrueandersoncs** [comment]
@RyanCavanaugh Thanks for your reply! Given your alternative I guess I don't need to write it this way.. but why would the "nesting" of the infer make a difference? Any pointers toward the design or code of the compiler I could take a look at?

**Comment by RyanCavanaugh** [comment]
This isn't the sort of thing that would be approachable by someone who didn't already know where to look, but the relevant function is
```
function inferTypes(inferences: InferenceInfo[], originalSource: Type, originalTarget: Type, priority = InferencePriority.None, contravariant = false) {
```
in `src/compiler/checker.ts` line ~24058
