### ISSUE TITLE
allow any property name as return type

### ISSUE THREAD

**Issue by heycalmdown** [Microsoft/TypeScript#5305]
I have an issue during writing a piece of declaration for existing node.js module - bluebird.js. The module has a method named `props` which gets an object has promises in it then return an object have same property names. It seems like object-version `map`. I wanted to add types for that.

For `all` I can easily get the types like

```typescript
  static all<T1, T2>(values: [Promise.Thenable<T1>, Promise.Thenable<T2>]): Promise<[T1, T2]>;
  static all<T1, T2, T3>(values: [Promise.Thenable<T1>, Promise.Thenable<T2>, Promise.Thenable<T3>]): Promise<[T1, T2, T3]>;
  // ...
```

But for `props` the other hand,

```typescript
  static props<T1>(object: {[k:string]: Promise.Thenable<T1>}): Promise<{[k:string]: T1}>;
```

I'm getting this

```
bluebird/bluebird-tests.ts(530,10): error TS2339: Property 'foo' does not exist on type '{ [k: string]: Foo; }'.
bluebird/bluebird-tests.ts(534,10): error TS2339: Property 'bar' does not exist on type '{ [k: string]: Bar; }'.
```

Is there any tip for issue like this?

**Comment by Zorgatone** [comment]
I think you have to type `result["foo"]`, `result["bar"]`, and not `result.foo`, `result.bar`.

**Comment by DanielRosenwasser** [comment]
As @Zorgatone mentions, that will work, though I understand that you still want to use property access notation. I think we'd need a formal suggestion to tackle this.

**Comment by heycalmdown** [comment]
@Zorgatone Okay, it works. Thanks!
@DanielRosenwasser It'll be nicer we can do that.

Furthermore, what actually I wanted to was taking an object with several property as different types, then return new object which has same property name and keep the types. So as same as the `all<T1, T2>()` example, `props` should be more look like...

```typescript
  static props<T1, T2>(o: {[k1:string]: Promise.Thenable<T1>, [k2:string]: Promise.Thenable<T2>}): Promise<{[k1:string]:T1, [k2:string]:T2}>;
```

But the compiler says,
```bash
07:22 $ tsc --noImplicitAny --module commonjs bluebird/bluebird-tests.ts
bluebird/bluebird.d.ts(482,63): error TS2374: Duplicate string index signature.
bluebird/bluebird.d.ts(482,125): error TS2374: Duplicate string index signature.
```

any thought?

**Comment by danquirk** [comment]
You probably want to return ```Promise<T1 & T2>``` and use intersection types.

**Comment by heycalmdown** [comment]
@danquirk At the first look, it is very promising. My example worked well.

```typescript
interface Foo {
	foo(): string;
}
interface Bar {
	bar(): string;
}
var foo: Foo;
var bar: Bar;

type FooBar = Foo & Bar;
type FooBarWithinObject = { [k:string]:FooBar };
var a = { foo: foo, bar: bar };
a.foo.foo();
a.bar.bar();
```

But, inferred type from combined with generic and intersection in an object seems like `any`.

```typescript
function testIntersection<T1, T2>(o: {[k:string]:T1&T2}):{[k:string]:T1&T2} {
    return o;
}
testIntersection(a);
```

```bash
08:05 $ tsc --noImplicitAny --module commonjs bluebird/bluebird-tests.ts
bluebird/bluebird-tests.ts(547,18): error TS2345: Argument of type '{ foo: Foo; bar: Bar; }' is not assignable to parameter of type '{ [k: string]: {}; }'.
  Index signature is missing in type '{ foo: Foo; bar: Bar; }'.
```

Am I something wrong?

**Comment by DanielRosenwasser** [comment]
You'll need to have a type annotation on `a` with the appropriate type. That way the object literal "inherits" the index signature from the contextual type.

**Comment by danquirk** [comment]
Just to be clear, when you write 
```ts
o: {[k:string]:T1&T2}
```
You are describing an object where all properties have the type T1 & T2. I'm not sure if that's what you really mean. Whereas
```ts
o: T1 & T2
```
means a type with the properties of both T1 and T2.

**Comment by heycalmdown** [comment]
Sorry, first example above was wrong. I can't sure the intersection is the solution for this kind of issue.

```typescript
type FooBar = Foo & Bar;
type FooBarWithinObject = { [k:string]:FooBar };
let a = { foo: foo, bar: bar } as FooBarWithinObject;
/*
bluebird/bluebird-tests.ts(539,9): error TS2352: Neither type '{ [x: string]: Foo | Bar; foo: Foo; bar: Bar; }' nor type '{ [k: string]: Foo & Bar; }' is assignable to the other.
  Index signatures are incompatible.
    Type 'Foo | Bar' is not assignable to type 'Foo & Bar'.
      Type 'Foo' is not assignable to type 'Foo & Bar'.
        Type 'Foo' is not assignable to type 'Bar'.
          Property 'bar' is missing in type 'Foo'.
*/
a.foo.foo(); // bluebird/bluebird-tests.ts(540,3): error TS2339: Property 'foo' does not exist on type '{ [k: string]: Foo & Bar; }'.
a.bar.bar(); // bluebird/bluebird-tests.ts(541,3): error TS2339: Property 'bar' does not exist on type '{ [k: string]: Foo & Bar; }'.
```

**Comment by heycalmdown** [comment]
@danquirk 
What I meant was to keep types of all properties in an object and return them with proper types. Not to merge them.

Let's say we have a list which has elements as different types. If we put them into a `map()` as usual, it should keep the types. I want to do same thing with an object. It is a typical behaviour as libraries work with collections. Like `loadsh`, `bluebird`, `async` and so on.

**Comment by danquirk** [comment]
I see. So if you're trying to say 'this function returns a Promise of A or a Promise of B' you want union types:
```ts
static props<T1, T2>(o: { [k1:string]: Promise.Thenable<T1>} | { [k2:string]: Promise.Thenable<T2>}): Promise<{[k1:string]:T1 | [k2:string]:T2}>;
```
If you wanted to say 'this returns a Promise of something that is both an A and a B' then you would use intersection types, but it sounds like this is not what you want.

**Comment by heycalmdown** [comment]
Hmm. I think my explanation was not clear. Sorry.

1. `props` takes an object which contains `Promise.Thenable<T1>` and `Promise.Tenable<T2>`
1. when after every promises are fulfilled the `props` resolve new object
1. then a developer can use T1 and T2 from a returned object

```typescript
class Hat {
  wear() {}
}
class Pizza {
  eat() {}
}
function getHat():Promise<Hat> {
  return async().then(() => new Hat());
}
function getPizza():Promise<Pizza> {
  return async().then(() => new Pizza());
}
bluebird.props({
  hat: getHat(),
  pizza: getPizza()
}).then(result => {
  result.hat.wear();
  result.pizza.eat();
});
```

Are we clear?

**Comment by heycalmdown** [comment]
Any ideas?

**Comment by Zorgatone** [comment]
[**@heycalmdown**](https://github.com/heycalmdown) commented on [24 ott 2015, 14:49 CEST](https://github.com/Microsoft/TypeScript/issues/5305#issuecomment-150809077 "2015-10-24T12:49:55Z - Replied by Github Comment Enhancer"):
> Any ideas?

Have you tried with this already?

```typescript
class Hat {
  wear() {}
}
class Pizza {
  eat() {}
}
function getHat():Promise<Hat> {
  return async().then(() => new Hat());
}
function getPizza():Promise<Pizza> {
  return async().then(() => new Pizza());
}
bluebird.props({
  hat: getHat(),
  pizza: getPizza()
}).then(result => {
  result["hat"].wear();
  result["pizza"].eat();
});
```

If you need to have arbitrary properties names and use the dot notation (ie. `obj.property`) in TypeScript you have to declare the type as `any`.

**Comment by heycalmdown** [comment]
@Zorgatone 

I don't have any interest how I can compile without an error at this point. I do want to rewrite `d.ts` to give people a proper guide.

If I have an array or an object which contains elements as same type the type could be looks like

```typescript
map<T, R>(collection: T[], iteratee):R;
map<T, R>(collection: {[index:string]:T}, iteratee):R;
map<T>(collection: T[], iteratee):Promise<T>[];
```

If I takes a function which contains multiple arguments with different types for `curry`, the typical signature could be looks like

```typescript
curry<T1, R>(func: (t1: T1) => R): CurriedFunction<T1, R>;
curry<T1, T2, R>(func: (t1: T1, t2: T2) => R): CurriedFunction<T1, T2, R>;
curry<T1, T2, T3, R>(func: (t1: T1, t2: T2, t3: T3) => R): CurriedFunction<T1, T2, T3, R>;
// ... so on
```
Having every signature combinations has its limitation, but it is worth and very common.

So when I have a function that takes an object which contains different types and return them, what pattern could I use? Something 

```typescript
props<T1>({[key:string]:Promise<T1>}):{[key:string]:T1}
props<T1, T2>({[key:string]:Promise<T1|T2>}):{[key:string]:T1|T2}
props<T1, T2, T3>({[key:string]:Promise<T1|T2|T3>}):{[key:string]:T1|T2|T3}
// ... so on
```

Or does Typescript have not ability of this kind of needs?

**Comment by Zorgatone** [comment]
I believe that's not possible
>
>

-- 
Inviato da Gmail Mobile

**Comment by heycalmdown** [comment]
Okay, TS can't handle those kind of usage. Thanks. That's what I want to be confirmed.
