### ISSUE TITLE
.d.ts emitted from JS doesn't use `this` for method return types

### ISSUE THREAD

**Issue by Methuselah96** [microsoft/TypeScript#53051]
# Bug Report

### 🔎 Search Terms

- jsdoc
- overload
- return type
- inheritance

### 🕗 Version & Regression Information

- This changed between versions 4.5 and 4.6

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5&filetype=js#code/KYDwDg9gTgLgBAYwDYEMDOa4GEIDsZQRJLBRwDeAUAJAJ5oECuCM0AFAJQU0C+lNAegBUQmnCFwAAlGAxGUXJnIwAFgEs0fauIE1GYACYoYwACIawqAJ6du1ajLkK4qjQG5elPpVCRYiVAw4ACEIImAUXBx8QmJSADkIAFEQAhQAWWAAWwAjUjhQE1wDTGiCIhIyKlp6JhZ2LmrqNH1STg9qb2p9IxNzNEsUG0aaGsVwgDokCABzNgByEwZ5jg6HWXlcF3U0Dr5vX2h4ZHRMUPDIstjKgHU1VRS0zNz8wuBi0rxyuKqaOkU6qwoLYmi0wG1VqNXGgJkt4ABeOAAVj2-G6hmMZgs1hBo3+aEm0zmi2Ay0h9kcm227k8fCAA)

### 💻 Code

NOTE: This is JS, not TS.

```js
export class Controller {
	constructor() {
	}

	/**
	 * @returns {this}
	 */
	updateDisplay() {
		return this;
	}
}

export class BooleanControllerNoExtraMember extends Controller {
	constructor() {
		super();
	}

	updateDisplay() {
		console.log('test');
		return this;
	}
}

export class BooleanControllerWithExtraMember extends Controller {
	constructor() {
		super();
		this.test = 5;
	}

	updateDisplay() {
		console.log('test');
		return this;
	}
}
```

### 🙁 Actual behavior

The resulting declaration file includes `updateDisplay()` in `BooleanControllerWithExtraMember` with a return type of `BooleanControllerWithExtraMember`. This is problematic and causes type errors because the return type for `BooleanControllerWithExtraMember.updateDisplay()` needs to be assignable to `this`. Duplicating the JSDoc to specify that it returns `this` is undesirable since we don't want to have to duplicate the JSDoc for all derived classes.

I included `BooleanControllerNoExtraMember` as well to highlight the inconsistency that it sometimes doesn't specify the method overload due to seemingly unrelated changes to the class.

```ts
export class Controller {
    /**
     * @returns {this}
     */
    updateDisplay(): this;
}
export class BooleanControllerNoExtraMember extends Controller {
}
export class BooleanControllerWithExtraMember extends Controller {
    test: number;
    updateDisplay(): BooleanControllerWithExtraMember;
}
```

### 🙂 Expected behavior

`BooleanControllerWithExtraMember` doesn't specify `updateDisplay()` because it doesn't need to. This is how TypeScript 4.5 behaves.

```ts
export class Controller {
    /**
     * @returns {this}
     */
    updateDisplay(): this;
}
export class BooleanControllerNoExtraMember extends Controller {
}
export class BooleanControllerWithExtraMember extends Controller {
    test: number;
}
```

**Comment by a-tarasyuk** [comment]
The TypeScript [example](https://www.typescriptlang.org/play?ts=4.9.5#code/KYDwDg9gTgLgBAYwDYEMDOa4GEIDsZQRJLBRwDeAUAJAJ5oECuCM0AFAJQUC+NjYAExQxgAEQCWaMKgCenAFxwYAC0kU4UYDEZRcS1WgDccXr0qhIsRKgxwAQhCLAUuHPkLFSAOQgBREAQoALLAALYARqRwoCK4AphuBEQkZFS09Ews7FzkcGj8pJzGvNT8QiISUrKc6prauvqSxZRmFtDwyOiYDk4uiR4pAOriKv6BIRFRMcBxCXhJnqk0YIzhSOIISsAMiriMk1CGNHS4DFDMrFA1adT5YIUcR9TUKpIAdCIMcAC8cACsTxKZWEYkk0hQchyGi0Oj0ryMJhalCAA) includes `updateDisplay()` for each class. Or am I wrong?

```ts
export declare class Controller {
    constructor();
    updateDisplay(): this;
}
export declare class BooleanControllerNoExtraMember extends Controller {
    constructor();
    updateDisplay(): this;
}
export declare class BooleanControllerWithExtraMember extends Controller {
    test: number;
    constructor();
    updateDisplay(): this;
}
```

**Comment by Methuselah96** [comment]
This when creating type declarations from JavaScript (you can change language in the TSConfig > Lang option).

**Comment by sandersn** [comment]
Here's a repro that's the same code in JS and TS, but generates different .d.ts files:

```js
export class C {
    cdata = 2
    constructor() {
    }

    updateDisplay() {
        return this;
    }
}

export class B extends C {
    bdata = 1
    constructor() {
        super();
    }

    updateDisplay() {
        return this;
    }
}

export class D extends C {
    ddate = 3
    constructor() {
        super();
    }

    updateDisplay() {
        return this;
    }
}
```

In all 3 classes, `updateDisplay: () => this` but the generated d.ts file for JS has `updateDisplay(): D` (using D as an example).

**Comment by sandersn** [comment]
Here's a repro for the overrride part of the bug (though this should perhaps be a separate bug):

```js
export class C {
    updateDisplay() {
    }
}

export class D extends C {
    updateDisplay() {
    }
}
```

The generated d.ts for JS has `export class D extends C {}` whereas for TS, `D` includes `updateDisplay(): void`.

**Comment by sandersn** [comment]
Filed #54061 to track the missing-identical-override bug
