### ISSUE TITLE
error when assigning union of property type to union of object type when both types have a property with the same name and different types

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#53060]
# Bug Report

### 🔎 Search Terms
property assignment union type 

### 🕗 Version & Regression Information
5.1.0-dev.20230301
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230301#code/JYOwLgpgTgZghgYwgAgILIN4Chm+TAewIH4AuZAIyIBsI4RkAfZAVxABMIZQJ2c8KcKOWx4xyANoBrcgGcwUUAHMAuuVT9cAXyw6soSLEQoAQpk34iZZCBYBbCtCasOXHnzGDh58XmlyFZTVkEwsdPTAATwAHFABhZABeNGdQrE4EaiEUBAIQeWQALxELOHI43Sxc-LBLAnKkzGQLL3JCgBoAek7kaCgCKEqgA)

### 💻 Code

```ts
interface A {
    foo?: boolean | undefined
    bar: {
        [k: string]: A
    }
}

interface B {
    foo?: number | undefined
    bar: {
        [k: string]: B
    }
}

type C = A | B

declare const z: {
    a: C
}
const foo: C = { 
    bar: z,// error
}
```

### 🙁 Actual behavior
```
Type '{ a: A | B; }' is not assignable to type '{ [k: string]: A; } | { [k: string]: B; }'.
  Type '{ a: A | B; }' is not assignable to type '{ [k: string]: B; }'.
    Property 'a' is incompatible with index signature.
      Type 'A | B' is not assignable to type 'B'.
        Type 'A' is not assignable to type 'B'.
          Types of property 'foo' are incompatible.
            Type 'boolean | undefined' is not assignable to type 'number | undefined'.
              Type 'boolean' is not assignable to type 'number'.(2322)
```

### 🙂 Expected behavior
no error, because `undefined` is a valid `foo` on both `A` and `B`

**Comment by fatcerberus** [comment]
> TS can't do the sort of many-worlds argument that says that the initializer would have to be assignable to "one of" the target union

What are you talking about, type systems based on multiverse theory are the next big thing and TS needs to get on implementing that, like, yesterday! 😆

**Comment by DetachHead** [comment]
oh i see, this is just the same thing as `A[] | B[]` vs `(B|A)[]`

```ts
declare const foo: { bar: { [k: string]: A | B } }

const bar: A | B = foo // error
```
