### ISSUE TITLE
Error on narrowing down non-null variables

### ISSUE THREAD

**Issue by LaurentRos** [microsoft/TypeScript#53064]
# Bug Report

### 🔎 Search Terms

typenarrowing, null

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about null and narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=19&ssc=1&pln=20&pc=1#code/C4TwDgpgBAglC8UDeAoK6oGMBcUB2ArgDZFoYAmuAzsAE4CWeA5igL5QA+yZ6OUNDZjyiV8xUuy6oMWanUYsZogQrYoUmAPZ4aUABYQSmhFAAUAQ1wwAlLgBum+uQQA+bjK07NRCADoimkwWvpjWwp5U3n4BQea+5GGs6hHAUAC25owmpnwqzJxiJAA0InKCTAWEJLZQDk6u7hj0AGZmAISYUABkXVBtCY0y6LQQwAS0eADcwknCLe0d3b391oNDI2MT+oYBZkiYJeSsYTKzMvOmiz19K2syG+N420Z7ByLHM+r3o4-Pu6b7Q4fJJAA)

### 💻 Code

```ts
type A = {
    c: null
    d: string
} | {
    c: string
    d: null
} | {
    c: string
    d: string
}

const hello = (a: A): void => {
    console.log(a.c)
    console.log(a.d)
}

const main = (c: string | null, d: string | null): void => {
    if (!c && !d) {
        return;
    }

    if (!!c && !d) {
        return hello ({c, d})
    }

    if (!c && !!d) {
        return hello ({c, d})
    }

    return hello ({c, d})
}
```

### 🙁 Actual behavior

Typescript doesn't narrow down the variables to be non-null at the end
![image](https://user-images.githubusercontent.com/25028479/222491138-becd17eb-639a-4d15-9774-4e707dae16db.png)

### 🙂 Expected behavior

Typescript should be able to narrow down the types to both be non-null

**Comment by RyanCavanaugh** [comment]
Narrowing is based on the parent control flow graph introducing a direct narrowing, rather than doing a sort of constraint-solving process as would be required to figure this one out. We don't intend to switch to the latter method since code that requires that sort of analysis is quite rare in practice.

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/52822#issuecomment-1434063410
