### ISSUE TITLE
Type doesn't "widen" after a function call

### ISSUE THREAD

**Issue by terrybrash** [microsoft/TypeScript#53071]
# Bug Report

### 🔎 Search Terms

type narrowing

### 🕗 Version & Regression Information

4.9.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysCGxoF4oG8BQVtQGYHt8AudeEgOwFcBbAIwgCcAaKWkgZ2AYEtyBzAL5QAPlErkAJhFy8IEgNwYBijLnEBjYN3zko1eLwAUnRBBJxTAShIA3fNwnosOE0gB0BfFFTipM8nKKOHrwIPQwEMAAYoTGCEiW8lAA9Ml4hFDq+JQANhIs8JKZlAwMEOTAOSBQ3Ows7JE1usAAFrV4Glo6ztjcuFBxph6ElugpaaCQ7Oo8YMBQrbwA1uzpXuqFUDpVrNC+0rKOnNw5OT3BmTrs+DkQbjn4fIPunm7wiecCShiqndq6+jCEAi0VirjMsHiEGsUDsDicwXBwy8qDQZCgAEYAAxYlhsKAAIhaEFO+AJyiUQA)

### 💻 Code

```ts
type State = {
    foo: {a: number, b: string} | undefined;
};

function main(state: State): void {
    state.foo = undefined;
    maybeSetFoo(state); // foo could, and currently is, set in this function
    if (state.foo) { // typescript thinks foo can only be undefined still
        console.log(state.foo.a);
    }
}

function maybeSetFoo(state: State): void {
    state.foo = {a: 100, b: "hello"};
}
```

### 🙁 Actual behavior

TypeScript thinks `state.foo` can ONLY be `undefined`.

### 🙂 Expected behavior

I expect that after calling `maybeSetFoo`, the type of `state.foo` is `{a: number, b: string} | undefined`.

In this situation, if TypeScript were perfect, the type of `state.foo` would be known as just `{a: number, b: string}` after calling `maybeSetFoo`. But that is not my expectation.

**Comment by RyanCavanaugh** [comment]
Duplicate #9998; function calls are assumed to not have side effects
