### ISSUE TITLE
Error type when reduce an array of string | number and return a number

### ISSUE THREAD

**Issue by RodrigoTomeES** [microsoft/TypeScript#53075]
Hi!,

I have this code to convert string or number to a currency (this is because wordpress return the price formatted). The problem is that TypeScript said that the reduce return string or number instead of only number.

<img width="604" alt="imagen" src="https://user-images.githubusercontent.com/13077343/222695768-7a36bd29-b654-4d1f-ac8b-bbda320b4a83.png">

Why could it be?

```ts
export const priceToNumber = (number: string): number =>
  parseFloat(number?.replace(/€/g, '').replace(',', '.'));

const convertToString = (val: string | number): string =>
  val ? val?.toString() : '0,00';

const operateCurrency =
  (...args: (string | number)[]) =>
  (operator: (num1: number, num2: number) => number) => {
    const getNumber = (a: string | number, b: string | number) => {
      const aString = convertToString(a);
      const bString = convertToString(b);

      return operator(priceToNumber(aString), priceToNumber(bString));
    };

    const number: number = [...args].reduce((a, b) => getNumber(a, b), 0);

    return toCurrency(number);
  };

// Example of use
export const SumCurrency = (...args: (string | number)[]) =>
  operateCurrency(...args)((num1, num2) => num1 + num2);
```

Thanks!!

**Comment by MartinJohns** [comment]
You used the wrong issue template. If you have a bug report, you should use the [issue template for bug reports](https://raw.githubusercontent.com/microsoft/TypeScript/main/.github/ISSUE_TEMPLATE/Bug_report.md). But this seems to be a question instead, which is not suited for this issue tracker and more suited for support platforms like StackOverflow.

The return type of the `reduce()` call is inferred based on the input arguments, in your case `string | number`. So the resulting type is `(string | number)[]`. You can add an explicit type instead: `[...args].reduce<number>(...)`

**Comment by RodrigoTomeES** [comment]
@MartinJohns Sorry, I thought this was the right template, thanks
