### ISSUE TITLE
TYPO: Mini typo :D

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [microsoft/TypeScript#53076]
s/Maop/Map
https://github.com/microsoft/TypeScript/blob/4b6fb95f040c5c81743e19a56df8fa99bf3d139f/src/server/project.ts#L301

**Comment by RyanCavanaugh** [comment]
If someone wants to send a PR they can, but I don't think searching for "Map" is doing anything useful nor is anyone reading this comment going to be confused, so this isn't really a priority

**Comment by sschneider-ihre-pvs** [comment]
I just stumbled upon it while searching for how typescript is resolving tsconfig.json :D
