### ISSUE TITLE
Functions with async keyword don't autocomplete

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript#53074]
# Bug Report

### 🔎 Search Terms

async function autocomplete 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `async`

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwgY2AdQJbABYGUQB2yAYgVALxQDeAsAFBSNQDOhJArkcBgPYEByAQwC2EAFxQAFAEoKAPigA3HhgAmAbnoBfevVCRYiFOizYAgqyKkK1ekyhgATj2EZmEYp1S8BI8VNlyBQAFZ1d3AB5lNTlNOh06XTpkPmZgKAAPKAl4JFRMHHwrMkpaBiZLZCgAemqoCIBaKE8uHygCPyg3KEF2YB4U4TAAGwhgCFUobAhHCG0klII0qBBswzyTHAs2a1K7JkFKhzCMGrrGqDM+gZcRsZ9mKE5BRUEMYcE4Ue0gA)

### 💻 Code

```ts
type ObjectWithSyncFn = {
    syncFunctionName: () => void;
}

type ObjectWithAsyncFn = {
    promiseFunctionName: () => Promise<void>;
}


const x : ObjectWithSyncFn = {
    sync // <- Function name is autocompleted here
}

const y : ObjectWithAsyncFn = {
    async promi // <- Autocompletions unavailable
}
```

### 🙁 Actual behavior

When trying to autocomplete `promiseFunctionName`, autocompletions are unavailable

### 🙂 Expected behavior

It would show `promiseFunctionName` in the autocompletion, similar to how it works with functions without the `async` keyword.

**Comment by gomain** [comment]
Interfaces with classes work, but not with plain objects.

[Extended playground](https://www.typescriptlang.org/play?ssl=27&ssc=2&pln=16&pc=1#code/C4TwDgpgBA8gRgKwgY2AdQJbABYGUQB2yAYgVALxQDeAsAFBSNQDOhJArkcBgPYEByAQwC2EAFxQAFAEoKAPigA3HhgAmAbnoBfevVCRYiFOizYAgqyKkK1ekyhgATj2EZmEYp1S8BI8VNlyBQAFZ1d3AB5lNTlNOh06emQ+ZmAoAA8oCXgkVEwcfCsySloGJktkKAB6KqgIgFooTy4fKAI-KDcoQXZgHmThMAAbCGAIVShsCEcIbV06ZIJUqBAsw1yTHAs2axK7JkEKhzCMatqGqDNe-pdh0Z9mKE5BRUEMIcE4EbnEugwCMaOABmgmQ0AAkgDpiCwTAgdsrF5uHxbGVGE4XG4PEifBIZPIoKFMZFoqpYj8kh9mI9wYMRqIAcxIYCYRA4QiOC0URg6RAGcAaVDgaC2fCKs1vCjSvZDmxjpjGDU6o0cF0AO48RwAa2YFIWKTSAC8JMzoSL2eKcSi9mjukcMa4zsqoKrHoIhsweFBVDwIMwCAByYDaIA)

```ts

interface InterfaceOfAsyncFunction {
    promiseFunction: () => Promise<void>;
}

class ImplementsInterfaceOfAsyncFunction implements InterfaceOfAsyncFunction {
    async promi  // <- this works
}

const z: InterfaceOfAsyncFunction = {
    async promi // <- this also doesn't
}
```
