### ISSUE TITLE
Double error on invalid delete of readonly property

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#53082]
# Bug Report

### 🔎 Search Terms

operand delete operator double diagnostic error

### 🕗 Version & Regression Information

- This changed between versions 3.9 and 4.0

Before 4.0, we only gave one error here. In 4.0 and above, we give two errors.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.9.5#code/MYGwhgzhAEBiD29oG8C+AoAJgUxNgLtnIgHQB2YAttgNxA)

### 💻 Code

```ts
class Foo {}
delete Foo.name;
```

### 🙁 Actual behavior

Two errors

### 🙂 Expected behavior

One error

**Comment by ahmad2901** [comment]
Hi, I wanted to work on this where should I start.

**Comment by ahmad2901** [comment]
Hey, @jakebailey I am new to typescript can you recommend where should I get started?

**Comment by jakebailey** [comment]
The place to start would be to find all places in the checker which emit this error message, set a breakpoint at each, and figure out in which conditions both appear, and see which one shouldn't be happening.

**Comment by ahmad2901** [comment]
sure thanks for your help.

**Comment by ahmad2901** [comment]
@jakebailey by checker do you mean tests folder??

**Comment by ahmad2901** [comment]
take

**Comment by somebody1234** [comment]
@jakebailey i can't repro on 5.0.2 and 4.0 - i get the second error on a `tsc` run, unless that's not what compiler and fourslash tests do? note that `checkDeleteExpressionMustBeOptional` explicitly checks for `strictNullChecks` so it will not be emitted if that's off

the fix *looks* like it'd be simple to me so i'm likely just misunderstanding something here

```ts
            if (isReadonlySymbol(symbol)) {
                error(expr, Diagnostics.The_operand_of_a_delete_operator_cannot_be_a_read_only_property);
                // missing return, so tsc *may* emit a second error from the below function call
            }
            checkDeleteExpressionMustBeOptional(expr, symbol);
```

**Comment by shoeb00** [comment]
Hey @jakebailey , any updates on this issue? I am unable to replicate this issue. I have tried versions 3.0, 3.9, 4.0 and 4.9 and there was a single error for all of them

> test.ts:2:8 - error TS2704: The operand of a 'delete' operator cannot be a read-only property.

> 2 delete Foo.name;
         ~~~~~~~~
> 

> Found 1 error in test.ts:2

**Comment by jakebailey** [comment]
I don't have any updates. This only reproduces in the language service and the playground, as I said before. If you check the latter by the link in my issue, you'll see it says there are two errors on the right.

**Comment by shoeb00** [comment]
This is my first time contributing to an open-source project, I would really appreciate your help. I have cloned the repo and switched to the [release-4.0](https://github.com/microsoft/TypeScript/tree/release-4.0) branch then I ran these commands

`npm install && npm run build`

Then I created a test.ts file with the code mentioned in the issue then to run that file I used this command

`node built/local/tsc.js test.ts`

Output:
~~~~~~~~
test.ts:2:8 - error TS2704: The operand of a 'delete' operator cannot be a read-only property.

2 delete Foo.name;


Found 1 error in test.ts:2

**Comment by gooddavvy** [comment]
What are the errors? Can you be more specific?

**Comment by somebody1234** [comment]
@gooddavvy check the "Playground Link" heading in the original post

**Comment by hooknb** [comment]
I think to it's trying to get an operand which could be empty, a property which has no use but still exist in the object.

**Comment by SauravChittal** [comment]
Is this issue fixed, or could I work on it?

**Comment by jakebailey** [comment]
There is #53961 which presumably fixes the issue but isn't yet complete.

Also note: https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#issue-claiming
