### ISSUE TITLE
Allow satisfies to be used as a type contraint to allow constraining types to be exactly the same as the constraint.

### ISSUE THREAD

**Issue by Kaerum** [microsoft/TypeScript#53084]
## 🔍 Search Terms

satisfies, constraints, extends

Couldn't find anything, but also there are way too many issues and it is quite hard to filter through them so I might have missed something, hopefully one day we could get AI assisted search for issues.

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [*] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [*] This wouldn't change the runtime behavior of existing JavaScript code
* [*] This could be implemented without emitting different JS based on the types of the expressions
* [*] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [*] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow `satisfies` to be used as a type contraint to allow constraining types to be exactly the same as the constraint.
Specifically, by using `satisfies` instead of `extends`, we tell the compiler that we do not accept Types that are subtypes of our constraint, only those that are structurally the same.

So instead of doing `T extends Type` one would use `T satisfies Type`.

## 📃 Motivating Example

This suggestion would allow to easily avoid 'Type could be subtype of constraint' errors.

So instead of having this code:
```ts
interface Events {
    first: { a: boolean }
    second: { b: string }
    third: { c: number }
}

type EventHandler<Key extends keyof Events> = (value: Events[Key]) => Promise<void> | void

const eventHandlers: Partial<{[Key in keyof Events]: EventHandler<Key>}> = {}

function addEventHandler<Key extends keyof Events>(name: Key, handler: EventHandler<Key>) {
    if (!eventHandlers[name]) {
        eventHandlers[name] = handler // error: '"first"' is assignable to the constraint of type 'Key', but 'Key' could be instantiated with a different subtype of constraint 'keyof Events'.
    }
}
```

We would have:
```ts
interface Events {
    first: { a: boolean }
    second: { b: string }
    third: { c: number }
}

type EventHandler<Key extends keyof Events> = (value: Events[Key]) => Promise<void> | void

const eventHandlers: Partial<{[Key in keyof Events]: EventHandler<Key>}> = {}

function addEventHandler<Key satisfies keyof Events>(name: Key, handler: EventHandler<Key>) {
    if (!eventHandlers[name]) {
        eventHandlers[name] = handler // no error
    }
}
```
## 💻 Use Cases

I am currenly not aware of workarounds for this issue.

**Comment by jcalz** [comment]
I’m not understanding; if you don’t want a subtype, why use a generic at all?

**Comment by RyanCavanaugh** [comment]
> Specifically, by using satisfies instead of extends, we tell the compiler that we do not accept Types that are subtypes of our constraint

What you're saying here is that
```ts
addEventHandler("first", () => {});
```
should be an illegal call, since `"first"` is a subtype of `keyof Events`. Huh?

It seems like you're trying to talk about #27808

**Comment by Kaerum** [comment]
Yes, I believe that https://github.com/microsoft/TypeScript/issues/27808 is precisely what I was trying to express.

Sorry for the trouble.
