### ISSUE TITLE
`ArrayBuffer.isView` should be typed as a type guard

### ISSUE THREAD

**Issue by jvilk** [Microsoft/TypeScript#5308]
I'm happy to go through the contributing process and open a PR with this change if you're accepting changes to `lib.d.ts`.

[`ArrayBuffer.isView(arg)`](https://github.com/Microsoft/TypeScript/blob/af05e46b2877edfbc239ade1a46d05b387568bd8/src/lib/core.d.ts#L1213) should be typed with the return value `arg is ArrayBufferView`

Relevant [standard documentation](http://www.ecma-international.org/ecma-262/6.0/#sec-arraybuffer.isview) (more [informally described at MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/isView)):

> The isView function takes one argument arg, and performs the following steps are taken:
> 1. If Type(*arg*) is not Object, return **false**.
> 2. If *arg* has a [[ViewedArrayBuffer]] internal slot, return **true**.
> 3. Return **false**.

I remember at one point you weren't accepting typing issues on `lib.d.ts` and deferred to the community for fixes, but it looks like your decision has changed. Feel free to close this issue if this is still the case.

**Comment by DanielRosenwasser** [comment]
For `dom.d.ts`, we auto-generate these definitions. I think you should be able to safely patch this one, though @zhengbli can correct me if not.

**Comment by jvilk** [comment]
Excellent. I will prepare a PR. Is this a change that I should cover with a unit test? I do not see any tests that are pertinent to the default declaration files that ship with TypeScript.

**Comment by DanielRosenwasser** [comment]
Check out [Adding a Test in our CONTRIBUTING.md](https://github.com/Microsoft/TypeScript/blob/0b580c4754bf4445d1cb184edac1e28e5938937f/CONTRIBUTING.md#adding-a-test). We have symbol/type baselines for all atomic nodes within the file, so just write an example where you have a variable that gets narrowed to an `ArrayBufferView`.

**Comment by jvilk** [comment]
D'oh, I should have read further on in that document. I opened a PR, and I think I added the test in the appropriate location. :smile:

**Comment by mhegazy** [comment]
thanks @jvilk !

**Comment by jvilk** [comment]
:+1: Thanks for being open to bug fixes, and for having a completely painless CLA process!
