### ISSUE TITLE
TS2416 wrong detection in Mapped Types

### ISSUE THREAD

**Issue by anton-tregubov** [microsoft/TypeScript#53097]
# Bug Report

### 🔎 Search Terms

TS2416 wrong detection

### 🕗 Version & Regression Information

Bug reporoduce on 4.9.5 and nighlty build too

Please keep and fill in the line that best applies:

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about TS2416

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230305#code/C4TwDgpgBACgTge0nYBLCBnAKuCAeLKCAD2AgDsATDKAbygG0BrCEKVcqDYODgcwC6ALigBDcmwC+APigBeKIRJkqNes1btO3XuUEiOAMwhwoANSiSoAfnNQR5CADcTAbgBQ7jmTiHRAY2h4JBNQM1EAGwBXfGDkUAAac0iY2Vp3KEyoOAhRSgRyCLYwRHiQETjQkA8s7Nz8wrYnFIgRcOiID0lPQyjyfzQCqHJRAFsISnaYvAB5AHdHOCTKlDZlCmooFhAEQyh5xekACgQAIwArCAGRA5MkkpDVgDkx1thSqoBKCo-Vqdjfol9gsTAwVqABGkMlkcsAonBOOlarUHmURKiqi9xglPMisnwIMAoM0OkdvsDFmDASABHRoXjarD4ZwzpcBgwMc9XgIagzurVJF1PKBIFAAEIIBARXLkf7yKCnSXS8Qedwi6AAYQiogwGAAklQSPKAIxQAA+UAATB51e9HqADZQjQpTRbLeaoABmDz+ArcWAAJQAogAxPUADXlACIwFHVd4TH5AhSTAB1OCiMDIPAavVEUgbGhanX6w3EKH0up5ApFLRgKLAY0iA314A5vVJY3SSs5auNOsNy3N8it9tJS3dxn1GtsDitz3D0e5pKe7vdNW4KAthvt-MqTbF3WOkjLPPrVR2srH8vy8Egf54ba7FNwbfADBj2B66TLQHobC4LMIKviODYfsuX7SFBqobqKtwga24FngWF6HqWTrEKee6FpeVTXrIChIjC079hos6cAABgAJLQ6rPjAwZhuGkgAPQ0bmkgAPo0TAeqSBRwjikqMr-F0qq2qmCBwEwoiIH0lAhlJYpRHwu7nge2pHmWBF0lOfa1mRWhQBRZqoHw5BSRAZrsXxAnWA4zhuO4grCpu8FqShGklvh8iVvBb5Ib+9ogPhngsSxUAAGRQJJ0myQg8mKXAymqbmsjhRqMwALJZUGTyEFgAASeoAMoxQAgp47j+JpNDwemmbIHqoxgBEHn7kWtU+agLXSuM5Dvi+DVZiY7YVnpDS1nODbGrymS9pN5GttaPYkVNoHAN6uJZL65A6FEAxSUcJSoM0ZBVotUCcRwGEiMulYMsiJ1ndAC0zldJIxIVUpOnANzAWNny6QywAABaoBgAB002NvKIzjJMLRHGDEOQ5xn0QN9ES-UkKNQzDWBIKg-hYhARzGp8nxzciePQxt7oKPDEz-Mj4NQ+jLRYzjUC0wTRMk68RyWpT1O1LzG2enDryI6StMcx0XN3DzbN062hNgMTpNHJ6IuVuuKK8C9A7AOrmuvHgvHYRed74cdUnABUerkk+ez+RtgWQcDeJMgixk8YxEasTRcs3SQXE0WA9v8dT3TrtVfpEggwH-Ysw3Zl2cMQHMQ0ZiNr69eTSREZkMYscanHGlGIg8DEOK1KX5eWlXPNwLXlYN5xnrNzXEDOZ88d7USeN6hgAa5BERQSlKMpNgqwniPKSeLKrM2QxjA-+sPo-j5P8-kEOc-TwvChLyYK-AJaa8tBvQ9syPY+RLvR-kAuh-KpwJ-AefnpXx07hAA)

### 💻 Code

I 'll try to make it shorter but can't sorry. 
```ts
type PropertiesType<T extends { [key in string]: any }> = T extends { [key in string]: infer V } ? V : never;

interface PropertyValue<Property, Value> {
    readonly property: Property;
    readonly value: Value;
}

function namedValue<Owner, Property extends keyof Owner>(object: Owner, propertyName: Property): PropertyValue<Property, Owner[Property]> {
    return {
        property: propertyName,

        get value(): Owner[Property] {
            return object[propertyName];
        }
    };
}

type BooleanValue = boolean;

type ClassIndex = 1 | 2;
type PropertyIndex = 1 | 2 | 3;
const PREFIX = "p";

interface OwnerWrapper<CI extends ClassIndex> {

    readonly input1: Input<CI, 1>
    readonly input2: Input<CI, 2>
    readonly input3: Input<CI, 3>
}

type Input<CI extends ClassIndex, PI extends PropertyIndex> = PropertyValue<keyof OwnerInputs<CI, PI>, PropertiesType<OwnerInputs<CI, PI>>>;


type OwnerInputs<CI extends ClassIndex, PI extends PropertyIndex> = {
    readonly [key in `${typeof PREFIX}/${CI}_${PI}`]: BooleanValue;
};

type WorkaroundForBug<CI extends ClassIndex> = {
    readonly [key in `|ignore|${CI}`]?: never;
};

type Owner<CI extends ClassIndex> =
    OwnerInputs<CI, PropertyIndex>

// & WorkaroundForBug<CI> //COMMENT THIS WA


class OwnerWrapperImpl<CI extends ClassIndex> implements OwnerWrapper<CI> {

    readonly input1;
    readonly input2;
    readonly input3;

    constructor(private readonly _index: CI,
                private readonly _valueHolder: Owner<CI>) {
        this.input1 = namedValue(this._valueHolder, this.inputTopicName(1));
        this.input2 = namedValue(this._valueHolder, this.inputTopicName(2));
        this.input3 = namedValue(this._valueHolder, this.inputTopicName(3));
    }

    private inputTopicName<PI extends PropertyIndex>(port: PI): keyof OwnerInputs<CI, PI> {
        return `${PREFIX}/${this._index}_${port}`;
    }
}

//Proff that this property realy boolean; 

const owner: OwnerWrapper<1> = new OwnerWrapperImpl(1, {
    "p/1_1": true,
    "p/1_2": true,
    "p/1_3": true
})
const thisIsReallyBoolean1: boolean = owner.input1.value
const thisIsReallyBoolean2: boolean = owner.input2.value
const thisIsReallyBoolean3: boolean = owner.input3.value

```

### 🙁 Actual behavior

```
Property 'input2' in type 'OwnerWrapperImpl<CI>' is not assignable to the same property in base type 'OwnerWrapper<CI>'.
  Type 'PropertyValue<`p/${CI}_2`, Owner<CI>[`p/${CI}_2`]>' is not assignable to type 'Input<CI, 2>'.
    Type 'boolean' is not assignable to type 'PropertiesType<OwnerInputs<CI, 2>>'.(2416)
```
System report error only if `Owner` type doesn't mix with other types with Generic. If and any FAKE field using maped type bug doesn't reproduce. 

### 🙂 Expected behavior

Code will compile without error and without WA WorkaroundForBug type

**Comment by RyanCavanaugh** [comment]
Please reduce this down to something shorter than more clearly demonstrates the issue.

**Comment by anton-tregubov** [comment]
I'l try to reduce sample

```ts
type PropertiesType<T extends { [key in string]: any }> = T extends { [key in string]: infer V } ? V : never;

interface PropertyValue<Value> {
    readonly value: Value;
}

type ClassIndex = 1 | 2;
type PropertyIndex = 1 | 2;

interface OwnerWrapper<CI extends ClassIndex> {

    readonly input1: Input<CI, 1>
}

type Input<CI extends ClassIndex, PI extends PropertyIndex> = PropertyValue<PropertiesType<OwnerInputs<CI, PI>>>;

type OwnerInputs<CI extends ClassIndex, PI extends PropertyIndex> = {
    readonly [key in `${CI}_${PI}`]: boolean;
};

type WorkaroundForBug<CI extends ClassIndex> = {
    readonly [key in `|ignore|${CI}`]?: never;
};

type Owner<CI extends ClassIndex> =
    OwnerInputs<CI, PropertyIndex>

// & WorkaroundForBug<CI> //UNCOMMENT THIS FOR FIX COMPILE ERROR


class OwnerWrapperImpl<CI extends ClassIndex> implements OwnerWrapper<CI> {

    readonly input1;  //---- COMPILE ERROR HERE. Type 'boolean' is not assignable to type 'PropertiesType<OwnerInputs<CI, 1>>'.

    constructor(private readonly _index: CI,
                private readonly _valueHolder: Owner<CI>) {
        const vh = this._valueHolder;
        const i = this._index;
        this.input1 = {
            get value() {
                return vh[`${i}_1`];
            }
        }
}

//BUT this work fine
const b1: PropertiesType<OwnerInputs<ClassIndex, 1>> = true;
```

**Comment by RyanCavanaugh** [comment]
A short repro is usually around 5-15 lines, not 45+. If this is the shortest manifestation of the bug, we almost certainly would not dedicate scheduled time to fixing it.
