### ISSUE TITLE
experimentalDecorators ignored within nodejs project

### ISSUE THREAD

**Issue by cveld** [Microsoft/TypeScript#5309]
I have walked through the wizard "Create a TypeScript project from existing nodejs code" with tsconfig.json containing the line: `"experimentalDecorators": true` within `"compilerOptions"`. Still I get the experimental warnings for all decorators that have been used.

I tried the same tsconfig.json configuration and code in an ASP.NET 5 project and there it just works without the warning showing up.

**Comment by cveld** [comment]
OK after scrolling down all the errors and warning I now see a clear message: tsconfig.json is not supported in this project type. Closing the issue.

**Comment by mhegazy** [comment]
In VS today, if a project file exists, it take precedence on a tsconfig.json file as the main source of configuration/ build information.

This has been confusing to users trying to use tsconfig.json in existing projects. Issue https://github.com/Microsoft/TypeScript/issues/5287 is tracking  making this happen.

One thing to note, any property that you define today in tsconfig.json file has a matching MSBuild property that can be defined in your .*proj file. First unload the project file, right click, and edit, then in the project file define a property (note needs to be before the import of the .targets file): 
```XML
<TypeScriptEmitDecoratorMetadata>true</TypeScriptEmitDecoratorMetadata>
```

for the complete list of MSBuild property names see: https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects
