### ISSUE TITLE
Each tuple member type becomes union of all tuple member types when intersection with object

### ISSUE THREAD

**Issue by btakita** [microsoft/TypeScript#53091]
# Bug Report

I'm attempting to define a `Row` type which has a generic being an array of pair tuples, like a Map's entries 2d array, that is a tuple of the mapped value members (index 1), of each pair intersected with an object of the key: value members.

```typescript
export type Row<Defs extends [string, any][]> = RowTuple<Defs>&TupleToProps<Defs, 0, 1>
export type RowTuple<Defs extends [string, any][]> = { [K in keyof Defs]:Defs[K][1] }
type TupleToProps<T extends readonly any[], KeyName extends keyof T[number], ValName extends keyof T[number]> = {
	[P in Exclude<keyof T, keyof readonly any[]> as T[P][KeyName]&string]:T[P][ValName]
}
```
This results in the following inferences:
```typescript
// Row
const foo = foo_()
const foo_0 = foo[0] // number|string
const foo_1 foo[1] // number|string
const foo_col0 = foo.col0 // number
const foo_col1 = foo.col1 // string
function foo_():Row<[['col0', number], ['col1', string]]> {
	return Object.assign([123, 'bar'], {
		col0: 123,
		col1: 'bar'
	}) as Row<[['col0', number], ['col1', string]]>
}
```

Without the intersected object type, the more precise inferences are made:

```typescript
/ RowTuple
const foo_tuple_0 = foo_tuple[0] // number
const foo_tuple_1 = foo_tuple[1] // string
function foo_tuple_():RowTuple<[['col0', number], ['col1', string]]> {
	return [123, 'bar']
}
```
It seems like the tuple position type inferences are not preserved.

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

### 🔎 Search Terms

typescript tuple intersection object

### 🕗 Version & Regression Information

5.1.0-dev.20230303

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/KYDwDg9gTgLgBDAnmYcBKEDuAeAIsAMwGc5QZgA7AExIG0iYoBLCgcwBo4BDCxAXVp8AfHAC86LABUArmAA2wPISJCAZDPnBJEAApQIYIkuKcADJwCMQgFChIsBMlQZMGhcZJlKNOPUYsObl4BYTE4AG9fAGk4FjgAa2BECAI4fGI+AC50oloogQs+OABfayQUODctXX1DbElSEHJqEihgLioICjlEIMRBTiikgDkuAFtULxaEpJTK2gppMYAjYCg+TgA1LjlRicbmn0Tk1MkFpdX1kXFw6wBIWh1YijgAURAAYzlpKkVjucknH+qTaHS6PT6ghEXBIZx0AiGiD2wD4qgYzDYWThAm2u3GKOspQA9ESJJhrB8ugw4AQIBAwrSIAB9AAUAEoKVT4IymaYGXTaKYiiS4IsVmsAD7ogKcijUnkWfkQWiFOAisWXKX+Niy+V0pmUuS8pUAOkNxvVFzWuu5+vNivEjLNECNipF0p1BGkFA+MCYXRp+vZmRc2FotAA5ObTBHOBq1htfFGXUyLLG4B7WHxQrc7m0YNIoC8APLLABWwF9JphRCYrAoLJVACYAMycCPLLhQCOJ3N3aOZOAWVvse79lMWQcdrsR+7FNncEih8PJo0xuNW9acSP29OZ7M2YmklxVG2B5kFzRKpmXhSsjmUuW2i+yO98x362-AQXC0nxqBnjyX6pteX4qr+Gbaqw1hej6foBkBr7APeIZSEhYY7im66ipuiaYa6e5QQeET3PmhYvM2bZwNO3Z8IS1hAA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

`foo_0` is a `number|string` & `foo_1` is a `number|string`.

### 🙂 Expected behavior

`foo_0` should be a `number` & `foo_1` should be a `string`.

I believe that the tuple position type behavior should be preserved when intersected with another type.

**Comment by Seally** [comment]
Your playground link uses the type `TupleToObject`, which doesn't exist, and there's an extra `)` in the type parameters of `Row` and `RowTuple`. 

I changed `TupleToObject` to `TupleToProps` (I assume that's the intention), and removed the extra `)` and I think it works now?

**Comment by btakita** [comment]
Sorry about that. I updated the [Playground Link](https://www.typescriptlang.org/dev/bug-workbench/?#code/KYDwDg9gTgLgBDAnmYcBKEDuAeAIsAMwGc5QZgA7AExIAoBDCxAbQF0AfW5omKASwoBzADRxGiVmwCUUgHxwAvOiwAVAK5gANsDyEisgGTqtwFRAAKUCGCK7iogAyiAjLIBQoSLATJUGTMbadiRklDRwDExsnNy8AiJiTJKsMvJKAN5wzADScAJwANbAiBAEcPjErABcFUQ5ks6scAC+bkgocIGmFlY22CqkIOTUJFDA9FQQFJqIiSysotnFg8PhRSVlKswUagC2AEbAUAtwAGr0mithJOulndt7h8dpcOluAJDM5nkUcACiIAAxpo1FQdLdNqIIXAxhMpjM5mx5PQSFtzJIlhIDDx+EJqmjJOdNKw3K0APRk5SYNyAqY8OAECAQRQMpkAfVoUhpdPgjIgbIcLL5zAcTQpcB2ByO7Bx8W5FHpfLZziFTOYjTg4slTxlcSE8sV7NpmgFqogADpjaatY8jgbeUaICaVUo+ZancrNZTZfqCGoKICYHwpqz+Zyqv5sMxmAByK0OGOibVHE6xq3ORNwH2CViseRvd5jGBqKC-ADy+wAVsBA+aUUQ+IIKFxnAAmADMohj+3oUBjJwL73jVTgbc7HyHHucI+7vZjH2aUjEJEj0bjHoTSdtx1Eaanmezufc5Mp-i69tDbOLJjNV402g5XNpCod-OvD8FrvZ7+AIrFlOTKALyVH9PS-N971-DVxWzNw-QDIMQxAyDHwjVRIKjPcTU3CVt1TddnQPPUczzV4PiLEtfnVDsux7PsSVaIA) in the OP description as well.

**Comment by RyanCavanaugh** [comment]
![image](https://user-images.githubusercontent.com/6685088/223228740-83fa25f8-1c06-4934-9323-e58a777554df.png)

Using the example from that link but adding `export` to show the types:
```ts
export type Row<Defs extends [string, any][]> = RowTuple<Defs>&TupleToProps<Defs, 0, 1>
export type RowTuple<Defs extends [string, any][]> = { [K in keyof Defs]:Defs[K][1] }
type TupleToProps<T extends readonly any[], KeyName extends keyof T[number], ValName extends keyof T[number]> = {
	[P in Exclude<keyof T, keyof readonly any[]> as T[P][KeyName]&string]:T[P][ValName]
}
// Row
const foo = foo_()
export const foo_0 = foo[0] // number|string
export const foo_1 = foo[1] // number|string
export const foo_col_0 = foo.col_0 // number
export const foo_col_1 = foo.col_1 // string
function foo_():Row<[['col_0', number], ['col_1', string]]> {
	return Object.assign([123, 'bar'], {
		col_0: 123,
		col_1: 'bar'
	}) as Row<[['col_0', number], ['col_1', string]]>
}
// RowTuple
const foo_tuple = foo_tuple_()
export const foo_tuple_0 = foo_tuple[0] // number
export const foo_tuple_1 = foo_tuple[1] // string
function foo_tuple_():RowTuple<[['col_0', number], ['col_1', string]]> {
	return [123, 'bar']
}
```
the .d.ts shows all as-expected
```ts
export declare const foo_0: number;
export declare const foo_1: string;
export declare const foo_col_0: number;
export declare const foo_col_1: string;
export declare const foo_tuple_0: number;
export declare const foo_tuple_1: string;
```

Can you clarify?
