### ISSUE TITLE
Add support for the jsdoc abstract tag

### ISSUE THREAD

**Issue by qwq0** [microsoft/TypeScript#53099]
# Suggestion

## 🔍 Search Terms

jsdoc   
abstract   

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add support for the abstract tag in jsdoc has the same behavior as the abstract keyword in typescript.

**Comment by a-tarasyuk** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/17227

**Comment by qwq0** [comment]
Duplicate
