### ISSUE TITLE
Feature request: Sharing with C#

### ISSUE THREAD

**Issue by BobFrGit** [Microsoft/TypeScript#5311]
I find myself sharing structures between C# and Typescript when I do client/server code and using browser code in my apps as with Awesomium and MSHTML. It would be nice to have a way to share a common interface definitions -- perhaps an option to automatically generate a corresponding C# or VB definition from the TS version. This would also be useful for enumerations and constants.

**Comment by NN---** [comment]
Try TypeLITE (http://type.litesolutions.net/) or Netjs (https://github.com/praeclarum/Netjs)

**Comment by BobFrGit** [comment]
Thanks - I'll look at TypeLITE because it is closer to the simpler effort to keep things in sync. But just as one wants to automatically compile TS=>JS it would be nice to have transparent integration from TS to C# declarations because the TS representation is more constrained.

**Comment by NN---** [comment]
C# is not structurally typed language and has a different type system.
It is pretty hard to have TS->C# and easier te opposite.

**Comment by BobFrGit** [comment]
There are some fundamental differences but I'm just trying to solve a simple problem - when I share between the two I'd like to improve the odds of compatibility across boundaries when I exchange bundles (structures, classes) of elements. If I serialize in C# to JSON and then use that JSON in TS I'd just like a little assistance. In fact there are tools for taking JSON and creating C# declarations -- it would just be nice to have such capabilities smoothly integrated into the IDE.

**Comment by NN---** [comment]
@BobFrGit In that case you have to use a subset of TS features to make it compatible with C#.
Actually you can hack TS compiler to produce C# output instead of JS :)

**Comment by NN---** [comment]
The other option is to parse that subset of TS by yourself and produce C#  if you limit yourself of course.
Writing parsers and generating is pretty easy using Nitra tool (https://confluence.jetbrains.com/display/Nitra/Home)
But maybe hacking compiler for another backend is easier.

**Comment by BobFrGit** [comment]
The problem is static friction -- getting up to speed on all the different interfaces and bodies of code. Much easier to those well versed in TS and VS. Otherwise I'll continue the manual approach for the few cases I need to deal with.

**Comment by mhegazy** [comment]
Looks like the original issue has been addressed. please reopen if this is not the case.

**Comment by eiva** [comment]
This is why I moved myself to pure nodejs without .net. Requirement to type same stuff 2 times is really contradict to dry principle. And you should always remember fun stuff of serializer which change capitaliztion.
All solutions which requires “right click and pick run custom tooling”is a.... not a solutions. It should be “on save” or on build. But i didnt find anything like that.
