### ISSUE TITLE
Feature request : currying

### ISSUE THREAD

**Issue by xmehaut** [Microsoft/TypeScript#5313]
I would suggest to add in a future version the ability to have currying in function in order to be able to write such function calls :+1: 
```
let dummy = myfunc(3, 6) {
        // something to do
}
```
with a function declaration sucha as :
```
function myfunc(a:number, b:number, c : ()=> void)
```

**Comment by kitsonk** [comment]
Essentially this is a variant of the existing JavaScript `.bind()` functionality and would be difficult to meet the [design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) of TypeScript.  Of course that is just my personal opinion.

**Comment by xmehaut** [comment]
In what is it a variant of the bind feature? 
By enabling my proposal , we could easily and clearly create Groovy-like builders, for instance to create such a code 
´´´
body {
     div {
          a( href="anurl") {
                 .. 
           }
     }

}

Envoyé de mon iPhone

**Comment by DanielRosenwasser** [comment]
Hey @xmehaut, check out a previous discussion of this on #486.
