### ISSUE TITLE
TSServer exited. Code: null. Signal: SIGTERM. Nothing useful in the logs.

### ISSUE THREAD

**Issue by mctrafik** [microsoft/TypeScript#53147]
# Bug Report

My TSServer keeps crashing.

### 🔎 Search Terms

I've been googling for 3 hours now things like:
 - `TSServer exited. Code: null. Signal: SIGTERM`
 - `VSCode intellisense not working`
 - TS Server crashes
 - Typescript Partial Mode

### 🕗 Version & Regression Information

About 2 months ago in January 2023.

I have checked:  https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs
There's nothing in there.

I am unable to install: `typescript@next` because npm goes into an infinite loop when trying to `--force` install it. Prints:
```
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer typescript@">=2.7" from ts-node@10.9.1
npm WARN node_modules/ts-node
npm WARN   dev ts-node@"^10.9.1" from the root project
npm WARN   12 more (ts-node-dev, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @snapchat/mw@0.0.1
npm WARN Found: typescript@5.1.0-dev.20230307
npm WARN node_modules/typescript
npm WARN   dev typescript@"5.1.0-dev.20230307" from the root project
npm WARN   8 more (ts-loader, ts-node-dev, tsc-watch, tsc-watch, tsc-watch, ...)
``` 

infinitely.

- This is a crash of Typescript Server
- This changed between versions (doesn't matter). Tried 4.7.0, 4.8.4 and 4.9.4
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about TS Server crash.

I don't have any extensions in my workspace in VSCode that would be conflicting. Not sure where to turn.

### ⏯ Playground Link

Cannot narrow it down to a "playground" code.

### 💻 Code

N/A

But here's what I see in the logs:

Typescript Extension Logs:

```
[Info - 20:05:49.788] Starting TS Server
[Info - 20:05:49.788] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info - 20:05:49.790] <syntax> Log file: /Users/atrofimov/Library/Application Support/Code/logs/20230307T111556/window1/exthost/vscode.typescript-language-features/tsserver-log-6TnEWJ/tsserver.log
[Info - 20:05:49.790] <syntax> Forking...
[Info - 20:05:49.792] <syntax> Starting...
[Error - 20:05:49.799] TSServer exited. Code: null. Signal: SIGTERM
```

Typescript Server Logs attached.
[serverlog.txt](https://github.com/microsoft/TypeScript/files/10913706/serverlog.txt)

### 🙁 Actual behavior

The typescript server crashes very soon after starting.

### 🙂 Expected behavior

I expect it to not crash.

**Comment by RyanCavanaugh** [comment]
Is this for all folders, or for a certain project?

**Comment by mctrafik** [comment]
This was for all of the folders within my project. I did get it to work by
reinstalling vscode, reinstalling dependencies and creating a new workspace
in a different folder. :shrug:

**Comment by RyanCavanaugh** [comment]
Uh, hmm. We'll need some way to reproduce this for sure then

**Comment by mctrafik** [comment]
I'll make a new issue when I encounter it again. A lot of my coworkers get the same issue sporadically. So it's probably something about our workspace.
