### ISSUE TITLE
TS: suggest the best fitting local variable

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#53141]
In this context:

![image](https://user-images.githubusercontent.com/900690/221763182-4708a481-0aaa-4aea-9838-9fff097b6262.png)

I would like `configurationService` to be suggested first, because it is a type compatible match to the expected first parameter of `getDirection`.

**Comment by mjbvz** [comment]
Minimal example:

```ts
class Foo { }

function doFoo(x: Foo) { }

const foo = new Foo();

doFoo() // trigger suggest in parens
```

![Screenshot 2023-03-07 at 9 47 45 AM](https://user-images.githubusercontent.com/12821956/223506238-47704d7d-10b8-4cda-9040-bf3699973c94.png)

The top completion results all have the same sort text and ranking in this case

**Comment by RyanCavanaugh** [comment]
There's no way we could do this with sufficient performance, and I think even a scoped version of this would be undesirable in terms of reducing predictability.
