### ISSUE TITLE
Feature request : default interface parameters

### ISSUE THREAD

**Issue by xmehaut** [Microsoft/TypeScript#5314]
I would suggest a quite silly but useful (especially for tsx) feature, ie default values in Interface , in order to be able to do such a thing :+1: 
```
interface myinterface {
        a : number = 5;
        b : string ='smthing';
        myfunc(c:number=5, d:string='sfdf');
}
```
By enabling this, we could in a simple manner define default values in react components :+1: 
```
interface myprops {
    avalue : number = 4;
}

interface mystate {
    astate: string= "initial value";
}

class mycomponent extend React.component<MyProps, MyState> {
}
```

**Comment by kitsonk** [comment]
Interfaces, by their very nature, do not deal with implementation.  They are wholly abstract.  Classes (the implementation) already take default values.

**Comment by xmehaut** [comment]
It is not contradictory to be able to specify a default value as a contract to be satisfied by implementation

Envoyé de mon iPhone

**Comment by RyanCavanaugh** [comment]
We've had multiple requests for this kind of thing, but no clear implementation that wouldn't require our emit to be based on type information, which is a no-go.
