### ISSUE TITLE
lib.dom missing "duplex" option in RequestInit

### ISSUE THREAD

**Issue by nornagon** [microsoft/TypeScript#53157]
# Suggestion

## 🔍 Search Terms

I looked for "lib.dom RequestInit duplex".

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The `RequestInit` type in lib.dom seems to be missing the `duplex` option. See https://github.com/nodejs/node/issues/46221 for further details.

## 📃 Motivating Example

https://github.com/nodejs/node/issues/46221 has an example.

## 💻 Use Cases

This is required for spec compatibility.

**Comment by jakebailey** [comment]
You probably want to be reporting this on: https://github.com/microsoft/TypeScript-DOM-lib-generator

**Comment by RyanCavanaugh** [comment]
Please use the lib modification bug template.

**Comment by nornagon** [comment]
Looks like https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1483, for any future bug hunters.
