### ISSUE TITLE
[Feature Request] Support runtime type checking like the package zod

### ISSUE THREAD

**Issue by Employee87** [microsoft/TypeScript#53168]
If I have this

```
interface B {
   bar:string;
}

interface A {
   foo:string;
   bar:B;
}
```

and then I have a abstract JS object like this

```
const r = await fetch("https://mylink.com");
const d = await r.json();
```

I want to do this

```
const matches:boolean = Matches(d, A);
```

This would be a great feature to have. I could use the library `zod`, but only if there is absolutely no plans of this being implemented natively in typescript.

**Comment by fatcerberus** [comment]
Directly from the [TypeScript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> **Goals**
> * Use a consistent, **fully erasable**, structural type system.
>
> **Non-Goals**
> * **Add or rely on run-time type information in programs**, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

So no, this will never be implemented.

**Comment by RyanCavanaugh** [comment]
> I could use the library zod, but only if there is absolutely no plans of this being implemented natively in typescript.

Please use `zod` (or something like it) 🙂
