### ISSUE TITLE
If the parameter of an anonymous function in interface is an empty object, it can match any object.

### ISSUE THREAD

**Issue by HuberTRoy** [microsoft/TypeScript#53161]
### 🙁 Actual behavior

```
    type p = { (props: {}): any; } extends { (props: { visible: boolean } ): any } ? true : false // excepted false but is true
```

### 🙂 Expected behavior

```
    type p = { (props: {}): any; } extends { (props: { visible: boolean } ): any } ? true : false // false
```

### Search

This type will be `false`, so the `{}` is not extends `{ visible: boolean }`

```
type e = {} extends { visible: boolean } ? true : false
```

**Comment by fatcerberus** [comment]
This is correct because function parameters are contravariant.  If the requirement is that your function can accept a `{ visible: boolean }` then one that accepts *any object at all* also works.

**Comment by fatcerberus** [comment]
Likewise, `((x: number) => void) extends ((x: 1 | 2 | 3) => void)` is also true even though `number extends 1 | 2 | 3` is false.

**Comment by HuberTRoy** [comment]
@fatcerberus 

Thanks.

It's may unacceptable in some condition. 

I want the function must have some parameters but it can run with no parameters now. I know this is legal in Js, but I use Ts now. If this is correct it seems losing the meaning of Ts.  or may I have some methods to do the check?

**Comment by fatcerberus** [comment]
If you ask me for a function that accepts an `A` as a parameter, I can give you one that accepts `A | B`.  That’s desirable and doesn’t weaken typechecking because you can still only pass `A`s through the original reference.  Same thing here - just because you get a function that accepts `{}` doesn’t mean you’re allowed to call it with anything other than `( visible: boolean }`.

**Comment by HuberTRoy** [comment]
@fatcerberus 

Thanks, can you give me some advice for this condition? I have no idea how to do it = =.

I wrote a function that intend to accept React Function-Component that must have `visible` props as parameter. 

Any other Function-Component that has no-matched parameters ts will give a type error tip, but the type of  Function-Component default is `FC<{}>` so ts don't show any tip for me. 

```ts
type FC<P = {}> = FunctionComponent<P>;

interface FunctionComponent<P = {}> {
    (props: P, context?: any): ReactElement<any, any> | null;
    ...
}

function giveMeFuntionComponent<T extends { visible: boolean }>(com: FC<T>) {}

const Component: FC = props => { return <div></div> }

giveMeFuntionComponent(Component) // no error.
```
