### ISSUE TITLE
Feature request : propose default typecript libraries

### ISSUE THREAD

**Issue by xmehaut** [Microsoft/TypeScript#5316]
i would suggest to start proposing default high level libraries witten in typescript like those we may find in Dart. 

The openess of typescript is a great advantage, but it is also useful to have a standardized ecosystem to share with other devs... In fact, using typescript like a true langage and not only a transpiler, with ultimately (i dream) using typescript directly in the the browser without having to compile in javascript.

**Comment by plantain-00** [comment]
Here is the typescript design goal at wiki: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

**Comment by xmehaut** [comment]
Thanks York for this reminder. Nevertheless the goals are made to be changed :) when the context of use change ;) 

Envoyé de mon iPhone

**Comment by kitsonk** [comment]
> Nevertheless the goals are made to be changed :)

Well, I would suspect that you would argue why to change the goal before expecting a proposal to be considered.

**Comment by xmehaut** [comment]
I use typescript since its beginning, and i reach a point where i consider typescript like a true language and not only a transpiler. And as a language, it is normal to consider to have the grammar and also the tools and the libraries.
Moreover, the fact that typescript has been chosen for angular in replacement of former atscript is a step  forwrd considering typescript as a true language.
Personaly, typescript plus react has the most potential and i invest in it 

Envoyé de mon iPhone

**Comment by kitsonk** [comment]
> I use typescript since its beginning, and i reach a point where i consider typescript like a true language and not only a transpiler.

Just because you have reached that point, doesn't mean that automatically changes the design objectives of TypeScript.

**Comment by xmehaut** [comment]
Of course :)
But nothing is ever written in the stone, and changing point of view may (should?) always be a creativity process

Envoyé de mon iPhone

**Comment by RyanCavanaugh** [comment]
The web development community changes very quickly and we're not in a position to choose winners and losers in the marketplace of libraries. TypeScript is JavaScript -- if you want a standard set of libraries, get the JavaScript community to standardize first (good luck! :wink:).

**Comment by xmehaut** [comment]
Indeed :(
The fact is we loose to much time to test libraries, frameworks an so on... I m sure that microsoft has chosen its way of developping ; choices are a little death but are necessary. It could be valuable that the typescript team choose also between this js jungle just to enable devs to be efficient.
It is why choose xamarin, or gluon instead of ionic like approaches may be an alternative to js dev
Regards 

Envoyé de mon iPhone
