### ISSUE TITLE
Making number literal type like `1.0` be `1.0` not `1`

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#53172]
# Suggestion
Using string template type, we can distinguish types like `1` and `1.2`, this feature allow us to refine number type into `int` and `float`. But for now, the literal types like `1` and `1.` and `1.0` are all `1`, we can refine 1.2 as `float` number type, but 1.0 or 1. are still `int` type

## 🔍 Search Terms

number literal type 
string template type

## ✅ Viability Checklist

My suggestion meets these guidelines:

 [ * ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
 [ * ] This wouldn't change the runtime behavior of existing JavaScript code
 [ * ] This could be implemented without emitting different JS based on the types of the expressions
 [ * ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
 [ * ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example
See the code in [playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKg8gETlAvFAdhAbhATgbgChDRIoAJAQwGcEB7YAHhiggA9gJ0ATaqa4LgCW6AOYA+VLFYcuvKAAMAJAG8RAMzwUIlbgF9VGrTEpCANnoWEoUAPzbdMzjz4AiAHSvrNu1EEBXCG8bAC4KGnomE3NxbzCWdmd5ZTV0TVwoAGURUTMIS297bLE8pzk3T2DfAKCfKDD1SjNqWvqMbDwiEnBocikqWgZGBQBGdwAGBXEiUl6AJn6IoYU5qa7ZqABJdCiylwx-AFsAIzxJNBSYSz35IwyAJUKoe5u+AWExKvsByMZ7yUS5SgjWarRs9hgVTCmBwuCh7VhcQRnWIGwAYmY6JRdoD9ugjqdcOdFKorgpXlA7s9CPYXrj5O8ck8fkN-hSak9IaFkXDuTC8IRoR0CMRuBAAMZmSi4aDqfzocXAIR0dDAxibCn4k54AA0UDRmoJZwAFEIwtsmJtxHr1GEMVimGjxABKMJYOhCbhddTGkZ6sZzZ2EH1+qBjIMh9xzf1RiO+vVzdxBwhAA)
![image](https://user-images.githubusercontent.com/21278900/223893183-94038309-71fa-445a-ac6d-1214e8273449.png)

## 💻 Use Cases
We can create a more stricted function `f` which accept two parameters, one is `int` type, another is `float` type.

**Comment by jcalz** [comment]
Given that `1 === 1.0` I'd be very confused if the TypeScript compiler were ever to treat them differently.  I'm afraid I don't understand the use case; why do we want to control how developers write their numeric literals?

**Comment by RyanCavanaugh** [comment]
I don't see how this makes any sense either. `1` and `1.0` are two ways of writing the same thing; it's not like `f` can tell which you wrote. It seems like you have a codebase-specific style convention, which is a linter's job to handle.
