### ISSUE TITLE
Destructuring of types

### ISSUE THREAD

**Issue by kjetilhartveit** [microsoft/TypeScript#53185]
# Suggestion

## 🔍 Search Terms

destruct, destruct types

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would like to destruct a type (in the shape of an object) to other types using the same syntax as when destructing runtime objects to variables. 

As destructuring is already an established concept within runtime JS, I figure it would be fairly easy to grasp and not so intrusive to introduce to types. 

## 📃 Motivating Example / Use Case

Imagine a "function" type (in the example below called `ApiTypes`) which takes a generic type and assigns type variations based on the generic to properties. We could access the properties using a string index, but sometimes it's more elegant to extract them to "top-level" types. Today we would have to assign each variable manually, and this gets tedious if we have many uses like this. It would be more convenient to destruct the types in a single assignment.

[Full playground example](https://www.typescriptlang.org/play?#code/LAKALgngDgpgBABRgeygGxgJRgcwJYDOYAThHALxwDeocdcAZnsUQHICGAtjAFxxHE8AOxwBuWvTTs2XXvxLCxcUAF8A2gF1xIUJFhwAajAAWeAMYZs+AWUo0Q9OJ2QATGGj4DF2xxBjtiPiEAV04AIxhibXUtUF1oeAApZDCrQhJbagk6MDwwDE8FER96YRdgm0LBYtVNbVAAega4djgAIigAmCEwNrg9eDNif1yRJ3YhMgJgsIGCBoA3ALx2XOQhAjgw6RgXOHW4fAXuw+7I836E+P0AQSg8ABUEggAeB7gYAA8wbpdN4KEAGshMgAO5CTQAPgoWQc9DSlTgDwANNk4ABJH6cPgPNQhcKRDSouF0TEwTiYdigvhUOBqBBwYRwQEwCDIBhIvGhCLEDQtTYAYXY9zA7DQeAAXjAXl4xgAyRCQjQ4rkE3n0vkqVT1EBNfqudhkUHwUHIYJoPbGdjHfX8gh4HBCD7sMzGS76TgTYJitBkPAc41wU3mvbilm2r4kF1gfrGeBzW1gOPtMCoAC0GGOaDaADpGs1-bHIjAAOSbT2Td0wTZJwinMA13Z4M0EPPgBKIFDoGBPWCbSh3R7PF5IVCWXDpUiQ7QDTssA6UUfd3vVtQlsmcEuxdv6JDzoSU0EwpcYFcENcbw9bmcdoymCw954wwdnl538zj6wZafXeDvh8wv+p7PBeWLXr+hgmB+WBUoBUEPmeoHkle26zskYRns+9yvuhCLfje+joTC6GIeuYGoR2uGwZQJEgWRyFUuBOi6s0xhgoyMZmGaFpbPAhaBlxIZwG4AjBGYMZzG2s60hufB7gQ6zIhiWKHnJkQKQesEqFhQ59iOXafpOEA-ju8AyVifBATASmXlSlnwZYWk6a+Vl4VOBFmcp5J8OhNkqXZcBUUe2kDthw64RONjTkAA)

```typescript
type PeopleRegistry = {
    firstName: string;
    lastName: string; 
}[];

// a "parent" type creating many subtypes/variations based on given generic type
type ApiTypes<T extends unknown[]> = {
    Registry: T,
    Item: T[number],
    ItemRaw: { [P in keyof T[number] as Capitalize<string & P>]: T[number][P] }
};

// today we would have to assign each type manually if we would like to extract the types to the "top-level".
// if there's many types this gets tedious.
type PeopleTypes = ApiTypes<PeopleRegistry>;
type Person = PeopleTypes['Item'];
type PersonRaw = PeopleTypes['ItemRaw'];

// how it could look if we could destruct types.
type { Item: Person, ItemRaw: PersonRaw } = ApiTypes<PeopleRegistry>;
```

**Comment by RyanCavanaugh** [comment]
Duplicate #35396
