### ISSUE TITLE
Name Method is not working But all method are working why?

### ISSUE THREAD

**Issue by Ghayyas** [Microsoft/TypeScript#5318]
// Hi While im trying to learn typescript im getting Confuse with this code..

class Startup {

    public static main(): number {
        console.log('Hello World');
        return 0;

    }
}

Startup.main(); // works fine

class startUp{ 
       
       public static run(){
	alert('hellow world run Static')
	 }}
startUp.run();     // still works fine

class startup{

       public static name() {
		alert('hellow world');	
		}
}
startup.name(); //getting error why i dont understand??

/* i dont understand why its not working.. */

**Comment by xLama** [comment]
Due to function name.  You can notice if you exec Startup.name you get "Startup". Startup is a function and functions have a name property.


http://i.imgur.com/fEiEu6s.jpg

**Comment by RyanCavanaugh** [comment]
See #442
