### ISSUE TITLE
Enums can't be properly used as type parameters to other types in function signatures

### ISSUE THREAD

**Issue by mashedkeyboard** [microsoft/TypeScript#53180]
# Bug Report

### 🔎 Search Terms

enum type parameter, enum types, type conversion enums, enum type assertions

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about enum types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5#code/KYOwrgtgBAKsDOAXAouaBvAUFHUDKA8gLLID6AwgQHIzI1QC8UARIgos5gL6aaICeAB2Cx2ABQCGAJwkQYQ4AB5EAPkZQsuKGyQBLNhABc27rwBmYEAGNEugPYht7AGKWb9kAAo0AI2BTjKkg-KQAaKAh+eWEAE2jgYzgkSRk5BWUFOzMoX38VAEoNbFwAehLYAAtdeCgYuwQoAHc7KQBrADpinCsHeDsAG2B2-rsAc09I+LiFdp1bA3yAblM512tbB08AVnD0Of1gIygAdi4l8zcNx1XLjwB1FtbpO0sYif5USGMBYSzRJE+EHCkwU02EiXE0lk8UUllaIDsjRABSKWjKlWqtXqNWabU6Wh6ID6g2GY087ym8SgEhqSUQKWh6R+wD+kUBBVm7AOEHOPBu63uj2er08dMBu32BghALQ7UIJAo1FoNDOy0wFgFDicSDW7gcACEJDEAIzvQHfTLZMVoYFRUHxaX0qFpYQZX7ZNloFGaUrlGBVHEOADkiCaj3CfisEjA8BEiAqcctEQ+aCgmPjifd2iT1sg4QRoYz2azuYg+NwhOJQxG4xBsXinL0C2WfJctwNRtNpYlXKl-xQsvlZEoNDoMFVF011zbU8NMQATGa0BaS+xxcnKQpHQyXUpPZBvV0oOj-ZjmiAQ2G2hHgFGYyJmPvoFJgGZ-DVEHZqVAAG4SfpgMAzDlt0vQDNWZJ1sAYJDJKhy8nwM56iAc6Lt2GhwUcpZysQw5KmOE7qu2046sRc4AMyKE+VLAAAHmwIAxLSa5ekuXzJoC8S2pu4L9juMLUQoh5on6AZhheoa4q01Khv+-Q3nesbaAmaYgIIYChk+aY1H8zIsMyfylsw+Z2KGukKCwRlHpW4GkrWdr1jMmEIfyyEUYopYqKKLF5hhvaHI6gI4QqI7KuO5xEVO2qILqVxzgALFRKaQDR9GgEx-bsmxRwGR6yW7tx9pbnxzoCfl8TCb6GKBhJV7SRIsn9P0UDAPoCZhFAkbRkpgnCNp37MuEfRQPwLxQFGtV1MWLJ5ZxCjWWBJI1hSRXCI28zwS2iGkbORqJZ53kyr5ez+VhPllkOiqjiqSxAA)

### 💻 Code

```ts
enum TestEnum {
    SOME_CONTENT = "test"
}

type TestParamType<t> = {
    testitem: t
}

function testFunction(number: Number, myTypedType: TestParamType<typeof number>) {
    // This does work.
    console.log(myTypedType.testitem);
}
testFunction(5, {testitem: 7});

function testFunctionWorkaround(myEnum: typeof TestEnum, myTypedType: TestParamType<unknown>) {
    // This does work.
    console.log((myTypedType as TestParamType<typeof myEnum>).testitem);
}
testFunctionWorkaround(TestEnum, {testitem: TestEnum.SOME_CONTENT});

function testFunctionBad1(myEnum: typeof TestEnum, myTypedType: TestParamType<typeof myEnum>) {
    // This won't work, because the typeof myEnum is the typeof typeof TestEnum, not the typeof TestEnum.
    console.log(myTypedType.testitem);
}
testFunctionBad1(TestEnum, {testitem: TestEnum.SOME_CONTENT});

function testFunctionBad2(myEnum: typeof TestEnum, myTypedType: TestParamType<myEnum>) {
    // This won't work, because "myEnum refers to a value".
    console.log(myTypedType.testitem);
}
testFunctionBad2(TestEnum, {testitem: TestEnum.SOME_CONTENT});

function testFunctionBad3<myEnumType extends TestEnum>(myEnum: myEnumType, myTypedType: TestParamType<myEnumType>) {
    // This won't work at all, because the input myEnum is of type "typeof TestEnum", not of type "TestEnum"
    console.log(myTypedType.testitem);
}
testFunctionBad3<TestEnum>(TestEnum, {testitem: TestEnum.SOME_CONTENT});

function testFunctionBad4<myEnumType extends TestEnum>(myEnum: typeof myEnumType, myTypedType: TestParamType<myEnumType>) {
    // This won't work at all either, because myEnumType is a type, so you can't do typeof myEnumType
    console.log(myTypedType.testitem);
}
testFunctionBad4<TestEnum>(TestEnum, {testitem: TestEnum.SOME_CONTENT});
```

### 🙁 Actual behavior

Not entirely clear to me whether this is really a bug report or a feature request, but... there doesn't seem to be any way to use the type of an enum in the signature of a function to act as a type parameter to another type in the function signature. Any way I've tried to do so fails for different reasons - I've commented the approaches I've played with above, as well as the <unknown> workaround.

### 🙂 Expected behavior

Of the approaches I've tried, the one I would have expected to work really would have been `myEnum: typeof TestEnum, myTypedType: TestParamType<myEnum>`; elsewhere, the TypeScript compiler lets enums act as a sort of hybrid of an object and a type, so it's sort of weird that it would get so picky here about them being one or the other and not both.

**Comment by RyanCavanaugh** [comment]
It seems like you're trying to write this?
```ts
function foo<E, K extends keyof E>(e: E, item: TestParamType<E[K]>) {
    console.log(item.testitem);
}
foo(TestEnum, {testitem: TestEnum.SOME_CONTENT});
```

**Comment by RyanCavanaugh** [comment]
> But then if we extend it:

What you want to write here is `E extends typeof TestEnum`.

Can you show me a test suite or something? It's much easier to just write a function signature that does what you want than to try to reverse-engineer what you want the expected behavior to be based on the examples that don't work.

**Comment by mashedkeyboard** [comment]
That does incidentally solve the direct problem I was having - so thank you! - but I'm still not sure there isn't some weirdness going on here with the way that the language actually works. To my mind, it makes little sense that

```ts
function testFunction(number: Number, myTypedType: TestParamType<typeof number>) {
    // This does work.
    console.log(myTypedType.testitem);
}
```
should work fine, but
```ts
function testFunctionBad1(myEnum: typeof TestEnum, myTypedType: TestParamType<typeof myEnum>) {
    // This won't work, because the typeof myEnum is the typeof typeof TestEnum, not the typeof TestEnum.
    console.log(myTypedType.testitem);
}
```
should not work at all. 

The type of an instance `myEnum` of the type of TestEnum should be the type TestEnum, not the type of the type of TestEnum, surely? In much the same way that in the first one, the type of the instance of Number `number` is `Number`, not `typeof Number`.

**Comment by RyanCavanaugh** [comment]
You seem to be confused about what the `typeof` operator does. [Docs here](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html)

**Comment by fatcerberus** [comment]
FWIW I still regularly tie my brain into knots trying to reason about `Enum` vs. `typeof Enum`.  I’m not sure why but it seems inherently more confusing than the equivalent dichotomy for classes.  If I had to guess it might just be the difference between `Enum.A` and `Enum["A"]` that throws me…
