### ISSUE TITLE
Type error when reconstructing pattern literal property of mapped type

### ISSUE THREAD

**Issue by gomain** [microsoft/TypeScript#53196]
# Bug Report

### 🔎 Search Terms

reconstruct pattern literal property mapped type

### 💻 Code

```ts
type A = {
    key1: string;
    key2: number;
    //key2: string; // if all props are same type, ok
};

type PA = { [K in keyof A as `p_${K}`]: A[K] };
// force eval type for more detailed error
//type PA = { [K in keyof A as `p_${K}`]: A[K] } extends infer X 
//  ? { [ K in keyof X]: X[K] } 
//  : never;

function test<K extends keyof A>(key: K, pa: PA): A[K] {
    return pa[`p_${key}`];
}
```

### 🙁 Actual behavior

```
Type 'PA[`p_${K}`]' is not assignable to type 'A[K]'.
  Type 'PA' is missing the following properties from type 'A': key1, key2
```
When expand `PA`

```
Type '{ p_key1: string; p_key2: number; }[`p_${K}`]' is not assignable to type 'A[K]'.
  Type '{ p_key1: string; p_key2: number; }' is missing the following properties from type 'A': key1, key2
```
### 🙂 Expected behavior

No error.

### Observation

1. The error message is surprising, why would `PA` need to have properties of `A`? This suggests the property types were not even considered yet.
2. But when all properties of `A` have the same type, its ok. I.e. whatever prop we take it would yield a single type. So property types were considered.

**Comment by RyanCavanaugh** [comment]
There's not really a way to observe that this function is correct except if all the properties are of the same type. *Iterating* through all the possible inhabitants of `K` works, but that's not a scalable way to check a generic function.
