### ISSUE TITLE
Filter getCompletions results based on location

### ISSUE THREAD

**Issue by mhegazy** [microsoft/TypeScript#532]
See below image.  Intellisense for the type name shows all identifiers.  Only types should be shown.

![attachfilehandler](https://cloud.githubusercontent.com/assets/8000722/4051544/8054e782-2d62-11e4-91ea-c301baa75835.png)

**Comment by jakebailey** [comment]
Just looking at old bugs; this one was fixed in #16206. Only types appear in the completion list in this code.

(A three digit issue; not many of those left...)
