### ISSUE TITLE
TypeScript 5.0 decorators don't work when `noUnusedParameters` is enabled and the context is unused

### ISSUE THREAD

**Issue by jlachniet** [microsoft/TypeScript#53208]
# Bug Report

In the current version of TypeScript, decorators which don't use the context do not work properly when `noUnusedParameters` is enabled. If the decorator includes a context parameter, then the compiler reports an error on the unused parameter. If the decorator does not include the context parameter, than the decorator cannot be used, as the decorator is called with one too many arguments.

### 🔎 Search Terms

`decorator, decorators`

### 🕗 Version & Regression Information

This changed between versions 4.9 and 5.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230311&experimentalDecorators=false#code/GYVwdgxgLglg9mABAWQJ4BECmE4CcCGUeAFFPrgOaZQBciYmA7osQHTvkUDOdDAbplwBKRAF4AfInABrMHEZgRAbwCwAKESbEOMFzgAbTK31wKpTtSEBudQF916gAJosOAkVyJ1Effi5cUVABhX39EJXs1IA)

### 💻 Code

```ts
function MyDecorator(target: new (...args: never) => unknown) {
    console.log(target);
}

@MyDecorator 
class MyClass {}
```

### 🙁 Actual behavior

Code compiles without errors.

### 🙂 Expected behavior

TypeScript throws the following error:

```
Unable to resolve signature of class decorator when called as an expression.
  The runtime will invoke the decorator with 2 arguments, but the decorator expects 1.
```

**Comment by fatcerberus** [comment]
Workaround: `_context`

**Comment by danielrentz** [comment]
This unused parameter is even useful to restrict your decorator to specific types.

For example, with
```js
function MethodDecorator(target: (...args: any[]) => any, _context: ClassMethodDecoratorContext) {
}
```
TS will give an error when trying to use the decorator anywhere else than for a class method.

**Comment by MondQ** [comment]
> Workaround: `_context`

This comment is useless without providing more context on how to use it. Thankfully the person below did.
