### ISSUE TITLE
Suggestion: Deep Partial

### ISSUE THREAD

**Issue by kaikaibenkai** [microsoft/TypeScript#53219]
# Suggestion

## 🔍 Search Terms

Sometimes I have config files like

```ts
export default defineMyConfig({
  title: 'Hello, World!',
  database: {
    port: 5330,
    password: '12348765',
  },
});
```

`defineMyConfig` will **deep merge** the given config options and default config.

...But what's the given options' type? `Partial<T>` isn't deep.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Adding a built-in type like `DeepPartial<T>`.

## 📃 Motivating Example

(in the fist paragraph)

## 💻 Use Cases

(in the fist paragraph)

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/51841#issuecomment-1344953135

**Comment by kaikaibenkai** [comment]
Ok then...
