### ISSUE TITLE
[Bug] Excess properties are allowed when using `reactive()`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/TypeScript#53212]
# Bug Report

### 🔎 Search Terms

"excess properties"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about typescript.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAJwKYENowG6oDwAqiqAHlKmACYDOicARgFarQB8AFA4wFyIECUvIgG8AUIhSooIZEi6iAvqNEww5ZMEypEAQURiJ6XtSjJVAc0XKICE4nQBGXnoC8+8fd4BydF4A0HvTe-ogA9KGIgLwbgBI7iFAAFshwAO5gVqLhiABicMiI1HAAttpo6AVgfnwAyogwtMCq2skwCXHxdZWouEgJcCDm8RkRpVi47PyI8ahoktKytMKe+aYWlUHLZmDmiEqZ7NSo2oV9B3C4eapt2gAOADboAJ7mSeCU-KI2YHboAEzOiG4RrAxgYlj5-IFgpVMjFEGA4FA2klUop3kA)

### 💻 Code

```ts
function reactive<T extends object>(obj: T): T {
  return obj
}

interface A {
  a: string
}

const a1: A = {
  a: 'a',
  b: '', // 👈 thrown
}

// For some reason, TS is fine with this, even though
// reactive() here returns { a: string, b: string }
// (see mouseover in the playground)
const a2: A = reactive({
  a: 'a',
  b: '', // 👈 not thrown
})
```

### 🙁 Actual behavior

```ts
// For some reason, TS is fine with this, even though
// reactive() here returns { a: string, b: string }
// (see mouseover in the playground)
const a2: A = reactive({
  a: 'a',
  b: '', // 👈 not thrown
})
```

### 🙂 Expected behavior

```ts
const a2: A = reactive({
  a: 'a',
  b: '', // 👈 thrown
})
```

**Comment by MartinJohns** [comment]
This is working as intended. The inferred generic type for `reactive` is based on the input arguments, not on the contextual type (what you try to assign it to). So the inferred type is `{ a: string; b: string }`, and this type is assignable to the type `A`.

**Comment by wenfangdu** [comment]
@MartinJohns Thanks for replying, how to make the inferred type `{ a: string; b: string }` not assignable to type `A`?

**Comment by MartinJohns** [comment]
You can't. TypeScript is [structurally typed](https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing). What you want would require #12936, which is very unlikely to happen for at least a few years (if ever).

**Comment by MartinJohns** [comment]
The error you see in line 11 is part of the "excess property checks" feature, which is more a linter feature than part of the type system. It only applies to object literals. Here's an example where it wouldn't work as you probably expect:

```typescript
const a1 = { a: 'a', b: '' }
const a2: A = a1
```

This works fine because the type for `a1` is inferred to be `{ a: string; b: string }` again, then upon assigning only a compatibility check is performed. Excess properties don't prevent compatibility.

**Comment by wenfangdu** [comment]
@MartinJohns Thank you for the clear explanation!
