### ISSUE TITLE
Type argument not preserved in object if object value is a chained expression

### ISSUE THREAD

**Issue by kelvin2200** [microsoft/TypeScript#53217]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.9.5&ssl=21&ssc=2&pln=1&pc=1#code/C4TwDgpgBAKhDOwoF4oG8BQVtQIYH4AuKRAJwEsA7AcwG4scAjYzHNqAYyJOApoewBfDIPoZQkKAAUU6AVABmlAIwAeGAD4AFLlLVuMAJSEAGuo3ylAJnM69B42c0iM48NCcbZMKADJpYhwA9pSIUEioaIJ48AGuwaFIAB7EcGGR8gD0mVoS0LrUAK4AthCUSOSxuABuuOQANriM9dAh9SBQABYQpBCGWZkAtMMjo2PDgC2EUPLM4QB0SspahguUVsurS-2CQAA)

### 💻 Code

```ts
type Test = {
    a?: string;
    b: {
        c?: string
    }
};

type P = {
    fn1<T>(arg?: T):X<T>
    fn2<T>(arg?: T):X<T>
}

type X<T> = T & P;

const t = {} as P;

const x: Test = {
    //(type argument is available only here)
    //-----------------↴ 
    b: t.fn1().fn2().fn1()
}
```

### 🙁 Actual behavior

It seems that the type argument is available only on the last function call in the chain. I've read similar issues, but I can't figure out if this is truly a design limitation or a bug.

### 🙂 Expected behavior
I'd expect every function in the chain to have the same type argument, not just the last one, obviously without having to declare it manually.

**Comment by RyanCavanaugh** [comment]
I don't understand what you mean. Adding type arguments at any point works:
```ts
const x: Test = {
    //(type argument is available only here)
    //-----------------↴ 
    b: t.fn1().fn2().fn1()
} 

const x2: Test = {
    b: t.fn1<string>().fn2().fn1()
} 
const x3: Test = {
    b: t.fn1().fn2<number>().fn1()
} 
```
Can you clarify?

**Comment by kelvin2200** [comment]
Like I said in the **Expected behavior** `"...without having to declare it manually."`
The point is, the type should be inferred on every function in the chain, exactly like it happens for the last call.
For a deeply nested structure, manually declaring the type is not an option.

**Comment by kelvin2200** [comment]
For the type in the example, if you go to the playground and hold the mouse over the last function in the chain, you'll see that it's type argument exists, is inferred, and does not have to be declared manually. Same thing doesn't happen for the previous methods in the chain

**Comment by RyanCavanaugh** [comment]
This behavior falls out of the inference rules. Type arguments don't apply beyond their specific application; that much is very much intentional.

**Comment by kelvin2200** [comment]
Such an "in-depth" answer...
