### ISSUE TITLE
HTMLPictureElement interface definition is missing

### ISSUE THREAD

**Issue by rayshan** [Microsoft/TypeScript#5323]
Reference: https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element

**Comment by RyanCavanaugh** [comment]
Looks like this is part of the draft specification. @zhengbli what's our plan for those?

**Comment by zhengbli** [comment]
Our support to these draft specification is normally determined by how the current browsers support it. If it is implemented in most of the browsers, we would add it now. If not, we might hold it and open for discussion.

**Comment by rayshan** [comment]
If I understand correctly based on this FAQ: https://wiki.whatwg.org/wiki/FAQ#What_does_.22Living_Standard.22_mean.3F, the spec is a "living standard", i.e. will never be "complete" or "frozen".

For reference: http://caniuse.com/#feat=picture (currently shows 54%)

**Comment by zhengbli** [comment]
Looks like Firefox and Chrome are already supporting it, plus Edge is also adding support soon. It should be added in then.

**Comment by mhegazy** [comment]
PRs are welcomed. here is some documentation for adding new types to lib.d.ts: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes
