### ISSUE TITLE
VSCode TypeScript types-registry Performance Bug

### ISSUE THREAD

**Issue by agallio** [microsoft/TypeScript#53235]
Type: <b>Performance Issue</b>

VSCode TypeScript keeps running `npm install types-registry@latest` wether the window is opened or even closed! This process makes 100% CPU all the time on my MacBook Pro M1 Pro 14" 2021. This makes my Mac runs hotter, and drains the battery so much. Please fix this.

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.57GB free)|
|Process Argv|. --crash-reporter-id 36f047c5-4fb0-47f5-b14f-86c1a3245f56|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   29	   180	  5581	code main
   10	    82	  5584	   gpu-process
    0	    33	  5585	   utility-network-service
   68	   393	  5587	   window (index.jsx — agallio.xyz)
   30	   180	  5588	   shared-process
    0	    66	  5590	     ptyHost
    0	    66	  5593	     fileWatcher
    0	     0	  5678	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   180	  5589	   utility-process
    0	   147	  5592	     electron-nodejs (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/_w/8g5fd_tn1ks7cklkr_c6t_t80000gn/T/vscode-typescript501/b7be7f9d6170981475a5/tscancellation-85b4d4295cb860a931aa.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	   328	  5594	     electron-nodejs (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/_w/8g5fd_tn1ks7cklkr_c6t_t80000gn/T/vscode-typescript501/b7be7f9d6170981475a5/tscancellation-d4ab4655c236db7fec79.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc)
    0	    98	  5608	       electron-nodejs (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/agalliosamai/Library/Caches/typescript/4.9 --enableTelemetry --typesMapLocation /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation)
    0	   147	  5610	     electron-nodejs (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/agalliosamai/.vscode/extensions/dbaeumer.vscode-eslint-2.4.0/server/out/eslintServer.js --node-ipc --clientProcessId=5589)
    0	    49	  5637	     electron-nodejs (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=5589)
   22	    82	  5676	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.jsx — agallio.xyz)
|    Folder (agallio.xyz): 1154 files
|      File types: js(509) json(313) css(73) svg(31) pack(20) jsx(20)
|                  woff2(12) sql(11) png(11) webp(9)
|      Conf files: package.json(3) dockerfile(2) jsconfig.json(2)
|                  settings.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.4.0
gitlens|eam|13.3.2
prettier-vscode|esb|9.10.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
funwalk2:30682974

```

</details>

**Comment by RyanCavanaugh** [comment]
This definitely isn't affecting everyone. Is there anything unusual about your system configuration we might want to know about?

**Comment by agallio** [comment]
IMO, there's nothing unusual about my system configuration or even my VSCode setup. I just reinstalled my VSCode and the issue still persists. Some additional information that might help:

My VSCode `settings.json`:
```json
{
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "diffEditor.ignoreTrimWhitespace": false,
  "editor.accessibilitySupport": "off",
  "editor.inlineSuggest.enabled": true,
  "editor.stickyScroll.enabled": true,
  "editor.tabSize": 2,
  "editor.wordWrap": "on",
  "emmet.triggerExpansionOnTab": true,
  "git.confirmSync": false,
  "github.copilot.enable": {
    "*": true,
    "markdown": true,
    "plaintext": false,
    "yaml": false
  },
  "json.schemas": [],
  "liveServer.settings.donotShowInfoMsg": true,
  "security.workspace.trust.untrustedFiles": "open",
  "terminal.external.osxExec": "iTerm.app",
  "terminal.integrated.env.osx": {
    "FIG_NEW_SESSION": "1"
  },
  "terminal.integrated.fontFamily": "MesloLGS NF",
  "window.commandCenter": true,
  "workbench.iconTheme": "material-icon-theme"
}
```

VSCode process window:
<img width="834" alt="Screenshot 2023-03-15 at 07 40 15" src="https://user-images.githubusercontent.com/22767465/225174279-28457b75-06bd-456f-9cbb-3c49e50fe094.png">

**Comment by ameliemaia** [comment]
This happens for me too.

**Comment by RyanCavanaugh** [comment]
A TS Server log might help too - see https://github.com/microsoft/TypeScript/wiki/Getting-logs-from-TS-Server-in-VS-Code

**Comment by agallio** [comment]
This is my TS server log: [tsserver.log](https://github.com/microsoft/TypeScript/files/10985996/tsserver.log). I've updated to VSCode 1.76.2 and it is still happening! 

Please fix this. This isn't good—running something in the background and consuming that much CPU & memory without the user's consent.

**Comment by jakebailey** [comment]
Which version of npm is installed globally on your system?

**Comment by agallio** [comment]
I use `nvm` to manage the `npm` version. Currently, I'm using node 16 with npm `8.19.3`.

**Comment by jakebailey** [comment]
Thanks; that may not be the version that vscode gets in this context, if that's only being added via bashrc/zshrc, technically.

When this happens, can you try running something like this:

```
$ ps auxwwwe | grep 'npm install' | grep -v grep
```

And then grab the `PATH` variable in the output? I don't recommend posting the entire output as it'd be the full environment variable set of the process and it could contain secrets, but, mainly I want to make sure that it's a recent version of npm.

**Comment by fatcerberus** [comment]
> ` | grep -v grep`

What does this do?

**Comment by jakebailey** [comment]
> > ` | grep -v grep`
> 
> What does this do?

When you grep the running processes, the first grep is running so you'll get two matches.

**Comment by agallio** [comment]
@jakebailey I upgraded the npm version to `9.6.2`, but the issue still persists. This is the result of the command: 
```
agalliosamai     10425 113.9  1.6 409669360 275920   ??  R     1:00PM   0:07.73 npm install types-registry@latest
```
<img width="959" alt="image" src="https://user-images.githubusercontent.com/22767465/225529075-a3660b28-e18f-4fb7-9626-8ea3b9af15d6.png">
<img width="825" alt="Screenshot 2023-03-16 at 13 03 58" src="https://user-images.githubusercontent.com/22767465/225529182-756317cb-b3d5-45b3-adb9-3f7db943be93.png">

**Comment by jakebailey** [comment]
Hm, it should have spat out loads of info. Does System Monitor give you a way to get a path to the binary?

**Comment by agallio** [comment]
Activity Monitor
<img width="553" alt="image" src="https://user-images.githubusercontent.com/22767465/225532296-136351df-d7a0-4382-914d-a4e6372bb0dd.png">

**Comment by jakebailey** [comment]
Hm, I was hoping it'd say more.

If you create a blank project and run that same command, does it also hang there?

**Comment by agallio** [comment]
Even with only a blank javascript file:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/22767465/225541612-0b0d63df-8719-4531-be0a-8792f14c3d30.png">

**Comment by jakebailey** [comment]
To be clear, I'm asking you to run "npm install types-registry@latest" by hand and see if it hangs.

It is helpful that you can reproduce it, but so far I'm at a loss as to why npm is hanging. We should probably add a timeout for it, but, please do test npm directly.

**Comment by agallio** [comment]
It's not hanging. It can be installed fine. Just the VSCode one that's hanging:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/22767465/225552732-668378f1-9ecb-435f-8ed0-b05c64bca604.png">

**Comment by jakebailey** [comment]
Very strange. If that's the npm being used, there's no reason for it to be hanging like that.

Can you run `type -a npm` and post the output?

**Comment by agallio** [comment]
`type -a npm`:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/22767465/225795057-23ba2bc4-99cf-4d02-ab61-3efbf2074ea2.png">

The new TS version artifact doesn't fix anything:
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/22767465/225796310-d127a6a0-df8f-48c3-83fd-c9832d4ecacc.png">

**Comment by jakebailey** [comment]
Thanks, that at least shows that it's that same npm.

Can you check `top` and verify that the parent process of that `npm install` is in fact the dev version of TypeScript?

**Comment by agallio** [comment]
`top`: 
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/22767465/225797664-9c7bd6fd-6a4e-4052-b074-01488cb360ef.png">

**Comment by agallio** [comment]
I think I found the culprit. The TS caches inside the `~/Library/Caches/typescript` are broken. I delete them and open VSCode again, and it can re-install the types-registry without hanging. It seems like it's because the last version I used  (can't remember exactly the version number) doesn't install the types-registry with `npm` directly (IIRC though, CMIIW).
