### ISSUE TITLE
Automatically infer context type constaint for class methods

### ISSUE THREAD

**Issue by Larissa-Kravtsova** [microsoft/TypeScript#53237]
# Suggestion

There is a difference in TS behavior that depends on whether the type of `this` for method is explicitly declared or inferred: [typescript playground link](https://www.typescriptlang.org/play?#code/PTAEFEA8EMFsAcA2BTUBGAUBgxo6BnfCGBFNUAbw1BtHgCcBLAN2gBdUAzR5RAE1ABedAG4stUPgAWAewDuACgCUlahNr1kbAK70AdqDZTG+AHTdefMRIC+GOxhRtQyEkmTlhe5HOJx3aMpiTpKycp4ubmSm0vJiGK7+0bGKSmLYMnr4MiimiDIA5gopgUppoCCgAEraemyMsKjI9PQy9FgYlVBJqABMWLgERN2kyL2qEgws7Fw8-EKi4rQpCkYmAFx+o70qVOoaWroGa2YW-Na0dg4hidsL3r4j7r1Bjlqh8uPCt88xYfE-FC9P7yV4ZLI5ZB5QrFMIvMoiCpgADCMgQjBQAFp6o0XC02hggA)

If inferred:
```ts
class Example1 {
    private field = 1;

    show() {
        return this.field;
    }
}

let example1 = new Example1();
let show1 = example1.show;

example1.show();
show1(); // Runtime error
```

If declared explicitly:
```ts
class Example2 {
    private field = 1;

    show(this: Example2) {
        return this.field;
    }
}

let example2 = new Example2();
let show2 = example2.show;

example2.show();
show2(); // Compile-time error: The 'this' context of type 'void' is not assignable to method's 'this' of type 'Example2'.
```

I believe it would be more consistent and type-safe if it behaved in Example1 the same way as in Example2: if method is using `this` then it requires `this` to be object of given class.

## 🔍 Search Terms

- this
- context 
- constraint
- type

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

This will probably be a breaking change for mobx code that uses decorators to automatically bind methods to objects.

## ⭐ Suggestion

Make inferred type for methods that use `this` be `methodName(this: ClassName, ...): ReturnType` instead of simply `methodName(...): ReturnType`.

## 📃 Motivating Example

More errors will be caught at compile-time: if developer tries to pass method as callback it will fail except for cases where `this` isn't used.

Example:

```tsx
class SomeState {
  // ...

  doCoolStuff() {
    // ...
    this.evenCoolerStuff();
  }
}

function SomeComponent(props: { state: SomeState }) {
  const { state } = props;

  return (
    <div onClick={state.doCoolStuff} /> /* will emit error at compile-time */
  );
}
```

## 💻 Use Cases

- It allows to detect errors early when passing methods as callbacks and forgetting about `.bind`.

**Comment by Larissa-Kravtsova** [comment]
> Sounds like a duplicate of #28548 to me.

Oh. Yes, it definitely is.

**Comment by Larissa-Kravtsova** [comment]
NVM, it is exact duplicate, I've reread that issue.

**Comment by fatcerberus** [comment]
Yeah, `this` isn't inferred.  If you don't specify it, it's just `any`.
