### ISSUE TITLE
Feature request: Please make the Playground editor embeddable in other web applications

### ISSUE THREAD

**Issue by T18970237136** [Microsoft/TypeScript#5324]
Hi,
I think TypeScript is a great language and I really like the web-based [playground editor](http://www.typescriptlang.org/Playground) editor due to its auto-completion/Intellisense features (which also shows method documentation, etc).

Unfortunately the editor doesn't seem to have a license so that it could be used for other web applications, as discussed here: http://typescript.codeplex.com/discussions/401549

Our use case: We are developing a web application where users can type their own Javascripts/Typescripts which extend the server's functionality. When the server runs these scripts, it provides an API object with defined properties and methods.
So, TypeScript would be ideal here because we can write a .d.ts definition file containing the API definition and then present a typescript editor which uses this definition file.

Then, when the users edit their scripts they would get auto-completion with IntelliSense etc.

Currently we are trying to use one of the alternatives mentioned in the above Codeplex discussion that is based on the ACE editor (e.g. the one from basarat), but there seem to be some bugs which don't allow a smooth editor experiene, and its auto-complete feature doesn't show property types, documentation etc.

Would it be possible to release the Playground editor under a license (which wouldn't need to be opensource) that allows to embed it in other application?
Thanks!

**Comment by mhegazy** [comment]
The playground is a component that we, the TypeScript team, do not own. The VSCode team would be the authority here. We use it in the playground in the website, but can not licence it for repackaging. We have gotten this request multiple times, and the playground editor with all the intellisense support is an awesome product, and personally I would love to see it in more places.

//CC: @egamma, he might have more comments here.

**Comment by T18970237136** [comment]
Hi @mhegazy,
thanks for your reply!

As an alternative if the repacking won't be possible, I could image a variant using an iframe to embed the editor that would also work for us (but I don't know if this also requires a license or something like that).

For example: The typescript editor currently allows to submit userdefined content in the querystring, e.g. http://www.typescriptlang.org/Playground#src=var%20s%3A%20string%20%3D%20%22Hello%20World!%22%3B%0A%0A%0A

Now, if there were a page similar like the one above that would accept parameters submitted in a POST body containing the script content and .d.ts definitions (either the content directly or a CORS-enabled URL reference) and a destination URL, the page could allow to edit the submitted content, and if the user clicks on a Save button, the page would do a POST request to the destination URL, containing the edited typescript and javascript.

That variant would also work for us, because we then could use an iframe in our configuration dialog which redirects to the typescript page. Would something like this be possible?

Thanks!

**Comment by egamma** [comment]
@T18970237136 it sounds like what you really want isn't the full TS playground, but the editor (the Monaco editor) used by the playground with the TS language service so that you can embed into your site. In addition, you would like to add a .d.ts  for your API. I don't see how this could be covered using the iFrame approach. I don't recommend to go down this path.

My team is currently heads down working on VS Code milestone. We can look into this request in a month or so. The editor actually has API to register an additional .d.ts which isn't exposed in the playground (check out the winjs playground: http://try.buildwinjs.com/playground/)

**Comment by T18970237136** [comment]
Hi @egamma 
thanks a lot for your reply!

> it sounds like what you really want isn't the full TS playground, but the editor (the Monaco editor) used by the playground with the TS language service so that you can embed into your site. In addition, you would like to add a .d.ts for your API.

Yes, that is what we'd want. Sorry for not being clear.

> I don't see how this could be covered using the iFrame approach. I don't recommend to go down this path.

Can you elaborate on why you don't see this being covered by an iframe approach?
I thought of using an inline-frame as an alternative if repackaging of the editor code on another (foreign) site won't possible.

In that case, e.g. the typscript page (www.typescriptlang.org) could host a static HTML page similar to the playground, containing the monaco editor. Then, a HTML page from a different host could use that page in an iframe and use window.postMessage() to send commands, e.g. to initialize the editor something like
```javascript
{
  "command": "ShowContent",
  "editorContent": "if (true) { var s: string = 'Hello World!'; }",
  "tsDefUrls": [
    "https://github.com/Microsoft/TypeScript/blob/master/lib/lib.core.d.ts",
    "https://example.org/myDefinition.d.ts"
  ]
}
```

The editor HTML page then could listen to MessageEvents to receive the commands, and in case of the above command, load the (CORS-enabled) .d.ts files and show the specified content in the editor. 
Then, if the surrounding page wants to get the current editor contents (because it wants to save the state) it could send some "GetState" command, and the iframe page could in turn send a message containing the current typescript and javascript contents of the editor.

This would mean the editor library files wouldn't need to be packaged by our (or some other) site but we still would be able to use the editor in an iframe to let users edit their type-/javascripts on our website.
However, I don't know how licensing would apply here and I would understand if you don't want to host such a page.
If it would be possible to repackage the monaco editor into other sites, I would prefer that approach.

Thanks!

**Comment by egamma** [comment]
I can see that you can host the Monaco editor inside an iFrame and use postMessage to work (in fact this is his how VSO embeds the Monaco editor). However I don't think this is applicable when embedding the TS Playground, which is a particular application that uses the Monaco editor. In other words the TS Playground does too much for your scenario.

We can look into the repacking or a CDN approach in roughly +1 month

**Comment by T18970237136** [comment]
OK, thank you!

**Comment by Artazor** [comment]
@egamma  It would be a huge step in evolving of TS-related public web tools if you'd allow to embed a MonacoEditor (with intellisense and ability to load custom .d.ts) into third-party products.

Eagerly awaiting to hear any progress in this direction!

**Comment by hiyelbaz** [comment]
+1

**Comment by kgusarov** [comment]
Voting for this issue to be implemented ASAP.

**Comment by vadkart** [comment]
+1

**Comment by dnarushevich** [comment]
++

**Comment by wonderwhy-er** [comment]
+1

**Comment by FabianLauer** [comment]
+1

**Comment by domotenko** [comment]
it would be great

**Comment by pkotov** [comment]
+1

**Comment by Artazor** [comment]
@egamma, Any news?

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/vscode/tree/master/src/vs/editor/browser

**Comment by kitsonk** [comment]
By the way, the open sourcing of the whole of VSC is totally awesome!  Hopefully it will help out everyone.

**Comment by Artazor** [comment]
If it is what I'm thinking about - it's awesome!

**Comment by T18970237136** [comment]
This is really great! Thanks a lot!

Now, I tried to use the Monaco editor in a simple HTML page just like the playground does, but I'm having problems and don't know how to to it correctly.

I downloaded the vscode repository and invoked tsc in the [src directory](https://github.com/Microsoft/vscode/tree/master/src) to compile the TS to JS. Then in that directory I created a HTML page that directory using the TS playground as template:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
<body>
<h1>Test Monaco</h1>

<div id="typescriptEditor"></div>

<script type="text/javascript">
        var require = {
            baseUrl: "/"
        };
</script>
<script type="text/javascript" src="vs/loader.js"></script>
<script type="text/javascript" src="vs/editor/editor.main.js"></script>
<script type="text/javascript">

if (!window.console.info) {
	window.console. info = function(){}
}

(function () {
	'use strict';

	var domnode = document.getElementById('typescriptEditor')
	var typescriptMode = null;

	require(['vs/editor/editor.main', 'vs/nls!vs/editor/editor.main', 'vs/css!vs/editor/editor.main'], function () {
		editorLoaded = true;

		Monaco.Editor.getOrCreateMode('text/typescript').then(function (mode) {
			typescriptModeLoaded = true;
			typescriptMode = mode;
			onSomethingLoaded();
		});

		var editor = Monaco.Editor.create(domnode, {
			value: '',
			mode: 'text/plain',
			fontIsMonospace: true,
			suggestOnTriggerCharacters: true,
			showTypeScriptWarnings: false
		});
	});
	
})();
</script>
</body>
</html>
```

However, when hosting the directory in IIS Express and opening the HTML page in a browser, I get various JS errors, such as
```
TypeError: nls is undefined keyCodes.js:432:13
TypeError: nls is undefined severity.js:18:9
TypeError: nls is undefined message.js:7:5
TypeError: nls is undefined actionbar.js:528:9
TypeError: b is undefined css.js:11:5
TypeError: nls is undefined lintRules.js:29:9
TypeError: nls is undefined pluginsRegistry.js:330:17
TypeError: ModesRegistry.Extensions is undefined monarchLexer.js:12:9
```

I'm a bit lost. Can somebody give me some pointers how to use the editor?

Thank you!

**Comment by kitsonk** [comment]
Probably best asked in the VSCode repository, not here @T18970237136.
