### ISSUE TITLE
Variadic element at position does not match element in target

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#53256]
# Bug Report

### 🔎 Search Terms 
Tuple spread variadic element length

### 🕗 Version & Regression Information

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230313&ssl=14&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABAQ0QHgNKIKYA8rZgAmAzogNrJgCeAugHyIAUAlIgN4CwAUIogPT9EAASgkAtDADmYOACdsiALJwiMYDGxyyEKrKgoADoezI5iABZbsAOiYBGewA4ALCx58i2CABsziiAQSAwh7AC4KGyiMWh4PASFRCWlZBWVVdU1tRF0wfSMTM0trO0dXd15EL19-HKCQgCYI8iibDAAaRFaYuMrBRAB5AGt4wLBgxAAjcIoqOkQAXhz7Xr5+gBVqE0QAchbozu7aHcQYMnzkEhIU5EmfRSg4RCgtxT25zrnjm3j+vgA1MwwZBqCA4e4AW0IBmQBkMcGusAQiAADKckCQ4CA5BBFEQ4NhznADBDYRALODsFCwDC4QiYEikGiYEgoGYpNgoHYGgBmBoNCp8MYTSZNWY0T40WiLHINHgAXyAA)

### 💻 Code

```ts
function a <K extends [any]> () {
  // @ts-ignore Modifiers cannot appear here.(1184)
  declare const c1: [...K]

  // @ts-ignore Modifiers cannot appear here.(1184)
  declare const c2: [...K, ...K]

  // Ok
  const b1: [any] = c1

  // Type '[...K, ...K]' is not assignable to type '[any, any]'.
  //   Variadic element at position 0 in source does not match element at position 0 in target.(2322)
  const b2: [any, any] = c2
}
```

### 🙁 Actual behavior

c2 is not assignable to b2

### 🙂 Expected behavior

c2 is assignable to b2

**Comment by iinicole** [comment]
Hi! This is my first time contributing. I would like to try resolving this issue if possible.
