### ISSUE TITLE
Object derived from spreading a class instance from within the class body has wrong type information

### ISSUE THREAD

**Issue by asnaeb** [microsoft/TypeScript#53252]
# Bug Report

### 🕗 Version & Regression Information

This happens on any version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=7&ts=4.9.5#code/MYGwhgzhAECC0G8BQ1XQGYHtPQLzQHIAjMAJwJTRIC8AKASkUrTVIFMAXAV1IDtEAdEI4ALAJYQAvs2jTpSYJl4QO0MHmi82AdzgMkCpSuiYiAKw1gBNfabPWwdRgHpn0ADwBaaADkcbUlJMUmgiLg4ALhNzB2poCU1MVXV0Ll5gDjElNVVSNMyAWzYDRWVVAH07ACYNBCEBMGlq2IZoVw9vAGFg9gzoAKDSJCA)

### 💻 Code

```ts
class A {
    foo = 'bar'
    baz() {
        return {...this}
    }
}

const a = new A()

const obj = a.baz()
obj.baz() // <- No error but: obj.baz is not a function at runtime

const _obj2 = {...a}
obj2.baz() // <- Correct error
```

### 🙁 Actual behavior
When spreading a class instance to an object from within the class itself, resulting properties are still presenting methods in its signature.

### 🙂 Expected behavior
Discarded methods would be removed from the type.

**Comment by fatcerberus** [comment]
Not destructuring, but spread.  Destructuring is when you do the reverse: `const { x, y } = point`

**Comment by RyanCavanaugh** [comment]
Duplicate #9726 - enumerability is not tracked by the type system

**Comment by fatcerberus** [comment]
Interesting that the second example works as expected, though

**Comment by RyanCavanaugh** [comment]
The curse of doing it right some of the time 🙂
