### ISSUE TITLE
TS does not recognise the "passwordrules" attribute on input

### ISSUE THREAD

**Issue by CraigKuriger** [microsoft/TypeScript#53259]
🔎 Search Terms

typescript passwordrules

 🕗 Version & Regression Information

Version: 4.5.4

 💻 Code

`  <input
    passwordrules="minlength: 15; required: lower; required: upper; required: digit; required: [-];"
  />`

Error message: 

`Argument of type '{ passwordrules: string; }' is not assignable to parameter of type 'HTMLProps<"input", HTMLAttributes<any>>'.
  Object literal may only specify known properties, and '"passwordrules"' does not exist in type 'HTMLProps<"input", HTMLAttributes<any>>'.`

🙁 Actual behavior

TS does not recognise the `passwordrules` attribute

🙂 Expected behavior

TS should recognise the `passwordrules` attribute

**Comment by sahithyandev** [comment]
I think `passwordrules` is not part of the HTML spec, is it?

**Comment by fatcerberus** [comment]
The only thing I could find was [this proposal](https://github.com/whatwg/html/issues/3518).

**Comment by RyanCavanaugh** [comment]
This is controlled by whatever JSX `.d.ts` you're using.
