### ISSUE TITLE
Illegal `.d.ts` class property definition for "constructor" generated from JavaScript

### ISSUE THREAD

**Issue by frank-weindel** [microsoft/TypeScript#53257]
# Bug Report

### 🔎 Search Terms

definition file, javascript, generated, incorrect, wrong, constructor, override, expected, 1005

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about definition generation from JavaScript
  - I tested from 3.5.1 to Nightly on the TypeScript Playground

### ⏯ Playground Link

[Playground link of the JavaScript code that generates the bad definition](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230313&filetype=js#code/MYGwhgzhAECyCeBhcVoG8BQ1vQPQCp8sdp9oABABzACcwBbdMAO3gF9oIB7egUwEFW-GgHMArn2YAXaAAoAks2j140GrzAgAtAHcuNEABNovAB4NKIXtCkALAJYwABi3hPojj-Uv3g9qQCUxDj4uMGcPLywvHZchrLcfILwwuKSgejhJHaOAHTAXMwQUjRiwFL60AC8EUlCohK80gDc4WwY7dBAA)
[Playground link with the generated definition code showing the error](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230313&filetype=d.ts#code/CYUwxgNghgTiAEkoGdnwLIE8DC1XwG8AoeU+AegCpKSz5L4ABAB1igFtCoA7TAX3jIA9uxABBXmJgBzAK6juAF3gAKAJLd47TPDhQIAWgDuQmBGDwQADw7MICRQAsAlmgAGPTG-iuf7O85gzooAlLRklOThgiIg6CBOQsAqwqISmFJyCooAXPCeIXkAbkLOwADc0WBC3MiKMLJgiqZ5npV8REA)

### 💻 Code

**JavaScript code:**
```js
class MyClass {
    /**
     * @param {any} someAnyArgument (In my real-world example this `any` is implicit)
     */
    someMethod(someAnyArgument) {
        this.constructor = someAnyArgument;
    }
}
```

**Definition code generated by TypeScript from the above JavaScript:**
```ts
declare class MyClass {
    /**
     * @param {any} someAnyArgument (In my real-world example this `any` is implicit)
     */
    someMethod(someAnyArgument: any): void;
    constructor: any;
    //         ^ '(' expected.(1005)
}
```

### 🙁 Actual behavior

TypeScript generates an invalid `constructor` property of type `any` on the class definition.

### 🙂 Expected behavior

TypeScript should not generate any property in this class. While it might notice that there is a statement that sets `this.constructor` to a value it should ignore it when generating property definitions for the class because its type is already implicitly a method with no parameters and it is illegal to even define a `constructor` class member in this way.

### Extra info

Just for extra info, here is the same program written in TypeScript directly as well as the `.d.ts` definition produced from that TypeScript:

**TypeScript code:**
```ts
class MyClass {
    someMethod(someAnyArgument: any) {
        this.constructor = someAnyArgument;
    }
}
```
[Playground](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230313&filetype=ts#code/MYGwhgzhAECyCeBhcVoG8BQ1vQgewFsBTWIgFwAs8ATACn2IEEA7eRgJwHMBXY5sgFzQwrAJTosOKZQCWEAHTA8zCGXbdgZPO2gBeXISIs2XXkX4BuSdgC+GO0A)

**Generated definition:**
```ts
declare class MyClass {
    someMethod(someAnyArgument: any): void;
}
```

As you can see, the expected valid definition file is generated.

**Comment by RyanCavanaugh** [comment]
I think this is a duplicate, but I have no hope of finding the other one.

**Comment by kb-s** [comment]
Hey @a-tarasyuk, have you fixed this issue?
