### ISSUE TITLE
Better UX for TypeScript Goto Symbols in VSCode

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/TypeScript#53269]
# Bug Report

### 🔎 Search Terms
Goto Symbols

### 🕗 Version & Regression Information

Please keep and fill in the line that best applies:

- I was unable to test this on prior versions because this is the first time I am trying this out.

### ⏯ Playground Link

https://github.com/siddharth2023/playwrightExperiments

### 💻 Code

So here's the repo:
https://github.com/siddharth2023/playwrightExperiments

In the file pageObjectModel.spec, I am not able to command click on addNewComputer(); and open it in the addComputer.page.ts file.

I am using VSCode for Mac.

I know it is the way that I have written the script but it would be better if TS of VSCode could take me to the symbol or if some error is thrown that shows a recommendation.

What's the right approach or alternative for this?

### 🙁 Actual behavior

I should be able to go to the function/var.

### 🙂 Expected behavior

I am not able to go to the function/var.

**Comment by fatcerberus** [comment]
Your link is broken.

**Comment by siddharth2023** [comment]
@fatcerberus Fixed. Sorry about that.

**Comment by RyanCavanaugh** [comment]
Please provide a self-contained example

**Comment by siddharth2023** [comment]
When I click on the first `clickAddNewComputer` it doesn't take me to the method when I command click on it.

When I click on the second `clickAddNewComputer`, it takes me to the method when I command click on it.


https://user-images.githubusercontent.com/122398930/226033060-31e05dcd-b9a6-4a60-b7ca-c1d93ace6757.mov


I hope that answers your question @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
A self-contained example would be a minimal code snippet that we can use to reproduce the issue (i.e. not a repo or a video)

**Comment by siddharth2023** [comment]
See comments on the lines `await addComputerPage.addNewComputer();`


`test.ts`

```

test.describe("Describe block", () => {
  let computersPage;
  let addComputerPage;

  test("basic test with POM", async ({ page }) => {
    computersPage = new ComputersPage(page);
    addComputerPage = new AddComputerPage(page);
    await computersPage.goto();
    await computersPage.clickAddNewComputer();

    await addComputerPage.addNewComputer(); // Cmd click here doesn't do anything because it is not point to a method

    await computersPage.assertNewComputerAdded();
  });

  test("basic test with POM 2", async ({ page }) => {
    const computersPage2 = new ComputersPage(page);
    const addComputerPage2 = new AddComputerPage(page);
    await computersPage2.goto();
    await computersPage2.clickAddNewComputer();

    await addComputerPage2.addNewComputer(); // Cmd click here takes me to wherever the method is

    await computersPage.assertNewComputerAdded();
  });
});

```

**Comment by RyanCavanaugh** [comment]
There have been three requests for a self-contained repro and one hasn't been provided.
