### ISSUE TITLE
allow storing results of narrowing of class properties in booleans for further narrowing

### ISSUE THREAD

**Issue by SteveRusin** [microsoft/TypeScript#53267]
# Bug Report

### 🔎 Search Terms

https://www.google.com/search?q=typescript+does+not+narrow+type+of+stored+variable&oq=typescript+does+not+narrow+type+of+stored+variable&aqs=chrome..69i57j69i64.8615j0j7&sourceid=chrome&ie=UTF-8

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?isolatedModules=false&ts=4.9.5#code/MYGwhgzhAECqAuBLEMDeAoa0LzE40iEAIgKYBmiAdqQCYA8AKgHwAUAbmCAK6kBc0RgEoBnHqUIwAcgHsqU7iHAAjEKSbNoGLFgBOpeN11VoY3tACEAXmhVFIANyZoAXycv06UJBgBBLc4ADtyqiATwpDgKALbKpLoCdrHx0AA+0NxUtBTUdE7OwHI4utzA8DK6rEIBOtCFVDiSMXG60DYIyBAAdERklDS0rPAAFkRdEVHcybpC+bWI5NCsRM3x1dq1dUXw0AAeiVMtbdAjYxPwq7pOtR5YHh7oajtUApkA1lQyAO5U+fWNK0OKXaSBQPRIOQGrCosy82yaU2O8AAnoFSDJFiYrNjoAByJItXH5BZLQHRdYFeH7WxA1o2X7oB7kTJlRByaDkGQyVjUgkpdKZbL9OgUrD-HZk44dMG9SF0Hmw5wLZYQGKinQAeg10GU3B2pxgXwqbwgzjF8ORB2mx1211cjKAA)

### 💻 Code

```ts
class Utils {
  static isDefined<T>(value: T): value is NonNullable<T> {
    return value != null;
  };
}

class A {
  public testNumber: number | undefined;

  constructor() {
    const isNumber = Utils.isDefined(this.testNumber);

    if (isNumber) {
      // Type 'number | undefined' is not assignable to type 'number'
      const x: number = this.testNumber;
    }
  }
}

function foo(x: number | undefined) {
  const isNum = Utils.isDefined(x);

  if(isNum) {
    // Works. No error here
    const y: number = x;
  }
}
```

### 🙁 Actual behavior

The narrowed type of class property is not inferred if narrowing result stored in variable

I expect the type to be correctly inferred as it's working for regular variables inside a function
[This PR fixed this bug for functions](https://github.com/microsoft/TypeScript/pull/44730)

**Comment by MartinJohns** [comment]
@fatcerberus But even if you make it `readonly` it's not working.

**Comment by sladiri** [comment]
I reduced the example to unexpected behaviour (bug?), where unknown is not reduced to number, unless you inline the type-check. Same issue?

https://www.typescriptlang.org/play?isolatedModules=false&ts=4.9.5#code/DYUwLgBAdgXBCuUDWUD2B3KBuAUDgxqlAM6QCWxAcvALYQC8EYAngA4ioBm0D9jA5FFoAjEACd+uHGW4AKCtRoBKCAG8cECIRKQAHnCE1RYhtFybtxVKAB0wVAHNZupbgC+eGRFkt2XHnwChsb8KuoWRKQQ+tAi4qbYGlqR1iB2js6uOB5AA

**Comment by RyanCavanaugh** [comment]
It does need to be `readonly`. Looks like we have a bug here when the property is on `this` specifically, since this code works as expected:
```ts
class Utils {
  static isDefined<T>(value: T): value is NonNullable<T> {
    return value != null;
  };
}

class A {
  public readonly testNumber: number | undefined;

  foo() {
    const obj: this = this;
    const isNumber = Utils.isDefined(obj.testNumber);

    if (isNumber) {
      // ok
      const x: number = obj.testNumber;
    }
  }
}
```
Common source of bug here when we check for something being an `Identifier`, which `this` isn't. From a type perspective these examples are the same so it's probably a simple fix.
