### ISSUE TITLE
Property is incompatible with index signature when using computed keys.

### ISSUE THREAD

**Issue by mktcode** [microsoft/TypeScript#53270]
# Bug Report

### 🔎 Search Terms

dynamic object symbol key property undefined

### 🕗 Version & Regression Information

This is the behavior in every version I tried..

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230315#code/MYewdgzgLgBA8gIQFIEYYF4YG8BQMYQgC2ApgNYkCeAXDAESGnQBOAlmAOZ04C+OOoSLERIATBmx4CxclVoMZIKAAsSzFuy69+USgAcSMALKUAKvsOZc+ANoBDWhs4BdWtfwwbFGgShsXjn6aANxSfHw4APSRMAAmICQQYADksADuIMxkAuDQMESUcABGAFYS7jYiKAB0jLKUrpIeMHYQsfKtsXQANGG9tiKitTLeje74sSQAZvKTU9z4PL0R0TAZWRBRMYJ5BcVlVlselcg1daNuR82dHW09VzBLRysx62Sbqzuwe6XlDwpMIKcOiXVbXNq3Lq9MGPaExfAAkhKVTqIFcUHwjxzWbTbgwp6rCLAAA2rQgxkoAGFSRBye4vswAK7AKCZAAUekZRWJrGA+UKpVoJnMBgAlE0PKtqtKwtockJ+dSyRIwCQ0hSlbS2T8SqL+DsQMSSNViSAONqqTSINUdaKgA)

### 💻 Code

```ts
const OBJ1 = { somekey: "somestring" }
const OBJ2 = { somekey: "someotherstring" }

type MyType = {
  [a: string]: {
    [key: string]: string;
  }
}

const myObj = {
  [OBJ1.somekey]: {
    asd: "asd",
  },
  [OBJ2.somekey]: {
    def: "def"
  },
}

class MyClass {
  constructor(public myObj: MyType) {}
}

const myClass = new MyClass(myObj) // type error
```

### 🙁 Actual behavior

```bash
TSError: ⨯ Unable to compile TypeScript:
index.ts:43:29 - error TS2345: Argument of type '{ [x: string]: { asd: string; def?: undefined; } | { def: string; asd?: undefined; }; }' is not assignable to parameter of type 'MyType'.
  'string' index signatures are incompatible.
    Type '{ asd: string; def?: undefined; } | { def: string; asd?: undefined; }' is not assignable to type '{ [key: string]: string; }'.
      Type '{ asd: string; def?: undefined; }' is not assignable to type '{ [key: string]: string; }'.
        Property 'def' is incompatible with index signature.
          Type 'undefined' is not assignable to type 'string'.

43 const myClass = new MyClass(myObj)
                               ~~~~~
```

### 🙂 Expected behavior

I'm not sure what I'm doing wrong. This might be expected behavior but it's weird that it works when `myObj` has only one entry (see playground). How do I need to type `MyType`?

**Comment by fatcerberus** [comment]
`MyType` is fine, the issue is that in the absence of a type annotation it's inferring an incompatible type for `myObj`. 
 Workaround: `const myObj: MyType = ...`.  It can then figure out that the object literal is compatible with `MyType` and everything works as expected.
