### ISSUE TITLE
Setting a variable type as a generic allows any property to be modified without type checking

### ISSUE THREAD

**Issue by benthomasknight** [microsoft/TypeScript#53279]
# Bug Report

### 🔎 Search Terms

generic type used for constant
set constant type as generic
spread operator on a generic variable

### 🕗 Version & Regression Information

4.9.5

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQghgZwgeQEYCsIGNhQLxQDeAUFGVGAE4D2YAXFAsJQJYB2A5gNynlW0AVAO7UGbAK4BbVBEo8AvsWIAzcWxwtqbKAHEIwAKIAPYBDYATCOfhI0mHAB4BUCCbPmEsRCgzZgAPgAKS2U4cQAbYAQGAQBKIl4yAHokqABBcPDqIU9JaGBqRn0oODYQChpISlAoADc4cPEIABooVHFcLAbwqBZcUEgoAUSoFKgACVloAEki3AADfjABAAtKCAh5l1qzKGAV6nEOFaGAZUYDiPNGOHK+qC62NmpcAGtnoV7lCsE1jd7PPVwixrspqJQ9uBoMNyA8tEwoNQMDF8AlYbCAHRYkJhSIIZojWFLBgAIlMTBJBPRfEqwlEUAADATCeQxqsIEgLodwtcZL02ECQa1EGcoOZqBy2AByN4fKBCFb6RUQ-YQcpwdYlTLZKxQMEqqFQeYCeYsshLVbrCBiCLhKnUkoAOQgQgACpVZKBSWkyvt2BwoLNga8IABCSkjRQjdbAcSUbRI9AKJTEAbQADqfRWqxYlHM7toqJsPnsuAAZGiab8rQxUNRqOEIKVk8QsPDcImGJn9jm8wWwKiSETKqStBAI8PBCIGAAme3m2l-a17ShNAnyHjENkrFieBC3TyqyGDXdG7vZnd9ypbdr9FZwXCn579VfQEVsF0-MCeIRTErmSxzGFCwSm0Vxd2Af15RFDgWB2bRSn5QVriBJpW3bREMEtf4CD0Qw3AsKxizsPxAkTWIuCAA)

### 💻 Code

```ts
type BaseObject = {
    prop: string;
    propTwo: number;
}

function GetExtendedBaseObject<T extends BaseObject>(defaults: T) {
    // Allows me to set any property value, but call it type T
    // Here I set `propThree` even though TS should say it cannot know if propThree is valid for type T
    const obj: T = {
        ...defaults,
        prop: "test",
        propTwo: 0,

        // These should be invalid, as TS doesn't know whether they are allowed for type `T`
        propThree: null,
        aNewProperty: "Anything I like!",
    }

    return obj;
}


type WithThirdProp = BaseObject & {
    propThree: boolean;
}

const obj: WithThirdProp = {
    prop: "one",
    propTwo: 2,
    propThree: true,
};

// This says the type is `WithThirdProp` but that is not true as new props were added, and an existing was given an invalid value
const objThree = GetExtendedBaseObject(obj);
```

### 🙁 Actual behavior

the type of `objThree` is set as `WithThirdProp` - but the actual value does not match that type. When setting a constant to a generic type it should only be valid to set properties of the generic that are known (the extended `BaseObject` type in the case), and should not allow unknown properties to be added/modified.

Without the spread of the `defaults` parameter it correctly says the following message:

`'T' could be instantiated with an arbitrary type which could be unrelated to '{ prop: string; propTwo: number; propThree: null; }'.`

But with the spread it then allows me to add/modify any key without it checking the types.

### 🙂 Expected behavior

I get an error saying `'T' could be instantiated with an arbitrary type which could be unrelated to '...'` when modifying unknown properties of a generic type variable.

**Comment by fatcerberus** [comment]
This is effectively a design limitation, because the only means TS has available to model a generic spread and keep it generic is as `T & OtherStuff`, which is assignable to `T` by the definition of intersection.  To check this correctly TS would first need first-class support for spread types like `{ …T, …U }`, which makes this a de facto feature request.

**Comment by benthomasknight** [comment]
I am not wanting TS to actually have first class support for spreading, I would just like it to tell me it is potentially invalid message used when I dont have the spread there. I would rather be force into casting it manually to my type rather than ha TS assuming what I have done is valid and allowing invalid types by default.

I am happy for `{ ...T }` to be considered type `T` - but something like `{ ...T, other: boolean }` should not be considered `T`, even if it ends up actually being valid as there is no way for it to confirm the prop `other: boolean` is valid or not.

**Comment by fatcerberus** [comment]
That’s what I’m trying to say - typechecking works by comparing types, so TS must infer *some* type for `{ …T, other: 42 }` before it can typecheck it; the closest available type is `T & { other: 42 }`.  Unfortunately that makes it typewise compatible with `T`, even though the value you actually get isn’t.  You can’t get closer than that without spread types.

**Comment by benthomasknight** [comment]
Yep okay that makes sense. The functionality feels wrong but I understand it at least. A quick google shows there is a ticket open for it so I will close this. Thanks for the help.

**Comment by fatcerberus** [comment]
> A quick google shows there is a ticket open for it

I *thought* this was a dupe, but I couldn’t the other issue.  But yeah, from what I remember of past discussion this is not really working as intended - it’s more like “this is the best we can do for now given how the type checker currently works under the hood”
