### ISSUE TITLE
Array Includes incorrectly uses generic type

### ISSUE THREAD

**Issue by willyboy** [microsoft/TypeScript#53275]
# Bug Report

Array.includes should not be inferring type. Especially when the type is a string and the array is defined by a union of strings.
The point of using includes is to see if something exists in an array. If the thing we are looking for is a string in an array with a union type of strings, we get an error like, "argument of type string is not assignable to parameter of type 'a' | 'b'".

### 🔎 Search Terms

array, includes

### 🕗 Version & Regression Information

I'm on 4.5.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydaiKBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEqz5AScCwYFgAFMAAsBmPxYDyAHz8jmwbiQZLMNQAK3i0EQAwIAEcfqh2DoJKs8AAvCoAIQAwgARGkAMQA4gAJACSACkANLPACyADkAPK0ACKj2IOHuzPAAA1QgAtAAMAEYAEwAZgALABWABsAHYABwATj5AG1A3VMAFktB4PAyOLa7FhS4kOKAJSgABUoELmb7AF1QD2ANzkxpUsRkMj5UDigDkDBXoAAPqAV9IVz2q+PeVW1yv+LuV6Pp4oEcvHGQAhlYNB2GrBOLafTGe5WZQOe4ez7ABvRQShKFQqXYRFFAAX2CFQcGaDwyC8RAW2cYF2BoL43DMZh2AYZhIDlaB1ESDl4D0EQvD5OkGSZQQ+SSbE+XABxUBXYRg0gCQhWKUMvjId5BGIrRICOVBHAUVxpDwUAnDQnRhiwfQUAQRBoWES4cIkFtohEAwOGxUUWDYLhuCCEogA)

### 💻 Code

```ts
let thing: string = 'random string that is not hardcoded';
const allowedStrings: ('a' | 'b') = ['a', 'b']

if (!allowedStrings.includes(thing)) {
    // do something
}
```

### 🙁 Actual behavior

An error is thrown preventing us from using includes to see if our string is in the array.

### 🙂 Expected behavior

No error is thrown as we don't know if the string is in the array or not until at runtime.

**Comment by RyanCavanaugh** [comment]
Lacking something like #14520, this is the intended behavior.

**Comment by willyboy** [comment]
@RyanCavanaugh How is this the intended behavior? "Includes" is basically a runtime type checking. It shouldn't even be inferring a type.
