### ISSUE TITLE
`@linkcode`/`@link` points to symbol import location not definition site in VSCode

### ISSUE THREAD

**Issue by Thundercraft5** [microsoft/TypeScript#53272]
# Bug Report

### 🔎 Search Terms
- `@linkcode`
- `@link` definition
- `@linkcode` points to import location
- `@link` doesn't point to definition site

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, this bug is present in nightly.

### 💻 Code
Create files with the following in VSCode:
`a.ts`
```ts
export type A = {}
```
`b.ts`
```ts
import type {A} from "./a";

/**
 * Desc -- {@link A}
 */
export type B = {}
```

### 🙁 Actual behavior
`{@link A}` points to the import location of `A` instead of the definition site.

### 🙂 Expected behavior
`{@link A}` should point to the definition site of `A`.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.

The logic goes like this: If you aren't sure how `A` got into scope, taking you to another file might make you think it's a global, or you might not notice that you changed files. It's also very confusing in the case of a renamed import, if you say `import { X as Y }` then going to `X` when you clicked on `Y` seems like the editor is just lost.

Conversely, if we take you to the import, you can just F12 again, and go to its originating declaration without loss of functionality.

**Comment by RyanCavanaugh** [comment]
Also you can use an import expression (`import("./a").A)` instead if you want to go directly to A
