### ISSUE TITLE
reset tsc compiler state for external module

### ISSUE THREAD

**Issue by co-dh** [Microsoft/TypeScript#5327]
I noticed that we don't need reference path for some require statement if the .t.ds has been referenced in another ts file.

for example:
If I have A.tsx WITHOUT reference path, and:

import React = require('react')

it WILL compile if another tsx file (B.tsx) have  /// <reference path="react.d.ts"> 

This behaviour is undesirable because it create a dependency of A.tsx on B.tsx, and if B is removed in future, A will not compile any more.

**Comment by ahejlsberg** [comment]
You can use the `-noResolve` command line option to suppress dependency resolution and include only files that are listed on the command line or in tsconfig.json.

**Comment by co-dh** [comment]
Glad to here your answer. But Dependency Resolution do not have to accumulate included files.
Each file should be compiled correctly independently, And also Dependency Resolution is a nice feature that I don't want to turn off.

**Comment by mhegazy** [comment]
My recommendation is to not use `/// <reference >` tags.
