### ISSUE TITLE
Have a problem with constructing a type which contains an undefined as Array member. Only triggered in whole-project compile.

### ISSUE THREAD

**Issue by magwas** [microsoft/TypeScript#53277]
# Bug Report

### 🔎 Search Terms

Array member unknown 

### 🕗 Version & Regression Information

exist at least with 4.8.4 and 4.9.5

The bug is not reproducible in the playground, probably because if I do `tsc test/current.test.ts` it does not manifest, only if I do `tsc`.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Array

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=1&module=1&noImplicitOverride=false&noPropertyAccessFromIndexSignature=false&noFallthroughCasesInSwitch=false&isolatedModules=false&ts=4.9.5&useDefineForClassFields=true&downlevelIteration=true&importHelpers=true#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAsAFDIXLaYBcyARttgDYRwgDcZAvl6aJFiIUABWh5cRMpWQg4AWwh08YKKADmPMmTABPdCgDiEMABV9KALzIAFAFcozZao0AaKphz4A-HQxZcAgBKZEsAPmQxKAkQbVI9A2QAQTxjMEE8AB5TZAgAD0gQABMCJKgoOF1MuxAAaxBsAHcQMIjrEnJKAG0AaWRQZFqIXWwYZFMAXTobEPDx3onpSm4dC2QAWRMAC2wi80TrGwA6E7godTw6dl0uidmI67iAeifkeTghgnQzhXUTDNkEAAbtBVokRD9FII0hlsrkChBigRNmAdnsLG1kABRAoVBBgTIpGHiTIQipQkmmVruMoVKozcI1epNFphZ6vd6fWx5ab3ZDXPl5GbIMDYZDwYDMZCNYCo8ZrADkTIazQV-QIDTA-LweGA6jk9FYIrFCRQCuFc2uCrILxkpsikJM0GJ0Th+UKJQ2212+wgmJxqkQBKJ-xJZIUTtdVLCNPKlWqdRVrLi9u+5JdBGs4YpUAzmTSvrZpDICECWuoAXwfk8gVCRA8YDoqjsEBWxdIpfwWpgTDoaYUGbrXQZYQARHBR+4RxWvARFqQYDV8V5kFt2EVWAAlGrIN0IpFe1E+jE2JYUfs5jN0bORvNUshBOhA7DAIpSToUTsqZAXyOZn+OtCobREc7zoDYNg8rYfICqEERCkEIRwAQN6wve7YyF+LAQEczDYOoNi-hkQRaO2WGsLh+E2GuxRbjUrg9tgJELkulYMGcMw0DURQQDAoAQG+HQyFAJgOCAyDcbx-FFKRX5avQcAAF51haESSXxIACSWgTYZRBFdOp0kTK4XQKVAMzGaZSkWUEQA)

Repository with only the absolute necessary stuff to trigger the bug:

https://github.com/kode-konveyor/cdd-ts/tree/bug/angulartest
commit 93cec6b0c3f40f768f9e790cbd6349c35d9cd4bb

### 💻 Code

```ts
interface Options {
    opt: boolean;
};
interface Person {
    name: string
}

type GetType = (url: string, options?: Options ) => Person

type AsGetters<T extends Array<unknown>> = {
    [K in keyof T]: () => T[K]
    }
type MethodType = (...args: any[]) => any

// makes paramgetters never
type ParameterGetters<T extends MethodType> = Extract<AsGetters<Parameters<T>>, Array<()=>unknown>>

// makes (x: () => any) => x() to fail with Type 'unknown' is not assignable to type '() => any'
//    type ParameterGetters<T extends MethodType> = Extract<AsGetters<Parameters<T>>, Array<unknown>>

type paramGetters = ParameterGetters<GetType>

const options: Options = { opt: true}

const foo: paramGetters = [()=>"a", ()=>options ]
function handleRun <T extends MethodType>(
    parameterGetters: ParameterGetters<T>
): void {
    const parameters = parameterGetters.map((x: () => any) => x()) as Parameters<T>

    console.log(parameters)
}

console.log(handleRun,foo)
function bar():undefined {
    return undefined
}
const baz = () => undefined
console.log([undefined],[bar()],[baz()])
```

### 🙁 Actual behavior

The second parameter being optional triggers the behaviour of paramGetters being never.
As if Typescript would think that an array `[unknown]` is impossible.

```
mag@mag-Librem-15-v4:~/project/KodeKonveyor/cdd-ts$ tsc
test/current.test.ts:30:45 - error TS2345: Argument of type '(x: () => any) => any' is not assignable to parameter of type '(value: unknown, index: number, array: unknown[]) => any'.
  Types of parameters 'x' and 'value' are incompatible.
    Type 'unknown' is not assignable to type '() => any'.

30     const parameters = parameterGetters.map((x: () => any) => x()) as Parameters<T>
                                               ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in test/current.test.ts:30

mag@mag-Librem-15-v4:~/project/KodeKonveyor/cdd-ts$ tsc test/current.test.ts 
mag@mag-Librem-15-v4:~/project/KodeKonveyor/cdd-ts$ 
```

A workaround is to pretend that the array is of unknowns and not `() => unknown`s, but that breaks the conversion code.

There are similar problems with the alternative implementation:
```
type AsGetters<T extends any[], converted extends any[] =[]> = T extends [infer head, ... infer tail]
    ? AsGetters<tail, [... converted, () => head]>
    : converted

export type ParameterGetters<T extends MethodType> = AsGetters<Parameters<T>>

```

### 🙂 Expected behavior

No error.

**Comment by RyanCavanaugh** [comment]
This behavior follows from the definitions of the types and the settings you've provided.

`tsc` and `tsc foo.ts` actually have quite different behavior since the latter will not use the settings in the local `tsconfig.json`. Seeing a difference between these two commands is expected if there is a local tsconfig with any non-default settings.

**Comment by magwas** [comment]
The problem is not that only a whole project compile triggers it. That part is a bit more complex: it cannot be reproduced in playground ot vscode.

But anyway, I have just added this information to help with reproducing the bug.

The bug is that there is an error where there should not have been one.

Please remove the "Working as Intended" label, as it is misleading.

**Comment by RyanCavanaugh** [comment]
> That part is a bit more complex: it cannot be reproduced in playground ot vscode.

The error is correct if and only if you have strict null checks enabled. Your Playground link disables strictNullChecks, which is the only reason it doesn't repro there. That's the same reason you saw a difference between `tsc` and `tsc foo.ts`.

I don't see a demonstration of a bug here. 100% of this behavior follows from the type definitions and settings being provided to tsc in each case.
