### ISSUE TITLE
enum value's type inferring won't work within objects

### ISSUE THREAD

**Issue by vacodoceo** [microsoft/TypeScript#53288]
# Bug Report

### 🔎 Search Terms

`const` `enum` `type` `inferring`

### 🕗 Version & Regression Information

I tried on `v4.9` and `v5`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230315#code/KYOwrgtgBA8mAuBjA9hYUDeBYAUFKAQgDbKIDWwAJlALxQDkxMAwgNICiAIvQDS74AFAIYBnEbQbCx9XAF9cueAE8ADukoBLEYgBOGiBpBD4VOElTo6GKMgQo0ALlh2LAOmKkKlHlABmyZCcReD0QAHMoWSgAH0wbF0dnczRXKREfACMhHSCQwwj5HFwUEGCoAAshEEoiYB0JAApbZOAHTW09AyMTSjN7YABKWgA+TH4oHWB4MB0QeJa5BRwSssmARzBgMqtx5v6nPrcPcio+PD8Ap3oZHEKlyuranQb1zeCBgG57qpq6huxznsLAcEsB3CQTt5xv5Atc5AMgA)

### 💻 Code

```ts
enum Outcome {
  Blocked = 'BlOCKED',
  Pass = 'Pass'
}

type discriminatedOutcome = { outcome: Outcome.Blocked, foo: string } | { outcome: Outcome.Pass, bar: string }

const handler = (outcome:discriminatedOutcome) => {
  return outcome
}

const request = {
  outcome: Outcome.Blocked, // here outcome is inferred as `Outcome` instead of `Outcome.Blocked`
  foo: ''
}


handler(request); // due to outcome being of type `Outcome` instead of `Outcome.Blocked`, type check fails here

handler({
  outcome: Outcome.Blocked, // type check here passes
  foo:''
})
```

### 🙁 Actual behavior

Type inferring won't work as expected on objects containing an enum value. It infers the type of enum instead of the type of the value within the enum.

### 🙂 Expected behavior

I'd expect the type of `request.outcome` to be `Outcome.Blocked` instead of `Outcome`

**Comment by MartinJohns** [comment]
Or alternatively you can add a type annotation to your `request` variable, providing the compiler with enough type information.

This is working as intended.
