### ISSUE TITLE
Property is used before its initialization error is only shown during compilation when using ES2022 but is with ESNext

### ISSUE THREAD

**Issue by alan-agius4** [microsoft/TypeScript#53286]
# Bug Report

### 🔎 Search Terms

- property is used before its initialization
- esnext
- es2022
- before its initialization

### 🕗 Version & Regression Information

- Does not seem to be a regression. 

### ⏯ Playground Link

ESNext: https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&ts=5.1.0-dev.20230315&ssl=4&ssc=2&pln=1&pc=1#code/MYGwhgzhAEBiD29oG9oChqegIzAJ2gF5oAXACwEsIA6bAVwC8BuDLYeAOwhLzuBPh4AFAAc8FAG5gSAUxyMAXNDocA1h3gB3DgEoUAXzT6gA

ES2022: https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9&ts=5.1.0-dev.20230315&ssl=4&ssc=2&pln=1&pc=1#code/MYGwhgzhAEBiD29oG9oChqegIzAJ2gF5oAXACwEsIA6bAVwC8BuDLYeAOwhLzuBPh4AFAAc8FAG5gSAUxyMAXNDocA1h3gB3DgEoUAXzT6gA

### 💻 Code
```ts
class Foo { 
    bar = this.buz;
    constructor(private buz: unknown) {}
}
```

### 🙁 Actual behavior

TSC correctly produces the below compilation error when targeting ESNext. But does not when targeting ES2022.

```
TS2729: Property 'buz' is used before its initialization.
```

### 🙂 Expected behavior
The same compilation error is shown when targetting ES2022.

**Comment by Ozz760** [comment]
Hello Alan, 
I was wondering if I can take this issue?

**Comment by alan-agius4** [comment]
Go for it

**Comment by alan-agius4** [comment]
It’s not a duplicate as those issues are closed and problem still persists. 

It appears that the problem was only fixed for esnext.

**Comment by Dev79844** [comment]
Hey Alan!
I would like to work on this issue if anyone is not working on it.

**Comment by alan-agius4** [comment]
@Dev79844, no one has opened a PR so far so feel free to open one.

**Comment by Hazmi35** [comment]
Can confirmed this issue is happening with `5.0.4`. Maybe related #50971 and #52331

ES2022 (and ESNext) implies `useDefineForClassFields: true`. TS2729 will happen if this option is set to true.

On ESNext, if you set the option to true it shows TS2729, and false doesn't. This is expected.

But on ES2022, even with `useDefineForClassFields: true` explicitly set to true, there are no TS2729 errors.

**Comment by ujlagarg1997** [comment]
Hello Alan,
Is somebody working on this PR? I would like to contribute if it is available.

**Comment by Anshul-target** [comment]
@alan-agius4  I  am new to opensource could you suggest how would I test the error.
 I have set up the project locally

**Comment by alan-agius4** [comment]
@Anshul-target, please see the [contributing guidelines](https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md).

**Comment by moheet333** [comment]
Hey @alan-agius4 does the PR #53885 fix this issue?

**Comment by alan-agius4** [comment]
> Hey @alan-agius4 does the PR #53885 fix this issue?

Looks like it
