### ISSUE TITLE
TypeScript cannot auto-complete keyword `typeof`

### ISSUE THREAD

**Issue by vikyd** [microsoft/TypeScript#53289]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.76.2
- OS Version: macOS 13.1 (22C65)

Steps to Reproduce:

1. there is an const object
2. want to create a type of that object
3. keyword `typeof` not showing auto-complete

<img width="435" alt="typeof1" src="https://user-images.githubusercontent.com/2208880/225608105-651f4772-29ae-4ccf-8725-e5ba5eb5f1c8.png">

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
