### ISSUE TITLE
Add generic parameter to Object.keys

### ISSUE THREAD

**Issue by eqprog** [microsoft/TypeScript#53294]
Pretty simple suggestion. It'd be nice to be able to assign a generic keyof type whenever looping through objects values in order to avoid multiple type assertions in my code. I have methods that have parameters as 'type: keyof MyType' which can also be used outside of a loop context. However, using Object.keys explicitly returns a string array. I'm not sure how possible it is but it would definitely make my code easier to read...

Example

`const someObject: MyType = { key1: 'hello', key2: 'world' }
const keys: Array<keyof MyType> = Object.keys<MyType>(someObject)`

And somewhere in the type definitions Object.keys would look something like
`function keys<T>(someObject: T): Array<keyof T>`

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template. This was suggested again and again ([see these issues](https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+Object.keys+in%3Atitle+is%3Aclosed)), and is rejected for good reasons: in TypeScript objects are not sealed. `Object.keys()` might very well return more keys than `keyof T` allows.
