### ISSUE TITLE
Grant minimal permissions to workflows

### ISSUE THREAD

**Issue by pnacht** [microsoft/TypeScript#53296]
# Suggestion

## 🔍 Search Terms

token permissions, permissions

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I'd like to suggest that TypeScript reduce the permissions granted to GitHub workflows. This is recommended by the OpenSSF Scorecard (added in #52103).

By default, GitHub grants workflows full write-all permissions, which makes the project vulnerable to supply-chain attacks.

Minimizing permissions can be done by:
- adding top-level permissions to the workflows themselves; and/or
- changing the repo settings so that workflows run with read-only permissions.

I'm sending out a PR along with this issue setting the top-level permissions if you wish to follow this track.

If you instead prefer to change the repo settings:
- Open the repository settings
- Go to [Actions > General](https://github.com/microsoft/TypeScript/settings/actions)
- Under "Workflow permissions", set them to "Read repository contents and packages permissions"

There are a few workflows that require elevated permissions. Specifically, those that automatically commit to the repository will require `content: write`. If the default repo setting is changed, these workflows will need to be updated to declare this elevated permission.

## 📃 Motivating Example

The current write-all permissions mean that, if any workflow dependency gets taken over by a malicious actor, a malicious version could be released to manipulate the TypeScript repository's contents or to exfiltrate secrets and credentials.

## Disclaimer

My name is Pedro and I'm working with Google and the OpenSSF to improve the supply-chain security of the open-source ecosystem.

**Comment by RyanCavanaugh** [comment]
Done, thanks!
