### ISSUE TITLE
`noUncheckedIndexedAccess` does not include `undefined` in the type for assignment operators like `??=` or `+=`

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#53303]
# Bug Report

### 🔎 Search Terms

assignment operator, noUncheckedIndexedAccess

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/PTAEAEDsHsFVIMYAsCmCDWKAmBJSWUAPbAQQQRQGdKAoGghAGwEMAnFUBaSSgF1EKEAXKABKaaKywAePqwCWkAOYAaUJACuAWwBGKVgD4A3HUEA6ZszO9oAMXnEsACgCUJkKFAA9APw0PvACeAA4o0ABmAoQWzKAAvAnq2nqsoAA+oBr4KOGK2KCAoOSm0To6oADUcaAAjO5g3n4BIWGR5qXxiZq6+qBOvGhIkPIIzIyMgZyS7Ai8Lv7A86DM4f2pzNTySpBaKJC8QosAbqMaLVFm7QlVAHLM16CAvBuARHvFZuSgPj5VtYsNi0GhCLnd5XJLdVKAGXI6DRzFgsPFznCKjU6p40ei-k1Aa1okjQV0UulMtlcpB8kUYdEUBxPr1zNSEdU3L9fP9mkDYfD8ckehksgRSeTfhj0aysWdOR0qgSegUlpRQPJeAByBWxdjMeGMaAjXjybg0IA)

### 💻 Code

```ts
// @noUncheckedIndexedAccess

declare const xx: Record<string, number>;

xx.aa.toFixed();
//  ^?
// typeof xx.aa === number | undefined ✅

xx.bb += 1;
//  ^?
// typeof xx.bb === number (technically correct)
//
// after assignment:
// valueof xx.bb === NaN 😢

xx.cc ??= 1;
//  ^?
// typeof xx.cc === number ❌


xx.dd = xx.dd + 1;
//          ^?
// typeof xx.dd === number | undefined ✅

xx.ee ?? (xx.ee = 1);
//  ^?
// typeof xx.dd === number | undefined ✅
//           ^?
// typeof xx.dd === number ✅ as it's a read location

```

### 🙁 Actual behavior

TS does not consider an assignment operator as a read, so it doesn't union in `undefined`.

### 🙂 Expected behavior

TS should consider an assignment operator to be both a read AND a write, and it should include `undefined` the same way it would in the operator's non-sugared forms.

### Additional info

In addition to the above - this behaviour makes it difficult for us to write lint rules because when we attempt to check if the LHS of the assignment is `undefined`, the type system reports that it is not. Example issue https://github.com/typescript-eslint/typescript-eslint/issues/6632

**Comment by RyanCavanaugh** [comment]
It's an assignment target, and the only legal assignment source is `number`, so that's what shows up here. That's the higher-order bit.

**Comment by bradzacher** [comment]
So the type is calculated based on the fact that it's in an assignment location, not based on the actual type of the thing?
It seems weird to me that the type of the assignment is applied in a position that is before the assignment is completed. But maybe I'm misunderstanding something.

Is there any way to ask TS for type of "what it should be" instead of "what it can be assigned by this operator"? Or are we SOL?

If we're SOL then this would probably kill support for checking for unnecessary logical assignment operators because we wouldn't be able to tell if the thing is possibly nullish.

**Comment by RyanCavanaugh** [comment]
Looking at it more, I'm not sure what you're running into. For example, here
```ts
function fn(x: string | number) {
    x = 32;
    x += 3;
//  ^?
}
```
This shows the CFA type of x, not the declared/write type. It seems like this should be sufficient for the rule to work?

**Comment by bradzacher** [comment]
```ts
const foo: Record<string, number> = {};
const bar: string = 'key';
foo[bar] ??= 0;
// ^ 1

foo[bar] ?? (foo[bar] = 0)
// ^ 2
```

This is the best example to illustrate what we're looking for.

When we interrogate the type of `foo[bar]` at 1, the type is `number`.
So when the rule attempts to check to see if the assignment operator is unnecessary, then we see `number` and we report on it because based on the types the value is never nullish, so using a nullish coalesce assignment is unnecessary.

When we inspect the type at 2 the type is `number | undefined`, so when the rule attempts to check if the nullish coalesce operator is useless, it does not report because the type is nullish.

Ideally the first case we should be able to report on because we would see the type as `number | undefined`, just like the second case. But because we don't we false positive on this case.

**Comment by bradzacher** [comment]
@RyanCavanaugh I guess another example of why I think this behaviour is wrong is this:
```ts
const foo: Record<string, number> = {};

let bar = foo['bar'];
//  ^? number | undefined

    foo['bar'] ??= 1;
//     ^? number
    bar ??= 1;
//   ^? number | undefined
```

It's specifically the case of an index signature on the left side of an assignment operator wherein TS reports the write type, not the read type.

**Comment by RyanCavanaugh** [comment]
> TS reports the write type, not the read type.

Why is this "wrong"? The variable is being *written to*.

**Comment by bradzacher** [comment]
For an assignment operator it's technically both! It's first being read from and then being written to.

All assignment operators are both a read and a write - which would be the reason that the `+=` operator is treated as a read and includes `undefined`.

**Comment by RyanCavanaugh** [comment]
Let's use "compound assignment operator" to refer to `+=` and its friends; `=` is the one and only "assignment operator".

Since it's both a read and a write, why is one of the answers correct and the other not? They have equal standing.

**Comment by bradzacher** [comment]
They definitely do! It depends on interpretation as to which you might see as "right".

As a consumer of the TS API I'd love to be able to explicitly ask for either (depending on my usecase) so that I don't need to manually implement logic to handle options like `noUncheckedIndexAccess`.

As a consumer of TS, I don't think I care either way because I wouldn't care about the type of the thing before / during the assignment (except in the case of the math operators where undefined can cause problems) - I'd only really care about it after the assignment.

From the context of TS itself - it probably prefers the write type, not the read type because it is writing there.

**Comment by LiST-GIT** [comment]
```ts
xx.bb += 1;
//  ^?
// typeof xx.bb === number (technically correct)
//
// after assignment:
// valueof xx.bb === NaN 😢
```

Hi @RyanCavanaugh , I'd like to ask if this is correct. 'xx.bb += 1;' should be equivalent to 'xx.bb = xx.bb + 1;'. However, 'xx.bb = xx.bb + 1;' gives an error stating that ''xx.bb' is possibly 'undefined'.
