### ISSUE TITLE
Enums as union types aren't compatible with strings (5.0)

### ISSUE THREAD

**Issue by Ayc0** [microsoft/TypeScript#53304]
# Bug Report

In https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#all-enums-are-union-enums, it mentions that enums can be used as union types, allowing to do this:

[TypeScript Play](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230316#code/KYOwrgtgBAolDeAoKKoEEoF4oBYBMANIgL6KLAAeADgPYBOALlADbBMBmAliMAFyxZceANxQA9GKgB3egGsAzuWr0mrJjRpV5-ONhwBmURKjsAhp2aLExzLcxlQkKADEEyVM42CAjAAYiqFAAQqZ0gnj+JGTsYCAAxgycNCBQDKaywABqpsxgwAAUfC4AlAikaRnZuQXOAHSeNMVGkjJ0CogVWTl5+X5N4i1y8gCEHeld1b14+v3GwHR09KNkiEA)

<img width="326" alt="image" src="https://user-images.githubusercontent.com/22725671/225783739-5532e419-3616-4ac4-9f7c-1e19056432cf.png">

The issue is that this seems to only work with `number`s, but not with other types like `string`s. If we take the exact same code but replace all numbers with strings, we have this:

> Type '"42"' is not assignable to type 'E'. (2322)

[TypeScript Play](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230316#code/KYOwrgtgBAolDeAoKKoEEoF4oHIAsATDgDSIC+iiwAHgA4D2ATgC5QA2wrAZgJYjAAuWFlyEcAbigB6KVC4BDHmwDOUAEZhWygBb0wbACZQA7kwDWVOk1YdW9erWVC42fAGYJ02QqXLKMrEwgylBIKAAxBGRUcPsRHABGAAYSaJQAIXlGeIIU0gpELjAQAGNmHnoQKGZ5M2AANXk2MGAACkEIgEoEChq6xua28IA6WPpOyQDTRjM-PoamltbElImvOUUVdU0oHT1DE3NEeYGlxIIPNYCfFUpKIA)

<img width="417" alt="image" src="https://user-images.githubusercontent.com/22725671/225783960-8b90393c-4d2f-4b7b-a29a-37d573be7439.png">

### 🔎 Search Terms

enum, union, string

### 🕗 Version & Regression Information

This new feature was introduced in the v5.0.0, and I tested it locally in the v5.0.2 and in the sandbox with the version `5.1.0-dev.20230316`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230316#code/KYOwrgtgBAolDeAoKKoEEoF4oHIAsATDgDSIC+iiwAHgA4D2ATgC5QA2wrAZgJYjAAuWFlyEcAbigB6KVC4BDHmwDOUAEZhWygBb0wbACZQA7kwDWVOk1YdW9erWVC42fAGYJ02QqXLKMrEwgylBIKAAxBGRUcPsRHABGAAYSaJQAIXlGeIIU0gpELjAQAGNmHnoQKGZ5M2AANXk2MGAACkEIgEoEChq6xua28IA6WPpOyQDTRjM-PoamltbElImvOUUVdU0oHT1DE3NEeYGlxIIPNYCfFUQgA)

### 💻 Code

```ts
enum E {
    A = '42',
}

export let fine: E = '42'; // fails but should work
//         ^
export let oops: E = '43'; // fails as expected

// ====

enum F {
    Foo = '10',
    Bar = '20',
}

function takeValue(e: F) {}
takeValue(F.Foo); // works
takeValue('10'); // fails but should work
//        ^
takeValue('123'); // fails as expected
```

### 🙁 Actual behavior

The error `Type '"42"' is not assignable to type 'E'. (2322)` is sent by TS for the code `let fine: E = '42';`.

### 🙂 Expected behavior

This shouldn’t behave differently from numbers, so writing `let fine: E = '42';` could be allowed by TS

**Comment by fatcerberus** [comment]
AFAIK string enums are intentionally stricter than numeric ones, so this is probably by design.

**Comment by notaphplover** [comment]
It's doesn't seem to be a bug. Consider this [message](https://github.com/microsoft/TypeScript/pull/50528#issuecomment-1341136338) from the lead architect of TypeScript.

**Comment by Ayc0** [comment]
I think you’re right @notaphplover, this comment was a reply of a question in the PR exactly about the behavior mentioned by this issue. So it doesn’t seem to be a bug.

I’ll close this as completed.

**Comment by devlopersabbir** [comment]
### Here is a simple way to do that.

**Here the example of how to convert a Typescript enum to a union type**
```ts
export enum PaymentSystemEnum {
  APPLE = 'APPLE',
  GOOGLE = 'GOOGLE'
}
```
**And it’s pretty easy**
```ts
type = `${PaymentSystemEnum}`; // "APPLE" | "GOOGLE"
```

[Reference Link](https://medium.com/@d.rosenberg/convert-typescript-enum-to-union-type-ff06217889b0)
