### ISSUE TITLE
TS didnot transform `foo.return` from dot notation to bracket notation when targeting "ES5"

### ISSUE THREAD

**Issue by AnnAngela** [microsoft/TypeScript#53309]
# Bug Report

### 🔎 Search Terms

I searched `es5 dot notation` but no relative issue.

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `notation`
- I was unable to test this on prior versions because _______

After ts 5.0, the `target: ES3` configuration has been deprecated, but when I tried to configured the target as ES5, I noticed that the `foo.return` syntax was not transformed to bracket notation as required by the ECMAScript 5.1 Specification.

According to [Section 11.2.1](https://262.ecma-international.org/5.1/#sec-11.2.1), the dot notation should use _IdentifierName_. However, [Section 7.6](https://262.ecma-international.org/5.1/#sec-7.6) forbids using _ReservedWord_ as _IdentifierName_. Furthermore, [Section 7.6.1.1](https://262.ecma-international.org/5.1/#sec-7.6.1.1) lists the `return` as a _Keywords_ which is a type of _ReservedWord_ in [Section 7.6.1](https://262.ecma-international.org/5.1/#sec-7.6.1).

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1#code/MYewdgzgLgBAZiEMC8MDeBYAUDXMBOAplAK75gBcMARAiNQDTYC+A3NqJCADaEB0ASzAIAFHT5FS5AJSsgA)

### 💻 Code

```ts
const foo = {
    return: "foo",
};
console.info(foo.return);
```

### 🙁 Actual behavior

Output: `console.info(foo.return);`

### 🙂 Expected behavior

Output: `console.info(foo["return"]);`

**Comment by fatcerberus** [comment]
The spec text actually says:

> An *Identifier* is an *IdentifierName* that is not a *ReservedWord*

But dotted property access uses *IdentifierName*, not *Identifier*.

**Comment by AnnAngela** [comment]
Sorry for that ...
