### ISSUE TITLE
Altering input causes TS5055

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/TypeScript#53315]
# Bug Report

### 🔎 Search Terms

TS5055

### 🕗 Version & Regression Information

- This is a crash
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [TS5055](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-the-error-ts5055-cannot-write-file-xxxjs-because-it-would-overwrite-input-file-when-using-javascript-files)
- I reproduced this using TypeScript 4.4 and TypeScript 5.

### ⏯ Playground Link

N/A

### 💻 Code

```jsonc
// tsconfig.json
// Modifying anything, for example editing this comment, will cause the issue.
{
  "compilerOptions": {
    "checkJs": true,
    // This comment just broke some internal state
    "declaration": true,
    "emitDeclarationOnly": true
  }
}
```

```js
// index.js
// Modifying anything, for example editing this comment, will cause the issue.
```

### 🙁 Actual behavior

Run the following

```sh
$ # Run thow however many times you like
$ tsc --build
$ tsc --build
$ tsc --build
$ tsc --build
$ tsc --build
$ tsc --build
$ tsc --build
$ tsc --build
$ # Can also be reproduced by adding this to tsconfig.json instead.
$ echo '//comment' >> index.js
$ tsc --build
error TS5055: Cannot write file '/home/remco/Downloads/asd/index.d.ts' because it would overwrite input file.


Found 1 error.
```

Without the `--build` flag this happens regardless of any previous modifications.

To recover, run:

```sh
tsc --build --clean
```

### 🙂 Expected behavior

Consistency. It’s currently not clear if one is supposed to exclude `*.d.ts` or not.

**Comment by MartinJohns** [comment]
See #51291. You should set an outDir, otherwise the .d.ts is considered an input file.

**Comment by remcohaszing** [comment]
I want to publish the JavaScript files as-is. I would also like to publish the `.d.ts` adjacent to the JavaScript files they represent, as that’s needed to support all TypeScript module resolutions. So using `outDir` is not an option.

So the intended solution for this is to use `"exclude": ["*.d.ts", "**/*.d.ts"]` then?

Regardless of intended behaviour, I would at least expect behaviour to be consistent between runs.

**Comment by MartinJohns** [comment]
Yes, you should exclude the files. Best would be outDir tho.

Tho behavior is consistent. The first time it succeeds because there's no .d.ts file, following builds without changes work because there are no changes, so nothing is built

**Comment by RyanCavanaugh** [comment]
+1 to Martin's comments

**Comment by remcohaszing** [comment]
I’m running into this again, and it’s weird. There appear to be some conflicting aspects here.

1. I have a project with types in JSDoc.
2. The biggest benefit of using types in JSDoc is there is no need for a build step, except to generate the types.
3. A `.d.ts` represents the `.js` file that’s next to it.
4. In this issue I’m being told to use `outDir`.
5. If I have to use use `outDir`, this implies either:
   - (3) is incorrect; or
   - (2) is incorrect and `emitDeclarationOnly` shouldn’t be used.
6. According to `tsc -b` it’s perfectly fine to emit declarations next to the `.js` files
7. According to both `tsc` and the language server before building, it’s perfectly fine to emit declarations next to the `.js` files
8. According to both `tsc` and the language server after building:
   - it’s ok to emit declarations next to the `.js` files
   - it’s not ok to import files that are inside the project (relative imports). This shows an unclear error message in `tsconfig.json` with no reference to the cause (the import).
