### ISSUE TITLE
Upgrade to Typescript 5 doesn't add definition for findLastIndex on arrays

### ISSUE THREAD

**Issue by jez9999** [microsoft/TypeScript#53310]
I upgraded my Vue project to Typescript 5.0.2 expecting the errors I was getting around arrays having `findLastIndex` called on them to disappear as they should [now be defined](https://github.com/microsoft/TypeScript/issues/48829) in es2023, but I'm still getting the errors but in VS Code and when I `npm run build`.  Specifically the error is occurring when `vue-tsc --noEmit -p tsconfig.vitest.json --composite false` is run, which does a type check.  Here are the relevant config files:

***tsconfig.vitest.json***
```
{
	"extends": "./tsconfig.app.json",
	"exclude": [],
	"compilerOptions": {
		"composite": true,
		"lib": [],
		"types": [
			"node",
			"jsdom"
		]
	}
}

```

***tsconfig.app.json***
```
{
	"extends": "@vue/tsconfig/tsconfig.web.json",
	"include": [
		"env.d.ts",
		"src/**/*",
		"src/**/*.vue"
	],
	"exclude": [
		"src/**/__tests__/*"
	],
	"compilerOptions": {
		"ignoreDeprecations": "5.0",
		"allowJs": true,
		"outDir": "dist",
		"noImplicitAny": true,
		"jsx": "preserve",
		"composite": true,
		"baseUrl": ".",
		"paths": {
			"@/*": [
				"./src/*"
			]
		}
	}
}
```

The error in VS code has a popup that seems to suggest TypeScript itself is the problem:

> Property 'findLastIndex' does not exist on type 'MoveDelta[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2023' or later. ts(2550)

If I try setting that lib in my tsconfig.json, it doesn't appear to be available:

```
"compilerOptions": {
	"lib":["es2023"],
}
```

... gives the build error:

> Parsing error: Invalid value for lib provided: es2023

The VS Code TypeScript version is set to the workspace's (upgraded) version, 5.0.2, instead of VS Code's version.

What could be causing this problem?

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

I can confirm it works when you add `"es2023"` do your `lib` configuration. Don't be fooled by the error VSCode shows, the JSON schema to validate the config just hasn't been updated yet.

**Comment by jez9999** [comment]
I don't just get the error in VS code, I get the build error on the commandline: Parsing error: Invalid value for lib provided: es2023

**Comment by jez9999** [comment]
Even if that had worked, by the way, shouldn't it be unnecessary?  TS5's defaults libs should include it shouldn't they?

**Comment by MartinJohns** [comment]
> I don't just get the error in VS code, I get the build error on the commandline

It works fine here. What command are you running? Are you sure the `tsc` you're executing is the correct version?

> Even if that had worked, by the way, shouldn't it be unnecessary? TS5's defaults libs should include it shouldn't they?

TypeScript never enables the latest ECMAScript features by default, you need to adjust your settings. It'll also work by setting the target to `ESNext`.

Only thing that surprises me is the lack of a `ES2023` target.

**Comment by jez9999** [comment]
I changed my script command to`"type-check": "echo-cli \"TSC version:\" && tsc --version && tsc --noEmit -p tsconfig.vitest.json --composite false"`, and I still have `"lib": ["es2023"]` in my tsconfig files, and I get:

```
> echo-cli "TSC version:" && tsc --version && tsc --noEmit -p tsconfig.vitest.json --composite false

TSC version:
Version 5.0.2
src/lib/game/MoveBroker.ts:272:65 - error TS2550: Property 'findLastIndex' does not exist on type 'MoveDelta[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2023' or later.

272   const lastIndexForPiece: number = this.#currentTurnMoveDeltas.findLastIndex(x => x.pieceId === md.pieceId && this.isSoulOperation(x.opType) && !x.isCombine && !x.isCapture && !x.isClearStorms);
                                                                    ~~~~~~~~~~~~~

src/lib/game/MoveBroker.ts:272:79 - error TS7006: Parameter 'x' implicitly has an 'any' type.

272   const lastIndexForPiece: number = this.#currentTurnMoveDeltas.findLastIndex(x => x.pieceId === md.pieceId && this.isSoulOperation(x.opType) && !x.isCombine && !x.isCapture && !x.isClearStorms);
                                                                                  ~
```

I also did `npm install -g typescript@5` for good measure so that the globally-installed version of `tsc` is 5.0.2 but still get the same errors.

**Comment by jez9999** [comment]
OK, for some reason, my `tsconfig.vitest.json` was setting `lib` to the empty array.  I removed that and targeted `ESNext` in my other config files and it stopped complaining on the commandline.

However, I still get the error in VS Code.  Why might this be?

**Comment by MartinJohns** [comment]
> I still get the error in VS Code. Why might this be?

See my comment from earlier: https://github.com/microsoft/TypeScript/issues/53310#issuecomment-1473469102

The JSON schema hasn't been updated. That's part of VS Code, not of TypeScript.

**Comment by jez9999** [comment]
Actually I reset the machine and the error in VS Code went away.  Seems it was a caching issue :smile:

**Comment by thernstig** [comment]
Maybe relevent for this thread?

https://github.com/SchemaStore/schemastore/issues/3364
