### ISSUE TITLE
[5.0.2] Incorrect property type deduction with type guard

### ISSUE THREAD

**Issue by quangloc99** [microsoft/TypeScript#53313]
# Bug Report

### 🔎 Search Terms

type guard, control flow analysis

As this only breaks in version 5.0.2, I only found #53311 related to this issue but it seems like it is not the same.

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/PTAEHUHsCcGsEsB2BzUBTAHgQwLYAcAbNAKAG9jRQAXATzzVAEFQBeUU0DALlAFdEAJmgBmSNAIDcoAL7EK1OgwBCrdpx6JeOAEZpoU2fOH8AxlXiREoABZYAzgBERYgQDF4aAgIAUkHswAfUCUASh5IUHg7YPZ5Smg0Kl5oK0gAOgxQAEIWNn4hUURxCXlDSmNEMwsrAUgAZSThYV9-UCDQjS1daFjKSnhhUG9bR2citw8vXxCQ3r74xOTUjJL52XmEpJTQAAZVmWJDEFBXLHgiAXRsfCIyeVp6UABJYQAeAGFLAXhzSyuqNCCaLaSCQIhYRAAGlAABVoLw0DDFNDTgQ7IjFKp8mNxAA+VSfQQ-ar-QECaJUeEkeaUAD8sKpSPocT6PEJ31+VkwAKBoGEWDR1Jp9NR6KZQvmPDhCPFbROArFihK90xAA1XjDSbyQWC0BDVDrwYh8WxyPNuM83jDoZodHpcfsynzTJybPYnIVxO5PD4-KBVWFQBEov7XpSEfizX1Nksgxlsrk+IIcZJSnJyi6SbUGrwmi1-YHbd05v1BsN3SnvVNIDMS9HFtt0hh9pR1vWtlY9mnpEA)

### 💻 Code

The playground contains a working example and a failed example. The following is the failed one to keep it short.

```ts
  type If<Condition extends boolean, TrueType, FalseType = undefined> = Condition extends true
      ? TrueType
      : Condition extends false
      ? FalseType
      : TrueType | FalseType;

  type X<T extends boolean = boolean> = {
    x: If<T, number>;
  }

  function hasDefinedField(o: X): o is X<true> {
    return o.x !== undefined;
  }

  function doStuff(o: X): number {
    if (hasDefinedField(o)) {
      return o.x;
    }
    return 0;
  }
```

### 🙁 Actual behavior

- In side the if statement of `doStuff`, `o.x` has the type of `number | undefined`.

### 🙂 Expected behavior

- `o.x` should be number (as `o` should be `X<true>`). The working example shows this should be possible.

**Comment by MartinJohns** [comment]
A `boolean` in the context of distributive conditional types is interpreted as `true | false`, so you end up once in the `TureType` and once in the `FalseType` branch (as `Condition` extends once `true` and once `false`).

**Comment by quangloc99** [comment]
There was a comment before about true false branch but it got deleted :(.

Anyway, after that comment, I figure the following works too
```ts
  function doStuff(o: X<true> | X<false>): number {
    if (hasDefinedField(o)) {
      return o.x;
    }
    return 0;
  }
```

But I think `X<boolean>` should be the same as `X<true> | X<false>`.

**Comment by MartinJohns** [comment]
I've deleted the comment because I have no clue why it's been different in 4.9. And `X<boolean>` is equal to `X<true | false>`.

**Comment by quangloc99** [comment]
Yes, `X<boolean>` should be `X<true | false>`, but structurally `X<boolean>` should be the same as `X<true> | X<false>` as well.

```ts
type If<Condition extends boolean, TrueType, FalseType = undefined> = Condition extends true
    ? TrueType
    : Condition extends false
    ? FalseType
    : TrueType | FalseType;

type X<T extends boolean = boolean> = { x: If<T, number>; }

declare let a: X<boolean>;
declare let b: X<true> | X<false>;

a = b;
```
This works, because `X<boolean>` and `X<true> | X<false>` has the same structure.

**Comment by RyanCavanaugh** [comment]
*For all `X<T>`*, `X<true | false>` isn't the same as `X<true> | X<false>`, and it matters which you write here. "Small" unions of literals can be evaluated combinatorially in your example shown, but not always.

**Comment by quangloc99** [comment]
So can you help we with a work around for this? Previously, in 4.9.5, I use type guard to force the type of an `object` to have _defined_ property. Now I can not do this in 5.0.2.

**Comment by quangloc99** [comment]
> _For all `X<T>`_, `X<true | false>` isn't the same as `X<true> | X<false>`. Object types do not distribute over unions; it matters which you write here. "Small" unions of literals can be evaluated combinatorially in your example shown, but not always.

Sorry, but I think we have some minor miscommunication. What I want to point out is not to have a type guard to narrow down the `true` from the union `false | true`, but to narrow down `X<true>` from `X<true | false>` **as a separate type**. Sorry again if my interpretation is not clear enough, but the following example might show what I meant:

```ts
type A = X<true>;
function hasDefinedField(o: X): o is A {
    return o.x !== undefined;
}

function doStuff(o: X): number {
    if (hasDefinedField(o)) {
        return o.x;
    }
    return 0;
}
```
[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgZgHgMIHsB2ATAlsL6oQAewEmAzlAEYooA2EAhmgDRQAqATgK4RvgSsAYg1ple-KAF4oXTBDhY0EDAD4pUVJhx40BYqQwVg3CACgoFqAH52JvpHOWAXBvTZc+IiXJQ4IsY4WNsKi4g6WUC6cPPbQAD5QIWKxANympqCQUAAaCGx63oZUNPRM6tR0jGhq0gDeUIQu8HmsaFwAtpQQHCopUAC+6ZnQAILqucY8vaZwsgDGHroAFgxkACLyisqCWBC0GAAUKC7ZAJQuKFBYFGO1gVAcEMBcHLooAHSEUACEktKyGE2SgwaUGM3miygGBQAGVnnA4EcTucoG1Ot0oHcIlg4FADit1kDtrt9kdTqdMfcIo9nq8oB9CGkIoNqU8XroAAygoA)

This is also a working example. What I want here is to narrow `X<boolean>` to the exact type `A`, which is essentially the same type as `X<true>` **as a separate type**.

**Comment by quangloc99** [comment]
Hi @RyanCavanaugh. Sorry for the mention, but I see you labeled this issue `Not a Defect`, so I think you may have missed the above follow-up question. I am confused because the code in the issue does not work, while the code with the type assignment `type A = X<true>` still works fine. Please correct me if I'm wrong, but I genuinely think both codes should have the same behavior.
