### ISSUE TITLE
Legacy/Experimental parameter decorators fails with TS1239 when StrictNullChecks is true in Typescript 5.0.2

### ISSUE THREAD

**Issue by mrttrifork** [microsoft/TypeScript#53312]
# Bug Report

### 🔎 Search Terms

experimentalDecorator, TS1239, parameter decorator

### 🕗 Version & Regression Information

4.8.3 -> 5.0.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wMIHkByBlAFQCUBVDArIgfQEEiBxPOAXjgCIqqk0YoBXBDGhUAhlADmqNgG4AsACgFoSLDgwAnmGBwAssBgiAJiIMBpYOoKbtrNgBFgW5IeDIE6tnAA+7AlBFoAJauMJ4+bACSyABWwILQYexYYDCBKCIANomRqFGxgiIARhnAMgpK4NDwgcgwwFAAZiII2g5I-kJQVlpwAN4KcINq1gD8AFy6+kYmIuaW1nLyAL7l8spVcDV1jc3aeXEGxdqgdc6ocG3QJtDd2v3yQ5sxB0Ul43BEwA31ri23ADx8ZAAa2QEAA7sgAHyLR4QFJpZCZd6FCAQEoBRYrRTyLb1JotOA4YDg17AAEEKF9AZDZAkgAUADpmWJJBMAuoANoAXQAlBMCFjVhoep9vlBfuTrP9KSwiSSyRSqT50FAauJvHBUOoALaojKLCoqeANIGCREXRyuFxudT0mr5Q4lCZin5uKVaQEgsGQqG86kPIYSmB8KDIOCmtypFBwekGCT6dnIdQAGjgVAmqvVabAYhEOv09SiLhAE2QfD19X990ej246CejrsMwm+wKRzlNdr3YdLyOE177ZKKZp3ceIuAE3sVucvw8o9rS1hY4A9CvECgGwhQxLanoDMYDK3nkPtD4gS4GjVgIY5WKSoJGeJ9PvpgZ6QvHmvHrn-AXtsWoAjoG3bfkM8bPjAwFjnAYGDNg+DEGQFDUHQjCfkM368suoHrveByMpe16voeIj0r++aFlAgEgGmvTMoyg4wM2Bhpgx25QLuMAkTMSxphB+hpghhCkOQlC0AweDYQuS4KNiCgIBkIioOcBDAOgXaDPWvACJ09IAAIOE4NruPSbB1OgbD+mAaoAG4mNoFkwJmvDqtWqyPNiSxAA)

### 💻 Code

I provided the playground link

### 🙁 Actual behavior

i assume `@Dependency("test)` returns `undefined` and i set the type to `string` so i assume that's why it fails now

### 🙂 Expected behavior

There should be no error

**Comment by notaphplover** [comment]
It seems legacy decorators now requires their second parameter to allow undefined values:

```ts
export function Dependency(injectable: ReferenceType<unknown>) {
    return function (target: any, _: string | undefined, parameterIndex: number) {
       ...
    }
}
```

Consider [this example](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wMIHkByBlAFQCUBVDArIgfQEEiBxPOAXjgCIqqk0YoBXBDGhUAhlADmqNgG4AsACgFoSLDgwAnmGBwAssBgiAJiIMBpYOoKbtrNgBFgW5IeDIE6tnAA+7AlBFoAJauMJ4+bACSyABWwILQYexYYDCBKCIANomRqFGxgiIARhnAMgpK4NDwgcgwwFAAZiII2g5I-kJQVlpwAN4KcINq1gD8AFy6+kYmIuaW1nLyAL7l8spVcDV1jc3aeXEGxdqgdc6ocG3QJtDd2v3yQ5sxB0Ul43BEwA31ri23ADx8ZAAa2QEAA7sgAHyLR4QFJpZCZd6FCAQEoBRYrRTyLb1JotOA4YDg17AAEEKF9AZDZAkgAUADpmWJJBMAuoANoAXQAlBMCFjVhoep9vlBfuTrP9KSwiSSyRSqT50FAauJvHBUOoALaojKLCoqeANIGCREXRyuFxudT0mr5Q4lCZin5uKVaQEgsGQqG86kPIYSmB8KDIOCmtypFBwekGCT6dnIdQAGjgVAmqvVmqBLgaNWAhjTYDEIh1+nqURcIAmyD4evq-vuj0e3HQT0ddhmE32BSOcubLaHDpeRwmI77JRTNKHjxFwAm9itzl+HhnLaWsNnAHpt4gUO2EKGJbU9AZjAYe89J9ofLmvgXDHKxSVBIzxPoz9MDPT149d48Jb+OW2xVqA06BkOAFDPGH4wBBs5wNBgzYPgxBkBQ1B0Iwf5DABvJblBe4vgcjJ5gWX4XiI9JAWWFZQGBIBpr0zKMhOMBdgYaasUeUAnjAlEzEsaawfoaaoYQpDkJQtAMHgBHrpuCjYgoCAZCIqDnAQwDoIOgxtrwAidPSAACDhODa7j0mwdToGw-pgGqABuJjaLZMCZrw6pNqsjzYksQA).

Having said that, it would be great to update [legacy decorator typings](https://github.com/microsoft/TypeScript/blob/ba42ad36467506f81a4f77d536354c4cb90c32d9/src/lib/decorators.legacy.d.ts) to reflect this change. This is breaking every single decorator that relies on `ParameterDecorator` in ts5 with strict null checks. Consider [this example](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wMIHkByBlAFQCUBVDArIgfQEEiBxPOAXjgCIqqk0YoBXBDGhUAhlADmqNgG4AsACgFoSLDgwAnmGBwAssBgiAJiIMBpYOoKbtrNgBFgW5IeDIE6tnAA+7AlBFoAJauMJ4+bACSyABWwILQYexYYDCBKCIANomRqFGxgiIARhnAMgpK4NDwgcgwwFAAZiII2g5I-kJQVlpwAN4KcINq1gD8AFy6+kYmIuaW1nLyAL7l8spVcDV1jc3aeXEGxdqgdc6ocG3QJtDd2v3yQ5sxB0Ul43BEwA31ri23ADx8ZAAa2QEAA7sgAHyLR4QFJpZCZd6FCAQEoBRYrRTyLb1JotOA4YDg17AAEEKF9AZDZAkgAUADpmWJJBMAuoANoAXQAlBMCFjVhoep9vlBfuTrP9KSwiSSyRSqT50FAauJvHBUOoALaojKLCoqeANIGCREXRyuFxudT0mr5Q4lCZin5uKVaQEgsGQqH8uAABTEIh1+nqlw60GpDyGEpgfCgyDgprcqRQcHpBgk+nZyHUABo4FQJqr1ZrtXr0YWwMHQ9soi4QBNkHw9fVedHHo9uOgno67DMJvsCkc5fcuxO+y8jhMHdOSvmaZOhiLgBN7FbnL8PEuu0tYZOAPSHxAoXsIBMS2p6AzGAxD54jkqaoEuBo1YCGOVikqCRnifQb2mAx6V3R5j0eGt-DreoG1ARcYwnCCV1ZfQEOXZDBmwfBiDIChqDoRgwKGCDeQPJCTx-A5GTfD8gLvER6SgkMwygOCQELXpmUZOdBAHAxC24i8oCvGB6JmJZCyzACYELbDCFIchKFoBg8DI3d9wUbEFAQDIRFQc4CGAdBxyGHteAETp6QAAQcJwbXcek2DqdA2A7MA1QANxMbQXJgEteHVDt7g0rSgA).

cc @rbuckton

**Comment by mrttrifork** [comment]
Thanks a lot i added 
```typescript
export type UpdatedLegacyParameterDecorator = (target: Object, propertyKey: string | undefined, parameterIndex: number) => void;
```

as a workaround

**Comment by rbuckton** [comment]
The reported issue is an expected behavior and is mentioned in the breaking changes section of the 5.0 release blog post: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#more-accurate-type-checking-for-parameter-decorators-in-constructors-under-experimentaldecorators

@notaphplover is correct that the typings for the legacy `ParameterDecorator` type do not reflect this change.
