### ISSUE TITLE
Key remapping over the "keyof" of a generic type makes it non-assignable to equivalent types

### ISSUE THREAD

**Issue by ayloncarrijo** [microsoft/TypeScript#53326]
# Bug Report

### 🔎 Search Terms

key remapping, keyof, generic

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about key remapping

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0&ts=4.9.5#code/C4TwDgpgBAKhDOwBKEDGB7ATgEwDwGkIQoIAPYCAO23igAVN1JNRCQAaKANQEMAbAK4QAfFAC8UAN4AoKFADa+KAEtKUNlB618AXQBc3fkIDc0gL6npGSoigAzdOnFRcMYQAp0AIwBWBmACUBigYOLgA1kTodrCciJiqAOaiYqIycta2FIj+CMhoWHiRINGxUPFJKVDePpq0lBAAbhCYpnKYEMACmGrZwMZQAPSDsODQAORwiCGFEVExMHHACZTJ4yr16MB18MqJlDxefNDATqCQUOMzYcWli+XLlePmpkA)

### 💻 Code

```ts
type TestRecord<Key extends PropertyKey, Value> = {
  [K in Key as K]: Value;
};

const foo = <T>(obj: T): Record<keyof T, string> => {
  const test: TestRecord<keyof T, string> = obj as never;
  return test; // Type 'TestRecord<keyof T, string>' is not assignable to type 'Record<keyof T, string>'
};
```

### 🙁 Actual behavior

Using key remapping on the "keyof" of a generic type makes it unassignable to equivalent types.

### 🙂 Expected behavior

The type must be assignable as no changes were made.

**Comment by RyanCavanaugh** [comment]
Why would you write that if not to change `K` (in which case the error is always going to be correct) ?

**Comment by RyanCavanaugh** [comment]
You've basically descontructed the type through a process, put it back together again through another separate process, and are then hoping that TypeScript is able to recognize that the type hasn't actually changed. Appreciate the high expectation 😅 but it's not something that we can feasibly recognize.

**Comment by ayloncarrijo** [comment]
Well, at least there's a workaround for that. Thank you anyways!
