### ISSUE TITLE
Not possible to narrow unsupplied optional generic argument

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#53321]
# Bug Report

### 🔎 Search Terms

Optional generic parameter and conditional types, narrow optional generic parameter

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230317#code/GYVwdgxgLglg9mABAcwKZQIwB4CCAnZRVADylTABMBnRKqPGMQgH1vseQG0BdRV8CqmCNUFAHwAKAFCJEMCgHk8ASWoB+AFyJ8yKQEpEWnUVLlqbBk0RqLHPojAgANk5mHtBE2Uo06lrrw2AEqoEHB4FFh+HAA0tlasji5iblohYRFR7Exx0UxiiADesrJSAL5SUk7oiACGGIgAvCjoGBIA5O16ANxVNQBGDc1omBI8PX1QiBBDLaMCQiIUPYgA9KuI6eGReci52cgFALSICgDWk4gUsyNtK+vxLJuh21n++-72SU4FrFuZuw+HF+DmcTkQJxgUHaNDAcCmYFqeDwcAA7qJKlJQJBYAg5gAmXCeEjecy7ey7Hj2BbCMCiSRueRKVRUTQeXQGIzE0w+R7WPmJMGpdleMy+A5U4IvAEHIEJUHJYXGElihyoABuqDw-P+O1ljxSsjS0r17wNRRKiHKlWqU1q+KaBI6XV6tsQ-Qdw3Q+LG3AmbognqdNKW-pqFCDIx99w2ABE4KgqGB2lNUeEzkQoQALLWVB4AdXTSLgAghiBAVDscE1eCccFq1Eq2Og8CQIwAzBI9MaMqbYgbes3cW30O2iYQVbzyaxKbx+JRFnTxNJZEyVOouRz3MqeWSDvzpwrXEaRZO9-5Jc9e29+4fvobt9zSTQQ0udSabzlzVo6TXB+AWzxDsJHkKhmQoNlD1nbsBSPexdU-PZYPveCP0BA03CKRlgEQCQoAATwAB1QOAcNA8CmkaZoYQOLosMtPB0BAPAkE6XpZAqS1rUuWp20dYDOjDKZ+j4r0oE7cZXRqCBRLmTtX1EISrlk4CY1OC4pCAA)

### 💻 Code

```ts
function get1<Arg extends string | string[] | undefined>(
  idOrIds?: Arg
) : Arg extends string ? string | null
  : Arg extends string[] ? Record<string, string | null>
  : Record<string, string> {    
}

let a1 = get1('');
let b1 = get1([]);
let c1 = get1(undefined); // Record<string, string> - Ok
let d1 = get1(); // string | Record<string, string | null> | Record<string, string> | null - it's not narrowed


function get2<Arg extends string | string[] | undefined>(
  idOrIds?: Arg
) : Arg extends string ? string | null
  : Arg extends string[] ? Record<string, string | null>
  : Arg extends never ? Record<string, string>
  : Record<string, string> {    
}

let a2 = get2('');
let b2 = get2([]);
let c2 = get2(undefined);
let d2 = get2(); // Doesn't work either

// Workaround - using overloads

function get3(): Record<string, string>;
function get3<Arg extends string | string[] | undefined>(
  idOrIds?: Arg
) : Arg extends string ? string | null
  : Arg extends string[] ? Record<string, string | null>
  : Arg extends undefined ? Record<string, string> : never;
function get3(idsOrId?: string | string[]): string | null | Record<string, string | null> | Record<string, string>
   {
  if (typeof idsOrId === 'string') {
    return '';
  }
    
}

let a3 = get3('');
let b3 = get3([]);
let c3 = get3(undefined);
let d3 = get3(); // Ok
```

### 🙁 Actual behavior

If the generic parameter is optional, the conditional type in the return will not narrow it properly.

### 🙂 Expected behavior

The case of no argument being supplied should either be treated as undefined or never.

**Comment by MartinJohns** [comment]
The inference is as intended. If you want it to be a specific type in absence of the type argument you can use a default type.

**Comment by MartinJohns** [comment]
```typescript
function f1<T = string>() {}
```

If `T` is not supplied / can't be inferred it defaults to `string`. You can apply the same case in your method to default to `never` or `undefined`.

**Comment by mckravchyk** [comment]
Thank you.
