### ISSUE TITLE
Array.copyWithin() signature is incorrect

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#53334]
# Bug Report

The signature should be:

```ts
interface Array<T> {
  copyWithin(target: number, start?: number, end?: number): this
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

TS: 5.0.2

### 🙁 Actual behavior

Currently, it is:

```ts
interface Array<T> {
  copyWithin(target: number, start: number, end?: number): this
}
```

**Comment by jasonghent98** [comment]
Hi has this issue been resolved yet?

**Comment by ericbf** [comment]
@jasonghent98 it’s open, so that means no. Bit you can see on the sidebar there’s an open PR for it:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/2483476/226993473-0fd27aac-f030-4b8a-aa22-b3be2506c600.png">

**Comment by tchetwin** [comment]
https://github.com/mdn/content/pull/27296

MDN has since been updated to [reflect the spec](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.copywithin) - the `start` parameter is not optional

**Comment by ericbf** [comment]
> [mdn/content#27296](https://github.com/mdn/content/pull/27296)
> 
> MDN has since been updated to [reflect the spec](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.copywithin) - the `start` parameter is not optional

Probably best to create a new issue, linking that change
