### ISSUE TITLE
Usage of "!" to reverse variable of custom type not working correctly

### ISSUE THREAD

**Issue by Creative-Difficulty** [microsoft/TypeScript#53338]
# Bug Report
The ! (exclamation mark) usually "reverses" (turns true to false and the other way around) variables.
But with custom types (string types) it does not work that way, it would be logical to have it implemented like that.
My tsconfig.json:
```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2020",
    "sourceMap": true,
    "outDir": "dist",
  },
  "include": ["src/**/*"],
}
```

TypeScript version: 5.0.2
@types/node version: 18.15.3

### 🔎 Search Terms

Using !myVar to reverse a variable of a custom type
"!" usage for custom Types

### 🕗 Version & Regression Information
I have just seen bug occur today when developing a TS project.
Please keep and fill in the line that best applies:
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type "reversing"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBFBOBDAJgUwCIEt6uFT4MAvDAN4zLa77gBcMARAEICqAmgzAL4BQoksAGYh4AW0QAbACpI0WHHgJh6DCeADmnAD6MIACxFROJBCgxVF4AHSUFNMMSIlm7TgH5GasJpgr9hhgBuPnAIEAlUKzV1AAoAQmExSRkzeWolAEoeGBggA)

### 💻 Code

```ts
const tradeDirection = { direction: "BUY" }
const formalTradeDirection: "long" | "short" = tradeDirection.direction === "BUY" ? "long" : "short";
console.log(!formalTradeDirection)
```

### 🙁 Actual behavior

`console.log(!tradeDirection)` produced "false"

### 🙂 Expected behavior

`console.log(!tradeDirection)` to produce "short"

**Comment by MartinJohns** [comment]
This is unrelated to TypeScript, this is just how JavaScript operates. Running this code in JavaScript will print `false` as well.

**Comment by fatcerberus** [comment]
Also, this is a not a bug.

**Comment by Creative-Difficulty** [comment]
Ok, sorry
