### ISSUE TITLE
Property 'findIndex' does not exist on type 'number[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

### ISSUE THREAD

**Issue by LuoRiWuSheng** [microsoft/TypeScript#53342]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙂 Expected behavior

1、vs code version
```
版本: 1.76.2 (system setup)
提交: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
日期: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22624
```

2.   tsc -V
typescript:   5.0.2

global install

3. small  demo

![image](https://user-images.githubusercontent.com/23192097/226117339-f6af89ba-ed1d-43f3-8aec-e9762d81c208.png)

4、  my config file  

```
 "target": "ESNext",  
  "lib": ["ESNext", "ESNext.Array","DOM"],  
```

![image](https://user-images.githubusercontent.com/23192097/226117362-4dfd0990-cea9-4527-a5d2-d1479ee2259c.png)

I tried restarting the vscode tool and running the command again, but it still didn't work；  

I want to know why I set lib, but the compilation still reported an error, but the file was actually converted normally again

**Comment by MartinJohns** [comment]
This is working as intended. When invoking `tsc` with filenames to compile (like `tsc 2.ts`) it won't use your tsconfig file, and as you don't provide arguments for target and lib they are set to the default values that don't provide definitions for `findIndex()`.

**Comment by LuoRiWuSheng** [comment]
> This is working as intended. When invoking `tsc` with filenames to compile (like `tsc 2.ts`) it won't use your tsconfig file, and as you don't provide arguments for target and lib they are set to the default values that don't provide definitions for `findIndex()`.
> 
> https://www.typescriptlang.org/docs/handbook/compiler-options.html
> 
> > # Emit JS for just the index.ts **with the compiler defaults**
> > tsc index.ts
> 
> https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson-or-jsconfigjson
> 
> > When input files are specified on the command line, `tsconfig.json` files are ignored.

thanks   

```
tsc --project ./tsconfig.json
```
After I specified the configuration file, there were no errors；  

It's a problem I use
