### ISSUE TITLE
Incorrect generated JS code when private (hashtag) property is used with parenthesis in left assignment

### ISSUE THREAD

**Issue by jbl428** [microsoft/TypeScript#53347]
# Bug Report

When private (hashtag) property is used with parenthesis in left assignment, TS generate `__classPrivateFieldGet`, not `__classPrivateFieldSet`.

I think this issue is related with [this one](https://github.com/microsoft/TypeScript/issues/49935).
It should apply `__classPrivateFieldSet` only if there is incrementing/decrementing operations.

### 🔎 Search Terms

- __classPrivateFieldGet
- private property
- Invalid left-hand side in assignment 

### 🕗 Version & Regression Information

- If compile target is `ES2022`, it is not an issue.
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about setting private property.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=8#code/MYGwhgzhAEAqCmBbADtA3gKGtATvMAJgPYB2IAngMQCWBAXNCQK6IBG8OA3BltMKRAAuOJsEFEcACgBuYEE3gNmbDgEp0vbIIAW1CADoaBaAF5os+fG7YAvj2wR4ggJIFJtJS3Y51mbNkkdPUNaaEhGLzVTaFpraDs7DBJ4AHc4JGRJAEYABlV9Rxc3ACY8oA)

### 💻 Code

```ts
class Temp {
  readonly #id: number;

  constructor(value: number) {
    this.#id = value;
  }

  setId(id: number) {
    (this.#id as number) = id;
    // (this.#id) = id <-- this one is also problem.
  }
}

new Temp(10).setId(20)
```

### 🙁 Actual behavior

TS generate the following code.

```js
class Temp {
    constructor(value) {
        _Temp_id.set(this, void 0);
        __classPrivateFieldSet(this, _Temp_id, value, "f");
    }
    setId(id) {
        __classPrivateFieldGet(this, _Temp_id, "f") = id; // it will throw error `Invalid left-hand side in assignment`
    }
}
```

### 🙂 Expected behavior

TS should generate the following code.

```js
class Temp {
    constructor(value) {
        _Temp_id.set(this, void 0);
        __classPrivateFieldSet(this, _Temp_id, value, "f");
    }
    setId(id) {
        __classPrivateFieldSet(this, _Temp_id, id, "f");
    }
}
```

**Comment by fatcerberus** [comment]
Random aside, I’m not sure I’d describe these as “hashtag properties” any more than I’d describe a bear as a fat dog

**Comment by rbuckton** [comment]
> Random aside, I’m not sure I’d describe these as “hashtag properties” any more than I’d describe a bear as a fat dog

Common parlance in TC39 is to call them "private elements".

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
