### ISSUE TITLE
.d.ts emit drops JSDoc when generating overload signatures from JSDoc `@overload`

### ISSUE THREAD

**Issue by aduth** [microsoft/TypeScript#53350]
# Bug Report

### 🔎 Search Terms

- `overload`
- `jsdoc`

### 🕗 Version & Regression Information

5.0.2

- I was unable to test this on prior versions because this is newly introduced in 5.0

### ⏯ Playground Link

[Broken JavaScript/JSDoc version](https://www.typescriptlang.org/play?filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQdQAxAVwDt5IBLAe3NABNlp4AnagBxvoDoCiAiLQBuyNgBtaAQ0ZDwnaW2kBbUAG9okDuQDmAX1AjpE0slAAFJaqMmzTFuy49y-QhDbJIpNg3UjaakZDACUvHwZjU3NmVg5uOlcBYCxcfHcyShcHOOdEt0F3cFFxKVl5RWU1dXJSFQAjcUMo+ysq22icpwS+Cutq2oam0ABtFWkAD2oVOuJlKkSAEWpdahgAXUt+0HGpmZU56QX6ZdWYLviXAo9w3w0AoNDbyLsYx0v85NS8IUzjhli3SuQj67U02moelAAB9QINGmxmq8tu0Wm9cj0kkVKjYanUEYYxpNprN5i5TmtoJs2jZdiSDmSlitKRc8r1CCkAGYUf6gTg6SAANVeAAo0QAaHbE-aHf4UmAASg0BFAquonNAIsgAE9OMhaBq0aAALym0AAInh4nNSvUKtVDtA8HoWlAnNobHGkEg4hNoAAkuRIBJeAA5fHiYger0i83IciwACqAGVzZK7Y7Mw66TLGSdmTBxfbM-oFQBuYuOo3Gt3R6Te8S8d2e+ti17l4v6LCO53kaC0CTIXhSXRt6Id-RAA) (see missing comment documentation in `.d.ts` output):

[For comparison, see working TypeScript version](https://www.typescriptlang.org/play?ssl=3&ssc=4&pln=1&pc=4#code/PQKhCgAIUgxBXAdgYwC4EsD2jIBMCmAzsgE7oAOG2AdFDHZAALkCGJLAtpIaiZAAptO3XniKkKVRLWhMS+VPBI4ASgqU4AbiwA28fGOJlKWaXWDgAZkjSnI5MolQA1XfoAUPEgC4RjgOYAlL6amOi4ANzg4KAQsggoUoYSJjQMDMxCXIjwXILs2bnJxlIyMJkFkBwsAB6w7LbYACLo-uiohAJZVbX1LI2ILW0dxZKmZXLqypBqitPaegYERmNp0BbWiXYO6E6ui+45HL5HAEb4JAA0PXUNUkPthAD8J7nnJMGQoeFRMWAMCQGo1SZlkGVYlQW+i6kLcS3EJXG4O61Vu-XurUeMOEqL6AweI2WKVKGXkc1UUy0cOBJPWVhsSR2ezh7ih+F8Xl2-kgAB9IGcLtdUegOLk8Rjhs9Xhx3oFIABvKCQZXoSyQdyoACe5HwmDVbMgAF5jZAAEQCkimuWK5W223IbA8SCWTAkaqoVAXI2QACSTh01AAcm8LrBXe73Kb8IgALQAVQAyqbrja7WnlcLRRxxaYCYRLkr0wBfQJRdPKg2G53hlgei7UF1u2usuGlwuQIvRO0OxCETA6fDUHSYfwtxZtotAA) (see included comment documentation in `.d.ts` output):

This snippet of code was adapted from the [announcement post description](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#overload-support-in-jsdoc).

### 💻 Code

```js
// @ts-check

/**
 * Function description.
 * 
 * @overload
 * @param {string} value Param value description.
 * @return {void} Return value description.
 */

/**
 * Function description.
 * 
 * @overload
 * @param {number} value Param value description.
 * @param {number} [maximumFractionDigits] Param maximumFractionDigits description.
 * @return {void} Return value description.
 */

/**
 * Function description.
 * 
 * @param {string | number} value Param value description.
 * @param {number} [maximumFractionDigits] Param maximumFractionDigits description.
 */
function printValue(value, maximumFractionDigits) {
  // ...
}
```

### 🙁 Actual behavior

There are no docblock comments in generated `.d.ts`.

Screenshot from broken JavaScript/JSDoc code snippet:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/1779930/226180484-7252c0be-494a-4856-9089-677d23263c11.png">

### 🙂 Expected behavior

Generated `.d.ts` includes docblock comment descriptions for function, parameters, and return value of overloaded forms.

Screenshot from working TypeScript playground link above:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/1779930/226180331-d787d3ae-4280-4483-848c-314f4d027089.png">

**Comment by fatcerberus** [comment]
Just letting you know, you swapped the expected and actual behavior (but not the corresponding screenshots, oddly).

**Comment by aduth** [comment]
> Just letting you know, you swapped the expected and actual behavior (but not the corresponding screenshots, oddly).

Thanks! I updated the original text.
