### ISSUE TITLE
In mapped types with key remapping, any property involving a generic type argument is dropped.

### ISSUE THREAD

**Issue by martaver** [microsoft/TypeScript#53357]
# Bug Report

When performing key remapping in mapped types, any property involving a generic type argument is dropped from the resulting type.

### 🔎 Search Terms

Mapped types with generic properties
Key remapping with generic properties
Properties with generic type dropped from mapped type with 'as' key remapping

### 🕗 Version & Regression Information

I first noticed it in `4.9.5` and still exhibited in `nightly` (`5.1.*`). Tried every version in playground down to `4.1.*`, same behavior.

This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Type System Behavior`, `Classes`, `Generics`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.1.5#code/KYDwDg9gTgLgBDAnmYcBiBLANjYUByEMAFhgHYDmAPACoB8cAvHAN5wDaACnOXANbBEEAGZwacAIYBnMVwC6cULjIATGTXlwA-HG4AuXXIMbOCgL4AoCwGMs09cCkwqALQYsLcL3GEQIACgkoCikDTBw8QhJyajYBRAMyAFcAWwAjPAAaOAA3CSwk4AMXbLSggwARCVw4MzoASlYrbxa4awgyJ1Z+QWy8guBSoNqmSWCpAG5Pb0szIA)

### 💻 Code

```ts
export type FilterNothing<T> = { [P in keyof T as T[P] extends T[P] ? P : P]: T[P] }

class Test<Z> {
    foo(args: FilterNothing<{ key: number, value: Z, bar: Date }>) {

        const { key, value, bar } = args; // value is missing
    }
}
```

### 🙁 Actual behavior

`value` is omitted from the resulting type, even though all properties `P` are emitted. Any property that has a type involving a generic type parameter always gets dropped from the key remapping.

### 🙂 Expected behavior

`value` to be on the resulting type as `Z`, since its key would be emitted and type looked up  by `T[P]`.

**Comment by Andarist** [comment]
> So maybe it's that as in key remapping drops unresolved (deferred) types?

Yes, that's exactly what happens. This conditional type stays deferred and thus it fails `isTypeUsableAsPropertyName` check later on and ain't added as a property to the result of this whole mapped type within this generic context.

**Comment by martaver** [comment]
Is there a reason why key remapping should drop deferred types, then, or is it just incomplete?

**Comment by Andarist** [comment]
How do you access a **property name** that is typed using a deferred type? This conditional type decides if that property got filtered out from the type or not. If TS can't resolve it immediately then it can't assume that it's there so it becomes inaccessible.

**Comment by martaver** [comment]
That makes sense! So in other words, "How can you name a property based on a type that hasn't been resolved?"

In the cases I provide, though, the only possible outcomes are `never` or `P` (a valid property name). `never` should be dropped, obviously...

Maybe typescript should attempt to resolve the conditional before evaluating the property name? That way it would be able to tell whether or not it can name the property, even if the type contains generic arguments.

**Comment by Andarist** [comment]
`never` is dropped from the union but it has a special meaning here - it makes the mapped type *filter out* given property. So it's not exactly the same.

I think that it's best to visualize this outcome as equivalent to:
```ts
type Preserved = { a: 1, b: 2 }
type Filtered = { a: 1 }

type Both = Preserved | Filtered

type Ok = Both['a']
type Err = Both['b']
```

Conceptually a very similar thing happens, at the generic level if your property name stays deferred it can end up being both (`P` or `never`). This makes us "expand" the result into a union of all possible outcomes.

**Comment by Andarist** [comment]
This is what I mentioned in one of the previous comments ([here](https://github.com/microsoft/TypeScript/issues/53357#issuecomment-1476749492)). I'm not sure why this particular type has to be deferred.

**Comment by martaver** [comment]
Ahhh... okay a little more context then... 

I came across the problem trying to filter our properties that have been explicitly marked as `never` from a type:
```
type FilterNeverProps<T> = { [P in keyof T as T[P] extends never ? never : P] : T[P] }

class Test<Z> {
    foo(args: FilterNeverProps<{ key: never, value: Z, bar: Date }>) {

        const { key, value, bar } = args; // 'key' is dropped, but 'value' is too...
    }
}
```

In the above, I expected `key` to be dropped, and Z to be retained. When I sought help, I was told that since never is assignable to Z, typescript had to consider all indeterminate cases and also dropped it.

So I tried a different approach, using a branded type to mark properties I wanted dropped:
```
interface ignore { readonly __ignore__: "__ignore__" }

type FilterIgnoreProps<T> = { [P in keyof T as ignore extends T[P] ? never : P]: T[P] }

class Test<Z> {
    foo(args: FilterIgnoreProps<{ key: ignore, value: Z, bar: Date }>) {

        const { key, value, bar } = args; // 'key' is dropped, but again 'value' is dropped too...
    }
}
```
In this approach, I flipped the `extends` to ensure that only properties that were exactly of the `ignore` type are dropped. In this case, `never` is still assignable to `Z`, but if `Z` is `never` then the conditional resolves as `P` because `ignore` is NOT assignable to `never`:
```
type x = ignore extends never ? 1 : 0; // Resolves as '0'
```

That's what led me to try a noop conditional where both branches return `P` and I found that no matter what I tried, any generic type is ALWAYS dropped when used in an `as` key remapping. 

The same is not true in a simple Identity mapped type, where `Z` and `never` are all passed through:
```
type Identity<T> = { [P in keyof T]: T[P] }

class Test<Z> {
    foo(args: Identity<{ key: never, value: Z, bar: Date }>) {

        const { key, value, bar } = args; // 'value' should exist        
    }
}
```

So I thought this inconsistency might be a bug!

**Comment by RyanCavanaugh** [comment]
The inconsistency is an intentional difference.

You're one of the [lucky 10,000](https://xkcd.com/1053/) today to learn about homomorphic mapped types - see #26063

**Comment by Andarist** [comment]
@RyanCavanaugh do you happen to know why `T extends T ? 1 : 0` gets deferred?

**Comment by RyanCavanaugh** [comment]
I think the example given is degenerate to the point that it's not useful to discuss. If you write `T[P] extends T[P] ? P : P` expecting it to just exactly like `P`, well, then you should obviously just have written `P`, `P` is already the thing that behaves exactly like `P`. Discussing the behavior of that example is misleading because it has invariants that real usages with different behavior would not.

**Comment by martaver** [comment]
I mean, I was only using the example to illustrate a broader issue... which was the inability to pass generic types through any kind of key remapping.

A more concrete example would be to filter out properties that are of type `never`:
```
type FilterNeverProps<T> = { [P in keyof T as T[P] extends never ? never : P] : T[P] }

class Test<Z> {
    foo(args: FilterNeverProps<{ key: never, value: Z, bar: Date }>) {

        const { key, value, bar } = args; // 'key' is dropped, but 'value' is too...
    }
}
```

But then I noticed that the `value` property was always dropped regardless of the `as` clause. Hence the 'degenerate' example.

I thought the whole point of `as` syntax was to map property names, and (because of its special handling of never) filter them. It seems quite limiting if `as` always drops any properties that are of a generic type without any resolution?

**Comment by Andarist** [comment]
I think that the current logic is fine and that it's very consistent with the rest of TypeScript. As I mentioned, given that this object depends on a generic it's essentially equivalent within this method to smth like:
```ts
type Args = { bar: Date, value: Z } | { bar: Date }
```
TypeScript doesn't allow you to access properties that are members of *some* union constituents - you can only access common keys. This is exactly how it works in concrete scenarios:
```ts
type Concrete = { bar: Date, value: number } | { bar: Date }
declare const c: Concrete
// Property 'value' does not exist on type 'Concrete'.
//  Property 'value' does not exist on type '{ bar: Date; }'
c.value
```

> It seems quite limiting if as always drops any properties that are of a generic type without any resolution?

Similar limitations are quite common in TypeScript. As long as things stay generic the reasoning capabilities are limited - often for good reasons though (and I think that this one is a good reason).

---

I think that perhaps what you would like to ask for here is the ability to narrow this implicit union using `in` operator:
```ts
type FilterNeverProps<T> = {
  [P in keyof T as T[P] extends never ? never : P]: T[P];
};

class Test<Z> {
  foo(args: FilterNeverProps<{ key: never; value: Z; bar: Date }>) {
    if ("value" in args) {
      args.value; // error but it wouldn't have to be
    }
  }
}
```

**Comment by martaver** [comment]
E.g. even if I constrain `Z` with a concrete type like `string`, the never case is still considered and `value` is dropped:
```
type FilterNeverProps<T> = { [P in keyof T as T[P] extends never ? never : P]: T[P] }

class Test<Z extends string> {
    foo(args: FilterNeverProps<{ key: never, value: Z, bar: Date }>) {

        const { key, value, bar } = args; // 'value' should be (Z extends string)
    }
}
```

Or am I still misunderstanding something?

**Comment by Andarist** [comment]
> E.g. even if I constrain Z with a concrete type like string, the never case is still considered and value is dropped:

That's just caused by what you have already mentioned - `never` is assignable to everything. So despite your `string` constraint... it can still be passed to it.

**Comment by martaver** [comment]
Yep, got that - I suppose my point is that maybe there should be a way to escape the `never` case, asserting not-never?
