### ISSUE TITLE
Object methods type holes

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#53353]
# Bug Report

### 🔎 Search Terms

method field type check hole

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gWxBgFksAFzwAUADrFNqZjAJYoDmAlPALwB88Abkg2AAoIQHpR8APIBpUgBUAnhQQByFAFcIEFfAZp4KJFiho0DZiigAjCAgxJ4GJavpNmKgHQY0ZAEwBmX19WIRAADwokGCxkdCwkKwArcAwARlIAbxw8QhJyKhgaOgxGFngAHwNNCHZuPgFgeABfTngs3AIiZpFxeAA5BxAYGCiAGngrdSxw5TAMEGEZqJjUTHgE5LnfTOzOxspqWnhXMsqNLVZSfkFm1vacrqahIA)

### 💻 Code

```ts
declare const method: (param: string) => void

// OK: Type 'null' is not assignable to type 'string'.ts(2322)
export const object1: { method: (param: string | null) => void } = { method }

// No error, but expected
export const object2: { method (param: string | null): void } = { method }

```

### 🙁 Actual behavior

`object2` produces no error

### 🙂 Expected behavior

`object2` produces the same error as `object1`

**Comment by fatcerberus** [comment]
Despite the soundness hole, this is expected behavior; methods are intentionally bivariant.  From https://github.com/microsoft/TypeScript/pull/18654:

> Methods are excluded specifically to ensure generic classes and interfaces (such as `Array<T>`) continue to mostly relate covariantly.

**Comment by awerlogus** [comment]
@fatcerberus Thank you for the explanation. Then I'm closing this
