### ISSUE TITLE
Auto-import suggestions prioritize aliased relative paths over package imports

### ISSUE THREAD

**Issue by sarimarton** [microsoft/TypeScript#53369]
# Bug Report

### 🔎 Search Terms

auto import alias relative package

### 🕗 Version & Regression Information

5.0.2

### ⏯ Playground Link

Can't have a playground link, it's an auto suggest issue.

### 💻 Code

When using a custom alias in a project's tsconfig.json, the auto-import suggestions in VSCode prioritize the aliased relative paths over package imports, despite having "non-relative" preference set in settings.json. This occurs only when a package is symlinked within a workspace.

### 🙁 Actual behavior

TypeScript version: 5.0.2
VSCode version: 1.76.2
Operating System: Windows 10

1. Configure tsconfig.json in the app:

```json
{
  "compilerOptions": {
    "baseUrl": "."
    "paths": {
      "@/*": ["./*"]
    }
  }
}
```

2. Set settings.json preferences (probably irrelevant):

```json
{
  "javascript.preferences.importModuleSpecifier": "non-relative",
  "typescript.preferences.importModuleSpecifier": "non-relative"
}
```

3. Create a workspace and symlink the @company/common package.

With the above configuration, when trying to auto-import a component, the auto-suggester suggests a relative import from the app folder to the common package. For instance, it suggests '@/../common' instead of '@company/common'.

### 🙂 Expected behavior

Auto-import suggestions should prioritize package imports over aliased relative paths when the "non-relative" preference is set in settings.json

### Workarounds

- Removing the paths configuration or changing it to target a subdirectory (e.g., "@/src/": "./src/") allows the auto-suggester to work as expected.
- Manually adjusting the import statements also works, TS recognizes the correct package path, only the suggestion part is wrong.

### Additional context

Not sure if it's relevant, but the package @company/common has

```json
  "exports": {
    ".": "./lib/index.tsx",
    "./engie": "./lib/engie/index.tsx"
  },
```

in its package.json, and moduleResolution is set to "bunder".

The issue persists with any alias used in the paths configuration, and not just with the '@' symbol. The pattern `"<anything>/*": "./*"` seems to be insufficient to trigger the package suggestion. E.g. ,

```json
{
  "compilerOptions": {
    "baseUrl": "."
    "paths": {
      "~root/*": ["./*"]
    }
  }
}
```

will trigger `~root/../common` instead of `@company/common`.

**Comment by andrewbranch** [comment]
@sarimarton I doubt this is specific to `bundler`—are you able to tell if this bug is a regression in 5.0 or if it’s older?

**Comment by sarimarton** [comment]
I've made some tests with ts@4.7.4 and 5.0.2.

In short:
- It's not specific to 5.0.2
- The bug happens when the common lib is symlinked and the export is coming from an "exports" subdirectory mapping.

See the blue arrows (➡️) below.

As part of my testing sequence, I recorded another possible bug, namely that node16/nodenext doesn't recognize wildcard re-exports. If that's known, sorry for the noise.

### Test scenario:

package.json:

```json
  "main": "lib/index.tsx",
  "exports": {
    ".": "./lib/index.tsx",
    "./engie": "./lib/engie/index.tsx"
  },
```

- @company/common/engie exports `Tooltip`
- @company/common exports `Common`
- @company/common exports * from 'file' which exports `Wildcard`

### Test runs:

- TS@4.7.4, no symlink, "moduleResolution": node16 & nodenext:
  - ✔️suggests Tooltip from '@company/common/engie'
  - ✔️suggests Common from '@company/common'
  - ❌doesn't suggest Wildcard from @company/common
  - ✔️import { Tooltip } from '@company/common/engie' works
  - ✔️import { Tooltip } from '@company/common/lib/engie' Cannot find module
  - ✔️import { Common } from '@company/common' works
  - ❌import { Wildcard } from '@company/common' Module has no exported member

- TS@4.7.4, ➡️symlink, "moduleResolution": node16 & nodenext:
  - same as previous no symlink, except that
  - ❌suggests Tooltip from '@company/common/lib/engie/index.js' (which it correctly refuses in the imports)

- TS@5.0.2, no symlink, "moduleResolution": "node16" & nodenext:
  - everything is same as TS@4.7.4

- TS@5.0.2, ➡️symlink, "moduleResolution": "node16" & nodenext:
  - everything is same as TS@4.7.4

- TS@5.0.2, no symlink, "moduleResolution": "bundler":
  - ✔️suggests Tooltip from '@company/common/engie'
  - ✔️suggests Common from '@company/common'
  - ✔️suggests Wildcard from @company/common
  - ✔️import { Tooltip } from '@company/common/engie' works
  - ✔️import { Tooltip } from '@company/common/lib/engie' Cannot find module
  - ✔️import { Common } from '@company/common' works
  - ✔️import { Wildcard } from '@company/common' works

- TS@5.0.2, ➡️symlink, "moduleResolution": "bundler":
  - same as no symlink, except that
  - ❌suggests Tooltip from '~/../common/engie'
