### ISSUE TITLE
never conditional type leak

### ISSUE THREAD

**Issue by unional** [microsoft/TypeScript#53364]
# Bug Report

```ts
type Foo<N> = N extends 0 ? 1 : 2;
type N = Foo<never>; // never
```

### 🔎 Search Terms

never, conditional type

### 🕗 Version & Regression Information

TS: 3.3 - 5.0.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=3.3.3#code/C4TwDgpgBAYg9nAPAOQHxQLxWVCAPYCAOwBMBnKABigH4oBGKALigCYBuAWAChRJtMsBIiIQAbhABOqdlAD0cqKImSeQA)

### 💻 Code

```ts
type Foo<N> = N extends 0 ? 1 : 2;
type N = Foo<never>; // never
```

### 🙁 Actual behavior

```ts
type Foo<N> = N extends 0 ? 1 : 2;
type N = Foo<never>; // never
```

### 🙂 Expected behavior

`never` should be the bottom type, so it extends nothing.
Therefore, the result should be `2`

```ts
type Foo<N> = N extends 0 ? 1 : 2;
type N = Foo<never>; // 2
```

**Comment by fatcerberus** [comment]
Distributive conditional types treat `never` as an empty union, so it distributives over nothing and the type evaluates to `never`.  This is the intended behavior.

**Comment by jcalz** [comment]
Duplicate #23182

**Comment by unional** [comment]
> Distributive conditional types treat never as an empty union, so it distributes over nothing and the type evaluates to never (i.e. still an empty union, like how .map over an empty array returns an empty array).

Got it. Trying to provide a clear example as "In this case never behaves as the empty union, so it distributes over the conditional and produces another empty union (which is just never again)" from https://github.com/microsoft/TypeScript/issues/23182#issuecomment-379094672 is not too clear to me.

One problem is that it is hard to envision this with TypeScript syntax:

```ts
type Foo<N> = N extends 0 ? 1 : 2;

type N = Foo<1 | 0>
       = 1 | 0 extends 0 ? 1 : 2
       = (1 extends 0 ? 1 : 2) | (0 extends 0 ? 1 : 2)
       = (2) | (1)
       = 2 | 1

type N = Foo<1>
       = 1 extends 0 ? 1 : 2
       = 2

type N = Foo<never>
       = never extends 0 ? 1 : 2
       = "empty union" extends 0 ? 1 : 2
       = ...
````

Let's try to describe it using a pseudo-lisp/fp syntax.

Here I use `<a | b>` to describe union for clarity:

```ts
type Foo<N> = N extends 0 ? 1 : 2;
            = (extends_0, N, 1, 2)

// i.e. 
extends_0(N, 1, 2)
// where
function extends_0(n, t, f) { return (n extends 0)? t : f }


type N = Foo<1 | 0>
       = (extends_0, <1|0>, 1, 2)
       = <(extends_0, 1, 1, 2) | (extends_0, 0, 1, 2)>
       = <2 | 1>
       = 1 | 2

type N = Foo<1>
       = (extends_0, <1>, 1, 2)
       = (extends_0, 1, 1, 2)
       = 2

type N = Foo<never>
       = (extends_0, <>, 1, 2)
       = <>
       = never
```

**Comment by fatcerberus** [comment]
@unional

> ```ts
> type N = Foo<never>
>        = never extends 0 ? 1 : 2
>        = "empty union" extends 0 ? 1 : 2
>        = ???
> ```

That would just be

```ts
type N = Foo<never>
       = never extends 0 ? 1 : 2
       = [nothing to distribute over, RHS is irrelevant]
       = never
```

It makes more sense to think of it as, the TypeScript syntax for "empty union" *already is* `never`.  This nicely models lots of things like, e.g, if you narrow all the possibilities out of a discriminated union, you get `never` in the else case.  It just so happens that because of how type unions work in TS, the "empty union" type also conveniently works as the bottom type.

**Comment by unional** [comment]
I think the confusion to me are things like:

> nothing to distribute over, RHS is irrelevant

It's like:

```ts
if (union.length === 0) {
  // early return
  return never
}
```

This sounds like a go-to statement, that's why it is hard to reason.

> you get `never` in the else case
What is this "else case? The conditional-type-ternary statement? i.e. `2` in `never extends 0 ? 1 : 2`?

What I tried to describe is that since we are talking about union distribution,
it is the same as arithmetic distribution.
e.g.: `(1 + 2) * 3 = (1 * 3) + (2 * 3)`.

Consider `+` as the symbol for union, and `*` as the symbol for the extend *function*.

i.e. `x extends 0 ? t : f` = `*`.

Describing that function in pseudo-typescript: `function extends_0(n, t, f) { return (n extends 0)? t : f }`

Describing that same function in pseudo-lisp: `(extend_0, n, t, f)` (omitting the implementation as it is irrelevant).

This function can work against a single value (e.g. `1` as in `Foo<1>`) or an union of values (e.g. `1 | 0` or `never` which is a *empty union*).
i.e. it can work against an *array*.

That's how the "like how `.map` over an empty array` you mentioned make sense.

**Comment by unional** [comment]
Let me try to redo that in a more TypeScript-like syntax,

still using `<a | b>` for union, and change the result to `a` and `b` for clarity:

```ts
type Foo<N> = N extends 0 ? 'a' : 'b';

type N = Foo<1 | 0>
       = <1 | 0> extends 0 ? 'a' : 'b'
       = <1 | 0>.map(x => x extends 0 ? 'a' : 'b')
       = <'b' | 'a'>
       = 'a' | 'b'

type N = Foo<1>
       = <1> extends 0 ? 'a' : 'b'
       = <1>.map(x => x extends 0 ? 'a' : 'b')
       = <2>
       = 2

type N = Foo<never>
       = never extends 0 ? 'a' : 'b'
       = <> extends 0 ? 'a' : 'b'
       = <>.map(x => x extends 0 ? 'a' : 'b')
       = <>
       = never
```

**Comment by fatcerberus** [comment]
Yeah, it’s called “distribution” but IMO that’s a misnomer - you should think of it more like `Array.prototype.map`: `[].map(x => y)` returns `[]` regardless of `y`.  It’s not a special case.

**Comment by unional** [comment]
> Yeah, it’s called “distribution” but IMO that’s a misnomer

It is not really a misnomer. It is correctly named. A single value equals a union of a single value.

Every type is a set (you can think of it as an array).

**Comment by fatcerberus** [comment]
So would you say that `Array#map` “distributes” a function over an array?  Because that’s what distributive conditional types do over type unions.  Feels like an abuse of terminology.

**Comment by unional** [comment]
> So would you say that Array#map “distributes” a function over an array?

Yep. That's what it means in category theory. AFAIK.
btw, I learn many of these from the excellent: https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/

**Comment by fatcerberus** [comment]
That's a good book, I page through it myself from time to time.  Anyway, we're getting off-topic and this isn't a bug, so the issue can probably be closed now.
