### ISSUE TITLE
Allow arithmetics on class/objects with valueOf method

### ISSUE THREAD

**Issue by Zorgatone** [Microsoft/TypeScript#5337]
Both of the two examples below won't work, and I get a compiler error/warning: "The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.".

Example 1 (defining method valueOf and implementing Number interface) working on runtime:

```typescript
class LOL implements Number {
	private _value: number;
	
	constructor(value) {
		this._value = value;
	}
	
	valueOf() {
		return this._value;
	}
	
	toFixed() {
		return Number.prototype.toFixed.call(this._value);
	}
	
	toExponential() {
		return Number.prototype.toExponential.call(this._value);
	}
	
	toPrecision() {
		return Number.prototype.toPrecision.call(this._value);
	}
}

type Lol = number | LOL;

let X: Lol = new LOL(10);
let Y: Lol = new LOL(7);

alert(X * Y);
```

Example 2 (extending Number "class") Runtime Error: "Uncaught TypeError: Number.prototype.valueOf is not generic"

```typescript
class LOL extends Number {
	constructor(value) {
		super(value);
	}
	
	valueOf() {
		return super.valueOf();
	}
	
	toFixed() {
		return super.toFixed();
	}
	
	toExponential() {
		return super.toExponential();
	}
	
	toPrecision() {
		return super.toPrecision();
	}
}

type Lol = number | LOL;

let X: Lol = new LOL(10);
let Y: Lol = new LOL(7);

alert(X * Y);
```

**Comment by Zorgatone** [comment]
I also tried this one (defining a variable with the Number interface), and got the same right-hand side error message:

```typescript
let X: Number = new LOL(10);
let Y: Number = new LOL(7);

alert(X * Y);
```

**Comment by Zorgatone** [comment]
I must define X,Y as any, which is not the best thing to do :disappointed:

**Comment by xLama** [comment]
This works on runtime but you can get a compiler error:

```
var x = new Number(10);
var y = new Number(20)

x * y 
```

I guess by design.

**Comment by Zorgatone** [comment]
@xLama yeah, of course. I was just experimenting with it, to see if there is a way to stop that compiler warning/error

**Comment by xLama** [comment]
@Zorgatone But I don´t know why fails because ES lets it. Maybe a Microsoft employee can explain us.   I think it should work to align with ECMA.

**Comment by Zorgatone** [comment]
It's just a warning from Typescript, but the generated code is correct and executes fine on runtime (first example only).

I know the second example will never work, it was a test

**Comment by RyanCavanaugh** [comment]
See #2361
