### ISSUE TITLE
TypeScript cannot auto-complete keyword `extends`

### ISSUE THREAD

**Issue by vikyd** [microsoft/TypeScript#53372]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2
- OS Version: macOS 13.1 (22C65)

Steps to Reproduce:

1. there is an interface `A`
2. want to create another interface `B` base on `A`
3. keyword `extends` not showing auto-complete

<img width="369" alt="extends" src="https://user-images.githubusercontent.com/2208880/226269663-2839f8cf-01cc-49d9-bd66-78de36595dac.png">

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
