### ISSUE TITLE
Control flow analysis does not recognise when an object is always defined if there is a type mismatch

### ISSUE THREAD

**Issue by eliasm307** [microsoft/TypeScript#53381]
# Bug Report

Typescript control flow normally narrows variables to be non falsy if they are always assigned e.g.
```ts
let somePossiblyUndefinedValue: Value | undefined;
if(!somePossiblyUndefinedValue) {
  somePossiblyUndefinedValue = someDefinitelyDefinedValue
}

// from here the type of somePossiblyUndefinedValue shouldnt include `undefined` as its always going to be defined
```

However this seems to break down if the type of `someDefinitelyDefinedValue` does not match the expected `Value` type, see examples [here](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictPropertyInitialization=false&noImplicitThis=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&noPropertyAccessFromIndexSignature=false&ts=4.9.5#code/C4TwDgpgBA8gRgKwgY2ANQIYBsCu0C8UA3gFBRQBmA9lQFxQDOwATgJYB2A5iQL4knIq7JlAAmEChwijMuCA3rwkqWXgDaAXSiFNJcciwZm0QcOBQwVBg1ZwsIAKrtxk9tIDKLDp3pM2XKAAfKBxnCSlRfgB6GNi4+ITEpOSU1MSSGLEqeXZzAHcqZgBrKDzWYAALKGAGAFoIAA9IVHrmZkKSUnIsCHMGKgBbCAAFKxs7RzDXaSUUdGw8RUQ51Whg0JcI-nJWCigACgBCfqHR61t7J023UVmVBYgASmIyckZBkbGLyeuZ5fu5NoXm83pkAAI1epNOatdrMKBqajwvIVDDACAANwg8OMGH67GqFVYDEYFSoOCwoigcGg2CwVDy0lK5TJOHMSOQ3kJxIs7UgzFA1XA0GAVGp0HYFMMdggGleIOodAsXwmV3CN08-m4IL45D4r0yxIYeCgFWx0B5GDg5PMlWgGIeyvOE3FXI26ukABooAaotS2VBylBkBhcuKQlMIt6g4IKVSaYToHl2gFQJB-eYg2UsFhw9dyhB7GIPZFyL8ZA8GAA6MA4BgVfYnT7Oy6Rm53eZyR68aJpPv9geDmIZP2ibIMMMFYrMyrVOqNZrAWGFKAOtih4CdV49PofM7jVvljurJbKTsm9Zt6TbYNCEQDYkDNHIM23f7ngjAt6K+gAVle+o7HsRxNvu3xqtMb5nqszxdKCfoQvO0ItNicIIkipSouiWI4hAeJCNyJL1uSlLht4hTSHKIKgSqh4lsejqEA+DBPsAL5-NBDwATehrWCaZrGIGJJWjaiaro6lgtiAroBO6kHer6GaBuYIZhgmclRspt5xuGdqlCmnBCumcABlmrA5nm6oFkW5avOWqzVrW9aNnutE-PR74wT2I5Dr5flDiOpSFEUJJlLOIZMN4W7dL07ynG5EERAxcinisjqXrZry7AcxyuVJiXtp5DywfKcXNge7mQclJqEHBIKZJQK4omimLYlAuL4oRpIkfGtI5gyTJhay7KFJyqZEiSYB8tigppiKYoJpKOZWj0pXkD+ToVQVHheAEeJQKGIClbqUCAcWkEOTWdYNjR+VXlBaVdt5-kva9KSBVOIUzlU7BCLUS1YLUeIMDNrBCNFUA7mVYGqvd1UQKlAIXhGmVATlt1bXDRVdl+5AY+BWOcYCtVrVADUYc12FtR1BGVDyxE6QmdIDVSQ2iRyXJ05N00CtJc3VAtEpSitECkxtkmY+WmreIcx3cXZJaXU5N15ZLHlE3g3b6m9Ou61EgUMBgQyNfCU2sA+wCsFi4lyCSEOmCI5bDGwFtWxADm+LtnCaECugxbu8V3U7LvlG7J6MF7QQoyWN7ZSBqsE8H5uh1iMG42TCGQguMKoR01EJ7DSeu6njFQP+eo3kXKfu5WV3Ofjhcls7yeWyXT18EAA)

I have recreated the issue using `ts-expect-error` however there are alternatives detailed in the examples of using non-null-assertions or casting, however these override the types and if the type issue is fixed in the future then the code will be confusing as the purpose of the type overrides would be unclear, `ts-expect-error` has the benefit that it prompts for its own clean up so it would be good if this worked like the alternatives.

The examples also highlight that the issue is regarding the assignment of the value when it is undefined, which is correctly raised as a type issue, however the subsequent type issues about the value being possibly undefined dont make sense and could be confusing noise for someone transitioning from JS where they can see the value is clearly always defined.

### 🔎 Search Terms

- ts-expect-error control flow 
- control flow not defined 

### 🕗 Version & Regression Information

 
- This is the behavior in every version I tried, and I reviewed the FAQ for entries aboutType System Behavior 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictPropertyInitialization=false&noImplicitThis=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&noPropertyAccessFromIndexSignature=false&ts=4.9.5#code/C4TwDgpgBA8gRgKwgY2ANQIYBsCu0C8UA3gFBRQBmA9lQFxQDOwATgJYB2A5iQL4knIq7JlAAmEChwijMuCA3rwkqWXgDaAXSiFNJcciwZm0QcOBQwVBg1ZwsIAKrtxk9tIDKLDp3pM2XKAAfKBxnCSlRfgB6GNi4+ITEpOSU1MSSGLEqeXZzAHcqZgBrKDzWYAALKGAGAFoIAA9IVHrmZkKSUnIsCHMGKgBbCAAFKxs7RzDXaSUUdGw8RUQ51Whg0JcI-nJWCigACgBCfqHR61t7J023UVmVBYgASmIyckZBkbGLyeuZ5fu5NoXm83pkAAI1epNOatdrMKBqajwvIVDDACAANwg8OMGH67GqFVYDEYFSoOCwoigcGg2CwVDy0lK5TJOHMSOQ3kJxIs7UgzFA1XA0GAVGp0HYFMMdggGleIOodAsXwmV3CN08-m4IL45D4r0yxIYeCgFWx0B5GDg5PMlWgGIeyvOE3FXI26ukABooAaotS2VBylBkBhcuKQlMIt6g4IKVSaYToHl2gFQJB-eYg2UsFhw9dyhB7GIPZFyL8ZA8GAA6MA4BgVfYnT7Oy6Rm53eZyR68aJpPv9geDmIZP2ibIMMMFYrMyrVOqNZrAWGFKAOtih4CdV49PofM7jVvljurJbKTsm9Zt6TbYNCEQDYkDNHIM23f7ngjAt6K+gAVle+o7HsRxNvu3xqtMb5nqszxdKCfoQvO0ItNicIIkipSouiWI4hAeJCNyJL1uSlLht4hTSHKIKgSqh4lsejqEA+DBPsAL5-NBDwATehrWCaZrGIGJJWjaiaro6lgtiAroBO6kHer6GaBuYIZhgmclRspt5xuGdqlCmnBCumcABlmrA5nm6oFkW5avOWqzVrW9aNnutE-PR74wT2I5Dr5flDiOpSFEUJJlLOIZMN4W7dL07ynG5EERAxcinisjqXrZry7AcxyuVJiXtp5DywfKcXNge7mQclJqEHBIKZJQK4omimLYlAuL4oRpIkfGtI5gyTJhay7KFJyqZEiSYB8tigppiKYoJpKOZWj0pXkD+ToVQVHheAEeJQKGIClbqUCAcWkEOTWdYNjR+VXlBaVdt5-kva9KSBVOIUzlU7BCLUS1YLUeIMDNrBCNFUA7mVYGqvd1UQKlAIXhGmVATlt1bXDRVdl+5AY+BWOcYCtVrVADUYc12FtR1BGVDyxE6QmdIDVSQ2iRyXJ05N00CtJc3VAtEpSitECkxtkmY+WmreIcx3cXZJaXU5N15ZLHlE3g3b6m9Ou61EgUMBgQyNfCU2sA+wCsFi4lyCSEOmCI5bDGwFtWxADm+LtnCaECugxbu8V3U7LvlG7J6MF7QQoyWN7ZSBqsE8H5uh1iMG42TCGQguMKoR01EJ7DSeu6njFQP+eo3kXKfu5WV3Ofjhcls7yeWyXT18EAA)

### 💻 Code

See playground link above

### 🙁 Actual behavior

```ts
type ObjectValue = {
  foo: string
}

const definedValues: ObjectValue[] = []
declare const possiblyUndefinedString: string | undefined

{
  let somePossiblyUndefinedObjectValue: ObjectValue | undefined

  if (!somePossiblyUndefinedObjectValue) {
    somePossiblyUndefinedObjectValue = {
      // @ts-expect-error [for whatever reason this should be allowed without forcing this property type to be nullable]
      foo: possiblyUndefinedString
    }
  }

  // ❌ the issue is here where the compiler says the value is possibly undefined, 
  // but it cant be undefined, it could be the wrong type but it will be definitely defined
  definedValues.push(somePossiblyUndefinedObjectValue)
}
```

### 🙂 Expected behavior

no type error for the code above

**Comment by fatcerberus** [comment]
If this worked, then the only way it generalizes is if the type is narrowed to `never`, since the only thing the compiler knows at this point is that the value doesn’t overlap with any of the members of the union.  Narrowing to `never` wouldn’t really be useful.

**Comment by eliasm307** [comment]
@RyanCavanaugh @fatcerberus thanks for the clarifications about the limitations, it looks confusing but its quite edge case behaviour with easy work arounds so I'll close this issue

**Comment by eliasm307** [comment]
@fatcerberus thanks for the further clarification.

It makes a lot of sense considering TypeScript uses structural typing so the type narrowing couldn't work if the structures the compiler is working with are different

It's just unfortunate it conflicts with how JS actually works here but as mentioned it's edge case behaviour and there are easy work arounds so it's minor

Thanks again for taking the time to explain things
