### ISSUE TITLE
ImageData's data isn't Uint8ClampedArray!

### ISSUE THREAD

**Issue by GoToLoop** [Microsoft/TypeScript#5338]
https://GitHub.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L11052
https://GitHub.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L12367

```ts
interface ImageData {
    data: number[]; // should be Uint8ClampedArray type here...
    height: number;
    width: number;
}
```

According to https://developer.Mozilla.org/en-US/docs/Web/API/ImageData/data
_data_ readonly property needs to be [_**Uint8ClampedArray**_](https://developer.Mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray), not some mere `number[]`.

**Comment by SaschaNaz** [comment]
#949 has said this a year ago but unfortunately haven't fixed yet :/

**Comment by mhegazy** [comment]
As @SaschaNaz mentioned. it is a duplicate.
