### ISSUE TITLE
Class generic extends class generic will not be evaluated even though the condition is always false

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#53390]
# Bug Report

### 🔎 Search Terms

conditional type narrow class generic

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230320#code/C4TwDgpgBAysD2AnCBRAdsRIoF4oG8AoKKASwBMAuKAZ01LQHNCBfQwgeg6gEEoAjAIY1SAYygAzAK5pRwUvDRQA7qWAALKIKjJgUxEtCQoGwcCjkIkNORpRFZYHYZgp5sIMSCAthGAREGgA6QmlZeQdGPwAeYih0TGwIAA9-Gzs4JFQMLAAaOJ5ERigUtNt4nJAAbQByChqAXSgAHwrE2vqGqqbWmUsJBghyXCg+iAG0IcIAPgAKOIoAeUQASVsAfmpC5gBKKC2iktSIdLasDvJGqHWz7Fa0KQAbR7jqACUIUSRyaLpEBkYuVu0wIJBIrHYYTkCkMEDo0QSWCOZQyCGQiJAcxOiTWNGoGIujW6eyIJC+aDoOjhT3MeCiwFm2KwuJ2AG44uSaPBHhAgo94IxZkYIPAJFSaDTagBGRpsqBcKCLADWEMIokewlRWQRlWRJ3KmXRlRBpKgrn4jzEUHpUui2z1pwJdUuPVuhK6rrGEyGIy9g3IcziJCWqw2B2YJD24Yd5SdnWutxaUAezyD+ygHy+iB+fwBQIxJrBUDibDi5st4n8dCljMquPxlXdxII7CLnPMyAlj1pJnUpGCNtrONsbLTCoJACIKBOPTG7JPp00bhikynHunM99fvQmPnja2wZzubz+YLhaLxZKajKGnKFbN+FJGHsPl3zP2zfAaCILdg1yWD3LK16QAJjtQ5Sn1edG2dK5WjjF1uiTP1JmGPAUKGQMixDXFNl4Io4ijfDikg05cyYBMV3uJ51wVD4wA1UQATdWCmlUDRaB3CMwXeT4t3IwFgVBMEALLKQLStKtgBAodmVsBt2lY5siDTdtL27EYNH7IJQNkkAWVZeVuE3bNt3+XdgQPMlFC5Hk+QFIVwBFMVOyvG8724ZVRJIIDKzhYAAGY9PrFjOmUtNhXsJURgQokmlI8oBMo3VqOeDc+NMgS90SaZ2SLBV4CVah8CgKpkmoASGgUrBS3y7geDSi8NGgfgIH5ZQoHJcg1BhOxVDSyYADcAgEaBfHMR932AGo7DQeBzC+bxXH8cgrJMJzRjQTtuWG8gpRimCwvi45HUbKdyBnZLElXGj0qzHMuOyrBcrHbgFwu2cEug9pzsu5cUuTW7ePusy80siKNpkbbHl2kCDsU+MvsTf7rtS9dgf4x7gTysFxzOxc52RxM0buzHzMEgs1siqG4R2oYAvh85jpRImqMBtKMcyrGCxxkg8faZmoNZgG11JrnyaezEALYIA)

### 💻 Code

```ts
type StoreEntry = {
  id: string
}

// A basic function with a return type that depends on its input parameters.
function get<
  Entry extends StoreEntry,
  Arg extends Entry['id'] | Entry['id'][] | undefined = undefined
>(
  idOrIds?: Arg
) : Arg extends Entry['id'] ? Entry | null
  : Record<string, Entry> {    
}

function test<Entry extends StoreEntry>(entryIds: Entry['id'][]) {
  const result = get(entryIds);
  console.log(typeof result['1']); // Ok
}

class Store<Entry extends StoreEntry> {
  public get1<Arg extends Entry['id'] | Entry['id'][] | undefined = undefined>(
    idOrIds?: Arg
  ) : Arg extends Entry['id'] ? Entry | null
    : Record<string, Entry> {    
  }

  public test1(entryIds: Entry['id'][]) {

    const result = this.get1(entryIds);
    // Entry["id"][] extends Entry["id"] ? Entry | null : Record<string, Entry>

    console.log(typeof result['1']); // (bug) Result is possibly null
  }

  public get2<Arg extends Entry['id'] | Entry['id'][] | undefined = undefined>(
    idOrIds?: Arg
  ) : Arg extends string ? Entry | null // Replacing Entry['id'] with string
    : Record<string, Entry> {    
  }

  public test2(entryIds: Entry['id'][]) {

    const result = this.get2(entryIds); // Record<string, Entry>

    console.log(typeof result['1']); // Ok
  }

  public test3(entryIds: Entry['id'][]) {
    type ok = Entry['id'][] extends string ? Entry | null : Record<string, Entry>;
    // ok: { [x: string]: Entry}

    // All of the below conditions will never be met but it's not computed

    type unresolved1 = Entry['id'][] extends Entry["id"] ? Entry | null : Record<string, Entry>;
    // Entry["id"][] extends Entry["id"] ? Entry | null : Record<string, Entry>

    type unresolved2 = Entry['id'] extends Entry ? Entry | null : Record<string, Entry>;
    // Entry["id"] extends Entry ? Entry | null : Record<string, Entry>

    type unresolved3 = Entry[] extends Entry ? Entry | null : Record<string, Entry>;
    // Entry[] extends Entry ? Entry | null : Record<string, Entry>
  }
}
```

### 🙁 Actual behavior

A conditional type that compares a class generic against a class generic will not be resolved, even though the condition is false no matter what the value of the generic is.

### 🙂 Expected behavior

The conditional should be properly resolved since whatever  `Entry['id']` is, there is no scenario where `Entry['id'][]` would extend `Entry['id']` which must be `string`. I cannot define a type that extends `StoreEntry` where the `id` property would be anything but a `string`. The conditional should be resolved as false in each case.

**Comment by mckravchyk** [comment]
@MartinJohns 

The previous issue occurred in functions, this one only occurs in classes. If it's the same design limitation - why does this work in functions?

**Comment by RyanCavanaugh** [comment]
> The conditional should be properly resolved since whatever Entry['id'] is, there is no scenario where Entry['id'][] would extend Entry['id'] which must be string.

In general, it's wrong, extremely difficult, or impossible to prove that for a given `T`, a type constrained to `U` cannot possibly extend it. Trivially, `T & U` by definition does, and whether or not `T & U` is necessarily `never` involves a lot of counterfactual reasoning that can generally be pushed upstream into "You shouldn't have written the type that way".

**Comment by mckravchyk** [comment]
Alright, thanks. I did not encounter the issue for anything else and in this scenario it's not a problem since the type is already constrained earlier by the extends keyword.
