### ISSUE TITLE
union type is not supported inside function

### ISSUE THREAD

**Issue by tonychunxizhu** [microsoft/TypeScript#53393]
# Bug Report

the union type doesn't work inside a function

### 🔎 Search Terms
union type

### 🕗 Version & Regression Information
TSC 5.0.2

This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/G4QwTgBAHhBcEDsCuBbARgU0gHwgZwBcwBLBAcwG4AoGAXggCIQ0BjB6uiAFgEYOJ6MANQQ+EcRMmSA9NMQB7CFjDywVFvIR55AGwwA6HfLIQAFFACU1KrIgg8EAA7gQKDASxUAZkgQsCxJoQXmYAnnCIqJg4+ESkJhYRwPLEACYQAN5UkuH04SJiUjJyyqoQACoAygBMAMwAbACs8ADyjlggBGUA5ELdECwgCAjyBBCYdo6OOsQY6V0QBKHtDt2EJOQQuMjoWP1D6d070d362RIaWroGRiamoVZUAL5Ur16mTKwMj++8j0A)

### 💻 Code

```
var x : number | string;
x = "abc";
x = 41;
x = x + 1;              // no error
console.log (x);

// as parameter
function f (y : number | string ) : void {
    y = y + 1;          // error TS2365: Operator '+' cannot be applied to types 'string | number' and 'number'.
    console.log (y);
}


f("abc");
f(41);
```

### 🙁 Actual behavior
the behavior of union type is inconsistent.
There are no errors for the normal assignment, but when the variables are  parameters of functions

**Comment by MartinJohns** [comment]
> the behavior of union type is inconsistent.

I don't see any inconsistent behaviour. If you assign a `string` or a `number` to your variable `y` within the function it won't report an error. Same, if you remove the assignment outside the function, you will get an error here as well.

**Comment by tonychunxizhu** [comment]
> > the behavior of union type is inconsistent.
> 
> I don't see any inconsistent behaviour. If you assign a `string` or a `number` to your variable `y` within the function it won't report an error. Same, if you remove the assignment outside the function, you will get an error here as well.

Hi @MartinJohns, thanks for your quick reply. I tested it and you are right.
Then what should the type of ```y```  be in function ```f``` , ```any```?

**Comment by whzx5byb** [comment]
FYI: https://dev.to/macsikora/this-is-why-typescript-restricts-operator-i0f
