### ISSUE TITLE
jsx, checkJs, and possibly more options must be tracked as affectsSemanticDiagnostics

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#53391]
Someone on Twitter mentioned that updating the `jsx` option in their editor was not updating their errors.

https://twitter.com/cromas/status/1636995012482453505

I looked into this and noticed that both `--jsx` and `--checkJs` are not tracked as `affectsSemanticDiagnostics`.

https://github.com/microsoft/TypeScript/blob/3fab5fff347fb7192bdf182668f513eb59e48024/src/compiler/commandLineParser.ts#L651-L671

In fact, I wonder if `checkJs` also needs the same options as `allowJs` (i.e. `affectsModuleResolution: true`) since one turns the other on implicitly.

https://github.com/microsoft/TypeScript/blob/3fab5fff347fb7192bdf182668f513eb59e48024/src/compiler/commandLineParser.ts#L642-L650

**Comment by jakebailey** [comment]
Per https://github.com/microsoft/TypeScript/pull/53403#discussion_r1187783681 I can't actually seem to reproduce the `jsx` issue.

`checkJs`, maybe.
