### ISSUE TITLE
Comparability/type assertion failure when using enums and underlying literals

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#53400]
The regression reported [here](https://github.com/microsoft/TypeScript/issues/53359#issuecomment-1475390601) can be traced back to #53192. The minimal~ repro case for it is this:
```ts
enum AutomationMode {
  NONE = "",
  TIME = "time",
  SYSTEM = "system",
  LOCATION = "location",
}

interface ThemePreset {
  id: string;
}

interface Automation {
  mode: AutomationMode;
}

interface UserSettings {
  presets: ThemePreset[];
  automation: Automation;
}

interface ExtensionData {
  settings: UserSettings;
}

export function getMockData(): ExtensionData {
  return {
    settings: {
      presets: [],
      automation: {
        mode: "",
      },
    } as UserSettings,
  }
}
```

[TS playground](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230320#code/KYOwrgtgBAgmAuB7CBDeBLRICyiAmwUA3gFBRQByA8hQKJQC8UARMwDRlQAqAktvU2YYIwdpwDKATXFda2RiwDOAT0XxgEMeQAyVAMIxeNBcwA2iAMZpMIMQF8SJdCHUAnAGYoLhLgAsNwAAKrsCKwPDEnOh4AFxQaq7OAOYA3CQOTi7AHl6EcEioGFiR5BD4wHH5yNZYuARpGc5unt5QAKphruLhGCBJiiVQAA4hYfCKcX4BwaHhANoAumnkKAjVRSCVa4U2DY5N2S2EtAAe6iCKNgAiaCiDY739cR3Z3fCPinskwCdDiK4RdxgEAWDZQJLhXAWADWN3gKAAFABKOKnc6XLBwu6kcgheBgVwgQbkB7JCbE8jDUbhcmLDiUymrAo1TYUhllAhxVj0hlQOw88h2KAoAYvLo9Mk8hwOIA)

_Originally posted by @Andarist in https://github.com/microsoft/TypeScript/issues/53192#issuecomment-1476171453_

**Comment by fatcerberus** [comment]
Isn't it intentional that string literals are not assignable to string-based enums, even if they match one of the enum members?

**Comment by Andarist** [comment]
It's about comparability and it seems that this type of conversion is valid in such a context, for example, this is OK:
```ts
const foo = "" as AutomationMode
```

**Comment by fatcerberus** [comment]
Ah, I missed the type assertion `as UserSettings` so it just looked like an assignability failure, which was expected.

**Comment by ahejlsberg** [comment]
The fix here is to exclude the comparable relation from the optimization in #53192. I will put up a PR.
