### ISSUE TITLE
Method expression can be null or undefined 

### ISSUE THREAD

**Issue by Mamorial** [microsoft/TypeScript#53404]
# Bug Report
typescript: 5.0.2
description: in vue3 project, use auto-imports.d.ts export function, typescript tip "Method expression can be null or undefined "
![image](https://user-images.githubusercontent.com/26594629/226506167-82e51036-76ce-4664-ae3a-65018eb9231d.png)

### 💻 Code

```ts
// setup
const route = useRoute();
const router = useRouter();

// auto-import.d.ts
const useRouter: typeof import('vue-router')['useRouter']

// ts infer
export const useRouter: (() => [Router](https://github.com/microsoft/TypeScript/issues/psi_element://Router)) | undefined
```

### 🙁 Actual behavior

infer error: `Method expression can be null or undefined `

### 🙂 Expected behavior

infer error: ''

**Comment by jakebailey** [comment]
"Method expression can be null or undefined" is not a message that TypeScript produces; this seems like a WebStorm problem judging by the screenshot.

**Comment by fatcerberus** [comment]
On the other hand,

> Cannot invoke an object which is possibly 'undefined'.

*is* an error that TypeScript produces, given a call `foo()` where `foo` is typed as `(() => T) | undefined` (like in the screenshot)

**Comment by jakebailey** [comment]
Right; I'm assuming that `auto-imports.d.ts` is something provided by WebStorm, but maybe it's something specific to vue, in which case if it exists, the types are wrong, otherwise, the error should be handled in the code.

**Comment by rmd1710714107** [comment]
> # Bug Report
> typescript: 5.0.2 description: in vue3 project, use auto-imports.d.ts export function, typescript tip "Method expression can be null or undefined " ![image](https://user-images.githubusercontent.com/26594629/226506167-82e51036-76ce-4664-ae3a-65018eb9231d.png)
> 
> ### 💻 Code
> ```ts
> // setup
> const route = useRoute();
> const router = useRouter();
> 
> // auto-import.d.ts
> const useRouter: typeof import('vue-router')['useRouter']
> 
> // ts infer
> export const useRouter: (() => [Router](https://github.com/microsoft/TypeScript/issues/psi_element://Router)) | undefined
> ```
> 
> ### 🙁 Actual behavior
> infer error: `Method expression can be null or undefined `
> 
> ### 🙂 Expected behavior
> infer error: ''

i have the same problem, have u solved it?

**Comment by rmd1710714107** [comment]
> > # Bug Report
> > typescript: 5.0.2 description: in vue3 project, use auto-imports.d.ts export function, typescript tip "Method expression can be null or undefined " ![image](https://user-images.githubusercontent.com/26594629/226506167-82e51036-76ce-4664-ae3a-65018eb9231d.png)
> > ### 💻 Code
> > ```ts
> > // setup
> > const route = useRoute();
> > const router = useRouter();
> > 
> > // auto-import.d.ts
> > const useRouter: typeof import('vue-router')['useRouter']
> > 
> > // ts infer
> > export const useRouter: (() => [Router](https://github.com/microsoft/TypeScript/issues/psi_element://Router)) | undefined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 🙁 Actual behavior
> > infer error: `Method expression can be null or undefined `
> > ### 🙂 Expected behavior
> > infer error: ''
> 
> i have the same problem, have u solved it?

i solve it when i use "typescript": "4.9.5"
