### ISSUE TITLE
5.0.2 `T extends GenericType<infer InferredType>` no longer resolves as true

### ISSUE THREAD

**Issue by markglattback** [microsoft/TypeScript#53415]
# Bug Report

In previous versions of TypeScript (including 5.0.0-beta), when working with Vue, component prop types could be inferred using the following `ExtractProps` type where `T` is a Vue component:

```ts
import type { ComponentOptions } from 'vue'

type ExtractProps<T> = T extends ComponentOptions<infer Props> ? Props : never
```

The returned type is now `never`.

### 🔎 Search Terms

infer, generic

### 🕗 Version & Regression Information

5.0.0-rc

- This changed between versions 5.0.0-beta and 5.0.0-rc

### 💻 Code

```ts
import type { ComponentOptions } from 'vue'
import MyComponent from './MyComponent.vue'

type ExtractProps<T> = T extends ComponentOptions<infer Props> ? Props : never

type MyComponentProps = ExtractProps<typeof MyComponent> // never (but correctly returned Props in earlier versions of TS)
```

### ⏯ Playground Link

[Working (4.9.5)](https://www.typescriptlang.org/play?ts=4.9.5#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGELgQ5bwC+c6UBcA5AG4CuqNAUKJLHDAJ5iqJx8hYjADyYGMCIBnOOUrV6TViwDGM+AFluQyCLgBeFBmx4Ce1CQAUCFnDhgqYaQC5Ed+3CwBDEKje2np48fG4AyjBQ2ADmADQeQVCoAI4MwEnIbpFMCXLxQd7R-u5B9iHFAHIMIABGqFD5nqQepI0wqOAANt7tbgAGABKonZ0QcADq0J3IfSykAJQsLOVwAKIAHpHeqjAACk7SADwAKgB8hnDHcKiblsiyukSWYhJSWEfY6PVw+xDO5wB+H4HOBuHB0epLFbaR4iX7OC4bLY7eFHcoQdBwGHmJ4kU5AA)

[Broken (5.0.2)](https://www.typescriptlang.org/play?ts=5.0.2#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGELgQ5bwC+c6UBcA5AG4CuqNAUKJLHDAJ5iqJx8hYjADyYGMCIBnOOUrV6TViwDGM+AFluQyCLgBeFBmx4Ce1CQAUCFnDhgqYaQC5Ed+3CwBDEKje2np48fG4AyjBQ2ADmADQeQVCoAI4MwEnIbpFMCXLxQd7R-u5B9iHFAHIMIABGqFD5nqQepI0wqOAANt7tbgAGABKonZ0QcADq0J3IfSykAJQsLOVwAKIAHpHeqjAACk7SADwAKgB8hnDHcKiblsiyukSWYhJSWEfY6PVw+xDO5wB+H4HOBuHB0epLFbaR4iX7OC4bLY7eFHcoQdBwGHmJ4kU5AA)

### 🙁 Actual behavior

`MyComponentProps` is `never`

### 🙂 Expected behavior

`MyComponentProps` should be the inferred `Props` type

**Comment by RyanCavanaugh** [comment]
We'd need a self-contained repro (i.e. 3-50 lines, none of which import the entirety of Vue) in order to determine if this is an intentional change or not.

**Comment by kasperpeulen** [comment]
@markglattback Why did you close this? I'm investigating this as well, this broke TS support for Vue in storybook.

**Comment by markglattback** [comment]
@kasperpeulen whilst the old approach was no longer working with TS 5.0.x, the following has helped:

I stumbled across a [comment](https://github.com/vuejs/language-tools/issues/2589#issuecomment-1510992428) from the author of Volar recommending `vue-component-type-helpers` to extract component types. IFound that in our project it was dependent on having a `d.ts` file containing component types but otherwise works very well. In our case our `d.ts` file is generated by the `unplugin-vue-components` plugin.

We're also using Storybook 7 and have no issues with type inference using `Meta<typeof MyComponent>` or `Story<typeof MyComponent`>.

**Comment by kasperpeulen** [comment]
@markglattback Thanks for that! That is really useful.

I opened a PR in storybook to use those type helpers:
https://github.com/storybookjs/storybook/pull/22814

Weird that you don't have issues, we have multiple users report that it breaks with TS 5.0.
