### ISSUE TITLE
Trying to get the type of a generic method of a class results in a parse error

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#53410]
# Bug Report

### 🔎 Search Terms

get type of a generic class method  parse error

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about it.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230321#code/MYGwhgzhAEBiD29oG8BQ0PQA4FcBGIAlsNHmAE4A8AKtAKYAeALnQHYAmMET5hrA5gD4AFBX4AuaNQCUk2mnSYAvqhWomATyx1oAM2padAXjiIA2gHIy5CwF1KFltwuDoAejfQA3PQbbgLOxAA)

### 💻 Code

```ts
class Foo {
    public bar<T extends string>(arg: T): T {

    }
}

type fType = Foo['bar']<'test'> // ; expected

```

### 🙁 Actual behavior

I'm not able to get the type of a generic method in a class. It results in a parse error.

### 🙂 Expected behavior

Getting type of a generic method of a class should be possible.

### Additional information

I need this to get the return type of a generic function from within to cast the return result (a workaround to to the bug with generic conditionals not resolving in certain cases).

It's not possible to just create a separate type to hold a reference to the method type because that type is not going to be a generic, and if you try to make a generic type out of it, it will result in the same problem. I'm not aware of any workarounds.

**Comment by mckravchyk** [comment]
The T generic of the method.

**Comment by MartinJohns** [comment]
I don't know what you mean by "a more narrow subtype". At that point there is no more narrow subtype. The function is generic, the type is provided at call site, there's no concrete type available.

**Comment by mckravchyk** [comment]
My real world case is that the generic extends `{ id: string }` so the actual generic can have more properties defined in the shape, i.e. `{ id: string, title: string}` In that case, doing `ReturnType<Foo['bar']>` would default the generic to `{ id: string }` but I need to be able to pass the generic in that return type so I can get `{ id: string, title: string}`  for instance. It's more complex than that too, the return type is a conditional that depends on the input generic, generic type narrowing does not work fully, so I need to cast the return type as precisely the return type of the method with the generic argument that was passed so I can bypass the error with casting.

The core issue here is that it's not possible to get the full type of a class method (as a generic).

**Comment by MartinJohns** [comment]
> The core issue here is that it's not possible to get the full type of a class method (as a generic).

It's not possible because **there is no type** to get. You can't know what what type is provided somewhere else at call site. It may be type A, it may be type B, it may be type C.

**Comment by MartinJohns** [comment]
@jcalz Makes it clear what he actually (probably) wanted and what the meaning of the `<"test">` was.

**Comment by fatcerberus** [comment]
Good catch, @jcalz - I knew it was an attempt at an instantiation expression, but I admit I also thought it was a bug that it didn’t work.  See, what’s frustrating is that you *can* do…

```ts
type Fun<T> = (x: T) => T;
type StringFun = Fun<string>;  // (x: string) => string
```

…and that makes perfect sense, so it does ultimately seem natural to expect this kind of thing to work.  It’s that pesky subtle distinction between “generic function type” and “concrete function type with generic type parameters” that gets in the way.

**Comment by whzx5byb** [comment]
It is possible to access a method type from `prototype`, so `type fType = typeof Foo.prototype.bar<string>` will work for you.

**Comment by mckravchyk** [comment]
Thanks, much appreciated. Yes, that was a little confusing, especially since I thought that in the example `type x = Foo['bar']` would be a regular type. @whzx5byb 's  solution is perfect.

**Comment by fatcerberus** [comment]
@mckravchyk Yeah, there’s a confusing distinction here in that `type Foo<T> = () => T` is a generic type that evaluates to a concrete, non-generic function type (i.e. it’s a type function), while `type Foo = <T>() => T` is the concrete, non-generic type of a generic function.  `Foo['bar']` gives you the latter, so you can’t pass type parameters to it.
