### ISSUE TITLE
Is there an option for "optional module export"?

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#5341]
TypeScript has these lines to do it:

https://github.com/Microsoft/TypeScript/blob/8864b06cbf5d19c3c54dcac7e319a10da30b8161/src/services/shims.ts#L1091
```typescript
// Here we expose the TypeScript services as an external module
// so that it may be consumed easily like a node module.
declare var module: any;
if (typeof module !== "undefined" && module.exports) {
    module.exports = ts;
}
```
https://github.com/Microsoft/TypeScript/blob/2c7c5bcab767f94c7cb7b4d0bd21b5789a544493/Jakefile.js#L448
```typescript
// Official node package definition file, pointed to by 'typings' in package.json
// Created by appending 'export = ts;' at the end of the standalone file to turn it into an external module
var nodeDefinitionsFileContents = definitionFileContents + "\r\nexport = ts;";
fs.writeFileSync(nodeDefinitionsFile, nodeDefinitionsFileContents);
```

... but currently `module: "commonjs"` does not check existence of `module` variable, which causes error when injected as a normal script on browsers. Is there any way to do this optional module export (without these extra lines)?

**Comment by mhegazy** [comment]
TypeScript, just as ES6, modules do not allow conditional module exports. if you want to do that you need to have knowledge of the loader, this is why we have the `typeof module !== "undefined"` check.

**Comment by mhegazy** [comment]
so short answer is no, there is no way to do that using module export syntax.

**Comment by SaschaNaz** [comment]
@mhegazy I don't want "if (an arbitrary expression) then export something" but I do want "if module loader exists then export something, else just go with no error". I'm not sure that ES6 export syntax break when the script injected directly without module import.

**Comment by mhegazy** [comment]
> "if module loader exists then export something, else just go with no error".

this is the problem. an external module assumes a loader. be it commonJS, AMD, system.. etc.. a loader has to exist. the typescript code we have is rather a hack. 

> I'm not sure whether ES6 export syntax breaks when the script injected directly without module import, but if it does then I think the current behavior makes sense.

ES6 has modules as a native feature, so the module loader is *assumed* to always exist as well. to do what you explain, you need to use the loader API directly to do this conditional importing/exporting. 

So let me ask how would you see this happening without the if condition? like what would you export from your "module" if loaded as a script? have you considered implementing `require` if it is not defined?

**Comment by SaschaNaz** [comment]
>so the module loader is assumed to always exist as well.

This is right, but what should occur in this case? Does ES6 spec says this should break or not? (Suppose that the browser already supports ES6 module system)

```html
<script>
function foo() {}
export { foo }
// Here I can think this line won't really export anything
// as it is not in <module> element
// but will it break with an error message or just be silent?
</script>
```

>what would you export from your "module" if loaded as a script? 

I would not export anything. I hope my code work as external module when in module environment and work as non-module script when in normal ES5/ES6 script element.

**Comment by mhegazy** [comment]
i think this would be an error. @bterlson can comment.

**Comment by bterlson** [comment]
Yes it's a syntax error. Modules and scripts have different top level grammars, and import/export statements are only syntactically valid in modules.

**Comment by SaschaNaz** [comment]
We have to keep using the d.ts post-modification then. Thank you for your answers :+1:

Still I hope there be some easier way as many libraries are already doing this. No post-modification is needed for them as their DefinitelyTyped declaration files are written by hand, anyway...
