### ISSUE TITLE
[5.0] Intersected array of intersection types with union field not compatible

### ISSUE THREAD

**Issue by intgr** [microsoft/TypeScript#53412]
# Bug Report

Basically I'm using `&` types as if subclassing. `BaseValue` has `items` array with fewer properties, `ExtendedValue` extends that with `items` with more properties.

### 🔎 Search Terms

intersection, ampersand, override, inheritance. Also looked at the titles of first 2 pages of open issues.

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0.2
- There is an easy work-around, but I'm not sure if it should be necessary.

### ⏯ Playground Link

[TypeScript 5.0.2 (error)](https://www.typescriptlang.org/play?ts=5.0.2#code/C4TwDgpgBAQghgZwgSWBAtlAvFA3gWACgooBLAEwC4oA7AV3QCMIAnAbiIF8jRIoBRAB5oa5COVQZssRCjSYAZHiIkxCAMYtSYYKQD2NagmBaaAcygAfWnQA2trh0JEe4aPCQA1OLbrQcBMRQAPTBUMAAFqzQcCzQepGsUABmpBC25AgqZPII1B5yGADaALpO3IS80EIiYuTevv4yXj5+UEqBJKHhUXFQsfGJLClpGVlBpLnUNRCi4pLopeUuzoTqBsZQACr8AMpbAPqeAIIAMgCq-NPCs3UNbQHZkxh5UEVdYVsRpAhkvwByAHktv17HoAO7iKAAKlIyWS0Kg6FIgihVV+AygdCQ5DINCgAAM1JptLoDATsiRcBRqABGAA0UGJWh0+kMNnsnHplLwNKgACZGczSWzqABycGkMxmWwgYB0RiMWwQMVc7IlRwrbowOjAMjJQnC1nkqARRBYmhwvQsTDoxmJfGTP5QQEAaUoRHWNE2gP+pwAmgd9gAlZD-ADiu2utXE9yanRyL2oRR51KoUAZTIgGhZZPZYsYensIHBemlytV3KCVL5gqzOZFBnFkvLcoVSpVaqCGsInCcXp9fsD-3Op1OUYENzm9Va8aeUzeqb5maNeeo9E5VZINfTddXoo5ti7JB7faIQA) vs [4.9.5 (OK)](https://www.typescriptlang.org/play?ts=4.9.5#code/C4TwDgpgBAQghgZwgSWBAtlAvFA3gWACgooBLAEwC4oA7AV3QCMIAnAbiIF8jRIoBRAB5oa5COVQZssRCjSYAZHiIkxCAMYtSYYKQD2NagmBaaAcygAfWnQA2trh0JEe4aPCQA1OLbrQcBMRQAPTBUMAAFqzQcCzQepGsUABmpBC25AgqZPII1B5yGADaALpO3IS80EIiYuTevv4yXj5+UEqBJKHhUXFQsfGJLClpGVlBpLnUNRCi4pLopeUuzoTqBsZQACr8AMpbAPqeAIIAMgCq-NPCs3UNbQHZkxh5UEVdYVsRpAhkvwByAHktv17HoAO7iKAAKlIyWS0Kg6FIgihVV+AygdCQ5DINCgAAM1JptLoDATsiRcBRqABGAA0UGJWh0+kMNnsnHplLwNKgACZGczSWzqABycGkMxmWwgYB0RiMWwQMVc7IlRwrbowOjAMjJQnC1nkqARRBYmhwvQsTDoxmJfGTP5QQEAaUoRHWNE2gP+pwAmgd9gAlZD-ADiu2utXE9yanRyL2oRR51KoUAZTIgGhZZPZYsYensIHBemlytV3KCVL5gqzOZFBnFkvLcoVSpVaqCGsInCcXp9fsD-3Op1OUYENzm9Va8aeUzeqb5maNeeo9E5VZINfTddXoo5ti7JB7faIQA)

### 💻 Code

```ts repro
type BaseItem = {
  id: number;
}
type ExtendedItem = BaseItem & {
  description: string | null
};


type BaseValue = {
  // there are other fields
  items: BaseItem[];
}
type ExtendedValue = BaseValue & {
  // there are other fields
  items: ExtendedItem[];
}


const TEST_VALUE: ExtendedValue = {
  items: [  // ❌ ERROR: This is NOT allowed *iff* mixed types are used in `description`
    {id: 1, description: null},
    {id: 2, description: 'wigglytubble'},
  ]
};
```

### 🙁 Actual behavior

Seems to me like they should be compatible. Also these examples are ✅ allowed in TS 5.0.2 if `description` only has uniform types, e.g.:

```ts
// ✅ Allowed: description has only strings
const ONLY_STRINGS: ExtendedValue = {
  items: [
    {id: 1, description: 'bollywoggle'},
    {id: 2, description: 'wigglytubble'},
  ]
};
// ✅ Allowed: description has only nulls
const ONLY_NULLS: ExtendedValue = {
  items: [
    {id: 1, description: null},
    {id: 2, description: null},
  ]
};
```

### 🙂 Expected behavior

Seems like it should be allowed.

### 🙄 Work-around

Typing `ExtendedValue` with `Omit<>` seems to fix the issue with no obvious downsides.

```ts
type ExtendedValue = Omit<BaseValue, 'items'> & {
  // there are other fields
  items: ExtendedItem[];
}
```

**Comment by RyanCavanaugh** [comment]
#52392

**Comment by ahejlsberg** [comment]
This issue looks to be caused by incomplete propagation of the `intersectionState` parameter in our type relation logic. I have a fix that I'll put up shortly.
