### ISSUE TITLE
Incorrect handling of template literals + intersections

### ISSUE THREAD

**Issue by jakebailey** [microsoft/TypeScript#53427]
# Bug Report

### 🔎 Search Terms

intersection template literals

### 🕗 Version & Regression Information

- This changed between versions 5.0 and nightly

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230321#code/C4TwDgpgBAsghiARhAwnYUC8UAGBjAEgG8BnYAJwEsA7AcwF8coAyXYsqu+4HAbgChQkWAmQBlPOhJZcJYvCSp09En378AJhDwAbOOWgA3fVAAeALhGKJUgf1MyARCUnASj3lAD0XqCQAWAPYArjoaUMhQAPIA0vZOLnDunj5+QaHhEOTkgeRAA)

### 💻 Code

```ts
type MaybeCat = `c${string}` & `${string}t`;
type MaybeScats = `s${MaybeCat}s`;

declare var x: MaybeScats;

x = "scats"; // should be OK
x = "scas"; // should error
```

### 🙁 Actual behavior

In 5.0, neither error, even though the second one should.

In nightly, after #52836, both error.

### 🙂 Expected behavior

First one is okay, second is an error.

Noted in: https://github.com/microsoft/TypeScript/pull/53406#pullrequestreview-1351197189

Unsure if this is a regression per-se; neither behavior is really right, I just managed to change it and expose what I believe is a new bug to do with how we handle template literals.

**Comment by ahejlsberg** [comment]
Fixed by #54188.
