### ISSUE TITLE
`if ('A' in el) {}` causes code below to error

### ISSUE THREAD

**Issue by ben-clayton** [microsoft/TypeScript#53425]
# Bug Report

### 🔎 Search Terms

`narrowing in if`
`Argument of type 'unknown'`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230321#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQEE4BvAKDjkyigC5S5D6kBXAWwCM0BuOAXwDaAXW5k+ZMqEixEKNFlwFCAIVIUqNeiUbN2XKL2W7OPfsNHjJ4aPHQsk2GAghI4AMQAUIekTgAfJWUASjVKbBcAZ3gWCOBVAF44DxhjfRD4gD5SPlFKdGgk8KQouGAAGzgIdDgQADpqKBDySkoEao8AckIO2VKypr44AHohuHC2NmAUSpZ4GAALBAi4MuQ8GAg4NkwAazwOmLiPctrgnvGwBDK8AHcEBYhZ0ppodVb2juUe5D6mt5aRnAAOrzKZwDptJJdb6ucoDHqYDgQABueCWcCQEHg40mKFQABMZjAADRwBZ4VZIPBcMoQG5wO5lCpoKAFO4LWj-SiAlkFeiEKAAc3YU3gVTJAE8wPt7DtMTckN9lpj4JgIhEEIKkIjrmTNmBqJhJqgoJVqjApftWCYoB1ah4AEwAZgALABWIJcuCHZTHMqnIK8Fpwf7iSjiPhAA)

### 💻 Code

```ts
export interface IA {
  arr: { A: number; }[];
}

export interface IAB {
  arr: { A: number; B: number; }[];
}

export function F(x: IA | IAB) {
  const useB = (t: number) => {};
  for (const el of x.arr) {
    if ('A' in el) {} // comment out this line to make 'useB(el.B)' compile without error
    if ('B' in el) {
      // When 'if ('A' in el) {}' above is not commentted out, the line below will error with:
      // error : Argument of type 'unknown' is not assignable to parameter of type 'number'.(2345)
      useB(el.B);     
    }
  }
}
```

### 🙁 Actual behavior

```
useB(el.B);
     ^^^^
error : Argument of type 'unknown' is not assignable to parameter of type 'number'.(2345)
```

The above error is raised if the line `if ('A' in el) {}` is **not** commented out.
Commenting out `if ('A' in el) {}` compiles without error.

### 🙂 Expected behavior

That the line `if ('A' in el) {}` does not narrow the type of `el` in a way that prevents code outside of the `if` from compiling.

**Comment by ben-clayton** [comment]
A slightly further reduced case:

```ts
export interface I {
  arr: 
     | { A: number; }[] 
     | { A: number; B: number; }[];
}

export function F(i: I) {
  const useB = (n: number) => {};
  for (const el of i.arr) {
    if ('A' in el) {} // comment out this line to make 'useB(el.B)' compile without error
    if ('B' in el) {
      // When 'if ('A' in el) {}' above is not commentted out, the line below will error with:
      // error : Argument of type 'unknown' is not assignable to parameter of type 'number'.(2345)
      useB(el.B);     
    }
  }
}
```

**Comment by fatcerberus** [comment]
This looks like a symptom of subtype reduction.  At some point (probably after CFA recombines the types at the edge of the first `if` block) `IA | IAB` gets subtype-reduced to just `IA`, leaving `B` to be re-manufactured from whole cloth… as `unknown`

In the past subtype reduction issues like this have been considered unfortunate, but ultimately intended behavior.

**Comment by fatcerberus** [comment]
@ahejlsberg Huh, this is the first time I’m hearing about a hard rule for when subtype reduction is allowed to happen.  Ryan usually just handwaves it as, subtype reduction can happen any time, so don’t depend on it not happening.

**Comment by ahejlsberg** [comment]
@fatcerberus As a rule, subtype reduction can happen any time, but since it is costly (worst case quadratic) we labor hard to avoid it when possible. The "foreign" type detection in CFA is an example of that.

**Comment by fatcerberus** [comment]
> … difference between `IA` and `IA | IAB`. Ideally you wouldn't be able to observe a difference between the two …

I agree in principle, though my suspicion is that so long as 1. users can write the latter without it being immediately reduced, and 2. unions can be narrowed, the difference will always be observable—and thus users will keep writing the latter because being able to narrow to a subtype using idiomatic (if admittedly unsound) syntax is indeed useful.

**Comment by ben-clayton** [comment]
Thank you ever so much for the impressively fast fix for this!

**Comment by fatcerberus** [comment]
@ben-clayton Just be aware that the original error is *technically* correct according to the rules of the type system (which is what Anders is getting at above when he says that `IA` and `IA | IAB` are equivalent): `{ A: number, B: string }` is assignable to `IA`.  Depending on who’s calling `F`, that might be a footgun you need to watch out for.  (in general this pitfall is unavoidable without #12936, sadly)
