### ISSUE TITLE
Suggestion: compiler flag to prevent functions returning non-`void` being assigned to functions returning `void`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#53421]
# Suggestion

## 🔍 Search Terms

- `void`
- `match`
- function return type
- `IO` type
- `Lazy`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A compiler flag to prevent [functions returning non-`void` being assigned to functions returning `void`](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void).

## 📃 Motivating Example

[Playground](https://www.typescriptlang.org/play?jsx=0#code/C4TwDgpgBAMghgLxAHgIID4oF4oAoCU2mqA3AFBkAmEAxgDZwBO0NA9gHYDOwUb7lAS2ACOALigAjVqzoQ47cmT7coAWzjAaAC2xkoUNOlwAPcQSJRUAGiggzhLMXzj4SQ0T14H6T-r6DhDigAfihjc3EQAkVlHjpWAHNdfVxVTgTxbkYBdgTnWEQUADdWAUpMR09zSv0-Dk4ZCAA6eITU9PxFAHouqEAZcigAFS0BTihRqDgoMEZExjhVVQhGKGXZxialep4AM3YARmw1DW1cVtwAIh3pC-wbasxzi+GJgHcBOjoodlYeCWhWgkIJQmrdOlsuDwpjg9vtomQerUoAA9YIURGAUHIhiMxhMtKxXuMeJx8QBXOiUKBaOBFaD-CDsKCvbLAYAMzaxKB7ABMR3Umi0Z0Sl2urFuNieLzG70+kgBiSBILB5E5EiOPPhiNqqIRvUcUGeOKZHy+-yggOBoLIQA)

```ts
type Lazy<A> = () => A;

declare const condition: boolean;

const match =
  <A>(x: () => A, y: () => A): Lazy<A> =>
  () =>
    condition ? x() : y();

const log =
  (msg: string): Lazy<void> =>
  () =>
    console.log(msg);

// ❌ This is a programmer error.
const fn1 = match(log("foo"), () => log("This will not be logged."));
const a = fn1();
//    ^?

// ✅ This is how it should have been written.
const fn2 = match(log("foo"), log("This will be logged."));
const b = fn2();
//    ^?
// => "This will be logged."

```

## 💻 Use Cases

See the above motivating example. This is a reduced version of bug we had on Unsplash (using the [`IO` type in fp-ts](https://github.com/gcanti/fp-ts/blob/1ca870a99c75717cdfa69afbb5d8937cb9037a27/src/IO.ts#L40-L42) instead of `Lazy`).

It's possible to catch these bugs using [`no-discarded-pure-expression`](https://github.com/buildo/eslint-plugin-fp-ts/blob/4099f438b37aa8e8a8fafc343cd5d201f00e7c9f/docs/rules/no-discarded-pure-expression.md), however this lint rule is extremely slow.

**Comment by fatcerberus** [comment]
Is there a reason you don’t think this agrees with the design goals?

**Comment by OliverJAsh** [comment]
I wasn't sure, but after thinking about it some more, I've now checked that box.

**Comment by RyanCavanaugh** [comment]
There's no way this would be workable in practice. The defining feature of void (relative to `undefined` or `unknown`) is that it does this; I would say if you think you have a problem with `void`, the general advice would be to only ever use `undefined` or `unknown` in your return type annotations instead.

The example itself doesn't really manifest any type violations, so trying to fix it with a type system change seems off. You could be writing, for example, this:
```ts
const log =
  (msg: string): Lazy<undefined> => // <- more-precise return type
  () =>
    void console.log(msg);

// I did mean to do this; no error has occurred
const fn1 = match(log("foo"), () => log("This will not be logged."));
const a = fn1();
if (a) {
  a();
}
```

A possible flag would be to treat unreturning function bodies as returning `undefined`, though it wouldn't really affect anything in the given example.
