### ISSUE TITLE
Double Emit of Contructor when using Getter Decorators

### ISSUE THREAD

**Issue by Matchlighter** [microsoft/TypeScript#53448]
# Bug Report

With the implementation of Stage 3 Decorators in TS 5, using a getter decorator can result in the content of the constructor being duplicated in the emitted code, for example:
```javascript
            constructor() {
                this.computedVal;
                console.log("As will this");
                __runInitializers(this, _instanceExtraInitializers);
                this.computedVal;
                console.log("As will this");
            }
```

### 🔎 Search Terms
Constructor duplicate decorators getter

### 🕗 Version & Regression Information
Started seeing this when I updated a library from TS 5.0-beta to TS 5.0.2.

This changed between versions `5.0-beta` and `5.0.2`. Not applicable to prior versions.

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&experimentalDecorators=false&ts=5.0.2#code/FAMwrgdgxgLglgewgAiggtgBzDApgEwAoYBDAJwHNcYAaVGADwC5kBhAGxIGcuBxavGQAiuNGRIwEZVkjwMYASmQBvYMnX0GAOhL58ASQhx4JdnABeuMoXDR4SZISWqNr1Ei4J2uLewQVCACJ9ADl9ABVAhTUNAF9o1zJqMDIUUkpqYFjgYChOHmQAIU4VGPUAenLkcIALOAgKLmQuXFx0ZElkAHcpAGtkbmRcBkxRPHxkOBAB5BA4XHYJqQGoKFweZbgm009kfFw5iAIaMuRKjQAjHAG9Y0QIU2QqGEEucpaXqybl9GoahHwTTQEHgEDAuA6CGarQ6NQh+AQYAu3iG6C2XHup3OD1+LC4MDI9QoyAAvMhAoEcq4AAJoLA4AinZ7uenjABqpicpTcGmBnm8vn8QVqW26cHY7GQmEJII6XTgayip0SyVSyAAzKdsqc+QSwLApFyXDzYVstHTsOzTMreR4vD4-AFAgBBJryiWmrhK1zZbVHLpFThOYBAA)

### 💻 Code
```ts
function computed(target, ctx: ClassGetterDecoratorContext) {
    ctx.addInitializer(function () {
        console.log("INIT")
    })
    return target
}

class Bla {
    // Things seem to work as expected if a field or accessor is also defined,
    //   but additional getters/setters or methods continue to see the double emission
    // name: string = ""

    @computed
    get computedVal() {
        console.log("This will print twice")
        return 3
    }

    constructor() {
        this.computedVal
        console.log("As will this")
    }
}

new Bla()
```

### 🙁 Actual behavior
Constructor logic is duplicated:
```javascript
            constructor() {
                this.computedVal;
                console.log("As will this");
                __runInitializers(this, _instanceExtraInitializers);
                this.computedVal;
                console.log("As will this");
            }
```

### 🙂 Expected behavior
Constructor logic should not be duplicated:
```javascript
            constructor() {
                __runInitializers(this, _instanceExtraInitializers);
                this.computedVal;
                console.log("As will this");
            }
```

**Comment by rbuckton** [comment]
The underlying issue is that the logic to inject `__runInitializers()` into a constructor incorrectly called `addRange`/`visitNodes` twice when a `super()` wasn't present. This only occurred for getters, setters, and methods because `__runInitializers()` is injected into the constructor when there are no fields present, but is injected into the first field initializer when fields are present.
