### ISSUE TITLE
[Bug] false `undefined` conclusion

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/TypeScript#53447]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about __TypeScript__
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZwIbgDYFM4F84BmUEIcA5BhACarIAWAtFsmQFCsDGEAdsvKnAC8KdGGwAKANoBGALoBKOOy68I2AHSUA5uIDUqRQHpDcQLwbgCR24MOsGRwOqbmXgAjHAAMArtypYCwbiwqdzgsADcsbis6CE8tOjh3PihgDhgAOU8MDABhOiwOAGtkENs4HlYgA)

### 💻 Code

```ts
import { sample } from 'lodash-es'

const a = sample([1]) 

console.log(+a) // 👈 this can't be `undefined` even though `strictNullChecks` is on
```

### 🙁 Actual behavior

TS throws `'a' is possibly 'undefined'`.

### 🙂 Expected behavior

TS doesn't throw.

**Comment by fatcerberus** [comment]
There is no bug here.  `sample` is declared as returning `T | undefined`.  TypeScript doesn't know anything about the implementation of `sample` to know that it can't actually return `undefined` in this case.

**Comment by wenfangdu** [comment]
@fatcerberus Thanks, opened it [here](https://github.com/lodash/lodash/issues/5620).

**Comment by fatcerberus** [comment]
I don’t think it’s a bug for lodash either fwiw - if you pass an empty array, you get `undefined`.  It’s just inconvenient in your case.  This is what non-null assertions `x!` are for.
