### ISSUE TITLE
how `--moduleResolution nodenext` affect /// <reference/> import

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/TypeScript#53449]
# Bug Report

### 🔎 Search Terms

moduleResolution nodenext 

### 🕗 Version & Regression Information
any version

### reproduce

clone this repo:
https://github.com/HomyeeKing/test-entry-ts

### 🙁 Actual behavior

after change moduleResolution from node to nodenext, `/// <reference/>`  in declare file not works

### 🙂 Expected behavior

I wonder how the nodenext resolutio strategy affect the `///<reference />`, the docs seems don't have much information about it

**Comment by RyanCavanaugh** [comment]
It's resolved the same as a module specifier

**Comment by HomyeeKing** [comment]
thanks, I see the problem, the `@ice/pkg/types` referenced in the declare file is not using `exports` properly
