### ISSUE TITLE
Add support for "Node18" or "dom.fetch" in the "lib" configuration to support NodeJS Fetch API

### ISSUE THREAD

**Issue by yinzara** [microsoft/TypeScript#53440]
NodeJS 18 now has the `fetch` API built in which includes support for all the normal Request/Response types supported by that API.

Right now if I attempt to use the tsconfig for NodeJS 18:
```json
  "compilerOptions": {
    "target": "ES2022",
    "module": "Node16",
    "moduleResolution": "Node16",
    "lib": [
      "ES2022"
    ]
  }
```

If I attempt to use the `fetch` API in code (or any of the classes related to it like Request/Response), I get:
```
error TS2304: Cannot find name 'fetch'.
```

If I add `dom` to the `lib` element in the compilerOptions, it compiles successfully but then I have access to the entire dom library which I don't want.

Can we get a `lib` option of `Node18` that adds all the classes related to the fetch APIs added in Node18?  Or maybe just `dom.fetch` or something?

**Comment by fatcerberus** [comment]
This would be something for `@types/node`.  TS has never included node types—for any node version.

**Comment by yinzara** [comment]
This is already in @types/node but when you attempt to compile, you get the given error.

**Comment by yinzara** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924
