### ISSUE TITLE
Problems when using method generics

### ISSUE THREAD

**Issue by tanhh326** [microsoft/TypeScript#53446]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.9.5 and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
export function paging<T>() {
    type DataType = Array<T & { checked?: boolean }>;

    const list: DataType = [];
    const list2: Array<T & { checked?: boolean }> = [];

    return {
        list,
        list2
    }
}

type Data = { id: number, name: string };

const {list, list2} = paging<Data>();

/*
  const list: DataType
  Alias for: Array<T & {checked?: boolean}>
*/
list.push({id:1,name:'2'});

// const list2: (Data & {checked?: boolean | undefined})[]
list2.push({id:1,name:'2'});

```

### 🙁 Actual behavior

Generic type T is not compiled to final type `Data`
### 🙂 Expected behavior

I want the `type DataType` to be reused in the function

**Comment by MartinJohns** [comment]
Your playground link doesn't work. And I don't see anything wrong in your code, in both cases the type is the same, just a different visual representation.

**Comment by tanhh326** [comment]
Occurred in the vue3+ts environment, it should not be a problem with ts

**Comment by tanhh326** [comment]
This `user00` and user are both the same data, why one will prompt a type error, and the other will not, and if the type is defined directly through `<Array<T & {checked?:boolean}>>` like `user10`, it will not prompt a type error . Maybe it's a problem with vue `Ref`?

**Comment by RyanCavanaugh** [comment]
Neither of these are type errors. Maybe this has been fixed in the interim? Please open a new issue if you have a clearer description of the problem. Thanks!
