### ISSUE TITLE
Option to emit ActionScript (ES3) bytecode for Adobe AIR

### ISSUE THREAD

**Issue by hydroper** [microsoft/TypeScript#53457]
# Suggestion

## 🔍 Search Terms

- ActionScript

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Add option to emit ActionScript bytecode (aka. AVM2 bytecode or ABC) for writting Adobe AIR apps in TypeScript. Here's a document of AVM2: https://jmendeth.com/snapshot/4d9475cfb10af8142e331551dc9b91e1217dc8c6/media/2014-05-17-reverse-engineering-flash/avm2overview.pdf

ActionScript is a subset of EcmaScript 3 (ECMA-262 3rd edition), so it's doable. Plus, wherever possible, TypeScript can emit classes statically instead of `prototype` constructor functions when the `extends` clause resolves to a known class ahead of time.

## 📃 Motivating Example

The Adobe AIR framework is actively maintained by Harman: [airsdk.harman.com](https://airsdk.harman.com). Apps are currently written either in ActionScript or Haxe by targetting ActionScript Bytecode (aka. ABC or AVM2 bytecode).

Adobe AIR is relevant for producing apps with unlimited data storage when compared to browser's indexedDB, localStorage and cookies. The [flash.filesystem.File](https://airsdk.dev/reference/actionscript/3.0/flash/filesystem/File.html) type supports URLs of scheme:

- `file:` locates directory or file in the user's device
- `app:` locates directory or file in the app's installation directory
- `app-storage:` locates directory or file in the app's storage directory

This was just a brief reason for using Adobe AIR. There is also support for native extensions aka. ANEs, though I don't know how TypeScript can use them; should there be a way to say a function or method is native?

## 💻 Use Cases

You can develop data-unlimited apps with Adobe AIR compared to browser as stated above.

**Comment by MartinJohns** [comment]
Same as #27362 and others. This is out of scope for TypeScript.

> [x] This feature would agree with the rest of TypeScript's Design Goals.

You might want to read those again.

**Comment by hydroper** [comment]
@fatcerberus I understand. I'd like to do it myself, but I don't know how to emit diagnostics and symbol tables and use them. I know there's an `emit()` method in `Program` at the compiler API, but it generates JS together.

Here's a discussion about that: https://github.com/airsdk/Adobe-Runtime-Support/discussions/2539#discussioncomment-5404173

**Comment by DanielRosenwasser** [comment]
Everything TypeScript has today supports this workflow - just not bytecode emit. `--outFile` with `--module none` is in reach. The only caveat is ES3 is now a deprecated target, so maybe you'd benefit from using ES5 while also linting against uses of keywords as property names (e.g. prefer `foo["default"]` over `foo.default`).
