### ISSUE TITLE
Generic Type only used as generic constraint is not checked

### ISSUE THREAD

**Issue by felixhirt** [microsoft/TypeScript#53451]
# Bug Report

### 🔎 Search Terms

generic used for generic constraint not checked 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (5.0.2)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=24&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgEoFcQmgHgCrIQAekIAJgM5oQID2UZOFYUoA5gDTIDeyAbgEYBALmTNWINsgC+APlk8AsACgA9KuRpMACjgjkAawgBPWjGR4AlKL61gZFZowgcAaUIkI5KkdPm8XAByHqSUFgDargC64QBEggKxUbK6+q5ccABMooHW-HYOytIqKjCYCGDAtCDIbLS0ZAhwADbN0NpQos7YUDi8gqL9QqKxFInIAD7Io5mxMjKylkrKmk2t7VCWKsXKpeWV1cgARnCNLW1QAh1dmD19-Nk8-MPTY3NTM3PSC0vcjshrC4dLZFErKMogCpVGonM7rKCZa5aLC4IaDZ76UYAZnerwALF8fstVucNiCdntIQcaoCNjcUb00U8EiM3vM5L9-lAAHTObTxRIgzQ8vnxWZC5AinQC2JcUaCrm86WCWWvcWK0V8WZyt7koA)

### 💻 Code

```ts
interface Runner<T extends Record<string, { v11: string }>> {
//  Run(a1: keyof T): void
  Run<K extends keyof T, N extends T[K]["v11"]>(a1: K, a2: N): void
}

function goodcaller(r: Runner<{ v1: { v11: "s1" | "s2" } }>) {
  caller(r)
}

function badcaller1(r: Runner<{ v2: { v11: "s1" | "s2" } }>) {
  caller(r)
}

function badcaller2(r: Runner<{ v1: { v11: "s3" | "s4" } }>) {
  caller(r)
}

function caller(r: Runner<{ v1: { v11: "s1" } }>) {
  r.Run("v1")
  r.Run("v2")
  r.Run("v1", "s1")
  r.Run("v1", "s2")
  r.Run("v2", "s1")
}
```

### 🙁 Actual behavior

As long as line 2 is commented out, the calls to "caller" on line 11 & 15 do not report an error, even though we can see from line 21, 22, 23 that we correctly restrict parameters based on "T". If line 2 is added, the errors are reported correctly. It seems generic types used only as internal generic constraints (like line 3) are not checked

### 🙂 Expected behavior

Generics used for constraints only should be included in the type analysis, because they are actually needed and lead to invalid code if ignored

**Comment by RyanCavanaugh** [comment]
Variance measurement doesn't take constraints into account. As a workaround, you can add a variance annotation to `Runner`. In this case it's invariant, so write
```ts
interface Runner<in out T extends Record<string, { v11: string }>> {
```

Simpler example of what's wrong:
```ts
interface Foo<T> {
  bar<U extends T>(s: U): void;
}
const x: Foo<string> = {
  bar(m) {
    m.toLocaleLowerCase();
  }
};
let y: Foo<number> = x;
y.bar(32);
```

**Comment by felixhirt** [comment]
Damn, i somehow missed the possibility to manually define variance in Typescript interfaces. I guess i have to learn how to use google properly. Sorry for wasting your time

**Comment by felixhirt** [comment]
Well, if you want to track this i can re-open the issue
