### ISSUE TITLE
`extends` keyword not suggested inside of generic

### ISSUE THREAD

**Issue by amunger** [microsoft/TypeScript#53467]
Not quite sure what makes it show up in the list but going to [this file](https://insiders.vscode.dev/github/microsoft/vscode/blob/62a44fb10b435ef7e083aa3bc0a290541a180bc0/extensions/ipynb/src/ipynbMain.ts#L127) and trying to add a generic type parameter with a constraint seems to show this issue:

![image](https://user-images.githubusercontent.com/2019016/227285193-2546630a-d5f8-40f8-82a1-a322b40aeb4f.png)

**Comment by mjbvz** [comment]
Minimal example:

```ts
function a<T exten|>() {}
```

**Comment by MartinJohns** [comment]
Possibly fixed by #53372?
