### ISSUE TITLE
Error constructor missing "options" optional parameter

### ISSUE THREAD

**Issue by NemoStein** [microsoft/TypeScript#53465]
# lib Update Request

## Configuration Check

My compilation *target* is `ESNext` and my *lib* is `the default`.

## Missing / Incorrect Definition

`Error` constructor is missing the `options` property

## Sample Code

```js
new Error('message', { cause: error })
// Expected 0-1 arguments, but got 2. ts(2554)
```

## Documentation Link

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error)
[TC39 Error Cause - Stage 4 proposal](https://github.com/tc39/proposal-error-cause)

**Comment by MartinJohns** [comment]
Works just fine: https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBApgJwSBMC8MCMBYAUGOAdxgFEkUAKAcgFs4IIBDAczioBoYBvGYRgVwhwAXPHKoAvgEo8QA

**Comment by NemoStein** [comment]
I tried to replicate in a clean project and it just work...
Deleted the whole `node_modules` and installed again and it worked.

So, yeah, my bad... Sowwy

**Comment by thernstig** [comment]
@NemoStein it was added in TS 4.9.
