### ISSUE TITLE
--exactOptionalPropertyTypes has no effect when narrowing object

### ISSUE THREAD

**Issue by wenq1** [microsoft/TypeScript#53462]
# Bug Report

### 🔎 Search Terms

exactOptionalPropertyTypes

### 🕗 Version & Regression Information

since the flag was introduced

- This is NOT a crash
- This changed between versions __4.4____ and ___5.0.2____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[](https://www.typescriptlang.org/play?noImplicitAny=false&target=9&exactOptionalPropertyTypes=true&ts=5.0.2&filetype=ts#code/FDD0oAgFQVwJwHYQPZILRoKYA8CGBjAFwHkAHQgS1VwBsAFOZUzOQgTyjeYGcR3mIAQQAmAN1wJ8mYcQBGAK0xEArBAC8EAN74Y3QsgC2AfgBcEPXAoIA5gBoIAMxrIA7qYgIYB2S3uyKhC4U3JjussjINJgSAL4gwOJwEKS4cCEAijAsbGQAYla0AMrM+KoQ5RUaDjCSlKgQABQAjllwbGYi4pLScooqAJTAmsAVo47ISQ1RhBAA1phsAAwoDhC9SoQAdPNs3I0t2f39WiNjZ6PTY-iowoJwcACM5+oQB20A2juLALoA3KfPM4UVYNL7qNQaADkOj0hkhx2GgKRY0uo2uCFu90BGjebE+Cx+-2RxMB4HKAD0jACSXESRVMDQQhBgY0wRCoU5XPCTnSkaiKujMUlnjjWnivn9qbySWSIJSpcjaec4nEEqlkqkMmK8gUaMUlFBMHpKo4akQqEhmmKzJp-IFgqEzOFItEEDFBppVYkIIQjYQAGqpCi4WRRDpiCRSGQKDZlcoaRHnO1BEJmBy0ELAGL-YApNKYTLZHUIIolQ3Ghq2gIpzBmX16QOWENRTbJh3ukBAA)

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

``` ts



// Turn on --exactOptionalPropertyTypes

type AdvancedObject5 = {custom?: string, bitwise?: boolean}



var parseQueryOpFinalSpecTest   = function (query: {bitwise?: boolean})
{}

var testVariable: AdvancedObject5    = {
        bitwise: false
};

// To prove that --exactOptionalPropertyTypes works, the following call
// will report: 
// Argument of type '{ bitwise: boolean | undefined; }' is not assignable to parameter of type '{ bitwise?: boolean; }' with 'exactOptionalPropertyTypes: true'
parseQueryOpFinalSpecTest ({bitwise: testVariable.bitwise})


var parseQueryOpFinalSpec5       = function (query: AdvancedObject5)
{
        for (let key0 of Object.keys (query)) {
                if (key0 === 'custom') {
                        let     condStr         = query[key0];          // wrong to include undefined in type?
                                //  ^?
                }
        }
}


```

### 🙁 Actual behavior

type of `condStr` is 'string | undefined'

### 🙂 Expected behavior

type of `condStr` has  NOT have `undefined` in it when --exactOptionalPropertyTypes is turned on

**Comment by RyanCavanaugh** [comment]
TS doesn't have special hardcoded logic about what `Object.keys` is. You can write this, which works:
```ts
  if ('custom' in query) {
    const m = query.custom;
  }
```
