### ISSUE TITLE
Stop global type leaks across commonJS modules

### ISSUE THREAD

**Issue by ziahamza** [Microsoft/TypeScript#5346]
A lot of type definitions in DefinatelyType export CommonJS module types and a global type definition for popular libraries. I.E Jquery can be used directly from the window object but also using the require syntax. 

But this causes Typescript to accept faulty code as correct. E.g using $ or jQuery directly in a commonjs module without requiring the module itself is compiled correctly, when in the first place it was a bug not to require the module. 

So can there be a flag where if commonjs modules is enabled then global types are not supported, and only types exported through a module name?

**Comment by weswigham** [comment]
#4913 has been proposed as a possible solution to this, but we have a number of competing proposals around the node package typing space. (You can find some of them linked in that PR)

**Comment by ziahamza** [comment]
Awesome, then I guess we can close the issue. will keep track of them. Thanks!
