### ISSUE TITLE
Implement decorator metadata proposal

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/TypeScript#53461]
# Suggestion

Implement [decorator metadata](https://github.com/tc39/proposal-decorator-metadata)

## 🔍 Search Terms

decorator metadata

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Now that decorators are shipping in TypeScript and decorator metadata has reached consensus on the approach needed for it to proceed to Stage 3, it seems like it may be time to implement metadata.

## 📃 Motivating Example

There are examples on the metadata repo, but a quick one is storing information about a class member to be used by the class's base class. Here we generate a custom element's `observedAttributes` by decorating fields:

```ts
// Library code:
const attributes = new WeakMap<typeof BaseElement, Array<string>>();
class BaseElement {
  static get observedAttributes() {
    // real code would get attributes from super-classes too
    return attributes.get(this[Symbol.metadata]);
  }
}
const attribute = (_, {name, metadata}) => {
  attributes.set(metadata, (attributes.get(metadata) ?? []).push(name));
}

// Usage:
class MyElement extends BaseElement {
  @attribute
  foo?: string;
}
```

## 💻 Use Cases

There are many use cases in the various decorators [repositories](https://github.com/tc39/proposal-decorators) and documents. Generally any time that some other API besides the decorated one needs information about the decorated items, you will need metadata.

It's worth noting that many libraries can't use decorators until metadata is implemented.

**Comment by MartinJohns** [comment]
> [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

I don't know the current position of the team on this, but it does violate non-goal 5. The current experimental metadata support comes from the early dark times before this design goal document.

**Comment by justinfagnani** [comment]
@MartinJohns 

> But that is only stage 2, usually the team waits for at least stage 3.

Yes, but like I mentioned the metadata proposal just got consensus on the approach to enable it to go to Stage 3 very soon. An issue like this can be used to track some work even before that work could be done or shipped.

**Comment by DanielRosenwasser** [comment]
Tentatively scheduling for TypeScript 5.2. Luckily, that's not too far off anyway.

**Comment by EisenbergEffect** [comment]
Please. Please. Please. Please. Please. Please. Please.

@DanielRosenwasser I will send your team a cake. Or, if you like other tastiest, let me know. Clearly I'm not above bribery when it comes to decoraator metadata 🤣

**Comment by EisenbergEffect** [comment]
Stage 3 is official!!! 🎊

**Comment by EisenbergEffect** [comment]
YES!!!! Awesome work everyone. @DanielRosenwasser please reach out to me on twitter, linkedin, etc. I really would like to thank the team somewhow.

**Comment by justinfagnani** [comment]
@rbuckton would #54657 be in the latest nightly? I'm trying to use metadata, and while it's in the typings, it appears to always be `undefined`: [Playground](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230625#code/FAYw9gdgzgLgBABwE5gQUyTAnnAvHAHgGEAaOANQD4AKASj0rmuDjhgEMkBzNGALjhEANuyhQAgiBBoxYJABE04JOxhyAKpx4xiZKiRZxwEGGgAe-QSLGTpshUrmq5RSKYu6KlerkYBvQ1ZjKDAhNAA6ITAuagByAFtedgATVXZYsmN3GHDEjlSOWgBuQLgkXgBXJAg4ANZ6uG1qGAALAEsoASJ6Oob68pgqmo5uXnDtcJB2ISFm9qhi0tYAXwM+uCheOY6usgA3AXIepfqRic2cqZntqH3F9dXS5ZLn4FBrKDhxVl6AAWRUBhsHRDOwpDIQkg4AAzMBgPBwWLsABGIFiLzewXg7AREDQAHcvnQSsFQhEojF2OFYWBFlSaax8LEzFgAF7o0CQEJhSLRaj0uGLIA)

**Comment by rbuckton** [comment]
Have you polyfilled `Symbol.metadata`? TypeScript does not polyfill runtime features, so you may need to add something like the following to use it:

```ts
(Symbol as any).metadata ??= Symbol.for("Symbol.metadata");
```

Also, you can use `// @lib: dom,esnext` in the playground to choose different libs.

**Comment by justinfagnani** [comment]
I just figured that out, thanks!

**Comment by jakearchibald** [comment]
@rbuckton I got caught out by `metadata` being `undefined` too. Would it make more sense to leave it defined even if `Symbol.metadata` is missing?

The current developer experience is:

1. Read the metadata docs
2. Try it in TypeScript
3. Try to set `context.metadata[key]`
4. `context.metadata` is `undefined`, wtf??

Whereas if `context.metadata` was still defined, it's:

1. Read the metadata docs
2. Try it in TypeScript
3. Set `context.metadata[key]`
4. Try to get the metadata from the class
5. `Symbol.metadata` is `undefined`, wtf??

With the latter case, you run into the actual problem, not a side-effect of the problem.

**Comment by justinfagnani** [comment]
I agree that seeing an error that `Symbol.metadata` is undefined would be a lot more clear - I initially thought that the TS metadata implementation had a bug).

I think changing the metadata initialization from this:

```ts
const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
// ...
if (_metadata) Object.defineProperty(this, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });

```

to this:

```ts
const _metadata = Object.create(null);
// ...
if (typeof Symbol === "function" && Symbol.metadata) Object.defineProperty(this, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
```

Would ensure that `context.metadata` is defined, that it's shared across all decorator applications for a class, that metadata usage that's only within decorators (ie, as a way of sharing) just works, and that the error from `Symbol.metadata` being undefined is more understandable.

**Comment by jakearchibald** [comment]
Yep, +1 to that implementation

**Comment by rbuckton** [comment]
If `context.metadata` is defined but isn't actually assigned to the class, it becomes more difficult for a decorator to test whether it can *actually* write metadata. This change wouldn't actually improve any use case, as any metadata you would attach would be lost.

Having `context.metadata` be `undefined` when not using a lib that has the symbol defined allows you to code defensively against environments that haven't shimmed `Symbol.metadata`. I'm not certain I'd be comfortable with this change.

I could see adding a documentation comment to the `metadata` property to explain the reason why it is missing.

**Comment by jakearchibald** [comment]
I guess if browsers shipped decorators without metadata, then `context.metadata` would be undefined.

Yeah, improved documentation seems reasonable.

**Comment by rbuckton** [comment]
The current approach also allows you to write the following shim in your code to enable `metadata` downlevel, if necessary:

```ts
export {};
declare global {
  interface SymbolConstructor {
    readonly metadata: unique symbol;
  }
}
Symbol.metadata ??= Symbol.for("Symbol.metadata");
```
The above code would also remove the `| undefined` from `context.metadata` due to the conditional type used to define it.

**Comment by justinfagnani** [comment]
> Having context.metadata be undefined when not using a lib that has the symbol defined allows you to code defensively against environments that haven't shimmed Symbol.metadata. I'm not certain I'd be comfortable with this change.

This is a really good point. We already do this in Lit 3.0 with a dev-mode warning when metadata is undefined telling people that they need to upgrade their compiler.
