### ISSUE TITLE
Autocompletion is working in TS 4.7 to 4.9 but broken/gone in TS 5

### ISSUE THREAD

**Issue by jgoux** [microsoft/TypeScript#53475]
# Bug Report

### 🔎 Search Terms

autocompletion

### 🕗 Version & Regression Information

- This changed between versions ^4.7.0 and ^5
- I was unable to test this on prior versions because some type features such as string literal manipulation are not available before 4.7

### ⏯ Playground Link

[Playground link with relevant code](https://tsplay.dev/wgD9lN)

### 💻 Code

Please go to the end of the code and try the `defineConfig` function:

```ts
defineConfig({
  exclude: {
    data: ["<cursor here, ctrl+space>"],
    structure: {
      schemas: ["secret", "<cursor here, ctrl+space>"],
      tables: ["<cursor here, ctrl+space>"]
    }
  }
})
```

### 🙁 Actual behavior

Between TS 4.7 and 4.9, we have autocompletion available for all array values under the `exclude` key
At TS 5 and above (I tried nightly as well), the autocompletion is gone

### 🙂 Expected behavior

The autocompletion should work the same as with TS 4.7 and 4.9

**Comment by Andarist** [comment]
Could you specify what exact completions you expect at given positions? I'm guessing that string completions are broken here (although some work in `extensions`). On top of that, I can see some inconsistencies between string completions and regular ones (in 4.9 as well)

**Comment by Andarist** [comment]
This was broken by [this PR of mine](https://github.com/microsoft/TypeScript/pull/51770) although I've hoped to fix its regressions with https://github.com/microsoft/TypeScript/pull/52875 . Gonna have to investigate what is different about this one here.

**Comment by jgoux** [comment]
@Andarist As `exclude.data`, `exclude.structure.schemas` and `exclude.structure.tables` are the generic I need to pick up, when the array is empty it's typed as `never[] | undefined`, so the normal autocompletion is not working in both 4.9 and 5 (I think there is no way I can make it works).
But if I use quotes in those like `"<cursor here, ctrl+space>"` it works in 4.9 but not in 5.
What's even stranger is that in 5, if you do `""<cursor here, ctrl+space>` (so the cursor after the empty quotes) it will provide autocompletion.
