### ISSUE TITLE
TS2366: Function lacks ending return statement in function with `unknown` return type with implicit return on some code paths, despite `noImplicitReturns` turned off

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#53473]
# Bug Report

### 🔎 Search Terms

lacks ending

### 🕗 Version & Regression Information

- This changed between versions 5.0.2 and 5.1.0-dev.20230323

I believe [this](https://github.com/microsoft/TypeScript/pull/53092/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8L35565-R35570) caused it.

### ⏯ Playground Link

https://www.typescriptlang.org/play?noImplicitReturns=false&ts=5.1.0-dev.20230323#code/GYVwdgxgLglg9mABFApgZygCgJQC5HgDWYcA7kgN4CwAUAJAzCKYCyAhlABYB0ATm2AAmcALY5EAPkQAGbgFZsiXiigheSKLxAoA3LQC+QA

### 💻 Code

```ts
function test(): unknown {
	if (Math.random() > 0.5) return true;
}
```

### 🙁 Actual behavior

```
> tsc --noEmit

index.ts:1:18 - error TS2366: Function lacks ending return statement and return type does not include 'undefined'.

1 function test(): unknown {
                   ~~~~~~~
```

### 🙂 Expected behavior

No error, if the function return type is `unknown` I'd expect that to allow implicit return of `undefined`.

**Comment by fatcerberus** [comment]
The error message changed, but this is an error in 5.0.2 and earlier too:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/4097841/227358484-db4491d3-30db-4ba8-ae9a-0f0751069e2a.png">

**Comment by AlCalzone** [comment]
Uh, the playground link had `noImplicitReturns` turned on. If you turn it off, it becomes an error **after** 5.0.2. I'll update the link

**Comment by fatcerberus** [comment]
What do you know, this actually broke some real-world code already. 😄 

> https://github.com/microsoft/TypeScript/issues/53474#issuecomment-1481902689

**Comment by DanielRosenwasser** [comment]
This was found in qwik too:

https://github.com/microsoft/TypeScript/issues/53474#issuecomment-1481902689

**Comment by DanielRosenwasser** [comment]
I think the simplest fix would just be to check for `TypeFlags.Unknown` - alternatively, we restore the `isTypeAssignableTo(undefinedType, type)` check.

Let's make sure that we test `strictNullChecks` on/off with other top-y types.

```ts
// @strictNullChecks: true,false

function foo(): unknown {
    if (Math.random()) return true;

    // implicit return
}

function bar(): {} {
    if (Math.random()) return true;

    // implicit return
}

function baz(): Record<string, any> {
    // implicit return
}

function blah(): any {
    // implicit return
}
```
