### ISSUE TITLE
`() => void` is assignable to `Record<string, any>`

### ISSUE THREAD

**Issue by aaditmshah** [microsoft/TypeScript#53484]
# Bug Report

### 🔎 Search Terms

1. function
2. record
3. any
4. mapped type

### 🕗 Version & Regression Information

I see the bug in all the versions of TypeScript, from v3.3.3 to v5.0.2, and even in the Nightly version.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHgLhgJQKagE4BMA80MCWYA5gDQwCGYAngHwwC8MAFAJSP0DeAvgNwBQQA)

### 💻 Code

```ts
const x: Record<string, any> = () => {};
```

### 🙁 Actual behavior

I do not get any type error.

### 🙂 Expected behavior

I expected to get the following type error.

```text
Type '() => void' is not assignable to type 'Record<string, any>'.
  Index signature for type 'string' is missing in type '() => void'.
```

**Comment by DanielRosenwasser** [comment]
It's because functions can have properties on them the same way that any other object can. Similarly, we (kind of unfortunately?) also allow functions to be assignable to the type `{ length: number }`.
