### ISSUE TITLE
Extract refactors break single-line `if` statements into two lines

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#53482]
# Bug Report

### 🔎 Search Terms

extract function single-line if

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about whether Tang was really invented by NASA

### 💻 Code

```ts
function f() {
  return [].filter(x => {
    if (!x) return false;
  });
}
```

### 🙁 Actual behavior

Select the arrow function callback of `filter` and run “Extract to inner function.” The formatting of the function contents should be the same in the extracted function.

### 🙂 Expected behavior

```typescript
function newFunction(): (value: any, index: number, array: any[]) => unknown {
  return x => {
    if (!x)
      return false; // New line added
  };
}
```

**Comment by fatcerberus** [comment]
> and I reviewed the FAQ for entries about whether Tang was really invented by NASA

lol

**Comment by DanielRosenwasser** [comment]
brb reading every issue Andrew has filed ever just in case I missed something

**Comment by andrewbranch** [comment]
You definitely did 😏

**Comment by iinicole** [comment]
Hi! This is my first time contributing. I would like to try resolving this issue if possible.
