### ISSUE TITLE
Does AmbientVariableDeclaration require a semicolon? If so, then dom.generated.d.ts does not conform to TypeScript syntax.

### ISSUE THREAD

**Issue by jirkadanek** [Microsoft/TypeScript#5348]
I think that the content of `dom.generated.d.ts` does not conform to TypeScript syntax as described in `spec.md`. I think that in the declaration below is missing a semicolon.

File https://github.com/Microsoft/TypeScript/blob/master/src/lib/dom.generated.d.ts contains the following:

    declare var ANGLE_instanced_arrays: {
        prototype: ANGLE_instanced_arrays;
        new(): ANGLE_instanced_arrays;
        VERTEX_ATTRIB_ARRAY_DIVISOR_ANGLE: number;
    }

TypeScript grammar at https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a10-ambients says:

    AmbientDeclaration:
        declare AmbientVariableDeclaration
        declare AmbientFunctionDeclaration
        declare AmbientClassDeclaration
        declare AmbientEnumDeclaration
        declare AmbientNamespaceDeclaration

    AmbientVariableDeclaration:
        var AmbientBindingList ;
        let AmbientBindingList ;
        const AmbientBindingList ;

That is, the semicolon at the end of an AmbientVariableDeclaration is required.

The spec.md does not talk about semicolon insertion at all, so I am unsure whether the grammar is for all TypeScript or only code that went through the insertion process first.

**Comment by RyanCavanaugh** [comment]
Ambient declarations have the same ASI rules as non-ambient code -- in this case, it hits the rule that says when you encounter an unexpected token (here, whatever token came on the line following the declaration) and there's a LineTerminator between the last valid token and the unexpected token, a semicolon is automatically inserted.

**Comment by jirkadanek** [comment]
So dom.generated.d.ts is correct, if maybe a bit inconsistent in where it puts the optional semicolons and where it omits them. (declare var's at the end of the file do have those semicolons,)

Thank you for your explanation.
