### ISSUE TITLE
tsc build for dependency library within client module ends with errors

### ISSUE THREAD

**Issue by kasi1999999** [microsoft/TypeScript#53485]
_#_ Bug Report

### 🔎 Search Terms

- _error TS2552: Cannot find name 'HTMLImageElement'. Did you mean 'HTMLLIElement'? tsc dependency build
- _tsc client library build
- _npm typescript lib client side build

### 🕗 Version & Regression Information

The bug started when trying to build a dependency library as an npm dependency for my main node module.
The dependency library is stored as GitHub repo and added as github dependency into main module. npm install inside repo of dependency library is working as expected.

- This is a crash
- Tested with typescript 4.6 and 5.0 - same errors
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _tsconfig.json Behavior_

### ⏯ Playground Link

Unable to setup playground, as the issue is related to tsc build with npm as submodule/dependency.

### 💻 Code

Dependency library has following build scripts, package.json:
```
  "scripts": {
    "dev": "ts-node ./script.ts",
    "build": "npx prisma generate && npx tsc --build --verbose ",
    "install": "npm run build"
  },
```
Dependency library has following tsconfig.json:
```
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "lib": ["ESNext"],
    "esModuleInterop": true,
    "target": "ESNext",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "declaration": true
  },
  "ts-node": {
    "esm": true
  },
  "include": [
    "./DependencyModel.ts",
  ],
  "exclude": ["node_modules", "**/test/*", "dist"]
}
```

Import in main module, package.json:
```
"dependencies": {
  ...
  "dependency-lib": "github:company/dependency-lib",
  ...
}
```

### 🙁 Actual behavior

npm install inside repo of main module ends with error:

```
9:50:37 AM - Projects in this build: 
    * tsconfig.json
115 error
9:50:37 AM - Project 'tsconfig.json' is out of date because output file 'dist/DependencyLibrary.js.map' does not exist
115 error
9:50:37 AM - Building project '/path_to_client_app/node_modules/dependency_module/tsconfig.json'...
115 error
../@types/mapbox-gl/index.d.ts(329,19): error TS2304: Cannot find name 'ImageData'.
../@types/mapbox-gl/index.d.ts(340,19): error TS2304: Cannot find name 'ImageData'.
../@types/mapbox-gl/index.d.ts(1161,27): error TS2304: Cannot find name 'Geolocation'.
../@types/mapbox-gl/index.d.ts(1231,33): error TS2304: Cannot find name 'Node'.
../@types/mapbox-gl/index.d.ts(1360,52): error TS2304: Cannot find name 'ImageData'.
../@types/mapbox-gl/index.d.ts(1388,24): error TS2304: Cannot find name 'HTMLImageElement'.
../@types/mapbox-gl/index.d.ts(1388,24): error TS2552: Cannot find name 'HTMLImageElement'. Did you mean 'HTMLLIElement'?
../@types/mapbox-gl/index.d.ts(1388,43): error TS2304: Cannot find name 'ImageData'.
../@types/mapbox-gl/index.d.ts(1388,55): error TS2304: Cannot find name 'ImageBitmap'.
../@types/mapbox-gl/index.d.ts(1474,21): error TS2304: Cannot find name 'HTMLVideoElement'.
../@types/mapbox-gl/index.d.ts(1536,26): error TS2304: Cannot find name 'HTMLCanvasElement'.
../@types/mapbox-gl/index.d.ts(1869,19): error TS2304: Cannot find name 'HTMLElement'.
../@types/mapbox-gl/index.d.ts(1954,52): error TS2304: Cannot find name 'MouseEvent'.
../@types/mapbox-gl/index.d.ts(1976,52): error TS2304: Cannot find name 'TouchEvent'.
../@types/mapbox-gl/index.d.ts(1990,52): error TS2304: Cannot find name 'WheelEvent'.
../@types/mapbox-gl/index.d.ts(1997,58): error TS2304: Cannot find name 'MouseEvent'.
../@types/mapbox-gl/index.d.ts(2033,58): error TS2304: Cannot find name 'WebGLContextEvent'.
../@types/mapbox-gl/index.d.ts(2398,20): error TS2304: Cannot find name 'WebGLRenderingContext'.
...
../@types/mapbox__mapbox-sdk/index.d.ts(36,27): error TS2304: Cannot find name 'ProgressEvent'.
../@types/mapbox__mapbox-sdk/index.d.ts(37,25): error TS2304: Cannot find name 'ProgressEvent'.
```

### 🙂 Expected behavior

npm install inside repo of dependency library is working as expected. I would expect the same, when building inside main module as dependency.

I tried to modify dependency module tsconfig.json file - I added _dom_ as _compilerOptions > lib_ option, then the dependency library build inside main module context works OK.

**Comment by RyanCavanaugh** [comment]
This doesn't look like a bug. You have `"lib": ["ESNext"],`, which means no DOM, and `mapbox-gl` is depending on types declared in the DOM. You might try settings `"types": []` in the tsconfig so that the mapbox-gl types don't get automatically loaded.

**Comment by kasi1999999** [comment]
Hello Ryan,
thanks for your reply.

Please, could you explain, why during the building of my dependency library (during `npm i ` in my client application), the `mapbox-gl` is processed?

In my dependency library package.json file, I have only these dependencies, no `mapbox-gl`:
 ```
 "devDependencies": {
    "@types/chai": "^4.3.4",
    "@types/chai-as-promised": "^7.1.5",
    "@types/expect": "^24.3.0",
    "@types/fs-extra": "^9.0.13",
    "@types/mocha": "^10.0.1",
    "chai": "^4.3.7",
    "chai-as-promised": "^7.1.1",
    "fs-extra": "^10.1.0",
    "mocha": "^10.1.0",
    "prisma": "^4.11.0",
    "ts-mocha": "^10.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.2",
    "@types/node": "^16.18.19"

  },
  "dependencies": {
    "@prisma/client": "^4.11.0"
  },

```

**Comment by jakebailey** [comment]
Try `npm why @types/mapbox-gl`.

Otherwise, the path in your message may imply that it's in a parent directory's `node_modules` (note the ..).

**Comment by kasi1999999** [comment]
I run `npm why @types/mapbox-gl` in my dependency library package. The output is: `npm ERR! No dependencies found matching @types/mapbox-gl`. This is not a surprise for me, because there are no `mapbox` dependencies in my dependency library package.

The `mapbox` dependencies are however in my client package that uses the dependency. My question is, why during the build of my dependency library package, it goes into dependencies of client package.

**Comment by jakebailey** [comment]
Try running `tsc --explainFiles` and see why it's being included. it's possible you're importing cross-project and so it's being included.
