### ISSUE TITLE
Type alias preservation breaks when a type is created from an indexed access type

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript#53496]
# Bug Report

### 🔎 Search Terms

type alias preservation, indexed access, 4.2

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type alias preservation

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/KYDwDg9gTgLgBDAnmYcAqwDOMCMcC8cA3nAIYBcxcARpdlAJYB2A5nAL7sDaARKTwF0AUENCRYCZKgzYATASq049Zm3YiAJsADGAG1JRU2iE2wIsuSjNxCA9LbiOnzxwD0A-Jp37DcY6fgYC1krYLsHF0iPISA)

### 💻 Code

```ts
export type Test1 = { a: { b: string }}["a"]

export type Test2 = { b: string }

declare const test1: Test1
//            ^? - const test1: {
//                b: string;
//            }

declare const test2: Test2
//            ^? - const test2: Test2
```

### 🙁 Actual behavior

TypeScript loses the `Test1` name in the type of the first variable, when it should keep it like the second variable.

### 🙂 Expected behavior

Both variables should have their type displayed as a type name, since I gave both types a name.

Ref: https://github.com/TypeStrong/typedoc/issues/2209

**Comment by RyanCavanaugh** [comment]
Type alias preservation isn't an invariant; the construction of `Test1` specifically defeats the heuristic used to set up the link.

**Comment by Gerrit0** [comment]
That's incredibly unfortunate, since type predicate libraries like zod, io-ts, etc. place the resulting type on a property of a class, then expect people to create types with `type MyType = lib.TypeOf<typeof MyTypeValidator>` which grabs that property.

Is there a better way of doing things here that will let dynamically created types retain names?

**Comment by RyanCavanaugh** [comment]
I'd have to understand why `Test1` was written that way in the first place

**Comment by Gerrit0** [comment]
The original bug report I received: [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM53gMyhEcDkwEAtDKvgNwBQVA9AglYnAOICmAdm1MjGynFQxewAMYYAnmH7IANsDRxsuAVACuHGKH4wpbAHRMEtKmwAekWJOlwAwrjDBZbACraXegDwAlDW5CuenDmfBwAJugw+h7SnsgcEgA0KAnJGgDWHBAA7hwAfHlwALwY0XoA8pg+fu56edSmFtDwohAcQnDeLgD6LmxCAIzFpbrSABQA3kyCMFAAXKVCUMAcAOaJ0xxqIAtRWyAARtxUAL4AlDTmlvCj-H2Dw-bgTq61sbcQmJ099zAD9ZcmlZbnBfgAmYZTOAzeYwlbrTbbBb7I5QU40eiMZguAAW-DAyB4AT4UDgwHQGigbGQYWQB2chmYAAECUS4KzkCAjCYrs0lBpRFo2nAQBIAGICgZjDk7UH9P5nOBQ6FwWi0FUazVagB6AH4aCcMQwjKC8ezCZy2CSyehMCsDCaWRa8DLuY1rvyOIKiBwReKBWDpc6FuDFcroWqtVHNXrTkA)

```ts
import * as t from 'io-ts';

/**
 * Generate a static type alias from a runtime type.
 */
export type CompileTimeType<RunTimeType extends t.Type<any, any, unknown>> = t.TypeOf<RunTimeType>;

export const RT_Test1 = t.type({
  str: t.string,
  num: t.number
})

export type Test1 = CompileTimeType<typeof RT_Test1>;
//                   ^ Works like Test1 in my example
```

**Comment by RyanCavanaugh** [comment]
OK, but the name *is* preserved, for example in declaration emit:
```ts
/**
 * The parameter is unreadable.
 * @param param
 */
export declare function myFunc1(param: Test1): void;
/**
 * The parameter is fine.
 * @param param
 */
export declare function myFunc2(param: Test2): void;
```

It seems like you're talking about the tooltip, though? In general the feedback we've gotten is that people want *more* structural display of types in tooltips rather than *less*. It seems like typedoc should be preferring the type-as-declared whenever possible. It's likely we'd change tooltips to have more structural display in the future rather than less.

**Comment by Gerrit0** [comment]
TypeDoc currently uses types typeToTypeNode when converting -- it does this instead of using the original type node so that it works properly when people inherit from generic classes, or a declaration like `const genNumber = generate<number>`. It would be best if I could ask TypeScript if the type I'm looking at refers to some type alias, and then intelligently decide (or even let the user decide) whether to use the type name or the expanded result.

I guess I could make typedoc take the type node, then check if `getSymbolAtLocation(node).flags` has the `TypeParameter` flag to determine if it should switch to asking TS for the resolved type?... fully rework the converter again.

Ideally, I'd like to make it act like how TypeScript does for `Test2` -- if you hover over the `Test2` type, you see the expanded object (which is what typedoc ought to show in the docs for Test2). If you hover over the `param` that references it's type as `Test2`, you should get `Test2`, not the expanded object.

**Comment by Gerrit0** [comment]
> OK, but the name is preserved, for example in declaration emit:

Coming back to this -- this is not always true.

```ts
export const test1 = null! as Test1
export const test2 = { b: "" } satisfies Test1
```

emits as:

```ts
export declare const test1: {
    b: string;
};
export declare const test2: {
    b: string;
};
```
