### ISSUE TITLE
Property keys in mapped types cannot be used to index nested types

### ISSUE THREAD

**Issue by saltman424** [microsoft/TypeScript#53491]
# Bug Report

When creating a mapped type where a property also appears on a nested type, for some reason the property cannot be used to index the nested type.

### 🔎 Search Terms

- Mapped types
- Property keys
- Mapped type indexing

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about this

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgdnCAnAglAvFA3lAhgLijgFcBbAI2SgF8AoUSWBZAIQ2ynMPIHseAbCLjg164aAHliwKphwEmiVAG5OheErZ1aAeh1QU-flB4AzKMAAW0Svx4B3KAGdLPYvwAmnaEjcBzS34QKAgAR2IASwA3XEE4YFpdfQA5HmA8IwcIDzFGADEIuFiARnYcAG0AaShCqABrCBAzKCkZJABdQlbkKvbe0QZoAqL+ACYyqCqakQByXBmoAB8oGfIZzpbpHsq+ndE9A0z7bNyhwtiAZgmp2rn1rq2kXv7qKAAyDhvZtY3up52XqcoMNYgAWCYKP7lO59GGqLibNrQn7I9YDcTA878ACs12qtQaTXMf1+j2ehOaUJ27VEQA)

### 💻 Code

```ts
type InnerA = { a: number }
type InnerB = { b: boolean }
type Outer = { a: InnerA; b: InnerB }

// All of the below should be roughly equivalent

// Not allowed
type Final1 = { [K in keyof Outer]: Outer[K][K] }
type Final2 = { [K in 'a' | 'b']: Outer[K][K] }
// Allowed
type Final3 = { [K in 'a']: Outer[K][K] } & { [K in 'b']: Outer[K][K] }
type Final4 = { a: Outer['a']['a']; b: Outer['b']['b'] }
type Final5 = { [K in keyof Outer]: Outer[K][keyof Outer[K]] }
```

### 🙁 Actual behavior

`Final1` and `Final2` produce:
> Type 'K' cannot be used to index type 'Outer[K]'.

### 🙂 Expected behavior

No errors with all five `Final` types being equivalent in this case. Really, I just want to be able to use `Final1`

**Comment by RyanCavanaugh** [comment]
An index type has to be statically verifiable through type information, not pure iteration, to be able to used in a lookup position.

You can write this, which will have no effect if the invariant you're relying on is true:
```ts
type Final1 = { [K in keyof Outer]: Outer[K][K & keyof Outer[K]] }
```

**Comment by saltman424** [comment]
@RyanCavanaugh thank you for the quick response and clarification!
