### ISSUE TITLE
`f<T>(a:T,b:T)` not rejects passing different `Record` types for a and b (but not when a and b are values). 

### ISSUE THREAD

**Issue by emilioplatzer** [microsoft/TypeScript#53503]
# Bug Report

### 🔎 Search Terms

  * Generic values 
  * Generic types
  * Geneics in parameters

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _all_

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/GYVwdgxgLglg9mABBBECGUA8AVAfACjQC5sAaRAIxIEojEBnKAJxjAHMBvAKEV8SYCmUEEyRpEAakQByGZMoBuLgF8uXAG5om-AfQCMiALzJUGfACIAFnAA2ac+QDM1BYh6IA9B8QBRAEp+APJ+dACCTGwgALYCYFCIcMCIUACeAA4CMmDRFAJMsjD0iGBw8Wj09DBsYGgUNplQcIhpWmgxUHkJSakZMows7NIAdPgATI4ALACs1Gqa2oL0o0YmkGYcNTFEVrb25Jo2IAJEjsrkG23HHgASux77aIfHpy5cHgBUyekCiavo8ZY8scuKBILAEH8MJgLlsGMxWGxXAcjnRslFckwFMpEAAfRAw46IPwCNg+AAeaSRjxRxRyeSxuHcfGZfEIdAJdH6CKpT1RdMx2LxHKJJPJlMQyMJaIxWPITJZLKo+M2hK57B5NOl9MFysudGJpIpGql-KxtDhAzYXHe3j4XCAA)

### 💻 Code

```ts
function concat<T>(a:T, b:T): string{
    return a + ' ' + b;
}

var res1 = concat("hola", 3); 
  // ERROR: Argument of type 'number' is not assignable to parameter of type 'string'.(2345)

var res2 = concat({name:"hola", value:3}, {name:/Hola/, value:3});
/* typeof concat here:
function concat<{name: string; value: number;} | {name: RegExp; value: number;}>
            (a: {name: string; value: number;} | {name: RegExp; value: number;}, 
             b: {name: string; value: number;} | {name: RegExp; value: number;}): string
*/
```

### 🙁 Actual behavior

The second call was accepted by TC, deducing that the property _name_ is of type `string | RegExp`,
albeit rejects the first. 

### 🙂 Expected behavior

In my opinion _concat_ must reject it, because the types are not the same (they aren't in the first call also). 

I think there is a degree of inconsistency. 

#### use case

```ts
compareDbRows<T>(row1:T, row2:T): boolean{
   // ...
}
```

**Comment by RyanCavanaugh** [comment]
> In my opinion concat must reject it, because the types are not the same (they aren't in the first call also).

> I think there is a degree of inconsistency.

The consistency argument can only go so far, since `concat(0, 1)` is *also* a call of two types (`0` and `1`). Inference attempts to infer what you wanted to happen; it can't know for sure so has to make some judgment calls in both directions.

**Comment by emilioplatzer** [comment]
I understand that the union can be always computed. But in `concat("hola", 3)` of my example TS founds an error (and could have understood the union type here). 

May be this is no so bad as it apears because it seems that this only happens when I passing literals to the function. In:

```ts
var left = {name:"hola", value:3};
var right = {name:/Hola/, value:3};
var res2 = concat(left, right);
```

It works as I expect (rejecting).

As you can see in [Playground](https://www.typescriptlang.org/play?ts=5.0.2#code/GYVwdgxgLglg9mABBBECGUA8AVAfACjQC5sAaRAIxIEojEBnKAJxjAHMBvAKEV8SYCmUEEyRpEAakQByGZMoBuLgF8uXAG5om-AfQCMiALzJUGfACIAFnAA2ac+QDM1BYh6IA9B8QBRAEp+APJ+dACCTGwgALYCYFCIcMCIUACeAA4CMmDRFAJMsjD0iGBw8Wj09DBsYGgUNplQcIhpWmgxUHkJSakZMows7NIAdPgATI4ALACs1Gqa2oL0o0YmkGYcNTFEVrb25Jo2IAJEjsrkG23HHgASux77aIfHpy5cHgBUyekCiavo8ZY8scuKBILAEH8MJgLlsGMxWGxXAcjnRslFckwFMpEAAfRAw46IPwCNg+AAeaSRjxRxRyeSxuHcfGZfEIdAJdH6CKpT1RdMx2LxHKJJPJlMQyMJaIxWPITJZLKo+M2hK57B5NOl9MFysudGJpIpGql-KxtDhAzYXHe3j4cy0iHqwHixg5OzsDgl1OeyiU834VUsLt1WxudwevNOfodi2WxhQayg+CdUHILDYQdevC8vgCwTCEWisXivx6mWkHGKepFhvFkr56PpiGUBSKJTKFSqNTqDSaLSYlw62lL3xklZVnPh6q9vNpjcxzeG7hzvGw3yKvzSTDgGSYqSyl1kWkyrBQURasB7Q2Xtr4a960gNYtbxVKiHKlWqtXqySaZb6U5sMMYyTDMahAA)
