### ISSUE TITLE
Array destructuring a `T[]` results in `T` instead of `T | undefined`

### ISSUE THREAD

**Issue by virchau13** [microsoft/TypeScript#53501]
# Bug Report

If you destructure an array with not enough elements, the rest of the elements are undefined. Currently, however, `T` is inferred for all elements, meaning that it's possible to get an `undefined` that's typed as a `T`.

### 🔎 Search Terms

Array destructuring, array destructuring inferred type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about array destructuring.
I wrote a script to test every version since 2.2.2 and none of them had the correct behaviour, so I don't think this is a regression.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230324#code/DYUwLgBAhgTjEF4IG0DkUBGBjVBdA3AFCiTJQA0EGui0cRWA9gHYDOjoAdMIwOYAUGAJT4gA)

### 💻 Code

```ts
function onlyAcceptsString(v: string) {}
let arr: string[] = ["only one string here"];
let [x, y] = arr;
onlyAcceptsString(y); // should fail, but passes fine
console.log(y); // `undefined`
```

### 🙁 Actual behavior

`y` has a type of `string`.

### 🙂 Expected behavior

`x` and `y` should _both_ have a type of `string | undefined`.

**Comment by jakebailey** [comment]
I think you're losing for `noUncheckedIndexedAccess`.

[Playground Link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&ts=5.1.0-dev.20230324#code/DYUwLgBAhgTjEF4IG0DkUBGBjVBdA3AFCiTJQA0EGui0cRA9AxC6wHoD8QA)

**Comment by virchau13** [comment]
Ah yes, you're right. A bit strange that it's not on by default, but thank you!

**Comment by jakebailey** [comment]
Enable it by default and you'll soon find out why it defaults to off 😅
