### ISSUE TITLE
Calling a function that returns never, not always triggers an unreachable code error

### ISSUE THREAD

**Issue by gabrielricardourbina** [microsoft/TypeScript#53510]
# Bug Report

### 🔎 Search Terms
- return never
- unreachable code

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about return never & unreachable code

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2&ssl=23&ssc=3&pln=1&pc=1#code/CYUwxgNghgTiAEYD2A7AzgF3gIwgVwQC54AKAOgtgHM1ioUBPASngF4A+eFEANxBgBQoSLATJ0WABZIAZsRIyU8QiSjyKZarXj1mbTtz4wWHeDyQBLYPBOdzVgQPGZ4AdwsZJAIXwJWpJlMAbwF4MJxfEgAiDBBMKKZQ8LgMPBglKIB5AGko+AB6fPgAVRQ4KDBJKFwxJFB4UFiwWOABAF9HZyx3TwAFCxQAazZSAAcB4fVKGBo6RlsuXn5AzhDw+HGh6Nj4xPWUtIycvMKSspAKqprEOoRG8Bb2ztQXHskAcTgQJX8SPCHiP9BigkK4UAs1uEuvAqF8fvAgTo0KQNFo5npTIZ+EkwrCQN9tnEMAkcfADul4FlcqdSuVKtUILV6gA5TIAFQaICajw6AmkMhIJDQIAgMhWkLCwtF0RQUEkkhJ+y5h0pmUGJyKtIu9OuyBZ7M53JArTaTCAA)

### 💻 Code
```ts
declare const blue : (...args: any) => never
declare const hof: (fn :(a: (...args: any) => never) => void ) => void

const withBlue = ()=> {
    blue("test")
    return "OK" // Unreachable code detected
}

const withPink = (pink : (...args: any) => never)=> {
    pink("test")
    return "OK" // Unreachable code detected
}

const withGreen = (unk: unknown) => {
    const green = unk as (...args: any) => never
    green("test")
    return "OK"// Unreachable code NOT detected
}

hof((self)=>{
    self("nahh")
    return "Ok" // Unreachable code NOT detected
})
```

### 🙁 Actual behavior

When the function that returns never is inferred, it does not detect unreachable code
When the function that returns has been type-asserted, it does not detect unreachable code

### 🙂 Expected behavior

Calling a function that returns never should render all code bellow unreachable

**Comment by MartinJohns** [comment]
It's a known design limitation, see #32695.

**Comment by gabrielricardourbina** [comment]
I understand, thanks, should I close this ticket?

**Comment by MartinJohns** [comment]
Feel free to. Either you do it, or typescript-bot will do it in a few days, as this issue has the duplicate label.
