### ISSUE TITLE
Property 'find' does not exist on type 'object'.ts(2339)

### ISSUE THREAD

**Issue by SavedCity** [microsoft/TypeScript#53520]
### Hey guys!

I am running into this type error with the `.find` method. I know this is a `tsconfig.json` lib issue but I read every single article and none of the solutions worked for me.

I tried adding to the `lib` list: es5, es2015, es6, es2016, es7, es2017, es2018, es2019, etc. one by one.
I also tried adding all those to the `target` as well

My typescript version is `4.9.4`

This is my `tsconfig.json`:

<img width="590" alt="Screenshot 2023-03-26 at 11 36 01 PM" src="https://user-images.githubusercontent.com/80661492/227834744-e80761ba-4d42-43d7-bf86-c44f5d36d603.png">

**Comment by MartinJohns** [comment]
> I know this is a tsconfig.json lib issue but I read every single article and none of the solutions worked for me.

It's not an issue with your tsconfig, it's an issue with your code. The error message in your title clearly indicates that you try to call `.find()` on a value typed `object`, but `object` does not have a `find()` method - no matter what `lib` is included.

Questions like this are better suited for a support forum like StackOverflow. The issue tracker is meant for feature requests and bug reports.

**Comment by SavedCity** [comment]
> > I know this is a tsconfig.json lib issue but I read every single article and none of the solutions worked for me.
> 
> It's not an issue with your tsconfig, it's an issue with your code. The error message in your title clearly indicates that you try to call `.find()` on a value typed `object`, but `object` does not have a `find()` method - no matter what `lib` is included.
> 
> Questions like this are better suited for a support forum like StackOverflow. The issue tracker is meant for feature requests and bug reports.

Okay, thanks for the answer. Thinking it's because of the value typed object. Might just mark it as `any` since the error goes away then

**Comment by SavedCity** [comment]
> > I know this is a tsconfig.json lib issue but I read every single article and none of the solutions worked for me.
> 
> It's not an issue with your tsconfig, it's an issue with your code. The error message in your title clearly indicates that you try to call `.find()` on a value typed `object`, but `object` does not have a `find()` method - no matter what `lib` is included.
> 
> Questions like this are better suited for a support forum like StackOverflow. The issue tracker is meant for feature requests and bug reports.

Okay, thanks for the answer. Thinking it's because of the value typed object. Might just mark it as `any` since the error goes away then
