### ISSUE TITLE
Disallow empty binding patterns

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5352]
It's currently being discussed whether or not an empty binding pattern should be an early error.

See https://github.com/tc39/ecma262/issues/97

**Comment by RyanCavanaugh** [comment]
Note: Outcome in linked bug was to continue to allow empty binding patterns.

That said, we should think carefully about how this ought to work in TypeScript since we have more user-side syntactic ambiguity and might want to make this an error.

**Comment by DanielRosenwasser** [comment]
Consider #5586 while discussing this.

**Comment by RyanCavanaugh** [comment]
If ES6 was willing to justify this, we're OK with it too.
