### ISSUE TITLE
valueof Type Operator like keyof

### ISSUE THREAD

**Issue by KingMario** [microsoft/TypeScript#53521]
# Suggestion

## 🔍 Search Terms

valueof

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

The `keyof` operator takes an object type and produces a string or numeric literal union of its keys.

I suggest `valueof` operator takes an object or array const and produces a string or numeric literal union of its values.

## 📃 Motivating Example

We may declare a type and an array const together like this:

```
export type Status = 'Online' | 'Offline' | 'Unknown';
export const AllStatus: Status[] = ['Online', 'Offline', 'Unknown'];
```

For usage in Angular, the type is used for type annotations and the array is used for some for-loops in templates and component classes.

If `valueof` type operator is available, we can make it more maintainable like this:

```
export const AllStatus = ['Online', 'Offline', 'Unknown'];
export type Status = valueof AllStatus;
``` 

## 💻 Use Cases

In some cases, literal unions are more type-friendly than enum while used in Angular templates.

For example, to guarantee type safety and make use of the auto-complete functionality of IDE:

Enum

```
<div *ngIf="item.status === Status.Online">
  <!-- ... -->
<div>
```

requires a `Status = Status` property in the component class.

vs

Literal Union

```
<div *ngIf="item.status === 'Online'">
  <!-- ... -->
<div>
```

If we can declare the array and then product the type using a `valueof` operator, we can write a more maintainable pair of array and type effectively.

**Comment by MartinJohns** [comment]
You can just do this:

```typescript
const AllStatus = ['Online', 'Offline', 'Unknown'] as const;
type Status = (typeof AllStatus)[number];
```

**Comment by KingMario** [comment]
@MartinJohns Thanks.

That works for array const.

What about AllStatus is an object? And I want a Status type as literal union of all the values of the object?

Thanks~~~

**Comment by MartinJohns** [comment]
If I understand you correctly:

```typescript
export const AllStatus = { foo: 'a', bar: 'b' } as const;
export type Status = { [P in keyof typeof AllStatus]: (typeof AllStatus)[P] }[keyof typeof AllStatus];
```

**Comment by Crunchyman-ralph** [comment]
I've found:
```ts
export type ValuesOf<T> = T[keyof T];
```

to be quite nice.

usage:
```ts
export type Status = ValuesOf<AllStatus>
```

**Comment by KingMario** [comment]
> I've found:
> 
> export type ValuesOf<T> = T[keyof T];
> to be quite nice.
> 
> usage:
> 
> export type Status = ValuesOf<AllStatus>

Thanks @Crunchyman-ralph. That's nice and neat!

Since AllStatus is a const, the usage should be:

```
export type Status = ValuesOf<typeof AllStatus>;
```
