### ISSUE TITLE
AbortController.abort(reason) doesn't use provided reason

### ISSUE THREAD

**Issue by austinchen12** [microsoft/TypeScript#53545]
# Bug Report

### 🔎 Search Terms

AbortController, AbortController.abort, reason
### ⏯ Playground Link

[Playground link with relevant code](https://codesandbox.io/s/autumn-architecture-rpu0z0?file=/src/App.js)
### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

In the codesandbox, when you press the button you get the message `bad!: "The user aborted a request."` instead of the custom error message "custom error message"
### 🙂 Expected behavior

When you press the button, you should see `bad!: "custom error message"`

**Comment by austinchen12** [comment]
Related to https://github.com/microsoft/TypeScript/issues/47505

**Comment by fatcerberus** [comment]
#47505 is about missing the `reason` parameter in the types.  It seems like this issue is about runtime behavior, which is out of TypeScript’s control.

**Comment by austinchen12** [comment]
@fatcerberus is this issue better in the react repo?

**Comment by fatcerberus** [comment]
@austinchen12 Assuming `AbortController.abort` is a React function, then yes.

**Comment by eden-eitani** [comment]
@austinchen12 did you find a solution?
