### ISSUE TITLE
[lsp] importId completion candidate should include keys of tsconfig.compilerOptions.paths

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#53553]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

- lsp
- editor
- completion
- ESM
- import
- importId
- tsconfig compilerOptions paths

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

importId completion candidate should include keys of tsconfig.compilerOptions.paths

## 📃 Motivating Example

Currrently, given

- tsconfig
```json
    "paths": {
      "foo": ["./path/to/foo"],
      "bar": ["./path/to/bar"],
```
- package.json
```json
  "dependencies": {
    "hello": "1.0.0",
    "world": "1.0.0",
```

- editor typing
```ts
import {} from "<Cursor></Cursor>"
```

Actually: get completion candidate
- hello
- world

## 💻 Use Cases

Not sure whether tsconfig.compilerOptions.paths have higher piority than packageJson.XXXDependencies.

If it does

Expected: get completion candidate
- foo
- bar
- hello
- world

If it does not

Expected: get completion candidate
- hello
- world
- foo
- bar

### Related
https://www.typescriptlang.org/tsconfig#paths

https://github.com/microsoft/TypeScript/issues/43326

**Comment by RyanCavanaugh** [comment]
The actual contents on disk of all these folders matters. Can you set up a sample repo?

**Comment by loynoir** [comment]
@RyanCavanaugh 

> The actual contents on disk of all these folders matters. Can you set up a sample repo?

Emm, not folders, I use `tsconfig.compilerOptions.paths` like importmap.

```json
    "paths": {
      "foo": ["./path/to/foo.mts"],
      "bar": ["./path/to/bar.mts"],
      "importId": ["./path/to/file.mts"]
```

Background:

1. I use `deno + importmap` for a while, and feel this way impressively neat and elegant, compared to `node.js + package.json + monorepo + packageManager`.

2. But some library is not yet well supported in `deno`, so I try to use `node + tsconfig.compilerOptions.paths` as `deno + importmap` workaround.

3. `node + tsconfig.compilerOptions.paths` has problem, importId completion candidate does not include keys of `tsconfig.compilerOptions.paths`.
