### ISSUE TITLE
Typescript treats private members of a class differently when resolving from d.ts or from a ts file

### ISSUE THREAD

**Issue by GiladShoham** [microsoft/TypeScript#53558]
# Bug Report
Typescript will treat private members of a class differently if there is a d.ts file vs `types: index.ts` (when that same index.ts file is used to generate the d.ts file) in the `package.json`.

### 🔎 Search Terms

* Private members
* Types have separate declarations of a private property

### 🕗 Version & Regression Information
I believe this is a long-time issue.
But I still consider this as a bug and not an FAQ.
It's quite hard to reproduce in the playground. But I've created a full repro repo example (attached below)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
I tried to search for a long time, but didn't find almost anything about it.

### ⏯ Playground Link
https://github.com/GiladShoham/typescript-private-members-issue

### 💻 Code

Typescript will treat that private `fullName` differently if there is a d.ts file vs `types: index.ts` in the `package.json`.
So in such cases TS will consider them as mismatch types.
```ts
export type Name = {
  first: string,
  last: string
}

export class Person {
  constructor (public nickname: string, private fullName: Name){}
}
```

### 🙁 Actual behavior

Typescript will treat that private `fullName` differently if there is a d.ts file vs `types: index.ts` in the `package.json`.

### 🙂 Expected behavior

Typescript will treat private members from d.ts file and ts file (that is used to generate the d.ts) the same way.

**Comment by fatcerberus** [comment]
“Being treated differently” is really unspecific to the point of being unhelpful.  Please be more specific as to what’s actually going wrong.

If you’re referring to the fact that private properties are emitted in a `.d.ts` without a type, then that’s 100% by design - otherwise your public declaration files would have a hard dependency on types you might only use internally.

**Comment by GiladShoham** [comment]
> Being “treated differently” is really unspecific to the point of being unhelpful. Please be more specific as to what’s actually going wrong.

differently means that I have `person.ts` and `person.d.ts` (generated by tsc from `person.ts`, not manually)
and when I compare the 2 types they are considered different and ts giving me an error.

You can see in the repo I have attached all the details and steps to run.
I return from one function an instance of a person (where the person is coming from person.ts) and except to get in another function an instance of Person (where the person is coming from the d.ts of person.ts). and TS tells that the types are not match.
This happens because the types of the private member of person don't match, and they do not match because in the d.ts they are stripped but not in the ts.

It's fine to strip them on the d.ts. I would expect in that case that when TS compares types it will ignore types of private members even when the class type is coming from a ts file and not from a d.ts file.
As of now my ts file type has a hard dependency on the type I'm using internally.

**Comment by RyanCavanaugh** [comment]
> I would expect in that case that when TS compares types it will ignore types of private members

This doesn't work, since classes can access private members of other class instances of the same type.

**Comment by GiladShoham** [comment]
> This doesn't work, since classes can access private members of other class instances of the same type.

That's also true when my instance is based on the type of the d.ts.

How running tsc on a ts file produces different type?

**Comment by GiladShoham** [comment]
What I would wish is to be able to configure TS to ignore the types of private members when accessing it from a ts file.
Similar to what would happen if I would emit a d.ts file for it.
in that case, TS would compare 2 classes without the private member (like happen when both have d.ts) but without me needing to generate the d.ts before.
So treat person.ts as TS would treat it if there were person.d.ts (for private members)
Does this make sense @RyanCavanaugh as a feature request?

**Comment by MartinJohns** [comment]
It does not make sense. There's no difference between `.ts` and `.d.ts` files in this regard. In both cases the type is nominally typed, so incompatible with any other types, even if they match structurally. It's just that importing the type once from the `.ts` and importing it once from the `.d.ts` is considered different modules, so different types, meaning incompatible types (by design). That's the error you see in your example repository.

**Comment by GiladShoham** [comment]
@MartinJohns 
if I'm importing from 2 different places both with d.ts there is no error (see the working folder in my repo)
