### ISSUE TITLE
`transform-origin` isn't recognized

### ISSUE THREAD

**Issue by justingolden21** [microsoft/TypeScript#53552]
# Bug Report

### 🔎 Search Terms

"typescript transform-origin"

### 🕗 Version & Regression Information

Just added typescript to my project. Latest version.

### ⏯ Playground Link

Searched for a while on https://www.typescriptlang.org/play and couldn't find a way to add HTML, but if someone else wants to recreate or show me how to add HTML, I'm happy to reproduce there.

### 💻 Code

Inside an svg:
```svg
<text transform-origin="center" transform="rotate(30)" x="32" y="8">A</text>
```

### 🙁 Actual behavior

> Argument of type '{ style: string; "transform-origin": string; transform: string; x: string; y: string; }' is not assignable to parameter of type 'HTMLProps<"text", SVGAttributes<any>>'.
  Object literal may only specify known properties, and '"transform-origin"' does not exist in type 'HTMLProps<"text", SVGAttributes<any>>'.ts(2345)

### 🙂 Expected behavior

No error

**Comment by justingolden21** [comment]
![image](https://user-images.githubusercontent.com/30274440/228123123-fb290835-f499-4fee-a057-9ae5a5f0a2c9.png)

`transform-origin` is a valid property for `text` and without it my code does not work.

**Comment by fatcerberus** [comment]
I’m really confused; if this is in an `.svg` file then why does TypeScript care about it at all?  Because if it’s JSX, then the playground supports that.
