### ISSUE TITLE
Feature request: universal grammar for IDE highlighting

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript#5356]
Now [TypeScript-Sublime-Plugin](https://github.com/Microsoft/TypeScript-Sublime-Plugin) and [Atom-Typescript](https://github.com/TypeStrong/atom-typescript) uses the same typescript grammars for highlighting. [Atom-typescript grammar](https://github.com/TypeStrong/atom-typescript/tree/master/grammars) , [TypeScript-Sublime-Plugin grammar](https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/TypeScript.YAML-tmLanguage)
Do you have any plans to export/support typescript grammar as any external module?
Now IDE  support of new typescript features looks like [Formula 1](https://www.formula1.com/) :)

**Comment by DanielRosenwasser** [comment]
I think this would be the right thing to do going forward. The tmLanguage file should reside in its own repo (TypeScript-TmLanguage), and editors could use a git submodule snapped to a certain commit (or perform whatever other wizardry they need).

@billti @zhengbli @dbaeumer @basarat

**Comment by basarat** [comment]
:+1:

**Comment by zhengbli** [comment]
I agree, the united effort for syntax files should be much better.

**Comment by stepancar** [comment]
@DanielRosenwasser, @zhengbli  could you create repo TypeScript-TmLanguage? please?.Ii think, it should be MS repo.

**Comment by mhegazy** [comment]
:+1:  @zhengbli wanna do the honors.

**Comment by zhengbli** [comment]
We have some existing tests that are in the other repo, we'll figure out how to incorporate them together with a CI for the new repo before we create one.

**Comment by sgal** [comment]
Hi guys, do you have any update on this?

**Comment by mhegazy** [comment]
@zhengbli can we just create the repo and figure out the tests later?

**Comment by zhengbli** [comment]
Sorry for the delay. Yeah I'll create a repo for this tomorrow first. Pinging @DanielRosenwasser as he said he already has a repo related

**Comment by DanielRosenwasser** [comment]
[Your wish is my command.](https://github.com/Microsoft/TypeScript-TmLanguage)

**Comment by zhengbli** [comment]
![](http://www.reactiongifs.us/wp-content/uploads/2013/08/picard_clapping.gif)
