### ISSUE TITLE
Type '[...T]["length"]' is not assignable to type 'string | number | bigint | boolean | null | undefined'

### ISSUE THREAD

**Issue by Czh0716** [microsoft/TypeScript#53563]
# Bug Report

### 🔎 Search Terms
Template Literal Types

### 🕗 Version & Regression Information
This is the behavior in every version I tried, and I reviewed the FAQ for entries about type alias preservation

### 💻 Code

```ts
type ToStringLength1<T extends any[]> = `${T['length']}` // ok
type ToStringLength2<T extends any[]> = `${[...T]['length']}` // error 
```

### 🙁 Actual behavior

type conversion error

### 🙂 Expected behavior

no error

**Comment by RyanCavanaugh** [comment]
If the first one works, why did you write the second one?

**Comment by Czh0716** [comment]
Because I want to add a element on the basis of T and turn it into a string
```
`${[...T, unknown]['length']}` 
```
But ‘length’ does not look like a number，It needs `& number` to be normal

**Comment by ahejlsberg** [comment]
The issue here is that we don't compute constraints for generic tuple types (tuple types containing at least one variadic element) and therefore the type `[...T]["length"]` doesn't appear to have a constraint.
