### ISSUE TITLE
Forbid implicit types conversions for at least null and undefined.

### ISSUE THREAD

**Issue by socketpair** [microsoft/TypeScript#53566]
I need an option that forbids implicit conversion from `null` and `undefined` to other types.

Possibly in two flavors:
1. forbid all cases where JS will convert types 
2. forbid all cases where JS will convert types except implicit casting to `bool`

```ts
const qwe: string | null = null;
const asd: string | undefined = undefined;

console.log(`${qwe}`); // should fail
console.log(`${asd}`); // should fail
if (qwe !==null)
    console.log(`${qwe}`); // should NOT fail
if (asd !==undefined)
    console.log(`${asd}`); // should NOT fail
```

What common in all these cases? Automatic conversion to a string from some types should be forbidden. The list of such types should be configurable, and `null`/`undefined` should be in the list by default. Objects/Arrays—the same. Objects—except those who don't have `ValueOf` or other explicit convertors to string.

In general, I see only one case where implicit conversion should be allowed: `something -> bool`. Other cases are almost always are bugs. A possible exception is some logging code.

For example, in my project—it's not allowed to implicitly convert numbers to strings. Because locale-aware formatting is required. And also scientific form is not ok. 

Possibly all these things can be checked by ESLint ?

**Comment by Josh-Cena** [comment]
You are right that all these can be handled by ESLint.

- [restrict-template-expressions](https://typescript-eslint.io/rules/restrict-template-expressions/)
- [restrict-plus-operands](https://typescript-eslint.io/rules/restrict-plus-operands)
- [strict-boolean-expressions](https://typescript-eslint.io/rules/strict-boolean-expressions)
