### ISSUE TITLE
TypeScript incorrectly infers types without const assertion

### ISSUE THREAD

**Issue by tesseractjh** [microsoft/TypeScript#53567]
# Bug Report

### 🔎 Search Terms
readOnly, as const, const assertion

### 🕗 Version & Regression Information
5.0.2 and 4.9.5

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgHkAjAKyQwGklq4BeOAM4wowAHYBzOAB84ogK4gmSKNMHVFEADYUqtegHEkMACp6AJgDkUIJAAUUMABYAeY3CQAPGElFmBcCFZ2GAAaOAAhFAF6T29ffyIUMwhRTR5mNk5uAG0AXT44ROTUnjyAPgKAb3I4OGyOODE4AGtuCEw4Y1yALk76-NifPzgAQSgoFGpnMUxlOABVMprauAB+ZZWVmUMTcysbeydnebywopS0uoA6G8josI5cpc3NmQAKO5ivIf88tbgGjJziU6o84L1gZdsjcrp8HrkAJQbcF9MGDeKIdjQMzOIQiCRhOSiZqiCAAd1EzxW6xeWzgO1MdEs1jsDhcxn6Z1QxShMLhAKeyNecA+US+cWGf1WANUkNKYIh3IupT5YvhSM2vU+7m+GLyyOlgMKSpB-WRiqSyuutzVAooAF9sq1qO1OrkdDQ6PSjIykAAxHAgfaso7GMKLArzHUS-zO13GZbSjnzXLLXpR9HDOV1GZzBqZ2NtDpdROo1O1dPRn7Gy2m3MqfO64Zx4thGH1xDl-4ctFN-yBTIwA2IKsYhl7FmHdn9KmbaXjugB3DBqeuTmIWcrXqiJAAN2U5tke4PFaP+6gOl0Xr9EAgVWWTBQUF6TFvmlQogotUfAC9etVNhQbcFCUKA8i-FYmGAxRlAg2oAEc5A8f8hTgNBejxMRxDglYBDJYAYDQRwXzfD8cNqYjZDkTRtGRe0IPo8hGPIMRvCgTB0HoWwcDAARnGWNwC0xNBsVxYQsMJYlSQpMoQmWDM+29XYmRXNlXFk8gKjgAC4EwaAQF6YwIJgJ9xCMYN0wg4ABAANWs4AmHfXo3l3FBNDkJBegXf1A1U0NwzKBE+AqV8tDIpjKBE0QhDgABhFIzAI4AUjcm8oBAABJbw8H4VxR2GZARKgHFMIJOAiRJclKXDfL-G85kDjU4wyjKN4wB4gRem4iBeNcAKgt4CodNqIgYDkKBRComiHR0KKYpGAo3gGobljmrB9N6G8734Sp7TgKJyqkqr9v8LadFqNa4DANkvJ9CdGqOLaKn4bJ8F-fAwnwRCPA+gg8IIoj8HdVaUhi1z3M8pTfSXINJzUrawk9JBXWupxnt0tzolIOAAHocYCZoQeisKrk0CBxBctyPIRbG8YJygRqMcbJreZFnE3WpnHi3wkpSzQ0sy7LdP03hKj09K9pMqAzJgYNRdex8oCBvbrLsgQHPfUXKYh5bcYAKjgJxrIx4BNH8GA7yRxpRFmIhRDQegiqIDBLjeYwAGUACYAGZPc9oK9fx8GPL2nGObgLmEt50RUv0rKkDwcWQFFpPJdM8yWXlt6nyBk60NBmAVds+zHKQLXg6QXWcYNiBmjgQO4Ar0PN2cMPlhppiKCAA)

### 💻 Code

```ts
type Foo = {
  bar: boolean;
  baz: {
    a: number[];
    b: number;
    qux: {
      c: string;
      d: null;
    };
  };
};

type ObjectKey = string | number | symbol;

// "NamePath" is string array type that decribes path of nested object keys.

// ex)
// const validPath: GetTypedNamePath<Foo> = ['baz', 'a'];
// type Foo has key 'baz', and Foo.baz has key 'a'.

// const invalidPath: GetTypedNamePath<Foo> = ['bar', 'a']; 
// type Foo has key 'bar', but Foo.bar doesn't have key 'a'. So type error occurred.

type GetTypedNamePath<T extends object, Base extends readonly ObjectKey[] = readonly []> = {
  [K in keyof T]: T[K] extends Array<infer U>
    ?
        | GetTypedNamePath<U[], readonly [...Base, K]>
        | (Base extends [] ? K | readonly [K] : readonly [...Base, K])
    : T[K] extends Record<string, unknown>
    ?
        | GetTypedNamePath<T[K], readonly [...Base, K]>
        | (Base extends [] ? K | readonly [K] : readonly [...Base, K])
    : Base extends []
    ? K | readonly [K]
    : readonly [...Base, K];
}[keyof T];

// GetTypeFromNamePath can infer value of object key that is described on NamePath.

// ex)
// const namePath: GetTypedNamePath<Foo> = [''baz', 'qux', 'c'];
// type NamePathType = GetTypeFromNamePath<Foo, typeof namePath>; // expected to be string

type GetTypeFromNamePath<T, U> = U extends keyof T
  ? T[U]
  : U extends readonly [infer K extends keyof T]
  ? T[K]
  : U extends readonly [infer K extends keyof T, ...infer R]
  ? T[K] extends object
    ? R extends GetTypedNamePath<T[K]>
      ? GetTypeFromNamePath<T[K], R>
      : never
    : never
  : never;
```
```tsx
// React

interface Props<
  T extends Record<string, unknown>,
  U extends GetTypedNamePath<T>,
>  {
  form: T;
  targetName: U;
  isVisible: (value: GetTypeFromNamePath<T, U>) => boolean;
}

// Without const assertion, U is inferred as GetTypedNamePath<Foo, readonly []> 
const ConditionalFormItem = <T extends Record<string, unknown>, U extends GetTypedNamePath<T>>(props: Props<T, U>) => {
    return null;
};

const Page = () => {
  const form = {} as unknown as Foo;

  return (
    <>
      <ConditionalFormItem
        form={form}
        targetName={['bar']}
        isVisible={(value) => /* this fails to type inference correctly (TS2322) */ value} // value is not boolean
      />
      <ConditionalFormItem
        form={form}
        targetName={['bar'] as const}
        isVisible={(value) => /* ok */ value} // value is boolean
      />
    </>
  );
};
```

### 🙁 Actual behavior
Without const assertion, type inference of first argument of `isVisible` fails.
First parameter `value` of `isVisible` should be boolean (Foo.bar), but it is union type of every possible value(Foo.bar, Foo.baz, Foo.baz.a, Foo.baz.b, Foo.baz.qux, Foo.baz.qux.c, Foo.baz.qux.d).

### 🙂 Expected behavior
I added `readOnly` to Get- prefixed types to prevent type error.
But I expected that typescript could infer `value` type correctly without const assertion and `readOnly`.

**Comment by Andarist** [comment]
In 5.0 you can workaround this with:
```diff
const ConditionalFormItem = <
  T extends Record<string, unknown>,
- U extends GetTypedNamePath<T>
+ const U extends GetTypedNamePath<T>
>(
  props: Props<T, U>
) => {
  return null;
};
```

**Comment by tesseractjh** [comment]
@Andarist Thank you for your answer!

**Comment by RyanCavanaugh** [comment]
This repro is huge so it's hard to say, but this doesn't look like a bug, especially since `const` changes the behavior to the one you're expecting.
