### ISSUE TITLE
Rename from number literal key to string doesn't add quotes in element accesses

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#53569]
# Bug Report

### 🔎 Search Terms

rename number literal key string element

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about language services

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAbgQwDYFcCmEYF4YG8BQMRMADAFwxQBO6ANPgL776KoYDaJAugNxA)

### 💻 Code

```ts
const values = {
    0: true,
}

values[0];
```

To repro this bug, trigger _Rename Symbol_ on the `0` key (line 2), and rename to a string literal such as `abc`.

### 🙁 Actual behavior

```ts
const values = {
    abc: true,
}

values[abc];
```

### 🙂 Expected behavior

The `0` literal should be switched to either a string literal (`['abc']`) or the more succinct element access (`.abc`). I'd think preferably the latter.

```ts
const values = {
    abc: true,
}

values.abc;
```

**Comment by MariaSolOs** [comment]
Can I take this?

**Comment by jakebailey** [comment]
Yes! See also: https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#issue-claiming

**Comment by fatcerberus** [comment]
TIL the term "cookie licking"
