### ISSUE TITLE
Unions with overlapping methods with type guard returns incorrectly checked

### ISSUE THREAD

**Issue by SMJSGaming** [microsoft/TypeScript#53578]
# Bug Report

### 🔎 Search Terms

- Overload
- Union
- Type guard return

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type guards

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=9&jsx=0&ts=5.0.2#code/MYGwhgzhAECC0G8CwAoV0PQA4FcBGIAlsNAE4CmYAJgPYB2IAntAGY00D8AXNBAC6lCdAOYBuVOkzB6-UjmB8apABRtOPWUOEBKRJMyY+AC0IQAdGugBeVu3EoDAXwkPMAejfQASuT45SdDBg0HyMWOTQwjhgpFQh5CBEIiEwxmB8IUYRFH4B0KZw0ADuhMbQwSyEieRxQrwCWvrY+EQkfOT8yto8xgUF8ABkiLY0Gg3JjnquBhg5-nQhYeQ0LJmmFuzWNgBEmiLb9k6ozmgooJAwAEJTTR7eYHS0ALZMZL7zqXIRSqxgIBDkAA0axgpjoAHIMlgYnxiDhwKRXkJ2hR+I1ps0CMR4p1utA8OwQJQFsgMQY5nkALLpIxmUgPZ5daAAPmgAAYzABWQ6YE4nVB3anMeivfhKCLwIT8B7ADqoaSBDJgWCkemMHiwADaAF1rNAdfYBZ4vAyaC9mBTAoUftcIDRytAcHRCPRFuF8jBLTVUCwnQoXQswAB5UiXLoa6AAH2g11JBkIq2U1OMdNNTyZrI5nN0cZms3eeTo5CKcC6PIwkwSAKmefzuQWRZLYe05egfJcdwAKiZQTA6DQS-Bo5d5TIMqj4RkbMHQ2WXAnoMoJyA+GZ2ric7dPN2CsAHviIuRSllSNbT9c8DgMsYIqFwlEYnEVoUnmAANYdaCdgDKazob-yDI9wWEVmDwCUmmVVUwEYMxcAgIwlw6ScW2OIA)

### 💻 Code

```ts
class A {

    public readonly foo?: string;

    constructor(foo?: string) {
        this.foo = foo;
    }

    // Returns a type guard telling ts that the return is A with a filled in string
    public test(): this is A & { foo: string } {
        return typeof this.foo == "string";
    }
}

class B {

    // Randomly returns true or false, this isn't particularly interesting
    public test(): boolean {
        return Math.random() > 0.5;
    }
}

// May only store A instances
const aArray: A[] = [];

// Randomly returns A or B so a union type is returned
function aOrB(): A | B {
    if (Math.random() > 0.5) {
        return new A();
    } else {
        return new B();
    }
}

// This is now A | B
const result = aOrB();

if (result.test()) {
    // This can be either A or B but the typeguard of A makes TS think it can only be A
    aArray.push(result);
}
```

### 🙁 Actual behavior

When the test method is run in an A | B union, the type guard of A makes TS see the union as only A even though it has no way of garanteeing that due to the overlap.

### 🙂 Expected behavior

That TS won't consider the typeguard return as valid when there's a possibility that it's not checking a typeguard due to overlapping methods within a union.

**Comment by RyanCavanaugh** [comment]
`A` and `B` are mutually assignable to each other, so this is the intended behavior.

Note that this is also OK, for the same reason
```ts
// This is OK
aArray.push(new B());
```

**Comment by SMJSGaming** [comment]
@RyanCavanaugh then this might've been a bad example, however, the case where I encountered this bug wasn't mutually assignable. And Typescript realized this the moment I turned the guard into a boolean.

**Comment by SMJSGaming** [comment]
Here's an [alternative example](https://www.typescriptlang.org/play?target=9&jsx=0&ts=5.0.2#code/MYGwhgzhAECC0G8CwAoV0PQA4FcBGIAlsNAE4CmYAJgPYB2IAntAGY00D8AXNBAC6lCdAOYBuVOky4CxMpVoNmbGgCEwpHnnYhKdcWhSZowev1I5gfGqQAUy7rwFDhASkSSjGPgAtCEAHTK0AC8rOz6npg+foHsaqQh0HyMWOQ0LGE0IaEARDh0VOQsQuRUORGYAL4ShpgA9HXQAErkfDikdDBgSSnk0MI46lRJ5CBEIkkwPmB8Sd59FG0d0H5w0ADuhD7Q3cVjpSt0joIiHtj4RCR85Pw2LjzutZGL7UfRAcrxFRjVKL+ooEgMBUjzO0kucmo9CY0Dw6k02l0+jOJk6AgsVlscISoRYYBAEHIbmQT087382MS2O+0H+pPBsmut3usMRYCOJMiGBey3J1LOvzpDWgAFkwMxocx+NY+vAhPx2cAbgDTLMwLBSKRxTxYABtAC6iQNyJQwqa7NoAFsYTzOmtrNAQRAst18oR6D1UisYLbSqgWPlLO6jmAAPKkFR3HXQAA+jseRkIGRsYp8-i1BRolru0AAfNAAAz+ACsxLORlt0Do5HWcDuNMq0FGhITXMr1drkZcDdQQsaABVfDBVnQaLX4HGVCq0XIIDgQLNQmGI-WaknoDYKHOF-4mXw7mXScLB6tgOzYX1yFt5gl4A6QXgcLMfH1kqkBkNoOk1pawABrG5oH7ABlOYhD-FZZjPI5JQvOAznVTVxX8XAIG8TcbnnPhu17IA) which demonstrates this behavior.
