### ISSUE TITLE
vscode enters into "Initializing JS/TS Language Services" loop in our repo

### ISSUE THREAD

**Issue by hasanayan** [microsoft/TypeScript#53574]
vscode enters into "Initializing JS/TS Language Services" loop in our repo and this slows things down and I am reloading the window or restarting the TS server every 15 minutes or so

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.76.2
- OS Version: MacOS 13.2.1

Steps to Reproduce:

Unfortunately, it is not possible to provide a way for you to reproduce this issue as it requires a big monorepo as we have and I can't share our repo as it would mean exposing the client's IP.

However, I'd be more than happy to share non IP info on our repo that would lead us to find the cause of this issue. Here is some initial info;

- We have a monorepo managed by Nx with ~45 libraries in it
- We are not using the default typescript config that comes with Nx because we had to implement TS Project References to speed up type checking
- Almost all of our libs are also using project references to separate the actual source files and test files so that our spec files has jest type included

Here is our tsconfig files;

`<repo-root>/tsconfig.base.json`: this file includes the base settings, the other tsconfig files extend this config file.

```{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "outDir": "tsc-out",
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "baseUrl": ".",
    "composite": true,
    "declaration": true,
    "declarationMap": true,
    "disableSourceOfProjectReferenceRedirect": false,
    "emitDeclarationOnly": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "incremental": true,
    "jsx": "react-jsx",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": false,
    "noEmitOnError": false,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": false,
    "resolveJsonModule": true,
    "rootDir": ".",
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "target": "esnext",
    "types": ["node"],
    "useUnknownInCatchVariables": false,
    "paths": {
      ....
    }
  },
  "exclude": ["node_modules", "tmp", "tsc-out", "dist"]
}
```

`<repo-root>/tsconfig.json`: this is the root tsconfig file that extends tsconfig.base.json and references the lib tsconfig files

```{
  "compilerOptions": { "module": "CommonJS" },
  "extends": "./tsconfig.base.json",
  "files": ["jest.config.ts", "jest.preset.js"],
  "references": [
    ....
  ]
}
```

in each library we have;

`<library-root>/tsconfig.json`: extends `tsconfig.base.json` and references `<library-root>/tsconfig.json` and `<library-root>/tsconfig.spec.json` and sometimes tsconfig file in the <library-root>/.storybook folder

```
{
  "extends": "../../tsconfig.base.json",
  "files": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    },
    {
      "path": "./.storybook"
    }
  ]
}
```

`<library-root>/tsconfig.lib.json`: includes the actual source files and excludes the files that are supposed to be included by other tsconfig.json files within the library

```
{
  "exclude": [
    "src/**/*.spec.ts",
    "src/**/*.test.ts",
    "src/**/*.spec.tsx",
    "src/**/*.test.tsx",
    "src/jest-setup.ts",
    "jest.config.ts",
    "src/test-utils/**/*.ts",
    "src/test-utils/**/*.tsx",
    "src/**/*.mdx"
  ],
  "extends": "./tsconfig.json",
  "files": [
    "../../node_modules/@nrwl/react/typings/image.d.ts",
    "../../libs/ui-theme/src/typings/styled.d.ts"
  ],
  "include": ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"],
  "references": [
 ...
  ]
}

```

`<library-root>/tsconfig.spec.json`: includes the test files and excludes the files that are supposed to be included by the other tsconfig.json files within the library

```
{
  "compilerOptions": {
    "module": "commonjs",
    "types": ["jest", "@testing-library/jest-dom", "node"]
  },
  "extends": "./tsconfig.json",
  "include": [
    "jest.config.ts",
    "src/jest-setup.ts",
    "src/**/*.test.ts",
    "src/**/*.spec.ts",
    "src/**/*.test.tsx",
    "src/**/*.spec.tsx",
    "src/**/*.d.ts",
    "src/test-utils/**/*.ts",
    "src/test-utils/**/*.tsx",
    "assets/**/*.json"
  ],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    }
  ]
}
```

If you wish to see some diagnostic outputs or logs, please direct me to them so I can share them with you

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by hasanayan** [comment]
thanks, I am enabling the verbose logging and will provide the output
