### ISSUE TITLE
`bundler` moduleResolution ambient modules not resolving when omitting `.d.ts`

### ISSUE THREAD

**Issue by blake-newman** [microsoft/TypeScript#53575]
# Bug Report

### 🔎 Search Terms

module resolution bundler
bundler resolution d.ts
bundler resolution delcaration
bundler resolution module argumentation

### 🕗 Version & Regression Information

Version 5.0.2

Using `bundler` module resolution option doesn't seem to resolve `.d.ts` files unless the extension is defined. 

This seems to affect 3rd party libraries running module argumentation, such as pinia onto the Vue options.

https://github.com/vuejs/pinia/blob/v2/packages/pinia/src/globalExtensions.ts

In the `node` module resolution it will resolve the module declaration with `.d.ts` automatically. 

### ⏯ Playground Link

Reproduction repo created here: https://github.com/blake-newman/typescript-bundler-d-ts

In the `correct` folder the ambient module declaration works with `.d.ts`

<img width="461" alt="Screenshot 2023-03-29 at 22 20 04" src="https://user-images.githubusercontent.com/7272211/228670502-e48ccf17-3f5d-4616-b4c8-46ffab96dfdc.png">

In the `error` folder the ambient module declaration is not working when the `.d.ts` is ommitted 

<img width="707" alt="Screenshot 2023-03-29 at 22 19 51" src="https://user-images.githubusercontent.com/7272211/228670619-088a9f61-7d24-418e-a005-d7a7bc46d034.png">

### 🙁 Actual behavior

Ambient modules are not resolved to corresponding `.d.ts`

### 🙂 Expected behavior

Ambient modules to resolve to the respective `.d.ts` file

**Comment by DanielRosenwasser** [comment]
I don't know specifically what is going on - I did notice that these all apply to Vue 2.x in the repro, and that doesn't currently seem like it's "friendly" to `node16` and `bundler` resolution modes.

From https://arethetypeswrong.github.io/ :

<html>
<body>


  | "vue" | "vue/compiler-sfc" | "vue/dist/*" | "vue/types/*" | "vue/package.json"
-- | -- | -- | -- | -- | --
node10 | ✅ | ✅ | ❓ Unable to check | ❓ Unable to check | ✅ (JSON)
node16 (from CJS) | 🐛 Used fallback condition | ✅ (CJS) | ❓ Unable to check | ❓ Unable to check | ✅ (JSON)
node16 (from ESM) | 🎭 Masquerading as CJS🐛 Used fallback condition | ❌ No types | ❓ Unable to check | ❓ Unable to check | ✅ (JSON)
bundler | 🐛 Used fallback condition | ❌ No types | ❓ Unable to check | ❓ Unable to check | ✅ (JSON)


</body>
</html>

**Comment by blake-newman** [comment]
Makes sense; just read more into the exports details. As such I think this may be a non issue but downstream packages need to correctly set exports.

Will close for now, and reopen if discover that updating downstream packages still does not fix.
