### ISSUE TITLE
Proposal: Typing for 'alias-extending' another type

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript#5357]
ES6 introduces the concept of a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). I assume that, when supported by anything, TypeScript will implement these as `Proxy<T>` -- this object can then be used to access any property of the proxied object with the default configuration.

Defining `Proxy<T>` and keeping static typechecking doesn't appear to be possible with the current type system. I encountered this issue polyfilling a restricted version of the `Proxy` object called `Handle<T>`.

I have no idea what sort of syntax would be effective for a feature like this, but I would imagine something like:

```ts
class A {
	foo: string;
}

class B<T> {
	[key: string] in T;
	bar: string;
}
```

Here, `A` has a single property, and `B<A>` has type signatures for all types in A without actually implementing them. This would be the case for a `Proxy<T>` implementation as well.

Interfaces are not sufficient as they require the type to be known at definition time, and it would require the actual members to be inlined into the class.

Further questions that might be important to ask include:
- Does a `Proxy<T>` pass as `T` if it shares a signature?
- What other syntax would be reasonable for this?

**Comment by mhegazy** [comment]
@LPGhatguy can you share a sample where you are defining and using the Proxy..

**Comment by LPGhatguy** [comment]
Well, here's how I imagine using an ES6 Proxy would be in TypeScript:

```ts
class Model {
	foo: string;
}

let myModel = new Model();
myModel.foo = "hello";

// Proxy<Model> has all properties of Model
let myProxy = new Proxy<Model>(myModel, {});
myProxy.foo; // "hello"

myProxy.foo = "world";

myModel.foo; // "world"
```

**Comment by ahejlsberg** [comment]
Generally a proxy just has the same type as its target because it acts as a type compatible substitute. In other words, it is not visible in the type system. There is no `Proxy<T>` type, but rather just `T`. In cases where a proxy adds additional properties to an object, you can use the `&` intersection type operator to model it, for example:

```typescript
interface ProxyProps {
    foo: string;
    bar: string;
}

function createProxy<T>(target: T): T & ProxyProps {
    // Implement proxy that provides foo and bar properties
}

var p = createProxy({ x: 10, y: 20 });
p.x;    // number
p.foo;  // string
```

**Comment by mhegazy** [comment]
> Well, here's how I imagine using an ES6 Proxy would be in TypeScript

@LPGhatguy `Proxy` is defined the same way you mentioned in lib.es6.d.ts (see https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L5049); so this should work today as you describe.

**Comment by LPGhatguy** [comment]
Neat, alright. That combined with the intersection typing suggestiom by @ahejlsberg should work just fine.

Thanks!
