### ISSUE TITLE
Typescript 5.0.2 new decorators incorrectly set redeclared variables to undefined instead of inheriting the parent class value

### ISSUE THREAD

**Issue by blayzen-w** [microsoft/TypeScript#53588]
# Bug Report

Typescript 5.0 decorators seem to be incorrectly setting overridden variables that are just being redeclared in a child class to undefined, even when the decorator is empty. This functionality differs from how the standard javascript class work if it didn't have the decorator.

### 🔎 Search Terms

decorators

### 🕗 Version & Regression Information

This first appears in 5.0.2 with the new decorator format.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&noImplicitThis=false&ts=5.0.2#code/FAMwrgdgxgLglgewgAgCYFMoAoCUyDewyxyATujGKSuNPElgqXAOZwQCGANgPoC2FABYJUALmQcIATwA0yKEhjoAHjHEBhLhwDO2gGJx0XVABFMTDjCbrFKmHkJESAX2CvgwKFt3I9CBADqcDCCZgqklkwETsQAAhjYODHIStpqyGnMECzIALzIAOTswQUA3G4eXjrayABCHKRBIWEWVqTIdugQqDV+gcGh5hFt0STI8Zi4yQgAbuikzBgp6Gnl7lU+fQHwwmAwLcNRhGOp6ZnsOflFECVrld419Y0DCHsHke2d3b3+23C7+yGH1GJFm80W6GWqwqwC4FAkeWQEHQAHc6g0moNwh9cOU4TBkAAjRHItFPTGvQHYtq4ypIbQIOEAOi4CBYWA4TNOeXyhK5K3spSAA)

### 💻 Code

```ts
function dec() {
    return function(original_method: any, context: ClassFieldDecoratorContext) {

    }
}

class Foo {
    @dec()
    test: string = 'init';
}

class Bar extends Foo {
    @dec()
    override test;
}

let f = new Bar();
console.log(f.test);
```
Unexpected result: the output is **undefined**.

```ts
class Foo {
    test: string = 'init';
}

class Bar extends Foo {
    override test;
}

let f = new Bar();
console.log(f.test);
```
Expected result: the output is **'init'**

```ts
function dec() {
    return function(original_method: any, context: ClassFieldDecoratorContext) {

    }
}

class Foo {
    test: string = 'init';
}

class Bar extends Foo {
    @dec()
    override test;
}

let f = new Bar();
console.log(f.test);
``` 
Unexpected result: the output is **undefined**

```ts
function dec() {
    return function(original_method: any, context: ClassFieldDecoratorContext) {

    }
}

class Foo {
    @dec()
    test: string = 'init';
}

class Bar extends Foo {
    override test;
}

let f = new Bar();
console.log(f.test);
```
Expected result: the output is **'init'**

### 🙁 Actual behavior

Redeclared variables with decorators are set to undefined when decorated.

### 🙂 Expected behavior

Redeclared variables with decorators should not set the value to undefined and match how the class would function without the decorator.

**Comment by fatcerberus** [comment]
This is the expected ES spec-defined behavior.  Your second example only does what you want because you haven’t enabled `useDefineForClassFields` and/or targeting an ES revision that supports classfields.

**Comment by blayzen-w** [comment]
Thanks for the quick response. This one really threw me for a loop since it differed from how the experimental decorators worked. The useDefineForClassFields option fixes this issue. Thanks again for your time and helping to develop an amazing language.

**Comment by fatcerberus** [comment]
> it's scary to think that might become a standard

Bad news: It already *is* the standard; that ship already sailed.  In an engine that supports native class fields, redeclaring a field in a subclass without an initializer of its own will set it to `undefined`.  ES decorators are ultimately unrelated as they are built on top of the already-standard behavior.

**Comment by blayzen-w** [comment]
That makes since and I appreciate the information. It's better to find out about it now so we can start planning for the future.

I know you don't have a crystal ball but do you foresee the false option for the useDefineForClassFields flag sticking around for a while? It's looking like that change will require a substantial rewrite of our codebase. Some of the things we are doing with experimental decorators and that flag set to false just don't seem possible anymore.

**Comment by fatcerberus** [comment]
Disclaimer: I’m not a TypeScript maintainer, I’ve just been hanging around for long enough to have an idea of how the project tends to be steered.

The flag will likely stick around for a while, but note that when you have `target: "es2021"` or later (I think; whichever one standardized class fields), it defaults to true because otherwise the compiler can’t emit native property declarations.  So future feature work will likely just assume the spec’d behavior, leaving `useDefineForClassFields: false` as an afterthought, just like what you see here.
