### ISSUE TITLE
Predicate returns never

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#53585]
# Bug Report

### 🔎 Search Terms

predicate

### 🕗 Version & Regression Information

- This is a crash No
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about predicate

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/C4TwDgpgBAqgdgazgewO5ygXigbyqSALigGdgAnASzgHMoBfAKAOgBVwIStd8PiByAIb8GUAD48WAgEYimjAMbI4ZKGHIQAJpQWDg0bAAoAboIA2AVwjF2kLhPhI0cAJTFTl6JS63OWAHy4jFAhUBrAFuQYANpC-AA0UPyyALoAdNQKlpqcJuZWaSwujPIAZhZwCsCUylCayADKyAC2EMAAFtQ0eZ42HCQuQaFQlKVQhgCE6lo6ehA9Vi6DOMHDoUoqwFAAIgCiAEIwAOLcHlara1AA9FfDAHoA-BcMzxuqe4cn2GcQzzdrjxKQA)

### 💻 Code

```ts
type Unknown = { type: string }
type Types = { type: 'a' } | { type: 'b' }

const predicate = (value: Types | Unknown): value is Types => {
    return ['a', 'b'].includes(value.type)
}

function doSomething(value: Types) {
    if (!predicate(value)) {
        const DEBUG = value
        //    ^? never - Expected here to be Unknown
    }
    const DEBUG = value
    //     ^? Types
}
```

### 🙁 Actual behavior

Type predicate gets 2 possible types `Types | Unknown` but returns never when it doesn't match the predicate.

### 🙂 Expected behavior

The type predicate always returns either type `Types` or `Unknown`.

**Comment by alesmenzel** [comment]
> You should type your value argument as Types | Unknown.

True, I was playing with the example and forgot to added back. The issue I have is how can I tell to TS that I know that when the type is Unknown, then in the other branches it must be the other Types. In the predicate function, I am checking whether the type is `a or b` and since there is no way to define Unknown type as `string except a | b` how can i distinguish between the types?

Here is a different example that might better illustrate the issue - I have just switched the check, now I check whether it is a `Unknown` type by checking the `type` is not one of the known values `'a' | 'b'`, so if it should return `Unknown`, but it returns `Unknown | Types`.

[Playground](https://www.typescriptlang.org/play?ts=5.0.2#code/C4TwDgpgBAqgdgazgewO5ygXigbyqSALigGdgAnASzgHMoBfAKAOgBVwIStd8PiByAIb8GUAD48WAgEYimjAMbI4ZKGHIQAJpQWDg0bAAoAboIA2AVwjF2kLhPhI0cAJTFTl6JS6OU6LAB8uIxQoVAawBbkGACEANpC-AA0UPyyALoAdNQKlpqcJuZWmSwujPIAZhZwCsCUylCayADKyAC2EMAAFtQ0hZ42HPawiH6uwWFQAPRTI07oIWGUFVCG6lo6ehD9Vi4uE5NhSirAUAAiAKIAQjAA4tweVouH07NhAHoA-M8MPz8zUAA0mNeJAoABaIK2Tg-Y6qS43e7YR4Qf5vD7fehAA)

**Comment by MartinJohns** [comment]
Your second example doesn't work, because **every** `Types` is **also** a `Unknown`. You can't say it's a `Unknown`, but not a `Types`. TypeScript can't represent such types.

**Comment by alesmenzel** [comment]
**Thank you for the quick response.** Are there any future plans to support such types or is this a limitation of the structural typing approach and cannot be done - in the case it cannot be done in the language as a feature, are there any suggestions/workarounds that could be used (given that I cannot change the input type `{ type: 'A' } | { type: 'B' } | { type: <some string I don't know yet> }`)? The type comes from an API that I don't control and which can add additional `{ type: ... }` which I want to handle as "unknown".

**Comment by MartinJohns** [comment]
> given that I cannot change the input type `{ type: 'A' } | { type: 'B' } | { type: <some string I don't know yet> }`

That is the very thing that's not supported. You can't have a `string`, except specific strings.

> Are there any future plans to support such types

There's an open issue called "negated types" for this, but it's years old and very unlikely to be supported anytime soon. But who knows, maybe Anders drops another feature-bomb on us in some starry night.

**Comment by fatcerberus** [comment]
> But who knows, maybe Anders drops another feature-bomb on us in some starry night.

This is how you identify people who have been hanging around the TS repo too long when they know about this 😄
