### ISSUE TITLE
Can contextual typing apply to merged declarations?

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#536]
Courtesy of @danquirk 

4.19 Contextual Typing says:
 
> Contextual typing of an expression e by a type T proceeds as follows:
·         ...
·         If e is an expression of a function type that contains exactly one generic call signature and no other members, and T is a function type with exactly one non-generic call signature, then any inferences made for type parameters referenced by the parameters of T’s call signature are fixed (section 4.12.2) and, if e’s call signature can successfully be instantiated in the context of T’s call signature (section 3.8.5), e’s type is changed to a function type with that instantiated signature.
·         Otherwise, e is processed without a contextual type.

Why do we have the restriction for 'no other members'? (as opposed to just no other call signatures). This section is for how to apply contextual typing in a case like:

```TypeScript 
map(identity, xs);
 ```

where identity is a function from T -> T. It's not clear why this should be invalid if for example identity is a fundule which has some additional static properties tacked on which wouldn't affect contextual typing.

**Comment by ahejlsberg** [comment]
We want to restrict the cases where we do this because it causes fixing of the type parameters, and therefore no further inferences for those type parameters.
