### ISSUE TITLE
Generic type arguments of callbacks are not being inferred from their return values

### ISSUE THREAD

**Issue by nicky1038** [microsoft/TypeScript#53603]
# Bug Report

### 🔎 Search Terms

generic, generics, type arguments, infer, inference, callbacks, argument functions, return value

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ page.

### ⏯ Playground Link

Please check the [Playground link with relevant code](https://www.typescriptlang.org/play?ts=Nightly#code/PTAEF5KzQZQSwLYAcA2BTU6AeBDFGoAFPAHagD2ATgCbpWgAuFoAzgBYUDuT7m6rVulIBjTBQBmvTMioVEGRAEoI0KAFgAUFsYBPZJljz0AYXnIKAV1I0AKvszg2jKmQDmoAD6hSlxACN6L1B-CgoMXFItLTJGeglcMVAAIQpsAB5bLGw4m1Y4YzMUKxt7AwA+UABvLVBQKnRcGgpSVF1QADdcVEt0AC5QWy0AX2jNCWsRRngW0DIOigBrdAAxROYqXQB9BPhUViIJAczs3Jp8o0RTcxK7B3KiFXBK2yUB1IzL6+LrO4rq2r1dCMSxUcg1TR1OpdHr9UASR6A0aaZFaECgACSoEWpG40gac3yuDYSDQmFY4Us01mZFAIlwQkoUkY7Hg+VYBhE8Ak8BEJII-DwArRYGSVLm5EQ7RE5gw2DpDMwWPppFxjDYnO57SyEmo0koVKCE1E1Ki40mpolC2Waym1G2XGoi1YJxwZwuhRuvzK6AeR2ITxebxSaXSXyKFm99wBkKBILBMahnW6vQGCKUSJGY3RAHV2O0WfRMGzQJEsFQ5Aw+A0APwhjK+AL0Spu4Tnevpaw47ikcoAOhFoAAggTCwTIu0GgyWvkuPneCWOFZUDRQAA5ADyWUdVEWNZipGtq3W9p2uD2B0eEEqAEYM9oH+i1FBQABZaiYGUC+U4fBk4giKgFBCAwzD6pYjL0kITzPuAg6vgWDKLISTAsLIFAdPAdCgBB9DssYoBXCyFCriyuDqiqITFoeSzoKuXDwCylCkJguBUG4fjCIwA6aOitiskS7GcaQ6olsSLjoOgAA0oBzkWyawvkkilqgqB0qyK4+CRAhsJwliaYEMmsLguhGZY-h6AYSlSDCvTWdI8AMMgbFcawPHokQhZAt0CqMou0yqYRH50rKOAyf44peYg57kFhjQoSybL3oOJgaTQDTkLidD5CqapURq6BcjydGlkS5BsVQJlMqAADiwj0LytgNOga7aQAtKwUmDoE9K4RKvDkb5mCFo5gygG49WuHyzmVURQRLvpq6BGwwKlYMAAKLkiV1vFgJEpF8KNPbqXsq5ZTpjqLVp6rLZZJXoQYVBtO5wCDkYMm0oW9oySIaVadlIVXctdA8ixq6YcSCR2ps8IWjMpD5LS1B0KBLATeqD1BJZ7h9rjg6432EXql5sjoJhVisG0oDZSIriBKu9CVglfDeRS5BzgWAnUxQOl5TuyHoIx1Y8bE8SJJgdUsVNTWSa1dCZJtGWMDJWStnkG1bYwlQQtCKZwrYO11LTjRxKlp0ZTWAwAEqNM0rS6COlW6OkmRm5pavtrYDyBrVk2Nc1cvoJkKtuzQ5TlFmD53YMAfaVbYSMJklROJLDUiDLLXaZ2pDdlwpAqxHD7GlM8Pc18iWkG4SdEICMqkDybgDBngfxxQide1owYLFh1SgMAABU3O823hHkXEDD92AqKaM05espXRA6wpqa97gAwAOS4OvoDDIbdJTqbaUZQMADagJ1FezzEEvSa2XCVSlhvW8ANwhBv-jb7v59Qsb5GmEfwhT7fyTJfSoi9gFJmXvfR+oBN7r1fv4d+68fobxEJ-CBdRhj3kgaAAAut-LBgJ8EojWnXVgjAlBAA)

### 💻 Code

Here is the shortest code example that shows the essence of the problem.

Though this small example can be easily rewritten in order to solve the problem, it is not always an option.
**Please visit the Playground link stated above for more details, and more complex example with the actual use case.**

```ts
type SomeCompoundType = string | number | boolean

interface Box<T extends SomeCompoundType> {
  readonly value: T
}

function invokeFactory_fails(f: <T extends SomeCompoundType>() => T): Box<SomeCompoundType> {
  return {
    value: f()
  }
}

invokeFactory_fails(() => 1) // error here
```

### 🙁 Actual behavior

```
Type '1' is not assignable to type 'T'.
  '1' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'SomeCompoundType'.(2322)
```

### 🙂 Expected behavior

`T` could be inferred as `'1'` or at least `'number'`, so that the code could work.
There are no other constraints and obstacles in this code that could prevent it from working.

**Comment by MartinJohns** [comment]
Your function `invokeFactory_fails` requires a **generic function** to be provided, but the function you provide in your last line **is not generic**.

You probably meant to write:

```typescript
function invokeFactory_fails<T extends SomeCompoundType>(f: () => T): Box<SomeCompoundType> {
  return {
    value: f()
  }
}
```

**Comment by fatcerberus** [comment]
This seems like a misunderstanding of how generics work.  Type parameters are inferred at the call site of a function, never at definition, so `f: <T extends U>() => T` means that `f` itself is expected to be a generic function and take a type parameter.  `() => 1` is not generic, it takes no type parameters and always returns a number.

You probably want to write this instead:
```ts
function invokeFactory_works<T extends SomeCompoundType>(f: () => T): Box<SomeCompoundType> {
  return {
    value: f()
  }
}
```

**Comment by fatcerberus** [comment]
Oops, got ninja'd by @MartinJohns.  That's new.
