### ISSUE TITLE
When verbatimModuleSyntax: true, allow an explicit isolatedModules: true

### ISSUE THREAD

**Issue by MuleaneEve** [microsoft/TypeScript#53601]
# Bug Report

The new `verbatimModuleSyntax` implies `isolatedModules`, which is fine. However, it also prevents us from specifying `isolatedModules: true` explicitly, which should also be fine.

This is an issue in a [Next.js](https://nextjs.org/) app because its build process will force "isolatedModules: true" to be present. [This issue has been reported on their side as well](https://github.com/vercel/next.js/issues/46509).

So it is currently impossible to upgrade a Next.js app to TypeScript 5.

### Existing bug reports

This issue was not taken into consideration:

https://github.com/microsoft/TypeScript/issues/53374
https://github.com/microsoft/TypeScript/issues/53160

### 🕗 Version & Regression Information

TypeScript 5.0

### 🙁 Actual behavior

`
Type error: Option 'isolatedModules' is redundant and cannot be specified with option 'verbatimModuleSyntax'.
`
### 🙂 Expected behavior

`verbatimModuleSyntax: true` should allow `isolatedModules: true`.

**Comment by fatcerberus** [comment]
> This is an issue in a [Next.js](https://nextjs.org/) app because its build process will force "isolatedModules: true" to be present.

I sure hope somebody picks up that phone, [because I called it!](https://github.com/microsoft/TypeScript/pull/53240#issuecomment-1467285767)

**Comment by GitMurf** [comment]
While we are waiting for the fix to be applied to v5.0.4 and released, is there a workaround to get this working? Is the only option to set `isolatedModules` to false until 5.0.4 comes out? Thanks!

**Comment by fatcerberus** [comment]
@GitMurf The workaround is to not have `isolatedModules` in your config at all, since `isolatedModules: true` is implied by `verbatimModuleSyntax: true`.  Setting it to false is actively contradictory and will not fix this error.

**Comment by GitMurf** [comment]
@fatcerberus thanks for the quick response! So you mean just remove (or comment out) the isolateModules from the tsconfig all together? And effectively then I will have the same settings via the verbatimModuleSyntax?

**Comment by fatcerberus** [comment]
@GitMurf Yes.  Behavior under `verbatimModuleSyntax` is a superset of `isolatedModules`.  That's why the current error message says the latter option is redundant.

**Comment by nyngwang** [comment]
@fatcerberus How did you know it's a superset? (this is sincerely asking as I'm beginner) I came from the docs: https://www.typescriptlang.org/docs/handbook/modules/guides/choosing-compiler-options.html#im-using-a-bundler.
