### ISSUE TITLE
Incorrect generic `infer`ence with "inherited" types

### ISSUE THREAD

**Issue by Mexican-Man** [microsoft/TypeScript#53623]
# Bug Report

### 🔎 Search Terms

Generics, inheritance, nested.

### 🕗 Version & Regression Information

All versions tested, up to 5.1.0-dev.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230401#code/C4TwDgpgBACghgJwgO2AFXBAjAHjVCAD2BQBMBnKZAVwFsAjCBAPigF4prkBrZAewDuyANwBYAFChIsRCnSYATHgLEylGgyasOaMeIlToAYQAWASwA2pDJCzsZSVDew4ArMz2Gopy9cX34R3lIJXc9A0woAHEIdFw0bSh8IhJkCgc5Z1wzZAAzJigAVVYAfiKoAC4qCAA3JmEoCOkY9CUE+2TVNMpAzMUcHPyEItLyquRa+sb9SUi0CHJgOw4WtFwfKyyPCQB6HagDgD0Spuh5xYV7VaUNvxDt8T2DqGOgA)

### 💻 Code

```ts
type ParentType<T extends number> = unknown;
type ChildType = ParentType<5>;
type GetT<T> = T extends ParentType<infer U> ? U : never; 

type Test = GetT1<ChildType1>;
```

### 🙁 Actual behavior

Type `Test` is equal to `number` rather than `5`.

However, if `T` *isn't* unused in `ParentType`:

```ts
type ParentType<T extends number> = T;
// or
type ParentType<T extends number> = Array<T>;
...
```

–then `Test` becomes `5`.

### 🙂 Expected behavior

`Test` should be `5` in all cases.

**Comment by fatcerberus** [comment]
Working as intended.  Inference is done by working backwards structurally.  If you don’t use the type parameter then TS won’t be able to recover it through inference and you’ll just get the constraint, as you see here.

I should note that from TS point of view any `ParentType<T>` is also *assignable* to any `ParentType<U>`, for all `T` and `U`.  This is the nature of structural typing.

**Comment by fatcerberus** [comment]
By analogy, you’re essentially asking TS to solve `x * 0 = 0`.  You can substitute any number for `x` and still have a valid solution.

**Comment by Mexican-Man** [comment]
I see. Is there a way to include `T` in `ParentType` such that it does exist as a valid constraint? I can't think of a way to work around this, assuming that `ParentType` *is* actually independent of `T`.

From what you're saying, it seems like passing `T` up through (potentially many cascading types) and including it in the base type is the only way to do this. Is that right?

**Comment by fatcerberus** [comment]
If `ParentType` is actually independent of `T` then the type parameter may as well not exist.  It won’t affect the type.  Think of it like the type equivalent of `(x: number) => 0`.  Once you’ve called the function, you can’t recover `x` - but it doesn’t really matter because the results are all interchangeable anyway.
