### ISSUE TITLE
`typeof` operator narrows output when input types are known

### ISSUE THREAD

**Issue by dustin-rcg** [microsoft/TypeScript#53622]
# Suggestion

## 🔍 Search Terms

typeof

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKuEHkBmAeGA+KBeWUIA9gIA7AEwGcoAjASwHMbjgoB+KAcloafagC4AsACgouAkTKUqAe2kAbCAENirDjPlLi7QSLGESFKADEArsQDGwGtJVt2SM5etadomHn2SoxEwFsqEABOquw+-kHawm4eEobSVABWEJYh8UmWkbru4gaU5MCBjHQh+YXEdJnROV7kIP7yJXUycpV6sZRmpBBIjBCkIZ3dvaStnPSMwLwAPmqyCsrTHA4WVjaLoX4BgetpyZNQM+ylReu19S0HHIM9xH3sANzCT0LLTjZQoJDIaOgAFPh8WAASkBcC+qAwUAA3lEoIEIMATIEVJ8INIkFB8FBFJQwYgIehHkIAL7PAD0ZKgr1WKnkpDx6P+gPU8xUMzCW0ux3KIKgACJuXQ+Zc+RygsKZnyuBMJfyWZpZQKmvJFddhordpZFdTnHzhDr3nSGUgmdQ5ppLmLgjNBUDobDRPDEciPvB0ZiiaShMIKVTHDTvBAAO7G03y5SWzZBLkFIq8gWx8qKq2K8PEPUvf3OQMht0mgFmjQR9lR61QW323SOhFIlHwZD-IGe8mU8w2fJQRhdIiBXyMRREQEJspCkUpkXSpip83KRVnZqqshDW6kDWJPbarM2DNt4gdrsIoJ94gD6A4VENvnCnFQMwAa2I0iDxCbz1RUAAsoowGBFFQFNghaspG4RloKlwACKnkSwi7h2H4AIIAAoAMqATCVZAZogJhjOL7YJgADaKHKnIAB0SDSIEvzsAAQggCAADIAKIIQAcuwQIADSYgAulxDreKWOEFladpYERJHnBRVE0WxACqH60cxABKnE8fg-GCYKImAhWElQMRpEydR7AoTAKkAJJsQA4upfECZhpCnrpUBQUQ4mScZlGmRBCEwMx9macIxLYpQcHADBmYrNmdI2QijF-hAciml+P5-godoYaIog0Bi-ydnuwDKOYaIYu5EB2k6tYcM5RAPIJ1Uuqi7r4M2QgRVAcUImlgGpd+v7-pVBGfshKGEd1wCJQEKX4ECvFRQaKi3EG8VTUls2Amlg2ZZWOWdvlWKMPkJVlW5p5VTWLrsHVEANZhTV1uCjbtZ1K1rb1OD9elQ2eaNqGEe9CUbY2C1AA)

I would like to see the `typeof` operator be typed as the following `typeOf` function:

```
type TypeOf<T> = T extends bigint ? 'bigint' :
  T extends boolean ? 'boolean':
  T extends Function ? 'function':
  T extends number ? 'number':
  T extends object ? 'object':
  T extends string ? 'string':
  T extends symbol ? 'symbol':
  T extends undefined ? 'undefined':
  'bigint' | 'boolean' | 'function' | 'number' | 'object' | 'string' | 'symbol' | 'undefined';


function typeOf<T>(x: T): TypeOf<T> {
  return typeof x as TypeOf<T>;
}

// function oldTypeof(x: boolean | number | string): "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"
function oldTypeof(x: boolean | number | string) {
    return typeof x;
}

// function newTypeof(x: boolean | number | string): "string" | "number" | "boolean"
function newTypeof(x: boolean | number | string) {
    return typeOf(x);
}

// const indeterminate: "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"
const indeterminate = typeOf("" as unknown);
```

## 📃 Motivating Example

```
type Mappable = boolean | number | string | Date;

const MAPS = {
    boolean: (x: boolean) => [Symbol.for('BOOLEAN'), x],
    number: (x: number) => [Symbol.for('NUMBER'), x],
    string: (x: string) => [Symbol.for('STRING'), x],
    date: (x: Date) => [Symbol.for('DATE'), x]
} as const;

function oldGetLabel(x: Mappable) {
    if (x instanceof Date) return 'date';
    return typeof x;
}
const oldGetMap = (x: Mappable) => MAPS[oldGetLabel(x)]; // <-- Typescript error here

function newGetLabel(x: Mappable) {
    if (x instanceof Date) return 'date';
    return typeOf(x);
}
const newGetMap = (x: Mappable) => MAPS[newGetLabel(x)]; // <-- No error here
```

## 💻 Use Cases

I am working on a builder class that is essentially used to build an AST. Many of the methods have overloads that take primitive types or builtin types (like Date) and map these to tagged AST nodes of the appropriate union type for the method input. The type cases are broken out as separate functions, because some of the union types are subtypes (sub-unions) of the most general supported mapping from primitive/builtin to AST node. This allows me to write a function that has properly typed (narrowed) input parameter based on the specified return type. 

Generally, this is implemented with a helper using `typeof`.  I end up doing handwaving inside the helper, due to typescript essentially widening the output of `typeof` into all possible primitive types, when it already has enough information to narrow the output type. I would not expect typescript in general to do this input-output type analysis on any function, but I feel that `typeof` should be a special case, because it is so frequently used, for example, to implement function overloading.

I am currently using the above `typeOf` helper and `TypeOf<T>` type, but it shouldn't be necessary to avoid using the builtin `typeof` everywhere. This change would be helpful to others for similar reasons.

**Comment by fatcerberus** [comment]
This doesn’t seem feasible because in general there’s not a consistent mapping between TS types and `typeof` results.  For example `{}` might be a primitive or function, but your `TypeOf` helper says it’s always `"object"`

**Comment by RyanCavanaugh** [comment]
I can't find the duplicate, but this was previously discussed and rejected. The *sound* version of this isn't particularly helpful and produces results that would be extremely surprising, e.g.
```ts
class Foo {
  static x = 1;
}
function fn(a: { x: number }) {
  // m is "function" but this is so surprising that
  // we'd get daily bug reports complaining about it
  const m = typeof a;
}
// Legal call
fn(Foo);
```

**Comment by fatcerberus** [comment]
@dustin-rcg That’s ultimately a consequence of the structural typing.  All that is true for, e.g. `{ toString(): string }` too, which I think most people would agree *should* be assignable to `object`.

> Wouldn't that [an object possibly being a function] be a basic concept that people need to understand?

You’d think so, but people still regularly write `typeof x === 'object' && x !== null` to check for objectness, so…
