### ISSUE TITLE
Misleading "implementation is missing" error when param type predicate missing 'is' type

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#53629]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type predicates

### ⏯ Playground Link

~[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwM6oKYCcoAoBuyANiBgFyLgDWYcA7mAJQVqY6qKEkaIwcDeAXyA)~ ~[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwM6oKYCcoAoBuyANiBgFyLgDWYcA7mAJQVqY6qKEkaIwepQsMMAHMgA)~

### 💻 Code

```ts
function assert(value: unknown): asserts value is {
    console.log("");
}
console.log("");
```

### 🙁 Actual behavior

That error message looks to be a generic _failed to parse function_ one.

### 🙂 Expected behavior

Maybe...

```ts
function assert(value: unknown): asserts value is string
    //                                         ~~
    // Type predicate missing a type after 'is'.
    console.log("");
}
console.log("");

```

**Comment by fatcerberus** [comment]
It's not really missing a type though (according to the grammar) - it's literally `asserts value is {}` (i.e. the type `{}`), so the parser is expecting to see `asserts value is {} { ... }` and therefore it's missing its implementation.

You'd get the same error if you wrote e.g.
```ts
function assert(value: unknown): asserts value is string
```

> That error message looks to be a generic *failed to parse function* one.

No, it's a "you wrote a set of overload declarations without an implementation" error.

**Comment by JoshuaKGoldberg** [comment]
> not really missing a type though

Haha, good point. Updated the OP to mention 

> No, it's a "you wrote a set of overloads without an implementation" error.

Not to quibble, but I was still technically accurate, just not precise. It is **_a_** generic _failed to parse function_ error. _"you wrote a set of overloads without an implementation"_ is also generic function parse error - just a more precisely relevant one. 😛

**Comment by fatcerberus** [comment]
> Not to quibble, but I was still technically accurate, just not precise. It is a generic failed to parse function error. "you wrote a set of overloads without an implementation" is also generic function parse error - just a more precisely relevant one. 😛

Now I'm really confused - when you say "a generic failed to parse function error" I'm interpreting that as "this error is produced any time the compiler can't parse a function"

**Comment by fatcerberus** [comment]
At any rate the expected behavior still seems wrong, since you could have written:

```ts
function assert(value: unknown): asserts value is string
function assert(value: unknown): asserts value is number
```

in which case it would be weird to say you forgot the type.  Clearly this is two complete function signatures and you're just missing an implementation for the overload set.

**Comment by JoshuaKGoldberg** [comment]
```ts
function assert(value: unknown): asserts value is string
console.log("");
```

**Comment by fatcerberus** [comment]
I'll agree that in that last example it's unambiguously missing a type (might be ambiguous to the parser but that's what bug reports are for :)  Your earlier examples are trickier because parsing hadn't actually failed - it successfully parsed an overload declaration.
