### ISSUE TITLE
Token dependency injections arent't working after update vs code to 1.77.0

### ISSUE THREAD

**Issue by Mauro-Domingues** [microsoft/TypeScript#53639]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.0
- OS Version: Windows 10 Pro 22H2
- node Version: 18.15.0
- tsyringe Version: ^4.7.0

Steps to Reproduce:

1. registerSingleton using container from tsyringe
```typescript
// contaner.ts
import { container } from 'tsyringe';

import ICategoriesRepository from '@modules/categories/repositories/ICategoriesRepository';
import CategoriesRepository from '@modules/categories/repositories/CategoriesRepository';

container.registerSingleton<ICategoriesRepository>(
  'CategoriesRepository',
  CategoriesRepository,
);
```
2. import the container.ts on the main file
```typescript
// app.ts
import '@shared/container';
```
3. inject inside a constructor using a token
```typescript
// simple service example
import { injectable, inject } from 'tsyringe';

import ICategoriesRepository from '@modules/categories/repositories/ICategoriesRepository';
import ICategoryDTO from '@modules/categories/dtos/ICategoryDTO';
import Category from '@modules/categories/entities/Category';
import IResponseDTO from '@dtos/IResponseDTO';

@injectable()
export default class CreateCategoryService {
  constructor(
    @inject('CategoriesRepository')
    private categoriesRepository: ICategoriesRepository,
  ) {}

  async execute(categoryData: ICategoryDTO): Promise<IResponseDTO<Category>> {
    const category = await this.categoriesRepository.create(categoryData);

    return {
      code: 201,
      message_code: 'CREATED',
      message: 'Category successfully created',
      data: category,
    };
  }
}
```
Results:

1. Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'.ts(1239)
![image](https://user-images.githubusercontent.com/104386910/229132147-387741e2-d66f-4872-9d21-80cd874fddf7.png)

2. Errors when compiling using tsc cli
comand: 
```json
"build": "tsc && tsc-alias",
```

![image](https://user-images.githubusercontent.com/104386910/229134079-99079e0c-034d-4cfa-8bb1-ec912f1d722e.png)

3. the code works correctly and the api runs. The problems seem to be only visual.
- running directly in ts
![image](https://user-images.githubusercontent.com/104386910/229134814-54110581-04a9-445d-adf9-0f7bb6a6ab43.png)
- compiled with babel, tsc doesn't work anymore
![image](https://user-images.githubusercontent.com/104386910/229135578-9895dd9f-3494-428e-82ce-0c7b8fc1d172.png)

OBS. this is working on any supported version of typescript and tsyringe using any compatible version of vscode below 1.77.0

**Comment by mjbvz** [comment]
https://github.com/microsoft/TypeScript/issues/53651#issuecomment-1495003042 includes possible repo

**Comment by rbuckton** [comment]
This is the result of more accurate type checking for legacy parameter decorators in 5.0 and was mentioned in the breaking changes section of the announcement [blog post] (https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#more-accurate-type-checking-for-parameter-decorators-in-constructors-under-experimentaldecorators). A parameter decorator on a constructor parameter has always received `undefined` for the method name, but we were not reporting this correctly.

**Comment by Mauro-Domingues** [comment]
> [#53651 (comment)](https://github.com/microsoft/TypeScript/issues/53651#issuecomment-1495003042) includes possible repo

https://github.com/Mauro-Domingues/vscode-issue-53639

**Comment by jakebailey** [comment]
See: https://github.com/microsoft/tsyringe/issues/221

I think this issue can be marked as External.

**Comment by mhaslam-becklar** [comment]
I thought that VS Code used the version of TypeScript you have installed for your project. Is this not the case? If I still haven't updated my project to v5 of TypeScript yet. Shouldn't VS Code see that, and then I shouldn't be seeing this issue?

(My project is still using v4.8.4 of TypeScript, but I am seeing these same errors in VS Code v1.77)

**Comment by AmauryD** [comment]
I've got the same issue, project is configured for typescript 4.x but it throws typescript v5 errors. (see my previous comment)

**Comment by jakebailey** [comment]
> I thought that VS Code used the version of TypeScript you have installed for your project. Is this not the case? If I still haven't updated my project to v5 of TypeScript yet. Shouldn't VS Code see that, and then I shouldn't be seeing this issue?
> 
> (My project is still using v4.8.4 of TypeScript, but I am seeing these same errors in VS Code v1.77)

Run the "select typescript version" command from the command palette and you'll see what's in and be able to change it. The default is not to execute code from the workspace.

**Comment by zheeeng** [comment]
There are still reports of this error when running tsc above 5.0.

**Comment by jakebailey** [comment]
Correct, this is an intentional change in 5.0. The right fix is upstream in tsyringe, per the cross-linked issue.

**Comment by hasantezcan** [comment]
I still getting the same errors is there any updates about that topic?

**Comment by Mauro-Domingues** [comment]
> I still getting the same errors is there any updates about that topic?

It was an error inside tsyringe package and it has been fixed on last update, check <a href="https://www.npmjs.com/package/tsyringe">tsyringe^4.8.0</a>
