### ISSUE TITLE
Intersection types feature do not work in Visual Studio 2013 with Typescript Tools 1.6.2

### ISSUE THREAD

**Issue by mif007** [Microsoft/TypeScript#5364]
Example of code:
```typescript
function compose<T1, T2>(a: T1, b:T2):T1 & T2 {
	return <T1 & T2>a;
}
```
![iamge](http://i60.tinypic.com/2ahwsc4.png)

**Comment by danquirk** [comment]
Just installed the latest on clean VS2013 and don't see this. How did you install the plugin? You have a working version of the command line compiler that compiles this code without error?

**Comment by mif007** [comment]
I get it. Resharper 9.2 not support this feature yet.

**Comment by danquirk** [comment]
Glad you tracked it down. I'm sure they're aware but probably doesn't hurt to file something on their issue tracker.
