### ISSUE TITLE
New keyword to simplify declaration of readonly constants

### ISSUE THREAD

**Issue by AClotfelter** [microsoft/TypeScript#53644]
# Suggestion

## 🔍 Search Terms

- "as const" keyword
- readonly keyword
- immutable keyword

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A new keyword to simplify/clarify the declaration of `readonly` constants would be very useful. This could be syntactic sugar for an `as const` assertion, while being easier to write, and consume. 

I suggest `immut` as this new keyword; it is easy to type, but unmistakable.

Rationales for this:

- Make writing immutable/readonly code easier, by only having to type `immut` at the beginning of a declaration, vs having to write `const`...`as const` (fewer characters to type, more direct).
-  Communicate the intent/functionality in a clearer way:
  - More expressive; would only have to see the initial `immut` to instantly understand this is a `readonly` variable.
  - In longer object declarations, the `as const` assertion may be located far away from the initial `const` keyword; possibly even off screen.
- Would make it less likely that a desired `as const` assertion might be forgotten.
- Would provide the functionality generally desired by use of `const`, without any risk of breaking existing `const` code.
- Not a global change to functionality, or a global configuration change; codebases could implement as quickly, or gradually, as they like.
- Same number of characters to type as `const`.
- A new keyword would be more straightforward to learn/teach, vs an assertion.
- A new keyword would get more attention, and likely get more uptake.
- Should be straightforward to implement, yet yield many benefits.

## 📃 Motivating Example

It is difficult to see that this is a readonly object, without noticing the `as const`, below.

```typescript
const animals = {
  mammals: [
    { name: "Elephant", species: "Loxodonta africana" },
    { name: "Giraffe", species: "Giraffa camelopardalis" },
    { name: "Kangaroo", species: "Macropus rufus" },
    { name: "Panda", species: "Ailuropoda melanoleuca" },
    { name: "Whale", species: "Balaenoptera musculus" },
  ],
  birds: [
    { name: "Eagle", species: "Aquila chrysaetos" },
    { name: "Parrot", species: "Psittacus erithacus" },
    { name: "Penguin", species: "Aptenodytes forsteri" },
    { name: "Sparrow", species: "Passer domesticus" },
    { name: "Swan", species: "Cygnus olor" },
  ],
  reptiles: [
    { name: "Alligator", species: "Alligator mississippiensis" },
    { name: "Chameleon", species: "Furcifer pardalis" },
    { name: "Cobra", species: "Naja naja" },
    { name: "Tortoise", species: "Testudo graeca" },
    { name: "Komodo Dragon", species: "Varanus komodoensis" },
  ],
  amphibians: [
    { name: "Frog", species: "Rana temporaria" },
    { name: "Salamander", species: "Ambystoma mexicanum" },
    { name: "Caecilian", species: "Caecilia thompsoni" },
    { name: "Newt", species: "Notophthalmus viridescens" },
    { name: "Toad", species: "Bufo bufo" },
  ],
  fish: [
    { name: "Clownfish", species: "Amphiprioninae" },
    { name: "Salmon", species: "Salmo salar" },
    { name: "Shark", species: "Carcharodon carcharias" },
    { name: "Swordfish", species: "Xiphias gladius" },
    { name: "Tuna", species: "Thunnini" },
  ],
} as const;
```

This is unmistakable:

```typescript
immut animals = {
  mammals: [
    { name: "Elephant", species: "Loxodonta africana" },
    { name: "Giraffe", species: "Giraffa camelopardalis" },
    { name: "Kangaroo", species: "Macropus rufus" },
    { name: "Panda", species: "Ailuropoda melanoleuca" },
    { name: "Whale", species: "Balaenoptera musculus" },
  ],
  birds: [
    { name: "Eagle", species: "Aquila chrysaetos" },
    { name: "Parrot", species: "Psittacus erithacus" },
    { name: "Penguin", species: "Aptenodytes forsteri" },
    { name: "Sparrow", species: "Passer domesticus" },
    { name: "Swan", species: "Cygnus olor" },
  ],
  reptiles: [
    { name: "Alligator", species: "Alligator mississippiensis" },
    { name: "Chameleon", species: "Furcifer pardalis" },
    { name: "Cobra", species: "Naja naja" },
    { name: "Tortoise", species: "Testudo graeca" },
    { name: "Komodo Dragon", species: "Varanus komodoensis" },
  ],
  amphibians: [
    { name: "Frog", species: "Rana temporaria" },
    { name: "Salamander", species: "Ambystoma mexicanum" },
    { name: "Caecilian", species: "Caecilia thompsoni" },
    { name: "Newt", species: "Notophthalmus viridescens" },
    { name: "Toad", species: "Bufo bufo" },
  ],
  fish: [
    { name: "Clownfish", species: "Amphiprioninae" },
    { name: "Salmon", species: "Salmo salar" },
    { name: "Shark", species: "Carcharodon carcharias" },
    { name: "Swordfish", species: "Xiphias gladius" },
    { name: "Tuna", species: "Thunnini" },
  ],
};
```

## 💻 Use Cases

Extremely easy to implement in a codebase (and likely, in the compiler). The likelihood of problems, due to inadvertent use, would be very small, vs an approach that changes how `const` behaves. The ease of this approach would likely result in readonly objects being more common, which would be a net benefit for the language.

**Comment by jcalz** [comment]
You want `immut x =` in TS to compile to `const x = ` in JS, but that violates 

>  This isn't a runtime feature (e.g. library functionality, **non-ECMAScript syntax with JavaScript output**, new syntax sugar for JS, etc.)

So you should either uncheck that box (which is essentially grounds for immediate rejection) or change your proposal so that the only changes between TS and JS involve *erasure*.

**Comment by AClotfelter** [comment]
@jcalz @fatcerberus How is this different than the output of `as const`?

**Comment by AClotfelter** [comment]
@MartinJohns I would expect `immut` to behave the same.

**Comment by MartinJohns** [comment]
You would expect `immut` to compile to `const`. That's something different.

Besides that, I think they keyword is a **really** bad idea. "immut" strongly indicates "immutability", which is not the case. TypeScript can't represent immutability in its type system.

**Comment by AClotfelter** [comment]
@MartinJohns The specific keyword would be debatable, but I see usage of ...`as const` becoming more common, and I think we should have a keyword that removes the redundant wording, and above-mentioned challenges to readability that it introduces, without sacrificing the functionality.

**Comment by RyanCavanaugh** [comment]
You can't do it in JSX files, but if you want something that's closer to the declaration site, you can do this:
```ts
const animals = <const>{
  mammals: [
    { name: "Elephant", species: "Loxodonta africana" },
    { name: "Giraffe", species: "Giraffa camelopardalis" },
```

I don't think this scenario raises to the level of "need a new keyword"
