### ISSUE TITLE
`const type parameters` can't be used together with normal type parameters.

### ISSUE THREAD

**Issue by zhiyuanzmj** [microsoft/TypeScript#53655]
# Bug Report

### 🔎 Search Terms

`const type prarameters`

### 🕗 Version & Regression Information

- This changed after versions ___5.0___

### ⏯ Playground Link

[https://www.typescriptlang.org/play?ts=5.1.0-dev.20230403](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230403#code/C4TwDgpgBAEghgZwHJwLYQVAvFA3lAOzQwC4oAnCOAEwHsCAbEKBYcgSwIHMBtAXSgBfANwAoAGYBXAgGNg7elC4RgKdAgCiADzhymAHgCqUCFuAQC1THAIgANFBn1WUAComzFq7ERqM2H2RiBAA+AAo4ci4yVwBKGJ4AIiJ1RIFcUSgsqAB6HOyCwqKoAD0y8oryzOzKYElyAihIrgA6FIwxQVFRPKgASQJxCHJKaihQSDJKGnomFjZOXj5RJwIXdswcZVVg7V1gAxsQcPwNsiSAQQZ2GQhEh0SAIVoAI3uoRI0ANzu+QVixL1isCQdlykA)
### 💻 Code

```ts
type HasNames = { names: readonly string[] };
function getNamesExactly<U extends any, const T extends HasNames = HasNames>(arg: T): T["names"] {
    //                   ^^^^^^^^^^^^^
    return arg.names;
}

// Inferred type: readonly string[]
const names = getNamesExactly<any>({ names: ["Alice", "Bob", "Eve"]});
//                            ^^^
```

### 🙁 Actual behavior

`readonly string[]`

### 🙂 Expected behavior

`readonly ["Alice", "Bob", "Eve"]`

**Comment by fatcerberus** [comment]
Nothing to do with `const` and this is working as expected.  Generic inference is all-or-nothing.  Since you passed a type for `U`, `T` defaults to `HasNames` instead of being inferred from the call.

Refer to https://github.com/microsoft/TypeScript/issues/26242.

**Comment by MartinJohns** [comment]
> This changed between versions 5.0 and 5.1.0-dev

I don't see any difference between these two versions. Can you elaborate?

**Comment by zhiyuanzmj** [comment]
> 

`const type parameters` was added in TypeScript 5.0

**Comment by fatcerberus** [comment]
Yes, but you’re claiming the behavior is different between 5.0 and 5.1, which it isn’t.

**Comment by zhiyuanzmj** [comment]
> 

sorry, I changed
