### ISSUE TITLE
Question (another language based on TS)?

### ISSUE THREAD

**Issue by acterhd** [Microsoft/TypeScript#5365]
Hello. Can I have TypeScript as base for another language? 
I'm sorry for JSCL, this is unfinished version. I will work on compute language concept, based on Ecmascript (Typescript).

**Comment by RyanCavanaugh** [comment]
TypeScript is released under the Apache license (see https://raw.githubusercontent.com/Microsoft/TypeScript/master/LICENSE.txt), so you are able to make derivative works subject to the terms of that license.
