### ISSUE TITLE
`Blob` type is incompatible with node definition of `Blob`

### ISSUE THREAD

**Issue by jeswr** [microsoft/TypeScript#53668]
# lib Update Request

## Configuration Check

My config is the default config created by running `npm init -y && npx tsc --init`. No packages have been installed.

Node Version: v19.3.0
NPM Version: 9.6.2

## Missing / Incorrect Definition

The `Blob` type defined here https://github.com/microsoft/TypeScript/blob/e83d61398ea0e4231e882121dd6c6bcfe4fdc9e4/src/lib/dom.generated.d.ts#L3075 is not assignable to the `Blob` type in node here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ec8923e261d3619aef6a4663d50159e7e0dcf3e9/types/node/buffer.d.ts#L121 due to type applied to the `prototype`.

## Sample Code

```ts
import { Blob as BufferBlob } from "buffer";
const bl: Blob = new BufferBlob([]);
```

Causes the typescript compilation error

```
Property 'prototype' is missing in type 'import("buffer").Blob' but required in type 'Blob'.ts(2741)
lib.dom.d.ts(2591, 5): 'prototype' is declared here.
```

**Comment by fatcerberus** [comment]
The default config includes the DOM (i.e. web browser API) types; since you're targeting Node, you should install `@types/node` if you haven't already and then write a `lib` entry in your tsconfig that doesn't include `dom`.  It is known that the DOM types are incompatible with `@types/node`.

**Comment by RyanCavanaugh** [comment]
It sounds like this is a problem in the node .d.ts, not the DOM's.

**Comment by MartinJohns** [comment]
@RyanCavanaugh isn't this essentially the same as #52166?

**Comment by jeswr** [comment]
In light of [this response](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65049#discussioncomment-5559405) can this issue be re-opened and addressed as part of the 5.1.0 milestone along with #52166.

**Comment by jeswr** [comment]
@RyanCavanaugh ?

**Comment by jeswr** [comment]
@DefinitelyTyped can this issue please be re-opened per https://github.com/microsoft/TypeScript/issues/53668#issuecomment-1504245808
