### ISSUE TITLE
Object key type narrowing for a variable when using `in` operator

### ISSUE THREAD

**Issue by Lutymane** [microsoft/TypeScript#53679]
# Suggestion

## 🔍 Search Terms

in operator, in keyword, object key type narrowing inferring

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [?] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`in` operator can be used to narrow down object's union type, but it also could be useful to narrow down the key type as well

## 📃 Motivating Example

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgQwA4wLwwN4Cga5gawFMBPAQQC4YBtAclJoF0AaHPI4gIUpo5qwF8sWAPTCYwBGBgAjQjEnEY0AE4BLMAHMsAG0KwIIOIQDKUNZrQwa7egG4hqgGYAKA0dPmNMdfGQBKbDwYURhCZWUQZQBCVlxEJCo3EzN1DQZ7WOCxYABXcMIwWAB3SPwECJywABN5atCADyRCYChCGtkACwQAN1VIzPjEw2TPeQgCEhBHGChiJqnfJAYBIA

```ts
const map = {
    keyA: ['A'],
    keyB: 'B'
}

// can be any string
let someString = 'keyA';

if(someString in map){
    // error!
    map[someString];

    // current workaround and expected behavior
    map[someString as keyof typeof map]
}
```

## 💻 Use Cases

Simplify code, remove unnecessary type casts

**Comment by ahejlsberg** [comment]
This already works provided `someString` is declared as a `const` variable.

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgQwA4wLwwN4Cga5gawFMBPAQQC4YBtAclJoF0AaHPI4gIUpo5qwF8sWAPTCYwBGBgAjQjEnEY0AE4BLMAHMsoSLAgg4hAMpQ1mtDBrt6AbiGqAZgAp9hk2Y0x18ZAEpseDCiMITKyiDKAISsuIhIVK7GpuoaDHYxQWLAAK5hhGCwAO4R+Ajh2WAAJvJVIQAeSITAUITVsgAWCABuqhEZcQkGSR7yEAQkIA4wUMSNkz5IDAJAA

It doesn't work with `let` variables because we'd have to do additional (an expensive) analysis to prove the variable isn't mutated between the `in` check and the element access.

**Comment by Lutymane** [comment]
@ahejlsberg yes, the suggestion is specifically for `let/var`, not `const`.

Could you elaborate how would it be any different from already implemented behavior with object type narrowing and then mutating it?

Comparison:
https://www.typescriptlang.org/play?#code/DYUwLgBA9gXBDeBDOBGAvhAPggRnATGgFBEAUpAlBALwB8CRAlgGakDkibEjAdtBfCIRhEAPSiIPRACdpUAO4gAJkJFQSIsRIC2AVzCIwygDQQAzlG5g2ZiLp6MofRAHNEvVcMvVcMQgG4iYjQKEnFwkgBjJzNIbUQABxoGTWQIAAZjTwg8CBQgklBIMxhY6V4XQJJyCjpBbJZSW14IeISBbM1bcXMACyhdYCUckAgAaxAATyhmCDBJhJAZ1sSNTRFbHwAieV7DEAA3EGktrQhmRGBgWxxESLG5yy2yiq3s4IogA

**Comment by ahejlsberg** [comment]
> Could you elaborate how would it be any different from already implemented behavior with object type narrowing and then mutating it?

The `s in map` construct only attempts to narrow `map` and has no effect on `s`. It wouldn't be sound to narrow `s` because `map` could well reference an object instance that has more properties than are known by the static type.

**Comment by Lutymane** [comment]
> could well reference an object instance that has more properties than are known by the static type

But it doesn't seem to apply when the map is `const`. TS will prevent adding more properties as well, so it looks like if  `s in map` is truthy, then s must be a `keyof map`. Correct?

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgQwA4wLwwN4Cga5ggLhgAYAaHPAIyIEYsBfLLRJAOmDRgCYBuJlzhmBEu9PlgA2AU1gQi0AE4BLMAHNxWABSaAlGgB8mJnhhKAZpoimw8ZDuwmTVgPTOYEABYgArhIAmMJRSMADWUgCeIGYwUOFIUlG2SMaOuFboAEQA7h4IUFIAblIKGTCuMGYIEhJWlAjAITEgMBmKKqoZFLiM9DpAA

**Comment by MartinJohns** [comment]
@Lutymane Objects are structurally typed. This is legal:

```typescript
const src = { a: 0, b: 1, c: true }
const map: { a: number, b: number } = src
```

**Comment by Lutymane** [comment]
@MartinJohns Oh, thank you for the example! Now it makes sense. So the difficulty here is tracking up the full set of keys for the map object comparing to its type definition, I see. 

Although, I suppose it's technically possible to check if the const was defined by a literal and that the type was inferred from that literal or type was not overridden when assigning identifier, but I guess it's not that easy to implement?

**Comment by MartinJohns** [comment]
> I suppose it's technically possible

It's only possible in some narrow cases, but not generally. The object could be created from within a function, or it could even be created from an imported module where the implementation is simply not known at all.
