### ISSUE TITLE
isolatedModules option is not work in ^5.0.0 version

### ISSUE THREAD

**Issue by winterlood** [microsoft/TypeScript#53683]
# Bug Report

### 🔎 Search Terms

isolatedModules

### 🕗 Version & Regression Information

This changed between versions 4.9.5 and 5.0.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?isolatedModules=true#code/PTAEEsGcHsBsEMAuBTAJgWWqgrrZlRoAHRcaAO1EmUVAHJEAnbZOgKBFHnNVHOlDIAHkWiNaYiAFtR40AGtkATwDuY1BzAAjbLW5LBjRpP56iRZPEabQASQBmoJdGygAxgAtuAc2ShEHn4AbsiMkGSUiAIALAB0AJyxAKwANP6BkYGGxoygKuCwsFzmlrkqyIVsbG4UkLQodaAAvPQNiHQA3FX22ORupBSg9uQAFACUoADeAL5AA

### 💻 Code

tsconfig.json
```json
{
  "compilerOptions": {
    "isolatedModules": true
  }
}
```

index.ts
```ts
const a = 1;
```

isolatedModules option set 'true'
and this code has no export or import keyword
but any error not appear

### 🙁 Actual behavior

it seems in 4.9.5 isolatedModules option work
but in 5.0.3 isolatedModules option not work

### 🙂 Expected behavior

I think the error should occur in 5.0.3, just like 4.9.5

**Comment by andrewbranch** [comment]
Scripts are no longer errors in `isolatedModules` unless they use global namespace declarations, which is the only kind of construct that is not safe to single-file transpile. See the motivating issue #46295, design discussion in https://github.com/microsoft/TypeScript/issues/51813, and implementation at https://github.com/microsoft/TypeScript/commit/cf5c28494bd7d2d354beb13ac24197254a4c0bd6 as part of https://github.com/microsoft/TypeScript/pull/52203.

**Comment by fatcerberus** [comment]
@andrewbranch Somewhat related, is there a way to get TS to treat all files as modules regardless of whether they contain imports/exports or not?  Or does `verbatimModuleSyntax` already do that?

**Comment by andrewbranch** [comment]
`--moduleDetection force`
