### ISSUE TITLE
Inconsistency in type refinement

### ISSUE THREAD

**Issue by bodinsamuel** [microsoft/TypeScript#53687]
# Bug Report

Hey team,
Im sure someone else has reported this but I can't figure out the keywords to search for

### 🔎 Search Terms
- Inconsistency
- Type refinement
- Type guard
- Nested function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried 4.9.5, 5.03

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=5&ssc=8&pln=5&pc=12#code/C4TwDgpgBAksEFsoF4oG8pgE4QG4EsB7AVwGcB+ALnSgDNDDrTgt8A7AcygF8AaKUJGoByeMwCCwnlAA+NbHiJkqNAEYBDLExbsufAeAgixwAEJTuAbgBQAY0JtmUACbEECENtacA2gF0UKH8ba1piNltgIjYoAAsIABsEwgAKfHgEajhEAEp0aygofFooFIBCdMQAOgUCElJZOUqEKsFoZA6oUQhmczy0AsKoHGBiLDYbQu5rQeaanDqyKvpCSygAenWoAGVYkgTnTHVSUlmM+cV6qo0sNc2dveIDqAgsLEIsGcLXdxAqhHUYBSKVw6gSeWQAD58kMNlsYCUAO7QeyOfDOV4CWL4BrHKDqKBsCCIqCo+AAD2A-GRhIgEEOwEIwwgtHY0HUHHU7Cx0Da-FoXKwLzYJA4sSqg0K922jCgkrhhQAtFAAAa1JSkFWk9QxZj4JJQVTQFXhDGsonOLXy+5QZUqtpa2w6qB6g1GqAAIhM4g9UA+npMpg91q2iOxCWN6vqWpxhvUtgA1gImex0vgwfxgPFMO8wKqHVAExAwMAisBhA0cObEBA2KWw-hbLEXEyRaWAUWXbXSBB5XMo0sVgqPQBRcmQSL0l5vD7B2FzNooTrdXpSe6mYilrOxhzQV7vIVGp1kXnYhq7uJ4oslsuVllshC10tlL5DYqlCrnAcNGRNc6LjpUBXMxhH6eVChGMYJnlaY+y-BYNWWBhBm4HJJjlbggA)

### 💻 Code

```ts
type Item = { previous?: { foo: string }, type: 'testA' } | { previous?: { bar: string }, type: 'testB' };
const dummy: string[] = [];

function hello(item: Item) {
  if (!item.previous || item.type === 'testB') {
    return;
  }

  item.previous.foo; // Should pass
  item.previous.bar; // Should error

  dummy.map((val) => {
    // If we consider this as a new context, we need to refine again the type, fair enough.
    // So: 
    //  - `previous` can still be `undefined` 
    //  - `type` can still be "testA" or "testB"
    // while `previous` is back to initial, the prop `type` kept it's refinement which do not make sense
    item.previous.foo // "Expected error"
    item.type === 'testB' // But this one error because this one has kept its refinement !

    if (!item.previous || item.type === 'testB') {
      return;
    }

    item.previous.foo
  });
}
```

At first I thought it was intentional because object are reference not copy, so the prop `previous` can be made undefined in between statement (if they are async). But then I realised it's the same with the other prop, I can still modify `item` reference in between statement (if they are async). 
So I don't know if it's intentional or a bug.

### 🙁 Actual behavior

When refining and entering a nested function/statement, half of the refinement is applied and not the rest.

### 🙂 Expected behavior

When refining and entering a nested function/statement it should either follow the type completely or not at all

**Comment by RyanCavanaugh** [comment]
For better or worse, the assumption we take here is that a discriminated union stays within its narrowed discriminated type "forever", but properties of the type are reasonably subject to change. This maps fairly consistently to how these things work in practice, and the rules work out pretty well in real-world code (noted by the fact that this has been the shipping behavior approximately forever without much complaint toward this particular distinction).

**Comment by bodinsamuel** [comment]
Alright, totally understandable.
I still wish it was different but it's not a big constraint and it's true that in the last years it's probably the first time I truly noticed.

Thanks a lot for the answer, closing ☺️
