### ISSUE TITLE
Manually updating a dependency's .d.ts file doesn't trigger a recompilation when using --build and incremental builds

### ISSUE THREAD

**Issue by alcuadrado** [microsoft/TypeScript#53684]
# Bug Report

Manually updating a dependency's `.d.ts` file doesn't trigger a recompilation when using `--build` and incremental builds.

I created this minimal reproduction repository using the latest version of `typescript`: https://github.com/alcuadrado/typescript-no-recompilation-issue-repro

Note that while manually modifying a `.d.ts` file may seem odd, this issue was discovered while building a native node.js addon using `napi-rs`, which autogenerates `.d.ts` files without calling `tsc`.

### 🔎 Search Terms

build, recompilation, modified .d.ts, incremental

### 🕗 Version & Regression Information

I'm sure the bug exists in 4.5.5, 4.6.2, and in the latest version. I haven't tried others.

It's also present in `typescript@next`.

Please keep and fill in the line that best applies:

- I was unable to test this on prior versions because of lack of time, as there are many versions, and i suspect it was always present.

### 💻 Code

See: https://github.com/alcuadrado/typescript-no-recompilation-issue-repro

### 🙁 Actual behavior

If I compile the project, then modify a dependency's `.d.ts` file, and try to recompile, the `tsc --build` run doesn't detect the change. 

### 🙂 Expected behavior

The project should be recompiled if a dependency's `.d.ts` file is modified.

**Comment by alcuadrado** [comment]
Some small updates:

1. This error is not present if you use `incremental` and not `--build`.
2. Using `tsc --build --verbose` lead me to this message `Project 'tsconfig.json' is up to date because newest input 'index.ts' is older than output 'tsconfig.tsbuildinfo'` which seems to be the root of the problem.

**Comment by RyanCavanaugh** [comment]
`build` mode tries to be as fast as possible under reasonable operating assumptions in terms of how files came to exist. If those assumptions aren't valid for your project, you'll need to pass`--force` (`incremental` will get you back to where you started in terms of perf minus the overhead of checking these files)

**Comment by alcuadrado** [comment]
Thanks for your answer, @RyanCavanaugh!

> under reasonable operating assumptions in terms of how files came to exist.

Are these documented somewhere I can read?

> you'll need to pass `--force` (`incremental` will get you back to where you started in terms of perf minus the overhead of checking these files)
 
I'm not sure if I understand the comment in parens. Does this mean that `--force` won't trigger a recompilation from scratch, but a more exhaustive check to the files instead?

**Comment by RyanCavanaugh** [comment]
The only two assumptions are "TypeScript is the only tool producing build outputs" and this one.

`--force` will cause a project to be built, but under `--incremental` a "project build" can still be a minimal recomputation of which modules have changed dependencies.

**Comment by alcuadrado** [comment]
Thanks again, @RyanCavanaugh, that was clear. I think this can be closed now.

We'll use `--force` in our development workflow now.

**Comment by fatcerberus** [comment]
> The only two assumptions are "TypeScript is the only tool producing build outputs" and this one.

"This one" meaning what?  I feel like I missed something.
