### ISSUE TITLE
method parameter types defined in an interface doesn't apply to an actual class method parameters

### ISSUE THREAD

**Issue by Jakhongiirr** [microsoft/TypeScript#53688]
###<h1> We don't want to define a type for both in interface and in class as we work with complex nested generic types</h1>

<h2> we want to see the error during coding, not at compile time  </h2>

🙁
Current behavior:
```
interface A {
  method(param: string): void;
}

class B implements A {
  method(param): void {
    // the type of param is any
    console.log(param);
  }
}

const b = new B();
b.method(1); // -> no error
```
<br>
```

🙂
Expected behavior:
```
interface A {
  method(param: string): void;
}

class B implements A {
  method(param): void {
    // should be type error for param
    console.log(param);
  }
}

const b = new B();
b.method(1); // -> should be type error

```

**Comment by fatcerberus** [comment]
This already is an error:

```
Parameter 'param' implicitly has an 'any' type.
```

**Comment by Jakhongiirr** [comment]
even after strict and noImplicitAny enabled, this is still an issue, sorry if it is duplicate, it is hard to analyze 5k+ issues
