### ISSUE TITLE
TS1324 dynamic import error despite apparently correct configuration

### ISSUE THREAD

**Issue by npenin** [microsoft/TypeScript#53694]
# Bug Report

### 🔎 Search Terms

TS1324 import assert json module es

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because I started to implement ecmasript modules in my library recently and tried even more recently to incorporate it in an angular application.

### ⏯ Playground Link

https://github.com/npenin/akala
No need to build everything just a 
`yarn workspace @akala/core tsc -b tsconfig.esm.json` is sufficient

### 💻 Code

```ts
(await import(path.resolve(root), { assert: { type: 'json' } })).default;
```

if I set the config in tsconfig to the following
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./tsconfig.settings.json",
  "compilerOptions": {
    "target": "ES2022",
    "moduleResolution": "node16",
    "module": "node16",
    "customConditions": [
      "node"
    ]
  }
}
```

### 🙁 Actual behavior

error TS1324: Dynamic imports only support a second argument when the '--module' option is set to 'esnext', 'node16', or 'nodenext'.

### 🙂 Expected behavior

No error as the module option is set to node16.

**Comment by MartinJohns** [comment]
I can't reproduce the issue after cloning the repository.

**Comment by RyanCavanaugh** [comment]
I'm not seeing this either.
