### ISSUE TITLE
Multiple types not correctly marked as `Iterable` in lib.dom.d.ts, and also have missing `entries()` methods

### ISSUE THREAD

**Issue by carlansley** [microsoft/TypeScript#53692]
# Multiple built-in types not correctly marked as `Iterable` in lib.dom.d.ts, and also have missing `entries()` methods

## Configuration Check

Typescript `5.0.3`.

My compilation *target* is `esnext` and my *lib* is `["esnext", "dom", "webworker"]`.

## Missing / Incorrect Definition

The following types are iterable but not marked as such:
1) Headers
2) FormData
3) URLSearchParams

This is not an exhaustive list, just the ones I noticed.  There are likely others.

## Sample Code

From Node/Safari/Chrome Javascript consoles:
```
> new Headers()[Symbol.iterator]
[Function: entries]
> new FormData()[Symbol.iterator]
[Function: entries]
> new URLSearchParams()[Symbol.iterator]
[Function: entries]
```

These however result in the following kind of Typescript error when compiling:
```
for (const [key, value] of request.headers) { // request.headers is of type Headers from lib.dom.t.ts
  requestHeaders[key] = value;
}

...

error TS2488: Type 'Headers' must have a '[Symbol.iterator]()' method that returns an iterator.
```

Note: these type definitions are also missing the `.entries()` method as defined in their various specs.

## Documentation Link

From https://developer.mozilla.org/en-US/docs/Web/API/Headers
> An object implementing Headers can directly be used in a [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) structure, instead of [entries()](https://developer.mozilla.org/en-US/docs/Web/API/Headers/entries): for (const p of myHeaders) is equivalent to for (const p of myHeaders.entries()).

From https://developer.mozilla.org/en-US/docs/Web/API/FormData:
> An object implementing FormData can directly be used in a [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) structure, instead of [entries()](https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries): for (const p of myFormData) is equivalent to for (const p of myFormData.entries()).

From https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams:
> An object implementing URLSearchParams can directly be used in a [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) structure to iterate over key/value pairs in the same order as they appear in the query string, for example the following two lines are equivalent: ...

**Comment by MartinJohns** [comment]
> My compilation _target_ is `esnext` and my _lib_ is `["esnext", "dom", "webworker"]`.

You're missing `dom.iterable`.

**Comment by carlansley** [comment]
Wow TIL about `dom.iterable` after 7 years of using Typescript.  Very weird ecosystem quirk.  Thanks!

**Comment by MartinJohns** [comment]
IIRC it's because iterable wasn't supported by all major browsers when introduced. Not sure if it's still reasonable to split it, given that (according to CanIUse) since 2018 all major browsers support it.
