### ISSUE TITLE
stricter type checking for using objects in template literal strings

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/TypeScript#53703]
# Suggestion

Adding a type checking rule that disallows using objects/arrays/functions in strings.

## 🔍 Search Terms

[object Object]
printing object
object string
strict string type checking
template string literal

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

```js
const object = {
  key: 'value'
}

console.log(`value is ${object}`) // prints "value is [object Object]"  :(
```

In large code bases it might not always be obvious whether or not the value being printed is a string or not.

Or a type that was a string before is changed to an object type - which introduces a subtle breaking change across the code base everywhere a value of that type coerced into a string.

Either way the end result can be bad error messages:
- Error: [object Promise]
- [object Object] Something went wrong
- uncaught [object Object]
- Unknown response id for response: [object Object]
- Cannot updateState: [object Object]

## 💻 Use Cases

It is important to make sure that objects are always coerced to strings the right way to not display `[object Object]`, `[object Array]`, `[object Symbol]` or `[object Promise]` which is generally not as helpful as it is supposed to be. Therefore a TypeScript rule that would check and enforce that only primitive values are used in string literals could help avoid a lot of bugs.

The shortcoming of existing approaches is that manually implementing error messages or other literal strings which contain variables is that it can be easy to miss converting an object/array/function to a string. 

I'm not sure whether there are any workarounds in the meantime, but having lots of unit tests can be very beneficial.

**Comment by MartinJohns** [comment]
Duplicate of #30239.

**Comment by SimonSiefke** [comment]
Indeed a duplicate, thanks for the pointer!
