### ISSUE TITLE
Please provide the debug logs, set `python.logging.level` to `debug` in **User** settings, reload window, then perform the steps to reproduce before providing the logs.

### ISSUE THREAD

**Issue by Yo0ybxk** [microsoft/TypeScript#53704]
Please provide the debug logs, set `python.logging.level` to `debug` in **User** settings, reload window, then perform the steps to reproduce before providing the logs.

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

_Originally posted by @karrtikr in https://github.com/microsoft/vscode-python/issues/20828#issuecomment-1464653143_

**Comment by MartinJohns** [comment]
...wat?

**Comment by RyanCavanaugh** [comment]
Not sure how this ended up here.
