### ISSUE TITLE
Typescript throws `TS2532` although accessed value is asserted to be set with if statement

### ISSUE THREAD

**Issue by McTom234** [microsoft/TypeScript#53702]
# Bug Report

### 🔎 Search Terms
- `language server undefined`
- `TS2532`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYOwrgtgBAoiUG8BQUoEEoF4oHICGOANClAEJa4BGRSAvkkgMYA2eAzm1ACrBsAuiEngD8ALigBlPmEoUwIACbAAZgEsQwBQG4SlMZOmzs8pWo0KGqAA4zmqxlGV5VzNgAp+M8VJmEoocTgASnFKAHsw5mA8eGRUVFVlKDc+AAtVNgBtUABdIKgAJ2BpAvhPSgA6VQUsTGw0jOyQHKrtElQikvgnV2AdVHoSG0o7BwB3MIKAa3dy70M-ANgQfLj4xjCQfigGth8jHfSs3P74xOTd-fzOsFKoctba+qP91tOO4tvuvF7T+kGWOxOPtBAkFOJwBBKMAChQAAx0IA)

### 💻 Code

```ts
enum En {
  A = 'a',
  B = 'b',
}

class Test {
  a?: Stub = undefined;
  b?: Stub = undefined

  public fails(stub: Stub, en: En): boolean {
    if (this[en]) return stub.id === this[en].id;
    return false;
  }

  public works(stub: Stub, en: En) {
    const thisStub = this[en];
    if (thisStub) return stub.id === thisStub.id;
    return false;
  }
}

class Stub {
  id: number = 0
}
```

### 🙁 Actual behavior

TypeScript gives the error TS2532: `Object is possibly 'undefined'.` in the method `fails`.

### 🙂 Expected behavior

The if statement asserts, that this property is set and no modification has been made to the code since the statement. The variable should be set and as the method `works` it works as expected by setting an extra variable for the accessed property.

**Comment by MartinJohns** [comment]
Duplicate of #10530 and oh so many others. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal.

**Comment by McTom234** [comment]
Oh, sorry! I had no idea which keywords should work to find the right duplicates. Do you know, if this will be fixed at any point?
