### ISSUE TITLE
The hinted type is consistent with the actual type

### ISSUE THREAD

**Issue by sauron0914** [microsoft/TypeScript#53719]
# Bug Report

![image](https://user-images.githubusercontent.com/25734944/230882754-64b6d034-6ba2-4541-b690-5c1e8508b241.png)

### 💻 Code

type RoutePath = "/login" | "/not-found" | "/choose-role" | `/wujie-test/${string}`

function fn(a: RoutePath) {

}

fn('')

### 🙁 Actual behavior

Type hints are missing `/wujie-test/${string}`  when I type "" 

### 🙂 Expected behavior

All types will be prompted

**Comment by Peeja** [comment]
Currently (AFAIK), only literal types are offered for autocompletion. `` `/wujie-test/${string}` `` isn't actually a literal type: it's a template, which contains a non-literal type, `string`. I'm not sure what you'd expect to have the editor fill in for you if you selected that. It would certainly be neat in this use case to get something like `'/wujie-test/¦'` or `'/wujie-test/⟨string⟩'`, where `¦` and `⟨...⟩` represent the cursor and selection, respectively. But to do that would be a fairly major feature addition. Definitely worth proposing and thinking through, just not a bug fix or a minor change.

I think an ideal solution (ignoring the effort to implement it) would be to handle any number of interpolations like a TextMate-style snippet. So, completing the type `'/foo/${string}/bar/${string}/baz'` would give you:

```
'/foo/⟨string⟩/bar/string/baz'
# type "1"
'/foo/1¦/bar/string/baz'
# type <tab>
'/foo/1/bar/⟨string⟩/baz'
# type 2
'/foo/1/bar/2¦/baz'
# type <tab>
'/foo/1/bar/2/baz'¦
```

But to do that would require whole lot of work across both TS itself and the editor support, so we'd need to develop strong use cases to justify the effort.

**Comment by RyanCavanaugh** [comment]
It's not really clear how you'd surface this for cases like `${string}/foo`.

**Comment by sauron0914** [comment]
> 

thanks for giving me some inspiration！I thought of a temporary solution

```ts
type ReplaceId<T> = T extends `${infer U}:id${infer V}` ? (`${U}${string}${V}` | ReplaceId<`[id:]${U}[id]${V}`>) : T;

export type RoutePath = ReplaceId<
  typeof publicRoutes[number]['path'] |  typeof privateRoutes[number]['path']
> extends infer R ? (R extends string ? R : never) : never;

function fn(a: RoutePath) {

}

fn('')

const publicRoutes = [
  {
    path: '/login',
    title: 'login',
  },
  {
    path: '/not-found',
    title: '404',
  },
  {
    path: '/wujie-test/:id',
    title: 'hydrogen',
  },
  {
    path: '/wujie-test/:id/detail/:id/name',
    title: 'hydrogen',
  },
] as const

const privateRoutes = [
  {
    path: '/choose-role',
    title: 'choose role',
  }
] as const
```
This tip helped me temporarily solve the problem

**Comment by sauron0914** [comment]
> Currently (AFAIK), only literal types are offered for autocompletion. `` `/wujie-test/${string}` `` isn't actually a literal type: it's a template, which contains a non-literal type, `string`. I'm not sure what you'd expect to have the editor fill in for you if you selected that. It would certainly be neat in this use case to get something like `'/wujie-test/¦'` or `'/wujie-test/⟨string⟩'`, where `¦` and `⟨...⟩` represent the cursor and selection, respectively. But to do that would be a fairly major feature addition. Definitely worth proposing and thinking through, just not a bug fix or a minor change.
> 
> I think an ideal solution (ignoring the effort to implement it) would be to handle any number of interpolations like a TextMate-style snippet. So, completing the type `'/foo/${string}/bar/${string}/baz'` would give you:
> 
> ```
> '/foo/⟨string⟩/bar/string/baz'
> # type "1"
> '/foo/1¦/bar/string/baz'
> # type <tab>
> '/foo/1/bar/⟨string⟩/baz'
> # type 2
> '/foo/1/bar/2¦/baz'
> # type <tab>
> '/foo/1/bar/2/baz'¦
> ```
> 
> But to do that would require whole lot of work across both TS itself and the editor support, so we'd need to develop strong use cases to justify the effort.

Thanks for the inspiration, I thought of a temporary solution!

```ts
type ReplaceId<T> = T extends `${infer U}:id${infer V}` ? (`${U}${string}${V}` | ReplaceId<`[id:]${U}[id]${V}`>) : T;

export type RoutePath = ReplaceId<
  typeof publicRoutes[number]['path'] |  typeof privateRoutes[number]['path']
> extends infer R ? (R extends string ? R : never) : never;

function fn(a: RoutePath) {

}

fn('')

const publicRoutes = [
  {
    path: '/login',
    title: 'login',
  },
  {
    path: '/not-found',
    title: '404',
  },
  {
    path: '/wujie-test/:id',
    title: 'hydrogen',
  },
  {
    path: '/wujie-test/:id/detail/:id/name',
    title: 'hydrogen',
  },
] as const

const privateRoutes = [
  {
    path: '/choose-role',
    title: 'choose role',
  }
] as const
```
it works

**Comment by sauron0914** [comment]
> It's not really clear how you'd surface this for cases like `${string}/foo`.

It is mentioned in the reply to Peeja!

**Comment by Peeja** [comment]
@sauron0914 Ooh, I like that solution! So, to summarize, the idea is to start with placeholders (like `:id`) in the paths (which is presumably how the router expects them when declaring the routes), and then translate those into `${string}` interpolations in the type, but *also* include the original path declaration explicitly in the union. So, for `/foo/:id/bar`, you'd end up with the type `` `/foo/${string}/bar` | '/foo/:id/bar' ``, which means that the placeholder version is a literal type available for autocompletion. And since `:id` is a valid string, the types are correct, they just happen to be singling out this one instance of `` `/foo/${string}/bar` `` redundantly in the union. Do I have that right?

Some editor support for this kind of thing would be lovely someday to be able to tab between the placeholders, but that's a ton of work to implement, and this is a solid solution that gets 95% of the way there without changing TS at all!
