### ISSUE TITLE
generic conditional operator type with boolean array is not work fine

### ISSUE THREAD

**Issue by dlog6649** [microsoft/TypeScript#53712]
# Bug Report

### 🔎 Search Terms

- ternary operator
- ternary operator boolean
- conditional type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230409#code/C4TwDgpgBAwg9gOwCYEtgsQQwDYHlIBOmwcBUAvFAEZxzYSYJQQAewEyAzlAhAG4QyAfmq16jKAC5RdBggDaAXQCwAKFCQoAcQ6CUAY3jI0GBDnyDipADwAVAHwUot5mw5JuvAcOdTnStTUkCH1sTAJofUROYBlsTmkjVHQsPEIrAjUaOk4AOjAAV04ACwAKYAICiABKLLE8wpLSgDMcThrA1WDQ8Mjo2IBzXQIDACF66R1eEcNEZNNzdJICa2zxBHs1Iemx+vyisoqq2tVtvX1xnP2m1viO1SA)

### 💻 Code

```ts
type ConditionalOperator = boolean extends never ? boolean : boolean[]
type GenericConditionalOperator<T> = T extends never ? T : T[]

declare const bools: ConditionalOperator
bools.push(true)
bools.push(false)

declare const genericBools: GenericConditionalOperator<boolean>
genericBools.push(true)
genericBools.push(false)
```

### 🙁 Actual behavior

can not push with true or false to genericBools
and error message says
> Argument of type 'boolean' is not assignable to parameter of type 'never'

### 🙂 Expected behavior

i think `bools` and `genericBools` types are should be `boolean[]`. but `genericBools`'s type is `true[] | false[]`

**Comment by MartinJohns** [comment]
`boolean` is a fancy keyword for `true | false`, so your conditional type acts distributive over this union type. This is working as intended.

**Comment by dlog6649** [comment]
> `boolean` is a fancy keyword for `true | false`, so your conditional type acts distributive over this union type. This is working as intended.

hmm.. then i have to write my code like this for boolean?
```ts
type GenericConditionalOperator<T> = T extends never ? T : T extends boolean ? (true | false)[] : T[]
```
it is so weird..

**Comment by MartinJohns** [comment]
Or disable distributive behaviour for this conditional type, depending on what you want to achieve.

**Comment by dlog6649** [comment]
i found out distributive behaviour from [ts handbook - Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) and tried to solve this but still weird
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230409#code/C4TwDgpgBAwg9gOwCYEtgsQQwDYHlIBOmwcBUAvFAEZxzYSYJQQAewEyAzlAhAG4QyAfmq16jKAC5RdBggDaAXQCwAKFCQoAcQ6CUAY3jI0GBDnyDipADwAVAHwUot5mw5JuvAcOdTnStTUkCH1sTAJofUROYBlsTmkjVHQsPEIrAjUaOk4AOjAAV04ACwAKYAICiABKLLE8wpLSgDMcThrA1WDQ8Mjo2IBzXQIDACF66R1eEcNEZNNzdJICa2zxBHs1Iemx+vyisoqq2tVtvX1xnP2m1viO1TUAekeoZoI4AFsoYuBgMATngB3YG5DQQTj6EZgYBhBADXKkAaPJBwfScR7FRhIbIAa0eACZHlFjCkzNgALRgvI-D7YNRg5xwACCBCIIAAcogACIoGJ2cAQRyUeS2AWKVzsLhQeSMEDikSiyBKPxeQQAbnpAu0wwMtmZrMwHO5vOAdiFvlYko8PH4gigIlVZGkepZbM5CB5fIcnW6YQiUGJMR4xpil3izv1bpDprWck2qgQ0bDDQO5Uq90THpNyeuZVu7ROQRCfr6CCDZxm7s9wGTkx1+hdBqNWb5scY8YrBir2b2jUO6ZOnf03dDvdT+fuQA)

```ts
// from https://www.typescriptlang.org/docs/handbook/2/conditional-types.html
type ToArrayNonDist<Type> = [Type] extends [any] ? Type[] : never;
type GenericToArrayNonDist<T> = T extends never ? never : ToArrayNonDist<T>

// nonDistBools type is boolean[]
declare const nonDistBools: ToArrayNonDist<boolean>
nonDistBools.push(true) // fine
nonDistBools.push(false) // fine

// genericNonDistBools type is true[] | false[]
declare const genericNonDistBools: GenericToArrayNonDist<boolean>
genericNonDistBools.push(true) // error occurred
genericNonDistBools.push(false)  // error occurred
```

Why is this happening?

**Comment by MartinJohns** [comment]
> Why is this happening?

Because `boolean` is treated as `true | false` and your conditional type distributes over this union.

In line 20 you have `GenericToArrayNonDist<boolean>`. As mentioned before, `boolean` is treated as `true | false`, and you do not opt out of distributive behaviour in your `GenericToArrayNonDist<T>` conditional type, so `GenericToArrayNonDist<boolean>` resolves to `(true extends never ? never : ToArrayNonDist<T>) | (false extends never ? never : ToArrayNonDist<T>)`.

**Comment by dlog6649** [comment]
ah i understood.
thank you very much!
