### ISSUE TITLE
Return type of constructor signature must be assignable to the instance type of the class

### ISSUE THREAD

**Issue by g162h3** [Microsoft/TypeScript#5372]
This is very annoying message because it comes without an explanation. Often appears when I convert an existing function-like class into a class-like function to write a proper interface without actually changing the implementation:

```ts
class Huge {
  foo: Foo;
  bar: () => Bar;

  constructor(...) {
    ...
    return {
      foo: ...,
      bar: ...
    };
  }
}
```

The `return` statement with the entire returned expression is highlighted and this confusing error is given. In many cases I end up commenting/uncommenting parts of the interface to find which members are causing this errors. In some cases I gave up and I had to case the result to `any`.

**Comment by RyanCavanaugh** [comment]
```ts
interface Foo { f }
interface Bar { b } 

class Huge {
  foo: Foo;
  bar: () => Bar;

  constructor() {
    return {
      foo: 32,
      bar: ''
    };
  }
}
```
Current output:
> a.ts(9,12): error TS2409: Return type of constructor signature must be assignable to the instance type of the class

Expected:
> a.ts(9,12): error TS2409: Return type of constructor signature must be assignable to the instance type of the class
    Elaboration that type of member 'foo' is wrong because 'number' is not assignable to 'Foo'
