### ISSUE TITLE
Overloaded constructors: 'TValue' not assignable to 'string'

### ISSUE THREAD

**Issue by anonbergine** [microsoft/TypeScript#53722]
# Bug Report

### 🔎 Search Terms

constructor, overload, TValue, jsdoc

### 🕗 Version & Regression Information

- This changed between versions "recent"? and ~1.77.1-ish
- I was unable to test this on prior versions because PR #52577 was not implemented (there was no reliable way to define overloads for class constructors)

Recent PR fixed the use of jsdoc-defined overloads for class constructors
* Bug report: #52477
* Bug fix (for jsdoc `@overload`): #52577

That seems to have made it in to recent VS Code release; I'm using:

- Version: 1.77.1 (user setup)
- Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
- Date: 2023-04-04T23:21:11.906Z
- Electron: 19.1.11
- Chromium: 102.0.5005.196
- Node.js: 16.14.2
- V8: 10.2.154.26-electron.0
- OS: Windows_NT x64 10.0.19045
- Sandboxed: Yes

### ⏯ Playground Link

(Updated to exhibit error): [Playground link](https://www.typescriptlang.org/play?moduleResolution=99&target=99&jsx=0&module=100&ts=5.1.0-dev.20230410&filetype=js#code/PTAEAEBcGcFoGMAWBTeBrAUB4AqHHQcJJkBbABwBsBDE0AFQDVrKBXZAoqAT3OVADeAZUgAnAJYA7AOYBpZNwCy1cgB4mLdgD4Avp2AZkAD3IB7UZFDwa0aKBESZ8pStDGSkgCZ3l5QQVBA3HxA0K54U0loMVZ4SHMAsIhTADdkUUpTak9EwK5yalFqUkEASRIigCNKZFUAbWjHaQAaBmY2ZABdXVBxCupqjlC8iAKikoFGqWkdUAAzc1JcwhA8ZfDIxtj40XXktIysnOHCUcLiwSmZWYXRJZOcVZDhjaiYuISH-fTM7L3wMYXATldIDGr1K4tNqaLo9PqgwbrJ7-CJvUTbT4vb6HP4PAzDVFbD6iAAUAEFWgAhACU-hOoWgrD4pOpy1CIFAADpubk9Llgv9UukJJ4hliAecJpDZmgFP9ARMNB1ZikYf9RMhIKxRFFBJBEOJoHo8bloJqSbLuK1VR1aQI2UEwJJFixxAAvfiW0AkjWkIWeebmUCVDUpPrcVn0wIarU60CM5mcs2QC0Ka0wyOhPR87B4Yi8fjCMTTZy+VSSVikSrpHqPDCEywLUygAC8oEkyAA7vZi04FL4SbSOapYLArKZRaADZJLMKgyo+IU7CgNUA)

### 💻 Code

```es6
// @ts-check

/**
 * @template TValue
 * @type {StringKeyMap<TValue>}
 */
export class StringKeyMap extends Map {
    /**
     * @constructor
     * @overload
     * @param {Iterable<[string, TValue]>} iterable
     * @param {string} form
     *//**
     * @constructor
     * @overload
     * @param {string} form
     *//**
     * @constructor
     * @overload
     * @param {Iterable<[string, TValue]>} iterable
     *//**
     * @constructor
     * @overload
     */
    constructor(A, B) {
        super()
        // ...
    }

    /**
     * @override
     * @param {string} key
     * @param {TValue} value
     * @returns {this}
     */
    set(key, value) {
        // normalize key (removed for brevity)
        return super.set(key, value)
    }
}


/** @type {StringKeyMap<number>} */
const foo = new StringKeyMap() // <-- code hint error appears here
```

### 🙁 Actual behavior

In VS Code editor, if I try and instantiate my class using code like this:

```es6
class foo {
    // ...

    /** @type {StringKeyMap<string>} */
    #tags

    /**
     * @param {Iterable<string>} tags
     */
    constructor(tags) {
        this.#tags = new StringKeyMap() // <-- error shows here
    }

    // ....
}
```

This happens:

![image](https://user-images.githubusercontent.com/120770250/230944512-04d35dcd-6f2e-46c1-9019-0fb5219b9503.png)

Hovering the error shows:

![image](https://user-images.githubusercontent.com/120770250/230944612-321b8434-8f6c-4c1e-9f9a-fde7cf5ca881.png)

The code still works fine when used in node, the issue is constrained to the VS Code editor which seems to think `TValue` is a type rather than a template.

Possibly related to comment here about type checking being broken: https://github.com/microsoft/TypeScript/issues/52477#issuecomment-1414165166

### 🙂 Expected behavior

`TValue` is a template and thus should adopt the `@type {StringKeyMap<string>}` defined for `#tags` .

**Comment by RyanCavanaugh** [comment]
I can't repro this in TS 5.0.2. or nightly. Can you try installing the [TS/JS nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) extension and seeing if that fixes it?

**Comment by anonbergine** [comment]
> I can't repro this in TS 5.0.2. or nightly. Can you try installing the [TS/JS nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) extension and seeing if that fixes it?

I've installed that extension and restarted VS Code and still getting the error. I'll try and make a smaller test case exhibiting the error.

**Comment by anonbergine** [comment]
I've updated code sample in OP to minimal code that reproduces the error.

**Comment by RyanCavanaugh** [comment]
Simpler:
```ts
/**
 * @template TValue
 */
export class StringKeyMap {
    /**
     * @constructor
     * @overload
     */
    constructor() {
    }

    /**
     * @param {TValue} value
     */
    bar(value) {
    }
}


/** @type {StringKeyMap<number>} */
let foo;
foo = new StringKeyMap() // <-- code hint error appears here
```
Removing the `@overload` line makes the error go away, but this shouldn't have any effect
