### ISSUE TITLE
Dynamic class instance property assignment is expecting `never` while its read type is `string | number`

### ISSUE THREAD

**Issue by frank-weindel** [microsoft/TypeScript#53738]
# Bug Report

I imagine this is a duplicate of something but I couldn't find it. 

### 🔎 Search Terms

class instance keyof mapped type assignment never 

### 🕗 Version & Regression Information

- This behavior exists from version 3.6.3 through 5.1.0-dev.20230411
- I reviewed the FAQ for entries about `keyof mapped type assignment never`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.3#code/JYOwLgpgTgZghgYwgAgLIE8DCAbOBnPAdSmDDDgCNsIAFKAewAc9kBvAKGS+UYcYEYAXMjxgSIAOYBuTt15MATMJABXALYVoMgL7t2AEwgJcUFMfwsMOC8mBrG1NRHCWsuAsVLkqtPiw7cyBIQYDx8-AAUAJTCouLSslx4IWFMkQBusWKgElEyiUEp8owK0crqmlAygcmhxaWZyKoa0Hnsuuxg6IwoVu54qCrkYMD0ICwAvGzIANosoMgA1hDo9DBobhaeZJTUdEx4ALoA-MJiKija+YbmpsgIY6LIakNwI4-CfRaDw6PjMjcTGZHqEQBAAO77RgANTg2AueE+mw8JB2PiheGuRiB9xBz2RiI21gI+QA9KTkAAhBjLED3fAQAB0zPYMHoUGQEQe41Cy3QtjpL1+jyibAK3Ke6ThF2QUzBkL4sPhEDwMz5yHwSxWayJ-W23j2fkO1W4agJapWGpYfJ1XxRXl2vgOh1lyClypk5K4AD1fX7-QHA0Hg0H2F7kAAVbooADkcRyyAAPk0KtAY7YWCB6KELMAJCBHcgwPQi9HkDGwek04ywxTuFGeuX45J08BM9mrXg8wWfEWS11GxWIFWoDHGREFABmBQKKLtPS15CEdmLOAMFQgfTMmtsjlcvHqhZCt5-PCigLcCWhd0yuUQqFKhEW-mam3rO1EVEGp3MY0FL0AKIAB5iIgObIPo6hmm6a7AIWxaFKEYAABYoKYcD6KWPTini9DYPoj4oFMZrEqq6qvtq74EvqjoYn+gThj6gYiNkkhJimLRQP+FIAGLskgnbQEhqGdt2WEoDqKESRQABWRjXtKEAFBEJH9M+VpaqsVGkTR6JGhpA4QDqeEEYpopTDeEA6EAA)

### 💻 Code

```ts
interface MyClassWrittableProps {
    prop1: string;
    prop2: number;
}

declare class MyClass implements MyClassWrittableProps {
    get prop1(): string;
    set prop1(v: string);

    get prop2(): number;
    set prop2(v: number);
}

type MyClassMutations = { [s in keyof MyClassWrittableProps]?: true };

declare const mutations: MyClassMutations;
declare const newPropValues: MyClassWrittableProps;

declare const myClass: MyClass;

// Broken case...
for (const key in mutations) {
    const value = newPropValues[key as keyof MyClassWrittableProps];
    myClass[key as keyof MyClassWrittableProps] = value;
//  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//  Type 'string | number' is not assignable to type 'never'.
//    Type 'string' is not assignable to type 'never'.(2322)
}


// Workaround...
for (const key in mutations) {
    const value = newPropValues[key as keyof MyClassWrittableProps];
    // Extract a dummy variable to get the read type
    const oldValue = myClass[key as keyof MyClassWrittableProps];
    //    ^^^^^^^ string | number
    // Force assert the assign type of the object value
    (myClass[key as keyof MyClassWrittableProps] as typeof oldValue) = value;
}
```

### 🙁 Actual behavior

- TypeScript expects the assignment type of the class instance value to be `never`

### 🙂 Expected behavior

- TypeScript expects the assignment type of the class instance value to be `string | number`

**Comment by frank-weindel** [comment]
Upon a bit more digging I think this is related to both:
- #31663
- And the TypeScript 3.5 change referenced by @RyanCavanaugh in the above issue
  - https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/#fixes-to-unsound-writes-to-indexed-access-types

So I guess this is working as designed?

**Comment by RyanCavanaugh** [comment]
Unlikely to see progress in this area, I think. The only way this kind of write is sound is when the indexing value is provably the same on both the read and the write side, and TS doesn't have anything in the way of mechanisms which would allow doing that.
