### ISSUE TITLE
Argument of type `(data: MyData[T]) => void` is not assignable to equivalent function in a derived mapped type

### ISSUE THREAD

**Issue by chrisfillmore** [microsoft/TypeScript#53745]
# Bug Report

Apologies in advance if I am wrong about this, or if it's a limitation. I searched previous issues and checked the FAQ but did not spot anything quite the same as this.

### 🔎 Search Terms
argument of type is not assignable to 

### 🕗 Version & Regression Information
I am able to reproduce on nightly. My actual app also reproduces, on v4.9.4.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230411#code/PTAEAUFcCMGUYFABcCeAHApqAMgSwM5IYB2GATrLgObECGSkZGAPAKIBuJS+oAvKAG8AvgD4+ghKCmgA2gDlaAWyy5ioANYYUAewBmoDl3wBdAFygAFADobtMlXznaxFDOMBKPmOcoA3AiEEZHQsKDgYNk5iblAMAA8iYgATHjxCEnJKGnpGFkNo-BExfgEEAEh8GHwAYzJcaBYAFViEkhSNLT0DKO4RCwwe80aAGlBq2gAbCehaavVzfO4ZRo9zdm1cJICgkFAAWRRQQkhdXSDUTH2UABF6WnFSiqQyc0I64ipy4khFc2-FBpkcp2F6gbTQABWGGqSDc2wuWAOWToDCYD0k0mWAGktKBVB0dPoDrckLRjKBzBZ2JNIBhzMS7titB4vKB1pttghqtpiIRQIoUGF4NB0RUqrV6k0Wol2ppCVdkTkmH0BlwhqNxlMZnN6ShFaiMMsWcJObpIMQYbgeUdxXUGsxmvEZTw5V0kdQUbk+uU0DBheYhRF3dkDSJhuVVdF1eVNdNZuoAIy6-W5I3hsqx7XqABMlKSd11JNoRs8vDE7K2nkevvC0CslWgNTtGH6PQ1kzjcwT7h9fpg9dtktbXHbWvj2Z7gQQDabQ4FgegowARG8l6MLKWxMJ15vBEJ3EA)

### 💻 Code

```ts
// I have a pubsub utility roughly like this one below
type ListenerSignature<Events = {}> = {
    [Name in keyof Events]: (...args: any[]) => any;
}

type PubSub<Events extends ListenerSignature<Events>> = {
	subscribe<T extends keyof Events>(event: T, callback: Events[T]): void
}

// My application code
type MyData = {
	str: string
	num: number
	arr: object[]
}
type MySignature = {
    [TKey in keyof MyData] : (value: MyData[TKey]) => void
}

function subscribe<T extends keyof MySignature>(
	pubSub: PubSub<MySignature>,
	event: T,
	callback1: MySignature[T],
	callback2: (data: MyData[T]) => void
) {
	pubSub.subscribe(event, callback1) // This works fine
	pubSub.subscribe(event, callback2) // Argument of type '(data: MyData[T]) => void' is not assignable to parameter of type 'MySignature[T]'.
}
```

### 🙁 Actual behavior
The type system complains:
```
Argument of type '(data: MyData[T]) => void' is not assignable to parameter of type 'MySignature[T]'.
```

### 🙂 Expected behavior
The function `(data: MyData[T]) => void` should be assignable to `MySignature[T]` in the code above. Is this not perfectly safe?

**Comment by RyanCavanaugh** [comment]
> Is this not perfectly safe?

This can only be shown to be safe through brute enumeration of the possible inhabitants of `T`. That's not a strategy TS uses since it tends toward combinatorial explosion.

**Comment by chrisfillmore** [comment]
Thanks for the reply @RyanCavanaugh, I appreciate you taking the time.
