### ISSUE TITLE
Proposal: Error on + + for Strings

### ISSUE THREAD

**Issue by aersamkull** [Microsoft/TypeScript#5374]
I recently wrote code like this:
```TypeScript
const aString = "asf" +
                + "asdf";
```
Which results in "asfNaN" which is not very obvious, I think.

I think it would be good to error on that case or to give at least a warning, It is very unlikely to be intended. 
I am even more confused as "1"+ +"2" is "12"!? However, that's JavaScript's fault, not TypeScript's. 

How do you think about that?

**Comment by DanielRosenwasser** [comment]
Oof, that's a bad one. Still, I don't think we could reasonably rule this out. A linter (i.e. TSLint) might do well in this sort of situation.

**Comment by weswigham** [comment]
> I am even more confused as "1"+ +"2" is "12"!? However, that's JavaScript's fault, not TypeScript's.

Let me explain this with our [spec](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.18.2): we say that unary plus is used to cast to number types, and [binary plus involving a string and a number](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4192-the--operator) has a result of a string, so nothing's wrong here. (And it captures the type conversions that these operators do in JS.) But! As @DanielRosenwasser points out, you could certainly add a lint rule to catch when you have a unary plus operation within a binary plus operation and forbid it within your own code.

**Comment by aersamkull** [comment]
Ok, so I close this one. I have now submitted an issue on tslint: https://github.com/palantir/tslint/issues/755
