### ISSUE TITLE
Generic types are not inferred for abstract classes if not explicitly used

### ISSUE THREAD

**Issue by Xriuk** [microsoft/TypeScript#53750]
# Bug Report
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.8.4#code/JYWwDg9gTgLgBAbzgcQKbwL5wGZQiOAchgE8xUBabVAZxkIG4BYAKFYEMAjOqdgY3h8ANuxo04AWRIBBbjF4C0AO1RRgfADwAVAGrshAV1QBGADRxd+owCY4qAB4xUSgCbiewJQHNzlw6gBmAD5EVjg4Lh5+eChUdhcIJSESOBBUEE5VAC4UdG09fzMLApsghjgAegq4AGF2JThMuAgYAAtVOD58MCEHOFJyGlYMVlZhUXEpGsS+WKdlVXV8qxNfEsCQhydXSZk5BRgFtU0w4pWzU+JaelNTvyMA1hCEU7SM7NyYZcLzK7pCEIAXjgSgMQiEAEJmGwWOEQCQ9FAcvcTHBgaDwVDhqMWNgDEoBMBEqkSEd1AAxfGExLfIxFFG2LbONxwDzeNYrYIAClOkXk0UROSksiiimci00KPp62sHP8wVYAEpECMYb14PDpgS5qhEWiQagAO6SEha2boVBkzRsnwggzvKBBLmK6Hwq2UgkwIlKLmamY6xEunHqkki-kCPXoo0ms06q0aU4226wu0Op7OiK7MMHeNJiJKEjmUEOsqsN3i44e6k++HZgXsKBBlhAA)

### 💻 Code

```ts
abstract class MyAbstractGeneric<TValue1, TValue2 extends string, TValue3> {}

class MyConcreteGeneric<TValue1, TValue3> extends MyAbstractGeneric<TValue1, 'test', TValue3> {}

function myGenericFunction<TValue1, TValue2 extends string, TValue3>(abstractVar: MyAbstractGeneric<TValue1, TValue2, TValue3>) {}

let myConcreteVar = new MyConcreteGeneric<string, number>();
// Inferred as <unknown, string, unknown>
myGenericFunction(myConcreteVar);

let myAbstractVar = new MyConcreteGeneric<string, number>() as MyAbstractGeneric<string, any, number>;
// Inferred as <string, any, number>
myGenericFunction(myAbstractVar);
```

If I declare a member of a generic type inside the abstract class everything works (for the declared members)
```ts
abstract class MyAbstractGeneric<TValue1, TValue2 extends string, TValue3> {
  myVar?:TValue1;
}

class MyConcreteGeneric<TValue1, TValue3> extends MyAbstractGeneric<TValue1, 'test', TValue3> {}

function myGenericFunction<TValue1, TValue2 extends string, TValue3>(abstractVar: MyAbstractGeneric<TValue1, TValue2, TValue3>) {}

let myConcreteVar = new MyConcreteGeneric<string, number>();
// Inferred as <string, string, unknown>
myGenericFunction(myConcreteVar);

let myAbstractVar = new MyConcreteGeneric<string, number>() as MyAbstractGeneric<string, any, number>;
// Inferred as <string, any, number>
myGenericFunction(myAbstractVar);
```
But then some complex type using any of the generic types is not considered apparently
```ts
import { Get } from 'type-fest';

abstract class MyAbstractGeneric<TValue1, TValue2 extends string, TValue3> {
  myVar?:Get<TValue1, TValue2>;
}

class MyConcreteGeneric<TValue1, TValue3> extends MyAbstractGeneric<TValue1, 'test', TValue3> {}

function myGenericFunction<TValue1, TValue2 extends string, TValue3>(abstractVar: MyAbstractGeneric<TValue1, TValue2, TValue3>) {}

let myConcreteVar = new MyConcreteGeneric<string, number>();
// Inferred as <unknown, string, unknown>
myGenericFunction(myConcreteVar);

let myAbstractVar = new MyConcreteGeneric<string, number>() as MyAbstractGeneric<string, any, number>;
// Inferred as <string, any, number>
myGenericFunction(myAbstractVar);
```

### 🙁 Actual behavior

The function called on a child of a generic abstract has the wrong type inferred if no concrete members of the type(s) are declared in the abstract class.

### 🙂 Expected behavior

The generic types should be inferred regardless of their use inside the class

**Comment by fatcerberus** [comment]
I’d say this is working as intended.  Because of structural typing, if you don’t use a type parameter in a type, then as far as TypeScript is concerned it effectively doesn’t exist for the purposes of type checking and inference.

**Comment by fatcerberus** [comment]
There’s also this entry explaining this exact behavior:
https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--

**Comment by Xriuk** [comment]
> I’d say this is working as intended. Because of structural typing, if you don’t use a type parameter in the definition of a type, then as far as TypeScript is concerned it effectively doesn’t exist for the purposes of type checking and inference.

The problem is that the type parameter usage is not considered, this is a valid type which is not picked by Typescript:
`Get<TValue1, TValue2>` which is a complex type using the generic class' parameters

**Comment by mp3por** [comment]
Sooo - how to fix this ? Please provide the proper implementation of the submitted code for reference to me and future people.

**Comment by RyanCavanaugh** [comment]
@mp3por there's nothing to "fix" here. Structural inference in a structural type system is the expected and intentional behavior. See also https://github.com/microsoft/TypeScript/wiki/FAQ#structural-vs-instantiation-based-inference
