### ISSUE TITLE
nodenext moduleResolution can't resolve package types correctly

### ISSUE THREAD

**Issue by tjx666** [microsoft/TypeScript#53759]
# Bug Report

### 🔎 Search Terms

nodenext, moduleResolution, exports

### 🕗 Version & Regression Information

happen on typescript@5.0 to typescript@next

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/231577475-cfc6fa20-58b2-4197-98d6-e18e697b905a.png">

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&moduleResolution=99&module=199&ts=5.1.0-dev.20230412#code/JYWwDg9gTgLgBAN2DApgBQDYFcDmwB2AaligExwBmUEIcA5AAJKoBWAzgPRjZ74C0CEqToBuAFBiAxhHxsIGFADoMEHAApm6HgWJk1ASn0igA)

The playground seems can't save my tsconfig.
You need to set:

- target: ESNext
- module: nodenext

### 💻 Code

```ts
import vitePluginVue2 from '@vitejs/plugin-vue2';

console.log(vitePluginVue2());
```

### 🙁 Actual behavior

```txt
This expression is not callable.
  Type 'typeof import("file:///node_modules/@vitejs/plugin-vue2/dist/index")' has no call signatures.(2349)
```

### 🙂 Expected behavior

No compile error

**Comment by RyanCavanaugh** [comment]
I don't think `nodenext` module resolution is just uniformly broken -- much more likely this is a misconfigured package. Can you be more specific about why you think this is a wrong result, and include a sample repo to demonstrate?

**Comment by tjx666** [comment]
I just want to to know why throw this error when I using moduleResolution; nrext. In fact, I don't use this, I just want to test it



> Can you be more specific about why you think this is a wrong result, and include a sample repo to demonstrate?

Why not click the playground link.

**Comment by RyanCavanaugh** [comment]
We'll have some new module docs soon that will explain all of this in more detail.

**Comment by RyanCavanaugh** [comment]
@MrHBS probably a preview version available in a couple weeks

**Comment by RyanCavanaugh** [comment]
@MrHBS see https://github.com/microsoft/TypeScript/issues/52593#issuecomment-1559777718
