### ISSUE TITLE
TSDoc @param should be followed by a hyphen

### ISSUE THREAD

**Issue by denizdogan** [microsoft/TypeScript#53755]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: ~1.77.1~ 1.77.2
- OS Version: macOS 13.3

Steps to Reproduce:

Start writing a TypeScript module, using the default TypeScript mode in VSCode:

```ts
function foo(bar: string): number {
  return bar.length;
}
```

Then type `/**` on the preceding line, as such:

```ts
/**
function foo...
```

A JSDoc comment suggestion should pop up. Hit `TAB` to use it, and you get:

```ts
/**
 * 
 * @param bar 
 * @returns 
 */
function foo(bar: string): number {
  return bar.length;
}
```

Note that the `@param bar` is not succeeded by a hyphen/dash/-, which it should [according to TSDoc](https://tsdoc.org/pages/tags/param/):

> The `@param` tag is followed by a parameter name, _followed by a hyphen,_ followed by a description.

Thoughts?

**Comment by RyanCavanaugh** [comment]
We didn't make TSDoc and can't satisfy multiple conflicting style guides.

**Comment by fatcerberus** [comment]
> We didn't make TSDoc

TIL “TSDoc” isn’t just the generic name for “JSDoc in TS” like how “TSX” is JSX-in-TS
