### ISSUE TITLE
Feature request: store constants for different build configurations

### ISSUE THREAD

**Issue by stepancar** [Microsoft/TypeScript#5376]
ASP.Net developers stores global constants in web.config. For different build configurations (Like Test, Debug, Release etc) they have different constants.
They have possibility to get constant by string key, and don't have possibily to chek existence of constant on development-time.

So, I have ts project, and want use different const , for example billingHost in different configurations
>Test: test.billing.com
>Debug: debug.billing.com
>Release: billing.com

What i can do? i can define all constants in common module, and on run-time firstly substitute needed
constants values by configuration values, and then import this constants to consume modules.
I faced problem. I don't want another developers know about what test, debug constants i use.

I think constant should be generated on build-time.
Now I store constants in tsconfig.json 
```javascript
"consts": {
        "comments": "Here you can find your application constants",
        "emails": {
            "comments": "emails for different configurations",
            "sellerEmail": {
                "comments": "seller email, if you testing your app don't use original email!!!",
                "release": "seller@mail.com",
                "debug": "myDebugSeller@mail.com",
                "test": "myTestSeller@mail.com"
            }
        },
        "apiKeys": {
            "comments": "api keys for different configurations",
            "googleMapsApiKey": {
                "comments": "Use another key for testing you google maps, because its very expensive",
                "release": "asd!22asdjk_eweqwerqw",
                "debug": "werwqj!2324324",
                "test": "rwer334225_3423n"
            }
        }
    }
```

And on build-time i generate ts file which contains constants.
I have autocomple in consume files, and another developers can't see my test constants.
All constants stored in one file. Each team member (not necessary developer can change constant in config)

example of usage
![try](https://github.com/stepancar/TypeScript-consts-generator/blob/master/docs/images/screen.png?raw=true)

May be we should investigate integration of this approach to typescript ecosystem?
For example add consts section to tsconfig + build configuration, and provide to compilation context needed consts?
Thank you!

**Comment by stepancar** [comment]
@mhegazy, could you set any label for this issue? Maybe i should provide more info?

**Comment by mhegazy** [comment]
Sorry for the delay. I think i typed up the response but never hit the comment button..

So tsconfig.json is meant to be extensible. so adding additional properties there that you are using in a different tool is a fine proposition. and looks like you are already setup

Now, should the typescript compiler be aware of these properties and generate code for them on the fly, i would say no.

**Comment by stepancar** [comment]
@mhegazy , thank you. Conditional compilation is what we realy need.

**Comment by mhegazy** [comment]
thanks for the reply. closing this ticket.
