### ISSUE TITLE
TS thinks spreading Map into object still has Map properties

### ISSUE THREAD

**Issue by elramus** [microsoft/TypeScript#53765]
# Bug Report

### 🔎 Search Terms

Map
Spread

### 🕗 Version & Regression Information

Not sure when it started, testing on current version. Same behavior observed in Nightly.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Maps.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=5.0.4#code/MYewdgzgLgBAtgTwLIEMAOMC8MwFMDuMqaAFANoCwAUDDGQOQBmII9ANDPQEYoBO9AXWoCAlNWqhIsRADkCxLDADeMAHTrECgL7iqkiCAA2uVYZABzErPnoYASykowwXCEZF0YqtWv5iq81woEiYWehEgA)

### 💻 Code

```ts
const myMap = new Map([
  ['foo', 'bar']
])

// TS thinks this is a Map, but it's not.
const myNewMap = { ...myMap }

// myNewMap.get is not a function 
myNewMap.get('foo') 
```

### 🙁 Actual behavior

TypeScript thinks `get` will be present, along with all the other Map properties. Running the code crashes though, because spreading the Map into the object yields an object. 

### 🙂 Expected behavior

I'm not sure if TS mistakenly thinks the new object _is_ a Map, or if is mistakenly grabbing the properties of the Map class, but one way or another it seems like TS should know that that spreading a Map into an object means no more Map properties.

**Comment by RyanCavanaugh** [comment]
Duplicate #53747, etc

**Comment by elramus** [comment]
@RyanCavanaugh thanks
