### ISSUE TITLE
Difficulty in extracting a function from a TypeScript type with properties

### ISSUE THREAD

**Issue by leobastiani** [microsoft/TypeScript#53760]
# Bug Report

I'm working with the following TypeScript code:

```ts
type MyFunctionWithProperties = {
    <T>(t: T): T;
    someProperty: string;
}

type MyFunctionOnly = Omit<MyFunctionWithProperties, keyof MyFunctionWithProperties>;
```

As you can see, `MyFunctionWithProperties` is a type that includes a generic function signature and a `someProperty` property. I'm trying to extract only the function signature from `MyFunctionWithProperties` and assign it to a new type called `MyFunctionOnly`. However, I'm having trouble doing so.

I've tried using the `Omit` utility type to exclude `someProperty` from `MyFunctionWithProperties`, but I'm not sure what to do with the resulting type. It appears to be an empty object, but I'm expecting it to be a function.

Can someone please help me extract only the function signature from `MyFunctionWithProperties` and assign it to `MyFunctionOnly`? Any suggestions or solutions would be greatly appreciated.

### 🔎 Search Terms

function with property, function with properties

### ⏯ Playground Link and 💻 Code

```ts repro
type MyGenericFunctionWithProperties = {
    <T>(t: T): T;
    someProperty: string;
}

// how do I extract the function from MyFunctionWithProperties?
type MyGenericFunctionOnly = Omit<MyGenericFunctionWithProperties, keyof MyGenericFunctionWithProperties>;
//   ^? type MyGenericFunctionOnly = {}
// it's expected to be a function although it's an empty object

type MyFunctionWithProperties = {
    (): void;
    someProperty: string;
}

type MyFunctionOnly = Omit<MyFunctionWithProperties, keyof MyFunctionWithProperties>;
//   ^? type MyFunctionOnly = {}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/C4TwDgpgBAsiDiEB2EBOBLAxgMQK5M2HQHskB1dYACwAVVjJUiIBnKAXigG8AoKfqAB4AKgD4AFMABcUYQEoZwgNx8BLYgFsIdBmlAyWwDEgDmKgL48eAemtQqxAO5QAJsSgBJKBAAeRgIaEUNTQAGb4hCRIUKH0GrAgeAREpBTUOozMLAD8PKCQCYgoGDgRKUgA8kgANiAcUBUalIJwRWhYSZGplLT0meisADRQANYQIMShhcjtpclRab26TAMsoiq2AgB6uZuUAORsvpCEEC7B7gBG0P4xZVFQ-tXUxLgmVFAHbP7REBpgoCgxEuACsIIQrPloHBOuVFhk9Kt6rwBFBxAooAA3YjoFwqVHqLQIpggAxGdCmCxWTYOZxuTzePyoQLAYJUML3UgxOIJWELHrErK5KG8zmVGp1TiNZowsXwvqIoajcaTUXzbrpBUrVjrGx2fg7IA)

### 🙁 Actual behavior

`MyGenericFunctionOnly` and `MyFunctionOnly` are not functions

### 🙂 Expected behavior

Extracting the function from type

**Comment by jcalz** [comment]
Related to #29261 (and [this comment](https://github.com/microsoft/TypeScript/issues/29261#issuecomment-451536491) in particular)

**Comment by nmain** [comment]
There's [this](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAsiBiBXAdgY2ASwPbIOoeAAsAFAJy0lMwgGcoBeKAbwCgp2oAeAFQD4AKYAC4o3AJQjuAbjYcaWALYQyFCFRAiawUhmQBzGQF8WLUJCgBRAB7aAhuiRpMObuAg9eDUVAg2IyABM6fgA6MNtSPRoRXQAzNSgAQTEGTziEgCUoAH4oUPDI6KSU+k8skWQIADc1GVM3KHgsLC9rOwcUdGxkV0hOOEcunHwiFUpqGl4ZIA) but it doesn't preserve the unbound generic.

**Comment by RyanCavanaugh** [comment]
Mapped types (which is what Omit and Pick are under the hood) intentionally only deal with properties.

The closest behavior you can achieve is probably this:
```ts
type MyGenericFunctionWithProperties = {
    <T>(t: T): T;
    someProperty: string;
}
type NoProperties<T> = { [K in keyof T]: never };
type OnlyCalls<T> = T & NoProperties<T>;

type MyGenericFunctionOnly = OnlyCalls<MyGenericFunctionWithProperties>;
declare const mgfo: MyGenericFunctionOnly;
const s: string = mgfo("hello"); // ok
mgfo.someProperty.toLowerCase(); // Error
```
