### ISSUE TITLE
Incorrect narrowing for union of object types.

### ISSUE THREAD

**Issue by yeah-boi** [microsoft/TypeScript#53766]
I get no warnings or errors for this program in typescript, but the genereated javascript blows up at runtime because of trying to call a string method on a number. The problem is that `t.y` is incorrectly narrowed to `string`.

```
type T = { x: boolean, y: string } | { y: number }

function f(t: T): void
{
    if ("x" in t) console.log(t.y.toUpperCase())
}

const t: T = { x: true, y: 0 }

f(t);

```

Typescript playground link:

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UDeUAeAuKAjA9jgNhAIYB2ANFCJgM7ABOAliQOZQC+UAPspZiQK4BbLBDrsAUOIBm-EgGNgDHCShSAFMEwwAlJgBuOBgBNxScVAtQGUqGoBEqO1ZXBtUOcuoEIAOnw5mDR8QH2AcAFUwSDoAYSJqCDVtbXE2SQ8SWihNWAQeDGy6fggKKigABglpDW0AbnEgA

**Comment by RyanCavanaugh** [comment]
Object types aren't sealed, so you have to have a bit more caution when using `in` due to its implicit narrowing (for a long time TS would *not* narrow here, but people complained too much and promised that they'd never write code this).

One solution is to explicitly mark nonpresent properties:
```ts
type T = { x: boolean, y: string } | { x?: never; y: number }
```
