### ISSUE TITLE
Incorrect TS2304 when using "export = class A {...}"

### ISSUE THREAD

**Issue by klkvsk** [Microsoft/TypeScript#5377]
I am writing an external module (using AMD) that needs to export only a single class. I want to simply import it as `import MyClass = require('./MyClass')`, therefore in MyClass module I use "export =" syntax:
```
export = class MyClass {
    // ...
}
```
This compiles without errors and produces reasonable JS code:
```
define(["require", "exports"], function (require, exports) {
    return (function () {
        function MyClass() { /* ... */ }
        return MyClass;
    })();
});
```
Next, I try to import it:
```
import MyClass = require('./MyClass');
var my: MyClass = new MyClass();
```
Compiling this gives me error at `var my: MyClass`: "TS2304: Cannot find name 'MyClass'".

But, when I change my module export to:
```
class MyClass {
    // ...
}
export = MyClass;
```
everything works okay, however produced JS code seems to be almost the same:
```
define(["require", "exports"], function (require, exports) {
    var MyClass = (function () {
        function MyClass() { /* ... */ }
        return MyClass;
    })();
    return MyClass;
});
```
As far as I can see, the only difference is, it uses temporary variable before return, which has no effect outside of this closure.

I believe both cases should work the same.

**Comment by vladima** [comment]
this is by design. Declaration of class `MyClass` has meanings of both type and value. As for class expression if it has name then this name is added to type\value declaration spaces **inside** the class expression. Outside you can bind class expression to either variable or parameter but this binding will only have value meaning. As a consequence:
```ts
var x = class A {
    f() {
        let a: A; // legal - A has type meaning
        a = new A(); // legal = A has value meaning
    }
}
let y1: A; // illegal - A is not visible here
let y2: x; // illegal - variable declaration adds name `x` only to value declaration space
let y3 = new x(); // legal - x has value meaning
```
