### ISSUE TITLE
Typescript 5 ES Class Decorators runtime error when passing class self-static property

### ISSUE THREAD

**Issue by szdolhan-abs** [microsoft/TypeScript#53778]
# Bug Report
We wanted to migrate to the new native decorators when upgrading to typescript 5, but ran into problem.
I get a runtime error when I pass a static variable of the same class to the class decorator. It seems that static members are initializing **after** decorator execution.

### 🔎 Search Terms

- decorators
- decorators static
- es decorators

### 🕗 Version & Regression Information

Typescript 5+and es decorators. ExperimentalDecorators works well with similar code.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=2&ts=5.1.0-dev.20230414#code/GYVwdgxgLglg9mABAEwKbBmVBhEBnKOAWwFEAbVI1MKACjAEMqAuRAgJ0wHMBKRAbwBQiEYnaooIdklpQG7LhNa4CxcpWpRsCDiGhx2AGkQQEUVAA8oysgzx4AIqlPsGhdtpqWofALwA+AWFREIh8QlIKKho8ADo0DCx6JlRjOQUJHgBuYJEAXxy8wUEAAQTMHHC1KM1aFQj1aKhYgBUAQQBxADk2gFkSHkEIW3tEeuqNGkRvamQ8RAAJFt6AGUbNIRCABxAAIzIYCDY5WCP27r6SRF9EACIw1SIAWjkuW8Li0zACREwCBkgqGuiCwAHcxlVIpM6NkgA)

### 💻 Code

```ts
function defineCustomElement(name: string) {
    return (target: CustomElementConstructor, context: ClassDecoratorContext) => {
        customElements.define(name, target);
    };
}

@defineCustomElement(CustomElement.TAGNAME)
class CustomElement extends HTMLElement{
    public static TAGNAME = "custom-tag";
}

const instance = new CustomElement();
```

### 🙁 Actual behavior

Runtime Error: Cannot read properties of undefined (reading 'TAGNAME') 

### 🙂 Expected behavior

Run without errors.

**Comment by Jamesernator** [comment]
> I get a runtime error when I pass a static variable of the same class to the class decorator. It seems that static members are initializing **after** decorator execution.

This is the correct behaviour, in the decorators proposal all class decorators are evaluated *before* the class is evaluated. ([See 15.8.21](https://arai-a.github.io/ecma262-compare/?pr=2417)).

If you want this sort've behaviour you'll need to use a function that can be called after the class has been fully defined:

```ts
function defineCustomElement(getName: () => string) {
    return function(klass: CustomElementConstructor, ctx: ClassDecoratorContext<CustomElementConstructor>) {
        ctx.addInitializer(function(this: CustomElementConstructor) {
            customElements.define(getName(), this);
        });
    };
}

@defineCustomElement(() => CustomElement.TAGNAME)
class CustomElement extends HTMLElement{
    public static TAGNAME = "custom-tag";
}

const instance = new CustomElement();
```
