### ISSUE TITLE
Inconsistent type inferring behavior

### ISSUE THREAD

**Issue by chernodub** [microsoft/TypeScript#53776]
# Bug Report

Hi, we're having issues using inline call of the generic function decorator in a specific context. Unfortunately, I couldn't find anything related to this on stackoverflow, or here. Please check out the code below and feel free to let me know if more information/context is needed. Thanks!

### 🔎 Search Terms

* `infer generic`
* `infer generic function`

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about **inference** and **generics**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/GYVwdgxgLglg9mABAEwKbFQJwIoiwTwB4AVAEQEMpyA+ACgG8BfALkXoChFEBHPTfAGJhWtAJSIAvNUQAFTHAC2MAM6oSFKtQDcnRAgDKICBFTLlI5JXKsyV8VMQA3ODGQ7G4jly4B6H4gA6IPZGdnZUAA8ABzhMKERQSFgEFFQIWMo1YhlyTHIFZURIqFQwZELwAGswOAB3MABtAF0AGkRiACVTEAAbKDpdRIgRIICo3Pzzdpy8gvtpOUUVLK7lXv6W3VHx2ansiYL2URF52XklVRJV9ekvRExUKBBMJDFJW91ff1HP+8fnpBDWjbA7KUQ6LiMdxhKD4KKoRAAQUwACMYFA8vwNORJGxdFF5PC4vhWMoMTAwABzdw6cLRWLxIbJJCUx7ItEY3L4bG0AD6rlYYBAChRWGOZyWl3Z6Mx3KszQ+XAeTxeEouqACD2UcB6jlQtAa9AJcCJsNYAHIAIwAJgAzObGE1wSEwmgMDg+PgGLpeAQhKw0Ok8iVaKyoNLOVirG1LQAGUSbLgGIwmMy0SxUTy-PzebwAPQA-L8M+QAsBYgBRcgQAAWtHSYG1PQ1PTglOdkM2HlpDbJiDD2NxgYyIbDEdl2Jj8Z0bqwuAI3q4vv4-v7j0numTxlMynTdjxuZzucQheLVjLlerdd7OpbbY7iEYXedQA)

### 💻 Code

```ts
function deferQuery<TData>({}: {
  queryFn: () => Promise<TData>;
  onSuccess: (data: TData) => void;
}) {
    // ...
}

export function decorate<TParams extends unknown[], TResult>(
  func: (...params: TParams) => Promise<TResult>,
  ...params: TParams
): () => Promise<TResult> {
  return () => {
    // ...
    return func(...params);
  };
}

type ArbitraryData = {
  property: string;
};

export function getArbitraryData(_id: number): Promise<ArbitraryData[]> {
  return Promise.resolve([{property: '123'}]);
}

deferQuery({
  queryFn: decorate(getArbitraryData, 10),
  onSuccess(data) {
    //      ^? (parameter) data: unknown
    data.forEach(console.log);
  },
});

const getData = decorate(getArbitraryData, 10);
deferQuery({
  queryFn: getData,
  onSuccess(data) {
    //      ^? (parameter) data: ArbitraryData[]
    data.forEach(console.log);
  },
});
```

### 🙁 Actual behavior

`data` is typed as `ArbitraryData[]` only when the decorated method is stored in a variable.

### 🙂 Expected behavior

`data` is typed as `ArbitraryData[]` in both cases.

```ts
deferQuery({
  queryFn: decorate(getArbitraryData, 10),
  onSuccess(data) {
    //      ^? (parameter) data: ArbitraryData[]
    data.forEach(console.log);
  },
});

const getData = decorate(getArbitraryData, 10);
deferQuery({
  queryFn: getData,
  onSuccess(data) {
    //      ^? (parameter) data: ArbitraryData[]
    data.forEach(console.log);
  },
});
```

**Comment by RyanCavanaugh** [comment]
See #47599

**Comment by chernodub** [comment]
Thanks for pointing this out @RyanCavanaugh! I'm closing this.
