### ISSUE TITLE
TS treats methods within type intersection as overloads instead of narrowing when parameters match 

### ISSUE THREAD

**Issue by Woodz** [microsoft/TypeScript#53777]
# Bug Report

### 🔎 Search Terms

type intersection function return value overload

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type intersection function overloading

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230414#code/C4TwDgpgBAGlC8UDeUBmA7AXFAFASgQD4oBDdEKAXygDJk0tcD5j0BXAWwCMIAnKgFACANhGBQAHthgBuIQHp5UAOoALCgBMA9hADOULlC0A3PsK0kNpdFZLDzAdyjBVAS30ldu1wHN0HCHRxYC0oXWBeV3QfKCjwiEsjVCh0El5eLQcomJCUzh5+Mis+DMjogH4BAGMtdHCw7HCymMQJAEIAOgx8IA)

### 💻 Code

```ts
type X = { fn: () => any } & { fn: () => number }

let x: X;

// Why does b overload and allow this assignment to string instead of narrowing to number and erroring?
const s: string = x!.fn()
```

### 🙁 Actual behavior

TS infers `fn` to be an overloaded method that both take no-args but return different types

### 🙂 Expected behavior

TS infers `fn` to be a single method that has a narrowed return type of `number`

**Comment by MartinJohns** [comment]
This is working as intended. The return types of your intersecting functions are intersected as well, so the return type is `any & number`, which gets simplified to `any`, and `any` is assignable to `string`.

**Comment by Woodz** [comment]
> This is working as intended. The return types of your intersecting functions are intersected as well, so the return type is `any & number`, which gets simplified to `any`, and `any` is assignable to `string`.

For method return types, I don't think the return type should be intersected because we know that the method has to return the narrowed type, not the widened type (which is what intersecting types do).

**Comment by MartinJohns** [comment]
Yeah, what I wrote was nonsense, forget that.

Intersections are considered overloads, and the algorithm to resolve the used overload is a "first match wins", [see this comment](https://github.com/microsoft/TypeScript/issues/50708#issuecomment-1245991306).

> When you call a function, TypeScript tries to figure out the right overload. This process is a "first-success-wins" one, where the first parameter list that's compatible with the arguments gets picked.

In your case the first matching overload returns `any`, which is assignable to `string`. When you swap order of the functions to `{ fn: () => number } & { fn: () => any }` the first resolved one will return `number`, resulting in an error.

**Comment by RyanCavanaugh** [comment]
There's not really a coherent claim on the "obviously correct" behavior of intersection when a function type is encountered. There are a lot of different invariants you might expect to hold and not all of them can be satisfied simultaneously. Even for the case of "identical" parameter lists like here, you quickly have to start questioning what really counts as identical (e.g. zero arg vs one optional arg). The current behavior is at least simple to explain.
