### ISSUE TITLE
Strange type checker errors when disable `StrictNullChecks` option

### ISSUE THREAD

**Issue by yuhuung** [microsoft/TypeScript#53788]
# Bug Report

### 🔎 Search Terms

`strictNullChecks`

### 🕗 Version & Regression Information

- This may not be a bug, but the behavior is confusing
- This changed between enable `strictNullChecks` options or not
- The confusing behavior exists from TSC3.3 to TSC5.0.4(actually all versions I can try in TypeScript Playground)
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?strictNullChecks=false&target=5&jsx=0&module=5&ts=4.2.3#code/GYVwdgxgLglg9mABFApgZygRkQCgIYD8AXImCALYBGKATogD6IBKKEcNAJgDwY0xgBzADSkK1GgD4AlIgDeAKERLEAGxRREeTCTJVaAbkXKYwXHkQAyC8gCeABxRxT5gLxvEAcjiUAVqygeMgrKIZrYLpoAdAAehiEAvogoKmgockahYYgR5vSMAAxxyvHyJfIQKnhoaIgAgukhUDR4YGgwsAg6YrTZiJiGJRVVNQBCDcp2IJQqMBDIza3t8GBdenSMZCoqvf0ZiJPTs4gwaPU4UiRQABYnxzX1wZmINOogNEjXJ5FNLW0dSG4IrsEqV5PJQJB-sh0FAAEy4IJ7NitDSUXpgFAAd0QI3Ohj2JlwlEiJ1q50RT0QyLQcDUkRUcAEOGJP0W-2+cAAyk1+EypFIipkXlA3khgcU9iyFn9loLnq93ohCqD5ChonZ2Bp+KgaMA8BA0gBhJSPJRQewoYiaMA2OUcE52So2AByeHIlpIvF5dodToA8pxaFbdOIBuDwNBltCMFwACoAaRQNiS0VQYA4NQA1kmnIhDRJcHtszYSAmk0J5BTlGoNBASMaIrISiEIABtYsAXR2AyAA)

### 💻 Code

eg.1 
```ts
function test (a?: number | Record<string, number>) {
    let a1: number;
    if (a && typeof a === 'object') {
        a1 = a.x;
    } else {
        a1 = a || 0;  // reports error here when `strictNullChecks` is false
    }
}
```

eg.2

```ts
class A {
    transition: number = 1;
}
class B {
    public transition: number | null = 1;
    public isA (): this is A {
        return this.transition === 1;
    }
}

function test2 () {
    const b = new B();

    if (b.isA()) {
        console.log(b.transition.toString());
        return 1;
    }
    b.transition;  // reports error here when `strictNullChecks` is false 
    return 0;
}
```
eg.3

```ts
export interface C  {
    type?: any;
    displayName?: string;
    displayOrder?: number;
}
function test<TKey extends keyof C> (
    key: TKey,
) {
    let c: C = {}
    c[key] = 1;  // reports error here when `strictNullChecks` is false 
}
```

### 🙁 Actual behavior

When enable `strictNullChecks=true` option, the exmaple code can compile successfully.
But if set `strictNullChecks=false`, it will report errors like:

Error info for eg.1 
```
Type 'number | Record<string, number>' is not assignable to type 'number'.
  Type 'Record<string, number>' is not assignable to type 'number'.
```

Error info for eg.2
```
Property 'transition' does not exist on type 'never'.
```

Error info for eg.3
```
Type 'TKey' cannot be used to index type 'C'.
```

This is very confusing, why it report the error **when `strictNullChecks` is false?**

### 🙂 Expected behavior

It seems that when disable `strictNullChecks`, it reports more "strict" type check error.
I just want to try to understand the strange behavior above for the 3 examples, could you please help? Thanks a lot!

**Comment by RyanCavanaugh** [comment]
These all follow from the assumption that any binding could be inhabited by `null`/`undefined` at any time. This assumption actually works against you in some cases since it means certain narrowings "do nothing" since their operation can't be represented in the type system.
