### ISSUE TITLE
Add support for type annotations for properties in object literals

### ISSUE THREAD

**Issue by frantchessico** [microsoft/TypeScript#53782]
# Type Feature

## 🔍 Search Terms

Currently, TypeScript allows developers to declare object literals with properties, but typing those properties is done inferentially. This can lead to typing issues when the object structure is complex or when there are ambiguities in type inference. One solution to this problem would be to allow the addition of type annotations for properties in object literals, allowing developers to explicitly define the typing for those properties.

Code Example:

```js
const user: {
  name: string;
  age: number;
} = {
  name: "João",
  age: 25
};

```

### With the addition of the proposed feature, the above code could be simplified to:

```js
const user = {
  name: "João",
  age: 25
}: {
  name: string;
  age: number;
};

```

This would make typing more explicit and help avoid type errors in more complex object literals. I believe this feature would be useful for the TypeScript community, and would like to propose its implementation.

**Comment by xiBread** [comment]
I'm confused, how is this any different than what's already available?

**Comment by fatcerberus** [comment]
Yeah, me too; you’ve just changed the order of the values and type annotations.  It’s not any simpler.

**Comment by fatcerberus** [comment]
It seems like you might be looking for `satisfies` (which already exists)?

**Comment by RyanCavanaugh** [comment]
This doesn't seem worth the visual syntactic ambiguity, compared to what's already available with `satisfies` or regular type annotations on the binding itself.
