### ISSUE TITLE
Specification for Enum's needs to use 'SignedInteger' in constant productions, not NumericLiteral

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#538]
Courtsey of @CyrusNajmabadi 

The spec currently lists this in the grammar productions for an Enum:
 
> ConstantEnumMemberSection:
  PropertyName   =   NumericLiteral
  PropertyName   =   NumericLiteral   ,   ConstantEnumMembers
 
This is slightly incorrect (and different from a previous version of the spec).
 
Specifically, previous versions used:
 
>  PropertyName = SignedInteger
 
The approach with "SignedInteger" is likely more correct.  NumericLiteral doesn't allow for things like "-1".  With the grammar productions as they exist in the latest version of the spec "-1" would be thought of as a computed expression.  i.e. the negation expression of the literal '1'.
 
This is important if we consider "-1" as a constant or not in an enum.  Right now we do.  But according to the spec, it would not be.
 
Also, with "PropertyName = NumericLiteral" we can do "Foo = 3.14159" and that would be considered a constant.  That's likely *not* at all what we want

**Comment by jbondc** [comment]
I'm confused by this, is it a breaking change? Prefer NumericLiteral... that's more closely aligned with JavaScript / Number.

A signedInteger enum should be declared as ~:
```
enum<int32> a {
  a, // 0
  b, = 1.1 // error, initializer must be a constant expression of type 'int32'
  c, = -1, // ok
  d, // 1
}
```

**Comment by ahejlsberg** [comment]
No longer an issue. Closing.
