### ISSUE TITLE
TypeScript auto-imports / import suggestions not working reliably

### ISSUE THREAD

**Issue by AlessioGr** [microsoft/TypeScript#53867]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.77.3
- OS Version: MacOS Ventura 13.3.1 (22E261)

Steps to Reproduce:

1. Clone this repository https://github.com/AlessioGr/payload-plugin-lexical/blob/vscode-autosuggest-bug and install the dependencies of both the root and the demo folder (using `yarn install`)
2. Go to the [index.tsx](https://github.com/AlessioGr/payload-plugin-lexical/blob/vscode-autosuggest-bug/src/index.tsx) file and/or the [problemhere.tsx](https://github.com/AlessioGr/payload-plugin-lexical/blob/vscode-autosuggest-bug/demo/src/fields/problemhere.tsx) and try to autocomplete "payload" and "useField".

You will notice that VSCode will auto-complete the `payload` import, but it will not auto-complete the `useField` import which is part of the `payload` package. For comparison, Webstorm is able to auto-complete both. Importing it manually works fine.

I generally find VSCode's autocomplete appearing a lot less compared to Webstorm. I've hand-picked "useField" here, so you can reproduce it and test it out.

**Comment by RyanCavanaugh** [comment]
Auto-import cannot offer imports from your entire hard drive. It can only offer up imports from two places:
 * Files already in your program
 * Listed dependencies in package.json

`node_modules\payload\components\forms.ts` does not match either of those conditions.

**Comment by notchris** [comment]
Isn't something in node_modules considered a listed dependency in a package.json? If not, how would one specify this particular dependency?
