### ISSUE TITLE
in operator infers wrong type when explicitly checking for non-existing property

### ISSUE THREAD

**Issue by raythurnevoid** [microsoft/TypeScript#53868]
# Suggestion

## 🔍 Search Terms

- "in operator"
- in operator check key
- in operator valid key

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Maybe a new tsconfig.json flag for "stricter" in operator type infer.

```
function doStuff(data: {
	nice: string;
} | {
	bad: {
		value: string;
	};
}) {
	if ('nice' in data) {
		console.log(data.nice);
	} else if ('unexistent' in data) {
		console.log(data.bad.value); // unreachable code
	}
}
```

In the example above, the second "if" will always return false, but typescript currently thinks that the type of data is `{ bad: ... }` and moreover doesn't notify about the unreachable code.

## 📃 Motivating Example

Raise a warning or set the type of data to `unknown`

## 💻 Use Cases

- notify the user that the check he is performing is most likely wrong
- raise a warning when signature of a third-party code changes and the user is using the in operator to check for a property

**Comment by polkovnikov-ph** [comment]
TypeScript isn't consistent at choosing whether object types are closed or open, so the use of `in` operator _intentionally_ leads to arbitrary unexpected results.

```typescript
{
    type A = { a(): string };
    type B = { b(): string };
    const f = (x: A | B) => "a" in x ? x.a() : x.b();
    const x = { a: 10, b() { return "hello"; } };
    const y: B = x;
    f(y); // x.a is not a function
}
```

Until TS implements `super` bounds or closed object types, this is indeed working as intended.

**Comment by fatcerberus** [comment]
> TypeScript isn't consistent at choosing whether object types are closed or open

No, it's very consistent that they're open.  Excess property check only applies to directly-assigned object literals and is considered a glorified lint check rather than part of the type system; it isn't meant to enforce type closure.  While it *is* true that the current narrowing behavior of `in` is unsound, that didn't happen without a *lot* of pushback from the TS devs.  Users just wanted to shoot themselves in the foot that badly I guess 😅

**Comment by fatcerberus** [comment]
> it's not a good example because I'm assuming the function's user is correctly following the defined signature.

TypeScript doesn’t have exact types, so passing an object with extra properties is correct according to the rules of the type system.  See #12936
