### ISSUE TITLE
should `.every()` return true when the array being evaluated is empty?

### ISSUE THREAD

**Issue by brignano** [microsoft/TypeScript#53874]
# Bug Report

`.every()` returns `true` when the array being evaluated is empty.

> It doesn't make sense to me why `.every()` would default to `true` if the array is empty.
>
> How could any condition be satisfied by an empty array?

### 🔎 Search Terms

- `.every()`
- default
- returns
- `true`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [ECMAScript Language Specification#sec-array.prototype.every](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.every)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ssl=11&ssc=32&pln=1&pc=1#code/MYewdgzgLgBAhgJwXAngRhgXhgbQORQCm0eANDAcVHgLoDcAUKJLIsigExa6Unm9Q0tRs2jwkqAMwAuGNAQBLMAHMcNbmsYMAZgFcwwKAvAwi0AKIA3QghQAKOLPlLVNAJSyARiBAAbQnBgMADeDDDhMAiEULoIQXAAdITWtnYKWAB8MOmYuRRm1G6MAL4MTOAQfoQJviDKdgVWNvZsqGhuReWQVTV1DVRNqa2cHSIVPbX1jSktEiiSo0A)

### 💻 Code

```ts
const array1 = ['test', 'test'];
const array2 = ['test', 'test1'];
const array3: string[] = [];

function testEvery(a: string[]): boolean {
    return a.every(i => i === 'test');
}

console.log(testEvery(array1));
console.log(testEvery(array2));
console.log(testEvery(array3));
```

### 🙁 Actual behavior

returns

```
true
false
true
```

### 🙂 Expected behavior

returns

```
true
false
false
```

**Comment by MartinJohns** [comment]
That's runtime behaviour of JavaScript. It has nothing to do with TypeScript.

And yes, it should be `true`, because the condition does apply to **every element in the array**.

**Comment by IllusionMH** [comment]
This is behavior specified in ECMAScript standard, not sure why it's bug/question in TS.

Counter point: `every` returns `false` as soon as it encounters item that doesn't satisfy condition. There is no such item.

**Comment by RyanCavanaugh** [comment]
This isn't a TS thing. Anyway, `true` is the identity operand of `AND`, and you can think of `every` as being `f(a[0]) AND f(a[1]) AND f(a[2]) AND ...`. So `[].every` is `true` the same way `5 ^ 0` is `1`, because `1` is the identity operand of multiplication.

**Comment by ritschwumm** [comment]
it's quite useful to have this as a law, regardless of how many elements `a` and `b` have:
```[ ...a, ...b ].every(cond) === a.every(cond) && b.every(cond)```

**Comment by brignano** [comment]
> That's runtime behaviour of JavaScript. It has nothing to do with TypeScript.

Got it, makes sense. 

> And yes, it should be `true`, because the condition does apply to **every element in the array**.

The problem is, at least in my example, every element in an empty array is not equal to test so I was not expecting to get true back when evaluating that condition.

I'll close this issue as it does not appear to be in scope for this repository.

**Comment by fatcerberus** [comment]
> every element in an empty array is not equal to test so I was not expecting to get true back when evaluating that condition.

The specific condition is actually irrelevant in the case of an empty list because there are no values to evaluate it against.  But mathematically, for literally any condition `P` you can think of, `P` is true of all elements of an empty collection by definition.  This is not an arbitrary choice and you will find this to be the case in pretty much any programming language or library with such a method.  From the Wikipedia article I linked above:

> For example, the statement "all cell phones in the room are turned off" will be true when no cell phones are in the room. In this case, the statement "all cell phones in the room are turned on" would also be vacuously true

This behavior is also documented:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every
> `every` acts like the "for all" quantifier in mathematics. In particular, for an empty array, it returns `true`. (It is [vacuously true](https://en.wikipedia.org/wiki/Vacuous_truth) that all elements of the [empty set](https://en.wikipedia.org/wiki/Empty_set#Properties) satisfy any given condition.)
