### ISSUE TITLE
--exactOptionalPropertyTypes conflicts with the `Required` utility type

### ISSUE THREAD

**Issue by rodrigopsasaki** [microsoft/TypeScript#53889]
# Bug Report

`--exactOptionalPropertyTypes` conflicts with the `Required` utility type

### 🔎 Search Terms

I searched for `--exactOptionalPropertyTypes` and discovered this other issue ([52494](https://github.com/microsoft/TypeScript/issues/52494)). However, the solution seems to be applied to only functions (I may be wrong here), so I am opening this new one

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `--exatOptionalPropertyTypes`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=4.4.4#code/C4TwDgpgBAglC8UDeAoK6oCMD8AuKAdgK4C2mEATlAD5REEAmEAZgJYEQMDcKAviigDGAewIBnYFACG+AEoQAjkVYVOAHhgA+BMjQZM+AAwAaPjxRSAdJgDUNniPHCANhEvPhAcwAUVzAEouIA)

### 💻 Code

```ts
type A = {
    b?: number | undefined;
}

const a: Required<A> = {
    b: 0,
};

a.b++;
console.log(a.b);
```

### 🙁 Actual behavior

The `a.b++` operation fails with the following error from TSC:

```
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
project/src/test.ts:9:1 - error TS2532: Object is possibly 'undefined'.

9 a.b++;
  ~~~
```

### 🙂 Expected behavior

I expect the increment operation to succeed given that the `b` property should always be defined in `Required<A>`

**Comment by Andarist** [comment]
`Required` is defined as follows:
```ts
type Required<T> = { [P in keyof T]-?: T[P]; }
```

As we can see, it only removes the optional marker from all properties. So your type becomes `{ b: number | undefined; }` (`undefined` is not removed from the property value) and therefore the error is correct. You might want to use this type if you are interested in removing nullable types from the property values as well:
```ts
type NonNullableRequired<T> = {
  [K in keyof T]-?: NonNullable<T[K]>;
};
```

**Comment by MartinJohns** [comment]
Or differently said: the property **is** required (must be present), but the value can still be `undefined`.

Not okay: `{}` - property `b` is missing (not set).  
Okay: `{ b: undefined }` - property `b` exists and is set to `undefined`.
