### ISSUE TITLE
TypeScript accepts illtyped program with function overload

### ISSUE THREAD

**Issue by nmattia** [microsoft/TypeScript#53886]
# Bug Report

### 🔎 Search Terms

* Function overload

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/AQYwNghgzlwGIHsEB4CCA+YBvAUMYUALhIQJYjABOAphACYIB2YAnsAK6MgAWEjA5tToAuDo1IBHdtQIsAtgCMEYYAF5gAZXlKwACgBEnHn0F19ASgDcOPKCZFK7EIQSVgugA6VSANxIy-MGlRVHMsAF8bfDkID2QAIXRdADNRXQgQ8zVMePNRRBRE62jYhKTU9wzgUOzgeOAAH2BCFg9qBGT4JAA6I14BIQAaYAB9OmoK3PykMuLgGLjElLSqmtUc4bGJgH5RKa7CzFx8E7tGImBA4Lq1YGTdQm5SKG6r6iso08uIIJkoEmeyVI1Fg8UswAA9BDvr9QHxgD8oAhgAoZAADFptDoHXpcfqmNG2U4gezKajdMAIfi6N5WSHQgCyEDYUG4CAA7sAAORaRTKAx9ExCCyEoknGiEdiURjARjUTkFGk-aQffCRSI4EnnQjzFgFW5yhUzBykARJfTcahgSkWaxai6GgrTFAms23OR6noLXTpUSu-hZdY4wUDOjDfTs1xgMxWIA)

### 💻 Code

```ts
 class Foo<A> {
  static readonly unchanged: unique symbol = Symbol("unchanged");
  constructor (private value: A){}

  map<B>(f: (a: A) => B): Foo<B>;
  map<B>(f: (a: A) => B | typeof Foo.unchanged, _def: B): Foo<B>;
  map<B>(f: (a: A) => B, _def?: B): Foo<B> {
      const value = f(this.value);

      value satisfies B; // value can also be `typeof Foo.unchanged`
      console.log(value); // May show 'Symbol("unchanged")`

      return new Foo(value);
  }
}

const myFoo = new Foo<string>("hello");
const newFoo: Foo<string> = myFoo.map((a: string) => Foo.unchanged, "world");
```

### 🙁 Actual behavior

TypeScript doesn't realize that `f` may return `typeof Foo.unchanged` and will happily assign the result to `value` which is of type `B` (and doesn't include `typeof Chan.unchanged`)

### 🙂 Expected behavior

TypeScript should warn that the result of `f(a)` with `a: A` and `f: A -> B | typeof unchanged` cannot be assigned to a value of type `B`

**Comment by MartinJohns** [comment]
The only problem here is that the compiler doesn't warn about the implementation signature of your overload (missing the symbol in the first parameter).

The rest is correct according to the type system. The user is responsible to make sure the implementation matches the signatures.

**Comment by nmattia** [comment]
Ah, that's a surprise!

I assumed it was mostly syntactic sugar around something like this:

```ts
  map<B>(args : { f: (a: A) => B } | { f: (a: A) => B | typeof Foo.unchanged, _def: B }): Foo<B>{
      const value: B = args.f(this.value); // does not typecheck
      ...
  }
```

I'll then you this more explicit version and avoid overloaded function for now. Thanks!

**Comment by MartinJohns** [comment]
Be aware that overloads and unions are not interchangeably. You can't have different return types based on the input type with unions.

Also it matters when calling the function. In case of overloads you can't pass a variable typed as the union of each overload argument, but with unions you can.

```typescript
function overloads(val: string): void;
function overloads(val: number): void;
function overloads(val: string | number) {}

overloads({} as string) // Type string is compatible
overloads({} as number) // Type number is compatible
overloads({} as string | number) // Type string | number is not compatible
```

**Comment by nmattia** [comment]
>  You can't have different return types based on the input type with unions.

Gotcha, luckily I don't need that here.

In general it looks like it's actually fairly easy to shoot yourself in the foot with the overloads, I'll try to avoid it as much as possible then!

**Comment by MartinJohns** [comment]
> it's actually fairly easy to shoot yourself in the foot with the overloads

Yes, it is. Another gotcha is that inference in conditional types does not work with overloads. It'll always use the last overload signature for the type inference.
