### ISSUE TITLE
keyof order affected by far away code change

### ISSUE THREAD

**Issue by adrianimboden** [microsoft/TypeScript#53894]
# Bug Report

### 🔎 Search Terms
- keyof order
- keyof stable
- object order
- keyof deterministic 

### 🕗 Version & Regression Information

Sorry in advance, if this behavior is expected. I did not find any hints to whether it is expected that the result of `keyof` is deterministic or even returns the order as written by the programmer. But I am not a typescript language definition expert, so I may not know how to search for this the proper way.

Also, the compiler behaves like this since this code is possible to compile.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&downlevelIteration=true&noStrictGenericChecks=true&noPropertyAccessFromIndexSignature=true&suppressImplicitAnyIndexErrors=true&ts=5.0.4#code/C4TwDgpgBAqgdgSwPZwCpIJJ2BATgZwgGNhk4AeGAPigF4oAKGKCADxzgBN8o4IA3PFAD8vAUIBcjAIa4A5lJgBKOjT6DcKth24z5UhHABmQjCto1+SBJxFQMUKerwBuAFBu2YJLmBRQkLCIKOioAK5gADYQ5Kg09PBk6Fg4BMSkKLEs7BBcPM64dgWOjMBSqOY0cdk6PAwA+k7imqpQhiaFAOp2ANoAdAOJIUjhUTEAoqxEkWGcMagANFCdVFRLnQC6JT0b7p6s3r5QRmFwJGRQSABGAFbp49i4CBD45ADytzW5ugBKxD6ccj4YBPOByJYfG49ADWEBASCMUEhG1WDGuNykkKWsJA+Ckf2knBQkRAlGCaBGEWi5BxCKRt1WSikMLhdKx9KhtMRyI2OygAG83FAoEQUMCoLJcMyuRyIbcWfDubcNrytvQdu5hUYfIxRXBxTi2nAoDj8CpBcLhXrxfxpDNoPR0QrdkLLQhEQxbfa6LR6Kc5kZDBBOObXZb-AALXBIADuUAARKcvOlgyLpIR45rLQBfMMS3C4PpgML4CMMBVLL1hCAbJRZ3PC3AQYBhXDGyXuXMeE5nDLGnDAgCMaNuUn50icYQAtlc8EsrpOZ3hs6Hhej7o9nvgRzclj149J40t41d47XO93TucUP4XsAAEw7scL3jT2e4JYT19L3ArgWu9cSAeEEtx3PcTyPBND3PNxcyAA)

### 💻 Code
We have a small helper function that forces us to include the list of properties the passed-in object has:
```ts
type UnionToIntersection<U> = (U extends never ? never : (arg: U) => never) extends (arg: infer I) => void ? I : never;

export type UnionToTuple<T> = UnionToIntersection<T extends never ? never : (t: T) => T> extends (_: never) => infer W ? [...UnionToTuple<Exclude<T, W>>, W] : [];

export function objectEntries<Obj extends Record<string, Obj[keyof Obj]>>(obj: Obj, keys: Readonly<UnionToTuple<keyof Obj>>): [keyof Obj, Obj[keyof Obj]][] {
  const arr: [keyof Obj, Obj[keyof Obj]][] = [];
  for (const key in keys) {
    const value = obj[key];
    if (value === undefined) {
      throw "unexpected case";
    }
    arr.push([key, value]);
  }
  return arr;
}


function test1(obj: {a: number, b: number}) {
  objectEntries(obj, ["a", "b"]);
}

function test2(obj: {b: number, a: number}) {
  objectEntries(obj, ["b", "a"]);
}
```

### 🙁 Actual behavior

The second call in `test2` fails to compile because `test1` is also existing in the code.

### 🙂 Expected behavior

Both `test1` and `test2` should compile fine, because there should not be global side effects just code "being there"

**Comment by fatcerberus** [comment]
`UnionToTuple` is an inherently ill-defined operation.  Union order is an implementation detail which roughly depends on the order types are first encountered during compilation; the observed order should be treated as effectively random.

**Comment by RyanCavanaugh** [comment]
Unions are sets and do not have any intrinsic ordering. If you manage to write code that observes an ordering, you should not be taking any dependency on that particular ordering being stable in anyw ay.

**Comment by adrianimboden** [comment]
Ok, just as I suspected. I hope this issue will be found in the future when someone searches it.

Thank you very much :)
