### ISSUE TITLE
[spec] Update accesibility bits in language spec

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#539]
An exported member depends on a (possibly empty) set of named types (section 3.5). Those named types must be at least as accessible as the exported member, or otherwise an error occurs.

named types include classes, interfaces and enums. However though functions\modules are not included in the set of named types in order to be used in typeof expression they should also be accessible. This bit is now missing in the spec

**Comment by ahejlsberg** [comment]
I'm going to close this as Won't Fix. This is ultimately an implementation detail of the .d.ts emitter and not something that is part of the language.
