### ISSUE TITLE
Map - value as class does not infer

### ISSUE THREAD

**Issue by Malix-Off** [microsoft/TypeScript#53905]
# Bug Report

### 🔎 Search Terms

Map, class, value, constructor, new, signature, any

### 🕗 Version & Regression Information

- This is a crash with every typescript versions

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiCWAnCAXaBvAvgKFJGAygKbAD2AdgCbREAeKRVMCyaW2uFq0AtmAA7QAvNHJEA7tACyAgDypE8cgHMANNBQBPfkVIAzOElQA+ABQBtbNGvRzAIjAAjYHfUtUAXVVWb9ykT1XaGIyKi9sDwBKAG4OPQBXcmAUeApoPTBk0kRNU2AAC1J4YCIALmgFJWVIjB9rRCIUeMRyUQleAQA6ZUa8wuKiGOgAemHoAHIxcXGaWn4GqFTydXFCiCINMEQetHBgAGsYMGhQhXjkivhlcjAmhvV4Hn4QYvgUEE1ofMhoMFbxv6aGZaHSdFAQUwAdgADNCAJyRbA4IA)

### 💻 Code

```ts
class First {}
class Second extends First {}

const map = new Map<string, typeof First>([
    ["abc", First],
    ["def", Second],
]);

function factory(choice: string) {
    return new map.get(choice); // 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.ts(7009)
}
```

### 🙁 Actual behavior

Error: `'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.ts(7009)`

**value as class does not infer**

### 🙂 Expected behavior

No error

**value as class inference**

**Comment by xiBread** [comment]
Wrap it in parenthesis and handle the `undefined` case:

```ts
new (map.get(choice)!)
// just used non-null assert for brevity
```

**Comment by yw662** [comment]
```ts
function factory(choice: string) {
    const a = map.get('choice')
    return a ? new a() : undefined
}
```

So that is why.

**Comment by RyanCavanaugh** [comment]
`factory("abc")` is a runtime error:
```
Uncaught TypeError: map.get is not a constructor
    at factory (<anonymous>:10:12)
    at <anonymous>:1:1
factory @ VM565
```

**Comment by Malix-Off** [comment]
> `factory("abc")` is a runtime error:
> 
> ```
> Uncaught TypeError: map.get is not a constructor
>     at factory (<anonymous>:10:12)
>     at <anonymous>:1:1
> factory @ VM565
> ```

[not for me](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiCWAnCAXaBvAvgKFJGAygKbAD2AdgCbREAeKRVMCyaW2uFq0AtmAA7QAvNHJEA7tACyAgDypE8cgHMANNBQBPfkVIAzOElQA+ABQBtbNGvRzAIjAAjYHfUtUAXVVWb9ykT1XaGIyKi9sDwBKAG4OPQBXcmAUeApoPTBk0kRNU2AAC1J4YCIALmgFJWVIjB9rRCIUeMRyUQloUz5+ADplRrzC4qJIyIBCaOgAeknoAHV8xlFSNHywKhAq6ET-PSUiaiFjaABRRERs8oByMXFLmlp+BqhU8nVxQogiDTBEPrRwYAAaxgYGgoQU8WSFXgynIYCaDXU8B4-A2wHgKBAmmgqxBrUua00dy0Om6KAgpgA7AAGakATki2BwnHIEFIICI3RApGUpgyWRypgczjsIwm00MrHK7CAA)

**Comment by Malix-Off** [comment]
Also I don't succeed to make it work with [abstract classes](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgYgSypBA3gL4BQKaGAygKawD2AdgCYLUAeE1zGOeixZVOgQAVABa4W7Ttyy58Aso3wBbYAAcEAXgQNqAdwQBZDQB5IUbAwDmAGgQQAnuup0AZnL4A+ABQBtEgQghD8AIlBYUPsaemYAXVtA4LCmajco0QkoJgSSOIBKAG4SEjcAVwZ4bEYENzgIOihHH1gxOmxYagAuBAsra3zCJKCoaggyqAZdAwQfNXUAOmsxlraO6nz8gEJChGGEAHoDhABhYAYGOkRYUeBOBHOEK0hzzoR3B6nQC3qkITAFvsjggAOpiLi6K4IMTnJjIfoICqpNxWagsLReBAAUSgUEaPQA5Hp9ATWGx1KN0NUGPZ9G0wNQHMAoMtEKhYABrDDAJDKaBleC9bDWBh3CbUezYFTqeGwbAQZCOaFoT4IAnnRykpwuBALCBgHwAdgADMaAJz5EikJQMMB0ZDUBbIOjWHx1eCNZrhECRTa7YG8SA9ARAA)

**Comment by RyanCavanaugh** [comment]
Yes, because there's nothing stopping you from writing
```
    ["qua", First],
```
What you want there is
```
const map = new Map<string, new() => First>([
```

**Comment by Malix-Off** [comment]
Why `new() => First` is working, but not `typeof First`?

**Comment by RyanCavanaugh** [comment]
Those are great questions for the Discord or StackOverflow, but this isn't a support forum.

**Comment by Malix-Off** [comment]
This issue can be deleted
