### ISSUE TITLE
Cannot import JSON files using path aliases

### ISSUE THREAD

**Issue by pauleustice** [microsoft/TypeScript#53908]
# Bug Report

### 🔎 Search Terms

`is:issue json path alias` on GitHub issues
`json path alias typescript` on StackOverflow

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `paths` and `json`

### ⏯ Playground Link

[Stackblitz link with relevant code](https://stackblitz.com/edit/y1y6zm?file=index.ts)

### 💻 Code

```json
{
  "compilerOptions": {
    // other settings removed for terseness
    "resolveJsonModule": true,
    "paths": {
      "@files": [
        "files/src"
      ]
    }
  }
}
```

```ts
// Importing JSON using relative paths works
// import * as sample from './files/src/sample.json';

// Importing JSON using a path alias does not work
import * as sample from '@files/sample.json';

console.log(sample);
```

### 🙁 Actual behavior

`Module not found: Error: Can't resolve '@files/sample.json' in '{{system path goes here}}'`

### 🙂 Expected behavior

I expect to be able to import JSON files using path aliases, as I do with Typescript files. This avoids the use of unnecessarily long relative imports for things like config files, mock data etc.

**Comment by jakebailey** [comment]
Unless I'm mistaken, that's a runtime error, not a TypeScript error message.

TypeScript does not rewrite import paths. What you write is what you get, so if you are using aliases to attempt to shorten import paths, that code will not run unless your runtime also handles it.

Generally, path aliases should not be used to "shorten" import paths. They should be used to inform TypeScript about what works at runtime.

**Comment by pauleustice** [comment]
Thanks Jake, that makes sense. I'll look into it further 👍
