### ISSUE TITLE
Nested object spread destructuring doesn't remove readonly-ness

### ISSUE THREAD

**Issue by pschiffmann** [microsoft/TypeScript#53917]
# Bug Report

The two functions below behave identical at runtime. However, TypeScript flags the second function with an error.
```ts
interface Data {
  readonly nested: Readonly<Record<string, string>>;
}

function updateNested_1(data: Data, k: string, v: string): Data {
  const nested = { ...testData.nested };
  nested[k] = v;
  return { ...data, nested };
}

function updateNested_2(data: Data, k: string, v: string): Data {
  const {
    nested: { ...nested },
  } = data;
  nested[k] = v; // Index signature in type '{ readonly [x: string]: string; }' only permits reading.ts(2542)
  return { ...data, nested };
}
```

### 🔎 Search Terms

`destruct readonly`

### 🕗 Version & Regression Information

Tested in version 5.0.4.

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCJzHZBvAUM5KCOAEwHsQAbAT2RAgGdISAuZAJWPKuoB5OEZKCV5MooAOYAaZGMkA+eQG5cAX1y4YAVxAIwwCsi0AHEhggA5RswD6ARgAUZzG3SYZAazZyQ05ADdvMHFfAEpXDCw8AkEQJjprCBJkAF4cZAA6LMgmNzgM+iYk5FUVAkLmAG0PAF1UgLLCCDAtKBB0rIznOBkK4tK1DW1dfUMTZ0tEkhsAJidIiPdkL1lgyRlA1ZCJcLRInHxkWPjoggSi1g6svuTVKUPVeu7Gm+q6tP9Goha2q67I3pTEoqdS4Y5gZA5MB5RZYNKnG5sU4EAAebAARDAyGR0fczshqBiAEZwKC4h73AZgigMMiUCAZShkCQOcbmKwXewOKF5GTolG45Do+gAd3RoQKQJS0sh1jykouoRUxzpDKZLLZkA5tjmPIBQoFfNF4oVzFSMr1mFNSSVuCAA)

### 🙁 Actual behavior

Since the spread-destructuring creates a copy of the original object, it should lose it's `readonly` modifier.

### 🙂 Expected behavior

The spread-destructured object retains it's `readonly` modifier.

Interestingly, this works already if `nested` doesn't have an index signature.

**Comment by RyanCavanaugh** [comment]
Expressions of type `{ ...x }` always have the same type as `x`. Doing anything else breaks other scenarios in terms of both correctness and performance.

**Comment by fatcerberus** [comment]
@RyanCavanaugh Hm, that doesn't explain why the behavior differs between `updateNested_1` and `updateNested_2` though.  The former has no error as `nested` seems to lose its `readonly`ness.

**Comment by pschiffmann** [comment]
> Expressions of type `{ ...x }` always have the same type as `x`.

Maybe we're talking about different situations? In TypeScript 5.0.4 (with `"strict": true`), creating an object with a spread operation removes `readonly`ness from it's type:
```ts
function f(original: Readonly<Record<string, string>>) {
  original.test = "something"; // Index signature in type 'Readonly<Record<string, string>>' only permits reading.ts(2542)

  const copy = { ...original };
  copy.test = "something"; // This is OK, no errors.
}
```

[Playground link](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=2&pc=1#code/GYVwdgxgLglg9mABMAFHATjA5jMBDAGwC5EAlAUzwBMECBPAHgogyoYGcpMwsAaRTtywA+YQEpEAbwBQiRBmy5CAOijlOiALyIAROzgBbclAAWuLDoDcsxCzAaWABzpapiZR4U58BRAF9rOSc6VXUoVz1DYzMeK2k-aSA)

**Comment by RyanCavanaugh** [comment]
I think I misread the original the first time around. The rules for destructuring and expressions are not necessarily different and are geared toward different inference cases. Behaviors are desirable in certain cases, and it's a zero-sum game of which one gets picked for which, so I don't think there's anything to change here.
