### ISSUE TITLE
Expected tuple type as function return value is not infered from written code

### ISSUE THREAD

**Issue by jonathanfady** [microsoft/TypeScript#53911]
Hello TypeScript team !

# Bug Report

I have an issue when expecting a tuple as a function return value and trying to return a tuple without explicitly specifiying that it is a tuple.
TypeScript assumes that I am returning any Array, although the syntax of the code is that of a tuple.

I have the following function:
```ts
(value) => [value.some((element) => (element))] // NOK
```
The type of value is : `(parameter) value: [boolean, boolean, boolean, boolean, boolean, boolean]`
The expected return type is `[boolean]`

With the above function, I get the following type error from TypeScript:
```ts
Argument of type '(value: [boolean, boolean, boolean, boolean, boolean, boolean]) => boolean[]' is not assignable to parameter of type '(value: [boolean, boolean, boolean, boolean, boolean, boolean]) => [boolean]'.
  Type 'boolean[]' is not assignable to type '[boolean]'.
    Target requires 1 element(s) but source may have fewer.
```
I can tell TypeScript specifically that the return type is indeed [boolean] with the following syntaxes:
```ts
(value): [boolean] => [value.some((element) => (element))] // OK
(value) => [value.some((element) => (element))] as [boolean] // OK
```

### 🔎 Search Terms

tuple

### 🕗 Version & Regression Information

I have TypeScript version 4.9.5 and work on VS Code 1.77.3.

### 💻 Code

```ts
(value) => [value.some((element) => (element))]
// (parameter) value: [boolean, boolean, boolean, boolean, boolean, boolean]
// => [boolean]

// Error
Argument of type '(value: [boolean, boolean, boolean, boolean, boolean, boolean]) => boolean[]' is not assignable to parameter of type '(value: [boolean, boolean, boolean, boolean, boolean, boolean]) => [boolean]'.
  Type 'boolean[]' is not assignable to type '[boolean]'.
    Target requires 1 element(s) but source may have fewer.
```

### 🙁 Actual behavior

I get the following error:
Argument of type '(value: [boolean, boolean, boolean, boolean, boolean, boolean]) => boolean[]' is not assignable to parameter of type '(value: [boolean, boolean, boolean, boolean, boolean, boolean]) => [boolean]'.
  Type 'boolean[]' is not assignable to type '[boolean]'.
    Target requires 1 element(s) but source may have fewer.

### 🙂 Expected behavior

I would expect to not get any error, since I used the "some" method that returns a boolean, and I put it in an array with [], which insures that I have one element. For me, the types seem coherent.
How could TypeScript handle this correctly ?

**Comment by MartinJohns** [comment]
If there's no contextual type information available to indicate that the result should be a tuple TypeScript errs on the side of returning an array. This is by design.

**Comment by MartinJohns** [comment]
In most cases the values are used as arrays, and inferring a tuple instead would be cumbersome (and it would have been a massive breaking changes, as tuples were added way after arrays).

If contextually it can be inferred that it's to be used as a tuple, it will be a tuple. Otherwise you can add a type annotation.

**Comment by RyanCavanaugh** [comment]
In general inferring the very-narrowest type for a function leads to suboptimal behavior in a lot of cases. Inference tries to pick the type that accurately reflects what's going on without being overspecific, but can't always know what you meant to do.

**Comment by jonathanfady** [comment]
Ok, thanks for your responses.
Too bad for the tuple lovers out there, but I guess it makes sense that the tuple is the new kid on the block and still needs to prove his worth to be deemed inferable against the big array boss !
Have a nice day !

**Comment by fatcerberus** [comment]
@jonathanfady You can write `[ .. ] as const` to get TS to infer a tuple type in cases where it can’t do so automatically.  This is safer than using an explicit type assertion like `as [boolean]`.

**Comment by jonathanfady** [comment]
> @jonathanfady You can write `[..] as const` to get TS to infer a tuple type in cases where it can’t do so automatically. This is safer than using an explicit type assertion like `as [boolean]`.

@fatcerberus Not sure this works as you expected. If I use my previous example, I get the following error in the editor with `as const` :
```
The type 'readonly [boolean]' is 'readonly' and cannot be assigned to the mutable type '[boolean]'.ts(4104)
```
Do you have any thoughts on this ?
