### ISSUE TITLE
Different inferencing in function generic between normal function and arrow function.

### ISSUE THREAD

**Issue by Beingbook** [microsoft/TypeScript#53924]
# Bug Report

### 🔎 Search Terms

`typescript function generic inference`, `typescript inference arrow function`

### 🕗 Version & Regression Information

5.0.4, nightly build are being reproduced

### ⏯ Playground Link

https://tsplay.dev/mp0YXm

### 💻 Code

```ts

function test<T = unknown>(options: {
    a: (c: T) => void,
    b: () => T
}) {}

test({
    a: (c) => { c }, // c is number
    b: () => 123
})

test({
    b: () => 123,
    a: (c) => { return c }, // c is number
})

test({
    b() { return 123 },
    a(c) { return c }, // c is number
})

test({
    a(c) { return c }, // c is unknown, expected number as above inferences
    b() { return 123 }
})
```

### 🙁 Actual behavior

last 'a' parameter 'c' inner `test()` inferred as unknown

### 🙂 Expected behavior

last 'a' parameter 'c' inner `test()` inferred as number

**Comment by jcalz** [comment]
This is probably a duplicate of #47599 and is currently the best we can do according to #48538, which explains the limitation you've got here.

**Comment by Beingbook** [comment]
thank you for letting know me, close this issue as duplicated.
