### ISSUE TITLE
Feature: typescript used to typecheck API/AJAX responses

### ISSUE THREAD

**Issue by ducin** [Microsoft/TypeScript#5392]
Actually, it's not typescript itself, but a couple of more tools used along.

The idea is to typecheck runtime responses - whether they conform to typescript types. TS does typecheck in compille time and the AJAX responses come in runtime, therefore TS can't do that on its own. But if we use [typson](https://github.com/lbovet/typson) to dump TS types down to JSON Schemas and to use a JSON Schema validator along with it to do checking in runtime. The idea is also described in https://github.com/lbovet/typson/issues/37.

I know typson is *not* a part of typescript. But it's doable to configure such tool stack for developers. And the benefits would be really great to typecheck a real API, especially, that developers (end-users of typescript) woudln't have to write anything more than they do now (as long as the AJAX calling function, whatever it is, calls the provided ts-json-schema-validation-mechanism function).

It could be also a built-in feature of TypeScript, though, it would create a dependency on typson, which might not be what you want. What do you think of such idea? Are you interested in using typescript to do runtime API typecheck?

**Comment by DanielRosenwasser** [comment]
This seems related to #1573 and #5125.

**Comment by mhegazy** [comment]
I do not think this belongs in the core compiler. as you mentioned. I would say you need an extensible emitter in the TS compiler, that you can leverage to get to what what you want. see my comment in https://github.com/Microsoft/TypeScript/issues/5125#issuecomment-156328141 for more details.
