### ISSUE TITLE
Generic with conditional type inference

### ISSUE THREAD

**Issue by kriskw1999** [microsoft/TypeScript#53928]
# Suggestion
## 🔍 Search Terms
conditional typing, generic with conditional typing, if statement check with generics

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion
I have searched for similar examples but I have not found them. 

My feature request is based on type inference when dealing with conditional operators depending on some generic arguments (really complicated to say, much more clear in the sandbox proposed). The idea behind this feature request is to have the generic inferred with a js check as done in the example that makes compute the conditional operator bound to it because in the scenario proposed after the if check the type will never change so also all the conditional typing bound to it should be computed. 

Actually, I know that the example is really simple, but can be extended to create really elastic types if possible and also smooth js + ts flows with these kinds of checks. Let me know! 

## 📃 Motivating Example
https://www.typescriptlang.org/play?#code/C4TwDgpgBAggPAFShAHsCA7AJgZygcgEN8oAfAgI3wD4oBeKAbwCgo2owBGALigVfZgATLySp02PERIB+AgDMAlgCccwEr3w4IAYwD22fMwC+zZvoxqoenk0K8MAVwC2FCMuP0mAtvagA2EzMLKz0RJgoHFzcPLxZ2KEioTgAGIPMDK3Q1ADEML0RkNExcAmIyShoACjBCEAAbPUIsXngEagBKelp49kV5GrrG5oA6Lno6BmkO3oS2GwBtWoamrDHOAF0vAE4fKE8Ieu1vOfYwpaHVsaEthiEhPdNjIA

## 💻 Use Cases
This applies to every scenario in which we have a conditional type depending on some generic.

**Comment by jcalz** [comment]
Duplicate of #33014 (all issues related to narrowing generic type parameters seem to be pointed there)

**Comment by kriskw1999** [comment]
@jcalz right thanks!
