### ISSUE TITLE
switch case object deleted

### ISSUE THREAD

**Issue by james-tindal** [microsoft/TypeScript#53927]
# Bug Report
### 🔎 Search Terms

"Left side of comma operator is unused and has no side effects"

### 🕗 Version & Regression Information

Typescript version 5.0.2 and 5.0.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAYw9gdgzgLgBAawKYE84F44CICGXiiSxw4ZwDecAZgFxwAUAlBgHxzjRgA2SAdF2ADm9XFmYBfQtHgAjMpVoNm6Nhyjc+A4Vhli4ktfBDzqdJq3ZEN-ISJB7JwcjgA0cGW5DiA2shQBdXiomYCA)

### 💻 Code

```ts
const key = "a"

const a = { f: () => console.log("a") }
const b = { f: () => console.log("b") }
const c = { f: () => console.log("c") }

{a, b, c}[key].f()
```

### 🙁 Actual behavior

- The first two items in the object literal are underlined, throwing error: "Left side of comma operator is unused and has no side effects".
- `.f()` is underlined. "Property 'f' does not exist on type 'string[]'"
- If I use `@ts-expect-error`, the transpiled code has `[key].f()` instead of `{a, b, c}[key].f()`

### 🙂 Expected behavior

I expect it to behave identically as if I had written any of the following:
- `~{a, b, c}[key].f()`
- `const x = {a, b, c}[key].f()`
- `;({a, b, c})[key].f()`
- `;({a, b, c}[key]).f()`
- `;({a, b, c}[key].f())`

Not randomly deleting bits of code!

**Comment by fatcerberus** [comment]
This code as written is incorrect; you’ve actually written this:

```ts
{
    a, b, c;
}
[key].f();
```

In other words, the object literal is parsed as a block statement—in TS as well as JS.  You have to put object literals in parentheses if they’re the first thing in a statement.
