### ISSUE TITLE
Confusing rules around function parameter names in a type

### ISSUE THREAD

**Issue by phillipb** [microsoft/TypeScript#53933]
# Bug Report

In auditing some code, I've noticed something that doesn't seem like it should compile. In >=4.95, the following code compiles without an issue, but in <=4.7.4, there is an error. Why is it possible to specify an object for the name of a parameter? This code was likely the result of a bad copy/paste, but TS isn't erroring on it. Am I missing something about the syntax? Also, is the discrepancy between versions intended? 

```ts repro
const DEFAULT_NUM_PAGINATED_RESULTS = 10;
type IPaginatedParams = {first?: number; after?: string;}

type GetPaginatedResults = <Obj, Key extends keyof Obj>(

  items: Obj[],
  
  { first = DEFAULT_NUM_PAGINATED_RESULTS, after }: IPaginatedParams,
  
  key: Key
  
) => { items: Obj[]; hasMore: boolean };
```

Playground links for [4.7.4](https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBAIgUQGIEECqAZAKgfQHJoCyOACigOICSeKWCcOASggMqZYswC8MAjAAwBuAFBQAngAcApjEokAhgHMAlmHlQpAEwUAneQFsI3GAG8AZsp3QA-AC4YYAK76ARlJ2CY8sxp12Y0DqqioIAvsKikjLkUlAKKmoamoxSEI4ANlBGPAA8APIuAFYANDAA0lJiMFIAHhpgmkYA1pUgZjAFhQB8ABQRMDDKGob2nQDaALrFwgMzpjAWVrA8iKjs+ESkFNS09Eys7Cyl3r4wofZySqrqWroGENOzAy1i9hVic8IAlNxd80NSEYdIqTTwAC3kEEIIB0UnsLhAIHSUnkYDOIiAA) vs [4.9.5](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAIgUQGIEECqAZAKgfQHJoCyOACigOICSeKWCcOASggMqZYswC8MAjAAwBuAFBQAngAcApjEokAhgHMAlmHlQpAEwUAneQFsI3GAG8AZsp3QA-AC4YYAK76ARlJ2CY8sxp12Y0DqqioIAvsKikjLkUlAKKmoamoxSEI4ANlBGPAA8APIuAFYANDAA0lJiMFIAHhpgmkYA1pUgZjAFhQB8ABQRMDDKGob2nQDaALrFwgMzpjAWVrA8iKjs+ESkFNS09Eys7Cyl3r4wofZySqrqWroGENOzAy1i9hVic8IAlNxd80NSEYdIqTTwAC3kEEIIB0UnsLhAIHSUnkYDOIiAA)

### 🔎 Search Terms

function parameter names

**Comment by RyanCavanaugh** [comment]
Looks like an unintended consequence of #49089

**Comment by RyanCavanaugh** [comment]
Minimal:
```ts
// Should syntax error
type Foo = ({ first = 0 }: { first?: number }) => unknown;
```
