### ISSUE TITLE
Function return type wrong when too many different shapes returned

### ISSUE THREAD

**Issue by dummdidumm** [microsoft/TypeScript#53931]
# Bug Report

### 🔎 Search Terms

function return type widen narrow

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about function return types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/GYVwdgxgLglg9mABMAhjANgHgCqIKYAeUeYAJgM6IBKeEcATqZuVPTGAOYA0i4A1mDgB3MAD5RACkQB6aYlJx2HRHTAtEuQsTKUAdPvlw85MAHIoKgBYpOeRDYCeUS0oBQASBYooIcgC5EMBAAWwAjPHouD1JvFADsVwBKeMQAbw96PB96JBioFABuRFcAXwLXV1BIWAREIXoEDglEtNdEGTlfJXtKVXValHR0RDhQgCtaKEoFYzMLCGtbezAnF042xBhgRAkAWW9LXXobBWDmxFFEAAZdAFYW9Pb2zOykVAwJABYrz55Hp-a5BAEAgxn8yEG5DwUQB7QiDXoAQAROwAG6DGCkAD6vgiYBQwTwSJhsNxOQJeGRxBYxI27RKiXK9Iq7S2O32ziOJzgZxalxu91aAJeIByEI+3yufzpTyBILBAVQ6ChJIB8IYyJQILg4CgWLocHQChEtNhKjghuNYACAGYpTKGUzECUWZttnsDlyyDzzvy7g8ZbINC5eihcZRnHYOCQIt48KREABBaDwMAAEViAFooA4AA52KBwRDhQIoegNITxwwiRCFvyBuSpRBy0HkcGhC3oPA2HjqxHN1jdEqIAA+aXw5YYAH4AuBSHhgOwq8Ox0EhjKRWL3ugvlcpeOWwqIcroROEQFTFqamRYljgjA20osbmGrnyKZnYkNi6NmyPZzjm9XkLmuf0hSeINsBDFQwyhCNLCjGNjmIBNk2vDN8mzPMCyLEt8UnSsEytWs4HrAEgybQ82wCDtDW7JAVwPYFW3bTt6OdUdAhAddhSyUU3jQHdJT+ZtmKPJUoU-J0f2ePicnKH8+gsTIgXQKAAHUGk4RAAF46i0ppGVcINYQAPSnCoqhTWo2A4SwoHOf4-w5Q5ANOX1QMFf5ZNeJj5Wo48VTPDVEBRMB0XQTEcShclCWJXgYvxQkqWMKAkWdaTXWcz03J9PlPIDXjfMosSAok08+01bVdX1TsrXig0jWEa1EDtDLvyy90XK9dz8oFQqnk3JASv88Fyt7Sd+0vayb3yO8H3IJ8XzgN8PxdZlfy6nLuWAv0vI3OThtE0bFUhOwyg6jYhoUiolMQFTuKgKgYDsiw9Ns+zmnKEyzIsoA)

### 💻 Code

```ts
function fail<T extends Record<string, unknown>>( // doing const T extends ... doesn't change anything
	status: number,
	data: T
): T {
	return data; 
};

function wrong() {
  // using as const on all objects doesn't change anything
  if (Math.random() > 0.5) {
    return fail(404, {
      success: false,
      error: "invalid_username",
      username: "test",
    });
  }

  if (Math.random() > 0.5) {
    return fail(400, {
      success: false,
      error: "account_cooldown",
      cooldown: 30,
    });
  }

  if (Math.random() > 0.5) {
    // This causes the generated ActionData-type to be narrowed down to:
    // { success: boolean, error: string } | { error?: undefined } | null
    return fail(400, { success: false, error: 'actiondata_missing_props' })
  }

  if (Math.random() > 0.5) {
    // This causes the generated ActionData-type to be narrowed down to:
    // { success: boolean } | { success: boolean } | null
    return fail(400, { success: false });
  }

  return;
}

const resultWrong = wrong();
//      ^?

function right() {
  if (Math.random() > 0.5) {
    return { success: false, error: "invalid_username", username: "test" };
  }

  if (Math.random() > 0.5) {
    return { success: false, error: "account_cooldown", cooldown: 30 };
  }

  if (Math.random() > 0.5) {
    return { success: false, error: 'actiondata_missing_props' }
  }

  if (Math.random() > 0.5) {
    return { success: false };
  }

  return;
}

const resultRight = right();
//       ^?

```

### 🙁 Actual behavior

The return type of the function is just `{ success: boolean }` when returning too many different shapes with a common base through an identity-like function. It doesn't happen when the shapes are returned directly.

### 🙂 Expected behavior

Infered return type should be the same as when returning the object shapes directly

**Comment by RyanCavanaugh** [comment]
These examples are meaningfully different. In `right`, we can be statically sure that there aren't additional properties in any of the object literals. In `wrong`, we can't, since `fail`'s declaration doesn't preclude the existence of them.

**Comment by fatcerberus** [comment]
> how would I type a function that says "I really don't return anything wider than the shape I have determined"

Narrower, because an object with more properties than its type asks for is considered a subtype.  But yes, that would require exact types.

**Comment by RyanCavanaugh** [comment]
> how would I type a function that says "I really don't return anything wider than the shape I have determined"?

Right, the crux of this is that currently the only thing determined to have zero extra properties is an actual-itself object literal. Given exact types, the behavior would be different once `fail` promised to return an `exact T`
