### ISSUE TITLE
dts resolve to CJS entry dts instead of ESM entry dts

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#53949]
# Bug Report

### 🔎 Search Terms

- dts resolve priority
- conditional exports

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```
==> reproduce1.cjs <==
require('@sinclair/typebox')

==> reproduce2.mjs <==
await import('@sinclair/typebox')

==> /path/to/node_modules/@sinclair/typebox/cjs/package.json <==
{"type":"commonjs"}

==> /path/to/node_modules/@sinclair/typebox/esm/package.json <==
{"type":"module"}
```

https://github.com/loynoir/typebox/blob/feat-esm/package.json#L13-L56

### 🙁 Actual behavior

reproduce1.cjs
```js
require('@sinclair/typebox')
```

dts resolve to `node_modules/@sinclair/typebox/cjs/typebox.d.ts`

reproduce2.mjs
```js
await import('@sinclair/typebox')
```

dts resolve to `node_modules/@sinclair/typebox/cjs/typebox.d.ts`

### 🙂 Expected behavior

reproduce1.cjs
```js
require('@sinclair/typebox')
```

dts resolve to `node_modules/@sinclair/typebox/cjs/typebox.d.ts`

reproduce2.mjs
```js
await import('@sinclair/typebox')
```

dts resolve to `node_modules/@sinclair/typebox/esm/typebox.d.ts`

### Related

https://github.com/sinclairzx81/typebox/pull/400#issuecomment-1517786546

https://github.com/microsoft/TypeScript/issues/53948

https://github.com/microsoft/TypeScript/issues/52593

**Comment by RyanCavanaugh** [comment]
ESM resolution is not broken across the board.

It sounds like you have `moduleResolution` set to "node" or "classic"; it should be "node12".

Please create a complete repro (including tsconfig.json) in a new issue if you have found a bug. Thanks!

**Comment by fatcerberus** [comment]
> "node12"

Preeetttyyy sure that won’t work. :wink:
AFAIR `node12` never shipped and `node16` is the lowest (barring legacy `node`), right?

**Comment by RyanCavanaugh** [comment]
😵‍💫 thanks

**Comment by loynoir** [comment]
> Please create a complete repro (including tsconfig.json) in a new issue if you have found a bug. Thanks!

Close in favor of https://github.com/microsoft/TypeScript/issues/53958
