### ISSUE TITLE
Typeguard function returns wrong result

### ISSUE THREAD

**Issue by stegano** [microsoft/TypeScript#53945]
# Bug Report

### 🕗 Version & Regression Information

- v4.8.4

### 💻 Code

```ts
// modules.ts
export const someEnv: string | undefined = process.env.TEST;
export const isString = (v: any): v is string => {
  if (typeof v === "string") {
    return true;
  }
  return false;
};

if (isString(someEnv)) {
  console.log(someEnv); // <- "`someEnv` type is string" works fine here.
}
```
![스크린샷 2023-04-21 오후 1 31 26](https://user-images.githubusercontent.com/11916476/233541280-f4f5f000-d8d0-4e0a-8657-10300d4b47ad.png)

```ts
// app.ts
import { someEnv, isString } from "./modules.ts";

if (isString(someEnv)) {
  console.log(someEnv);  // <- The `someEnv` type must be a `string`, but in this case, it is displayed as `string | undefined`
}
```
![스크린샷 2023-04-21 오후 1 31 54](https://user-images.githubusercontent.com/11916476/233541291-edd59402-fb24-4ced-a809-624d37b50c89.png)

- When the value passed as an argument is in the same file as the TypeGuard function, it can infer types correctly, but when the value passed as an argument is a variable from another file, it seems that type inference is not performed correctly.
 
### 🙁 Actual behavior

- If the result of executing the isString function is true, then the type of someEnv should be string, but it is being displayed as string | undefined.

### 🙂 Expected behavior

- If the result of executing the isString function is true, then the type of someEnv should be string, and it should be displayed as string.

**Comment by whzx5byb** [comment]
```ts repro
// @strict: true
// @filename: modules.ts
export declare const someEnv: string | undefined

// @filename: app.ts
import { someEnv } from "./modules";
declare function isString(v: any): v is string;

if (isString(someEnv)) {
  someEnv.charAt(0)
// ^? 
// Actual: (alias) const someEnv: string | undefined
// Expected: (alias) const someEnv: string
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=5.0.4#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoEEAzeAGywDsBDAWyzSoHsATDUyAOmkhywA8AHerGihGWRMQqwsoRPTIxQkejQCiZAG5oYCMgHNQAH1AYyoomSyMceMOCKlKNNBT58OXeFQFDQAb0XKWGrqoAC+oASwyqAARGzADMysMQDcOKLiktIEJsjwcqDwkADKcPB6ABSaoBRkAJ4AlGghRYplemk48ASgFUWlOroVSqoaDQ1+OKABo+psiAAWkgCC0BUADA02oAB6APw4oUA)

It seems like a tooltip error since `someEnv` is actually narrowed to `string`.

**Comment by stegano** [comment]
> ```ts
> // @strict: true
> // @filename: modules.ts
> export declare const someEnv: string | undefined
> 
> // @filename: app.ts
> import { someEnv } from "./modules";
> declare function isString(v: any): v is string;
> 
> if (isString(someEnv)) {
>   someEnv.charAt(0)
> // ^? 
> // Actual: (alias) const someEnv: string | undefined
> // Expected: (alias) const someEnv: string
> }
> ```
> 
> [Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=5.0.4#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoEEAzeAGywDsBDAWyzSoHsATDUyAOmkhywA8AHerGihGWRMQqwsoRPTIxQkejQCiZAG5oYCMgHNQAH1AYyoomSyMceMOCKlKNNBT58OXeFQFDQAb0XKWGrqoAC+oASwyqAARGzADMysMQDcOKLiktIEJsjwcqDwkADKcPB6ABSaoBRkAJ4AlGghRYplemk48ASgFUWlOroVSqoaDQ1+OKABo+psiAAWkgCC0BUADA02oAB6APw4oUA)
> 
> It seems like a tooltip error since `someEnv` is actually narrowed to `string`.

Hi @whzx5byb,
Thanks for reply. Is this a bug?
