### ISSUE TITLE
Narrowing return type inside a generic function using object map

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#53952]
# Bug Report

Incorrectly narrowing type inside a generic function where the return type is indexed from an object.

### 🔎 Search Terms

Generics, Mapped types, index types

### 🕗 Version & Regression Information

- This is a crash No
- This changed between versions - on version 3.3.3333 did not error, but was not correct type either
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics, index types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeAoK6oEMBcUB2ArgLYBGEATigL4oqiRQBCCyaGJA-LgM7DkCWeAObVa9aAFkYABRaoMWXDAA0bdCVyNRKAGYE8AY2D8A9nihCIwaeRM7+AGwjcAYifIA5KwHd3AawAeL2Bfcj8oCAAPYAg8ABNuKD8IEDsoKWkAPgAKPB9-XGDQvwBKXAyAbSL-AF1WBX4dKFz8sIR4RAByTE6S+oUMcisCcnMkRSgAFgBmKBoFeYxG5ryQ-3aukl7+gagh4BGxqA0oTpJz8865tQGAeluoAFEAJWeAeWeoAFooGxNIcigU49KD8RJEMHcQRCUHmcSncYnXgCYQAbjmVxIBGAewgAEcCPwhnFYVB4Z0YJ0AHTZABM01ptJKNwU9yg1TaYIssQo-AMUBMADcKMCrgAfU5bKDcEygnEGTDmMgCvAOEBQACMAqawAAFiZuNBBZgHARnMoybqjSazdL9QQHCS8JhyLZvJboPtDmTwNBgLLmFahjdFug9W78BB3Y9Xe5sp0AKp4Px4EzePAAQl61CAA)

### 💻 Code

```ts
type A = {
    a: number
}

type B = {
    b?: string
}

type MAP = {
    a: A,
    b: B
}

function getProfilesForNetwork<Network extends keyof MAP>(network: Network): MAP[Network] {
    if (network === 'a') {
        return { a: 43 }
    }
    if (network === 'b') {
        return { b: 'bbbbb' }
        // ERROR - Property 'a' is missing in type '{ b: string; }' but required in type 'A'.(2322)
        // Network is generic over 'a' | 'b' so it can be only 1 of those values, the value should narrow the return type to B here
    }
    throw new Error('Unknown!')
}
```

### 🙁 Actual behavior

TS expects the return type to be `A & B`.

### 🙂 Expected behavior

The `network === 'a' / network === 'b'` should narrow the return type and should be either A or B.

**Comment by RyanCavanaugh** [comment]
This isn't doing what you think it's doing; there isn't narrowing on type parameters like the code sample implies:
```ts
function getProfilesForNetwork<Network extends keyof MAP>(network: Network): MAP[Network] {
    if (network === 'a') {
        return { a: 43 }
    }
    if (network === 'b') {
        return { a: 32 } // <- no error
    }
    throw new Error('Unknown!')
}
```
See #33014
