### ISSUE TITLE
dts resolve to CJS entry dts instead of ESM entry dts when not included in tsconfig

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#53958]
# Bug Report

dts resolve to CJS entry dts instead of ESM entry dts when js not included in tsconfig

### 🔎 Search Terms

-  dts resolve priority
- tsconfig
- javascript
- `// @ts-check`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```js
await import('@sinclair/typebox')
```

https://github.com/loynoir/reproduce-typescript-53958

```sh
$ npm exec -- tsc --showConfig  | grep checkJs
        "checkJs": true
$ npm exec -- tsc --showConfig  | grep include -A 4
    "include": [
        "./src/**/*",
        "./test/**/*",
        "./reproduce2/**/*"
    ],
```

### 🙁 Actual behavior

- `./reproduce1/test-esm-dts-resolve-1.mjs`
- `./reproduce1/test-esm-dts-resolve-2.mjs`
- `./reproduce1/test-mts-dts-resolve.mts`

dts resolve to `./node_modules/@sinclair/typebox/cjs/typebox.d.ts`

### 🙂 Expected behavior

dts resolve to `./node_modules/@sinclair/typebox/esm/typebox.d.ts`

**Comment by RyanCavanaugh** [comment]
The files in `reproduce1` don't correspond to any tsconfig file, so nothing causes them to have `moduleResolution: "nodenext"` as is required to do node16 module resolution
