### ISSUE TITLE
Multi file namespaces and access.

### ISSUE THREAD

**Issue by theduke** [Microsoft/TypeScript#5395]
I want to split a namespace accross multiple files.

I would expect to be able to access unexported classes/interfaces/etc within the namespace, even if they reside in another file.

This does not seem possible:

```javascript
// file: a.ts

namespace Ns {
  class A {
  }
}
```

```javascript
// file: b.ts
/// <reference path="a.js" />
namespace Ns {
  class B extends A {
  }}
}
```

This results in the error `Cannot find name 'A'`.

Is there any compiler option or method to enable this?

**Comment by DanielRosenwasser** [comment]
You need to export the declaration of `A` for it to be visible in other declarations of your namespace. Let me know how that works out.

* `a.ts`
    ```TypeScript
    namespace Ns {
        export class A {
        }
    }
    ```

* `b.ts`
    ```TypeScript
    namespace Ns {
        class B extends A {
        }
    }
```

**Comment by smac89** [comment]
The proposed answer does not work:
`a.ts`

```typescript
namespace Ns {
    export class A {
    }
}
export = Ns;
```
`b.ts`

```typescript
/// <reference path="./a.ts" />
namespace Ns {
    export class B extends A {
    }
}

export = Ns;
```

`c.ts`

```typescript
import * as a from './a';
import * as b from './b';

let bClass = new b.B();

```

Compiling `c.ts`, I get:

> TSError: ⨯ Unable to compile TypeScript
> b.ts (3,28): Cannot find name 'A'. (2304)

**Comment by RyanCavanaugh** [comment]
@smac89 see https://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules

**Comment by smac89** [comment]
@RyanCavanaugh  What am I to be seeing? The example (Version 2) shown does not help my question.

If I was trying to use the `Twix` class from a file called `main.ts`, how would `main.ts` look? That's more of what my confusion is about.
