### ISSUE TITLE
AMD import side effect order is wrong.

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#53969]
# Bug Report

```ts
import 'side-effect'
import { x } from 'mod'

console.log(x)
```

### 🔎 Search Terms

AMD side effect order

### 🕗 Version & Regression Information

I tested 5.0.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&moduleResolution=99&module=2&esModuleInterop=false#code/JYWwDg9gTgLgBAcgM7ACYFMC06BmP0DGMCAUKJLHAN5wAecAvnDlBCIiBKqSQRAHZIIAG3QA6YRADmACloBKEkA)

### 💻 Code

```ts
define(["require", "exports", "mod", "side-effect"], function (require, exports, mod_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    console.log(mod_1.x);
});
```

This is wrong. `side-effect` should run before `mod`

**Comment by RyanCavanaugh** [comment]
AMD doesn't specify load order between two dependencies of the same module.
