### ISSUE TITLE
Infer Correct Parameter Type From Argument (v5, const type parameter)

### ISSUE THREAD

**Issue by tusharf5** [microsoft/TypeScript#53972]
# Bug Report

### 🔎 Search Terms

generic infer parameter type from argument

### 🕗 Version & Regression Information

This is the behavior in version 5 since I am using the new `const` type feature

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAchDOwIBMCSA7AxgGwK7IgB4AVKCADyXWXigHsAjAKwk2AD4oBeKAbwCgoUANoBrCCCgBLdFHEg6AMyjEAugH4AXCrETVZShGq1GLNoKFR1UAAoBDAE7Apd7ITiIUGHPiLFdIKrsnAA+UAx0dNgQdugWQtoRUTHoANz8AL7p-KCQsAhIaFh4BMgAouR2ALZg0dz5nkU+BIQCQmCORsDavFCYABZS2MjaiA4yAOapUPBSDNiT2ui4VQwQDlBZmezZAPS7ULnQHoXeJRAV1bXQUrS9HQ5dWuGR0bFQYb0DQ8jPSW-oAA0MzmC3QEz+rxSm02-H4+ygAGUINE2FBFFIUTR0Q46FUoHZDuBHuE7PAUPRZFJgLQTl5ir4iZAcuBoMjUcA6A4SAYqNjTKxgMCANK8ozYulNc4kYL1NoieTSWTyJRQYWqbTCgL6Ch82jABy4CDxKxyCRi4xmhTKYgmoTWfzyVR2qBLCAAN3WJs12ot-OYgpN1kVuvFtBVNpdDt9octAvMlkTpvZgq5JG1Iu17BdCSg6A9XqTrrzBYc3pLnoc6S2LLyABE7MA7AwyRAAEqsLnIYisuUWKQjPMrNZViwQKp2IajA2TdJCLkTACq6GpPRNA6Ww-Wc8s6GqEGn43BO6EuBX3T4LoGrFEh9nJq2Qi2NaOSJRqYcxAK9RTbDTFgbJsW3JDtMC7HtIEBCxeg3Q5DQgaYF2XVc+CgM8UK+fob20A0jRhDJYR2OEEV-TlP2-AB3IZsEpbBJH6OxPWkZAoAAMnoBwl3PAA6dDgG469MFEHE8SgQDm1bUDwN7I5iIOAB1LDZFQODJE5NDyUOLCCQiJjSK5FRexkAl0TPNgpDoKlgCgZA6AQNJrIorlRHhA5XGAfo6FwCZ+mkRznNoCilKgFSkEQPyCVoQlEFiZBXEs6BXzJGZPIo2RmzoJiACJ9PIxAsrktVpFoeBcDAMA6HJFj1LWLToH+aEJzAehlCCxsCWwGiMSxfU6Bmd80UUXF8VtBFUGshior6SyxkndBrI89rqRLFBevCaBCUlM5fBlJloCCqQBjIdBSseeBXLq-qOXoAM0VFSaQSqIZHBSuw8mS21FDM5xLPRGRkAAQWoUjCAsMCTus0hY39MwhTBmbrNFaHaQKelmj8TgeC2hkWmIbN2AACkcCZtABziSBFdgAEptFyim1U4eVHmAXAHHSzjIrfDk02ISnqzhV8yYmHlkZu2GRT9FHGm23HMYaU4cYxuX5RkdHNWrPYDg8+qUToCiDCuOpbPsgByfyHGE9zPO83ziERFKvOGdadLqdSZEUdY6ou0VXyG0TtagLLVfOLKxcFbi32gLKhYK8HwuN+B5vk5z6gxaggeQEHxOA9tOwcbtWUJlXFbXRNYNwiAoMTJDzxw+Cq82KCMip7IE6T5zuJr6luL3KoEKgBE2-N4TABlyQqA4oQ2dewPWoCci3aDWTA7FwTTX1FW4DFqQ7qQu5Fx1oBZxBUe3N-QOhrObV2+vdz2A593s-fxAPg8ZYmVi6aaHEeNg6P4OPh7wHktSfoFRt6YGpBBaAPA06A2BgNYAoMhDZ0knnAukFoLrkHBXE8HEuIoRwRYDI-Ai79hLpeMu2D64mi7heCuDcMhNxbnCeeoggEgLAQsCBwAoGd04shfivd+4IlYbQQAoOT8CAA)

### 💻 Code

```ts
type NestedInclude<T extends object> = {
  [key in keyof T]?: T[key] extends object
    ? Partial<NestedInclude<T[key]>> | boolean
    : boolean;
};

type NestedIncludedExample = NestedInclude<{
  parent: { child: string; sibling: number };
}>;

// type NestedIncludeExample is { parent?: boolean | { child?: boolean, sibling?: boolean } }
// Basically, it converts each field to a ?: boolean

// Select fields from a type based on its NestedInclude type
type Selector<T extends object, K extends NestedInclude<T>> = {
  [key in keyof K]: K[key] extends true
    ? key extends keyof T
      ? T[key]
      : never
    : K[key] extends object
    ? key extends keyof T
      ? T[key] extends object
        ? Selector<T[key], K[key]>
        : never
      : never
    : never;
};

type DatabaseRecordType = {
  id: number;
  email: string;
  orgUnit: {
    id: number;
    name: string;
    unit: {
      check: string;
    };
  };
};

type SelectorTest = Selector<
  DatabaseRecordType,
  { id: true; orgUnit: { unit: { check: true } } }
>;

// SelectorTest will only have id & orgUnit.unit.check from DatabaseRecordType type

// When I try to use the above Selector Type in a function it doesn;t work
// although it works when I test it as a standalone type as shown above "SelectorTest"

// K is supposed to be the boolean map of what all fields to select from T
// It has a constraint that it needs to be a NestedInclude<T> type which ensures
// the select object K has similar shape as T
function findAndSelect<
  const T extends object,
  const K extends NestedInclude<T> = NestedInclude<T>
>(arg: Arg<T, K>): Selector<T, K> {
  return arg as Selector<T, K>;
}

type Arg<T extends object, K extends NestedInclude<T> = NestedInclude<T>> = {
  include: K;
};

// the below example doesn't work although TS should be able to infer the
// K type from the "include" object. See "Arg"
const doesntWork = findAndSelect<DatabaseRecordType>({
  include: {
    id: true,
    orgUnit: true,
  },
});

doesntWork.orgUnit.name; // doesnt work ❌

// the example below works because type K is explicit
// Seems like TS is not able to infer the K type from the include argument correctly
const worksWithExplicitType = findAndSelect<
  DatabaseRecordType,
  {
    id: true;
    orgUnit: true;
  }
>({
  include: {
    id: true,
    orgUnit: true,
  },
});

worksWithExplicitType.orgUnit.name; // works ✅
```

### 🙁 Actual behavior

The `findAndSelect` generic function does not correctly infer the generic type parameter `K` from the argument. Instead it uses the default value. 

### 🙂 Expected behavior

The `findAndSelect` generic function should be able to infer the type of generic type parameter `K` from the passed argument instead of using the default value of the type parameter.

**Comment by MartinJohns** [comment]
This is working as intended. Type argument inference is all or nothing. If one argument is provided, all arguments must/should be provided, no inference happens.

You want #26242.

**Comment by tusharf5** [comment]
It's not correctly inferring the type from the argument. If you look at the "doesntwork" example, TS should have inferred the type of K from the passed "include" object but it actually used the default value of the type variable instead.

**Comment by MartinJohns** [comment]
In your "doesntwork" example you call `findAndSelect` by explicitly providing one type argument (`DatabaseRecordType`), as a result the second type argument **will not be inferred** and is using the default type. This is working as intended.

**Comment by tusharf5** [comment]
[Just tried it](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygHgIKILyIYBOMYA5gDQQIaIBC+hUJ5AfABQCGRZAXItgqIARtz70AlPwYBvAFCJERFFBBEkongG45AXzlzqYWsrQgANlEUFUGTAHJs9jo-tD7dexINzQkWAjI6FAATDiMxKSURrQMBJFsXDz8giJi0lL0iPKKyqrqadp6BjFWphah1kEYIeyu7p7ePkA). You are correct, I didn't know about this. Thanks!

So https://github.com/microsoft/TypeScript/issues/26242 should be able to get the above code working as intended.

**Comment by jcalz** [comment]
Note that the phrase "working as intended" here means that the language is behaving the way *the TypeScript language maintainers* intend for it to do, as opposed to it being a bug or a design limitation.  @MartinJohns is saying it is *currently* "working as intended" in this sense, which has little to do with whether *you* intended for it to do something else.

**Comment by RyanCavanaugh** [comment]
Maybe someday we'll have a "Working as Intended but only for compat reasons" label 😅

**Comment by fatcerberus** [comment]
> Working as Intended but only for compat reasons

This is just `wontfix` with extra steps
