### ISSUE TITLE
Allow some way of specifying a 'fragment type'

### ISSUE THREAD

**Issue by Meowtimer** [Microsoft/TypeScript#5398]
React's setState(state) method accepts an object with only some of the total set of keys found in a component's state but to express that in Typescript the definition of the interface passed to React.Component[Props, State] has to be somewhat sacrificed by making all fields optional (?):

```ts
interface State { stateField1?: number; stateField2?: number; }
class MyComponent extends React.Component<any, State> {
... this.setState({ stateField1: 123 }); ...
}
```
Better IMO would be to have some way of specifying that the argument to setState is a 'fragment' of State.

```ts
class Component<Props, State> {
  ...
  setState(update: fragmentof State);
}

interface State { stateField1: number; stateField2: number; }
var s: State = { stateField1: 123 }; // ts error
this.setState({ stateField1: 123 }); // ts ok
```

**Comment by ivogabe** [comment]
Looks like the same suggestion as #4889

**Comment by mhegazy** [comment]
Yup, looks like a duplicate. thanks @ivogabe
