### ISSUE TITLE
typed const

### ISSUE THREAD

**Issue by holynewbie** [microsoft/TypeScript#53981]
# Suggestion

## 🔍 Search Terms

as const typed

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

```ts
type RouteItem = { readonly path: string };

const routes = [
    { path: '/abc/:bcd' },
    { path: '/bcde' }
] as const;
```

`as const` tells the compiler that the `routes` is const, but I want to tell the programmer that item in `routes` must satisfies `RouteItem` so that there won't be some unexpected properties in `routes` item just like 

```ts
const routes = [
    { path: '/abc/:bcd' },
    { other: 'abc' },
    'some string'
] as const;
```

## 📃 Motivating Example

```ts
type RouteItem = { readonly path: string };

const routes = [
    { path: '/abc/:bcd' }
] as readonly RouteItem[] as const;
```

**Comment by MartinJohns** [comment]
```typescript
const routes = [
    { path: '/abc/:bcd' },
    { path: '/bcde' }
] as const satisfies readonly RouteItem[];
```
