### ISSUE TITLE
Omit<Foo, 'foo'> does more than omitting the 'foo' property

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#53994]
# Bug Report

Omit seems to not work as I'd expect it to, if I do an `Omit<Foo, 'foo'>` the result is not just that the `'foo'` property is omitted from the `Foo` type.

### 🔎 Search Terms

- omit in:title

### 🕗 Version & Regression Information

Reproduces in v5.0.4, not sure about the rest.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwghgGwQIzgYwNZQLxQBQCUOAfFAG4D2AlgCYDcAUA6JFACITIUCuAdmhBo5YiFOiwAyKAG8oaOPwgIAXCKSpMAGigAzBNwDOAC1Xx14qAF9GzcNA5c+AmgDkKAMX3HhAeQC2VMAAPA48ijTaAOR6hkaRxIxAA)

### 💻 Code

```ts
type Callback = () => void;

type Debounced = Callback & { cancel: Callback, flush: Callback };

type DebouncedNoFlush = Omit<Debounced, 'flush'>;
```

### 🙁 Actual behavior

`DebouncedNoFlush` is no longer a function for some reason.

### 🙂 Expected behavior

`DebouncedNoFlush` should still be a function.

**Comment by RyanCavanaugh** [comment]
See discussion in https://github.com/microsoft/TypeScript/issues/53169
