### ISSUE TITLE
Generic Extract alone cannot be used from uninstantiated generic parameter

### ISSUE THREAD

**Issue by erwanvivien** [microsoft/TypeScript#53998]
# Bug Report

### 🔎 Search Terms

- Extract
- Generic
- Type union

### 🕗 Version & Regression Information

- This is a bug
- This is the behavior in every version I tried, even nightly

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAgmCWAFA9gZ2FAvAKCnqAPlAN677lgCGwAFgFxQBEA9ADbIDm8AdowNxlyeAEbIAJiAbEAvgPLTBhEoorV6TZgFdUEAE78V+URKlRulALYQG6XTw58osxQuyhIUFOkRqssBF7AANqMVLSMALoC7tCBAELiIAA8iDAAKgASUBAAHsAQ3GKonmjAPrQAfH4Aonm6lADGwElwSKUANCRQYeqpmU4VIcYgkQLMzFAxJegJEinpWbn5hcWB5TRVmFC1wPVNLQEdXT0MfVnSg4zDkVAAZFBBUVDjUADuyLoA1qjYL1PxiXm-SWBSK0zKak22zqjWarUCnWI3TUpwWAyGiRu92QwgAVhAmo4Xu8vj8-uBYqVZskztk8qDVqV1lCdns4Yd0IjkbRUf0LhiJFiuq8IPBdGIGFdNBxGE4iRMSd9fhN-lTAbSQStwcy-AAKeGlO7HFGeNHSACUApGT2JHyV2GwDWQ3HQ3UNW0oqBA3AaUCBi3pWrWkN1ihOpsy7UUxGGnQAdAnkGBgPBnahpAwAPIWeDNABKEAAjpoIOgAJLcXOdADkw2rVXuMcSpzVczOFQU5tOumQOZ0SW4mlYrE2VVI5F0EGAml03DMQ9Y2FcTpdGGAFjAfn9dOWYODlVDeHDZyjImb4Op-oq2HNWDHZDApSvup6XOGTnNS6AA)

### 💻 Code

```ts
type ApiPost =
    | {
        path: "/something1";
        body: {};
    }
    | {
        path: "/something2";
        body: { name: string; };
    }

type PostPath = ApiPost["path"];
type PostBody<PATH extends PostPath> = Extract<ApiPost, { path: PATH }>["body"];
// type PostBody<PATH extends PostPath> = Extract<ApiPost, { path: PATH }>["body"] & []; // works
// type PostBody<PATH extends PostPath> = Extract<ApiPost, { path: PATH }>["body"] & object; // works
// type PostBody<PATH extends PostPath> = Extract<ApiPost, { path: PATH }>["body"] & { weird: "bug" }; //works
// type PostBody<PATH extends PostPath> = (ApiPost & { path: PATH })["body"] // works

const post = async <PATH extends PostPath>(
    path: PATH,
    {body, ...options}: Omit<RequestInit, 'body'> & {body: PostBody<PATH>}
): Promise<null> => {
    return null
}

const tmp = <PATH extends PostPath>(
  path: PATH,
  body: PostBody<PATH>
) => {
  post<PATH>(path, { body })
}
```

### 🙁 Actual behavior

It brings an error where it SHOULD accept the type, adding random types makes the error disappear

### 🙂 Expected behavior

I should be able to use the first type as it does the same as every other types

**Comment by ahejlsberg** [comment]
The issue here appears to be that the type `PostBody<PATH>` diverges when normalized for reading vs. writing--effectively, the type ends up not being assignable to itself! This happens early on in `isRelatedTo`, before we even check if the source and target types have identical object identities. We definitely need an identity check to happen first.

**Comment by ahejlsberg** [comment]
Simpler repro:

```ts
function fx1<P extends PostPath>(x: { body: PostBody<P> }, y: { body: PostBody<P> }) {
    x = y;  // Error, but shouldn't be
}
```
