### ISSUE TITLE
Type narrowing does not work when accessing a Partial<Record> with a Union type as the key

### ISSUE THREAD

**Issue by ChrisRZen** [microsoft/TypeScript#54003]
# Bug Report

### 🔎 Search Terms
type narrowing, union, if, undefined, partial

### 🕗 Version & Regression Information

I saw this initially with 5.0.4 I used the playground below to try with other versions as old as 3.3

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing union types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?suppressImplicitAnyIndexErrors=false&ts=5.1.0-dev.20230424#code/PTAEGECcFMEMBdqlqAqgOwJYHt2ngJ4AOSA7pvABagDO2AtkgDYXSSxO3ySboDmNAFCESoAMrdefDDjwBeUACIAZtmyLQAHyUAjWJA3bFegF6LBgkBBgIkKGAGNskACahyVZKCL74mDqAAStBOrqAArjRStLCYbjK4gk7oNPCgjs4uAOoUlAAKvv5MCegA0tAEAFygBZB+HAA8waEuDRI8-CUANFwdfAB8-aAKAN6CoBNKqurVKphmggC+Fkm4qRE00CUAKsTQ5QQ0w6AAFADWFdXtUiUAlJWpfcNDY5OgmMonGa45VLX1xSwuAOAG0LgQALqgACEcgU4XQLmgyl40Bct1Arzekxg8HCkDw32yuX+RRKoPBUKsu1EAHJHtFtAikSj0Gjae8juhsGlYDQonx0LAdEwkPBsPg9qB6ZJ+LSAHTjSbLN64-F4RSIVLmZaWMDXfigIWQSDYciG0jOM5HVnQYRSg18ZqZY7O1wNBn8HqegYWZLrH1ulyVR1B45YiYqNSKWYoha6-1pSLQR0HMMKc6XXpSe4+56YpUTD4nQMhTJgipQ2HwxHI1HogvYnHQPEE7P8IMVyGgamUTBHHz86BHKhivYOSghM6F0Aq5utjVa+A6oA)

### 💻 Code

```ts
type ExplicitUnion = "foo" | "bar" | "baz"

const recordWithPartialUnionKey: Partial<Record<ExplicitUnion, string>> = {
    "foo": "fiz"
}


const useUnionTypeKeys = (key: ExplicitUnion):string => {
    if(recordWithPartialUnionKey[key] !== undefined) {
        return recordWithPartialUnionKey[key] // This fails the function const
    }
    return "test"
}

// Create a Union type with some literal strings
type StringUnion = "foo" | "bar" | "baz"

// Create a record with a partial Record using said Union
const recordWithPartialUnionKey: Partial<Record<StringUnion, string>> = {
    "foo": "fiz"
}


const useUnionTypeKeys = (key: StringUnion):string => {
    if(recordWithPartialUnionKey[key] !== undefined) {
        return recordWithPartialUnionKey[key] // Type 'string | undefined' is not assignable to type 'string'.
    }
    return "test"
}

// String narrowing works fine
type StringRecord = Record<string, string>

const stringRecord:StringRecord = {
    "foo": "fiz"
}

const useStringKeyRecord = (key: string):string => {
    if(stringRecord[key] !== undefined) {
        return stringRecord[key] // This passes the typecheck
    }
    return "test"
}
```

### 🙁 Actual behavior

When checking if a key exists on a `Partial<Record>` with a key value type set to a union of string literals, the type of the value is not narrowed down in the same way as it is for a `Record` with a `string` key in a similar situation.

### 🙂 Expected behavior

When checking if a key exists on a `Partial<Record>` with a key value type set to a union of string literals, the type of the value is narrowed to exclude undefined

**Comment by RyanCavanaugh** [comment]
There's no narrowing going on in the bottom example.

Duplicate #48227, etc

**Comment by ChrisRZen** [comment]
> There's no narrowing going on in the bottom example.
> 
> Duplicate #48227, etc

Ah I see. I forgot about the `noUncheckedIndexedAccess` config which would cause the second example to fail. 

@RyanCavanaugh I tried looking through the FAQ and it sounds like this has come up a lot. Did I miss a question that covers this? Is it valid to consider this a bug?

**Comment by RyanCavanaugh** [comment]
This should be in the FAQ.

I would say this is really more of a feature request, since to do it soundly requires tracking information that is currently not considered. Conservative implementations of this have also incurred too-large performance hits, so it's a trade-off.
