### ISSUE TITLE
Inference regression (5.0.4 vs 4.9.5) with nullable enum function parameter

### ISSUE THREAD

**Issue by cakoose** [microsoft/TypeScript#54005]
# Bug Report

### 🔎 Search Terms

inference string null function parameter 

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/KYOwrgtgBAKgFgSxAcygbygQygXigck3wBooAjXAskqAXwG4AoRgMzBAGMAXBAexCgsAFIyhioAJ2DIEAZy4TMPfgGUuSsLIDyAB2UhZALigrgAG2Ddd+2QB54SZAD5io8fwDCcTCmDGh8hpGsIgoUAA+UOBmZgCUuE5QAG68CAAmpAD0mVC2ALR5UABKwBC8ScBQXHCVAAaR0Wa1WCBpVTVQwBISvBJQyLzAslgA7pgAngB0jLHGKenobmKy5pZcQhjZuQVQAIJpbT6dAB46ZggcCFxV4zqVmBLIkKDXtQ4ozT5t1ZVdPX0DIajCbTcRgqC8PR8AzGKQyeSKfRqILWaGyVzg9wgLw+ZB+CHY7y+LI5ACiRSKWiKUCQyQArJMAAyTAAs5DA1xAvGutKSLMmAE5JnTjDBbpV8AF1FxNKLQqgGmAYvEcIl5ml8DThlzrphZLIEMgQJgyBYqrwbncCEIANbAcbGBGOFVq1Ia0HiWixJi0ZjAU69a5sTj6KArCzcWwAaXtMBOXFAaWGTpQTiEOh6OmCpgjXAACpm7DHxjAnLNkm7FmDqj0RlFgHXSd1ekJ8DUYrx8N7GL7GP6dIHLZUc2sC5Ci7H44nkwpHIk8GglgScb5-HaHVBizAXRX0kwwZCbAB+YwjqxQ-gTktOehQLb5QolMoVdp1I+fVqvzrNgGDYaYMYph7Jg+wDCRri4cUTFWc8bGjSd-QTVoZwkOdcCXLYPF4CAIBeTorhqPpeBYL8yHMXg63YaEoFwiAyIkYZeA5Fpvg6P5en6P9gSAsFIl2boJlsNB12MLdaCcJc+IE8Z4OvJggA)

### 💻 Code

```ts
enum Thing { a = 'a', b = 'b', };

function f(
    registrationStatusOptions: SelectOptions<Thing>,
    onChange: (status: Thing | null) => void, // <-- Remove the `| null` and the error goes away.
): void {
    select({ // <-- Add an explicit type argument `Thing` and the error goes away.
        options: registrationStatusOptions,
        onChange: onChange, // ERROR in v5.0.4 but not in v4.9.5: Type '(status: Thing | null) => void' is not assignable to type '(key: string) => void'.
    });
}

export function select<KeyT extends string>(props: SelectProps<KeyT>): void {
    throw new Error('hello');
}

export type SelectProps<KeyT extends string> = {
    onChange: (key: KeyT) => void;
    options?: SelectOptions<KeyT>; // <-- Remove the `?` and the error goes away.
};

export type SelectOptions<KeyT extends string> =
    // Comment either of the below union members out and the error goes away.
    | Array<{key: KeyT}>
    | Array<KeyT>;
```

### 🙁 Actual behavior

1. Got a type error; see "ERROR" comment above. Looks like the type argument to `select(...)` is being inferred incorrectly.
2. Minor perturbations of the code cause the error to go away; see other comments above.

This was extracted from some React UI code.

### 🙂 Expected behavior

TypeScript 4.9.5 infers the type argument I wanted. I was hoping TypeScript 5.0.4 would do the same.

**Comment by fatcerberus** [comment]
Educated guess: Since this involves enums and the behavior changes between 4.9 and 5.0, this is likely fallout from https://github.com/microsoft/TypeScript/pull/50528.

**Comment by RyanCavanaugh** [comment]
Not enums.

This is weird since removing the constraint also fixes it. Bisecting.

```ts repro
type Thing = 'a' | 'b';

function f(
    options: SelectOptions<Thing>,
    onChange: (status: Thing | null) => void, // <-- Remove the `| null` and the error goes away.
): void {
    select({ // <-- Add an explicit type argument `Thing` and the error goes away.
        options,
        onChange, // ERROR in v5.0.4 but not in v4.9.5: Type '(status: Thing | null) => void' is not assignable to type '(key: string) => void'.
    });
}

declare function select<KeyT extends string>(props: SelectProps<KeyT>): void;

type SelectProps<KeyT extends string> = {
    options?: SelectOptions<KeyT>; // <-- Remove the `?` and the error goes away.
    onChange: (key: KeyT) => void;
};

type SelectOptions<KeyT extends string> =
    // Comment either of the below union members out and the error goes away.
    | Array<{key: KeyT}>
    | Array<KeyT>;
```
