### ISSUE TITLE
Conditional types produce incorrect typings when used with literal types

### ISSUE THREAD

**Issue by Danchieke** [microsoft/TypeScript#54009]
# Bug Report

### 🔎 Search Terms

Conditional types, union types, literal types, boolean

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics, union types and booleans

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAKhDOwA8MB8UC8soQB7AgDsATeKQiANwgCcoB+cq2gbQF0oAuWdgbgCh+AGwjAoubnERIARgHs5IgIaF0WFsBoBXCABoAZkqHwIbASLEhJCZAGYAPgBZ7AVjVQWL3bbNA)

### 💻 Code

```ts 
type Test<T> = T extends never ? never[] : T[];

let x: Test<boolean> = [true, false];
let y: Test<3|4|5> = [5,3];
```

### 🙁 Actual behavior

Compiles with errors
```
Type 'boolean[]' is not assignable to type 'false[] | true[]'.
  Type 'boolean[]' is not assignable to type 'false[]'.
    Type 'boolean' is not assignable to type 'false'.
Type '(3 | 5)[]' is not assignable to type '3[] | 4[] | 5[]'.
  Type '(3 | 5)[]' is not assignable to type '3[]'.
    Type '3 | 5' is not assignable to type '3'.
      Type '5' is not assignable to type '3'.
```

`x` is of type `true[] | false[]`
`y` is of type `3[] | 4[] | 5[]`

### 🙂 Expected behavior

`x` be of type `boolean[]`
`y` be of type `(3|4|5)[]`
Compiles with no errors

**Comment by MartinJohns** [comment]
This is working as intended. Check the section about distributive conditional types in the handbook.

**Comment by MartinJohns** [comment]
@RyanCavanaugh FYI, not sure if you saw it, but your bot is often going haywire.

**Comment by fatcerberus** [comment]
Robot apocalypse -
Expectation: Skynet becoming self-aware
Reality: Mass-produced robots with faulty programming shorting out and falling on people
