### ISSUE TITLE
.ts endings reverted to .js when imports are auto-updated after moving a file

### ISSUE THREAD

**Issue by ssalbdivad** [microsoft/TypeScript#54001]
# Bug Report

### 🔎 Search Terms

vscode, language server, imports, .ts, .js, extensions, auto-update, refactor

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (have seen this since `.ts` suffixes were release)

@jakebailey requested I log this.

### Repro

This video is taken is with `typescript.preferences.importModuleSpecifierEnding` set to "auto" (as shown in the second part of the clip). Also tested this setting as "js", same result.

https://user-images.githubusercontent.com/10645823/234110894-106a8b73-6c28-46c4-8a34-37ca92683281.mp4

### 🙁 Actual behavior

the paths are correctly updated but .ts endings are replaced with .js

### 🙂 Expected behavior

.ts endings from the original file are maintained, the paths are correctly updated

**Comment by RyanCavanaugh** [comment]
Video transcript:
 * User is in `scope.ts`. There's a tasteful low-polygon Rhinoceros theme. WSL.
 * There are imports to e.g. `./nodes/problems.ts`
 * User moves `scopes.ts` to `nodes/scopes.ts` via a drag-and-drop in the VS Code file explorer
 * Paths change from `./nodes/problems.ts` to `./problems.js` <- wrong, should be `./problems.ts`

**Comment by ssalbdivad** [comment]
brb, changing my bio to include that my theme has been described as "tasteful" by @RyanCavanaugh.

**Comment by andrewbranch** [comment]
@ssalbdivad what are your tsconfig settings here?

**Comment by ssalbdivad** [comment]
@andrewbranch I believe some of the relevant settings looked something like this:

```json
        "module": "ESNext",
        "target": "ES2022",
        "moduleResolution": "Bundler",
        "allowImportingTsExtensions": true,
  ```
 
If you're not able to reproduce it I can try to dig through some git history and find the exact config.

**Comment by andrewbranch** [comment]
Yeah, I’m not able to repro. I did find one suspicious line in the implementation, but it shouldn’t matter if there are multiple `.ts` imports in the file, as in your video.

**Comment by ssalbdivad** [comment]
@andrewbranch I created a minimal repro here: https://github.com/ssalbdivad/ts-rename-extension-repro

This still occurs using `1.80.0-insider`. The tsconfig only includes `allowImportingTsExtensions`. I tested with `typescript.preferences.importModuleSpecifierEnding` set to `auto` and unset, and the change occurred in both cases.

**Comment by andrewbranch** [comment]
It still doesn’t repro for me 😮 Tried with nightly TS and 5.1.6.

**Comment by andrewbranch** [comment]
Do you have any funky extensions installed?

**Comment by ssalbdivad** [comment]
This is is with all extensions disabled and all settings defaulted.

The only thing I can think of is that maybe it's WSL-related? Hard to imagine why, but it's the only variable left I can think of.

This was the builtin TS for insiders, which is `5.1.3`. I could try again on `5.1.6`, but it seems unlikely that's the issue.

https://github.com/microsoft/TypeScript/assets/10645823/be395f94-0917-453c-affd-b6b713459276

**Comment by andrewbranch** [comment]
I’ve asked the team if someone can try to repro on WSL.

**Comment by andrewbranch** [comment]
I debugged this with @jakebailey who was able to reproduce on WSL. When we go to generate the edits for the newly moved file, that file actually belongs to an inferred project instead of the configured project covered by the tsconfig.json. Since the default options for inferred projects don’t include `allowImportingTsExtensions`, we refuse to generate a `.ts` extension for the new module specifier.

Presumably, there’s an OS-dependent order difference in when VS Code tells TS Server that the file move happened and when it asks TS Server for the edits to update import paths. That said, I’m not sure why TS Server ever creates an inferred project for the moved file in the first place, when it clearly should belong to the existing configured project as soon as it gets created. @sheetalkamat, do you have any insight as to why this might happen? (I don’t currently have access to a Windows machine, as I’m working remotely with just my MacBook this week, and out next week.)

I’ll put up a fix that short-circuits deciding on a new extension when there’s an existing extension that can be used, but there may be other related bugs that manifest from generating edits to moved files under the wrong compiler settings, so it may be worth digging into this more.

**Comment by andrewbranch** [comment]
Well, I’m second-guessing about always preserving the original file extension, because we intend to support moving files across projects. If you move a file with `.ts` imports from a project that allows them to one that legitimately doesn’t, should we try to update them for you?

**Comment by ssalbdivad** [comment]
> I’ll put up a fix that short-circuits deciding on a new extension when there’s an existing extension that can be used

@andrewbranch That would be great, but no rush. I'm well past the point where I consciously process the `.js` suffixes, so it's really just a matter of telling other contributors who are bothered by it to wait for the numbness to kick in 👍

**Comment by sheetalkamat** [comment]
@andrewbranch it could be that the change doesnt reflect in directory watcher or something and hence the file list for the configured project is not updated. Can you share log with me and i can take a look.

**Comment by jakebailey** [comment]
Here's what I had shared internally:

[issue54001-1.log](https://github.com/microsoft/TypeScript/files/12017708/issue54001-1.log)

**Comment by sheetalkamat** [comment]
@jakebailey thats not tsserver log. We need tsserver verbose log.

**Comment by andrewbranch** [comment]
It looks like that’s what you get out of the TypeScript Output tab in VS Code. The TS Server log can be seen via Command Palette > Open TS Server Log. I still don’t have a way to reproduce this, unfortunately 😕

**Comment by jakebailey** [comment]
I can no longer reproduce the issue with the above repo, even back in 5.1. I'm not sure if this means that something in VS Code changed to make this no longer race in the bad way or what. Before, it was always broken, now it's never broken.

@ssalbdivad Do you still see this happen?

**Comment by ssalbdivad** [comment]
@jakebailey Nope, seems like it must have been resolved in VSCode somehow! 🎉
