### ISSUE TITLE
Incorrect partial union signature matching

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#5401]
```
function g1(b?: string, ...a: string[]) { }
function g2(a?: string, b?: string) { }

var s: typeof g1 | typeof g2;

s("a", "b", "c") // should be an error: 0..2 parameters are allowed
```

**Comment by mhegazy** [comment]
@sandersn can you take a look.

**Comment by sandersn** [comment]
Sure.

**Comment by sandersn** [comment]
Seems like it only repros with optional arguments. This correctly errors:

```ts
function g1(b: string, ...a: string[]) { }
function g2(a: string, b: string) { }

var s: typeof g1 | typeof g2;

s("a", "b", "c") // should be an error: 0..2 parameters are allowed
```

**Comment by sandersn** [comment]
It's not in the union code like the last bug. The two signatures now union without a problem.

**Comment by sandersn** [comment]
It looks like resolveCall just treats unioned function types as an overload set and accepts a call if *any* member of the union matches. It should be *all*.

But I may be mis-reading the code -- I don't know why it only repros with optional arguments.

**Comment by sandersn** [comment]
With required parameters, only the fixed-arg signature matches with the rest-arg signature. `compareSignatures` is not commutative, and it happens that

```
{ (...a: string[]): string } `match` { (a:string, b:string): string }
```

but not

```
{ (a: string, b: string): string } `match` { (...a: string[]): string }
```

So when overload resolution happens, only `{ (a: string, b: string): string }` is considered. However, when the parameters are all optional, then the overload set includes both:

2. `{ (...a: string[]): string }`
1. `{ (a?: string, b?: string): string}`

And overload resolution just takes the first member of the union.
