### ISSUE TITLE
No docs for Assertion Functions

### ISSUE THREAD

**Issue by OwnageIsMagic** [microsoft/TypeScript#54020]
# Bug Report

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

https://www.typescriptlang.org/docs/handbook/2/narrowing.html nor https://www.typescriptlang.org/docs/handbook/2/functions.html doesn't mention this feature.

### 🔎 Search Terms
Assertion Functions, docs

**Comment by voxpelli** [comment]
It is mentioned in https://www.typescriptlang.org/docs/handbook/2/narrowing.html#assertion-functions nowadays, fixed by https://github.com/microsoft/TypeScript-Website/pull/2446 a month after your issue :)
