### ISSUE TITLE
Function overload requires an if statement for TS to parse argument types correctly

### ISSUE THREAD

**Issue by xitanggg** [microsoft/TypeScript#54027]
### 🔎 Search Terms
Function overload

### 🕗 Version & Regression Information
This is the behavior in every version I tried starting at 4.x, as well as the nightly version

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/PTAEGUEME9U0BmBXAdgYwC4EsD2LQC20AYqmqBpANYCmAzqFvgExwBOA5kgTShnQDpQAKBCgAQjgwALdlx58GkNjVA0sMmm1B0MbJhwY5tAIxw4ANjUgpBwjNAAOqgLIkyoALzDQoAD6gANrKHACMAFw6egYANHLMkbr6KBwAuj7+QSERoGaW1ihxIQm55lY2qQDcwmh4uoTu6F6gABQC7cGcoUWczKmRbqToAJReAHygAN4AvsKiYERDaKzSkAyaOpA8jCiOSBgUTqo2ACY7AG44tAyLHkx0WCc086AAKuAU0mw4AO5K+FpvqYaGhIEg6KoNJ8mFQlF1gMVQKD8CZVGYZFFkhxQAAyUr5Gw1OoHW7oVieVrtASdMI9Dh9AaNNCjTwTSYZUloFrZOnMYbCWYvTkAZlAq3W0lUdC2kN2+0OzjgKDOTEu1waSx2DyeL3eoBOOHoKAA5AcZN8fkq1GwgbkQWCIRqyKLxVasAgopAMDQFGacDoaI5lF7VDh5UkDMA8uUUC8TPKNu7Pd7fYwGDQEAgQdhzjQLLBwXn6AwHuhVJzuV1eaMsEoLD8YAxVVcaCcibYSUzRRS2h0efF+qBBmQWWyMkmWg5nDgPdkvJ4KcaIyljcN2b5fBX+8V+b5pnmIeuN1uq-Fd6BZoKxABJCW1uC5JDY046aRhixnPUoKSfC1WwHGIggGcswAD8QA)

### 💻 Code
```ts
// Say a function myFunc takes in 2 arguments. 
// Both arguments are either strings or booleans.
type MyFunc =
  | [arg1: string, arg2: string]
  | [arg1: boolean, arg2: boolean];
const myFunc = (...[arg1, arg2]: MyFunc) => {}

// myFunc2 has the same input type and invokes myFunc inside
// TS throws an error because it thinks arg1/arg2 can be both string & boolean
const myFunc2 = (...[arg1, arg2]: MyFunc) => {
  myFunc(arg1, arg2)
}

// myFunc3 has the same input type and invokes myFunc inside
// TS doesn't throw an error because myFunc3 has an if statement to separate out string/boolean
// but the if statement is effectively useless since myFunc(arg1, arg2) is always invoked
const myFunc3 = (...[arg1, arg2]: MyFunc) => {
  if (typeof arg1 === 'string'){
    myFunc(arg1, arg2)
  }else{
    myFunc(arg1, arg2)
  }
}
```

### 🙁 Actual behavior
TS throws an error for `myFunc2` because it thinks arg1 can be both `string` or `boolean`  but it should only be either one.

### 🙂 Expected behavior
TS should not throw an error for `myFunc2`

**Comment by MartinJohns** [comment]
Duplicate of #40827.

**Comment by nmain** [comment]
> Duplicate of #40827.

This is a single call signature with a union type for the arguments so it's not actually an overload.  This is closer to https://github.com/microsoft/TypeScript/issues/32639; the type system can't form a dependent narrowing relationship between `arg1` and `arg2`.  You can get around the limitation here by not destructuring:

```typescript
const myFunc4 = (...args: MyFunc) => {
  myFunc(...args);
}
```

**Comment by fatcerberus** [comment]
See also https://github.com/microsoft/TypeScript/issues/30581 and/or https://github.com/microsoft/TypeScript/issues/35873

**Comment by xitanggg** [comment]
Thanks all for the pointers and @nmain for the cool workaround, very interesting that not destructuring would make it work 👍

**Comment by fatcerberus** [comment]
@xitanggg Basically the destructured version fails because the compiler is only looking at the types of values individually, it doesn’t track “where they came from” (a `MyFunc` in this case), so as far as TS is concerned (prior to narrowing) you’re passing in a newly minted `[ string | boolean, string | boolean ]`—which isn’t allowed by the call signature because it doesn’t guarantee the elements match.

By not destructuring, you keep a `MyFunc` around, which is known upfront to be a valid input to the call.

**Comment by xitanggg** [comment]
Thanks for the explanation @fatcerberus. Right, this seems like a TS limitation as it doesn't try to loop through the options of call signature.

My actual use case is slightly more complex with where a function with a call signature of an array union calling another function with a call signature of an object union. It seems it would have to destructure to create the object with no easy workaround
```lang=typescript
type MyFuncObjArgs =
  | {
      arg1: string;
      arg2: string;
    }
  | { arg1: boolean; arg2: boolean };
const myFuncObj = (args: MyFuncObjArgs) => {};

type MyFuncArrayArgs =
  | [arg1: string, arg2: string]
  | [arg1: boolean, arg2: boolean];
const myFunc = (...[arg1, arg2]: MyFuncArrayArgs) => {
  // Have to destructure here to create an object, but Typescript yells
  myFuncObj({ arg1, arg2 });
};
```
[Playground](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAsiBiBXAdgYwPICMBWBBATgOYDOUAvAFBRQA+UA3ldcwIZECMAXFMcPgJbJCAbibMobQgCZuvAUNHiAvkzr0JHbpgD22gDYQWyYRulbdBo1CWjU25LygBbBCgw5yUABSTi3OEhoWHhExACU5AB8DDYUFKCQsK5oBPgsIAQk5KpQANqSXDx8goQANKYyRfKEALo5+ZpQOvqGyOWSlc2WyDW29o4ugaieXgB04w2E7O1EUjX+yaip6ZnhUQxMAPSbUAASLABu0MDaUAAmEHKIqMCI+NAAFhD3UCdQqPcswNBW2jgQN3KmEQwCgABVwJcPvwwKCQBA9HpiExBm5gl51AUZtJrGFRDYgA)

**Comment by fatcerberus** [comment]
> Right, this seems like a TS limitation as it doesn't try to loop through the options of call signature.

@RyanCavanaugh talks about that often - in general, if something can only be proven safe through manual enumeration of the possibilities, the compiler is most likely going to reject it.  Type safety has to be provable “in the abstract”, so to speak.
