### ISSUE TITLE
Type assertion with `as` operator does not work on recursive functions

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#5403]
With `--noImplicitAny`:

```typescript
function foo() {
    let element = foo() as number;
    return element;
}
/*
issue5403.ts(1,10): error TS7023: 'foo' implicitly has return type 'any' because it does not
have a return type annotation and is referenced directly or indirectly in one of its return
expressions.
issue5403.ts(2,6): error TS7022: 'element' implicitly has type 'any' because it does not have
a type annotation and is referenced directly or indirectly in its own initializer.
*/
```

**Comment by mhegazy** [comment]
The compiler uses right hand expressions to infer the type of un-annotated declarations. it also uses return expressions to infer the type of function declarations without return type annotations.

In the example above, the compiler tries to figure out the type of `element`, and as part of doing this it figures it needs to find the return type of `foo`, which is the type of `element`. the compiler breaks these cycles by giving them the type `any`. the warning tells you that this happened. 

either give the function a return type annotation, or declare element as number.

you can find more information in https://github.com/Microsoft/TypeScript/issues/1146#issuecomment-62930915

**Comment by SaschaNaz** [comment]
@mhegazy Here it has `as number` type assertion so the type of `element` should be explicitly `number` here.

**Comment by mhegazy** [comment]
this is a type assertion and not a type annotation. the type assertion needs to be checked that it is assignable to the expression. for instance:

```ts
"string" as number // error Neither type number nor type string are assignable to each other
```

so the compiler needs to do this check, but to do it, it needs to know the type of `foo()` which is the type of `element`, which it was trying to figure its type already.

**Comment by SaschaNaz** [comment]
Ah, I understand. Thanks for your explanation. :+1:
