### ISSUE TITLE
Narrowing Union of objects does not return a Union of different narrowed types 

### ISSUE THREAD

**Issue by yannbriancon** [microsoft/TypeScript#54041]
# Bug Report

When modifying a variable with a type Union of objects, the inferred type should be the Union of the possible results.

### 🔎 Search Terms

- Union
- Narrow union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Union and narrow

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gVwE4GNoF4oG8BQV9SiQBcUA5AO4DOZeBSEAhgCYRKlZXCPASlko4AOyEQUwAJZCA5mQC+OOVAA+2OviJ9yAMwkAbCLQJQGLNhy48tQhAFsARmwUKcB4FCqJUW+MjRRMLE1+XQMyABoTJlZ2fE5uXlIARgAmORcAegAqPCyoAFEkJDhY6QhgX28AdQlgAAsYBOgGYGQhQnBoCSooXLUoPI1O0gAiahGVKBHQiBGAbj78S0SpwRExSRkJ1RsHNgWBqCU+qS5oqDhtRdxDoZIpmfnFjybSXcckA7ylZWvn4Km4y+BGWWhGa1E4ik0ieh2OAwyODWXCgZQqXjQNXqjSsASgAAoAJQBAB8-Xo5Ta5OMdy0nj8EAAdJpwuoaaDSPTvIzTDFGaC2c4cEjhCiuZjag0mni0ZUJdimkScBJtATxRAsVKrMzOgF0JgyDMyMSbgQMhkCkUSmz1Zqcbx+dKANSYJKKIA)

### 💻 Code

```ts
type Source = {
    type: 'ws'
    reader: {state: 'connecting'}
} | {
    type: 'file'
    reader: {state: number}
}

let source: Source = {type: 'file', reader:  {state: 12}}

/*
 * Error: getSourceWithState return type is 
 * {
 *   type: "ws" | "file";
 *   state: "connecting" | number;
 * } 
 * instead of
 *  {
 *   type: "file";
 *   state: number;
 * } |
 *  {
 *   type: "ws";
 *   state: "connecting";
 * } 
 */
const getSourceWithState = () => {
    return {
        type: source.type,
        state: source.reader.state
    }
}

const sourceWithState = getSourceWithState()
if (sourceWithState.type === 'file') {
    // Error
    sourceWithState.state += 1
}
```

### 🙁 Actual behavior

The return type of getSourceWithState is 
```ts
{
  type: "ws" | "file";
  state: "connecting" | number;
} 
```

Then trying to narrow the type is impossible.

### 🙂 Expected behavior

The return type of getSourceWithState should be
```ts
{
  type: "file";
  state: number;
} |
{
  type: "ws";
  state: "connecting";
} 
```

This would make it possible to narrow the type and is also the truth.

**Comment by yannbriancon** [comment]
Thanks for your replies @jcalz & @fatcerberus 

@jcalz It is exactly what I do usually but I am tired of this complicated mapping and hoped something better would exist.

Hope someday this feature can be implemented.

**Comment by fatcerberus** [comment]
@jcalz For what it's worth I'm not convinced going all-in on distributive CFA is strictly necessary - most of these cases feel like they could be solved by simply tracking the provenance of types.  That would allow the compiler to recognize that

```ts
const { x, y } = p;
const q = { x, y };
```

is an isomorphism regardless of the types involved, without having to distribute over any unions.
