### ISSUE TITLE
`Debug Failure. False expression: Paths must either both be absolute or both be relative`

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#54057]
# Bug Report

- `Debug Failure. False expression: Paths must either both be absolute or both be relative`
- Dynamic import
- Conditional import
- Optional import

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions __5.0.4____ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

https://github.com/loynoir/reproduce-typescript-54057

### 💻 Code

```ts
export const mod = await (async () => {
  const x: number = 0;
  switch (x) {
    case 0:
      return await import("./case0.js");
    case 1:
      return await import("./case1.js");
    default:
      return await import("./caseFallback.js");
  }
})();
```

### 🙁 Actual behavior

```
/path/to/node_modules/typescript/lib/tsc.js:113984
      throw e;
      ^

Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at getRelativePathFromDirectory (/path/to/node_modules/typescript/lib/tsc.js:5717:9)
    at getLocalModuleSpecifier (/path/to/node_modules/typescript/lib/tsc.js:41911:206)
    at computeModuleSpecifiers (/path/to/node_modules/typescript/lib/tsc.js:41875:21)
    at getModuleSpecifiersWithCacheInfo (/path/to/node_modules/typescript/lib/tsc.js:41831:18)
    at getModuleSpecifiers (/path/to/node_modules/typescript/lib/tsc.js:41803:10)
    at getSpecifierForModuleSymbol (/path/to/node_modules/typescript/lib/tsc.js:48272:27)
    at symbolToTypeNode (/path/to/node_modules/typescript/lib/tsc.js:48317:23)
    at createAnonymousTypeNode (/path/to/node_modules/typescript/lib/tsc.js:47333:20)
    at typeToTypeNodeWorker (/path/to/node_modules/typescript/lib/tsc.js:47178:16)
    at typeToTypeNodeHelper (/path/to/node_modules/typescript/lib/tsc.js:46958:24)

Node.js v18.15.0
```

### 🙂 Expected behavior

No error

### Workaround
```diff
diff --git a/src/index.ts b/src/index.ts
index e46ce65..0fe805e 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -1,8 +1,8 @@
-export const mod = await (async () => {
+export const mod: typeof import("./case0.js") = await (async () => {
   const x: number = 0;
   switch (x) {
     case 0:
-      return await import("./case0.js");
+      return await import("./case0.js") as any;
     case 1:
       return await import("./case1.js");
     default:
```

**Comment by janyawat** [comment]
class C {
  /** @typedef {string} A */
  ;
  m() {
    /** @type {A} */
    let a = 'ok'
    /** @type {B} */
    let b = 'ok'
  }
  /** @typedef {string} B */
}

**Comment by janyawat** [comment]
class C {
  /** @typedef {string} A */
  ;
  m() {
    /** @type {A} */
    let a = 'ok'
    /** @type {B} */
    let b = 'ok'
  }
  /** @typedef {string} B */
}

**Comment by trusktr** [comment]
Same error here, similar stack as the OP.

```
/home/trusktr/node_modules/typescript/libtsc.js:113984
      throw e;
      ^

Error: Debug Failure. False expression: Paths must either both be absolute or both be relative
    at getRelativePathFromDirectory (/home/trusktr/node_modules/typescript/lib/tsc.js:5717:9)
    at getLocalModuleSpecifier (/home/trusktr/node_modules/typescript/lib/tsc.js:41911:206)
    at computeModuleSpecifiers (/home/trusktr/node_modules/typescript/lib/tsc.js:41875:21)
    at getModuleSpecifiersWithCacheInfo (/home/trusktr/node_modules/typescript/lib/tsc.js:41831:18)
    at getModuleSpecifiers (/home/trusktr/node_modules/typescript/lib/tsc.js:41803:10)
    at getSpecifierForModuleSymbol (/home/trusktr/node_modules/typescript/lib/tsc.js:48272:27)
    at /home/trusktr/node_modules/typescript/lib/tsc.js:48142:132
    at Array.map (<anonymous>)
    at getSymbolChain (/home/trusktr/node_modules/typescript/lib/tsc.js:48142:40)
    at lookupSymbolChainWorker (/home/trusktr/node_modules/typescript/lib/tsc.js:48125:36)
```

## Reproduction:

```ts
const code = await (fetch('./node_modules/vscode-oniguruma/release/main.js').then(r => r.text()))

const exports = {} as (typeof import('vscode-oniguruma'))
const module = { exports }

new Function('module', 'exports', code)(module, exports)

console.debug('vscode-onig module:', module.exports);

export const {createOnigScanner, createOnigString, loadWASM} = module.exports
```

[playground](https://www.typescriptlang.org/play?ssl=10&ssc=78&pln=1&pc=1#code/MYewdgzgLgBKAmBTGBeGBDA7uglrAFAGaJTAAW+A5AHQD0YISA+gLaMCuANohLQG4QEiALTgcAc3YAndi3S0pibugiJacnGGoArCJQCU1KGURh8U1AD4YUo4gAeUfPpcAoV6EiwHABxBSoCFQYAG8AXwwg-CgATx9EEEIYHBY-AKoBIVEwCWlZdAN9D3BoGDZ4LmQ0EJhff0CYMPcwREwYADF2MGAoHHAqcsrKABoYSjqAvVGhfXxB7lGJwKLiyBBuaiQAI3ZxDMFGETFxMo5uAC4R04qNpYh9AG53JbgS2BDgRXQoRAB5HPEAGVgOgwC0pNMvj9-hJAVApJpxKNOCB0PAAOoAQUBAFkImh5ohqHcgA)

## Workaround:

```ts
const r = await fetch('./node_modules/vscode-oniguruma/release/main.js')
const code = await r.text()

const exports = {} as (typeof import('vscode-oniguruma'))
const module = { exports }

new Function('module', 'exports', code)(module, exports)

console.debug('vscode-onig module:', module.exports);

export const {createOnigScanner, createOnigString, loadWASM} = module.exports
```

[playground](https://www.typescriptlang.org/play?ssl=11&ssc=78&pln=1&pc=1#code/MYewdgzgLgBATjAvDAhgdxQS1gMwKZTAAWAFAOQB0A9GCACZ4D6AtvQK4A2eEVAbhKAYBacJgDmbOG2YoqcPFxQQ8VGZjAUAVhDIBKAFChIsQXiSoM2eBSh4AHlBIHD4aDHsAHEHCgRzAbwBfVD8SKABPDzwQHBhMZi8fcn5TETBxSWkUPQMjN1Y6TjNkf3c7RN8YQP19MDw0GAAxNjBgKExwcgKisgAaGDJPb18+mFNdEm6ufqGfCGc8kC4KBgAjNjFkgXo8NPEYKbwALlHDilnfXQBuGoux11h-YHkUWwB5dLEAZWAUMDq4P1nnhXngPuIvlA4OoxP0OCAUHQAOoAQS+AFlgsgzhcIEA)

**Comment by ccclever2** [comment]
Deleting `tsconfig.tsbuildinfo` fixed it for me

**Comment by loynoir** [comment]
Close, as I remove workaround code and found no error now.

The latest workaround would be, prev workaround, plus

```ts
     case 1:
       return await import("./case1.js");
```

to

```ts
     case 1:
       return await import(`./case1.js` as string);
```

**Comment by sheetalkamat** [comment]
This is still a issue and i think its from https://github.com/microsoft/TypeScript/blob/main/src/compiler/parser.ts#L1914 where we create source file with originalNode set because of await at top level detection. The sourceFile used as originalNode in that case is not completely formed so doesnt have "path" and other properties set so results in being default `""` which causes issues with module specifier logic

**Comment by GaryParr** [comment]
I just upgraded a project from v4.9.4 to v5.2 and hit this.  Initial builds work fine, but subsequent builds with the watch option fail.  While I know almost nothing about the inner workings of typescript, I can confirm that the contextFile object obtained in the getSpecifierForModuleSymbol function has an empty string for path which sounds suspiciously like what @sheetalkamat  mentioned above.
