### ISSUE TITLE
Webpage containing license text not reachable

### ISSUE THREAD

**Issue by rahulmohang** [microsoft/TypeScript#54058]
# Bug Report

The webpage, 'http://hg.ecmascript.org/tests/test262/raw-file/tip/LICENSE' with license of the file, https://github.com/microsoft/TypeScript/blob/main/tests/cases/conformance/parser/ecmascript5/parser10.1.1-8gs.ts is not reachable anymore. So, it is not possible to know the license of the file. 

### 🔎 Search Terms

license, parser10.1.1-8gs.ts

### 🕗 Version & Regression Information

version - 5.0.2 that I was analyzing, and the 'master' branch as well.

### 🙁 Actual behavior

The webpage with the license information should work when we use the URL in our browser. However, it does not work. So, users may not be able to understand the license that govern the terms of use of the file. 

### 🙂 Expected behavior

The URL should be accessible and users should be able to see the text of the license that the file is licensed under.

**Comment by jakebailey** [comment]
This license would be: https://github.com/tc39/test262/blob/main/LICENSE

**Comment by rahulmohang** [comment]
Thank you.
