### ISSUE TITLE
extends operator with literal types

### ISSUE THREAD

**Issue by DPOH-VAR** [microsoft/TypeScript#54050]
# Bug Report

### 🕗 Version & Regression Information

- This is wrong behaivor of `extends` operator
- This changed between versions **3.3.3** and **3.5.1**
- Most likely this is the reason: https://github.com/microsoft/TypeScript/pull/30779

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.1.0-beta#code/C4TwDgpgBAglC8UDeAPAXAZ2AJwJYDsBzAXygB9l18BXAWwCMJtSLU0oMQGB7AG2IBQA0JCgAhBJUw4CJclJoMmLKVHrc+EAIb5BUfQcNHjJ0wYD05qAD0ovXMCZbeUEdAAWTCMPDQAwpJsWHhEKmyKjMxCblAAGoHowbLyEcoCllAABvEQKI74ACYY4plq1MBQ+NwVcNzYUH5CPqKxAPpwiDl5EIXFcAD8UABEXflFsENQ7COV1VC5Y31DANzpVvrW-dG+ca0SnfPdveJQgzMLPeNik9PxVRUXx9erGRtbzdBtAQeP4wFno0uxT8N2Gdzmv2BKzWBk221EMFa8UQcEhcVOw1RR3GsVBQzg90Oizi0NeNneMTESMkEjR8TOtOxxVxU2GEkJdNJ63J8P81MQATpGKGgqZJNZItmDzFuJe3LhQA

### 💻 Code

```ts
type A = {x:string} | {x:number} | {x: symbol}

type B = {x:string} | {x:number} | {x: boolean}
                                       // ^ literal type here
type C = {x:string} | {x:number}

type X = {x:string | number}
// `X extends B` but not A or C


type X_A = X extends A ? "X extends A" : "X not extends A";
//   ^? X not extends A

type X_B = X extends B ? "X extends B" : "X not extends B";
//   ^? X extends B

type X_C = X extends C ? "X extends C" : "X not extends C";
//   ^? X not extends C

```
the bug is reproduced with any literal type instead of `boolean`

### 🙁 Actual behavior

`X` not extends `A`
`X` extends `B`;
`X` not extends `C`

### 🙂 Expected behavior

`X` not extends `A`
`X` not extends `B`
`X` not extends `C`

**Comment by jcalz** [comment]
#30779 implemented this behavior intentionally, and it is [documented in the TS3.5 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#smarter-union-type-checking).  Unions with discriminant-worthy properties (involving literals) are related differently, on purpose.  That results in:

```ts
type A = { x: string } | { x: number } | { x: symbol }
type B = { x: string } | { x: number } | { x: boolean }
type C = { x: string } | { x: number }

type X = { x: string | number }

const x: X = { x: Math.random() < 0.5 ? "abc" : 123};
const a: A = x; // error
const b: B = x; // okay
const c: C = x; // error
```

And so `extends` is behaving the way assignability behaves.  Maybe it's inconsistent, but it's not a bug.
