### ISSUE TITLE
Operator Overloads

### ISSUE THREAD

**Issue by Antony-Jones** [Microsoft/TypeScript#5407]
It would simplify a lot of use cases if we could override relational, equality, additive, and Multiplicative operators.

My initial thoughts on how this would work is that functions would replace the operators with functions when compiling to JavaScript. 

    class MyClass {
        constructor() {
        }
    
        public Operator > (value: any):boolean {
            // compare value
        }
    }
    
    var myClass = new MyClass();
    
    if(myClass > otherValue){
    	// Do stuff
    }

Becomes:

    var MyClass = (function () {
        function MyClass() {
        }
        MyClass.prototype.greaterThan = function (value) {
            // compare value
        };
        return MyClass;
    })();
    var myClass = new MyClass();
    if (myClass.greaterThan(otherValue) {
    	// do Stuff
    }

**Comment by DanielRosenwasser** [comment]
One thing we avoid doing is type-driven emit. The idea is that TypeScript types have no bearing at runtime - the code is as close to the analogous JavaScript that you would have written. Given that, substituting in a method call for an operator would go against that.

Apart from that, this is related to #2319, so I'm going to close this as a duplicate.

**Comment by nitinbansal1989** [comment]
i have written an ORM framework in typescript. Its still new and only supports mysql currently. Its architecture is based on entity framework. 
https://www.npmjs.com/package/es-entity
Enabling Operator Overloading will support the creating of 'LINQ' like queries. 
You can add this feature as a optional extension like Decorators feature with experimental implementation and compiler option. Hope to see this in typescript.

**Comment by jay3sh** [comment]
I'm developing numpy like library in typescript ([bluemath](https://github.com/bluemathsoft/bluemath)). Operator overloading will significantly improve the interface of my [NDArray](http://www.bluemathsoftware.com/docs/classes/ndarray.html) class.
