### ISSUE TITLE
[Feature Request] Option to inherit types for .js files from their associated .d.ts file (alternative to JSDoc for IDE type checking)

### ISSUE THREAD

**Issue by alshdavid** [microsoft/TypeScript#54078]
## 🔍 Search Terms

checkjs declarations

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

# Suggestion

In cases where developers must write code using standard JavaScript, the only way to add explicit type annotations for an improved development experience is through the use of types defined via JSDoc. 

While this works, JSDoc lacks a lot of features, doesn't have the best documentation, and is very verbose.

As an alternative it would be amazing if TypeScript's language server offered a setting that allowed for types _within_ a JavaScript file to be populated by types defined in an adjacent/associated `.d.ts` file.

The intention of this proposal is to assist with the development experience within the IDE - not expansion of `tsc` to include checks for JS files.

## Example Case

_Assume `checkJs: true`, `strict: true` and CommonJS_

Say I have the following written in JavaScript

```javascript
// ./bar.cjs
const bar = null
module.exports.bar = bar;
```

I could manually write a `.d.ts` file that covers its definition

```typescript
// ./bar.d.ts
declare const bar: null | string;
```

Any JavaScript consumer of this file will have access to the types defined in the type declaration file
```javascript
const { bar } = require('./bar.cjs')
if (bar === null) // The language server will pick up the type defined in the .d.ts file
```

Unfortunately, this does not enforce that the type _within_ the `./bar.cjs` matches that of the type defined within `./bar.d.ts` allowing the assignment of values outside of the defined type or misuse of the type in modules that have more functionality.

```javascript
// ./bar.cjs
const bar = false

void function main(){
  bar = 42
}()
```

One solution to this is mixing JSDoc with the the TypeScript declaration file like so:
```javascript
// ./bar.cjs
//** @type {import('./bar').bar} */
const bar = null
```

This tells the language server to import the type from the `./bar.d.ts` file and assign it to the current variable. 

This approach is a bit cumbersome because it requires every variable to be annotated with the type it represents in the declaration file, but it does work... until you come across more complex types like classes or features like generics.

Take for example this type:

```typescript
// ./foo.d.ts
export type FooOptions<T> = {
    foo: string;
    bar: T;
};

export declare class Foo<T> {
    foo: string;
    bar: T;
    constructor(options: FooOptions<T>);
}
```

When using JSDoc to shuttle the type across, we end up lacking any type information

```javascript
// ./foo.cjs
//** @type {import('./foo').Foo} */
class Foo {
  constructor(options) {    // options has no type
    this.foo = options.foo  // foo has no type
    this.bar = options.bar  // bar has no type
  }
}
module.exports.Foo = Foo
```

## Proposal

Expanding the `checkJs` functionality to allow for type checking of the target js file by using its associated declaration file.

Such a feature could be enabled via a new compilerOption like: `checkJsUsingDeclarations` within the `jsconfig.json` or `tsconfig.json` files.

Such an addition would be a valuable as it would give developers low friction access to TypeScript types in scenarios where they are needed but unavailable.

## 💻 Use Cases

- Legacy codebases written in JS that don't have the option to add the TypeScript toolchain but would benefit from additional type checking - at least within the IDE
- Codebases written in JS that are migrating to TypeScript
- Codebases written in JS that do not intend to switch to TypeScript but require advanced types in certain places
- JavaScript targeting the web that don't use a compiler and would like to use types but do not want to spend extra kb on shipping JSDoc comments

In many cases writing applications that use JSDoc for JavaScript types inevitably results in defining types twice. Once for the file and once again for consumers (not always but it does happen). This workflow can become cumbersome due to the repetition and switching between the two declaration syntax

**Comment by jakebailey** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/30304?

**Comment by alshdavid** [comment]
Yeah looks like it, thanks!
