### ISSUE TITLE
Incorrect definition for Date.UTC

### ISSUE THREAD

**Issue by tungs** [microsoft/TypeScript#54084]
# `es5.d.ts` Update Request

## Incorrect Definition

According to spec, the static method `Date.UTC`'s second argument (`monthIndex`) should be optional, but in `es5.d.ts`, it isn't:

https://github.com/microsoft/TypeScript/blob/d5d9171909ad1a8fafe1012239e60a9446d1a628/src/lib/es5.d.ts#L929

## Sample Code
```
Date.UTC(2023); // should be valid
```

## Documentation Links

MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC#syntax
ECMAScript Spec: https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date.utc

**Comment by Josh-Cena** [comment]
Note that this is es5.d.ts, so it cannot encode ES2017+ semantics. However, I'm not sure if declaration merging allows overriding the optionality of parameters.

**Comment by fatcerberus** [comment]
Declaration merging creates overloads IIRC, so that should be allowed.
