### ISSUE TITLE
Bug: Node18/ES2022 triggers objects to have keys with undefined values: breaks spread

### ISSUE THREAD

**Issue by pvogel1967** [microsoft/TypeScript#54093]
# Bug Report

### 🔎 Search Terms

typescript
nodejs 
spread
es2022

### 🕗 Version & Regression Information

- This changed between versions @tsconfig/node16 and @tsconfig/node18 with node 18.16.0

### ⏯ Playground Link

I was not able to reproduce this on the bug workbench, I suspect there's some interaction going on with node18 here.  But I did set up a very simple repo that reproduces the problem reliably.

https://github.com/pvogel1967/ts-node18-spread-bug

Using node 18.16.0 (I didn't try other versions of node18)
`git clone https://github.com/pvogel1967/ts-node18-spread-bug.git`
`npm install`
`npm build`
`npm test` 

Will print FAILED at the end...

```
➜  ts-bug-report git:(main) ✗ npm run test

> ts-bug-report@1.0.0 test
> node dist/src/test.js | grep pass || echo FAILED

FAILED
```

Note, there is _also_ a `tsconfig.willpass.json` file in there.  If you build with that file, the test will pass.  The _only_ difference is the reference to `@tsconfig/node18/tsconfig.json` instead of `@tsconfig/node16/tsconfig.json` which, in turn means the only diff is to the `target` and `lib` settings from `es2021` to `es2022`.

### 💻 Code

```ts
class TestDataDTO {
    b?: string;
    legacyB?: string;
}

class TestData {
    a?: string;
    b?: string;
}
const bar: TestDataDTO = { legacyB: 'pass' };
const barTest = new TestDataDTO();
// this next line simulates what you typically get from an API layer which is receiving a DTO
// with many optional fields via JSON and, after validating the DTO content, spreads it into an
// "empty" object created via new.
const { legacyB,...restDto } = {...barTest, ...bar};
// This next line is what causes the problem.  We successfully spread { b: legacyB } into the result
// but then the spread of what _should be_ an empty restDto overwrites the b property with undefined.
const result3: TestData = {
    ...(legacyB ? { b: legacyB } : {}),
    ...restDto
}
console.log(JSON.stringify(result3, null, 2)); // should be { "b": "pass" }
console.log(`restDto keys`, JSON.stringify(Object.keys(restDto))); // should be [] but is [a, b]
console.log(`barTest keys`, JSON.stringify(Object.keys(barTest))); // should be [] but is [a, b, legacyB]
console.log(`result3 keys`, JSON.stringify(Object.keys(result3))); // should be [b] but is [b, a]
```

### 🙁 Actual behavior

Spread of an _empty_ object into a literal object after spread of a non-empty object in that same literal object results in the empty object (well, not quite empty, all keys have the value `undefined`).

### 🙂 Expected behavior

The empty object spread into a literal object should _not_ cause properties already added to the literal object to be overwritten with `undefined`.

**Comment by pvogel1967** [comment]
It should be noted this _also_ breaks Jest's `toMatchObject()` method as the expected object may have several properties left intentionally `undefined` so that those properties are not inspected on the actual object.  Instead, the expect fails with the expected object having several
properties that are undefined causing a mismatch to the received object which does not have those properties or has those properties with actual values.

**Comment by fatcerberus** [comment]
Assuming the spreaded objects in question have properties *explicitly set* to `undefined` (as opposed to just omitted entirely), then this is the expected behavior per the ES specification.

**Comment by MartinJohns** [comment]
As far as I can tell this is working as intended. Targeting ES2022 instead of ES2021 changes the default value for `useDefineForClassFields` and causes your classes to use ECMAScript standard compliant class fields. That means your class fields are **always** defined with an explicit `undefined`.

Depending on `useDefineForClassFields` your class `TestData` compiles to:

```typescript
class TestData { } // not ECMAScript standard compliant, properties are missing
class TestData { a; b; } // ECMAScript standard compliant, properties are defined
```

Classes are a poor choice for DTO structures. You should use interfaces instead.

**Comment by pvogel1967** [comment]
Classes allow for decorators on properties, particularly important for swagger.

**Comment by nmain** [comment]
You can also see this in any compliant JS engine (with no Typescript involvement).

This code will print `["a"]` in Javascript, and `["a"]`when transpiled by Typescript with `useDefineForClassFields` enabled, but `[]` in Typescript without `useDefineForClassFields` enabled:

```js
console.log(Object.keys({ ...new (class { a; })}))
```

**Comment by pvogel1967** [comment]
Yeah.  I get what's going on (thanks for the pointer to `useDefineForClassFields`) and I do see the update to the ES class standard where fields are _always_ present even if undefined in a class.

That said, the implication to spread semantics and object comparison is interesting...
