### ISSUE TITLE
Module 'XXX' has no exported member 'xxx'

### ISSUE THREAD

**Issue by OldManMeta** [microsoft/TypeScript#54109]
5000 + Bugs - clearly filling in all the stuff has very little effect, so ignoring that noise. Impossible to search effectively as well.

I'm almost positive that someone has already filled this - but you never know.

I've seen this issue a lot over the last several months.

Not sure if it's a consistency thing, because for me it happens mainly with only some specific packages, and I thought I may mention that, if it helps repro or remove that as a culprit.

One of those packages that causes problems is :

https://github.com/pmndrs/drei

Create a really simple solution and add references to things like Grid, PointerLockControls and several others - they will show the error.
 In another package, I've just captured the images of it occuring:

https://github.com/pmndrs/react-three-rapier

Here I am using the Debug module which is clearly exported in the Dist:

![image](https://user-images.githubusercontent.com/107874035/235875877-4ef02040-dd94-490c-93c9-903fb0456430.png)

Yet, here we see the error:
![image](https://user-images.githubusercontent.com/107874035/235876029-ea6f54f6-62a2-44fe-a2f9-b0a942ed3ed1.png)

The only way to resolve this at the moment is to create a direct reference:

```
import { Debug} from "@react-three/rapier/dist/declarations/src/components/Debug";
```

Is this something to do with the way the original module is declared and exported i.e. MemoExotic ?

Leave this with you and hope it helps.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
