### ISSUE TITLE
Google feedback on TS 5.1-beta

### ISSUE THREAD

**Issue by rahul-kamat** [microsoft/TypeScript#54101]
This GitHub issue contains feedback on the TS 5.1-beta release from the team
that is responsible for keeping Google's internal software working with the
latest version of TypeScript.

## Executive summary

*   We do not expect to have significant difficulty in upgrading Google to TS
    5.1.
*   Some changes to our TypeScript code are required to make it compile with TS
    5.1.
      *   Detail sections below explain the changes to our code we expect to make to
           unblock the upgrade.

## Impact summary

Change description | Announced | Libraries affected
------------------ | --------: | -----------------:
lib/d.ts changes   | yes       | 0.1%
other changes      | yes       | 0.005%

The **Announced** column indicates whether we were able to connect the observed
change with a section in the
[TS5.1-beta announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-1-beta/).

The following sections give more detailed explanations of the changes listed
above.

### lib/d.ts Changes

We support the typing improvements. Generally it's clear what's changing and the
changes seems minimal this time.

For the TypeScript compiler changes, we expect to fix our codebase to comply to the new API and
for other typing changes, we expect to `// @ts-ignore` to silence the errors.

We observed the following types of errors:

*   TS2345: Argument of type 'T1' is not assignable to parameter of type 'T2'
    *   .054% of libraries affected
*   TS7023: Function 'f' implicitly has return type 'any'
    *   0.01% of libraries affected
*   TS2322: Type 'T1' is not assignable to type 'T2'
    *   0.018% of libraries affected
*   TS2365: Operator '(>)(<)(=)' cannot be applied to types 'T'
    *   0.017% of libraries affected

**Comment by DanielRosenwasser** [comment]
Thank you so much for trying it out!
