### ISSUE TITLE
Checking falsiness of optionally chained property incorrectly infers definedness of parent

### ISSUE THREAD

**Issue by ericbf** [microsoft/TypeScript#54103]
# Bug Report

### 🔎 Search Terms

optional chaining, type inference, optional boolean, incorrect type inference, incorrect type narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about optional chaining, inference, types, etc.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3kgRgKwC54BvAKHgviiJySQhChXMpxroadIF94AfeAFcUoAGYBLFCGClSAejnZ8AOhzw0ACySCIwdVACe8AAYByXHlPxxaeAAckaNOJwQjp4WMnTTx5aXFReAAKAEILAH5lKH4BcJUcAEoSFgoFeGAkdSQAWxAMDUkAcx4gA)

### 💻 Code

```ts
declare const obj: {
    a: boolean
    b: boolean
} | undefined

// obj.b should say `'obj' is possibly 'undefined'`.
if (!obj?.a || !obj.b) {
    // do something
}
```

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

Transpiler error on the `obj.b` access.

**Comment by fatcerberus** [comment]
If `!obj?.a` is true, then `|| !obj.b` is unreachable due to short circuiting.  This implies `obj?.a` is truthy at that point (because its negation is false), and that therefore `obj` can’t be `undefined`.  This all looks correct to me.

**Comment by ericbf** [comment]
Lol my b. Don’t know what I was thinking haha.
