### ISSUE TITLE
Inconsistent handling of whitespace in string in template literal types

### ISSUE THREAD

**Issue by annacb40** [microsoft/TypeScript#54119]
# Bug Report

### 🔎 Search Terms

template literal types
template literal whitespace
template literal spaces
template literal strings

### 🕗 Version & Regression Information

This changed between versions 4.0.5 and 4.1.5.  I think this variety of type definition was not supported prior to 4.1.5.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAysBOBLAdgcwOqOACwHIFcBbAIwngA0oBeKAAwBIBvAZwRVQF8onkjT4OAD1oBuAFChIUAMIB7QoQCGMCGDhI0mHARJlKNBo3XstePno4AabkbaasZ3RQ6iJ4aHIXK7qFWp+mOvz6dEzG9trmztZMrBqcYQEOQRauYgDGssisUJlefuEYyVHkAFwy8koFSZFOIQDkAGayslAALILWxIrwUACsgvXimdnAUHEmxU7lhYEl1FBNLf2D4hlZORCEYKCFMzWOwQv1K0Pro1CEsvAQMGCK6RDMAEIQwADuEBDI+-Fzdcdmq0oCCBkMoAB6CHjL6EZi5DaIVjfMaoRAAN2+UGwwGAYGYpShaJw+GIADo8hDCIh0vBZMxZI1gBCACruGC0xA7CFI5j4J4QtoANgAjAAGACc5xyfMajUQgjuDyev0mtSONCWrT6IKgg0h0OYsPhI2YSOAKKgaMxyGxuPxhIhxOwpIp8ipNLpDKZrPZnO5vP5zEFoslYjEUKgLMUxHhimQABMoMgIO8oAAbFBPKA9aAodLp-AJiBJ94OcY+Lr4MbMe6POM3ZOyYDSsZgG7ywS4VMAGSzqoihz0xwAOsggacRFBW8ne1mAJLIPawA4pCiAlpj7q9MHDDZjFPvPsp14fL4-Fd-KYaxYTsenaemmv4OUK7tH-uXtVD9eaicDMdwUjQ8MyzKAkSbMZEFQZBrhLGd2wgTto2IAcinVYdNRHYB-1WR99ygYAY0XZdZmvTDb03YBt0nGciOIU9Pm+ND-hvLUoGwh8Z1lZCYxY8jf0o7VBGwoDoXo8D4VgqCYLghNw0jaRFCNeEcEUGtYXA5BTXNFFuLrJ4SJ8fiMME9iaN3A1xgM+EUAreIc0baSc3TdNZE+BMAH4EI7BUlXrEyfwaXVcLE6zlTjGsiPgMZGXs9hHOgZzFFc9yS28mcIEEBBlFUfyIHKTwqjy1d5j-ZYOmsKALLwyMspy8LHkk5B6ig7TC2LUtyyNEYkwmNBvKfKB6vgXK1AMgAmQrKm8eJqivUyGgnSqQRqsLFATBMEpwaB+tQLTCOwXbVB6dTrgzN54UIaANqTLKHmAdMQCgLJdoMg7SDPb46PeWQAFFstGgoDOm-IfHm781yWirOl1Nap0jW7tqO+K0AOnaYXuUbgHO9NLsuG7NuGwQHqel6U0avNbU+pjkHDMQgA)

### 💻 Code

```ts
type StringWithNumberX = `${string} ${number}x`;
type CommaSepStringWithNumberX = `${StringWithNumberX}, ${StringWithNumberX}`;
type CommaStringSepStringWithNumberX = `${StringWithNumberX}, ${string}${StringWithNumberX}`;

const commaSepStringWithNumberX: CommaSepStringWithNumberX = 'foo 4x, bar 5x';
const stringWithNumber: StringWithNumberX = 'foo 5x';

const emptyString: StringWithNumberX = ' 5x';
const moreSpacesBetween: StringWithNumberX = 'foo    5x'; // seems consistent given https://github.com/microsoft/TypeScript/issues/46109
const suffixSpaces: StringWithNumberX = 'foo 5   x' // seems consistent given https://github.com/microsoft/TypeScript/issues/46109

// Tabs and new lines are included with string, but spaces are not
const prefixNewLine: StringWithNumberX = '\nfoo 5x'; 
const newLineInString: StringWithNumberX = 'foo\nbar 5x';
const newLineBetween: StringWithNumberX = 'foo \n 5x' 
const suffixNewLine: StringWithNumberX = 'foo 5x\n'; // new line is not ignored
const prefixTab: StringWithNumberX = '\tfoo 5x'; 
const tabInString: StringWithNumberX = 'foo\tbar 5x';
const tabBetween: StringWithNumberX = 'foo \t 5x' 
const suffixTab: StringWithNumberX = 'foo 5x\t'; // tab is not ignored

// Cases that seem inconsistent
const spacesInString: StringWithNumberX = 'foo bar 5x'; // spaces in string are not allowed?
const prefixSpaces: StringWithNumberX = '   foo 5x'; // spaces at start of string are not allowed?

const extraSepSpace: CommaSepStringWithNumberX = 'foo 4x,  bar 5x'; // extra space isn't included with second string?
const extraSepSpace2: CommaStringSepStringWithNumberX = 'foo 4x,  bar 5x'; // adding the string in the separator lets me add exactly one space in between
const twoExtraSepSpace: CommaStringSepStringWithNumberX = 'foo 4x,   bar 5x'; // adding the string in the separator lets me add exactly one space in between
```

### 🙁 Actual behavior

${string} in a template literal type will accept tabs and/or new lines anywhere in the string, but does not accept spaces within the string.

### 🙂 Expected behavior

${string} should allow spaces within the string.

**Comment by DanielRosenwasser** [comment]
Maybe I'm missing some part of your examples - but I think this just has to do with greedy string matching. When TypeScript encounters a template string type like

```ts
`${string}FOO...`
```

there is no back-tracking involved in trying to solve for all places where a `FOO` will occur. The first one wins, and everything up until that point will be matched against that `string`.

So please correct me if I'm missing something, but I don't think this has anything to do with whitespace.

**Comment by annacb40** [comment]
@DanielRosenwasser Maybe I am missing something, but take the example of `const spacesInString: StringWithNumberX = 'foo bar 5x';`.... I'm not sure how this would involve backtracking at all?  It appears to me there is only one instance of            
 ` ${number}x`, and for some reason "foo bar" is not then matching for string.

**Comment by annacb40** [comment]
@DanielRosenwasser  I wonder, are you looking at the playground and not just the code sample in the issue?  The playground shows several type errors for several cases where I would not expect type errors.  The lines with type errors are 16, 20, 23, 24, 26, and 28.  Lines 16 and 20 failing seems consistent.  The others do not, specifically because of the way spaces are being treated.

**Comment by fatcerberus** [comment]
The space makes a difference because your pattern contains one.  Daniel is saying that TypeScript is matching `foo ` (with the space) with `${string} `, it is then unable to match `bar 5x` with `${number}x` and gives up.  It won’t go back and try to match with a larger `${string}`.

**Comment by fatcerberus** [comment]
This new bot sucks.
