### ISSUE TITLE
Dynamic imports shouldn't be transpiled in CommonJS

### ISSUE THREAD

**Issue by Ayc0** [microsoft/TypeScript#54111]
# Bug Report

When using a dynamic `import()` in a TS codemod, it gets transpiled to a `require()` (wrapped in a Promise):

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/22725671/235927918-0f496060-0eca-4863-bbc0-71b8db3bdfdc.png">

The issue with this is that `import()` are the only way for CJS files to import an ESM file. So we need to be able to keep the dynamic import in the transpiled code (because using `require` in those cases will crash as they aren't compatible with ESM).

Also `import()` is fully supported by Node, even in CJS:  see https://nodejs.org/api/esm.html#import-expressions.

> [Dynamic import()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) is supported in both CommonJS and ES modules. In CommonJS modules it can be used to load ES modules.

### 🔎 Search Terms

esm, ecma script module, ecmascript module, common js, commonjs, cjs, dynamic import, import()

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about esm

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?module=1#code/JYWwDg9gTgLgBAQzgMyhEcDkA6A9AzAKEIGMIA7AZwgBsBTbGiAcwAoEBKYsq+AIzgBeRJQCe5EnFYchAPjgBvQnBVweleEmEIA7gmDxQkWKxz5sIAFaVMHANyEAvkA)

### 💻 Code

```ts
import a from './a'

console.log(a)

const b = async () => {
    const a = await import('./a.mjs');
}
```

### 🙁 Actual behavior

`import()` is transpiled as `Promise.resolve().then(() => __importStar(require('./a.mjs')))`

### 🙂 Expected behavior

`import()` should transpiled as `import()` as dynamic imports are supported in CJS (and are the only way to import ESM from CJS)

And this, we should generate this:

```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const a_1 = __importDefault(require("./a"));
console.log(a_1.default);
const b = async () => {
    const a = await import('./a.mjs');
};
```

**Comment by fatcerberus** [comment]
You need to use `module: "node16"` (alternatively, `nodenext`) to use dynamic import in CJS.

**Comment by fatcerberus** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/52775

**Comment by Ayc0** [comment]
I don't think I can:
`node16` & `nodenext` are using top level ESM:

- node16:
  <img width="729" alt="image" src="https://user-images.githubusercontent.com/22725671/235931512-36d76e4e-1b5e-46e7-9551-ea242a892c58.png">
- nodenext:
  <img width="729" alt="image" src="https://user-images.githubusercontent.com/22725671/235931575-860161a9-d33f-46c5-bc27-875044b73e5b.png">

**Comment by Ayc0** [comment]
Edit: in the REPL, if I switch to `module: node16`, and then switch back to `module: commonjs`, it seems to output the proper code (see in [TypeScript Play](https://www.typescriptlang.org/play?target=99&moduleResolution=99&module=1#code/JYWwDg9gTgLgBAQzgMyhEcDkA6A9AzAKEIGMIA7AZwgBsBTbGiAcwAoEBKYsq+AIzgBeRJQCe5EnFYchAPjgBvQnBVweleEmEIA7gmDxQkWKxz5sIAFaVMHANyEAvkA))

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const a_1 = require("./a");
console.log(a_1.default);
const b = async () => {
    const a = await import('./a.mjs');
};
```

This may be an issue in the REPL itself (as `moduleResolution` isn't exposed there)

I'll close this issue. Thanks for your reply 🙇
