### ISSUE TITLE
type 'Plugin_2' 'Plugin' is not assignable to type 'PluginOption'.

### ISSUE THREAD

**Issue by kumv-net** [microsoft/TypeScript#54124]
pnpm 、TypeScript、vite 支持似乎出现了问题
plugins
类型： (Plugin | Plugin[] | Promise<Plugin | Plugin[]>)[]

https://github.com/vitejs/vite/issues/13027

Reproduction
https://github.com/kumv-net/vite3-4-unocss-macros

**Comment by jakebailey** [comment]
Despite the bad bug reporting, I did a little looking and this looks like it's just a pnpm problem.

- https://github.com/vitejs/vite/issues/13027#issuecomment-1538734840
- https://github.com/pnpm/pnpm/issues/6501#issuecomment-1538735638

**Comment by kumv-net** [comment]
pnpm unocss

**Comment by smellai** [comment]
I use npm and I get this error when upgrading from vite 4.4.7 to 4.4.8
