### ISSUE TITLE
Well-typed ECMAScript decorators don't handle generic types in Args

### ISSUE THREAD

**Issue by cheit-epic** [microsoft/TypeScript#54122]
# Bug Report

Using the example `loggedMethod` in the [release notes.](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#writing-well-typed-decorators) with generic types that are used in args fails with the error

    Types of parameters 'args' and 'args' are incompatible.
        Type 'unknown' is not assignable to type .

### 🔎 Search Terms

decorator, generic, unknown

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because these decorators are only available starting in 5.0+

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAGzgczQUwCYFlNQAWc2APACqEwDOANIgIIBOa1imAHlJmNmwIZgAngG0AuvQBKBEEzAA+ABQAoRGsRR+LAgC5EiojT2Ua9AHQWtrPc1YBKRAF55iaVFlhaq9RATcuegDCyPzU1PhEJAAimL5M-FBwTIF+nFAUVHT6htTGmeaWLLmMRQ7OrjJy8soOAN7ear5g1FCIALYExNgAcvwdTogAylBMMGBoik3+UGZgfZh2ANwNiKCQsAiITJgADiEQmB1gUBFdBpl5pogWZlbFttR2em4eiPXqH4hN1HDImGaoCYAAwAMgB5ADiegAosdMKNxu1OiREAByAAktQ6kR68wAvqizEC7CsPt9WttqCBkK1HBorAQzBB+MhkOcrjc7ktST4ED8-gD0IpQZCYRwYLBEdiumjMdKSL0OgSiSTPuptu45FtMFSacsPniVhrXts9vwDkcTsjsMtDcoICEwogAGJwODKd7qAACgKweGtK0BJmoFCUzNZACNzQBrPSKO7GMouABucBg2CeiFT6beyhWhrxQA)

### 💻 Code

```ts
function loggedMethod<This, Args extends any[], Return>(
    target: (this: This, ...args: Args) => Return,
    context: ClassMethodDecoratorContext<This, (this: This, ...args: Args) => Return>
) {
    const methodName = String(context.name);
    function replacementMethod(this: This, ...args: Args): Return {
        console.log(`LOG: Entering method '${methodName}'.`)
        const result = target.call(this, ...args);
        console.log(`LOG: Exiting method '${methodName}'.`)
        return result;
    }
    return replacementMethod;
}

class Foo
{
    @loggedMethod //fails
    logThis<T>(callback: (args: T) => void): void {}
}
```

### 🙁 Actual behavior

Compile error. I don't see why it needs to go deeper than the basic Args to be able to match the signature.

### 🙂 Expected behavior

No compile error, since this seems properly constrained to me. If not, how to properly type this to work on any method without resorting to `ClassMethodDecoratorContext<This, any>`?

**Comment by mtripg6666tdr** [comment]
I have same problem. is there any solution? currently no way other than just to use `@ts-expect-error`?

**Comment by ajvincent** [comment]
This might provide a hint: [Jasmine spec code testing](https://github.com/ajvincent/es-membrane/blob/dc226645f250ecd8fb365f3bdfb59f1402b9a4de/_02_mixin_decorators/spec/_types/ClassMethodDecoratorFunction.mts) a [custom `ClassMethodDecoratorFunction` type](https://github.com/ajvincent/es-membrane/blob/dc226645f250ecd8fb365f3bdfb59f1402b9a4de/_02_mixin_decorators/source/types/ClassMethodDecoratorFunction.d.mts).  No `//@ts-expect-error` there.

**Comment by mat813** [comment]
This no longer seems to give an error with 5.4.2.
