### ISSUE TITLE
Function return type obtains different value than type alias definition even though both are explicitly set to same values

### ISSUE THREAD

**Issue by Durisvk** [microsoft/TypeScript#54136]
# Bug Report

### 🔎 Search Terms

- `return type`
- `control flow`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed all the FAQ entries

### ⏯ Playground Link

[[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)](https://www.typescriptlang.org/play?#code/FAkFwTwBwUwAgHIwM5hgEwGIEsYBt0BJAOwHkAjAKxgGMwAeYOOAFQsrhgA81j1k4Aeyq0wAGiasACgEMwAC048YfAQCcYM9IOJ4IcVGuzEA5gG0AuhOYsc+dEt78DYI6eAA+OAF5pcxdxOApaSAPysdgSOKs4A1jAQggBmrOySzOFsVGa2uAQW6XAAXHAArnwwScYYkiUssgrRqnBmxkkwanAAEproYnAAdENtHawy2HgFGd29TXEJyalUhZnjeHMChsbmU8x7mexmPVoWG3AjnWl713Dh7GfC1HSFN7eIKGhYeURkInT07H6LDWQMi6A8LxuJXK6Eq1XQkOY0IqVWINVeyNhqPRe0xcLRCKRZRR8IA3OBoPApIJjGg1PQspQgQ0AspmhotDo9C43DsvL4AN6SMwAaXOxDg8USKXq-gsdRZotOgRiAili0Zb0ZOUVIospxKaIAbh1yQBfcnAbhQQRqMBwGg6VBwGQ0GgoZBIVAYME+OCMGz3FXNR6iax+RrB5wc7S6fRbUyWcO5exnBMmTwACkkjzqgMkUH8Cv84aq9jqYOAAEoSl7PmCSOxRAzARH5KDvvyvELmJBYHAAEooUp4e2+Os+76Nv4MRnMksRTvk5h4GD2m20jolamb+lztv8oRUF0CGTECDLuBJW1wTOO4jO5ClciFxqLV-yKtwHt7bApTPYMgTZ0JmG7EHSX4AGSQQYz4fuKcBgRB36Qkhoy+GhahmE+L7+CekoLCkfYwO+NLgR0pwyKe56XswZqcHgyDwBoYClGoEowviGD4UOT6jpeZogMwLFsRKAFATOoFkch0FXt8CGYSst6YWYZZRFRBHSnAxGkbulECBOXz2NOTwMIiSxMuZsoKOGrwpgQkIeFWhR4ti6BfhpvEjmA5qWhS-aEBJpkMoeLAPDObyZmFUYCMQI7rOESQyIx8AlK4pQwF+JRJSl5LWra9r3s6gHAWO-rRWyzhnhAHiZrmrA1nAgWlSFPgQswmY6Skjw+N4vgAEShnQ-VwLJPUAIR9XAcV4HgHkCM1M4hX5xFwAAGn6hkNr8wUCi6JR7eQB0OiUACMcD0Zd-RmP1Mj9f0-XkP1VhwP1ND9R4pJwAA9N9rDyIB5wCI6agaM8wBFfaXB+q67rIJ6HyTvY2bMHtMjHUd34nXA52XRd+GQ+GN13Q9T36Q6TriJIb0jRpkPVl9v3aQDAiA5xblAA)

### 💻 Code

```ts





type NestedFieldInObject<
  TObj extends object,
  TPath extends readonly string[],
  TField extends string
> = TPath extends []
  ? TField extends keyof TObj
    ? TObj[TField]
    : undefined
  : TPath extends [infer Head, ...infer Tail]
  ? Head extends keyof TObj
    ? Tail extends string[]
      ? TObj[Head] extends infer Obj
        ? Obj extends object
          ? NestedFieldInObject<Obj, Tail, TField>
          : undefined
        : undefined
      : undefined
    : undefined
  : undefined;

type Pointer<TObj, TPath extends readonly string[]> = {
  [K in keyof TPath]: TPath[K] extends keyof TObj ? TObj[TPath[K]] : never;
};

export const accessNestedField = <
  TObj extends object,
  TPath extends readonly string[],
  TField extends string
>(
  obj: TObj,
  path: TPath,
  field: TField
): NestedFieldInObject<TObj, TPath, TField> => {
  type Result = NestedFieldInObject<TObj, TPath, TField>;
  let pointer: Pointer<TObj, TPath> = obj as any;
  for (const subpath of path) {
    if (isObject(pointer) && subpath in pointer) {
      pointer = pointer[subpath as keyof typeof pointer] as any;
    } else return undefined as Result;
  }

  return (isObject(pointer) && field in pointer
    ? (pointer[field as keyof typeof pointer] as NestedFieldInObject<
        TObj,
        TPath,
        TField
      >)
    : undefined) as Result;
};



type IsObject<T> = T extends object ? (T extends null ? false : true) : false;
export const isObject = <T extends any>(obj: T): IsObject<T> =>
  (typeof obj === "object" && obj !== null) as IsObject<T>;


type X = NestedFieldInObject<{ a: { b: { c: 1 } } }, ["a", "b"], "c">; // This is correct

const x = accessNestedField(
  { a: { b: { c: 1 } } } as const,
  ["a", "b"] as const,
  "c" as const
); // this is undefined
```

### 🙁 Actual behavior

**The `const x` receives type `undefined`** even though the return type of the `accessNestedField` function is explicitly set and the `type X` receives a correct type with exactly same invocation.

### 🙂 Expected behavior

**The type of `const x` should be 1** just like in `type X`

**Comment by fatcerberus** [comment]
The types are not actually the same.  `as const`, besides inferring literals, also infers readonly; if you instantiate `X` with `readonly [ "a", "b" ]`, it likewise resolves to `undefined`.

**Comment by Durisvk** [comment]
Okay, so the issue was that the `extends` condition didn't work on arrays because `readonly any[]` does not extend `any[]`. Thanks for pointing that out. Here's a corrected version of the code in case someone needs it. I'm closing the issue:

```ts
type NestedFieldInObject<
  TObj extends object,
  TPath extends readonly string[],
  TField extends string
> = TPath extends readonly []
  ? TField extends keyof TObj
    ? TObj[TField]
    : undefined
  : TPath extends readonly [infer Head, ...infer Tail] // added readonly
  ? Head extends keyof TObj
    ? Tail extends readonly string[] // added readonly
      ? TObj[Head] extends infer Obj
        ? Obj extends object
          ? NestedFieldInObject<Obj, Tail, TField>
          : undefined
        : undefined
      : undefined
    : undefined
  : undefined;

type Pointer<TObj, TPath extends readonly string[]> = {
  [K in keyof TPath]: TPath[K] extends keyof TObj ? TObj[TPath[K]] : never;
};

export const accessNestedField = <
  TObj extends object,
  TPath extends readonly string[],
  TField extends string
>(
  obj: TObj,
  path: TPath,
  field: TField
): NestedFieldInObject<TObj, TPath, TField> => {
  type Result = NestedFieldInObject<TObj, TPath, TField>;
  let pointer: Pointer<TObj, TPath> = obj as any;
  for (const subpath of path) {
    if (isObject(pointer) && subpath in pointer) {
      pointer = pointer[subpath as keyof typeof pointer] as any;
    } else return undefined as Result;
  }

  return (isObject(pointer) && field in pointer
    ? (pointer[field as keyof typeof pointer] as NestedFieldInObject<
        TObj,
        TPath,
        TField
      >)
    : undefined) as Result;
};



type IsObject<T> = T extends object ? (T extends null ? false : true) : false;
export const isObject = <T extends any>(obj: T): IsObject<T> =>
  (typeof obj === "object" && obj !== null) as IsObject<T>;


type X = NestedFieldInObject<{ a: { b: { c: 1 } } }, readonly [ "a", "b" ], "c">; // This is correct

const x = accessNestedField(
  { a: { b: { c: 1 } } } as const,
  ["a", "b"] as const,
  "c" as const
); // this is now correct too
```

https://www.typescriptlang.org/play?ts=5.1.0-dev.20230502#code/C4TwDgpgBAchDOwIBMBiBLCAbZBJAdgPIBGAVhAMbAA8AUFFAComlQQAeS+y8UA9mUrAANPSYAFAIbAAFm04RuvAE4RJyPviwgoiZenwBzANoBdUQ0YZsyeVx67g+o7QB8UALwTpcjvZVqGlo6ZmIA-EzWOHaKDgDWECB8AGZMLGIMEcxkxlaYOKYZUABcUACu3BDJBihipYxSsjFKUKrqmtpQxgbJEMpQABKBwlAAdOM9fUyS6FiFmYOBzfGJKWlkRVkzWMsB7cGOzibzDKdZLMZD6qa7UJP96adPUBEstwLkVEXPL7AISGh8ngiIIqNQWCNGNtIVFkK5vs9ShVkFUasgEQwkZVqvhaj8sSicXjTgTUbj0Zjyti0QBuWi0UCQKDiPgGJDKajZUiQxq+BQtNpBTp6AzHdxeADeYmMAGk7vgoAkkqkGj5TPVebKbn5YrwlWsub8ublNTLTDdSriAG59OkAXzptA4YD4ymAUAomkQUEkFAoCHgcEQKFhnigdEsbx1LQ+Qgs3ia0Ycgo6OhFRjM8byNlu6cMbgAFGIPvUIWIwD4NT549UbPVYbQAJSlIMA2EEFhCTkQhMyGFA8XuKUMRnQABKCDKWHdXlbIaBHdBNC5POrkQHdIYWAg7pdbL6pRZ+45K974v4ZB9vEk+BAm6gyVdUALnvw3vgZWIFaaa2-MkbUDDqc6CpAW6DwJ2VAFnu+DsgBABk8G6J+f7ylAMFwYBCIYVMXg4coxgfl+PhXoqqypKOv6srBfQ3JI163veDB2mwWDwNAqjAGUygKsiZIoKRE4ftO952vSDCcdxCpgRBS7QdRmGIQ+QJofhmzPvhxi1tE9FkcqUCUak+F0bwc6AjYi6fDQGLrNyNmqrI8Y-NmOAIq4jZFKSRLIABulCVOwD2o69KjlAuCyVZnLnow7xLr8BYxUmvD4FOOwRMkkhsdApROGUEAAaUGVZXSzquu6r7euBkEzuGiX8g4N4gK4BYlkwzZhRFXaMIOYgFoZF6sB4Q1QAARLGVAjVASkfFAACEw0pVgWC+bw4XVVFwWhQAGmGZntiCkUSj6pRHcQJ0eqUACMUAsbdIwpgcxijZII0jCNxCTeYo0UCNrg0lAAD0ANMDI4F3LwnrKKoXy0BV7rsGGvr+vAgb-PONhFgwR2SOdZ2ARdUDXbdN2kXD8bGCNL1vR9Jkel6IhiCNP2k-TTb-UDBmg7wYOQ9D7rAHwfBAA
