### ISSUE TITLE
Types not flowing down as expected to `sort`

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#5414]
I think I've encountered a problem with types flowing down correctly. Take the following code:

```
function stringComparer<T>(propLambda: (item: T) => string) {
  return (obj1: T, obj2: T) => {
    const obj1Val = propLambda(obj1) || '';
    const obj2Val = propLambda(obj2) || '';
    return obj1Val.localeCompare(obj2Val);
  };
}

var myBooks = [
	{title: 'Sherlock Holmes'},
	{title: 'Moby Dick'}
];

myBooks.sort(stringComparer(x => x.title));

console.log(myBooks);
```

The `stringComparer` allows us to sort an array, given a string lambda expression.  In this case I'm looking to sort my array of books by their title.  

However, even though `sort` is expecting `compareFn?: (a: T, b: T) => number` and `stringComparer` delivers on that with `(obj1:T, obj2: T) => number` there is a problem.  The type of `x` in `x => x.title` has not flowed though as expected.  It is not `{title: string}`.  It's just `{}`.

You can see this in the playground [here](http://www.typescriptlang.org/Playground#src=function%20stringComparer%3CT%3E(propLambda%3A%20(item%3A%20T)%20%3D%3E%20string)%20%7B%0A%20%20return%20(obj1%3A%20T%2C%20obj2%3A%20T)%20%3D%3E%20%7B%0A%20%20%20%20const%20obj1Val%20%3D%20propLambda(obj1)%20%7C%7C%20''%3B%0A%20%20%20%20const%20obj2Val%20%3D%20propLambda(obj2)%20%7C%7C%20''%3B%0A%20%20%20%20return%20obj1Val.localeCompare(obj2Val)%3B%0A%20%20%7D%3B%0A%7D%0A%0Avar%20myBooks%20%3D%20%5B%0A%09%7Btitle%3A%20'Sherlock%20Holmes'%7D%2C%0A%09%7Btitle%3A%20'Moby%20Dick'%7D%0A%5D%3B%0A%0AmyBooks.sort(stringComparer(x%20%3D%3E%20x.title))%3B%0A%0Aconsole.log(myBooks)%3B)

I'm not certain if this is a but or if I've missed a trick here - I thought I'd best report it just in case.

**Comment by RyanCavanaugh** [comment]
Same root cause as #5256 -- contextual types do not flow through the return value of a function.

**Comment by johnnyreilly** [comment]
Glad it's already been raised - thanks for responding @ryancavanaugh.
