### ISSUE TITLE
A union is not assignable to property of a union object if the property itself is a union

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#54147]
# Bug Report

### 🔎 Search Terms

- Type is not assignable to type.
- Types of property are incompatible.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAogHsCA7AJhFA1AhgGwK4QA8AKgHxQC8UxUAPlAN4AkWSIA-AFxQDkYATgHtI-UDwC+AKEmhIUABqVGsiN3iJU6bPiI8sPUuLrLwq2AmRpMuAoR4AjA+IDc0gMaCkAZ2BQVSvE0AMwBLJHQAQigsL159YwceV0kPb184AEZuRSoGFRd3Tx8oOAAmbKU80249CWTU4rgAZgrclRrHAqA)

### 💻 Code

```ts
type ExtendedValue<T> = T | {$any?: 'property'}

type X = {type: ExtendedValue<'a'>} | {type: ExtendedValue<'b'>};

const type = undefined! as 'a' | 'b';

const x1: X = {type}; // error, should be okay

const x2: X = {type: 'a'}; // okay

const x3: X = {type: 'b'}; // okay
```

I tried to find a duplicate but too many noises searching terms I can think of.

**Comment by MartinJohns** [comment]
This is working as intended. An object with a property being either `"a"` or `"b"` is different than either an object with a property always being `"a"` or an object with a property always being `"b"`

**Comment by vilic** [comment]
@MartinJohns Unless they are actually equivalent and that's why it works in case of `{type: 'a'} | {type: 'b'}`.

**Comment by vilic** [comment]
Hi @RyanCavanaugh,

Could you please give me a hint why it works for `{type: 'a'} | {type: 'b'}` but not `{type: ExtendedValue<'a'>} | {type: ExtendedValue<'b'>}`? I guess it might be some issue with complexity or performance?

And some keywords to relevant discussions would be appreciated. Thanks.
