### ISSUE TITLE
Constructor beside class name (Similar to Java Record, Similar to Kotlin class)

### ISSUE THREAD

**Issue by hannah23280** [microsoft/TypeScript#54150]
I not sure if anyone has suggested this before (at least I could not find in the issues section)

To make the class definition even more concise, can consider this

**Current way**
```
 class Horse{
      constructor(public name:string, private color:number){}
}
```

**Suggested Enhance Way**
    `class Horse (public name:string, private color:number) {}`

In fact, for extra bonus, if the class body is empty, braces are optional
     `class Horse (public name:string, private color:number)`

Of course, if needed additional constructors, can define in the class body, as per current way of doing

The suggestion to put constructor beside the class name is aspired by Java Record and Kotlin class definition.

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template. It contains a viability checklist, which your proposal violates. Your suggestion is not in line with the TypeScript Language Design goals.
