### ISSUE TITLE
Exported decorated class is not defined in decorators API stage3 in CommonJS.

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#54158]
# Bug Report

### 🔎 Search Terms

decorators, export

### 🕗 Version & Regression Information

TypeScript@5.0.3 
`experimentalDecorators` : false
`module` : `CommonJS`

### ⏯ Playground Link

https://www.typescriptlang.org/play?module=1#code/GYVwdgxgLglg9mABAEQKYTgCgHS4IYBOA5gM4BceYAngNoC6AlAN4C+AsAFAACaGnqADwAOcAlEQQANnhIlEAYUStOGMCTiTU2SXCKZ5DIA

### 💻 Code

See playground

### 🙁 Actual behavior

Thrown `C is not defined `

### 🙂 Expected behavior

Log class C correctly

**Comment by jakebailey** [comment]
Duplicate of #53332?

**Comment by jakebailey** [comment]
Yes; works in the beta and nightly.
