### ISSUE TITLE
Incorrectly unifying sub-classes which extend a class with a generic, when both sub-classes have some intersecting fields

### ISSUE THREAD

**Issue by jasononeil** [microsoft/TypeScript#54162]
# Bug Report

### 🔎 Search Terms

unifying subclasses which extend a class with a generic, and both subclasses have intersecting fields

### 🕗 Version & Regression Information

- I have tried `5.1.0-beta`, `5.0.4`, `4.9.5`, and `3.9.7` and the `5.1.0-dev.20230506` nightly in the playground and all have the same behaviour.
- I have reviewed the FAQ "Why do these empty classes behave strangely" which gave me the workaround I could use in my situation. I still believe this constitutes a bug though (more details below)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYGwhgzhAECyCeBhcUA8AVAfNA3gKGmgDcwQBXAUwC5p0BuA6YAewDsIAXAJzOA+a4AKAA5guYALY10ASlyNCHABYBLCADoS5CtAC80UeIkNCAXzzm8oSDAByknRQAeHCqwAmMBMhuoc0VgcaTi4VVgBzaFNsHHNrKGgAQXDHFzdPOCQUCD9oMBSaVjIJACMKLiiYuOykkBB7CQoYZ1cPLyzff0DG4O4w8IAaAJVgAGtupt7QiIBtAF1K+UIWdm5efiFDSSouoOgQ-qHWEfGHCCn++ai5fEJCCDJhcpExSRkTO5WIZhAKdRBmOFBAAiAASFHg0GBQy2EnUxzGEw0ACtmGEQdABPslMwyCB3NAAJL7MCQ4Eyd6McyWAD0NNoqhgamgYQAZuUuBQCZBoAADQQceBPZis6ANHQAH2gguFouSFBk815QwA7qpgEoWTBwsxmO4rGxOHkuFwAIx6aAzcVDeVzBh4OkM5nO1jsk1cvIwfkyigisUORVzXnQNUjTXE5RhUZalmsFjuvgG1bGrgAJgtVocNrq4ogdrweDEafUEjAwkEoBguhijEd6EZIZUdWgnIeIA4sbyLbIrA4Kka0A5WN5wDArAA5B2wMBgE0YMIuMwnlxBVDUWFoQZXnCEadGkyYD33BRWWEubzGKwKCqmCAIIIcBMaMCAFKQNjA0wyCwyIA)

### 💻 Code

Setup: 

- I have a class that uses a type parameter in a constructor argument
- The subclasses are structurally the same (same methods, same properties) 
- But the constructor body may be different, and utilises the different argument to the constructor (because the type parameter is different)

```ts
class MyClass<T> {
  value: T;
  constructor(param: T) {
    this.value = param;
  }
}

class Name extends MyClass<{ name: string }> {}
class Age extends MyClass<{ age: number }> {}
class AllNames extends MyClass<{ name: string, nicknames: string[] }> {
  constructor(param:{ name: string, nicknames: string[] }) {
    super(param);
    console.log("Hey ", param.nicknames.join(" or should I say "));
  }
}

// This is inferred as `(typeof Name | typeof Age)[]`, which is good
const arr1 = [Name, Age];

// This is inferred as `(typeof Name)[]` which I think is incorrect
const arr2 = [Name, AllNames];

arr2.map(cls => {
  // This will result in a runtime error `can't access property "join", param.nicknames is undefined`
  new cls({name: "Jason"})
})
```

You can also reproduce this outside of arrays using the same types, which may be an easier test case:

```
const nameCls: typeof Name = AllNames;
new nameCls({ name: "Jason" }); // this will throw a runtime error as `nicknames` is not supplied.
```

### 🙁 Actual behavior

- TS treats `AllNames` as compatible with `Name`, even though they require different constructor arguments.
- The type `[Name, Age, AllNames]` is inferred as `(typeof Name | typeof Age)[]`
- This leads to runtime errors.
- Note: TS treats `Name` and `Age` as incompatible types. I suspect the common `{name: string}` field that both `Name` and `AllNames` share in the type parameter is the cause of the issue.

### 🙂 Expected behavior

- `AllNames` should be considered incompatible with `Name`, in the same way that `Age` is considered incompatible with `Name`.
- The type `[Name, Age, AllNames]` should be inferred as `(typeof Name | typeof Age | typeof AllNames)[]`

### Comment 

This seems similar to [the FAQ entry describing empty classes being compatible](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely), but I am submitting this issue anyway as TS does differentiate `Age` and `Name` in the way I expect, despite being structurally similar (identical if you ignore the type parameter). The problem only occurs when the type parameter has intersecting fields.

It also leads to runtime errors despite the compiler reporting no type errors.

If this is a similar case to the FAQ entry and is in fact the expected behaviour, feel free to close this issue.

**Comment by whzx5byb** [comment]
I think this is because ts treats class constructor parameters as bivariant (See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant). 

Here is a short example to show.
```ts
class A {
  constructor(value: string | number) {}
}

class B {
  constructor(value: string) {
    console.log(value.charAt(0))
  }
}

let a: typeof A = A;
let b: typeof B = B;

a = b; // unsound
new a(0); // will cause runtime error

// define constructor in the form of function properties
interface _A { 
  new: (value: string | number) => A 
}
interface _B { 
  new: (value: string) => B 
}

declare let _a: _A;
declare let _b: _B;

_a = _b; // error as expected
```

**Comment by jasononeil** [comment]
Oh that looks like a relevant FAQ entry, I think I'd been too focused on this being about classes, but if its more about the constructor as a function that makes sense.

It also explains why `Age` in my example was incompatiblen - the bivariance of the function arguments means that it has to be compatible in at least one direction, and in my case `{ name: string, nicknames: string[] }` could be provided as a valid value to `{ name: string }` (even though the reverse is unsound / incorrect).

In that case I'll close this issue.
