### ISSUE TITLE
Type hole: everything is assignable to element of generic indexable

### ISSUE THREAD

**Issue by awerlogus** [microsoft/TypeScript#54160]
# Bug Report

### 🔎 Search Terms

generic tuple element assignable

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230506#code/PTAEDkHtQUwJzpOAaUAjArgF1gDwA4wDGWMAJgLABQRkAdgM44CGoAvKADwAqepdZBqADaGOgGs6kAO50AugD4AFLgBcobgEp13YQAY57BaACMAJgDM1aiFBM4ASzoBzUFgCehVJhx0MAWzR4UAA3ZgAbDBhqWkYcNHZQZiVhAHJUuU0gA)

### 💻 Code

```ts
// No error, but expected
const a = <T extends [unknown]>(x: T): T[0] => 123

// string type, but number value
const b = a([''])
```

### 🙁 Actual behavior

It's possible to return everything

### 🙂 Expected behavior

It's possible to return entities which only have `T[0]` type

**Comment by fatcerberus** [comment]
Hmm, it seems like TS is eagerly reducing `T[0]` to `unknown` here.  Not sure whether that’s intentional or not.

**Comment by typeholes** [comment]
Oddly, this does error:
`const a = <U extends unknown, T extends [U]>(x: T): T[0] => 123`

**Comment by fatcerberus** [comment]
@typeholes Username checks out

**Comment by Andarist** [comment]
Essentially the problem is the same as the one here:
```ts
// No error, but expected
const a = <T extends { foo: number | string }>(x: T): T["foo"] => 123

// string type, but number value
const b = a({ foo: 'str' })
```

In other words, it's not limited to tuples. It's actually about indexed accesses with non-generic index constraints that are *concrete*~ (index signatures are not prone to this) on generic objects. The code responsible for this is [here](https://github.dev/microsoft/TypeScript/blob/2291afc187359593f9926195f3b2d683ccd0e675/src/compiler/checker.ts#L21519-L21536)

**Comment by RyanCavanaugh** [comment]
Clearly the only sound behavior in this case is to only allow expressions that are exactly of the form `x[0]`, but `x[0]` doesn't have the type `T[0]`, it has the type from the constraint. It's not clear there's anything we could do to improve the situation here except to radically rework how indexed access works in generic functions, which I don't think is quite on the table yet given the motivating scenarios apart from this one

**Comment by mkantor** [comment]
I found this issue after coming across some code like [this](https://www.typescriptlang.org/play?jsx=0#code/MYewdgzgLgBFCm0YF4YB4AqN4A8FgBMIYBvGAQwC4YBXMAazBAHcwYBfAPgAodqMAlCk6kYOAHTkUMAIwAmAMwcAUKEiwc0slRgByXSoTReA1eCRMoAZSgAnAJZgA5tInllAeg8wfMAHoA-EA):
```ts
const test = <T extends { a: unknown }>(x: T) => { x.a = 123 }
const x = { a: '' }
test(x)
const notString = x.a
//    ^? const notString: string
```

I think that's a different symptom of the same underlying problem.

**Comment by awerlogus** [comment]
@mkantor You may be looking for https://github.com/microsoft/TypeScript/issues/39915

**Comment by mkantor** [comment]
I stumbled across this again via default values for destructured properties of type parameters. [Code like this is legal but unsound](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAZjAvDAPAFRgUwB5U2AEwhgG0wBXAWwCNMAnAfgF0A+AChIEMkYAWAJiYAuGGgCUItCQAMTJCxicAUEtCRYnEeUKY4ASzCYCPOByZjV4CCAA2mAHQ2QAczacxMAPSeYT58QADAQCgA):

```ts
<T extends [number?]>([a = 42]: T): T[0] => a
```
