### ISSUE TITLE
Compiling uses wrong order, which makes compiled code not work

### ISSUE THREAD

**Issue by emanuelfranklyn** [microsoft/TypeScript#54170]
# Bug Report

### 🔎 Search Terms

Typescript not a constructor
Typescript compiling in wrong order
typescript _1.class is not a constructor

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about compiling order

### ⏯ Playground Link
```ts repro
// @filename: index.ts
export * from './AFunction';
export * from './BClass';

// @filename: AFunction.ts
import { BClass } from './';

const myInstance = new BClass();

export default function activate() {
    myInstance.foo();
}

// @filename: BClass.ts

export class BClass {
    foo() {
        console.log('bar');
    }
}

// @filename: test.js
// Assuming that the js file is in the same folder that the compiled typescript code
const { BClass } = require('./')

const myInstance2 = new BClass();
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEDMEsBsFMB2BDAtvAXKaiAm8APAOgBcBnAWAChCAHAewCcTQAqUSR+1UAciOABBAGIBXRAGMS0eol4BuanSYt2nbnwEAhAMKxkZMgurUQEGAhTosI8VJmJSlKtFQNmoAN6hd+w6ABfDi4efmBjKmoJWTIWVABPAElEWORJeFAAXlBEeAB3Hz0DMgAKAEpFSJoCdxZ8SGRRWBZIO2lZUGR7ADdkEnhyr2pQEdAE5NT0okh6enLKgJMqMyg4JDRMQr8yJyXlDwltreKhqlHQaJSSRlEpJkHPYfPRs1x6UFjRSEgnkcWq84zOZlU7PUaXMj0BBEWD0ADmJV4ACNkIxeBVfoFqAEgA)

### 💻 Code

All the code is already in the workbench and markdown above

### 🙁 Actual behavior

It will show an error in the AFunction compiled file saying that _1.BClass is not a constructor, because inside the compiled index.js file AFunction is being exported first than BClass, and since AFuntion uses BClass in the global scope of the file this is executed first than the definition of BClass in the BClass.js compiled file, causing it to error when you try to import index.js

### 🙂 Expected behavior

The typescript compiler should detect that BClass is a dependency of the AFunction file and export it first inside the compiled index file

### Extra info
inside the compiled index.js file on the last lines for that specific code theres the order of the exports as such
```js
...
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./AFunction"), exports);
__exportStar(require("./BClass"), exports);
```

Just changing the BClass line to be on top of the AFunction class fixes the issue

```js
...
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./BClass"), exports);
__exportStar(require("./AFunction"), exports);
```

**Comment by LoboMetalurgico** [comment]
I can confirm.

Typescript: 5.0.4

**Comment by RyanCavanaugh** [comment]
This is the expected behavior; In the very ideal case we would issue an error here, but typescript will never reorder the statements in your code to try to make something work. You need to write things in the correct order if they have runtime load order dependencies

**Comment by emanuelfranklyn** [comment]
I tested using vanilla Node.js (version 16) with the .mjs module files, and while it also shows the same problem different of typescript which issues an error that looks like it's an actual error on the file that imports (and not in the index file itself), vanilla Node shows a way more appropriate error, that BClass has been used before declaration, typescript error also seems rather generic from what I gather from Google searches about the error, so while it may not be possible to automatically fix the ordering, it would be nice if a proper error was raised saving a lot of debugging time looking at the wrong places.

**Comment by fatcerberus** [comment]
@emanuelfranklyn What you’re seeing is a runtime error, which is out of TypeScript’s control.
