### ISSUE TITLE
`...infer X extends TypeParameter[]` in conditional type inappropriate binding

### ISSUE THREAD

**Issue by webstrand** [microsoft/TypeScript#54197]
# Bug Report

### 🔎 Search Terms

conditional type, extends, infer, spread, tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about extends

### ⏯ Playground Link
[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nAPAaQDRQCpQgD2BAOwBMBnKAJwgEMi4CAbEKAVwIGsC4B3AgbQF0AfFAC8mbHkKkK1Wgya8qBEOgB06gJYEAZhHJQAGhPzEylGnUYt2nHgP5QA-IagAuKAQgA3PQG4AUKCQUABCVOQo6Fi4JtLmclasHNx8QqLiMVJmspYKSipQ6qpauvpGmaYyFvJQyPZOLu6ePuQBQdBhAF6RGZKV8bnWyXZpYtF9cTk1ispqmjp6LhWT1VYAFMhQAD5QAERUu9t7AEa7AJT1zkZN3n7+geDQOOnwSPuHO7un6Lzv6F+7f6nIT+AD0oKgkIAeo4HsEmGIwhF3kcAT8-idAZi0mCIdDYe0oJ10l1ECjPt8oL8DkCsQCQeDIVAYf4gA)

### 💻 Code

```ts
type Foo<K, T extends readonly unknown[]> = T extends readonly [any, ...infer X extends readonly unknown[]] ? X : never;
type Bar<K, T extends readonly unknown[]> = T extends readonly [any, ...infer X extends readonly K[]] ? X : never;
type Baz<K, T extends readonly unknown[]> = T extends readonly [any, ...infer X extends readonly (K | "a" | "b")[]] ? X : never;

type x = Foo<"a" | "b", ["a", "b", "b"]>
//   ^? - type x = ["b", "b"]
type y = Bar<"a" | "b", ["a", "b", "b"]> 
//   ^? - type y = readonly ("a" | "b")[]
type z = Baz<"a" | "b", ["a", "b", "b"]>
//   ^? - type z = ["b", "b"]

```

### 🙁 Actual behavior

The conditional types do not produce the same output:
```ts
type x = Foo<"a" | "b", ["a", "b", "b"]> // ["b", "b"]
type y = Bar<"a" | "b", ["a", "b", "b"]> // readonly ("a" | "b")[]
type z = Baz<"a" | "b", ["a", "b", "b"]> // ["b", "b"]
```

### 🙂 Expected behavior

The conditional types should all produce the same output. The fact that `K` is a type parameter should not affect the output.

```ts
type x = Foo<"a" | "b", ["a", "b", "b"]> // ["b", "b"]
type y = Bar<"a" | "b", ["a", "b", "b"]> // ["b", "b"]
type z = Baz<"a" | "b", ["a", "b", "b"]> // ["b", "b"]
```

Alternatively if that is infeasible for technical reasons, the conditional type should fail. Inferring the constraint makes traversing the tuple impossible.

**Comment by warriordog** [comment]
Here's another reproduction, showing how it works if the tuple is reversed.

```typescript
type Heads<T extends any[]> = T extends [... infer Rest, any] ? Rest : never;
type Tails<T extends any[]> = T extends [any, ... infer Rest] ? Rest : never;

// Expected: [1, 2]
// Actual:   never
type heads = Heads<[1, 2, 3]>;

// Expected: [2, 3]
// Actual:   [2, 3]
type tails = Tails<[1, 2, 3]>;
```
