### ISSUE TITLE
Illegal types disrespecting generic constraints can be created

### ISSUE THREAD

**Issue by lxhom** [microsoft/TypeScript#54209]
# Bug Report

### 🔎 Search Terms

constraint, satisfying incorrectly, illegal type

### 🕗 Version & Regression Information

- This changed between versions 4.6.4 and 4.7.4

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.4&ssl=37&ssc=56&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgEIHsAeAeAKgPmQG8AoZc5ANzgBsBXCALmVxIF8SSwBPABxVxwA5kIgATDDgCiyCJkggxAZzRZscEN3yEAvMhkAyYgH1jAIyzjmYKAw4kA9A+Q7XyJ5yfJ+sCAjA03Mg0EEK0XHwoADKhtIJCki4swqISapLYIHQAtmbQ2p7OSgAW6HQ0YrJQUOhQADTIWbnQyGLoEErgsvIQiqo4GloR-MgAkjQhYTTxiXrxqRlNeVD4hchwyDB0IP7A6CDIYMVwYOsISLxgKhDARy0a69VwQY7O6DDIFpgdyLXryEpQEIQp8sOsVBtqPQICQtjswHsDkp0NkIKUAO4xKZ4boKZT9dSaAoACihDGYuAAlBSUuIMgQ1iErt4oBA8chgMhsnAxCgNtlgEowHAANYoYrQPl9RAIYC88C0QKvZDomqQZAAQSe3EJWg5ICFEB5vw+Wqgz2wGUGBThu32AJRaPQmNiNBxcjxKjNFutq1JtHJLGpxAA2gBpfXIMXcd4sAC6NJEdLUuHDcfwbGQytTYbjyGOKh4I0GADps7S0gMiRyVCB0KclHReLx0EpxId0N1BWAy150cUgoLDsUhwgUbxgDQgQB+WecW0I+3I1EYrG0PD4f3QimU4hkCissB0KAHb3cEuCs9bhi76f7igUMkQEvc3jElA6QjEogl38QBqmF8ViHLYEBsJSu6MPeD7EL+JZPgB5iWGI1igRw9heOQlDYThuHYfm6CUC0dysh2AIQCgdyHJEJBMsgIZLNAMxYHmejLk6LpTMSIYAMxxpSyqcm0XRHKAIrDicNYAk2LZtpUYCdscza9J8fhwHQbbKtsU5ipGU4gCgACMhkNPMyY4IxKxSXW6LBK604AITIEAA) (change the version to 4.7.4 and 4.6.4 to see where the bug was introduced)

### 💻 Code

```ts
interface Box<T> {
    value: T
}

type TaggedBox<E extends Box<any>> = E & {__boxed: true}

// === //

// perfectly legal
type LegalTagBox = TaggedBox<Box<number>>

// should error, number doesnt extend Box<any>
type IllegalTagBox = TaggedBox<number>

// a function that accepts either an array 
// of boxes or a single box as a value
function somehowLegal<T extends Box<any>>
(value: T): TaggedBox<T>

// lets pretend i made a mistake here and accidentally
// wrote Array<any> instead of Array<Box<any>>
function somehowLegal<T extends Array<any>>
(value: T): {[K in keyof T]: TaggedBox<T[K]>} 
// T[K] has type any.
// TaggedBox<any> is not supposed to exist.
// why is this compiling???

function somehowLegal<T>(value: T) {
    return Array.isArray(value) ?
        value.map(e => ({...e, __boxed: true})) :
        {...value, __boxed: true}
}

//   vvvvvvvvvvvv this has the type TaggedBox<number> now.
let [numberTagBox] = somehowLegal([3])
// i dont think that is supposed to happen because
// unlike in line 11, TaggedBox<number> is now legal?! 
```

### 🙁 Actual behavior

A type that should not exist was created.

### 🙂 Expected behavior

This should error, because it isn't respecting the `extends Box<any>`

**Comment by lxhom** [comment]
@whzx5byb You're not wrong, replacing it with unknown does fix the code. Nevertheless, TypeScript should still a) catch that illegal invocation of TaggedBox (judging by line 11 that is supposed to happen), and b) not allow a type that directly contradicts itself to exist, even with any.

**Comment by somebody1234** [comment]
in general, generic type (and function type) definitions are typechecked when they are defined, not when they are used

**Comment by RyanCavanaugh** [comment]
Instantiation is not a process that can produce errors, except via constraint violation. These are the risks you undertake when you use `any`; you can instead write

```ts
declare function somehowLegal<T extends Array<unknown>>(value: T): {[K in keyof T]: TaggedBox<T[K]>}
```
