### ISSUE TITLE
Unexpected: implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#54211]
I am using latest insiders and have no editor open, then I just open `src/vs/workbench/services/history/test/browser/historyService.test.ts` and I am greeted with compile errors that do not show up when compiling:

![image](https://github.com/microsoft/vscode/assets/900690/98eb1dda-add8-4745-a31c-3724fc8b21c7)

**Comment by mjbvz** [comment]
Looks like #53955 and #51434. Hope the full logs from when this happens can help with the investigation

**Comment by jakebailey** [comment]
It shouldn't be related to #53955 since that one happens even when compiling with `tsc`, whereas this issue appears to only happen once you edit something.

**Comment by DanielRosenwasser** [comment]
Always helpful to have a server log or code-as-text when possible.

That said, do you see the same issue with semantic highlighting and inlay hints turned off?

**Comment by mjbvz** [comment]
@DanielRosenwasser Good thought. Just tested and I wasn't able to reproduce the issue after disabling semantic highlighting: `"editor.semanticHighlighting.enabled": false`
