### ISSUE TITLE
Parameters<> helper only shows the last declared overload

### ISSUE THREAD

**Issue by m-gallesio** [microsoft/TypeScript#54223]
# Bug Report

### 🔎 Search Terms

Parameters, Overload

### 🕗 Version & Regression Information

5.0.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgBrIN4FgBQz-JwAUAHgFzIDOYUoA5gJQUBuA9sACYDcuBhpFEAFcAtgCNoTZG048cAX1y4wATwAOKACrIAvMgAKcKHBERIUSgB5UAbQBEcOwF0AfDYAMTubgA2Z5CAU2noAjFzIAPQRyADurFAA1pS+-pRBusgOduFRyACiAEoFAPIFQeooAOTUtCB0lcjAlAGsYISUlMB0IHBifshgrAMVyJXC4tCVQA)

### 💻 Code

```ts
interface X {
    a(x: string): void;
    a(x: number): void;
}

type T = Parameters<X["a"]>[0];

let n: T = 1; // works
let s: T = "a"; // ERROR: Type 'string' is not assignable to type 'number'
```

### 🙁 Actual behavior

When using the `Parameters<T>` helper type on a function with overloads, the resulting type considers only the very last overload.

I noticed this while trying to extract tpe type of the second argument of `String.replace` which can be both a string and a replacer function; only the replacer function is seen.

### 🙂 Expected behavior

I would expect the previous code to consider valid all types which can be used for the function's parameters.
In the given example `T` should be resolved as `string | number`.

Possibly related to https://github.com/microsoft/TypeScript/issues/53541

**Comment by MartinJohns** [comment]
This is a design limitation. `Parameters<>` is a conditional type using type inference, and these have trouble with overloads. See [Inferring Within Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types):

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the *last* signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Comment by m-gallesio** [comment]
Understood, thank you for your quick response.
