### ISSUE TITLE
Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index function type

### ISSUE THREAD

**Issue by erikbrinkman** [microsoft/TypeScript#54220]
# Bug Report

When declaring a functional interface, you can usually add extra properties, define a function, and then manually attach the properties to meet the interface, e.g.
```ts
interface TestProp {
    (): void;
    readonly prop: true;
}

function prop(): TestProp {
    function inner(): void {
    }
    inner.prop = true as const;
    return inner;
}
```

However this fails if the sole property is a unique symbol, e.g. 
```ts
const symb = Symbol();

interface TestSymb {
    (): void;
    readonly [symb]: true;
}

function test(): TestSymb {
    function inner(): void {
    }
    inner[symb] = true as const;
    return inner;
}
```
unlike a normal "string" property typescript seems to fail to infer that this could be part of an interface so throws:
```
Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type '() => void'.
  Property '[symb]' does not exist on type '() => void'.(7053)
```
it also then seem to forget about the assignment and thinks that `inner` doesn't match the interface.

In my specific case, if the prop weren't readonly, you could cast and then assign. You can also do other "tricks" as seen in the playground link, but non are satisfying. More details are in the playground link.

Note that this is close to the realm of esoteric javascript behavior so I could be unaware of some edge case in the spec that affects inference in this specific case.

### 🔎 Search Terms

function, symbol, functional interface, implicit any

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `symbol`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/MYewdgzgLgBBCeBbARjAvDAyk5IA2AFAJQDcAUGQPSUxQAWAlhDAO4gBOA1hGQ2FAFN2AMwCGwATAAqA6AAV2IAA4wA3mRiaYxAFwwAbiAYATchq3sBo4+DzwYSxUr1R2AVwHkAvhWFuwwFAM4A5OutKyUArKauaafgFBIXxgQuGGJrFaMD5xMClCAHSOMRiuHjCizKCQUGbZllBu7GD5YKns3hTUtIzMNrJgAOSwbFy8-EJiEhHQAHJueHhZWulGphQNVjZgdqHKemCLeF1kCYHBrSVKC0vhMvPHK-H+F8ntaUR6GcbPOZtaArsYpOdAwI5LeoWARNFptDqnHr0JgwAYQYajDicCaCETiSQPKDYFB-NYmKGaSzWWz2ADaCBQAF0XO5PGRcuckq1BNB7pFiah1NlOZd4Z9vus-rlskD6ThGWDypIqjAatAKTBGs1WkDETRkf0QLJWFicVN8bMoAAZBicSRC1ZfAzrDVypkAfhZHlOIuSEBtdoIfGcMH8nDAIBYYCdwfyzEJAfteS1cKVPteXMqEAgQigQbAIbDEajTqqOfYUGYsdUHIzop51ttAj50AFf19Oo+7DJvxrAM0atgKT0CabYN1eRSbuQCrKrKzqvA6v7MB6yDcsEsAEc3AxLMwDaqqlBkzDtfCF4SBacqPq+qijcwxti+LjpgTIgBRAAerlEpKdH4NSpHY9mnZlaFZDUQHoIRohDNN2V8OsQgEX92FEFsoB-P92xQzsOh7KUVyBQoYLoODQTnCoVUHDVZQZGdFXnWilzqFcUwIoRvCAA)

This includes a few other example of odd behavior and attempted fixes

### 💻 Code

Also listed above
```ts
const symb = Symbol();

interface TestSymb {
    (): void;
    readonly [symb]: true;
}

function test(): TestSymb {
    function inner(): void {
    }
    inner[symb] = true as const;
    return inner;
}
```

### 🙁 Actual behavior

```
Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type '() => void'.
  Property '[symb]' does not exist on type '() => void'.(7053)
```

### 🙂 Expected behavior

no errors / proper inference

**Comment by fatcerberus** [comment]
I'm extremely confused as to why TS is okay with `TestProp` but apparently not with `TestNull`.  Literally the only difference between them is the type of `prop`.

**Comment by fatcerberus** [comment]
btw, to the OP for future reference: https://github.com/microsoft/TypeScript/pull/54153

> People keep posting different code in their examples versus in their playground links and it is very confusing.
