### ISSUE TITLE
8K command line restriction when publish typescript from VisualStudio

### ISSUE THREAD

**Issue by EdMaurer** [Microsoft/TypeScript#5423]
I have a typescript project in Visual Studio that compiles and runs well from the IDE. 
When I try to publish it in Azure, VS launches tsc and puts all file names to compile in one command line. I have about 130 .ts files. Having average file length about 85 (full path), my command line exceeds 8K an is being truncated so tsc receives incomplete file set and raises errors. 
To check that the problem is in 8K, I created Subst drive and shorten all paths. Tsc compilation was OK during this test. 

Steps: 
1. Create Typescript Site 
2. Add 100 any .ts files that have 100 characters in name length (full path) 
3. Click Publish To Azure 
Expected: 
All typescript files compiled to JS and uploaded to Azure 
Actual: 
TSC compiler bails out with error different errors, depending on actual file names length. Most popular is "file not found" when you have dependencies between files.

**Comment by DanielRosenwasser** [comment]
We're looking into it, but as a workaround you can create a [`tsconfig.json`](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) with your project, or alternatively make a response file.

**Comment by mhegazy** [comment]
Can you share the project? msbuild should automatically create a response file and pass it to the compiler if the commandline is too long, wounder why this is not happening.

**Comment by paulvanbrenk** [comment]
Actually I just verified it always creates a response file.. I wonder why that doesn't work as expected.

**Comment by paulvanbrenk** [comment]
I created an huge project, but it doesn't exhibit the behavior described in the bug. Without a project that has the issue there is no good way to diagnose this.
