### ISSUE TITLE
Issues initializing TS server in certain JS projects using jsconfig.json "paths"

### ISSUE THREAD

**Issue by rwalle** [microsoft/TypeScript#54231]
# Bug Report

### 🔎 Search Terms

* initializing js/ts language features stuck
* lodash ts watcher

### 🕗 Version & Regression Information

TS Server 5.0.4 used in VSCode 1.78.1

### ⏯ Playground Link

This concerns project setup, so playground does not apply.

minimal reproduction repo at https://github.com/rwalle/ts_bug_example/tree/main, with source code at https://github.com/rwalle/ts_bug_example/blob/main/dev/apps/app1/app.js (1 line)

### 💻 Code

```js
import _ from 'lodash/lodash.min.js';
```

### 🙁 Actual behavior

Symptom: with our setup, when editing JS file in VSCode, the TS service is stuck at "Initializing JS/TS Language Features" forever, and there is a info message that links to [setting max watchers](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc). This should not be applicable, because this is a small project. If I update the import file name to `lodash4.js` and also rename the file, the issue still exists. If I remove `lodash` from jsconfig.json `paths`, the initializing finishes very quickly. If I remove the line of code where lodash is imported, it also works fine.

The setup is like this:
* We do not use the npm system. Project code is under `apps` folder, third-party JS libraries and other JS code outside the same build system are placed under `artifacts/ui/`, and `artifacts/` folder is a huge folder with many non-JS files. All the necessary JS dependencies exist in `artifacts/ui`. The `jsconfig.json` is correctly set up ([minimal example](https://github.com/rwalle/ts_bug_example/blob/main/dev/apps/app1/jsconfig.json)) and works well for other dependencies. We are importing files directly instead of importing a package. (This probably will get more common with things like import map)

Diagnostics:

After enabling the TS Server logging and tracing, I discovered that the server is trying to traverse and watch the folders under `artifacts`, and because `artifacts` folder is huge, it never ends. Relevant part of the log file is below:
```
Info 24   [20:25:17.969] FileWatcher:: Added:: WatchInfo: /home/user/dev/artifacts/ui/lodash/lodash.min.js 500 undefined WatchType: Closed Script info
Info 25   [20:25:18.775] DirectoryWatcher:: Added:: WatchInfo: /usr/share/code/resources/app/extensions/node_modules 1 undefined WatchType: node_modules for closed script infos and package.jsons affecting module specifier cache
Info 26   [20:25:18.800] Elapsed:: 24.543788999319077ms DirectoryWatcher:: Added:: WatchInfo: /usr/share/code/resources/app/extensions/node_modules 1 undefined WatchType: node_modules for closed script infos and package.jsons affecting module specifier cache
Info 27   [20:25:21.345] DirectoryWatcher:: Added:: WatchInfo: /home/user/dev/artifacts 1 undefined Project: /home/user/dev/apps/app1/jsconfig.json WatchType: Failed Lookup Locations
```
In the real project, it gets stuck at 27 for a very long time. You can see that it is trying to look for `node_module` folder, and somehow wanders into the `artifacts` folder as well and tries to add watch for thousands of folders or more. However, if lodash is commented out in `jsconfig.json` or if the import in the JS file is commented out (but still has reference to other libraries), it never goes into `artifacts` folder. It appears that the TS service is looking for something but could not find it, and as a result it tries to go to all known places including parent folder for it. This is strange -- the lodash file is right there on the disk, and there is no need to add any watcher for any folder outside `artifacts/ui/`.

We are able to mitigate the issue by adding `/home/user/dev/artifacts` to `watchOptions` -- `excludeDirectories`. However I don't think this should be necessary, because the `artifacts` folder should never be watched in the first place.

### 🙂 Expected behavior

The TS server should get quickly set up without going into `artifacts` folder.

**Comment by sheetalkamat** [comment]
This seems to work as intended. Because of paths like: https://github.com/rwalle/ts_bug_example/blob/main/dev/apps/app1/jsconfig.json#LL9C16-L9C25  the module resolution will look for resolution from `artifacts` folder and we prefer to watch `artifacts` instead of `artifacts/loadash` simply because we would be watching many sub folders in the `artifacts` folder.

**Comment by rwalle** [comment]
> This seems to work as intended. Because of paths like: https://github.com/rwalle/ts_bug_example/blob/main/dev/apps/app1/jsconfig.json#LL9C16-L9C25 the module resolution will look for resolution from `artifacts` folder and we prefer to watch `artifacts` instead of `artifacts/loadash` simply because we would be watching many sub folders in the `artifacts` folder.

I saw something else recently that might be related: I have two packages `packageA` and `packageB` living under the same folder. The jsconfig.json file is correctly set up for both packages. In some cases I would see automatic import like this

```js
import { fun } from 'packageA/../packageB/module';
```

instead of
```js
import { fun } from 'packageB/module';
```

Not sure what exactly is going on in this case, but I assume you would consider this to be allowed, which justifies the discover process you mentioned?

**Comment by sheetalkamat** [comment]
without a repro for auto import suggestion, it would be hard to tell if its intentional or not. Please provide repro and create separate issue with details to track that. Thanks.

**Comment by rwalle** [comment]
> without a repro for auto import suggestion, it would be hard to tell if its intentional or not. Please provide repro and create separate issue with details to track that. Thanks.

will do.
