### ISSUE TITLE
receiving `undefined` in class with valid code

### ISSUE THREAD

**Issue by hvlxh** [microsoft/TypeScript#54235]
### ⏯ Playground Link
https://www.typescriptlang.org/play?#code/MYGwhgzhAEBC4AtoG8BQ1oDcwgK4FNoBeaAIgEFT1owBlAewFt8AXBASwDsBzALhWgRGbfgAoAlMQB8WeuwAm0AL6pqwepwgsATrmAt62iSmoY27CADo6TVhx7ETGZ4OEJ+5qxFvmep5dQq1AAO2uzYLITezL7cxmgu6pr0IPiWIPRxnpbYePjigahBnPgA7nCIEtYMMfbclkJsEkA

### 🙁 Actual behavior
should print the the value

### 🙂 Expected behavior
but receiving undefined

**Comment by MartinJohns** [comment]
You forgot to fill out the rest of the issue template.

This is working as intended. The `this` value is not bound when storing methods like this. You get the same result in plain JavaScript.

See also: [Why does `this` get orphaned in my instance methods?
](https://github.com/microsoft/TypeScript/wiki/FAQ#why-does-this-get-orphaned-in-my-instance-methods)

**Comment by hvlxh** [comment]
okay thank you for the help!
