### ISSUE TITLE
Minimized files ignored in JS projects using jsconfig.json "path"

### ISSUE THREAD

**Issue by rwalle** [microsoft/TypeScript#54232]
# Bug Report

### 🔎 Search Terms

* safe list
* safelist
* minimized file
* .min.js

### 🕗 Version & Regression Information

TS Server 5.0.4 used in VSCode 1.78.1

### ⏯ Playground Link

N/A -- only reproducible in projects

### 💻 Code

https://github.com/rwalle/ts_bug_example

```js
import _ from 'lodash/lodash.min.js';
```

Our project does not use npm module system. `jsconfig.json` is correctly set up: https://github.com/rwalle/ts_bug_example/blob/main/dev/apps/app1/jsconfig.json. We import from file directly instead of using package name.

### 🙁 Actual behavior

`lodash.min.js` ignored in module import autocompletion suggestion

<img width="598" alt="Screenshot 2023-05-12 200005" src="https://github.com/microsoft/TypeScript/assets/3648011/bde5d484-c22f-45d2-9761-5d43b4424900">

It seems that all these files including certain jQuery files etc are ignored:
https://github.com/microsoft/TypeScript/blob/f0ff97611f2e9c8aff208f4b6520489fe387e9ab/src/server/editorServices.ts#L387
https://github.com/microsoft/TypeScript/blob/f0ff97611f2e9c8aff208f4b6520489fe387e9ab/src/server/editorServices.ts#L4112

I can understand why this is done for "regular" JS projects using npm modules or TS projects with or without `@types`, but this should not be generalized when looking up a file/files in arbitrary JS projects, especially when various options in `compilerOptions` of `jsconfig.json` is meant to specifically address such use cases.

### 🙂 Expected behavior

`lodash.min.js` should show up just like `anotherFile.js`.

**Comment by RyanCavanaugh** [comment]
To be clear, the only bug here is that it doesn't show up in the import auto complete list?

**Comment by rwalle** [comment]
> To be clear, the only bug here is that it doesn't show up in the import auto complete list?

Yes, that is correct

**Comment by rwalle** [comment]
> To be clear, the only bug here is that it doesn't show up in the import auto complete list?

It has been a few days since the last update, I want to follow up and check if this should be tracked as a bug? Thank you.

**Comment by RyanCavanaugh** [comment]
I would call this the intended behavior. We intentionally filter out `.min` files from this list because usually that's not what you want to see, and there are often a bunch of `.min` files and only one correct non-`.min` import. This is the first I've seen where this behavior wasn't desired, so unless this becomes a more common scenario for some reason, I think we'll leave this as-is.
