### ISSUE TITLE
Formatter: comment at end of selection (or document) doesn't get indented

### ISSUE THREAD

**Issue by russelldavis** [microsoft/TypeScript#54243]
# Bug Report
Typescript's formatter doesn't indent comments when they appear at the end of the selection (or at the end of the document when formatting the whole document).

### 🔎 Search Terms
comment indentation

### 🕗 Version & Regression Information
5.0.4 (AFAICT this has always been broken)

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about formatting and indentation

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYMwBAFALgTgrgUwJRgN4CgD0mxQQZyjAGMB7AW3IQDsp0BfdIA)

### 💻 Code

```ts
if (true) {
// test comment
}
```

### 🙁 Actual behavior

Select all of line 2 (the comment), right click and run "Format selection". The line does not get indented.

### 🙂 Expected behavior

The line should get indented (the same way a non-comment line, or a comment line not at the end of the selection, would get indented).

### Additional Info
Another very common way to trigger this bug: in VS Code, with the "Format on Paste" setting enabled, cut or copy a comment line, then paste it into a different block with different indentation. The indentation should be changed to match the new block (like it does if you do this with a non-comment line), but it doesn't because of this bug.

**Comment by officialanurag** [comment]
This kind of behaviour in case of only comment line is expected. When you select the entire code block and format it, the formatter will apply formatting rules to the entire block, including comment. However, when it is applied on a comment, the formatter will only apply the formatting rules that relevant to comments, such as:

1. the maximum line length for comments or whether to use single-line or multi-line comments.
2. how the code is indented which includes any code.

In your case, it seems that the formatter is not applying any comment-specific rules when you select only the comment line for formatting. Instead, it may be relying on the indentation rules to determine how to format the comment. It's possible that the formatter is not designed to format comments alone and requires some surrounding code to determine how to format the comment. 

For example, if you try to format line 2 and 3, it will format it with code applying second rule.

`
if (true) {
// test comment
console.log("Hello");
}
`

In case if you're using Prettier, it is mentioned here: https://prettier.io/docs/en/rationale.html#comment

**Comment by russelldavis** [comment]
No user would expect this behavior, it's definitely a bug. You're right about the cause, I tracked it down and the formatter was only processing comments when the next token was in the range.

It's an easy fix though. In fact, a similar fix was already done at #5983 to deal with whitespace at the end of the range. It just needed to be tweaked to handle comments as well. I have a draft PR at #54250 which fixes it and adds several test cases (It's ready to go, I can submit it once this issue gets triaged.)
