### ISSUE TITLE
TS Playground prints incorrect text for a Set nested within an Object

### ISSUE THREAD

**Issue by zmillman** [microsoft/TypeScript#54257]
# Bug Report

### 🔎 Search Terms

TS Playground set log console

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about printing objects

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-beta#code/MYewdgziA2CmB00QHMAUZYHcAEBlWALqgJTwCGAJhagEQAWs0SAhDccQNwBQokMCSNAG8u2MdggAubBhz4ipStXqMWbLgF9iQA)

### 💻 Code

```ts
console.log(new Set().add("hello!"));
console.log({
    s: new Set().add("hello!")
})
```

### 🙁 Actual behavior

Clicked "Run", then got this result:

```
[LOG]: Set (1) {"hello!"} 
[LOG]: {
  "s": {}
} 
```

### 🙂 Expected behavior

Should print out:

```
[LOG]: Set (1) {"hello!"} 
[LOG]: {s: Set(1)}
```

or maybe something like this:

```
[LOG]: Set (1) {"hello!"} 
[LOG]: {s: Set (1) {"hello!"}}
```

Chrome DevTools shows this:

<img width="281" alt="Screenshot 2023-05-15 at 7 24 01 PM" src="https://github.com/microsoft/TypeScript/assets/1028921/391a62f1-8db7-49ca-9005-28256c8ab3f3">

**Comment by jcalz** [comment]
I wonder if this belongs in [microsoft/TypeScript-Website](https://github.com/microsoft/TypeScript-website/issues) instead of here?  Although given microsoft/TypeScript-Website#2804 I'm not sure if it would be appropriate there either.

**Comment by jakebailey** [comment]
It definitely not for this issue tracker.

Since it's not critical, we wouldn't keep such an issue open, but a PR would be welcome.
