### ISSUE TITLE
TypeScript noEmitHelpers flag

### ISSUE THREAD

**Issue by NexaraDev** [microsoft/TypeScript#54259]
# Suggestion

## ✅ Viability Checklist

My suggestion meets these guidelines:

✅ This would change the runtime behavior of existing JavaScript code

## ⭐ Suggestion
I was writing some sort of code, noticed that whenever I compile my typescript code, it generates some helper functions even though JavaScript has the ability to process the code without the use of helper functions. 

Even I tried to compile with '--noEmitHelpers' flags, but it only removes the helper functions not the usage.

**Comment by MartinJohns** [comment]
You forgot to fill out most of the issue template.

This is working as intended. `--noEmitHelpers` is meant to avoid emitting duplicate helpers when you're including the `tslib` NPM package, which brings these helpers. The helpers are still needed if you target a JavaScript version that does not provide the features you're trying to use.

Most likely you just need to adjust the `target` version.

**Comment by NexaraDev** [comment]
OK. What should be the ```target``` version? I am using node.js ```v18.0.0```.

**Comment by MartinJohns** [comment]
You can find a list of supported features for various runtimes here: https://kangax.github.io/compat-table/es2016plus/

Node 18  supports most of ES2022.

**Comment by NexaraDev** [comment]
At my current node.js version, I should use ES2023?

**Comment by NexaraDev** [comment]
Thanks a lot. It worked with ES2022.
