### ISSUE TITLE
some template function cannot call inside class

### ISSUE THREAD

**Issue by wenxiao** [microsoft/TypeScript#54261]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, including 4.9.5 and 5.0.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMYAUCGAnNBbCwIYDOAPACoB8UAvFKVBAB74IAmhUAFAHQ+YDmhAFxQAlggBmBKCgCU1SmgQgoAfmlRhCCADcCAbgCwAKGNIANmkLsAglADexqFDBwARmZFIoGCCxE+kYABhNDMzMgAaKABpeiYIVnYAawgQAHtxWnIOYH48YVIo8UQkADkcCGFoqJ4ufiFYEvQsXHwiMgBtaIBdcjkHIycnXIw+PA7i5HLcbsNBqABfY0cocQ5+pfnxNbRNOGxXAg3l+bERYHX7FeGACxFCLh8-AODQsxy7wiiAcnFvmT0QyBAHpgbQAMoAJgAzAAWACswmso32CWAUAyUFAkCg3w63W+onYCDS6MshBEfAQaHc0GAaWcmAqbQxmWx0G+8GQzWZBHY3y41yxn0evn8EECITCH3uP223yiAEYAUNQRCYQikSjcAh0Zj2biOoqCUSoCSyVZKdTaViGWAma0pPrwByuagHXg+bjBfNNptjGY8FA0NQzRAAO5QazrOZoUXPCWvaVoOX-QEgsGlADy9AwGDSGGMcae4slbw4Kdx8qVKrV2dz+cLRiAA)

### 💻 Code

```ts
type FuncParameters<T> = T extends (...args: infer P) => any ? P : never;

class A {
  public redirectCall<T, K extends keyof T>(target: T, funcName: K, ...args: FuncParameters<T[K]>) {
    target[funcName];
  }

  f() {}
  ff(a: number) {}

  init() {
    this.redirectCall(this, 'f');       // TS2345: Argument of type '[]' is not assignable to parameter of type 'FuncParameters '.
    this.redirectCall(this, 'ff', 1);   // TS2345: Argument of type '[1]' is not assignable to parameter of type 'FuncParameters '.
  }
}

let a = new A();
a.redirectCall(a, 'f');     // NO error
a.redirectCall(a, 'ff', 1); // NO error
```

### 🙁 Actual behavior

in `init` function of `class A`, we cannot call `this.redirectCall`, but we can call it outside the class.

### 🙂 Expected behavior

No error should occur.

**Comment by RyanCavanaugh** [comment]
Correct. A workaround is to write
```ts
  init(this: A) {
```
