### ISSUE TITLE
Navtree doesn't return computed class members 

### ISSUE THREAD

**Issue by jrieken** [microsoft/TypeScript#54266]
*TS Template added by @mjbvz*

**TypeScript Version**: 4.1

**Search Terms**
- `navtree`
- outline

---

* have the TS file below
* open outline, breadcrumbs, or quick outline
* :bug: the members `[State.WAIT_FOR_INPUT]` and `[State.INIT_UI]` are missing

```ts



const enum State {
	INIT_UI = 'INIT_UI',
	WAIT_FOR_INPUT = 'WAIT_FOR_INPUT',
}

class AAAAA {

    [State.INIT_UI]() {
        return 23;
    }

    [State.WAIT_FOR_INPUT](){
        return 43;
    }

    bbbbb() {
        return 333;
    }
}

```

**Comment by a-tarasyuk** [comment]
https://github.com/microsoft/TypeScript/blob/58f030072ed41e3428c658a83579bdb880ef6886/src/services/navigationBar.ts#L309-L322

**Comment by RyanCavanaugh** [comment]
It seems like it would just be totally fine to include any dotted name or bare identifier in this list. I don't see any downside of doing that, and it would make the code cleaner too.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
