### ISSUE TITLE
TypeScript doesn't check modules using side-effect imports

### ISSUE THREAD

**Issue by AngeloCore** [microsoft/TypeScript#54275]
# Bug Report

### 🔎 Search Terms

TypeScript doesn't check if a side-effect import/bare import is installed
![image](https://github.com/microsoft/TypeScript/assets/62988428/13567979-4b77-472c-994c-288dab602c96)

### 🕗 Version & Regression Information

TypeScript version: `5.0.4`

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgAoEMDGBrFBzApgFQAsUYARCXAZwDsYBRAD2EpgQG4AoUSWOMDbHABmUCCESpMOAsTIUa9JiwRA)

### 💻 Code

```ts
import 'PackageThatDoesntExist';
import react from 'PackageThatDoesntExist'
```

### 🙁 Actual behavior

TypeScripts throws an `Cannot find module 'PackageThatDoesntExist' or its corresponding type declarations.` error when you're trying to use an package that you don't have installed, but doesn't throw one if is an side-effect import.

### 🙂 Expected behavior

It should throw an error just like the default/named/other imports do.

**Comment by fatcerberus** [comment]
Apparently this is intentional but see https://github.com/microsoft/TypeScript/issues/50394 for discussion.
