### ISSUE TITLE
Import module specifier breaks when folder name starts with $

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/TypeScript#54279]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: macOS 13.2.1

Steps to Reproduce:

1. Have a typescript module in an import path that contains a folder starting with $, such as "~/routes/trpc+/$trpc/instance"
2. Try to import that module using the auto complete feature
3. Observe that the import path becomes "~/routes/trpc+/\/instance"

![Screenshot 2023-05-16 at 1 40 11 PM](https://github.com/microsoft/vscode/assets/5280818/acf8bdb5-d4b6-419b-a48f-0189b296e9e4)

![image](https://github.com/microsoft/vscode/assets/5280818/f1b4c5ac-adc1-418f-9808-5c5165f45e50)

**Comment by fatcerberus** [comment]
Looks like a duplicate of https://github.com/microsoft/TypeScript/issues/53290

**Comment by WesleyYue** [comment]
Thanks, that does look like a closely related issue. I tried upgrading to 5.1.0-beta (which should contain [the fix](https://github.com/microsoft/TypeScript/pull/53407)) in my project but it was still showing the same problem. Is it correct to assume that the LSP should be using the typescript version I have installed? Or is it going to be running its own version?

**Comment by fatcerberus** [comment]
It uses a bundled copy by default.  You have to tell it to use your local TS version by clicking the `{}` in the status bar next to “TypeScript”.

**Comment by WesleyYue** [comment]
Great, thanks. Can confirm 5.1.0-beta fixes it.
