### ISSUE TITLE
IntelliSense hangs after Find All References in VS 2022. Solution with many projects. 

### ISSUE THREAD

**Issue by olmobrutall** [microsoft/TypeScript#54277]
# Bug Report

Executing Find All References in a highly referenced project hangs VS IntelliSense, making all the TS language services unusable until VS is restarted. 

### 🔎 Search Terms

Visual Studio 2022, Find All References, Multi-Project

### 🕗 Version & Regression Information

`Microsoft.TypeScript.MSBuild` `5.0.4`

The problem started after a reform that splitted three big projects into 50 smaller ones. 

### ⏯ Playground Link

Unfortunately the issue only appears on solutions on many projects (maybe some O(N^2) algorithm?), so it can not be reproduced with a TypeScript Playground. 

On the other side, the project is OpenSource and hosted in GitHub.  

Steps to reproduce: 
* Clone `https://github.com/signumsoftware/southwind/tree/ts_hang`. I have prepared this branch with all the custom nugets disabled to simplify the problem. The project uses [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules), so from the CLI consider using `git clone --recurse-submodules`.
* Execute `yarn install` in the root folder. 
* Open the .sln in Visual Studio 2022. 
* Compile the Southwind project. It will take some minutes the first time.  
* Open the folder `2.Extensions` in Solution Explorer to see all the projects. 
* Open `Southwind\MainAdmin.tsx` to load the IntelliSense. Southwind is the top project that references everything else. 
* Open `Framework\Signum\React\Reflection.ts` in the editor.  `Signum` is the base project referenced by all the extensions and southwind. 
* In line 498, call Find All References over `getTypeInfo`

### 🙁 Actual behavior

The progress indicator in le botom-left corner hangs forever in one of the extension projects (typically `Signum.Alerts` or `Signum.Authorization`, but could be any...)

![image](https://github.com/microsoft/TypeScript/assets/720953/e51c4fa0-a120-488e-a136-c77afb58c840)

This task can not be cancelled in any way and while in this state, all the TypeScript services are unresponsive. 

The only solution is a VS restart. 

### 🙂 Expected behavior

The task is able to finish or at least is cancelable.

**Comment by goldenauge** [comment]
Same issue here!

**Comment by olmobrutall** [comment]
Looks like this is stale... 

Please some attention... we have to restart VS 2022 a few times every day because of this issue. 
![image](https://github.com/microsoft/TypeScript/assets/720953/fd3f2a5c-9cb2-4845-b83d-132d934b199a)

**Comment by joj** [comment]
@armanio123 maybe you can take a look as part of your current FAR investigation?

@olmobrutall are your projects mostly combined C# and TS, using the TypeScript Nuget?

**Comment by olmobrutall** [comment]
@joj Yes are many C# project (about 40) using TypeScript Nuget in Visual Studio. 

Is the same solution related to this other issue where we also worked together:  https://github.com/microsoft/TypeScript/issues/53795

Unfortunately in this case is not something that can be reproduced with an small new project. 

In the branch `ts_hang` I have removed some custom Nuget that do C# -> TypeScript magic and some IL rewriting to better isolate the problem.

**Comment by olmobrutall** [comment]
I've found that VS Code is much faster on this, but only looks in the current project not in all the solution... maybe an option to enable this in Visual Studio could make sense?

**Comment by mehdy-karimpour** [comment]
I have same issue!

**Comment by rezanos** [comment]
same issue here! so annoying 😩

**Comment by olmobrutall** [comment]
Problem is solved in VS 2022 after installing `Microsoft.TypeScript.MSBuild 5.2.2`.

Now the behaviour is like in VS Code: Project-wide (instead of solution-wide) but very fast. 

Thank a lot!
