### ISSUE TITLE
Set up new perf infrastructure, calibrate numbers

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#54286]
We recently got new machines to run performance numbers on. We will need to

1. Set up the perf infrastructure
2. Make sure they produce reasonable results
3. Backfill at least some amount of data
4. Integrate existing workloads with these machines (per-commit perf runs, and on-demand perf runs)

**Comment by jakebailey** [comment]
This is done; the new perf is set up, it's currently backfilling, and is used for PRs. The infra and stuff will eventually be made public (no reason for it not to be) soon.
