### ISSUE TITLE
Move to file should be returned when on part of a const or function 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#54284]
# Bug Report

### 🔎 Search Terms
- refactor
- refactoring

### 🕗 Version & Regression Information

5.1.0-dev.20230509

### Repo

1. Try running the move to file refactoring by explicitly requesting it when the cursor is on `const` or `function` in:

```ts
const a = 1;
function foo() { }
```

### bug
The move to file refactorings  are not returned in this case. You can only move these by selecting the entire statement: `const a = 1;` or `function foo() { }`

I'd expect:

- When refactorings are automatically requested (by moving the cursor around the file) we do not return these refactorings
- However when the refactorings are manually requested, we should try to expand the current selection the the nearest enclosing symbol and return a move to file refactoring for it (if it can be moved)

**Comment by gabritto** [comment]
This may or may not be the same bug, but I noticed that `Move to file` and `Move to new file` only show up in the list of refactorings if I select the whole statement including the semicolon, e.g. `|const x = 1;|`. If I select everything but miss the semicolon, it doesn't show up, e.g. `|const x = 1|;`
