### ISSUE TITLE
JSDoc virtual comments support

### ISSUE THREAD

**Issue by zeakd** [microsoft/TypeScript#54296]
Hi. Does vscode support "virtual comments" feautre of JSDoc?

when declare something without actual object like,
`@name` https://jsdoc.app/tags-name.html
``` js
/**
 * @name highlightSearchTerm
 * @function
 * @global
 * @param {string} term - The search term to highlight.
 */
eval("window.highlightSearchTerm = function(term) {};")
```

`@namespace` https://jsdoc.app/tags-namespace.html
``` js
/**
 * A namespace.
 * @namespace MyNamespace
 */

/**
 * A function in MyNamespace (MyNamespace.myFunction).
 * @function myFunction
 * @memberof MyNamespace
 */
 ```
 
this is useful when declare global object and dynamic properties

**Comment by XHighIntell** [comment]
I think you can create a d.ts file and put it somewhere in your project.
```d.ts
function highlightSearchTerm(term: string) : void;
```

**Comment by RyanCavanaugh** [comment]
Please file a new issue with the "Suggestion" template. Thanks!
