### ISSUE TITLE
Omit Key extends keyof `any` but should be `T`

### ISSUE THREAD

**Issue by JustJarethB** [microsoft/TypeScript#54303]
## Preamble
The helper type `Omit` is defined in many of the test files as: 
```typescript
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
```
[(evidence)](https://github.com/search?q=%22type+Omit%3CT%2C+K+extends+keyof+T%22+repo%3Amicrosoft%2FTypeScript&type=code&ref=advsearch)

I agree with this definition.

However, as a VS Code user I have often come across a non-report error from the IDE. Upon investigation, I have identified that the file [src/lib/es5.d.ts](https://github.com/microsoft/TypeScript/blob/174599c5542c38ee8f1fc61c9ca6532b68cbb19c/src/lib/es5.d.ts#L1598) as well as [several test files](
https://github.com/search?q=%22type+Omit%3CT%2C+K+extends+keyof+any%22+repo%3Amicrosoft%2FTypeScript&type=code&ref=advsearch) defines the type as 
```typescript
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
```

Where the key diff is

```diff
- K extends keyof any
+ K extends keyof T
``` 
## Expectation Vs Reality
This means no error is thrown for the following example:
```typescript
type Example = {
  foo:string
}

type Omitted = Omit<Example, 'bar'> // fine
```
where the expected functionality would be the error:
```typescript
type Omitted = Omit<Example, 'bar'> // Type '"bar"' does not satisfy the constraint '"foo"'.ts(2344)
```
## Proposition
My proposition, therefore, is to update tests and definition file to match the more strict `keyof T` used in the majority of test files.

 I do not see this causing any issues with previous versions. However, this would report failure in pre-existing bugs/typos. In this scenario, the `Omit` helper would not have been modifying the type correctly, so reporting this would be expected behaviour. Have I missed any reasons why this is not currently `keyof T`?

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template for feature requests or bug reports.

Duplicate of #30825.

**Comment by JustJarethB** [comment]
> You forgot to fill out the issue template for feature requests or bug reports.
> 
> Duplicate of #30825.

Thanks for linking. I was unable to find from my searching, but agree so will close as duplicate. Strangely I wasn't prompted with the template 🤔.
