### ISSUE TITLE
Destructuring intellisense bug in visual studio

### ISSUE THREAD

**Issue by alisabzevari** [Microsoft/TypeScript#5431]
This code gives intellisense error in visual studio 2015 but compiles successfully.

``` typescript
declare var $q: any;
declare var p1: any;
declare var p2: any;
declare var p3: any;


let promises = [p1(), p2(), p3()];

$q.all(promises)
  .then(([p1Result, p2Result, p3Result]) => {
    // ...
  });
```

Errors are:
* On p1Result, p2Result, p3Result: Cannot resolve symbol.
* On ") =>": ) expected

**Comment by mhegazy** [comment]
Do you have any extensions? the message "Cannot resolve symbol" does not sound like anything that TypeScript Language Service generates.

![image](https://cloud.githubusercontent.com/assets/8000722/10795023/09658a7a-7d55-11e5-9e39-b28d2e54edc8.png)

**Comment by alisabzevari** [comment]
@mhegazy  Yes, I use Resharper. But I have disabled it in typescript. I will check with more details.

**Comment by alisabzevari** [comment]
@mhegazy Thanks. It was resharper's problem.

**Comment by mhegazy** [comment]
thanks for getting to the bottom of this
