### ISSUE TITLE
Typescript fails to see props having default values and instead treats it as being undefined.

### ISSUE THREAD

**Issue by hugo-instasense** [microsoft/TypeScript#54323]
# Bug Report

Typescript does not detect props being not null when given a  default value

### 🔎 Search Terms

"React Default props"
"Default props"
"props infered types default"

### 🕗 Version & Regression Information

- This is a crash, I used 4.9.3 and 5.0.4. Code will word, but not compile

### ⏯ Playground Link

[❌ Cleanest example that doesn't work](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoCzAVwDsNgJa46ATVVgQShAE8AKMDjABnAFxwACsJEBKOAG8KcOERjUozfspVwAPK2AA3AHw7duhQHoAVHACScAO4pa8GAAtgIuDAhxaCHgRDwgnOCQoHCgfGysAX3MLfQAtXAAjYCQAUSiAlBAkAF4FfAApJExMfHiTPSs0kEycqLNyZN09RubcqHzCkvwAIQAbYFpWKQgIEbgAMRGIFBheOAqqmojeJBESgAZ4uBQeXYUDuBGkAHNT8-QYRloS-nkikwIFpZgfY4g2GrqDQyWV6bQs9UMph0sgoiUo5BWYCQUhkcCKiiStAKSAkIhgUHGVwANEkkNsRAB+CS0ahNSIk9q6Y4gSnU2npelJS43KkBdmcxkqe6PXkvNHvPEE2hXWEUChoJh4uDsTAoagjGDSCCiNEYwX9HEEfAMixknYSABMJqZJ0t1pU3PEcCtSWFTAkYreBECnkJZHIcIoViscCGOAA1khmKwwswkAAPApgS7yxXwbpZAASHF1ghkEi1ole7yUjLUGi0SQMxhMAGI4NlyRIFEJtSIAHRmnwAajgBwhNehsvhCtoSozSAAKtARP50Xm2wWZMW9Spy5o4Np9dXTPXmU6WzJ2-u4L3zoe28eGEwXvEB1DGTCA3LyKPx8CkAAZa4+eet0RLm2K6lmuSDqBuW7gpCdZwN+NzNv+HaOqefZ3lY0FDs+8JBiGACyKDjHACrgEwUYwBQCaQLAyqVGqGpwDQ9APEwcATr0C4ASiba6iqdGasuq6qGBFablWGH6hYE5wAAtIoiHtlihRwh0KhdB+2YoJMCjtjpiG1PUE4aawYIqWpTRZNOMT+NpukyPpQLmVOM4QCZHRmc0cE+DZ7Z6YCE6ea5+joYOj7DkAA)
- This example is hands down the easiest way
- Cleanest code of all 3
- Least error prone

[✅ Using destructuring, this works but child objects are needed per field assignment](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoCzAVwDsNgJa46ATVVgQShAE8AKMDjABnAFxwACsJEBKOAG8KcOERjUozfspVwAPK2AA3AHw7duhQHoAVHACScAO4pa8GAAtgIuDAhxaCHgRDwgnOCQoHCgfGysAX3MLfQAtXAAjYCQAESQRGChqDA0kVmkIUQCUECQAXgV8ACkkTEx8eJM9KzSQTJy8gqL1IjKZM3Jk3T0evtz8wuKR8sraarqGgCEAG2BaVikICC24ADEtiBQYXjhm1vaI3jz6gAZ4uBQeERe3raQAcy+Cle7wYTHq-HktRMBDOFxgPg+EDY7U63QyWTmg0WpWWInGFi6hlMOlkFESlHIVzASCkMjgtUUSVWNQk812fwANEkkI8RAB+CS0ai9SJcia6D4gfmC4XpUVJX4AgUBWXy8UqdAwRi0ZUQ+nQtm0P5kigUKxWOAbHAAayQzFYYWYSAAHtUwL8KGgmPk4DMsgAJDj0uCCGQSBQ8vIykVQeKQ6FKcVqDRaJIGYwmADEcAAorzw0IKiIAHSRnwAajgr0JGZJJopXtoPr9SAAKtARP4GaGi+HJeIVTGOSCtUwJHqoXBDX84-rGUmkMNU+r9ESs+9PgWZMX+3BK8CFIXRDvQbQIfEa8TxaTyOTPd74C2ADL-Hzdo8DhSKgdCmOzyeJioyaaCGaZrtmL4AluRbFt+e5VheVhrnWt6mhS5pwAAsiguxwF64BMHaMAUC6kCwHA7CYCg1BbFgdCnr66L9PMQwlKMRb8AozJIMOZbBgATMOu4MoJcBwSJQkMd28YEIEnjsu0Ei4vIgGqIuKagSu6ZXpMKgtnAAC0ijceSumpExgYoPsZb1GWHRdC2lmsPiunTEx7YxP4-b1P2byatqPmnvZaK9FkHmdi5kxuaFSCQT4371N+wXPq+kX6EhtbXvWQA)
- This is the best working example
- Issue is having to list every field individually, later leads to field bloom, harder to read then

[✅ Using custom type, this also works but DefaultProps type requires manual field adding](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoCzAVwDsNgJa46ATVVgQShAE8AKMDjABnAFxwACsJEBKOAG8KcOERjUozfspVwAPK2AA3AHw7duvQC1cAI2BIAkrRhJNKADbSIouLRQgSAC8CvgAUkiYmPgAviZ6APQ2IPZOLm7+XjJm5BYW1nYOzq7uWT4ifgHBoQBCHsC0rFIQEB5wAGIeECgwvHARUbFwSLxIIiEADDFwKDzjClNwHkgA5vOL6DCMtCH88kEmBJ3dMBWzEGyx8UmFaSWZ3qI5+QmGpjqyFDEUP+S9YEg4AARSIoageGCPCpBRBIACO1GARFYekkwDQAGtUTIADQEEZjfBwAA+BFmIBERNJ+GWaypZIYTHwJhMAG4KP9AcUMp4oXAYXyAGTA0HgyEyX6cqQyfmKcyVQISEQwKANFY4+UEkQAfgktGoKTcGtyunJOr1BtsRvltPNfkt1pNKk2211cD2-MOytVtBWX1+aCYyrg7EwYIhUIkILDYr5MKUTuGo3EcAATMaLGaJOmbasUznEy6mBIPQcCLQIDAABZqsjkb6UcgJBJwGo4DFIZisCAAd2YSAAHgEwMsKIHaMHkqkABIcWWCGQSbmlKH7Q4JlRqDRaeUGYwmADEcAAosmJAohOUAHRauAAajgU0Sb2ecE+9YDQfgU4cABVoCIEDzpeohLukK4yGucomlumjuruL5HlmiggSIV5mvej7TBeMjoYytB7DEz77h8-qNuOk63AAMnmwGLnAy4PJBnrQZuSDqHB2iJnuphHjRaznqhV62phT6vCRJrvg2vzNnAACyKANHAgbgEwnYwBQg6QLAIaihCcA0PQWxMHAP53DyZSiAu5QSKurHKV+cANPcvL0YxrnlLKChXj5obhuK5R4j5V6odJMHsdu8HcS+8oWGZcAALSKM5FlQle-iBA2eSWGZs4oE03k+SlEHlHEiS5Rwr7ZQUKR-gBQGFVexVMaV1xmf+UCAVVeQ1ak-EVI1zUeaIZU3LVSD9d1xHvJJZFAA)
- This is error prone when adding new optional props because of type picking
- Least maintainable over the long term
- Adds non-standard complexity to a project

### 💻 Code

```ts
function undeadArmy(props: Props) {
  return (
    <div>
        <ZombieErr name={'Jeff'}></ZombieErr>
        <ZombieErr name={'Blind Pool Floaty Jeff'} eyes={0} arms={0} legs={0} action={() => 'Floats around'}></ZombieErr>
    </div>
  )
}

type Props = {
    name: string,
    eyes?: number,
    arms?: number,
    legs?: number,
    action?: () => string
}

const defaultProps = {
    name: '',
    eyes: 2,
    arms: 2,
    legs: 2,
    action: () => 'nothing'
}

// All these props.value show undefined ❌
const ZombieHead = (props: Props) => { return <div># Eyes: {props.eyes + 0}</div> }
const ZombieTorso = (props: Props) => { return <div># arms: {props.arms + 0} {props.action()}</div> }
const ZombieLegs = (props: Props) => { return <div># Legs: {props.legs + 0}</div> }

export default function ZombieErr(props: Props = defaultProps) {
  return (
    <div>
        Zombie - {props.name}
        <ZombieHead {...props}></ZombieHead>
        <ZombieTorso {...props}></ZombieTorso>
        <ZombieLegs {...props}></ZombieLegs>
    </div>
  )
}

```

### 🙁 Actual behavior

props.eyes, props.arms and props.legs has a default value but this won't compile (see other playground examples).

### 🙂 Expected behavior

Similar to how `if(props.eyes) { props.eyes + 0 }` works, if you assign a default value with all the fields, Typescript should detect optional values as not having values.

**Comment by MartinJohns** [comment]
The compiler is correct.

First, within the `ZombieHead` and other functions the compiler can't know anything about your default value in `ZombieErr`, and the properties like `eyes` **are** optional.

Second, the default value only is used if `props` is not passed at all. But it's still valid to pass an explicit props object where the properties like `eyes` are set to undefined: `ZombieErr({ name: '', eyes: undefined })`

**Comment by hugo-instasense** [comment]
Ah, made the mistake of destructing in my mind. Spoke with a colleague, his solution is the best. For anyone wondering, allows you to specify require fields which is less common that optionals, and doesn't have custom type.

Here is the [playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoCzAVwDsNgJa46ATVVgQShAE8AKMDjABnAFxwACsJEBKOAG8KcOERjUozfspVwAPK2AA3AHw7duhQHoAVHACScAO4pa8GAAtgIuDAhxaCHgRDwgnOCQoHCgfGysAX3MLfQAtXAAjYCQAUSiAlBAkAF4FfHx4kz0rNJBMnKizcmTdPRq63Kh8wpL8ACEAG2BaVikICH64ADF+iBQYXjgAKSRMTHKI3iQREoAGeLgUHm2FPbh+pABzY9P0GEZaEv55IpMCadmYH0OINnLK6oyWQ6jQsVUMph0sgoiUo5HmYCQUhkcCKiiStAKSAkIhgUCGFwANEkkJtxAFqLVIkSmrpDiAybQKekqUlzlcJIzKVBqRZbvcJPw4E8Ua8cXjaBc4FDyDCKGgmDi4OxMChqP0YNIIKIJJrRCi0TSVBjChIyjzdCSthIAEzmlR0sm21mXR12g4MJgC56vfCBTz4sgyigUKxWOC9HAAayQzFYYWYSAAHgUwOc5Qr4G0sgAJDj6wQyHUyb0GlRqDRaJIGYwmADEcGypIkCiEWpEADpLT4ANRwPZgmuQ6HB8jy2iKrNIAAq0BE-lRBbbRbbJaUNPLmiFVfBdYOR2brdE7YdcF7pxbMmPHtoT3iA4hNOlstHGbgk4AMi784eybq5CLS1UJB1E3bRDX0Hd60-dlFB-ds2R7Ps7ysHchyDWEQzDeFEQAERWVV1T-fVkAAR2oYAiFYPRJGANBI2omQCQILt8DgAAfAgHVYjj8AQ7jOOvfATBMABuTC4AAWRQIY4HlcAmBjGAKCTSBYCVfC1SwOhrzfQF6igfgAH0fx1Q47hQfoGLbV4ADIpFo+i-yY31MSE+Q1xUMdFRMpE231BQ4HbILlQIjVGMCoLjORZ8y2Aist3A6sH2aFRJzgABaWDL2NJAYRS1I9NzFARgUIL2x-CoqknIrWBBFLWj0mcYn8Uqgoq-5Jyauc6uaBraiyaCfFa8qZEqgF+qQQaev0FDB0fYdyCAA)

**Comment by MartinJohns** [comment]
Just be aware that, unless you have `exactOptionalPropertyTypes` enabled, with `Partial<Props>` you can still explicitly provide `undefined` values for the properties, which will overwrite your `defaultProps` properties by spreading:

```ZombieErr({ name: '', action: undefined })```

**Comment by hugo-instasense** [comment]
Oh wow, thanks for heads up. Enabled it, thanks!

For reference if anyone finds this issue, you needs to add the following to your `tsconfig.json`:
```JSON
{
  "compilerOptions": {
    "exactOptionalPropertyTypes": true,
  }
}
```
