### ISSUE TITLE
Autobind this

### ISSUE THREAD

**Issue by sqrtroot** [Microsoft/TypeScript#5432]
Hi guys,
I'm using typescript in combination with react and react hotloading.
unfortunately hot reloading doesn't work with arrow functions but i need the this content for setting state. 
Is there a way to use normal prototype functions and let them be automaticly be bound to this. (a.k.a not need to write ```this.function = this.function.bind(this)``` in the constructor for every function?
See https://github.com/gaearon/react-hot-loader/issues/209 for more details on the problem

**Comment by kitsonk** [comment]
That would break so many things... Once something is bound, it is bound and cannot be rebound and breaks any `fn.call` and `fn.apply`.  How would you suggest that this work for people who wouldn't want this feature?

**Comment by RyanCavanaugh** [comment]
We don't intend to meaningfully change the class emit at this point -- its semantics are as close to ES6 as we can get.

The example you linked to is confusing; the two classes you posted are not the same (is `tick` supposed to be the same as `count` ?). If you could boil this down to a meaningful small example we could try out locally, we might be able to brainstorm some better solutions.
