### ISSUE TITLE
console.trace definition is invalid in /lib/lib.dom.d.ts

### ISSUE THREAD

**Issue by wallride** [Microsoft/TypeScript#5433]
`console.trace(a,b,c,1,2,3)` emits compilation error:

> error TS2346: Supplied parameters do not match any signature of call target.

So, let's open the declaraion in /lib/lib.dom.d.ts:
```javascript
interface Console {
    log(message?: any, ...optionalParams: any[]): void;
//  ......................
    trace(): void;
}
```
arguments should be the same as in `log(message?: any, ...optionalParams: any[])`

**Comment by mhegazy** [comment]
@wallride for now you can reopen the interface locally and define the missing signature as such:

```ts
interface Console {
    trace(...args: any[]): void;
}
```

**Comment by wallride** [comment]
@mhegazy, thanks for your reply! It was the first thing i've done. :) But transpiling via gulp-typescript still throws warnings. Though i've fixed every interface i could find.
Anyway, i supposed this issue would be useful for the typescript project.

**Comment by mhegazy** [comment]
just out of curiosity, what are the errors you were getting from gulp?

**Comment by wallride** [comment]
@mhegazy , oh just the same as i've written above.
Although i've optioned gulp-typescript to use TS from require('typescript'). And i've searched-and-replaced  every d.ts file around typescript modules. Have no idea why it's still not satisfied. but errors don't block building process. so i move on.

**Comment by mhegazy** [comment]
but you do not need to replace the definition in lib.d.ts, you can just augment it. so in one of your files, just add the new definition.. here is what i mean in the playground: http://www.typescriptlang.org/Playground#src=interface%20Console%20%7B%0D%0A%20%20%20%20trace(...args%3A%20any%5B%5D)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Aconsole.trace(%22message%22)%3B%20%2F%2F%20OK%0D%0A

**Comment by wallride** [comment]
@mhegazy Yes, that is a some kind of solution. Thanks!
And declaration in lib.d.ts should be fixed anyway, i suppose :)

**Comment by mhegazy** [comment]
yup. the bug is open, should be fixed in TS1.8, but until then, no need to keep getting errors in your compilation.

**Comment by mhegazy** [comment]
PRs are welcomed. here is some documentation for adding new types to lib.d.ts: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes
