### ISSUE TITLE
TS 5.1.1-rc: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by belgattitude** [microsoft/TypeScript#54348]
# Bug Report

Tried an upgrade to 5.1.1-rc from 5.0.4 and got a `RangeError: Maximum call stack size exceeded` for one of the app of the monorepo (nextjs, mui, i18next,...). Others apps and packages works. 

You'll find a reproduction here: https://github.com/belgattitude/nextjs-monorepo-example/pull/3826 with explanation.

```bash
git clone https://github.com/belgattitude/nextjs-monorepo-example.git --branch typescript-5.1.1-rc 
yarn install
cd apps/nextjs-app
yarn typecheck
```

Note that this repo uses yarn 4.0.0-rc.44 with node_modules linker.The cause might be linked to that as well. But in general this example repo used to work across ts updates quite well.

The error is visible on the CI https://github.com/belgattitude/nextjs-monorepo-example/actions/runs/5049578076/jobs/9059197251?pr=3826 and reproduced locally on linux / node 18.16

Just wanted to let you know, didn't had time to investigate. 

Huge thx for ts team, I really appreciate what you're doing :heart: 

### 🔎 Search Terms

```
RangeError: Maximum call stack size exceeded
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63011:28)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)
    at inferFromTypes (/home/sebastien/github/nextjs-monorepo-example/node_modules/typescript/lib/tsc.js:63018:9)

```

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.0.4 and 5.1.1-rc

### ⏯ Playground Link

https://github.com/belgattitude/nextjs-monorepo-example/pull/3826 with explanation.

```bash
git clone https://github.com/belgattitude/nextjs-monorepo-example.git --branch typescript-5.1.1-rc 
yarn install
cd apps/nextjs-app
yarn typecheck
```

**Comment by jakebailey** [comment]
This bisects to #53365, but reverting it doesn't actually fix the problem and it doesn't really make sense anyway. Really strange.

**Comment by jakebailey** [comment]
Ah, I see what's wrong here.

**Comment by jakebailey** [comment]
Apparently, no, what I thought was wrong was not wrong. I can only think that there's some form of corruption happening here. Except that now, I can't get this to break on main. Doing a bisect then says that we somehow fixed it on main in #54125, which is totally ridiculous.

**Comment by belgattitude** [comment]
Thank you for looking @jakebailey ... let me know if I can be of any "modest" help.

**Comment by capaj** [comment]
same here on 5.1.3 and even 5.0.4. Applying the fix from @jakebailey fixes the issue.

**Comment by belgattitude** [comment]
@jakebailey if it helps I've upgraded to ts 5.1.3 and still have the same issue
https://github.com/belgattitude/nextjs-monorepo-example/pull/3888

**Comment by chriskuech** [comment]
This is also an issue with nestjs, which uses parameter decorators extensively.

**Comment by jakebailey** [comment]
This was really weird, but I figured it out. The code added in #53246 directly checks the object flags of the type. When this code executes, `CouldContainTypeVariables` is not computed, so it proceeds to check `couldContainTypeVariables` for the type arguments. But, this may be recursive; the current type may actually have its objectFlags updated in the process of calling `couldContainTypeVariables`. If that calculation actually said "false", then this new code wrote over the old value with a new one, causing this problem.

I'm looking into a proper fix now.

**Comment by chriskuech** [comment]
I noticed in [the release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html) that decorators require disabling the previous compiler flags. Should the compiler at least warn that those config settings are enabled if its related to this issue?

**Comment by jakebailey** [comment]
This issue is not at all reserved to decorators; I have multiple test cases which exhibit this bug which do not involve decorators. This is just a bug that will be fixed and very likely backported to the next patch release of 5.1.

**Comment by Toinouze** [comment]
Any temporary workaround for this issue ?

**Comment by jakebailey** [comment]
You could use the build on my PR: https://github.com/microsoft/TypeScript/pull/54507#issuecomment-1574445489

Or, just downgrade back to 5.0... 5.1's only been out for a couple of days.
