### ISSUE TITLE
NodeListOf, TS2488 -- `for of` method that returns an iterator

### ISSUE THREAD

**Issue by asottile** [microsoft/TypeScript#54351]
# Bug Report

### 🔎 Search Terms

NodeListOf TS2488

I found #2695 which claims that this is fixed but it looks like it wasn't fixed for `NodeListOf`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _some things_ (I read the titles but none of them seemed relevant)
- I was unable to test this on prior versions because _I am lazy_

### ⏯ Playground Link

unfortunately I can't reproduce this in the playground because it does not have a setting for dom.

### 💻 Code

here's a reproduction instead inline:

#### tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "lib": ["dom", "es2020"],
    "downlevelIteration": true
  },
  "exclude": ["node_modules"],
  "include": ["t.ts"]
}
```

#### t.ts

```ts
function f(els: NodeListOf<HTMLDialogElement>) {
    for (const el of els) {
        console.log(el);
    }
}

f(document.querySelectorAll('dialog'));
```

#### package.json

```json
{
  "dependencies": {
    "typescript": "^5.0.4"
  }
}
```

### 🙁 Actual behavior

```console
$ ./node_modules/.bin/tsc
t.ts:2:22 - error TS2488: Type 'NodeListOf<HTMLDialogElement>' must have a '[Symbol.iterator]()' method that returns an iterator.

2     for (const el of els) {
                       ~~~


Found 1 error in t.ts:2
````

### 🙂 Expected behavior

(no errors)

**Comment by MartinJohns** [comment]
You're missing the lib `dom.iterable`.

**Comment by asottile** [comment]
ah then perhaps the diagnostic should be improved, or it should get pulled in by default with dom?
