### ISSUE TITLE
Cannot overload interface method with different return types

### ISSUE THREAD

**Issue by enisdenjo** [microsoft/TypeScript#54354]
# Bug Report

Defining an overloaded method in an interface raises an error during implementation if overloads have different return types.

### 🔎 Search Terms

`overload`, `method`, `interface`, `factory function`

### 🕗 Version & Regression Information

Doesn't work in v3, v4 or v5.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4&ssl=4&ssc=2&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgMoAs4AcUG8BQyycUEcAFAB4BcyIArgLYBG0AlLQy9ANyHGkKNOk1ZQANMgCenUe1oBnMFFABzPgF98+BABs4ChWkw4Akoyy7kwC7oiMI4Ixmx5+JMuQD6wrmMleUgD8stxQHCJhyAA+yEoqIKrIBEREpGD0UCDIAAx8RFpa+DD0IAhgwAD22QiCkC445BENbmkQGVnJ-EQeFD6h-siBIZFiEX7QMXHKal2pqemZ2XndyBri-Bqa+EA)

### 💻 Code

```ts
interface Shape {
  area(x: number): number;
  area(x: number, y: number): string;
}
```

### 🙁 Actual behavior

```ts
class ShapeImpl implements Shape {
  // ❌
  area(_x: number, _y?: number): number | string {
    return 0;
  }
}

function createShape(): Shape {
  return {
    // ❌
    area(_x: number, _y?: number): number | string {
      return 0;
    },
  };
}
```

### 🙂 Expected behavior

```ts
class ShapeImpl implements Shape {
    // ✅
  area(_x: number, _y?: number): number | string {
    return 0;
  }
}

function createShape(): Shape {
  return {
    // ✅
    area(_x: number, _y?: number): number | string {
      return 0;
    },
  };
}
```

### More details

If the return type does not change, overloads work as expected.

✅
```ts
interface Shape {
  area(x: number): number;
  area(x: number, y: number): number; // 👈
}

class ShapeImpl implements Shape {
  area(_x: number, _y?: number): number {
    return 0;
  }
}

function createShape(): Shape {
  return {
    area(_x: number, _y?: number): number {
      return 0;
    },
  };
}
```

Also works if the overloads are defined in the class or on root level functions

✅
```ts
class Shape {
  area(x: number): number;
  area(x: number, y: number): string;
  area(_x: number, _y?: number): number | string {
    return 0;
  }
}

function area(x: number): number;
function area(x: number, y: number): string;
function area(_x: number, _y?: number): number | string {
  return 0;
}
```

**Comment by jcalz** [comment]
Essentially #47669 (focuses on arrow functions but it’s the same issue: we currently have no way to say “check this the same loose way that overload implementation are checked”)

**Comment by RyanCavanaugh** [comment]
These are just correct errors; the function provided *doesn't* match the overloads you wrote and a valid call could result in an unsound result.

**Comment by enisdenjo** [comment]
> These are just correct errors; the function provided doesn't match the overloads you wrote and a valid call could result in an unsound result.

Hmm, but how doesn't it match? Also, why do the inline overflows work then?

**Comment by enisdenjo** [comment]
Basically this:

```ts
interface Shape {
  area(x: number): number;
  area(x: number, y: number): string;
}

function createShape(): Shape {
  return {
    area(_x: number, _y?: number): number | string {
      return 0;
    },
  };
}

const num: number = createShape().area(3);
const str: string = createShape().area(3, 3);
```

**Comment by enisdenjo** [comment]
@RyanCavanaugh I don't want to be a nuisance, I just want to understand - can you please explain https://github.com/microsoft/TypeScript/issues/54354#issuecomment-1559663754? Thanks in advance!

**Comment by RyanCavanaugh** [comment]
I don't understand the question. You're basically saying that if you an `implements` clause, then your methods you write should not have the types that you wrote on them?

**Comment by fatcerberus** [comment]
@enisdenjo I think I understand what Ryan is getting at - currently, `implements` is merely a hint to the compiler to check that the class is a valid implementation of the type, but doesn’t change the type at all.  Under your proposal the single `area` signature would become an overload implementation and thus the presence of `implements` theoretically changes the type (by hiding that signature from callers).

@RyanCavanaugh The above being said, I don’t think that’s necessarily true - I’m envisioning that if you call the method directly through a `ShapeImpl` instance, you’d get the declared signature (*with or without* the `implements` clause), while if you call it through the interface you get the overloads.  So I thus read this is just a request to make the `implements` check more loose in considering `ShapeImpl` a valid implementation.  Which makes sense to me since overloads only ever get one implementation anyway.

**Comment by enisdenjo** [comment]
> You're basically saying that if you an implements clause, then your methods you write should not have the types that you wrote on them?

No, I am saying they should. This also doesn't work:

```ts
interface Shape {
  area(x: number): number;
  area(x: number, y: number): string;
  area(_x: number, _y?: number): number | string;
}
class ShapeImpl implements Shape {
  area(_x: number, _y?: number): number | string {
    return 0;
  }
}
const num: number = (new ShapeImpl()).area(3);
const str: string = (new ShapeImpl()).area(3, 3);
```
[_^ playground link_](https://www.typescriptlang.org/play?ts=5.0.4#code/JYOwLgpgTgZghgYwgAgMoAs4AcUG8BQyycUEcAFAB4BcyIArgLYBG0AlLQy9ANyHGkKNOk1ZQANMgCenUe1oBnMFFABzPkRJlyAfWFcxknVID8s7lA4iLyAD7IlKkOvwBffAgA2cBQrSYcAElGLE9kYBDPCEYIcD8MbDx+LQo9c0NkYzNrMSsDaDsHZTVkAiIiUjB6KBBkAAYNZHd3BAB7ECVrdIKAXmRyEAgAd39E4NDyNjYAOhTyAGY2PjaOsCKoRWLnZD6B4dGgyMmZufnJRb4gA)

Why are overloads different when defined in interfaces compared to directly on functions/methods?

**Comment by RyanCavanaugh** [comment]
`implements` clauses don't change the shape of your class; this fact is intentional. IOW, for these two snippets
```ts
class ShapeImpl implements Shape {
  area(_x: number, _y?: number): number | string {
    return 0;
  }
}
```
and
```ts
class ShapeImpl {
  area(_x: number, _y?: number): number | string {
    return 0;
  }
}
```
`ShapeImpl.area` has the same type in both.

**Comment by fatcerberus** [comment]
@RyanCavanaugh I’d probably just expect that assignment to succeed.

**Comment by RyanCavanaugh** [comment]
Are you just saying that any signature which roughly matches an overload list should be assignable to it? Or that classes with `implements` lists would allow extra stuff that wouldn't normally be allowed to happen?
