### ISSUE TITLE
Could add "automatic brace completion" to VS2015

### ISSUE THREAD

**Issue by jimior2** [Microsoft/TypeScript#5435]
Could add "automatic brace completion" to VS2015 like Visual Studio Code did.
![image](https://cloud.githubusercontent.com/assets/654999/10794375/9802fbee-7dcf-11e5-819b-8720c6f9c32d.png)

![image](https://cloud.githubusercontent.com/assets/654999/10794429/cbbd7fc2-7dcf-11e5-9af1-6e61d9629956.png)

**Comment by mhegazy** [comment]
This is not currently supported but it is on our list of features to add. the work is tracked by #1484.

**Comment by jimior2** [comment]
@mhegazy Thanks.
