### ISSUE TITLE
Require that sub-classes include default params when overriding concrete functions

### ISSUE THREAD

**Issue by boconnell** [microsoft/TypeScript#54365]
# Suggestion

I almost introduced a bug today due to the following code:

```ts
class Parent {
    foo(baz = false) {
        this.bar(baz);
    }

    bar(baz = false) {
        console.log(baz)
    }
}

class Child extends Parent {
    foo(baz = false) {
        // some extra logic
        return super.foo(baz)
    }

    bar() { // this should fail to compile because bar is an override and is missing the optional param
        // some extra logic
        return super.bar();
    }
}

const x = new Child();
x.bar(true); // fails because extra param
```

I think `Child` should fail to compile because `Child.bar` does not contain an optional param. Otherwise, `Parent`'s `this.bar(baz)` call seems unsafe because it includes a parameter that a sub-class can ignore.

Additionally, this seems like the concrete mirror of the follow abstract setup, which rightly fails to compile:
```ts
abstract class Parent {
    foo(baz = false) {
        this.bar(baz);
    }

    abstract bar(baz?: boolean): void;
}

class Child extends Parent {
    foo(baz = false) {
        return super.foo(baz)
    }

    bar() { // fails
        console.log();
    }
}
```

Here, `Child.bar` rightly fails to compile for not accepting an optional parameter. This feels like an inconsistency?

## 🔍 Search Terms

sub-class sub class override default param parameter fail

## ✅ Viability Checklist

This would be a breaking change, but otherwise this seems to be an inconsistency at best and dangerous at worst.

**Comment by fatcerberus** [comment]
This is by design on the basis that omitting the parameter is the same as actually including it and then ignoring it at runtime.  See https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters

Enforcing this would mean you’d always have to include all parameters in callbacks even if you don’t use them (the `index` param of an `arr.map()`, for instance).

I don’t know why the `abstract` case has different behavior, though.

**Comment by whzx5byb** [comment]
> Here, Child.bar rightly fails to compile for not accepting an optional parameter.

But I don't see any error [here](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgCsKBTAdogN4BQC5CAZgPbUAUIwAXggLxXDJi4CUCpFQQggALAJZgAdIygNmPANxkKAXxLLyoSDHgIZcpgH4AXHtrJcwfD1MA3amIAmStSRRoMAYXHJHCXAAeEASOGNh4hPwaVLQGbBxcvFFCFHgQAK5Q+Ahg6QAOuFCSNPSMTDzRroL6fEQIAPT1HGJc0YKw1Phg1BaSyNQA5nSKlSQqQA).

**Comment by boconnell** [comment]
@whzx5byb well there goes half my argument - good catch.

I've known about https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-with-fewer-parameters-assignable-to-functions-that-take-more-parameters but didn't make the connection here

**Comment by fatcerberus** [comment]
@boconnell Yeah, method overrides are checked in terms of “is this function assignable to the one in the base class?” so the same argument applies as in that FAQ entry.
