### ISSUE TITLE
keyof inside a generic is treated as purely contravariant, but should ignore values and Partial<>

### ISSUE THREAD

**Issue by matthewvalentine** [microsoft/TypeScript#54364]
# Bug Report

### 🔎 Search Terms

keyof variance contravariant partial generic

### 🕗 Version & Regression Information

- This changed between versions 3.3.3333 and 3.5.1, and also between versions 4.1.5 and 4.2.3.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBAYg9nKBeKAlCBjOAnAJgHgHIAzBQgGigDsBXAWwCMJsA+AbgChRJYEAhAIbZkaTDgIkyUAD5RCDIRWr0mrTh2I0qGYAEs4VKLoDOAQWPHdAcyoCGAGwj4AKkKsRglAGoD7NaBAAHsAQVLjGUK7Y7sAsABQAlFAA3gC+bFAA9JlQAG6+urhGxFAABlhUxsBQwG4eAFyRddUo+X7QAhE+7aVQAO5wNPZFA9gA1hwc2VBjECBwJdZUOBARAApCer74LJQCYUYRcMAAFsx9JtAVwNgC+di6+8AAdJEnAsCEEVjY2JgvHBM5ksNjsjnwySggUas3mJQ22C29nw8DgglYUFSlEh0JmcwWvEQqXiCQy0zgEymOT4NGquhK8xoNWwIBqiFwiFO0GMAjo0AupygAmovIgRW4EEoXKgTHeuX0whMUFw9OIzFCAOmcQAqpYqFYygBZEDOcBOZwsESwgnOXoqv46eys94RZZQMDYOAOCB0YyUXTVKgQMURYCIJhC6qOTrVG66eW+J39W5gSBFTpGOkRM5-Z4JLhmqDG02QFyWlA4mH4krOTHqaYAZRoGAwwfCRkMAGZnt3O33u1TYAJdPYIrpDPYPsw8sxLAYIgKTmUS9BCAikSj+EIWIRDtRjkKLEswdAwzVC4RUYRnqVAWYj6Dvfhi2b8OvHsjUeiWLsiybX6iP6JPWOQAPJcsI9yPHo879DgYzPHewLHk+L6ll+26UGhTiASSZI5BSSEPrYqH-uhW6sFhZFOO+2y4XhWQERMQLESez7UW+mwfpuaLbr+2GcYi3H0cBjFQIRg6mFAlh0COQjup63p0EKDzGKsxRQIywgSlALrKqq6pUNUbT+H6UAQLkoQaQGukZtKPJ8niIDGIhOkYdgDY3CI6A-BIpBwLusjyIolBVA8+rsJMLEgiR4KVk5BLuZi2JQlWcKEuinnCMSwGTNMphWMOVBSicSrGM2rYhh2UC9j2-aUAwtJQMQw6jtVk4hJBs76JUiHRSh4ICe5-Ece5WVAaSeU5M4pUREwWB8hEwp0Cs0nMPoNARB6XqOMp80CJt0A+eI+BheOViUM8V2WmVkAYB+AC0GCdGKewHAIOhLVA9gBsAjgyjZP2zFAtHIsdeCnXG+qXddLAFjwpj2PYADScwRCg4MEGd0PKIwzCRYOTYtm2Y6GAALM8ACMzwAKyIdMMCtaT31Tl12BzpU-QBkupRrJ6kCIqykgBXuslHvq1U6YQiMo2ju6NdUfwAI40LofxFOO548JeZA3kRMVsQJMuo85I0rjxE0gVAADqoGoMjpioKB2oAHIACKDgAkgygwdjccC4M20ClNaNa9BmwpqWAQhTlA7hBg8GDujHfKdSVVmnOdC7wVAK1-Ie5mBHdIS4K5hbGtb8FCIMYQuJQyOFyEYQRKHkRWtWkTlikqVQA36RRfeBukZX4zV1oBCgzx34jSPYxj7XuGieSExAA)

### 💻 Code

```ts
type Foo = Record<'foo', number>;
type FooBar = Record<'foo' | 'bar', number>;

function isAssignable<Target, Value extends Target>() {}; // valid if `const target: Target = value as Value` would work

// keyof ignores Partial<>, and is otherwise contravariant. That's correct.
isAssignable<{ x: keyof Partial<FooBar> }, { x: keyof Foo }>(); // ok

// But if you try to do the same with a named type, the behavior is different.
// (Using `MyType<T> = keyof T` directly has no problems, it needs to be at least trivially wrapped as it is here.)
type MyType<T> = { x: keyof T };

// Succeeds in 3.3.3333.
// Fails in later versions with `Type 'Partial<FooBar>' is not assignable to type 'Foo'.`
isAssignable<MyType<Partial<FooBar>>, MyType<Foo>>();

// Other variations work.
isAssignable<MyType<FooBar>, MyType<Foo>>(); // ok
isAssignable<MyType<FooBar>, MyType<Partial<Foo>>>(); // ok
isAssignable<MyType<Partial<FooBar>>, MyType<Partial<Foo>>>(); // ok

// A similar problem arises if your type has different values, even if it has the same keys.
type FooBarStr = Record<'foo' | 'bar', string>;

isAssignable<{ x: keyof FooBar }, { x: keyof FooBarStr }>();

// Again, this succeeds in 3.3.3333, but fails in later versions.
isAssignable<MyType<FooBar>, MyType<FooBarStr>>();

// This becomes a more serious problem because Record<string, ...> is special-cased, and acts a little bit like Partial<Record<string, ...>>
type AllKeys = Record<string, number>;

// Succeeds in 4.1.5.
// Fails in later versions with `Property 'foo' is missing in type 'AllKeys' but required in type 'Foo'.`
isAssignable<MyType<AllKeys>, MyType<Foo>>();

// WORKAROUND
// If you introduce `keyof T` as a separate generic parameter, then things work more as expected.
type MyWorkaround<T, K extends keyof T = keyof T> = { x: K };

isAssignable<MyWorkaround<Partial<FooBar>>, MyWorkaround<Foo>>(); // ok
```

### 🙁 Actual behavior

The generic `MyType` behaves as if it is strictly contravariant in its generic param. You can't assign a `MyType<Foo>` to a `MyType<AllKeys>` even though you could assign the types they resolve to (`{ x: 'foo' }` and `{ x: string }`).

### 🙂 Expected behavior

It should behave more like the directly written type.

I assume the problem is this: The type records its variance for each generic parameter. A `keyof T` expression is treated as contravariant in T, and that is inherited by the generic type. But in reality, `keyof T` is not contravariant on T but on a transformation of it, one that strips out all values and partiality first.

So, it might be tricky to fix this regression while still retaining the simplifications or performance improvements that I imagine caused it. I don't really know, but perhaps something like secretly introducing `keyof T` as a hidden generic parameter as it is in the workaround might be a path forward.

**Comment by fatcerberus** [comment]
Looks like a duplicate, more or less, of https://github.com/microsoft/TypeScript/issues/43608

**Comment by matthewvalentine** [comment]
Yes, looks like a duplicate to me too, sorry. Although I have at least confirmed this is a regression and not the behavior in every version.

**Comment by matthewvalentine** [comment]
It's also worth noting that this repro also shows it's not actually feature of index schemas as discussed there, but just of `keyof`.
