### ISSUE TITLE
Cannot pass result of `typeof ... == 'function'` of `instanceof Function` as function parameter

### ISSUE THREAD

**Issue by Alexsey** [microsoft/TypeScript#54373]
# Bug Report

### 🔎 Search Terms

typeof function, instanceof Function, narrowing, Function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAdwE4EMAOiAUwwBcuAdKeqgOYDOR6YAngNoC6AlIgLwB8i4A1mDjIw7AN4BfALAAoGaEiwEiKKnoB1DNjyFeYAUJFEAbnBgATRKJmJEMYLij1MAUzj38nDogDk86PDBvdjQsbVYZKVlpIA)

### 💻 Code

```ts
function wrap (fn: (...args: any[]) => unknown) {}

function tryWrap (fn: unknown): void {
  if (typeof fn == 'function') wrap(fn)
} //         The error is over here ↑↑
```

### 🙁 Actual behavior

Error: `Argument of type 'Function' is not assignable to parameter of type '(...args: any[]) => unknown'.
  Type 'Function' provides no match for the signature '(...args: any[]): unknown'.(2345)`

### 🙂 Expected behavior

No error

### Notes

The reason for having this problem is because `typeof ... == 'function'` is narrowing to `Function`. And here we have a few problems:
 * Assuming that `Function` [interface is basically an implementation detail of the compiler](https://github.com/microsoft/TypeScript/issues/41225#issuecomment-716627722)
 * `Function` is [too generic](https://github.com/microsoft/TypeScript/issues/34540#issuecomment-543358887)

The behavior for `instanceof Function` is the same.

So, the solution would be to narrow it to a different type, because implementation details should not be exposed as a result of basic ES operations, or fix the `Function` type

**Comment by fatcerberus** [comment]
IMO this is a correct error.  `wrap` is free to call `fn`, per its signature, with any number and type of arguments.  Given that the only thing you know about `fn` is that it's a function, you have no way to know that any attempt to call it is safe, so the compiler prevents that from happening.

**Comment by fatcerberus** [comment]
In other words, since this is an error...

```ts
function tryWrap (fn: unknown): void {
  if (typeof fn == 'function') {
    fn(42, "foo");
  }
}
```

...then this should also be an error (and is)...
```ts
function wrap (fn: (...args: any[]) => unknown) {
  fn(42, "foo");
}

function tryWrap (fn: unknown): void {
  if (typeof fn == 'function') wrap(fn)
}
```

**Comment by Alexsey** [comment]
@fatcerberus
1. I have tried your code in the playground - it gives no error
2. It's up to `wrap` to decide on what to do with `fn`, not `tryWrap`

**Comment by fatcerberus** [comment]
> It's up to wrap to decide on what to do with fn, not tryWrap

If it’s not safe to call `fn` directly with arbitrary arguments (which *it isn’t*, and I don’t know why that code isn’t an error), then why should you be allowed to pass it to a function *that can freely do the same?*

**Comment by Alexsey** [comment]
The ability to call comes from the nature of ECMAScript - something that has `typeof "function"` can be called. TypeScript is checking only the types of arguments and the return value. And the signature of `wrap` is as generic as possible. Moreover, it uses `any`, and `any` should disable any kind of type checks

**Comment by nmain** [comment]
> The ability to call comes from the nature of ECMAScript - something that has `typeof "function"` can be called.

This falls under [all legal JavaScript is legal TypeScript](https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean).  Yes, if `typeof f === 'function'`, you can call `f` with any number of arguments of any type and that will not result in a runtime error.  But the callee may very well throw a runtime error of its own because it got arguments it didn't expect, or it might not throw an error but might do an entirely inappropriate thing for your use case.  The errors that Typescript gives help you avoid these undesirable situations.  If you want to say "shut up I know what I'm doing" to the compiler, consider asserting `fn as any` or setting the compiler option `noEmitOnError: false`.

**Comment by Alexsey** [comment]
> you can call `f` with any number of arguments of any type

yes

> and that will not result in a runtime error

no. A runtime error is not a term of TypeScript.

You can provide to `wrap` any kind of function you can specify and `wrap` can do anything with it - TypeScript will give no error
```ts
function foo (x: number) {}

declare const boo: (...args: never) => unknown

function wrap(fn: (...args: any[]) => unknown) {
  fn('abc')
}

wrap(foo)
wrap(boo)
```

This is expected and intended. So arguments types have nothing to do with the problem here because checking on them has been disabled by `any`.

The problem here is with the synthetic `Function` type that seems to cover something more than a function in JavaScript or TypeScript can be

**Comment by uhyo** [comment]
Hey, just to mention that `typeof class {}` is also `"function"`... 😶‍🌫️
