### ISSUE TITLE
Can't parse type correctly in as expression

### ISSUE THREAD

**Issue by spket** [microsoft/TypeScript#5437]
How is type parsed in typescript, by context like C/C++ or simply by guessing? like following code:

``` javascript
var a = 1;
var b = a as Number < 1;
```

Playground reports Type 'Number' is not generic, is it a bug or I have to use (a as Number) < 1, from Spec 'as' has same precedence as '<', right?

**Comment by DanielRosenwasser** [comment]
This looks like a bug in both the spec ([4.15.3 - (Grammar Ambiguities)](https://github.com/Microsoft/TypeScript/blob/0aef9440f28609ead886a1745f52d2a517326fde/doc/spec.md#4153-grammar-ambiguities) doesn't seem to cover it) and the implementation. `1` couldn't allow a syntactically valid *TypeArguments* production, so in principle we should speculatively check whether or not we have a valid *Type*.

Maybe @CyrusNajmabadi, @RyanCavanaugh, and @ahejlsberg have some input.

**Comment by weswigham** [comment]
@DanielRosenwasser:
```ts
var x: string|number;
var y = x as String < "20";
```
Consider string types.

**Comment by vladima** [comment]
Also current behavior is similar to C#
```C#
    class Program
    {
        public static bool operator >(Program a, int b)  { throw new NotImplementedException(); }
        public static bool operator <(Program a, int b) { throw new NotImplementedException(); }
        static void Main(string[] args)
        {
            object x = null;
            Program y = null;
            var z = x as Program < y; // The non-generic type Program cannot be used with type arguments
        }
    }

```

**Comment by CyrusNajmabadi** [comment]
Correct, we parse as C# does.  If we're in a type context, and we see a ```<```, then we treat it as the start of a type argument list.

This can be worked around by parenthesizing the ```as``` expression if you wish.

**Comment by mhegazy** [comment]
This issue tracks updating the spec to reflect the current behavior. the original issue is by design.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
