### ISSUE TITLE
Declare method quick fix not returned for `#private` method

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#54383]
# Bug Report

### 🔎 Search Terms

- quick fix
- code action

### 🕗 Version & Regression Information
5.2.0-dev.20230524

### 💻 Code
```ts
class Foo {
    constructor() {
        this.#bar();
    }
}
```

1. Trigger quick fixes on `#bar`

### Bug
No `declare method` quick fix is returned

This quick fix is returned if you remove the `#`

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!
