### ISSUE TITLE
bug(regression): Cannot narrow types with `Readonly` and `type predicates`

### ISSUE THREAD

**Issue by Gumichocopengin8** [microsoft/TypeScript#54385]
# Bug Report

### 🕗 Version & Regression Information

- Reproducible in version `5.1.0-beta` and `5.0.4`
- Works fine in version `4.9.5`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-beta#code/PTAECcFMDMC5QBYBckAcDOsQHdcDokBPVSdAY3AEtUkAbAQwDsBzPAe3GeABM2z1gCJtwBGbNgGtgAJmCN64cG2yUWeZAFtaAKG1ESoAGKV0CUAF5QAb1DoVG+AAoAlBYB8oAG5tK3UAF8Abj1iSFAAIUpwP0sbaFpCJ1dzD29fAOD9MPC2JDNLY1NQAB8IqO5daABXRjIkSjZGUBNChEcSJHhWkrLo53gO5vQjEzMrbVAISCQq8Cb26dB6YdbnPDtKDVAAQnNLGu4YVUhuQNAQUEZc0GwOCRvKPNAAAwAiDY1X5qaO59BIR4ISDgUDafy6C6PG53YYqJ5ZUCoKDcShkehIUjaaq1eqNUAaNieSCOJibei0eA5PKucaTSjQUCOFqjEmMMm0Zw0iaTKYzOZLNkacnrewuYKTcGTKB8pqkoW0PDxQhisEQsBQgAiAHkAKIAZVAADktQAVaHge5wswIpEnVHo0gCvwAJUg9F4jASWJqdQaTQJROkrPZ8Fd7saCQAPFSEG4uXSGUz0K1g-LOdZuVLprNZYLhR8VRLudKcwL2YqEmLzmBIwBaUAAdQAEgBNAD8qu0kKQ5oksMB31AbBI4HRHFB2N9eIDkAA+qpU+TKbkEPHmon3vYvqoy2mMzzeaW5fnRc5xQFi9n+ceFUqVeCu+qe7cLf2njvh8CxyDhKAwx6vUnXF-UJOdVCDG9QzdADCGjFc433ddGU3TZt1zdk1yzGVdxPTZCwvLCjzzW9KzPMEgA)

### 💻 Code

```ts
// ref: https://www.typescriptlang.org/docs/handbook/2/narrowing.html

type Fish = { swim: () => void };
type Bird = { fly: () => void };
type Both = Fish | Bird

function isFish(pet: Fish | Bird): pet is Fish {
  return (pet as Fish).swim !== undefined; // not work with `"swim" in pet` either 
}

// it works with type predicates
function move(animal: Both) {
  if (isFish(animal)) {
    return animal.swim();
  }
  return animal.fly();
}

// it DOES NOT work with type predicates and Readonly
function move2(animal: Readonly<Both>) {
  if (isFish(animal)) {
    return animal.swim();
  }
  return animal.fly(); // <- WHY?
}

// it works with in operator 
function move_in(animal: Both) {
  if ("swim" in animal) {
    return animal.swim();
  }
  return animal.fly();
}

// it works with in operator and Readonly
function move_in2(animal: Readonly<Both>) {
  if ("swim" in animal) {
    return animal.swim();
  }
  return animal.fly();
}
```

### 🙁 Actual behavior

[Type narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) does not work with `Readonly` and `type predicates`

### 🙂 Expected behavior

Type Narrowing should work with `Readonly` and `type predicates`

**Comment by RyanCavanaugh** [comment]
This is correct behavior. `Fish` is a subtype of `readonly Fish`, so knowing that something is not a `Fish` doesn't tell you that it's *not* a `readonly Fish`

**Comment by Gumichocopengin8** [comment]
@RyanCavanaugh 
It used to work fine before v5 with `Readonly`, such as `v4.9.5`. Does that mean v5 changed the behavior? IIRC, [the doc](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html) does not mention the change of the behavior. 
What is the good way to narrow types with `Readonly` and type predicates after v5 then?

**Comment by fatcerberus** [comment]
I suppose it's true that `Fish` is a subtype of `Readonly<Fish>` but since there's no way to distinguish them at runtime (as `readonly` is a compile-time-only concept), the compiler making that distinction doesn't seem useful and only gets in the way of using `Readonly` with UDTGs.

@Gumichocopengin8 I guess a workaround would be to declare your type predicate as returning `pet is Readonly<Fish>`, though I'm not sure if that would run into other issues.
