### ISSUE TITLE
Typing [enter] near the bottom of checker.ts takes nearly a second

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#5438]
Open tsc.ts in Visual Studio 2015, and open checker.ts from the solution explorer. Scroll to somewhere close to the bottom, find an empty line and type `[enter]`. 

Notice the delay until the new line is rendered and you can start typing again.

This doesn't seem to repro in VS Code. And seem better on VS 2015 RTM

**Comment by vladima** [comment]
@paulvanbrenk can you check if you still have this issue using ret TypeScript bits. Please make sure that DevMode is disabled

**Comment by paulvanbrenk** [comment]
Nope, this seems fine now.
