### ISSUE TITLE
Inheritance with generics disappears when using typings and "this" type

### ISSUE THREAD

**Issue by alberto-schena-gizero** [microsoft/TypeScript#54398]
# Bug Report

### 🔎 Search Terms

type generics constraints incompatible assignable typings extends class subclass this

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about any of these keywords "type generics constraints incompatible assignable typings extends class subclass this".

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEHkCcEsHNoHYEMA2oDGKkGdsFNsBYAKBLwA8AHAe0gBcMtdQBlAVwCMArPdOgHgAq7DtnQwOeSABpQggLJ46AC2oATUBTp4Ea7HJFiJUgNoBrPAE9qAMwOcj0SZAC6APhIBvEqF8ZqCNh0kGx8tAAUlJDU2nx4GpB4SGoBKJag+Ci8dLQAXKDh2A7iTlL5wsXGkACUoAC8bnKKKurVPn6eAL4k3aTEFDT0jDj6AEJ4ykgAbtC02EIAogh00HTpWjp6oEsrax7E3sR+oFEx2fGgicmp6QD6AQCCamrxACT1oAh4AO6snDx8cLhVb5cAIcaTGa0J4vNSLZarSxuWoNUCrAB0AQh01mkBh8WqAG4SO1fOgAkEQmFIJForFtAkkikEGlNAi1uUdoi2kcOr1emQqLQGIhtJAbEh0HgIOCJjjoc94vDdutyNpdPouXsvKTQFi5VC8Yq1OEdCrOezLNV8lNqNA1MTiAL+kKhkhRMFJQxMCNtpadbzfFdmazJJDcfo6p8fqBsYbsOEVNBsESeiSXYNvUx9AARPAzKW6jYav0qgPHYM3NEaKMABkdzpAoAA4jopEgGaA1pRELB9OFEsgALYE9MDYWgF4+xLDZgiAF0W5qW50eYVUQlZyyBRKVQaYtbdeOZzmKy2ewbqruUCHY6nekXSss9KZbJ5ApFS+lSDlQybqQoo0O4tA6urkoEwShDkNKvtS+SFJU36-ohziAU0u6tA2gqZpOvBYDOPrMHGEZLiua5aqq6pbBRpGro0t5+Pe5yMtcz5suacgUY6d50sxlxMlW9wIPiaivPk87ZLR8xgsRCqwlJyqIm4simpaFoqmhtr2m43F+OBlJQREZqIup3JYRmE6ilIEpSjKslGvJy6ropayaGqmyapaUn0bq+rhnJ8SqRxggUdaoBaaBTrYROU74dK7qUl6s6eSqUk3rqT6hgaEb5PZ2AKUm2A6WmFlDLFSAEdmoB5gWeBpQeKWImlDFBgJbH2h89YlSQTYAMLKLwZhEH03bSjY0RDt2vYfDV0BSvV7kljRTn6AA-KAADk1BmBtoD5BtZjUBtjqjaA43UEO2DUGwkBSpG1X5nN0oNaWiKgOtW07Xtm2Hcd6aEfoABi1DUG5VFjNlcz8LNUpuF0JAA7GFVgx5saQ5A+UrdDj3zStcOdEAA)

### 💻 Code

```ts
// Original classes

export class Subject<TSubscriber, TMethod extends TSubscriber[keyof TSubscriber]>
{
    constructor(protected readonly selector: (subscriber: TSubscriber) => TMethod)
    {}
}

export class Behaviors<TEntity extends Entity>
{
    protected readonly _onAdded$ = new Subject((it: OnBehaviorAdded<TEntity>) => it.onBehaviorAdded);

    constructor(protected readonly entity: TEntity)
    {}
}

export interface OnBehaviorAdded<TEntity extends Entity>
{
    onBehaviorAdded(entity: TEntity): void;
}

export abstract class Entity
{
    readonly behaviors = new Behaviors(this);
}

export class Device
    extends Entity
{
    readonly id = 0;
}

// Generated typings (renamed)

export declare class Subject_d_ts<TSubscriber, TMethod extends TSubscriber[keyof TSubscriber]> {
    protected readonly selector: (subscriber: TSubscriber) => TMethod;
    constructor(selector: (subscriber: TSubscriber) => TMethod);
}
export declare class Behaviors_d_ts<TEntity extends Entity_d_ts> {
    protected readonly entity: TEntity;
    protected readonly _onAdded$: Subject_d_ts<OnBehaviorAdded_d_ts<TEntity>, (entity: TEntity) => void>;
    constructor(entity: TEntity);
}
export interface OnBehaviorAdded_d_ts<TEntity extends Entity_d_ts> {
    onBehaviorAdded(entity: TEntity): void;
}
export declare abstract class Entity_d_ts {
    readonly behaviors: Behaviors_d_ts<this>;
}
export declare class Device_d_ts extends Entity_d_ts {
    readonly id = 0;
}

// Checks

type fromtyping = Device_d_ts extends Entity_d_ts ? 'ok' : 'ko';
type fromsources = Device extends Entity ? 'ok' : 'ko';

class Foo extends Behaviors<Device>{}
class Bar extends Behaviors_d_ts<Device_d_ts>{}
```

### 🙁 Actual behavior

As you can see, `Device_d_ts` does not extend `Entity_d_ts` (`fromtyping` is `'ko'`), whereas `Device` extends `Entity` (`fromsources` is `'ok'`).
Thus, through typings the type check yields a different result from the original type definitions.

### 🙂 Expected behavior

I would have expected the same behavior regardless of using typings or not.

Which one is correct?
- Both `fromtyping` and `fromsources` must be `'ko'`
- Both `fromtyping` and `fromsources` must be `'ok'`

**Comment by fatcerberus** [comment]
My initial guess is some kind of discrepancy in variance measurement but yeah, this is weird

**Comment by RyanCavanaugh** [comment]
This example encounters a limitation in our variance measurement algorithm. Annotated example:
```ts
export class Subject<in TSubscriber, out TMethod extends TSubscriber[keyof TSubscriber]>
{
    constructor(protected readonly selector: (subscriber: TSubscriber) => TMethod)
    {}
}

export class Behaviors<out TEntity extends Entity>
// Under v1, this is incorrectly measured as covariant on TEntity
// Under v2, it is correctly measured as invariant
{
    // v1
    protected readonly _onAdded$ = new Subject((it: OnBehaviorAdded<TEntity>) => it.onBehaviorAdded);
    // v2
    // protected readonly _onAdded$: Subject<OnBehaviorAdded<TEntity>, (entity: TEntity) => void> = null as any;

    constructor(protected readonly entity: TEntity)
    {}
}

export interface OnBehaviorAdded<in TEntity extends Entity>
{
    onBehaviorAdded(entity: TEntity): void;
}

export abstract class Entity
{
    readonly behaviors = new Behaviors(this);
}

export class Device
    extends Entity
{
    readonly id = 0;
}
```

See #44572 for more details (including links to longer discussion)
