### ISSUE TITLE
Constructor Overloading

### ISSUE THREAD

**Issue by BWootBIJC** [microsoft/TypeScript#54397]
# Suggestion

I would love to overall see TypeScript adopt even more Object Oriented concepts and features. One of those is multiple constructor overloading similar to the way it's done in C#. The current way to work around this is to provide nullable values to your constructor, but that makes your primary constructor look bloated and at times ugly. I jump between TypeScript and C# a bunch and I wish it was as easy in TypeScript as it is in C#. With the idea of constructor overloading, it would also be nice to be able to implement private constructors for implementing certain design patterns like the Singleton pattern or advanced Factory patterns.

## 🔍 Search Terms

Constructor Overloading
Multiple Constructors
Private Constructors

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

I would love to see the ability to declare multiple constructors in TypeScript, similar to how it can be done in C#. I would also like the ability to declare certain constructors as private, thus forcing the creation of the object to go through a factory method.

## 📃 Motivating Example

The introduction of constructor overloading improves the object oriented abilities of TypeScript. If you are building enterprise level applications using agile, you would benefit greatly from implementing the latest oop features in TypeScript.

## 💻 Use Cases

This feature would be useful for creating complex objects in TypeScript code. This would be very useful if I wanted to encapsulate constructor logic in a class and allow an internal factory class to do the building of the object for me. This would also allow me to easily create different constructors for the instantiation of an object. In C#, this is straightforward and very simple to do and simple to read. In TypeScript, the only way to achieve this is to provide nullable values to your constructor and have a long list of if checks in your constructor to see that the right constructor is built. This approach works but it can get very messy. If I could implement multiple constructors in TypeScript, this would bring a stronger developer experience to TypeScript, especially for those that come with a deeper background in heavy object oriented languages like C# or Java.

**Comment by MartinJohns** [comment]
You can overload constructor just like any other function already. But overloading in the sense of having different implementations per overload is explicitly out of scope for TypeScript. It has also been suggested and declined before.

Don't try to treat TypeScript like C#. They operate quite differently.

**Comment by RyanCavanaugh** [comment]
```ts
class Foo {
    constructor(n: string);
    constructor(s: number);
    constructor(ns: string | number) {}
}
```
