### ISSUE TITLE
Latest RC version tsc faild to load tsconfig.json>compilerOptions>types

### ISSUE THREAD

**Issue by adoin** [microsoft/TypeScript#54390]
When I run tsc on 
    "typescript": "^5.0.4",
It crash by "RangeError: Maximum call stack size exceeded".
Then I try 
    "typescript": "^5.1.1-rc",
It tell me ``` tsconfig.json:20:16
    20     "types": [ "vite/client","jest", "node"],
                      ~~~~~~~~~~~~~
    File is entry point of type library specified here.```
So I remove ``` "vite/client",```
It works, but all type like styleValue can't be found.

What should I do? lower one crashed, higher one can read "types" config.
Any Idea or It's a issue?

**Comment by RyanCavanaugh** [comment]
Please provide a complete repro

**Comment by nopeless** [comment]
I am having similar issues, encountering it from Nuxt's development cli, sporatically. I'll get back if I ever find a reproduction

**Comment by adoin** [comment]
> Please provide a complete repro

Not easy to make a repro, a make a clean project whick works fine...
I don't know which package or code crushed causing this problem.

**Comment by nopeless** [comment]
Update: it seems to only happen when vite hmr has been active for a long time. I don't know why this is the case but at least its reliable. Problem is reproducing takes like 20 minutes of waiting

**Comment by chrisahardie** [comment]
@RyanCavanaugh I'm able to repro on [this project](https://github.com/chrisahardie/ts-project):

```
ts-project yarn tsc --noEmit 
yarn run v1.22.17
$ /Users/chrishardie/src/github.com/chrisahardie/ts-project/node_modules/.bin/tsc --noEmit
error TS2688: Cannot find type definition file for 'vite/client'.
  The file is in the program because:
    Entry point of type library 'vite/client' specified in compilerOptions

  tsconfig.json:21:15
    21     "types": ["vite/client", "vitest/globals"]
                     ~~~~~~~~~~~~~
    File is entry point of type library specified here.

error TS2688: Cannot find type definition file for 'vitest/globals'.
  The file is in the program because:
    Entry point of type library 'vitest/globals' specified in compilerOptions

  tsconfig.json:21:30
    21     "types": ["vite/client", "vitest/globals"]
                                    ~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.


Found 2 errors
```

**Comment by sheetalkamat** [comment]
@chrisahardie  the project you provided is configured incorrectly. "typeRoots" is a place where the types should be looked up and "types" is the list of types to automatically add to project. So configuring ["typeRoots": ["./app/ui/types/custom.d.ts"]](https://github.com/chrisahardie/ts-project/blob/main/tsconfig.json#L20) is trying to resolve `@vite/client` from that location which seems not intentional

**Comment by chrisahardie** [comment]
@sheetalkamat thanks, I've inherited a tsconfig and didn't catch the misconfiguration. I assume that between latest and version `5.0.4` things have simply tightened up.
