### ISSUE TITLE
types of `A[] || B[]` and `A[] ?? B[]` are incorrect if `A` is a subtype of `B`

### ISSUE THREAD

**Issue by Alexsey** [microsoft/TypeScript#54409]
# Bug Report

### 🔎 Search Terms

Arrays, null coalesce, OR operator, subtype reduction

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 
### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.0-beta#code/CYUwxgNghgTiAEYD2A7AzgF3lAXPA3vAB56YwCWKA5vAL4DaAuvAD7wCuKoAZpSMAChQkWAmTosadgCMAgnkIl4ZSlQA08AJ54U7ALbSQMOkyHhocRKkzwUSDAGUZ8glp37DxhowEDxNqiQkYHgAXmxWNjtHZ3gAejjXJRVqE2Y2Qm1bDyM0v2ssaSgQ8KhI5ViEpNIMClTvASA)

### 💻 Code

```ts
declare const a: { x: string }[] | undefined
declare const subA: { x: string, y: number }[]
declare const notSubA: { y: number }[]

const good = a || notSubA // { x: string }[] | { y: number }[]
const bad = a || subA // { x: string }[]
```

### 🙁 Actual behavior

`bad` is `{ x: string }[]` (type of `a` but without `undefined`)

### 🙂 Expected behavior

`bad` should be `{ x: string }[] | { x: string, y: number }[]` (a union of `a` and `subA` without `undefined`).

Type of `||` should not depend on the relationship between types of operands

### Notes

null coalesce `??` suffers from the same problem

**Comment by fatcerberus** [comment]
It's admittedly annoying, but not really a bug.  Technically the types `{ x: string } | { x: string, y: number }` and `{ x: string }` are equivalent since in both cases you might have ended up with, e.g. a `{ x: string, y: boolean }` (see #12936); you can't actually safely assume anything about `y` in either case.

**Comment by Alexsey** [comment]
@fatcerberus I'm afraid I have to disagree because your logic can be applied the same way to non-subtype case:
```tstype A = { a: string }
type B = { b: number }

function foo (x: A | B): string {
    if ('a' in x) {
        return x.a.toUpperCase()
    }
    return `${x.b}`
}

const runtimeCrashArg = {a: true, b: 22}

foo(runtimeCrashArg) // no error
```
