### ISSUE TITLE
[Function Overloading] implementation is obviously different to the signatures, but no ts error

### ISSUE THREAD

**Issue by shhider** [microsoft/TypeScript#54406]
# Bug Report

### 🔎 Search Terms

overload, implementation, signature, different, compatible

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [This-FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-supplied-parameters-do-not-match-any-signature-error)

### ⏯ Playground Link

[code in playground](https://www.typescriptlang.org/play?#code/PTAEGcEsHMDsEMAuBXATgUwFADNmwMaKQD2so2xxAFAB40BcosyAtgEbqoCUjz7nAbhx5CJMhWp1erDqgA0oAJ6LG4RKkixoPCOs3QhmEKEgsADgBt0LdLERIxwgkVLlKtBkxmcFygPyqelo6fLKgAD66GloRoGyUVvBkAN6YoOkm2KBUyqAAvHleFhZcoKkZFaAYKKhkdEIVAL5pGZBZOYr5BaAARABsAz2l1Whk6sjoDRkjtUqKQs1AA)

### 💻 Code

```ts
// signature
function foo(xx: number): number;
function foo(xx: number, yy: string): string;

// implementation
// ❗️it may return `boolean`, differing to the signatures
function foo(xx: number, yy?: string): number | string | boolean {
    if (yy == null) {
        return xx;
    }
    if (yy === "666") {
        return true;
    }
    return yy;
}
```

### 🙁 Actual behavior

Obviously, the implementation doesn't satisfy the signatures, but TS didn't "find" it. It confused me, and brought some issues into my project.

I don't know whether it is by-design or a bug, and I didn't find any doc about this behavior. Please  tell me the reason of this design, if it is by-design.

### 🙂 Expected behavior

```ts
// signature
// EXPECTED: Tell me "This overload signature is not compatible with its implementation signature."
function foo(xx: number): number;
function foo(xx: number, yy: string): string;

// implementation
function foo(xx: number, yy?: string): number | string | boolean {
    // ...
}
```

**Comment by fatcerberus** [comment]
This is basically the same kind of unsoundness that happens with the "correct" signature:

```ts
// signature
function foo(xx: number): number;
function foo(xx: number, yy: string): string;

// implementation
function foo(xx: number, yy?: string): number | string {
    return 42;  // unconditionally returns a number
}
```

...namely that nothing prevents you from returning the wrong type for the overload that was actually called.  There doesn't really seem to be an easily generalizable mechanism by which you could reject the case in the OP without also rejecting the "correct" signature, either, since both cases involve a return type which is simultaneously wider than both overloads'.  So what would the rule for that be?

**Comment by jcalz** [comment]
Duplicate #52478 and ultimately #13235
