### ISSUE TITLE
discriminated types that include one optional case break when combined with unions or interface inheritence

### ISSUE THREAD

**Issue by RoboPhred** [microsoft/TypeScript#54418]
# Bug Report

Given a discriminated type where one of its variants involves the discriminating property being optional:
- If the final combined type is unioned with another type, then discrimination breaks and allows any dependent property without requiring the discriminant
- If the interfaces that make up the discrimination themselves inherit from a common interface, then the discrimination breaks and allows any dependent property without requiring the discriminant

### 🔎 Search Terms

Discriminated types
interface inheritance
Unions

### 🕗 Version & Regression Information

Seen in 4.9 and 5.1 beta
__
- This is the behavior in every version I tried, and I reviewed the FAQ for known issues on discriminated types

### ⏯ Playground Link

[Case 1: Non-unioned shows correct errors, union to another type masks the error](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgeXXTgG8AoOOAEwQGdsoEBbZTFAfgC44sAbW4AG4yAXzJlQkWIhRosuAklIVqdBs1YpuMKAFchKqMACOuhEaoAxXUmwwEEJAAoAlNwBuEBFWFiyMAE8wPAARNUYWJExUKjgAXgIiOAAfRWEyAHoMuAA5CDg0KGgAGgL3NACYAAtkAHM4CABrMmxHWnhUdsJ0bjD6CNYY+OVRcSy4AFEoIqhaOEw5yWA7YCpSgAMjU3NV61t7R3W4JAh4WmDsBHQEVZa2juAupF7wjSihhPJKGn63thhtHpgKNMtkpjM5gsCuBljFuOsfupIv8jiczhcrjcqHckO04J0YAB1BDVCC6GB9JGaAFwSkDd6rYZfOBbMwWPZ2BzPOCueIAPlIYj8kmg8GQqAwODwAEEqDQDlFeAAFIpgObM9AQCDcJC6JgAIzQvnEIukgWCk3AbCoqzpfw+tNeyKGADI4LL5VzMMrVbR0uM8gVpiUyhVqnUGs1WriHu0JlakDaqN1uPGwNbbU7BozPipNdq4AAWABMIPG4OgkMWMJWVHhrJ2VhsnMOx1OcHOy0xt2jeIJaYzye5A8Tmd+zpzyko+e4JeKKkR9P+gP0ZeyACEAKoAcQAhJRA4VoPu4AAVADKcEaJwA7nNqtEWSY2btmwrEHN0EUmHB1vgkOspT6uScCgm2QYzB+cBgEYAiyLEX4QD+1R4CwtC0BGCJZlEKBHDBEDBLAAQ4n2jwwCOSbEqS5J2siWiWumo5ULR2axLm05arOxbzpQDbsm+XLcLycQCiQQpAA)

[Case 2: Trying to work around the bug by using interface inheritance causes the same bug](https://www.typescriptlang.org/play?ts=4.0.5#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgQQBNCEYEIlMAbABSgjAGc4BvAKDjnQggC44kAVwC2AIzQBuNgF82bUJFiIUaLLjgB5dOjihUSQsyIkyFanQbN2nEo2xQEw5JhQB+fliqNgU2fPDQ8MioGDh4Gki6IPqGBMSk5JS09EysHHC29o7OKPwwUII+6VDAAI6CCCWEAGKCSNimSAAUAJT8AG4QCIS+cjAAnmB4ACIIdg5OlKiEcAC8mtpwAD6aSFJsAPQbcAByELpQ9FAANLrtaP0wABbIAOZwEADWbNgUjPCo71ro-KPj2VNgDN5tYuDx+AAWABMMjkWzgAFFDtBmJhmApgA0gacAAYlcqVIG1eqNHECCDwRhDbAIdAIIEvN4fYBfJC-MZZSaYaZzNKcbh8ODQ47pTITHIwPIFYCwzbbABCAFUAOL8PYHI6nMUAlxBZhIClwKmY2n0winUSCeAAFQAynAcLgwDBmPiKlViQ1Eg7mO1qN1GUh3nBPjAAOqkK4QK1-TkS9n-Lk8kHpAWQqEizhuwk1Opeij8VpzAB8rFk0iAA)

### 💻 Code

```ts
interface Off {
  discriminant?: false;
}

interface On {
  discriminant: true;
  requiredFunction(): void;
}

type Discriminated = Off | On;

// Errors as expected: `discriminant` not specified
const testWithoutDiscriminant: Discriminated = {
  requiredFunction: () => {}
}

interface AdditionalProps {
  foo: number;
}

type ExpandedDiscriminated = Discriminated & AdditionalProps;

// BUG!  No error!  TS knows that requiredFunction is from `On`, but 
// no error is presented from the missing `discriminant` property
// Also note that requiredFunction seems to be typed as required here, even though
// no error will be presented if it is removed
const testExpandedWithoutDiscriminant: ExpandedDiscriminated = {
  foo: 42,
  requiredFunction: () => {}
}
```

Attempts to work around this issue by instead using inheritance on the discriminated types triggers the exact same error.

```ts
export interface AdditionalProps {
  foo: number;
}

export interface Off extends AdditionalProps {
  discriminant?: false;
}

export interface On extends AdditionalProps {
  discriminant: true;
  requiredFunction(): void;
}

type Discriminated = Off | On;

// No error, everything ok
const testOff: Discriminated = {
  foo: 42
}

// Errors as expected, `requiredFunction` not specified
const testOn: Discriminated = {
  foo: 42,
  discriminant: true
}

// BUG: No error, discriminant is not specified, but TS accepts requiredFunction as valid
const testWithoutDiscriminant: Discriminated = {
  foo: 42,
  requiredFunction: () => {}
}
```

### 🙁 Actual behavior

`requiredFunction`, which should only be present when `discriminant` is true, is instead available when the discriminant is missing.

### 🙂 Expected behavior

`requiredFunction` should indicate an error if not accompanied by `discriminant: true`

### Background

This was discovered when trying to configure React components such that options can be enabled with boolean values which then enable access to additional properties.  These properties should not be available if the boolean is not present / set to true.

For example:
```ts
// Valid
<SelectField />

// Valid
<SelectField searchable={true} onSearchChanged={handler}/>

// This should error: component is not searchable.
<SelectField onSearchChanged={handler}/>
```

### Workarounds

It seems to be possible to get the behavior I want if I never use unions on discriminated types.  This would mean I have to fully expand out every interface variation for the component's properties.  This might be feasible with just one variant, but we have multiple flags such as this and it is not feasible to create every permutation by hand.

It seems to work fine if the 'off' state has the discriminant not be optional.  This is a non-starter for us as we have to maintain backwards compatibility and we do not want developers to need to explicitly opt out of any feature they are not using.

We were able to make a workaround by making the react component an overloaded function, using the overloads as discriminants instead of the combined Discriminant type.  However, this results in the entire component usage getting marked as an error instead of just the offending property due to TS not being able to figure out which of the many overloads it should be generating an error for.  This is a really bad and confusing developer experience for the library consumer.

**Comment by RyanCavanaugh** [comment]
The value you initialized here is absolutely a valid member of the union prescribed:
```ts
const obj = {
  foo: 42,
  requiredFunction: () => {}
}
const off: Off & AdditionalProps = obj;
```
The only defect here is that you're not seeing excess property checks which are a little bit laxer than you might expect from a theoretical perspective but excess property checks are basically event featured designed to catch typos and there's no typos here

**Comment by RoboPhred** [comment]
It looks like you replied before I could update the second case I discovered:

https://www.typescriptlang.org/play?ts=4.0.5#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgQQBNCEYEIlMAbABSgjAGc4BvAKDjnQggC44kAVwC2AIzQBuNgF82bUJFiIUaLLjgB5dOjihUSQsyIkyFanQbN2nEo2xQEw5JhQB+fliqNgU2fPDQ8MioGDh4Gki6IPqGBMSk5JS09EysHHC29o7OKPwwUII+6VDAAI6CCCWEAGKCSNimSAAUAJT8AG4QCIS+cjAAnmB4ACIIdg5OlKiEcAC8mtpwAD6aSFJsAPQbcAByELpQ9FAANLrtaP0wABbIAOZwEADWbNgUjPCo71ro-KPj2VNgDN5tYuDx+AAWABMMjkWzgAFFDtBmJhmApgA0gacAAYlcqVIG1eqNHECCDwRhDbAIdAIIEvN4fYBfJC-MZZSaYaZzNKcbh8ODQ47pTITHIwPIFYCwzbbABCAFUAOL8PYHI6nMUAlxBZhIClwKmY2n0winUSCeAAFQAynAcLgwDBmPiKlViQ1Eg7mO1qN1GUh3nBPjAAOqkK4QK1-TkS9n-Lk8kHpAWQqEizhuwk1Opeij8VpzAB8rFk0iAA

This uses inheritance instead of unions, so there's no possibility it could cross the contents between them.  However, the error still persists.
