### ISSUE TITLE
super in object literal causes error

### ISSUE THREAD

**Issue by mrac** [Microsoft/TypeScript#5441]
The following code should log:
```
original
new
```
as it does in ES6. Instead in TypeScript 1.6.2 it causes an error:

```'super' can only be referenced in a derived class.```

Here's the code:

```
var obj = {
    __proto__: {
        method() {
            console.log('original');
        }
    },
    method() {
        super.method();
        console.log('new');
    }
};

obj.method();
```

**Comment by mhegazy** [comment]
As per the ES6/S2015 spec, super is only allowed in classes. In this sample `__proto__`  is just a regular poverty and is not treated differently by the typesystem. What works is rewriting this as classes, this should be equivalent: 

```ts
var obj = class extends class {
    method() {
        console.log('original');
    }
}{
    method() {
        super.method();
        console.log('new');
    }
};
```

**Comment by mrac** [comment]
I didn't decypher the spec document, but the MDN doc says:
> The super.prop and super[expr] expressions are valid in any method definition in both classes and object literals.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super

Chrome, Node, Firefox and Babel all call the prototype method here. No error.
So TypeScript is not compatible with ES6 in this case.

**Comment by weswigham** [comment]
@mrac seems right - nothing in the [super keyword spec](http://tc39.github.io/ecma262/#sec-super-keyword) indicates that it is only valid within a class, and, in fact, there are even places that call out that you can't user `super` in places like [certain evals](http://tc39.github.io/ecma262/#sec-scripts-static-semantics-early-errors) and [module statement lists](http://tc39.github.io/ecma262/#sec-module-semantics-static-semantics-early-errors). The spec area indicating that any function with a home object can use `super` would be [Function.[[HasSuperBinding]]](http://tc39.github.io/ecma262/#sec-function-environment-records-hassuperbinding).

**Comment by mhegazy** [comment]
yes. looking at the final spec that seems the case; though i remember it was not at some point.

**Comment by RyanCavanaugh** [comment]
Design meeting resolution: `super` should be allowed only in ES6 in a shorthand method body in an object literal and is of type `any`
