### ISSUE TITLE
Discriminated unions on interfaces with inheritance cross-contaminate when one discriminate is optional 

### ISSUE THREAD

**Issue by RoboPhred** [microsoft/TypeScript#54421]
Continued from #54418

# Bug Report

Given a discriminated type where one of its variants involves the discriminating property being optional:
If the interfaces that make up the discrimination themselves inherit from a common interface, then the discrimination breaks and allows any dependent property without requiring the discriminant.  This does not happen if inheritance is not used.

### 🔎 Search Terms

Discriminated types
interface inheritance

### 🕗 Version & Regression Information

Seen in 4.9 and 5.1 beta
__
- This is the behavior in every version I tried, and I reviewed the FAQ for known issues on discriminated types

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.0.5#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgQQBNCEYEIlMAbABSgjAGc4BvAKDjnQggC44kAVwC2AIzQBuNgF82bUJFiIUaLLjgB5dOjihUSQsyIkyFanQbN2nEo2xQEw5JhQB+fliqNgU2fPDQ8MioGDh4Gki6IPqGBMSk5JS09EysHHC29o7OKPwwUII+6VDAAI6CCCWEAGKCSNimSAAUAJT8AG4QCIS+cjAAnmB4ACIIdg5OlKiEcAC8mtpwAD6aSFJsAPQbcAByELpQ9FAANLrtaP0wABbIAOZwEADWbNgUjPCo71ro-KPj2VNgDN5tYuDx+AAWABMMjkWzgAFFDtBmJhmApgA0gacAAYlcqVIG1eqNHECCDwRhDbAIdAIIEvN4fYBfJC-MZZSaYaZzNKcbh8ODQ47pTITHIwPIFYCwzbbABCAFUAOL8PYHI6nMUAlxBZhIClwKmY2n0winUSCeAAFQAynAcLgwDBmPiKlViQ1Eg7mO1qN1GUh3nBPjAAOqkK4QK1-TkS9n-Lk8kHpAWQqEizhuwk1Opeij8VpzAB8rFk0iAA)

### 💻 Code

The following code produces the (lack of) error
```ts
export interface AdditionalProps {
  foo: number;
}

export interface Off extends AdditionalProps {
  discriminant?: false;
}

export interface On extends AdditionalProps {
  discriminant: true;
  requiredFunction(): void;
}

type Discriminated = Off | On;

// No error, everything ok
const testOff: Discriminated = {
  foo: 42
}

// Errors as expected, `requiredFunction` not specified
const testOn: Discriminated = {
  foo: 42,
  discriminant: true
}

// BUG: No error, discriminant is not specified, but TS accepts requiredFunction as valid
const testWithoutDiscriminant: Discriminated = {
  foo: 42,
  requiredFunction: () => {}
}
```

However, if we remove the inheritance, everything works as expected
```ts
export interface Off {
  discriminant?: false;
}

export interface On {
  discriminant: true;
  requiredFunction(): void;
}

type Discriminated = Off | On;

// No error, everything ok
const testOff: Discriminated = {
}

// Errors as expected, `requiredFunction` not specified
const testOn: Discriminated = {
  discriminant: true
}

// Errors as expected: Identified type is 'On', Missing property 'discriminant'
const testWithoutDiscriminant: Discriminated = {
  requiredFunction: () => {}
}
```

### 🙁 Actual behavior

`requiredFunction`, which should only be present when `discriminant` is true, is instead available when the discriminant is missing.

### 🙂 Expected behavior

`requiredFunction` should indicate an error if not accompanied by `discriminant: true`

### Background

This was discovered when trying to configure React components such that options can be enabled with boolean values which then enable access to additional properties.  These properties should not be available if the boolean is not present / set to true.

For example:
```ts
// Valid
<SelectField />

// Valid
<SelectField searchable={true} onSearchChanged={handler}/>

// This should error: component is not searchable.
<SelectField onSearchChanged={handler}/>
```

### Workarounds

It seems to be possible to get the behavior I want if I never use unions on discriminated types.  This would mean I have to fully expand out every interface variation for the component's properties.  This might be feasible with just one variant, but we have multiple flags such as this and it is not feasible to create every permutation by hand.

It seems to work fine if the 'off' state has the discriminant not be optional.  This is a non-starter for us as we have to maintain backwards compatibility and we do not want developers to need to explicitly opt out of any feature they are not using.

We were able to make a workaround by making the react component an overloaded function, using the overloads as discriminants instead of the combined Discriminant type.  However, this results in the entire component usage getting marked as an error instead of just the offending property due to TS not being able to figure out which of the many overloads it should be generating an error for.  This is a really bad and confusing developer experience for the library consumer.

**Comment by RoboPhred** [comment]
This behavior was previously seen using unions to add the additional properties, but apparently unions spread out over everything  and the excess property check goes out to lunch over it.

Howeer, in this case, there are only a few possible types that Discriminated can be:

```ts
{
  foo: number;
  discriminant: undefined;
}
{
  foo: number;
  discriminant: false;
}
{
  foo: number;
  discriminant: true;
  requiredFunction(): void;
}
```

The type in the issue matches none of these, but TS still passes it and thinks it recognizes the requiredFunction() property despite the type not structurally matching that possibility.

**Comment by RoboPhred** [comment]
This actually seems unrelated to inheritence, just the presence of a common property triggers the issue

[Common 'foo' property](https://www.typescriptlang.org/play?ts=5.0.4#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgeXXTgG8AoOOdCCALjiQFcBbAIzQG4K4ATBAZ2xQEzZJhQB+elgA2-YFwC+ZMqEixEKNFlwEkpbtToMW7KF0p9Bw0UnEx6MKIwXcowAI6ME7ngDFGJGwYBAgkAAoASnoANwgEHiUVGABPMDwAEQEhETFUHjgAXgIiOAAfPS4yAHpquAA5CDg0KGgAGmaYtBSYAAtkAHM4CABrMmww-nhUKcJ0eizrXLt8ooNKI3oAFgAmMmUauoBRKFaofjhMC7VgYOAeDoADdy8fe4CgkLDHhgh4fnS2AQ6AQ93Gk2mwFmSAW2RseXua3IGxo2x2bW4VhytnsjmcwH2KlqcAAQgBVADi9EazVO7V4cOW9kQFyQfzgANuwNBDzgrEY8AAKgBlS7YXBgGAXF7eXwfYKhfRXOAxTAyBLgpBTOAzGAAdQQfQgAsW2LEKFhSxxq2KyKoqLguwxlBlb38gQVYXoUSKAD5SMpFEA)

**Comment by RyanCavanaugh** [comment]
The reply in the other issue apply equally to this one. TypeScript has a structural type system and also warns you on certain excess properties when it can detect that they're definitely excess, but that isn't hit in this case.

**Comment by fatcerberus** [comment]
The long and short of it is EPC[^1] is there to try to catch some mistakes but you shouldn't be relying on it to enforce invariants as it's not nearly that comprehensive.  You would need exact types (#12936) to meaningfully enforce this.

[^1]: Excess Property Check

**Comment by guillaumebrunerie** [comment]
Let me also add that if the "discriminating property" is optional, then it's not a discriminating property at all anymore. So what you have is not a discriminated union, and has all the drawbacks of non-discriminated unions.
