### ISSUE TITLE
A `Constructor` type

### ISSUE THREAD

**Issue by Malix-Off** [microsoft/TypeScript#54428]
# Suggestion

## 🔍 Search Terms

Class, Constructor, Function, lib

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

A `Constructor` type

## 📃 Motivating Example

There are currently a lot of elements being typed as `Function` instead of `Constructor` (see #implementation bellow)

## 💻 Implementation

https://github.com/Malix-Off/oop-utility/blob/ab0b593f0a7039582ea2876a6eb1c980f4262fd4/src/constructor.ts#L1

```ts
export type Constructor<T extends Object = object> = new (...args: any[]) => T;
```

**Comment by jcalz** [comment]
This will be declined.  TS doesn't add new utility types anymore unless they are required for emitting declaration files.  See [this comment](https://github.com/microsoft/TypeScript/issues/51841#issuecomment-1344953135) on #51841 and the things to which it links.

**Comment by MartinJohns** [comment]
Also a duplicate of #41656 / #20256.
