### ISSUE TITLE
Allow overriding the return type of an overridden method

### ISSUE THREAD

**Issue by Malix-Off** [microsoft/TypeScript#54427]
# Suggestion

## 🔍 Search Terms

Override, return

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow overriding the return type of an overridden method

## 🧪 Example

[Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAKYCcCmA7ALtA3gKAJAFsk0ALAewBMAKASgC5oI0EBLFAcyz12TQFcEU0AERCA3HgC+2KdlCQYAYWLMQ5aEgAeaVORjxk6TrlIA3JAhbkk0QiQo16KXvgBG5o7gD0AKmh+AeoFBXNC+uLiwCKQADuZoAJ7QAOS2ZORJ0KzQCbHJSirpmTAopBjyzGwoYC4g1mik2cTWEGCE0NFRsQgJmYIukHXxuUn6qGhJAHQhYeEAKkPWSTTQALwAfNBOruYZzMWl0OWV1bXZDTmLy+sMTKxsk9PQ4XMLyVtuCLv7ZVAVVTV1c6vJKMFjsSaUABMABYAIwANmo0082C4PH4ggADOJcFIpEA)

```typescript
class Parent {
	method(): string {
		return "";
	}
}

class Child extends Parent {
	override method(): number {
		/*   ^^^^^^
		 * 		Property 'method' in type 'Child' is not assignable to the same property in base type 'Parent'.
		 * 			Type '() => number' is not assignable to type '() => string'.
		 * 				Type 'number' is not assignable to type 'string'.(2416)
		 */

		return 0;
	}
}

```

**Comment by Malix-Off** [comment]
#54426

**Comment by jcalz** [comment]
Looplicate of #54426, see comment

**Comment by jcalz** [comment]
Looplicate of #54427, see comment

**Comment by Malix-Off** [comment]
> Looplicate of #54427, see [comment](https://github.com/microsoft/TypeScript/issues/54426#issuecomment-1565812968)

Disagreed.
Although both of these issues are referring to an update on the current implementation of method overriding, they are not referring to the same part of it.

> In what way is this currently not allowed?

No

> An actual example would be nice.

Absolutely.
I updated https://github.com/microsoft/TypeScript/issues/54427#issue-1729065200 to feature one.
Thanks

**Comment by MartinJohns** [comment]
> > An actual example would be nice.
> 
> Absolutely. I updated [#54427 (comment)](https://github.com/microsoft/TypeScript/issues/54427#issue-1729065200) to feature one.

Can you provide an actual real use case for this request? I don't see how this would desirable, it would make type safety only worse. Keep in mind that a `Child` can be assigned to a `Parent`, so it's possible to call it typed via `Parent`, which says the return type is `string` (while the implementation of `Child` returns `number`).

**Comment by Malix-Off** [comment]
@MartinJohns do you think it should only allow covariant types?

**Comment by MartinJohns** [comment]
I'm not happy with that either, but I can see some reasoning behind that. But a completely different type? That'll just make it worse.

What's your argument and actual use case to allow this? You didn't fill in the "motivating example" and "use cases" sections of the issue template.

**Comment by Malix-Off** [comment]
> I'm not happy with that either, but I can see some reasoning behind that. But a completely different type? That'll just make it worse.
> 
> What's your argument and actual use case to allow this? You didn't fill in the "motivating example" and "use cases" sections of the issue template.

Honnestly, I thought it would be something I could want after encountering #54426.

Right now I do think by default, TypeScript should allow covariant types for overriden methods

**Comment by Malix-Off** [comment]
@MartinJohns what?

**Comment by jcalz** [comment]
TS *does* allow overrides to narrow the return type. Covariant return types are already supported.  I’m not really sure what this issue is asking for: looks like something either unsafe or something already supported.

**Comment by fatcerberus** [comment]
Yeah, the example given in the OP isn't safe.  `extends` is supposed to create subtypes, but if the compiler allowed that example you wouldn't be able to safely call a `Child` instance through the `Parent` type because the method would return the wrong type at runtime.

**Comment by MartinJohns** [comment]
> @MartinJohns what?

I've asked twice for an actual use case, but my request has been ignored both times. That's why the thumbs down. 🤷‍♂️

**Comment by jcalz** [comment]
https://github.com/microsoft/TypeScript/issues/54426#issuecomment-1566158058

**Comment by Malix-Off** [comment]
@MartinJohns I answered you that

> Honnestly, I thought it would be something I could want after encountering https://github.com/microsoft/TypeScript/issues/54426.

There is no other use case I have been through, although I know Java have been allowing covariant return types for overriden methods

**Comment by fatcerberus** [comment]
Covariant returns are already allowed:
```ts
class Parent {
	method(): string | number {
		return 0.5 > Math.random() ? "choo" : 777;
	}
}

class Child extends Parent {
	// ok, narrower return type allowed
	override method(): number {
		return 1206;
	}
}
```

What's *not* allowed is returning a completely unrelated type from the overridden method, because that would mean `Child` wouldn't be assignable to `Parent`, and thus not a valid subtype (see: Liskov substitution principle, etc.)

**Comment by Malix-Off** [comment]
Okay then I agree on letting it stays that way.
Have a great day y'all.
