### ISSUE TITLE
Allow overriding parameters of an overridden method

### ISSUE THREAD

**Issue by Malix-Off** [microsoft/TypeScript#54426]
# Suggestion

## 🔍 Search Terms

Override, parameters

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Allow overriding parameters of an overridden method

## 🧪 Example

[Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAKYCcCmA7ALtA3gKAJAFsk0ALAewBMAKADwC5oI0EBLFAcwEosBfbX7UJBgBhYsxDkAjNCTU0qcjHjJ0WPKQBuSBC3JJohEhRr0UAV3wAjbVxy5cAegBU0VwD0PnvLmgv7sBFIAB200AE9oAHJDMnJI6FZocJCo0XEpeOYYFFIMIWY2FDBLEH00UiTifQgwQmggwJCEcISUaEtIMrCUyOVUNEiAOm9faHtcABVu-UiTaHMrG2gAXgA+aA1SZjiE7NzofMLi0qSK5Jm5xhZ2LjWNrbjh+1HxyemYUgAzesRaom0YJFqPEwChyFFgQdkK1gKR8EEwGhmCUkE8fH5XlMeldWGxMns8lACkUUacktMogtrAghpQAEwAFkkADYOCMnA48Lx+IIoNA0hI6TI5AolIh+mpcJptLp9DFjHQGExcQAaaBheg4m6SxwudyeDzssa4ALBUIRaJEWKZNrnVJiQX4+b7Q4kk7lSrVP71Rrm1rtTrknp9dBDI3jLEXRVathqjVK66cFbrTbbJ05QkQYnHMpnCmzaPK7V3VOPelM1nszm4bnYIA)

```typescript
class Parent {
	method(x: string) {}
}

class Child1 extends Parent {
	override method(x: number) {
		/*   ^^^^^^
		 * 		Property 'method' in type 'Child1' is not assignable to the same property in base type 'Parent'.
		 * 			Type '(x: number) => void' is not assignable to type '(x: string) => void'.
		 * 				Types of parameters 'x' and 'x' are incompatible.
		 * 					Type 'string' is not assignable to type 'number'.(2416)
		 */
	}
}

class Child2 extends Parent {
	override method(x: string, y: string) {
		/*   ^^^^^^
		 * 		Property 'method' in type 'Child2' is not assignable to the same property in base type 'Parent'.
		 * 			Type '(x: string, y: string) => void' is not assignable to type '(x: string) => void'.(2416)
		 */
	}
}

```

**Comment by Malix-Off** [comment]
#54427

**Comment by jcalz** [comment]
Looplicate of #54427, see [comment](https://github.com/microsoft/TypeScript/issues/54427#issuecomment-1565812861)

**Comment by Malix-Off** [comment]
> Looplicate of #54427, see [comment](https://github.com/microsoft/TypeScript/issues/54426#issuecomment-1565812968)

Disagreed.
Although both of these issues are referring to an update on the current implementation of method overriding, they are not referring to the same part of it.

> In what way is this currently not allowed?

No

> An actual example would be nice.

Absolutely.
I updated https://github.com/microsoft/TypeScript/issues/54426#issue-1729064272 to feature one.
Thanks

**Comment by fatcerberus** [comment]
> > In what way is this currently not allowed?
>
> No

That’s not a yes/no question…

**Comment by Malix-Off** [comment]
> That’s not a yes/no question…
> It reminds me of that “Q: how many X do you want? A: yes” meme. 😄 

Lol yes sorry, I read it "in **t**hat way", my bad.
Check the example tab in https://github.com/microsoft/TypeScript/issues/54426#issue-1729064272

**Comment by jcalz** [comment]
My “looplicate” comment was meant to be humorous (hint: that’s not a real word) but I see the joke failed. Oh well, I’ll never get a job as a comedian.

But still: was it really necessary to file two issues in immediate succession about two parts of the same thing? Now we get to have two nearly identical conversations. 

To wit: in both of these you’re either asking for something already supported or something unsafe. In both cases the current behavior is stable and unlikely to change.  In both cases it’s not clear what the motivation is: *why* do you want to be able to make subclass methods completely unassignable to superclass methods? Breaking subtyping intentionally would need a fairly convincing argument to be considered… but I don’t see one here.  It’s like saying cars shouldn’t warn when the driver isn’t wearing their seat belt with the motivating example “I want to drive without wearing a seat belt”.  The answer’s going to be “no, sorry; consider wearing the seat belt or using a `//@car-ignore-error` directive no lawsuits kthxbai”

**Comment by fatcerberus** [comment]
> My “looplicate” comment was meant to be humorous (hint: that’s not a real word) but I see the joke failed.

Don't worry, I got the joke at least. (though admittedly it took me a good minute 😅)

**Comment by Malix-Off** [comment]
> My “looplicate” comment was meant to be humorous (hint: that’s not a real word) but I see the joke failed. Oh well, I’ll never get a job as a comedian.

Whoops, my bad, I thought you thought the two issues were in a kind of "recursive duplicate" state

> was it really necessary to file two issues in immediate succession about two parts of the same thing?

Maybe not, indeed.
I thought that there is a different debate for each, may be wrong, my bad if it turns out being true.

> something already supported

Ah? I don't find any way to do it.



Also, the "Allow overriding parameters of an overridden method" concept is an existing thing in some OOP languages such as Java.

**Comment by jcalz** [comment]
> I don't find any way to do it.

*Safely* overriding methods with *contravariant* parameters is already allowed:

```ts
class Child1 extends Parent {
  override method(x: string | number) { } // no error
}

class Child2 extends Parent {
  override method(x: string, y?: string) { } // no error
}
```

The thing you're asking for is demonstrably unsafe:

```ts
class Child1 extends Parent {
  override method(x: number) { console.log(x.toFixed());  }
}

let parent: Parent;
parent = new Child1(); // should be safe but isn't
parent.method("abc"); // RUNTIME ERROR, x.toFixed is not a function

class Child2 extends Parent {
  override method(x: string, y: string) { console.log(y.toUpperCase()) }
}
parent = new Child2(); // should be safe but isn't
parent.method("abc"); // RUNTIME ERROR, y is undefined
```

[Playground link](https://www.typescriptlang.org/play?ts=5.0.4&ssl=17&ssc=1&pln=16&pc=4#code/HYQwtgpgzgDiDGEAEApeIA2AvJBvAUEkqJLAsgMogBmEAKgBYCWwA5gIIYBOEIAJgE8KAVxgwA9lwAuEPnnyEiSeBhBQoSAAogewKfKVLIUhuL4AKAB4AuJFClcWrAJR4kAX0VFPX5avVIAMLMGHwAjEgQljLAfBrauvoEhkTiAG4QXI58yMamFjZ2Dk5IAD7EwmAARpmuuB6+PoYqahrBTKEATJHRELHxOn1JvqkZWUw5SHlmVrb2jmwANEgCAPxzxWx1DYZNDYok0HCISACqwFA09MxsmlzizFVMMnwAYpLsAEq8UOLABkoWgEEkMAYZpgUNgsXG5PLsFM1-G0QuEejE4lpBnowUp0plsrkICYZoVgJUalxtgB6KmRLKSEaAv6-DAQAB0GHErCsbKk4leTEssnMzmcjLhSj2RFZ+jgiVsIL0AG4EUo5aCALzECAAdyCKLCIqVSBpdPuXCQfGEyD5UyJ+SQLHg4jAcCkTCeGGeAl8DgEOKI6r0bIh5gARCAqvAw2LdsoQFJ4AwkOYIHVGc6LuJWRyuanXKbLLz+YLZI6NMBxPoQEhqMJgPB3X9GgpfEDkR0+N0ouiBokA0g8eNJqHCvMnMsBFCnNtMyz2ZzuQJi6cxJlAmoICLXBLvL4g-otcBdfrO50jSbafjJJbrUhbRDHQ2XW6PR1vb6uP7kikDyH7TMEZRjGjTxomyb5gOc7ZgueZppeKzlkg9Y5NQLCyC2iieO4QA)

TS does allow some unsafe things, indeed it allows *covariant* parameters in method overrides, which are also unsafe. But you're asking to add *new* unsafe things and haven't presented anything resembling a compelling reason to do so.  

> the "Allow overriding parameters of an overridden method" concept is an existing thing in some OOP languages such as Java.

No, Java does not allow that.  It allows *overloading* methods, which is different.  The method in the parent class would still be callable on an instance of the subclass, if you pass in the right arguments.  But even if you were right about this, it wouldn't be sufficient to justify adding the feature to TypeScript.  For that, we'd still need to see some compelling TypeScript-specific use cases for it. 

What are these use cases?

**Comment by jcalz** [comment]
TS cannot support multiple overload implementations, so that will not happen.  But there's no need to do that; if you actually want overloading, you can do it with a single implementation that checks its inputs.  And even that isn't needed, you can just use unions in the input parameters.  TS already supports overriding with wider parameters, as I mentioned earlier. Again, for your example it looks like

```ts
class Child1 extends Parent {
  override method(x: string | number) { } // no error
}

class Child2 extends Parent {
  override method(x: string, y?: string) { } // no error
}
```

Doesn't that meet your needs?  You check inside the method what `x` is, or if `y` is defined, and then move on from there.  Without needing the TS language to be changed.  

I don't think I'll engage further here if you don't mind.  You should probably close this feature request, or you can leave it open and it will most likely be declined.  Either way I think I've said everything I can think of multiple times now, so I'm just adding noise that isn't helping anyone.  Good luck!

**Comment by Malix-Off** [comment]
I guess I will find my way anyway, thanks for your time!
