### ISSUE TITLE
JSX files not correctly accounted for in MSBuild tasks

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5443]
From @Christopher1065 on Gitter at [October 28, 2015 4:42 PM](https://gitter.im/Microsoft/TypeScript?at=56315d516afab45a2ce6412c):

> This seems like a bug but not sure if it is in msbuild targets for tsc or tsc itself. I have a single server.tsx file and it outputs to server.jsx file including a source map. However in the msbuild output I see the reported "GeneratedJavascript" collection includes server.js and server.js.map. Later in the build chain this causes an error because of the missing files.

@paulvanbrenk claims it's a bug in the way the msbuild task works.

**Comment by paulvanbrenk** [comment]
I checked in a fix, which will be released with 1.8
