### ISSUE TITLE
Generics get broken when inferred from a function with an implicitly typed parameter

### ISSUE THREAD

**Issue by mattersj** [microsoft/TypeScript#54438]
# Bug Report

### 🔎 Search Terms

generic, function, parameters, unknown, never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Generics`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/JYOwLgpgTgZghgYwgAgKLmGAnsg3gKGSOWABMAuZEAVwFsAjaAbkOJDlokoGcwpQA5iwC++fNgAOKAGIgAPABUAfMgC8yABQS4UDt0oAlCAgD2UUnN78QAgDTJqIANYgTAdxBKAlGpUKA2gC6LPikxgA2OigwjghgwCYgyJC8ivYA0sgQAB6QIKTcyE4QWCYwyMoaMCCUsopK9sVYlOlelAohKWAaGj6qKkHIcIXo8dhB9gDkZJNeTMgA9AvIAMLDKADEAIyU2rq0hVEgk2AO3BCkyICg5OIQvD17eobGZhZWgvaOLu6efQOBQxGGHGgSm7E4s3mS1W62QGwATLsdHohlAUNRzpc3JgABZDZJYKTIRiCLLZCThYAITDhHDcKTUmDAC7XW73LTIg6UL6uDx-ZCDYZoYFYCbIaakSGLZZrc5wgDMSP2hzRZxZ2LAeLgyFIwBgMGgEHABKJNy6D053H5gqBY1FoPFMzm0phco2ABYlSiomqsbihklgLQKVTMCaIPYBEboFSSIU5DyfvYQBAAG7QFSAGXJ8EA)

### 💻 Code

```ts
interface Entity {
    id: number;
    name: string;
}

type Fn<T> = (params: Record<string, unknown>) => T[];

declare function test<T, K extends keyof T>(fn: Fn<T>, key: K): T;

// Case #1: params aren't used, generic is `<Entity, 'id'>` ✅
test(() => [] as Entity[], 'id');

// Case #2: params are used with a type being explicitly specified, generic is `<Entity, 'name'>` ✅
test((params: Record<string, unknown>) => [] as Entity[], 'name');

// Case #3: params are used with a different type, generic is `<Entity, 'id'>` ✅
test((params: unknown) => [] as Entity[], 'id');

// Case #4: params are used with an implicit type, generic is <unknown, never> ❌
test((params) => [] as Entity[], 'id');
      ^ but it's inferred properly as Record<string, unknown>
```

### 🙁 Actual behavior

In the case **4** a generic gets broken and has a type `<unknown, never>` instead of `<Entity, 'id'>` as shown in the previous examples.
There's nothing wrong with an implicit type for `params` since it's already automatically inferred as `Record<string, unknown>`.

### 🙂 Expected behavior

The case **4** should work exactly the same as the previous ones and missing type annotation in parameters should have no impact on the inferred generic type.

**Comment by jcalz** [comment]
Duplicates the still-open part of #47599.

**Comment by fatcerberus** [comment]
Thanks @jcalz, I suspected this was related to contextual typing but wasn't confident enough about the cause to jump in.  I thought it might just be a circularity (i.e. `T` infers from the function argument, but the function itself is contextually typed by `T` -> cycle detected -> default to constraint)

**Comment by mattersj** [comment]
@jcalz Thank you for clearing this up, it makes sense now. I'm going to close this one as it already has a bunch of duplicates out there.
So, for anyone coming up here the best solution is to explicitly add a type annotation for your parameter like this: `(params: YourType) => ...` or get rid of your parameter at all.
