### ISSUE TITLE
`typeof` explicitly-typed value isn't equal to its type

### ISSUE THREAD

**Issue by RichDom2185** [microsoft/TypeScript#54431]
# Bug Report

### 🔎 Search Terms

typeof, type erasure

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `typeof` and type erasure

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.4#code/PTAEBUE8AcFMBNQEMDOoBEALWAbHB7dUAHwwHd8AnHedAKAGN8A7FAF1DdnYGU3KAlswDmALgzY8hEuSo0iAXgm4C6ANx06ICDATI0WFYTptdEbmyhxQS03HwAzThb6CRGoA)

### 💻 Code

```ts
// Typed as "hello" | "world"
const testString: "hello" | "world" = "hello";

// Typed as "hello"
type TestType = typeof testString;
```

### 🙁 Actual behavior

`TestType` is typed as `"hello"`, even though we are using `typeof` in the _type_ context and not an _expression_ context.

### 🙂 Expected behavior

It should be equal to `"hello" | "world"`, which is the type we explicitly assigned to `testString`. I don't think type erasure should affect the inferred type when using `typeof` as it is being called in the _type_ context. Even when called in an _expression_ context (which I think should be similar to JS behavior), `typeof testString` would give `"string"`, not `"hello"`.

**Comment by MartinJohns** [comment]
This working as intended. Assigning narrows the type of the variable. If you don't want this behavior, you can opt-out using a type assertion: `const testString = "hello" as "hello" | "world";`
