### ISSUE TITLE
Adds the "length" attribute for the literal of the object type

### ISSUE THREAD

**Issue by MrA380** [microsoft/TypeScript#54430]
# Suggestion

## ⭐ Suggestion
I was creating a generic type called "set" (which is used to limit the number of attributes in an object), but object types do not have a "length" attribute like arrays, making this impossible. If you can, add a "length" attribute to the object.

This is my vision:
```ts
type set<N> = { [Key: string]: any } & { length: N };
```

## ✅ Viability Checklist
My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by fatcerberus** [comment]
The fact that objects don't have a `.length` like arrays is a JavaScript thing; adding such a property to them would change runtime behavior which means this doesn't mean *any* of the viability guidelines.

**Comment by MrA380** [comment]
So, what's the solution?

**Comment by MrA380** [comment]
I'm know.

**Comment by xiBread** [comment]
Then why open this issue and check the boxes?

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template (motivating examples and use cases).

If you want to limit the amount of properties an object can have, then TypeScript is not a good fit for you. There's no mechanism in the language that supports this, and I can't really see this as a compelling feature. The closest feature (and probably even a requirement) would be Exact Types (#12936).
