### ISSUE TITLE
Template literal type check to `symbol` is loose

### ISSUE THREAD

**Issue by TomokiMiyauci** [microsoft/TypeScript#54433]
# Bug Report

### 🔎 Search Terms

template literal, symbol, #19666

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for
  entries about all

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3lAXPNAngLYBGSEA3AFCiSwLLpYl6GnnwA++GMAligDm1WtDiJUmRHgDeAXy75iZSjXBiGkrMFlyR6+hKbwQeAK4oA1iiQB3FNSqMpAfSjwAvPAAGAEhlQct4U8AD0ofAAojAwSDBOWvAuJJ4+-iRBIeFRMXEJxi5gqX4yYJlhEdGx8c5YLsDF-sDl2QDylvmuCF4lIC0R7VRAA)

### 💻 Code

```ts
declare const a: symbol;
declare const b: symbol | string;
declare const c: {} | symbol;
declare const d: {};
declare const e: unknown;

const _a = `${a}`; // Error
const _b = `${b}`; // Error
const _c = `${c}`; // Error
const _d = `${d}`; // Ok
const _e = `${e}`; // Ok
```

### 🙁 Actual behavior

No type error if `symbol` is implicitly included.

### 🙂 Expected behavior

Type error on `unknown` and `{}`.

**Comment by Mateusnasciment** [comment]
In TypeScript, symbols are a unique data type that represents a unique identifier. When you try to interpolate a symbol into a string using template literals, it results in a type error because symbols are not implicitly convertible to strings.

**Comment by TomokiMiyauci** [comment]
What do you think about providing like `strictTemplateLiteral` as a compiler option?

**Comment by RyanCavanaugh** [comment]
That seems extremely niche. I have seen appetite for a broader compiler flag that covers any implicit string coercion at all, which I think would be more palatable.

**Comment by TomokiMiyauci** [comment]
I agree with you!

**Comment by Josh-Cena** [comment]
@TomokiMiyauci You may be interested in https://typescript-eslint.io/rules/restrict-template-expressions/
