### ISSUE TITLE
"this" not correctly assigned with spread operator

### ISSUE THREAD

**Issue by Dinhero21** [microsoft/TypeScript#54434]
# Bug Report

### 🔎 Search Terms

spread operator, this

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `this`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play#code/MYewdgzgLgBCBGArApsWBeGBvAUDGAdEbvvgObKwAUAlNnqfgE6UCuTYMUAFgJYQN8AXwA0gmKDBRkADygAuGAHJeYMMiZKGQmAEMIE8NDH5J0uYqUhW0zTh37DkKDhyToT8xjhJUUAhRQtARmsi4A9OGMAHoA-K7uIAA2yARJIGRUoXI0QA)

### 💻 Code

```ts
const object = {
  ...{
    get () {
      return this
    },
    context: 'inner'
  } as const,
  context: 'outer'
} as const

const context = object.get().context
//    ^?

console.log(context)
```

### 🙁 Actual behavior

The type of context is `'inner'`

### 🙂 Expected behavior

The type of context is `'outer'`

**Comment by nmain** [comment]
It works if you make `get` generic in `this`:

```typescript
const object = {
  ...{
    get<T>(this: T) {
      return this
    },
    context: 'inner'
  } as const,
  context: 'outer'
} as const

const context = object.get().context
//    ^?

console.log(context)
```

I'm not sure if this is intended; I'm having trouble searching the issues for it as searching `"generic this"` seems to bring up many unrelated issues.

**Comment by fatcerberus** [comment]
Probably intentional; typing this correctly requires a polymorphic `this` which TS doesn’t do by default for performance reasons.

**Comment by RyanCavanaugh** [comment]
[Correct](https://github.com/microsoft/TypeScript/issues/54434#issuecomment-1568963349)
