### ISSUE TITLE
Wiki  incorrect example 

### ISSUE THREAD

**Issue by Zt0** [microsoft/TypeScript#54455]
# Bug Report

### 🔎 Search Terms

  I am reading about typescript and encountered incorrect example (in my opinion)
[Example](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-does-this-get-orphaned-in-my-instance-methods:~:text=or%20protected%20member.-,Why%20does%20this%20get%20orphaned%20in%20my%20instance%20methods%3F,-I%20wrote%20some)

### 🕗 Version & Regression Information

30.05.2023

### 🙁 Actual behavior

The method `someCallback` doesn't even called, and `this.x` prints 10, not undefined

### 🙂 Expected behavior

I think we can fix this example, or remove

**Comment by RyanCavanaugh** [comment]
I'm not sure what you're getting at. Try running this code in your browser console; it behaves as described

![image](https://github.com/microsoft/TypeScript/assets/6685088/19f56cd1-0bc8-466c-9b89-358094d9599c)
