### ISSUE TITLE
Broken emit with private field in class decorator

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/TypeScript#54465]
# Bug Report

### 🔎 Search Terms

private field, decorators, broken emit

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about decorators

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?useDefineForClassFields=true&module=7&ts=5.1.0-beta&ssl=15&ssc=1&pln=2&pc=1#code/FAMwrgdgxgLglgewgAgLYEMDWBTAItqBAJ3RmIAoQIAuZcgOkfSIHMBnW9CATwG0BdAJTIAvAD5kXbsIDewZAuRFsMMERTho8JMgAmBYqWwBhADbo2bADzHk2AB4xsEXW2QRsAdzqN6zdpw8AsLikjxi5PKK0ZjmlrTGADTIUdEKsPYJcWz4hCRkRMZITo6JqcjCyHJpigD0tcgAKgAW2MhwqAAOptiozjCkiCgIIMgwzXBuugjYbBAA5DBopE5E5QC+wJvAAAIYOLmGBeT2ohL29ADEIAgIgsBQ2cgAYrdV5de3tBBgqABG2CIomQAGYANxbYBAA)

### 💻 Code

```ts
function makeDecorator(fn: (...args: any[]) => any) {
    return function decorateClass<C extends new (...args: any[]) => any>(
        klass: C, 
        ctx: ClassDecoratorContext,
    )  {
        // The implementation of this doesn't matter
    }
}

@makeDecorator(x => x.#foo)
class Foo {
    #foo: number = 3;
}

```

### 🙁 Actual behavior

The generated code is syntatically incorrect with the error:

```
Unexpected token ')' 
```

This happens on the line, basically nothing is emitted after the `x.`:

```
    let _classDecorators = [makeDecorator(x => x.)];

```

### 🙂 Expected behavior

Functioning code should be emitted.

**Comment by Jamesernator** [comment]
> [Private fields aren't accessible outside the class body](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#:~:text=It%20is%20a%20syntax%20error%20to%20refer%20to%20%23%20names%20from%20outside%20of%20the%20class.) (it's a syntax error), which I don't think the decorator is part of.

If it's meant to be syntax error that was fine, my assumption was that given TS parsed it correctly decorators must still be in class scope.

**Comment by RyanCavanaugh** [comment]
Yeah, just to be clear, the bug here is that we're not issuing an error
