### ISSUE TITLE
Question: Is it possible to optimize the compilation process based on the user's browser?

### ISSUE THREAD

**Issue by kasajian** [Microsoft/TypeScript#5446]
I'd like to know if the following would be possible to do.   Similar to how html5test.com can detect what features your particular browser version supports, one can do the same with JavaScript.   Imaging that when a user goes to the web-site, first thing that's done is a javascript detection to see what capabilities she's got.   The test may take a few seconds, which means that after the detection is complete, their "support feature list" is cached on the server against their particular browser version, using the user-agent.   That means, any one else who visits the web site with the same exact user-agent string won't have to do the feature detection.   I don't know if that correlation can be made or not, which is partly why I'm asking this question.   If it cannot, I'd like some examples of why it won't work.

Now, assuming we can very quickly determine the browser's javascript compatibility level very quickly, we serve that user JavaScript that specifically compiled for their browser.   This would mean that TypeScript compiler would have to be invoked with specific settings indicating which features the browser already has, and which features need to be polyfilled.   So, technically some future version of Chrome that supports ES 7 won't require any polyfilling at all, for instance.

The TypeScript compilation output is cached and served to anyone else who has the same exact browser version.

In a real environment, simply running your website against dozens of browsers against browserstack.com, before going life, would create these caches so that in product, the compilation will rarely be done.   And if it's really rare, than one can completely remove the runtime compilation step when the browser type is unknown by serving that client a page where everything is polyfilled down to ES3.

This way, you don't have to specify what you're targeting, ES3, ES5 or ES6.   As we get close to browsers support ES6 natively, you're going to have a bunch of extra code in your JavaScript files that you're sending to the client that won't be used at all.   But you can't turn it off because you still want to support the 10% customers who are using some legacy browser still.

I wouldn't recommend AMD here because there's no reason to load many tiny javascript modules at runtime when they can all be concatenated into a single file before going live.

Thoughts?

**Comment by ivogabe** [comment]
I think this is probably out of scope for TypeScript. You can use [Microfill](https://github.com/ivogabe/microfill) to only load the required polyfills. Microfill doesn't check for ES3, 5, or 6 to provide the correct compiled version, but I think you won't get a big decrease in file size based on that.

**Comment by kasajian** [comment]
ivogabe, that's interesting.   I tried Babel and just to have the module system, added like 8K to my tiny little script.   That's huge if I have to load it multiple times on a single web page (imagine these are "ads" on someone else's web site, and they have to be small)

I would think that once browsers support ES6 modules, then there would be no polyfilling required.

okay, well thanks for the response.
