### ISSUE TITLE
No completions for generic object with string literal union types

### ISSUE THREAD

**Issue by jprestidge-nex** [microsoft/TypeScript#54464]
# Bug Report

### 🔎 Search Terms

* Autocompletion, completions, missing, generics, object, string literals unions, etc.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Generics

### ⏯ Playground Link

https://tsplay.dev/WGdLJw

### 💻 Code

```ts
type Test<
  T extends {
    example: "yes" | "no";
  }
> = T["example"];

const foo: Test<{ example: "" }> = "yes";
//                         ^^ <- No completions available here.
//                               As a string literal there should be concrete completions for "yes" | "no".

//                               The compiler does however recognize the correct type with type error:
//                               `Type '{ example: ""; }' does not satisfy the constraint '{ example: "yes" | "no"; }'.`
```

### 🙁 Actual behavior

There are no type completions hints for string literal unions inside generic objects.

### 🙂 Expected behavior

There should be type completion hints with the appropriate type variants. In the example above, with the completions should be `yes` and `no`.

**Comment by Andarist** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/52898

**Comment by jprestidge-nex** [comment]
That definitely is a worthy duplicate, sorry I couldn't find it before creating this 😞

Shall I close this issue?

**Comment by Andarist** [comment]
I'd close it - since it so closely relates to that other issue.

**Comment by jprestidge-nex** [comment]
Duplicate
