### ISSUE TITLE
Improve err message on call signatures

### ISSUE THREAD

**Issue by SpyrosSpiliopoulos** [microsoft/TypeScript#54469]
# Bug Report

This looks more like an improvement on the error msg produced here:

type FunType = {
  bla : string;
  (someArg : number) : boolean;
}

function goo(fn: FunType) {
  new fn(5);
}

### 🙁 behavior

produces an error msg like:
test.ts:xx - error TS2350: Only a void function can be called with the 'new' keyword.

thats a bit misleading non void functions can also be called with the 'new' keyword

### versions affected:
<=nightly

**Comment by RyanCavanaugh** [comment]
But that actually is the rule. Huh?

**Comment by fatcerberus** [comment]
Is there a good reason for this rule?  `fn();` is legal regardless of return type; if there’s going to be a restriction on `new`, it seems like that restriction should be “must have a construct signature”, not "must have `void` return type"—the latter seems arbitrary.

**Comment by RyanCavanaugh** [comment]
The rule is there to support ancient inference of JS "classes"
```ts
function fn() {
  this.myProp = 3;
}
const c = new fn();
```

**Comment by SpyrosSpiliopoulos** [comment]
ok but this JS class once instantiated with new, it is a callable that can actually return a value rather than just void. So why constraint it ? I think the error msg is misleading...

**Comment by SpyrosSpiliopoulos** [comment]
otherwise fn is constrainted to be non pure..

**Comment by RyanCavanaugh** [comment]
It's not misleading just because you don't like the rule it describes

**Comment by SpyrosSpiliopoulos** [comment]
Unless I am mistaken if you add the new keyword there it compiles so it works as I describe. The error msg is just misleading.

**Comment by SpyrosSpiliopoulos** [comment]
But whatever its minor we can live with it.
