### ISSUE TITLE
ES6 modules default exported function/class/generator name is not declared

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5447]
```ts
// function
export default function foo() {
}
export {foo}; // hello.ts(3,9): error TS2304: Cannot find name 'foo'.

// generator
export default function *foo() {
}
export {foo}; // hello.ts(3,9): error TS2304: Cannot find name 'foo'.

// class
export default class Foo {
}
export {Foo}; // hello.ts(3,9): error TS2304: Cannot find name 'Foo'.
```

```ts
// hoistable
export {foo}; // hello.ts(1,9): error TS2304: Cannot find name 'foo'.
export default function foo() {
}
```

http://www.ecma-international.org/ecma-262/6.0/#sec-source-text-module-records
http://www.ecma-international.org/ecma-262/6.0/#table-42

**Comment by WangJi** [comment]
is this fixed in `1.8`?

**Comment by sandersn** [comment]
Not yet. I haven't had a chance to look at it.

**Comment by sandersn** [comment]
It looks like [an earlier fix](41e39735e88301c38ca89e98e0cdfaa42d8301e0) prevents exported identifiers from being available to namespaces that have merged with the module in question. It doesn't take into account that `default` actually does introduce a local name.

**Comment by mhegazy** [comment]
@WangJi and @falsandtru can you give tonight's `typescript@next` a try.

**Comment by WangJi** [comment]
Tried on Version `1.8.0-dev.20151112`, still got the same warning.
And
```
export default class Foo{
}
``
is complied into 
```
exports.Foo = Foo; //instead of default
``

**Comment by sandersn** [comment]
This bug fix indeed only fixes the name resolution, not the emit. Although the emit is wrong for classes but not functions. I'll open a separate bug for the incorrect emit.

**Comment by sandersn** [comment]
And it only happens when the target is ES6, not ES5.

**Comment by sandersn** [comment]
Turns out the bug is already known: #5594
