### ISSUE TITLE
RequestInit.priority type

### ISSUE THREAD

**Issue by RafidMuhymin** [microsoft/TypeScript#54472]
# Bug Report

Type `RequestInit.priority` hasn't been typed yet, it should be `"high" | "low" | "auto"`. Chromium-based browsers support this feature since `v101`

Links: [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/fetch#:~:text=via%20an%20AbortController.-,[priority](https://developer.mozilla.org/en-US/docs/Web/API/fetch#:~:text=via%20an%20AbortController.-,priority,-Specifies%20the%20priority),-Specifies%20the%20priority), [CanIUse](https://caniuse.com/mdn-api_fetch_init_priority_parameter)

### 🔎 Search Terms

- init.priority fetch typescript
- RequestInit.priority typescript

### 🕗 Version Information

`4.8.4`, `5.0.3`, `5.0.4`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYUwLgxgFgFARFMYAOBnAXAekyAHgQwFtkAbEAOggHtDM4AaAAgG8BYAKEa8cPCioAm6RnAAKAeQDKAFQYdujZACcAllVVgAnsLgkqAdzmduAI0HbGAKUniAcuVRhVAOwDmK4JphtjXbI3JAxgF8MHx5bgBfAEp6DhiAbiA)

### 💻 Code

```ts
fetch("https://example.com/", {
    method: "POST",
    priority: "low",
    body: JSON.stringify({
      // ... data
    }),
});
```

### 🙁 Actual behavior

`RequestInit.priority` hasn't been typed.

### 🙂 Expected behavior

The type of `RequestInit.priority` should be `"high" | "low" | "auto"`.

**Comment by SevenOutman** [comment]
I've opened a PR microsoft/TypeScript-DOM-lib-generator#1572 for this
