### ISSUE TITLE
Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.

### ISSUE THREAD

**Issue by Ak-0024** [microsoft/TypeScript#54484]
![Screenshot 2023-06-01 145228](https://github.com/microsoft/TypeScript/assets/79638706/dc6b730c-878c-4490-89b7-33e74c5e05ce)
![Screenshot 2023-06-01 145120](https://github.com/microsoft/TypeScript/assets/79638706/ee6d61df-5776-44c3-a2da-e1504a5223c8)

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
