### ISSUE TITLE
Rename a TS file changes it into a JS file

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#54492]
# Bug Report

### 🔎 Search Terms

nodenext rename ts

### Reproduce

<img width="873" alt="image" src="https://github.com/microsoft/TypeScript/assets/5390719/61801eeb-4b50-47c6-8bf3-b371ad42e242">

change `b` to `c`

<img width="242" alt="image" src="https://github.com/microsoft/TypeScript/assets/5390719/a6823901-19e5-499c-b653-145e96043024">

b.ts becomes c.js, but it should be c.ts

**Comment by RyanCavanaugh** [comment]
@mjbvz is this our bug or yours?

**Comment by mjbvz** [comment]
@RyanCavanaugh The `rename` request from typescript returns a `fileToRename`. VS code then uses this to rename the file with the new name

https://github.com/microsoft/vscode/blob/7f4221a9553c32f79a894da9a58cf5a2bbb69123/extensions/typescript-language-features/src/languageFeatures/rename.ts#L87

Instead we likely also need TS to return the new file name with this response so we use the correct name here
