### ISSUE TITLE
Animation.currentTime is typed incorrectly in 5.1

### ISSUE THREAD

**Issue by jackfranklin** [microsoft/TypeScript#54496]
# Bug Report

### 🔎 Search Terms

- animation
- currentTime

### 🕗 Version & Regression Information

- This changed between versions 5.0.4 and 5.1.3
- I have also tested TS Nightly which has the same issue.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3&ssl=3&ssc=1&pln=3&pc=14#code/MYewdgzgLgBAHjAvDA3gXxgQwjArmAazBAHcwscBBMASwFtMobwAoFuAOmFwCceBTMFAAq9fkA)

### 💻 Code

```ts
const x = {} as unknown as Animation

x.currentTime // Inspect the type of this value.
```

### 🙁 Actual behavior

The type is `CSSNumberish | null`

### 🙂 Expected behavior

The type should be `number | null`. Taken from the [MDN currentTime page docs](https://developer.mozilla.org/en-US/docs/Web/API/Animation/currentTime):

> A number representing the current time in milliseconds, or null to deactivate the animation.

**Comment by bramus** [comment]
The type changed in web-animations-2 to `CSSNumberish` to cater for scroll-driven animations which have no notion of wall clock time.

https://www.w3.org/TR/web-animations-2/#the-animationtimeline-interface

> Returns the [current time](https://www.w3.org/TR/web-animations-1/#timeline-current-time) for this timeline or null if this timeline is [inactive](https://www.w3.org/TR/web-animations-1/#inactive-timeline). The value is expressed as a percentage for a [progress-based timeline](https://www.w3.org/TR/web-animations-2/#progress-based-timeline), or as a double in milliseconds otherwise.

**Comment by MartinJohns** [comment]
@bramus But that spec clearly states:

> This spec is not yet ready for implementation.

So isn't this change a bit early?

**Comment by bramus** [comment]
With [Scroll-Driven Animations](https://drafts.csswg.org/scroll-animations-1/) – which uses the adjusted type – set to ship in Chrome 115, parts of it have already been implemented.

**Comment by RyanCavanaugh** [comment]
Seems like we might have jumped the gun a little bit on this one, but I don't think it's worth it to flip-flop-flip now if this is where things are headed.

**Comment by bschlenk** [comment]
Sorry if this is the wrong place for a question, but what's the right way to get the number value if the type is CSSNumericValue? In the chrome console I can do `cssNumericValue.value`, but that doesn't exist in the types.

**Comment by brunnerh** [comment]
@bschlenk:
`value` is defined on the prototype of `CSSUnitValue` while most of the changed animation properties return `CSSNumericValue`. You would probably have to convert it first via `to`. For `Animation.currentTime` the draft says:

> The value is expressed as a percentage for a [progress-based timeline](https://www.w3.org/TR/web-animations-2/#progress-based-timeline), or as a double in milliseconds otherwise.

So maybe use `timeline.currentTime.to('percent').value`, not sure though. Probably depends on how/where the timeline is constructed. I would expect that for something like `document.timeline.currentTime` you would still be guaranteed to just get a double as that surely is not "progress-based" in way that can be expressed via percentages. It also would lead to breaking changes all over the place, otherwise.

**Comment by runarberg** [comment]
Has the change been reverted in Chrome? When I use this in Chromium 127 on Ubuntu (via snap) I just get a normal number as documented on MDN.

Scroll animations has been implemented by Chrome but using a different API which doesn’t touch `document.timeline`.

**Comment by bramus** [comment]
Testing in Chrome 127 (on Mac) I don’t see a problem:

- For a scroll driven animation, which is a progress-based timeline, I get back a `CSSUnitValue`
- For a time-based animation I get back a `double`

This is in line with [what the spec says](https://www.w3.org/TR/web-animations-2/#dom-animationtimeline-currenttime).

If you keep seeing incorrect behavior on your platform @runarberg, then please file a bug on https://crbug.com/new

**Comment by runarberg** [comment]
No this is the same behavior I see, however, like the original issue stated this is inconsistent with the type definition of `document.timeline.currentTime` which is always a `number` on all platforms and according to the spec (unless I’m mistaken) but typescript incorrectly says it is a `CSSUnitValue`.

**Comment by runarberg** [comment]
This is the same behavior I see. I didn’t realize that CSSNumberish means that `currentTime` returns a different thing depending on whether you call it on e.g. `document.timeline` or a scroll animation while both inheriting from the same interface.

In my honest opinion this is a bad spec. Or at best confusing. `document.timeline.currentTime` will always return a `number` and doing type narrowing only to please the type checker feels—and should be—unnecessary.
