### ISSUE TITLE
Argument of type 'this' is not assignable to parameter of type 'this'.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#5449]
This error also appears on generics with `this` to the `super` call (which is the real use case).

```ts
class A {
    constructor(bar: this) { }
    foo(bar: this) { }
}

class B extends A {
    constructor() {
        super(this); // Error
        this.foo(this); // Works
    }
}
```

**Comment by vladima** [comment]
btw, this is incorrect ES6 code since `this` is used before `super` call

**Comment by vilic** [comment]
I don't know why #2 is causing the same error but I did more test with the latest "next" release and found the actual issue:

```ts
class Test<TSample> {
    // this is the public property triggering the issue.
    public samples: TSample[];
    
    constructor() { }
}

class Sample {
    constructor(
        public host: Test<this>
    ) { }
}

class TerminalSample extends Sample {
    constructor(
        host: Test<this>
    ) {
        super(host);
    }
}
```

**Comment by mhegazy** [comment]
here is a simpler example:

```ts
class Base {
    constructor(a: this) { }
}

class Derived extends Base {
    prop: string;
}

var base: Base;
var derived: Derived;

new Base(base); // Error should be OK
new Derived(derived); // Error should be OK 
new Derived(base); // Error
```

**Comment by ahejlsberg** [comment]
The bug here is that the `this` type should not be in scope in the parameter list of a constructor (but it should be in scope *within* the constructor body). This is similar to how the `this` type is not in scope in static members.

**Comment by mhegazy** [comment]
@sandersn can you add the error check for release-1.7

**Comment by sandersn** [comment]
There is an existing error for this, it's just getting missed now. I'll figure out why.

**Comment by ahejlsberg** [comment]
@sandersn The issue is in the `getThisType` method. When the container is a constructor we should be checking that the node is in the body of the constructor (and thus not in the parameter list).

**Comment by vilic** [comment]
So I just made my use case dead? I don't understand why we need to disallow `this` type in constructor parameter list.

**Comment by ahejlsberg** [comment]
@vilic The use case was dead all along, we just weren't reporting an error properly. The compiler isn't equipped to handle `this` types in the static side of a class (which includes the constructor) and it would take a substantial amount of work to implement it. Is there a particular scenario where this would be useful?

**Comment by vilic** [comment]
@ahejlsberg It's actually quite like what I wrote, more specifically:

```ts
abstract class Test<TSample> {
    sample: TSample;
}

class SomeTest extends Test<SomeSample> {

}

abstract class Sample {
    constructor(
        public host: Test<this>
    ) { }    
}

class SomeSample extends Sample {

}

let someTest = new SomeTest<SomeSample>();
someTest.host.sample; // expecting type `SomeSample`.
```

Actually I ended up with another implementation, but I think the scenario should be reasonable. I didn't realize that constructors have different contexts than other instance methods, but certainly it could wait long enough if it's not something trivial to do.
