### ISSUE TITLE
no-default-lib reference is not persisted into declarations file

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#545]
Compile this code and generate a declaration file:;

``` TypeScript
/// <reference no-default-lib="true"/>
```

**Comment by NaridaL** [comment]
What should the behavior be when multiple files are bundled, not all of which `hasNoDefaultLib`? Error?

The relevant section https://github.com/Microsoft/TypeScript/blob/0ae42ea3def8cab3405e55927320d9dbc2ebfcd9/src/compiler/declarationEmitter.ts#L86-L103 confuses me somewhat, dont ///ref directives only make sense at the top of the file? Wouldn't the section make more sense outside of the forEach loop?
