### ISSUE TITLE
Add support for Background Synchronization API 

### ISSUE THREAD

**Issue by cawa-93** [microsoft/TypeScript#54509]
# Suggestion

Types for DOM do not contain information about interfaces [Periodic Background Synchronization API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API) and [Background Synchronization API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API)

Currently it show type error. [Playground](https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsI2QUxMgCgEoYBvAKBipik3xgCccBzVfB4NTGAXhmADuwVMhgRgAN1TNO6BgDoQOBlKg4A6nIDWy+U2AATMAG5ylaoOGimrdpwwR5AB2UYDqKAGVIUPSza4DAQARMw4yAC0ADaceJEQOAIgwUSm1PxCIoz+dlyO4NB+toEhYZExuPgRCUkppgC+QA).

## 🔍 Search Terms

Background Synchronization API 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by MartinJohns** [comment]
FYI, TypeScript **usually** waits until the API is no longer experimental and it's supported by at least two major browser engines. According to your links it's currently only supported by one.

**Comment by RyanCavanaugh** [comment]
Please use the lib template, when the feature is in multiple engines. Thanks!
