### ISSUE TITLE
empty class acts as "any" type: by design or bug?

### ISSUE THREAD

**Issue by Ziriax** [Microsoft/TypeScript#5451]
The following typechecks fine:

```
class Empty {
}

// From a strongly-typed point of view, this feels strange
var e1: Empty = "Strange";
var e2: Empty = 42;
```

This also compiles

```
class Foo {
	name: string;
	
	constructor(name: string) {
		this.name = name;
	}
	
	hello() {
		return "456";
	}
}

class Bar {
	name: string;
	
	hello() {
		return "123";
	}
}

var foo = new Foo("Jo");

// From a strongly-typed point of view, this feels strange
var bar: Bar = foo;
```

Is this by design?

**Comment by RyanCavanaugh** [comment]
Yes. Note that the empty type does *not* behave as `any` - it is a valid *target* for all assignments, but is only a valid *source* for assignments to other empty types:
```ts
var e: Empty, f: Foo;
f = e; // Error
```

TypeScript uses a [structural type system](https://en.wikipedia.org/wiki/Structural_type_system), see also:
http://stackoverflow.com/questions/22385775/typescript-type-check-failed-to-catch-wrong-assignment/22386927#22386927
http://stackoverflow.com/questions/32106253/why-does-typescript-implicitly-convert-between-unrelated-classes/32106416#32106416
http://stackoverflow.com/questions/28080106/typescript-type-confusion-variable-doesnt-mind-type/28080519#28080519

**Comment by binarez** [comment]
I'm using typescript in an educational situation and would find useful to have a stricter mode that doesn't allow this special case. Is there any way to disable this? I found a work-around : adding a dummy private member makes not empty (obviously).

    class Empty
    {
        private dummy : any;
    }
    
    let e : Empty = 2;
    
    Type 'number' is not assignable to type 'Empty'. Property 'dummy' is missing in type 'Number'.

I use '_' instead of 'dummy' in my lib (empty File class, it's really just a handle for the user, no attributes or methods) but you get the idea.

**Comment by RyanCavanaugh** [comment]
There isn't a way to disable this behavior.

**Comment by binarez** [comment]
Is adding one an option or is it too tied to the type system? I haven't read the type system docs you provided above, yet.

**Comment by RyanCavanaugh** [comment]
This isn't something we'd add an option for. It's a structural type system, so empty types are equivalent by definition.
