### ISSUE TITLE
Asynchronous Classes

### ISSUE THREAD

**Issue by codesculpture** [microsoft/TypeScript#54512]
# Suggestion

My suggestion is to enable the Typescript to support deeply on Asynchronous Classes by default as like dart does. 
This suggestion's intention is from dart that the language made the way very easily for asynchronous

So what am saying is it will took a long time to implement such thing in Js by tc39, so my idea is to just make it implement in directly typescript. Rxjs is one of the greatest library which has some classes such as `Observable` and `Subject` and to make it support natively by typescript.

## 🔍 Search Terms

Async in typescript
Asynchronous Programming
Async in ts
Async support in ts

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Adding Asynchronous Support to the typescript natively by implementing rxJs

## 💻 Use Cases

This would be great for implementing async features in typescript

**Comment by fatcerberus** [comment]
Putting aside the fact that I have no clue what you're really asking for, I can say this much: TypeScript is not going to implement any runtime features that aren't supported natively in JS.

Your suggestion most definitely *does not meet this guideline*:
> - [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

**Comment by codesculpture** [comment]
So

> Putting aside the fact that I have no clue what you're really asking for, I can say this much: TypeScript is not going to implement any runtime features that aren't supported natively in JS.
> 
> Your suggestion most definitely _does not meet this guideline_:
> 
> > * [ ]  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

Sorry it meet the guidelines, i just forget give tick those things

**Comment by MartinJohns** [comment]
I have no idea what you're trying to suggest that would meet the viability checklist. That you hardly filled out the issue template doesn't help.

- That you can use Observables? You can already, libraries like RxJS provide these types and the type information.
- That TypeScript provides its own implementation of observables? Definitely out of scope. TypeScript does not provide any library functions (except for downlevel emit).
- That TypeScript provides custom syntax for easier integration of observables? Again, definitely out of scope, TypeScript doesn't add new syntax.

TypeScripts goal is to only add type information (besides some choices in the past before this decision was made).

**Comment by codesculpture** [comment]
Ok i know that i messed up totally, but the thing i thought u would understand what am trying to say. That the thing i want is rxJs API's to be provided built-in by typescript. This is all i want. I think it was not applicable by this guidelines but whatever it would be great if those were builtin since asynchronous programming is much needed when u build things which beyond web. Because typescript and js is not used anymore only in web these days right..

**Comment by codesculpture** [comment]
https://github.com/tc39/proposal-observable 
I found a proposal regarding this at tc39 and probably it was dead

**Comment by MartinJohns** [comment]
I'm no member of the TypeScript team, but this suggestion is **definitely** out of scope. The only runtime functionality TypeScript brings along is for downlevel emit (supporting newer ES features in older targets). The code for this is either duplicated in each file or provided by the tslib NPM package.

I don't see the benefit of TypeScript providing it either. It would shift the focus away from what TypeScript aims to provide and fracture the whole ecosystem even further. And instead of just adding the RxJS package you'd have to add a TypeScript specific implementation package, so you're still stuck with an additional dependency. You'd gain nothing.

**Comment by RyanCavanaugh** [comment]
> So what am saying is it will took a long time to implement such thing in Js by tc39, so my idea is to just make it implement in directly typescript.

TC39 is the correct place for this to happen
