### ISSUE TITLE
Wrong extend relations for interface and Record

### ISSUE THREAD

**Issue by Arcrsr** [microsoft/TypeScript#54514]
# Bug Report

### 🔎 Search Terms
interface type Record condition

### 🕗 Version & Regression Information

- 3.3.3 is the last version with the correct type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230604#code/JYOwLgpgTgZghgYwgAgILIN4ChnIM4Bc+YUoA5gNxYC+WYAngA4oBCyAvJjvkXieVWpUGzZACUAjBzTIIAD0ggAJnnEQEAeyhKAPH1IgyAGmRwQ9AHzIA-MhIBXFEXgAbPBGFMUYgEzS28ooqapraevyGJmaWNnZQjsjOcG4edF7iAMzS6IEQyqpi6lq6+uQm9iAA1iAaAO4gVrYOTsiu7p6iYgAs-rIKecGFoSURxsgV1XUNsc2JrcntQA)

### 💻 Code

```ts
interface A {
  s: string;
}
type B = {
  s: string;
};
type R1 = A extends Record<string, any> ? true : false;
type R2 = B extends Record<string, any> ? true : false;
type R3 = A extends Record<string, unknown> ? true : false;
type R4 = B extends Record<string, unknown> ? true : false;
```

### 🙁 Actual behavior

R1, R2, R4 is true, and R3 is false

### 🙂 Expected behavior

R1, R2, R3, R4 is true

**Comment by MartinJohns** [comment]
This is working as intended. `interface` and `type` are not fully interchangeable.

Duplicate of https://github.com/microsoft/TypeScript/issues/42825. See also https://github.com/microsoft/TypeScript/issues/15300#issuecomment-332366024.

**Comment by Arcrsr** [comment]
Thank you for your help! It's my wrong understanding. I will close this bug issue.

**Comment by Arcrsr** [comment]
Solved
