### ISSUE TITLE
TS1479 Unable to import types from ESM package when moduleResolution is nodenext

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#54523]
# Bug Report

When I set `moduleResolution: "nodenext"` I see this error when I try to `import type` from a package:

<img width="842" alt="Screenshot 2023-06-04 at 11 33 29 PM" src="https://github.com/microsoft/TypeScript/assets/297678/bea274ed-46d7-46f0-9987-d9dcf0ee22e6">

Then I tried to switch to dynamic `import()` (even in for a type, not a runtime value), and get the same error:

<img width="724" alt="Screenshot 2023-06-04 at 11 30 19 PM" src="https://github.com/microsoft/TypeScript/assets/297678/213b8ce2-9540-4163-b92e-d146e630d959">

With _runtime value_, we can typically switch to dynamic `import()` to get around the problem. But with type imports, this is not getting around the problem.

Here's the error message for searchability:

<details><summary>error message (click to open)</summary>

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("wazum")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/Users/trusktr/src/project/package.json'.ts(1479)
```

</details>

Note that the error says

> Consider writing a dynamic 'import("wazum")' call instead.

which is what I've done with `import('wazum').Add`.

Adding `typeof` has the same issue:

<img width="726" alt="Screenshot 2023-06-04 at 11 39 25 PM" src="https://github.com/microsoft/TypeScript/assets/297678/a582a0a4-efed-4180-8ed4-e3186166264f">

Note, the `wazum` package is not the one currently at https://npmjs.com/wazum, but the one installed from my current GitHub fork:

```sh
npm install 'wazum@trusktr/wazum#simple-esm-dist-output'
```

### 🔎 Search Terms

typescript moduleResolution nodenext unable to import types

### 🕗 Version & Regression Information

Not sure when it regressed, if at all.

### ⏯ Playground Link

I am unable to provide a playground link because it doesn't seem to be configurable with the required options.

TODO: make a clonable reproduction.

### 💻 Code

```ts
type t = import('wazum').Add // error ts(1479)
```

Here's my tsconfig:

```js
{
	"compilerOptions": {
		// Compiler setup
		"target": "esnext",
		"module": "commonjs",
		"lib": ["ESNext"],
		"sourceMap": true,
		"outDir": "out",
		"moduleResolution": "nodenext",
		"esModuleInterop": true,
		"skipLibCheck": true,
		"forceConsistentCasingInFileNames": true,

		// Type checking
		"strict": true,
		"noUnusedLocals": true,
		"noImplicitReturns": true,
		"noImplicitOverride": true
	},
	"include": ["src/**/*.ts"],
	"exclude": ["out", "node_modules"]
}

```

### 🙁 Actual behavior

Unable to import types. 

### 🙂 Expected behavior

Expect there to be _some_ way to import types. `import type` imports are not regular ES Module imports, so it seems like `import type {...} from '...'` should just work, however I understand if it should match with the _runtime_ `import()` requirement for CommonJS output for consistency, but that's just not working either.

Plus using dynamic `import()` syntax for type imports is too cumbersome because some features are missing, f.e. the ability to import generic types:

<img width="532" alt="Screenshot 2023-06-04 at 11 56 31 PM" src="https://github.com/microsoft/TypeScript/assets/297678/5b0cdf03-424e-4d63-9544-6d33dc650aba">

So even if `import()` is what I should be doing (currently not working) `import type` would be better.

**Comment by trusktr** [comment]
A simple workaround is to put a `// @ts-expect-error` comment over the import:

```js
// @ts-expect-error moduleResolution:nodenext issue 54523
import type {SomeType} from 'some-lib'
```

**Comment by fatcerberus** [comment]
Known issue, see https://github.com/microsoft/TypeScript/issues/52529.  `@ts-ignore`/`@ts-expect-error` is the only current workaround.

**Comment by bmeck** [comment]
Seeing this as well after updating TS, workaround doesn't work as the type is still seen as non-existent.

**Comment by andrewbranch** [comment]
I think you can add the resolution-mode import assertion and ts-ignore the error that tells you not to do that.

```ts
import type { SomeType } from 'some-lib' assert { "resolution-mode": "module" }
```

This will become an import attribute and not illegal once we land support for import attributes.

**Comment by TheNoim** [comment]
> ```ts
> import type { SomeType } from 'some-lib' assert { "resolution-mode": "module" }
> ```

This is currently the correct way I guess:

```typescript
import type { SomeType } from 'some-lib' with { 'resolution-mode': 'import' };
```
