### ISSUE TITLE
Omitting a property on a discriminated union type

### ISSUE THREAD

**Issue by Trekiros** [microsoft/TypeScript#54525]
# Bug Report
When using Omit on a discriminated union type, the properties unique to each "branch" of the union type are lost.

### 🔎 Search Terms
Omit, union, discriminated union

### 🕗 Version & Regression Information
Tested on TypeScript 4.8.4 and on the nightly version (June 5th, 2023)

### ⏯ Playground Link
[demo](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230605#code/C4TwDgpgBAKlC8UDeAoK6oHpNQMIHsBbQ-AOyjACd9JLgBLCAZzQ1IENCIAuKJ4SvVIBzADQpW6bFAAi9JgGNBhIe2D5KkqKEi8AjOK3SAqqXoBHAK7QqNCHUYsMFamD29+gkeIC+UAD7IRjgExGRQAAqu9gzMWhxcHgJCYhLO0nKKyqrqms46PFAATIbpOKYW1pHRDnHOtmBFSV6pPhLSMAAW8lA9AG7sADb0ACYoCmT8UPgARgBW7rAIQc4JhQDkswvr4vnghQZaDYvr-UOj6yhtKAWwRcsA8irAADwwolDra+sAfO04XR6QNIA2GIw+M0swF60KYnXwlkGIygM2goNGKIgCnYliY0AA7tAyIMQNNnsAIMjgJ1oAAiNa0lx2OggcaTaFbXgwe6IVB7XTFXYYBpNT7sGYKEY7K5AA)

[Alternative demo](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230605#code/C4TwDgpgBAKlC8UBQVVQPTqgYQPYFt9cA7KABQCddILgBLCAZxTQG8piBDfCALikbAKdYgHMoAXyQtUmKABE6jAMbD8IzsAgATKAFdidEjKgAyKAAoTaKO1CR+ARgA0UMFTCP+g4WMnWoAB9bKHs+KAAmV3dqCO8hEXEpGwBKaTkYAAslKByAN04AGzptJGUSQShcACMAKy9YBFsTLh5+AHIa+vbnEzCnXpsYzw78opL2pCkkMNgIpoB5dWAAHhhXdtaIdoA+dKwsnKPiAuLtV2q9YFzrxkzcPULdauhTkqgX5U49RmgAd2gJEKICqyy0umAmWgACIttC3B4ILQQGUKtcuvwYPNEKw+uBwlETMM4lB2pxqsptD0MFgAMr3R66CAADyU6NIWKmQA) (a different way to do discriminated unions, which is also affected)

### 💻 Code
```
type T = {
    name: string,
    type: 1,
    prop1: string,
} | {
    name: string,
    type: 2,
    prop2: string,
}

type T2 = Omit<T, 'name'>
```

### 🙁 Actual behavior
T2 is interpreted as such by TypeScript:
```
type T2 = {
    type: 1 | 2;
}
```

And the following object is seen as invalid:
```
const obj: T2 = {
    type: 2,
    prop2: 'abcd', // "prop2 does not exist on type T2"
}
```

### 🙂 Expected behavior
T2 should be interpreted like this instead:
```
type T2 = {
    type: 1;
    prop1: string;
} | {
    type: 2;
    prop2: string;
}
```
And the object described above should be seen as valid.

**Comment by MartinJohns** [comment]
This is unfortunately working as intended. Omit does not distribute over the union. There are many implementations of a distributive omit out there, just search for it using "distributive omit". See also #54451.

**Comment by nurulakbaral** [comment]
You can create your own Omit with Distributive Conditional Types:

`type TheOmit<T, K extends string | number | symbol> = T extends any ? Omit<T, K> : never`

**Comment by MartinJohns** [comment]
@nurulakbaral Be aware that this version will **not** warn you if you mistype the property name, while the version suggested in #54451 will error, but only allows to omit properties common to all types of the union.

**Comment by nurulakbaral** [comment]
> @nurulakbaral Be aware that this version will **not** warn you if you mistype the property name, while the version suggested in #54451 will error, but only allows to omit properties common to all types of the union.

type TheOmit<T,  K extends keyof T> = T extends any ? Omit<T, K> : never

How about this?

**Comment by NagayamaToshiaki** [comment]
Current solution is tedious and how it works is unintuitive. Honestly this is reinventing the wheel. Needs official way to resolve.
