### ISSUE TITLE
Array reduce inference regression

### ISSUE THREAD

**Issue by alexroeber** [microsoft/TypeScript#54529]
# Bug Report

I have this code snippet:
```
export function reduceList<S, R>(list: S[], fun: (item: S) => R[]): R[] {
  return list.reduce((prev, curr) => [...prev, ...fun(curr)], [] as R[]);
}
```
In TS 4.9.5 it worked just fine, in TS 5.0.4 (Angular, can't go higher) it suddenly causes an error, inferring T as the return type, concluding R[] and T are incompatible. It didn't matter what I tried, I couldn't get it to use the third overload (U as the returned type)

### 🕗 Version & Regression Information

- This changed between versions 4.9.5 and 5.0.4

**Comment by alexroeber** [comment]
I could add, that the obvious fix `as R[]` actually works

**Comment by jcalz** [comment]
Could you please fill out the bug report template fully? Right now it's missing things and the stuff that is there doesn't seem to demonstrate what you're talking about (there's no error in that code, possibly because you already applied the fix you described in your comment?)

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by alexroeber** [comment]
Oh, don't be too ridiculous, the description is perfectly fine. Anyways, this was an issue with IntelliJ, so sorry about that. Should remain closed.

**Comment by fatcerberus** [comment]
> Oh, don't be too ridiculous, the description is perfectly fine.

It's not; Ryan's response above is canned specifically because if you don't fill out the whole template, the maintainers will ignore it.
