### ISSUE TITLE
Intellisense stopped working for JavaScript

### ISSUE THREAD

**Issue by TickedOffCodess** [microsoft/TypeScript#54535]
Type: <b>Bug</b>

Three weeks ago, this feature was working on my JavaScript projects.

Hover over an import > right click > select Go to definition >Error: No source definitions found

This is the full error: 
```
No source definitions found.

Source: TypeScript and JavaScript Language Features (Extension)
```

This occurs for all imports from node modules. This feature works for local files.

This is my `tsconfig.json`
```json
{
  "extends": "./node_modules/@fitbit/sdk/sdk-tsconfig.json"
}
```

These are the dev dependencies in my `package.json`
```json
  "devDependencies": {
    "@fitbit/sdk": "~6.1.0",
    "@fitbit/sdk-cli": "^1.7.3",
    "@types/chai": "^4.3.5",
    "@types/eslint": "^8.40.0",
    "@types/vscode": "^1.78.1",
    "@typescript-eslint/eslint-plugin": "^5.59.7",
    "chai": "^4.3.7",
    "eslint": "^8.41.0",
    "eslint-config-standard-with-typescript": "^34.0.1",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-n": "^15.7.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.32.2",
    "mocha": "^10.2.0",
    "typescript": "^5.0.4"
  },

```

These are the imports in my `index.js` file:

```javascript
import { HeartRateSensor } from 'heart-rate';
import { BodyPresenceSensor } from 'body-presence';
import { me as appbit } from 'appbit';
import { user } from 'user-profile';
import { vibration } from 'haptics';
import document from 'document';
import clock from 'clock';
import { updateClock } from './clock';

import * as deviceSettings from './device-settings';
import * as battery from './battery';
```

I tried the following things to try to troubleshoot:
- Reload window 
- Restart TypeScript server
- Restart computer 
- Uninstalled VSCode
- Reinstalled VSCode
- Create new settings profile 
- Install Insider's version of VSCode

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.37GB free)|
|Process Argv|--crash-reporter-id 18d77195-ed8d-48f4-9608-e9dde606bb01|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
go|gol|0.38.0
python|ms-|2023.8.0
vscode-pylance|ms-|2023.5.50
jupyter|ms-|2023.4.1011241018
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.78.9
vscode-typescript-next|ms-|5.2.20230603
vscode-readme-pattern|tho|1.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
pythongtdpathcf:30739705

```

</details>

**Comment by TickedOffCodess** [comment]
Any updates on this?

**Comment by andrewbranch** [comment]
These imports seem to be modules that are built into the FitBit operating system. There are no JS files that correspond to these imports on your system, so there’s nothing that Go To Source Definition could possibly show. Additionally, you don’t have any types for them installed, so there’s not even any .d.ts files that we can fall back to. It seems like you would need to use something like https://github.com/SergioMorchon/fitbit-sdk-types in order to have any definition info or intellisense.
