### ISSUE TITLE
Spread operator with `get` replaces accessor with the value

### ISSUE THREAD

**Issue by ackava** [microsoft/TypeScript#54548]
# Spread operator with `get,set` for ES2015 generates wrong code.

Consider the following...
```typescript
const a = {  ... {} , get time() { return Date.now(); }};
console.log(a.time);
console.log(a.time);
```

Generated ES2015 is,
```javascript
"use strict";
var a = Object.assign({}, { get time() { return Date.now(); } });
console.log(a.time);
console.log(a.time);
```

However, if you run the code, `a` contains time as a member as opposed to time should be a getter defined in Ecmascript.

So each time when you access `a.time` in generated javascript, it returns constant value where else in ES2021, `a.time` returns current time.

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=2#code/G4QwTgBCELwQ3hAdChBfANBA5gUwC4T4CWAtrgBQCUCEYBArmAHYQAiI+uSzA9gO7UA3BDRohQA

In following sample you can check the difference.
https://jsfiddle.net/72xfsz3k/1/

### 🙁 Actual behavior

Every time we access `a.time` it returns a constant value. And if you try to get `Object.getOwnPropertyDescriptor(a, "time")`, it returns value instead of `get`.

### 🙂 Expected behavior

`a.time` should not return a constant value.

### Solution
As per Ecmascript specifications, For spread operator, `Object.assign` should not be used, instead there should be a separate `assign` method which should copy property descriptors instead of values for the source.

```javascript
__assign = __assign || function(target, source) {
    var n = Object.assign({}, target);
    var all = Object.getOwnPropertyDescriptors(source);
    for(var i = 0; i < all.length; i++) {
        var descriptor = all[i];
        if(descriptor.enumerable) {
            Object.defineProperty(n, descriptor);
        }
    }
    return target;
};

// following code should be generated for ES2015
var a = __assign({}, { get time() { return Date.now(); }});
```

**Comment by RyanCavanaugh** [comment]
TS downleveling has a small amount of spec compliance deficit in some cases as a trade-off for smaller/cleaner generated code. If you need downleveling with closer compliance, you'll need to use a different downlevelr.

**Comment by ackava** [comment]
@RyanCavanaugh 

This is not about downleveling, the code generated gives wrong output.

1. The generated code is deviating from TypeScript design goal number 7.
2. Requested change is as small as `Object.assign(...)` to `__assign(...)`, and its cleaner code, same way async/await and generators are generated. The definition of `__assign` needs to be corrected.

Babel does generate correct code, have a look at https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=G4QwTgBCELwQ3hAdChBfCAaCBzApgC4QECWAtngBQCUCEYhArmAHYQAiIBeSLA9gHcaAbgho0woA&debug=false&forceAllTransforms=true&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.22.4&externalPlugins=%40babel%2Fplugin-proposal-object-rest-spread%407.20.7&assumptions=%7B%7D

**Comment by fatcerberus** [comment]
> This is not about downleveling

It is.  Downleveling = transpiling modern JS code for older JS engines, in this case downleveling a native spread to an ES version that doesn’t support it.  If you target e.g. ESNext, so that the spread is not downleveled, then you get the expected output.

> Babel does generate correct code

Then you’ll have to target `esnext` and use Babel for downleveling, as Ryan said above.

**Comment by ackava** [comment]
@fatcerberus 
1. Incorrect Downleveling again violates design goal 7. Please refer, https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
2. Using babel to generate correct code violates design goal 10.

The correction requested here is too small considering setting up babel + typescript in vscode to get correct working JavaScript.
