### ISSUE TITLE
(...args: never) => void signature throws an error in TS 5.1

### ISSUE THREAD

**Issue by anthonyma94** [microsoft/TypeScript#54543]
[Playground](https://www.typescriptlang.org/play?ts=5.0.4#code/GYVwdgxgLglg9mABAQwM4BNgAowgLYBciueARgKYBOANIgHQPKUDmqRY5AblQJSIDeAKEQjEEBKjgAbcnSlxmOfDwDcggL6DBaTFgCMPIA)

If I have a function with the signature of `(...args: never) => void`, TypeScript 5.1 now throws this error:
```
Argument of type '[]' is not assignable to parameter of type 'never'.
```

Previous versions of TypeScript allows me to call the function without any parameters.

Is this intended behaviour? I don't believe seeing anything in the changelog mentioning this.

**Comment by Andarist** [comment]
This is intended, see: https://github.com/microsoft/TypeScript/pull/52387
