### ISSUE TITLE
Bug Report: TS creates contravariant intersection when K extending keyof T assigned new type

### ISSUE THREAD

**Issue by RoboZoom** [microsoft/TypeScript#54547]
# Bug Report

### 🔎 Search Terms

T[K] assignment does not transform type of T

### 🕗 Version & Regression Information
Version: 4.8.4 to Present

This is bug became relevant when 4.8.4 released.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/C4TwDgpgBAEghgZwJIBEoF4oG8oEsAmAXFAsAE64B2A5lAL4DcAUEwMYD2lpUAZlfgHlKEAEIgk+DFAA8AFSgQAHsAiV8CWIlQA+ABRUwAV2DFZAbQC6AGjxES5KtQCUpqAB8ohtRD7DJ6bWwmKCgyCGBDMko8SiNgADpffF1dRScMQMV4ggx0TAInZkYWDi5gKAArdioAZTgAWzAAG2hMORsAaQVlVXUoAGsIEHYeKFkbAFVulTUNeGQUPWCoMDgwyhMxq2XV9eAOoeIO7ZDWAAtcJvx14gnLE-syTlpMHjgmhAgmdICg085uIMQABBMhkOAgKS7VTAMzQjYHEAWKCIR6OSzMEJhCJRP4hKDxQnw4APEJwtYwxEWYhA0HgkDxepwMApfo-QJJISicTJc6Xa6qGxspzLYp0FigSBQABi7HYUiwyxCBGIpAoNEx+IARmsEKqHDQMaLmJLoCI1gqlbZ9erqJqQvgIAhWBQwMBcJwbY5NcVTTLDE0mrL5ZhFfjrWiNVadWQ9VBdOayO5PN5fBB8E4jSFistStwEA1mhBg3Hg5YpGYrWHw1AY3GzAByOANmwNrUN6xW5V2BsARgbVropLx4brxEbrBbUDbHeH3eIDYATAPw+KQhZmLmAeUY8DiInLeHHc7Xe7PdOD8CW1aVdPm8at2Va2sRPuLaGrceXbg3R7KAuDxEa9w1vGcH3+J8YwAYTfJMPyPJ1v1-c8GwPKDgPxUDJ3AqA83KHgAyDOVS0IstkUwStw2rUddXHXcbBjEROxrCM+xXfEhyrLtn1jOi1ighiX2YmtQOXQdlgsEptxRYMpALRoWhLMwAAYNzYaS+SudYK3oniREEsgoLUvDKmqPwpCqWpCxaXQ4GDVs6ynTSBUoQopK4dgWniJp2GoXQACkagEAA5eI1UcXAeBAXRLL8JxCiAA)

### 💻 Code

```ts
const joinSample = <T, K extends keyof T, U extends HasID>(
  parent: T,
  parentKey: K,
  children: U[],
) => {
  const keyArray = parent[parentKey] as string[];
  return {
    ...parent,
    [parentKey]: keyArray.map((k) => findOneById(children, k)) // Returns type U | undefined
  };
}
```

### 🙁 Actual behavior

The above code infers the output to `joinSample` as `T & [x: string] : (U | undefined)[]` which indicates that the T has the same key twice, with different types. 

This is demonstrated in the playground when `joined` is typed to `FullFoo`.  Untyped, when run, it produces an object that meets the criteria for `FullFoo`.  When declared with type `FullFoo`, it raises an error.

### 🙂 Expected behavior

I would expect Typescript to substitute the type of parentKey from its previous value (in this case, always `string[]`) to `(U | undefined)[]`.  The compiler *knows* that K is a keyof T - instead of creating a `never` condition, it should replace the type of T[K] to U.

**Comment by RyanCavanaugh** [comment]
The Playground link is very very long, and the sample here has unbound identifiers. Can you please provide a minimal sample that more clearly demonstrates the problem you're describing?

**Comment by RoboZoom** [comment]
This is as condensed as I can get it: [Typescript Playground](https://www.typescriptlang.org/play?ts=5.1.3#code/C4TwDgpgBAEghgZwJIBEoF4oG8oEsAmAXFAsAE64B2A5lAL4DcAUEwMYD2lpUAVu1QGU4AWzAAbaJgA8AFQA0UANJQIAD2ARK+BFADWEEOwBmUeVACqK9Zu2xEqAHwAKJlChg4ZTcGLzX7z29FA2JFOSYASgwHbH8OLmA9AwBBMjI4EAwAr0pgAG0PHOBgkABdKEQScipqPNLmNy9gAFcySli3NwA6HsLvcM6oAsDcktLifRBU9JAu4TgwJyddKPQYgEYAJgBmCP9GJjoWUEgoADF2diysfzcCYlIKGgbOgCNPBAfqmjqXg5PoGdmmIxBcrpgboN7lUntQXm53mRPlBKM1hK8IGRfvtmHFONwECJxBAwcQwddblBEci8gByOC0uS01600oDTrQ+mvVi0-YsNzxbhqSCsDT4ABKEAQwJ8QJB5MwlMhgypH2IeS22zkmrZlLuRCgXJ5lKOgsSfCoEANctBlyyFsoQlEEichOdJMuCmZH1pEVxgvYEi6YnY1CcACkBAB5AByXUeNVwRhATgdVoifqAA)

Most of the space is scaffolding.  The link above doesn't represent the desire to re-type the output is transformed so that the object[K] has type U[].  Everything is still scaffolding to demonstrate the following:

```ts
const joinSample = <T, K extends keyof T, U extends HasID>(
  parent: T,
  parentKey: K,
) => {
  const keyArray = parent[parentKey] as string[];
  return {
    ...parent,
    [parentKey]: keyArray.map((k) => 123) // This assignment causes the problem
  };
}
//...
const joined: FullFoo = joinSample(sampleFoo, 'bars'); // Error - the type for joined is inferred as {id: string, bars: string[], bars: number[]}
```

**Comment by RyanCavanaugh** [comment]
The problem here is that there isn't a correct type to describe what `joinSample` actually does, so TypeScript errs on the side of caution when describing it.

First let's fix `joinSample` to do what you want, then show why that's "wrong":
```ts
const joinSample = <T, K extends keyof T>(
  parent: T,
  parentKey: K,
) => {
  const keyArray = parent[parentKey] as string[];
  return {
    ...parent,
    [parentKey]: keyArray.map((k) => 123)
  } as T & Record<K, number[]>;
}
```
This behaves as desired.

However, if you invoked this as
```ts
const joined: FullFoo = joinSample<typeof sampleFoo, 'bars' | 'id'>(sampleFoo, 'bars');
```
then the implied behavior based on the type definition is that you'd have an object with `bars: number[], id: number[]`, but that's obviously not what's happening -- the function can't (as in, can't possibly) runtime-enumerate all possible inhabitants of `K` to provide properties of it.

**Comment by fatcerberus** [comment]
Chalk up another use case for https://github.com/microsoft/TypeScript/issues/27808.

**Comment by RoboZoom** [comment]
First, you if you're having to cast the output, then you aren't getting appropriate inference and I'd argue it's still a problem.

Second, your application of `joinSample` typing isn't an appropriate application of logical types.  If you are looking at K as a union, then the output should be a union of each of the different possibilities driven by the input union.

So T has keys `id` and `bars`, then K is by definition `id` and `bars`, then in this case the output *should* reasonably be (and is certainly computable):
```ts
{ bars: number[]; id: string } | {bars: string[]; id: number[]}
```

This could be further narrowed when the function is called.

**Comment by fatcerberus** [comment]
@RoboZoom I think Ryan’s point is, ultimately, that there’s no way to represent that type operation generically (since your implementation is generic) using the type operators that are currently available.  That would require [spread types](https://github.com/microsoft/TypeScript/issues/10727).

Basically there’s no type that TypeScript can currently infer that would accurately represent the output of this function.

**Comment by RyanCavanaugh** [comment]
> First, you if you're having to cast the output, then you aren't getting appropriate inference and I'd argue it's still a problem.

The point of that example is to show that the inferred signature is the more correct one. If we gave it the type you're saying it should have, the output would be wrong.
