### ISSUE TITLE
1029 nightly broken

### ISSUE THREAD

**Issue by robertbaker** [Microsoft/TypeScript#5455]
Getting cannot find module errors for my entire app. 1027 nightly is fine.

**Comment by mhegazy** [comment]
can you share more information?

**Comment by mhegazy** [comment]
are you using typescript through an extension to webpack, gulp, gurnt, browserify, etc..

**Comment by robertbaker** [comment]
I'm using gulp-typescript, which is using typescript@next. It's using my tsconfig which is pretty basic. 

I use es6 style imports.

```
\app\customer\customer.ts(3,30): error TS2307: Cannot find module '../api/base/base-controller'.
src\app\customer\customer.ts(4,38): error TS2307: Cannot find module './service/customer'.
src\app\customer\customer.ts(5,33): error TS2307: Cannot find module '../api/data/entities'.
src\app\customer\customer.ts(6,22): error TS2307: Cannot find module '../api/action-buttons/action'.
src\app\customer\customer.ts(7,28): error TS2307: Cannot find module '../api/action-buttons/action-cancel'.
src\app\customer\customer.ts(8,26): error TS2307: Cannot find module '../api/action-buttons/action-save'.
src\app\customer\customer.ts(9,26): error TS2307: Cannot find module '../api/action-buttons/action-edit'.
src\app\customer\customer.ts(10,30): error TS2307: Cannot find module '../api/action-buttons/action-edit-save'.
src\app\customer\customer.ts(11,26): error TS2307: Cannot find module '../api/action-buttons/action-star'.
src\app\customer\customer.ts(12,28): error TS2307: Cannot find module '../api/action-buttons/action-delete'.
src\app\customer\customer.ts(13,51): error TS2307: Cannot find module './ICustomerExtended'.

```

Running tsc on my src dir (where the tsconfig is installed). seems to output without errors.

Something must have changed with the nightly that affected gulp-typescript

**Comment by robertbaker** [comment]
Seems like you now pass relative paths in the api.

See:
https://github.com/ivogabe/gulp-typescript/issues/223

Might want to notify others about this change.

**Comment by ivogabe** [comment]
@mhegazy @vladima It looks like #5462 has reverted this behavior, is that right?

**Comment by vladima** [comment]
@ivogabe yes, now we'll use whatever host has returned to us as `resolvedFileName`
