### ISSUE TITLE
cannot access generic type directly inside function

### ISSUE THREAD

**Issue by ephemeral108** [microsoft/TypeScript#54559]
# Bug Report

### 💻 Code

```ts
const test: <T>(para: T) => void = (para) => {
  let a: T = para; // error: cannot find name T
  let b: typeof para = para; // √
};
```

### 🙁 Actual behavior

error: cannot find name T

### 🙂 Expected behavior

No error

**Comment by ephemeral108** [comment]
this only happen when using jsx

**Comment by RyanCavanaugh** [comment]
There is no type named `T` in scope at that location.

**Comment by nmain** [comment]
Is the quickinfo misleading here?

```typescript
const test: <T>(para: T) => void = (para) => {
  //                                ^? (parameter) para: T
};
```

At that location, `para` has an unnamed type.

**Comment by RyanCavanaugh** [comment]
I guess it's more properly "anonymous T" or something? The type exists, but you can't name it via `T`

**Comment by jcalz** [comment]
“Anonymous T” is my new stage name

**Comment by fatcerberus** [comment]
"Anonymous `T`" sounds suspiciously like an existential.

I wonder if this is related to the recent bug where TS was inferring the type of something as `T` outside the scope of the generic.  I feel like the proper thing for TS to infer for `para` there is `unknown`... or else an implicit `any` error.

**Comment by ephemeral108** [comment]
Sorry, i remember i closed this issue when i comment "this only happen when using jsx"😓

**Comment by ephemeral108** [comment]
and when i try it on pure ts environment, it works fine, so i guess this is related to jsx

**Comment by nmain** [comment]
> I feel like the proper thing for TS to infer for `para` there is `unknown`...

But if there's a bound, that bound is still usable, and that seems perfectly fine.

```typescript

type Fn = <T extends { a: string }>(para: T) => void;

const test: Fn = (para) => {
  para.a;
};
```

There's just no good name to put on the "T" inside the function.

**Comment by ephemeral108** [comment]
sorry, i just relise that i put the <T> in the worry place😅

**Comment by ephemeral108** [comment]
the code should be like this:
const fun2: () => void = <T>() => {
  let b: T;
};

**Comment by ephemeral108** [comment]
`const fun2: () => void = <T>() => {
  let b: T;
};`

**Comment by ephemeral108** [comment]
it should be like this:
`
const fun2: () => void = <T>() => {
  let b: T;
};
`
