### ISSUE TITLE
How is the URL formed when clicking CTRL + S on Typescript Playground

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [microsoft/TypeScript#54555]
Hello All. Does anyone know what library or package is used to compress and persist all information in the current playground code into the encoded link?

- I go to https://www.typescriptlang.org/play (which I use almost every single day and I LOVE it)
- test some stuff out
- CTRL + S

Now I see the URL is updated with all the information encoded and probably compressed as well. For example https://www.typescriptlang.org/play?#code/MYewdgziA2CmB00QHMAUByAFraSAEAZgE4gC2eALtniFbEXhAJYAms6AlANxA

My question is, how exactly is this happening Is it custom compression logic or any library is used to achieve it? I have a similar requirement and would love to know how this is achieved. Thanks in advance.

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript-Website/blob/0995425273ba42a547f5952de1f4ef93fc5b1dfb/packages/playground-handbook/copy/en/URL%20Structure.md?plain=1#L11

**Comment by EmmanuelPonnudurai** [comment]
That's awesome thank you.
