### ISSUE TITLE
forceConsistentCasingInFileNames doesn't work on macos and windows when import package

### ISSUE THREAD

**Issue by tjx666** [microsoft/TypeScript#54565]
# Bug Report

### 🔎 Search Terms

forceConsistentCasingInFileNames, macos, windows

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

exists on latest stable version and nightly version

### ⏯ Playground Link

[reproduce repository](https://github.com/tjx666/ts-filename-case-issue)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

```typescript
import plugin from 'unplugin-detect-duplicated-deps/Vite';

console.log(plugin);
```

### 🙁 Actual behavior

https://github.com/tjx666/ts-filename-case-issue/actions/runs/5203586299/jobs/9386641836

<img width="1440" alt="image" src="https://github.com/microsoft/TypeScript/assets/41773861/b319ca6d-308a-4487-8768-65af6ca60335">

macos, windows can pass tsc check, but linux can't, linux output

```node
> tsc --noEmit

Error: index.ts(1,20): error TS230[7](https://github.com/tjx666/ts-filename-case-issue/actions/runs/5203586299/jobs/9386641836#step:6:8): Cannot find module 'unplugin-detect-duplicated-deps/Vite' or its corresponding type declarations.
 ELIFECYCLE  Test failed. See above for more details.
Error: Process completed with exit code 1.
```

### 🙂 Expected behavior

Because I set `"forceConsistentCasingInFileNames": true` options, tsc should throw error on all system, not only linux

**Comment by fatcerberus** [comment]
`forceConsistentCasingInFileNames` only ensures the filenames are consistent *within your codebase*, not necessarily with the file system.

**Comment by tjx666** [comment]
1. maybe this is feature request, implements this can help identify problems in advance
2. we can improve the error report, for example notify user maybe your module path case not right and provide the correct path

**Comment by tjx666** [comment]
I use macos devlop the ts code, code can pass tsc on mac machine, but can't pass the linux ci. This question took me an entire afternoon to investigate.

**Comment by RyanCavanaugh** [comment]
#21736

**Comment by tjx666** [comment]
close because duplicated
