### ISSUE TITLE
Typescript 5.1.3 generates incorrect javascript (5.0.4 is correct)

### ISSUE THREAD

**Issue by air2** [microsoft/TypeScript#54561]
# Bug Report

### 🔎 Search Terms
I looked through all recent bug reports

### 🕗 Version & Regression Information

- This changed between versions 5.0,4 and 5.1.3

### 💻 Code

The generated code in 5.0.4 was:

```
 let P = class {
....
}
s(
...
),
(P = s(
...
),
(t.MainService = P)

```

However in 5.1.3 it changed to:

```
let P = (t.MainService = class {
....
},
s(
....
),
 (t.MainService = P = s(
...
)
```

### 🙁 Actual behavior

In the second version t.MainService is overwritten instead of extended, therefor critical functionality is stripped

### 🙂 Expected behavior

In the second version t.MainService should not be overwritten but extended

**Comment by fatcerberus** [comment]
> The generated code in 5.0.4 was

Generated code for *what*?  What is the corresponding TS code?  You haven't provided a way to reproduce the bug.

**Comment by fatcerberus** [comment]
Just knowing which TS code corresponds to the emitted JS in the OP would go a long way, because looking at it right now, it doesn’t look like anything `tsc` would emit natively.

**Comment by air2** [comment]
I created a reproduction. The problem is maybe not in typescript. It occurs when webpack is used to create a single file from the generated typescript code. With 5.0.4 the exported class is named, with 5.1.3 it is anonymous.

The reproduction is in.
https://github.com/air2/typescript-bug

This anonymous class is a problem for the TS.ED framework, which uses the name of the class to store information about it in a Map as far as I can tell. It took me some time to create this reproduction, sorry for the delay. Maybe the problem is in webpack, but I cannot tell, but as long as I use typescript 5.0.4, the class is named and with 5.1.3 not, so therefor I think the problem is in typescript. But well with software you never know. Hopefully this gives more insight in the problem

**Comment by jakebailey** [comment]
@rbuckton

**Comment by rbuckton** [comment]
I made some changes in how we handle assigned names to match with `NamedEvaluation` in preparation for #54505, which itself has some additional improvements in how we handle assigned names.

However, I cannot seem to reproduce the anonymous class issue in the Playground: https://www.typescriptlang.org/play?experimentalDecorators=true&emitDecoratorMetadata=true&module=1#code/JYOwLgpgTgZghgYwgAgMIHsQ2Ac2QbwChkTkIAPAByggGdaAuA5AIwBs4ALJ2sKUPAF9CwwjACuIBGGCY0mbDnFQ4MzAAoEC3MtWyQTAApwoMuGwA8GLLgB8yALwFBASiYAxSdP0FipGmDKIMjqLo72RKRRyFo2SipqIH4kggDcIoSEAALWirqJ6pGkFNR0jMzsXEwA5JC81cjCroQl6KYxHPTIALJwoADK0ABuwEi+ohJSiazo6GC8KpTqALboACbibBBMcCAAnmFFJLG06FsAdGzoOCvrmxDnIHDLEC4ZhCyz83xwS70Dw1Gr1SQA

Also, while this does seem to repro under WebPack's `mode: "production"`, it does not repro under `mode: "development"`:

![image](https://github.com/microsoft/TypeScript/assets/3902892/04db0624-2841-43fa-aae2-6c4162eead1f)

Which seems to indicate that WebPack decided to remove the unreferenced class name when minifying. I'm not familiar enough with Terser's configuration to be able to tell you if there is an option to control this, but it is possible to work around it by using `static { Object.defineProperty(this, "name", { value: "MainService" }); }` explicitly.

**Comment by rbuckton** [comment]
Apparently Terser has a `keep_classnames` minification option that can help: https://terser.org/docs/api-reference.html#minify-options

**Comment by air2** [comment]
@rbuckton The work around is a nice catch. In the real code this would mean I have to do this for every exported class, because I cannot determine which classes keep there names and which do not, also I am not sure for which classes the name is important, so I'll stick to `5.0.4` for now, or does this mean it is not something that can be easily solved in the typescript compiler? I will also look at the Terser `keep_classnames` option, because that sounds more promising.

**Comment by air2** [comment]
It looks like adding the terserplugin options to the webpack configuration:

```
  optimization: {
    minimize: true,
    minimizer: [new TerserPlugin({
        terserOptions: { 
            keep_classnames: true
        }
    })],
  }
  ````
  is working. At some bigger javascript costs (although I guess the gzipped end result will not be larger, or just a little bit) I need to test more if everything is working fine, but I guess that is very workable solution/workaround. thanks for the help.
  
  Will the typescript  output be changed so this is not necessary anymore, or will this be the recommended approach?
