### ISSUE TITLE
Regression in autocompletion on spread generic arguments

### ISSUE THREAD

**Issue by dexx086** [microsoft/TypeScript#54572]
# Bug Report

### 🔎 Search Terms

autocomplete, regression

### 🕗 Version & Regression Information

- This changed between versions **5.0.4** and **5.1.3**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/GYVwdgxgLglg9mABMMAeAKogpgDylsAEwGdEAKAcgDcBDAGxCwEYLEAfRa+xgJlY64MsAZgoBKANoBdAHxkAdItpDiALkTox6zAG9EAJyxQQ+pMsbEA3IgC+AKDsB6R4gCSSAKzym84QBpEMDhEZRhCRBoQKDgAWwAHOiN4JDI4fQi6BABzRAB3GCgACwMaIliAmEg0w2gQ7ixiMQCAIyjESsQvAAZ5ABY6oSY2cyweYfrhAYsIwwiouAhYhKMscMX9Gqg6AE87RbBiKCnmRABeZDBKcUs9hEPjnjOLyhGWAIpruyA)

### 💻 Code

```typescript
function fn<T extends ('value1' | 'value2' | 'value3')[]>(...values: T): T { return values; }

const value1 = fn('');
const value2 = fn('value1', '');
```

### 🙁 Actual behavior

It should autocomplete inside both '' (empty string) places with value1|value2|value3 possible values, however it shows incorrect (kind of randomly gathered) options. For eg.:

![image](https://github.com/microsoft/TypeScript/assets/8817255/e6eee51b-f60f-4d39-80d0-8a7cdaaec4b3)

### 🙂 Expected behavior

It should show only value1 / value2 / value3 options (as it does correctly with 5.0.4 and before), like this:

![image](https://github.com/microsoft/TypeScript/assets/8817255/658ea401-f325-42c1-8df9-9003a34e4610)

This issue could be related to (https://github.com/microsoft/TypeScript/issues/53555) and (https://github.com/microsoft/TypeScript/issues/52726) but I think my case is more basic, and appeared only in the latest (5.1.3) version of TS. (couldn't test if versions between 5.1.0 and 5.1.3 were affected or not, I could test only 5.1.3).

**Comment by Andarist** [comment]
Bisected this to: https://github.com/microsoft/TypeScript/pull/52717 . Gonna look into fixing this soon
