### ISSUE TITLE
`resolvePackageJsonExports` doesn't actually work

### ISSUE THREAD

**Issue by ekwoka** [microsoft/TypeScript#54574]
# Bug Report

Using `node` module resolution doesn't examine `exports` paths.

adding `resolvePackageJsonExports: true` is accepted in the tsconfig, but doesn't actually work. It still says ts can't resolve it.

### 🔎 Search Terms

`resolvePackageJsonExports`

### 🕗 Version & Regression Information

Latest

### ⏯ Playground Link

Can't use npm imports in the playground.

### 💻 Code

```ts
import UI from "@newthink/ui";
```

```json
{
  "include": ["src/**/*"],
  "exclude": ["src/**/*.spec.ts", "src/**/*.test.ts"],
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@/*": ["*"]
    },
    "noEmit": true,
    "declaration": true,
    "outDir": "dist",
    "declarationMap": true,
    "target": "es2017",
    "module": "esnext",
    "moduleResolution": "node",
    "resolvePackageJsonExports": true,
    "noImplicitAny": true
  }
}
```

### 🙁 Actual behavior

`Cannot find module '@newthink/ui' or its corresponding type declarations.`

### 🙂 Expected behavior

Actually Work

**Comment by Andarist** [comment]
> Can't use npm imports in the playground.

You actually can, sort of, do that:
[TS playground](https://www.typescriptlang.org/play?resolvePackageJsonExports=true&ts=5.1.3#code/PTAEAECcFMGcHsA2A3aAFAhgYwNYYObQBSCAdgKIAeADvJAC6wBco9kArtAFACWAtrQagAqgElQAM0jw+oAEThS0AO70AFj1I5g7HnIDcoEKwCe1OCwAMAOgCMdro65A)

Note - please reorder `exports.{import,types}` to `exports.{types,import}`. In this case the `types` condition isn't strictly needed anyway because those files have the same names (just different extensions) so you can rely on the sibling lookup. However, if you want to include the explicit `types` condition it's best to put it first. `package.json#exports` are actually **order-sensitive**

**Comment by ekwoka** [comment]
Okay, I am seeing that in the docs


But if `types` isn't necessary, since it's index.js and index.d.ts then it also should still work even if the order is wrong.

**Comment by Andarist** [comment]
> But if types isn't necessary, since it's index.js and index.d.ts then it also should still work even if the order is wrong.

Yeah, it works right now but might be misleading to users or copy-pasted to other projects where the situation will be different.

**Comment by fatcerberus** [comment]
@Andarist While I understand the order-dependence, does it matter for `types`?  `import` and `types` are, I thought, completely orthogonal (assuming both exist) so it shouldn’t matter which one has “precedence”.

**Comment by Andarist** [comment]
While this might feel odd at first - yes, `types` shouldn't be treated in any special way here.

What should resolve here and how exactly the algorithm should be written to make the rules clear if the overarching rule of `package.json#exports` is that they are order-dependent:
```json
{
  "exports": {
    "import": {
      "types": "./foo.d.ts"
      "default": "./bar.js"
    },
    "types": "./baz.d.ts"
  }
}
```

Of course, the outer `types` could be used here merely as a "fallback" (if the inner one wouldn't have `types` condition) but imho that only makes things more muddy when that overarching rule is in place. 

Currently, it actually might be used as a fallback but that's considered a bug: https://github.com/microsoft/TypeScript/issues/50762

**Comment by fatcerberus** [comment]
fwiw I was referring more to how `import` and `types` relate to each other when at the *same* level of nesting, and both refer directly to files.  I guess you’re implying that if the `import` comes first then the “expected” behavior is that TS would always use sibling lookup

**Comment by Andarist** [comment]
> fwiw I was referring more to how import and types relate to each other when at the same level of nesting, and both refer directly to files. 

Yeah, but what you describe goes into "more rules" territory whereas the basic rule of order-dependency is pretty simple and using it uniformly helps educating the community at large about this fact. Diverging from it introduces a dangerous precedence and creates more complexity for other tools that try to replicate TS behavior when analyzing packages etc. In every other context those keys are order-dependent so treating `types` as not fully order-dependent would force other implementers to specialcase this .

**Comment by RyanCavanaugh** [comment]
I'm not seeing a bug described here.

Generally we don't ship flags that are completely broken out of the gate?

**Comment by ekwoka** [comment]
It just doesn't seem to do anything. Or the spec doesn't clarify when it should or shouldn't work.

Basically, the goal would be getting a situation where you can leave off the `.js` extension, and use packages that don't have `main` or `types` entries in the package JSON, using `exports` only.

Based on the docs, the aforementioned flag seems like it should use `exports` always regardless of other settings.
