### ISSUE TITLE
compilation of jsx files with visual studio

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#5457]
Hi, I have 2015 update 1 ctp + asp.net 5 beta tools and typescript 1.6. I'm trying to create a simple react app starting from the jsx sample in the typescriptsamples repo, but looks like that if I add the outDir param with jsx react the tsx files are not compiled anywhere, but if I remove this setting the files are compiled in the same directory of the tsx file.
Is this possible?

**Comment by paulvanbrenk** [comment]
I don't reproduce this on my machine, which does have some fixed scheduled for 1.8.. can you share your project so I can make sure things work as expected.

**Comment by lucamorelli** [comment]
You can download it from https://dl.dropboxusercontent.com/u/19486794/TestDrive.zip, it's the **React** project. In the **Angular2** project the **jspm_modules** is hidden from solution explorer to fix a performance issue with solution manager. It's a big file, but I added all the installed files so I think you can better check.

**Comment by lucamorelli** [comment]
using the language services file cloning the repo I can check this? btw: if I use the language file from the repo inside vs what are the differences? I would like to use the up to date version, but it's not so clear what really changes

**Comment by paulvanbrenk** [comment]
@lucamorelli no, these changes are not in the public repo, but are part of the Visual Studio components, which are still closed.

**Comment by paulvanbrenk** [comment]
This works as expected for me, and shouldn't involve any of the changes I made in the msbuild tasks. Can you try the VS2015 Update 1 RC, which we released yesterday.

https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx

**Comment by mhegazy** [comment]
This should be working in TS 1.7. please reactivate if still an issue.
