### ISSUE TITLE
Proposal for Mixins, including Abstract Mixins, in TypeScript

### ISSUE THREAD

**Issue by RedYetiDev** [microsoft/TypeScript#54576]
# Suggestion

## 🔍 Search Terms

Mixin, Abstract Mixin, `with` keyword, Native Mixins, Interface

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

This proposal suggests introducing enhanced mixins, including abstract mixins, in TypeScript to address the limitations of the current mixin support. The proposed changes include using the `with` keyword for implementing mixins and the `mixin` keyword for defining mixins. This syntax provides a more concise and intuitive way to work with mixins, enhancing code organization, reusability, and maintainability.

## 📃 Motivating Example

Imagine you are building a web application that requires various user interface components, such as buttons, input fields, and dropdown menus. Traditionally, you would have to duplicate code across different components, leading to code redundancy and reduced maintainability.

With enhanced mixins, you can easily create reusable behavior that can be mixed into multiple components, eliminating the need for code duplication. Let's take a look at an example:

```typescript
// Define a mixin for handling click events
mixin Clickable {
  onClick(): void {
    console.log('Clicked!');
  }
}

// Define a mixin for handling focus events
mixin Focusable {
  onFocus(): void {
    console.log('Focused!');
  }
}

// Create a button component with the click and focus behavior
class Button with Clickable, Focusable {
  // Button implementation
}

// Create an input component with only the focus behavior
class Input with Focusable {
  // Input implementation
}
```

In this example, we define two mixins: `Clickable` and `Focusable`. The `Clickable` mixin provides a common `onClick` method, while the `Focusable` mixin provides a common `onFocus` method. We then create a `Button` component by mixing in both `Clickable` and `Focusable` mixins, and an `Input` component by mixing in only the `Focusable` mixin.

By using mixins, we can effortlessly add behavior to our components without duplicating code or creating complex inheritance hierarchies. This approach promotes code reuse, simplifies maintenance, and improves code organization.

Furthermore, enhanced mixins also support abstract mixins, allowing us to define mixins with unimplemented methods or properties. This empowers us to create reusable templates that can be customized by the implementing class.

I am excited to bring this powerful feature to the TypeScript community. Enhanced mixins will streamline the development process, enhance code organization, and ultimately make TypeScript code more maintainable and reusable.

## 💻 Use Cases

The current approach to mixins in TypeScript has some shortcomings that the proposed feature aims to address. Currently, implementing mixins can be cumbersome and requires the use of complex patterns or external libraries. There is a lack of native support for mixins, leading to increased code verbosity and reduced maintainability. Additionally, abstract mixins, which allow for defining mixins with unimplemented methods or properties, are not supported in TypeScript.

To work around these limitations, developers often resort to creating base classes, using composition patterns, or relying on external libraries such as ts-mixer or ts-mixin. While these workarounds can provide some level of mixin functionality, they introduce additional complexity, dependencies, and can make the code harder to understand and maintain.

The proposed enhanced mixins feature aims to provide a more straightforward and native way to define and use mixins, including abstract mixins, in TypeScript. This will eliminate the need for complex workarounds and external libraries, simplifying code organization and promoting reusability and maintainability.

---
> ## I prepared a proposal for mixins, you can view it below
---
# Proposal for Mixins, including Abstract Mixins, in TypeScript

## Introduction
TypeScript is a popular statically typed superset of JavaScript that provides powerful features for building robust and maintainable applications. However, the current support for mixins in TypeScript is limited, making it challenging to effectively abstract classes and interfaces. Developers often rely on complex patterns or external libraries to manually implement mixins, resulting in increased code verbosity and reduced maintainability. Additionally, there is a lack of support for abstract mixins, which hinders the ability to define mixins with unimplemented methods or properties. This proposal aims to introduce enhanced mixins, including abstract mixins, in TypeScript to address these limitations and provide a more straightforward and native way to define and use mixins.

## Problem Statement
The current state of mixins in TypeScript has several limitations. First, there is no built-in syntax for defining mixins, requiring developers to use workarounds or external libraries. This leads to non-standardized patterns and increased complexity in codebases. Second, the lack of support for abstract mixins makes it impossible to define mixins with unimplemented methods or properties, limiting the flexibility and reusability of mixins.

To illustrate the problem, let's consider a scenario where we want to define mixins for adding logging functionality to classes. Currently, developers might resort to the following approach:

```typescript
// External library or custom implementation for mixins
function applyMixins(derivedCtor: any, baseCtors: any[]) {
  baseCtors.forEach(baseCtor => {
    Object.getOwnPropertyNames(baseCtor.prototype).forEach(name => {
      derivedCtor.prototype[name] = baseCtor.prototype[name];
    });
  });
}

// Mixin for logging functionality
class LoggableMixin {
  log(message: string) {
    console.log(`[LOG]: ${message}`);
  }
}

// Class using the LoggableMixin
class MyClass {
  // Class implementation
}

// Applying the mixin to MyClass
applyMixins(MyClass, [LoggableMixin]);

const instance = new MyClass();
instance.log("Hello, mixins!");
```

In the above example, developers need to rely on an external function `applyMixins` to manually apply the mixin to the class. This approach introduces boilerplate code and reduces the readability of the class definition. Additionally, the current implementation does not provide a way to define abstract mixins, making it impossible to enforce the implementation of certain methods or properties.

## Proposed Change
The proposed change introduces enhanced mixins, including abstract mixins, in TypeScript to provide a more intuitive and native way to define and use mixins. It suggests the introduction of the `with` keyword for implementing mixins and the `mixin` keyword for defining mixins, both for regular mixins and abstract mixins.

### Syntax
To implement a mixin, developers can use the `with` keyword followed by the mixin's name(s) in the class definition. Abstract mixins can be implemented in the same way, and any unimplemented methods or properties from the abstract mixin must be implemented in the class. The syntax for implementing mixins is as follows:

```typescript
class MyClass with MixinA, MixinB {
  // Class implementation
}
```

To define a mixin, the `mixin` keyword is used along with the mixin's name and its implementation. The implementation includes methods, properties, and other class members. Abstract mixins can be defined by using the `abstract` keyword before the `mixin` keyword. The syntax for defining mixins is as follows:

```typescript
mixin MixinA {
  // Mixin implementation
}

abstract mixin AbstractMixin {
  abstract method(): void;
  abstract property: number;
}
```

### Implications
The proposed change has several implications that need to be considered:

#### 1. Syntactic
The suggested syntax for implementing mixins with the `with` keyword does not interfere with existing ES6 or plausible ES7 changes. The `mixin` and `abstract mixin` keywords for defining mixins are new additions to the TypeScript grammar but align with the intuitive nature of mixins. The proposed syntax provides a more concise and readable way to define mixins, enhancing the overall developer experience.

To illustrate the syntax implications, let's consider some scenarios:

**Scenario 1: Attempting to implement a non-existent mixin:**
```typescript
class MyClass with NonExistentMixin {
  // Class implementation
}
```
In this case, the TypeScript compiler should raise an error indicating that the mixin `NonExistentMixin` does not exist.

**Scenario 2: Conflicting member names between mixins and classes:**
```typescript
class MyClass with MixinA {
  name: string;
}

mixin MixinA {
  name: number;
}
```
In this scenario, the TypeScript compiler should raise an error since the `name` property in the class conflicts with the `name` property in the mixin, resulting in an ambiguity.

**Scenario 3: Misuse of mixin implementation syntax:**
```typescript
mixin MixinA {
  name: string;
}

const myMixin = new MixinA(); // Error: Mixins cannot be instantiated
```
In this case, the TypeScript compiler should raise an error indicating that mixins cannot be instantiated directly.

**Scenario 4: Failure to implement abstract methods or properties from an abstract mixin:**
```typescript
class MyClass with AbstractMixin {
  // Class implementation without implementing the abstract method and property
}

abstract mixin AbstractMixin {
  abstract method(): void;
  abstract property: number;
}
```
In this scenario, the TypeScript compiler should raise an error indicating that the abstract methods and properties from the abstract mixin `AbstractMixin` must be implemented in the class `MyClass`.

#### 2. Semantic
The proposed feature affects the semantic behavior of the language in several ways. Errors may occur when attempting to implement non-existent or incompatible mixins, conflicting member names between mixins and classes, misuse of mixin implementation syntax, or failure to implement abstract methods or properties from an abstract mixin. These errors serve as guardrails to ensure correct usage of mixins and abstract mixins.

On the other hand, successful implementation and usage of mixins and abstract mixins should not introduce any conflicts or alter the existing subtype, supertype, identity, and assignability relationships. Mixins and abstract mixins should work seamlessly with generics, ensuring compatibility and avoiding unexpected type constraints.

#### 3. Emit
The feature should correctly emit valid JavaScript code that retains the intended behavior of the mixins and abstract mixins. The generated JavaScript code should not rely on runtime type information or introduce any issues when variables of type `any` are used. The declaration file (.d.ts) emit should reflect the presence of mixins and provide accurate type information for consumers. Mixins and abstract mixins should be compatible with external modules, ensuring smooth integration without causing conflicts or breaking the module system.

#### 4. Compatibility
Mixins do not alter JavaScript expression semantics, maintaining compatibility with JavaScript behavior. The implementation of mixins and abstract mixins aligns with future JavaScript features, such as ES6 and ES7.

#### 5. Other
The implementation of the proposed feature should aim to minimize negative impacts on compiler performance. Tooling scenarios, such as member completion and signature help in editors, should be updated to provide appropriate suggestions and assistance when working with mixins and abstract mixins. This will enhance the developer experience and enable seamless integration with TypeScript development workflows. By addressing these implications, the proposed enhanced mixins feature, including abstract mixins, will improve code organization, readability, and maintainability, enabling developers to leverage the benefits of mixins more effectively within TypeScript projects.

## Conclusion
The current limitations of mixins in TypeScript hinder code abstraction and reusability. This proposal introduces enhanced mixins, including abstract mixins, to address these limitations and provide a more straightforward and native way to define and use mixins. The proposed syntax using the `with` keyword for implementing mixins and the `mixin` keyword for defining mixins, along with the support for abstract mixins, simplifies the usage of mixins and promotes code organization and maintainability.

By implementing this proposal, TypeScript will provide a more powerful and intuitive mechanism for working with mixins, reducing the need for complex patterns or external libraries. This will result in cleaner code, improved developer productivity, and enhanced code maintainability, ultimately benefiting the TypeScript community as a whole.

**Comment by fatcerberus** [comment]
> This isn't a runtime feature (e.g. library functionality, **non-ECMAScript syntax with JavaScript output, new syntax sugar for JS**, etc.)

It is, though.  Nowadays, TypeScript doesn't add runtime-affecting syntax that isn't supported natively by JS, so this will be declined.  It should instead be proposed to TC39 if you want it to get any traction.

**Comment by fatcerberus** [comment]
> The implementation of mixins and abstract mixins aligns with **future** JavaScript features, such as **ES6 and ES7**.

Found the time traveler

**Comment by RedYetiDev** [comment]
> > This isn't a runtime feature (e.g. library functionality, **non-ECMAScript syntax with JavaScript output, new syntax sugar for JS**, etc.)
> 
> It is, though. Nowadays, TypeScript doesn't add runtime-affecting syntax that isn't supported natively by JS, so this will be declined. It should instead be proposed to TC39 (the ECMAScript committee) if you want it to get any traction.

Your right. I didn't think about how default functions would affect the runtime, I don't know how I overlooked that. Thanks for your advice, I will make sure to submit a proposal to TC39.

**Comment by RedYetiDev** [comment]
Oh! That's great! That saves me a lot of time and effort. I'm sorry if I inconvenienced anyone with this.
