### ISSUE TITLE
Type narrowing inconsistency when using the ‘in’ operator

### ISSUE THREAD

**Issue by stoltzrobin** [microsoft/TypeScript#54586]
# Bug Report

### 🔎 Search Terms

* Type narrowing inconsistency 
* ‘in’ operator

### 🕗 Version & Regression Information

at least since 4.6.4

- Shows wrong types
- I was unable to test this on prior versions because the playground did not show the types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/C4TwDgpgBAglC8BYAUFKAfKBvKBrCIAjAFxQDOwATgJYB2A5lAL4pqY74gBMpFNDzVhmx4CJclTr0ANKJAAWXpIEtkKAMYB7WhSiUArrQRQAFABMAhsAukYASgQA+bEOoAzUwEITAIk6EfKDooS2s7B0oIYH1KWhQhUIshAHpkqAA9AH541CCPX04uQODEhywhNESKqFSM7NzVBKsk3NqslCYgA)

### 💻 Code

```ts
type A =
  | { key1: string }
  | { key2: string }
  | { key1: string, key4: string }

const run = (data: A) => {
  if (!("key1" in data)) return

  data
  // ^? (parameter) data: { key1: string; } | { key1: string; key4: string; }

  if ("key2" in data) {
    data
    // ^?
  }

  data
  // ^? (parameter) data: { key1: string; }
}
```

### 🙁 Actual behavior

The type of `data` change above and below the last if statement

### 🙂 Expected behavior

the type of `data` should be the same above and below the last if statement

**Comment by Andarist** [comment]
It's not exactly inconsistent. Your first check leads to an early return while the second one doesn't.

At the last position of `data` u essentially end up with a union of two types:
```ts
type PreIfStatement = { key1: string; } | { key1: string; key4: string; }
type FromWithinTheNarrowingIfThatCarriesOverPastItsBlock = ({ key1: string; } | { key1: string; key4: string; }) & Record<"key2", unknown>

type FinalType = PreIfStatement | FromWithinTheNarrowingIfThatCarriesOverPastItsBlock
```

And it just happens that this is a subject to subtype reduction and so you end up with just `{ key1: string; }`. As per [Ryan's comment](https://github.com/microsoft/TypeScript/issues/50171#issuecomment-1205468199):
> Subtype reduction isn't required to happen, but is allowed to happen at any point. There's not a bug here.

**Comment by fatcerberus** [comment]
I was wondering where that foreign `Record<'key2', unknown>` came from then I finally realized that the `{ key2: string }` case is ruled out by the early return so `key2` has to be resynthesized inside the second `if`.  I had actually forgotten that `'x' in foo` can synthesize new properties now.

**Comment by jcalz** [comment]
I think we can say that `in` operator narrowing is *intentionally* inconsistent.
