### ISSUE TITLE
Class Instance types resolved differently depending on how they are accessed

### ISSUE THREAD

**Issue by eliasm307** [microsoft/TypeScript#54582]
# Bug Report

### 🔎 Search Terms

- this types not resolved
- class instance types not resolved 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Classes"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/C4TwDgpgBAYgrgOwMbAJYHsEHkEBsQA8MAfFALyxQQAewECAJgM5QAUAdJwIYBOA5kwBcULghABKcqVEgoAfkrCEEAG4QeAWABQ2pLi5MWABV71gUAN7aoNqAwh7TVNQmABlVHwRdgcHhCFLa1sQsFNXDy8fPwhhVhUuXGEmYB5UBD5JMlIVdFQGYJsAX21CqAAzVH8AURdgAgA5LgBbaBo6RhYAawgQdHKoYAALVCYAbQByVTNI719-JgmAXWJWMpCmTzmYptbhXYgAGnXbTnZeAWETHhaIOh4mIkQUDGw8QmHRyemIreiF5ZjA4rYhlcTCXL5SwlLQw3T6QxQADCI1wDCotHozCg1zMQS0IXsjn8zhmf3mASu4WA3zqs3+AWWUAAZPiQiEkKiGPSKXEEkkoAg4M0AEbqLI5PIFAm2OEymytYboBgAdVQwwAIhBylw4LhgAAVEZMViSKzy9kAektUEAMuQiFBwRKDcDQBDocwLdC4NTo8o8dDNKAAA0+TGDJxsoEgUE2fHIg2NtLJUQpiyWk05qDRPJiy0jUGtIQAenICwWi-aGOgAoKPVAvT7oHHtiSLsKzCx-YGQ2GIxaQmH2JUanVWBMwv5fqm84coAAiefiAtDkcQWpmcdZnPk2dQACMy4tcpCiqGyrVwyRBjoDCNo1YYeEKOzDDNUArNsAoOQNgLetQsNG0CiOiTDngA7iw4FDD4UDqg6viJPgcFQUM9C9sawYoVASA3hA6LAOgibNrcOEIkwK6urGngJkB-Q4cm06toyGYTNu3K7v4+YDrYRa2KWpQ8TYRY-o2AEIU6uDUTObb8B2rioehoaYdhuEpPhgxEcMJGtGRBgUUJiajMOVTrmOE7UrmXFzouR7srYq6mRurhblyVkQBMc6HmUMJykS+gkkgmApDhz5coJIm-kw-61kBIiMLGEGobB8FcI6SGyKMGL3N4uDIZgxFwQgKSiEgEDaHFca0a69FIIx7icSxmZuY13F8TYAk6FokVibWaWIVJLYMiIcmtApUDQehuF5Rp7TqLl+UIIV6Qlcg5VaEgJmjpu86TimzHzjZS66FtZmbmxLUyR5XniEAA)

### 💻 Code

```ts
type FunctionOnly<F> = F extends (...args: any) => any ? F : never

class Parent {
    declare eventSignatures: {
        parentSignature: (val: string) => void
    }

    fireEvent<Name extends keyof this['eventSignatures']>(
        signatureName: Name,
        ...args: Parameters<FunctionOnly<this['eventSignatures'][Name]>>
    ): void {}
}

class Child extends Parent {
    declare eventSignatures: Parent['eventSignatures'] & {
        childSignature: (val: number) => void
    }

    methodWithDefaultThis() {
        // ❌ actual type not resolved from `this`
        type sig = this['eventSignatures']['childSignature']
        //    ^?
        
        // ❌ does not resolve signature arguments from `this`
        this.fireEvent('parentSignature', "")
        this.fireEvent('childSignature', 1)
    }

    methodWithCastedThis(this: Child) { 
        // ✅ resolves type and shows what it actually is when `this` is casted to the same class
        type sig = typeof c['eventSignatures']['childSignature']
        //    ^?

        // ✅ resolves actual signature arguments when `this` is casted to the same class
        this.fireEvent('parentSignature', "")
        this.fireEvent('childSignature', 1)
    }
}

declare const c: Child

// ✅ resolves type and shows what it actually is externally on the instance
type sig = typeof c['eventSignatures']['childSignature']
//    ^?

// ✅ resolves actual signature arguments when called externally on the instance
c.fireEvent("parentSignature", "")
c.fireEvent('childSignature', 1)
```

### 🙁 Actual behavior

When trying to resolve function property types of an object member from `this`  the actual types don't get resolved. I don't know if this is limited to just function properties of an object member.

### 🙂 Expected behavior

The types should be resolved as happens when `this` is casted to the same type as the local class or externally on an instance. Where or how a type is accessed from an instance shouldn't affect the type?

**Comment by fatcerberus** [comment]
So the thing here is that `this` is, by default, generic and should be thought of as `this extends Class`, which means `this["foo"]` tends to get deferred because you might be calling it on a subclass that has a different, narrower type for `foo`.

**Comment by jcalz** [comment]
It's the intended behavior of [polymorphic `this`](https://www.typescriptlang.org/docs/handbook/2/classes.html#this-types) and not a bug.

**Comment by eliasm307** [comment]
Hi, thanks for the feedback.

However in the linked docs in this section https://www.typescriptlang.org/docs/handbook/2/classes.html#this-types

There's a statement saying "In classes, a special type called this refers dynamically to the type of the current class", so does this mean this is innacurate as `this` is not exactly the type of the current class?

**Comment by eliasm307** [comment]
> So the thing here is that `this` is, by default, generic and should be thought of as `this extends Class`, which means `this["foo"]` tends to get deferred because you might be calling it on a subclass that has a different, narrower type for `foo`.

Is this not true outside of the class also? e.g. one could do the following with polymorphism in TS, so the behaviour isn't consistent. In the case of class types would this mean no type should be usable externally also since "you might be calling it on a subclass that has a different, narrower type"? 

```ts
type FunctionOnly<F> = F extends (...args: any) => any ? F : never

class Parent {
    declare eventSignatures: {
        parentSignature: (val: string) => void
    }

    fireEvent<Name extends keyof this['eventSignatures']>(
        signatureName: Name,
        ...args: Parameters<FunctionOnly<this['eventSignatures'][Name]>>
    ): void {}
}

class Child extends Parent {
    declare eventSignatures: Parent['eventSignatures'] & {
        parentSignature: (val: "foo" | "bar") => void
    }
}

function foo(instance: Parent) {
    type sig = typeof instance['eventSignatures']['parentSignature']
    //    ^?

    // allows any string
    instance.fireEvent("parentSignature", "anything")
}

foo(new Child()) // argument instance event signature is narrower here but wide type used inside function
```

Should this also be true for using `this` anywhere in a class since a subclass could have overridden members? e.g.
```ts
class Foo {
    constructor() {
        this.method("anything")
    }
    
    method(val: string) {}
}

class Bar extends Foo {
    method(val: "narrow") {}
}

new Bar()
```

Since it's possible to cast `this` into the type of the current class (which does not change anything in terms of the available class API) it seems odd why this changes anything since the same statements apply, ie casting `this` to `Foo` also means any member used could be "on a subclass that has a different, narrower type".

I dont know if I'm missing something, but I'm not understanding what problem this restriction is preventing specifically since similar behaviour is allowed in different contexts, so if anyone can elaborate I would be grateful.

**Comment by fatcerberus** [comment]
Like I said, think of it as a similar case to `this extends Class`.  It’s implicitly generic.  While it’s true that subtypes are assignable to supertypes, `T extends Foo` clearly behaves differently than a direct reference to `Foo`.  It’s the same thing here.

**Comment by eliasm307** [comment]
@fatcerberus Thanks for the reply. I'm trying to understand your message and tried the following, however, I'm not seeing the difference, can you please provide some examples of what you mean by "T extends Foo clearly behaves differently than a direct reference to Foo"?

```ts
class Foo {
    constructor() {
        this.method("anything")
    }
    
    method(val: string) {}
}

class Bar extends Foo {
    method(val: "narrow") {}
}

function normal(instance: Foo): void {
    instance.method("anything")
}

function generic<T extends Foo>(instance: T): void {
    instance.method("anything")
}

normal(new Bar())
generic(new Bar())
```

**Comment by eliasm307** [comment]
Oh is this what you mean? If it is I still wonder if this makes sense, from my understanding since Typescript is structurally typed, the `normal` function declaration's argument implicitly means the `instance` argument can be any type that extends `Foo` which is why we can provide subclasses to the function.  So its still not clear to me why explicitly defining the argument as extending `Foo` changes its type behaviour? 

Does this make sense to you or is it just a thats how it is thing?

```ts
class Foo {
    declare eventSignatures: {
        parentSignature: (val: string) => void
    }
    constructor() {
        this.method("anything")
    }

    fireEvent<Name extends keyof this['eventSignatures']>(
        signatureName: Name,
        ...args: Parameters<FunctionOnly<this['eventSignatures'][Name]>>
    ): void {}
    
    method(val: string) {}
}

class Bar extends Foo {
    
    declare eventSignatures: Parent['eventSignatures'] & {
        parentSignature: (val: "foo" | "bar") => void
    }

    method(val: "narrow") {}
}

function normal(instance: Foo): void {
    instance.method("anything")
    instance.fireEvent('parentSignature', "")
}

function generic<T extends Foo>(instance: T): void {
    instance.method("anything")
    instance.fireEvent('parentSignature', "") // type error
}

normal(new Bar())
generic(new Bar())
```

**Comment by eliasm307** [comment]
Additionally it seems in some cases the compiler does implicitly resolve types from `this` which makes this behaviour more confusing

```ts
type FunctionOnly<F> = F extends (...args: any) => any ? F : never

class Parent {
    declare eventSignatures: {
        parentSignature: (val: "foo") => void
    }

    fireEvent<Name extends keyof this['eventSignatures']>(
        signatureName: Name,
        ...args: Parameters<FunctionOnly<this['eventSignatures'][Name]>>
    ): void {}

    addListener<Name  extends keyof this['eventSignatures']>(
        signatureName: Name,
        handler: (...args: Parameters<FunctionOnly<this['eventSignatures'][Name]>>) => void
    ): void {}
}

class Child extends Parent {
    declare eventSignatures: Parent['eventSignatures'] & {
        childSignature: (val: "foo" | "bar") => void
    }

    method() {
        this.addListener("parentSignature", v => {
            // it knows the type?
            const num: number = v; // error
            const str: "foo" = v; // not an error?
            const str2: "bar" = v; // error
        })
        this.fireEvent("parentSignature", "foo") // now it doesnt like it?
    }
}
```

**Comment by AdalynsDad** [comment]
Thank you for your time,
                      Adam Wilkolaski
