### ISSUE TITLE
`export { a as "hello world" }` is valid JavaScript but invalid TypeScript

### ISSUE THREAD

**Issue by jcbhmr** [microsoft/TypeScript#54584]
# Bug Report

### 🔎 Search Terms

"es2020"
"export as string"
"import as string export as string"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "exports"

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=5.1.3#code/MYewdgzgLgBAhjAvDAzAFgNwCgCmAPABxACdYBveeCGAIgAscAbRkGAdxMYBMaYBfDEA)

### 💻 Code

```ts
// This typescript code...
const a = 34;
export { a as "hello world" };
```

### 🙁 Actual behavior

```js
// ...generates this invalid JavaScript code.
const a = 34;
export { a as  } from "hello world";
;
```

The input was **valid JavaScript** so I would _expect_ (intuitively) for it to be valid TypeScript. This is currently not the case.

### 🙂 Expected behavior

```js
// I expected this JavaScript code to be generted:
const a = 34;
export { a as "hello world" };
```

Current behavior in browsers and Node.js works with this syntax!
```js
// But running this in the DevTools or Node.js REPL works just fine.
await import("data:text/javascript," + encodeURIComponent(`
const a = 34;
export { a as "hello world" };
`))
```
![image](https://github.com/microsoft/TypeScript/assets/61068799/03ba2379-ad92-4e67-8772-43fbbaf8a104)
![image](https://github.com/microsoft/TypeScript/assets/61068799/b8a8b9dc-9ed2-4a23-be0a-871d994f0b54)

JavaScript seems to allow strings as import/export names:
```js
import { "hello world" as a } from "./hello.js"
export { a as "hello world" };
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#syntax
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#syntax

**Comment by Josh-Cena** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/40594

**Comment by jcbhmr** [comment]
Darn! I didn't search thoroughly enough. 🤦‍♂️
