### ISSUE TITLE
Array.reduce doesn't allow for a different return type without providing an initial value

### ISSUE THREAD

**Issue by ADSmith-0** [microsoft/TypeScript#54589]
# Bug Report

### 🔎 Search Terms
array.reduce, reduce, typescript reduce

### 🕗 Version & Regression Information
5.0.4
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about array.reduce/reduce

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/MYewdgzgLgBCBGArGBeGBtAUDGBvMAhgLYCmAXDAEQAWJANnSJQL4A02ehpFlUtATiRaYAugG5MmAPRSYAdQJgoJACYwAbgToBXcjADktBiFYw+JQfskyYAYXDACsMCFhbGAd1Ux4JR9ogSAwJgYH0YAEsIGEU4JD8oTAREADpBFW1gEgAKbJDgU006AEpUAD4Y0JTQMEcobP1TRo0tFK4SYuKJaVkAZRIoKAiwAHMzWjMATwAHIIJo6H5hsZc3Yy81X39AmBdIsAihrRadIKiYaf4QdQiVVSSkNNVMkgAeReWy3PzCrVKUCr5aoOJwNJq-OhtYgdLrWWQAQXW92STwyWXeUCWoy+eVCEP+gKqNTqYIMEKhpGKTX0XRgMhA2ig00ZFGaRkYpnMlgeqXSL2+eJOBMqwGBtVBzWaRQpHWptPpjOZUFZpnZJnGFhIVh6dlivhgHhA-AA1t4CFdtGA1B5DtQYBA6BEstkAExUnyMg0MuibIIHLJmEC7VwwagEdRBKBBlRBvhOIA)

### 🙁 Actual behavior
```ts
const obj = [
  {name: "hello"},
  {name: "there"}
];

// Wanted value: 'hello, there'

// Concat not allowed because 'acc' is an object
obj.reduce((acc, val) => acc.concat(', ', val.name));

// Setting the type as string not allowed because no initial value is provided
obj.reduce<string>((acc, val) => acc.concat(', ', val.name));

// Allowed
obj.reduce<string>((acc, val) => acc.concat(', ', val.name), ''); //output: ', hello, there'
obj.reduce((acc, val) => acc.concat(', ', val.name), ''); //output: ', hello, there'

// Can be worked around with slice(2), but would be nice to not have to do that
```

### 🙂 Expected behavior
```ts
obj.reduce<string>((acc, val) => acc.concat(', ', val.name));
// expected output: 'hello, there' with no TS errors
```
It might be that I'm using it incorrectly, I'm quite new to TypeScript, but when I read the MDN docs [they said that the initial value is optional](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce), so I thought that maybe with TS it should be too

**Comment by fatcerberus** [comment]
The initial value *is* optional, but if it’s not provided then the first entry in the array is used as the initial value (in this case an object) and enumeration starts from the second element.  So the types accurately reflect the runtime behavior here.

**Comment by ADSmith-0** [comment]
Yeah that's true, maybe I should have flagged it as a feature request then, I just feel like since array.reduce is pretty frequently used with type conversion in mind it would be clearer and nicer to be able to write
```
reduce<string>((acc, val) => acc.concat(', ', val.name));
```
instead of 
```
reduce<string>((acc, val) => acc.concat(', ', val.name),'').slice(2);
```
but maybe it's more of a JS issue than a TS one

**Comment by fatcerberus** [comment]
I don’t see any way that can work - you need to extract a string from the first object, and nothing in the code you propose writing does that.  How would it automatically know to read the first string from `obj.name` instead of, say, `obj.arglbarghl`?
