### ISSUE TITLE
Function parameters cannot use both generics, generic constraints and default values

### ISSUE THREAD

**Issue by CwRv07** [microsoft/TypeScript#54598]
# Bug Report

### 🔎 Search Terms

generics, generic constraints and default values

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/PQKgUABBCyCeEFEB2BzANgSwM4AsLYiQHsAXCFIogEwgEMkaBJCAW1vh1oDcBTV7AE48ADkKw8kJHjRI4+AMyJo0RAO4ZUgLH+wkCM1X0yJIhACu48hJ4CMAYyz4kEIgKrWIxiPNq2MmErRSHnIesMJ8trRotqZogRhETkTyEEIkpgJOXFGmPFgANBC69EwQBpIeJraJWCQCtBp0DI4YJBhR2HyyfG7esSQOigKWSNZ2WDpQAEKmZMSqepZk9BDWAi4AXISmLABG7pFIxGT7dFhYGCijMibdI2O2EAAqTaWj0pVmFrQQWKa7tji52cKSQO32w08GlqhnaQSeugAyiZmJxeHQIABHXK1BJIQrYJAAcjILHgvVo-Qg2TQuRBEAAjBi-gCgQ5kts9tYAPyQEDAHQkMJ8OAAJR46UyT2FAB4ngA+CAAXmeAG4dPJTEhbG1El5KHLVgAPKQMBxgrnDFUM+UACgtWxe1oAlFsxRKMkhpeE5YqAN66NKezlgAC+YGqSFqHjyJAADMr9URbc6IzUjLGmSrFMmAEypnRgUC6RhOO4SUrVWI0RJoeA+HAYHjosl0DAsCC7WB8gWa7W6py7WgCQ08E0V83g9zWu0O56Jpm0BxPV0wWDiyVe2UKiABqBBzIh0NAA)

### 💻 Code

```ts
type MyReturnType<T> = T;

function foo<T extends number = 1>(num: T = 1): MyReturnType<T> {  // error: Type 'number' is not assignable to type 'T'
  return num
}
const test0 = foo()
const test1 = foo(2)
```

### 🙁 Actual behavior

  I want to use generics in order to facilitate the type calculation of return values, and I want to constrain and initialise the defaults for generics.
  But now I get an error: ”number cannot be assigned to the generic T and I need to use a subclass of number to instantiate T“
  So I have a question, isn't my default value of 1 a subclass of number?

### 🙂 Expected behavior

  There is no error reported, or a more accurate error reported to show me how to implement the operation

**Comment by fatcerberus** [comment]
> number cannot be assigned to the generic T and I need to use a subclass of number to instantiate T

It's not telling *you* to use a subtype of `number`, it's telling you the *caller of your function* might use a type that isn't compatible with the default value.  As I demonstrated [in the other issue](https://github.com/microsoft/TypeScript/issues/54597#issuecomment-1585483802)
