### ISSUE TITLE
For es6 targets, created import statements should now have the `.js` postfix

### ISSUE THREAD

**Issue by iislucas** [Microsoft/TypeScript#5460]
According to https://github.com/google/traceur-compiler/issues/1997 is seems that es6 requires that import statements are fully resolved to concrete filename. It seems that omitting the `.js` postfix is no longer supported. So it seems that typescript compiler, for a es6 target, should be emitting import statements in the code that have the fully resolved js filename (i.e. postfix should now include `.js` in the output file).

**Comment by mhegazy** [comment]
This is not really ES6, this is the module loader spec. the spec is still WIP. we are aware of these changes and we are keeping an eye out. once the spec has progressed in the standardization process we will put the changes in the emitted JS code.

**Comment by mhegazy** [comment]
handling this is tracked by #4595
