### ISSUE TITLE
Invalid control flow error when variable updated in function with side effect

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#54612]
# Bug Report

### 🔎 Search Terms

control flow if const assignment function no overlap

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/MYewdgzgLgBAygFQIIIKIH0BqSAyMC8MADDAIYQyiRQDcAUFdPMmugPIBCAUgTAIxkKjWnTpQAngAcApvCikos-HRgwAPjAkyQAM2YoM2HCvWap03ftacu9UQBtpsaAukAuOa96IDWXHZ0AVzBgKABLcBhpMEUAJwAKAEoYAG8TF0VvFgwbegBfUWi4pLswvXiMpXxCH2tuZLTVRhBHADp7EABzCvlFRPy6IA)

### 💻 Code

```ts
const STATE_VAL = 0 as const;
const STATE_OBJ = 1 as const;

type State =
  | typeof STATE_VAL
  | typeof STATE_OBJ;


let state: State = STATE_VAL;

function enter() {
  state = STATE_OBJ;
}

enter();

if (state === STATE_OBJ) {
  console.log(state);
}
```

### 🙁 Actual behavior

```
This comparison appears to be unintentional because the types '0' and '1' have no overlap.
```
at the if statement

### 🙂 Expected behavior

No errors

**Comment by nicolo-ribaudo** [comment]
Oh this has been discussed in https://github.com/microsoft/TypeScript/issues/9998. It's very annoying, but I guess the only solution is `@ts-ignore`

**Comment by Josh-Cena** [comment]
@nicolo-ribaudo The actual issue is that `state` is optimistically narrowed. You can use `let state = STATE_VAL as State` to make it work.
