### ISSUE TITLE
Incorrect key inference while using ForInStatement [for...in] with a readonly object.

### ISSUE THREAD

**Issue by vahan-sahakyan** [microsoft/TypeScript#54631]
## Bug Report

Please consider the `for...in` statement to infer the `key/prop` of an object, especially when it is readonly.
In my opinion, In this case scenario when the object has a literal value, it cannot have dynamically modified keys.
Perhaps there can be cases that I'm missing but it would be nice to have some sort of inference here.

### 🔎 Search Terms

`for..in`, `for...in`, `for in`, `forin`, `ForInStatement`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `for...in`

### 💻 Code

```ts
const person = {
    id: 0,
    name: "Joe"
} as const;

type PersonKey = keyof typeof person;

for (const key in person) {
    person[key] // 🔴 does not infer the keys implicitely
    person[key as PersonKey] // 🟢 works only via explicit type casting
}

```

### 🙁 Actual behavior

`key` is inferred as `string`

### 🙂 Expected behavior

`key` is inferred as `'id' | 'name'`

**Comment by MartinJohns** [comment]
The current behaviour is working as intended. Objects are not sealed, there might be more properties present than the ones according to the type definition.

**Comment by vahan-sahakyan** [comment]
@MartinJohns 
So does that mean if we seal the object we have to get the expected result?

How should the code behave in case we specify the type of the keys as a union beforehand if you will:

```ts
const person: Record<"id" | "name", unknown> = {
    id: 0,
    name: "Joe"
} as const;
```

I mean there should be a spot to make it possible and achieve the result at least having some prerequisites.

**Comment by MartinJohns** [comment]
You can't seal the object. There's no way to represent immutability in TypeScripts type system.

**Comment by fatcerberus** [comment]
Also see #12936
