### ISSUE TITLE
Types are not correctly inffered?

### ISSUE THREAD

**Issue by HarelM** [microsoft/TypeScript#54639]
# Bug Report

### 🔎 Search Terms
VideoFrame

### 🕗 Version & Regression Information

This started failing on latest version 5.1.3 after everything passed in 5.0.4.
- This changed between versions 5.0.4 and 5.1.3

### ⏯ Playground Link

Couldn't reproduce it on the playground, not sure why, but I can reproduce it easily with my project - maplibre.

### 💻 Code

An example of the problem can be seen here:
https://github.com/maplibre/maplibre-gl-js/blob/0df72fcef8b225a190baebc3d35a1cede9f09c29/src/util/browser.ts#L28
The error I get is:

```
src/util/browser.ts:28:61 - error TS2339: Property 'width' does not exist on type 'CanvasImageSource'.
  Property 'width' does not exist on type 'VideoFrame'.

28         return context.getImageData(-padding, -padding, img.width as number + 2 * padding, img.height as number + 2 * padding);
```

### 🙁 Actual behavior

There's an error when we compile the project using a simple `tsc --noEmit` command

### 🙂 Expected behavior

This should pass as it did in 5.0.4 - `CanvasImageSource` should have `height` and `width` properties.

**Comment by RyanCavanaugh** [comment]
A possible value of `CanvasImageSource` is a `VideoFrame`, and `VideoFrame` does not have width (it has `codedWidth` and `displayWidth` instead)

**Comment by HarelM** [comment]
Thanks for the super fast response!
When I click on the `CanvasImageSrouce` in vscode I get to the following file and definition:
![image](https://github.com/microsoft/TypeScript/assets/3269297/0e340b73-f941-45ff-bf93-cd0bcbb4494e)

Which doesn't have `VideoFrame`.
So was this introduced as part of 5.1.3 in order to align with the MDN specifications? https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images

**Comment by RyanCavanaugh** [comment]
It sounds like your VS Code is not using the same TS version as commandline

**Comment by HarelM** [comment]
I've managed to solve this on my project by reducing the possible types of a method.
Thanks for the help.
Closing.
