### ISSUE TITLE
fix(dts): Update type of `ArrayBuffer`

### ISSUE THREAD

**Issue by indrajitbnikam** [microsoft/TypeScript#54636]
# lib Update Request

The problem is that proper types are not available when `Resizable ArrayBuffer` need to be created by passing `options` in the constructor.

## Configuration Check

My compilation *target* is `ESnext` and my *lib* is `the default`.

## Missing / Incorrect Definition

**`ArrayBuffer`** Constructor signature.

## Sample Code

```TypeScript
const buff = new ArrayBuffer(10, {
  maxByteLength: 100,
});

console.debug(buff.resizable);
console.debug(buff.byteLength);

buff.resize(100);
console.debug(buff.byteLength);
```

## Documentation Link

You can check the signature over here.

[ArrayBuffer() constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/ArrayBuffer)

**Comment by RyanCavanaugh** [comment]
# Please post code, not screenshots of code.

This isn't part of a merged ECMAScript 2015, see https://github.com/tc39/proposal-resizablearraybuffer . This needs to go into ESnext first.

**Comment by indrajitbnikam** [comment]
Sorry about the screenshots. I'll update the description with code.

**Comment by julien-c** [comment]
Note that https://github.com/tc39/proposal-resizablearraybuffer has landed in the spec now. So I think we could move ahead with this now?

**Comment by guest271314** [comment]
Reproducible in TypeScript playground 

```
const buffer = new ArrayBuffer(0, { maxByteLength: 1024 ** 2 });
```

TypeScript error

```
Expected 1 arguments, but got 2.
```

**Comment by guest271314** [comment]
What's the status on this?
