### ISSUE TITLE
Quotes in JSX output are not properly escaped

### ISSUE THREAD

**Issue by ajpalkovic** [Microsoft/TypeScript#5463]
Example test case:
```
console.log(typescript.transpileModule('var x = "hello"; <h1>"{x}"</h1>;', {
  compilerOptions: {
    jsx: 2, // React
  },
  fileName: 'test.tsx'
}));
```

Output:
```
'var x = "hello";\nReact.createElement("h1", null, """, x, """);\n'
```

The triple quotes in the generated output is wrong, it needs a backslash before the middle quote.

**Comment by mhegazy** [comment]
I do not see this on latest: `typescript@1.8.0-dev.20151029`

this is what i get:

```shell
{ outputText: 'var x = "hello";\r\nReact.createElement("h1", null, "\\"", x, "\\"");\r\n',
  diagnostics: undefined,
  sourceMapText: undefined }

```

**Comment by ajpalkovic** [comment]
O, fancy, yea, sorry I should have specified a version number, I was on
1.6.2 which is the latest stable release I think?

**Comment by mhegazy** [comment]
it should be fixed in next release 1.7.3, and it is already fixed in nightlies (`typescript@next`).

**Comment by ajpalkovic** [comment]
Cool, thanks.  When (roughly) is the next release?

**Comment by mhegazy** [comment]
We try to have a major release every 6-8 weeks. no hard dates yet, but should be a couple of weeks or so.

**Comment by RyanCavanaugh** [comment]
For future finders: #5132
