### ISSUE TITLE
Types include unresolved imports will be turned into `any`

### ISSUE THREAD

**Issue by so1ve** [microsoft/TypeScript#54630]
# Bug Report

### 🔎 Search Terms

any, unresolved

### 🕗 Version & Regression Information

- This changed between versions 5.0.4 and 5.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3&ssl=11&ssc=43&pln=11&pc=13#code/C4TwDgpgBAkgzgQQHYgDwBUB8UC8UBGA9oQDYQCGSUEAHsBEgCZxQAU61dDzUSEAbhABOUAPxRgQgK7QAXFABm5EnAgBKMROlzFy1QG4AUKEhQACgEsAxgGsAcoWDI0CADRQAQtjzxnqBNi09EwskjKaHlDyCEaGAPRxUAACwHAAtBYA5kiEQhDG4NDkuFAWALZgucCsAOT8MjVqAHQA4iSE+MoAwoQVhHxIqfGJUFAAeqKGBaZtHd29lQOpuMOj45MAkAnJqRnZufkblrYOTiio5ZVC1XUNzbOdJD19S3DuAN4AvphTJtAP8xeDFSACYVttRhNDFtEil0lkcnlocd7I4-JQQB9voYgA)

### 💻 Code

```ts
type IsAny<T> = boolean extends (T extends never ? true : false) ? true : false;
type PickNotAny<A, B> = IsAny<A> extends true ? B : A;

// @ts-ignore
type a = import('vue').GlobalComponents
//   ^?

type GlobalComponents =
//   ^?
	// @ts-ignore
	PickNotAny<import('vue').GlobalComponents, {}>

type GlobalComponents2 =
//   ^?
	// @ts-ignore
	PickNotAny<any, {}>
```

### 🙁 Actual behavior

 ¯_(ツ)_/¯

### 🙂 Expected behavior

They should not behave differently

**Comment by so1ve** [comment]
Update: not right actually. Types include unresolved imports will be turned into `any`, no matter what they do. So a shorter demo: [Link](https://www.typescriptlang.org/play?ts=5.1.3#code/C4TwDgpgBAkgzgQQHYgDwBUB8UC8UBGA9oQDYQCGSUEAHsBEgCZxQAU61dDzUSEAbhABOUAPxRgQgK7QAXFABm5EnAgBKMROlzFy1QG4AUIYD0JqAAFgcALQBLAOZJCQiIdCQo5XLEQpUdgC2YC7ArADk-DLhagB0AOIkhPjKAMKEwYR8SNaYhkA)

**Comment by johnsoncodehk** [comment]
Just for to make it clearer:

```ts
type IsAny<T> = boolean extends (T extends never ? true : false) ? true : false;

type A = IsAny<any>; // ✅ type A = true
type B = IsAny<import('vue').GlobalComponents>; // ❌ type B = any
type C = IsAny<import('vue').GlobalComponents & {}>; // ✅ type C = true
```

**Comment by RyanCavanaugh** [comment]
There are no specific guarantees on what happens when there is an error type in your program.

**Comment by so1ve** [comment]
That's true. However, the type of it is literally `any`, but it doesn't behave like `any`.

**Comment by so1ve** [comment]
Maybe you are right!
However I still prefer the former behavior. Typing it as `any` but it does not behave like `any` ismisleading. What's more, because volar imports the `GlobalComponent` interface from three different packages and the users maybe install one of them only (detecting whether they were installed without type system will increase workload), we rely on the former behavior to detect whether they were installed. If not, the interfaces are simply `any` and we can fallback to an empty interface. But in 5.1.3 we'll need a hack to fix that. In short, the old behavior is useful in some cases, but that in 5.1.3 is not intuitive.

**Comment by fatcerberus** [comment]
My suspicion is that any check that *requires* a `@ts-ignore` in the source to work at all will never be a supported use case.  You are more or less in “undefined behavior” territory; here be dragons.
