### ISSUE TITLE
`forceConsistentCasingInFileNames` doesn't work as advertisted

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#54642]
# Bug Report

### 🔎 Search Terms

- forceConsistentCasingInFileNames
- casing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `forceConsistentCasingInFileNames`

### 💻 Code

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true
  },
  "files": ["./src/main.ts"]
}

```

`src/main.ts`:
```ts
// Casing is incorrect here, but there's no type error (on macOS at least).
import { foo } from "./FOO";

console.log(foo);

```

`src/foo.ts`:
```ts
export const foo = 1;

```

### 🙁 Actual behavior

Testing on macOS (case insensitive file system), there is no type error (in my editor and when I run `tsc`).

### 🙂 Expected behavior

There should be a type error due to incorrect casing for `import { foo } from "./FOO";`, as per the documentation for `forceConsistentCasingInFileNames`:

> When [`forceConsistentCasingInFileNames`] is set, TypeScript will issue an error if a program tries to include a file by a casing different from the casing on disk.

— https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames

**Comment by MartinJohns** [comment]
Or alternatively, the documentation should be fixed, because as far as I know the behaviour is intentional and will only warn about mixing casing within your code base (link to issue mentioning this missing).

You want #21736.

**Comment by fatcerberus** [comment]
Current behavior may not be intentional: https://github.com/microsoft/TypeScript/issues/21736#issuecomment-514741973
