### ISSUE TITLE
5.1.3 new "feature"? Branded types are preserved in `const` template literal

### ISSUE THREAD

**Issue by conorbrandon** [microsoft/TypeScript#54648]
# Bug Report

### 🔎 Search Terms

branded, interpolation, 5.1.3

### 🕗 Version & Regression Information

This changed between versions 5.0.4 and 5.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/C4TwDgpgBAylC8UAGBLAJgfQCQG8DOwATigHYDmUAZFDhgEaECGJaAXFAEQCSAIhwL78kAbgBQAenFRpAPQD8otBADGAG0aFoygPYkCUdOwLFyVGvSYt23PvzE69wKHgTJ02HOiFRGLhwTFJaVk5IA)

### 💻 Code

```ts
type S = `id_${string & {_brand: "ID"}}`;
//   ^? type S = `id_${string & { _brand: "ID"; }}`
declare const id: string & {_brand: "ID"};
const s = `id_${id}` as const;
//    ^? const s: `id_${string & { _brand: "ID"; }}`
```

### 🙁 Actual behavior

The intersected brand is preserved during string interpolation for variables and types!

### 🙂 Expected behavior

Pre 5.1.3, the intersected brand always got removed during string interpolation for variables and types.

This is part bug report and question. My question being in future versions, will this behavior be preserved? I wrote a clunky generic function and type to do this exact thing because I found it valuable, but I'd much rather rely on native behavior if this is going to stick around 👀

**Comment by RyanCavanaugh** [comment]
I think this was (unintentional?) fallout from #48034 / #52345

**Comment by jakebailey** [comment]
I think this was intentional? (I at least explicitly added it and tests for it, though in the course of fixing other stuff.)

Also @weswigham

**Comment by jakebailey** [comment]
Though, I'm not sure how this should interact with as const... I guess it's a noop and that's normal?

**Comment by jakebailey** [comment]
The relevant PR is https://github.com/microsoft/TypeScript/pull/52836, note that the tests contain effectively exactly what the original post contains, a branded type inside a template.

**Comment by conorbrandon** [comment]
Ah, template literals, that's the word I was looking for (instead of string interpolation). Had a brain fart, my apologies.

**Comment by ahejlsberg** [comment]
I'm reopening this one. The original issue, #48034, was that we're not "untagging" literal types when they occur in template literal placeholders. In other words, the expectation was that

```ts
type S1 = `xyz${"a"}`;
type S2 = `xyz${"a" & { tag: any }}`;
```

both resolve to `"xyza"`. Originally, `S2` would resolve to `string`. Currently, `S2` resolves to `` `xyz${"a" & { tag: any }` ``. Neither of those are right, `S2` should just resolve to `"xyza"`.

**Comment by jakebailey** [comment]
I guess that implies that #52836 is to be reverted? 🙁

There are some performance considerations (see #52345), so hopefully we don't regress that back again. That and the branded use case, and #53427, etc.

**Comment by ahejlsberg** [comment]
> I guess that implies that #52836 is to be reverted? 🙁

I think so. But we still want to revert #48044 also. I think all we need is support for "popping tags" on literal types (such that `"a" & { tag: void }` behaves the same as just `"a"`).

I really don't want to mess with supporting generalized intersections in placeholders. It doesn't add much in terms of expressiveness, but it adds a lot in terms of complexity and possible performance issues related to normalization.

**Comment by ahejlsberg** [comment]
There's also #54188 which I really don't like. We decided to allow `string & {} | "a" | "b"` to not reduce to just `string` because the pattern was in use in some popular DT packages. But it's not at all clear we want to broaden this support to template literals--and even if we did, I would think it's the template literal itself that should be intersected with `{}`, not one of the placeholders.

**Comment by jakebailey** [comment]
I guess we'll talk about it in the design meeting, but I can't help but feel a little sad given this issue was about the construct being useful, and I found the branded case to be a valuable idea: https://github.com/microsoft/TypeScript/blob/e170bc59d4ba0d335ce86f66296bec71c5018317/tests/cases/compiler/templateLiteralIntersection2.ts

I'll have to resurrect the perf test I had that motivated my follow-up.

**Comment by ahejlsberg** [comment]
@jakebailey I saw that test, but I'm not sure I've seen an actual user request for the feature. Other than just stripping tags. I'm just not convinced anything beyond that is worth the complexity.

**Comment by jakebailey** [comment]
Just to link it (since it's in the middle of a thread), https://github.com/microsoft/TypeScript/issues/52345#issuecomment-1407216732 is the perf case I had been looking into.

**Comment by ahejlsberg** [comment]
My inclination was otherwise, but since the consensus in the design meeting trended towards preserving tagged literals in placeholders, I'm going to go along. We still need a few fixes however, such as #53427 and not descending into template literals in `getGenericObjectFlags`. I will put up a PR to that effect.

**Comment by jakebailey** [comment]
Funny, I had the opposite takeaway from the meeting given the potential perf benefit 😅

**Comment by ahejlsberg** [comment]
My chief performance concern was the overhead of descending into template literal types in `getGenericObjectFlags` and adding the `objectFlags` property to it. I'm backing that out in my PR as it isn't necessary. Beyond that, there is of course some overhead associated with preserving tagged literal types in placeholders, but you only incur that overhead if you use tagged literal types. It seemed like most folks liked the preservation and I'm willing to go with it.

**Comment by davidAtInleague** [comment]
Hi, I saw some minor breakage related to this on upgrading to 5.3.2. Prior to 5.3.2, for some T and U of type (string & {...}), T <: U meant that \`${T}\` <: \`${U}\`; but after the change (and with T <: U still valid), \`${T}\` <: \`${U}` no longer holds.

I'm not sure from reading this if it was an expected change or not.  Working around it is easy enough. I have a small repro on the ts playground on the chance that it might be a useful example case.
 
[playground](https://www.typescriptlang.org/play?ts=5.3.2#code/PTAEEMBsEtwZ1AFwJ4AcCmoDu1EAtQ4B7AW0wCIt1wBrc0aAOwDMiIAjIgV0Wz3F64GcADRI8mAE7o4XSIIRNE6RgBN0qpGyhZwyBO0zw40AOaNw7SJkTa1oZpNKgAQvHQAoFBlABJFkQAgjDwADxucOhiACqg6AAeymoIcIiSTKYAfKAAvK7uoABkoADeoAD65dBw-qyVAPwAXKAAbkTQmgC+RaWgANo0DIyg0QC6Ta3tXR5eaJgA4lwduX4BwbBwoanpjKZi5KZLquTZIKDk4KCLy9UQhGkZ5LM+ANLoyACMK7VBIZvXqn2NHeHxOAG5QGcLqBgZ9hHcAfDLttHjNvJgAMKkVBEEzKN7IFYAAwAJCUCR9OkTIWAmKBpFBcISsNxIJpDKAYMDShTOsBye8AEx8gB0YtAREkcUQAGMRTMZURGKlQFiSDi8egCeUiDQXOhWNIAKzlADM5UFKwAFDRmgCAJSgZpqjW4LXvXLZUklGhUmlXI7wxhEXjGMwWKw2NgUjyK5W8F24t0E6220AUx3O7FJ-EenJesm+okzay8FG7ACEzXLpjBHlLoEOHSrAY6dYbsI+LYpdY8ic12t1+sN6BN5sFVpr9r72YH7x1eoNktHZotVqbqmn-eT86HS+Nq4nna3s53yEnD12J-VOfd54319dufPx48QA)

**Comment by unional** [comment]
This behavior is causing a few types in `type-plus` to fail (e.g. `IsTemplateLiteral`, `IsStringLiteral`, `Omit`) to fail https://github.com/unional/type-plus/issues/429.

In term of soundness, IMO it does make sense that `${string & { a: 1 }}` to be reduced to `${string}`.

in JS, it would be:

```js
const extendedStr = Object.assign('abc', { a: 1 })
console.log(`${extendedStr}`) // 'abc'
```

the reasoning being the `toString(): string` remains unchanged thus the resulting type should be safe to reduce.

**Comment by conorbrandon** [comment]
@unional That is a valid point, indeed.

**Comment by conorbrandon** [comment]
It didn’t come up in the original discussion, but I might as well add it now. The specific use case for this relates to DynamoDB keys. A common pattern for such keys is, for example, `USER#${UserID}`. In these template literals, it has proven valuable to have a stricter type that includes the brand to avoid mistakes, especially during refactors. 

i.e., this:
```ts
type UserID = string & { [BRAND]: "UserID" };
type Key = `USER#${UserID}`;
```
vs. this:
```ts
type KeyWide = `USER#${string}`;
```

Of course, there are workarounds, such as a helper function to enforce a `KeyWide` _actually_ includes a `UserID`,
```ts
const formatUserKey = (userID: UserID): KeyWide => `USER#${userID}`;
```
but it's convenient to be able to write them literally as well, and have stronger assurances:
```ts
const foo = "foo";
const key: Key = `USER#${foo}`; // oops!
```

So I would like to see this stick around (as I mentioned, it has proven valuable), however, I do understand that "it's convenient" is not the strongest of arguments, especially if this is causing issues elsewhere.

**Comment by unional** [comment]
Connecting related issues:

https://github.com/microsoft/TypeScript/issues/49839
https://github.com/microsoft/TypeScript/issues/54648
https://github.com/microsoft/TypeScript/issues/57776 
https://github.com/microsoft/TypeScript/issues/57807
