### ISSUE TITLE
why is array.length one higher, and why is it a 0 index array

### ISSUE THREAD

**Issue by passhley** [microsoft/TypeScript#54645]
# Bug Report

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

**Comment by passhley** [comment]
THIS WAS AN ACCIDENT

**Comment by fatcerberus** [comment]
Okay but just for the record: `array.length` is one higher than the last index in the array precisely *because* it's 0-based :)

**Comment by RyanCavanaugh** [comment]
I'm just happy to get a bug report I actually have a solid answer to
