### ISSUE TITLE
Code comlpetion not working for variables

### ISSUE THREAD

**Issue by Ilyat1337** [microsoft/TypeScript#54654]
# Bug Report

### 🔎 Search Terms

Completion, IntelliSense

### 🕗 Version & Regression Information

Tested in 'Nightly' version - the problem is not fixed.

- This changed between versions 5.0.4 and 5.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/DYUwLgBAZg9jBcEB2BXAtgIxAJwgXggEYAoWIA)

### 💻 Code

```ts
let foo: number = 1
fo
```

### 🙁 Actual behavior

Completion list ater `fo` does not contain `foo` item.

### 🙂 Expected behavior

Completion list ater `fo` contains `foo` item.

**Comment by Andarist** [comment]
This has been changed in `typescript@5.1.0-dev.20230415` so the likely culprit is https://github.com/microsoft/TypeScript/pull/52690 , cc @zardoy

**Comment by fatcerberus** [comment]
Huh, odd - you'd expect that ASI would kick in and have the parser act as if there's a semicolon after the `1`

**Comment by svipas** [comment]
@DanielRosenwasser @zardoy @RyanCavanaugh issue still exists:

```ts
const obj = {
  name: '',
} as const
```

<img width="460" alt="image" src="https://github.com/microsoft/TypeScript/assets/10441177/fd0a46f4-7c05-404f-9f25-439aa3d5b7e9">

If I add `;` semicolon it starts to work:

```ts
const obj = {
  name: '',
} as const; // <- added semicolon
```

<img width="809" alt="image" src="https://github.com/microsoft/TypeScript/assets/10441177/9aac1434-bfbe-4ddb-91d7-7a48f22984e7">

TS Version: `5.2.0-dev.20230717` and same with `5.1.6`
Playground: https://www.typescriptlang.org/play?ts=5.1.6#code/MYewdgzgLgBCBGArGBeGBvAUDGYCGAtgKYBcMA5OQDSYC+MeEMoksA9GzAIIAmPMAbgZh+AS1gB3EACcA1hEyYgA

**Comment by svipas** [comment]
@RyanCavanaugh @DanielRosenwasser  Let me know if I should open a new issue or we re-open this one
