### ISSUE TITLE
Types resolving to `any` across packages in monorepo using project references

### ISSUE THREAD

**Issue by ernestostifano** [microsoft/TypeScript#54653]
# Bug Report

## 🔎 Search Terms

- TypeScript issue monorepo references
- TypeScript issue monorepo types resolving to any
- TypeScript issue types depth limit
- TypeScript issue resolution limit
- TypeScript issue references type any

## 🕗 Version & Regression Information

- I have tested versions from `4.9.5` to `5.1.3`, all presenting the same behaviour regarding this issue.

## ⏯ Playground Link

- N/A.

### NOTE

Unfortunately I have not been able to replicate this issue in a reproduction repository because I think it is related to type resolution limits of `tsserver` (so it depends on the size and complexity of the codebase) and I am not allowed to give access to the original repository. However, I will try to be as precise and linear as possible, providing all relevant information. 

**If there are any additional debugging steps that I can perform or any other information I can gather, I would be happy to do so.**

### ISSUE SUMMARY

We have a monorepo (~17 packages and ~1287 files) using Yarn Workspaces and Yarn PnP with TS Project references configured as per documentation.

Everything seems to work just fine, but for some reason, some types get resolved to `any` when consumed in other packages.

- This is only happening when packages are not built (no `types` directory generated).
- This is only happening in some packages, even if all packages are configured in the same way.
- This is only happening for a particular type (see details below).
- All packages imports get resolved correctly.
- I suspect that the issue is only present in `tsserver`, since the project builds without errors using `tsc --build`.
- `@typescript-eslint/eslint-plugin` is able to resolve the type correctly (I assume it uses `tsc` and not `tsserver` internally) (see test `2` below).
- Error is shown both in WebStorm and in VSCode.
- All references have been properly set (done automatically with a script and then manually checked multiple times).
- There are no circular dependencies or other strange stuff.
- Packages have been renamed for confidentiality reasons and non related/relevant data have been removed when possible.

### PROJECT CONFIGURATION

<details>
<summary> Root's File Structure </summary>

```
.
├── package.json
├── packages
│   ├── package-a
│   ├── package-b
│   ├── package-c
│   ├── package-d
│   ├── package-e
│   ├── package-f
│   ├── package-g
│   ├── package-h
│   ├── package-i
│   ├── package-j
│   ├── package-k
│   ├── package-l
│   ├── package-m
│   ├── package-n
│   ├── package-o
│   ├── package-p
│   ├── package-q
├── tsconfig.base.json
└── tsconfig.json
```

</details>

<details>
<summary> Root's tsconfig.base.json </summary>

```json
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "@scope/*": ["./packages/*"]
        },
        "target": "ESNext",
        "isolatedModules": true,
        "resolveJsonModule": true,
        "esModuleInterop": false,
        "allowJs": false,
        "checkJs": false,
        "strict": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "allowUnreachableCode": false,
        "allowSyntheticDefaultImports": true,
        "forceConsistentCasingInFileNames": true,
        "useDefineForClassFields": true,
        "removeComments": false,
        "noEmitOnError": true,
        "declaration": true,
        "declarationMap": true,
        "emitDeclarationOnly": true
    }
}
```

</details>

<details>
<summary> Root's tsconfig.json </summary>

```json
{
    "files": [],
    "references": [
        {
            "path": "packages/package-a"
        },
        {
            "path": "packages/package-b"
        },
        {
            "path": "packages/package-c"
        },
        {
            "path": "packages/package-d"
        },
        {
            "path": "packages/package-e"
        },
        {
            "path": "packages/package-f"
        },
        {
            "path": "packages/package-g"
        },
        {
            "path": "packages/package-h"
        },
        {
            "path": "packages/package-i"
        },
        {
            "path": "packages/package-j"
        },
        {
            "path": "packages/package-k"
        },
        {
            "path": "packages/package-l"
        },
        {
            "path": "packages/package-m"
        },
        {
            "path": "packages/package-n"
        },
        {
            "path": "packages/package-o"
        },
        {
            "path": "packages/package-p"
        },
        {
            "path": "packages/package-q"
        }
    ]
}
```

</details>

<details>
<summary> Package's File Structure </summary>

```
.
├── package.json
├── src
└── tsconfig.json
```

</details>

<details>
<summary> Package's tsconfig.json </summary>

```json
{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": {
        "rootDir": "./src",
        "outDir": "./types",
        "composite": true,
        "incremental": true,
        "lib": ["ESNext", "DOM"],
        "module": "ESNext",
        "moduleResolution": "NodeNext",
        "jsx": "preserve"
    },
    "include": ["./src/**/*"],
    "references": [
        {
            "path": "../package-a"
        },
        {
            "path": "../package-g"
        },
        {
            "path": "../package-h"
        },
        {
            "path": "../package-c"
        },
        {
            "path": "../package-d"
        }
    ]
}
```

</details>

<details>
<summary> Package's package.json </summary>

```json
{
    "name": "@scope/package-f",
    "types": "./types/index.d.ts",
    "module": "./esm/index.js",
    "main": "./esm/index.js",
    "exports": {
        ".": {
            "types": "./types/index.d.ts",
            "import": "./esm/index.js",
            "default": "./esm/index.js"
        }
    },
    "dependencies": {
        "@scope/package-a": "workspace:*",
        "@scope/package-g": "workspace:*",
        "@scope/package-h": "workspace:*"
    },
    "devDependencies": {
        "@scope/package-c": "workspace:*",
        "@scope/package-d": "workspace:*"
    }
}
```

</details>

### ISSUE DETAILS

The problematic type is declared in a certain package (`package-g`) and is applied to a wrapper of `createUseStyles` from `react-jss`.

<details>
<summary> createUseStyles Declaration </summary>

```ts
import {getFileCallerDetails} from '@scope/package-b';
import type {Classes, Styles} from 'jss';
import {createUseStyles as _createUseStyles} from 'react-jss';
import type {ITheme} from '../../defines/theme.types';

type TStyles<TC extends string, TProps, TTheme> =
    | Styles<TC, TProps, TTheme>
    | ((theme: TTheme) => Styles<TC, TProps>);

type TUseStyles<TC extends string, TProps, TTheme> = (
    data?: TProps & {theme?: TTheme}
) => Classes<TC>;

function createUseStyles<
    TProps = unknown,
    TC extends string = string,
    TTheme = ITheme
>(styles: TStyles<TC, TProps, TTheme>): TUseStyles<TC, TProps, TTheme> {
    if (process.env.NODE_ENV === 'development') {
        const {componentName, packageName} = getFileCallerDetails();

        return _createUseStyles(styles, {
            name: `${packageName}-${componentName}`
        });
    }

    return _createUseStyles(styles);
}

export {createUseStyles};
```

</details>

Now, the type works perfectly fine when importing and using the function in most of the other packages:

<img width="1416" alt="Screenshot 2023-06-15 at 14 15 35" src="https://github.com/microsoft/TypeScript/assets/34403992/9c2c1b47-9918-4240-999c-d04466f31a15">

But in some packages, this happens:

<img width="1416" alt="Screenshot 2023-06-15 at 14 14 38" src="https://github.com/microsoft/TypeScript/assets/34403992/50ac6d96-4919-4298-9164-15fb446d8392">

- `@scope/package-g` is properly declared as a dependency for all packages in the same way.
- `@scope/package-g` is imported and used in the same way in all packages.
- There are no other significative differences between working and non-working packages.
- **I suspect that this is related to the overall complexity of the type (thus some kind of limitation), because the following modification in the declaration also makes the issue go away:**

```ts
type TStyles<TC extends string, TProps, TTheme> =
    // | Styles<TC, TProps, TTheme>
    | ((theme: TTheme) => Styles<TC, TProps>);
```

### INTERESTING TESTS

`1`
---

If I move the file containing the above error from its original position, to the root of the `src` directory of the package, the error disappears:

<img width="488" alt="Screenshot 2023-06-15 at 14 30 50" src="https://github.com/microsoft/TypeScript/assets/34403992/2be86e05-cd41-4693-befd-922211ec1cdd">

<img width="485" alt="Screenshot 2023-06-15 at 14 32 18" src="https://github.com/microsoft/TypeScript/assets/34403992/a902211c-b4b1-47e2-914c-1cac456125f3">

<img width="1269" alt="Screenshot 2023-06-15 at 14 32 36" src="https://github.com/microsoft/TypeScript/assets/34403992/ff88d31a-fa56-4605-bdb8-ac6bd7c0c496">

It only seems to work when placed just inside `src`, also for the other non-working packages.

`2`
---

I changed the type for `breakpoint.s` from `number` to `null | boolean` to make ESLint complain (`@typescript-eslint/restrict-template-expressions`), proving that it is correctly resolving the type. TypeScript still resolved it to `any`.

<img width="1271" alt="Screenshot 2023-06-15 at 14 50 48" src="https://github.com/microsoft/TypeScript/assets/34403992/d762dee2-28ca-446b-835b-2701e1d72026">

<img width="1268" alt="Screenshot 2023-06-15 at 14 49 17" src="https://github.com/microsoft/TypeScript/assets/34403992/4617a20a-fc9e-448f-9fdb-bbc57fbd2f43">

<img width="1273" alt="Screenshot 2023-06-15 at 14 50 33" src="https://github.com/microsoft/TypeScript/assets/34403992/8d3b7c53-d6e2-4049-9515-59f935aa44e4">

### POTENTIAL WORKAROUND

I have been trying to figure this out by myself for around 10 days, so believe me I have researched and tried a lot.

This is the farthest I got:

If I change the `paths` configuration in the root's `tsconfig.base.json` file from this:

```json
{
    "paths": {
        "@scope/*": ["./packages/*"]
    }
}
```

To this:

```json
{
    "paths": {
        "@scope/*": ["./packages/*", "./packages/*/src"]
    }
}
```

The issue goes away and everything seems to work perfectly. IntelliSense and overall performance also seemed to be improved.

<img width="1342" alt="Screenshot 2023-06-15 at 15 31 07" src="https://github.com/microsoft/TypeScript/assets/34403992/dadfd860-f248-4332-a166-ccd1aac831b8">

But, does this configuration make sense? What other issues could it provoke? The only issue I could think of is if packages are build in the wrong order (should not happen using `tsc --build`).

If a package gets built before one of its dependencies, a direct relative import will be generated in declaration files, which is obviously wrong. When done in the correct order, the first pattern of `paths` has priority (types directory can be found), and build is correct.

Wouldn't this workaround be ideal? I mean, does not it make the entire monorepo to be seen as a single source? So the IDE does not need need to build packages in the background?

In any case, right now, this workaround is triggering some errors:
- `TS6059: File '...' is not under 'rootDir' '...' .'rootDir' is expected to contain all source files.`
- `TS6307: File '...' is not listed within the file list of project '...'. Projects must list all files or use an 'include' pattern. File is CommonJS module because '...' does not have field "type"`.

But I think those can be easily solved by changing `rootDir` config and having a separate TS config for building (with the correct `rootDir`).

### POTENTIALLY RELATED ISSUES

- https://github.com/microsoft/TypeScript/issues/30946
- https://github.com/microsoft/TypeScript/issues/48728
- https://github.com/microsoft/TypeScript/issues/26913
- https://github.com/microsoft/TypeScript/issues/29511
- https://github.com/microsoft/TypeScript/issues/32707
- https://github.com/microsoft/TypeScript/issues/32573

**Comment by andrewbranch** [comment]
Thanks @ernestostifano for the very detailed description. A few thoughts/questions:

1. Would you be able to give me read access to the repo where this is happening? Ultimately, that, or an equivalent repro, might be the only way I can determine if there’s actually a TS bug and figure out a real fix.
2. Is there a reason you don’t want to or can’t use yarn workspaces (symlinks to local packages in node_modules, or whatever equivalent Yarn PnP sets up) instead of `compilerOptions.paths`? Especially considering you’re using `--moduleResolution nodenext` and package.json `exports`, it’s highly recommended to set things up so that module resolution of your local packages works the way it will actually work in the runtime/bundler; i.e. through `node_modules`.
3. FYI, #54567 made `--module esnext --moduleResolution nodenext`, as your packages have, an error. You probably want to switch to either just `--module nodenext` or `--module esnext --moduleResolution bundler`, depending on where your packages are getting loaded. (I doubt this will affect the bug you were observing, just an off-topic observation.)
4. What does go-to-definition on `createUseStyles` do when you’re getting the error? Does it change when types are built?
5. Are you sure [`disableSourceOfProjectReferenceRedirect`](https://www.typescriptlang.org/tsconfig/#disableSourceOfProjectReferenceRedirect) isn’t enabled anywhere?

**Comment by zb-sj** [comment]
From lots of trial and errors with extensive searches, this config helped my problem. 

```tsconfig.json
  "typeAcquisition": {
    "enable": true
  }
```

**Comment by andrewbranch** [comment]
In the interest of housekeeping, I’m going to close this since I can’t reproduce the issue and haven’t received any follow-up info I could use to try to narrow down the problem. I really appreciate the significant effort given here to provide a lot of detail in lieu of a repro, but unfortunately this kind of issue is nearly impossible to diagnose even with TS Server logs, and definitely impossible without. If anyone is able to provide a repro, please file a new issue. Thanks!

**Comment by janwirth** [comment]
I'm having the exact same problem. I can provide a repo.
