### ISSUE TITLE
TypeScript Target PreComputeCompileTypeScript fails in custom msbuild script

### ISSUE THREAD

**Issue by mduu** [Microsoft/TypeScript#5466]
Hi,

Searching for days now how to fix this issue so help would be really appreciated.

*Set-up:*
- VS Enterprise 2015 (V 14.0.23107.0 D14REL)
- .Net Framework 4.6.00081
- TypeScript Tools 1.6 (latest)
- ASP.Net MVC 5

The solution builds / rebuilds successfully and all fine from:

- inside Visual Studio
- Command line MSBUILD mySoltions.sln

but it doesn't from:

- Command line with custom MSBUILD script

It happens on my dev machine as well as on our TFS Build-Server.

I get the following msbuild error:

> PreComputeCompileTypeScript:
> C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(122,5): error MSB4062: The "TypeScript.Tasks.VsTsc" task could not be loaded from the assembly C:\Program Files %28x86%29\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll. Could not load file or assembly 'file:///C:\Program Files %28x86%29\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\dev\repos\MyRepo\MySolution\WebUI.csproj]

I've added some debugging message to the Microsoft.TypeScript.targets file and checked that the ToolsVersion, Paths etc look fine. The point to the V14 directories. If I remove the   `PreComputeTypeScript` target or empty it the custom MSBUILD script will build just fine.

The following path look fine to me:
- C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript
- C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.6

I also uninstalled TypeScript 1.5 and deleted remaining folders repaired and even re-installed TypeScript Tools 1.6 without success.

The really strange thing is that building the .sln file using MSBUILD (command line) with the same target, configuration and platform (Rebuild, Release, AnyCPU). but when i to a MSBUILD with our custom script it doesn't work. Our custom script does the failing build with:

    <MSBuild ContinueOnError="false" Projects="@(Solution)" Targets="Rebuild"
             Properties="Configuration=$(Configuration);Platform=$(Platform)" />

So really nothing special.  My colleagues and I don't have any more idea how to find out why TypeScript.Tasks.VsTsc fails. Does anybody have an idea how to diagnose this problem any further? Is the encoded path notation above correct?

Thanks for helping us! Cheers,
Marc

**Comment by wgebczyk** [comment]
It might indicate that [TypeScript.tasks.dll] cannot be loaded for some reason. Try use [https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx] Assembly Binding Log Viewer to see reasons of not loading this or that. Try use SysInternals FileMonitor to diagnose failures with file opening by MSBuild.

**Comment by mduu** [comment]
Thanks for the tool hints. Fuslogvw did not show anything but Sysinternals Procmon did show that msbuild really try to load the file `C:\Program Files %28x86%29\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll` (with those encoding leftover or whatever it is). See attached screenshot.

In the Typescript.targets file I see that the path is build using VSToolsPath variable. In our build script we set it with the following code:

    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>

We don't set MSBuildExtensionsPath32 at all. Does anybody have an idea where this path comes from and why there are some encoding codes are in there?
![msbuild_typescript_tasks](https://cloud.githubusercontent.com/assets/8256317/10932885/bf4d3f2a-82d4-11e5-8399-9d37b26e3787.png)

**Comment by wgebczyk** [comment]
Run MSBuild with verbosity diagnostic (diag) [https://msdn.microsoft.com/en-us/library/ms164311.aspx], and see where its beeing twice encoded. You can use "flp" flag to increase verbosity only for specified log file.

**Comment by mduu** [comment]
I got the diagnostic log of my msbuild and found several places where the encoded paths occur but I don't really know what that means. Here is one of them:

    Target "ResolveCodeAnalysisRuleSet: (TargetId:62)" in file "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets" from project "C:\dev\repos\MySolution\Source\MyProject.Common\MyProject.Common.csproj" (target "CoreCompile" depends on it):
    Using "ResolveCodeAnalysisRuleSet" task from assembly "Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
      Task "ResolveCodeAnalysisRuleSet" (TaskId:47)
      Task Parameter:CodeAnalysisRuleSet=MinimumRecommendedRules.ruleset (TaskId:47)
      Task Parameter:CodeAnalysisRuleSetDirectories=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\\Rule Sets (TaskId:47)
      Task Parameter:MSBuildProjectDirectory=C:\dev\repos\MySolution\Source\MyProject.Common (TaskId:47)
      Output Property: ResolvedCodeAnalysisRuleSet=C:\Program Files %28x86%29\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset (TaskId:47)
    Done executing task "ResolveCodeAnalysisRuleSet". (TaskId:47)

Do you know that that context means? Looks like something task from Microsoft.Build.Core related to code analysis but where does that one take the paths from and why doesn't this happen I build the .sln file using msbuild.exe? Looks like we are getting deeper in the rabbit hole ;-)

**Comment by wgebczyk** [comment]
At top of the log file there should be list of all env variables, properties etc. Maybe upload log file somewhere and post link?

**Comment by mhegazy** [comment]
please reopen if this is still an issue.
