### ISSUE TITLE
Returned type of class decorator is ignored when class is decorated

### ISSUE THREAD

**Issue by b-strauss** [microsoft/TypeScript#54663]
# Bug Report

Using decorators and proxies it's now possible to elegantly create classes which don't require the `new` keyword for instantiation. Unfortunately TypeScript doesn't allow this.

### 🔎 Search Terms

decorators, class decorators

### 🕗 Version & Regression Information

- Tested in 'Nightly' version

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230615#code/C4TwDgpgBAwghgGwXARgiAeAKlCAPYCAOwBMBnKIiAdygAoA6JuAJwHMyAuKOIkASigBeAHw8+YoVBwAyeo2bsusAPZEywFgFcAxsBUsACqzgBbCIRZlsIwaKgBJdcF46IWcJiy2A3ACg-ADMtIj0ASzUoUzgAawh4JFR0DBhcAmJyShp6JgZWDm5eAWExIrE6HWQALyruGH46xGQ0TBgxAG8-KCgWCy0WIizaQxYVPBAK6qqAGihO7u64MDAEEHoXdgtZ4AALMLIAQXZZ-KOWOGL5he7e4H7BqloNtgsFPPYzi-5-a4Bfaa6UF+gjgFBCMSIKmog1BsCaSVaIn8vwCwVCwAigx08JaKTShFIFEeOUUBXExXsZXolTgNTqsx0akIBDqyDIZAAIhBGed9CwYEz8MAUrZGolcW05oDbvcorF4jj0JNaVVvn4UX4APSaqAAVTIYSIbCgaPCaj8jOcerIEBYwjlcQSzSVNPZUu6lo02j0BnoRDMEG4XsNbBOLwA-NwiFpTChbYJ2ijgf4LWoNFA8PbifrbXQAOSBFQqPNqz0qdAMBAqNh0TOGjSuCAqQLW+Mpz3AKBrKQ5lj5lCsEs+KDaqDUAwxMip9TliCV6t0Nb1lyhJst3tqrU6-UhqAkbkGOB8vwAAWx4vQFrZFC5PKPEBIvfdUA73r5foDQc0IbDEEjlBjOMWATJMAg7Hgs2yW9D0IR8bT7AsizzWYAEYAE5SzTWd5xrOAoGXRtmygaDeQfDd2zTTsUHtEj7zg3M8wHFhkKgFCACZvhHHUADVEC0aAiNASAoDzIS12Ig9SPo5j8KJFRO3PZ052IsISC7FQtCiCBeCgfR8NCBAtH3ETHjzcM6DYgBmAAWAAOfhpzIbCqxraiCNXIjaNg8igA)

### 💻 Code

```ts
type Callable<T extends new (...args: any) => any> = T & ((...args: ConstructorParameters<T>) => InstanceType<T>);

function makeCallable<C extends new (...args: any) => any> (clazz: C): Callable<C> {
  return new Proxy(clazz, {
    apply (target, thisArg, argArray) {
      return new target(...argArray);
    },
  }) as unknown as Callable<C>;
}

function callable<C extends new (...args: any) => any> (clazz: C, context: ClassDecoratorContext<C>): Callable<C> {
  return makeCallable(clazz);
}

// Using function
const User = makeCallable(class {
  constructor (name: string, age?: number) {}
});

const x = new User('foo');
console.log(x instanceof User);

const y = User('bar'); // works
console.log(y instanceof User);

// Using decorator
@callable
class DecoratedUser {
  constructor (name: string, age?: number) {}
}

const a = new DecoratedUser('foo', 19);
console.log(a instanceof DecoratedUser);

const b = DecoratedUser('bar', 12); // Value of type 'typeof DecoratedUser' is not callable.
console.log(b instanceof DecoratedUser);
```

### 🙁 Actual behavior

TypeScript does not allow for the proxied class to be called, although this is valid js code and all instanceof checks are passing.

### 🙂 Expected behavior

TypeScript should use the return type of the decorator as the new type for the class.

**Comment by jcalz** [comment]
This is probably less "bug" and more "missing feature".  Cross-linking to #51347
