### ISSUE TITLE
Completions within a word do not replace the original contents

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#54670]
# Bug Report

Completion does not work in the middle

### 🔎 Search Terms

Completion in the middle

### 🕗 Version & Regression Information

- I think this never worked

### 💻 Code

```ts
HTMLElement
// trigger completion before E, like HTML|Element, | is the cursor 
```

Select HTMLAreaElement

### 🙁 Actual behavior

Code becomes `HTMLAreaElementElement`

### 🙂 Expected behavior

Code becomes `HTMLAreaElement`

**Comment by gabritto** [comment]
This seems to be working for me, at least in vscode. There's a setting in vscode called "Insert Mode", and if you have it set to "replace" (vs "insert"), then when you select a completion, it should replace the whole word.

![image](https://github.com/microsoft/TypeScript/assets/19519347/b1bccaa5-c8d0-434d-85cb-478dafb03db7)

**Comment by fatcerberus** [comment]
I think you have the actual and expected behavior swapped?

**Comment by gabritto** [comment]
Thanks, updated my comment with the opposite thing.

**Comment by fatcerberus** [comment]
@gabritto I meant the OP.  I have a hard time believing they *wanted* to end up with `HTMLAreaElementElement`.

**Comment by Jack-Works** [comment]
oh you're right, I don't want `HTMLAreaElementElement`

**Comment by Jack-Works** [comment]
interesting, it's ok with editor settings
