### ISSUE TITLE
es2022 doesn't generate the right js code

### ISSUE THREAD

**Issue by tonychunxizhu** [microsoft/TypeScript#54677]
ts file 
```
//demo.ts
class Foo {
    i ! : string;
    static s : string;
    c ! : string;
    constructor (c : string) {
        this.c = c;
    }
}
console.log (new Foo ("constructor property").c);
Foo.s = "added static property";
console.log (Foo.s);
Foo.prototype.i = "added instance property";
var i : Foo = new Foo ("constructor property");
```
when using target es2021 to generate js file  ```tsc -t es2021 demo.ts -strict```, the js code is
```
"use strict";
class Foo {
    constructor(c) {
        this.c = c;
    }
}
console.log(new Foo("constructor property").c);
Foo.s = "added static property";
console.log(Foo.s);
Foo.prototype.i = "added instance property";
var i = new Foo("constructor property");
console.log(i.i);
var o = new Foo("constructor property");
o.o = "added oject property";
console.log(o.o);
```
and it's the expected code 
```
$node demo.js
constructor property
added static property
added instance property
added oject property
```

but when using target es2022,   ```tsc -t es2022 demo.ts -strict```, the js code is different
```
"use strict";
class Foo {
    i;
    static s;
    c;
    constructor(c) {
        this.c = c;
    }
}
console.log(new Foo("constructor property").c);
Foo.s = "added static property";
console.log(Foo.s);
Foo.prototype.i = "added instance property";
var i = new Foo("constructor property");
console.log(i.i);
var o = new Foo("constructor property");
o.o = "added oject property";
console.log(o.o);
```
the js code looks incorrect and output wrong
```
$node demo.js
constructor property
added static property
undefined
added oject property
```

### 🕗 Version & Regression Information
$tsc -v
Version 5.1.3

$node -v
v18.12.1

### ⏯ Playground Link
it's interesting that this problem is not in TypeScript Playground, but only on tsc command line
https://www.typescriptlang.org/play?target=9&module=7#code/MYGwhgzhAEBiD29oG8BQBLAhALggFwCd0A7AcwG5V8w91hoZsHCSLpVgd8izz2P4xbgFdgeeAQAU9Jt1YBKFNDwALdBAB0wALzBKqAL7QDqAUPggAphpDxS0ScUsB3OIgcAiYIJFiJ0AAcCeADLAjwATw95LXk+VAR4DRhtaA8wABMMywzmGjpA4NDwqP1vcysbO0lE5LjTWqD4cUjQjXRoVPSsnOgSamJgS0KQsMiPeIA3MAI+6CZEzugnV0XJLx9CUXFZpuLxuPZyiAtrW3tJdHb61GnZpCYwYgillbckdeOtv12isajDqgkkguplsrl4AArSxiEb7UqmY6nKoXYGHIA

### 🙂 Expected behavior
the output js code of target es2022 should be the same as target es2021

**Comment by MartinJohns** [comment]
The behaviour and generated code is correct. When targeting es2022 a new default value for `useDefineForClassFields` is used (enabled, instead of disabled like earlier ES versions).

See: https://www.typescriptlang.org/tsconfig#useDefineForClassFields

**Comment by tonychunxizhu** [comment]
> The behaviour and generated code is correct. When targeting es2022 a new default value for `useDefineForClassFields` is used (enabled, instead of disabled like earlier ES versions).
> 
> See: https://www.typescriptlang.org/tsconfig#useDefineForClassFields
> 
> The issue doesn't appear in the playground because the playground is not using the default value, but whatever value is configured in the playground. When you change the setting it will reflect the same behaviour in the playground.

thank you so much @MartinJohns
