### ISSUE TITLE
Quick fix module imports suggestions does not work with newly installed packages.

### ISSUE THREAD

**Issue by Anthony-Breneliere** [microsoft/TypeScript#54671]
# Bug Report

Quick fix module imports suggestion does not work with newly installed packages.

The TS Server does not seem to scan the node_modules package that have been newly installed, even after restarting TS Server, or after restarting Visual Studio Code.

### 🔎 Search Terms

typescript restart ts server module imports not found

### 🕗 Version & Regression Information

"typescript": "~5.1.3"
"tslib": "^2.5.3",
Visual Studio Code 1.79.2
node 18.16.0

![image](https://github.com/microsoft/TypeScript/assets/6704165/4ca4a86f-f949-45bd-801b-fc04b483c6b9)

### 🙁 Actual behavior

Create a new Angular project, last version

- ng new Toto
- cd Toto
- code .
- from the terminal:
- npm install @angular/material --save
- open src/app/app.module.ts
- in imports, add MatButtonModule, and save.
- type F1, then > typescript restart TS Server

The issue is the import of MatButtonModule is not proposed as a quick fix.
![image](https://github.com/microsoft/TypeScript/assets/6704165/177bac0c-cabd-4600-ba96-1950e1f8c3c7)
But if I remove an angular native modules, for example `import { CommonModule } from '@angular/common';` then it works for that import:
![image](https://github.com/microsoft/TypeScript/assets/6704165/1aad3198-a903-4fed-ab6f-8b9fa833e652)

If I add the import manually, then the module is found in node_module, and there is no more issue
![image](https://github.com/microsoft/TypeScript/assets/6704165/30f6bf0c-0a1e-4633-bbe8-bdfab8ec16cc)

### 🙂 Expected behavior

import of MatButtonModule should be proposed as a Quick fix:

![image](https://github.com/microsoft/TypeScript/assets/6704165/de830ba8-0cfc-4a4a-9338-742df24063bc)

**Comment by RyanCavanaugh** [comment]
Auto-import can only offer suggestions from modules that are already "known", i.e. part of your program already. Installing the modules alone isn't always going to be sufficient to get them into that known set. You'll have to import them at least once the old-fashioned way, after which point auto-import should be surfacing all identifiers from the imported module.
