### ISSUE TITLE
Abnormal file system usage on macOS while running TypeScript

### ISSUE THREAD

**Issue by guillermo-avalos** [microsoft/TypeScript#54683]
# Bug Report

### 🔎 Search Terms

`fs_usage`, `file system usage`

### 🕗 Version & Regression Information

5.1.3, but also happening with earlier versions.

### 🙁 Actual behavior
Endless loop of `fs_usage` activity.
To Reproduce:

1. Create a new, blank Next.js project with `npx create-next-app@latest` (although any TS project will do)
2. Run `sudo fs_usage -w | grep 'Users/[username]/[project-location]/' --line-buffered` to capture macOs' filesystem activity.
3. Open the project in Visual Studio Code. Immediately after opening a few config files (although it's completely random), the filesystem usage will start an endless loop as you see in my screen capture. 

Screen capture of the issue: https://share.cleanshot.com/SYpRks7p

### 🙂 Expected behavior

This issue seems to be related to TypeScript. If I use a different code editor, such as Nova from Panic, that allows me to fully disable TS, the problem goes away. File system activity returns to normal. Immediately upon enabling TypeScript support, the loop starts yet again.

**Comment by jakebailey** [comment]
Given your description, likely this is #52535 and #52876.

Can you set:

```json
"typescript.tsserver.watchOptions": {
    "watchFile": "fixedPollingInterval"
},
```

And see if this helps?

**Comment by guillermo-avalos** [comment]
Thanks @jakebailey. Adding that to VS Code `config.json` did make a change, the polling is still several times a second but now I'm seeing actual files from my projects. It's mostly `node_modules` and several other directories and files.
It this how TS is supposed to work? The polling seems excessive.  Any other suggestions?

**Comment by jakebailey** [comment]
There are other file watching methods that can be passed to that option; I just randomly chose one. You can also try `dynamicPriorityPolling`. The default was changed in #50366.

File watching is fickle and we're working on this. Marking as a duplicate.

**Comment by guillermo-avalos** [comment]
Awesome. I'm glad this isn't only happening to me. I understand that file watching is necessary, just surprised that TS needs to watch every file randomly several times a second.
