### ISSUE TITLE
Question: Why must ambient interface declaration members be redeclared on every class?

### ISSUE THREAD

**Issue by yGuy** [Microsoft/TypeScript#5468]
Hi, I realize that this has been [asked on Stackoverflow](http://stackoverflow.com/q/14583231/351836) before and [Ryan gave a short answer](http://stackoverflow.com/a/14587529/351836), but I would really like to see this discussed more, since I believe this could be a huge time and ressource saver if it was implemented differently:

I am trying to write a compact typescript definition file, but I am having troubles doing so for a larger project. 

My project has lots of interfaces that are implemented by a number of classes.

From what I can see I always need to re"implement"/redeclare the methods of the interfaces in the classes like so:

```typescript
    declare module someModule {
		
		interface InterfaceOne {
			/**
			* Some lengthy description
			*/
			someStuff():any;
			/**
			* Some lengthy description
			*/
			moreStuff():any;
		}
		
		class OneClass implements InterfaceOne {
			/**
			* Some lengthy description
			*/
			someStuff():any;
			/**
			* Some lengthy description
			*/
			moreStuff():any;
			/**
			* Even more description
			*/
			classStuff(): any;
		}
	
		class TwoClass implements InterfaceOne {
			/**
			* Some lengthy description
			*/
			someStuff():any;
			/**
			* Some lengthy description
			*/
			moreStuff():any;
			/**
			* Even more description
			*/
			classStuff(): any;
		}
	}	
```

If I leave out the `someStuff` and `moreStuff` declarations from the interfaces in the class declarations
I get this error:

>  error TS2137: Class TwoClass declares interface InterfaceOne but does not implement it:

So I always need to copy all of the declarations to each and every class that implements the interface.

In his answer to the similar question Ryan wrote this:

> Let's say you didn't have to write out the interface members:
>
> ```typescript
>   class Base { }
>    class Derived extends Base { }
>
>    interface Foo {
>    	method(t: number): Base;	
>    }
>
>    declare class FooImpl1 implements Foo {
>        // Empty
>    }
>
>    declare class FooImpl2 implements Foo {
>    	public method(): Derived;
>    }
>```
>
>Is `FooImpl2` trying to declare an additional overload of `method`, or is `FooImpl2` implementing
>`method` using a signature that takes fewer parameters and returns a more derived type? Either 
>would be a valid interpretation. You'd have to make rules for all sorts of cases like this so the 
>programmer could specify what they actually meant, making the language less predictable.

I don't understand his arguments:

First: for the vast majority of cases the `//Empty` case is the case that is totally *un*ambiguous: I have a class that implements Foo and thus I can call all methods from Foo, why do I need to redeclare all of them?

Second: It's the same thing with classes, too, and there the existing rules seem to suffice: If I extend a class (in a definition .d.ts file) I don't have to reenumerate all the base type members either:

```typescript
class Base {
	baseMethod():any;
}

class Derived extends Base { 
	derivedMethod():any;
}

class Foo {
    public method(t: number): Base;    
}

class FooImpl1 extends Foo {
    // Empty - works! why not for interfaces?
}

class FooImpl2 extends Foo {
    public method(): Derived;
    public method(t: number): Base;    // need to redeclare in case of overload if I want to use that method!
}
```

So why should this not work for interfaces, too?

By the way I really don't understand why you cannot do the following if you _leave out_ the redeclaration in the last line of `FooImpl2` above:

```typescript
new FooImpl2().method(2);  // TS2081: Supplied parameters do not match any signature of call target. TS2087: Could not select overload for 'call' expression.
```

If `FooImpl2` extends `Foo`, it _must_ be possible to call `method(t:number)` from the base type *and* the method declared. After all it's all about library definition files (.d.ts) that declare how the library will behave, so the overload resolution happens at runtime and if multiple members are declared, then all of them should work and be available, shouldn't they?

So back to the original question: Why can't `implements SomeInterface` behave like `extends SomeClass` in `.d.ts` declaration files? This would save us so much duplicated declarations and documentation, decrease the `d.ts` file size and speed up compilation and parsing, wouldn't it?

Edit 2015-10-31: I had accidentally written that my desired way of writing the declaration would be "ambiguous" in the most common case - of course I meant "*un*ambiguous", otherwise this would all make no sense.

**Comment by yGuy** [comment]
A solution to this problem might also help defining mixins where [people are facing similar problems](https://typescript.codeplex.com/wikipage?title=Mixins%20in%20TypeScript&referringTitle=Declaration%20Merging#C29954). Or it could be the other way around, if mixins where better supported on the declaration side, my problem could go away, too.

**Comment by SaschaNaz** [comment]
Any ambient class declarations that implements lib.d.ts interfaces breaks when the interfaces are updated with more members. Fixing this may prevent potential breaking changes from lib.d.ts.

**Comment by andershessellund** [comment]
As a workaround, you can use declaration merging. The mixins example from the TypeScript handbook can be done like this:

**Comment by andershessellund** [comment]
As a workaround, you can use declaration merging of interfaces. The mixins example from the handbook can be accomplished like this:
```typescript
// Disposable Mixin
class Disposable {
    isDisposed: boolean;
    dispose() {
        this.isDisposed = true;
    }

}

// Activatable Mixin
class Activatable {
    isActive: boolean;
    activate() {
        this.isActive = true;
    }
    deactivate() {
        this.isActive = false;
    }
}

interface SmartObject extends Disposable, Activatable {}

class SmartObject {
    constructor() {
        setInterval(() => console.log(this.isActive + " : " + this.isDisposed), 500);
    }

    interact() {
        this.activate();
    }
}

applyMixins(SmartObject, [Disposable, Activatable]);

let smartObj = new SmartObject();
setTimeout(() => smartObj.interact(), 1000);

////////////////////////////////////////
// In your runtime library somewhere
////////////////////////////////////////

function applyMixins(derivedCtor: any, baseCtors: any[]) {
    baseCtors.forEach(baseCtor => {
        Object.getOwnPropertyNames(baseCtor.prototype).forEach(name => {
            derivedCtor.prototype[name] = baseCtor.prototype[name];
        });
    });
}`

**Comment by andershessellund** [comment]
Or, for your example:

```typescript
declare module someModule {

        interface InterfaceOne {
            /**
            * Some lengthy description
            */
            someStuff():any;
            /**
            * Some lengthy description
            */
            moreStuff():any;
        }

		interface OneClass extends InterfaceOne {}
        class OneClass {
            /**
            * Even more description
            */
            classStuff(): any;
        }

		interface TwoClass extends InterfaceOne {}
        class TwoClass {
            /**
            * Even more description
            */
            classStuff(): any;
        }
    }
`

**Comment by SaschaNaz** [comment]
The `interface` workaround look good! So `class A implements B` thing is discouraged when B may be extended later?

```typescript
interface Foo {
  foo: string;
}
interface Bar {
  bar: string;
}

class A implements Foo, Bar {
  foo: string;
  bar: string;
}
class B implements Foo {
  foo: string;
  baz: number;
  m(): void;
}
```

```typescript
// the next version of d.ts
interface Foo {
  foo: string;
  // extended
  flash: string;
}

// Now every classes implementing Foo break so they should be updated manually
```

**Comment by yGuy** [comment]
Thanks for your suggestions. I believe the proposed solution fits my specific needs very well. I'm with Sascha, though: This is a workaround, only, and I would rather see a clean solution that also works for non-declaration files.

**Comment by andershessellund** [comment]
@SaschaNaz 
If a class implements an interface, and the interface is extended later, you probably want TypeScript to verify that the class still implements the entire interface.

In the case of mixins, this is not necessary. The additional fields or methods from the mixin class is automatically added.

In the case of ambient declarations, it is probably also not necessary.

However, for a concrete class which must implement a particular interface, you probably want TypeScript to verify that the class implements the interface, also when the interface is extended with new properties.

**Comment by yGuy** [comment]
@andershessellund - yes, I agree with your analysis. Since in my case interfaces can be both mixins and interface declarations (with "abstract" members), we are only adding functionality to the mixin parts between releases. So this really only is a problem for the mixin use-case.

**Comment by SaschaNaz** [comment]
I'm talking about ambient declarations (sorry I omitted `declare` before `class`).

**Comment by SaschaNaz** [comment]
It seems this limit has been lifted?
