### ISSUE TITLE
"TypeScript for Visual Studio" installer not available for 5.1

### ISSUE THREAD

**Issue by wnayes** [microsoft/TypeScript#54685]
# Bug Report

There [does not appear](https://marketplace.visualstudio.com/search?term=typescript&target=VS&category=All%20categories&vsVersion=&sortBy=PublishedDate) to be a "TypeScript 5.1 for Visual Studio" installer available on marketplace.visualstudio.com.

Previous releases of TypeScript have had installers made available, such as [this one](https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-504) for 5.0.4.

Was it intended to stop publishing this for 5.1 onward?

### 🔎 Search Terms

Visual Studio 2019/2022, Windows SDK

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/54686 seems like it might be related

**Comment by noshlag** [comment]
5.1.3 has now been published. Here is the link to it: https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-513

Apologies that it did not go up immediately. Future publishes should happen simultaneously with the NuGet releases.

**Comment by HolgerJeromin** [comment]
Does this even work with the buildin node 12 version in VS2019 (or even node 10 in VS2017)?

**Comment by cheit-epic** [comment]
@noshlag Simultaneous publishes don't seem to be working, since 5.2 is also missing from the marketplace.

**Comment by DanielRosenwasser** [comment]
> Does this even work with the buildin node 12 version in VS2019 (or even node 10 in VS2017)?

Unfortunately no - [there are ways of customizing VS2019 to use an alternative version of Node.js](https://developercommunity.visualstudio.com/t/TypeScript-51-not-working-properly-on-V/10383037), but TypeScript won't work with the built-in Node.js from VS2019.

> publishes don't seem to be working, since 5.2 is also missing from the marketplace.

Apologies, there was an oversight in the publishing process. That said, I would highly recommend switching over to using NuGet, or more preferably npm, to customize the version of TypeScript used in VS.

**Comment by HolgerJeromin** [comment]
@cheit-epic It was on nuget.org but not anymore (because it was buggy):
https://github.com/microsoft/TypeScript/issues/57475#issuecomment-2189424566
