### ISSUE TITLE
What happened to typescript.d.ts?

### ISSUE THREAD

**Issue by lancejpollard** [microsoft/TypeScript#54690]
It used to be here: [lib/typescript.d.ts](https://github.com/microsoft/TypeScript/blob/7c14aff09383f3814d7aae1406b5b2707b72b479/lib/typescript.d.ts), what happened to that file or the data in that file? How do I recover it? Thanks!

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/pull/52226.

**Comment by jakebailey** [comment]
This file was never meant to be used by anyone other than us; it was only related to the compiler used to compile the compiler itself and has been removed.

If you need this file, you should use npm or a tagged commit or release branch.
