### ISSUE TITLE
Class incorrectly implements interface generated with template string literal mapped type

### ISSUE THREAD

**Issue by zpix1** [microsoft/TypeScript#54694]
# Bug Report

Error message and refactoring ("implement interface") are confusing when implementing mapped type.
Implementing methods stated in error do not fix the error.

If interface is correctly implemented  no error is thrown.

### 🔎 Search Terms

* class incorrectly implements interface mapped type string literal template
* X is missing the following properties from type Y: foo, foo

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230618#code/C4TwDgpgBAMglgZ2BAdhATgFQgWzAGwENkAeTAGigGUoIAPZFAEwSiXThQHNKBJWhqhZtgHblAC8UAEQASAN4BGAL7SAfJKjyAUFCgBtANJROUANYQQAewBmUTFEKtj9RsPacuuvVAD81ATdWAAMFThsMKAAxZQVeWPlwyIAlZWDvHz8oUPkYhUME1PTMvQAuKEMMqHLDAF1ygAp8REYMRrBCEHwrQiZyzCNagEpJDQA3KzgmEYlxyaYAbm1lJe16MCt0YChQSFgW1ABBAGNgOCsUQgAjfAgSAFENKXgkVAxsPCJSb3vyb2lekwAFQvVroaRQAA+MnQuCsYwgIIOaHBfz00iB0m0alWu2gAGFmsczPcEShgFQAK5gDZbTSgo6nc6XG53HSZQlwYnlADkCCsOAgAFpjkSzEKIGTgEKOl0ekwecscdoVQB6VVQQlOVg8qgCiCc4nXW5ahAIHkmFDHTaw074EAmT64VDAVicZDoGyEY7QHkMlEfAjENmasXlaT8wUisUSqUyzrdXrSBZQZSUAFMYH+jAQ6HSWE4eGI7OomSYtQ8gB02nVPkw4F9esFhrMxoNRDNFsQUBwiAQnh2AAtoDYrPhugB3AdgdBWSBbOAQVg2Wc4HYNqB+5HvXBB0jyUNcszhyPC0VH2Mu+NypMptMyQFI14o3MwuEIp9g6Tp8s88otygW20UVtWofUWzbU03SdQVyVYFtSRdKkaU2bYdGUIA)

### 💻 Code

```ts
type ListenerTemplate<T, S extends string, I extends string = "${1}"> = {
  [K in keyof T as K extends string
    ? S extends `${infer F}${I}${infer R}`
      ? `${F}${K}${R}`
      : K
    : K]: (listener: (payload: T[K]) => void) => void;
};

export type ListenActionable<E> = ListenerTemplate<
  E,
  "add*Listener" | "remove*Listener",
  "*"
>;

type ClickEventSupport = ListenActionable<{
    Click: 'some-click-event-payload'
}>;


// Class 'SomeClickableClass' incorrectly implements interface 'ListenerTemplate<{ Click: "some-click-event-payload"; }, "add*Listener" | "remove*Listener", "*">'.
//   Type 'SomeClickableClass' is missing the following properties from type 'ListenerTemplate<{ Click: "some-click-event-payload"; }, "add*Listener" | "remove*Listener", "*">': Click, Click
class SomeClickableClass implements ClickEventSupport {
}
```

### 🙁 Actual behavior

Error message reports that properties `Click`, `Click` are not implemented. Refactoring "Implement  interface" creates 2 fields named `Click` duplicating each other.

### 🙂 Expected behavior

Error message reports that properties `addClickListener`, `removeClickListener` are not implemented. Refactoring "Implement  interface" creates 2 methods named `addClickListener` and `removeClickListener`.

**Comment by RyanCavanaugh** [comment]
For clarity, the expected generation is
```ts
class SomeClickableClass implements ClickEventSupport {
    addClickListener(listener: (payload: "some-click-event-payload") => void): void {}
    removeClickListener(listener: (payload: "some-click-event-payload") => void): void {}
}
```
