### ISSUE TITLE
compiler API - unnecessary underscore where property name start with two underscores or more

### ISSUE THREAD

**Issue by netanel-mce** [microsoft/TypeScript#54704]
# Bug Report

### 🔎 Search Terms
* underscore

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Compiler API

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?noImplicitAny=false&noEmitHelpers=true&noUnusedParameters=true&preserveConstEnums=true&target=7&module=1&inlineSourceMap=true&ssl=8&ssc=1&pln=9&pc=1&filetype=ts#code/JYWwDg9gTgLgBAKjgQwM5xugZlCI4BEMAnmAKaoDGUwYMBA3AFBOUQB2q8qEArlJTIAxYABsycALwZUAOmplkMMgGU+A4WLIAKJnH2ES5WZgIAaPQYAGRiQFliAFVITpAb0sGDAfWQAuOC4adgBzZi8vb28AIwCg4FDwiP0o70o4mGCwzwjU7wATDKyk-QBfBisLL0xZFWpaGEdkKBCyGFkAGSUKGAsASmZWDi4MFwA5CHzXOG0efkERcVkubpAydkwAbQAGAF0UdBrncgBBUWA0ABEySlFmpWAOPpMXA5lZY7IO4GUoZFEJlNmGxOPA1iBomQoOhpLZAWRZODIdC3jV4ScoH9iAAeGoABVw5FgxBUwBC7CU-DIAD5gcMwWQIVDUI4yAAPeDSJHMxHIMDabTcqB9KTUmZC2QUtaouQASSmG2AWGAUOeFEofLI+VZHIGLBBPCWoggIUFjORLPZMAGcAA9La4OzyJRlPk4JsCL5zIQotFvZ6opR-Xl8gRdmY7Q7orx4CEIDAAh6vRGAzFg6kgym8gUwywhqC4BwyCcpHAhZaObIErdeFNUNpPcgCDLZFEVJkEiEbfaMFBeBI0I62c7XfmRjAAO4QABCpfLOva1dEtYoDd9zcHNTbHdC3YdTpurowEDgcfgmX7EejsfjcCw-1QZDH54AFlAyGQAMJz83MhdV9gazrNdAw3Q45G3LI9yHEctWPU9bwvMgrxjBD4HvURH2fO91EuH8mWhf8lxXetUxzFtIM7aCDxdOCYBPM9e0vOBrzQu8HyfbD6InEsuV-QirQAoDVwDJsKO8dsoIYSN2Mwgd0Bo0cDVfd8yFnPiCIrRdAOXYDUz9cTJKo6Se0UuiGNvDDHxQm9zz7J9lJw-hvw0i0iJ0kiQNAwydy7Ez92HQ9zLYqzkJY1DGKQ7DlQANzIPDXL-QTiL07NQx8qSZLMt16JCjibLYqKxwgI0TW0DwvCLE4Ix7KLqinacaodUKchgN8P0-JrZKwrwsFwrqWtaiAeIGjjWvatSurqgw+ucqb7JyWL4qaqLSj1Jgex4O9cHwScT14dgpmhNh33QZBDrLaAwpfZA4pQOADvYG4KFQZpiAew7mROhEgA)

### 💻 Code
```ts
import * as ts from "typescript";

const sourceFile = ts.createSourceFile(
    "type.ts",
    `type MyType = {
        _a: string;
        __b: string;
        ___c: string;
        ____d: string;
    };`,
    ts.ScriptTarget.Latest,
);

const typeNode = (sourceFile.statements[0] as ts.TypeAliasDeclaration).type as ts.TypeLiteralNode;
const members = typeNode.members as ts.NodeArray<ts.PropertySignature>;
const membersText = members.map((member) => (member.name as ts.Identifier).escapedText);

console.log(membersText); // expected ["_a", "__b", "___c", "____d"], // but got: ["_a", "___b", "____c", "_____d"]


const oneA = membersText.includes("_a" as ts.__String); // true as expected
const twoB = membersText.includes("__b" as ts.__String); // expected to got true, but got false
const threeC = membersText.includes("___c" as ts.__String); // expected to got true, but got false
const fourD = membersText.includes("____d" as ts.__String); // expected to got true, but got false

const towA = membersText.includes("__a" as ts.__String); // false as expected
const threeB = membersText.includes("___b" as ts.__String); // expected to got false, but got true
const fourC = membersText.includes("____c" as ts.__String); // expected to got false, but got true
const fiveD = membersText.includes("_____d" as ts.__String); // expected to got false, but got true

console.log({
    oneA, // true
    twoB, // false
    threeC, // false
    fourD, // false

    towA, // false
    threeB, // true
    fourC, // true
    fiveD, //true
});

// so from two underscores and more, have a unnecessary underscore.



```

### 🙁 Actual behavior
membersText = ["_a", "___b", "____c", "_____d"]
### 🙂 Expected behavior
membersText = ["_a", "__b", "___c", "____d"]

**Comment by MartinJohns** [comment]
This is intentional. See this comment: https://github.com/microsoft/TypeScript/issues/46401#issuecomment-1205693404
