### ISSUE TITLE
Possibility to transpile TSX to MJS or CJS

### ISSUE THREAD

**Issue by mcfdez** [microsoft/TypeScript#54700]
# Suggestion

## 🔍 Search Terms

I have performed several searches with these queries:

- tsx to mjs 
- jsx to mjs 
- transpile tsx esm 
- transpile jsx esm 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Nowadays if a project made with Typescript file extensions are in .mts, when it is transpiled, the resulting files are under the .mjs format.

However, if we have .tsx files, the result is still .js. I propose to implement some way to transpile .tsx files to .mjs or .cjs to adapt it to Node's ESM standard. The system of how this transpilation would be done and what would be the result (it could be with some configuration in the tsconfig.json), I leave it in your hands.

**Comment by fatcerberus** [comment]
`.mts`/`.cts` can already contain {T|J}SX tags, afaik.  That having been said...

> However, if we have .tsx files, the result is still .js. I propose to implement some way to transpile .tsx files to .mjs or .cjs to adapt it to Node's ESM standard.

You seem to be implying that `.js` files can't be ESM.  If so, that's not true; you can put `"type": "module"` in your `package.json` to have Node treat all `.js` files as ESM.
