### ISSUE TITLE
Rename TypeScript to LintScript

### ISSUE THREAD

**Issue by calimeroteknik** [microsoft/TypeScript#54724]
# Suggestion

## 🔍 Search Terms

rename
typescript name
project name

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).
* [x] This feature would ***be necessary*** to agree with [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals), and in particular:
  * Non-goal 3: Apply a sound or "provably correct" type system. Instead, strike a balance between correctness and productivity.

## ⭐ Suggestion

I suggest to name the project in a way that is faithful to its design goals. This is not in jest. I fear this proposal will anyhow be rejected as such.

## 📃 Motivating Example

* Seeing the name of the language, I thought it intended to be a type-checked language, which it is not; it only checks it partially, aka lints it.

* After reporting or actively following several issues that were closed as "won't implement", I finally figured out that TypeScript didn't actually fully intend to be a typed ECMAScript, unlike the name claims, just a linted one covering most but not all cases. Two examples of consequences of this misunderstanding which I'm not alone having: https://github.com/microsoft/TypeScript/issues/28682 https://github.com/microsoft/TypeScript/issues/34736

## 💻 Use Cases

This would make it clear for people who expect type-checked JS that they should not, and instead that it is a JS linter, because there are `TypeError`s that make it to the runtime (e.g. #34736).
Indeed, "to strike a balance between correctness and productivity" is the job of a linter, not that of a static type checker, which makes no such compromise as having type errors pop up at run time.

**Comment by calimeroteknik** [comment]
To the inevitable reactions with emoji, for or against: please do provide your reasons. I believe in argumented discussion.

To show good will, I will state an argument against my proposal: it is an effort.

The question I ask is: is the effort worth it?
* It will keep away people like me who were mislead by the name TypeScript.
* It will also save the maintainers the trouble of dealing with bug reports and RFEs aiming to make the typing complete, as I mentioned.

**Comment by jcalz** [comment]
This is a bizarre quixotic take.  Even if everyone agreed with your sentiments and reasoning, it would still be *far* too late to make such a change.  I strongly suggest you close this issue before anyone from the TS team has to deal with it.

**Comment by calimeroteknik** [comment]
Why is it (far) too late?

Projects bigger than this one did change names, although I suspect never for such a reason.

I hear your sentiment, but why are you trying to intimidate me into retreating my suggestion?

**Comment by jcalz** [comment]
I was asking you to retract your suggestion because it's not going to happen, and I'm not inclined to spend very much effort explaining why.  Either you already understand that this is not going to happen, in which case it's bad faith to pretend otherwise.  Or you do *not* understand this, in which case the likelihood that someone outside the TS team can convince you is very low.  Either way I regret saying anything.

**Comment by nmain** [comment]
>  static type checker, which makes no such compromise as having type errors pop up at run time.

But that's simply not true.  The spectrum of "typing" and what qualifies as a "typed language" is a very broad one.  Many other languages with types, even languages that are generally referred to as "strongly statically typed", have limitations and soundness holes through which runtime errors can happen that the compiler is unable (or unwilling) to check or prove.

I did not expect the word "Type" in "Typescript" to imply that my code could never again fail, and I think many other developers would agree with me as evidenced by the popularity and longevity of the language.

**Comment by calimeroteknik** [comment]
>No type system can prevent all errors while still remaining usable

This is indeed true if your notion of "usable" mandates Turing-completeness, IIRC.
As a counter-argument, I have never produced a program that required Turing-completeness. They all fell under the slightly smaller category of https://en.wikipedia.org/wiki/Total_functional_programming (and this does not mean "looking like Haskell")

**Comment by calimeroteknik** [comment]
@Yokozuna59 Yes, the way you envision this is too brutal. Do it the mysql way… just rename the repo, keep the issues, keep the code, keep the history… *that* is a matter of pressing F2.

Even in my craziest dreams, I don't expect any more than having a `lsc` executable that allows all the iffy stuff, and meanwhile `tsc` will be able to take more liberties adding stricter checks, as people can always be told to use `lsc` if they want to take risks.

@nmain I just want to quote https://www.typescriptlang.org/ a little bit:
> TypeScript is a strongly typed programming language 
A Result You Can Trust
Safety at Scale
Catch errors early in your editor.

This should clearly be watered down, at the very least:
*  "catch errors" should be "some classes of errors"
* "A Result You Can Trust" should be "A Result You Can Trust more than before"

**Comment by benasher44** [comment]
It's not just used for scripts though anymore. What about calling it Lint for Scripts and Programs, aka LISP?

**Comment by jcalz** [comment]
also see https://github.com/microsoft/TypeScript/issues/9825#issuecomment-306272034

**Comment by fatcerberus** [comment]
> "A Result You Can Trust" should be "A Result You Can Trust more than before"

…I, um… I don’t think this issue is worth engaging with further

**Comment by RyanCavanaugh** [comment]
I've raised this up with the appropriate leadership and we have decided not to do this.
