### ISSUE TITLE
Nested union and conditional type have different behaviors in template literal and tuple type

### ISSUE THREAD

**Issue by xuld** [microsoft/TypeScript#54722]
# Bug Report
Currently these rules are applied:
- `` `foo${A | B}` `` is equivalent to `` `foo${A}` | `foo${B}` ``
- `keyof (A | B)` is equivalent to `keyof A & keyof B`

But these are not:
- `[A | B]` is not equivalent  to `[A] | [B]`
- `` `foo${X extends Y ? A : B}` `` is not equivalent  to ``X extends Y ? `foo${A}` :  `foo${B}` ``

Is this by design? Or is there a principle indicating when the union and conditional type will be expanded.

`[A | B]` and `[A] | [B]` is identical and can be assignable to each other. But when used in distributive conditional types, they have different behaviors.

### 🔎 Search Terms
in:title union template
in:title union tuple

### 🕗 Version & Regression Information
5.1.3

### 💻 Code
Example1:
```ts
function fn<T>(x: `${T extends true ? 'a' : 'b'}`, y: T extends true ? 'a' : 'b') {
	x = y
	y = x
}
```

Example2:
```ts
type X1 = keyof (1 & string)

type X<T, R> = keyof (T & R)
type X2 = X<1, string>
```

Example3:
```ts
type A = `${1 | 2}${3 | 4}`
type B = [1 | 2, 3 | 4]
```

### 🙁 Actual behavior
Example1: Cannot assign y to x; Cannot assign x to y
Example2: X1 and X2 is not identical
Example3: A ==> "13" | "14" | "23" | "24"   &    B ==> [1 | 2, 3 | 4]

### 🙂 Expected behavior
Example1: No errors
Example2: X1 should be same as X2
Example3: A ==> "13" | "14" | "23" | "24"    &   B ==> [1, 3] | [1, 4] | [2, 3] | [2, 4]

**Comment by RyanCavanaugh** [comment]
Combinatorial expansion is done *where needed*, but in general it's something to be avoided since it can quickly produce far too many types.
