### ISSUE TITLE
Support ECMA-262 arbitrary non-identifier module export names

### ISSUE THREAD

**Issue by guybedford** [microsoft/TypeScript#54733]
# Suggestion

## 🔍 Search Terms

string exports, arbitrary identifier namespace names

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

Example valid ECMA262 code that fails:

```
import { "some name" as impt } from 'external';
export { impt as "other name" }
```

See:

https://www.typescriptlang.org/play?ts=5.2.0-dev.20230621#code/KYDwDg9gTgLgBAbzmOBDAznARAC2AG3wjgHdp8ATLOAXyA

## 💻 Use Cases

Allow TypeScript to support non-identifier export names per ECMA-262 support (https://github.com/tc39/ecma262/pull/2154).

**Comment by MartinJohns** [comment]
Duplicate of #40594.

**Comment by guybedford** [comment]
Ahh, after seeing the issue I found the duplicates thanks.
