### ISSUE TITLE
"Find All References"  does not work on js exports with only object shorthand

### ISSUE THREAD

**Issue by JeremyPlease** [microsoft/TypeScript#54730]
Type: <b>Bug</b>

## Description

In a workspace with a javascript project, the "Find All References" feature does not work as expected when object literal property value shorthand is used in commonjs `module.exports`.

## Steps to reproduce:

1. Create two files:

```js
// a.js
const a = 1;
module.exports = { a };

// b.js
const { a } = require('./a');
console.log(a);
```

2. In `a.js`, right click on `a` and select "Find All References".

Expected behavior: show reference of `a` in `b.js`

Actual behavior: only shows references in `a.js`

## Screenshot

<img src="https://f.jerm.me/Jhk2A9.png" />

## Other Scenarios

Here is the full list of export scenarios that I tested:
```js
module.exports = { a }; // does not work
module.exports.a = a; // does not work
module.exports = { a: a }; // works
module.exports = { a: 1 }; // works
module.exports = ({ a }); // works
module.exports = { a, anything: true }; // works
```

## Related issue:
* https://github.com/microsoft/vscode/issues/21507

## System Details

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:33.551Z)
OS version: Darwin arm64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 4|
|Memory (System)|64.00GB (10.82GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id ff338d35-7f9a-4521-a7a9-16ade63c0054|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000
pythonidxptcf:30772540
pythondjangots:30772535

```

</details>

**Comment by fatcerberus** [comment]
I’m pretty sure this is a duplicate.  From what I remember the cause is that there’s ambiguity between whether the `a` in the source refers to the *property* `a`—in which case it’s first defined in the object literal itself—or the `a` from outside.  There’s no mechanism (or UI) to disambiguate, so FAR picks one arbitrarily.

**Comment by fatcerberus** [comment]
Found the dupe: https://github.com/microsoft/TypeScript/issues/1507

That issue is… a lot older than I thought. 😅

**Comment by JeremyPlease** [comment]
@fatcerberus Thanks for looking into this and finding the other issue. It's just 9 years old 🙃 

>  ... the cause is that there’s ambiguity between whether the a in the source refers to the property a—in which case it’s first defined in the object literal itself—or the a from outside. There’s no mechanism (or UI) to disambiguate, so FAR picks one arbitrarily.

That kind of makes sense, but the interesting thing is the following two examples find the reference of `a` in `b.js`:
```js
module.exports = ({ a }); // works
module.exports = { a, anything: true }; // works
```
So it seems like that syntax results in FAR picking the key `a` which can find the external references. 

I'm guessing this behavior is happening [here](https://github.com/microsoft/TypeScript/blob/e69a0b0e38b380677adb83ff0d20d8b8c32b2d9d/src/services/findAllReferences.ts#L2027C14-L2040)? Is there any reason we can't (or shouldn't) use both the property and the value when object shorthand is used?

**Comment by fatcerberus** [comment]
My understanding of this may be wrong but AFAIK this ends up being tricky because you don't want to unconditionally link otherwise unrelated references through an incidental assignment:

```ts
function foo() {}       // (a)
const fooey = { foo };  // (c)
fooey.foo();            // (b)
```

If I FAR on the `foo` at either `(a)` or `(b)`, then ideally I'd want it to find the `foo` at `(c)` but *not* `(b)` or `(a)` respectively, as they refer to distinct entities (an identifier in scope vs. a property of some type).  However, if I FAR on `(c)` then it's acceptable to highlight both `(a)` and `(b)`, since *in that specific position* it has both meanings.  But to avoid this linkage being treated as bidirectional, the compiler would have to track two meanings separately for the same physical reference, which it doesn't seem to be equipped to do.

**Comment by JeremyPlease** [comment]
@fatcerberus Yeah, I completely understand how this is pretty tricky and I see there is no clear winner for choosing property or value here. However, I'm hoping we could at least end up with some consistent FAR behavior.

```js
module.exports = ({ a }); // Scenario 1: FAR finds all references in the definition file AND all external references
module.exports = { a }; // Scenario 2: FAR only finds references in the definition file
```

Could you help me understand why the parenthesis in Scenario 1 makes FAR behave differently? Or, a link to the source code where this might be happening would be super helpful too.
