### ISSUE TITLE
Issue with unknown properties and functions

### ISSUE THREAD

**Issue by bryanerayner** [Microsoft/TypeScript#5473]
I am unsure how to properly write this code in Typescript 1.6:

````ts
function foo(){

}
foo.bar = function(){

};
````

I am getting an error, "Property 'bar' does not exist on type '() => void'. Is this intended behavior? What is the work around, other than aggressively using `any`?

**Comment by DanielRosenwasser** [comment]
Hey @bryanerayner, try function-namespace merging:

```TypeScript
function foo() {
}

namespace foo {
    export function bar() {
    }
}
```

As a heads up, the repo's issues tracker is mostly for bugs/feature request. In the future [StackOverflow](http://stackoverflow.com/questions/tagged/typescript) or [our Gitter channel](gitter.im/Microsoft/TypeScript) might be better places to ask questions while learning.

Hope that helps!

**Comment by bryanerayner** [comment]
I could have gone to StackOverflow. But, this is an awkward catch 22 of the language.

In the initial line of code, the error is that `bar` is an unknown property. But, if I declare an interface to represent `foo`:

````

    interface FooWithBar {
        (): void;
        bar(): void;
    }

    var foo: FooWithBar = function () {
    };
    foo.bar = function () {

    };
````
I get a different error - "Type '() => void' is not assignable to type 'FooWithBar'. Property 'bar' is missing in type '() => void'";

It's impossible to write the desired code with the language. Typescript is supposed to be a superset of Javascript, but it seems that when desiring to write code like this, you just can't use types at all.

Is that the intended behavior? If so, I can live with that. But if not, it would be good to find a solution.

**Comment by weswigham** [comment]
It's not impossible, you just need to assert that you know what you're doing with a cast. Try this out:
```ts
   interface FooWithBar {
        (): void;
        bar(): void;
    }

    var foo: FooWithBar = function () {
    } as FooWithBar;
    foo.bar = function () {

    };
```

**Comment by bryanerayner** [comment]
That works. Thanks so much, I've run into that problem many times, and now have a way to solve it.

I've posted a SO question.
