### ISSUE TITLE
Arrow functions in classes

### ISSUE THREAD

**Issue by nlamarti** [microsoft/TypeScript#54741]
# Suggestion

Currently when adding a single line function in a class you need to do this:
```
class Test { 
    isValid(): boolean {
        return true;
    }
}
```
I am proposing to have the ability in typescript to do the following
```
class Test { 
    isValid(): boolean => true;
}
```
I am aware that you can do this which we do currently but this generates a host of issues (like inheritance, comparisons) because its actually a property not a function
```
class Test { 
    const isValid = (): boolean => true;
}
```

**Comment by robgeurden** [comment]
+1

**Comment by manea-eugen** [comment]
+1

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template. It contains a "viability checklist" that shows you already that this is out of scope for TypeScript.
