### ISSUE TITLE
Spreading a discriminated union in a narrowing block widens it back

### ISSUE THREAD

**Issue by OriR** [microsoft/TypeScript#54745]
# Bug Report

### 🔎 Search Terms
discriminated, union, type, narrowing, spread

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing, discriminated union, spread

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230622#code/MYewdgzgLgBAZmGBeGAKOIQC4YG8YBGAhgE44DkR5MAPjOQeQDSFEBeOYArgLYECmJGAF8AlMgB8eAFAw5MAJZw0GEADpiQpNvpVxuWfKNKVmDaWQ6G5fYaP2YAekcwAqmAAmg6EU9ECADYAnixQABb8MP4gAG6RoJ4KUArgihBRAQDuREHpcEQBEEEwEApgwJHhlUEADpEK6WCkJCCZ-B529sLSnUYJ0DAAHsgyDg5qE6q98sIA3NNyC4rKqIPmWlaMtmP2zjAAEoKRYa38cUJVMFC1kZkKXpDwIEIQIDyRJPxEr4i+HoqwDwgfgQMDkWCCFokJbdJb9WD4TQiEaqeZLEyoJHaFDWbY7eR7AAqYQaGVeMEhz3SoBIn2AUGCLHJSSiNTqpHS4SIsHAwRgIAIACt+PSSjVPkQPGUAOYwO4PTkRK43RTlZ50hlBGE9IzdYRAAA)

### 💻 Code

```ts
 const fn = (foo: { bar: 'a' | 'b', baz: number }) => {
     if (foo.bar === 'a') {
         if (foo.bar === 'b') {
             // Understandably, the above condition is always falsy since the type is narrowed
         }
 
         const x = {
             ...foo
         };
         
         if (x.bar === 'b') {
             // Here however the type widens for some reason and it doesn't error
         }
 
         const { bar } = foo;
 
         if (bar === 'b') {
             // This also errors correctly, so it appears that only object spreading widens the type incorrectly
         }
 
     }
 }
```

### 🙁 Actual behavior

When narrowing over a discriminated union and then spreading that object somewhere else the type of the discriminant property widens to the original type.
This doesn't occur if you destructure that property or try to access that property directly, so it seems odd that spreading it over to another object would widen it.

I have seen both #47710 and #51932 but they seem a bit different than this issue.

### 🙂 Expected behavior

the discriminant property doesn't widen after spreading inside a narrowing block.

**Comment by RyanCavanaugh** [comment]
Spreading isn't exactly the same as its naive desugaring because people can and do write types which combinatorially explode if you try to do that.

**Comment by OriR** [comment]
Hey,
I'm entirely sure how after narrowing, the type can still combinatorially explode, specifically in spreading.
Can you share an example?
