### ISSUE TITLE
Type narrowing doesn't seem to consider functions that can set variables

### ISSUE THREAD

**Issue by MaxNanasy** [microsoft/TypeScript#54758]
# Bug Report

### 🔎 Search Terms

`function set variable`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `function` or `variable`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAHgXBDOYBOBLAdgcwgHwmgrsMBALx6HADcAUNfOABoAUA5AIYBGAxiwJQ3UUAMwhMovCAG9qEWRC4B7NPAWgAdMAUYmAAygaQmMAAsYOgDTQDR4-2oBfWkPxouYFEoSMmANzbB8EDhEVEwJaTloUgg-AJAaRyA)

### 💻 Code

```ts
let x: string | null = null;

setX('abc');

if (x) {
    console.log(`x.length:`, x.length);
}

function setX(value: string) {
    x = value;
}
```

### 🙁 Actual behavior

The code gives the TS error:

```
test.ts:8:32 - error TS2339: Property 'length' does not exist on type 'never'.

6     console.log(`x.length:`, x.length);
```

Note that changing `setX('abc')` to `x = 'abc'` fixes the TS error

### 🙂 Expected behavior

The code typechecks

**Comment by RyanCavanaugh** [comment]
#9998
