### ISSUE TITLE
TypeScript is broken at type-checking array/Record access

### ISSUE THREAD

**Issue by alamothe** [microsoft/TypeScript#54762]
```ts
const array = [1, 2, 3, 4]

a[i] // this should be of type number

type Key = "a" | "b" | "c"
const record: Record<Key, number> = { "a": 0, "b": 1, "c": 2 }

record[i] // this should be of type number

const record: Record<string, number> = { "a": 0, "b": 1, "c": 2 }

record[i] // this should be of type number | undefined
```

Why isn't there a way to configure TypeScript to have these most sane type assumptions? Either they're all a `number`, which is very unsafe for the third case, or with `noUncheckedIndexedAccess` they're all `number | undefined` which makes zero sense for the first two, as basically means to use `!` for every array access.

EDIT: Note also that if `Map` is used in place of `Record` for the third case, it will correctly be `number | undefined` which also makes zero sense given that `Record` and `Map` are used interchangeably and should have consistent interfaces.

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template. The behavior is working as intended and not broken. Also, `Record` and `Map` are not interchangeably.
