### ISSUE TITLE
Cannot exclulde `'console'` via `autoImportFileExcludePatterns` in VS Code

### ISSUE THREAD

**Issue by xixixao** [microsoft/TypeScript#54765]
# Bug Report

### 🔎 Search Terms

autoImportFileExcludePatterns, console

### 🕗 Version & Regression Information

At least in 1.79.2

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about autoImportFileExcludePatterns

### ⏯ Playground Link

N/A this is a VS Code issue

### 💻 Code

```
log
```

### 🙁 Actual behavior

When you type `log` VS Code suggests to import `log` from `console` despite it being blocklisted in `autoImportFileExcludePatterns`. See https://github.com/microsoft/TypeScript/issues/54135#issuecomment-1538603555

### 🙂 Expected behavior

The import is not suggested.

**Comment by andrewbranch** [comment]
Can you try putting `console.d.ts` instead of `console` in those globs?

**Comment by xixixao** [comment]
@andrewbranch using `console.d.ts` does lead to the expected behavior.

**Comment by andrewbranch** [comment]
The glob-like patterns work exactly the same as tsconfig `include`/`exclude` patterns. This could be better documented, but I think it’s working as intended.

**Comment by elijah-highbar** [comment]
This does not work for for me either. 

I have tried the following:

```
"@mui/material",
"Tooltip.d.ts",
```

has this problem regressed?
