### ISSUE TITLE
Type inference is not correct

### ISSUE THREAD

**Issue by CGQAQ** [microsoft/TypeScript#54774]
# Bug Report

### 🔎 Search Terms
Type inference

### 🕗 Version & Regression Information
5.1.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMMAKAlAbwFCL4gGwFMpk44AuRMEAWwCMiAnAH3ABMjgYwj2BubLnwxgiVAEJg5dIhz4FiJiRBMwghQF8hC6XA34A9IYB6Afh34MiALwA+OcMVl9TxcfNvtbvQbweLTSA)

### 💻 Code

![image](https://github.com/microsoft/TypeScript/assets/15936231/df846ac8-d1e7-44a5-ab03-96037d187545)

### 🙁 Actual behavior

inferred as number|undefined

### 🙂 Expected behavior
inferred as number type

**Comment by MartinJohns** [comment]
Duplicate of #9998.
