### ISSUE TITLE
Declaration merging broken with NodeNext?

### ISSUE THREAD

**Issue by benasher44** [microsoft/TypeScript#54770]
# Bug Report

### 🔎 Search Terms

- NodeNext
- Declaration
- Merging

### 🕗 Version & Regression Information

Tested on versions 4.7.4 and 5.1.3.

### ⏯ Playground Link

It's kind of a large project. See below. 

### 💻 Code

I have a branch pushed to https://github.com/benasher44/tiptap/tree/basher/nodenext.

### 🙁 Actual behavior

In packages/core/src/commands/focus.ts, `RawCommands['focus']` (the `focus` part of the type is added to `RawCommands` via merging of the declaration at the top of the file)  fails to resolve, when `moduleResolution` is set to `NodeNext` (resolves fine when set to `Node` ).

### 🙂 Expected behavior

It resolves for both "Node" and "NodeNext".

**Comment by benasher44** [comment]
I am sure this is just a different issue where something about the way this project is configured is not compatible with NodeNext, but I'm not able to figure out why this is broken.

**Comment by RyanCavanaugh** [comment]
Behavior changing when you change configuration is generally expected, or at least expectable. We'd need a minimal repro that demonstrates what's wrong in order to investigate further.

**Comment by benasher44** [comment]
I have the project linked. I'm not sure I'll be able to put together a minimal repro, but I may have time to try putting one together next week.

**Comment by benasher44** [comment]
There's a general issue though of "changing moduleResolution to NodeNext causes things to break in un-intuitive ways", and I wish there was a guide on how to debug them.

**Comment by MartinJohns** [comment]
> There's a general issue though of "changing moduleResolution to NodeNext causes things to break in un-intuitive ways", and I wish there was a guide on how to debug them.

The whole module stuff has grown over the years and is very complicated. There's an open issue about the documentation, if your use case hasn't been mentioned yet (please check before commenting) you might want to mention it. #52593
