### ISSUE TITLE
Class instance can be passed to a class constructor that does not properly implement the declared interface

### ISSUE THREAD

**Issue by shawnmcknight** [microsoft/TypeScript#54789]
# Bug Report

Within the following code, I am able to pass an instance of `Foo` to `Bar1`'s constructor even though `Foo`'s `doSomething` method is not compatible with the type declared by `BarType1`.  Effectively, this could be a runtime error if `Foo.doSomething()` were to expect property `b` to have been assigned:
```ts
interface TestInterface<T> {
	doSomething(param: T): void;
}

type FooType = { a: string; b: string };
class Foo implements TestInterface<FooType> {
	public doSomething(param: FooType): void {}
}

type BarType1 = { a: string }; // subset of FooType
class Bar1 {
	private test: TestInterface<BarType1>;

	public constructor(test: TestInterface<BarType1>) {
		this.test = test;
	}

	public anotherThing(param: BarType1) {
		this.test.doSomething(param);
	}
}

type BarType2 = { c: string }; // disjoint of FooType
class Bar2 {
	private test: TestInterface<BarType2>;

	public constructor(test: TestInterface<BarType2>) {
		this.test = test;
	}

	public anotherThing(param: BarType2) {
		this.test.doSomething(param);
	}
}

type BarType3 = { a: string; b: string; c: string}; // superset of FooType
class Bar3 {
	private test: TestInterface<BarType3>;

	public constructor(test: TestInterface<BarType3>) {
		this.test = test;
	}

	public anotherThing(param: BarType3) {
		this.test.doSomething(param);
	}
}

type BarType4 = { a: string; c: string } // contains some members of FooType as well as additional members
class Bar4 {
	private test: TestInterface<BarType4>;

	public constructor(test: TestInterface<BarType4>) {
		this.test = test;
	}

	public anotherThing(param: BarType4) {
		this.test.doSomething(param);
	}
}

const bar1 = new Bar1(new Foo()); // Shouldn't this be an error?  Property b is missing from BarType1 but it's required in FooType.  I would expect the same error as in the bar4 example below.
const bar2 = new Bar2(new Foo()); // Error "Type 'BarType2' is missing the following properties from type 'FooType': a, b" -- errors as expected
const bar3 = new Bar3(new Foo()); // No error but that seems okay -- the Foo.doSomething() would just get an extra property passed
const bar4 = new Bar4(new Foo()); // Error "Property 'b' is missing in type 'BarType4' but required in type 'FooType'" -- This error looks correct, but I'm not sure why this is an error when bar1 was not.
```

I'm guessing this is an undesirable although expected behavior in TypeScript since I am able to replicate it as a problem in all versions supported by the TypeScript playground.  However, this behavior seems incorrect to me since TS correctly detects the error in the `Bar4` instance.

I reviewed the FAQ about `strictFunctionTypes` to see if that had any bearing, but the same non-error occurs when I use a function or arrow function which accepts a parameter that is of type `TestInterface<BarType1>`.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `strictFunctionTypes`.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5gJLmvJAHlQD5kBvAWACgBIAEwHsBlRgWwjAAtQBzACgAOcKHDYAuNAEpJAN0bB6AbhoBfGjTABPQSgBijRqh0oAvBWRxJWKHyXIARtbC2QvZKpXUEAGzgYMZANGZGA2QR8IDnBA9CxcSFhECEJg410yKjpBAFcHH2AEZCZWDm4+IRExSTSTGWR5RQp1ahbNE2QAIRF0iABGZHNyS2dXd09kAHpJ5Aw8jE5kRhggw16aX39A7qgBrNpBW1k4SGRILEk4nDwkoh3evpIvGgO8gqKERhAbHIQwRig-HOYEumGuiQIKXuJkeUgoL1o5QwADpgYMzmCvLQ2tk3oVLCBGNxoKgeG5KqIJF0ejC4ftETwUcDkSV2JwyQJhJSpFiWjjtLpqVBegAmdHDBCjPgeezTYrADAAKwU4CWK1qug2fgCQrF+0OwGOp2BoPiN0hhGhuhFTw0uPy+M+3xcv3+gJNaDBCXwyUtNOtJDpCKRqLB6OBvLtrwdRTghOJwo5FOqQtFQboDIVoawLJYbPK5K5Yh5Lz5doFKCtEAAzOKRrMXHZHFK3PZJQ2xhM5XNdFAFmA1asjCYtVshbX9UcTigPVdvbcof6a7bqC9cjHkE6fn8AUCwabwT67kvq4H4RmQ2jzBHS1H1+8CUSuCSk0WqVXq+naJmmWDc6V2QqN8SzoMtV2oCtUxMAAWOsrA7Jt2xsaVVCmGYnTAOBQECDA2WQDg2AcaBAmWIdeksQIAHcIB8HwKMseh6GAMBgC+OA6IIoi+1HHUdlgydDWnDELk9M0IV9KtoJXNc8Q+L5tzdPcRLnc0JKXKSvx-bMB2vTFb3A6MHzjJ8XyAqp33UzTLz-VkylfcyQOxNQ7S3AcHBEAZzBACBKKFPp+G83zgn4KQeTQ5BmC4Rgch8egQAAcgHJFHBQONkGgKAAQAfmQZAAAVMt7bRHFCQI2AVDBpRgTK2Cg3QBgcHIB2Y+LAigCAAEccmAdr6FCEAyJMZFcuwZBKOi2L0oAD10P4zmfWYxBQDKAXo0B5pQdyoFgiAprECIIGRDZ5LckQxS8nzdQCy7gtC2UZgAUSgTKoGQAAicj4qrEV4tK-CKulYlkBgRhaMYSjpUORgiuATBgZqs4OnijUIHiyQ4AAGkcN7kAAWlx9LnoBQJ-Gm2bIHoY7nUcERawu3ydmra6gsMEKwrlUae0ERgFnmhUlm8v7GAAazgLQsaB4J+qwOMkDGia+sVHIsGQXhFjS3akB1KGiq0KmVa22D6aFaDmaHNn7uQJ6XvegroegYr4ocX7+fKgJpXWyCvvU37GoHdqup6iA+s9pGUfinH8bQRlCZtnxDGFwJPmeiA-ixv3kGweLavjWYcnasauC0PnAn5jWideyjnwGraBko0n4yO6ggA)

### 💻 Code

```ts
interface TestInterface<T> {
	doSomething(param: T): void;
}

type FooType = { a: string; b: string };
class Foo implements TestInterface<FooType> {
	public doSomething(param: FooType): void {}
}

type BarType = { a: string }; // subset of FooType
class Bar {
	private test: TestInterface<BarType>;

	public constructor(test: TestInterface<BarType>) {
		this.test = test;
	}

	public anotherThing(param: BarType) {
		this.test.doSomething(param);
	}
}

const bar = new Bar(new Foo()); // no error
```

### 🙁 Actual behavior

Construction of `bar1` does not emit a type error.

### 🙂 Expected behavior

Construction of `bar1` should emit `Property 'b' is missing in type 'BarType1' but required in type 'FooType'`

**Comment by RyanCavanaugh** [comment]
Methods are bivariant; this is in the FAQ. You can write
```ts
interface TestInterface<T> {
	doSomething: (param: T) => void;
}
```
to get the expected error

**Comment by shawnmcknight** [comment]
> Method parameters are bivariant; this is in the FAQ. You can write

Thanks for the quick response.  I missed the word `property` in the FAQ and was testing arrow functions and function declarations, but they also had the same behavior because the interface remained unchanged.  In looking again at the FAQ I understand it more clearly now.
