### ISSUE TITLE
Typescript deoptimizes wildcard imports when module type is commonjs

### ISSUE THREAD

**Issue by jeetiss** [microsoft/TypeScript#54796]
# Bug Report

```ts
import * as operations from 'utils'
operacions.add(1, 2)
```

is much slower than 

```ts
import {add} from 'utils'
add(1, 2)
```

when module type is `commonjs`

### 🔎 Search Terms

- wildcard
- wildcard imports
- wildcard imports commonjs

### ⏯ Playground Link

I created reproduction with [stackblitz](https://stackblitz.com/edit/stackblitz-starters-72cjpj?file=index.ts,dist%2Findex.js), because i needed wore than one file to reprodece this bug;

steps:
- open repro
- check `dist/index.js`

### 💻 Code

```ts
import * as operations from './utils.js';
operations.add(1, 2);

import { add } from './utils.js';
add(1, 2);
```

compiled into 

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const operations = require("./utils.js");
operations.add(1, 2);

const utils_js_1 = require("./utils.js");
(0, utils_js_1.add)(1, 2);
```

### 🙁 Actual behavior

variant with direct import is `~20-30%` faster than wildcard import

### 🙂 Expected behavior

wildcard imports should have `(0, utils_js_1.add)` optimization too

**Comment by fatcerberus** [comment]
If `imports.foo()` is slower than `(0, imports.foo)()` (since that’s the only meaningful difference in the emit) then I don’t think there’s anything TypeScript can do about that.
