### ISSUE TITLE
What is the purpose of the XMLDocument interface defined in lib.d.ts?

### ISSUE THREAD

**Issue by lord-saumagen** [Microsoft/TypeScript#5479]
Dear Ladies and Gentlemen,

it appears that the XMLDocument interface defined in lib.d.ts is only a double of the HTMLDocument interface. That's not surprising when you look at the definition:

>interface XMLDocument extends Document {
>}

>declare var XMLDocument: {
>    prototype: XMLDocument;
>    new(): XMLDocument;
>}

But I would expect the members which are defined for the "IXMLDOMDocument" as defined here:
https://msdn.microsoft.com/en-us/library/ms756987(v=vs.85).aspx

A second HTMLDocument interface which only differs in it's name doesn't make much sense to me.
Please can you explain what's the purpose of the "XMLDocument" interface? 

Kind regards, Lord Saumagen.

**Comment by rielz** [comment]
The `XMLDocument` interface is defined in the DOM specs and lib.d.ts is based on these, so the definition should stay.
But you're right, practically, it is not very useful in its current form.


https://dom.spec.whatwg.org/#xmldocument
http://www.w3.org/TR/domcore/#xmldocument

**Comment by lord-saumagen** [comment]
Dear Mr. or Mrs. rielz

thank you very much for your explanation. Now I know where the Interface comes from, but I'm still wondering how such a stupid interface could become part of the specification in the first place. It seems that some brighter persons at the W3C share my opinion. 

https://www.w3.org/Bugs/Public/show_bug.cgi?id=22960

Thank you for enlighten me and kind regards, Lord Saumagen
