### ISSUE TITLE
Can property definitions in object literal have modifiers?

### ISSUE THREAD

**Issue by spket** [Microsoft/TypeScript#5480]
This issue was found in [babel](https://github.com/babel/babel/issues/2629), some how typescript has similar behave
```javascript
var o = {
  private static async a:1,
  static async b : function() {},
}
```

**Comment by DanielRosenwasser** [comment]
1. `private` is only valid within classes, so not that one.
2. `static` would be nonsensical on an object literal property.
3. `async` is not a valid modifier for property declarations, *however*, it can be for function expressions, arrow functions, and object methods:

    ```TypeScript
    var o = {
        async method() { },
        method2: async function foo() { },
    }
    ```

If you really need static properties or privacy modifiers, you'd be better served by a class expression:

```TypeScript
var o = class {
  private static async a = 1,
  static async b() {},
}
```
