### ISSUE TITLE
Conditional type using never type does not work in generic functions

### ISSUE THREAD

**Issue by dummdidumm** [microsoft/TypeScript#54806]
# Bug Report

When using a conditional type that checks for the `never` type inside a function with a generic parameter that check is not correctly executed and the type is not narrowed accordingly, even if the generic has a constraint that makes clear that the generic type can't be `never` (though it should probably also work without a constraint).

### 🔎 Search Terms

generic function narrow condition type never

Possibly related to #49852 / #53455

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about generic functions and never type

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/C4TwDgpgBAkgzgOQgNwgJwDwBVwQHxQC8UA2jpALpQQAewEAdgCZykMrpUD8UArsxABmAS3ZMoALihxgaUQHMA3AFgAUKEiw4AIQD2ugDYQAhg2y4CxctFr1mrAEb6jpqDxlyG8yXwEixKqpqTBAAxgbGaNCC-KHAwroMUOyoaABiZlh4ABTAUlgAlFLwSKnYeIEh4ZHRsfGJUE6GJgwZ5bn5RVp6zablgWoxDHEJSfKM6MKhbVjUdIwsjc4tOXlQhVAA3moAkKGJMku9DABKEHC8BsBERy6tDLkFgTtNd2cXVwB0wLoAyrIKbIFKAAehBUAA7ro0ABrOBSV4td6Xa7CVj7NBROIGEDJSJoXQQiDiH5QDTQDwKNS7fYMQ4pdDIq5pAkAWwAMsJ6GhjAYbgz0g9ZLwIE9dgKmcAWboOVz0Lzvn8AV4gYpQeCobD4ckOGhJdLZdzeVA0VAMVjgDi8ZjCcSyboybhpMr5NTVHsDtcJecUQaAOITOShfm6jKPZ7ej5StkB9hBxX-TzyVXq6g2tBSSO+mOBqYm1gMXTXc1hS24hj420kh3k51JtQAXyAA)

### 💻 Code

```ts
type IsNever<Type> = [Type] extends [never] ? undefined : string;
type IsBoolean<Type> = Type extends boolean ? string : undefined;

declare function neverFn<T>(t: T): IsNever<T>;
declare function booleanFn<T>(t: T): IsBoolean<T>;

function genericFn<T extends boolean>(t: T) {
	const booleanResult = booleanFn(t);
	booleanResult.toString() // works: booleanResult is correctly narrowed to type string

	const neverResultFromLiteral = neverFn(true);
	neverResultFromLiteral.toString(); // works: neverResultFromLiteral is correctly narrowed to type string

	const neverResultFromGeneric = neverFn(t);
	neverResultFromGeneric.toString(); // error: neverResultFromGeneric is not correctly narrowed to type string
}
```

### 🙁 Actual behavior

`neverResultFromGeneric` is not correctly narrowed to type string

### 🙂 Expected behavior

`neverResultFromGeneric` is correctly narrowed to type string

**Comment by jcalz** [comment]
I'm not seeing a bug here.

> even if the generic has a constraint that makes clear that the generic type can't be `never`

But `never` is the bottom type in TypeScript: for all `X`, `never` extends `X`. One cannot use a generic constraint to prohibit `never`.  So `genericFn<never>` is a valid instantiation.  Could you elaborate on where you think there's a bug?

**Comment by dummdidumm** [comment]
The use case here is to type that a function should never accept a second parameter under certain cirumstances:

```ts
// type definition
interface EventDispatcher<EventMap extends Record<string, any>> {
	<Type extends keyof EventMap>(
		...args: [EventMap[Type]] extends [never]
			? [type: Type, parameter?: null | undefined]
			: null extends EventMap[Type]
			? [type: Type, parameter?: EventMap[Type]]
			: undefined extends EventMap[Type]
			? [type: Type, parameter?: EventMap[Type]]
			: [type: Type, parameter: EventMap[Type]]
	): boolean;
}

// function definition
declare function createEventDispatcher<EventMap extends Record<string, any> = any>(): EventDispatcher<EventMap>;

// usage
const dispatch = createEventDispatcher<{
   requiredParam: string;
   noParam: never;
   optionalParam: string | null;
}>();

dispatch('requiredParam'); // error, no second param given
dispatch('noParam', 'foo'); // error, second param given
```

I guess I need to rewrite the type to use `noParam: null` for that case then - this luckily works in this case. I'm curious though - assuming that _wouldn't_ work for me, how should one be able to "ban" `never` from a generic then to get around this? Not possible, because it's a type system limitation?

**Comment by fatcerberus** [comment]
It's actually a fundamental type theoretical limitation - the bottom type `never` is assignable *to* all types, just as `unknown` is assignable *from* all types.  This is related to the logical principle of explosion: if you "have a value of type `never`"--which has no values--then that's a logical contradiction and you can thus "prove anything from a contradiction."  Of course this is just the theory; the practical idea it corresponds to is, any code that has such a value must be unreachable by definition, so it's impossible to prove or disprove that its type is correct (because type checking it at all presumes it's reachable and thus invokes the contradiction).

**Comment by RyanCavanaugh** [comment]
The definition of `neverFn` is the root cause here. What you're saying is that if you call this function, then it returns a `string` if the value isn't `never`. But if you have a value of type `never`, then you can't be there in the first place. So this function is the same as
```ts
declare function neverFn<T>(t: T): string;
```
and you're just making it much more confusing to reason about by saying `IsNever<T>` instead. There's no reason to do that.

**Comment by dummdidumm** [comment]
Apologies, I should've made the use case more clear - this is only what I reduced this to. The actual use case can be found in [this playground](https://www.typescriptlang.org/play?#code/PTAEBcE8AcFNQCawGYEsB2ryoPboLABQG4sATsgIYDG8AogG6zrgAiqAztJeNQBbkAPI2bgAspWihYAD1LoEHUACVY1HGQSCO4MhgDmAGlCV0kAHznQAbyIBIQQBUY8WfMWgA1rEg5koERYJaHMACns7ADpoyjJ9DgAuUABtQPFJZOc4AF1s6TlmD2T0WCYybIi7AH4UqDgkrNhjbjJKAFtYUjIqpPQAVwAbAdAAH1A+hRQMWAQKwjsF3sHht0KlNODMlzmF6tqXBpdm2PbO8h6ApiCMxtzKpImkNBKEfPd1q-ToLZzKmuS6rBDnBjq0Ol0Lhsbtsdot9vVQI1Qacukkod9bjsAJRJABGOBwA1gpgA3EQAL5EIggUDICbUbB4RBTTCMgiEJDUAaxeB09AM3DoUDUMjE0hpdhcHj8ITot5rFRqDRaHR6dBGExmKwAXk1FlCOMuokl3F4AjIwk+wXMZMI1LAfQ4lH0sCI6nQOkQnFN-FAupFYtgEu90vNglshFAUdFAEc+qhRQgAAonNpJVUGW1R0DoHApsG9UrkLNRnDQNmUAb59rp3QGUY55a28lhLG2ogIENm0IAclj8cT1baPbboBp5DIGmMudAHCVClALXaoH0qCuHa7-F7uaHPeMPeQBJHJLHYAnU9n89eS7aK7XzCphBpGA4qCQJlp9LZRD5AqZyHQJx5QUJR8UJYl0DCcAGixGx7HdT1OylM0-WFUUeCDT4TVDIQI2zBZ+wTGYhwaEtQAWHdU0LMoyIWMsKyrKjZzrdUG36IZbTsFsDXbeYkJ9Phe0IwdUz3CAyD6WBR3HMhJzIYxHGAjwwKJUxjA4HBZz4HBBleAB3DRPFAEh42wJgBkgYxcT6cBEWFHSBleXF4BKMpZwwWgcyLMglNAglVPQdTNPdTs2WMpRc1s9BYknPSZgpIggA).

Essentially the task is to give the user some way to specify that a function when called with a specific string as the first parameter only accepts `undefined` or `null` as the second parameter (the parameter shouldn't be `never` so that you can actually pass something to it to fill the third parameter) - and the conditional should work for both with and without strict null types. But I guess `never` is not the right type to formulate this.

**Comment by RyanCavanaugh** [comment]
That doesn't seem incorrect either. If we follow the rule-of-thumb that a generic body should work for any valid instantiation of its type parameters, the function's error is correct:
```ts
// inside a function
function fn<T extends boolean>(t: T) {
	const dispatch = createEventDispatcher<{
   		requiredParam: T;
   		noParam: never;
   		optionalParam: string | null;
	}>();

	dispatch('requiredParam', true);
	// Modified to expose
	return dispatch;
}

// Sample instantiation
const a = fn(false);
// It's not allowed.
a('requiredParam', true);
```

**Comment by dummdidumm** [comment]
I now understand that this isn't incorrect because `T extends boolean` -> `T` could be never `never extends boolean` == valid -> can't be narrowed.

I guess at this point this deviated into a question rather than an issue, so I'm going to close this - thanks for the explanation everyone. What I take from this is that you should be _very_ careful where you use `never` as it quickly breaks down in (at first) unexpected ways when used with generic types that can't be narrowed (in other words, inside the function that defines the generic).

**Comment by fatcerberus** [comment]
@dummdidumm A good way to think about it is: “I have a value of type `never`” -> I’ve already thrown an error/crashed.  If you *haven’t*, then that’s a type violation in itself.  So you shouldn’t really worry about people passing `never`s to your functions.

**Comment by dummdidumm** [comment]
That is true - and I also shouldn't use/encourage `never` as way for people to type that for example a parameter does not exist (as I did in this case), as that opens the path to this type violation.
