### ISSUE TITLE
Mapped Types: using 'boolean' as a mapped value produces no autosuggest

### ISSUE THREAD

**Issue by RossCurry** [microsoft/TypeScript#54808]
# Bug Report

### 🔎 Search Terms

mapped autocomplete bug

### 🕗 Version & Regression Information

I have tested this in the playground from versions 3.5.1 => 5.1.3.
I have not tested the list exhaustively, but more than 6 versions. 
I have also tested this in Nightly. It doesn't work there either.
None of them work.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/PTAEEkGdIVwU1AdwJYBcAWoC2BDADnnACaioCehkANKAEYD29ANnDgHbb6EkBuOT8UHgBO9IjADGCNvVA4YqerADmyuJFQAoTcjao4wgGY4poAILDUyDaADem0HUZMAXKADk7gNyaAvtvJCUAAhZ1Y2AFl8AB4AFQo4AD5QAF47B1AAbQAFUUJLMlBdUABrODJ6Q1B4wgBdN1RhQS9QEFAAOVkiZENDAzg2U119YQl0dmVdZTo4VEQ4AYamhAAfUGMmSFWnZnC-H0CEAGVGqai8OITktPtHHLyDciKOMoqqmrh60AAiQ0Zv0Brb60HDCb4+XwHBIdGBYWgGc6XQjXdJ3XL0fJPYqvSrVBJfACMgNAAE4SRCfJpDiEwuxztxUjTdnSYhYrBpElCgidhGcuMRGTy+Rc2dZUJyqdD2rD4cJ6QK0tK4QjWZYxRLtBJ6GwbPoNKFmG4mSwWQQFaidq5HK0wDI5AolDBVOotP4tTrUKQXUK2MojT7lPKSDcMgxDT8QWCbUh6MISpA-Jp3bqXUrZUa0yqzcGLWGrUS2ohY-HE0A)

### 💻 Code

```ts
// Issue with mapped types, boolean mapped value produce no autosuggest

interface Artist {
  bool: '';
}

type BooleanMap<Type> = {
  [Property in keyof Type]: true ; // No difference interchanging between: true | false | boolean
};
type StringMap<Type> = {
  [Property in keyof Type]: "foo" | "bar";
};
type NumberMap<Type> = {
  [Property in keyof Type]: 1 | 99;
};

type BooleanMapped = BooleanMap<Artist>;
type StringMapped = StringMap<Artist>;
type NumberMapped = NumberMap<Artist>;


const testBool:  BooleanMapped = {
  bool:   // no autosuggest
}
const testString:  StringMapped = {
  bool: "bar" // works
}
const testNumber:  NumberMapped = {
  bool: 1 // works
}

```

### 🙁 Actual behavior

On line 23 I use the autosuggest/completion shortcut, after the property 'bool'.
The list shown is not what the mapped type ('BooleanMap') indicates: true.

I will add that hovering over the key, in this case 'bool', there the correct suggestion is given.
So possibly this is to do with some communication between the editor and ts. 🤷 

### 🙂 Expected behavior

Well I am expecting to be autosuggested the boolean value 'true' on line 23.
On lines 26 ad 29 the other mapping types give me the correct autosuggestions, either a string or number. 
This indicates that behaviour I expect should be there.

**Comment by fatcerberus** [comment]
Messing around with this in the playground, I'm not seeing suggestions for *any* of these.

**Comment by RossCurry** [comment]
That's strange. I definitely am. In the example I left the value empty, on line 23. Did you complete that, to true. And then try the others?

<a href="https://imgbb.com/"><img src="https://i.ibb.co/MCScxpZ/Screenshot-2023-06-28-at-15-49-32.png" alt="Screenshot-2023-06-28-at-15-49-32" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>you foto</a>

**Comment by fatcerberus** [comment]
Huh, I got it after pressing Ctrl+Space to get the suggestion popup and you're right, there's no suggestion for `true`.  I could have sworn the shortcut used to be Cmd+Shift+Space though...

**Comment by RyanCavanaugh** [comment]
I'm not understanding what the implied bug about mapped types here is. `boolean`, in general, doesn't prompt `true` / `false`:
```ts
let t: boolean = /**/
```

Is this just a general suggestion to always include `true` and/or `false` when those are present in the target type?

**Comment by fatcerberus** [comment]
I just assumed OP happened to notice it when using mapped types but it's actually a more general issue (as you demonstrated)
