### ISSUE TITLE
Missing computed properties on expando functions 

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#54811]
# Bug Report

### 🔎 Search Terms

expando functions computed properties

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/MYewdgzgLgBMMF4YCIDCyCwAoApgDwAcQAnWAMwFcxgoBLcGAEx2ABsYAKAShgG8BfbAHohTFqwB0ZECEQpMWZmwDayAELIAunIAM2Ja2XBtSPVmwWsQA)

### 💻 Code

```ts
const c = "C"
export function decl () {}
// decl.foo = ""
decl["B"] = 0
decl[c] = 0
```

### 🙁 Actual behavior

Properties "B"  and "C" are not present in the generated declarations unless `decl.foo` is uncommented. 

### 🙂 Expected behavior

Properties "B"  and "C" should be present in the generated declaration regardless of the presence of `foo`.

**Comment by dragomirtitian** [comment]
Found this while trying to emulate the behavior in isolated declarations

**Comment by aditya1** [comment]
Can I work on this one? I’m interviewing for a company, which wants me to contribute to some open source project in the form of PR? I’m looking to contribute for 2-4 hours.

**Comment by WilczynskiT** [comment]
@aditya1 You don’t have to ask anyone ;) Just fork the repo, fix the bug, and then open a pull request

**Comment by dragomirtitian** [comment]
> Can I work on this one? I’m interviewing for a company, which wants me to contribute to some open source project in the form of PR? I’m looking to contribute for 2-4 hours.

@aditya1  I would look in `isExpandoFunctionDeclaration` the check there seems different from what is happening in the declaration emitter at https://github.com/microsoft/TypeScript/blob/dd3e81a6752401f1656e2d02354bf35c3baac3ea/src/compiler/transformers/declarations.ts#L1528
