### ISSUE TITLE
"from" keyword displaying incorrect completions

### ISSUE THREAD

**Issue by armanio123** [microsoft/TypeScript#54818]
# Bug Report

When typing an import statement the `from` keyword is not shown on the completion list correctly. Note that this only happens in `js` and `jsx` files.

Related item: https://developercommunity.visualstudio.com/t/Javascript:-from-keyword-overwritten-b/10383619

![image](https://github.com/microsoft/TypeScript/assets/13305542/889d16c4-235a-412d-843a-264621793e5d)

### 🔎 Search Terms

completion import from

### 💻 Code

file.js:
```js
import Foo fro| // <--- At this point fromBar is being suggested by completions.

function fromBar() {}
```

### 🙁 Actual behavior

`from` keyword on an import statement shows any valid completion that contains "from".

### 🙂 Expected behavior

Only the `from` keyword should be displayed.

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
