### ISSUE TITLE
Error TS1005 thrown due to incorrect ES6 signature for isArray in ArrayConstructor

### ISSUE THREAD

**Issue by SphinxKnight** [Microsoft/TypeScript#5481]
Setting up https://github.com/SphinxKnight/Twitter-Assistant, at the `npm run build`, a TS1005 error was thrown. This is due to the signature of the `isArray` method in `lib.es6.d.ts` which is incorrect.

This typo also occurs in signatures for `isView` with `ArrayBuffer`.

Note: This wasn't detected by running the tests.

**Comment by SphinxKnight** [comment]
PR has been suggested here https://github.com/Microsoft/TypeScript/pull/5482

**Comment by DanielRosenwasser** [comment]
As mentioned in the PR, this is a duplicate of #3873.
