### ISSUE TITLE
Redux Toolkit Reselect Library TypeScript Features Not Built

### ISSUE THREAD

**Issue by secretLabHQ389** [microsoft/TypeScript#54821]
# Bug Report

When building frontend storage with Redux Toolkit, one way to prevent state loss is to use the library 'reselect'. When using TypeScript, I noticed a lot of missing features for this ecosystem.

Please provide an example of Redux Toolkit with extra reducers for API calls that uses TypeScript, along with selectors for state objects using TypeScript.

There are a lot of variations posted on GitHub that are not functional when tested.

Preferred frontend is React.

### 🔎 Search Terms

TypeScript
Redux Toolkit
API calls
Selectors

### 🕗 Version & Regression Information

Please keep and fill in the line that best applies:

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Redux Toolkit.

### ⏯ Playground Link

No Playground.

### 💻 Code

No code- requesting a code example from scratch.

### 🙁 Actual behavior

Tried to use TypeScript in Redux Toolkit along with the library Reselect. Errors prevented the selectors and extra reducers.

### 🙂 Expected behavior

Building in JavaScript delivers built-in error handling and loading status for API calls and selectors for each state object that do not lose state from asynchronous activities.

**Comment by MartinJohns** [comment]
You should ask for this in the Redux repository. The TypeScript repository is the wrong place to ask for third-party libraries.

**Comment by MartinJohns** [comment]
The third-party library is providing the types, not TypeScript itself.

**Comment by secretLabHQ389** [comment]
I posted it here, to follow along: https://github.com/reduxjs/redux-toolkit/discussions/3566

**Comment by RyanCavanaugh** [comment]
This isn't a support forum.
