### ISSUE TITLE
Some thoughts on the front page md file

### ISSUE THREAD

**Issue by milkawa** [microsoft/TypeScript#54828]
# Suggestion

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ✔] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ✔] This wouldn't change the runtime behavior of existing JavaScript code
* [ ✔] This could be implemented without emitting different JS based on the types of the expressions
* [ ✔] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ✔] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

First, we can create a new home page MD file (in other languages) for people who can't speak English. Second, we can add Other entries to the original one, which can put links to some tools, such as ts-node, to facilitate debugging and learning.

One suggestion: you can add the yarn installation method to the home MD file, because some learners are not good at NPM (or bugs) or don't want to use NPM to install type script

## 📃 Motivating Example

There is nothing to say here, the main thing is to add some practical debugging tools to the home page MD file.

## 💻 Use Cases

  1.The utility can be increased so that useful tools can be discovered.
 2.It makes the document less concise because now there is only one change.
 3.My approach is to keep the text as simple as possible, as easy to read as possible and as aesthetically pleasing as possible.

**Comment by RyanCavanaugh** [comment]
This feedback doesn't really align with other feedback we've heard.
