### ISSUE TITLE
5.1: union involving keyof on generic type is wrongly narrowed

### ISSUE THREAD

**Issue by LukeNotable** [microsoft/TypeScript#54837]
# Bug Report

### 🔎 Search Terms

`union`, `narrow`, `keyof` (for issues since 5.1 beta release date)

### 🕗 Version & Regression Information

This changed between versions 5.0.4 and 5.1.3
(and is still broken in nightly)

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/GYVwdgxgLglg9mABAcwKZQGI1QGwCYA8AKoqgB5Sph4DOicARgFarQB8AFGQFyIkA+iMCBw4ANIgDWvSagCecYHwCUiAN4AoRIggIaURACdUNEQYC8iMogD8VgNqSAuol7DRAbi2IA9D8QArAB0AAy8xqY4FnyO8op8LoLuON5+gUEAjOEmZoiWyd7GUCCGSBFmXgC+GkA)

### 💻 Code

This is the simplest reproduction I could find:

```ts
function getField<T extends object>(x: T | null, k: keyof T) {
  const result = x ? x[k] : null;
  // 5.0: result = T[keyof T] | null
  // 5.1: result = null
  return result;
}
```

### 🙁 Actual behavior

The union `T[keyof T] | null` from the ternary was reduced to just `null`, when the result may very well be not null.

### 🙂 Expected behavior

The result type should remain `T[keyof T] | null`.

**Comment by ahejlsberg** [comment]
This appears to have been broken by #53059.

**Comment by ahejlsberg** [comment]
Specifically, as we're examining constraints of `T[keyof T]`, the logic added in #53059 constructs the type `T[never]`, which reduces to `never`, which is a subtype of everything. Clearly not correct.

**Comment by ahejlsberg** [comment]
It's even more broken than I thought:

```ts
function foo<T extends object>(a: T[keyof T]) {
    let b: number = a;  // No error!
}
```

I'm going to put up a PR to back out #53059.
