### ISSUE TITLE
Type correlation regression 

### ISSUE THREAD

**Issue by jfet97** [microsoft/TypeScript#54834]
# Bug Report

### 🔎 Search Terms

indexed Access Inference Improvements, indexed access type, mapped type, correlated types

### 🕗 Version & Regression Information

When did you start seeing this bug occur? 

Without `Readonly` it never worked, the compiler doesn't see the correlation between `v[node.type]` and `node`.
With `Readonly` stopped working from `5.1.3`.

### ⏯ Playground Link

[With `Readonly`](https://www.typescriptlang.org/play?target=9&jsx=0&noErrorTruncation=true&ts=4.6.4#code/C4TwDgpgBAcgrgWwgJwJYGMAyrgoIYA2UAvFAN4BQUUAboXBAFxQB2iARigNxVSiTMARPCRosOfAUE8Avj37QAysDQsA5tlzJCJcrzoEGzAM4rU6ntQVDlqjRO1TZ88NACSAEwgtgqAGaoKLqU1Cx4SCZmFrzWUIKe3r4BKNIUchQKUADChAQAogAeYMgQxsaoAPYswbxhEVCmdpZQeMhqiInGzAAiyBVgnK0wFV4A2gC6zbGCOQT5RSVllSyp6RmuUL39g8jDXiS8AD6wHWKakkdQtub2WoSXCT7+gciXs-PFpeVVPOuQUAAVVwAWTwYBq1FGAGkoOZNn0BhAhiMIKNBApBONxsxCio8OhgAAeLaI5FeAA05D4rmYMJkAD5nBQ-tAAGqocrACrICFQaGw6oAawgIAqfkBILB2KgAAoWCjmAAlJEeKoEECEoGQUFgaHjekAShI9NoFVQHiZFD8cBYBOWtA5OD2EEJMIgBVwLA8xigwtF4q1EB19JltQVUGVeFVLHVmsluqh+vJ+mY7M53IoRpCtFG8q8ADoFOM5SiDbIKEA)
[Without `Readonly`](https://www.typescriptlang.org/play?target=9&jsx=0&noErrorTruncation=true&ts=4.6.4#code/C4TwDgpgBAcgrgWwgJwJYGMAyrgoIYA2UAvFAN4BQUUAboXBAFxQB2iARigNxVSiTMARPCRosOfAUE8Avj37QAysDQsA5tlzJCJcrzoEGzAM4rU6ntQVDlqjRO1TZ88NACSAEwgtgqAGaoKLqU1Cx4SCZmFrzWUIKe3r4BKNIUchQKUADChAQAogAeYMgQxsaoAPYswbxhEVCmdpZQeMhqiInGzAAiyBVgnK0wFV4A2gC6zbGCOQT5RSVllSyp6RmuUL39g8jDXiS8AD6wHWKakkdQtub2WoSXCT7+gciXs-PFpeVVPOuQUAAVVwAWTwYBq1FGAGkoOZNn0BhAhiMIKNBApBONxsxCio8OhgAAeLaI5FeAA05D4rmYMJkAD5nBQ-tAAGqocrACrICFQaGw6oAawgIAqfkBILB2KgAAoWCjmEDIKCwNDxgBKEj02gVVAeJkUPxwFgE5a0Dk4PYQQkwiAFXAsDzGKDC0XipUQFX0mW1BUS5VgtXk-TMdmc7kUTUhWijeVeAB0CnGcpR6tkFCAA)

### 💻 Code

```ts repro
type NumericLiteral = {
  value: number;
  type: "NumericLiteral";
};
type StringLiteral = {
  value: string;
  type: "StringLiteral";
};
type Identifier = {
  name: string;
  type: "Identifier";
};
type CallExpression = {
  name: string;
  arguments: DropbearNode[];
  type: "CallExpression";
};

type DropbearNode =
  | NumericLiteral
  | StringLiteral
  | Identifier
  | CallExpression;

type TypeMap = {
  [K in DropbearNode["type"]]: Extract<DropbearNode, { type: K }>;
};

type Visitor = {
  [K in keyof TypeMap]: (node: Readonly<TypeMap[K]>) => void;
  //      I am referring to this ^ one...
};

function visitNode<K extends keyof TypeMap>(
  node: Readonly<TypeMap[K]>,
  // ... and ^ this one 
  v: Visitor
) {
  v[node.type](node);
}
```

### 🙁 Actual behavior

The focus is the implementation of the `visitNode` function .

Without the use of `Readonly` in the definition of `Visitor` and `visitNode` the code does not compile in any version of TS. On the other hand, using `Readonly` in those definitions has worked until `5.1.3`. Thanks to those `Readonly` TS was somehow able to see the correlation between `v[node.type]` and `node`.

P.S. It seems that `v[node.type as K](node)` always solves the problem, in all versions, with or without the use of `Readonly`.

### 🙂 Expected behavior

I repropose a simplified version of this example because I've recently had a chance to get my hands back on code that makes use of the pattern suggested in #47109. This is sort of a simplified version of what is suggested in that PR so I am not sure about the right behaviour.

It would be nice if TS would be able to support this simplified pattern for expressing correlations, instead of something more convoluted like [this one](https://www.typescriptlang.org/play?target=9&jsx=0&noErrorTruncation=true&ts=5.2.0-dev.20230629#code/C4TwDgpgBAcg9gEwgZygXigbwFBVgVwFsIAnASwGMAZM4UgQwBsAuLXPKANyfwlYDsiAI1IBudgF92AZWDl+Acxp0STVjg5cefKMjllF4vFLwBJJP2BkAZmVLr2efvWKs98hUagmoAYSaMAKIAHmAkKMhkcPwOms6uuvqGjlD0JApEEJbIrAAiJHBgImnwSADaALpeUlLYoJBQ+YXFJKUQADwA0lAQwXT8CKgA1hAgcNawiCjoUCNjE23IAHwzmFBlAApQBlCdFbEc9TobADTYElAAZJNIyJsVEmV74nXg0ABqZJHAcCSr7E9tvxZqNxjcUPsoAAKfhTPIFIoQEpTLpLACU6BWnDgZAQ5xe1nw-AoVmiXC+tDaXR6fSygxB83ByxhcMaCJaVM6SxOXFYn2+vwxGi4ZVhSAAdEcKiykGjzthsEgKIw0tAKNE9LyoPzaL8FUA) where I think I am perfectly following what is indicated in #47109. And TS seems to be able to do it, although I don't know why `Readonly` was needed nor why it suddenly stopped working.

**Comment by RyanCavanaugh** [comment]
#53098

**Comment by Andarist** [comment]
So it seems that this fixes it https://github.com/microsoft/TypeScript/pull/54689 but I'm not entirely sure if that solution is on the right track.

**Comment by ahejlsberg** [comment]
I think this somewhat accidentally worked with `Readonly`, but now we do a better job of preserving the higher order types and thus we detect more situations where types differ at higher order. A formulation of the problem that more closely follows the pattern in #47109 seems to work nicely:

```ts
type TypeMap = {
  NumericLiteral: { value: number },
  StringLiteral: { value: string },
  Identifier: { name: string },
  CallExpression: { name: string, arguments: DropbearNode[] }
};

type DropbearNode<K extends keyof TypeMap = keyof TypeMap> = { [P in K]: { type: P } & TypeMap[P] }[K];

type NumericLiteral = DropbearNode<"NumericLiteral">;
type StringLiteral = DropbearNode<"StringLiteral">;
type Identifier = DropbearNode<"Identifier">;
type CallExpression = DropbearNode<"CallExpression">;

type Visitor = {
  [K in keyof TypeMap]: (node: DropbearNode<K>) => void;
};

function visitNode<K extends keyof TypeMap>(node: DropbearNode<K>, v: Visitor) {
  v[node.type](node);
}
```

**Comment by jfet97** [comment]
@ahejlsberg yes that solution works nicely until we need to apply modifiers to the type of `node` just like `Readonly`. Is there a solution for this? [Link to playground](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/C4TwDgpgBAKuEFkCGYoF4oG8BQUoDkBXAWwgCcBLAYwBkLhykAbALiygDdnCI2A7EgCNyUAL4AaXFADKwSnwDmdBmWZtMnbrygBnORUVjJeAJIATCH2AUAZhXLqofJKTZ75Co1IDCzJgFEADzAyCB0dCgB7PkdnV119RXEoJDIFEktgHTYAETJIsGFU-EiLAG0AXTFsUQBubGxQSCg8gqKyEosAHgBpKAhAhj4zHSgAawgQSJtYeGRUDAmpmbhIeYA+dHYygAUoAygeiscm7T3RKAAyWbWUXarRMqP6xvgCDMpaekYmLdbCiDFUoQLoAIiIpE+yh+oPW9VOMkSSm+ql+GH+7U6INBsg80NRsPhb3MmVs9jIf3yAKB3VBJKsZPIhNezV8TACwVC4SifEpbUBHWBYLZHJCYQi0WZLOgADUKBFgJEKRgcHgnvteUtpjdEChjlAABR8YFsABKgLM0SYIC6GIFWN663WAEp0JsOJEKGZ6nUGjZCHwqNZopx5fQHX0BkMRuNJtrVrqwOsjSaoOakJa+NbbVTMUKek7khw2HKFUrXarOGVjRYAHSnCopizOn1AA)

**Comment by Andarist** [comment]
It works if `Readonly` gets pushed into `DropbearNode` and if we avoid wrapping it over `{ type: P }`: [TS playground](https://www.typescriptlang.org/play?ts=5.4.0-dev.20240115#code/C4TwDgpgBAKuEFkCGYoF4oG8BQUoDkBXAWwgCcBLAYwBkLhykAbALiygDdnCI2A7EgCNyUAL4BuXFADKwSnwDmdBmWZtMnbrygBnORUVjJeAJIATCH2AUAZhXLqofJKTZ75Co1IDCzJgFEADzAyCB0dCgB7PkdnV119RXEoJDIFEktgHTYAETJIsGFU-EiLAG0AXS8JbGxQSCg8gqKyEosAHgBpKAhAhj4zHSgAawgQSJtYeGRUDFHxybhIGYA+dCwpMoAFKAMoTorHUKQzaKYQKHrtHdEoADIoACUIE7OQdqXEFG2KlclRMoHSR1eAEDKUWj0RhMdZNQovVqlCDtABERFIEOU0JRfxBDVkHixqhhGDhLTayJRBIMSihxJxkiuUHMmVs9jIsPy8OKSNRLKsbPIDLx0F8TACwVC4SifE5zQRFNRYolITCEWiwpFUAAahQIsBIhyMDg8IDdrL5hMpssUIcoAAKPhI3Jc8m8zorACU6DWHEiFDM-2BNkIfCo1minD19EV3V6-UGIzGVs+q0dzsaroV7pWABpOGxdfrDd6TZwyk6LAA6K4VdMWT3-bBAA).
