### ISSUE TITLE
Importing an exported "declare const" doesn't work

### ISSUE THREAD

**Issue by paulcdejean** [microsoft/TypeScript#54848]
# Bug Report

### 🔎 Search Terms

I searched all over. I eventually found this stackoverflow but it's unanswered so I added a bounty...

https://stackoverflow.com/questions/68133038/how-to-export-a-declared-external-value-as-a-named-export

### 🕗 Version & Regression Information

tsc Version 5.0.4

### ⏯ Playground Link

Playground link doesn't work due to this requiring multiple files.

### 💻 Code

**This code works:**

```ts
declare const ThisReallyExists: string
console.log(ThisReallyExists)
```

Output:
`This global variable really exists, it is just in a mysterious place outside the code`

**This code compiles but doesn't work:**

stuff.d.ts
```ts
export declare const ThisReallyExists: string
```

main.ts
```ts
import { ThisReallyExists } from "./stuff"
console.log(ThisReallyExists)
```

Output:
```Could not load stuff.js no such file or directory```

This is because stuff.d.ts gets removed during compilation but the import does not.

**This code WOULD work if it were able to compile.**

stuff.d.ts
```ts
export declare const ThisReallyExists: string
```

main.ts
```ts
import type { ThisReallyExists } from "./stuff"
console.log(ThisReallyExists)
```

Output:
```tsc: ThisReallyExists cannot be used as a value because it was imported using 'import type'```

### 🙁 Actual behavior

You are forced to inline all your `declare const` statements. `export declare const` doesn't work.

### 🙂 Expected behavior

Code with `export declare const` is able to be built.

**Comment by paulcdejean** [comment]
There's `import type` can we maybe add `import global` or something?

**Comment by MartinJohns** [comment]
I don't see a bug here. A .d.ts file declares types for objects that exist already at runtime, but if it doesn't really exist (no stuff.js) then your code does not match reality. Import type does not work because you're trying for import a value.

**Comment by paulcdejean** [comment]
@MartinJohns `declare const` isn't a value, it's a typescript fiction. It can't be actually imported at runtime, just like a type can't be actually imported at runtime.

`export declare const ThisReallyExists: string` gets stripped by tsc, just as a ` export Interface` declaration does.

`export declare const ThisReallyExists: string` can be included in a d.ts file, because it's a pure typescript fiction, just like a `export Interface` or similar does.

If you put `export declare const ThisReallyExists: string` into a .ts file, you get basically the same error:

`./stuff doesn't export ThisReallyExists`

**Comment by paulcdejean** [comment]
I found a sort of workaround, but it's pretty stupid...

```ts
declare const ThisReallyExists: string
export const bogusThing = ThisReallyExists;
export {bogusThing as ThisReallyExists};
```

**Comment by paulcdejean** [comment]
Also why is:

```ts
export declare const ThisReallyExists: string
```

Valid typescript, if it can't be imported by anything?

It gets stripped during compilation, so it can't be imported with import, and it's not a type so it can't be imported with import types.

**Comment by MartinJohns** [comment]
`declare` is used to describe values **that exist at runtime already**. TypeScript is not responsible to provide those values at runtime, you are. That's the entire point of `declare`. If then that value does not actually exist at runtime you end up with an error or course.

**Comment by paulcdejean** [comment]
Yes I am well aware of that.

Declare is working fine. What's not working fine is trying to encapsulate it into a seperate file.

**Comment by paulcdejean** [comment]
It's unfortunately pretty tricky to give a "real world" example that involves declare, but if someone can provide an example that uses declare, I can easily change it into an example that shows that `export declare const` is not working.

**Comment by MartinJohns** [comment]
I can't really say more than that this is working as intended and that you don't seem to understand the purpose of `declare`.

You're providing type information for a module `stuff.js`, but then don't actually have such a module at runtime.

**Comment by paulcdejean** [comment]
Since apparently I don't understand the purpose of declare.

Could you kindly provide a quick example of some code that uses `declare export const` that compiles and runs?

**Comment by paulcdejean** [comment]
In this bug report I'm making the bold claim that there is no example where code exports a declare const, and imports it in another file, and that code works.

So if I counter example can be provided then this can be closed.

**Comment by MartinJohns** [comment]
Have a `stuff.js` file with this content: `export const ThisReallyExists = "abc"`.

Your `.d.ts` file says "There will be a module that exports this `ThisReallyExists` variable", but then you don't actually have such a module at runtime. You're basically lying to the TypeScript compiler.

**Comment by paulcdejean** [comment]
`ThisReallyExists` is a global variable that exists outside the code. That's why we need to to use `declare`...

Lets look at the example in the documentation.


**The global variable foo contains the number of widgets present.**
```ts
/** The number of widgets present */
declare var foo: number;
console.log("Half the number of widgets is " + foo / 2);
```

That's the example from the documentation.

So is it possible to take this example, and make the first line and the second line in separate files, connected with an import?

**Comment by fatcerberus** [comment]
The trick is *not to import from `stuff.d.ts`* but just to make sure it's part of your compilation.  Also get rid of the `export` because that tells TS it's a module that needs to be imported at runtime.

**Comment by MartinJohns** [comment]
You're exporting / importing. Then you're dealing with modules, not with script files that contain global variables.

`declare` itself has nothing to do with global or not global. It's a way to declare that a value exists outside of your TypeScript code and will be/is provided at runtime (e.g. via a JavaScript file or module). In your example you declare that a module `stuff.js` will exist that exports a `ThisReallyExists` value - then proceed to not have such a module at runtime.

If you want to deal with globals, then don't import/export anything. If your .d.ts has export statements and you want to declare a global variable you can do this:

```
declare global {
    interface Window {
        ThisReallyExists: string;
    }
}
```

But again, you should **not import** this. A "global" variable is not to be imported. And again, also here, the value **should already exist** at runtime. You're telling TypeScript "this value will exist", but nothing in your code makes sure it actually **does exist**.

**Comment by paulcdejean** [comment]
> The trick is _not to import from `stuff.d.ts`_ but just to make sure it's part of your compilation.

@fatcerberus interesting. How do you include something in your compilation without importing it?

Of course one way is to have everything in the same file, maybe there's some other way I don't know about though.

**Comment by fatcerberus** [comment]
> How do you include something in your compilation without importing it?

`.d.ts` are picked up from your source directory(/ies) the same as `.ts` files.

**Comment by paulcdejean** [comment]
> Any file with no imports or exports is treated as global script.

Ohhhh. This was the missing piece...

I still think a `import global` would be useful similar to `import type` so that you wouldn't have to have your global declared across your entire codebase...
