### ISSUE TITLE
typescript module not found error while running "npx shadcn-ui@latest init"

### ISSUE THREAD

**Issue by bloodgroup-cplusplus** [microsoft/TypeScript#54847]
while initializing shadcn-ui using the command "npx shadcn-ui@latest init" in nextjs using typescript an error is generated
which says
cons err= new Error(message);
Error: cannot find module '@ts-morph/common'

Installed ts-morph using yarn ("yarn global add ts-morph) but the error still persists

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by sauravhathi** [comment]
Please use npm instead of yarn to install or initialize `shadcn-ui` ⚡🧑‍💻
