### ISSUE TITLE
Leak type check of function return value

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5484]
```ts
// parameter
var f: (p: boolean) => any,
	g: (p: number) => any = f, // error
	h: (p: void) => any = f; // error
```

```ts
// return value
var f: () => boolean,
	g: () => number = f, // error
	h: () => void = f; // should be error
```

**Comment by mhegazy** [comment]
This is the indented design. the rational here, is that you have a function contract that says it returns nothing (`void`), so the user has no was of depending on the return value, it should be safe to assign something that has a return value to this contract, since the output is ignored anyways. the opposite is not true though.

```ts
var n: () => number;
var v: () => void;

n = v; // Error, caller expects a number as a return type

v = n; // OK, caller does not expect a value anyways
```

**Comment by falsandtru** [comment]
I understand.

> NOTE: We might consider disallowing declaring variables of type Void as they serve no useful purpose. However, because Void is permitted as a type argument to a generic type or function it is not feasible to disallow Void properties or parameters.

https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#325-the-void-type

Thanks for your teaching.

**Comment by RyanCavanaugh** [comment]
Here's a concrete example of why you probably *wouldn't* want this behavior.

For example, `Array#push` returns a `number`, the new length of the array. Let's say you had a non-breaking `forEach` method:

```ts
function forEach<T>(array: T[], callback: (item: T) => void): void {
  /* for loop goes here */
}
```

Then you wrote:
```ts
let x = [1, 2, 3];
let y = [4, 5, 6];
forEach(y, n => x.push(n));
```

That last line involves the assignment of a function returning a `number` to a function returning a `void`. There's nothing wrong with this code *at all*. It would be really annoying if you were forced to write
```ts
// Explicitly throw away the return value...
forEach(y, n => void x.push(n));
```
