### ISSUE TITLE
tsconfig multiple extends doesn't work in build mode when using pnpm

### ISSUE THREAD

**Issue by tjx666** [microsoft/TypeScript#54858]
# Bug Report

### 🔎 Search Terms

tsconfig, extends, pnpm, symbolic, build mode

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.1.6 and next
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Reproduce Repositry](https://github.com/tjx666/tsconfig-extends-symboli)

### 💻 Code

```ts
console.log(123);
```

### 🙁 Actual behavior

If I use npm, everything works.
If I use pnpm(package manager use symbolic), tsc will work, but tsc -b will not work

error message:

```node
node_modules/@yutengjing/tsconfig-node/tsconfig.json:2:16 - error TS6053: File '@yutengjing/tsconfig-base/tsconfig.json' not found.

2     "extends": "@yutengjing/tsconfig-base/tsconfig.json",
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

### 🙂 Expected behavior

build mode also works

**Comment by gooddavvy** [comment]
I think only TypeScript supports `npm` and `yarn`. `pnpm` might have code that may "conflict".

**Comment by RyanCavanaugh** [comment]
> If I use npm, everything works.
> If I use pnpm

Sounds like a pnpm bug. We don't support running on monkeypatched runtimes.

**Comment by jakebailey** [comment]
I think there actually may be a bug here; pnpm doesn't do monkeypatching (that'd be yarn berry).

pnpm has an interesting layout here but one that should work if resolution is working properly:

![image](https://github.com/microsoft/TypeScript/assets/5341706/1b91fad4-61bc-42d9-bb90-fd09da9200cf)

And you can see that a regular build doesn't work but `-b` does not:

```
$ pnpm tsc                        
$ pnpm tsc -b                     
node_modules/@yutengjing/tsconfig-node/tsconfig.json:2:16 - error TS6053: File '@yutengjing/tsconfig-base/tsconfig.json' not found.

2     "extends": "@yutengjing/tsconfig-base/tsconfig.json",
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by tjx666** [comment]
@zkochan

**Comment by jakebailey** [comment]
So, it's possible that build mode is not using the right resolution mechanism, given IIRC it has to do its own processing of the graph?

**Comment by sheetalkamat** [comment]
This to me looks like issue with ParseConfigHost is not defined to extend ModuleResolutionHost. So `realPath` is missing which results in this.
