### ISSUE TITLE
generics on abstract classes where a superclass explicitly declares them are 'unknown' when inferred unless there is *some* implementation.

### ISSUE THREAD

**Issue by RobMayer** [microsoft/TypeScript#54857]
# Bug Report

### 🔎 Search Terms

infer, generics, class, superclass, extends, abstract classes

### 🕗 Version & Regression Information

tried on version 5.0.3, 5.1.5, and nightly.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about inference, classes, generics, and superclasses

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/PTAEBcAsEsGdQCYHsCm8B2TygO5IE4DWAUMSKLCuAK4AOoAZgRGtgIzECGARrOPpwDG2QQBtOseAEkAyoMgoAtpwDy6FAB4ASgD5QAbwC+xMRPgBRAB7gU6BCgRyFytZoByAGlC7QKa7YRpJyVVdQ03UAAfbz0jYnAAT1oUUGDlABUklFcNdL0AXlB03387IPkQnOh0BhR8GNAAfm9QAC5QdQA3OoBuUnIbPlAOROSi1jZQQrTOTOSc2QqXML58aoBzHR0e0HJVjfis8b4AJinUpdmsnKsbOwcZnP30da90akVuOq2d8j9k4QOUAACme6yiHQ+X3wAEpQOssKBqOhCJgcOh+mAoHBQAAqZBoXG4AgkMhgSg0ehMeqDbAnLi8fhCETiSSgRbOWZ4bSxYigfmgWhrTqcGwdJC0YGddpaOFxYymNm3AIPS7pbmeBp+O6BdkzdVIcIQnxxUYpfVZA25ApFEo68qcq3VWr1HzNLRtDoobr4PqHMbpVgAZnOFuSVo5IStYJ+u3J-AOZuO4AALKG1Zbucr7o41dywW8od9tnGQWCIe9PnUYcQgA)

### 💻 Code

```ts
// this does not work

// setup for test 1
abstract class ISchemaOne<R> {}
class ExtendedSchemaOne<N, R> extends ISchemaOne<N | R> {}
type SchemaTypeOne<T> = T extends ISchemaOne<infer R> ? R : never;

// test 1
type Test1 = SchemaTypeOne<ISchemaOne<string>>; // string
type Test2 = SchemaTypeOne<ExtendedSchemaOne<string, number>>; // expected (string | number) got unknown

// this *does* work

// setup for test 2
abstract class ISchemaTwo<R> {
    private nop(v: R) {}
}
class ExtendedSchemaTwo<N, R> extends ISchemaTwo<N | R> {}
type SchemaTypeTwo<T> = T extends ISchemaTwo<infer R> ? R : never;

type Test3 = SchemaTypeTwo<ISchemaTwo<string>>; // string
type Test4 = SchemaTypeTwo<ExtendedSchemaTwo<string, number>>; // (string | number)
```

### 🙁 Actual behavior

when there is no method or property on an abstract classes that uses the generic, even though the generic is explicitly defined by the superclass, an infer will return unknown rather than the expected type.

### 🙂 Expected behavior

an explicitly declared generic should not be unknown when inferred by another type.

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--

> Remember: You should *never* have unused type parameters!

**Comment by RobMayer** [comment]
ah-hah fair enough.
Sorry for taking up the time.

**Comment by fatcerberus** [comment]
@RobMayer I like to explain it like this: generic inference is structural, so `infer`ring an unused type argument is like asking TS to solve for `x * 0 = 0` - not only is *any* `x` is a valid solution but you can’t possibly recover the original `x` from only the `0` you got as output.
