### ISSUE TITLE
Unexpected "Object is possibly 'undefined'." error with a nullable key

### ISSUE THREAD

**Issue by alex996** [microsoft/TypeScript#54854]
# Bug Report

### 🔎 Search Terms

Object is possibly 'undefined' / undefined key / nullable key

### 🕗 Version & Regression Information

- This is the behavior in every major version I tried, from 3 to 5, and I reviewed the FAQ for entries matching "undefined", "object", "record", and "property".

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230701#code/MYewdgzgLgBAZiEATAXDASgU1AJyQHmhwEswBzAGhiNLIG0BdGAHxgFcwlM5TMkA+GAF4YAbwBEcHG2JQI4tHXEBDAA6qANpnEMAvgG4AUIdCRYAa0wBPCMJhKAbpjKYoygEZb5VcQFtMylDiPkjKxDhWweyc3LxIDEam0DA4ypwgvgDS1naWNnQAsoEAFgB0cBqIOAAURVBlqem+1QCUMABUMHkQpVrk9S0JxsRwMNWNSBnZVm2ihjALMCNjCMh0E1PWDLPzi3urSOtpk1lbpapsEMXV4gDuxYGYTjjiLbsLujCYGhCYYu97eCIQ4bU5WJgiJT3R7PHRGPa6Qy6IA) (Nightly)

### 💻 Code

```ts
const food: Record<string, string[] | undefined> = {"fruits": ["apple"]};

const keys = ["vegetables", "meat", "dairy", undefined];
const randomKey = keys[Math.floor(Math.random() * keys.length)];

if (randomKey) {
    if (food[randomKey]) {
        food[randomKey].push("whatever")
    } else {
        food[randomKey] = ["whatever"];
    }
}
```

### 🙁 Actual behavior

It fails to compile with an error: `Object is possibly 'undefined'.(2532)`.

It should compile because:
1. We check that `randomKey` is truthy (I tried `if (randomKey !== undefined) {` but got the same error)
2. We check that `food[randomKey]` is truthy (I tried `if (food[randomKey] !== undefined) {` but got the same error)
3. The resulting JavaScript code executes without a runtime error.

### 🙂 Expected behavior

It should compile without errors.

**Comment by MartinJohns** [comment]
Duplicate of #10530. Type narrowing does not occur for indexed access forms `e[k]` where `k` is not a literal. Just store it in a local `const` variable.

**Comment by alex996** [comment]
Can you please elaborate on 

> Just store it in a local `const` variable.

The key is in a `const` already. I tried this but as expected got the same error:

```ts
if (randomKey) {
    const arr = food[randomKey];
    if (arr) {
        food[randomKey].push("whatever")
    } else {
        food[randomKey] = ["whatever"];
    }
}
```

P.S. Apologies for the duplicate, I could not find it. I suspected it was a long-standing issue.

**Comment by alex996** [comment]
Apologies for the duplicate. I thought it was going to be a long-standing issue.

The fix as suggested (and the [[playground]):](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEATAXDASgU1AJyQHmhwEswBzAGhiNLIG0BdGAHxgFcwlM5TMkA+GAF4YAbwBEcHG2JQI4tHXEBDAA6qANpnEMAvgG4AUIdCRYAa0wBPCMJhKAbpjKYoygEZb5VcQFtMylDiPkjKxDhWweyc3LxIDEam0DA4ypwgvgDS1naWNnQAsoEAFgB0cBqIOAAURVBlqem+1QCUMABUMHkQpVrk9S0JxsRwMNWNSBnZVm2ihjALMEmwyjg4dgjIdBNT1kOLMCNjqziz8weLJ6WqbBDF1eIA7sWBmE444i3nC7owmBoQTBib4XTZIbZpSZZPZ2JTPV7vHRGA66Qy6IA)

```ts
if (randomKey) {
    const arr = food[randomKey];
    if (arr) {
        arr.push("whatever")
    } else {
        food[randomKey] = ["whatever"];
    }
}
```
