### ISSUE TITLE
Infer the jsx property type

### ISSUE THREAD

**Issue by NWYLZW** [microsoft/TypeScript#54851]
# Bug Report

### 🔎 Search Terms

jsx, infer property

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSX

### ⏯ Playground Link

```tsx
import React from 'react'

declare function A(props: {
  children:
    | React.ReactElement<{ test: 'aaaa' | 'bbbb' }>
}): React.ReactElement

declare function B<P extends Record<string, any>>(props: ...
```

[Playground Link](https://www.typescriptlang.org/play?ts=5.1.3#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSATJNAGxSLkwFcA7DYCFuAQQAowcYAM4AuOAG9ScOGgAWwGhSIsRU6XAA+iYjAB0ydDACiNJCCQsYAHnFwYSITDH4UrlPk0EARj68eAvgB8pP4AlGIGGPo6JmYWMORUtPRIjKzsnHAAQlYACnBIAB72LBRC2mjQFFaOUMAsAOYANHAoLACegYH8gqJwueHahtGGseaWecGklSyOcADCcAC8cFbcwdJWWXYOMEviLvj+cAD0G6cncAB6APxq4lm8kuo7js5u7monl7dqYf6kKwndakIA)

### 💻 Code

```ts
import React from 'react'

declare function A(props: {
  children:
    | React.ReactElement<{ test: 'aaaa' | 'bbbb' }>
}): React.ReactElement

declare function B<P extends Record<string, any>>(props: P): React.ReactElement<P>

const C = <A>
  <B test={'a'} />
  // ^? (property) test: string
  {B({
    test: 'aaaa'
  // ^? (property) test: 'aaaa'
  })}
</A>
```

### 🙁 Actual behavior

Infer test property is `string` type in JSX.

### 🙂 Expected behavior

Infer test property is `'aaaa'` type in JSX.

**Comment by Andarist** [comment]
Type-checking this won't work without something like https://github.com/microsoft/TypeScript/pull/29818 .

The contextual types here could maybe be improved to aid autocompletions and stuff like that, but it likely wouldn't solve your underlying problem, see [this playground](https://www.typescriptlang.org/play?ts=5.1.3#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocgEyTQBsUi5MBXAOw2AjbgEEAKMDjABnAFxwA3uThw0AC2B0qRNhOToYAOg0YAonSQgkbGAB5JcGEhEwJ+FI5T44AHwIAjLx5cBfAHwUvgCU6sTaujAGRiYwFNS0DEysHDBcPABCZgAKcEgAHtZsVCKItNBUZrZQwGwA5gA0cChsAJ7+-vwycEIQohLZ5KFlmjrh0camOYGUaNy2cADCcAC8cF2yZrz+3ZsZVjYwK5IOLiilc2y2vnAA9Dubt9tDFEA)

**Comment by NWYLZW** [comment]
Type-checking look like works. In fact, I need provide correct keywords hints when typing 'a', such as:
<img width="661" alt="image" src="https://github.com/microsoft/TypeScript/assets/51358815/8ce0d4c2-3710-46b6-9716-1099df0b819a">
When using function not JSX, call a function which is return `React.ReactElement` type. It provide the correct hints.

**Comment by NWYLZW** [comment]
The example is very easy. Actually, my case is use a function and infer the function arguments type.
<img width="689" alt="image" src="https://github.com/microsoft/TypeScript/assets/51358815/8e92cd70-8e06-4466-b884-f9bfc667865c">
<img width="664" alt="image" src="https://github.com/microsoft/TypeScript/assets/51358815/de06a484-4941-41ae-b24e-35cc278dc5fd">
