### ISSUE TITLE
Report unused imported modules

### ISSUE THREAD

**Issue by manekinekko** [Microsoft/TypeScript#5486]
Just a feature request. Is it possible to add support for unused imported modules and the ability to automatically remove any unused module?

![image](https://cloud.githubusercontent.com/assets/1699357/10870903/dec6b736-80d7-11e5-89f1-9f432b4d46d5.png)

Thanks.

**Comment by kitsonk** [comment]
This is typically a job of the linter and currently [tslint](https://github.com/palantir/tslint) supports the `no-unused-variable` flag.

**Comment by mhegazy** [comment]
as @kitsonk a lint rule should address this. We should revisit this when we have definite assignment analysis infrastructure in place.

**Comment by ryanmcnamara** [comment]
For posterity it seems that the `--no-unused-locals` flag addresses this
