### ISSUE TITLE
Class Type predicates don't keep narrowed generic unless it's directly used for a type.

### ISSUE THREAD

**Issue by tech-meppem** [microsoft/TypeScript#54865]
# Bug Report

### 🔎 Search Terms

predicate this type narrow class guard

### 🕗 Version & Regression Information

- This changed between versions 4.8 and 5.0

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/MYGwhgzhAEBiD28A8BBaBTAHgF3QOwBMYAjREdMPaAXmlPnMoD5oBvAKGi4AcBXYkAEtg0AJIQAamCEEAFAEpoALmjYAFoJia4iJNgBOvdE05cOXC9H3psvfVQNGA3KegBfV3wHDoUkEYVlaDQsXEIYR3RoAH5oCANBPABzILxeAFtidH02VwtrW3toACI1dBAQeGgAdXh9EAJi6EhmvABPFwsPD3ZQSBgAITB9VAwcfCI6MgoqWnpGPBZzHn4hEXE-QTlFFXVtbSGRyJMLZcsCuwdDdE6uDwsvNd9pAJ3gsbDJyJi4hOTUjJZHJnfI2S4lMoVKq1eqNZowSgdVz3LgAelRdF42GaBAIiRSiWa0AAbi8ouowNjeBB0DA0OkwABrWnQQTYgDudUZnlWPlJ-nQKjQtAAZtIafDWkien0oNAhgAvUahCYkaaUGhTBgzJY87zrSTSLaBXYaLSDMBK46uEFcC5FSK3dx6p5+V5BELjcKqa4-eL6fEAzLZXKWO1goqlcqVGp1BpNFqIp0o6DozHYsC4wOEsAksmqNSU6DUln0pkstnQTn6bkPXkiAAqtOwCiFobD9qoUahVbjcMT7WR7Bl8Dw8VUzYAjJq8Oh2Tp4AoXIIRbJcPFJwA6DZG7aKM5p9fYacQNTwXgNOhRBDIY7QMrWAA06dZ2AA5DAb0h5jqncBR+O1gQBe2K0EeW5uugS7DuwvQAdiR4AEwznO8rDNBK5rs2iHboaMgKPuriHthrIWkc1wnFw-5jtiQEgZqSGbpB0EjjRE7xAAzCh86Khhq5HhxuGbHu7aphiAmkWhVoUa41GAbS9Fgc2gnMfILgeEAA)

### 💻 Code

```ts
class Foo<A extends boolean = boolean> {
   public IsValid() : this is Foo<true>
   {
      return true;
   }
   public Value() : A extends true ? string : number {
      return "hello World" as any;
   }
}

class Bar<A extends boolean = boolean> {
   public IsValid() : this is Bar<true>
   {
      return true;
   }
   public Value() : A extends true ? string : number {
      return "hello World" as any;
   }
   // but adding in a value that uses A makes it work
   public value: A = false as any;
}

class Baz<A extends boolean = boolean> {
   public IsValid() : this is Baz<true>
   {
      return true;
   }
   public Value() : A extends true ? string : number {
      return "hello World" as any;
   }
   // but adding in a value that uses A makes it work
   public Test(): A {
      return "hello world" as any
   }
}

const test1 = new Foo();
if(test1.IsValid()) {
   // test1 should be Foo<true> here, but it's Foo<boolean>;
   const result = test1.Value();
}

const test2 = new Bar();
if(test2.IsValid()) {
   // test2 is Bar<true>
   const result = test2.Value();
}

const test3 = new Baz();
if(test3.IsValid()) {
   // test3 is Baz<true>
   const result = test3.Value();
}
```

### 🙁 Actual behavior

The narrowed type from the type predicate is not kept for class Foo.

### 🙂 Expected behavior

The narrowed type would persist for the whole if block

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--

> Remember: You should *never* have unused type parameters!

**Comment by tech-meppem** [comment]
> https://github.com/microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--
> 
> > Remember: You should _never_ have unused type parameters!


I wouldn't classify it as unused though, because it is part of a function return response:
```ts
public Value() : A extends true ? string : number
```
Just not directly, but it is still used. I sort of get why that couldn't be inferred though.
I guess it might be worth updating the FAQ just saying that "Conditional Types" don't classify as the type being used, so it doesn't work.


Also after testing, it works if you have a private variable in the class:
```ts
private value: A
```
which wouldn't be part of the public 'type', but that means it narrows correctly.

**Comment by RyanCavanaugh** [comment]
What we really mean, but which is *way* too technical for a FAQ, is that a type parameter should appear in at least one inference position, and the check clause of a conditional type is not an inference position (why this is the case is left as an exercise to the reader). `Foo<boolean>` is a valid supertype of `Foo<true>` so I don't see a defect here.
