### ISSUE TITLE
Missing `toggle` and `beforetoggle` popover events in 5.2.0-beta

### ISSUE THREAD

**Issue by jpzwarte** [microsoft/TypeScript#54864]
The PR https://github.com/microsoft/TypeScript/issues/54280 is missing definitions for `beforetoggle` (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforetoggle_event).

Also, the existing `toggle` event (from `<detail>`) is typed as `Event`, while `toggle` from `[popover]` is typed as `ToggleEvent`. (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/toggle_event)

cc @sandersn

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator#why-is-my-fancy-api-still-not-available-here

> Why is my fancy API still not available here?  
> A feature needs to be supported by two or more major browser engines to be included here, to make sure there is a good consensus among vendors: Gecko (Firefox), Blink (Chrome/Edge), and WebKit (Safari).

**Comment by jpzwarte** [comment]
@MartinJohns the rest of the `popover` API was added in 5.2.0-beta, just not these events.

**Comment by MartinJohns** [comment]
> the rest of the `popover` API was added in 5.2.0-beta, just not these events.

That sounds like an unfortunate mistake.

**Comment by jpzwarte** [comment]
> That sounds like an unfortunate mistake.

I doubt that:
- It is shipping in Chrome 114
- It will ship in Safari 17
- It is under active development in Firefox

**Comment by sandersn** [comment]
These types come from `@mdn/browser-compat-data` originally. I'll go see what I can find out about popover there.

**Comment by sandersn** [comment]
1. The [PR that adds popover to browser-compat-data](https://github.com/mdn/browser-compat-data/pull/19876/files) includes [beforetoggle_event](https://github.com/mdn/browser-compat-data/pull/19876/files#diff-29cbac2fd863800dc8e1a564aa1774fe06e85bbac11da67fb1355ebf411874e2L406) on HTMLElement along with hidePopover, showPopover, togglePopover and toggle_event. The non-events make it into the DOM types. It's been a while since I looked at the generating code, but maybe it's treating events differently than properties for some reason. @saschanaz can you think of a reason? I know you've worked with the code way more than I have.
2. I don't understand the second problem you mention. Isn't it correct for popover's [toggle] to be typed as ToggleEvent? Or is the problem that it's missing from HTMLElement?

**Comment by saschanaz** [comment]
"preview" is not counted as an actual support. It seems someone forgot to update it with "17"`. https://github.com/mdn/browser-compat-data/blob/44464ab1b3c0ce3bf58d275fe6d7f6ef0413bd3f/api/HTMLElement.json#L384-L425

**Comment by sandersn** [comment]
Thanks. That was the missing piece in my understanding--I assumed that truthy=supported.

**Comment by jpzwarte** [comment]
> * I don't understand the second problem you mention. Isn't it correct for popover's [toggle] to be typed as ToggleEvent? Or is the problem that it's missing from HTMLElement?

There are 2 `toggle` events:
1. `toggle` from `<detail>`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/toggle_event
2. `toggle` from `[popover]`: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/toggle_event

They are typed differently. In 5.2.0-beta there is only the first one, and that is typed as `Event`. If you can add the second one and have both typed correctly, then great! Just wanted to highlight the different types.

**Comment by saschanaz** [comment]
There is a way to fix such kind of issue, but using that will make HTMLDetailsElement not compatible with HTMLElement. 🤔

**Comment by sandersn** [comment]
I believe Orta attempted to make HTMLElement generic over some properties and failed because of backward compatibility breaks. And I think HTMLDetailsElement should remain assignable to HTMLElement. So we might be stuck with worse typing of HTMLDetailsElement.toggle.

**Comment by RyanCavanaugh** [comment]
Is there a bug here?

**Comment by sandersn** [comment]
1. Yes, but it's external -- https://github.com/mdn/browser-compat-data/issues/20298
2. Yes, but it's a Design Limitation -- there's no good way to allow subtypes of HTMLElement to have a different type of event for the same event name (without breaking existing code).

**Comment by gsong** [comment]
It seems this is still a problem? TS complains about incompatibility between `Event` and `ToggleEvent`.

```
  const ref = useRef<HTMLDivElement>(null);
  const [isOpen, setIsOpen] = useState<boolean>(false);

  useEffect(() => {
    const popover = ref.current;

    if (popover) {
      const handleBeforeToggle = (event: ToggleEvent) => {
        if (event.newState === "open") {
          setIsOpen(true);
        } else {
          setIsOpen(false);
        }
      };

      popover.addEventListener("beforetoggle", handleBeforeToggle);

      return () => {
        popover.removeEventListener("beforetoggle", handleBeforeToggle);
      };
    }
  }, []);
```

**Comment by gsong** [comment]
It's also worth nothing that according to <https://github.com/microsoft/TypeScript/issues/54864>:

> It is also the event object for the HTMLDetailsElement [toggle](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/toggle_event) event, which fires when a <details> element is toggled between open and closed.

**Comment by victorbueno** [comment]
I had to cast from Event to ToggleEvent inside the event listener. 

This gives the message: `No overload matches this call`

```ts
popover.addEventListener('beforetoggle', (event: ToggleEvent) => {});
```

This "workaround" makes it work:

```ts
popover.addEventListener('beforetoggle', (event: Event) => {
    const toggleEvent = event as ToggleEvent;
    console.log(toggleEvent.newState);
});
```
