### ISSUE TITLE
wrong type in callback when class extends Promise

### ISSUE THREAD

**Issue by sigmaSd** [microsoft/TypeScript#54867]
```ts
class A extends Promise<number> {
}
async function a(): Promise<A> {
  return new A((resolve) => resolve(4));
}
a().then((b) => {
  // no type error here
  const c: A = b; // typescript thinks c is A but its a number
  console.log(typeof c); // number
});
```

https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0FMAeAXBA7AJjACgJwHsBbASwgQB50BXIgIwTwD5oBvAKAF93IBPdYNABm1AShIF00MAAoAlAC5o+YmUqwWHaNDwIU1PFPQIA7nBkzdEAiABuCOdAC8LKzfsyALHLkBuLuw88gB0KAAWGBZ0ji5s7NrAkhAo0MBK8E7QdL7QAPS50Ci8AA4IEMB4JMUp4SToANYwgmRwWdQpJCgwYNA09IzxqUk2CMEgBADmMkWlBEKpflyLQA

**Comment by jcalz** [comment]
This issue was not properly filed according to the instructions; I'd suggest you go back and fix it, but I don't know if you can remove the "Duplicate" tag yourself.

Although, this looks a lot like #47593 to me, so maybe "Duplicate" can stay?  🤷‍♂️
