### ISSUE TITLE
Provide a command-line `tsc` flag for specifying `type` in `package.json`

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/TypeScript#54876]
To quickly check if some package properly provides its types under node16 from ESM it would be convenient if you could specify "node16 & ESM" solely on the command-line, but currently that does not appear to be possible since you apparently have to put `"type": "module"` in the `package.json` file.

I also tried using `--moduleDetection force` but that didn't have the same effect as `"type": "module"` in `package.json` either.

**Comment by fatcerberus** [comment]
This is a Node.js runtime requirement, so any option to override it would essentially be lying to TS about the runtime environment, leading to runtime errors.  It would do more harm than good, IMO.

**Comment by not-my-profile** [comment]
Fair enough ... I still think the [moduleDetection](https://www.typescriptlang.org/tsconfig#moduleDetection) documentation should be clarified ... I guess it's only about the detection of other modules but not the detection of the current module?

**Comment by fatcerberus** [comment]
`moduleDetection` is about detecting module vs. not-module.  All `moduleDetection: "force"` does it make TS detect files as modules (instead of old-style global scripts) even when they have no imports/exports.  What *kind* of module it is (ESM vs. CommonJS) is a separate concern.

**Comment by not-my-profile** [comment]
Closing this since debugging node16 resolutions is probably rather an edge case and probably warrants dedicated tooling like [@arethetypeswrong/cli](https://www.npmjs.com/package/@arethetypeswrong/cli).
