### ISSUE TITLE
Why after typeof x === "string" there is no narrowing to string, but instead T & string

### ISSUE THREAD

**Issue by tyt34** [microsoft/TypeScript#54877]
Using the function type example from this link - https://www.typescriptlang.org/docs/handbook/2/conditional-types.html

I don't understand why type narrowing does not occur in this case, and return typing does not work without using:
```
as NameOrId<T>;
```

How in this case it is possible to write the given example more competently?

Example:
```
interface IdLabel {
  id: number;
}

interface NameLabel {
  name: string;
}

type NameOrId<T extends number | string> = T extends string ? NameLabel : IdLabel;

const createLabel2 = <T extends number | string>(nameOrId: T): NameOrId<T> => {
  if (typeof nameOrId === "string") {
    const result = {
      // why in this case type nameOrId
      // is (parameter) nameOrId: T & string
      // instead of symple string ??
      name: nameOrId,
    } 
    return result;
  }
  return {
    id: 123,
  } as NameOrId<T>;
};
```

**Comment by tyt34** [comment]
I don’t understand where the label "Duplicate" came from. I didn’t put it.

**Comment by MartinJohns** [comment]
> I don’t understand where the label "Duplicate" came from. I didn’t put it.

You used the wrong issue template.

**Comment by tyt34** [comment]
> > I don’t understand where the label "Duplicate" came from. I didn’t put it.
> 
> You used the wrong issue template.

How do it better?

**Comment by tyt34** [comment]
I understand, that there I dont find answer an asq Q on stackoverflow. Link: https://stackoverflow.com/questions/76618641/why-after-typeof-x-string-there-is-no-narrowing-to-string-but-instead-t/76618962#76618962

**Comment by tyt34** [comment]
This is how it should have been written from the very beginning so that this question does not arise
```
type NameOrId<T extends number | string> = T extends string ? NameLabel : IdLabel;

const createLabel2 = (nameOrId: number | string): NameOrId<number | string> => {
  if (typeof nameOrId === "string") {
    const result = {
      name: nameOrId,
    };
    return result;
  }
  return {
    id: 123,
  };
};
```
