### ISSUE TITLE
Module Resolution: Importing Type Only Generates JS 

### ISSUE THREAD

**Issue by ac566** [microsoft/TypeScript#54880]
### Demo Repo

https://github.com/ac566/typescript-import-type-bug

### Which of the following problems are you reporting?

The module specifier resolves at runtime, but not at build time

### Demonstrate the defect described above with a code sample.

// When importing only the type, the entire other file is included in the output even though it is not included in the config and is not used anywhere
import type { MyType } from "./lib";
const x: MyType = { x: 99 };
x.x = 5;

### Run `tsc --showConfig` and paste its output here

{
    "compilerOptions": {
        "moduleResolution": "node10",
        "strict": true,
        "module": "commonjs",
        "outDir": "./dist",
        "baseUrl": "./"
    },
    "files": [
        "./src/main.ts"
    ],
    "exclude": [
        "./dist"
    ]
}

### Run `tsc --traceResolution` and paste its output here

======== Resolving module './lib' from 'C:/Users/ac566/module-error/src/main.ts'. ========
Explicitly specified module resolution kind: 'Node10'.
Loading module as file / folder, candidate module location 'C:/Users/ac566/module-error/src/lib', target file types: TypeScript, Declaration.
File 'C:/Users/ac566/module-error/src/lib.ts' exists - use it as a name resolution result.       
======== Module name './lib' was successfully resolved to 'C:/Users/ac566/module-error/src/lib.ts'. ========
======== Resolving module '@typescript/lib-es5' from 'C:/Users/ac566/module-error/__lib_node_modules_lookup_lib.es5.d.ts__.ts'. ========
Explicitly specified module resolution kind: 'Node10'.
Loading module '@typescript/lib-es5' from 'node_modules' folder, target file types: TypeScript, Declaration.
Directory 'C:/Users/ac566/module-error/node_modules/@types' does not exist, skipping all lookups 
in it.
Scoped package detected, looking in 'typescript__lib-es5'
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-es5'
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-es5'
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-es5'
Loading module '@typescript/lib-es5' from 'node_modules' folder, target file types: JavaScript.  
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
======== Module name '@typescript/lib-es5' was not resolved. ========
======== Resolving module '@typescript/lib-decorators' from 'C:/Users/ac566/module-error/__lib_node_modules_lookup_lib.decorators.d.ts__.ts'. ========
Explicitly specified module resolution kind: 'Node10'.
Loading module '@typescript/lib-decorators' from 'node_modules' folder, target file types: TypeScript, Declaration.
Directory 'C:/Users/ac566/module-error/node_modules/@types' does not exist, skipping all lookups 
in it.
Scoped package detected, looking in 'typescript__lib-decorators'
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-decorators'
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-decorators'
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-decorators'
Loading module '@typescript/lib-decorators' from 'node_modules' folder, target file types: JavaScript.
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
======== Module name '@typescript/lib-decorators' was not resolved. ========
======== Resolving module '@typescript/lib-decorators/legacy' from 'C:/Users/ac566/module-error/__lib_node_modules_lookup_lib.decorators.legacy.d.ts__.ts'. ========
Explicitly specified module resolution kind: 'Node10'.
Loading module '@typescript/lib-decorators/legacy' from 'node_modules' folder, target file types: TypeScript, Declaration.
Directory 'C:/Users/ac566/module-error/node_modules/@types' does not exist, skipping all lookups 
in it.
Scoped package detected, looking in 'typescript__lib-decorators/legacy'
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-decorators/legacy'
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-decorators/legacy'
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-decorators/legacy'
Loading module '@typescript/lib-decorators/legacy' from 'node_modules' folder, target file types: JavaScript.
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
======== Module name '@typescript/lib-decorators/legacy' was not resolved. ========
======== Resolving module '@typescript/lib-dom' from 'C:/Users/ac566/module-error/__lib_node_modules_lookup_lib.dom.d.ts__.ts'. ========
Explicitly specified module resolution kind: 'Node10'.
Loading module '@typescript/lib-dom' from 'node_modules' folder, target file types: TypeScript, Declaration.
Directory 'C:/Users/ac566/module-error/node_modules/@types' does not exist, skipping all lookups 
in it.
Scoped package detected, looking in 'typescript__lib-dom'
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-dom'
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-dom'
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-dom'
Loading module '@typescript/lib-dom' from 'node_modules' folder, target file types: JavaScript.  
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
======== Module name '@typescript/lib-dom' was not resolved. ========
======== Resolving module '@typescript/lib-webworker/importscripts' from 'C:/Users/ac566/module-error/__lib_node_modules_lookup_lib.webworker.importscripts.d.ts__.ts'. ========
Explicitly specified module resolution kind: 'Node10'.
Loading module '@typescript/lib-webworker/importscripts' from 'node_modules' folder, target file 
types: TypeScript, Declaration.
Directory 'C:/Users/ac566/module-error/node_modules/@types' does not exist, skipping all lookups 
in it.
Scoped package detected, looking in 'typescript__lib-webworker/importscripts'
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-webworker/importscripts'
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-webworker/importscripts'
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-webworker/importscripts'
Loading module '@typescript/lib-webworker/importscripts' from 'node_modules' folder, target file 
types: JavaScript.
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
======== Module name '@typescript/lib-webworker/importscripts' was not resolved. ========        
======== Resolving module '@typescript/lib-scripthost' from 'C:/Users/ac566/module-error/__lib_node_modules_lookup_lib.scripthost.d.ts__.ts'. ========
Explicitly specified module resolution kind: 'Node10'.
Loading module '@typescript/lib-scripthost' from 'node_modules' folder, target file types: TypeScript, Declaration.
Directory 'C:/Users/ac566/module-error/node_modules/@types' does not exist, skipping all lookups 
in it.
Scoped package detected, looking in 'typescript__lib-scripthost'
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-scripthost'
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-scripthost'
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'typescript__lib-scripthost'
Loading module '@typescript/lib-scripthost' from 'node_modules' folder, target file types: JavaScript.
Directory 'C:/Users/ac566/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
======== Module name '@typescript/lib-scripthost' was not resolved. ========

### Paste the `package.json` of the *importing* module, if it exists

{
  "name": "module-error",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "tsc -p tsconfig.json"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "typescript": "^5.1.6"
  }
}

### Paste the `package.json` of the *target* module, if it exists

{
  "name": "module-error",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "tsc -p tsconfig.json"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "typescript": "^5.1.6"
  }
}

### Any other comments can go here

Description:
* Actual: When importing only the type from another file, the entire file is included in the output
* Expected: Only files included directly in the tsconfig, or imported as values are included in the output

* Workaround: Setting "noResolve" to true, emits the correct output, but gives error during generation
* Note: Empty JS module gets emitted even when there are no values present in the exporting module

**Comment by guillaumebrunerie** [comment]
Did you try to use `--verbatimModuleSyntax`?

**Comment by ac566** [comment]
> Did you try to use `--verbatimModuleSyntax`?

Yes. It still outputs both files.

My understanding from reading the docs is that that setting and the ones it replaces only drop the imports themselves from the output, but doesn't stop the files from being compiled if they are referenced.

**Comment by ac566** [comment]
Sorry I accidently closed it

**Comment by RyanCavanaugh** [comment]
The behavior of TS is to produce all JS files which have TS input files. The used-for-types vs not distinction you're making here does not exist.

**Comment by fatcerberus** [comment]
> The used-for-types vs not distinction you're making here does not exist.

Hmm, it does still feel bad that TS is pulling a file into emit *only* for the sake of an import which is marked upfront (via `import type`) as “do not emit”, particularly if the file would not otherwise be part of the compilation.

I guess the thing is that the imported file *does* still need to be type-checked itself, at which point JS emit can’t be prevented.  So maybe a more correct way to express this is to say that the concept of “file that only *contributes* types” doesn’t exist.  A file can certainly be *used* only for types in a way that affects emit; that’s what `import type` is.

**Comment by RyanCavanaugh** [comment]
I think there'd need to be some identifiable downside of emitting a file. If you actually need it (maybe it'd dynamically loaded through means not statically visible in your program), it's helpful. If you actually don't need it, but it exists... who cares?

**Comment by fatcerberus** [comment]
That's fair.  Anyone who cares about that kind of thing at all, e.g. optimizing package size, etc., is probably already post-processing with a bundler for tree-shaking, etc. anyway.

**Comment by ac566** [comment]
My only issue was that it changed how my build directory, which was unexpected. I was mostly surprised there was no way to only output "necessary" files, or some way to generate output for only the files specified.

In all fairness I was just trying the laziest way I could think to share types across my codebase, so I don't expect it to be a very sympathetic use-case.
