### ISSUE TITLE
Variable decorators

### ISSUE THREAD

**Issue by ismail-codar** [Microsoft/TypeScript#5488]
ClassDecorator, PropertyDecorator, MethodDecorator, ParameterDecorator supported in typescript. All of them aimed class structure.

However, the following notation will be very useful. More javascript like code but powered with decorators.(Currently raises decorators are not valid here exception) 

```javascript
@ComponentDecl
var obj = {
//some object definition
}

@Log
function MyMethod() {
	
}
```

**Comment by HerringtonDarkholme** [comment]
Why not just a function call? It is more flexible than decorator in TS.

**Comment by mhegazy** [comment]
There is a long discussion in the original decorator proposal about function declarations: https://github.com/Microsoft/TypeScript/issues/2249; one thing to note, what TypeScript has is an implementation to an existing  ECMAScript proposal, and we will not want to deviate from the proposal much specially in such an early stage.

And as @HerringtonDarkholme mentioned, using a function should achive what you want with a clearer semantics:

```ts
var obj = ComponentDecl()({
//some object definition
});

var MyMethod = Log()(function MyMethod() {

});
```
