### ISSUE TITLE
Object with dynamic key has the wrong type

### ISSUE THREAD

**Issue by godart-corentin** [microsoft/TypeScript#54889]
# Bug Report

### 🔎 Search Terms

- dynamic key
- key type fail

### 🕗 Version & Regression Information

- This is the behavior in every version I tried: 5.1.6 and nightly version

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBA5gUygFQE4ENIBt1XQIywQHl8ArBYWAXhgB5kYEAPKBMAEwhmlQEswcAHwAKAA6oQYhKigBPAFwxkAShjUhMAN4AoGDFRIArqjDa9+mAG0ABgBItEqTPkBfAPoAzVDYC6SgCJ8cDIQEwCAGgt9WwcnaVk5D3Y-QIALBCwsEEiLVwBuHQKdHVBIWDS+dXgkNEwIHDxCEnJKKBEAyoCVQp0Aej6DBAgjLCgFfsGy6BhKpV0ByxjmJV4BOH8eKH5BQsXXEsWWaSoEDkmYaYq+eYulyq9UVe31vcH7vnd2Z524N5gDkA)

### 💻 Code

```ts
const getTranslatableObject = <T extends string>(property: T) => {
  return {
    [`${property}_fr`]: "bonjour",
    [`${property}_en`]: "hello",
  };
};

const hi = getTranslatableObject("hi");
```

### 🙁 Actual behavior

The `hi` variable is typed like this:

```ts
const hi: {
    [x: string]: string;
}
```

### 🙂 Expected behavior

It should be typed like this:

```ts
const hi: {
    hi_fr: string;
    hi_en: string;
}
```

--- 

I also tried to use `as const` like this:

```ts
const getTranslatableObject = <T extends string>(property: T) => {
  const frProperty = `${property}_fr` as const;
  const enProperty = `${property}_en` as const;

  return {
    [frProperty]: "bonjour",
    [enProperty]: "hello",
  };
};
````

but it didn't work.

**Comment by godart-corentin** [comment]
Might be related to #42076

**Comment by jcalz** [comment]
Duplicate of #13948

**Comment by Andarist** [comment]
This is definitely related to https://github.com/microsoft/TypeScript/issues/13948 but this doesn't work because of one extra reason ([TS playground](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230705#code/MYewdgzgLgBA5gUygFQE4ENIBt1XQIywQHl8ArBYWAXhgB5kYEAPKBMAEwhmlQEswcAHwAKAA6oQYhKigBPAFwxkAShjUhMAN4AoGDFCRYYgIzqYAAwAkWiVJnyAvgH0AZqgsx03Q9ADcegbg0DAgSrr6+gDazkry0iCuMKYAukq8AnAB+o7mEZFRqUoARPjgZCAArqjFADSBjtkwqEjVYKEBjTpAA)):
```ts
const getTranslatableObject = <T extends string>(property: T) => {
  const p1 = `${property}_fr` as const;
  const o: {
    [_: typeof p1]: string; // An index signature parameter type cannot be a literal type or generic type. Consider using a mapped object type instead.(1337)
  } = {
    [p1]: "bonjour",
  };
  return o;
};
```

And since those index signatures can't be generic... you can't assign to the appropriate mapped type without casting because you'd end up with something like:
> Type '{ [x: string]: string; }' is not assignable to type '{ [K in "fr" | "en" as `${T}_${K}`]: string; }'.(2322)

**Comment by RyanCavanaugh** [comment]
> It should be typed like this:

This is wrong because it implies that if you called the function this way, *which is legal*:
```
getTranslatableObject<"hi" | "howdy">("hi")
```
then you'd get back an object with 4 properties. But you won't.

**Comment by godart-corentin** [comment]
Didn't even think of it. Thank you for the explanation!
