### ISSUE TITLE
Type assertion does not creates a type union anymore 

### ISSUE THREAD

**Issue by drtex0** [microsoft/TypeScript#54883]
# Bug Report

Since version 5.1.X I am facing this issue with type assertion. In version 5.0.X the type resolves with an Union of the original type & the assertion type. However in 5.1.X there is only the original type left 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.0.1 and 5.1.3
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type assertion
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=99&ts=5.1.3#code/JYWwDg9gTgLgBAbwAUgIZgGqoDYFcCmAznAL5wBmUEIcA5NhACaqEAWtA3AFBcwCeYfHAAiwAHb4qcOAF5EXaSFzYAXHAAUASlkA+OIRhRxAcy4keAYwhiDcYIVESpc9RABGAKzW4xAazEQAO5immruHnbEjpIQunAKcPyCEORw4bIycgBE4fgWMFlwAGRFaZ5wAISZcGLK2MWlAPKeeTAAdKwsjcGungA0cFlK2Fmalta2hqg25NAgWHhEsnAAPADC1lP5cPgAHjD4YozEufk66lZiW-BqG1dQqPnacQgJcGiYOASEF5sP+QN1AA3L74Aa+fB8bQyPSvaTwuzkdT2aJUYGgzTaOEI+EAelxcAAClRBLA+HRhrQ4IwIEsAvA9vZ4NZEgIhLQ7tcANoQvgpOCc-4wAC6tDa6gATABmKUATjGbxxIMWbWGWniOLxBLgyoIcAAtHpBY8YDzIfzjflhXYxHAACoAZTgAFY2gBGNoADUVCPxOtBtz+JrNfNSlpFxRE4hiNvtTtdAAYvTxNeZFSQFSQgA)

### 💻 Code

```ts
import { mapValues } from 'lodash';

type Dinero  = {
  mul: () => number
}

const isDinero = (obj: unknown): obj is Dinero => 
  typeof obj === "object" && obj !== null && Object.hasOwn(obj, "mul")

const transformValues = <Contract extends object>(contract : Contract)  => {
   mapValues(contract, (value, key) => {
      if(isDinero(value)) {
        //  value -> Contract[keyof Contract] in TS 5.1.X
        // value: Contract[keyof Contract] & Dinero in TS 5.0.X
        value.mul() 
        
      }

    })

}
```

### 🙁 Actual behavior

The type value is `Contract[keyof Contract`

### 🙂 Expected behavior

The type value to be at least `Contract[keyof Contract] & Dinero`

**Comment by fatcerberus** [comment]
1. `isDinero` is a *type predicate*, not a type assertion.  Type assertion is e.g. `as Foo`
2. The expected type is an *intersection*, not a union.

**Comment by thibault-lr** [comment]
Indeed. Sadly I can't 

> 1. `isDinero` is a _type predicate_, not a type assertion.  Type assertion is e.g. `as Foo`
> 2. The expected type is an _intersection_, not a union.

Indeed, I'm not allowed to update the post content however.

**Comment by RyanCavanaugh** [comment]
Adding a self-contained repro so this can be bisected...
```ts repro
type Dinero  = {
  mul: () => number
}
declare const isDinero: (obj: unknown) => obj is Dinero;
const transformValues = <Contract extends object>(contract : Contract)  => {
    let value: Contract[keyof Contract] = null as any;
    if(isDinero(value)) {
      value.mul() 
    }
}
```

**Comment by RyanCavanaugh** [comment]
The originating PR #53059 is being reverted in favor of #54845, so I think it's safe to call this a duplicate
