### ISSUE TITLE
Return type union with empty object is just empty object

### ISSUE THREAD

**Issue by TheBlue-1** [microsoft/TypeScript#54888]
# Bug Report

### 🔎 Search Terms

conditional return 
return type option missing 
only first return type 
empty object return 

### 🕗 Version & Regression Information

- This is the behavior in version 5.1.3 and nigtly 5.2.0-dev.20230705

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/LAKALgngDgpgBAUQB5QE4wM4YJYHsB2GAvAN7YYDCuuANsmpjgQFxioCuMAvqKJLHACCAYzB58AZTAwocInBKg4yuNnxR2YAPzNEKdFnEY4AHzjt8AExgAzNTEsBuUDxC8QMFLlRg4Ni6LicDAAbgCGNOxh0gCS6poAFBjSULoiYgRSMgCUCkqqNnAJAITJMgB0ahpguehg7Kj4ClzOIMp1DU0AjK2uoMIEyeZEoRFRsfFgCfjsNDRwYcZh+BDZjnAA9BvmAOTG-PDkcABEJFzHqoTSYZZwuIWnXKZwXcdAA)

### 💻 Code

```ts

type Expressions={isCoolExpression:true}

type ActionStep = {
    input?: Expressions | undefined;
}


export function evaluateInput(step: ActionStep) {
  if (!step.input) return {};
  return 1;
}

const u=evaluateInput(null as any); // u's type is "{}" instead of "{} | 1"
```

### 🙁 Actual behavior

If a function returns either an empty object or a number (could also be or a promise or anything) the return type will be just empty object instead of a union type. It is wrong because a number or promise doesnt equal to an empty object. A promise is much more than an empty object and it should be typed that way, a number is just totally different in usage and should therefore be typed with a union.

### 🙂 Expected behavior

The expected behaviour would be a return type as a union like "1 | {}" or "{} | Promise<unknown>"

**Comment by fatcerberus** [comment]
This is just normal subtype reduction.  Everything (except `null` & `undefined`) is a subtype of `{}`.

**Comment by fatcerberus** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/50171, among others.
Also see: https://www.typescriptlang.org/docs/handbook/type-inference.html#best-common-type

**Comment by TheBlue-1** [comment]
But it is a mistake to do the subtype reduction for infered return types, because it hides the actual returns.

**Comment by fatcerberus** [comment]
> But it is a mistake to do the subtype reduction for infered return types

The inferred return type here is no different in concept to the inferred type of the ternary expression in #50171.  It's inconvenient, but ultimately not considered a bug.

**Comment by guillaumebrunerie** [comment]
`{}` does not mean "empty object", it means anything with any properties you want, or in other words any value except `null` and `undefined`. In particular, every number is already assignable to the type `{}`, so even if it did return `1 | {}`, there would be no way to make use of this information.

**Comment by TheBlue-1** [comment]
closing since ts wont solve the problem... There should be a type saing its just an empty object or sth else and not a "base type" that just includes everything since its just wrong...

**Comment by guillaumebrunerie** [comment]
See #12936.
