### ISSUE TITLE
5.1.6 on Npm, but not in GitHub releases list (latest there is 5.1.5)

### ISSUE THREAD

**Issue by janpio** [microsoft/TypeScript#54881]
Something is off with the releases right now:

![image](https://github.com/microsoft/TypeScript/assets/183673/077a2966-125c-4bbc-94da-35cb4f529508)
vs.
![image](https://github.com/microsoft/TypeScript/assets/183673/a8188cd6-ec3f-430e-b783-626d7ff4c661)

via https://www.npmjs.com/package/typescript?activeTab=versions and https://github.com/microsoft/TypeScript/releases

**Comment by IllusionMH** [comment]
Basically duplicate of #51553

**Comment by jakebailey** [comment]
Posted now: https://github.com/microsoft/TypeScript/releases/tag/v5.1.6
