### ISSUE TITLE
Google feedback on TS 5.2 Beta

### ISSUE THREAD

**Issue by frigus02** [microsoft/TypeScript#54897]
This GitHub issue contains feedback on the TS 5.2 Beta release from the team that is responsible for keeping Google's internal software working with the latest version of TypeScript.

## Executive summary

*   We do not expect to have significant difficulty in upgrading Google to TS 5.2.
*   Some changes to our TypeScript code are required to make it compile with TS 5.2.
*   Detail sections below explain the changes to our code we expect to make to unblock the upgrade.

## Impact summary

Caveat: We're not quite done rolling out 5.1. These numbers are our best estimates.

Change description | Announced | Libraries affected
------------------ | --------: | -----------------:
lib/d.ts changes   | yes       | 0.004%
other changes      | yes       | 0.007%

The **Announced** column indicates whether we were able to connect the observed change with a section in the [TS 5.2 Beta announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2-beta/).

The following sections give more detailed explanations of the changes listed above.

We expect to fix our codebase mostly by adding `// @ts-ignore` to silence the errors and apply proper fixes over time.

### lib/d.ts Changes

We support the typing improvements. Generally it's clear what's changing and the
changes seems minimal this time. Examples:

-   Removal of `track` from `RTCStatsType`.
-   Removal of `contributingSources` from `RTCEncodedVideoFrameMetadata`.
-   Addition of `silent` to `Notification`.
-   Addition of `WebTransport`.

### other changes

We observed some new errors, that generally seem like improvements, such as:

```ts
interface Foo {
    prop?: Array<string>;
}

const PROP = 'prop';

const foo: Foo = { [`${PROP}`]: 'a, b' } as Foo;
//               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Conversion of type '{ prop: string; }' to type 'Foo' may be a mistake because neither type sufficiently overlaps with the other.
```

**Comment by DanielRosenwasser** [comment]
Thank you for providing this feedback! 🙂
