### ISSUE TITLE
Extending abstract class with optional parameters

### ISSUE THREAD

**Issue by pawelkondraciuk** [microsoft/TypeScript#54895]
# Bug Report

### 🔎 Search Terms

extend abstract method optional parameters

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about arguments

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAggiAwq9CA3gFAJkKiQzwIC2AphABYD2AJgBQBuwyArvQD8ALgRUAlgDsA5gEpREmQG5iAX2LEUaDAElaebZgT0AHhHqS2GbAYIlydRq049+9BdClyipB+SiMfFCSCK4CAHQQLACqAA6x9FA4aPQcsioO6uqa+Lr6uQBCxmYWVli4uT4ODMzs3LwCImKeMrJVfmQBEEEhYUKRMfGJyWCpbYKCCABEAKIAsgAKACoAmlMZ5FkasCySkBSiNpUAvAiS9ADuCHq2YJhpKjt7iCCHFdoIp+dXN4UPGsBwjVnP8QECnHV0kA)

### 💻 Code

```ts
abstract class AbClass {
    abstract method(value?: string): string;
}

class ImClassA extends AbClass {
    method(value: string) {
        return value.toUpperCase();
    }
}

class ImClassB extends AbClass {
    method(value?: string) {
        return value?.toUpperCase() ?? "EMPTY";
    }
}

const a: AbClass = new ImClassA();
const b: AbClass = new ImClassB();

a.method();
b.method();
```

### 🙁 Actual behavior

Code compiles successfully but throws runtime error

### 🙂 Expected behavior

Code should not compile, method parameters doesn't match (abstract string | undefined -> implemented string)

**Comment by Andarist** [comment]
Methods parameters are always compared bivariantly: https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant
