### ISSUE TITLE
Wrong static type checking when providing a string value to a function parameter that is not typed to receive string.

### ISSUE THREAD

**Issue by lillallol** [microsoft/TypeScript#54899]
# Bug Report

Wrong static type checking when providing a string value to a function parameter that is not typed to receive string.

### 🔎 Search Terms

string,function,parameter,static,type,checking,bug

### 🕗 Version & Regression Information

**This is the behavior in every version 4.*.* and 5.*.* version I tried in the playground + nightly**

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.3#code/MYewdgzgLgBFCm0YC4YAoCGAnA5hFMA3gFAxkzQgAOA8mACIZQYwD8q0WAlmDgDSlyAegBUIweREwAAgBNEwblShdwEslIDKUavgDuAC3hgYLHcwA2MEADMYAAwvGcUA-ZiymLAxnwAjeGMKRQwqKnhZADp1GCk5eBsMAFcLWABJMBseLigAT3URIXUnXlc2VDAkgFsArGIAXwBKGABeAD4YAAUsECquCHgAHhJyOHgAD1gOKG5eAVGMDHlOkGgAFS4qxGYqqgJKmvgsefIIEKoNregMXf3q2oaAbQBdDpbTCFywYHRm9qJ1Fh4FAklgTC8ANwNKHEBDQND2eyNKFwqBoABE6ORsO2aBmSXg2NRaAAjMigA)

### 💻 Code

```ts
const test : (args : {
    stopOnData ?: string,
    /**
     * @description
     * Stops when a total of `length` data has been scrapped.
     * @default Infinity
    */
    length ?: number
}) => Promise<{
    text : string,
    aadePostTimestamp : number,
    scrapTimestamp : number
}[]> = async () => {
    return [];
};

test(``);//BUG : does not lint error
test("");//BUG : does not lint error
test(true);//does lint error
test(1);//does lint error
```

**Comment by lillallol** [comment]
Renaming the property `length` to something different solves the issue. Is this the expected behavior in the first place?

**Comment by MartinJohns** [comment]
This is working as intended. Strings have a `length` property, resulting in a sufficient overlap with the type the function accepts.

**Comment by lillallol** [comment]
What about providing a function instead of a string?

**Comment by Josh-Cena** [comment]
A function also has a [`length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) property :)

**Comment by lillallol** [comment]
[Yes it does, but it lints error](https://www.typescriptlang.org/play?ts=5.1.3#code/MYewdgzgLgBFCm0YC4YAoCGAnA5hFMA3gFAxkzQgAOA8mACIZQYwD8q0WAlmDgDSlyAegBUIweREwAAgBNEwblShdwEslIDKUavgDuAC3hgYLHcwA2MEADMYAAwvGcUA-ZiymLAxnwAjeGMKRQwqKnhZADp1GCk5eBsMAFcLWABJMBseLigAT3URIXUnXlc2VDAkgFsArGIAXwBKGABeAD4YAAUsECquCHgAHhJyOHgAD1gOKG5eAVGMDHlOkGgAFS4qxGYqqgJKmvgsefIIEKoNregMXf3q2oaAbQBdDpbTCFywYHRm9qJ1Fh4FAklgTC8ANwNKHEBDQND2eyNKFwqBoABE6ORsO2aBmSXg2NRaAAjETcWg-h1CE0gA).

**Comment by RyanCavanaugh** [comment]
The rule that prevents assignability to all-optional types is basically a heuristic; from a purely theoretical POV all of these inputs "should" be accepted (but this is obviously undesirable in practice). The "weak type" rule effectively checks for properties on the object version of the type, so `string` gets `length`, etc, whereas the `.length` property of a function isn't directly surfaced since it only appears as part of being in the `Function` interface.
