### ISSUE TITLE
Release note typo

### ISSUE THREAD

**Issue by rimiti** [microsoft/TypeScript#54896]
Hello, 👋 

It's a not a bug, just a typo into latest [Release note](https://github.com/microsoft/TypeScript/releases/tag/v5.2-beta):

Right link of the latest RN is:
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-2-beta/

Not: 
- https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/

Have a nice day. ;)

**Comment by RyanCavanaugh** [comment]
Fixed, thanks
