### ISSUE TITLE
Computation of intersection of multiple objects

### ISSUE THREAD

**Issue by missannil** [microsoft/TypeScript#54903]
# Bug Report

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FAFwngDgpgBAhjAvDA3vAXDAziATgSwDsBzGAXwG5hRJYAjJVGOzQgVwFs6pdyqboMAMaM0cVp269K1cIIAmojMwD2KgDZQ4hPrNowAwio4Q2IKAElC53FihCQ+FYQA8AeQB8SgNoBrGEQwvlBgKgBmMG4AuphuflG6ArDmOACMjEYmZpbWPHYOTq4IAGTMHhQwwAD0VTApIOmIXkzi2HhEpBUs7Fw8ZDAwACoAFnAgAORYMADuoyAwFjBQAB7QDlDyeoL1AEwZxqbmVjb5js4uJcLllTV1UDh7TS2sUABuPOQwgDD-I2OTM3MFktVvZzPIAHQwABWbBwMHU+GCmF2SlaOAIJBgpR6UnIW2S9xAAGZ9lkjrlbKDChcscJafJytRbvUScgvIQ3h9ISN8FNTAAvfmaKYcKBfACCQiEKlw8g6dRUdweABoBiyAlMsGwIBAVHZFCBFdwYAAiMSYdHy7GSD6lOhqTTaMgmobDWC4e5sdTzXltfDqdSm80c97SE34pUgAAspMOOROVPOkb2pQZ-FuACUoBB1HAhLBLiJpvgQMNkzBIfUY08xDB0CGPmRIQAJFTTGDyRXTWBsQjyPIgbQG4a8gCE1CAA)

### 💻 Code

```ts
type a = { a: string };

type b = { b: number };

type c = { a: number };

type d = { a: boolean };

type ComputeIntersection<O> = { [k in keyof O]: O[k] };

type test1 = ComputeIntersection<a & b>; 
// test1 =>  { a: string ; b:number}  That's what I expected

type test2 = ComputeIntersection<a & c>; 
// test2 => { a: never } ，That's what I expected. just like: test2 = { a: string & number }

type test3 = ComputeIntersection<a & c & d>;

// test3 = > never . This puzzles me，According to test2,  test3 is supposed to be "{ a: string & number & boolean}" The result is still "{ a:never }"

// Replace a & c with test2 .
type test4 = ComputeIntersection< test2 & d>;
// test4 => { a : never }. How do we understand this!
```

### 🙁 Actual behavior

type test3 = ComputeIntersection<a & c & d>; 
// test3 => never 

### 🙂 Expected behavior
type test3 = ComputeIntersection<a & c & d>; 
//  test3 = { a: never }

**Comment by jcalz** [comment]
working as intended as per #36696
