### ISSUE TITLE
Union type evaluation inside condition

### ISSUE THREAD

**Issue by juanferrer** [microsoft/TypeScript#54905]
# Bug Report

### 🔎 Search Terms

type evaluation on or condition 

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about type validation.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/GYVwdgxgLglg9mABABwE4zFAyldYDmAFAM4BcixuG+AlIgN4BQiLiECxcANgKYB0XOEWI0A3IwC+jRqEiwEifDygA1AIZcQPYoTpNWiVMpCokAbQDklPPgsAaROAAmPYBh5OAuuKmMA9H6IAIIAbnAwTohOMEbQiFAAnsg8bAAWPBAA1tSIAEYJbBpcOWqIstDwYIzsYJSIZmoOuZ6IALyKyuqa2rrijDDAiIRqesysAYilMMTxqCBQqQXDYJELIDOlYAgAtDwAtsiJFFQENGMsaBjYJ0QjPtIDQ7mIAISt7c6u7k6jBhPP00QWygjhWXzAHiGahW8VS60mxxsZwMl0wOBshFyYkkD0Gw0QAB8CXlfuNAgBRGALHioBFwWnPNRGWbzRZQmFrDZAnb7Q4FazUZGsVHXDGlIkk8QovCi6j4gD88slOP6eNKbw+YLcEMiEueGtBLm1HlJLAmlOptNK9Lyk2ZwMN4Mhy1WcK5AtO5xQMvRcvFxKxUuFPpuCqVgckQA)

### 💻 Code

```ts
function printString(s: string) {
    console.log(s);
}

function getValues() {
    return ['string', undefined];
}

// Avoid direct type checking by calling a function
const [a, b] = getValues();

if (a) {
    // a is truthy (and thus a non-empty string)
    printString(a);
}

if (b !== undefined) {
    // b is not undefined (and thus a string)
    printString(b);
}

if (a || b) {
    // Either a or b are truthy (and thus a non-empty string)
    printString(a || b);
    printString(a ?? b);
}

if (a !== undefined || b !== undefined) {
    // Either a or b are not undefined (and thus a string)
    printString(a || b);
    printString(a ?? b);
}
```

### 🙁 Actual behavior

`a || b` and `a ?? b` are evaluated to `string | undefined`, even though they will never be undefined inside the condition. This is the case for all types I checked.

### 🙂 Expected behavior

Inside the condition `a || b` and `a ?? b` evaluate to `string`.

**Comment by MartinJohns** [comment]
Duplicate of #54252.

**Comment by juanferrer** [comment]
Shame.
