### ISSUE TITLE
Multiline strings are missing sourcemap entries

### ISSUE THREAD

**Issue by roblourens** [Microsoft/TypeScript#5490]
Here's a screenshot of the sourcemap visualizer.

![image](https://cloud.githubusercontent.com/assets/323878/10874916/2fedee50-80e1-11e5-9d1c-9e50981f19a0.png)

**Comment by sheetalkamat** [comment]
@roblourens  do you have any specific need for source map entries within the string literals? We do emit the sourcemap location of start and end of string literal.

**Comment by mhegazy** [comment]
closing for now. please reopen if it is still an issue.
