### ISSUE TITLE
Omit not working properly

### ISSUE THREAD

**Issue by CyberMew** [microsoft/TypeScript#54904]
# Bug Report

After using Omit<>, my undefined key errored out.

Example of working (before Omit) and notworking (after Omit) inside:
https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQEFUG9ir65JAewFdIAuVAZwhnAHMBuXfBCaAWwAcIrKa6YJsAC+oSLEQpUAIWws8AIxAAbFZRz4tqMAg5R+tBsy0jUAH1RkAJlDjgo1xqgD0L1AHkeIIrpUA6UXFoeGQ0AGF5LWIJCijtPGgADwhDQWFTIIgATy40ABFUAF4MVAAyVEiKmWYcvNQAUWLSivDmKCSuIhgIVDq0ADFmwssG5mAYmmoifQA1BBgAOSIIDw4QdkdKIZLNVk3uXkoAImOAGgVUZTVKGzsHazPXd3Q1VHoiImtUAHcAC1UaDAKysVAYnnWEAAPAA+S4xaBxPYJZKpVCnS4iC5aQikOIYsTAfqoAASzTWGyhAyex1xZAgxxhzEmvSoMyg8xgFM21koZN2lzYnB4fHR50u13UVjAtnsYEcTzcVxgRAA1lAwKg-rA0GQVFAqFRUMQOPoJN9SBB4b5EWjkdpUSdjpjsawkMR6U6WCJxkrifyIZTqei6ZBGYwgA

### 🔎 Search Terms

Omit

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQEFUG9ir65JAewFdIAuVAZwhnAHMBuXfBCaAWwAcIrKa6YJsAC+oSLEQpUAIWws8AIxAAbFZRz4tqMAg5R+tBsy0jUAH1RkAJlDjgo1xqgD0L1AHkeIIrpUA6UXFoeGQ0AGF5LWIJCijtPGgADwhDQWFTIIgATy40ABFUAF4MVAAyVEiKmWYcvNQAUWLSivDmKCSuIhgIVDq0ADFmwssG5mAYmmoifQA1BBgAOSIIDw4QdkdKIZLNVk3uXkoAImOAGgVUZTVKGzsHazPXd3Q1VHoiImtUAHcAC1UaDAKysVAYnnWEAAPAA+S4xaBxPYJZKpVCnS4iC5aQikOIYsTAfqoAASzTWGyhAyex1xZAgxxhzEmvSoMyg8xgFM21koZN2lzYnB4fHR50u13UVjAtnsYEcTzcVxgRAA1lAwKg-rA0GQVFAqFRUMQOPoJN9SBB4b5EWjkdpUSdjpjsawkMR6U6WCJxkrifyIZTqei6ZBGYwgA)

### 💻 Code

```ts
// playground.
```

### 🙁 Actual behavior

Error!

### 🙂 Expected behavior

Working without error by TypeScript when 'bill' key is defined to be `undefined`.

**Comment by MartinJohns** [comment]
This is working as intended. See #54451 and the linked issues.

**Comment by CyberMew** [comment]
Thanks for the hyperlink. Still feels like a bug to me though. When omitting something we expect the rest to stay the same and only the ones mentioned affected. The behaviour doesn’t match up with the meaning of the word at all. Hope they revamp it officially.

**Comment by MartinJohns** [comment]
If you look up the definition of `Omit` you will figure out why it's not working as you expect.

> Hope they revamp it officially.

As per the issue and it's linked issues: they will not. Now changing the definition of `Omit` is a too huge breaking change.

**Comment by CyberMew** [comment]
I looked up the definition of omit as you suggested:
_leave out or exclude (someone or something), either intentionally or forgetfully._

Sounds like it’s not working as per definition. It’s erroring out as per my playground. Please enlighten me (with details if possible) if I am missing something here.

**Comment by MartinJohns** [comment]
`Omit` is not a conditional type, so it doesn't distribute over unions. It's using `keyof`, which for union types only returns the keys common to all types of the union. That's where properties are "lost".
