### ISSUE TITLE
Type analysis for extending classes that narrow the type for some methods is faulty

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#54909]
# Bug Report

TS seems to allow narrowing the type of methods in extending classes in ways that shouldn't be allowed.

### 🔎 Search Terms

- class extends
- class narrowing

### 🕗 Version & Regression Information

It reproduces on v5.1.6 and v5.2.0-beta, not sure about the rest.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/MYGwhgzhAECC0G8BQ1oDMB2AKAbgLmggBcAnASwwHNoAfaDAVwFsAjAUxIEoCcB7MgCaJoKVNGC8MEXiDYA6EL2pZoAcgCS4sBmgALbQNmFSFSjAP1m7EhFXROAblEBfJ6kwAmXAWLkqtS1YObmg+QURRVCJdMgg5TFxHFyRnJCRQSBgAIWg2AA8iNgwBGHhkd2x8QOsQsKFysQkpGXlFZTVNYG1oSRAATz0DI0Ygmzsk1FcUtIw2AHdoHKxOeIwPaBVVSAFxhyA)

### 💻 Code

```ts
class A {
  fn(v: string | number): void { 
    console.log ( 'I can handle strings and numbers' );
  };
  fn2(v: string | number): void {
    this.fn(v);
  }
}

class B extends A {
  fn(v: number): void {
    console.log ( 'I can only handle numbers' );
  };
}

new B ().fn2 ( 'asd' );
```

### 🙁 Actual behavior

The problem is that TS seems to allow narrowing the type of non-static methods in this case, but that doesn't work because `A#fn2` relies on having access to a function at `this.fn` that can handle `string | number`, but since narrowing is allowed we can just make that point to a function that can only handle `number` so the class is basically completely broken now at the type level.

### 🙂 Expected behavior

This kind of extension like that should be disallowed, or it can cause bugs.

**Comment by RyanCavanaugh** [comment]
Please see "bivariant" in the FAQ

**Comment by fabiospampinato** [comment]
It seems related, by why would it be wrong to have an additional check like this when extending classes?:

- For every class in the extension chain.
	- For every non-static method on the class compute a map of the methods that are being accessed from "this", mapped to the interface of these methods before extension.
	- Compute the same map but after the extension.
	- Compare these maps to check if the newer for methods accessed from ".this" is still assignable to their older type.
	- If it isn't, consider the code invalid.

What would this break?

Like what I'm reporting seems akin to do this:

```ts
let foo: (v: unknown) => true;
foo = (v: number) => true;
```

Which is rightfully not supported, you can't narrow the type of the function like that or anything depending on it might break, so why is not the same logic applied for classes?

Like I don't understand why it's by design to allow that `B` class in my initial post to be broken?

**Comment by fatcerberus** [comment]
@RyanCavanaugh The FAQ should probably be updated - the relevant entry is "Why are function parameters bivariant" (reflecting pre-`strictFunctionTypes` behavior), uses only examples involving plain function types, and doesn't mention the distinction between regular function types and methods at all.  I don't blame anyone who thinks this is a bug even after reading that entry.

The *actual* relevant text is in https://github.com/microsoft/TypeScript/pull/18654 (emphasis mine):
> The stricter checking [of `strictFunctionTypes`] applies to all function types, *except those originating in method or constructor declarations*. Methods are excluded specifically to ensure generic classes and interfaces (such as Array<T>) continue to mostly relate covariantly. The impact of strictly checking methods would be a much bigger breaking change as a large number of generic types would become invariant ...

**Comment by fabiospampinato** [comment]
@fatcerberus If one special-cases this for classes via something like the algorithm I outlined [here](https://github.com/microsoft/TypeScript/issues/54909#issuecomment-1625615340), are you saying that that would just be too big of a change to make because of backwards compatibility?

I think it would be valuable even partially fixing this for classes only, and while I understand that a fix may be more disruptive than the bug itself I'm having trouble picturing the kind of code we shouldn't fix for classes, like do we really need classes specifically to be broken like this?

**Comment by fatcerberus** [comment]
There's no special carve-out for classes that would enable that special-case check to my knowledge - when you write `B extends A`, the check the compiler does is "Is `B` assignable to `A`?"  If the answer to that question becomes "no" due to stricter method checking, then so does the answer to "Is `Dog[]` assignable to `Animal[]`?"

**Comment by fabiospampinato** [comment]
I see 🤔 Would it then make sense to introduce another flag that enables the correct behavior? Like "surely" how it works today is not perfection and perfection is desirable.

**Comment by fatcerberus** [comment]
fwiw perfection is explicitly not a goal for TS - see https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals, in particular

> 3. [Do not attempt to] Apply a sound or "provably correct" type system. Instead, strike a balance between correctness and productivity.

**Comment by fabiospampinato** [comment]
I understand, but neither is a goal to have as much incorrect stuff as possible. Maybe this is a case where the fix can be added behind a flag?

**Comment by fatcerberus** [comment]
If this is ultimately a feature request for `strictMethodChecks`, then I'm pretty sure there's already an issue about that... but I can't seem to find it.
