### ISSUE TITLE
Generic return type (T[K]) is intersection among all properties of T instead of union

### ISSUE THREAD

**Issue by taozhou-glean** [microsoft/TypeScript#54901]
# Bug Report

### 🔎 Search Terms

conditionally generic return type, union vs intersection, valueof etc

### 🕗 Version & Regression Information

- This changed between versions 3.3.3 and 3.5

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYQiXQQHMBBOAbwCg44BXAZzQC44mYplSaBfGjVCRYiFGiy4CREqQBC1OnADaAa2ABPdp25JSAXXZIGAWwBGaOAB8OXHtbhmIEADbBMSfoOHR4yVBg4eITEZIr05AD87CGy5Epy0dKh8l5C4L5w2C6YTEzJsvg5eeFZMmQx5aRwALzUAvSkwDAAFOpacO0Q6AVkAJSl9FDNDFBIcDAAFghMAHTYVWqa+koCAjQwGmB4AGqYLgzAAPLoADwAKgB8tXDnSxrdtys0C0icZSk3SMAA7r2kRVyTBafUE6AYSGwMAQRDgmFOAGk4KBUEgACb5Lo9WJkS5tTTsBF9SopZQI-SlYYwUbjV6yWZNVrtUHrV7vABu+0OTHYewOxzOONI1zqdLIDOaLQA5OQpQMAPTyuEtABE5BVoLZrmAsxcEFILU5-KYfSAA)

### 💻 Code

```ts
export interface ConfigA {
  user: string
}

export interface ConfigB {
  [key: string]: number | string | boolean
}

export interface Config {
  A?: ConfigA
  B?: ConfigB
}

export class ConfigClass {
  config: Config = {}
  get(key: keyof Config) {
    return this.config[key]
  }
}

type ValueOf<T> = T[keyof T]

const config = new ConfigClass()

function a<K extends keyof Config>(key: K): Config[K] {
  return config.get(key)
}
```

### 🙁 Actual behavior

Type 'ConfigA | ConfigB | undefined' is not assignable to type 'Config[K]'.
  Type 'ConfigA' is not assignable to type 'Config[K]'.
    Type 'ConfigA' is not assignable to type 'ConfigA & ConfigB'.
      Type 'ConfigA' is not assignable to type 'ConfigB'.
        Index signature for type 'string' is missing in type 'ConfigA'.

### 🙂 Expected behavior

I would expect no error of returning `config.get(key)` within function a

**Comment by xiBread** [comment]
[`get` needs to be generic](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYQiXQQHMBBOAbwCg44BXAZzQC44mYplSaBfGjVCRYiFGiy4CREqQBC1OnADaAa2ABPdp25JSAXXZIGAWwBGaOAB8OXHtbhmIEADbBMSfoOHR4yVBg4eITEZIr05AD87CGy5Epy0dKh8l5C4L5w2C6YTEzJsvg5eeFZMmQx5aRwALzUAvSkwDAAPADScKCoSAAm+eoaEOgFZAB8ABQD7G0AlKX0UM0MUEhwMAAWCEwAdNhVapr6SgICNDAaYHgAapguDMAA8ugtACqjtXAvB4PDL0c0eyQnDKKQ+SGAAHcRqQirkmOMZoJ0AwkNgYAgiHBMO1OiBun04AMhtCJlM4LNKillG19KVFjBlqtAbJtk0YJNNIi+EA); otherwise, the return type is essentially `Config[keyof T]`.

**Comment by taozhou-glean** [comment]
> [`get` needs to be generic](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYQiXQQHMBBOAbwCg44BXAZzQC44mYplSaBfGjVCRYiFGiy4CREqQBC1OnADaAa2ABPdp25JSAXXZIGAWwBGaOAB8OXHtbhmIEADbBMSfoOHR4yVBg4eITEZIr05AD87CGy5Epy0dKh8l5C4L5w2C6YTEzJsvg5eeFZMmQx5aRwALzUAvSkwDAAPADScKCoSAAm+eoaEOgFZAB8ABQD7G0AlKX0UM0MUEhwMAAWCEwAdNhVapr6SgICNDAaYHgAapguDMAA8ugtACqjtXAvB4PDL0c0eyQnDKKQ+SGAAHcRqQirkmOMZoJ0AwkNgYAgiHBMO1OiBun04AMhtCJlM4LNKillG19KVFjBlqtAbJtk0YJNNIi+EA); otherwise, the return type is essentially `Config[keyof T]`.

thanks! But even with `Config[keyof T]`, should not it be `ConfigA | ConfigB` instead of `ConfigA & ConfigB` ?

**Comment by fatcerberus** [comment]
> But even with Config[keyof T], should not it be ConfigA | ConfigB instead of ConfigA & ConfigB ?

It’s a side effect of #30769.
