### ISSUE TITLE
exactOptionalPropertyTypes vs class implementing interface with optional properties

### ISSUE THREAD

**Issue by aredridel** [microsoft/TypeScript#54919]
# Bug Report

### 🔎 Search Terms

`exactOptionalPropertyTypes` `interface` `implementation` `class`

### 🕗 Version & Regression Information

4.4

Regressed additional case in 5.0.4

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `exactOptionalPropertyTypes` (there are no FAQ entries)
- I was unable to test this on prior versions because the feature was introduced in 4.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=5.0.4#code/JYOwLgpgTgZghgYwgAgCrIN4Chm+QDwH4AuZARgG4sBfLLBAGzgGdm11gBbABwYk4jg26bHgIk0AbQBE+aQF0qtek1bsOPPgKHIACnChhgcBgB5UAPkw48ADQmUaQA)

### 💻 Code

```typescript
// with exactOptionalPropertyTypes enabled

interface T {
    x?: 1;
}

// Breaks in 5.0.4 with TS2420
// Class 'TT' incorrectly implements interface 'T'.
//  Types of property 'x' are incompatible.
//    Type '1 | undefined' is not assignable to type '1'.
//      Type 'undefined' is not assignable to type '1'
class TT implements T {
    x?: T["x"];
}

// Broken since 4.4 with TS2559
// Type 'TTT' has no properties in common with type 'Partial<T>'.
class TTT implements Partial<T> {
    X?: 1;
}
```

### 🙁 Actual behavior

It is not possible to implement the interface in 5.0.4, and difficult to implement by reference in 4.4

### 🙂 Expected behavior

Both cases satisfy the constraint

**Comment by RyanCavanaugh** [comment]
This is possible, you just can't write `T['x']` since that is `1 | undefined` and you're not allowed to have an instantiated property with value `undefined` under EOPT. All this behavior follows from the definitions of the rules.
```ts
class TT implements T {
    x?: 1 = 1;
}
```

**Comment by aredridel** [comment]
The hover in vscode shows `T["x"]` as `1` not `1 | undefined`

this is also useless since in real cases there is no default value here; 1 is a trivial example

But

> not allowed to have an instantiated property with value undefined under EOPT

seems like something that should be documented along with the option since that makes it quite possible to create interfaces that are not implementable.

**Comment by aredridel** [comment]
Also is there a reason for requiring properties to have values when instantiated? This is literally modeling a constructor that conditionally sets a property.

**Comment by aredridel** [comment]
Are these rules documented anywhere?

**Comment by fatcerberus** [comment]
> Also is there a reason for requiring properties to have values when instantiated?

Because that is literally the *raison d'être* for `exactOptionalPropertyTypes`?  If you don’t want that behavior, turn it off.

**Comment by aredridel** [comment]
> Because that is literally the raison d'être for exactOptionalPropertyTypes? If you don’t want that behavior, turn it off.

how do you model the difference between

```
class X {
   constructor() {
      this.x = 1;
   }
}
```

and 

```
class X {
   constructor(x) {
       if (x) {
            this.x = 1;
       }
   }
}
```

I'm using EOPT specifically for this.

**Comment by RyanCavanaugh** [comment]
`T["x"]` in a read position is `1 | undefined`, you can experiment to determine this:
```ts
interface T {
    x?: 1;
}

class TT {
    x: T["x"];
    constructor() {
        this.x = undefined; // allowed
    }
}
```

> seems like something that should be documented along with the option since that makes it quite possible to create interfaces that are not implementable.

But you can implement it; my example showed how.

**Comment by aredridel** [comment]
Ugh this is not really resolved — you can't use EOPT on classes this way.
