### ISSUE TITLE
Array.isArray no longer narrows 'object' values in 5.1

### ISSUE THREAD

**Issue by AustinGrey** [microsoft/TypeScript#54917]
# Bug Report

### 🔎 Search Terms

All open issues referencing "Array.isArray"
"typeguarding arrays from object values"

### 🕗 Version & Regression Information

- This changed between versions 5 and 5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwM7ACGUaAFgPIBGAVsBgDwAqcoMwKAJnnBDXTAD4AFACgAkL2oAuOIwA04sFAhhgsTMDwyhAa2ABPCAlkBKANoBdBSbgBvcQmhwhaHHnhKVamPp7HPquqaNvZiYq4o7nAAboQANnAAvDw0ZgHe+hYA3OJimMZCAIJQUIT6AHSYeMWl+kKxcSYhuWIN5Y5QAKKEZEJCNokCdgC+Jjlhw+KTw0A)

### 💻 Code

```ts repro
export function searchObject<T extends object>(
	obj: T,
	properties: (keyof T)[],
) {
	for (const property of properties) {
		const val = obj[property];
		if (Array.isArray(val)) {
			val.forEach(() => {});
		}
	}
}
```

### 🙁 Actual behavior

`val` may be an array, but Typescript reports that forEach is not defined on val because T[keyof T] cannot be an array.

### 🙂 Expected behavior

`val` is 'narrowed' to `T[keyof T] & any[]`

**Comment by RyanCavanaugh** [comment]
The originating change is being reverted. Track at #54845
