### ISSUE TITLE
One more case of partial union signature matching

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#5491]
```(typescript)
function f(x: string, a?: number) {}
function g(x: string, a?: string) {}

var m: typeof f | typeof g;

m("a"); 
```

Currently in this case the resulting type doesn't have any signatures.
But factually, the resulting type can have a signature with a single parameter of type "string".

**Comment by ahejlsberg** [comment]
We have the rule that we only keep existing signatures and never speculatively manufacture new ones. In your example, no *existing* signature is compatible with at least one signature from each constituent function type, so the resulting type has no signatures.

**Comment by zhuravlikjb** [comment]
Thanks, now it's clear how it works.
