### ISSUE TITLE
recursive Map

### ISSUE THREAD

**Issue by JiangShanyi** [microsoft/TypeScript#54911]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about MAP

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
var a = new Map ([[1, 'a'], [2, new Map ([[3, 'c']])]])

```

### 🙁 Actual behavior

It has error:
No overload matches this call.
  Overload 1 of 4, '(iterable?: Iterable<readonly [number, string]> | null | undefined): Map<number, string>', gave the following error.
    Argument of type '([number, string] | [number, Map<number, string>])[]' is not assignable to parameter of type 'Iterable<readonly [number, string]>'.
      The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
        Type 'IteratorResult<[number, string] | [number, Map<number, string>], any>' is not assignable to type 'IteratorResult<readonly [number, string], any>'.
          Type 'IteratorYieldResult<[number, string] | [number, Map<number, string>]>' is not assignable to type 'IteratorResult<readonly [number, string], any>'.
            Type 'IteratorYieldResult<[number, string] | [number, Map<number, string>]>' is not assignable to type 'IteratorYieldResult<readonly [number, string]>'.
              Type '[number, string] | [number, Map<number, string>]' is not assignable to type 'readonly [number, string]'.
                Type '[number, Map<number, string>]' is not assignable to type 'readonly [number, string]'.
                  Type at position 1 in source is not compatible with type at position 1 in target.
                    Type 'Map<number, string>' is not assignable to type 'string'.
  Overload 2 of 4, '(entries?: readonly (readonly [number, string])[] | null | undefined): Map<number, string>', gave the following error.
    Type 'Map<number, string>' is not assignable to type 'string'.

1 var a = new Map ([[1, 'a'], [2, new Map ([[3, 'c']])]]);
### 🙂 Expected behavior

I think it should be a valid TS code and I want there should be no error

**Comment by RyanCavanaugh** [comment]
You can do this, you just need a type argument since inference thinks something is fishy here
```ts
var a = new Map<number, string | Map<number, string>>([[1, 'a'], [2, new Map ([[3, 'c']])]])
```

**Comment by jcalz** [comment]
duplicate #37527
