### ISSUE TITLE
Inconsistency in polymorphic 'this' typing

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#5492]
```(typescript)
class A {
    p: A;
    c = this.p;
}

class B extends A {
    p: B;    
}

var s: B;
var k = s.c; // 'k' is 'A'
```

```(typescript)
class A {
    c = this;
}

class B extends A {        
}

var s: B;
var k = s.c; // 'k' is 'B'
```

**Comment by zhuravlikjb** [comment]
After some experiments, a simple question: is 'this' polymorphic only for simple expression "this", and not when it's used as a qualifier in some reference expression, e.g. "this.foo"?

**Comment by mhegazy** [comment]
One thing to note, there are two uses of the keyword `this`. your example above uses an initializer. this will be evaluated once, in the context of the base class `A`; the type of the expression `this.p` here is `A`, and there is no polymorphism here. if you however, gave `c` the type `this`, this will be instantiated in the context of the derived class, and you would get the desired polymorphism.

**Comment by zhuravlikjb** [comment]
Thanks, now it's more clear how it behaves.
