### ISSUE TITLE
querySelector should support Level 4 CSS selectors

### ISSUE THREAD

**Issue by unikitty37** [microsoft/TypeScript#54934]
# Suggestion

## 🔍 Search Terms

`queryselector has`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

`querySelector` and `querySelectorAll` should support Level 4 CSS selectors such as `:has()`.

## 📃 Motivating Example

If you're writing front-end tests, you can now use modern Level 4 CSS selectors in `document.querySelector()` and `document.querySelectorAll()` — making your tests easier to write!

## 💻 Use Cases

When selecting items in tests, it can save having to add `data-testid` attributes if it's possible to select the correct element with standard CSS. Sometimes, when there are multiple elements, it's necessary to use `:has()`.

While the Level 4 selectors still seem to be at Working Draft stage, they are widely adopted in modern browsers (though, for some reason, Firefox still hides `:has()` behind a flag 🤷) and are being used by developers. It's a serious disconnect to find that your tests don't allow you to use them.

**Comment by IllusionMH** [comment]
What support you expect from TS?
`querySelector(All)` has `string` overload so you can use whatever selector you want.

**Comment by unikitty37** [comment]
I'm not 100% sure what's implementing this, TBH — when I ⌘-click on `querySelector` in VSCode, it takes me to VSCode's own node_modules/typescript/lib/lib.dom.d.ts, so I think the "typescript" in that path has fooled me into thinking TypeScript implements it.

I _was_ slightly puzzled by that, TBH. Apologies for the noise.

(If anybody know what _is_ responsible for implementing that, do please let me know :)

**Comment by IllusionMH** [comment]
TS provides type definitions for those funstions which are expected to be available in runtime, and you were navigated to those definitions.
It's up to browsers and other tools (like jsdom) to implement them
