### ISSUE TITLE
String literals in mapped type lost when passing an object type to a function

### ISSUE THREAD

**Issue by evur** [microsoft/TypeScript#54936]
# Bug Report

### 🔎 Search Terms

mapped type string literals lost

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mapped types and string literals

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230709#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIDWEAngFzIDOYUoA5gNz7IzAAeEAJgPoBucAGwCuEShQDkMTOOQAfZOIBGcKOKYBfXLjAkADigBCKgDwAVZBDaQQnSmkwBtALoA+ZAF5kAJQgJ0UTmMAA24AEmxTBxAhAFtFaCcHcWIScSd1IIAaKhp6FyZcAHpC5CFKemQwAAsUHX1kTmAoXzABEmQAd39CMS0BCDAGppaKIyhjB2Y8AgIUiSl0cUzmAlYOHn5hUXnpZYJ1PZwVolIJZVVD1fYuPkERMQVzpeYD3FcmRuaEMAA6IpKAETcBYA5BwGzIIHnUEqFC6ZqUCDgZDoECQz4tUEACi6UEI9AAlFpishFEJBtUUFIBAJ0B0Kpx0KIQOJBrjCGQtH4QNRkM1Bp4sTAhCBvsBUcgzBYrEjbPZ0M4XFjQLpyRRTASjgR+UIoGjsOowXYxmZ8rh1ASsZMCNMZnMFAtnjMWNcNndtg7di9DrbZqdHionTM1jdNvczoHDq8nASmPy-iSgSCwRCoSoYc1kDFgJRyiA6CwoOgYpD+QDcEA)

### 💻 Code

```ts
interface Foo {
  key: string;
  fixed_values: 'foo' | 'bar';
}

type Bar<T extends Foo[]> = Record<`_${T[number]['key']}`, string>;

// using the type directly works:

let direct: Bar<[
  {
    key: 'foo',
    fixed_values: 'foo',
  },
  {
    key: 'bar',
    fixed_values: 'bar',
  },
]>;
// "_foo" and "_bar" are present on "direct" (working)

// but the following doesn't work:

const ret = (function <T extends Foo[]>(input: T) {
  return {} as Bar<T>;
})([
  {
    key: 'foo',
    fixed_values: 'foo',
  },
  {
    key: 'bar',
    fixed_values: 'bar',
  },
]);
// "_foo" and "_bar" are missing from "ret"
```

### 🙁 Actual behavior

The mapped type in the variable `ret` doesn't have any fields.

This problem occurs because the string literals are reduced to the `string` type. This is also shown by the below screenshots.

The type should look like this:
![](https://github.com/microsoft/TypeScript/assets/63237520/77527e4b-89eb-4c35-be14-94758ed0474d)

But it just has `string` instead of the actual values:
![](https://github.com/microsoft/TypeScript/assets/63237520/b9a59e4e-9243-4541-95d7-dfbf664ed269)

It works, when replacing the type of the `key` field with a string literal union like in `fixed_values` or a template literal. But then the value is restricted.

### 🙂 Expected behavior

The resulting type should be an object with the "key" fields of the objects from the input array as the keys but prefixed with an underscore.

The values are irrelevant in this example.

The expected behavior is achieved when using the type without a function as shown in the code snippet.

In the real code which brought me to this problem, the input array is used as value and type at the same time.

**Comment by Andarist** [comment]
Literals are only inferred automatically~ when they have a *direct* primitive constraint. Your overall constraint is an object type and it only has a string property - so the type there is widened to a `string`. You can work around this using `const` type parameters: [TS playground](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230709#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIDWEAngFzIDOYUoA5gNz7IzAAeEAJgPoBucAGwCuEShQDkMTOOQAfZOIBGcKOKYBfXLjAkADigBCKgDwAVZBDaQQnSsigQ4ndCAEk0mANoBdAHzIAXmQAJQgEdChOYwADbgASbFNPECEAW0Vob09xYhJxb3VogBoqGnpfJlwAeirkIUp6ZDAACxQdfWROYAcEMDdkAHcIwjEtAQgwTu6wsAojKGNPZjwCAlyJKXRxIuYCVg4efmFRDekdgnVznF2iUgllVSu99i4+QRExBQft5kvcPyYXR6YAAdNVagAibibCHIOA2ZBQh6wlQoXQOSgQcDIFyIoEzWEACiGUEI9AAlFoashFEJJi0UFIBAJ0ANGs5RCBxJMSYQyFpwiBqPYJoFkISYEIQL1gLjjILheZLNZbCKnC5+hh0D5fITQLo6RRTOTrgQHGAhFAQDh1HC7PMzBVcOpyYSlgQVqt1gpNj9ViwXod3icfWdfldPWs7l8VH7VvtXkcPvdY1c-t5yUxzWDqVCYXCEUiVCiHMhUsBKA0QHQWFB0KlEeaIbggA)

**Comment by evur** [comment]
Thank you! It works now.
