### ISSUE TITLE
Map#has() should suffice for an undefined check when proceeding Map#get()

### ISSUE THREAD

**Issue by SReject** [microsoft/TypeScript#54930]
# Suggestion

## 🔍 Search Terms

Map, map has

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

For instances cast as `Map<>`, a check of `Map#has(key)` should suffice as an undefined check for the key

## 📃 Motivating Example

Currently, we are required to have a redundant typecheck after a `Map#has()` for `Map#get()` calls:

```ts
const myMap : Map<string, string> = new Map();
myMap.set('key', 'value');

if (myMap.has('key')) {

  // ts(2322) - 'string | undefined' is not assignable to type 'string'
  const value : string = myMap.get('key');
}
```

This suggestion asks that ts infer the type as not a union with undefined if a `Map#has()` check has proceeded the `Map#get()` call

**Comment by MartinJohns** [comment]
Duplicate of #13086.

**Comment by SReject** [comment]
That is indeed the case. Closing
