### ISSUE TITLE
Return types could be narrowed at callsite given parameter types

### ISSUE THREAD

**Issue by spence** [microsoft/TypeScript#54931]
# Suggestion

### 🔎 Search Terms

- narrowing return types
- parameter types infer narrow

## ✅ Viability Checklist

* ✅ This wouldn't be a breaking change in existing TypeScript/JavaScript code
* ✅ This wouldn't change the runtime behavior of existing JavaScript code
* ✅ This could be implemented without emitting different JS based on the types of the expressions
* ✅ This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* ✅ This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Infer function callsite return types to match existing behavior of declarations and assignments.

```ts
// Declarations correctly infer narrower types

let a: boolean | null = true // type narrowed to `true`

// Assignments correctly infer narrower types

let b: boolean | null
b = true // type narrowed to `true`

// However, function calls do not yet infer narrower return types

function defaultNull  (v: string | null = null) { return v }
function optional     (v?: string)              { return v }
function union        (v: string | number)      { return v }
function generic<T, K>(v: T | K)                { return v }

let v1 = defaultNull("")             // `string | null`. could narrow to `string`
let v2 = optional("")                // `string | undefined`. could narrow to `string`
let v3 = union("")                   // `string | number`. could narrow to `string`
let v4 = generic<string, number>("") // `string | number`. could narrow to `string`

// A workaround requires overloading to explicitly define param/return type combos

function overload<T>(v: T): T
function overload<T>(v?: T): T | undefined
function overload<T>(v: T) { return v }

let v5 = overload<string>()   // existing behavior returns `string | undefined`
let v6 = overload<string>("") // overloading narrows type to `string`

```

## 📃 Motivating Example

If we know a value can't be undefined or null, Typescript has previously removed these types. 

Narrowing return types at callsites could be done automatically rather than requiring users to manually narrow types. This would remove unnecessary type checking and remove bugs for users that explicitly cast return values.

## 💻 Use Cases

I'm developing a library that takes optional defaults. 

```ts
// Library to get state
const get = <T>(defaultValue?: T) => {
  const state = void(0) as T | null // mock state
  return state ?? defaultValue
}

// Usage without default
// - Intuitively returns `string | undefined` 
const state = get<string>() 

// Usage with default
// - Intuitively it should return `string` as there's no possibility it's undefined
// - Unintuitively returns `string | undefined`
// - Currently, requires additional type checking or explicit type casts
const state = get<string>("default")
const stateNarrowed = state as string
```

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEDEFcDsGMBcCWB7apYEMA2WDOoATZUaZeURaAMwFMAnEjOu5Ad3tDpvkjrXgCeABxr4A5ogBuNNEKYYAttw6CRuAFDqqMBCjQEaVDJCzwAciayhQACkkAuULnh1KY0AB8Sl0AF5vOACUoADenNy8aJKgAL5aOkiooMhCidDY1pl2APyOzq7QYsGZJaWh4Tx8oNFx2nBpoDB6ZdZ2eS5unt4KAEb0xSVhXJVRsfH1zWIy9IiwADwAKgA0oADSAHxtoAtdqwMtZUMRVTWaWNzVAIx+hIbGphY4NgBEz-sHoCCgNAAeIgg0AigAAG+TcwNAYjIILBhS60EswPU53IkgATDcUmlsC83h8Wl9fv94ICYR1ChCoeRQeT3F4YAYqJRAUiUdUAMw3JqoXHvfElQl-GgAoE0gpiSnQsWdLwI3r0VkXSQAFhuU2gM3msLEKzlfTom1ewUFxNJ0opkKl2vhkHldCR6i+AHVkHQANZMZAM8IAR0giC4+GQ0joWGQGAInXgxCJWFmiHgWAEtyZGtAcjoimAw0ioFUNHQyF6yA0410SWD9DDEcWmwc20CjgWZYaldD4YItZyTcb2y6DMMzIILeabernYWdZ75RzJzGyKVAFZMSHx3NtYa8SbhSTRdrJdT9wvUQA2FdVjvr2mbAbbkVk8X96CMocHh8yxrPwcaghIoA)

**Comment by fatcerberus** [comment]
The return type of a non-generic function is inferred from the function body itself, not the callsite.  This is not a bug.  To infer things from the callsite, you need to write a generic function.

**Comment by spence** [comment]
> The return type of a non-generic function is inferred from the function body itself, not the callsite. This is not a bug. 

Thanks. Updated to be a suggestion rather than a bug.

**Comment by RyanCavanaugh** [comment]
Non-generic functions don't have a relationship between their input and output types; this is what the distinction between generic and non-generic is.

**Comment by spence** [comment]
But generics _aren't_ inferring narrower types for optional parameters.

<img width="400" alt="image" src="https://github.com/microsoft/TypeScript/assets/138762/f1c3a1b0-27e6-44b9-abee-92474d989fa4">

I'm curious why these are the exception. Wouldn't it be better to narrow when possible?
