### ISSUE TITLE
Type narrowing working with ts-node but not with tsc

### ISSUE THREAD

**Issue by Fectorez** [microsoft/TypeScript#54946]
# Bug Report

### 🔎 Search Terms

- tsc
- ts-node
- type narrowing
- discriminated union

### 🕗 Version & Regression Information

I have a discriminated union, with a boolean being the discriminator for my 2 interfaces.
If I use boolean coercion, then the type in the "if" statement is correctly narrowed, but the type in the "else" statement is not narrowed, and the code fails with the error [TS2339](https://typescript.tv/errors/#TS2339). 
This problem occurs with tsc (`npx tsc ./test.ts`), but not with ts-node (`npx ts-node ./test.ts`).

This is the behavior in every version I tried.
Exemple :
- tsc: 5.2.0-dev.20230710 ;
- ts-node: 10.9.1.

### ⏯ Playground Link

The code is working with the official playground:
[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/JYOwLgpgTgZghgYwgAgJLIN4FgBQz8H4BGAXMmFAK4QDcuhhAHmSJQLZHR04C+uuoSLEQoAUpnoNiZeABsAzrUlSAnmXkVQAc258cuBAHsQG5DGQBeZAAoIZdAB9kogJSWAfBLxTkwc7YA6Ijdsbx8fIxNDWQgA2UMtQMYXbnCeZAgFFFDw8Mj5aNj4xNiVFOUGPR4gA)

However, it does not work with mycompiler:
[mycompiler link with relevant code](https://www.mycompiler.io/view/5W2pmhLWWVe)
(Click on "Execute")

### 💻 Code

```ts
interface I {
        b: true;
        x: number;
}

interface J {
        b: false;
        y: string;
}

const f = (e: I | J) => {
        if (e.b) {
                console.log(e.x);
        } else {
                console.log(e.y);
        }
}
```

(Try `npx tsc ./test.ts`, then `npx ts-node ./test.ts`)

### 🙁 Actual behavior

This error occurs:
```
test.ts:15:31 - error TS2339: Property 'y' does not exist on type 'I | J'.
  Property 'y' does not exist on type 'I'.

15                 console.log(e.y);
                                 ~
```

### 🙂 Expected behavior

No error should occur, and, in line 15, `y` should be considered by tsc as being attribute `y: string` of `J`, as it is with ts-node.

**Comment by MartinJohns** [comment]
Make sure the TypeScript versions **and** the compiler settings are the same. Most likely you have `strictNullChecks` turned off in the non-working case.

**Comment by Fectorez** [comment]
Thank you @MartinJohns, turning `strictNullChecks` on resolves my problem.
