### ISSUE TITLE
Error:  Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by crazyair** [microsoft/TypeScript#54943]
# Bug Report

### 🔎 Search Terms
`error TS2589: Type instantiation is excessively deep and possibly infinite.`

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ___4.9___ and ___5.1.6___
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcAiwBmBLAdsAeQCMArABQEMYALAHgBUAaOegRjlBmFwBMBnOBVyIA2gF04AXjgBXXAGtcEAO65xAPilwA3gCg4BuCLJw8cecEQRMLMQC44AJWABHGdijAeDdcYmdufjgIUmAAYxh9Q2iAfnQsPEJSShpaZzcPLx8-ZjYRXBkAWyJgKH8QLl4BPhgoPABzODiRADo2tmYyCQc-dSjogwcTAB8jNpaOuC6Abl0AXxELKxt6MVndUEhYU1wuKEwKMNR6CiIAG2AyKAgwPgYtIURNPWieKgoAZQgZKCOYh3o4lm0TCEDORVwfH+OjgbxgFAAkrxQNCMDh8MRyFQ6PRNAs1vNdBtwNB4Jg5BFsBBcHBybgwvdpI91AAKMDXW4A04XK43O64gCUOn6cE8MB+NPZfNmcyJm1JcFBkPgPGAhQgWjpYRZ2lh7y+PyOPV1FAcuqIDgA5GFLXA5naxMxQeDCpDjXr4UjVSAepaKJbmJaiJaJHNQwL1gB6SOK6jheQIZDAYlbeBIFCx+P0JNaNGJTEpOgms1wC1wGp1XCNe1zdSzIA)

### 💻 Code

```ts
export type DefineObjPath<T, T1 extends any[] = unknown[]> = {
    [P in keyof T]: Required<T>[P] extends object
        ? DefineObjPath<Required<T>[P], T1[number] extends string ? [...T1, P] : [P]>
        : P | [...T1, P];
}[keyof T];

export interface TableProps<T = any> {
    dataSource?: T[];
    columns?: { dataIndex?: DefineObjPath<T> }[];
}

export function func<T = any>(props: TableProps<T>) {
    return props;
}

export const demo = func({ dataSource: [{ a: { b: 'c' } }], columns: [{ dataIndex: ['a', 'b'] }] });

// check type
export type checkType = DefineObjPath<{ a: { b: string } }>;


```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/7971419/9fab4c44-ee76-4405-8f9c-cbab112f20cd)

**Comment by xiBread** [comment]
This isn't a bug.

**Comment by jcalz** [comment]
It's definitely not a *crash* (which is what happens when the compiler fails to complete property... a runtime error of the compiler process itself.  It's not when the compiler completes but produces unexpected results)

**Comment by whzx5byb** [comment]
See my comment in https://github.com/microsoft/TypeScript/issues/54910#issuecomment-1625666735. The workaround also works here.

**Comment by crazyair** [comment]
> See my comment in [#54910 (comment)](https://github.com/microsoft/TypeScript/issues/54910#issuecomment-1625666735). The workaround also works here.

I am experiencing performance issues

**Comment by RyanCavanaugh** [comment]
Hitting the depth limiter is not a bug.

**Comment by crazyair** [comment]
> Hitting the depth limiter is not a bug.

How should I write it

I want 
```ts
export type DataType = {
    a: { b: { c: string } };
    list:{ key:string }[]
};

export type checkType = DefineObjPath<DataType>

```

to 

```ts
// ['a'] | ['a', 'b'] | ['a', 'b', 'c'] | ['list'] | ['list', number ] ['list', number, 'key']
```

**Comment by crazyair** [comment]
This is what I want


https://www.typescriptlang.org/play?ts=5.1.6#code/C4TwDgpgBAYglhANgEwIICd0EMQB4AqUEAHsBAHbIDOUW5IA2gLoB8UAvFPgwMxNGkK1KFWDo45AOYBYAFBQFUAPywEKDNjwNuABiYAaLgwCMBowCYmrKAB8o2hnsPdTzhpbd8mcxVABcFvwkZJQ0ouJSPooq8EhomDi4Dk5GptZ2yWYuWe5WUQoB2QIhwuESMvLRqnEaiZnp9ro5afn+RnrFQmFi5a0q9a2FANxycqCQUAAiEABmEhAA8gBGAFYACljAABYAolgAxlsEhgCSVLUgnaFQSwD2t4gQdBxQM1iIVBDOxlfCdIz8TgAV3IAGtyLcAO7kZhsTgAb1aDDWUAkUFBEBAtxmXCYAQAShAAI5AuDoCDIAgsZFBQTXeH2DEgALkIEAWyWEHQeKgt1WEH2wCgAF9mK1fCppnNyItVhttntDrhCSSyRSqTSGKyOVyzGIgV8uMYtezOdzft0IpJlPYAHT2-DGQxrfgBGkscWKAnE0nkyn4akui20ehiyq+BQqR0mnXm4JdEQ9SLhiMSu0Op1QIMZe22x3Owzas38OyxdQJPCOj0p1MFLO2exrQum3Weusq33qgM04N8lYC4Btm1S+bLdabXYHI4dtX+wNmN4fQ3Rou64NlKQ2hi5-NZ12N1hDwrG1dxumlJMVWs2gAUZwuwf10H6O8zp5L6bzb5b6Gd++3GZ-gAlA2ZbxJoBDGNW14BGsIyyKKTLYri8FjOA0AjjKY7ykcAYvEhOKEBkBG4g2mGyuOCpTlSqGyCQYC3OgQrjNAhwCqC+DoS85HYROuCTJsWCcZALC0QA9GJUCAFyegDR8nI9GMcxXECcAQlcQirRYAEG6SPBvhLEo2mXswemKPshlQAy+zGBZOlDFA+zmBZp4iiZrTIBZDLIDZRlWiZUDIE5vnlCKpkKBAnlED5llEEFiZWvZEA8LZxlMIlAAsAQMhAACsWVEAAbMFm7CiKZXCvBFWjLIElcFscA0A1vKgvJxAMUxDm3OQogBRAbK3AEPFynxKlqSJzAvAwrS1YAX+qAAIerQAORYIt+hLUsq1Lfsm0potyA7b4i0QAdigMMti0GEii0bZdKZndtt2+Gd+2PadR0XWtKa1YAMXKAOV+gCncoAUHJXRthiuFd21g69Cj3atUCZot1kfRDcMI45yN3XtcN7cYGNPVjhg46j0P2ATUB7eYeNvcdhMQLjJNnTT5N09jECUwz7207jtM8FTMOc8z3PM7zUOffjTNHULR3pXzpMSyztMy7TOWy4zrNSxASvMyrHPyxrWtHSrtMFRjaXVdVCkdRIZDoG8+zQPgWBLI8azoLcYBUAQLz-GwiIpsggkAMq3EC6D2xZ3Bmym+wPOy3WRQHqknJQJAWUNlG4WwopR8KFttYprwgoKcBdYX5D7F7nA+zeYBux7hROy7deewGIF+745LAKH5BQLX7tUJV1W1fg9U0BCQq3C1sgzEXN5eUHIdhxAboMlpMVLAEiOLeVZgx4gcdUCvAWCcnyAkG6538MKV9AfBQA
