### ISSUE TITLE
Inconsistency between annotated and unannotated optional parameters in presence of a contextual type

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#54948]
# Bug Report

### 🔎 Search Terms

optional parameter contextual type annotated

### 🕗 Version & Regression Information

- This changed between versions 4.6 and 4.7

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230710#code/MYewdgzgLgBAZgRgFwwBQEMXQE4EswDmANDAEYpgCuAtqQKbYCUMAvAHwwBuIuAJq2nQlSAfmbsYAbwBQMMrJgB6RTAB6I6QF8A3NOmhIsOACYUGLFDyFhFGvSasO3PgIzCRt2g3EcZc0grKaho60kA)

### 💻 Code

```ts
const f1: (a: string, b: number) => void = (a, b?) => {
  b
  // ^? 4.7+: number, before: number | undefined
};

const f2: (a: string, b: number) => void = (a, b?: number) => {
  b
  // ^? number | undefined
};

```

### 🙁 Actual behavior

optionality added through `?` gets "lost" when there is no type annotation on the parameter

### 🙂 Expected behavior

I think that it would make sense to keep this parameter optional since it was annotated as such

**Comment by Andarist** [comment]
That is true - but the same thing could be said about annotating `b` as `string | number` but that wider type gets preserved despite the fact that `b` can never be anything other than `number`. Perhaps `?` is not as integral part of the type annotation as the actual type annotation itself so maybe this one won't be classified as a bug. I find it at least interesting that this one has changed in 4.7 though :p

**Comment by RyanCavanaugh** [comment]
> I think that it would make sense to keep this parameter optional since it was annotated as such

I agree. The optionality marker is actually meaningful in named function expressions and it seems like it'd be weird to have anonymous and named function expressions type differently.
```ts
const f2: (a: string, b: number) => void = function self(a, b?: number) {
  self(""); // <- should be a legal call
};
```
