### ISSUE TITLE
Generic Constraints are not considered during assignment

### ISSUE THREAD

**Issue by drarmstr** [Microsoft/TypeScript#5494]
When a _constraint_ is applied to a generic type it allows the function or class to properly access members of that type when accessing the type.  However, it does not appear to consider this constraint when assigning to a parameter or variable of the generic type.  The following example demonstrates this error.  I set the parameter type as an array as assigning and manipulating an array is a more common pattern then parameter assignment.

    interface struct {
        foo: number
    }

    function func<T extends struct>(arr: T[]) {
        arr[0].foo;    // OK to read the struct
        arr[0] = { foo: 42 };    // ERROR: type '{foo:number}' is not assignable to type 'T'
        arr[0] = <struct>{ foo: 128 };    // ERROR: type 'struct' is not assignable to type 'T'

        var x: T;
        x.foo;    // OK
        x = { foo: 42 };    // ERROR: type '{foo:number}' is not assignable to type 'T'
    }

Since we know that `T` is a `struct` from the _Generic Constraint_, it should be safe to assign a `struct` to a parameter or variable of type `T`.

**Comment by vladima** [comment]
no, it is not safe. Constraint provides information about some aspects of the type but does not expose exact shape.

```ts
interface struct {
    foo: number
}

let x = [{ foo:1, bar:"1"  }]
function func<T extends struct>(arr: T[]) {
    arr[0] = { foo: 42 };
}
func(x);
x[0].bar.toLowerCase(); // will fail since x[0] does not have bar

function func<T extends struct>(f: (a: T) => void) {
    var x: T;
    x = { foo: 42 };
    f(x);
}
func<{ foo: number, bar: string }>(x => x.bar.toLowerCase()); // will fail since x does not have bar

```
