### ISSUE TITLE
A framework friendly satisfies-like (ability to disregard type information for specific inference).

### ISSUE THREAD

**Issue by Izhaki** [microsoft/TypeScript#54958]
# Suggestion

## 🔍 Search Terms

- Specific
- Satisfies
- Extract type information
- Ignore type information
- Endless other searches on SO and this repo, even tried ChatGPT!

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [X] This wouldn't change the runtime behavior of existing JavaScript code
* [X] This could be implemented without emitting different JS based on the types of the expressions
* [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [X] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Thanks to the great work of @a-tarasyuk, we now have `satisfies` in typescript, for which [the explanation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html) goes:

> TypeScript developers are often faced with a dilemma: we want to ensure that some expression matches some type, but also want to keep the most specific type of that expression for inference purposes.

`satisfies` works great for apps, where the whole codebase is in your control. But a framework wishing to extract specific type information from an argument is at the mercy of consumers using `satisfies`.

In other words, consumers are forced to use `satisfies` in order for the framework to work correctly.

I'll leave it for others to come up with the best solution, but the first thing that came to my mind is a utility such as `Untype` or `Literal` that takes a type and strip any type information - returning what would have been a literal (for the inference of specifics).

## 📃 Motivating Example

A a minimal example can be seen in this [SO thread](https://stackoverflow.com/q/76616298/1179377). 

⚠️ **I think it would be for the benefit of everyone if those who think this is doable without `satisfies` post their solutions on the [SO thread](https://stackoverflow.com/q/76616298/1179377) rather than in this issue**.

Here, I'll share a real use-case.

Consider an editor that can be extended using an arbitrary number of extensions.

```typescript
interface Extension {
  actions: Record<string, Action>,
  // ...
}

interface Editor {
  // a merge between all the `actions` in `Extensions`.
  actions: Record<string, Action>,
}
```

Usage:

```typescript
const extension1: Extension = {
  actions: {
    a: () => {},
    b: () => {}
  }
}

const extension2: Extension = {
  actions: {
    c: () => {},
  }
}

const editor = createEditor([extension1, extension2]);

const { actions } = editor;
// actions = {
//    a: () => {}
//    b: () => {}
//    c: () => {}
// }
```

The last example would work if instead of `:Extension` one uses `satisfies Extension`.

But more often than not extensions will be imported from elsewhere, where authors will have to write:

```typescript
export myExtensions = {
  //..
} satisfies Extension;
```

instead of
```typescript
export myExtensions: Extension = {
  //..
};
```

Further, extensions may be broken down further (say `actions` in a separate script) so each type related to extensions will have to use `satisfies`.

The crude idea is to be able to do something like this:

```ts
// TBuildReturnType gets a type as if `extensions` were provided as a literal (no type information).
function createEditor<T extends Extension[]>(extensions: T): TBuildReturnType<Untype<T>> { ... }
```

## 💻 Use Cases

To overcome this issue, [TipTap uses global module declarations](https://github.com/ueberdosis/tiptap/blob/c30594498e4c8a242ce8e8e8ac552efee9f34148/packages/extension-bullet-list/src/bullet-list.ts#L13-L22), which works if you only have one editor (or identical editors) in your app.

It should also be noted that such feature should help reducing multiple function declarations, such as those (from [redux](https://github.com/reduxjs/redux/blob/80bda95d58f46fb5f6cbf6996ea87d1dcf58a602/src/applyMiddleware.ts)), since you could extract specific type information from an arbitrary list of items:

```ts
export default function applyMiddleware(): StoreEnhancer
export default function applyMiddleware<Ext1, S>(
  middleware1: Middleware<Ext1, S, any>
): StoreEnhancer<{ dispatch: Ext1 }>
export default function applyMiddleware<Ext1, Ext2, S>(
  middleware1: Middleware<Ext1, S, any>,
  middleware2: Middleware<Ext2, S, any>
): StoreEnhancer<{ dispatch: Ext1 & Ext2 }>
export default function applyMiddleware<Ext1, Ext2, Ext3, S>(
  middleware1: Middleware<Ext1, S, any>,
  middleware2: Middleware<Ext2, S, any>,
  middleware3: Middleware<Ext3, S, any>
): StoreEnhancer<{ dispatch: Ext1 & Ext2 & Ext3 }>
export default function applyMiddleware<Ext1, Ext2, Ext3, Ext4, S>(
  middleware1: Middleware<Ext1, S, any>,
  middleware2: Middleware<Ext2, S, any>,
  middleware3: Middleware<Ext3, S, any>,
  middleware4: Middleware<Ext4, S, any>
): StoreEnhancer<{ dispatch: Ext1 & Ext2 & Ext3 & Ext4 }>
export default function applyMiddleware<Ext1, Ext2, Ext3, Ext4, Ext5, S>(
  middleware1: Middleware<Ext1, S, any>,
  middleware2: Middleware<Ext2, S, any>,
  middleware3: Middleware<Ext3, S, any>,
  middleware4: Middleware<Ext4, S, any>,
  middleware5: Middleware<Ext5, S, any>
): StoreEnhancer<{ dispatch: Ext1 & Ext2 & Ext3 & Ext4 & Ext5 }>
export default function applyMiddleware<Ext, S = any>(
  ...middlewares: Middleware<any, S, any>[]
): StoreEnhancer<{ dispatch: Ext }>
```

**Comment by guillaumebrunerie** [comment]
```typescript
// TBuildReturnType gets a type as if `extensions` were provided as a const literal (no type information).
function createEditor<T extends Extension[]>(extensions: T): TBuildReturnType<Untype<T>> { ... }
```
This is already possible since Typescript 5.0, see [const type parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters). The only thing you need to change is to add `const` before the declaration of the generic type `T`, and it will act as if the argument to the function had an `as const`.
```typescript
function createEditor<const T extends Extension[]>(extensions: T): TBuildReturnType<Untype<T>> { ... }
//                    ^^^^^
```

Also, I don’t think you ever *need* to use `satisfies`. You can actually remove all uses of `satisfies` in your code, and it will still typecheck properly. It is just helpful sometimes for catching potential issues, but it only affects the place where it is used, not the rest of the program.

**Comment by Izhaki** [comment]
Thanks @guillaumebrunerie. As for `const` - you are right; I have removed it from the question.

As for satisfies, please feel free to jump in on the [SO thread](https://stackoverflow.com/q/76616298/1179377), ideally with a working example.

Note that the issue here is not about type checking, it is about inference of specifics. Soon as you provide type the argument (say `actions: Record<string, Action>`), whatever you do, typescript will return `Record<string, Action>` for `actions` - never the actual list (`a`, `b`, `c`) - so you could call `actions.invalid` even though it isn't an action in any of the extensions.

**Comment by conorbrandon** [comment]
@Izhaki Does [this](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgDJxAcwK50ygbwChlSRgEBrEOAWwgGcAuZAJQgQHsoATAHgZgooTABpkg4VgB8AbiIBfIkTABPAA4oA+gHEIYAHIVqdRn1TIIAD0ggeDZFAhwenEABtVaDDjwQA2gC64gCCCAiWNhB2DuxcvAJCIuKSItLIALzIBArpWSSkFta29o7Orh5e-qAw0MgAYsBQgpElDuhYuPjiAHR9NXXsLcXRpU4ubp7enX5BgQXIAPzIuvpGVDT0DHxDYOLEpKT+ANLIoMgAFJQQqpwwyGERAD7I17f3jc1g-gDk5BumBg-QIASkCLFOIxirxudwaTUEv3+Ji2wKW8K+SOMm0YwJOgWQLEe+Pkh1yCyJ4Xkak0yD0hmxgPMrVGDnGFSmHV8+CCeRW9PWKLMqDkyhg2BACDAwDcyHwDIBWz4XBALSKUWh7MmXi5XQCgWkF3cPj1zDQIOyC2QKpayJxDiyxpm+AYPScPGwSB2HG4-FSWBSSRkhouiAQ4gQ2CgUAtGXSB0OiZg3EuNrAyDtpjOIGtUagPUzWwtCcTpeQYf8hYgBKykejBcZW0rjerpLLyCU7bKYCjObDbdICn2ChBA+7vYzLYccAcAqn5lFSiIaccmTlaynF38BRLk8VjBYu9IAHdgO53MA6CwfgAjM-uH6iK1Dgov0i7qtmo-l9zWDA8aBrwYGcAAs4EfK0T3vS9aGvTgADdoGEACfmfJ9ByfUF5BtThfx6dxOEwC4Y1kIA) work?

Depending on what you want, it may make sense to throw an error for duplicate nicknames instead of overriding them, but that's what I chose to do.

```ts
interface Language {
   nicknames: Record<string, string>;
}

type _GetNicknames<L extends readonly Language[], Acc extends Record<string, string> = {}> = 
   L extends readonly [infer First extends Language, ...infer Rest extends readonly Language[]]
   ? _GetNicknames<Rest, {
    [K in (keyof Acc | keyof First['nicknames'])]: K extends keyof First['nicknames'] ? First['nicknames'][K] : Acc[K];
   }>
   : Acc;
type GetNicknames<L extends readonly Language[]> = _GetNicknames<L>;

function getNicknames<const L extends readonly Language[]>(languages: L) {
    const nicknames = languages.reduce<Record<string, string>>((acc, curr) => {
        for (const nickname in curr.nicknames) {
            acc[nickname] = curr.nicknames[nickname];
        }
        return acc;
    }, {});
    return nicknames as GetNicknames<L>;
}

const r = getNicknames([
  {
    nicknames: {
      william: 'bill',
    },
  },
  {
    nicknames: {
      alexander: 'sasha',
      william: 'override'
    },
  },
]);
console.log(r);
```

**Comment by RyanCavanaugh** [comment]
I don't understand from the examples here how something like `satisfies` is supposed to fill the gap you're describing.

The example as posted can be typed as:
```ts
const editor = createEditor([{
  actions: {
    a: () => {},
    b: () => {}
  }
},{
  actions: {
    c: () => {},
  }
}]);

declare function createEditor<const K extends string>(obj: ReadonlyArray<{ actions: Partial<Record<K, () => void>> }>): { actions: Record<K, () => void> };

const { actions } = editor;
actions.a();
actions.b();
actions.c();
```

**Comment by Izhaki** [comment]
Sorry for being unclear.

@conorbrandon @RyanCavanaugh both your examples pass untyped objects - absolutely no problem extracting specifics from them.

The problem is with typed arguments, as it seems that typescript has no way introspecting the specifics - it just picks up the provided types.

I've amended the original post usage example to clarify this.

Here is [Ryan's approach with typed arguments](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHZQLxQBQEpMB8UAbsogCYDcAUNYqsBAE4BmAhnNAKIAejqAZxToA3tShQOSNAIBcUAEoQ4yJuQA8A4E3oBzADSwEwgvuoBfWisHAoEPhEHCAjFHm9+QtJihiJU4TlfcQlJeTxCX3MzUKgAI3D8DCIRSwlLcxpqay07Byc0ACZ3fK90LD9JYxl5Sok4RMjUmKgMqxlbCHJEYFUfOCYINkYubt6mbABte08XQxnHMsKAXVws8mUAGzZBqBYAV1Rq9AGhkbHVdRzbAGk8-nIBKC0dVF0CbGQ4gCt5JTZyGhNiAYEwmGwQOoRFVpIJ5AAFHZINibdRKFRqdQ3QwRZIkMjkAhEcwEXC1GGBP7KVQabE4JJEUgUYlZa6+CkyVo+Lo9VQ0AIyAB0bDw-OOAkFcVF1AFgkFcFFQA) and it return `Record<string, Action>`.

Here is the change (and the challenge):

```typescript
const extension1: Extension = {
  actions: {
    a: () => {},
    b: () => {}
  }
}

const extension2: Extension = {
  actions: {
    c: () => {},
  }
}

const editor = createEditor([extension1, extension2]);

const { actions } = editor;
// actions = {
//    a: () => {}
//    b: () => {}
//    c: () => {}
// }
```

Since `extension1` and `extension2` are typed, `actions` ends up as `Record<string, Action>`. You cannot extract `a`, `b` or `c`.

Myself (18 hours) and others cannot find a way around it, other than typing each extension with `satisfies Extension` rather than `: Extension`.

I hope this is clearer now.

**Comment by Izhaki** [comment]
And just spare others the time, I'm aware that a wrapper function would solve this (as you can pass object literals and have `const` and `satisfies` within.

Still don't see it as an elegant (or safe) solution. And while I can elaborate on the whys, it is little relevant to the feature request.

**Comment by guillaumebrunerie** [comment]
Yes, once a variable has been assigned a certain type, then there is indeed no way to extract a more specific type out of that variable (you can’t reexaminate how the variable was created). This is a fundamental property of how any type system works, for many different reasons, for instance performance. You don’t want any use of any variable to need to inspect exactly how that variable (and all other variables it is using, and the variables they are using, etc.) was created, that would make type-checking prohibitively expensive. Also, with such a feature, it would be very easy to start leaking out/depend on implementation details. Plus it would probably not be easy to implement, and it would also be harder to work with (now you need to remember that every variable has two types, the declared type and the "introspected" type). Not to mention that it would need to interact with every other Typescript feature, for instance narrowing.

If you need a more specific type, you need to define your variable with a more specific type to begin with. Either `as const` (no type safety), or `as const satisfies …`, or a wrapper function. I personally think that a wrapper function is rather elegant (and safe), especially if you need specific types only in some places and not in other places, then the wrapper function can give you a way to express exactly that.

**Comment by Izhaki** [comment]
Thanks @guillaumebrunerie for the detailed explanation.

One final comment:

> I personally think that a wrapper function is rather elegant (and safe).

No doubt it will be type-safe, but I meant that it does not prevent consumers from typing the object passed, and I have just checked by if you type a variable and tuck on `satisfies` on it - it is still seen as typed.

**Comment by RyanCavanaugh** [comment]
@guillaumebrunerie said what I was going to say, but I'll restate it again for coverage.

Let's make some terminology
```ts
const x: T = expr;
```
What you have here is `T`, the *annotated type*, `expr`, the *initializing expression*, and (implicitly) `typeof expr`, the type of the initialization expression.

There's no operation that can take `x` and give you back the type of the initialization expression. Once you assign it to `x: T`, it's gone in the wind. I don't think we'd ever add something that says "Give me the type of the expression that initialized this binding". It just doesn't make sense as an operator. It seems like you're stuck on writing `const x: T =` when the `: T` part is making your type inference worse -- maybe that's worth [XY-problem](https://xyproblem.info/)ing on
