### ISSUE TITLE
Reorder the definition of `ts.SyntaxKind.FirstXXXX` enum elements

### ISSUE THREAD

**Issue by h-joo** [microsoft/TypeScript#54950]
# Suggestion

Reorder the definition of `ts.SyntaxKind.FirstXXXX` and `ts.SyntaxKind.LastXXXX` in the enum such that the SyntaxKinds which the value are equivalent to those nodes are assigned after the `FirstXXXX` and `LastXXXX` that the query 

e.g. `ts.SyntaxKind[ts.SyntaxKind.VariableStatement]` returns `VariableStatement` and not `FirstStatement`

(it's currently the other way around)

## 🔍 Search Terms

`SyntaxKind`, `enum`, `order`

Possible duplicate of issue #18062 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Reorder the definition of `ts.SyntaxKind.FirstXXXX` and `ts.SyntaxKind.LastXXXX` such that the SyntaxKinds which the value are equivalent to those nodes are assigned after the `FirstXXXX` and `LastXXXX` that the query 

e.g. `ts.SyntaxKind[ts.SyntaxKind.VariableStatement]` returns `VariableStatement` and not `FirstStatement`

(it's currently the other way around)

## 📃 Motivating Example

Querying `ts.SyntaxKind[ts.SyntaxKind.VariableStatement]` will return `VariableStatement` instead of `FirstStatement` 

## 💻 Use Cases

This will be a minor improvement when debugging into the TypeScript compiler, that it's much more readable when trying to figure out which type a node is for the Nodes which are `ts.SyntaxKind.FirstXXXX`. 

I will file a PR if this request sounds sensible to the owners.

**Comment by RyanCavanaugh** [comment]
We can't. Look at how it's defined in types.ts and try to.

**Comment by jakebailey** [comment]
> This will be a minor improvement when debugging into the TypeScript compiler,

If you're working in the codebase, you probably want to be using the `Debug.format*` helpers, which fixes this up and is generally used anywhere we'd want reverse mapping of nontrivial enums.

e.g., try using `ts.Debug.formatSyntaxKind(node.kind)` to get a friendly string.

Or, use our launch.json template and get debug strings automatically.

**Comment by h-joo** [comment]
@jakebailey thank you, this seems to be something exactly that I needed!
