### ISSUE TITLE
not recognizing path mappings for files with a .jsw extension, even though having set "files.associations": {"*.jsw": "typescript"}

### ISSUE THREAD

**Issue by jhlee111** [microsoft/TypeScript#54957]
Type: <b>Bug</b>
opened with Jetbrains IDE, and all types and modules works properly.

1. create tsconfig file that has "references" and "path" property. something like
"references": [
    {
      "path": "sub/tsconfig.json"
    }
]

2. add  "sub/tsconfig.json" to import types
  "compilerOptions": {
    "typeRoots": ["../"],
    "lib": ["ES2020"],
    "types": ["dist/types/backend", "dist/types/node"]
  }

3. add vscode setting
"files.associations": {"*.jsw": "javascript"}

4. create `test.js` and 'test.jsw"

5. import module and types
compare test.js and test.jsw

VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|. --crash-reporter-id 9f0ac6eb-66f7-4287-8ae9-03c0d2e7316c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.78.0
dscodegpt|Dan|2.1.13
dart-code|Dar|3.66.0
vscode-eslint|dba|2.4.2
githistory|don|0.6.20
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.16.0
copilot|Git|1.93.189
copilot-labs|Git|0.14.884
elixir-ls|Jak|0.15.1
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|1.6.0
live-server|ms-|0.4.8
remote-repositories|ms-|0.36.0
LiveServer|rit|5.7.9
vscode-icons|vsc|12.4.0
volar|Vue|1.8.2
vscode-typescript-vue-plugin|Vue|1.8.2
html-css-class-completion|Zig|1.20.0

</details><details>

</details>

**Comment by RyanCavanaugh** [comment]
TypeScript doesn't read VS Code's file extension settings
