### ISSUE TITLE
Generic boolean type lost

### ISSUE THREAD

**Issue by juanrgm** [microsoft/TypeScript#54968]
# Bug Report

### 🔎 Search Terms

generic boolean callback

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.1.6#code/KYDwDg9gTgLgBDAnmYcBKwDOEA2A3YAHgBUA+OAXjmLlBmADsATTOAIwl2AEMGBYAFBxhcAPxwAFHm44ArsABc1AJSVyvRIJFwlUmfKXFVFdQ0QBuQYIDGEBpngOoASwYBzJRmz4iT12-IqPDU4PAA6GAgAGQgAd2AoAGFuTGAJZRs7BzgGWQBbNgTPLFwCQlyChMDQkPDIgDFnEGAmCQAmDIFbe3gINgArYGsYYu8ygG92ThwlDi5eOABfauCTULC5nCsBAHoduAAFbihuPOB6KDgAcjwruGc8sBxna2cYHEQ4AAsUuAWrjR3JAoMKZHpTXCjUpETY8BgrEIwKDyIA
### 💻 Code

```ts
export type Resolve<T> = T extends boolean
    ? (value: T) => any
    : (value: T) => any;

const string: Resolve<string> = v => v.toLowerCase()
const number: Resolve<number> = v => v.toFixed(2)
const object: Resolve<{ bool: boolean }> = v => v.bool

// Parameter 'v' implicitly has an 'any' type.
const bool: Resolve<boolean> = v => true
```

### 🙁 Actual behavior

```ts
const bool: Resolve<boolean> = v => true // Parameter 'v' implicitly has an 'any' type.
```

### 🙂 Expected behavior

Respect the generic type.

**Comment by MartinJohns** [comment]
This is working as intended. `boolean` is treated as the union type `true | false` and behaves distributive in your conditional type.
