### ISSUE TITLE
`Array.copyWithin()` signature is incorrect - Part II

### ISSUE THREAD

**Issue by tchetwin** [microsoft/TypeScript#54967]
# Bug Report

In https://github.com/microsoft/TypeScript/issues/53334 TypeScript's lib was updated to allow `Array#copyWithin`s 2nd argument `start` to be optional, to match the MDN documentation at that time.

The MDN documentation [has since been updated](https://github.com/mdn/content/pull/27296) to match [the spec](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.copywithin), meaning TypeScript 5.1's types are incorrect.

To remediate: a reversion of https://github.com/microsoft/TypeScript/pull/53340 is needed. This might be a _slightly_ breaking change for anyone that adopted TypeScript 5.1 and started (incorrectly) relying on the parameter being optional.

### 🔎 Search Terms

copyWithin

### 🕗 Version & Regression Information

- This changed between versions 5.0 and 5.1

**Comment by DanielRosenwasser** [comment]
Should be a quick and easy PR if you want to fix it up.

**Comment by Mburnand-tech** [comment]
I am going to pick this up

**Comment by shubhamshd** [comment]
@DanielRosenwasser @tchetwin @Mburnand-tech I would also like to give it a try, if it's not against the community values!!!

**Comment by Mburnand-tech** [comment]
@shubhamshd Go for it! I've struggled to correct the tests so they pass.

**Comment by shubhamshd** [comment]
@DanielRosenwasser  please review the changes in pr and let me know, if anything needs to be corrected, thanks!!!

**Comment by shubhamshd** [comment]
Apologies team, but is there any scheduled time for the pr to get merged?
