### ISSUE TITLE
Conditional types work differently inlined and with generics

### ISSUE THREAD

**Issue by felds** [microsoft/TypeScript#54974]
# Bug Report

I was trying to replicate the `Extends` utility type (before knowing `Extends` exists) when I stumbled on this.

Creating my own utility type worked ok, whereas inlining the code would give out a different result.

Shouldn't both approaches result in the same type?

### 🔎 Search Terms

Inline extract discriminated union type never

### 🕗 Version & Regression Information

- This happens since v 3.3.3 (oldest in the Playground) up until 5.2.0 Nightly 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/C4TwDgpgBAKhAewAKB7AzsKBeKBvAUFEVKJABICGAdgCYA2EATgFxQBEwCwbA3IccACWwBqwyNBVAOZ9iUAMYowIMcAnS+AX3yloSABYpgKVBmx5+RXZVoMW7MIeO9LUAK6M6q9TPzad4HromDhwiKaYAD5QBkYmwfj4APRJUFyMFPJC0lAARiBQVBRCAG7QbkJ0wgW6AZBQAGKMKAC2AHLFgmXmAKKIGVkAPBEANHjW1PRMrADkjnEzmgB8yalEAHoA-Ikpaf2Z2VJ5BfJuGK3uldUkgXXQAMJnxi19ageDMGMAqkvmMHucWhoKBfKCbWBQVhUCBlRh3RrNFqPc4tczI56vAbAYbBMa4Ca2aZQOZOFCLFa7DbbVYArGSI6SKrQ+EASSoTOgOAiAIgQPGgRsU3sJIWmjBMWCkMKMKYNKpiSAA)

### 💻 Code

```ts
type TextPost = {
    typeHandler: "text";
    title: string;
    copy: string;
}
type PhotoPost = {
    typeHandler: "photo";
    url: string;
}

type Post = TextPost | PhotoPost
// extracting by native utility type
type FromNative = Extract<Post, {typeHandler: 'photo'}>
//   ^? type FromNative = { typeHandler: "photo"; url: string; }

// extracting by custom utility type
type CustomExtract<T, U> = T extends U ? T : never
type FromCustom = CustomExtract<Post, {typeHandler: 'photo'}>
//   ^? type FromCustom = { typeHandler: "photo"; url: string; }

// extracting inline
type Inline = Post extends {typeHandler: 'photo'} ? Post : never
//   ^? type Inline = never
```

### 🙁 Actual behavior

Inline and utility types have different behaviors.

### 🙂 Expected behavior

Using an inline type should be the same as using the same type as an utility type.

**Comment by MartinJohns** [comment]
They have different behaviours, just as documented.

[Distributive Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types)

> When conditional types act on a generic type, they become *distributive* when given a union type.
