### ISSUE TITLE
tsconfig.json not being read by tsc

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#5497]
Given:

``` json
// tsconfig.json
{
    "compilerOptions": {
        "noImplicitAny": true,
        "module": "commonjs"
    }
}
```

``` js
// main.ts
/// <reference path="./node_modules/immutable/dist/immutable.d.ts" />
import * as Im from 'immutable';
```

``` json
// package.json
{
  "private": true,
  "dependencies": {
    "immutable": "^3.7.5",
    "typescript": "^1.6.2"
  }
}
```

My `tsconfig.json` doesn't appear to be read by `tsc`:

```
$ ./node_modules/.bin/tsc main.ts
main.ts(1,1): error TS1148: Cannot compile modules unless the '--module' flag is provided.
```

Am I missing something?

**Comment by JKillian** [comment]
If you specify input files, `tsconfig.json` is ignored. (I agree this is slightly surprising behavior.) 
Check out [this page](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) for more info on `tsconfig.json`.

**Comment by OliverJAsh** [comment]
Okay, that is surprising. Thanks

**Comment by mhegazy** [comment]
The other option is to use `--project <path to tsconfig.json directory>` instead.

**Comment by martellaj** [comment]
For anyone reading this now, it seems as if the `--project` option is no longer supported.

**Comment by mhegazy** [comment]
> For anyone reading this now, it seems as if the --project option is no longer supported.

@martellaj that is not correct. `--project`/`--p` is still a supported feature. as a matter of fact, starting with TS 1.8, `--project` now supports a full file path. see https://github.com/Microsoft/TypeScript/issues/2869

**Comment by martellaj** [comment]
@mhegazy, my bad! My PC got into a weird state where I had a [second version of TypeScript installed and that's where `tsc` was mapped to](http://stackoverflow.com/questions/32497809/windows-10-tsc-error-ts5007-cannot-resolve-referenced-file-tsconfig-json). I'll edit my previous comment.
