### ISSUE TITLE
Go to Definition assumes use of rest parameters when spread syntax is used with empty array unless of type `[]`

### ISSUE THREAD

**Issue by aweebit** [microsoft/TypeScript#54977]
# Bug Report

### 🔎 Search Terms

- function declaration
- function overload
- rest parameters
- spread syntax
- Go to Source Definition

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about spread parameters handling for overloaded functions.
- Only tested in TS Playground with v5.1.6. The behavior is unlikely to have been different earlier.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABKSAKAlALkQNzjAEwG4AoFaeJc1AOjoEMAnAcwGdt6wBPAbQF0sufMRJlwFBMnG0GLdok68B2PIUQBvAL6jqdGv3RFEAemPIYjVlEQEAphAA2TerEkALGMzcPPbqLYIxND1UfgVWBW4DQxMzVnsEAht7J0YXSkQPLx8vf0CgA)

### 💻 Code

```ts
function func(): void;
function func(...args: any[]): void;

function func(...args: any[]): void {}

func(...[]); // first declaration highlighted
func(...([] as any[])); // second declaration highlighted
```

### 🙁 Actual behavior

An array of type other than `[]` is assumed to always lead to the overload with rest parameters when Go to Definition is called, despite the fact that it can be empty.

### 🙂 Expected behavior

A list with both overloads opens up.

**Comment by Andarist** [comment]
TypeScript might compute an "effective arguments list" at times when you are using spreads. You are effectively passing it 0 arguments with `...[]` and that matches the first overload. An empty array is considered to be a 0-length tuple and that's not the same as `any[]`.

I think this works as expected.

**Comment by aweebit** [comment]
It is perfectly fine that the first overload is chosen for the `[]` type. What I find problematic is the assumption that all arrays of type `any[]` are not empty. I used the empty array explicitly to illustrate it, but it could an array whose contents we are not aware of, so either of the overloads could apply.

**Comment by aweebit** [comment]
It is not about overload matching for a particular function call with particular parameter values, it is about the _Go to Definition_ which, as far as I can tell, only works with symbols and not values. I see now that I forgot to mention it additionally in the issue description, but it is what I was talking about. Try Ctrl + clicking the second function call in the playground and you'll see the second declaration highlighted, but instead, a list with both declarations should open up.

**Comment by Andarist** [comment]
Ye, I know what you are saying here - but the fact is that Go to Definition actually goes to the resolved signature (can also be tested using a different demo [here](https://www.typescriptlang.org/play?ts=5.1.6#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAooAueAZwxi1QHMBKcqm+gKFElgRXWzwLEy8AOQsRTeKmQBbAEYgYbNmDxV4cCvAC8gomOoS2AemPxz8AHoB+NkA)). This behavior is actually quite helpful because you can easily jump to the matched overload - and if you need to look at others they usually are just close to it.

**Comment by fatcerberus** [comment]
The spread/rest is IMO a red herring here.  This is analogous to writing:

```ts
declare function foo(x: string): void;
declare function foo(x: string | number): void;
declare const bar: string | number;
foo(bar);  // go to def picks second overload
```

Yes, *sometimes* it will match the first overload *at runtime* (ignoring the fact that overloads are pure type info and don't exist at runtime, except insofar as they are encoded in the single function implementation), just as an `any[]` might *sometimes* be `[]` at runtime, but the call only resolves to the `string | number` overload regardless.  Same principle.

**Comment by aweebit** [comment]
Thanks to both of you for clearing up my misconceptions!
