### ISSUE TITLE
`as any` unexpectedly breaks function parameter type inference

### ISSUE THREAD

**Issue by sodatea** [microsoft/TypeScript#54987]
# Bug Report

### 🔎 Search Terms

as any
type casting
function parameter
generic type inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics and any and type casting

### ⏯ Playground Link

- [Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATgYQPYDsBmBLA5lAXigG8AoKKYAQ0VwmAC4oAiCOAVmagB8W2AmAAwBGTjz5x0EAB7BmAbnJQcAGwgA5KgFsITABSZUiLVUZQ4wRNnS4AlIQB85y9dyKAvotCRYCFBhxcAFFpMCNgQl8kNCw8cT09CHQANyZUACMAKwgAY2B7Aid4aIC8W0VSTABXdDzsDCgAEwgcKRjAgB4AFSgZYCTGuCj-WODQ8Ic9HNLcJi7bOZIlRHoqxHQoadGPUmbWiHa8BIKnPTIKalp6JlYOZgAaJVUNbV0oAyMTfMcoAANrZrSAB0ABJiIZjKZCAQiLcuAB+FhaTJwLg3HIo5juX6Pdy2cqkQl7awHGYJc6UGh0My3TiPCgAegZUAAyqgdAALVAAd0oHOg3mg1kwSBWtWgqEwfOwQ2qtWA9Q26Vy7LYUGs00QKzyT2wak0On0EK+Jz+AJkoPBnyhMNhbARSMxUHRmOxuPxUCoQyo6BAFSZrK5VRUjXQAHIIqKjFB+St7r1sMBY7sWiTDrhjj8zkpLtSbmw6br9a8jdbvoUzehAZbjTaYRIHcxkajnSwMai3aQ8fYvZ7fYogA)

### 💻 Code

```ts
type UserConfig = {
  target: "es5" | "es2015" | "esnext";
  fileName: (format: string) => string;
};
type UserConfigExport = UserConfig | ((env: object) => UserConfig);

function defineConfig<T extends UserConfigExport>(config: T): T {
  return config;
}
defineConfig(() => ({
  target: "es5",
  fileName: (format) => `index.${format === "es" ? "mjs" : "cjs"}`,
}));


defineConfig(({
  target: "es5",
  // Somehow the type inferrence of this function becomes incorrect
  fileName: (format) => `index.${format === "es" ? "mjs" : "cjs"}`,
})) as any;

// Shouldn't error here, either
defineConfig(() => ({
  target: "es5",
  fileName: (format) => `index.${format === "es" ? "mjs" : "cjs"}`,
})) as any;
```

### 🙁 Actual behavior

The ones with an `as any` typecasts failed.

### 🙂 Expected behavior

All `defineConfig` calls should pass.

**Comment by RyanCavanaugh** [comment]
Because `T` is in the return position, a contextual type on the function call acts as an inference candidate, so having `as any` here is the same as if you had written
```ts
defineConfig<any>(() => ({
  target: "es5",
  fileName: (format) => `index.${format === "es" ? "mjs" : "cjs"}`,
}));
```
which displays the same behavior.

**Comment by sodatea** [comment]
Thank you so much for the explanation!
It does make sense once I replace `as any` with `<any>`.

I didn't make the connection because the code came from a refactor of the function from non-generic to generic types 😂
