### ISSUE TITLE
Add jsdoc support for function return type in JavaScript

### ISSUE THREAD

**Issue by xiaoxiangmoe** [microsoft/TypeScript#54985]
# Suggestion

## 🔍 Search Terms

 
jsdoc
## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

```ts
function fun(level: 'warn' | 'error', ...args: string[]): 'foo' | 'bar' {
    return 'foo';
}
```
We can write the corresponding js code

```js
// example 1
/**
 * @param {'warn'|'error'} params 
 * @param  {...string} args 
 * @returns {'foo' | 'bar'}
 */
function fun(params, ...args) {
    return 'foo';
}
```
 Or

```js
// example 2
function fun(/** @type {'warn'|'error'} */ level, /** @type {string[]} */ ...args) /** @type {'foo'|'bar'} */ {
    return 'foo';
}
```

Or

```js
// example 3
const fun = (/** @type {'warn'|'error'} */ level, /** @type {string[]} */ ...args) /** @type {'foo'|'bar'} */ => {
    return 'foo';
}
```
![image](https://github.com/microsoft/TypeScript/assets/8111351/74422395-3870-41bc-b002-51c7d13edfe3)
![image](https://github.com/microsoft/TypeScript/assets/8111351/b8c5a0d4-76fc-4a44-8c96-14ddac9f4ed0)

But in example 2 and 3, the return type seems to be ignored.

Can we add support for jsdoc function return type?

**Comment by thorn0** [comment]
Use `@returns`. See https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#param-and-returns

**Comment by xiaoxiangmoe** [comment]
Here is another example:

```js
/**
 * @template T
 * @param {(mode : 'dev'|'prod') =>T} arg
 * @returns {[T]}
 */
function foo(arg) {
    return [arg('dev')];
}

const bar1 = foo(
    /**
     * @returns {'a'|'b'}
     */
    (input) => {
        return 'a';
    },
);

const bar2 = foo((input) /** @type {'a'|'b'} */ => {
    return 'a';
});

```

In TypeScript, we may write

```ts
const bar2_ts = foo((input): 'a'|'b' => {
    return 'a';
});
```
The practice of bar2 is closer to the habit of TypeScript (bar2_ts) than bar1

**Comment by RyanCavanaugh** [comment]
I don't see how this is an improvement, really. You can already use `returns`, can already write this,
```js
const fun = (/** @type {'warn'|'error'} */ level, /** @type {string[]} */ ...args) => {
    return /** @type {'foo'|'bar'} */('foo');
}
```
and the line length implied by putting `@type` at the `=>` doesn't seem like something people would do
