### ISSUE TITLE
Extending nested arrays suddenly stopped working

### ISSUE THREAD

**Issue by JDansercoer** [microsoft/TypeScript#54983]
# Bug Report

### 🔎 Search Terms

nested array

### 🕗 Version & Regression Information

- This changed between versions `4.3.5` and `4.4.2`

### ⏯ Playground Link

[Failing playground](https://www.typescriptlang.org/play?ts=4.4.2#code/JYOwLgpgTgZghgYwgAgMIAs5TAZTHSZAbwChlzkAbOAIwkoGcAuZBsKUAcwG0BdAbjIUAJgTgMIYZsm5CKFUvKUVqdSizYcQnQcuU1EAa05QA9gFcQw1KcqmoG9lz7IAPqyfbde+elMA3aAAhIxMLKxs7Bw8tHl43GK5vH3JRfBZkAApNLlcQcwBbOigASj5kpQBfOWQBEmqSMABPAAcUAH00uBxJABVWlABeNExsPAIIbgByLokpKd5uAAY6xoHkdoMoDCwwABExHrB+tuRhzsO+9YAyYjkt3vRgBEMQCAZpfKLoQQaIAA8WvYwMhmqcQttRuNCMMdmN8IRbopkLNJNIAIJQKBwJoAHk2WDh+0uxwGAD56iQSAhTCA2KD3mAWBC4dChncVLR6NJpjBTKYpgAaZBTLYLQVyVFSFiyZTIvSqegsKZ8gUSlIGF5hSzWWz2ZUAYhgEGNxqFNSUfkCUBCWrMOsi+pFRpgrtd5pSXRlUzgQpFNHFFvkDyeLzeHxYAGZ1VUY7V6kA)
[Correct playground](https://www.typescriptlang.org/play?ts=4.4.2#code/JYOwLgpgTgZghgYwgAgMIAs5TAZTHSZAbwChlzkAbOAIwkoGcAuZBsKUAcwG0BdAbjIUAJgTgMIYZsm5CKFUvKUVqdSizYcQnQcuU1EAa05QA9gFcQw1KcqmoG9lz7IAPqyfbde+elMA3aAAhIxMLKxs7Bw8tHl43GK5vH3JRfBZkAApNLlcQcwBbOigASj5kpQBfOWQBEmqSMABPAAcUAH00uBxJABVWlABeNExsPAIIbgByLokpKd5uAAY6xoHkdoMoDCwwABExHrB+tuRhzsO+9YAyYjkt3vRgBEMQCAZpfKLoQQaIAA8WvYwMhmqcQttRuNCMMdmN8IRbopkLNJNIAIJQKBwJoAHk2WDh+0uxwGAD56iQSAhTCA2KD3mAWBC4dChncVLR6NJpjBTKYpgAaZBTLYLQVyVFSFiyZTIvSqegsKZ8gUSlIGF5hSzWWz2ZUAYhgEGNxqFNSUfkCUBCWrMOsi+pFRpgrtd5pSXRlUzgQpFNHFFvkDyeLzeHxYAGZ1VUY7V6kA)

### 💻 Code

```ts
interface ChartState {
    labels: string[];
    datasets: [
        {
            label: string;
            backgroundColor: string[] | string;
            hoverBackgroundColor: string[] | string;
            data:  (string|number)[];
        }
    ];
}

type _dataSetType = ChartState['datasets'][0];

type _barChartDataSetType = _dataSetType & {
   barThickness: number;
}

export type BarCharState = ChartState & {
  datasets: Array<_barChartDataSetType>
}

const test: BarCharState = {
   labels: ['foo', 'bar'],
   datasets: [
      {
         label: 'foo',
         backgroundColor: '#fefefe',
         hoverBackgroundColor: '#ffffff',
         data: ['a', 'b'],
         barThickness: 3,
      },
   ]
}
```

### 🙁 Actual behavior

It does not correctly merge the two types

### 🙂 Expected behavior

The resulting type displays incorrect behavior

**Comment by geoffreytools** [comment]
It could be a bug related to [this issue](https://github.com/microsoft/TypeScript/issues/53355) but `ChartState/datasets` should be defined as an array. This intersection between a tuple and an array does not make much sense and is best avoided.

**Comment by RyanCavanaugh** [comment]
It really seems like you wrote `[T]` thinking it meant `T[]`. This works as expected:
```ts
interface ChartState {
    labels: string[];
    datasets: 
        {
            label: string;
            backgroundColor: string[] | string;
            hoverBackgroundColor: string[] | string;
            data:  (string|number)[];
        }[]
    ;
}
```
