### ISSUE TITLE
Suggestion: function declarations should have way to reuse established types.

### ISSUE THREAD

**Issue by tbremer** [microsoft/TypeScript#54989]
# Suggestion

## 🔍 Search Terms

- is:issue function declaration label:Suggestion 

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Would love it if I could re-use some defined function type without have to use a function expression. Function declarations should allow for a generic after the keyword `function` that defines it's arguments and return type.

Example:
```typescript
type Formatter = (s: string) => `FORMATTED: ${s}.`

// today you have to use a function expression
const fmt:Formatter = (str) => { … }


// ideally something like this is possible
function<Formatter> (str) { … }
```

Playground link with sample code: https://www.typescriptlang.org/play?#code/PTAEHcHsFcBsBNS0gNwKagIYUwT1AC6SjxoDGsmAThgQBYCWAzqAGbQB2ZBDkHoTBgHMOmAtBoRgxOphQMOQwsWhMM2dlx59QaAB4AHGk0E7IVUDQC04KgwK06GUqwX3eHAHQAoELs9CngBcbJzcHgA8AHJ8UXCUAEawaBEAsrgAkhwOVKyYZGgA2gDk+docTMUAuiUMpNkMrLjVAHwtoHVoDU0AFACUoADeoIBkBKAAvt6a4Tqd3bj9Q6DAAFSjoCtgk36gu3u7AHoA-N7eZHxMBB31PE0ATCExHHGwiclpmdlouflFpTMVaq1G6NZpVdoAXlAiwh7WGq3WmwmvjA+32x1OChyeQKoHSWWxvyG3l2ZQ8TBCgxJezmt1wRxCPTqIUudkUABpdABbTAMWAMgQENlCAaw0AoSB1ADc1N2xjQBAFMPaEulssIaEuStFKsl8Blu0m4yAA

## 📃 Motivating Example

1. See playground link above.
2. This could enable more concise function overloads ([example from docs](https://www.typescriptlang.org/docs/handbook/2/functions.html#writing-good-overloads)).

```typescript
type LenString = (s: string) => number;
type LenArr = (arr: any[]) => number;

function<LenString | LenArr> (x) {
    return x.length;
}
```

## 💻 Use Cases

- Allows for type re-use in places where function expressions are unnecessary. 
- Better ergonomics when you have interfaces that define functions.
- Concise function overloads

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/22063

**Comment by tbremer** [comment]
> Duplicate of #22063

Thank you @whzx5byb! I assumed this was suggested before, but could not find it. I'll close this issue and add a comment with my examples as well.
