### ISSUE TITLE
JSX and ES2015 syntax highlighting issues in VS2013 and 2015 Community

### ISSUE THREAD

**Issue by kjendrzyca** [Microsoft/TypeScript#5498]
Few weeks ago I installed VS2015 Community edition along with TypeScript 1.5 for ES2015 and JSX support. I was really happy to see that my simple JSX files are recognized as a valid JS.

This code is ok and VS doesn't have a problem with it:
```
let Edit = React.createClass({
    render () {
        
            <div className="Edit">
                Editing something of id: {this.props.id}
            </div>
        );
    }
});

let mainContainerDiv = document.getElementById('main-container');
React.render(<Home />, mainContainerDiv);
```

Yesterday I've updated TypeScript tools to 1.6 and tried to run more complicated example. I encountered some syntax errors:
1) Don't know really why this is not ok:
![image](https://cloud.githubusercontent.com/assets/7491025/10894987/ee3eeeba-81b1-11e5-8dbe-b0ee0e593f00.png)

2) JSX doesn't accept import statements:
![image](https://cloud.githubusercontent.com/assets/7491025/10895062/67109424-81b2-11e5-890c-2f02cdbe854e.png)

I've seen screenshots where people are using import statements in JSX and it works fine. But it doesn't work for me. I've already tried to:
- reinstall typescript
- revert back to 1.5
- reset all vs settings

Additional info:
- It is possible that in the past I was trying to hack VS to give me at least partial support for JSX (before TS1.5 was released), but as far as I remember all changes were reverted
- I have also VS2013Pro installed with TypeScript tools 1.6. ES2015 and JSX doesn't work there really well:
![image](https://cloud.githubusercontent.com/assets/7491025/10895190/2487cb58-81b3-11e5-85f4-8af9775fed15.png)

![image](https://cloud.githubusercontent.com/assets/7491025/10895243/74d6ddc4-81b3-11e5-8ef4-5f2cc2a99ecd.png)

I don't know where to search for info. I've tried StackOverflow and searched through the issues here. No luck so far.

**Comment by mhegazy** [comment]
@TheOneYouDontLike one thing to note, TypeScript support in VS opperats on `.ts` and `.tsx` files. from all your screenshots you seem to be using `.js` an `.jsx` files; so the update to TypeScript has no impact there either positive or negative.

let me ping the owners of the JSX support in VS: @madskristensen, and @sayedihashimi

**Comment by mhegazy** [comment]
If you already have TypeScript project, you can just add your JSX code in a `.tsx` file, and you should have full ES6 support along with types. here is a sample for using JSX: https://github.com/Microsoft/TypeScriptSamples/tree/master/jsx

**Comment by JaxCavalera** [comment]
I've been trying to get both Syntax Highlghting and Intellisense working in VS 2015 Community, I even updated to RC1 but still no dice.

I would have thought that with react support you could type something like :
React.Component

And when you type the "." it brings up a list of possible props to choose from but instead I get an intellisense error and all my code is highlighted as invalid syntax.

**Comment by madskristensen** [comment]
@JaxCavalera There was an issue in Visual Studio 2015 RTM where the JS/JSX editor in a web/asp.net project wouldn't recognize react.js when installed through Bower. That has been fixed and will be in the next update to the ASP.NET 5 tooling release

**Comment by JaxCavalera** [comment]
@madskristensen Hmm would this be the same if I had installed react and react-dom using NPM and am using the "Open Website" option.

I also have been unable to find a list of which Extensions beyond vanilla VS 2015 Community Update RC1  which would be required to get this functionality working (if any).  I'm gathering that there is an ASP.NET tooling extension?

Apologies if this is a poorly constructed question, I was working with netbeans and notepad++ prior to Visual Studio and am still trying to work out how extensions work etc.

**Comment by madskristensen** [comment]
You would have to add a reference to the file from your .js file for Intellisense to light up. Example:

```js
 /// <reference path="../node_modules/react/react.js" />  
```

You can do this globally as well by utilizing the _references.js file. Read more about that here http://madskristensen.net/post/the-story-behind-_referencesjs

**Comment by Pelice** [comment]
this was usefull for me: http://stackoverflow.com/questions/34097915/visual-studio-2015-jsx-es2015-syntax-highlighting
