### ISSUE TITLE
Parser failure when an argument is named "in"?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/TypeScript#5499]
Arguments are not allowed to be named `in` ?
```
class Greeter {
	private static filter(in:any[]): any[] {
		throw new Error('Not implemented');
	}
}
```

![image](https://cloud.githubusercontent.com/assets/5047891/10896840/e0bd5d7a-81bc-11e5-868b-68d879e5b80b.png)

**Comment by RyanCavanaugh** [comment]
`in` is not a valid parameter name in JavaScript.

http://es5.github.io/#x7.6.1
