### ISSUE TITLE
[DOCS] Use issue forms instead of issue templates

### ISSUE THREAD

**Issue by Panquesito7** [microsoft/TypeScript#54996]
# Suggestion

The current templates are the old version of the issue templates. We can convert the issue templates to issue forms for easier management and better issue creation.
Many projects and repositories have been using it, and they are beneficial. It appears there are only a few templates to convert to issue forms (if no new ones are added).

## 🔍 Search Terms

`issue forms`, `issue templates`

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Convert the issue templates to issue forms.

## 📃 Motivating Example

I'm not 100% sure this fits this issue, but this would improve the issue management and make it easier for maintainers to check the issues and for users to report and fill in the required fields.

## 💻 Use Cases

1. **What do you want to use this for?**

This will be used by many people who create issues and will make everything easier and better.

2. **What shortcomings exist with the current approaches?**

There are no required fields or use of advanced form settings, which makes it very limited when creating issues or creating new types of templates/forms.

3. **What workarounds are you using in the meantime?**

Issue templates which is the current way of creating issues (some templates are using issue forms now, though).

**Comment by RyanCavanaugh** [comment]
Yeah, this is something that's been on my mental todo list for a while.

**Comment by fatcerberus** [comment]
Is `Help Wanted` appropriate here, seeing as (afaik) this is something only the repo maintainers can do?

**Comment by jakebailey** [comment]
They're just files in the `.github` directory; anyone could submit them.

**Comment by Panquesito7** [comment]
May I work on this, or should this be assigned to someone else?

**Comment by RyanCavanaugh** [comment]
Feel free to

**Comment by Panquesito7** [comment]
Thanks! Working on it. 🙂
