### ISSUE TITLE
github actions pnpm build error ts2322 , But it's normal locally

### ISSUE THREAD

**Issue by lixiaofa** [microsoft/TypeScript#54998]
# Bug Report

github actions pnpm build error ts2322 , But it's normal locally

error info: Error: ../../packages/hooks/use-forward-ref/index.ts:20:5 - error TS2322: Type '(el: T) => void' is not assignable to type 'ForwardRefSetter'. Types of parameters 'el' and 'el' are incompatible. Type 'T' is not assignable to type 'T'. Two different types with this name exist, but they are unrelated. 'T' could be instantiated with an arbitrary type which could be unrelated to 'T'.

20 setForwardRef, ~~~~~~~~~~~~~
![image](https://github.com/microsoft/TypeScript/assets/23230215/525205d4-6c05-4f73-9789-ac2c949c6674)

https://github.com/lixiaofa/fast-plus/actions/runs/5532747753/jobs/10107559848
### 🔎 Search Terms

ts2322

### 🕗 Version & Regression Information

 "typescript": "^5.1.6",

### ⏯ Playground Link
https://github.com/lixiaofa/fast-plus

### 💻 Code

https://github.com/lixiaofa/fast-plus/actions/runs/5532747753/jobs/10107559848
### 🙁 Actual behavior

 pnpm build error ts2322 in github actions , But it's normal locally

### 🙂 Expected behavior

npm build  no error in github actions

**Comment by MartinJohns** [comment]
That doesn't sound like a problem with TypeScript. It's either an issue with pnpm (which is not officially supported by TypeScript) or just a version mismatch.

**Comment by lixiaofa** [comment]
> That doesn't sound like a problem with TypeScript. It's either an issue with pnpm (which is not officially supported by TypeScript) or just a version mismatch.

@MartinJohns 
I also installed it locally through PNPM

**Comment by jakebailey** [comment]
> pnpm (which is not officially supported by TypeScript)

I'm not sure where you got that idea; I don't think we have made any claims like this and loads of people successfully use pnpm with TypeScript. I'm even working on converting DT to a pnpm monorepo.

**Comment by lixiaofa** [comment]
> > pnpm (which is not officially supported by TypeScript)
> 
> I'm not sure where you got that idea; I don't think we have made any claims like this and loads of people successfully use pnpm with TypeScript. I'm even working on converting DT to a pnpm monorepo.

My project is also a pnpm monorepo.
Can you help me
@jakebailey 
see  https://github.com/lixiaofa/fast-plus/actions/runs/5532747753/jobs/10107559848

**Comment by MartinJohns** [comment]
> I'm not sure where you got that idea; I don't think we have made any claims like this and loads of people successfully use pnpm with TypeScript.

I could swear there was an open issue for supporting it, and that's also why pnpm has to monkey patch something with every new TypeScript version. I might be mixing things up.

**Comment by Josh-Cena** [comment]
Yes, you are probably confusing pnpm with Yarn berry :)

**Comment by MartinJohns** [comment]
Thank you @Josh-Cena, that's exactly what happened!

**Comment by RyanCavanaugh** [comment]
This is a pretty big & involved repo. We'd really need a minimal repro to be able to investigate. Most likely, there's a file ordering issue where your local build and CI builds are seeing the files in a different oreder. In rare cases, this can cause errors (this is expected and not a bug since e.g. additional overloads appear in reverse-file order).

**Comment by lixiaofa** [comment]
> This is a pretty big & involved repo. We'd really need a minimal repro to be able to investigate. Most likely, there's a file ordering issue where your local build and CI builds are seeing the files in a different order. In rare cases, this can cause errors (this is expected and not a bug since e.g. additional overloads appear in reverse-file order).

@RyanCavanaugh 
Can you give me some ideas? What may be the problem

**Comment by lihaorangood** [comment]
did ypu fix the error i have the same question , if you fix it can you give me some idea thanks
![image](https://github.com/microsoft/TypeScript/assets/50411904/32e47160-815d-4c36-9cc0-1ee8257ef194)
