### ISSUE TITLE
Negative constant enums return number when toString is called

### ISSUE THREAD

**Issue by DustinBrett** [microsoft/TypeScript#54992]
### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.1.6#code/MYewdgzgLgBApmArgWxgFTtAok1BvAKBmJgEEYBeGARgBoiSAhSmAWmoIF8CDRIQANnAB0AkAHMAFA2JQAngAc4IAGYwAylABOASzBSM2XMNIBKeiRjylq9Jig4UJ4VBCbd+yaYLfe4CIIiYlIyVorKau56BvaOyMKM5qHWEXZGTowubtrRXj5AA

### 💻 Code

```ts
const enum TestEnum {
    A = 1,
    B = -1
}

// "string",  "string" 
console.log(
    typeof String(TestEnum.A),
    typeof TestEnum.A.toString()
)

// "string",  "number" 
console.log(
    typeof String(TestEnum.B),
    typeof TestEnum.B.toString()
)
```

### 🙁 Actual behavior

Constant enums which use negative numbers will return type of `number` when `.toString()` is called.

### 🙂 Expected behavior

A `string` type should be returned

**Comment by fatcerberus** [comment]
If anyone's wondering how this happens, it's because the emit is `-1 .toString()` - property access has higher precedence than negation.  So effectively what happens is this logs the result of `typeof -(1..toString())` -- which is `number`.

**Comment by RyanCavanaugh** [comment]
I'm honestly shocked this has been shipping since at least 3.3, possibly forever, without getting noticed 😰

**Comment by fatcerberus** [comment]
I don’t think people generally call methods on enum values, since they’re usually just meant to be used as sentinels.  Probably even fewer people still use negative values.
