### ISSUE TITLE
Incorrect ES5 transpilation for multiple optional properties with default values

### ISSUE THREAD

**Issue by frigus02** [microsoft/TypeScript#55006]
# Bug Report

ES5 transpilation for multiple properties with default values changes runtime behavior. It seems this requires a rest parameter and a static class field to reproduce.

### 🔎 Search Terms

ES5, TypeError

### 🕗 Version & Regression Information

- This changed between versions v4.9.5 and v5.0.4
- It's fixed in 5.2.0-beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?target=1#code/MYGwhgzhAEBCkFNoG8C+AoAlgOwC4ICcAzMYJeCBWEAe2AGsAFMAsAWxmXWmm3YQD8ALmgRcBHAHMA3N2g0ADrkw0+IYdABGNGiARhssjAgAeCmgVzRQkGBSq0G0U-mwATO4hRyFAV00gmMCiuGDKwQByAIIAsgCi0AC80ABE9tR09CmyPH4BQbz8ImIS2DI+-oHBisqqYCAi2rr6huhywKolvsC4FgAUXDw8fGxIyQDk4wA0cjw1KmpJ0CQglDND0AB02wos-PgEEHKoIumOTHscS2gAlN4bEL4KhH03OUO4ABaYEJsjY4VRu8eF8fpt5nUQEsIWp3hhUEA)

### 💻 Code

```ts
class Base {}
interface BaseBlockParams {
  name?: string;
  optional?: boolean;
}
export class BaseBlock extends Base {
  public static NAME = "BaseBlock";
  public name: string;
  public optional: boolean;

  constructor({
    name = '',
    optional = false,
    ...parameters
  }: BaseBlockParams = {}) {
    super();
    this.name = name;
    this.optional = optional;
  }
}
```

### 🙁 Actual behavior

Output (formatting mine):

```js
// v4.9.5
var _b = _a.name, name = _b === void 0 ? '' : _b,
    _c = _a.optional, optional = _c === void 0 ? false : _c,
    parameters = __rest(_a, ["name", "optional"]);

// v5.0.4 and v5.1.6
var name = (_a = _a.name, _a === void 0 ? '' : _a),
    optional = (_b = _a.optional, _b === void 0 ? false : _b),
    parameters = __rest(_a, ["name", "optional"]);
```

The second version is wrong. It reassigns `_a` and then accesses `optional` on the reassigned value, which never has an `optional` property.

This means `new BaseBlock()` is a TypeError at runtime and `new BaseBlock({name: '', optional: true})` has `optional` set to `false`.

### 🙂 Expected behavior

What v4.9.5 did and what v5.2.0-beta does.

I realize it's slightly odd to file a bug for a fixed issue. My question is: Do you know which commit fixed this? We might want to cherry-pick the fix until 5.2 is released.

**Comment by frigus02** [comment]
I did a bisect and I believe this was fixed by https://github.com/microsoft/TypeScript/commit/f9cf8216c6e9e1339a79e81d772799190c10fa49

**Comment by frigus02** [comment]
Yeah, confirmed. 

https://github.com/microsoft/TypeScript/commit/d90eb0d731c3f74b131dcfafe69ef5341ed14934 produces the result mentioned above for versions v5.0.4 and v5.1.6.

https://github.com/microsoft/TypeScript/commit/f9cf8216c6e9e1339a79e81d772799190c10fa49 produces:

```
var _b = _a.name, name = _b === void 0 ? '' : _b,
    _c = _a.optional, optional = _c === void 0 ? false : _c,
    parameters = __rest(_a, ["name", "optional"]);
```

I guess we can close this. Or would you like a test case for this?

**Comment by MartinJohns** [comment]
This works fine in 5.0.4 and 5.1.6. [Playground link](https://www.typescriptlang.org/play?target=1&ts=5.1.6#code/MYGwhgzhAEBCkFNoG8C+AoAlgOwC4ICcAzMYJeCBWEAe2AGsAFMAsAWxmXWmm3YQD8ALmgRcBHAHMA3N2g0ADrkw0+IYdABGNGiARhssjKEgwKVWg2gIAHvmwATM4hRyFAV00hMwUbjDKvgByAIIAsgCi0AC80ABE5tR09HGyPB5ePrz8ImIS2DJunt6+isqqYCAi2rr6huhywKp57sC4NAQAFFw8PHxsSLEA5EMANHI8ZSpqMdAkIJTjvdAAdGsKLPz4BBByqCKJlkybHLNoAJSuyxDuCoSd52m9uAAWmBAr-YPZA088r+8VlMKiBZsC1E8MBh0E1sBBaitaJJOtgEAB3OCIJIMB7nGHNBFIlHozGUbH0bo-BAiEajeRKaaVETidxIVDnc5AA)

Or does it only happen when referencing tslib?

**Comment by MartinJohns** [comment]
The generated code without `export`:

```typescript
var BaseBlock = /** @class */ (function (_super) {
    __extends(BaseBlock, _super);
    function BaseBlock(_a) {
        if (_a === void 0) { _a = {}; }
        var _this = this;
        var _b = _a.name, name = _b === void 0 ? '' : _b, _c = _a.optional, optional = _c === void 0 ? false : _c, parameters = __rest(_a, ["name", "optional"]);
        _this = _super.call(this) || this;
        _this.name = name;
        _this.optional = optional;
        return _this;
    }
    BaseBlock.NAME = "BaseBlock";
    return BaseBlock;
}(Base));
```

And with `export`:

```typescript
export var BaseBlock = /** @class */ (function (_super) {
    var _a, _b;
    __extends(BaseBlock, _super);
    function BaseBlock(_a) {
        if (_a === void 0) { _a = {}; }
        var _this = this;
        var name = (_a = _a.name, _a === void 0 ? '' : _a), optional = (_b = _a.optional, _b === void 0 ? false : _b), parameters = __rest(_a, ["name", "optional"]);
        _this = _super.call(this) || this;
        _this.name = name;
        _this.optional = optional;
        return _this;
    }
    BaseBlock.NAME = "BaseBlock";
    return BaseBlock;
}(Base));
```

**Comment by fatcerberus** [comment]
> Ah, good catch. It only seems to break when you export the class: `export class BaseBlock`

I wonder if this is related to https://github.com/microsoft/TypeScript/issues/53332 (not a duplicate, though, since there are no decorators here)

**Comment by RyanCavanaugh** [comment]
Closing since it's fixed
