### ISSUE TITLE
Supporting negative types is very convenient

### ISSUE THREAD

**Issue by Autumn-one** [microsoft/TypeScript#55000]
# Suggestion

## 🔍 Search Terms

Negated types

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Many typescript users want the ability to negate types

```typescript
type NotStr = not string;
```
At present, typescript does not have real negative types, but if negative types can be applied in some actual development scenarios, it will be able to express types more clearly and directly. I think this is the basic function that a Type system should have. Without this function, developers may use some imprecise and complex ways to implement flexibly, which is not good
I've seen a PR that was turned off, which is a real shame
https://github.com/microsoft/TypeScript/pull/29317

**Comment by xiBread** [comment]
https://github.com/microsoft/TypeScript/pull/29317#issuecomment-1137500090
