### ISSUE TITLE
Warn the user when a different version of typescript than the one running is installed as a local package

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#5500]
We should consider checking whether there exists a local `typescript` package installed, and whether it differs from the one currently running. This was brought up by @alexeagle in https://github.com/Microsoft/TypeScript/pull/5465#issuecomment-152898293.

**Comment by RyanCavanaugh** [comment]
Seems out of scope

**Comment by DanielRosenwasser** [comment]
I will also mention that tools like [Volta](https://get.volta.sh/) are excellent and automatically do the right thing for running `tsc`.
