### ISSUE TITLE
Type infer issue about tuple type

### ISSUE THREAD

**Issue by grapehunter** [microsoft/TypeScript#55016]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, including 5.1.6 and 5.2.0 beta

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/KYDwDg9gTgLgBMAdgVwLZwLIQCbIDbBwDeAUHHAOQDKwAzrQJYSIVwC8cADADRmVUwowAIaoKvcgHpJcAHTySAXxIlQkWHBgBPMISy4CNAgGMYAHgAqCEDCTZacIcOzM8WzDnzAA2gF1ucBb6XkbApta2iPZwAEph0NhmwQQBwohaAHwZ7IERdg7efAyIAGbAUHAAYnlRDsnAEnLyxWUVADI10U4uiG4eBj6+JEPkAPyB9aGm3pW+cABk-SHAJuZtAUGehithMBl8AFxwyIgA1ogQAO6IANwq5GrQ8Nq6cACCMATCtDAA8oiENh8AA+cG89QC8lk9T8IzgoO8UJh-iWBCGfEeGmKtigJWExkIAEkaPQmIhSABIY60cqE7BHH5QYoAczu5GUGPATzg2PKeIJcGJghEqFI5HIjJFdIZghZbLgHIeXKxiBx-L0WzoGGEYGIfHBmtkJMYzF8R2JdBNt319SNwtEZvIQqc6EWFtJzHl0iasiUKkxzx0GoGlWKwjwZj4VlAkWiHy+P3+wBI2Q4kx2pksAXqtG1YAyd1UysDr3qocQ4YACgxjKdI+RozZ8u9PiJEwCUzk4NXa0lNeXw5YMgEKMgaVA6RQC3BvQA-eezuAACQAojEV4KqJuqABVFeyQJByiMlmsFx0OAXeC0YQwBi0EruGAAC0IxmYjOE2Mop2AWggJSosAUzmBY2aarmOoZKwFhHhQJ6IMyrD3peEDwN8jDMhWABGBCaBAmhwQCABu5QULIAAUABMADMAAsdEAJQqN6ZZhhGfjZAAcmhcCoLexjPi2CZ-ACB7vqgYAMHh5RQNAJCsf27FmAaAx2i64FqcaZK+NkwAAI7IOGDgwARzoigsm6WmSCkyGxFYcba2mmnphnGfhTrOYgtlAQOjmGgILq6Qgbl4CZBGbvarpWR63nelQZmaM+xSnNStLYDyDjCHAtDPsIQgZSUDArNExS+cpFjZC+t6CnAxhpHAUm1mlE6FXJ6AMDAJBAA)

### 💻 Code

```ts
export enum Module {
  'Session' = 0,
  'Stream',
  // ...
}

export type ModuleSelect<T extends readonly Module[], TModuleSelect extends Record<Module, any>> = T extends [
  infer F extends Module,
  ...infer L extends readonly Module[]
]
  ? TModuleSelect[F] & ModuleSelect<L, TModuleSelect>
  : unknown;

  export type AtleastOne =
  | [Module, ...Module[]]
  | [...Module[], Module]

  export interface ISession{
	 userId: string;
  }

  export interface IStream{
    streamId: string;
  }

  export interface ModulesMap {
  [Module.Session]: ISession;
  [Module.Stream]:  IStream & ISession;
  // ...
}

export type ModuleFinal<
  T extends AtleastOne
> = ModuleSelect<T, ModulesMap>;

export type ModuleFinalPick<
  T extends AtleastOne
> =  Pick<ModuleFinal<T>, 'userId'>; // ~~~~ HERE IS ISSUE. Type 'string' does not satisfy the constraint 'keyof ModuleSelect<T, ModulesMap>' Type 'string' is not assignable to type 'never'.(2344)

// ModuleFinal<[]> Not match AtleastOne. compile error
// ModuleFinal<[Module.Stream, Module.Session]> equals to IStream & ISession
// ModuleFinal<[Module.Session]> equals to  ISession
// ModuleFinal<[Module.Stream]> equals to  IStream & ISession
// So I think userId is a shared fields in ModuleFinal<T> that I can pick userId from it


```

### 🙁 Actual behavior

This Line compile error. Type 'string' does not satisfy the constraint 'keyof ModuleSelect<T, ModulesMap>' Type 'string' is not assignable to type 'never'.(2344)
```ts
export type ModuleFinalPick<
  T extends AtleastOne
> =  Pick<ModuleFinal<T>, 'userId'>; 
```
![image](https://github.com/microsoft/TypeScript/assets/3354458/837c8977-7099-4cef-9adf-f9012e19e231)

### 🙂 Expected behavior

This compilation error should not occur.
T of ModuleFinal<T> is constrained to be **extended** `AtleastOne`, and `AtLeastOne` is an array containing at least one `Module`.

- `ModuleFinal<[Module.Stream, Module.Session]>` equals to `IStream & ISession`
- `ModuleFinal<[Module.Session]>` equals to  `ISession`
- `ModuleFinal<[Module.Stream]>` equals to  `IStream & ISession`
- `ModuleFinal<[Module.Session, Module.Stream, Module.Stream, Module.Session]>`(No matter how many module combinations) equals to  `IStream & ISession`
- <del>`ModuleFinal<[]>` is not allowed, so empty array [] is not legal type of T</del>

At this point `ModuleFinal<T>` contains (insersects) `ISession` regardless of **any legal type of T**. And the `userId` must be a **key of** `ModuleFinal<T>`.

![image](https://github.com/microsoft/TypeScript/assets/3354458/6623a282-1d89-44af-ab38-e2233e3f1d4c)
```[tasklist]
### Tasks
```

**Comment by MartinJohns** [comment]
I think this is working as intended / a design limitation. `Pick<>` requires the property name to exist on the picked type, this is done using `keyof`. But `ModuleFinal<T>` resolves to `unknown` at this point (because the compiler doesn't know the **actual** type of `T`), and `keyof unknown` ends up being `never`, and the string `"userId"` is not assignable to `never`.

**Comment by grapehunter** [comment]
> `ModuleFinal<T>` resolves to `unknown` at this point (because the compiler doesn't know the **actual** type of `T`), 

T is constrained to be `AtleastOne`, and `AtLeastOne` is an array containing at least one `Module`.
`ModuleFinal<[Module.Stream, Module.Session]>` equals to `IStream & ISession`
`ModuleFinal<[Module.Session]>` equals to  `ISession`
`ModuleFinal<[Module.Stream]>` equals to  `IStream & ISession`
At this point `ModuleFinal<T>` contains (insersects) `ISession` regardless of any legal type of T.

**Comment by MartinJohns** [comment]
It's irrelevant what the type of `ModuleFinal<>` is when providing concrete types, what matters is the type definition of `ModuleFinalPick<>` at line 36-38. **At this point** the compiler has **no** information what type `T` will actually be. It only knows that it extends `AtleastOne`, but this information is not enough to ensure that the type will have a `userId` property.

**Comment by grapehunter** [comment]
> It's irrelevant what the type of `ModuleFinal<>` is when providing concrete types, what matters is the type definition of `ModuleFinalPick<>` at line 36-38. **At this point** the compiler has **no** information what type `T` will actually be. It only knows that it extends `AtleastOne`, but this information is not enough to ensure that the type will have a `userId` property.

I don't think so. 
**type T will actually be** doesn't matter, what matters is **the possible types of T**.
Any legal type of T ensure that the type(infer to ISession & ...) will have a `userId` property.

The proof is that if you replace the recursive implementation of `ModuleSelect` with the ugly one, the compile error disappears!

```ts
// export type ModuleSelect<T extends readonly Module[], TModuleSelect extends Record<Module, any>> = T extends [
//   infer F extends Module,
//   ...infer L extends readonly Module[]
// ]
//   ? TModuleSelect[F] & ModuleSelect<L, TModuleSelect>
//   : unknown;

export type ModuleSelect<T extends Array<Module>, TModuleSelect extends Record<Module, any>> = (0 extends keyof T
  ? TModuleSelect[T[0]]
  : Record<string, never>) &
  (1 extends keyof T ? TModuleSelect[T[1]] : Record<string, never>) &
  (2 extends keyof T ? TModuleSelect[T[2]] : Record<string, never>) &
  (3 extends keyof T ? TModuleSelect[T[3]] : Record<string, never>) &
  (4 extends keyof T ? TModuleSelect[T[4]] : Record<string, never>) &
  (5 extends keyof T ? TModuleSelect[T[5]] : Record<string, never>) &
  (6 extends keyof T ? TModuleSelect[T[6]] : Record<string, never>) &
  (7 extends keyof T ? TModuleSelect[T[7]] : Record<string, never>) &
  (8 extends keyof T ? TModuleSelect[T[8]] : Record<string, never>) &
  (9 extends keyof T ? TModuleSelect[T[9]] : Record<string, never>) &
  (10 extends keyof T ? TModuleSelect[T[10]] : Record<string, never>);
```
Please check playground.

[new playground](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/KYDwDg9gTgLgBMAdgVwLZwLIQCbIDbBwDeAUHHAOQDKwAzrQJYSIVwC8cADADRmVUwowAIaoKvcgHpJcAHTySAXxIlpCcNHgwAnmEJZcBGgQDGMADwAVdTCTZacIcOzM82zDnzAA2gF1ucJYGXsbAZjZ2DgBKYdDY5sEEAcKI2gB8aeyBEYj2cN6qMuQMiABmwFBwAGI5eYnAvGrk8rIl5ZUAMrUOTi6Ibh6GPr6FcCNNcAD8gfWhZt5VvnAAZIMhwKYWHQFBnkYbYTBpo+QAXHDIiADWiBAA7ogA3CqgkLBwOnpr+5tW3XAAQSgUGE2gSe2AaR2swO4VAtly0ViUHi9WSqQyWQAFJx-ldgNoIKVAnxprshnMYN5LN5OL4Rmc4DETHFzLRBCUAOYBRDAABuFTSAEoVnwsQBGPEEonZMkwzbU7zi+lwc7M1nsqBcnn8wUi5ZigBMUsJxOscohlMVhpVauR8U12rgvIFUGFovIWIAzCaZeaZpbYVSaV7bUz7WyOYhuc7dW79WKACy+s1TAMUoOKxNh9UoyNa6M613ug2egCsKdl6fWCppZZzEcdhdjxYTnoAbJX-eSa4dFe2Gyy802Yy69R64FiAOxdtM9n59mlTwcaqOjuMlsUADlnFozte8W5Xw7XRfHpcnAE5d9WF-MaZfjw7Ty3z2Lxbj4ZE4PjTVX58AVo0h+T75k6Y7xs8fCvJoHy6IQAIwAQwjsgA8ry7B8AAPvkaJyPI9R+AycA4d4LSEf43zACM0EaO8JS2FApTCCYhAAJI0PQTCIKQACQFy0BUbHYOcI7POQyi0W88AMRUzGsXAHGCCIqCkOQ5CaipwmiWu4lwJJ5AwfRiCMfJ+gQrQGDCGAxB8N49SyJxjDML45wcXQzlPHZDkCE4qCueQSl+SsilOdxelqC0SgvHRWjwVRVQlMIeDmHw1hfoigJISIaG8iQmQcPKhxWAE9SWdZaRQUZcVfPUiWIMlAAKDAmFcqXkOlIAInkiHIblwD5VkcDNa14JDPVyVWFClDIIJUDCRQlVwGoAB+a0rXAAASACiUTbaFoVUAAqttsiBPFFAjqwLh0M6EDwLQwgwAwtClO4MAABaECyiCasIDGUL+MpFWYJVUeVYBpKwlgXVdcAvXd8AoYwnINQARgQHwQHBXwUBBFCyFihpeomiZCioah1UlKV+JkABy91wKgT0mB9WV9TA6HAGdLKoGADCYxUUDQKMVMNTTPnKaIpUQo5Hncb4mTAAAjsgyUODA2NBSpIXuVxzCixCE0S7LYUuUrqvq1jgVm4ghvjdT5j2abUv+Rbat4Br2Oha7uu26MVBax8H0lFcAlCdg8MOMIcC0B9whCJHpQMBseQlAljuWJkn1PYpcAmCkcD8614fzUnwvoAwMBAA)

**Comment by grapehunter** [comment]
I think I found the cause of the problem, recognising [...T[], T] with an error?
```ts

export type CountEmpty<T extends readonly string[]> = T extends [
  infer F extends string,
  ...infer L extends readonly string[]
]
  ? {NotEmpty: string}
  : {empty:string};

type t1<T extends [string, ...string[]]> = Pick<CountEmpty<T>, 'NotEmpty'> //ok
type t2<T extends [...string[], string]> = Pick<CountEmpty<T>, 'empty'> //ok
type t3<T extends [...string[], string]> = Pick<CountEmpty<T>, 'NotEmpty'> //compile error
```

[playground link](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/FAUwHgDg9gTgLgAjgTwiBBhKBXAdnAUQFsIUAeAFQXDhFwBMBnBGEAQ3qlwBtkFG4MAJa4A5gG0AugD4EAXgRUadJgnHAECEQDMQMBADFqYWg2YDhYgDQaEAOgc69CADLHTq1hy69+gkRKSwEGaAPwIAN4AclCEJCgAXH6WogC+tkkRIPHICRYBqQDcwMAoaEgAjJTuKszi+db2Dg2BMvIIAApCAMYA1mRYeHGkyJTSVggA5DHDKJPSpajocABM1cpmag52LVITLW0KXX0DOPjEI2MTk9kj84vlcADM6ya1W83+YnvJAYedPX6g3OOSuUxmFzm0iAA)

**Comment by MartinJohns** [comment]
> Any legal type of T ensure that the type(infer to ISession & ...) will have a `userId` property.

That's not accurate. Adding this code is legal:

```typescript
export enum Module { Abc = 999 }
export interface ModulesMap { [Module.Abc]: IStream }
type Test = ModuleFinal<[Module.Abc]> // IStream, no userId property
```

But you would be right if you use a type alias instead of an interface.

**Comment by grapehunter** [comment]
> > Any legal type of T ensure that the type(infer to ISession & ...) will have a `userId` property.
> 
> That's not accurate. Adding this code is legal:
> 
> ```ts
> export enum Module { Abc = 999 }
> export interface ModulesMap { [Module.Abc]: IStream }
> type Test = ModuleFinal<[Module.Abc]> // IStream, no userId property
> ```
> 
> But you would be right if you use a type alias instead of an interface.

No, I think you are not correct.
Change ` type AtleastOne =  [Module, ...Module[]] | [...Module[], Module]` to ` type AtleastOne =  [Module, ...Module[]]`, the code will be  compiled successfully.

```ts
export enum Module {
  'Session' = 0,
  'Stream',
  // ...
}

export type ModuleSelect<T extends readonly Module[], TModuleSelect extends Record<Module, any>> = T extends [
  infer F extends Module,
  ...infer L extends readonly Module[]
]
  ? TModuleSelect[F] & ModuleSelect<L, TModuleSelect>
  : unknown;

  export type AtleastOne =
  | [Module, ...Module[]]

  export interface ISession{
	 userId: string;
  }

  export interface IStream{
    streamId: string;
  }

  export interface ModulesMap {
  [Module.Session]: ISession;
  [Module.Stream]:  IStream & ISession;
  // ...
}

export type ModuleFinal<
  T extends AtleastOne
> = ModuleSelect<T, ModulesMap>;

export type ModuleFinalPick<
  T extends AtleastOne
> =  Pick<ModuleFinal<T>, 'userId'>;
```

[playground](https://www.typescriptlang.org/play?ts=5.2.0-beta&ssl=15&ssc=26&pln=14&pc=1#code/KYDwDg9gTgLgBMAdgVwLZwLIQCbIDbBwDeAUHHAOQDKwAzrQJYSIVwC8cADADRmVUwowAIaoKvcgHpJcAHTySAXxIlQkWHBgBPMISy4CNAgGMYAHgAqCEDCTZacIcOzM8WzDnzAA2gF1ucBb6XkbApta2iPZwAEph0NhmwQQBwohaAHwZ7IERdg7efAyIAGbAUHAAYnlRDsnAEnLyxWUVADI10U4uiG4eBj6+JEPkAPyB9aGm3pW+cABk-SHAJuZtAUGehithMBl8AFxwyIgA1ogQAO6IANwq5GrQ8Nq6cACCMATCtDAA8oiENh8AA+cG89QC8lk9T8Qz4jw0xVsUBKwmMhAAkjR6ExEKQAJDHWjlDHYI4-KDFADmd3Iynh4CecCR5VR6LgWMEIlQpHI5Ap3NJ5ME1NpcHpD0ZiMQyLZei2dAwwjAxD44IVsmxjGYviOWLo2tuavqmq5ol15E5TnQi31OOYYukTVkShUCOeOnlA0qxWEeDMfCsoEi0Q+Xx+-2AJGyHEmO1MlgC9VoSrAGTuqilHte9R9iD9AAUGMZTgHyEGbPl3p8RBGAdGcnAiyWkgq837LBkAhRkMSoKSKOmgA)

**Comment by RyanCavanaugh** [comment]
Another good solution would be
```ts
export interface ModulesMap {
  [Module.Session]: {};
  [Module.Stream]:  IStream;
  // ...
}

export type ModuleFinal<
  T extends AtleastOne
> = ModuleSelect<T, ModulesMap> & ISession;

export type ModuleFinalPick<T extends AtleastOne> =  Pick<ModuleFinal<T>, 'userId'>; 
```
which saves you the duplication and works higher up the type stack
