### ISSUE TITLE
getSymbolAtLocation returns wrong symbol for import alias in RHS of "import ="

### ISSUE THREAD

**Issue by jeffreymorlan** [Microsoft/TypeScript#5501]
```ts
module SomeModule { export class SomeClass {} }

import M = SomeModule;  // or import M = require(...)
import C = M.SomeClass;
```

On the `M` identifier in `M.SomeClass`, getSymbolAtLocation returns the `SomeModule` module symbol, rather than the alias `M` to it.

This affects renaming, find references, and occurrence highlighting:
* If you select the `M` in `import M = ...`, the second `M` will not be found
* If you select the `M` in `import C = M.SomeClass`, the first `M` will not be found, but the two `SomeModule` references will be found instead.

**Comment by DanielRosenwasser** [comment]
Yeah, rename on aliases seems to be extremely broken.

![brokenaliases](https://cloud.githubusercontent.com/assets/972891/10903370/c0297368-81bd-11e5-83e2-e223262d813d.gif)
