### ISSUE TITLE
VS Code Typescript service reports false positive error.

### ISSUE THREAD

**Issue by elliason** [microsoft/TypeScript#55022]
In new Vite project, there is .eslintrc.cjs file with `__dirname` used there. If `tsc` is called from CLI, there is no problem but the IDE service reports this `__dirname` usage as error.
![image](https://github.com/microsoft/vscode/assets/6887123/cc4c1823-11d1-4e6c-89a7-fac1f5eb42ad)
I have tried every step that came to my mind (including installing @types/node and adding types: ["node"] to tsconfig.json compilerOptions) to solve this without using // @ts-ignore, but failed everytime.

This issue occurs even without extensions.

- VS Code Version: 1.80.1
- OS Version: Windows 11 (22621.1992) with WSL2 - Ubuntu 22.04.2 LTS

Steps to Reproduce:

1. run `npm create vite@latest`
2. choose "typescript + swc" template
3. check the `.eslintrc.cjs` file and look how `__dirname` error is reported

**Comment by jakebailey** [comment]
You need to add `.eslintrc.cjs` to `tsconfig.node.json` in vite's projects, as that's the one for config files.

![image](https://github.com/microsoft/TypeScript/assets/5341706/dd73c626-eb6e-425e-81e8-50ec70e37c97)

**Comment by drewhoener** [comment]
I just ran into it this morning, appears to be a Vite issue, not TS.
Check https://github.com/vitejs/vite/pull/13749 for the PR status, or copy the settings manually for an immediate fix

**Comment by elliason** [comment]
@jakebailey Yes, I have done that, but the issue is still there.
![image](https://github.com/microsoft/TypeScript/assets/6887123/2362eda5-8128-40ac-b332-6f89b11252c8)
![image](https://github.com/microsoft/TypeScript/assets/6887123/0a5f32da-d8c0-4755-80aa-d7db39df07ef)

Even after reloading VS Code window, no change at all.

@drewhoener This is happening on all of my projects, and some of them are not based on Vite. I just chose the Vite template as a good example. And because running `tsc` via CLI gives no actual error, I highly suspect the VS Code IDE.

@ts-ignoring "fixes" this but, I would really like to know where is the problem. Can't figure it out.
