### ISSUE TITLE
Incorrect Return Inference for Object Unions in Multiple Return Types

### ISSUE THREAD

**Issue by dpchamps** [microsoft/TypeScript#55025]
# Bug Report

### 🔎 Search Terms

 Return Inference Object Unions Multiple Return Types

### 🕗 Version & Regression Information

Seeing it from version 3+

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/PQKhCgAIUgFAnA9gIwDYFMC2kDKAXAQzy3QDs8AuKGayAdQAszIDIAzAV1IGM8BLRKUgMCAZ0iYOqfgAcMkeOjwd4QgG4FUHdKIA0LUgBNIg9CbaQ8TSDMSjRfNGcXLVkDVp2Q+o2qy4CQogWKABW6Lx6ltYuKkJ4AJ4yZj7epGzo8IrGYtFm3IiYmII2SMnw-F7ISgDu6MxWRLRhEXjUwOCdicmQABqQALyQAN5QkOMEFJCkHJjV8OAAvpAAPiNjE1Mzc5m6G5DIU6J48HykAOZLncDAcEhOmER83JAAwmLonYYRqASKkAVSMd3JptFNegBucDfbi-f6A4HIRCIVBTJEo9AEUhQ8AIvDsIRDAAUAEpBgA+dbjcZ8NhE9GoMmxNxcb5sM7oQxQ6kKJRxEGeKGLTp43miKR4ABCBGMQzYpFJUNpRMU4uk0uMADJNZAAETIXVpMUSjUk0Y8mR-UToACS5BVOhNMoAdMgSULrrcAKIADzkzz4+OZ6lB6H0AFVSDJ7hhHvxuCLBMD5b7-dxA4NIKTwStWeh2aRORSqdTlQymXyWUZ8xyuftgwLtB7cUmg47pKnUAH8XLSJ3u4rwMrVRL++n8dq9QajSOO36u+OzftLfBrXa8A61Xgx4HXe6ruAbpBI9GULGni9uB9E0D8ch4FjuAwMPYAGKErNkgaU83UhseJsD1FWc8AAcWRWUDgfHhnx0UR30HZV9UNM5jWkcDEEMJcLStW17RAjDDD3A8jwQPhMEDPg1DMd5rQjKMYywC8b2TUgyIo-hqMzUli1-Gk6XLXlXCEPMC05blSzpABZIgGGdaDDEKHjKQABmdABWCthMgABGCTxgbXUdN1IDWzQvB2Morje0szj0EHTplW6dBgnM2yqLMAYvL1Y5TguXVsL-dsLNODiPMgI8jJM5Z0FQa1vAsIlnNckD3Os7zdW2eYApLAzgrSswjx0pZIFi+K+Lc0KrMK25RNrJYgA)

### 💻 Code

```typescript
type X = {
    a: number
} | {
    a: number,
    b: string
}

// Problematic Case

declare const value: X;
declare const bool: boolean;

const fn = () => {
    if(bool) return undefined;
    return value;
}

const resultBad = fn();
if(resultBad && "b" in resultBad){
    parseInt(resultBad.b); // type error, b unknown
}

// Explicit return value, Unproblematic

const fnExplicit = (): X|undefined => {
    if(bool) return undefined;
    return value;
}

const resultExplicit = fnExplicit();
if(resultExplicit && "b" in resultExplicit){
    parseInt(resultExplicit.b); // ok
}

// Unproblematic case

const branchlessFn = () => {
    return value;
}

const resultGood = branchlessFn();
if("b" in resultGood){
    parseInt(resultGood.b); // ok
}
```

### 🙁 Actual behavior

When a function has multiple return values, and one of the possible return values is
a union of objects, the return type is inferred as the common properties between that
object, instead of the full union

### 🙂 Expected behavior

I would expect the object to be the full union, e.g. I would expect the inferred return value of `fn` to be the same as the explicitly typed value of `fnExplicit`

**Comment by MartinJohns** [comment]
This is the expected behaviour due to "subtype reduction".

**Comment by guillaumebrunerie** [comment]
Your type `X` is equivalent to `{a: number}` because any value of type `{a: number, b: string}` is assignable to `{a: number}`. If you use a discriminated union for `X` instead, the issue disappears:
```typescript
type X = {
    hasB: false,
    a: number
} | {
    hasB: true,
    a: number,
    b: string
}
```
