### ISSUE TITLE
TypeScript fails to use the correct type immediately after assignment

### ISSUE THREAD

**Issue by nstepien** [microsoft/TypeScript#55023]
# Bug Report

### 🔎 Search Terms

generic assignment

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about assignments

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/DYUwLgBAtghgDgLggWXgHgM5gE4EsB2A5gDQRZ5EB8A3AFC0D0DEAAmBgLQgAecIAxmC7ZsAe2wQAZjFzBaAClhwIAXgj4QAdxTx5ASj0A6DOHkByM6QCMAJgDMeuo2aFRogCYKlEAPw+1GtqocPpGJmDmlhC2DnSK8KrqWjohBsamFqRmMWaOXgl+AcnBoekRmRDZ9rlOBGAg2NL8IBAAymAw9RAA3rQQ0PA+SMGYOAQkZGNUdAC+9KCQWJ0gSO3Lid0zTkys7Fy8AkINYhLSsgpL9YbeRUG6aeGR1vZ5O2ycPHyCwidSMnLyS4ga4FfxJO6pMIZKIxPLOCCuDwXDpXG7glKlR4VKp2GrI5Yg5SFdElB7QrI5RxAA)

### 💻 Code

```ts
let map: Map<string, string>;

// @ts-expect-error fail
(map = new Map()).set('', 123);

// good
(map ??= new Map()).set('', 123);
(map = new Map()).set('', '123');
(map ??= new Map()).set('', '123');

interface State {
  map?: Map<string, string>;
}

let state: State = {};

// @ts-expect-error fail
(state.map = new Map()).set('', 123);
// @ts-expect-error fail
(state.map ??= new Map()).set('', 123);

// good
(state.map = new Map()).set('', '123');
(state.map ??= new Map()).set('', '123');
```

### 🙁 Actual behavior

TS seems to use the inferred type of the value instead of the type of the variable/property the value is assigned to.
`(map ??= new Map()).set('', 123);` is the only case where TS catches the type issue properly.

### 🙂 Expected behavior

TS should catch the type error in the following cases, as we should not be allowed to assign a number where a string is expected.
```ts
(map = new Map()).set('', 123);
(state.map = new Map()).set('', 123);
(state.map ??= new Map()).set('', 123);
```

**Comment by fatcerberus** [comment]
While this *is* a footgun, it's also effectively just this with fewer steps:

```ts
let map: Map<string, string>;
let mapAny: Map<any, any>;

mapAny = new Map();
map = mapAny;
mapAny.set('', 123);  // oops
```

...which also doesn't produce a type error.

**Comment by RyanCavanaugh** [comment]
The only plausible fix here would be to remove the `Map<any, any>` overload, but I don't think that would be palatable
