### ISSUE TITLE
Excessive stack depth comparing types

### ISSUE THREAD

**Issue by Vacatee** [microsoft/TypeScript#55027]
# Bug Report

I encountered an error while using the [prisma-nestjs-graphql](https://github.com/unlight/prisma-nestjs-graphql) generator that resulted in an "Excessive stack depth comparing types" error. This error prevents nestjs from starting correctly.

### 🔎 Search Terms

Excessive stack depth comparing types, NestJs Prisma Excessive stack depth, Excessive stack depth comparing types typescript

### 🕗 Version & Regression Information

Today

- This is a crash

### 💻 Code

Steps to reproduce:

1. Clone the test repository: [repo-test](https://github.com/Vacatee/repo-test)
2. Follow the installation instructions in the README to set up the project.
3. Run the project and trigger the scenario that causes the error.
4. See the "Excessive stack depth comparing types" error in the console.

### 🙁 Actual behavior

I think the problem comes from typescript, it's certainly not a problem in the code itself. Strange thing:

1. I transform the type SupplierUpdateInput in the file app.service.ts into any.
2. I save, the server starts without errors
3. I change the type back to SupplierUpdateInput and save again, the server starts without error too.

So it seems to me that the problem is only with server startup. Of course, in a real project, transforming types into any everywhere in the code and putting them back is not an option.

### 🙂 Expected behavior

I expected the nestjs start without any error in the console

Additional information:

- Version of the "prisma-nestjs-graphql" generator: ^18.0.2
- Operating system: windows
- Prisma version: ^4.15.0
- NestJS version: ^9.0.0
- Typescript version : ^4.7.4

**Comment by Vacatee** [comment]
Resolved by changing the generator config to : 
```
generator nestgraphql {
  provider                              = "node node_modules/prisma-nestjs-graphql"
  output                                = "./@generated/prisma-nestjs-graphql"
  fields_Validator_from                 = "class-validator"
  fields_Validator_input                = true
  requireSingleFieldsInWhereUniqueInput = true
  emitSingle                            = true
  emitCompiled                          = true
  purgeOutput                           = true
  noTypeId                              = true
}
```

**Comment by RyanCavanaugh** [comment]
Hitting the type depth limiter isn't a bug
