### ISSUE TITLE
Type hole: A function with const generic does not infer the type if it is a spread parameter (tuple)

### ISSUE THREAD

**Issue by Refzlund** [microsoft/TypeScript#55033]
# Bug Report

### 🔎 Search Terms

`is:issue is:open function generic tuple const`
`is:issue is:open in:title tuple const`

Might solve; https://github.com/microsoft/TypeScript/issues/54254 `<T extends [a: string, b: number]>(...args: T)`

### 🕗 Version & Regression Information

- This is a overlooked type feature
- This has been an immediate effect of including a new feature: `const` in function generics
- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about `const`

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=5.1.6&ssl=21&ssc=51&pln=2&pc=1#code/FAehAICpwWj8DKBLAtgBwDZIGZIKYAm4eAHgIboZ6zzRjDDYCuAdgMYAuSA9i8SWjydCAITwALMgDceTAE4AeNrwDOHcAGkAfAApSFTHgBcmgJTgA3sHA3wcvB3l8LAX3BkVm4C4bKWa8G4AawBGcABefkFhAjFJGW55HQtwDjw1EzCXU1AIWwA9AH4GBmZ2Ll5wVlJotNiJaVlFPwCNfjSWAk9WIJZuAHcWAG0AXV0AOkmyOQBzFRMNcytbOwcnSzcPLx9gFvU+jgB5UIiqlhqhOrjGxMUhlLSM8BYmFAAjPDlwFzHk1PSOJlvjkwCsigxQQB1STqJCw+YrRF7Z7cI6hEz3f5PF7vT7fEa5cDQsjqfpbC4xEzgZEHY4hDEPAFAn4lEqg6BwGDgACqKjIM2o+ko1E5UHA9EYrE4PD42DInG4cgAnkpVOoACrtPCdbosXoDYa-NhvEw6SbjaZzEzq8zhLTgKTcJAEJbWWz2RxyWVSip8NhkDAYVX+dRtUgdLrgdUTKazBGLBaWN02UGItPpmz5cAAJTwKG4UmoKDwycRHvWrncng0pZ8O2RHDCkTlCuVOh0ZBMjOxrw+XxcABpwCbwGo5EgWDNbfbXKY-o9AeAQgAmADM3yHAHIVNxi6OOOPJ5uQXlM8VdmrUsvTi2OIqle3O5YsYucX2N8OTGOJ1OIjPsvOTJLmu3xVtSapbjue7fkeJ5goUQA)

The playground contains both a simplification and the actual use case.

The simplified example shows the core issue, that rest parameters will not be inferred using the function generic `const`.

The usage example is to demonstrate relevance in a factory pattern, and to ensure test coverage if necessary.

### 💻 Code

```ts
// * --- Simplified example --- * //

function expectedBehaviour<const K>(example: K) {
    return {} as K
}

const ok1 = expectedBehaviour({ test: 1 })
//    ^?



function unexpectedBehaviour<const K extends unknown[]>(...args: K) {
    return {} as K
}

const notOk1 = unexpectedBehaviour<[{ test: number }]>({ test: 1 })
//    ^?

// What it is:         const notOk1: [{ test: number }]
// What was expected:  const notOk1: [{ test: 1 }]





// * --- Usage example --- * //

function factory<const T extends unknown[]>(cb: (...args: T) => void) {
    return function call<const K extends T>(...args: K): K {
    //                     ^ Remove me
        return {} as K
    }
}

const t1 = factory((a: { test: number }, b: string) => {})({ test: 123 }, 'some string')
//    ^?

const t2 = factory((a: { test: number }, b: string) => {})({ test: 123 } as const, 'some string')
//    ^?
```

#### What
A generic function does not apply `const` to contents of a rest parameter.

`function fn<const K extends unknown[]>(...args: K): K`

#### Why
It's a bug, as the tuple does not become literal.

### 🙂 Expected behavior

Function generic `const` makes a type literal, including rest parameters.

<br><br><br>

**Comment by Andarist** [comment]
There is no bug in your simplified example. You should write this:
```ts
function unexpectedBehaviour<const K extends readonly unknown[]>(...args: readonly [...K]) {
    return {} as K
}
```

From [the PR](https://github.com/microsoft/TypeScript/pull/51865) that introduced this feature:
> When a const type parameter is constrained to an array type, that array type should include a readonly modifier; otherwise, inferences for the type parameter will fail to meet the constraint. [...] Without the readonly modifier in the constraint, inference defaults to unknown[] because an inferred readonly tuple type wouldn't be assignable to unknown[].

The other problem with this example is that you provide the explicit type argument to your call, one that is using a wider type. I'm not sure why do u expect other things here but if you provide explicit type arguments then inference doesn't even kick in so it's not a surprise that TS doesn't narrow the type based on the provided arguments.

**However**, the behavior with the showcased `factory` in the "Usage example" section definitely looks odd. It's odd that **adding** the `const` modifier you end up with a *wider* type than when not using t.

**Comment by Andarist** [comment]
So the problem is that `T` in the `factory` gets inferred as a *mutable* array. So later on, with `const`, the inferred type (a narrow one) doesn't pass the constraint check because a readonly array isn't a subtype of the mutable array (it's the other way around) and so the inferred type falls back to the constraint (which is the mutable array inferred from the outer `factory` call).

This is a minimal repro case of the problem: [TS playground](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230715#code/GYVwdgxgLglg9mABMAhtOAnAngHgggZykQBVEBTADynLABMDENyU6EAbLRcAazDgDuYANoBdAHwAKCACMAXIkkA6FSgwBzAgpIBKRAF5xiAG5wYdPQG8AUIjtNyUEBiSWAvohSMS1t9ev4YESIUAAsBshoUJhYkpLyiEQYMGDqeoaI7jrWAPQ59ogAegD8-kA).

**Comment by Refzlund** [comment]
Thank you @Andarist, that was quick!
I'm not sure about the relevance of what I encounter after following your correction is intended.

[TS Playground](https://www.typescriptlang.org/play?ts=5.1.6&ssl=24&ssc=1&pln=2&pc=1#code/FDBmFcDsGMBcEsD2kAEoCGdECcCeAeaZAZ1hQBUUBTAD1isgBNiUoBrSRAd0gG0BdAHwAKaACMAXCmEA6OemwBzYlPIBKFAF5BKAG6J4jDQG9gKcymxVY4bKggwEyFNHQAbN4RJkA0tToMzBQicjIKylJW6IzIbrgovKE+-CZmFulWNnYoxgC+KOgsPmnmucBlwPCQ9NgY0FQoAPIADk6QLKbp9KQA-FKQ4AC2YlTYADQlKAAWo819KKTYVYrlIMBE7WSuHqNaaJiwOLjCwoitSO1SLW3EGto5uWogG6QosACMe9tuo8LGKIxZlIAOSFRjAlCPYAAemh6XhCIsAD0UMD-oDsM0pItlgBuSEQ+AsThkQrEeCKSDoMQ-N6IFDNBToQbWXaIUBvXDNBrA64XYjA57eN4AJi+7h+2D+byopCk7xFAGYxgCgaiwRCobDEQjyFMiSgDegCsRyZTqbTDk1ziQejqhZs3oqrjb2nt-t1YPKlSqMVj1cRwZCQEA)

```ts


function factory<const T extends unknown[]>(cb: (...args: T) => void) {
    return function call<const K extends T>(...args: readonly [...K]) {
        return {} as K
    }
}

interface Options {
    test?: number,
    herp?: string
}


const caller = factory((options: Options) => {})

const t1 = caller({ derp: 'asd' })
//                  ^ '{ derp: string; }' is not assignable to parameter of type 'Options'

const t2 = caller({ test: 123, derp: 'asd' })
//             This is a assignable to Options?        

const t3: Options = { test: 123, derp: 'asd' }


```

In this example it seems that `K` loses it's ability to extend `T` after providing one valid property for `T`.

I would have expected it to **always** conform to the shape of `T`. I am not smart to not to assess whether this is relevant to this conversation.

**Comment by Andarist** [comment]
Extra keys are always allowed. What you see is the excess property check which is more of a lint rule error than a type system violation.

To truly check for assignability I recommend this:
```ts
type Test = Source extends Target ? 1 : 0 // assignable if 1, not assignable if 0
```

**Comment by fatcerberus** [comment]
btw, the `Options` above is additionally subject to [weak type detection](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#weak-type-detection) which *is* enforced comprehensively, unlike the excess property check.

**Comment by RyanCavanaugh** [comment]
Everything here is working as intended for various reasons discussed above
