### ISSUE TITLE
Enum member with same name by itself and dose not export anything

### ISSUE THREAD

**Issue by Lai-hung** [microsoft/TypeScript#55038]
### 🔎 Search Terms

- enum member with same name by itself

### 🕗 Version & Regression Information

- This changed between versions 5.0 and 5.1

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?module=1&ts=5.1.6#code/KYOwrgtgBAwghgJygbwFBQ7RAadmAqCYAxgNa4C+qqwAHgA4D2CALinhvApUA)

### 💻 Code

```ts
enum Car {
    Car,
    Truck,
}

export {
    Car,
}
```

### 🙁 Actual behavior

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Car = void 0;
var Car;
(function (Car) {
    Car[Car["Car"] = 0] = "Car";
    Car[Car["Truck"] = 1] = "Truck";
})(Car || (Car = {}));
```

Try to get Car.Car but undefined happened because it does not export anything

### 🙂 Expected behavior

```js
use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Car = void 0;
var Car;
(function (Car) {
    Car[Car["Car"] = 0] = "Car";
    Car[Car["Truck"] = 1] = "Truck";
})(Car || (exports.Car = Car = {}));
```

**Comment by fatcerberus** [comment]
For reference, pre-5.1 emit is:
```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Car = void 0;
var Car;
(function (Car) {
    Car[Car["Car"] = 0] = "Car";
    Car[Car["Truck"] = 1] = "Truck";
})(Car || (Car = {}));
exports.Car = Car;
```

The last line is missing in 5.1 and later.

**Comment by Lai-hung** [comment]
I think 5.1 change compile behavior.
Because I check other files which not same name with enum itself and enum member, and those compile result likes last line in expected behavior block.
```ts
})(Car || (exports.Car = Car = {}));
```

But <5.1 is use as follow as result
```ts
})(Car || (Car = {}));
exports.Car = Car;
```

**Comment by rbuckton** [comment]
This was due to a fix in name resolution for `namespace` that should have also applied to `enum`. I've just put up a PR to address this in #55070.
