### ISSUE TITLE
Type infering don't work when one var depends on the other but the other is reassigned (unexpected implicitly type 'any')

### ISSUE THREAD

**Issue by orl0** [microsoft/TypeScript#55041]
# Bug Report

TypeScript can't infer type for local variable `varA` which depends on variable `varB`.
This happens when and only when variable `varB` is reassigned and it's value depends on `varA`

### 🔎 Search Terms

- infer+recursion
- implicit+any+bug

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for ... (searched for word 'implicitly')

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.2.0-beta&ssl=17&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABAQwCaoCoHc4DkQC2ARgKYBOAzgBTJlkBciA2mIaWQDSKvHkC6TPgEpGPdoMQBvAFCJEEBBSiIyJCqLbkJAXmZ8A3LMQAbEsoi0yATwDyYEol3BkxiiUNHgcMoioKwSszIXER8iHDAKHQAdKoAbuRuVEJCUkZy-oEUhI4oiADUiEQFvhZ0tvaIAPyIAIyIjAAMQvqIAPRtiDAEAA7GMBAwUMZWiADkyGBWY+kqatE9IBQAFlTZBIgApHXNhnIZlhUOuuuIAHyIAJwe++2dAEIAqhiIUMswFOGVwDAAHmpFEAAc3osw68kOdmOiGcrncYM6MEiaxyF0uqTK1ihuSgZBA8LkAF9pEYkaVIfZUqoKAslqtai0jKooCAyEhqbESAlKCRkoZidJMnBTNFjHAgVQAAYAEkkaEwOHwvEoVCYTAA7BxGnwOEwAEwcACsOqYABYOAA2E0AZg4pr4wkJksZQpFYolMrl6GweE0KrVhqNDqETsZQA)

### 💻 Code

```ts
function addTwoNumbers(arr: [number, number][]): number[] {
  const res: number[] = [];
  let carryOne = false;

  for (const [a, b] of arr.reverse()) {
    const sum = a + b + (carryOne ? 1 : 0); // implicitly 'any'
    res.push(sum % 10);
    carryOne = sum > 9;

    // BUT this one fixes bug:
    // carryOne = false;
    // if (sum > 9) carryOne = true;
  }

  if (carryOne) res.push(1);
  return res.reverse();
}
```

### 🙁 Actual behavior

> 'sum' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### 🙂 Expected behavior

Variable`sum` should infer type because there are no circular references

**Comment by RyanCavanaugh** [comment]
This is a circular type dependency, because the possible values of `carryOne` when entering the loop in its second iteration depend on the possible values of `sum`

**Comment by orl0** [comment]
It looks like a circular type dependency, but it's not. All possible values of `carryOne` are still `true` and `false`.

Do you mean that TypeScript cannot guess the resulting type of assignment expression `carryOne = sum > 9`?

If so I might suggest to add that information to the behavior section of the [FAQ](https://github.com/microsoft/TypeScript/wiki/FAQ#type-system-behavior)

Otherwise it is a bug.
