### ISSUE TITLE
A Type Error occurs with using a generic that extends a branded intrinsic type

### ISSUE THREAD

**Issue by RebeccaStevens** [microsoft/TypeScript#55040]
# Bug Report

### 🔎 Search Terms

- generics
- branded
- intrinsic type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/PQ18ZXTt-IBQIAEAVAngBwKYGdFEAXbHFAIQCcBDAOwBMd6A5AVwFsAjHSlAXhS0O3XgDIUAb0QoUAfVmcaDJgC4URSqxyIAvoRK4UAeVw0iASwD2tAJJGAPGhQ4AHkRwM8g4TwB8-dGc3D3ovKjpGFh9KaRQAfnRYtSEuHgBuQgQs7Jzc+GRgFAAxVloAYwtrQgAzUoqrWhQ8Vk5HIPdPb1TKXwAKWOo1Ex5qStsHNF8AGkQASjVeziHTUYa7R19Z-n9hszWJ-ykZShwiVkpGxa2+f0WUAFoUai3qLzoMDL1MvJ-fv5gCuh8EQCICALLUADWZGaJ0E1nuigiTC6Ii8AHdLJRIQA6RBlax4IjqYFsbpeATNTi9ABMs16AGZZhlwVCYecyEjlPRUTwMVjcYhauUxiSiQB1cxEAAWllYRAA4h4eOYynheoMKEpImSRFMUEstciot0tkcUCczhcmi0NfTOMzdN8UABlFoGfAoSzVA3alEpNFNWWsAA2PMx2PUlkseOF9WsYqIkplStoKrVbVcHVCRu5ur8GrUaH1hrQZtilvOjSpdquaRQqHs90e4ulGBQ5i8Ms78OJ1BDIcs6KYcSdgIAEq8UATKCcKupsOZaABzFD0TtYKVkaicSwANzIPEoWLxBNoRMTACV8KGk1Lpan0xTE8mH8rKKr1bEaU8wn6TSIKDiBIciyNU0ZqAAjDoMwyAyv65jq0RAZIoHgZYUF6MyQA)

### 💻 Code

```ts
/////////////////////////////////////////////////////////////////////////////////////////////
// Types

type BrandedNumber = number & {
  __branded: true
}

type OperationIO<T extends number> = T extends BrandedNumber
  ? T
  : number;

/////////////////////////////////////////////////////////////////////////////////////////////
// Function

function sub<T extends number>(
  a: OperationIO<T>,
): (b: OperationIO<T>) => OperationIO<T> {
  return (b) => (b - a) as any;
}


/////////////////////////////////////////////////////////////////////////////////////////////
// Tests

// Make sure non-branded numbers work.
const testNumbers = sub(2)(3);

// Make sure branded numbers work.
function testWithoutGenerics(a: BrandedNumber, b: BrandedNumber) {
  return sub(a)(b);
}

// Subtypes of branded numbers should work too.
function testWithGenerics<T extends BrandedNumber>(a: T, b: T) {
  return sub(a)(b); // <-- Why is this not allowed?
}

// Has correct typing dispite above error.
const testResultWithGenerics = testWithGenerics(
  2 as BrandedNumber & { __foo: 1},
  3 as BrandedNumber & { __foo: 1}
);
```

### 🙁 Actual behavior

TypeScript reports a type error on line 35.

### 🙂 Expected behavior

No error should be reported because as far I can tell, this line should be valid. Additionally, TypeScript can successfully deduce the type on line 39.

**Comment by fatcerberus** [comment]
What is an “instinct type”?

**Comment by jcalz** [comment]
From context I'd say it means "primitive type"? 🤷‍♂️

The issue here is probably just that generic conditional types don't consult the generic's constraints and therefore remain unresolved, as in #31096

**Comment by RebeccaStevens** [comment]
Yeah, it does seem to be that issue that's occurring. Any suggestions on how I can work around it? The only solution I've come up with is to use overloads of the `sub` function.

Also, I said "instinct" was a mistake by me, I meant "intrinsic".

**Comment by jcalz** [comment]
The conventional term is "primitive", though.  In TypeScript, "intrinsic" refers to compiler-provided types that users cannot implement themselves (see #40580), and while one could make a case that all primitive types are intrinsic, not all intrinsic types are primitive.

**Comment by RebeccaStevens** [comment]
Ahh, good to know. I've kind of just been using the two interchangeably.

**Comment by RyanCavanaugh** [comment]
For this substitution to be safe, the conditional type would have to be nondistributive. If you change this to
```ts
type OperationIO<T extends number> = [T] extends [BrandedNumber]
  ? T
  : number;
```
then it indeed works as expected
