### ISSUE TITLE
autoImportFileExcludePatterns has no effect on node modules.

### ISSUE THREAD

**Issue by smallmain** [microsoft/TypeScript#55059]
# Bug Report

### 🔎 Search Terms

autoImportFileExcludePatterns

### 🕗 Version & Regression Information

Visual Studio Code v1.80.1, Typescript v5.1

### ⏯ Playground Link

None.

### 💻 Code

```
{
    "typescript.preferences.autoImportFileExcludePatterns": [
        "**/node_modules/@xenon.js/core/**/*"
    ]
}
```

or

```
{
    "typescript.preferences.autoImportFileExcludePatterns": [
        "@xenon.js/core"
    ]
}
```

### 🙁 Actual behavior

Will still be automatically imported from the package `@xenon.js/core`.

### 🙂 Expected behavior

Will not be automatically imported from these paths.

**Comment by RyanCavanaugh** [comment]
There's not enough information here to explain what you're trying to do

**Comment by smallmain** [comment]
> There's not enough information here to explain what you're trying to do

I want to exclude the automatic import of the npm package @xenon.js/core from the project. I set autoImportFileExcludePatterns, but the automatic import is still triggered.
![image](https://github.com/microsoft/TypeScript/assets/28684663/773e76ff-8ef7-4139-bd11-60d1846268cf)
If what I add to autoImportFileExcludePatterns is a relative path, it works, but if it's an npm package, no matter what the package is.

**Comment by smallmain** [comment]
Why? The problem is not solved yet.
