### ISSUE TITLE
detect and warn on cyclic dependencies

### ISSUE THREAD

**Issue by martin19** [microsoft/TypeScript#55050]
# Suggestion

Implement a compiler mode / addon to detect and warn if cyclic dependencies are present in the code base.

## 🔍 Search Terms

cyclic dependency dependencies madge
https://github.com/microsoft/TypeScript/issues/40471

## ✅ Viability Checklist

My suggestion meets these guidelines:

[x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
[x] This wouldn't change the runtime behavior of existing JavaScript code
[x] This could be implemented without emitting different JS based on the types of the expressions
[x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
[x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Implement cyclic dependency detection in typescript. Output the cycles in either parsable form on command line (for manual fixing) or as api to be used by 3rd party tools for automated code assistance. Module loaders suchas amd don't like cycles and keeping track of them is a difficult, recurring task but predestined for tool assistance. There are third party tools suchas "madge" or es-lint but they wont work well and lack resources. If you are not willing to implement this, please suggest where and how to implement/maintain this functionality.

## 📃 Motivating Example

The larger the project gets the harder it is to track cycles in dependencies. Typescript is made for large projects. I think the compiler or tooling around it should support this.

## 💻 Use Cases

typescript module compile target with amd, no webpack build step (I think they handle the cycles.)

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/pull/21780 and associated discussion.
