### ISSUE TITLE
TS2502 when referencing a non-existant property of an object to type another property of that object

### ISSUE THREAD

**Issue by bl-ue** [microsoft/TypeScript#55076]
# Bug Report

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (3.3.3 to Nightly)

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=0&ts=3.3.3#code/PTAEHUHsCcGsGdQAoB2lQGMCW0MFcAbAQ2lAFNpoYBKAOgCgCyAXUSAIwCsBGALlADeoIgAUqABwrMAnvxmTIAMzZduoAL4BuevRCgAwgEkASvoCqAGQCCx0AFFjxgPLHGLFZwBM-IaIlTZUHkyJQ9PWjQUOwAPLHhmIhRmMUhJaBkNbSA

### 💻 Code

```ts
// Works (no circular error).
let obj1: { aProperty: typeof obj1 };

//          TS2502 vv
let obj2: { aProperty: typeof obj2.nonExistantProperty };
//          ^^^^^^^^^ 'aProperty' is referenced directly or indirectly in its own type annotation. ts(2502)


```

### 🙁 Actual behavior

There are several errors in the above example, but only the one underneath `aProperty` in the second example is relevant, and it's TS2502 `'aProperty' is referenced directly or indirectly in its own type annotation`.  I don't understand why it's not happening in the first example but it is happening in the second, since both reference the object inside itself.  `nonExistantProperty` doesn't even exist, and `aProperty` isn't being referenced at all.

### 🙂 Expected behavior

TS2502 shouldn't be happening, because `aProperty` isn't being referenced at all, either directly or indirectly.

**Comment by RyanCavanaugh** [comment]
I'm not sure what the intended upshot of this example is. Once there's one error in a program (and particularly in a *line*), all other errors are somewhat open to whatever recovery interpretation we have to do.

**Comment by fatcerberus** [comment]
Yeah, this code produces an error regardless:

> Block-scoped variable 'obj1' used before its declaration.

At this point, any other errors on the same property are a moot point.
