### ISSUE TITLE
Excess properties allowed in function weak return types

### ISSUE THREAD

**Issue by michaldudak** [microsoft/TypeScript#55078]
# Bug Report

### 🔎 Search Terms

excess, extra

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about excess properties

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?esModuleInterop=false&isolatedModules=false&allowSyntheticDefaultImports=false&exactOptionalPropertyTypes=true&ts=5.1.6#code/JYOwLgpgTgZghgYwgAgKIFsAOYCeBJcaeJZAbwF8AoS0SWRFAOQHsQItcC7iVTkB9APwAuZAFcQAaxDMA7iGRUaheiQDKzdBADyYABbQuRBmUrJzyAB4jkAZzBRQAcwDclJbkwptAIwBWEAhg2lAAwnAANhE+iJIAPAAqAHzIALxmyAA+yAAUGlq6BlBGqigAZMgJAJQZ2Tk5VWkpeZo6+oYqPMgV1VVulAD0A8gAAmC2ALQQll5BU1BQzFCUCKz2yHCivgFBIeFRMQjxGNj4nQwpqWTI00i2tgAKi5iiAIyK-UOj41MzgWDzRbLVYgdbwLb+f57SLRWJxE6cc5IS65RqpZp8W4Qe5PZgvZDvch9ZBfWR6HDIAAmzGxIAA5GBkPpgLZkAg4GJbCg4ApoECmcxmIJqF8xpNprMAXylis1oyfBCdsEwjDDvEWGwOGduBc0tcsTjnm8PiLhmLfpLATKQWCFchtlCVQc4Rr2KcSjwUQ0mrlMZY7o8jQTFH1KEA)

### 💻 Code

```ts
interface EmptyInterface {}

interface NonemptyInterface { _?: unknown }

interface SomeOtherInterface {
    x?: string;
}

type ObjectOrCallback<T> =
  | (SomeOtherInterface & T)
  | (() => (SomeOtherInterface & T));

// @ts-expect-error
const a: ObjectOrCallback<EmptyInterface> = { excessProp: 1 };

const fa: ObjectOrCallback<EmptyInterface> = () => ({ excessProp: 1 }); // why doesn't this cause an error too?

// @ts-expect-error
const b: ObjectOrCallback<NonemptyInterface> = { excessProp: 1 };

// @ts-expect-error
const fb: ObjectOrCallback<NonemptyInterface> = () => ({ excessProp: 1 });
```

### 🙁 Actual behavior

The function `fa`, which is defined as having the return type `{ x?: string } & {}` can return an object with extra properties, whereas function `fb`, having the return type `{ x?: string } & { _?: unknown}` cannot. This seems to be inconsistent.

### 🙂 Expected behavior

Since both `EmptyInterface & SomeOtherInterface` and `NonemptyInterface & SomeOtherInterface` are types with optional properties only, both `fa` and `fb` should not allow excess properties on their return type.

**Comment by MartinJohns** [comment]
> // why doesn't this cause an error too?

Because your function has no return type annotation, so the return type is inferred. Then the type of your function is checked for assignability, in which case excess property checks are not occurring anymore. This is working as intended, and there are numerous issues about this.

**Comment by michaldudak** [comment]
Why the behavior of the `fb` function is different, though?

**Comment by RyanCavanaugh** [comment]
Duplicate #241
