### ISSUE TITLE
npm package scripts should be recognized by typescript (webstorm 11 has it!!)

### ISSUE THREAD

**Issue by HansS** [Microsoft/TypeScript#5507]
npm scripts
A new npm scripts tool window lists all the tasks specified in the package.json scripts section and allows you to easily run any of them with a simple double-click. You can also create a new Run configuration for an npm script task and run it with the familiar Run... action.

**Comment by HansS** [comment]
Hi Kelly,
sorry this is meant for Visual Studio Code!
kind regardsHans

Date: Tue, 3 Nov 2015 03:18:09 -0800

**Comment by mhegazy** [comment]
For VSCode issues, please file them on the VSCode issue tracker: https://code.visualstudio.com/Issues/List
