### ISSUE TITLE
Spread types may only be created from object types.

### ISSUE THREAD

**Issue by infacto** [microsoft/TypeScript#55083]
# Bug Report

### 🔎 Search Terms

> Spread types may only be created from object types. ts(2698)

### 🕗 Version & Regression Information

TypeScript version: `~4.7.2`
No error on TS 4.6.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/MYewdgzgLgBADiCECWAjANgUwKpgCaYBmyYmeMAvDAK75ElkDcAsAFCiSwioBWlMAbxgA6UQiRosuAsVJ4ANDHCYAXDACMMAL4tWQA)

### 💻 Code

```ts
const possibleUndefined = undefined;
const obj = { ...possibleUndefined, one: 1 };
```

### 🙁 Actual behavior

Error: 

> Spread types may only be created from object types. ts(2698)

### 🙂 Expected behavior

No error. This is no problem in JavaScript. You can use spread on such values.
In my case, it's intentional that I optionally extend the object with spread. No need for error.
Btw. do TS support warning instead of error? Workaround use `Object.assign` instead. But seriously why error?

Update: You can't even not fallback to object. Still same error:
```ts
const possibleUndefined = undefined;
const obj = { ...(possibleUndefined ?? {}), one: 1 };
```
but this works. but is not really nice:
```ts
const possibleUndefined = undefined ?? {};
const obj = { ...(possibleUndefined), one: 1 };
```
But I would rather disable this error. Or only show this error on values who will really not work for spread (on JS).

**Comment by MartinJohns** [comment]
This is intentional: https://github.com/microsoft/TypeScript/issues/20153#issuecomment-516193778

**Comment by fatcerberus** [comment]
> ```ts
> const possibleUndefined = undefined;
> const obj = { ...(possibleUndefined ?? {}), one: 1 };
> ```

[This works fine (Playground link).](https://www.typescriptlang.org/play?#code/MYewdgzgLgBADiCECWAjANgUwKpgCaYBmyYmeMAvDAK75ElkDcAsAFCiSwioBWlMAbxgA6UQAoESNFlwFipcgH5FggL4BKADQxwmAFwwAjDFUtWQA)

**Comment by infacto** [comment]
I missed the return type `string` from the union type in my code, sorry. [See here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoHsC2EDyAjAKwgTGQG8BYAKGVuTAHd0AuZEAV0z2gG5qBfatQToQAZ1IBzCGHxESyALzIAFAEpWGbHOKkAPsglRQk5AfYgAJhBigIls23YAbZ0oB85anWQjxpADc4Z3YIMSVkAG0La1sQewAacnomVgAmZH4kgHIAGRxc7KSOVwBdbzooGXYoEGQgkLDIgFk4MAALADoYZ3R0KBVWjs6oOCssdWQAKnrg0LFO5wgQSQ61Ur4qQSphUQlZxojpWUJddU2-ffRCCLJkToeG0KTRCFYARkzNoA). So it's correct, I wouldn't spread a string here either. And nullish (undefined, null) works. But why is "definitely undefined" not allowed since it wouldn't cause any problem? Anyway...

It seems that I found another issue. The inline `(value  ?? {})` didn't work in my case of possible type `string`, what's correct. But I was able to bybass it a line above, as shown in my initial post. See demos below:

See demos: 
- [Demo A](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoHsC2EDyAjAKwgTGQG8BYAKGVuTAHd0AuZEAV0z2gG5qBfatQToQAZ1IBzCGHxESyALzIAFAEpWGbHOKkAPsglRQk5AfYgAJhBigIls23YAbZ0oB85anWQjxpADc4Z3YIMSVkAG0La1sQewAacnomVgAmZH4kgHIAGRxc7KSOVwBdbzooGXYoEGQgkLDIgFk4MAALADoYZ3R0KBVWjs6oOCssdWQAKnrg0LFO5wgQSQ61Ur4qQSphUQlZxojpWUJddU2-ffRCCLJkToeVBtDkAH5X8n41JNEIVgBGTKbIA): Correct
- [Demo B](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoHsC2EDyAjAKwgTGQG8BYAKGVuTAHd0AuZEAV0z2gG5qBfatQToQAZ1IBzCGHxESyALzIAFAEpWGbHOKkAPsglRQk5AfYgAJhBigIls23YAbZ0oB85anWQjxpADc4Z3YIMSVkAG0La1sQewAacnomVgAmZH4kgHIAGRxc7KSOVwBdbzooGXYoEGQgkLDIgFk4MAALADoYZ3R0KBVWjs6oOCssdWQAKnrg0LFO5wgQSQ61Ur4qQSphUQlZxojpWUJdSYB+c-J+Tb999EIIsmRO14bQpNEIVgBGTM2gA): Should not work or did I miss something? Becuase `??` should only handle nullish values.

**Comment by MartinJohns** [comment]
> But why is "definitely undefined" not allowed since it wouldn't cause any problem? Anyway...

Did you read the comment I linked? Wanting to spread `undefined` is clearly a logic error. It makes absolutely no sense.

**Comment by fatcerberus** [comment]
`{ …definitelyNullish }` is always the same as `{}` so there’s no reason to ever write it. If you do then TS errors because there’s almost certainly a mistake in your program.

> But why is "definitely undefined" not allowed since it wouldn't cause any problem?

“It works at runtime” is not a valid counterargument for type errors, see https://stackoverflow.com/questions/41750390/what-does-all-legal-javascript-is-legal-typescript-mean

**Comment by infacto** [comment]
Ok, I just wondered for the demo code. In real code you maybe have never undefined-only values. Anyway...

I rather wonder why I can bypass the error in `Demo B` but not in `Demo A`. Is that correct? The type should still be possible `string`. What do you think?

- ✔️ [Demo A](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoHsC2EDyAjAKwgTGQG8BYAKGVuUgA8wAuZAZzClAHMBuagL7VqCdCA7JuEMPiIlkAXmQAKAJSsM2WcVIAfdpx7J9AVxAATCDFARzx5CBMAbJ4oB85anWSjxpAG5wTiYQbIrIANpmltYgtgA05PQQTKwA5ABi6OhpyAKJaQBCcFBpiY4uALpedFDSJlAgyIHBoREAsnBgABYAdDBO2VDKnT29UHAWWGrIAFTNQSFsvU4QINw9qpX8VEJUImISLSHhUjKEOmo7vhLohOFkyL3PyscoAPzv5AKqiWIQrAAjHkdkA): Is not possible because of possible `string` which is correct. 
- ❌ [Demo B](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoHsC2EDyAjAKwgTGQG8BYAKGVuUgA8wAuZAZzClAHMBuagL7VqCdCA7JuEMPiIlkAXmQAKAJSsM2WcVIAfdpx7J9AVxAATCDFARzx5CBMAbJ4oB85anWSjxpAG5wTiYQbIrIANpmltYgtgA05PQQTKwA5ABi6OhpyAKJaQBCcFBpiY4uALpedFDSJlAgyIHBoREAsnBgABYAdDBO2VDKnT29UHAWWGrIAFTNQSFsvU4QINw9qpX8VEJUImISLSHhUjKEOjMA-FfkAju+EuiE4WTIvR-HEIliEKwAjHkdkA): Should not work or did I miss something? Becuase `??` should only handle nullish values. It should be still possible `string` or not? It should look like [that](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoHsC2EDyAjAKwgTGQG8BYAKGVuUgA8wAuZAZzClAHMBuagL7VqCdCA7JuEMPiIlkAXmQAKAJSsM2WcVIAfdpx7J9AVxAATCDFARzx5CBMAbJ4oB85anWSjxpAG5wTiYQbIrIANpmltYgtgA05PQQTKwA5ABi6OhpyAKJaQBCcFBpiY4uALpedFDSJlAgyIHBoREAsnBgABYAdDBO2VDKnT29UHAWWGrIAFTNQSFsvU4QINw9qpX8VEJU1KsBiyhKUjKEOmo7wDAqYACeAA4Q6LctIYoKSmkcXOtpqk8NDo7xOSUYLAWrTyOz2vgk6EI4TIyF6aNBiTEEFYAEYYdQgA).

**Comment by MartinJohns** [comment]
The difference is subtype reduction, which may occur at any point, but doesn't have to. In case of Demo B the type is reduced to `{}`, which is the supertype of both `SomeObject` and `string`.
