### ISSUE TITLE
Add new script element kind for proposed string completions

### ISSUE THREAD

**Issue by zardoy** [microsoft/TypeScript#55086]
# Suggestion

## 🔍 Search Terms

Non-strict completion kind

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion and 📃 Motivating Example

I propose to add a new script element kind for completions for types that can be any string, but still have string literal suggestions. For example:

```ts
declare const foo: "test" | "bar" | (string & {})
declare const bar: "test" | "bar"

if (foo === "|") {
  // ...
}
```

[ts-playground](https://www.typescriptlang.org/play?ssl=4&ssc=1&pln=5&pc=1#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAEQYiZHwA+xARrBdQBSYwCWKA5vAGTwDeAXwCUAKFCRYCZOix0YhEmQwNa9ESNbZ4jXEngBeQ8SJD+I+PAD0l+ADp7IgUA)

Here, vscode shows the same completions lists for `foo` and `bar`, however `foo` can have any string actually:

<img width="375" alt="Screenshot 2023-07-20 at 20 21 48" src="https://github.com/microsoft/TypeScript/assets/46503702/d21589a0-e154-48fa-bf96-edd7279af411">

My proposal here is to change completions list somehow (like adding new script element kind [here](https://github.com/microsoft/TypeScript/blob/f38e0fe6f0ef5aec742dc0ff5081a6362e4a585a/src/services/types.ts#L1561)) so the user can see that he can actually ignore these completions and use any arbitrary value instead. For example:

```ts
declare const foo: "test" | "bar" | (string & {})
declare const bar: "test" | "bar"

if (foo === "something-else") {
  // ...
}
```

## 💻 Use Cases

This would be useful for types using pattern from above (`'proposed-variant' | (string & {})`). And also for the following issues:
- https://github.com/microsoft/TypeScript/issues/29729
- https://github.com/microsoft/TypeScript/issues/52736

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.

**Comment by zardoy** [comment]
Sorry, I must admit it could be hard to understand motivation from the initial description of the issue. However, I updated the body of the issue so I hope it should clear now what I want to propose. Again, it's just a proposal that I wanted to share with you, if you don't find it useful, feel free to close this one.
