### ISSUE TITLE
Stimulsoft

### ISSUE THREAD

**Issue by Andrew1000** [Microsoft/TypeScript#5508]
Name: Stimulsoft
Homepage url: https://stimulsoft.com
Brand Guidelines/Licensing: use our logo
Logo: http://www.stimulsoft.com/images/stories/Stimulsoft.png

**Comment by mhegazy** [comment]
looks like the site does not support `https`, the working Homepage url is http://stimulsoft.com

**Comment by Andrew1000** [comment]
Dear Mohamed,

Thank you for the reply.

Yes, our website does not support https. Is this a critical issue?

Waiting for your reply.
Thank you.

2015-11-03 20:57 GMT+03:00 Mohamed Hegazy <notifications@github.com>:

> looks like the site does not support https, the working Homepage url is
> http://stimulsoft.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/TypeScript/issues/5508#issuecomment-153433684>
> .
>



-- 
Best regards,
Andrew Savin
Stimulsoft Team

http://www.stimulsoft.com/

**Comment by mhegazy** [comment]
thanks. http works just fine.

**Comment by Andrew1000** [comment]
Thank you for the reply.

2015-11-04 9:59 GMT+03:00 Mohamed Hegazy <notifications@github.com>:

> thanks. http works just fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/TypeScript/issues/5508#issuecomment-153606792>
> .
>



-- 
Best regards,
Andrew Savin
Stimulsoft Team

http://www.stimulsoft.com/
