### ISSUE TITLE
return type of function being union instead of one-of-union 

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#55089]
# Bug Report

### 🔎 Search Terms

return type inference, discriminating union

### 🕗 Version & Regression Information

ø

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?jsx=0#code/JYWwDg9gTgLgBAbzgQwM6oKawDRwKICOArsgDapwC+cAZlBCHAOQyrI0ZMBQXA9L-gAeycKQxwibAObiA7sBgALOADEIEAELIocGAE8wGLvsOr1cALyIucW7XUAuOKhhRgAOykBuLpR-GDcS0dKwQbOwAjbSd3IhAIrB8-HhNxNU1tS2s7ewgndJ8cqKgnYKT-VLgAaQ8AEwxagB4AFQA+LLCcgG0quA84AGsMPQgaOGaAXScuob0nKtwANzInZp6Jid8Z4dHxza4aIncAYxhgCHddDBcW1oAKADon7b0lsinquobbgEpsuygGBgRCgl2WpF8-n4cAAAqwALQYQSGU6IqD0HTw9qsODHBhgUjIDwUJEomANUh6XSKZDwbRSVBdACME2ciggRFItTgCTMEC4ePcLjgWAxACYsuSbulgvcmDR1ExcEhik4AAxUH5QgRw1CI5EYVGi6BwLG6Ch40REoUig2nClUpS0lBQBnM1modmc7nBAUXYXGqBMyXXGCNGXaOXFJWIXJOJguNyeJia7W0eiMJTiQMUZARCCLOTiAbuCCyF1ull9ChgeiGKCU3SBWp8AQRIjwLNwQHA0ENODgojiYAUFzAUikOAAA3ScAAPnBglO4A4ADp+oXwBUQEPS9Syu7yxXKuPMRMeKQpyhajfC4q7sMRqBR7QxlXROAa69p+G-44d394S4NBMFgRpCBIchGlSXZt1wdJWnuH5gPQLAwwgshUGgwJdmKXBZSQrggA)

### 💻 Code

```ts
import { assert, Equals } from 'tsafe'

// Example usage with FooBar type
type Foo = {
    foo: string;
};

type Bar = {
    bar: number;
};

type FooBar = {
    foo: Foo;
    bar: Bar;
};

type Kinded<T> = {
    [K in keyof T]: [key: K, val: T[K]]
}[keyof T]

function test<T>(...[key, val]: Kinded<T>) {
    return val
};

// @ts-expect-error -> ts complains expectedly that args[1] should be Foo
const error2 = test<FooBar>('foo', { bar: 0 });

// @ts-expect-error -> ts complains expectedly that args[1] should Bar
const error1 = test<FooBar>('bar', { foo: 'string' });

// from the errors above we know args[1] is properly typed
// but the returned value is still `Foo | Bar` :\
const foo = test<FooBar>('foo', { foo: 'string' });
const bar = test<FooBar>('bar', { bar: 0 });

// ---cut---
assert<Equals<typeof foo, Foo>>()
assert<Equals<typeof bar, Bar>>()
```

### 🙁 Actual behavior

Firstly, I do understand that the function defines arguments as (basically) `declare function test<T>(...args: [keyof T, T[keyof T]])`, and so the compiler thinks _"test() returns args[1] which is `T[keyof T]` so the returned type should be `T[keyof T]`"_ (which in my example is `Foo | Bar`).

Where I think this stops to be logical is that type inference based on `args[0]` actually works great for function arguments: it successfully narrows the type of `args[1]` due to the discriminating union created by `Kinded`. We can see that this happens well thanks to the `error1` and `error2` constants.

### 🙂 Expected behavior

So, since the function only contains `return val` (`args[1]` of the tuple), and since the type of val was properly inferred in the function arguments, i guess it should be expected that return type of the function should be properly inferred rather than the static union of.

**Comment by y-nk** [comment]
As a workaround, there's possibility to curry the function, which would end up as a workaround for partial type inference. Posting here so that people interested can find a temporary solution.

```
function test<T>() => <K extends keyof T>(key: K, val: T[K]) => val
```

instead of expected:

```
const shouldBeFoo = test<FooBar>('foo', { foo: 'str' }) // ← type of `shouldBeFoo` is Foo | Bar
```

you'll have to add `()` (...for no other reason than a TS one)

```
const isFoo = test<FooBar>()('foo', { foo: 'str' }) // ← type of `isFoo` is Foo
```

**Comment by y-nk** [comment]
@jp-diegidio thanks for taking the time to look at my problem 🙏 

there's something not on par with my actual issue in your proposal, is that `TypeMap` is hardcoded into `test`. What i was looking for is to do exactly the same _but_ with a "pluggable" type map.

you can see here:

```ts
const error2 = test<FooBar>('foo', { bar: 0 });
```

that i'm purposely passing the type into the function's generic. The intent behind is that this function should be reusable for anything extending `Record<string, any>`.

**Comment by jp-diegidio** [comment]
@y-nk  You are welcome and thank you too, I myself am learning TS...

I have played with it a little bit more and below is the best I could get (so far), still there is (IME) something "smelly" with this pattern, anyway maybe you/others can take it from here.

```ts
type Foo = {
    foo: string;
};

type Bar = {
    bar: number;
};

type Keyed<M> = Record<keyof M, M[keyof M]>;

type TypeMap = {
    foo: Foo;
    bar: Bar;
};

// without the default for param `T`, cannot be called with
// only one type argument instead of getting a union:
function test<M extends Keyed<M>, T extends M[keyof M] = M[keyof M]>(val: T): T {
    return val;
};

// @ts-expect-error : Argument of type '{ bar: number; }'
// is not assignable to parameter of type 'never'
const errorFoo = test({ bar: 0 });
// @ts-expect-error : Argument of type '{ foo: string; }'
// is not assignable to parameter of type 'never'
const errorBar = test({ foo: 'string' });

// returns the union `Foo | Bar`
const unionFoo = test<TypeMap>({ foo: 'string' });
// returns the union `Foo | Bar`
const unionBar = test<TypeMap>({ bar: 0 });

// returns exactly `Foo` (but, isn't this just a
// convoluted way to say "I want Foo" to begin with?)
const foo = test<TypeMap, Foo>({ foo: 'string' });
// returns exactly `Bar` (but, isn't this just a
// convoluted way to say "I want Bar" to begin with?)
const bar = test<TypeMap, Bar>({ bar: 0 });
```

[Link to code in playground](https://www.typescriptlang.org/play?jsx=0#code/C4TwDgpgBAYg9nKBeKBvAUFLUBmCBcUAzsAE4CWAdgOYDc6AvveqJFAEICGpyam2AI26FKAVwC2AiKXpN0LcNADSEEBAAmAHgCyAPl4AlCAGM4pLQGtVcHFG0AaOwG0rIG3YC6u5q2gAVRW1OMF4MbFwCWAR6cKFSQi4ZRmYAehSoAHdyYAALOFFgKFzodQgcTlEAG0K8HjBuTnEoAAM-ZsdjTkpKOEKpKE7Kyo1M7Jz0NKg4SkqQKcpoXyhuagkISkKqEghOdSnbaghgYCpqZahRSnJp-HQcS+MT6aKIEh0oCAAPYHX1IigVGotHpHH4Pt9fv9tC5rLZtB5eNDXO54boABQAN04lUIfgAlLi+OFSEdRKRKFAsZVZKl0gABYBEAC0X0gjxZpFIZighAAgqRVuJ1oV3EsAOSoKBxEQSKQyKAMMUTdLkf49QqcIhEcjUSicATDIqIeqkRpHaT7IqKKBihYY6RK0yUEgfTlmeCIFA-EhoyXSqAABgVePokwZzNZJmAHK5PD5ArWG0t4sleDghBIFBotAVSsmqqg6uWWp1eoNi2NDSFPx4outtog9tIjumLukscSvG9wF9EXTNszpzFwdpUBJwDJzqKOWgl2uFOaHqgAB8ONxmugnS659Ml17XsBNAFIEEwOjU5ExYOaMOGCHlWPSeT-sULldnouECu16QN1vCjulCdvubzHhAp7nlKwiBiO8iTOOk7-F8nCPLMLQes0UBogIBSOKqlBioUuQFgAVqILqcA+ToYnAlQFCMGScHMwCIEQTFQAARAAkpkXSFB6HFGlKEDUFQoy5AA-Him6tjUX4gYeYGno4HqQWmhBXmQQ6wfBT5TshqFzM0iSYdhuFQPhhHTqR5EalR0w0XRPx7IxzGsex3G8UmiSCSxwmiRSWSSdJ-5QTwClHoEwSOIkkH+kGd70EAA)

**Comment by jp-diegidio** [comment]
This improves on my previous code and might even be it (up to you to say), surely it's the nearest I can get that still makes sense to me.  I have shuffled things around a bit, so if one wants it's still parametrizable on a "type map", though at a quite different level here:

```ts
function check<T = never, U extends T = T>(val: U): U {
    return val;
};

type Foo = {
    foo: string;
};

type Bar = {
    bar: number;
};

type TypeMap = {
    foo: Foo;
    bar: Bar;
};

// @ts-expect-error : Argument of type '{ bar: number; }'
// is not assignable to parameter of type 'never'
const errorFoo = check({ bar: 0 });
// @ts-expect-error : Argument of type '{ foo: string; }'
// is not assignable to parameter of type 'never'
const errorBar = check({ foo: '' });

// returns `Foo` as expected
const foo = check<TypeMap['foo']>({ foo: '' });
// returns `Bar` as expected
const bar = check<TypeMap['bar']>({ bar: 0 });

// returns `Foo` as expected
// (indeed, `TypeMap['foo']` is equivalent to just `Foo`)
const foo2 = check<Foo>({ foo: '' });
// returns `Bar` as expected
// (indeed, `TypeMap['bar']` is equivalent to just `Bar`)
const bar2 = check<Bar>({ bar: 0 });
```

[Link to code in playground](https://www.typescriptlang.org/play?jsx=0#code/GYVwdgxgLglg9mABBAFgUwgawDwBVEC8iYaAbmgE4A0iAqomgB5RpgAmAzovkbgHwAKUgEMANgC46ASkn0A3gChEyxBTRQQFJCNEBuBQF99CqAE8ADmkQAxOHEKJFKxMDuSOUCjDABzfUYUTCysAIWEKBycVACNwyTAQAFtoyn9jM0tuYIBZYXNIpRVXOElbOH1nWIpJMIo0wIB6BsQAASgOAFomS2guigo4CMkAQQofJNYoRDhgRAyrAHI5RCr4pJS6xAMFhSbEGC4wOCnhDg4YHzBhaNErKHtzcOFE9Upp2fnEBZJyCh2IBAeBj9QZlByoDCYATLVaIAAMWyk+j2bU63QwUD6AyGiFG4xeYCmMzmwS+y2K7k83j8Wx2ewOxGOiFO50u11ucweTxeLAixM+3zIlH+gKmlGxtXB6Cw0Jcbi+C0Rxj2ag0Wi4AAMyhrmVx0dA0GwFACwEDilLIXgcnkANoLYoLAC6gnJ8oWioMSN2zVVmlNiA1tR1pwYjB6LCNJqBVQtWCtlly5jtVSdLpWcXhSsaPvUfs12t1ofDhu9iAE3jYaENNA1uGtSftdidOoZaAAjiAYDpJpzEAArEBArV2DVSY2iuVwABMsZwZTTFIVWZVufVAaDhf1EdL5fYVbYNbrCdtCxTjpbeo7XbEPfu-cHU0D4VH49NUyqM6IELjtTTsIRnr6EAA)

**Comment by RyanCavanaugh** [comment]
I don't understand what the alleged defect is. You have type arguments in all these positions, so of course `f<T>(a)` and `f<T>(b)` aren't going to return different types.

**Comment by fatcerberus** [comment]
If I’m reading this right, OP seems, in general, to expect `<T, U>(x: T | U) => x` to return `T` or `U` only depending on what was passed in, but that’s not how return type inference works

**Comment by y-nk** [comment]
on the side i've written in the ticket description that i do understand what you tell i don't.

> Firstly, I do understand that the function defines arguments as (basically) declare function test<T>(...args: [keyof T, T[keyof T]]), and so the compiler thinks "test() returns args[1] which is T[keyof T] so the returned type should be T[keyof T]" (which in my example is Foo | Bar).

where i stopped understanding this is when a discriminating union comes into play.

**Comment by RyanCavanaugh** [comment]
Please don't post screenshots of code.

It seems like this is more of a question than a bug report; nothing outlined here is indicative of a defect.
