### ISSUE TITLE
TSC tries to compile my .d.ts files, then spits out errors from these attempts.

### ISSUE THREAD

**Issue by kdawg1406Aurelia** [Microsoft/TypeScript#5509]
When I compile my project using `tsc` it tries to compile my .d.ts files event though the /typings folder is excluded in my 'tsconfig.json' seen below.

Why is this happening?
Why are .d.ts files compiled?

```
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "target": "ES5",
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules",
    "typings",
    "src/jspm_packages"
  ]
}
```

**Comment by mhegazy** [comment]
do you have a `/// <reference ` in one of your files to the .d.ts file in question?

**Comment by kdawg1406** [comment]
Yes.  All of my regular .ts files have ///<reference... 

Isn't that why we have them; so they can provide a nice code-time experience?

Did I miss something?

**Comment by mhegazy** [comment]
If you have a /// reference to a .d.ts it will be included in the compilation. The OP did not expect this to happen.

**Comment by kdawg1406** [comment]
Who is the OP?

Seems bizarre that the TSC would ever try and compile a ".d.ts." file.

**Comment by mhegazy** [comment]
.d.ts files are normal files. they just have no implementation. .d.ts can be authored by hand, and you can have errors both syntactic and semantic in your .d.ts files.
when including a .d.ts file in your compilation, it will be type checked, any errors will be reported, but no output will be emitted.

**Comment by mhegazy** [comment]
OP => Original Post

**Comment by ithinkihaveacat** [comment]
I think this is a recent change, but tsc will now attempt to compile packages in `node_modules/@types`, which gives rise to the same error. To prevent this, specify `types: []` in `tsconfig.json`. ([More info](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types).)
