### ISSUE TITLE
Discriminate string or number literal from general type. 

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#55095]
# Suggestion

## 🔍 Search Terms
- exclude string literal from string type
- exclude number literal from number type
- discriminate string literal

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

I want to be able to write code such as

```ts
type ApiResponse<Body> = {status: 200, body: Body} | {status: number, body: unknown}

// Get this type from calling an API...
declare const response: ApiResponse<{text: string}>

if (response.status === 200) {
  response.body.text // this is a string
} else {
  response.body // this is unknown 
}
```

Fundamentally, this seems like the type checker needs to evaluate literal types before more general types.

I've also tried using `Exclude` but that doesnt help for obvious reasons.

```
type ApiResponse<Body> = {status: 200, body: Body} | {status: Exclude<number, 200>, body: unknown}
```

This is also useful for strings and string literals too, e.g. `{type: "a", a: number} | {type: string, value: unknown}`

## 💻 Use Cases

I think its surprisingly common that there are well known types we can use to narrow down a value, while there is still a large unknown amount of types that we aren't aware of an perhaps don't even care about.

The variety of http responses I could get is much larger than I can properly type (unfortunately), but the same can be said for progressively typing a large library. Perhaps I only care about a few different object types, but I still want there to be a catch all for the things I haven't typed yet and might run into...

**Comment by RyanCavanaugh** [comment]
You'd need negated types for this to work properly, since this is a legal (but unsound) construction if this were allowed:
```ts
const n: number = 200;
const m = { status: n, body: 42 };
const response: ApiResponse<{text: string}> = m;
if (response.status === 200) {
  response.body.text // claimed as string, but is number
```

**Comment by ccorcos** [comment]
Ah yeah, i guess that's basically what I was getting at with `Exclude`...

https://github.com/microsoft/TypeScript/issues/4196

Seems really useful, but probably a pretty big amount of work to implement. 

Thanks for the help!
