### ISSUE TITLE
Can't reassign to a narrowed union type

### ISSUE THREAD

**Issue by alecgibson** [microsoft/TypeScript#55102]
# Bug Report

### 🔎 Search Terms

reassign narrowed union type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about narrowing

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/C4TwDgpgBAChB2ATAlvA5gKQPYCMoF4oBvAZ2AENgIAuKAckiVTToF8BuAWAChRJYATlgDGEEiQiJseQqQpVaDIaPGS2XXuGjSCsBCnQ6APoJFiJU3Bp4AzAK7xhwZFnhREWaQAoAVrlrSAJS0AG5YyIjEPFBQyDZQvrgAdGSU0PgZ9GDK5mqBUAIQwHYC8BoxAPQV7lhQJFgAttAA7lgCANbRUH44KfLpWTmqiHQarDxAA)

### 💻 Code

```ts
type PendingJob = {state: 'pending'};
type ProcessedJob = {state: 'processed'};
type Job = PendingJob | ProcessedJob;

function doJob(job: Job): void {
  if (job.state === 'processed') return;
  // do some work
  job.state = 'processed'; // Type '"processed"' is not assignable to type '"pending"'. (2322)
}
```

### 🙁 Actual behavior

The type is narrowed, and cannot be reassigned to the wider type declared at the start of the function.

### 🙂 Expected behavior

The type can be widened when reassigning, since the variable was declared as the wider type.

I think I understand (broadly speaking) why the compiler doesn't like this; I just found it a little surprising.

To be fair, this can be worked around (in this simple example at least) by redefining the types:

```ts
type Job = {state: 'pending' | 'processed'};
type PendingJob = Job & {state: 'pending'};
type ProcessedJob = Job & {state: 'processed'};
```

In our real-life code, the types are obviously more complicated than this, and can't be "inverted" like I've done here. For example:

```ts
type PendingJob = {
  state: 'pending';
  input: any;
};

type ProcessedJob = {
  state: 'processed';
  output: any;
  processedAt: Date;
  // etc.
};

type Job = PendingJob | ProcessedJob;
```

**Comment by jcalz** [comment]
In your example real-life code, you couldn't modify `state` without violating the rest of the structure, anyway.    Do you have an example where it's safe and useful to switch an object to different members of a union of object types by writing to one of its properties?  It seems that the only time that can actually happen is when you don't need a union of object types to start with, and the property should just be a union instead.

**Comment by alecgibson** [comment]
> you couldn't modify `state` without violating the rest of the structure, anyway

Yeah I realised that after I wrote it. I'm not sure I can think of one off the top of my head (and this is the first time I've run into this in 6 years of TypeScript development!).

It's very probable that this is "working as intended"; I just thought I'd document it as I did initially find it surprising.
