### ISSUE TITLE
Type checking doesn't work properly with never

### ISSUE THREAD

**Issue by jakeleventhal** [microsoft/TypeScript#55103]
# Bug Report

### 🔎 Search Terms

never type check

### 🕗 Version & Regression Information

- This is a type check issue
- This has always been here

### ⏯ Playground Link

See code section. The problem is easy to reproduce

### 💻 Code

```ts
const numFunc = (num: number) => {
  return num;
}
const stringFunc = (str: string) => {
  return str;
}

type Obj = {
  a: string;
  b: number;
  c: never;
}

const someFunc = (x: Obj) => {
  numFunc(x.c)
  stringFunc(x.c)
}
```

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

Passing in `x.c` should be a type error

**Comment by RyanCavanaugh** [comment]
`never` is the bottom type; definitionally this must not be an error.

**Comment by jakeleventhal** [comment]
What type should `c` be declared to be if i want to ensure c is never accessed then?

Use case is the following

```
import { NextApiRequest, NextApiResponse } from 'next';

interface RouteRequest extends NextApiRequest {
  body: never;
  query: { userId: string };
}

export default myRoute = async (req: RouteRequest, res: NextApiResponse) => {
  // I want a type error here
  const { id } = req.body;
}
```

Is the suggested pattern to just declare `RouteRequest` as:
```ts
interface RouteRequest extends Omit<NextApiRequest, 'body'> {
  body: never;
  query: { userId: string };
}
```

**Comment by RyanCavanaugh** [comment]
```ts
interface RouteRequest extends Omit<NextApiRequest, "body"> {
  query: { userId: string };
}
```

**Comment by RyanCavanaugh** [comment]
`Omit` is the correct approach, yes

**Comment by jakeleventhal** [comment]
Thanks

**Comment by RobertSandiford** [comment]
> `never` is the bottom type; definitionally this must not be an error.

Can you explain this?

**Comment by RyanCavanaugh** [comment]
The empty set is a subset of every set
