### ISSUE TITLE
Type rules are not followed for parent classes with generic types and child class fields

### ISSUE THREAD

**Issue by RobertSandiford** [microsoft/TypeScript#55113]
# Bug Report

Child class, fields, properties, generic class inheritance, type rules, additional properties in objects

Child class fields do not follow type rules

### 🕗 Version & Regression Information

Seen in 4.9.5 + 5.1.6. Not aware of a version without it.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about anything relevant

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230720&ssl=28&ssc=2&pln=1&pc=1#code/MYGwhgzhAEAKA8AVAfNA3gWAFDWgFwH4AuaRbAX22zwE8AHAU2gFVoBedbXMEgOwFcAtgCMGAJy7RhfIaIlZKWbKEgwAwgEZoDAB54GvACYwEzVJhz526aAHpb2nY2D7D2sWID2YgDRToAJYwgkEQAbwA5pLcJBo+koqKyp68EHjQ-CSsHBYx0HGS0tAATPGWwCQAzHYOus6u7l6+0MCBMGCGhgF4ASlgIBRUWCpQ0GrFjvpGJvBmnJbpOdHQPPlluLhFpcsV0NX2Gbx1DC4MhmcgNCsgIJ4A7mcJFEA)

### 💻 Code

```ts
class P<T> {
  t?: T
}

type U = {
  a: number
  b: number
}

class C1 extends P<U> {
  t = { // expected error, b is missing
    a: 1,
  }
}

const u: U = {
  a: 1,
  b: 2,
  c: 3 // expected error, c is additional
}

class C2 extends P<U> {
  t = {
    a: 1,
    b: 2,
    c: 3 // unexpectededly allowed
  }
}
```

### 🙁 Actual behavior

The (object with 1 property) assigned to C1<U>.t does not match the type U. As expected.
The (object with 3 properties) assigned to u does not match the type U. As expected.
However the (object with 3 properties) can be assigned to C2<U>.t without an error. Not expected.

### 🙂 Expected behavior

Assignments to P<U>.t (t is type U) to behave in the same was as assignments to u (type U), type error thrown at line 26

**Comment by fatcerberus** [comment]
Sigh… [the excess property check is not an actual type rule](https://github.com/microsoft/TypeScript/issues/55033#issuecomment-1638523746) and shouldn’t be relied on to enforce runtime invariants.

**Comment by MartinJohns** [comment]
Additionally to what @fatcerberus wrote, your property `C1.t` lacks a type annotation, so the type of the property is inferred from it's assignment. It is **not** using the type from the base class. This is tracked by #10570.

**Comment by RobertSandiford** [comment]
I put together this playground to show the root of the issue (thanks for the advice) - the way that excess property checks and indexing checks are applied.

[Playground](https://www.typescriptlang.org/play?ts=5.2.0-dev.20230720#code/C4TwDgpgBAKlC8UDeBYAUFKBDAXFAdgK4C2ARhAE7oC+66AxgPb4DOwUweciqG2eARgA06TKTwAmKAHppUAKIAPehBYsoABQqNIFUFADCACwj0A1lEraqaWmgbM2UQgmSj+UYe-FQJNOmhMrOwAblyuLrJQAHKMChTWAIRQALQKyqrqWjqUwACWqtgU0FgANqWMAO4QACYBIQB09K4AzDJySipqmtq6+samFmZ55up5+NgA5ljjAUFOFogA5DVL6CEA2mYAuq4ALO2YSmDFannMUIwAZhzg0CtLUPRY+PiM7OTOLLUcceM1EEUUEaCiuV1M+RCEFKIHSXSyvVysIG5igeXUpCw5nQQA) 

```ts
type T = {
  a: number
}

const t: T = {
  a: 1,
  b: 2 // Excess Property Check error
}

const u = {
  a: 1,
  b: 2
}

const v: T = u // No Error! - Excess Properties are allowed

v.c = 3 // Excess Property Check kicks in again

const k = 'd'
v[k] = 4 //  Expression of type 'd' cannot be used to index v. Effectively Excess Property Check is back
```

I'm not a fan of the behaviour. I would much rather see TS stick to one route or another. I would prefer something like Exact object types and loose objects types per [#12936](https://github.com/microsoft/TypeScript/issues/12936)

**Comment by RyanCavanaugh** [comment]
> I'm not a fan of the behaviour.

Detecting misspelled properties in object literals was basically the highest-requested behavior change in the entire language at the time we did it.

**Comment by RobertSandiford** [comment]
> > I'm not a fan of the behaviour.
> 
> Detecting misspelled properties in object literals was basically the highest-requested behavior change in the entire language at the time we did it.

Yes I can see the desire for it. The issues right now are consistency (the example in this ticket), and understandability (that its a sanity check and not a type violation).

How about this approach:

1) Excess Property Checks and Key checks are marked as warnings, not errors (I don't know if TS has any concept of this currently), and marked with yellow squiglies in code editors (where possible).

2) Express Property Check wording is changed to something like ```warning: property 'c' in type 'U' is not recognised. Is this a mistake?```

3) Excess Property Check applies when initializing an untyped property in a derived class, that is implementing an abstract typed property (the example at the top of this ticket). This gets into issue #10570 - I'm not going to fully consider that now.

4) Adding a new property to an object updates the type of that object instead of setting it to any. Example:

```ts
const o = {
  a: 1
}

o[b] = 2 // Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{ a: number; }'
```

Here the type of o would be updated to {
    a: number,
    b: number
}

The top of the object referred to be o would not be universally updated.

```ts
const o = {
  a: 1
}

function f(oo: typeof o) {
  oo[b]
}

o // { a: 1 }
```

But this does not violate anything on the basis that TS objects are truly extensible. Developers can easily assign the result of f if they want to keep the new typings.

5) Adding a new property to an object is treated as a warning, yellow squiglies.

6) The wording of the new property warning would be set to something like ```warning: property 'c' in type 'U' is not recognised. Is this a mistake?``` or  ```warning: property/indexer string in type 'U' is not recognised. Is this a mistake?```

7) Allow these "warnings" to be disabled via a default entry in the tsconfig (EPC can be disabled, but the option is not listed by default, and apparently is deprecated, to be removed in the future.

8) Ideally Exact types would be brought in to provide bullet proof restrictions where required.


Advantages of this are

A) its easier for TS users to understand the TS objects are extensible, and cannot be assumed not to have additional properties. Will avoid some bugs and mistakes, albeit rare ones.

B) Developers who prefer to work with objects in the JS sense, that is freely extensible, can do so more conveniently, be it ignoring the yellows or disabling the checks. Type info is now present on extended objects automatically, without needing explicit type definitions and conversions. (note: the spread operator can be used to achieve this fairly easily at current, but that could become laborious with more complex algos)
 
C) Checks are added to prop initialization in derived classes (depending on #10570)


Disadvantages: I don't see any, besides the work involved.

Back Compatibility issues: 

i) Derived class prop initialization checks would lead to warnings in existing code. If these "warnings" never prevent code emit, this would not be problematic.

ii) Typing changes to objects that have new properties assigned could lead to type errors. Variables that were `any` will not be typed. However since any type errors created this way are likely to indicate a bug in the program, this seems acceptable.


I'm open to contributing code by the way.

**Comment by RobertSandiford** [comment]
Thinking about whether the idea that TS objects are extensible is correct.

[Playground](https://www.typescriptlang.org/play?ssl=14&ssc=28&pln=2&pc=1#code/LAKANgpgLgBA9jAvDA3qGMCGAuGBGUAX1FADMBXAOwGMoBLOSmCADygkoBMAKOXFGAG0A1hACeuAM5QATnUoBzALr9CMQgBoYoiTGlzFWgG6Yw5CKoCUqdPBHilSGCbMQiJEK3ZdeWgOQARn5aAEyWHtSMknCQAHRgcAq84SAA9KnwTgI4+FoBuCHqoOnwfpIwUGIADhBZWLiU5AC2ARAyRSBAA)

Is this behaviour intentional?
```ts
let o = {
  a: 1
}

function extend(o: { [key: string]: {} }, key: string, value: {}) {
  o[key] = value
}

extend(o, 'b', 2)

console.log(o)
// o = { a: 1, b: 2 }
// o's type = { a: number }
```

I don't see how the type { a: number } is satisfying the constraint { [key: string]: {} }. ({} is being used as "any value except null and undefined)

**Comment by RyanCavanaugh** [comment]
You're describing an *extremely* large set of changes to address a fairly narrow surprise here. There's not going to be a lot of appetite for throwing out this many babies with the bathwater for the sake of addressing this.

I agree the error message wording could be improved. Open to useful suggestions on that one.

OT: It seems like you're new to TS and are logging bugs about every surprise you encounter along your learning journey -- keep in mind that the behavior you see is largely designed to mitigate *previous users'* surprises that they encountered when learning TS that had other behavior. It's not practical to reduce this amount to zero; everyone brings their own different preconceptions around how a language should work. Have you read the Handbook? It's designed to address some of these questions.

**Comment by fatcerberus** [comment]
> This is why the key part of my suggestion about was to change the display of EPC/Indexing errors to being clearly warnings, so as to establish a clear heircarchy: object typings are structural typings but here are some warnings, because maybe you just made a mistake here.

TS unfortunately makes no distinction between warnings and errors but check out https://github.com/microsoft/TypeScript/pull/55152.

> I read about structural types when I started - but obviously over time, being hands on, I just became convince that we were dealing with exact types.

I don't think you're alone.  Issues similar to the OP seem to show up about once a week on average.  It's been said by the maintainers that the demand for #12936 dropped off sharply after EPC was introduced, but my suspicion is that a lot of these people are misapprehending what the feature actually does (in particular, that it's not intended to enforce runtime invariants) and would *still* want exact types if they knew the EPC wasn't a full type-level check.

**Comment by RobertSandiford** [comment]
> TS unfortunately makes no distinction between warnings and errors but check out #55152.

Just changing wording will be adequate. Slap a big "Warning:" at the beginning and/or use "are you sure" kind of language.

It's been managed with the typecasts `Conversion of type '{ foo: string; }' to type '{ id: 123; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.`

Doesn't tell you it can't be done, and even tells you how to do it.

`Warning: Property 'c' does not exist in type 'U'. Is this a mistake? If this is intentional, cast the new object to U before assignment.`

e.g. `const user: User = { name: 'Jim', age: 37 } as User`

Yellow squiglies are nice, but not the biggest issue.

**Comment by fatcerberus** [comment]
@RobertSandiford You should post your suggestion(s) for wording in #55152 while it’s still open.
