### ISSUE TITLE
autoImportFileExcludePatterns has no effect on node modules.

### ISSUE THREAD

**Issue by smallmain** [microsoft/TypeScript#55111]
# Bug Report

### 🔎 Search Terms

autoImportFileExcludePatterns

### 🕗 Version & Regression Information

Visual Studio Code v1.80.1, Typescript v5.1

### ⏯ Playground Link

None.

### 💻 Code

```
{
    "typescript.preferences.autoImportFileExcludePatterns": [
        "**/node_modules/@xenon.js/core/**/*"
    ]
}
```

or

```
{
    "typescript.preferences.autoImportFileExcludePatterns": [
        "@xenon.js/core"
    ]
}
```

### 🙁 Actual behavior

Will still be automatically imported from the package `@xenon.js/core`.

I want to exclude the automatic import of the npm package @xenon.js/core from the project. I set autoImportFileExcludePatterns, but the automatic import is still triggered.
![image](https://github.com/microsoft/TypeScript/assets/28684663/773e76ff-8ef7-4139-bd11-60d1846268cf)
If what I add to autoImportFileExcludePatterns is a relative path, it works, but if it's an npm package, no matter what the package is.

### 🙂 Expected behavior

Will not be automatically imported from these paths.

**Comment by RyanCavanaugh** [comment]
Please provide a concrete repro

**Comment by axefrog** [comment]
@RyanCavanaugh 

1. Install the npm package "colorjs.io"
2. In a separate file, export a custom type guard function named `isString`.
3. In your main code, type a reference to `isString`. The one from colorjs.io is offered (first for me, which is annoying).
4. Add it as an auto import exclude pattern.
5. Repeat step 3. The export from colorjs.io is still offered.

**Comment by andrewbranch** [comment]
> 4. Add it as an auto import exclude pattern.

> every possible glob pattern I can think of

Can you list any of them?

**Comment by andrewbranch** [comment]
```
❯ npm info @xenon.js/core
npm ERR! code E404
npm ERR! 404 Unpublished on 2023-07-17T09:16:03.622Z
npm ERR! 404
npm ERR! 404  '@xenon.js/core' is not in this registry.
```

Can’t make a repro from the OP either unfortunately, as that package no longer exists

**Comment by axefrog** [comment]
@andrewbranch From memory, it would have been things like:

colorjs.io
colorjs.io/
colorjs.io/**/*
/colorjs.io
**/node_modules/colorjs.io

and so on.

**Comment by axefrog** [comment]
If you still can't reproduce it, I have one more wildcard I didn't mention, though it seems like a stretch that it would be the cause. In my multiroot workspace root folder I have a code folder called "shared". This is soft-symlinked into both the client and server directories which have different tsconfig folders. I use this setup because it lets me share code between the projects without having to confuse the compilers with types leaking between client and server.

**Comment by andrewbranch** [comment]
And you’re adding that to `/workspace/.vscode/settings.json`?

**Comment by axefrog** [comment]
I believe so... for what it's worth I'm not using colorjs.io anymore - I removed it because I was using one function from it and it wasn't worth the hassle.

**Comment by smallmain** [comment]
> 

xenon.js/core has indeed been deleted, but the problem is still there, I will see if I can try to provide a reproducible project later.

**Comment by andrewbranch** [comment]
In the interest of housekeeping, I’m going to close this since I’ve tried and failed to reproduce the bug, and nobody else has been able to provide a repro either. If anyone is able to provide a repro, comment here and I’ll reopen, or feel free to file a new issue.

**Comment by dawnmist** [comment]
I have run into this issue too, and have created an example repository that replicates the issue. This example is available to download from: https://github.com/dawnmist/typescript-issue-55111-reproduction

To reproduce, clone the above repository then look at the example import suggestions in VSCode as documented in the README file.

The repository is trying to turn off making suggestions to import from `@remix-run/server-runtime`, as those suggestions generally should be coming from `@remix-run/node` instead, but this is not working.

If I've misunderstood how to correctly specify a library to be excluded, please let me know what I should be doing instead/how to fix the `autoImportFileExcludePatterns` setting.

My environment:
- Debian 12 Linux on x86_64
- Tested with both Node 18 + Node 20
- Typescript: 5.3.2 & 5.3.3

**Comment by andrewbranch** [comment]
@dawnmist your repro is working as expected for me:

<img width="513" alt="image" src="https://github.com/microsoft/TypeScript/assets/3277153/ee6f830d-a5dd-46c5-b26e-b92f9b2d75c2">

I’m asking some coworkers with Linux machines to see if they can repro.

**Comment by dawnmist** [comment]
My apologies for the crash - I had an error in my `.gitignore` file that accidentally excluded checking in the yarn release version. I've updated that now, so if you pull from master again it should work.

I'll give npm a try tonight when I get home.

**Comment by andrewbranch** [comment]
No need. I can reproduce with yarn 👍
