### ISSUE TITLE
Unexpected widening when using Partial<T> for a generic function argument

### ISSUE THREAD

**Issue by aqueenan** [microsoft/TypeScript#55115]
# Bug Report

### 🔎 Search Terms

- is:issue generic Partial: label:Bug
- is:issue generic Partial label:"Working as Intended"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Partial`
- TypeScript v3.3.3333 also failed to show an error for `fn2`

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMMAGAPAFUQUwB5Q5gAmAzonAEYBWO0AfIgBQD6AXIpgJQcBucMYogDeAXwCwAKBSomARi5SpUAJ4AHHIgAKAQwBOsHQBs5WRgF4RUxIgDaWxDCQBrHCrjBOAXQD8HTPZeANxSEtLg0PBIKKbY+IQk5FS0DMzs2vqGJmY8iPyCImEx8oqSyuqaugYwxgBMZoiWcQREZBQ0dFCIPlaSNvaOLm4e3n6cgSGSooj+UqCQsAjIYPXNCW3JnYysHFVZq-S5+UJicyslUkA)

### 💻 Code

```ts
function fn0<T extends object> (_: T): void {}
fn0(1) // Argument of type 'number' is not assignable to parameter of type 'object'.ts(2345)

type Partial1<T> = {
  [P in keyof T]?: T[P];
}
function fn1<T extends object> (_: Partial1<T>): void {}
fn1(1) // No error, even though 1 isn't an object

type Partial2<T> = T extends object ? {
  [P in keyof T]?: T[P];
} : T
function fn2<T extends object> (_: Partial2<T>): void {}
fn2(1) // Argument of type 'number' is not assignable to parameter of type 'object'.ts(2345)
```

Note that `Partial1<T>` is actually how Partial is implemented in TypeScript, just copied here for comparison.

It may not be the cause of this issue, but I'm also perplexed as to why `Partial2` behaves differently than `Partial1` when `T extends object` is always `true`. Any ideas?

### 🙁 Actual behavior

`fn1` doesn't cause an error, even though `1` isn't an `object`.

### 🙂 Expected behavior

`fn1` should cause `Argument of type 'number' is not assignable to parameter of type 'object'.ts(2345)`, just like the other examples.

**Comment by RyanCavanaugh** [comment]
Mapped types don't preserve the object-ness of their input; this is intentional.

`fn2` doesn't really make sense as a thing to write since you have no reliable place to infer `T` from.

**Comment by fatcerberus** [comment]
> Mapped types don't preserve the object-ness of their input; this is intentional.

Even so, it shouldn’t be possible to infer `Partial<T = number>` since that violates the constraint, right?  Yet that seems to be what happens here…
