### ISSUE TITLE
Replace handle on requestId in cancelAnimationFrame.

### ISSUE THREAD

**Issue by fosemberg** [microsoft/TypeScript#55128]
"requestId" is more understandable than "handle".
On mdn, it is the "request id" that is used, not the "handle":

A long integer value, the request id, that uniquely identifies the entry in the callback list.

https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#return_value

**Comment by nmain** [comment]
[WhatWG calls these "frame callback identifiers" in its abstract descriptions of the mechanism, and "handle" on the IDL for cAF](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#animation-frames).  So I disagree.  The "request id" on MDN appears to be editorializing, and "handle" is the most acceptable term, with "frame callback identifier" being another acceptable term.
