### ISSUE TITLE
TS Server language server does not apply `compilerOptions` to excluded files (such as tests), making development less ergonomic

### ISSUE THREAD

**Issue by isaacs** [microsoft/TypeScript#55125]
# Bug Report

### 🔎 Search Terms

- tsserver
- tsconfig
- exclude
- include
- tsserver 2307
- esm
- compilerOptions

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about tsconfig, tsserver, language service

### ⏯ Playground Link

Not possible to reproduce in playground

### 💻 Code

This repository reproduces the issue reliably, with a full explanation and 3 possible workarounds.

https://github.com/isaacs/tsserver-2307-exports-issue/tree/main

Also tried:
- Having a separate `tsconfig.test.json` that included the test files and excluded the source, in the hopes that tsserver would pick that up and use it instead.
- Setting nvim's `tsserver.tsconfigPath` (this is a bit inconvenient, since it has to be done with each project, and it means that newcomers to the project will need to change their editors around before they can easily contribute)

### 🙁 Actual behavior

Receive a `tsserver 2307` error stating that types could not be found, because `compilerOptions` were not applied when TS Server is processing the excluded test file, meaning that it does not know that it is supposed to load the module using `import` and `Node16` semantics.

### 🙂 Expected behavior

Excluded test files should be processed by `tsserver` in the same manner as project source files. Ie, `include` and `exclude` settings in the tsconfig.json file should be ignored.

**Comment by MartinJohns** [comment]
This would result in a massive amount of wrong errors in some of my projects. I've excluded files because they're incompatible with the settings of that specific tsconfig file and should not be evaluated using it.

**Comment by isaacs** [comment]
@MartinJohns Hmm, that's a really good point.

Another path forward might be if tsserver did something like ts-node, so you could have `"tsserver": { "include": ["**/*.*"] }` to override the main tsconfig settings. (And I guess that's  how platforms end up with config proliferation issues 😅)

**Comment by RyanCavanaugh** [comment]
I have a hard time seeing the proposed behavior as anything except the source of a constant stream of "What do you mean `exclude` doesn't exclude things?" bugs. The suggested alternative configuration (I wouldn't even call it a workaround; it's just how things *should* be set up) is much clearer.

**Comment by isaacs** [comment]
> I have a hard time seeing the proposed behavior as anything except the source of a constant stream of "What do you mean exclude doesn't exclude things?" bugs.

As it is, the current behavior leads to "this module doesn't properly export types" bugs posted to maintainers of esm-only projects. It's very surprising that a node project with `"type":"module"` is managed in the editor as if it was building for es5 and commonjs. I'm not the smartest developer out there, but I've been building hybrid modules for a while now and getting very into the weeds with tsconfig edge cases, and I was completely stumped by this until I took a day to actually reproduce it and figure out what was going on. 

Perhaps there are more sensible defaults that could be used by tsserver for excluded files in such a scenario? Or at least a better error message than "can't load the types", indicating that the current file is excluded from the tsconfig?

A `tsserver` override in tsconfig.json would also be helpful, as it would provide both a more convenient workaround which package authors could suggest in those issues, and something to likely find in a google search. I use that for ts-node in a few places for similar reasons.

**Comment by isaacs** [comment]
@RyanCavanaugh Would you be open to / recommend an enhancement request or discussion regarding better ways for tsserver to communicate that the file being processed is excluded from the config it's using, and/or ways to provide alternative configuration overrides to tsserver?  I see that excluding the file is "Working as Intended", but I find it hard to believe that the resulting confusion is intended 😅

Some suggestions, any or all of which would improve the ergonomics imo, but also have their own trade-offs to explore:

1. attach a message to the tsserver error string if the file is excluded. So instead of `Cannot find module 'some-dep' or its corresponding type declarations. (tsserver 2307)` in this case, it'd be something like `Cannot find module 'some-dep' or its corresponding type declarations. (tsserver 2307) (This file is excluded by the configuration in tsconfig.json.)`
2. support a `tsserver: { ... }` section in tsconfig.json, akin to how ts-node does.
3. support loading `tsconfig.tsserver.json` along with (or instead of) `tsconfig.json`. This could be similar to (2), or could use first config file that includes the file (or something).

Probably other ideas out there that might be better.
