### ISSUE TITLE
Use keyof to get the union name in generic comprehensions. If the key value contains an ordinary function, the type hint is lost

### ISSUE THREAD

**Issue by biggerstar** [microsoft/TypeScript#55124]
### 🕗 Version 
- ts version: `5.1.6`
- webStorm version `2022.3.1`
- os version mac `13.4.1 `

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/zh/play?ssl=37&ssc=17&pln=37&pc=4#code/C4TwDgpgBAaghgGwK4QM4B4AqA+KBeKTAbQGsIQB7AM0IF0BuAKFEigFEAPYAJzgGNgAMQCWEBABMMAeTDBhFAHapcBeMjToA3lAD0O9l14CowABbQFcALZoo1KIgRRUEPovFQEEAG5ioZEFQoMDhUFw9hBRMKE3M7WXklOwAjACtXYEYoKCIAaShI-3J7GTlFVFoALihSxNQ82igILggFSRT04wB+IsoaWvKGqGqFHwhuRgBfbGZwaABlCGBMOfQBpRUoTSycgOrUHkiAcyqHBRAd4DhuI6Wu6s4efiFRCWkE8pnJxkYqJAUBIkTGhgGsPkoACJwK5NFptIKLZardaoKFXbDYAAUFHBqGqKLRcAAlNVvBRhB5ttk3EoKF4AHQIChHbG4olMb6MPRQbhoJAIYDVABEABJgCCAMxCqAAHygovFBwALNK5QqQQBGVXysUggBMQtmrHmSD4fDQqEeRheYg8BCtzxEtow2l0+hNZotfwQCBAsKeAggHkcvSglhsqAANDtxNC4BrqlTslBdQcE1ANZno8mU4rgHqRvyENmoJMS7GrgWtjtsqngBLE2Wa7mQUrqpiifhcJom9lvtNsj9uVIogB3CDJA4UbhWSOxaB5qB-AFlMfCH08iBgafAByb4Nebi7yLiYR8aHHPcsaBWYSoKzQvimelc-QASRoZgX11uu+vBSCFw-xiA5uGOOdhF3Ud1ycBQKF3XltyPPdeQPcZgDnZIkD-Uw7ygcQKFsODdxsJY7CQbhYUgAQL3KZgQUxJMrhuJZqgAcjrJU2PLON0yTWs83TTMNRLAT9ULH0S17fC4yrfiWwOBstmksTlXbTs8G7FS3TrABWDsex2fsiSAA)  
 
### 💻 Code

```javascript
type Values<T> = T[keyof T];
type ExtractFields<Options> = Values<{ // Extract the names of all second level keys passed in to the options object
  [K in keyof Options]: Options[K] extends object ? keyof Options[K] : never
}>
type SetType<Options> = {
  [key: string]: any
  target?: ExtractFields<Options>
}

function test<OptionsData extends SetType<OptionsData>>(options: OptionsData): void {
  console.log(options);
}

// result: "$test3" | "$test4" | "$test1" | "$test2"
type SuccessExtractField = ExtractFields<{  // Successfully extracted all key names,
  data1: {
    $test1: 111,
    $test2: null,
  },
  data2: {
    $test3: {},
    $test4: () => {},
  }
}>  

// On webStorm, the test function will report a red alert indicating a type mismatch.
// If the target type is set to string, it will not report a red alert, but this does not meet our expectations
test({
  target: '$test4',  // Expect normal code here to prompt $testX
  data1: {
    $test1: 111,
    $test2: null,
  },
  data2: {
    $test3: {},
    $test4: () => {},
 // $test5(){}  // Add $test5 and an error will be reported in target.
  }
})
```

### 🙁 Actual behavior
At present, there are two problems. The second question seems to be a bug
  1. The `webStorm`  editor reports red after writing the relevant code, but can be sure that the code will not report an error if it is normal under intuitive circumstances.
 2.  Type derivation failed. When using `ExtractFields` alone to extract the key names of all second layers of an object, the following situations occur. Matching key value pairs without a function is normal
`{$test4: ()=>{}}`    ------  Target can correctly code prompt
`{$test5() {}}`          ------ Target cannot correctly code prompt

### 🙂 Expected behavior

Correct code hints in the editor

**Comment by RyanCavanaugh** [comment]
See #47599
