### ISSUE TITLE
Typescript: find TYPE references when using external modules

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5513]
Copied from: https://code.visualstudio.com/Issues/Detail/19804

When using external modules in typescript, in my case CommonJS modules, I would expect "Find all references" to find where a given TYPE is used all over the project, not only in the current file.

It works with methods, which means the code for resolving external modules is already there, but it does not work for TYPES, when the cursor is on the name of the class in the class definition.

It also does not work on the constructor.

For example, given the following code :

File MyClass.ts

```
export = MyClass;
class MyClass {
 constructor(public val:number) {}
 doSomething() {}
}
```

File Other.ts

```
import MC = require('./MyClass');

var typed :MC;
var built = new MC(3);

built.doSomething();
```

From inside MyClass.ts :
- When cursor is on "doSomething", SHIFT+F12 correctly reports usage in Other.ts
- When cursor is on "constructor", SHIFT+F12 reports nothing
- When cursor is on "MyClass", SHIFT+F12 reports usage inside MyClass.ts but not in other files

**Comment by mhegazy** [comment]
find all references implementation does not handle aliases. so if you search for an identifier, it will only find things with the same name, if you alias it, aliased symbols it will not be found, a separate search will need to be requested.

For `export=` we can do better, when searching for a symbol, we can look if it is the same as export= symbol for the current module, search for the module import.

**Comment by DanielRosenwasser** [comment]
> find all references implementation does not handle aliases

I find it kind of odd that FindAllRefs doesn't deal with the original declaration for an alias. It would be useful if a user didn't need to find references to every alias as well as the originating declaration.

**Comment by mhegazy** [comment]
the main reason is to limit noise. if you have an import, and you hit find all refs, you probably do not want to see all other aliases to the same entity in other files. 

i do not think there is an objective reason here why it should or should not work. i would be open to trying the experience out and seeing what can be done.

**Comment by mjbvz** [comment]
Closing as out of date
