### ISSUE TITLE
Spurious TS7024 (Function implicitly has return type 'any'...) and TS2577 (Return type annotation circularly references itself) in TS 5.1.x

### ISSUE THREAD

**Issue by jstasiak** [microsoft/TypeScript#55145]
# Bug Report

### 🔎 Search Terms

* TS7024: Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions
* TS2577: Return type annotation circularly references itself
* 5.1.6 regression

### 🕗 Version & Regression Information

* I see the issue with TS 5.1.3-5.1.6 and the latest nightly.
* I do not see the issue with TS 5.0.4.

- This changed between versions 5.0.4 and 5.1.3

### ⏯ Playground Link

Variant 1 (no return type annotations, 2x TS7024)

https://www.typescriptlang.org/play?target=99#code/GYVwdgxgLglg9mABMAPAFUQUwB5U2AEwGdEBDMATwG0BdAPgAoA3ALkQCVNSCEAbCgIIAnIaQro6ASkQBvRAF8AUMuAMqixJsTqtuxOAKZgMMJgIAaDXs0NpAXjqyFl3TRdad1xAEZ3124gOslZeWhAIRHC8mAB0vHAA5gwA5AASmLzxyZIhevJ+iG6KNDlAA

Variant 2 (I added one return type annotation, I get TS7024 + TS2577):

https://www.typescriptlang.org/play?target=99#code/GYVwdgxgLglg9mABMAPAFUQUwB5U2AEwGdEBDMATwG0BdAPgAoA3ALkQCVNSCEAbCgIIAnIaQro6ASkQBvRAF8AUMuAMqixJsTqtuxOAKZgMMJgIAaDXs0NJbJnBgFEAXjqyFl3TS9ad1xABGX2tbV3cZKwCtCAQiOF5MADpeOABzBgByAAlMXlTMySi9eRDEH0UaIqA

### 💻 Code

Variant 1

```ts
function f<T extends any[]>(v: ReadonlyArray<T>) { }


f([
    [
        undefined,
        () => { },
    ],
    [
        1,
        () => {
            console.log('Hello')
        },
    ],
])

```

Variant 2

```ts
function f<T extends any[]>(v: ReadonlyArray<T>) { }


f([
    [
        undefined,
        (): void => { },
    ],
    [
        1,
        () => {
            console.log('Hello')
        },
    ],
])

```

### 🙁 Actual behavior

The code doesn't compile.

What's strange is from my tests it seems that if I run `tsc filewithcode.ts` it compiles fine but if I run `tsc` on the whole project it produces errors.

### 🙂 Expected behavior

I expected the code to compile.

**Comment by MartinJohns** [comment]
> What's strange is from my tests it seems that if I run `tsc filewithcode.ts` it compiles fine but if I run `tsc` on the whole project it produces errors.

Most likely you're having a `tsconfig.json` with `noImplicitAny` enabled. When running `tsc` on individual files the compiler won't use your project configuration, and the default value for `noImplicitAny` is `false`.

**Comment by jstasiak** [comment]
Oh yes, `noImplicitAny` is very much enabled (in the local project and in the playground).

**Comment by Andarist** [comment]
Bisected this to [this diff](https://github.com/microsoft/TypeScript/compare/27d3454f07cb41a24275d7f1de07621b8217f739...21db2ae9a2cb8ba88f9b10ac11d3bbd928bde3b1). It should be safe to say that this has been changed by https://github.com/microsoft/TypeScript/pull/53607

**Comment by ahejlsberg** [comment]
I'll take a look.

**Comment by jstasiak** [comment]
Thank you all, I can confirm the problem is gone in the current nightly (`5.2.0-dev.20230728`).
