### ISSUE TITLE
`void` does not properly swallow the return type when used inside a generic (e.g. `Promise<void>`)

### ISSUE THREAD

**Issue by GauBen** [microsoft/TypeScript#55149]
# Bug Report

> A contextual function type with a void return type, when implemented, can return any other value, but it will be ignored.
>
> https://www.typescriptlang.org/docs/handbook/2/functions.html#return-type-void

Also documented here https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

This appears to only work for sync functions, not async ones.

### 🔎 Search Terms

async void promise generics Type is not assignable to type 'void'.

### 🕗 Version & Regression Information

- [x] This is the behavior in every version I tried, and I reviewed the FAQ for entries about void

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/PTAEHUHsCcGsGdQDMangTwHYGNkFccAXAS0k3gFgAoAEwFNsAbAQ2jvyNM1GgIApszRowBGzbLABcoPgEpQAXgB8oAG6RiNWdPWaA3NV6Y+cxSoDeAX1kGqRk-OWhCvOjeohQXrwD0A-NQeYAAikHSImJCEoADuMLDIqMwYOBzYJGSUtAwsbGkZ3MlY2ABK-ILCYhLSpk4ACtCQALbE8HQAPLo0StpqGjS2RThlxkO4tRbWgyml-GMyjioueG62nt4bm97+gVSeAMLNTWSgeG0AtIJt1GMjfPMToA3NrXQAdEKMfADaALqy7j2YC2IN8ASoQVAAHE6Jg6NBiNhEAAHNiqWGERBdZCNJpoGKfSAxYiYADmzgAFuw2IQ8NBuIR0Mi6NRGczobD2gAVFQKUDmQjSLmWWz0JisdjYTLRJA1RanTCwSIxTB6LZINDMEjwJDEcILMx9fTUMW5SXS0CkuWGmGYdoEJVEzBKNXk+Ba1q6-WPW2dfou6hAA)

### 💻 Code

```ts
declare function asyncRun(callback: () => Promise<void>): void;
asyncRun(async () => {});
asyncRun(async () => true);
                  // ~~~~  Type 'Promise<boolean>' is not assignable to type 'Promise<void>'.
```

### 🙁 Actual behavior

Type 'Promise<boolean>' is not assignable to type 'Promise<void>'.

### 🙂 Expected behavior

`Promise<void>` should accept `Promise<any>` the same way `void` accepts `any`

**Comment by MartinJohns** [comment]
Duplicate of #49755.

**Comment by GauBen** [comment]
Sorry for the noise, closing in favor of #55149
