### ISSUE TITLE
Import aliases have poor quick-info descriptions

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5515]
![image](https://cloud.githubusercontent.com/assets/972891/10923920/5abb940e-8238-11e5-94b4-8b5794d9adb8.png)

**Comment by mhegazy** [comment]
what would you want see more here?

**Comment by DanielRosenwasser** [comment]
I'd like to see every entity that `y` encompasses. For instance, look at the quick info I get on `A` here:

![image](https://cloud.githubusercontent.com/assets/972891/10924052/24b6c6b6-8239-11e5-9e37-306899f5b01d.png)

**Comment by mhegazy** [comment]
except that an alias has a different name. so it is confusing to hover over `y` and get `interface A`. we used to do that, then added the new `import ` kind.

**Comment by DanielRosenwasser** [comment]
What about something like

```
import y
interface y
namespace y
```

**Comment by mhegazy** [comment]
but there is no `interface y`, it is really `import y (aliasing) interface A / namespace A`

**Comment by mhegazy** [comment]
any concrete proposals here?

**Comment by techird** [comment]
In file `type.ts`, I define an interface `Person`

```ts
/**
 * The type repencent a person
 */
export interface Person {
    name: string,
    age: number
}
```

In file `index.ts` where I import `Person`,

```ts
import { Person } from './types';

var techrid: Person; // hover point
```

when I hover on the hover point (the `Person` word), I would expect to see below.

```
import Person

interface Person
The type repencent a person
```

If I specific an alias like

```ts
import { Person as MyPerson } from './types';
```

I would expect to see below.

```
import Person as MyPerson

interface Person
The type repencent a person
```

In simple, just grap the quick info from the *origin* export point appending to the import quick info.

**Comment by mhegazy** [comment]
We would be open to a PR here. A possible solution is for Aliases to augment their quick info with that of their target.

**Comment by techird** [comment]
@mhegazy nice!

**Comment by mhegazy** [comment]
thanks @jwbay !
