### ISSUE TITLE
Generic type infers `undefined` despite `exactOptionalPropertyTypes`

### ISSUE THREAD

**Issue by NiGhTTraX** [microsoft/TypeScript#55164]
# Bug Report

### 🔎 Search Terms

exactOptionalPropertyTypes partial generic infer

### 🕗 Version & Regression Information

5.1 and nightly.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about exactOptionalPropertyTypes

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=5.2.0-dev.20230720#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwFsoMwALAHgBUA+ACjACMAueWgNygmRBcoEp4AXmrwGOHBBBRUfXgG4AUAtCRYCFOmx4k42gAccAZxYBveAA8A-C1TICDEDDnwAntfi37j+AF9Zo8UlpRQVEXVozFxYiElJaFyERBJEABgE-PkUAeiz4PPyCgoA9SyA)

### 💻 Code

```ts
declare function match<T>(cb: (value: T) => boolean): T;

declare function foo(pos: { x?: number; y?: number }): boolean;

foo(({ y: match(y => y > 0) }));
//              ^? number | undefined
```

### 🙁 Actual behavior

The type of `y` includes `undefined`.

### 🙂 Expected behavior

The type of `y` should just be `number`, because of `exactOptionalPropertyTypes`.

`foo(({ y: undefined }));` correctly fails under that flag, so I'd expect `match` to not infer `undefined`.

**Comment by DanielRosenwasser** [comment]
Thanks @Andarist!

**Comment by unional** [comment]
Same issue?

```ts
type Y = { a?: string }

type Z = Y['a'] // string | undefined
```

https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/C4TwDgpgBAmlC8UDeUCGB+AXFAzsATgJYB2A5lAL4BQVokUAWgrANoDkqbAulAPS+4CJcgB8oAV2IATCADMSEKUA

**Comment by Andarist** [comment]
I think this is the expected result here. The indexed access like this returns a read type that includes `undefined`

**Comment by unional** [comment]
Ohhhh~~~~~~ yeah, you are right. My head is spinning.... 😛
