### ISSUE TITLE
 Computed properties do not respect setter signatures

### ISSUE THREAD

**Issue by miyaokamarina** [microsoft/TypeScript#55168]
# Bug Report

Computed property assignments do not respect corresponding setter signatures.

### 🔎 Search Terms

variant accessors, setter, computed properties, write type

### 🕗 Version & Regression Information

- Affected versions: 4.3 to 5.1.6 (current stable).

### ⏯ Playground Link

[Playground Link (5.1.6)](https://www.typescriptlang.org/play?ts=5.1.6#code/MYewdgzgLgBA1jAvDAygTwLYCMQBsAUAlANwBQpoksApmAK4YwAKATiAA4QwDepM-8JDADkcYQBpSAX3IBLMFGosAZgENg1GADEQIHnwEBzarDhEAXKhMAeaC3mGAfGQEwIJ+PgBulgJKKWVSxcalsoezAnEnJXY1gAbTgAXQsrKDCIpxcBdwTk7z8AoJCMh0domVIAE2pgXFUWTUpoGGVdSx0QcgB6bpgAeQBpc1I2kAA6BFcBZHjhWSgJEQB3EBY4CGEkslJemABRFjYWCBGxubEk6dnhCAALEDpcKqXhVfWtsnPWDghJq5uWDoi3EInUUDoqlwuDQn1GukSV2mQjmVRA1E2oOEYBAiySPT6AHETAEuO8EKouNQAB7sWqKKojZqwLxQugYlFjSag86iLY8hE-Tj-AUgRFXSkwZlkPYCAB6AH5SEA)

### 💻 Code

```ts
const k = Symbol();

const enum Props {
    k = 'k',
}

interface Foo {
    get k(): Set<string>;
    set k(v: Iterable<string>);

    get [k](): Set<string>;
    set [k](v: Iterable<string>);
}

declare const foo: Foo

// OK:
foo.k        = ['it', 'works'];

// Errors:
foo['k']     = ['should', 'work'];
foo[Props.k] = ['but', 'actually'];
foo[k]       = ['does', 'not']

// Getters work as expected:
const values = [foo.k, foo['k'], foo[Props.k], foo[k]] as const;
//    ^? const values: readonly [Set<string>, Set<string>, Set<string>, Set<string>]
```

### 🙁 Actual behavior

Getter type is used at the LHS of an indexed/computed property assignment.

### 🙂 Expected behavior

Setters should accept their declared types.

**Comment by rotu** [comment]
I think this is fixed in 5.3.2, per the playground example.
