### ISSUE TITLE
My configs are not supported for typescript latest version 5.1.6

### ISSUE THREAD

**Issue by vigneshsivaji** [microsoft/TypeScript#55170]
# Bug Report

My configs are not supported for typescript latest version 5.1.6
### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 3.3.1and 5.1.6
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

{
"compilerOptions": {
"target": "es5",
"module": "amd",
"declaration": true,
"removeComments": true,
"noLib": false,
"experimentalDecorators": true,
"sourceMap": true,
"pretty": true,
"allowUnreachableCode": false,
"allowUnusedLabels": false,
"noImplicitAny": true,
"noImplicitReturns": true,
"noImplicitUseStrict": false,
"noFallthroughCasesInSwitch": true,
"allowJs": false,
"forceConsistentCasingInFileNames": true,
"moduleResolution": "node",
"suppressImplicitAnyIndexErrors": true,
"ignoreDeprecations": "5.0",
"noImplicitThis": false,
"types": ["jasmine","jasmine-ajax","requirejs","chai", "es6-promise"],
"lib": ["es2015.collection","es2015.core","es5", "dom"]
},
"exclude": [
"node_modules",
"dist",
"public",
"coverage",
"test-report"
],
"compileOnSave": false
}

### 🙁 Actual behavior

 error TS2365: Operator '>' cannot be applied to types 'number' and 'string | number'.
error TS2339: Property 'columnName' does not exist on type 'never'.
  The intersection 'Column & AggregateColumn' was reduced to 'never' because property 'formatFn' exists in multiple constituents and is private in some.
error TS2345: Argument of type 'IRow<T> & { class?: string[]; }' is not assignable to parameter of type '{ [x: string]: Object; }'.
  Index signature for type 'string' is missing in type 'IRow<T> & { class?: string[]; }'.
 error TS2440: Import declaration conflicts with local declaration of 'ColumnModel'.
error TS2532: Object is possibly 'undefined'.
 error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.
error TS2300: Duplicate identifier 'mod'.
### 🙂 Expected behavior

No errors.

**Comment by MartinJohns** [comment]
Your configuration works just fine for TypeScript 5.1, but you have type errors in your code. Your case seems better suited for some kind of support forum, but not for the TypeScript issue tracker (which is meant for actual bug reports and feature requests).

**Comment by RyanCavanaugh** [comment]
Please provide a self-contained repro.
