### ISSUE TITLE
Multi Generics type with Conditional not currect

### ISSUE THREAD

**Issue by lgl017temp** [microsoft/TypeScript#55174]
# Bug Report

Multi Generics type with Conditional not currect

See Playground Link
type InitParam1: Multi Generics type is work
type InitParam2: 2 Generics type with Conditional is work
type InitParam3: Multi Generics type with Conditional not currect
type InitParam4: same as InitParam3

Why? This is weird, I'm not sure if I'm misunderstanding something

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/KYDwDg9gTgLgBDAnmYcCSA7AljACgQynwFsBGAHgBUAaOAJTlBmAwBMBnOAa2EQgDM4NOAHlGIZm048+gygD44AXjgBvAFABIANpc4WDPQC6ALiG6jAbnUBfOADI1W3fsMijAfjOUL1m+vVQSFgEZFRMHAIiYgAmKloxJhYObl4BITgAHzgMAFcAG3zlHIL8xRVEiWTpNLk4DycdPQNU2ThcLABjLnjReU9vX1sHRpcWmXSRYhxekX7Brithsw0m11b0ylNzRb8AoOh4JBR0bDxCEgBmXoYkqQ25BPFJFIm67LzC4s+y4sqXmptSj1UbNQx0bY+XbDRyrMZuAY7JZ2FbOMHGBbI-bgQ6hE4Rc7RAAsN2e1QeQied1etQyH1K31K5VEZPubwyDTh6PZHW6N3mSL8Iy56x5XR6wjmiKhyLgqLWLQhmL26k6+Xw7E4lGA7HgGjgBrg+DMuqgBgA5sUAERW6yGuAAIxNMDNGEtKhtdsNnWdrvdcE96ntrF9FuttoC9oMOFIAAoIGAYFgIBgzASoiQKNrdbQrfgrVkAw6rbnOgXslbWFb5ABKJz2+0wAAWWHYADp8MUE0mUx2vQ2EC32w6u4nkxg2w7rEGB4PW23OqOexPFx4Glay-2G8356wl+O23u1wGq1v-FGzjEAPpx7vjtNnDOxKg6mC1+uznftzsqO+9-Bbo2Q6TvuvZTpGn7AYuv5jr2nSAYaX6HqBE6sGeM4GtGMDXjE8awampyRBcz7ZjApblie1Z1vqkHzj+cB-hOAEYduwEjjBy6TtOs5zu20EMfhC71Oum4sUBu4ochx6VhG9rnoaWGXDeeHLg+RHRNcpG5vmhZWsW740QOSH0YxfZiYhbGSeBcksYpV64YxamElcL45gGOkVsW5G6VWBnmQaxmScxPFIexAmceB-m8UJHEHquImybR7Z7rFvZHuup4sfJmFnESymOYRznECSWnuRRelUR+RnASZgnBUlIGpRO1mGtlrg4HlDn4U5T4la+2nlV5AZlj5lWGaxdFBQhAWWU1XEQdV878aZ8XDYli3JZJ6WUeh-hAA)

### 🙁 Actual behavior

No field InitParam3<Test, "a" | "b", "c" | "d">.c

### 🙂 Expected behavior

Have field InitParam3<Test, "a" | "b", "c" | "d">.c: string | undefined

**Comment by RyanCavanaugh** [comment]
I'm not looking at 70-line repros. Please provide a concise example of why you think you've found a bug.

**Comment by lgl017temp** [comment]
[[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/KYDwDg9gTgLgBDAnmYcCSA7AljACgQynwFsBGAHgBUAaOAJTlBmAwBMBnOAa2EQgDM4NOAHlGIZm048+gygD44AXjgBvAFABIANpc4WDPQC6ALiG6jAbnUBfOADI1W3fsMijAfjOUL1m+vVQSFgEZFRMHAIiYgAmKloxJhYObl4BITgAHzgMAFcAG3zlHIL8xRVEiWTpNLk4DycdPQNU2ThcLABjLnjReU9vX1sHRpcWmXSRYhxekX7Brithsw0m11b0ylNzRb8AoOh4JBR0bDxCEgBmXoYkqQ25BPFJFIm67LzC4s+y4sqXmptSj1UbNQx0bY+XbDRyrMZuAY7JZ2FbOMHGBbI-bgQ6hE4Rc7RAAsN2e1QeQied1etQyH1K31K5VEZPubwyDTh6PZHW6N3mSL8Iy56x5XR6wjmiKhyLgqLWLQhmL26k6+Xw7E4lGA7HgGjgBrg+DMuqgBgA5sUAERW6yGuAAIxNMDNGEtKhtdsNnWdrvdcE96ntrF9FuttoC9oMOFIAAoIGAYFgIBgzASoiQKNrdbQrfgrVkAw6rbnOgXslbWFb5ABKJz2+0wAAWWHYADp8MUE0mUx2vQ2EC32w6u4nkxg2w7rEGB4PW23OqOexPFx4Glay-2G8356wl+O23u1wGq1v-FGzjEAPpx7vjtNnDOxKg6mC1+uznftzsqO+9-Bbo2Q6TvuvZTpGn7AYuv5jr2nSAYaX6HqBE6sGeM4GtGMDXjE8awampyRBcz7ZjApblie1Z1vqkHzj+cB-hOAEYduwEjjBy6TtOs5zu20EMfhC71Oum4sUBu4ochx6VhG9rnoaWGXDeeHLg+RHRNcpG5vmhZWsW740QOSH0YxfZiYhbGSeBcksYpV64YxamElcL45gGOkVsW5G6VWBnmQaxmScxPFIexAmceB-m8UJHEHquImybR7Z7rFvZHuup4sfJmFnESymOYRznECSWnuRRelUR+RnASZgnBUlIGpRO1mGtlrg4HlDn4U5T4la+2nlV5AZlj5lWGaxdFBQhAWWU1XEQdV878aZ8XDYli3JZJ6WUeh-hAA)](https://www.typescriptlang.org/play?ts=5.1.6#code/KYDwDg9gTgLgBDAnmYcCSA7AljACgQynwFsAeAFQBo4AlOUGYDAEwGc4BrYRCAMzipwA8vRCMW7Lj37k4AHzgYArgBsVcALyLVKgHybho8W07c+AuAH44AbwBQASADaHOFgy0AugC4BLzwDcdgC+cABkto4ubh5Cnpa+5P5Bob72zq7uXonJIXZ2AMYq+Kzs5MCs8PZwNXD4vpVQ7gDmBgBEbUG1cABGDTBNGK1aHV21Bf2Dw3Cjdt3Mky3tnfndc7XuOADMABQQYDBYEBi+mDgERGTlldRt+G3yMz1ttwUPCm3MbboAlJHd3RgAAssKwAHT4Az7Q7HCFjAEIEHgnpQg5HDBgnpBdYI4GgsEFVEwjGEyzWNpveEAvHg5hE9FgulkmZfKnBHF5IA)

type InitParam<Test, "a" | "b", "c" | "d"> should have field c, d

**Comment by MartinJohns** [comment]
@lgl017temp https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

**Comment by lgl017temp** [comment]
@MartinJohns Oh, thx. I never realized this was calculated independently
