### ISSUE TITLE
Latest typescript version shows errors

### ISSUE THREAD

**Issue by vigneshsivaji** [microsoft/TypeScript#55184]
# Bug Report

Latest version of typescript shows lot of errors mentioned below.

### 🔎 Search Terms

In my old version the codes are working fine. I have upgraded to latest these error occurs

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 3.3.1 and 5.1.6
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about NA
- I was unable to test this on prior versions because not working.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

```ts
// We can quickly address your report if:
//  - The code sample is short. Nearly all TypeScript bugs can be demonstrated in 20-30 lines of code!
//  - It doesn't use external libraries. These are often issues with the type definitions rather than TypeScript bugs.
//  - The incorrectness of the behavior is readily apparent from reading the sample.
// Reports are slower to investigate if:
//  - We have to pare too much extraneous code.
//  - We have to clone a large repo and validate that the problem isn't elsewhere.
//  - The sample is confusing or doesn't clearly demonstrate what's wrong.
```

### 🙁 Actual behavior

blazor\sf-grid.ts(460,23): error TS2339: Property 'msSaveBlob' does not exist on type 'Navigator'.
demos\grid\paging\template.ts(16,5): error TS2532: Object is possibly 'undefined'.
spec\grid\base\grid.spec.ts(787,17): error TS2365: Operator '<' cannot be applied to types 'number' and 'string | number'.
src\grid\renderer\row-renderer.ts(268,58): error TS2365: Operator '>' cannot be applied to types 'number' and 'string | number'.
src\grid\renderer\row-renderer.ts(345,35): error TS2345: Argument of type 'IRow<T> & { class?: string[]; }' is not assignable to parameter of type '{ [x: string]: Object; }'.
  Index signature for type 'string' is missing in type 'IRow<T> & { class?: string[]; }'.
src\grid\renderer\summary-cell-renderer.ts(81,88): error TS2339: Property 'columnName' does not exist on type 'never'.
  The intersection 'Column & AggregateColumn' was reduced to 'never' because property 'formatFn' exists in multiple constituents and is private in some.
### 🙂 Expected behavior

No error occurs.

**Comment by MartinJohns** [comment]
All these errors look like expected and need to be fixed by you. Each version of TypeScript may contain breaking changes that can result in new errors. The breaking changes are documented in the release notes.

This repository is not meant as a support forum. If you believe you found an actual bug in TypeScript you should post a minimal example demonstrating the bug. But just posting a list of errors in your project is not the way to go.

**Comment by vigneshsivaji** [comment]
Can you please explain how to solve these issues? is there any configs are available

**Comment by xiBread** [comment]
> This repository is not meant as a support forum.

And I'm not sure what you think changing your config will do. That's not going to fix your errors magically.
