### ISSUE TITLE
`in` and `!in` operators as corollaries of `array.prototype.includes`

### ISSUE THREAD

**Issue by surajsharma** [microsoft/TypeScript#55194]
# Suggestion

## 🔍 Search Terms

- in operator
- not in`!in` operator
- array.prototype.includes
- python
- rust

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

- Upgrade legacy operability of existing `in` operator to include arrays
- Implement `!in`  (aka bang-in) operator as an inverse

## 📃 Motivating Example

-  'array.prototype.includes' vs 'in'

```
console.log('suraj' in ['george','power']) //false
console.log('1' in ['0','2']) //true
```
-  [creative ways to use `in` will backfire](https://stackoverflow.com/questions/7972446/is-there-a-not-in-operator-in-javascript-for-checking-object-properties) 

- compare: `in` in python 3 and `!in` in rust
 

## 💻 Use Cases

Self-explanatory

**Comment by MartinJohns** [comment]
This goes beyond the realm of TypeScript and is out of scope. This would first need to be supported by JavaScript. Carefully check the Viability Checklist again.

**Comment by surajsharma** [comment]
@MartinJohns updated visibility checklist, thanks!

**Comment by MartinJohns** [comment]
@surajsharma 

This is the important point:

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

The feature you request is not supported by JavaScript and it's a runtime feature. TypeScript only aims to support type related features, it's the clear design goal of the language.

Once this code `'1' in ['0','2']` works in JavaScript as well the way you expect it could be supported by TypeScript. But this is likely never going to happen, because this code is already legal JavaScript and behaves different.

**Comment by surajsharma** [comment]
@MartinJohns thanks, updated the request. though it makes no sense to have the runtimes wedded like so, bueraucracies slowing down progress everywhere :/

**Comment by MartinJohns** [comment]
> though it makes no sense to have the runtimes wedded like so

It makes perfect sense. TypeScript aims to add type information on top of JavaScript, it does not aim to expand on JavaScript. This way they keep compatibility with JavaScript (which is the code that runs in the end) and prevent feature creep. It allows them to focus on their goal. What would happen if they add a feature people want, and then ECMAScript / JavaScript will add a completely incompatible version? They either have to drop compatibility with JavaScript or remove/change the existing feature, resulting in massive breaking changes and a lot of headache.

This ensures progress on the side of JavaScript and on the side of TypeScript.

**Comment by surajsharma** [comment]
@MartinJohns the counterpoint here is even the creator of JS is saying we should not use JS and move on to loftier solutions

**Comment by RobertSandiford** [comment]
`in` already applies to arrays in javascript. But `in` checks keys not values.

`0 in ['a value'] == true` because it matches the key `0`

Anyhow TC39 deals with improvements to javascript, have a look over [here](https://github.com/tc39/proposals)

**Comment by RyanCavanaugh** [comment]
> even the creator of JS is saying we should not use JS and move on to loftier solutions

Just to be clear, TypeScript's goal is to be a type checker for JS, not some new solution to replace JS.

**Comment by surajsharma** [comment]
> Just to be clear, TypeScript's goal is to be a type checker for JS, not some new solution to replace JS.

doesn't it sound rather short-termed and parochial, sort of like saying TS can never have an identity of its own. just saying
