### ISSUE TITLE
Yielding an assertion function call does not narrow the asserted type

### ISSUE THREAD

**Issue by WilcoKruijer** [microsoft/TypeScript#55205]
# Bug Report

### 🔎 Search Terms

generator, yield, assertion function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about assertion functions and generators.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/AQMwrgdgxgLglgewsAVMGBTAzjAYpKACgEpgBvAKGGvQE8AHDYAZQQFsMAVBpgXnICGALmAQwbAEYYATgF8A3BSo0ANhhjAoCSBv4AGRTVAF4SYAKxYZMAIKcAFnAgBzQggkArEZADWEBADuEMQiFlbSMFjA7h7AcFGsHNyM5MpG1AD0GcAAJkgA5BpQAtJMAhLaGjD2THBs9Cpp6Vo6ANSthjSySkZaEDjAEirCwL7+QcD8ZCMAzApNYdZ2ji6EQwLEik1Zogh0KTLSCNLANaVNfVgIagB0Kgiu6zcbW71IA+sATN4QfoHIUxGABZ5kZaHAMCocuZLEsHE5HsNPpsejQdl84lExv8ADSDMAaLD2bRQwZMRJcHgwmHhTDQiS0dA1GlwlbOTQCFQqG5NOAgYBrJHPYAAQl4-CBpEo6Ro1SOAVEGAVAFFpEdpIQAERfYVEkn0phAm6alFGbq8-mEFoQDRi-jI1Iy6hywKKlVq45agDC2htwD1YFJUnQAQQxtNXVR1Eu1wwdweWoAUgIAG4WKDSOD0QlgKBQbBYE1Uc0gY4Cy4aOCYNjRfmYHD4aAkKXbDIUWRAA)

### 💻 Code

```ts
 function * testFunc() {
    type SomeType = {a: number};

    let count = 0;
    function assertAThing(obj: unknown): asserts obj is SomeType {
        // don't care about the impl
        count++;
    }

    const bla: unknown = {a: 3};
    assertAThing(bla);

    // no type error here
    console.log(bla.a);

    const bla2: unknown = {a: 4};
    yield assertAThing(bla2);

    // bla2 is unknown, but should be SomeType as asserted by the assertAThing call.
    if (bla2.a !== 4) {
        throw new Error("bla2.a should be 4.");
    }

    if (count !== 2) {
        throw new Error("Count should be two.");
    }

    console.log("Javascript success")
 }

for (const item of testFunc()) {
    //
}
```

### 🙁 Actual behavior

The variable `bla2` is still `unknown` even after passing it through the assertion function `assertAThing`.

### 🙂 Expected behavior

`bla2` should be narrowed to be `SomeType` like `bla1`.

### Workaround
We are effectively yielding `void` since assertion functions cannot return anything. This means there is a simple workaround:
```ts
assertAThing(bla2);
yield;
```

**Comment by MartinJohns** [comment]
This is not a bug as per #32695:

> A function call is analyzed as an assertion call or never-returning call when
> - **the call occurs as a top-level expression statement**, and
> - the call specifies a single identifier or a dotted sequence of identifiers for the function name, and
> - each identifier in the function name references an entity with an explicit type, and
> - the function name resolves to a function type with an `asserts` return type or an explicit `never` return type annotation.

**Comment by RyanCavanaugh** [comment]
This doesn't seem like something you would likely (ever?) actually do in real code, and making new CFA graph nodes slows down everything else.
