### ISSUE TITLE
Initial class field with another stage3 decorated field, then get `undefined`.

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript#55211]
# Bug Report

### 🔎 Search Terms

Initial class field with another stage3 decorated field, stage3 decorators

### 🕗 Version & Regression Information
5.1.6
### ⏯ Playground Link

[[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)
](https://www.typescriptlang.org/play?experimentalDecorators=true&target=3#code/PTDuEsBcAsAIFMAeAHeAncBbeA7SBDAGwBF4BjAezX0ioGdYAzIu+AKEYFcczJwKcsUpQDMACgBuRTvABcsfDgCeAGliU8SSLMVKAlLADebAL5tzICDAQp0WXARLkqNerEhoZHbr36DhFABMYhp08rpqANbwSuHKBsam5mSE+HQMAMqcqGhGbLDqAnQenLxUYnrGBQViMOAMaQrxAHQAJjT4sAC8sADkjBQUvfmwZmZsKWkMAMI2kLitmdnoeQUAAgGBIyCwG84iI+0EAISyxRg4AOYjAEb4uT11dG0dSRNFFITwzYQUl2JiHDwUCwaZ6Zp3NAGHb9Qa9WBiYr4S7wQIGKiwbiteCMcBA1oIpEokR6NhAA)

### 💻 Code

^^^ see playground ^^^

### 🙁 Actual behavior

Log 'foo' with stage2 decorators and 'undefined' with stage3 decorators

### 🙂 Expected behavior

Log 'foo' with both decorator stages.

**Comment by Jamesernator** [comment]
> ### 🙁 Actual behavior
> Log 'foo' with stage2 decorators and 'undefined' with stage3 decorators
> 
> ###  Expected behavior
> Log 'foo' with both decorator stages.

The reason for the behaviour here is that stage 3 decorators imply [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) behaviour as it's neccessary for stage 3 decorators semantics to work.

Under that flag (and by extension your example), in the subclass `data!: string` also defines the field, note that this behaviour is the same as the following JS (i.e. with the types removed):

```js
class Super {
    constructor() {
        this.data = "foo";
    }
}

class C extends Super {
    // This defines the property "data" as undefined
    data;
    bar = this.data;
}

console.log(new C().bar);
```

TypeScript does [support type only annotations](https://www.typescriptlang.org/docs/handbook/2/classes.html#type-only-field-declarations).

Regardless your example gives no indication as to why you aren't just declaring `data` in the superclass, i.e.:

```js
class Super {
    data: string;
    
    constructor() {
        this.data = "foo";
    }
}

class C extends Super {
    bar = this.data;
}
```
