### ISSUE TITLE
CompilerOptionsDiagnostics not working for "target"?

### ISSUE THREAD

**Issue by blackening** [Microsoft/TypeScript#5521]
Hi, I've been trying to develop a typescript compiler for broccoli. I'm having issues detecting the CompilerOptions. Apparently when i pass in an obviously wrong target, no diagnostics will be produced. However, it does modify the code produced - if a wrong target is passed in, Class will still be present in the resultant javascript.

Code:

    var allDiagnostics = this.services.getCompilerOptionsDiagnostics()
		.concat(this.services.getSyntacticDiagnostics(fileName))
		.concat(this.services.getSemanticDiagnostics(fileName));
	console.log('--------------------->', allDiagnostics.length);
	console.log(this.services.getProgram().getCompilerOptions());
	console.log(this.services.getProgram().getOptionsDiagnostics());
	console.log(this.services.getProgram().getGlobalDiagnostics());
	console.log(this.services.getCompilerOptionsDiagnostics());

Where this.services is an instance of LanguageService.
Output:

    ---------------------> 0
    { sourceMap: true,
      target: 'THROW ME AN ERROR',
      module: 'commonjs',
      outDir: 'C:\\projects\\app\\tmp\\broccoli_tsc-output_path-RaiEbvPK.tmp',
      rootDir: 'C:\\projects\\app\\tmp\\broccoli_tsc-input_base_path-Ibh9oTc5.tmp\\0
    ' }
    []
    []
    []

**Comment by mhegazy** [comment]
`CompilerOptions` uses enums for the values of `target` and `module`, see the definition in https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L1321. passing them invalid values is not checked.

if you want to pass in strings, use `ts.parseJsonConfigFileContent`.

I would note that using the TypeScript compiler to compile your plugin against typescript.d.ts should catch these issue for you.

**Comment by blackening** [comment]
Thanks =)
