### ISSUE TITLE
useUnknownInCatchVariables sets default value differently to other strict commandline options

### ISSUE THREAD

**Issue by 12wrigja** [microsoft/TypeScript#55227]
# Bug Report

Not necessarily a bug, but I would like some clarification on why the the definition of the useUnknownInCatchVariables CommandLineOption (https://github.com/microsoft/TypeScript/blob/cd23992100f8edd29ef9c29e29758008cdbeb8ec/src/compiler/commandLineParser.ts#L888) is different from the other options that also set `strictFlag: true` (e.g. https://github.com/microsoft/TypeScript/blob/cd23992100f8edd29ef9c29e29758008cdbeb8ec/src/compiler/commandLineParser.ts#L878).

All the other CommandLineOptions that have their fallback influenced by `strict` set a `defaultValueDescription` of `Diagnostics.false_unless_strict_is_set`, but `useUnknownInCatchVariables` explicitly sets `false` (see permalink above). Why?

### 🔎 Search Terms
false_unless_strict_is_set, defaultValueDescription

### 🕗 Version & Regression Information

I noticed this within the codebase at head.

### ⏯ Playground Link

n/a

### 💻 Code

n/a

### 🙁 Actual behavior

useUnknownInCatchVariable's CommandLineOption sets a defaultValueDescription of `false`.

### 🙂 Expected behavior

useUnknownInCatchVariable's CommandLineOption sets a defaultValueDescription of `Diagnostics.false_unless_strict_is_set` like all the others?

**Comment by MartinJohns** [comment]
That's a bug. The value depends on `strict`.

**Comment by RyanCavanaugh** [comment]
Yep, good catch
