### ISSUE TITLE
Base class should not be assignable to subclass with private field

### ISSUE THREAD

**Issue by jrose-signal** [microsoft/TypeScript#55235]
# Bug Report

### 🔎 Search Terms

"subclass", "private property", "assignable", "nominal"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (back to 4.0 in the playground), and I reviewed the FAQ for entries about "bugs" that aren't bugs

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6#code/MYGwhgzhAEBCkFNoIB4BcEDsAmMDyARgFYLBrQDeAUNNAA4BOAlgG5gbQMJjYD2mIAJ7QAZkwQhsALmiYArgFsCCBgG4a0YPwhoGcsrwYAKMROmzFyhgEpKG2hDl0VR6+tq00ACyYQAdKaS0AC8ouKS7tAAvlQxVKCQMADKcgQAjMjoWLhwiHa0jKzsSFw8-ELQAPqVaILOAPwymAgsKuoxCVDQKQQATJkYODDwEEjUBcxsHKV8AsLVtQ1NLW2xVPHa5LzEMiNIoc0A7t2paUZpbhuYOtCOBDI9-aHbRKrQAPTvt168ckGYvHIymgYBAIF4hwQ2AAhOstNdyFoGFwyEIAOJYFTFCAAQUwAFFkYYHqknrIEMcemcLuogA)

### 💻 Code

```ts
class Base extends Object {
  private readonly field: number;
  constructor(field: number) {
    super();
    this.field = field;
  }
}

class Sub1 extends Base {
  private readonly __type?: never;
}
class Sub2 extends Base {
  private readonly __type?: never;
}

const obj: Base = new Sub1(1);
const sub: Sub2 = obj; // should not be allowed!

const correctlyGeneratesAnError: Sub2 = new Sub1(1);
```

### 🙁 Actual behavior

No error is generated for the assignment of `obj` to `sub`.

### 🙂 Expected behavior

`obj` should not be considered assignable to `sub` because Sub2 has private properties, and even though those private properties are optional they may conflict with private properties in other subclasses. I expected an error, like the one I get in the last line:

> Type 'Sub1' is not assignable to type 'Sub2'.
>  Types have separate declarations of a private property '__type'.

(I recognize that using private properties to get nominal-typing-like behavior is a hack, but even though I'm *only* using it for that purpose this would be an issue with private properties that actually hold data as well.)

**Comment by fatcerberus** [comment]
I think this is just a manifestation of the usual unsoundness around optional properties (i.e. `{ foo: number, bar: number }` is assignable to `{ foo: number }` which in turn is assignable to `{ foo: number, bar?: string }` even though that means you may now have a “string” which is actually a number at runtime)

**Comment by RyanCavanaugh** [comment]
> even though those private properties are optional they may conflict with private properties in other subclasses

As @fatcerberus, this logic applies to public properties as well. Private properties are nominal in terms of their declaration sites, but don't cause the enclosing shape to become nominal as well. The structural comparison is still structural and the definition of optional means this is allowed.
