### ISSUE TITLE
JSDoc fails parsing type imports containing `*/`

### ISSUE THREAD

**Issue by duanwilliam** [microsoft/TypeScript#55242]
# Bug Report

### 🔎 Search Terms

JSDoc, type imports

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.1.6&filetype=js#code/PQKhAIAEBcE8AcCm4DeAiEw0F9yYFD6gQwLIoCWAtvAPYBO0AFAOSYsB0AYrbQJS4CRMPjxQ4SVNTqNW7Pt17ZRQ4ivFkAJogBmUmg2YtImHbxYKetXFZXAgA)

### 💻 Code

```ts
/** @type {"*/"} */

/** @type {import('*/'.Foo)} */

/**
 * @type {import('*/').Foo}
 */

/**
 * @typedef {import('@*/foo').Foo} Foo
 */
```

JSDoc parsing fails on encountering the substring `*/` in type information.

This issue only occurs in JSDoc comments (i.e. `type Foo = import('*/').Foo` in a `.ts` file is fine).

In the context of npm, package names follow the pattern `^(?:@(?:[a-z0-9-*~][a-z0-9-*._~]*)?/)?[a-z0-9-~][a-z0-9-._~]*$`, so modules containing `*/` such as `@foo*/bar` are valid and plausible module names. This bugs makes types from such modules nigh on inaccessible in JSDoc.

### 🙁 Actual behavior

Parsing the type fails, and the type isn't properly resolved.

### 🙂 Expected behavior

The characters are parsed correctly.

**Comment by IllusionMH** [comment]
That's because `*/` closes multiline comment immediately. You have invalid JS on hand, so it's not JSDoc
![image](https://github.com/microsoft/TypeScript/assets/1312662/aa4eb0f7-e9cc-4230-b4b5-b5b2c8646e88)

**Comment by duanwilliam** [comment]
ahh bit of an oversight there.
seems this is a general issue with jsdoc as a whole - https://github.com/jsdoc/jsdoc/issues/821

unfortunately the workarounds listed don't work in the context of type imports still, though.
