### ISSUE TITLE
optional parameters in the middle.

### ISSUE THREAD

**Issue by co-dh** [Microsoft/TypeScript#5526]
I found this problem while type d3.js

d3.csv has the following signature:
d3.csv(url[[, accessor], callback])

so if there are two parameters, the second one will be callback, if 3, then the 3rd one will be callback.
It can be typed use overload, however, this feature will make less copy & paste.

one suggestion is to use ??: for level two optional parameter, 
the other suggestion is to use [[,accessor], callback] syntax.

**Comment by co-dh** [comment]
Here is a code sample:
```
    type Dict<T> = { [key: string]: T };
    type S= Dict<string>;
    type DsvAccessor<T> = (rows: S[], index?: number)=> T ;
    interface DsvCallback<T>{
        (rows: T[]): void;
        (error: any, rows: T[]): void;
    }
    interface Dsv {
           (url: string, accessor?: DsvAccessor<void>, callback?: DsvCallback<S>): DsvXhr<S>;
           (url: string, accessor?: DsvAccessor<S>,    callback?: DsvCallback<S>): DsvXhr<S>;
           (url: string,                               callback?: DsvCallback<S>): DsvXhr<S>;
        <T>(url: string, accessor?: DsvAccessor<void>, callback?: DsvCallback<T>): DsvXhr<T>;
        <T>(url: string, accessor?: DsvAccessor<T>,    callback?: DsvCallback<T>): DsvXhr<T>;
        <T>(url: string,                               callback?: DsvCallback<T>): DsvXhr<T>;

```

**Comment by mhegazy** [comment]
Just allowing the middle parameter to be optional does not solve the issue outlined in the sample. the proposal here to allow it would be to introduce new syntax. We would be hesitant to do this as it may conflict with possible future ECMAScript syntax (see https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals).
