### ISSUE TITLE
Overload Shows Everything

### ISSUE THREAD

**Issue by iseeeva** [microsoft/TypeScript#55260]
### 🔎 Search Terms

When I use this function the autocomplete shows all values for the second parameters

### 🕗 Version & Regression Information

- Typescript: 5.1.6

- This might be a bug

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAcgrgWwEYQE4CUIEMAmAVcCAZygF4oByASwDtgAOCqAH0tuAEYA2J16ugMwAmXpQBmAGwD2WYMIoAoUJCgAhOGLFpMuApBLkKkmXJEtx02d1H9gEAOZpFEAB5gpqYFDFwaAY2AqKRooHRwAQSIACgA1LAk4CAAuKCJgVFp7ABooPWS1DS0MbHxCIhyAeTBA4KIAfhSAb1SAdywwAH0IGhwqLBoUpCkpCWwQgF8AShSaRBRUBVd3T29fAKCQsMjY+MSZubQcvJT4ZG0SvPKoKpqaeqbW9q6evoGoIZGxqCmUtIyaeyLNweLw+fy3UIlbZxBL5P6ZcyzM6oI6EE4HYq6MrmdSac5Y-SVaobe5QZpENqdbq9fqDYajfrfaapdII1hI+Zk8YKBRbaIABiyACJjFYuELJkA

### 💻 Code

```ts
type NumberReadTypes = 'int8' | 'int16' | 'int32' | 'float32'
type BufferReadTypes = 'float32' | 'float16' | 'integer'
export function ReadAs(Value: string, Type: BufferReadTypes, Options?: { swap_endian: boolean }): number
export function ReadAs(Value: number, Type: NumberReadTypes, Options?: { swap_endian: boolean }): string
export function ReadAs(Value: string | number, Type: NumberReadTypes | BufferReadTypes, Options?: { swap_endian: boolean }): string | number {}

ReadAs(0,"float16")
```

### 🙁 Actual behavior

When I use this function the autocomplete shows all values for the second parameters.

[
![image](https://github.com/microsoft/TypeScript/assets/107738269/ac5023a4-b14e-43c5-98ff-e063248ce8e1)
](url)

### 🙂 Expected behavior

i just want see true overload

**Comment by jcalz** [comment]
Duplicate #26892
