### ISSUE TITLE
Most specific signature isn't chosen for callbacks

### ISSUE THREAD

**Issue by jeengbe** [microsoft/TypeScript#55272]
### 🔎 Search Terms

callback overload signature specific wrong pick

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _n/a_

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.0-beta#code/JYOwLgpgTgZghgYwgAgGIFcQOQbwFDLIAUAHgFzIDOYUoA5gJQXW0h0DcBx5VN9yAH2Qh0AG1FNerOoOFjRnAL548AEwgJRcKCgQB7ENWQxMCChiyc1GrTuT7DYZAAcoegLYUACm-fBKEAA8LPQAfJzqmtq6BkbaUBQAglBQcACewXxs4Sr4hA5xyAC8Lr4AdGAAFhAgRBCixaHGpnUSDJyEAPSdhIQAegD8XAVOAEbFpR4V1bUmWO1c3b3Ig3jKeHn2sU5wE-Fl7nDOrY3NWK0MC109y7f9Q-nbyOMl+4fHcwhXyEt3t6uKIA

### 💻 Code

```ts
interface Func {
  (x: string): string;
  (x: string | null): string | null;
}

declare const func: Func;
declare const prom: Promise<string>;

const a = prom.then(el => func(el));
//    ^? Promise<string>
const b = prom.then(func);
//    ^? Promise<string | null>
```

### 🙁 Actual behavior

```ts
const a = prom.then(el => func(el));
//    ^? Promise<string>
const b = prom.then(func);
//    ^? Promise<string | null>
```

I assume this happens because `func(el)` picks the most restrictive/specific signature for `el`, which is `(x: string): string`. I assume that this step is not done for callbacks.

### 🙂 Expected behavior

```ts
const a = prom.then(el => func(el));
//    ^? Promise<string>
const b = prom.then(func);
//    ^? Promise<string>
```

**Comment by RyanCavanaugh** [comment]
Generic inference to an overloaded function always chooses the last signature. See #43187 and others
