### ISSUE TITLE
Headers.prototype.getSetCookie

### ISSUE THREAD

**Issue by kentcdodds** [microsoft/TypeScript#55270]
### 🔎 Search Terms

headers getSetCookie

### 🕗 Version & Regression Information

On version `5.1.6`, the `lib.dom.d.ts` has the following interface:

```
interface Headers {
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Headers/append) */
    append(name: string, value: string): void;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Headers/delete) */
    delete(name: string): void;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Headers/get) */
    get(name: string): string | null;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Headers/has) */
    has(name: string): boolean;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Headers/set) */
    set(name: string, value: string): void;
    forEach(callbackfn: (value: string, key: string, parent: Headers) => void, thisArg?: any): void;
}
```

This is missing `getSetCookie`: https://developer.mozilla.org/en-US/docs/Web/API/Headers/getSetCookie

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAFgUwIYBMECcIwLwzAgdxgAlk1MAKASgChRJYIEoBhEEAawEsEd4yMEAHQBzZgGVmbTj2pA

### 💻 Code

```ts
const headers = new Headers()
const setCookie = headers.getSetCookie() // <-- Property 'getSetCookie' does not exist on type 'Headers'.(2339)
```

### 🙁 Actual behavior

Property is not defined

### 🙂 Expected behavior

The property should be defined.

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh should this be moved to https://github.com/microsoft/TypeScript-DOM-lib-generator ?

**Comment by kentcdodds** [comment]
I've not heard of that project. Sounds like it 👍

**Comment by balazsorban44** [comment]
Looks like it's already in https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/9a39f1049cfcceec4d76d3ffc0481bf2d63f1f51/baselines/dom.generated.d.ts#L13448-L13449

but I don't understand the flow of how that one gets merged in to TypeScript.

**Comment by balazsorban44** [comment]
Actually, it looks this is already in this repo too: https://github.com/microsoft/TypeScript/blob/a0e0104656415b6c6d18c6ba1100ae42157a4f09/src/lib/dom.generated.d.ts#L13428-L13429

So I'm not sure why it's missing in newer versions.

**Comment by balazsorban44** [comment]
After some detective work, I found out that `5.2.1-rc` already has this, if you are using VSCode, make sure you are using the local version:

![image](https://github.com/microsoft/TypeScript/assets/18369201/c5f53488-a886-4af1-a1a1-22ab93996e87)
![image](https://github.com/microsoft/TypeScript/assets/18369201/6d15c2c0-16c2-4d71-8d81-293630c5bb8e)

**Comment by jeswinsimon** [comment]
@kentcdodds Looks like this is fixed. The playground link is showing the current annotation now.

**Comment by kentcdodds** [comment]
Thank you for confirming!

**Comment by dotspencer** [comment]
I was getting the same error but at build time and not in VS code. Fix was to `yarn add -D @types/web` to the project.
