### ISSUE TITLE
method type references don't infer `this` type

### ISSUE THREAD

**Issue by mfulton26** [microsoft/TypeScript#55286]
### 🔎 Search Terms

method
this
type
any
infer
missing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the `this` keyword

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAQg9nANhAhgOwCpwMrAE4CWaA5gGICuaAxsAXGlALxQBGCy6A2gETA75Fi3ALoBuAFDiq9AM7AoAWxDwkqTP0IkAXLHZqsuTWUo06DZgDMTtelAAUASigBvcVHdQZAdwLAqAC3tgfwIZJ1cPSKgqFBlofHIILTco1LwIYHI8Bm4MACUAVQBRbglU9xi4qAsURDjk8qj0zOyoblIAQQAZbBKU9wBfcQGgA

### 💻 Code

```ts
type BooleanToStringFunction = boolean["toString"];

const myBooleanToString: BooleanToStringFunction = function () {
    switch (this) {
        case true:
            return "TRUE";
        case false:
            return "FALSE"
    }
}
```

### 🙁 Actual behavior

error received:

> 'this' implicitly has type 'any' because it does not have a type annotation.

I can work around this by changing `BooleanToStringFunction` from `boolean["toString"]` to `(this: boolean) => string` or by adding `this: boolean` to `function ()` in the implementation but both of these require repeating types whereas I want to reference the type and not repeat them.

### 🙂 Expected behavior

`this` is inferred from the referenced method without any additional work

**Comment by RyanCavanaugh** [comment]
There aren't `this` types defined on `Boolean` or other built-ins and it's not clear what the upside of doing so would be (apart from this *exact* scenario), but there'd be a substantial performance hit associated with doing it.

**Comment by mfulton26** [comment]
I was hoping that the performance hit would be marginal, if any. My use case is that I want to define types in interfaces and then implement them elsewhere and rather than duplicating the function signatures I wanted to reference them but when doing that I found that `this` was lost. I made myself a utility type for now to take in the `this` type plus the method key string or symbol. I can do a workaround.

https://www.typescriptlang.org/play?#code/C4TwDgpgBA6glsAFgFUXAzgBQIYCdsC2EwEuAPMgDRQCqUEAHiQHYAm6UAFAHS94Dm6AFxRszEAEooAXgB8o8fOlcAUFHVQkGEVTUbe3AcKg58RErnRkA8gQSoMpwsVJkas2SqlyoAJWIArrjMyOAQbrIA3CoqoJBQALLEiAD2rABiAcwAxsBwKcxkeurI9EwQbBz+2Sm4rGQA0tRZANbMKQDuzLKUxVANZSzsJrgpkLigDRAgvUqwCChoWHjOFhTUyADaDQC6gxXDPHy4giJikjLy51AA-FBbu1AizBAAbqRRMXHQAEIpKQAbCBiZApADKwFwcGY-EyOTyBRkiWSaThuXyhQARv8gWJqAAiYDgyHQ-j4z4qGrMdDAKAEEB-QHAkLEqEwkSM3EsiFs2FZdGI5QAM35COYXCkAG8+ugOghsoguFp0FK+hooNlsOhoJCAhAhGr1RpcIFglB8chfDQAKL46JGjSa7VQIXYAHag0Oh0m4BBcX49IAQQAMmDbX0AL4qCNAA

```ts
type WithThisParameter<T, U extends (...args: any) => any> = (
    this: T,
    ...args: Parameters<OmitThisParameter<U>>
) => ReturnType<U>;

type MethodFunction<
    T extends Record<K, unknown>,
    K extends PropertyKey,
> = WithThisParameter<T, T[K] extends (...args: any) => any ? T[K] : never>;

type BooleanToStringFunction = MethodFunction<boolean, "toString">;

const myBooleanToString: BooleanToStringFunction = function () {
    switch (this) {
        case true:
            return "TRUE";
        case false:
            return "FALSE"
    }
}
```

**Comment by fatcerberus** [comment]
> but when doing that I found that `this` was lost.

It wasn't really "lost" *per se* - the information simply never existed in the first place.  Methods don't have a `this` type at all, not even an inferred one, unless one is put there explicitly, because as Ryan says above, including it hurts compile-time performance.  So in fact `boolean['toString']` *is* giving you the declared signature for that method and your workaround is manufacturing a `this` type from whole cloth.

**Comment by mfulton26** [comment]
okay, so I see it isn't "lost" per se, that's fine, but isn't this inconsistent?

e.g. in the following code snippet `this` is correctly inferred as `Boolean`:

```ts
Boolean.prototype.toString = function () {
  return this ? "TRUE" : "FALSE";
};
```

but when I attempt to extract the right-hand-side to a constant then `this` is "lost":

```ts
type BooleanToStringFunction = typeof Boolean.prototype.toString;
const booleanToStringFunction: BooleanToStringFunction = function () {
  return this ? "TRUE" : "FALSE";
//       ^^ 'this' implicitly has type 'any' because it does not have a type annotation.
};
Boolean.prototype.toString = booleanToStringFunction;
```
