### ISSUE TITLE
tsc with watch does not attempt to reuse oldProgram structure

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/TypeScript#5528]
When tsc is run with watch enabled, the recompile timeout handler eventually calls compile(). In compile() the call to createProgram() does not provide an oldProgram so the old program structure is never tested to see if it can be reused. Why is this?
Perhaps related is when the watched project config file changes the cached program is set to undefined thus also never giving the chance for the call to createProgram to use oldProgram. If a project config changes it is not necessarily a reason to throw away the oldProgram.

**Comment by DanielRosenwasser** [comment]
>  In compile() the call to createProgram() does not provide an oldProgram so the old program structure is never tested to see if it can be reused. Why is this?

Are you sure that the program structure isn't reused? Maybe you mean in certain contexts? `recompile` calls `performCompilation` which creates a new compiler host whose `getSourceFile` uses `cachedProgram` if it is available and not invalidated.

> If a project config changes it is not necessarily a reason to throw away the oldProgram.

I agree; we could always just keep the intersection of the listed files and the old files in cache. I think the current behavior was adopted because it was simpler (and thus less prone to a surprise memory leak).

**Comment by ToddThomson** [comment]
Yes, I saw that the host getSourceFile() is overridden to utilize the cachedProgram if it exists. Perhaps, I need a better understanding of what that exactly accomplishes ( other than handling file watch operations ). However, I am not sure how that effects the actual call to createProgram() from within compile(). Without actually passing in the cachedProgram to createProgram() the oldProgram structure is not tested to see if it can be used in the incremental compilation. It seems that source files from the oldProgram ( even if read by the overridden getSourceFile() ) need to be tested ( by the call to tryReuseStructureFromOldProgram() ) to see if they can be reused. If oldProgram is not provided in a call to createProgram() the old program structure is not used.

**Comment by DanielRosenwasser** [comment]
`createProgram` uses the given host object's `getSourceFile` whenever it needs a SourceFile object for a given path. `getSourceFile` will check the cache before actually doing all the hard work (i.e. dependency resolution, scanning, parsing, etc.)

After going over it with @mhegazy, the reason we don't reuse programs when a `tsconfig.json` is modified is that the project options might have changed (e.g. `moduleResolution`, `module`) which affect the way in which dependency resolution is run. This means that when `getSourceFile` gets called again, it might give wrong results because the module resolution strategy might differ.

Still this is not a stopper; my understanding is that @vladima has done some work in the language service so that we can reuse the program despite project settings changing.

By the way, if you don't mind me asking, what's your interest in the current code?

**Comment by mhegazy** [comment]
> When tsc is run with watch enabled, the recompile timeout handler eventually calls compile(). In compile() the call to createProgram() does not provide an oldProgram so the old program structure is never tested to see if it can be reused. Why is this?

We added this optimization for the Language Service, but never enabled it for watch scenarios. we could, not sure if there is much value there though, the LS operations are more frequent and re-resolving the whole project every request is a usage blocker.

One thing to note, the program structure is not the AST, reusing the AST is done in getSourceFile. this is about module resolution results.

> Perhaps related is when the watched project config file changes the cached program is set to undefined thus also never giving the chance for the call to createProgram to use oldProgram. If a project config changes it is not necessarily a reason to throw away the oldProgram.

it is simpler. changing tsconfig (as well as adding a new file/removing a file) is rather an infrequent event in the lifetime of a watch session. so we can just simplify the logic by throwing away everything. again we can always optimize it.

**Comment by ToddThomson** [comment]
@DanielRosenwasser I use Typescript for all my javascript projects. The one thing that I need is the ability to output a single file bundle from sources that use ES6 imports. Earlier in the year I wrote a node base gulp vinyl adapter that takes as input the typescript configuration file and compiles the individual files and also looks a the file dependencies and generates bundles if the tsconfig.json file has a "bundles" property ( my addition to the schema ). It works perfectly for my needs ( I also use it to compile itself - producing a single file commonjs node module ).
Although not the mainstream gulp typescript compiler, a number of people need the bundling capabilities so I've been adding features as I have time ( file globs, etc ). I try to stay current with the whatever the new tsconfig.json schema provides so when I saw the watch compilerOption I thought I'd add that too.

**Comment by ToddThomson** [comment]
@mhegazy Thank-you. I guess I still need to get a better understanding of the AST. I cannot wrap my head around how your getSourceFile() from the cachedProgram is useful if a watched source file change results in a dependency change. No worries, I'll figure it out.

**Comment by mhegazy** [comment]
The SourceFile (AST) is used for incremental parsing. so if you have a file, and make an edit in one line, the majority of the nodes in the AST are reused, and we only re-parse the area around the change. this saves both memory and time.

now the change itself, after incremental parsing is done, could affect module resolution. e.g. you added new `import * as ns from "module"`, now this program should include `module.ts` in it. so we need to re-resolve the program.

the logic to reuse program structure, tries to reuse as much as it can, i.e. if non of your import changed, no need to re run the resolution (find what file `"module"` should resolve to) as it needs to do fileExists and folder search operations that can be expensive.

again watch implementation does not do that today. so it is possible to go update it to do that, and would give you some perf gains.

**Comment by ToddThomson** [comment]
@mhegazy Thank-you. I get it now. My incorrect assumption was that with the watch implementation and passing oldProgram to createProgram()  and if retaining program structure that program.emits would be incremental too ( along with incremental parsing ).
For bundles I don't need the intermediate js, map a d.ts files, but if compiled output is needed in some cases, it would be nice to have just the set of modified file(s) and the files that are dependent on the modified file(s) emitted.

**Comment by ToddThomson** [comment]
@mhegazy Thank-you. I've gone over the differences in the watch implementation in tsc vs the incremental change processing in services.ts.
I've seen that the most significant perf gains come by holding onto the AST between compilations. I'll take advantage of that when building bundled external modules. I'll leave incremental parsing for now.
For source file changes that affect module resolution have you looked at partial reuse of the program - keeping sourceFiles that are not affected at all by the change?

**Comment by mhegazy** [comment]
> For source file changes that affect module resolution have you looked at partial reuse of the program - keeping sourceFiles that are not affected at all by the change?

both implementations do this already. as you mentioned, keeping the sourceFiles (AST) that have not changed between compilations is a big perf gain.
