### ISSUE TITLE
Investigate use of aliases when naming symbols in type baselines

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#553]
The type baselines seem inconsistent in terms of how they name symbols that can be reached through aliases. Sometimes the symbol is named via the alias, and sometimes via a reference to its original declaration. Some examples:

tests/cases/compiler/acceptableAlias1.ts:
```TS
import r = M.X;
>r : r
>M : typeof M
>X : r // Used alias
```

tests/cases/compiler/importInTypePosition.ts:
```TS
import a = A;
>a : a
>A : typeof a // typeof alias
```

tests/cases/compiler/dottedModuleName2.ts:
```TS
import X1 = A;
>X1 : X1
>A : typeof X1
 
    import X2 = A.B;
>X2 : X2
>A : typeof X1
>B : typeof X1.B
 
    import X3 = A.B.C;
>X3 : X3
>A : typeof X1
>B : typeof X1.B
>C : typeof X2.C
```

Here is a list of many affected tests:
* tests\baselines\reference\acceptableAlias1.types
* tests\baselines\reference\ambientExternalModuleWithInternalImportDeclaration.types
* tests\baselines\reference\amdImportNotAsPrimaryExpression.types
* tests\baselines\reference\circularImportAlias.types
* tests\baselines\reference\commonJSImportNotAsPrimaryExpression.types
* tests\baselines\reference\declareDottedExtend.types
* tests\baselines\reference\declFileInternalAliases.types
* tests\baselines\reference\dottedModuleName2.types
* tests\baselines\reference\exportImportAlias.types
* tests\baselines\reference\importedModuleClassNameClash.types
* tests\baselines\reference\importInTypePosition.types
* tests\baselines\reference\importOnAliasedIdentifiers.types
* tests\baselines\reference\importStatements.types
* tests\baselines\reference\innerAliases2.types
* tests\baselines\reference\internalAliasClass.types
* tests\baselines\reference\internalAliasEnum.types
* tests\baselines\reference\internalAliasEnumInsideLocalModuleWithoutExport.types
* tests\baselines\reference\internalAliasEnumInsideTopLevelModuleWithoutExport.types
* tests\baselines\reference\internalAliasFunction.types
* tests\baselines\reference\internalAliasFunctionInsideLocalModuleWithoutExport.types
* tests\baselines\reference\internalAliasFunctionInsideTopLevelModuleWithoutExport.types
* tests\baselines\reference\internalAliasWithDottedNameEmit.types
* tests\baselines\reference\internalImportInstantiatedModuleMergedWithClassNotReferencingInstanceNoConflict.types
* tests\baselines\reference\internalImportUnInstantiatedModuleMergedWithClassNotReferencingInstanceNoConflict.types
* tests\baselines\reference\internalImportUnInstantiatedModuleNotReferencingInstanceNoConflict.types
* tests\baselines\reference\returnTypeParameterWithModules.types
* tests\baselines\reference\sourceMapValidationImport.types

**Comment by mhegazy** [comment]
This does not seem to be actionable for PR. closing.
