### ISSUE TITLE
How and where to add some utility types

### ISSUE THREAD

**Issue by Daggron** [microsoft/TypeScript#55301]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I just want to ask few questions w.r.t utility types in typescript

Right now whenever we have to get a union of object values we have to do something like this

```ts

const stages = {
   LOADING : 'LOADING'
   ERROR: 'ERROR'
   SUCCESS: 'SUCCESS'
} as const 

type Stages = typeof stages[keyof typeof stages]
```

this becomes redundant in code base and can be improved with utility types for e.g.

```ts
type ObjectValues<T extends Record<any, any>> =  T[keyof T];
```

Willing to add this as a utility type provided by TS, but stuck on where to add this `es5.d.ts` is one place where I can write it but not sure if thats the correct place and do I need to add it somewhere else or not.

**Comment by MartinJohns** [comment]
Nowhere. See https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388:

> We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.

**Comment by Daggron** [comment]
> Nowhere. See [#39522 (comment)](https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388):
> 
> > We've opted to not include utility type aliases in the lib unless they're required for declaration emit purposes.

Lol, time to create my own utility library then 😂

**Comment by MartinJohns** [comment]
You're free to do so. Or use one of the many many out there.
