### ISSUE TITLE
tsserver: need to be able to send content on open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5530]
Since the tsserver can crash (for example due to memory limits) we added code to VSCode to restart the server. However if a TS file is not saved we can't bring the server back in sync since the open command reads the content from disk. To enable the restart case the open command must accept the content as well. To not break existing client the content can be made optional and if not provided read from disk.

**Comment by mhegazy** [comment]
> Since the tsserver can crash (for example due to memory limits) 

do you have repros we can look at. Ideally it should not crash :)

**Comment by dbaeumer** [comment]
I have ask the dev that is seeing the crash for steps. However it can always happen that the server crashes (could even be node/V8). So being able to restart it and bring it back in sync is desirable.

**Comment by dbaeumer** [comment]
Another example were sending the content is when a user switches the mode of a file in the editor. For example he opens a file in text mode, makes some edits and switches to TS mode.

**Comment by mhegazy** [comment]
@zhengbli can you take a look.

**Comment by zhengbli** [comment]
I agree this is important for stability, and it will make it possible to provide language service for unsaved buffer as well.

**Comment by dbaeumer** [comment]
@mhegazy & @zhengbli: is there any hope to get this fixed soon. I tried to work around this but it does cause problems if a change has occurred on the last line. The ranges get out of sync. So there is little I can do right now (the bug Andres reported against VSCode suffers from this)

**Comment by zhengbli** [comment]
@dbaeumer I sent a PR at https://github.com/Microsoft/TypeScript/pull/5593, should be going in soon

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/pull/5656 fixes this in release-1.7
