### ISSUE TITLE
TypeScript build isolated modules completely separately

### ISSUE THREAD

**Issue by mnaoumov** [microsoft/TypeScript#55315]
### 🔎 Search Terms

isolatedModules

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about isolated modules

### 💻 Code

I have a bunch of JavaScript scripts that I want to improve using JSDoc and TypeScript Typings

I need to be able to compile them absolutely independently so the code from one script doesn't mess up the typing system in the other script.

##### script1.d.ts

```typescript
export {};

declare global {
    var myGlobalVariable: {
        property1: {
            childProperty1: string;
        }
    }
}
```

##### script2.d.ts

```typescript
export {};

declare global {
    var myGlobalVariable: {
        property1: {
            childProperty2: string;
        }
    }
}
```

##### script1.js

```js
/// <reference path="script1.d.ts" />

console.log(myGlobalVariable.property1.childProperty1);
```

##### script2.js

```js
/// <reference path="script2.d.ts" />

console.log(myGlobalVariable.property1.childProperty2);
```

##### tsconfig.json

```json
{
    "compilerOptions": {
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
        "isolatedModules": true
    },
    "include": [
        "*.js"
    ]
}
```

Executing

```
> tsc
```

Is there a way to configure TypeScript to build my isolated modules indeed in an isolated way?

Additionally I prepared a [gist](https://gist.github.com/mnaoumov/7db6e73c5872b8c286bc812e6ad62c81) with all those files mentioned above.

### 🙁 Actual behavior

I am getting the errors

```
script2.d.ts(4,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'myGlobalVariable' must be of type '{ property1: { childProperty1: string; }; }', but here has type '{ property1: { childProperty2: string; }; }'.
script2.js(3,40): error TS2551: Property 'childProperty2' does not exist on type '{ childProperty1: string; }'. Did you mean 'childProperty1'?
```

### 🙂 Expected behavior

No build errors produced

**Comment by mnaoumov** [comment]
Same question on [StackOverflow](https://stackoverflow.com/questions/76863560/typescript-build-isolated-modules-completely-separately)

**Comment by mnaoumov** [comment]
To clarify confusions I will provide more context why do I need such architecture.

I am using [Obsidian](https://obsidian.md/) note-taking app with the [Dataview](https://github.com/blacksmithgu/obsidian-dataview) plugin.

This plugin allows to execute custom JavaScript

```dataviewjs
await dv.view('script1');
```
which will invoke abovementioned `script1.js`

Internally Dataview executes `script1.js` by reading its content and `eval`s it.

Naturally, `script1.js` and `script2.js` are executed and `eval`ed independently and have no shared context.

**Comment by RyanCavanaugh** [comment]
You can do this by having a separate tsconfig for each file, or by just using `tsc` directly without a tsconfig and passing the filenames. There isn't a configuration option to cause the behavior you're describing.

**Comment by mnaoumov** [comment]
@RyanCavanaugh I want to be able to edit my files in viscose and have proper code completion, so running `tsc` manually individually is not an option
