### ISSUE TITLE
Typescript type narrowing issue for TypeGuard

### ISSUE THREAD

**Issue by Nek0-hinata** [microsoft/TypeScript#55317]
### 🔎 Search Terms

- TypeScript union type narrowing
- TypeScript type narrowing issue with typeof
- TypeScript typeof with union types
- TypeScript typeof typeguard problem
- TypeScript typeof type error 
- TypeScript union callable type narrowing issue
- TypeScript switching on typeof union type problem

### 🕗 Version & Regression Information

- This is the behavior in version 5.1.6 and Nightly I tried, and I reviewed the FAQ for entries about typescript type narrowing issue

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230808#code/C4TwDgpgBAysBOBLAdgcwPLwGIFdkGNhEB7ZKAXigCItjiqoAfKAChYEoKA+agIQEN4VdgCgR+UgGdgUYgCMAVlABcUAEoR+AE1IAbEAB4A3lABmyVXCRpMuAkVJQAvj0onzqjtz6CGTqOJSMqCQ6KZYZJQhEMSmsooAdOZiEsjSUBAAHpCEViioFKzS8KrF+ZzkPEZOYpIA7ojA+AAWLNFhEZxGIlC9UPj8ktBUpniEJMhUyj19APSzfb0AKs2IkhnZ8BCSkhNQa1DIxDIDurr8croQCTO9830AcsdQ-Gf9QY04EMjA67FQ0SgAHI8jZsGMHMggS8tv1XudLtdblB7osluBoECaHQqNDmoNDsQ4W9dqhkPxgDgtpIEiwAEwAZgALABOUSLLI5YCg1AseQKJLIDjsvpyLb8ADWAG5kQMhtQymgpsj7gBBeCoHAAW2+Mn+gJBCHytghE2hByOMkGpPJiIBRLAgn4OuAEHgsjiBsVqCBN0WqKg6MgwK8lR8QnN60tLx2iDJFyu9oBGOB3t99OZAFYRb1ORBcka0HzEuYc1AxZppcitBBTPwcLpgNMaiJ6o0Wm0Mf9+YKurLBsNRvYJsqOdl89zC7ye+ZhXcFgBJGR1YjwCWSZEVyUyxZy4be0d9PMF6zTkvIThzRfL1frzfiquLGt1htNkQ1IA

### 💻 Code
```ts
type StringOrFunction = "Foo" | (() => "Bar")

const obj : Readonly<{ fn: StringOrFunction }> = { fn: () => "Bar" } 
const typeOfFn = typeof obj.fn

const expectString = (str: string) => {}

switch(typeOfFn) {
    case "function":
    expectString(obj.fn())
    break;
    case "string":
    expectString(obj.fn)
    break;
    default:
}

switch(typeof obj.fn) {
    case "function":
    expectString(obj.fn())  
    break;
    case "string":
    expectString(obj.fn) 
    break;
    default:
}
```

### 🙁 Actual behavior

The TypeScript compiler is unable to correctly infer the type of obj.fn within the context of the switch(typeOfFn) statement.

### 🙂 Expected behavior

The expected behavior is for TypeScript to correctly narrow down the type of obj.fn based on the typeOfFn in this context, thus not leading to any type errors.

**Comment by fatcerberus** [comment]
This is like the third issue I've seen where the code isn't in a code block.  Is there a problem with the new issue template(s)?

**Comment by yagnikvadi2003** [comment]
type StringOrFunction = "Foo" | (() => "Bar");

const obj: Readonly<{ fn: StringOrFunction }> = { fn: () => "Bar" };
const typeOfFn = typeof obj.fn;

const expectString = (str: string) => {};

switch (typeOfFn) {
  case "function":
    expectString(obj.fn());
    break;
  case "string":
    expectString(obj.fn);
    break;
  default:
    // Handle other cases here
}

switch (typeof obj.fn) {
  case "function":
    expectString(obj.fn());
    break;
  case "string":
    expectString(obj.fn);
    break;
  default:
    // Handle other cases here
}

I apologize for the misunderstanding. Your original code should actually work as expected without requiring any type assertions. The type narrowing based on the `typeof` check in your `switch` statements should work correctly for the given scenario.

**Comment by Nek0-hinata** [comment]
Can't we store the result of `typeof` in advance to narrow down the type in switch statements?

`type StringOrFunction = "Foo" | (() => "Bar")

const obj : Readonly<{ fn: StringOrFunction }> = { fn: () => "Bar" } 
const typeOfFn = typeof obj.fn

const expectString = (str: string) => {}

switch(typeOfFn) {
    case "function":
    //     This expression is not callable.
    //   Not all constituents of type 'StringOrFunction' are callable.
    //     Type '"Foo"' has no call signatures.(2349)
    expectString(obj.fn())
    break;
    case "string":
    // Argument of type 'StringOrFunction' is not assignable to parameter of type 'string'.
    //   Type '() => "Bar"' is not assignable to type 'string'.(2345)
    expectString(obj.fn)
    break;
    default:
}

switch(typeof obj.fn) {
    case "function":
    expectString(obj.fn())  // It works
    break;
    case "string":
    expectString(obj.fn)    // It works
    break;
    default:
}
`

**Comment by xiBread** [comment]
@yagnikvadi2003 Can you not clog the issue with ChatGPT responses
