### ISSUE TITLE
`Infer function return type` should also working for `.tsx`

### ISSUE THREAD

**Issue by loynoir** [microsoft/TypeScript#55314]
`Infer function return type` should also working for `.tsx`

**Comment by mjbvz** [comment]
Seems for work for me with typescript: 5.2 (the current nightly).

![Screenshot 2023-08-08 at 2 43 29 PM](https://github.com/microsoft/TypeScript/assets/12821956/eab7a69b-43e0-426e-a61e-1cc4c8ebf87b)

If you're using `"jsx": "react"` it inserts: 

```
import React from 'react';

function App(): React.JSX.Element {
    return <></>
}

export default App
```

**Comment by loynoir** [comment]
- When `"jsx": "react-jsx"` from [@tsconfig/vite-react](https://github.com/tsconfig/bases/blob/main/bases/vite-react.json#L20), no candidate `Infer function return type`.

- When `"jsx": "react"`,  ts error `'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.`

- When `"jsx": "react"`, and code like below, OK

Input 

```tsx
import type React from 'react'

function App() {
  return <></>
}

export default App
```

Output


```tsx
import type React from 'react'

function App(): React.JSX.Element {
  return <></>
}

export default App
```

**Comment by RyanCavanaugh** [comment]
All of those sound like OK behavior. What are you expecting to happen differently?

**Comment by loynoir** [comment]
I expect [when `react-jsx`](https://github.com/tsconfig/bases/blob/main/bases/vite-react.json#L20), there is candidate `Infer function return type`.

And also, why there is no candidate `Infer function return type` when `react-jsx`?

**Comment by RyanCavanaugh** [comment]
I'm seeing the option appear when `jsx: react-jsx`.

I think we need a more concrete repro.
