### ISSUE TITLE
Format on type removes new line added in template literal

### ISSUE THREAD

**Issue by SujithJr** [microsoft/TypeScript#55324]
In a JS file, hitting enter/return between an opening curly brace and underscore within a template literal causes a glitch

- VS Code Version: 1.80.2 (Universal)
- OS Version: MacBook Pro M1 - v13.4.1 (c) 

Steps to Reproduce:

1. Create a javascript file (.js)
2. Add the code ``${_.length()}``
3. Place the cursor between the underscore `_` and opening curly brace `{` 
4. Hit `return` on Mac

https://github.com/microsoft/vscode/assets/29048470/80399ef9-0003-4917-a2f1-e2eb13cc0013

**Comment by mjbvz** [comment]
The normal format command also removes the new line. Moving to TS for further feedback

**Comment by RyanCavanaugh** [comment]
I can't repro this
