### ISSUE TITLE
Namespace 'global.Express' has no exported member 'User'

### ISSUE THREAD

**Issue by sugandansa** [microsoft/TypeScript#55327]
### 🔎 Search Terms

While build code
node_modules/.pnpm/@types+passport-oauth2@1.4.11/node_modules/@types/passport-oauth2/index.d.ts:55:63 - error TS2694: Namespace 'global.Express' has no exported member 'User'.

55     type VerifyCallback = (err?: Error | null, user?: Express.User, info?: object) => void;
                                                                 ~~~~


Found 1 error in node_modules/.pnpm/@types+passport-oauth2@1.4.11/node_modules/@types/passport-oauth2/index.d.ts:55

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______
While building the code i am getting the error'
node_modules/.pnpm/@types+passport-oauth2@1.4.11/node_modules/@types/passport-oauth2/index.d.ts:55:63 - error TS2694: Namespace 'global.Express' has no exported member 'User'.

55     type VerifyCallback = (err?: Error | null, user?: Express.User, info?: object) => void;
                                                                 ~~~~

Found 1 error in node_modules/.pnpm/@types+passport-oauth2@1.4.11/node_modules/@types/passport-oauth2/index.d.ts:55

### 💻 Code

```ts
// Your code here
```
   type VerifyCallback = (err?: Error | null, user?: Express.User, info?: object) => void;

### 🙁 Actual behavior

Error inside node module passport-oauth2

### 🙂 Expected behavior

Error in node modules

**Comment by RyanCavanaugh** [comment]
Please fill out the form properly 😕
