### ISSUE TITLE
The detection to unreachable code is inconsistent 

### ISSUE THREAD

**Issue by FlandreDaisuki** [microsoft/TypeScript#55329]
### 🔎 Search Terms

unreachable, reachability

### 🕗 Version & Regression Information

- I test between versions 4.0.5 and 5.1.6
- I'm not sure whether this relates to https://github.com/microsoft/TypeScript/issues/34955#issuecomment-561824718

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.1.6#code/MYewdgzgLgBFAWAnEB3AWgU2TAvDAFAJS4B8MA3nEqjAAwwC+A3AFAsBmArmMFAJbgY7WkQosYEqsnRYQRVpJihIIADYYAdKpABzfAHIMADwAOGXjG6IMAQ2DwbAI3X7CrBmy49+g9gEZ8SgRpegYALgopVFoIqABPMxB2KJlsBmJycUlg6PksiWUINU1tPUNTc1grW3snFzcWDxYAE3NVG2shbl4BMBSAeTAMUQihgDcsVg5unz6delFMxRyUQeGGxULirV0DarsHZwwYGwgYYzNeDGbXd08Z3pgdPwIg6hQX8IoVv1iEjCSAyG6TEy3eAQ2ki26h2ZQulUsYGsBzqGFujTYhVgKwAKigQBFRDgyOMsLgCMRiZEVjAAEyMKZeHqCeALDL5FJ4uSQgrgIow0p7JE1Q7qE5neFXG4NJpM2YweAvQIpelfcgrWl-RLJXH4kFLbLvWl5TZ87aC8qXKrClFHdEMIA

### 💻 Code

```ts
const throwZero = () => { throw 0 };

function f0() {
    throwZero();
    console.log('expect unreachable');
}

function f1({ throw0 }: { throw0: typeof throwZero }) {
    throw0();
    console.log('expect unreachable');
}
```

```ts
declare function throwOne() : never;

function g0 () {
    throwOne();
    console.log('unreachable as expected');
}

function g1 ({ throw1 }: {throw1: typeof throwOne}) {
    throw1();
    console.log('expect unreachable');
}
```

### 🙁 Actual behavior

In first code block:

The two `console.log()` are not identified as unreachable code.

In second code block:

It works at `g0` declaration but not `g1`.

### 🙂 Expected behavior

They should be unreachable code.

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/53510

**Comment by FlandreDaisuki** [comment]
@whzx5byb Thanks your help :D
