### ISSUE TITLE
Builds are much slower with current nightly

### ISSUE THREAD

**Issue by blesh** [Microsoft/TypeScript#5532]
We noticed after switching to the TypeScript nightly build that builds were taking a lot longer. Discussion can be found here: https://github.com/ReactiveX/RxJS/issues/650

This is the current SHA that builds slowly with TSC 1.8.0 nightlies: https://github.com/ReactiveX/RxJS/tree/c5cc06f0356076ec1f03dc6627561dda6ba592af

We've decided to leave it building against nightlies for now, in hopes that you'll be able to fix this issue.

Thanks!

**Comment by mhegazy** [comment]
@vladima is looking what happened there. do you know which build started to show this perf degradation? was it the 1.7.0-dev* builds?

**Comment by vladima** [comment]
It looks like a known perf issue with node v0.12.
```
vladima@vladima-OptiPlex-990:~/Sources/bugs/RxJS$ node --version && node ../../TypeScript/built/local/tsc.js --diagnostics
v4.2.1
Files:             165
Lines:           27629
Nodes:          123503
Identifiers:     41846
Symbols:       4598525
Types:          117863
Memory used:   229430K
I/O read:        0.01s
I/O write:       0.03s
Parse time:      0.37s
Bind time:       0.24s
Check time:      2.85s
Emit time:       0.42s
Total time:      3.88s
vladima@vladima-OptiPlex-990:~/Sources/bugs/RxJS$ nvm use v0.12.7
Now using node v0.12.7 (npm v2.11.3)
vladima@vladima-OptiPlex-990:~/Sources/bugs/RxJS$ node --version && node ../../TypeScript/built/local/tsc.js --diagnostics
v0.12.7
Files:             165
Lines:           27629
Nodes:          123503
Identifiers:     41846
Symbols:       4598525
Types:          117863
Memory used:   226743K
I/O read:        0.01s
I/O write:       0.05s
Parse time:      0.38s
Bind time:       0.40s
Check time:     14.39s
Emit time:       0.56s
Total time:     15.73s

```

**Comment by blesh** [comment]
@mhegazy it started after we upgraded to 1.8.. we used 1.7 builds for a while without issue.

cc/ @kwonoj

**Comment by kwonoj** [comment]
it's currently `1.8.0-dev.20151017`.

**Comment by mhegazy** [comment]
What version of node do you see this on? If this is 0.12 Can you try a different version, either 0.10 or 4/5?

**Comment by kwonoj** [comment]
Yes, thanks to @vladima 's help, confirmed node v4 shows faster results and trying to use those version on CI with https://github.com/ReactiveX/RxJS/pull/653. Originally it was using 0.12.

**Comment by blesh** [comment]
This solution is satisfactory for us, I think. Thank you for your help, everybody. I really appreciate it!
