### ISSUE TITLE
currentScript property not exists in Document interface

### ISSUE THREAD

**Issue by dashaus** [Microsoft/TypeScript#5533]
The [currentScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) not exists in Document interface.

**Comment by mhegazy** [comment]
A PR would be appreciated. here is some information about submitting a lib.d.ts PR: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by dashaus** [comment]
Ok. Nice. I will do it now!

**Comment by zhengbli** [comment]
This is fixed in https://github.com/Microsoft/TSJS-lib-generator/pull/17

**Comment by mhegazy** [comment]
@zhengbli should we close this? Or you want to do a port first?

**Comment by zhengbli** [comment]
@mhegazy I think these issues should be closed only when the changes are checked in the TypeScript repo. It might be easier to track if we can add a new label to these ones, like "Fixed in TSJS" so we can close them in batch when syncing with that repo.

**Comment by mhegazy** [comment]
Sounds good.
