### ISSUE TITLE
TS 5.0 decorators don't follow the DecoratorCallExpression grammar

### ISSUE THREAD

**Issue by evanw** [microsoft/TypeScript#55336]
### 🔎 Search Terms

DecoratorCallExpression

### 🕗 Version & Regression Information

- This issue is specific to TypeScript 5.0+ decorators (not experimental decorators)

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99&ts=5.1.6#code/CYUwxgNghgTiAEEQBd4A8Bc8AUBKeAvAHzwDe8AnlnoSdpvFAHYUA0lWzF+xjL8AXwCwAKAACaPADoKeUZCgBnRfABmAe3VlhIoA

### 💻 Code

```ts
declare let x: () => { y: () => (x: any, y: any) => any }
@x().y()
class foo {}
```

### 🙁 Actual behavior

TypeScript allows this invalid syntax without any errors.

### 🙂 Expected behavior

Here's the grammar (taken from the spec linked in [the proposal](https://github.com/tc39/proposal-decorators)):

```
Decorator[Yield, Await] :
    @ DecoratorMemberExpression[?Yield, ?Await]
    @ DecoratorParenthesizedExpression[?Yield, ?Await]
    @ DecoratorCallExpression[?Yield, ?Await]

DecoratorMemberExpression[Yield, Await] :
    IdentifierReference[?Yield, ?Await]
    DecoratorMemberExpression[?Yield, ?Await] . IdentifierName
    DecoratorMemberExpression[?Yield, ?Await] . PrivateIdentifier

DecoratorParenthesizedExpression[Yield, Await] :
    ( Expression[+In, ?Yield, ?Await] )

DecoratorCallExpression[Yield, Await] :
    DecoratorMemberExpression[?Yield, ?Await] Arguments[?Yield, ?Await]
```

My reading of this grammar is that TypeScript should only be allowing a single `Arguments` production at the end of the decorator. So I believe TypeScript should consider this example to be a syntax error. Here's what other decorator parsers do:

* [Babel](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=CYUwxgNghgTiAEEQBd4A8Bc8AUBKeAvAHzwDe8AnlnoSdpvFAHYUA0lWzF-xjL8AXwBQAATR4AdBTxDIUAM7z4AMwD2qssKA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ctypescript&prettier=false&targets=&version=7.22.10&externalPlugins=%40babel%2Fplugin-syntax-explicit-resource-management%407.20.0&assumptions=%7B%7D):

    ```
    /repl.ts: Leading decorators must be attached to a class declaration. (2:4)

      1 | declare let x: () => { y: () => (x: any, y: any) => any }
    > 2 | @x().y()
        |     ^
      3 | class foo {}
      4 |
    ```

* [esbuild](https://esbuild.github.io/try/#dAAwLjE5LjAALS1sb2FkZXI9dHMAZGVjbGFyZSBsZXQgeDogKCkgPT4geyB5OiAoKSA9PiAoeDogYW55LCB5OiBhbnkpID0+IGFueSB9CkB4KCkueSgpCmNsYXNzIGZvbyB7fQ):

    ```
    ✘ [ERROR] Expected "class" after decorator but found "."

        <stdin>:2:4:
          2 │ @x().y()
            ╵     ^

      The preceding decorator is here:

        <stdin>:2:0:
          2 │ @x().y()
            ╵ ^

      Decorators can only be used with class declarations.
    ```

**Comment by rektide** [comment]
Part of me wants to push to get the spec updated to allow more complex/arbitrary expressions. Nice spotting this.

**Comment by trusktr** [comment]
I've been wondering if there should have been a new option called `--standard-decorators` (`standardDecorators`) that defaults to `false` due to small things still fluctuating (whether there or here), then eventually defaulting to `true` once things settle.
