### ISSUE TITLE
Should infer not undefined in "else" when checked in compound boolean expression in "if" 

### ISSUE THREAD

**Issue by yftachman** [microsoft/TypeScript#55331]
### 🔎 Search Terms

"infer", "undefined", "compound", "boolean expression"

### 🕗 Version & Regression Information

i dont know if this is changed behaviour

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDKHJgBcyWUoA5sgD7ICuIAJhDKBMwNx4C+eeGEwRhgAexDFMYAGLCAFHDLosAGmQAjMhrFiANhDggAlPiLIA9BeQAFKGI0GAtsgRwMEAkWAxk8jcgAZIHIAIRwAHRgxrhe5oQIEhj6EBF6YlTyAOQ+WcZxyLzIEHoesfFEVsgAkgByAMIA8gBKzQCi9ajIALTIIGLYTKzsIJzkABZiDHrMmiigMNBQnAXmiSBYmsgAvMiRYBGgrAAejTDZAIx5POb8AuZVAOpiUADW1K7unuY+fgHBeyiMTMFUs1iarQ6XV6-UGLDYHFmCyWK1BriS2ACu32h3hp3OWSuxhuRDuD2szzeHzcHgKv3k4SB5VBVgKRRKZRBFSqEPanR6fQGjHhIzGyKgy2YqyI602WMBByOEHxl2ubL4QA

### 💻 Code

```ts
interface Test {
    t: string | undefined;
}

function testFunc(a: Test, b: boolean){
    // Problem case
    if (b && !a.t) {
        console.log('if')
    } else {
        // INCORRECT - not undefined should be inferred
        const b = a.t.indexOf('1');
    }


    // Working case
    if (b && a.t) {
        // CORRECT - not undefined inferred
        const b = a.t.indexOf('1');
    }

    // Working case
    if (!a.t) {
        //
    } else {
        // CORRECT - not undefined inferred
        const b = a.t.indexOf('1');
    }
}
```

### 🙁 Actual behavior

a.t was checked to be undefined by if, but in else it is not inferred.

in test case 1, we can see that doing the reverse (checking for defined and checking in "if" for defined works correctly)
in test case 2, we can see that if its not a compound boolean expression it works correctly

### 🙂 Expected behavior

inferred type in else should be defined because it was checked in the if

**Comment by MartinJohns** [comment]
>         // INCORRECT - not undefined should be inferred
>        const b = a.t.indexOf('1');

If your `boolean` `b` is `false`, then you have no clue whether `a.t` is `undefined` or not. Why shouldn't it be `undefined` here?

**Comment by malikmouhiidine** [comment]
That is precisely what Martin just said.

Here is a truth table to understand the more the logic:

<html>
<body>


a.t | b | b && !a.t | Result in "if" block
-- | -- | -- | --
defined | exists | false | Not executed
defined | exists | true | Executed
defined | absent | false | Not executed
defined | absent | true | Not executed
absent | exists | false | Not executed
absent | exists | true | Not executed
absent | absent | false | Not executed
absent | absent | true | Not executed


</body>
</html>

**Comment by RyanCavanaugh** [comment]
The legal call
```ts
testFunc({ t: undefined }, false)
```
crashes this function.
