### ISSUE TITLE
TS assumes navigator does not exist if it doesn't have a "share" property

### ISSUE THREAD

**Issue by jpcastberg** [microsoft/TypeScript#55341]
### 🔎 Search Terms

TS2339, Property does not exist on type 'never'

### 🕗 Version & Regression Information

- This changed between versions 4.84 and 4.95

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.9.5#code/JYMwBAFARAzgFgQwE4FMpmAOzJhA3YAcwQBcB7JASjAG8AoMRsAembHmRXbIFsUS4WQnQC+YFABsYXekxz4ipCgDoAxhOAAHAEZlkAE1FA

### 💻 Code

```ts
if ("share" in navigator) {
    // share something
} else {
    navigator.clipboard // TS throws "error TS2339: Property 'clipboard' does not exist on type 'never'"
}
```

### 🙁 Actual behavior

When checking for device support of the ["navigator.share"](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) api, typescript assumes that if the "share" property does not exist on navigator, then navigator must be of type "never".

### 🙂 Expected behavior

Not all browsers support the navigator.share api, so the share property not being present on navigator, but other properties of navigator still being present is a valid case. See browser support for navigator.share on MDN: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/51059

**Comment by jpcastberg** [comment]
Thanks for the fast reply. I don't fully comprehend the reasoning behind this behavior, but can appreciate that accounting for these kind of dynamic browser-dependent interfaces might be out of scope for the project.

Perhaps the error messaging could be updated to acknowledge this case and describe the workaround?

**Comment by MartinJohns** [comment]
> Perhaps the error messaging could be updated to acknowledge this case and describe the workaround?

There are no individual error messages for specific types, and changing the error message in general for all cases is just unnecessarily muddying the waters for 99.69 % of the cases.

**Comment by jpcastberg** [comment]
Agreed - even though it makes me sad. I discovered another workaround - saving the check to a variable and using that makes the error go away:

```ts
const isNavigatorShareAvailable = "share" in navigator;

if (isNavigatorShareAvailable) {
    // share something
} else {
    navigator.clipboard // no error, yay
}
```

A bit surprising that the compiler doesn't mark this case as an error as well though.
