### ISSUE TITLE
Object's value having string keys should consider `undefined`.

### ISSUE THREAD

**Issue by ozum** [microsoft/TypeScript#55343]
### 🔎 Search Terms

object string key undefined value 

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about the object

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.0-beta#code/MYewdgzgLgBCBGArAXDASgU1AJwCYB5psBLMAcwBoYwBXAW3g2wD4YBeGAbwCgYYAPVAEYKvGAE9UAJlEBfANzduoSLDoBDAA6oAslsJQS5KrQZNWHMBgDuMPZoAUAbTFOARPzdUhAXVF93cS8YKT9uHwBKRWVwaBh1djgkADoAL0UVOPhEjU1ksgwoBzdUtyilTJAAGwxkqpAyBwSAahghcsqauoaHbNb2+SA

### 💻 Code

```ts
const obj: Record<string, number> = {
  x: 1,
  y: 2,
};

const map: Map<string, number> = new Map([
  ["x", 1],
  ["y", 2],
]);

const a = obj.z;
const b = map.get("z");

console.log(a + 1);
console.log(b + 1);
```

### 🙁 Actual behavior

Type of `a` is `number`.
Type of `b` is `number` or `undefined`.

### 🙂 Expected behavior

Type of `a` is `number` or `undefined`.
Type of `b` is `number` or `undefined`.

We can use `a` as if it is a number. Actually, it is not. It seems the behavior of `Map` is more correct.

Is there a specific reason why objects and maps are acting differently for the very same code?

Thanks in advance,

**Comment by MartinJohns** [comment]
That's what the `noUncheckedIndexedAccess` compiler option is there for. This is working as intended.

**Comment by ozum** [comment]
Thanks for the fast response @MartinJohns.
