### ISSUE TITLE
instanceof type guard does not narrow type of `this`

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#5534]
Here's an example which demonstrates (tested on 1.6.2 and current playground):

```typescript
class Foo {
	a: number;
	
	foo(): string {
		if (this instanceof Bar) {
			return this.b;  // not okay - `this` typed as Foo
		}
		return '';
	}
	
	bar(): string {
		let that = this;
		if (that instanceof Bar) {
			return that.b;  // okay - `that` typed as Bar
		}
		return ''
	}
}


class Bar extends Foo {
	b: string;
}
```

**Comment by kitsonk** [comment]
I think this is all related to polymorphic `this` #4910 which isn't in 1.6.2 (and playground is 1.6.2).  Before that, you couldn't change the `this` type.

**Comment by ahejlsberg** [comment]
Type guards currently only affect parameters and local variables, but I agree it seems reasonable to also have them apply to `this`. @kitsonk No, not related to the polymorphic `this` feature, the restriction is still there in current builds.

**Comment by mhegazy** [comment]
This should be working as expected in master.
