### ISSUE TITLE
Arrow function don't see `never` as a return type, while normal functions do

### ISSUE THREAD

**Issue by Asaf-S** [microsoft/TypeScript#55351]
### 🔎 Search Terms

"typescript function that throws", "typescript function that always throws"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 4.7 + 5.1

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.6.4#code/GYVwdgxgLglg9mABBBBnOAbApgUQE55x4CCYAJgCoAWhA7gPoCMAFFgUQLJaqoCGA5lgBciVFDwww-AJQiwWAG5tEAb0QB6dYgA8AWn2IAckQC2vDIlCRYCALAAoRE+RpMWAHRtCeVuzxceASxpAG4HZ0QoGjhaRHlY-G9fbwC+QVCHAF8HBxQwMURaPF4ABxK2ADFwaHgwJkQAXkRmdBMsADVePDkQEwAjNmlGgD5VcMQYYGbWjq6dRABWIZVxiLwsKBA8JBnOvDDHREzELAxULDHDiLz0bESiUkpohhYAA3u8Qt5USzhwMgAhK8ModsvZMgdcmgoC58m4Po9qHR6AAmRrNLycbhpYSicSSGRyRTKBqjNQaLR6AzEdixKw1OyHG5uTx+ZJYwLpA5OKJ0OJYBJszH+bFBEFgqH5GFFUrlPBVay1VHolpwNp7Hr9QYjVQUoxwGHmCwoMgXEq8KI-dabbaIXiIBTmEAeZoAdgADABmd3SVYTKaq9VzbSLZZ+tYbLY7NWzfZ+46nc6XCLXVx3PyI56o5jvPxfH7AP7kIEgiJgiEOIA

### 💻 Code

```ts
function consoleErrorAndThrow_1(errorMessage: string): never { // <--- Normal function
    console.error(errorMessage);
    throw new Error(errorMessage);
}

const wrapperFunction_1 = (someVar: number) => {
  if (someVar < 5) {
      return someVar;
  } else {
      consoleErrorAndThrow_1(`Error was found!`);
  }
};

const consoleErrorAndThrow_2 = (errorMessage: string): never => {  // <--- Arrow function
  console.error(errorMessage);
  throw new Error(errorMessage);
}

const wrapperFunction_2 = (someVar: number) => { // Not all code paths return a value. (7030)
    if (someVar < 5) {
        return someVar;
    } else {
        consoleErrorAndThrow_2(`Error was found!`);
    }
};
```

### 🙁 Actual behavior

Get error `Not all code paths return a value. (7030)`

### 🙂 Expected behavior

No error

**Comment by Asaf-S** [comment]
Is it a bug or an undocumented feature?

**Comment by MartinJohns** [comment]
It's working as intended and documented here: #32695

**Comment by fatcerberus** [comment]
> documented here: https://github.com/microsoft/TypeScript/pull/32695

In particular, this rule:

> each identifier in the function name references an entity with an explicit type

`consoleErrorAndThrow_2` has no type annotation.

**Comment by Asaf-S** [comment]
Setting the type of `consoleErrorAndThrow_2` solves this issue, although I'm not really sure why, as the constant's type should be taken from its value.

```ts
const consoleErrorAndThrow_2: (errorMessage: string) => never = (errorMessage: string): never => {  // <--- Arrow function
  console.error(errorMessage);
  throw new Error(errorMessage);
}
```

**Comment by MartinJohns** [comment]
> although I'm not really sure why, as the constant's type should be taken from its value.

For performance reasons only identifiers with type annotations are analyzed.

**Comment by Asaf-S** [comment]
> > although I'm not really sure why, as the constant's type should be taken from its value.
> 
> For performance reasons only identifiers with type annotations are analyzed.

Make sense, thx!
