### ISSUE TITLE
Record is not assignable to intersection

### ISSUE THREAD

**Issue by quangloc99** [microsoft/TypeScript#55355]
### 🔎 Search Terms

`union`, `Record`, `assignment`, `property is missing`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [Common "Bugs" That Aren't Bugs](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.1.6#code/C4TwDgpgBAYg9nKBeKAlCBjOAnAJgHgGdhsBLAOwHMAaKcgVwFsAjCbAPgG4AoUSKAEIBDbMigBvKEIBcdJq1EBfKADIJUZlFkMWbKIp7cA9EamFCpSuUYRywKLjgRCdOPYDuOANbdcmADYi0P4Q9gBmCLLwcDx+GIHYwaEaIrLC2DzMImIRMVBQJlD4ALSlZVBs2DjcxqZh9OQYwKRw5FAYQv7+Dk4u5G5Qntg+cQnQ9Y3NrVBh5AAUMoIiAJSyAG5wpLg8s3O5y5z5hSVlpxXYVdjcQA

### 💻 Code

```ts
type Foo = Record<string, number>;
type Bar = { a: number } & { b : number };

// assignment does not work
declare let foo: Foo;
declare let bar: Bar;
bar = foo;  // <------ error

// function call does not work
declare function fn(a: Bar): void;
fn(foo);  // <-------- error

```

### 🙁 Actual behavior

There is an error in the assignment, as well as in the function call.

The error diagnosis message was:
```
  Property 'a' is missing in type 'Foo' but required in type '{ a: number; }'.(2322)
```

### 🙂 Expected behavior

The error should not have happened, as the union type `Bar` (`{ a: number } & { b: number }`) is a subtype of `Foo` (`Record<string, number>`).

The reason I think this was the case is that the subtype should be an **extension** of the supertype, that is, its properties should include the properties of the supertype, as well as its own properties.

Here we can see the `Record<string, number>` has infinitely many keys, and this set **includes** the keys of the union `{ a: number} & {b: number}` type. Therefore the `Record` type should be the subtype of the union one.

**Comment by quangloc99** [comment]
I have edited the issue post a bit because some part of the playground code is not what I expected. I also included my reasoning.

**Comment by MartinJohns** [comment]
This is working as intended. The type `Foo` **may** have the properties `a` and `b`, but the type `Bar` **must** have them.

**Comment by quangloc99** [comment]
I don't think so. `Foo` actually `a` and `b` **defined** properties (and many other **defined** properties), and this should work in strict mode.

In runtime, I can even construct an object that has many keys with `Proxy`.

**Comment by MartinJohns** [comment]
> `Foo` actually has `a` and `b` as its **defined** properties (and many other **defined** properties)

Uhm.. No.

```typescript
const foo: Foo = {}; // No properties a and b
```

**Comment by quangloc99** [comment]
That is just initialization. You can still get arbitrary properties out of `foo: Foo` and it will always be `number`.

```ts
const foo: Foo = {};

const x: number = foor.x;
```

**Comment by MartinJohns** [comment]
Again, the type `Bar` says there **must** be properties `a` and `b`. But the type `Record<string, number>` does not dictate that these properties must exist, they **may** exist, or they may be missing. You can't assign a type that misses some properties to a type that mandates having them. I'm not sure how to explain this any simpler.

This is working as intended.

**Comment by fatcerberus** [comment]
Also, for what it’s worth, `&` is *intersection*, not union.

**Comment by quangloc99** [comment]
I just want to ask to have a better understanding of Typescript and apply it better.

So to be type-safe, in most cases, I should not use `Record<string, number>`, but `Partial<Record<string, number>>` or `Record<string, number | undefined>`? The alternatives actually do what the original _should_ do: indicate the properties _may_ exist.

With `Record<string, number>` I can still manipulate it on the type level like extracting the property type with index access, which gives me a defined type.

**Comment by quangloc99** [comment]
> You seem to think that the type `Record<string, b>` defines _all_ properties, but it actually defines _no_ properties at all. It defines an index signature.

Yes, I do believe `Record<string, b>` should be used to define an object with all possible properties, because there is a case for that:

```ts
const x = new Proxy<Record<string, number>>({}, {
    get(target, p, receiver) {
        return String(p).length;
    }
});

console.log(x.xyz);
```

**Comment by quangloc99** [comment]
> Also, for what it’s worth, `&` is _intersection_, not union.

Thank you. I'll change the issue title.

**Comment by MartinJohns** [comment]
> So to be type-safe, in most cases, I should not use `Record<string, number>`, but `Partial<Record<string, number>>` or `Record<string, number | undefined>`? The alternatives actually do what the original _should_ do: indicate the properties _may_ exist.

Or turn on the compiler option `noUncheckedIndexedAccess`.


> Yes, I do believe `Record<string, b>` should be used to define an object with all possible properties, because there is a case for that:

Your example is such a rare corner case, it's unreasonable to expect this behaviour on a type level just to support the chance of having a proxy that will always return a value. In 99.9 % of the cases you deal with objects that don't have a value for **every** property.

**Comment by quangloc99** [comment]
Thank you for being patient and for your detailed explanation. I understand better now. I'll close this issue then.
