### ISSUE TITLE
`include` patterns need to specifiy `.json` extension in composite projects despite `resolveJsonModule: true`

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript#55366]
### 🔎 Search Terms

include composite resolveJsonModule

Reopening of https://github.com/microsoft/TypeScript/issues/25636 which doesn't seem to have fixed all problems reported in that issue

### 🕗 Version & Regression Information

This is the behavior in every version I tried (up until 4.1)

### ⏯ Playground Link

https://github.com/eps1lon/ts-references-json

### 💻 Code

```ts
import data from "./data.json";

export default { data };
```

```json
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "composite": true
  },
  "include": ["./**/*"]
}

```

### 🙁 Actual behavior

```bash
$ tsc --build tsconfig.json
feature-two/index.ts:1:18 - error TS6307: File '/Users/sebastian.silbermann/ts-references-json/feature-two/data.json' is not listed within the file list of project '/Users/sebastian.silbermann/ts-references-json/feature-two/tsconfig.json'. Projects must list all files or use an 'include' pattern.

1 import data from "./data.json";
                   ~~~~~~~~~~~~~


Found 1 error.
```

Explicitly adding `.json` to `include` like https://github.com/microsoft/TypeScript/issues/25636#issuecomment-627111031 suggested works also but is unintuitive since the extension is only required in composite projects.

### 🙂 Expected behavior

Compiles just fine without having to add another `include` pattern using `.json`.

**Comment by eps1lon** [comment]
While this may be what you intended when implementing, it's not intuitive from a user perspective.

**Comment by sheetalkamat** [comment]
Given that data.json will be copied to your `outDir` it seems correct that it should be listed in your config. 

But while writing above comment i realised, your config doesnt have `outDir`. So it seems like a bug where `data.json` shouldnt need to be listed? 

Note that if we change this, it also means that not listing `data.json` has implications on `tsc --build` only root files specified by config are checked if anything changed with respect to output and with this it will not rebuild project if data,json gets updated after project was successfully built.
