### ISSUE TITLE
Cross-project symbol search no longer works (at least in our codebase)

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#55372]
Repro steps:

1. Open the TypeScript codebase in VS Code
2. Open `src/compilers/utilities.ts` and close everything else
3. Command palette > Reload window (restarting TS Server is **not enough** to ensure a clean cache, not sure why—it may not restart the syntactic server?)
4. Invoke global symbol search (⌘T for me, `#` prefix in the command palette) for `skipConstraint`. See no results.
5. Open `src/services/utilities.ts`.
6. Optional: close `src/services/utilities.ts`—what matters is you forced it to load.
7. Search for `skipConstraint` again. The result from `src/services/utilties.ts` now populates.

I’m like 99% sure @amcasey made this work in the past, regardless of what you had already loaded, but I haven’t tried to find a past version of TS where it works.

**Comment by jakebailey** [comment]
I definitely hit this all the time, but in my testing, you don't need to open `services/utilities.ts` at all; just wait a second on the first search and then change it / retrigger it manually and then the result appears.

I can see in the bar at the bottom that projects are loading when the first search happens, but the query finishes before that, apparently.

**Comment by andrewbranch** [comment]
That’s not what happens for me. They never load.

**Comment by andrewbranch** [comment]
It was caused by https://marketplace.visualstudio.com/items?itemName=mxsdev.typescript-explorer.
