### ISSUE TITLE
Recursive reverse mapped types don't work well with mixed object and tuple structures

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#55382]
### 🔎 Search Terms

inference recursive reverse mapped type tuples arrays

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPigAfKIQipi+WgBsQrDl14BtALoBuAFDrQkKABEIAMzrVg1SaQAqArAG91UKIoDSUOlHYQQ+A1AvKAXFAAFEEAlJgCFs7K4cL6RrQmZrSW0XwaAL4a6sR4UqiiUAZscKaSUHCiqMAQllAQAB41tMTksIgoqHxBuQlJkoHxxmUpVqGBFtkEtJQiEOQsUsCYFVU1QXYOqIFhEVAAjIz2UABGgZsOFTvhGAIARHdHDhlHGaHZAPQfUMAI1G2SaCJOAQGSuWgGCCENoAAxsUG2UFoLGQJyhqlO5yuUEoNAYUAyBJh6lECyWGi+UAAegB+TTTWakxbAABMK0qYnWil2twOzG5N3ud2UMU+31+-yggPBkOhUBhyNRUJUMNOLGWJhxCHwi2IMqh8sUirRhH5uLo9BFxKZSxZFO+tPpkkZ82ZAGZ2WsIBtjoieQJDsczo5-VAHspXu9NJSJQDaNA6LLYfDEcaocxg+aGCoiWqNctyNrdfrCPKU4E06bMY4s5aiSTXUs3fbqTSgA

### 💻 Code

```ts
type Schema = Record<string, unknown> | readonly unknown[];

type Definition<T> = {
  [K in keyof T]: (() => T[K]) | Definition<T[K]>;
};

declare function create<T extends Schema>(definition: Definition<T>): T;

const result = create({
  a: () => 1,
  b: {
    c: () => "",
  },
});

// this one nicely infers `{ a: number; b: { c: string } }`
result;
// ^?

const result2 = create([() => 1, [() => ""]]);

// this one infers `number[]` but it should infer `[number, [string]]`
result2;
// ^?

const result3 = create({
  a: () => 1,
  b: [() => ""],
});

// this one infers `{ a: number, b: string[] }` but it should infer `{ a: number, b: [string] }`
result3;
// ^?
```

### 🙁 Actual behavior

tuples can't be inferred recursively here

### 🙂 Expected behavior

tuples are inferred as arrays

### Additional information about the issue

I understand that I need some tuple context to actually infer tuples but I've tried a couple of ways to add it and I just can't make it work. It would be much simpler if TS would just infer tuples here with the original code.

1. an attempt with `const` type parameter: [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPigAfKIQipi+WgBsQrDl14BtALoBuAFDrQkKABEIAMzrVg1SaQAqArAG91UKIoDSUOlHYQQ+A1AvKAXFAAFEEAlJgCFs7K4cL6RrQmZrSW0XwaAL4a6gD0OVDixHT0UAS0lFASEOS0AOTAUEhSYK7A6sR4UqiiUAZscKaSpaKowBCkZRUWUBAAHmO0xOSwiCiofEEdCUmSgfHGgylWoYEW2ZMNouQsUg1YcCNjQXYOqIFhEVAAjIz2UABGgReDlK73CGAEACJIb8HBlfhlQtkrjdgBo8lAAHoAfk0FxE1VRACZMMMxE9FB8Id9mJTwVDIcoYsjCbciej8ji8ZIKijbgBmUkPckQZ5-N7Bek0v6AxxUhnKBFIzR84D8jlY7FAA)
2. an attempt with adding a constraint to `Definition`: [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPigAfKIQipi+WgBsQrDl14BtALoBuAFDqA9FqjjidelAK1KhVHWBQJEcrQDkVpFLBQARnlQty0YElpQAAYAKooA0sqBUNySjlDkqMDU5ABmstRWonAshOTUAG4QMuqgkFAAIhApdBnUkqTBUBAAHsAQtMTksIgoqAJYAN7qUFDhUHRQ7BAg+ClQwcoAXFAAFCsAlJgCoRGbwpXVtLX1O8p8qlA68+DQ9qf21vi2UFxWCUmpsn7QJmYWtFZ7PAkGh7AA6dQAXw06mIeCkqFEUBSbDgSUkxlEiQgDSarXanW6IL6Kzhh2OtGWBxq6NoDT462WwRhv0ythYUisWDgWLaKyGI1Qyw2WygAEZGMN3MsBSNjMLNhgBAAiZWSkaQyWQ9Yw0TkDnADRXAB6AH5NKyROzOQAmTCYsR8xQipXi5jOxUq5XKZQ6zR6g02o26M0WySUK36zkAZntPMdEH5UqFq09bqlbmWHtFquUWr96gDMeDUFDQA)
3. "routing"/resolving the `T[K]`'s constraint using a conditional type to satisfy the `Definition`'s constraint: [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKAV1oGtb8B3WgPigAfKIQipi+WgBsQrDl14BtALoBuAFDrQkKABEIAMzrVg1SaQAqUCAA9gEWsXKxEKVAKwBvdVCgB6PygAIkJ8FlMGIKhgJCgAAwtFAGllOKhUKXJ8KAkIcloAcmAoJCkwZhMoACNRVHZnGOhuBHwpaFE4FkJyagA3aDoDCFFaOAhmcghoDKlWclR6aFtUZDA28h8oZKg6KHYIEHwDKAtlAC4T5OVrOwcnFyQ0KAB+PUNjU3NElIELgAoAJSYATfNRQdQAXw06mIeCkqFEUAMbDgn1oUDgtXslhu9kczngj3cf1hRloJjMtAu+jJFK+fABFws0IItEoIjyLCkxSwmLE9j+3l8qH+QIwAgAjIxNlULkLfBjRcDgkFpb4IdKIQDoaJyFzgBoAlAAHrPTSs9m6-UAJkwGKxED+ikByqlWxd4pVymU2s0Vu51sNgVN5skls53IAzHa+agBfKRVAPZK1dULs6xQIgkFlJrfep-cBI0GTWagA)
4. an attempt with changing `Schema` to use `any` over `unknown` to fix the recursive constraint problem: [TS playground](https://www.typescriptlang.org/play?#code/PTAEGMAsEMDsHMCWDQBdIFNQDdoBsBXDYDPDAWw1lTQE8AHLVAe1AAM5a3QATZjAM6wA5DQDuzAE4BrUBkToMkgFCoGWAMpQK0UAF5QAJQzgpPADwDUk5PAA0oTgD5QAH1CSM0PrDy1HsLQA2gC6ANzKquqgACIYAGbICojMsOYAKnIAHqhUPAKgWpjk0C4GAN7KoKBBANKgyKDSGLTM8aDpIQBcoAAUvQCU+i7pdSFD7nGJsMmpGWNOEQC+Eco8JnjQnqDxBLDgqCmwEJ7QuRnZubD5hdolTr3r07OwPVNJh3PpTgM96aumWBWDyCAh4GgGcCnXK9SrVaA9QbDUAARjsVVAACMenDqhBEUM9C4AETE9HVJbopYDVaeARg1ARECgAB6AH5IoDgXSGQAmfQnLwwoJIomohwiwkk4khca00Hg3lMsDszmpbkK1AAZgFUKFGFhGIRfSl4ox2JqoulISpNMiPPBWuVrI5QA)
5. an attempt with a separate mapped type for the array constraint and routing to it: [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAygxgCwgWwIZQLxQEoTgewCcATAHgGdhCBLAOwHMAaKVWkAPigB8pCJVi+WgBsQLNgG0AugG4AUHNCQoAEQgAzOtWDUhAQUKFSAFSgQAHsAi1i5Xv0EixrENM5YA3nKhQJAaSg6KABrCBB8dShjKQAuKAAKeIBKTE5jfykUnjVNWm1dWhMM9nkAX3k5AHpKqAAiQnwAVx0GWqhgJCgAA2MulmFyfChBCHJaAHJgKCRhMGZtKAAjPlRguw7oAHcEfGFoPjhGwnJqADdoOnUIPlo4CGZyCGhUYWEoRvJUemgLVGQwPbkKo1fCLABWeGAAFohKIoKdUDRWFNlvw1lBNtoEN1jOALrRKMjqKgdEJAnYLHdyCdznDiE8wOJiFAwPhqdRFnDLlorAA6eIAJgArAAOACcSS6ijxqg0PIKJjMlmstlgiBQqHcUSVVhsdhWjjhLmk3igAH5Zbl8vpDCZ2Ka4l4fM7fAEgqFwpFonFEikMGkMllLfKhEU-FISqafOUFPS4MJEdB1I1bqTaFA4CsrIqLLrVfAkGh2PF6Va03EciHCsZ2Ek4sYKgQCVM+ORGsIplhM-wrPEnSwfX7OABGRimxaOqMZwepOq1MfRselJIVVvt4DyapQAB6ZoUTco9jbHYFmAzWYg8QkyVno98N-9c6kmVXo3XAs3NV3+6Eh7XHYAZjPbsSUvftUBnR9R3HOJryHJ8lxXBR-2AADPx3PcgA)

**Comment by andreaTarascioSophany** [comment]
Hi! I would be excited to contributing fixing this issue
