### ISSUE TITLE
Feat: Allow template literal types as interface property keys

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/TypeScript#55385]
### 🔍 Search Terms

template string, template literal types, property key, computed properties

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Add the ability to use template literal types to declare property keys on interfaces.

```tsx
interface Foo {
  [`foo_${string}`]?: boolean
}

const a: Foo = {
  foo_name: true,
  foo_bar: true,
}
```

### 📃 Motivating Example

We want to extend the JSX types for Preact to declare conditional class names similar to svelte. For that they use a `class:*` property whose value is a boolean.

```jsx
<div
  class="foo"
  class:my-class={condition}
  class:some-other-class={condition}
/>
```

The problem is that the part that comes after `class:*` isn't known upfront. Ultimately, the user decides how they name their CSS class so that part of the property key is dynamic.

### 💻 Use Cases

1. What do you want to use this for?
Extending JSX types for Preact

2. What shortcomings exist with current approaches?
Index types cannot be marked as optional. Something I tried is this:

```ts
// Index types cannot be marked as optional
interface Foo {
  [key: `foo_${string}`]?: boolean
}
```

The only other way I found was to first declare the type and add a `Partial<>` around it:

```ts
interface InternalFoo {
  [key: `foo_${string}`]: boolean
}

type Foo = Partial<InternalFoo>
```

Problem is that this doesn't work with declaration merging of JSX types where I need to extend an existing interface.

3. What workarounds are you using in the meantime?
None, can't get it to work.

**Comment by MartinJohns** [comment]
> Index types cannot be marked as optional.

Why would they? The properties of index types are by definition already optional.

**Comment by Andarist** [comment]
A running example of the above: [TS playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gJRFMGAXPFCgJ4DcAUFSlALYhoAO+CAUgMoAa8A3lXjwQAD2ZIYWAJYoMIGADM28AJKyYMtFLABBDBg0AjAK5y0-QUPgBtANbEABpCho0hACR9MGlAHMAvg4AusSGSEgQeCjwAD7wxiigCjIgwNRC-pai4pLwMnKKymoGmtoAopGMsuYCVvDAUgBuxFzcAHTFPlq6+kamTOnwmZlUADwNjfAA9AB81ONNiNCuhArh03NjE0submtIALx8AIwADKf+G9RAA)

```ts
declare const React: any;

namespace JSX {
  export interface IntrinsicAttributes {
    [k: `class:${string}`]: boolean | undefined;
  }
  export interface IntrinsicElements {
    div: JSX.IntrinsicAttributes;
  }
}

<div />;
<div class:foo />;
<div class:foo={100} />;

```

**Comment by marvinhagemeister** [comment]
Thanks for the responses! I didn't occur to me that I could simply type the value as `undefined` and that that would have the same effect. That solves my case 👍
