### ISSUE TITLE
Falsy instanceof check doesn't affect righthand or expression

### ISSUE THREAD

**Issue by LeviticusMB** [microsoft/TypeScript#55395]
### 🔎 Search Terms

instanceof or unknown

### 🕗 Version & Regression Information

- Didn't think of it until 4.4 when caught values became unknown, but the actual problem has probably been present for a long time.

See #38309, for instance.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.0-beta#code/MYGwhgzhAEDqCmAjAogJ1Qe1deAPALvAHYAmMAqgEoCSam2A3gLABQ070E+Y+ArhAH4AXNCK8AtonioA3KwC+rVvlQBPaMzYcA9NugBZMAGt40MNFTwAjr3hcF0YD2AALaAAppqAJQbWHaABLADMPLyCiLjAiYHgMUIQUdCxoAF506GCwEAhTAB88nHQAOii+GABCVOgAFgAGAEZfTQCA4AxIjBB4Yq8sT3RvOS12RRYxoA

### 💻 Code

```ts
class WebError extends URIError {
    status?: number;
}

try {
    // Make a request
} catch (err) {
    if (err instanceof WebError === false || err.status != 401) {
        console.error(err);
    }
}
```

### 🙁 Actual behavior

The compiler thinks `err` is `unknown` and does not understand that err.status must be a valid property.

### 🙂 Expected behavior

No compiler error.

**Comment by nmain** [comment]
The recognized syntactic form for this one is `!(a instanceof b)`

https://www.typescriptlang.org/play?ts=5.2.0-beta#code/MYGwhgzhAEDqCmAjAogJ1Qe1deAPALvAHYAmMAqgEoCSam2A3gLABQ070E+Y+ArhAH4AXNCK8AtonioA3KwC+rVvlQBPaMzYcA9NugBZMAGt40MNFTwAjr3hcF0YD2AALaAAppqAJQbWHaABLADMPAEJPdCCiLjAiYHgMUIQUdCxfAB8MnHQAOli+GDCAXmgAFgAGAEZfTQCA4AwYjBB4XK8sSJ85LXZFFn6gA

**Comment by Andarist** [comment]
`=== false` variant should start working once this PR lands: https://github.com/microsoft/TypeScript/pull/53714

**Comment by LeviticusMB** [comment]
Oh I see, it was just because of the `=== false` part ... I always write it like that because those extra parentheses annoy me.

Thanks for the tip.
