### ISSUE TITLE
Typescript error: Argument of type 'registerResponseBody' is not assignable to parameter of type 'WritableDraft<AuthenticatedUser>'

### ISSUE THREAD

**Issue by niralivasoya** [microsoft/TypeScript#55412]
### 🔎 Search Terms

typescript, type error, reactjs, nextjs, redux-toolkit action

### 🕗 Version & Regression Information

I am using the same version since I started the project. I have used redux-toolkit asyncThunk action for adding the user. I am attaching the initialStates and the used types as well. please help me to fix the issue.

This is my initial states

### 💻 Code

```ts
interface OrganizationUserState {
    users: AuthenticatedUser[];
    status: 'pending' | 'error' | 'success' | null;
    error: string | null;
}

const initialState: OrganizationUserState = {
    users: [],
    status: null,
    error: null,
};

// Invite a User to an Organization
export const inviteOrganizationUser = createAsyncThunk<registerResponseBody, registerRequestBody>(
    'organizationUserSlice/inviteOrganizationUser',
    async (user, thunkAPI) => {

        try {
            const response = await HttpService.post(`/organization/${user.organization}/invite`, user);
            return await response as registerResponseBody;
        } catch (error) {
            return thunkAPI.rejectWithValue('Error');
        }
    }
);

.addCase(inviteOrganizationUser.pending, (state) => {
                state.status = 'pending';
                state.error = null;
            })
            .addCase(inviteOrganizationUser.fulfilled, (state, action) => {
                state.status = 'success';
                state.users.push(action.payload)
                // state.users = [...state.users, action.payload];
            })
            .addCase(inviteOrganizationUser.rejected, (state, action) => {
                state.status = 'error';
                state.error = action.payload as string;
            })

export type registerResponseBody = Success<AuthenticatedUser> | Fail;


export type Success<T> = {
  success: true;
  payload: T;
};

export type Fail = {
  success: false;
  error: string;
};

```

### 🙁 Actual behavior

I am getting a typescript error when I push the new Authenticated user to the existing state.

[Argument of type 'registerResponseBody' is not assignable to parameter of type 'WritableDraft<AuthenticatedUser>'](https://stackoverflow.com/questions/76917014/redux-toolkit-typescript-error-argument-of-type-registerresponsebody-is-not-a)

### 🙂 Expected behavior

It should add to the existing User state when I push the newly registered user to it.

### Additional information about the issue

Can someone check this issue, because the registerResponse type is the same as an Authenticated user, I have added all the type in my code.

**Comment by MartinJohns** [comment]
If you believe you found a bug in TypeScript, then it's best to provide a self-contained minimal example (that's why the template asks for a playground link). If you're just struggling with the usage of Redux, then this is not the right place to ask.
