### ISSUE TITLE
export namespace compiled failed in create-react-app

### ISSUE THREAD

**Issue by yangguansen** [microsoft/TypeScript#55410]
### 🔎 Search Terms

create-react-app
export namespace
namespace nest

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions __3____ and ___5____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about __namespace and module_______
- I was unable to test this on prior versions because _it only reproduce at project instead of web playground______

### ⏯ Playground Link

https://github.com/yangguansen/typescript-bug-report

### 💻 Code

test-ts.ts
```
export namespace RuntimeStatus {

	export namespace Progress {
		export interface Quantity {
		  total?: number;
		  completed?: number;
		  unit?: string;
		}
		// export const a = '1';
	}

	export enum Severity {
		UNSPECIFIED = 0,
		NOTICE = 1,
		WARNING = 2,
		ERROR = 3,
		CRITICAL = 4,
	}
}

```

App.tsx
```
import './App.css';
import { RuntimeStatus } from './test-ts';

const a: RuntimeStatus.Progress.Quantity = {
  total: RuntimeStatus.Severity.ERROR
};
function App() {
  return (
    <div className="App">
      <header className="App-header">
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/24775952/9ae10d29-11b0-491a-89d0-c68911e33b25)

### 🙂 Expected behavior

it shouldn't has error report

### Additional information about the issue

Reproduce steps:
1. create a new project from `create-react-app@5`
2. add `test-ts.ts` file like above and import this file at a `*.tsx` file
3. then it report an error, but i think it shouldn't has error.

**Comment by yangguansen** [comment]
> That doesn't look like a TypeScript error, but an issue with your tooling. Probably due to [Babels impartial namepace support](https://babeljs.io/docs/babel-plugin-transform-typescript#impartial-namespace-support).

Thanks for reply, i already had this plugin `@babel/plugin-transform-typescript`, but it not compiled correct, and if i remove `export namespace`, it compiled correct. 

See the compiled code in error img, it had `export` inner function, which may should not inner function.

**Comment by nmain** [comment]
That plugin is maintained by the Babel team.  If there's a bug here, you'd have to file it with them.  The code works properly in the Typescript compiler.

**Comment by yangguansen** [comment]
Okay, thanks, I will report it to Babel
