### ISSUE TITLE
parseIsolatedEntityName doesn't return correct pos

### ISSUE THREAD

**Issue by NilsIrl** [microsoft/TypeScript#55415]
### 🔎 Search Terms

parseIsolatedEntityName,pos,invalid

### 🕗 Version & Regression Information

Fails on `typescript@5.1.6` and `typescript@next`.

### 💻 Code

```ts
import ts from "npm:typescript@next";
console.log(ts.parseIsolatedEntityName("  aa  ", ts.ScriptTarget.ESNext));
```

### 🙁 Actual behavior

```
$ deno run --check --allow-read code.ts
IdentifierObject {
  pos: 0,
  end: 4,
  flags: 262144,
  modifierFlagsCache: 0,
  transformFlags: 0,
  parent: undefined,
  kind: 80,
  escapedText: "aa",
  jsDoc: undefined,
  flowNode: undefined,
  symbol: undefined
}
```

The value of `pos` is 0 even though the identifier doesn't start at position 0.

### 🙂 Expected behavior

```
$ deno run --check --allow-read code.ts
IdentifierObject {
  pos: 2,
  end: 4,
  flags: 262144,
  modifierFlagsCache: 0,
  transformFlags: 0,
  parent: undefined,
  kind: 80,
  escapedText: "aa",
  jsDoc: undefined,
  flowNode: undefined,
  symbol: undefined
}
```

The value of `pos` is 2.

### Additional information about the issue

Deno is used for simplicity but same behavior would be displayed using nodejs

**Comment by RyanCavanaugh** [comment]
Trimming isn't a feature of this function. I'm honestly not even sure why it's public.
