### ISSUE TITLE
Initialize data with custom type values

### ISSUE THREAD

**Issue by Ispanki** [microsoft/TypeScript#55411]
### 🔍 Search Terms

initialize custom types, inti types, auto create type object 

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I always struggled when i had to create an initialized object for a custom type. What if instead of manually have to create every field with its default value what if it can be a one liner code

### 📃 Motivating Example

what if we have a cutom type like:
type user_data = { _id: String, name: String, age: Date, like: Number }

Currently if i want to create an object with this type and want it to have the fields with there initialized values or in a class in the constructor i always have to initialize the data fields like this:
const data: user_data = { _id: "", name: "", age: new Date(), like:0 }
now imagine if a that type has 10-30 fields and multiple custom fields as well

what if instead of manually doing that i could be created with a one liner, like this:
const data: user_data = new user_data
and it would initialize an object with each fields default value
if it has an embedded custom field i has to be imported to work
if it has an enum as field i will initialize to a 0 as pointing to the first in the enum

### 💻 Use Cases

1. What do you want to use this for? 
mainly in the classes constructor to initialize a data and of you need an object of a type with the default values.

2. What shortcomings exist with current approaches?
If you have a type that has 5-10-30 fields and some with custom types as well it can take much time to manually write default values for each field and it can take up 10-150 line of code, depending on its complexity.

3. What workarounds are you using in the meantime?
i wrote it one time and copy paste it every type, but it never was and never will be a good solution.

**Comment by MartinJohns** [comment]
This is out of scope for TypeScript. Check the viability checklist again. TypeScript will not create additional JavaScript code to initialize objects for you.

**Comment by Ispanki** [comment]
I understand now why it is out of scope. But what you think, can it be a VSCode extension? Would it be useful?
And thank you for the side note

**Comment by MartinJohns** [comment]
You surely can write a VS Code extension that generates code for you. But the TypeScript team won't do it.

**Comment by Ispanki** [comment]
Thank you, i understand why
