### ISSUE TITLE
Propagating information from type guards to parent objects

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/TypeScript#55422]
### 🔍 Search Terms

- narrowing
- parent
- propagate

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

An example is worth a 1000 words:

```ts
type Process = undefined | {
  exitCode: number | null
}

const isNull = ( value: unknown ): value is null {
  return value === null;
};

let process: Process;

if ( isNull ( process?.exitCode ) ) {
  process.exitCode
  // ^?
}
```

We are narrowing `process.exitCode`, but indirectly we should be also narrowing the parent objects, which in this case is just `process`. Basically if process.exitCode is `null` then `process` can't be `undefined`, still, TS thinks it might still be.

### 📃 Motivating Example

See above.

### 💻 Use Cases

Generally the smarter the type checker the better, and the cleaner the code you can write gets.

**Comment by MartinJohns** [comment]
Duplicate of #42384.

**Comment by fabiospampinato** [comment]
Aaaaah, missed that, thanks!

**Comment by fatcerberus** [comment]
@fabiospampinato Note that this form of narrowing (narrowing a parent object to be non-null off the result of an optional chain) actually already works when done inline:

```ts
let process: Process;

if (process?.exitCode === null) {
  process.exitCode  // ok
}
```

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgewMYQM6qgXigVwHYAmEAZgJZ4QFQA+UA3gFBRQQAepwAwgkQFxR4cAWwBGEODQE4ANtIYBfBgyQI8qYFFKoAcjOlYoACigA3AIbScEfvgDWeBAHc8UAJT9zl6Fqmz6TKDgIYBw4F08rLExsQVkAbgUEhmlgqDBEFHR+eGQ0VCTSYiN03PQAfgA6Ng5uIiiYvVd-ZhLM1Cr2Lh5oKAB6XqgEWwUGIA)

Not sure why it doesn't work with UDTGs.  I guess technically a type predicate can lie but the compiler generally assumes they don't.
