### ISSUE TITLE
Discriminated union narrowing breaks when discriminating from a wider union type

### ISSUE THREAD

**Issue by Cipscis** [microsoft/TypeScript#55425]
### 🔎 Search Terms

discriminated union
narrowing
unknown

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about bugs that aren't bugs and entries about type narrowing

This was not an issue prior to v4.0.5, where I saw discriminated unions were not narrowed in the same way (I assume they were a new feature in v4.0 but haven't been able to track this down)

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiAiBLAzgYwE6ILaIHYENgIATAVV0QHtcoBeKAbylEgC4oByAQQ4Bop8ABXSUw7XAFcsAIwjooAXygAfRs3AR2HAEJ8o04aPbJgmXAHNFAbgBQxCKgA2+dNABmE3KmBUaKOEhomDgERGQU1AAUiERY7J4A1riUAO64AJTsMRBYUCiwCCgY2HiEJOS+tnYOzq5QqNQmUCmU6Al45vG4Sam4tvZOLtANuE3SIgkQuOwASg6txAA8Jmbm-Pi4IAB8KlCe9m54JP01Q-WNwM2t7RZc5vh4s-PoSysd65s7qvsQh7gku0SyTSVX8hSCJVC5QiuEiLTaHXSUAAZMirgiLAA6FjQWh4zg8FFo+E3cyYoQiMBWKAAehpUEWAFooAB1a7IGxgwLFEJlcK+SLjSiTDJE-QTKbYjR0fHcDhioUi8mGKm0+lMqAAUXQInQnOQASKwVKYQqURJHTuD1FqPRpKteClkBl9DlYott3ujopompdIZzLZbWQAi9uBsQA

### 💻 Code

```ts
type MyDiscriminatedUnion = { type: 'A', aProp: number } | { type: 'B', bProp: string };
declare function isMyDiscriminatedUnion(item: unknown): item is MyDiscriminatedUnion;

declare const working: unknown;
declare const broken: Record<string, any> | undefined;
declare const workingAgain: Record<string, any> | undefined | unknown;

isMyDiscriminatedUnion(working) && working.type === 'A' && working.aProp; // <- Works
isMyDiscriminatedUnion(broken) && broken.type === 'A' && broken.aProp; // <- Error
isMyDiscriminatedUnion(workingAgain) && workingAgain.type === 'A' && workingAgain.aProp; // <- Works again
```

### 🙁 Actual behavior

When narrowing a variable first to a discriminated union, and then to a specific member of that discriminated union by narrowing on its discriminant property, TypeScript either will or won't perform the second part of the narrowing correctly depending on the initial type of the variable.

The variable is not narrowed correctly if it was initially given a union type such as `Record<string, any> | undefined`. However, it would be narrowed correctly if its initial type was not a union, e.g. just `Record<string, any>`, or if its initial type was widened to include `unknown` e.g. `Record<string, any> | undefined | unknown`.

### 🙂 Expected behavior

After first narrowing a variable to a discriminated union, it should then be possible to narrow it to a specific member of that union by checking its discriminant property. This should work regardless of the variable's initial type before it was narrowed to the discriminated union type.

**Comment by Cipscis** [comment]
I expect the workaround of adding `unknown` to the union works because that collapses the union down to just `unknown`.

**Comment by ahejlsberg** [comment]
Yeah, this doesn't seem right.
