### ISSUE TITLE
Inconsistent error for two different ways of filtering properties of a certain type

### ISSUE THREAD

**Issue by trajafri** [microsoft/TypeScript#55423]
### 🔎 Search Terms

Pick vs 
inconsistent conditional type 
index signature type argument 
conditional type index signature 

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about:
- empty classes
- homomorphic mapped types
- conditional types

### ⏯ Playground Link

[link](https://www.typescriptlang.org/play?ts=5.1.6#code/C4TwDgpgBAYglgG2BATgBRQezAZwDwAqANFGgHxQC8UA3gLABQUzUA2gNJRwB2UAogA9gKAIYBjYHgDWEEJgBmUYlBzCeAczIBdAFxKOWqBCERuAExykoAfiic93CADdUAbkYBfVoOHjJMuUVlVRQNbXcGRgB6KKUAd0woOJEQS2BEswh5HmhspFQoTF4RXkwAIwArCAlGUEhYRGQUAEZCEnIqUjgxKTaG-PQsXD7yMgi66HgBgCYRimp6JhYOLl4ppoxsfGVyXX12Q2Nkc0s0G33DB2c3Twja8GgAJQgcAFckQiMTE9o2bhEALYQPQhDR7UHcdRQAA+UDKmEwCAgJSgHnmtEYLCgKAADHoAGqoODyEB4daoVrBNSQshjKAxIwoLAoTEsFoEokksmNVCzKmhGl0hncRKoZmeRj3eqE0JcghfY4WX6sf5AkHU9TgjWo9EEVxAA)

### 💻 Code

```ts
type FilterProps<T, P> = {
    [K in Extract<keyof T, string>]: T[K] extends P ? K : never;
}[Extract<keyof T, string>];

// Two ways to define filter on an object
type Filter1<T, P> = Pick<T, FilterProps<T, P>>;
type Filter2<T, P> = {
    [K in FilterProps<T, P>]: T[K] extends P ? T[K] : never;
};

type Result<T extends { [name: string]: string | boolean }> = {
    r0: Verify<Filter1<T, string>>; // error
    r1: Verify<Filter2<T, string>>; // no error
}

type Verify<T extends { [name: string]: string }> = T;
```

### 🙁 Actual behavior

The `Filter1` argument to `Verify` is a type error, but `Filter2` argument to `Verify` is not a type error.

### 🙂 Expected behavior

Both should either be correct or a type error. In this case, I believe both should result in a type error.

**Comment by RyanCavanaugh** [comment]
Filter2's construction defies the logic that allows Filter1 to work. There are any number of ways you can indirect things, all of which at some point would defeat whatever logic is in place to recognize more straightforward constructs.

I'm not sure why you think these should both be errors? In either case, in a concrete instantiation, only string properties are present.

**Comment by trajafri** [comment]
> Filter2's construction defies the logic that allows Filter1 to work.

Could you expand on/rephrase what you mean by this, i.e., why does the extra `T[K] extends P ? T[K] : never` as compared to what we see in the definition of `Pick` equate to defying logic here? I am interpreting "defying logic" as a bad thing, in which case I feel like I should avoid using `Filter2` in my programs.

I ask because I have a program that works/typechecks with something equivalent to `Filter2` but not `Filter1`. I don't have a solid explanation for why `Filter2` works because to me, both implementation of Filter are doing the same thing. Is there a simple explanation for what `Filter2` is doing different here that let's the `r1` property above typecheck?

Thank you 😸

**Comment by RyanCavanaugh** [comment]
An analogy might be helpful

Scenario 1: You get a box of bricks and metal cans from Alice, and want to give it to Eve who can only accept metal cans. You know Dave, whose job is to remove everything from a box that isn't metal, so you give the box to Eve with a note on it that says "Take this box to Dave before you start". Eve accepts because she can tell that post-Dave, the box will only contain metal cans, since that's Dave's job.

Scenario 2: You get a box of bricks and metal cans from Alice, and want to give it to Eve who can only accept metal cans. You take it to Bob, whose job is to remove the bricks, and then take it to Eve. Eve says "You got this box from Alice? She sometimes gives out bricks; I can't accept this box because it might have bricks in it". You say "No no, this box has gone via Bob, who is sure to have removed the bricks" but Eve is not smart enough to recognize that this implies there are only cans left in the box.

Could Eve be made smarter? Almost certainly. Will there still be constructions which Eve isn't able to recognize without becoming a general-purpose propositional logic solver? Also yes.

**Comment by trajafri** [comment]
Thank you!

My initial understanding was that the "extra assertion" (the `T[K] extends P ? T[K] : never` in `Filter2`) doesn't do anything on top of what `Pick<T, FilterProps<T, P>>` does, but I was wrong.

`Pick`'s job is to "filter properties". Me telling it to filter properties that also happen to have the type `string` doesn't mean that Eve will be able to understand that the filtered properties will have the type `string`.

If go one step further and say "only filter properties of type `string`", then Eve does understand that the filtered properties will all be of type `string`.

**Comment by RyanCavanaugh** [comment]
Yep, exactly

**Comment by trajafri** [comment]
> I'm not sure why you think these should both be errors?

I concluded they both should be errors because I misunderstood how conditional types work with union types. I started with the type below:

```ts
(string | boolean) extends string ? true : false
```

The above type is always `false`, so I concluded that the following in `Filter2` should always be `never` when `T[K]` is `(string | boolean)`:

```ts
T[K] extends P ? T[K] : never
```

But, I learned about [distributive conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) after digging around in the checker. If I understood things correctly, then the type above actually expands to:


```ts
(string extends string ? string : never) | (number extends string ? string : never)
```

**Comment by fatcerberus** [comment]
@trajafri Distributivity only applies when the LHS is a lone, naked type parameter (`T extends …`) which is why it’s easily disabled just by wrapping the type parameter in a tuple type (`[T] extends […]`).

The bricks and cans analogy is the only thing relevant in this case.

**Comment by trajafri** [comment]
@fatcerberus interesting, thank you for sharing that.

If it’s not distributive conditionals, then what allows us to narrow down to a member of the union type? I have been assuming that `T[K]` is `string | boolean` in the `r1` property above, but maybe I am wrong about that too 🤔
