### ISSUE TITLE
Overloads error in global scope but not in class methods

### ISSUE THREAD

**Issue by ScrapsBits** [microsoft/TypeScript#55430]
### 🔎 Search Terms

overload, overload signature, overload error, overload global scope, overload class

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about overloads
Tested TypeScript versions Nightly (_v5.3.0-dev.20230818_), 5.1, 4.9, 4.8 and 4.7.

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99&ts=5.1.6#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwBYCGKAJgDbBQAUaBppARgWgNYBccllKBAtsOwGcYUTCgDmASjgBeAHxwAbhEzEJE9l1784QkeKlzFy4gG4AUKEixEqDNlyES5KjTqMWGzX0HDRYgDQ6SFDc3jq++jLySipqGqHaun6BAsEJPnqSUUYqJnAA9PlwAKJQUNACKWlacJgCcCjAChRwqMTACKLAxBbg0PDI6Fg4+ERkFNS0DExsHF6JEQFBIVoA-Bl+BtHGcQVFAIL0EM1wxBDA9SgQ8BTlULUIcAAGqSthSeJPHFcoALQQYGG3FIEjMAB85ulwpktjlVODIVoNuIqm8FjDsjFVHAAN5mOBwKDAGBpOCuaYsAB05HEMDwcAAPHAAEz4glwVbfJHQzbsLHZcnuZjzUHsuDxbkfJavKFS9RwgVTIXzVEJUEAXzMvSsA1sQNGTgozMmbhmnlli1hWN282RWUMWPMln6NiG9gN4ygxsFZsR70WqsllsxO3ltp5KOWFoxDuMeUKJTKFUDfFqlyaLTaHS6PWd1kGdhGjk93qVvs40c2IdicAhFaDmRTwHWEft21i8oTh2OwFO50u1zgt2gD2eMobfi+XBw-0B9looLr4bl1fhS8rkfH-pj7exeIJRJJITJZapNLEdMZLLZBM5y8tfOMitNLBFN-FXO3ySjE-0j5Uz4UsKCRNhqWpoKQBACPUAAqFzwPucBgEg9CkJgaAes4JpAeav5tnCNobvhjpsshqHoZhEw+h4frot+W50ZEsYdhKX6btUbHEXGeyJnclQ-qmdQNBm9xZp0jQ9ASZFoRhxZYdRsz1pxTYtiuzGqJ2BxHCcZwXA0g7DvcmCPC8HGMWIU4-LOQILmy654VaOx2bRdpNnajk1ohB7EqSCnUsAtL0kyrJineRHyvyhgKW+YqseZbmthFT5RaewFaKBbKapqZgQVBsHwcyuKkShMmUV62FCrhnEeRpcXuau5hSSVFFyUaFXlvejYCeZNWEXhCVqbu8ZFAAIv2+k3EmUCBPQSDwAxabCc0okkNmEnFeRsljM4pYvopnVVupUj2cp3WqcGR3qM5Sk9auoq1i5rYDRdu5SF5hI+cefnnpewXvmFDn-sQgHKmq751U93XuUDIMzCq3X3VlZhAA

### 💻 Code

```ts
export function handler(callback: ((name: string) => void)): (name: string) => void;
export function handler(callback: ((name: string, surname: string) => void)): (name: string, surname: string) => void; // Errors, surname is never undefined
export function handler(callback: ((name: string, surname?: string) => void)): // Above does not error if `surname: string` (non-optional)
| ((name: string) => void)
| ((name: string, surname: string) => void) {
  return callback.length < 2
    ? (name: string): void => callback(name)
    : (name: string, surname: string): void => callback(name, surname)
}

export function handler2(callback: ((name: string) => void)): (name: string) => void;
export function handler2(callback: ((name: string, surname: string) => void)): (name: string, surname: string) => void; // Errors, surname is never undefined
export function handler2(callback: ((name: string) => void) | ((name: string, surname?: string) => void)): // Above does not error if `surname: string` (non-optional)
| ((name: string) => void)
| ((name: string, surname: string) => void) {
  return callback.length < 2
    ? (name: string): void => callback(name)
    : (name: string, surname: string): void => callback(name, surname)
}

class Test {
  public handler(callback: ((name: string) => void)): (name: string) => void;
  public handler(callback: ((name: string, surname: string) => void)): (name: string, surname: string) => void; // Errors, surname is never undefined
  public handler(callback: ((name: string, surname?: string) => void)): // Above does not error if `surname: string` (non-optional)
  | ((name: string) => void)
  | ((name: string, surname: string) => void) {
    return callback.length < 2
    ? (name: string): void => callback(name)
    : (name: string, surname: string): void => callback(name, surname)
  }
}

class Test2 {
  public handler2(callback: ((name: string) => void)): (name: string) => void;
  public handler2(callback: ((name: string, surname: string) => void)): (name: string, surname: string) => void; // Does not error, but surname is never undefined
  public handler2(callback: ((name: string) => void) | ((name: string, surname?: string) => void)):
  | ((name: string) => void)
  | ((name: string, surname: string) => void) {
    return callback.length < 2
    ? (name: string): void => callback(name)
    : (name: string, surname: string): void => callback(name, surname)
  }
}
```

### 🙁 Actual behavior

Overloads within classes do not consistently error when their global-scope equivalents would error.

In the provided example, the second overload never matches any implementation-overload. However, this does not error in class Test2, while all other implementations do error.

### 🙂 Expected behavior

Overloads within classes consistently error when their global-scope equivalents would error.

In the provided example, Test2 should display an error on the second overload.

### Additional information about the issue

The order of overload declarations has been found not to be relevant.

Versions 4.8 and older seem to throw multiple errors on the same issue, according to Playground.

**Comment by ScrapsBits** [comment]
On an unrelated note, if the overloads are correct (surname is not optional), the length check does not filter out possible overloads.
![image](https://github.com/microsoft/TypeScript/assets/43343406/15b0eaba-b791-4ab9-bba2-05e686673527)

**Comment by MartinJohns** [comment]
Class methods and functions are not treated the same, unless you disable `strictFunctionTypes`. See https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant.

**Comment by ScrapsBits** [comment]
I understand class methods and functions are not treated the same. However, that should not apply to overloads.

When using overloads, the overload declaration is a blueprint of what the implementation function can handle. In a way, it always limits what the implementation function can receive. The argument declaration of Test2's `handler2` function should match the overload descriptions. In this case, it should receive a function with 1 argument, or a function with 2 arguments. 

Looking at both class implementations, I do not see how the method implementation arguments differ from each other. In both cases, they accept a function with 1 argument, or a function with 2 arguments. Yet, when specifically adding a declaration for a function with 1 argument, the class accepts the overload that requires at least 2 arguments.

**Comment by RyanCavanaugh** [comment]
> I understand class methods and functions are not treated the same. However, that should not apply to overloads.

The overload validation is done in terms of assignability to the implementation signature, and since the implementation signature is a method, it gets method assignability rules (i.e. parameter bivariance). It sounds like you want to trade one consistency for another, which in general isn't something that has a net positive effect.

I can look at the example again if it's simplified; this example seems overcomplex relative to the defect it's trying to describe

**Comment by ScrapsBits** [comment]
I must've overlooked that. Intuitively it'd make more sense to have overloads be the defining factor, where the implemenation signature must adhere to that; but if bivariance says that a function with two arguments, where the second argument is optional, then the second argument can be omitted. That's why, when adding a function with 1 argument, it accepts it.
