### ISSUE TITLE
Renamed field takes on documentation from other field with the same name

### ISSUE THREAD

**Issue by alexschrod** [microsoft/TypeScript#55434]
### 🔎 Search Terms

"renamed field docs"
"renamed field documentation"

### 🕗 Version & Regression Information

- This changed between versions 4.5 and 4.6

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvAUFLUD0AqPTbKPKAFQAsBLAOwHMoqBnKAQygCNWAnI7PHH0ZMAQjwBcnBABsIrGkPyFiJctXrC2nVgC8hJQcWZidkjjLkKAvunQAzAK40AxsCpwaUOhGDw4ACgBKST80IW4fB25PJwATCDtaCFi2FnkQdBt0Zw8mYDRhE0ljHigrZC8fPyCAbmzcuFkAOniOBzp-Eu5AmqA

### 💻 Code

```ts
type Foo = {
    /**
     * Thing is a bar
     */
    isBar: boolean
    /**
     * Thing is a baz
     */
    isBaz: boolean
}

function getFoo(): Foo {
    return undefined as any
}

const { isBaz: isBar } = getFoo();
console.debug(isBar);
```

### 🙁 Actual behavior

If you inspect the tooltip/documentation for the `isBar` that is the renamed `isBaz` from the call to `getFoo()`, it takes on the docs for the actual `isBar` rather than `isBaz` (or nothing) (screenshot is from the playground with 5.1.6):
![image](https://github.com/microsoft/TypeScript/assets/767490/71b1160e-dae1-4eb2-8057-796d0264b931)

While that would be the correct documentation if it were in fact, the actual `isBar`, this one is actually `isBaz` and should have `isBaz`'s docs.

### 🙂 Expected behavior

Despite me renaming `isBaz` to another field that also exists, it should either still show the docs for `isBaz` for the renamed variable, or at least nothing.

### Additional information about the issue

I say this changed between 4.5 and 4.6, but that's mainly because in 4.5 and earlier versions, the renamed version shows no documentation at all. 4.6 and later still show no documentation if you rename the field to something not present in the original type (screenshot is from the playground with 5.1.6):
![image](https://github.com/microsoft/TypeScript/assets/767490/47a5e712-9871-46a8-9333-c1f09d9de3b3)

Personally, I'd prefer it if the renamed version still showed the docs from the original, but *nothing* is still better than *wrong*.

**Comment by fatcerberus** [comment]
This is definitely wrong, because `isBar` does not, at any point, refer to the property by that name in `Foo`.  Not even indirectly.

**Comment by DanielRosenwasser** [comment]
Thank you @a-tarasyuk!
