### ISSUE TITLE
Request : Consistent Lexical Classification for TSX closing tag

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5544]
For the following: 
```
<div>foo</div>
```
We get: 

```
< Operator
div Identifier
> Operator
foo Identifier
< Operator
/div> Identifier
```

Would be great if we got: 

```
< Operator
div Identifier
> Operator
foo Identifier
< Operator
/ Operator
div Identifier
> Operator 
```

:rose:

# More

For self closing
```
<img/>
```
its okay 

```
< Operator
img Identifier
/ Operator
> Operator
```

**Comment by DanielRosenwasser** [comment]
> ```
< Operator
div Identifier
> Operator
foo Identifier
< Operator
/div> Identifier
```

Are you sure you don't get 

```
< Operator
div Identifier
> Operator
foo Identifier
< Operator
/div> StringLiteral (**which is really just a regular expression literal**)
```

**Comment by basarat** [comment]
> Are you sure you don't get

Nope. `Identifier`

![image](https://cloud.githubusercontent.com/assets/874898/11010440/f583f150-8532-11e5-9125-07e3ebac692d.png)


But not urgent anymore, I need to figure out a better way to do the whole of TSX :rose:

**Comment by mhegazy** [comment]
this should be fixed in latest.
