### ISSUE TITLE
Check for import nonexistent module

### ISSUE THREAD

**Issue by zyf0330** [microsoft/TypeScript#55457]
### 🔍 Search Terms

check import nonexistent module

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Now according to https://github.com/microsoft/TypeScript/issues/20767, we should write `import {} from "./nonexistenmodule"` to import nonexistent module. 
But, unused module will be removed by IDE or some other import optimize tools. So this code will be removed.

### 📃 Motivating Example

I don't know.

### 💻 Use Cases

1. import module to run it without use symbols of this module
2. ensure to check nonexistent module error

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/20576#issuecomment-355403887

**Comment by RyanCavanaugh** [comment]
Duplicate #40450
