### ISSUE TITLE
"undefined" passed for the "context.metadata" field in a decorator metadata 

### ISSUE THREAD

**Issue by mushketyk** [microsoft/TypeScript#55453]
### 🔎 Search Terms

"decorator metadata" in both closed and opened issues.

### 🕗 Version & Regression Information

- `context.metadata` is undefined in a decorator function

### 💻 Code

Code mostly copies the example from the [TypeScript 5.2 release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2-beta/#decorator-metadata).

```ts
function setMetadata(_target: any, context: any) {
    console.log(`@setMetadata - ${context.name}`)
    context.metadata[context.name] = true;
}

class SomeClass {
    @setMetadata
    foo = 123;

    @setMetadata
    accessor bar = "hello!";

    @setMetadata
    baz() { }
}

const ourMetadata = SomeClass[Symbol.metadata];

console.log(JSON.stringify(ourMetadata));
```

### 🙁 Actual behavior

Script fails when trying to set a value on the `context.metadata` field.

```
@setMetadata - bar
/Users/ivanmushketyk/Development/courses-creation/pluralsight-typescript-decorators/metadata.js:48
    context.metadata[context.name] = true;
                                   ^

TypeError: Cannot set properties of undefined (setting 'bar')
    at setMetadata (/Users/ivanmushketyk/Development/courses-creation/pluralsight-typescript-decorators/metadata.js:48:36)
    at __esDecorate (/Users/ivanmushketyk/Development/courses-creation/pluralsight-typescript-decorators/metadata.js:12:40)
    at /Users/ivanmushketyk/Development/courses-creation/pluralsight-typescript-decorators/metadata.js:78:13
    at /Users/ivanmushketyk/Development/courses-creation/pluralsight-typescript-decorators/metadata.js:82:11
    at Object.<anonymous> (/Users/ivanmushketyk/Development/courses-creation/pluralsight-typescript-decorators/metadata.js:84:2)
```

### 🙂 Expected behavior

It should not fail, and metadata should be displayed using the `console.log` statement

### Additional information about the issue

Compiler version:

```
tsc --version
Version 5.2.1-rc
```

**Comment by a-tarasyuk** [comment]
Are you utilizing a polyfill to define `Symbol.metadata`?

> Because this feature is still fresh, most runtimes will not support it natively. To use it, you will need a polyfill for Symbol.metadata.

**Comment by mushketyk** [comment]
@a-tarasyuk Good catch! Thank you!
