### ISSUE TITLE
After the generic interface uses Omit, it is introduced into the new component property interface, and then inherited in the component. When the component is used, the property is required

### ISSUE THREAD

**Issue by Midas-Li** [microsoft/TypeScript#55458]
### 🔎 Search Terms

Omit

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions _4.9.5_____ and __5.1.6_____
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```typescript
interface I1<T> {
  a: number;
  b: T;
}

interface I2<T> extends Omit<I1<T>, 'a'> {
  c: string;
}

const Test1 = (props: I2<boolean>) => {
  return (
    <>test </>
  );
};

const Test2 = () => {
  return (
    <div>
      <Test1 b c = "test str"/>
    </div>
  );
};
``` 

### 🙁 Actual behavior

`<Test1 b c = "test str"/>` <<-In this sentence, the warning is found:Element Test1 doesn't have required attribute a.

### 🙂 Expected behavior

I don't think this warning can happen

**Comment by MartinJohns** [comment]
Please fill out the issue template completely. You omitted the playground link.

The actual behaviour does not report an error. [Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChTgA7GJKTdJOASQEYAeAFQD44BvUuHBQAuOJQCuIAEa0A3ALhTRHeQF9yVGnQbMATJx5IAHjUoATAM5wA8iGAw2rAwBoCKfD36C0oizChUAOZq5GgQlH5wHEh+LHAAvHAAFGA4YBaiTPpSEBAANqiUXACUCZ4KRDDiUJTJCoJsXDSRbAD0XArFavKkYRHw0X66Ccml8eWCldW1SfVwbGbAAG4dgmvzgzBxUnBoIwBEzfB+UPvtc22LK53dpEA)

**Comment by Midas-Li** [comment]
> Please fill out the issue template completely. You omitted the playground link.
> 
> The actual behaviour does not report an error. [Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChTgA7GJKTdJOASQEYAeAFQD44BvUuHBQAuOJQCuIAEa0A3ALhTRHeQF9yVGnQbMATJx5IAHjUoATAM5wA8iGAw2rAwBoCKfD36C0oizChUAOZq5GgQlH5wHEh+LHAAvHAAFGA4YBaiTPpSEBAANqiUXACUCZ4KRDDiUJTJCoJsXDSRbAD0XArFavKkYRHw0X66Ccml8eWCldW1SfVwbGbAAG4dgmvzgzBxUnBoIwBEzfB+UPvtc22LK53dpEA)

Thanks for the tip, but strangely, I can't see the error I raised when using ts in the link environment you provided, but there is one on my side of the project. I don't know why. What should I do? Here's what I get using the npm list directive in my current project:
client@1.0.0 K:\WebPrjs\Honey\client
+-- @babel/core@7.22.5
+-- @babel/runtime@7.22.5
+-- @emotion/react@11.11.1
+-- @emotion/styled@11.11.0
+-- @pmmmwh/react-refresh-webpack-plugin@0.5.10
+-- @tarojs/cli@3.6.7
+-- @tarojs/components@3.6.7
+-- @tarojs/helper@3.6.7
+-- @tarojs/plugin-framework-react@3.6.7
+-- @tarojs/plugin-html@3.6.8
+-- @tarojs/plugin-platform-alipay@3.6.7
+-- @tarojs/plugin-platform-h5@3.6.7
+-- @tarojs/plugin-platform-jd@3.6.7
+-- @tarojs/plugin-platform-qq@3.6.7
+-- @tarojs/plugin-platform-swan@3.6.7
+-- @tarojs/plugin-platform-tt@3.6.7
+-- @tarojs/plugin-platform-weapp@3.6.7
+-- @tarojs/react@3.6.7
+-- @tarojs/runtime@3.6.7
+-- @tarojs/shared@3.6.7
+-- @tarojs/taro-loader@3.6.7
+-- @tarojs/taro@3.6.7
+-- @tarojs/webpack5-runner@3.6.7
+-- @testing-library/react@14.0.0
+-- @types/chai@4.3.5
+-- @types/mocha@10.0.1
+-- @types/node@18.16.18
+-- @types/react@18.2.12
+-- @types/testing-library__react@10.2.0
+-- @types/webpack-env@1.18.1
+-- @typescript-eslint/eslint-plugin@5.59.11
+-- @typescript-eslint/parser@5.59.11
+-- babel-preset-taro@3.6.7
+-- chai@4.3.7
+-- classnames@2.3.2
+-- eslint-config-taro@3.6.7
+-- eslint-plugin-import@2.27.5
+-- eslint-plugin-react-hooks@4.6.0
+-- eslint-plugin-react@7.32.2
+-- eslint@8.42.0
+-- lodash@4.17.15
+-- marked@5.1.2
+-- mocha-typescript@1.1.17
+-- mocha@10.2.0
+-- postcss@8.4.24
+-- react-dom@18.2.0
+-- react-refresh@0.11.0
+-- react@18.2.0
+-- stylelint@9.3.0
+-- taro-ui@3.1.0-beta.5
+-- ts-node@10.9.1
+-- typescript@5.1.6
`-- webpack@5.86.0

**Comment by Midas-Li** [comment]
After I set up a pure react+ts project again, the issues disappeared.
