### ISSUE TITLE
Having to restart TS server every time I build a package in a workspace

### ISSUE THREAD

**Issue by gittymcgit** [microsoft/TypeScript#55450]
Type: <b>Bug</b>

I have a monorepo setup, using workspaces. 
Whenever I rebuild one of my packages, all files in another workspace can no longer resolve types for it. That is until I do cmd + shift + P -> TS restart

VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin arm64 21.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 9, 9|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 971cdb5c-5eac-4e31-85ae-d33323f572d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
postcss|css|1.0.9
vscode-eslint|dba|2.4.2
gitlens|eam|14.2.1
prettier-vscode|esb|10.1.0
vscode-jest-runner|fir|0.4.66
angular-console|nrw|18.6.0
vscode-stylelint|sty|1.2.4
vscode-mdx|uni|1.4.0
vscode-css-variables|vun|2.6.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by sheetalkamat** [comment]
@gittymcgit the repro you shared doesnt work for me since when i open index.tsx, the import is not resolved.
Do i need any special setup apart form running `pnpm install`
Do you have any repro that doesnt involve pnpm. 

![image](https://github.com/microsoft/TypeScript/assets/8052792/7f524343-6cd2-4a0f-80a2-e657ebcd3962)

Thanks

**Comment by gittymcgit** [comment]
@sheetalkamat Hi! Did you build all workspaces? pnpm build from the root of the repo

**Comment by sheetalkamat** [comment]
I dont see the issue after the `build`
![Upsell](https://github.com/microsoft/TypeScript/assets/8052792/3d777674-f78c-4b1b-a084-87ff4d5c2688)

**Comment by gallak-openfin** [comment]
I am also facing this issue with a monorepo. Our structure is as follows:
packages/
-- pkg1
-- pkg2
src/
-- file1
-- file2

Whenever I change something in either pkg, or in src and rebuild, all my types become `any` until I restart the TS server.

**Comment by 66beta** [comment]
Same issue, have to `restart TS server` every 15~30 mins

Windows 10 64bit lastest & VSCode lastest

**Comment by gittymcgit** [comment]
yep, definitely still happening. Facing it every day

**Comment by s0** [comment]
I face this all the time with `@microsoft/rush` repos... perhaps you need a clean step that clears packages for it to happen? Or maybe it depends on which editors are open. Here's a project of mine where this happens all the time: https://github.com/synesthesia-project/synesthesia

**Comment by sheetalkamat** [comment]
Please provide concrete steps on what you are doing and how to repro along with tsserver log to be able to diagnose this.

Thanks

**Comment by gallak-openfin** [comment]
FWIW my team found the root cause for this, with TSServer Log set to "normal" - in the output log we saw this:
```
[10:16:50.811] Non TS file size exceeded limit (21224809). Largest files: c:/User/........../out/shared-worker.js:1924538
```

We realized our tsconfig was not excluding our compiled JS folders. We added our `out/` and `tmp/` folders to the `exclude` tsconfig key using this glob:
```
  exclude: [ "./**/*/out", "./**/*/tmp"]
```
The problem was resolved.

**Comment by sebastien-f** [comment]
@sheetalkamat here is a repo that reproduce the issue : https://github.com/sebastien-f/vs-code-ts-server-needs-restart
Here is the [tsserver.log](https://github.com/microsoft/TypeScript/files/14118249/tsserver.log)

Steps to follow : 

1. clone repo
2. in project root : `npm i`
3. in packages/package1 : `npm run build`
4. open VS Code
5. open file `packages/package2/src/index.ts`, everything is fine (as expected)
6. from npm scripts in VS Code, run build for package1
7. package1 is underlined in red (which is the issue, and unexpected)
8. restart TS Server
9. everything is fine again

Also a video here (had to make 2 parts because of the recording software) : 

1. first part with the commands in PS : https://www.youtube.com/watch?v=pvTf-c3b5PE
2. second part in VS Code : https://www.youtube.com/watch?v=OII7kYvr7b8

In the second video I forgot to restart the TS Server at the end, but it solves the issue.

**Comment by sheetalkamat** [comment]
@sebastien-f thank you for the repro and the log, i am able to see the issue. Its to do with use watching `node_modules` and not `node_modules/package1` for changes to resolution.

**Comment by rivaros** [comment]
Is this bug still not fixed? A year has passed - having same issue in VSCode 1.87.2

**Comment by rivaros** [comment]
@sheetalkamat  do you have any info is is issue with typescript or VSCode
Have created a tiny demo project showning the issue with README

https://github.com/rivaros/demo-ts-server-failure

**Comment by sebastien-f** [comment]
> p.s.: @sebastien-f have you got it resolved? can see you are using workspaces, in my case it is a link tool https://github.com/privatenumber/link but the issue still is the same and is probably related to cleaning (rimraf, rf inside linked package)

I'm not working on that side project at the moment, but had a workaround with a keyboard shortcut (ctrl t+s)  to reload TS.

**Comment by Chivano** [comment]
Having the same issue in a PNPM monorepo, VSCode 1.87.2. Any time i build one of the internal packages i need to restart the TS server.

**Comment by mastershadow** [comment]
> Having the same issue in a PNPM monorepo, VSCode 1.87.2. Any time i build one of the internal packages i need to restart the TS server.

Same here.
