### ISSUE TITLE
Failure of generic type inference

### ISSUE THREAD

**Issue by Midas-Li** [microsoft/TypeScript#55460]
### 🔎 Search Terms

generic 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.1.6 and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
export interface IProps<T> {
  onClose: (data: T) => void;
}

interface NewProps extends IProps<string> {
  newProp: string;
}

const TestComponent = ({onClose}: NewProps) => {
  onClose(888);  //no report type error!
};
 
```

### 🙁 Actual behavior

The sentence with the comment above, typing the number into onClose, is not reporting a type error.

### 🙂 Expected behavior

I expect T to perform type inference correctly

### Additional information about the issue

I hope this will do the type inference correctly as well, strangely enough the above code if you select the onClose word and look at the type information in the ide, the result is correct, T can be deduced. But in webstorm using code completion->basic, the result of filling in parameters is wrong, T is not deduced.

**Comment by MartinJohns** [comment]
Please fill out the issue template completely. You omitted the playground link.

The actual behaviour does report a type error. [Playground link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQAUoIwBnAHgBUA+OAbwCg44IkBhAGwjOAC44ACgAmmGJgFUAlHAC8dAG4QEwgNyMAvo0bJUGHHgBywAO7FSZOKFRJhloiXIUyMKMgDmdJiySnzYARc3JHd1LUZsNhc4KmAXdggAW0hfFDkhejYuHmANAWMzRzIZeQZmVg5uXkEADjqpVRYAeiakCDgoYEhYOBgATzA8NBIoAEJNdSA)

**Comment by fatcerberus** [comment]
> `//no report type error!`

I'm confused, because this *is* a type error: 
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQAUoIwBnAHgBUA+OAbwCg44IkBhAGwjOAC44ACgAmmGJgFUAlHAC8dAG4QEwgNyMAvo0bJUGHHgBywAO7FSZOKFRJhloiXIUyMKMgDmdJiySnzYARc3JHd1LUZsNhc4KmAXdggAW0hfFDkhejYuHmANAWMzRzIZeQZmVg5uXkEADjqpVRYAeiakCDgoYEhYOBgATzA8NBIoAEJNdSA

> Argument of type 'number' is not assignable to parameter of type 'string'.

**Comment by Midas-Li** [comment]
Thanks for the tip, but oddly enough, I can't see the error I made when using ts in the context of the links you provided, but it did happen in my project. I don't know why. What should I do? Here's what I get when I use the npm list directive in the current project:
client@1.0.0 K:\WebPrjs\Honey\client
+-- @babel/core@7.22.5
+-- @babel/runtime@7.22.5
+-- @emotion/react@11.11.1
+-- @emotion/styled@11.11.0
+-- @pmmmwh/react-refresh-webpack-plugin@0.5.10
+-- @tarojs/cli@3.6.7
+-- @tarojs/components@3.6.7
+-- @tarojs/helper@3.6.7
+-- @tarojs/plugin-framework-react@3.6.7
+-- @tarojs/plugin-html@3.6.8
+-- @tarojs/plugin-platform-alipay@3.6.7
+-- @tarojs/plugin-platform-h5@3.6.7
+-- @tarojs/plugin-platform-jd@3.6.7
+-- @tarojs/plugin-platform-qq@3.6.7
+-- @tarojs/plugin-platform-swan@3.6.7
+-- @tarojs/plugin-platform-tt@3.6.7
+-- @tarojs/plugin-platform-weapp@3.6.7
+-- @tarojs/react@3.6.7
+-- @tarojs/runtime@3.6.7
+-- @tarojs/shared@3.6.7
+-- @tarojs/taro-loader@3.6.7
+-- @tarojs/taro@3.6.7
+-- @tarojs/webpack5-runner@3.6.7
+-- @testing-library/react@14.0.0
+-- @types/chai@4.3.5
+-- @types/mocha@10.0.1
+-- @types/node@18.16.18
+-- @types/react@18.2.12
+-- @types/testing-library__react@10.2.0
+-- @types/webpack-env@1.18.1
+-- @typescript-eslint/eslint-plugin@5.59.11
+-- @typescript-eslint/parser@5.59.11
+-- babel-preset-taro@3.6.7
+-- chai@4.3.7
+-- classnames@2.3.2
+-- eslint-config-taro@3.6.7
+-- eslint-plugin-import@2.27.5
+-- eslint-plugin-react-hooks@4.6.0
+-- eslint-plugin-react@7.32.2
+-- eslint@8.42.0
+-- lodash@4.17.15
+-- marked@5.1.2
+-- mocha-typescript@1.1.17
+-- mocha@10.2.0
+-- postcss@8.4.24
+-- react-dom@18.2.0
+-- react-refresh@0.11.0
+-- react@18.2.0
+-- stylelint@9.3.0
+-- taro-ui@3.1.0-beta.5
+-- ts-node@10.9.1
+-- typescript@5.1.6
`-- webpack@5.86.0

Sorry, two questions in a row are the same result. In the future, I will carefully test on that link before I send a report.
