### ISSUE TITLE
Services.ts with ~8000 lines of code

### ISSUE THREAD

**Issue by Anjmao** [Microsoft/TypeScript#5547]
I just wonder why https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts file is not splitted into other files and currently have 7993 lines of code Is where is any pros of doing it?. Mum always teached me to each service to it's own file :)

**Comment by RyanCavanaugh** [comment]
Just wait until you see checker.ts :wink:

A root cause is that these components wrap everything in a giant closure, and it's not possible to split a function expression across multiple files.
