### ISSUE TITLE
Expando member write widens a writeonly property

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#55477]
### 🔎 Search Terms

expando write only accessor setter javascript jsdoc

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230822&filetype=js#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoHiB7AOxlAA9QBeUAbwF8BuPAeQCMArLZAOgBMsAZvCJYACrAIAHLLGgBPABRkANKADk0LDDWqaOUKGAAqIxEkBDWOYC2tIhmusZdUOdBHg+0JCzRQC8wBKWjocOkC8Mm5NUmo1NUMwYQA3cwAbeF5QAHcETRwgA

### 💻 Code

```ts
// @strict: true

const x = {};

Object.defineProperty(x, 'test', {
  /** @param {number} a */
  set (a) {}
})

x.test = '' // invalid write
```

### 🙁 Actual behavior

The invalid write is accepted and the emitted declaration for this property includes the type of this invalid write:
```ts
declare namespace x {
    let test: string | number;
}
```

### 🙂 Expected behavior

I expected for this invalid write to be reported as an error

### Additional information about the issue

Expanded properties are somewhat special and unsafe already so perhaps that's just a design limitation. 

```ts
// source
const x = {};

x.one = 42;

if (false) {
  x.other = "";
}

// emitted declaration
declare namespace x {
    let one: number;
    let other: string;
}
```

**Comment by andrewbranch** [comment]
Both assignments/definitions are expando declarations, and this is how expandos are intended to work. A simpler example that has the same behavior:

```ts
const x = {};
x.test = 4;
x.test = '';
```

While your examples show cases where it’s quite clear which assignments happen in which order, the motivation behind the feature is stuff like

```ts
if (process.env.NODE_ENV === 'development') {
  exports.foo = 'foo'
} else {
  exports.foo = 4
}
```

We just do a best effort to capture the widest type based on all the declarations we see.

Pinging @sandersn to validate my understanding here

**Comment by andrewbranch** [comment]
Honestly more working as intended than design limitation, because I don’t know what kind of consistent rule we would implement to decide when you want the first declaration to be the only declaration vs. when you want to get the union type, and the union type seems to be more desirable for common patterns around `module.exports`.
