### ISSUE TITLE
Wrong type inference if object property is used as accumulator in recursive conditional type

### ISSUE THREAD

**Issue by vaderkos** [microsoft/TypeScript#55473]
### 🔎 Search Terms

TS2589, any, infer, accum, recursive

### 🕗 Version & Regression Information

- This is wrong type inference
- Possibly silent error

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?ts=5.1.6#code/C4TwDgpgBAShBuEBOBnCBBAPAKClAysElBAB7AQB2AJilCkQJaUDmANLlOgMbcnlVa9JqygBeKAHJJ2AHziCRfhRp0ABgBIA3swBmyKAGEAFgEMkAX216DcBhbWcA-LATI0WO8DZRNWk+ZWWjzcDrKcAFxcvNjYoJCuiKgQAEI4eITEZCpCDEjM7JwAshDAyoJ0WlCmvACuALZReQVQFgpVNdwNUdKtcgqZ5aq+1pT6xAGWo+Ou9o54LnBJaGlePh11jSP+ZlNaJcAA2pKdDZIAug6t4XhRB7Hx0JkAjAAMr5wSkgD6zwBMAGYACwAVgAbAB2AAcAE5foDQZDYfDgeDoXD-qikRiEWjkZjEeiUYT8bjscS8TiseiZNgAPR0qAAewA1vTGWoYVCIWCQUCAX9nt8uTy+QKhSLefzBcLuVLxbLRdKJXKxTLJWqVUqFRrlYr5TK1FA4uBoEgIChagAbYDoBRLdwYTAvd7yWLsqAAFSQtUoNVMFDoAagINeUG4uxQHs5qr1up1sYT2vViZl2lMlBAVxNCXNlptKXtbmSaRdrzdsQZUAAMkzWXQrYwWdBGGV6owWMYygAjaDcJmUSgQbgUahQYBMqAAIk9+D+INhUU9pqgzAYGeAjADjAHq7oZG4FpQjEQVpAUGoEAgYGqNCgYCZKGP3bPq7GzFbEAAdFOoN3amUuimIwVp0MeVpUMAZ5AA

### 💻 Code

```ts
type ReverseA<
  Str extends string,
  Acc extends string = ''
> = Str extends `${infer Char}${infer Rest}`
  ? ReverseA<Rest, `${Char}${Acc}`>
  : Acc

type ReverseB<
  Str extends string,
  Met extends { accum: string } = { accum: '' }
> = Str extends `${infer Char}${infer Rest}`
  ? ReverseB<Rest, { accum: `${Char}${Met['accum']}` }>
  : Met

type Str100
  = '_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789'

// ok
// `987654321_987654321_987654321_987654321_987654321_987654321_987654321_987654321_987654321_987654321_` 
type resultA = ReverseA<Str100> 


// Trunacates at 50 chars and appends `${any}`
// `987654321_987654321_987654321_987654321_987654321_${any}` 
type resultB = ReverseB<Str100> 


// Looks like it might be connected to "TS2589: Type instantiation is excessively deep and possibly infinite." but fails silently

### 🙁 Actual behavior

Appends `${any}` to accum thus providing no information about existing problem.

### 🙂 Expected behavior

accum property inside object works same as if it is standalone generic.

resultB is equal to resultA.

### Additional information about the issue

Looks like it might be connected to "TS2589: Type instantiation is excessively deep and possibly infinite." but fails silently and instead append any.

**Comment by RyanCavanaugh** [comment]
Code that hits these edge cases is *well* past what these features were designed for; please use other constructs to do whatever it is needs to be done.

**Comment by fatcerberus** [comment]
@RyanCavanaugh If I’m reading the OP correctly then the implied bug is that the type fails silently (inserting an `any` into the result) rather than producing the edge-case error(s).
