### ISSUE TITLE
Module augmentation causes import to be tree-shaken (is removed from output)

### ISSUE THREAD

**Issue by matthew-dean** [microsoft/TypeScript#55481]
### 🔎 Search Terms

"module augmentation" tree-shaking

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because: I'm using the satisfies keyword

### ⏯ Playground Link

https://github.com/jesscss/jess/blob/dev-freeze/packages/css-parser/src/cssParser.ts#L2

### 💻 Code
```ts
// chevrotain.d.ts
declare module 'chevrotain' {
  interface CstParser {
    // things that augment this type
  }
}


// cssParser.ts
import { CstParser, EOF } from 'chevrotain'

class CssParser extends CstParser {
 // class implementation
}

// outputs
import { EOF } from 'chevrotain'
```
### 🙁 Actual behavior

Augmenting the module seems to remove it from being considered "used" when compiling.

### 🙂 Expected behavior

Augmenting the module should have no effect on tree-shaking imports.

### Additional information about the issue

I thought maybe this was an expected behavior, and I'd just never encountered it before? But I could find nothing in TypeScript documentation about this.

Also, interestingly, the import is not tree-shaken from the exported `.d.ts` file, only the `.js` file. 🤷‍♂️

**Comment by jakebailey** [comment]
You didn't mention that you were using a patched version of TypeScript via `ts-patch`. If you disable `ts-patch`, then things work as expected.

Before:

```
$ (cd packages/css-parser; pnpm compile)
$ grep 'CstParser' packages/css-parser/lib/cssParser.js
export class CssParser extends CstParser {
```

After removing `ts-patch`, cleaning the repo, and reinstalling:

```
$ git diff package.json
diff --git a/package.json b/package.json
index 93f9a2e..85e0d09 100644
--- a/package.json
+++ b/package.json
@@ -47,8 +46,7 @@
     "ci": "pnpm run -r ci && pnpm run lint",
     "lint:fix": "eslint --fix '**/*.{js,ts}'",
     "lint": "eslint '**/*.{js,ts}'",
-    "preinstall": "npx only-allow pnpm",
-    "prepare": "ts-patch install -s"
+    "preinstall": "npx only-allow pnpm"
   },
   "repository": {
     "type": "git",
$ (cd packages/css-parser; pnpm compile)
$ grep 'CstParser' packages/css-parser/lib/cssParser.js
import { CstParser, EOF } from 'chevrotain';
export class CssParser extends CstParser {
```
