### ISSUE TITLE
Iterable gets resolved incorrectly if value is passed directly and element has method

### ISSUE THREAD

**Issue by InSyncWithFoo** [microsoft/TypeScript#55489]
### 🔎 Search Terms

"iterable", "literal", "method"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried:
- - [4.8.4](https://www.typescriptlang.org/play?ts=4.8.4#code/PTAEEEBdIJwSwEYFdJwPYDsBcoAW0AHAZyxCMgEMBjAazQDcBTGAMwBs0B3AOirQFtgFYAHYArADYAHCIDMUgCwBYAFCQAngUagAcpgDKsOBgDmASUjMKCNowA8AFQB8oALyhVoUA9CMAHpYYACZEoOTwpqAA-KAYjEwwoDg+-oEhoBZWNvYUGOouMT44cQkA3KqqQYxUbBQw2ixIGFSomKBBaPoCjJC4xiaOTgAU9BRsSIw4ehiGEeaWMNa2gwCUyeUqqnwY5KBobqAA3qAsaGhDK0cAvqBXG5Wd3b39QwDko+OMrysbHV38PT6piGAG13q8ALo-B7-QEvEFoKG-R4A57AkHHU7nS6HG5XJFAA)
- - [4.9.5](https://www.typescriptlang.org/play?ts=4.9.5#code/PTAEEEBdIJwSwEYFdJwPYDsBcoAW0AHAZyxCMgEMBjAazQDcBTGAMwBs0B3AOirQFtgFYAHYArADYAHCIDMUgCwBYAFCQAngUagAcpgDKsOBgDmASUjMKCNowA8AFQB8oALyhVoUA9CMAHpYYACZEoOTwpqAA-KAYjEwwoDg+-oEhoBZWNvYUGOouMT44cQkA3KqqQYxUbBQw2ixIGFSomKBBaPoCjJC4xiaOTgAU9BRsSIw4ehiGEeaWMNa2gwCUyeUqqnwY5KBobqAA3qAsaGhDK0cAvqBXG5Wd3b39QwDko+OMrysbHV38PT6piGAG13q8ALo-B7-QEvEFoKG-R4A57AkHHU7nS6HG5XJFAA)
- - [5.0.4](https://www.typescriptlang.org/play?ts=5.0.4#code/PTAEEEBdIJwSwEYFdJwPYDsBcoAW0AHAZyxCMgEMBjAazQDcBTGAMwBs0B3AOirQFtgFYAHYArADYAHCIDMUgCwBYAFCQAngUagAcpgDKsOBgDmASUjMKCNowA8AFQB8oALyhVoUA9CMAHpYYACZEoOTwpqAA-KAYjEwwoDg+-oEhoBZWNvYUGOouMT44cQkA3KqqQYxUbBQw2ixIGFSomKBBaPoCjJC4xiaOTgAU9BRsSIw4ehiGEeaWMNa2gwCUyeUqqnwY5KBobqAA3qAsaGhDK0cAvqBXG5Wd3b39QwDko+OMrysbHV38PT6piGAG13q8ALo-B7-QEvEFoKG-R4A57AkHHU7nS6HG5XJFAA)
- - [5.1.6](https://www.typescriptlang.org/play?ts=5.1.6#code/PTAEEEBdIJwSwEYFdJwPYDsBcoAW0AHAZyxCMgEMBjAazQDcBTGAMwBs0B3AOirQFtgFYAHYArADYAHCIDMUgCwBYAFCQAngUagAcpgDKsOBgDmASUjMKCNowA8AFQB8oALyhVoUA9CMAHpYYACZEoOTwpqAA-KAYjEwwoDg+-oEhoBZWNvYUGOouMT44cQkA3KqqQYxUbBQw2ixIGFSomKBBaPoCjJC4xiaOTgAU9BRsSIw4ehiGEeaWMNa2gwCUyeUqqnwY5KBobqAA3qAsaGhDK0cAvqBXG5Wd3b39QwDko+OMrysbHV38PT6piGAG13q8ALo-B7-QEvEFoKG-R4A57AkHHU7nS6HG5XJFAA)
- - [5.2.0-beta](https://www.typescriptlang.org/play?ts=5.2.0-beta#code/PTAEEEBdIJwSwEYFdJwPYDsBcoAW0AHAZyxCMgEMBjAazQDcBTGAMwBs0B3AOirQFtgFYAHYArADYAHCIDMUgCwBYAFCQAngUagAcpgDKsOBgDmASUjMKCNowA8AFQB8oALyhVoUA9CMAHpYYACZEoOTwpqAA-KAYjEwwoDg+-oEhoBZWNvYUGOouMT44cQkA3KqqQYxUbBQw2ixIGFSomKBBaPoCjJC4xiaOTgAU9BRsSIw4ehiGEeaWMNa2gwCUyeUqqnwY5KBobqAA3qAsaGhDK0cAvqBXG5Wd3b39QwDko+OMrysbHV38PT6piGAG13q8ALo-B7-QEvEFoKG-R4A57AkHHU7nS6HG5XJFAA)
- - [5.2.1-rc](https://www.typescriptlang.org/play?ts=5.2.1-rc#code/PTAEEEBdIJwSwEYFdJwPYDsBcoAW0AHAZyxCMgEMBjAazQDcBTGAMwBs0B3AOirQFtgFYAHYArADYAHCIDMUgCwBYAFCQAngUagAcpgDKsOBgDmASUjMKCNowA8AFQB8oALyhVoUA9CMAHpYYACZEoOTwpqAA-KAYjEwwoDg+-oEhoBZWNvYUGOouMT44cQkA3KqqQYxUbBQw2ixIGFSomKBBaPoCjJC4xiaOTgAU9BRsSIw4ehiGEeaWMNa2gwCUyeUqqnwY5KBobqAA3qAsaGhDK0cAvqBXG5Wd3b39QwDko+OMrysbHV38PT6piGAG13q8ALo-B7-QEvEFoKG-R4A57AkHHU7nS6HG5XJFAA)

### 💻 Code

```ts
// Attribution: https://stackoverflow.com/a/75687384
type NonStringIterable<T> = 
  T extends string ? never : T extends Iterable<any> ? T : never;

declare function doSomething<T>(value: NonStringIterable<T>): T;

const o = { foo() {} };

doSomething('value');
doSomething(['v']);
doSomething([o]);
doSomething([{ foo() {} }]);
```

### 🙁 Actual behavior

```ts
const o = { foo() {} };

doSomething('value');
//          ~~~~~~~
// Argument of type 'string' is not assignable to parameter of type 'never'. (2345)
// (correct)

doSomething(['v']); // Fine (correct)
doSomething([o]);   // Also fine (correct)

doSomething([{ foo() {} }]);
//          ~~~~~~~~~~~~~~
// Argument of type '{ foo(): void; }[]' is not assignable to parameter of type 'never'. (2345)
// (incorrect)
```

`doSomething([o])` works correctly, yet directly passing the same object as `o` causes an error. This error happens regardless of the method being deeply nested or not. Interestingly, empty object (`{}`) and arrow function (`{ foo: () => {} }`) [are fine](https://www.typescriptlang.org/play?ts=5.1.6#code/PTAEEEBdIJwSwEYFdJwPYDsBcoAW0AHAZyxCMgEMBjAazQDcBTGAMwBs0B3AOirQFtgFYAHYArADYAHCIDMUgCwBYAFCQAngUagAcpgDKsOBgDmASUjMKCNowA8AFQB8oALyhVoUA9CMAHpYYACZEoOTwpqAA-KAYjEwwoDg+-oEhoBZWNvYUGOouMT44cQkA3KqqQYxUbBQw2ixIGFSomKBBaPoCjJC4xiaOTgAU9BRsSIw4ehiGEeaWMNa2gwCUyeUqqnwY5KBobqAA3qAsaGhDK0cAvqBXG5Wd3b39QwDko+OMrysbHV38PT6piGAG13q8ALo-B7-QEvEFoKG-R4A57AkGeI6YrynNA4C5uFyHK4AGmxoAQdXxHwmOHC-UurhcNO0AGpQK8OPV+K8ySovF5KQAvHAY-kCrzHXH4xlEm5XckQzEKlRImFPIEmUGY45VRgENjqHDHOLkRhBY2gVG4NBBAnE26OlVqlR-DXwnVhCgAgDqcF6lrqi3UJFAIKlZ3t8ohTtUUKAA). The same goes with [a separately declared method](https://www.typescriptlang.org/play?ts=5.1.6#code/PTAEEEBdIJwSwEYFdJwPYDsBcoAW0AHAZyxCMgEMBjAazQDcBTGAMwBs0B3AOirQFtgFYAHYArADYAHCIDMUgCwBYAFCQAngUagAcpgDKsOBgDmASUjMKCNowA8AFQB8oALyhVoUA9CMAHpYYACZEoOTwpqAA-KAYjEwwoDg+-oEhoBZWNvYUGOouMT44cQkA3KqqQYxUbBQw2ixIGFSomKBBaPoCjJC4xiaOTgAU9BRsSIw4ehiGEeaWMNa2gwCUyeUqqo3NrRigLGhoQyugAN4AvhUqfBjkoGhuZ-uHoOcblZ3dvf1DAOSj40YvxWGw6XX4PT6piGAG1-r8ALogj7gyE-GFoJGgz4Q77QmGnZ5HE4XV5YlFfKEmWGEg4Pc5YoA).

### 🙂 Expected behavior

Only the first example should cause an error.

**Comment by andrewbranch** [comment]
This is one example of the kind of problem tracked at https://github.com/microsoft/TypeScript/issues/47599.
