### ISSUE TITLE
Quick info displays incorrect type in discriminated union type

### ISSUE THREAD

**Issue by kettanaito** [microsoft/TypeScript#55495]
### 🔎 Search Terms

quick info, union, discriminated union, wrong info.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UDeAoKUB2BDAthAXFAOQBWA9gBYZFQA+xA1lsBDfQM7ABOAlhgOZQAZMgC+KUcKgAKNMjnY8hTrwFSk49AG0GEEMu59+AXUJYMICXXnpFBYuSpE57MngAKXMmEIAjMmQANhDmEnL0qOi2uPZETCzOUVDxEADKkADGPABmPBkA0nqESFAZZACuGMCEGOU4vhBcUJrNKACUKCjSJXaEROYgALR2RAA0UFiEAIzjvoTc5RDjrkpQUwBMAMzNbVDszDzsuRDssJ0A9OdQABJkAG6NUPePAEQrEJ7eLwB0UAAqFGgAEdynkGFA+NkyHssCBTjxgERTv4giEMChLlAAO4UHjBcZ8KDZLAZYAExGnF4DF4yYmBQKnSoAE0eWCgODIXGgYC5OEO7B4DwhGBZAA89jx+NhgOUuW1vl0ejE+o5qMs3B8vD4oAtoKJdvtgIdjqcYJ0UEA

### 💻 Code

```ts
type X = {
  name: 'john' | 'kate' | string & {}
} & (
  {
  name: string & {}
  [key: string]: any
} | {
  name: 'john'
  someProp: boolean
}
  | {
    name: 'kate'
    kateSpecificKey: { count: number }
  }
)

({ name: 'any-name', a: 1, b: true, some: 123 }) satisfies X

// Hover over "someProp". The quick info says it's boolean
// while, in fact, it's "any" (falls under a more premissive index signature).
({ name: 'john', someProp: true }) satisfies X



```

### 🙁 Actual behavior

The quick info prop for `someProp` displays `boolean` as if the object matches the discriminated union. It doesn't, as you can observe from the actual type validation—`someProp` is still `any`, matching a more permissive index signature. 

### 🙂 Expected behavior

The quick info must display `someProp` correctly—as `any`. 

### Additional information about the issue

This is a purely visual issue. The type validation is performed correctly.

**Comment by Andarist** [comment]
This one is correct. `someProp: true` has a `boolean` type. The purpose of `satisfies` is to **keep** the expression's type (and influence it with some contextual type information). As long as the expression's type is assignable to the `satisfies` operand that's all good.

There is a bug there though but it's a different one:
```ts
({ name: 'john', someProp: 'wrong!' }) satisfies X
```

If we hover over `someProp` here we might see this: 
> (property) someProp: boolean
but we really should see:
> (property) someProp: string

**Comment by kettanaito** [comment]
Thanks for the clarification, @Andarist! Also, if this is a beginner-friendly issue, you may navigate me around and I could be able to contribute 🙏

**Comment by Andarist** [comment]
If you are up for it we could try to schedule a pairing session.

**Comment by kettanaito** [comment]
I would love to. Let's sync in Twitter/Discord and have this issue fixed.
