### ISSUE TITLE
Define types for common properties of class in general

### ISSUE THREAD

**Issue by kevit-yuvraj-kanakiya** [microsoft/TypeScript#55491]
### 🔍 Search Terms

common types, class property, productivity

### ⭐ Suggestion

Lately, while working on class structures, I encountered a scenario where numerous properties shared the same data types. It struck me that it would be quite beneficial if we could establish common types for these recurring properties. Consider a situation where we have a class named "User" encompassing several properties – perhaps around 6 to 12 of them are strings, and 3 to 5 are numbers. From a technical standpoint, this might not cause any issues. However, when we consider efficiency and productivity, we realize that having to repeatedly define types for these similar properties becomes redundant and mildly hampers our workflow.

I envision a feature that enables the definition of generalized types for such commonly occurring properties. While it might seem ambitious, the advantages in terms of productivity and code cleanliness could be significant. Your consideration of this concept would be greatly appreciated. Thank you.

### 📃 Motivating Example

```
type.all(string).exclude(age);    // I would like to see something like this to define a common type for properties
export class Student{
  name;
  birthDate;
  email;
  phoneNumber;
  educationDetails: {
    instituteName;
    education;
    percentage;
  };
  gender;
  address;
  summary;
  age: number
}
```

In the example mentioned earlier, I've constructed a class named "Student" that holds various properties related to students. If you take a closer look, you'll notice that all these properties are of the string type, except for one property called `age`,  which is of number type. What I'm hoping for is a feature akin to the hypothetical representation I provided for the Student class `type.all(string).exclude(age)` that would allow us to efficiently specify that all properties should be of the string type, except for the "age" property, which can be of a different number type.

I trust that my intended meaning comes across. Thank you for your understanding.

### 💻 Use Cases

1. What do you want to use this for?
Ans. I would like to use it to improve my productivity and save some time.

2. What shortcomings exist with current approaches?
Ans. Technically not at all.

3. What workarounds are you using in the meantime?
Ans. I am using it which currently you are providing.

**Comment by andrewbranch** [comment]
The suggested syntax is a valid JavaScript expression, so we can’t use it for types. Moreover, I think declaring the type of class fields is not a problem that really needs a solution besides the one that already exists.

**Comment by kevit-yuvraj-kanakiya** [comment]
Got it. Apologies for any inconvenience.
