### ISSUE TITLE
[typeBaselines] Poor message from harness when a compiler test causes errors in lib.d.ts

### ISSUE THREAD

**Issue by JsonFreeman** [Microsoft/TypeScript#555]
In the typeBaselines branch, we get the following error when running the tests:

compiler tests for tests/cases/conformance/types/members/duplicateStringIndexers.ts Correct errors for tests/cases/conformanc
e/types/members/duplicateStringIndexers.ts:
     AssertionError: total number of errors: expected 52 to equal 54
      at Object.getErrorBaseline (C:\Work\XTeamUpdate\src\typescript\public\built\local\run.js:34387:20)

The problem is that the test has errors, but the compiler actually reports the errors in lib.d.ts. This is arguably a bug in the compiler, but the harness should also be more explicit about this.

**Comment by mhegazy** [comment]
This should be fixed now.
