### ISSUE TITLE
Auto-imports / renames of `.tsx` files use extension `.jsx`, leading to Next.js module resolution error

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript#55502]
### 🔎 Search Terms

auto-import, auto import, jsx, file extension, vs code,  `typescript.preferences.importModuleSpecifierEnding`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about JSX and React

### ⏯ Playground Link

none yet (requires auto-import of other files, which I don't believe works on the Playground)

### 💻 Code

`tsconfig.json`

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "target": "es2022",
    "module": "Node16",
    "moduleResolution": "Node16",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "preserve",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "strict": true,
    "incremental": true,
    "noUncheckedIndexedAccess": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "**/*.cjs",
    "**/*.mjs",
  ],
  "exclude": ["node_modules"]
}
```

### 🙁 Actual behavior

Auto-importing `Form` from `./Form.tsx` (or renaming of `.tsx` files which have already been imported) causes this line below to show up in my editor when I'm using `Node16` (I would like to be able to keep fully-specified ESM imports):

```js
import Form from './Form.jsx';
```

This causes Next.js to crash because it cannot resolve this file:

```
- error ./app/profile/page.tsx:1:0
Module not found: Can't resolve './Form.jsx'
> 1 | import Form from './Form.jsx';
  2 | 
```

Arguably, Next.js should also support the `.jsx` extension by adding the webpack `extensionAlias` config to their configuration: https://github.com/vercel/next.js/pull/44177/files

However, users may want to keep extensions always as `.js` for `.tsx` files (which TypeScript supports) for other reasons:

- stylistic reasons
- for other environments / bundlers which do not support `.jsx` -> `.tsx` resolving
- to avoid Git churn when changing a file extension back and forth between `.ts` and `.tsx` (less common)

### 🙂 Expected behavior

Auto-importing `Form` from `./Form.tsx` should create this import:

```js
import Form from './Form.js';
```

Potentially based on a user configuration setting

### Additional information about the issue

I tried to configure this using [the VS Code setting `"typescript.preferences.importModuleSpecifierEnding": "js"`](https://code.visualstudio.com/docs/getstarted/settings#:~:text=component/index%60.%0A%20%20//%20%20%2D-,js%3A%20Do%20not%20shorten%20path%20endings%3B%20include%20the%20%60.js%60%20or%20%60.ts%60%20extension.,-%22typescript.preferences.importModuleSpecifierEnding), but this does not help - it still uses `.jsx` extensions for `.tsx` files

cc @andrewbranch, in case this happens to be in your wheelhouse

**Comment by andrewbranch** [comment]
Why does Next.js need to do that? Surely it’s just processing the input files with a transpiler that it can feed options to programmatically. It shouldn’t care what’s in the tsconfig for emit purposes, right?

**Comment by karlhorky** [comment]
Not 100% sure about the details behind it, seems like it's been there for a few years:

- https://github.com/vercel/next.js/pull/13510

**Comment by andrewbranch** [comment]
I think this is one or more Next.js bugs. Although, `allowImportingTsExtensions` and writing `.tsx` imports might be the nicest workaround.

**Comment by karlhorky** [comment]
> I think this is one or more Next.js bugs

Ok, then I'll try over there as well:

- https://github.com/vercel/next.js/issues/54550

Maybe the `extensionAlias` webpack configuration from https://github.com/vercel/next.js/pull/44177 should be extended with `.jsx` support

**Comment by karlhorky** [comment]
Should we leave this open until there's a response / resolution on the Next.js side?

**Comment by andrewbranch** [comment]
I think the current behavior is pretty unambiguously correct on both the TypeScript and VS Code front here. I’m happy to consult on the issue you opened in Next.js if the maintainers have questions. I would like to know why they need (or think they need) to force `"jsx": "preserve"`. That just seems wrong to me. If you’re not using tsc for emit, your emit-related compiler options are supposed to reflect what’s happening in the build system you’re using to replace tsc, so that checking (and editor features, as in this issue) can understand what’s going on. And the .tsx files are not producing .jsx files; they clearly are applying a React JSX transform, so the setting should be `react-jsx`.
