### ISSUE TITLE
Same references from different (but not found) modules

### ISSUE THREAD

**Issue by jkillian** [microsoft/TypeScript#5551]
If you have code like the following:

``` typescript
import { resolve as resolveUrl } from 'url';
import { resolve } from 'path';
```

`getDocumentHighlights` marks both references of `resolve` as the same if the modules 'url' and 'path' can't be found. However, if 'url' and 'path' can be found, it correctly differentiates between the two.

I know this is somewhat of an edge-case, but is this intended behavior? Or is it a bug?

**Comment by mhegazy** [comment]
they both given the same symbol (`unknownSymbol`), the find all references code will think they are because they also have the same name. we could exclude the unknownSymbol from this logic. but would not say it is a priority.

**Comment by jakebailey** [comment]
Thanks for checking; I bisected and this was fixed in https://github.com/microsoft/TypeScript/commit/e8c3d548eb66c020b02cfa135b492f9480ef639c, but it's not clear to me that this actually has a test and it'd be nice to have one via a fourslash baseline or something.
