### ISSUE TITLE
Cannot destructure properties of a resource obtained using the 'using' keyword

### ISSUE THREAD

**Issue by electricmonk** [microsoft/TypeScript#55527]
### 🔎 Search Terms

using destructure

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because this is a new feature in 5.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQEqoM5xAJwlQAoBKRAbwChFbF90Clq7XFg44AuRAIgCMAhvl4AaGm1oBtAMoBPALb84AGwB0AExjYADnGyoAujzKIAvAD5KAX3GtrVB1RZ0Q2GGGT1zKdFlwERGQA3BK0EAi4KqhqKnDIxPhqHHCkoU7OYYhuHl4U7JyI1j5omDh4hCRpWRFgUTFxCSnV1kA

### 💻 Code

```ts
function getResource() {
    return {
        foo: "bar",
        [Symbol.dispose]: () => {},
    }
}

{
    using { foo } = getResource();
    console.log(foo);
}```


### 🙁 Actual behavior

> Error: 'using' declarations may not have binding patterns.(1492)


### 🙂 Expected behavior

Should be able to destructure a variable defined using the `using` keyword

### Additional information about the issue

_No response_

**Comment by MartinJohns** [comment]
This is working as intended. JavaScript does not support combining destructuring and using declarations. See [This comment and the linked issues](https://github.com/tc39/proposal-explicit-resource-management/issues/78#issuecomment-1135152072).

**Comment by electricmonk** [comment]
Fair enough.
It could be argued, though, that this is just another piece of sugar TSC can provide us with.
From the dev experience perspective, this behavior violate the principle of least surprise and I'm sure that many many developers will be surprised to learn about it.

**Comment by MartinJohns** [comment]
> that this is just another piece of sugar TSC can provide us with.

It's not. That would require additional code to be emitted that goes beyond downleveling support for older runtimes. A clear no-go for TypeScript.

**Comment by guillaumebrunerie** [comment]
I guess one issue is that's it's unclear whether it's the result of `getResource` that should be disposed, or the `foo` variable. Technically, the statement only introduces a variable called `foo`, so it would make more sense to dispose `foo`, but it is not disposable.

**Comment by electricmonk** [comment]
To me it's very clear that the containing object is the disposable but maybe I'm in minority.
