### ISSUE TITLE
Typescript issue with includes in tsconfig

### ISSUE THREAD

**Issue by alainbelez** [microsoft/TypeScript#55525]
### 🔎 Search Terms

tsconfig includes

### 🕗 Version & Regression Information

Version: 5.2.2/ 5.1.6

### 💻 Code

![image](https://github.com/microsoft/TypeScript/assets/6648110/68d6a5b8-b813-4d29-a5ec-de505e70f847)

### 🙁 Actual behavior

I created a new file that is included in the includes in tsconfig, but it keeps on nagging me that the file 

`File '/home/path/to/file/resources/js/views/TestNewView.vue' is not listed within the file list of project '/home/path/to/file/tsconfig.app.json'. Projects must list all files or use an 'include' pattern`

### 🙂 Expected behavior

there shouldn't be any error since the pattern is included already

### Additional information about the issue

 restarting vscode seems to fix the issue, but will occur again for other new files

**Comment by andrewbranch** [comment]
Does this happen for `.ts` files or just for `.vue` files?

**Comment by alainbelez** [comment]
it seems to only happen with `.vue` files only

**Comment by sheetalkamat** [comment]
Can you please share tsserver verbose log for the same. 

You can upload logs by following these steps:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart vscode or vscode insiders
3. Reproduce the problem
4. In vscode or vscode insiders, run the `TypeScript: Open TS Server log` command
5. This should open a large file called `tsserver.log`. Please share this file.

**Comment by alainbelez** [comment]
here you go. thanks

[tsserver.log](https://github.com/microsoft/TypeScript/files/12564461/tsserver.log)
