### ISSUE TITLE
No add private field in declaration

### ISSUE THREAD

**Issue by regseb** [microsoft/TypeScript#55520]
### 🔎 Search Terms

private, field, declaratio, d.ts

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _private_

### ⏯ Playground Link

https://www.typescriptlang.org/play?&filetype=ts#code/MYGwhgzhAEBiD29oG8BQ0PQMQCMwCcAuaCAF3wEsA7Ac2gF5oAiAIQEEAlJgblXU1xgAXsTKVaDZuwBaPPpmg0ApqWgBHAK4APABQBKFNHwqN+KtFIALChAB0g-NADUF63cFDu0AL6pfQA

### 💻 Code

```ts
class Foo {
    #bar: string = "BAR";

    #baz: string = "BAZ";

    get qux() { return this.#bar + this.#baz; }
}
```

### 🙁 Actual behavior

In the generated _.D.TS_, a private field `#private` is in the class.

```TypeScript
declare class Foo {
    #private;
    get qux(): string;
}
```

### 🙂 Expected behavior

In the generated _.D.TS_, the private fields aren't in the class.

```TypeScript
declare class Foo {
    get qux(): string;
}
```

**Comment by fatcerberus** [comment]
That’s intentional, because without the private field in the definition, the class type becomes structural (private properties make it nominal)
