### ISSUE TITLE
Assigning a type to a type variable changes behavior

### ISSUE THREAD

**Issue by ddurschlag** [microsoft/TypeScript#55523]
### 🔎 Search Terms

"type inference" "type variable" "inference" "unknown" "indirection" "extends" "conditional type" "type alias" "type alias preservation"

### 🕗 Version & Regression Information

- This is a bad type evaluation
- This changed between versions 4.1.5 and 4.2.3
- This seems like it could be related to [type alias preservation](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html#smarter-type-alias-preservation)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAKg9gdQE4EMxQLxQHYFcC2ARhEgNxQWVQD01UAInBAM45zBT4rDAlQC0-KL2a8AJlADuAS2AALKKKTTsAcwA0OXABttmlNgl4iJAFChIUZGkhIAPNbCQxAPkxQA3gF9ytKAGVgJDg1bRBObl4kVkEoJAgwYLFcAGMWKVkFbygDCQAFYPxpZgg7ADc4aVdNQlwObHYM+SgAeUIAKwgU4E0AbQBdTWwIMpJNOCQtXQA6c3BoAElDaXju6RD3R1s7eEcXUlNTPwBRAA9Ibu517AEhFTEVruAVVSgACghp1WmoJYfV54bMrMH5bEg7RCoMAuACUEQA1ukGlAHgAzVEkCDYNKzCzQeiPboAYTkXXhVCwYPsuyhbgoEFOvEMrCpdhUGMmYNcUAA-FYoc4oAAuHAjEgHPG-ZYAklkihYP6EwE3Kj0xlYsQsgXg9l8LluPlc4Wi0ZkQ5+ABKEBQ2lkIBFBJlpJS5PizDg2lGrGAcFgkLQAHJWGUbbhoB8vj9jMQkDDyIqnXLijltJIUCBWLhsPCGpJsEc6DA5Mm06wGhx5NAUigSlAVFAACzTACM0wArFBahxk5WoNXa-WbdooKbmNdWAsA6NhMoIBIx9joE2AEzTADM7xUKW0uAeahw0lUcmAYRhQA

### 💻 Code

```ts
type ToWrap = number;       // Does not matter -- tested with string, null, and number
type Wrapper<Wrapped> = {}; // Strongly matters -- reproduces with {} and Promise<void>, but not with Object, [], never, or null.
type Indirection = Wrapper<ToWrap>;

// Expectation -- indirecting (e.g. Indirection vs. Wrapper<ToWrap>) makes no difference.
type DirectCheck    = Wrapper<ToWrap>   extends Wrapper<infer Wrapped> ? Wrapped : never;
type IndirectCheck  = Indirection       extends Wrapper<infer Wrapped> ? Wrapped : never;

// Reality: DirectCheck resolves to ToWrap's value (e.g. number); IndirectCheck is always unknown
// This was not the case in 4.1.5 but is the case in all versions I've tried since 4.2.3 (including nightly)
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
// Reality: DirectCheck resolves to ToWrap's value (e.g. number); IndirectCheck is always unknown
// This was not the case in 4.1.5 but is the case in all versions I've tried since 4.2.3 (including nightly)

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAKg9gdQE4EMxQLxQHYFcC2ARhEgNxQWVQD01UAInBAM45zBT4rDAlQC0-KL2a8AJlADuAS2AALKKKTTsAcwA0OXABttmlNgl4iJAFChIUZGkhIAPNbCQxAPkxQA3gF9ytKAGVgJDg1bRBObl4kVkEoJAgwYLFcAGMWKVkFbygDCQAFYPxpZgg7ADc4aVdNQlwObHYM+SgAeUIAKwgU4E0AbQBdTWwIMpJNOCQtXQA6c3BoAElDaXju6RD3R1s7eEcXUlNTPwBRAA9Ibu517AEhFTEVruAVVSgACghp1WmoJYfV54bMrMH5bEg7RCoMAuACUEQA1ukGlAHgAzVEkCDYNKzCzQeiPboAYTkXXhVCwYPsuyhbgoEFOvEMrCpdhUGMmYNcUAA-FYoc4oAAuHAjEgHPG-ZYAklkihYP6EwE3Kj0xlYsQsgXg9l8LluPlc4Wi0ZkQ5+ABKEBQ2lkIBFBJlpJS5PizDg2lGrGAcFgkLQAHJWGUbbhoB8vj9jMQkDDyIqnXLijltJIUCBWLhsPCGpJsEc6DA5Mm06wGhx5NAUigSlAVFAACzTACM0wArFBahxk5WoNXa-WbdooKbmNdWAsA6NhMoIBIx9joE2AEzTADM7xUKW0uAeahw0lUcmAYRhQA)
      

### 🙁 Actual behavior

DirectCheck and IndirectCheck are different types, despite having the same definition (modulo one layer of indirection).

### 🙂 Expected behavior

DirectCheck and IndirectCheck should be the same type. This could be the wrapped type (as it was in older versions) or unknown, or anything else really. It just needs to be the same.

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/48070

**Comment by ddurschlag** [comment]
> Duplicate of #48070

Agreed, closing as dupe.
