### ISSUE TITLE
Please support the 'option' type - a shorthand alias for `null | undefined`

### ISSUE THREAD

**Issue by Silentdoer** [microsoft/TypeScript#55530]
### 🔍 Search Terms

Please support the option type, when null strict checking is enabled, let foo: string|null|undefined can be abbreviated as let foo: string|option

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

make option as null|undefined

### 📃 Motivating Example

let foo: string|null|undefined can be abbreviated as let foo: string|option

### 💻 Use Cases

1. What do you want to use this for?
simple code
3. What shortcomings exist with current approaches?
none
5. What workarounds are you using in the meantime?
none

**Comment by guillaumebrunerie** [comment]
You can define it yourself by putting
```typescript
type option = null | undefined;
```
in a `.d.ts` file in your project.

But I would suggest instead that you avoid such types, just pick either null or undefined and stick with it.

**Comment by DanielRosenwasser** [comment]
Agreed with @guillaumebrunerie, and also we have other rationales on the issue tracker for why we're not adding a built-in type aliases like `type Optional<T> = T | null | undefined`
