### ISSUE TITLE
Cannot use conditional type to strongly type `this` type hint for callback

### ISSUE THREAD

**Issue by mqudsi** [microsoft/TypeScript#55533]
### 🔎 Search Terms

"conditional this type"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types, infer, 

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/GYVwdgxgLglg9mABAWwIYAcA8AVANAVVwGFEBeRcAEwFNgYxrKA+ACigAsYBnALkQEEAToNQBPHE1yIIqADayARqggBrPm069EJagA8o1MJS4Ujteo0QB+AcLETEfAHIInIeagWzqmIpMQAbnIg1Hx4iPQ0unxgIMgK1IJSqHaiYQDaALoAlGRMiISIHNxCAOZWfETZfPhZiADeAFCILdIIXFCIgtRc7lA1deRZANzNrRDtnRNgBvpkRZpl1jbFXKOtiMBwgogs3p0w8wAMwxGImAvcAHTeYKUcpwDUjzC5TRsb0x1F86vpMJl1h8Wl9OiB5jJ5EpVFdIbIWNNZlApMiIijNNkgcDur1ZFB-pl5iAsYgAL5jFrdKAgQRIHF9Uak0ZAA

### 💻 Code

```ts
function map<T,U,C = undefined>(this: Array<T>, callback: (this: C extends undefined ? Array<T> : NonNullable<C>, value: T, index: number, array: T[]) => U, thisArg?: C): U[] {
    const result: U[] = [];
    const context = thisArg ?? this;
    for (let i = 0; i < this.length; ++i) {
        const t = this[i];
        const u = callback.call(context, t, i, this);
        result[i] = u;
    }
    return result;
};
```

### 🙁 Actual behavior

TypeScript seems to be unable to resolve the conditional assignment to `context` with the conditional type `C extends undefined ? Array<T> : NonNullable<C>`

### 🙂 Expected behavior

tsc should be able to deduce that the type of context matches the type of `callback`'s `this` type hint.

### Additional information about the issue

I tried a number of different variations for the conditional assignment of `context`, trying to see if the problem was with when I was `this` to `context`, but all of the ones I tried gave me variations of the same error.

* `this ?? thisArg`
* `typeof thisArg === "undefined" ? this : thisArg`
* `typeof thisArg === "undefined" ? this : <NonNullable<C>> thisArg`

(Obviously using `<any>` in any number of places in the code would work around the issue.)

**Comment by fatcerberus** [comment]
Similar to https://github.com/microsoft/TypeScript/issues/33912; conditional types aren't related to the results of control-flow analysis so you'll have to cast.

**Comment by mqudsi** [comment]
Thanks.

Closing as a duplicate of https://github.com/microsoft/TypeScript/issues/33912
