### ISSUE TITLE
"typeof" does not work with private properties of a class even when used in class methods

### ISSUE THREAD

**Issue by qwq0** [microsoft/TypeScript#55549]
### 🔎 Search Terms

typeof private properties

### 🕗 Version & Regression Information

I am using the nightly plugin in vscode and the problem is still there.

### 💻 Code

```js
class Manager
{
    /**
     * @type {Array<{ start: number, end: number, id: string }>}
     */
    #fragmentList = [];

    /**
     * @param {string} type
     * @param {number} time
     */
    async #getFragment(type, time)
    {
        /** @type {typeof this.#fragmentList} */
        let timeConformFragments = [];
    }
}
```
I used jsdoc and I tried ts and got the same error

### 🙁 Actual behavior

![screen_capture](https://github.com/microsoft/TypeScript/assets/82009862/c6ebaffa-946b-4e73-8a61-dfa7fd7a93f7)
get the ts(1003) error: Identifier expected

### 🙂 Expected behavior

typeof should work fine with private properties in the class's methods or constructors

**Comment by MartinJohns** [comment]
Duplicate of #47595.

**Comment by qwq0** [comment]
Duplicate
