### ISSUE TITLE
Support `isWellFormed` and `toWellFormed` in lib.esnext.d.ts

### ISSUE THREAD

**Issue by iKingNinja** [microsoft/TypeScript#55543]
### 🔍 Search Terms
NodeJS 20, isWellFormed, toWellFormed

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

NodeJS 20 introduces new features that are not supported by the TypeScript compiler yet.

As an example node version 20 introduces `String.prototype.isWellFormed` and `String.prototype.toWellFormed`. Using these functions causes `error TS2339: Property 'isWellFormed' does not exist on type 'string'.`

Current environment:
- Node version: 20.5.1
- TypeScript version: 5.2.2

### 📃 Motivating Example

This update will enable developers to fully use all features available in the latest major version of NodeJS.

### 💻 Use Cases

This would allow the usage of ECMAScript features such as `isWellFormed` and `toWellFormed`.

The only current workaround is to use `// @ts-ignore` to let the project compile.

**Comment by MartinJohns** [comment]
> NodeJS 20 introduces new features that are not supported by the TypeScript compiler yet.

How do these types require support by the TypeScript compiler? Sounds to me that it just needs updated `@types/node` definitions.

**Comment by iKingNinja** [comment]
Because even with `@types/node@20.5.7` installed the error keeps occurring.

**Comment by Josh-Cena** [comment]
isWellFormed and toWellFormed are ES features, so they belong in the lib defs, not `@types/node`—the title is just misleading :)

**Comment by DanielRosenwasser** [comment]
I *think* usually we don't create a new target/library combo until the spec edition is ratified. I think `esnext` is probably the place for now.

**Comment by andrewbranch** [comment]
Ah, I missed that https://tc39.es/ecma262/ shows the draft state. Is there a handy link that shows all spec versions and their statuses?

**Comment by Josh-Cena** [comment]
@andrewbranch https://github.com/tc39/ecma262/releases

Every release is cut at around April–June, and new features are always mentioned in the [introduction](https://tc39.es/ecma262/#sec-intro).
