### ISSUE TITLE
Tsserver doesn't discover all files on OpenBSD

### ISSUE THREAD

**Issue by nbonfils** [microsoft/TypeScript#55540]
### 🔎 Search Terms

"tsserver openbsd", "file 'node_modules/@types/react/index.d.ts' is not a module.", "typescript file is not a module", "typescript file is not a module openbsd", "typescript TS2306 openbsd", "typescript TS2306 Eglot", "typescript TS2306 lsp", "tsserver Changing to watchFile", "typescript lsp Changing to watchFile", "typescript emacs eglot openbsd", "tsserver syslog Changing to watchFile", "eglot typescript problem", "create react app typescript lsp", "cannot find name 'document'. do you need to change your target library? try changing the 'lib' compiler option to include 'dom'."

### 🕗 Version & Regression Information

I was unable to test this on prior versions because I don't believe this to be an issue related to the version of typescript but simply an issue linked with the OS. And I found this issue as soon as I started using the [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server).

## Case study: Create React App

To test a similar setup on both Linux and OpenBSD, I setup a barebone CRA project with typescript template, I just added the files in a git repo (so that emacs sees the whole project), otherwise there is no modification, just running `npx create-react-app ts-test --template typescript` should get you the exact same setup.

The code per say works and compile on both OSes, but when using the [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server) on OpenBSD, the tsserver sends wrong diagnostics about this snipet.

```ts
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

### 🙁 Actual behavior

So I've been trying to setup a typescript dev environment on my OpenBSD box with Emacs+Eglot and latest [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server). (It may also be worth noting I use node v18.17.1)
So the server start and Emacs is able to communicate with it, without any issues, it even manages to send some diagnostics and display them.

## Problem

Now the problem is that it gives me diagnostics when it shouldn't, I increased the log verbosity and it seems that the issues might be related to tsserver, it's in those logs that I observed a difference between a fully functional setup on Linux and a broken one on OpenBSD.

### On OpenBSD

As an example, I get diagnostics like the following in the index.tsx file of the CRA project:

```
    1  18 error    e-f-b    typescript [2306]: File '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/index.d.ts' is not a module.
    2  21 error    e-f-b    typescript [2306]: File '/home/nature/dev/ts-test/node_modules/@types/react-dom/client.d.ts' is not a module.
    4  16 error    e-f-b    typescript [2306]: File '/home/nature/dev/ts-test/src/App.tsx' is not a module.
    5  28 error    e-f-b    typescript [2306]: File '/home/nature/dev/ts-test/src/reportWebVitals.ts' is not a module.
    8   2 error    e-f-b    typescript [2584]: Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
    8  37 error    e-f-b    typescript [2304]: Cannot find name 'HTMLElement'.
   11   2 error    e-f-b    typescript [2306]: File '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/jsx-runtime.d.ts' is not a module.
```

And the tsserver.log is the following:
[tsserver_openbsd.log](https://github.com/microsoft/TypeScript/files/12453918/tsserver_openbsd.log)

What's mostly different is all those `sysLog:: /home/nature/dev/ts-test/node_modules/react:: Changing to watchFile` which seems to indicate that those files are not being considered.

When scrolling down we also see that **Linux sees something like 200+ files and OpenBSD only 60**.

### On Linux

I get no diagnostics and I get the following tsserver.log:
[tsserver_linux.log](https://github.com/microsoft/TypeScript/files/12453913/tsserver_linux.log)

All is fine there.

### Additional information about the issue

An interesting thing to note is that when I run `tsc --watch` on the project (on OpenBSD) it's able to compile successfully without errors and notice the changes made to any files within the project (even those that don't seem to be picked up by tsserver).

I also opened an issue on the  [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server) repo but I was redirected here as it seemed more of a tsserver/typescript specific issue:
https://github.com/typescript-language-server/typescript-language-server/issues/745

I've been struggling with this setup for 2 days straight now... So any help will be highly appreciated.

**Comment by andrewbranch** [comment]
Are you able to try this in some way that doesn’t involve typescript-language-server? I’m not very familiar with OpenBSD so I’m not sure what your options are, but since you say you only started seeing this upon using typescript-language-server, we would really want to remove any third-party components from the equation before trying to investigate.

**Comment by sandersn** [comment]
I use [tide](https://github.com/ananthakumaran/tide) which uses the tsserver protocol directly instead of wrapping it with the Language Server Protocol. Do you still see the error if you use tide instead?

Also, @sheetalkamat are you aware of any watch issues on OpenBSD? It sounds like it could be a problem with different definitions of files vs folders or something. (Though that could also be a problem with an LSP wrapper so probably worth trying to eliminate that first.)

**Comment by nbonfils** [comment]
Very good suggestion, so I just tried to open the same file with tide and I don't get the same diagnostics, but I still get something that probably shouldn't be there, here it is:

```
 index.tsx     1   1 error    1208   'index.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module. (tsx-tide)
```

Then, looking at the tsserver logs again we can see it being full of those `sysLog:: /home/nature/dev/ts-test/node_modules/yaml:: Changing to watchFile` lines.

[tsserver_openbsd_tide.log](https://github.com/microsoft/TypeScript/files/12463535/tsserver_openbsd_tide.log)

And this times it only seems to be able to find 59 files:

```
Info 946  [12:27:11.247] Project '/home/nature/dev/ts-test/tsconfig.json' (Configured)
Info 946  [12:27:11.247] 	Files (59)
```

I could also try the same setup again on Linux and see if things are different there, but I feel something janky is going on with tsserver on OpenBSD, my wild guess is that it could be linked to some usage of `fs.watch` and `fs.watchFile`.

When I tried to dig a bit inside the tsserver code, I found that the `Changing to watchFile` appears when there is an error here: https://github.com/microsoft/TypeScript/blob/v4.9.5/src/compiler/sys.ts#L1152
But the only error code that is checked is `ENOSPC` but if I am to believe some node documentation I read, nodejs uses [kqueue(2)](https://man.openbsd.org/kqueue.2) on OpenBSD (don't trust me on that statement), and if that is the case, in the man page it is not specified that it ever returns `ENOSPC`.
I think it could be interesting to print the error code at this `Changing to watchFile` syslog statement, to understand which error we are talking about.

Forgive me if I am getting ahead of myself, I am very new to typescript, I am trying to give as much element as I've been able to find over the past 3-4 days.

**Comment by sandersn** [comment]
To double-check: does `tsc` work when you run it from `~/dev/ts-test`?

**Comment by nbonfils** [comment]
Ok I tried a few things.

First off, I tried to run `tsc` from `~/dev/ts-test` and it runs fine.

Then I turned off `isolatedModules` in tsconfig, so no more diagnostics when I open the file, but as soon as I purposefully make a syntax error and save the file I have many errors popping, so I proceed to fix the mistake I just made and save the file again and this time the diagnostics are the exact same as with the typescript-language-server:

```
 index.tsx     1  19 error    2306   File '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/index.d.ts' is not a module. (tsx-tide)
 index.tsx     2   8 error    1192   Module '"/home/nature/dev/ts-test/node_modules/@types/react-dom/client"' has no default export. (tsx-tide)
 index.tsx     4  17 error    2306   File '/home/nature/dev/ts-test/src/App.tsx' is not a module. (tsx-tide)
 index.tsx     5  29 error    2306   File '/home/nature/dev/ts-test/src/reportWebVitals.ts' is not a module. (tsx-tide)
 index.tsx     8   5 error    2584   Cannot find name 'document'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'. (tsx-tide)
 index.tsx     8  40 error    2304   Cannot find name 'HTMLElement'. (tsx-tide)
```

Here is the log:
[tsserver_openbsd_tide2.log](https://github.com/microsoft/TypeScript/files/12466705/tsserver_openbsd_tide2.log)

Do you want me to try the same manipulation from the Linux setup? I am pretty sure it will end up seeing the 200+ files of the project and not have those `sysLog:: /home/nature/dev/ts-test/node_modules/yaml:: Changing to watchFile` lines.

**Comment by nbonfils** [comment]
I just tried and the wrong diagnostics are still present. :(
here is the logs from tsserver:
[tsserver_ts_v5.3.0.log](https://github.com/microsoft/TypeScript/files/12474130/tsserver_ts_v5.3.0.log)

**Comment by sandersn** [comment]
Have you tried a different editor? VSCode should be easy to set up and it would be interesting to know whether you get the same results. You should -- but my memory of setting up tsserver's interaction with emacs was that were lots of failure points, so vscode should eliminate some of them.

**Comment by nbonfils** [comment]
No I have not, and VSCode is unfortunately not available on OpenBSD.
If you have any other suggestions to isolate the issue I could give it a shot.

**Comment by nbonfils** [comment]
Coming back here, I would still love to get this working, but as I said VSCode is not supporting OpenBSD at all, there is no port available, and building electron apps on OpenBSD seems to be like asking for pain.
So I'd be willing to try any workeable solutions in order to investigate this further.

**Comment by sandersn** [comment]
I think @sheetalkamat is the only expert in this area, so maybe she will have an opinion.
In the meantime, you could try another tsserver-supporting editor, like vim, to see if it has the same difference. But vim is not necessarily any easier to set up than emacs.

**Comment by nbonfils** [comment]
@sheetalkamat Let me know if there is anything more I could provide so that this can move forward.

**Comment by sheetalkamat** [comment]
So looking into the logs it seems like we are not able to set native file watching and hence using polling watch. That should not impact initial project creation. To me it seems like we are not able to find some files for some reason. 

Can you enable `traceResolution` in tsconfig and generate the tsserver log on linux and open bsd so we can compare and see where things deviate. 

Also what is surprising is that on linux you get some additional lib files that are referenced through `node_modules/typescript/lib/lib.esnext.d.ts` (or indirectly from its references) while we dont see those in bsd even though that one is present.
So can you please compare the contents of `node_modules/typescript/lib/lib.esnext.d.ts` on both platforms. 

```
	node_modules/typescript/lib/lib.es5.d.ts
	  Library referenced via 'es5' from file 'node_modules/typescript/lib/lib.es2015.d.ts'
	  Library referenced via 'es5' from file 'node_modules/typescript/lib/lib.es2015.d.ts'
	node_modules/typescript/lib/lib.es2015.d.ts
	  Library referenced via 'es2015' from file 'node_modules/typescript/lib/lib.es2016.d.ts'
	  Library referenced via 'es2015' from file 'node_modules/typescript/lib/lib.es2016.d.ts'
	node_modules/typescript/lib/lib.es2016.d.ts
	  Library referenced via 'es2016' from file 'node_modules/typescript/lib/lib.es2017.d.ts'
	  Library referenced via 'es2016' from file 'node_modules/typescript/lib/lib.es2017.d.ts'
	node_modules/typescript/lib/lib.es2017.d.ts
	  Library referenced via 'es2017' from file 'node_modules/typescript/lib/lib.es2018.d.ts'
	  Library referenced via 'es2017' from file 'node_modules/typescript/lib/lib.es2018.d.ts'
	node_modules/typescript/lib/lib.es2018.d.ts
	  Library referenced via 'es2018' from file 'node_modules/typescript/lib/lib.es2019.d.ts'
	  Library referenced via 'es2018' from file 'node_modules/typescript/lib/lib.es2019.d.ts'
	node_modules/typescript/lib/lib.es2019.d.ts
	  Library referenced via 'es2019' from file 'node_modules/typescript/lib/lib.es2020.d.ts'
	  Library referenced via 'es2019' from file 'node_modules/typescript/lib/lib.es2020.d.ts'
	node_modules/typescript/lib/lib.es2020.d.ts
	  Library referenced via 'es2020' from file 'node_modules/@types/node/index.d.ts'
	  Library referenced via 'es2020' from file 'node_modules/typescript/lib/lib.es2021.d.ts'
	node_modules/typescript/lib/lib.es2021.d.ts
	  Library referenced via 'es2021' from file 'node_modules/typescript/lib/lib.es2022.d.ts'
	node_modules/typescript/lib/lib.es2022.d.ts
	  Library referenced via 'es2022' from file 'node_modules/typescript/lib/lib.esnext.d.ts'
	
```

**Comment by nbonfils** [comment]
Hi @sheetalkamat sorry for the delay, I was a bit busy last week.

First off, here are all the logs I was able to get when running `typescript-language-server --stdio --log-level 4 --tsserver-log-verbosity verbose` with eglot on emacs:
[tsserver_semantic_openbsd.log](https://github.com/microsoft/TypeScript/files/12641105/tsserver_semantic_openbsd.log)
[tsserver_syntax_openbsd.log](https://github.com/microsoft/TypeScript/files/12641106/tsserver_syntax_openbsd.log)
[tsserver_semantic_linux.log](https://github.com/microsoft/TypeScript/files/12641108/tsserver_semantic_linux.log)
[tsserver_syntax_linux.log](https://github.com/microsoft/TypeScript/files/12641109/tsserver_syntax_linux.log)

Also here is the diff between the two `lib.esnext.d.ts` files:
```
--- lib.esnext.openbsd.d.ts     Sat Sep 16 18:09:42 2023
+++ lib.esnext.linux.d.ts       Sat Sep 16 18:10:13 2023
@@ -14,9 +14,9 @@
 ***************************************************************************** */
 
 
-/// <reference no-default-lib="true"/>
 
-/// <reference lib="es2023" />
-/// <reference lib="esnext.intl" />
-/// <reference lib="esnext.decorators" />
-/// <reference lib="esnext.disposable" />
+/// <reference no-default-lib="true"/>
+
+
+/// <reference lib="es2022" />
+/// <reference lib="esnext.intl" />
```

It's actually quite strange that both files are different since I really followed the exact same procedure of using create-react-app (exact same version of node) on both machines.

Both files for reference (had to add `.txt` to upload them):
[lib.esnext.linux.d.ts.txt](https://github.com/microsoft/TypeScript/files/12641125/lib.esnext.linux.d.ts.txt)
[lib.esnext.openbsd.d.ts.txt](https://github.com/microsoft/TypeScript/files/12641126/lib.esnext.openbsd.d.ts.txt)

**Comment by sheetalkamat** [comment]
The typescript version you are running on both these are different so that would explain changes in lib files:

```
// From openBSD log
Info 0    [15:52:54.434] Starting TS Server
Info 1    [15:52:54.435] Version: 5.3.0-insiders.20230829
```

```
// From Linux log
Info 0    [16:00:44.413] Starting TS Server
Info 1    [16:00:44.418] Version: 4.9.5
```

**Comment by nbonfils** [comment]
Hi @sheetalkamat,
I am sorry, I didn't realize I kept the tsserver version from https://github.com/microsoft/TypeScript/issues/55540#issuecomment-1698086360.

I reset the version and here are the logs with the correct version on OpenBSD:
[tsserver_semantic_openbsd.log](https://github.com/microsoft/TypeScript/files/12678872/tsserver_semantic_openbsd.log)
[tsserver_syntax_openbsd.log](https://github.com/microsoft/TypeScript/files/12678873/tsserver_syntax_openbsd.log)

I also checked `node_modules/typescript/lib/lib.esnext.d.ts` and now there are no difference at all between the file on Linux or OpenBSD.

**Comment by nbonfils** [comment]
I don't think this issue should be closed.
It still is not working on OpenBSD and we haven't found any explainations yet, I produced all the required logs and this time with the specific `traceResolution` option as well as maximum verbosity. Of course with the same version on Linux and OpenBSD, I tried my best to investigate this a month ago and my initial thought was that there is something fishy going on with the file discovery and those `sysLog:: /home/nature/dev/ts-test/node_modules/react:: Changing to watchFile` messages.
Unfortunately I don't have enough knowledge of tsserver to start making custom builds and debugging it...

**Comment by sheetalkamat** [comment]
Can you please upgrade to nightly typescript and use latest create-react-app and get me logs on linux vs openBSD from just so we can avoid any fixed issue. (with `traceResolution` enabled.

I would also like you to share the source code with `node_modules` folder as is so that we can verify that contents are same. 
I noticied few discripencies in linux and open bsd logs:
`isolatedModules` is true on linux but not on openbsd. Not sure i

First place where resolutions goes differently is the absence of following resolution from open bsd:
```
======== Resolving module './' from '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/jsx-runtime.d.ts'. ========
Info n  [dd:mm:yy:mmm] Explicitly specified module resolution kind: 'NodeJs'.
Info n  [dd:mm:yy:mmm] Loading module as file / folder, candidate module location '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/', target file type 'TypeScript'.
Info n  [dd:mm:yy:mmm] File '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/package.json' does not exist.
Info n  [dd:mm:yy:mmm] File '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/index.ts' does not exist.
Info n  [dd:mm:yy:mmm] File '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/index.tsx' does not exist.
Info n  [dd:mm:yy:mmm] File '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/index.d.ts' exist - use it as a name resolution result.
Info n  [dd:mm:yy:mmm] ======== Module name './' was successfully resolved to '/home/nature/dev/ts-test/node_modules/@types/react/ts5.0/index.d.ts'. ========
```

**Comment by DanielRosenwasser** [comment]
also for what it's worth, if you're still running into issues with the latest TypeScript (and have followed all of Sheetal's instructions), a more up-to-date version of the inode PR is going to be available here: https://github.com/microsoft/TypeScript/pull/55567#issuecomment-1738006493
