### ISSUE TITLE
String.prototype.matchAll must return RegExpExecArray

### ISSUE THREAD

**Issue by nihil-admirari** [microsoft/TypeScript#55557]
### ⚙ Compilation target

ESNext

### ⚙ Library

ESNext

### Missing / Incorrect Definition

[`es2020.string.d.ts`](https://github.com/microsoft/TypeScript/blob/7c417bfd1d14326575a2f08f8b6013a8c10d9f9e/src/lib/es2020.string.d.ts#L9) defines `matchAll` as returning `RegExpMatchArray`:
```ts
interface String {
    matchAll(regexp: RegExp): IterableIterator<RegExpMatchArray>;
}
```

[`RegExpMatchArray`](https://github.com/microsoft/TypeScript/blob/7c417bfd1d14326575a2f08f8b6013a8c10d9f9e/src/lib/es5.d.ts#L936C17-L936C17) has optional `index` and `input`:
```ts
interface RegExpMatchArray extends Array<string> {
    index?: number;
    input?: string;
    0: string;
}
```

[MDN says](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#return_value) that `matchAll` returns an iterator of matches:

> Each match is an array with the same shape as the return value of [RegExp.prototype.exec()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec).

But [`RegExpExecArray`'s](https://github.com/microsoft/TypeScript/blob/7c417bfd1d14326575a2f08f8b6013a8c10d9f9e/src/lib/es5.d.ts#L951) `index` and `input` are not optional:
```ts
interface RegExpExecArray extends Array<string> {
    index: number;
    input: string;
    0: string;
}
```

### Sample Code

```TypeScript
Array.from(str.matchAll(separator)).forEach(m => {
    // doesn't compile with `strictNullChecks`, since `m.index` is `number | undefined`
    const lastIdx = m.index + m[0].length;
});
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#return_value

**Comment by jakebailey** [comment]
https://github.com/microsoft/TypeScript/issues/36788 ?

**Comment by nihil-admirari** [comment]
Oops. Closing as a duplicate.
