### ISSUE TITLE
Parsing error for `for (await using of of of) {}`

### ISSUE THREAD

**Issue by sosukesuzuki** [microsoft/TypeScript#55555]
### 🔎 Search Terms

"using of"

### 🕗 Version & Regression Information

- This changed between versions ___5.1___ and ___5.2____

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/N4KABGBmD2BOYAoCGB3JBLALmArgZ3QDsBzMaSMi8gSgG5wo4xUNtk0tcCTLeb6AviCA

### 💻 Code

```ts
{
  for (await using of of of);
}
```

### 🙁 Actual behavior

Parsing error `The left-hand side of a 'for...of' statement must be a variable or a property access.`

### 🙂 Expected behavior

Parse successful.

### Additional information about the issue

Context: https://github.com/prettier/prettier/pull/15321/files#r1308180336
Spec: https://tc39.es/proposal-explicit-resource-management/#sec-for-in-and-for-of-statements

Babel can parse `for (await using of of of) {}`. ref: https://github.com/babel/babel/blob/b804bb08912d262133213dcd7f40d81645f97489/packages/babel-parser/test/fixtures/experimental/async-explicit-resource-management/valid-for-using-binding-of-of/input.js

**Comment by fisker** [comment]
Typo 

> Babel can parse for (using of of of) {}.

Should be 

> Babel can parse for (await using of of of) {}.

**Comment by sosukesuzuki** [comment]
@fisker Thank you, fixed.

**Comment by MartinJohns** [comment]
Does this ever happen with real code, or is it just an attempt to intentionally *break* the parser?

**Comment by sosukesuzuki** [comment]
I didn't see this with real code but I didn't intentionally break the parser, I just noticed it while developing the code formatter.

**Comment by DanielRosenwasser** [comment]
(congrats on issue #55555!)

**Comment by rbuckton** [comment]
> Does this ever happen with real code, or is it just an attempt to intentionally _break_ the parser?

It's a spec conformance issue. The spec specifically forbids `for (using of of` since that can be ambiguous (`using` could be an identifier like `x` in `for (x of of`, or `of` could be either an identifier or a keyword), while `for (await using of of` is unambiguous (`await using` can only imply the declaration, thus `await using of` must declare an identifier).
