### ISSUE TITLE
URLSearchParams: has() method can have 2 arguments

### ISSUE THREAD

**Issue by isumix** [microsoft/TypeScript#55569]
### 🔎 Search Terms

URLSearchParams has Expected 1 arguments, but got 2.

### 🕗 Version & Regression Information

Typescript version 5.1.6

### 💻 Code

```ts
searchParams.has('category', category)
```

### 🙁 Actual behavior

Error:

Expected 1 arguments, but got 2.

### 🙂 Expected behavior

Should pass type checker

### Additional information about the issue

Quickfix:

Add this to your `any.d.ts` file

```ts
global {
  interface URLSearchParams {
    has(name: string, value?: any): boolean;
  }
}
```

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator#when-the-type-is-missing

> [..] see the browser compatibility section and check whether it's supported by **two or more** browser engines.

According to MDN this is only supported by Firefox.

**Comment by isumix** [comment]
same applies for the `delete` method

**Comment by portoaj** [comment]
The value parameter now seems to be supported by all web browsers although support was only added quite recently in 2023.
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/delete
