### ISSUE TITLE
Spreading an object allows adding incompatibly typed properties to an object

### ISSUE THREAD

**Issue by chriskuech** [microsoft/TypeScript#55563]
### 🔎 Search Terms

spread type property

### 🕗 Version & Regression Information

- Observed with TS v5.2.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAFwngDgpgBAsmAKpWBeGBvYMYEMBcMAdgK4C2ARlAE4DcwAvsMAMYD2RAziDAJZEA3XABteAExjosOAjACMAGmwwKhAEyN6wAPTbibELxawQAC1w8ABvyGixlvp309cnTrwDmRXBWEm2MJYIyNCWrBzcKoTBKJKYeISKUTBqDFq6KiQ8AO6wuNR5vv4wINRGANZ8ObxmMJwQBbgSbNDUFmzU4Vwu0UixUjAAdMM2IuIwTEA

### 💻 Code

```ts
type MyType = {
  a: number;
}

const invalid = {
  a: 1,
  b: 2
};

// notice that `invalid` is not assignable to `MyType`
const b: MyType = { a: 1, b: 2};

// but we are able to trick it with spread operator
const a: MyType = { ...invalid }
```

### 🙁 Actual behavior

Spreading allows the extra invalid property, causing downstream breakages during runtime.

### 🙂 Expected behavior

TypeScript compiler correctly identifies that a spread property is incompatible and does not produce a build.

**Comment by MartinJohns** [comment]
The spread object is not incompatible. Additional properties are allowed. This is not a bug.
