### ISSUE TITLE
Import type information only

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/TypeScript#5556]
There's a few other issues that touch on something similar (https://github.com/Microsoft/TypeScript/issues/5098, https://github.com/Microsoft/TypeScript/issues/278), but is there a way to explicitly import **only** type information from an external module? I imagine something like below, where there's a reserved word used to modify an existing import:

```ts
import type * as ts from 'typescript'
import type ts = require('typescript')

ts.parseJsonConfigFileContent(...) // Error, type information only.

var TS: ts = require('typescript')

ts.parseJsonConfigFileContent(...) // Works great.
```

This construct would import type information only, and any runtime usage of the namespace in the current module could be considered an error. This is useful in a few place (E.g. `ts-node` and `tsconfig`) where I need the type information from TypeScript, but I also need to guarantee that I don't accidentally import it as a dependency in the compiled output. Not sure if others have a similar use-case, but the reverse at least seems to be an issue (importing for side-effects only, which is optimized out by the compiler currently).

**Comment by DanielRosenwasser** [comment]
So you're not going for eliding modules, right? You're specifically trying to make it so that users don't accidentally use values withing a module?

**Comment by basarat** [comment]
> but I also need to guarantee that I don't accidentally import it as a dependency in the compiled output

I tend to use `_ts` for *type import only* scenarios. e.g. 

```ts
import _atomUtils = require('../main/atom/atomUtils');
var atomUtils: typeof _atomUtils;
```

[Use case lazy loading](https://basarat.gitbooks.io/typescript/content/docs/project/external-modules.html) Or I might have misunderstood the question

**Comment by blakeembrey** [comment]
@basarat Absolutely correct, that's the same use-case I have with `ts-node` too. I wanted the TypeScript type information, but the TypeScript compiler is lazy loaded depending on the compiler the user specifies.

@DanielRosenwasser Yes, eliding modules works. But I need to be explicitly sure that I haven't accidentally used the value before it's been defined (E.g. guarantee that `require('typescript')` does not get emitted).

**Comment by mhegazy** [comment]
see #2812 for more details.

**Comment by philkunz** [comment]
I think that this behaviour would be really helpful. Otherwise lazy loading of modules is practically impossible when wanting to preserve module typings, isn't it?

**Comment by philkunz** [comment]
ok, I'm currently implementing a module that allows easy lazy loading of plugins with types in place using systemjs so it'll work in browsers and in node.

**Comment by philkunz** [comment]
Here is my idea:

```typescript
import {LazyModule, loadNow } from 'smartsystem'

import * as myPluginType from 'myPlugin' // plugin does not get loaded here at runtime
let myPluginPromised = LazyModule<typeof myPlugin>('myPlugin')

import * as anotherPluginType from 'anotherPlugin' // plugin does not get loaded here at runtime
let anotherPluginPromised = LazyModule<typeof anotherPlugin>('anotherPlugin')

myPluginPromised.then(myPlugin => { /* do something with myPlugin */ })
myPluginPromised.also(anotherPluginPromised).then((m,a) => {}) // also takes multiple other plugins

loadNow.only('myPlugin') // loads myPlugin and resolves the lazy promise
loadNow.also('myPlugin') // loads myPlugin and any chained 'also' modules, e.g. 'anotherPlugin'
```

**Comment by philkunz** [comment]
https://www.npmjs.com/package/smartsystem
