### ISSUE TITLE
Type inference fails when using combined boolean variable in if condition

### ISSUE THREAD

**Issue by ddubrava** [microsoft/TypeScript#55577]
### 🔎 Search Terms

"typescript destructuring losses types", "typescript destructuring losses type object is possibly undefined", "typescript type alias destructuring loses type", "typescript inference with union types"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhAigVwgJxAJQnZAbYAHgBUA+KAXigG8AoKBqASzgGVkBjDnOALigBmAQzwIA3PUYATIcCH9kAOykQBTRRCkSAvlAA+NSQxbsuPfsDSoJjKDLn9itbRNoClHYEwD2iqMgQUdBAACgBKfngkVAxsXAJCRWQAWwAjdHI6WzQIYGQ0PyzbRhNObjg+QREEABojYvt5f2VVdU062xdnWloOXzhgGjtZJsaARhrmNjLzKdNyuDGoXSoA6ODwiT7FAaHG-kaAJknSswr+U4XD5cp-QJjQsK3+wephh3ehAGYT6bPKy48L43Vb3DZPHoAekhUAAkoMAO7eNAAazgUCE6IgAA9IJ5NLQmAIoCFARUlgAyClzGYVa5Umn-L5hQy2cYAOmA3gAorjfBBFF4RJt6kdOTy+RpBUxhRC2SMvuLeWB+dLZToettdkIcvMeLcyYsoAzDfTqYavq5oXDBlJvDhFAByRHIlFQAAW6AgkwR7qYeGgTGAjvRACsAoMhFA+ml1LIfH5vMSQ7SEHBHYTiSEdRA9RUWUUGByucrVUK8CL5XJDkrJQLy5XpArayqpQ2IdogA

### 💻 Code

```ts
type UseQueryResult<T> = {
    isSuccess: false;
    data: undefined;
} | {
    isSuccess: true;
    data: T
};

function useQuery(): UseQueryResult<number> {
    return {
        isSuccess: false,
        data: undefined,
    };
}

const { data: data1, isSuccess: isSuccess1 } = useQuery();
const { data: data2, isSuccess: isSuccess2 } = useQuery();
const { data: data3, isSuccess: isSuccess3 } = useQuery();

// It works as expected
if (isSuccess1 && isSuccess2 && isSuccess3) {
    data1.toExponential();
    data2.toExponential();
    data3.toExponential();
}

const areSuccess = isSuccess1 && isSuccess2 && isSuccess3;

// It doesn't work here, while it's just a combination of 'successes'
if (areSuccess) {
    data1.toExponential();
    data2.toExponential();
    data3.toExponential();
}
```

### 🙁 Actual behavior

The issue occurs when using the combined boolean variable `areSuccess` in the second if condition. Although `isSuccess1`, `isSuccess2`, and `isSuccess3` are all true, TypeScript cannot narrow down the types of `data1`, `data2`, and `data3` within the if block, leading to a type error

### 🙂 Expected behavior

`areSuccess` is a combination of the individual `isSuccess` variables, it should correctly infer the types of `data1`, `data2`, and `data3` as the specific data type (number) defined for the queries. This should allow the code to call the toExponential method on each data variable without any issues.

**Comment by fatcerberus** [comment]
For performance reasons, IIRC indirect narrowing only works one level down.

**Comment by andrewbranch** [comment]
I think #44730 and #46266 aren’t talking to each other. I’m not sure if that’s a known limitation. @ahejlsberg?

**Comment by fatcerberus** [comment]
I thought it was just that

```ts
const typeGuard1 = ...
const typeGuard2 = ...
const check = typeGuard1 && typeGuard2;
if (check) {
    // not a type guard
}
```

doesn't work in general.  But maybe I'm wrong about that, I haven't actually tested it thoroughly.

**Comment by andrewbranch** [comment]
Seems like it goes through quite a few aliases and logical operators: https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFz0xgEsUBzeAH3gFcVQAzEkYAbgChRJYFl0sBPfIRLkqtBk1Zs2vTDgCSaACIhGKZvAC8OeAEJN28asntZAxSrUbt-PQZp1j6qWyL14ACmwWnGgGR+8Pw+VsAAlPAA3mzwsTgAdBhIADJIAO4gMADCUGggHmHscUGJKemZOXkF7AC+0mbwAEZIGAAWAIJwlpJaCsq+wPABQSEmru4ezW2dIN3OEdHF2KWpGdm5+YUxcfwr5etVW3XwMZzQcIiocgBeQhjEZJQOEs5FDdejzr3XdoaOoewYg0oBAIDM5tYmi0Ol0BkNAh9+gCYm5PCCwbDQgttrFlklVhUNtUcSV8ftKpsinFrns1hTifBjkA
