### ISSUE TITLE
Arrow function parameters using an alias and intersection are expanded inappropriately in `.d.ts`

### ISSUE THREAD

**Issue by webstrand** [microsoft/TypeScript#55575]
### 🔎 Search Terms

arrow function type alias parameters expansion intersection

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about declarations and aliases.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230830#code/JYWwDg9gTgLgBAbzgBShMBnOBfOAzNEOAIigFMBDAYxgFoMyAbMm4gbgCgOyAPSWOFQgA7DPADCAVzEQQAZSYsYARjgBeOAB4A8mBjARAGgB8ACh4AuFGkw69B4YfwVGDY3ABkibAEp17hGxuPmh4PElhGgc4KRl5RRoAJjt9IzNLa3QMFIcnPBc3T28-QKA

### 💻 Code

```ts
import { Props } from "react-select";

export const CustomSelect1 = <Option,>(x: Props<Option, false> & {}) => {}
export function CustomSelect2<Option,>(x: Props<Option, false> & {}) {}
```

### 🙁 Actual behavior

The output `.d.ts` incorrectly expands the imported `Props` alias. Note that it has incorrectly resolved the default parameter. 

```ts
import { Props } from "react-select";
export declare const CustomSelect1: <Option>(x: Omit<import("react-select/base/dist/react-select-base.cjs").PublicBaseSelectProps<Option, false, import("react-select").GroupBase<Option>>, "inputValue" | "menuIsOpen" | "onChange" | "onInputChange" | "onMenuOpen" | "onMenuClose" | "value"> & Partial<import("react-select/base/dist/react-select-base.cjs").PublicBaseSelectProps<Option, false, import("react-select").GroupBase<Option>>> & import("react-select/dist/declarations/src/useStateManager").StateManagerAdditionalProps<Option>) => void;
export declare function CustomSelect2<Option>(x: Props<Option, false> & {}): void;
```

### 🙂 Expected behavior

The imported type alias `Props` _must not_ be expanded, if the upstream package changes its defaults this will cause confusion because dependencies relying on the defaults will not be able to use the new default.

```ts
import { Props } from "react-select";
export declare const CustomSelect1: <Option>(x: Props<Option, false> & {}) => void;
export declare function CustomSelect2<Option>(x: Props<Option, false> & {}): void;
```

### Additional information about the issue

This problem became _much_ worse with the advent of 4.2.3, with prior version of typescript only mistakenly expanding the default argument.

Additionally this causes difficult-to-reproduce issues producing errors like

> The inferred type of 'CustomSelect' cannot be named without a reference to '../../../node_modules/react-select/dist/declarations/src/useStateManager'. This is likely not portable. A type annotation is necessary.ts(2742)

because the expanded alias uses types that aren't imported.

**Comment by Andarist** [comment]
What is interesting here is that in the case of function declaration `isSymbolAccessibleWorker` isn't even called. This also means that `serializeTypeForDeclaration` isn't called (as that leads to tracking entity names and to checking `isSymbolAccessibleWorker`). 

The variable statement gets transformed here: 
https://github.com/microsoft/TypeScript/blob/45e5a45d87fd28cc6d5d752daf40f4961b9fa745/src/compiler/transformers/declarations.ts#L1782-L1784

and the function declaration doesn't go through a similar transformation:
https://github.com/microsoft/TypeScript/blob/45e5a45d87fd28cc6d5d752daf40f4961b9fa745/src/compiler/transformers/declarations.ts#L1522-L1533

It feels that there might also be other differences between those 2 and that both branches should get unified more when it comes to emitting signature declarations. It's probably also worth rechecking if there are similar discrepancies between class expressions and class declarations.
