### ISSUE TITLE
TS5094: Compiler option '--noEmit' may not be used with '--build'

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/TypeScript#55573]
### 🔎 Search Terms

TS5094  
TS5094 noEmit build

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

N/A, it’s a CLI bug

### 💻 Code

```ts
// An empty file will suffice, but let’s add a console.log to make more interesting.
console.log('hello')
```

```jsonc
// Now this is the interesting file
// tsconfig.json
{
  "compilerOptions": {
    "noEmit": true
  }
}
```

### 🙁 Actual behavior

This command behaves as `tsc --noEmit`

```sh
$ tsc --build
```

The `--build` and `--noEmit` options are mutually exclusive. I imagine `--build` is supposed to be mutually exclusive with the `noEmit` compiler option instead.

```sh
$ tsc --build --noEmit false
error TS5094: Compiler option '--noEmit' may not be used with '--build'.
```

### 🙂 Expected behavior

My preferred solution is that `--build` disables the `noEmit` compiler option.

Another option is that `--build` fails if `noEmit` is true.

### Additional information about the issue

I think the `tsc --build` option is great. I prefer this over running `tsc` without it.

I also like the idea of running `tsc` without emitting anything. This is achieved by adding `noEmit` to `tsconfig.json`.

It’s unfortunate these two currently don’t play well together. As a workaround I now typically don’t use `--build`.

**Comment by fatcerberus** [comment]
Related to https://github.com/microsoft/TypeScript/issues/53979.  Apparently [the two options aren't *entirely* mutually exclusive](https://github.com/microsoft/TypeScript/issues/53979#issuecomment-1520521650).

**Comment by remcohaszing** [comment]
I’m going to close this as a duplicate of https://github.com/microsoft/TypeScript/issues/53979. Maybe that issue should add `TS5094` to the search terms.

> This is not a crash.

Not really, but it felt the most accurate one from the options the issue template gave me.
