### ISSUE TITLE
error TS2300: Duplicate identifier 'print'

### ISSUE THREAD

**Issue by provegard** [Microsoft/TypeScript#5557]
I have a file that will be evaluated by Nashorn. Nashorn has a global function called `print`. Therefore I declare it like so:

```
declare var print: (_: string) => void;
```

When I compile, I get:

```
.../node_modules/typescript/lib/lib.d.ts(16887,18): error TS2300: Duplicate identifier 'print'.
```

If I call tsc with the `--noLib` option, I instead get:

```
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
```

What are my options here? Importing Window from lib.d.ts is pointless since there is no window in Nashorn.

**Comment by mhegazy** [comment]
use `lib.core.d.ts` instead. this does not have the DOM or any of the other environment declarations. here is the file: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.core.d.ts

**Comment by provegard** [comment]
Works perfectly! Thanks!

**Comment by mhegazy** [comment]
glad it helped.
