### ISSUE TITLE
Type narrowing does not work on boolean variables

### ISSUE THREAD

**Issue by LeonardYam** [microsoft/TypeScript#55586]
### 🔎 Search Terms

"type narrowing", "type guards", "switch statement", "switch", "possibly null"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBVDtHHwDAAXlAAG9FCUSpx2IgAPJkAByUWg+X6bOk31AAB8BdBoIoAL7BBCcQQ0ZLU6SOUD8pW0hlM5msjnc3n8gCsvGlwUUcoVDIFep5EtAUtAdI1KrI5salqEPMQjutnNt0FAAEIaXTWRKANzBFQSeBkeLCBjCCGQWAKbjFBGgAAUnrZAEo0fL4O4AtB4Mws40UAAeUAARgADHmzYJ3qgNNnc4gC4zmaNBJYyOxIIU+32VAR4II5NJoHhxQHvmxXWPmRbi5BS+Ws7q-bzQLXG83VyUJh5pjKo2AcM0PGQvIhY85gewaF83GZmOwGMxIPxYNA6iJAwwJ6CIXgAEQAKKrAwiALPoEFJNiEHgA4qAAOTCFykASBBQQqOyXxkO8A78L+RyoI4abjPOTiPjowxYPoKAIIg0IJjwzGSLG0QiAYHDYgsTCsBwPBBCUQA

### 💻 Code

```ts
type foo = {
    numOrNull: number | null
}

const foobar : foo = {
    numOrNull: 5,
}

const { numOrNull } = foobar
const isNum = numOrNull !== null;

// works as expected
// if (isNum) console.log(one < 10)

switch (isNum) {
    case true:
        // possibly null error
        console.log(numOrNull < 10)
        break
}
```

### 🙁 Actual behavior

`numOrNull` is `possibly null` inside the switch statement

### 🙂 Expected behavior

`numOrNull` should be narrowed down to type `number` and there should not be any errors

**Comment by fatcerberus** [comment]
For the record, this doesn't work either, so it's nothing to do with the variable:

```ts
switch (numOrNull !== null) {
    case true:
        // possibly null error
        console.log(numOrNull < 10)
        break
}
```

TS just doesn't seem to recognize `switch` over a type guard as a narrowing operation.

**Comment by MartinJohns** [comment]
Related: #37178

This is probably just a pattern that is not supported. And I honestly see no reason why you'd write code like this.

**Comment by LeonardYam** [comment]
Ah I see! Of course, I understand this pattern is very uncommon and there are simple alternatives with if-statements. I just wanted to understand why it did not work - whether the control flow analysis does not support this pattern etc.

And upon further digging, I found the exact reason why this is [not supported](https://github.com/microsoft/TypeScript/issues/32819#issuecomment-520543814). Thanks for the quick replies @fatcerberus @MartinJohns!

**Comment by mykohsu** [comment]
Unlike #37178, this also doesn't work with if statements? Extracting certain logical expressions into local variables to make a complex if more parsable seems like a reasonable use case.

```
declare function equals(a: { [key: string]: any; }, b: { [key: string]: any; }): boolean;

let current: undefined | {} | null = null;

function updateValue() {
  const value = Math.random() > 0.5 ? {} : undefined;
  const check = current && value;
  if (check && equals(current, value)) { // error
    return;
  }
  if (current && value && equals(current, value)) {
    return;
  }
  current = value;
}
```

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxAEdkoIBnACigC54BveAbQGsQBPWsjGLVAcwC6tKKjYBueAF8ANPABGtBi3aduvQcNETJASlpycOCCBFiAUGeMZ4YZDDioMtNKES8QweAB96k7-FRkCAh4AF4AoIhzMxR0bDx4ZAAHYCgMEAA1UmQQCh16M3gbPC54ADdshHCAWTSACwA6GBFgHABbPPgAPngABgaAVngAfl94Z1RXd2BzIrAS6zA68GYwmzsHawAyLfLK2fgsRHgKJZX4HYJiUkpbexBHWQqIHJ18ukKi+DgMO1QDySfI4nO6bC67Z45cFXEjkU4bB4YJ6VN4FL7fEC-GD-T6AuYIxxrSEgcySIA
