### ISSUE TITLE
VSCode does not provide suggestions/auto-complete for NPM package installed as a dependency of another

### ISSUE THREAD

**Issue by paul-uz** [microsoft/TypeScript#55594]
I have my own "SDK" package which has a dependency of a popular ORM package.

I can installed my SDK package in a project, and I can import the ORM package and use it, however, autocomplete, and suggestions when i write a method belonging to the ORM hasn't yet been imported, simply do not work, unless I add the ORM package explicitly to my projects package.json, which seems a bit redundant?

Is there anything I can add to my project package.json file to get it working?

**Comment by andrewbranch** [comment]
Duplicate of #38768

**Comment by mrleblanc101** [comment]
It would be nice ot have an option to not filter sub-dependencies
