### ISSUE TITLE
Can no longer debug typescript files in Visual Studio 2013 Update 3

### ISSUE THREAD

**Issue by Zenoware** [Microsoft/TypeScript#556]
Not even sure how this has happened, but I was able to use Visual Studio and debug with Internet Explorer 11 for the longest time without any issues. Then, one day the breakpoints started not to load. After emptying the cache in Internet Explorer, they loaded again. Now, they are consistently not loading. The Script Document shows the javascript files that are compiled and I can debug in Firefox (even the typescript files) so I assume the map files are correct. I have reinstalled Visual Studio and IIS just to eliminate any of those being an issue, so I am now turning here and hopefully this is just some simple issue.

I have gone through at least 20 possible solutions for this issue and the fact that I can hit a breakpoints in the Script Documents tells me something is up.

**Comment by mleyb** [comment]
I also get this problem and have done since update 3

I can debug .ts files in Firefox, but not in Chrome or IE

**Comment by mantalope** [comment]
I was using Web Essentials to minify the JS files and experiencing the same problem in Update 4. When I changed my HTML reference to the un-minified JS files, breakpoints began to work again...at least so far.

**Comment by frodegil** [comment]
Had the same issue. Mantalope gave me an idea. I had just recently changed the script reference in my index.html file to the minified version of the JavaScript file (typescript output). Changing from "myfile.min.js" to "myfile.js" fixed the problem. Typescript debugging in VS works again.

**Comment by sheetalkamat** [comment]
I installed update 4 and created typescript app and wasn't able to repro this issue. Played around a code bit by adding internal modules, classes, functions etc and still was able to debug properly. If anyone who is still running into this with update 4, if you can share your project/code, I would be able to investigate in detail.

I also installed web essentials later, there is no option to minimize the typescript file output. The minimized .js file has missing sourceRoot entry and hence vs doesn't allow you to debug that file. I added that entry manually and the offsets seem to be off. But that's again done with web essentials minimizer and not the typescript compiler. Note that VS doesn't support indirect/linked sourcemaps right now.

**Comment by mhegazy** [comment]
I believe the main issue reported in this issue has been addressed. closing. please file a new issue if you are still experiencing problems with debugging.
