### ISSUE TITLE
Missing `type` keyword completion causes auto-import of `type` symbol

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript#55607]
With `@types/node` installed, start typing `type` at the top level in any TS file 😱 

<img width="829" alt="image" src="https://github.com/microsoft/TypeScript/assets/3277153/ca99cc56-eeee-4269-9b76-a6bf32275478">

**Comment by andrewbranch** [comment]
I can reproduce this at least back to 4.8... bananas that nobody has complained about this as far as I know? Is something weird in my own setup?

**Comment by fatcerberus** [comment]
Maybe `type` is a short enough keyword that nobody feels the need to auto-complete it?

**Comment by andrewbranch** [comment]
I guess my laziness consumed one more keystroke than it used to in the last couple weeks

**Comment by andrewbranch** [comment]
Through an extremely scientific process I have determined that this problem exists for exactly this set of contextual keywords:

- abstract
- async
- await
- declare
- module
- namespace
- type

The problem doesn’t repro for cases where the completion is already happening in type-space, which eliminates most contextual keywords:

```ts
// global `string` type comes first, auto-import second if present
type S = stri/*|*/
```

Many other contextual keywords (e.g. `as`, `out`, `infer`, `of`) are only treated as keywords in a location where auto-imports are already not offered, so those are fine too.

Of the affected list, `async` and `await` are the only ones that can be keywords in the middle of an expression. The others are only keywords when they begin a declaration. Unfortunately, our keyword filtering is really bad, so here:

```ts
const x = abstrac/*|*/
```

ideally we wouldn’t give you the `abstract` keyword completion at all, and there would be no conflict if there was an auto-import named `abstract`. Whereas here:

```ts
abstrac/*|*/
```

we should offer both the keyword and the auto-import, but prioritize the keyword (as we always do when same-named entries between these kinds exist).

I think I’m not going to fix keyword filtering broadly as part of this, nor add special casing to prioritize the auto-import in RHS expressions for `abstract`, `declare`, `module`, and `namespace`. If exports by those names exist, they’ll always be prioritized beneath keywords for now, even in places where those keywords shouldn’t be offered.
