### ISSUE TITLE
Duplicate identifiers in github-electron-* definitions

### ISSUE THREAD

**Issue by Patman64** [Microsoft/TypeScript#5560]
I just got bit by the same issue [mentioned here](https://github.com/Microsoft/TypeScript/issues/1066#issuecomment-115708947).

I'm using DefinitelyTyped with the `github-electron*` definitions, and [github-electron-main.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/github-electron/github-electron-main.d.ts) and [github-electron-renderer.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/github-electron/github-electron-renderer.d.ts) both declare an `ipc` module and export something, causing the errors:

```
typings/github-electron/github-electron-main.d.ts(229,2): error TS2300: Duplicate identifier 'export='.
typings/github-electron/github-electron-renderer.d.ts(99,2): error TS2300: Duplicate identifier 'export='.
```

Is there a way to prevent `tsc` from loading these definitions, so I can just `/// <reference />` it in the proper source files?

**Comment by Patman64** [comment]
Should be fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6663

**Comment by mhegazy** [comment]
Thanks @Patman64 for the update. looks a DT issue then.
