### ISSUE TITLE
"ESNext" target doesn't compile "using" keyword while "ES2022" does

### ISSUE THREAD

**Issue by hazae41** [microsoft/TypeScript#55609]
### 🔎 Search Terms

"ESNext", "using", "keyword", "ES2022", "target"

### 🕗 Version & Regression Information

When I tried compiling my lib with Rollup, including **the new "using" keyword**, under "ESNext" target, it failed with "Unexpected token" error; but when compiling under "ES2022" target, it works fine

### 💻 Code

```ts
using disposable = ...
```

### 🙁 Actual behavior

"Unexpected token" error

### 🙂 Expected behavior

Successful compilation, just like ES2022, since ESNext >= ES2022

### Additional information about the issue

`tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "baseUrl": "./src",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "downlevelIteration": true,
    "lib": [
      "DOM",
      "ESNext"
    ]
  },
  "include": [
    "./src/**/**.ts",
  ],
}
```

`package.json`.`devDependencies`

```json
"rollup": "^3.28.1",
"@rollup/plugin-typescript": "^11.1.3",
"tslib": "^2.6.2",
"typescript": "^5.3.0-dev.20230902"
```

`rollup.config.js`

```js
import ts from "@rollup/plugin-typescript"

export const config = [
  {
    input: "./src/index.ts",
    output: [{
      dir: "./dist/esm",
      format: "esm",
      exports: "named",
      preserveModules: true,
      sourcemap: true,
      entryFileNames: "[name].mjs",
    }, {
      dir: "./dist/cjs",
      format: "cjs",
      exports: "named",
      preserveModules: true,
      sourcemap: true,
      entryFileNames: "[name].cjs",
    }],
    plugins: [ts()]
  }
]

export default config
```

**Comment by MartinJohns** [comment]
Works just fine on the playground: [Playground link](https://www.typescriptlang.org/play?target=99&lib=lib.esnext.d.ts&ts=5.3.0-dev.20230902#code/PTAEAEBsEsCMC5QFMDOA7JAPALgWAFAEDGA9mitqAOZLYAi0KADiSgIayRKgC8oAFAEpeAPgEBvUAG0AygE8AtrBKQAdABNGLFEgC6iIaNDiAvqBOCCBAK4poaKqE3NWHLr2q0GL9pyRCAbgIgA)

Are you sure it's not an issue with rollup? Does it happen too when you compile without rollup, just by using `tsc`?

**Comment by hazae41** [comment]
> Works just fine on the playground: [Playground link](https://www.typescriptlang.org/play?target=99&lib=lib.esnext.d.ts&ts=5.3.0-dev.20230902#code/PTAEAEBsEsCMC5QFMDOA7JAPALgWAFAEDGA9mitqAOZLYAi0KADiSgIayRKgC8oAFAEpeAPgEBvUAG0AygE8AtrBKQAdABNGLFEgC6iIaNDiAvqBOCCBAK4poaKqE3NWHLr2q0GL9pyRCAbgIgA)

I have the following error on the playground link you submitted: "Unexpected identifier 'disposable'"

> Are you sure it's not an issue with rollup? Does it happen too when you compile without rollup, just by using `tsc`?

You're right, it works when using `tsc --project tsconfig.json --outdir dist` with both ESNext and ES2022

Maybe this has to do with `tslib` or `@rollup/plugin-typescript`?

**Comment by fatcerberus** [comment]
> I have the following error on the playground link you submitted: "Unexpected identifier 'disposable'"

That's a runtime `SyntaxError` thrown by the browser, because it doesn't natively support `using`.  There are no compile-time errors.

**Comment by MartinJohns** [comment]
This sounds like @hazae41 is trying to run the compiled code in an environment that does not support `using` and is confusing runtime errors with a compile time error. Under ES2022 it's polyfilled, under ESNext not.

**Comment by hazae41** [comment]
> This sounds like @hazae41 is trying to run the compiled code in an environment that does not support `using` and is confusing runtime errors with a compile time error. Under ES2022 it's polyfilled, under ESNext not.

No, this is a compile-time error when compiling with Rollup:

```bash
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/node/mods/index.ts (9:10)
 7: }
 8: export function test() {
 9:     using example = window;
              ^
10: }
```

**Comment by fatcerberus** [comment]
That's a rollup issue, then.  You need to report it there, if you haven't already.

**Comment by MartinJohns** [comment]
According to the comment in your other issue Rollup simply does not support `using` yet. This is completely unrelated to TypeScript.

https://github.com/rollup/rollup/issues/5113#issuecomment-1700305458

**Comment by hazae41** [comment]
> That's a Rollup issue, then. You need to report it there, if you haven't already.

I'm not sure this is a Rollup issue or TypeScript issue, I already made an issue there too

> According to the comment in your other issue Rollup simply does not support `using` yet. This is completely unrelated to TypeScript.
> 
> [rollup/rollup#5113 (comment)](https://github.com/rollup/rollup/issues/5113#issuecomment-1700305458)

No, it **does** support "using" when targetting ES2022, which is why it makes me think it's probably a TypeScript issue

**Comment by MartinJohns** [comment]
> No, it **does** support "using" when targetting ES2022, which is why it makes me think it's probably a TypeScript issue

When you target ES2022, TypeScript will emit downlevel code for runtimes that don't support `using` yet, so the resulting JavaScript code does not contain any `using` anymore. As far as I understand Rollup is using this emitted JavaScript code, so it doesn't have any issue parsing the code, since there's no `using`.

When you target ESNext, TypeScript will emit the `using`, so the JavaScript code ends up containing `using` and Rollup fails to parse it.

**Comment by hazae41** [comment]
> > No, it **does** support "using" when targetting ES2022, which is why it makes me think it's probably a TypeScript issue
> 
> When you target ES2022, TypeScript will emit downlevel code for runtimes that don't support `using` yet, so the resulting JavaScript code does not contain any `using` anymore. As far as I understand Rollup is using this emitted JavaScript code, so it doesn't have any issue parsing the code, since there's no `using`.
> 
> When you target ESNext, TypeScript will emit the `using`, so the JavaScript code ends up containing `using` and Rollup fails to parse it.

Thanks, that's probably what's happening, I'm closing this issue for now
