### ISSUE TITLE
Promise then/awaited nested unwrap inconsistency

### ISSUE THREAD

**Issue by maximilianMairinger** [microsoft/TypeScript#55612]
### 🔎 Search Terms

Promise then awaited inconsistency await nested

### 🕗 Version & Regression Information

- This changed between versions v5.3.0-dev.20230902 and 3.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230902#code/C4TwDgpgBAonUF4oAUBOB7AtgSwM4QB40s9DdhVsA7AcwD46AoRgGwmCggC5Y5mAKAIa4QVAMZR+ASkR0oAb0ZRlUMeirlOEaEkEB3Qdg4QlKgPRmooSOgBmUcpVqMAvlOnMIAOmAALCFT8-NoQMghyiipQFlbgEHYoGDj4BI7U9K5SjEA

### 💻 Code

```ts
type EEE = Promise<Promise<string>>

let e: EEE

(async () => {
    const eee = await e
    // typeof string
})()

e.then((eee) => {
    // typeof Promise<string>
})
```

### 🙁 Actual behavior

When unwrapping nested promises with .then the resulting type is not deeply unwrapped, just the first layer.

### 🙂 Expected behavior

Similar to other methods of unwrapping promises (e.g. `await`) it should deeply unwrap the value nested inside two or more promises

### Additional information about the issue

Nested promises are automatically unwrapped all at once at runtime. The `Awaited` type reflects this. Typing for the runtime code `Promise.resolve(Promise.resolve("string"))` as well as the `await` keyword resolve this correctly.

It is possible however to construct a type as follows: `Promise<Promise<string>>`. This should be resolved to string using all methods to unwrap promises. This does not work for then currently. The issue is clearly apparent in lib.es5.d.ts.

**Comment by fatcerberus** [comment]
Duplicate or related to https://github.com/microsoft/TypeScript/issues/47593 and/or https://github.com/microsoft/TypeScript/issues/52764.
