### ISSUE TITLE
Update library to use `declare class`

### ISSUE THREAD

**Issue by dr-vortex** [microsoft/TypeScript#55611]
Currently, declarations for classes consist of an interface for the instance and a `declare var` for the static side. This is a convoluted way of approaching classes. Instead, Typescript should use `declare class`, which clarifies the type (since the class is known to be a class, rather than a `var` object which has a new method and prototype property) and simplifies the definition (only one declaration).

### Sample Code

```TypeScript
// old
interface Class {
	method(): void;
	property: number;
}

declare var Class: {
	prototype: Class;
	new(arg: string): Class;
	staticMethod(): void;
}

//new
declare class Class {
	method(): void;
	property: number;
	constructor(arg: string);
	static staticMethod(): void;
}
```

**Comment by andrewbranch** [comment]
> since the class is known to be a class

Which ones specifically are known to be classes?

<img width="418" alt="image" src="https://github.com/microsoft/TypeScript/assets/3277153/7e8803b0-ccf3-429d-9187-a62039d36896">

<details><summary>(text version)</summary>

```
❯ node
Welcome to Node.js v20.3.1.
Type ".help" for more information.
> Number
[Function: Number]
> class Foo {}
undefined
> Foo
[class Foo]
> Buffer
[Function: Buffer] {
  poolSize: 8192,
  from: [Function: from],
  copyBytesFrom: [Function: copyBytesFrom],
  of: [Function: of],
  alloc: [Function: alloc],
  allocUnsafe: [Function: allocUnsafe],
  allocUnsafeSlow: [Function: allocUnsafeSlow],
  isBuffer: [Function: isBuffer],
  compare: [Function: compare],
  isEncoding: [Function: isEncoding],
  concat: [Function: concat],
  byteLength: [Function: byteLength],
  [Symbol(kIsEncodingSymbol)]: [Function: isEncoding]
}
```
</details>

More importantly, this pattern is super important for some weird compatibility hacks implemented in `@types/node` (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59905)

**Comment by dr-vortex** [comment]
@andrewbranch I was thinking more in the DOM lib, since it doesn't share many types with node.

**Comment by andrewbranch** [comment]
[It increasingly does.](https://nodejs.org/api/webstreams.html) And anyway, they look the same:

<img width="216" alt="image" src="https://github.com/microsoft/TypeScript/assets/3277153/c38ebae0-8941-4d00-aafd-862c084b165a">
