### ISSUE TITLE
URL: Type 'never' has no construct signatures after upgrading from `5.1.6` to `5.2.2`

### ISSUE THREAD

**Issue by amir-ziaei** [microsoft/TypeScript#55623]
### 🔎 Search Terms

"TS2351", "Type 'never' has no construct signatures", "URL", "This expression is not constructable", "URL.canParse"

### 🕗 Version & Regression Information

- This is a compiler error
- This changed between versions 5.1.6 and 5.2.2
- This is the behavior in every newer than 5.1.6 version I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230903#code/GYVwdgxgLglg9mABDAzgNQIYBsYBMCqASgDIAUAthgJ4BGApvgE5YBciKUjMYA5gJRsacOFjoYkAbwBQiZMESkA5BHEAFDIxR1FyJEWJ9E02bMZ0oIRnpIA6FWHWa6FavSZY+AbhmIAvj84qIx9ZMDoAd0R9F1oGZi8QxDMLK0ROEDpvWV9EFSgIAAtgkyTzSyRgbC0svylfIA

### 💻 Code

```ts
function isValidURL(maybeUrl: string): boolean {
  if ('canParse' in URL) {
    return URL.canParse(maybeUrl);
  }
  try {
    new URL(maybeUrl); // error TS2351: This expression is not constructable. Type 'never' has no construct signatures.
    return true;
  } catch {
    return false;
  }
}
```

### 🙁 Actual behavior

A compiler error is thrown in the version >= 5.2.2
```
error TS2351: This expression is not constructable.
  Type 'never' has no construct signatures.

16     new URL(maybeUrl);
```

### 🙂 Expected behavior

Not to get a compiler error like in version 5.1.6 and below

### Additional information about the issue

- I don't get any LSP errors for this problem in my vscode editor (latest version as of Sept 4, 2023)
- In `5.1.6` I cast URL to have `canParse`. Since 5.2.2 comes with `canParse` I got rid of the casting. Here's [a playground against 5.1.6 without errors](https://www.typescriptlang.org/play?ts=5.1.6#code/GYVwdgxgLglg9mABDAzgNQIYBsYBMCqASgDIAUAthgJ4BGApvgE5YBciKUjMYA5gJRsacOFjoYkAbwBQiZMESkA5BHEAFDIxR1FyJEWJ9E02bMZ0oIRklL7EGFEcQqw6zXTalLrdp248ANIg09nQA-GwcXLyGALwAfEHCouKIAL58AHTOrloU1PRMWHwA3DJpZZxURmWyYHQA7oj6ebQMzCU1iGYWVoicIHSlsqlOGFAQABbVJl3mlkjA2FpD5alAA).

**Comment by MartinJohns** [comment]
This is working as intended. Since 5.2 the type `URL` **always** has a `canParse` member, so according to the type system your check is always true. That means outside your check `URL` is narrowed to `never`, and `never` can't be constructed.

**Comment by amir-ziaei** [comment]
> This is working as intended. Since 5.2 the type `URL` **always** has a `canParse` member, so according to the type system your check is always true. That means outside your check `URL` is narrowed to `never`, and `never` can't be constructed.

Thanks for your prompt reply. It makes sense, but I'm still not quite sure how I am supposed to write that piece of code in `5.2` compliant way. I wanna use `canParse` if it's available in the browser (currently it's only in Firefox), but fall back to the old way otherwise.

**Comment by MartinJohns** [comment]
Since it's only supported in Firefox, it shouldn't really have been included in the type definitions.

A simple workaround is to put the check in a variable:

```typescript
  const check = 'canParse' in URL;
  if (check) { ... }
```

This will not narrow the type.

**Comment by Andarist** [comment]
I'm actually surprised that this doesn't narrow. It's an aliased condition and that should work roughly in the same was since TS 4.4 🤔 

What is also interesting is that the compiler has some logic to avoid certain kinds of errors caused by runtime checks for what is seemingly always available according to the typedefs:
https://github.dev/microsoft/TypeScript/blob/5d04803196899fab535103a5114bc9bf8d04dbd9/src/compiler/checker.ts#L41992-L41993

This feels like a very similar situation to that one but fixing it would break some basic narrowing principles that we can rely on today.

**Comment by ahejlsberg** [comment]
> I'm actually surprised that this doesn't narrow.

It doesn't because `URL` is declared using `var` and not `const`. We only narrow `const` variables based on aliased conditions.

**Comment by Andarist** [comment]
Hm, i understand why it’s a good rule for the aliased condition itself but im surprised that it matters how `URL` itself is declared. It doesnt impact the local reasoning capabilities within the function

**Comment by andrewbranch** [comment]
> Since it's only supported in Firefox, it shouldn't really have been included in the type definitions.

If someone can track down when/where/why it was added, we can revisit that decision. The compiler behavior looks ok here.
