### ISSUE TITLE
Optional types for optional/peer-optional dependencies

### ISSUE THREAD

**Issue by nscarcella** [microsoft/TypeScript#55628]
### 🔍 Search Terms

`optional dependencies` `peer-optional dependencies` `type of imported optional dependencies`

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I'm working a lot with plugins lately and, thus, rely a lot on optional peer dependencies.
One thing I'm constantly struggling with is that the potential absence of optional dependencies (in my case, usually peer dependencies with the `optional` metadata) is not reflected on  `import` statements.

I would very much like to see imports propagating an `| undefined` to the types of optional deps:

```ts
import regularDep, { aFeature } from 'some-regular-dep'   // This would remain the same
import optDep from 'some-opt-dep'   // If the default export of some-opt-dep is declared to be of type T, optDep would be of type T | undefined
import { aFeature } from 'some-opt-dep' // If aFeature is declared to be of type T, the imported aFeature would be of type T | undefined
```

### 📃 Motivating Example

Any code that needs to handle optional dependencies need to do some runtime check to ensure that the dependency is available. It would be nice to reflect that absence possibility in the code to prevent accidentally skipping said check.

 

### 💻 Use Cases

1. What do you want to use this for?
>  Any piece of code with optional or peer-optional dependencies
2. What shortcomings exist with current approaches?
> The potential absence of optional dependencies is ignored by the type checker
3. What workarounds are you using in the meantime?
> No workaround needed, but current solution is error prompt

**Comment by andrewbranch** [comment]
In what runtime would

```ts
import optDep from 'some-opt-dep'
```

result in `optDep` being undefined if `'some-opt-dep'` is not resolvable? Every runtime or bundler I know of would simply crash here.

**Comment by nscarcella** [comment]
@andrewbranch that's a fair point. Probably most (or all) runtimes would force you to use `require` or dynamic imports and try-catch the exception.

But this, at least to me, feels a bit off. It forces an heterogeneous notation and it is quite error prompt. Besides, I have to very expressly declare a dependency as *optional* so that dependency not existing is rather expectable. If this was a parameter instead of an import, it would be the textbook usecase for a `?` type.

I believe there might be a solid case for compiling imports of optional dependencies as `const`s initialized with a dynamic import that handles the error and returns `undefined` instead. I don't think that falls under the rule of not generating different runtime code based on types, since no typing info is really used (this could be done directly in JS).

I wouldn't mind to have to use a compiler option or using a particular target/module to enable this and would make the use of optional dependencies way more safe and clean.

Let me hear your thoughts

**Comment by andrewbranch** [comment]
That’s out of scope via design goal 7:

> Preserve runtime behavior of all JavaScript code.

Import declarations are real JavaScript code, so their semantics must be preserved. I think writing the dynamic import yourself is the way to go.

**Comment by nscarcella** [comment]
@andrewbranch I understand. Thanks.
