### ISSUE TITLE
Language Server auto-import doesn't see default export if export { foo as default }

### ISSUE THREAD

**Issue by switz** [microsoft/TypeScript#55629]
### 🔎 Search Terms

getLocalSymbolForExportDefault
export default as auto-import

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it's not a compilation issue, but rather a language server issue. It does seem like it has existed for quite some time.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230904&ssl=2&ssc=1&pln=2&pc=26#code/MYewdgzgLgBAZiEMC8MCMBuAUAUwB4AOIATrAN7yIwCGEMAJjnNQK4A2sAvkA

### 💻 Code

```ts
const driver = 1;
export { driver as default };
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/990166/04216997-6ac9-4bd8-8c16-327a4f0748e2)

The default import is not reflected.

![Screenshot 2023-09-04 at 14 02 44](https://github.com/microsoft/TypeScript/assets/990166/0462094a-384a-4931-b02c-a0648bf9982b)

If I manually change the type definitions to:

```
export default driver
```

![Screenshot 2023-09-04 at 14 03 33](https://github.com/microsoft/TypeScript/assets/990166/8424b2ab-32ad-459e-ae9c-471337b08874)

it works.

![Screenshot 2023-09-04 at 14 03 19](https://github.com/microsoft/TypeScript/assets/990166/b2aa8c48-fe66-4e1d-bc9a-5036bed9d7dd)

### 🙂 Expected behavior

I'd expect the ts language server (`getLocalSymbolForExportDefault`) to see `export { foo as default }` as default auto-imports

### Additional information about the issue

Relevant issues where I was directed from (esbuild): https://github.com/evanw/esbuild/issues/3363#issuecomment-1704300876

My personal library issue: https://github.com/switz/driver/issues/6

tsup issue: https://github.com/egoist/tsup/issues/985

**Comment by andrewbranch** [comment]
> I was unable to test this on prior versions because it's not a compilation issue, but rather a language server issue

The language server is part of TypeScript. The version is listed (or can be seen on hover/click) in VS Code’s status bar, and you can install and select different versions. Are you sure you’ve tried with the latest TypeScript? Someone recently submitted a fix for this. https://github.com/microsoft/TypeScript/pull/54871

**Comment by switz** [comment]
I'm running 5.1.6
![Screenshot 2023-09-05 at 19 49 38](https://github.com/microsoft/TypeScript/assets/990166/306ca1b7-962c-4ee3-9d11-9e4e87ceecce)

**Comment by switz** [comment]
upgraded to 5.2.2 and its working again. sorry for the false alarm!
