### ISSUE TITLE
Autocomplete parenthesis after type assertion

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#5563]
Is it possible if TS could autocomplete type assertion?

When typing this:
```typescript
html as HTMLAreaElement)
```
it autocompletes to this:
```typescript
(html as HTMLAreaElement)
```

Really painful to go back and type that left parenthesis.

**Comment by mhegazy** [comment]
TypeScript does not do any thing now with brace completion. the brace completion you get in sublime/atom/vscode are built in to the editors and TS is not contributing to them. we have an issue tracking adding support for it in VS in #1484, i expect when we do this we will add some service APIs around it. this issue would be something we should revisit then.
