### ISSUE TITLE
Triple slash directive is inconsistently added to declaration files

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#55636]
### 🔎 Search Terms

declaration emit triple slash references

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ 

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEBMFMGMBsCGAnRAXAlgewHYC5Q1kBXaAWACgQIAzDeaHRAW2gOADoBnZWYHLDAD6zQcQZdg4NAE8ADtEkCYwDDhgAPDpA5oulGAhTRQoyOJMAiYsniXQAb0qgXoaBrlZkaUEa5dQAFVbRwBfZ1d3T29QGmIcWExcUDkULmgACgBKAmD4AG5QSnCqMHA6BiZWAmIuRABzaF19CgxmaJ8HFLSTUNjkLGZQa1tLfMoorx9YXC4fNAALNXq8No6MkbssjjzQAF5u5HTswsoQSZiZnDnCJZx6-cPjrMLQagBJGkJ5EwwAtRo0GQyGgkFAiDe1EgGBBiQwADdfgFEJAYJAgA

### 💻 Code

```ts
// @declaration: true
// @filename: /.src/node_modules/@types/node/index.d.ts
declare module "url" {
    export class Url {}
    export function parse(): Url; 
}
// @filename: usage.ts
import { parse } from "url";
export const thing:import("url").Url = parse(); 
//export const thing = parse();  // If type is inferred a /// directive is added
```

### 🙁 Actual behavior

If the type of the variable is inferred a reference directive is added (`/// <reference types="./.src/node_modules/@types/node">`). If the type is written in code, the directive is not added

### 🙂 Expected behavior

The directive is either added in both cases or not at all. 

### Additional information about the issue

Discovered while working on isolated declarations. Generally we will need to error if the declarations need to add reference directives if they not already specified in code.

**Comment by andrewbranch** [comment]
The bug workbench doesn’t seem to be showing the correct declaration file output. Can you paste the exact output? Also, can you ensure this isn’t specific to `moduleResolution: classic`?

**Comment by dragomirtitian** [comment]
@andrewbranch It might be a bit hard to see but it does. There is a bug in the way the file is formatted in HTML where reference directives are interpreted as HTML tags:

![image](https://github.com/microsoft/TypeScript/assets/8193316/2c541362-3109-4cad-a31e-3db15f13a046)

![image](https://github.com/microsoft/TypeScript/assets/8193316/d89882e2-5bc3-46b3-885d-d7f52ebc4c7d)

**Comment by andrewbranch** [comment]
Seems like the correct behavior is to include the triple slash in both cases since `"url"` is an ambient module declaration and won’t be resolvable if the declaring file isn’t included.

**Comment by andrewbranch** [comment]
We’re just generally missing these triple-slash references for any reference to an ambient module that was written in the source code. The smallest repro is

```ts
export { parse } from "url";
```

Fixing this is going to add a line to a huge number of .d.ts files in the wild, but I don’t know of any good reason why these hand-written imports and exports should be treated any differently than other referenced globals inferred import types.
