### ISSUE TITLE
Can the checkNullSafety method for class objects be automatically generated?

### ISSUE THREAD

**Issue by Silentdoer** [microsoft/TypeScript#55633]
### 🔍 Search Terms

Can the checkNullSafety method for class objects be automatically generated to detect whether the attribute values of the runtime class object comply with the definition after empty security is enabled, such as let foo=JSON. parse (ioInput); Let ok=foo. checkNullSafety(), there is a non empty field called prop1 in the Foo class. If the prop1 obtained after JSON. parse is null or undefined, foo. checkNullSafety() will return false

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

none

### 📃 Motivating Example

check null safety

### 💻 Use Cases

let foo: Foo = JSON.parse(ioInput);
if (!foo.checkNullSafety()) {
  throw new Error("input is not corrent JSON string");
}

**Comment by jcalz** [comment]
I'm not sure what you're asking for exactly but it's clearly some sort of runtime feature, which means that you should not have checked this checkbox

> - [x] This isn't a runtime feature

Which implies that this will be declined. TypeScript is out of the business of adding runtime functionality. If you want to see something like this happen, it needs to be implemented first in JavaScript.

**Comment by MartinJohns** [comment]
Damn, those are a lot of search terms.

**Comment by Silentdoer** [comment]
> I'm not sure what you're asking for exactly but it's clearly some sort of runtime feature, which means that you should not have checked this checkbox
> 
> > * [ ]  This isn't a runtime feature
> 
> Which implies that this will be declined. TypeScript is out of the business of adding runtime functionality. If you want to see something like this happen, it needs to be implemented first in JavaScript.
> 
> So you should close this issue. (If you don't, the TS team will almost certainly close it for you, but you can save them the effort by doing it yourself.)

This is not a runtime feature, but rather a hope that typescript can automatically generate a check for whether the property values of the class object comply with the non null/undefined definition when compiling the relevant classes after null safety is enabled

**Comment by MartinJohns** [comment]
> hope that typescript can automatically generate a check method

Which would be in violation of these two points:

> This could be implemented without emitting different JS based on the types of the expressions
> This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
