### ISSUE TITLE
TypeScript in keyword

### ISSUE THREAD

**Issue by ghosh-rounak** [microsoft/TypeScript#55642]
### 🔎 Search Terms

TypeScript in keyword

### 🕗 Version & Regression Information

// Typescript compiler not reporting the below syntax error during compile time and it happens in all versions of typescript

class Test {
 id:number=0;
}

function t1(test:Test) {
  return "id" in Test; // this should be the object test and not class Test but not detected as error by compiler
}

console.log(t1(new Test()));

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTAEBUE8AcFMGcDGAnAltALqRB7AttKgDazKgB2OWys0OyGq5A5qBgBaygBGsROAd1Clk9UABMArmhbZ8hEm1R5YAWABQiIgEN48CAiwBvDaFTiAXOUl5eyALwAGANwaAvho0AzSeUSMccjYARgAKDEMLcEMASlATdVBQGgxpIIAic3SzIOj4DGdQEDZ2VH14dhxJInEeLg4uHG4AK1h-NkNQbXJayiwtXX08rG5JLD6JWAj-WFrdYWRRZHdPTUD4HBIAOn5mcLDyWCFh0Jiz13VVoA

### 💻 Code

// Typescript compiler not reporting the below syntax error during compile time and it happens in all versions of typescript

class Test {
 id:number=0;
}

function t1(test:Test) {
  return "id" in Test; // this should be the object test and not class Test but not detected as error
}

console.log(t1(new Test()));

### 🙁 Actual behavior

// Typescript compiler not reporting the below syntax error during compile time and it happens in all versions of typescript

class Test {
 id:number=0;
}

function t1(test:Test) {
  return "id" in Test; // no error detected by tsc compiler in this line
}

console.log(t1(new Test())); // returns false and code compiles fine

### 🙂 Expected behavior

// Typescript compiler should report the below error

class Test {
 id:number=0;
}

function t1(test:Test) {
 // the below line should be reported as error "in keyword not applicable on class Test . Did you mean the object test ?"
  return "id" in Test;
}

console.log(t1(new Test())); // code should not compile

### Additional information about the issue

// Incorrect typescript code

class Test {
 id:number=0;
}

function t1(test:Test) {
 // the below line should be reported as error "in keyword not applicable on class Test . Did you mean the object test ?"
  return "id" in Test;
}

console.log(t1(new Test())); // code should not compile

// ---------------------------------------------------------------------------------------------------------------------------

// Correct version of the above code snippet : =>
class Test {
 id:number=0;
}

function t1(test:Test) {
  return "id" in test; // this is fine as test is object
}

console.log(t1(new Test()));  // returns true which is fine

**Comment by MartinJohns** [comment]
This is working as intended. The `in` operator can be used to check for properties existence that the type system does not directly know about. So limiting the option to check only for known keys is not practical, but I don't see any other option to prevent the issue you're seeing.

**Comment by ghosh-rounak** [comment]
The "no unused parameters rule" only says that test parameter is unused in the code below

function t1(test:Test) {  // test unused
// the below line should be reported as error "in keyword not applicable on class Test . Did you mean the object test ?"
return "id" in Test;
}

Can a new flag be introduced in tsconfig.json which will report syntax error if the in keyword is used on invalid things . Like in the above example in keyword is used on the class Test instead of the object test , so tsconfig should report that error during compile time because typescript is supposed to catch errors during compile time and not runtime.

Please look into the below correct and incorrect examples from typescript playground to understand the issue better :

Correct Example :=>

https://www.typescriptlang.org/play?#code/PTAEGEHsCdoUwMYBdRwB4EMC2AHANnAFCEJ4YDO5oAgjvnKAN6GiuhIVICeAXAEaRIBDADtQAXnbQArnADcxNqACW5WvQAqnLgAoAlP0HCRzJUvhJp0MUgAWqgHQdy3BUoC+hTyTKVQAIVEgphY2Z25DIThRCVAAMww8cnlFNlVAkSCtF10DASjRUzNWCysbe3InbTc2T09uHAYAMRllFEl1AlAAHwCgzOI46RFkZUgxVRbpNs64HTjWpB4ptoMF6ZRVGjoCIpK4S2tQACJVWezuY5UxdbbQEFAEGHhkPC5QaWSAE2vQAGs4FwAO4wH7jUCQPgAK0QKFuSC8g2Go3BCFsiD+KyQ80Wy0Wej2KjiOkmi1mOI2egJoWKTxE5CiDjwkAA5joAAazFRUcLvSQAEkY8IcZx2cAuuXc7L0NNA7jgSTghKUdIZBCZrI5GWCW15sUFwvS-QwEv0UplHkRJHRCExix0IjgQO29H0enuYBEkFQsBgoHR8FAfEQGE+DEgcUez1hH3IGBZ4cjyjEAOBoNAGAEADc4EA

Incorrect Example :=>

https://www.typescriptlang.org/play?#code/PTAEEkDsGMHsCd4FNoBdRIB4EMC2AHAGyQCgTpDsBnK0AQXyKVAG8TQPRVrUBPALgBGsWMWyRQAXi7wArkgDcZTqACWVBkwAqPXgAoAlEJFjIbFSuSpZ8CagAW6gHTcqfJSoC+Jb+Uo1QACFxENZ2Tlc+Y1EkcSlQADNsQipFZU51YMgQnTd9I2EY8XMLDisbO0cqF10PTm9fPnxmADE5VXRpTWJQAB8gkOyyBNkYVFVYCXU22Q7upD0E9tR+GY6jJdn0dXpGYhKOEFBcdW4Aa2ZVSuZBJEJYAHdQQivmSFh0ZHwEVCQAE1A1AwiAQoEEvFAcAIqmI8CcoHChzA2HQYjcXHszCh+BhSHgoCo9lgskIAN+hEIGJRagkF14DwQAJ273Q2D2qmg2EEPUmkP8tHmCJUR1QVGgBKJJLJd0pqFggL2EKuoDpDPgAN5cVgggAVihWZAASzQLyKNQqIjQOVbKAAETqea5Pi2mm7JigI7WyC0JIpS7e37YDUJSGwaE9PHwBA+YajNATCTQTHQM5rVCLZarZYGA5qBJ6abLeYZrYGHOWlRwb0xJz3ADmegABoKdpEIdIACQsTYdJwOvZIJ35TyNgyWzx3VK5yuTKg1+tNrKhVu6eJdnuoPtUJfZIeGEdjrwx8jJ1PLPSQJBPYtlj1gOR2VS4ZhJGE2Zj2NnNb2A2gOZhcrAABuWJhjiPTjM+wJRvixp-EgvxoP8YIQqK0BAA

**Comment by fatcerberus** [comment]
Except it is not a syntax error.  Checking for `"id" in Test` is a perfectly fine thing to do at runtime (i.e. testing for existence of static properties on the class), it's just not what you wanted to do in this case.

**Comment by ghosh-rounak** [comment]
> Except it is not a syntax error. Checking for `"id" in Test` is a perfectly fine thing to do at runtime (i.e. testing for existence of static properties on the class), it's just not what you wanted to do in this case.

Yes its correct , **in keyword can also be used on class to check if static properties or methods exist in the class**. Actually this was not mentioned in the typescript documentation. I think this issue can be closed.

**Comment by MartinJohns** [comment]
> Actually this was not mentioned in the typescript documentation.

It doesn't need to be. This is purely a JavaScript functionality. The `in` operator can be used on values, and classes are values.
