### ISSUE TITLE
tsconfig watchOptions.excludeDirectories and excludeFiles resolve relative to cwd instead of tsconfig

### ISSUE THREAD

**Issue by dmichon-msft** [microsoft/TypeScript#55656]
### 🔎 Search Terms

watchOptions, working directory, cwd, tsconfig, excludeDirectories, excludeFiles

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about watchOptions

### 💻 Code

```ts
const path = require('node:path');
const ts = require('typescript');

const tsConfigPath = // Some path to a valid tsconfig with watch options defined.

const parsedConfigFile = ts.readConfigFile(tsConfigPath, sys.readFile);
const basePath = path.dirname(tsConfigPath);
const sys = {
  ...ts.sys,
  getCurrentDirectory: () => basePath // ts.sys.getCurrentDirectory() returns the memoized value of process.cwd() as of when `require('typescript')` executed
};
const tsconfig = ts.parseJsonConfigFileContent(
  parsedConfigFile.config,
  {
    fileExists: sys.fileExists,
    readFile: sys.readFile,
    readDirectory: sys.readDirectory,
    useCaseSensitiveFileNames: true
  },
  basePath,
  /*existingOptions:*/ undefined,
  tsConfigPath
);

const compilerHost = ts.createWatchCompilerHost(tsconfig.fileNames, tsconfig.options, sys, undefined, undefined, undefined, tsconfig.projectReferences, tsconfig.watchOptions);
const watchProgram = ts.createWatchProgram(compilerHost);
```

### 🙁 Actual behavior

Typescript evaluates `watchOptions.excludeFiles` and `watchOptions.excludeDirectories` relative to the value of `process.cwd()` as of the moment the ~~`require('typescript')` call evaluated.~~
Edit: the value gets memoized upon the first invocation of `ts.sys.getCurrentDirectory()` (which is captured via closure and therefore not overrideable).

### 🙂 Expected behavior

The `watchOptions.excludeFiles` and `watchOptions.excludeDirectories` patterns are evaluated relative to the folder containing the tsconfig file.

### Additional information about the issue

The expressions here evaluate `excludeFiles` and `excludeDirectories` using a value of `basePath` that is a memoized invocation of `process.cwd()` at the moment `ts.sys` was created:
https://github.com/microsoft/TypeScript/blob/6cc605fcfe66118eafb50b2fdbd386da7e419795/src/compiler/sys.ts#L866-L869

This interferes with the ability to run multiple instances of the TypeScript compiler in watch mode in the same process concurrently, or even to run the compiler in watch mode via the API in a root folder other than the current process working directory (and changing the current working directory doesn't work either).

**Comment by sheetalkamat** [comment]
exclude files and exclude directories are marked as file path so when those options are parsed and generated as object, the evaluated `excludeFiles` and `excludeDirectories` are already based relative to tsconfig and work as intended,

Here is what i tried with cwd as `c:/temp/test`
```js
const path = require('node:path');
const ts = require('typescript');

const tsConfigPath = "c:/temp/test/abc/tsconfig.json";

const parsedConfigFile = ts.readConfigFile(tsConfigPath, ts.sys.readFile);
const basePath = path.dirname(tsConfigPath);
const sys = {
  ...ts.sys,
  getCurrentDirectory: () => basePath // ts.sys.getCurrentDirectory() returns the memoized value of process.cwd() as of when `require('typescript')` executed
};
const tsconfig = ts.parseJsonConfigFileContent(
  parsedConfigFile.config,
  {
    fileExists: sys.fileExists,
    readFile: sys.readFile,
    readDirectory: sys.readDirectory,
    useCaseSensitiveFileNames: true
  },
  basePath,
  /*existingOptions:*/ undefined,
  tsConfigPath
);

console.log(JSON.stringify(tsconfig.watchOptions));
```

The result was: 
```
{"excludeFiles":["c:/temp/test/abc/file.ts"]}
```

```jsonc
// c:/temp/test/abc/tscofig.json
{
  "compilerOptions": {
    "noEmit": true
  },
"watchOptions": { "excludeFiles": ["file.ts"] }
}
```

If you are running into issues we need complete repo with tsocnfig disk path, contents and test where you are running into issues.

**Comment by dmichon-msft** [comment]
Yep, closing this as user error.

Only repros if the caller injects a relative pattern into the `watchOptions.excludeFiles` or `watchOptions.excludeDirectories` after tsconfig parse.

This investigation came about from me trying to track down all the various places I needed to override the current directory, and finding one where I couldn't. I didn't look quite far enough to realize that although the value is provided, it doesn't actually end up getting used in practice.

At most it might be worth removing `getCurrentDirectory()` from this API and having it throw if the input pattern is relative.
