### ISSUE TITLE
__spreadArray does not support DOMTokenList

### ISSUE THREAD

**Issue by yanhaijing** [microsoft/TypeScript#55660]
### 🔎 Search Terms

typescript classlist.values to array

### 🕗 Version & Regression Information

- This changed between versions typescript 5.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=1#code/GYVwdgxgLglg9mABBANgQwM4YHJoLYCmGAFASgFyICiKBhYUAlJRlAE4xgDmA2gLqIA3gChEiNgSgg2SHgDoFZOakwYAMjFZyAbmhQgixRnwDcwgL5A

### 💻 Code

`[...el.classList.values()]` can be executed normally in the chrome browser.

I have the following code:

```ts
function classNames(el: Element): string[] {
  return [...el.classList.values()];
}
```

The compiled code for typescrpt is as follows(target = es5):

```js
"use strict";
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
function classNames(el) {
    return __spreadArray([], el.classList.values(), true);
}
```

the `[...el.classList.values()]` is replace to `__spreadArray([], el.classList.values(), true)` .

Now you have an empty array, because of `DOMTokenList.length` is `undefined`.

### 🙁 Actual behavior

`[...el.classList.values()]` always get an empty array.

### 🙂 Expected behavior

`[...el.classList.values()]` The behavior of this code stays with the browser all the time.

**Comment by yanhaijing** [comment]
Because of typescript, I'm ditching classList for className.

```ts
// className
function classNames(el: Element): string[] {
  return el.className.split(/\s+/).filter(Boolean);
}

// classList
function classNames(el: Element): string[] {
  return [...el.classList.values()];
}
```

**Comment by nmain** [comment]
> Search Terms
> empty

You're supposed to search for existing issues first before opening a new one.

You can get the desired behavior by enabling the `downlevelIteration` compiler flag.  My search terms were "array downlevel length".

**Comment by yanhaijing** [comment]
@nmain Many thanks to you. When the `downlevelIteration` flag is turned on, the code works normally.

Here is a short summary, **Note** that this relies on the browser to implement `classList` and `Symbol.iterator`.

the source code:

```ts
function classNames(el: Element): string[] {
  return [...el.classList.values()];
}
```

The compiled code for typescrpt is as follows(**downlevelIteration=false**): 

```js
"use strict";
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
function classNames(el) {
    return __spreadArray([], el.classList.values(), true);
}
```

The compiled code for typescrpt is as follows(**downlevelIteration=true**): 
```js
"use strict";
var __read = (this && this.__read) || function (o, n) {
    var m = typeof Symbol === "function" && o[Symbol.iterator];
    if (!m) return o;
    var i = m.call(o), r, ar = [], e;
    try {
        while ((n === void 0 || n-- > 0) && !(r = i.next()).done) ar.push(r.value);
    }
    catch (error) { e = { error: error }; }
    finally {
        try {
            if (r && !r.done && (m = i["return"])) m.call(i);
        }
        finally { if (e) throw e.error; }
    }
    return ar;
};
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
function classNames(el) {
    return __spreadArray([], __read(el.classList.values()), false);
}

```
