### ISSUE TITLE
typeof widens type

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#55663]
### 🔎 Search Terms

typeof narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUiCGAnA5gLkTBAFsAjAU20QEpEBvAKEUQgQGcplEBeRKAJ4AHCnGBY8AbkYBfRkA

### 💻 Code

```ts
function foo( arg: number ) {
  const f = typeof arg;
}
```

### 🙁 Actual behavior

const f is `"string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function"`

### 🙂 Expected behavior

const f is `"number"`

**Comment by MartinJohns** [comment]
I can't find the issue right now, but this is definitely working as intended. And changing this would break a lot of checking code for negligible benefits.

**Comment by whzx5byb** [comment]
See also https://github.com/microsoft/TypeScript/issues/46399
