### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [microsoft/TypeScript#55679]
### 🔎 Search Terms

twitter
twitter icon
twitter logo
xtwitter

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this. hasn't

Screenshot
<img width="960" alt="Screenshot 2023-09-08 102935" src="https://github.com/microsoft/TypeScript/assets/91591901/78c5f71f-3b1d-4a5f-a71c-de7893d094f0">

### 🙂 Expected behavior

Twitter logo should be changed to XThe 

### Additional information about the issue

@andrewbranch 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by jakebailey** [comment]
https://github.com/microsoft/TypeScript-Website/pull/2930
