### ISSUE TITLE
Ability to emit parts of code without transpiling or type-checking = a comment to turn off TypeScript

### ISSUE THREAD

**Issue by niieani** [Microsoft/TypeScript#5567]
It would be great to have the option to emit certain code as is, without the `tsc` touching it or analyzing it.
I'd imagine it could be achieved with a simple, special comment that the TypeScript transpiler would understand, e.g.:
```ts
// normal TypeScript code...

/// <no-compile>
'whatever is here will just get copied to the output .js file, without being touched';
/// </no-compile>

// more proper TypeScript code...
```

My use case and reasoning is the following: 

I'm currently using a dual transpiling stack: 
TS -> ES6 (via TS) -> ES6 (via Babel). 

This works great, but Babel has some nice new ES2016 features that TypeScript probably won't have for a year or more. It would be great if we could write using those features, surround them with such `no-compile` comments so that only those would not get transpiled or analyzed by TS. Babel could take care of them in the next stage of transpilation pipeline.
There might be other reasonable use-cases for the ability to turn off TypeScript for a part of code.

Partially related to these, but I'd imagine this would be much simpler to implement: 
- https://github.com/Microsoft/TypeScript/issues/449
- https://github.com/Microsoft/TypeScript/issues/4691

**Comment by mhegazy** [comment]
for these files, write them separatelly and create a .d.ts for them, and do not pass in the .js files to the TypeScript compiler.

**Comment by twome** [comment]
Here is a different use-case: if the you have an extremely large and complex .d.ts file, such as one for Angular, and the file is mostly fine but has occasional small errors in them which block you from writing perfectly legitimate code. Let's assume this file is so large and so complex that finding the method that's troubling you, figuring out the syntax/structure, and properly fixing the error would be a sizeable waste of time.

You could still write `declare let angular: any` at the head of the file, but then that will disable type checking for *all* the times you reference Angular within that file, not just the few lines or particular method you care about.

Do you think that's a valid use-case?

**Comment by mhegazy** [comment]
Declaration correctness is an issue that should be solved on the producer side, in your example angular team for angular2 or definitely typed for angular1.
If the file has errors, you copy them locally, change the declarations to either stub out parts you do not care about or fixing the declarations. from the compiler perspective all errors are equal, regardless if they come from a file you wrote, or a file you acquired form definitely typed.
