### ISSUE TITLE
SuppressedError constructor should not have Error constructor overloads

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/TypeScript#55674]
### ⚙ Compilation target

esnext

### ⚙ Library

esnext

### Missing / Incorrect Definition

The `SuppressedError` constructor inherits the `ErrorConstructor`:

```ts
interface SuppressedErrorConstructor extends ErrorConstructor {
    new (error: any, suppressed: any, message?: string): SuppressedError;
    (error: any, suppressed: any, message?: string): SuppressedError;
    readonly prototype: SuppressedError;
}
declare var SuppressedError: SuppressedErrorConstructor;
```

however this spuriously adds overload signatures from `ErrorConstructor` which should not be allowed for `SuppressedError`.

### Sample Code

This overload inherited from `ErrorConstructor` should not be allowed for `SuppressedError`:

```ts
const supressedError = new SuppressedError(`This should not be an allowed signature`)
```

### Documentation Link

The spec for `SuppressedError` is [here](https://arai-a.github.io/ecma262-compare/?pr=3000&id=sec-suppressederror).

**Comment by sandersn** [comment]
From reading the spec, it looks like `error` and `suppressed` can technically be optional as well, but it's not likely to be the intended usage.
