### ISSUE TITLE
`"moduleResolution": "bundler"` incorrectly allows default imports from commonjs modules

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#55681]
### 🔎 Search Terms

moduleresolution bundler default import commonjs

### 🕗 Version & Regression Information

5.3.0-dev.20230908

##### `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "esModuleInterop": true,
    "strict": true
  },
  "include": ["main.ts"]
}
```
##### `main.ts`
```ts
import foo from './foo.cjs'

console.log('this works at runtime:', foo.default.a)
```
##### `foo.cjs`
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = { a: 1 };
```
##### `foo.d.cts`
```ts
declare const _default: {
    a: number;
};
export default _default;
```

### 🙁 Actual behavior

```
> tsc; node main
main.ts:3:43 - error TS2339: Property 'default' does not exist on type '{ a: number; }'.

3 console.log('this works at runtime:', foo.default.a)
                                            ~~~~~~~


Found 1 error in main.ts:3

this works at runtime: 1
```

### 🙂 Expected behavior

no compile error, because at runtime it's not a real default export, but rather an object with a property called `default` on it

### Additional information about the issue

changing `moduleResolution` to `nodenext` fixes the issue, but i don't think this is intended behavior because according to [the docs](https://www.typescriptlang.org/tsconfig#moduleResolution) the only thing that should be different to `node16`/`nodenext` is that it doesn't enforce the file extensions:

> 'bundler' for use with bundlers. Like node16 and nodenext, this mode supports package.json "imports" and "exports", but unlike the Node.js resolution modes, bundler never requires file extensions on relative paths in imports.

**Comment by Andarist** [comment]
This might be a duplicate of https://github.com/microsoft/TypeScript/issues/54102

**Comment by DetachHead** [comment]
dang that was fast lol
