### ISSUE TITLE
Definition file: unable refernce top namespace

### ISSUE THREAD

**Issue by MarenkovIgor** [Microsoft/TypeScript#5568]
This code (.ts) compiles fine
```
namespace A {
    export enum TestEnum { One };
}

namespace A {
    namespace B {
        namespace A {
            class Test {
                main(): TestEnum {
                    return TestEnum.One;
                }
            }
        }
    }
}
```

This code (.d.ts) 
```
declare namespace A {
    export enum TestEnum { One }
}

declare namespace A {
    namespace B {
        namespace A {
            class Test {
                main(): A.TestEnum.One;
            }
        }
    }
}
```
compiles with error `error TS2305: Build: Module 'A.B.A' has no exported member 'TestEnum'.`

**Comment by mhegazy** [comment]
what version of typescript are you using? 

I can not seem to get a repro for this on latest:
```ts
namespace A {
    export enum TestEnum { One };
}

namespace A {
    export namespace B {
        export namespace A {
            export class Test {
                main(): TestEnum {
                    return TestEnum.One;
                }
            }
        }
    }
}
```
compiling using:

```shell
> tsc --v
message TS6029: Version 1.8.0-dev.20151105

> tsc C:\test\file1.ts --d
```

produces:

```ts
declare namespace A {
    enum TestEnum {
        One = 0,
    }
}
declare namespace A {
    namespace B {
        namespace A {
            class Test {
                main(): TestEnum;
            }
        }
    }
}
```

**Comment by mhegazy** [comment]
maybe i miss understood. is this .d.ts generated by the compiler or hand authored?

if it is hand authored, then a few comments:
- using the enum value `A.TestEnum.One` in a type location is not allowed, I am guessing you actually mean `TestEnum`
- your inner namespace `A` shadows the outer `A`, so when you refer to `A` here it always means the inner one, which does not have a `TestEnum` on it.
- options: 
 1. do not qualify it, and let the compiler find it in any enclosing scope, 
 2.if this is not possible e.g. there is another TestEnum in the path and you really want the outer one use aliasing to get the correct qualification.

e.g.:
```ts
declare namespace A {
    import outerA = A;
    namespace B {
        namespace A {
            class Test {
                main(): outerA.TestEnum;
            }
        }
    }
}
```

**Comment by MarenkovIgor** [comment]
Ok, it`s not a bug. --d flag helped me.

Thank you and sorry for inconvenience.
