### ISSUE TITLE
Typescript unable to automatically infer alternate type of a type predicate when used as a generic parameter

### ISSUE THREAD

**Issue by linuslagerhjelm** [microsoft/TypeScript#55680]
### 🔎 Search Terms

Typescript predicate
typescript predicate infer opposite type generics

### 🕗 Version & Regression Information

I have tested this in version `5.1.3`, `5.2.2`, `next` and `3.3.3` (the oldest version available on Playground) and the issue is present in all those versions.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBA6gTgQzJOAeAKlCAPYEB2AJgM5T4CuAtgEYRxQA+UxwcAlvgOYB8UAvFADeAKChQAbggA25COnAQAXFHTCAvsOEAzcvgDGwNgHt8UNsQByVWnAAU45fCQpUFGnUbNWHHgEpl4makTsh0rtZ0vCJicBDA5HCmoJBGWhIAdJIycgpifPlQAERuNoXqmjr6hiZQ5MQ+9o6IoWglHkws7Fzc-mQR9NFQsfGJQVbuduK+UAD8GVmy8pBQymAIcMQQAJL4wPaZ0osKADRQAIwADL7qQA

### 💻 Code

```ts
type Wrapper<T extends number | string> = {
  valueType: T
}

function isNumber(v: Wrapper<number | string>): v is Wrapper<number> {
  return typeof v.valueType  === "number"
}

function using(v: Wrapper<number | string>): number {
  return isNumber(v) ? v.valueType : parseInt(v.valueType, 10) // This line gives the error
}
```

### 🙁 Actual behavior

The function call `parseInt(v.valueType, 10)` gives the error:

```
Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'
```

Even though the [documentation](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) states that typescript should be able to derive the alternate type after a predicate is called.

### 🙂 Expected behavior

I would have expected that typescript would be able to determine that if the type in `Wrapper<number | string>` is not a `Wrapper<number>`, then it *must* be a `Wrapper<string>`. Much like how it works for types that are not used in generics.

**Comment by jakebailey** [comment]
I'm not sure this code is safe; `Wrapper<number | string>` isn't the same thing as `Wrapper<number> | Wrapper<string>`. Swapping the former for the latter makes your code compile.

(I'm sure someone will beat me to writing up the full explanation why a la variance etc etc but it's late for me...)

**Comment by MartinJohns** [comment]
`Wrapper<number | string>` is a type with a property that can either be a `number` or a `string`, and can be changed to one of the other. `Wrapper<number> | Wrapper<string>` is either a type with a property that's always a `number`, or a type with a property that's always a `string`.

**Comment by linuslagerhjelm** [comment]
Thank you @MartinJohns for explaining this subtle difference. It seems like `TypeScript` was actually rightfully pointing out a bug in my code then. Will close this issue and go and fix my code.
