### ISSUE TITLE
Array.prototype.flat limited depth to 21

### ISSUE THREAD

**Issue by PKrasinski** [microsoft/TypeScript#55685]
### ⚙ Compilation target

ES2019

### ⚙ Library

es2019

### Missing / Incorrect Definition

Array.prototype.flat definition is supporting `depth` only up to 21.  Over 21 return wrong type.

### Sample Code

```TypeScript
const foo = [ [ ['string' ] ] ]
const flatFoo = foo.flat(22) // string[][][] should be string[]
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

**Comment by MartinJohns** [comment]
Anyone who has arrays with such a depth needs to take a very good look at itself in the mirror.
