### ISSUE TITLE
Identical comparisons cause incorrect type guard type

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#55698]
### 🔎 Search Terms

identity always equal TS2367 typeguard

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about typeguards

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAhgRgBQEMBOBzALmUgGsIEB3CASiIGcYc4I9kBvYZL5OEZDZCCwAbOgFNkAXmmCR45AB8FqAJ4AHMQj65WAQhkByBkxYHk1dp27WoSBshVTkOgNxXrXHGJhgcKAwZu1gC+wO7IthD2AF5OrsgA9AnIdAAWCGDCACbIAEYSAEQQYgBuYjgF4V4+fsgBbqGgkLCIKDAATNj4RKTkVLQpjMysHNa8-LKiEtKSk-IAZPOqGlrO+Mj6s0ZDpuaWHtyR9o6zruHW1b7+geGNNnYwyLGn+C6JyWkZ2XmFxsOVF28VzqN0a4Gg8CQqAAzF1CIMTHgFBAwABbfI4AZ-Fj7bjjARCKZSGSE+RKZaabTrTZ1bF4MwWUYHCIPBxxV7nbiXWr1W5he5RR7PNZ4N5JFLpTI5fLIIqlcoArlAnmgsLglpQmAAFjh9B2SJR6PKWP1uK4+Lm0xJcgkiwpqx0G0MdIZZo8R0eJxFQWZ3OuPq4d0OrOF8XFnylP1ldMVnmV-uAoSAA

### 💻 Code

```ts
function t1(arg: unknown): string {
    if ( false === false || typeof arg !== 'string' ) {
        const y = arg;
        return '';
    }

    const z = arg; // should be "never"
    return '';
}

function t2(arg: unknown): string {
    if ( false === false && typeof arg !== 'string' ) {
        const y = arg;
        return '';
    }

    const z = arg; // should be "string"
    return '';
}

function t3(arg: string|number): string {
    if ( false === false || typeof arg !== 'string' ) {
        const y = arg;
        return '';
    }

    const z = arg; // should be "never"
    return '';
}

function t4(arg: string|number): string {
    if ( false === false && typeof arg !== 'string' ) {
        const y = arg;
        return '';
    }

    const z = arg; // should be "string"
    return '';
}
```

### 🙁 Actual behavior

Types are incorrectly asserted when using an identity in the condition (e.g. false === false; but can be any function/variable that always returns a specific type)

### 🙂 Expected behavior

Line 18/38 should be "string", just like if the "false === false &&" weren't there, since this condition should not affect the logic.

Line 8/28 is ok(-ish), but should be "never" to be fully correct, I guess?

**Comment by andrewbranch** [comment]
What is the use case for comparing `false === false`? Is there any real example motivating the behavior you want to see?

**Comment by RyanCavanaugh** [comment]
Comparisons are basically always assumed to be possibly-true or possibly-false. In light of this, the behavior is correct

A conditional type like `T extends ValidLocations ? T : false {}` shouldn't exist in zero-order; it's not safe.
