### ISSUE TITLE
Format issues

### ISSUE THREAD

**Issue by rasul-sisutech** [microsoft/TypeScript#55694]
### 🔎 Search Terms

"autoformat" "?="

### 🕗 Version & Regression Information

- This is a bug which occurs on saving file. It is disappearing if I remove formatter settings in `settings.json`.
  
 Eslint/Prettier complains on it as it `?` and `=` should be separate in such cases.

### 💻 Code

```ts
export class SomeError extends Error {
    message: string;
    data? = {};
}
```
```json
{ 
  "[typescript]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
}
```

### 🙁 Actual behavior

`? =` is being joint into `?=`

### 🙂 Expected behavior

keep `? =` as it is written

**Comment by MartinJohns** [comment]
Sounds like an issue with eslint or prettier, not with TypeScript.

**Comment by fatcerberus** [comment]
@MartinJohns OP says eslint/prettier is *complaining* because VSCode/TypeScript has changed a property declaration to `data ?= {}` (which is not syntactically valid), if I’ve read it right.

**Comment by andrewbranch** [comment]
I have literally never seen `data? = {}` and didn’t know it was allowed, which is wild because it seems like legitimately useful syntax
