### ISSUE TITLE
Allow to pass "unique symbol" as  a type parameter (e.g. Opaque<string, unique symbol>).

### ISSUE THREAD

**Issue by olalonde** [microsoft/TypeScript#55691]
### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I have been trying to write a type helper to facilitate the creation of nominal types (aka branded/tagged/opaque types), but I'm a bit stuck by the fact I can't pass `unique symbol` as a type parameter.

The following doesn't work:

```typescript
type Opaque<T, TBrand> = T & {
  readonly __brand: TBrand;
}

type UserId = Opaque<string, unique symbol>;
// error: 'unique symbol' types are not allowed here.
type GroupId = Opaque<string, unique symbol>;
// error: 'unique symbol' types are not allowed here.

function printUserId(userId: UserId) {
  console.log(userId)
}

printUserId("abc" as UserId);
printUserId("def" as GroupId);
```

And if I just get rid of the TBrand parameter, it considers both UserId and GroupId to be compatible.

```typescript
type Opaque<T, TBrand> = T & {
  readonly __brand: TBrand;
}

type UserId = Opaque<string>;
type GroupId = Opaque<string>;
// error: 'unique symbol' types are not allowed here.

function printUserId(userId: UserId) {
  console.log(userId)
}

printUserId("abc" as UserId);
printUserId("def" as GroupId); // works ... :(
```

### 📃 Motivating Example

See suggestion.

### 💻 Use Cases

1. What do you want to use this for?

Creating nominal types

2. What shortcomings exist with current approaches?

Have to memorize how to do it, more code to type.

3. What workarounds are you using in the meantime?

To do the nominal type without using a type helper.

**Comment by nmain** [comment]
[You can create each unique symbol](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mCGBHArhAPAFQDRQwIQCd4A7AEwD4oBeXKAMigG8AoKKAieUge2IBsQUAPpCARkTIAuXIRKkA3MwC+zZgGNeAZ2BQAqpogFZZAMogAtqO59qUM5esAKAJSL1WnQHEC3ZGGOk9lY2NEFOrqqgkHoGBACSpLZwSKho2gQAlsQA5jhRENwAZjGGAWF85IoA9FVQhj4E0gDkyMQZKNCaFsFNUPmaUPAcUMTcOvB8fNwA7hCJABaGEAB0zPlQ3r5gCUkIHWnAmTl54AXFm35l3daVzDV1BA3Nre2oUF0OfL39g8Oj45MZnMoIsOKtmIVWmpgBleFAwEdgPpDAlHMhYglpMj4qRnExWFANMRNNYVlNsmiMbjlKoEVkkVTHAAieCiNRMwYDbEJCJ04gMlGkZmkCCFDnwAYXba4xRAA).

[Or, if you want the symbols to only exist in type space and not at runtime, you can declare each unique symbol](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mCGBHArhAPAFQDRQwIQCd4A7AEwD4oBeXKAMigG8AoKKAieUge2IBsQUAPpCARkTIAuXIRKkA3MwC+zZqQgBjPvA5QNvAM7AoAVQMQCssgGUQAW1Hc+05MQCWKaAfuO+itZrauvrERlAA4gTcyGBWpLYOTi7unlDeiX6qoJCm5gQAkqTUsAieaEYEbsQA5jjZENwAZrkWcQm+5IoA9F1QFlEE0gDkrh6oaT5OQ1D1BlA60MTcxvB8fNwA7hBFABYWEAB0zPURUTGFxXBIqOXAlTV14A3NkdGxEvGTfJ3MPX0EA2Go1S6V801m810SxWa022ygew4R2YjVcGmAbl4UDA92AZgshQAFMg8oVpPiCqQAJRMVh6QxOQ7rarE0nU5SqHFVPFswkAIngog0fPmcwphSpii5xB5BNI-PUjRF8Dmr3O1MUQA).

**Comment by fatcerberus** [comment]
^^^ what he said.  `unique symbol` types are tied to a variable declaration, to ensure they always have an identity.  Otherwise every utterance of `unique symbol` in the program would create a new type and you’d have no way to refer back to old ones.

**Comment by olalonde** [comment]
Those are good workarounds but they are workarounds.

>  Otherwise every utterance of unique symbol in the program would create a new type and you’d have no way to refer back to old ones.

Not sure what you mean by that.

**Comment by fatcerberus** [comment]
It means exactly what I said.  Your own example is of creating two `Opaque<string, unique symbol>` and having them be distinct types despite being the exact same in the source text.  But if that were allowed, how could you later refer to the unique symbol type for a particular `Opaque` if you haven’t given it an identity in the program?

**Comment by fatcerberus** [comment]
> Those are good workarounds but they are workarounds.

By this reasoning, what you’re trying to do is a workaround too and you ultimately really want https://github.com/microsoft/TypeScript/issues/202

**Comment by olalonde** [comment]
I am not sure I understand why are you opposed to this feature? Because there are workarounds?

**Comment by olalonde** [comment]
What seems like the way to go?

**Comment by fatcerberus** [comment]
#202

**Comment by olalonde** [comment]
I agree that #202 would be ideal but it has been opened for almost 10 years and it could be opened for another 10 years. While the feature I propose is not be a big change, it's even arguably a bug.

**Comment by andrewbranch** [comment]
This can’t be done without allowing `unique symbol` types literally anywhere (and so redesigning the entire feature) since the generic type could use the type anywhere:

```ts
type Id<T> = T; // obviously legal type alias declaration
type X1 = unique symbol; // error: 'unique symbol' types are not allowed here
type X2 = Id<unique symbol>; // instantiation is legal but results in the same type as X1, which is illegal?
```
