### ISSUE TITLE
"keyof" infers type incorrectly when it is applied to interface that extends Record<string, any>

### ISSUE THREAD

**Issue by nicky1038** [microsoft/TypeScript#55706]
### 🔎 Search Terms

keyof interface extends record number

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Link](https://www.typescriptlang.org/play?ts=5.3.0-dev.20230910#code/JYOwLgpgTgZghgYwgAgKIFsAOYCeBJcaeJZAbwF8BuAKF0xQGUwpQBzAJQgQHsoATZAF5knHvwA8AZ2ZsANMmksQrAHw1QkWIhQFNxFBAAekEH0nImSjl14CKNWjnpo8AMQDSEHEOQBrL9wwaFi4ukTayAD0kcggEABu0I7ODOye3sL+OIEWMsqitlEximzJOh5ePlk5YVok0bEArugARtDIAD4KeazyAO4AFt4g3GDdVgD8QA)

### 💻 Code

```ts
interface EmptyInterface {};
type StringRecord = Record<string, string>;
interface Interface extends StringRecord {};

type EIFKey = keyof EmptyInterface // never
type SRKey = keyof StringRecord // string
type IFKey = keyof Interface // number | string, why not string?
```

### 🙁 Actual behavior

`IFKey` is `number | string`

### 🙂 Expected behavior

`IFKey` should be `string`

**Comment by Andarist** [comment]
In general, what is indexable by string is also indexable by number:
```ts
const stringRecord: StringRecord = {};
const test1 = stringRecord["foo"];
const test2 = stringRecord[100];

const interface_: Interface = {};
const test3 = interface_["foo"];
const test4 = interface_[100];
```

The difference in `keyof` results here is surprising to me though.

**Comment by fatcerberus** [comment]
I believe the difference in behavior comes down to, `Record` is implemented as a mapped type.  `keyof MappedTypeOverString` is `string`.  Interfaces can’t be mapped types though (AFAIK), so extending a `Record<string, T>` demotes it to an index signature, and `keyof StringIndexSignatureType` is `string | number`, by design.
