### ISSUE TITLE
unknown incorrectly coerced to type when typeof !==

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#55701]
### 🔎 Search Terms

unknown typeguard not typeof

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about typeguards

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAhgRgBQEMBOBzALmUgGsIEB3CASiIGcYc4I9kBvYZL5OEZDVAE8ADgFMEfXKwCEAXlnIA5AyYtFyau07cdUJA2SDkCqQG5tOrjlEwwOFIsXmdAX2AXkeiAYBex5GbIAPRBqAAWcHQ8dBCKMMgQolCidHS4cAA2RljIKsx4ADSeWCgARqIBCWAAtuU4RaUICBmiJUUIpQBWSTAFAHQDqE0e1rb2Sk7AbkA

### 💻 Code

```ts
function t1(arg: unknown): string {
    if ( typeof arg !== 'string' ) {
        const y = arg;
        return '';
    }

    const z = arg; // this isn't necessarily a string, can be a number, boolean, object,... too
    return '';
}
```

### 🙁 Actual behavior

"z" is assumed to be "string", but this is wrong.

### 🙂 Expected behavior

"z" to be unknown

**Comment by fatcerberus** [comment]
If `const z` is reached then `typeof arg` is guaranteed to be `"string"` because your function returns before then if it isn’t
