### ISSUE TITLE
Unable to define async function type

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#5570]
I'm just wondering if I could define an async function type. I want to create an interface where one of the properties of the interface is an async method.

```typescript
interface Setup {
     asyncMethod: async () => Promise<any>; // cannot find name 'async'.
}
```

The reason I want to await, is so I can await on a function that returns a promise from a JS library. Also await on any type isn't working either.

**Comment by mhegazy** [comment]
`async` is only allowed in implementation. use `Promise`

```ts
interface Setup {
    asyncMethod: () => Promise<number>;
}

async function asyncMethodImplementation() {
    return 0;
}

var s: Setup;

s.asyncMethod = asyncMethodImplementation;
```

**Comment by tinganho** [comment]
Ok thanks
