### ISSUE TITLE
readonly bindings with primitive types use the declared type in nested scopes

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#55708]
### 🔎 Search Terms

readonly const binding primitive type declared type flow type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230910#code/CYUwxgNghgTiAEYD2A7AzgF3gcRC0MAwgBZICWYIaAXPAN4BQ88cUwqEAnvALJQQhaAIj4ChAbiYsQbDtwBiIALb9B8IYpVjJAX0kZOABwS58IIqQoIAvPAAUB40gBmOPARLlKaAJQBtAGsQThd4RxBQ0w9LbwBdSQZw+AAFczRUeFtGZjJgWhQAVyUAI3NJZhQoJTVMGDIUAHNdfSMEVJh0lAAhTgBJYEz4ACVwJBhgAB5CkvMAGhS01AA+BKT2zp6o80Hk2AwyfgmR5HGJrYsvEHn11B7+pZWGBmR0LAb3c1pzzytBkVUJE8Xph4EhigArQbZeB+d5mGCxWjOfhoK7wBh6Bhg8EMAD0uPgAD0APxA1Ag4wdW6cc60G7dGkfGCDbHieD4sLEMhoeDsKjwFBILAAdzGAXgUB5IAAHsYwBgQMAns4Cih5WQMgrMPJVerUHYfPQpMCsNioVJmLCmYj4MiIKjZlJMcxsVIOSTjeSsJSNoz4XTFgzziyIWyOUgkIY0GQqPMMFyeagEFAwGBcngMPwuLykFQUAByLDmGBjDEMIA

### 💻 Code

```ts
declare const GenderChoices: {
  readonly Male: "Male";
  readonly Female: "Female";
};
type GenderChoice = (typeof GenderChoices)[keyof typeof GenderChoices];

type Person = {
  id: number;
  name: string;
};
type PersonById = Record<number, Person>;

type PersonByGender = Partial<Record<GenderChoice, PersonById>>;

const gender: GenderChoice = "Male";

const obj = {
  [gender]: false, 
};
obj
// ^?

const personByGender: PersonByGender = obj; // this does not work as expected

function testFunction() {
  const obj = {
    [gender]: false,
  };
  obj
  // ^?
  const personByGender: PersonByGender = obj; // oopsies, this one accidentally doesn't error
}
```

### 🙁 Actual behavior

The computed property in the nested scope uses the declared type and that's a union. A union isn't usable as a property name and thus this property's type is widened to `string`, creating `{ [k: string]: boolean }` at the end. This in turn is assignable to a weak target type.

### 🙂 Expected behavior

I think that often the fact that locally the declared type isn't used as the type of a binding is overlooked. The example at hand shows how this might result in a surprising difference between those two scopes. Since the created binding is a readonly one and has a primitive/unit type, I think it would be nice if the type of this binding wouldn't differ between scopes - it could still be `"Male"` in the inner one.

**Comment by ahejlsberg** [comment]
I'm not quite sure what change you're asking for. The type of `gender` in the outer scope is narrowed to `"Male"` and we therefore create a property by that name. But the type of the `gender` parameter in the function is a union type, and when the `obj` initializer executes we don't know the exact name of the property. We could potentially give the union type `{ Male: boolean } | { Female: boolean }` to `obj`, but when there are multiple such properties with large numbers of possible choices, the size of the union explodes exponentially.

**Comment by Andarist** [comment]
> But the type of the gender parameter in the function is a union type

This part is what this issue was meant to be about. Since `gender` is `const` and has a unit type - is there a reason why `gender` has to have a different type at both of those locations?

**Comment by Andarist** [comment]
Omg, sorry for this 🙈 This was based on the code shared on Twitter and I totally missed that - was living under the impression that this was referencing the outer one. That said... the result doesn't change if we do reference the outer one in that inner scope: [TS playground](https://www.typescriptlang.org/play?ts=5.3.0-dev.20230910#code/CYUwxgNghgTiAEYD2A7AzgF3gcRC0MAwgBZICWYIaAXPAN4BQ88cUwqEAnvALJQQhaAIj4ChAbiYsQbDtwBiIALb9B8IYpVjJAX0kZOABwS58IIqQoIAvPAAUB40gBmOPARLlKaAJQBtAGsQThd4RxBQ0w9LbwBdSQZw+AAFczRUeFtGZjJgWhQAVyUAI3NJZhQoJTVMGDIUAHNdfSMEVJh0lAAhTgBJYEz4ACVwJBhgAB5CkvMAGhS01AA+BKT2zp6o80Hk2AwyfgmR5HGJrYsvEHn11B7+pZWGBmR0LAb3c1pzzytBkVUJE8Xph4EhigArQbZeB+d5mGCxWjOfhoK7wBh6Bhg8EMAD0uPgAD0APxA1Ag4wdW6cc60G7dGkfGCDbHieD4sLEMhoeDsKjwFBILAAdzGAXgUB5IAAHsYwBgQMAns4Cih5WQMgrMPJVerUHYfPQpMCsNioVJmLCmYj4MiIKjZlJMcxsVIOSTjeSsJSNoz4XTFgzziyIWyOUgkIY0GQqPMMFyeagEFAwGBcngMPwuLykFQUAByLDmGBjDEMIA)

**Comment by ahejlsberg** [comment]
> That said... the result doesn't change if we do reference the outer one in that inner scope

Yes, that's because of function hoisting and their inability to rely on control flow analysis of outer variables. The `testFunction` function is in scope and callable *before* the declaration of `gender`, so we can't rely on `gender` having a particular narrowed type. It works if you change the declaration to use a `const` variable and an arrow function:

```ts
const testFunction = () => {
  const obj = {
    [gender]: false,
  };
  obj
  // ^?
  const personByGender: PersonByGender = obj; // error
}
```

The difference is unfortunate, but no sure there's much we can do.

**Comment by Andarist** [comment]
I'm fine with this. I created this mainly to get a better understanding of *why* this is this way. Your answer is perfect, thank you very much for it! Let's mark this as a design limitation/working as intended and close it :)

**Comment by fatcerberus** [comment]
So… ultimately related to #9998?
