### ISSUE TITLE
The `type` key in `package.json` unexpectedly modifies the behavior of tsc

### ISSUE THREAD

**Issue by olalonde** [microsoft/TypeScript#55707]
### 🔎 Search Terms

package.json, tsc, module, nodenext

### 🕗 Version & Regression Information

All versions I tested

### 💻 Code

See this repo: https://github.com/olalonde/tsbug

Changing the value of the `type` key in `package.json` changes the behavior of the compiler.

### 🙁 Actual behavior

When `package.json` has `"type": "module"`, the compilation fails with:

```
$ npm install
$ npx tsc --noEmit
src/valid.ts:3:23 - error TS2339: Property 'isIP' does not exist on type 'typeof import("/Users/redacted/code/tmp2/tsbug/node_modules/@types/validator/index")'.

3 console.log(validator.isIP("12312"));
                        ~~~~


Found 1 error in src/valid.ts:3
```

When I remove the `type` key from `package.json`, compilation succeeds:

```
$ tsc --noEmit

$
```

### 🙂 Expected behavior

Compilation succeeds, regardless of value of `type` key in `package.json`.

### Additional information about the issue

https://github.com/olalonde/tsbug

**Comment by MartinJohns** [comment]
This is intentional. See also: https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions

**Comment by fatcerberus** [comment]
*Also* also: https://arethetypeswrong.github.io/?p=validator%4013.11.0

**Comment by olalonde** [comment]
@MartinJohns I know what `"type": "module"` does to a Node.js package. But this is not an issue with Node.js, it is one with tsc. `tsc` fails to load a type file for a module I'm importing and this has nothing to do with my code... Is there a bug in the way DefinitelyTyped publishes packages?

**Comment by fatcerberus** [comment]
It's a bug in the `validator` types specifically (see my link above)

**Comment by MartinJohns** [comment]
> I know what `"type": "module"` does to a Node.js package. But this is not an issue with Node.js, it is one with tsc.

Did you even read the documentation I linked to? Setting the type to module changes how TypeScript interprets the packages. So changed behavior is absolutely to be expected. And if your packages are not compatible with this changed behaviour (like cerberus pointed out) you're gonna have a bad time (errors).

**Comment by olalonde** [comment]
@MartinJohns so what's the point of `moduleResolution` again? 

@fatcerberus Ok you're right. It works when accessing `validator.default`

**Comment by olalonde** [comment]
Note to self:

```
import validator from "validator/es";
```

**Comment by fatcerberus** [comment]
> so what's the point of `moduleResolution` again?

The current state of things is indeed pretty confusing.  See https://github.com/microsoft/TypeScript/issues/55221.
