### ISSUE TITLE
[INFO] 12:26:22 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.2.2) Compilation error

### ISSUE THREAD

**Issue by rumon5h** [microsoft/TypeScript#55719]
### 🔎 Search Terms

Unable to compile TypeScript:
error TS5109:

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions "^5.2.2"

### 💻 Code

```ts
// Your code here
import { app } from "./app";
require("dotenv").config();


// Create the server

app.listen(process.env.PORT, () => {
    console.log(`Server is connected with port ${process.env.PORT}`);
})
```

### 🙁 Actual behavior

server\server.ts
[ERROR] 12:31:45 ⨯ Unable to compile TypeScript:
error TS5109: Option 'moduleResolution' must be set to 'NodeNext' (or left unspecified) when option 'module' is set to 'NodeNext'.

### 🙂 Expected behavior

Server is running 

### Additional information about the issue

> ts-node-dev --respawn --transpile-only server.ts

[INFO] 12:26:22 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.2.2)
Compilation error in D:\company\course-app\server\server.ts
[ERROR] 12:26:22 ⨯ Unable to compile TypeScript:
error TS5109: Option 'moduleResolution' must be set to 'NodeNext' (or left unspecified) when option 'module' is set to 'NodeNext'.

**Comment by jakebailey** [comment]
This is an intentional error, see: https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#module-and-moduleresolution-must-match-under-recent-node-js-settings

This is either a misconfiguration in your tsconfig, or ts-node-dev is using an incorrect configuration. Either way, this isn't a problem with Typescript.

**Comment by rumon5h** [comment]
Thank you

**Comment by muh-arslan** [comment]
I used `tsnd --respawn server.ts`
instead of `ts-node-dev --respawn --transpile-only server.ts`
and i worked for me

source: https://www.npmjs.com/package/ts-node-dev

**Comment by AnasShinkafi** [comment]
Thanks @muh-arslan  it's also worked for me

**Comment by skyinnocent** [comment]
> I used `tsnd --respawn server.ts` instead of `ts-node-dev --respawn --transpile-only server.ts` and i worked for me
> 
> source: https://www.npmjs.com/package/ts-node-dev

Thank You this worked for me as well

**Comment by arwayush** [comment]
Thanks this also worked for me !!

**Comment by HuyTrongTran** [comment]
> I used `tsnd --respawn server.ts` instead of `ts-node-dev --respawn --transpile-only server.ts` and i worked for me
> 
> source: https://www.npmjs.com/package/ts-node-dev

thanks it work with me too
