### ISSUE TITLE
Error when assigning to a Record when `noUncheckedIndexedAccess: true`.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/TypeScript#55722]
### 🔎 Search Terms

noUncheckedIndexedAccess record undefined not assignable

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about noUncheckedIndexedAccess

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3lADjiIAXPAN7wDaA1iAJ7GYwCWKA5gLrEBGSSBUK8AD7wArilAAzZiGDwAvgChk6LJ37riAJXBIYwADwNmLADTxuvEPwB88ALzY8BeAHoX8EDBi6Fb+ABUaHAQAcjIqWnoMJlYOcx4+AWExSWlgAG55EPhGNHgUJCwoNDRGFhQoTmcMJHgMINDtZD1DaOMzC0TrEIA6X3d4eBCjVmzmUAAPeFLyqAwRODzYBGZkAFscOcYqkD6-QcHA4KHOqyTRcRApFBkxvIKikrKKnbra+uOQ0-5e-oP-o6hFJXNJ3fKFbBPWavGp1BonBJnXoACgATABmVGogCUQA

### 💻 Code

```ts
declare const apple: { [key: string]: boolean | undefined }
const banana: Record<string, boolean> = apple // error
// Type '{ [key: string]: boolean | undefined; }' is not assignable to type 'Record<string, boolean>'.
//   'string' index signatures are incompatible.
//     Type 'boolean | undefined' is not assignable to type 'boolean'.
//       Type 'undefined' is not assignable to type 'boolean'.(2322)
```

### 🙁 Actual behavior

An error when trying to assign an object that functionally matches the Record type (when `noUncheckedIndexedAccess` is enabled).

### 🙂 Expected behavior

Able to assign an object to `Record` that matches the `Record` type signature when `noUncheckedIndexedAccess` is enabled.

### Additional information about the issue

Originally reported as a comment on https://github.com/microsoft/TypeScript/issues/10530#issuecomment-1715467002 because it looked like other issues surrounding `noUncheckedIndexedAccess` were being duplicated there, but someone suggested it isn't a duplicate.

The problem may be that `undefined !== not-defined`, but TypeScript doesn't have a way to describe that difference in the type system, so it becomes impossible to assign an "exploded" `Record` to a `Record`.

My real-world case is that I have a library that wants a `Record<string, T>` as a function parameter and I have (for complicated reasons involving lots of generics) a `{ [key: string]: T | undefined }`.  TypeScript is not allowing me to pass my object to the library function because it thinks they are of different types, but there is no way to define my type to actually match `Record` other than casting it explicitly to a `Record` because there isn't a mechanism for creating a type like `{ [key: string]: T | not-defined }` in TypeScript.

**Comment by MartinJohns** [comment]
> Able to assign an object to `Record` that matches the `Record` type signature when `noUncheckedIndexedAccess` is enabled.

But it doesn't match. If you change your type to `Record<string, boolean | undefined>` it matches. Your object may have properties explicitly set to `undefined`.

**Comment by MicahZoltu** [comment]
I believe it matches for all situations that you can actually type check.  For example, if you index into any string key the resulting type is `boolean | undefined` for both types.

Separately, I think the issue here is that `undefined` is a type that you can express to the compiler, but `not-defined` is something the compiler internally understands but you cannot actually express.  `Record<string, boolean>` is synonymous (internally) with `{ [key: string]: boolean | notdefined }`, but the TypeScript language doesn't provide any mechanism to actually express that type to the compiler.

**Comment by fatcerberus** [comment]
> Separately, I think the issue here is that `undefined` is a type that you can express to the compiler, but `not-defined` is something the compiler internally understands but you cannot actually express. `Record<string, boolean>` is synonymous (internally) with `{ [key: string]: boolean | notdefined }`, but the TypeScript language doesn't provide any mechanism to actually express that type to the compiler.

This isn't entirely true.  https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes

**Comment by MicahZoltu** [comment]
> This isn't entirely true anymore. https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes

Sadly, you cannot have an optional indexed typed.  This is an error:
```ts
declare const apple: { [key: string]?: boolean }
```

**Comment by MartinJohns** [comment]
In my first comment I confused compiler options and thought of `exactOptionalPropertyTypes`.

> Sadly, you cannot have an optional indexed typed.

It wouldn't make any sense. Properties of indexed types are by definition optional.

**Comment by fatcerberus** [comment]
I should maybe also note that

```ts
declare const foo: { [key: string]: boolean }
foo["bar"] = undefined;
```

is an error.  As for your example, in general `Partial<T>` is not going to be assignable to `T`

**Comment by fatcerberus** [comment]
> something the compiler internally understands but you cannot actually express

In my experience I think this is the source of like 75% (figure I just made up) of people's frustrations with TS in general, so I can definitely relate to it.

**Comment by RyanCavanaugh** [comment]
I don't see any behavior change here when toggling `noUncheckedIndexedAccess`, can you double-check?

The behavior here is consistent and correct; when you have a `Record<string, T>`, the sort of implicit understanding is that you know which keys are valid and which aren't (otherwise the type would be uninhabitable, since no object has *every* utterable key).

**Comment by MicahZoltu** [comment]
> I don't see any behavior change here when toggling `noUncheckedIndexedAccess`, can you double-check?

You are correct, there is no behavior change when toggling `noUncheckedIndexedAccess`.  I believe there *should* be.

> The behavior here is consistent and correct; when you have a `Record<string, T>`, the sort of implicit understanding is that you know which keys are valid and which aren't (otherwise the type would be uninhabitable, since no object has _every_ utterable key).

As a user with `noUncheckedIndexedAccess` enabled, my expectation is that `Record<string, T> === Record<string, T | undefined>` because, as you said, it is impossible to set every utterable `string` key.  The default TS behavior with `Record` is unsound (which is fine, there are a number of such design choices in the language), and I expect that `noUncheckedIndexedAccess` will make it sound by making all keys possibly undefined.
