### ISSUE TITLE
Tuple containing a union is not assignable to the equivalent union of tuples, but only when type is an object property

### ISSUE THREAD

**Issue by cyberia-ng** [microsoft/TypeScript#55724]
### 🔎 Search Terms

union within tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about unions, tuples, objects

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMAhjANjMBzAKgUwGcoBhFQ-ACgEpEBvAKEWcSgE8AHfRAMTjkQBeesn4AuRAG0A5CmkAaRNIBG0xAB8lEBUoAm0gLqIAvgG4mLdl0QAhFACchI4OKmydKj-qPGNz1zJyitLawd4m5hbMoJCwCKJwuHB29pQucBJ8cNQSKfRRLMz2+FAg9kjp5oXGDAUx0PBIyg5JWZTN9rkOObz8+YWFxaXliB1VLDU1DPVxSIQgEBD4+LpYeESk5FS0jIVW3FlOgR6qfiFehuPM+7YOR+7BqmGGfsfBoXqXtYUzjQlJKTSriyPTyuwGRRKZQq-CuJm+LF+8Q6rX47QcXXsPUO4IhQ2howccMmDCAA

### 💻 Code

```ts
function failingTestCase() {
    type Foo = { foo: ['a', 'b' | 'c', 'd'] };
    type Bar = { foo: ['a', 'b', 'd'] } | { foo: ['a', 'c', 'd'] };

    function fooToBar(foo: Foo): Bar {
        return foo;
        // error TS2322: Type 'Foo' is not assignable to type 'Bar'.
        //   Type 'Foo' is not assignable to type '{ foo: ["a", "c", "d"]; }'.
        //     Type at position 1 in source is not compatible with type at position 1 in target.
        //       The types of 'foo' are incompatible between these types.
        //         Type '"c" | "b"' is not assignable to type '"c"'.
        //           Type '"b"' is not assignable to type '"c"'.
        //
        // 6         return foo;
        //           ~~~~~~
    }

    function barToFoo(bar: Bar): Foo {
        return bar;
    }
}

function succeedingTestCase() {
    type Foo = ['a', 'b' | 'c', 'd'];
    type Bar = ['a', 'b', 'd'] | ['a', 'c', 'd'];

    function fooToBar(foo: Foo): Bar {
        return foo;
    }

    function barToFoo(bar: Bar): Foo {
        return bar;
    }
}
```

### 🙁 Actual behavior

Type checking fails with `error TS2322: Type 'Foo' is not assignable to type 'Bar'.`

### 🙂 Expected behavior

Expected type checking to succeed since the types are structurally equivalent

**Comment by Andarist** [comment]
`succeedingTestCase` works OK because you are relating directly a source with a target that is a discriminated union. The `failingTestCase` doesn't work because the compiler related that source separately with each target union constituent (that union is not a discriminated one).

I'd say that this is a design limitation but it might be best for a TS team member to chime in on this one.

**Comment by RyanCavanaugh** [comment]
In general, assignments that can only be seen to be legal through combinatorial explosion are not allowed. There are some special cases allowed because people are generally happier when more things work rather than fewer, but this isn't one of them.
