### ISSUE TITLE
Pasting nested block comment causes mangling

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#5572]
Hi,

**Version:**: TS 1.6 / VS 2015

In the following snippet

``` typescript
/**
 * The result can be [1] 
 */
function foo() {

    // [2] then(() => /*next tick*/ assert.isTrue(...);)
}
```

Copying and pasting [2] at the point where it says [1] causes the comment to be mangled.

This is occurring because of the nested comment `/*next tick*/`

**Comment by Andarist** [comment]
I'm not really sure if this is something that should be fixed. I'd be surprised if TypeScript would rewrite somehow what I just pasted using the regular paste action. If the paste introduces syntax errors in the document, that's on me as the user and I think it's fine/expected that I would have to fix this on my own. @jakebailey WDYT?

**Comment by RyanCavanaugh** [comment]
I agree; paste should not imply random edits. We have no idea what the user intent is.

**Comment by NoelAbrahams** [comment]
I've spent the last eight years ruminating on the right solution for this and, after trying out many agonising alternatives, I agree this doesn't need fixing.
