### ISSUE TITLE
Fails to use the generic parameter default when omitting the optional argument providing the type

### ISSUE THREAD

**Issue by luka-bip** [microsoft/TypeScript#55730]
### 🔎 Search Terms

generic parameter default, optional argument

### 🕗 Version & Regression Information

- I believe this is a bug
- This bug affects v5.2.2 as well as the current nightly (v5.3.0-dev.20230912)
- This is the behavior in every version I tried (above plus v4.9.5 and v3.9.7), and I searched through the FAQ for entries about "optional" and "generic type default"

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/PQKhCgAIUhBAneBDAnpALge0gWSQBw2QDsBnAM03gFsBTeKGAAXyWWsjeTXQAtbOiVJADuvTKQG0ANrTrF0pUQEtp0yACMB6EhSp0AJpGULstBfGW0lmchn6RqBRpBZskHANa0UAZRm0AMZY8JDkAK7EwcqYxPZI6BhI3kpIcQHyiWlG8LTo4fBk9gLeKC5u7JAAbkjS4bT+ssFUYZHRsfGJ6MnWnOmymX05eQVFfAI1dQIAFFzCGeaJyooydsp2mNTL6LQGAJTlufmFqY4EKnzFkAbWyrlGpanERpP1pIzA4IGxpFlCKAAVTB4QgAXkgAB4AKIAGkgAGk4QA1SDgqEAPmmUEgOLmKAAXJAoQBtAC6MOxONKjSCIUJ0wWCkJUL2qPRCIpOJxrwaAWa8AA-PTGehmazQeykeA9oSQRDEZAkeyJZBiLQRLgCLN-gA6Jz4aYMgaLcXs4nUvkhI1yE1w6Y8mn8gU662ZVkCgWQEV7Ul7PYAbiAA

### 💻 Code

```ts
/**
 * Array to Map transformer
 * @param array the array whose elements will be transformed into entries of the map
 * @param keySelector function that takes an element and returns the key
 * @param valueSelector function that takes an element and returns the value (array element itself if omitted)
 * @returns a map with the desired keys and values
 */
const arrayToMap = <E, K, V = E>(
    array: E[],
    keySelector: (element: E) => K,
    valueSelector?: (element: E) => V
): Map<K, V> => new Map(array.map((element) => [keySelector(element), (valueSelector?.(element) ?? element)]));
```

### 🙁 Actual behavior

The compiler complains that:
```
Type 'Map<K, E | NonNullable<V>>' is not assignable to type 'Map<K, V>'.
  Type 'E | NonNullable<V>' is not assignable to type 'V'.
    'V' could be instantiated with an arbitrary type which could be unrelated to 'E | NonNullable<V>'.
```
forcing me to cast `E | NonNullable<V>` as `V`:
```ts
/**
 * Array to Map transformer
 * @param array the array whose elements will be transformed into entries of the map
 * @param keySelector function that takes an element and returns the key
 * @param valueSelector function that takes an element and returns the value (array element itself if omitted)
 * @returns a map with the desired keys and values
 */
const arrayToMap = <E, K, V = E>(
    array: E[],
    keySelector: (element: E) => K,
    valueSelector?: (element: E) => V
): Map<K, V> => new Map(array.map((element) => [keySelector(element), (valueSelector?.(element) ?? element) as V]));
```

### 🙂 Expected behavior

With `valueSelector`, `V` should default to `E` and TS should know that the return type the map is `[K, E]` and that the resulting type `Map<K, E>` is assignable to `Map<K, V>`

**Comment by MartinJohns** [comment]
> `V` should default to `E`

It defaults to. But it can also be provided and be a **completely** different type than `E`.

**Comment by luka-bip** [comment]
@MartinJohns I don't see the problem. When type `V` is provided, the return type is `Map<K, V>`. And when it's not, `V` defaults to `E`, so the return type `Map<K, E>` is the same as `Map<K, V>`

**Comment by nmain** [comment]
Consider this call:  https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwXAngFRAWTgBxgXhgB4BRAGhgGkKA1AmEgPgAoAoGD+JVALgYG0AumXacA1gFMUAZQkAbCcCggEfZvIkBbCWCh8SASgKMqIzjABucOQFcJshUpUB+NRu279R-CZqsDfNg4RNQwNCY+MGASAO4wQcyIyCgAdJq4zOoKHlDeJvySMhpOCFlaOrkUzFa29sXKCM4pZTlGzs4w7hUGggYGANysrFYIMAAe9EmoGEFEYDaaAEYSCBTzSysU0AgAlmAA5iz8AMwUACwUAKzC48bjA6wA9I8cAHrOrEA

```typescript
var x = arrayToMap<number, number, string>([3, 4, 5], x => x);
```

The types claim you'll have a `Map<number, string>` here, but the implementation will actually provide a `Map<number, number>`

**Comment by luka-bip** [comment]
Oh, it hadn't occurred to me that I can provide the type explicitly. Thanks.

**Comment by MartinJohns** [comment]
That's what I meant with "it can also be provided".

**Comment by luka-bip** [comment]
@MartinJohns I figured as much, I appreciate you trying to help.

**Comment by luka-bip** [comment]
For those who may find this through google, the solution is to use function overloading, with signatures `arrayToMap<E, K>: Map<K, E>` `arrayToMap<E, K, V>: Map<K, V>`, and `arrayToMap<E, K, V>(...): Map<K, V | E>` (the last one with the actual implementation)
