### ISSUE TITLE
JSDoc {@link} support all 4 types of links

### ISSUE THREAD

**Issue by vanowm** [microsoft/TypeScript#55737]
According to [JSDocs documentation](https://jsdoc.app/tags-inline-link.html) `{@link}` may be formatted 4 different ways:
```
{@link namepathOrURL}
[link text]{@link namepathOrURL}
{@link namepathOrURL|link text}
{@link namepathOrURL link text (after the first space)}
```
VSCode currently only supports first and last formats:
![image](https://github.com/microsoft/vscode/assets/511517/664ef256-fc81-4d21-a3e5-c2ed6ddffcdc)

The third format (`{@link namepathOrURL|link text}`) produces wrong URL by appending text into the url

**Comment by xiBread** [comment]
The third works if you add a space before and after the pipe. `{@link www.google.com | Google}`

**Comment by vanowm** [comment]
@xiBread true, as a work around for your own work. However, if you are working on someone else's code who used one of these standards, it might create unwanted results.
