### ISSUE TITLE
Shorthand property names issue with target ES6 and commonjs module

### ISSUE THREAD

**Issue by ghalle** [Microsoft/TypeScript#5573]
Using typescript@next (1.8.0-dev.20151109) and the following compilerOptions:
```json
"compilerOptions": {
    "target": "ES6",
    "module": "commonjs"
}
```
Any code using named import as a shorthand property will result in invalid code being generated.

Example:
```typescript
import {foo} from './foo';
const test = {
  foo
};
```
generates
```javascript
var foo_1 = require('./foo');
const test = {
    foo
};
```
```
ReferenceError: foo is not defined
```

**Comment by mhegazy** [comment]
@ghalle the fix should be in `typescript@next` later tonight (around 12:00 am PST). please give it a try and let us know how it fairs.

**Comment by ghalle** [comment]
@mhegazy @vladima Seems to be fixed, didn't expect a fix so soon, great work :)
