### ISSUE TITLE
Rename tsconfig `exclude` to `resolutionExclusions`

### ISSUE THREAD

**Issue by nl-brett-stime** [microsoft/TypeScript#55748]
### 🔎 Search Terms

"tsconfig", "exclude"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `tsconfig`

### 💻 Code

tsconfig.json
```json
{
  ...,
  "resolutionExcludes": ["node_modules"]
}
```

### 🙁 Actual behavior

New property name not recognized.

### 🙂 Expected behavior

Recognize new property name which better distinguishes the behavior of the currently-named `exclude` property from the behavior of the `include` property.

### Additional information about the issue

Hopefully this more self-documenting name will help user understanding and nudge this awesome project closer to the principle of least astonishment.

Obviously, we'd want the `exclude` name to keep working for a major version or two with some deprecation warnings.

**Comment by RyanCavanaugh** [comment]
I don't understand; `exclude` is merely a filter on `include`, and has no effect whatsoever on what we would normally call resolution. The proposed name seems (much) worse.
