### ISSUE TITLE
Replace<Type, KeyOld, <KeyNew,TypeNew>> Utility Type

### ISSUE THREAD

**Issue by mazimcoder** [microsoft/TypeScript#55745]
### 🔍 Search Terms

Replace<Type
Reaplce
replace type util
replace type utils
Replace<Type, KeyOld, <KeyNew,TypeNew>>
replace<type,

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Types utilities are marvellous, yet they don't have a simple `Replace`! It's not only nice to have, but would make it easier to replace types' key with new one with its associated type as below:

```typescript
Replace<Type, KeyOld, <KeyNew,TypeNew>>
```

### 📃 Motivating Example

The type User has its `updatedAt` key replaced with `updatedBy`  along with the new type in `NewUser` type

```typescript
type User = {
	id: string,
	firstName: string,
	lastName: string,
	createdAt: string,
	updatedAt: string,
}
```
Assuming we have type utility `Replace<Type, KeyOld, <KeyNew,TypeNew>>`

```typescript
type NewUser = Replace<User, updatedAt, <updatedBy,{
	userId: string,
	updatedAt: string,
}>>
```
The `NewUser` type now looks like
```typescript
type NewUser = {
	id: string,
	firstName: string,
	lastName: string,
	createdAt: string,
	updatedBy: {
		userId: string,
		updatedAt: string,
	},
}

```

### 💻 Use Cases

1. What do you want to use this for?
replacing types' key with new one along with its type
2. What shortcomings exist with current approaches?
using `Omit` or `Exclude` to make new type with the replaced key. The `Replace<Type, KeyOld, <KeyNew,TypeNew>>` is one easier utility.
4. What workarounds are you using in the meantime?
a combination of `Omit` and `&` or  `Exclude` and `&` to replace the current key

**Comment by nmain** [comment]
See https://github.com/microsoft/TypeScript/issues/55301
