### ISSUE TITLE
default import not working

### ISSUE THREAD

**Issue by ntilwalli** [Microsoft/TypeScript#5574]
When using a default export in one of my declaration files and default import in my source file, I see this error from the compiler:`proxyData.ts(4,12): error TS2304: Cannot find name 'MockServer'.`

My declaration file `server.d.ts` looks like this:
```
interface Server_Static {
  new(url: string): Server_Instance
  of(url: string): Server_Instance
}

interface Server_Instance extends EventTarget {
  on(type, callback): any
  send(data, options?): any
  emit(event, data, options?): any
  close(options:any): any
  clients(): any
  to(room): any
}

declare var Server: Server_Static
export default Server
```

My source file looks like this: 
```
import MockServer from './resources/mock-socket/server'

export class ProxyData {
  servers: MockServer[]
  constructor(actualWS: WebSocket) {
    this.servers = []
  }
}
```

I'm using typescript@next, 1.8.0-dev.20151107

Any ideas?  The replication code is uploaded to http://github.com/ntilwalli/tsDefaultIssue

**Comment by mhegazy** [comment]
The import here is a variable (`Server` in `server.d.ts`)  but you are using it as a type in `proxyData.ts`. i suspect that you meant to define `Server` as a class instead of a variable.

**Comment by ntilwalli** [comment]
I was just following the example in http://www.typescriptlang.org/Handbook#writing-dts-files

There it says I can use class decomposition to separate out the static and instance members, and it seemed to imply that by instantiating a `var` which is of the static type, it's equivalent to declaring a class.   Did I misunderstand that?

**Comment by mhegazy** [comment]
then you need to export both:

```ts
interface Server_Static {
    new (url: string): Server;
    of(url: string): Server;
}

interface Server extends EventTarget {
    on(type, callback): any;
    send(data, options?): any;
    emit(event, data, options?): any;
    close(options: any): any;
    clients(): any;
    to(room): any;
}

declare var Server: Server_Static;

// Export both variable Server and interface Server
export default Server;
```

**Comment by ntilwalli** [comment]
Got it. Thank you.
