### ISSUE TITLE
Regression in nightly build related to keyof, type narrowing, and exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by mtreder** [microsoft/TypeScript#55756]
### 🔎 Search Terms

keyof
type narrowing
exactOptionalPropertyTypes

### 🕗 Version & Regression Information

- This is newly identified as error by the compiler
- This changed between versions nightly build on 9/13 and 9/14
- This is the behavior in every version I tried prior to Nightly

### ⏯ Playground Link

https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=5.3.0-dev.20230915#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgSQCFMBnPAbwFgAoASAH0AjKTJAEwC45WBPAbhoBfGjVCRYiFGiy4CAETQIAbsDYBBOKFTsSBYmThU6YKBDBoYPNQH4ujCBAA2wVgOrDqo8NHjJUGHDx8BShlVUJNEG02XSJSChpaEzMLHkJbOBIYUKQAczcPL3F4S3MCNUdHAHkwGAQIJF0AXj14uAAyRODFFXUOrpCwtkI3Ip84dABXJGw6hrhsRwbgGrnGgApEkihsLnwK6tr6xoAaRLZgLLgW4ABbWp5V45IAHn3Kp4aSAD51gEoztQ-oZEusqowAFbAWYAOgA1sAeCR1ttsMDSHB1gieBB0OUPkcvn8ANoAXT+MPQ0AAojgABbrMDXb4gui0BB49alYC4zI7YlgUlwACETRaACIIJDoTBxcCjLRFRcsgKhS1Uaq3IqPLRBH9RnQoMAYJMoEg4MqYAURNQpjM1pp7pZPo0XgAVSLRWIHF0-f5cD0Ko0ms2GOBMFjsLhKCAINhwAAMcEE3F0boKQA

### 💻 Code

```ts repro
// @strict: true
// @exactOptionalPropertyTypes: true

export interface IBase {
	_brand: any;
}

export interface IDerivedA extends IBase {
	propertyA?: boolean;
}

export interface IDerivedB extends IBase {
	propertyB?: string;
}

export type IAllOptions = IBase &
	IDerivedA &
	IDerivedB;

export function cloneOptions(
	src: IAllOptions,
	dest = emptyOptions<IAllOptions>(),
) {
	(Object.keys(src) as (keyof IAllOptions)[]).forEach(p => {
		if (typeof src[p] !== "object") {
			dest[p] = src[p];
		}
	});

	return dest;
}

function emptyOptions<T extends IAllOptions>(): T {
	return { _brand: void 0 } as T;
}
```

### 🙁 Actual behavior

There is an error on the line attempting to copy `src[p]` into `dest[p]`: 

```
type 'any' is not assignable to type 'never'.
```

### 🙂 Expected behavior

Previously this compiled without error.  Both objects are of the same type, so they should have the same properties.

**Comment by RyanCavanaugh** [comment]
> The change between origin/release-5.2 and origin/main occurred at https://github.com/microsoft/TypeScript/commit/9cbcf010ce0701a25f01a2a074000db34f80cc17.

Uh, no

**Comment by RyanCavanaugh** [comment]
This seems like a correct change. The example is not, from TypeScript's perspective, any different from
```ts
	let m1: keyof IAllOptions = 'propertyA' as keyof IAllOptions;
	let m2: keyof IAllOptions = 'propertyB' as keyof IAllOptions;
	dest[m1] = src[m2];
```
which should be an error (and also changed at the same time).

That said, we should narrow down which PR did this to make sure it was at least somewhat intended.

**Comment by fatcerberus** [comment]
> `dest[p] = src[p];`

I'm like 99% positive this has come up before in different contexts but basically, yeah, the compiler only sees the types in zero-order and doesn't understand the higher-order concept that `p` necessarily refers to the same property in both positions.  Supporting that would likely require https://github.com/microsoft/TypeScript/issues/30581 or something similar.

> we should narrow down which PR did this

@RyanCavanaugh Looks like that'd be https://github.com/microsoft/TypeScript/pull/55585, if typescript-bot's updated bisect is correct (the commit you quoted is different from the one that's linked now).

**Comment by jakebailey** [comment]
A local bisect confirms that this is due to #55585. @Andarist

**Comment by Andarist** [comment]
You either die a hero or live long enough to see yourself become the villain…

I will, of course, investigate this soon - thanks for the ping.

**Comment by Andarist** [comment]
I can't say this one was intended but it also looks to me like a correctness improvement. What I can offer is to add some tests covering this but other than that LGTM and the issue could be closed.

**Comment by fatcerberus** [comment]
@SlurpTheo I’d recommend opening a new issue for that because it definitely sounds like a bug.

**Comment by SlurpTheo** [comment]
> Adding an explicit `| undefined` to _either_ `propertyA`'s -OR- `propertyB`'s declaration makes this new error disappear. Seems like this new checking/error is incomplete (i.e., still possible to get `undefined` _explicitly_ stored in a signature that doesn't have `| undefined` in its declaration).

> @SlurpTheo I’d recommend opening a new issue for that because it definitely sounds like a bug.

I can't come up with a reproduction that doesn't involve `{ _brand: any }`; and with `any` involved, I don't feel like quibbling over ~inconsistencies.


[Playground link](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=5.3.0-dev.20230919#code/PTAEAEGcBcCcEsDG0Bco4FcCmBYAUCBFgB4CGyA8gA7TwD2AdqQDYAKsdVWs0AngCq8ukNJlx58TALZZIVcllABBUAG98ASD5dQASSXNm1Wo0igAvGs0aqHLj15KA-GgBGdOsyykGAbk0AvqAAZFZ4GjZ23HwAQi6gMAgMAOagAD6gGAwAJlgAZvAMWNn+4QGlmrmIzKSwioim0KB0rgBWaPqGxvQMkKUaVTV1oA29TbacaADWWLx0eXoGRjQ9fZqE4NCQALQkXMi7sBywmi2tANoTVAC6Fs1tl3bXFeF7dDygg7X1jaDEHUtuqZztosPNQFdnvgAvhJKQZHIFKAYmEtEJFJ1liZend1OFIpxoo54u5PN4-IEQqiCfZYvFEoVUhksrkCkUSpTQniIgB9VywHzZNBFABu3H65Vh4S+w1GMHu7UWXRWpn6Mp+Ywhdmms3BmKBvX6Gy2u2I+2gh2OpwekLuZ0enChEleZveTXVI1+-yVWNWIPR4MhpRhzuksnkiEUAGFUaCfQazJZuTSic43B4vD4JVTk1ciXE0AyUulMjl8oVitmudY+QKcmgfLwJS8Blhqt9PZqzgDldi1tK20MNfKrjq5gt9SrDdaLrbLPag1KNG8Ph65U1vZO+-6uIGnsGpWHEZHQAARWPo+NTxPUvMONOgUmZillHPWO90wtwRlV6m1wUNgwTaBC2a6-N2V59mqg4duuWqTKAMzjpBqxGmAmw7HsbYWtwxygNs2wJNAtTQMUnwYEkqQAAagpAiAIDQ4AAKwAHQAMwsQADNsuQiixABUVH4YRAAW0DQFQIggMk8DQCJGCuCxDRSMAUhIBwkDzNAwCCFwADK9HwDQwDwJAkDYJAwBMUxADsTEAGwAMSmeZbZ0FIMgMBaACMNkAExsQALJxACcbH2SFM4Ojcdo2vuS4ru6MGyl6Pa+sCoJ7o6B54EAA)

**Comment by fatcerberus** [comment]
Yeah, that's expected; once you have an `any` involved all bets are off because both `any | T` *and* `any & T` just reduce to `any`.  To be specific, what the assignability check for `dest[p] = src[p]` asks is: "Is the union of all properties potentially selected by `p` assignable to the intersection of those properties?"  So that behavior for `any` is actually consistent, despite outward appearances.

**Comment by fatcerberus** [comment]
#30769 was a similar change made years ago that was likewise a big source of consternation when first introduced, for what it's worth.
