### ISSUE TITLE
`Readonly` type loses `Partial`-ness of generic-keyed `Record`

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#55757]
### 🔎 Search Terms

readonly partial generic

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about N/A

### ⏯ Playground Link

https://tsplay.dev/mLJGZw

### 💻 Code

```ts
// @ts-expect-error This makes sense
<T extends 'a'>(): Readonly<Record<T, unknown>> => ({});
// This works
<T extends 'a'>(): Partial<Readonly<Record<T, unknown>>> => ({});
// But why is this not allowed? `T` can only be 'a' (or some intersection with it) or `never`.
<T extends 'a'>(): Readonly<Partial<Record<T, unknown>>> => ({});

// Sanity check other permutations work
<T extends 'a'>(): Partial<Record<T, unknown>> => ({});
(): Readonly<Partial<Record<'a', unknown>>> => ({});
(): Readonly<Partial<Record<never, unknown>>> => ({});
(): Partial<Readonly<Record<'a', unknown>>> => ({});
(): Partial<Readonly<Record<never, unknown>>> => ({});
```

### 🙁 Actual behavior

There is a type error `Type '{}' is not assignable to type 'Readonly<Partial<Record<T, unknown>>>'.(2322)`, despite `T` being bound by a "finite" type.

### 🙂 Expected behavior

No type error

**Comment by RyanCavanaugh** [comment]
There's special logic that allows `{ }` to be assignable to a mapped type that can be seen to be all-optional, as `Partial` is. That logic doesn't go arbitrarily deep.

**Comment by MichaelMitchell-at** [comment]
Has the TypeScript team considered consolidating documentation about all these special cases in one place or having concentrated efforts to clean up the type system model to require fewer special cases? As someone that often takes the responsibility of helping my colleagues with assorted TypeScript questions, every time I can't just link to the docs as an educational resource, I can sense the discouragement and feeling that they'll never understand TypeScript grow. Too often I have to refer to a specific release announcement, a specific comment buried in a Github issue, or even a tweet to provide explanations for certain behaviors.
