### ISSUE TITLE
Exclude removes string from union if union also includes Record<number, string>

### ISSUE THREAD

**Issue by nahinojo** [microsoft/TypeScript#55771]
### 🔎 Search Terms

"Exclude<Record<number,  string> | string, Record<number,  string>>", "string | Exclude<string | Record<number,  string>, Record<number,  string>>", "Exclude<> over exclude string from union with Record<number, string>", "Exclude utility type bug"

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I _searched_ the FAQ for entries about the utility type Exclude and couldn't find anything of relevance.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230917#code/PTAEFEA8GMBsFcAmBTUAnZBbA9gN2QM6gDkBALmgJYB2A5saAO4AWy1oyMCiNtoASsmjY0iADzV4mAEbI0AGlDkqdAHwA6AFBkAngAdUAIQCGiQcNGgAvAKEjxkmXMXLeq7ftQBJapTKVjWGslCl5QAB9QEzM7UQ8DUAAxGkDgqDgkZDEfPwDYRWjze3dNWGQyUEwdAGVQugAuJJTYTSralT4bYgAzbGxiTUGQUC9u0D1jNGNMcrkibDGiy0nUHm7uuTYyRTJWdlI6+lBKImpsUFhsOjkOLkzELV0EgHE+mItEAEFgpYcpWQUoEcAPcT1Qr2w73shh+sXErjoimBclBnlAEKhogAwrCPmIEbQXIdUQkcv5At8bASIui3r9PvFvL5ybAYVTDjSMb9DIyRsy8jj2R1OXS4VjeclqBS0ncUNl+RTFFy4Z8SahJYE2RBZVkyXlDErRR9DGqmlLYILtRk5XrAljDZDfliSmUKm1Dp9GhrYAzXZUaodDF7mjy-e6Oljg+bxeHeJSSL1+q0Ax0tT0+gNY3RLemk0A

### 💻 Code
```
type BadRecord = Record<number, string>
type Initial = string | BadRecord
type Final = Exclude<Initial, BadRecord>
```

### 🙁 Actual behavior

Final is type 'never'

### 🙂 Expected behavior

Final is type 'string'

**Comment by fatcerberus** [comment]
This happens because `Exclude` removes all types that are assignable to the given type and `string` is assignable to `Record<number, string>`:

```ts
let x: Record<number, string> = "foo";  // ok, no type error
```

So probably working as intended, for better or worse.

**Comment by fatcerberus** [comment]
Interestingly, `string | BadRecord` is *not* subject to subtype reduction.

**Comment by nahinojo** [comment]
I see what you mean @fatcerberus. In some way, `string` and `Record<number, string>` are the same in that they both will return a string value when indexed with a number. Or rather, that `Record<number, string>` is a kind of parent type of `string`.

While I can't say I'm completely satisfied with this answer, it does resolve the issue. Thanks.
