### ISSUE TITLE
need vscode error tooltip  when use type  and & 

### ISSUE THREAD

**Issue by vaynevayne** [microsoft/TypeScript#55784]
### 🔍 Search Terms

when use type and &,  There was a type incompatibility, but instead of telling me, ts went straight back to nerve, and I had no idea what the problem was until I switched to interface

<img width="766" alt="image" src="https://github.com/microsoft/TypeScript/assets/124666577/30c11630-6ebe-4561-a834-e3893189f747">

<img width="758" alt="image" src="https://github.com/microsoft/TypeScript/assets/124666577/9fb2e3a6-903c-4609-9da2-938c34a0a957">

```jsx
type FullSelect2Props = Omit<SelectProps, 'mode'> & {
  name: string
  modeList?: any
  mode: (typeof defaultModeList)[number]['value']
  onModeChange: (nextMode: (typeof defaultModeList)[number]['value']) => void
}
```

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

It should have an error message, just like interface

### 📃 Motivating Example

no

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by MartinJohns** [comment]
I'm surprised there is no eslint rule warning on intersections resulting in `never`.
