### ISSUE TITLE
Type definition with two rest operations for two arrays doesn't validated correctly

### ISSUE THREAD

**Issue by KingMario** [microsoft/TypeScript#55783]
### 🔎 Search Terms

`rest` `array`

### 🕗 Version & Regression Information

N/A

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAggTnAhiA6gS2ACwHIFEA2EAthAHbADOAPACoA0U2UEAHsGQCYVSkCuRAIwhwAfFAC8UGgG0AulABkUAN6FSAcywAuRgF8A3AChDoSLATJ0WbAAV8vCgWJlKtBk1btSXHvyGiJKGkAOlD4JFQMHCcScmp6RhEGUOCZWVkjE3BoAFkQcORAgsjrOwcYl2o+QWEGABYRTIBjAHtSCmAoRAQABgBGHTziwOk+hgAmBgBmDMMgA

### 💻 Code

```ts
type ArrayWithNElements<T, N extends number> = T[] & {length: N};

type ArrayWithNPlusElements<T, N extends number> = [...ArrayWithNElements<T, N>, ...T[]];

type MyArray = ArrayWithNPlusElements<number, 4>;

const arr01: MyArray = [1, 2, 3];
```

### 🙁 Actual behavior

`const arr01: MyArray = [1, 2, 3];` in the code is not validated as error.

While in the following code, arr02 is validated as error.

```ts
type NumberX4 = [number, number, number, number];
type MyArray2 = [...NumberX4, ...number[]];

const arr02: MyArray2 = [1, 2, 3];
```

### 🙂 Expected behavior

`const arr01: MyArray = [1, 2, 3];` in the code should be validated as error.

Validation of MyArray should be an attempt of splitting it into two arrays to validate against each array rest operation.

**Comment by MartinJohns** [comment]
`T[] & {length: N}` is not a valid tuple type, it's an array. So when you spread it, it's spread as an array, and your `ArrayWithNPlusElements<T, N>` type ends up being just `T[]`. You can see this when hovering over the type. When you use a proper tuple type you don't have this issue, that's why the suggested solution for the "N Tuple type" is https://github.com/microsoft/TypeScript/issues/54740#issuecomment-1602985590.

**Comment by KingMario** [comment]
Thanks MartinJohns

I'm just reporting a bug that either typescript should be able to report an error while declaring the type `ArrayWithNPlusElements<T, N>` as the error reported for `type MixedArray<T, U> = [...T, ...U]`, or typescript should be able to validate arr01 as error.

**Comment by KingMario** [comment]
Hi @RyanCavanaugh

IMHO, this is not a question. It's the buggy behavior of typescript compiler/language service that

either

typescript should be able to report an error while declaring the type ArrayWithNPlusElements<T, N> as the error reported for type MixedArray<T, U> = [...T[], ...U[]], which is, A rest element cannot follow another rest element.,

or

typescript should be able to validate arr01 as error.

@[MartinJohns](https://github.com/MartinJohns) I can't @ you because you blocked me. But I'm not talking about Tuple at all as a subset of the Array type. I don't use Typle much because I think it's immature, whereas you can call pop so that the tuple type of [string, string] becomes [string] or [] without realizing it.
