### ISSUE TITLE
Generalize private field duck typing

### ISSUE THREAD

**Issue by jrandolf** [microsoft/TypeScript#55786]
### 🔍 Search Terms

private, field, class, types

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Currently, private fields are considered a part of a class's interface resulting in errors when trying to duck-type a given class for another one which matches all properties except the private field.

Given that private field access is validated at access, we suggest to remove the above restriction.

### 📃 Motivating Example

```ts
class Foo {
  #test = 'foo';
  hi() {
    console.log(this.#test);
  }
}

class Bar {
  #test = 'bar';
  hi() {
    console.log(this.#test);
  }
}

function sayHi(a: Foo) {
    a.hi();
}

// Before: Property '#test' in type 'Bar' refers to a different member that cannot be accessed from within type 'Foo'.
// After: No error!
sayHi(new Bar());
```

### 💻 Use Cases

1. What do you want to use this for?
To avoid boilerplate and simplify API designs.
2. What workarounds are you using in the meantime?
Defining a separate interface.
3. What shortcomings exist with current approaches?
Defining a separate interface creates a lot of boilerplate. The suggestion is also valid behavior.

**Comment by fatcerberus** [comment]
> The suggestion is also valid behavior.

Class instances can access *each others’* private properties, not just their own.  If that happens, `Bar` may not be substitutable for `Foo`.  Hence why they aren’t interchangeable.

**Comment by nmain** [comment]
Your example works not because of any comparison between the `#test` fields, but because `sayHi` only uses `hi()`.  It would be better to extract that as an interface, and then use that interface as the parameter type to `sayHi`

```typescript
interface Hiable { hi() }
class Foo implements Hiable { ... }
class Bar implements Hiable { ... }
function sayHi(a: Hiable) { ... }
```

**Comment by jrandolf** [comment]
> > The suggestion is also valid behavior.
> 
> Class instances can access _each others’_ private properties, not just their own. If that happens, `Bar` may not be substitutable for `Foo`. Hence why they aren’t interchangeable.

There are already [checks](https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/checker.ts#:~:text=lexicallyScopedIdentifier.escapedName)%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20function-,checkPrivateIdentifierPropertyAccess,-(leftType%3A%20Type%2C%20right) for that, so if one attempted to access a private property in a different class, this is already caught.

> Your example works not because of any comparison between the #test fields, but because sayHi only uses hi(). It would be better to extract that as an interface, and then use that interface as the parameter type to sayHi

https://www.typescriptlang.org/play?#code/FAYwNghgzlAEBiB7RsDexawMQBcCmUOsAvLAOQBmyZA3BrABYCWAFAJRr2YiIB2UiMHgB0YRAHMWOZlGG4CONnUwBfYGtCQYsAEIQATp0zzCJcgCMDtes3ZHMsHv0Eixk6U1knFy2Go0UAK68IDhMfLBQEACeABKsEABcCMgc6A6wEMK2SurAwFFxrLx4AO66Buy5QA

**Comment by fatcerberus** [comment]
> There are already [checks](https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/checker.ts#:~:text=lexicallyScopedIdentifier.escapedName)

Okay but that’s a *runtime* error.  The type system’s main job is to *prevent* runtime errors caused by using the wrong type.

**Comment by jrandolf** [comment]
> The current behavior is intentional.
> 
> > so if one attempted to access a private property in a different class, this is already caught.
> 
> You're talking about a runtime crash - the whole idea of having a type system is to prevent those from occurring.

IIUC, TypeScript checks this in their type checker (which is compile time, not runtime). See checkPrivateIdentifierPropertyAccess in src/compiler/checker.ts

**Comment by RyanCavanaugh** [comment]
Right, and you're proposing that we not check it...

**Comment by fatcerberus** [comment]
> if one attempted to access a private property in a different class, this is already caught.

It is not… or rather it *is*, but only through the error you’re suggesting be removed:
```ts
class Foo {
  #foo = 777;
  stuff(x: Foo) { console.log(x.#foo); }
}

class Bar {
  #foo = 1206;
  stuff(x: Bar) { console.log(x.#foo); }
}

new Foo().stuff(new Bar());  // runtime error
```

**Comment by jrandolf** [comment]
> Right, and you're proposing that we not check it...

No, I am not proposing that. We should check that. What I am suggesting is allowing the example outlined in the issue above which is governed by a separate check.

**Comment by RyanCavanaugh** [comment]
By what means should [this example](https://github.com/microsoft/TypeScript/issues/55786#issuecomment-1726080606) have an check-time error if private fields are treated the way you're proposing they're treated?

**Comment by jrandolf** [comment]
> By what means should [this example](https://github.com/microsoft/TypeScript/issues/55786#issuecomment-1726080606) have a check-time error if private fields are treated the way you're proposing they're treated?

Yes, this should result in compile time error.

**Comment by RyanCavanaugh** [comment]
How? The proposal *is that* a `Foo` should be usable as a `Bar`. So there's no error in that program now.

**Comment by jrandolf** [comment]
Ah, you're right. Sorry, misread that example. Indeed, it seems to be problem when you have this swap of classes in such a way.

I guess this has no solution then :/ The main idea was to capture the fact that

```
class T {
  #prop: string;
}
```

can be compiled down to

```
const PROP = new WeakMap<T, string>();
class T {
}
```

But it seems the allowance of same-instance private field access puts a full stop on removing this type check. Such a shame...
