### ISSUE TITLE
Inconsistent behavior when classes implement partial index signatures

### ISSUE THREAD

**Issue by StelFoog** [microsoft/TypeScript#55782]
### 🔎 Search Terms

"class implements index signature", "class implements partial index signature", "partial index signature class"

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about `classes`

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2&ssl=12&ssc=69&pln=12&pc=1#code/C4TwDgpgBAkgdgEwgDwCrmgXigBQIYBOwAlngDYA8A3lANoDWEIAXFAM7AHFwDmAuqwAUASiiYAfO07ceUAL7iA3ACgAxmTxs2sRCjIQtUYgFsw+4xDjBt8JGgxQqcqAHoXUAPIBpNRsO2UECNTc0trHTt0SEdXdwBRAgIAewJlAEg7EBFHdLSCCGAAVwI4KAByTLKVNLllWvVNG11kABliYGgTMwgLKybIhxo3Tx801SS4DgJC1WAU7Kc65WVQaIBlSFViADNiVQDkMVxCEnJqOkYWKAADAAEAEiopmTlrgShsiSkuXnklX0aUA2EC2u3UBm0XVCfSBmx2ewOjmcw28AMMAFVJnCwcFur1wsDQQjmjFhglkqk0iAkgtcvkiiVqrV6n5tIT4apcdCCdjiXZSfFEil0mVbmxeRAEGVaWk8gViqUyuKQfDJVV0sy0WzeapyGQQJjlUTOVCemFtSqwYihoKKekAG7kQpYKAAIkdZGdrqWKwc+CIpDI+oAIhBdnBJUd-adKFR0ngRKx7UliAhqgAjRNQZOp6qqLM5tN1f4NQyh8N4YD6zFIcOR0347TRwMhsPcSNOWIjLVAsjEHgACyrBt0dYQXLNMObepA5fb45t3bSCdEcdl40mSX0ADoyEkeIJXXhXcImekEDK5QzSq6EK6z3IgA

### 💻 Code

```ts
type IndexType = Partial<{ [key: string]: () => string }>;
class Indexless implements IndexType {} // OK
class Indexy implements IndexType { // Error
	dexy() {
		return 'dexy';
	}
}
class IndexLite implements IndexType { // OK
	constructor() {}
}

type SpecificIndex = Partial<{ [key: `@${string}`]: () => string }>;
class Unspecific implements SpecificIndex { // Error
	yo() {
		return;
	}
}
class SpecificallyUnspecific implements SpecificIndex { // Error
	value = "value"
}
```

### 🙁 Actual behavior

A class implementing a partial type with includes an index signature is marked as an error if it has any method or value defined. If nothing is defined, or only a constructor is defined, it is without error.

### 🙂 Expected behavior

A class should either be marked as an error when implementing any partial type that includes an index signature, regardless of what's defined on the class – or TypeScript should allow and support partial index signature types.

There should be a consistent way with which TypeScript deals with index signatures being part of a type that a class implements.

**Comment by RyanCavanaugh** [comment]
The consistent rule on display here is that when a target type is all-optional, which `Partial<T>` is for all `T`, then a source type must either be empty, or have at least one member in common with the target type. See https://github.com/microsoft/TypeScript/pull/16047

**Comment by StelFoog** [comment]
If I understood the principle correctly this would be an example of intended behaviour:

```ts
type Foo = {
  bar: boolean;
  zot: string;
  other: number;
}

class Baz implements Partial<Foo> { // OK
  bar: boolean;
  zot = "string";
  constructor() {
    this.bar = true;
  }
}
class Wrong implements Partial<Foo> { // Error – ts(2559)
  log() {}
}
```

But when an index signature is involved it seems to result in an error, even when two out of three properties are in common:

```ts
type Foo = {
  bar: boolean;
  zot: string;
  [key: `@${string}`]: () => void;
}

class Baz implements Partial<Foo> { // Error – ts(2420)
  bar: boolean;
  zot = "string";
  constructor() {
    this.bar = true;
  }
}

class Baz2 implements Partial<Foo> { // Error – ts(2420)
  bar: boolean;
  zot = 'string';
  constructor() {
    this.bar = true;
  }

  "@test"() {}
}
```
