### ISSUE TITLE
Inconsistent literals inference in reverse mapped types

### ISSUE THREAD

**Issue by jfet97** [microsoft/TypeScript#55795]
### 🔎 Search Terms

reverse mapped type literal inference

### 🕗 Version & Regression Information

This is the behavior in every version I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMAeAKHngBV4QAPQ1YI+Ab3gAcYdOAueCRhZUAcwDc8VMULABHaSRDAACj36CMwsfAC+egDTkAfAAocAIwBW8+AG0A0vBHwA1iACeORDQC6A6kdfPQBKAPFycjA8Eng4ImQIDHgAXgIZUzZKLnUBACJEHBw8oypFWXlsspllNV58i1gS7N1SukYYKAaoAC9m3RCI8njEjAiAenGAPQB+IA

### 💻 Code

```ts
declare function test<
  T extends { prop: string; nested: { nestedProp: string } },
>(obj: { [K in keyof T]: T[K] }): T;

const result = test({
  prop: "foo",
  nested: {
    nestedProp: "bar",
  },
  extra: "baz",
});
```

### 🙁 Actual behavior

The type parameter `T`, that is the type of `result` too, is inferred as:

```ts
{
  prop: "foo";
  nested: {
      nestedProp: string;
  };
  extra: string;
}
``` 

But it's unusual that `prop` is inferred as `"foo"` instead of `string`, especially since there are no `as` assertions being used and `T` is not a `const` type parameter.

### 🙂 Expected behavior

`T` inferred as:

```ts
{
  prop: string;
  nested: {
      nestedProp: string;
  };
  extra: string;
}
```

**Comment by Andarist** [comment]
I think that the current behavior is expected (although somewhat surprising at first).

The basic rule is that a literal type is preserved when the inference target is a type variable and when it has a primitive constraint. For example:
```ts
declare function test1<T>(obj: { prop: T }): T
test1({ prop: 'foo' }) // string

declare function test2<T extends string>(obj: { prop: T }): T
test2({ prop: 'foo' }) // "foo"
```

So if we look at just this it's surprising that with a reverse mapped type the literal types might be preserved as its properties. However, the inference of reverse mapped is somewhat different. It's actually more than a single inference process! Inferring `T` only involves inferring a reverse mapped type with deferred properties~ and each property is inferred only when "requested" and each such inference is separate/independent. Conceptually, it's a way of creating a **dynamic** list of type parameters.

So if we take a look at it from this perspective then everything checks out and obeys our basic rule. The inference target of that secondary inference of a reverse mapped type property is `T[K]` and `T["prop"]`'s constraint is a primitive type. So a literal type gets preserved here.

We also need to remember that reverse mapped types predate `const` type parameters. Without them and the behavior described above it's still possible to infer literal types for `T[K]`:
```ts
declare function test<T>(obj: {
  [K in keyof T]: T[K] extends string ? T[K] : never;
}): T;

test({
  a: "foo",
  b: "bar",
});
```

but that's not as ergonomic as:
```ts
declare function test<T extends Record<string, string>>(obj: {
  [K in keyof T]: T[K];
}): T;

test({
  a: "foo",
  b: "bar",
});
```

I must say though that I built this mental model for myself knowing how things work under the hood. The behavior looks certainly more confusing if we don't have that knowledge. I think that it could be explained in the docs through this lens (without going too much into implementation details, of course, the core concept is just that "reverse mapped type properties have their own standalone inferences"). 

It's also that this behavior has been likely for a long time so it's probably just not worth changing it anyway.
