### ISSUE TITLE
JSDoc does not support @this when using an arrow function as method in class

### ISSUE THREAD

**Issue by a92126** [microsoft/TypeScript#55796]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.3
- OS Version: win10

Steps to Reproduce:

1. giving these code
```
/**
 * @typedef {{sayHello( wording: string )}} CanSayHello
 */

class A{
 /** 
  * @this {CanSayHello} 
  * @word {string}
  */
 morning = who => this.sayHello(“morning,"+who);
}
```
2. this.sayHello in method morning was not identified. Prev issue can be found [here](https://github.com/microsoft/vscode/issues/22264#issuecomment-285262598)

**Comment by a-tarasyuk** [comment]
@sandersn Should the compiler throw an error that arrow functions cannot have 'this'? [Like it does for TypeScript files](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJLIN4ChnJiACjgC5kBnMKUAcwEpSA3Ae2ABMBuLAXyywQBs4ZMsgDCmHMgAOyALzICYABbAypVABpkcWnIB8yZaoB0UorU48gA). Or should `this` be resolved from the `tag`?"

**Comment by sandersn** [comment]
The compiler should error just like TS does. (Although inside a class `this` is resolved, so only an error on the tag, not on `this.sayHello`.)

**Comment by DanielRosenwasser** [comment]
Wait why is this a bug? You can't change the type of `this` in an arrow function because it's bound.

**Comment by sandersn** [comment]
It's a bug because the TS expression `(this: CanSayHello, word: string) => this.sayHello('x')` gives an error on (1) `this: CanSayHello` (2) `this.sayHello`.
The equivalent JS+JSDoc expression has error (2) but not (1).

I think that @a92126 expected no errors and `this: CanSayHello` but that doesn't work with the semantics of arrow functions.
