### ISSUE TITLE
Unions: Improper typings in certain situations 

### ISSUE THREAD

**Issue by Sixstring982** [microsoft/TypeScript#55792]
### 🔎 Search Terms

"union", "invalid" "type"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about (type assignment)

### ⏯ Playground Link

https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true&ts=5.2.2#code/MYewdgzgLgBAygFQIICUEEkByBxA+gdQFEkAFAeUzhgF4YBvAKBmZgHcBLALwEMAnAEwBcMAOTRuAMwkiANExZ9gACwCmvYSIBGIViIYBfGNwgxQkKAygBPAA4qYKbsHu0A1iqsgJMa3a-xkNCw8IlIKOEtbe3wVbhtwGh8o-0RUDBwCYnJKAG1HZwBdBki7eDtgdgl2YDgoPig1EidXAB4UGBUADwawfhN3T29fFRTA9JCs8IA+RJRY-nAAGysWxhYYXicVYRR5ZnFeKHYwAHMYuPBhYdG04Myw3JQi-Sni4fg6w8bmmnkAHzKKgqVRqnwavCawFaIg4PAEIlezABcHKlWqtXq3yhLREilUvARxQkAFcwMAjgkTiooBjDsczrF4mAWiQOt0VL0TLTwZDXFMABSbZzCEg5ERClQiAoAShFYoOR1O5yZUvo8l41OJvDAMH5axYsL4QlE2l0cnWeLUGlNsnkhmMpnA0GlOQlz2KZmgMHEUkSVJpYPpyvALRRQLRoMxEOaOMN8KmAphXCNImlDAA9On1jAAHoAfg9TpAixUADpFiATvyfRJpUA

### 💻 Code

```typescript
const STARTING_WEAPONS = {
    wizard: 'staff',
    archer: 'bow'
} as const
type Race = keyof typeof STARTING_WEAPONS
type Weapon = typeof STARTING_WEAPONS[Race]

type SpecificStarterPack<R extends keyof typeof STARTING_WEAPONS> = Readonly<{
    race: R
    startingWeapon: typeof STARTING_WEAPONS[R]
}>

type StarterPack =
  | SpecificStarterPack<'wizard'>
  | SpecificStarterPack<'archer'>

function getStartingWeapon<P extends StarterPack>(race: P['race']): P['startingWeapon'] {
  return ({
    wizard: 'bow',
    archer: 'bow',
  } as const)[race]
}

const staff = getStartingWeapon<SpecificStarterPack<'wizard'>>('wizard')
//     ^?  (const staff: 'staff')

console.log(staff)  // prints 'bow'
```

### 🙁 Actual behavior

The above code sample prints `'bow'`, but `staff` type-checks to `'staff'`.

### 🙂 Expected behavior

I would expect there to be some type error in the definition of `getStartingWeapon`. As it stands, someone can call it and get it to return a value that has the wrong type.

**Comment by jcalz** [comment]
Looks like
* #54160 : Design Limitation
* #51180 : Bug

Not sure which one this would be (or why those two are categorized differently from each other)
