### ISSUE TITLE
for in loop

### ISSUE THREAD

**Issue by GooseOb** [microsoft/TypeScript#55809]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

```ts
type Dict = Record<'a' | 'b', any>;

const dict: Dict = { a: 1, b: 2 };

const arr: (keyof Dict)[] = [];

for (const key in dict) arr.push(key);
```
does not work, works only with `key as keyof Dict`

**Comment by MartinJohns** [comment]
This is intentional, because objects are not sealed and may have more properties not covered by `keyof T`.

Did you try to search for existing issues before?

**Comment by GooseOb** [comment]
I tried to search but haven't found anything. What are cases in which `keyof T` doesn't cover all the properties?

**Comment by MartinJohns** [comment]
```typescript
const src = { a: 1, b: 2, c: 3 };
const dict: Dict = src;
```

Objects are not sealed. They're allowed to have additional properties not specified by the type.

**Comment by GooseOb** [comment]
Ok, thank you
