### ISSUE TITLE
Intersection on indexing a conditional type object

### ISSUE THREAD

**Issue by MaximilianFullStack** [microsoft/TypeScript#55804]
### 🔎 Search Terms

"indexing a conditional type object", "type mismatch indexing a conditional type object ts"

### 🕗 Version & Regression Information

- This exists on 5.1.6 and latest (5.2.2)

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wNIFECaBlOAXjgG0ByBAQxjIBo4yATCAczoYDMIR2zore3MgF04lVIhToAsACg5oSLElpMuPAH0AKjgAKWDQFkAgrt0BJAHIBxInADecuImoAuBhDAwAllLpO4ZhZ3Pi9fNH9ZZy4QEM8fP1oA-koQqEpkFmBI5240jKzIgF8xCSRVOQVwaHgYAE8wYDgMYDqANUoAGwBXJuJHKLh48NR3dChvTJJhAPTM4Hd7OABbSYB+d2Ru5YAjYCgAbhXKEA24Ld39uCK5G-lZRRq4esa4cxhgZYl+gJIMOEmcAAFC9gBAOM11ABKEgXPZQYTCM4tdpdXokEENMEQ7D4bR6AwmMxWawwjCI26Ve6dYDwDLeZZdUZvD5fOz2KgwdwkABEIB59B5dQFcD5POEdzkXCgwJp8AA1q0hjjoQ4AgB6dVwbrIcLKuCQVCobw7GlwABuaKaoIkgLIKI6PWyATlcBAdnpjM6qBIirqM3uzk1cCwACVQwB5UPuPZIZbACQZAHID5QVDABAJZBwADuAAtgNmYFA6pMWM8IHB07UCxarQFPUzfa1RMQQJTZEA

### 💻 Code

```ts
export const KEYS = ['cat', 'dog', 'fox', 'orca', 'ox'] as const

export const KEYS_TYPE_MAPPING = {
  cat: 'options',
  dog: 'options',
  fox: 'options',
  orca: 'range',
  ox: 'range',
} as const

export type KeyValue = {
  options: string[]
  range: { min?: number; max?: number }
}

export type Items = {
  [K in (typeof KEYS)[number]]?: KeyValue[(typeof KEYS_TYPE_MAPPING)[K]]
}


let animals: Items = {cat: ["x", "y", "x"]}

for (let key of KEYS) {
  // union of possible value types in 'KeyValue'
  let x = animals[key]

  // ERROR: becomes an intersection when trying to set the value
  animals[key] = x
}
```

### 🙁 Actual behavior

After creating a object type where each key has a mapped value type, an intersection of said types is created which causes object[key] to not be the same type as object[key] when setting a value at an index of the object. 

It should not be an intersection type since the value types never overlap.

### 🙂 Expected behavior

I expected the type of 'x' (when setting it as the value of object[key]) to be the same type as 'object[key]'. Since they both reference the same index in the same object. Also I would expect the type of 'x' and 'object[key]' to be a union of the value types since they do not overlap.

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/55756#issuecomment-1721950988 and #30769.  When `key` is union-typed, as it is here, the compiler doesn’t understand that `key` refers to the same property in both places.  The intersection type arises because that’s the only type that’s known to be valid for any possible `key`.

**Comment by MaximilianFullStack** [comment]
Interesting, I assume the most optimal work around would be to explicitly type each key value as the union then? Unless there's something else that I'm not aware of.

**Comment by Andarist** [comment]
There might be a way to write this in terms of correlated unions created out of mapped types: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-6.html#indexed-access-inference-improvements
