### ISSUE TITLE
`computeCommonSourceDirectory` doesn't work on case-insensitive filesystems

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#5581]
Specifically, we throw `Cannot_find_the_common_subdirectory_path_for_the_input_files`. This is causing our present RWC failures. (Since now we always try to find a common source directory at first, rather than just 'as needed'.)
If `outDir`/`sourceRoot`/`mapRoot` are specified and `rootDir` is not (or some files in the compilation are not within `rootDir`), then the issue surfaces.
Some of our tests are on `D:/` and some are on `d:/` which is causing a mismatch in the computation, and so no common directory can be found.

HOWEVER, this does bring to light another issue: Compilations including files from multiple drives on windows will likely trigger this error as well. (This should never be an issue on 'nix because we'll eventually reach the root and compare empty strings.)

**Comment by mhegazy** [comment]
We should not show the error all the time, as this will break existing scenarios. we should maintain backward comparability and not show the error if it did not show in the past.
