### ISSUE TITLE
Explicit return type should be the same as explicit property definition

### ISSUE THREAD

**Issue by Arlen22** [microsoft/TypeScript#55812]
### 🔎 Search Terms

"generic function return type doesn't resolve implicit assignment", "using explicit types to break circular references", "using explicit types to break circular references"

### 🕗 Version & Regression Information

- I made this in 4.9.5 and checked 5.2.2 in the playground. I have not tested this in previous versions but it most likely applies to those as well. 

### ⏯ Playground Link

[code I expect to work](https://www.typescriptlang.org/play?#code/C4TwDgpgBAygCnAKuCiBOEIB5EBooBKUEAHsBAHYAmAzlDcGgJYUDmAfFALxQDeUAbQDSUFvUYtWUAGRQA1hBAB7AGZREAXQBcsBMkjpMOYRvwADACS8CAXwD0VoTbOcbMvlAD6nnURsAoUEhdOAAxT0QIBhxiMkpaEIiUTh4ACggdeCQUQ2w8KAAiAvYASm5OAEMKEAENAG5-fwBjABsKmjoszyomNBjScmpOhCTITl5-KCgmpQoGNABXJuAlNFSwBYAjFqYmqArgRh0JqamKtDQKkAAZJgYAfkyEcMjoxHZcSagbMomvgICzTaHUS+mgJygADcKi1HoU5CpaAArOQtRE0FEtAr+AKtdrDOCeACyEAAtpsIH1ELFBgkumDxl8ZnNGEsVmtlqtjlAKBAAO6pEo6ak2fAAOglPTQNCehKlOHYtV+3xx-hUCwoyyYs1BUWAnlCGqa-TiQ1ByVSTPZ3N5AqF6jq30+ZwuV1uDB0qRIsrBuRw+CKpXK+2qtU+9q6JPJlIVfC+GGACzQFB5-MSUYpHPZ+FtiSlqX450uNzuwG+JRKDUBeJB9L1ngAjDT4gTRuCvgA5Cqk6A8XMwCRsQUNKZKYAAC0p3F1DANRtSddnACZ8CRgwISGKx5O0GLvBoSqqgfiZ-ql82zfSUHGpl2e9P+4PWMOvtupzxF-rDZqFyNXvqG1XddNzfXd90PGwgA)

[code that actually works, but seems unnecessary](https://www.typescriptlang.org/play?#code/C4TwDgpgBAygCnAKuCiBOEIB5EBooBKUEAHsBAHYAmAzlDcGgJYUDmAfFALxQDeUAbQDSUFvUYtWUAGRQA1hBAB7AGZREAXQBcsBMkjpMOYRvwADACS8CAXwD0VoTbOcbMvlAD6nnURsAoUEhdOAAxT0QIBhxiMkpaEIiUTh4ACggdeCQUQ2w8KAAiAvYASm5OAEMKEAENAG5-fwBjABsKmjoszyomNBjScmpOhCTITl5-KCgmpQoGNABXJuAlNFSwBYAjFqYmqArgRh0JqamKtDQKkAAZJgYAfkyEcMjoxHZcSagbMomvgICzTaHUS+mgJygADcKi1HoU5CpaAArOQtRE0FEtAr+AKtdrDOCeACyEAAtpsIH1ELFBgkumDxl8ZnNGEsVmtlqtjlAKBAAO6pEo6ak2fAAOglPTQNCehKlOHYtV+3xx-hUCwoyyYs1BUWAnlCGqa-TiQ1ByVSTPZ3N5AqF6jq30+ZwuV1uDB0qRIsrBuRw+CKpXK+2qtU+9q6JPJlIVfC+GGACzQFB5-MSUYpHPZ+FtiSlqX450uNzuwG+JRKDUBeJB9L1ngAjDT4gTRuCvgA5Cqk6A8XMwCRsQUNKZKYAAC0psuJZMzWDrDE8ACYUrrF4bNakF-ql-gSMGBCQxWPJ2gxd4NCVVUD8Wud82zfSUHGpl2e9xU3zYIPWMOviep3TWcY23RtV1Ajcmi3EZXn1Bs9wPI8ALPC8rxsIA)

### 💻 Code

```ts

type SPPTypeTree<T, R extends string> = { [K in string & keyof T]: SPPTypeTree<T[K], `${R}/${K}`> } & { __: R }
type SPPF_Test<T extends SPP_Type> = (e: SPPTypeTree<T, "">) => any[];

class SPP_dir<T extends SPP_Type> {
  constructor(public attr: {
    arrayList?: SPPF_Test<T>,
  }) {

  }
}

class SPP_Type {
  val?: "kfdsjklfdsjkl"
}
class SPP_Member<T extends SPP_Type> {
  constructor(ctor: { new(): T }, ...dirs: SPP_dir<T>[]) { }
}
function SPP_Test_Func<T extends SPP_Type>(
  ctor: { new(): T; },
  arrayList: (x: SPPTypeTree<T, "">) => any[],
): SPP_Member<T> {
  return new SPP_Member(ctor, new SPP_dir({ arrayList }));
}

class SPP_Test_1 extends SPP_Type {
  Name = new String();
  other = SPP_Test_Func(SPP_Test_2, x => [x.other.__])
}

class SPP_Test_2 extends SPP_Type {
  Name = new String();
  other = SPP_Test_Func(SPP_Test_1, x => [x.other.__])
}

```

### 🙁 Actual behavior

The lines 

```
other = SPP_Test_Func(<class>, x => [x.other.__])
``` 

give the error 

```
Type of property 'other' circularly references itself in mapped type '{ val: SPPTypeTree<"kfdsjklfdsjkl", "/val">; Name: SPPTypeTree<String, "/Name">; other: SPPTypeTree<any, "/other">; }'.
``` 

which is true, but changing the property definition to 

```
other: SPP_Member<SPP_Test_1> = ...
``` 

makes this message go away.

### 🙂 Expected behavior

I would expect that the explicit return type of the function SPP_Test_Func would be enough to also make the message go away since there is no question what the inferred type is supposed to be. If setting the type on the property itself makes it go away, setting the same type (with explicit generics or inferred from explicit arguments, as in my example) on the return type of the function should also be enough.

**Comment by RyanCavanaugh** [comment]
Type circularities may issue an error. In some cases there is deferred checking that will let you get away with a circularity, but those deferrals are not contractual guarantees that any equivalent representation will also be deferred.
