### ISSUE TITLE
Better responses for TSX getSyntacticClassifications

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5582]
Currently its all `identifier` as shown below: 

![image](https://cloud.githubusercontent.com/assets/874898/11056021/5efb6a46-87d1-11e5-9fe3-313ac4d1f5ce.png)

(I haven't wired up the highlight response with the syntactic response so don't mind the colors just yet :rose:)

Would be great if it was something like TSX identifier etc. Would allow me to implement tag matching better.

refs https://github.com/Microsoft/TypeScript/issues/5545

**Comment by basarat** [comment]
I'll PR soon :rose:

![image](https://cloud.githubusercontent.com/assets/874898/11056729/d2a080ba-87d8-11e5-9480-82416dc41f8f.png)

**Comment by basarat** [comment]
PR sent : https://github.com/Microsoft/TypeScript/pull/5583 :rose:

**Comment by mhegazy** [comment]
thanks @basarat
