### ISSUE TITLE
Using method type of derived class in base class

### ISSUE THREAD

**Issue by bruderstein** [microsoft/TypeScript#55827]
### 🔎 Search Terms

abstract derived this 
ReturnType<this['method']>

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this, derived types

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQCEEGcoElKyIqoDewqFqIAJgFypYQzgDmA3MAL7CgHzJoAogA9oYalGqoooqOKwZsePkTRlK00TAT1GzMOy48EAIz3IIqJABtsCzDgBiAe2elylU+aSWWUCAAqABasABQAlPQOytD8KBwaOIEhBqEQKSz0AEr+AK4wYAEAngAOUAA86SBYANoA5H7JrHUAugB84e4aFAD0PVQAtiXWUANyEAgQIM5gVDAwUCMAbgiQHhTc3MA2dqgubjJi1PZK+10UjcFhkagiR5LnlAsQ+bMkVHSodXCudQA0miYOi+JgQMDqqE4CQ2PEoWGcYwAsv4gs5qBFHqg+qgrgpYDBnDAsACdiABqxUOk0BBSmgfjBKSEsAA6S4ZDHUZxQBRgZyWAaTJBBRloHIvArFMqVJn1NnNdrrLH9AByfOpQUmqAA+lSGAgxlYENZrFrUCU7NzUNZnAB3WCoTk2sAAuAEgaoZy5CBYGjqtA7LBYRVVFlJK6pEOs-zhlgRcIcRXY3HSeaEhSuhGoG0gKqzEOoMbpNFZnPC3VYfVofGEgFQJZyRmeljCjPuz3e31USzmwPc4NM5lh9nqboUGj0b6-P6KjSHbQT0HgxWcePrTY8JAzRioH7OfCMVbEAC8qDAUBte1cEQ42IAguJUEV-ACc1QFAB5ADSqCCsCgzOAXd9wmMAUEHaN2SAsAD1A-85VScJV2AbEABkQAAa3PaooABfMbUJdDiTNOwKQQAtBQySlaUA1xgMPf8hzCEdR3HL5d3+GdKDnYE6kXOouCQ5D+mTTd5igHxrCKFMCSJAFsBFVAAANuMU1BMKk6oC2qH0DCE1AAAFqyJegACYAGYABYAFYaL3aCQLAxjUmY7pWMnZx+NHXp+m4hcwQhJUtMDVgBLYIA

### 💻 Code

```ts repro

interface BaseInterface {
    id: string;
}

interface Extended extends BaseInterface {
    extra: string;
}

abstract class BaseFoo {
    abstract getThing(): BaseInterface;
    setThing(thing: ReturnType<this['getThing']>) {
      // implementation irrelevant
    }
}

class Foo extends BaseFoo {
   getThing(): Extended {
     return { id: 'foo', extra: 'bar' };
   }

   someMethod() {
    // This errors, claiming the type for this.getThing() does not match the ReturnType&lt;this['getThing']>
    // Note that _the same call_ passes lower down, from outside the class
    this.setThing(this.getThing());

    // This errors from within this method with the same error, even though from outside it passes
    this.setThing({
        id: 'foo',
        extra: 'bar'
    });
   }
}

const fooInstance = new Foo();
// And yet, it is OK here.
fooInstance.setThing(fooInstance.getThing());

// Likewise, this works, passing a matching type
fooInstance.setThing({
        id: 'foo',
        extra: 'bar'
});


// This correctly errors, as the `extra` key is missing
// @errors: 2345
fooInstance.setThing({
        id: 'foo'
        // extra: 'bar'  // missing
});
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/FASwdgLgpgTgZgQwMZQAQCEEGcoElKyIqoDewqFqIAJgFypYQzgDmA3MAL7CgHzJoAogA9oYalGqoooqOKwZsePkTRlK00TAT1GzMOy48EAIz3IIqJABtsCzDgBiAe2elylU+aSWWUCAAqABasABQAlPQOytD8KBwaOIEhBqEQKSz0AEr+AK4wYAEAngAOUAA86SBYANoA5H7JrHUAugB84e4aFAD0PVQAtiXWUANyEAgQIM5gVDAwUCMAbgiQHhTc3MA2dqgubjJi1PZK+10UjcFhkagiR5LnlAsQ+bMkVHSodXCudQA0miYOi+JgQMDqqE4CQ2PEoWGcYwAsv4gs5qBFHqg+qgrgpYDBnDAsACdiABqxUOk0BBSmgfjBKSEsAA6S4ZDHUZxQBRgZyWAaTJBBRloHIvArFMqVJn1NnNdrrLH9AByfOpQUmqAA+lSGAgxlYENZrFrUCU7NzUNZnAB3WCoTk2sAAuAEgaoZy5CBYGjqtA7LBYRVVFlJK6pEOs-zhlgRcIcRXY3HSeaEhSuhGoG0gKqzEOoMbpNFZnPC3VYfVofGEgFQJZyRmeljCjPuz3e31USzmwPc4NM5lh9nqboUGj0b6-P6KjSHbQT0HgxWcePrTY8JAzRioH7OfCMVbEAC8qDAUBte1cEQ42IAguJUEV-ACc1QFAB5ADSqCCsCgzOAXd9wmMAUEHaN2SAsAD1A-85VScJV2AbEABkQAAa3PaooABfMbUJdDiTNOwKQQAtBQySlaUA1xgMPf8hzCEdR3HL5d3+GdKDnYE6kXOouCQ5D+mTTd5igHxrCKFMCSJAFsBFVAAANuMU1BMKk6oC2qH0DCE1AAAFqyJegACYAGYABYAFYaL3aCQLAxjUmY7pWMnZx+NHXp+m4hcwQhJUtMDVgBLYIA)

### 🙁 Actual behavior

From inside the class method, calling `setThing` with a valid object errors. From outside the class (using an instance), the exact same call passes.

### 🙂 Expected behavior

The method call should be valid with same type from both inside and outside the class.

### Additional information about the issue

The same behavior can be seen even if the return type of `getThing` is a simple type such as `string` - the example is just more of a real world situation.

**Comment by fatcerberus** [comment]
Given your current implementation:

```ts
interface Special extends BaseInterface {
    special: string;
}

class Bar extends Foo {
   getThing(): Special {
     return { id: 'foo', special: 'bar' };
   }
}

const bar = new Bar()
bar.someMethod();  // oops, now the thing is the wrong type
```

It's not really possible to get this pattern to typecheck from inside a class[^1] while still being generic over subclasses so TS rejecting it out of hand seems like the most sensible behavior.

[^1]: I'll concede that `this.setThing(this.getThing());` is (probably) safe, but making the compiler understand that *that's* safe would be a lot of implementation effort for no real gain because presumably you want to set things *other than* the one that's already been set, in which case... well, refer back to above :wink:

**Comment by DanielRosenwasser** [comment]
It's not known what `this` will be at runtime - `this` is effectively deferred and generic.

But if you know better, you can always specify and restrict the type of `this`.

```ts
interface BaseInterface {
    id: string;
}

interface Extended extends BaseInterface {
    extra: string;
}

abstract class BaseFoo {
    abstract getThing(): BaseInterface;
    setThing(_thing: ReturnType<this['getThing']>) {
      // implementation irrelevant
    }
}

class Foo extends BaseFoo {
   getThing(): Extended {
     return { id: 'foo', extra: 'bar' };
   }

   someMethod(this: Foo) {
    // This now works.
    this.setThing(this.getThing());

    // This now works.
    this.setThing({
        id: 'foo',
        extra: 'bar'
    });
   }
}
```

[Playground link here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgEJwM4QJLmvJZAbwChlzlgATALmQzClAHMBuEgXxJNElkRQBRAB6QQVCFWQRREcRjSYcefoVIVpoqHDoMmINp25wARnsRhkCADaYF6LADEA9s+JkKp8wkvMIYABUACxYACgBKOgdlPgIIdg0sQJCDUIB9MBTmOgAlfwBXKBAAgE8ABwgAHkzgDABtAHI-ZJYGgF0APnD3DXIAej7KAFsy6wghuTA4MGBnEEooKAgxgDc4cA9yLi4SGztkFzcZMSp7JUOe8mbgsMjkERPJS4olsEL5okpaZAaYVwaADSaRg6H4mOBQBrIDgJLbcCgYZwTACy-iCziooRqGDoh266goA2QNwUIGcAHdkOTnFAANYYAB0m2Q2IZSRuqVZ1yyEXC7GZRJJyDJlOpdMZzNZ7J5BN6Xzov3+AOZGmO2gV4MhzI4fM22xIQA)

**Comment by bruderstein** [comment]
That makes total sense, thank you for explaining.

I'm really sorry I thought this was a bug - the real case is much more complex with multiple layers of mapped types, and it took a while to get it down to this minimal example, didn't think about `this` not being provably consistent in the method.

**Comment by DanielRosenwasser** [comment]
Don't sweat it!
