### ISSUE TITLE
Sourcemaps with decorators

### ISSUE THREAD

**Issue by adrianhara** [Microsoft/TypeScript#5584]
Hi,

I'm trying to get source maps working with typescript and it looks like as long as I don't use decorators they work just fine. Once I use some decorators it looks setting a breakpoint in Chrome dev tools results in the breakpoint being set elsewhere instead of where the line where i clicked to set it.

Is there some known issue about this not working currently? I use typescript 1.6.3 with "experimentalDecorators" flag set to true.

Thanks!

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look.
