### ISSUE TITLE
Suggestion: Allow rest parameters to be ArrayLike instead of strict arrays

### ISSUE THREAD

**Issue by diegommm** [microsoft/TypeScript#55846]
### 🔎 Search Terms

"arraylike rest parameters"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _rest parameters_

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230923#code/PTAEGUFNILlALALogDgZxiAJpAbpAGwHsVIAnAOgFsiAvASwIIEMKiyBzYSAOwFoAquGBYiAYzTAA4sTRpmZAJ7AAQszSQAbABYAxIniQA+gFce9MURxGUZIgCMCkKgCgAZmbGJ6RHqHuKiJBoACpEaho6ABQBQRigAIJkZMyKADL0ANaQADw8JlT25AB8AJSgAN4uoDWgIKBoBPQcSASKoGLwzDwckFigbnZUoAaQoOzN9DzMBKCQAB7MVChOADT+JoigzF4mM22gAO7smWgjhg1LkNW1ljxoW-ZT4IhkUxygALwQr+8Ug0QqABhKyQAAKRCmiAozBQK0UUTMODcUz6qxutVq9R40H6iCIoBwfEQilI5zGEw4UxmoFwMxMY3xHV8+DIW3oWyZaEBkAM71AHMJRGCPAA5FscX0MZi6mAmUUKAADF5vHr-IYgnAQqEwuFtRUCs7I1H9Q4c+CgMjBLYoBRXIJkNDrbkCxCis5udhiKUyrFygkmDTbPwKFLtIhuUD5QrkJ1HQxW9Su8Y8A6B4KgRVOHoGA3dfqQHYWiPkgU8HDzYLSzGxDNJsyZHhEQ4hs7RopkADaAF1SgBuaVWxAmMh+ez45gxZ6-Hr9lwAXxcLjuD0tvIAjF9-IFgmEIlptFEcYdQCEFogAKI8Sw4MhRUoUXg3yBRABEzFAgABAUCAAA3AAA7oCAOGmoCAHwbgAhu6+pRziuRBOBQxAcFEQ7rv2sqgK+ACa4AACIXhwQLYYcmQAJJAgkxEAPLMAA6vAiiETwmjMBer5LiuWxuMw2RJGQW5VJi2YcAYcAAMzopiAAMcAAJwAOzibU64yQAHApNQAEwydJC7Lr4q6cdxyRgvM7TfMeoBgnYJlRAZkA8es-G1L0iBRA4ABWcDdIo6y2CQcAPKqHClI5vowXBCFRL5KBzr6NRDiOfjuZ2UXdgOmKLvOpRsXpWxDupW61qE4TqAeNlcXZRkmah9SvoJBisbFjVNc1vo1RJDUtZ1XV+uh64dd1A1NTV6msWFkDwUQiF5dVYCYdRABSbmsbp9yweNEV5V8nzfIVe4ldE5lnvMl7XqCd4Pk+oJvsw9hiJBUF9mhrwMkAA

### 💻 Code

```ts
function printItems(...params: ArrayLike<number>){
    const l=params.length;
    for (let i=0; i<l; i++)
        console.log(params[i]);
}

const fakeArr = {length: 3, 0: "a", 1: "b", 2: "c"};
printItems.apply(undefined, fakeArr);
```

### 🙁 Actual behavior

Two errors:

1. In the definition of the rest parameters: `A rest parameter must be of an array type`.
2. In the call to `printItems.apply`: `Argument of type (...) is not assignable to parameter of type 'any[]'. Type (...) is missing the following properties from type 'any[]': pop, push, concat, join, and 25 more`.

### 🙂 Expected behavior

No errors thrown in either case. I should be able to have an `ArrayLike` as rest parameter. Check the Playground link for a real life example using `String.fromCodePoint.apply` to encode UTF-8 strings to base64 based on an example from MDN (with a small change).

**EDIT**: So it could be actually two things, happy to break down into different issues but they are too interrelated:

1. Allow rest parameters to be `ArrayLike` instead of just `Array`. This allows explicitly saying we're not changing anything in the incoming rest parameters argument.
2. Add an overload on `CallableFunction.apply` that accepts an `ArrayLike` instead of `Array`. This one looks harder, since I don't see an obvious way of linking `CallableFunction.apply` to the actual implementation of the function so that the types can be narrowed down to know an `ArrayLike` is acceptable.

**Comment by fatcerberus** [comment]
It doesn’t really make sense to say the rest parameter in the function definition is anything other than a real array, since it’s *guaranteed* to be one by the JavaScript runtime—even if called with `.apply()`.

> This allows explicitly saying we're not changing anything in the incoming rest parameters argument.

A rest parameter is always a newly minted array, so any such changes won’t be visible to the caller anyway.

> I don't see an obvious way of linking `CallableFunction.apply` to the actual implementation of the function so that the types can be narrowed down to know an `ArrayLike` is acceptable.

No such linkage is necessary; whatever is passed to `.apply()` will be copied into a new array, which is what the function will see as its rest parameter.

**Comment by diegommm** [comment]
I see you're right. Thanks for the clarification, I'm closing this as won't fix.
