### ISSUE TITLE
Object.assign not inferring

### ISSUE THREAD

**Issue by dev-ardi** [microsoft/TypeScript#55853]
### 🔎 Search Terms

typescript Object.assign

### 💻 Code

```ts
function foo() {
    const a = {a:1, b:2}
    const b = {}

    Object.assign(b,a)
    return b
}
```

### 🙁 Actual behavior

`ReturnType<foo>` is `{}` when
```ts
{
    a: number;
    b: number;
}
``` 
could be inferred

**Comment by MartinJohns** [comment]
Please remember to completely fill out the issue template.

This is working as intended. `Object.assign()` does not propagate type information to it's `target` property, so TypeScript is not aware of any changed type of `b` and the type remains `{}`.

**Comment by dev-ardi** [comment]
Shouldn't it?

**Comment by fatcerberus** [comment]
> The only way to change the type of another variable like these are assertion functions, but these are not allowed to return anything

I'm pretty sure there's a feature request for that, but I can't find it.

**Comment by whzx5byb** [comment]
> I'm pretty sure there's a feature request for that, but I can't find it.

https://github.com/microsoft/TypeScript/issues/40562
