### ISSUE TITLE
JSX is still not transformed to `React.createElement` when inside spread with target >=`ES2018`

### ISSUE THREAD

**Issue by bob-difronzo** [microsoft/TypeScript#55858]
### 🔎 Search Terms

JSX, spread, React.createElement

### 🕗 Version & Regression Information

Issue is first seen in `5.1.6`, and forward to `5.2.2` and the current nightly version.

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=5&ts=5.2.2#code/DwYQ9gtgDgBATgSwOYAsAuBeA3sAJggNwD4APYAen2IF8YsA6RrGAdzjADskAuGPQ0hSpFq1ckQCwAKCA

### 💻 Code

```tsx
<Comp right={<div>x</div>} {...{ wrong: <div>x</div>}}/>
```

### 🙁 Actual behavior

```js
React.createElement(Comp, { right: React.createElement("div", null, "x"), wrong: <div>x</div> });
```

### 🙂 Expected behavior

```js
React.createElement(Comp, { right: React.createElement("div", null, "x"), wrong: React.createElement("div", null, "x") });
```

### Additional information about the issue

The same bug seems to have been fixed in #54425, but only when the target is `ES2017` or below. When target is set to `ES2018` or above the issue still exists.

**Comment by Andarist** [comment]
This one is also related: https://github.com/microsoft/TypeScript/pull/55008 . Both of the mentioned fixes touched `transformJsxAttributesToExpression` but the fix likely also needs to be introduced to `transformJsxAttributesToProps`. I'll put up a PR for this soon.
