### ISSUE TITLE
Nested objects are not checked

### ISSUE THREAD

**Issue by vaynevayne** [microsoft/TypeScript#55852]
### 🔎 Search Terms

```jsx
type TreeNode = {
name:string
} 



const authNameMap: Record<number, TreeNode> = {};

const a = authNameMap[1].name
```

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgThCA5A9gE2gXigbwFAB2AhgLYQBcAzsHAJYEDmeAvlHu3gMYoHVREBXYAAskpCAFkiYclABKEbnDQAeAgJIAjCHAA0sBMnQQAfFGw5mAbnbdewfuf5DR4qWADaARgC6AOmIyPCA

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

ts Verification passed

### 🙂 Expected behavior

ts Verification not passed

### Additional information about the issue

<img width="622" alt="image" src="https://github.com/microsoft/TypeScript/assets/124666577/f71f3943-0eca-49c2-8019-4b1d4a1fdc3c">

**Comment by MartinJohns** [comment]
This is working as intended. This is what the [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) compiler option was added for. When you enable it the code will error.
