### ISSUE TITLE
tsconfig: noDom option to exclude DOM APIs?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/TypeScript#5585]
I would like to use TS in an environment where there is no DOM (e.g. node.js). If I leave the default options of tsconfig.json on, I still get completions for DOM related members like "window".

I can turn this off by setting noLib: true in the tsconfig.json but then I have to manually include all d.ts files, even from ECMAScript.

Is there any way I can tell TS to not include DOM APIs?

**Comment by mhegazy** [comment]
this is tracked by https://github.com/Microsoft/TypeScript/issues/4168.

For now, if you include lib.core.d.ts explicitly in your project, it should do the trick.
