### ISSUE TITLE
Object.assign breaks after 4 arguments

### ISSUE THREAD

**Issue by dev-ardi** [microsoft/TypeScript#55854]
### 🔎 Search Terms

object.assign 5 arguments

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=18&ssc=2&pln=1&pc=1#code/GYVwdgxgLglg9mABMOcAUBKRBvAUIgxCBAZykQENEBeHCgLgEYBffQ4sMxAIxp2-oAmVoSKlyEPtghCR7cYgAmUxfQAsrXGwIAnAKZQQOpAHluAKz3QAdBRIkYAczBoKAGm5uIbxRlytQSFgEHgodTBxtMU5yKlpsBhYoji5eeIFhZIVJeJlM0RTyZXjVDS0o-UNjRDNLGzsHZzRsZjdKDy8fP2YgA

### 🙁 Actual behavior

Bar has return type {}

### 🙂 Expected behavior

Bar has the correct inferred type

### Additional information about the issue

this breaks because ObjectConstructor defaults to `any` after 3 source arguments
```ts
assign(target: object, ...sources: any[]): any;
```

**Comment by MartinJohns** [comment]
This is working as intended. The overload for so many arguments is explicitly typed to return `any`. Only a specific amount of overloads for the most common usages are specified (for performance reasons). You're free to add your own overloads using declaration merging, if you really require `assign` calls with so many arguments.

Relevant issue: #28323
