### ISSUE TITLE
ObjectTypes Utility Function

### ISSUE THREAD

**Issue by lucasdomanico** [microsoft/TypeScript#55850]
### 🔍 Search Terms

Hello, I would want to create a tuple with the given object types.
For example
```javascript
let o:{ i:number, j:string } = { i:1, j:'a' }
type X = ObjectTypes<o>
// X is [number, string]
```

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

ObjectTypes utility function

### 📃 Motivating Example

```javascript
type X = {
    i: number
    j: string
}
let f = (...a:ObjectTypes<X>) => ...
```

### 💻 Use Cases

1. What do you want to use this for?
Avoid repeating too much code (identifiers and types)

2. What shortcomings exist with current approaches?
Repeating too much code (identifiers and types)

3. What workarounds are you using in the meantime?
Repeating too much code (identifiers and types)

**Comment by xiBread** [comment]
https://github.com/microsoft/TypeScript/issues/39522#issuecomment-656201388

**Comment by fatcerberus** [comment]
Chalk up another vote for https://github.com/microsoft/TypeScript/pull/55746

**Comment by IllusionMH** [comment]
I believe there is no guarantees about properties (in this case related values types) order, so you can't get tuple out object with fixed order.
