### ISSUE TITLE
Feature: Don't care/anonymous parameter

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#5586]
Many functional languages have a don't care parameter/variable that holds values not used by programs.

For example, a function like `Array.prototype.forEach` supplies three arguments to the callback. If the code only needs the second argument (index), it will still have to supply a name for the first one. The programmer can use a don't care parameter as the name of the first argument instead. This improves readability and avoids problem of accidentally shadowing.

An additional keyword/comment may have to be introduced to define which string is used for this purpose as the traditional "`_`" happens to be used by the popular underscore library.

This can also be extended to destructuring code.

**Comment by RyanCavanaugh** [comment]
Just thinking aloud -- would `arr.forEach(( , index) => console.log(index));` look too much like a typo?

**Comment by sandersn** [comment]
I think so. Also, when commas stack up they get hard to count.

**Comment by FabianLauer** [comment]
I agree with @sandersn. How about `arr.forEach((void, index) => console.log(index));`?
Just the first thing that came to mind. Correct me if I'm wrong, but I think this doesn't lead to a conflict with the ES spec as it would be a part of the type system.

**Comment by coreh** [comment]
> Does the already-supported workaround of _, __, __, ... suffice?

Maybe `_` could be special cased, so that you can use it multiple times, then `__` and `___` wouldn't be needed.

```typescript
(_, __, x, ____) => x + 1
```

Would become

```typescript
(_, _, x, _) => x + 1
```

**Comment by LiamGoodacre** [comment]
How about `?`?  For example: `(?, x, ?) => x + 1`.
Given that `_` is a valid identifier name, I don't believe it is appropriate to use here.

**Comment by DanielRosenwasser** [comment]
You could just use an empty binding pattern like`[]` or `{}`.

```ts
arr.forEach(({}, index) => console.log(index));

arr.forEach(([], index) => console.log(index));
```

**Comment by LiamGoodacre** [comment]
@DanielRosenwasser nice :+1:

**Comment by billccn** [comment]
@DanielRosenwasser Sounds perfect. Would be nice if this special use case is documented though.

**Comment by FabianLauer** [comment]
@DanielRosenwasser Great, thanks.
