### ISSUE TITLE
Narrowing with a typeguard fails after object spread 

### ISSUE THREAD

**Issue by Akiyamka** [microsoft/TypeScript#55876]
### 🔎 Search Terms

typeguard narrowing, object spread 

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I recheck handbook about:
- https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/JYOwLgpgTgZghgYwgAgCIBUDyyDeAoZZGAe2IC5kBnMKUAcwG4DkAjOKAfgutpEbwC+ePKEixEKDJgDqwMAAsAQu2QQAHpBAATSmiy5mbKNxr0mQvAmIhqqmwFcoEZVACSlAMoQwyALzIACi0wcj1MAEo-AD5kAEJY4OIAOiMmPAB6dOQPAAcnOC1kBHzIXThWezo8GHsQBDBga2QAWzhQALUKKXCurFkFFwNCYBhA2LUU9kj8QkIJoz9kAHItCHh7ABswJaZCC0IIBycXdy8wDvC0wisbHwBPRfn2BmRM5AfgXR56WOZmJzAjhAQ1mSTBamYQgsb368mI9h8lDyEAKyAA7sQoABrMq6dQ5CD1CBaaq1eqNYEsBEdXoRWmwwYzZAjMZPKDTZhzSZQRYrNZwTbbXbIfZ2SiOZzsU7eC5XIrWWwPfxsl6vLIfL6mPi-Qj-bxAkGEEihCbGgA0nNY7AobMhgmEQA

### 💻 Code

```ts
interface DTO {
  foo: string;
  bar?: string;
}

interface DTOWithBar extends DTO {
  bar: string;
}

const ensureBarIsSet = (dto: DTO) => !!dto.bar;

function main(x: DTO): DTOWithBar {
  if (!x.bar) {
    x.bar = 'default';
  }

  ensureBarIsSet(x);
  const y = x.bar; // y is string!
  return {   ...x  } 
  //         ^^^^
  // Type 'undefined' is not assignable to type 'string'
}

```

### 🙁 Actual behavior

Typescript ignore  type guard if spread used

### 🙂 Expected behavior

Typescript respect  type guard even after spread

**Comment by MartinJohns** [comment]
Duplicate of #54745.

**Comment by fatcerberus** [comment]
More accurately, duplicate of https://github.com/microsoft/TypeScript/issues/42384 (there’s no discriminated union here).

**Comment by Akiyamka** [comment]
From #42384:
> Type guards do not propagate type narrowings to parent objects. The narrowing is only applied upon access of the narrowed property which is why the destructing function works, but the reference function does not. Narrowing the parent would involve synthesizing new types which would be expensive.

Not sure it's my case, I already declare new type, and just want to keep it

**Comment by fatcerberus** [comment]
It’s the same thing.  Your type check narrows `x.bar`; for this to work, it would also need to narrow `x` as a whole.  If you change the function to `return x` you’ll see you get the same error.

**Comment by MartinJohns** [comment]
I posted too early. I just noticed that he does not narrow, because the function `ensureBarIsSet` is pointless. It's neither a type guard nor an assertion function. Just a plain function returning a `boolean`, a result that is then discarded.

**Comment by MartinJohns** [comment]
Just additionally pointing out that the `ensureBarIsSet` function is completely useless. It's neither a type guard, nor an assertion function. Just a function returning a `boolean`, a result that is then discarded.

**Comment by Akiyamka** [comment]
@MartinJohns you right, it's mistake in example
