### ISSUE TITLE
Checking if object is instance of interface

### ISSUE THREAD

**Issue by WarstekHUN** [microsoft/TypeScript#55871]
### 🔍 Search Terms

Check if object is instance of interface
Get keys of interface
Convert interface to class dynamically
Check if an object can be casted into an interface
Convert interface into JSON Scheme dynamically

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

 This function should only return true when the given obj has the exact properties as T. (Of course T can have optional parameters)

```ts
function CheckObjIsInterface<T>(obj: any): obj is T{
  return Interface.IsInstanceOf(T, obj);
}
```

Maybe the compiler can be modified in a way that it will create simple JS classes out of interfaces? Maybe only from specific interfaces?

A decorator could be used to determine if the compiler needs to create a class from the interface.
```ts
@TypeCheckableInterface
interface MyInterface {
  someProp: string;
  otherProp?: number;
}
```

A new type could be introduced that works like an interface but can be type checked.

```ts
struct MyStruct {
  someProp: string;
  otherProp?: number;
}
```

### 📃 Motivating Example

This could bring higher security and better type handling to TypeScript when working with JSON objects.

### 💻 Use Cases

1. What do you want to use this for?

I'm currently developing a websocket library that can send objects as JSON between the client and the server. I wanted to check if the decoded JSON object has the same properties as an interface. Of course, this can be done through hardcoding but I want to do this dynamically.

2. What shortcomings exist with current approaches?

Classes can be used instead of interfaces

4. What workarounds are you using in the meantime?

Probably I'll advise the future-to-be users to use classes or handle the type checking themselves.

**Comment by MartinJohns** [comment]
This is explicitly rejected in the viability checklist:

> This could be implemented without emitting different JS based on the types of the expressions  
> This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

This is definitely out of scope for TypeScript. Your best option is to write a custom user type-guard function.

**Comment by WarstekHUN** [comment]
I know. This is why I wrote the `struct` part. That way the default interface won't be changed. Or are you talking about generating code in JS with other type than in TS? I figured the  `struct` idea could be good if `enum` already exists in TypeScript that outputs JavaScript code which is almost completely different than its equivalent in TS.

**Comment by MartinJohns** [comment]
Generally anything that requires additional code to be emitted is a big no-go for TypeScript. Your proposal would require the validation code to be emitted. The only exceptions are down-leveling to support older runtimes and enums/namespaces (these features come from dark times, before the team decided to focus on type-only features).

That's what this point in the viability checklist means:

> This could be implemented without emitting different JS based on the types of the expressions

And this non-goal from the language design goals:

> Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

**Comment by WarstekHUN** [comment]
Okay. If my proposal violates the rules then is it okay if I make the changes myself? Also, I have a question about this topic, I have noticed that even the compiler is written in TS. Is there a closed-source compiler which's not in this repository? Could my proposal be implemented using this repo or only the TS dev team is capable of doing that?

**Comment by fatcerberus** [comment]
I mean, you could fork the repo and implement it yourself locally, the compiler is fully open-source, but the TypeScript *project* is not a democracy and any PR that implements this will be rejected by the maintainers.

**Comment by WarstekHUN** [comment]
Okay, thanks.

**Comment by coolCucumber-cat** [comment]
Question: Would it be possible for TypeScript to generate type guards when you use instanceof? Yes it does emit JS code but it just automating exactly what the user has to do anyway and it already knows exactly what the types have to be. It's not creating any new variables or interfering with anything. It's comparable to how public infront of a constructor parameter automatically assigns it to this `this`.
