### ISSUE TITLE
Typescript is not able to resolve the union after a merge

### ISSUE THREAD

**Issue by thibault-lr** [microsoft/TypeScript#55872]
### 🔎 Search Terms

union inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 5.2.2

### ⏯ Playground Link

https://www.typescriptlang.org/fr/play?#code/FAFwngDgpgBAslATgcygHgGIBoYGUB8MAvDAN7AwwDaA0jAJYB2MA1lGAPYBmeMAPq3bcYGALoAuGHSgAPEFEYATAM6DOPXBUowA-HlqitlSdLkKVa4RiO6RBm5MZQAbkgDcwAL4fw0GABUAVwgAGyh-DgBVRnoORjR-GFl5JVVEKABDRTiQsBhAxhZGDgB3RipRQhJ-KkZAgFsAIyRRD2BQSFgAQWIyLTYwSQAiLqGPSghEDggARkllEEQmZA9Pdt9YACFe8koB4c2xrUnpgCZHBubEVfaOv2jY5mrgsIiHuLQqLpxNypgAen+MB6fAABdt1p14EhUIoIgBhEIZZSqEgIFDoDiNABWUAAxiAcO9GPh2op8Uj0jA8XEFtTJOjYQikSiPPQuAAKPEAOgGxCIJBGQwAlH1KIC8AALDiBEKKGDNGAbYQ9LQ8rztIA

### 💻 Code

```ts

type Merge<F, S> = {
  [K in keyof S | keyof F]: K extends keyof S
    ? S[K]
    : K extends keyof F
    ? F[K]
    : never;
};
type TupleToUnion<T extends readonly unknown[]> = T[number];


type A = {
  key: "A";
  prop1: string;
}

type B = {
  key: "B";
  prop2: number;
}


type Union = TupleToUnion<[A, B]> // A | B 
type MergedToClass = Merge<object, Union>

declare const c: MergedToClass;
if(c.key === "A") {
  // expecting c to be typeof A 
}


```

### 🙁 Actual behavior

Typescript can't resolve the type of C correctly. Expecting it to be a type of A

### 🙂 Expected behavior

Since the type `MergedToClass` merges an object and a union of types, I expected typescript to be able to resolve the type.

**Comment by MartinJohns** [comment]
What type do you expect `Merge<object, Union>` to result in? Because right now it results in `{ key: "A" | "B" }`, and for this type there won't be any narrowing based on `key`. You would need it to result in `A | B`, two types each with a distinct `key` property.

**Comment by RyanCavanaugh** [comment]
It seems like you're expecting `Merge` to be distributive, but it's not, and since the mapped type inside isn't homomorphic, per-branch property information is lost, by design.

What you might want is this:
```ts
type MergeDistrib<F, S> = S extends unknown ? Merge<F, S> : never;
type Merge<F, S> = {
  [K in keyof S | keyof F]: K extends keyof S
    ? S[K]
    : K extends keyof F
    ? F[K]
    : never;
};
type TupleToUnion<T extends readonly unknown[]> = T[number];


type A = {
  key: "A";
  prop1: string;
}

type B = {
  key: "B";
  prop2: number;
}


type Union = TupleToUnion<[A, B]> // A | B 

type MergedToClass = MergeDistrib<object, Union>

declare const c: MergedToClass;
if(c.key === "A") {
  // OK
  c.prop1;
}
```
