### ISSUE TITLE
Generics are not inferring properly in functions

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#55873]
### 🔎 Search Terms

generics in functions

### 🕗 Version & Regression Information

- This is a crash No
- This changed between versions 3.3.3333 and 3.5.1
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics
- I was unable to test this on prior versions because I am using TS playground when the latest version is 3.3.3333

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/C4TwDgpgBAIghsOUC8UDeAoK2pwFxQDkchWOARgYeaTlAMZX2kC+GGAZgK4B29wASwD2PKAEEAPABUoEAB7AIPACYBnIiSgAfIjW1FmAPgAUoSASkAaKMoT5YdgNpSAugEp0ZbAHpvUAHSBGGycvPzCogBC0rIKSmoahPrUSTqERqbgEBYemHQAThDAXPmiYpmQ1mYQbl5QvlBSABbQYlDcfIIiuPT0EGDA6uXEhNYjHjrDNGM0E+LG6aMGhLV0DQASEIVQwC1QqhD0Isq4+QDmXAC2SsBQAuqqTUIA7gI8Z7j7AI6vZ2cANiA6nUGmJzlcblAhBwdlkiFIkvcoDwhLc4KpVAIzjw4OR-tBgEIoGA4Pk4NdFPkoTDqkR4IhnC5CP4QX4pHDCAAiOCc-Sc8i8nSc+icxHqFFojFYnF4glE2mEelwRnM1l0Roc7miu7i1G4KXY3H4nbyjlKlUstZ+OjsyBEVTAfJvM5i5F69GYw2yk2wu2EHgQABuW1VVvVNo5CJ1bslnplxsJvug-qDIctOAa4ewtuTDqd71dEv1caNcqTRADwfyoYz1qzEb9eedhfdBvjZYVlbTxgATABmAAsAFZaiEgA

### 💻 Code

```ts
type Data = {
    a: 'a'
    b: 'b'
    c: 'c'
}

function A<T extends 'a' | 'b' | 'c'>(type: T, data: Data[T]) {
    // ...
}

function B<T extends 'a' | 'b' | 'c'>(type: T) {
    return A(type, type)
    // The A function accepts A('a', 'a') | A('b', 'b') | A('c', 'c')
    // Here the second argument shows a squiggly
    
    // Argument of type 'T' is not assignable to parameter of type 'Data[T]'.
    // Type '"a" | "b" | "c"' is not assignable to type 'Data[T]'.
    //     Type '"a"' is not assignable to type 'Data[T]'.
    //     Type 'string' is not assignable to type 'never'.
    //         Type 'T' is not assignable to type 'never'.
    //         Type 'string' is not assignable to type 'never'.
    //             Type 'string' is not assignable to type 'never'.(2345)
}
```

### 🙁 Actual behavior

Showing an error that `Argument of type 'T' is not assignable to parameter of type 'Data[T]'`

### 🙂 Expected behavior

No error.

### Additional information about the issue

It is common to have a list of "types" and associated data for those types.

**Comment by RyanCavanaugh** [comment]
This program *only* works if `Data` has the property that `T === Data[T]`, so why not just write
```ts
function A<T extends 'a' | 'b' | 'c'>(type: T, data: T) {
```
If you change that invariant, then the argument that `A(type, type)` can be shown to be unsound.

**Comment by alesmenzel** [comment]
Hi, sorry if my example was oversimplified. It did not provide a good example. Here is a more complete code I am working with (simplified as well, but intentions should be clearer + I added comments to help you navigate).

**Code description**
The code is creating a internal representation of a Tree with Nodes, where both the Tree and Node are EventEmitters and can fire update events whenever something changes.

**Issues**
**There are total of 4 TS issues, but the one reported in this issue is marked as `Question 3`, but I would really appreciate if you could also look at issue marked as `Question 4`. For `Questions 1-2` I have workarounds that I can live with, but I would still appreciate any suggestion if those can be improved 🙏.**

[TS Playground](https://www.typescriptlang.org/play?#code/PTAEBkFMHNIOwCYCgSkLwbhUPdAXlAdwHsAnAawGcAaUAIwFcAXUACwEMBjEgT1DIIBsGASwJxQACgBmxNpDKh6nAA6R5BUABUAygEoUYQKDkOfMXJUEBWXADkjZUSlEAtqBZxurDpRoNQguWVpqAFoCRXpBRxY+cUgAOmhY0CJIAEdaQWS5FgQEQXCRKPlIR0VEgDcWIkEWaj4VXEdi4k5dPVAAUQA1doA5dQ6AWQBJdXV2gCVQIJceCMU6miICPDJIIiTIILm6xrh6FnzRAgkOsvh6dsc8+jXxFjl2s731SthGNlc4AkZqFUgADxuiEgCFAIjBfAQt00LAklUEoDORDIwjgZFaAMUxEYCmUED8QLWAB5HucAHxGMSQJ70ABcp3O2hwFLKBEEyEx2PkShUpL2ZAAQpx1DyAMIiMj0IgsQR7IwAb1AAG0SJBOPTJVU4NAALr01zcAC+SE5RBxPPxkvgazIJJpcgBQIQD3tQpFynFaKlMr2FNw8qQAEgle6VLLQKrOMcGfydQB+engAnWoh285kEM8nVkpU6pDGpBsPj3F3nS7XYl8+iC4UWx3wZ0x6tusUS72y+gUgOBgDEfGTcBtiYHNrT-JbyjJSCDbDbRFobHoxDETO7gfoTD8sT7I+RCuNgYLoGPYLgRNDoHriDkkejVZrobJYlxkHpoao-atg6Iw6-lddtbKJmyjZquQbrpuZDbp+hLIkqL46qAcZxrguZICeGGgKgACKtCyIcoAAIxvpoPBMAQtCQhss7QHAfgqEwawqBuBzyIxbFbjuf57gQ1AAFaQIuzD3MqCGgIoSx2AosTgRunEwSmGYIbEii0GQTBiAp36tJhJ6oAA6gA8uMADSACC4yGQAqj0AAioCAMmE6G6VhYBqcx7HUK40BgnYBzEFQdCMHgrCMIIJx4CoySOAQZxsSoUJwpRjA1LFkBUBu8AcXIs6UaCtTLKAtCKOgGCyZB0G7kpWYAIQqWpGlaWsugYUeJ7FHkY70BeV6NreJz3hOkBPi+9JVu+l40mNAGhkq41ZmBLmuaAuH4aioAAEwkWRFFUXAlRLHgbGsZlEZqpe-wElB4HheIL6+KIclQVxsFyAAZG92WVdx1UgWBgaBhhT3fa98FZrEDjtOwGmabuv6wV1D48nNNKhqBzKgE1RBUjS2gtUtJ7OQTy1GaZFnWXZRGOUTBOoKEhyFGwrCyrK0CBT4eS+HItBwIOMhkGQlTcJg4FAxVL2KWDIFxhDxBQ0zYiw9x8MpojQ0o+caNkky2AUljOOMvjxM00tBnGeZlk2fZG3U8Tx6oO58U0N5vlrP5RDs8FoW+BFUVNHFp1M4JJAZYxj2QaAuVUQVR3FaVosnsDEvfr9kA6nVkPQ4rWMq9+auAZAGvPFm2sY-r1KGybJ5tbpZtk5blMAMy2y5qDqBHhCkFkiCgJEqr+PAqxUHxamMKwoJLi4bCzjFCAHB5KizlCoAOBopF4HkTAzDcJTEELiLwjUCz6FXx6zl6mNVUYSdY6neZLbdSuvYtdu37LRDyzDOeWgjg0F0X3US46z1ruA2ew8an1AAeY0BZUA9EMrZdobQAAKBABaCFqCoL4UIyC0jaIOI6PQCBQjEFYFgVgqCKlGqAMhFCD4CFfDwKUrNcxQN0KgAhoAiEkKsNQOhVCeT0l4XQ6U2pGHyiuHAekcBaCOF+B7XuLB-jSNkfIw0bD8GQEIcQyApC2D8O5MoIRfCzCQH2IIPg9IeYkC+HgUQhp2FgHgWMekQwwpyGSAgHmc85ST1VJAEqp17rhmoN8Le91XCgjnvsT2vh3iuBoAxSAfBFASEoqoM6ASnbBNENElgPA1CRUjgkx2nMRL5NyGQNgVRJGuEYMWG4RBpxtwjh8UQvwCmNDBAwVSjAJBLGcGZZBQwV7EAuiwEodQkD3W4ZATQaxqj9gAF4gn6P6QxjDaFUAqAwjUzDtSsPUQAH1AAIoxNCTFJG8uIyRKi5FrCoJEZRoAZH3KIOo45pyNlCP0aY8xliipwBscsex0yLSzNDGsrhOj5lVCiIIFZCB1BKhsDyKweYwV4jMjkPIqIoi2QOPk-0NMWD0kVJUo+IIEw0AIPwSACTjQYWoGSh6RY1KCDONS0JdKGX5nQm0do-xFCRKdrM2FiyEWrIyR0vA0pFDKFBN424AAiVYcLlkghZbEbVUDlUuDkJlZIxT2kqDCbcCSoQ1jhFkA9UAeTjrBRUHgOpGTJTEEgJilQsyCX7AVMqC84YIU8nUHqDQdZAQNhvGqaM2LcgMz4D6-JcZQCxtxQUBNhLgJp1AJ9RUaqJWIrGoCaUi4iRioWfCxF6hKHfLDXiQ0FJ1EsvzZWzVHRi3sHoGWmFFaNVIprdQi8DaoFQKVEG5QIbPXQqhImwyEhzw8j9O270pbvWEprS2vtLLB0Wg+VOKdsz7wLrxL1OQ47IDqCXQGDCxVomMNmce4afKTRCq5EWEs07ICPouk6M9OjIVGHPZen9kamzlnoI07tUIj2Pi7DTHsO7lDwbyfSNd+w52PopKgRNLgjXJAaSCDJQSLTRmwR6jCPYmYWIQMkKRn7WGoFFJuSEtHjWJJcG4MEhqNnweFbRukn7QAnJkXwaIqBkGVHOGxjpBouOMXWC+acGFz6agXEubGiH0p2sJahnRs752PhfrpAIdgVxKZckne6uBFNLSTva3AeTIFJyoyxrKqF74WfFnxqTuARN8BpjXHgZiJP8bEGR3TUIjOYSTt5uUvmdEBfM8ebICAmPUdo2FnREXIBRYwjhPCkp1qN3pJA1AgrlCLgOKiekyqnp6r8PqlE+1MH6vEpJ3xahZMPu1bECkIlTqxfcRsrIf7l5BApA+oDFJxuRzSnuKI0QXxkFK0474jDauQT1WIWUkpXAyCZOpXa+VTUnBmTozDgHzu0IpGMh9wibvrDu-oskVAQqCCZjtPKLhRPsZLIIWilKMmDde5uD7DXoxnahESZVLA9UnOVdQOHoBlVsGVWSOMkCyOxFWPQEL5xnyQSNphVAZkiDQFkVJiHFobCQSsFzF53xGv-eawsSefGJlmNuFTvEVgH0w6RwjgXqOyRWBkrZ8WLmaPwHqupTLkWnMVQ6vQUht7550KekTmBzSwDqHGO0JBU71DJEgDB43syQPXk-VemmqubhvmN+eM3OipwFlNO8YsAsNAO6DEbyAkBzensE7gWZFAkAUkD1WcDkHfcm-tI7v3syyRwd7Esb49uE86KEy8yi-mZxzjU8uVPAmY+zP+oGEzawzPlU4kXowRegyBZS7MuXjCS86Ny4ncWReZYpbS65uALfNdJZcDkcVraECzLIGITdkqJ86NwZ+sffbkU6g78eVeYgVOMBn4i830Yd8gkn2v4nYBVqFfBAAFhK3bZa5XBL7EODVvNvbZ8ahf7vzPhp6sjZRADlrk9ZkrA5BHMb84E1s391VZ9ZlYhgk5B+cs9BcEDUcONQQmsZBvtogLUpJBAbUY0cV40cNJNfJ40qBOZDsvsRA+BuBkg0gMhmI1BhVPdToD9QQ+JeAjhTt2JZlIFlM2wGdl5fMtFP1p939D8dEYCeQN1RCEAICC0xDl4HEeC9IwBSdyddhGBucVArBn9IDC1F9pD1AABuKBOnBrL4FKdBP-VnBgyoDnRpMEU7anNDFgDDeA+HRHJAtHUXSBRlauPlIAA)

```ts
// Legend
// 😕 = works, but hacky solution (forces type to TS)
// ✅ = works, doesn't perform any hacks, but is sub-optimal (e.g. requires additional temp. variable = memory)

// EVENT EMITTER - a simple browser re-implementation of EventEmitter (as EventTarget cannot be extended on older Safari versions)

export type Listener<Event> = (event: Event) => void
export type EventsByTypeConstraint = { [key: string]: any }
export type Listeners<Events extends EventsByTypeConstraint> = {
    [Type in keyof Events]?: Listener<Events[Type]>[]
}

class EventEmitter<EventsByType extends EventsByTypeConstraint> {
    #listeners: Listeners<EventsByType>

    constructor() {
        this.#listeners = {}
    }

    on<Type extends keyof EventsByType>(type: Type, listener: Listener<EventsByType[Type]>) {
        this.#listeners[type] ??= []
        // Question 1: TS should recognise here that the this.#listeners object has [type] property.
        this.#listeners[type].push(listener)

        // WORKAROUND ↓
        // use the bang operator, but what if we remove the default above, then this could blow up 😕
        this.#listeners[type]!.push(listener)
    }

    emit<EventType extends keyof EventsByType>(type: EventType, event: EventsByType[EventType]) {
        // Question 2: TS should narrow that the key exists.
        if (type in this.#listeners && this.#listeners[type]) {
            this.#listeners[type].forEach((listener: Listener<EventsByType[EventType]>) => listener(event))

            // WORKAROUND 1 ↓
            // optional chaining, but it is unnecessary 😕
            this.#listeners[type]?.forEach((listener: Listener<EventsByType[EventType]>) => listener(event))

            // WORKAROUND 2 ↓
            // use the bang operator, but what if we remove the check, then this could blow up 😕
            this.#listeners[type]!.forEach((listener: Listener<EventsByType[EventType]>) => listener(event))
        }

        // WORKAROUND 3 ↓
        // This works and makes sense, just had to accomodate the code for TS with a temporary variable ✅
        const listeners = this.#listeners[type]
        if (listeners) {
            listeners.forEach((listener: Listener<EventsByType[EventType]>) => listener(event))
        }
    }
}

// NODE
// Possible nodes:
// new Node('a', { type: 'a', value: string[] })
// new Node('b', { type: 'b', range: {min: number, max: number} })
// new Node('c', { type: 'b', detail: unknown })
// NOTE: It is redundant to keep the type in both type and data, but it can be helpful to keep the type in data so we can use it as a discriminant later

// This can be some output from API for example
type NodeSerializedT = { type: 'a', value: string[] } | { type: 'b', range: { min: number, max: number } } | { type: 'c', detail: unknown }
type NodeTypeT = NodeSerializedT['type']

type AdditionalData = {
    a: { disabled?: boolean }
    b: { inclusive?: boolean }
}

// Expand the NodeSerializedT to be wrapped under "serialized: { ... }" as there can be other properties in data that we want to store
type NodeData = { [Type in NodeTypeT]: Type extends keyof AdditionalData ? AdditionalData[Type] & { serialized: Extract<NodeSerializedT, { type: Type }> } : { serialized: Extract<NodeSerializedT, { type: Type }> } }[NodeTypeT]
type NodeDataOf<Type> = Extract<NodeData, { serialized: { type: Type } }>

type NodeEvents<Type extends NodeTypeT> = {
    update: Node<Type>
}

export class Node<Type extends NodeTypeT = NodeTypeT> extends EventEmitter<NodeEvents<Type>> {
    #type: Type
    #data: NodeDataOf<Type> // Data are related to the type of node
    #children: Node[] // Children can be any other type
    #parent: Node | null // Parent can be any other type

    constructor(type: Type, data: NodeDataOf<Type>) {
        super()

        this.#type = type
        this.#data = data
        this.#children = []
        this.#parent = null
    }

    setParent(node: Node) {
        this.#parent = node
    }

    addChildren(node: Node) {
        // Question 3: 
        // Expectation: "this" is assinable as parent to any Node<...> as the parent is types as Node -> Node<NodeTypeT> -> covers all types
        // Note: "this" (instance) should be of type Node<Type> = Node<'a'> or Node<'b'> or Node<'c'>, which should all be assignable to parent, which is of type Node<"a" | "b" | "c">?
        node.setParent(this)
        // Argument of type 'this' is not assignable to parameter of type 'Node<"a" | "b" | "c">'.
        this.#children.push(node)
        this.emit('update', this)
    }
}

// TREE

type TreeEvents<TreeNode extends Node> = {
    update: Tree<TreeNode>
}

export class Tree<
    TreeNode extends Node = Node,
> extends EventEmitter<TreeEvents<TreeNode>> {
    #root: TreeNode | null

    constructor(root: TreeNode) {
        super()

        this.#root = root
    }

    addNode(node: TreeNode) {
        this.#root?.addChildren(node)
    }

    addSerializedNodes(serializedNodes: NodeSerializedT[]) {
        for (const serializedNode of serializedNodes) {
            // Question 4: 
            // Expectation: "{ serialized: serializedNode }" is assignable to Node's data
            // Note: serializedNode.type is "a" | "b" | "c" and since all properties of AdditionalData are optional, it should only require to pass the serialized json of the Node
            const node = new Node(serializedNode.type, { serialized: serializedNode })
            // Argument of type '{ serialized: NodeSerializedT; }' is not assignable to parameter of type 'NodeDataOf<"a" | "b" | "c">'.
        }
    }
}
```
