### ISSUE TITLE
Does tsc support importing for relative path with extension?

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#5587]
Currently `import myClass from './myClass.ts';` transpile to `var myClass_ts_1 = require('./myClass.ts')'`.

Since `myClass.ts` is transpile to `myClass.js`, the transpiled code does not work.

I try to stick to pure ES6 as much as possible so I want to avoid using internal module syntax.

Thanks!

**Comment by unional** [comment]
FYI doing `jspm bundle` to transpile the code works as it is transpiled to `System.register('./myClass.ts', ...)` therefore the referencing still work correctly.

**Comment by vladima** [comment]
out of curiosity, why do you need to specify an extension in import? `import myClass from "./myClass"` should also work

**Comment by unional** [comment]
Because that is the suggested convention for referencing the file name. As in:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
https://hacks.mozilla.org/2015/08/es6-in-depth-modules/
`systemjs` will also depreciate `defaultJSExtension` in the future.

I can't remember the exact reason.

**Comment by weswigham** [comment]
Duplicates #4595?

**Comment by unional** [comment]
Yes it is the same issue, but targeting compile/transpile logic in `tsc` instead of loading in application.  The objective is to create a npm/jspm module that is transpiled.

I have a related issue on [jspm](https://github.com/jspm/jspm-cli/issues/1276) that tries to see if a pure, raw typescript module is possible.

**Comment by mhegazy** [comment]
They both seem to be stemming form the same issue. we need to reach a solution, we have been waiting on the loader spec to solidify.
