### ISSUE TITLE
Function with properties in JSX

### ISSUE THREAD

**Issue by jcubic** [microsoft/TypeScript#55874]
### 🔎 Search Terms

"function with property"
"function with properties"
"extending functions"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs

### 💻 Code

This is the code you normaly use to add property to the function

```ts
// type alias for `verifyAge` function
// with function signature and a property with its type
type VerifyAgeFunc = {
  (age: number): boolean;
  usedBy: string;
};

// the function itself that
// satisfies the above type alias
let verifyAge = <VerifyAgeFunc>((age: number) => (age > 18 ? true : false));

// add a property called `usedBy`
verifyAge.usedBy = "Admin"; // allowed ✅.
```

### 🙁 Actual behavior

It doesn't work with React/JSX. The problem is that that `<VerifyAgeFunc>` is treated as a JSX tag and the normal way to handle generics in JSX to add a comma doesn't work. Probably because this is not generic only syntax that is similar.

### 🙂 Expected behavior

I expect to use functions with properties in React.

**Comment by MartinJohns** [comment]
You can either use `as T` or just write `T,` in JSX. Then it won't be misunderstood as a tag.

**Comment by fatcerberus** [comment]
I don’t think adding a comma works for a type assertion (OP mentioned this).  But `foo as T` is the idiomatic way to do type assertions these days anyway.

**Comment by jcubic** [comment]
So what I needed to do was to write two interfaces/types one when the property is optional and use `as T` to force the proper type.

This is my real code, nothing else is working:

```typescript
import { type ReactNode } from 'react';
import { Animated, View, Text, type TextProps, type StyleProp, type TextStyle } from 'react-native';
import { styles } from './styles';

type CharTextProps = {
  position?: number;
  children: string;
  style?: StyleProp<TextStyle>;
  mapStyle?: (index: number, chr: string) => StyleProp<TextStyle>;
} & TextProps;

interface CharTextFuncOptional {
  (props: CharTextProps): ReactNode;
  Animated?: (props: CharTextProps) => ReactNode;
}

interface CharTextFunc {
  (props: CharTextProps): ReactNode;
  Animated: (props: CharTextProps) => ReactNode;
}

type TextComponent = typeof Text | typeof Animated.Text;

const makeCharText = (Text: TextComponent) => {
  const component = ({ mapStyle, style, children, ...restProps }: CharTextProps) => (
    <View style={styles.container} {...restProps}>
      {[...children].map((chr, index) => (
        <Text key={`${chr}-${index}`} style={[styles.char, style, mapStyle && mapStyle(index, chr)]}>
          {chr}
        </Text>
      ))}
    </View>
  );
  component.displayName = 'CharText';

  return component;
};

const CharText: CharTextFuncOptional = makeCharText(Text);

CharText.Animated = makeCharText(Animated.Text);

// HACK
// This is probably a bug in TypeScript that doesn't allow using functions with props
// with JSX. We asked on StackOverflow: https://stackoverflow.com/q/77156753/387194
export default CharText as CharTextFunc;
```

**Comment by fatcerberus** [comment]
```ts
let verifyAge = ((age: number) => (age > 18 ? true : false)) as VerifyAgeFunc;
```

https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions

**Comment by jcubic** [comment]
That works thanks. The problem was that no one online you could find this way of adding a property to a function. I only found articles that use syntax as in my original snippet.

Maybe there is a need to add an article on how to do that properly or update documentation.

I will try to write something that will have a high SEO ranking so it's easy to find. And I will answer my question or StackOverflow which may also be visible in Google.

**Comment by fatcerberus** [comment]
IMO (don't take this the wrong way, I don't mean it in a mean-spirited way) it'd probably be good to try to understand the basic building blocks of the language itself first before copying and pasting code from SO and/or blog articles.  Type assertions are a more general mechanism than just "a way to add properties to a function".  As it is this is an X/Y problem but kind of in reverse; you've presented the specific problem you're trying to solve but without really understanding the more general mechanism that was failing.

**Comment by jcubic** [comment]
I just assume that `as T` is kind of F*ck you TypeScript I know better what I'm doing. Similar to using `any` and it should be avoided.

I just didn't know that `as T` is the same type annotation as `<T>`. Thanks for pointing out the holes in my understanding.
