### ISSUE TITLE
downlevelIteration not transpiled above es5

### ISSUE THREAD

**Issue by conartist6** [microsoft/TypeScript#55891]
### 🔎 Search Terms

TS `downlevelIteration` does not do downleveling if the target environment is greater than es5, that is to say if the target envrironment supports real iterators. This is a bug because it is not safe **not** to downlevel iteration if downleveling has been configured!

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?downlevelIteration=true&target=2&ts=5.2.2#code/MYewdgzgLgBA2gawKYE8A0MBuBDANgVyQF0YBeGAeQCMArJYKAOmwggEsBzMACm4DN8YBm3AAqbgEoA3ijZJcAExgBGANwxZ8pQCYAvhMkY4AZgwAWIhNUAoa0A

### 💻 Code

```ts
const [a, b] = Object.assign(
  (function*(){yield 99; yield 99})(),
  [1, 2]
);
```

### 🙁 Actual behavior
```ts
// with downlevelIterators on, es5 target
assert(a === 1);
assert(b === 2);

// with downlevelIterators on, es6 target
assert(a === 99);
assert(b === 99);
```

### 🙂 Expected behavior
```ts
// with downlevelIterators on, es5 target
assert(a === 1);
assert(b === 2);

// with downlevelIterators on, es6 target
assert(a === 1);
assert(b === 2);
```

**Comment by fatcerberus** [comment]
"Downleveling" in the context of TS compilation means "transpiling so that newer features work with older ES versions".  If there's native support for something in the lowest ES version you claim to support, then there's no need to transpile.  So "downleveling" iteration to ES6+ just means using native iterators, by definition.

**Comment by conartist6** [comment]
I disagree. There is a need to transpile wherever your language has nonstandard semantics, and I hope I have made a clear and direct case that the semantics are nonstandard.

**Comment by conartist6** [comment]
Sorry, I had some more errors in my expected/actual that have now been fixed.

**Comment by conartist6** [comment]
The setting and the setting alone should control the behavior, not a mixture of setting and language level. Only the value of the setting can reveal what semantics the user thought they were writing for in the environment in which they wrote the code.

**Comment by MartinJohns** [comment]
> This flag is to enable support for a more accurate implementation of how modern JavaScript iterates through new concepts in older JavaScript runtimes.

It explicitly refers to "older JavaScript runtimes". The flag is not meant to do anything on modern JavaScript runtimes that support iterations (ES6 and later).

**Comment by conartist6** [comment]
Updating the docs to make that explicit instead of subtly implied would be an acceptable solution to me.

**Comment by conartist6** [comment]
Actually I'm not even sure if the docs are right because the name `downlevelIteration` is still extremely confusing to me. I think of downleveling iteration as taking a high-level construct (iteration) and replacing it with a low-level construction (indexed looping). In fact, you seem to see it exactly the opposite way: taking a "higher" langauge (es6) and mapping its behaviors onto a "lower" langauge.

**Comment by conartist6** [comment]
If it were me I'd invert the setting and call it `transpileIterationCorrectly` and the default could still be `false` and the docs explain in about 5 plain words that the setting only impacts es3 and es5 builds.

**Comment by fatcerberus** [comment]
> taking a "higher" langauge (es6) and mapping its behaviors onto a "lower" langauge

That’s exactly what “downleveling” means in TS, in every context where the term is used.

> taking a high-level construct (iteration) and replacing it with a low-level construction (indexed looping)

That’s what happens when `downlevelIteration` is *off*.

**Comment by conartist6** [comment]
That's fine, but the setting's name is still ambiguous if both behaviors can be thought of in some obvious sense as "downleveling"

**Comment by MartinJohns** [comment]
The setting will not be renamed. That's a pointless change, causing unnecessary effort with no real benefit. 🤷‍♂️

**Comment by conartist6** [comment]
I guess I must just be stupid for being confused.
