### ISSUE TITLE
Template string wrongly infers type from a default value used in destructuring assignment

### ISSUE THREAD

**Issue by LasAtt** [microsoft/TypeScript#55907]
### 🔎 Search Terms

"template string", "default value", "infer type", "destructuring"

### 🕗 Version & Regression Information

This changed between versions `5.1.6` and `5.2.2`. The bug is also present in `5.3.0-dev.20230928`.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20230928#code/C4TwDgpgBACghgJzgWwM5QLxQN4CgpQBucANgK4QD8AXFKsAgJYB2A5lAD5TNnIBGEBLgC+uXADMyzAMbBGAe2ZQIADxRgSEABRhEKCMEGpa8JGgCUOfFGmL6OIqQqYoAcgCMAJgDMrqMJddMwMjawQDMgQlAAMAEmxicghhaMwMLFdvABYAVlcRXCA

### 💻 Code

```ts
type Params = {
  value?: string | number
}

function example(parameters: Params) {
  const { value = '123' } = parameters
  return `${value}` === '345' // <--- Error: This comparison appears to be unintentional because the types '"123"' and '"345"' have no overlap.(2367)
}
```

### 🙁 Actual behavior

The template string expression, `${value}`, is assigned type `"123"`, based on a default value assigned to `value` in a destructing assignment.

### 🙂 Expected behavior

The expression should instead be assigned a type of `string`. The field `value` is correctly assigned a type of `string | number`, so any template string using `value` should not be restricted to the default value used in destructuring.

**Comment by Andarist** [comment]
I'm almost certain that this is a fall out of https://github.com/microsoft/TypeScript/pull/53907 and it's definitely a bug. I'll look into this soon.

**Comment by LasAtt** [comment]
> I'm almost certain that this is a fall out of #53907 and it's definitely a bug. I'll look into this soon.

Thank you for looking into it!

**Comment by Andarist** [comment]
It's actually an old bug but this one is a new manifestation of it. [TS playground](https://www.typescriptlang.org/play?ts=5.0.4#code/C4TwDgpgBACghgJzgWwM5QLxQN4CgpQBucANgK4QD8AXFKsAgJYB2A5lAD5TNnIBGEBAG5cAXxG4AJhADGJRNBkB7ZvShhEKCMEGpa8JGhHLVwHEVIVMUAEQBGAEwBmG1FHWNh7bokQeyKABRHHwoHTUsYnIIABoxXCA)
