### ISSUE TITLE
Generic type aliases behave weirdly in functions if there is more than one layer of abstraction

### ISSUE THREAD

**Issue by pwall2222** [microsoft/TypeScript#55900]
### 🔎 Search Terms

generic type aliases functions

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Functions and Generics

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAogtmUB5ARgKwgY2FAvFAJSwHsAnAEwB4BnYUgSwDsBzKAHykYFc4UJT2UaiF7EANgBpOEAG78AfAG4AUMtCQoAcQjAAIgENg+vFADeyqJagAzeqVoAuKCmLiI+xiqtCSjck5c3DxUAXxU1cGgAYQALLABrADE7WkoAFSgIAA9gCD9qLR0DI3kTDOzc-LNbe2AnOi4IEKgAfmqUuqE6JmZmp3hEEFQMbBV1aLjMeIBlXypynLzyAu09Q31SsszFqtNqOfrSRua2vYOuhhY+2ARkdCxgcPHCtaMiai5gdO3K5ZfijYmWIJZK1dKlABkUGBU1mmGIfnB4WsXEY2HoCKguVoiVRmAAjFBvhUlisiut5AAKfSkZhONIASicqwB70+4LMpB0XFIjDMzX0BQ8IBCyhRaOAGL52OAuLRACYiQtfmTXhtqbT6UzoZMkh0OVCYTM5hzTFzgDy+aYBULGCLVPDGLQsRBaIT8OZvDVHDZ9GJ9hILFZ9o7-L7-RBAzaoI7aCpYzgZYqPUHLN7OtY-QHUz5Q4dGlIAPSFqAAQlLUDSBAAqjBlNGE09IpXImlXcB3f91myvuNiNYXW6lMpi1YAHotZQJmx4-FEC28zsyuUEyky-EMkcl8eT6fizDy+eWpftlfytftjdb7wT1QRDRpVvt5Ndt6u9l9gdJ4ejyy3vezkevIvsus4XrQ8oMiov5-ruCLOvuh7csBJigQq4HAJB0HbrByhAA

### 💻 Code

```ts
type EmptyObject = Record<string | number | symbol, never>;

type GetData = {
    first: boolean;
    second: boolean;
};

type CheckFirst<T extends GetData> = T extends {first: true} ? {first: string} : EmptyObject;
type CheckSecond<T extends GetData>  = T extends {second: true} ? {second: string} : EmptyObject;

type GetDataResut<T extends GetData> = CheckFirst<T> & CheckSecond<T>;

function testFunc1 <T extends GetData>(arg: T): GetDataResut<T> {return {} as any}
function testFunc2 <T extends GetData>(arg: T): CheckFirst<T> & CheckSecond<T> {return {} as any}

const test1 = {
    first: false,
    second: false,
} as const;
const test2 = {
    first: false,
    second: true, // !! TRUE
} as const;

type TypeTest1 = GetDataResut<typeof test1>; // EmptyObject
const func1Return1 = testFunc1(test1); // EmptyObject
const func2Return1 = testFunc2(test1); // EmptyObject


type TypeTest2 = GetDataResut<typeof test2>; // { second: string; }
const func1Return2 = testFunc1(test2); // GetDataResut<{ readonly first: false; readonly second: true; }>
const func2Return2 = testFunc2(test2); // { second: string; }

```

### 🙁 Actual behavior

When we use the type alias `GetDataResut` in a function the return type just breaks.
```
const func1Return2 = testFunc1(test2); // GetDataResut<{ readonly first: false; readonly second: true; }>
```
As it returns the param type (wrapped in the type alias), instead of deriving it.

### 🙂 Expected behavior

The expected behavior is for `testFunc1` using the type alias `GetDataResut` to return the resolved type (same as using `GetDataResult<typeof test2>` or `testFunc2`. In this case the return type should be

```ts
{ second: string; }
```

or more clearly

```ts
{ second: string; } & EmptyObject;
```

### Additional information about the issue

This might be just an issue with my code, and its in the very far depths of the type system. But I thought I'd share it because I've encountered it before, and it might stem from the type checker just being clueless on how to resolve the type. But in this precise case it only breaks if it has two layers of generics / aliasing.

**Comment by jfet97** [comment]
I think it's just TS being lazy. If you force it to compute the return type, e.g. setting the return type of `testFunc1` to `GetDataResut<T> & unknown`, you get [your desired result](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogtmUB5ARgKwgY2FAvFAJSwHsAnAEwB4BnYUgSwDsBzKAHykYFc4UJT2UaiF7EANgBpOEAG78AfAG4AUMtCQoAcQjAAIgENg+vFADeyqJagAzeqVoAuKCmLiI+xiqtCSjck5c3DxUAXxU1cGgAYQALLABrADE7WkoAFSgIAA9gCD9qLR0DI3kTDOzc-LNbe2AnOi4IEKgAfmqUuqE6JmZmp3hEEFQMbBV1aLjMeIBlXypynLzyAu09Q31SsszFqtNqOfrSRua2vYOuhhY+2ARkdCxgcPHCtaMiai5gdO3K5ZfijYmWIJZK1dKlABkUGBU1mmGIfnB4WsXEY2HoCKguVoiVRmAAjFBvhUlisiut5AAKfSkZhONIASicqwB70+4KgUNR8UYxAA7owzKQdFxSILTM19AUPCAQsoUWjgBjBdjgLi0QAmIkLX5k14bam0+lM6GTJIdDlQmEzOYc0zC4Ci8WS6WMWWqeGMWhYiC0Qn4czeGqOGz6MT7CQWKz7T3+UPhiCRl1QT20FSpnCqrUBqOWYOdaxhiO5nyxw6NKQAekrUAAhLWoGkCABVGDKZMZp6RRuRNK+4D+-7rNlfcbEaw+v1KZTVqwAPRaygzNjx+KIjrFg9V6oJlNV+IZM5r88Xy4VmA166dW-7O41e-7B6P3gXqgiGjSvf72aHb197LHCcs2nWdLFfM9VyvMUf23VcH1oDUGRUUCwNPBFvXPS8RWgkxYM1eDgEQ5Dj1Q5QgA).

**Comment by RyanCavanaugh** [comment]
These are just two ways of naming the same type. There's no single correct answer.
