### ISSUE TITLE
JSX.IntrinsicClassAttributes<T> not supoort JSX.ElementClass

### ISSUE THREAD

**Issue by textbus** [microsoft/TypeScript#55902]
### 🔎 Search Terms

//

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```tsx
interface Component {
  render(): any
}

interface Ref<T> {
  current: T
}

declare namespace JSX {
  interface ElementClass extends Component {
  }

  interface IntrinsicClassAttributes<T> {
    ref?: Ref<T>
  }
}

function Child() {
  return {
    render() {
      //
    }
  }
}

class Child2 {
  render() {
  }
}

interface CommonComponentMethods {
  foo(): void
}

function useRef<T>(): Ref<T> {
  return {
    current: null as any as T
  }
}

function App() {
  const ref = useRef<CommonComponentMethods>()
  return {
    render() {
      return [
        <Child ref={ref}/>, // not working, type exception not thrown as expected
        <Child2 ref={ref}/> // is ok, detectable lack of foo method
      ]
    }
  }
}

```

### 🙁 Actual behavior

//

### 🙂 Expected behavior

//

**Comment by MartinJohns** [comment]
You forgot to fill out most of the issue template.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
