### ISSUE TITLE
`--build` overwrites `"preserveWatchOutput": true`

### ISSUE THREAD

**Issue by llllvvuu** [microsoft/TypeScript#55905]
### 🔎 Search Terms

`-b`, `--build`, `preserveWatchOutput`, `--preserveWatchOutput`, `build mode`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about build mode

Tested: 5.2.2, 3.0.1

### 💻 Code

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "preserveWatchOutput": true
  }
}
```

Project contents:
```typescript
console.log("Hello world!")
```

```sh
; tsc --watch  # preserved
; tsc --build --watch  # not preserved
; tsc --build --watch --preserveWatchOutput # preserved
```

### 🙁 Actual behavior

Watch output was not preserved. It looks like build mode has its own `parseBuildCommand` and this does not include the `tsconfig.json` options into the `diagnostics`

### 🙂 Expected behavior

Watch output preserved, since `"preserveWatchOutput": true`. Or documentation about this behavior if it is intended.

**Comment by MartinJohns** [comment]
This seems intentional: https://github.com/microsoft/TypeScript/issues/26873#issuecomment-418467438
