### ISSUE TITLE
Allow usage of custome Promise as return type of async functions

### ISSUE THREAD

**Issue by Fuzzyma** [microsoft/TypeScript#55909]
### 🔍 Search Terms

"The return type of an async function or method must be the global Promise type"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Atm, specifying a different return type then Promise for async functions leads to the following error:

> The return type of an async function or method must be the global Promise type

I tested some js code that does NOT return a global promise but a custom object and it worked fine:

```js
const getPromise = async () => ({ then (cb) => cb(5) })
const result = await getPromise() // 5
```

await works with any object that has a certain "then" shape. Why enforce the global Promise as type?
Even extending the global promise will not get rid of that error:

```ts
class CustomPromise<T> extends Promise<T> {}

// this will yell at you
const getPromise = async (): CustomPromise<number> => new CustomPromise<number>(resolve => resolve(5))
```

### 📃 Motivating Example

there is a typescript package called "ts-results" that brings the rust Result-Type to typescript.
It has a limitation tho because it does not support async functions which makes unwrapping the result out of the promise and rewrapping it back tedious.

So this would be very nice:

```ts
class AsyncResult<T, E> extends Promise<Result<T, E>> {

  constructur(result: Promise<Result<T, E>> | Result<T, E>) {
    super(resolve => resolve(result))
  }

  map<U>(mapper: (value: T) => U | Promise<U>): AsyncResult<U, E> {
    const mappedResult = this.then(async (result) => {
      if (result.ok) {
        return Ok(await mapper(result.val));
      } else {
        return Err(result.val);
      }
    });

    return new AsyncResult(mappedResult);
  }

  // other stuff ...
}
```

Asnyc functions now could define their return type as Async Result and directly use the Result methods on it

```ts
const data = await getApiData().map(response => response.data) // Result<typeof response.data, any>
```

### 💻 Use Cases

1. What do you want to use this for? - See above
3. What shortcomings exist with current approaches? - You have to convert every promise that comes back
4. What workarounds are you using in the meantime? - converting every promise to an async result

**Comment by Fuzzyma** [comment]
ok that sucks. thx for the headsup

**Comment by fatcerberus** [comment]
I don't even remember making that comment 😮
