### ISSUE TITLE
Class's prototype property is typed incorrectly and includes instance properties

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/TypeScript#55904]
### 🔎 Search Terms

class prototype typeof instanceof

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about all Common "Bugs" That Aren't Bugs

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=9#code/MYGwhgzhAECC0G8BQ1oDMD2HoF5oCYBuFaAIzACcAKASkWgoFMAXAVwoDtoBGQ6AXySCkwDBwgYQjAHQgMAcyqxpABwoZmGgJ4qZmDABpoAcn3HoASy7K1G7bprFR4yTLmKb6zcx0zyFI2N-cys4VS97RkckIA

### 💻 Code

```ts
class A {
  foo = 2;
  bar() { return 1; }
}

console.log(A.prototype.foo, 'foo' in A.prototype);
console.log(A.prototype.bar, 'bar' in A.prototype);
```

### 🙁 Actual behavior

The type of `A.prototype` includes `foo`, which is an instance field and not actually present on the prototype.

### 🙂 Expected behavior

The type of `A.prototype` should not include instance fields like `foo`.

### Additional information about the issue

My motivation for looking into was trying to write a utility type that differentiated between instance properties and prototype properties in order to generate proper React props types from a class that ignored things that should not be set from the prototype. Right now there is no way at the type level to tell a field from a prototype method at all that I can see.

**Comment by MartinJohns** [comment]
I believe this is essentially due to the lack of #9726.

**Comment by justinfagnani** [comment]
I don't think this should be modelled as an enumerable properties issue. It's more that the instance type of a class is a union (or more accurately an `extends` type operation) of the instance properties with the prototype's type, but instead the prototype is typed the same as the instance type.

**Comment by jcalz** [comment]
Duplicate #11558 #20922
