### ISSUE TITLE
Abstract method called with callback

### ISSUE THREAD

**Issue by HarelM** [Microsoft/TypeScript#5591]
Hi,
I like typesctipt a lot and recently I updated my compiler to version 1.6.
I have some classes that were "abstract" and now I want to use the new keywork ```abstract```
My question is as follow:
In order to scope the ```this`` variable I used the following type of methods when calling them from JQuary/Angular promise:
```js
export class SomeClass {
    public handleCallback = () => { 
        this.whatEver();
        //... 
    }
}
```
This will make sure that if I use this callback for an async operation the ```this``` variable will be correct.
How do I the same with abstract classes since I can't specify an abstract property?

**Comment by mhegazy** [comment]
looks like the same as #4669.

The compiler does not check for property implementation in classes. you could mark the whole class as abstract, not sure if this helps. 

this is a new use case for abstract properties, and I would say we should reconsider the support for abstract properties.

**Comment by mhegazy** [comment]
closing as duplicate in favor of #4669.
