### ISSUE TITLE
JSDoc Typedef Syntax for Overloadable Constructors

### ISSUE THREAD

**Issue by ITenthusiasm** [microsoft/TypeScript#55916]
### 🔍 Search Terms

constructor jsdoc overload

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Currently, with pure TypeScript, it's possible to create an [overloaded, generic constructor](https://stackoverflow.com/questions/64228054/overload-class-type-definition-in-typescript/64229224#64229224) type. (The benefits of overloaded generic constructors are better detailed in #40451.) However, there is no similar concept available in JSDocs. After migrating a TS project to JSDocs, I found this to be a hindrance. (There are some workarounds, but they still negatively impact user experience surrounding `import`s.)

It would be great if this use case was supported in JSDocs land. Alternatively, if #40451 was resolved, I'm assuming that this issue would be inherently be resolved as well. Rich Harris made a compelling case for using JSDocs in his [interview with the Primeagen](https://www.youtube.com/watch?v=zPOHY-cZ1wE) and his [interview with Kev](https://www.youtube.com/watch?v=MJHO6FSioPI&t=95s) from Svelte Society. It seems there are more library authors interested in reaching for JSDocs (through TS) for simplicity (myself included); so greater support in situations like these would be fantastic.

### 📃 Motivating Example

I'm appealing to #40451 and the example in #52585 here. If I want to create a DOM-watcher class in TypeScript that will have a _consistent, unchanging_ interface and that can be _constructed_ in different ways, I need a generic constructor:

```ts
type EventType = keyof DocumentEventMap;
type ObserverEvent<T extends EventType> = DocumentEventMap[T];
type ObserverEventListener<T extends EventType> = (event: ObserverEvent<T>) => unknown;

/* -------------------- Base Observer -------------------- */
interface BaseObserverConstructor {
  new <T extends EventType>(type: T, listener: ObserverEventListener<T>): BaseObserver;
  new <T extends ReadonlyArray<EventType>>(types: T, listener: ObserverEventListener<T[number]>): BaseObserver;
}

interface BaseObserver {
  observe(element: HTMLElement): void;
  unobserve(element: HTMLElement): void;
  disconnect(): void;
}

export const BaseObserver: BaseObserverConstructor = class<T extends EventType | ReadonlyArray<EventType>> {
  constructor(typeOrTypes: T, listener: ObserverEventListener<EventType>) {
    // Do something with arguments
  }

  observe(element: HTMLElement): void {
    // Observe the element
  }

  unobserve(element: HTMLElement): void {
    // Undo the observation
  }

  disconnect(): void {
    // `unobserve` everything
  }
};
```

This works fine in TS, but it's incompatible with JSDocs -- causing friction during migration. If JSDoc support was added, perhaps we'd probably have something like the following:

```js
/** @typedef {keyof DocumentEventMap} EventType */
/** @template {EventType} T @typedef {DocumentEventMap[T]} ObserverEvent */
/** @template {EventType} T @typedef {(event: ObserverEvent<T>) => unknown} ObserverEventListener */

/* -------------------- Base Observer -------------------- */
/**
 * @constructor BaseObserverConstructor
 * // Define overloads that create a `BaseObserver` instance
 */

/**
 * @typedef {Object} BaseObserver
 * // Define types
 */

/** 
 * @template {EventType | ReadonlyArray<EventType>} T
 * @type {BaseObserverConstructor}
 */
export const BaseObserver = class {
  /**
   * @param {T} typeOrTypes
   * @param {ObserverEventListener<EventType>} listener
   */
  constructor(typeOrTypes, listener) {
    // Do something with arguments
  }

  /** @param {HTMLElement} element @returns {void} */
  observe(element) {
    // Observe the element
  }

  /** @param {HTMLElement} element @returns {void} */
  unobserve(element) {
    // Undo the observation
  }

  /** @returns {void} */
  disconnect() {
    // `unobserve` everything
  }
};
```

That said, this can also be solved by resolving #40451. Resolving said issue would remove the need for any additional TS-specific JSDoc syntax. However, if that is not up for consideration, then a JSDoc syntax that mimics TypeScript's behavior would be very helpful.

### 1&rpar; What do you want to use this for?

The example above is probably the clearest example of what I need this for. This is for a project that I'm actively working on.

### 2&rpar; What shortcomings exist with current approaches?

The current shortcoming is that this isn't possible for those only wanting to use JSDocs. This creates some minor friction in how a project structures its `exports` (in `package.json`) and how a project structures its filesystem. (I didn't require extra `.d.ts` files before migrating to JSDocs.) It also separates a class method's documentation (defined in an `interface` in a `.d.ts` file) from its implementation (defined in a `js` file) -- resulting in lesser maintainability.

### 3&rpar; What workarounds are you using in the meantime?

The current workaround is to create a separate `<FILE_NAME>Types.d.ts` file that has the TS Generic Constructor defined. The constructor can be imported _from_ the types file _by_ the JS file. This would need to be done for every JavaScript file. Alternatively, a global types file for the application/library being built can be created, and the types would be imported collectively from there instead.

This does add some complexity for library maintainers using `package.json`'s `exports` property, however.

**Comment by DanielRosenwasser** [comment]
If you want a generic constructor, you can write

```js
/**
 * @template T
 */
class C {
    /**
     * @template T
     * @overload
     * @param {T} value
     * @return {C<T>}
     */

    /**
     * @template T
     * @overload
     * @param {T} first
     * @param {T} second
     * @return {C<T>}
     */

    /**
     * @param {T} first
     * @param {T} [second]
     */
    constructor(first, second) {
    }
}

const x = new C(123);
//    ^?

const y = new C("hello", "world");
//    ^?

const y = new C(123, "hello");
//    ^?
```

[See the playground](https://www.typescriptlang.org/play?ts=5.2.2&filetype=js#code/PQKhFgCgAIWgBALgUwLYAcA2BDF0AqUswUAxjgM4XQDC0A3kdM6BDM83EmlrsgUw5cA9gDdkAJ0zDsAE0GcE6bBOyoG+AL7RR2TAFdkC2AgnJE+iQDsGNADz4AfJuMgSkBa1cIUGHHkJ2IQQxSWk5b3hlVXV6LWgAMwBLCQpESOi1DW0KZFJhK3kgxXgzC2tbB2dXd08wDJUsuO1k1PTikyjG2PiAbVz8woBdGoVBtIl9UkRhCQAKVrSAGmgBgtkASgYFF0hdsgK06AAPaABeaCtkAHdaOYBGACYAZg2AbihgYA5oAD0AfigBysRwAnudLjc7gAiAAWyEw0mhK2h11mmFk0Pen2+HABQMg40Q0HBFyutxoDxeKPhiOEWI+kC+PwBQA).

It is questionable whether that's the right way to declare `constructor` overloads though. Ideally you could write something like this, but it results in errors.

```js
/**
 * @template T
 */
class C {
    /**
     * @overload
     * @param {T} value
     */

    /**
     * @overload
     * @param {T} first
     * @param {T} second
     */

    /**
     * @param {T} first
     * @param {T} [second]
     */
    constructor(first, second) {
    }
}

const x = new C(123);
//              ~~~
// Argument of type 'number' is not assignable to parameter of type 'T'.
//  'T' could be instantiated with an arbitrary type which could be unrelated to 'number'.

const y = new C("hello", "world");
//              ~~~~~~~
// Argument of type 'string' is not assignable to parameter of type 'T'.
//  'T' could be instantiated with an arbitrary type which could be unrelated to 'string'.

```

([playground link](https://www.typescriptlang.org/play?ts=5.2.2&ssl=32&ssc=91&pln=1&pc=1&filetype=js#code/PQKhFgCgAIWgBALgUwLYAcA2BDF0AqUswUAxjgM4XQDC0A3kdM6BDM83PAPYBuyAJ0zdsAEyYcu6bAOyoG+AL7Re2TAFdkEziUjbW22Aj6DhYw1JlyFygGYBLARUQWE02fPpLoFZKW4AduLskrr6YK7w7tZedo7OkdGe3gDavv5BALoWuhzQGc4C6qSI3AIAFA5OiAA0Pn6BogCUDNqKUO16kAWI0AAe0AC80AHIAO605QCMAEwAzE0A3FDAwHnr6wB+2ytrAIICAObqqMgBvdy20IgAnujI0ADkAScARoKP0PbUAdy92FR7IcAthXpgHqVoElkCgBNBLtc7g9HvhHgA6XbMFGffzqTCiaDvL4BZzYc72XDIAljeyIAAW0DJjIEr1psgEN0R92gYzp9lIDNx+MJD3UAQEyBwKAJkOebw+GK6PWgnOGowmNHKACI6ZLhFq6lqxmV8VqlpiNpbttadpBVtADsdTud4VdbtzHoV7AFDp9viM-ozAcDQeDrtwoVZTrDXVzkajFfanqj8tw8QSid7SeTKdTaQymTJWYh2Zz3Q9efzBWnhUSxRKpVTw08vT70VAgA))

**Comment by DanielRosenwasser** [comment]
Also looking more closely at your code, you can just express `BaseObserverConstructor` in the following way.

```js
/** @typedef {keyof DocumentEventMap} EventType */
/** @template {EventType} T @typedef {DocumentEventMap[T]} ObserverEvent */
/** @template {EventType} T @typedef {(event: ObserverEvent<T>) => unknown} ObserverEventListener */

/**
 * @typedef {Object} BaseObserver
 */

/**
 * @typedef {{
 *   new <T extends EventType>(type: T, listener: ObserverEventListener<T>): BaseObserver;
 *   new <T extends ReadonlyArray<EventType>>(types: T, listener: ObserverEventListener<T[number]>): BaseObserver;
 * }} BaseObserverConstructor
 */

```

[Playground Link](https://www.typescriptlang.org/play?ts=5.2.2&filetype=js#code/PQKhAIAEBcE8AcCmATRAzcBvA1o2B7DAEXwGMBXAW0QDtoBRAN1ugFkBDeAX3CZYBUEicCGABYAFCgIMRJXgAbdtGGY+dQUh78ocJKgyYSFanXVtOAbX4BdHgHkARgGdEAJ2ZvzI8VLC65RWVVc01EbV0hAywACkRmOgAucCdXD3dzAB5+AD4ASnAAXhzwchpsGnwAdxoHF3dPcwAZAEtnFRp3H0lJaUkRSP10LCcAK0RSaB4AIXZXVIb3ftEevxBlwZRhzEwN8HBOqvBs8EQADw7kZ14E6DCcmL1EZP4AGnAFNo73ZIX0r1urXatHc2XyyVm83q-wA3HsDogjidzpdrgAlRDsZD4GgKWAAQTcbnYsEyoSEOQeT2cL3en2BnTcv2hjUBXxBbmylhoVEc7hs4PAkMQf08cIkAy4MzmIpZ7gAwjj2m5yJN8G5lr4gA)

**Comment by ITenthusiasm** [comment]
@DanielRosenwasser The example that you gave me seems to fail when the various `template`s are identified with the same letter. Is that expected? [Playground Link](https://www.typescriptlang.org/play?ts=5.2.2&filetype=js#code/PQKhAIAEBcE8AcCmATRAzcBvA1o2B7DAEXwGMBXAW0QDtoBRAN1ugFkBDeAX3CZYBUEicCGABYAFCgIMRJXgAbdtGGY+dQUh78ocJKgyYSFanXVtOAbX4BdHgHkARgGdEAJ2ZvzI8VLC65RWVVc01EbV0hAywACkRmOgAucCdXD3dzAB5+AD4ASnAAXhzwchpsGnwAdxoHF3dPcwAZAEtnFRp3H0lJUHAAWkGh4ZGR8AAhdlcU+vS3AdHF0e6-GRV5JRUsUKFwAB9wACVEdmR8GgVYAEE3N3ZYTJ2kHIjRSVIlZ2cJqcRUhq6mEk4HA0mBIIgADEWm52uAzqRnOCRMi1oFNiEEtAwtpUVB8J4FPhTnjIPB2HdKFh+Dw9IgkRIQSIoOTKVh-nNmm0Ou5si9wApubR3AymTI3IhoOQ3DQsJNXBzPHyuKjfOCwYyIeAAMqIUjnZDwsiiiGk9ZBLaYY6nc6XG53B5PRD8-ikgnuIkkzXMskU9hUzA08B0k0+1n+9mzRpY1rtYVubKWGhURzuGz8wVxzqw0kSqUyuW-RW83Iq71vCTqsCk8MBoMhmt+gPFrwxoXZx5YsIZ9si1Xg-U0dpucikaD4NwxEMAGgFvdhBSB3tBvhBZarMlrWAAEvxWE16Ao5CweIgj6ZoFA89Kh1hGPgWsgeBWQfgo4g4ueWIvkSuZmlmGDAALYQz2POhwXXTVpBZJsdz3A8vzoU8kMvSBrxlb5MHvR9n1XUpKnfT9wOgH9l2AYBwAAVRoM5gOEN8AOUFpzkgnpoP8dDJRvLCcKfFYQWQNpB06McYjIpk-wAAzKRiASk8B4ncWBoCAloaAAczYiQoMHOFh3UjSinAToqh+BV30nAAiD4WlIbArNncSihKMoDHUlA8gAbnec44QpB1jNM8y-ksmJLBswV7KsmwnIKYoCPczpkG83yh0vCUbQua5bnuILEDM+VQoA9wYhgmBdkwPToDw8BwsiuyHJsPI4pcxL0A8lKfIkIA)

Additionally, the comments for the `@overload` JSDocs don't seem appear when the constructor overloads are called. (I don't see the descriptions on hover.) Is that normal as well?

I actually prefer the first example you showed me, where I can simply use `class` directly. I suppose in the meantime, I can use the `typedef` example that you provided. But I only suggested the `typedef` approach because I didn't know syntax was possible/allowed when using `class` directly. In the past, I've received TS errors stating that constructors cannot be generic.

**Comment by ITenthusiasm** [comment]
It seems like this is a bug with overloads, potentially. Will open a separate issue in that case.

**Comment by DanielRosenwasser** [comment]
Yeah, in TS itself, construct signatures can't add more generic type parameters than their containing class.

In the JSDoc version, it's an irregularity that overload signatures permit them.

The doc comments being lost is a valid bug as well if you'd like to file something there.
