### ISSUE TITLE
Ability to auto-import from nested folders

### ISSUE THREAD

**Issue by william-fargues** [microsoft/TypeScript#55911]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I recently switched from a simple NextJS project to a monorepo and because of that all my shareable code as been split into the `packages` folder meaning that I now have a `components` folder, a `utils` folder and so on.

Now I'm trying to auto-import some of my `utils` functions in my `components` files. The thing is that I get no suggestion. However, if write the path by hand it works.
For example I can do this:
`import { tailwindBreakPoints } from "@company/utils/src/lib/tailwind/getTailwindConfig".`
Now, if I comment out this line and try to auto-import `tailwindBreakPoints`, I'll have no suggestion.

If I understood correctly everything I read online (sorry I'm new to npm packages), there are only 2 solutions to fix my problem:
1. Create an `index.ts` at the root of my `utils` folder and export every file from here
2. Add the `exports` property inside the `utils` `package.json` and export all of my folders and subfolders from here

The thing is that, I would rather not do any of those 2 solutions because doing all of this work by hand for every folder I have would take me days of manual exports.

So is there a way to auto-import directly from nested folders ?

Structure of the `utils` folder and any folder I have inside `packages`:
```
/utils
-- package.json
-- tsconfig.json
-- /src
---- all of my previous code (files, folders, nested folders)
```

**Comment by RyanCavanaugh** [comment]
Auto-import doesn't directly care about folder structure. It's likely the target file isn't part of the project already. Please log a full repro.

**Comment by william-fargues** [comment]
As a repro you can:
1. Clone the basic example of Turborepo: [https://github.com/vercel/turbo/tree/main/examples/basic](https://github.com/vercel/turbo/tree/main/examples/basic)
2. Go in the `ui` package
3. Create a `src` folder
4. Move the `card.tsx` file inside the `src` folder
5. Delete the `index.tsx` file
6. Now in the `web` or `doc`  app, try to auto-import the `Card` component. You'll have no suggestion
