### ISSUE TITLE
JS Doc comment not shown in signature help when `overload` tag exists

### ISSUE THREAD

**Issue by ITenthusiasm** [microsoft/TypeScript#55939]
### 🔎 Search Terms

overload jsdoc

### 🕗 Version & Regression Information

Because `@overload` was [introduced in TS 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/), I don't think this is a regression. It may just be something that was missed when overloads were introduced.

### 💻 Code

```js
/* -------------------- Distinct Docs -------------------- */
/**
 * Do something with number
 * @overload
 * @param {number} a
 * @returns {void}
 */

/**
 * Stringing
 * @overload
 * @param {string} a
 * @returns {void}
 */

/**
 * @param {string | number} a
 * @returns {void}
 */
function doSomething(a) {}

doSomething(1);
doSomething("");
```

<details>
  <summary>Also See</summary>

```js
/* -------------------- Fallthrough -------------------- */
/**
 * This does something different
 * @overload
 * @param {boolean} b
 * @returns {void}
 */

/**
 * @overload
 * @param {object} b
 * @returns {void}
 */

/**
 * @param {boolean | object} b
 * @returns {void}
 */
function doSomethingDifferent(b) {}

doSomethingDifferent(true);
doSomethingDifferent({});

/* -------------------- Deferred Fallthrough -------------------- */
/**
 * @overload
 * @param {Event} c
 * @returns {void}
 */

/**
 * Only Mutation Observers do cool things
 * @overload
 * @param {MutationObserver} c
 * @returns {void}
 */

/**
 * @param {MutationObserver | Event} c
 * @returns {void}
 */
function anotherThing(c) {}

anotherThing(new Event("click"));
anotherThing(new MutationObserver(() => {}));
```
</details>

### 🙁 Actual behavior

The _types_ resulting from the JSDocs are correct, but the _comments_ are lost. This same issue occurs for overloaded constructors.

### 🙂 Expected behavior

As is the case for regular overloads in TypeScript ([example](https://www.typescriptlang.org/play#code/PQKgBAtF07tgEQJYGcAuSB2BjNiD22KkcpcYIwAsAFCjgL5gr4C2ApmgBZYDmYAdyTcwmAK6sARuwBOFajQBmYnBnyYwAE3wBlNpx6ZeACgCGALlETpMgJSWAbviSaA3LXpgdaGXz7zaZVUkdS1dfW4+M0t0XyN7MCcXdyUVXBCNbT0OSKNo5h9-AB8rKVkEpM0wAG8AX1paLIjDEwBGWxSmnJbjACJejoa6cDJR6DAAMVMAG2nuGXwxXi4SMbIA4fAAFR5ibXZiFm7-TSRFRVl2TDxKQLS1TPDjo2Rzy+vjSUtJfHxp9lMmAqzjcd2CoS6Bj4rwuMiuaE+lnwkgAVuxcMDkmD0hCnlCXmdYfDEWAfn8ARoSsi0RjHCCavUaI08bleDD3gifGJ2IMaJDWey4R86ryPCM1usEOxYXCqlNZvNFstVhL4LdUuCNID8NxZDsothLABRBzwzGgzZgADymGmAE8wABZMRoUwPa2SFCyU0yPZMbC-aZgVnEdVBHFazA6rh6nqGp0ut0ZK2e73lOlYjURsDa3UyfV5ePO10PFNemQ+sAlE1mjNVOpDXMx-M9TDsARgGsfXrYaZIbAAawGvKbsaibY7xaT6jLaZkxmMtjAAF4AHwM2wdIA)), I would expect my JSDoc comments that use the `@overload` tag to be preserved.

**Comment by RyanCavanaugh** [comment]
> to be preserved.

To be preserved where?

**Comment by ITenthusiasm** [comment]
That's a great question. The JSDoc comments (`/** ... */`) are definitely moved over to the `.d.ts` file during compilation. So in a sense, they are "preserved". But the documentation doesn't seem to be preserved in the IDE. That is, if I call my function, `overloaded()`, in VS Code, I don't see the documentation for that function. I mainly just see type information. This problem only occurs when using the `@overload` approach in `.js` files; using regular overloads in `.ts` files works fine. So I'm not sure whether it's a VS Code issue, or an issue with how TypeScript is communicating documentation information.

But I suppose more accurately, I would like for the documentation information to be preserved in VS Code?

## IDE (VS Code) Info for `.ts` Files (Universal)

If I define an overloaded function, `overloaded`, in `functions.ts` and write JSDoc comments for the function and its parameters, then when I call the function or hover it, I get the correct documentation.

```ts
/**
 * You can count on me
 * @param a NUMBER
 * @param b BOOLEAN
 */
function overloaded(a: number, b: boolean): void;
/**
 * Does some string stuff
 * @param a STRING
 * @param b OBJECT
 */
function overloaded(a: string, b: object): void;
function overloaded(a: string | number, b: boolean | object): void {
  //
}
```

When I start typing out `overloaded` in VS Code, I see the _entire_ JSDoc information for the first overload. This means I see the comments for the function, and the comments for the parameters. As I start providing parameters, the parameter documentation for the _current_ parameter moves to the top, and the documentation for the function moves to the bottom. Docs for parameters that I'm not currently supplying disappear because they are irrelevant.

If I type `overloaded()` and starting pressing `ArrowDown`/`ArrowUp`, I can toggle between the different overloads and the documentation for the params/function body.

If I hover `overloaded` (after providing proper arguments), then I get the _entire_ JSDoc information for the overload.

_These experiences remain consistent even after TypeScript compiles the `.ts` file._

## IDE (VS Code) Info for `.js` Files (Pre-Compilation)

I would think that the experience that I described earlier for `.ts` files would be the same for `.js` files with JSDocs, but they aren't. Let's rebuild the scenario.

```js
/**
 * You can count on me
 * @overload
 * @param {number} a NUMBER
 * @param {boolean} b BOOLEAN
 * @returns {void}
 */
/**
 * Does some string stuff
 * @overload
 * @param {string} a STRING
 * @param {object} b OBJECT
 * @returns {void}
 */
/**
 * @param {string | number} a
 * @param {boolean | object} b
 * @returns {void}
 */
function overloaded(a, b) {
  //
}
```

When I start typing out `overloaded` in VS Code, I _don't_ see _any_ JSDoc information for the overloads. This means I see neither the comments for the function _nor_ the comments for the parameters. As I start providing parameters, the parameter documentation for the _current_ parameter appears, _but the documentation for the function itself is still absent_. As with before, docs for parameters that I'm not currently supplying are absent because they are irrelevant.

If I type `overloaded()` and starting pressing `ArrowDown`/`ArrowUp`, I can toggle between the different overloads. However, the documentation for the function never appears. (The docs for the first parameter still appears as expected.)

If I hover `overloaded` (after providing proper arguments), then I get the _no JSDoc information at all_. No information about the function or the parameters is presented. I just see the types (parameter types and return type).

## IDE (VS Code) Info for `.js` Files (Post-Compilation)

Oddly enough _the experience that I described for the `.js` files **changes** after compilation_. There's no need to rewrite the code, but I'll go through each scenario one-by-one again.

When I start typing out `overloaded` in VS Code, I see _some_ of the JSDoc information. Specifically, I see the comment for the function in general. If I add a `@template` tag, then I also see that. However, _I don't see any documentation for the parameters_. This is the same experience that I get as I start providing parameters to the function. _Documentation for the parameters never appears_, although the parameters are still properly typed. The only thing that I see the entire time is the `@overload` tag, the function body comment, and `@template` (if it was present).

The above experience still occurs if I type `overloaded()` and start pressing `ArrowDown`/`ArrowUp`.
The above experience still occurs if I hover `overloaded` (after providing the proper arguments).

## Conclusion

The `.ts` files provide the best and most consistent DX in terms of documentation. When using `@overload` in `.js` files, however, _documentation_ information (not type information) is lost in one way pre-compilation and in another way post-compilation. I would like to have an experience in my `.js` files that's consistent with how the `.ts` files behave. (Again, not sure if this is a TS issue or a VS Code issue. If TS compiled `@overload` to look just like regular TS in `.d.ts` files, I'm assuming this issue wouldn't occur.)

Does that help?

**Comment by RyanCavanaugh** [comment]
OK, TL;DR

When the `@overload` tag exists, we shouldn't drop the description from the signature help
![image](https://github.com/microsoft/TypeScript/assets/6685088/2a61a256-fb3c-4894-97e9-c62daf3220e0)
```ts
/**
 * neat
 * @overload
 * @param {string | number} a
 * @returns {void}
 */
function doSomething(a) { }
doSomething(/*signature help here*/1);
```
