### ISSUE TITLE
Allow <boolean> type cast on any type

### ISSUE THREAD

**Issue by marke-apexit** [microsoft/TypeScript#55933]
### 🔍 Search Terms

("!!" AND "truthy") AND ("as boolean" OR "<boolean>") AND "type" AND ("convert" OR "conversion" OR "coerce" OR "coercion" OR "cast" OR "casting" OR "assert" OR "assertion")

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

A common practice in TypeScript to test a non-boolean to be 'truthy' is to use a `!!foo`.  Another common approach is to use  `foo===true`.  Both of these common practices are simply to suppress errors like ts(2322) and ts(2352) as !! and ===true are not necessary to convert a truthy value to true.

The problem with both of these approaches are that they emit JavaScript code that is not idiomatic. It is not necessary in JavaScript to use `!!` or `===true` to treat truthy/falsy as boolean.  The resulting code is readable but might be considered. nonsensical because `!!` or `===true` are not necessary.

There are other workarounds for typearesafe handling of  truthy/falsy in Typescript, but they are all rather verbose which is why developers often choose to use `!!` .  The advantages of these typesafe approaches is they emit  idiomatic JavaScript code. But the verbosity comes from having to cast to `any` before casting to  `boolean`

### 📃 Motivating Example

Typecasting of any object to `boolean` in TypeScript allows improved clarity of code, a more consistent pattern for TypeScript, and more idiomatic JavaScript output.

The common practice in TypeScript of using `!!foo` or `Boolean(foo)` will emit `!!foo` or `Boolean(foo)` respectively in JavaScript, which is unnecessary and not idiomatic in JavaScript. And, although `<boolean><any>foo` does emit idiomatic JavaScript, it is unnecessarily lengthy and confusing as a double cast.

### 💻 Use Cases

1. What do you want to use this for

For a concise and idiomatic way of handling truthy/falsy objects in TypeScript that translates directly to the equivalent JavaScript idioms for truthy/falsy

2. What shortcomings exist with current approaches?

- Verbose or unclear code in TypeScript through double type casting such as `<boolean><any>foo`
- Emitting non-idiomatic JavaScript for the concise alternatives `!!foo` or `Boolean(foo)`

3. What workarounds are you using in the meantime?

I have used the `!!foo` approach but have had people viewing the JavaScript complain about the nonsensical code from a JavaScript perspective.  So, I have mostly switched to using the `<boolean><any>foo` approach.  However, whenever I use this, I ask myself, why can't I use `<boolean>foo`? It seems reasonable since it is an explicit cast; I am telling the compiler I want to treat it as a boolean.

**Comment by MartinJohns** [comment]
Why would you **want** that? Even if you cast directly to `<boolean>foo`, the runtime value will still not be a `boolean`, that's why the direct cast is not allowed and the compiler warns you.

**Comment by marke-apexit** [comment]
Whether `!!` in JavaScript is idiomatic or not might be argued, but what can't be argued is that it is unnecessary in JavaScript since (foo) {}` and `if(!!foo) {}` are equivalent.  

The idea of this boolean typecast is to tell the TypeScript compiler it is OK to treat this value can be treated as truthy/falsy. 

One way to look at this is that  directly casting `<boolean>foo` is syntactic sugar for the double casting `<boolean><any>foo`

**Comment by MartinJohns** [comment]
If you just check for truthyness then use the type `any` or `unknown` instead. Type it `boolean` if you expect a `boolean`.

For something like `if (foo)` your `foo` variable does not need to be typed `boolean`. It can already be any type. I don't see the purpose of casting it to a `boolean` and essentially lying to the compiler about the type of your value.

Your suggestion is just a another reduction in type safety.

**Comment by fatcerberus** [comment]
Yeah, I don’t understand this proposal either.  You can already write `if (foo) …` without the cast, regardless of the type.

**Comment by marke-apexit** [comment]
@MartinJohns I fail to see how it reduces type safety as it is explicit by the developer and used when, and only when, needed.  Also, what is different from a type safety perspective between `<boolean><any>foo and <boolean>foo` ?

@fatcerberus You are correct! I was hasty in my response examples using `if (foo)` in comments (not in my original).   My real-world examples in my code are where I must have a boolean variable indicating if some function call returned results; `let foo = fnReturnsObject(); let bar = <boolean><any>foo`

**Comment by marke-apexit** [comment]
Here is an example from the code I was looking at today, with two currently viable implementations

```
let verbose = false
verbose = argv.find(a => a==='--verbose' || a==='-v') ? true : false
verbose = <boolean><any>argv.find(a => a==='--verbose' || a==='-v')
```
Results in JavaScript:

```
let verbose = false;
verbose = node_process_1.argv.find(a => a === '--verbose' || a === '-v') ? true : false;
verbose = node_process_1.argv.find(a => a === '--verbose' || a === '-v');
```

I propose to allow:

````
let verbose = false
verbose = <boolean>argv.find(a => a==='--verbose' || a==='-v')
```

With JavaScript output:

```
let verbose = false;
verbose = node_process_1.argv.find(a => a === '--verbose' || a === '-v');
```

**Comment by fatcerberus** [comment]
That’s not really safe though, because the code you pass `verbose` on to might be doing a `=== true` check (as you yourself noted in the OP) instead of a truthiness check.

**Comment by MartinJohns** [comment]
> I fail to see how it reduces type safety as it is explicit by the developer and used when, and only when, needed.

It removes the warning by the compiler that you're trying to cast incompatible types (e.g. a `string` to `boolean`).

> Also, what is different from a type safety perspective between `<boolean><any>foo and <boolean>foo` ?

By first casting to `any` you explicitly acknowledge that you're casting between incompatible types, and that your value is **definitely not a `boolean`**.

---

Regarding your example, it depends on what `verbose` is used for. `find()` will return the found value, which I believe for `argv` is `string`. If you just use this for a truthy check, then there's no need for any cast to `boolean`, just use the value typed as it is.

But if you cast the value to `boolean` and pass it to a method/property that expects `boolean` you're possibly going to create a bug. Whatever code uses the value could make an explicit comparison with `true` or `false`, or it could even check if the runtime type is `boolean` (which it is not in your example), or it could serialize the value and end up with whatever `string` you got out of `argv` instead of `"true"` or `"false"`.

And in this case you actually should use `some()` instead of `find()`.

---

Note that the cast actually is allowed when **there's a possibility** that your value is actually a `boolean`, e.g. it's fine to cast `string | boolean`, but it's forbidden when the value (according to the type) is **never** a `boolean`.

**Comment by DanielRosenwasser** [comment]
>  Another common approach is to use  `foo===true`.

> Also, what is different from a type safety perspective between `<boolean><any>foo and <boolean>foo`

Type assertions are an escape hatch, but they're still too easy to screw up without any of the checks we have today.

If we easily let you cast `foo` to a `boolean` and compare it to `true`, then you'd always get `false` if it's a `string`, right? I don't feel like we can be convinced on this one to be honest.

**Comment by marke-apexit** [comment]
> If we easily let you cast foo to a boolean and compare it to true, then you'd always get false if it's a string, right?

I would assume that a cast of a string to a boolean would follow the 'truthy' rules of JavaScript when casting to a boolean, so a non-empty string would be true.

**Comment by MartinJohns** [comment]
I'm not sure you understand what a cast actually is in TypeScript. All it does is tell the **compiler** what the type of your value is. It has absolutely **no** runtime semantics or changes.

So if you cast your `string` to a `boolean` and compare it using the strict equality operator `===` with `true` you will **always** end up with `false`. And comparing it with `false` will **also** always result in `false`. According to the type it's one of them, but it's actually neither - it's not even a `boolean`.

**Comment by fatcerberus** [comment]
^^ what Martin said.  If you want the value to actually *be* a boolean at runtime, you have to write either `!!foo` or `Boolean(foo)`, just like you would in vanilla JavaScript.  TypeScript's types only exist at compile time.

**Comment by marke-apexit** [comment]
> ^^ what Martin said. If you want the value to actually _be_ a boolean at runtime, you have to write either `!!foo` or `Boolean(foo)`, just like you would in vanilla JavaScript. TypeScript's types only exist at compile time.

But that is part of the point. You don't have to do that in vanilla JavaScript. 

People commonly do that to silence the TypeSript compiler errors, but those patterns are emitted in JavaScript where they are unnecessary.  And that is why I believe the typecast is preferable. It is an explicit way of silencing those errors without emitting unnecessary code in JavaScript.

**Comment by MartinJohns** [comment]
You don't have to do it in TypeScript either. Just use the correct types. Your value is not a `boolean`, so using the `boolean` type is wrong.

**Comment by fatcerberus** [comment]
Okay so just to make this *abundantly* clear:

```ts
// pretend you didn't write this function and you can't see the implementation:
function doTheThing(x: boolean) {
    if (x === true) {
        console.log("yay!");
    } else {
        console.log("boo!");
    }
}

// this is your code
const arr = [ "foo", "bar" ];
const foundFoo = <boolean><any>arr.find(it => it === "foo");
doTheThing(foundFoo);  // prints "boo!" even though it's truthy
```

The cast *does not change the value*.  You need to write `!!foo` to do that.

**Comment by marke-apexit** [comment]
I now understand how JavaScript and TypeScript would be the same.   If I want a variable to hold a `boolean` in JavaScript I must use one of `p = !!foo` or `p = Boolean(foo)` in both.  And, if I want to use it only in a logical condition, `if (foo)` or `foo ? 'truthy' : 'falsy'` it would also be the same for both.
