### ISSUE TITLE
export default broken for Class expression with target ES6 and commonjs module

### ISSUE THREAD

**Issue by ghalle** [Microsoft/TypeScript#5594]
Using typescript@next and the following compiler options:
```json
"compilerOptions": {
  "target": "ES6",
  "module": "commonjs",
}
```
A class expression being default exported will be incorrectly compiled into a named export instead.

Example:
```typescript
export default class Foo {}
```
compiles into:
```javascript
class Foo {
}
exports.Foo = Foo;
```

**Comment by mhegazy** [comment]
@weswigham can you take a look.
