### ISSUE TITLE
Hit a `debugger` statement when debugging OSS using Insider

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/TypeScript#55953]
Type: <b>Bug</b>

Line 4084 in extensions/node_modules/typescript/lib/tsserver.js

![image](https://github.com/microsoft/vscode/assets/6726799/74a591cf-020f-4357-8eaa-c490f765be83)

Version: 1.83.0-insider
Commit: 4268e464763087044d0c1b5bdd37ebbe683cadfa
Date: 2023-09-29T20:42:50.630Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.83.0-insider Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36

VS Code version: Code - Insiders 1.83.0-insider (4268e464763087044d0c1b5bdd37ebbe683cadfa, 2023-09-29T20:42:50.630Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by RyanCavanaugh** [comment]
Please file a new bug using one of the TypeScript bug templates.

**Comment by gjsjohnmurray** [comment]
Not sure I'll be able to create repro steps. I only reported it because it surprised me to see a `debugger` command in the source. I have been debugging the OSS build of VS Code for several years now as I contribute PRs, and this was the first time I had experienced my debugging hit a hardcoded `debugger` command.

**Comment by fatcerberus** [comment]
See https://github.com/microsoft/TypeScript/issues/46883

The `debugger` statement is there intentionally, because you’ve hit a failed assert in the TS compiler/language service (and therefore a compiler bug).  It’s there to help the TS maintainers debug the crash—assuming you can provide a repro. 😉
