### ISSUE TITLE
Function type notation for object properties handles union parameters inconsistently

### ISSUE THREAD

**Issue by glean-calder** [microsoft/TypeScript#55950]
### 🔎 Search Terms

"function type notation", "union function parameter", "different function type", "object property function type"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [strict function types](https://github.com/microsoft/TypeScript/pull/18654)

Before 3.9.7, this was a bug in _both cases_ cited below, not just the anonymous function case.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAcgrgWwEYQE4HlUGVioJYB2A5lALxQGIqpQA+UAzroUQNwBQ7AZnAQMbA8AewIUqadJFQBDYENQAKSggBcY5GgCUUAN7soUPiIZCANhAB0poUSWIoAaigBGTRwC+nHv0EjGzYkk0WXkFJlQ1cJZtPQMjAhNzKxsw3EcoACIACzwMt3ZPdlBIKAAVCCYgmTlUUvAKsl19KAB6FrKsiuhgAHchRiyhOFMAEygUKG8BYQJpU1MQKAgARzg8ADc5iAJgC2auAiqQiKgwuCQAKwgBNXgNDGwAom1SAD4odaE8EY4DaQIREcamdLtdgLdxA8cPhiJo1J9vh4vLxpn4DgBRAAe1zgwAgIKuN1gkMw0JYABooEIpMc1OVKjSanVIAwANoZA5A+QZAC6MWa1OCwIY50JwHyhSmvlE-xEWJxeIJYIh91JT0pguq8jpFWAXNq9TZGVlh0Z3L5TQMmuOSoEEs4bQ6eAYUGAWVQQh6LukrvqS1QHpoCmkLrwwAGQ1Gmj2joAAsAGABaCCYyACZMB+TcAjyvi4-HOSnKaj6-LsR2lHIukZCCoEADku3YJtz+YUhfUJbNqHyQA

### 💻 Code

```ts
type NumberOrString = number | string;

function numberOperator(num: number) {
  console.log(num + 1);
}

function stringOperator(str: string) {
  console.log(str + "hi");
}

type TestOperatorTypes = {
  // These two should be functionally equivalent.
  fnOperator: (subject: NumberOrString) => void;
  anonOperator(subject: NumberOrString): void;
}

function fnExecute(subject: NumberOrString, operator: TestOperatorTypes["fnOperator"]) {
  operator(subject);
}

function anonExecute(subject: NumberOrString, operator: TestOperatorTypes["anonOperator"]) {
  operator(subject);
}

// This throws a type error (as it should).
// @ts-expect-error
fnExecute(1, numberOperator);

// This doesn't.
anonExecute(1, numberOperator);
```

### 🙁 Actual behavior

`anonExecute(1, numberOperator);` doesn't error. It should have because `numberOperator` does not consume a union parameter type - it consumes a specific member of the union.

### 🙂 Expected behavior

`anonExecute(1, numberOperator);` errors because `numberOperator` does not consume a union parameter type.

**Comment by glean-charlie** [comment]
Was able to replicate this when constructing objects too. [Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAQgrgcwSAKuaBeKBvAUFKAekKhQAsIBnaYAdwHspKz64AbAEygCNoAzOADsAxsACW9QQEM2bEFAgBHOGIBuMiIOAA6fFDAAnepAOgAYoIBcUABSU43AFYRR1wXAC2vA1AA+TYAMxQQQASigMAD4oVXoxDgBuPQ8IYBYOOwdnVyh3Lwgff0pA4LDrWPikgF9cXGJSMjFKKAERcUkoAHkAOQAZAE0oKWFhCDBgZrzvSm0oAElgKCaobs6UIZiZeKWPMDYIFK0pdsE6kno+KAADeCRUdABtAHJDYwLzQSeAXSuhwS4bohkGhIM8Uml6BxvlddK1RBJBFBJHIAIIjMYTbqeaY2PJubEFcJ4AjCSSUej7bRsegIXGeKAAaigAEZQtVaqTBMUoKSDAYXMBrAAFKSmMQyAA8t2B6GiWGJRAAVIq9ORlgB9Xn80RydVQfn2NgTJaItL8CnU2ilBR8+gGSy1Agg6BPOkefH5AzhKIxOJQpaTeiLKSUShiBDSbj7KDARigSBQV32JwC6xYz2dAwAZRKIW90QqUN0TvQzQu+lFUnBBWaTzyTz+XCeyeywAbougwVJu2OYijEGLBFI6ET6e8mZzQRCDeWgiDQ1D4cj0djMZHdYJBieg6Hw4TzdzCBngeDi4jUn7Mbj66mBW3eigisIenqAAEJgBaCAAD0goi-toGHorwmB81jIiAaKjOMlBjjWAA0uBVEkuCctyXZ2tqgpQCKYqStK9yQHKOAvsqqqNM06oYXyAq6hWoZUGuCbCBQwgANaUIhBC0I0LE8qwnD6lQ7CLMEJpagK+pCOIKQ8BAZBSKoEgGDuT7JKk6TgYIqLojBcEGJxSEJEAA)

**Comment by DanielRosenwasser** [comment]
Unfortunately using the "method" syntax exempts functions from the `strictFunctionTypes` checks, and such functions will have their parameters checked bidirectionally.

Not doing something like this would break a lot of code, making lots of collections invariant.
