### ISSUE TITLE
'Parameter' utility class gives an unneccesary warning

### ISSUE THREAD

**Issue by CCleanerShot** [microsoft/TypeScript#55967]
### 🔎 Search Terms

"Parameters", "Parameter utility class",  "Nested objects", "Generics", "does not satisfy the constraint '(...args: any) => any'", "^5.1.6", "5.1.6"

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because im lazy and i just always use the latest. "^5.1.6"

### 💻 Code

```ts
function myFunction(myParam: number, myParam2: { name: string }) {}
function myOtherFunction(myParam: string) {}

const myObject = {
    test: { what: myFunction, ishere: myOtherFunction },
};

const exampleFunction = <T extends keyof typeof myObject, K extends keyof (typeof myObject)[T]>(category: T, something: K) => {
    const item = myObject[category][something];
    return {
        item: item,
        call: (...params: Parameters<typeof item>) => item(...params),
    };
};

const test4 = exampleFunction("test", "ishere");
const test5 = exampleFunction("test", "what");

test5.call(42, { name: "asdad" });
test4.call("adsajsdajad");
```

### 🙁 Actual behavior

compile warnings (ts(2344), yet intellisense works with `test5.call(42, { name: "asdad" });`

### 🙂 Expected behavior

no compile warnings 

### Additional information about the issue

I assume this to be a bug, because there are no compile warnings when `myObject` does not include another nested object inside.
On version "^5.1.6".
example: 
```
const myObject = {
    test: myFunction,
};
```

and my compileTargetVersion (i dunno if this is important)
```
    "compilerOptions": {
        "target": "es2017",
        }
        ```

**Comment by RyanCavanaugh** [comment]
A doubly-nested lookup type can't satisfy a constraint - it's fully deferred. This tends not to come up much in practice since at the point you have two levels of lookup, there's no meaningful commonality between all possible lookups.
