### ISSUE TITLE
"Show call hierarchy" should work with React components

### ISSUE THREAD

**Issue by the21st** [microsoft/TypeScript#55966]
"Show call hierarchy" is a useful vscode feature for exploring the call tree of a function. I often need to do the same with our React components – to quickly go through the "usage hierarchy" (component tree) of a certain component. If this feature was generalized to work with any "usages" and not just "function calls", that would be great! It could be named "Show usage hierarchy".

**Comment by RyanCavanaugh** [comment]
If we take possible external invocation into account, this is just "Find all references". We don't plan to bake in the invocation semantics of every possible framework

**Comment by the21st** [comment]
@RyanCavanaugh I apologize, perhaps I didn't word my request as well as I could. What I meant by this is not to create a React-specific functionality, but to extend "Show call hierarchy" into "Show usage hierarchy".

I renamed the issue and reworded the description. Could you please give it another glance? Thank you.

**Comment by fatcerberus** [comment]
> What I meant by this is not to create a React-specific functionality, but to extend "Show call hierarchy" into "Show usage hierarchy".

Since you say this is a generalized feature request, what are you defining as "usage" that's different from what Find All References already does today?

**Comment by the21st** [comment]
@fatcerberus yes – a reference hierarchy view is what I had in mind. An extension of `Find All References` where for each reference of X, I could dig deeper into where the "referencer" is referenced, etc.

**Comment by TimMoore** [comment]
Sorry to see this closed before the request was clarified. This would be very useful.
