### ISSUE TITLE
Unable to define safe type guards

### ISSUE THREAD

**Issue by zxti** [microsoft/TypeScript#55960]
### 🔎 Search Terms

I want to define a function isX(x): x is X.

However, I want it to throw a type error if x was never possibly an X.

For instance, this should compile:

```
isX(... as X | Y | Z)
isX(... as X | undefined)
```

But this should not:

```
isX(... as Y | Z)
isX(... as undefined)
```

This got me close, and it fully worked in TS 4.x:

```
type X = {a: number}; // For example

export function isX<T>(x: [Extract<T, X>] extends [never] ? never : T): x is [Extract<T, X>] extends [never]
  ? never
  : X extends T // Needed when T is any
  ? X
  : Extract<T, X> {
  return true;
}
```

But it no longer fully works in TS 5.x.

For instance, if you try using it from another function that takes the same type but narrows it to be NonNullable:

```
export function isMaybeX<T>(x: [Extract<T, X>] extends [never] ? never : T): x is [Extract<T, X>] extends [never]
  ? never
  : X extends T // Needed when T is any
  ? X
  : Extract<T, X> {
  if (x === undefined || x === null) { return true; }
  return isX(x); // ERROR
}
```

You get this error:

```
Argument of type '([Extract<T, X>] extends [never] ? never : T) & {}' is not assignable to parameter of type '[Extract<([Extract<T, X>] extends [never] ? never : T) & {}, X>] extends [never] ? never : ([Extract<T, X>] extends [...] ? never : T) & {}'.
```

### 🕗 Version & Regression Information

- This changed between versions 4.x and 5.x

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAYwNghgzlAEAasDeFYF5YEYC+BuUkMsAmsgEbpZ7DACmAHgA4D2ATgC6wBmArgHYh2AS2Z9YQqPAA8AFQB8ACnoAuWAG0AovXasIg2QBoEcgLqwG7WnwAmcNX1oA3WqzMB+WA+etYqmQEpVenE7LR09dkNjMwsrW3UvFxNgWFgPRNYU3wRzbTi4GVgAeiLYADlaWmsq2AB3AAsrWEKJWAg+AE8sj3gs1TDdfRkjeDlkLNZadh5WMR0eWnxsOiY2Tl4BYVEQgFkIDrJaaXklVU1tQcjh6NzLGzsM908nF2yAoJD1AYio0Zi8+4JF6ubrPbx9HKxQGFErlSrVax1RpiFpwdpdVI9CHfIYjMZILJCLiwJToNAYfjVLhCByIgA+dNgwXJGD4PDAYH8yFgk2ms1g80WsGWqV5MzEEngSn8S2AQA

### 💻 Code

```ts

class X {a = 1};
class Y {b = 1};

export function isX<T>(x: [Extract<T, X>] extends [never] ? never : T): x is [Extract<T, X>] extends [never]
  ? never
  : X extends T // Needed when T is any
  ? X
  : Extract<T, X> {
  return true;
}
export function isMaybeX<T>(x: [Extract<T, X>] extends [never] ? never : T): x is [Extract<T, X>] extends [never]
  ? never
  : X extends T // Needed when T is any
  ? X
  : Extract<T, X> {
  if (x === undefined || x === null) { return true; }
  return isX(x);
}

```

### 🙁 Actual behavior

```
Argument of type '([Extract<T, X>] extends [never] ? never : T) & {}' is not assignable to parameter of type '[Extract<([Extract<T, X>] extends [never] ? never : T) & {}, X>] extends [never] ? never : ([Extract<T, X>] extends [...] ? never : T) & {}'.
```

### 🙂 Expected behavior

No error

**Comment by RyanCavanaugh** [comment]
I'm not sure how a type system is supposed to reason about this, so it's unsurprising the workaround stopped working at some point. The thing you're trying to represent fails some very basic symmetry of expectations -- if `X | T` is a valid argument because it contains `X`, therefore `X | unknown` is valid because `unknown` contains `X`, and `unknown | X` is just another way of saying `unknown`, and for any arbitrary `T`, `T` is also `unknown`. So it doesn't really make any sense to say you can write `X | T` but not `T`, because even `T` supersets `X` in the type `T & X` (which is conceivably inhabitable).
