### ISSUE TITLE
Type argument inference across composite projects not working

### ISSUE THREAD

**Issue by rafaelliu** [microsoft/TypeScript#55971]
### 🔎 Search Terms

"generics argument inference", "type argument inference", "composite projects", "project references"

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ___type inference___
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://github.com/rafaelliu/repro-composit-project-inference

### 💻 Code

```ts
// === package "'@mono/pkg1"

export abstract class ParameterizedType<TParams = unknown> {
    private _param?: TParams;
}

export class Wrapper<TProvider extends ParameterizedType = ParameterizedType> {
    parameterValue: InferParameter<TProvider>;
}

export type InferParameter<T> = T extends ParameterizedType<infer X> ? X : never;

// === package "'@mono/pkg2"
import { ParameterizedType, Wrapper } from '@mono/pkg1'

class Instance extends ParameterizedType<string> { }

const obj = new Wrapper<Instance>();

// Language Service infers type just fine, but this will error with tsc -b
// index.ts:9:7 - error TS2322: Type 'unknown' is not assignable to type 'string'.
const stringValue: string = obj.parameterValue
console.log(stringValue)
```

### 🙁 Actual behavior

Using command line, type checking fails:

```bash
> pnpm tsc -b --force
index.ts:9:7 - error TS2322: Type 'unknown' is not assignable to type 'string'.

9 const stringValue: string = obj.parameterValue
        ~~~~~~~~~~~

Found 1 error.
```

### 🙂 Expected behavior

Same as Language Service, which infers `string` correctly (verified through VSCode), this should be type-safe

### Additional information about the issue

This only happens when using project references and when working across projects. If everything is defined in a single project there's no issue

**Comment by RyanCavanaugh** [comment]
Declaration emit doesn't include the types of private fields; this behavior is intentional for a large number of good reasons. That means you get this in the .d.ts file:
```ts
export abstract class ParameterizedType<TParams = unknown> {}
```
Without a usage site of `TParams`, structural inference has nothing to match on, so you get `unknown`, unfortunately.

A common suggested workaround is to include an unused public field:
```ts
export abstract class ParameterizedType<TParams = unknown> {
    "__ I am covariant on TParams, ignore me please"?: TParams;
}
```

There are quite a few duplicates on this but I can't find them at the moment.

**Comment by rafaelliu** [comment]
Thanks Ryan, making the field public or even protected did work. The [FAQ talks](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--) about this but what tripped me is the fact that LS is fine with it. From LS, seemed like my `private` was enough 

What it means is everything looks great on VSCode but when I tried to compile it I get an error. Is there a reason LS doesn't have a problem with this? Any way to it consistent?

You mention the .d.ts file, which I did check before. It shows the private field (or public/protected):

```typescript
export declare abstract class ParameterizedType<TParams = unknown> {
    private _param?;
}
```

When you say

```typescript
export abstract class ParameterizedType<TParams = unknown> {}
```

Were you talking about some internal representation?

**Comment by RyanCavanaugh** [comment]
The LS redirects to the underlying source file so that operations like "Find all references" work as expected. You can turn off this redirection but it will make a lot of other things much worse.

I was just being lazy leaving out the unused private field in the declaration emit.
