### ISSUE TITLE
Narrowing switch(true) doesnt work for default case and is wrong for fallthrough cases in 5.3

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#55986]
### 🔎 Search Terms

switch, fallthrough

### 🕗 Version & Regression Information

- This is a crash No
- This changed between versions 5.2 and 5.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231004#code/C4TwDgpgBAZg9nKBeKByAhqqAfNAjLXVAY1QCgzi4A7AZ2FmTUynVtgQtoHcBLYYgAsAFMABOAVwgBKKAG8yUJVGJtoMZEhQZUALkXLVtdZu0F9ywzVpwANhAB0tuAHNhMaQcsB6b5f9QAHoA-F7KeGIQ6ADWYQAmEDDoErbAFv5UdHaOzm4eYUq+AZYhZAC+QA

### 💻 Code

```ts
type foo = 'a' | 'b' | 'c'

const f = 'a' as foo

switch(true) {
    case f === 'a':
    case f === 'b':
      console.log(f)
      //          ^?  'b'
      break
    default:
      console.log(f)
      //          ^?  'a' | 'b' | 'c'
}
```

### 🙁 Actual behavior

The fallthrough case has wrong type `b`.
The default case is not narrowed.

### 🙂 Expected behavior

In the fallthrough the type should be a union of `a | b`.
The default case should be `c`.

### Additional information about the issue

Related to https://github.com/microsoft/TypeScript/commit/70b7de11fbadb16d30f6770332f544c44134eb82

**Comment by DanielRosenwasser** [comment]
Bizarre that it might have something to do with empty case clauses

[Playground Link](https://www.typescriptlang.org/play?ts=5.3.0-dev.20231004#code/C4TwDgpgBAZg9nKBeKByAhqqAfNAjLXVAY1QCgzi4A7AZ2FgC5YFk1Mp1bPqQLaA7gEtgxABYAKYACcArhACUUAN5ko6qMS7QYyJCgypGajeqp04AGwgA6S3ADmEmApOmA9O9PeoAPQD8bhqesOiWltzAYtJwsg5iUEFatDp6BgTGPua0Vrb2Ti5B6iE+GgFFUHjSEOgA1kEAJhAw6LKWwJne2bl2js6uPiWlfoEAvkA)

```
type foo = 'a' | 'b' | 'c'

const f: foo = 'a' as any

switch(true) {
    case f === 'a':
      console.log(f)
      //          ^? "a"
      // falls through 
    case f === 'b':
      console.log(f)
      //          ^? "a" | "b"
      break
    default:
      console.log(f)
      //          ^? foo
}
```

**Comment by jakebailey** [comment]
@Andarist if he beats me to it before tomorrow

**Comment by fatcerberus** [comment]
@DanielRosenwasser fwiw while your code narrows correctly for the `case`s, it still gets `default` wrong (it should narrow to `"c"`)

Also when did `switch (true)` start working? (this pattern is an irrational pet peeve of mine but that's neither here nor there)

**Comment by DanielRosenwasser** [comment]
I also think it's a little hokey but https://github.com/microsoft/TypeScript/pull/53681

**Comment by jakebailey** [comment]
This comes down to the fact that the PR didn't handle multiple clauses at all... I should have known the PR was too simple 😅 

I have a fix for the multiple clause cases, but default, not so sure about. May need to just be unnarrowed there as I'm not sure we have a mechanism to narrow like we do the other switch case instances as those do the narrowing directly without control flow, whereas this has to be more like if statements or something. I guess we'll have something like this eventually for matching...

**Comment by jakebailey** [comment]
PR at #55991.

**Comment by MartinJohns** [comment]
Related: #37178
