### ISSUE TITLE
Type 'MethodDecorator' is not generic.

### ISSUE THREAD

**Issue by hosseinmd** [microsoft/TypeScript#55980]
### 🔎 Search Terms

MethodDecorator, generic

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
export function CustomDecorator(): MethodDecorator {
  return (
    target: object,
    propertyKey: string | symbol,
    descriptor: TypedPropertyDescriptor<{ data: any }>,
  ) => {
    return descriptor;
  };
}
```

### 🙁 Actual behavior

typescript return this error 

```
Type '(target: object, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<{    data: any;}>) => TypedPropertyDescriptor<{ data: any; }>' is not assignable to type 'MethodDecorator'.
  Types of parameters 'descriptor' and 'descriptor' are incompatible.
    Type 'TypedPropertyDescriptor<T>' is not assignable to type 'TypedPropertyDescriptor<{ data: any; }>'.
      Type 'T' is not assignable to type '{ data: any; }'.
```

### 🙂 Expected behavior

MethodDecorator should be generic, we should be able to pass T (`TypedPropertyDescriptor<T>`) to MethodDecorator like `MethodDecorator<T>`

If I pass type to `MethodDecorator<{ data: any; }>` typescript will return this error`Type 'MethodDecorator' is not generic.`

**Comment by MartinJohns** [comment]
`MethodDecorator` requires you to provide a generic function. The function you provide is not generic.

**Comment by hosseinmd** [comment]
> `MethodDecorator` requires you to provide a generic function. The function you provide is not generic.

`Type 'MethodDecorator' is not generic.` this is what I get from typescript check 
MethodDecorator is not correctly defined, I have a PR about it. Please check https://github.com/microsoft/TypeScript/pull/55979

**Comment by fatcerberus** [comment]
It’s intentional that you can’t pass type arguments to `MethodDecorator`; you’re supposed to return a function which is *itself* generic rather than one that’s specialized to a particular type (`{ data: any }` in your case).

**Comment by hosseinmd** [comment]
But there is no way to pass type to `TypedPropertyDescriptor<{ data: any }>` because typescript return error I mention it in issue description

**Comment by hosseinmd** [comment]
Why It’s intentional, what is the problem of it?

**Comment by hosseinmd** [comment]
When you want a decorator method to functions which have some type of parameters, who you could do it?

**Comment by fatcerberus** [comment]
This is what you're supposed to write:
```ts
export function CustomDecorator(): MethodDecorator {
  return <T>(
    target: object,
    propertyKey: string | symbol,
    descriptor: TypedPropertyDescriptor<T>,
  ) => {
    return descriptor;
  };
}
```

In other words the function works for any `T`, not just `{ data: any }`

**Comment by hosseinmd** [comment]
> This is what you're supposed to write:
> 
> ```ts
> export function CustomDecorator(): MethodDecorator {
>   return <T>(
>     target: object,
>     propertyKey: string | symbol,
>     descriptor: TypedPropertyDescriptor<T>,
>   ) => {
>     return descriptor;
>   };
> }
> ```
> 
> In other words the function works for any `T`, not just `{ data: any }`

Thank you, but how can I get type error if `T` is not extends of `{ data: any }`

**Comment by fatcerberus** [comment]
I don't think `T` can ever be `{ data: any }` in a method decorator - it'll always be a function type.

**Comment by hosseinmd** [comment]
https://github.com/microsoft/TypeScript/blob/d1a2e7e730cb8ebd44662ece6b263e2d4d885da2/src/lib/es5.d.ts#L1500
T passed to value

**Comment by fatcerberus** [comment]
Yes, and that value is the method you’re decorating

**Comment by hosseinmd** [comment]
ok, can I pass this  `({ data: any })=>any` as `T`
