### ISSUE TITLE
Type-check Import Attributes in static imports

### ISSUE THREAD

**Issue by mkubilayk** [microsoft/TypeScript#55994]
### 🔍 Search Terms

import attributes, import assertions

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

[TypeScript 5.3 Beta](https://devblogs.microsoft.com/typescript/announcing-typescript-5-3-beta/) supports the latest updates to the [import attributes](https://github.com/tc39/proposal-import-attributes) proposal, which is great to see!

It's possible to augment the global `ImportAttributes` type with host-specific attributes. However, auto-complete and type-checking of import attributes seems to only work with dynamic `import()`. It would be nice if this could also work for attributes in static declarations.

### 📃 Motivating Example

https://www.typescriptlang.org/play?target=99&ts=5.3.0-dev.20231002#code/CYUwxgNghgTiAEBzCB7ARlC8DeBYAUPPAJYB2ALiDAGZRgLwCSAtgA4ozkCC55MxaAK6UAzjgJEi5AJ6sQALngAiAFYiUpJRPgBfAnvwFibDuXgAqeFDGkx1GCmbLqKFEvgB3YuQAWOeDJyikqkKOQAtGoa7joA3AQAbijEwPC28Yb4xuycABRKLm4ANOKEnt4+inhlUrIKyqERUZraBjoAlBkEQA 

```typescript
declare global {
    interface ImportAttributes {
        type: "json";
    }
}

import * as ns from "foo" with { type: "not-json" }; // no error
void ns;

import("foo", {
    with: {
        type: "not-json", // Type '"not-json"' is not assignable to type '"json"'. (2322)
    },
});
```

### 💻 Use Cases

1. What do you want to use this for?

https://github.com/tc39/proposal-import-attributes#motivation

In addition, we have an internal use case in Bloomberg to use Import Attributes as an annotation to achieve lazy-loading by deferring module evaluation. This is an early implementation of the [TC39 proposal for Deferring Module Evaluation](https://github.com/tc39/proposal-defer-import-eval) that annotates the static import.

It would be a better developer experience if auto-complete was available for Import Attributes in the static form.

2. What shortcomings exist with current approaches?

It is possible to write a static import declaration using unknown/invalid attributes.

3. What workarounds are you using in the meantime?

None.

**Comment by RyanCavanaugh** [comment]
Consensus from the design meeting was that we just "forgot" to do this.

Additional point for type authors - use caution when defining `type` like this. The correct way to make an "open-ended union", as should be used here, is to make a dummy interface and use keyof so that other declarations can introduce new items to the union:
```ts
  interface ImportAttributes {
    type: keyof AllowedTypes;
  }
  // In my .d.ts
  interface AllowedTypes {
    "json": unknown;
  }
  // In other .d.ts
  interface AllowedTypes {
    "png": unknown;
  }
```

**Comment by krutoo** [comment]
This may not be the best place to ask, but could you tell me if it's possible to somehow describe types for modules that are imported specifically with attributes?

I tried something like this but it is not working:
```ts
declare module '*.svg' with { type: 'react-svg' } {
  // ...
}
```

**Comment by jakebailey** [comment]
That is #46135, I searched for "module attribute" and it was the first result.
