### ISSUE TITLE
Type narrowing of object properties by variables does not work as expected

### ISSUE THREAD

**Issue by RabbitHunter13** [microsoft/TypeScript#55997]
### 🔎 Search Terms

"narrowing object property", "type narrowing", "narrowing", "narrowing truthiness"

### 🕗 Version & Regression Information

In version 4.4.4 was added support for narrowing a local variable by constant variable that had result for narrowing (last example in code)

### ⏯ Playground Link

[Link here](https://www.typescriptlang.org/play?ts=5.3.0-dev.20231005#code/FAYw9gdgzgLgBGARgKwFxwN4QKa2wEwHkV0tcYCAFAJzAAd1ZqBLCAczgB84IBXAG34BfIXAC8mHHiIlJ5KrQZwARBVjKRAblCRYPMADl5+GvXFwAhEmQA6KRRm37Cs527W7x4k+Om64sQllZW1gAHowiENfRTh8MFx9eAgAQ2paAHceGLMAMzBqOBhqXhgAC1ZcKGBmXIAKCyijaT8ASkxgODhwaHgoMrABfAAhbABlYtY2Rkn2cw9nR08WxU04CIAVAE86bDgAciYprh4Bfn24ZigkuBSoKGY2VMR+PZgwIp29w9m2fZtgEJgOEwlAUgBbPb8MBsZggW7XJo5Og1eoWBoLLwoZYOPxcdzYxbeHEufyBILKVrtDCdbq6PoDIajCYsdgzVkcCSY6TExZ+bRAkGIUpwDIFADW1wyzHKRTKezBkLgdEU2GoMC2CIeTwIRQ+ADc0swUi9sDpetkVmYuYSsT4rXRtD09EiHQA1NLmRrI-GW3GxckqELA2oNV3++ge6jU2nOhmDfgjca-dnHCR81aAoA)

### 💻 Code

```ts
const obj: {nestedObj: {nestedProp: string | null}} = {nestedObj: {nestedProp: "test"}};
const noNestedProp = !obj.nestedObj.nestedProp || obj.nestedObj.nestedProp === "";

//noNestedProp does not narrow nestedProp for truthiness
if(!noNestedProp) {
  const shouldBeString: string = obj.nestedObj.nestedProp; //Type 'string | null' is not assignable to type 'string'.
}

//same logic as noNestedProp
if(!(!obj.nestedObj.nestedProp || obj.nestedObj.nestedProp === "")) {
  const shouldBeString: string = obj.nestedObj.nestedProp; //works
}

//but works with the same property assigned to variable
const nestedProp = obj.nestedObj.nestedProp;
const noNestedPropVar = !nestedProp || nestedProp === "";

if(!noNestedPropVar) {
  const shouldBeString: string = nestedProp; //works for ts 4.4.4 and newer
}
```

### 🙁 Actual behavior

Error `Type'string | null' is not assignable to type 'string'` on line 5

### 🙂 Expected behavior

No error, as type should be narrowed by noNestedProp check.

**Comment by fatcerberus** [comment]
It doesn’t work because the properties being checked aren’t `readonly`, which is one of the requirements for indirected narrowing.

**Comment by RabbitHunter13** [comment]
```ts
const obj: {readonly nestedObj: {readonly nestedProp: string | null}} = {nestedObj: {nestedProp: "test"}};
```

Yeah, after after adding readonly, it works good. Thanks for clarifying.
