### ISSUE TITLE
Suggestion: Allow arbitrary property access when with string indexer

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#560]
``` typescript
interface Dictionary {
    [key: string]: any;
}
var dict: Dictionary = {};
dict['work']; // Works
dict.work; // Doesn't work
```

Resulting JavaScript is valid but TypeScript blocks this.
Allowing this would allow general JavaScript dictionary use cases.

Example: [from MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.dataset). `el.dataset.id` is generally preferred to `el.dataset['id']`.

``` html
<div id="user" data-id="1234567890" data-user="johndoe" data-date-of-birth>John Doe
</div>
```

``` javascript
var el = document.querySelector('#user');

// el.id == 'user'
// el.dataset.id === '1234567890'
// el.dataset.user === 'johndoe'
// el.dataset.dateOfBirth === ''

el.dataset.dateOfBirth = '1960-10-03'; // set the DOB.

// 'someDataAttr' in el.dataset === false

el.dataset.someDataAttr = 'mydata';
// 'someDataAttr' in el.dataset === true
```

**Comment by kataras** [comment]
We need something like [index:type] :Something . This will tell the compiler to  map any property name and this property will be instance of Something. 

We know what is the object that comes before the dot and  what is after the dot. but we don't know what the name of this property is, so we don't have code assistance.

**Comment by tikotzky** [comment]
Just bumped into this myself...
What I noticed is that destructuring works but direct property lookup doesn't.
extending the example above...
```ts
interface NumberDictionary {
    [key: string]: number;
}
var dict: NumberDictionary = {};
dict['work']; // Works
dict.work; // Doesn't work
var { work } = dict;  // Also works
```
destructuring compiles to direct property lookup so for consistency it probably should work the same.

**Comment by SaschaNaz** [comment]
I think it will be helpful to close this and add a link to the more recent #12596
