### ISSUE TITLE
Link is broken for the discord channel.

### ISSUE THREAD

**Issue by kvramyasri7** [microsoft/TypeScript#56008]
### 🔎 Search Terms

github typescript team

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______
This is nothing major issue.

### 💻 Code

```ts
// Your code here



### 🙁 Actual behavior

https://github.com/microsoft/TypeScript/issues/new/choose


I tried to navigate to open the above link to quickly chat in discord. But seems link the link is broken.  I need to chat with the right people for a feature request in TS docs team.
Could you please update it. Thanks


### 🙂 Expected behavior

Should be able to navigate correctly to the discord channel. 

### Additional information about the issue

_No response_

**Comment by jakebailey** [comment]
The discord link works fine for me.

**Comment by kvramyasri7** [comment]
Thanks for the quick follow up. The chat section of that seemed broken. It is working for me now though. Thanks.👍

**Comment by kvramyasri7** [comment]
Thanks for the quick follow up.
