### ISSUE TITLE
Compiler tests do not look for new-style imports to determine how files should be loaded

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#5600]
We look for [require and reference](https://github.com/Microsoft/TypeScript/blob/master/src/harness/compilerRunner.ts#L80) in the text of the test to indicate that the test files should be loaded as found by the final file in the test. This is odd, but more importantly, it misses `import ... from` statements, meaning for a test to load in the order the code implies, you _must_ use the text `require(` or `reference path` somewhere in your test.

We should replace this odd inference with a comment flag indicating if every file is meant to be included in the compilation (as running `tsc` at the root of the directory), or if only the last file is to be used as an entrypoint.

**Comment by mhegazy** [comment]
:+1:

**Comment by weswigham** [comment]
We do have a flag for this nowadays - `@noImplicitReferences: true`, which forces the test into the mode where all files are found via the last file.
