### ISSUE TITLE
It's incorrect to resolve spread interpolation as intersect

### ISSUE THREAD

**Issue by gomain** [microsoft/TypeScript#56006]
### 🔎 Search Terms

object spread generic intersect

### 🕗 Version & Regression Information

- ~This is a crash:~
- ~This changed between versions ______ and _______~
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: _no mention in the FAQ_
- ~I was unable to test this on prior versions because _______~

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231005#code/GYVwdgxgLglg9mABAWwIYGsCmB1APAeUUwA8pMwATAZ0QG9FUAuBsAT0QF8AaRAIQD4AFHGb4eqAEzNeiAJR0AUIkQAnTFBAqk9AHR6445pJ4cA3ArMKFEBFSiIA7ogC8KDDkH0mdRACNmAIwMNDZgdpzcPhDMEsGIoeEcsubWtnAANpg66XAA5oIOOqg6vi7OrgHJQA

### 💻 Code

```ts
function makeW<O extends { a: any }, B>(o: O, a2: B ) {
  return { ...o, a: a2, };
};

const w = makeW({ a: { b: 1 as const }}, { c: 2 as const });

console.log(w.a.b === 1);
```

### 🙁 Actual behavior

Return type of `makeW` is resolved/inferred as `O & { a: B }` which is wrong.

the returned value `{ ...o, a: a2 }` overrides any `o.a`. 

### 🙂 Expected behavior

type of `w` is `Omit<O, "a"> & { a: B }`.

### Additional information about the issue

Explicit typing works, but should be needed.
```ts
function makeW<O extends { a: any }, B>(o: O, a2: B ): Omit<O, "a"> & { a: B } {
  return { ...o, a: a2 };
};

const w = makeW({ a: { b: 1 as const }}, { c: 2 as const });

console.log(w.a.b === 1); // type error, no `b`.
```

**Comment by RyanCavanaugh** [comment]
Duplicate #10727
