### ISSUE TITLE
Incorrect automatic inference of optional values

### ISSUE THREAD

**Issue by thomasttvo** [microsoft/TypeScript#56003]
### 🔎 Search Terms

Object.values, Object.entries, inference, optional, partial

### 🕗 Version & Regression Information

version 5.2.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgNgQwOZQLxQOQEYNQD6YBMGAUCQMYD2AdgM7BQAeAXAN5QDaA1hCFAJbVYiJAF0A-MygAjSpTgQEQgL5oorDMWYBXagBMIAM0EQ9ygNwUa9KH3QB5aQCsI5YADoAbgjjaItAApGAEpLIA

### 💻 Code

```ts
type Prop = '1' | '2'

const x:{ [key in Prop]?: boolean } = {'2':undefined};
const y = Object.values(x);
```

### 🙁 Actual behavior

the type of `y` is `boolean[]`

### 🙂 Expected behavior

the type of `y` is `(boolean | undefined)[]`

### Additional information about the issue

This can potentially cause a LOT of issues at runtime. The problem boils down to the fact that type inference is not well made for optional type. The `<T>` parameter on `Object.values` resolves to `boolean`. It should resolve to `boolean | undefined`

**Comment by RyanCavanaugh** [comment]
This behavior is controlled by `exactOptionalPropertyTypes`
