### ISSUE TITLE
Two textually-identical types aren't cross-assignable

### ISSUE THREAD

**Issue by TMaszko** [microsoft/TypeScript#56009]
### 🔎 Search Terms

"types incompatibility", "fastify"

### 🕗 Version & Regression Information

- This is crashing my application when I want to test linked package.

### 💻 Code
Reproducible repository with explanation in the README.
https://github.com/TMaszko/ts-bug-main

### 🙁 Actual behavior

Error with two code-wise identical packages with a mismatched version in linked package's node_modules package package.json.

### 🙂 Expected behavior

There should be no error at all if packages are code-wise identical and only versions don't match.

### Additional information about the issue

Having code-wise identical packages when version of the package `fastify2` is a different one from the original `fastify` the error about type incompatibility occurs. When versions are aligned then there is no error at all. One thing that might be related are generic types because if I remove some of the properties from both type definitions the error is gone as well...
So for example:
1. package version in the main project fastify -> 4.23.2
2. package version in the main project fastify2 -> 4.23.1 (only version in the package.json was manually changed)

**Comment by RyanCavanaugh** [comment]
We would need an actual repro to be able to investigate further

**Comment by TMaszko** [comment]
@RyanCavanaugh Added repos for easy error reproduction :)

**Comment by RyanCavanaugh** [comment]
I don't understand why you're saying this is wrong. The error is 100% correct and represents an actual problem you'd have at runtime if you let this proceed.

**Comment by TMaszko** [comment]
The types are code-wise identical in both node_modules the only thing that I changed is the version number in the linked package. Why it is causing any issues?

**Comment by RyanCavanaugh** [comment]
That's not a "problem cause by npm link" bug, that's a "two textually-identical types aren't cross-assignable" bug. Please provide a minimal repro for the latter.

**Comment by TMaszko** [comment]
I don't know how to do that right now :(. The error is gone if versions are matching.
