### ISSUE TITLE
Should Limit `number` based off `if` guard

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [microsoft/TypeScript#56014]
### 🔎 Search Terms

if guard for number

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about if guards.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiDKkDGBLAhgGwHIFcC2UAvFAAxQA+UAjBVAEy0DMA3AFCtID2AdgM7BQ8IAIIAnUUSgBtAEQpgEPFRkAaKHIV46q9fMWMZAXTYYIAoQDVMALlgJk6bPkkk2KAGZQAFELGiAdKbcAObAABZQADzEjACUUADerFCCIFYYkr7i-u4o3AAmAJIFEAAeXrxEAHxQlYT1upra8QDU1MxQAPSdUAAq4NAQ4pyirAC+rEA

### 💻 Code

```ts
type MySpecialNum = 0 | 1 | 2 | 3;

const myArr = ["item1", "item2", "item3"];
let myVal: MySpecialNum = 0;
if (myArr.length <= 3) {
  myVal = myArr.findIndex(s => s === "item2") + 1; // Type error
}
```

### 🙁 Actual behavior

Type error on this line
`myVal = myArr.findIndex(s => s === "item2") + 1; // Type error`

### 🙂 Expected behavior

No type error.

I would expect no type error here because TypeScript has some really good type inference around `if` branches and `typeof`. This is really handy I would expect it to handle the problem above. Here is why I think TS should handle the case above:
- I have declared my type to limit my number to the range 0-3 (which is another feature I'd love to see added)
- Then I am creating a variable to find what position in my list a certain element is and I'm using my custom type
- I have an `if` check to determine if I have less than 3 items in my array so that I can use `findIndex` to get the index of my element and add one to get the position in the list (note this still breaks if I remove the `+ 1` at the end

Ordinarily, one might say that `findIndex` could return something above my limiting type; that is true except I have an `if` statement guaranteeing that won't be a problem. In a sense, it is a kind of guard.

The main counter argument to this might be that we can't do anything about the arbitrary `+ 1` at the end. This is where my very limited knowledge of how TS works shows. I'm not sure if it would be possible to account for that, but I wouldn't think it impossible.

**Comment by RyanCavanaugh** [comment]
This is at least two (probably more) feature requests in one: #26382, #54925,
