### ISSUE TITLE
Assertion functions don't propagate across fn boundaries

### ISSUE THREAD

**Issue by bmeck** [microsoft/TypeScript#56012]
### 🔎 Search Terms

asserts, narrow, multiple, combine

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about asserts

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/DYUwLgBAHhC8EEYBQpIE86JeCAvTyAZgK4B2AxmAJYD2pEhNNAFFAFwSnEC2ARiACcAlBwCGAZ3GCw46BCqyEEAN4BfJEhIVqdBkwBMzNBy59BAGjwme-YSqQQ9LNEIdPmuV+s1NWr8nTiNKAAdMA0AOZ+SAD0MY4JiRAAegD8Gow0hmiWnkgBpEGh4VE5eK5xSUlpSEA

### 💻 Code

```ts
let y = 1
function foo(x: number): asserts x is 1 {}

function foo2(y: number) {
  foo(y)
}

foo(y) // y is 1
foo2(y) // y is number
```

### 🙁 Actual behavior

y is a number instead of getting the result of narrowing via the assertion function foo.

### 🙂 Expected behavior

foo2's return is dominated by foo's return and should adopt it's narrowing.

### Additional information about the issue

This came about trying to figure out a way to have an assertion function that covers more than 1 variable reference:

```ts
// using comma operator in return slot just for demo purposes
function isMember(user: User, org: Org):
asserts user is (typeof user & Member<typeof org['id']>),
asserts org is ActiveOrg
{
}
```

**Comment by RyanCavanaugh** [comment]
This is largely intentional; assertion functions are *never* inferred since it's not always the case that that's an intended effect of your function.

**Comment by bmeck** [comment]
@RyanCavanaugh sounds good, but this isn't a valueful return, the return in the example was just showing it is just intended to assert over 2 things was how I found this; having a way to assert over 2 variables would equally satisfy things but that seems like it would be a grammar change / more of a feature than a bug

**Comment by RyanCavanaugh** [comment]
Right, but if it were inferred as one, then it looks like a bug when you to from this
```ts
function fn(y: string | number) {
  assertIsString(y);
}
// Elsewhere
let x: string | number = ...;
fn(x);
x.substr(0);
```
to this
```ts
function fn(y: string | number) {
  assertIsString(y);
  return y.length;
}
// Elsewhere
let x: string | number = ...;
fn(x);
x.substr(0);
```
and the code in 'elsewhere' changes for no apparent reason
