### ISSUE TITLE
String Literal refactoring support

### ISSUE THREAD

**Issue by basarat** [microsoft/TypeScript#5602]
Thanks for https://github.com/Microsoft/TypeScript/pull/5185 :rose:. Would be great if we could get refactoring support for string literals 

``` ts
type Foo = "aReallyLong" | "bReallyLong"; // allow me to rename any of these values
let foo:Foo;
foo = "aReallyLong"; // allow me to rename this value
```

refs https://github.com/Microsoft/TypeScript/issues/5554#issuecomment-155622379

**Comment by falsandtru** [comment]
+1

**Comment by mhegazy** [comment]
PRs are welcomed. 

The change should be done in services.ts::[getReferencedSymbolsForNode](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L5547). String literals do not have a symbol, so we will need to check their contextual type, and if it is a string literal type, replace all strings with the same contextual type.

**Comment by DanielRosenwasser** [comment]
> so we will need to check their contextual type

This will require a breaking change in the type checker API because right now the exposed `getContextualType` returns the apparent type.

**Comment by mhegazy** [comment]
ah. we can add another one, to return the string literal type at a location then.

**Comment by DanielRosenwasser** [comment]
I think we should just do the correct thing and make the break. I don't think most people will be affected by it, and It's going to be necessary elsewhere. We should favor a more general solution that gets users where they need to be than one that solves a specific use-case. I'll make the change and see what breaks in our language service.

**Comment by Duckers** [comment]
Bump. Perhaps this wasn't that urgent in 2015 when filed, but now with the level of sophistication TS has reached I think this should be reconsidered for roadmap.

Whether this feature exists or not is a pretty big deal wrt. what should be considered best practice for enums when writing new code/new APIs. 

String literals have benefits over enums as they require no imports to be used, is easy to debug and serialize, and makes for less verbose code. Also a critical tool for javascript interop where there are no pre-existing enum objects. 

Without refactoring support, committing to string literals as best practice for how we design APIs in TypeScript is sketchy.

**Comment by Niryo** [comment]
I don't get something...It looks like Intellij IDE can do exactly what we ask for in this Issue. How the hell Intellij can do this if it's not supported in Typescript itself?

**Comment by fuafa** [comment]
Maybe IntelliJ implements their own language service?

**Comment by Niryo** [comment]
I don't know...Maybe typescript already supports this and it's now an issue with VScode? What about this merged commit #5615, did it solve the issue?

**Comment by aspirisen** [comment]
That would be very handy to have such feature in TypeScript

**Comment by dontsave** [comment]
Bump. This should be a feature in TypeScript and VSCode in 2020. Right now to get refactoring behavior in VSCode you have no choice but to use string enums, which are far less elegant

**Comment by theluk** [comment]
mega bump

**Comment by Kingwl** [comment]
I'd like to take a try on this.
