### ISSUE TITLE
Module Programming without Modules

### ISSUE THREAD

**Issue by clickclickpwn** [microsoft/TypeScript#56025]
### 🔍 Search Terms

"embeddable modules" "modules" "call a function without import and export" "all in one file" "multiple scripts"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

A way to label scripts as objects, or get functions as methods by a script ID, or any variable inside to another script, without having to use import and export, by using script tags in html.

I hope what I write below and reference helps and motivates you, thank you for your time.

### 📃 Motivating Example

[https://github.com/clickclickpwn/embeddable-modular-programming-example-for-Javascript](url)

I created this repository to show a real live example of how this actually works in vanilla, and doesn't break the code or involve extensive libraries, the readme also gives the philosophy for it and how I came up with this trick. I just don't know how to contribute it to the typescript and JavaScript community. Or how to create it into a feature, like a keyword or something new besides using the ID and creating a script as a callable object, thats what i discovered working with my chatGPT robot.

I like making code that i can copy and paste to google sites, like a website within a website, or an html widget, they get complex though as they do multiple tasks, so it got me into modular programming, the problem is i cant copy paste multiple files, it had to be one for this problem, and thats how i found out this trick.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

1. Embeddable programming, more portability and less files. Copy Paste your html file with multiple scripts anywhere and it works with easier readability. Or, make this easier, less lines of code, call a script as an object, use its functions as methods.
2. It relies on the DOMs order of data loading to work, so if you dont order the script tags a certain way they may not work.
3. I call the script tag by ID, then it runs the function from that ID object called, I havent tested making the function into a method, but this is me working around importing and exporting multiple modules to make an HTML file embeddable and more readable to the user as it gets more complex.

**Comment by IllusionMH** [comment]
```
// Access the script element by its ID (Script 1) 
 const scriptElement = document.getElementById('myScript');
```

That's not how you access function from other script, your function is just in global scope and therefore accessible by name in any other script on the page.
You can just write `.ts` files without `import`/`export` and have access to other global functions/variables as well

**Comment by clickclickpwn** [comment]
> ```
> // Access the script element by its ID (Script 1) 
>  const scriptElement = document.getElementById('myScript');
> ```
> 
> That's not how you access function from other script, your function is just in global scope and therefore accessible by name in any other script on the page. You can remove these lines.
> 
> You can just write `.ts` files without `import`/`export` and have access to other global functions/variables as well

It is accessed this way, as it works in the console.log.

the point of this idea is to not write multiple files, but to embed it into html in a different way.

It is not global, it is in different script tags in one global html file. the variables are local to the script objects.

I do appreciate your input as well because I didn't know that about type script.

The end goal is for embedding while making it modular within HTML itself, not outside in a directory or in separate files.

**Comment by clickclickpwn** [comment]
> ```
> // Access the script element by its ID (Script 1) 
>  const scriptElement = document.getElementById('myScript');
> ```


I just tested out what you suggested, and very cool, you don't need this line, i was wrong, if youd like you could remove it from my repo to get credit for that, thank you for showing me this.

The one thing that keeps it from being truly global though, is the order of the scripts in the HTML.

If i put myScript2 first in the html file, it wont be called. 

How would we make this global? and if we could, could we use import and export by ID for script tags to work around the need to keep it a specific order?

Just saying ideas for this problem, and potential new workarounds for the future user.

The key point of this problem is to expand upon single file programming.
