### ISSUE TITLE
Version 5.2.2 broke declaration merging when redeclaring a class merged with a namespace.

### ISSUE THREAD

**Issue by miguel-leon** [microsoft/TypeScript#56031]
### 🔎 Search Terms

declaration merging namespace class 

### 🕗 Version & Regression Information

Works well up to the previous version v.5.1.6.
Stopped working in current version 5.2.2.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/CYUwxgNghgTiAEkoGdnwPIwJYHMsDsoIAeAFQD54BvAKHnvgDMB7ZgLnlIG4aBfG0EjjxCAWxDIADlDAJMuAkWp0GIAB6TmMAC7xtAT0kIAQrHgBeeACVwW4MWTbs+HABoRAV1EAjEDHJ8NEHqmjrwgtDCYMz4jtYgEbBQ2lgxHAZGzIwY2HiEEDwhWrqJwhkINqXJqfhklJbyeUR1hRrF4eCRCGIS0rLxVSkxygzwWKKhuqYwFjkK+QB00zyjRWFU8NPwvDz8QaUI0bG63rAclZ1JQ-hLsFxAA

### 💻 Code

```ts
declare class Original<T> {
    foo: T;
}
declare namespace Original {
    export type Bar = Record<string, number>
}


export declare const Redeclaration: typeof Original;
export declare type Redeclaration<T> = Original<T>;
export declare namespace Redeclaration {
    import Bar = Original.Bar;
    export { Bar };
}


declare const bar: Redeclaration.Bar;
```

### 🙁 Actual behavior

Error 2451 Cannot redeclare block-scoped variable.

### 🙂 Expected behavior

Should do the declaration merging.

### Additional information about the issue

The example code may look a bit strange because it's a simplified minimal reproduction where it seems there's no need to redeclare.
One probable reason might be the need to slightly modify a type to re-export it.

[v5.1.6 link](https://www.typescriptlang.org/play?ts=5.1.6#code/CYUwxgNghgTiAEkoGdnwPIwJYHMsDsoIAeAFQD54BvAKHnvgDMB7ZgLnlIG4aBfG0EjjxCAWxDIADlDAJMuAkWp0GIAB6TmMAC7xtAT0kIAQrHgBeeACVwW4MWTbs+HABoRAV1EAjEDHJ8NEHqmjrwgtDCYMz4jtYgEbBQ2lgxHAZGzIwY2HiEEDwhWrqJwhkINqXJqfhklJbyeUR1hRrF4eCRCGIS0rLxVSkxygCQWKKhuqYwFjkK+QB001wM8DQjRWFU8NPwvDz8QaUI0bG63rAclZ1JQ-hLsFxAA)

**Comment by RyanCavanaugh** [comment]
Bisects to #54816
