### ISSUE TITLE
String Literal autocomplete support

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5603]
Thanks for https://github.com/Microsoft/TypeScript/pull/5185 :rose:. Would be great if we could get autocomplete support for string literals 

```ts
type Foo = "aReallyLong" | "bReallyLong";
let foo:Foo;
foo = "aReallyLong"; // allow me to autocomplete this
```

refs https://github.com/Microsoft/TypeScript/issues/5554#issuecomment-155622379

**Comment by DanielRosenwasser** [comment]
Looks like a duplicate of #606.
