### ISSUE TITLE
(intellisense) No suggestions for imports when tsconfig-paths has been added

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/TypeScript#56059]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.84.0-insider (user setup)
Commit: 874831ebcf088f59735879156f62308ce48f17d1
Date: 2023-10-06T19:09:07.673Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: Window 10 x64 22H2

Steps to Reproduce:

1. Clone: https://github.com/JonWallsten/vs-code-intellisense
2. npm i --force
3. Open repo in VSCode
4. Go to `packages/main-app/src/app/app.component.ts`
5. Try to use Ctrl+Space for one of the missing imports

It will state `No suggestions`.
If you uncomment the imports they will work.

![image](https://github.com/microsoft/vscode/assets/5993909/39087a55-8e08-41c5-b746-9a0ac2acb8b7)

![image](https://github.com/microsoft/vscode/assets/5993909/e4e6b1a8-69df-49a6-a2fb-7f809b5a7688)

If I remove the paths I get this:
![image](https://github.com/microsoft/vscode/assets/5993909/8c20fe7b-235d-4bd8-9ec0-eb5c76a63148)

But only once, then i get this again:
![image](https://github.com/microsoft/vscode/assets/5993909/23c1b5ce-b98d-4cf9-97fd-c555b27488bc)

Worth to mentioning is that after one import has been manually added in the app, the IntelliSense works fine for the affected path.

**Comment by RyanCavanaugh** [comment]
Auto-import can only offer files that it's already aware of. Until that first import occurs, those target files are outside the scope of analysis

**Comment by JonWallsten** [comment]
> Auto-import can only offer files that it's already aware of. Until that first import occurs, those target files are outside the scope of analysis

@RyanCavanaugh: Can it be provide to the scope manually somehow?

**Comment by RyanCavanaugh** [comment]
You can put them in your tsconfig `files` list

**Comment by JonWallsten** [comment]
I just tried that but it still doesn't work, unfortunately.
I added them both in the lib and the app to make sure.
Please check the updated repo if you have the time to make sure I did not do anything wrong.

**Comment by andrewbranch** [comment]
It sounds like there may be a bug; I’ll have to take a closer look a little later, but I want to add right away that it’s highly recommended to use package manager workspace features instead of `paths` for monorepos. `paths` should usually be a last resort override for resolutions that the compiler can’t possibly know about any other way. It was originally made to support the RequireJS AMD loader for the browser, and it’s not recommended to use it as a convenience feature for enabling friendly module specifiers, _especially_ when packages with package.json files are involved. `paths` will very intentionally _not_ work the same way as real node_modules package resolution.

**Comment by JonWallsten** [comment]
@andrewbranch: Thank you for the explanation. I definitely guilty of using it "as a convenience feature for enabling friendly module specifiers" in our monorepo. Path of least resistance etc! I will look into alternatives meanwhile.

**Comment by andrewbranch** [comment]
Every package manager supports [workspaces](https://docs.npmjs.com/cli/v10/using-npm/workspaces?v=true) and TypeScript just works with those 👍

**Comment by fatcerberus** [comment]
> `paths`

> not recommended to use it as a convenience feature for enabling friendly module specifiers

The worst part is that the docs used to imply that this was the *intended* use case ("if you're tired of writing `../../../foo`" etc.).  Thankfully that bit has been removed.
