### ISSUE TITLE
Rename Symbol F2 with "pure keyof" is not possible - but it is possible if "wrapped as calculated property"

### ISSUE THREAD

**Issue by qwertysk** [microsoft/TypeScript#56052]
**I think this could be related to typescript only, even I reported it also here** https://github.com/typescript-language-server/typescript-language-server/issues/767

### 🔎 Search Terms

Rename symbol, keyof

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://tsplay.dev/N7QgPW

### 💻 Code

```ts
////////////////////////// CASE 1 - keyof to computed property /////////////////////////

declare const Att_1: "Att 1"

interface Case_1 {
  [Att_1]: string
}

declare const fnc_1: <K extends keyof Case_1>(p: K) => void

fnc_1("Att 1")
//     ^_ Rename Symbol F2 => SUCCESS



////////////////////////// CASE 2 - pure keyof //////////////////////////

interface Case_2 {
  "Att 2": string // here is the difference, pls compare to Case_1
}

declare const fnc_2: <K extends keyof Case_2>(p: K) => void

fnc_2("Att 2")
//     ^_ Rename Symbol F2 => FAIL
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/45438489/9cc37b11-52fb-41e8-8fc2-f445108ac29a)

It is wrong because `Att 2`  in `interface Case_2` is not renamed 

### 🙂 Expected behavior

I expect `Att 2` in `interface Case_2` to be successfully renamed to `Attribute 2`

### Additional information about the issue

Even it is not "a bug but the feature", is there best practice - if reliable renaming is really frequent and important in my project ?

**PLS HELP ME ❤️❤️❤️ ... because manually create tons of constants for all project interfaces and all attributes - this is not maintanable way - any other ideas/patterns please ?**

**Comment by qwertysk** [comment]
@sandersn this issue is not completed - try it yourself pls, see playground link above.

**Comment by a-tarasyuk** [comment]
@qwertysk [Playground](https://www.typescriptlang.org/play?ts=5.4.0-dev.20231213#code/PQ18eAEDCCCBlAolAjFSmvAFA4CYCmAxgDYCGAToVMQPYB2AzgC5RwssD6qAXFACIObVALwBLBi0KUAZuWI0Y5JoR5QA3jihQA2sJ4Bdfq0qSA5jgC+eImSo16zNrIbEe-ADwBpKIQAe0gz4TFAA1oQAnnSysCpqqAB8ABQADvzeAJRQALyJUABudOL4eK7uqMlCnGgCmTggOk0AelxQAEqEDOQAtjQIkT0ARnSkUABiAEy5+QgAqjAwSAgIeHjYG9DwyFDTm-u4OJLScgpK8VzTWjrVbJMCJixmDJY2BCQU1LSMrFDll15fAEgiFwlEYnFVJcUukoFkZoViqUcP9JlVhLs6g1gE0dK0Ol1ev1BiMxlMEeM4ABJAAyQA) - Both examples can be renamed. Could you provide additional cases that should be covered?

https://github.com/microsoft/TypeScript/assets/509265/e9fc63cd-d184-43e5-b789-f82fd965456f

**Comment by qwertysk** [comment]
![image](https://github.com/microsoft/TypeScript/assets/45438489/3bffd3ab-38b3-4951-afd5-85f91c31e974)

[Playground](https://www.typescriptlang.org/play?ts=5.4.0-dev.20231213#code/JYOwLgpgTgZghgYwgAgJLIN4ChnIEQAKUA9gA7ICMyAYscXgFzIDOYUoA5lgL64D0fZAD1kpADbNkbAJ7IoEEHAC2KYGGQALaCgC0yNfskxgADwgATLFazmICMXHnIExEK2QwQTADwBpZBAmkCDmkgDWENLEMGgAfAAUpEy+AJTIALyxyABuxMCWWJ7xhCTkVLT0KVgCuLgi0hCSevKKKprayADucJJwYvJw5rLGZuZAA)

**Comment by sandersn** [comment]
I opened #57026 to track the follow-up fix.
