### ISSUE TITLE
Parameter inlay hints show the wrong parameter names

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript#56078]
### 🔎 Search Terms

inlay hints

### 🕗 Version & Regression Information

I'm not sure in which version it started, but it is present in 5.2

### ⏯ Playground Link

Does not work in the playground, needs VSCode with parameter inlay hints enabled

### 💻 Code

```ts
declare function foo(
    arg1: number,
    arg2: string | null,
)

declare const num: number;

foo(num, null)
```

### 🙁 Actual behavior

The inlay hint for `arg2` shows `arg1`
![grafik](https://github.com/microsoft/TypeScript/assets/17641229/b9551899-bff7-4d7f-bf70-3c3b08cc3680)

### 🙂 Expected behavior

The inlay hint for `arg2` should show `arg2`

**Comment by MartinJohns** [comment]
Sounds like a duplicate of #55866.

**Comment by AlCalzone** [comment]
Indeed. Somehow I didn't find that.
