### ISSUE TITLE
Decorator cannot set on top of overload method

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5608]
I want to use a following design.

```ts
// hello.ts
class C {
  @readonly
  method()
  method() { }
}

function readonly(target, key, descriptor) {
  descriptor.writable = false;
}
```

```
$ node built/local/tsc.js hello.ts --noEmit --target ES5
hello.ts(2,3): error TS1206: Decorators are not valid here.
```

**Comment by mhegazy** [comment]
Decorating an overload does not make much sense, the overload does not exist at runtime, but this when the decoration happenes. you should be decorating the implementation instead.

```ts
class C {   
    method(a: string);
    method(b: number);
    method();
    @readonly
    method(a?:any) { }
}
```

**Comment by falsandtru** [comment]
It is regrettable. Thanks for your answer.

**Comment by Buildstarted** [comment]
Seems to me the decorator should just filter down to the implementation. cleaner to have the overloads closer to each other and the `@decorator` on top of them all - the decorator can easily get lost in the clutter of doc comments and what not.

**Comment by DanielRosenwasser** [comment]
That's a bad error message though, so I've filed #6064.
