### ISSUE TITLE
Array of objects union - autocompletion & intellisense not working properly

### ISSUE THREAD

**Issue by ivodolenc** [microsoft/TypeScript#56082]
### 🔎 Search Terms

"array of objects union", "array union narrowing", "union narrowing", "object union operator in"

### 🕗 Version & Regression Information

TypeScript: 5.2.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKLisCBnZBvAKGWOQHoAqcok5c5ABQBsBXAc1F1BgHsA6f6iXKlByAA4t2IbAH4AXMgBKEBNygATADzYwmEKwA0SlWq069h5MxABrENwDuIAHzPRFKjVrIA8szBi-shcfAJewqLc-oFg8sjmoKzulKLeAGJqALZwYMEgPPy8qRE0PFDZsQoJ+gQAvgQEoJCwiCgAkiAxyBAAHpAg6rjouli4hDQexcgdXSGFxSI0oDFVIzX1jeDQ8EjIACoAnmI43X0QA0MYo-jJnjR0h8ec+aFF4YskYEc4qxZ1DV9jmgrjgfGIwMBuNJkABeaadIIAH3232wDQIqmkuW44Mh0gUw0woNxUOwAG0ALqw5Bk0TjLzEZb+BQAcl4pGwUAQpFA6l6vDA2BZRiiAWZyDZpHUwB0PIG-MyACshaJagY6alPqjWezOdzATgBUKjGUKqycJkWaqCBSgA

### 💻 Code

Here is live [playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKLisCBnZBvAKGWOQHoAqcok5c5ABQBsBXAc1F1BgHsA6f6iXKlByAA4t2IbAH4AXMgBKEBNygATADzYwmEKwA0SlWq069h5MxABrENwDuIAHzPRFKjVrIA8szBi-shcfAJewqLc-oFg8sjmoKzulKLeAGJqALZwYMEgPPy8qRE0PFDZsQoJ+gQAvgQEoJCwiCgAkiAxyBAAHpAg6rjouli4hDQexcgdXSGFxSI0oDFVIzX1jeDQ8EjIACoAnmI43X0QA0MYo-jJnjR0h8ec+aFF4YskYEc4qxZ1DV9jmgrjgfGIwMBuNJkABeaadIIAH3232wDQIqmkuW44Mh0gUw0woNxUOwAG0ALqw5Bk0TjLzEZb+BQAcl4pGwUAQpFA6l6vDA2BZRiiAWZyDZpHUwB0PIG-MyACshaJagY6alPqjWezOdzATgBUKjGUKqycJkWaqCBSgA).

```ts
interface Entries {
  /**
   * Plugins info...
   */
  plugins?: Record<string, Record<string, unknown>>
  /**
   * Output info...
   */
  output?: string
  /**
   * Format info...
   */
  format?: string
}

interface Input extends Entries {
  /**
   * Input info...
   */
  input: string
}

interface Types extends Entries {
  /**
   * Types info...
   */
  types: string
}

type EntriesOptions = Input | Types

const options: EntriesOptions[] = [
  {
    input: './src/index.ts',
    output: './dist/index.mjs', // there is no description when you hover over the prop
  },
  {
    types: './src/types.ts',
    format: 'esm', // there is no description when you hover over the prop
  },
]
```

### 🙁 Actual behavior

Hi, I've noticed that when using an array of union objects, the autocomplete/intellisense doesn't work as expected in VSCode.

Also, properties from the `Entries` object don't get description info or offer proper auto-completion which can be confusing.

### 🙂 Expected behavior

I expect it to offer the correct auto-completion for each object and provide the right information when I hover over a property to see the type or description of what that option does.

### Additional information about the issue

-

**Comment by ivodolenc** [comment]
Here are the screenshots:

<img width="484" alt="" src="https://github.com/microsoft/TypeScript/assets/51852491/378c474f-1f94-4ea3-b448-ea21d253efcd">
<img width="452" alt="" src="https://github.com/microsoft/TypeScript/assets/51852491/64d5ef44-5d0f-4ba1-9595-9bb402ecbfb5">
<img width="435" alt="" src="https://github.com/microsoft/TypeScript/assets/51852491/82096711-10e6-493b-96d6-091c0e6d26e2">

**Comment by ivodolenc** [comment]
Hi and sorry to ask again, is this already implemented or does it still need some internal improvements?

To be specific, I have a `TS` [project](https://github.com/hypernym-studio/bundler/blob/main/src/types/entries.ts) that loads the configuration from the project root via the `defineConfig({ entries: [] })` function that uses an array of objects.

But this `entries` array has interfaces of multiple types and I'm having a hard time debugging why `TS` doesn't infer correct types and doesn't offer auto-completion when adding new options to an object in VSCode.

I created a minimal reproduction via a new [TS playground](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgKLigTwEJwM4oDeAUMmcgPQBUVp5yVyA8gK5gAObyoMA9gHSC65KhWHJebTmAD8ALmR4wUUAHNx1WvQbIAYrygBbOGG4g+g-uIZj6fIyfmLlajTWuMAcnEMoeAoW1RcRAfCCclFRB1AF9iYlBIWEQUdGVMAEkQaWQIAA9IEAATPDQMHHwiNy16Riyc-0sPW3JQaQVI13pND2QABQAbFlVQUra2JqCWsnYhkZA8JwAlCAQDIoAeTuiAGmQVtahN7dU9lhAAaxBeAHcQAD574jiE8Gh4JDL0gBVMdghSvlCiUvlhcARkCRuu4gshfv8xuYAlYpuIwH8AR0XNFqr1BsNRsh0QjJrVpshZgSFstVusttjTvtaUd6VFGecrrcHk8XsTUhhgACmOwwMBeAtkABeUGZbJcAA+MvhAPixDWC1MvBFYoWCjSKiF2vFeAA2gBdKXIE3iKHaMjjMAKADk-AoeCgCAooCK+X4YDwTr2kg4bGdrqKwCUXuKvsMACsA3tKfM8ApCLk8AAjFjAAZFNMxZBxegxHY26zkPmp5Aut0eihVv2J5D2YyOmsAwyBilzUZp5BFf0FoviOJmoA) link to better see the issue.

<img width="622" alt="Screenshot 2024-09-11 at 20 38 53" src="https://github.com/user-attachments/assets/ed4c3cb5-608b-4926-90fe-1ea16e524738">

<img width="625" alt="Screenshot 2024-09-11 at 20 38 59" src="https://github.com/user-attachments/assets/a348f81d-b381-49e8-a20d-94bbe5995fa3">

**Comment by ivodolenc** [comment]
> I created a minimal reproduction via a new [TS playground](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgKLigTwEJwM4oDeAUMmcgPQBUVp5yVyA8gK5gAObyoMA9gHSC65KhWHJebTmAD8ALmR4wUUAHNx1WvQbIAYrygBbOGG4g+g-uIZj6fIyfmLlajTWuMAcnEMoeAoW1RcRAfCCclFRB1AF9iYlBIWEQUdGVMAEkQaWQIAA9IEAATPDQMHHwiNy16Riyc-0sPW3JQaQVI13pND2QABQAbFlVQUra2JqCWsnYhkZA8JwAlCAQDIoAeTuiAGmQVtahN7dU9lhAAaxBeAHcQAD574jiE8Gh4JDL0gBVMdghSvlCiUvlhcARkCRuu4gshfv8xuYAlYpuIwH8AR0XNFqr1BsNRsh0QjJrVpshZgSFstVusttjTvtaUd6VFGecrrcHk8XsTUhhgACmOwwMBeAtkABeUGZbJcAA+MvhAPixDWC1MvBFYoWCjSKiF2vFeAA2gBdKXIE3iKHaMjjMAKADk-AoeCgCAooCK+X4YDwTr2kg4bGdrqKwCUXuKvsMACsA3tKfM8ApCLk8AAjFjAAZFNMxZBxegxHY26zkPmp5Aut0eihVv2J5D2YyOmsAwyBilzUZp5BFf0FoviOJmoA) link to better see the issue.

Should I open a new issue for this (as I mentioned in the comment above)?

**Comment by sandersn** [comment]
Yes, please open a new issue for this and reference this PR.
