### ISSUE TITLE
[TypeChecker] Weird type checking, requiring a "{} &" intersection hack

### ISSUE THREAD

**Issue by gustaveWPM** [microsoft/TypeScript#56080]
### 🔎 Search Terms

"type checker", "{} &"

### 🕗 Version & Regression Information

_nothing_

### ⏯ Playground Link

https://www.typescriptlang.org/play#code/KYDwDg9gTgLgBDAnmYcBCBDAzsAYgS2ABsATLOAXjgG8AoOBfGI4ALhoWTbgHIsYo+AHYBzHgG44UYAEcArvmkl2AuagC+4+nAC2wGBhLAsAY0FgY+CEPbVOKdnwHCxk6fMXBlCKGribtI1NzS2tbe24nQVEJKVkFJXYAMwwiHH8tBhIMGG47JAdebNzY9wSvFV8NTLg5KCJwgsj+aNc4j0SfPwCA2lBIWDgTa344AAUACQBBADkAFQB5AFkAfTGFgGU5lYBhBZncAEkAcXYAEQgTOT0hGB3rJPwROa5KGm0hDD1HMYALDFuEB0Ywg-B4ABptI8WGMcr9YTBclAbLwIVDCKQsLZtAxLMw8hFHC0XBD2uVvKoNJCGFljGZ8BYrCj8lwic4YuCyZ5vCk0lScbp9IY6SEmY1WbxiRyuZ1Kf5qTTigSmo4laSytzKt0FQw6g0OCrJeyxJyNbKqv5tOpaOo4NghiMYFpaMMhKMSNcdIgQfx7kJHiIAOpMX73HRgOS5EgEYhkACiIC+YBY50u12Atz9AZeKAAPDw9TwAHxvOgMT7fXhnT3e0EwNEMaHABHwnJIlE8ABUnYA9EIILksD3u8OAHQ6EgNuCPWNY940xj48WFKIk03xTVdfkLoL0xlhA0S1fSs0VaepdLqHWCgy70UHlkrqUmmVnuVXgVK5eRNXrjpvi1rQYD8GGGcNIy8GNMWxBc9W-NlWnVYwICIAA3bgAApIH4dgAUQABKSgSwAAx7AASahsJgUcVigDAAHdRySIg2wzLwW3UYjLWAm07XIV1+GdfpoHgJo4AuK4bjuB4nhzYBczDCMoygsg4FAXIhFUgBrYBEAgJJ0GwPAMVUqghGAdCoBLKhqFtAAyOBFIg6MTPIdSM1U8zLO0AB+cS0ykrNZK4BMBGwJYhWKe0HLsGdoMMnAVPIIC4FTSSM2k-1gpQUK6KwCLbxyaL5wXadXPYBYdCYXNMES1zOSc5TXKLGoFzApTIPKxygQ6lzZyWDAwBQEg5ggWFYHwVJauM2cNmuOSFJ65ykpagVemEwYxMazrZ1LbQAG0AGk4GEOAdL0gzpqSgBddhtr60hc0O1bejEuSZi+VAqGfLQxIIGE4QRds3h+2haDEiT00zGTnhCkAwvyyKivIGyPk+9h3s+momxbIHgGRdh-ubQHWORLRXtee6VKetT4Y88hzv0hKZsxay4Eq6qrtco7rs5HhT0nEsYriLAUPQ9gMNHKWMCgEQ5zw-brsIigSzkIQtP7eihAyMGtqWpr+sG4bRvGywpqMpK5p0BbjvczSGd0pmudnNmyzgfaxhO7XDtu7rwINx7nvJrQgA

### 💻 Code

```ts
export type BaseFields = {
  title: { type: 'string'; required: true };
  metadescription: { type: 'string'; required: true };
  description: { type: 'string'; required: false };
  date: { type: 'date'; required: true };
  url: { type: 'string'; required: true };
};

export const PHANTOM_POST_CONFIG: DocumentConfigType = {
  name: 'PhantomPost',
  filePathPattern: '',
  fields: {
    title: { type: 'string', required: true },
    description: { type: 'string', required: false },
    metadescription: { type: 'string', required: true },
    date: { type: 'date', required: true },
    url: { type: 'string', required: true }
  }
} as const;

const dummyPostConfigWithComputedFieldsExample: DocumentConfigType<'url'> = {
  name: 'DummyPost',
  filePathPattern: '**/notes/**/*.md',
  fields: {
    title: { type: 'string', required: true },
    description: { type: 'string', required: false },
    metadescription: { type: 'string', required: true },
    date: { type: 'date', required: true }
  },
  computedFields: {
    url: { type: 'string', resolve: (post: any) => `/${post._raw.flattenedPath}` }
  }
} as const;

export type DocumentConfigType<ComputedFields extends keyof BaseFields = never> = {} & ComputedFields extends never
  ? DocumentConfigTypeExtrasMetadatas & { fields: BaseFields }
  : DocumentConfigTypeExtrasMetadatas & {
      fields: Omit<BaseFields, ComputedFields>;
      computedFields: ComputedFieldsMappedToPartialBaseFieldsSumType<ComputedFields>;
    };

export type ComputedFields = {
  [K in keyof BaseFields]: ComputedField<K>;
};

type TypeName = string;
type FilePathPattern = string;

type DocumentConfigTypeExtrasMetadatas = {
  name: TypeName;
  filePathPattern: FilePathPattern;
};

type ComputedField<K extends keyof BaseFields> = Omit<BaseFields[K], 'required'> & { resolve: (...args: any[]) => unknown };

type ComputedFieldsMappedToPartialBaseFieldsSumType<K extends keyof BaseFields> = {
  [P in K]: ComputedField<K>;
};
```

### 🙁 Actual behavior

When removing the strange `{} &` (`DocumentConfigType`), the _Type Checker_ raises an error on the declaration of the `PHANTOM_POST_CONFIG` constant:
> ... is not assignable to type 'never'.ts(2322)

### 🙂 Expected behavior

No need to use the strange `{} &` hack.

**Comment by MartinJohns** [comment]
This is working as intended. Your variable is typed `DocumentConfigType`, you do not provide a type parameter and specify the default as `never`, so `ComputedFields` is `never`. Within this type you use this type argument in a distributive conditional type, and `never` always distributes to `never`.

**Comment by gustaveWPM** [comment]
> Also, `keyof BaseFields | never` is just a long and pointless way to write `keyof BaseFields`. The type `never` represents an empty union type. Having this in a union with another type essentially removes it.

Oh, thank you! I wasn't aware of that.

> This is working as intended. Your variable is typed `DocumentConfigType`, you do not provide a type parameter and specify the default as `never`, so `ComputedFields` is `never`. Within this type you use this type argument in a distributive conditional type, and `never` always distributes to `never`. Check the documentation of conditional types for more information about distributiveness.

> and `never` always distributes to `never`

That's what I noticed.
But I don't find it very intuitive in this case.

Thank you for your fast and clear answer!
