### ISSUE TITLE
Destructuring and function properties

### ISSUE THREAD

**Issue by Kinchkun** [Microsoft/TypeScript#5609]
Hi,

we are using Visual Studio 2013 with TS 1.6

i don't get why this is valid:

```typescript
function foo({bar: string}) {}
```

but this leads to a compile error:

```typescript
function foo({bar: () => string}) {}
```

Compile error message is "Cannon find name string".

For me this is a defect behavior. What do you guys think?

Kind regards,
Timo

**Comment by falsandtru** [comment]
Correct code example:

```ts
function foo1({bar}: {bar: () => string}) {}
function foo2({bar = () => ''}: {bar?: () => string}) {}
```

**Comment by Kinchkun** [comment]
I see, thank you!

Kind regards,
Timo
