### ISSUE TITLE
"Go to Definition" does not work with wildcard imports

### ISSUE THREAD

**Issue by StephenVHendrix** [microsoft/TypeScript#56092]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.83.0
- OS Version: Ventura 13.6

### Steps to Reproduce:

1. Use this configuration in `jsconfig.json`:

```json
{
  "compilerOptions": {
    "moduleResolution": "classic",
    "paths": {
      "~/*": ["./src/*"]
    }
  }
}
```

2. Create a component in `src/components/component.js` and default export it:

```javascript
export default function Component() {
  return (
    <div />
  );
}
```

3. Import the component using wildcard syntax and invoke it:

```javascript
import { Component } from '~/components/*';`

export default function Page() {
  return (
    <div>
      <Component />
    </div>
  );
}
```

4. Right-click the component in either the import statement or invocation and select "Go to Definition."

### Expected Behavior:

`component.js` is opened in a new tab.

### Actual Behavior:

Cursor simply moves to the other occurrence of `Component` within `Page`.

### Notes:

- `import Component from '~/components/component';` does work as expected.
- There is no `index.js` file in `components`.
- Changing the value of the `moduleResolution` property in `jsconfig.json` or adding a `baseUrl` hasn't changed anything.
- The expected behavior occurs in this scenario when using Sublime Text.

**Comment by mjbvz** [comment]
What tools support using `*` in the import path?

**Comment by StephenVHendrix** [comment]
> What tools support using `*` in the import path?

Sublime Text!

**Comment by mjbvz** [comment]
But what JS bundlers or frameworks support it?

**Comment by StephenVHendrix** [comment]
I'm doing a transformation with Next in my `next.config.js` under `modularizeImports` if that's any kind of answer? But your questions make me feel like I'm missing something. If I'm wrong to expect this behavior from every IDE and/or it's not a bug, please don't let me waste your time!

**Comment by RyanCavanaugh** [comment]
`*` in an import path is generally not supported; this is the first I've heard of someone trying.

> I'm doing a transformation with Next in my next.config.js

The JS language service has no idea about this kind of operation, so can't predict what the output path will look like, e.g. if you had `component1.js`, `component2.js`, and `component3.js` in `/component/`, each of those seems like equally valid targets. I'm not really clear on what this schema is -- it's possible if the only file in there was named `index.js` it would be resolved, but I'm not sure.
