### ISSUE TITLE
Hi, does anyone pay attention to the update of the document Localizations?

### ISSUE THREAD

**Issue by fullmooooon** [microsoft/TypeScript#56095]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

https://github.com/microsoft/TypeScript-Website-Localizations

TypeScript-Website-Localizations 's PR has been overstocked for a long time.
I have noticed this since a year ago.

I believe there are many people who are as difficult as I am to understand static type terms without a local translation.

**Comment by fatcerberus** [comment]
Probably https://github.com/microsoft/TypeScript/pull/55479#issuecomment-1692139435 is relevant

> Unfortunately, Microsoft fired so many of its translators this year that we don't have budget for fixing anything but critical mistranslations. 💀 It might be possible to switch over to community translations, although I'd have to learn whether that would be possible.

**Comment by fullmooooon** [comment]
> Probably [#55479 (comment)](https://github.com/microsoft/TypeScript/pull/55479#issuecomment-1692139435) is relevant
> 
> > Unfortunately, Microsoft fired so many of its translators this year that we don't have budget for fixing anything but critical mistranslations. 💀 It might be possible to switch over to community translations, although I'd have to learn whether that would be possible.

As a matter of fact, there was no translation, and I had to code anyscript in typescript to enjoy the convenience of type prompts.
Someone has finished the translation, and no one wants to update it to the website. Maybe the owner of the website doesn't care.

**Comment by fatcerberus** [comment]
> Maybe the owner of the website doesn't care.

See https://github.com/microsoft/TypeScript-Website/issues/2804 - the localizations are no longer being officially maintained.

**Comment by RyanCavanaugh** [comment]
Please understand that not having the resources to do something isn't the same as not caring about it.
