### ISSUE TITLE
Incorrect parameter names for literals in inlay hints

### ISSUE THREAD

**Issue by Ilyat1337** [microsoft/TypeScript#56098]
### 🔎 Search Terms

"parameter names", "inlay hints"

### 🕗 Version & Regression Information

- This changed between versions 5.1.6 and 5.2.2

### ⏯ Playground Link

No playground link - inlay hints are not shown there

### 💻 Code

```ts
function myFunc(p1: number, p2: number) {}
let arg1: number = 1
myFunc(arg1, 2)
```

### 🙁 Actual behavior

```ts
function myFunc(p1: number, p2: number) {}
let arg1: number = 1
myFunc(arg1, /* p1 */ 2)
```

### 🙂 Expected behavior

```ts
function myFunc(p1: number, p2: number) {}
let arg1: number = 1
myFunc(arg1, /* p2 */ 2)
```

### Additional information about the issue

For inlay hints to work only for literals you need to set `typescript.inlayHints.parameterNames.enabled` setting to `literals`.

**Comment by Ilyat1337** [comment]
Duplicate

**Comment by fatcerberus** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/55866
