### ISSUE TITLE
`String#match` and `String#search` types are too lenient (should not accept string as `regexp` argument)

### ISSUE THREAD

**Issue by lionel-rowe** [microsoft/TypeScript#56109]
### ⚙ Compilation target

ES5+

### ⚙ Library

ES5/any

### Missing / Incorrect Definition

Current definitions, which allow `string | RegExp` as the parameter named `regexp`:

https://github.com/microsoft/TypeScript/blob/e38944d8b8b5f6039e18b36574720ce337a5be1b/src/lib/es5.d.ts#L434-L438

https://github.com/microsoft/TypeScript/blob/e38944d8b8b5f6039e18b36574720ce337a5be1b/src/lib/es5.d.ts#L454-L458

### Sample Code

The following results would be unexpected if `string` was truly supported:

```ts
'$abc'.search('$') // 4
'$abc'.match('$') // ['', index: 4, input: '$abc', groups: undefined]
'abc['.search('[') // Uncaught SyntaxError: Invalid regular expression: /[/: Unterminated character class
'abc['.match('[') // Uncaught SyntaxError: Invalid regular expression: /[/: Unterminated character class
```

Strings are only supported insofar as a regex can be constructed from them (i.e. they're only marginally supported because JS is weakly typed). So `'$abc'.search('$')` is equivalent to `'$abc'.search(/$/)`, not `'$abc'.indexOf('$')` or `'$abc'.search(/\$/)`.

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search

> [regexp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search#regexp)
A regular expression object, or any object that has a [Symbol.search](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/search) method.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match

> [regexp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#regexp)
A regular expression object, or any object that has a [Symbol.match](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/match) method.

https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.search

> 4. Let rx be ? [RegExpCreate](https://tc39.es/ecma262/multipage/text-processing.html#sec-regexpcreate)(regexp, undefined).

https://tc39.es/ecma262/multipage/text-processing.html#sec-string.prototype.match

> 4. Let rx be ? [RegExpCreate](https://tc39.es/ecma262/multipage/text-processing.html#sec-regexpcreate)(regexp, undefined).

**Comment by MartinJohns** [comment]
Related: #47310

`matchAll` explicitly does not support `string`.

**Comment by RyanCavanaugh** [comment]
I think we can take a PR and assess what the breaks look like

**Comment by RyanCavanaugh** [comment]
PR turned up way too many breaks in code that is actually fine by inspection

**Comment by lionel-rowe** [comment]
> PR turned up way too many breaks in code that is actually fine by inspection

@RyanCavanaugh Would deprecating the `regexp: string` signature work as an alternative? My intuition is that top-400 codebases aren't very representative in terms of code quality, and a broader search would turn up a lot more problematic uses. The motivation is more about helping learners, junior devs, and less well-resourced projects.

Some examples of confusion in the wild:
* [W3schools](https://www.w3schools.com/jsref/jsref_search.asp) starts by giving examples of "searching using a string" and "searching using a regular expression" as if they're functionally different. You have to scroll halfway down the page to see the disclaimer _If the search value is a string, it is converted to a regular expression_.
* Many, many examples of articles on the site [dev.to](https://dev.to/) ([1](https://dev.to/zak100/javascript-searching-a-string-containing-parenthesis-3pij), [2](https://dev.to/ayabouchiha/all-js-string-methods-in-one-post-4h23), [3](https://dev.to/urstrulyvishwak/javascript-string-search-methods-9hf), [4](https://dev.to/femi_dev/common-built-in-string-methods-in-javascript-lo7)), a blogging site popular with beginner web devs. It seems like only every few days someone publishes a "string methods you need to know" listicle that uses an example with a string param and fails to mention the gotcha.

Obviously deprecating it wouldn't instantly clear up this confusion, but at least it would give a useful hint if intellisense complained at this usage.

In terms of its impact as a security sink, the obvious examples are uncaught runtime errors and ReDoS attacks, but it's not too hard to contrive an example where it could open the door to XSS attacks or similar:

```js
function getOutputHtml(qps: URLSearchParams): string {
    const text = qps.get('text')
    const query = qps.get('query')
    
    if (!text) return '<span class="error">No text supplied</span>'
    if (!query) return '<span class="error">No query supplied</span>'

    // failed attempt to guard against XSS
    if (query.includes('<')) return '<span class="error">Query cannot include &lt;</span>'

    return text.match(query)?.[0] ?? '<span class="warn">Query not found in text</span>'
}
```

In this example, a malicious user who can control both `text` and `query` can easily craft a payload such as the following: 

```js
{
    "text": "abcd <img src=x onerror=alert(1)>",
    "query": "abcd \\x3cimg src=x onerror=alert\\(1\\)>"
}
```

The issue would still exist if explicitly constructing a regex from the user input, but it's a lot easier to catch issues during linting or code review if there's only one such sink for creating regexes, namely the `RegExp` constructor.

**Comment by RyanCavanaugh** [comment]
Unlikely; people treat all new warnings of any form as if they are hard breaking changes.

You can add overloads yourself (in usercode) that would cause these to be marked deprecated if you'd like, though.

**Comment by lionel-rowe** [comment]
> Unlikely; people treat all new warnings of any form, including deprecations, as if they are hard breaking changes.
> 
> You can add overloads yourself (in usercode) that would cause these to be marked deprecated if you'd like, though.

Fair enough. I guess `no-implicit-regexp` could be a good candidate for a new rule in eslint etc.

I'll still submit a docs-only PR at some time as I think the current wording "A variable name or string literal containing the regular expression pattern and flags" is super confusing.
