### ISSUE TITLE
New Website Logo: صنایع فناوری طراحان بهینه

### ISSUE THREAD

**Issue by MasoudBimar** [Microsoft/TypeScript#5610]
Please fill the following out:

- Name: صنایع فناوری طراحان بهینه
- Homepage url: http://tbcom.ir
- Brand Guidelines/Licensing: http://www.tbcom.ir/about.aspx?id=1
- Logo: http://i.imgur.com/OVODdRg.gif

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
@MasoudBimar can you provide the logo in png format
