### ISSUE TITLE
A part of JSDoc for TypedArray toSorted is wrong.

### ISSUE THREAD

**Issue by noshiro-pf** [microsoft/TypeScript#56119]
### ⚙ Compilation target

ES2015

### ⚙ Library

esnext

### Missing / Incorrect Definition

The description for TypedArray `toSorted` should be:

```diff
- If omitted, the elements are sorted in ascending, ASCII character order.
+ If omitted, the elements are sorted in ascending order.
```

### Sample Code

```TypeScript
(omitted)
```

**Comment by jeswinsimon** [comment]
@RyanCavanaugh I have raised a PR for updating TypedArray sort function definition here https://github.com/microsoft/TypeScript/pull/56148
