### ISSUE TITLE
Check for optional property expanded with spread operator is skipped

### ISSUE THREAD

**Issue by 085astatine** [microsoft/TypeScript#56114]
### 🔎 Search Terms

"spread operator", "optional property"

### 🕗 Version & Regression Information

- This is the behavior in every version in Playground.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCJzHZBvAUMg5GAe2IC5kBnMKUAcwG59CAjOKC62kR3AX1y5QkWIhQB5AA5hgxEHAA26TDmYES5KjXpNCyNlAD8nbTyYDcAekvIAwnEooAjBQCiUKMShWbAPmQACp6S0GAAnsgA5AaRyMCUyAC28ZT0cSDI4SFR2PpwAF7GWtx0yAA+yACuIAAmEDCgEDUMRKQmJS18sSyVYMhQEACOlcADNemZYdmRynCRAHS4CHLUyABuipUQLmgYWAC8qnoaFJEAYuLikQA0asjzD9hs+RQARABC7K98t3xMPnYHCgAEwUAByxGQ7k8UGQhnhSxWfQ2Ci2oOQUhkckUs2QhzwxzaUTOpBudwe8yeBTenyg31+-2sgMcyAAzG4PF4Af4ACpTFCRXInYo6PIvEVmZBdOIJEDEPoOVJ0eQsBQoMCQrICzGyeRKPYLbkYlgAKwgCD6CmAIkUSTgETkCgilBCCGAMAiAGs5QB3DKSYKhYAQSjXZBwWpRZ6xGrEEPIOV9CAAD3ifVAk2mOux+swhuWIFWKK27Ix0l1OL2eKOhGF51Jtz0z1OtLJf2YQA

### 💻 Code

```ts
interface Data {
    foo: string;
    bar: string;
}

interface OptionalData {
    foo: string;
    bar?: string;
}

// Case 1: Error
// > Property 'bar' is missing in type '{ baz?: string | undefined; foo: string; }' but required in type 'Data'.
const value1: Data = {
    foo: 'FOO',
    ...{baz: "Bar"},
};

// Case 2: No Error ???
const value2: OptionalData = {
    foo: 'Foo',
    ...{baz: "Bar"},
};

// Case 3: Error
// > Type '{ foo: string; baz: string; }' is not assignable to type 'OptionalData'.
// > Object literal may only specify known properties, and 'baz' does not exist in type 'OptionalData'.
const value3: OptionalData = {
    foo: 'Foo',
    baz: 'Bar',
};
```

### 🙁 Actual behavior

In all cases, `bar` is misspelled as `baz`

In cases 1 and 3, typos can be detected as errors.
However, in case 2, the compilation succeeds without any errors.

### 🙂 Expected behavior

In all cases, typos can be detected as errors.

### Additional information about the issue

I found this bug when I was writing the following code with `exactOptionalPropertyTypes` set to true.

```ts
return {
    foo,
    ...(bar !== undefined ? { bar } : {}),
};
```

**Comment by fatcerberus** [comment]
The Excess Property Check[^1] is not (currently) done for spreads.  See https://github.com/microsoft/TypeScript/issues/39998.

[^1]: Note that, in general, EPC is primarily designed as a lint check and is intentionally not comprehensive.
