### ISSUE TITLE
Differentiate between interfaces and classes in generics and other types

### ISSUE THREAD

**Issue by Will-at-FreedomDev** [microsoft/TypeScript#56126]
### 🔍 Search Terms

"how to type for a class instance", "don't allow interface type for class", "class vs interface types", "class vs interface generics"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I'd like to be able to constrain a generic type as an interface and not as a class. I don't think that "interface" types should ever have been able to be set onto a class type, but here we are and changing that behavior would lead to breaking changes unfortunately (tbh, this is the better solution in my mind). Like this should not have been possible to begin with: https://www.typescriptlang.org/play?#code/MYGwhgzhAECyCeBhcVoG8CwAoa0AOATgPZ4CmBALvAFzQQUECWAdgOYDc22uwRz9BAK7AKRAgApCJclVoCWrAJTpuuaBQAWjCADopZSvGgBefMQNVOOaAF9sdrNl78K0ZkQoJkkCLS8oYU0xrfRkaaAAiAEkAcgBbaDBoADMwAGtyHQj7KycNUmA08XdPJADFXKxkwWYRRj5oYHzC6HFtABUtCH8fPzKfZWDcRmTWjq6e1BZ6MFrSIlHJiEHVHj4IIhBSHRAiVnEIgBlhNMYQeAAaaEZXbSyK1RtoUhAIUhVrNf5N7d39iIActIru0AMrQAAmRFIEGYMVcaXcAHd1PlISNkuRSHMdNAotANGAAG7vUQE4nvJIAKXBQmYFEYcXeTQKaWuzGgcSMYLMRAAVgUKPcrLgHA5sOIADztZ4ADwo2IhMCWAD5xLLaO1lMYVR8eM0irKHlgbIpih4lhUgA

But at least being able to add some kind of generic constraint, new type, new syntax, etc. to the TypeScript language should be feasible. 

It could be as simple as `myFunction<T is class>` or `myFunction<T is interface>` - I don't really mind how it gets implemented as long as something makes it work.

### 📃 Motivating Example

API responses will never be class instances and should never be typed as classes.

There are specific use-cases where a class type is necessary over an interface type (like for Rxweb form decorators) and developers still accidentally use interface types instead of classes as a generic type argument. 

Here is an Angular Material issue that was fixed that could have been avoided if interfaces != classes in TS :/ https://github.com/angular/components/pull/26571

### 💻 Use Cases

1. What do you want to use this for? See motivating examples.
2. What shortcomings exist with current approaches? Not possible to do this currently and causes unnecessary attention in PRs and inefficient developers as they try to figure out a problem when using an interface vs a class and vice versa.
3. What workarounds are you using in the meantime? PRs.

**Comment by fatcerberus** [comment]
> API responses will **never be class instances** and should **always be typed as classes**.

> There are specific use-cases where **a class type is necessary** over an interface type (like for Rxweb form decorators) and developers still **accidentally use class types** instead of interfaces as a generic type argument.

These statements seem self-contradictory?

**Comment by fatcerberus** [comment]
I want to note that your proposal doesn't solve this very related issue:

https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8CwAoa0AOAne2AprgC4CeAXNBCbgJYB2A5gNwYZbDwM24CuwEvFwAKPAWLkqvRkwCUKDlmgkAFnQgA6cUVJloAXhz5d5NpmgBfDNfQZQkGACEwuRRZ2TK1WrPNKuHloBIVFPPWlfZgU0Cyw1DW0TL0NjCT1zLFtbe24aaAZ4EgR4KhLUhkIAd2gXUQAiAEkAcgBbaDBoADMwAGtiTXq5f3RgVUJgXpFC4sRh9nQuvgZBOm5oMYne6BENABV1CBKyufcsOi6d-cPyxhowFcJ4S5KYpU48+BBCTRB4JhE9QAMgJenQQGQADTQOgkGFaIaZKzQQggCCEM7KQIQL4-P4A+oAOQk0L2AGVoAATeCECAMZpw3qFGpqDGUi5dYiER6aaCNaCqMAANwxQgFwoxnQAUhT+AwSHRWhjNpMYQxoK19OS0gArCYkQbzCzZBYiAA8exRAA8SNzKTASgA+ERWqh7BQGR2YlVTK1GyxyaZFV7mIA

What you really want here is nominal typing, and you can already get that by adding a private property to them.  You don't have to actually use it, and it can even have the same name across classes.

```ts
class Foo {
  private $nominal!: never;
  property: string;

  constructor(property: string) {
    this.property = property;
  }
}

class Bar {
  private $nominal!: never;
  property: string;

  constructor(property: string) {
    this.property = property;
  }
}

const notFoo: Foo = new Bar("I'm a faker.");  // now this is an error
```

**Comment by willherr** [comment]
> Thing is, non-public members aside, as far as typescript is concerned, a class is just a bunch of sugar. You get a constructor interface, an instance interface, and the concrete values to implement them—same thing with or without classes. So I guess the question is what problem are you really trying to guard against? Is this an XY problem?
> 
> You can contrive a parameter type that would forbid constructors, but that doesn't really help you because the instance type is separate from the class/constructor and is essentially just an interface. It doesn't even know itself whether it's the product of a constructor, hence why this is valid:
> 
> ```typescript
> class X{ y!: number; }
> var inst: X = {y: 3};
> ```

Very specifically, the problem I have is this: We have a base class that is used as the definition of a service that interfaces with an API's rest actions. There is a set of rest actions for each entity. Each entity has its own implementation of this base class and the base class is given a constructor to type the results of these API service methods. Now we know that the results of a JSON response will not be a class instance. They will be interfaces, so developers must provide an interface to the generic.

The first issue is that in my mind, in your example where you assigned that plain JS object to a type where it says it is a class is buggy and leads to confusion (think instanceof checks)

Secondly, the library we use requires classes to instantiate form models in memory, which receive validators through the use of decorators via the class's properties (NOT the interface). This is where a lot of people have a hard time and need to learn the hard way that a class != interface.

This is why I would like a way to say at compile time with TS, that a thing is or is not a class.

**Comment by fatcerberus** [comment]
While it can be argued that a plain object literal being assignable to a class type is a footgun (and I wouldn’t disagree, though again, easy workaround is just add a private prop to the class), the reverse situation is definitely by design: an interface merely describes the capabilities of a type.  I’d consider it *very* strange if someone’s API said it took an `IFooable` and then wouldn’t accept the value I gave it just because it originated from a class constructor.

That’s why I suspect this is an X/Y problem - you don’t really need to distinguish class and interface types as such (because that wouldn’t actually solve the underlying problem, as I showed above), you just need class types to be treated nominally by the compiler such that the only thing assignable to `FooClass` is something returned by `new FooClass()` (or a subclass)

**Comment by willherr** [comment]
It may be a fool's errand to make this comparison, but in C# we can constrain a type to be either a class type or a struct type. Plain JS objects I can see being more struct-like in this comparison (not an exact comparison), so there is value imo where we could make this distinction in TS.

I suppose if it's just a philosophy that TS decided to take, that's fine. I'd definitely like to find out via a plugin or linter of some kind to get this functionality anyway since this is a real problem that exists (if it can't come from the compiler).

**Comment by Will-at-FreedomDev** [comment]
> I’m not sure why adding a private property to your classes isn’t a workable solution, as it solves this issue completely - is the problem that you don’t control the classes in question?

This is not a design/compile-time enforcement. It's cool that this "makes it work", but my developers now need to instead of just using an interface generic on the parent class, we just moved the issue to remembering to put a private property onto every class. I guess I don't see how that makes it a better developer experience. This private property is completely a (not great) workaround which requires manual human intervention.

As the owner of a parent class, I want to type my parent class in the way that it needs to be used, not hope that developers put a "magic private property" (that is how everyone will see it) on every entity class. Or now instead of reviewing a PR that devs didn't use a class type in the generic, now I just need to look for this private property on all the classes. This just moves the problem and doesn't address it at an architectural level. 

However, as stated I'm good with finding a plugin to automatically do some of this, so if that means automatically adding a private property hack to every class, I suppose that works as a design time solution.

> It's true that you can't go in the other direction and enforce that something isn't a class instance, but I don't see why you'd want to.

I think the problem comes from developers with experience in other typed languages. When something is typed as `X`, you expect it to be `X` (let's ignore the fact that JS is running in the background and yes I could type everything perfect and `X` could still be _whatever_). So in this flow, it makes a lot of sense why you would want to enforce that something isn't a class instance: 
1. When a library requires a class instance (in this case it is grabbing decorators off properties - Angular heavily makes use of TS decorators. Maybe a different solution for me would be to allow decorators on interface but that seemed like a bigger "no way that's going to happen 🙂"). 
2. A developer typed the result of an API response as a class type but never new-ed it up. Believe it or not, there are developers with little to a few years of experience doing this multiple times. I don't blame them.
3. The developer then passed this plain object which now looks like a class type into said library, which brings on a lot of confusion as now it throws up errors or odd behaviors.
4. Now I have to explain to developers that once again they used a class type as a generic and "no, TS does not have a way for me to fix that for you." 
   a. If there was a way for me to fix it that didn't require developers to also remember to put a magic private property on classes (or something else since it sounds like this doesn't really address that problem) I'd love to hear it. It's got to be some kind of constraint on the parent class itself though and not moving the burden of development to another place in source control.

**Comment by fatcerberus** [comment]
> If there was a way for me to fix it that didn't require developers to also remember to put a magic private property on classes (or something else since it sounds like this doesn't really address that problem) I'd love to hear it.

To be clear, in the case of a deep class hierarchy, you don't need the private property on *every single* child class - just the top-level base class.  Then anything that `extends` that class will be considered to have the property, but not unrelated classes or POJO types.

**Comment by fatcerberus** [comment]
> I think the problem comes from developers with experience in other typed languages. When something is typed as X, you expect it to be X

Yeah, this is just an impedence mismatch between structural and nominal typing that you'll have to accept.  If you come in expecting the type system to work like it does in e.g. C# or Java or whatever, you're going to have a bad time.  TS's type system was designed primarily to model duck typing in JS so this is just the way things are.

**Comment by fatcerberus** [comment]
btw you might be interested in https://github.com/microsoft/TypeScript/issues/202

**Comment by Will-at-FreedomDev** [comment]
Hmm, okay. I think you are right that I'm really wanting what is proposed in #202 (or some version of that). It seems like the problem I have goes beyond this specific proposal. I think my real problem is that class X can equal an interface Y (according to TS's structural typing system) and there is a different solution that maybe TS won't be able to solve (or want to solve). 

I appreciate the discussion!
