### ISSUE TITLE
Publish 1.7.x to npm

### ISSUE THREAD

**Issue by Artazor** [Microsoft/TypeScript#5612]
In this repo package.json already points to 1.8, however, npm version still reports 1.6.2.
The question is: where is 1.7 and will it be published to npm?

**Comment by shadeglare** [comment]
:thumbsup:

**Comment by mhegazy** [comment]
We like to stabilize releases for a couple of weeks before publishing them to npm. the release is in the final stabilization phases, so should be out shortly.
