### ISSUE TITLE
No overload matches this call.   Overload 1 of 4, '(iterable?: Iterable<readonly [unknown, unknown]> | null | undefined): Map<unknown, unknown>'

### ISSUE THREAD

**Issue by albertkao9** [microsoft/TypeScript#56120]
### 🔎 Search Terms

"No overload matches this call" '(iterable?: Iterable<readonly [unknown, unknown]> | null | undefined): Map<unknown, unknown>'

### 🕗 Version & Regression Information
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about this.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlmADgV1gXhmApgdxgWQENEAKAbRjIHJjEAbLKgGioCcsATKgXScqoBGhMMMLMqATyx06IHDxjcAlAG4AsAChseIqTIA6QwhRRu+gLbESWMFFYSYaAHwwbdifvYA3LKwhYSJSCVIA

### 💻 Code

```ts
const input = new Map([ ['apple','red'], ['banana','yellow'] ]);
new Map([...input].map(entry => entry.reverse()));
```

### 🙁 Actual behavior

compile error:
No overload matches this call.
  Overload 1 of 4, '(iterable?: Iterable<readonly [unknown, unknown]> | null | undefined): Map<unknown, unknown>', gave the following error.
    Argument of type 'string[][]' is not assignable to parameter of type 'Iterable<readonly [unknown, unknown]>'.
      The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
        Type 'IteratorResult<string[], any>' is not assignable to type 'IteratorResult<readonly [unknown, unknown], any>'.
          Type 'IteratorYieldResult<string[]>' is not assignable to type 'IteratorResult<readonly [unknown, unknown], any>'.
            Type 'IteratorYieldResult<string[]>' is not assignable to type 'IteratorYieldResult<readonly [unknown, unknown]>'.
              Type 'string[]' is not assignable to type 'readonly [unknown, unknown]'.
                Target requires 2 element(s) but source may have fewer.
  Overload 2 of 4, '(entries?: readonly (readonly [unknown, unknown])[] | null | undefined): Map<unknown, unknown>', gave the following error.
    Argument of type 'string[][]' is not assignable to parameter of type 'readonly (readonly [unknown, unknown])[]'.
      Type 'string[]' is not assignable to type 'readonly [unknown, unknown]'.

### 🙂 Expected behavior

No compile error

### Additional information about the issue

This JavaScript code has no compile error at https://developer.mozilla.org/en-US/play .
i.e. It works.

**Comment by nmain** [comment]
So you want `.reverse()` to change the type `[T, U]` into `[U, T]`?  I can't find a specific issue for this, but this is closely related to things like https://github.com/microsoft/TypeScript/issues/44309 and the other tickets linked from that.

**Comment by RyanCavanaugh** [comment]
There's no currently type constructor that reflects the type of `reverse()`, so we don't "know" how many elements are in it

**Comment by sukima** [comment]
I ran into this error for a different reason. It has to do that TS expects the constructor for Map to take an Array when in fact per the spec it should be an Iterable. [this line](https://github.com/microsoft/TypeScript/blob/main/src/lib/es2015.collection.d.ts#L32) I think should be:

```diff
 
 interface MapConstructor {
     new (): Map<any, any>;
-    new <K, V>(entries?: readonly (readonly [K, V])[] | null): Map<K, V>;
+    new <K, V>(entries?: readonly (Iteratable<readonly [K, V])> | null): Map<K, V>;
     readonly prototype: Map<any, any>;
 }
 declare var Map: MapConstructor;
```
