### ISSUE TITLE
TypeScript reports a cycle when using a function with an Expression as body

### ISSUE THREAD

**Issue by cpojer** [microsoft/TypeScript#56121]
### 🔎 Search Terms

initializer cycle implicit any

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAEg9gdwDYFEBOa5oMIEMlIBGuAxgNZQC8UAFAM5wCuAdgCYCSrAXFM4wLaEIaADRRhmNDxZlmiZgEoqAPigA3OAEtWAbgBQezc2DCAZqWjxkAeTDBNcZnSgBvPVA9RHYJLhASsAH4eK1QMLDwCYnIoAB8oFlYIUyMIXT0AXwMSXzpnUNd3TxJHOmA0RhJgLBowRkIkTRIoNAhcVkckEC87BycQxCRbe1KlFyzPL2YSCBpmXH4IHgByFiQ4cmWxU2YeGiVKVQ1tMaLJkqc4JAgAOnWAczmFiG3FfUmsrL0LsqgjMtw02g1GYEAQsEGNDcHm8vn84SktAOqn+wEBMxujhmNFWzHWmzE+xUrgyCkyCn02VKwD+TjRQIATFReGCIcgoUVYX4AoiiYdCpNWsBGGhmLSAYzMUCcWsNmQtkjieMKUVPirvtTxfSZgBmZmg8GhDkw5g+bkIvbI9RaVha9EQHVS7G4-HywlW5Xkyk-Gmo+0AFn1rKN0KmZvhkktSrOdqB-qdsxdcoVfNUyveUDVOiAA

### 💻 Code

```ts
type HowlErrorCallback = (soundId: number, error: unknown) => void;

interface HowlOptions {
    onplayerror?: HowlErrorCallback | undefined;
}

class Howl {
    constructor(public readonly options: HowlOptions) {}
    once(name: 'unlock', fn: () => void) {
      console.log(name, fn);
    }
}

const instance = new Howl({
  onplayerror: () => instance.once('unlock', () => {})
});


const instance2 = new Howl({
  onplayerror: () => {
    return instance2.once('unlock', () => {});
  }
});

const instance3 = new Howl({
  onplayerror: () => void instance3.once('unlock', () => {})
});

const instance4 = new Howl({
  onplayerror: () => {
    instance4.once('unlock', () => {});
  }
});
```

### 🙁 Actual behavior

Variants 1-3 report an error, variant 4 does not.

### 🙂 Expected behavior

Neither of the variants reports an error, or at least variant 3 (void) should not return an error.

### Additional information about the issue

This seems like a minor bug with a proposed fix in https://github.com/Andarist/TypeScript/commit/66a7638405f771e86163af1f31cd73ea666c10b0 by @Andarist

**Comment by RyanCavanaugh** [comment]
These are fairly evident cycles.
