### ISSUE TITLE
Omit not providing intellisense on what can be omitted from type

### ISSUE THREAD

**Issue by Daggron** [microsoft/TypeScript#56135]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Description
- When I am using Omit it takes two parameters
   1. The object type from which the keys are to be omitted
   2. The keys which we want to remove.

- Now when I try to do this I get no intellisense / autocompletion that hey these are the keys which are present in the Object type.

### Reproduction

This can be reproduce in the [this ts playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8BQUoEMCqATgDYBcUiBAlgHYDmA3FlAEYCuxZFNDT8A9gFsIwABbcyzPnyIQc1RgF8MGAPQrYBEFGB8oYAgnhQAxsGJQA1OTA5j0GtpHR4EY32oATPTgI4BUAEdWPmAEDFBIKAB5AUpgUI8YcGhUGLiAHjhEABooAHI8gD4gA)

Screen shot for reference
![Screenshot 2023-10-17 at 6 24 35 PM](https://github.com/microsoft/TypeScript/assets/41940582/7f612e46-afd2-4524-b093-f4a5ed551abe)

### Solution

```ts

type BetterOmit<T extends Record<any, any>, K extends keyof T> = {
    [P in T as P extends K ? never : P]: T[P]
}
```

All we need to do is add extends clause to the second Param which will give intellisense.

I can add this to the repo but need suggestion or reasoning behind the current implementation

**Comment by nmain** [comment]
See https://github.com/microsoft/TypeScript/issues/30825, https://github.com/microsoft/TypeScript/issues/54451, https://github.com/microsoft/TypeScript/issues/53169

**Comment by RyanCavanaugh** [comment]
Omit isn't constrained on `K` (this is intentional), so there's no information to provide that hint from

**Comment by dnistreanu-diffco** [comment]
This should be a bug. Please reopen and fix it. It makes no sense to have no intelligence on Omit.

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/wiki/FAQ#add-a-key-constraint-to-omit

https://github.com/microsoft/TypeScript/wiki/FAQ#this-is-closed-but-should-be-open-or-vice-versa
