### ISSUE TITLE
ts(2366) CFA can't tell that switch(x % k) is exhaustive

### ISSUE THREAD

**Issue by dan-mcdonald** [microsoft/TypeScript#56137]
### 🔍 Search Terms

The most related issue I found was #51199. Here is some code I wrote

```typescript
type ObjectEntry = {
  y: number;
  x: number;
  tileIndex: number;
  flags: number;
}

export class PPU {
  _oam = new Array<ObjectEntry>(40).fill({y: 0, x: 0, tileIndex: 0, flags: 0});
  readOam(addr: number): number { // ERROR: Function lacks ending return statement and return type does not include 'undefined'. ts(2366)
    if (addr < 0 || addr >= 0xA0) {
      throw new Error(`Invalid OAM address ${addr}`);
    }
    const entry = this._oam[addr/4];
    switch (addr % 4) {
      case 0: return entry.y;
      case 1: return entry.x;
      case 2: return entry.tileIndex;
      case 3: return entry.flags;
    }
  }
}
```
This is some code that I expected to compile without a problem. I thought that the switch was guaranteed to match because `addr % 4` can only be 0-3.  This is actually not true. addr = -0 would return undefined because -0 % 4 = -0. However I tried adding a `case -0:` and I tried `switch (Math.abs(addr) % 4) {`, either of which should prevent this odd case and typescript didn't fix it. 

More generally, as a user I wish the CFA could give some feedback about why it thinks the switch isn't exhaustive. Maybe there should be some way I could declare that I think the switch is exhaustive and Typescript can return an error if I'm wrong, e.g. a new keyword:

```
switch (addr % 4) exhaustive {
```

Would explain which cases are not handled if the CFA failed to prove it was exhaustive. Even if it explained its limitations e.g. "exhaustive switch over type number is unsupported" would be helpful. Now that I'm at the end of typing all this I realized I never considered infinity or NaN! 

Anyway, I was just opening this ticket as some real world feedback. If nothing seems feasible to implement, feel free to close it. Thanks for your work on TypeScript!

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

see above

### 📃 Motivating Example

see above

### 💻 Use Cases

1. What do you want to use this for?
Code like the above example
2. What shortcomings exist with current approaches?
I can't tell if I'm smarter than the CFA or if I'm forgetting something
3. What workarounds are you using in the meantime?
I would just add a `throw` before end of the function and I would never know how it could be reached at runtime.

**Comment by RyanCavanaugh** [comment]
`-5 % 2 == -1` as well.

This doesn't seem like a common-enough pattern to warrant new support for. Adding this line resolves the type error and handles any cases where a negative number ends up in your array.
```ts
    switch (addr % 4) {
      case 0: return entry.y;
      case 1: return entry.x;
      case 2: return entry.tileIndex;
      case 3: return entry.flags;
      default: throw "unexpected addr";
    }
```

**Comment by dan-mcdonald** [comment]
The case -5 should have been caught by the if check though. -0 is insidious because `addr < 0` evaluates to false. This is the kind of JS footgun that it would be nice if TypeScript could warn about. But I'll close the issue for now unless there is popular demand.

**Comment by fatcerberus** [comment]
Wait, doesn't `case 0` also match negative zero?  Since `0 === -0` is true (you need to induce a `SameValue` comparison to get them to be different, and I don't think `switch` does that)

**Comment by KarolS** [comment]
There are other corner cases, like fractions, infinities and NaNs.
