### ISSUE TITLE
Controlling sources URL in inlined source maps (sourceRoot)

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#5613]
When inlining/embedding a source map into files, TypeScript compiler seems to always generate local file names, instead of paths e.g. matching what would end up in `--outDir`. `tsc` does not accept a `sourceRoot`, and does not use `rootDir` for the denormalization.

Ideally, I would like to pass in a `sourceRoot` of `''` (empty string), so that all files end up with the complete path showing properly.

**Comment by mprobst** [comment]
In particular, these are the problems we're facing:

```
error TS5052: Option 'sourceRoot' cannot be specified without specifying option 'sourceMap'.
error TS5053: Option 'sourceRoot' cannot be specified with option 'inlineSourceMap'.
```

**Comment by mhegazy** [comment]
@sheetalkamat ran into this yesterday. she should have a fix for it.

**Comment by mhegazy** [comment]
@mprobst can you give `typescript@next` a try.

**Comment by mprobst** [comment]
@mhegazy: I'll be OOO next week, will look into this once I'm back.

Mohamed Hegazy <notifications@github.com> schrieb am Do., 12. Nov. 2015 um
13:31 Uhr:
