### ISSUE TITLE
Type checking and inference for optional function invocation (chaining)

### ISSUE THREAD

**Issue by vzakharov** [microsoft/TypeScript#56134]
### 🔍 Search Terms

optional function invocation, optional chaining

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I propose an enhancement to TypeScript's type inference mechanism in the context of optional function invocation. The idea is to allow TypeScript to automatically narrow down the type of a variable that could be either a function or a value of a different type, based on its usage in an optional function invocation. 

So, in a line like this:

```typescript
const value = valueOrFunction?.(context) ?? valueOrFunction;
```

..., assuming value is _some function type | other types_, the expression before the `??` operator will be inferred as the former and after it as the latter.

### 📃 Motivating Example

Consider a function that accepts a parameter which could be either a function or a value of a different type:

```typescript
function example<T, U>(valueOrFunction: ((context: T) => U) | U), context?: T) {
    const value = typeof valueOrFunction === 'function' ? valueOrFunction(context) : valueOrFunction;
    // value infers as U
}
```

With the proposed feature, TypeScript would automatically infer the type based on the usage, allowing you to write more concise and readable code:

```typescript
function example<T, U>(valueOrFunction: ((context: T) => U) | U), context?: T) {
    const value = valueOrFunction?.(context) ?? valueOrFunction;  // < after ??, valueOrFunction typeguards to U
    //                             ^ typeguards to (context: T) => U
    // value infers as U
}
```

Indeed, as using the `?.(` syntax is only possible on a function, a `typeof` check seems redundant here, so TypeScript could automatically infer that the expression before the `??` operator is a function. This would streamline the code and make it more readable, while also reducing the potential for errors due to manual type checking.

### 💻 Use Cases

_1. What do you want to use this for?_
This feature would be useful in scenarios where a function accepts a parameter that could be either a function or a value of a different type. It would allow developers to write more concise and readable code by eliminating the need for explicit type guards.

_2. What shortcomings exist with current approaches?_
It is too verbose.

_3. What workarounds are you using in the meantime?_
In the absence of this feature, developers have to resort to explicit type guards and conditional logic to handle variables that could be either a function or a value of a different type.

**Comment by jcalz** [comment]
The example is going to do bad things at runtime regardless of any change to TS's inference.  If `valueOrFunction` can be any non-nullish non-function, then `valueOrFunction?.(context)` will explode.  So if you call `example("abc")`, then at runtime you'd be trying to call the non-nullish `"abc"` as if it were a function.  This can't be fixed with the type system; optional chaining is a JS feature that TS does not control.  The only reasonable thing for TS to do here is issue an error that `valueOrFunction` is not callable.  Which is what it does already.  Is this a fundamental problem with your proposal or did you just use a problematic example?

**Comment by fatcerberus** [comment]
Thanks @jcalz.  I always forget `foo?.(bar)` is the syntax for an optional call.  When I see `foo?.(bar)` I instinctively read it as `foo?.bar` with extraneous parens so I didn't even realize why the example was problematic.

**Comment by MartinJohns** [comment]
Besides that, `U` can very well be a function as well, making this a very sketchy pattern.

**Comment by vzakharov** [comment]
> Besides that, `U` can very well be a function as well, making this a very sketchy pattern.

This would hold for the original kind of type checking as well, *this* is an issue with the example at least. (Replace `U` with `string` then.)

**Comment by MartinJohns** [comment]
I didn't mean your proposal, but the sketchy pattern "function returning value or value". You can't do this safely, because you can't differentiate between the two.

**Comment by vzakharov** [comment]
If we know for sure that U isn’t function (which we often do), this is a
very useful pattern that allows you to eg have default values either
specified literally or inferred/initialized from some context.

Вт, 17 окт. 2023 г. в 21:11, Martin Johns ***@***.***>:
