### ISSUE TITLE
Wrong assignability of class types from expressions with private fields 

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#56146]
### 🔎 Search Terms

class expression private fields assignability 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?target=99#code/GYVwdgxgLglg9mABAWwIYGsCmBhANqgZwIAoA3ALkTBGQCNMAnASkQG8BYAKER8QcyggGSCPiKJsHbrxkBiGABNEAXkSkA3FxkyCUVLAiIA5gICSC4nErYWU7fb4ChSOADp5CzdPsBfLbz9OQK4IBF1EUQIARhUUDBwxEiimELCoCNwCACZYtCw8QhIslM4uXAEImNUwTAB3DOziJnVEAHpWxAAVAGVEKAALGDB0Aj7B0ZhRuHQQzKjXEyhzYghkto6GcFhkTERGBjgGRAUYYGBGTDB00kYCeDAp4EQPIA)

### 💻 Code

```ts
function makeClass(v: number) {
    return class C{
        #id = v;
        static getId(o: C) {
            return o.#id;
        }
    }
}

const cls1 = makeClass(1)
const cls2 = makeClass(2)

let c1 = new cls2(); // TS thinks this is ok
cls1.getId(c1) // runtime error different versions of #id
```

### 🙁 Actual behavior

`c2` is assignable to `c1` even though they contain private fields that are different (even if they come from the same source code) 

### 🙂 Expected behavior

Instances of `cls2` should not be assignable to `cls1` since they have different versions of the private field. 

### Additional information about the issue

Found as I was exploring the consequences of https://github.com/microsoft/TypeScript/issues/56145

**Comment by fatcerberus** [comment]
I'm thinking this is probably a design limitation (i.e. nominally-typed properties are distinguished by source location or something), but yeah, ouch, that's unfortunate.

**Comment by RyanCavanaugh** [comment]
Yeah, there is zero concept of the kind of per-invocation tracking you'd need to handle this.

**Comment by jcalz** [comment]
Reminds me of #37469, where each invocation of a function spits out a new nominal type.
