### ISSUE TITLE
The printer/emitter module needs to support multiple Typescript formats

### ISSUE THREAD

**Issue by mananpancholi24** [microsoft/TypeScript#56141]
### 🔍 Search Terms

I have an AST on which I have applied some in-place transformations. I would like to save the transformed AST to a new Typescript source file. To generate the source text, I'm using `ts.createPrinter() --> ts.printNode()`. What I notice is that the saved file has changed much more than the transformations I applied. Additional changes are mainly formatting related, one instance being that all the single quotes in the original source file were converted to double quotes. Other changes include additional white-spaces for new lines.

It looks like today there is no way for us to configure the printer to not override the source formatting. I would like this to be configurable, so that the resulting file is adherent to the linting rules I've set for my project.

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The printer should respect the original formatting by default. In addition it can support custom formatting specification by the users.

### 📃 Motivating Example

The printer module now supports custom formatting specification. Previously the printer used to put all the string literals inside double quotes. While syntactically this was ok, the resulting code was not necessarily adherent to all kinds of linting rules. With this feature a user can specify the formatting and the printer will generate the final text according to the specification. If no specification was specified then it will use the original formatting.

### 💻 Use Cases

The printer module now supports custom formatting specification. Previously the printer used to put all the string literals inside double quotes. While syntactically this was ok, the resulting code was not necessarily adherent to all kinds of linting rules. With this feature a user can specify the formatting and the printer will generate the final text according to the specification. If no specification was specified then it will use the original formatting.

Current workaround is to run a linter manually after the new file is generated. Even after that there are a few places that need to be updated manually for a successful lint validation.

**Comment by RyanCavanaugh** [comment]
The emitter isn't geared to the kind of use case you're describing - its only real job is to produce "good enough" output either for later formatting (in LS scenarios) or JS emit where only semantic correctness is necessary.

I'd really recommend using `ts-morph` for this use case; [it's what we use](https://devblogs.microsoft.com/typescript/typescripts-migration-to-modules/) when doing in-place source transforms intended for continued author consumption.

**Comment by RyanCavanaugh** [comment]
@MartinJohns a wafer-thin request from me - please don't 👎 well-intentioned feature requests straight out of the gate; I think it creates an unwelcoming environment

**Comment by fatcerberus** [comment]
> wafer-thin

Oh crap, everybody run for the hills!

**Comment by mananpancholi24** [comment]
@RyanCavanaugh I was not aware of `ts-morph`, thanks for pointing me to that! I will look into it and hopefully it will do the trick! Appreciate your warm friendly note to guide me in the right direction instead of outright rejecting the request :)
