### ISSUE TITLE
Who is the copyright owner of this project?

### ISSUE THREAD

**Issue by g-e-r** [microsoft/TypeScript#56152]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

The LICENSE file says _"Licensor" shall mean the copyright owner or entity authorized by the copyright owner that is granting the License."_
 Typically there's a **Copyright (c) xxx** in the LICENSE file mentioning the copyright holder.

 The commit below (on Feb 2020) removed a reference to CLA granting permission to Microsoft (https://github.com/microsoft/TypeScript/commit/fcd55c21a1bf4670080630d3a6c00231e0d626a0).

 Is Microsoft Corporation still the "Licensor" of this project?

Thanks
Germano.

**Comment by RyanCavanaugh** [comment]
Yes, it's still Microsoft

**Comment by g-e-r** [comment]
Thanks!
