### ISSUE TITLE
tsc target did not work expectedly when compile ES2022 to ES2015

### ISSUE THREAD

**Issue by turtleinspace1** [microsoft/TypeScript#56160]
### 🔎 Search Terms

target  ES2022  ES2015

### 🕗 Version & Regression Information

TS 4.5

### 💻 Code

npx tsc --target es5 index.ts --outFile indexout.js

index.ts:
const arr = [1, 2, 3, 4, 5];
arr.at(1); // 2

### 🙁 Actual behavior

indexout.js:

const arr = [1, 2, 3, 4, 5];
arr.at(1); // 2

### 🙂 Expected behavior

Array.at is a new feature in ES2022
The target is ES5, the output js should not include Array.at
so the indexout.js can not work on the old browser.

**Comment by MartinJohns** [comment]
TypeScript will only downlevel newer syntax. If the function you're trying to call does not exist at your runtime it's your responsibility to polyfill it.

**Comment by turtleinspace1** [comment]
Thanks I understand
