### ISSUE TITLE
Types fail to resolve with `"moduleResolution": "NodeNext"`

### ISSUE THREAD

**Issue by aryzing** [microsoft/TypeScript#56167]
### 🔎 Search Terms

moduleResolution

types not resolving

library types not loading

nodeNext

jump to definitino

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because it's the opposite of an error: there are no errors. Incorrect types are allowed.

### 💻 Code

[Reproduction repo](https://github.com/aryzing/repro-ts-module-resolution-types-not-working).

### 🙁 Actual behavior

Invalid types are allowed when using `"moduleResolution": "NodeNext",`

The below video is from the reproduction repo linked above. It shows how errors are not detected when changing the module resolution.

<details>
<summary>Video types failing</summary>

[Screencast from 21-10-2023 14:28:49.webm](https://github.com/microsoft/TypeScript/assets/4924405/8111b241-acd1-4df2-a5f5-58b91eb1a79c)

</details>

### 🙂 Expected behavior

Invalid types should be caught and reported.

### Additional information about the issue

tsc Version 5.2.2

**Comment by fatcerberus** [comment]
Looks like the issue is with solid-js, not TypeScript:
https://arethetypeswrong.github.io/?p=solid-js%401.8.3

**Comment by aryzing** [comment]
Thanks @fatcerberus, that's a handy resource.
