### ISSUE TITLE
Throwing functions should return `never` type

### ISSUE THREAD

**Issue by senyai** [microsoft/TypeScript#56170]
### 🔍 Search Terms

noreturn, bottom type

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

```typescript
function f() {
    throw 42;
}
```
`f()` should have `never` return type instead of `void`.

```typescript
function c() {
    f();
    return 42;
}
```
`c()` should have `never` return type instead of `number`. `return 42;` should be marked as a line that never executes.

### 📃 Motivating Example

```typescript
function t() {throw new Error('Method not implemented.');}

readDirectory(): Thenable<[string, FileType][]> {
    throw new Error('Method not implemented.');
    // throw can't be replaced with `t();`, but it should be.
}
```
Related closed issues: #7538, #3076

### 💻 Use Cases

just imagine

**Comment by MartinJohns** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/16608#issuecomment-309327984.

**Comment by senyai** [comment]
Wait! Typescript is already one third of a way there!

```typescript
function f(): never {
    throw 42;
}

function c() {
    f()
    return 3;
}
```
When `f()` is marked `never` explicitly, `return 3;` is grayed out.

**Comment by senyai** [comment]
thanks @MartinJohns

**Comment by fatcerberus** [comment]
> When `f()` is marked `never` explicitly, `return 3;` is grayed out.

That's intentional - it's a known limitation that a `never` return type must be explicitly marked in the source text to affect control flow analysis.  Even if TypeScript could infer `never` returns automatically, it wouldn't affect unreachable code detection so would be of questionable utility.
