### ISSUE TITLE
Why the type compuation is different between this two ways?

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#56178]
### 🔎 Search Terms

union type

### 🕗 Version & Regression Information

version 5.2.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKg9gQQE5IIYgDwwHxQLyxQQAewEAdgCYDOUq5IUA-LANoC6UAXFORAG4QkAKGGhIUANL4oARigAfKACZR46JIQz4yNJknYx4DQgD6M6STJVa9Ri0kduvAUKA

### 💻 Code

```ts
// Your code here
type ToArray<T> = T extends any ? T[] : never

type K = 1 | 2

type KA = ToArray<K>
type KA_ = K extends any ? K[] : never
```

### 🙁 Actual behavior

The Type KA is `1[] | 2[]`, but the Type KA_ is (1 | 2)[], why this two type is not the same? i just inlined the `ToArray` in KA_ definition.

### 🙂 Expected behavior

The Type KA and KA_ should be the same definition.

**Comment by fatcerberus** [comment]
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types
