### ISSUE TITLE
Nullish coalescing operator: fallback value is not type checked when left-hand value is array element

### ISSUE THREAD

**Issue by taylorkline** [microsoft/TypeScript#56188]
### 🔎 Search Terms

`nullish coalescing operator`, `??`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about nullish coalescing operator

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231023#code/MYewdgzgLgBNBOBLMBzAgveBDAngLjiiVQG0BdGAXhnIG4AoUSWAExAFMIA5EKAUUwh4aCHwAeAB3bAo7FgQTIUVQsXSZcJAAwUA-LpgBGAEwBmBk2gx2g+BADCQ+NKgAbfKqUrFqDNhzaep6+GgE6MAQm5ozgVliuECAC8EIOTi7uCkRe1D7q-oEwAD5FRma0QA

### 💻 Code

```ts
const stringArray: string[] = [];
const doesNotErrorAsExpected: string = stringArray[0] ?? 123;
const errorsCorrectly: string = stringArray[0] ? stringArray[0] : 123;
const alsoErrorsCorrectly: string = stringArray[0] || 123;
```

### 🙁 Actual behavior

Like the ternary and logical OR operator, `const doesNotErrorAsExpected: string = stringArray[0] ?? 123` should error with message "Type 'number' is not assignable to type 'string'."

### 🙂 Expected behavior

`const doesNotErrorAsExpected: string = stringArray[0] ?? 123` is permitted with no type errors.

**Comment by RyanCavanaugh** [comment]
You'll need to turn on `noUncheckedIndexedAccess`, since from the checker's POV with that option off, the LHS is never nullish

**Comment by taylorkline** [comment]
Thanks, why is that different than with the ternary?
