### ISSUE TITLE
UnionToIntersection not returning an object type

### ISSUE THREAD

**Issue by cocacola-lover** [microsoft/TypeScript#56185]
### 🔎 Search Terms

UnionToIntersection Spread types may only be created from object types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about spread types.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231023#code/JYWwDg9gTgLgBDAnmApnA3nAqgO2BHAFQgEkcYUoBnFAYxnxzgF84AzKCEOAcgFcGAG2BIAtElRUeAKGls+OeozgKRKAPIAjAFZ0YVADyE4KAB4UcAEypwIOvQG0AugD4AFADovd3fRsAuOEIASgxpODgoFBg+KCZ0Lw83LV8YDwBDKipgAHMcN3RmABo4RJ89KlDM7DwCYjIKaj1GIwccPhBNSldg5mlmIA

### 💻 Code

```ts
// Your code here
import type { UnionToIntersection } from 'utility-types'

function uniteObjects<T extends object[]>(...objects : T) {
  return {...(Object.assign({}, ...objects) as UnionToIntersection<T[number]>)}
}
```

### 🙁 Actual behavior

Encountered error : Spread types may only be created from object types.(2698).

### 🙂 Expected behavior

Expected to work without errors.

**Comment by MartinJohns** [comment]
FYI: https://github.com/microsoft/TypeScript/issues/43077#issuecomment-790758767

> We don't really support uses of `UnionToIntersection`; this operation is ill-defined.

**Comment by RyanCavanaugh** [comment]
The difference is that if we encounter weird behavior from using it, we're not surprised 🫠
