### ISSUE TITLE
Typescript is not inferring the correct type for an extended class!

### ISSUE THREAD

**Issue by Saff-Elli-Khan** [microsoft/TypeScript#56184]
### 🔎 Search Terms

"extended class inference invalid"

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/MYGwhgzhAEBCkFMA8YA00BG7gD5oG8BfAKGNEhgBUwAnAcwQBcV0tpdoEAPRhAOwAmMeBGRpM2PPmLR2Aez4RGNAK7BGcmgAowALmjiM+tsH3AAlARmzoEFQAcE28wG5rJEmQVLolYNABeaD4EAHdfWgZGLQBlZQBLPjp0ACIlGkS6AEYU1PTMgCYU11JGAE9HX0Docsc5ADNfYDdiWoRfAGFqyk4efiE4RBQ+MvQwEfRE+qdoACU8AH456H0QgDcnFyA

### 💻 Code

```ts
class Base<a, b, c> {}

class Target<a, b, c> extends Base<a, b, c> {
  constructor(a: a, b: b, c: c) {
    super();
  }
}

const Tc = new Target(String, "string1", "string2");

type T = typeof Tc;

type TC = T extends Base<any, any, infer R> ? R : never; // TC should be `string` not `unknown`!
```

### 🙁 Actual behavior

The type of TC is `unknown`

### 🙂 Expected behavior

The type of TC should be `string`

**Comment by nmain** [comment]
See [the FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--).

The example works when the type parameters are actually used and affect the structure of the class.

**Comment by Saff-Elli-Khan** [comment]
> See [the FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--).
> 
> The example works when the type parameters are actually used and affect the structure of the class.

I see what you are saying, I did use those parameters on the real code and just created a dummy code for you of course. But I still see an unexpected behaviour because sometimes the third parameter was getting inferred correctly! Maybe I did something wrong, will it be possible for you to make some changes to the above code and build exactly what I am expecting? This will give me an idea of the mistake I've made...

**Comment by fatcerberus** [comment]
TS can sometimes infer unused type parameters when inferring between two instances of the same generic (i.e. `Foo<string>` -> `Foo<infer T>` -> `T = string`, but this is a special case and you shouldn't depend on it.  In general inference is structural so trying to infer an unused type parameter makes about as much sense as solving for `x * 0 = 0`

**Comment by fatcerberus** [comment]
I understand what you want, but you need to actually use the type parameters in the base class, otherwise from the type system point of view, *it doesn’t matter what the types are* (try it yourself—all `Base<T, U, V>` are assignable to each other regardless of which types you use) and it can infer anything.

If you need this pattern to work you can add private properties to the class with each generic type.  You don’t need to actually use them in the implementation.
