### ISSUE TITLE
Expose `getMergedSymbol` in type checker to public

### ISSUE THREAD

**Issue by timocov** [microsoft/TypeScript#56192]
### 🔍 Search Terms

"type checker", "getMergedSymbol", "merged symbol"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

While using the compiler's API in some cases (I wasn't able to find a small reproduction yet) the type checker might return "merged symbol" that it seems is not possible to resolve to the original symbol as yet. I noticed that there is an API but it is marked as internal. Is there any particular reason why this API isn't exposed yet and we should use something else to resolve merged symbols?

I also noticed that dtsBundler script from the compiler's repo is [using it via `any` hack](https://github.com/microsoft/TypeScript/blob/d9d027d0c4f5044631a0c078166b8d01f41d28b5/scripts/dtsBundler.mjs#L260-L262) which means that there is a room for an external usage of this API?

If that's fine to expose this API I'm happy to make a PR.

### 📃 Motivating Example

This feature allows to resolve merged symbols? I don't know to be honest 😄 

### 💻 Use Cases

1. What do you want to use this for? I'm maintaining https://github.com/timocov/dts-bundle-generator and I've got [an issue report](https://github.com/timocov/dts-bundle-generator/issues/265), after debugging I figured out that the tool is getting different symbols for the same node depends on where you asking the type checker to resolve it.
1. What shortcomings exist with current approaches? Its not possible to resolve some symbols to the original versions and it makes impossible to perform some operations.
1. What workarounds are you using in the meantime? No workarounds as yet, but probably will use the same `as any` hack

**Comment by jakebailey** [comment]
How are you planning on using the function? I'm trying to decide if the actual thing to export here is a helper that says if two symbols are the same (which is what the bundler actually needs). Hard to say if this "merged symbol" thing is an internal detail or not. This function is apparently unused in the public API so I'm surprised it's there. That or I added it and I forgot.

**Comment by timocov** [comment]
> How are you planning on using the function?

@jakebailey In my case I'm relying on symbol objects uniqueness and made an assumption (probably wrong?) that for a given identifier I can get a symbol and get other symbols that are using this symbol (the tool builds symbols usage "tree" i.e. a key is a symbol A and value a set of symbols that reference this symbol A) so later I can detect all places where a given node/symbol is used and do some analysis later. So at the moment the issue (at least from my debugging) is that when I'm building the tree I'm getting "source" symbols and building a tree based on that, but then when do analysis I'm hitting export statements like `export { Foo as Bar }` and when trying to resolve `Foo as Bar` I'm getting "merged symbol" which cannot be found in the "usage tree".

> That or I added it and I forgot.

It was added back in 2017 IIRC 🙂

**Comment by timocov** [comment]
> Hard to say if this "merged symbol" thing is an internal detail or not

100% agree, without knowing that a symbol can be "merged" usage of this function is questionable (when you're gonna call it? only knowing the implementation you can say that its safe to call it with non-merged symbols 😄), e.g. for `getAliasedSymbol` there is symbol flag that tells you that a symbol is an alias...

I admit that I might be doing something crazy in the tool thus I'm hitting such issues, but I don't know what exactly I'm doing wrong...

**Comment by timocov** [comment]
Hi @jakebailey, do you have any news in the regard of this issue? I understand that exposing this API might not be a desired feature for the compiler API and I appreciate that, but maybe you have any ideas how we can address the issue from my description above? Maybe something isn't clear? Another slightly different question - maybe you can help with understanding what these "merged symbols" are or how they are appearing in the type checker (I mean the context or what they solve)? Thanks!

**Comment by jakebailey** [comment]
It's on the docket to talk about at a design meeting, you just happened to ask on the day of the week that's farthest away from those meetings 😄

**Comment by jakebailey** [comment]
It sounded like we were okay with adding this; I am certainly curious though if this is the only function that you need to solve your problem, though it sounds like you're trying to key off of the symbol and therefore an equality function is _not_ the API you need.

**Comment by timocov** [comment]
Thank you so much for the update!
