### ISSUE TITLE
noImplicitAny rule does not work correctly on "let" variables

### ISSUE THREAD

**Issue by jangoergens** [microsoft/TypeScript#56196]
### 🔎 Search Terms

"noImplicitAny let not working",

### 🕗 Version & Regression Information

As far as I can test in the playground it never worked before, but I am sure that it was working at some point. For example [this article](https://www.geeksforgeeks.org/explain-about-noimplicitany-in-typescript/) uses let as an example,

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-dev.20231023#code/DYUwLgBAhg3EA

### 💻 Code

```ts
let a;
```

### 🙁 Actual behavior

No error

### 🙂 Expected behavior

Error: Variable 'a' implicitly has an 'any' type.ts(7005)

### Additional information about the issue

In case this is actually intended behaviour, I think the description of the rule should be adjusted to be clear about it.

**Comment by RyanCavanaugh** [comment]
Evolving `let` is an intentional feature. See #54414, #45369, etc.

**Comment by jangoergens** [comment]
Thank you for linking me to those threads, I now understand why it was implemented that way. Do you think it is helpful to add a small explainer to [the docs](https://www.typescriptlang.org/tsconfig#noImplicitAny)?

**Comment by RyanCavanaugh** [comment]
We need that page to be a manageable length, and the number of cases of "unannotated thing *isn't* `any`* is quite large. I think fixing #54414 would be better

**Comment by jangoergens** [comment]
That sounds good, thank you!
