### ISSUE TITLE
Provide @ValidNullsafety special annotations

### ISSUE THREAD

**Issue by Silentdoer** [microsoft/TypeScript#56199]
### 🔍 Search Terms

Provide @ValidNullsafety special annotations, such as:
```typescript
@ValidNullsafety
class Foo {
  name: string;
  age: number?;
}
```

after enabling null security, after compiling into js, you can automatically add validate instance methods to Foo to generate such a piece of code:
```typescript
Foo foo = JSON.parse(content);
if (!foo.validate()) {
  throw new Error("data error");
}
```
; This is useful for verifying that the field values of foo are correct after JSON.parse is converted to a Foo object

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

none

### 📃 Motivating Example

none

### 💻 Use Cases

none

**Comment by fatcerberus** [comment]
> This wouldn't change the runtime behavior of existing JavaScript code

It very much would, per the very example you gave.

> This isn't a runtime feature

It is, because you're asking for the compiler to add runtime-callable methods to objects that don't already have them.

> This could be implemented without emitting different JS based on the types of the expressions

Also not true: The compiler has to know the type of `foo` to know whether it should add method(s) to it

> This feature would agree with the rest of our Design Goals

Directly from the [TypeScript Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) under **Non-Goals**:

> 5. Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.
> 6. Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

**Comment by Silentdoer** [comment]
But this is a very meaningful feature, without this ability then TypeScript's null safety is meaningless, and this will only generate relevant code after writing special annotations, and will not affect the whole

**Comment by RyanCavanaugh** [comment]
This is definitely out of scope, per the above comment
