### ISSUE TITLE
In a modular context, when an enum uses another-enum as its value, the enum be Reverse mappings

### ISSUE THREAD

**Issue by shaddollxz** [microsoft/TypeScript#56206]
### 🔎 Search Terms

"enum" "revers mappings" "module"

### 🕗 Version & Regression Information

typescript: 5.2.2
vite: 4.4.7 or nextjs: 13.5.6
react: 18.2.0
vue: 3.3.4

### ⏯ Playground Link

https://codesandbox.io/s/amazing-mcclintock-j6s48r?file=/src/App.tsx

### 💻 Code

```ts
// enum.ts
export enum Map {
  A = 'a',
  B = 'b',
}
// index.ts
import { Map } from './enum'
enum NewMap {
  KeyA = Map.A
}

console.log(NewMap) // { KeyA: "a", a: "KeyA" }
```

### 🙁 Actual behavior

`NewMap` is a **reverse mappings** enum

### 🙂 Expected behavior

`NewMap` not revers, like `{ keyA: 'a' }`

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/issues/56153#issuecomment-1773331706

**Comment by fatcerberus** [comment]
Hmm, but that comment only says this would be an error under `isolatedModules`.  Here, even *without* `isolatedModules` (where this would presumably be allowed), it's emitting a reverse mapping for a string-valued member, which seems wrong.

**Comment by RyanCavanaugh** [comment]
Codesandbox appears to be using single-file transpile and thus should turn on `isolatedModules`. The whole-program `tsc` emit is correctly unidirectional.
