### ISSUE TITLE
Unable to widen "this" with an index signature (but a class instance works)

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#56208]
### 🔎 Search Terms

type assertion 
TS2536

### 🕗 Version & Regression Information

- This is the behavior from 3.3 to 5.3 beta

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-beta#code/MYGwhgzhAEC2CeBhcUDeAoa0AOBXARiAJbDRgAm5AEmMANYAUAlBllsAPYB2EALtLwAWRCADUwAJ2gBeAcJiRoDISOgAyaACUAppwnkAPHwlEuAcwA0S5jIB80AG4ci5JraYBuTGwD0P6AAq8Nja0ADkAERc2gDuNPRU2hLaEWHQwGBcXBz8+KG4ENrkAhzQpuTaAB4CwaFhKjAaOnqGxqaWSkx2ZFzwtmEAdN5YDeISANph0XG0dInJYQC6Mp3StqgAvljow9B+0ACSXBXVEERmXGC8uMnQAGYcUry14W3maaqwImfmZVw1IXCCGQkAgg12nB4-FAoLGKwaZBgDGBKEaWl0j1avBM5isDBsa0czlc7i8bHSqLGk2m8TmSW0SxWzDWm22O3JkL40GmIKgRy5smmcCQqJsihRoPU6JaRmx7TxBPsThcbjJvn8MUedBgxDooTA6UEklgux5qP5vGpsVp8wZy1kzPWG12+yoNwkYHgVmeIRgmokdHa0EE9NNsV5EAtVpiAHUJNwzDb6YyHQB9GLx8wABUkYFg2l4SQAXNB8BwOCBtJkmCznVhnc6gA

### 💻 Code

```ts
class myClass{
  public addHack(){
    const thisVar = this as (this & Record<string, (() => void)>);
    // Type '"newHackHere"' cannot be used to index type 'this & Record<string, () => any>'.
    thisVar['newHackHere'] = ()=>{}  

    // Index signature for type 'string' is missing in type 'myClass'.
    const classVar = this as (myClass & Record<string, (() => void)>);
    classVar['newHackHere'] = ()=>{}  


    const newClassInst = new myClass() as myClass & Record<string, (() => void)>;
    // works like a charm
    newClassInst['newHackHere'] = ()=>{}
    // Hurray, types working here
    newClassInst['newWrongHackHere'] = (_wrongParameter: boolean)=>{}
  }
}
```

### 🙁 Actual behavior

I am not able to widen the type of `this` with `& Record<string, (() => void)>`.

### 🙂 Expected behavior

But with a new class variable this is no problem.

### Additional information about the issue

related to #31439 ?

**Comment by RyanCavanaugh** [comment]
This follows from the definitions of the operations involved:
 * `this` is treated as an arbitrary subtype of `MyClass`
 * The write expression `thisVar['newHackHere'] = ()=>{}` is unsound because a valid subtype of `this` might have some other field at `newHackHere`
 * `T as U` is allowed when `T` or `U` is a subtype of the other

**Comment by HolgerJeromin** [comment]
Thanks for your time. 
I have no insight why `this` is treated as an arbitrary subtype of `MyClass`, but I am pretty sure there is a good reason for that.

**Comment by fatcerberus** [comment]
> I have no insight why `this` is treated as an arbitrary subtype of `MyClass`

Let's say you have a class that derives from `MyClass`.  If `addHack` is called through an instance of *that* class, `this` will be refer to instance of said derived class at runtime, *not* of `MyClass`.  Thus the type of `this` is implicitly generic.

**Comment by RyanCavanaugh** [comment]
Demo of why `this` is an arbitrary subtype:
```ts
class Foo {
    getMe(): this {
        return new Foo();
        // ^ must error, because...
    }
}
class Bar extends Foo {
    doBarThing() {
        console.log('hi');
    }
}

// ... this crashes
(new Bar()).getMe().doBarThing();
```
