### ISSUE TITLE
Incorrect type inference after array unpacking. Unsound error

### ISSUE THREAD

**Issue by Crinax** [microsoft/TypeScript#56217]
### 🔎 Search Terms

"type inference", "array", "unpacking", "destructuring"

### 🕗 Version & Regression Information

- This is a unsound error
- All versions in playground have this bug

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQGIwE4GcoAUAhttgFyJggC2ARqtgNoC6AlIgN4BQiviECfIkYA3IgBsQqZogC8iEtgDcPPtnQhsSMZNQqAvly7j0iYHJToseQi1ZKgA

### 💻 Code

```ts
function getFirst(arr: number[]) {
    const [value] = arr;
    return value;
}

let f = getFirst([]);
```

### 🙁 Actual behavior

`f` variable has type `number`

### 🙂 Expected behavior

`f` variable must be a `number | undefined`

**Comment by MartinJohns** [comment]
This was already fixed by introducing the `noUncheckedIndexedAccess` compiler option. You need to enable it, then it results in `number | undefined` as expected.

**Comment by MartinJohns** [comment]
> In that way, wouldn't it be considered a logical error? When a user tries to get an element, TypeScript guarantees that it exists.

I don't understand what you mean. Without `noUncheckedIndexedAccess` the type is unsound, yes. That's why this option was added.
