### ISSUE TITLE
Confusing error message when an array of objects of types a is used instead of a plain object of type a

### ISSUE THREAD

**Issue by vjau** [Microsoft/TypeScript#5621]
With following code :

```ts
interface IFoo {
  bar: string;
}

let arr = [{bar: "baz"}, {bar: "booz"}];


function doFoo(obj:IFoo){
  return obj;
}

doFoo(arr);
```
You are getting the error message on the doFoo(arr) line:

```
error TS2345: Argument of type '{ bar: string; }[]' is not assignable to parameter of type 'IFoo'.
  Property 'bar' is missing in type '{ bar: string; }[]'
```

I was just downvoted to oblivion on stackoverflow for asking such a stupid question, but at least for me, the error `Property 'bar' is missing in type '{ bar: string; }[]` is rather confusing (it doesn't make any sense) if you don't understand that the problem is that you have an object of type A on one side with an array of objects of type A on the other side.
IMHO, something like `an array of IFoo is not assignable to a plain IFoo` or whatever you prefer would be better than actual message. 

Thank you.

**Comment by mhegazy** [comment]
I do not think there is much we can do here. the TS type system is a structural one. not all types have names, and even when they do, their names do not matter much. in your example, `arr` is not of type `IFoo []` it is of type `{ bar : string}[]`, asking the compiler to relate this to a named type and give you the name instead is not by any means a simple task, and I do not think it will help resolve the issue either. if `arr` is defined as `IFoo[]` you should get the message you want.

the error message gives you a stack of the failed comparison, and drills down to reach the missing. i understand that this takes some training to get used to, but i believe this capture the most information he compiler can provide.
