### ISSUE TITLE
Make VS Code use ".js" instead of ".jsx" when auto-generating import for ".tsx" file

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#56210]
Given a file `foo.tsx` and `bar.tsx`, when importing bar from foo, I'd like a VS Code setting that will make it auto-import as `import Bat from './bar.js';`

**Comment by RyanCavanaugh** [comment]
The auto-import behavior will try to match whatever would work at runtime. Please post a complete repro (including tsconfig, package.json, and the actual files)

**Comment by sdegutis** [comment]
Hey @RyanCavanaugh. So it's my custom runtime in https://github.com/sdegutis/immaculatalibrary.com, where all .ts or .tsx files are compiled by sucrase and [turned into .js files](https://github.com/sdegutis/immaculatalibrary.com/blob/main/src/runtime.ts#L51) within the runtime environment. I currently have an ugly hack to [just replace all .jsx with .js](https://github.com/sdegutis/immaculatalibrary.com/blob/main/src/module.ts#L43) during the compilation phase, but it would be nice if VS Code had an option to just allow me to specify auto-imports as `.js` since that's what .ts and .tsx could reasonably compile to in other environments as well. This is also part of my plan for this week of creating universal modules that work the same both at build time (for my ssg) as well as client-side, which means my "compiler" would be generating .js files that can be imported in the browser, where .jsx isn't a reasonable extension to generate, plus it has no JSX in it (compiled away by sucrase).

**Comment by sdegutis** [comment]
On a related note, why hasn't the JS community standardized on just transforming JSX expressions to this? Seems like it would solve like _every problem_.

```typescript
interface JSX {
  _isJsx: true,
  tag: string | Function,
  attrs: Record<string, any>,
  children: any[],
}
```

**Comment by RyanCavanaugh** [comment]
It sounds like you want to set `jsx` to `react-native`, which preserves JSX for the next step in the build chain, but tells TS that the final file extension will be `.js`

**Comment by sdegutis** [comment]
Yep that does exactly what I need. Maybe it should be renamed to be more generic? But minor issue
