### ISSUE TITLE
moduleResolution: Bundler leads to "out of memory" with JSON

### ISSUE THREAD

**Issue by artola** [microsoft/TypeScript#56219]
### 🔎 Search Terms

"moduleResolution", "bundler", "resolveJsonModule"

### 🕗 Version & Regression Information

- This is a crash

### 🙁 Actual behavior

A project with too many JSON files fails to compile if used `tsconfig.json` containing:

```text
    "moduleResolution": "Bundler",
     "resolveJsonModule": true,
```

```text
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

While it works if the `tsconfig.json` is set to:

```text
    "moduleResolution": "Bundler",
     "resolveJsonModule": false,
```

or using:

```text
    "moduleResolution": "NodeNext",
     "resolveJsonModule": true,
```

### 🙂 Expected behavior

It compiles with a normal memory usage.

### Additional information about the issue

Tested with TS `5.2.2` and `5.3.0-beta` same outcome.

This project compiles if the memory is increased over 8GB:

```shell
yarn tsc -p tsconfig.json --noEmit --extendedDiagnostics
```
Output:

```text
Memory used:               8594988K
```

As I see, the problem is related to the typings for the huge JSON files. Possibilities?

- set `resolveJsonModule` to `false`: now all the typings are `any`, compatible with behaviour in older TS versions.
- create a `.json.d.ts` as `any` per file: 
  - PRO we can get typings where needed (no `.json.d.ts`)
  - CON huge burden because there are really a lot of files, plus error prone
- is it possible to declare a global for JSON files inside some folders only? while the others will be properly resolved?

**Comment by RyanCavanaugh** [comment]
If you have a huge JSON file, you either need to put a `.d.ts` in front of it so TS doesn't try to load it, or not try to resolve it in the first place. You can selectively have some `.d.ts`'d and some not.

There's not really a third way here; we've investigated this before and basically are already doing the best we can on JSON inference.

**Comment by artola** [comment]
> If you have a huge JSON file, you either need to put a `.d.ts` in front of it so TS doesn't try to load it, or not try to resolve it in the first place. You can selectively have some `.d.ts`'d and some not.
> 
> There's not really a third way here; we've investigated this before and basically are already doing the best we can on JSON inference.

Thanks for the prompt answer. AWESOME.

**Comment by artola** [comment]
@RyanCavanaugh I can workaround with the suggestions above, but I would like to remark, that the same project and same JSON files, compile without problem when we set `moduleResolution = NodeNext`, it is just `moduleResolution = Bundler` that produces a huge memory allocation, around 10 times more in this case.
I would guess that there is a memory leak that could make sense to re-check.
