### ISSUE TITLE
Inappropriate Type Narrowing on Iterative Variable Reassignment

### ISSUE THREAD

**Issue by pedrodurek** [microsoft/TypeScript#56216]
### 🔎 Search Terms

"type narrowing", "type narrowing within loop"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/FAFwngDgpgBAyiKEYF4YG9g2zAzoiAOQEMBbKALjxACcBLAOwHMscGoAPEBJKn5AD4wGAVwA2YgNzAAvsGABjAPYN81JABk6atAG0A5MX0AaGPoBGJswv0BdaWKggYACyjEAJvz4EYQ0RKowuJSwI7OEDRQAG7e8L7+IUEBocD4mtogAHQAZko0AKLECi4AFKXpRGRQAJSoAHwYrNjKqs7sAO5x-EGYOP3qVeTGzQPsXHEpo3KjdDkwpW6ePSirwRJ1fQPYS16+aJ380v0z-XMLkTH8m6P9l7EEWePc+8JQXQTHOKc49ytvHyQ0hkNXk4GgMEYOSgNCiHgAKpBYGhwVAlPNdvxgAB6bHYAB6AH5gEA

### 💻 Code

```ts
type Step = {
    stepName: string
    nextStep: Step | null;
}

const stepList = ['a', 'b', 'c'];
let headStep: Step | null = null;
let prevStep: Step | null = null;

stepList.forEach((stepName) => {
    const newStep: Step = {
        stepName,
        nextStep: null
    }

    if (headStep === null) {
        headStep = newStep;
    }

    if (prevStep) {
        prevStep.nextStep = newStep;
    }

    prevStep = newStep;
})

type inferredType = typeof headStep
//  ^?

```

### 🙁 Actual behavior

```ts
type inferredType = typeof headStep
//  ^? type inferredType = null
```

### 🙂 Expected behavior

```ts
type inferredType = typeof headStep
//  ^? type inferredType = Step | null
```

### Additional information about the issue

Whenever `headStep` is reassigned within the forEach loop, the `Step` gets filtered out from the original type (wrongly narrowing).

**Comment by RyanCavanaugh** [comment]
Effects of callbacks aren't modeled in CFA, so your example is equivalent to
```ts

type Step = {
    stepName: string
    nextStep: Step | null;
}

const stepList = ['a', 'b', 'c'];
let headStep: Step | null = null;
let prevStep: Step | null = null;

type inferredType = typeof headStep
//  ^?
```
which is correct.

See #11498

**Comment by pedrodurek** [comment]
Ohhh got it, thanks for the explanation @RyanCavanaugh! Just realised that I 👍 the original issue at some point in the past. I'll close this one.
