### ISSUE TITLE
Types not generated/working with AMD module

### ISSUE THREAD

**Issue by ts-lover** [microsoft/TypeScript#56224]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

When using AMD modules and working in VSCode, type declarations are not being picked up for modules that load dependencies using an array passed to the define function, but they are working for modules that load dependencies using `require('./module-path')`

In a simple project structured like this:

```
app
    |app.js
    |lib.js
    |lib.d.ts
```
The file `lib.js` contains this:

```
define('lib', function() {
    return {
        libTest: (msg) => {
            console.log('lib is working!', msg);
            return true;
        },
    }
});
```
The file `lib.d.ts` looks like this:

```
/** @name declaration test */
export module './lib';
/** @name libTest */
export function libTest(msg: string): boolean;
```
The declarations from `lib.d.ts` are correctly picked up in `app.js` with this and Intellisense works as expected, pulling info from `lib.d.ts`:

```
const lib = require('./lib');
lib.libTest(); // hovering pointer on 'libTest' shows "function libTest(msg: string): boolean \n @name -- libTest" and hovering on 'lib' shows "@name -- declaration test"
```
The declarations also work as expected if `app.js` looks like this instead:

```
define(function() {
    const lib = require('./lib');
    lib.libTest(); // hovering pointer on 'libTest' shows "function libTest(msg: string): boolean \n @name -- libTest" and hovering on 'lib' shows "@name -- declaration test"
});
```
However, the declarations **do not work** at all when the code in `app.js` looks like this:

```
define(['lib'], function(lib) {
    lib.libTest(); // hovering pointer on either 'lib' or 'libTest' just shows "any"
});
```
Why are the declarations from the `lib.d.ts` file working as expected for the first two variations of `app.js`, but not the third variation which uses an array of dependencies?

Additionally, if I delete the `lib.d.ts` file and try to have the compiler generate the declarations automatically (using `"declaration": true, "emitDeclarationOnly": true` in tsconfig) the tsc command completes successfully, but the generated d.ts file is completely empty

**Comment by RyanCavanaugh** [comment]
JS module inference only works for calls to the `require` function; it doesn't support AMD `define` calls.

**Comment by ts-lover** [comment]
Ok, thanks for the quick response Ryan :)

What about if the app file was a TypeScript file instead of a JS file, would that make any difference?

**Comment by RyanCavanaugh** [comment]
You'd have to write it with "normal" TS syntax and transpile to AMD format for it to be recognized

**Comment by ts-lover** [comment]
Got it, thanks so much!
