### ISSUE TITLE
Extend Arrays In Tsconfig

### ISSUE THREAD

**Issue by enchorb** [microsoft/TypeScript#56223]
### 🔍 Search Terms

I am unable to use both tsconfig.base paths (nx monorepo libs) and tsconfig.local paths (relative path cleanup).

Good solutions are mentioned here https://github.com/microsoft/TypeScript/issues/20110

Opening this with another issue because that one is from 2017 and seems to largely have fallen off the radar 

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

An `<inherit>` peoprty for tsconfig files. See here for more: https://github.com/microsoft/TypeScript/issues/20110

### 📃 Motivating Example

See here for more: https://github.com/microsoft/TypeScript/issues/20110

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by xiBread** [comment]
There's no point in making another issue if there's already one open.

**Comment by RyanCavanaugh** [comment]
Making duplicates on purpose is a misuse of the issue tracker and is not appropriate behavior. Further violations will result in a block.
