### ISSUE TITLE
Unnecessary renames after after extract refactoring code actions

### ISSUE THREAD

**Issue by zardoy** [microsoft/TypeScript#56236]
### 🔎 Search Terms

not needed newly introduced variable / symbol renaming after extract to constant refactor

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about it

### ⏯ Playground Link

-

### 💻 Code

```ts
a.newLocal;
b + c
```
Select `b + c`, and apply the extract to constant code action.

### 🙁 Actual behavior

```ts
a.newLocal;
const newLocal_1 = b + c;
```

### 🙂 Expected behavior

```ts
a.newLocal;
const newLocal = b + c;
```

since there is actually no variable collision

### Additional information about the issue

The actual behavior above can be confusing a bit.
By the way, I was trying also to work on https://github.com/microsoft/TypeScript/issues/54130, but I don't think it would be possible to implement since `getUniqueName` uses simple `identifiers` map on the source file.

**Comment by zardoy** [comment]
There is no playground link since as I understand refactorings don't work in playground, or I need to enable them somehow?
<img width="375" alt="Screenshot 2023-10-28 at 01 27 43" src="https://github.com/microsoft/TypeScript/assets/46503702/e8906dec-1913-4c18-8de4-1826371a91c3">

**Comment by RyanCavanaugh** [comment]
Why is it a bug what arbitrary name we pick here? It's ephemeral.

**Comment by zardoy** [comment]
Agree, my bad. It could be an enhancement to the current behavior, but maybe it is just not worth changing since the variable will be renamed anyway. (I just decided to open an issue before sending a pr :)

**Comment by zardoy** [comment]
@RyanCavanaugh but what about https://github.com/microsoft/TypeScript/issues/56236#issuecomment-1783586089 ? It would be so great if I could refactorings on the same playground, does it work in general?

**Comment by RyanCavanaugh** [comment]
It'd be nice! The Playground uses the editor surface some a slightly lower level than VS Code does, so not everything works the same way. PRs welcomed but I'm not sure it's a straightforward toggle.

**Comment by fatcerberus** [comment]
An enhancement that *would* be nice is if it automatically triggered a rename action (or just prompted for a name first, but I assume there's no machinery in place for that)

**Comment by zardoy** [comment]
> An enhancement that _would_ be nice is if it automatically triggered a rename action (or just prompted for a name first, but I assume there's no machinery in place for that)


Doesn't it already trigger a rename action? IMO TypeScript should add snippet support for code actions (https://github.com/microsoft/TypeScript/issues/50166). This would be a big improvement. Right now, the rename action can be triggered with a big delay, which is not ideal.

---
Also I used a command in vscode that asks for a variable name first (via inputbox), but it was terrible since you can get word-based completions only within the editor.

**Comment by fatcerberus** [comment]
> Doesn't it already trigger a rename action?

I don't know, actually! 😅  I kind of assumed it didn't though since IMO there's no reason to care about the initial name TS picks for the variable otherwise.
