### ISSUE TITLE
Function with parameters used as a generic constraint does not work as expected

### ISSUE THREAD

**Issue by alesmenzel** [microsoft/TypeScript#56234]
### 🔎 Search Terms

"function generic parameters"

### 🕗 Version & Regression Information

- This is a crash No
- Same result in every TS version from 3.3 up to 5.3
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about functions and generics.

### ⏯ Playground Link

https://www.typescriptlang.org/play?jsx=4&ts=5.3.0-beta#code/C4TwDgpgBAglC8UAUYBOB7MBnAXFA3lAGbrp4DkJ65ANFAEYCGqFTq5UAvgJQIB8UAG7oAlgBMAUKEhQAQgmRpMuAsVIUqHHvyGjJEogFcAdgGNgI9MagAVAKIBlGwB4bUCAA9gEY2KzIUDGw8QioNUlooAG0AawgQPCxgVBFjAHMAXTxGYxAuXngBYXFuPiRUsENgADFjPBs6JWCoAAVmRgBbCG9ULFc+KIAGDN58CSgJgHpJqAA6efGJ0yssdAAbCFm19DTA5VmqbkWoVG7DVGsKqtq97CPOCQll4yTiYxg8OERbrAKBEzEECIqQgkmeryIxlkeHk3yavx0AKBIP09icSEhMDooXUUEoETobFYzC0vGmUEAMuQSckAPQA-NSZjBUGlDF1jMAoOgiFBpNByDAOCJ-MZ0JzGFgsCI0sZGPQNrz0FAwO0uj0uTy+XifiFonEElAkil0lkoDkQABuNRkKAAIiotqt2kKunE5FmjImtnAEH83OVqu6EF6ePhHByYlDQSw4dOUFSyw6Kos8s2nq9rSCwdAeLYQv8HWFUvS8esWvIhFi8USyVSmWyuStYTtDqdHHoVROEAAjoYRKdI6leT68TibfbSI6GMw8La2FPOO6kAAmADMABYAKxHclXYCzYBYDxIACMdFXy+4xPY8f8gNMa2YoKgAAtg2m0TYMVDsdbwtR8igclAFByIA

### 💻 Code

```ts
type A = (props: { foo: 'foo', bar: 'bar' }) => void
type B = (props: { foo: 'foo' }) => void

function TEST<T extends ((props: { foo: 'foo', [key: string]: any }) => void)>(inputFn: T, props: Parameters<T>[0]) {
   // ...
   console.log(props.foo)
   return inputFn(props)
}

const fnA: A = (props) => undefined
const fnB: B = (props) => undefined

TEST(fnA, { foo: 'foo', bar: 'bar' }) // ❌
// ^?
// Argument of type 'A' is not assignable to parameter of type '(props: { [key: string]: any; foo: "foo"; }) => void'.
//   Types of parameters 'props' and 'props' are incompatible.
//     Property 'bar' is missing in type '{ [key: string]: any; foo: "foo"; }' but required in type '{ foo: "foo"; bar: "bar"; }'.(2345)
// input.tsx(1, 32): 'bar' is declared here.
TEST(fnB, { foo: 'foo' }) // ✅
```

### 🙁 Actual behavior

Constraining the function parameter `TEST<T extends ((props: { foo: 'foo',  [key: string]: any }) => void)>` does not structurally require the passed function to include at least the given property.

### 🙂 Expected behavior

No error. The function A (`fnA`) does satisfy the constraint of `<T extends ((props: { foo: 'foo',  [key: string]: any }) => void)>`.

**Comment by RyanCavanaugh** [comment]
This is a correct error. If `T` extends that constraint, then
```
   inputFn({foo: "foo"});
```
from the body of `TEST` is a legal call, but it isn't a valid call to `fnA`, hence there's an error.

If you're saying the index signature should somehow allow this, then the parameter type on the constraint you're implying is `any` (or `never`).

**Comment by alesmenzel** [comment]
Could you please provide a runtime example when this could not work? From my pov, if I pass `fnA` then the second argument must be of type `{ foo: 'foo', bar: 'bar' }` which is the signature for the function. Furthermore, if I remove the constraint on the function parameter (change it to `extends ((props: any ) => void)`), then it will work. But I would like to require that the passed function expects a property `foo`.

```
// But without the constraint it works
function TEST<T extends ((props: any ) => void)>(inputFn: T, props: Parameters<T>[0]) {
   // ...
   console.log(props.foo)
   return inputFn(props)
}
```

**Comment by RyanCavanaugh** [comment]
```ts
type A = (props: { foo: 'foo', bar: 'bar' }) => void
type B = (props: { foo: 'foo' }) => void

function TEST<T extends ((props: { foo: 'foo', [key: string]: any }) => void)>(inputFn: T, props: Parameters<T>[0]) {
    // This is OK per the definition of the signature
    inputFn({foo: "foo"});
}

const fnA: A = (props) => {
    // Prints 'I am sure that undefined is "bar"'
    console.log(`I am sure that ${props.bar} is "bar"`);
}
// Alleged: This should be legal
TESt(fnA, { foo: 'foo', bar: 'bar' });
```

> But I would like to require that the passed function expects a property foo.

You can't put a contravariant constraint on generic parameters. They're only covariant.

**Comment by alesmenzel** [comment]
I see, I could call the inputFn inside the function without all of the required properties, thanks for examplaining.
