### ISSUE TITLE
Using function overloads with an invalid type for the methods on the second param correctly infers the generic type as being nullable, but results in an error in which the same generic type is non nullable

### ISSUE THREAD

**Issue by loucadufault** [microsoft/TypeScript#56238]
### 🔎 Search Terms

function overloads - inferred type - error expected type - mismatch discrepancy - non nullable - nested function method - properties param

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about overloads

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/C4TwDgpgBAwgRgHgKoD4oF4oAoCUG1IDcAUMaJFAPJwBWEAxsAOoCWwAFgGIB2AzggDU0mAN7EoEqADMWAJ17AAXNjABDWaoC2AFUqyAcgFcANseUCoAHyjcTxvOjQA3APYsAJiUlReDF93dlLDUNTQAGZVVuEAc0W004CFkSAF8SYilDbkYWf2kXFwRtFCx6OGV4IpQAGigXZWo6RlYOHn5inEjojKycvKkCqtLy2ERi2vqqWgZmNi4+Ks6oKJAe7OBc7nzC4uGKsZq6hunmubbFrpAoERTSdwZjdWh6fwUoTRB4INifYFkWbgAcysNjspAGLiwH3gtTE3hk8iU2HUgN0BjsPxu1XEkl8LwCQRRYUxOO8ElkEGAhlkWxuy14UCyAGtuC4AO7cUlQW4pHBAA

### 💻 Code

```ts
type Cb<U> = () => U;

type ObjectWithFns<V> = {
    first: (paramTOrNull: V | null) => void;
    second: (param0: any) => number;
};

function foo<T>(cb: Cb<T>, o: ObjectWithFns<T>): any
function foo<T>(cb: Cb<T>, o: ObjectWithFns<T>): any
function foo<T>(cb: Cb<T>, o: ObjectWithFns<T>): any {}

declare const myCb: () => string | null

foo(myCb, {
    first: (argTOrNull) => {},
    second: (arg0) => {
        return {} as unknown
    }
})
```

### 🙁 Actual behavior

Hovering over `foo`, it inferred `T = string | null`. Indeed, if the signature of `foo` is changed (in all overloads) to return `T`, and the result stored in a variable, the resulting type of the var (as emitted in the `.d.ts`) is `string | null`.

However the usage gives a compiler error for `myCb` that it does not match any of the 2 overloads for foo with `T = string` (`string | null` not assignable to `string`). 

Clearly, the type for `T` in the error for `myCb` does not match both:
1. the inferred type for T in `foo` itself
2. the types at any of the inference sites for `T`

The first constitutes a direct contradiction within the type system; `T` is simultaneously inferred as two different types within the same program.

The second (taken on its own) suggests faulty inference, since the generic param does infer its type from the first (by the parameter order) and only inference site with type information available (since the argument `argTOrNull` has type `unknown`), but the with `null` union member is stripped out for some reason.

### 🙂 Expected behavior

Since the supplied callback for the `second` property does not satisfy the expected type of `string | null` (in this case returning `unknown` instead of `number`), and since the supplied `myCb` for the first param satisfies the expected type(matching 2 of 2 of the function overloads), we would expect the compilation error to be for the `second` parameter instead of `myCb`, namely the error:

```
No overload matches this call.
  Overload 1 of 2, '(cb: Cb<string | null>, o: ObjectWithFns<string | null>): string | null', gave the following error.
    Type '(arg0: any) => unknown' is not assignable to type '(arg0: any) => number'.
      Type 'unknown' is not assignable to type 'number'.
  Overload 2 of 2, '(cb: Cb<string | null>, o: ObjectWithFns<string | null>): string | null', gave the following error.
    Type '(arg0: any) => unknown' is not assignable to type '(arg0: any) => number'.(2769)
```

### Additional information about the issue

Some additional observations:
- asserting the supplied callback for the `second` property to return `as any` still results in the same error (only asserting to return `as number` removes the compilation error)

Some tweaks that fix the bug, making the compilation error be for the `second` parameter instead of `myCb` (as expected):
- explicitly setting the generic type to `string | null`
- removing one or both of the function overloads
- making the `second` property on `ObjectWithFns<...>` a primitive type (e.g. `number` directly, instead of function returning `number`), and supplying a value that does not conform to the primitive type
- removing `param0` to make the signature for `second` property on `ObjectWithFns<...>` be a function without an argument (e.g. `() => number`)
- making the return type of `myCb` be non-nullable
- making the argument type for `paramTOrNull` be non-nullable

**Comment by RyanCavanaugh** [comment]
I don't see a defect here. The equation `4 + 2 = 7` is wrong, and we can say that the `4` should be `3`, or the `7` should be `6`, etc, but no error has a claim to be the one correct error.

**Comment by loucadufault** [comment]
Even ignoring which error is chosen, the bug report is mainly about consistency with the types as inferred in the program. Is it not a defect for the program to choose one type, and the error message choose the other? My understanding is that compiler errors operate based on the existing inferred types as pre-conditions, otherwise I don't see how it is feasible to reason about such issues if the valid and error outputs of the compiler reflect distinct decisions for the program types?

Regarding which error is the "correct" one. In your example the satisfiability of 4 in the equation is tied to that of 2, which explains how either error could be "correct". In the OP example however, it is not clear how there is any relation between the subject of the error and the actual source of the error. Namely, the value given for the first `cb` param is valid on its own, and there is no value given for the property `second` that would cause `cb` to no longer be valid. That the compiler handles a type error by flagging a completely unrelated and otherwise valid part of the program seems to me like a clear defect, no different from a more extreme case like:

```ts
function bar<T>(a: T, b: string) {}

bar('abc', 123)
//  ^ hypothetical type error here
```

**Comment by RyanCavanaugh** [comment]
>  Is it not a defect for the program to choose one type, and the error message choose the other?

Not really. These are separable concerns; they can (and do) have different answers. There are definitely cases where it'd be better to unify these, but also cases where it wouldn't be. It's generally best to try to "contain" errors as much as we can so that a single problem doesn't result in a large chain of downstream errors. For example, let's say you had
```ts
declare function foo<T extends string>(x: T): T;
const m: string = foo(42);
```
This program has at least one error: the inferred type of `T` will not meet the constraint. Under a "the types must be the same" regime, this program now has two errors - the constraint violation `T: number`, and the illegal assignment of `number` to `m: string`. But the second error isn't one that you should action until you fix the first error (at which point the second error has gone away).
