### ISSUE TITLE
VS Code Autocomplete takes a lot of time to load

### ISSUE THREAD

**Issue by grenganathan-atlassian** [microsoft/TypeScript#56231]
### 🔎 Search Terms

"vscode IDE performance" "vscode IDE autocomplete issue"

### 🕗 Version & Regression Information

- This has been an issue for a long time. Current Typescript version we are using is 4.9.
- Tested it using 5.2 and still the issue persists

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

We are seeing the tsserver take > 2 seconds to show the auto complete box in the IDE in our monorepo. In some files the autocomplete is faster(no delays) but in some complex files, it takes more time. We have project references implemented in parallel and we are seeing similar numbers.  We have an even bigger monorepo but we are not seeing delays there. Only in certain files in this monorepo.

Here is the output of `--extendedDiagnostics` of the repo

```
Files:                        49660
Lines of Library:             29122
Lines of Definitions:       1721305
Lines of TypeScript:        3706383
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Identifiers:                5601816
Symbols:                   10740739
Types:                      3464732
Instantiations:            16989098
Memory used:               9151862K
Assignability cache size:   1971921
Identity cache size:          81835
Subtype cache size:          226518
Strict subtype cache size:   216332
I/O Read time:                5.41s
Parse time:                   8.47s
ResolveModule time:           6.32s
ResolveTypeReference time:    0.04s
Program time:                22.00s
Bind time:                    4.97s
Check time:                 135.64s
printTime time:               0.01s
Emit time:                    0.01s
Total time:                 162.63s
```

TS Server log:
```
getCompletionData: Get current token: 0.0038750000530853868
Info 255  [18:38:35.556] getCompletionData: Is inside comment: 0.01470800000242889
Info 256  [18:38:35.556] getCompletionData: Get previous token: 0.025999999954365194
Info 257  [18:38:35.556] getCompletionsAtPosition: isCompletionListBlocker: 0.006708999979309738
Info 258  [18:38:35.561] getExportInfoMap: cache miss or empty; calculating new results
Info 259  [18:38:35.723] forEachExternalModuleToImportFrom autoImportProvider: 0.017084000050090253
Info 260  [18:38:35.723] getExportInfoMap: done in 162.00424999999814 ms
Info 261  [18:38:37.572] collectAutoImports: resolved 100 module specifiers, plus 303 ambient and 1670 from cache (233.6% hit rate)
Info 262  [18:38:37.572] collectAutoImports: response is incomplete
Info 263  [18:38:37.572] collectAutoImports: **1848.6797500000102**
Info 264  [18:38:37.572] getCompletionData: Semantic work: 2015.1172919999808
Info 265  [18:38:37.584] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 12.625125000020489
```

Trace of tsserver
<img width="1700" alt="Screenshot 2023-10-27 at 6 30 29 PM" src="https://github.com/microsoft/TypeScript/assets/113331937/b0eb073a-76f4-41af-9c9b-07d5edeac417">

Our tsconfig setup:
We have a base tsconfig and each package in the monorepo has a tsconfig.json which extends the base tsconfig. The package level tsconfig includes the files for that package.

### 🙂 Expected behavior

Expecting auto-complete to be fast

**Comment by RyanCavanaugh** [comment]
This is 5 million lines of code under analysis; even sublinear algorithms produce big numbers when inputs are that large. The only way forward here is some reduction of the amount of scope TS server has to consider.

**Comment by RyanCavanaugh** [comment]
> We have project references implemented in parallel and we are seeing similar numbers

Have you turned on disableSourceOfProjectReferenceRedirect?

**Comment by grenganathan-atlassian** [comment]
> This is 5 million lines of code under analysis; even sublinear algorithms produce big numbers when inputs are that large. The only way forward here is some reduction of the amount of scope TS server has to consider, which is a user-space configuration problem.

But in leaf packages (packages which do not depend on other packages in the repo) the time is pretty fast. Would you know why would that happen? Also in another repo, which is ~2x the size the autocomplete is fast.

> Have you turned on disableSourceOfProjectReferenceRedirect?
Yes. This doesn't seem to help.

I compared the `--extendedDiagnostics` with the other repo which is much larger and found this difference
```
Files:                         93334
Files:                         49660

Lines of Library:              28452
Lines of Library:              29122

Lines of Definitions:         781691
Lines of Definitions:        1721305
```

The 'Lines of Definitions' is ~3x more in the smaller repository. Could this be the issue?

**Comment by RyanCavanaugh** [comment]
FWIW 50,000 files is still way too many if you want fast editor interactivity. This would generally indicate a misconfiguration unless your project is absolutely enormous.

> Could this be the issue?

Absolutely. I'd recommend running `tsc --explainFiles` to see what the difference is and see if you can scope out some of the larger files.

**Comment by en-yash** [comment]
@RyanCavanaugh we do have 50k files in our repository. What we see in the above trace is `updateGraph` takes a lot of time. Can you guide us as to what the underlying issues could be?

**Comment by RyanCavanaugh** [comment]
I think the first step would be to run `tsc --explainFiles`, identify a file that *shouldn't* be in the list, and work backwards from there to figure out how it's getting in. Repeat as many times as necessary until the file list matches what you think it should.

**Comment by en-yash** [comment]
@RyanCavanaugh here is the output of `tsc --explainFiles`:
[explain-logs.log](https://github.com/microsoft/TypeScript/files/13223609/explain-logs.log)
I don't see anything odd as it contains all the declaration files from `node_modules`. Can you take a look and see if you see something odd?
Also curious to know does the output of `tsc --explainFiles` relate to autocomplete time

**Comment by RyanCavanaugh** [comment]
> Also curious to know does the output of tsc --explainFiles relates to autocomplete time

You pay a very small but nonzero penalty on incremental edit for every file in the project, since it requires a small but nonzero amount of work to verify the file is up-to-date, redo a small amount of work related to the file's exports, and so on.

**Comment by en-yash** [comment]
Is this denoted by  `getExportInfoMap` in the logs? From what the logs say, it's collectAutoImports that was around 2 seconds of time:

```
getCompletionData: Get current token: 0.0038750000530853868
Info 255  [18:38:35.556] getCompletionData: Is inside comment: 0.01470800000242889
Info 256  [18:38:35.556] getCompletionData: Get previous token: 0.025999999954365194
Info 257  [18:38:35.556] getCompletionsAtPosition: isCompletionListBlocker: 0.006708999979309738
Info 258  [18:38:35.561] getExportInfoMap: cache miss or empty; calculating new results
Info 259  [18:38:35.723] forEachExternalModuleToImportFrom autoImportProvider: 0.017084000050090253
Info 260  [18:38:35.723] getExportInfoMap: done in 162.00424999999814 ms
Info 261  [18:38:37.572] collectAutoImports: resolved 100 module specifiers, plus 303 ambient and 1670 from cache (233.6% hit rate)
Info 262  [18:38:37.572] collectAutoImports: response is incomplete
Info 263  [18:38:37.572] collectAutoImports: **1848.6797500000102**
Info 264  [18:38:37.572] getCompletionData: Semantic work: 2015.1172919999808
Info 265  [18:38:37.584] getCompletionsAtPosition: getCompletionEntriesFromSymbols: 12.625125000020489```

**Comment by RyanCavanaugh** [comment]
The overall program penalty is in `updateGraph`, but yeah, auto-import also spends nonzero time per file. You might want to consider disabling auto-import entirely if you're not able to reduce the total file count by much.

**Comment by en-yash** [comment]
<img width="1015" alt="image" src="https://github.com/microsoft/TypeScript/assets/132332843/e0ce5e9d-186a-42f4-8d03-d803673971ad">
This is the option that I disabled and I don't see any improvements. Here is how slow the autocomplete response is:

https://github.com/microsoft/TypeScript/assets/132332843/fe5d0dea-bd1a-4f6f-b784-daec48c5acd3

This is a biting issue for the developers in our team. Can you help us figure out the root cause for this?

**Comment by RyanCavanaugh** [comment]
> Can you help us figure out the root cause for this?

The problem is that you have 50,000 files being analyzed. You can figure out why this is the case with `tsc --explainFiles`. I can't tell you which files don't belong since I don't know anything about your project

**Comment by RyanCavanaugh** [comment]
This is the correct setting to turn off auto-imports:
<img width="413" alt="image" src="https://github.com/microsoft/TypeScript/assets/6685088/3f65a823-cc5b-4886-9dbf-93199dafc5fa">

**Comment by en-yash** [comment]
> The problem is that you have 50,000 files being analyzed. You can figure out why this is the case with tsc --explainFiles. I can't tell you which files don't belong since I don't know anything about your project

We have 50000 files in our repo as I stated above so I guess it is expected? Also `tsc --explainFiles` includes all the types from our `node_modules` and some custom typings that we add to the project which I think is the expected output of `tsc --explainFiles`? Please correct me if I am wrong

> The problem is that you have 50,000 files being analyzed
Also, since you mentioned this, does this mean tsserver is meant to be this slow for a project of this scale?

**Comment by RyanCavanaugh** [comment]
Just because you have 50,000 files on disk doesn't mean that they should all be loaded as part of any project. I assume you have some level of componentization (separate tsconfigs) already? tssever should only be loading the files that are needed for analysis of any given tsconfig file. There's probably a misconfiguration somewhere that's causing it to load more than that.

If your build is just one tsconfig with every file, then the first step would be to separate out your project into smaller parts.

**Comment by en-yash** [comment]
> This is the correct setting to turn off auto-imports:
I see. I don't think we want to disable auto imports as it is a vital feature that we use in VS Code

**Comment by en-yash** [comment]
> If your build is just one tsconfig with every file, then the first step would be to separate out your project into smaller parts.

We do have a similar structure where we have multiple packages inside a single monorepo. I ran` tsc --extendedDiagnostics` on the particular package to which this file belongs and here is the output:
```
Files:                         7826
Lines of Library:             29122
Lines of Definitions:        511953
Lines of TypeScript:         500288
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Identifiers:                1116830
Symbols:                    1743180
Types:                       520453
Instantiations:             2814240
Memory used:               1991395K
Assignability cache size:    274435
Identity cache size:          28314
Subtype cache size:           40357
Strict subtype cache size:    37887
I/O Read time:                1.09s
Parse time:                   2.28s
ResolveModule time:           1.50s
ResolveTypeReference time:    0.06s
Program time:                 5.39s
Bind time:                    1.03s
Check time:                  22.28s
transformTime time:          13.84s
commentTime time:             0.18s
I/O Write time:               1.08s
printTime time:              15.87s
Emit time:                   15.87s
Total time:                  44.57s
```

**Comment by grenganathan-atlassian** [comment]
@RyanCavanaugh In our base config, the `compilerOption.paths`  object has 2k keys and this base config is being extended by 700 tsconfigs in the repo. We reduced the number of paths on each of the package level tsconfigs to only have the paths that is required and we are seeing improvements in our auto completion times. Are the paths array processed during autocompletion in IDE?

**Comment by RyanCavanaugh** [comment]
Yes, since we have to know how to resolve modules in order to know what to show in the completion list
