### ISSUE TITLE
New files not recommended for automatic import.

### ISSUE THREAD

**Issue by BenMcLean981** [microsoft/TypeScript#56240]
### 🔎 Search Terms

TypeScript new files not recommended for import

### 🕗 Version & Regression Information

I am on 4.9.5, this has been around for at least a year before then.

### 💻 Code

**foo.spec.ts**

```
const foo = new Foo();
```

**foo.ts**

```
export class Foo {
  constructor() {
    console.log("Foo!");
  }
}
```

### 🙁 Actual behavior

Selecting the new Foo and prompting for imports does not suggest Foo.ts when Foo.ts is created after foo.spec.ts.

If foo.spec.ts is created after Foo.ts, then this works as expected.

### 🙂 Expected behavior

The order of file creations does not matter, auto-imports/intellisense should be able to find them.

### Additional information about the issue

I'm not certain that this is the right place for this issue. I suspect it's an issue with the tsserver because this happens in Webstorm and VSCode.

**Comment by RyanCavanaugh** [comment]
We need a full repro here - your tsconfig, packag.json, and other files' location and contents matters here
