### ISSUE TITLE
ts.createSourceFile adds parent to nodes when asked not to

### ISSUE THREAD

**Issue by kungfooman** [microsoft/TypeScript#56249]
### 🔎 Search Terms

createSourceFile, JSDoc, setParentNodes, parent

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, from 3.3.3 to 5.3.0

### 💻 Code

```js
const str = `
/** @type {number[]} */
const arr = [10, 20];
`;
const ast = ts.createSourceFile('repl.js', str, ts.ScriptTarget.Latest, false /*setParentNodes*/);
ast.statements[0].jsDoc[0].parent; // will show a parent
```

### 🙁 Actual behavior

`ast.statements[0].jsDoc[0].parent` is a node

### 🙂 Expected behavior

`ast.statements[0].jsDoc[0].parent` shouldn't be a node

**Comment by RyanCavanaugh** [comment]
Setting this param to true causes a second pass of the tree to fix up any parent pointers *not* set in the first pass. It's not a guarantee that there won't be any parent pointers (I'm not sure what anyone would do with that invariant in the first place) - the same way some nodes are constructed, the parent is already available.

**Comment by kungfooman** [comment]
> I'm not sure what anyone would do with that invariant in the first place

It happens to be nice for `JSON.stringify` (preventing circular references).

The naming is confusing, so it should have been `ensureParentNodes`?

**Comment by RyanCavanaugh** [comment]
I don't think it's confusing; this is this first anyone has ever asked about it in ~9 years of existence. There are many many more problems you'll have trying to `JSON.stringify` the AST nodes.

**Comment by kungfooman** [comment]
> There are many many more problems you'll have trying to `JSON.stringify` the AST nodes.

Not really, I tested with giant TS files and this works perfectly:

```js
  const ast = ts.createSourceFile('repl.ts', str, ts.ScriptTarget.Latest, false /*setParentNodes*/);
  const out = JSON.stringify(ast, function(name, val) {
    if (name === "parent") {
      return undefined; // remove
    }
    return val; // keep
  }, 2);
```

But yes, *nvm*.
