### ISSUE TITLE
Allow anonymous/dynamic override / implementation of method without the need for a declared subclass

### ISSUE THREAD

**Issue by ORESoftware** [microsoft/TypeScript#56245]
### 🔍 Search Terms

anonymous inline subclass abstract implementation override

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

This is a useful construct in any language.

Saw we have a class;

```typescript
abstract class Foo {
  abstract method1?(): void
}
```

or even more simply without abstract:

```typescript
 class Foo {
  method1?(): void
}
```

I want to be able to create a new instance of Foo, without having to declare a new class (thus more dynamic and generic), something like this:

```typescript

// bogus imaginary syntax:

const f = new Foo(){   
  method1(){
     // implement -or- override existing method declarartion
  }
}
```

the only way I know of doing this currently, is with abstract and this ugly syntax:

```typescript
const f = new (class extends Foo{
  method1(){
     // implement -or- override existing method declarartion
  }
})();
```

is that the only way? 

### 📃 Motivating Example

This is a useful construct in any language.
I have one SO question about it:
https://stackoverflow.com/questions/77380853/how-to-create-instance-of-a-class-without-extending-it-perse-but-override-a-me

### 💻 Use Cases

1. What do you want to use this for? wherever I can
3. What shortcomings exist with current approaches?  too verbose 
4. What workarounds are you using in the meantime?  the one mentioned

**Comment by jakebailey** [comment]
You checked:

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

But this is a runtime feature that doesn't exist in JavaScript, so wouldn't be added to TypeScript.
