### ISSUE TITLE
a new type to allow only instance of a class

### ISSUE THREAD

**Issue by robertIsaac** [microsoft/TypeScript#56248]
### 🔍 Search Terms

instance of class

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

add a way to enforce only instance of class to be passed and not any object that match the class
because this can break a lot of applications this should be behind a flag, or to have it as a utility like `OnlyInstance<ClassName>` that means only instance of this class to be passed

### 📃 Motivating Example

```
class Foo {
    foo = '';
}

class Bar {
    bar = 0;
}

function getNumber(value: Foo | Bar): number {
    if (value instanceof Bar) {
        return value.bar;
    } else {
        return value.foo.length;
    }
}

console.log(getNumber({bar: 1}));
```

this code will throw runtime error, because the runtime check `value instanceof Bar` will be false since the method is called with a generic object, but typescript currently think that `{bar: 1}` match with the class and let it go

### 💻 Use Cases

1. What do you want to use this for?
  to make typescript match the runtime, this can remove a lot of pain points
2. What shortcomings exist with current approaches?
  when you expect an instance of class, you can get an object that only match the class type
3. What workarounds are you using in the meantime?
  instead of using instanceof we have to use user defined type guards, which can be complicated and confusing in some cases + add more maintenance effort when the class structure change

**Comment by xiBread** [comment]
Duplicate of #29063

**Comment by MartinJohns** [comment]
That's why it's IMO best practice to always have at least one private property on your class, even if it's just a branding.

**Comment by robertIsaac** [comment]
> That's why it's IMO best practice to always have at least one private property on your class, even if it's just a branding.

but if it's private, how I will check for it in the type guard function?

**Comment by MartinJohns** [comment]
Having a private property makes the class nominally typed, not structurally. That means in order to create an instance you need to use the `new` operator, which means that subsequent checks using `instanceof` are safe.

**Comment by robertIsaac** [comment]
> Having a private property makes the class nominally typed, not structurally. That means in order to create an instance you need to use the `new` operator, which means that subsequent checks using `instanceof` are safe.

thank you, I tested it now and understood
I will close this issue then since there is a workaround and already proposed duplicate issue
