### ISSUE TITLE
`asserts` keyword with intersection type is not working

### ISSUE THREAD

**Issue by samchon** [microsoft/TypeScript#56256]
### 🔎 Search Terms

- asserts
- intersection

### 🕗 Version & Regression Information

Occurs since v3.7 update, the first update supporting the `asserts` statement.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwIYDOBwsAyjFJigOYAUVYSMAXHKgNYoQDuKAlK0LFYBOAyZjRBClWpwAZHGmUacAN4AoONrEI4tGAE8wwCHvHwAhAF5rcAOTLZ9vlp3uYACyg84KYNxwAKJQPlC09gCSKIzwmKJc8HhKMjQuANxu2lDAMEhQuBaZAL5AA

### 💻 Code

```ts
export function assertString(input: unknown): asserts input is string & string {
    if (typeof input !== 'string')
        throw new Error('Input is not a string');
    return input;
}
```

### 🙁 Actual behavior

It is possible to declare an `asserts` guard function with intersection return type. There's no error until that.

However, the intersection return type does not work, and just working as a `void` return type.

```bash
Type 'string' is not assignable to type 'void'.
```

### 🙂 Expected behavior

Hope the intersection return type to work.

**Comment by MartinJohns** [comment]
The type `string & string` is the same as `string`.

It's not clear what you actually want and how it should work. Assertion functions don't return anything. You're just declaring that whatever `input` is is of the type `string & string` (which is equal to `string`).

**Comment by samchon** [comment]
Got it, what I want was to making a function returning `(asserts input is T) & T`.

**Comment by MartinJohns** [comment]
That would be a feature request, not a bug report, and it already exists: #40562

Currently such functions are not possible.

**Comment by samchon** [comment]
Thanks for fast response. I should consider another way.
