### ISSUE TITLE
Default rest parameter names to destructuring names when of an anonymous tuple

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#56289]
### 🔍 Search Terms

default rest parameter name destructure anonymous tuple

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Right now, when calling a function with an inline destructured rest parameter whose type is an anonymous tuple, the inferred variable names will be auto-generated like `__0_0`:

```ts
function withPair(...[first, second]: [number, named: string]) { }

withPair(/* __0_0: number, named: string */ 0, "");
```

In cases where the tuple is destructured inline, how about any constant/static destructuring names being used as a fallback for anonymous tuple elements?

I.e.:

```ts
function withPair(...[first, second]: [number, named: string]) { }

withPair(/* first: number, named: string */ 0, "");
```

### 📃 Motivating Example

The pattern of immediately destructured rest parameters of a tuple is one that sometimes gets used for better type safety on parameters than generics or overloads. One downside, though, is that developers have to either explicitly add names to the tuple type _or_ suffer from poor auto-generated parameter hints.

A slightly more real-world example:

```ts
interface AppleInfo {
  color: "green" | "red";
}

interface BananaInfo {
  curvature: number;
}

type FruitAndInfo = ["apple", AppleInfo] | ["banana", BananaInfo];

function logFruitTuple(...[fruit, info]: FruitAndInfo) {
  switch (fruit) {
    case "apple":
      console.log(`My apple's color is ${info.color}.`);
      break;
    case "banana":
      console.log(`My banana's curvature is ${info.curvature}.`);
      break;
  }
}

logFruitTuple(/* __0_0: "apple", __0_1: AppleInfo */ "apple", { color: "red" });
```

With this suggested change, the parameter hints for `logFruitTuple` would instead be:

```ts
logFruitTuple(/* fruit: "apple", info: AppleInfo */ "apple", { color: "red" });
```

### 💻 Use Cases

This pattern of destructuring rest parameters of a tuple type allows for precise descriptions of type parameters. It can sometimes be preferable for types over:

* Function overloads: which allow for descriptions of different call signatures for a function, but the function's body doesn't apply type narrowing based on them ([function overloads playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIIAd0BsIEkQwD2yA3gFDKXIKFaFQBcyARAOZQQQjPIA+LHACbMA3GQC+ZMqEixEKAEJwQyuPiKkKVBAFcoANzhg9EJiB0BbAEbQxksjB0gEYYIRDI6rAGJQdwMAB5fWg6OEEAChg-AKZmOEwcZgAaZFAiJgxsPAJCAEomfUJgQTFHZ1d3T0IfGKCQqDDI6P8wOKtVFRS03KYlFRV1fMLi0ocnFzcPL19W4NDCcIitShbYlgTsnn5mDoG4FJWejLREnI1+ftUhsjzNKmQAZwB3AIQAC2QourvyB4eEHBHih4mdmAwjv9tO5HrQIAA6LwRAAGAFkAJ7ITY4ADkj2otHoaXxABISBF0sQgadskM8vCaHQoOJ4ci8mIoVCrBw4ABrDmcwHAlh7VTgyGCmFwxE1Zac+XINGY0UqPHUPSGYwcYnIMkU3JY-FXQa5em6AxGEws5ESqHs23-bkQPkCyiSewzOrzRqLSKgrapEgEplxdicbjIcTs5AAehjyECvKknrmDSaEV2nQOgeD9FDHC4PCjIlj8YAyu9CDosIJkNAoPQgA))
* Generic functions: which also can't always type narrow internally ([generic function playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIIAd0BsIEkQwD2yA3gFDKXIKFaFQBcyARAOZQQQjPIA+LHACbMA3GQC+ZMqEixEKAEJwQyuPiKkKVBAFcoANzhg9EJiB0BbAEbQxk6eGjwkydYQBi9d1B3AwmqmQ4TBwmDGw8AkIxQKtVFSYlFRU3OykYHRAEMGBCEGQ6Vm9fMABxLmhgBAAeYr9kCAAPSBBBAGdkAGsIAE9CGFcozyg6sAA+AAotShgfPyZRgBpp5FAiJjdh0YBtUYBdMgBKAKo2gHc-BAALZAnZkuPyQMCEODaUZmCI5gYV5+08m1aBAAHSFCYAAwAsj0giEIAByDo0OhQVYdAAkJAma2IbzQ8LchxBKPo4hBEMOMX+zysHDgnWp-1e7xYcWScB+fxpNBAQJwYMIrCmNNFyGhsPZqiR1D0hmMHHRyCxOKiQQ6SVURJJcqMJnJEO5-ypRtp9MZK0k9kKo3KIEqCAmn3hzEWpGotHoTDYHC4PHEVOQAHog8gAPKdKQ2uZlCpQKpOqUqV3u0mMFjsTjcZABkTB0MAZSuhB0WEEDSgUHoQA))

Thanks to @evangalen for noting this in https://twitter.com/EmilVanGalen/status/1719622053769216013!

**Comment by PrathamLalwani** [comment]
I think I can do this, would you recommend this for a beginner @RyanCavanaugh
