### ISSUE TITLE
TS2322: Type  () => void  is not assignable to type  Function in Typescript 5.2.2

### ISSUE THREAD

**Issue by sundial-dreams** [microsoft/TypeScript#56282]
### 🔎 Search Terms

TS2322
Type  () => void  is not assignable to type  Function 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions  5.2.2

### 💻 Code

```ts
// TS2322: Type  () => void  is not assignable to type  Function 
let c: Function = () => {};

console.log(c);
```

### 🙁 Actual behavior

// TS2322: Type  () => void  is not assignable to type  Function 

### 🙂 Expected behavior

no ts error

**Comment by appsforartists** [comment]
works fine:

https://www.typescriptlang.org/play?#code/DYUwLgBAxgXBBiBXAdlMBLA9siBeCAFAJR4B8EA3gL4DcAsAFBTYDOmoAdMJgOYFREaQA

(btw, that's why there's a playground - so you can share examples with people)
