### ISSUE TITLE
Properties with index signatures are lost when recuring between two types.

### ISSUE THREAD

**Issue by Griffork** [microsoft/TypeScript#56285]
### 🔎 Search Terms

"Index Signature", "Recursive", "Type Recursion"

### 🕗 Version & Regression Information

- This is a typing error
- This **did not change** between versions 3.3.3 (oldest I could test on playground) and 5.2.2
- This changed in commit or PR unknown
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `everything except the glossary`
- I was unable to test this on prior versions because I don't have them

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/FAguE8AcFMAIDMCWAnAzqAPAFQHywLywDeA2gNKyIB2sA1tOAPbyxYC6sAXK+WwL4BuYABtooWKGjoAjAEJuSNJiIBjABaJhAE26kqAQwC20bumTUA5m276q4PnxxDJMgsWCxPsdZp3EARGrQwsKM-tz+AO6MyNr+fMCCwBAwsKjQKoxUWth4hKQU1HQMzKwc3KAayDlYvDhJKXCVKDV5xOSUNPRMLOxcaRlZNXVJouIuoABM8gOZ2RiqGtq6JAbGpqDmVFY2dg5OyVJTbkQeXj7LAUEhYRHRsVrxic5QcPCMAK7IlbknHUXdUp9bi1MgcaAAD0k2VQsEYACMAFYZcQAfgQn2+amwdX6oP4QjGEiOAGYZu8vj9Fr4VmsTGlNpZrLBbPZHM5SSczp4Ln4iIFgqFwrAojE4glBEA

### 💻 Code

```ts
type first<T> = {[K in keyof T] : T[K]};
let test1!: first<{child: {[name: string]: any}}>;
test1 = {
    child: {"hello": "world"}
};
type second<T> = {[K in keyof T] : third<T[K]>};
type third<T> = {[K in keyof T] : second<T[K]>};
let test2!: second<{child: {[name: string]: any}}>;
test2 = {
    child: {"hello": "world"}
};
type fourth<T> = {[K in keyof T] : T[K] extends object ? fourth<T[K]> : T[K]};
let test3!: fourth<{child: {[name: string]: any}}>;
test3 = {
    child: {"hello": "world"}
};
```

### 🙁 Actual behavior

Trying to assign the value to `test2` gives the following error:
Type 'string' is not assignable to type 'second<any>'.

### 🙂 Expected behavior

All three typing scenarios (first, second and third, and fourth) should not error.

**Comment by RyanCavanaugh** [comment]
This seems correct? The only legal inhabitant of `"hello":` is a `second<third<second<third<second< [infinite...]<string>>`, which `string` isn't.

**Comment by Griffork** [comment]
Why does `second<third<{[string]: any}>>` not work but `fourth<fourth<{[string]: any}>>` work? They should be identical?

**Comment by RyanCavanaugh** [comment]
These type definitions are pretty different; it's not immediately obvious to me (or apparently to TS) that they should be identical

**Comment by Griffork** [comment]
Ahh. My bad. I didn't realise that the `extends object ? ` check was somehow converting `{[name: string]: any}` into `{}`. That's probably because any maps onto object.

This was my attempt to simplify into a test case a problem I was running into with more structured types, but I ended up rewriting the more complex types to function and I still don't know why it wasn't working the first time.
