### ISSUE TITLE
Why is pageYOffset marked as deprecated? 

### ISSUE THREAD

**Issue by chandraaditya** [microsoft/TypeScript#56308]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

`scrollY` is an alias of `pageYOffset`, but there's no documentation anywhere else (as far as I'm aware) that `pageYOffset` is deprecated, but it is marked as deprecated in the definitions [here](https://github.com/microsoft/TypeScript/blob/d2fdf851cc630d812b7b336a43cc1f363ba25083/src/lib/dom.generated.d.ts#L25658C40-L25658C40) and [here](https://github.com/microsoft/TypeScript/blob/d2fdf851cc630d812b7b336a43cc1f363ba25083/src/lib/dom.generated.d.ts#L27263)

References to `pageYOffset` and `scrollY`:
https://developer.mozilla.org/en-US/docs/web/api/window/pageyoffset
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY

The main issue I am having with this is that IntelliJ uses these definitions in the IDE and so it's being marked as deprecated [link to issue](https://youtrack.jetbrains.com/issue/WEB-55890/wrong-deprecated-warning-for-window.pageXoffset-and-window.pageYoffset).

**Comment by jakebailey** [comment]
This sounds like a question for https://github.com/microsoft/TypeScript-DOM-lib-generator.

**Comment by jcalz** [comment]
This should probably be moved there.  Looks like https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1082 was responsible for this.

**Comment by chandraaditya** [comment]
@jcalz @jakebailey thank you for letting me know, I moved the issue there.
