### ISSUE TITLE
`tsc` incorrectly simplifies declaration files

### ISSUE THREAD

**Issue by etcd** [microsoft/TypeScript#56302]
### 🔎 Search Terms

"declaration", "undefined", "type", "inference", "union", "arrow", "function"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried. I tested from typescript version 3.5.3 to 5.2.2.

### ⏯ Playground Link

https://github.com/etcd/tsc-arrow-fn-declarations-bug

### 💻 Code

This code:

```ts
export const map = <I, O>(i: I | undefined, fn: (_: I) => O): O | undefined => {
  if (i === undefined) {
    return undefined;
  }

  return fn(i);
};

export function map2<I, O>(i: I | undefined, fn: (_: I) => O): O | undefined {
  if (i === undefined) {
    return undefined;
  }

  return fn(i);
}
```

produces two functionally different declaration types:

```ts
export declare const map: <I, O>(i: I, fn: (_: I) => O) => O;

export declare function map2<I, O>(
  i: I | undefined,
  fn: (_: I) => O
): O | undefined;
```

with the command:

```bash
tsc src/*.ts --outdir build/ --allowSyntheticDefaultImports --declaration --sourceMap
```

### 🙁 Actual behavior

The generated type for the function written in arrow notation (`map`) incorrectly simplifies types `X | undefined` into `X` when it shouldn't. 

### 🙂 Expected behavior

The expected signature is what was generated for the function written in function notation (`map2`), as shown above.

### Additional information about the issue

This bug easily reproduces with my demonstration project. I could not get the playground to generate the incorrect `d.ts` types, and I am not sure why.

**Comment by MartinJohns** [comment]
You need to enable `strictNullChecks`, otherwise the type `undefined` does not exist.

**Comment by fatcerberus** [comment]
It is kind of interesting that the `undefined`s are preserved in the second case, but yeah, without `strictNullChecks` `T | undefined` is just the same as `T` and the compiler will treat them interchangeably.

To the OP - Since I noticed that your repro includes a `tsconfig.json` with `strict: true` and this is a *very* common pitfall, I'll note that passing filenames directly to `tsc` causes any tsconfig you have to be ignored unless you also use the `--project` option.

**Comment by nmain** [comment]
> It is kind of interesting that the undefineds are preserved in the second case

The first one requires a type inference pass to determine the type of `map`, where as the second one can just copy out the type verbatim.  The inference pass causes the non-strict rules to be applied and change the type.  [Playground example showing how an arrow function without inference behaves the same as a plain function](https://www.typescriptlang.org/play?strict=false&strictNullChecks=false#code/KYDwDg9gTgLgBAYwgOwM7wLYEMxwLxwA8AkgDRwDyAfABQCWAXHMXAD5wCuyAJsAGZ1kwbuT7ImNAPpNiASnxVKsphTace-QcIVwA3gCg4cOnzj18eAl14Ch3eQaNGowGByjJ1NrdwDchuABffQCXNw84MXpZf0D-fVBIWEiuBBg6FDhsMAAmEnJqehk1a007UXEzaWZ5PEUKZUoSjVttR2NTc0srFp8HAOdXd09S1r8A4NChiKi6GP1JxOh4JDRMHABmJnzKWkZmZu9yyMqpGVr6i6b2UZ98IjJdooOb3uOxCWq5HQaVQ7LtHU9AETGY6BYekdhP0nHAwsMvADxkZJoNwp5ZvM4vogA).
