### ISSUE TITLE
Extending a generic parameter of unknown breaks the compiler when providing an object with extra fields for the parameter

### ISSUE THREAD

**Issue by SteakOvercooked** [microsoft/TypeScript#56317]
### 🔎 Search Terms

extending generics with unknown

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/C4TwDgpgBAwg9gO2AJzgGzRZAeAagGigFEA+KAXigG8AoKKOAawC4oAKANwEM0BXCVrgCUFMhzgBLACYBuOlCzJWbRXCXER5MZNk0AvjRoQAHmDXAooSFADqE4AAsAggGcQCAMZ5CpCtXkSLgDykAisAEZw6BBcCHL0Hogo6Jjq8EioGFjexCRyenI0iQguFgDu9s5unn7YAAoKxsAQCFIutpWu7l68CIwIcGUIhL39gwgkJGzyALZwUjzKYKhgLqx1mtrSNJv+9AD0+1BScFAucDMQjhIIAOZQFY6WDtBzC2j6hVbQALLzPHUVu1KHZHF1PNgELwZuEsIRSsgbrcyAAyaiWeyYVgIpEyKAFQzFUpQP7vPxsZZwVasUkAoG7KgEoqIYlcaoeWloPyPKrdNicoRyIA

### 💻 Code

```ts
type Controller<V, E> = {
  ok: (value: V) => void;
  err: (error: E) => void;
}

export type WithAsync<V, E> = {
  isOpen: boolean;
  controller: Controller<V, E>;
};

const withAsync = <P extends WithAsync<unknown, unknown>>(
  modal: (props: P) => void
) => {
  // do something with the modal
};

type ModalProps = WithAsync<number, string> & { title: string; };

const Modal = (props: ModalProps) => {};

const asyncModal = withAsync(Modal);
```

### 🙁 Actual behavior

Compiler fails with the message: `Property 'title' is missing in type 'WithAsync<unknown, unknown>' but required in type '{ title: string; }'.`

### 🙂 Expected behavior

No error message

### Additional information about the issue

If `& { title: string; }` part gets removed it compiles. If the constraint of `P` is `extends WithAsync<number, string>` it compiles. It also compiles with `any` instead of `unknown`, but i do not want to resort to `any`. Why does adding an additional field break the types?

**Comment by jcalz** [comment]
Functions are contravariant in their parameter types.  This is working as intended.

**Comment by SteakOvercooked** [comment]
Thanks for the quick answer. It helped me understand what to google for!
