### ISSUE TITLE
Visual Studio: Please provide a SonarQube plugin for TypeScript

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#5632]
The Visual Studio tools team have developed a  [SonarQube](http://www.sonarqube.org/) plugin [for C#](http://blogs.msdn.com/b/visualstudioalm/archive/2015/08/24/build-tasks-for-sonarqube-analysis.aspx).

This is a request to integrate TypeScript as a supported language. 

There has been an [attempt on this already](http://pablissimo.com/647/sonarqube-typescript-plugin), but in the authors own words the plugin is 'not even alpha-level yet '.

This would be a way to integrate TSLint into Visual Studio, so that warnings are available on build.

Furthermore, SonarQube offers additional features, such as incremental technical debt analysis (i.e. "only warn when the code I write has errors - not for the whole solution"). This kind of analysis is useful for incrementally converting a solution.

**Comment by mhegazy** [comment]
This would out of the scope for the TypeScript project. We would love to help as much as possible. for instance, if there are specific API's needed in the services layer we would be open to adding them. but i do not think the core team can take on such plugin.

**Comment by NoelAbrahams** [comment]
Okay, understood. I've created a [user voice item](http://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/10679553-please-provide-a-sonarqube-plugin-for-typescript) for this. Hopefully it will get picked up by the VS tools team.

**Comment by atulsureka** [comment]
Is there any update on this. Any plugin for type script which works with SonarQube?

Atul
