### ISSUE TITLE
[bug] class-factory mixins started causing error with presence of mapped types

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#56330]
### 🔎 Search Terms

site:github.com typescript class-factory mixins breaking mapped types

### 🕗 Version & Regression Information

- This changed between versions **4.8.4** and **4.9.5**
- This changed in commit or PR _______

### ⏯ Playground Link

[playground with TS 5.3.0-beta](https://www.typescriptlang.org/play?target=99&jsx=0&noImplicitOverride=true&ts=5.3.0-beta#code/KYDwDg9gTgLgBDAnmYcDCEB2BnGUCuAxjNADwAqcAvHBAEYBWwxANHAIJygzCYAm2OAENMiANoBdasNGS2AZRhCYAS0LSA3gF8AfNIAUmYAHc4+gHSWhALg4BKanvIOAZHEXK1AWABQoSLAIyKjsdLhQQsQYOHhEJFAU0vRMrBxcIDz8giLiUjQ5cu5Kquo02no0+kJheJHwRqYWVrbsDlROrr4AkB4lvr5IKHAAogA2wAC2vDDkwexQEYjkEACSMfOLidy8AuhY4XHQkhVwGr5wF3AA9FdwAApqANa0mKOICAAWqJj4E3TAUDgj2AiEEVQWQneADchKN8MBsGxMBB4EIIe8pjAPhBdiI+HAwFAIChYCoEXZzOdLmIANJwFSYIEgiAAMzg5AktjWuBEhGAsxQFDEPz+ALgbhpEh0vi0A2CHHRADVYfDsFsMjtsrIpdJyMLfv9AW5gYhWeyJHKhmNJtMBQj1ZldtEDsQjjqaBtIcq4fbrVNMDM5ujltyYJ7EBQdNKfL5-NB4Cz8JhiCosCMWSzmDBE6MHZq9jECK7AQAfDg1CJRfaxYs6fQAISE2GAtmcp26UGAMHwUEZhFGTcEwwzWZz6UdgkbzdOsp8s98-cHcAAYhAIO2fJc4ABzLu0MIAqHAPgAeUYWf0dlsySzG63W6xRNMDXZwWGC2g+gABioJmBRvSjLYPgdCLtg2BfnYVIXPOm6XAA+vBLLQMYaJ8MedxEmA2CXrY+gmmaWIqNgYgAOT0M2UBHqe57EKREh2JId73hcnbdr2cCSNBcCzrBYGTk2qDbFkK5rsxFzAOM-owAAhLYfq2sEaoAEpdj2mB2qQREkaRnYAI74ConZ8ApAZ2vRUb9D4XT6YZxmmYGKCXhuXQ2WpHFiA5FrWbBW4QEeCwqOhO57hRh7HmeKQwM5ZxwSxbHqZ8xHmJJNoBtxvFWfxcAAOrQI82DLgyQkaiJU6oLFfkBVAQWoLZRnHg5doxdxW4JR5AAS5AALIADJeRlMpZQO4EjB+gLCbsw6ZsQOYNoJDiVZc-kAjVwX1fZUmKU5i2tZc7WMmIXV9QNcU8TKQA)

### 💻 Code

```ts repro
export type Constructor<T = object, A extends any[] = any[], Static = {}> = (new (...a: A) => T) & Static
export type AbstractConstructor<T = object, A extends any[] = any[], Static = {}> = (abstract new (...a: A) => T) &
	Static

type ElementTypeArrayToInstArray<T extends Constructor[]> = {
    // Pick only the number keys (array values, not array methods and properties).
    [K in keyof T]: InstanceType<T[number & K]>
}
type ArrayValues<T extends any[]> = T[number & keyof T]
type ElementTypes<T extends Constructor[]> = ArrayValues<ElementTypeArrayToInstArray<T>>

export function Effectful<T extends Constructor | AbstractConstructor>(Base: T) {
	return class Effectful extends Base {}
}

class Foo {
    get observedObject(): object {
        throw new TypeError(`impl in subclass`)
    }

    __forwardedProps(): (keyof this['observedObject'])[] {
        return []
    }
}

class Base extends Foo {
    element!: ElementTypes<ReturnType<this['requiredElementType']>>

	requiredElementType() {
		return [Element]
	}

    override get observedObject() {
        return this.element
    }
}

class WorksFine extends Base {
    override requiredElementType() {
        return [HTMLElement]
    }
}

class Error extends Effectful(Base) { // <--------------- ERROR
    override requiredElementType() {
        return [HTMLElement]
    }
}
```

### 🙁 Actual behavior

An error started happening when putting an (an even empty) class-factory mixin class in between subclass and base class.

### 🙂 Expected behavior

There should be no error.

### Additional information about the issue

There's no error in 4.8.4:

[playground with TS 4.8.4](https://www.typescriptlang.org/play?target=99&jsx=0&noImplicitOverride=true&ts=4.8.4#code/KYDwDg9gTgLgBDAnmYcDCEB2BnGUCuAxjNADwAqcAvHBAEYBWwxANHAIJygzCYAm2OAENMiANoBdasNGS2AZRhCYAS0LSA3gF8AfNIAUmYAHc4+gHSWhALg4BKanvIOAZHEXK1AWABQoSLAIyKjsdLhQQsQYOHhEJFAU0vRMrBxcIDz8giLiUjQ5cu5Kquo02no0+kJheJHwRqYWVrbsDlROrr4AkB4lvr5IKHAAogA2wAC2vDDkwexQEYjkEACSMfOLidy8AuhY4XHQkhVwGr5wF3AA9FdwAApqANa0mKOICAAWqJj4E3TAUDgj2AiEEVQWQneADchKN8MBsGxMBB4EIIe8pjAPhBdiI+HAwFAIChYCoEXZzOdLmIANJwFSYIEgiAAMzg5AktjWuBEhGAsxQFDEPz+ALgbhpEh0vi0A2CHHRADVYfDsFsMjtsrIpdJyMLfv9AW5gYhWeyJHKhmNJtMBQj1ZldtEDsQjjqaBtIcq4fbrVNMDM5ujltyYJ7EBQdNKfL5-NB4Cz8JhiCosCMWSzmDBE6MHZq9jECK7AQAfDg1CJRfaxYs6fQAISE2GAtmcp26UGAMHwUEZhFGTcEwwzWZz6UdgkbzdOsp8s98-cHcAAYhAIO2fJc4ABzLu0MIAqHAPgAeUYWf0dlsySzG63W6xRNMDXZwWGC2g+gABioJmBRvSjLYPgdCLtg2BfnYVIXPOm6XAA+vBLLQMYaJ8MedxEmA2CXrY+gmmaWIqNgYgAOT0M2UBHqe57EKREh2JId73hcnbdr2cCSNBcCzrBYGTk2qDbFkK5rsxFzAOM-owAAhLYfq2sEaoAEpdj2mB2qQREkaRnYAI74ConZ8ApAZ2vRUb9D4XT6YZxmmYGKCXhuXQ2WpHFiA5FrWbBW4QEeCwqOhO57hRh7HmeKQwM5ZxwSxbHqZ8xHmJJNoBtxvFWfxcAAOrQI82DLgyQkaiJU6oLFfkBVAQWoLZRnHg5doxdxW4JR5AAS5AALIADJeRlMpZQO4EjB+gLCbsw6ZsQOYNoJDiVZc-kAjVwX1fZUmKU5i2tZc7WMmIXV9QNcU8TKQA)

The error exists in 4.9.5:

[playground with TS 4.9.5](https://www.typescriptlang.org/play?target=99&jsx=0&noImplicitOverride=true&ts=4.9.5#code/KYDwDg9gTgLgBDAnmYcDCEB2BnGUCuAxjNADwAqcAvHBAEYBWwxANHAIJygzCYAm2OAENMiANoBdasNGS2AZRhCYAS0LSA3gF8AfNIAUmYAHc4+gHSWhALg4BKanvIOAZHEXK1AWABQoSLAIyKjsdLhQQsQYOHhEJFAU0vRMrBxcIDz8giLiUjQ5cu5Kquo02no0+kJheJHwRqYWVrbsDlROrr4AkB4lvr5IKHAAogA2wAC2vDDkwexQEYjkEACSMfOLidy8AuhY4XHQkhVwGr5wF3AA9FdwAApqANa0mKOICAAWqJj4E3TAUDgj2AiEEVQWQneADchKN8MBsGxMBB4EIIe8pjAPhBdiI+HAwFAIChYCoEXZzOdLmIANJwFSYIEgiAAMzg5AktjWuBEhGAsxQFDEPz+ALgbhpEh0vi0A2CHHRADVYfDsFsMjtsrIpdJyMLfv9AW5gYhWeyJHKhmNJtMBQj1ZldtEDsQjjqaBtIcq4fbrVNMDM5ujltyYJ7EBQdNKfL5-NB4Cz8JhiCosCMWSzmDBE6MHZq9jECK7AQAfDg1CJRfaxYs6fQAISE2GAtmcp26UGAMHwUEZhFGTcEwwzWZz6UdgkbzdOsp8s98-cHcAAYhAIO2fJc4ABzLu0MIAqHAPgAeUYWf0dlsySzG63W6xRNMDXZwWGC2g+gABioJmBRvSjLYPgdCLtg2BfnYVIXPOm6XAA+vBLLQMYaJ8MedxEmA2CXrY+gmmaWIqNgYgAOT0M2UBHqe57EKREh2JId73hcnbdr2cCSNBcCzrBYGTk2qDbFkK5rsxFzAOM-owAAhLYfq2sEaoAEpdj2mB2qQREkaRnYAI74ConZ8ApAZ2vRUb9D4XT6YZxmmYGKCXhuXQ2WpHFiA5FrWbBW4QEeCwqOhO57hRh7HmeKQwM5ZxwSxbHqZ8xHmJJNoBtxvFWfxcAAOrQI82DLgyQkaiJU6oLFfkBVAQWoLZRnHg5doxdxW4JR5AAS5AALIADJeRlMpZQO4EjB+gLCbsw6ZsQOYNoJDiVZc-kAjVwX1fZUmKU5i2tZc7WMmIXV9QNcU8TKQA)

**Comment by trusktr** [comment]
A workaround is to avoid the mapped type, and instead write out the result types manually (a little less DRY, and prone to human-error) like so:

[playground with TS 4.9.5](https://www.typescriptlang.org/play?target=99&jsx=0&noImplicitOverride=true&ts=4.9.5#code/KYDwDg9gTgLgBDAnmYcDCEB2BnGUCuAxjNADwAqcAvHBAEYBWwxANHAIJygzCYAm2OAENMiANoBdasNGS2AZRhCYAS0LSA3gF8AfNIAUmYAHc4+gHSWhALg4BKanvIOAZHEXK1AWABQoSLAIyKjsdLhQQsQYOHhEJFAU0vRMrBxcIDz8giLiUjQ5cu5Kquo02no0+kJheJHwRqYWVrbsDlROrr4AkB4lvr7+0PAAZviYxCpYcACiw8PMMKMANoncvALoWOFx0HAAPhw1EVFbscTQOvoAQkLYwLbOcBrdUMAw+FCYcIRLt4Kz82Iy3SmQ2NzuTy0vihPl8Pz+cAAYhAIE9fHAMXAAOZvWhhYBQABuwD4AHlGAt9HZbMkFmifJjGQgABZQCCmBpwcjBaZQNlQfQAAxUAFswEs4Covth8HR4dhsIK7OjMTCVRiAPoa4bQYxCKB8EkABTZYGwVNs+gA1sBEBBhiyVNgxAByeh3Ikk8kpGAuiR2ST0pmY17vT5wSTquAwtU+eWCcGoNZZJEooOYgD0Ga4S2AIt4MAAhLZprn85gYNyUNhSAAlN4fTBV4CkGDMp2u14AR3wKlefFLeYLzb9Oh0UeAZYLxZmU4r-R8XW7vf7g-LleCVPpXSXDfDYjXBYk3VjjIgxL5KkN2Nx7oJxLJFOIW+eDODcFDjcd2HMk6H87fDEYwXeM4AAdWgK1sERKUkwydYE1uVBX0ZQ14VeHN-xgWwAAlyAAWQAGUPACo3PAkoCvVBlz7EkSI3FAXyjRlP33PCiPo49AOjaEQN+BUZj5aAAElsAAcSwODQX+OYFmWa4kIcFDMTQ34ML-ddcII4i5xgKMyIvSjrxo1ddObJjuJYvcvjEdidKwrjGRjIA)


```ts
class Base extends Foo {
    // element!: ElementTypes<ReturnType<this['requiredElementType']>> // <--- instead of this
    element!: Element // <---------- do this

	requiredElementType() {
		return [Element]
	}

    override get observedObject() {
        return this.element
    }
}

class WorksFine extends Base {
    declare element: HTMLElement // <---------- add this

    override requiredElementType() {
        return [HTMLElement]
    }
}

class ErrorIsGone extends Effectful(Base) {
    declare element: HTMLElement // <---------- add this
    
    override requiredElementType() {
        return [HTMLElement]
    }
}
```

**Comment by trusktr** [comment]
ts repro

**Comment by jakebailey** [comment]
@typescript-bot bisect good v4.8.4 bad v4.9.5

**Comment by RyanCavanaugh** [comment]
The error message is correct; the subclass is not a subtype of its base type:
```ts
class MyError extends Effectful(Base) {
    override requiredElementType() {
        return [HTMLElement]
    }
}

const pretend = Effectful(Base);
const pretendInstance = new pretend();
// Cannot contain 'accessKey'
const m = pretendInstance.__forwardedProps();

const mine = new MyError();
// Can contain 'accessKey'
const e = mine.__forwardedProps();
```
