### ISSUE TITLE
JSX attribute key ignores special characters for wrapping as string

### ISSUE THREAD

**Issue by idoros** [Microsoft/TypeScript#5634]
```jsx
var x = <div xx-y="val"></div>;
var y = <div x-y="val"></div>;
var z = <div longattrr="val"></div>;
```
is transpiled to:
```jsx
var x = React.createElement("div", {"xx-y": "val"});
var y = React.createElement("div", {x-y: "val"}); // SYNTAX ERROR 
var z = React.createElement("div", {"longattrr": "val"});
```

It seems typescript decides to wrap option keys as string only by the length of the attribute key (4 characters) and not by the characters that might break javascript.

**Comment by RyanCavanaugh** [comment]
I don't even want to explain the embarrassingly wrong regex I was using here...
