### ISSUE TITLE
Example incorrect

### ISSUE THREAD

**Issue by saimatam** [microsoft/TypeScript#56346]
Documentation

File: packages/documentation/copy/en/reference/Iterators and Generators.md

The example code to illustrate 'for of'... is not compiling even if the target is specified as ES2022.

`let pets = new Set(["Cat", "Dog", "Hamster"]);
pets["species"] = "mammals";
for (let pet in pets) {
    console.log(pet); // "species"
}

for (let pet of pets) {
    console.log(pet); // "Cat", "Dog", "Hamster"
}`

The error in line: 2 
`for.ts:2:1 - error TS7053: Element implicitly has an 'any' type because expression of type '"species"' can't be used to index type 'Set<string>'.
  Property 'species' does not exist on type 'Set<string>'.

2 pets["species"] = "mammals";
  ~~~~~~~~~~~~~~~
`

**Comment by fatcerberus** [comment]
Where is this file?  I don’t see such a file anywhere in the TS repo.  At any rate, that’s valid JS code, illustrating the difference in runtime behavior between the two `for` loop types.  That TS considers it a type error is irrelevant (in fact it’s a good thing that it doesn’t compile, IMO).

**Comment by MartinJohns** [comment]
@fatcerberus He/she just got the wrong repository. The file is here: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Iterators%20and%20Generators.md

And the code works fine with `noImplicitAny` disabled.

**Comment by RyanCavanaugh** [comment]
The code example is only there to demonstrate runtime differences in edge cases.
