### ISSUE TITLE
Incorrect type inference when using short if and empty array

### ISSUE THREAD

**Issue by cipriancaba** [microsoft/TypeScript#56342]
### 🔎 Search Terms

inference empty array short if shorthand

### 🕗 Version & Regression Information

Type inference not working correctly

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=9#code/DYUwLgBCCMELwQNoCgJogb1enBDAXBAEQDSAogJpHZoC+ANBDRAHRsAUzOYATgK4gIAfiY4cKMZMxcpeQqUrVZOWjLQBdUVMKJ1ASmbrkyUJBAAmeBF4DhSDBALFyVCLU06jJ8FADMVm0ERRAcnBVdcAGdnRTcPJHUgA

### 💻 Code

```ts
let e1 = [
    {
        a: "KEY"
    }, 
    ...(
        true ? 
        [
            {
                a: "KEY"
            }
        ] 
        : [])
    ]

let e2 = true ? [{ a: "KEY" }] : []

let e3 = true ? [{ a: "KEY" as "KEY" }] : []
```

### 🙁 Actual behavior

e1 and e2 are arrays of type `{ a: string }[]` instead of `{ a: "KEY` }[]`
e3 is inferred correctly as { a: "KEY` }[]

### 🙂 Expected behavior

e1, e2 and e3 are arrays of type `{ a: "KEY` }[]`

**Comment by Andarist** [comment]
This is working as intended. Strings are usually widened since you'd expect this to work:
```ts
const e4 = [{ a: "KEY" }]
e4.a = "OTHER" // should work by default
```

Your third example is different because you assure the compiler that you want that literal there by using the `as` assertion.

**Comment by MartinJohns** [comment]
And the if/else makes absolutely no difference here.

**Comment by cipriancaba** [comment]
I can see how that might make sense. But what about the e1 example? There is already an element in the array that defines the shape of the array, I add another one, shouldn't that be enough to not want to widen to string?

**Comment by MartinJohns** [comment]
Because this should work:

```typescript
e1.push({ a: "another key" });
```

**Comment by cipriancaba** [comment]
Ok, I guess it makes sense for most use-cases, and my case is more specific. I will just use the `as` casting, thanks for clarifying 👍

**Comment by fatcerberus** [comment]
@cipriancaba If you’re concerned about the safety of `as "foo"`, you can use `as const` instead—that’s what it’s for.  You can even use it on entire object literals to prevent widening for all properties.

**Comment by cipriancaba** [comment]
Thanks for clarifying, this is what i ended up doing
