### ISSUE TITLE
Duplicate property error when a computed property names come from an object destructuring with the same default value 

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#56341]
### 🔎 Search Terms

"An object literal cannot have multiple properties with the same name" object destructure destructuring computed

### 🕗 Version & Regression Information

- This changed between versions 5.0.4 and 5.1.6

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/MYGwhgzhAEAqCmEAu0DeAoa0AOAnA9thAIQBcaAHgPznK4CWAdgOYA00AnjdHU8wL4BuTNAC28JAAt8AEwAUASjQiswfI2RpoFaAF5oAcgPsOewwf5mp9CADo8hCMKxZcEgK65Gyly4DaFAC65ACMrCr+HMHQAEzhvkIi-OjJ6ABm7ozASPTq0ABGYLhyDkTkqNS0SAwsJty8LPxKGL5qGiio2mZGJt0WZqVOEW5Int4tvtAB0WERWH5R5HERiakZWTl5afj4cp06+j2cffzllTzVfHVVNQLNIiNjPv5BofGR0ctYq+hAA

### 💻 Code

```ts
function bar(props: {x?: string, y?: string}) {
    const { x = '', y = ''} = props;
    return {
      [x]: 1,
      [y]: 2,
    };
}
```

```ts
function foo({ x = '', y = ''}: {x?: string, y?: string}) {
  return {
    [x]: 1,
    [y]: 2,
  };
}
```

### 🙁 Actual behavior

In the first example - the `[y]: 2` line reports `An object literal cannot have multiple properties with the same name.(1117)`

In the second example - the `[y]: 2` line reports nothing.

### 🙂 Expected behavior

There should be no reports as both variables are typed as `string`.

### Additional information about the issue

The above code works fine in [5.0.4](https://www.typescriptlang.org/play?ts=5.0.4#code/MYGwhgzhAEAqCmEAu0DeAoa0AOAnA9thAIQBcaAHgPznK4CWAdgOYA00AnjdHU8wL4BuTNAC28JAAt8AEwAUASjQiswfI2RpoFaAF5oAcgPsOewwf5mp9CADo8hCMKxZcEgK65Gyly4DaFAC65ACMrCr+HMHQAEzhvkIi-OjJ6ABm7ozASPTq0ABGYLhyDkTkqNS0SAwsJty8LPxKGL5qGiio2mZGJt0WZqVOEW5Int4tvtAB0WERWH5R5HERiakZWTl5afj4cp06+j2cffzllTzVfHVVNQLNIiNjPv5BofGR0ctYq+hAA), but fails in both [5.1.6](https://www.typescriptlang.org/play?ts=5.1.6#code/MYGwhgzhAEAqCmEAu0DeAoa0AOAnA9thAIQBcaAHgPznK4CWAdgOYA00AnjdHU8wL4BuTNAC28JAAt8AEwAUASjQiswfI2RpoFaAF5oAcgPsOewwf5mp9CADo8hCMKxZcEgK65Gyly4DaFAC65ACMrCr+HMHQAEzhvkIi-OjJ6ABm7ozASPTq0ABGYLhyDkTkqNS0SAwsJty8LPxKGL5qGiio2mZGJt0WZqVOEW5Int4tvtAB0WERWH5R5HERiakZWTl5afj4cp06+j2cffzllTzVfHVVNQLNIiNjPv5BofGR0ctYq+hAA) and [5.2.2](https://www.typescriptlang.org/play?ts=5.2.2#code/MYGwhgzhAEAqCmEAu0DeAoa0AOAnA9thAIQBcaAHgPznK4CWAdgOYA00AnjdHU8wL4BuTNAC28JAAt8AEwAUASjQiswfI2RpoFaAF5oAcgPsOewwf5mp9CADo8hCMKxZcEgK65Gyly4DaFAC65ACMrCr+HMHQAEzhvkIi-OjJ6ABm7ozASPTq0ABGYLhyDkTkqNS0SAwsJty8LPxKGL5qGiio2mZGJt0WZqVOEW5Int4tvtAB0WERWH5R5HERiakZWTl5afj4cp06+j2cffzllTzVfHVVNQLNIiNjPv5BofGR0ctYq+hAA).

It looks like it's been fixed in [5.3.0-beta](https://www.typescriptlang.org/play?ts=5.3.0-beta#code/MYGwhgzhAEAqCmEAu0DeAoa0AOAnA9thAIQBcaAHgPznK4CWAdgOYA00AnjdHU8wL4BuTNAC28JAAt8AEwAUASjQiswfI2RpoFaAF5oAcgPsOewwf5mp9CADo8hCMKxZcEgK65Gyly4DaFAC65ACMrCr+HMHQAEzhvkIi-OjJ6ABm7ozASPTq0ABGYLhyDkTkqNS0SAwsJty8LPxKGL5qGiio2mZGJt0WZqVOEW5Int4tvtAB0WERWH5R5HERiakZWTl5afj4cp06+j2cffzllTzVfHVVNQLNIiNjPv5BofGR0ctYq+hAA).

I figured I should file this at least for bookkeeping purposes and just as an FYI considering i don't see any other issues filed about this particular error. Feel free to close this as fixed.

**Comment by Andarist** [comment]
This got fixed by https://github.com/microsoft/TypeScript/pull/55193 but the fix wasn't really fixing this case so it's worth adding some extra test coverage based on this issue here.
