### ISSUE TITLE
Contravariant inference breaks on generic conditional types.

### ISSUE THREAD

**Issue by rzvc** [microsoft/TypeScript#56344]
### 🔎 Search Terms

mapped types templates contravariant inference

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.3.
- This is the behavior in every version I tried.

### ⏯ Playground Link

https://tsplay.dev/NVrBBN

### 💻 Code

```ts
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never;

function test<T>(value: T)
{
    type I = UnionToIntersection<
          { a: number }
        | { b: number }
        | (T extends number ? { c: T } : { c: T })
    >;

    let i : I = null as any;

    i.a = 1;    // With c defined, i.a is available only up to version 4.1.5. Afterwards, it breaks.
    i.b = 1;    // Same for i.b.
    i.c = value;
}
```

### 🙁 Actual behavior

The non-generic dependent properties were not available.

### 🙂 Expected behavior

At least the non-generic dependent properties to be available. Ideally, `c` should have been available too and `value` should have been assignable to it, but that's less "expected" than the first part.

### Additional information about the issue

It completely breaks more complex mapped types that used to work up to 4.1.5. The conditional generic type was still not available, but it was better than nothing.

If the previous behaviour cannot be restored, perhaps there's a way to detect that you're dealing with a generic type which will be deferred, and allow the programmer to decide what to do with it?

**Comment by jcalz** [comment]
You might consider coming up with an example that doesn't depend on `UnionToIntersection` since that tends to get issues closed: https://github.com/microsoft/TypeScript/issues/43077#issuecomment-790758767.  Can you reproduce the basic issue with a less problematic use of contravariant inference?

**Comment by jcalz** [comment]
I imagine the type should have some obvious real-world utility for a use case the TS team is interested in supporting, but I can't say what that is on first glance.  🤷‍♂️

**Comment by fatcerberus** [comment]
I’m confused why you’re writing `T extends U ? V : V` (presumably this is just to get the distributive behavior?) instead of something like `T extends unknown ? V : never`

Although in the case of `Remap` there’s seemingly no reason to write that conditional type at all since `T[K] extends …` is not distributive…
