### ISSUE TITLE
await keyword on function parameters

### ISSUE THREAD

**Issue by eggers** [microsoft/TypeScript#56345]
### 🔍 Search Terms

await function parameters

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Similar to the public/private keywords on object constructors, it would be helpful to add an `await` keyword to function parameters that automatically awaits the parameter so that the parameter is the awaited value rather than a promise

### 📃 Motivating Example

It's a frequent pattern that a parameter to an async function can be a promise or a value , and then it's immediately awaited at the top of the function:

```ts
async function awaitParamsInBody(
  paramA: Promise<string[]> | string[],
  paramB: Promise<string> | string,
) {
  const [awaitedParamA, awaitedParamB] = await Promise.all([paramA, paramB]);
  return awaitedParamA.includes(awaitedParamB);
}
```

The below is more concise and easier to read:

```ts
async function awaitKeyword(await paramA: string[], await paramB: string) {
  return paramA.includes(paramB);
}

awaitKeyword(Promise.resolve(['foo', 'bar']), 'foo');
```

### 💻 Use Cases

1. What do you want to use this for?

Some syntactic sugar to avoid names like `paramPromise`/`awaitedParam`

2. What shortcomings exist with current approaches?

It's a bit more verbose to pass in a promise to a function to only immediate await it. It becomes even more so when there are multiple params that are promises.

3. What workarounds are you using in the meantime?

**Comment by eggers** [comment]
The proposal is also similar to the `for await...of` syntax

**Comment by jcalz** [comment]
You checked

> - [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, **new syntax sugar for JS**, etc.)

but yet this is clearly

> Some syntactic sugar to avoid names like paramPromise/awaitedParam

This will be declined for that reason.  TC39 is the place to go for JS stuff.

**Comment by MartinJohns** [comment]
>  [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

I don't see how this is the case. Want to elaborate?

**Comment by RyanCavanaugh** [comment]
This violates a necessary condition listed in the template:

>  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

**Comment by RyanCavanaugh** [comment]
Triple jinx???

**Comment by fatcerberus** [comment]
Could have been a quadruple jinx, but I wasn't near a computer a 35 minutes ago.

**Comment by eggers** [comment]
Ah, I misunderstood runtime feature.
