### ISSUE TITLE
Control flow not considering mutable values could change between iterations of an async for loop

### ISSUE THREAD

**Issue by eliasm307** [microsoft/TypeScript#56349]
### 🔎 Search Terms

- control flow async generators 
- control flow async for loop

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Type System Behaviour

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99&ts=5.2.2&allowUnreachableCode=false#code/CYUwxgNghgTiAEYD2A7AzgF3lNBPFYA4iCiDFBkjAFzwCCeBxp5lMAPAK4oDWKSAdxQA+ANwBYAFBSIILAFtOGKACNZAISRJZUFPAC88AGZQIaEBOmTzGACoBLeSCRKAFK4CUB4fADeU+HhFZTUQTW0QXQN4DBhOCykAXwAaeABGAAYMj0spIypsASh7LFdkdCwAN1N4JCNsRiISMgoqL39JQIB6LvhAGXJEVFjtYwhBeGAkEDQULHK0e1AYeGqIeMHOCGBEAAtdAHMEez0VOQEQEhidhBx8MHgSlox7VDQA+B6Gh4w0eH4sOAAWhwC32pG2xyu9l+aGQAAcEAIdvYwDsgpF0FcEPkIGMBMd9g8YTtBHocNh4HBgNxgLo5tcwDx3p8SedKmQsfAAAY2BxOFwYLnYFRIdkbLa7A4IDDXFamdb5ZZoJBOb5PF7od72equYKqDRaHR6fQmmJxEDtd6BFRwKA8SyBRJJKRSW4EYzcMDPVDGLSePzM3qAUHJ4JwFihCTLocYYCqKUZPd69PjQJiZdLcAjUuSSuLtqipfBTorpbKEwQk0TEKZZMBA1DftGkRR4GgSZttns4Qi9JCuYrCsVBfAxkg4b9TMqtTq9aFwkaDKbYvFLZ1ApS5JwYCgHfAnZJ91IQAAPOFULC+RKWIA

### 💻 Code

```ts
declare const asyncGenerator: AsyncGenerator<unknown>;

let mutableBoolean = false;

setTimeout(() => {
  mutableBoolean = true;
}, 100);

for await (const val of asyncGenerator) {
  // ❌ control flow doesnt consider value could change in between the async iterations
  // as its not re-assigned in this scope which means the following is shown as a redundant check
  // however the `setTimeout` above could change the value for some iterations
  if (mutableBoolean === true) { // type error
    break;
  }
}

async function foo() {
  // ✅ using this from a function widens the type, as it could change before the function is called
  // this is what should happen in `for await` loops also
  if (mutableBoolean === true) {
    return;
  }
}

export {};


```

### 🙁 Actual behavior

Within a `for await` loop, mutable values that could change in the awaited time between iterations do not have their types widened to consider the value could be different when accessed in different iterations.

### 🙂 Expected behavior

Same as for functions, the control flow analysis should consider that values could change externally between `for await` loop iterations and it should not flag the comparison to check the current value in the loop as redundant

**Comment by RyanCavanaugh** [comment]
Not different from #9998

**Comment by eliasm307** [comment]
@RyanCavanaugh thanks for the reply, yes the linked issue looks strongly related, I'll close this
