### ISSUE TITLE
Add support for MediaStreamTrackProcessor

### ISSUE THREAD

**Issue by dahmadjid** [microsoft/TypeScript#56353]
### 🔍 Search Terms

typescript autocomplete
MediaStreamTrackProcessor

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

add support for MediaStreamTrackProcessor: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrackProcessor

it can not find the name of "new MediaStreamTrackProcessor()" but it works on the browser just fine (chrome)

### 📃 Motivating Example

in a ts file write:

new MediaStreamTrackProcessor();

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript-DOM-lib-generator#when-the-type-is-missing:

> check whether it's supported by two or more browser engines.

Your type seems to be supported by only one engine. *Usually* types for experimental API are not added.

**Comment by dahmadjid** [comment]
true makes sense. my bad. thanks.

**Comment by anaelshomrai** [comment]
This is now released for Safari as well

**Comment by cozzbie** [comment]
Sooooo...whats up? This getting added or....???? It now has support on Safari and Opera.

**Comment by RodRich1991** [comment]
Watching...
