### ISSUE TITLE
Allow emitting values from types

### ISSUE THREAD

**Issue by thezzisu** [microsoft/TypeScript#56367]
### 🔍 Search Terms

"convert type to value" "emit type as value" "use type as value"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Add a keyword to emit a literal value from a non-union literal type.

Assuming `type_cast` as the keyword, the following code

```ts
type A = 'some_str'
let a: A = type_cast A
```

Will be transformed into

```js
let a = 'some_str'
```

Just supporting string literal and number literal is quite enough.

### 📃 Motivating Example

As we all know, C++ templates have the ability to static initial values at compile time using template magic. The type system of TS is much human-friendly than C++, but lakes the bridge from type inference to runtime value. If casting types to values is made possible, the TS type will be ever more powerful.

### 💻 Use Cases

1. What do you want to use this for?

Implement metaprogramming frameworks without code generator, like
- Generate JSON Schema directly for TS types
- Extract type information without using decorator&reflect-metadata
- And more possibilities as seen in C++...

2. What shortcomings exist with current approaches?

We must use code generators which is just not clean.

3. What workarounds are you using in the meantime?

Code generators.

**Comment by MartinJohns** [comment]
> [x] This could be implemented without emitting different JS based on the types of the expressions

I don't think this should be checked.

**Comment by IllusionMH** [comment]
In most cases you can go opposite way - get types from code with `typeof`, to make sure that types stay true to the actual code to reduce duplication.

As for JSON motivation example - I would recommend something like Zod and related Libs to ensure runtime to TS (+ JSON Schema) guarantees.

**Comment by thezzisu** [comment]
> > [x] This could be implemented without emitting different JS based on the types of the expressions
> 
> I don't think this should be checked.
> 
> I also don't see how this would be useful for your use case. This would really just be a simple "search & replace", and wouldn't really work for any slightly more complex type (e.g. a union).

I apologize if I'm misunderstanding the concept of "emitting different JavaScript based on the types of expressions". My grasp of TypeScript's internal compilation processes isn't deep, and I'm uncertain if introducing a feature like this would necessitate significant changes in the code.

Regarding the point about this being a mere "search & replace" process, I want to highlight that extracting types without third-party tools like ttsc isn't straightforward. In many cases, having type information readily available would greatly simplify metaprogramming tasks. For instance, TypeORM utilizes decorators and reflect-metadata, but these are limited to classes and don't extend to more common constructs like interfaces. Introducing a method to directly convert a type into a value could open up new possibilities.

I agree that this approach might not be effective for more complex types. However, as I've mentioned before, supporting basic types like string and number literals would be sufficient for many use cases.

The inspiration for this idea comes from C++ templates. While I'm not a fan of C++'s template system, its power is undeniable. The JavaScript type system has evolved to allow programmers to perform type-safe metaprogramming. We can transform values and types, and infer types from constant values. The missing piece of the puzzle is a way to derive values from types.

**Comment by thezzisu** [comment]
> In most cases you can go opposite way - get types from code with `typeof`, to make sure that types stay true to the actual code and to reduce duplication (partially covers second use case)
> 
> As for JSON use case - I would recommend something like Zod and related libs to ensure runtime to TS (+ JSON Schema) guarantees.

Thank you for your suggestions. I've personally used TypeBox and Zod for such tasks. However, in my experience, they tend to be cumbersome and not particularly conducive to the DRY (Don't Repeat Yourself) principle.

Regarding the use of the typeof operator, I've experimented with it in some personal projects. But, as I mentioned earlier, the core motivation behind this feature request is to facilitate easier and more powerful metaprogramming, without the need to resort to code generators.

**Comment by thezzisu** [comment]
Actually only emiting very, very basic string/number literals will be just enough, because we can use carefully handcrafted generic types to convert a very complex type into a string. And after that we can just use JS to do the rest work.

Example [playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIFkCerzXk5AbwChkzk4AuZAZzClAHNTyAjakAVwFtXoWyCagBE4kYgF9ixMJgAOKACryIigPYBlekwA8igHzIAvMkXIIAD0ggAJjVraQjZAH5kAcjoMn75JQHkgUHBZGaW1nbIXLzQrh7RfFC+-iGpqWFWELb2opBx7jZiEMkBaWXuamAAFtA07tKyCsgA0hCYygoACnDAUDR6hiYkZADazcigyADWbWowpgC61OPhWZFeTHEABgAkhM0SlHsdqpqOjHpjC-oSW35REABu-BIjM5hziw0qpgCMxi02idur1+hhsLhYIgIPpvk0AKogYBqEDqHCQPoQBBgZEgHTwwbIAAU8PMmWyFBAmDiRKm1HhAEpjIZHmpgDZ7iAntAmasKUSWHSJiAYLFUMQmUYWWybCw3OKyBxuVAANxwlCI3HqADyjwANnZ8YTNSi0ZCaFicSidCxSXzInAqTSYPTJdL2ZzlcR9GqZD9Omo5Ca8QSAcGdfrDaH7fYiVRhaKoMgAIJu5Csj1uZOe56q9VoGjBgYAkaKBZkiL2EbhtTo2qW3EDctueB6i33eicCC+xoapGmtTJqBQOCYPQAGhTFbW9k4ICmIDUAHcQCNyyY14TUIX+3iDNOKZ2IHLkDWhyOxwBRCwIPWcGwQCfIANB3cDfSTkYvosGScAOgA5NrhYahS3-QCFh7H4ACUIBoTg9TAMNd3Uc9Rz0X5YT9JowDObwLn3EwMkrBx8LiMwlVzfMACk2Txc9Jw0CA5APdZzkJc9WKrZtkAAIl4+5OJjZARlARNkAAMXAv8xNiaCeN2QhcK0fCdAkm49iYuQJD2WjQB0aDGOYm47ko-hsJQCTQDgPVYPgxCAT0vE7IQsBJ148deP0IA)

```ts
interface IMyInterface {
    a: string
    b: number
    c: Date
}
// Omitted type magics
type FinalResult = Join<Result, ","> // type FinalResult = "a:string,b:number,c:date,"

// Now we can do the rest work using *emitting values from types* and JS.
```

**Comment by fatcerberus** [comment]
> I apologize if I'm misunderstanding the concept of "emitting different JavaScript based on the types of expressions".

It means pretty much exactly what it says - for example, here you're asking that the expression `type_cast A` produce something different in the output JS based on what the type `A` is.  TS's design philosophy is based around being able to blindly remove type information to produce the compiled output (e.g. Babel can transpile TS code without having to actually parse the type-level stuff, thanks to this design), known as "type erasure".  While there are some features that violate this, e.g. `const enum`, those were introduced before the "no type-directed emit" policy was put in place so are kept around for backwards compatibility.

The feature request here will almost certainly be rejected by the TS team.

**Comment by fatcerberus** [comment]
btw I think this also counts as "non-ECMAScript syntax with JavaScript output"

**Comment by thezzisu** [comment]
> btw I think this also counts as "non-ECMAScript syntax with JavaScript output"

Thank you for the clarification. I have to admit this suggestion will break the `being able to blindly remove type information to produce the compiled output` philosophy. Although it's a pity for me, I will try to investigate other solutions to meet my need, and closing this issue.
