### ISSUE TITLE
Missing FileSystemDirectoryHandle methods in the lib.dom.d.ts

### ISSUE THREAD

**Issue by pascalav** [microsoft/TypeScript#56360]
### 🔎 Search Terms

typescript, visual-studio-code, intellisense, origin-private-system, FileSystemDirectoryHandle, lib.dom.d.ts

https://stackoverflow.com/questions/77453180/missing-filesystemdirectoryhandle-keys-method-in-vscode-intellisense

The nightly version and Playground do not display methods either.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about FileSystemDirectoryHandle methods.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20231110#code/BQQwzgngdgxgBMAlHAvAPjgbwFBz3GAeyjABc4AnQw0gEQEsLU4QB3Ee8qEAN3oHMQpQhQB0ZESH4BTUTLqNpMYRQhIA3LnwB6bXABihADZHCrelH5wAttNIALQgBMwN+mDAX+AGjgAjAFdyMACAB1CRUlcLG0IyfypWMGkKV2B7UlJQsAAuXSdpHmlTUJTRa0IAL3oTEFERfm1pKABaAFUAZW0nQhgwbQB1aT9tAEEABQBJbX0a6Q6IMmlrBgolFQgACRAoJyNpAGI-ROSKAH0ia1Chej8azghELTwqGlXRAGtpRY1nymoFGJmqQKPRpGBfvh-m9GKIeCAjAFwb8AL6IJBAA

### 💻 Code

```ts
    const rootDir = await navigator.storage.getDirectory();
    // Following methods missing, but supports in most browsers (https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle#browser_compatibility)
    rootDir.keys();
    rootDir.entries();
    rootDir.values();
```

### 🙁 Actual behavior

TypeScript write: Property 'keys' does not exist on type 'FileSystemDirectoryHandle'.(2339).

### 🙂 Expected behavior

That the TypeScript check recognizes the methods as valid.

**Comment by jakebailey** [comment]
I'm pretty sure that this is something that has to be fixed in https://github.com/microsoft/TypeScript-DOM-lib-generator; I had thought that the problem here was that they weren't including `DOM.Iterable`, but I don't see this type mentioned there.

**Comment by MulverineX** [comment]
Related issues: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1639 https://github.com/microsoft/TypeScript/issues/29867

Looks like the typings are being generated 🤔 https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/baselines/dom.asynciterable.generated.d.ts
