### ISSUE TITLE
Generic loses generic behaviour under certain conditions.

### ISSUE THREAD

**Issue by coolCucumber-cat** [microsoft/TypeScript#56377]
### 🔎 Search Terms

generics, generic loses genericness, generics with object types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-beta#code/C4TwDgpgBAslC8UDeAoAkAQwFzKgEw2GygHIMSoBfdAIxyX0OJJourQGN7GicSO2KaigBmAVwB2HYAEsA9hKgSAPAHkoEAB7AIEvAGcoAawgg5I2AD4AFHJyqAlDhgBtVQF0XJAkRLvk6ABOEMBigYpkJEIoKBLWLCQOKEA

### 💻 Code

```ts
type M = {
	a: { data: 'a' }
	b: { data: 'b' }
	c: { data: 'c' }
}

function n<O extends keyof M>(o: O): M[O]['data'] {
	return 'a' // expected error
}

n('b')
```

### 🙁 Actual behavior

It allows 'a', 'b' or 'c' instead of the generic type which is supposed to be the same as the input. The same problem occurs with assigning variables or functions inside the other function. Although the type must be `M[O]['data']` and it says that it is that, it acts as if it were no longer generic, as in `M[keyof M]['data']`.

### 🙂 Expected behavior

I woud expect it to be `M[O]['data']`.

### Additional information about the issue

You don't have this issue if you remove the object with the data key and replace it with the value of data, for example `''a'` instead of `{ data: 'a'}`

**Comment by IllusionMH** [comment]
Related to #27808

**Comment by RyanCavanaugh** [comment]
This is the best we have at the moment, since doubly-higher-order indexed operations aren't deferred. If this were an error, we'd have an error on a legal function body:
```ts
type M = {
	a: { data: 'a' }
	b: { data: 'b' }
	c: { data: 'c' }
}

declare const m: M;
function n<O extends keyof M>(o: O): M[O]['data'] {
	let t1 = m[o];
	//  ^? t1: M[O]
	let t2 = t1.data;
	//  ^? t2: 'a' | 'b' | 'c'
	return t2;
}

n('b')
```
You could rewrite this in terms of a conditional type, but at then point then there's no cast-free legal implementation of `n`
