### ISSUE TITLE
Typescript does not accept `"string name"` aliases

### ISSUE THREAD

**Issue by landonxjames** [microsoft/TypeScript#56375]
### 🔎 Search Terms

export alias string names
import alias string names
string alias for imports/exports

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about string names as import/export aliases

### ⏯ Playground Link

https://www.typescriptlang.org/play?module=1&ssl=3&ssc=17&pln=3&pc=20#code/MYewdgzgLgBAZiEMC8MCMBuAUFgpgDwAcQAnWAbwSQEMIYAiAI2pPoF9sg

### 💻 Code

```ts
const foo = 1;

export {foo as "bar"};
```

### 🙁 Actual behavior

This fails to compile because of the `as "bar"` in the `export` statement.

### 🙂 Expected behavior

This should compile and allow string name aliases. 

### Additional information about the issue

String name import/export aliases should be allowed by the ts compiler. They are valid javascript (see the [syntax section of the MDN page](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#syntax) in `exports`).

**Comment by fatcerberus** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/40594

**Comment by fatcerberus** [comment]
PR to implement support for this is here https://github.com/microsoft/TypeScript/pull/49297 but seems to be stalled.

**Comment by landonxjames** [comment]
Ahh thank you for the pointer! Closing in favor of the existing issue.
