### ISSUE TITLE
What is the type of T['x'] when T is type param of a generic function?

### ISSUE THREAD

**Issue by zhoudaxia2016** [microsoft/TypeScript#56388]
### 🔎 Search Terms

generic indexed type

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAylC8UDeAPAXFA5AQwEYGNMBfAKADMBXAO32AEsB7KqMgHgBUoIVgIqATAM6wAfAAoAlMhJQo+JoOBR0yANoBrKHWbtVmFJgC6hjFQoBbXBABORBMjz4MARjsB6N12vWG1mXIUlEAwkDS1mGD0DY1MLK1t7JEcXUlJKGnomFmcOLh4+IVFJaVl5KkVlDF19I3scAkx-MorgqGrouoALbG7MKA8vHz8iIA

### 💻 Code

```ts
type S = {x: 'abc'}
function f<T extends S>() {
  const x: {[k in T['x']]: number} = {abc: 1} // error
  const y: {[k in S['x']]: number} = {abc: 1}
}
```

### 🙁 Actual behavior

First line of function f has error.

### 🙂 Expected behavior

No error.

### Additional information about the issue

I think the type of `T['x']` should be `'abc'`. Am I missing something or is a bug?
I has asked this at stackoverflow, but no useful answer.

**Comment by fatcerberus** [comment]
No, `T` could be any type assignable to `S` so, e.g. you might have `T = { x: 'abc', y: 'def' }` and then you'd be missing a `def` property.  The error is correct; there is no concrete type you can safely assign to `T["x"]` because you can't guarantee all properties are present for an arbitrary `T`.  The only way you get a legal value is by taking something (a parameter, for example) of type `T` and reading its `.x` property.

**Comment by fatcerberus** [comment]
> Object literal may only specify known properties, and 'abc' does not exist in type '{ [k in T["x"]]: number; }'.

This part might be a bug, though.  Tripping the excess property check for a deferred generic type that can't be satisfied *at all* is weird.

**Comment by zhoudaxia2016** [comment]
> No, `T` could be any type assignable to `S` so, e.g. you might have `T = { x: 'abc', y: 'def' }` and then you'd be missing a `def` property. The error is correct; there is no concrete type you can safely assign to `T["x"]` because you can't guarantee all properties are present for an arbitrary `T`. The only way you get a legal value is by taking something (a parameter, for example) of type `T` and reading its `.x` property.

Thank for your answer. I can't understand why `you can't guarantee all properties are present for an arbitrary T`. T extends {x: 'abc'}, why we cannot guarantee T['x'] is 'abc'.
What is the type of T['x']
