### ISSUE TITLE
generic looses `undefined` when inferring from optional parameter

### ISSUE THREAD

**Issue by mProjectsCode** [microsoft/TypeScript#56386]
### 🔎 Search Terms

generic, optional, undefined

### 🕗 Version & Regression Information

This happens in every version of the playground that I tested, back to 3.3.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAECiAeAHApsALgHgCoD5oG8AoASDQHsAhZACmSVTQC5osBKZgNzIEsATAwiQC+hEYQBmAVwB26bmWnQ6KdNmgBeaDIDW0sgHdpOamHSSwIAPzM2zBCsy4BxAE7I0kl4unJ9ceqq41KwA3KKCUrJo8ooA5sjSAILBzBBoLtzSsdAAPlrSvMjimcj8RK7unooyhcU+vGFiygzU8UnBrAB05FTUAORoyGl9oYTN6K0JyaxdPTQ1RSW8oUA

### 💻 Code

```ts
class Expect<T> {
	toBe(expect: T): void {

	}
}

function expect<T = unknown>(actual?: T): Expect<T> {
	return new Expect<T>();
}

function genA(): string | undefined {
	return undefined;
}

expect(genA()).toBe('test');
expect(genA()).toBe(undefined);
```

### 🙁 Actual behavior

The line `expect(genA()).toBe(undefined);` throws the following type error `Argument of type 'undefined' is not assignable to parameter of type 'string'.`, since `undefined` is missing on the inferred generic.

### 🙂 Expected behavior

`undefined` is part of the generic and there is no type error.

### Additional information about the issue

This is impacting Bun Test, see https://github.com/oven-sh/bun/pull/6634.

**Comment by jcalz** [comment]
Doesn't look like a bug to me; `actual` is optional to `undefined` is always in its domain.  TypeScript is being asked to infer the type `T` for which `T | undefined` is the same as `string | undefined`.  If someone asked me to do that, I'd say `string`, which is what TS is doing here.  It isn't *incorrect* to infer `string | undefined`, but it would be weird to do so.  

If you don't like the inferred type argument you could always specify it yourself:

```ts
expect<string | undefined>(genA()).toBe('test');
expect<string | undefined>(genA()).toBe(undefined);
```
[Playground link](https://www.typescriptlang.org/play?ssl=9&ssc=2&pln=8&pc=25#code/MYGwhgzhAECiAeAHApsALgHgCoD5oG8AoASDQHsAhZACmSVTQC5osBKZgNzIEsATAwiQC+hEYQBmAVwB26bmWnQ6KdNmgBeaDIDW0sgHdpOamHSSwIAPzM2zBCsy4BxAE7I0kl4unJ9ceqq41KwA3KKCUrJo8ooA5sjSAILBzBBoLtzSsdAAPlrSvMjimcj8RK7unooyhcU+vGFiygwYaRlZufm1JbzG8UnBrAB05FTUAORoyGnjoYTNqm2Z2Xk1RT19Ccmsw6M0a3WloUA).

**Comment by mProjectsCode** [comment]
> If you don't like the inferred type argument you could always specify it yourself:

But the point of correct inference is that I don't need to do that 😉 

>  It isn't incorrect to infer string | undefined, but it would be weird to do so.

But the current behavior can quickly lead to runtime errors thanks to the wrong security that partially incorrect types give you here.

**Comment by fatcerberus** [comment]
The current subtractive inference behavior is often relied on, e.g.

```ts
function isNonNullish<T>(x: T | undefined | null): x is T {
    return x != null;
}
```

This is a very common pattern and would be broken if TS started inferring e.g. `string | undefined` for `T` instead of `string`

**Comment by mProjectsCode** [comment]
Ok, but then why does my example work (not erroe) when I remove the `?`, making it a required argument?

**Comment by jcalz** [comment]
Because then `undefined` is not automatically in the domain.  An optional parameter behaves like a union with `undefined`z

**Comment by mProjectsCode** [comment]
I think I get it now. 

Is there a way to restore the passed in type while also keeping the argument optional without always making it a union with undefined?

**Comment by RyanCavanaugh** [comment]
Once you wire this up in a way that's actually dangerous, you'll see an error
```ts
class Expect<T> {
	constructor(public actual: T) { }
	toBe(expect: T): void {
	}
}

function expect<T>(actual?: T): Expect<T> {
	return new Expect<T>(actual); // <- error here
}

function genA(): string | undefined {
	return undefined;
}

expect(genA()).toBe('test');
expect(genA()).actual; // danger, says string but it's not
```
Then once you fix that, the danger goes away:
```ts
class Expect<T> {
	constructor(public actual: T) { }
	toBe(expect: T): void {

	}
}

function expect<T>(actual?: T): Expect<T | undefined> {
	// Now OK
	return new Expect<T | undefined>(actual);
}

function genA(): string | undefined {
	return undefined;
}

expect(genA()).toBe('test');
expect(genA()).actual; // Correctly string | undefined
```

**Comment by mProjectsCode** [comment]
But this will result in the `Expect` class always having undefined as a union member even if the passed in type is e.g. a simple string.

**Comment by danny-may** [comment]
You could use an overload to solve this
```ts
class Expect<T> {
	constructor(public actual: T) { }
	toBe(expect: T): void {

	}
}

function expect(): Expect<undefined>;
function expect<T>(actual: T): Expect<T>;
function expect<T>(actual?: T): Expect<T> {
	return new Expect<T>(actual);
}

function genA(): string | undefined {
	return undefined;
}

expect(genA()).toBe('test');
expect(genA()).actual; // Correctly string | undefined
expect().actual; // undefined
```

**Comment by mProjectsCode** [comment]
Thanks, I also arrived at that solution, but I forgot to post it here 🤦‍♂️.
