### ISSUE TITLE
"A & B extends infer U" didn't works as expected

### ISSUE THREAD

**Issue by AndreyDiak** [microsoft/TypeScript#56383]
### 🔎 Search Terms

extends infer U, conditional types

### 🕗 Version & Regression Information

- This happenes on TS version 5.3.0 and below

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PQKhCgAIUh1BTSB3AhgOzSyAXA9pAc3m0gEs1t4AnAZ3gGNtTc1JcAzSAQUgDJIAQmU6kS8AB6ka2GgBo22ABbUkUxEnXpMOfERICoMACqKphfEiosCbNABsAnsmWsNOKk7yQArnUgAiCUo0ABMaMjR2akgAVX9IFBJpFCoSdBDneFYlMxiycP80eAA3an9DYHBwUAhoSABRcRQAWwAHO3VRRVxvEnJKWgYmFgBCCqrsB1bELgBGSABeSDRvZoAjagBuCanEAXml6SpyGwAfSDXcXA70bergZFwqAGtwy2sx4AeACVwkZEQemWJWo8lInDcIRYYlKrCoxG8VFYogSaAcSGU8IA-OBJtNIAAZA7ceb8faQIJZMIRKJUWKQLH0ymhcJFUp0xnkgBc9J5+02kC+wPZVSFSCer0g7HI8DGeMQBIATIsSXxBPNmdS2dFOfMeXM1eTNeFyLT6Yy8nz5kKjidIOdLtd4OhRWBDA0mm0OsguhEBnRGMw0GNoJVcbtuMqlit1lsdviBFHILa0GcLlcbqxzjGNlQ7mKJeFpUU5RGCQBmFVcZVk5XGmnRPIWiniYJakEcwTKnmWrsCoU56iih7il5FmWl-EEgAsVZrXZbbdZHYZC-188Ti6pJsijdXvc3A9WufAQA

### 💻 Code

```ts
/**
 * We wanna to get intersection of A & B if it exists, otherwise we wanna to get B
 * This go wrong only when we try to use "extends infer U" at start and when this U is "never"
 */

type A1 = number;

type B1 = string | boolean;

// works wrong!
// How we get never, if we dont even return it anywhere?
type L1 = A1 & B1 extends infer U ? U extends never ? B1 : U : B1; // never

// works fine!
type L2 = A1 & B1 extends never ? B1 : A1 & B1 extends infer U ? U : B1 // string | boolean
```

### 🙁 Actual behavior

I try to get intersection in infer U and wanna to return condition, but I get  type "never", 
How it works, if we dont even return "never" anywhere?

### 🙂 Expected behavior

See in example on TS playground

**Comment by RyanCavanaugh** [comment]
A conditional type is distributive over a type parameter, and an `infer ` output is a type parameter, so the clause `U extends never ?` distributes over the `never` that got produced from `A1 & B1 extends infer U ?`
