### ISSUE TITLE
Visual Studio 2015 compiles ALL typescript files when SINGLE file is changed

### ISSUE THREAD

**Issue by yesman85** [Microsoft/TypeScript#5638]
I have a ton of TS files in my project, but when I save just a single one the status bar shows:
Generation of 'File.ts' complete. Remaining files still compiling.

This hangs for easily 2-3 minutes, giving VS2015 100% CPU and lagging the editor completely.

Why was this behavior changed from previous versions?

**Comment by mhegazy** [comment]
Starting with VS 2015 RTM, Compile-on-Save, every time you save a file we need to generate *all* files in the project to ensure consistent output. We have got numerous issues related to inconsistent output when saving files in different orders. Building all files is the only way we can guarantee correct and consistent output given all the language constructs and how they interact across files (e.g. namespaces/internal modules can be augmented, and that affects the shape of emitted code, also const enms are in lined as constants, etc..).

Assuming that your code is just modules, we should be able to do better. We have an issue logged here to track this work: https://github.com/Microsoft/TypeScript/issues/3204

**Comment by yesman85** [comment]
Yes we just have modules, we only use DI so there are no build dependencies.

Problem is we have around 450 TS files for just the app and then another 300 for unit tests.

We upgraded recently to VS2015 and TS 1.6 (from 1.3), is this a 1.6 issue or VS issue? Is there something I can do in the meanwhile?

**Comment by mhegazy** [comment]
This change has been in all TS releases since 1.5 for VS2015 plugin.

> This hangs for easily 2-3 minutes, giving VS2015 100% CPU and lagging the editor completely.

is this a VM? do you have more than one core? i do not expect any UI hangs, this work happens mainly in the background..
can you share a project we can look at?

**Comment by yesman85** [comment]
No we are all using normal development machines, mine is a i5-4670 with 16GB ram and an Samsung 850 EVO SSD. 

I can share the project, but unfortunately I would have to send an NDA. 

The text editor will become very laggy, but it might because of Resharper, I will try disabling it and see if it improves.

**Comment by mhegazy** [comment]
great. appreciate the help diagnosing the issue.

**Comment by yesman85** [comment]
I disabled resharper, it seemed faster but after a few minutes it slowed down again.

I save my work alot every few seconds, does it maybe stack compilers and not stop already running ones?

Here is a video I made from the behaviour: http://screencast.com/t/uMQUgRXuruX

**Comment by SamuelEnglard** [comment]
I have Visual Studio crash on compile for a large project has lots of files that can't actually compile yet (have known compile errors). I'm thinking this is the same issue.

**Comment by mhegazy** [comment]
@SamuelEnglard a crash is definitely not expected. can you share some more details? a project that exhibits the crash would be ideal.

**Comment by SamuelEnglard** [comment]
Both https://github.com/SamuelEnglard/Humanizer.Js and https://github.com/SamuelEnglard/CIL.JS currently crash studio. I've been trying to see about crashing a smaller project but no luck

**Comment by paulvanbrenk** [comment]
I reproduced this in the CIL.JS project. There is an issue in the language service in VS, which doesn't work well with an error in `~\CIL.JS\TypeSystem\Cecil\AssemblyNameReference.ts`. VS no longer crashes if you remove the `attributes: AssemblyAttributes;` field from that class.

We're working on a language service fix.

**Comment by SamuelEnglard** [comment]
Great to hear! Thanks!

**Comment by yesman85** [comment]
Why was this closed? I don't think my issue was even investigated yet.

**Comment by mhegazy** [comment]
Github closes issues automatically.

**Comment by yesman85** [comment]
Would it be possible to build de VS2015 TS1.6 extension ourselves and disable the all compile on save feature? Or is this build in VS2015? We tried using VS2013 with TS1.6 but the issue seems persistent.

**Comment by paulvanbrenk** [comment]
You can disable Compile On Save in the project properties, and for loose files in Tools > Options > Text Editor > TypeScript > Project.

Unfortunately we're not able to open the source for the extension, and if we could there are too many dependencies on our internal tools to be able to compile it.

**Comment by yesman85** [comment]
If I disable it what would be an alternative to compile? Running it from the command window or using a different extension?

**Comment by paulvanbrenk** [comment]
There are a number:
* building the project each time after your save. 
* using the `watch` mode with NodeJs
* compiling using a file watcher from Grunt/Gulp

**Comment by yesman85** [comment]
Ok thanks I will investigate that. 

Is it possible to include in the next version of the VS extension an option in the settings page to compile only the current saved file instead of the whole project?

**Comment by paulvanbrenk** [comment]
Yes, that should be part of the work for #3204.

**Comment by yesman85** [comment]
Great, then I'll close this issue.
