### ISSUE TITLE
tsc API: undefined JSX element attribute value incorrectly showing syntax kind of 79 or 80

### ISSUE THREAD

**Issue by jdharvey-ibm** [microsoft/TypeScript#56399]
### 🔎 Search Terms

kind 79, undefined, jsx, prop, attribute

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

- ts 5.0.4 on astexplorer.net returns Kind = 79
- ts 5.2.2 on a local test returns Kind = 80

### ⏯ Playground Link

https://astexplorer.net/

### 💻 Code

```ts
function asdf() {
  return <SomeThing stuff={undefined} />
}
```

### 🙁 Actual behavior

the emitted AST gives the following on astexplorer:

```json
"expression": {
  "pos": 45,
  "end": 54,
  "flags": 0,
  "modifierFlagsCache": 0,
  "transformFlags": 0,
  "parent": "[Circular ~.statements.0.body.statements.0.expression.attributes.properties.0.initializer]",
  "kind": 79,
  "escapedText": "undefined"
}
```

Locally, with 5.2.2, we get:
```
IdentifierObject {
  pos: 601,
  end: 610,
  flags: 0,
  modifierFlagsCache: 0,
  transformFlags: 0,
  parent: <ref *1> NodeObject {
    pos: 600,
    end: 611,
    flags: 0,
    modifierFlagsCache: 0,
    transformFlags: 2,
    parent: NodeObject {
      pos: 575,
      end: 611,
      flags: 0,
      modifierFlagsCache: 0,
      transformFlags: 2,
      parent: [NodeObject],
      kind: 291,
      symbol: undefined,
      localSymbol: undefined,
      name: [IdentifierObject],
      initializer: [Circular *1]
    },
    kind: 294,
    dotDotDotToken: undefined,
    expression: [Circular *2]
  },
  kind: 80,
  escapedText: 'undefined',
  jsDoc: undefined,
  flowNode: undefined,
  symbol: undefined
}
```

- Type 79 maps to CaretEqualsToken, LastAssignment, LastCompoundAssignment, LastPunctuation,  and LastBinaryOperator.
- Type 80 maps to Identifier.
- None of these have any relation to undefined, such as Kind = 157 (UndefinedKeyword).

### 🙂 Expected behavior

I expect this to behave like null, false, true, etc... where undefined is recognized in the AST as a keyword.

**Comment by jakebailey** [comment]
SyntaxKind is unstable and its exact values must not be depended on. Only the names are stable, and must be used to look up values at runtime for a given instance of typescript.

**Comment by jakebailey** [comment]
Maybe I'm misunderstanding, but undefined is an identifier, not a keyword, so what you're seeing is correct.

**Comment by jakebailey** [comment]
In type space, it's what is used to represent the `undefined` type. e.g. put your cursor on the type in https://ts-ast-viewer.com/#code/MYewdgzgLgBAHgLhgVzAEwKYDMCWYNowC8K62eBA3EA and note the Node on the right.

**Comment by jdharvey-ibm** [comment]
That's super helpful info, thank you!

As a side note, we've been really happy with the TypeScript compiler API so far. We're using it to perform static analysis of source code for telemetry purposes.
