### ISSUE TITLE
Please create an official TypeScript Mastodon account

### ISSUE THREAD

**Issue by mlcohen** [microsoft/TypeScript#56396]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

This is a very humble request for someone on the TypeScript team to please setup an official TypeScript [Mastodon](https://joinmastodon.org) account. Currently the TypeScript team only has a [Twitter/X account](https://twitter.com/TypeScript). There are many developers who use TypeScript who would prefer to follow updates on Mastodon. This would be very easy to do. Just setup an account on [mastodon.social](https://mastodon.social) (e.g. `typescript@mastodon.social`). Get the account [verified](https://joinmastodon.org/verification) and add prominent links to the account on the [TypeScript website](https://www.typescriptlang.org).

<img width="1017" alt="Screenshot 2023-11-14 at 10 51 31 AM" src="https://github.com/microsoft/TypeScript/assets/100445/e573c3b4-9d82-4443-85b1-46f1355f38b5">

**Comment by mlcohen** [comment]
> we're on bluesky

Nice! However, it'd still be great if TypeScript had an official Mastodon account as there are many developers there and not on bluesky. Mastodon has over 1.8 million active users. As well, update the website to include links to all the social media accounts; not just Twitter/X

**Comment by RyanCavanaugh** [comment]
https://fosstodon.org/@TypeScript

**Comment by mlcohen** [comment]
Awesome! Looks like it was setup recently (June, 2023). To help people know that it is indeed the official Mastodon account, it would be great to get it properly [verified](https://joinmastodon.org/verification). This is easy to do. Just requires that the typescript home page includes a `rel="me"` link using either a `link` or `a` tag (e.g. `<link rel="me" href="https://fosstodon.org/@TypeScript">`). The account's bio then includes a field to the website.  Also, perhaps update the account's bio to say that it is the official TS Mastodon account. To help promote your other social media accounts (Mastodon, Bluesky, etc), best to update the TS homepage to include prominent links.

**Comment by mlcohen** [comment]
Just for comparison, The Python Software Foundation (PSF) has an official Mastodon [account](https://fosstodon.org/@ThePSF) that is verified and is promoted prominently on their python.org website. The account posts frequently and has over 9,000 followers. I'm sure the TypeScript Mastodon account could easily gain a lot of followers by getting it verified, promoted and actively posting.

**Comment by DanielRosenwasser** [comment]
The 5.3 release was posted there, I'll try to keep cadence up across the platforms.

**Comment by mlcohen** [comment]
@DanielRosenwasser Appreciate the response. I'd still like to suggest getting the account [verified](https://joinmastodon.org/verification). Verification goes a long way to help build trust that the Mastodon [account](https://fosstodon.org/@TypeScript) really is the official account. For example, the official [Python](https://fosstodon.org/@ThePSF) and [Rust lang](https://social.rust-lang.org/@rust) Mastodon account are both verified. If you'd like, I'd be happy to help 😊

**Comment by jakebailey** [comment]
The website should now provide a link, which should verify the account whenever @DanielRosenwasser has some time to add the website URL to the profile.

**Comment by mlcohen** [comment]
@jakebailey Yay, that's fantastic news! Thank you so much for making the update. Checking for the website update with the Mastodon link. Look forward to seeing the official account being verified 🙌

**Comment by DanielRosenwasser** [comment]
Done - we're verified! Thanks for the gentle and understanding nudge on this @mlcohen.

**Comment by mlcohen** [comment]
Yep, see the profile updated with the website field. The website update must be still propagating.

**Comment by mlcohen** [comment]
Can confirm that the TypeScript Mastodon account is now [verified](https://fosstodon.org/@TypeScript) ✅. Woohoo! 👏

One tiny nit: The Mastodon link is missing an icon. Can find the official brand log here https://joinmastodon.org/branding

<img width="579" alt="Screenshot 2023-11-21 at 1 59 47 PM" src="https://github.com/microsoft/TypeScript/assets/100445/33e774f1-f241-4078-9f6b-26ad631b65f5">

<img width="1250" alt="Screenshot 2023-11-21 at 2 00 22 PM" src="https://github.com/microsoft/TypeScript/assets/100445/fad587d4-881e-4d14-ad2b-42d049d3bea9">

**Comment by jakebailey** [comment]
Done.

**Comment by mlcohen** [comment]
@jakebailey Yep, can confirm. Thanks for the quick update 💪. The TypeScript Team rocks! 😎

<img width="408" alt="Screenshot 2023-11-21 at 5 10 02 PM" src="https://github.com/microsoft/TypeScript/assets/100445/47e8fc64-e012-4aa1-a981-17639fcbd0ab">

**Comment by orta** [comment]
Nice!
