### ISSUE TITLE
private fields are not private

### ISSUE THREAD

**Issue by reverofevil** [microsoft/TypeScript#564]
Consider the following code

```
export class Test {
    private x: number;
    constructor() {
        this.x = 42;
    }
    f() : number {
        return this.x;
    }
}
```

Typescript generates the following JS

```
var Test = (function () {
    function Test() {
        this.x = 42;
    }
    Test.prototype.f = function () {
        return this.x;
    };
    return Test;
})();
exports.Test = Test;
```

Obviously, one could run something like `new Test().x` in a JS library, and `private` invariant would fail. I think it's not a kind of behaviour one would expect from `private`, at least in `export`ed classes. The fix is quite simple:

```
var Test = (function () {
    var _private = {};
    function Test() {
        _private.x = 42;
    }
    Test.prototype.f = function () {
        return _private.x;
    };
    return Test;
})();
exports.Test = Test;
```

**Comment by Hainesy** [comment]
This philosophy is problematic mainly for the for ... in scenario. To get around it, I'm using the underscore prefix convention for all private fields, and then checking for property.startsWith("_") in the for ... in loop.

**Comment by acheshkov** [comment]
I can't understand why @RyanCavanaugh closed this issue !?

**Comment by RyanCavanaugh** [comment]
Me neither, because I didn't?

**Comment by polkovnikov-ph** [comment]
@acheshkov Let's imagine that TS compiled to assembly. Would `private` be still valid in assembly code? Of course, it wouldn't. But JS is essentially assembly language of the web. There is no guarantees for `private` fields to be still private in JS, and there shouldn't be any. Semi-readable JS code that compiler generates could make you think otherwise, but it's not true. That's why I closed my own issue.

**Comment by acheshkov** [comment]
Sorry guys, 

i lost the main topic of this issue. My concern is not about encapsulation with _private_ keyword. I just wanted to give my vote to the idea of using _Object.defineProperty(..{enumerable: false} ...)_ for private properties. 

@RyanCavanaugh the UX of github are confused looks like you closed it :)

**Comment by polkovnikov-ph** [comment]
@acheshkov `Object.defineProperty` is not a very fast method. There's really no need to inflict slowdown on all programs with `private` fields, because if it matters to your code, you're using generated JS as if it were an implementation language, not assembly, and you're wrong.

**Comment by acheshkov** [comment]
@polkovnikov-ph 

* there is always a tradeoff between performance and language power/expressiveness. And my opinion that the second one is more important if we want to develop JS/TS.
* i agree with you only in one that there are not right approach today to hide private methods from inherited instances even at runtime execution level. But actually it's possible and there are workarounds playing with _Object.definePropery_ that can help in particular case.
* about slow down. please look at [https://jsperf.com/object-defineproperty-vs-definegetter-vs-normal](benchmarks). not so bad

**Comment by ileathan** [comment]
I got all excited when I saw typescript supported `private` until I opened the source and saw it was public lol. I guess they just added the word private to facilitate better coding? I guess thats nice, but, 3 years later there should atleast be actual `private` support.
