### ISSUE TITLE
"Extract to type alias" not available at end of span

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#56401]
```ts
interface Yadda<T> {
    x: T
}

export let blah: Yadda/*a*/<string>/*b*/;
```

**Expected**: At both `a` and `b`, *extract to type alias* is offered as a refactoring.
**Actual**: Only `a` offers the refactoring.

**Comment by babakks** [comment]
I've just submitted a PR for this. Please review it whenever you deem fit.
