### ISSUE TITLE
Ternary operator type daemon failed

### ISSUE THREAD

**Issue by vaynevayne** [microsoft/TypeScript#56407]
### 🔎 Search Terms

any

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ___4.9.5___ and _4.9.5______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

i had use confition like   `item.data && typeof item.data === 'object'` , but ts error still exist

```jsx     
<div 
     options={
                      
                          (item.data && typeof item.data === 'object'
                            ? Object.keys(item.data).map((key) => ({
                                label: key,
                                value: item.data[key],
                              }))
                            : null)
                        }
</div>
```

### 🙁 Actual behavior

```jsx     
<div 
     options={
                      
                          (item.data && typeof item.data === 'object'
                            ? Object.keys(item.data).map((key) => ({
                                label: key,
                                value: item.data[key],
                              }))
                            : null)
                        }
</div>
```

### 🙂 Expected behavior

<img width="566" alt="image" src="https://github.com/microsoft/TypeScript/assets/124666577/644662c5-45ea-4ac4-a9f7-b9e276bf6c04">

**Comment by fatcerberus** [comment]
*sigh* #9998

**Comment by MartinJohns** [comment]
Good news everyone! The expected behavior is the actual behavior.

**Comment by RyanCavanaugh** [comment]
Duplicate #11498

"daemon" ?
