### ISSUE TITLE
Confusing error message when calling value whose type is a union of types with call signatures

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5640]
From @StrahilKazlachev on Gitter on [November 12, 2015 9:04 AM](https://gitter.im/Microsoft/TypeScript?at=5644c69e039e2333061922d0)

```TypeScript
interface MyType {
	x;y;z;
}

function transform(items: MyType[] | string[]) {
    return items.map(val => val);
        // ~~~~~~~~~~~~~~~~~~~~~ Cannot invoke an expression whose type lacks a call signature.
}
```

We should consider giving a more helpful error message if the type is a union, all of whose types have call signatures. Something like

```
Cannot invoke an expression whose type is a union with incompatible call signatures.
```

or hopefully something better than that

**Comment by zbjornson** [comment]
This message seems to have just manifested after upgrading to 2.1.0-dev.20160729. Glad to find the translation in this issue :).
