### ISSUE TITLE
`jsdoc` does not create proper link when you link an imported module

### ISSUE THREAD

**Issue by optyler** [microsoft/TypeScript#56419]
Type: <b>Feature Request</b>

Following `jsdoc` syntax shoud work when you reference a module.
/**
 * bla bla bla
 * @see module:date-fns/format
 */

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin x64 21.2.0
Modes:

**Comment by RyanCavanaugh** [comment]
There's a lot of missing information here. Please file a new issue using one of our TypeScript repo templates.
