### ISSUE TITLE
Leak memory in build typescript

### ISSUE THREAD

**Issue by tuwibu** [microsoft/TypeScript#56410]
### 🔎 Search Terms

"typescript build leak memory", "leak memory"

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______
Typescript: 5.2.2
Node: v20.9.0
Platform: Debian 11

### 💻 Code

```
tsc
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/89235917/13fa43fa-d68a-4b4c-bdcc-78fbef1e8b04)
When i build typescript in vps debian 11, its error leak memory
My VPS: 8GB ram (free 7GB)

### 🙂 Expected behavior

I want build in vps success
Currently I have to do the build on the my pc then push it to the vps

### Additional information about the issue

all package:
```
"@faker-js/faker": "^8.0.2",
"@fastify/autoload": "^5.7.1",
"@fastify/cors": "^8.2.1",
"@fastify/jwt": "^6.7.1",
"@fastify/multipart": "^8.0.0",
"@prisma/client": "^5.5.2",
"@sinclair/typebox": "^0.28.9",
"aws-sdk": "^2.1376.0",
"axios": "^1.4.0",
"bcrypt": "^5.1.0",
"bezier-js": "^6.1.4",
"bull": "^4.10.4",
"colorette": "^2.0.20",
"crypto-js": "^4.1.1",
"dayjs": "^1.11.9",
"dotenv": "^16.0.3",
"exceljs": "^4.3.0",
"fastify": "^4.17.0",
"fastify-multer": "^2.0.3",
"googleapis": "^126.0.1",
"https-proxy-agent": "^7.0.0",
"ioredis": "5.3.1",
"jsonwebtoken": "^9.0.2",
"node-cron": "^3.0.2",
"prisma": "^5.5.2",
"socks-proxy-agent": "^8.0.1",
"typescript": "^5.0.4",
"uuid": "^9.0.0",
"winston": "^3.8.2",
"ws": "^8.13.0",
"yargs": "^17.7.2"
// Dev
"@types/bcrypt": "^5.0.0",
"@types/bezier-js": "^4.1.1",
"@types/crypto-js": "^4.1.1",
"@types/jsonwebtoken": "^9.0.3",
"@types/lodash": "^4.14.199",
"@types/node": "^20.1.2",
"@types/node-cron": "^3.0.8",
"@types/uuid": "^9.0.1",
"@types/ws": "^8.5.5",
"@types/yargs": "^17.0.24"
```

**Comment by Katli95** [comment]
I'm running into the same on `GitHub Actions Runner (ubuntu-latest)` but not on local (M1 Pro). 
Pretty large project, ~75k LOC. 
Please ask for more info that might be helpful and I'll examine if there's something I'm at liberty to share.
