### ISSUE TITLE
Code actions  "Move to file" and "Move to new file" are shown everywhere

### ISSUE THREAD

**Issue by jrieken** [microsoft/TypeScript#56416]
* open [this file]( https://github.com/microsoft/vscode/blob/109e1f8d8afb754ed31317f79937a44e98d5063b/src/vs/base/common/arrays.ts#L126)
* select `data`
* select light bulb
* :bug: there is entries for "Move to file" and "Move to new file"

<img width="425" alt="Screenshot 2023-10-25 at 08 13 20" src="https://github.com/microsoft/vscode/assets/1794099/ba91dbaf-e161-44f9-a63a-b169199465c7">

**Comment by mjbvz** [comment]
Some ideas:

- Only show the lightbulb (implicit code action) when on declarations
- Maybe still keep showing these actions if refactorings are explicitly requested 
- In the refactoring label, show the name of what is going to be moved. Right now it makes is seem like the loop itself will get moved

**Comment by jrieken** [comment]
> Only show the lightbulb (implicit code action) when on declarations

💯 on that - showing the code action further down is noise and lowers my trust in light bulb being helpful (and not ad-space)

**Comment by aiday-mar** [comment]
HI @sandersn, I would like to have a go at this PR. Could I have a pointer to place in the code where the change should be, or discuss this issue with one of your team members in a meeting? We are currently looking into displaying code actions in the light-bulb menu in VS Code on empty lines too, and currently we are seeing the `Move to file` and `Move to new file` actions appearing very often. I had initially prepared a PR to patch this issue on the VS Code side, but we think ideally this fix should come directly from TypeScript

**Comment by sandersn** [comment]
@aiday-mar I believe @navya9singh and @andrewbranch have worked the most on Move To File.
