### ISSUE TITLE
Parameters<F> does not consider all function overloads

### ISSUE THREAD

**Issue by adiba** [microsoft/TypeScript#56430]
### 🔎 Search Terms

"overload parameters"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.2.2#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHLoBu0ANunACYAUcUA5gFzIgCuAtgEbQCUTxdMCr5CJcpVr1myAM5gooBv0HDcAX1xgAngAcUABWQBeZAfpwOESFFkAeDOgDaAcnFQK1FwF0AfLgB6ALNkAAs4WWQdfWQneUUQBm9kUHkIaiIYWPZuaGSAH1j4pW9cBHQQeWRdFiNTJwAGbwBuIA

### 💻 Code

```ts
interface Foo {
    overload(arg: number):void
    overload(arg: string):void
}
type P = Parameters<Foo['overload']>
// P has type [string] instead of [number] | [string]
const p: P = [0];
```

### 🙁 Actual behavior

Error: Type 'number' is not assignable to type 'string'.

### 🙂 Expected behavior

No error.
`P` should be `[number] | [string]`

**Comment by MartinJohns** [comment]
This is a documented design limitation: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types

**Comment by adiba** [comment]
> This is a documented design limitation: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types

Thanks, just found this myself. Sorry!
