### ISSUE TITLE
Proposal for enhancing ways to extend tsconfig file

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/TypeScript#56436]
### 🔍 Search Terms

"extends", "merge", "compilerOptions", "paths", "outdir", "include", "exclude", "typeRoots", "references", "tsconfig", "ability to merge tsconfig", "ability to make tsconfig paths relative to final config"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Today when you extend a config the options written in the final config override the options from the base config. Here is sample of what happens today:

```jsonc
// @fileName: /temp/test/base.tsconfig.json
{
    "compilerOptions": {
        "paths": {
            "@libs/*": ["libs/*"],
            "@project1/*": ["project1/*"]
        },
        "typeRoots": ["node_modules/@types"],
        "outDir": "dist"
    }
}
```

```jsonc
// @fileName: /temp/test/project1/tsconfig.json
{
    "extends": "../base.tsconfig.json",
    "compilerOptions": {
        "paths": {
            "@environment/*": ["env/*"]
        },
        "typeRoots": ["typings"]
    }
}
```

Here is what it would mean that project1 tsconfig was written as:

```jsonc
// @fileName: /temp/test/project1/computed.tsconfig.json
{
    "compilerOptions": {
        "paths": {
            "@environment/*": ["env/*"]
        },
        "typeRoots": ["./typings"],
        "outDir": "../dist"
    }
}
```

Over years users have asked us for ability to create a final config that adds to base config instead of overriding. This is extremely useful for `paths` from compiler options or say `references` that specify project references.

This would allow to users to write a base config that contains common options that shouldn't have to be copied in all projects and yet allowing projects to specify there additional specific options.

For example in above sample, one would expect a way to write config such that final `paths` property is:

```jsonc
// @fileName: /temp/test/project1/computed.tsconfig.json
{
    "compilerOptions": {
        "paths": {
            "@libs/*": ["../libs/*"],
            "@project1/*": ["../project1/*"],
            "@environment/*": ["env/*"]
        }
    }
}
```

Here is the proposal to add `merge` as root level config property that specifies options that need to merged instead of completely overwritten in the final config.
The values specified in merge can be root level properties: `files`, `include`, `exclude` and `references` or option names from either `compilerOptions`, `watchOptions` or `typeAcquisition` which are lists or object type eg. `paths`, `typeRoots`, `libs` etc.

From the above example writing the `project1` config as:
```jsonc
// @fileName: /temp/test/project1/tsconfig.json
{
    "extends": "../base.tsconfig.json",
    "compilerOptions": {
        "paths": {
            "@environment/*": ["env/*"]
        },
        "typeRoots": ["typings"]
    },
    "merge": ["paths", "typeRoots"]
}
```

per @andrewbranch 's suggestion here: https://github.com/microsoft/TypeScript/issues/56436#issuecomment-1821583108
other option is to write config as:
```jsonc
{
  "compilerOptions": {
    "extend": {
      "paths": {
        "@/foo/*": ["../packages/foo/dist/*"]
      }
    }
  },
  "extend": {
    "references": [
      { "path": "../packages/foo"  }
    ]
  }
}
// Note we probably need to call this merge since extends and extend are too close at root level ?
```

Would mean that project1 wrote the tsconfig as:
```jsonc
// @fileName: /temp/test/project1/computed.tsconfig.json
{
    "compilerOptions": {
        "paths": {
            "@libs/*": ["../libs/*"],
            "@project1/*": ["../project1/*"],
            "@environment/*": ["env/*"]
        },
        "typeRoots": ["../node_modules/@types", "./typings"],
        "outDir": "../dist"
    }
}
```

Note how the paths still remain relative to config they are defined in but allowing one to add more properties and if say baseConfig also had rule for `@environment/*` path mapping it is overwritten by the project1 specific. That is it does not recusively merge property values of path mappings.

Apart from having ability to specify specific options that get merged, users have often asked us for a way to specify config such that base config will specify option say `outDir` and instead of it being relative to the base config, it needs to be relative to project's tsconfig. 

For example in the above example, instead of all projects output going into `/temp/test/dist` the output to be inside each `dist` folder of each project.
Apart from `outDir` this would also help in writing base configs such that extending `base.tsconfig.json` would include project's `src` files and extending `base.test.tsconfig.json` would include `tests` files

With below configs:
```jsonc
// @fileName: /temp/test/base.tsconfig.json
{
    "compilerOptions": {
        "typeRoots": ["node_modules/@types"],
        "outDir": "dist"
    }
}
```

```jsonc
// @fileName: /temp/test/project1/tsconfig.json
{
    "extends": "../base.tsconfig.json"
}
```

Today the resulting config of project1 is:
```jsonc
// @fileName: /temp/test/project1/computed.tsconfig.json
{
    "compilerOptions": {
        "typeRoots": ["../node_modules/@types"],
        "outDir": "../dist"
    }
}
```

Proposal here is to add property `raw` with names of properties in base config such that extending it would mean as if project extending it specified them, making them relative to final config instead of the base config.

So with change to base.tsconfig.json as:
```jsonc
// @fileName: /temp/test/base.tsconfig.json
{
    "compilerOptions": {
        "typeRoots": ["node_modules/@types"],
        "outDir": "dist"
    },
    "raw": ["typeRoots", "outDir"]
}
```
per @andrewbranch suggestion option 2 to consider:
```jsonc
// tsconfig.base.json
{
  "compilerOptions": {
    "outDir": "${projectRoot}/dist"
  }
}
// need to parse each file path, is projectRoot allowed anywhere in the path or just start
```

would result in final project1 config as if it wrote:
```jsonc
// @fileName: /temp/test/project1/computed.tsconfig.json
{
    "compilerOptions": {
        "typeRoots": ["./node_modules/@types"],
        "outDir": "./dist"
    }
}
```

and another project2 say with `merge` property as:
```jsonc
// @fileName: /temp/test/project2/tsconfig.json
{
    "extends": "../base.tsconfig.json",
    "compilerOptions": {
        "typeRoots": ["typings"]
    },
    "merge": ["typeRoots"]
}
```

would result in configuration as if written as:
```jsonc
// @fileName: /temp/test/project2/computed.tsconfig.json
{
    "compilerOptions": {
        "typeRoots": ["./node_modules/@types", "./typings"],
        "outDir": "./dist"
    }
}
```

The property `raw` can be used for:
1. Options that are paths like: `outDir`, `declarationDir` etc
2. Options that list of paths like: `rootDirs`, `typeRoots` from `compilerOptions` or `excludeFiles`, `excludeDirectories` from `watchOptions`
3. `include` and `exclude` root config properties. (`files` and `references` are not included here as not sure if they really make sense?)
4. `paths` is a special option where normally the base path (property `pathsBasePath`) is relative to config they are declared in. So adding `paths` to `raw` would mean that path mapping is done relative to config file extending the root config file.

There was consideration of specifying `raw` extend as part of config extending root config but that would mean either writing something like `"rawExtend": ["outDir", "typeRoots"]` or  `"merge": [{ "name": "include", "kind": "raw" }]` in each config defeating the purpose of concise extend. Any feedback on that?

Should `merge` be in root config: probably not because if project wants to override or add should be part of project decision and it would need to add properties to list only if that config specifies to making this property of project config makes more sense.

TODO:
What happens to `raw` and `merge` when multi-level extending is in play. Probably they need to be merged instead of overwritten but need to think about that.

Here are issues this would help with:
https://github.com/microsoft/TypeScript/issues/44589
https://github.com/microsoft/TypeScript/issues/27098
https://github.com/microsoft/TypeScript/issues/20110
https://github.com/microsoft/TypeScript/issues/29172

### 📃 Motivating Example

A way to specify say project specific "paths" mapping without having to rewrite all the mappings from the base config.
And a way to specify root config that can specify `include` and/or `outDir` and not needing to write than in each project.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by andrewbranch** [comment]
I would definitely like to see more powerful options like these here. A few thoughts:

For `merge` functionality, I like the syntax that [Tailwind](https://tailwindcss.com/docs/theme#extending-the-default-theme) uses for distinguishing between overrides and extensions:

```json5
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    // Override:
    "paths": {
      "@libs/*": ["libs/*"],
      "@project1/*": ["project1/*"]
    },

    // Merge:
    "extend": {
      "paths": {
        "@libs/*": ["libs/*"],
        "@project1/*": ["project1/*"]
      }
    }
  }
}
```

I think the semantics can be the same as what you proposed, but (a) this scheme has prior art that will be familiar to many, and (b) the indicator that an extension is happening is more closely colocated with the property doing the extending.

Instead of `raw`, I think I prefer the use of interpolated variables, which I think have come up in some discussions in the past:

```json5
// tsconfig.base.json
{
  "compilerOptions": {
    "outDir": "${projectRoot}/dist"
  }
}
```

This is again just different syntax for the same semantics you proposed, but I like it because (a) it’s obvious what’s intended to happen just by looking at the option value, (b) it’s impossible to forget whether `"raw"` belongs in the extending or base config, and (c) the word “raw” doesn’t do as much for my intuition about what’s going to happen as seeing a variable placeholder (the name of which is debatable).

**Comment by sheetalkamat** [comment]
For `merge` i thought about having separate entry because of `references` which many people want to extend and is not part of `compilerOptions` and is array of objects and not object itself. 

For `raw` using syntax while more clear`${projectRoot}/dist`, it means that we have to do file path parsing on each config instead of relying on one property to do "transform" to either absolute path or use raw one.

**Comment by andrewbranch** [comment]
I find the desire to extend `references` pretty suspicious, but I think `extend` covers that well since it could appear both inside `compilerOptions` and at the root:

```ts
{
  "compilerOptions": {
    "extend": {
      "paths": {
        "@/foo/*": ["../packages/foo/dist/*"]
      }
    }
  },
  "extend": {
    "references": [
      { "path": "../packages/foo"  }
    ]
  }
}
```

Overall, I think clarity should be the top priority—it’s hard to imagine config parsing being a significant part of the total compilation time of a large app.

**Comment by sheetalkamat** [comment]
we probably need to use "merge"  instead of "extend" given we already have "extends" at root

**Comment by ArZargaryan** [comment]
+1 A very useful and necessary feature, especially in monorepositories (as in my case)

**Comment by antongolub** [comment]
Coincidentally, we are developing a system that requires processing of this kind of configs with a declarative extension (`preset`, `extends`) feature. And now we are also experimenting with the notation for describing different types of transformation.

The mentioned case now looks like this:
```js
const tsconfig = await populate('tsconfig.json', {
  rules: {
    compilerOptions: 'merge',
    'compilerOptions.paths': 'merge',
    'compilerOptions.typeRoots': 'merge'
  },
  vmap({value, cwd, root, prefix, key}) {
    if (cwd !== root && (
      prefix === 'compilerOptions.outDir' ||
      prefix.startsWith('compilerOptions.typeRoots.') ||
      /^compilerOptions\.paths\.[^.]+\./.test(prefix))
    ) {
      return path.join(path.relative(root, cwd), value)
    }
    return value
  }
})
```
It's definitely _too verbose_. So we're planning to use this proposal syntax instead:
```js
const tsconfig = await populate('tsconfig.json', {
    compilerOptions: 'merge',
    'compilerOptions.paths': 'merge',
    'compilerOptions.typeRoots': 'merge',
    'compilerOptions.outDir': 'rebase',  // to resolve any level rel paths from the root / entry point cwd.
    'compilerOptions.paths.*.*': 'rebase'
})
```

**Comment by sheetalkamat** [comment]
Closing this in favor of https://github.com/microsoft/TypeScript/issues/57485 and https://github.com/microsoft/TypeScript/issues/57486
