### ISSUE TITLE
`extends` expansion may not working with function return type

### ISSUE THREAD

**Issue by lihz6** [microsoft/TypeScript#56443]
### 🔎 Search Terms

"extends expansion"

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
type EventAction<T> = T extends (...args: any[]) => any ? never : T | (value: T) => T;

declare const test: EventAction<boolean>;
```

Expect `test` to be `boolean | (value: boolean) => boolean`, but got `boolean | (value: true) => true | (value: false) => false`.

### 🙁 Actual behavior

Got `boolean | (value: true) => true | (value: false) => false`.

### 🙂 Expected behavior

Expect `test` to be `boolean | (value: boolean) => boolean`.

### Additional information about the issue

Trying some work around, but didn't work:

```ts
type Action<T> = T | (value: T) => T;
type EventAction<T> = T extends (...args: any[]) => any ? never : Action<T>;

declare const test: EventAction<boolean>;
```
Expect `test` to be `Action<boolean>`, but got `Action<true> | Action<false>`.

**Comment by MartinJohns** [comment]
This is working as intended. As a generic argument `boolean` acts as the union `true | false`, so you end up with distributive behaviour in your conditional type.

**Comment by MartinJohns** [comment]
> Is there any way to get the expected result?

Yes, don't use a distributive conditional type. The documentation provides an example on how to opt-out of the distributive behaviour.

**Comment by MartinJohns** [comment]
> I believe the simplification should apply for the function

But that would be wrong. `(value: true) => true | (value: false) => false` is either a function that always accepts `true` and returns `true`, or it's a function that always accepts `false` and returns `false`. But `(value: boolean) => boolean` is a function that either accepts `true` or `false`, and returns either `true` or `false` (regardless of the input argument).

Same thing would apply to objects, having a property that is **always** `true` or **always** `false`, or having a property that can be either of those two values.

**Comment by fatcerberus** [comment]
Yeah, `Foo<T> | Foo<U>` -> `Foo<T | U>` is not a valid substitution in general.
