### ISSUE TITLE
[IDE feature]Adding auto completion when typing `.` or something else as a prefix of a field of a type like language zig.

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#56444]
### 🔍 Search Terms

auto completion

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When you create a instance of a type t, you would need going to the definition of type t to know what field does type t has, this is too trivial if the definition of type t is relative huge. I know that the language zig and it's language server can complete the field when you type dot in creating an struct instance, so may be we can also make this useful ablitity in typescript, just removing dot after user finished choosing a field.

See the example below.

![auto-completion](https://github.com/microsoft/TypeScript/assets/21278900/ab4efd67-74e0-425d-9b6e-bc0de7355e3e)

### 📃 Motivating Example

```typescript
type Person = {
  name: string
  age: number
  ...
}

const p: Person = {
 // line 8
  .
}
```
When typing dot at the line8, the ts language server can create completion of [name, age, ...], and the user can choose field in the completion tips, the dot will be removed after the user finished choosing field.

Here is the example in zig language.
![auto-completion](https://github.com/microsoft/TypeScript/assets/21278900/79acee58-562b-4527-b81b-e0a8dd905fbf)

### 💻 Use Cases

1. What do you want to use this for?
  This ide feature would be very useful in our daily development.
2. What shortcomings exist with current approaches?
 As far as i know, there is no approache for now.
3. What workarounds are you using in the meantime?
  For now, i need go to the definition of type or just create another window and open the definiton in the new window.

**Comment by MartinJohns** [comment]
This already works. Just press ctrl + space.

**Comment by Mng12345** [comment]
@MartinJohns Ohh! thanks.
