### ISSUE TITLE
Why is TypeScript not detecting implicit use of any in nested object/array properties?

### ISSUE THREAD

**Issue by UROjQ6r80p** [microsoft/TypeScript#56454]
### 🔎 Search Terms

typeguarding nested unkown object, typescript not detecting implicit use of any

### 🕗 Version & Regression Information

Why is Typescript not detecting that I've checked only part of unknown type, and not it's nested properties thus resulting in runtime error?

```
interface User {
    name: string,
    age: number
}

const externalData: unknown = [1, 2, 3];

(Array.isArray(externalData) ? externalData : [])
    .reduce<User[]>((acc, curr) => {
        return [
            ...acc,
            {
                name: curr.some.nested.property, // not detecting that these properties may not exist on type 'any'
                age: curr.some.nested.another.propety // not detecting that these properties may not exist on type 'any'
            }
        ]
    }, []);
```

### ⏯ Playground Link

https://www.typescriptlang.org/play#code/AQ4SwOwFwUwJwGYEMDGNgFUDO9gG8AoUY4CJAWxgC5gso5IBzAGiJJCUetIFdyAjeGxABfAsOAoA9hDrAYAD1hwyAGwAiSKEho8IAawhSA7hGABeYAG0AjM2AAmewGYAugG5xxABQBBOHBIAJ4AdGBY-oFB3orKapraAJTAAPzySvDxWkjANFauiRLEIXAwACY8aAA82PD5AHze3qgo9ig8Acnm9fhF7MClUB1mVn39oCGTLazj44SzC6QU3O0BIVhSlCEQMHTlIQAOcFIH8FBB9gD0l6RSUMBlMLAoUEzAUAAWWu8fu+hHJzOYF2wHIwVu90U4XuMneQVOwAA5EgIEFEWNFhwuDRVnB1psYNtdrAyiEUXdfniAadzsBrhCHk8YC83p9vp8-sBqUCQWCggyoXJYecEcjUejMcQxJjXBiRPZ8ol3EA

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

Typescript is not detecting implicit use of 'any'

### 🙂 Expected behavior

To detect use of any.

**Comment by MartinJohns** [comment]
Because there's no implicit `any`. Your call to `Array.isArray` explicitly types it.

Also, you didn't fill out the issue template correctly.
