### ISSUE TITLE
RegExpExecArray has incorrect type for named groups

### ISSUE THREAD

**Issue by Qrokqt** [microsoft/TypeScript#56457]
### 🔎 Search Terms

regex

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about regex
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99#code/MYewdgzgLgBATgUwOYIB4wLwzAg7jAJWQFFUAHACgHIKB+AHgDMQQA+AIwEM4BKKngNwAoUJFiIImeMjQA6NAmDUucfsICWjChNqykcEAFcyEHjADeQmNZiiIIADYJZDkEgpQAnmQQhG0iD0DY0CuAC9BIQBfIA

### 💻 Code

```ts
const regex = new RegExp('(?<foo>bar)');
const res = regex.exec('bar');
if(res?.groups) {
    console.log(typeof res.groups.baz);
}
```

### 🙁 Actual behavior

typescript thinks the values inside RegExpExecArray.groups are strings

### 🙂 Expected behavior

the values inside RegExpExecArray.groups should be string | undefined

**Comment by fatcerberus** [comment]
The type of the `groups` property is `{ [key: string]: string }`, so like all string index signature types, property accesses are assumed to exist.  You have to enable `noUncheckedIndexedAccess` to get `string | undefined`.
