### ISSUE TITLE
Unclear behavior in recursion type

### ISSUE THREAD

**Issue by kayac-chang** [microsoft/TypeScript#56462]
### 🔎 Search Terms

"Type instantiation is excessively deep and possibly infinite."
"recursive types"

### 🕗 Version & Regression Information

- This changed between versions _5.0.4_ and _5.4.0_
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Type instantiation is excessively deep and possibly infinite.`

### ⏯ Playground Link

1. [The first one](https://shorturl.at/cgxU1)
2. [The second one](https://shorturl.at/djmCM)
3. [The third one](https://shorturl.at/epyBX)

### 💻 Code

I worked on a project for serialization and tried my best to check the parameters passing from the user strictly, 
so there's a deep check for nested data. 
But the recursive check gives me the "Type instantiation is excessively deep and possibly infinite." error, 
and I try my best to research how to solve this, but it gets even more confusing.
I am still looking for the expected behavior in the documentation.

### 🙁 Actual behavior

To demonstrate my confusion, I created three playgrounds.

1. [The first one](https://shorturl.at/cgxU1)
In line 84, the compiler raised the "Type instantiation is excessively deep and possibly infinite." error.
```ts
declare function serialize<const S extends Schema, V extends Value<S>>(schema: S, value: V): Bytes;
```

2.  [The second one](https://shorturl.at/djmCM)
In line 84, I use the `value: Value<S>` instead of `V extends Value<S>`.
Now, line 84 does not throw the "Type instantiation is excessively deep and possibly infinite." error.
```ts
declare function serialize<const S extends Schema>(schema: S, value: Value<S>): Bytes;
```
But in line 88, the compiler raised the "Type instantiation is excessively deep and possibly infinite." error.
```ts
serialize("u8", 1); 
```

3. [The third one](https://shorturl.at/epyBX)
Following the second one, we add `'u8'` type argument in line 88.
Now, it has passed. But why?

```ts
serialize<'u8'>("u8", 1); 
```

### 🙂 Expected behavior

My original expectation is that the recursive type should work ideally to check the parameter, even the nested data structure.

But recursive type raised "Type instantiation is excessively deep and possibly infinite." error,
Even worse, the location where the error was raised will change for unclear reasons.

Even worse, if we pass `u8`, the error will gone.

**Comment by rotu** [comment]
It *would* be nice to have a trace of the first and last few type constructors in the chain.

The current behavior is akin to printing an error and throwing out the stack trace.
