### ISSUE TITLE
Create a file parsing cache to improve the speed of opening a large-scale project not for the first time.

### ISSUE THREAD

**Issue by fxsg20151212** [microsoft/TypeScript#56469]
### 🔍 Search Terms

index cache.

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

1. When the project is opened for the first time, an index cache is created.
2. When a project is opened for the second time, information is directly read from the index cache to accelerate the parsing of dependency information in the project. You do not need to parse the information again each time the project is opened.

### 📃 Motivating Example

no

### 💻 Use Cases

1. What do you want to use this for?
     The index speed of opening a large project (for example, a project contains 1 million lines of code) is improved.
2. What shortcomings exist with current approaches?
    Now it's re-parsing every time, which is time-consuming.
4. What workarounds are you using in the meantime?
    no.

**Comment by andrewbranch** [comment]
https://www.typescriptlang.org/tsconfig#incremental
