### ISSUE TITLE
[5.3] Type error in typescript.d.ts with exactOptionalPropertyTypes = true

### ISSUE THREAD

**Issue by uid11** [microsoft/TypeScript#56478]
### 🔎 Search Terms

"exactOptionalPropertyTypes", "JsDocParsingMode".

### 🕗 Version & Regression Information

- This changed between versions 5.2.2 and 5.3.2
- I think, this changed in commit or PR https://github.com/microsoft/TypeScript/pull/55739

### 💻 Code

```ts
// "exactOptionalPropertyTypes": true,

import type { CompilerOptions } from "typescript";

export type { CompilerOptions };
```

### 🙁 Actual behavior

Error:
```
node_modules/typescript/lib/typescript.d.ts:3287:24 - error TS2420: Class 'Project' incorrectly implements interface 'LanguageServiceHost'.
  Types of property 'jsDocParsingMode' are incompatible.
    Type 'JSDocParsingMode | undefined' is not assignable to type 'JSDocParsingMode'.
      Type 'undefined' is not assignable to type 'JSDocParsingMode'.

3287         abstract class Project implements LanguageServiceHost, ModuleResolutionHost {
                            ~~~~~~~


Found 1 error in node_modules/typescript/lib/typescript.d.ts:3287

```

### 🙂 Expected behavior

No error.

### Additional information about the issue

Minimal repository with bug reproduction: https://github.com/uid11/jsDocParsingMode-error-example.

As far as I can see, to fix this error, it is enough to replace the line 
https://github.com/microsoft/TypeScript/blob/c266e47794fbd187425989448670238576523d4e/src/services/types.ts#L435
with 
```ts
    jsDocParsingMode?: JSDocParsingMode | undefined;
```

Although, perhaps, such errors with `exactOptionalPropertyTypes` are corrected differently.

**Comment by jakebailey** [comment]
Working on this; there are more errors than just this one.
