### ISSUE TITLE
Unexpected 5.3.2 version tagged on npm

### ISSUE THREAD

**Issue by swissspidy** [microsoft/TypeScript#56473]
### 🔎 Search Terms

5.3 is not released yet, but 35 minutes ago a version 5.3.2 was released on npm. https://www.npmjs.com/package/typescript/v/5.3.2?activeTab=versions

What's going on?

### 🕗 Version & Regression Information

- This is an unexpected release

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

`npm outdated` tells me I can update to TypeScript 5.3.2

### 🙂 Expected behavior

No 5.3.2 release available on npm yet

**Comment by Andarist** [comment]
It's already released and even the announcement blog post is already out: https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/

I think that you just caught this very early - it's impossible to sync up a blog post, npm release and a GitHub release perfectly 😉

**Comment by swissspidy** [comment]
Ha, fascinating! I searched for an announcement too as I thought it was imminent, but couldn't find it. Plus I found it odd that there was no 5.3 or 5.3.1 version & 5.2.2 is still marked as `latest`

**Comment by DanielRosenwasser** [comment]
I've published 5.3.2 on GitHub as well.

**Comment by andrewbranch** [comment]
Patch versions 0 and 1 are beta and RC releases for us, so those are always `5.3.0-beta` and `5.3.1-rc`, with `.2` typically being the first unsuffixed stable release. npmjs.com also notoriously lags `npm info`.
