### ISSUE TITLE
Type definitions for `Promise.withResolvers()`

### ISSUE THREAD

**Issue by mkubilayk** [microsoft/TypeScript#56483]
### ⚙ Compilation target

esnext

### ⚙ Library

ESNext

### Missing / Incorrect Definition

`Promise.withResolvers()` is missing type definitions.

It is a Stage 3 TC39 proposal that is shipping in [Chromium 119](https://chromestatus.com/feature/5810984110784512), [Firefox 121](https://bugzilla.mozilla.org/show_bug.cgi?id=1845586) and soon in other runtimes.

### Sample Code

```TypeScript
const { promise, resolve, reject } = Promise.withResolvers();
//                                           ^ Property 'withResolvers' does not exist on type 'PromiseConstructor'.(2339)
```

### Documentation Link

https://github.com/tc39/proposal-promise-with-resolvers

**Comment by mkubilayk** [comment]
An update from this week's TC39 meeting: the proposal advanced to Stage 4 yesterday. 🥳 

https://twitter.com/robpalmer2/status/1729216597623976407

**Comment by linusg** [comment]
@sandersn If you haven't started working on this yet I'd be interested in submitting a PR!

**Comment by angelhdzmultimedia** [comment]
Hello! Just to confirm:

I tried with typescript 5.3.3 and didn't work, but upgraded to 5.4.0-dev.20240215 and it worked.
So I set my VSCode workspace typescript version to that one instead.

So I'll wait until VSCode typescript's version gets updated to officially start using `Promise.withResolvers`. 

Good stuff! 🔥😍🎉👏

**Comment by SerkanSipahi** [comment]
@angelhdzmultimedia How did you enable Promise.withResolvers in TypeScript >= 5.4?

**Comment by angelhdzmultimedia** [comment]
> [@angelhdzmultimedia](https://github.com/angelhdzmultimedia) How did you enable Promise.withResolvers in TypeScript >= 5.4?

![Image](https://github.com/user-attachments/assets/9344d5c6-8187-43d3-8eae-e209ac64f4f5)

When I started digging, apparently the types were added, but not the implementation. I remember I used to polyfill it myself.

"Gaslight me you should not". - Me  🤣

Anyway, it's working now right? My VSCode TS version is 5.7.3. I also use `tsx` for running Node typescript code.
And it has been working also when using Vite web based projects like Nuxt or Vue.

All the information provided will be appreciated.

**Comment by acutmore** [comment]
> When I started digging, apparently the types were added, but not the implementation.

TypeScript doesn't implement APIs, only syntax.

**Comment by SerkanSipahi** [comment]
In `tsconfig.lib`, we must add `ESNext.Promise` and then it works.
