### ISSUE TITLE
`keyof` losing type information when used with generics extend

### ISSUE THREAD

**Issue by Lonli-Lokli** [microsoft/TypeScript#56484]
### 🔎 Search Terms

extends generics keyof 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about types

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBASg9gdygXigbwFBW1BBLAE2AAsAuKAOwFcBbAIwgCcBuDAXww1EigGE4ANrQop0WHPiJlKtBi3HZiEPAHNiwctXpNWHDAGM4FAM7AoxkDVEBlS3UEAKAJRdw0AKoU8ARyrRUmDhQANoWNAC6mrI6ClAAjOQAhhQgsUYCIAAKjHBg5KaMeBQqupz6AonGxlAAQlR4AgRMADwAKgB8YrFgVHQCePpQjFQUDnjkAKIAHsCMifrAzQDWECBwAGZQrQA05rNFKp0APlAOziidWnJOTmJBQXibDtwQG1B4KMioAOQFB9+3QL3YGGEyCCAAOgEcBUYyhEGKJBcwOwbCgEAExmgQJROFBxnBUJhY2cyJRHCCHD06xGCzwRlwczAkEYbXRMwRBGq8CQJ34QhoFHaDjo9UaTHIdQaTVZHUBsVF0qYEOGo2+khIAOYUAA9DqoAA5OBmOBLKAAWk6AEFGCpaAiTZsXlBfvtit93tUKMaoJVjKoKIk+tBgHAoGBEnMaBBgEwoG9nd8zrdkJdooxbidprN5osVmtNjs9oViu1vhCHAAmADMABYAKwuPQUCBIKXi1k84VOFUjBzqwialwtttimXNLvOXtqjXESsA3X6gDyAGkLejGDlGBgR7Uxy1Jz3VcmLlBG5wgA

### 💻 Code

```ts
type Row = {
    width: number;
}

type Column = {
    width: number;
    height: number;
}

const sym = Symbol()
type Unique = {
    [sym]: number;
    1: any
    onlyProp: string;
}

class Builder<T> {

    public run(i: Extract<keyof T, string> | (() => number)) {
        if (typeof i === 'string') {
            console.log(i.length)
        } else {
            console.log(i())
        }
    }
}

function wrapper<T extends Row | Column>(builder: Builder<T>) {
    builder.run('width'); // Not ok -> Argument of type 'string' is not assignable to parameter of type '(() => number) | Extract<keyof T, string>'.(2345)
}

new Builder<Row>().run('width')
new Builder<Row>().run('width2') // OK - error
new Builder<Row>().run(() => 5)


```

### 🙁 Actual behavior

Argument of type 'string' is not assignable to parameter of type '(() => number) | Extract<keyof T, string>'.(2345)

### 🙂 Expected behavior

No errors for existing string properties

**Comment by fatcerberus** [comment]
No type information is “lost”, the `Extract` is just deferred because `T` is generic.

**Comment by andrewbranch** [comment]
I suggest writing it [like this](https://www.typescriptlang.org/play?#code/C4TwDgpgBASg9gdygXigbwFBW1BBLAE2AAsAuKAOwFcBbAIwgCcBuDAXww1EigGE4ANrQop0WHPiJlKtBi3HZiEPAHNiwctXpNWHDAGM4FAM7AoxkDVEBlS3UEAKAJRdw0AKoU8ARyrRUmDhQANoWNAC6mrI6ClAAjOQAhhQgsUYCIAAKjHBg5KaMeBQqupz6AonGxlAAQlR4AgRMADwAKgB8YrFgVHQCePpQjFQUDnjkDgDWECBwAGZQrU5QAGTmwIXFUAA+UA7OKJ1ack7LgUE4eAsO3BDzUHgoyKgA5AVFKi9nsRc4hiaCCAAOgEcBUYxBEGKJBcv2wbCgEAExmg5zhfyMxkBILBY2csLhHCCHD0cxG+mAeCMuEYiTAkEYbURAA9gFCCNV4EhdvwhDQKO0HHR6o0mOQ6g0moyOt8gsLJUwgcNRi9JCQvswoAB6LVQABycDMcEmUAAtJ0AIKMFS0KFGha3KBvDYfF4PaoUQ1QSrGVQURJ9aDAOBQMCJWk0CBsxhQe6Ol77ZbII7RRjLXYAUVZtIpzWmswWrQANOtNip2i8gQ4AEwAZgALABWFx6CgQJAS0WMrmCpxKkYOVWEdUuNsdkVS5o95z9lVq4jVr7a3UAeQA0mbEYwcowMGPahOWtO+8rE4coM3OEA) to avoid our limited ability to reason about generic conditional types

**Comment by Lonli-Lokli** [comment]
@andrewbranch thanks, we are using this way too, but I was expecting to see `Extract` to behave the same.
@fatcerberus thanks, is there anywhere more detailed explanation why it's not an issue?

**Comment by fatcerberus** [comment]
`Extract` is implemented as a distributive conditional type, specifically `T extends U ? T : never`; such types have to be evaluated for each member of a union individually, so in general they can't be resolved until the compiler knows exactly what type `T` is.  Until then, nothing is considered assignable to it.
