### ISSUE TITLE
Regression in 5.3 tsconfig cannot extend node module

### ISSUE THREAD

**Issue by jd-carroll** [microsoft/TypeScript#56492]
### 🔎 Search Terms

tsconfig module extends

### 🕗 Version & Regression Information

Version with issue: v5.3.2

Downgraded to v5.2.2 and issue is resolved

### 💻 Code

Monorepo with `tsconfig.json` in each project that looks like:
```
{
  "extends": "@project/tsconfig/nextjs.json",
  "compilerOptions": {
     ...
  }
}
```

Structure of `@project/tsconfig`
```
packages
  |- tsconfig
      |- package.json
      |- tsconfig.json  
```

### 🙁 Actual behavior

Fails to run the script

```shell
monorepo % lerna run dev --scope @client-sites/main
info cli using local version of lerna
lerna notice cli v7.4.2
lerna notice filter including "@client-sites/main"
lerna info filter [ '@client-sites/main' ]
lerna info Executing command in 1 package: "yarn run dev"
@client-sites/main: /path/to/monorepo/node_modules/ts-node/src/index.ts:859
@client-sites/main:     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
@client-sites/main:            ^
@client-sites/main: TSError: ⨯ Unable to compile TypeScript:
@client-sites/main: error TS6053: File '@project/tsconfig/nextjs.json' not found.
@client-sites/main:     at createTSError (/path/to/monorepo/node_modules/ts-node/src/index.ts:859:12)
@client-sites/main:     at reportTSError (/path/to/monorepo/node_modules/ts-node/src/index.ts:863:19)
@client-sites/main:     at createFromPreloadedConfig (/path/to/monorepo/node_modules/ts-node/src/index.ts:874:36)
@client-sites/main:     at create (/path/to/monorepo/node_modules/ts-node/src/index.ts:624:10)
@client-sites/main:     at Object.register (/path/to/monorepo/node_modules/ts-node/src/index.ts:591:15)
@client-sites/main:     at Object.<anonymous> (/path/to/monorepo/node_modules/ts-node/register/index.js:1:16)
@client-sites/main:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
@client-sites/main:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
@client-sites/main:     at Module.load (node:internal/modules/cjs/loader:1091:32)
@client-sites/main:     at Function.Module._load (node:internal/modules/cjs/loader:938:12) {
@client-sites/main:   diagnosticCodes: [ 6053 ]
@client-sites/main: }
```

### 🙂 Expected behavior

For the script to actually run the dev server

```shell
monorepo % lerna run dev --scope @client-sites/main
info cli using local version of lerna
lerna notice cli v7.4.2
lerna notice filter including "@client-sites/main"
lerna info filter [ '@client-sites/main' ]
lerna info Executing command in 1 package: "yarn run dev"
@client-sites/main: Successfully wrote configuration: ...
...
```

**Comment by jakebailey** [comment]
If you're able to control your TypeScript version, can you bisect using https://www.npmjs.com/package/every-ts ? You haven't provided a project to test on so we can't really do anything.

**Comment by jakebailey** [comment]
Also, this error is given by ts-node; can you reproduce it with just tsc?

**Comment by VirtualWolf** [comment]
I've added a really simple repo [here](https://github.com/VirtualWolf/ts-node-typescript-issue) that demonstrates the issue. 

`tsc` doesn't have any problems at any point, it's only running via `ts-node` that doesn't work. Downgrading to Typescript 5.2.2 or updating the `ts-config.json` `extends` option to include `./node_modules` both work to fix it.

**Comment by tanimaroy2012** [comment]
im seeing the same issue so far @VirtualWolf solution is working for me

**Comment by andrewbranch** [comment]
For the record that overload is `@internal`. The public API didn’t change but I guess ts-node needed to access the internal one. They’ll need to make an update on their end. Thanks @effektsvk!

**Comment by matsko** [comment]
Just use `tsx` instead of `ts-node`

**Comment by cd-ff** [comment]
`ts-node` issue: https://github.com/TypeStrong/ts-node/issues/2076

**Comment by SStranks** [comment]
It doesn't work for me on either ts-node or tsx, on TS 5.3 or 5.2.
