### ISSUE TITLE
Contextual `never` parameter type gets precedence over the initializer's type

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#56505]
### 🔎 Search Terms

contextual parameter type initializer never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20231122#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxAGcMAeAKHngBUBhPQgDwwBpKaBZEDACx2CLwQzEKgHwASuBwxgpEjCyoA5i3gAKTIwBcNeqiat4AOlOxlRXahAA3EDADaAXQCU8ALwA+eGgDWqHAB3VE82T00GYQxdOkjmNQBbbj4BGK5efiIXXRscLGAAbnJyQhJ1dgBvdiowHDRo+AAGNioAXxb4KqoannBfABksBKwGzQxGRKhGD3gAVkbGty9O9ur4HigiAEEwMGJLDS01ZCJ7XQr4VCgk3QUlZXhWpe8K1ba2FyKgA

### 💻 Code

```ts
declare function test<
  TContext,
  TMethods extends Record<string, (ctx: TContext, ...args: never[]) => unknown>,
>(context: TContext, methods: TMethods): void;

test(
  {
    count: 0,
  },
  {
    checkLimit: (ctx, max = 500) => {},
    hasAccess: (ctx, user: { name: string }) => {},
  },
);
```

### 🙁 Actual behavior

`never` gets assigned as the type of `max` parameter and TS errors on the initializer's type mismatch:
> Type 'number' is not assignable to type 'never'.(2322)

### 🙂 Expected behavior

I'd expect the type inferred from the initializer to take precedence over `never` here. After all, we could annotate this contravariant position with `max: number = 500` and that wouldn't violate any constraints.

**Comment by fatcerberus** [comment]
For what it's worth, this isn't specific to `never` and in fact is a more general issue that TS doesn't care about the initializer type at all: if the contextual parameter type is, say, `1 | 2 | 3`, then this is *also* an error when it doesn't need to be (a function that takes `number` is assignable to one that takes `1 | 2 | 3`).

**Comment by Andarist** [comment]
Good point. I can probably tweak this somewhat easily by checking the assignability between the initializer's type and the contextual type - just in the right direction.
