### ISSUE TITLE
Missing types for Window Management API

### ISSUE THREAD

**Issue by Franziskus1988** [microsoft/TypeScript#56518]
### ⚙ Compilation target

ESNEXT

### ⚙ Library

ESNEXT, DOM

### Missing / Incorrect Definition

Hi, I just recognized that there are no types for the new Window Management API, which is already supported in Chrome. I've already seen this issue #51794 and I've read the comments. Since it might often be the case that developers need to play around with experimental features I would have 2 follow-up questions:

1. If I got it right Typescript types are already generated from MDN. Is there a tool / API to generate types from MDN on my own? 
2. Would it be an idea to automatically push experimental features to a certain "@types space". So in case of Window Management API something like `@types/mdn-experimental-window-mangement-api`. Than I could add the types on my own. 

Spreading `//@ts-expect-error` or even worse, using plain JS 😱, are not really nice solutions. 

### Sample Code

```TypeScript
window.getScreenDetails();
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/Window_Management_API

**Comment by MartinJohns** [comment]
See https://github.com/microsoft/TypeScript-DOM-lib-generator#when-the-type-is-missing:

> check whether it's supported by two or more browser engines.

Your types seem to be supported by only one engine. *Usually* types for experimental API are not added.

**Comment by guillaumebrunerie** [comment]
Check out the `@types/webscreens-window-placement` npm package.

**Comment by Franziskus1988** [comment]
> Check out the `@types/webscreens-window-placement` npm package.

Didn't found this on my own 🤦‍♂️
