### ISSUE TITLE
False 'extends clause uses private name'

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#5651]
```typescript
var x: {
    new<T>(s: any): Q;
}

class Q {
    s: string;    
}

class B extends x<string> {    
}

var q: B;
q.s;
```

Compiler yields:
TS4020	Extends clause of exported class 'B' has or is using private name 'x'.

That's not correct because 'x' is a global variable.

**Comment by zhuravlikjb** [comment]
Reproduces only if '-d' flag is specified

**Comment by enriched** [comment]
:+1:
