### ISSUE TITLE
[REG 5.2->5.3] parameter initialization is not accepted in abstract function

### ISSUE THREAD

**Issue by orgads** [microsoft/TypeScript#56525]
### 🔎 Search Terms

A parameter initializer is only allowed in a function or constructor implementation.

### 🕗 Version & Regression Information

- This changed between versions 5.2.2 and 5.3.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.2#code/IYIwzgLgTsDGEAJYBthjAgQmgpgg3gLABQCCokM8CAZgK4B2sAFPrQPbsIC8twyYPAF8AlAC4EAN3YBLACYBuEkJJA

### 💻 Code

```ts
abstract class Base {
  abstract func({ foo = false }): void;
}
```

### 🙁 Actual behavior

Error TS2371: A parameter initializer is only allowed in a function or constructor implementation.

### 🙂 Expected behavior

It should be accepted.

**Comment by Andarist** [comment]
Abstract methods are erased at runtime. I don't think allowing initializers (a purely runtime feature) in them is something that should be allowed.

**Comment by orgads** [comment]
Then should it be declared this way?
```ts
abstract class Base {
  abstract func({ foo }: { foo?: boolean }): void;
  client() { this.func({}); }
}
```

**Comment by MartinJohns** [comment]
Yes. Afaik the default value is considered an implementation detail, not part of the signature.
