### ISSUE TITLE
Symbol description property should not forget its value.

### ISSUE THREAD

**Issue by rotu** [microsoft/TypeScript#56535]
### 🔎 Search Terms

symbol, description

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?esModuleInterop=false&declaration=false&target=9&jsx=0&module=7&stripInternal=false&noErrorTruncation=true&ts=5.4.0-dev.20231124&ssl=10&ssc=48&pln=1&pc=1#code/MYewdgzgLgBBCeBbGBeGBlJAjEAbAFAOQBmIIhAlAFBUD0tMUAFgJYQwCGEELA5mIgCmYWBCYgArrgAmMAO4gATgGsqoSLAAeALgDe0wRGCKWABygtw2kmUIBfVHCQ16jVuwUqOiyWFnSQQxgwEFhPVXVoGHhHBGQuGHwJMBYARwlBJ0QcXBgAMhh9Q2MzCysbcjtqOgZmNnklZXYsCVhBRS4guJyYZLSMsEMINXAogC9YpE52fG68fMKDIxNzSzBrUkqKIA

### 💻 Code

```ts
const sym = Symbol('foo')

// this assignment should work
const x:{description:'foo'} = sym

// this workaround does not work
const y = sym as (unique symbol & {description:'foo'})

// this works but erases symbol uniqueness
const z = sym as (symbol & {description:'foo'})
```

### 🙁 Actual behavior

The assignment fails with
> Type 'typeof sym' is not assignable to type '{ description: "foo"; }'.

Typescript infers `sym` as a `unique symbol` with a `readonly description` property of type `string | undefined`.

Note that you can't correct this with an intersection type (as also illustrated in the example)

### 🙂 Expected behavior

Typescript should infer that `description` is of type `"foo"` and permit the assignment.

**Comment by andrewbranch** [comment]
You’re looking for

```diff
- const y = sym as (unique symbol & {description:'foo'})
+ const y = sym as (typeof sym & {description:'foo'})
```

**Comment by rotu** [comment]
@andrewbranch You're right! Adding a wrapper type works.

It seems an assertion does as well:

```typescript
const sym = Symbol('foo')
assert(sym.description === 'foo')
```

**Comment by rotu** [comment]
@andrewbranch why did you mark this as a question? Is there a design reason the auxiliary type or the assertion should be needed at all?

**Comment by andrewbranch** [comment]
Yes, this is working as intended; I sometimes use "Question" to indicate that the OP was trying to solve a problem and found a solution, even if they went in thinking they were seeing a bug.
