### ISSUE TITLE
Force adding module to System.register on import

### ISSUE THREAD

**Issue by tfrydrychewicz** [Microsoft/TypeScript#5653]
How do I force TS to add "unused" module to generated ```System.register(...)```?

Consider below example. 
```typescript
import {TypeA} from './typeA';

class TypeB {

   public foo(a: TypeA) {
   }

}
```

I'd like TS to generate
```javascript
System.register(['./typeA'], function(exports_1) { 
... 
});
```

Is it possible to force TS compiler to do that without actually using ```TypeA``` as a function. 

I'm using TS 1.6.2 with 

```json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": false,       
    "removeComments": true,    
    "sourceMap": true,
    "module": "system",    
    "target": "es5",    
    "experimentalDecorators": true    
  },
  "exclude": [
    "node_modules",
    "jspm_packages"    
  ]
}
```

**Comment by vladima** [comment]
you can use 
```ts
import "./typeA";
```
TypeScript compiler never elides such imports assuming that they are added purely for side-effects of its loading

**Comment by tfrydrychewicz** [comment]
Adding extra import is a worst solution i could think of (from my aesthetic point of view :D) Isn't there any other option?

**Comment by vladima** [comment]
well if module imports is never used in a value position but there is still a reason why you want this module to be loaded then I suspect that this reason is - side effects from module being loaded. If this is the case then `import "./typeA"` is a right solution from ES6 perspective.

**Comment by vladima** [comment]
also as a note if `TypeA` does not have value side (i.e. it is interface) then per ES6 spec this code will crash in runtime since imported name `TypeA` does not exists in module `./typeA`
```ts
import {TypeA} from './typeA';
```

**Comment by tfrydrychewicz** [comment]
If there is no other way, I'll have to take that one :) I understand the ES6 way of making that clear choice for loading a module for it's side effects. I just wanted that to be more "transparent" for end developer, so that he doesn't have to know that this particular module does have some side effect. 

Thanks!
