### ISSUE TITLE
`constructor` has wrong type in intersections

### ISSUE THREAD

**Issue by somebody1234** [microsoft/TypeScript#56531]
### 🔎 Search Terms

intersection, constructor

### 🕗 Version & Regression Information

Unknown. Seems to be an issue even in 3.3.3333, so this might be a design limitation.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.2#code/JYOwLgpgTgZghgYwgAgILIN7LgLmQRmQF8AoUSWRFAIU2QHIEB7EAZzCgFcEwmp68hUuWjwkyAMLIIAD0ggAJqzQAaZLQykwATwAOKAOoALOGEIBeNAG1GLdlx596AXRIB6N8i8A9APwkdfWRjUwAmZEtqG2Y2Dm5eflcPL2Q-AL1DEzAAZgjkAApNAEpouzjHRPdPH39AzNMAFjzC5Bj7eL5BYhLbWIcElyqUtLrgrIBWPIlSvo7K5Jr0oJCwADZm9AAydR628oGk6tT-IA

### 💻 Code

```ts
interface A { a: 1 }
interface B { 'constructor': 1 }
interface C extends A, B {}
type What1 = A['constructor']
//   ^? - type What1 = Function
type What2 = B['constructor']
//   ^? - type What2 = 1
type What3 = ({})['constructor']
//   ^? - type What3 = Function
type What4 = ({ constructor: 1 })['constructor']
//   ^? - type What4 = 1
type What5 = C['constructor']
//   ^? - type What5 = 1
type What6 = (A & B)['constructor']
//   ^? - type What6 = Function & 1
```

### 🙁 Actual behavior

`What6` is `Function & 1`

### 🙂 Expected behavior

`What6` is `1`. I'd accept it being `Function` instead, but I'm not sure it should be *both*...

**Comment by andrewbranch** [comment]
This may appear unexpected, but I think it’s internally consistent and a perfectly valid interpretation of the types. The thing that makes this ok is that you are prevented from constructing a value of this nonsense type:

```ts
const x: (A & B) = { a: 1, constructor: 1 };
//                         ^^^^^^^^^^^
// Type '1' is not assignable to type 'Function & 1'.
//  Type 'number' is not assignable to type 'Function'.(2322)
```

https://www.typescriptlang.org/play?ts=5.3.2#code/JYOwLgpgTgZghgYwgAgILIN7LgLmQRmQF8AoUSWRFAIU2QHIEB7EAZzCgFcEwmp68hUuWjwkyAMLIIAD0ggAJqzQAaZLQykwATwAOKAOoALOGEIBeNAG1GLdlx596AXRIB6N8i8A9APwkdfWRjUwAmZEtqG2Y2Dm5eflcPL2Q-AL1DEzAAZgjkAApNAEpouzjHRPdPH39AzNMAFjzC5Bj7eL5BYhLbWIcElyqUtLrgrIBWPIlSvo7K5Jr0oJCwADZm9AAydR628oGk6tT-Ej3kGTx8rZ28rFwCNT3+zoJiAG4gA

The reason `Function & 1` doesn’t immediately reduce to `never` is it’s very similar to the mechanism that allows for tagged primitive types:


```ts
type Path = string & { __brand: "path" };
```

**Comment by somebody1234** [comment]
@andrewbranch Fair - but `const x: C` produces no error, right? So while I understand that `Function & 1` is a *valid* type, it is not consistent with `interface extends`, as compared to using an intersection - I'd expect `extends A, B` to be more or less equivalent to `A & B`.


Perhaps importantly: To me, I feel like this makes it confusing *how* and *when* `constructor` leaks into a type.

**Comment by somebody1234** [comment]
Unrelated to the issue: It's possible (although of little use) to make the above branded string type type-safe:
[Link to Playground](https://www.typescriptlang.org/play?ts=5.3.2&ssl=2&ssc=21&pln=1&pc=19#code/JYOwLgpgTgZghgYwgAgMpiqA5sg3gKGSOQH0SAjKOEAEwC5kAiABzjAAtGBufAX33zpMILADpmUAPZhpAT2YRRZStRrIAvE1YduAhJJABnMMgDu7Ng2PCcAMjykKVWgxZtOyXhqZxuQA)

(and hence it is understandable that it does not collapse to `never`, at least.)

```ts
interface String {
    __brand: "path";
}

String.prototype.__brand = "path";

const what: string & { __brand: "path" } = "a";
```

**Comment by somebody1234** [comment]
But yeah, as for the issue itself - it would be nice to find out the behavior of when we should be expecting `constructor` to be `Function` - but otherwise, do feel free to just close this issue.

**Comment by craigphicks** [comment]
@somebody1234  - With respect to objects with properties,  `&` is mostly used a method of composing/building objects (union of property keys, intersection of their property values, with total collapse to never of the object if any property values intersects to never), whereas with primitives `&` is used to express set logic intersection. Very ad hoc.

**Comment by somebody1234** [comment]
@craigphicks If this is about the primitive branding - yeah, *but* the point I was making is that TS *does* happily accept that code, hence it is entirely possible for the intersection to not be `never` (and the types are indeed correct for the runtime behavior!)

**Comment by somebody1234** [comment]
If this is about the original question instead - the issue is that `constructor: Function` seemingly appears from nowhere. Specifically, if *every* type has `constructor: Function`, then surely `B['constructor']` should be `Function & 1`?

**Comment by fatcerberus** [comment]
> It's possible (although of little use) to make the above branded string type type-safe:

Yeah, but putting the brand onto the prototype (and thus, every single string ever) defeats the purpose of using a branded type in the first place; you want it to *not* be compatible with arbitrary strings.  It’s effectively a type system hack, but one that’s well-supported by the compiler devs because it’s so common.

**Comment by andrewbranch** [comment]
The type system operation `{}['constructor']` is mimicking the way prototypal inheritance works at runtime. It looks to see if there’s a `constructor` property declared on the object type, and if not, it looks to see if there’s one on `Object.prototype`. This is why it wouldn’t make sense for `B['constructor']` to be `Function & 1`. Accessing the `constructor` property at runtime of an object that conforms to `B` shadows `Object.prototype.constructor`.

```
❯ node
Welcome to Node.js v21.1.0.
Type ".help" for more information.
> ({}).constructor
[Function: Object]
> ({ constructor: 1 }).constructor
1
```

**Comment by somebody1234** [comment]
Oh... so I guess `(A & B)[K]` is *always* equivalent to `A[K] & B[K]`, given that both `A[K]` and `B[K]` do not error

**Comment by craigphicks** [comment]
> If this is about the original question instead - the issue is that `constructor: Function` seemingly appears from nowhere. Specifically, if _every_ type has `constructor: Function`, then surely `B['constructor']` should be `Function & 1`?

I should have been more explicit and said `&` is not equivalent to set intersection - although it sometimes is.  That obviously doesn't mean that set logic intersection as applied to types in doesn't exist, it just means that TypeScript doesn't have a consistent symbol for it in the TypeScript language.

**Comment by fatcerberus** [comment]
`&` is best thought of as a conjunction on assignability.  `A & B` refers to any value which is simultaneously assignable to both `A` and `B`.  This often corresponds to set intersection, but not always.  Likewise, `|` (union) is disjunction.

**Comment by andrewbranch** [comment]
This is not really the place to discuss it, but, what you are referring to as “not equivalent to set intersection”

> union of property keys, intersection of their property values, with total collapse to never of the object if any property values intersects to never

is in fact how set-theoretical intersection behaves on objects, assuming you define “belonging to the set defined by `{ x: string }`” as “having a property `x` whose value belongs to the set `string`.” (That is, we assume object types are not closed/sealed.) There are a couple corner cases that are incompatible with set theory (an intersection of functions, a.k.a overloads, is not commutative; index signatures are super weird).
