### ISSUE TITLE
Thanksgiving turkey is inexplicably no longer on the menu

### ISSUE THREAD

**Issue by fatcerberus** [microsoft/TypeScript#56542]
### 🔎 Search Terms

turkey, thanksgiving, leftovers, gobble, reggie, jake, sans, papyrus

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions `turkey.0` and `pizza.0`
- This changed in commit or PR `free-birds`
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about **going back in time to the first Thanksgiving to get turkeys off the menu**
- I was unable to test this on prior versions because **the Great Turkey tried to kick my butt**

### ⏯ Playground Link

The turkey ate it.

### 💻 Code

```ts
// the turkey ate the code that was here
```

### 🙁 Actual behavior

Turkeys are not on the menu.

### 🙂 Expected behavior

Turkeys should be on the menu.

### Additional information about the issue

I think two weird turkeys named Jake and Reggie went back in time to the first Thanksgiving to get turkey off the menu.  That’s right—they went back in time to the first Thanksgiving to get turkey off the menu.

…and that’s terrible.

**Comment by fatcerberus** [comment]
Not a real TypeScript bug, obviously.  I just wanted to have some fun. 😅

**Comment by andrewbranch** [comment]
Is this a reference to a classic holiday film I haven’t seen?

**Comment by fatcerberus** [comment]
I don’t know if I’d go so far as “classic”, but yes: Free Birds.
