### ISSUE TITLE
Can't assign never as object value to conditional type

### ISSUE THREAD

**Issue by vpzomtrrfrt** [microsoft/TypeScript#56578]
### 🔎 Search Terms

"never conditional not assignable"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about never

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20231128#code/C4TwDgpgBAYg9nAPAFQHxQLxQN4DcCGANgK4QBcUyAvgNwBQokUAQvgE4rpbJQQAewCADsAJgGcoxURABmASyEQRUAPw4CJcpSpQKeIqQrV6dGVIDGwOXCFQARu04AKAJQ46UT1HM2xwKHwU8EhomOoGWgAMUPgSirgQbLQeXj5CflAgFKwcoVj6mhTRsVDxicle3r7+AF7ZjnlQxXEQCWz0VEA

### 💻 Code

```ts
type Foo<T> = {value: T};
type Bar<T> = T extends undefined ? {value: T} : {value: T};

function bar<T>() {
    const x: Foo<T> = {value: 0 as never};
    const y: Bar<T> = {value: 0 as never};
    const z: Bar<T> = 0 as never;
}
```

### 🙁 Actual behavior

`Type '{ value: never; }' is not assignable to type 'Bar<T>'.` on the `const y` line, despite the fact that Bar should be equivalent to Foo

### 🙂 Expected behavior

I expect to be able to assign never to everything

**Comment by MartinJohns** [comment]
Resolving of conditional types involving unbound type arguments is deferred. The compiler doesn't know what type `T` is, so it can't resolve the conditional type.

This should really be added to the FAQ, given how often this gets reported (a lot).

**Comment by RyanCavanaugh** [comment]
Duplicate #51488, others
