### ISSUE TITLE
Windows build failing due to drive letter case

### ISSUE THREAD

**Issue by itslenny** [microsoft/TypeScript#56575]
### 🔎 Search Terms

drive letter case sensitive windows

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.9.5 and 5.2.2

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

When a windows cmd prompt is opened with the lower case drive letter `c:\` the build fails, but when the drive letter is capital `C:\` it succeeds. 

error: 

```
File 'src\main.ts' is missing from the TypeScript compilation

ERROR File 'src\polyfills.ts' is missing from the TypeScript compilation

Ensure the file is part of the TypeScript program via 'files' or 'include' property
```

### 🙂 Expected behavior

The build should succeed regardless of the case of the drive letter as they are case insensitive and do not effect portability to case-sensitive platforms. Also, the paths specified in code are relative and appear to be resolved to absolute paths by the compiler so there is not a way to fix this with changes to client code.

### Additional information about the issue

This was noticed because we had a shortcut with a "start in" path starting with a lowercase `c:\`, but when cmd is opened using the run window (CMD+R, "cmd") the drive letter is uppercase `C:\`. The build would consistently fail from the cmd window launched via shortcut until the "start in" path was changed to uppercase. In our case this was a simple workaround, but there are situations (e.g. CI/CD) where the user may not have control over the environment's drive letter case.

The issue did not occur on TypeScript 4.9.5 and began happening when we recently upgraded to 5.2.2

It appears a similar issue was raised before and fixed (in 2019), but that was related to `forceConsistentCasingInFileNames`. However, I set this value to false in our tsconfig and the build still failed. It would only succeed if the cmd window path started with a capital drive letter.

Previous Issue: https://github.com/microsoft/TypeScript/issues/31327

Previous PR: https://github.com/microsoft/TypeScript/pull/31503

**Comment by sheetalkamat** [comment]
Please share steps to repro with the code and clear steps

**Comment by itslenny** [comment]
After attempting to create a repro for this I've determined it is likely an issue with Angular and not Typescript.

I was able to create a repro with a brand new (minimal) project in Angular, but could not reproduce it with Typescript directly (outside of Angular).

I sent them an issue here: https://github.com/angular/angular-cli/issues/26519
