### ISSUE TITLE
Unable to access tuple elements beyond bounds

### ISSUE THREAD

**Issue by tuoqiu** [microsoft/TypeScript#56587]
### 🔎 Search Terms

access tuple elements

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
let arr: [string, number];
arr = ['hello', 10];
arr[2] = 'dz';//Type 'dz' cannot be assigned to type 'undefined'. Ts (2322)
console.log(arr[0].substring(1));
console.log(arr[2].substring(1));//The object may be undefined. Ts (2532)
```

### 🙁 Actual behavior
```ts
let arr: [string, number];
arr = ['hello', 10];
arr[2] = 'dz';Type 'dz' cannot be assigned to type 'undefined'. Ts (2322)
console.log(arr[0].substring(1));
console.log(arr[2].substring(1));//The object may be undefined. Ts (2532)
```
### 🙂 Expected behavior

Should document errors be corrected? Tuples can add elements beyond the bounds, but cannot be accessed beyond the bounds

**Comment by MartinJohns** [comment]
I don't understand what you're trying to report. You're getting an error when trying to assign something out of bounds. This is as expected.

**Comment by tuoqiu** [comment]
> I don't understand what you're trying to report. You're getting an error when trying to assign something out of bounds. This is as expected.

![Snipaste_2023-11-29_17-15-16](https://github.com/microsoft/TypeScript/assets/41751619/930ce1a6-ccfe-4877-8df6-db8809672546)

**Comment by whzx5byb** [comment]
@tuoqiu

The picture you provided is an outdated Chinese documentation. Here is the latest documentation: https://www.typescriptlang.org/docs/handbook

See also https://github.com/microsoft/TypeScript/issues/32628.

**Comment by tuoqiu** [comment]
> https://www.typescriptlang.org/docs/handbook

Thank you very much. It is indeed an error in the Chinese document. The document you provided is correct
