### ISSUE TITLE
ES2022 target breaks `stack` initialisation on classes that extend Error

### ISSUE THREAD

**Issue by balupton** [microsoft/TypeScript#56588]
### 🔎 Search Terms

es2022, target, stack, trace, error, inheritance, extend

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because not applicable

### ⏯ Playground Link

https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9#code/MYGwhgzhAECyCeBRATsg9s6BTAHgFywDsATGFdTAbwChpoB6AKkegGU0BbLaYtYAVy6E8YPAEs0haADMM0CCOABraI3q1oAB34AjEGODzFSgFxHkYwgHMNwSQuT9geDAAouUMFaxmHlqwCU0DR0dBD8mljI7lie3gEadPT00AACeBAAtGJWhBhYidB2hBBoIFgAdCBoVq4ABsUOTi7IAIxmACSUeAAWYhAVCmDKAL51CaHQvf2DxtAAvNAA5GgAblEWxFhLhY1lldW1DfZ4js4YAEyd3X0DQ6PjGiPUz3vlFaBYYNEJjXjYqAW0EIWAA7nAkKg3EsPBAvNtfvZ9lUavUNtcNrNhkoxgkgA

### 💻 Code

```ts
class MyError extends Error {
  /** Some documentation for stack */
  public stack: string
  constructor(message: string) {
    super(message)
    // @ts-ignore
    console.log(`constructor1: ${this.stack}`)
    this.stack = 'override'
    console.log(`constructor2: ${this.stack}`)
  }
}
console.clear()
const err = new MyError('message')
console.log(`err: ${err.stack}`)
```

### 🙁 Actual behavior

`useDefineForClassFields` breaks `stack` making it empty, due to the `stack;` in:

``` javascript
"use strict";
class MyError extends Error {
    /** Some documentation for stack */
    stack;
    constructor(message) {
        super(message);
        // @ts-ignore
        console.log(`constructor1: ${this.stack}`);
        this.stack = 'override';
        console.log(`constructor2: ${this.stack}`);
    }
}
console.clear();
const err = new MyError('message');
console.log(`err: ${err.stack}`);
```

### 🙂 Expected behavior

stack not being touched so that the error constructor (called via super) works

### Additional information about the issue

Encountered this in https://github.com/bevry/errlop with this tsconfig:

```
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "maxNodeModuleJsDepth": 5,
    "moduleResolution": "Node",
    "strict": true,
    "target": "ES2022",
    "module": "ESNext",
    "downlevelIteration": true
  },
  "include": [
    "source"
  ]
}
```

and this compilation:

```
 tsc --module ESNext --target ES2022 --outDir ./edition-es2022-esm --project tsconfig.json && ( test ! -d edition-es2022-esm/source || ( mv edition-es2022-esm/source edition-temp && rm -rf edition-es2022-esm && mv edition-temp edition-es2022-esm ) ) && printf '%s' '{"type": "module"}' > edition-es2022-esm/package.json
```

due to:

> true if [target](https://www.typescriptlang.org/tsconfig#target) is ES2022 or higher, including ESNext; false otherwise.
> https://www.typescriptlang.org/tsconfig#useDefineForClassFields

**Comment by Jamesernator** [comment]
> `useDefineForClassFields` breaks `stack` making it empty, due to the `stack;` in:

This is just how actual class fields work, as they're a part of ES2022, TypeScript has to imply `useDefineForClassFields` in order to have equivalent behaviour.

You can use [`declare field`](https://www.typescriptlang.org/docs/handbook/2/classes.html#type-only-field-declarations) instead if you simply want to change the type (or add doc annotations).

**Comment by Andarist** [comment]
> You can use [declare field](https://www.typescriptlang.org/docs/handbook/2/classes.html#type-only-field-declarations) instead if you simply want to change the type (or add doc annotations).

TIL, thanks!

**Comment by balupton** [comment]
> You can use [`declare field`](https://www.typescriptlang.org/docs/handbook/2/classes.html#type-only-field-declarations) instead if you simply want to change the type (or add doc annotations).

TIL too, thanks will do. Happy to have it closed then.

**Comment by nmain** [comment]
For clarity, here's a minimal example in vanilla Javascript (no transpilation whatsoever) that demonstrates that this is the expected behavior of a modern JS engine:

```javascript
(new Error).stack === undefined // false

(new (class extends Error { stack; })).stack === undefined // true
```
