### ISSUE TITLE
Inquiry: Accessing non-static private/protected member variables in static member functions

### ISSUE THREAD

**Issue by FeelyChau** [microsoft/TypeScript#56599]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

**Description:**
I have recently noticed that in TypeScript, it is possible for static member functions to directly access non-static private or protected member variables. This behavior seems to differ from my understanding of access modifiers. Based on my knowledge, protected members should be accessible within all member functions of a class as well as in derived classes. However, in the case of static member functions, I have observed that it is possible to access protected member variables without the need for public member functions or friend functions.

**Code Example:**
```ts
class MyClass {
  private privateVariable: number;

  protected protectedVariable: number;

  static createInstance(): MyClass {
      const obj = new MyClass();
      obj.privateVariable = 10; // it's ok
      obj.protectedVariable = 20; // it's ok
      return obj;
  }
}

```

Could someone explain the original intention behind this design and provide relevant details, as I couldn't find related information in the documentation?

**Comment by MartinJohns** [comment]
This is working as intended and how most languages operate (e.g. C#). `private` means the visibility is limited to the class definition, and your static functions are part of your class definition.

For questions like this it's better to use StackOverflow or other community sites (e.g. Discord).

**Comment by FeelyChau** [comment]
> This is working as intended and how most languages operate (e.g. C#). `private` means the visibility is limited to the class definition, and your static functions are part of your class definition.
> 
> While not strictly about `static`, the behavior is documented here: https://www.typescriptlang.org/docs/handbook/2/classes.html#cross-instance-private-access
> 
> For questions like this it's better to use StackOverflow or other community sites (e.g. Discord).

Thank you for the prompt response. I will follow up with the documentation to get a better understanding of this feature. Thanks again.
