### ISSUE TITLE
Can you provide a configuration in tsconfig that requires the function to manually specify the return value type, which helps with code readability and maintenance

### ISSUE THREAD

**Issue by Silentdoer** [microsoft/TypeScript#56595]
### 🔍 Search Terms

return value type

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Can you provide a configuration in tsconfig that requires the function to manually specify the return value type, which helps with code readability and maintenance, this is a option config item

### 📃 Motivating Example

 helps with code readability and maintenance

### 💻 Use Cases

1. What do you want to use this for?
 function func(aa:string): number {...}
let a = (b: number): string => {...}
3. What shortcomings exist with current approaches?

5. What workarounds are you using in the meantime?

**Comment by MartinJohns** [comment]
You can use ESLint for this: https://typescript-eslint.io/rules/explicit-function-return-type/

**Comment by RyanCavanaugh** [comment]
This seems like a linter's job
