### ISSUE TITLE
Can you provide the cast keyword to throw an exception when the strongly converted type does not match

### ISSUE THREAD

**Issue by Silentdoer** [microsoft/TypeScript#56597]
### 🔍 Search Terms

type, cast, error

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

let a: any = 8
let  b: string = a cast string
should throw TypeCastError

### 📃 Motivating Example

for type safety

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by MartinJohns** [comment]
Something like this has been requested often and is **explicitly** out of scope for TypeScript.

**Comment by fatcerberus** [comment]
It also counts as

> non-ECMAScript syntax with JavaScript output

because you’re asking for this to generate additional runtime code.
