### ISSUE TITLE
Leading comment and trailing type assertion in return incorrectly remove load bearing parentheses

### ISSUE THREAD

**Issue by frigus02** [microsoft/TypeScript#56591]
### 🔎 Search Terms

return, parens, parenthesis, assertion

### 🕗 Version & Regression Information

- This is the behavior in every version I tried: v5.2.2, v5.3.2, v5.4.0-dev.20231129

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.2#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITgbwFgAoORJAS2ADt4BeAkssgc2BgBUALC6lgLjgAKAJRw6APjgAFKBAC2FNMAB0UYGghIAbsCEByfSKZwAviRMAzXKMGyFS4AB5tECgBMpRUs3UwArlDUwibMcAD0AFRwHADyACKxggCCrh5w-mi8LHAwAJ5gwHDoyrAUENRoADRwYEjA6EXqligIMNAqcJHhuTxoKshUtKFhcCpsnDx8osWY-tQA1tQQAO7B6DJyisoubp4jIgDcJubEp0A

### 💻 Code

```ts
export class Foo {
  client = {
    getThing: () => Promise.resolve('')
  }

  foo(): Promise<void> {
    return (
      /* TODO: Avoid using type assertions, please refactor. */ this.client
        .getThing() as unknown as Promise<void>
    );
  }
}
```

### 🙁 Actual behavior

```js
export class Foo {
    constructor() {
        this.client = {
            getThing: () => Promise.resolve('')
        };
    }
    foo() {
        return 
        /* TODO: Avoid using type assertions, please refactor. */ this.client
            .getThing();
    }
}
```

This means `new Foo().foo()` essentially `returns undefined`.

### 🙂 Expected behavior

```js
    foo() {
        return (
        /* TODO: Avoid using type assertions, please refactor. */ this.client
            .getThing());
    }
```

### Additional information about the issue

This happens specifically when the return statement begins with a comment and ends with a type assertion.

**Comment by nmain** [comment]
> load bearing parentheses

I congratulate you on inventing a brand new term (at least, I can't find any mention of it on Google anywhere), yet one that is immediately understandable to a reader who has never heard it before.
