### ISSUE TITLE
`Symbol.for` returns a `unique symbol`

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript#56611]
### 🔎 Search Terms

symbol, 
unique symbol

### 🕗 Version & Regression Information

While changing a `Symbol` implementation from `Symbol()` to `Symbol.for()` is expected the `d.ts` definition to go from `unique symbol` to `symbol`. 

### 🙁 Actual behavior

Symbol.for() returns a `unique symbol`

### 🙂 Expected behavior

Symbol.for() returns a `symbol`

**Comment by RyanCavanaugh** [comment]
This is the correct behavior, since `Symbol.for("blah") === Symbol.for("blah")`

**Comment by JeanMeche** [comment]
Shouldn't it be just `symbol` ?

**Comment by Andarist** [comment]
`unique symbol` represents a concrete/unique symbol - but all of them "display" in the same way since they don't have public names. Each one of them is associated with a particular instance of a symbol though. 

> Shouldn't it be just symbol ? Since the symbol isn't unique per your demonstration.

If we make a quick test in a JS engine then we'll see this:
```ts
Symbol.for("blah") === Symbol.for("blah") // true
```

Perhaps you are interpreting this uniqueness differently. From the compiler's PoV, a unique symbol is kinda like a string literal whereas a symbol is like a string type.

**Comment by JeanMeche** [comment]
Thx for the additional info. It's good for me !

**Comment by Andarist** [comment]
I guess that it's kinda impossible today to treat those as equal in all scenarios since declaration emit can't preserve the input used to create those unique symbols. And that also could always be just a `string` anyway.

**Comment by rotu** [comment]
> Every `unique symbol` is its own nominal type, which is at odds with the fact that `Symbol.for("foo") === Symbol.for("foo")`.

More strikingly, this results in:

```ts repro
const s1 = Symbol.for('foo')
const s2 = Symbol.for('foo')
type T = typeof s1 & typeof s2 // never
let s:typeof s1 = s2

let s3 = Symbol.for('foo')
let s4 = Symbol.for('foo')
type U = typeof s3 & typeof s4 // symbol
let u:typeof s3 = s4
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBBCMMC8MDKBPAtgIxAGwDoAzEAJwAoByEkSgSgChRJYIAmZNLXQki6kLUZR0ABwCmMACqcREkETiIAZDDniFcDgHptMMOIBu40gzzjWALnWaEndgzMW4AZk4Yc+YmSo16T1gAWd24vPl9Bf3UYAFVZMQ1FCDdVGyTg3ThQvACYAFdrBNs3FAhAhiA)
