### ISSUE TITLE
[BUG?] "Cannot find module" error is back?

### ISSUE THREAD

**Issue by 0618** [microsoft/TypeScript#56616]
### 🔎 Search Terms

"yarn typescript Cannot find module"
"yarn pnp typescript Cannot find module"
"yarn typescript pnp"

### 🕗 Version & Regression Information

4.0.2

### 💻 Code

```sh
npm uninstall -g yarn
rm -rf ~/.yarn
mkdir yarn-issue
codepack enable
yarn init -2
yarn dlx @yarnpkg/sdks vscode # installed ZipFS, picked "Use Workspace Version"
yarn add @yarnpkg/pnpify -D
yarn add moment
touch index.ts
```

### 🙁 Actual behavior

```ts
// index.ts
import fs from "fs"; // Cannot find module 'fs' or its corresponding type declarations.
import React from "moment"; // Cannot find module 'moment' or its corresponding type declarations.
```

### 🙂 Expected behavior

It should be able to find the modules.

**Comment by MartinJohns** [comment]
You need to install `@types/node` and `@types/moment`.

**Comment by 0618** [comment]
> You need to install @types/node and @types/moment.

Tried, but don't work.

> And consider updating, your TypeScript version is from 2020.

😂  sorry, I thought posted at https://github.com/yarnpkg/berry/issues

**Comment by RyanCavanaugh** [comment]
The repro steps don't describe any invocation of TypeScript
