### ISSUE TITLE
Problems with assignability involving objects with nested object fields introduced in 4.9 

### ISSUE THREAD

**Issue by ericpromislow** [microsoft/TypeScript#56628]
### 🔎 Search Terms

nested
symbols
assignability

### 🕗 Version & Regression Information

- This is not a crash, but it stops our build systems and gives eslint errors.
- This changed between versions _4.8.4_____ and ___4.9.3____
- This changed in commit or PR _*not sure*______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _____nested objects, assignability____
- I was unable to test this on prior versions because __no released GA version between 4.8.4 and 4.9.3_____

### ⏯ Playground Link

Too complex for a playground link

### 💻 Code

```ts
// Your code here

```bash
mkdir .../tmp
git clone https://github.com/rancher-sandbox/rancher-desktop.git
cd rancher-desktop
nvm use 18.16
npm install -g yarn
yarn global add cross-env
# NOTE: `sed -i` sometimes needs another argument on some platforms.
sed -i -e 's/"typescript": "4.5.5"/"typescript": "4.9.3"/' package.json
git diff package.json ## !!!  Should have output
yarn
yarn build # <--- failure here
```

### 🙁 Actual behavior

The raw failure is unreadable, but here's the gist:
```
Argument of type 'Exclude<GetFieldType<RecursiveReadonly<

{ version: 10;
  application: { adminAccess: boolean; debug: boolean; extensions: { allowed: { enabled: boolean; list: string[]; }; installed: Record<string, string>; }; pathManagementStrategy: PathManagementStrategy; ... 5 more ...; window: { ...; }; };
  ... 7 more ...; 
  experimen...' 

is not assignable to parameter of type 

{
  [x: `application.extensions.installed.${string}`]: string;
  [x: `WSL.integrations.${string}`]: boolean;
  [x: `diagnostics.mutedChecks.${string}`]: boolean;
  version: 10;
  application: RecursiveReadonly<{
     adminAccess: boolean;
     debug: boolean;
     extensions: {
         allowed: {
             enabled: boolean;
             list: string[];
         };
         installed: Reco...'
```

### 🙂 Expected behavior

Up to version 4.5.5 there have been no type failures

There are some other new errors coming in with version 4.6.2, and yet more at 4.8.4, but this is the most puzzling one.

BTW, we target window registries, and there's a difference between:

```
WSL: { integrations: Record<string, boolean> }
```

and
```
WSL: { integrations: { string1: bool1, string2: bool2, etc... } }
```

The former corresponds to two registry keys, `WSL`, and then `integrations`.
The latter has three layers of registry keys, `WSL`, and then `integrations`, and then `integrations` points to an arbitrary number of registry keys. We want it to point to a single reg container of names and values.

### Additional information about the issue

You can see the type in `pkg/rancher-desktop/config/settings.ts`.

The problem is in the three fields that are defined like `WSL:        { integrations: {} as Record<string, boolean> },`

Our typescript code is now injecting three symbols into the type definition, one for each of them. So we're now seeing the types

```
 [x: `application.extensions.installed.${string}`]: string;
  [x: `WSL.integrations.${string}`]: boolean;
  [x: `diagnostics.mutedChecks.${string}`]: boolean;
```

from defined fields

```
installed: { } as Record<string, string>,
WSL:        { integrations: {} as Record<string, boolean> },
mutedChecks: {} as Record<string, boolean>,
```

all in https://github.com/rancher-sandbox/rancher-desktop/blob/5cc484b6c5f20df030ef5f98894157895a0f4336/pkg/rancher-desktop/config/settings.ts#L59

The type def that is adding these fields is at https://github.com/rancher-sandbox/rancher-desktop/blob/5cc484b6c5f20df030ef5f98894157895a0f4336/pkg/rancher-desktop/backend/k3sHelper.ts#L73 :

```
type RequiresRestartSeverityChecker<K extends keyof RecursiveTypes<K8s.BackendSettings>> =
  (currentValue: RecursiveTypes<K8s.BackendSettings>[K], desiredValue: RecursiveTypes<K8s.BackendSettings>[K]) => 'restart' | 'reset';
```

**Comment by RyanCavanaugh** [comment]
We're not going to investigate something that changed 4 releases ago (without anyone else noticing) unless there's a reduced repro.

**Comment by ericpromislow** [comment]
The problem is still in effect now. I associated it with 4.9.3 because that's when it first appears, going from 4.8.4, ignoring all RCs and dev-commits.

**Comment by ericpromislow** [comment]
OK, I have a repro...

```
const CURRENT_SETTINGS_VERSION = 10 as const;

const defaultSettings = {
  version:     CURRENT_SETTINGS_VERSION,
  application: {
    adminAccess: false,
    extensions:  {
      /** Installed extensions, mapping to the installed version (tag). */
      installed: { } as Record<string, string>,
    }
  }
};
type Settings = typeof defaultSettings;
type RecursiveKeys<T> =
  Record<string, unknown> extends T ? string :
  T extends readonly unknown[] ? RecursiveKeys<T[number]> :
  T extends Record<string, unknown> ? keyof T & string | RecursiveKeysInner<T, keyof T & string> :
  never;

type RecursiveKeysInner<T, K extends string> = K extends keyof T ? `${ K }.${ RecursiveKeys<T[K]> }` : never;
type RestartReasons = Partial<Record<RecursiveKeys<Settings>, {
  current: any;
  desired: any;
  severity: 'restart' | 'reset';
}>>;

type RecursivePartial<T> = {
  [P in keyof T]?:
  T[P] extends (infer U)[] ? RecursivePartial<U>[] :

    T[P] extends Record<string, unknown> ? RecursivePartial<T[P]> :
      T[P];
};

type RecursiveReadonly<T> = {
  readonly [P in keyof T]:
  T[P] extends (infer U)[] ? readonly RecursiveReadonly<U>[] :

  T[P] extends Record<string, unknown> ? RecursiveReadonly<T[P]> :
  T[P];
};

type BackendSettings = RecursiveReadonly<Settings>;

type RecursiveTypes<T extends Record<string, any>> =
  Record<string, unknown> extends T ? never :
  {
    [P in RecursiveKeys<T>]:
      P extends keyof T ?
        T[P] :
      P extends `${ infer K }.${ infer R }` ?
        (
          K extends keyof T ?
            (
              T[K] extends Record<string, unknown> ?
                ( R extends keyof RecursiveTypes<T[K]> ? RecursiveTypes<T[K]>[R] : never ) :
                never
            ) :
            never
        ) :
      never;
  };

type RequiresRestartCheckers = {
  [K in keyof RecursiveTypes<BackendSettings>]?: RequiresRestartSeverityChecker<K>;
};

type RequiresRestartSeverityChecker<K extends keyof RecursiveTypes<BackendSettings>> =
  (currentValue: RecursiveTypes<BackendSettings>[K], desiredValue: RecursiveTypes<BackendSettings>[K]) => 'restart' | 'reset';

type ExtraRequiresReasons = {
  [K in keyof RecursiveTypes<BackendSettings>]?: {
    current: RecursiveTypes<BackendSettings>[K];
    severity?: RequiresRestartSeverityChecker<K>;
  }
};

class K3sHelper {
  requiresRestartReasons(
    currentSettings: BackendSettings,
    desiredSettings: RecursivePartial<BackendSettings>,
    checkers: RequiresRestartCheckers,
    extras: ExtraRequiresReasons = {},
  ): RestartReasons {
    const results: RestartReasons = {};
    const NotFound = Symbol('not-found');

    function cmp<K extends keyof RestartReasons>(key: K, checker?: RequiresRestartSeverityChecker<K>) {
      const current = currentSettings[key as keyof BackendSettings] || NotFound;
      const desired = desiredSettings[key as keyof BackendSettings] || NotFound;

      results[key] = {
        current, desired, severity: checker ? checker(current, desired) : 'restart', // <---- this line
      };
    }
    return results;
  }
}
```

In the typescript playground (When I try to share it, I get a gigantic URL... not exactly sure how to do this, but don't want to lose the repro).

With TS 5.3.2 I get this error message at line 92 (complaining about `current` in `current, desired, severity:...`):

```
Argument of type '10 | RecursiveReadonly<{ adminAccess: boolean; extensions: { installed: Record<string, string>; }; }>' is not assignable to parameter of type '{ [x: `application.extensions.installed.${string}`]: string; version: 10; application: RecursiveReadonly<{ adminAccess: boolean; extensions: { installed: Record<string, string>; }; }>; "application.adminAccess": boolean; "application.extensions": RecursiveReadonly<...>; "application.extensions.installed": RecursiveR...'.
  Type '10' is not assignable to type '{ [x: `application.extensions.installed.${string}`]: string; version: 10; application: RecursiveReadonly<{ adminAccess: boolean; extensions: { installed: Record<string, string>; }; }>; "application.adminAccess": boolean; "application.extensions": RecursiveReadonly<...>; "application.extensions.installed": RecursiveR...'.
    Type 'number' is not assignable to type 'never'.(2345)
```

Note the generated `[x: \`application.extensions.installed.${string}\`]` -- I think that's what's causing the type error.

When I revert to version 4.8.4 I don't get this error message.

If I move up to the next version, 4.9.5, I get it.

It's still occurring at version 5.3.2 (latest as I write this).

**Comment by ericpromislow** [comment]
This blocks dependabot bump https://github.com/rancher-sandbox/rancher-desktop/pull/6138 - I still need to know if this is a bug in typescript or in our code. If the latter, it would be great if an authoritative person could suggest why. As I said above, there's a standalone repro in https://github.com/microsoft/TypeScript/issues/56628#issuecomment-1841898810

**Comment by RyanCavanaugh** [comment]
It seems unlikely that something that changed in TypeScript 4.9 and wasn't otherwise reported in the last ~year is both a TS bug and a bug that we'd be able to prioritize. If you have a repro that a human can grok in a short-ish amount of time, we can elaborate more, but a 90-line repro is very difficult to reason about in terms of whether the code is "correct" or not in type terms.

**Comment by ericpromislow** [comment]
I got somewhere by changing ```
export type RecursiveReadonly<T> = {
  readonly [P in keyof T]?:
``` to ```
export type RecursiveReadonly<T> = {
  readonly [P in keyof T]?:
```

but that revealed 127 other TS errors in our code.   

And I'll have to ask the original author what `<TEST>?:...` means without a term between the `?` and `:`.

Closing this bug for now. Thx for the quick response.
