### ISSUE TITLE
optional parameter (?) doesn't work in classes with "target":  "esnext"

### ISSUE THREAD

**Issue by meloalves** [microsoft/TypeScript#56624]
### 🔎 Search Terms

I had modified the "tsconfig" a day before so I tested restoring the old config and it "fixed" the bug

### 💻 Code

```ts
class Dog {
  name;
  breed;

  constructor(name: string, breed?: string) {
    this.name = name;
    if (breed) {
      this.breed = breed;
    }
  }
}

const dog = new Dog('Rex1');
const dog2 = new Dog('Rex2', 'Golden Retriever');

function showDogDetails(dog: Dog) {
  if ("breed" in dog) {
    console.log(`${dog.name} is a ${dog.breed}`);
  } else {
    console.log(`The dog is a dog`);
  }
}

showDogDetails(dog);
showDogDetails(dog2);
```

### 🙁 Actual behavior

Rex1 is a undefined
Rex2 is a Golden Retriever

### 🙂 Expected behavior

The dog is a dog
Rex2 is a Golden Retriever

**Comment by MartinJohns** [comment]
The relevant configuration: https://www.typescriptlang.org/tsconfig#useDefineForClassFields
