### ISSUE TITLE
Support for "`const` modifier on type parameters" with JSDoc

### ISSUE THREAD

**Issue by leibale** [microsoft/TypeScript#56634]
### 🔍 Search Terms

"const type parameter jsdoc", "const generic jsdoc", "const template jsdoc"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

v5.0 added support for ["`const` modifier on type parameters"](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters), but it is not supported with JSDoc [`@template`](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#template) tag (or at least I couldn't make it work nor find any documentation about it).

I propose adding support for the `const` prefix in the `@template`:
```javascript
/**
* @template {const Array<any>} T
*/
```

### 📃 Motivating Example

The same as "`const` modifier on type parameters" itself..

### 💻 Use Cases

1. What do you want to use this for? 
...
2. What shortcomings exist with current approaches?
...
3. What workarounds are you using in the meantime?
I have to wrap the generic value with `/** @type {const} */(...)` every time I'm using the function

**Comment by Andarist** [comment]
A workaround for this that you can use at the declaration site:
```ts
/** @type {<const T>(a: T) => T} */
function test(a) {
    return a;
}
```

**Comment by leibale** [comment]
@Andarist thanks! :)

**Comment by fatcerberus** [comment]
> squirrely braces

Well, that’s a new one 😆

**Comment by fatcerberus** [comment]
> is `U` const? Who knows.

Reminds me of C pointers.

```c
int* p,q;  // p is int*, q is int
```

Used to trip me up all the time; now it just annoys me.

**Comment by bjg2** [comment]
I see this is checked in and marked as completed, but I cannot make it work? If I try to run the same thing as from the connected checkin, I get this:

![image](https://github.com/microsoft/TypeScript/assets/6639273/749d02ec-2ac1-44c7-8b94-d46230cd37d0)

**Comment by bjg2** [comment]
Ok, the first part (about not being able to set @template const) was up to vscode language server using older typescript version.

Still, I am not able to set explicit type for jsdoc typed function:

![image](https://github.com/microsoft/TypeScript/assets/6639273/2c597379-9b78-4651-8cc4-39eda7ddf382)
