### ISSUE TITLE
getEncodedSyntacticClassifications invalid on multiline-commented regex 

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5663]
Sample from : https://github.com/Microsoft/TypeScript-TmLanguage/issues/3

```ts
let regex = /**/ /foo/;
```

![image](https://cloud.githubusercontent.com/assets/874898/11159561/da7e40e0-8ab4-11e5-9f0d-3ffd2796cfb4.png)

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by DanielRosenwasser** [comment]
What's the bug here? This looks correct.

**Comment by basarat** [comment]
@DanielRosenwasser yes ... Its fine in the referenced tm grammar as well :rose: 


![image](https://cloud.githubusercontent.com/assets/874898/11160337/a05c8982-8abc-11e5-88e4-bb759165966c.png)


Just that I expected this result to be different from textmate result which I assumed to be a bug  and hence thought this was a :bug:

**Comment by basarat** [comment]
Ahhh textmate version should have shown yellow like a string literal

![image](https://cloud.githubusercontent.com/assets/874898/11160365/e9b404f2-8abc-11e5-8277-370be8de0958.png)

 textmate version still has the bug. No bug here :rose:

**Comment by DanielRosenwasser** [comment]
See https://github.com/Microsoft/TypeScript-TmLanguage/issues/3.
