### ISSUE TITLE
`lib.webworker.d.ts` URLSearchParams miss methods "entries, keys, values" definition

### ISSUE THREAD

**Issue by jason-chang** [microsoft/TypeScript#56631]
### ⚙ Compilation target

ESNext

### ⚙ Library

lib.webworker.d.ts

### Missing / Incorrect Definition

`URLSearchParams` miss methods "entries, keys, values" definition.

### Sample Code

```TypeScript
let url = 'https://a.com/b?c=1&d=2';
let urlObj = new URL(url);
let data = Object.fromEntries(urlObj.searchParams.entries());
```

### Documentation Link

[https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)

**Comment by RyanCavanaugh** [comment]
> You might need to include webworker.iterable in your tsconfig

👆

**Comment by jason-chang** [comment]
@fatcerberus 👍 you are right.
