### ISSUE TITLE
Allows you to configure functions not to pass arguments when they can be undefined

### ISSUE THREAD

**Issue by guaijie** [microsoft/TypeScript#56632]
### 🔎 Search Terms

"undefined", "void", "optional", "no arguments", "rules"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about typescript

### 💻 Code

```ts
const fn1= (param: undefined | number) => {}
const fn2 = (param: undefined | number) => {}
```

### 🙁 Actual behavior

```ts
fn1(undefined) // success
fn1() // fail
fn2(undefined) //success
fn2() // success
```

### 🙂 Expected behavior

```
fn1(undefined) // success
fn1() // success 
fn2(undefined) //success
fn2() // success
```

**Comment by fatcerberus** [comment]
This is what optional parameters are for
```ts
const fn1 = (param?: number) => {};
fn1(undefined);  // works
fn1();  // also works
```
