### ISSUE TITLE
Microsoft.TypeScript.MSBuild output are not included only when publishing an app

### ISSUE THREAD

**Issue by datvm** [microsoft/TypeScript#56638]
I am not sure if this is where I report issue with .NET package `Microsoft.TypeScript.MSBuild`. Please point me to the correct one if this is not, thanks.

I am having this strange issue: [[JS files compiled by TypeScript not included when publishing though they are included when building in Debug and Release mode](https://stackoverflow.com/questions/77544835/js-files-compiled-by-typescript-not-included-when-publishing-though-they-are-inc)](https://stackoverflow.com/questions/77544835/js-files-compiled-by-typescript-not-included-when-publishing-though-they-are-inc):

I have a .NET MAUI project with TypeScript in `Scripts\scriptfiles.ts` folder that is compiled into `wwwroot\js\scriptfiles.js`. Everything works well until my client tries to publish it and everything stops working and I realized all script files are missing. I noticed that building with both `Debug` and `Release` build works but as soon as I use `publish`, the files are missing, both in the `\obj\Release\net8.0-android\assets\wwwroot\js` folder and the APK file (I can open and check it with 7zip).

This is the publishing command:

```
dotnet "publish" "-f:net8.0-android" "-c:Release" "/p:AndroidKeyStore=True" "/p:AndroidSigningKeyStore=<keyfile>" "/p:AndroidSigningStorePass=<pass>" "/p:AndroidSigningKeyAlias=<key>" "/p:AndroidSigningKeyPass=<keypass>" "D:\Github\MauiWithTypeScriptBug\MauiWithTypeScriptBug\MauiWithTypeScriptBug.csproj"
```

The TypeScript files is compiled using `Microsoft.TypeScript.MSBuild`:

```xml
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.2.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
```

It happens to newly create projects as well. You can checkout this [Github repository](https://github.com/datvm/MauiWithTypeScriptBug) and reproduce it.

What's the problem here and why is it happening even though it works for Release build?

---

This is the `tsconfig.json` file even though I don't think it's relevant because the build works well in Debug or Release mode:

```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "strict": true,
        "noEmitOnError": true,
        "removeComments": false,
        "sourceMap": true,
        "target": "ESNext",
        "module": "ESNext",
        "outDir": "wwwroot/js"
    },
    "exclude": [
        "node_modules",
        "wwwroot"
    ]
}
```

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I don't know when this behavior started.

### 🙁 Actual behavior

Output files are not included in the published build.

### 🙂 Expected behavior

Output files should be included in the published build.

### Additional information about the issue

A workaround I use is to only include TypeScript package in the Debug build. I have to make sure the files are compiled in Debug build first and they go to the Git repository so when anyone builds or publishes with Release config, the files are already there:

```xml
<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.2.2"
						Condition="'$(Configuration)'=='Debug'">
	<PrivateAssets>all</PrivateAssets>
	<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

**Comment by datvm** [comment]
@fatcerberus Thanks. I thought so but I couldn't find any reference from the package as to where to report the bug. Do you know which Issue tracker I should report this to? Thanks.

**Comment by joj** [comment]
There's some context I'm missing. When you build in debug, the file gets generated but when you build in release it gets removed (and then publish is not including it because it's not there)? Or is the problem where the file ends up in Release? IIRC, that nuget is not doing anything different for release and debug, both builds should be identical.

**Comment by joj** [comment]
I'm really not sure what dotnet publish does. I'll find someone from MAUI and see if they can take a look.

**Comment by datvm** [comment]
@joj thanks for checking, here's the file (remove the `.zip` as GitHub doesn't allow `.binlog` extension). It happens to newly created project as well so no problem sharing it publicly here I think.

[msbuild.binlog.zip](https://github.com/microsoft/TypeScript/files/13589437/msbuild.binlog.zip)

Note that I also discovered I don't even need any signing for this to happen. I simply ran: 

```ps
dotnet publish -c:Release -f net8.0-android -bl
```

I also noted that the first time I ran it, the issue didn't happen (there's `js` folder with compiled files in there). I think it's due to the files being already there before. So before running the command the 2nd time, I went to `wwwroot` and deleted the `js` folder, then run the command again. After the publish:

- The APK doesn't contain `js` folder with the compiled files. `obj` doesn't contain `js` folder as well.
- The project's `wwwroot\js` folder does contain the compiled files.

**Comment by joj** [comment]
Hi! I checked the logs and everything seems to be working properly from the TypeScript side. I was talking with some folks on MAUI, and they say `dotnet publish` is not really needed in android scenarios. They pointed me to this: https://github.com/dotnet/docs-maui/pull/1929. 

Also, there's something about content files not being included in apk's because there's no good way to get to them, but I think they should be able to explain that better. 

I would recommend taking it there (https://github.com/dotnet/maui). They should be able to assist you better. Point back to this and to me if you want, most folks there know how to reach me :) 

Thanks!
J

**Comment by datvm** [comment]
@lonix1 _maybe_ . I will try it again later without them. The `PrivateAssets` is set by default when installing the package.
