### ISSUE TITLE
Generic type in class forgets that it has a super type when used as partial

### ISSUE THREAD

**Issue by Casimodo72** [microsoft/TypeScript#56651]
### 🔎 Search Terms

typescript partial generic not working in class

### 🕗 Version & Regression Information

Tried with latest version: 5.3.2

### 💻 Code

```ts
interface Bar {
    title: string
}

class Stool<T extends Bar = Bar> {
    // Ok
    one: Partial<T> = { }
    // Compiler error
    two: Partial<T> = { title: "barking dog"}
}
```

### 🙁 Actual behavior

Can't initialize with a field defined in the super type of the genereric type.
Getting the error: "Type '{ title: "barking dog"; }' is not assignable to type 'Partial<T>'"

### 🙂 Expected behavior

Should be able to initialize with a field defined in the super type of the genereric type.

**Comment by MartinJohns** [comment]
This is working as intended.

`{}` is a valid object for `Partial<T>`, regardless of what `T` is. But `{ title: "barking dog" }` is not a valid object, because `T` might be typed `{ title: "Xi bear" }`.

```typescript
const s = new Stool<{ title: "Xi bear" }>
```

**Comment by Casimodo72** [comment]
> This is working as intended.
> 
> `{}` is a valid object for `Partial<T>`, regardless of what `T` is. But `{ title: "barking dog" }` is not a valid object, because `T` might be typed `{ title: "Xi bear" }`.
> 
> ```ts
> const s = new Stool<{ title: "Xi bear" }>
> ```

Ah (I hope I get it), so the issue is that the actual T might restrict the (string) type of "title" to specific string values, thus making "barking dog" be of invalid type since the actual type is not really known.

Hmm, kind of makes generics less usefull (for me at least).

Plus, it doesn't explain why I can assign any value I want after the object has been initialized:
```ts
interface Bar {
    title: string
}

class Stool<T extends Bar = Bar> {
    // Ok
    one: Partial<T> = { }

    constructor() {
        // Ok. So I can't use that value in an initializer, but I can assign it afterwards. Magic!
        this.one.title = "barking dog"
    }
}
```
