### ISSUE TITLE
An explicitly typed function/method in an object is ignoring the types of all return statements when one of them includes a type of `any`.

### ISSUE THREAD

**Issue by christo8989** [microsoft/TypeScript#56650]
### 🔎 Search Terms

 generic return any

### 🕗 Version & Regression Information

Breaks on v3.3.3333
Breaks on v5.3.2. 
Breaks on the nightly version.

### ⏯ Playground Link

[TypeScript Playground ](https://www.typescriptlang.org/play?target=2&module=1&allowSyntheticDefaultImports=true&ts=5.3.2#code/C4TwDgpgBAqgzhATlAvFA3gKClAZgS0TmADkBDAWwgC4pjF8A7AcwG5soAbM48q2+kzaYAvu0yhIUAIoBXJCFQYOzCMHhJaACgCUqAHywEidiMyYAxgHtGxKBcQQywCABUA7lYAKzgBZwBYAYWJQByUPEAekioAFEADS9YgGFXWIARSxs7VXVjJV1aDWQUQywcHHxcKC0HJxcPbz84VBQ0UMYrYChgX3wWsD9QvXKKnGtbbskIAEFGEAAlNVlERloyeaV0MzGcR2AVxh7wWfmlg9WOHDMrqGioVz6W-cO6YGcIKkZu3DJ8Tha1kQjgswE4IAAdLcXqtlLs8IReJQaFAAIwAJgAzAAaW44bhI-horG4sZmG73GAkBJJVIZGoAIRgAHEAPw6LKTKBkUGyMicWhyBRbFRqYq6OEVKo1OofRo+XotNrtTpTJ5QQa9YaSsYTOzTOaLZardabNDbPFQGFHA1nY2MW43Mb3R79K32t4fL7dAAmVggLVVeD+nG5jB9UAAkj0+owANZQfDdOC+KyyTg+qFja06ioEIikZG0DE4y0EwtEkukio7KDkzBAA)

### 💻 Code (UPDATED v2)

**I recommend using the playground link.**

```
type User = {
  firstName: string;
  lastName: string;
};

type Query = {
  getUser: () => User;
}

const createTwoPaths: string = '';

// EXPECTED
const getUser = (): User => {
    if (createTwoPaths === 'not this path') {
      const typeAnyReturn: any = {}
      return typeAnyReturn
    }

    // This return statement fails correctly.
    return {
      firstName: 123,
      lastName: 123,
    }
}

// UNEXPECTED (BUG?)
const actual: Query = {
  getUser() {
    if (createTwoPaths === 'not this path') {
      const typeAnyReturn: any = {}
      return typeAnyReturn
    }

    // This return statement does not fail and I think it should.
    return {
      firstName: 123,
      lastName: 123,
    }
  }
}
```

### 🙁 Actual behavior

Returning the wrong type but it doesn't break because the other return statement returns type `any`. And, it somehow seems related to how object types are handled.

### 🙂 Expected behavior

Of course, the return of type `any` shouldn't break. But the return of the wrong type should break. 

If you compare the two scenarios (EXPECTED/UNEXPECTED), I would expect them to act the same.

**Comment by mdgozza** [comment]
Yes! This does look odd, specifically when the function type is inferred from object type and a branch exists in which the return statement is casted to `any`. This scenario seems to trick the compiler into no longer checking other return statements within the function body.

[Here are some other interesting reproductions ](https://www.typescriptlang.org/play?target=2&module=1&allowSyntheticDefaultImports=true&ts=5.3.2#code/C4TwDgpgBAqgzhATlAvFA3gKClAZgS0TmADkBDAWwgC4pjF8A7AcwG5soAbM48q2+kzaYAvu0yhIUAIoBXJCFQYOzCMHhJaACgCUqAHywEidiMyZcsxgGNg+APaMoq9cd20NiLDkRrZiJ28cPEJeShooABYAGg4cbjD+KAB2DjMzTGtHYigAR3lEEAAmWjkFJSCAekqoYAALfDg8MnxOOBU1T209FEMgnCzGHOAlACJgCGJRqB46YAYWOKh8XC0RlA2occngUb1+4N9gf0Cl4JCiUnDaUdHY8-OEq6Tbs6gzc4-DvwDlB4vEhEAKz3B5PPgRVKfNKicyWGx2Ry1HZQdxGJB-KCDYZjCZTGZNQSLHArNaoTbbKY6A5HE4YEQEmaMEAwnDVWoNJq4FptDi034HAiXCG0GJLcHXFIwjLYkb5BSlAqKNBBFxdVE9PpLWW1XE7aazInMJak9YUvG7fZvfmnf44IWAm53N7xHjPCKvf4M2ZkZlLL5smr1Rp0Or2WScAAmzVaAH4ljbMecHe7aCC3hKklDgl90uZzEA)

**Comment by nickjoseph** [comment]
Here's a simplified reproduction that narrows it down to two different function signatures: [Playground](https://www.typescriptlang.org/play?target=2&module=1&allowSyntheticDefaultImports=true&ts=5.3.2#code/C4TwDgpgBAqgzhATlAvFA3gKClAZgS0TmADkBDAWwgC4pjF8A7AcwG5soAbM48q2+kzaYAvu0wBjAPaNiUCYghlgEACoB3KQAVlACziooAQiMBZPQDpcnKVMQAKe+eC6LiMowAmUivYCUUABUUACMAAxhAQCkUABMfuIA9IlQAKIAGlqpAMKqqQAikjJyzBDA8EiG-rQVyCgAfBgcOPi4UPYKSioa2npwAVg4Q-LFwFCgkACCjCAASmUAroiMtB4ghugizUOKwEuM4+AQ03OLy9tb28lQqrr4Brv7dMDKEFSMY9KIihLAnOvue4QAweKBIRB2CzbR7LJrDHAEIikSg0UKxADMABptjhuLwUbQQhjscMtpdrjASBksrkCu0AEIwADiAH4-EVZGNSuUEIhYrR-KhGrUqgEGnChq12p1Xj0dC5+hLhtJOYcpjN5ntlqsZhstvCoDCDhNjhqzowLpgrilbvdDebnq93mM4LopAtOJ5DWQgVBQeC7JjDfhmLpgCzoQ7BvDEfj+GisTiuDxkfGiYnSaIgA)

```
const getUser = (): User => {...}. // raises the expected error
const getUser2: () => User = () => {...} // does not raise the expected error
```

**Comment by RyanCavanaugh** [comment]
This is the expected behavior. There are two steps here:
1. Compute the shape of the object literal (or method, in the above screenshot)
2. See if that shape is assignable to the target type

In Step 1, the return type of `getUser` is `any`, because there's an `any` in a `return` position

In Step 2, it's checked that a function returning `any` is assignable to a function returning `User`. Per the definition of `any`, of course, it is.

**Comment by christo8989** [comment]
@RyanCavanaugh How come step 1 ignores the explicit type in the latter example and not in the former?

**Comment by RyanCavanaugh** [comment]
It matters where the explicit type is. When you have
```ts
const a = (): T => { return e; }
```
Then every `e` in a return position has to match `T`

When you have
```ts
const a: () => T = () => { return e; }
```
Then the shape of the initializing expression is first computed before being checked for suitability for the target type
