### ISSUE TITLE
Imports get lost, when classes are only referenced in switch/case

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#5666]
Reported by @mechanoid  here https://github.com/TypeStrong/atom-typescript/issues/719#issue-116718119  Tested with TypeScript nightly

Sample from original issue report : https://github.com/mechanoid/ts-import-error-test

**Comment by DanielRosenwasser** [comment]
Probably a duplicate of #5637. Appears to be fixed in the latest nightly.

**Comment by mechanoid** [comment]
thx! :)
