### ISSUE TITLE
[Regression 5.3.2] TS2339 property cannot be resolved when generic type has the same name

### ISSUE THREAD

**Issue by ClementValot** [microsoft/TypeScript#56661]
### 🔎 Search Terms

generic types
regression
5.3.2
TS2339

### 🕗 Version & Regression Information

- This changed between versions 5.2.2 and 5.3.2

### 💻 Code

```ts
// minimal code for reproduction: Have a class extend another, and have a property with the same name as a generic type
class BaseClass {}

class Item<data> extends BaseClass {
  data: data;
  getData() {
    return this.data;
  }
}

```

### 🙁 Actual behavior

TS2339: Property 'data' does not exist on type 'Item<data>'.

### 🙂 Expected behavior

No transpiler errors

### Additional information about the issue

Note: compilerOptions are default 

While it may be bad design to have properties and generic types share names, I didn't find it listed anywhere as a breaking change; my mistake if it is :)

Good luck!

**Comment by MartinJohns** [comment]
Duplicate of #56620.

**Comment by ClementValot** [comment]
Indeed, why it didn't turn up when I filtered by TS2339 in the search bar is beyond my comprehension 👍
