### ISSUE TITLE
Promise interface problem with async function.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#5667]
The declaration of `then` method of `Promise` is now:

```ts
interface Promise<T> {
    then<TResult>(onfulfilled?: (value: T) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => TResult | PromiseLike<TResult>): Promise<TResult>;
    then<TResult>(onfulfilled?: (value: T) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => void): Promise<TResult>;
}
```

However onfulfilled could be of type `void` and thus the created promise will have the same time as the former one.

The more complete declaration:

```ts
interface Promise<T> {
    // onfulfilled here should not be optional.
    then<TResult>(onfulfilled: (value: T) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => TResult | PromiseLike<TResult>): Promise<TResult>;
    then<TResult>(onfulfilled: (value: T) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => void): Promise<TResult>;
    then(onfulfilled?: void, onrejected?: (reason: any) => T | PromiseLike<T>): Promise<T>;
    then(onfulfilled?: void, onrejected?: (reason: any) => void): Promise<T>;
}
```

However, this declaration does not play well with `async`.

Another question, why do we need the second `then` with `onrejected?: (reason: any) => void`?

**Comment by mhegazy** [comment]
//cc: @rbuckton

**Comment by rbuckton** [comment]
Why would `onfulfulled` be of type void? If you pass `undefined` or `null` for the `onfulfilled` callback, the chained promise will still be of type `T`?

**Comment by vilic** [comment]
Yup, as defined in Promises/A+ specification. https://promisesaplus.com/#point-43

> If onFulfilled is not a function and promise1 is fulfilled, promise2 must be fulfilled with the same value as promise1.

But for TypeScript, `undefined`/`null` should be the only valid values.

**Comment by mhegazy** [comment]
This should be addressed in latest changes to the library.
