### ISSUE TITLE
Any on recursive interfaces inside a generic on declaration

### ISSUE THREAD

**Issue by Eythaann** [microsoft/TypeScript#56686]
### 🔎 Search Terms

interfaces, generics, recursion, recursive interfaces, any on recursion.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried from 4.8 to 5.3

### 💻 Code

```ts
type generic<T> = T;

type tree<T> = generic<{
  value: T;
  left: tree<T>;
  right: tree<T>;
}>;

type myTree = tree<number>;

const a: myTree = {} as myTree;
a.left.left.right.left.right; // this works fine
a.left.left.right.left.otherKey; // this give error so the type internally not is any but show it as any 
```

### 🙁 Actual behavior

The leafs o the recursed value in this case 'left' and 'right' shows it as any but internally it have their correct types.

### 🙂 Expected behavior

'left' and 'right' should show it as "tree<T>" instead of any

**Comment by RyanCavanaugh** [comment]
They do. Are you hovering in the wrong spot?

![image](https://github.com/microsoft/TypeScript/assets/6685088/2aa4eb1a-2161-4245-96b9-103a8a46c3ea)

**Comment by Eythaann** [comment]
ohh, I see it only happens when `noErrorTruncation` is in the tsconfig.
```json
{
  "compilerOptions": {
    "noErrorTruncation": true,
  },
}
```

**Comment by Eythaann** [comment]
but still is showing `...` instead `Tree<T>` that is default behavior if you don't wrap it in a generic.

**Comment by fatcerberus** [comment]
The `…` indicates that the type is infinitely recursive; if printed in its entirety it would literally go on forever.  Essentially you can read `…` as “insert the containing type here”
