### ISSUE TITLE
Returned assert functions need needlessly explicitly typed

### ISSUE THREAD

**Issue by jas7457** [microsoft/TypeScript#56695]
### 🔎 Search Terms

"assert function", "react hook", "Assertions require every name in the call target to be declared with an explicit type annotation", "2775"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Link](https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoczAVwDsNgJa5haA3FKYFWmAMVoAKNEwAmwGI1oAuOHQDWtCAHdaAGjggkAZ20oA5klnaYXWvoCUslLqSxtcEbXGSmcAN7k4LTHEEBCJxcpCw8vbzgYAAscZThaJDiAUSgcKEEtXQMkCwpvAF9yQqo6BjdqbSQASXZObl5BUM9vIhhqKGZWDi4efloKYpgATzAkOD5gABsYOzgAXjDvSRhJozgTM30BuAAfeOpJyYoS+ldmABUdGABGQXc4TCmZqDh82XvH6btZCa+X-Ka4QA9EC5NpWPpIlExlEIBB5HA2HZwW5RBAdLQAOTwZTQeQaJBIzq+KpwVrtZhIAAe6BWQyhYz0WgepTO4ScJhYtR6vHmYOq3PqMEaeS53SFgk+zw0+F+z3iSDQOj0UCG+Fy7KY2ggqwAdJMIPpJU87LrlqsNcDQdSwJNgGgJJN6cMwBCGXBYfDEcipHBcVB5NoAPxwADqAEFzpraJyunVegAmWTINodc4jJAAHhdSAgvgqAvFvQAfHyCzUiw0Nd44zyYAnjX8ZXLZgklVlVerRRydUh9YbG88zY6cscWkhU8xM+I2MX3FLTeakPlM0CZ8WBpQaKdfZcTA2Pib-u8HkefkfXoDvCDHChDm7omNtw6YKjgEQME6-XiHI8EuFayFARBzsZsLzbZVODVatHC1Xt+yNBcoGHFZR0ocdJzgadgFnecjxQ1YVzXHCNyKcggA)

### 💻 Code

```ts
import React from "react";

function invariantFn(condition: unknown, message: string): asserts condition {
  if (!condition) {
    throw new Error(message);
  }
}

function useInvariant() {
  return invariantFn;
}

type Filter = {
  title: string;
} | null;

function Test1({ filter }: { filter: Filter }) {
  // using the hook version doesn't work, even if I return exactly the same function
  const invariant = useInvariant();
  invariant(filter, "Filter necessary");
  console.log(filter.title);

  // explicitly typing the hook version works? WAT
  const invariant2: ReturnType<typeof useInvariant> = useInvariant();
  invariant2(filter, "Filter necessary");
  console.log(filter.title);

  return <div>{filter.title}</div>;
}

function Test2({ filter }: { filter: Filter }) {
  // calling the funciton directly works fine
  invariantFn(filter, "Filter necessary");
  console.log(filter.title);

  return <div>{filter.title}</div>;
}

```

### 🙁 Actual behavior

I need to manually type the function returned from my hook, even though it is the same exact function used without needing a type.

### 🙂 Expected behavior

TypeScript should allow me to return an assert function from a hook or other function and not need to manually type it at the callee location.

### Additional information about the issue

I'm trying to create an `invariant` function that will act similar to the npm invariant package. I'd like to put it into a React hook so that I can use another hook to grab our logger, and then return a function that will call the `invariant` function and our logger.

Even with this slimmed down example that I provided, without any of the logging logic, TS is unhappy and forces me to provide some type annotation for every consumer of the hook.

**Comment by RyanCavanaugh** [comment]
This is an intentional trade-off since the performance characteristics of making the CFA graph include any possible function call are quite bad (in other words, this error message isn't in the code by accident).

**Comment by jas7457** [comment]
> This is an intentional trade-off since the performance characteristics of making the CFA graph include any possible function call are quite bad (in other words, this error message isn't in the code by accident).

Sorry, I'm not familiar with what a CFA graph is. But what's the difference [here](https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocmATzCTgEkA7ANxSmBSfgF44AKNBCYATYDGDCAXHACuTANZMIAdyYAaOCCQBnHSgDmSGTpgcmBgJRweAPjgo9SWDrhDR4yUwrl3puMCs7JzcAGJMMsxsHFy8Au5iEsKa2nqGSNZ2cADe5HABmAIAhAmewta5+fkwABY4KnBMSA0AolA4UPyp+kaWFPkAvuRD5JjyGF5yOkhRwbH8lpFBMdw5eXBEMLJQTAHLITDhFCM0dHChwAA2MM42a9Xil8ZwpuYGx3AAPo2yl5c+YyYE2EcAAKroYABGfjZOCYK43KBwAYyWHw67OGQXDFIgYVdYAegJU0CBjgtXoNQgEAUcBYzh0kxEEF0TAA5PAVNAFJokPTdsBCgwNkgtjs4EgAB7oGCXajkmr0fTaOHjJJMdZ+eCBaIHO6yaazFYwBb9Pa6+boxGafDYxGNJBoXT6KDUfB9TXCHQQJ4AOkuEAM-Ctzl9EllGR8+SJEslYEuwDQj3lp1JCsp1Np9KgjJBXKgCh0AH44AB1ACCoM9TH8Orm3AATDJkGKmKDaEgADynJAQQoGmb7WL2PgDo0HU3rOvGhvBhHOG1225NJ1pV3us1+H1If2Buc4sOPSOUfKbba7TtiFi2bIhqCHiMDTsEq+2Y6UQHA3bg0yztHz3FUThACsQA5F8WjYk0BQP40wpVUgXEEExCIDA5TgfNC2ApopyHMImH3a0CCXJEV2ddg3Q9fItz9AMgzvB8ng9dYz3FS9gGvW8AMYpAnxfDi32GcggA) if I manually type it? Shouldn't both be of type `Invariant`, so I'd think both should act exactly the same?

**Comment by MartinJohns** [comment]
> I'm not familiar with what a CFA graph is.

CFA stands for control flow analysis.

> But what's the difference [here](https://www.typescriptlang.org/play?ts=5.3.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AocmATzCTgEkA7ANxSmBSfgF44AKNBCYATYDGDCAXHACuTANZMIAdyYAaOCCQBnHSgDmSGTpgcmBgJRweAPjgo9SWDrhDR4yUwrl3puMCs7JzcAGJMMsxsHFy8Au5iEsKa2nqGSNZ2cADe5HABmAIAhAmewta5+fkwABY4KnBMSA0AolA4UPyp+kaWFPkAvuRD5JjyGF5yOkhRwbH8lpFBMdw5eXBEMLJQTAHLITDhFCM0dHChwAA2MM42a9Xil8ZwpuYGx3AAPo2yl5c+YyYE2EcAAKroYABGfjZOCYK43KBwAYyWHw67OGQXDFIgYVdYAegJU0CBjgtXoNQgEAUcBYzh0kxEEF0TAA5PAVNAFJokPTdsBCgwNkgtjs4EgAB7oGCXajkmr0fTaOHjJJMdZ+eCBaIHO6yaazFYwBb9Pa6+boxGafDYxGNJBoXT6KDUfB9TXCHQQJ4AOkuEAM-Ctzl9EllGR8+SJEslYEuwDQj3lp1JCsp1Np9KgjJBXKgCh0AH44AB1ACCoM9TH8Orm3AATDJkGKmKDaEgADynJAQQoGmb7WL2PgDo0HU3rOvGhvBhHOG1225NJ1pV3us1+H1If2Buc4sOPSOUfKbba7TtiFi2bIhqCHiMDTsEq+2Y6UQHA3bg0yztHz3FUThACsQA5F8WjYk0BQP40wpVUgXEEExCIDA5TgfNC2ApopyHMImH3a0CCXJEV2ddg3Q9fItz9AMgzvB8ng9dYz3FS9gGvW8AMYpAnxfDi32GcggA) if I manually type it?

It's a design decision to only analyze assertion calls that are explicitly typed (for performance reasons). That's why the one version works, the other not. This is intentional.

**Comment by fatcerberus** [comment]
It’s interesting to me that the second version works, since `useInvariant` doesn’t have an explicit return type either.

**Comment by fatcerberus** [comment]
Huh, I guess return type inference happens before CFA then (since otherwise the compiler wouldn't be able to resolve `ReturnType<typeof useInvariant>` as an assertion functon type at that time)
