### ISSUE TITLE
JSX.Intrinsic type error on custom elements

### ISSUE THREAD

**Issue by kahlan88** [microsoft/TypeScript#56693]
```
import * as React from 'react';
declare global {
    namespace JSX {
        interface IntrinsicElements {
            'my-html-custom-tag': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
        }
    }
}
```

_Originally posted by @TheAfterman in https://github.com/microsoft/TypeScript/issues/15449#issuecomment-385959396_

The above throws a compile error `Error TS2339: Property 'my-html-custom-tag' does not exist on type 'JSX.IntrinsicElements'.`

The same happens when adding `test` property or `Test` property, so the issue isn't caused by not using PascalCase.

I tried multiple things to solve this, but no luck, including everthing mentioned here https://stackoverflow.com/questions/37414304/typescript-complains-property-does-not-exist-on-type-jsx-intrinsicelements-whe

We're using `preact` v10.

tsconfig.json:
```
"compilerOptions": {
    "lib": ["es2017", "dom"],
    "allowJs": true,
    "skipLibCheck": true,
    "jsx": "react",
    "jsxFactory": "h",
    "jsxFragmentFactory": "h.Fragment",
    "sourceMap": true,
    "noEmit": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "downlevelIteration": true,
    "moduleResolution": "node",
    "types": ["...", "@types/jest", "@types/node", "node", "@types/react"]
  },
```

**Comment by fatcerberus** [comment]
> The above throws a compile error

I'm not seeing an error on that code in the playground:
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQAJlrgDbKVwDmLEARsizgBvOnDFwAdshBZUYPFjgApAMoANYaPHbgEmFigEFcAJJ6ou1MFwBRFlhl70I7a-FkQATwC0ACxggLN64AK6oMCTeMMicZABcmFQwAHQAIljRwPYMABIAKgCyADIACsRgqAA82Hgp+cUAgjAwFrwh+lX1RXYOWHoAfAA0cF09jjD99G5iAL5as3RzQA

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
