### ISSUE TITLE
Javascript Language Server : Increase File Limit

### ISSUE THREAD

**Issue by yj7** [microsoft/TypeScript#56700]
We have a repo with ~10k js files. Continously getting the configure excludes message. Need a way to increase the number of files that vscode server can process. 

A workaround also coud be:
Our repo contains both frontend and backend code, so maybe we can configure excludes based on the current open file ... Process only front end files if current open file is in front end folder :thinking:

**Comment by mjbvz** [comment]
> Our repo contains both frontend and backend code

@yj7 Is your code split up into projects either using a `jsconfig` / `tsconfig`?
