### ISSUE TITLE
Typescript error in my node_modules (reactjs)

### ISSUE THREAD

**Issue by samy-mssi** [microsoft/TypeScript#56704]
### 🔎 Search Terms

"typescript error node_modules"

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 4.1.2 and 5.3.2
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "node_modules"

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

I upgrade my React 17 project to React 18. I also upgrade almost all my libs, fixed all typescripts errors that appeared, but now I got errors in my node_modules (@reduxjs/toolkit). They told me that this is not an issue from them, but a typescript issue.

```
ERROR in node_modules/@reduxjs/toolkit/src/query/fetchBaseQuery.ts:40:57
TS2556: A spread argument must either have a tuple type or be passed to a rest parameter.
    38 |  * Avoids storing `fetch` in a closure, in order to permit mocking/monkey-patching.
    39 |  */
  > 40 | const defaultFetchFn: typeof fetch = (...args) => fetch(...args)
       |                                                         ^^^^^^^
    41 |
    42 | const defaultValidateStatus = (response: Response) =>
    43 |   response.status >= 200 && response.status <= 299

```

I don't know why it checks the node_modules folder, here is my tsconfig.json :

```
{
  "compilerOptions": {
    "target": "es2020",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "noImplicitAny": false,
    "allowJs": true,
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src/types",
    "src"
  ],
  "exclude": [
    "node_modules/*"
  ],
  "types": []
}

```
I don't know if it's a eslint issue but I added ignorePatterns and .eslintignore just in case :
```
    "ignorePatterns": [
        "node_modules/",
        "**/node_modules/",
        "/**/node_modules/*",
        "out/",
        "dist/",
        "build/"
    ],
```

.eslintignore : 
```
/**/node_modules/*
node_modules/
```

I also added resolution for @types/react in my package.json as I saw in another post

I tried to delete node_modules then reinstall, tried a 'yarn cache clean', tried to delete yarn.lock but still got this error. 

### 🙂 Expected behavior

I expect that typescript not checking inside my node_modules

### Additional information about the issue

As I saw in a post, I tried to install a 5.1.x instead of 5.2.x or above. Same result.

**Comment by RyanCavanaugh** [comment]
I can't repro this. `tsc --listFiles` with this config shows that tsc is correctly resolving to the redux .d.ts files, not .ts.

What's in `src` ?
