### ISSUE TITLE
organizeImports Incorrectly Orders Imports with Similar Paths

### ISSUE THREAD

**Issue by dreadjr** [microsoft/TypeScript#56716]
### 🔍 Search Terms

organizeImports

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When using organizeImports, imports with similar prefix paths should be ordered alphabetically as expected.

### 📃 Motivating Example

Given this code

```ts
import logoInverted from "@assets/logo-inverted.svg";
import logo from "@assets/logo.svg";
```

I would expect the imports to be organized as follows.
```ts
import logo from "@assets/logo.svg";
import logoInverted from "@assets/logo-inverted.svg";
```

### 💻 Use Cases

1. What do you want to use this for?
`I want to use this to organize the imports e.g. prettier-plugin-astro-organize-imports`

2. What shortcomings exist with current approaches?
`Other eslint/prettier format plugins sort as expected but do not use the typescript function which may yield inconsistent results in the organization of imports.`

3. What workarounds are you using in the meantime?
`Manually organize or use another plugin/integration`

**Comment by RyanCavanaugh** [comment]
This is textual ordering (`"logo-inverted.svg" < "logo.svg"`), as is used by many import organizers.

Understandably, other tools might have other algorithms:
 * Remove file extensions using some specific definition of what is/isn't a file extension
 * Different treatment of case sensitivity
 * Different treatment of paths
 * Different ordering of relative and non-relative paths
 * etc

We can't reasonably provide configurability to match any string ordering algorithm anyone might think of; if your linter provides its own view of `>` then you should configure your editor to use that linter for import sorting purposes.

**Comment by dreadjr** [comment]
@RyanCavanaugh Thank you. I guess I didn't realize it was sorting by path, not the whole import.
