### ISSUE TITLE
Please infer `type<A> | type<B>` to `type<A | B>`

### ISSUE THREAD

**Issue by KingMario** [microsoft/TypeScript#56712]
### 🔍 Search Terms

infer generic ternary

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Please infer `type<A> | type<B>` to `type<A | B>`.

### 📃 Motivating Example

When writing some RXJS codes, I encountered a problem that a switchMap in pipe reports a strange error: expected 0 arguments but got 2. It turns out that an observable, obtained by a ternary operator using different types of observables, is inferred as Observable<A> | Observable<B>.

`(this.docRequired ? this.uploadDocument() : of(null)).pipe(switchMap(...))`

Another simple example:

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8Aq6AOEA8mAfMgN4CwAUMssACYBcyAzmFKAOYDcVNAbnAA2AVwhNMPSgF8qVMLhTY8AQWQBeNFgX4ARgHs9giHBBFJ8vMiUQAQus3X8IYQFsd0M7MoxhIBGGA9EGQOCDAANSFRQiIACj0dACsmDEdiAEoyXmQoMOEoYITEgDoBEQhJGUoqBCDWZAAPezZRSRq6sGQ4cQVVDQpqWkZkAHIARhGAGmyy0SZ4QWYIaekvWpB6nR68O37s+iYRgCYpmaixZCOqKvaNwwhiwT0OWNCI89imgH4uph109JrOr3R7PV5hSLlWKfZA-brIf5dZgObT6e4mZAAH2QzjcHgBVCAA

### 💻 Use Cases

1. What do you want to use this for?
Use this to intelligently infer the type of a ternary operator.

2. What shortcomings exist with current approaches?
Currently, the error message is hard to understand.

3. What workarounds are you using in the meantime?
Use `as Type<A|B>` to workaround the problem.

**Comment by MartinJohns** [comment]
This is working as intended. The types `Type<A> | Type<B>` and `Type<A | B>` are not interchangeably. I would expect changing the inference for this to be a massive breaking change.

In the cases where the compiler has issues you can give it a hint by providing the types: `getValue<boolean | number>(x ? a : b)` (much safer than using `as`).

**Comment by benlesh** [comment]
FYI: This also solves the problem.

```ts
function getValue<T extends { value: unknown }>(obj: T): T['value'] {
  return obj.value;
}
```
