### ISSUE TITLE
Can I keep generators (async/await) only and compile other features to ES5?

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#5672]
Did try babel for second compilation but can we make it directly through TypeScript?

**Comment by DanielRosenwasser** [comment]
Sounds like you want #4692. We are working on downlevel async functions though, and as part of the effort, we're hoping to enable more granular control over transformations.

**Comment by vilic** [comment]
@DanielRosenwasser great to know, I had read that issue but didn't know you are already working on it. Thanks!
