### ISSUE TITLE
Incorrect outline shown for object literal properties within a function argument

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/TypeScript#56735]
### 🔎 Search Terms

outline for object literals as function call argument

### 🕗 Version & Regression Information

-

### 💻 Code

```ts
myFunction('foo', { foo: 1 });
```

### 🙁 Actual behavior

TS extension in vscode shows outline with a single element `foo` 

<img width="1579" alt="image" src="https://github.com/microsoft/TypeScript/assets/16353531/7bc1ec36-ec60-4dca-8f70-da58a3c16b12">

### 🙂 Expected behavior

```ts
myFunction('foo', {foo: 1})
```

(at least not see `foo` as a separate outline-tree element

**Comment by ulugbekna** [comment]
I would also expect the behavior in #30515 because there's a variable definition, which is an object, with corresponding properties, but in my case the object literal appears as an argument within a top-level (source-file-level) function call

**Comment by RyanCavanaugh** [comment]
I don't really see why that changes anything. You might easily have some very large object literals forming the bulk of your file, for example.
