### ISSUE TITLE
unique symbol quick info is different in JS than TS

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#56737]
Discovered by @8HoLoN at https://github.com/microsoft/TypeScript/issues/48231#issuecomment-1849865024

The quick info behaviour is still different for me between .js and .ts:

```ts
const typescript: unique symbol = Symbol()
typescript
// ^? prints 'const typescript: typeof typescript'
```

```js
/** @type {unique symbol} */
const javascript = Symbol();
javascript
// ^? prints `const javascript: symbol`
```

However, the tests from https://github.com/microsoft/TypeScript/pull/48270 still pass and show that the emitted .d.ts is indeed `unique symbol`, just like typescript. So it's likely that #48270 is an incomplete fix and that quick info still needs additional code.

**Comment by 8HoLoN** [comment]
![image](https://github.com/microsoft/TypeScript/assets/7399918/d74b1c6b-7e7f-405a-8d4f-70bcdb03ca4b)

I added a screenshot where this also impact the intellisense for available key in object when the key should exclusively be the proper symbol. In the example of the screenshot `v[bar]` is inferred as a boolean but doesn't exist on the object.

**Comment by sandersn** [comment]
#56800 has a more complete test case, but is probably a dupe of this bug.
