### ISSUE TITLE
Union types using "pipeable" style incorrectly assert arguments

### ISSUE THREAD

**Issue by benlesh** [microsoft/TypeScript#56741]
### 🔎 Search Terms

expected zero arguments
pipe
RxJS

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbziAhmANHCAzOBfObKCEOAcigA8ArAZzIG4AoJgYwgDtb5aIBXKKwCmcALxwAsihgALAHRQUHACYkAFAEo4APjgAGOQFY4AfizY1HPgBtrWgFzm1fFUOzAOQ5RuZtO3OCghWht4cV4BYTkwYDAhNVQwNU0xXTIZYDINHyA

### 💻 Code

```ts
import { map, of } from 'rxjs';

const source = Math.random() > 0.5 ? of(null) : of(undefined);

const result = source.pipe(map(() => 'hi'));
```

### 🙁 Actual behavior

The code errors with "Expected 0 arguments" for the `pipe` method.

### 🙂 Expected behavior

Either: 

A. Don't error and infer the types.
or
B. Error, but with something that clues people into what they need to do to fix it

### Additional information about the issue

I can understand if there are limitations here, but it would be nice if the error was pointed the proper direction. The current error is confusing.

For anyone here looking for a workaround:

```ts
import { map, of } from 'rxjs';

const source: Observable<null | undefined> = Math.random() > 0.5 ? of(null) : of(undefined);

const result = source.pipe(map(() => 'hi'));
```

**Comment by KingMario** [comment]
Hi @RyanCavanaugh

A simple version example is in #56712. The problem is that `Type<A> | Type<B>`, where type Type<T> has a method `methodA<T>`, is not inferred to have a method `methodA<A | B>`.

The problem in Array has been dealt with in [Easier Method Usage for Unions of Arrays](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#easier-method-usage-for-unions-of-arrays#easier-method-usage-for-unions-of-arrays).

**Comment by craigphicks** [comment]
> Hi @RyanCavanaugh
> 
> A simple example is in #56712. The problem is that `Type<A> | Type<B>`, where type `Type<T>` has a method `methodX<T>`, is not inferred to have a method `methodX<A | B>`.
> 
> The similar problem in Array has been dealt with in [Easier Method Usage for Unions of Arrays](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#easier-method-usage-for-unions-of-arrays#easier-method-usage-for-unions-of-arrays).

The bug there is in the method not being evaluated correctly.

If `method(null as any as Type<A>)` is valid and `method(null as any as Type<B>)` is valid it should pass.
The return type is the union of those two method calls.

**Comment by benlesh** [comment]
> What's a version of this that doesn't need something as complex powerful as rxjs to demonstrate the problem?

🤣 

Fair. But @RyanCavanaugh, if **I** have to deal with the silly things people do with the library I maintain (for free), I think **you** have to deal with the silly things I do with your language you maintain (for money). Did you want this to be easy? 😆 

Honestly, the only real outcome I care about here is that I can at least give people an error that guides them to do the right thing. Otherwise, if it "just works" in some future version of TypeScript, all the better.

**Comment by rraziel** [comment]
A small reproduction:
```ts
type OperatorFunction<T, R> = (source: Observable<T>) => Observable<R>;
interface Observer<T> { next(value: T): void; }
declare class Observable<T> {
  pipe(): Observable<T>;
  pipe<A>(op: OperatorFunction<T, A>): Observable<A>;
  subscribe(observer: Observer<T>): void;
}
declare const y: Observable<number> | Observable<string>;
y.pipe(); // only the first overload available
```

Can be "fixed" multiple ways:
- making Observer non-generic
- making the overload non-generic
- making the overload simpler (`pipe<A>(op: A): Observable<A>`)

Also found a few oddities while attempting to create a reproduction:
- in some cases, pipe() with no argument returns the first type of the union (so swapping the members of the union changes the return type)
- changing the 2nd overload to `pipe(op: OperatorFunction<T, number>): Observable<number>` actually shows 3 overloads instead of 2 (which is kind of nice?)

**Comment by craigphicks** [comment]
@rraziel - You are definitely reporting a bug because either of
- commenting out `subscribe`, or
- making `y` be a non-union

will result in being able to "see" `pipe` as an overload with the tool tip.
 
```ts
type OperatorFunction<T, R> = (source: Observable<T>) => Observable<R>;
interface Observer<T> { next(value: T): void; }
declare class Observable<T> {
  pipe(): Observable<T>;
  pipe<A>(op: OperatorFunction<T, A>): Observable<A>;
  //subscribe(observer: Observer<T>): void;
}
declare const y: Observable<number> | Observable<string>;
declare function id<T>():(...args:any)=>T;

const r = y.pipe(0 as any as OperatorFunction<string,1>); // no error
r; // const r: Observable<1>
```

**Comment by ahrjarrett** [comment]
I might be missing something, but this seems like an avoidable problem if you branch inside the Observable constructor, rather than outside of it:

```typescript
import { type Observable, map, of } from 'rxjs';

const source = of(Math.random() > 0.5 ? null : undefined)

const result = source.pipe(map(() => "hi"))
//    ^? const result: Observable<string>
```

https://tsplay.dev/WGGjJW

**Comment by craigphicks** [comment]
Remove the `T` typed argument from `next` and a *different* bug appears:
```ts
type Observable<T> = {
  pipe(): Observable<T>;
  pipe<A>(op: (source: Observable<T>) => Observable<A>): Observable<A>;
  subscribe (observer: { next(value: T): void; } ): void;
}
declare const y: Observable<number>|Observable<string>;
const ry1 = y.pipe(); // only the first overload available
// const ry1: Observable<number> | Observable<string> (correct)
const ry2 = y.pipe(0 as any as <T>(source:T)=>T ); // only the first overload available
// error

type Observable2<T> = {
  pipe(): Observable2<T>;
  pipe<A>(op: (source: Observable2<T>) => Observable2<A>): Observable2<A>;
  subscribe (observer: { next(/*value: T*/): void; } ): void;
}
declare const z: Observable2<number>|Observable2<string>;
const rz1 = z.pipe(); // only the first overload available
rz1; //  Observable2<number> (wrong)
const rz2 = z.pipe(0 as any as <T>(source:T)=>T ); // only the first overload available
rz2; //  Observable2<number> (wrong)
```
