### ISSUE TITLE
Typescript global d.ts types not recognized

### ISSUE THREAD

**Issue by thewh1teagle** [microsoft/TypeScript#56761]
- VS Code Version: 1.85.0
- OS Version:  windows 10

Steps to Reproduce:

1.  Fresh install vscode 1.85.0
2. Create ts project and add global.d.ts
3. Try to use in another file

I cheched previous vsc version and it doesn't happen there. 
Took me 3 hours to figure out it's vscode issue from latest update.

**Comment by thewh1teagle** [comment]
I use the same as latest code in the branch, and from this point I'll leave this branch as is so you can check it in the future.

**Comment by RyanCavanaugh** [comment]
We can take a look at this if there's a reduced repro, but in a repo this size it's very likely this is just a misconfiguration that was being covered up by a prior bug in TS

**Comment by thewh1teagle** [comment]
I pasted link to specific folder. 
The repo isn't heavy, and it happens in specific project (the link)
Just clone this specific folder. 
It's happens when you just open that specific folder

**Comment by shivansh22agra** [comment]
i am also gettting this error now 
Type '{ children: Element[]; className: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'className' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.ts(2322)
(property) className: string

Let me know if u have find any solution with latest vs code (1.87) version

**Comment by RyanCavanaugh** [comment]
Please post a reduced repro in a new issue. Thanks!

**Comment by shivansh22agra** [comment]
Hi just solved the issue 
Actually className was missing from 
After adding this 
error disappered
<img width="504" alt="image" src="https://github.com/microsoft/TypeScript/assets/94140467/f009ba84-2450-413e-9e8b-133e2ad78d1a">
