### ISSUE TITLE
Unsafe assignment of type any[] in TypeScript 5.3.2

### ISSUE THREAD

**Issue by Stadly** [microsoft/TypeScript#56767]
### 🔎 Search Terms

"Unsafe assignment of type any[]", "tailwind plugin wrong type"

### 🕗 Version & Regression Information

- This changed between versions 5.2.2 and 5.3.2

### ⏯ Playground Link

https://stackblitz.com/edit/stackblitz-starters-zre7x7?file=tailwind.config.ts

### 💻 Code

```json
// tsconfig.json
{
  "compilerOptions": {
    "exactOptionalPropertyTypes": true,
    "strict": true
  }
}
```

```ts
// tailwind.config.ts
import type { Config } from "tailwindcss";

export default {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [require("@tailwindcss/forms")],
} satisfies Config;
```

### 🙁 Actual behavior

`npx eslint .` gives the following error:
```
/home/projects/stackblitz-starters-zre7x7/tailwind.config.ts
  8:3  error  Unsafe assignment of type any[] to a variable of type (PluginCreator | { handler: PluginCreator; config?: Partial<Config>; } | { (options: any): { handler: PluginCreator; config?: Partial<...>; }; __isOptionsFunction: true; } | undefined)[]  @typescript-eslint/no-unsafe-assignment
```

If you downgrade TypeScript from version 5.3.2 to 5.2.2 there is no error.

If you turn off `exactOptionalPropertyTypes` in `tsconfig.json` there is no error, which seems strange.

### 🙂 Expected behavior

I would expect `npx eslint .` to not give an error, as was the behavior with TypeScript 5.2.2.

**Comment by MartinJohns** [comment]
That's not a TypeScript error.

**Comment by fatcerberus** [comment]
It's indeed not a TypeScript error, but many ESLint rules are driven by the TS type checker, so I'm guessing there was a change in type-checking behavior between 5.2 and 5.3 that would have caused a new lint error to show up.

**Comment by Stadly** [comment]
I was able to fix it using `import` instead of `require`:

```ts
import type { Config } from "tailwindcss";
import * as forms from "@tailwindcss/forms";

export default {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [forms],
} satisfies Config;
```
