### ISSUE TITLE
Template strings with parameters break Scanner tokenization

### ISSUE THREAD

**Issue by chpoit** [microsoft/TypeScript#56768]
### 🔎 Search Terms

template string scanner tokenization tokenizer typescript condensed

### 🕗 Version & Regression Information

- This is a bug
- This is a problem in both TS 4.9.5 and TS 5.3.3
- I could not find anything related to this behavior

### ⏯ Playground Link

https://codesandbox.io/p/sandbox/typescript-playground-export-r9t7sp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq3voufe0006356hdnmzg3l6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq3voufe0002356h2x8ix9ah%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq3voufe0003356hccr40yub%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq3voufe0005356hog8rw0yz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq3voufe0002356h2x8ix9ah%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq3voufe0001356hstzvjecl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.ts%2522%257D%255D%252C%2522id%2522%253A%2522clq3voufe0002356h2x8ix9ah%2522%252C%2522activeTabId%2522%253A%2522clq3voufe0001356hstzvjecl%2522%257D%252C%2522clq3voufe0005356hog8rw0yz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq3voufe0004356hcml2tz3l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq3voufe0005356hog8rw0yz%2522%252C%2522activeTabId%2522%253A%2522clq3voufe0004356hcml2tz3l%2522%257D%252C%2522clq3voufe0003356hccr40yub%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq3voufe0003356hccr40yub%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 💻 Code

This is a snippet of code that runs the `Scanner` on a bit of code to show how it breaks with template strings
To use with TS 4.9.5 the `getTokenStart` must be replace with `getStartPos` and the  `const end = scanner.getTokenEnd();` and `      end,` must be removed.

Since there is a requirement to use the `typescript` package from npm a `codesandbox` link was provided. The output is both added to the window's body and the console provided by `codesandbox`
If required I can provide a repository with more examples.

```ts
import ts from "typescript";

const scanner = ts.createScanner(ts.ScriptTarget.Latest, true);
scanner.setScriptTarget(ts.ScriptTarget.Latest);
scanner.setLanguageVariant(ts.LanguageVariant.Standard);

function getTokens(contents) {
  scanner.setText(contents);
  let tokens = [];
  let kind = scanner.scan();
  //"Scanning" and getting all the tokens
  while (kind !== ts.SyntaxKind.EndOfFileToken) {
    const start = scanner.getTokenStart();
    const end = scanner.getTokenEnd();
    const text = scanner.getTokenText();
    const value = scanner.getTokenValue();
    tokens.push({
      kind,
      start,
      end,
      text,
      value,
    });
    kind = scanner.scan();
  }
  return tokens;
}

//Here are the text contents of the file to be parsed. the ${new Date(...)} has to be escaped to prevent it from being evaluated and
//"breaking" the example
//The first template string is there to show that it works and doesn't break when there are no parameters
//It is probably caused by the presence of the {} symbols.
//Adding/removing spaces, using crlf, an encoding that isn't utf-8 didn't seem to affect the behavior
const textContents = `const paramlessTemplateString = \`I'm a template string that has no params\`;

const something = () => {
  console.log("whatever");
};

const templateStringWithParam = \`I'm a template string created on \$\{new Date(2023, 11, 13)\}\`;

const someThingElse = () => {
  console.log("whatever");
};
`;

let textTokens = getTokens(textContents);
//Logging all the tokens
console.log(textTokens);
//Logging the last token, which is "wrong" to the console
console.log(textTokens[textTokens.length - 1].text);
```

### 🙁 Actual behavior

When a template string contains a parameter the Scanner's tokenization breaks and it condenses multiple tokens into one, setting the `kind` to `NoSubstitutionTemplateLiteral` (`15`) which makes no sense.

For example this bit of code 
```ts
const templateStringWithParam = `I'm a template string created on ${new Date(2023, 11, 13)}`;

const someThingElse = () => {
  console.log("whatever");
};
```
has it's last token be
```json
{
        "kind": 15,
        "start": 225,
        "end": 289,
        "text": "`;\n\nconst someThingElse = () => {\n  console.log(\"whatever\");\n};\n",
        "value": ";\n\nconst someThingElse = () => {\n  console.log(\"whatever\");\n};\n"
}
```

### 🙂 Expected behavior

The scanner should correctly "end" it's tokenization of the template litteral and not condense a chunk of tokens into a single "big token".

The output should be similar to the template litteral without parameters.

### Additional information about the issue

Elements I tested that didn't affect anything
- Reading from a file
  - As long as the "textContents" are properly escaped, and not evaluated, the behavior is the same
- Changing the file encoding
- Removing all whitespace characters except one (`.replace(/\s+/g, ' ')`
- Using `CRLF` or `LF` as line endings
- Adding more code after the template litteral
  - Sometimes it gets added to the "big token", others it will decide to start tokenizing properly again
- The amount of parameters, as long as there is one, a "big token" will be created 

Things I tried that changed the behavior
- Not having a parameter does not break the `Scanner`
- Having multiple template litterals with parameters creates multiple big tokens

**Comment by RyanCavanaugh** [comment]
You can't call the scanner like that; it's only designed to be called from a parser that understands the state of what's going on. This is why the scanner has methods like `reScanTemplateToken`
