### ISSUE TITLE
How to call generic static functions or variables like this: T.staticproc()?

### ISSUE THREAD

**Issue by Eisenspalter** [Microsoft/TypeScript#5677]
Is it possible to call generic static functions or variables like this: T.staticproc()?

**Comment by ahejlsberg** [comment]
How is T declared?

**Comment by Eisenspalter** [comment]
Example;

```typescript
class ViewModel {
	static defaultTemplate = 'editMask';
	firstname:string;
	lastname:string;
	constructor (firstname:string, lastname:string) {
		this.firstname = firstname;
		this.lastname = lastname;
	}
}

function render<T> (viewModel:T, template?:string) {
	// That is what I want: T.defaultTemplate
	var template = template || T.defaultTemplate;
	// .....
}

// default
render(new ViewModel('Luke', 'Skywalker'));
// or do something special 
render(new ViewModel('Luke', 'Skywalker'),'editMaskAdvanced');
```
[Typescript Playground](http://www.typescriptlang.org/Playground#src=%0Aclass%20ViewModel%20%7B%0A%09static%20defaultTemplate%20%3D%20'editMask'%3B%0A%09firstname%3Astring%3B%0A%09lastname%3Astring%3B%0A%09constructor%20(firstname%3Astring%2C%20lastname%3Astring)%20%7B%0A%09%09this.firstname%20%3D%20firstname%3B%0A%09%09this.lastname%20%3D%20lastname%3B%0A%09%7D%0A%7D%0A%0Afunction%20render%3CT%3E%20(viewModel%3AT%2C%20template%3F%3Astring)%20%7B%0A%09%2F%2F%20That%20is%20what%20I%20want%3A%20T.defaultTemplate%0A%09var%20template%20%3D%20template%20%7C%7C%20T.defaultTemplate%3B%0A%09%2F%2F%20.....%0A%7D%0A%0A%2F%2F%20default%0Arender(new%20ViewModel('Luke'%2C%20'Skywalker'))%3B%0A%2F%2F%20or%20do%20something%20special%20%0Arender(new%20ViewModel('Luke'%2C%20'Skywalker')%2C'editMaskAdvanced')%3B)

**Comment by kitsonk** [comment]
The problem is that you only have access to the instance within your function.  The `constructor` though will contain any static properties, so something like this should work:

```typescript

class ViewModel {
	static defaultTemplate = 'editMask';
	firstname:string;
	lastname:string;
	constructor (firstname:string, lastname:string) {
		this.firstname = firstname;
		this.lastname = lastname;
	}
}

function render<T extends ViewModel> (viewModel:T, template?:string) {
	// That is what I want: T.defaultTemplate
	var template = template || (<typeof ViewModel> viewModel.constructor).defaultTemplate;
	// .....
}

// default
render(new ViewModel('Luke', 'Skywalker'));
// or do something special 
render(new ViewModel('Luke', 'Skywalker'),'editMaskAdvanced');
```

[Playground](http://www.typescriptlang.org/Playground#src=%0Aclass%20ViewModel%20%7B%0A%09static%20defaultTemplate%20%3D%20'editMask'%3B%0A%09firstname%3Astring%3B%0A%09lastname%3Astring%3B%0A%09constructor%20(firstname%3Astring%2C%20lastname%3Astring)%20%7B%0A%09%09this.firstname%20%3D%20firstname%3B%0A%09%09this.lastname%20%3D%20lastname%3B%0A%09%7D%0A%7D%0A%0Afunction%20render%3CT%20extends%20ViewModel%3E%20(viewModel%3AT%2C%20template%3F%3Astring)%20%7B%0A%09%2F%2F%20That%20is%20what%20I%20want%3A%20T.defaultTemplate%0A%09var%20template%20%3D%20template%20%7C%7C%20(%3Ctypeof%20ViewModel%3E%20viewModel.constructor).defaultTemplate%3B%0A%09%2F%2F%20.....%0A%7D%0A%0A%2F%2F%20default%0Arender(new%20ViewModel('Luke'%2C%20'Skywalker'))%3B%0A%2F%2F%20or%20do%20something%20special%20%0Arender(new%20ViewModel('Luke'%2C%20'Skywalker')%2C'editMaskAdvanced')%3B)

The `T extends ViewModel` isn't required, but it ensures that you are using the right type of ancestor.  Currently the constructor isn't properly typed, therefore you have to assert the type.  I think there is a ticket for that somewhere.

**Comment by Eisenspalter** [comment]
Nice.
I use for `<typeof ViewModel>` an `abstract class DefaultTemplate` so I'm not depending on `ViewModel`.Perhaps it would be useful to have something like a `static interface`.

```typescript
abstract class DefaultTemplate {
	static defaultTemplate:string;
}

class ViewModel {
	static defaultTemplate = 'editMask';
	firstname:string;
	lastname:string;
	constructor (firstname:string, lastname:string) {
		this.firstname = firstname;
		this.lastname = lastname;
	}
}

function render<T> (viewModel:T, template?:string) {
	// That is what I want: T.defaultTemplate
	// var template = template || T.defaultTemplate;
	var template = template || (<typeof DefaultTemplate> viewModel.constructor).defaultTemplate;
	console.log ('template:', template);
	// .....
}

// default
render(new ViewModel('Luke', 'Skywalker'));
// or do something special 
render(new ViewModel('Luke', 'Skywalker'),'editMaskAdvanced');
```

[Playground](http://www.typescriptlang.org/Playground#src=abstract%20class%20DefaultTemplate%20%7B%0A%09static%20defaultTemplate%3Astring%3B%0A%7D%0A%0Aclass%20ViewModel%20%7B%0A%09static%20defaultTemplate%20%3D%20'editMask'%3B%0A%09firstname%3Astring%3B%0A%09lastname%3Astring%3B%0A%09constructor%20(firstname%3Astring%2C%20lastname%3Astring)%20%7B%0A%09%09this.firstname%20%3D%20firstname%3B%0A%09%09this.lastname%20%3D%20lastname%3B%0A%09%7D%0A%7D%0A%0Afunction%20render%3CT%3E%20(viewModel%3AT%2C%20template%3F%3Astring)%20%7B%0A%09%2F%2F%20That%20is%20what%20I%20want%3A%20T.defaultTemplate%0A%09%2F%2F%20var%20template%20%3D%20template%20%7C%7C%20T.defaultTemplate%3B%0A%09var%20template%20%3D%20template%20%7C%7C%20(%3Ctypeof%20DefaultTemplate%3E%20viewModel.constructor).defaultTemplate%3B%0A%09console.log%20('template%3A'%2C%20template)%3B%0A%09%2F%2F%20.....%0A%7D%0A%0A%2F%2F%20default%0Arender(new%20ViewModel('Luke'%2C%20'Skywalker'))%3B%0A%2F%2F%20or%20do%20something%20special%20%0Arender(new%20ViewModel('Luke'%2C%20'Skywalker')%2C'editMaskAdvanced')%3B)

**Comment by jeffreymorlan** [comment]
Why not make it an instance method instead?
```ts
interface DefaultTemplate {
    defaultTemplate(): string;
}

class ViewModel implements DefaultTemplate {
    defaultTemplate() { return 'editMask'; }
    firstname: string;
    // ...
}

function render(viewModel: DefaultTemplate, template?: string) {
    var template = template || viewModel.defaultTemplate();
    // .....
}
```

**Comment by Eisenspalter** [comment]
If something is static you should not declare it as an instance member. That is not a good approach. 
````typescript
function render<T extends DefaultTemplate> (viewModel:T, template?:string) {
    // That is what I want: T.defaultTemplate
    var template = template || (<typeof ViewModel> viewModel.constructor).defaultTemplate;
    // .....
}
````
If you extend T like `<T extends DefaultTemplate>` the typescript compiler could implement access to static methods or variables like this `T.defaultTemplate`. That would improve typescript.

**Comment by mhegazy** [comment]
looks like the issue is addressed. please reopen if not the case.

**Comment by ZackDeRose** [comment]
Sorry to necro this old issue, I'm working through a use case where I'd like to access the static members of a class, but do not have access to an instantiated object of this class. As such I can't use the solution above.

This hopefully demonstrates the issue: 

```
abstract class A {
    static fields: { [fieldName: string]: any };
}

class B extends A {
    static fields: { [fieldName: string]: any } = { 'testB': 'testB' };
}

class C extends A {
    static fields: { [fieldName: string]: any } = { 'testC': 'testC' };
}

class Wrapper<T extends A>{
    foo(): void {
        console.log(T.fields.testB); // compiler error: "'T' only refers to a type, but is being used as a value here"
        console.log(T.fields.testC); // compiler error: "'T' only refers to a type, but is being used as a value here"
    }
}

let bWrapped = new Wrapper<B>();
bWrapped.foo();

let cWrapped = new Wrapper<C>();
cWrapped.foo();
```
[Playground link](http://www.typescriptlang.org/play/#src=abstract%20class%20A%20%7B%0A%20%20%20%20static%20fields%3A%20%7B%20%5BfieldName%3A%20string%5D%3A%20any%20%7D%3B%0A%7D%0A%0Aclass%20B%20extends%20A%20%7B%0A%20%20%20%20static%20fields%3A%20%7B%20%5BfieldName%3A%20string%5D%3A%20any%20%7D%20%3D%20%7B%20'testB'%3A%20'testB'%20%7D%3B%0A%7D%0A%0Aclass%20C%20extends%20A%20%7B%0A%20%20%20%20static%20fields%3A%20%7B%20%5BfieldName%3A%20string%5D%3A%20any%20%7D%20%3D%20%7B%20'testC'%3A%20'testC'%20%7D%3B%0A%7D%0A%0Aclass%20Wrapper%3CT%20extends%20A%3E%7B%0A%20%20%20%20foo()%3A%20void%20%7B%0A%20%20%20%20%20%20%20%20console.log(T.fields.testB)%3B%20%2F%2F%20T%20is%20not%20defined%0A%20%20%20%20%20%20%20%20console.log(T.fields.testC)%3B%20%2F%2F%20T%20is%20not%20defined%0A%20%20%20%20%7D%0A%7D%0A%0Alet%20bWrapped%20%3D%20new%20Wrapper%3CB%3E()%3B%0AbWrapped.foo()%3B%0A%0Alet%20cWrapped%20%3D%20new%20Wrapper%3CC%3E()%3B%0AcWrapped.foo()%3B%0A%0A%0A%2F%2F%20console.log(B.fields.testB%20%3F%20B.fields.testB%20%3A%20'undefined')%3B%0A%2F%2F%20console.log(B.fields.testC%20%3F%20B.fields.testC%20%3A%20'undefined')%3B%0A%2F%2F%20console.log(C.fields.testB%20%3F%20C.fields.testB%20%3A%20'undefined')%3B%0A%2F%2F%20console.log(C.fields.testC%20%3F%20C.fields.testC%20%3A%20'undefined')%3B%0A%0A%2F%2F%20let%20b%20%3D%20new%20B()%3B%0A%2F%2F%20let%20c%20%3D%20new%20C()%3B%0A%2F%2F%20console.log((%3Ctypeof%20A%3Eb.constructor).fields.testB)%3B%0A%0A%2F%2F%20function%20getFields%3CT%20extends%20A%3E(obj%3A%20T)%3A%20void%20%7B%0A%2F%2F%20%20%20%20%20console.log(T.fields.testB)%3B%0A%2F%2F%20%20%20%20%20console.log(T.fields.testC)%3B%0A%2F%2F%20%7D%0A%0A%2F%2F%20getFields(b)%3B%0A%2F%2F%20getFields(c)%3B)

**Comment by RyanCavanaugh** [comment]
@ZackDeRose Types are erased. You have to give `Wrapper` a reference to `B` or `C`.

**Comment by ZackDeRose** [comment]
@RyanCavanaugh - this seems to work:

```
abstract class A {
    static fields: { [fieldName: string]: any };
}

class B extends A {
    static fields: { [fieldName: string]: any } = { 'testB': 'testB' };
}

class C extends A {
    static fields: { [fieldName: string]: any } = { 'testC': 'testC' };
}

class Wrapper<T extends A>{
    constructor(private classRef: typeof A) { };

    foo(): void {
        console.log(this.classRef.fields.testB); 
        console.log(this.classRef.fields.testC); 
    }
}

let bWrapped = new Wrapper<B>(B);
bWrapped.foo();

let cWrapped = new Wrapper<C>(C);
cWrapped.foo();
```
[Playground Link](http://www.typescriptlang.org/play/#src=abstract%20class%20A%20%7B%0A%20%20%20%20static%20fields%3A%20%7B%20%5BfieldName%3A%20string%5D%3A%20any%20%7D%3B%0A%7D%0A%0Aclass%20B%20extends%20A%20%7B%0A%20%20%20%20static%20fields%3A%20%7B%20%5BfieldName%3A%20string%5D%3A%20any%20%7D%20%3D%20%7B%20'testB'%3A%20'testB'%20%7D%3B%0A%7D%0A%0Aclass%20C%20extends%20A%20%7B%0A%20%20%20%20static%20fields%3A%20%7B%20%5BfieldName%3A%20string%5D%3A%20any%20%7D%20%3D%20%7B%20'testC'%3A%20'testC'%20%7D%3B%0A%7D%0A%0Aclass%20Wrapper%3CT%20extends%20A%3E%7B%0A%20%20%20%20constructor(private%20classRef%3A%20typeof%20A)%20%7B%20%7D%3B%0A%0A%20%20%20%20foo()%3A%20void%20%7B%0A%20%20%20%20%20%20%20%20console.log(this.classRef.fields.testB)%3B%20%2F%2F%20T%20is%20not%20defined%0A%20%20%20%20%20%20%20%20console.log(this.classRef.fields.testC)%3B%20%2F%2F%20T%20is%20not%20defined%0A%20%20%20%20%7D%0A%7D%0A%0Alet%20bWrapped%20%3D%20new%20Wrapper%3CB%3E(B)%3B%0AbWrapped.foo()%3B%0A%0Alet%20cWrapped%20%3D%20new%20Wrapper%3CC%3E(C)%3B%0AcWrapped.foo()%3B%0A%0A%0A%2F%2F%20console.log(B.fields.testB%20%3F%20B.fields.testB%20%3A%20'undefined')%3B%0A%2F%2F%20console.log(B.fields.testC%20%3F%20B.fields.testC%20%3A%20'undefined')%3B%0A%2F%2F%20console.log(C.fields.testB%20%3F%20C.fields.testB%20%3A%20'undefined')%3B%0A%2F%2F%20console.log(C.fields.testC%20%3F%20C.fields.testC%20%3A%20'undefined')%3B%0A%0A%2F%2F%20let%20b%20%3D%20new%20B()%3B%0A%2F%2F%20let%20c%20%3D%20new%20C()%3B%0A%2F%2F%20console.log((%3Ctypeof%20A%3Eb.constructor).fields.testB)%3B%0A%0A%2F%2F%20function%20getFields%3CT%20extends%20A%3E(obj%3A%20T)%3A%20void%20%7B%0A%2F%2F%20%20%20%20%20console.log(T.fields.testB)%3B%0A%2F%2F%20%20%20%20%20console.log(T.fields.testC)%3B%0A%2F%2F%20%7D%0A%0A%2F%2F%20getFields(b)%3B%0A%2F%2F%20getFields(c)%3B)

Unfortunately, my use case is attempting to make a generic Angular component (analogous to Wrapper in this example). I'll have to look into the dependency injector to see if I can do something like this solution; but that's an Angular issue now. Thanks for your assistance!!
