### ISSUE TITLE
Nuget Microsoft.TypeScript.MSBuild release notes

### ISSUE THREAD

**Issue by rgroenewoudt** [microsoft/TypeScript#56782]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

The nuget package  Microsoft.TypeScript.MSBuild is missing release notes. It only links to the page "What's new in TypeScript", which is from Typescript itself.

I have no idea what changed from 5.3.2 to 5.3.3.

**Comment by fatcerberus** [comment]
> I have no idea what changed from 5.3.2 to 5.3.3.

It’s strictly a bugfix release.  TS only has release notes for feature releases (e.g. 5.2.x -> 5.3.x), while maintenance releases only get a list of fixed GitHub issues; see https://github.com/microsoft/TypeScript/releases/tag/v5.3.3

I don’t think the TS team maintains the MSBuild package.
