### ISSUE TITLE
Type argument incorrectly inferred from union type

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/TypeScript#56792]
### 🔎 Search Terms

- generics
- type argument
- inference
- union type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type parameters/arguments and inference.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMwFzwB4BBAPgAoN8BtIgXQEp4BeE+ANyQEtgBuAKFCRYCZOiwAPaphicUAc1rwAPvCooArgFsARiBi1+fbGXH0eQA

### 💻 Code

```ts
declare const f: <A>(t: [A]) => void;
declare const x: [string] | [number];

f(x);
```

### 🙁 Actual behavior

TypeScript infers the type argument as `string`.

### 🙂 Expected behavior

TypeScript infers the type argument as `string | number`.

### Additional information about the issue

This issue appears to describe a similar problem with functions: https://github.com/microsoft/TypeScript/issues/52295.

Reduced test case:

```ts
type A = { a: string };
type B = { b: string };

// Parameter types
declare const f: <A>(ff: (x: A) => void) => void;
declare const x: ((x: A) => void) | ((x: B) => void);
// Inferred type argument: A
// Expected: A & B
f(x);

// Return types
declare const g: <A>(gg: () => A) => void;
declare const y: (() => A) | (() => B);
// Inferred type argument: A
// Expected: A | B
g(y);

```

**Comment by Andarist** [comment]
The difference is that in those other examples the type parameter appears in what it considers a naked~ position. It unionify candidates from such positions. 

The union of tuples is different since the position is not naked, it’s an element inside a tuple type.

This isn’t incorrect. How different inferences work is often just heuristic-based. As far as I know, this is working as intended - it’s not a bug. It can be treated as a feature request though.

**Comment by jcalz** [comment]
If it's a feature request then it duplicates #44312

**Comment by OliverJAsh** [comment]
Thanks for the responses. If it provides more context, below is the original real world problem I encountered before reducing it down to the examples you see above.

```ts
export interface Reader<R, A> {
  (r: R): A;
}

declare const chain: <A, R, B>(
  f: (a: A) => Reader<R, B>
) => (ma: Reader<R, A>) => Reader<R, B>;

declare const boolean: boolean;
declare const a: Reader<string, number>;
declare const b: Reader<number, number>;

// Type argument `R` inferred as `string`.
// Ideally this would be `string | number`.
chain(() =>
  // Error: Type 'string' is not assignable to type 'number'.
  boolean ? a : b
);

```

and

```ts
interface Left<E> {
  readonly _tag: "Left";
  readonly left: E;
}

interface Right<A> {
  readonly _tag: "Right";
  readonly right: A;
}

export type Either<E, A> = Left<E> | Right<A>;

declare const chain: <E, A, B>(
  f: (a: A) => Either<E, B>
) => (ma: Either<E, A>) => Either<E, B>;

declare const boolean: boolean;
declare const a: Either<string, string>;
declare const b: Either<string, number>;


// Type argument `B` inferred as `string`.
// Ideally this would be `string | number`.
chain(() =>
  // Error: Type 'number' is not assignable to type 'string'.
  boolean ? a : b
);

```

**Comment by fatcerberus** [comment]
There’s also the fact to consider that, in general, `G<T | U>` cannot be safely substituted for `G<T> | G<U>` for arbitrary `G`, so TS won’t even attempt inferences that imply such a substitution.

**Comment by craigphicks** [comment]
The "Actual Behavior" doesn't match the actual behavior upon opening the play ground link - which is this
```
declare const f: <A>(t: [A]) => void;
declare const x: [string] | [number];

f(x); // error
//~
// Argument of type '[string] | [number]' is not assignable to parameter of type '[string]'.
//   Type '[number]' is not assignable to type '[string]'.
//     Type 'number' is not assignable to type 'string'.(2345)
// const f: <string>(t: [string]) => void```
```
That error makes sense because `[string] | [number]` cannot be equal to `[something]`.
It could argued that TypeScript should infer the `A=[string | number]` because it's smallest inference that satisfies, (although I think it's kinder to be strict).

No problem here:
```
declare const g: <A>(t: A) => void;
declare const y: [string] | [number];
g(y); // no error
```

**Comment by fatcerberus** [comment]
> The description "Actual Behavior" doesn't match the actual behavior

@craigphicks The OP claims that Actual Behavior is:

> TypeScript infers the type argument as `string`.

which is consistent with the error message:

> Argument of type '[string] | [number]' is not assignable to parameter of type '[string]'.

i.e. TS infers `A = string` for the call to `f` and subsequently produces an error upon trying to pass a `[string] | [number]` (that is, `x`) to a parameter typed as `[A] = [string]`.  So the description of actual behavior looks correct to me.

**Comment by craigphicks** [comment]
It doesn't seem right that the inferred type depends upon the order, but as long as it fails, then it really isn't a problem.
