### ISSUE TITLE
Improve test discovery speed

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#56790]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Running a single test or a small number of tests can be slow because the current test runner will discover all tests and then greps based on test title. The main issue appears to be the number of fs sys calls during setup. This does not happen on all systems, but on my system (Windows 10), especially in debug test discovery can take up to 6/7 seconds.

**Comment by fatcerberus** [comment]
> This does not happen on all systems, but on my system (Windows 10), especially in debug test discovery can take up to **6/7 seconds**.

A few years ago, this might have surprised me.

While I like Windows for day-to-day use, it's really overdue for a file system that's not NTFS.  Windows 10/11 feel way slower than any other modern OS, even with a fast SSD, and it's becoming more and more obvious to me that like 99% of that is file system latency.

**Comment by RyanCavanaugh** [comment]
The Windows team agreed - https://learn.microsoft.com/en-us/windows/dev-drive/
