### ISSUE TITLE
Optional object property that must be a spesific type and can't be undefined

### ISSUE THREAD

**Issue by babakfp** [microsoft/TypeScript#56803]
### 🔎 Search Terms

.

### 🕗 Version & Regression Information

.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAsiAq5oF4BQUNQD5QN5QDsBDAWwgC4oBnYAJwEsCBzKAX3Ux32LMpoeYBuKAHswweiOIAbSnQCu0dqgDGUmlBIgAakWmKoyPBww8KUAEQWANCdHjJMyvIIATCADNGEV9agB6fygAdQB5ACUAaQBlPwAhAFV4KABJKABRAA0ABXSAYWSU5PhQjPDwiNR2IA

### 💻 Code

```ts
type MyType =
    | { name: string }
    | { name: string; optional: true }
```

### 🙁 Actual behavior

```ts
const myValue = {
    name: "",
    optional: undefined, // WORKS
}
```

### 🙂 Expected behavior

```ts
const myValue = {
    name: "",
    optional: undefined, // ERROR: Type 'undefined' is not assignable to type 'true'.
}
```

### Additional information about the issue

I don't know if this should be a bug report or a feature request.

**Comment by fatcerberus** [comment]
Not a bug.  `{ name: "", optional: undefined }` is assignable to `{ name: string }` due to structural subtyping.  You're looking for #12936.

**Comment by fatcerberus** [comment]
> Optional object property that must be a [specific] type and can't be undefined

The above having been said: if this is your only use case for the requested behavior, then you can get that simply by enabling `exactOptionalPropertyTypes`.
https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes
