### ISSUE TITLE
The property prototype of an abstract constructor type is unavoidably of type any.

### ISSUE THREAD

**Issue by miguel-leon** [microsoft/TypeScript#56801]
### 🔎 Search Terms

abstract constructor prototype type any

### 🕗 Version & Regression Information

Latest version as of today.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8C+AoFAXAngBwKZwGEB7AOwnQCcBXYdIi6AXmhNwHcAKASiYD44A3Gix5CpctVr0AkiXS4KEXLQCWpJtA6tOPRv1g8AZImjYKROiNwAuONCRCUKuQoBmYYPljEylGnQoAJVwAW1wAExUIxBRoOJZ2bltYIXjTc0scG0EUVGEsuFgAIwkPdB8Jf3oNMBLKMoSdPhynFwp3TzhpEOwiKBUikFwKvykGBFj42tLaRqTBaAB6RegFcwpJuLMLCyzkoTz80QB9AEYNDisiVzguAG0Acm3MvAeAXQElleB6CmV0ZJHfDHABMGm84lGAUez12rw+X2gzh+FD+tFsYBImCB0GOAGZwSNJAFZPJFP81CQYRk4bh3p9lkiSCi0QDoJjsRgCscACyEyHE+jBMKRCLUnZWemIln-QFck4AVnBxRm5QFVQo4pedIRjORv1l7KxKCAA

### 💻 Code

```ts
class A {}

type AConstructor = new() => A;

type AConstructorIntersection = (new() => A) & { prototype: A };

interface AConstructorRemedied {
    new(): A;
    prototype: A;
}


type AAbstractConstructor = abstract new() => A;

interface AImpossibleConstructor {
    abstract new(): A; // error
    prototype: A;
}



type _1 = (typeof A)['prototype']; // correct: A

type _2 = AConstructor['prototype']; // incorrect: any

type _3 = AConstructorIntersection['prototype']; // incorrect: any

type _4 = AConstructorRemedied['prototype']; // correct: A

type _5 = AAbstractConstructor['prototype']; // incorrect: any
```

### 🙁 Actual behavior

There's no way of making the type of `prototype` something other than `any`, not even with an intersection.

### 🙂 Expected behavior

A way to make the type of `prototype` something other than `any`. It seems that constructor types have a hidden `prototype` of type `any`. Shouldn't it be of type `unknown` so that at least the intersection works? (or wouldn't it be better for it to be the same type as `InstanceType` directly?)

**Comment by fatcerberus** [comment]
Possible (ugly) workaround: `Omit<new () => A, "prototype"> & { prototype: A }`

**Comment by jcalz** [comment]
(@fatcerberus  `Omit` loses the construct signature)

Instead of trying [to use `abstract new` inside an object type](https://github.com/microsoft/TypeScript/pull/36392#issuecomment-1025807607), you can do this:
```ts
type AAbstractConstructor = abstract new () => A;
interface AAbstractConstructorRemedied extends AAbstractConstructor {
    prototype: A;
}
```
This will have the `prototype` property you care about while maintaining the `abstract`ness of the constructor

[Playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G9oF8BQqAuBPADgUzlgCMIMAnMYDAYQHsA7UsgVytrOgF5owTzKM0engDu0ABQBKLgD44AblQBLehjxkAZpQKxiTAXUblWGdgCU8AWzwATJbeh4AHmvo2YuvhSqGmJ9oio0MHQOGS0ptj4AFwKqGiYuAQA+lyEXgYMfmxkFtZ2tgDaAORhERFJxQC68tCoAPT1IQB6APzoNnigYGQEwFmCYLGe+j4DLDl5tvY2qMJiYFK1jY5k4WSoQA)

**Comment by miguel-leon** [comment]
Thanks for the workaround @jcalz, silly me I didn't think of this while coming up with a minimal reproduction.

The thing is, that the type that returns the construct signature is a parametric type.
I just tried
```ts
// error
interface WithPrototype<Class extends abstract new (...args: any) => any> extends Class {
    prototype: InstanceType<Class>
}

type AbstractConstructorWithPrototype<Class extends abstract new (...args: any) => any> =
    WithPrototype<abstract new (...args: ConstructorParameters<Class>) => InstanceType<Class>>;
```
[playground](https://www.typescriptlang.org/play?#code/PTAEFMCdIe0goAlgOwC5QGYEMDG5QDqiqAFgAqyoyoCeADuADwDCANlgM4cQAe6yAE25YARh1SRcqUMnAB3UAAoAdKqyQA5hwBcoLMhoBKUAF4AfHoMXwfcIO5tO3AN7xQ70HUrV64XQElkcX08ABVfFnYuM3gAX3h4WgZQAEExCSlmGCCJAFccKkgiUgpqHwZIp15+IT10yQKZeSVVZXUtXX0jUwsuixM3D2LybySmUXEG6VkFFTVNHVAsnMh8wrJ1LABbcHRIDkro43NQQODkMIjHaLMAbnggA) 

But the interface declaration errors.
Do you think that as a parametric type then it becomes unavoidable? 😓
Or maybe is there another workaround?


Thanks anyway for the suggestion.

**Comment by miguel-leon** [comment]
I messed around with it for a bit and managed to make it work like this:

```ts
type AbstractConstructor<Class extends abstract new (...args: any) => any> =
    abstract new (...args: ConstructorParameters<Class>) => InstanceType<Class>;

interface AbstractConstructorWithPrototype<Class extends abstract new (...args: any) => any> extends AbstractConstructor<Class> {
    prototype: InstanceType<Class>
}
```
[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAggRgZ2AJwIYGNgGED2A7JZAV0x2QB4sAbVBBKCAD2AjwBN7VEUNgo8IAdygAKAHQTUyAOYIAXFFR4QASigBeAHyLl29QCgoRxdzSZ+Q0RLFTZC3ARQlgZAApTUAWwgtkCSjR0mmpaUACSjkroEAAq4BABtAiaANz6+gCWeL4AZhjQ8IS8DoTOZADqGcAAFq7IOC6gkIl0DMysHCZF5gLC4pIy8jqqGtpKINpMLOz0hTyYJU6kFNRJ2gDehsZg9Y3xChFIUbHxLcn6AL7p6IGzUJtX+mwQN1LQ6PhIsDBYCnNm2E+SxcyEqNTqDQapyaEBwOVgqXSvW+WBEKhSUAA9JiGMh6sh0jCoK4NFAYXCUWIdpCYRjsVAPniXsA-vogA)


The fact that the "hidden" prototype is of type `any` instead of (at least) unknown, it's a little bit odd, but since there's a work around, no problem in closing this issue.
