### ISSUE TITLE
Intersection will be splited when wrap a tuple and use `extends` tuple.

### ISSUE THREAD

**Issue by NWYLZW** [microsoft/TypeScript#56811]
### 🔎 Search Terms

* intersection
* Distributive Conditional Types
* union

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 5.3.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDCEA2ngGMYAMAPACoA0cAqgHxwC8cJcoMwAdgCYDOcA2gLpwA-HDbAAbsChwAXHyYAyKvwBQoSLATJUGbHhgBGUhRr15cJZVUqkKRgTMAKA3AA+cAExu4AcgDMPgCUFqIArgC2AEZSKgD0sXCJAHpCNtqMLgy6OPjELu5e7n7ePgAsPhRsEdFQ1HEJyam2qCReWVg5hkT5nt7F7mUVYVFSdfGJcCkqQA

### 💻 Code

```ts
export type Collect0<T, U> = T extends [] ? never : [T & U]
export type Collect1<T, U> = [T & U]

type T0 = (1 | 2 | '3') & number
//   ^? type T0 = 1 | 2
type T1 = Collect0<1 | 2 | 3 | '4', number>
//   ^? type T1 = [never] | [1] | [2] | [3]
type T2 = Collect1<1 | 2 | 3 | '4', number>
//   ^? type T2 = [1 | 2 | 3]
```

### 🙁 Actual behavior

```ts
type T1 = Collect0<1 | 2 | 3 | '4', number>
//   ^? type T1 = [never] | [1] | [2] | [3]
```

### 🙂 Expected behavior

```ts
type T1 = Collect0<1 | 2 | 3 | '4', number>
//   ^? type T1 = [1 | 2 | 3]
```

**Comment by fatcerberus** [comment]
Working as intended.
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

**Comment by fatcerberus** [comment]
On a side note, `T0` should be written as

```ts
type T0 = (1 | 2 | '3') & number
```

because `&` has higher precedence than `|`.

**Comment by NWYLZW** [comment]
> Working as intended. https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

Yes, I've seen this. So is this true even in the `else` branch? Here, this looks very strange.

**Comment by fatcerberus** [comment]
Yes.  Distribution is over the *entire conditional type*, not individual branches.  In other words it runs the ternary conditional expression once for each member of the union and then reassembles it at the end.

This does what you want:
```ts
export type Collect0<T, U> = [T] extends [[]] ? never : [T & U]
```

**Comment by NWYLZW** [comment]
<img width="947" alt="image" src="https://github.com/microsoft/TypeScript/assets/51358815/f285a785-09e0-46cc-98c8-d9bf9e4cd63a">
You are faster than me, haha.

**Comment by NWYLZW** [comment]
A little weird, but I get it, thanks for your help.
