### ISSUE TITLE
Remove unused exports & dead code (using Knip)

### ISSUE THREAD

**Issue by webpro** [microsoft/TypeScript#56818]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Opened a PR (#56817) to clean up some code using [Knip](https://knip.dev).

The removed bits look fairly harmless and safe to merge from my untrained eye. Yet the question is also: should Knip be removed from the PR, or added to the `devDependencies` and some CI job to make sure regression won't creep in later down the road?

I'll do my part by improving Knip itself and adding it to [Knip's integration tests](https://github.com/webpro/knip/blob/main/.github/workflows/integration.yml) as to not cause you more trouble later.

Thanks a lot for being such a stable source file parser (and so much more), this is a small PR to give something back :)

**Comment by RyanCavanaugh** [comment]
Not gonna merge anything infrastructural until people are back from holidays, but we'll discuss
