### ISSUE TITLE
`export {} from 'xxx'` got wrongly compiled to `export {}`

### ISSUE THREAD

**Issue by thisrabbit** [microsoft/TypeScript#56820]
### 🔎 Search Terms

reexport, export {} from

### 🕗 Version & Regression Information

- This is NOT a crash
- This changed between versions ______ and latest
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about import/export, but non of them match
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20231217#code/KYDwDg9gTgLgBAbwL5wGZQgWzgclQSwBtgcg

### 💻 Code

index.ts
```ts
export {} from './file';
```

file.ts
```ts
export function foo() {}

console.log('side effect')
```

### 🙁 Actual behavior

`index.ts` was compiled to:
```js
export {}
```
if `"module": "esxx"` and any other ESM settings,

and the following code under CJS module systems:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

### 🙂 Expected behavior

Compiled `index.js` should preserve the `from './file'` so that the statement has the same semantic (a reexport that has some side effect).

That is, if the code snippets above are raw JavaScript, then executing them should have `'side effect'` string printed on command line, however, given TypeScript compiled code, it will not print that string. (In both scenarios, the entry point is index.js)

**Comment by guillaumebrunerie** [comment]
I believe this is by design, use the `verbatimModuleSyntax` option to get the desired behavior, that’s what this option is for (https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax).

**Comment by thisrabbit** [comment]
@guillaumebrunerie Thanks for providing the link and I have read it and tried it manually, the `verbatimModuleSyntax` option is truly helpful in preserving blank expression `export/import {} from 'xxx'` in case of any side effects, and it is in the experiment did I notice that if that option is disabled, `import {} from 'xxx'` will also be compiled to `export {}`.

Though this problem can be workaround by using that option, I think it is just a coincident, since `verbatimModuleSyntax` is designed to easily handle type import/export and value import/export, this issue is more focused on side effects if import/export specifier list is empty.

**Comment by RyanCavanaugh** [comment]
This behavior is consistent with our other import removal strategy. Enabling VMS is the correct configuration change to make if you have modules with side effects.
