### ISSUE TITLE
Static class field allows colon value with no assignment

### ISSUE THREAD

**Issue by TrueWill** [microsoft/TypeScript#56837]
### 🔎 Search Terms

static

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about static

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ0PQgFzNglsNAEZgBOAXNNmQK4CmA3KgL6qrDwB2E8I9AOhDwA5gAoE8AaTIBKRtAD0i6LS4ATegDN8XeutRA

### 💻 Code

```ts
class Foo {
    static bar: true;
}

console.log(Foo.bar); // undefined
```

### 🙁 Actual behavior

I spotted this in production code.

The developer intended to write

```ts
class Foo {
    static bar = true;
}
```

which makes sense. TypeScript gives no errors or warnings with the colon-value. While you can use a colon to specify a type when assigning a value, that does not seem to be what is happening here. I can see no reason why anyone would intentionally write the original code.

### 🙂 Expected behavior

TypeScript reports an error.

**Comment by fatcerberus** [comment]
This technically may not a bug but a missing feature.  In any case, duplicate of https://github.com/microsoft/TypeScript/issues/27899.

**Comment by fatcerberus** [comment]
> I can see no reason why anyone would intentionally write the original code.

It can sometimes make sense to write code like this, if you intend to do the actual initialization in a `static` block:

```ts
class Foo {
    static bar: boolean;
    static {
        bar = isBar();
    }
}
```

Note that `true` is a valid literal type; in fact `boolean` is equivalent to `true | false`.

**Comment by TrueWill** [comment]
Closing as duplicate.
