### ISSUE TITLE
Improvements for `String`

### ISSUE THREAD

**Issue by thegitduck** [microsoft/TypeScript#56833]
### ⚙ Compilation target

ES5 (or any other)

### ⚙ Library

typescript

### Missing / Incorrect Definition

I'd like to make the `String` interface generic

### Sample Code

```TypeScript
type Animal = 'DOG' | 'CAT';

const animal: Animal = 'DOG"

const lowerAnimal = animal.toLowerCase(); 
//     ^? const lowerAnimal: string

// I would prefer the type to be interpreted more accurately as `LowerCase<Animal>`
```

**Comment by thegitduck** [comment]
I'd be happy to create a PR to add these changes to the String interface if the change is acceptable, but wanted to post here before doing the work in case this is a change that would not be desirable.

**Comment by fatcerberus** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/44268

**Comment by thegitduck** [comment]
oops, thanks!
