### ISSUE TITLE
Generic index signatures

### ISSUE THREAD

**Issue by mckravchyk** [microsoft/TypeScript#56843]
### 🔍 Search Terms

generic index signatures

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

In a generic constraint, you can do something like `K extends string`  but `R extends Record<string, unknown>` requires R to have an index signature of type string.  Considering that TypeScript has a structural type system, would it not make more sense to allow R to extend `Record<I, unknown>` as long as R's index signature is assignable to (extends) I?

### 📃 Motivating Example

In some simpler cases it's possible to do something like `type C<R extends Record<keyof R, unknown>> = ...` but it cannot be always applied - i.e. in the code below I have to explicitly define the keys / index signature type as an extra argument, that has to be passed to each generic in the generic dependency chain.

[Playground](https://www.typescriptlang.org/play?#code/PTAEHEFMBcGdWgCwPa0qA1pAnvZAzBRdAZQFcAjAK0gGNpQB3RAS1sVADcBDAGzPQATZJHgA7ZA0gAPaJDGDQAAwAqSgHQAoGQAdkAJwbRsO9ADlkYlScgBpHLAA85anSmz5g+ACU6BwY6w0PosYgDmoAA+oGJkALYUkPpRoLDYCci8ADSgZGIYEoxiAHw5KsWgALygAN6aoKAA2vbYoKGYOASgLjT0ALoAXN2UvdDNOH2gMnIK8CqgAPwxkJxJoEMtmgC+jVjYXT1ufQDcmtrSeoYINqAAssiCfADyOtAslvDVvrT+gcGhYRyeQKyCKxVOugMRhu90evAAwpZ8Cwwo5bFMPLNUv9whUvn59AFbDlYc9Xu8xPBorFeLxwWdIVdQnJ9PhuLR0KTeLASLw2JA0RiZl5sSFwjlEWJkRFpp54FzJdK0cUKnUGshTGISNBuHIAPpDNUNJpcszcOLodp7LqKlGDUAUZCZSDcMT1UBbM7q8kfA21d0NRqm82WsSgCxWGwtJy2wExMi04r22NBh58M0Wvruz2ezTMpJsjmgADqBgwsB07MgXPgRriad4AEZDQG2mIWNBfKt9Gg-Y7na7s9szsZTN0+UXqjXefzHNbCKX9OXKxyazlF8uqzXimcgA)
```ts
// Gets those keys of the Subject which value does not extend `T`.
export type NonTypeKeys<Subject extends Record<string | number | symbol, unknown>, T> = {
  [Key in keyof Subject]: Subject[Key] extends T ? never : Key
}[keyof Subject];

export type ModalOptions = Record<string, unknown>;
export type ModalConfig<K extends string> = Record<K, ModalOptions | null>;

export interface ModalsSlice<K extends string, Config extends ModalConfig<K>> {
  openState_: {
    [ModalName in keyof Config]: boolean
  }

  options_: {
    [ModalName in NonTypeKeys<Config, null>]: Config[ModalName]
  }
}

interface WorkspaceModals {
  modal1: {
    initReverse_: boolean
  }
}

type Slice = ModalsSlice<keyof WorkspaceModals, WorkspaceModals>
```

It just feels like the generic should automatically assume the index signature of the input and treat it a wide index signature like string, exactly like a regular type K extends string becomes the generic, why does the index signature cannot be a generic?

### 💻 Use Cases

1. What do you want to use this for?
To properly type generic constraints

2. What shortcomings exist with current approaches?
In some cases I need to define an extra generic parameter for the index signature / keys type.

3. What workarounds are you using in the meantime?
Same as 2.

**Comment by jcalz** [comment]
> index signatures
Mapped types like `Record<K, ⋯>` and `{[P in K]: ⋯}` only have index signatures if `K` is a wide type like `string`, `number`, `symbol`, or a pattern template literal like `` `foo${string}` ``.  But your examples are using things like `keyof WorkspaceModals`.  Do you really mean "index signatures" or just *keys*?  

> `R extends Record<string, unknown>` requires `R` to have an index signature of type `string`. 
Not for object literal types (as opposed to interfaces, as per #15300)

> would it not make more sense to allow `R` to extend `Record<I, unknown>` as long as `R`'s index signature is assignable to (extends) `I`?

Generally speaking `R extends Record<I, unknown>` only if `I extends keyof R`, not if `keyof R extends I` (e.g., `{a: string, b: string}` extends `{a: unknown}` but not `{a: unknown`, b: unknown, c: unknown}`).  Object types are naturally *contravariant* in their key types.  Well, *except for actual index signatures*, where they are unrelated.  It's weird.

**Comment by mckravchyk** [comment]
> Not for object literal types (as opposed to interfaces, as per https://github.com/microsoft/TypeScript/issues/15300)

I'm aware of it and I have been using it as a workaround for a long time, but it's quite limiting and I started to implement it "the right way (tm)" to not limit the consumers of the API to not use interfaces. 

> Do you really mean "index signatures" or just keys?

I was sort of using it interchangeably, I thought that 'a' | 'b' | 'c' could also be an index signature, not a wide type. I understand it's not and I see how it makes sense with structural typing, it's not assignable because the assignee lacks the index signature completely but the constraint has it. Nevertheless, I think the feature request still makes sense, it would just need to be formulated differently: "Allow a signatureless type to pass a constraint with index signature if the type of its keys is assignable to the index signature"

> Generally speaking R extends Record<I, unknown> only if I extends keyof R, not if keyof R extends I

Ok, I think I get it. Thanks. I thought that  `interface A { a: unknown }` would be assignable to Record<string, unknown>  - but I can imagine the latter now as a bigger type that the former cannot extend. So yes, this sort of does not make sense with the type system, thanks!

I still wish there was a way to auto-derive the keyof type from the generic input rather than having to define a separate parameter (the example above),  but that's a topic for another feature request.

**Comment by mckravchyk** [comment]
Actually I was able to remove the extra K parameter. I can pass `keyof T` where T is the interface generic, but the parameter where it's passed must be string | number | symbol

```ts
// Gets those keys of the Subject which value does not extend `T`.
export type NonTypeKeys<Subject extends Record<string | number | symbol, unknown>, T> = {
  [Key in keyof Subject]: Subject[Key] extends T ? never : Key
}[keyof Subject];

export type ModalOptions = Record<string, unknown>;

// Extends string | number | symbol so keyof Config can be passed
export type ModalConfig<K extends string | number | symbol> = Record<K, ModalOptions | null>;

// Passing keyof Config
export interface ModalsSlice<Config extends ModalConfig<keyof Config>> {
  openState_: {
    [ModalName in keyof Config]: boolean
  }

  options_: {
    [ModalName in NonTypeKeys<Config, null>]: Config[ModalName]
  }
}

interface WorkspaceModals {
  modal1: {
    initReverse_: boolean
  }
}

type Slice = ModalsSlice<WorkspaceModals>
```
