### ISSUE TITLE
Program is not completely re-used when imports change but import graph is identical 

### ISSUE THREAD

**Issue by devversion** [microsoft/TypeScript#56846]
### 🔎 Search Terms

program re-use, old program, oldProgram, imports changed, graph same, reuse result

### 🕗 Version & Regression Information

n/a

### 🙁 Actual behavior

Consider an incremental program using `oldProgram` in the compiler API. 

TypeScript will sometimes NOT fully re-use the program when a source file changed its imports even though the module graph remains the same. It considers structure changed. This is reasonable, but in some cases new imports may not signify that resolution results or the import graph has changed. A new import with existing imported modules may be added. e.g.

```
import {Directive} from `@angular/core`; // part of first compilation
import * as i0 from `@angular/core`; // added in the second! same module name!
```  

### 🙂 Expected behavior

TypeScript may consider deduplicating module names and would not treat the structure as invalidated. Later resolution validation as part of the re-use strategy may still bail out if discovers changes, but most of the time this is very likely the same (unless e.g. an import mode is used using `with`- this is NOT new behavior though)  

### Additional information about the issue

PR: https://github.com/microsoft/TypeScript/pull/56845

**Comment by sheetalkamat** [comment]
This is currently working as intended. 

Even though the program structure is not reused as is, the module resolution is reused and that reduces the cost of constructing new program. Having to check set of the the imports adds the cost that is avoided as linear check which is what it is in most cases and we dont want to regress in normal scenarios having to make a set of imports and then compare the imports when in most cases it could do with the one to one check
