### ISSUE TITLE
Generator type inference is not conforming correctly.

### ISSUE THREAD

**Issue by ccorcos** [microsoft/TypeScript#56840]
### 🔎 Search Terms

Generator type inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generators.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.2#code/C4TwDgpgBAwg9gWwQQwHYBMoF4oG8oDaA1hCAFxQDOwATgJaoDmAuhQEQ1tQC+AUL+ggBjADbIa0AGYBXVEOB04qKDVlQAFJNQV1ASmwA+KAHEIqCDWTA4NADzwkadABooANzh0X7z+gO6KDy9+AHoQqAB1GyJKXlVUTVl5RVQAKg19XF4ASBA6CBFMfFQ4QQBGdk4eXm5dUPCAETgISlQAcmAoAHdouNlEuQUldL08HLyCoqgS8squPlz8wrxp0ogAJjnq2vrI6Nj4geThjLHFyZWZiAqoDnmoZEpYRBQMcaWpq83bqu4oGrqvDCexoMT6CRkgxSI0y7wuxTWNzuPH+52WCME32Rfzh6NWggAzFs-o9no43rUgA

### 💻 Code

```ts
type Command = { [key: string]: "r" }

declare function run (fn: () => Generator<Command, void, void>): void

// Works
run(function* () {
	yield { node1: "r" }
})

// Doesn't work
run(function* () {
	yield { node1: "r" }
	yield { node2: "r" }
})

// Works
run(function* () {
	yield { node1: "r" } as Command
	yield { node2: "r" } 
})

// Works
run(function* () {
	yield { node1: "r" } 
	yield { node2: "r" } 
	yield { node3: "r" } as Command
})
```

### 🙁 Actual behavior

The yielded type gets inferred as `{ node1: "r"; node2?: undefined; }` instead of `Command`

### 🙂 Expected behavior

I expect the type to be inferred in a way that conforms with the type definition I specified.

**Comment by MartinJohns** [comment]
You're another victim of subtype reduction.

**Comment by jcalz** [comment]
#19513 adds those optional `undefined` props and then that's not assignable to an index signature as mentioned in #19613.  Looks like #39131 is also relevant, and the advice in there is to use ` { [key: string]: "r" | undefined }` instead.  Or you just annotate/assert to `Command` as you're doing.  In either case it doesn't look like they'll think this is a bug.

**Comment by RyanCavanaugh** [comment]
I think the best fix would be to write `function* (): Generator<Command>`. I don't see any bug per se here; the only change we might make here would just introduce inconsistency elsewhere.

Somewhat oddly, this is an error you can actually make go away by turning on `exactOptionalPropertyTypes`.

**Comment by fatcerberus** [comment]
> Somewhat oddly, this is an error you can actually make go away by turning on exactOptionalPropertyTypes.

Is this because it infers `{ x?: never }` for the nonexistent properties instead of `{ x?: undefined }`?
