### ISSUE TITLE
Bug With vscode

### ISSUE THREAD

**Issue by Alataq** [microsoft/TypeScript#56849]
### 🔎 Search Terms

There, when I used isNaN it require a number, but this function verify if the given string is a number, so the given argument should be a string. 

![image](https://github.com/microsoft/TypeScript/assets/72706324/268af2c3-cff6-4ac0-9ad5-7d156ac6b6d5)
![image](https://github.com/microsoft/TypeScript/assets/72706324/651b7645-5663-40f7-bf22-4b1eefe0b755)

### 🕗 Version & Regression Information

I am in the version 5.3.2

### 💻 Code

```ts
if(!isNaN(char)){
                isNumber = true
                hasNumber = true
 }
```

### 🙁 Actual behavior

It just show it need a number

### 🙂 Expected behavior

The needed type should be a string

**Comment by RyanCavanaugh** [comment]
See #55398, etc.
