### ISSUE TITLE
I can not get a right type

### ISSUE THREAD

**Issue by toplyb** [microsoft/TypeScript#56850]
The code:
```ts
let input = document.querySelector('#copy-input');
if (!input) {
  input = document.createElement('input') as HTMLInputElement;
}
```
I think it should get a HTMLInputElement, but I got the type is Element in WebStorm and it is 3.9.5 of the Typescript version.
How can i get the type of HTMLInputElement?

**Comment by MartinJohns** [comment]
Please use the correct issue template. And notice that this repository is not really meant as a support forum, it's for feature requests and bug reports. Better try the Discord or StackOverflow.

Your variable `input` is typed `Element` from the initialization. Later assigning a value typed `HTMLInputElement` does not change the type of the variable. Just use a second variable instead.
