### ISSUE TITLE
Construct signature not recognized when declared as a function-typed property

### ISSUE THREAD

**Issue by fsoikin** [Microsoft/TypeScript#5686]
```
var C : { 
   new: () => number; 
   new(x: number): string; 
}

var x = new C();
var y = new C(1);
```
([same thing on playground](http://www.typescriptlang.org/Playground/#src=var%20C%20%3A%20%7B%20%0D%0A%09new%3A%20()%20%3D%3E%20number%3B%20%0D%0A%09new(x%3A%20number)%3A%20string%3B%20%0D%0A%7D%0D%0A%0D%0Avar%20x%20%3D%20new%20C()%3B%0D%0Avar%20y%20%3D%20new%20C(1)%3B))

The `y` declaration works fine, but the `x` declaration generates an error saying that "Supplied parameters do not match any signature of call target".

Incidentally, this also doesn't work:

```
var C : { 
	new: {
		(): number; 
		(x: number): string;
	} 
}
```

One could argue that "who cares!", but I would object that this prevents some cases of code reuse, for example:

```
interface I<T> {}
type Ctor<T> = (t: T[]) => I<T>

var sn : { 
	new: Ctor<string> & Ctor<number>;
}

var nb : { 
	new: Ctor<number> & Ctor<boolean>;
}
```

**Comment by ahejlsberg** [comment]
The syntax `new: () => number` declares a property named `new`, not a constructor. The declaration actually behaves as expected:

```typescript
var C : { 
   new: () => number; 
   new(x: number): string; 
}

var x = C.new();   // Ok, call new method
var y = new C(1);  // Ok, call constructor
