### ISSUE TITLE
Generic error

### ISSUE THREAD

**Issue by LiST-GIT** [microsoft/TypeScript#56864]
### 🔎 Search Terms

Generic

### 🕗 Version & Regression Information
5

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygHgCqJQD1TABM1EBvAXwBpEAFPQlEsq2gUUaNIsQG0A1igCeALkQYATjDABzALriAFBASpC4gJIBKRAF4AfIgBucGMUQ1Emrsx7lEMgA4go43JUQAyegaXEAQygA8XIAKERIxzAXKAB+d2oIqKdJOCc0BPpvRGwACxg0bGEnFExNAySovGNmKEzxdiTKXXDKMNQMJXDq51dQzwDWZOrIvqgAQSywEABbACMUSQBuEdHxgCE4pW1xU3NV6po11PS0ULXq06cJ8QBGACYAZirRyIB6d8RZlCg8uGIt0QO30RgcVk+iDgAkuUR+fwBExB4NokKWaUka2O1RQtTA9Qub0iuLqADkAj8VGoCFBWrC3qp8TSAHTXCaHInVRnqKDM+H-QE7DmcyLclnjZnjdn0yyvSLHFrLIA

### 💻 Code

```ts
function test<T extends {}, P extends {}, E extends { [key: string]: (context: I) => void }, I extends { input: T } & P>(data: {
    input?: T,
    props?: P & ThisType<I>,
    events?: E,
}) {
}
test({
    input: {} as {
        inputA?: number;
        inputB?(): void;
    },
    props: {
        propA: 123,
        // methodA: () => { }, // ok
        methodA() { }, // error
    },
    events: {
        eventName(context) {
            context.propA;
                 // ^ Property 'propA' does not exist on type '{ input: { inputA?: number | undefined; inputB?(): void; }; }'.
            context.methodA();
                 // ^ Property 'methodA' does not exist on type '{ input: { inputA?: number | undefined; inputB?(): void; }; }'.
            context.input.inputA;
        },
    },
});
```

### 🙁 Actual behavior

Both are defining functions, but using an arrow function does not result in an error, whereas using a regular function does.

### 🙂 Expected behavior

In both cases, there should be no error reported.

**Comment by MartinJohns** [comment]
> This is a crash

The compiler doesn't crash for me. What version are you using? Or are you confusing an error with a compiler crash?

**Comment by LiST-GIT** [comment]
I'm sorry, I got confused.

**Comment by julienandreu** [comment]
I tried to determine the proper type for your test function and it seems I have good result here:
https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygHgCqJQD1TABM1EBvAXwBpEAFPQlEsqgPgApiBDKbgLgoAoRKMQwwABxBQA-IOzURYyQCc4ktPPpKxeAG7MoWwcL16A2gGsUAT0EZVEgOYBdQRwgJUhQeQnSUAqUiABk9ACUiAC8bIj6cDDEiMqiNEKUUeQZQqgYHNl6ATJ+IdysqebFUACC2mAgALYARiiqANyVRVIyAEKyHBGCCUmdeul6ahpofpVTkjWCAIwATADMumIA9FuIjShQABZwxIuIgzFx5Ig0iDuIcFaV+0cnNRfXt-dt6qqVE2IUIYwMZZuZAcCoAA5bj7TzeAhQLJdcGILwgxEAOnmNTGqL06J8UExL2Op0GePxokJWOqmOquJRaU2zIyEXaQA

Here is the code:
```typescript
function test<T extends {}, P extends {}>(data: {
    input?: T,
    props?: P,
    events?:  {
        [key: string]: (context: {input: T} & P) => void 
    },
}) {
}
test({
    input: {} as {
        inputA?: number;
        inputB?(): void;
    },
    props: {
    propA: 123,
    // methodA: () => { }, // ok
    methodA() { }, // ok
    },
    events: {
        eventName(context) {
            context.propA;
            context.methodA();
            context.input.inputA;
        },
    },
});
```

**Comment by LiST-GIT** [comment]
Thank you for your answer.
