### ISSUE TITLE
type narrowing for getday

### ISSUE THREAD

**Issue by imwh0im** [microsoft/TypeScript#56865]
### 🔎 Search Terms

getday

### 🕗 Version & Regression Information

All versions

### 🙁 Actual behavior

```ts
const now = new Date();
const now_day = now.getDay(); // type "number"
```

### 🙂 Expected behavior

```ts
const now = new Date();
const now_day = now.getDay(); // type "0 | 1 | 2 | 3 | 4 | 5 | 6"
```

### Additional information about the issue

Using type narrowing will be return correct type and improve usability.

**Comment by MartinJohns** [comment]
A change like this was previously rejected: https://github.com/microsoft/TypeScript/issues/36401#issuecomment-578217960
