### ISSUE TITLE
refactor 

### ISSUE THREAD

**Issue by Freed-Wu** [microsoft/TypeScript#56879]
### 🔍 Search Terms

Can tsserver support refactor like clangd and pyright?

<https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction>

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Refactor function allow user to open a new window to refactor variable names.

### 📃 Motivating Example

This is an example about refactor in clangd.

![a](https://github.com/microsoft/TypeScript/assets/32936898/2ad19f16-9c6f-40e2-bd44-749abf135405)

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by fatcerberus** [comment]
How is this different from right click -> Rename Symbol (or pressing F2)?

**Comment by Freed-Wu** [comment]
This is rename:
![a](https://github.com/microsoft/TypeScript/assets/32936898/ca84e08b-ec27-4dcd-b1b6-7a9d221aefb2)

refactor will open a new window to display what variables will be changed in real time. rename will not.

**Comment by Freed-Wu** [comment]
And most language server, such as clangd, pyright. if it support rename, it usually support refactor, because these two features share same logic and code, after realizing one, realizing another is very easy. So I think support refactor is reasonable, especially rename have been realized.

**Comment by Freed-Wu** [comment]
![a](https://github.com/microsoft/TypeScript/assets/32936898/a8c78c0d-1c14-451d-9dd6-a31ccaaf8ee9)

I found latest tsserver have supported refactor. :+1:
