### ISSUE TITLE
Typed Array missing one or more of type definitions for TypedArrays.prototype functions

### ISSUE THREAD

**Issue by rcampbel** [microsoft/TypeScript#56874]
### ⚙ Compilation target

ESNext

### ⚙ Library

typescript

### Missing / Incorrect Definition

TypedArray.prototype.at

### Sample Code

```TypeScript
// Note Uint8Array is one of many classes that extends the TypedArray
const buffer = new Uint8Array();
buffer.at(0);
```

### Documentation Link

MDN 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#exceptions

TypedArray Spec
- https://tc39.es/ecma262/multipage/indexed-collections.html#sec-%typedarray%.prototype.at

**Comment by fatcerberus** [comment]
Works for me if `lib` is at least `es2022`: [Playground](https://www.typescriptlang.org/play?target=9#code/MYewdgzgLgBARgVwGZIKYCcYF4ZlQdxgFUBLMKADgEF10BDATwAoBKAbgChEUMA6OqEwAM7DkA)

**Comment by rcampbel** [comment]
Hmmm..... Thought I had my `compilerOptions.target` set to `es2022`, not `es2017`
I think that was the actual issue.

**Comment by fatcerberus** [comment]
@rcampbel For the record, the actual thing that controls it is `lib` - it’s just if you don’t have `lib` set explicitly then it’s inferred from `target`
