### ISSUE TITLE
Complete @name, @version, ... metadata of user script

### ISSUE THREAD

**Issue by Freed-Wu** [microsoft/TypeScript#56887]
### 🔍 Search Terms

Currently, tsserver only complete @ts-*:

![screen-2023-12-27-22-48-08](https://github.com/microsoft/TypeScript/assets/32936898/973a8b47-bdfd-45e7-ad6f-91f0f11f6b64)

<https://greasyfork.org/en/help/meta-keys> lists all metadata of user script. such as `@name`, `@version`, I hope when I input `@` can get the completion.

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Add completion for metadata of user script.

### 📃 Motivating Example

I think this feature should be very simple. Although it is simple, it can help user script developer create their scripts easierly.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by nmain** [comment]
Most Javascript runtimes are not Greasy Fork.  Wouldn't this make more sense in an editor plugin specifically created for Greasy Fork?

**Comment by Freed-Wu** [comment]
Hey, greasy fork is not a javascript runtime. I guess you want to say [user script](https://openuserjs.org/about/Userscript-Beginners-HOWTO)?

I support this feature due to the following reasons:

1. IMO `@name`, `@version` is just some keyword like doxygen's `@param`, should be a very simple feature and will not cost very long time to realize it.
2. the completion will happened in comment block ahead of `*.user.js`, so it will not effect the user in the completion of normal code.
3. `*.user.js` have many users, See <https://greasyfork.org> and <https://openuserjs.org/> to see the number of scripts and developers. And the number of users will be greater than the number of scripts and developers. So it is not a requirement of a few people. It can help a large number of people.

**Comment by RyanCavanaugh** [comment]
TypeScript tells you about TypeScript constructs. It's not feasible for us to suggest every userland comment DSL that might exist. Suggestions are just suggestions, after all.

**Comment by Freed-Wu** [comment]
So is there any solution to allow user to add customized keywords for completion?
