### ISSUE TITLE
intersection of getters has wrong variance

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#56890]
### 🔎 Search Terms

getter intersection wrong variance

is:issue in-title: getter *(nothing relevant found)*
is:issue in-title: intersection variance *(nothing relevant found)*

Related in concept to the TypeScript documentation for ["Optional Variance Annotations for Type Parameters"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#optional-variance-annotations-for-type-parameters)

### 🕗 Version & Regression Information

Same in TypeScript 4.3.5 ~ 5.3.2 (latest)

Prior to TypeScript 4.3.5, usage of #a was not allowed, but the same problem could obtained with different syntax.

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?jsx=0&ts=5.3.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVK2AB4AVAPgAoBKALhIG4AoRsPAZw3lgCYb4BvRvGHw2ITlApQa3KkxHwA5uPgxqNAIwAfbloDMTAL7wAvPFQgA7vEhQ2beEQCCAGgBKZQQoDE0+E-kRVlQOGGRMHDVpJyoBDAALLDYAOl8TKHpDIRExCSkaGIF4BKTUqFMuengshWVONVo3IrgMZBh8CgAGLgcoVABPHvg3OWrGQwpEQmo5ZmCOVQ09brMeJhglzuTysw0qgHp9+BAYGEiXG0i4TEYN5e2K7gOj1Bxj0-PL0-AMW82HswGeCHd5nGAXVjfG5-e4wZ7wbS6PQQq4-ObsCQwPR8Lw5FSSaSI2a1FQNTQ6IzwABkAmywlyXHySOJIjqqnUSMpZgs1ls9kcTmOAA8MCBUMAHIj9BcmiARWKJQidPpPHT4L4+AE1fMMGEIlECrF+CUUmkMjU8XlokbiolTTtKmMSfV1E1+KpxG0Ot07FwBkMRlUshMpsAZkwWBjFgAWFZcLHrDSxgEI+EnMEoqG-DbJh1PYEvN7pz6Q67ZpNbB1AkHF8FfMvMHNbOEF+BJeDcC45eI4ZAQYDwABGCClemEAEJJ+P4AAJACibjn8AAkgBleAkefwABCAFUAOKMIA)

### 💻 Code

```ts
declare function fid<T>():T;

const ar2: {
    set a(a:2);
    get r():1|2|3;
} = new class <A,R>{
    #a: A;
    constructor(a:A) {this.#a=a;}
    set a(a:A) { this.#a = a; }
    get r():R { return (0 as any as R); }
}(fid());

const r130 = ar2;
r130.a = 1; // error, correct
r130.a = 2; // no error, correct
r130.a = 3; // error, correct

r130.r; // 1|2|3, correct

const ar3: {
    set a(a:1|2);
    get r():1|2;
} & {
    set a(a:2|3);
    get r():2|3;
} = new class <A extends 1|2|3, R extends 1|2|3>{
    #a: A;
    constructor(a:A) {this.#a=a;}
    set a(a:A) { this.#a = a; }
    get r():R { return (0 as any as R); }
}(fid());

const r140 = ar3;
r140.a = 1; // error, correct
r140.a = 2; // no error, correct
r140.a = 3; // error, correct

r140.r; // is 2,    should be 1|2|3  !!!! HERE IS THE BUG
```

### 🙁 Actual behavior

```ts
r140.r; // is 2,    should be 1|2|3  !!!! HERE IS THE BUG
```
shows the intersection of getters range evaluated as `2` ...

### 🙂 Expected behavior

... but it should be `1|2|3`.

### Additional information about the issue

It seems as though the `r` getter is being treated as a plain property.

Recall "Optional Variance Annotations for Type Parameters". If I add the in and out annotations here the in gives an error, and the out doesn't change the range - it remains the wrong value `2`.

```ts
declare function fid<T>():T;

const ar2: {
    set a(a:2);
    get r():1|2|3;
} = new class <in A, out R>{
//             ~~~~
// Type '(Anonymous class)<super-A, R>' is not assignable to type '(Anonymous class)<sub-A, R>' as implied by variance annotation.
//   Types of property '#a' are incompatible.
//     Type 'super-A' is not assignable to type 'sub-A'.(2636)
    #a: A;
    constructor(a:A) {this.#a=a;}
    set a(a:A) { this.#a = a; }
    get r():R { return (0 as any as R); }
}(fid());

const r130 = ar2;
r130.a = 1; // error, correct
r130.a = 2; // no error, correct
r130.a = 3; // error, correct

r130.r; // 1|2|3, correct

const ar3: {
    set a(a:1|2);
    get r():1|2;
} & {
    set a(a:2|3);
    get r():2|3;
} = new class <in A extends 1|2|3, out R extends 1|2|3>{
//             ~~~~~~~~~~~~~~~~~~
// Type '(Anonymous class)<super-A, R>' is not assignable to type '(Anonymous class)<sub-A, R>' as implied by variance annotation.
//   Types of property '#a' are incompatible.
//     Type 'super-A' is not assignable to type 'sub-A'.(2636)
    #a: A;
    constructor(a:A) {this.#a=a;}
    set a(a:A) { this.#a = a; }
    get r():R { return (0 as any as R); }
}(fid());

const r140 = ar3;
r140.a = 1; // error, correct
r140.a = 2; // no error, correct
r140.a = 3; // error, correct

r140.r; // is 2,    should be 1|2|3  !!!! HERE IS THE BUG
```

Even if the `in` keyword is omitted and only the `out` keyword is used, the range is still the wrong value `2`.
If there were any error message for using the in or out keywords, it should be that they are not necessary in this context.

**Comment by Andarist** [comment]
I'm not sure where the bug is and how this relates to variance. `R` is covariant here from what I can tell. However, it also doesn't matter what happens within the value that you assign to `ar3`/`r140`. You have there an explicit annotation so the given repro can be slimmed down to:
```ts
declare const ar3: {
  set a(a: 1 | 2);
  get r(): 1 | 2;
} & {
  set a(a: 2 | 3);
  get r(): 2 | 3;
};

ar3.r; // 2
```

Since this is an intersection type, the types of its properties are intersected. This is also consistent with just plain properties:
```ts
declare const ar4: {
  r: 1 | 2;
} & {
  r: 2 | 3;
};

ar4.r; // 2
```

**Comment by craigphicks** [comment]
The slimmed down version as you described would have been sufficient to post the bug.

However, as it happens the initializer makes it easy to see that `R` does not have to correspond to any plain property.  It corresponds to a function return range.

Recall ["Optional Variance Annotations for Type Parameters"](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#optional-variance-annotations-for-type-parameters).  If I add the `in` and `out` annotations here the `in` gives an error, and the `out` doesn't change the range - it remains the wrong value `2`.

However, neither `in` nor `out` should be necessary because those are already implied by the keywords `get` and `set`.

```
**declare function fid<T>():T;

const ar2: {
    set a(a:2);
    get r():1|2|3;
} = new class <in A, out R>{
//             ~~~~
// Type '(Anonymous class)<super-A, R>' is not assignable to type '(Anonymous class)<sub-A, R>' as implied by variance annotation.
//   Types of property '#a' are incompatible.
//     Type 'super-A' is not assignable to type 'sub-A'.(2636)    
    #a: A;
    constructor(a:A) {this.#a=a;}
    set a(a:A) { this.#a = a; }
    get r():R { return (0 as any as R); }
}(fid());

const r130 = ar2;
r130.a = 1; // error, correct
r130.a = 2; // no error, correct
r130.a = 3; // error, correct

r130.r; // 1|2|3, correct

const ar3: {
    set a(a:1|2);
    get r():1|2;
} & {
    set a(a:2|3);
    get r():2|3;
} = new class <in A extends 1|2|3, out R extends 1|2|3>{
//             ~~~~~~~~~~~~~~~~~~
// Type '(Anonymous class)<super-A, R>' is not assignable to type '(Anonymous class)<sub-A, R>' as implied by variance annotation.
//   Types of property '#a' are incompatible.
//     Type 'super-A' is not assignable to type 'sub-A'.(2636)    
    #a: A;
    constructor(a:A) {this.#a=a;}
    set a(a:A) { this.#a = a; }
    get r():R { return (0 as any as R); }
}(fid());

const r140 = ar3;
r140.a = 1; // error, correct
r140.a = 2; // no error, correct
r140.a = 3; // error, correct

r140.r; // is 2,    should be 1|2|3  !!!! HERE IS THE BUG
```

If there were any error message for using the `in` or `out` keywords, it should be that they are not necessary.

**Comment by craigphicks** [comment]
@Andarist 

It should not be consistent with a plain property.

`R` does not have to correspond to any plain property. In this case (the rhs) it corresponds to a function return range. That is the general case. So it should be union, and not intersection.

I've added more information in the Additional information about the issue section.

**Comment by Andarist** [comment]
> In this case (the rhs) it corresponds to a function return range

Getters are special in this sense though. In the the TS type system they are governed more like properties than functions.

> I've added more information in the Additional information about the issue section.

I'm afraid that this doesn't clarify the issue for me. Note that I'm really not an expert on variance - so perhaps you should try to explain this in more depth, step by step. For the time being, this feels quite OK to me - type parameters used as their return types are covariant, getters are like properties so their read types are just intersected in here.

Perhaps the best way to explain this is to show the unsoundness in practice. How do you create a runtime-space value that is assignable to this type and how does accessing `.r` returns you an incorrect type that doesn't match the runtime.

**Comment by craigphicks** [comment]
> Getters are special in this sense though. In the the TS type system they are governed more like properties than functions.

Does that mean that in the case of functions, the OR'ing of function outputs makes sense to you?

A getter is a function that may return a constant or a random value, as extreme example - it isn't the case that it *must be* correlated with any state variable.  Of course it may (and usually is) correlated with state variables, but we can't assume anything about that correlation unless it is explicitly stated in getter type definition.

When we talk about intersection of functions at runtime, (I assert here) that what we are trying to calculate is the type range of valid inputs - that is a hard constraint that must be honored - while we have no such constraint on what outputs are read.

There is also anecdotal code snippet - although I am not saying it proves anything:
```
        function inferFromSignature(source: Signature, target: Signature) {
            if (!(source.flags & SignatureFlags.IsNonInferrable)) {
                const saveBivariant = bivariant;
                const kind = target.declaration ? target.declaration.kind : SyntaxKind.Unknown;
                // Once we descend into a bivariant signature we remain bivariant for all nested inferences
                bivariant = bivariant || kind === SyntaxKind.MethodDeclaration || kind === SyntaxKind.MethodSignature || kind === SyntaxKind.Constructor;
                applyToParameterTypes(source, target, inferFromContravariantTypesIfStrictFunctionTypes);
                bivariant = saveBivariant;
            }
            applyToReturnTypes(source, target, (source, target, priority) => {
                inferWithPriorityMaybe(source, target, priority);
            });
        }
  ```
You can see that parameters make contravariant contributions while returns make covariant contributions.
However, because of the funky way TypeScript converts intersections into overloads, and then uses only only the last overload for inference, its actually hard to see that playing out in practice.

**Comment by craigphicks** [comment]
@Andarist 
> How do you create a runtime-space value that is assignable to this type 

While trying to come up with an good real runtime example for intersection, which I haven't got yet,
I got the following results for union types, instead:

### union case

```
declare const id:<T>()=>T

function f2(x: {f:((a:1|2)=>1|2)} | {f:((a:2|3)=>2|3)} ){
    const r = x.f(id())
//                ^ const id: <2>() => 2,
//        ^ const r: 1 | 2 | 3
}

function f3(f: ((a:1|2)=>1|2) | ((a:2|3)=>2|3) ){
    const r = f(id())
//              ^ const id: <2>() => 2,  
//        ^ const r: 1 | 2 | 3
}


function f4(x: {set d(a:1|2); get r():1|2} | {set d(a:2|3); get r():2|3} ){
    x.d = id();
//        ^ const id: <1 | 2 | 3>() => 1 | 2 | 3
    x.r; 
//    ^    (property) r: 1 | 2 | 3
}
```
In these cases inference isn't required to see the return type `R`, but it is required to see the parameter type `D`.

You can also see that whereas the inferred function parameter is narrowed in cases `f3` and `f4`, the setter parameter is not narrowed in case `f5`.  I would expect it to be narrowed.  I will open a new issue for this: "getter inferred from union has incorrect variance".


### intersection case 

As for the intersection case, I tried this to generate an intersection "in the wild" (as opposed to constructed):

```
type F<D extends 1|2|3, R extends 1|2|3> = (d:D)=>R;

function g1(g: (((x:F<1|2,1|2>)=>void)|((x:F<2|3,2|3>)=>void))){
    g(id());
//  ^        g: (x: F<1 | 2, 1 | 2> & F<2 | 3, 2 | 3>) => void
//     ^  id: <F<1 | 2, 1 | 2> & F<2 | 3, 2 | 3>>() => F<1 | 2, 1 | 2> & F<2 | 3, 2 | 3>
}
```
As you can see the display result is simply the constructed intersection, and there is no way to access the members.
  
The question is, what is the type of the function that is assignable to both `F<1 | 2, 1 | 2>` and `F<2 | 3, 2 | 3>`.  TypeScript calculates that to be the overload `F<1 | 2, 1 | 2> & F<2 | 3, 2 | 3>`.

When we try to infer from that
```
declare const x: F<1 | 2, 1 | 2> & F<2 | 3, 2 | 3>
const r = x(id());
//    ^ r: 1 | 2
//           ^ const id: <1 | 2>() => 1 | 2

```
we get one overload only, which is not really satisfactory (a bug?).  

The narrowest *single* function that is assignable to both `F<1 | 2, 1 | 2>` and `F<2 | 3, 2 | 3>` is the union 
`F<1 | 2, 1 | 2> | F<2 | 3, 2 | 3>` which is just `F<1|2|3, 1|2|3>`.  At least that gives a symmetric answer. 

By the same logic, the following should hold: 
```
const ar3: {
    set a(a:1|2);
    get r():1|2;
} & {
    set a(a:2|3);
    get r():2|3;
}
ar3.a // 1|2|3
ar3.r // 1|2|3
```
which is opposite variance of plain properties.  At any rate, my original assertion no longer holds, so I have to clone this.

**Comment by fatcerberus** [comment]
@craigphicks You're just proving my hypothesis that TypeScript, in spite of its deficiencies in this regard (or maybe *because of them*?), is a gateway drug to type theory[^1]. 😆 

[^1]: And, if you’re ambitious and/or curious enough (like me!), category theory.
