### ISSUE TITLE
let tsserver support document link

### ISSUE THREAD

**Issue by Freed-Wu** [microsoft/TypeScript#56892]
### 🔍 Search Terms

Some language servers support document link:

![screen-2023-12-28-21-33-03](https://github.com/microsoft/TypeScript/assets/32936898/b79184f6-fd07-4328-b234-a2e14a07d23a)

Can tsserver support it? For example:

```javascript
import { commands, workspace } from 'coc.nvim';
```

Display the path of `node_modules/coc.nvim` in `'coc.nvim'`.

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Support document link.

### 📃 Motivating Example

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by RyanCavanaugh** [comment]
TS Server doesn't support LSP, so this request doesn't really make any sense? "Go to Definition" provides the list of places where that module resolves to.

**Comment by Freed-Wu** [comment]
> TS Server doesn't support LSP

What is the meaning? I thought `tssever` is a language server, am I wrong?

**Comment by RyanCavanaugh** [comment]
TCP is a communication protocol. That doesn't mean all communication occurs over TCP.
