### ISSUE TITLE
Import package with lots of non-modular .d.ts files?

### ISSUE THREAD

**Issue by TheChilliPL** [microsoft/TypeScript#56901]
### 🔎 Search Terms

no modules .d.ts, type declaration globals, merge .d.ts, typescript multiple declaration files

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about global type declarations (nothing found)

### ⏯ Playground Link

Trying to develop library: https://github.com/TheChilliPL/rmmv-types/tree/dev

### 💻 Code

`tsconfig.json` of the imported package:
```json
{
  "compilerOptions": {
    "module": "None",
    "moduleResolution": "Node",
    "target": "ES5",
    "sourceMap": true,
    "strict": true,
    "baseUrl": "src/",
    "outDir": "dist/",
    "skipLibCheck": true, // TODO fix Window problem.. somehow
    "lib": [
      "ES6"
    ],
    "noImplicitOverride": true,
//    "noImplicitAbstractOverride": true, // https://github.com/microsoft/TypeScript/issues/47250
  },
  "include": [
    "src/"
  ]
}
```

Added dependency `"rmmv-types": "TheChilliPL/rmmv-types#dev"`, then tried importing in many different ways and all tsconfig.json configurations I could think of; nothing worked.

### 🙁 Actual behavior

The IDE (WebStorm) recognizes the types (the syntax highlighting changes, it shows the `.d.ts` file on hover & go to declaration works) but red squiggly line appears saying cannot find the type.

Whenever trying to compile using tsc, for each subdirectory of `src` it throws:
```
error TS2688: Cannot find type definition file for 'subdirectory'.
  The file is in the program because:
    Entry point for implicit type library 'subdirectory'
```

### 🙂 Expected behavior

The global types should be recognized and it should compile

### Additional information about the issue

It's a project of type declarations for completely non-modular JS code, around 30k lines of code in fact.  
Preferably, it'd be best if the source could stay divided into lots of files, as having thousands of methods in one file seems really difficult to maintain.

**Comment by RyanCavanaugh** [comment]
This seems like a problem you're having, not a bug report. What's the defect?

**Comment by TheChilliPL** [comment]
Well the types aren't available at all. I looked through the documentation, but there's barely anything about non-modular type declarations
