### ISSUE TITLE
"else" is omitted JS code generated for a if-else statement in promise callback

### ISSUE THREAD

**Issue by cjackie** [microsoft/TypeScript#56917]
### 🔎 Search Terms

I typescript version that I used is  "typescript": "^4.9.5".  In the IF-ELSE statement, the else block is unconditionally run.

### 🕗 Version & Regression Information

- Incorrect JS code generated.
- This bug is in typescript version ^4.9.5

### 💻 Code

```ts
fetch("http://localhost:3000/api", {
    method: "POST",
    body: JSON.stringify({}),
    headers: {
        "Content-Type": "application/json"
    }
}).then((e => {
    if (e.ok) return e.json().then((e => {
        console.log("good")
    }));
    console.log("failed 2")
})).catch((e => {
    console.log("failed 1")
}))
```

### 🙁 Actual behavior
// the generated code is 

fetch("http://localhost:3000/api", {
    method: "POST",
    body: JSON.stringify({}),
    headers: {
        "Content-Type": "application/json"
    }
}).then((e => {
    if (e.ok) return e.json().then((e => {
        console.log("good")
    }));
    console.log("failed 2")
})).catch((e => {
    console.log("failed 1")
}))

### 🙂 Expected behavior

fetch("http://localhost:3000/api", {
    method: "POST",
    body: JSON.stringify({}),
    headers: {
        "Content-Type": "application/json"
    }
}).then((e => {
    if (e.ok) return e.json().then((e => {
        console.log("good")
    }));
    **else** console.log("failed 2")
})).catch((e => {
    console.log("failed 1")
}))

**Comment by MartinJohns** [comment]
There is no `else` in your code.

**Comment by RyanCavanaugh** [comment]
I don't understand why this would matter, let alone be desirable. If you want the `else` the output, write it in the input, that's how everything else in TS works.
