### ISSUE TITLE
The generic is changed if used `extends`

### ISSUE THREAD

**Issue by Emiyaaaaa** [microsoft/TypeScript#56921]
### 🔎 Search Terms

extends

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about 'extends'

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20240101#code/PTAEBUGVQNwUwE4GcCWB7AdqArAOgMy4BMAUCQC4CeADnBHEuQDzgB8oAvBKHAB7lwMAEySgAhhkqgA-KEgBXAEbgGzNqABcoDHHgIA3GSq05SlYxbsuAQQQIxlS2QBm8jAGNy6LAIvge-IIioABKcO5oCEJMjAgoGADmADSgbgDWGGgA7hisrAAU8dTy5FrgAJSgAN4kAJAgAbSecEJ1ERiMoHEJABbknKAAjOKi6Zk5I6bKqkzGcGjOoEUl7A0K036sdc6RoPntnQigC10oveSVNbW1c6EDcycGoA3gdQC+ZPVgmf18TQJCFIAA3M5CBoEUcB6Yhg6COKFEP1ASDEAFs6OQ0KAgetQUC2phOlkEJgEgNhmJRhgMtksJT6BYHotluRVmBQU5ajsjvtCf0ssdFsTSZc6jcaHQAOr3CUnLL6Z5gKqgADavC0sXiCQAuloxrTQB9ah8PiQQBwLZardabba7faHY7rWQGgBJUDQ+CgTGgIRY8g9Og7AA2wey3p6Wu9WNRYjSdBBqnBtyykTSFAloAAYiheC0OeAUhFqJR-Fx1OWAgJhKIJFJZLiZsXS+wtDo9IYSK4PF5MN7VEQWFWgqIwhEojFyHFEil9Tk8oUMMVShBRV9GuEAQSOr9eNRyZM53TRDm80IOUylkuVors7n8zM2NtdrydzxBY01+KTABRGW0E44AVF53hIN4gA

### 💻 Code

```ts
type Test<T> = T extends any ? SubTest<T> : never;

type SubTest<T> = Array<T>

function test<T extends Record<string, unknown>>(input: T) {
	// expected
	const right = 1 as unknown as SubTest<typeof input> // SubTest<T>
	for (const r of right) {
		type R = typeof r; // T
	}

	// not expected, `Test` behavior is not same to `SubTest`
	const wrong = 1 as unknown as Test<typeof input> // Test<T>
	for (const w of wrong) {
		type W = typeof w; // { [x: string]: unknown }
	}
}

//=======================================================================

// I have to do the follow thing to make `Test` type work
type FixedTest<T, copyT = T> = T extends any ? SubTest<copyT> : never;

function test2<T extends Record<string, unknown>>(input: T) {
	// expected
	const exp = 1 as unknown as FixedTest<typeof input> // FixedTest<T>
	for (const e of exp) {
		type E = typeof e; // T
	}
}
```

### 🙁 Actual behavior

```ts
function test<T extends Record<string, unknown>>(input: T) {
	const wrong = 1 as unknown as Test<typeof input> // Test<T>
	for (const w of wrong) {
		type W = typeof w; // { [x: string]: unknown }
	}
}
```

### 🙂 Expected behavior

```ts
function test<T extends Record<string, unknown>>(input: T) {
	// expected
	const right = 1 as unknown as Test<typeof input> // Test<T>
	for (const r of right) {
		type R = typeof r; // T
	}
}
```

### Additional information about the issue

my solution is copy the type to make SubTest's behavior is same to Test currently:
```ts
type Test<T, copyT = T> = T extends any ? SubTest<copyT> : never;
```

but this solution also has some issue that `copyT` is miss the type inference:
```ts
type Test<T, copyT = T> = T extends object ? SubTest<copyT> : never;
// TS konw T is an object after `?` but don't know copyT is what type.
```

**Comment by fatcerberus** [comment]
No bug here; this is working as intended:
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types

If you don't want the distributive behavior, you can rewrite the type as
```ts
type Test<T> = [T] extends [any] ? SubTest<T> : never;
```

**Comment by Emiyaaaaa** [comment]
> No bug here; this is working as intended: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types
> 
> If you don't want the distributive behavior, you can rewrite(重写) the type as
> 
> ```ts
> type Test<T> = [T] extends [any] ? SubTest<T> : never;
> ```

Sorry I don't think so, I understood the distributive-conditional-types rules but haven't union in my case.

maybe the `keyof` caused you to misunderstand, I updated the playground

**Comment by fatcerberus** [comment]
Well, it seems to have *something* to do with distributivity because making the conditional type non-distributive fixes the issue:
[Playground link](https://www.typescriptlang.org/play?ts=5.3.2#code/PTAEBUGVQNwUwE4GcCWB7AdqArAOgMy4BMAUCQC4CeADnBHEuQDzgB8oAvKANrgC6oOAA9ycDABMkPAIYZKAgPyhIAVwBG4BszagAXKAxx4CANxkqtZes2MW7LgEEECaZTtkAZiowBjcuixRW3BBETFJUAAlOB80BHEmRgQUDABzABpQbwBrDDQAdwxWVgAKFOoVcn1wAEpQAG8SAEgQUNo-OHFm2IxGUGTUgAtyTlAARlBpKRy8wsmpVQ0tJgs4NA9Qcsr2VsWbbVZmjzjQEp6+hFB1-pQh8jrGpqbVqNHV69NQVvBmgF8yFpgPIjYTtUTiTIAA32kNAajgg2kMHQlxQUmBoCQ0gAtnRyGhQJC9lpId1MH18ghMKlRhMplkMLkClh6fsVjQ1hstuQdmA2WwjiczuSRvkrhtKdSHs1nhzQAB1N4c675ExfMD1HhCfRJFKpPj6GbM0D-Jr-f5AA)

**Comment by Emiyaaaaa** [comment]
> Well, it seems to have _something_ to do with distributivity because making the conditional type non-distributive fixes the issue: [Playground link](https://www.typescriptlang.org/play?ts=5.3.2#code/PTAEBUGVQNwUwE4GcCWB7AdqArAOgMy4BMAUCQC4CeADnBHEuQDzgB8oAvKANrgC6oOAA9ycDABMkPAIYZKAgPyhIAVwBG4BszagAXKAxx4CANxkqtZes2MW7LgEEECaZTtkAZiowBjcuixRW3BBETFJUAAlOB80BHEmRgQUDABzABpQbwBrDDQAdwxWVgAKFOoVcn1wAEpQAG8SAEgQUNo-OHFm2IxGUGTUgAtyTlAARlBpKRy8wsmpVQ0tJgs4NA9Qcsr2VsWbbVZmjzjQEp6+hFB1-pQh8jrGpqbVqNHV69NQVvBmgF8yFpgPIjYTtUTiTIAA32kNAajgg2kMHQlxQUmBoCQ0gAtnRyGhQJC9lpId1MH18ghMKlRhMplkMLkClh6fsVjQ1hstuQdmA2WwjiczuSRvkrhtKdSHs1nhzQAB1N4c675ExfMD1HhCfRJFKpPj6GbM0D-Jr-f5AA)

I trid that but not work in [my case](https://github.com/sindresorhus/type-fest/blob/02a95c540b38d0aa4e269b77fa7029935ce1df43/source/entries.d.ts#L57)(muti extends), I think `copyT` is the best way to fix my issue, but I also hope this issue can be fixed by TypeScript if this is a bug

https://github.com/sindresorhus/type-fest/issues/649

**Comment by RyanCavanaugh** [comment]
I don't recall the motivating example, but IIRC it's not "safe" to keep the type parameter here so instead we have to fall back to the constraint. Both behaviors are correct.

**Comment by rotu** [comment]
In the `wrong` branch, not only have we inferred the type of `w` differently, but it's not assignable to a variable of type `T` anymore. `let t:T = w;` gives:
> Type 'Record<string, unknown>' is not assignable to type 'T'.
> 'Record<string, unknown>' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'Record<string, unknown>'

In the [2.8 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#distributive-conditional-types) I noticed something slightly funny:

> In instantiations of a distributive conditional type `T extends U ? X : Y`, ... references to `T` within `X` have an additional type parameter constraint `U` (i.e. `T` is considered assignable to `U` within `X`).

I know that in the true branch, the type of `T` can't be simply the intersection `T & any`, since `T & any` is `any`. How is that assignability constraint represented if not an intersection? Is it possible that the assignability constraint is actually mangling the type?
