### ISSUE TITLE
stripInterval does not strip @internal for .js input, even though JSDoc doesn't care about JS vs. TS, it's JSDoc.

### ISSUE THREAD

**Issue by Pomax** [microsoft/TypeScript#56928]
### 🔎 Search Terms

`--stripInternal`

### 🕗 Version & Regression Information

- This changed between versions 3.6 and 3.7

### ⏯ Playground Link

https://www.typescriptlang.org/play?stripInternal=true&filetype=js#code/PQKhCgAIUgBBLAdgFwKYCdEEMA2UTDg6rKQD6ZAJgPYoDKAFtQO4AqD8AzpALyQCMAJgDMAbnBA

### 💻 Code

```ts
/**
 * @internal
 */
let __dontShowThis = 123;
```

### 🙁 Actual behavior

The DTS file is
```
/**
 * @internal
 */
declare let __dontShowThis: number;
```

### 🙂 Expected behavior

The DTS file should be empty, because the JSDoc says there is nothing public in this file.

### Additional information about the issue

When picking "typescript" as language in v3.7 and above, the DTS file is empty as it should be.
When picking "javascript" as language in 3.7 and above, the DTS file is not empty, despite the fact that there is no difference between the two when it comes to JSDoc.

**Comment by RyanCavanaugh** [comment]
The documentation says

> This is an internal compiler option; use at your own risk, because the compiler does not check that the result is valid

**Comment by Pomax** [comment]
And now I'm reporting it misbehaving so that can get fixed, because "use at your own risk" doesn't mean "we don't care if it does the right thing". It does the right thing, it just needs to do the right thing irrespective of the input language. Because that shouldn't matter, and 3.6 shows it didn't in the past.

**Comment by Pomax** [comment]
(not to mention that if issues like https://github.com/microsoft/TypeScript/issues/46515 get taken seriously, with code fixes, closing this just because it's about an internal option makes no sense)

**Comment by Pomax** [comment]
(@RyanCavanaugh ping to unmark this as completed)

**Comment by RyanCavanaugh** [comment]
I'm not sure we're on the same page here. The feature isn't supported. Our discretion to not bother to fix this is what it means for something to be unsupported.

**Comment by Pomax** [comment]
Apparently we're not. If a feature is not supported, don't expose it, and don't add it to the public docs. If you do, accept bug reports for it and consider whether they're easy to fix or not and decide to close based on _that_ instead.
