### ISSUE TITLE
Generic type validation incorrect with recursive type

### ISSUE THREAD

**Issue by ledenis** [microsoft/TypeScript#56925]
### 🔎 Search Terms

does not satisfy the constraint
recursive conditional type
generic constraints

### 🕗 Version & Regression Information

- This bug is present in every version I tried, from 4.1.5 to 5.3.2.
- I was unable to test this on versions lower than 4.1 because recursive conditional types was introduced here.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.2#code/C4TwDgpgBAggTnAPAOShAHsCA7AJgZymwFcBbAIwjgBooAVNTHAqAQ2xAG0BdKAXig8AfP3qcA5ABscAc2AALcbwxY8hVAH56UAFywEKWpwB0purXYhuQgFChIUAJLYAxikaqWJClRECTpvBIyEIWHNwS0thyitw2duDQAEoQAI7EAJZwEMhklMEezITe+X5QwHDEEPH20HQQ+MDuKkVEeb6iKelZOe1Izm4htkA

### 💻 Code

```ts
type Arr<N extends number, T extends any[] = []> = T['length'] extends N ? T : Arr<N, [...T, any]>
type Inc<N extends number> = [...Arr<N>, any]['length']

type RequireNumber<N extends number> = true

type Test<N extends number> = RequireNumber<Inc<N>>
```

### 🙁 Actual behavior

Under `Inc<N>`, we can see this error:

`Type 'Inc<N>' does not satisfy the constraint 'number'. (2344)`

### 🙂 Expected behavior

No error, since `Inc<N>` is a number (it is a `.length` of an array)

**Comment by RyanCavanaugh** [comment]
We basically only have one of two options when dealing with a lookup type:
 * `Inc` produces a deferred lookup type that will resolve upon instantiation
 * `Inc` produces a concrete type (`number`) that can satisfy a constraint

> No error, since Inc<N> is a number (it is a .length of an array)

*If* this is true (TS basically can't prove that it is), then WLOG you can write

```ts
type Inc<N extends number> = number & [...Arr<N>, any]['length']
```

**Comment by ledenis** [comment]
Ok, thanks for the explanation and the `number &` workaround. That works for me 🙂
