### ISSUE TITLE
Inconsistent tripple-slash directive in sub-directory

### ISSUE THREAD

**Issue by icholy** [microsoft/TypeScript#56930]
### 🔎 Search Terms

tripple-slash directives references

### 🕗 Version & Regression Information

v4.x did not emit these directives at all.

### ⏯ Playground Link

https://github.com/icholy/tsc-tripple-slash-bug

### 💻 Code

* `src/types/fs.ts`
```ts
declare module 'fs' {}
```

* `src/a/x.ts`
``` ts
import * as fs from 'fs';

export { fs };
```

* `src/a/b/x.ts`
``` ts
import * as fs from 'fs';

export { fs };
```

### 🙁 Actual behavior

Emitted files:

* `lib/a/x.d.ts`
``` js
/// <reference path="../types/fs.d.ts" />
/// <reference types="node/fs" />
import * as fs from 'fs';
export { fs };
```

* `lib/a/b/x.d.ts` (using `types` instead of `path`).

``` js
/// <reference types="lib/types/fs" />
/// <reference types="node/fs" />
import * as fs from 'fs';
export { fs };
```

### 🙂 Expected behavior

Emitted files:

* `lib/a/x.d.ts`
``` js
/// <reference path="../types/fs.d.ts" />
/// <reference types="node/fs" />
import * as fs from 'fs';
export { fs };
```

* `lib/a/b/x.d.ts`

``` js
/// <reference types="../../types/fs" />
/// <reference types="node/fs" />
import * as fs from 'fs';
export { fs };
```

### Additional information about the issue

This seems to be related to module resolution.

**Comment by fatcerberus** [comment]
Looks like the same issue as https://github.com/microsoft/TypeScript/issues/56571

**Comment by icholy** [comment]
@fatcerberus that does look like the same issue. But I'm not clear on why `lib/a/x/d.ts` outputs a `path="..."` while `lib/a/b/x.d.ts` outputs a `types="..."` directive?

**Comment by icholy** [comment]
@RyanCavanaugh do you have any insight about why the two files contain different variations of the directive?
