### ISSUE TITLE
The Keyof Type Operator shows inconsistent behavior.

### ISSUE THREAD

**Issue by 13OnTheCode** [microsoft/TypeScript#56938]
### 🔎 Search Terms

The Keyof Type Operator shows inconsistent behavior.

### 🕗 Version & Regression Information

-

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgjFAvFA3lA2gDwFxQM7ABOAlgHYDmAurgK6kDWpA9gO6lQC+AsAFAD0fKEIB6Afl69QkKACUEyehBBMAZrDi8BQqGIk8p0GACYksiAGMmhACYAeAiQoAaKHUatSAPk2CR4npLg0DImCkqqsEY+2ro8QA

### 💻 Code

```ts
type T1 = { [x: string]: unknown }
//   ^? type T1 = { [x: string]: unknown; }

type R1 = keyof T1
//   ^? type R1 = string | number

type T2 = Record<string, unknown>
//   ^? type T2 = { [x: string]: unknown; }

type R2 = keyof T2
//   ^? type R2 = string
```

### 🙁 Actual behavior

According to the type hint, the types of `T1` and `T2` are the same, but the results they get through `keyof` are not the same. According to the document, they should both get `string | number` .

Document link: [https://www.typescriptlang.org/docs/handbook/2/keyof-types.html#handbook-content](https://www.typescriptlang.org/docs/handbook/2/keyof-types.html#handbook-content)

### 🙂 Expected behavior

Infer the correct type.

### Additional information about the issue

In addition, it may also be related to [https://github.com/microsoft/TypeScript/issues/56888](https://github.com/microsoft/TypeScript/issues/56888).

**Comment by MartinJohns** [comment]
This is working as intended, see also #55706.

`Record<>` is implemented as a mapped type, it behaves different than an indexed type.

**Comment by fatcerberus** [comment]
Yeah, it's confusing that `Record<string, T>` is displayed as an index-signature type in type hints.  It's actually a mapped type over `string`, which, while they behave similarly most of the time, is not the same thing as a `string` index signature.
