### ISSUE TITLE
Bundler module resolution fails to resolve colocated declaration file

### ISSUE THREAD

**Issue by Methuselah96** [microsoft/TypeScript#56933]
### 🔎 Search Terms

moduleresolution
bundler
directory
package.json 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "moduleResolution"

### ⏯ Playground Link

https://github.com/Methuselah96/test-ts-module-resolution

### 💻 Code

`./app/test.ts`

```ts
import { test } from '../lib';

test();
```

`./lib/package.json`

```json
{
  "main": "./cjs/index.js",
  "module": "./esm/index.js"
}
```

`./lib/cjs/index.js`

```js
export function test() {}
```
`./lib/cjs/index.d.ts`

```ts
export function test(): void;
```

`./lib/esm/index.js`

```js
export function test() {}
```
`./lib/esm/index.d.ts`

```ts
export function test(): void;
```

### 🙁 Actual behavior

```
app/test.ts:1:22 - error TS7016: Could not find a declaration file for module '../lib'. 'C:/Users/nbier/Documents/test-ts-module-resolution/lib/cjs/index.js' implicitly has an 'any' type.

1 import { test } from '../lib';
                       ~~~~~~~~


Found 1 error in app/test.ts:1
```

### 🙂 Expected behavior

Types should work.

### Additional information about the issue

`react-icons` use a directory structure like this. I encountered this issue while trying to switch to `"moduleResolution": "bundler"` with a dependency on `react-icons`.

**Comment by robpalme** [comment]
The error goes away if you update `lib/package.json` from `"main": "./cjs/index.js"` to the extensionless `"main": "./cjs/index"`.

I don't think that should be necessary for automatic sibling DTS lookup to work, so it does seem like a bug.

**Comment by andrewbranch** [comment]
Looks like this affects `--moduleResolution nodenext` CJS resolution too.
