### ISSUE TITLE
Iteration Plan for 5.4 release?

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#56945]
Is there no iteration plan for the next typescript?
And also, is there a way to suggest wich features should be worked on?
And additionally, could also the roadmap be refreshed?

If it is possible to suggest features, I'd like to suggest:
#42048 and #3841 (#32452 nearly the same)

**Comment by MartinJohns** [comment]
> And also, is there a way to suggest wich features should be worked on?

Yes, by giving the issues thumbs up.

**Comment by jogibear9988** [comment]
https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc then #3841  is already on second page :-)
#42048 has a long way to go

**Comment by MartinJohns** [comment]
Thumbs up are not the only deciding factor, of course. But that's the way you can express your favor. Anything else would just result in a lot of unnecessary spam and distraction.

And in some cases like #3841 it's simply not viable due to mentioned problems: https://github.com/microsoft/TypeScript/issues/3841#issuecomment-163350868

**Comment by jogibear9988** [comment]
> Thumbs up are not the only deciding factor, of course. But that's the way you can express your favor. Anything else would just result in a lot of unnecessary spam and distraction.
> 
> And in some cases like #3841 it's simply not viable due to mentioned problems: [#3841 (comment)](https://github.com/microsoft/TypeScript/issues/3841#issuecomment-163350868)

yeah, but the properties defined on the constructor, means the static objects of the class should/could be inherited somehow... like in the workaround described here: https://github.com/microsoft/TypeScript/issues/32452#issue-469403238

**Comment by RyanCavanaugh** [comment]
5.4 plan will be out shortly

**Comment by MartinJohns** [comment]
#56948
