### ISSUE TITLE
Constants can be reassigned

### ISSUE THREAD

**Issue by tomatodev** [microsoft/TypeScript#56958]
### 🔎 Search Terms

This issue can be reproduced in typescript playground -->  [Playground](http://www.typescriptlang.org/play/?ts=Nightly).

### 🕗 Version & Regression Information

latest [Playground](http://www.typescriptlang.org/play/?ts=Nightly).

### 💻 Code

const  a = 'abc';
function test2(value:number): number{
    if(value) return value
    return 1111
}
if (typeof test2 === 'function') {
    (a as unknown as number) = test2(2)
}
console.log(a)

### 🙁 Actual behavior

I defined a constant a, but I reassigned it to a new value in later code without any errors，but I got an error after running it.
![ts-error](https://github.com/microsoft/TypeScript/assets/155722734/32269a0a-49a6-46ef-be3c-8d037aa82c65)

### 🙂 Expected behavior

When I modify constant a, I expect an error prompt

**Comment by MartinJohns** [comment]
You're explicitly telling the compiler to ignore the error you'd otherwise get using the type assertion.

It's when you tell the compiler to treat a `number` as a `string`, then complain when you get a runtime error about missing `string` methods.

**Comment by tomatodev** [comment]
Why is there no error notification when I modify constants.
Error prompt for the following example
![Uploading image.png…]()

**Comment by MartinJohns** [comment]
I mentioned it in my comment. Because you turn off the check by using a type assertion. Type assertions are a way to tell the compiler "shh, I know what I'm doing, trust me."
