### ISSUE TITLE
Function intersection does not always resolve to last signature

### ISSUE THREAD

**Issue by rotu** [microsoft/TypeScript#56951]
### 🔎 Search Terms

function intersection overloads

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about overloads

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99&jsx=0&ts=5.4.0-dev.20240104#code/PTAEBcAsFMITwA6wPYDNQEMB2oCWXxoAnAZ2gGNCATUVAVy0t2R1xL3HYBsMTxQAVA1wBHOtAGgqFHkWg0SuAOZYM4OnICwAKHCJYAJVABeUAejqiWACr6APAAoHASmMA+LHQC2AI2LPQADJQJ1c3PiJ8JQDg0PdPX383UBA8dgiogBpQaAAPJEpQBL8iHVTQUAA9AH4dMrAoNlBIDAQkLHZcdChYcgwuLlBFFTUNWCb8CBg8AmIyJhZM+sFoADdoVlRJHvgkNKLkfn65DCo4Ganx2dIKcGYsHT09gDETUABvFwAuYuJs3K+AEYAL5BD7fDJYJTZOBA0HBT7OH7eErZABecMe+jMACY3uZLDZ7M9kqkmpDoTl8rciijiMsKjU6tpUj46PxGuxhGINtASOwvBhztJ2jQWKAAO4wHpEXawVYYSIYHxcPmYOQzPjYO5qeSgZCyrCHLEvADidgAgpkAEKZADCyVMBI0RKQjhc7gtMRCHrc1u9cTcducbgZVVqumxBgAzG9nubfkRMhTMonSWAmonsnkCvxE2Gmdpljsnih0Nh9esiFxkKc9fRGHdxRNOKAeHwpDJFXrhqpLNBsnIlIqqKr+fr0NzxFg+SQdNJyLJYA2FjhUN989oF0vaAxV7QIeBIlD512NSum2uN3TSpG9tZ8RYXbY3aW0LR0-ss1Tc7TErfynDIA

### 💻 Code

```ts
// the type of an intersected function is its last *unique* declared signature
type R = ReturnType<(()=>number) & (()=>string) & (()=>number)> // is string, expect number
//   ^?

// this happens if the call signature is in the intersection,
// *even if* the type is not already in the intersection
type F = {():number, x:1} & {():string, y:1} & {():number, z:1}
type R2 = ReturnType<F> // is string, expect number
//   ^?

// but this uniqueness may depend on whether type variables are instantiated or not
type FG<A,B,C> = ReturnType<(()=>A) & (()=>B) & (()=>C)>
//   ^?
type R3 = FG<number,string,number> // is number, expect number
//   ^?

// the type of an overloaded function is its last declared signature, regardless of uniqueness
declare function f():number
declare function f():string
declare function f():number
type T = ReturnType<typeof f> // is number, expect number
//   ^?
```

### 🙁 Actual behavior

When intersecting function types, a call signature is ignored if it is already in the intersection. This means that `ReturnType<(()=>number) & (()=>string) & (()=>number)>` is resolved as `string`.

### 🙂 Expected behavior

It is expected that `ReturnType<(()=>number) & (()=>string) & (()=>number)>` is `number`, the return type of the last intersected element. This is because function intersection is semantically supposed to be treated as overload resolution, which takes the last declaration regardless of repetition.

**Comment by MartinJohns** [comment]
The type `(()=>number) & (()=>string) & (()=>number)` is an elaborate way to write the type `(()=>number) & (()=>string)`. It's the same as `string & string` is just `string`.

**Comment by fatcerberus** [comment]
> ```ts
> type R = ReturnType<(()=>number) & (()=>string) & (()=>number)> // is string, expect number
> ```

The problem with this case is not actually with `ReturnType` and isn't even unique to functions - this is an expected side effect of intersection simplification.  For example `Foo & Bar & Foo` simplifies to `Foo & Bar`: [TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvKAzBAuKBnYAJwEsA7AcygF8BuAKFEigCEBDQ5NKAI3dwJIVq9RtACKAVwAeneIgBkLdlEVz6AenVRtAPQD8dIA)

As far as `ReturnType` is concerned, the last overload *is* `() => string`.

On the other hand...

```ts
type F = {():number, x:1} & {():string, y:1} & {():number, z:1}
type R2 = ReturnType<F> // is string, expect number
```

*This one* is a bit surprising, since the last member shouldn't be simplified away.

**Comment by rotu** [comment]
> > ```ts
> > type R = ReturnType<(()=>number) & (()=>string) & (()=>number)> // is string, expect number
> > ```
> 
> The problem with this case is not actually with `ReturnType` and isn't even unique to functions - this is an expected side effect of intersection simplification.

I tried to word that clearly. `ReturnType` is the easiest way to get at this (even though this is a pretty contrived example; a function that is overloaded only on its return type!). If you *omit* `ReturnType`, there is no visible bug, since the intersection is left unsimplified.
```ts
type F = (()=>number) & (()=>string) & (()=>number)
//   ^? type F = (() => number) & (() => string) & (() => number))
```

Because intersection *can be* sensitive to order, it changes the meaning of the program, so it's not a benign simplification. When the operands are *not* callable, the intersection simplification is valid since (as far as I know) the order of an intersection does not affect the type in any discernable way. But the expectation for callables is that the order *does* matter - so it's a bug in this context.

I did notice some other things like:

- the argument name doesn't matter
- argument types *do* matter
- the intersection does not simplify if one function type is a strict subtype of the other

[playground](https://www.typescriptlang.org/play?#code/PTAEBMEsDNoUwE6kgO1AQwQcwK4Fs4UAXUIgTwAc4Aocq0AMQEFsAVAXlACU4icEUrSnAA8ACjEAPAFwBGAJTsAfCnwAjRPNAAyUBMVKAzkQSosW3RJkAmA6rwaE8paBCh7j6m9CgAegH4vMChYRGQ0TFwCYnd0AlphRhYsADlQTh4+ASEqcSk5O3VNHT0xA2NTFHMSiTIC5Q9NFzcKsyCfP0C3aEgEY1BoHBQAYyJIAHs0SEMMUEMcNTo4UHHoUgALXvBSYQT6BgBlBfTuXn5BYTyZNXHxgBs4dBQDMRMcOHkLUvKTMy+raRvD7KMQ3e6PZ7OVxgMEPJ7tHwBdo9PokQYjMaTZAzdBzHBUBBLFZrIibBDbJZ7ZaHfEnTLnHKiAFAl6wiGfGplZStKr-fJsp4vFlQtxAhGdahAA)

> *This one* is a bit surprising, since the last member shouldn't be simplified away.

I think this is a bug *inside* `ReturnType` namely how `infer` distributes over intersection.

**Comment by RyanCavanaugh** [comment]
The *intended* thing for users to do is:
 * Write their overloads
 * Have a "catch-all" overload, last, that represents the behavior of the function when overload resolution is ambiguous, whose return type should be the union of all other signatures' return types

Unless people follow this rule, `ReturnType` can't do its job in a number of ways, including this one. Certainly for something like this that has zero runtime analog whatsoever, there's nothing meaningful for the type system to say about it.

**Comment by rotu** [comment]
> The _intended_ thing for users to do is:
> ...
> 
> Unless people follow this rule, `ReturnType` can't do its job in a number of ways, including this one. Certainly for something like this that has zero runtime analog whatsoever, there's nothing meaningful for the type system to say about it.

That sounds very much like a precondition. If certain input gives erroneous output, then TypeScript ought to report that instead of returning misleading output!

Barring that, there are 4 meaningful possible type judgements here:
1. treat it as an intersection of covariant types - return the intersection of all return types.
2. consider it as "the return value is conditional on the input" - return the union of all return types. If the user obeys the above "rule", this is the expected output anyway.
3. treat it the same as a function overload where the syntactically last declaration's return type is returned
4. treat it as the *first* declaration's return type. This is what you get if you use `infer` today to extract a covariant type parameter of a generic intersection type.

None of these are what happens. Hence a bug.
