### ISSUE TITLE
Add // @ts-ignore to typescript.d.ts AssertClause and AssertEntry entries for API backwards compatibility?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript#56954]
### 🔍 Search Terms

api breaking change interface merge assert clause entry import attribute attributes

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The `AssertClause` and `AssertEntry` interfaces in TypeScript 5.3.3 clash with their declarations in typescript-eslint - even after #56485. We don't see a way to resolve this for users. For the sake of backwards compatibility, could the types be given `// @ts-ignore`s so that folks don't have to `skipLibCheck`?

```diff
    /** @deprecated */
+   // @ts-ignore
    interface AssertEntry extends ImportAttribute {
    }
    /** @deprecated */
+   // @ts-ignore
    interface AssertClause extends ImportAttributes {
    }
```

...and in general, whenever a type is `@deprecated`, could it be given a `// @ts-ignore`?

### 📃 Motivating Example

We haven't been able to figure out a way to fix this for users of typescript-eslint who want to keep `skipLibCheck` disabled.

I realize how gross it is to suggest `// @ts-ignore` inside TypeScript's types, but short of moving the types to DefinitelyTyped or `patch-package`, I'm out of ideas...

### 💻 Use Cases

typescript-eslint uses [interface merging to ensure types for newly-added nodes are present regardless of TypeScript version](https://github.com/typescript-eslint/typescript-eslint/blob/53f4c37dc089e74da590c932b17d26d76204c27c/packages/typescript-estree/src/ts-estree/ts-nodes.ts#L3-L10):

```ts
// Workaround to support new TS version features for consumers on old TS versions
// Eg: https://github.com/typescript-eslint/typescript-eslint/issues/2388, https://github.com/typescript-eslint/typescript-eslint/issues/2784
declare module 'typescript' {
  /** @ts-ignore - added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
  export interface AssertClause extends ts.Node {}
  /** @ts-ignore - added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
  export interface AssertEntry extends ts.Node {}
```

Paraphrasing @bradzacher's https://github.com/typescript-eslint/typescript-eslint/issues/8047#issuecomment-1876138010: 

* TypeScript 4.5 - 5.2 declared `AssertClause` and `AssertEntry` with standard interfaces (`interface AssertEntry extends Node { ... }`)
* TypeScript 5.3 changed them to `type` aliases (`type AssertEntry = ImportAttribute`), which broke interface merging in typescript-eslint
* https://github.com/microsoft/TypeScript/pull/56485 -> TypeScript 5.3.3 changed them to interfaces (`interface AssertEntry extends ImportAttribute { ... }`)

...but the 5.3.3 change didn't fix type checking on `typescript.d.ts` complaints for users. https://github.com/typescript-eslint/typescript-eslint/issues/8047 shows project links & reports from users reporting they need to enable `skipLibCheck`:

```ts
node_modules/typescript/lib/typescript.d.ts:6021:15 - error TS2320: Interface 'AssertEntry' cannot simultaneously extend types 'ImportAttribute' and 'Node'.
  Named property 'kind' of types 'ImportAttribute' and 'Node' are not identical.

6021     interface AssertEntry extends ImportAttribute {
                   ~~~~~~~~~~~
```

**Comment by jakebailey** [comment]
Can we just duplicate the declaration and deprecate one of them? Since they have the same structure and kind, they would be assignable to each other.

**Comment by bradzacher** [comment]
We preserve it in the dts by making it a block comment 😅

I'm more than happy if you guys wanna duplicate it and yeah it sucks that we need to keep this hack around.

Sadly though we'll be stuck with a hack until you guys remove it. We won't be able to remove ours until we bump our dep min past 5.3

**Comment by jakebailey** [comment]
If you get a chance, can you try the package built on https://github.com/microsoft/TypeScript/pull/56967 to see if that "fixes" the problem?

**Comment by JoshuaKGoldberg** [comment]
👍 that fixes it! https://github.com/JoshuaKGoldberg/repros/tree/ts-eslint-tsc-assert-entry-clause-clash has a repro.

**Comment by jakebailey** [comment]
@JoshuaKGoldberg We realized in the design meeting that there is likely a much simpler fix; in your declarations, can you just specify the `kind` prop? For example:

```ts
  /** added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
  export interface AssertClause extends ts.Node {
    kind: ts.SyntaxKind.AssertClause;
  }
  /** added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
  export interface AssertEntry extends ts.Node {
    kind: ts.SyntaxKind.AssertEntry;
  }
```

**Comment by jakebailey** [comment]
Hm, it seems like it doesn't work alone in your repro repo. I get fewer errors:

```

node_modules/typescript/lib/typescript.d.ts:6021:15 - error TS2320: Interface 'AssertEntry' cannot simultaneously extend types 'ImportAttribute' and 'Node'.
  Named property 'parent' of types 'ImportAttribute' and 'Node' are not identical.

6021     interface AssertEntry extends ImportAttribute {
                   ~~~~~~~~~~~

node_modules/typescript/lib/typescript.d.ts:6024:15 - error TS2320: Interface 'AssertClause' cannot simultaneously extend types 'ImportAttributes' and 'Node'.
  Named property 'parent' of types 'ImportAttributes' and 'Node' are not identical.

6024     interface AssertClause extends ImportAttributes {
                   ~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/typescript/lib/typescript.d.ts:6021
```

However, having them do this does work:

```ts
    /** added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
    interface AssertClause extends ts.ImportAttributes {
    }
    /** added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
    interface AssertEntry extends ts.ImportAttribute {
    }
```

Or even:

```ts
    /** added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
    interface AssertClause extends ImportAttributes {
    }
    /** added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
    interface AssertEntry extends ImportAttribute {
    }
```

This would allow TS to not have to change anything.

**Comment by jakebailey** [comment]
I just tested the above two examples forcing TS 5.2, and they both compiled (well, almost; they complain about `ts.JSDocParsingMode`).

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/8181

I tried this on 5.2 and it errored. 
Essentially I tested this by installing both in a test repo and then manually modifying the `.d.ts` files with the fix.

I'll check again in a bit - maybe I did something wrong in my test.

**Comment by bradzacher** [comment]
So as a base install with no changes:
```
$ yarn list @typescript-eslint/typescript-estree typescript
├─ @typescript-eslint/typescript-estree@6.18.2-alpha.5
└─ typescript@5.2.2
✨  Done in 0.06s.

$ yarn tsc
✨  Done in 1.15s.
```

```
$ yarn list @typescript-eslint/typescript-estree typescript
├─ @typescript-eslint/typescript-estree@6.18.2-alpha.5
└─ typescript@5.3.3
✨  Done in 0.06s.

$ yarn tsc
node_modules/typescript/lib/typescript.d.ts:6021:15 - error TS2320: Interface 'AssertEntry' cannot simultaneously extend types 'ImportAttribute' and 'Node'.
  Named property 'kind' of types 'ImportAttribute' and 'Node' are not identical.

6021     interface AssertEntry extends ImportAttribute {
                   ~~~~~~~~~~~

node_modules/typescript/lib/typescript.d.ts:6021:15 - error TS2320: Interface 'AssertEntry' cannot simultaneously extend types 'ImportAttribute' and 'Node'.
  Named property 'parent' of types 'ImportAttribute' and 'Node' are not identical.

6021     interface AssertEntry extends ImportAttribute {
                   ~~~~~~~~~~~

node_modules/typescript/lib/typescript.d.ts:6024:15 - error TS2320: Interface 'AssertClause' cannot simultaneously extend types 'ImportAttributes' and 'Node'.
  Named property 'kind' of types 'ImportAttributes' and 'Node' are not identical.

6024     interface AssertClause extends ImportAttributes {
                   ~~~~~~~~~~~~

node_modules/typescript/lib/typescript.d.ts:6024:15 - error TS2320: Interface 'AssertClause' cannot simultaneously extend types 'ImportAttributes' and 'Node'.
  Named property 'parent' of types 'ImportAttributes' and 'Node' are not identical.

6024     interface AssertClause extends ImportAttributes {
                   ~~~~~~~~~~~~


Found 4 errors in the same file, starting at: node_modules/typescript/lib/typescript.d.ts:6021
```

Then if I manually patch `node_modules/@typescript-eslint/typescript-estree/dist/ts-estree/ts-nodes.d.ts`
```ts
    /** added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
    interface AssertClause extends ts.ImportAttributes {
    }
    /** added in TS 4.5, deprecated and converted to a type-alias in TS 5.3 */
    interface AssertEntry extends ts.ImportAttribute {
    }
```

```
$ yarn list @typescript-eslint/typescript-estree typescript
├─ @typescript-eslint/typescript-estree@6.18.2-alpha.5 (PATCHED)
└─ typescript@4.5.5
✨  Done in 0.06s.

$ yarn tsc                                                 
✨  Done in 1.26s.
```

```
$ yarn list @typescript-eslint/typescript-estree typescript
├─ @typescript-eslint/typescript-estree@6.18.2-alpha.5 (PATCHED)
└─ typescript@5.2.2
✨  Done in 0.06s.

$ yarn tsc                                                 
✨  Done in 1.26s.
```

```
$ yarn list @typescript-eslint/typescript-estree typescript
├─ @typescript-eslint/typescript-estree@6.18.2-alpha.5 (PATCHED)
└─ typescript@5.3.3
✨  Done in 0.06s.

$ yarn tsc                                                 
✨  Done in 1.26s.
```

I'm so confused right now - I tested the above fix several times and it broke on TS5.2 with an error because it said that the interfaces had a different parent - that's why I ended up closing the PR and leaving that comment.

Well I guess I'll reopen and land that PR then 🤷

**Comment by jakebailey** [comment]
Well, I'm glad it works, anyway! That other linked PR didn't seem to allude to what broke, unless I misread something...

**Comment by jakebailey** [comment]
`6.18.2-alpha.6` is working, so I'm going to close this.
