### ISSUE TITLE
Subclass declared default overwriting constructor assignments using parent method

### ISSUE THREAD

**Issue by freakypie** [microsoft/TypeScript#56950]
### 🔎 Search Terms

subclass default initial value replaced overwrote overwritten

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because _I'm not very smart, i just found this bug_

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAECC0G8BQ1XTNAvNAjAbjWiRTWAHsA7CAFwCcBXYas2gCjFoHMIBKREwqmoALAJYQAdPQAOAEzDUApuy688A6AF9ihGfKWtptMtN79BaAGYtorclWrQA1ooCe0URWhGTZ5BYsRcQBtF1cAXSxvY1NQt3D1AMF7CDIQRQkQMk5WMIAaaCCIOIieRIDtQm1tJFBIGAAhaEUADyUKWRh4fzQAIyiAJnUNFLpGZjYObj4eiwgZRUnVMo1CAHo1wrFJPQVlKbUNauJR6H7sCkUAd2gG1gQzgC5oAGYC4GeXrRXaylT0zLZVgAciUNBwwIKvQk50w2BeKxSaQyWRyoMUNAGkLOEmAWDhrxWQA

### 💻 Code

```ts
import { assert, describe, it } from "vitest";

describe("typescript classes", () => {
  it.only("should overwrite default values", () => {
    class A {
      b = 1;
      c = 1;

      constructor(args) {
        this.update(args);
      }

      update(props) {
        for (const key in props) {
          this[key] = props[key];
        }
      }
    }

    class B extends A {
      b = 2;
      c = 2;

      constructor(args) {
        super(args);
        // this.update(args);
      }
    }

    const b = new B({ b: 3, c: 3 });
    assert.equal(b.b, 3);
    assert.equal(b.c, 3);
  });
});

```

### 🙁 Actual behavior

in my version (5.3.3), both are 2

### 🙂 Expected behavior

i would expect the properties `b` and `c` to be 3

### Additional information about the issue

I'm just a fool who got bit by this, maybe i'm just doing something wrong

**Comment by RyanCavanaugh** [comment]
You can run this code in your browser console and see that `b.b` and `b.c` are both 2. This is JavaScript behavior; nothing to do with TypeScript here.

**Comment by freakypie** [comment]
You are indeed correct, thank you for pointing it out to me
