### ISSUE TITLE
method with boolean signature not guaranteed to return boolean

### ISSUE THREAD

**Issue by fernandezpablo85** [Microsoft/TypeScript#5696]
```typescript
function defined(str: string): boolean {
	return str && str.length > 0;
}

console.assert(defined("foobar") === true);
console.assert(defined("") === false);
```

The last assert will fail because `defined("")` returns the empty string, not `false`.

**Comment by kitsonk** [comment]
It is actually up to the implementation to ensure it is returning something that is compatible with the return type.  TypeScript is type guarding you, not performing magic for you.  Runtime type coercion in JavaScript is silly, therefore you should be explicit:

```typescript
function defined(str: string): boolean {
    return Boolean(str && str.length > 0);
}
```

**Comment by fernandezpablo85** [comment]
> It is actually up to the implementation to ensure it is returning something that is compatible with the return type

If I try to do the following, typescript correctly alerts that the return type is not compatible:

```typescript
function defined(str: string): boolean {
	return "";
}
```

I don't expect typescript to do magic for me but I do expect it to complain if theres a type mismatch.

**Comment by fernandezpablo85** [comment]
I don't expect typescript to perform magic for me, but I do expect it to tell me if there's a type mismatch. In this case there is. It shouldn't allow that in the same way it doesn't allow this:

```typescript
function defined(str: string): boolean {
  return "";
}
```

In this case the return type enforcement is not "up to the implementation", it's correctly marked as a compile time error instead.

**Comment by RyanCavanaugh** [comment]
Relevant reading: http://stackoverflow.com/questions/12693787/why-does-the-operator-produce-the-type-of-the-second-operand

The failure mode of the logic we used here is when a falsy left operand to `&&` is actually a falsy primitive rather than `undefined` or `null`. Perhaps the type of `string && T` or `number && T` should actually be `string|T`/`number|T` rather than `T`.

**Comment by kitsonk** [comment]
@RyanCavanaugh was you say makes sense because:

```typescript
let a = "" || false; // type is string | boolean
let b = "" && false; // type is boolean
```

Though the potential result for `b` is actually a union type at runtime.

**Comment by DanielRosenwasser** [comment]
If we expanded literal typing to booleans and numbers, these issues could be accurately expressed.

```ts
var s: string;
var x = s && 10;
```

In this example the type of `x` could be `"" | number`. Keep in mind this is me rambling before I head to sleep, but it might be worth exploring.
