### ISSUE TITLE
ts(2367) error when using typeof : This comparison appears to be unintentional error

### ISSUE THREAD

**Issue by robertlario** [microsoft/TypeScript#56966]
### 🔎 Search Terms

"ts2367", "This comparison appears to be unintentional because the types"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ts2367

### 💻 Code

```ts
            let x : string | File;

            if (typeof x === File)
            {
                console.log('this is a file');
            } else {
                console.log('this is not a file');
            }
```

### 🙁 Actual behavior

string, options?: FilePropertyBag): File; prototype: File; }' have no overlap.ts(2367)

### 🙂 Expected behavior

if x is of type 'File'
'this is a file' would be printed to the console log
else
'this is not a file' would be printed to the console log

**Comment by fatcerberus** [comment]
That's... not how `typeof` works in JS.  I think you're looking for [`instanceof`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) instead.

**Comment by RyanCavanaugh** [comment]
This comparison does, indeed, appear to be unintentional.

**Comment by RyanCavanaugh** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof
