### ISSUE TITLE
Types inlined (duplicated) in declarations in the generated declaration file

### ISSUE THREAD

**Issue by bugron** [microsoft/TypeScript#56969]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Hi there,
I'm working on a component library and there is a type generation behavior I don't quite understand.

Here is [an example](https://typescriptlang.org/play?noImplicitAny=false&jsx=4&verbatimModuleSyntax=false#code/JYWwDg9gTgLgBAbzgYQuCA7AphmAFKCMAZwHVgYALCAVxgCUsAzAGjiegHcBDKAE0ZM4AX3aEQcAERQs3AMYxJAbgBQKrAA9IsODACeYLHABCdGJgJFicALwo0kbLkslyVWg2YAeSQCMzmJIAfHAAZIgqcHDcYIa83BhyWAD8AFyRUXAAPlJgUKC8epIZUTmSxFhymHyFxZnZUgDm1MSKJQ2SNRiNWFB1mWVdPVAAtBVVGDVQRapRxMAAXimpUsQg3AA2G5IdIFh8wDQgO2UbvD3KGRsQ3AfdaXC+EBAbshgNGEe+varCqupaaDwCatEwBd52DhQHj8QReAASABUALIAGVMMHMGAAoq89rg2BisS5iEEABQZMlIOSUYAbPgyd7CNgyJgASlsIQQ7RkMBoUHeFPqUS8-kxmHa9VZNgQrOEkrgQQVUQQNLpDJw8uFcC8AHoxVilfU2bMRCoTWogA). Notice that `ButtonProps` in the `.D.TS` tab is inlined (duplicated) in the Button declaration.

I have another component that uses a type union in its prop types and I don't see the prop types being inlined in the component declaration there. So I tried [this](https://typescriptlang.org/play?noImplicitAny=false&jsx=4&verbatimModuleSyntax=false#code/JYWwDg9gTgLgBAbzgYQuCA7AphmAFKCMAZwHVgYALCAVxgCUsAzAGjiegHcBDKAE0ZM4AX3aEQcAERQs3AMYxJAbgBQKmAE8wWOAEkM2KACE6MTASLE4AXkQq4cbmG29uGOVgD8ALnsO4AD5SYFCgvBqSfg5BksRYcph84ZH+gVIA5tTEilFpkkkY6VhQKf4xBUVQALRxCRhJUBGqDsTAAF5e3lLEINwANn2SeSBYfMA0IEMxfbxFyn59ENxjhT5wAEYQEH2yGGkYE+vFqsKqKlgAHpCwcJracCYwZhgWJDYoaJDYuK9kFNR0QQAHkk61MmEkAD44AAyOAACn0hkez1+aSRxRR5kIJAAlGdLtd4HVsg9wXtbBwoDx+MCABIAFQAsgAZLEYACiOxGuDY7N+kPhfnhSDklGAfT4Mj2wjYMiYuJs0IQuRkMBoUD2QtSDiBYKemFyqXl1gQ8uERrgkMtDgQYolUpwFp1cCBAHp9c9ral8X4Lb6VEA) - no type inlining 🤷‍♂️

Also [using an interface](https://typescriptlang.org/play?noImplicitAny=false&jsx=4&verbatimModuleSyntax=false#code/JYWwDg9gTgLgBAbzgYQuCA7AphmAFKCMAZwHVgYALCAVxgCUsAzAGjiegHcBDKAE0ZM4AX3aEQcAERQs3AMYxJAbgBQKrAA9IsOMFxYoTeVjgAhOjEwEixOJpg4+t1Omy5rJclVoNmAHkkAIwtMSQA+RBU4OG4wMFkobgw5LAB+AC4o6LgAHykwKFBeAE9JLOi8yWIsOUw+ErLs3KkAc2piRXLmyXqMFoNG7Mre-qgAWmrajHqoUtVo4mAALzT0qWIQbgAbLclukCw+YBoQPcqt3n7lLK2IbiO+jLhAiAgt2QxmjBPAg1VhVTqLTQeBTDpmEKfAC87C4vAE-gAEgAVACyABlzDBLBgAKLvA64NhYnEeYhhAAUWQpSDklGAWz4Mk+wjYMiYAEo4FCIggujIYDQoJ8qU1on5gtjMF0muyoQh2cIZXAwsrogg6QymTglWK4H4APSSnGqpoc+YiFTmtRAA) here seems to fix this issue too.

Could you please help me understand why the type inlining happened in the first example and how to avoid it without the weird `T | T` or using an interface?

Thanks in advance for any help 🙏

**Comment by robpalme** [comment]
Duplication of types in emitted DTS files is a well-known [existing issue](https://github.com/microsoft/TypeScript/issues/37151).

For projects that opt-in, it will be solved by [Isolated Declarations.](https://github.com/microsoft/TypeScript/pull/53463)

**Comment by bugron** [comment]
Got it. Thanks @robpalme!
