### ISSUE TITLE
Union Type resolution breaks when importing an interface implementation

### ISSUE THREAD

**Issue by yroc92** [microsoft/TypeScript#56964]
### 🔎 Search Terms

"importing", "union type inference", "union type resolution"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 

### ⏯ Playground Link

https://stackblitz.com/edit/typescript-playground-xjsoqh?file=index.ts

### const.ts
```ts
import { TypeWithDynamicValue } from "./types";

export const dyanamicTypeImplementation: TypeWithDynamicValue = {
  foo: 'fizz',
  bar: false,
  value: 59
};
```
### types.ts
```ts
export type TypeWithDynamicValue = {
  foo: string;
  bar: boolean;
} & (
  | {
      value: string;
    }
  | {
      value: number;
    }
  | {
      value: boolean;
    }
);

export interface MyInterface<T> {
  foo: string;
  bar: boolean;
  valueWithStrictType: T;
} 
```
### function.ts
```ts
import { MyInterface, TypeWithDynamicValue } from "./types";

export function someFunction<T extends TypeWithDynamicValue>(param1: T): MyInterface<T['value']> {
  return {
    foo: param1.foo,
    bar: param1.bar,
    valueWithStrictType: param1.value
  }
}
```
### index.ts
```ts
import { dyanamicTypeImplementation } from "./const";
import { someFunction } from "./function";
import { TypeWithDynamicValue } from "./types";

const result = someFunction(dyanamicTypeImplementation);
type ResultTypeOfValueWithStrictTypeWhenImported = typeof result.valueWithStrictType  // string | number | boolean

const implementation2: TypeWithDynamicValue = {
  foo: 'fizz',
  bar: false,
  value: 60
};
const resultWithLocalVar = someFunction(implementation2);
type ResultTypeWhenNotImported = typeof resultWithLocalVar.valueWithStrictType; // number
```

### 🙁 Actual behavior

As seen in `index.ts`, Typescript is treating the resolved union type of `valueWithStrictType` differently depending on whether or not the object was instantiated locally or imported from a different file.

### 🙂 Expected behavior

Typescript should resolve the union type the way it does for a locally instantiated value for imported values.

**Comment by RyanCavanaugh** [comment]
Within the same file, you'll see the control-flow-analyzed type of a value, but outside the file it's always the declared type from the type annotation. You might want to write
```ts
export const dyanamicTypeImplementation = {
  foo: 'fizz',
  bar: false,
  value: 59
} satisfies TypeWithDynamicValue;
```
instead if you want the outer type to match the CFA type

**Comment by yroc92** [comment]
Thanks for your reply. This technically works, but my original goal was to avoid any special syntax for devs implementing objects of type `TypeWithDynamicValue` (generics included). 

Perhaps using `infer` with `TypeWithDynamicValue` could be useful in this context (I wasn't able to figure it out)? 

The TLDR is we want  `valueWithStrictType` to have a strict (non-union) type determined by the implementation of `TypeWithDynamicValue`, as passed into `someFunction`.

**Comment by RyanCavanaugh** [comment]
I'm not sure what makes `const x: T = e` differently special from `const x = e satisfies T`.

For a little context, the invariant here is that if you have
```ts
export const x: T = ...
```
in a `.ts` file, then the generated `.d.ts` will always say
```
export const x: T;
```
without info about the initializer, and we don't any behavioral differences between `.ts` and the corresponding `.d.ts` file (if practical)

**Comment by yroc92** [comment]
I see, so what you're saying is it is impossible to have the type resolved by an implementation without the control-flow-analyzer (i.e. in the same file)? 

Would this be a use case for `infer`? If not, we can probably close this since what I'm looking for is impossible without the use of a generic or `satisfies`.

**Comment by RyanCavanaugh** [comment]
`infer` isn't valid anywhere of use here

**Comment by yroc92** [comment]
Good to know thank you for the insight and explanation. Seems like `satisfies` is the solution here. Thank you!
