### ISSUE TITLE
type inference of nested type property

### ISSUE THREAD

**Issue by jaedeok0** [microsoft/TypeScript#56979]
### 🔎 Search Terms

"type inference",  "property deep inside"

### 🕗 Version & Regression Information

tested at `5.3.3`, `4.9.3`, `4.6.3`

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8AoKUA+UDeUwCcD2YAXJlKJMQEQCGFA3FAG5UA2ArhMVgBYCWxATFAC+w4cjQlcBTqXAcoFAEZ1GLdjK4RmzPMQCMokUNqJEAYzwA7AM7AoVBFAAUVYjACUCAHyZx1gO48wGZczlQAdFJg4WQQnhjiKGZU1tDUFISJKFA4EMCsOJb2kfjRTGwQ4bz0APQ1UAAqclAAkpYAZhC5lmbQ-ng4ANbhWcmpCsqZ2dm5+YXOnvA+EVHh5exVWjq19U2QrR1dED3Qlnh2-UMjKEKIxqYWNnaKjk6Kbos+CUlWtpKlongUEUJj8gWCoScq1i8VGKTSNCm0xyeQKRVW60q1SgdUazTanW6vSgl2GcPGSgyWRQszRC282FKazUWK2eB2eP2BKOJxJAzJNzuQA

### 💻 Code

```ts
type A =
  | { prop: { type: "a"; value: { hi: 2 } } }
  | { prop: { type: "b"; value: { hello: 1 } } };

const a = (a: A) => {
  switch (a.prop.type) {
    case "a":
      return a.prop.value.hi; // Type Inference work.
    case "b":
      return () => a.prop.value.hello; // Type Inference not work.
  }
};

const b = (b: A) => {
  const { prop } = b;

  switch (prop.type) {
    case "a":
      return prop.value.hi; // Type Inference work.
    case "b":
      return () => prop.value.hello; // Type Inference work.
  }
}
```

### 🙁 Actual behavior

When a property deep inside an object is entered in a conditional statement, type inference is not made.

<img width="610" alt="Screenshot 2024-01-08 at 3 52 34 PM" src="https://github.com/microsoft/TypeScript/assets/89368498/69e4e736-87de-402d-9ac7-86c2efe26591">

### 🙂 Expected behavior

type error not occur.

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/18758
