### ISSUE TITLE
Can not default import a commonjs module from an ES module with "module": "node16" in tsconfig.

### ISSUE THREAD

**Issue by xieyuheng** [microsoft/TypeScript#56971]
### 🔎 Search Terms

- "module": "node16"
- esModuleInterop
- default import with "module": "node16" 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, including 5.3.3 and nightly.

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=2&moduleResolution=99&module=100&ts=5.3.3&jsx=0&allowSyntheticDefaultImports=false#code/JYWwDg9gTgLgBAMyhAdjAsgQxjAplRZEOAIiVRgFoRs8oSBYAKGYGNUBneAbzlqmAAjAK54OAGjiCIAEwCecAL5wAvIQpYc+ABQkSASiA

### 💻 Code

```ts
import frontMatter from "front-matter"

const { attributes, body } = frontMatter("")
```

### 🙁 Actual behavior

This expression is not callable.
  Type 'typeof import("file:///node_modules/front-matter/index")' has no call signatures.

### 🙂 Expected behavior

No error, because the "front-matter" package has default export.

### Additional information about the issue

Place do not forget to set tsconfig to "module": "node16" in the playground.

Here is my tsconfig:

```
{
  "include": ["src"],
  "compilerOptions": {
    "lib": ["esnext", "dom"],
    "module": "nodenext",
    "target": "es6",
    "strict": true,
    "verbatimModuleSyntax": true,
    "declaration": true,
    "sourceMap": true,
    "declarationMap": true,
    "resolveJsonModule": true,
    "outDir": "lib"
  }
}
```

**Comment by fatcerberus** [comment]
https://arethetypeswrong.github.io/?p=front-matter%404.0.2

**Comment by xieyuheng** [comment]
@fatcerberus Thanks for this tool.
