### ISSUE TITLE
js callheirachy should should include name of initialized when called from a labda called from a member initializer

### ISSUE THREAD

**Issue by jhv2017kam** [microsoft/TypeScript#56984]
Given the following code:
`
class Foo {
    bar = new ResizeObserver(entries => this.baz(entries);}
    baz(entries) {
        // ...
    }
}
`
"Show call hierachy" on baz will show:
`
baz
    Foo
`
instead it should show e.g.
`
baz
    Foo.bar
`
or maybe
`
baz
    Foo.bar#<lineNumber_linePosition> 
`
where <lineNumber_linePosition> is where calling lambda is defined

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
