### ISSUE TITLE
Code snippet hangs compiler

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#5699]
```typescript
var c;
function f<T extends typeof c> (c: T) {
    c.x;
}
```

Tested with TSC v1.6.2 and latest dev build (1.8).

**Comment by mhegazy** [comment]
@sandersn can you take a look

**Comment by vladima** [comment]
nice :) simplified repro
```ts
function f<T extends typeof c> (c: T) {
    c.x;
}
```
bug is that parameter `c` is visible in type parameter list so we loop forever trying to get apparent type of `c`

**Comment by mhegazy** [comment]
@yortus can you give `typescript@next` a try.

**Comment by yortus** [comment]
@mhegazy confirmed fixed in `typescript@next`, thanks guys.
