### ISSUE TITLE
'getTransformToElement' missing on SVGGraphicsElement 

### ISSUE THREAD

**Issue by anton-tregubov** [microsoft/TypeScript#56994]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

https://www.w3.org/TR/SVG11/types.html#__svg__SVGLocatable__getTransformToElement - Specification.
But on TS lib

```
interface SVGGraphicsElement extends SVGElement, SVGTests {
    readonly transform: SVGAnimatedTransformList;
    /** [MDN Reference](https://developer.mozilla.org/docs/Web/API/SVGGraphicsElement/getBBox) */
    getBBox(options?: SVGBoundingBoxOptions): DOMRect;
    getCTM(): DOMMatrix | null;
    getScreenCTM(): DOMMatrix | null;
    addEventListener<K extends keyof SVGElementEventMap>(type: K, listener: (this: SVGGraphicsElement, ev: SVGElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof SVGElementEventMap>(type: K, listener: (this: SVGGraphicsElement, ev: SVGElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
}
```

Thare are no **getTransformToElement** :( (that should be in SVG 1.1)

Related: https://github.com/microsoft/TypeScript/issues/23420

**Comment by MartinJohns** [comment]
The specification you linked is for `SVGLocatable`, which has been deprecated. The graphics element does not have such a method.

**Comment by RyanCavanaugh** [comment]
This is noted as being deprecated in SVG as of 2016 https://stackoverflow.com/questions/5891552/more-usage-of-gettransformtoelement

**Comment by gorshkov-leonid** [comment]
A direct link for history: https://lists.w3.org/Archives/Public/www-svg/2015Aug/att-0009/SVGWG-F2F-minutes-20150824.html#item02
