### ISSUE TITLE
Parenthesized `SatisfiesExpression`s with comments are not unwrapped consistently in emitted JS

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#56997]
### 🔎 Search Terms

parenthesis satisfies comment removeComments emit

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTAEAECcFMFsHsBu0DC9a2gOwC4GcAuUAMwEMAbPaAKAGN4s8dRTQBeUYAKnoy7ACMABhZ5QWAK6wARtEh0GTUNPagAFN16x+oYaPFTZkAJQLGzWqrUae6bYJGkxkmXOOmzSgCarNdnXp4pDgAlnjEIdDOhnKezNBWfnwOoEGh4ZHRriZxJFY2WgEiaWERUQbZ7kA

### 💻 Code

```ts
// @removeComments: false
const a = /*comm*/ 10 as number
const b = (/*comm*/ 10 as number)
const c = ((/*comm*/ 10 as number))

const d = /*comm*/ 10 satisfies number
const e = (/*comm*/ 10 satisfies number)
const f = ((/*comm*/ 10 satisfies number))
```

### 🙁 Actual behavior

Emitted `.js` file:
```ts
"use strict";
// @removeComments: false
const a = /*comm*/ 10;
const b = /*comm*/ 10;
const c = /*comm*/ 10;
const d = /*comm*/ 10;
const e = ( /*comm*/10);
const f = (( /*comm*/10));
```

### 🙂 Expected behavior

```ts
"use strict";
// @removeComments: false
const a = /*comm*/ 10;
const b = /*comm*/ 10;
const c = /*comm*/ 10;
const d = /*comm*/ 10;
const e = /*comm*/ 10;
const f = /*comm*/ 10;
```

### Additional information about the issue

Those are not handled by `visitParenthesizedExpression`
https://github.com/microsoft/TypeScript/blob/4557e34e7003f5dd11fd33881ae91d10451fb23a/src/compiler/transformers/ts.ts#L1641
since they are (correctly) not considered to be assertions. That skips over the `createPartiallyEmittedExpression` call that, from what I understand, would help it to be handled correctly (consistently with assertions). I'm not sure but fixing this might require some changes/additions to `OuterExpressionKinds`

**Comment by DanielRosenwasser** [comment]
Thanks @jean-michelet!

**Comment by jean-michelet** [comment]
You're welcome, thanks for the opportunity!
