### ISSUE TITLE
Binding element alias is kept in function expressions even though they are never used in declaration files.

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#56992]
### 🔎 Search Terms

binding element alias declaration files

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.3.5#code/KYDwDg9gTgLgBAYwgOwM7wGbIIxwLxwAUA3nGFBGAFwBGcAvlXKeZU8gK4C2NwUDASnwA+ZgwDcAWABQM0JFiIU6OFgBM+IiwrU6jMa2pxOPPoJFwaU2dPnR4SNJmQBmTSTI7aDJtrbHuXn56ASYYAE8wYAgMSwsABmsgA)

### 💻 Code

```ts
export const fn1 = ({ prop:b }: { prop: number }) => { };

export const fn2 = ({ prop:b }: { prop: number }) => b;

export const fn3 = ({ prop:b }: { prop: number }): typeof b => 0;

```

### 🙁 Actual behavior

`b` is kept in all exported function signatures, even though it is never used. Even if we have `typeof b` in the signature of the original function expression, the type printer will remove that and use the resolved type.

```ts
export declare const fn1: ({ prop: b }: {
    prop: number;
}) => void;
export declare const fn2: ({ prop: b }: {
    prop: number;
}) => number;
export declare const fn3: ({ prop: b }: {
    prop: number;
}) => number;
```

### 🙂 Expected behavior

`b` is removed from all signatures since it will never be used. Even if the original type uses `typeof` the resulting type will resolve any typeof expressions

### Additional information about the issue

Related to #55654

**Comment by jakebailey** [comment]
`test1` is a function declaration, which declaration emit walks directly and can reuse nodes from. `test2` has an inferred type from the right hand side, so declaration emit uses `typeToTypeNode` to produce type nodes for the type. The two unfortunately behave differently as declaration emit has full context whereas type printing does not and has to be conservative.

It's possible that we could reuse something here, but arrow functions / function expressions are not legal initializers in declaration files and must be rewritten. Right now, it's all "consistent" and goes through the same printer.

**Comment by Andarist** [comment]
Thanks for the explanation - it helped me to understand how some of this is implemented :)

**Comment by fatcerberus** [comment]
Here's an interesting discrepency I found while playing around:
```ts
// index.ts
export function test1(a: number): typeof a {
  return a;
}

export const test2: (a: number) => typeof a = function (a: number): typeof a {
  return a;
};
```

```ts
// index.d.ts
export declare function test1(a: number): typeof a;
export declare const test2: (a: number) => typeof a;
```

which is consistent with what @jakebailey was saying... *BUT!*  The hover text is different!

Type hints:
* `test1` - `function test1(a: number): typeof a`
* `test2` - `const test2: (a: number) => number`

Hmm... 🤔 [(Playground link)](https://www.typescriptlang.org/play?ts=4.3.5#code/PTAEEsDsBMFMA8B0AXAzgWAFAIA4HsAnZUAMwFdIBjZcPSUZWVZARgAoBDALlEjIFsARrAIBKHsgCeOWHhKgOoAN5ZQoArGRkC9DgG4sAXyxZchYpTrMGTZACYenHnyEjRoALwA+BtNnzFD1IKalp6J14BYTEJPzkFZVV1TW1dA0xDdKA)

**Comment by dragomirtitian** [comment]
@fatcerberus Type printer flags are different between declarations and tooltips probably. Declaration emit has different requirements.

**Comment by dragomirtitian** [comment]
Another case that is not currently handled:

```ts

let prop = "0";
export function oo({ prop: a} : { prop: number}): typeof prop {
  return prop
}
```

In this case the name `prop` will now shadow the parent scope variable producing a different result.

**Comment by Andarist** [comment]
Doesn't this one prove that renames in declaration files should always be allowed (and kept)? It seems that by removing them edge cases are introduced and it's not even apparent to me how this one above could be fixed without overcomplicating things.

**Comment by dragomirtitian** [comment]
> Doesn't this one prove that renames in declaration files should always be allowed (and kept)? It seems that by removing them edge cases are introduced and it's not even apparent to me how this one above could be fixed without overcomplicating things.

I was just arriving at the same conclusion. Sure it would be nice to remove them since they are an implementation detail. But this seems to introduce a lot more problems than it's worth if we want to do it correctly.

I would suggest we just remove this behavior an revert back to always preserving the aliases. 

@jakebailey @RyanCavanaugh I can open a PR to remove it you also agree with this.

**Comment by jakebailey** [comment]
I'm fine with reverting the PR, so long as we keep all of the tests and add tests for any new edge cases.

**Comment by jakebailey** [comment]
Right, makes sense.
