### ISSUE TITLE
Use Custom/Nightly Build of TSC in Visual Studio

### ISSUE THREAD

**Issue by SamuelEnglard** [Microsoft/TypeScript#5700]
I'd like to use features and bug fixes in more recent builds of TypeScript than the one in the latest tools that ship with Visual Studio. Is there a way to make Visual Studio use TSC from a custom location instead of the bundled one?

**Comment by DanielRosenwasser** [comment]
Looks like you want to use what we call ["dev mode"](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio). Clone our repo and [follow the instructions on our wiki](https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio).

**Comment by mhegazy** [comment]
Note that this only affects your editing experience in VS and not building through tax.exe called by MSBuild. For the later you can use node with 'typescript@next'; @paulvanbrenk is working on getting a nightly nuget release that should streamline this scenario.
