### ISSUE TITLE
Type matching seems to be reversed when assigning function to const

### ISSUE THREAD

**Issue by Tlepel** [microsoft/TypeScript#57003]
### 🔎 Search Terms

"ts2322", "strict typing", "strict function types"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about function/method types (and the `strictFunctionTypes` option)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=5&ssc=64&pln=5&pc=68#code/GYVwdgxgLglg9mABFApgZygMXNeSAUaKANitHAE4BciGFMYA5gDTICGFjKUNdDjAShoA3ODAAmiAN4BfANwAoCAgzJ0PRIRJkolGuADWYOAHcwrAHRWOjNDTZgAngMQBeAHyJREt2ozZIWARFAHoQxAjEAD1EABVHAAcURAByLVJyalooeiZWKBtuXhz+Fw8vMXEUxBg0RGMoRDY0NBhGMDYAI1JkOGRE5LSiDN0sw2MzS2tOOyanMs9vKosFMMj1uIG6uGBEBI42AFtuFAo6lOGdSmqHSQvtTJuKZIZlQ-3YbpQVtY31+KSqXGpjA1Vq9TgjWarXaXR6un6gIuJSYKQs+AATABmDEYgQKIA

### 💻 Code

```ts
function testFunction (selector: string, target: string): void {};
const test: (selector: unknown, ...args: any) => void = testFunction;
//    ^ Type '(selector: string, target: string) => void' is not assignable to type '(selector: unknown, ...args: any) => void'.
//        Types of parameters 'selector' and 'selector' are incompatible.
//          Type 'unknown' is not assignable to type 'string'.(2322)
```

### 🙁 Actual behavior

The compiler throws an error saying the required type for `test`, a function with an unknown first argument, isn't met by the type for `testFunction`, while `testFunction` does have a first argument.

### 🙂 Expected behavior

I expect this to compile without errors, since the type given specifies that the type for the first parameter isn't relevant.

I tried the following smaller example, and it does compile:
```ts
const test = 'test';
const testResult: unknown = test;
```

The same should apply for a function assignment in my opinion.

### Additional information about the issue

The compiler error isn't present if the `strict` option is set to `false`.

**Comment by fatcerberus** [comment]
> since the type given specifies that the type for the first parameter isn't relevant.

That’s not what `unknown` means.  It’s not an “I don’t care” type (that would be `any`), it’s the top type, so the type specifies a function that can legally accept *any value at all* for the first argument, however `testFunction` says it only works with strings.  The error is correct.

The relevant option is `strictFunctionTypes`: https://www.typescriptlang.org/tsconfig#strictFunctionTypes

**Comment by Tlepel** [comment]
> It’s not an “I don’t care” type (that would be any), it’s the top type, so the type specifies a function that can legally accept any value at all for the first argument, however testFunction says it only works with strings. 

Oh right, that makes a lot more sense. Thanks for the explanation, my thought process was the wrong way around. I saw that `any` instead of `unknown` fixed the issue, but couldn't figure out why that would solve it.

I'll have to rewrite the typing, but at least I can see that this is not a bug in TypeScript.
