### ISSUE TITLE
`All<T>` that provides an union of the all static values belonging to `T` seen in the source code.

### ISSUE THREAD

**Issue by genki** [microsoft/TypeScript#57018]
### 🔍 Search Terms

algebraic data type.

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The tsc knows the all static values while processing the code.
I would like them to provide the values as the finite union type as like as `All<string>`, `All<number>`.

### 📃 Motivating Example

Suppose we define the type `X<T>` that matches every values such as `{foo:{foo:T}}`, `{bar:{bar:T}}` and `{baz:{baz:T}}`
Simple solution I found is:
```ts
type X<T, K extends PropertyKey=PropertyKey> = {
  [P in K]?: {
    [Q in K]?: P extends Q ? T : never
  }
};
```
But unfortunately, this doesn't work.
This limitation comes from treatment of the infinite sets on the algebraic data types.
If we have the finite `All<T>`, we can answer to the question by like this:
```ts
type X<T, K extends PropertyKey=All<PropertyKey>> = {
  [P in K]?: {
    [Q in K]?: P extends Q ? T : never
  }
};
```

### 💻 Use Cases

1. What do you want to use this for?
Declaring more detailed types over the hierarchical objects.

2. What shortcomings exist with current approaches?
It is difficult to define a type that is over the object hierarchy.

3. What workarounds are you using in the meantime?
Giving up to check such the type mismatch.

**Comment by fatcerberus** [comment]
But `All<string>` would be an infinite union...

**Comment by RyanCavanaugh** [comment]
I don't understand what's being proposed or what problem you're trying to solve - the example here is pretty convoluted. What's the zero-order usage/behavior of this type?

**Comment by genki** [comment]
@fatcerberus I think it may be smaller than LoC.

@RyanCavanaugh This can provide a way to define the type of constraint on intersection between parent and child objects. `Having the same named key` is an example.  Current the TypeScript couldn't making intersection between the infinite sets such as `PropertyKey and PropertyKey`. But if there are finite set of all `PropertyKey`, it is possible.
This can be nested more than 2 hierarchy, so thus we can freely design constraints over the tree structure of object.

**Comment by genki** [comment]
Of Course, it is the best if this becomes working as is
```ts
type X<T, K extends PropertyKey=PropertyKey> = {
  [P in K]?: {
    [Q in K]?: P extends Q ? T : never
  }
};
```

**Comment by RyanCavanaugh** [comment]
Again - what's the zero-order usage/behavior of this type? What are a few very basic concrete instantiations of it?

**Comment by genki** [comment]
@RyanCavanaugh Sorry, I am not familiar with the saying "zero-order".
The basic concrete instantiation is to define types having constraint such as `{value:{value:T}}`.
This is useful for using as a reference to a property of state object.
For example, there is a state object such as:
```ts
type User = {name:string, age:number};
const user = {name:"John", age:20};
```
then we want to permit the R/W access to the `age` property of it to some functions like this:
```ts
const incrementAge = (refAge:{age:{age:number}}) => refAge.age.age++;
incrementAge({age:user};
```
This is already possible. But if there is `All<T>`, we can define the `incrementAge` function like this:
```ts
type Ref<T, K extends PropertyKey=All<PropertyKey>> = {
  [P in K]?: {
    [Q in K]?: P extends Q ? T : never
  }
};
const keyRef = <T>(ref:Ref<T>) = Object.keys(ref)[0];
const getRef = <T>(ref:Ref<T>) = ref[keyRef(ref)];
const setRef = <T>(ref:Ref<T>, v:T) = ref[keyRef(ref)][keyRef(ref)] = v;
const incRef = (ref:Ref<number>) => setRef(ref, getRef(ref) + 1);
const incrementAge = (refAge:Ref<number>) => incRef(refAge);
incrementAge({age:user});
```
We can define utility functions using such the Ref object in type safe.

**Comment by fatcerberus** [comment]
“Zero order” here just means what does it do, concretely, by itself, as opposed to an abstraction in a larger use case (which is what you keep explaining).

When Ryan asks for zero-order behavior he’s essentially asking, when you (hypothetically) write `type Foo = All<PropertyKey>` in a given program… what is `Foo`?

**Comment by genki** [comment]
@fatcerberus Thank you for explanation :)
As written in the title, the`Foo` of `type Foo = All<PropertyKey>` is the union of all `string`, `number`, `symbol` literals having seen in the source code the tsc is parsing.

**Comment by RyanCavanaugh** [comment]
I don't feel like we're really progressing toward clarity on this. Either way, features that apparently only make sense in higher-order scenarios generally aren't a great fit for the language; we don't really have anything that works like that.
