### ISSUE TITLE
performance wiki page says to use --trace-ic but node says bad option

### ISSUE THREAD

**Issue by lukeapage** [microsoft/TypeScript#57016]
### 🔎 Search Terms

--trace-ic, node, performance

On this page:
https://github.com/microsoft/TypeScript/wiki/Performance#performance-tracing

It says to do this:

```
node --trace-ic ./node_modules/typescript/lib/tsc.js --generateCpuProfile profile.cpuprofile -p tsconfig.json
```

but in node v18 I get:

```
C:\Program Files\nodejs\node.exe: bad option: --trace-ic
```

**Comment by jakebailey** [comment]
Probably we need to stop recommending this at all and start pointing to https://github.com/microsoft/deoptexplorer-vscode and dexnode.

**Comment by jakebailey** [comment]
I've updated the wiki to instead suggest dexnode. https://github.com/microsoft/TypeScript/wiki/Performance#profiling-the-compiler
