### ISSUE TITLE
ESM Version of Typescript in Node Package

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/TypeScript#57010]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Is there a plan to include a ESM Version of Typescript in the Typescript nodejs package? Or does there exist one?

**Comment by RyanCavanaugh** [comment]
Not yet, and no imminent plans for one.

**Comment by jakebailey** [comment]
See also #51440.

**Comment by jogibear9988** [comment]
https://github.com/microsoft/TypeScript/issues/32949

**Comment by jogibear9988** [comment]
> Not yet, and no imminent plans for one.

sad...

currently I'm workin on a vscode HTML Designer (https://marketplace.visualstudio.com/items?itemName=node-projects.vscode-designer-addon) wich uses typescrit for parseing inside a webview, wich should load esm modules via importmap (https://github.com/node-projects/vs-code-designer-addon/blob/9a776a01fd4b6c5a9bdf2a3a21cb671e7eda9edb/src/vscode/DesignerTextEditor.ts#L174) and one of the imports should use typescript (https://github.com/node-projects/web-component-designer/blob/08c50e1ccddfabbead11fa2e840931ebb7619a83/packages/web-component-designer-htmlparserservice-base-custom-webcomponent/src/service/htmlParserService/BaseCustomWebcomponentParserService.ts#L2)
But maybe I could load TS as a global instance, I'll test and will see...

**Comment by jogibear9988** [comment]
I fixed it now by using a global script import, but now I have no types. For this I created another issue: #57019
