### ISSUE TITLE
Overriding all parent methods breaks inference

### ISSUE THREAD

**Issue by xixixao** [microsoft/TypeScript#57035]
### 🔎 Search Terms

infer, extend, class, interface, methods, type parameters, generics

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about inference

### ⏯ Playground Link

[link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDiwB2woEsDGAkgCYA8AKgIYBGANsAHKUC2qoMWxAznFzHpgDmAPjgBeXv1xC4AMjgBvOAH1lMGvSasAXHCp1GLVAF8A3AChzoSLATJUANUq0ArqjHm4cAD5xML2lpPHzhqXEFpGGDff2ZqHGjQiAh6SkxEvgFBRIBBKChKRAAhFwAzUoSvXydXYABtAF1EpTqAa2BEXUzpQQbdF0xiYFLpYGIQmrc4MytwaHgkFHQsHAIAEQh8F1ZMeAkAJWB8aDJuoQAaOEngYQtZm3hInFLKfFQAZWBKKHwAC0JBqAAMIQTAjQSkYKfb5-ABiuGAtHG7E4PDOgnOwXhtA4UHhiO4cBRgzRUiE5lECmCAHoAFS04JwWl6X6oEYEhAQODSIYgOClaD8gK0BDsXhfH6-AB0jIZXiZLNwPGYLj4oVQlH5CKRcAgpTsSwABujDTL5bTqcEuBK4driLpoZL8Ui7l46XKvMycsRiLgYLhQc4tQSeDAuTzQPzBS81SMcasZAB3VmYOBQAaYHrimG-OAARzceGAXDNnstXjjuOd3AA-LpsVW7VxGhZjJZ3Z5meRWXBjmDwi4Cv7QVGoHBNQA3I5hscRkBmuXMgACYBcdAInct1nm3N2z1ejmn0ABvJB-YhwQcR7xdqJIA4JMkWUxXgbOGrPGJhPRFMUNPpsosmyt5hruvKjnAU74DO2aSqWTKAd2SpwCqarxOOwY6nqBqoIaE5St8BSIAAFPhpS0BAlAwAAbAALMRACUDGGnAxGCpqAwBpgDGyuWkHXtWuhXtB0DVhYboAeaQFwPQQgwLm2HyagUEzjwc5jFKirKqq8DofEMCJsAWBwAATOOgymQADLRAAcu74K4XC4FO8EWsEvo7E5oJcLosTxFA4lwB2Uner6w6YEG7JIqG4aAnyApjjG8CVgmghwMmxnppgmYyCpgrWjmxauXxKU3iGdZwG+ZXRS25httutgOZQXA8DUuDEFR0CQl45D2O8+B4GAMC9SgL5wIQXAAPJDVxQZfjw1DJKkqYSC8tDWmN1YAApUb8n73qiT5ZhI2BTlAv5Ul4UBfMQoK0IgOEAIS6CNwD9YNw32IF12ULdmD3dyU0zYGtDPeNQPhc4303XdD1RcQO3yVwYPbbtXCukF1JwFtUAQCgsBw+xoR+rq+qYBAzDSEGiyoFwlAVEgpY-X9APKEqbUdTO-SAiM2DEBjzOw7qwMRbQuiLSkXwrfyzjWq29w7jTcAAKLgGkZCTdQABW06vXeD6EocxxQGQaSIJcZvCKIHheJrOvQXr81wEbJykGbFuYIgwiMnANZ-vKAdwHUADSHS7nA7SINhdu6-YfRwDHDv2CHHQNIFAdtgHvnAGddzBV6OFwEMXADbgYQyM4IqKT2t1bDsyVNuHmrqAYC6dkB1q9mkRJ+qyY7ofDfhGDwxG0Lg7RwAARBFrCTwxupjtdFTXZgbwxZhhKgu32B8GMura9OI9jxPk9gLj+P+kVM-AHPC5wCua5j-gm4K7YSsYNgeD4KjSPiEdQh5yxieSMr0eCY2pBAyBUDoEwNgXA+BCCYHtkkgXJWxdS7lzSkpBeQxrrjHhmpVM3c5xtwVN2YsqB8Dd2AL3HA6oN5D1YEfceqBp5GDngvNMwwcBYDXpyDePAt4Kh3hwcYEAD7QWYSfM+eMcCXxLNfW+7cH7rmfkyLccw372GWJ-AgwCQAfj-uiWq5h85wByIXdBeBMEIB7OpQhGEW70FIcyQgMAADkPBu7iPtvAZglAwBgCzF8P4YFIzX34dggh4dsEkOUauVRL8GoLG0R-VY+B9D0H0cWP+LsTakHRJcNJX99EfluMgxc5jLHFgwVmbBfZwSDiolxUmGECqSjCfOeJj8NzqNfikpYxSCCOj+Pos84I-6XVgraAkXQySCECqVD8cysitjzigqpaCanWKzJXVp2D2mhPsU3BAGhgAuK0oDcy+9fEoQCUEmQITcxzkYagUC9TQQTISrY1AcSFQqKfkkzRAzUBDIyWckZ-w4o5IOEcV2Vp5ljTBZCsZnzwgUnWZUixWyS47JkB888TTwqtMnNeTpd8AW9LcskwuYLhIzlReeSZwQ8rVXtP-BZ7lcCeS4j5Pw2x-KLNwPGNlfL0RrMsKYjZS4nhQFFkCh4hd9HMq8HONY2zcBDWgCsnoQqQw6qELVGYUrKkyr3HK5wCrFbaJRXFFVnT1W4s1VzDlgVDm-EEq64ISymwGsEEaiwZjsXaKsWXXZgR9k9lZZ0nJ0hHFnIuUhNSXjUw+OnHcwJwTXjPLtRE95PYGnhAgrEuKFKEmAr6TS9+Kwv6ZOAPS480KeCwuNmQBFz5gh0uvIy8EGLzBDCatdXstBmo8Dreq3mfouLdTgBsOuWB4BOzNn-d2WI7SIz2vrQ66IjGIouv+D0CoJ2jGuS8kc8lkJOPObKRCXJUhyvHItFwjwm2XGtKgOox6cppWyVwBoxFfgwBgGAHyEDa4lj7FOecQwJzUlVD0ak9iGKuUAiub4LBXlwAALTSQidXX5pbUNgHQ8wAR2HpLRNAnOS4caTg4E0gAWR0rwFA+BcClAelRGSXw1SgmAIBeGrl77XRgIOTAPALEKCXGPTArQ9BnK-VO0Exh0q91schF50gHIuCGMQYqwQ5wzq8PorQbADqPkKT7eEUA+A-1zE7OzXAxpeEOLZ9daMt2Pkc40YIwhiI+2vroEzRhnMCN0HUazbmCQbsuFKOLrmYCOaaF4BiL0FPDGkEpzARnZ2bG2Au0LjnfNwDuJYCSh7mRfo1NMnN4Fz2-EvQmm9UlyB3olEQp98B3Uxqc+KD9kL-2AeA6B6k4GpSQdAFKGD1IOD3iw+65DzXPT32IwUUjEScPkMw-h8lRGSOdPGUWzbPZusvMLYIIlLS03QSE0uETYmJOKGk9IOT46MuZnCipxMamL1ohtLVyMWnXC6f014d1+icvBdYJ578e6A6QurDDngjnCvCsbCGJHlV3O-xOjnSocA-MBaMEFuKpnQtzkO4IXQqtiODFILa08aKIQI7tJcKqZTvYpbSwYRT4Uctzvy7sVH0W0bFdK22SwNLZUvDeCrXYvPp3BAF-XTHy6JCrtfNjzdTsd0SEs14ZWxBBA5KXZ7FdntfxOze5OvnPtlcFas1rrgxWpnBWW1V09dr6uNdbktshbXvgdYgM+nrb6jJB0UzIX9g2gMge0GBzYEHQRQamznODTkhCIabYt80e21uYeO6gPD+oS28lu6tjD0TC9kao3FGjqaTb0bgExtUXBWPsc4-AVIvHsACbtLd+7crHtSZk699LNuuJfZ+w1wh4Egc6Y0rxAzcVIek6MJj-X8pIuJa15jlHPsEuOb307nzXhCcB0C+NNfrBQsEPC9vuzsX4vFh3yLpGyW4CpblzABXoJ+d5frmFyRA3Scx9kN2N2dzPwxjdyPXe2q1Oy91TF+1OV91zxawDwfRoGDy63+1Dz6yDgGwA1jxGzGwm2gzT1mxgHm3+xz09Dzwww21w3Xx2z+WWzQ3zwpyZ3Iy2wQPAnO0uxHGuxgAH2AFEyHyqRHxe3kx53eyyyn3knUz+xzE6XsmB0X3ND4nBxXx9ihzMwNlJA7Xh3+0Rwcyd1RxFUMVMLf03VxzOl838wv2Jyv15DJx9k4PPGpzVjpwZ2BCZ3p2MNZyxwsKbCtmCC-2Vnl1kNtwDntyF0d2sNAIDnAOLF83F0sD7DVBAGp0iInz-wUGMEuEnmUAGi+HCnIG5RvkuHyOtn5QjWanMkQDuCVi2j-hpmwj5Ct3H0yz53dgaM519gQHTH4y8F0DWjlksGaLMgkDaP1A6PM0JGt26MV1VTBDoVhDGmkGXkqgAEYKRgg-Z+A3BghRjZZgA7hR05FSBlYCxZZSAtpLhDibhykLjYAribj1o7iTIHihirZSsoE4B3hyAch9hyAXp7AsM-gjhWgsxn1hUeAoF+lC5riXBbiAANS4AATRqOIgoD83njEFEHIEx1RIGO2LgF0BMnnidhnXIApEYnEEJMxwxNJPJNMn2MGKOJGJlnWjOPbCxmLBkyoN9DpgMCw2wDmxk1QCXBpidSGiwwFMiGpHJiwwGFVDGCwwnG+GdxpVKAGGghaReJgAoEx0eLxP9kxj8C5GwD3lAlugaIvSEEenSmAHcSHS1mY0NN2XgGOGYCCXoAQAqNsS42wRphpCxgr1YFxCuUeJlDbH+OVgYDWDBJQAhNZHwGhJkFhPWnAUtCAA)

### 💻 Code

```ts
// I have a class using builder pattern that I'm trying to extend
declare class Def<T> {
  a(): Def<T>;
  b<SearchField extends T>(param: SearchField): Def<T>;
}

// The extended class has to redeclare all methods, because it has a more
// concrete subtype (it has additional methods, not shown here)
declare class ExtendDef<T> extends Def<T> {
  a(): ExtendDef<T>;
  b<SubT extends T>(param: SubT): ExtendDef<T>;
}

declare const x: ExtendDef<"hello">;

// Both of these should be true, but they are not
type DoesItExtend = typeof x extends Def<any> ? true : false;
type CanItBeInferred = typeof x extends Def<infer F> ? true : false;
assert<Equals<DoesItExtend, true>>;
assert<Equals<CanItBeInferred, true>>;


// Ok, that's surprising, but this is even more surprising:
declare class ExtendDef2<T> extends Def<T> {
  a(): ExtendDef<T>;
  // no b()
}
declare const x2: ExtendDef2<"hello">;
// This works!
assert<Equals<typeof x2 extends Def<infer F> ? true : false, true>>;

// Ok, ok, but this is even even more surprising:
declare class ExtendDef3<T> extends Def<T> {
  // a(): ExtendDef<T>;
  b<SubT extends T>(param: SubT): ExtendDef<T>;
}
declare const x3: ExtendDef2<"hello">;
// This works too!
assert<Equals<typeof x3 extends Def<infer F> ? true : false, true>>;

// As long as I don't override at least one parent method,
// the inference continues working. Unfortunately I cannot do this
// in my code, I !have! to override all the parent methods.

//// START: Type-checking utils ////
type Equals<X, Y> = (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y
  ? 1
  : 2
  ? true
  : false;

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function assert<T extends true>() {
  // no need to do anything! we're just asserting at compile time that the type
  // parameter is true.
}
//// END: Type-checking utils ////

```

### 🙁 Actual behavior

Inference is broken when I override all methods.

### 🙂 Expected behavior

Inference should continue to work.

### Additional information about the issue

This is blocking a library release I'm trying to make.

Also I cannot change the parent to have `this` in method return types, because the return types actually change (the code has been simplified from hundreds of LOCs in our project).

**Comment by DanielRosenwasser** [comment]
My guess is that during inference, there are no places to actually infer types from directly.

With identical type references like `Def<Blah> => Def<T>`, the type system can bail out early because it knows `Blah` can be inferred to `T`.

As the type system tries to relate an `ExtendDef` to a `Def`, it does so structurally. As it descends into the type, it finds no useful information in either `a` or `b`. It can't infer from the bounds of your generics, and where it matches up an `ExtendDef` to a `Def` the type system finds itself doing work it was already in the middle of.

One easyish fix is to just have something like

```diff
 declare class Def<T> {
   a(): Def<T>;
   b<SearchField extends T>(param: SearchField): Def<T>;

+  protected " _unused"!: T
 }
```

You unfortunately cannot declare this as a `private` field because TypeScript makes the assumption that the types of private fields can be erased away in declaration emit, which would make inference fail structurally.

Anyway, this is more of a guess. Not sure if @RyanCavanaugh wants to take a look.

____

Side note, in the code you've given, you're using *a lot* of type parameters that are used as inputs, but not in the return types. I would get rid of those if possible.

**Comment by xixixao** [comment]
Thanks @DanielRosenwasser, I boiled this down from a much more complicated code. The type parameters are constrained in reality, and they are used in the type of the class, which is then used (not refuting your analysis though, I don't understand the typechecking internals well enough).

You can find real `Def` here: https://github.com/get-convex/convex-js/blob/main/src/server/schema.ts#L151-L311
And `ExtendDef` looks like this (with additional methods):

```ts
interface EntDefinition<
  Document extends GenericDocument = GenericDocument,
  FieldPaths extends string = string,
  Indexes extends GenericTableIndexes = {},
  SearchIndexes extends GenericTableSearchIndexes = {},
  VectorIndexes extends GenericTableVectorIndexes = {},
  Edges extends GenericEdges = {}
> extends TableDefinition<
    Document,
    FieldPaths,
    Indexes,
    SearchIndexes,
    VectorIndexes
  > {
// overridden parent methods and additional methods...
}
```

> One easyish fix is to just have something like

Nice! It's good to know I don't even need to declare a method to get around this on the parent.

**Comment by xixixao** [comment]
Hmm, so I also have to use `return this: any` in the parent for this to work:
[playground link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28A8AVAfNA3gKGtAtgBQAeAXNCgJTkLLpa554BOApgC4CuzAdtD5xAhokETwCeAbkYBfbHOwBLHu1bMAZmGCtoAIXCoANNADSGVsVU8AJjFqoMOPETIVqegymNnpC9Zx5gdkV4PgAjcEJ3fTAkCHZmZQBzY3jEniTHRjYuXn5BYVEwCV9sMux2cQAHHVoUatZUaAsrW2gAZWAAC1Z8MAwAXiwAbQBrVnFoZWhx8Xh1CmgAMmg05IBdck6evrGJ9ebLVhs7RAdoAH5F8h5WADc1GWkKho7u3rBoIYAlVmB4ZjWOIJZLGezFcRoNBlf48eLQYhfLDqRSsEDWcgRMBRJ7lSo1aAADSRdQaSHxrHmCOh2CAA)

Code:
```ts
// I have a class using builder pattern that I'm trying to extend
class Def<T> {
  // Comment out this field, you'll fix the error in `a` but will break
  // inference later.
  protected " _unused": T

  a<U>(u: U): Def<T & U> {
    // This errors, but it is possible to cast this as any to suppress the error:
    return this;
  }
  b<SearchField extends T>(param: SearchField): Def<T> {
    return this;
  }
}

// The extended class has to redeclare all methods, because it has a more
// concrete subtype (it has additional methods, not shown here)
declare class ExtendDef<T> extends Def<T> {
  a<U>(u: U): ExtendDef<T & U>;
  b<SubT extends T>(param: SubT): ExtendDef<T>;
}

declare const x: ExtendDef<{a: "hello"}>;

// If you comment out the field in Def, the second here will error:
type DoesItExtend = typeof x extends Def<any> ? true : false;
type CanItBeInferred = typeof x extends Def<infer F> ? true : false;
assert<Equals<DoesItExtend, true>>;
assert<Equals<CanItBeInferred, true>>;
```

**Comment by RyanCavanaugh** [comment]
I'd need a concrete example where inference was failing the presence of what could have been a deducible structural inference to classify this as a bug

**Comment by xixixao** [comment]
@RyanCavanaugh Does this example help? [playground link](https://www.typescriptlang.org/play?#code/PTAEElQCwQwNwKahqAxgGxgZy6ArlgJYB2A5qAEZ6HoAmCATqAA4wAubjxobsbEAcgC2PBgE8S5NgHtQCAB6ditAFAZsuACIIAZgB4AKgD5QAbxWhQWBGwOGjACjYAuUAYCUr7fuNmLl0AYbPAZuXkIsAG5-AF9-GD0AVUc8V0TPUG9DUAAyUGS-ANAQCH4IlmkcQgp0JBk0bH5w3GxkYjEeWSw8ZmYgnB4oJEYGaQZnf0sgthCwqAjoyzjLCj0AZQQYBlQoADFCBDo5RQRlXGMHVgYYIVcNrZ39w9oMrN9zIunZwYXY-xLEsRUNIhEJTvwdGNBkgSDpGKdUHVZAB3MYAa2QpBgJH+YCEDleunshWKYCmwVCPyiuNAcTiKhKBiGxyU9FoaEwA1guHqQXo6iCyHQ6FAYN40loWAANJQEKgYAQYfxuchRWMEAywMCgdMkN0KGwxMwkA5CMrWjBaLQzYRpMQYCKxVAJdLQMRpPwsM7kdwhkF3Cp+ZhBeoBgBRE7KN4mBSsrRE97+ay2exOVweVwR1nRxbIJIpNIZLOnWhvXL5Iy51ZrPAUAwskvnRxXG53WsZ0DFqMJysqenarD8eSgAC8oAcxAQyM7kdLugJ7gAdMmDA5TPJXAAiIbC6SbmJLmBrsRb1EMOj79zRFSG42ZaQILDgNhd9lj28IaQ6UDD2ONzJEjA7QmAA-KIeBIK4OgOtY0QfhAxBwgwfKjjwRqft+v6zvG+iwowoC7KBBGgK4k6IAw0QaIwbB6GGACOeAwXomgPk+L6zjKbAMBBRi9iU4DfmI0h4PgQIgmCxBNMy+LuKKNjOuyzSgMiNAiqwOAqFRDA0fRjHoFgejgIhIwILQMrrq4g4MJIMTlqYJ5WFxNm8deIAlGsBgAIIAEoGOm6EALQ7HKaKSPgbA0LgbnADe6GdgxTEABoygAmiYY4OKmskjiY9Z-mcoCJaAYEAIwkaAABMsn5ZKoBZaOuUNgVKX+KV-iuBVrXgRqlhQTBCCuWAj7oCQbABdaWAwDUCABZOigBSNk6gAAAh+WCoNZzBjcNo3AO6AV4MQiq0AFcBbFgKg6IdqARXayA4NR2Q1Ty3EII4skfKSbqyJOpmdKAtCyEBYjhGQACEykIAIgoAFYEPwWkRWQyD8MCQjMDQdSEGCgzsNCaHGjSLZivh5RcRBi59pqJRhgAcpo-nGkFQyoKFyN4BF+mkiAKhAA)

```ts
// I have a class using builder pattern that I'm trying to extend
class Def<T> {
  setT<T>(t: T): Def<T> {
    return this;
  }
  a<U>(u: U): Def<T & U> {
    // It is possible to cast this as any to suppress the error:
    return this;
  }
  b<SearchField extends T>(param: SearchField): Def<T> {
    return this;
  }
  // Uncomment for the inference to work again
  // m(): Def<T> {
  //   return this;
  // }
}

// The extended class has to redeclare all methods, because it has a more
// concrete subtype (it has additional methods, not shown here)
declare class ExtendDef<T> extends Def<T> {
  setT<T>(t: T): ExtendDef<T>;
  a<U>(u: U): ExtendDef<T & U>;
  b<SubT extends T>(param: SubT): ExtendDef<T>;
}

const x = (new ExtendDef()).setT({x: "hello"}).a({y: "world"});

type DoesItExtend = typeof x extends Def<any> ? true : false;
type Inferred = typeof x extends Def<infer F> ? F : never;
assert<Equals<DoesItExtend, true>>;
// This errors, if you uncomment the m() method this will pass
assert<Equals<Inferred, {x: string} & {y: string}>>;
```

**Comment by RyanCavanaugh** [comment]
All uses of `T` in `Def` are self-referential or in constraint positions, so no

**Comment by xixixao** [comment]
What would make `T` not be those? How come uncommenting `m()` changes things? (sorry I'm not that familiar with the type-checking details)
