### ISSUE TITLE
Type not being inferred correctly in conditional operator that calls a function with a union return type

### ISSUE THREAD

**Issue by JeremyBernier** [microsoft/TypeScript#57036]
### 🔎 Search Terms

type inferred incorrectly function with return type of union
ternary operator, conditional operator
union type not being inferred correctly in conditional operator containing function with return type of union

### 🕗 Version & Regression Information

Seeing this on v5.3.3 as well as other versions

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBASg9gdygXigbygJ0QLigOwFcBbAIwkygF8BuAKFElkQEF8ATAYTgBsT8U6LLgIlymADRQAxr354iZCtTp0AZoXzTgASzgCA5hGAAVABY78BgBSWwhYArEUAlHngI2XOcQEAfZiQAoh4edDooSKgdNShbfHtgKAAeKAAGADoAZhcsY0JMARCeeijo2PjElPSMgFZczHzCoWwEPDTqUqjG4AKBDFb2qVk+X3bOuio6WXwAZyTMAEMOQQBZReAzDKWOOGJrF3oZ+eiEhzWNrZ32PYP6af0TzcsDQWtrqAA+GtqoADI-lAjKYLFZKg4XLk-AEAOQWGE0KAAeiRUAQZhAUBuEFmUGeuMY0HwcCSM2Ai0sgS83FG+AA-A85klnlYAExvD7fTK-AFA4zmF7g4CQqB0ulQOE6BHI1HozHYgkWAngIkkmT6cmUjzUnz0xlPUEGLKCTk-UV8kGCuwQqB4SXSlFojFYuA4vFKvEqghqskUgTajg0-gM47Mw0AFhNy3YXzN4uBArB1uFtotiZsydyiMdcpdbvxnqYxNJGr9VMDuoZ+pLmEa2kECcNQsOMvdOlx7fVtYg2mrXbrwHZqFN3P+gMbVrOwuzqILndk3e0QA

### 💻 Code

```ts
type Row = { row: number };
type RowAndColumn = { row: number, column: number }

function getThing(input: number): RowAndColumn | Row | null {
    if (input < 0.3) return null;
    if (input < 0.5) return { row: 0 };
    return { row: 0, column: 0 };
}
const rand = Math.random();
const input = Math.random();

const thing = (rand > 0.5 && getThing(input)) || 'hi'; // why does this type not contain RowAndColumn?
const thing2 = (rand > 0.5 && getThing(input)) ?? 'hi'; // why does this type not contain RowAndColumn?
const thing3 = rand > 0.5 ? getThing(input) : 'hi'; // why does this type not contain RowAndColumn?
const thing4 = rand > 0.5 ? getThing(input) : getThing(input) ; // why does this type not contain RowAndColumn?

const correct = getThing(input); // this is correct
const correct2 = rand > 0.5 && getThing(input); // this is correct
```

### 🙁 Actual behavior

It says the type of the `thing` variable is `Row | "hi"`

### 🙂 Expected behavior

The type of `thing` should be `RowAndColumn | Row | "hi"`

### Additional information about the issue

Also applies to ternary operators (see the 4 cases in the code)

Works as expected when there are no conditional operators.

**Comment by MartinJohns** [comment]
Look up "subtype reduction". Every `RowAndColumn` is also a `Row`, so the type gets simplified. It's working as intended.

**Comment by JeremyBernier** [comment]
I don't understand why this behavior would be desired, or how to fix this in a clean manner without writing additional redundant code or resorting to type assertion.

I suppose a simpler example is just the following

```
type Foo = { x: number }
type Bar = { x: number, y: string }

function f(arg: Foo | Bar) {
    const a = true ? arg : null // the type of a is Foo | null, instead of Foo | Bar | null which makes more sense
}
```

**Comment by rotu** [comment]
I hate this behavior too. It’s an interaction between distributivity and subsumption.

I think the easiest solution is to redefine `Row = {row:number, column?:undefined}` to prevent subsumption.
