### ISSUE TITLE
organizeImports needs to be called twice to be stable

### ISSUE THREAD

**Issue by iteriani** [microsoft/TypeScript#57030]
### 🔎 Search Terms

organizeImports

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because this seems to be a tooling issue.

### 💻 Code

```ts
import {abc, Abc} from 'b';
import {
  I,
  R,
  M,
} from 'a';
```

### 🙁 Actual behavior

This needs to be organized twice in order to be stable. The first time we get

import {I, M, R} from 'a';
import {abc, Abc} from 'b';

and the second time we get

import {I, M, R} from 'a';
import {Abc, abc} from 'b';

### 🙂 Expected behavior

I'd expect

import {I, M, R} from 'a';
import {Abc, abc} from 'b';

the first time around

**Comment by iisaduan** [comment]
I've investigated, and this behavior existed pre-5.3, and seems to be because `organizeImports` `s detection detects the first sort as case-insensitive, and the second sort as case-sensitive. I'm currently working on improving the detection, and currently, this issue can be manually avoided by adding
```
"typescript.unstable": {
     "organizeImportsIgnoreCase": true,
}
```
to your editor settings

**Comment by iisaduan** [comment]
@rubiesonthesky could you provide some more details about the cases you experience this on? I would like to make sure the issues are fixed with #57267

**Comment by iisaduan** [comment]
@rubiesonthesky If you've been unable to get a minimal repro, can you test this version in your repository? https://github.com/microsoft/TypeScript/pull/57267#issuecomment-1986700634

**Comment by iisaduan** [comment]
@rubiesonthesky To clarify, is that config the setting you already had? And how are you invoking `organizeImports`? (through VScode?)
>import {BehaviorSubject, Observable, forkJoin, of} from 'rxjs';

(also, with this case in particular, it is already sorted in a case-sensitive way so `case sensitivity = auto` *should* always tell that it is case-sensitive.)

Thank you for testing!
