### ISSUE TITLE
TypeConfusion between Object and Array when destructuring an Array

### ISSUE THREAD

**Issue by tobiasdcl** [microsoft/TypeScript#57048]
### 🔎 Search Terms

spread, destructuring, { ...[]} 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Destructuring

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.3#code/MYewdgzgLgBATgUwIYBsCCc5IJ4C4ZgCuAtgEYJwDaAujALwyUCMANDAExsDM1A3AFChIsAGZIA1ggxY8BEuSq0GAbxgA6DYlTScMAL4CA9IZimz5i5bMA9GAEkYAdxCEUAExgIAHgAcEwWAAVAGUYKBAYUGIfFCQASzAYJFIXWCgACziIGFJCURA4GAgQYgR4ZGLEuNg3EARssBAofkFwYpQENRQQAHMACgADACEkCAQPcDDsPwhgODifNOn6mAByLXRMHFWYLKTEpC3sHLzd7Ory1BRsAH4YABJlHWw1LOe+jeeASj0Br4EhO1Ot1+sNRuMYJMoMtZvNFlMZmsxJJnjs9kgDkcTrA9hcNtc7o9nq8IO9kVIjj8-gJ+J8jmofCAfH0vjBjE4CuIIPxycTGczWezALwbgFKdmC8+n8s4EJpJcWEMABOKTIA

### 💻 Code

```ts
const realArray: number[] = [1, 2, 3];
const fakeArray: number[] = { ...realArray };
//                        ^ I would expect TS to complain about this but for some reason it does not

console.log(`Based on typescript types 'realArray' is an array but is it really? ${Array.isArray(realArray)}`);
console.log(`Based on typescript types 'fakeArray' is an array but is it really? ${Array.isArray(fakeArray)}`);

realArray.pop() // works
fakeArray.pop() // 💥 fakeArray.pop is not a function 
```

### 🙁 Actual behavior

there is no TypeError when assigning `{ ...[]}` to a variable that is supposed to be an array based on the TS type

### 🙂 Expected behavior

I would expect a type error like `Type '{}' is missing the following properties from type 'number[]': length, pop, push, concat, and 26 more.` which happens when you try to assign `{ }` to a variable with an Array type

### Additional information about the issue

I hope this is no duplicate or that I am missing something obvious but I was not able to find something related to this specific issue

**Comment by MartinJohns** [comment]
Duplicate of #34780. Used search terms: `destructure object array in:title`

**Comment by tobiasdcl** [comment]
> Duplicate of #34780. Used search terms: `destructure object array in:title`

Sorry, my bad! 
Thanks 🙌
