### ISSUE TITLE
Infer async return types to avoid needing `Promise<T>`

### ISSUE THREAD

**Issue by scarletquasar** [microsoft/TypeScript#57043]
### ⚙ Compilation target

any

### ⚙ Library

any

### Missing / Incorrect Definition

It would be profitable for async methods to have inference to promise from a common return type.

### Sample Code

Before

```TypeScript

async function method(): Promise<number> {
    return await someService.getNumber();
}

ReturnType<typeof method> //Promise<number>
```

After
```ts
async function method(): number {
    return await someService.getNumber();
}

ReturnType<typeof method> //Promise<number>
```

**Comment by RyanCavanaugh** [comment]
#45387

**Comment by scarletquasar** [comment]
> #45387

> Our view of this is that async is an implementation modifier, the same way that parameter destructuring is -- from the outside, a caller has no legitimate reason to care if you wrote an async function or a regular function returning a Promise<T>. Type declarations in all places reflect that [non-]distinction

That is actually a syntax sugar. Not directly related on how it works since the transpiler will infer that if the method `N` contains the `async` keyword, then  the `Promise<T>` declaration can be changed to `T`. Keeping the necessity of declaring that the return type is a promise is unnecessary because it's intrinsic that **all** of the returns to an async function will be promises.

I don't remember if it is possible to use inheritances of Promise or implementations of PromiseLike instead of promise in async functions but I'm almost sure that it isn't, so, one more reason to disable the strict need for declaring promises directly as a return type of async functions.
