### ISSUE TITLE
`Expression expected` error in specific combination of object with specific name and documentation comment.

### ISSUE THREAD

**Issue by jan920** [microsoft/TypeScript#57041]
### 🔎 Search Terms

"Expression expected.", "TS1109", "async", "comment", "`Expression expected.`documentation comment"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about anything related to this

### ⏯ Playground Link

https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&target=3&ts=5.2.2&filetype=js#code/FAYw9gdgzgLgBAQygTwiOBeOBvAJmAZTAFsBTGACwEsIBzALjgAoEBKTAPhwQF8fhgSVCAB0+ImUo1aTYHHlwA9ACo4yxXIVN2GLth4AaYKwFC0YwiXLU6shUuWr1m+ds45Dx4EA

### 💻 Code

```js

const async = {doSomething: (a) => {a}}

async.doSomething(
    /* */
    () => {},
)

async.doSomething(
    /** */
    () => {},
)

```

### 🙁 Actual behavior

`Expression expected.` error is shown when a documentation comment and an object called async are combined.

### 🙂 Expected behavior

This kind of code does not show `Expression expected.` error.

**Comment by jan920** [comment]
Yeah, it's pretty specific. I'm turning on static type checking in a repository with callbacks (using `async` library) that has types defined in JSDoc and I got stuck on this.

**Comment by Andarist** [comment]
That's the kind of content I'm here for 😅 Nothing smells like an edge case bug in the evening.

**Comment by abrahamguo** [comment]
I have been working on this issue. So far I've discovered that the bug was not present in `2.4.0-dev.20170531` but was introduced in `2.4.0-dev.20170601`.

**Comment by abrahamguo** [comment]
I haven't verified, but almost certainly from [PR 16156](https://github.com/microsoft/TypeScript/pull/16156/files).
