### ISSUE TITLE
TSServer Plugins with sub-packages/paths are not loaded

### ISSUE THREAD

**Issue by kitten** [microsoft/TypeScript#57047]
### 🔎 Search Terms

"language server", "because only package name is allowed plugin name", "language server plugins"

### 🕗 Version & Regression Information

This behaviour must be going back to 4.2.2 as per #43124.

### 💻 Code

**tsconfig.json**

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "package/lsp"
      }
    ]
  }
}
```

### 🙁 Actual behavior

TypeScript rejects sub-path package plugins, as per:
- https://github.com/microsoft/TypeScript/blob/23faef92703556567ddbcb9afb893f4ba638fc20/src/server/editorServices.ts#L4490-L4493
- and; https://github.com/microsoft/TypeScript/blob/23faef92703556567ddbcb9afb893f4ba638fc20/src/compiler/moduleNameResolver.ts#L2525-L2531

**tsserver log**

```
Info 11   [15:52:00.931] Enabling plugin package/subpath from candidate paths: [...]node_modules/typescript/lib/tsserver.js/../../..
Info 12   [15:52:00.931] Skipped loading plugin package/lsp because only package name is allowed plugin name
```

### 🙂 Expected behavior

Plugins are loaded as per either `package.json:exports` with subfolders specified, or via `package/sub-path/package.json` or `package/sub-path/index.js`.

### Additional information about the issue

Related issues: #42688 and #42688.

If my understanding is correct, TypeScript only wants to allow packages that:
- have been installed via a package manager, so that opening VSCode without installing doesn't immediately run unauthorised code
- are not relative paths or local code that's checked into a repository

Neither applies to sub-packages. The use-case here is to publish packages that both provide code _and_ an LSP package in one, without splitting this into two packages because of the assertion in TypeScript.

**Comment by RyanCavanaugh** [comment]
PRs accepted, but this will need to be very carefully vetted. We might need some different syntax to disambiguate that `package` isn't interpreted by anyone to be a relative path

**Comment by kitten** [comment]
PR, as linked, is for the proposed change. Happy to of course make changes, if a different syntax is required, but currently, I’m assuming that the PR can for now represent behaviour without breaking the documented behaviour that a package name is expected, or how the [wiki](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) puts it:
> This name can only be an NPM package name.
