### ISSUE TITLE
Children (sub-class) cannot `override` the `extend` the `static const` of a base class. 

### ISSUE THREAD

**Issue by xeho91** [microsoft/TypeScript#57044]
### 🔎 Search Terms

- `class`
- `extends`
- `const`
- `override`

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAEDKAuB7YBraBvAUASAA4FcAjEAS2GgnjHjOgFkBJAOWgF5oAGaSaYRAO0oBuHAWK1K1WnQCCADTbQAjAH0O6tRvVcefQfBGiATongBTYOYAm0AG5gQ+MwC5o-fAFtCZo4ex7KI3xLRCMACntHFzdPbyMASgwcbHgACxIIADpIp0UcsxFsAF9MEswA+GgPEn4EZDR2OtRMxiYhaAB6DugAeQBpaABaAD5oeABPXDNoDM5ygQhEEDNMkEQAczD0KpqmtCL4w1BIGABFfDB+GgnoMwAPc34rGD2kvCJSckkaclbFJW4MAqfgqQRC4XyrncXh8iSw2GwEHwUwhDichxwJTK830O3450u13Gij2LWY7S60AAoncppYzDYJlMxohoN5lDjFstVhstniCVcSDcDkIgA

### 💻 Code

```ts
export class Stock {
	public static MIN = 0 as const;
	public static MAX = 1_000_000_000 as const;

	protected value: number;

	constructor(value: number) {
		this.value = value;
	}
}

const minStock = Stock.MIN; // OK -> type is 0


export class Quantity extends Stock {
	public static override MIN = 1 as const;

	constructor(value: number) {
		super(value);
	}
}

const minQuantity = Stock.MIN; // Expected type to be 1

```

### 🙁 Actual behavior

```txt
Class static side 'typeof Quantity' incorrectly extends base class static side 'typeof Stock'.
  Types of property 'MIN' are incompatible.
    Type '1' is not assignable to type '0'.
```

### 🙂 Expected behavior

When using `override` keyword _(in `static MIN` of the sub-class `Quality`)_,\
I expect it to override the `const` _(of `static MIN`)_ in base class _(`Stock`)_ as well.

**Why?**

Might be just me, but it sounds more intuitive. I'm not experienced enough to know if this works as intended or is impossible by design.

**Regardless** the `MIN` of `Quantity` outputs:

- ~~in compiled **TypeScript**  _(with abuse of the `@ts-ignore`)_ code: `0` -> see [playground](#playground-link))~~ **EDIT**: _irrelevant, I made a typo, see: https://github.com/microsoft/TypeScript/issues/57044#issuecomment-1890340527)_
- **in JavaScript _(without types)_ it outputs: `1`** -> MDN Playground: https://developer.mozilla.org/en-US/play?id=MV4u%2F9KISLVk5YGr6MbUJ2eWR6IVOisL47dMB0FdIv5sE%2FWDfVBm57rd2qSjH%2BL7pTax8A2jrkaIBFpW

**Comment by fatcerberus** [comment]
This is intentional, because `0 as const` causes the property to be typed as literal `0`, to which literal `1` is not assignable.  It also has nothing to do with `static`: you get a similar error if these are instance properties.

> in compiled TypeScript (with abuse of the `@ts-ignore`) code: `0`

No, it prints `1`, just like the MDN example.  There's a typo in your TS code: you're printing `Stock.MIN` instead of `Quantity.MIN`.  TypeScript doesn't change the behavior of your code, even if there are type errors.

**Comment by xeho91** [comment]
> This is intentional, because `0 as const` causes the property to be typed as literal `0`, for which literal `1` cannot be substituted (and therefore `Quantity` is not a valid subtype).  It also has nothing to do with `static`: you get a similar error if these are instance properties.
> 
> > in compiled TypeScript (with abuse of the `@ts-ignore`) code: `0`
> 
> No, it prints `1`, just like the MDN example.  There's a typo in your TS code: you're printing `Stock.MIN` instead of `Quantity.MIN`.  TypeScript doesn't change the behavior of your code, even if there are type errors.

Thanks!

I guess that closes the issue, as this intended behaviour. I trust your expertise.
