### ISSUE TITLE
Missing RegExp#unicodeSets

### ISSUE THREAD

**Issue by Josh-Cena** [microsoft/TypeScript#57055]
### ⚙ Compilation target

ESNext

### ⚙ Library

ESNext

### Missing / Incorrect Definition

Missing `RegExp#unicodeSets` property

### Sample Code

```TypeScript
/[a]/v.unicodeSets
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets

**Comment by fatcerberus** [comment]
tc39: *uses meaningless letter `v` because "it's just `u` but better"*
also tc39: *calls corresponding property `unicodeSets` implying it's an additional feature rather than just an enhanced mode*

**Comment by Josh-Cena** [comment]
> implying it's an additional feature rather than just an enhanced mode

There are incompatibilities. It's not a strict superset of any existing feature. You can read the linked documentation to see what changed.

**Comment by fatcerberus** [comment]
Yeah, I get that, but `unicodeSets` implies it's supplemental, i.e. that `v` is something you specify *in addition to* `u`.  At least the weird "we called it `v` because it's `u`+1" reasoning adequately explains why they're mutually exclusive.  The naming scheme here is just weird.

**Comment by Josh-Cena** [comment]
There were discussions about whether `v` should still make `unicode` be true but it was eventually decided otherwise. Anyway that's pretty tangential
