### ISSUE TITLE
consider allowing to specify the exact file instead of a folder that has a tsconfig.json

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5705]
seriously, each tsconfig.json has to have its own folder in order to be referenced with `--project` parameter

- **What if I need 2 projects based on the same set of files?**

**Comment by RyanCavanaugh** [comment]
This would be really nice.

**Comment by DanielRosenwasser** [comment]
Behold, ask and ye shall receive a ~2 month old pull request from @SaschaNaz which incredibly has absolutely no merge conflicts right now: #4883

Also that sort of makes this a duplicate of #2869, though I'm leaving this open for the sake of discussion.

**Comment by aleksey-bykov** [comment]
Since `--project` is taken already I suggest the `--configuration` parameter

**Comment by mhegazy** [comment]
this is a duplicate of  #2869. we should revive  #2869 as well as #4883
