### ISSUE TITLE
Wrong control flow analyse.

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#57063]
### 🔎 Search Terms

"control flow analyse"

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______
TS 5.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAYgTgQwOYFsIDthQLxQN4BQUUokAXFAOQBuAlgCYQD2lANEVAB4XoCuKAIwhwoAHyi90jAGa10EegQC+Y-B1IQKlYBE7A263cAAyEacB78hcZasLENWsLQDGwXnAiUO3KH0HCqpIycgrKBAQuTOgAzljSFPDIaJg4+CoIMVAI6CAR0pJutNFQKAhyABQAlBTUTAxqxLTSUBXSAHQaONi4NAzMlFAAZENQHZzduMFmofRVjcRQnu5w6BwqHM2tHV09vc5uHl7Do+OTElIz8nMLxMsea8RKmy1tneDQAIQ9VDp6lPN7IsorEsBNcOMOMQAPTQqAAC2E0GAiJIHygTBaExi8KYvAANvQMeh8SAoEI-FZhKxybwsLR9Fl-NYgpdZNc-EwAO7tdbKIA

### 💻 Code

```ts
type Fragment = {
  type: 'video',
  x: number | undefined
} | {
  type: 'text',
  textLeft: number
} | {
  type: 'picture'
  x: number | undefined
}

const f: Fragment = {} as any

function main(): void {
  if (f.type === 'video' && f.x === undefined) {
    return
  } 
  if (f.type === 'picture' && f.x === undefined) {
    return
  }
  if (f.type !== 'text') {
    const x = f.x // line 22 is here
    // here the type of x should only be number, but it's number | undefined now.
  }
}
```

### 🙁 Actual behavior

In line 22, the type of x is number | undefined.

### 🙂 Expected behavior

It should only be number because it is already be narrowed before and not be reassigned again. I know that i can assign the f.x to a const variable `fx` and then narrow the variable `fx` as a workaround.

**Comment by fatcerberus** [comment]
> TypeScript doesn't perform this kind of analysis.

Obligatory link to https://github.com/microsoft/TypeScript/issues/52822#issuecomment-1434989002
