### ISSUE TITLE
Different behavior when using a type as is, or as a type alias

### ISSUE THREAD

**Issue by ehmicky** [microsoft/TypeScript#57062]
### 🔎 Search Terms

type alias
extends array
different behavior

### 🕗 Version & Regression Information

This was introduced by [version `4.2`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/), and continues as of today (version `5.3`).

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAggPAFQHxQLxQN4EMBcUFQQAewEAdgCYDOUwATgK4QDaAulAPy2PR4BmWADZUIAXwDcAWABQM0JCgAhNLDj0mbJOKgB6HZlzcmoueGgBhFfABGAe1uCIWMpu16D-ISJPT50ACJWajyahCTk1FCWXOq8UALCEG76AAYJIikANFAA7gAWAJYAxnlQBTRFtnR0EEXApgoAokGxocSklDQ29o7OoTE8UJ6JyVApsVm5hSVlNAVkldW1wEA

### 💻 Code

```ts
type A<T> = {a: T extends true[] ? true : false};

type B = A<true[]>; // {a: true}
type C = A<boolean[]>; // {a: false}
type D = A<true[]> extends C ? true : false; // `false`, which is correct
type E = A<true[]> extends A<boolean[]> ? true : false; // `true`, which is incorrect
```

### 🙁 Actual behavior

The types `D` and `E` have different values.

### 🙂 Expected behavior

The types `D` and `E` should have the same value since they are identical, except for one using a type alias.

**Comment by fatcerberus** [comment]
Looks like a variance measurement issue (`A` is erroneously measured as covariant)

**Comment by ehmicky** [comment]
Thanks @fatcerberus. I can confirm this,as the following code works:

```ts
type A<in T> = {a: T extends true[] ? true : false};
```

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/48070

**Comment by ehmicky** [comment]
Thanks @whzx5byb and sorry for the duplicate. Closing in favor of #48070.
