### ISSUE TITLE
Value collisions in string enums result in contradictory typings

### ISSUE THREAD

**Issue by LoeschMaximilian** [microsoft/TypeScript#57065]
### 🔎 Search Terms

"enum"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Enums

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAUwdgrgtgBAsiAzoghgcyTA3sGeYASAogDIkDyMAvDAEQBGAniLcAL6iSwLLqY74YAIQCaRanSYt2wAMYB7MIgAuMWRJ6oMiAHSiiAbmBA

### 💻 Code

```ts
enum Messages {
    HELLO = "bye"
}
enum Messages {
    BYE = "bye"
}
const c = Messages.BYE;
```

### 🙁 Actual behavior

declarations
``` ts
declare enum Messages {
    HELLO = "bye"
}
declare enum Messages {
    BYE = "bye"
}
declare const c = Messages.HELLO;
```

### 🙂 Expected behavior

declarations
``` ts
declare enum Messages {
    HELLO = "bye"
}
declare enum Messages {
    BYE = "bye"
}
declare const c = Messages.BYE;
```

### Additional information about the issue

I was experimenting with using a global enum to differentiate messages from a message broker like the BroadcastChannel browser API. I was hoping to get compile-errors when a string enum gets expanded by a key with an already present value. It makes sense, that there is no error at compile-time, but the result should at least be consistent between the JavaScript and .d.ts results.

The idea relates to #53013

**Comment by RyanCavanaugh** [comment]
This behavior is still correct; the values are considered interchangeable and are effectively aliases for each other.
```ts
// Not an error
const c: Messages.HELLO = Messages.BYE;
```
