### ISSUE TITLE
Bug that kill TypeScript build time

### ISSUE THREAD

**Issue by nisimjoseph** [microsoft/TypeScript#57075]
### 🔎 Search Terms

"long time", "stuck build"

### 🕗 Version & Regression Information

- Occur on all versions.

### 💻 Code

```ts

export type HtmlAnchorTarget = '_self' | '_blank' | '_parent' | '_top';

type CssAbsoluteUnit = 'cm' | 'mm' | 'in' | 'px' | 'pt' | 'pc';
type CssRelativeUnit = 'em' | 'ex' | 'ch' | 'rem' | 'vw' | 'vh' | 'vmin' | 'vmax' | '%';

export type CssLength = `${number}${CssAbsoluteUnit | CssRelativeUnit}`;
export type CssMargin = CssLength | `${CssLength} ${CssLength}` | `${CssLength} ${CssLength} ${CssLength} ${CssLength}`;
```

### 🙁 Actual behavior

the build time grow exponential because of the amount of permutations we have and it Stuck the IDE completely and make the TSC to take 4-5x more build time.

### 🙂 Expected behavior

run faster

### Additional information about the issue

just change the line:
``` ts
export type CssMargin = CssLength | `${CssLength} ${CssLength}` | `${CssLength} ${CssLength} ${CssLength} ${CssLength}`;
```
to:
``` ts
export type CssMargin = CssLength | string;
```

and all run fast.

**Comment by nisimjoseph** [comment]
You are right, this is not a defect or a bug.
We discovered that today, but the issue is we didn't know about it until we tracked back in all the code for the last 2 weeks, and it lot of code.
it was good to have some kind of warning in the compile time to note there is a potential issue with X that can cause a long build time, or something like that.

**Comment by nisimjoseph** [comment]
so the threshold is 50k and we reach to little lower. ok.
can we config this threshold? 50k is too much and pretty kill the compiler time.

**Comment by MartinJohns** [comment]
It's not configurable, and likely won't be: https://github.com/microsoft/TypeScript/pull/44997#issuecomment-900595879

**Comment by nisimjoseph** [comment]
10x for the data.
