### ISSUE TITLE
[Windows][git clone] Filename too long

### ISSUE THREAD

**Issue by AaronNGray** [microsoft/TypeScript#57079]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

error: unable to create file tests/baselines/reference/tsserver/configuredProjects/Open-ref-of-configured-project-when-open-file-gets-added-to-the-project-as-part-of-configured-file-update-buts-its-open-file-references-are-all-closed-when-the-update-happens.js: Filename too long

fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

```
C:\Users\Nathaniel\GitHub>git clone https://github.com/microsoft/TypeScript.git
Cloning into 'TypeScript'...
remote: Enumerating objects: 655240, done.
remote: Counting objects: 100% (871/871), done.
remote: Compressing objects: 100% (478/478), done.
remote: Total 655240 (delta 498), reused 631 (delta 350), pack-reused 654369Receiving objects: 100% (655240/655240), 2.30 GiB | 8.72 MiB/s
Receiving objects: 100% (655240/655240), 2.31 GiB | 8.66 MiB/s, done.
Resolving deltas: 100% (444181/444181), done.
error: unable to create file tests/baselines/reference/tsserver/configuredProjects/Open-ref-of-configured-project-when-open-file-gets-added-to-the-project-as-part-of-configured-file-update-buts-its-open-file-references-are-all-closed-when-the-update-happens.js: Filename too long
Updating files: 100% (70682/70682), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by MartinJohns** [comment]
Essentially a duplicate of #38998.

Also see this comment: https://github.com/microsoft/TypeScript/issues/45051#issuecomment-880995566  
Do you have `core.longpaths` enabled?

**Comment by AaronNGray** [comment]
> Essentially a duplicate of #38998.
> 
> Also see this comment: [#45051 (comment)](https://github.com/microsoft/TypeScript/issues/45051#issuecomment-880995566) Do you have `core.longpaths` enabled?

@MartinJohns  Sorry, I did do a quick issue search but on the main error not the actual cause !

In Windows Admin terminal do :-

```git config --system core.longpaths true```
