### ISSUE TITLE
import.meta.dirname is missing

### ISSUE THREAD

**Issue by adaboese** [microsoft/TypeScript#57078]
### 🔎 Search Terms

Property 'dirname' does not exist on type 'ImportMeta'.ts (2339)
Property dirname does not exist on type 

### 🕗 Version & Regression Information

N/A

### 💻 Code

```ts
import.meta.dirname
```

### 🙁 Actual behavior

Expect not to throw an error

### 🙂 Expected behavior

Receiving an error

### Additional information about the issue

TS config:

```json
"module": "NodeNext",
"moduleResolution": "NodeNext",
"target": "ESNext",
lib": [
  "ESNext"
],
```

This feature has been in node.js since https://nodejs.org/en/blog/release/v20.11.0

**Comment by xiBread** [comment]
This isn't a TS lib concern. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68157
