### ISSUE TITLE
null and undefined extends T inconsistency on array (works for primitive and object).  

### ISSUE THREAD

**Issue by olivier-spinelli** [microsoft/TypeScript#57083]
### 🔎 Search Terms

null undefined extend array generic parameter

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about extends

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTAEBUEMCcHMFMAuoCWBnUlQG8C+pEALSZAdxQBsLRiA3eUAIgDtGAuSZgT1AApp4aAA4A6JgBN2nLgEpQQ6AHsh8aIh4oAZhFQYAcgHlwoZgFcqkAEYUG-QaNCHjp5uPiaUzeOJljQAKHUVUABBISEKLj1zCisbAB5wABooOCQAPlAAXhMY0HgAD0R4VwxjAH4IGARkNiq0xAAybBYpblwAbkCuYLCIrgBVV3dPb0SU6ozs0Bc3Dy9xfKKS8TLQStSa0DrNpGbGSQ52rqCGPsjx3cRMnPPB4fmx5Lvoi2t4S8nr9K7QP4D-CBQAAJeAUFTQUCaRSQ06gWjoUyQCgoABeJBQimYfn+-k0LgAxohMcwIIl0rwZNhQAJEKZoKS8Jgyh1QLh-ICwAB1GEAawwkAwhRURO8In8BKxaGQ0shfxy4Hid3iss8sCS2GK0rYAEZcOkKTJWUDNYJkEkTBbxOzJcxpaBZXp5WTlarmLAAD5mKgarWIXX6w3GsCm6VWm1SmWIaADZ2K13RtUe2YjBa+s0Bg2U4M4P0W5gRu1RmNOhVK8IXN2elOPcRemLp7V6rNG0Amv2F+2O2NlhPQJPeijJh6jcSN-3NoNtkMdjlAgDKSHiim0pGIxXo0Ey6FAiksCMUpjQkRMimQg7iDE4i2YZ5mI4WYglkYdSH+cfL-Xii8QKsT7vScdMyndszVAfNw2fItX0QAxNCdaZ4wrLhvyXKt6yoQDQwnQNs2nXMwIg0BrSgrskDg2NEM-C4fz-ft3WHOZRywv1gLw0D7SIkjbTI2DNAGUsXWQ1Df3QmtRwwigWIzSd2JnQjLWI9lOVCaBoEgFCV1ANcSHgTdMk0SBKAwABbdBVDiLg6kYHSN1URhQBMkhimgNAAEIVNAABaUAuRQIhd2YE8sQYQdgHEhZ7xJAhCB3Ug+TQcUeOQGB1J4d9e2EqsAG0AF0gNk1sOPNRTuJfVKNLghDMq-dDBzygrcKK+TONKzsUrUyr+I-Pskwi7wGuwtjmoI1rmEgzyfIAIVMMh-MIAh4tyKhwofbwoqxVBkEM4yRD20iOrSijBKQ2r-2rNa63q-KhsKnNsPAkw2U8v4QlcGKGEseA6ExSEdzcAlYnU4lNphNxITcFRhmYRAPOSzBOq4KqeyEs76M9QdGNTAabtYu78Ieq1nv8IA

### 💻 Code

```ts
// Target is a {} that will have "n":any (resp. "d":any) property if T is NOT nullable (resp. NOT undefined).  
type ApplyNullable<T,Target> = null extends T ? Target : Target&{"n":any};
type ApplyUndefined<T,Target> = undefined extends T ? Target : Target&{"d":any};
type Apply<T,Target> = ApplyUndefined<T,ApplyNullable<T,Target>>;
    

// Helper for type visualization.     
function T<T>(){ return {} as T; }

// Works as expected.
const str   = T<Apply<string,{test:1}>>(); // {test , n, d}
const strN  = T<Apply<string|null,{test:1}>>(); // {test, d}
const strU  = T<Apply<string|undefined,{test:1}>>(); // {test, n}
const strUN = T<Apply<string|undefined|null,{test:1}>>(); // {test}
const strNU = T<Apply<string|null|undefined,{test:1}>>(); // {test}

// Set<of whatever> is obviously not nullable and not undefined. 
const set     = T<Apply<Set<string>,{test:1}>>(); // {test , n, d}
const setOfN  = T<Apply<Set<string|null>,{test:1}>>(); // {test , n, d}
const setOfU  = T<Apply<Set<string|undefined>,{test:1}>>(); // {test , n, d}
const setOfUN = T<Apply<Set<string|undefined|null>,{test:1}>>(); // {test , n, d}

// Array<of whatever> fails miserably: "whatever" matters!
//  - With only one null/undefined union this works.
const array     = T<Apply<string[],{test:1}>>(); // {test , n, d}
const arrayOfN  = T<Apply<string|null[],{test:1}>>(); // {test , n, d}
const arrayOfU  = T<Apply<string|undefined[],{test:1}>>(); // {test , n, d}

//  - But with two null/undefined union it fails...
const arrayOfUN = T<Apply<string|undefined|null[],{test:1}>>(); // {test , n }
//    And the behavior is declaration order dependent!
const arrayOfNU = T<Apply<string|null|undefined[],{test:1}>>(); // {test , d }
```

### 🙁 Actual behavior

This simple type mapper fails on Array while working on a primitive and object (here a Set to "look like" an array).
What is really worrying is that the behavior changes depending on the order of the union type declaration: `string|null|undefined[]` doesn't lead to the same (bad) result as `string|undefined|null[]`.   

### 🙂 Expected behavior

Any `X[]` should produce the same type.

### Additional information about the issue

There may be to be 2 issues here:
- First, why is the `|null` or `|undefined` of the **item's** array impacts the resulting type?
- Second, given this impact, why does the declaration order have side effect?

**Comment by MartinJohns** [comment]
> `string|null|undefined[]` doesn't lead to the same (bad) result as `string|undefined|null[]`.

Can you elaborate why it should? The one union includes an array of `undefined`, the other includes an array of `null`. Why should they be treated the same?

I'm not sure if you're aware that `string | number[]` and `(string | number)[]` are completely different types. The first is either a `string` or a `number` array (a union type), while the second is an array that contains `string`s and `number`s (not a union type).

**Comment by olivier-spinelli** [comment]
> The [] binds stronger than the |.
Oh My!!!
How could I missed that, I lost one day on this one... 
I'm feeling sooooooo stupid! Closing this stupidity right now!
