### ISSUE TITLE
TouchEvent on() handlers in "lib.d.ts"

### ISSUE THREAD

**Issue by GoToLoop** [Microsoft/TypeScript#5708]
Diff. from any other event handler in "lib.d.ts", the 4 [**_TouchEvent_**](https://developer.Mozilla.org/en-US/docs/Web/API/TouchEvent) callbacks are merely declared as `any`:
```ts
declare var ontouchcancel: any;
declare var ontouchend: any;
declare var ontouchmove: any;
declare var ontouchstart: any;
```

They should be declared this way instead:
```ts
declare var ontouchcancel: (ev: TouchEvent) => any;
declare var ontouchend: (ev: TouchEvent) => any;
declare var ontouchmove: (ev: TouchEvent) => any;
declare var ontouchstart: (ev: TouchEvent) => any;
```

**Comment by mhegazy** [comment]
PRs are welcomed. Here is some information about contributing lib.d.ts fixes: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by DanielRosenwasser** [comment]
I think those should return `void``

**Comment by GoToLoop** [comment]
* I was just following the model which was already there.
* That is, all event handlers are declared as returning `any`.
* Therefore if we change 1 of them to `void`, all of the rest gotta follow suit as well.
* However, any "ontype" handler callback can indeed return `false` in most cases as replacement for **preventDefault()** method or `ev.returnValue = false`.
* Therefore I believe most correct returning type is `boolean`. Or at least `void | boolean`.

http://www.QuirksMode.org/js/events_early.html
