### ISSUE TITLE
GetReferencesAtPosition in ObjectBindingPattern on BindingName fails

### ISSUE THREAD

**Issue by JoviDeCroock** [microsoft/TypeScript#57094]
### 🔎 Search Terms

LSP Plugin, TSServer, ObjectBindingPattern, GetReferencesAtPosition 

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://github.com/0no-co/GraphQLSP/issues/187#issuecomment-1899544136

### 💻 Code

The following happens on the `data` binding-name of the second snippet

```ts
  const references = info.languageService.getReferencesAtPosition(
    source.fileName,
    node.getStart()
  );
```

```ts
 const { data, loading, error, refetch } = useQuery(Query)
```

We follow the reference of Query to the invocation, see it's an object-destructuring and follow all the binding-names to collect access patterns. I have noticed before that we had to use `node.getStart()` rather than `node.pos` else TS would not find anything, however this is just a straight up crash 😅 

### 🙁 Actual behavior

Crashes within tsserver on 

```
    TypeError: Cannot read properties of undefined (reading 'escapedName')
        at getTypeForVariableLikeDeclaration (/home/banks/Development/beep/node_modules/typescript/lib/tsserver.js:56154:39)
```

### 🙂 Expected behavior

This to follow the reference correctly.

### Additional information about the issue

I am terribly sorry that this is on a real project, I could not find good ways to reproduce issues with LSP plugins yet...

**Comment by Andarist** [comment]
The problem is that a symbol is read from a declaration in JSDoc function type and those don't have symbols and it leads to a crash. I'm still working on reproducing this in isolation.

**Comment by Andarist** [comment]
test case:
```ts
/// <reference path='fourslash.ts' />

// @moduleResolution: node

// @Filename: node_modules/use-query/package.json
////{
////  "name": "use-query",
////  "types": "index.d.ts"
////}
// @Filename: node_modules/use-query/index.d.ts
////declare function useQuery(): {
////  data: string[];
////};

// @Filename: node_modules/use-query/package.json
////{
////  "name": "other",
////  "types": "index.d.ts"
////}
// @Filename: node_modules/other/index.d.ts
////interface BottomSheetModalProps {
////  /**
////   * A scrollable node or normal view.
////   * @type null | (({ data: any }?) => any)
////   */
////  children: null | ({ data: any }?) => any;
////}

// @Filename: src/index.ts
////import { useQuery } from "use-query";
////const { /*1*/data } = useQuery();

verify.baselineFindAllReferences('1');
```
