### ISSUE TITLE
ClassFieldDecoratorContext has addInitializer method which is not part of the spec.

### ISSUE THREAD

**Issue by phiresky** [microsoft/TypeScript#57096]
### 🔎 Search Terms

ClassFieldDecoratorContext, addInitializer, decorators, undefined

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (5.04 up to nightly), and I reviewed the FAQ for entries about decorators

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20240119#code/GYVwdgxgLglg9mABAIwIYCcAUB9AXI1MATwBpFoAPfAYQBtUBnBgMRgFNaATAETYjnSooA6gihsKUAJSIA3gChE5BAzi02AOlpwA5pgBEDABZwQXFG0ThObYDDBtO+spQ2pOnAJJgYsVLRgALzZ0KQBueQBfeQh6JkRmODg5RUQAATR0FFRAxABeRABGKKA

### 💻 Code

```ts
function bar(_: any, ctx: ClassFieldDecoratorContext) {
  console.log("should be undefined", ctx.addInitializer);
}
class Foo {
  @bar baz = 1
}
```

### 🙁 Actual behavior

addInitializer is a function and ClassFieldDecoratorContext defines it as such

### 🙂 Expected behavior

`should be undefined undefined` + a typescript compile error because it's wrong code

### Additional information about the issue

This is problematic because babel apparently follows whatever typescript does so it does work there, but swc follows the spec so code breaks there. For example, mobx works when compiling with tsc but breaks with swc: https://github.com/mobxjs/mobx/issues/3817

Here's excerpts from the spec:

https://github.com/tc39/proposal-decorators

> ```ts
> type ClassFieldDecorator = (value: undefined, context: {
>   kind: "field";
>  name: string | symbol;
>  access: { get(): unknown, set(value: unknown): void };
>  static: boolean;
>  private: boolean;
>}) => (initialValue: unknown) => unknown | void;
> ```
>
> **Since class fields already return an initializer, they do not receive addInitializer and cannot add additional initialization logic.**

**Comment by rbuckton** [comment]
All current decorators, including class fields, support `addInitializer`. The explainer text is out of date compared to the actual specification text at https://arai-a.github.io/ecma262-compare/?pr=2417. 

As you can see from [CreateDecoratorContext](https://arai-a.github.io/ecma262-compare/?pr=2417&id=sec-createdecoratorcontextobject), `addInitializer` is attached unconditionally on step 12:

![CreateDecoratorContext algorithm steps](https://github.com/microsoft/TypeScript/assets/3902892/da66de6f-844a-4e9a-8563-a617ef26510f)

**Comment by phiresky** [comment]
Ah. Thanks, then I'll open an issue with swc instead.

**Comment by rbuckton** [comment]
You may also want to open an issue or PR on the proposal repo to fix the explainer.

**Comment by phiresky** [comment]
Good idea, opened an issue.
