### ISSUE TITLE
TS2362 - Error when doing arithmetic operations on date 

### ISSUE THREAD

**Issue by erichillah** [Microsoft/TypeScript#5710]
Hi, 
The following valid js code compile with TS2362 error 
```typescript
let start = new Date();
let elapsed = new Date() - start;
``` 

```
index.ts(9,22): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
index.ts(9,37): error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
```
To avoid the error i need to explicitely cast opreands wit `<any>`.

**Comment by weswigham** [comment]
Duplicates #2361 since this works because `valueOf` a `Date` is a `number`.

**Comment by weswigham** [comment]
BTW, a canonical workaround (and generally safer thing to do) is this:
```ts
let start = +new Date();
let elapsed = +new Date() - start;
```

Unary `+` will coerce to string.

**Comment by erichillah** [comment]
Thanks, I've checked #2361 and didn't know all that about the `Date` object. Happy enough with the unary `+` operator.
Closing this issue.
