### ISSUE TITLE
Quickinfo displays `any` in TS files within JSDoc comments

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#57108]
### 🔎 Search Terms

quickinfo jsdoc ts any 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20240120#code/PQKhAIAEBcE8AcCm4DeAKAlOAvAPleACYCG0xAXOAM7QBOAlgHYDmA2gLrgC+X4IwAKABmAV0YBjaPQD2jcNEQ1MlFEVIVqdJm068UA8OFqJoI2nP2HDJMpQ4AaA9wDcArgIGgIkY6fNVUVRsNGgYWDm5efmExSRk5BRoAJmUCYMpQ7Qi9J18zCydrdTt2R0MuV3dPMCg4JEDwACNiWgytFmdIvkFxWRp5RWgAZhwCZtbwAHJJ7g8gA

### 💻 Code

```ts
/** @type {() => { data: string[] }} */
function test(): { data: string[] } {
  return {
    data: [],
  };
}

/** @returns {{ data: string[] }} */
function test2(): { data: string[] } {
  return {
    data: [],
  };
}

/** @type {{ bar: string; }} */
const test3 = { bar: '' }
```

### 🙁 Actual behavior

When hovering over any of those properties in the JSDoc comments we get a useless quickinfo mentioning `any`

### 🙂 Expected behavior

I'd expect those quickinfos to not be displayed at all in TS files

**Comment by fatcerberus** [comment]
That's super weird since I thought TS just didn't parse JSDoc type info at all in `.ts` files, but clearly it's done enough work to know `data` and `bar` are things that should have types.
