### ISSUE TITLE
Spread operator cannot be typed with intersection type

### ISSUE THREAD

**Issue by reverofevil** [microsoft/TypeScript#57100]
### 🔎 Search Terms

`intersection spread`

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because there is no online bisect tool for that, and git clone of TS repo doesn't work on Windows

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgUwE4HMEwLwwDwEEA0MAQgHwAUAhgFwwEwBGNRAlJiTGQN4B0vFhvbvQC+zANwAoCaEiwArphicAHjTKsM7AORbhkmdBgA3RSrUb2ABj3TwhgO6nVHCzChI5CG7dkxlixFQEMjlCQLQyI0J7ZmZuZXVJAHokv24oEAAZEHtkAGEKCHQASwgYMBBYChgAMzkwYChi8B8IEAAbBG52kBQyZXSsnPzC4NixIA

### 💻 Code

```ts
const merge = <A, B>(a: A, b: B) => ({...a, ...b});

const u = {x: () => ''};
const v = {x: () => 0};
const w = {x: () => true};

const x = merge(u, merge(v, w)).x();
// x.toLowerCase is not a function
console.log(x.toLowerCase());
```

### 🙁 Actual behavior

TS doesn't see any kind of an issue with the code

### 🙂 Expected behavior

Property 'toLowerCase' does not exist on type 'boolean'

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/issues/50185#issuecomment-1205549273

**Comment by reverofevil** [comment]
@RyanCavanaugh It links a suggestion/feature request, and this one is surely a bug. Can we mark that one as bug, or unduplicate this one?

**Comment by RyanCavanaugh** [comment]
Correctly representing this requires a new feature. Missing features aren't bugs - there's no straightforward way to just "fix" this without that feature.

**Comment by reverofevil** [comment]
It doesn't, really. The type is `Exclude<A, keyof B> & B`, modulo other bugs in intersections' implementation.

**Comment by RyanCavanaugh** [comment]
That doesn't correctly handle optional properties.
