### ISSUE TITLE
Function sum type inference broken, requires convoluted workaround

### ISSUE THREAD

**Issue by paskozdilar** [microsoft/TypeScript#57120]
### 🔎 Search Terms

function argument sum type

### 🕗 Version & Regression Information

v5.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAShDOBXANsAwgQ2cgRhgxgNYA8AKgHxQC8UAFAFBR0QBOLA9iwFxQCibnADRQWCFMB6IAdgBMIAMwCWUiDICU1SgDd2imfQ0AfOo2YDuUKSmTDRSVD1Iaq23frUBuevVCRYY1ExsPCI0dikdZERgVTJKGlpWDgt+ZKhjK2xbAIkoAH0ACQhkSBZScAgyYV8IdnkoJM5yZ1c9Lxr8opLWcsgqqABpBoAPGNl4PnN0y2t4wZGxmQnUzigAfihpOSUVGShHL295aXxgRXCoGPhgOHt0LFwCQlp8HB5b8SDHomIrAFscKxmlAAN6mV60FQAd0myVoAHJGix4WphFsFMpVJ4oAB6HFQACCLAA5og-hApMAoHVLhUoPCVsioIoJlJ2FSMPB4IpiVIMDhkNBgOwoGAMCwMOSYixqfUOvCVFpWPCAHS0ABMAGYACwAVjU4JwkOswm16uxeMJJLJFKpNPlmWQ8OZrPZUE53N5-MFlxFYolUtYstpfgVECVyLVWr1BoAvkcTmcLlcbjkviFCGEIuwojEZC83v47umnlnItFYv9ASxgWCmBDobDOAikSi0bIMbsLfiwn8wIpBRMdhBDcaslAzd2oL3+4OoMP6LGgA

### 💻 Code

```ts
type ResultCallback<T> = (
  (error: Error, result: undefined) => void
) | (
  (error: null, result: T) => void
);

type ResultCallbackConvoluted<T> = (error: Error | null, result: _HelperType<T, typeof error>) => void;
type _HelperType<T, K extends Error | null> = K extends Error ? undefined : T;


function testResultCallback(cb: ResultCallback<number>) {
  cb(new Error('error'), undefined); // Argument of type 'Error' is not assignable to parameter of type 'never'.(2345)
  cb(null, 42); // Argument of type 'null' is not assignable to parameter of type 'never'.(2345)
}

function testResultCallbackConvoluted(cb: ResultCallbackConvoluted<number>) {
  cb(new Error('error'), undefined); // Compiles fine
  cb(null, 42); // Compiles fine
}
```

### 🙁 Actual behavior

Code refuses to compile because TypeScript infers the type of first argument of `ResultCallback`  as `never`.

### 🙂 Expected behavior

Code compiles, because the `ResultCallback` specifies exactly the same type as `ResultCallbackConvoluted`, which compiles properly.  

### Additional information about the issue

I ran into this problem while working with `ts-protoc-gen` gRPC library, so this type of code is already used in the wild.

**Comment by ritschwumm** [comment]
i don't think `testResultCallback` should compile:
* assuming ResultCallback is actually a `(error: Error, result: undefined) => void` then calling it with ` cb(null, 42)` would be wrong,.
* assuming ResultCallback is a `(error: null, result: T) => void` then calling it with `cb(new Error('error'), undefined)` would be wrong

**Comment by jcalz** [comment]
There's no TS bug here, unions of functions can only be safely called with intersections of arguments (as supported since [TypeScript 3.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-3.html#improved-behavior-for-calling-union-types)).  Maybe you want an intersection of functions instead? Or a single function which accepts a discriminated union of rest arguments ? But either way TS is behaving as intended.

**Comment by fatcerberus** [comment]
Yeah, `ResultCallbackConvoluted` and `ResultCallback` are not equivalent.  The former describes a function that can accept either `Error` or `null` while the latter describes either a function that only accepts `Error` *or* a function that only accepts `null` but you don't know which one it is.  Contravariance 101.

**Comment by paskozdilar** [comment]
You're right. My mistake.

> Maybe you want an intersection of functions instead? 

Yes, that's exactly what I wanted. For some reason I thought union was the correct option.

It works fine with the intersection of functions:

```typescript
type ResultCallback<T> = (
  (error: Error, result: undefined) => void
) & (
  (error: null, result: T) => void
);

type ResultCallbackConvoluted<T> = (error: Error | null, result: _HelperType<T, typeof error>) => void;
type _HelperType<T, K extends Error | null> = K extends Error ? undefined : T;


function testResultCallback(cb: ResultCallback<number>) {
  cb(new Error('error'), undefined); // Argument of type 'Error' is not assignable to parameter of type 'never'.(2345)
  cb(null, 42); // Argument of type 'null' is not assignable to parameter of type 'never'.(2345)
}

function testResultCallbackConvoluted(cb: ResultCallbackConvoluted<number>) {
  cb(new Error('error'), undefined); // Compiles fine
  cb(null, 42); // Compiles fine
}
```
