### ISSUE TITLE
enable `@typescript-eslint/no-unused-vars`

### ISSUE THREAD

**Issue by abrahamguo** [microsoft/TypeScript#57124]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

The ESLint config file references investigating whether `@typescript-eslint/no-unused-vars` can be enabled. I have done so in [PR 57123](https://github.com/microsoft/TypeScript/pull/57123).

**Comment by jakebailey** [comment]
See #55139.
