### ISSUE TITLE
A flag to disable reverse mapping in number enums

### ISSUE THREAD

**Issue by y-nk** [microsoft/TypeScript#57134]
### 🔍 Search Terms

"number" "enum" "Object.values"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

A simple configuration flag to disable explicitly reverse mapping for enums (https://github.com/microsoft/TypeScript/issues/30487)

```ts
enum Foobar {
  FOO,
  BAR,
}

console.log(Object.keys(Foobar)) // ["0", "1", "FOO", "BAR"] 
console.log(Object.values(Foobar)) // ["FOO", "BAR", 0, 1] 
```

While this is intended behavior, it can be found as unnatural behavior since string enums don't behave the same way. I don't mind the current behavior, but having a flag to **align both number and string enums** would make sense, at least to me.

### 📃 Motivating Example

```ts
enum Foobar {
  FOO,
  BAR,
}

function isFoobar(arg: any): arg is Foobar {
  return Object.values(Foobar).includes(arg)
}

console.log(isFoobar(Foobar.FOO)) // ok
console.log(isFoobar('FOO')) // should not pass, only 0 & 1 (as number) should be allowed
```

[playground link](https://www.typescriptlang.org/play?#code/KYOwrgtgBAYg9nARgQwE5QN4CgqwPJ4A0OUAQgIIBKxAvllgGZggDGALgJZwhQcDO8JGgAUaAOYAuKMhABPAJRTxvPrAQp02XKmBswqHnkQArYOwB0AN2QAbMMD7DBG+eY6s7AEwejUY+Vh0WCzcfHA2wOY2cGLC-M4iCajmMATy8lAA9JlQcADWwaHhkdGx8eoiAOSpeJXpWTl8ABZwYDaeUCBwbFAADsh8fIS5IDayUAAMUABkUACMUKKq4BCIwKgZza3tUGvSNtEA7sCeQA)

### 💻 Use Cases

1. What do you want to use this for?
writing typeguards in the same way for string and number enums

2. What shortcomings exist with current approaches?
there's a need for a filtering pass on enum set

3. What workarounds are you using in the meantime?

```ts
// inefficient but clean
function isFoobar(arg: any): arg is Foobar {
  return Object
    .values(Foobar)
    .filter((v: any) => !isNaN(v))
    .includes(arg)
}

// efficient but amazingly ugly
function cleanEnum(enumType: any) {
  Object.entries(enumType)
    .forEach(([k, v]: [any, any]) => {
      if (isNaN(v)) delete enumType[k]
    })
}
```

[playground link](https://www.typescriptlang.org/play?ssl=16&ssc=3&pln=17&pc=2#code/KYOwrgtgBAYg9nARgQwE5QN4CgqwPJ4A0OUAQgIIBKxAvllgGZggDGALgJZwhQcDO8JGgAUaAOYAuKMhABPAJRTxvPrAQp02XKmBswqHnkQArYOwB0AN2QAbMMD7DBG+eY6s7AEwejUY+Vh0WCzcfHA2wOY2cGLC-M4iCajmMATy8lAA9JlQcADWwaHhkdGx8eoiAOSpeJXpWTl8ABZwYDaeUCBwbFAADsh8fIS5IDayUAAMUABkUACMUKKq4BCIwKgZza3tUGvSNtEA7sCe9PRMrJzcKkkwHAAeJ76S0nKK0n4qakKaJDp6BigRlMFmsdh8SVcDA4NjY62EwksSjeUAAvAA+KAAQn4ADlkLjEek3B4wN5HOIAkEQiAwhEojE4gIKqg7o9PE4WSk0hlsrkCjS6SVGeUfmyntUCHVeTl8p04Id6KKNOLToxmOwuDwWBEZABRFbCUCQAAqsl6wGRCkwJGBZjY5lAbFQHB8xogZotAVwuHMDDgqD1yBYTQRAG08sNLABdKRhmSyYYJ6MZDE2n0+jgMRZ4glEjLeCJwqDuz3ACPRki4GhU+g64D6w2QutFemlJlJTk-bl4ep8-KFWnFBllZk-YSS2p92V5eWKoA)

### Other considerations

Maybe another approach would be to have a different way of writing enums so that they match `instanceof` but i can't think of anything which is not ugly and hacky.

Or since enums emit JS code, have their own `.is()` type guard function generated would be nice too.

**Comment by fatcerberus** [comment]
Such a flag might be problematic; suppose a `.d.ts` file for some library contains

```ts
declare enum FooBar {
    Foo,
    Bar,
}
```

Now further suppose the library writer enabled `noEnumReverseMappings` when compiling this library, but the *user* of the library didn't.  The type checker would then allow reverse lookups on this enum, only for the app to crash because the entries don't actually exist at runtime...

**Comment by fatcerberus** [comment]
> it can be found as unnatural behavior since string enums don't behave the same way

For the record, the only reason string enums don't get reverse mappings is because they are vulnerable to collisions whereas numeric enums aren't.

**Comment by y-nk** [comment]
i believe that's not _really_ related to my proposal. i understand that enums are the only things emitting JS (in that sense you're right) but it's not my proposal which will solve the issue of mismatch of tsconfig between built lib and source.

for example, i wonder if - to some extend - a library with types compiled with `noExplicitAny: false` should be valid to be used in a project where `noExplicitAny: true` is set.

**Comment by fatcerberus** [comment]
> i understand that enums are the only things emitting JS (in that sense you're right) but it's not my proposal which will solve the issue of mismatch of tsconfig between built lib and source.

Right, but I'm pointing it out because the potential for such mismatch to be a runtime footgun is *very* likely to be cited as a reason for the TS devs to reject the proposal.

**Comment by y-nk** [comment]
> For the record, the only reason string enums don't get reverse mappings is because they are vulnerable to collisions whereas numeric enums aren't.

this i know, but there are valid reasons to use number has enums. from storing in db to magic calculations ; doesn't mean it should not be first class citizen

**Comment by MartinJohns** [comment]
Essentially sounds like a duplicate of #44753 to me.

**Comment by fatcerberus** [comment]
And a maintainer already noticed the above issue too: https://github.com/microsoft/TypeScript/issues/44753#issuecomment-869798237

**Comment by RyanCavanaugh** [comment]
If you don't want the reverse lookup, there's not much reason left to write a numeric enum.
```ts
const MyEnum = {
  x: 1,
  y: 2
} as const;
type MyEnum = (typeof MyEnum)[keyof typeof MyEnum];
```
