### ISSUE TITLE
Can't "typescript.preferences.importModuleSpecifierEnding" receive a custom array?

### ISSUE THREAD

**Issue by jin-Pro** [microsoft/TypeScript#57131]
Hello, I am a software engineer who uses vscode well.
Thank you so much for the functionality you provide.

---

I use '[React](https://react.dev/)' and '[vite](https://vitejs.dev/)'

```
Component
   ㄴindex.tsx
   ㄴindex.jp.tsx
   ㄴindex.tw.tsx
```

Through the above structure, I'm creating web services for several countries,

---

I use a javascript bundler called '[vite](https://vitejs.dev/)',
Vite has a function called '[extensions](https://vitejs.dev/config/shared-options.html#resolve-extensions)'.

This function can adjust the file reference priority during `build` and `local dev start`.

```tsx=
// When I select jp through the vite option, 
// the result of that component is Component/index.jp.tsx. 
// But in vscode the reference points to Component/index.tsx.
import Component from './Component' 
```

I understand that I can change the reference via the `typescript.preferences.importModuleSpecifierEnding` option.

so, I expected the following usage, but the value of the option was limited so it was not possible.

```tsx=
// in settings.json
"typescript.preferences.importModuleSpecifierEnding": ['.jp.tsx','.tsx'] 
```

Is there a good way to solve the above problem?

thank you.

**Comment by RyanCavanaugh** [comment]
This is a "which of these things do you want" setting, not a "write the text you want to happen" setting
<html>
<body>

/** Determines whether we import `foo/index.ts` as "foo", "foo/index", or "foo/index.js" */
--
3569 | readonly importModuleSpecifierEnding?: "auto" \| "minimal" \| "index" \| "js";


</body>
</html>

**Comment by jin-Pro** [comment]
> This is a "which of these options do you want" setting, not a "write the text you want to happen" setting
> 
> ```
> /** Determines whether we import `foo/index.ts` as "foo", "foo/index", or "foo/index.js" */
> --
> readonly importModuleSpecifierEnding?: "auto" | "minimal" | "index" | "js";
> ```

Of course, you're right.
So how can I apply vscode the extension priority?

**Comment by jin-Pro** [comment]
I solved this problem, it wasn't a problem, it was my mistake.

i used [moduleSuffixes](https://www.typescriptlang.org/tsconfig#moduleSuffixes)

so, I will close this issue. Thank you
