### ISSUE TITLE
Custom attribute documentation/examples don't work

### ISSUE THREAD

**Issue by JakobJingleheimer** [microsoft/TypeScript#57140]
### 🔎 Search Terms

"custom attributes", "jsx"

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about [JSX](https://www.typescriptlang.org/docs/handbook/jsx.html#attribute-type-checking)

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdAJlrgDbKVwB2yIWqYPFjgApAMoANOAG86cOMC4wsUAkLgBJJVEWpguAKKssfJelnz5BCBABcMuJQCOAV2CVGABWJh7qGDpcAOY0cBBgMMAQPKze4QD89lwuIABGKnAAvvTymXR5dAA81hCOWK7uWF4+ALwARKkcdXAA9AB8oS0tYQDWRSVlFR5xYPWNUM3hkdHIsbXSAAyZrR2t3RB9xTYrnd0qxFAANINuwz4K6CDAqHrB-dvOp1UjNYvL7btw+9DHj5XV4TgqAAFhAXKxGHB0iggQFFEF7qU-mdwmMmnAXFwelwIAB3LgjHZrL5QA7HTHYvEE86MCD8bgQeBYAAe1xgiJO-xeDXRqBIWAAtBScfiBWBzh9iRtjulcMgXKhhGQ+XwhViRVwxT4yBcGfBkHAAG6zYCQ01YJTAAjAFRAA

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

The document's provided code does nothing (the error is unchanged).

### 🙂 Expected behavior

It to work as the TS docs claim it does.

### Additional information about the issue

I'm trying to add custom attributes to native HTML elements, like `variant` in `<input type="checkbox" variant="toggle" />`, but it results in `ts(2322)` despite applying the JSX namespace changes per the docs. Following the responses from maintainers in related threads does not work—the answers appear to be outdated (on top of being written for someone who already knows the answer).

**Comment by fatcerberus** [comment]
TS looks up `JSX` from the global scope, but your augmentations are module-scoped.  This fixes it:

```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      foo: { requiredProp: string; optionalProp?: number };
    }
  }
}
```
