### ISSUE TITLE
Allow indentation option for organizeImports

### ISSUE THREAD

**Issue by iteriani** [microsoft/TypeScript#57157]
### 🔍 Search Terms

organizeImports

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

const importArgs: ts.OrganizeImportsArgs = {
    type: 'file',
    fileName,
    mode: ts.OrganizeImportsMode.SortAndCombine,
    indent: 1,
  };
  const fileChanges =
      languageService.organizeImports(importArgs, formatOptions, {});

### 📃 Motivating Example

Right now, it looks like destructured imports adds two tabs per destructured item. Prettier currently adds one. Normally this wouldn't be an issue as we call organizeImports before Prettier, but adding ranged format support surfaces this discrepency.

### 💻 Use Cases

1. What do you want to use this for?
    Sorting imports before Prettier with ranged line support 
3. What shortcomings exist with current approaches?
    See below
5. What workarounds are you using in the meantime?
    We're likely going to disable sorting imports when sorting with ranged lines.

**Comment by RyanCavanaugh** [comment]
I can't repro the described behavior of two tabs - can you clarify?

**Comment by Misha327** [comment]
I think I get the issue he's describing, when I have organizeImports enabled on save, this happens:

<img width="328" height="214" alt="Image" src="https://github.com/user-attachments/assets/86f2e30d-1ed2-4011-9843-bbad75ce4a4b" />

Can't find a way to overcome this.
