### ISSUE TITLE
`NonNullable` doesn't work on mapped types instantiated with `null`/`undefined`

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#57151]
### 🔎 Search Terms

mapped nonnullable empty object null undefined instantiation

### 🕗 Version & Regression Information

- This changed in PR: https://github.com/microsoft/TypeScript/pull/49119

### ⏯ Playground Link

https://www.staging-typescript.org/play?ts=5.4.0-dev.20240124#code/C4TwDgpgBAYg9nAPAFQHxQLxQHJwHbYCuANsQIYBGxEiA3lANoDSUAlnlANYQhwBmUZAF0AXIOZCoAX1QBYAFALQkKACUIAZxLBMsBIjwliqIA

### 💻 Code

```ts
type Foo<T> = NonNullable<{ [K in keyof T]: T[K] }>

type Result = Foo<null>
```

### 🙁 Actual behavior

`Result` is of type `null`

### 🙂 Expected behavior

`Result` should be of type `never`

### Additional information about the issue

This likely gets closed as a design limitation like the one here: https://github.com/microsoft/TypeScript/issues/56644

**Comment by ahejlsberg** [comment]
> This likely gets closed as a design limitation like the one here: https://github.com/microsoft/TypeScript/issues/56644

That is indeed what I'm going to do. 😄
