### ISSUE TITLE
`exactOptionalPropertyTypes: true` prevents me assigning `prop?` to `prop?`

### ISSUE THREAD

**Issue by simPod** [microsoft/TypeScript#57152]
### 🔎 Search Terms

"exactOptionalPropertyTypes incompatible"

### 🕗 Version & Regression Information

- This is the behaviour in every version I tried, and I reviewed the FAQ for entries about 

### ⏯ Playground Link

https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/JYOwLgpgTgZghgYwgAgApQPYAcDOyDeAUMsnAPwBcyOYUoA5gNyEC+hhCGINyAYhhmQBeZAAp8pZCyrpsOAJTCAfKWYQAHlgxQwyTt10AhOFGFiJcKTMy5FQlQB5+guEPxwWyAPRLmQA

### 💻 Code

```ts
interface Props {
  a?: string;
}

const Foo = ({ a }: Props) => a;
export const Bar = ({ a }: Props) => <Foo a={a} />;

```

### 🙁 Actual behavior

Getting ```Type '{ a: string | undefined; }' is not assignable to type 'Props' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
  Types of property 'a' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.(2375)```

### 🙂 Expected behavior

No error. `a?` should be assignibale to `a?` (or am I missing something?)

**Comment by Andarist** [comment]
This works as expected. At runtime you deal with **values** - the `a`'s value in `Bar` has the type of `string | undefined` and `undefined` can't be assigned to an optional `a?: string` under EOPT (that's the goal really, right?).

The situation here is not different from:
```ts
interface Props {
  a?: string;
}

const p: Props = {
  a: undefined
}
```

**Comment by simPod** [comment]
I understand, thank you very much.
