### ISSUE TITLE
`string` satisfies `literal` type when use on object property

### ISSUE THREAD

**Issue by tylim88** [microsoft/TypeScript#57155]
### 🔎 Search Terms

satisfies incorrect type

### 🕗 Version & Regression Information

tested on nightly, 5.3.3 and 5.0.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhjAvDA5MFMJygSwgMxwFMJV0YAfVAExQCgB6BmFmAPQH467RJYBBJDADedVvABcZDFlwFipNBiopajZuy4BfGEA

### 💻 Code

```ts
const a = 'c' satisfies 'c' | 'd'
//    ^?

const A = {
    a: 'c' satisfies 'c' | 'd'
//  ^?
} 
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/5227509/8bda13bf-6081-4e7f-b7bd-4bd072bebbaf)

### 🙂 Expected behavior

![image](https://github.com/microsoft/TypeScript/assets/5227509/43b8488d-c9f9-4438-a276-131aadc19f50)

or throw error instead because `string` should not satisfies `literal` type 
```ts
const a = ('c' as string) satisfies 'c' | 'd'
```
![image](https://github.com/microsoft/TypeScript/assets/5227509/2f5aebdc-63f2-463f-a6bb-820248594010)

**Comment by Andarist** [comment]
I'm not sure if this is a bug. It matches some other existing behaviors:
```ts
const str = 'c'
//    ^? const str: "c"

const A = {
    a: str
//  ^? (property) a: string
} 
```

If you want to preserve the literal type you can always throw an extra `as const` at this.

**Comment by tylim88** [comment]
i see, maybe throw error instead because string does not satisfy literal type?

```ts
const a = ('c' as string) satisfies 'c' | 'd'
```

![image](https://github.com/microsoft/TypeScript/assets/5227509/f576067e-9ea8-4661-8160-599f53469fdc)

**Comment by Andarist** [comment]
It’s a widening problem. The expression at this position has the type that you expect (a literal string) - so the error can’t be raised there. It’s when it’s assigned to a property (a mutable location) the assigned type gets widened to a string. It’s perfectly valid situation to have RHS’ type to be different from the LHS’ type as long as it’s assignable to it

**Comment by tylim88** [comment]
i see, thanks for your explanation
