### ISSUE TITLE
Question about TypeScript Coding-guidelines

### ISSUE THREAD

**Issue by bvahdat** [Microsoft/TypeScript#5716]
Could you please elaborate the reason why a TypeScript based App [should better make use of `undefined` and not `null`](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined) as I do exactly the opposite!

Out of curosity I just looked into the [Angular 2](https://github.com/angular/angular) TypeScript codebase and:

- Found `return undefined` [6 times](https://github.com/angular/angular/search?l=typescript&q=%22return+undefined%22&type=Code&utf8=%E2%9C%93)
- Found `return null` [100 times](https://github.com/angular/angular/search?l=typescript&q=%22return+null%22&type=Code&utf8=%E2%9C%93)

**Comment by DanielRosenwasser** [comment]
This is our codebase's style guideline:

> **While these guidelines are mainly meant for contributors to the TypeScript project**, certain suggestions apply as to how idiomatic TypeScript code should be written

To answer your question, there's no reason to introduce `null` into the mix. `'undefined `already pops up by default if you don't set a value (in object properties, out of bounds accesses on arrays, variables, parameters, etc.), so differentiating between the two becomes a major pain. This is exacerbated even you are using the better equality operators (`===` and `!==`).

**Comment by bvahdat** [comment]
>these guidelines are mainly meant for contributors to the TypeScript project

Then why do I find more usage of `null` compared to `undefined` inside the TypeScript codebase?

- Found `return undefined` [107 times](https://github.com/Microsoft/TypeScript/search?l=typescript&q=%22return+undefined%22&type=Code&utf8=%E2%9C%93)
- Found `return null` [231 times](https://github.com/Microsoft/TypeScript/search?l=typescript&q=%22return+null%22&type=Code&utf8=%E2%9C%93)

>`undefined` already pops up by default if you don't set a value (in object properties, out of bounds accesses on arrays, variables, parameters, etc.)

I'm already aware of that but don't see it's relation to my question.

**Comment by RyanCavanaugh** [comment]
@bvahdat all the hits you see for `return null;` are in our testcases. Even if we don't use `null` in the compiler, we still have to make sure it works for user code.

**Comment by GoToLoop** [comment]
* Perhaps rather than banning `null` ban `=== undefined` & `!== undefined` instead.
* Even very strict linters open exception for `== null` or `== undefined`.
* Since either of them catches both `undefined` & `null` in 1 swoop.
* `null` exists in JS in order to denote something already declared but it's not initialized yet or it doesn't have a meaningful value at that moment.

From https://developer.Mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null:
> In APIs, `null` is often retrieved in place where an object can be expected but no object is relevant.

**Comment by Elephant-Vessel** [comment]
@GoToLoop Totally agree, null and undefined can have completely different semantic meaning.
