### ISSUE TITLE
(Is it possible to | please provide a way to) specify the main module in a System-JS "outFile" bundle?

### ISSUE THREAD

**Issue by JX75** [microsoft/TypeScript#57168]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

When loading a bundle of several modules in a browser, System-JS only "executes" the first one, unless there a call to System.import later, e.g. in the page itself. By executing, I mean running the global statements in the source .ts file.

The trouble is that - unless I'm mistaken - it doesn't seem possible to specify which module will be bundled first in the file specified with an "outFile" option. I tried to change the "main" property in the corresponding package.json but it has no effect.

**Comment by RyanCavanaugh** [comment]
We nearly cut SystemJS `outFile` support in 5.0. I'd recommend switching to a more-configurable bundler if you need functionality beyond what's already available.

**Comment by JX75** [comment]
Thank you for the information.
