### ISSUE TITLE
Auto intellisense really slow with React and TypeScript when node_modules is big

### ISSUE THREAD

**Issue by razb-viola** [microsoft/TypeScript#57179]
Does this issue occur when all extensions are disabled?: YES, also restarted the computer, closed all of the programs. Opened just one IDE window. The problem is with the node_modules.

- VS Code Version: Version: 1.85.2 (Universal)
- OS Version:  MacOS Ventura 13.4

Steps to Reproduce:

1. Go to any React + Typescript project, start write: <Butt, wait 10 seconds that the editor will suggest you with import <Button> from 'some-package'.
2. Go to any node.js with Typescript, without React, without Next.js, write anything you like, get instant, like 0ms suggestions for anything - for function props, for object properties or module imports suggestions.
3. Go back to the React + Typescript project, write con, wait 5 seconds and the editor will suggest you with console.log.

The problem is 100% the size of node_modules, when I deleted it, it worked like a snap. 
But unfortunately, I cannot delete this folder in my real projects.

What to do?

**Comment by RyanCavanaugh** [comment]
The first thing I'd do is add
```
  "types": []
```
to your tsconfig and see what happens.

Beyond that, it's hard to predict what's going on
