### ISSUE TITLE
TS 5.4 beta release tag not available

### ISSUE THREAD

**Issue by rahul-kamat** [microsoft/TypeScript#57178]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Has TS 5.4 beta been released? When I do `git tag`, I don't see a `v5.4-beta` branch. 

Can you guys create a branch so we can bring TS 5.4 into Google and report feedback to you.

**Comment by RyanCavanaugh** [comment]
5.4 beta isn't out yet. Ping here again if you don't see the release tag in github once the 5.4-beta release is on npm (these should happen basically simultaneously)

**Comment by rahul-kamat** [comment]
Ok sounds good thank you :)

**Comment by Jimm19999** [comment]
> ### Wissen
> * [x] Ich erkenne an, dass Probleme, die diese Vorlage verwenden, nach Ermessen des Betreuers ohne weitere Erklärung geschlossen werden können.
> 
> ### Kommentar
> Wurde TS 5.4 Beta veröffentlicht? Wenn ich das tue `git tag`, sehe ich keinen `v5.4-beta`Zweig.
> 
> Könnt ihr einen Zweig erstellen, damit wir TS 5.4 in Google integrieren und euch Feedback melden können?

**Comment by DanielRosenwasser** [comment]
FYI, 5.4 beta is now available
