### ISSUE TITLE
Function Overload should consider Type Parameter Compatibility

### ISSUE THREAD

**Issue by horita-yuya** [microsoft/TypeScript#57186]
### 🔍 Search Terms

Function Overload

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The implementation signature of Function Overload should consider the type parameter compatibility.

### 📃 Motivating Example

Assuming, we have the following code.
```typescript
function createSendLog(title: string): () => void
function createSendLog<T extends string>(title: string): (additionalText: T) => void
function createSendLog<T extends string>(title: string): ((() => void) | ((additionalText: T) => void)) {
  return (args: T) => {
    console.log(`${title}, count of additionalText: ${args.length}`)
  }
}
```
This function can create sendLog function determining if it will receive a parameter like the following code.
```typescript
const sendLogWithNoParams = createSendLog("This is log with no params")
const sendLogWithParams = createSendLog<string>("This is log with params")
```

There is a problem for these functions.

```typescript
// Build succeeds, but runtime error occurs. (Cannot read properties of undefined (reading 'length'))
sendLogWithNoParams()
// Build fails, but Works correctly ignoring type check.
// sendLogWithNoParams("param1")

// OK
sendLogWithParams("param1")
```

As the above code, `sendLogWithNoParams()` can be called without arguments, but it results in runtime error with `(Cannot read properties of undefined (reading 'length'))`.

If type parameters are considered in function overloads,
```typescript
function createSendLog(title: string): () => void
function createSendLog<T extends string>(title: string): (additionalText: T) => void
// NEW FEATURE: This occurs build error, type parameter T is not compatible
function createSendLog<T extends string>(title: string): ((() => void) | ((additionalText: T) => void)) {
  return (args: T) => {
    console.log(`${title}, count of additionalText: ${args.length}`)
  }
}

// UPDATED Example with NEW FEATURE
// Just for simplicity `| undefined` is added.
function createSendLog(title: string): () => void
function createSendLog<T extends string>(title: string): (additionalText: T) => void
// NEW FEATURE: Build succeeds and no runtime error
function createSendLog<T extends string | undefined>(title: string): ((() => void) | ((additionalText: T | undefined) => void)) {
  return (args: T | undefined) => {
    console.log(`${title}, count of additionalText: ${args.length}`)
  }
}
```

We can avoid this kind of error.

Thanks!

Reference:
- [Ordering & TypeScript chooses the first matching overload when resolving function calls.](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#function-overloads)

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by RyanCavanaugh** [comment]
We've tried probably 20 times to write down a better algorithm for validating the relationship between overloads and implementation signature that catches enough errors while also not making it sometimes *impossible* to write a working implementation signature, and have come up empty-handed every time.

The current algorithm works pretty well as long as you're not actively trying to sabotage yourself, and you can also use parameter tuples now (and hopefully soon, conditional types) to avoid for the need for overloads in the first place.

**Comment by horita-yuya** [comment]
Thank you for the valuable information.

**Comment by JesusTheHun** [comment]
@RyanCavanaugh are you talking about something like that ?

```ts
function fn<Args extends UnionOfPossibleSignatureParameters>(...args: ValidateArgs<Args>);
```

Right now it doesn't work and it would be great if it could :D 
It won't bring the readability of overloads but at least it will open some doors !
