### ISSUE TITLE
Multiple rest arguments may be allowed if they occupy different tuple nexting levels.

### ISSUE THREAD

**Issue by craigphicks** [microsoft/TypeScript#57182]
### 🔎 Search Terms

Multiple rest arguments may be allowed in tuples

### 🕗 Version & Regression Information

At least >=4.3.5 

### ⏯ Playground Link
[play](https://www.typescriptlang.org/play?ts=4.3.5#code/CYUwxgNghgTiAEYD2A7AzgF3gMwFzwAoAPfFAVwFsAjEGAGngDpnYBzNfAbXOtoecacBmGAEsUrTgF06VJEgggoKOgM5yFSlcIxiJ0qYYCUAXgB8ANySjgAbgBQoSLATJ0WVvmKlKNekxYYdi4eP35mIWYRcUkZAnV5RWUpAB8EzWVZRK0pI1Uo3RiDXPMrGwcAegr4Gtq6+obGpuaW1rb2gD8u7p6O+yr4AEF4OEx4EEUKEBQsMGUUJCxsBQgkAHd4ZUWAC1oRkDGJkCmZxgIARgAmADYAViN7e2xbeCrsb3hQvk2gtAB9AAMPl4-gEbH+5y80Qk8BS8A0SRQRmkRnwZWAj3e5zo2OwUAgaBARgcWJxdDxBJA5PxhOJTwuZIphLoACIWXTSbiaVSmVS2RyGdi2dTKaz2STBWKRczeWK6fTsUKWdK+crZcLefLHOBoHBEKgxhguCRPr5vmDfiEzaCIjo9LEshltBEEVp8oxobFDIYHE5da4DVgyMbgWEAoxwVaQeFBHainF0ojUom3a7knk4-pvVJKtV2vmC4WiwXet1+tVhqMsEcTrN5oscCt1psFhhdjB9odJtMMGcrncHvYMC8Bm5DSHTdHJ2GBARPbD4dllMjDI8gA)

### 💻 Code

```ts
declare const f: (x: number, ...args: [number, ...[...string[],boolean,...[boolean,...string[]]]])=>void;
declare const g: (x: number, ...args: [number, ...[...string[],([boolean]|[boolean,boolean]),...string[]]])=>void;
//                                                                                             ~~~~~~~~~~~
// A rest element cannot follow another rest element.(1265)

f; //f(x: number, args_0: number, ...args_1: (string | boolean)[]): void

f(1,1,false);
f(1,1,false,false);
f(1,1,false,"");
f(1,1,false,false,"");
f(1,1,"",false,"");
f(1,1,"",false,false,"");

f(1,1,"",false,"",false,"",false);


declare const t: [x: number, ...args: [number, ...[...string[],boolean,...[boolean,...string[]]]]];
declare const u: [x: number, ...args: [number, ...[...string[],([boolean]|[boolean,boolean]),...string[]]]];
//                                                                                           ~~~~~~~~
// A rest element cannot follow another rest element.(1265)

t; // const t: [x: number, number, ...(string | boolean)[]]
```

### 🙁 Actual behavior

f, t pass

### 🙂 Expected behavior

f and t are equivalent to g and u respectively, so perhaps should not pass.

**Comment by RyanCavanaugh** [comment]
The rule is just here to inform you that the thing you think syntactically is happening might not be. It can be evaded if you try hard enough (more simply, through aliasing/instantiation).

**Comment by craigphicks** [comment]
@RyanCavanaugh - Yes, I get that it is more of warning than an <s>error</s>.  The point of this issue is that both `f` and `g` contain double rest elements, but only `g` gets the <s>error</s> warning.
Because it is actually just a warning and not really an <s>error</s>, I would agree that it is *not a defect*, in both cases.  If that's what you mean, then I agree.

**Comment by unicornware** [comment]
> The rule is just here to inform you that the thing you think syntactically is happening might not be. It can be evaded if you try hard enough (more simply, through aliasing/instantiation).

@RyanCavanaugh do you have examples of this? is there a way to spread an array between elements of a tuple?

```ts
type Comment = { type: 'comment' }
type Identifier = { type: 'identifier' }
type Nothing = { type: 'nothing' }
type StringLiteral = { type: 'string' }

// type Comments = Comment[]
type Comments = [] | [Comment, ...Comment[]]

type Children = [
  ...Comments,
  Identifier | Nothing,
  ...Comments,
  StringLiteral
]

// | [Identifier | Nothing, StringLiteral] 
// | [Identifier | Nothing, Comment, ...Comment[], StringLiteral]
// | [Comment, ...Comment[], Identifier | Nothing, StringLiteral] 
// | [Comment, ...(Comment | Identifier | Nothing)[], StringLiteral]
```

in the example above, the last tuple in the resulting union allows for multiple `Identifier` or `Nothing` types, when it should only allow one.

**Comment by craigphicks** [comment]
@unicornware - I had assumed that the internal representation was limited to the following:
 - From the left:
```
[ <union of types that could be in 0th place>, <union types that could be in 1th place>, .... ]
 ```
and that eventually reaches the end of the tuple, or a final repeating element. 

- From the right: (Same as from from the left but starting at the end.)

If that representation were actually the case, then I wouldn't be surprised by multiple `Identifier | Nothing`, just because it couldn't know for sure at which index that `Identifier | Nothing` would appear.  (Of course a different internal representation could allow "single instance" along with "unknown index", but that would count as a new feature).

Given that assumed representation we would get:
From the left:  `[...(Comment|Identifier|Nothing|StringLiteral)[]]`
From the right:  `[StringLiteral, ...(Comment|Identifier|Nothing)[]]`
Unifed left first:  `[...(Comment|Identifier|Nothing)[], StringLiteral]`

However, the type shown by TypeScript user interface:
```
// | [Identifier | Nothing, StringLiteral] 
// | [Identifier | Nothing, Comment, ...Comment[], StringLiteral]
// | [Comment, ...Comment[], Identifier | Nothing, StringLiteral] 
// | [Comment, ...(Comment | Identifier | Nothing)[], StringLiteral]
```
leaves me puzzled.  If the user type is going to be transformed for display, why not transform it to the canonical representation? 

Also, if it is using the displayed type internally, that's going to result ion unnecessary complexity of computation.
