### ISSUE TITLE
Base class is narrowed to `never` after User-defined Type Guard on subclass

### ISSUE THREAD

**Issue by gluxon** [microsoft/TypeScript#57193]
### 🔎 Search Terms

- user defined type guard
- narrowing
- subclass

### 🕗 Version & Regression Information

- This reproduces on v5.3.3.
- This is the behavior in every version I tried, going back to v3.3.3333.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=6&ssc=1&pln=7&pc=1#code/MYGwhgzhAECCB2BLAtmE0DeAoa0AOArgEYiLDSoDWApgHID2iE1AFAJSY67QBO1ALgR7xoAIniNmorgF8scrKEgwAIvQDm0agA9+1eABMYCFGk65CJMtAj8w-a0xZgkqEAC44rtG08vT6EzQaprY3LwCQiL+btCI8LYuwNT0AGZeAbLyWFipBPDADvQierbO3h4Zbr42-DzxoVyI6SwhAHROMT4cYdx8gsLQXSBtVHSSrGxZuP1RQxWjYDQMTJNcAPTr4bgAegD82bn5hYjF0KX8AEzlAZ4m1Z629fCNuM3QN7HxiQUp6SE9LgzSKDYaLZYTdjTCIDaILMYrZhQ3CbbbQfbZIA

### 💻 Code

```ts
class Animal {
  public makeNoise() {
    return "noise"
  }
}

class Dog extends Animal {
  public static is(animal: Animal): animal is Dog {
    return animal instanceof Animal
  }
}

function test(animal: Animal): string {
  if (Dog.is(animal)) {
    return animal.makeNoise()
  }
  return animal.makeNoise()
  //      ^?
}

function test2(animal: Animal): string {
  if (animal instanceof Dog) {
    return animal.makeNoise()
  }
  return animal.makeNoise()
  //      ^?
}
```

**Edit**: Switched `animal is Animal` to `animal is Dog`. Caught by @Andarist https://github.com/microsoft/TypeScript/issues/57193#issuecomment-1912622082.

### 🙁 Actual behavior

Under the `test()` function, the `animal` object is narrowed to `never`.

### 🙂 Expected behavior

The `animal` object is not narrowed kept as `Animal`.

### Additional information about the issue

This seems to be different when using a user defined type guard vs an inline `instanceof` check which surprised me.

**Comment by Andarist** [comment]
Your `Animal` and `Dog` classes are structurally identical so TS sees them as compatible. On top of that, your static `Dog.is` tries to check if `animal is Animal` but you probably have meant `animal is Dog`.

After "correcting" both you get the expected results: [TS playground](https://www.typescriptlang.org/play?ts=5.3.3#code/MYGwhgzhAECCB2BLAtmE0DeAoa0AOArgEYiLDSoDWApgHID2iE1AFAJSY67QBO1ALgR7xoAIniNmorgF8scrKEgwAIvQDm0agA9+1eABMYCFGk65CJMtAj8w-a0xZgkqEAC44rtG08vT6EzQaprY3LwCQiL+btCI8LYuwNT0AGbBGrJceDyIAG721NASyPFongTwlBIA7vAA3PJYWKmVwA70Inq2zt4eXgG+Nvy58KFciOksIQB0TjE+HGHcfILC0AsgM1R0kqxsWbirURt922A0DEz7XAD0t+G4AHoA-E0tbR1d1LYATL0BTwmNxDWyjca4SbQAGxeKJeDJNIZdRLLhHSLrTbnS57diHCJraJnHZXZh43D3R7QV5NIA) . You have just observed a normal subtype elimination process - in your version you have "removed" `Animal` from `Animal` and thus you have been left out with `never` in the else branch

**Comment by gluxon** [comment]
> On top of that, your static `Dog.is` tries to check if `animal is Animal` but you probably have meant `animal is Dog`.

Thanks for catching that. I did intend to write `animal is Dog` here. Going to edit the problem description for that fix.

> Your `Animal` and `Dog` classes are structurally identical so TS sees them as compatible. After "correcting" both you get the expected results: [TS playground](https://www.typescriptlang.org/play?ts=5.3.3#code/MYGwhgzhAECCB2BLAtmE0DeAoa0AOArgEYiLDSoDWApgHID2iE1AFAJSY67QBO1ALgR7xoAIniNmorgF8scrKEgwAIvQDm0agA9+1eABMYCFGk65CJMtAj8w-a0xZgkqEAC44rtG08vT6EzQaprY3LwCQiL+btCI8LYuwNT0AGbBGrJceDyIAG721NASyPFongTwlBIA7vAA3PJYWKmVwA70Inq2zt4eXgG+Nvy58KFciOksIQB0TjE+HGHcfILC0AsgM1R0kqxsWbirURt922A0DEz7XAD0t+G4AHoA-E0tbR1d1LYATL0BTwmNxDWyjca4SbQAGxeKJeDJNIZdRLLhHSLrTbnS57diHCJraJnHZXZh43D3R7QV5NIA) .

I also noticed that adding a new private field to `Dog` changes the narrowing behavior. I was debating whether to commit that workaround to an internal codebase.

> You have just observed a normal subtype elimination process - in your version you have "removed" `Animal` from `Animal` and thus you have been left out with `never` in the else branch

I think the surprising bit is that this happens when removing `Dog` from `Animal` as well. I'm realizing from your description that UDFs are structural checks, and there's a separate ["_`this`-based type guard](https://www.typescriptlang.org/docs/handbook/2/classes.html#this-based-type-guards) that would be better for classes.

In any case, the behavior seems intended. Thank you for the help!
