### ISSUE TITLE
The typescript compiler sometimes interprets "--outFile" as a file to compile resulting in error TS6231.

### ISSUE THREAD

**Issue by flenniken** [microsoft/TypeScript#57194]
### 🔎 Search Terms

outFile TS6231

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about outFile and TS6231

### 💻 Code

Steps:

```
$ tsc --lib es7 –-outFile image.js ts/image.ts --showConfig
```

### 🙁 Actual behavior

Actual results:

The options contain a file called "./--outFile":

```
{
    "compilerOptions": {
        "lib": [
            "es7"
        ]
    },
    "files": [
        "./–-outFile",
        "./image.js",
        "./ts/image.ts"
    ]
}
```

### 🙂 Expected behavior

Expected:

I expect the output to look like:

```
{
    "compilerOptions": {
        "outFile": "./myfile.js"
    },
    "files": [
        "./ts/image.ts"
    ]
}
```

### Additional information about the issue

Note:

Running version 5.3.3 on Debian version 12.
```
tsc -v
Version 5.3.3

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Note:

When you  don't use the showConfig option, you get the TS6231 error:

```
error TS6231: Could not resolve the path '–-outFile' with the extensions: '.ts', '.tsx', '.d.ts', '.cts', '.d.cts', '.mts', '.d.mts'.
  The file is in the program because:
    Root file specified for compilation
```

Note:  

Both outFile and outfile sometimes work as expected:

    
```
$ tsc --outFile myfile.js ts/image.ts --showConfig
{
    "compilerOptions": {
        "outFile": "./myfile.js"
    },
    "files": [
        "./ts/image.ts"
    ]
}

$ tsc --outfile myfile.js ts/image.ts --showConfig
{
    "compilerOptions": {
        "outFile": "./myfile.js"
    },
    "files": [
        "./ts/image.ts"
    ]
}
```

Note:

The workaround is to use "outfile" instead of "outFile":

```
$ tsc --lib es7 --outfile myfile.js ts/image.ts --showConfig
{
    "compilerOptions": {
        "lib": [
            "es7"
        ],
        "outFile": "./myfile.js"
    },
    "files": [
        "./ts/image.ts"
    ]
}
```

**Comment by abrahamguo** [comment]
Using a tool like [this one](https://www.babelstone.co.uk/Unicode/whatisit.html), you can tell that the first of the two dashes before `outfile` is actually an en dash, not a normal hyphen, so there looks to be no issue here.

**Comment by flenniken** [comment]
Wow, good find.  I just removed the characters and typed two dash and it
works as expected.

**Comment by abrahamguo** [comment]
No problem! To clarify a bit more for anyone else reading the issue — camelcasing vs lowercasing has no effect; it was simply coincidence that the first example was the only one that contained the mis-copied en dash.

@RyanCavanaugh let me know if you think it would be beneficial to add some sort of user-friendly error handling for this case, although I would guess that most other CLIs would have no special handling for this case and would give similarly cryptic results.

**Comment by fatcerberus** [comment]
Smart quotes (and hyphens) strike again!

**Comment by RyanCavanaugh** [comment]
The wonderful thing about humans is, by sheer numbers, we eventually make every possible mistake.

If it happens again we can think about hardening the commandline parser
