### ISSUE TITLE
VS Code error: Error 2322 on HTML Meta charset

### ISSUE THREAD

**Issue by murugappanrm** [microsoft/TypeScript#57195]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Hi,
I am getting this error on HTML script:

[{
	"resource": "/C:/xampp/htdocs/MyCourses/react/udsmilga/tutorial/public/index.html",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ charset: string; }' is not assignable to type 'DetailedHTMLProps<MetaHTMLAttributes<HTMLMetaElement>, HTMLMetaElement>'.\n  Property 'charset' does not exist on type 'DetailedHTMLProps<MetaHTMLAttributes<HTMLMetaElement>, HTMLMetaElement>'. Did you mean 'charSet'?",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 15,
	"endLineNumber": 4,
	"endColumn": 22
}]

See Screencap below

![Screenshot_4](https://github.com/microsoft/TypeScript/assets/63133893/88babac2-b952-4e37-abbf-848a8b21ee75)

**Comment by IllusionMH** [comment]
Looks like you have config or extension that treats HTML as JS/JSX, and not like TS issue.

**Comment by murugappanrm** [comment]
@IllusionMH I am not sure i understand. Please assist and explain so that i can locate the problem. The odd thing is that this only happens when i doing a React app. Other apps e.g pure web app or embed HTML in php this does not happen.

Btw, the app works fine. Its just annoying error that misleads,

**Comment by IllusionMH** [comment]
I don't know what you doing d like n your config, but probably there's wrong file association of. `html` to `javascriptreact`/`typescriptreact`, or extension that does this. Disable all extension (or use bisect) and/or bisect(manually) config to see what causes this problem.

**Comment by RyanCavanaugh** [comment]
We don't control this behavior and I don't know who's setting this up for you in the editor either

**Comment by murugappanrm** [comment]
@IllusionMH @RyanCavanaugh , 

Sorry for the delayed update. I was about to use the Bisect extension to debug the problem when there was an update to Better Comment extension. When i reloaded the extension, the problem seems to have resolved. Hmmm... 

Thank you for assisting me, especially related to the Bisect extension. Never knew that one existed.
