### ISSUE TITLE
Cannot use const string in enum when it's type is specified explicitly

### ISSUE THREAD

**Issue by undsoft** [microsoft/TypeScript#57199]
### 🔎 Search Terms

enum string, enum const

### 🕗 Version & Regression Information

- This is the behavior in every 5+ version available in Playground.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZgQwJYBsIC4YHIAqBTADyixgF5t8isBuAKFElgHcQAnAawjIsOLtrxgArgFsYARSF5oScDgCeABzwwA3rRgxKscolQQANBq28ATNxYdDtAL5A

### 💻 Code

```ts
const fails: 'Text' = 'Text';
const works = 'Text';

enum QuestionType {
  Text = fails,
  Text2 = works,
}
```

### 🙁 Actual behavior

When `fails` is used in enum, there is an error:

> Type 'string' is not assignable to type 'number' as required for computed enum member values.(18033)

### 🙂 Expected behavior

I can use `fails`, because to me it is equivalent to `works`.

### Additional information about the issue

Related to https://github.com/microsoft/TypeScript/issues/29718 ?

**Comment by ahejlsberg** [comment]
Enum members may be initialized by _constant expressions_ that compute string or numeric values. Constant expressions may reference `const` variables, but only if those variables have no type annotations. When enum member initializers reference variables with type annotations, they're considered non-constants to be computed at run-time. Such computed enum members are restricted to numeric values. See #50528 for the exact rules.

**Comment by RyanCavanaugh** [comment]
> Constant expressions may reference const variables, but only if those variables have no type annotations

I think this is probably the thing that sounds surprising, but presumably it's to ward off problems like this?
```ts
// Correct emit is ... ?
const fails: number | 'Text' = 'Text';
```

**Comment by ahejlsberg** [comment]
> but presumably it's to ward off problems like this?

That's one reason, but another is to avoid circularities. Imagine that a type annotation depends on the enum type for which we are in the process of evaluating constant expressions.

**Comment by Andarist** [comment]
Isn't @RyanCavanaugh argument already somewhat trumped by allowing this in other similar situations like this one?
```ts
// input
const one: number | "Text" = "Text";
const two = one;

// dts output
declare const one: number | "Text";
declare const two: "Text";
```

I also found a confusing error to be reported in a related situation:
```ts
const a = E.two; // A member initializer in a enum declaration cannot reference members declared after it, including members defined in other enums.(2651)
const b = `pre${a}`;

const enum E {
  one = "foo",
  two = `${E.one}bar`,
}
```

The location of the error seems to be wrong. It mentions a member initializer but the error node is completely different. On top of that, the referenced enum member doesn't depend on any member declared after it.

This problem goes away if we remove `const b` completely or if we annotate `const a` with `E.two` or similar.
