### ISSUE TITLE
Allow generic instances with private field function of type `(param: T) => any` to be assignable to wider type.

### ISSUE THREAD

**Issue by robbiespeed** [microsoft/TypeScript#57209]
### 🔍 Search Terms

unknown, generics, private fields, collection types, derived, mapped, bivariant, covariant

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Make generic class instances with functions assigned to private fields bivariant the same as instance methods.

Currently such classes cannot be assignable to wider counterparts like `number[]` is assignable to `unknown[]` or `(0 | 1)[]` to `number[]`.

This restriction only holds true for code within the project once `.d.ts` files are generated private fields get stripped away.

### 📃 Motivating Example

A good example of where this limitation causes issues is with a readonly class which function is to act as a derived value of an input, it receives an input box object and a derive callback.

```ts
interface Box<T> {
  get(): T;
}
class Mut<T> implements Box<T> {
  #value: T;
  constructor (value: T) {
    this.#value = value;
  }
  get(): T {
    return this.#value;
  }
  set(value: T) {
    this.#value = value;
  }
}
class Derived<T, U> implements Box<U> {
  #input: Box<T>;
  #derive: (value: T) => U;
  constructor (input: Box<T>, derive: (value: T) => U) {
    this.#input = input;
    this.#derive = derive;
  }
  get(): U {
    return this.#derive(this.#value.get());
  }
}

const d: Derived<unknown, unknown> = new Derived(new Box(2), (value) => value.toString());
```

In that example the last line will result in the following type error:
```
Type 'Derived<number, string>' is not assignable to type 'Derived<unknown, unknown>'.
  Types of property '#derive' are incompatible.
    Type '(value: number) => string' is not assignable to type '(value: unknown) => unknown'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'unknown' is not assignable to type 'number'.(2322)
```
[TS Playground](https://www.typescriptlang.org/play?jsx=0#code/JYOwLgpgTgZghgYwgAgEIHsAeAeAKgPmQG8AoZZAcwjAAoBKALmVwG4SBfEhAGzgGc+yALIBXMHkLAAtgAduEKRHCCMOAsTLIAxADc43ERCatNCdCD5goIhGHRRkNPQaPM6G8uTAALYHwB0uvqGyAC8yM6GbOSc5FS0jMwenlDUIlAgyD5+gZEQ0cixyHzUTsGuuO6knlm+AUEuYRHlBZycPPyCACLQwDoQACZ4ADTIAKqSsvKKymhY2BPJWqAyYkyqEgVaA739TGUuxu6hhGMFZhZWNnYONCtrc2r4oztQfa4Hhkdhp1WaXnVAvcwE1gQUATltrsUOFXu9Wpp4vQmGNkuRUmB0plsvU4f0aDigSBVmB-Ei6HQEZwuOZLMgBkwem9+kMRCAANYgdAAdxAozZnJ5IEI4RAEG5yCZ7wGNDFEtEtAATHRRp8IMdCHl-HYAMpWUAUeiUoA)

Technically the type checker is correct, you wouldn't want a function that accepts `number` to be put somewhere where it could be called with `unknown`. However given the implementation this function cannot be called externally, and we hold no such restrictions on methods like the examples `Mut set(value: T)`. If there were such restrictions on methods then assignments from `number[]` to `unknown[]` would not work.

Again if the last line were application code there would be no error because private members get stripped from `.d.ts`.

### 💻 Use Cases

> What do you want to use this for?

Classes that are passed callbacks for internal use.

> What workarounds are you using in the meantime?

There are 2 workarounds I know of (described using motivating example):

**1.** Avoid using generic param in the stored function, by replacing it with `any`:
```
  #derive: (value: any) => U
```

This is less than ideal because you lose type safety inside your class code.

**2.** Make the type of the function itself generic and extend the original generic param:
```
  #derive: <TT extends T>(value: TT) => U
```

This is a ideal option since it preserves type safety, but it's unclear why this works and the original does not. Though a simpler example of forcing bivariance like this can be produced with generic functions [TS Playground](https://www.typescriptlang.org/play?jsx=0#code/JYOwLgpgTgZghgYwgAgGImQHgCoD5kDeAUMlttshAB6QgAmAzsngBQBuAXM9gJRcNgooAOYBuIgF8iRBAHsQA5DFmyu6TCACuAWwBG0fAF5k7OABtNEHskP425ywDows1MCoQ6LHuOWyWAEw+MvKKunBQaiCYmiAA1iCyAO4gRkoq4uFQLABEAHKyYMhwyFp60Dk+yAD01cgASrFgwNoo0FCyUEA)

**3.** Explicitly declare both type parameters to be covariant with the use of `@ts-expect-error` or `@ts-ignore`:
```
class Derived<
  //@ts-expect-error
  out T,
  out U
> implements Box<U> {
```

This has the same benefits as option 2, and is probably easier to understand.

**Comment by fatcerberus** [comment]
> Technically the type checker is correct, you wouldn't want a function that accepts number to be put somewhere where it could be called with unknown. However this function cannot be called externally

The type check still applies because *other* instances of the same class can access the private field.

> and we hold no such restrictions on methods

The method exception is an intentional unsoundness left in to keep arrays and similar container types covariant.  It is not a good argument against this behavior because the same restriction applies to other function-typed fields, private or not.  For example if you declare `set` as a (public) field instead of a method then the same error happens.

**Comment by fatcerberus** [comment]
I think you're ultimately asking for one of two things:

1. Private fields shouldn't influence the type of a class at all
2. Standard (non-method) function types should be treated as bivariant *only* when they're the type of a private field, even under SFT.

1 is untenable because, as I said, other instances of the same generic class but different type argument(s) can access the field, and it's entirely possible that the only use of a type parameter is in the type of a private member.  2 is asking for a pretty narrow special case, which would likely be rejected on principle.

I think the only solution you have if you *really* need this to work is to turn off `strictFunctionTypes`.

**Comment by robbiespeed** [comment]
Interestingly 1 is already the case once .d.ts is generated, so it wouldn't be that far fetched. It's also wouldn't solve the issue, you'd lose type safety inside the class unless TS was smart enough to split the class into internal and external types. In which case it would still need to internally treat private field functions as bivariant, and externally behave like the .d.ts output (privates have no impact).

> I think the only solution you have if you really need this to work is to turn off strictFunctionTypes.

Not something I would consider doing as it would affect the whole project.

**Comment by fatcerberus** [comment]
> It's also wouldn't solve the issue, you'd lose type safety inside the class

That’s true, but what you’re proposing—bivariant private function types—*also* loses type safety inside the class, if the field is accessed by other instances.

**Comment by RyanCavanaugh** [comment]
> Interestingly 1 is already the case once .d.ts is generated

*This* is the bug, not the correct treatment of variance in this case. It's simply unsound to allow the assignment to occur.

**Comment by robbiespeed** [comment]
@RyanCavanaugh is the second workaround of a function becoming bivariant when it is generic intentional? I hope so, because I am relying on it for library code, and the only other option would be `any` which is more unsound.

**Comment by RyanCavanaugh** [comment]
"intentional" is maybe a stretch; *ideally* this would be checked but doing this in the past has been fairly catastrophic in terms of performance and inducing unwanted circularity errors. I suspect you'll be able to "get away with it" for quite a long time.
