### ISSUE TITLE
5.3: const-like inference of arrays no longer requires readonly modifier

### ISSUE THREAD

**Issue by conorbrandon** [microsoft/TypeScript#57217]
### 🔎 Search Terms

5.3 const type parameter const like array readonly 

### 🕗 Version & Regression Information

- This changed between versions 5.0.4, 5.1.6, 5.2.2 and 5.3.3, 5.4.0-dev.20240129

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.3#code/MYewdgzgLgBADgJwKYDcCWICuEBCSAWAhuiAjALwwA8oksAKjEgB5RJgAmEMyhH4AGwCeMaAjRgA5gG0AugD4AFFABcMegEoK8mFADcAKFrRdSaAAVkJbBXhWM2PERIJF0gEQAzECHeyNhgD0gTChMAB6APwGRuAmYEgA7k7EGGSUNHEMTKzsXKJQ4lJySqrqWuQ6+rF0ptAAckm2CckEqaRuXj5+AQbBYRGRQA

### 💻 Code

```ts
const previousBehavior = <const T extends readonly string[]>(t: T) => t;
const testPrevious = previousBehavior(["foo"]);
//    ^?

const newBehavior = <const T extends string[]>(t: T) => t;
const testNew = newBehavior(["foo"]);
//    ^?
```

### 🙁 Actual behavior

`newBehavior` is able to infer `t` as `["foo"]` on 5.3+.

### 🙂 Expected behavior

I would expect `newBehavior` to infer `t` as `string[]` as it did on previous versions and a `readonly` modifier must be used to infer `["foo"]` (well, technically, `readonly ["foo"]`), as is mentioned is required on the [pull request](https://github.com/microsoft/TypeScript/pull/51865) and [announcement](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters) that introduced this feature.

### Additional information about the issue

I'm curious if this is expected behavior and can be relied upon in future versions. Thanks!

**Comment by MartinJohns** [comment]
> This changed between versions 5.0.4, 5.1.6, 5.2.2 and 5.3.3, 5.4.0-dev.20240129

I'm having a hard time believing it really changed between each of these versions.

**Comment by fatcerberus** [comment]
The change was intentional: https://github.com/microsoft/TypeScript/pull/55229

**Comment by conorbrandon** [comment]
Thank you for the quick reply and apologies for the duplicate issue. Feeling silly my search terms didn't find [#57107](https://github.com/microsoft/TypeScript/issues/57107), removing "5.3" from the search terms finds it🤦.
