### ISSUE TITLE
tsconfig.json - reference files

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#5721]
Hello,

I have a directory of ts files.
Each file is referencing same d.ts files using /// <reference ...

I was wondering if there is (or could be added) option in tsconfig to add static references that would be used for every file in the directory.

I know I can use "files" section in tsconfig, but I wish compiler to pick files automatically, I don't wish to add any new ts file manually to "files" section.

Thanks!

**Comment by DanielRosenwasser** [comment]
> I know I can use "files" section in tsconfig, but I wish compiler to pick files automatically, I don't wish to add any new ts file manually to "files" section.

I don't understand; your `/// <reference ... />`s are being manually added, so what's the issue with adding these files to the `files` section?

Alternatively, if the problem is that you have many `/// <reference ... />` comments, you could have a central `.d.ts` that references those, and have each file reference the central one.

**Comment by DanielRosenwasser** [comment]
Also see #1927 for a better overall solution.

**Comment by pankleks** [comment]
file wildcards would definitely solve my problem, I would then add:
>"files": ["../file1.d.ts", "../file2.d.ts", "*.ts"]

I have following directory structure:
* /root
 * file1.d.ts
 * file2.d.ts
 * /bin
   * tsconfig.json
    * userfile1.ts
    * userfile2.ts
    * ...
    * /bin2
      * userfile3.ts
      * ...

All user files needs reference to file1.d.ts and file2.d.ts
Since user files might be added dynamically, I don't wish to modify "files" every time a new file is created.
Also using /// <reference is painful, since I need to modify path at every user file as there might be multi-level depth directories.

Hope it's more clear now:)

**Comment by DanielRosenwasser** [comment]
Yes, I think globs are the key solution.

In the mean time, if all you have is source in that directory, you could just omit the `"files"` field entirely and use the `"exclude"` field to filter out what you *don't* want. For more details see here: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json
