### ISSUE TITLE
Organize Imports: Incorrect combination of imports with import attributes

### ISSUE THREAD

**Issue by k15a** [microsoft/TypeScript#57215]
### 🔎 Search Terms

"organize imports assert", "organize imports with", "organize imports assertions", "organize imports attributes"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "organize imports"

### ⏯ Playground Link

Playground doesn't support organize imports as far as I can tell.

### 💻 Code

In VSCode run the organize imports command on the following code:

```ts
import { A } from "./file";
import { type B } from "./file";
import { C } from "./file" assert { type: "a" };
import { A as D } from "./file" assert { type: "b" };
import { E } from "./file" with { type: "a" };
import { A as F } from "./file" with { type: "b" };

type G = A | B | C | D | E | F;
```

### 🙁 Actual behavior

Currently, organize imports will combine all the imports to the following line:

```ts
import { A, C, A as D, E, A as F, type B } from "./file";

type G = A | B | C | D | E | F;
```

### 🙂 Expected behavior

As import attributes can change the behavior of the imported module they should stay as separate lines:
```ts
import { A, type B } from "./file";
import { C } from "./file" assert { type: "a" };
import { A as D } from "./file" assert { type: "b" };
import { E } from "./file" with { type: "a" };
import { A as F } from "./file" with { type: "b" };

type G = A | B | C | D | E | F;
```

**Comment by iisaduan** [comment]
@k15a organize imports is removing all occurrences of `A`, including `A as` from your output? I'm seeing 
```
import { A, C, A as D, E, A as F, type B } from "./file";
```
which is still concerning, but different behavior.
