### ISSUE TITLE
Public property on class not inferred from type of type parameter

### ISSUE THREAD

**Issue by steveluscher** [microsoft/TypeScript#57222]
### 🔎 Search Terms

"infer class property", "refine class"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about classes.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYOwrgtgBAogTnA9nAwogJsAzlA3gKCiKgCEBBAESgF4oAGAGkOIBUYAldgSRIBkYaUAIxNiUMgHUAYgFVeggExMAvvnwAXAJ4AHYLATIKwdQEMAlgBsctAmIDa8JKgzYAdOQoBdAFx4oAdwALTV8sdTgzEABzKGVRYgcDZ0wsVzZOHn4fPyDgOGBQ8MiYuOYiRKc0FNdJWV5s3ADAxEKI6NiVNQBjCxMsHCrgdEdkAB4WQahgAA91UHQcEeTsQSXBrAA+PDKoLsQQMLgwLvVkAAp8k3R9i01dl18JlwYoS+uQW6hMU0ssXyWjD8rHYnphPABKPyqVT4PYHdRQMAgADWIEQ-hAS0E4AsFigfURKLRGPxAxcwySAG58GYAGZQM5I1HozFJVx7TA0ai0NYuVLpbh8GCQ2zEAD0YqgXACiDAFnQU2muhOUAABt9zFZVVBTlAAEZ6fK0yJDHWINUA4yarAVZDrNIcQVZbWBPLAVw7JnE1lOVwa35QLAmdRmLDGlaWoE23nVAWZGCealiOFYRAWd0WRBRRlEllLP1W36uXL5cHU5RAA

### 💻 Code

I have two public, readonly properties on a class: `code` and `details`. The type of `details` depends on the value of `code`.

```ts
enum ErrorCodes {
    BAD = 0,
    TERRIBLE = 1,
    AWFUL = 2,
}

type ErrorDetails = {
    [ErrorCodes.BAD]: { why: string },
    [ErrorCodes.TERRIBLE]: { where: string },
    [ErrorCodes.AWFUL]: { who: string },
}

class CodedError<TCode extends ErrorCodes = ErrorCodes> {
    constructor(
        readonly code: TCode,
        readonly details: ErrorDetails[TCode],
    ) { }
}
```

### 🙁 Actual behavior

When I make an assertion on the value of `code` I would expect that to refine the type of `details` but it doesn't seem to in this example:

```ts
const unknownError = null as unknown as CodedError;
if (unknownError.code === ErrorCodes.TERRIBLE) {
    unknownError.details satisfies ErrorDetails[ErrorCodes.TERRIBLE]; // ERROR
    console.log(unknownError.details.where); // ERROR
}
```

### 🙂 Expected behavior

After having asserted that `code === ErrorCodes.TERRIBLE` I would expect `details` to be refined to `ErrorDetails[ErrorCodes.TERRIBLE]`.

**Comment by RyanCavanaugh** [comment]
What you have here is the same as if you had written
```ts
declare const unknownError: CodedError<ErrorCodes>;
```
which is the same as you'd get if you wrote
```ts
const unknownError = new CodedError<ErrorCodes>(ErrorCodes.AWFUL, { why: "not actually ok "});
```
which shows that it's not safe to perform that narrowing

**Comment by RyanCavanaugh** [comment]
Put another way, having a `Foo<A | B | C>` is not the same as having a `Foo<A> | Foo<B> | Foo<C>`

**Comment by steveluscher** [comment]
Though I don't love the API, when I jam everything on to _one_ property of the class I can get the effect I want – albeit my customers will have more characters to type.

```ts
type ErrorConfig = Readonly<{
    [P in ErrorCodes]: ErrorDetails[P] & { code: P, }
}>

class CodedError<TCode extends ErrorCodes = ErrorCodes> {
    constructor(readonly details: ErrorConfig[TCode]) {
    }
}

const unknownError = null as unknown as CodedError;
if (unknownError.details.code === ErrorCodes.TERRIBLE) {
    unknownError.details satisfies ErrorDetails[ErrorCodes.TERRIBLE]; // OK
    console.log(unknownError.details.where); // OK
}

new CodedError<ErrorCodes>({ code: ErrorCodes.AWFUL, why: "not actually ok " }); // ERROR
new CodedError<ErrorCodes>({ code: ErrorCodes.AWFUL, where: "not actually ok " }); // ERROR
new CodedError<ErrorCodes>({ code: ErrorCodes.AWFUL, who: "you!" }); // OK
```

([Playground link](https://www.typescriptlang.org/play?#code/KYOwrgtgBAogTnA9nAwogJsAzlA3gKCiKgCEBBAESgF4oAGAGkOIBUYAldgSRIBkYaUAIxNiUMgHUAYgFVeggExMAvvnwAXAJ4AHYLATIKwdQEMAlgBsctAmIDa8JKgzYAdOQoBdAFx4oAdwALTV8sdTgzEABzKGVRYgcDZ0wsVzZOHn4fPyDgOGBQ8MiYuOYiRKc0FNdJWV5s3ADAxEKI6NiVNS1dfUrEEAAzMxjadmATdH6LTQAeWwSABShI3uQq7GzHQ2NzKzsFzygAMj8AYxdfBYZY-GUAPjVTixMsHHX0LbgZlnWoYAAPdSgdA4T7rayrZLYO54MpQc4gMJwMCndTIAAU+QmU00UEwpksWF8YP6Qyidh+Lk8AEpYWJVKp8AiwlAwCAANYgRD+ECfQTgCwWKAvVkcrk84VvFwfJIAbnwZgGUHRbM53N5SVc+N2qXOmBo1FoJOq6W4fBgtPmRFV4o1Ti1O0JUCwJnUZiwQ2wkKMBL2xrcpsyME8sqgAHow1AAPIAaThzMQFmArgsiCiKrF6s+Dt9qVy+WpoYj0bjjJAwH8UHenxm-qwd3RjT1BUh4Jq0jk1yCISgACIuephaiwCZBbjEOy+7FC-hy5Xq0la0lwQ2mxdWy5UrVO008i3+4hByZh6PplAJ1PlDO51XpTW66v4eu6+26l3mr5e5pEGAAIS96dZSAA))
