### ISSUE TITLE
How to increase the priority of custom overloaded function signatures?

### ISSUE THREAD

**Issue by gwsbhqt** [microsoft/TypeScript#57226]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I'll give you an example, actually it's just an example, the discussion point is not the example itself.

I wrote a setTimeout function and found several signatures, and they have an order.
- @types/node/timers.d.ts
- typescript/lib
<img width="1922" alt="image" src="https://github.com/microsoft/TypeScript/assets/16471930/f2a17bb4-d98c-4b2b-ba52-f8d8d11054aa">

I was not satisfied with the signature they provided, so I decided to customize the signature of the "reset" function.
I know to use window.setTimeout, but the point is not to discuss that. Because there are many other functions that also have this situation.

```
// src/typings/reset.d.ts

declare function setTimeout(callback?: () => void, ms?: number): number
```

This is good, he works, the type signature of the function is already loaded, and they have an order.
- @types/node/timers.d.ts
- typescript/lib
- src/typings/reset.d.ts
<img width="1926" alt="image" src="https://github.com/microsoft/TypeScript/assets/16471930/bde783a4-19b7-4b48-a2c8-3476106da005">

But when I start to actually write code, this time the return value will be determined because the imported parameters match, and everything changes.
<img width="1926" alt="image" src="https://github.com/microsoft/TypeScript/assets/16471930/b21a42e2-be5a-454c-b70a-9a177000002a">

This is not what I expected. What about the custom function signatures in reset.d.ts that I expected?

And how to control the signature order of typescript loading? make

- @types/node/timers.d.ts
- typescript/lib
- src/typings/reset.d.ts

to

- src/typings/reset.d.ts
- @types/node/timers.d.ts
- typescript/lib

**Comment by RyanCavanaugh** [comment]
When two interface declarations merge and they have function overloads that need to merge, the overloads from the "later" interface (the one that appears later in the file list) go "above" (which means higher-priority) the overloads from the earlier interface. So if you have higher-priority overloads, you want the file that provides them to be a close to the bottom of the files list as possible.

**Comment by fatcerberus** [comment]
> So if you have higher-priority overloads, you want the file that provides them to be a close to the bottom of the files list as possible.

Hmm... is compilation order deterministic, esp. in cases where `includes` uses glob patterns?  If so, this could be potentially fragile.

**Comment by RyanCavanaugh** [comment]
Our `readdir` function sorts file / directory names

**Comment by gwsbhqt** [comment]
Thank you for your reply. Your reply saved my day!

I changed the typings directory to the _typings directory (to make the custom type directory lexicographical before node_modules), and the "priority" takes effect when vscode looks at the type.

But when I use tsc --build --onlyDeclaretion to do type checking, I find that it doesn't take effect. Does this rule also follow when using tsc --build?
