### ISSUE TITLE
Different behavior between sub enum in the same file or in a different file

### ISSUE THREAD

**Issue by MohammadYounes** [microsoft/TypeScript#57234]
### 🔎 Search Terms

"ts enum reverse mapping"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about enums handling

### ⏯ Playground Link

https://playcode.io/1743524

### 💻 Code

```ts
// enum.ts
export enum MainEnum {
  itemA = 'A',
  itemB = 'B',
  itemC = 'C'
}
export enum SameFileSubEnum {
  itemA = MainEnum.itemA,
  itemB = MainEnum.itemB
}

//another-file.ts
import { MainEnum } from './enum'
export enum AnotherFileSubEnum {
  itemA = MainEnum.itemA,
  itemB = MainEnum.itemB
}

//main.ts
import { SameFileSubEnum } from './enum'
import { AnotherFileSubEnum } from './another-file'
console.log('SameFileSubEnum [No Reverse Mapping]', SameFileSubEnum)
console.log('AnotherFileSubEnum [Reverse Mapping Applied]', AnotherFileSubEnum)
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/4712046/95675e2c-e43e-4553-8f14-1cc6145a6ec3)

### 🙂 Expected behavior

For both enums to be the same

**Comment by RyanCavanaugh** [comment]
I can't repro this with tsc. I suspect playcode is using its own transpiler.

**Comment by MohammadYounes** [comment]
I tired this with tsc and couldn't produce either.  I think it's caused by babel. 
Thanks.

**Comment by fatcerberus** [comment]
Yeah, Babel transpiles modules individually, doesn't care about type info and doesn't resolve imports.  This is why computed enum members are required to be numbers now.

Is this an error under `isolatedModules` (which should be used if transpiling with Babel)?  I'd be surprised if it wasn't.

**Comment by MohammadYounes** [comment]
I get the same behavior regardless of `isolatedModules`.

**Comment by fatcerberus** [comment]
No, I was wondering if `tsc` considered this an error with isolatedModules on (exactly because this behavior is the natural consequence).
