### ISSUE TITLE
Can not assign a generic function to a normal function

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#5723]
```typescript
function f<T>(){
	return 1;
}

var a = f<number>;
```
the error is: `error TS1005: '(' expected.`
this is OK:
```typescript
function f<T>(){
	return 1;
}

var a = () => {
	return f<number>();
};
```

**Comment by ahejlsberg** [comment]
That is by design. You can only supply type arguments in a call expression. For purposes of function assignment compatibility checking, generic functions are implicitly instantiated using type `any`, so your assignment should work if you simply say `a = f`.
