### ISSUE TITLE
Inconsistent behavior of `Object.assign()` in the constructor of parent class

### ISSUE THREAD

**Issue by hnguy311** [microsoft/TypeScript#57258]
### 🔎 Search Terms

"inheritance property override", "inheritance property assignment", "Object.assign in parent class"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Classes"

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG8BQ0PQGYHscH4AuaCAFwCcBLAOwHMBuVdTYHas8gV2FJ3IAocAIwBWxAAphypSmBAAeeBAQA+AJQpmmTAHlRCHgDpIESrWr9SAC0oQANNGEi1jbdtbscIBIZA5aljYQLlrQAL6oEaigJtAAwjYgACbQCAAepAjUSTBKSGjaQlJEJBQ0DKEA7nJJONAAvNAA5MCJKdXJOE2MoR4c3LwCThJSMnLyCZTJ6ppumBCcAA4IQ6Ih2hFRfV4+fgHUCJXxbfzI2HjETbhdDkXkl3dNDh21ly9d4WpqqEA

### 💻 Code

```ts
class Base {
    foo?: string;

    constructor(obj: Partial<Base>) {
        Object.assign(this, obj);
        console.log(this);
    }
}

class Child extends Base {
    bar?: string;
    waldo = 'child waldo';

    constructor(obj: Partial<Child>) {
        super(obj);
    }
}

console.log(new Child({ foo: 'foo', bar: 'bar', waldo: 'waldo' }))
```

### 🙁 Actual behavior

The final `Child` object only copies the value from `bar` and does not do so for `waldo`, resulting in the following console log:

```
Child { foo: 'foo', bar: 'bar', waldo: 'waldo' }
Child { foo: 'foo', bar: 'bar', waldo: 'child waldo' }
```

### 🙂 Expected behavior

I expect both `bar` and `waldo` in the final `Child` object to either

- take the corresponding values of the object passed into the child's constructor and output the following:

```
Child { foo: 'foo', bar: 'bar', waldo: 'waldo' }
Child { foo: 'foo', bar: 'bar', waldo: 'waldo' }
```

- or does not overwrite the child's default values at all, which would output the following:

```
Child { foo: 'foo', bar: 'bar', waldo: 'waldo' }
Child { foo: 'foo', bar: undefined, waldo: 'child waldo' }
```

### Additional information about the issue

The second expected result is the behavior of pure Javascript, as shown in [this example](https://jsfiddle.net/4spma6Lz/).

```js
class Base {
    foo;

    constructor(obj) {
        Object.assign(this, obj);
        console.log(this);
    }
}

class Child extends Base {
    bar;
    waldo = 'child waldo';

    constructor(obj) {
        super(obj);
    }
}

console.log(new Child({ foo: 'foo', bar: 'bar', waldo: 'waldo' }))

// Output:
// Child { foo: 'foo', bar: 'bar', waldo: 'waldo' }
// Child { foo: 'foo', bar: undefined, waldo: 'child waldo' }
```

**Comment by whzx5byb** [comment]
Turn on [useDefineForClassFields](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) and you will get the second expected result.

**Comment by hnguy311** [comment]
Thank you! That works perfectly!
