### ISSUE TITLE
Array.isArray does not narrow return type of function

### ISSUE THREAD

**Issue by gutentag2012** [microsoft/TypeScript#57268]
### 🔎 Search Terms

Array.isArray type narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type narrowing

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-dev.20240202#code/GYVwdgxgLglg9mABFATjAtgZVTMBzAeRQEEUUBDATwAoAoRRXABxCgC5EBnHfRAHy488AbQC6tAJQcolJgFM4wRmBZREcgB5Q5YACadBafGMQB+Q7hGjEHbkbyIA3vUZLqpCpQB0MTh6rUzKwSEk4uDChyUCAoSEFQXujkTNQGALwAfFxeOOjUIQDcLgC+LpHRscqqOWh5EkXFBUA

### 💻 Code

```ts
function trimStringOrArray(
  input: string | string[]
): typeof input extends string[] ? string[] : string {
  if (Array.isArray(input)) {
    return input.map(s => s.trim());
  }
  return input.trim();
};
```

### 🙁 Actual behavior

After checking the input whether it is an array, typescript expects the return type to be a string

### 🙂 Expected behavior

With the input being a string array, the function return type should also be a string array

**Comment by gutentag2012** [comment]
As a note, this also does not work when using a generic type like this

```typescript
function trimStringOrArray<I extends string | string[]>(
  input: I
): I extends string[] ? string[] : string {
  if (Array.isArray(input)) {
    return input.map(s => s.trim());
  }
  return input.trim();
};
```

**Comment by varganatt** [comment]
The reason for this is that you're confusing type-space and value-space.

You have defined `input: string | string[]`, so `typeof input` is equivalent to `string | string[]`. This type does not extend `string[]`, so `typeof input extends string[] ? string[] : string` is equivalent to just `string`.

What you should do instead is use overloads:

```ts
function trimStringOrArray(input: string): string;
function trimStringOrArray(input: string[]): string[];
function trimStringOrArray(input: string | string[]): string | string[] {
   if (Array.isArray(input)) {
    return input.map(s => s.trim());
  }
  return input.trim();
}
```
