### ISSUE TITLE
where is TypeScript Language Specification pdf file ?

### ISSUE THREAD

**Issue by ghyaoutlook** [microsoft/TypeScript#57278]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

where is TypeScript Language Specification pdf file ?

**Comment by MartinJohns** [comment]
There is no specification.

**Comment by fatcerberus** [comment]
TypeScript as it exists today has no specification.  Git history is public so you can find the old version if you go back far enough, but that document is *very* old and outdated, and likely isn't useful for anything except historical curiosity.
