### ISSUE TITLE
Extension method on interfaces and objects as in C#

### ISSUE THREAD

**Issue by muhamedkarajic** [microsoft/TypeScript#57280]
### 🔍 Search Terms

typescript extensions for interfaces

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I think a lot of people would like this feature of being able to simply call a method in the way we can do it in C#.

### 📃 Motivating Example

E.g. if you have

interface InterfaceA {

}

that you can assign to it an extension method e.g.

function functionA(interface: Interface) { }

Then you simply can do 

object: InterfaceA;
object.functionA();

### 💻 Use Cases

1. What do you want to use this for?
Everywhere cause it makes the code more simple.
2. What shortcomings exist with current approaches?
It could be that e.g. InterfaceA has already a method called functionA. That would have to be considered.
3. What workarounds are you using in the meantime?
None.

**Comment by MartinJohns** [comment]
This is explicitly out of scope for TypeScript.

You wrongly checked this:

> This could be implemented without emitting different JS based on the types of the expressions

**Comment by xiBread** [comment]
Also a duplicate of #45968

**Comment by muhamedkarajic** [comment]
> This is explicitly out of scope for TypeScript.
> 
> You wrongly checked this:
> 
> > This could be implemented without emitting different JS based on the types of the expressions

My bad.



> Also a duplicate of #45968

Ty!
