### ISSUE TITLE
TypeScript cannot infer type arguments correctly when swapping function parameters.

### ISSUE THREAD

**Issue by webvv** [microsoft/TypeScript#57287]
### 🔎 Search Terms

It's been 2 years that I'm playing with higher order functions and kinds. This is part of my effort on creating a course of "Functional Programming with TypeScript". You can find the content [here](https://www.youtube.com/watch?v=Z3PLwD3iebg&list=PLuPevXgCPUIMbCxBEnc1dNwboH6e2ImQo).
I'm working on a next video to teach "Functor composition", but I'm getting to a strange behavior on argument inference that I cannot reason about. You have an example of what I'm working on (`compose` function) in the [docs here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#higher-order-type-inference-from-generic-functions).
What baffles me is why swapping place of arguments in the compose function, makes my examples for higher kinded types fail. I've explained this completely in a question with a sample snippet of code and playground in [StackOverFlow here](https://stackoverflow.com/questions/77934689/why-one-of-my-compose-functions-cannot-infer-types). I'm trying this with the latest version of TypeScript.

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type inference.

### ⏯ Playground Link

[Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8mwEsD2A7APAQQHxQLxQGUkBbCTHAHygDlUIAoehFYCAJwDMBDAY2iNLkoAb3pQoAfWBcA5gC4oAcgERFYqADcuAGwCuEBRnoBfRs1ade0WimijxU2QsU3VJxj1QBnYFC8lofEwAGiwACgAPQwBKBThEVCFcHHUw4UlpeSUVRWDNHX0FCKhjaI9vXxQ6OPhkdFsNdhx8dXTHLJc6RRLylB8oBC9XPCgQ8KjYWsTsWKhiwZo6PBTxCIA6drxcfE7bNXoAegOoAFoz84vLy8ZQSCgAUQRgAAt2NHu87BGAGQgOYHelCgACUEDJngDsGYWOxuHwoL9-oCROp2s5EcA1OJtH9gAp7u4mDDLPDQeDITh7BknEoyRCsVA2GCIYZCZ4+r4cf8Ru9ghhcA0mpF8bMHk9XmxeVAvskoGlqR0MbkoFy8XNSvR2f0meSeRhgvcBRBGmxxjEFGKXm8PtLmjh5WjaczMXkdSz1WVNRUBl4MTybdgwlx8eLrZ8sLMuD6EbjkbL1FwNpktjslYxDscrlms9CLHDoABVYEASWASAA0swACYARiEVPEinidUUNQS6ChpiJeasUCLpYr1YATLyvg2lI8rWxW5aJaOsITboWSwQayMANYQEBIDh9ktlysoWtoLgoEALpd74sEIcbrc7q8H4cns95U-nm7gaCH4-9qAQCJWCPLwr1XcMRn7J8jzrbAAG1+wAXXoS8fxHP8AKAqsQP7G88gDZpH0HI8Rw+ODEM-O4AAlywAFTrftwPwdJ+wUfsAG4oGDaUSg45CvygaiaLQktPjyAAhAjmJLViSw4riMA4gAjBQxJKcRc1hXsADFdBQHgyzYOstP-QCIGA0Ca0pdRxDYCAuCrVBtBAK8FC06yoGILgwAUEIoAksIOAUIMYmWPzolCgKuJ-Izw3C2VorQLTxIXLtzE0+EdL0gyR2MjCzKw0Chys8QbLshyUCclyoDckqPK8nyA2SgKgvkuKcDEtq5W4BRUMSvDYtC3qkoeZLCTSkloEy-SkElLTipK2z7Mc5yWOq9zPO80Z9T88JArlVrQo6iLuoE2iYttTrBPOiTCSOU5swe7Nen6JAphQKaDNc3TpsMtAmzexRJPUVb-vbXJ1A2nz9X8vbhWlTqjtlSK2zqchZmbRIJNC9zBlcSLwoAfigKpbCgBR-FIALIrWLQ9AgaIyi7LVfAgUM2A+mavqymaR0UScJUBkYqRB-n2HB8RIdGUjghhoKJgwBHOuR2cwwukMpylLH41qwYMXxqAie4MnGWdKnuDWN1gAZ27M0eu3rj4u4AGESDAJAvECLbxLyJ3wnUWGJkRnAnbydQsjhhXDvoJX5c6p3nt8TxiDdj2FBd5P3c91IODyGROuKWUODCGRImtx3oHTlOIGBPVvagX2wjDuWQtlMTgn95uwtCp2oGjiLY+7hOoCTqvgTT13M5rlpxGLvIOHz0Ki5LiIy7u+317OCjoGLPTbNIFgRjhlBdGIRT2E64-T-YL0OQGXeIH3tUd54PezN8fAC5wCIAGoay3qAaJIAIMAJkKAZAyEPhMS+Z82CdR8KAmQN9+hlmAQgrIgDUHMHASMT+UAAAGAASYQERjB4KHiPTOVYRgUI9mEFBICsEyDyMwF+D835lGZsPCeHsqxTy4RnD2wIwgsNfiwPI9C0EcO4RAKsYQaxDnCuIO6AAiGsABmZRXoBEyKEfIxRUAVHqM0RmABzwFge30nUfhYAEA4hAkgdcnEjxQCXCBZgHB2C2SoZ4Ngtl9KVQAO6vBQNY92WCoAcG+u2LwaxGBrw3vbIeG01z4Feu2DmbA1gbSQb4Dat58CsynBkrJXlyHSNrNQ6RYRkl5Dyfo2qd00DbHwHkqAzwuAgU8TNJxVDXHD1PFUXwZ874eN8TIrhYz-EgByaEnh+TZnV2qV5GstSvIKNqko44TTth1TALeBYDi2nsAgAAQjiccGibBnJeACU8HgZiwG7LXKeKheS1hQAAOrPGcswfBNCZE1jwQAr8BAX4IHgP0lAgyRnsBcV+ECPi-HACckTZ4SAAmQqgMWCJCB5jAAJowIAA)

### 💻 Code

Unfortunately this is the smallest snippet of code I could shrunk the issue to:

```ts
type Option<A> = Some<A> | None

interface Some<A> {
  _tag: 'Some'
  value: A
}

interface None {
  _tag: 'None'
}

const some = <A,>(x: A): Option<A> => 
  ({ _tag: 'Some', value: x })

const none: Option<never> = 
  { _tag: 'None' }

const isNone = <A,>(x: Option<A>): x is None => 
  x._tag === 'None'

// --------------------

type Either<E, A> = Left<E> | Right<A>

interface Left<E> {
  _tag: 'Left'
  left: E
}

interface Right<A> {
  _tag: 'Right'
  right: A
}

const left = <E,A=never>(x: E):  Either<E, A> => ({ _tag: 'Left', left: x})
const right = <A,E=never>(x: A):  Either<E, A> => ({ _tag: 'Right', right: x})

const isLeft = <E, A>(a: Either<E, A>): a is Left<E> => 
  a._tag === 'Left'


// --------------------

interface URItoKind1<A> {
    'Option': Option<A>
}

interface URItoKind2<E,A> {
    'Either': Either<E,A>
}

type URIS1 = keyof URItoKind1<any>
type URIS2 = keyof URItoKind2<any, any>

type Kind1<URI extends URIS1, A> = URItoKind1<A>[URI]
type Kind2<URI extends URIS2, E, A> = URItoKind2<E,A>[URI]

type HKT1<URI, A> = { URI: URI; a: A }; 
type HKT2<URI, A, B> = { URI: URI; a: A; b: B }  

interface Functor1<F extends URIS1> {
    readonly URI: F
    map: <A, B>(f: (a: A) => B) => (fa: Kind1<F, A>) => Kind1<F, B>
}

interface Functor2<F extends URIS2> {
    readonly URI: F
    map: <E, A, B>(f: (a: A) => B) => (fa: Kind2<F, E, A>) => Kind2<F, E, B>
}

interface Functor<F> {
    readonly URI: F
    map: <A, B>(f: (a: A) => B) => (fa: HKT1<F, A>) => HKT1<F, B>
}

// --------------------------

const optionFunctor: Functor1<'Option'> = {
  URI: 'Option',
  map: <A,B>(f: (x: A) => B) => (fa: Option<A>): Option<B> => 
    isNone(fa) ? none : some(f(fa.value))
}

const eitherFunctor: Functor2<'Either'> = {
  URI: 'Either',
  map: <E,A,B>(f: (x: A) => B) => (fa: Either<E, A>): Either<E, B> => 
    isLeft(fa) ? fa : right(f(fa.right))
}

// ---------------------------

type Compose = <A, B, C>(
  f: (x: B) => C, 
  g: (x: A) => B
) => (x: A) => C

const compose: Compose = 
  (f, g) => x => f(g(x))

type ComposeR = <A, B, C>(
  g: (x: A) => B,
  f: (x: B) => C 
) => (x: A) => C

const composeR: ComposeR = 
  (g, f) => x => f(g(x))

// ---------------------------

type Increment = (x: number) => number
const increment: Increment = x => x+1

type ToStringg = (x: number) => string
const toStringg: ToStringg = x => `${x}`

const composed = compose(toStringg, increment)
const composedR = composeR(increment, toStringg)
composed(12)   // "13"
composedR(12)   // "13"

// This section compiles ok and types inferred correctly when composing functions.

// ---------------------------

const map1 = optionFunctor.map
const map2 = eitherFunctor.map

const composed1 = compose(map1, map2)       // <=== map2 has error and types cannot be inferred correctly
const composed2 = composeR(map1, map2)      // <=== map2 is ok here!

// Try switching map1 and map2. Why in `composed1` TypeScript cannot infer types correctly? how can I fix it?
```

### 🙁 Actual behavior

Type inference on compose function is not working as expected. This is from the snippet and sample code above.
```ts
// ...
const composed1 = compose(map1, map2)       // <=== map2 has error and types cannot be inferred correctly
const composed2 = composeR(map1, map2)      // <=== map2 is ok here!
```

### 🙂 Expected behavior

In both ways of composing `map` functions (`map1`, `map2`), typescript could infer generic type arguments correctly.

### Additional information about the issue

This code is heavily influenced by [fp-ts library](https://github.com/gcanti/fp-ts). (I've already investigated the library. The library has a `flow` function that is implemented similar to the `compose` function in the [TypeScript docs here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#higher-order-type-inference-from-generic-functions), but there are no function like my `compose` function there that parameters are swapped. 
The way I implemented the `compose` function and choosing the arguments order is based on the Composition-Operator in Math and Haskell for when we try to compose functions: (`f o g` in Math and `f . g` in Haskell means call `g` with the input parameter first and then call `f` with the output of `g`, and return)

**Comment by jcalz** [comment]
Cross-linking to #30215, this is working as intended, perhaps this issue should be reworded as a feature request.
