### ISSUE TITLE
Constructor parameters of `BigInt` which is lost `BigInt`, `String`, `Boolean`, `Number` type

### ISSUE THREAD

**Issue by NWYLZW** [microsoft/TypeScript#57283]
### ⚙ Compilation target

ES2020

### ⚙ Library

TypeScript

### Missing / Incorrect Definition

```ts
interface BigIntConstructor {
    // wrong
    (value: bigint | boolean | number | string): bigint;
    // right
    (value: bigint | BigInt | boolean | Boolean | number | Number | string | String): bigint;
}
```

### Sample Code

```TypeScript
declare const n: unknown

if (n instanceof BigInt) {
  BigInt(n)
  //     ^? TS2345: Argument of type BigInt is not assignable to parameter of type string | number | bigint | boolean
}

// ----

function foo(a: BigInt) {
  BigInt(a)
  //     ^? TS2345: Argument of type BigInt is not assignable to parameter of type string | number | bigint | boolean
}
foo(Object(BigInt(1)))
```

### Documentation Link

We can see in [21.2.1.1 BigInt ( value )](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-bigint-constructor-number-value) that [`2. Let prim be ? ToPrimitive(value, NUMBER).`](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-bigint-constructor-number-value:~:text=2.%20Let%20prim%20be%20%3F%C2%A0ToPrimitive(value%2C%20NUMBER).) corresponds to our situation and triggers [`ToPrimitive`](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-toprimitive).
`ToPrimitive` attempts to retrieve the `valueOf` method of the `Object`. For `BigInt`, `Number`, `String`, and `Boolean`, this method exists, allowing us to obtain a corresponding primitive value. Then, based on the `preferredType` of `NUMBER`, it is further converted to a number.
Our problem is essentially answered here, indicating that we should support `Boxed Types` as input.

<img width="211" alt="image" src="https://github.com/microsoft/TypeScript/assets/51358815/77871509-a243-49f4-9a26-7d1a80fcda5e">

#### about
* [MDN BigInt()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt/BigInt#parameters)

**Comment by MartinJohns** [comment]
This is intentional. The usage of these wrapper objects is discouraged. This is the same as #54059.

Also see the handbook: https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#number-string-boolean-symbol-and-object

> ❌ **Don’t** ever use the types `Number`, `String`, `Boolean`, `Symbol`, or `Object` These types refer to non-primitive boxed objects that are almost never used appropriately in JavaScript code.

You also shouldn't use `instanceof BigInt`, as this check will actually fail with primitive bigints: `5n instanceof BigInt // false`.

**Comment by NWYLZW** [comment]
1. I understand that TypeScript does not encourage the use of `boxed types`. However, as a runtime data validation module, I cannot guarantee whether the data received by the user at runtime has been boxed or not.

2. I am aware that instanceof cannot handle checks for `primitive`, so I have implemented an `unboxing` process.

https://github.com/typp-js/typp/blob/cd94af21d2c0bb9a73026df0e634e845841719e4/packages/validator/src/index.ts#L349-L353
