### ISSUE TITLE
Generic parmater with union type not working as expected (not assignable to parameter of type)

### ISSUE THREAD

**Issue by JasonMan34** [microsoft/TypeScript#57299]
### 🔎 Search Terms

union, generic, assignable, not assignable to parameter of type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union and generics

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBFCGBrApgZSgJwJZgOYwF4YAKAB3g3gFsAuGabPASkID4YBXMAE2QDMcybgG4AUKEiwEKAHIcqAI2QZCJcpVoww8pRhYF2XXgLBCxoqAE9SyGADEuwVVZsg+cJGkw58AHzjWyG4esjrK5hLQMFTICA5gTkQAPAAqMMgAHlDIPBD2jqzEfI50KQA0MOrUdAAKFNSxyhCprADaAAwAuvrsAN6iMDAA9EMwAIIYuPI5sMEutgDkDD4w-tqKygswWHlgILDwEBBYuGDwCgA2tlAglfUx2SpzgTALpgBumwB0A8OjKS8lt48Fsdlp9jBDsdTucrnBbvNXh9Nr9igkyPcmGIAL6iUQjGAAmzbMB8ZQ5YC2ADuIAwiDyh3SGRswGy3BgVIAFjkYMB4BcLisoNyYGjWVhwPjRhMpjEwLN3Ii3mEMKDdhCoSczpdrrcqg9lDBnsSgYxcAtRA94PFgMRpF4zRUAExMURAA

### 💻 Code

```ts
const takeString = (param: string) => undefined;
const takeNumber = (param: number) => undefined;

type Func = typeof takeString | typeof takeNumber;

const metaFunc = <T extends Func>(func: T, param: Parameters<T>[0]) => {
  // Argument of type 'string | number' is not assignable to parameter of type 'never'.
  // Type 'string' is not assignable to type 'never'
  func(param);
}

// Type inference works as expected when calling the function
// Argument of type 'number' is not assignable to parameter of type 'string'
metaFunc(takeString, 2)
```

### 🙁 Actual behavior

The `func` invocation is invalid. With the error:
```
Argument of type 'string | number' is not assignable to parameter of type 'never'.
  Type 'string' is not assignable to type 'never'
```

### 🙂 Expected behavior

TypeScript should recognize that since the same `T` is used for both `func` and `param`, the invocation of `func(param)` is valid. Similar to how it recognizes that `metaFunc(takeString, XXX)` should be called with a string rather than a `string | number`

### Additional information about the issue

Potentially related: https://github.com/microsoft/TypeScript/issues/51587, https://github.com/microsoft/TypeScript/issues/33912, https://github.com/microsoft/TypeScript/issues/30581

Note that this is different than `https://github.com/microsoft/TypeScript/issues/30581#issuecomment-476417974` since the same `T extends Func` is used for both `func` and `param`, rather than using `Func` for both types

**Comment by snarbies** [comment]
As defined, this is a valid invocation of `metaFunc`

```typescript
metaFunc<Func>(takeString, 3);
```

It might not be practical in your actual use case but in your example, this workaround is available:
```typescript
const metaFunc = <T extends string | number>(func: (arg: T)=>undefined, param: T) => {
    // ...
}
```

**Comment by JasonMan34** [comment]
I see the issue.
The workaround actually works great for me:

```ts
type Func<T extends string | number> = (arg: T) => undefined

const metaFunc = <T extends string | number>(func: Func<T>, param: T) => {
  func(param);
}
```

Of course in real life `Func` is more complicated, but as long as I can neatly wrap it in it's own type it doesn't bother me

Thanks!
