### ISSUE TITLE
TypeScript language server does not highlight the `@satisfies` keyword in JSDoc.

### ISSUE THREAD

**Issue by KSXGitHub** [microsoft/TypeScript#57307]
![Screenshot of the code](https://github.com/microsoft/vscode/assets/11488886/4511bfe2-9985-4827-b40b-fe5950e8cbe9)

TypeScript Version: 5.3.3 (selected from workspace)

**Comment by jaydenseric** [comment]
With TypeScript v5.4.2 in VS Code, with this JSDoc:

```js
/** @satisfies {Record.<SupportedShell, String>} */
```

The JSDoc tag `@satisfies` is syntax highlighted:

<img width="455" alt="Screenshot 2024-03-12 at 9 39 30 pm" src="https://github.com/microsoft/TypeScript/assets/1754873/3133249b-7af2-432a-ac5b-63d5b04ad0d0">

So this issue can be closed?
