### ISSUE TITLE
Typescript autocomplete: extending an abstract class's async method get autocompleted incorrectly

### ISSUE THREAD

**Issue by JorensM** [microsoft/TypeScript#57301]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.85.2
- OS Version: Windows 10

https://github.com/microsoft/vscode/assets/17122123/9cf9a4d3-130f-4fef-8aaa-a3e336583ca8

Steps to Reproduce:

1.  Create an abstract class with an abstract async method ( returns a Promise)
2.  Create another class that extends this abstract class, and try to write the method using autocomplete, by starting with typing `async`
3.  See that it gets autocompleted incorrectly

**Comment by mjbvz** [comment]
Copiable code: 

```ts
abstract class AFoo {
    abstract bar(): Promise<void>;
}

class Foo extends AFoo {
    async b
}
```

**Comment by mjbvz** [comment]
Here is the completion entry:

```
        {
            "name": "bar",
            "kind": "method",
            "kindModifiers": "abstract",
            "sortText": "11",
            "insertText": "async bar(): Promise<void> {\n    $0\n}",
            "filterText": "bar",
            "isSnippet": true
        },
```

No replacement range is returned
