### ISSUE TITLE
Intellisense can't find types in a pnpm workspace when types are built again

### ISSUE THREAD

**Issue by Seboran** [microsoft/TypeScript#57329]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.86.0 (Universal)
- OS Version: OS: Darwin x64 23.2.0

Steps to Reproduce:

1. Clone https://github.com/Seboran/repro-pnpm-intellisense
2. Install with `pnpm i` from  root
3. Open file https://github.com/Seboran/repro-pnpm-intellisense/blob/f2d02c1f80dfc8f307112a4f03a65e439a684f1e/packages/solid-playground/index.ts
4. Run `pnpm build`, which builds types of the other package.
5. Get the message "Could not find a declaration file for module"
![image](https://github.com/microsoft/vscode/assets/21184670/0fdac6d7-b02c-4dfe-9a93-feb60d5322c6)

When you restart the typescript server, the issue goes away.

**Comment by sheetalkamat** [comment]
I am trying to see if #58139 can help you but when i run this with typescript nightly or my version of PR the error about resolving module doesnt go away event if i start tsserver fresh after the build. Am i missing any steps

**Comment by Seboran** [comment]
Hi, I just fixed the repo, the package.json file was missing, sorry about that.

You should get an error like this: 
![image](https://github.com/microsoft/TypeScript/assets/21184670/b2b2e273-5d14-40af-b790-21c39e9c5040)

**Comment by sheetalkamat** [comment]
This seems to be fixed by https://github.com/microsoft/TypeScript/pull/58139 as with nightly i see that error gets resolved.
