### ISSUE TITLE
Allow support for refactoring all instances

### ISSUE THREAD

**Issue by Dpschu2** [microsoft/TypeScript#57325]
If there is not already, there should be support for refactoring(creating local variable of) all instances of a selection. The images show a before and after of what I am looking to do. I tried creating a shortcut with multiple commands where the first selects all instances then the second refactors the lines, but this is not yet possible.

Thank you.

**Comment by RyanCavanaugh** [comment]
Please follow a relevant issue template for this repo. Thanks.
