### ISSUE TITLE
'resolves to a type-only declaration and must be imported using a type-only import' doesn't have a quick fix

### ISSUE THREAD

**Issue by acutmore** [microsoft/TypeScript#57326]
### 🔎 Search Terms

verbatimModuleSyntax type quick fix

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about fixes

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?moduleResolution=100&target=99&verbatimModuleSyntax=true#code/PTAEAEDcFMCcCMCGAXAlgWwLIHsAmBXAG2gGUBPAO2UQA8AuUZWfaAKBAnTyOgegGcK0GsnZhwXAsQBKA7IXxpsFBvHwVcxWGIjVYAc2jI+g4aJ3gAZqmIVE6XqEKp4AOmT9WwgA7ZYyUEt1AGMlCkCACgBKUABvAF9WC2tbe0ckWFhoQndPHz8A5DJvaFAAKlBEflB4QNhsdFAAIldgZzcAK34mgG4kjisbaDsHBlQNYVzWDF9-OJrQeLqG5taMrJyu3tYgA

### 💻 Code

```ts repro
// @verbatimModuleSyntax: true
// @module: esnext
// @moduleResolution: bundler
// @target: esnext

// @filename: lib.ts
export function f() {}

// @filename: barrel.ts
export type * as b from "./lib.js";

// @filename: index.ts
import { b } from "./barrel.js";
         ^  //  ts1485: 'b' resolves to a type-only declaration and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?moduleResolution=100&target=99&verbatimModuleSyntax=true#code/PTAEAEDcFMCcCMCGAXAlgWwLIHsAmBXAG2gGUBPAO2UQA8AuUZWfaAKBAnTyOgegGcK0GsnZhwXAsQBKA7IXxpsFBvHwVcxWGIjVYAc2jI+g4aJ3gAZqmIVE6XqEKp4AOmT9WwgA7ZYyUEt1AGMlCkCACgBKUABvAF9WC2tbe0ckWFhoQndPHz8A5DJvaFAAKlBEflB4QNhsdFAAIldgZzcAK34mgG4kjisbaDsHBlQNYVzWDF9-OJrQeLqG5taMrJyu3tYgA)

### 🙁 Actual behavior

No quick fix is available for this error.

### 🙂 Expected behavior

Able to apply a quick fix converting the code into `import type { b } from "./barrel.js";`

### Additional information about the issue

Wondering if this could be addressed by including this error as part of this existing quick fix: https://github.com/microsoft/TypeScript/blob/c790dc1dc7ff67e619a5a60fc109b7548f171322/src/services/codefixes/convertToTypeOnlyImport.ts#L28-L32

**Comment by RyanCavanaugh** [comment]
80 minutes from reported to fixed, possibly a new record?

**Comment by acutmore** [comment]
Thanks @a-tarasyuk!

Raised issue, went to bed, woke up, issue was fixed 😮😍
