### ISSUE TITLE
IntelliSense with typescript in monorepo

### ISSUE THREAD

**Issue by mshkpchv** [microsoft/TypeScript#57338]
I am have this project setup with Typescript

📁 project-root
|
├── 📁 contract-dependencies
|   └── 📁 node_modules
|       └── 📁 misho
|              └──── 📁 dep1
|              └──── 📁 dep2
|
├── 📁 contracts
|   └── 📄 tsconfig.json
|
├── 📁 events
|   └── 📄 tsconfig.json
|
└── 📄 tsconfig.json

In the main root tsconfig.json 

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
     "@contract-dependencies/*": [
        "contract-dependencies/node_modules/@misho/*"
      ],
      "@contracts/*": [
        "contracts/src/"
      ],
      "@events/*": [
        "events/src/*"
      ]
    }
  },
  "include": [
    "src/**/*.ts"
  ],
  "references": [
    {
      "path": "./contracts/tsconfig.json"
    },
 {
      "path": "./events/tsconfig.json"
    }
  ]
}

```

IntelliSense does not function as expected for "node_modules" within the folder "contract-dependencies." While it accurately displays all exported types when something is imported in the current file, it currently fails to do so otherwise(if nothing is imported).

**Comment by RyanCavanaugh** [comment]
What do you mean "does not function" ? Can you provide a list of concrete steps we can do to see unexpected behavior (and what the expected behavior is)?
