### ISSUE TITLE
TypeScript project: Quick Fix does not suggest import as an option

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/TypeScript#57336]
Type: <b>Bug</b>

Direct link to repository/branch with issue: https://github.com/DanKaplanSES/jsdom-configurable-resource-loader/tree/vs-code-quick-fix-does-not-suggest-import

## Steps to reproduce

1. `git clone git@github.com:DanKaplanSES/jsdom-configurable-resource-loader.git`
2. `git switch vs-code-quick-fix-does-not-suggest-import`
3. Open the root folder in VS Code.
4. `npm install`
5. Open `src/index.spec.ts`
6. Notice the error on `new ConfigurableResourceLoader()`:

    ```ts
    import { ResourceLoader } from 'jsdom';

    describe('Configurable Resource Loader', () => {
        it('extends jsdom.ResourceLoader', () => {
            const subject = new ConfigurableResourceLoader(); // <-- error

            expect(subject).toBeInstanceOf(ResourceLoader);
        });
    });
    ```
7. Hover over this error.
8. Notice the pop-out:

   ![image](https://github.com/microsoft/vscode/assets/373675/d35b6178-77d8-43b7-89a7-acb564c2dcf2)

### Expected:

There is a "Quick fix" option to add `ConfigurableResourceLoader` as an import.

### Actual:

There are no "Quick fix" options.

## Notes:

If you manually type `import { ConfigurableResourceLoader } from './index';` at the top of this file, the error goes away.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.75GB free)|
|Process Argv|--disable-extensions --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by RyanCavanaugh** [comment]
Auto-import can only offer files that are part of your project, and the file you're asking to import from isn't in your compilation yet:
```ts
D:\Throwaway\jsdom-configurable-resource-loader>tsc --listFiles -p tsconfig.test.json
( ... lib files ...)
D:/Throwaway/jsdom-configurable-resource-loader/src/index.spec.ts
D:/Throwaway/jsdom-configurable-resource-loader/tsup.config.ts
```
