### ISSUE TITLE
Conditional type unexpectedly non-distributive with `never`

### ISSUE THREAD

**Issue by rotu** [microsoft/TypeScript#57343]
### 🔎 Search Terms

never, intersection, contradiction

### 🕗 Version & Regression Information

- This changed in commit or PR #36696

### ⏯ Playground Link

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?ts=5.4.0-dev.20240208#code/C4TwDgpgBAkgzgOQK4FsBGEBOAeAKgPigF4pcoIAPYCAOwBM4obUNMoB+KYTJaALigAzAIYAbOBABQk0JCgBhAPY1BogJYBjanWJQA3hT7deAXygAyfYZHiIZgPT2mEAG5ZJjqF4B67abOgAUQoARl14ZHQsbCUVdS0IOkJPYwgAOigAZQALRSRRHQxnNzYPJx8-AKhggCZwxBZomlcsfDKvKF9pT1jVTW0oOGBhTGBGDGzhFzUaAHModQBraAADZpKVqGFZ4RmoAHds2ig6NSHMNTQkYDVp0CgzoUVMDUSoNBAoMGubuYfgB40LZQJA0NTKGTgIIUADM9UirGwACIAPKBdFIqAAHwUyj6CSSUE8NgkUAAFGhFIpRBBhEC9rgoZkNBcwACACxpABsaXZAEp2hVIXJguz4Y0cGEcb14tpkk5UoLOn4gA)

### 💻 Code

```ts repro
type IsNumber<T> = T extends number ? true : false

type Conflicted = {x:true} & {x:false} // never
//   ^?

type Ex1 = IsNumber<Conflicted> // true. Should be never 
//   ^?
type Ex2 = IsNumber<never>
//   ^?

// Conflicted starts behaving like `never` again when distributivity is forced by putting it in a union
type Ex3 = IsNumber<"OEEE" | Conflicted> // false (boolean in TypeScript 4.6.4)
//   ^?
type Ex4 = IsNumber<1 | Conflicted> // true
//   ^?

```

### 🙁 Actual behavior

`Ex1` is `true`.

### 🙂 Expected behavior

`IsNumber<Conflicted>` should be `never`. This is a distributive conditional.

### Additional information about the issue

This also manifests as `ReturnType<T>` being `unknown` when `T` is a conflicted intersection.

Originally submitted in #57210 which was overly broad.

**Comment by fatcerberus** [comment]
Possibly related to/same root cause as https://github.com/microsoft/TypeScript/issues/57210?
