### ISSUE TITLE
Implicitly casting non-numbers with a PrefixUnaryExpression should fail typechecks

### ISSUE THREAD

**Issue by cpojer** [microsoft/TypeScript#57347]
### 🔎 Search Terms

prefixunaryexpression

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAEAa0G8BQ1rAPYDsIBcBOArsDungBQAOBARiAJbDR4CmYAJliAJ5oF4uYcAYXS4AXNEwEAttWZ4AlIgC+SFNCq0G0AhTZgczMhnGSZcxYnWoWOPpknMA7nDI4AFnQgA6YHwHCojjQANRoQQoA3OqqqkgY2MEmwQC8iMkSAKzK0fFYuNAAHtBpmM6umVFqhd66+oZkALTJVWptbTV1BkbJ0ABU0I0AjFFAA

### 💻 Code

```ts
class X {
  constructor(public readonly currentCost: number) {}

  public update(cost: number) {
    return new X(this.currentCost + cost);
  }
}

const cost = {cost: 5};

const x = new X(5);

x.update(-cost); // Should error

x.update(cost * -1); // Errors correctly
```

### 🙁 Actual behavior

I refactored some code from returning a number to returning an object. I expect TypeScript to point me to all the places where I needed to make adjustments and came across one where I had `-cost` where `cost` was changed from a number to an object. TypeScript was not giving me an error like it does when I use `cost * -1`.

### 🙂 Expected behavior

I would expect TypeScript to prevent implicit casts on non number types (or non-scalar types in case there are valid use cases of this for boolean/strings) if a PrefixUnaryExpression is used. There are some fun JavaScript things that can be done by using `-[]` or `-{}`, it is almost never what a developer intents.

**Comment by RyanCavanaugh** [comment]
Duplicate #20131
