### ISSUE TITLE
Auto-complete on `satisfies` auto-imports `satisfies`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#57348]
### 🔎 Search Terms

satisfies auto import vscode

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I (didn't) reviewed the FAQ for entries about it because @DanielRosenwasser told me to open an issue

### 💻 Code

Create a file that has `export function satisfies() {}`. Then, in a different file type `const a = 1 sat` and hit enter (to select the "satisfies" auto-complete in vscode).

### 🙁 Actual behavior

The TS language server will add an `import { satisfies } from "..."`.

### 🙂 Expected behavior

It should not do it.

### Additional information about the issue

This is only a problem if you have a module that exports `satisfies` somewhere, but this is very common: https://www.npmjs.com/package/@types/semver does and has 21M weekly downloads.

It also happens for `as`, but  I have never seen a module exporting an `as` function so I never encountered this in practice.

**Comment by DanielRosenwasser** [comment]
Thanks for filing this one. 😊
