### ISSUE TITLE
Add feature to indicate when calling an async method that has await key omitted

### ISSUE THREAD

**Issue by velara3** [microsoft/TypeScript#57359]
### 🔍 Search Terms

await async promise

### ✅ Viability Checklist

- [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [ ] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

In a typescript project, after creating an async method the next step would be to use it. Adding an warning if await is not used is helpful for debugging. 

But async methods have different behavior if you use the await keyword before hand. 

Calling this function: 

```
async doSomething() {
    // make an async call or action usually
     return await fetch(url)
}

// this first call results are different than the second call results
var aPromise = doSomething();
var aResponseObject = await doSomething();

// this first call is different than second 
var aPromise = doSomething();
console.log("This line is called immediately even though doSomething is not finished it's task")
var aResponseObject = await doSomething();
console.log("This line is not called until after doSomething has a result from the server") 
```

In the first call the program flow continues to the next line. 
In the second call the program execution flow pauses. 

Both cases are valid but having a warning (not an error) for the cases when the `await`keyword is missing would be very desirable. 

I don't know how many times my code has behaved unexpectedly and the unexpected behavior is due to a missing `await` keyword for an `async` function. Having a simple indication in typescript gives me an notice that maybe I need to add an await. 

### 📃 Motivating Example

"A new feature in Typescript will alert you when your code omits the await keyword when calling async methods, saving developers hours of time for hard to track bugs!"

### 💻 Use Cases

1. What do you want to use this for? 
- for assistance during development 

3. What shortcomings exist with current approaches?
if you don't use await on an async method there's no indication that the call is no longer waiting or pausing the execution flow. there's no way to tell when debugging if the function is inside of an async program execution

4. What workarounds are you using in the meantime?
pulling out my hair saves money on haircuts

**Comment by MartinJohns** [comment]
> but having a warning (not an error)

TypeScript does not have the concept of warnings. There are only errors.

**Comment by RyanCavanaugh** [comment]
Duplicate #13376

**Comment by fatcerberus** [comment]
> "A new feature in Typescript will alert you when your code omits the await keyword when calling async methods, saving developers hours of time for hard to track bugs!"

That's not a motivating example... *motivational*, yes, but not a motivating example.

> pulling out my hair saves money on haircuts

Significantly more painful, though.

**Comment by velara3** [comment]
New feature request. Typescript adding warnings or code comments.

“Hey buddy, I see you didn’t add an await keyword to that function.
Sometimes code acts differently if you don’t have that. Just saying bro…”
