### ISSUE TITLE
Pass down type of record key when mapped over it

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [microsoft/TypeScript#57354]
### 🔎 Search Terms

Records, Maps

### 🕗 Version & Regression Information

- This is the behavior in every version I tried also the nightly version

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?#code/AQ0guCeAOCmwAUBOsDGBLa7wENzoHsA7ZAgIxzPQBtt1YBnAFXQFtYBlag8B4AXgBQYMAB9gAIgCMwWDiTVIwVgSRF0RAOYThIkOIkAmZavVade-ZIDMwIgWIXLBgCzAcAM3Cw1Dok70DAFY7dE0AC3AJAG5BXTBUYgZwYGgUDCxcfGJSCipafEYALmAAJTRVABMAHniRZDRMbDxCEiRySho6RhZ2Lh4GABo6sCIAV1YyH2BxMaJK2A8NWEqR4AA+AWAAbzWQaVl5RRM1DW0SuYWlohXhy0ljFVPzC-nF5cq7ywlbe0dXq4fL56CRuTzeXz-YCXd43T57SQhdQRKIA2G3NYAXziAHkyAArNDgAB0sCI4CQ9AYAAo0o1Mi0cu08l1CgwAJTE1g4aDU6kAbQA1rBIINgAA3HDUMawAC67IEm12CSSBGosGJ3E01OFoolUplCoA9EbgExwvBdcBwjg+FA4MBkpStMAyGMUgxwgQxtRKtacOL4Pb4A0Ms1sm0Ovlusw2JxuLxBJj2UA)

### 💻 Code

[Playground Link](https://www.typescriptlang.org/play?#code/AQ0guCeAOCmwAUBOsDGBLa7wENzoHsA7ZAgIxzPQBtt1YBnAFXQFtYBlag8B4AXgBQYMAB9gAIgCMwWDiTVIwVgSRF0RAOYThIkOIkAmZavVade-ZIDMwIgWIXLBgCzAcAM3Cw1Dok70DAFY7dE0AC3AJAG5BXTBUYgZwYGgUDCxcfGJSCipafEYALmAAJTRVABMAHniRZDRMbDxCEiRySho6RhZ2Lh4GABo6sCIAV1YyH2BxMaJK2A8NWEqR4AA+AWAAbzWQaVl5RRM1DW0SuYWlohXhy0ljFVPzC-nF5cq7ywlbe0dXq4fL56CRuTzeXz-YCXd43T57SQhdQRKIA2G3NYAXziAHkyAArNDgAB0sCI4CQ9AYAAo0o1Mi0cu08l1CgwAJTE1g4aDU6kAbQA1rBIINgAA3HDUMawAC67IEm12CSSBGosGJ3E01OFoolUplCoA9EbgExwvBdcBwjg+FA4MBkpStMAyGMUgxwgQxtRKtacOL4Pb4A0Ms1sm0Ovlusw2JxuLxBJj2UA)

### 🙁 Actual behavior

[Playground Link](https://www.typescriptlang.org/play?#code/AQ0guCeAOCmwAUBOsDGBLa7wENzoHsA7ZAgIxzPQBtt1YBnAFXQFtYBlag8B4AXgBQYMAB9gAIgCMwWDiTVIwVgSRF0RAOYThIkOIkAmZavVade-ZIDMwIgWIXLBgCzAcAM3Cw1Dok70DAFY7dE0AC3AJAG5BXTBUYgZwYGgUDCxcfGJSCipafEYALmAAJTRVABMAHniRZDRMbDxCEiRySho6RhZ2Lh4GABo6sCIAV1YyH2BxMaJK2A8NWEqR4AA+AWAAbzWQaVl5RRM1DW0SuYWlohXhy0ljFVPzC-nF5cq7ywlbe0dXq4fL56CRuTzeXz-YCXd43T57SQhdQRKIA2G3NYAXziAHkyAArNDgAB0sCI4CQ9AYAAo0o1Mi0cu08l1CgwAJTE1g4aDU6kAbQA1rBIINgAA3HDUMawAC67IEm12CSSBGosGJ3E01OFoolUplCoA9EbgExwvBdcBwjg+FA4MBkpStMAyGMUgxwgQxtRKtacOL4Pb4A0Ms1sm0Ovlusw2JxuLxBJj2UA)

### 🙂 Expected behavior

[Playground Link](https://www.typescriptlang.org/play?#code/AQ0guCeAOCmwAUBOsDGBLa7wENzoHsA7ZAgIxzPQBtt1YBnAFXQFtYBlag8B4AXgBQYMAB9gAIgCMwWDiTVIwVgSRF0RAOYThIkOIkAmZavVade-ZIDMwIgWIXLBgCzAcAM3Cw1Dok70DAFY7dE0AC3AJAG5BXTBUYgZwYGgUDCxcfGJSCipafEYALmAAJTRVABMAHniRZDRMbDxCEiRySho6RhZ2Lh4GABo6sCIAV1YyH2BxMaJK2A8NWEqR4AA+AWAAbzWQaVl5RRM1DW0SuYWlohXhy0ljFVPzC-nF5cq7ywlbe0dXq4fL56CRuTzeXz-YCXd43T57SQhdQRKIA2G3NYAXziAHkyAArNDgAB0sCI4CQ9AYAAo0o1Mi0cu08l1CgwAJTE1g4aDU6kAbQA1rBIINgAA3HDUMawAC67IEm12CSSBGosGJ3E01OFoolUplCoA9EbgExwvBdcBwjg+FA4MBkpStMAyGMUgxwgQxtRKtacOL4Pb4A0Ms1sm0Ovlusw2JxuLxBJj2UA)

**Comment by MartinJohns** [comment]
You might want to fill out the issue template properly, instead of just repeatedly posting the playground link.

This is working as intended. `Object.entries()` returning `string` for the key is intentional. See #38520 for more information.
