### ISSUE TITLE
incorrect implementation message is the most mysterious, please demystify 

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5735]
![image](https://cloud.githubusercontent.com/assets/937933/11311482/1cbea8bc-8f9e-11e5-982e-574662d61f2e.png)

**Comment by RyanCavanaugh** [comment]
Normally when we issue an error like this, there's supposed to be "more" - an additional error message shown underneath this one:

![image](https://cloud.githubusercontent.com/assets/6685088/11312329/4fa94020-8f8a-11e5-9892-f24e9df66f35.png)

There can be compiler bugs that result in error messages that should have elaboration not getting them. Can you isolate the repro for getting this error without any elaboration? Fair warning: this is usually rather difficult.

**Comment by mhegazy** [comment]
this looks fixed in latest. please reopen if not the case.
