### ISSUE TITLE
Code Improvements and Validations Repetitive 

### ISSUE THREAD

**Issue by kevinuehara** [microsoft/TypeScript#57376]
### 🔍 Search Terms

I notice some "problems" that we can improve on code:

## First: `nodeServer.ts`

<img width="735" alt="image" src="https://github.com/microsoft/TypeScript/assets/20498649/af13fa8d-c538-4bf6-b8db-13aa6da0729c">

## Second: `server.ts`

<img width="713" alt="image" src="https://github.com/microsoft/TypeScript/assets/20498649/a4f733de-3de9-4b00-afae-2897f73e8ef2">

<img width="869" alt="image" src="https://github.com/microsoft/TypeScript/assets/20498649/cbe7b2d6-7d7c-4483-a50b-2adfced63aea">

## Third: `nodeServer.ts`

When the tests was running this error of lint appears:
<img width="1235" alt="image" src="https://github.com/microsoft/TypeScript/assets/20498649/adb9a72c-897a-459b-bb5a-d5502be65e78">

To adjust I will simple change the `null!` to `undefined`

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

## First: `nodeServer.ts`

I change this function here, which was using switch and update to use the get object pattern

<img width="672" alt="image" src="https://github.com/microsoft/TypeScript/assets/20498649/f9374809-9b43-4322-b3f7-955f9e8ee59d">

## Second: `server.ts`

<img width="669" alt="image" src="https://github.com/microsoft/TypeScript/assets/20498649/25886b5b-1f27-42fc-b10e-d0074f075472">
<img width="679" alt="image" src="https://github.com/microsoft/TypeScript/assets/20498649/a1711207-c76d-4d2e-baad-fd153bf65260">

## Third: `nodeServer.ts`

I adjust this line, because when the tests was running this error of lint appears:
<img width="1235" alt="image" src="https://github.com/microsoft/TypeScript/assets/20498649/adb9a72c-897a-459b-bb5a-d5502be65e78">

To adjust I', simple change the `null!` to `undefined`

### 📃 Motivating Example

I want to start to contribute with open source projects and as I use Typescript every day I want to deep dive study the code and improve it.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by RyanCavanaugh** [comment]
Appreciate the thought but we don't need stylistic changes at this point. Please refer to the Backlog Milestone for ideas of identified defects to work on. Thanks!
