### ISSUE TITLE
Invalid use of 'eval' when defining a namespaced eval function

### ISSUE THREAD

**Issue by bendmorris** [microsoft/TypeScript#57386]
### 🔎 Search Terms

eval, strict mode, namespace

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEBzCB7ARlC8DeAoeB8IAHgA4owAu8AdlALYgDOpUYCNIlAZhAJbEc+QiJLkq8bgFcaYSnxQ0iAN0wAKAJQAueMpR9gAbmEEAvrnO4xFatnNA

### 💻 Code

```ts
declare global {
    export namespace myNamespace {
        export function eval(): void;
    }
}

export {}
```

### 🙁 Actual behavior

Invalid use of 'eval'. Modules are automatically in strict mode.

### 🙂 Expected behavior

No error

### Additional information about the issue

I see in https://github.com/microsoft/TypeScript/issues/3036 that this behavior is by design as defining an 'eval' function is forbidden in strict mode. However, the namespace declaration above describes runtime code more like the following, which is perfectly valid in strict mode:

```ts
const myNamespace = {
    eval() {
        // ...
    }
}
```

Would it be possible to not fail on namespaced function declarations?

**Comment by Josh-Cena** [comment]
The equivalent TS code cannot be transpiled because the output looks like:

```js
export var myNamespace;
(function (myNamespace) {
    function eval() {
    }
    myNamespace.eval = eval;
})(myNamespace || (myNamespace = {}));
```

So it's only useable in a declaration context.
