### ISSUE TITLE
Imported symbol as a type is not merged with a local variable

### ISSUE THREAD

**Issue by Conaclos** [microsoft/TypeScript#57414]
### 🔎 Search Terms

Declaration merging, isolatedModule, type import conflict

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about declaration merging

### ⏯ Playground Link

https://www.typescriptlang.org/play?isolatedModules=true&ts=5.4.0-beta#code/JYWwDg9gTgLgBDAnmApnA3nAwhcEB2K+8AvnAGZS5wDkUKAhgMYw0DccA9J3ACoDKcFFCpQAznAIIAFsAkB3WQBs0weHLihIsFABM4DCQwTIUAKCYEx8HHkLEAXNlyR78AD5x8AVyVK4ALxevkpsZmZa0PBIqBhwAGJYcGSU1HSMLOxcPAIGfhDyEjCyRhJqNEYmqBZW8IlOiXCePn6BwX5hQA

### 💻 Code

```ts
import type { Component } from 'react'; // TS errors on this while it is imported as a type
const Component: Component | null = null;

import type { FC } from 'react'; // TS allows this as it's a type
const FC: FC | null = null;
```

### 🙁 Actual behavior

TypeScript reports the following error:

```
Import declaration conflicts with local declaration of Component.
```

### 🙂 Expected behavior

Because `Component` is imported as a type, it should be merged with the variable `Component` without emitting an error.

### Additional information about the issue

A [related issue](https://github.com/microsoft/TypeScript/issues/55584) was [recently fixed](https://github.com/microsoft/TypeScript/pull/56354) and discussed in a [design meeting](https://github.com/microsoft/TypeScript/issues/56437).

Fixing the current issue could make TypeScript behavior more consistent.

**Comment by whzx5byb** [comment]
This is intended, since `import type {}` will also create type information which can be used in `typeof` if possible. You can write:
```ts
// @filename: a.ts
export const Foo = 'Foo';

// @filename: b.ts
import type { Foo } from './a';
type Bar = typeof Foo
  // ^ type Bar = "Foo"
```
You are not allowed to define a variable `Foo` here, because it will change the result of `typeof Foo`.

**Comment by Conaclos** [comment]
@whzx5byb I am not sure that you have understood my point, or I am not sure that I am following you.

Here `FC` is a type that is **imported as a type** and is **merged with the local variable `FC`**.
`Components` is a class that is **imported as a type** and **should merge with the local variable `Components`**.

Basically, every type or value imported as a type should be mergeable with a local variable (**that is not a type**).

**Comment by Conaclos** [comment]
Thanks! That's so ugly ;(

**Comment by fatcerberus** [comment]
> import type {} will also create type information which can be used in `typeof` if possible.

More specifically, it imports *all meanings of the imported symbol*, even value meanings, it just doesn't allow using them in emitting positions.
