### ISSUE TITLE
Function return type inference fails when the possible return types have different structures for a field with the same name, and one is returned as a promise

### ISSUE THREAD

**Issue by G1itcher** [microsoft/TypeScript#57413]
### 🔎 Search Terms

function inference, promise, return type, union

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about function return type inference

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-beta#code/IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8AoGcmAJwFNkFKtSKKAjYSgLmLOYqgAscXAET9qAG3HphPZgF9ysmHJIqSoSLEQoMWNpQLdmNOgyO9y+rkwu8BQmKIlThAGiW2YLB8IDu6SnEAExlPFXlVEnVwaHgkKDRMLwQAc0MbchN6LABZYGR+ADpKYAgg9ABbQwAeGAAGQoBWGAB+JTgcQw4lfQIAblUgA

### 💻 Code

```ts
async function foo() {
    return {
      bar: {
        choo: "hello"
      }  
    }
}

function bar() {
    return {
        bar: {
            choo: "hello",
            boo: "world"
        }
    }
}

async function bug() {
    return Math.random() < 0.5 ?
    await foo() :
    bar();
}
```

### 🙁 Actual behavior

bug's return type is
```ts
Promise<{
    bar: {
        choo: string;
    };
}>
```

### 🙂 Expected behavior

bug's return type should be
```ts
Promise<{
    bar: {
        choo: string;
    };
} | {
    bar: {
        choo: string;
        boo: string;
    };
}>
```

### Additional information about the issue

I tested across a number of versions on the playground, including the oldest and nightly

It looks like playing with the awaits can resolve this issue, but that doesn't seem to be ideal.

**Comment by MartinJohns** [comment]
It's working as intended and called "subtype reduction". There are plenty of issues about it.

**Comment by G1itcher** [comment]
Seems not easy to find if you don't know the name for it. Doesn't seem like a great solution honestly, but if this is known I'll close this ticket.
