### ISSUE TITLE
another strangeness

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5741]
```typescript
// tag types: https://github.com/Microsoft/TypeScript/issues/4895
const enum Tag {} // <-- tag (hopefully nominal) type to indicate some assertion taken place over a string value

function foo(
	values: (string & Tag)[],
	callback: (one: string & Tag) => number // <-- only strings that have satisfied the assertion are welcome here
) {
	return undefined;
}

function bar(one: string): number { // <-- function that doesn't require its parameter to be marked
	return undefined
}

foo([], bar); // <-- no problem... why is bar an ok argument? didn't we ask for a function that requires a string & enum?
// are enums not nominal? why is it ok to ignore it here?
```

**Comment by weswigham** [comment]
> Function Argument Bivariance
>
> When comparing the types of function parameters, assignment succeeds if either the source parameter is assignable to the target parameter, or vice versa. This is unsound because a caller might end up being given a function that takes a more specialized type, but invokes the function with a less specialized type. In practice, this sort of error is rare, and allowing this enables many common JavaScript patterns.

`string & Marker` is assignable to `string`, so `(one: string) => number` is assignable to `(one: string & Marker) => number`

**Comment by aleksey-bykov** [comment]
oh god...

**Comment by RyanCavanaugh** [comment]
:rose:

**Comment by aleksey-bykov** [comment]
RIP tag types: #4895
