### ISSUE TITLE
type guard does not analyze correctly when in an unreachable code block and allowUnreachableCode is true

### ISSUE THREAD

**Issue by thomasrea0113** [microsoft/TypeScript#57423]
### 🔎 Search Terms

type guard  unreachable code allowUnreachableCode

### 🕗 Version & Regression Information

Version 5.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?allowUnreachableCode=true&ts=5.4.0-dev.20240215#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcIYqohCgAgqAAvKAA3oqgDWL5oIKolJzMigC+wSVEoABCVaAVAGS19Y3Sza3tzADc3cEInK0igkPVABQMzWUAlM3iopsAfGilKaA7YsJmePsB0lWV1QBEsxnMb8vwqzQSeSYACqnCcDFM0ncwx2e32VVOijqjREqS2bXYkHhTlQ7DInEWkwaK0E8HcAWg8GYWze2GglMk8DI0Te+2CKIoaKEAx2+zZKJRJLJkApVJ2TzZPUUJIBQI4qFB4Mh0O2uxG8MqiORjSF5Mp1NpMAZEiZLLZRNR125vP5AuJf1JerFDAlSwaQA

### 💻 Code

```ts
// Welcome to the TypeScript Playground, this is a website
// which gives you a chance to write, share and learn TypeScript.

// You could think of it in three ways:
//
type A = {
    a: string
}

type B = A & {
    b: string;
}

const isB = (a: A): a is B => typeof (a as any).b === "string"

const withUnreachable = (a: A) =>
{
    if (true) return;

    console.log("hello world")

    if (isB(a))
        console.log(a.b)
}

const withoutUnreachable = (a: A) =>
{
    console.log("hello world")

    if (isB(a))
        console.log(a.b)
}
   
```

### 🙁 Actual behavior

type error is thrown because the type guard is not executed

### 🙂 Expected behavior

type guards should be processed even if the code is unreachable, or all type checking should be disable for unreachable code

### Additional information about the issue

I tested with all versions available on the playground, none work. Full type checking is not executed on unreachable code even when `allowUnreachableCode` is `true`. It seems that the type guards do not infer the guarded type if it is in an unreachable block, so I get a compile error. This isn't a huge deal but during testing sometimes it's easier to force an early return.

**Comment by fatcerberus** [comment]
Duplicate https://github.com/microsoft/TypeScript/issues/26914
