### ISSUE TITLE
Unexpected broadening of generic type parameter when used in the types of 2 different function params

### ISSUE THREAD

**Issue by estradanic** [microsoft/TypeScript#57427]
### 🔎 Search Terms

type broadening, type narrowing, generics, generic type parameter, index type, template literal, typescript, unexpected, why doesn't typescript know that these are the same, same generic instance not enforced between function params

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about the same generic instance type being used in different function parameters

### ⏯ Playground Link

https://www.typescriptlang.org/play#code/C4TwDgpgBAyg9gWwsAFgSwHYHMoF4oDk8SqmWBA3AFCiSyLLrYCiANgM7T5EOkscRKVGuGgAVCAjCsAhsAhjReKAANijMgDoAJAG91fLAF8VUAD6qDTLG0479va7YgnhAMwCuGAMbA0cDCgAEzgrMgB1NFQAWRAxawAeMSgIAA95DCD2ehJrcxyNfk4APgAKNzQIViCALigxABooODA-ALqxAEooXSoofqhvAPZgKAQ4yWk5CA7J2XlFOnwVPQqqoKN7FraME2ojKiA

### 💻 Code

```ts
type Something = 'Something';
type SomethingElse = 'SomethingElse';

type TemplateType = `Something.${Something}` | `SomethingElse.${SomethingElse}`

function doSomethingWithMyThing<T extends Something | SomethingElse>(field: T, option: T) {
    const myTemplate: TemplateType = `${field}.${option}`;
}
```

### 🙁 Actual behavior

The actual type of `${field}.${option}` is some sort of cartesian product of the types of field and option, causing the `TemplateType` type of `myTemplate` to be incorrect.

### 🙂 Expected behavior

The type of `${field}.${option}` should be either "Something.Something" or "SomethingElse.SomethingElse" based on the same `T` being enforced between the two params.

**Comment by fatcerberus** [comment]
https://github.com/microsoft/TypeScript/issues/57372#issuecomment-1939463884
`T` can legally be instantiated to `Something | SomethingElse` in which case the parameters don't have to correlate.  You're looking for https://github.com/microsoft/TypeScript/issues/27808.

**Comment by estradanic** [comment]
Interesting. That is frustrating, but it makes sense. Thanks for the link!
