### ISSUE TITLE
I am having issues and constantly have issues with tsconfig settings - visual editor needed

### ISSUE THREAD

**Issue by velara3** [microsoft/TypeScript#57420]
### 🔍 Search Terms

tsconfig settings preferences

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I'm having constant problems with tsconfig settings. Is it impossible to make a UI for it? Is it too hard? I would believe you because the tsconfig itself is too hard. 

I need Typescript authors to show me a set of options, then allow me to pick them, tell me if there are any conflicts and reasons not to choose these options and show me expected output and any compatibilities. 

### 📃 Motivating Example

Spending hours and days fighting with the tsconfig.json file to get the settings I need. 

### 💻 Use Cases

1. What do you want to use this for?
Because I want to spend time coding not fighting with settings

2. What shortcomings exist with current approaches?
No autocomplete, no warning messages or suggestions, no normal human interaction for interfacing with the program. 

3. What workarounds are you using in the meantime?
crying, throwing things, ranting and raving at water fountains

**Comment by xiBread** [comment]
https://github.com/tsconfig/bases
https://www.typescriptlang.org/tsconfig

**Comment by RyanCavanaugh** [comment]
I'm not sure what you're asking for that doesn't already exist.

 * `tsc --init` gives you a file full of documented recommendations
 * There's a published JSON schema that works in any editor that understands JSON schema
 * The TS Playground has a UI for choosing options and seeing what they do
 * There is [extensive documentation](https://www.typescriptlang.org/tsconfig)
 * There are tsconfig bases
 * Many TS content creators have written about config files as well

**Comment by velara3** [comment]
It doesn't work. Autocomplete doesn't work half the time, it doesn't give value descriptions, it doesn't prevent you from have incompatible property values for your project. it breaks when you add file or include and exclude properties, it doesn't exclude or include those values or tell you how to write them. 

Writing a UI proves that your tsconfig json file works or doesn't by forcing you to support the properties you export. It helps expose bugs and fix them internally so you can release the UI for it. Not having a UI is negligent in that it allows you to blame the user instead of the author who could prove if the config works or not.

**Comment by velara3** [comment]
@RyanCavanaugh Your point of pointing to so many resources existing about tsconfig proves my point pointing out that it needs a UI: 

<img width="653" alt="image" src="https://github.com/microsoft/TypeScript/assets/1084127/cae87a6d-a927-4389-b073-2fd5ef044826">

Roughly quoting, "If the book store is filled with tons of books on a subject that subject most likely hasn't been solved to a scientific satisfactory degree. When it has (like math), there's 3 or 4 books." - Neil DeGrass Tyson
