### ISSUE TITLE
Failed to acquire camera feed :Error : getUserMedia is not implemented in this browser

### ISSUE THREAD

**Issue by Nitika2023** [microsoft/TypeScript#57438]
### 🔎 Search Terms

I am using getUserMedia but when i am run in my mobile browser its give me  error "Failed to acquire camera feed :Error : getUserMedia is not implemented in this browser "

### 🕗 Version & Regression Information

- This is a crash
- Typescript version "^5.3.3"

### ⏯ Playground Link

https://github.com/VinceG/vue-web-cam/issues/47

### 💻 Code

 if (navigator.mediaDevices.getUserMedia) {
        navigator.mediaDevices
          .getUserMedia({
            video: {
              width: { ideal: VIDEO_WIDTH },
              height: { ideal: VIDEO_HEIGHT },
            },
          })
          .then((stream) => {
            mediaStream.current = stream;
            videoEl.current.srcObject = stream;
          })
          .catch((error ) => {
            alert('testingggg',)
          });
      }

### 🙁 Actual behavior

its not allow me to run the website in mobile bowser in local server . I also done the all settings ,upgrade  

### 🙂 Expected behavior

I expected its run also in localhost server because we want to test the code 

### Additional information about the issue

if (navigator.mediaDevices.getUserMedia) {
        navigator.mediaDevices
          .getUserMedia({
            video: {
              width: { ideal: VIDEO_WIDTH },
              height: { ideal: VIDEO_HEIGHT },
            },
          })
          .then((stream) => {
            mediaStream.current = stream;
            videoEl.current.srcObject = stream;
          })
          .catch((error ) => {
            alert('testingggg',)
          });
      }

**Comment by MartinJohns** [comment]
This not an error with TypeScript. Chrome is requiring secure origins (HTTPS) for `getUserMedia`.
