### ISSUE TITLE
informations about language services

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#5743]
HI,
where I can find more informations about using typescript language services from csharp programs like a scaffolder and/or a visual studio extension?
When I'm able to interface to the language services, what can I do?

**Comment by DanielRosenwasser** [comment]
Hey @lucamorelli, you can take a look at:

* [Using the Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)
* [Using the Language Service API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API)
* [A list of available APIs in our services layer](https://github.com/Microsoft/TypeScript/blob/c94dcbd770f0ed8631678c69d00e3c2d4f30613a/src/services/shims.ts#L99)
* [A list of available APIs exposed by TS Server](https://github.com/Microsoft/TypeScript/blob/c94dcbd770f0ed8631678c69d00e3c2d4f30613a/src/server/session.ts#L952)

**Comment by lucamorelli** [comment]
thanks
