### ISSUE TITLE
Typo in the 2.2 release notes page

### ISSUE THREAD

**Issue by eugeneilyin** [microsoft/TypeScript#57430]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html

> Note that the union type case only **only** occurs

**Comment by xiBread** [comment]
Wrong repo https://github.com/microsoft/TypeScript-Website

**Comment by eugeneilyin** [comment]
Thanks, will PR there.
