### ISSUE TITLE
Missing type leaks through properties inference with `exactOptionalPropertyTypes`

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#57446]
### 🔎 Search Terms

missing type exactoptionalpropertytypes inference properties undefined never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=5.4.0-dev.20240220#code/PTAEAEFMA8EMGMAuB5ADoglgewHawDYAKATlqpMYgJ4AqV5AzgFyiLECukAUNeaDZAaJQAXlABvUKlKoA-CxyQAbhVABfUDESQcAEwYSpM+aAw4AZqprrQs-qBbmCDSAG4uIUF9AA9WUA

### 💻 Code

```ts
// @exactOptionalPropertyTypes: true
type Test = { prop?: never } extends { prop?: infer T } ? T : false;
//    ^? type Test = undefined
```

### 🙁 Actual behavior

Infers `missingType` (it displays as `undefined`). This is wrong since, I believe, `missingType` should mostly be an internal type that is either removed or converted to a regular `undefined` depending on the context/operation.

### 🙂 Expected behavior

`never` should be inferred here.

### Additional information about the issue

I discovered this while reducing my repo to this minimal~ repro case: [TS playground](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true&ts=5.4.0-dev.20240220#code/PTAEAEFMA8EMGMAuB5ADoglgewHawDYAKATlqpMYgJ4AqV5AzgFyiLECukAUF9eaADUCnBgB4aAPlABeUDQDaAa0hUsAMzkBdANw8+kUAFEAbpBwoARgCtISGaADeXUK3qQWDNhhwBzXQF9dLm9ECjUEAwBBJCxiABksHwx4cRMzRFAYUJwAEwYjU3Nka1tEKScXNlgcBgxMXBYACkhjFho08wBKGSl2HEUcLAB3HAC9N1AAVX7BkejEWISk+Ht5xcTk0RwWigkgkLCI0BIsYwwcyBy14kdnUAZieA8vX10XfA2nqZnhnGul5JjYLmQ7wKJIbA4ABifQhuHE10y0GyeWOpDOFyuMWI5TujU6LGMWHOb1AAH0sOxEGSaNcAPxta5Ag7EcJg0CRBi1Hx-OE4BHYpEo-InDGXa64lz4wnEnKkilUmn0xnY5kg1lHACyCAAFt5IABhXBqDA+AULG5ZMyo0XncXYyWZczEKgMjl8mE4Pnm2J7Lj+HgXeD4WDEAxqWH1HCgWBc0382mCq25EXou1Yi0SRp3MlNBioWAjJoIC0qi3yABED3gFc03WkUiJ53r5X8ABouASOXGefNIT6cUF9HIsLbMdcB-lk6iAEq2WI5USeYjeHxt74DX7-T4SKTSO5CfAiUQVFygeQAaVA3lAylUGkTFvyADJ7i8fJoWKez-dHiwL6SP4fMsZaxAwl46HcLiBHc-h+lwQYhmGoARl6Ub3JAiDsKgoh3I+YFCta+RzvAC5Lu+67TJuczYgC8B7o47ZcFmGAALaoPgkCseksBRgwbqniWYECeeV43ne6hyNcDCflJ2LgRemigDB-hdqe8BhrxkDavAerbCwuE-qRNQZDQRo4CaPiESmoA6XphrGqa4ijmm47YpOu4di4WZQaAxmWW05mWV5oAtqATZyv6QSIaGBjGZ4fmUuqdEsNuywnq45AsBWACSAByBozoYmqGHlNAVsp8EgEisDsZxoDsAwsA+NwDCYdhjSCfJX6JX0oTECwpF9RQdHKR2qkAHQaZAWl2fqnV3OkLosLG3I4I0jT5oWOBhd+9wFiMjQVkN6oVp02igNVWCKL5W2HRWBChqxZ0XdVFCkMQvlhlhxDRg4MHQZ043nTw1WDKAqCuZcMbyeuAAGq3xnD9w6pS+A5G+GD4PgoBDLEN1tVhqD4lNmmhHN2wLS4S1UCtPbrfiPSgJ1qlA-6INAA). After discovering what happens that led me to creating this very minimal 1-line repro case.

**Comment by fatcerberus** [comment]
I was thinking this might be correct since it's probably inferring the read type of `prop` (which would be `T | undefined` for an optional property), but if we change the repro code to

```ts
Test = { prop?: string } extends { prop?: infer T } ? T : false;
```

then it infers `string` so yeah, for consistency I'd expect the original repro to infer `never`.
