### ISSUE TITLE
Automation server can't create object problem

### ISSUE THREAD

**Issue by paulcode83** [Microsoft/TypeScript#5744]
after i installed Typescript 1.6.3 on visual studio 2015 , when i build a project i have this error in output window :"VSTSC : tsc.js(704, 13) JavaScript runtime error : Automation server can't create object . " When i unistall it, all works correctly. what happens? has anyone the same problem?
Thank you for your time

**Comment by mhegazy** [comment]
Did you happen to uninstall or reinstall IE after you installed TS/VS?

**Comment by paulcode83** [comment]
No , it happens when i install visual studio 2015 and i had install a
previous visual studio version on my pc yet.
I think that it depends on enviroment variables.


2015-12-02 5:26 GMT+01:00 Mohamed Hegazy <notifications@github.com>:

**Comment by mhegazy** [comment]
> I think that it depends on environment variables.

can you elaborate?

**Comment by robcube** [comment]
VS 2015 Update 1: I have the same issue. It compiles to js just dandy when I save the ts file, however when building the solution, it throws the error "VSTSC : tsc.js(764, 13) JavaScript runtime error : Automation server can't create object." Even running in under Developer Command Prompt for VS2015, simply running tsc outputs the same error. TypeScript 1.7.6/WIndows 7

**Comment by mhegazy** [comment]
@robcube, What version of IE do you have on your machine?

**Comment by mhegazy** [comment]
this looks like a mismatched version of IE after the installer ran. please run repair on the installer or install IE 11.
