### ISSUE TITLE
moduleResolution Bundler fails to get symbols from another repo with path alias 

### ISSUE THREAD

**Issue by yf-yang** [microsoft/TypeScript#57455]
### 🔎 Search Terms

bundler, path

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about everything

### ⏯ Playground Link

Nope

### 💻 Code

Check the reproduction repository https://github.com/yf-yang/ts-bundler-bug

Installation:
``` shell
pnpm i
```

To review the bug:
Open file `packages/derived/src/index.ts`, the language server will complain about the error, `tsc` is the same.

A description of the code:
There are two repos in the monorepo, `base` and `derived`.

```
- base
|-- index.ts
|-- types.ts
|-- nested
  |- index.ts
- derived
|-- index.ts
```

In `base/types.ts`
``` typescript
export interface InterFaceA {
  a?: number;
}

export type Generic<T extends InterFaceA = InterFaceA> = T & {
  something: number;
};
```

In `base/nested/index.ts`, pay attention to the import statement
``` typescript
import { InterFaceA } from "@/types"; // THIS LINE IS THE ROOT CAUSE

export interface InterFaceB extends InterFaceA {
  b?: number;
}
```

In `derived/index.ts`

``` typescript
import type { Generic, InterFaceB, InterFaceC } from "base";

function foo(): Generic<InterFaceB> {
  return {
    something: 1,
  };
}
```

In `base/tsconfig.ts`
``` json
{
  "compilerOptions": {
    "paths": {
      "@": ["."],
      "@/*": ["*"]
    }
  }
}
```

### 🙁 Actual behavior

In `derived/index.ts`, 
Type 'InterFaceB' has no properties in common with type 'InterFaceA'.

### 🙂 Expected behavior

No error.

### Additional information about the issue

This error happens, because TypeScript fails to get path from path alias.

The resolution procedure:
`derived/src/index.ts` resolve `base` => find the correct file `base/src/index.ts`
`base/src/index.ts` resolve `./nested` => find the correct file `base/src/nested/index.ts`
`base/src/nested/index.ts` resolve `@/types` => failure, `InterfaceB` type falls back to `any`

I also added the same function `foo` to `base/src/index.ts`, and another function `bar` as a comparison, they are all working as expected, indicating the failure to resolve path alias is the root cause.

**Comment by yf-yang** [comment]
Before `"moduleResolultion": "Bundler"` is supported, the stuff is usually dealt with `ts-patch` and `typescript-transform-paths`

``` json
{
  "compilerOptions": {
    "plugins": [
        {
          "transform": "typescript-transform-paths"
        },
        {
          "transform": "typescript-transform-paths",
          "afterDeclarations": true
        }
     ]
  }
}
```

**Comment by yf-yang** [comment]
@RyanCavanaugh Sorry to directly @ you, why this issue is not triaged? I mention ts-patch in the comment, but the plugin does not work for tsserver, so the coding experience with the editor is still broken and this issue cannot be solved by any 3rd party solution afaik. 

According to the search results, seems Andrew is the expert.

**Comment by RyanCavanaugh** [comment]
@yf-yang I have other responsibilities too, and it's been not even 48 hours. For issues that take more than a few minutes to figure out, it takes a bit longer to find time to look at them.

**Comment by RyanCavanaugh** [comment]
`derived` isn't even aware of `base`'s tsconfig in this repo, and can't make decisions based on what path mappings it had.

This isn't a bug, it's just a misconfiguration that produces unusable output. Everything is doing what you told it to do.

**Comment by yf-yang** [comment]
Thanks for your response! Are there any instructions 🤔 ?

Let me describe my use case, I am setting the project based on [turborepo's official example](https://github.com/vercel/turbo/tree/main/examples/basic), then I find it is painful to rebuild and rebuild again to get the latest type signature when changing a dependency folder's file and developing another folder. In order to allow the tsserver to instantly catch up with the latest signature, I find the `"moduleResolution": "bundler"` option and figure out it does work for most the case (except for the path alias).

Suppose `"moduleResolution": "bundler"` is the correct configuration for this use case, how can I tell the tsserver to do so? Via project references?

**Comment by yf-yang** [comment]
Update: 
To do so, add base repository to [tsconfig references](https://www.typescriptlang.org/tsconfig#references)
To enable references, the [composite](https://www.typescriptlang.org/tsconfig#composite) option should be enabled
