### ISSUE TITLE
tsc compiler will ignoring *.*.*.d.*.*.

### ISSUE THREAD

**Issue by Rick4CieNETLiaoKe** [microsoft/TypeScript#57456]
### 🔎 Search Terms

compiler

### 🕗 Version & Regression Information

- latest typescript

### 💻 Code

if i have a file named : a.c.v.ts
use command 'tsc a.c.v.ts' 
ok it is working, there will be a compiled file named a.c.v.js
but when i have a file named 'a.c.d.s.m.ts'
and 'tsc a.c.d.s.m.ts'
then there is nothing happen...

### 🙁 Actual behavior

can't compile file that named 'a.c.d.s.m.ts'

### 🙂 Expected behavior

file named 'a.c.d.s.m.ts' should be compiled

### Additional information about the issue

I can understand typescript ignoring *.d.ts - because *n.d.ts is a declaration file

but why ignoring *n. *. *. d. *n. *. ts ????

Is there any particular reason？

**Comment by RyanCavanaugh** [comment]
The correct filename to describe `foo.json` is `foo.d.json.ts`, so `.d.` anywhere in the path is treated as "is declaration"

**Comment by Rick4CieNETLiaoKe** [comment]
> The correct filename to describe `foo.json` is `foo.d.json.ts`, so `.d.` anywhere in the path is treated as "is declaration"

ok make sense, thx!
