### ISSUE TITLE
Though we are filtering out for undefined values, typescript is not able to recognize this. 

### ISSUE THREAD

**Issue by JosephJibi** [microsoft/TypeScript#57457]
### 🔎 Search Terms

![image](https://github.com/microsoft/TypeScript/assets/90312113/f4785d7c-af11-4c02-9609-2f0d8b5f03c1)

### 🕗 Version & Regression Information

- This is a crash
- I was unable to test this on prior versions.

### 💻 Code

```ts
    const foo = [1, undefined, 2];
    const foo2: number[] = foo.filter((value) => value);
```

### 🙁 Actual behavior

Show this error in 'foo2' :
Type '(number | undefined)[]' is not assignable to type 'number[]'.
  Type 'number | undefined' is not assignable to type 'number'.
    Type 'undefined' is not assignable to type 'number'.

### 🙂 Expected behavior

Should not show this  any error, because we are filtering out all undefined.

### Additional information about the issue

![image](https://github.com/microsoft/TypeScript/assets/90312113/40eca355-87b1-4e71-b7e8-32d080f19971)
![image](https://github.com/microsoft/TypeScript/assets/90312113/3edcc734-b0e0-4aa5-bbf9-e2999a66b137)

**Comment by bgenia** [comment]
see #16069 #38390

**Comment by fatcerberus** [comment]
> Search Terms: [image]

I didn't know GitHub had image search :wink:

**Comment by tomkcook** [comment]
On a semi-related note, it'd be nice if the return type of a type predicate were transitive.  At the moment, this doesn't work:

```
class Foo {
  foo?: string;

  isComplete(): this is CompleteFoo { return this.foo !== undefined; }
}

interface CompleteFoo extends Foo {
  foo: string;
}

const arrayOfFoo: Foo[] = [];
const completeFoos = arrayOfFoo.filter<CompleteFoo>((foo) => foo.isComplete());
```

because even thought the type of `Foo.prototype.isComplete` is declared as `this is CompleteFoo`, when it's called that type collapses to `boolean` and the compiler has to be told again that it's a type predicate:

```
const completeFoos = arrayOfFoo.filter<CompleteFoo>((foo): foo is CompleteFoo => foo.isComplete());
```
