### ISSUE TITLE
Incorrect import destination after using `Move to file`

### ISSUE THREAD

**Issue by aramikuto** [microsoft/TypeScript#57451]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.0-insider (Universal)
- OS Version: macOS 14.3.1

Steps to Reproduce:

1. Create files `utils.ts` and `program.ts`
2. Create and export any function inside `utils.ts`.
3. Import this function from `program.ts`.
4. Move the function into `program.ts` using the `Refactor` -> `Mote to file` action.

**Expected result**:
The function should be excluded from the import in `program.ts`.

**Actual result**:
The import statement for the function remains present, and the import destination changes from `utils` to `program` (which would not work).

**Comment by fatcerberus** [comment]
For what it's worth, circular module references (and therefore self-imports) are legal in ESM.  I wouldn't try to claim this behavior is desirable though 😜

**Comment by eloyrobillard** [comment]
I have a PR that will prevent self-imports for this issue.
