### ISSUE TITLE
TS gets very confused when merging objects inside a generic function

### ISSUE THREAD

**Issue by denis-migdal** [microsoft/TypeScript#57466]
### 🔎 Search Terms

none

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=5.3.3#code/GYVwdgxgLglg9mABMOcA8ARAhlLiCmAHlPmACYDOiASvhHAE5loVQMxgDmANIlmAE8AfEIAUZHFgBcibLgCUiAN4AoNYg2J6YVogBCAQQDKAUQD6GAwBUDiALzKVm54gBEGEwBkTVkxlcybCD4TpoAvgDc6poA9DF8gogAtvgMnBycyfhQABZwZAB0RaEacYg5UFAADhRScaxYEADWcABuqcAANnAA7gX0STEAjsGs8DoxACwAnABsABwATACss9MxUAJV+BQQ7FVQALQpafiHcABGAFZ0R5vbFCWI9-g0PmZWAJoACib2iAB5JIwKCYSS8dxeHx+VxCRAAMmeW3wcGA+mM5ksNiiT062UQDB2IE6UA0DgB11uBSwFAoME4YFESjCvAkuF4hlMFmsBnkUWceNJhIoxKgi3+FJu0GptPpjOZHIx3JsrMkfNx+OFooAzP9mXwqNR3l9fjjnC9EFYAIz-I1WD4-EwAbUh3l8-gAuhFEGUHHaHb8XR43TCPUUCtENBarOKHC9UQSiSSCsHoRhvWULqg8fxwxHzcjLbq48iE1qSYsU1D3Rn4lm4DmwHnED0GAhOOGntHJv942jy1BtVWQ+mfXXs-hc+HEBQ4IgBHAQIgmmBeogQZ2C9tLcte6X+0nB0Hq6Ha3rw2FjyPXB7I0jt-6TSZY4DgaCaHRGMxWOwuLx+MIEKpu6sIIveKJopymI8vymjRrMtrGo6ixXmmN5nvWjadhqpIwFaMhWLuDiTGeqRtgwOHrosBEIcRpEMORlEwNqBE2nRY4EAxjAqGEQA)

### 💻 Code

```ts
function foo<Data extends Record<string, any>>(data: Data) {


    const BASE_DATA = {
        "DELETED": true
    };

    // any merging method...
    // https://stackoverflow.com/questions/49682569/typescript-merge-object-types
    type RET_TYPE = Omit<Data, "DELETED"> & typeof BASE_DATA;

    let result  = Object.assign({}, data, BASE_DATA);
    let result2 = Object.assign({}, BASE_DATA, data);
    let result3 = {} as RET_TYPE;

    type T1 = RET_TYPE["DELETED"]; // = RET_TYPE["DELETED"]...

    type T2 = typeof result.DELETED; // boolean....
    type T3 = typeof result2.DELETED; // boolean.... wrong...
    type T4 = typeof result3.DELETED; // boolean.... so you know it...
    type T5 = typeof result3["DELETED"]; // = {...}["DELETED"]

    type RET_TYPE2 = Omit< Record<string, any>, "DELETED"> & typeof BASE_DATA;
    type T6 = RET_TYPE2["DELETED"]; // boolean...

    let i3: T1 = true; // error
    let i1: T5 = true; // error
    let i2: T6 = true; // ok
}
```

### 🙁 Actual behavior

In this context, TS is somehow losing type informations when manipulating types with `[""]` (cf T1 and T5), when he knows the type as shown by T4. In other contexts, TS doesn't lose the type informations as shown by T6.

There is also an issue with `Object.assign()` where the returned type is wrong (cf T3, `data` can have a member called `DELETED` that will override `BASE_DATA.DELETED` in the `Object.assign()`.)

### 🙂 Expected behavior

TS shouldn't lose type informations and shouldn't bully me like that.

T3 should be any, as `data` can have a member called `DELETED` that will override `BASE_DATA.DELETED` in the `Object.assign()`.

**Comment by RyanCavanaugh** [comment]
`Object.assign` is not 100% correctly representable in the type system so the resulting types may not be perfect. See #10727 for the needed operator.

> TS shouldn't lose type informations and shouldn't bully me like that.

This isn't a defined behavior; please be specific.

You seem to be a little confused on syntax,
```ts
type T5 = typeof result3["DELETED"]; // = {...}["DELETED"]
```
is parsed as
```ts
type T5 = (typeof result3)["DELETED"]; // = {...}["DELETED"]
```
so is correctly different from `typeof result3.deleted`, which parses as `typeof (result3.deleted)`

**Comment by denis-migdal** [comment]
I think I just found out a workaround... I think I understand why it works, but I'm not fully sure.
I'll have to check tomorrow if it works in the context of my code.

```ts
function foo<Data extends Record<string, any>>(t: { [K in keyof Data]: K extends "DELETE" ? never : Data[K] } ) {

    type BASE_DATA = {DELETE: boolean};

    type RET_TYPE = {
      [K in keyof (Data&BASE_DATA)]: (K extends keyof Data ? Data[K] : never) | (K extends keyof BASE_DATA ? BASE_DATA[K] : never) 
    }

    let a: RET_TYPE["DELETE"] = true;

    return {} as RET_TYPE;
}

{
  let f = foo({a: 32});
  f.DELETE // boolean
  f.a // number

  type Z = typeof f;
  type A = Z["DELETE"] // boolean
  type B = Z["a"]      // number
}
{
  let f = foo({a: 32, DELETE: 43});
  f.DELETE // does not exists
  f.a // does not exists
}
```

**Comment by RyanCavanaugh** [comment]
> Even though Data["DELETED"] IS omitted...

`Omit` is a userland type alias, not a primitive operation, so TS isn't capable of using it to do the kind of higher-order reasoning that you're doing here.

**Comment by denis-migdal** [comment]
> `Omit` is a userland type alias, not a primitive operation, so TS isn't capable of using it to do the kind of higher-order reasoning that you're doing here.

Thanks for your answer.
I'm not quite sure what would be the difference between a "userland type alias" and a "non-userland type alias".
Is there some documentation on it somewhere ?

I'll have to check things more in depth tomorrow.
Some workarounds seem to work with this simple case, but I believe it didn't initially work when I first tried them in my more complex code. I'll have to test it little by little to see if I missed something or if I have indeed something else going on.


Another version that seems to work:
```ts
function foo<Data extends  Record<string, any>>(t: Data) {

    type BASE = {DELETED: boolean};

    type RET_TYPE = {

      [K in keyof (Data&BASE)]: K extends keyof BASE ? BASE[K] : Data[K]

    } & {};

    let a: RET_TYPE["DELETED"] = true; // TS error

    return {} as RET_TYPE;
}

let f = foo({a: 32});
```

**Comment by MartinJohns** [comment]
I'm not sure understand what `Omit<Data, "DELETED">` does. This is essentially a no-op, you can't omit a specific key from a record.

**Comment by denis-migdal** [comment]
> I'm not sure you understand what `Omit<Data, "DELETED">` does. This is essentially a no-op, you can't omit a specific key from a record.

Shouldn't this behavior be documented ? or raising a warning when doing so ?

I'm even more confused now. Indeed, the following code works without the `Omit` :
```ts
type Data = Record<string, number>;
type RET_TYPE2 = Data & {DELETED: boolean};

let b: RET_TYPE2["DELETED"] = true;
```
But why ??? Shouldn't `RET_TYPE2["DELETED"]` be of type `never` ? (`number & boolean`).

And this one doesn't :
```
function foo<Data extends Record<string, number>>() {
    type RET_TYPE2 = Data & {DELETED: boolean};

    let b: RET_TYPE2["DELETED"] = true; // b not assignable to type `never`.
}
```

> you can't omit a specific key from a record.

I guess the best workaround we have is :
```ts
type T = Record<string, any> & {DELETED?: never}
```
The only issue is that it can also take `undefined` as a value...

Isn't it strange that:
```ts
type T = Record<string, any> & {DELETED: never}
let t: T = {} // error, DELETED missing
```
Requires the "DELETED" key to be present ?
Should I open an nth suggestion or is this normal ?

**Comment by denis-migdal** [comment]
> I guess the best workaround we have is :
> 
> ```ts
> type T = Record<string, any> & {DELETED?: never}
> ```
> 
> The only issue is that it can also take `undefined` as a value...

According to the documentation:

> The never type represents the type of values that never occur.

Then shouldn't the following be correct in this case ?

```ts
type T = {
     DELETED: never // DELETED never occur, i.e. can't be used in type T.
}
let t: T = {} // TS error: missing key DELETED
```

Otherwise, shouldn't the documentation state something like the following instead ?

> The never type represents a type whose constraints are never satisfied. It can be used to represent the type of values that should never occurs, but the variable still exists.


I also noticed that TS doesn't seem to have a way to express a facultative attribute that can't be undefined...

**Comment by MartinJohns** [comment]
> Shouldn't this behavior be documented ? or raising a warning when doing so ?

You can't document every single small pitfall. And when you look up how `Omit<>` is defined it should be understandable. Or if you check the resulting type of your intersection and see that the `DELETED` is gone.

> But why ??? Shouldn't `RET_TYPE2["DELETED"]` be of type `never` ? (`number & boolean`).

It's an intentional unsoundness to allow combining types with index signatures (that's what `Record<>` basically is) and incompatible typed known properties. Keep in mind that having a fully sound type system is not one of TypeScripts design goals.

What you want would basically require "negated types" (#4196), so you can represent a type "any key, except this one". This is currently not possible. There are many many issues about this use case.

**Comment by denis-migdal** [comment]
> You can't document every single small pitfall.

The issue is that it seems there are a *lot* of pitfalls, that are hard to understand if we don't know exactly how TS is doing things behind the curtain... and I do not know if we have access to such documentation.

>  And when you look up how `Omit<>` is defined it should be understandable.

How so ?

> type Omit<T, K extends string | number | symbol> = { [P in Exclude<keyof T, K>]: T[P]; }

How am I supposed to know that if `keyof T` is `string`, then `Exclude` will have no effects, simply by reading the `Omit` definition ?

It is maybe obvious for you as you seem to be a contributor, but for a simple user, this isn't.
It is even less obvious when you get a type error due to this, with an unreadable error message due to complex type manipulation...


> Or if you check the resulting type of your intersection and see that the `DELETED` is gone.

?

> > But why ??? Shouldn't `RET_TYPE2["DELETED"]` be of type `never` ? (`number & boolean`).
> 
> It's an intentional unsoundness to allow combining types with index signatures (that's what `Record<>` basically is) and incompatible typed known properties.

But why doing something unsound, when you could simply add a e.g. `Assign<X, Y>` type utility to explicitly perform such dangerous operation ?
This unsound thing can lead to undetected bugs, as shown by the exemple I gave above.

I could understand the principle, but at the same time, when doing it inside a generic function, it doesn't work anymore...
There is no consistency in this behavior...

> Keep in mind that having a fully sound type system is not one of TypeScripts design goals.

It is really hard to use when we get stuck for days due to undocumented unsoundness.

> I'm not sure what you mean with "facultative attribute". If you mean an optional property, then this is intentional, because reading a missing property results in `undefined`.

If, indeed, reading a missing property results in `undefined`, this isn't the same as having a property which value is `undefined`.

For me this is clearly a bug, and I opened an issue for that:
https://github.com/microsoft/TypeScript/issues/57479

**Comment by RyanCavanaugh** [comment]
@denis-migdal the documentation tries to explain concepts so that you can understand how things work at a high level, and assumes that the reader is capable of doing simple experiments if they are curious about edge cases. If you're new to a language I always recommend doing small little tests to understand it better, as well as reading all of the documentation (it's not that long).

**Comment by denis-migdal** [comment]
> @denis-migdal the documentation tries to explain concepts so that you can understand how things work at a high level,

For example, in the documentation for `Exclude`, nowhere it states that `Exclude<string, "test">` would have no effects, and tsc generates no error for that. Idem for `Omit<Record<string, number>, "test">`. Idem, in the documentation for type intersections, it doesn't state that we should be cautious when using them with indexed type as it produces counter-intuitive results.

But, in order to use TS properly, we need to know that, or at least to be warned by tsc.


> and assumes that the reader is capable of doing simple experiments if they are curious about edge cases.

But for that we need to know that theses are edge cases.

I got an error, which were unreadable. I spent hours trying to get a minimal reproducible example.
Only to discover that there are a strange behavior that manifests sometimes, and sometimes doesn't, for something that I though was trivial. A part of code that worked in the general case, but stopped working when put in a generic function.

**Comment by RyanCavanaugh** [comment]
The docs say

> Constructs a type by excluding from UnionType all union members that are assignable to ExcludedMember

`string` isn't a union. A union type looks like this: `A | B`.

**Comment by RyanCavanaugh** [comment]
The docs never imply that strings are unions, nor are any unions in TypeScript infinite as would be required. I don't know how to write documentation in a way that fends off any incorrect assumptions the reader might come in with, unfortunately, and people come up with new incorrect assumptions on a daily basis. I think it'd be tiresome to read docs that spend the majority of their time disclaiming incorrect interpretations.

> Couldn't some warnings be added

Of course; TypeScript has thousands of warnings. If you're doing something that doesn't generate a warning, it's probably because that thing is also plausibly some intended thing. Can you be more specific?

**Comment by denis-migdal** [comment]
> I think it'd be tiresome to read docs that spend the majority of their time disclaiming incorrect interpretations.

What about some spoilers (e.g. with details/summary HTML tags) : "Show some common misconceptions" ?
Or a page for common misconceptions and workarounds ? To put the knowledge dispersed in the git issues into a single page ?

I don't know, maybe there is something possible to do.

> Of course; TypeScript has thousands of warnings. If you're doing something that doesn't generate a warning, it's probably because that thing is also plausibly some intended thing. Can you be more specific?

For example, when doing :

`Exclude<string, "toto"|"titi">` : I understand now that this is theoretically correct, but it is very likely that this doesn't do want the user tries to do.
The rule could be to warn (with an opt-out flag) "when the ExcludedMembers contains literals of a type specified in UnionType", or could be restricted to "when UnionType is a type, and ExcludedMembers is literals of this type".

In the same way :

`Omit< Record<string, any>, "toto"|"titi">` : "When Type has an index signature and Keys is compatible with the index signature key ?".

**Comment by MartinJohns** [comment]
The compiler does not know what type `T` is, so it can't resolve the type involving `typeof addEvents`.

**Comment by denis-migdal** [comment]
> The compiler does not know what type `T` is, so it can't resolve the type involving `typeof addEvents`.

It doesn't matter, as no matter what type is really `T`, it is still possible to know the type of some properties.

Furthermore :
```ts
type T = (keyof typeof events) | (keyof typeof addEvents); // = "DELETED" | keyof T
```

So here the compiler at least knows that he can try to precompute the type for the already known "DELETED" property.

**Comment by denis-migdal** [comment]
For future reference, simply adding a `// @ts-ignore` inside the generic method seems to work and causes to issue outside the generic method... Not ideal, but as long as it works...

**Comment by MartinJohns** [comment]
> It doesn't matter, as no matter what type is really `T`, it is still possible to know the type of some properties.

And that doesn't matter. The compiler does not resolve types that contain unbound generic arguments. Besides that, `T` could be typed `{ DELETED: number }`, resulting in `never`.

> For future reference, simply adding a `// @ts-ignore` inside the generic method seems to work and causes no issue outside the generic method...

Yes, `@ts-ignore` can be used as an escape-hatch, when you either willingly want to ignore potential type issues or the compiler can't figure out the correctness of your code (due to design limitations).

**Comment by denis-migdal** [comment]
> And that doesn't matter. The compiler does not resolve types that contain unbound generic arguments.

Well, it should.
It'll like be :
- more performant ;
- cleaner type printing in errors/hovering ;
- remove some non-errors.

> Besides that, `T` could be typed `{ DELETED: number }`, resulting in `never`.

Nope.

The only way `T` could be an issue, is for the 4th case (`keyof (U&T)`), if typed `{ DELETED: never }`.
For the other cases, no matter `T`, the answer will always be `boolean`.

**Comment by denis-migdal** [comment]
This is an issue only in the case 4:

[Playground Link](https://www.typescriptlang.org/play?ts=5.5.0-dev.20240224#code/N4KABBYGYK4HYGMAuBLA9naa0B4AqYApgB5KFwAmAzmAEqEJoBOFOVSTKcA5gDRjwA1nDQB3OAD4JACiQAuMHgCUYUJHVhGcdkQBu5JDUgBeVQBEAogBkLeC2YUcYhAL4B6N1RgAHQkwB0APqE+nCGANzgGhBaOgCGFBQWoYZgpsAuYHE0eOFgHmBUKAC2MAA2cWRR0UgAnr5gAFoATGmq1dGQANoA0mBcYNKChLVoUGB1vmN6BlQqAD6Dw6Pjk4TTCUkpcwC6CgBG2GWEcXAd6i6RnWBMhEgwTJgZWTQtV5AuIB2xSGCBt79TFBsNJgJYbHYHGAACwAZhcSi6ACJwbZ7EidnkCoc0MdTiBPmpILBEKgMFhcAQSGRKDR6IwWGwOFw+AI4MIxJIZPJFCoidEfjMwkYIOlUZDHExnO5PD4-EEQrN3gKMPFEslZm1ntlFFi3IUSuVKoRzpA1k1WulTdFev1MMtprJ6utxorhWAAGQTZ0bdXbJR7MA4vFna6Xa03O4PJ6ZHVvDqfb6q37-O5tYFoUHi+wKOEI5HZswYvVBo4nM6Ejok5DoTAZ-BEUjkah0BjMVjsTg8fhCETiKSyBTKdrXQVu1ImczWNFQpyuDxeXwBYLbZUaQWbDXu9KxnIloqlCpVa7mlpaiPqW0DIYjaZrabjuZgRY3lbeqbjTf+wN9anNmgOqsPqutsYAAPylri5YKJ2LIRuG1wAtGqi7haa6JuogqpoCFJZtOEowvCiIovh6KYvk+rBuWBJAA)

So I stand correct for case 3 and 5...
