### ISSUE TITLE
Untyped JS module is not assignable to type even though it satisfies it

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript#57460]
### 🔎 Search Terms

Untyped JS module is not assignable to type even though it satisfies it, "Object literal may only specify known properties"

### ⏯ Playground Link

https://github.com/bradzacher/bug-repros/tree/ts-js-issue-huh

### 💻 Code

```ts
import eslintReact from 'eslint-plugin-react/configs/recommended.js';

(eslintReact satisfies {
  plugins: {
      react: {
          rules: any;
      };
  };
});
```

### 🙁 Actual behavior

There should be no errors because the type
`{ plugins: { react: { deprecatedRules: any; rules: any; }; }; }`
is assignable to
`{ plugins: { react: { rules: any; }; }; }`

### 🙂 Expected behavior

```
Type '{ plugins: { react: { deprecatedRules: any; rules: any; }; }; rules: any; readonly languageOptions: any; } & { languageOptions: any; rules: { 'react/display-name': number; 'react/jsx-key': number; 'react/jsx-no-comment-textnodes': number; ... 18 more ...; 'react/require-render-return': number; }; }' does not satisfy the expected type '{ plugins: { react: { rules: any; }; }; }'.
  The types of 'plugins.react' are incompatible between these types.
    Object literal may only specify known properties, and 'deprecatedRules' does not exist in type '{ rules: any; }'
```

### Additional information about the issue

This issue is particularly weird because it only occurs in a JS file!

For more context this is the original bug report https://github.com/typescript-eslint/typescript-eslint/issues/8522
And the original repro from the issue (the usecase we really want to fix): https://github.com/printfn/tseslint-react-repro

We have built support for ESLint flat configs via our `typescript-eslint` package and it exports a function to allow typechecking of the config array. So the repo looks like this

```js
// @filename eslint.config.js


// @ts-check

import tseslint from 'typescript-eslint';
import eslintReact from 'eslint-plugin-react/configs/recommended.js';

export default tseslint.config(
	eslintReact, // type error is on this line
);
```

Best I can tell it looks like TS is treating the `eslintReact` variable the same way it would as an inline object expression - hence it's erroring saying "too many properties".

**Comment by Andarist** [comment]
This is a private repo or something: https://github.com/bradzacher/bug-repros/tree/ts-js-issue-huh

**Comment by bradzacher** [comment]
oops sorry made it public

**Comment by Andarist** [comment]
the repro doesn't contain a concrete TS version and a tsconfig.json :P

**Comment by bradzacher** [comment]
Yeah I know. The latter one is intentional.
Users don't setup an `eslint.config.js` and cover it with a tsconfig - it just uses the vscode defaults

As for the TS version - I doubt it matters? I was just using whatever is installed in the latest vscode version.

In the issue I linked a bigger repro if you want some more stuff. I was just trying to be as isolated as possible.

**Comment by Andarist** [comment]
There is some difference between my default and your default setups then because I don't get this error but rather this at the import statement:
> Module '"/repros/bug-repros/foo"' has no default export.ts(1192)

We have to use different module resolutions for some reason.

**Comment by bradzacher** [comment]
sod it, sorry @Andarist - I forgot to push a fix.
The import in `foo.ts` should be from `eslint-plugin-react/configs/recommended.js` (I just updated the repo)

**Comment by Andarist** [comment]
I still get a different error:
> Module '"/repros/bug-repros/node_modules/eslint-plugin-react/configs/recommended"' can only be default-imported using the 'esModuleInterop' flagts(1259)
> recommended.js(5, 1): This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

**Comment by bradzacher** [comment]
Maybe there's some vscode settings that impact this?
Have you changed any of the defaults?

I spent a while playing around with a `tsconfig.json` but I couldn't make it repro with any combo of tsconfig settings I tried.

Can you give this repro a go? https://github.com/printfn/tseslint-react-repro
Just install and open the `eslint.config.js`. 
If it doesn't repro there then you defs have tweaked some settings.

**Comment by Andarist** [comment]
No luck either even after disabling extensions. I downloaded the insiders version of VS Code and I managed to repro it there

**Comment by Andarist** [comment]
This should fix this incorrectly reported error: https://github.com/microsoft/TypeScript/pull/57467 . However, it still won't typecheck in your case because this property from the source isn't compatible with your target: https://github.com/jsx-eslint/eslint-plugin-react/blob/36e791de784e7fa1edd5b6d232fbcaf2dd7cf9bf/configs/all.js#L28

Its type gets computed as `{ [x: string]: number; [x: number]: number; [x: symbol]: number; }`. See the error reported here: [TS playground](https://www.typescriptlang.org/play?ts=5.5.0-dev.20240221#code/JYWwDg9gTgLgBDAzgU0QG2AO3gMyhEOAIhgE8xUBjKYMGAWlQ2yIG44B6Dhc1ALjgB2AHQAGYQCYAUFIAmySmgCGUZHEoRMieEsoxgAN2QAlAK5pUAYU05gAcwEBvKXDgBtAB4DtNTHYC6ApimIABGyFCsLu5ecMFhEYFxIeGR0Z7epGEQaEnxqVEAvlFSGlrwTFgwxsi68AC8cM6uUOb8cHWGJm2I1pi2dgA0UsUySJXYwmUDABQT1bV6AJRRQA)

**Comment by bradzacher** [comment]
> Its type gets computed as { [x: string]: number; [x: number]: number; [x: symbol]: number; }.

If I locally modify my `node_modules` and comment out [the line that's currently erroring](https://github.com/jsx-eslint/eslint-plugin-react/blob/36e791de784e7fa1edd5b6d232fbcaf2dd7cf9bf/configs/all.js#L24) then I get no more errors in my IDE (i.e. I can't repro that wide signature).

Unless I'm misunderstanding and you're saying that after your fix the record is inferred as that wide type?

**Comment by Andarist** [comment]
> If I locally modify my node_modules and comment out [the line that's currently erroring](https://github.com/jsx-eslint/eslint-plugin-react/blob/36e791de784e7fa1edd5b6d232fbcaf2dd7cf9bf/configs/all.js#L24) then I get no more errors in my IDE (i.e. I can't repro that wide signature).

When doing just that (without applying my patch in tsserver, just removing that single line with `deprecatedRules` property) I get the same error as the one that I get with my tsserver patch applied (the one showcased on the TS playground above).

Could you try hovering over `activeRulesConfig` [here](https://github.com/jsx-eslint/eslint-plugin-react/blob/36e791de784e7fa1edd5b6d232fbcaf2dd7cf9bf/configs/all.js#L28)? What type is displayed by the quick info? Is it `{ [x: string]: number; [x: number]: number; [x: symbol]: number; }`?

**Comment by bradzacher** [comment]
Note: filed https://github.com/jsx-eslint/eslint-plugin-react/pull/3694 to add some minimal JSDoc annotations which will short-circuit the TS inference and fix things.

**Comment by bradzacher** [comment]
> Could you try hovering over activeRulesConfig [here](https://github.com/jsx-eslint/eslint-plugin-react/blob/36e791de784e7fa1edd5b6d232fbcaf2dd7cf9bf/configs/all.js#L28)? What type is displayed by the quick info? Is it { [x: string]: number; [x: number]: number; [x: symbol]: number; }?

![image](https://github.com/microsoft/TypeScript/assets/7462525/e5623c2b-c44f-442c-acdc-f7170facc12a)

It just shows `any` for me.

**Comment by Andarist** [comment]
😅 
<img width="318" alt="`quick info showing { [x: string]: number; [x: number]: number; [x: symbol]: number; }`" src="https://github.com/microsoft/TypeScript/assets/9800850/255bd635-80fa-460a-ac8e-c2a549e89610">

Could you try applying my patch to see what happens with it?

**Comment by bradzacher** [comment]
still `any` 😨

the error disappeared though so your patch definitely was applied.

I think you're getting hit by automatic type acquisition and TS is automatically pulling in [`@types/object.fromentries`](https://www.npmjs.com/package/@types/object.entries).
If I manually install that then I get the same behaviour.

Essentially without `@types/object.fromentries` the `object.fromentries` package is too complex for TS to infer types for -- so the `fromEntries` call returns `any`.
With it TS understands the return type and thus propagates that up the call stack and infers that final type.

The JSDoc annotations I added in https://github.com/jsx-eslint/eslint-plugin-react/pull/3695 will short-circuit TS's inference here.

**Comment by Andarist** [comment]
> I think you're getting hit by automatic type acquisition and TS is automatically pulling in [@types/object.fromentries](https://www.npmjs.com/package/@types/object.entries).

Yeah, that's probably it. Thanks for looking into this.

> The JSDoc annotations I added in https://github.com/jsx-eslint/eslint-plugin-react/pull/3695 will short-circuit TS's inference here so that ATA won't change the signature

IIUC ATA might impact `activeRulesConfig`'s type and you have left that untyped so it won't fix your issue completely. The added annotations there might help with the bug fixed by https://github.com/microsoft/TypeScript/pull/57467 though 👍

**Comment by bradzacher** [comment]
> IIUC ATA might impact activeRulesConfig's type and you have left that untyped so it won't fix your issue completely

`const activeRulesConfig = configureAsError(activeRules);` -- I typed `configureAsError` so the type flows into `activeRulesConfig` so it should fix things!

---

`"typescript.disableAutomaticTypeAcquisition": true`
I disabled ATA a long time ago because I kept getting bit by it auto-grabbing `@types/eslint` when I didn't want it to.

**Comment by Andarist** [comment]
> const activeRulesConfig = configureAsError(activeRules)

ah cool, I somehow missed that 👍
