### ISSUE TITLE
triple-slash reference added only if another triple-slash reference exists

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#57482]
### 🔎 Search Terms

triple-slash reference added

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

[Workbench](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEBMFMGMBsCGAnRAXAlgewHYC5Q1kBXaAWACgQIAzDeaHRAW2gOEWByxgH1mexBgGdg0AB5FOGHDHEA6SPLTDKMtNGQ1EsaKACiyZFmQAmUAG9KoG6GFodAa1MF7yGQHMA3JQC+lSmpwOgYmVnZObj4BSCFoUWEsVjQAC09gGTlFZVUqagAeZGgaTUZdQgBPAAd4gF4AIgkpetBgAD5AsAA9UCKBADc9RAAjLEHQRFlQDDRQAHd6eFBuUEgMIthMcYX4JeGhyBhIQiwJqqrslUoJKpNZmmIcTewcUBosLAAKAEo8Q2MzD4KJ1aPRGCw2K1OIhzjkQUUSkUnno0Kcmqh5otQPsJodoMcUqVpjRCISiqAJBh7MIJtxUppesVSsiThTJKhruJbsh7o9nrg3h8fpZrLYimhiMhXjghPAAIQTGn-EymIG+IA)

### 💻 Code

```ts
// @declaration: true
// @filename: /a/node_modules/extra/index.d.ts
interface Error2 {
    stack2: string;
}

// @filename: /a/node_modules/something/index.d.ts
/// <reference types="extra" />
// ^ remove above and it will no directive will be added to app.d.ts
export function foo():Error2;

// @filename: /a/app.ts
// reference to extra will be added here if there exists another reference to extra
export function foo() {
    return null! as Error2;
}
```

### 🙁 Actual behavior

`/// <reference types="extra" />`  is added to `app.d.ts` only if another reference directive to extra already exists (in this example one from `node_modules`)

### 🙂 Expected behavior

`/// <reference types="extra" />` is always added since `extra` is required for `app.d.ts` to be valid

### Additional information about the issue

This was discovered while trying to understand reference directives in the context of isolated declarations.

**Comment by dragomirtitian** [comment]
@andrewbranch do you have any insight on if this behavior is intentional?

**Comment by andrewbranch** [comment]
I feel like I recently stumbled across a piece of code that _doesn’t_ add type reference directives if the types are found in `typeRoots`, but I don’t remember exactly where that was, and it feels unjustifiable to me.

**Comment by dragomirtitian** [comment]
This seems to be intentional, but I still don't understand why:

```ts
function getTypeReferenceDirectivesForEntityName(node: EntityNameOrEntityNameExpression): [specifier: string, mode: SourceFile["impliedNodeFormat"] | undefined][] | undefined {
    // program does not have any files with type reference directives - bail out
    if (!fileToDirective) {
        return undefined;
    }
```
Also `fileToDirective` is populated from the `host` (`const resolvedTypeReferenceDirectives = host.getResolvedTypeReferenceDirectives();`) and `getResolvedTypeReferenceDirectives` just returns the cache of reference directives that were found while parsing the program `SourceFiles`.

This code seems to be really old (2016 by Vladimir Matveev)
