### ISSUE TITLE
flag return within forEach as error

### ISSUE THREAD

**Issue by unicomp21** [Microsoft/TypeScript#5748]
correct me if i'm wrong, TS can't handle a return within a forEach

**Comment by vladima** [comment]
can you please elaborate:
- what `forEach` do you mean: [Array.prototype.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), [ts.forEach] (https://github.com/Microsoft/TypeScript/blob/master/src/compiler/core.ts#L84) or something else
- what 'can't handle return' mean

**Comment by unicomp21** [comment]
Array.prototype.forEach, doing a return from logic within the loop doesn't seem to work.  As a workaround I assigned to a variable declare outside the loop, and then returned it.

**Comment by vladima** [comment]
1. TypeScript does not polyfill `forEach` so in runtime you should get the whatever behavior is provided by the runtime or was polyfilled by some another library
2. do you mean that if you return value from the callback on some iteration it does not become the `forEach`? If yes - then then this behavior per [spec](http://tc39.github.io/ecma262/#sec-array.prototype.foreach) - callback is invoked for each element present in array and `forEach` itself returns `undefined`

**Comment by DanielRosenwasser** [comment]
Yes, TypeScript is just JavaScript at runtime, so all the same libraries will have the same behavior.
