### ISSUE TITLE
Omit enhancement

### ISSUE THREAD

**Issue by Abdel-Monaam-Aouini** [microsoft/TypeScript#57481]
Here's an enhanced version of the `Omit` type that uses the type parameter `T` instead of `any` to ensure type safety:

```typescript
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
```

In this version, `K` extends `keyof T`, meaning `K` can only be a key that exists within the type `T`. This ensures that you cannot omit a key that doesn't belong to the object type `T`, thereby preventing errors when selecting keys to omit.

![image](https://github.com/microsoft/TypeScript/assets/52112750/17b762a7-f98d-4b32-9964-eddf337cf9c2)
![image](https://github.com/microsoft/TypeScript/assets/52112750/7d88a642-3753-42b9-a051-5a5b79ecad3c)

**Comment by MartinJohns** [comment]
You might want to modify your issue, because right now it's absolutely unclear what you're suggesting or asking for. I suggest to use the "Feature Request" issue template.

**Comment by Abdel-Monaam-Aouini** [comment]
> You might want to modify your issue, because right now it's absolutely unclear what you're suggesting or asking for. I suggest to use the "Feature Request" issue template.

check now :)

**Comment by MartinJohns** [comment]
This was suggested numerous times already and has been declined, e.g. #30825. That's also why the issue templates ask for used search terms to find existing issues (at least the bug report one does).

**Comment by fatcerberus** [comment]
Also see https://github.com/microsoft/TypeScript/issues/54451
