### ISSUE TITLE
Regression: Indexed Access of Partial Mapped Type with Union from Generic Function is missing `undefined`

### ISSUE THREAD

**Issue by 3x071c** [microsoft/TypeScript#57487]
### 🔎 Search Terms

generic function, partial, optional, mapped type, indexed access, undefined, bug, regression

### 🕗 Version & Regression Information

- This is a bug
- This changed between versions 4.5.5 and 4.6.2
- This is the behavior in every version I tried (all playground versions)

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99&jsx=0&pretty=true&ts=4.6.2#code/C4TwDgpgBA8gRgKygXigbwFBW1AhgLigEYAaLHOQgJgwF8BuDDAYwHsA7AZ2CgFtcwkACaFMOKAG0A0lACW7KAGsIIVgDMoABVwAnYLNwAbADzwEAPgC6hM9Mt0U6WkzZceOiJ1aGAbhACyAsKOxjIQAB7AEOxCnEoq6lCgkIn8ghBC5gAUyiCEUgCUKOZ8QRkSuZYAdMCsAMrAOvIA5lkFjAD0HVAAegC0fVAAojo6rDpQEZDMUUJQWQAGacIVKpYLcnFgrJycsnCGIFAArjEQavIZBRhAA

### 💻 Code

```ts
type Obj = {
    a: 1,
    b: 2
};

const mapped: {
    [K in keyof Partial<Obj>]: Obj[K]
} = {}

const resolveMapped = <K extends keyof typeof mapped>(key: K) => mapped[key].toString();
// ^-- Error expected (`mapped[key]` is possibly undefined)
```

### 🙁 Actual behavior

TypeScript does not recognize `mapper[key]` might be undefined and emits broken code without errors

### 🙂 Expected behavior

Correct type inference from pre-v4.6.x

**Comment by RyanCavanaugh** [comment]
Isn't the bug earlier? The type `{ [K in keyof Partial<Obj>]: Obj[K] }` should be `{ a: number, b: number }` and the initialization from `{ }` should fail.

**Comment by 3x071c** [comment]
@RyanCavanaugh The `mapped` definition seems to work as intended (`{ a?: number, b?: number }`), as it does in all TypeScript versions since 3.3.3 (from the playground). Kinda surprised if that actually isn't expected behavior.

**Comment by RyanCavanaugh** [comment]
Bisects to #47109

**Comment by jcalz** [comment]
[From here](https://stackoverflow.com/a/78043776/2887218)
