### ISSUE TITLE
errors for duplicate declaration when double versions of the same package is installed

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#5750]
Hi,
  this is and issue I had a few times upgrading aurelia packages during the preview time, but I think may a problem even in production, because looks like that frameworks like aurelia and angular 2 are going to add .d.ts files inside the packages.
  the problem is that upgrading the standard set of aurelia packages, I can have another additional package that still references an older version of some standard packages, as aurelia-templating and so on.
  At runtime I don't see any problem, because module loaders can handle multiple versions of the package, but there is the problem that inside the project you have two versions of the same .d.ts file almost identical.
  How can I handle this?

**Comment by mhegazy** [comment]
the package should not expose a loose .d.ts, it should be a module, modules do not conflict with each other, i.e. no "duplicate declaration" errors. can you elaborate on the details a bit?

**Comment by lucamorelli** [comment]
I found this with aurelia packages during the preview: the **aurelia-framework@1.0.0-beta.1.0.2** package contains **aurelia-framework.d.ts** that contains inside **declare module 'aurelia-framework' ...**.
During the preview I had this situation:
1. before the preview I have, for example, **aurelia-templating@0.0.17** that contains **aurelia-templating.d.ts** .
2. after the update of packages I have **aurelia-templating@0.0.18** that contains **aurelia-templating.d.ts**
3. If in addition to the framework packages I have installed other compoents that depends on the previous build and are not still updated, it may happen that I find installed both 0.17 and 0.18 versions of the templating package, and each of them contains a version of aurelia-templating.d.ts.

The module can handle this and serves the correct version of the module, but typescript find both the d.ts files and start to give errors of duplicate declaration.
I explained the situation?

**Comment by mhegazy** [comment]
i think the Aurelia package should not include these .d.ts files. these files pollute the global namespace, and adding them this way causes conflicts. see this wiki page for more details: https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

i would say it should be a module, just like what typescript typings are see: https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L2192

**Comment by lucamorelli** [comment]
Hmm... I supposed this answer, just surprised because at the moment aurelia and angular 2 teams are using this approach, but I don't know if they'll do the same at rtm.
I'll try to get in touch with some member via gitter to understand a little better the situation.

**Comment by lucamorelli** [comment]
the files they include declare a module, the problem is that in this situation we have due files that describe the same module, causing conflicts.
I spoke with a few people using gitter (I don't know if part of the core team): the issue is known and accepted, and their answer is to remove the duplication source manually.
Remembering a few posts read in the past I suppose this is considered a minor drawback compared to the advantage of having .d.ts files up, running and aligned with the library in a single step.

thinking of is I suppose that in the future this could be a problem: for example, angular include a version of rxjs that could be different from the latest one I obtain installing directly the package, and both angular and rxjs let to export the observable object.
In this scenario you can easily export two different versions of observable in the same source, possibly with differences in the .d.ts creating problems using the same .d.ts with the same definition, but honestly at the moment I don't think is a common scenario

**Comment by mhegazy** [comment]
This area has admittedly been lacking documentation and a coherent strategy. we are currently working on this. issue https://github.com/Microsoft/TypeScript/issues/6438 tracks better documentation here.
