### ISSUE TITLE
Omit returns empty when the base type is a lookup type

### ISSUE THREAD

**Issue by zqtay** [microsoft/TypeScript#57500]
### 🔎 Search Terms

 "omit" "lookup type"

### 🕗 Version & Regression Information
Version 5.3.3, 5.4.0-beta
When a lookup type (i.e. Type["prop"]) is referred in Omit, it returns an empty type and the "not omitted" props are removed.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAKhDOwoF4oG8BQUoEMBcUiATgJYB2A5gNxZQBGA-AcedbQMZOHCmU0C+GDKEhQACjiIQySVJmzAEwLnEQChAeg1QA8gFsSSMEQD2YKACJ2FqADNTeqCOgXVwC8PDQ3ARhS6DYAAeNwAaKABrCBATW3ROZh5WfgA+DC0AwyhjM0trOwcoABsTEwiAV3NnSwkpGQBtC0VECwBdGxIAOghOpy9LNw9qtwAmf31DINrpYEbm91bwqJi4tATuXgpUzW0AYRMiKXYkOggACxwANxID8JMyIpBs03MrDvgoKT0TS4gAE3COTAHwsOBsODIf0sdBsXxw5Aw7HuiCcSj8cnwlgs4ToBAsFn4uA+vmEaM6OFJiB8nTo6W0AFEAB6QY7-Aj3R7PXJvKAkD5fH7-AomRyjQEvEFg3CQ6E2eBnEzlIpQuEIjLzEbkqAAMlRiE1dEICqVULIJiQwDOpgA7oQQDIcIyoBBDgdEciLUoxhi8dj6L7CThiV7KcBNRSNTSgA

### 💻 Code

```ts
type Test = {
  a: string;
  b?: string;
  c?: string;
}

type Parent = {
  test?: Test;
}

// Omit prop "c" from type "Test"
type Test1 = Omit<Test, keyof {c?: string}>
// Omit prop "c" from lookup type "Parent["test"]" i.e. type "Test"
type Test2 = Omit<Parent["test"], keyof {c?: string}>

// Correct behavior, only prop "c" is removed, props "a" and "b" remain
const test1 = {a: "", b: ""} as Test1
test1.a
test1.b
// Expected: only prop "c" is removed from Test2, props "a" and "b" should remain
// test2.a & test2.b should not throw syntax error
const test2 = {a: "", b: ""} as Test2
test2.a
test2.b
```

### 🙁 Actual behavior

`test2.a` and `test2.b` shows error
```
Property 'a' does not exist on type 'Test2'.
Property 'b' does not exist on type 'Test2'.
```

### 🙂 Expected behavior

`test2.a` and `test2.b` should exist.

**Comment by fatcerberus** [comment]
I think the problem here is that `Parent["test"]` is actually `Test | undefined`, not just `Test`, and `Omit` is not distributive.

**Comment by zqtay** [comment]
> I think the problem here is that `Parent["test"]` is actually `Test | undefined`, not just `Test`, and `Omit` is not distributive.

Thank you for the hint, seems like `NonNullable<Parent["test"]>` works.

I shall close this issue.

**Comment by zqtay** [comment]
For future reference:
[Playground](https://www.typescriptlang.org/play?ssl=31&ssc=8&pln=1&pc=1#code/C4TwDgpgBAKhDOwoF4oG8BQUoEMBcUiATgJYB2A5gNxZQBGA-AcedbQMZOHCmU0C+GDKEhQACjiIQySVJmzAEwLnEQChI6DAD2AeQC2JWeg5cWlDIIwB6a1ANGoYItrBQARO3dQAZi-1QmrBKwuBaSgCMKPaGwAA8qsAANFAA1hAg2j6werEAfDZ2DkjOrh7svv5QADba2qkArm5BElIyANruiojuALpQJAB0EIOBYcGIUAA+UA1kACYQPuQQ86GiiQBM0cVxrdLAnd3AfSnpmdk6xQW2MY6lbp7eftoBZNpkALRkDdXVOHRqtBavUmmNRPsOl0lH0BsNRkFEutwogAMw7WJxAByHyxv3+gIge0kByOMN6eTOGSyOWuQnYH0mxyicnwHncKToBHc7n4uHgE2AEWEkUGOBFiAigzohXEJKhx1h7BwZHo0Do2mAAAtBVBtERZgslis1gyyEylNtWdyOfQbXycAKthLgJsxS63TKzRa0dE0GyeZz7fzBaiXaj3ccI3QgA)

```ts
type Test = {
  a: string;
  b?: string;
  c?: string;
}

type Parent = {
  test?: Test;
}

type ToOmit = {
  c?: string
}

// Omit prop "c" from type Test
type Test1 = Omit<Test, keyof ToOmit>
// Omit prop "c from lookup type Parent["test"] i.e. type Test | undefined
type Test2 = Omit<Parent["test"], keyof ToOmit>
// Omit prop "c" from non-nullable lookup type Parent["test"] i.e. type Test
type Test3 = Omit<NonNullable<Parent["test"]>, keyof ToOmit>

const test1 = {a: "", b: ""} as Test1
test1.a
test1.b

// Syntax error
// Parent["test"] can be both Test or undefined
const test2 = {a: "", b: ""} as Test2
test2.a
test2.b

const test3 = {a: "", b: ""} as Test3
test3.a
test3.b
```

**Comment by fatcerberus** [comment]
Just for future reference (so you don't confuse anyone), there is no syntax error here.  A syntax error would mean the code can't be parsed at all, like a missing brace or a keyword in the wrong place.  This is just a type error.
