### ISSUE TITLE
The `export default interface` is allowed with `verbatimModuleSyntax` enabled 

### ISSUE THREAD

**Issue by ueokande** [microsoft/TypeScript#57518]
### 🔎 Search Terms

- verbatimModuleSyntax
- export default interface

### 🕗 Version & Regression Information

- I can reproduce on v5.0.4 and the nightly version.

### ⏯ Playground Link

https://www.typescriptlang.org/play?target=99&noImplicitReturns=false&alwaysStrict=false&noImplicitThis=false&strictPropertyInitialization=false&strictBindCallApply=false&strictFunctionTypes=false&strictNullChecks=false&noImplicitAny=false&ts=5.5.0-dev.20240224&esModuleInterop=false&declaration=false&jsx=0&verbatimModuleSyntax=true&allowSyntheticDefaultImports=false#code/KYDwDg9gTgLgBAE2AMwIYFcA28CWA7GYKNAY2DgEk4BvAXyA

### 💻 Code

```ts
export default interface I {}
```

### 🙁 Actual behavior

The compiler allows `export default interface I {}` with `verbatimModuleSyntax` enabled.

### 🙂 Expected behavior

When we try to export an interface separately with the definition and `export default`  syntax, the `tsc` outputs an error.

```ts
interface I {}
export default I
```

```
An 'export default' must reference a value when 'verbatimModuleSyntax' is enabled, but 'I' only refers to a type.
```

We can export an interface with `export default interface I {...}` even if the exported name does not reference a value, it references an interface.  I have no idea whether the tsc should output an error in that case since I cannot found such case in [the test](https://github.com/microsoft/TypeScript/blob/v5.3.3/tests/baselines/reference/verbatimModuleSyntaxNoElisionESM.js).    I think it can either be an error or needs to update the error message.

**Comment by whzx5byb** [comment]
Related: https://github.com/microsoft/TypeScript/issues/41409

**Comment by ueokande** [comment]
I'm not sure.  But by the error message, I guess, the compiler expects that the exported symbol is a value.  I think the tsc should output an error if we could use `export default type`.

**Comment by ajmas** [comment]
It is not clear in that case what the 'correct' way of dealing with this is?

If I follow a 'one interface declaration' by file approach:

```ts
interface IMyInterface { 
  // interface props
}
```

Then none of these work:

```ts
export default IMyInterface;
export IMyInterface;
export { IMyInterface };
export default type IMediaItem;
```

I feel like I am forced to use the `verbatimModuleSyntax`, simply because there isn't a clear 'correct' solution. At least the TS error 1284, doesn't provide sufficient clues.

**Comment by andrewbranch** [comment]
```ts
export default interface IMyInterface {
  // interface props
}
```

and

```ts
interface IMyInterface {
  // interface props
}
export type { IMyInterface as default };
```

are two verbatimModuleSyntax-compatible ways of default-exporting an interface.

**Comment by rauschma** [comment]
Given that this works:

```ts
export default interface Intf {}
```

Shouldn’t either one of the following work too? Why should interfaces get special syntactic treatment?

```ts
export default type MyType = {};
export default type SomeOtherType;
```

**Comment by andrewbranch** [comment]
I’m guessing because `interface` is a reserved word in ECMAScript whereas `type` is not. Both of those constructions would need ASI restrictions:

```ts
export default type
MyType = {};

export default type
SomeOtherType;
```
