### ISSUE TITLE
Type narrowing fails to understand that a variable is always assigned

### ISSUE THREAD

**Issue by ljharb** [microsoft/TypeScript#57516]
### 🕗 Version & Regression Information

on `next`

### ⏯ Playground Link

https://tsplay.dev/WGb4Vm

### 💻 Code

```ts
function f(x: { a: '1' } | { a: '2' }): string {
	let foo: string;

	if (x.a === '1') {
		foo = 'one';
	} else if (x.a === '2') {
		foo = 'two';
	}

	return foo;
}
```

### 🙁 Actual behavior

`return foo` errors with `Variable 'foo' is used before being assigned.(2454)`.

### 🙂 Expected behavior

Given that the type of `x` is known, and the if/else if covers both branches, if i put `else { }` i'd expect TS to complain somehow that the else block is unreachable - and since `foo` is assigned in every possible code branch as far as TS is aware, i would expect no error.

I recognize that the runtime value might not conform to the type, but doesn't TS assume it does, meaning that it shouldn't error here?

**Comment by ljharb** [comment]
Interesting, ok - so in order to silence the error without an override comment, i'd have to add an `else` that throws or assigns?

**Comment by RyanCavanaugh** [comment]
Correct

**Comment by ljharb** [comment]
ok, thanks for confirming
