### ISSUE TITLE
Dangerous calls allowed by TS: class generic type, when `unknown`, should be treated as `never` in the class methods/callback parameters

### ISSUE THREAD

**Issue by denis-migdal** [microsoft/TypeScript#57519]
### 🔎 Search Terms

unknown never generic type methods

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=5.5.0-dev.20240224&ssl=32&ssc=2&pln=1&pc=1#code/PTAEEMBtIewdwM6gCbgHYHMCmAnGBXJAYykgQCgBvc0W0IycBJADQB4AVAPlGrv-qkARuCIBrABQAXAFygOASl4BfGnVVraRGGgRTQADyGgAvKDRY4odkJgxIWdFwkKA3OXIBIbbv0G57PhoYmjwaDxmRq6gIKAwYl4GAHQk0CLiEgDMACxuMWComLgECEnkqrEkaADk+kwIAJYYaKANAGaCaaIJfHQM9dacPNSe3sLdAIRy0nKKpjwAbjANyF4a-D56hsZmFlY2dg5OLu7eOlv+g0EhYRHb0bGhCZ7JqZDpkjl5sYXYeITlcixAAOeGBMAQUComnojGYg24vBhG3GGVk8lAWAMUiwaGQSGuoTgLQA-OYsAtcKBZkpKKp+Os+uc-Dtyfs2LZ7I5wicPGdfIYAmxCbdTPd8nFnq9UZ9cg8wLg8DhQBIMHZkApykA)

### 💻 Code

```ts
// allows dangerous calls
{
    class X<T> {
        callback(t: T) {}
    }

    const xb = new X<boolean>();

	const x: X<unknown> = xb; // ok
	x.callback(34); // dangerous.
}
// can't assign if callback
{
    class X<T> {
		callback!: (t: T) => void
	}

    const xb = new X<boolean>();
	const x: X<unknown> = xb; // nok
	x.callback(34); // dangerous
}
// proposal
{
    class X<T> {
        callback(t: T extends unknown ? never : T) {}
    }

    const xb = new X<boolean>();

	const x: X<unknown> = xb; // ok
	x.callback(34); // error (good)
}
```

### 🙁 Actual behavior

When a class generic type is unknown, if used as parameters in a method/callback, will authorize dangerous calls :
```ts
(x as X<unknown>).callback(34); // we don't know the generic type of x so we should assume it is unsafe to call this method.
```

Also, due to that, if the class has a callback, we can't assign `X<...>` to `X<unknown>`.

### 🙂 Expected behavior

TS should assume the method parameter type is `never` to prevent its call, until the user has asserted the class real type.

```ts
// proposal
{
    class X<T> {
        callback(t: T extends unknown ? never : T) {}
    }

    const xb = new X<boolean>();

	const x: X<unknown> = xb; // ok
	x.callback(34); // error (good)
}
```

### Additional information about the issue

This would also enable to use `unknown` instead of `any` in some cases :

```ts
// use unknown instead of any to not trigger LINT warning.
function foo<T extends Record<string, X<unknown>>>() {

}
```
Current workaround would be :
```ts
function foo<T extends Record<string, X<U>>, U>() {

}
```

**Comment by denis-migdal** [comment]
> This is working as intended, because method parameters are bivariant. That's why the "callback" version does result in an error. You can find more information here: https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

Urg, that's so dirty.

Surely, there are better ways to proceed.
E.g. only authorizing such affectations when the target is fully read-only to prevent any issues (e.g. `readonly Animal []` for an array) , otherwise forcing an explicit cast with "as".


On another note, maybe we'd need a way to indicate an unknown generic type parameter as opposed to an `unknown` type, e.g. :
```ts
Array<Unknown> // I don't know its parameters, so I should be able to call methods/callbacks depending on the type parameter.
Array<unknown> // An array which elements are of type unknown
```

**Comment by MartinJohns** [comment]
> fully read-only to prevent any issues (e.g. `readonly Animal []` for an array)

Read-only types are implicitly compatible with the writable versions, so this wouldn't work. `{ readonly v: number }` can be passed to `{ v: number }` without issues. The `readonly` only applies to modifications via that interface. And there's no way to represent immutable types in TypeScript.

> On another note, maybe we'd need a way to indicate an unknown generic type parameter as opposed to an `unknown` type, e.g. :

That would essentially be `never`.

**Comment by denis-migdal** [comment]
> `{ readonly v: number }` can be passed to `{ v: number }` without issues. The `readonly` only applies to modifications via that interface.

WTF. Why ???
That's crazy.

At least requiring an explicit cast, doing it implicitly is just dirty, really dirty.

Though,
```ts
let a = {} as readonly number[];
let b: number[] = a;
```
does raise an error, so there are hopes.

> Read-only types are implicitly compatible with the writable versions, so this wouldn't work.

After thinking about it, it should be in fact "without methods whose parameters depends on the generic type".

Maybe to have a way to explicitly state we can accept super type of `T`, to allow things like:
```ts
class Base {}
class X extends Base {
    foo(){}
}

let a = new Array<X>();
let b = new Base();
a.find( b );
```


> And there's no way to represent immutable types in TypeScript.

Isn't it a design choice ?


> edit: this issue is well known and has existed for quite a while. If there would be a practical solution the team would surely have implemented it already.

Well, it is in other languages.
It feels like there were at some point one bad decision in TS design, that locked TS in this state as changing it would break everything.


> That would essentially be `never`.

Nope. `Array<Unknown>.pop();` would be `unknown`, not `never`. In parameters it'd be `never` (to prevent calls), and in return values `unknown`.

With `never` you also can't write:
```ts
function foo<T extends Record<string, never>>(t: T) {
    return t;
}

foo({"ok": 3});
```

**Comment by Andarist** [comment]
> does raise an error, so there are hopes

that’s not because of a readonly modifier anywhere but rather because mutable arrays have more methods in TS (like push, pop, etc). So its about the target side requiring more properties than the source has - not about per property modifiers difference

**Comment by denis-migdal** [comment]
> So its about the target side requiring more properties than the source has - not about per property modifiers difference

Indeed.

Still, I don't understand why TS isn't doing such very basic check.
We can very easily implement our own system, and not much needs to be added to TS to make it cleaner and more generic:

```ts
const RW = Symbol("");

class X {
    private [RW] = true;

    foo_ro() {}
    faa_rw(){}
}

type RO<T> = {
    [K in keyof Omit<T, typeof RW> as K extends `${infer _X}_ro` ? K : never ]: T[K]
}

let x: RO<X> = new X();
x.foo_ro();
x.faa_rw();
let y: X = x;
```

or

```ts
const AsRO = Symbol("");

abstract class _RO {
    abstract [AsRO]: _RO;
}

class XRO extends _RO {

    faa_ro() {}

    get [AsRO](): XRO { return this }
}


class X extends XRO {

    foo_rw() {}
}


type RO<T extends _RO> = T[typeof AsRO];

let x: RO<X> = new X();
x.faa_ro();
x.foo_rw();
let y: X = x;
```

**Comment by MartinJohns** [comment]
> Still, I don't understand why TS isn't doing such very basic check.

Reasons are provided in the issues. Just have to search for them properly and read through them. You may also want to join the TypeScript Discord.

In general:
- resources are limited.
- priorities differ.
- trade-offs are being made.
- TypeScript is not designed or aims to have a fully sound type system.

**Comment by fatcerberus** [comment]
Why are methods bivariant?  See https://github.com/microsoft/TypeScript/pull/18654, where `strictFunctionTypes` was implemented:

> The stricter checking applies to all function types, except those originating in method or construcor declarations. Methods are excluded specifically to ensure generic classes and interfaces (such as `Array<T>`) continue to mostly relate covariantly. The impact of strictly checking methods would be a much bigger breaking change as a large number of generic types would become invariant (even so, we may continue to explore this stricter mode).

**Comment by denis-migdal** [comment]
> You may also want to join the TypeScript Discord.

Maybe I'll do it next time.


>     * resources are limited.

Is a flag check really what is the most resources intensive in TS ?

>     * priorities differ.

I understand, but doing things in half will just result into things blowing in your hand.
If a `readonly` is introduced, it is expected that it would have at least the very minimal and basic features.

If I declare something `readonly`, I don't want it to explode just because of a bad affectation.

>     * trade-offs are being made.

Adding a `if` vs things blowing up ?
Sorry, I'm a little salty tonight.
 
>     * TypeScript is not designed or aims to have a fully sound type system.

Yeah, I'm starting to understand it...
But there are fully sound in one side, and messed up in the other.
I kind of understand some inconsistencies, but the last things are messed up.


More than a week, lost because of issues and bugs (because yes, even if it is intentional, theses are bugs) known for 5 to almost 10 years... I think I earned the right to be a little salty tonight.

**Comment by MartinJohns** [comment]
> Is a flag check really what is the most resources intensive in TS ?

I'm referring to the team. Someone has to implement and maintain the code.

> If a `readonly` is introduced, it is expected that it would have at least the very minimal and basic features.

It does have very a minimal and basic feature: via that type you can't modify the property. That's what most people wanted.

> Adding a `if` vs things blowing up ?

Trade-offs in terms of language design and complexity, as well as priority of features to implement.

> Sorry, I'm a little salty tonight.

You should really abstain from public discussions then. It's not the right place to vent your salt.

> even if it is intentional, theses are bugs

No, they're not. Undesired behavior, sure. Bug, no.

**Comment by denis-migdal** [comment]
I was ready about `in out` annotations in the announcement of 4.7 (couldn't find them in the doc when searching on Google).

The initial issue is in fact solved by using `class X<in T>` in the declaration of `X`.
Could be nice to have a flag to get a warning to remember us to use `in` and `out` inside generics (I don't think there are cases when it is neither `in` nor `out`)...


Also, isn't `Array<T>` ill defined ? Shouldn't it be `Array<in out T>` ?


> I'm referring to the team. Someone has to implement and maintain the code.

> Trade-offs in terms of language design and complexity, as well as priority of features to implement.

Ok, this I can understand.

**Comment by fatcerberus** [comment]
No, `Array<in out T>` would make it invariant.  `Array` is intentionally covariant because making `Dog[]` not be assignable to `Animal[]` would break a lot of real-world code.  The unsoundness there is deliberate.

**Comment by denis-migdal** [comment]
> `Array` is intentionally covariant because making `Dog[]` not be assignable to `Animal[]` would break a lot of real-world code.

A code that would make that is already kind of broken.
Only `Dog[] -> readonly Animal[]`  (`ReadonlyArray<out T>`) should be correct, no ?

> The unsoundness there is deliberate.

Why allowing such a dangerous unsoundness in TS, i.e. in scripts where we want some protections, instead of simply allowing to skip some tests in some files when needed ? Outside of theses files, we'd just need an explicit cast if necessary.

**Comment by RyanCavanaugh** [comment]
@denis-migdal I'm just going to ask that you *please* not learn TypeScript's various ins and outs via filing bugs on the issue tracker. If you have some behavior that also repros in 3.3, it's 99.99% certain that it's not a longstanding bug that's just been overlooked for 5+ years.

**Comment by denis-migdal** [comment]
> @denis-migdal I'm just going to ask that you _please_ not learn TypeScript's various ins and outs via filing bugs on the issue tracker.

I'm sorry for that, but you'll have to admit that TS has *LOT* of undocumented unsoundness, at a point you really should have a whole "Designs choices and intentional unsoundness" chapter in the documentation...

Some features are even undocumented, like `in` and `out` annotations, only talked about in the 4.7 announcement.
With such feature, it should either (from best to worst) :
- TS deduces the `in`/`out` by itself and explicit annotation is used to change this behavior.
- every generic be `in out` by default.
- every generic requiring explicit `in`/`out` annotations

But instead of introducing some compiler flag(s), TS introduced unsoundness instead and again...
This is a living hell of undesirable undocumented behavior... just to dirty-solve some specific cases, when more control on the compiler flags would do the trick...


> If you have some behavior that also repros in 3.3, it's 99.99% certain that it's not a longstanding bug that's just been overlooked for 5+ years.

If if walk like a bug, and quack like a bug, it is very likely a bug. You can call intentional bugs "intentional unsoundness", it still remains a bug (more specifically a flow or a fault in the design).

How many big issues are still open and has been overlooked for 5+ years, while having lot of duplicates ?

**Comment by fatcerberus** [comment]
> TS deduces the in/out by itself and explicit annotation is used to change this behavior.

This is, in fact, exactly what happens.  The annotations were added later because TS sometimes gets it wrong.

> If if walk like a bug, and quack like a bug, it is very likely a bug. You can call intentional bugs "intentional unsoundness", it still remains a bug (more specifically a flow or a fault in the design).

It’s not a fault in the design if soundness was never a design goal in the first place (and this fact is documented).  You may not *like* it, but that’s the direction the designers chose and if that’s unsuitable for your use, you’ll need to look for a different tool.

**Comment by ritschwumm** [comment]
i wish `strictMethodTypes` were a thing. for the time being, my advice is to avoid classes as much as possible. most of the time, type aliases and function suffice and even if it's a bit more work (or less performance) it's imho well worth the additional help the compiler can give you.

**Comment by Andarist** [comment]
> class X<T> { // should be "in"...

This is a classic invariant case - "represented" as `in out` in TS. This works very much as expected and is correct. If you are after soundness you should, at the very least, be happy about this one.

> If only this different tool existed...

It's an open market. You can create an alternative or stop paying for this piece of software that doesn't satisfy your needs.

**Comment by denis-migdal** [comment]
> This is a classic invariant case - "represented" as `in out` in TS. This works very much as expected and is correct. If you are after soundness you should, at the very least, be happy about this one.

? I do not think TS gets the annotations right in theses cases:

```ts
	class X<T> {
		#t!: T;
	
		callback(t: T) {
			this.#t = t;
		}
	}

	const _a: X<unknown> = {} as X<boolean> // authorized
```
```ts
	class X<in out T> {
		#t!: T;
	
		callback(t: T) {
			this.#t = t;
		}
	}

	const _a: X<unknown> = {} as X<boolean> // forbidden (ok)
```
Without the attribute:
```ts
{
	class X<T> { // should be "in"...
	
		callback(t: T) {}
	}

	const _a: X<unknown> = {} as X<boolean> // authorized
}
```
```ts
{
	class X<in T> { // should be "in"...
	
		callback(t: T) {}
	}

	const _a: X<unknown> = {} as X<boolean> // forbidden
}
```

**Comment by Andarist** [comment]
> ? I do not think TS gets the annotations right in these cases:

Ah, right. I've misinterpreted my quick tests. This has already been mentioned in the thread - but well, methods are bivariant in TS. You might not agree with this decision but it's here to stay. You can always create a linting rule to avoid the method syntax altogether. This behaves like you expect it to:
```ts
class X<T> {
  t!: T;

  callback = (t: T) => {
    this.t = t;
  };
}

const _a: X<unknown> = {} as X<boolean>; // forbidden (ok)
```

**Comment by RyanCavanaugh** [comment]
It's not like we're not aware of the downsides of this. If it were easy and simple to fix, we would have done it already.

**Comment by fatcerberus** [comment]
> And this decision is an example of a design flaw:
> This produces unsound and unsafe behaviors (cf example), while simple alternatives (some I presented here) would easily solve issues...

As I said before, it's not a design flaw because *soundness and correctness are not design constraints*.

From https://github.com/microsoft/TypeScript/wiki/TypeScript-Design-Goals under **Non-Goals**:

> 3. [Do not try to] Apply a sound or "provably correct" type system. Instead, strike a balance between correctness and productivity.

**Comment by denis-migdal** [comment]
> It's not like we're not aware of the downsides of this. If it were easy and simple to fix, we would have done it already.

Why would e.g. an `--require-explicit-generics-inout`  (set every generics `in out` by default)  or a `--require-explicit-ro-casts` option be hard ?
You use it if you need for security, and don't if you need compatibility.
