### ISSUE TITLE
Problem about this operator

### ISSUE THREAD

**Issue by mydiscogr** [Microsoft/TypeScript#5752]
Hi I have a problem with traspiling class and mixing it with existing es5 code to better esplain the issue I've created a repo. the problem is to use in this simple function a method of class generated via typescript

```ts
function setObjVal(fn,val){
    fn(val);
}
```
repo:
https://github.com/mydiscogr/jscontextproblem

There's is a workaround for this problem thanks

**Comment by SaschaNaz** [comment]
You are passing a prototype member function which will only work when called by the prototype chain. This will always work, BTW.

```
setObjVal((val) => obj.setVar1(val), val);
```

**Comment by RyanCavanaugh** [comment]
It sounds like you're proposing that we emit all classes as constructor functions which re-allocate a closure per method. This isn't a good idea, both in terms of ES6 compat and in terms of runtime performance (one closure per method __per instance__ is *much* worse than one closure per method). But if this is actually a question or something (I can't tell), we'll need more information to answer it.

**Comment by mydiscogr** [comment]
prequel.
"I have wrote time ago one app in node so i would integrate with typescript"


Sorry, I would better explain the problem.
I have a simple ES5 function:

function setObjVal(fn,param){
  fn(param);
}

well I see only, that if ,fn is a method, and the object method use this operator, 
in my many way to declare in es5 an object don't work.
I've found that only in one way works, with closure, as below.

module.exports = (function(){

    var self = {

        var1: "unmod",
        setVar1: function(val){

            self.var1 = val;
        }   
    }

    return self;

})();

So I dunno if closure can cause a problem (why?? is bad??), 
or memory wasting of memory, or cause memory lacks,
but my problem is more simple, I would like to create an object in safe way, just to
avoid critical bugs (you know the difficult to find bug sometimes).

So I hope that if you declare a class in typescript your way to generate a class
should (must?) be safe(so I think). Because this is a transpiler, and can be a really pain to find
a "bug" of code not wrote by you...(think about c++ compiler, nobody is interested as create asm src..., we assume that code generated is correct) 

So wrapping up. I'm not asking to generate and object as I wrote in my repo, 
I'm not a great js programmer
but I ask to taking care of this problem.

I hope to make more clear my question.


thanks for attention.

**Comment by mydiscogr** [comment]
No other comment? .. a solution.

**Comment by mhegazy** [comment]
Class emit in TypeScript is meant to be inline with the ES6 spec. this allows you to interoperate your classes with other ES6 classes and vice versa. TS will place methods on your prototype, and will support inheritance as well. 

You can still port your implementation to TS by giving your function a type annotation as:

```ts
// type of instance of MyClass
interface MyClass {
    var1: string;
    setVar1(val: string): void;
}

// constructor function of MyClass
var MyClass: { new (): MyClass; } = <any>function () {
    var self = {
        var1: "unmod",
        setVar1: function (val) {
            self.var1 = val;
        }
    };
    return self;
};

// Make it the export of my module
export = MyClass;
})();
```
