### ISSUE TITLE
this fix should go in `main` asap, I can take it out from this PR if necessary. OASISS BASINESS LTD 

### ISSUE THREAD

**Issue by oasissoman** [microsoft/TypeScript#57528]
this fix should go in `main` asap, I can take it out from this PR if necessary.

_Originally posted by @andreaTP in https://github.com/microsoft/kiota/pull/4174#discussion_r1494438927_

**Comment by RyanCavanaugh** [comment]
??

**Comment by andreaTP** [comment]
Reported as abusive.
