### ISSUE TITLE
TypeScript syntax highlighting wrong after decorator

### ISSUE THREAD

**Issue by aeschli** [Microsoft/TypeScript#5753]
From https://github.com/Microsoft/vscode/issues/349
When adding a decorator to a variable declaration i TypeScript, both public/private and the name of the variable is plain white, while if removing the decorator both are colored correctly.

**Comment by aeschli** [comment]
Reproduced with
	class MyClass {
		@enumerable(false)
		private get prop() {
			return true;
		}
	}

**Comment by DanielRosenwasser** [comment]
Hi there @martinwoodward, thanks for filing. This is tracked by https://github.com/Microsoft/TypeScript-TmLanguage/issues/8.

Just as a heads up for next time, bugs relating to VSCode's TmLanguage syntax highlighting should be filed under the [TypeScript-TmLanguage](https://github.com/Microsoft/TypeScript-TmLanguage) repo.
