### ISSUE TITLE
Type predicates are not applied when the guard function is called with `fn.call`

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#57532]
### 🔎 Search Terms

- type predicate this call
- type guard this call

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about (n/a)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.3#code/GYVwdgxgLglg9mABDAzgORAWwEYFMBOAFAB4BciYWe+iAPoilPjGAOYCU5xyKFVBiAN4AoRGMT5cUEPiRQAngAdccYIm4BeLYgDklHAR0BuYQF9hwgCa4IAGwCGkxLanry+6nQZMWrEzDVCVAwDImJ2diFRcRcoRCh3fhoNdRNzAMQg9CSAOgh7W1tCcGtgFlxLABp1CKjxZ1cEvlDEFOITeoB6TrEAP0QAFSVcXUZmNi8PQx4KODj7FBQYVjB7bBd4uHjh3Sn8HRyzYSA

### 💻 Code

```ts
function isNumber(x: number | string): x is number {
    return typeof x === 'number';
}

declare let x: number | string;
if (isNumber(x)) {
    let t: number = x;
}
if (isNumber.call(undefined, x)) {
    let t: number = x;
    //  ~ Type 'string | number' is not assignable to type 'number'.
}
```

### 🙁 Actual behavior

The type of `x` only narrows when the predicate is called directly, not via `isNumber.call`.

### 🙂 Expected behavior

I'd expect the type of `x` to narrow in both conditionals.

### Additional information about the issue

I noticed this while investigating whether `this` parameters were relevant for #57465.

I can't imagine why you'd want to invoke a predicate this way, but I also don't see why it shouldn't work!

**Comment by Andarist** [comment]
I'd call this a current design limitation in inference. `CallableFunction.call` is a function like any other (without special support in the compiler). 

If you test this out `ReturnType<typeof isNumber>` you'll just get `boolean`. Return types of type predicates refer to bindings from their parameters list and I don't see how you'd correctly capture this variable information using current inference capabilities (it's different from inferring using a known position in the parameter list like in `(x: any) => x is infer R`)

**Comment by fatcerberus** [comment]
> `CallableFunction.call` is a function like any other (without special support in the compiler).

Is this true?  Then what does `strictBindCallApply` do?

**Comment by Andarist** [comment]
> Then what does strictBindCallApply do?

It makes the compiler to select `CallableFunction.call` over `Function.call` but that's about it. The actual definitions of those live in the lib files.
