### ISSUE TITLE
error: Property 'innnerHTML' does not exist on type 'Element'

### ISSUE THREAD

**Issue by am11** [Microsoft/TypeScript#5754]
I am getting this error with `v1.6.3` with the following code:

```typescript
document.querySelector('body>section.container').innerHTML  // error: TS2339
```

To remedy it, I had to explicitly cast it as `HTMLElement`:

```typescript
(<HTMLElement>document.querySelector('body>section.container')).innerHTML  // it works!
```

However, `innerHTML` is supported by `Element` interface:
https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML.

**Comment by mhegazy** [comment]
PRs are appreciated. here is how to send lib.d.ts PRs: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by lgolven** [comment]
I would to try to fix this bug, is it possible to assigned it to me ?
Thanks !

**Comment by mhegazy** [comment]
@lgolven feel free to send a PR for it.

**Comment by MartyIX** [comment]
I have added PR here: https://github.com/Microsoft/TSJS-lib-generator/pull/35

**Comment by MartyIX** [comment]
@mhegazy Is this a correct way to fix the problem?

**Comment by DanielRosenwasser** [comment]
Thanks @MartyIX! This will just need to be synced up with the repo.

**Comment by duanyao** [comment]
Well, `Element.outerHTML` is still missing :(

**Comment by RyanCavanaugh** [comment]
@duanyao Be the pull request you want to see in the world :wink:
