### ISSUE TITLE
Sort matching types to the top when suggesting types

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#57547]
**Steps:**
* empty profile to ensure this is not some setting I changed
* `git clone https://github.com/bpasero/ticino-playground.git`
* open `Features.ts`
* uncomment the commented out `toString` in line `27`
* trigger suggest in between the `()`

=> the list seems to be sorted in a way that does not suggest the most matching type at the position first

I think it would be great if the most matching types are sorted to the top and then I can just accept them.

![Image](https://github.com/microsoft/vscode/assets/900690/feae19a4-63df-4057-a994-7f98ff2107d0)

**Comment by RyanCavanaugh** [comment]
It's not possible to do this in a performant way

**Comment by mjbvz** [comment]
I believe we do this with enums in some cases:

![Image](https://github.com/microsoft/TypeScript/assets/12821956/42d63efd-f087-4206-a943-761046ccf25d)

As we're sensitive to performance of completions, could we limit this to exact type matches or even just primitives like `boolean` or `string`?

**Comment by RyanCavanaugh** [comment]
It's not information that we're currently computing -- the global completion list doesn't compute the types of things (that comes in through a completion entry details request as the user goes through them). We need to be very very careful what we do with a list of > 1,000 or more items here.

I'm also not sold on the UX upside here either. If you need a string or a boolean, that information could be coming from anywhere (a comparsion, a toString call, etc); unless the user *realizes* that the sort order is changing to try to help, it'll just look scrambled.

Is the precedent in some other LS for this?

**Comment by jrieken** [comment]
> Is the precedent in some other LS for this?

Pretty sure Eclipse and Jetbrains products have this for Java

**Comment by bpasero** [comment]
@RyanCavanaugh quite sure VS has this for C# / IntelliCode:

![Screenshot 2024-02-26 at 20 46 41](https://github.com/microsoft/TypeScript/assets/900690/78e1df4d-044b-44d1-887f-d1c41404e64d)

**Comment by RyanCavanaugh** [comment]
That's IntelliCode; TS already has IntelliCode

**Comment by bpasero** [comment]
@RyanCavanaugh if so, where is the option to promote likely items to the top in TS?

**Comment by RyanCavanaugh** [comment]
<img width="620" alt="image" src="https://github.com/microsoft/TypeScript/assets/6685088/4e15c183-666d-429d-9507-de3cf3cf44e3">

**Comment by jakebailey** [comment]
FWIW Go's LS (gopls) does this, but that's a language with very different design and performance characteristics that make type directed completions cheap.

They also (via LSP) can return partial lists that update as the user types, so can quickly return matching locals and limit the actual request time for things like auto imports. Which may not even help us if it's not cheap to ask every available name if it could be a candidate.
