### ISSUE TITLE
@types are loaded into the global scope when they shouldn't

### ISSUE THREAD

**Issue by josemigallas** [microsoft/TypeScript#57555]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **1.86.2** 
- OS Version: **macOS 14.3.1**

I am desperate to know whether this is a bug or I am doing something wrong. The web project uses 2 versions of jquery:
-  `1.8.2` is installed via cdn and exported as `window.$`. Typings for this are defined manually in a `app/javascript/src/Types/globals.d.ts`.
- `3.7.0` is installed from node_modules and imported via `import $ from "jquery"` so that it's only available there, not globally, not from window. Types are defined by package`@types/jquery`.

I have the following in the tsconfig.json:
```json
{
  "compilerOptions": {
    [...]
    "types": [],
    "typeRoots": ["app/javascript/src/Types"],
  },
  "typeAcquisition": {
    "exclude": [
      "jquery"
    ]
  },
  "include": [
    "app/javascript",
    "spec/javascripts"
  ],
  "exclude": [
  ]
}
```

And this is vscode settings:
```json
    // typescript
    "typescript.preferences.importModuleSpecifier": "non-relative",
    "typescript.tsdk": "porta/node_modules/typescript/lib",
    "typescript.disableAutomaticTypeAcquisition": true,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "typescript.tsserver.log": "verbose",
```

In the aforementioned `globals.d.ts` I have defined a specific prop that is only available in our jquery `1.8.2`, the one in window:
```ts
import type { JQueryStatic as JQueryStaticV1 } from 'Types/jquery/v1'

declare global {
  const $: JQueryStaticV1 & { foo: string }

  // [...]
}
```

And the .ts file:
```ts
document.addEventListener('DOMContentLoaded', () => {
  console.log($.foo)
}
```

Compiles OK and doesn't throw any TS error. However, vscode will complain:
![Screenshot 2024-02-22 at 14 39 56](https://github.com/microsoft/vscode/assets/11672286/ceb796be-f740-4936-bfab-e19d7418fbbe)

EDIT:
Additional note just to confirm: when "going to definition" on `$` from `$.foo` it goes go `node_modules/@types/jquery/misc.d.ts`.

**Comment by RyanCavanaugh** [comment]
We'd really need a concrete repo to investigate

One sanity check: Does invoking the "go to project configuration" verb in that file take you to the expected tsconfig?

**Comment by josemigallas** [comment]
> We'd really need a concrete repo to investigate

This is the repo and branch: https://github.com/3scale/porta/pull/3700 if you don't mind it being a full project.

This problem should be reproducible in any `app/**/*.ts file`, for instance `app/javascript/packs/bulk_operations.ts`. Typing `window.$.` gives correct intellisense suggestions:
![Screenshot 2024-02-27 at 09 16 44](https://github.com/microsoft/TypeScript/assets/11672286/fd197565-7272-4bfc-b1c7-4d953301ba41)

,but `$.` not:

Here's the error from `globals.d.ts`. AFAIK it shouldn't happen since @types/jquery should not be loaded.
![Screenshot 2024-02-27 at 09 10 46](https://github.com/microsoft/TypeScript/assets/11672286/e757a432-d23c-411f-983d-561f1b39df17)

**Comment by josemigallas** [comment]
> One sanity check: Does invoking the "go to project configuration" verb in that file take you to the expected tsconfig?

Yes, it does.

**Comment by RyanCavanaugh** [comment]
jquery isn't being loaded via `types` AFAICT. 

Running `tsc --explainFiles`, I see that you have
```ts
import jQueryUI from 'jquery'
```
in `app/javascript/packs/cms.ts`
which is causing jquery to get resolved via module resolution. If a module gets found via module resolution, the `typeRoots` setting has no impact -- `types`-based resolution is only a fallback in the presence of module resolution failure.

It seems like you have your own jquery definition, so in this case I'd put `jquery.d.ts` with content `export { }`, and add a compiler `path` mapping for it
```json
    "paths":{
      "jquery": ["jquery.d.ts"]
    }
```

Seems to work
<img width="203" alt="image" src="https://github.com/microsoft/TypeScript/assets/6685088/c06337a5-5a97-4178-b870-b0ed3316e3a0">

**Comment by josemigallas** [comment]
`import X from 'jquery'` is used in multiple places so that jQuery 3.x is available. For the rest of files where jquery isn't imported, jQuery 1.x is available in the global scope.

I'm not sure that solution fits my problem because then the types I have defined exclusively for jQuery 3.x will wrongly be available from the global scope. Same problem but upside down.

The fact that this errors only show up in vs code makes me believe there's some kind of issue with the typescript extension. That or somehow Webpack + ts-loader is cleverer and does not mess up the compilation.

What I am thinking now is best is to add an eslint rule to forbid using `$` from the global scope... this way types are as expected. 🤷🏻‍♂️

**Comment by RyanCavanaugh** [comment]
Within a single project, you can only have one global scope. There's no support for different global scopes depending on which file you're in.

**Comment by josemigallas** [comment]
I see. Is there are way to "ban" a specific global variable? What I didn't get is why Typescript or vs code assumes $ is globally available.. but I guess it's the typings' fault, isn't it? 

These 2 lines are "injecting"  `$` and `jQuery` into the global scope:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5dddaaa384aaba8ba23840fb8132f2f9f800c9ef/types/jquery/misc.d.ts#L7336-L7337

But they're assuming that I am doing: `window.$ = $` which I am not.

**Comment by RyanCavanaugh** [comment]
No, you'd need to use a lint rule or such.

**Comment by josemigallas** [comment]
Thanks @RyanCavanaugh
