### ISSUE TITLE
Static member added by class decorator is not emitted in types

### ISSUE THREAD

**Issue by yoursunny** [microsoft/TypeScript#57558]
### 🔎 Search Terms

class decorator, static member

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about decorators

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240226#code/GYVwdgxgLglg9mABAQwCaoPrADwBUB8AFFMgE4DmAplAFyJiUDuhAlALz64A0i0AHnWRgAnizqEGzdpxaIAZIgDeiYONkd6IALYAjSqUQBfJQChEiUtRCkkAeR0ArStAB0yAM7uY5MMTJUoHmVVRFYOAEYjFhNDExMAATRMYBMIABsPd0QAZVNY1IR3ODTKFzS4ckJsl2BWFgBuEyA

### 💻 Code

```ts
function add_f<T>(target: new()=>T, ctx: any): (new()=>T) & { f: () => number } {
  return Object.assign(target, { f: ()=>1 })
}

@add_f
class S {
}

console.log(S.f());
```

### 🙁 Actual behavior

**.d.ts** emits:

```ts
declare class S {
}
```

Errors include:

```text
Property 'f' does not exist on type 'typeof S'.
```

Runtime behavior is correct: it prints `1`.

### 🙂 Expected behavior

**.d.ts** emits:

```ts
declare class S {
  static f(): number;
}
```

No error.

**Comment by fatcerberus** [comment]
Looks like https://github.com/microsoft/TypeScript/issues/4881
