### ISSUE TITLE
Object.create with typescript with namespace

### ISSUE THREAD

**Issue by anuraj** [Microsoft/TypeScript#5755]
I am using object.create to create objects dynamically. I have added one namespace in the typescript file like this. - dotnetthoughts.net.javascript with a class helloworld. It generates a file like this
```javascript
var dotnetthoughts;
(function (dotnetthoughts) {
    var net;
    (function (net) {
        var javascript;
        (function (javascript) {
            var HelloWorld = (function () {
                function HelloWorld() {
                }
                HelloWorld.prototype.print = function (message) {
                    console.log(message);
                };
                return HelloWorld;
            })();
            javascript.HelloWorld = HelloWorld;
        })(javascript = net.javascript || (net.javascript = {}));
    })(net = dotnetthoughts.net || (dotnetthoughts.net = {}));
})(dotnetthoughts || (dotnetthoughts = {}));
```
Now if I am trying to create an object with dotnetthoughts.net.javascript.HelloWorld it is failing.

How can I fix this issue?

Here is what I am doing - http://stackoverflow.com/questions/15338610/dynamically-loading-a-typescript-class-reflection-for-typescript

**Comment by mhegazy** [comment]
I am not sure i understand the question.. this code works for me.. if you add:
```js
var h = new dotnetthoughts.net.javascript.HelloWorld();
h.print("hi");
```
and run it using node:

> node file.js

i get:

> hi
