### ISSUE TITLE
Without native LSP support, it's very inconvenient to auto-complete CSS file paths during `import` when aliasing is involved.

### ISSUE THREAD

**Issue by nyngwang** [microsoft/TypeScript#57557]
### 🔍 Search Terms

"typescript-language-server", "CSS Modules", "intellisense", "auto-completion", "import", "ESM".

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Without native LSP support, it's very inconvenient to auto-complete CSS file paths during `import` when aliasing is involved. For example, it's common to utilize the options `compilerOptions.paths` of `tsconfig.json` for aliasing: (I removed irrelevant parts)

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "/*": [ "./public/*" ],
      "@/*": [ "./src/reactApp/*" ],
      "@components/*": [ "./src/reactApp/components/*" ],
      "@firebase/*": [ "./src/firebase/*" ]
    }
  }
}
```

And given that CSS Modules are still very popular with the help of bundlers like webpack, it's common to see this:

```js
import * as styles from '@shorthand/styles/some.css'

// can now use local-scoped class, e.g. `styles.menu`.
```

But currently, it seems that there is no convenient way to auto-complete the aliasing without native LSP support. Let me explain:

1. An editor knows how to auto-complete the "plain" file path of a CSS file. The file path itself is language-independent, so it's reasonable that an editor should support this out of the box (or by a bundled plugin).
2. An editor DOESN'T know how to auto-complete the file path of a CSS file, if `compilerOptions.paths` is set.
3. Path aliasing itself has no meaning without compiler/bundler support. We need a compiler/bundler to compile/transpile the path alias into the real file path.

Now it's complicated to achieve a simple target: After setting `compilerOptions.paths` of `tsconfig.json`, we still need to:

1. Find/Write a plugin to sync `compilerOptions.paths` and the settings of a bundler, e.g. `resolve.alias` of webpack.config.js. We already have one for webpack, even though it currently has some serious pending bugs: https://github.com/dividab/tsconfig-paths-webpack-plugin.
2. Find/Write a plugin to sync `compilerOptions.paths` and your editor settings to auto-complete aliasing. I haven't found a plugin for file path autocompletion for CSS files.

**But all the existing solutions for both 1. and 2. only work for TS/JS files**. I need support for those CSS files when `compilerOptions.paths` of `tsconfig.json` is set.

Thanks for your reading!

### 📃 Motivating Example

```js
import * as styles from '@shorthand/styles/some.css'
```

And `tsserver` will support auto-completion of `some.css` after `@shorthand` is typed.

### 💻 Use Cases

1. What do you want to use this for?

To support file path autocompletion of CSS Modules when path aliasing is involved, without the need of an extra plugin from the editor side.

2. What shortcomings exist with current approaches?

Currently, `tsserver` doesn't show any file path of CSS files for auto-completion upon `import`ing CSS files in TS/JS files.

3. What workarounds are you using in the meantime?

I extended an existing plugin for my specific editor to make it take `tsconfig.json` into consideration.

**Comment by fatcerberus** [comment]
Have you enabled `allowArbitraryExtensions` (https://www.typescriptlang.org/tsconfig#allowArbitraryExtensions)?  I don’t know if it matters here, but AFAIK you’re supposed to enable that whenever importing from non-JS files.

**Comment by nyngwang** [comment]
@fatcerberus Thanks for your advice. While it doesn't work, I use the keyword you provided and now I believe that my problem is not new at all and probably already have a third-party solution in the wild. I will investigate more and close this issue myself when necessary.

**Comment by fatcerberus** [comment]
> it doesn't work given that I'm not using VSCode and I haven't installed any plugin

Huh?  That’s a `tsconfig.json` option.

**Comment by nyngwang** [comment]
Yes, I know. I probably express it wrong but I meant settings it to `true` only doesn't help. It doesn't provide auto-completion and produce an error. I'm not using VSCode so I cannot just install some plugins to solve this problem that I believe might have been solved by people who using VSCode.
