### ISSUE TITLE
What is TypeScript Salsa?

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#5756]
I have noticed a few things with the [tag](https://github.com/Microsoft/TypeScript/labels/Salsa) and a mention of a [Salsa server](https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/364#issuecomment-144939687), [design meeting minutes](https://github.com/Microsoft/TypeScript/issues/5740) that mention it and that some things will only be available in Salsa, but I cannot seem to find any publicly available information that explains what it is.

Can anyone enlighten?

**Comment by billti** [comment]
It's a codename for this effort: https://github.com/Microsoft/TypeScript/issues/4789
