### ISSUE TITLE
`types` compiler option does not behave correctly when the compiler is ran in another directory path

### ISSUE THREAD

**Issue by costinsin** [microsoft/TypeScript#57562]
### 🔎 Search Terms

"types", "compilerOptions", "Cannot find type definition file for", "Entry point of type library", "another", "path", "type resolution", "typeRoots"

### 🕗 Version & Regression Information

- This is a crash happening in `typescript@5.3.3`

### ⏯ Playground Link

https://github.com/costinsin/typescript-types-option-bug

### 💻 Code

index.js
```js
// The directory path to the TS project 
const cwd = "target-ts-project"

// Reading the config file from `${cwd}/tsconfig.json`
const configFile = ts.readConfigFile(path.join(cwd, "tsconfig.json"), ts.sys.readFile);

// My fix is forcing the type roots to `node_modules/@types`
// if (configFile.config?.compilerOptions !== undefined) {
// 	configFile.config.compilerOptions.typeRoots = ["node_modules/@types"];
// }

// Parsing the config file with `cwd` as basePath
const config = ts.parseJsonConfigFileContent(configFile.config, ts.sys, cwd);

// Creating the program
const program = ts.createProgram({
	rootNames: config.fileNames,
	options: config.options,
});

// Showing the diagnostics
const diagnostics = ts.getPreEmitDiagnostics(program);
```

target-ts-project/tsconfig.json
```json
{
	"compilerOptions": {
		"target": "ES2020",
		"module": "ES2020",
		"moduleResolution": "node",
		"lib": [
			"es6",
			"dom"
		],
		"outDir": "build",
		"rootDir": ".",
		"strict": true,
		"noImplicitAny": true,
		"esModuleInterop": true,
		"resolveJsonModule": true,
		"allowJs": true,
		"types": [
			"react"
		]
	},
	"include": [
		"**/*"
	]
}
```

### 🙁 Actual behavior

I am type checking an external TS project using the `typescript` library. I have noticed that `types` compiler option is no longer working as intended as it always searches in the `./node_modules/@types` folder, instead of searching inside the `${tsconfig_folder}/node_modules/@types`.

I have attached you a demo repository. In order to see the problem run `node index.js` in the repository root.

You will see that a diagnostic is thrown `Cannot find type definition file for 'react'. The file is in the program because: Entry point of type library 'react' specified in compilerOptions`.

**Folder `react` is present in `target-ts-project/node_modules/@types`.**

If you change the `cwd` variable to `.` in `index.js`, then `cd target-ts-project`, then run `node ../index.js` you will see that the problem disappears. This made me think that types are searched based on the `process.cwd()` value, instead of `project_directory` value.

A temporary fix for me was writing the `typeRoots` field explicitly to point to `node_modules/@types` before parsing the `tsconfig.json` file.
```ts
if (configFile.config?.compilerOptions !== undefined) {
	configFile.config.compilerOptions.typeRoots = ["node_modules/@types"];
}
```

### 🙂 Expected behavior

Types should be searched in `${project_dir}/node_modules/@types`, instead of `${process.cwd()/node_modules/@types`.

**Comment by costinsin** [comment]
Thank you for you explanation!

I find the TypeScript Compiler API sometimes confusing, the naming of these 2 apparently similar, but actually different functions is not very clear.

For example, I have identified 6 functions that seem to have more or less the same purpose:
- `getParsedCommandLineOfConfigFile`
- `readConfigFile`
- `parseConfigFileTextToJson`
- `readJsonConfigFile`
- `parseJsonConfigFileContent`
- `parseJsonSourceFileConfigFileContent`

How should one choose which one to use? 🤔

 I will close this issue. Thank you again for helping me!

**Comment by RyanCavanaugh** [comment]
> I find the TypeScript Compiler API sometimes confusing, the naming of these 2 apparently similar, but actually different functions is not very clear.

You're correct to be confused and I really don't have any better guidance than to read the code of what they do (or experiment). It's a mess and I'm sorry you had to deal with it. We should try to improve the docs on them at least.
