### ISSUE TITLE
{} does not extend Record when Generic

### ISSUE THREAD

**Issue by Dinhero21** [microsoft/TypeScript#57561]
### 🔎 Search Terms

overly strict function generic record

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Structural Typing, Functions and Generics.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240226#code/PTAECcFMAdwewCYFcDGBLARgG0qA7mgC4AWoAhgHYCeJaFA5qCWYaJAB6GQUIDOovQuDqMAPqApIAthkjhQ43lRlwsbdihisKkAG5yAUISrRcAaUhVQAXlABrS3ABm5agYMgIMeMnTZcBCTkGLyqSFxYVpQ0xCJGJrgAamRYSLi20e5OSBQohGhwFOSgADwAKupcPPwWVAB8ABQAlABcoABKkChw4AjlADSgyamQdaAA3gag016ESOBF4wC+BisG3RSCoBhtnd29JbWDw2ljtstAA

### 💻 Code

```ts
// reproducible with anything that extends string | number | symbol except never
type Key = keyof any

// reproducible with absolutely anything
type Value = any

function a <T extends Key>(): Record<T, Value> {
    return {}
}

const b: Record<Key, Value> = {}
```

### 🙁 Actual behavior

In `a`, `{}` is not assignable to the return type.

### 🙂 Expected behavior

In `a`, `{}` is assignable to the return type just like `b` is as `Record<T, Value>` is identical to `Record<Key, Value>` and `T` extends `Key`.

**Comment by Dinhero21** [comment]
```ts
type FilterKey<T> = T extends Key

type c: Record<FilterKey<any>, Value> = {}
```

also works (does not error), which is how I expected a generic `extends` to work

**Comment by MartinJohns** [comment]
Duplicate of #47689.

**Comment by fatcerberus** [comment]
> `Record<T, Value>` is identical to `Record<Key, Value>`

It is not.  The only thing you know about `T` is that it's *assignable to* `Key`.  You don't know what type it refers to.

Let's say I call `a<"foo" | "bar">()`, its return type is thus `Record<"foo" | "bar", any>` i.e. `{ foo: any, bar: any }` and `{}` is not assignable to that (it's missing two properties).  This is working as intended.

**Comment by Dinhero21** [comment]
> > `Record<T, Value>` is identical to `Record<Key, Value>`
> 
> It is not. The only thing you know about `T` is that it's _assignable to_ `Key`. You don't know what type it refers to.
> 
> Let's say I call `a<"foo" | "bar">()`, its return type is thus `Record<"foo" | "bar", any>` i.e. `{ foo: any, bar: any }` and `{}` is not assignable to that (it's missing two properties). This is working as intended.

I see, thank you for the insight.

**Comment by Dinhero21** [comment]
> > `Record<T, Value>` is identical to `Record<Key, Value>`
> 
> It is not. The only thing you know about `T` is that it's _assignable to_ `Key`. You don't know what type it refers to.
> 
> Let's say I call `a<"foo" | "bar">()`, its return type is thus `Record<"foo" | "bar", any>` i.e. `{ foo: any, bar: any }` and `{}` is not assignable to that (it's missing two properties). This is working as intended.

Well, `"foo"` and `"bar"` should be assignable to `"foo" | "bar"` so shouldn't `Record<"foo", T>` and `Record<"bar", T>` be assignable to `Record<"foo" | "bar", T>`?

**Comment by MartinJohns** [comment]
`Record<"foo" | "bar", T>` is a type that must have both a `bar` and a `foo` property. `Record<"foo", T>` is a type that must only have a `foo` property, but not necessarily a `bar` property. So logically you can't assign it.
