### ISSUE TITLE
generics can only detect arrow function in object but not function expression

### ISSUE THREAD

**Issue by Asweallcan** [microsoft/TypeScript#57572]
### 🔎 Search Terms

typescript
generics
arrow function
function

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAwlC8UA8AoK6oFkLABYHsATAZwBo0MBBYYAQwGNcJCEoAKAWxwJIC4tuRYgEoEAPigA3fAEtCKMWwrp8YYDPwA7YvwDeyjOi54h-bCZIBuA4do0GTQv2p1Gza4YC+KUfAm1NEGsUSVoAJ1h8DjAtCE1gfjhENl8JXShvFBgomM044DZ9W3s3Qk5BElEiwwxjHmIAOgAjFpSoAHp2qDww-AB3buIoCDDesINPckM60yhqmqgWprb07y8UT2EULJzY+MKDO1dHcosROZtaisalts6ofABrCamrs71L9CX+Nr85jImG2EQA

### 💻 Code

```typescript
type C = <
        Methods,
        Attached = (methods: Methods) => void
    >(
        options: {
            methods: Methods;
            attached: Attached;
        }
    ) => any;
    
    var Component: C = () => { }
    
    Component({
        attached(methods) {
            methods.bbb() // throw ts error
        },
        methods: {
            bbb() { }
        }
    })
    
    Component({
        attached(methods) {
            methods.bbb() // ok
        },
        methods: {
            bbb: () => { }
        }
    })
```

### 🙁 Actual behavior

Parameter "methods" in "attach" function should be functions declared in "methods" property, but it works only when function is arrow function.

### 🙂 Expected behavior

Parameter "methods" in "attach" function should be functions declared in "methods" property

**Comment by Andarist** [comment]
An object method without an explicit `this` parameter is going to always be context-sensitive (it has that implied `this` parameter). Your issue falls under this umbrella issue: https://github.com/microsoft/TypeScript/issues/47599

You can verify this by annotating `this` explicitly in your `bbb`:
```ts
type C = <Methods, Attached extends (methods: Methods) => void>(options: {
  methods: Methods;
  attached: Attached;
}) => any;

var Component: C = () => {};

Component({
  attached(methods) {
    methods.bbb(); // ok
  },
  methods: {
    bbb(this: unknown) {},
  },
});
```

**Comment by Asweallcan** [comment]
> An object method without an explicit `this` parameter is going to always be context-sensitive (it has that implied `this` parameter). Your issue falls under this umbrella issue: #47599
> 
> You can verify this by annotating `this` explicitly in your `bbb`:
> 
> ```ts
> type C = <Methods, Attached extends (methods: Methods) => void>(options: {
>   methods: Methods;
>   attached: Attached;
> }) => any;
> 
> var Component: C = () => {};
> 
> Component({
>   attached(methods) {
>     methods.bbb(); // ok
>   },
>   methods: {
>     bbb(this: unknown) {},
>   },
> });
> ```

what if I need to use Type C to define bbb's "this" type，will this issue be solved or not? @Andarist

**Comment by Andarist** [comment]
You can even workaround this particular situation by reordering your `attached` and `methods`. `attached` acts as a consumer here and it's better to put the consumer after the producer (`methods` here):
```ts
type C = <Methods, Attached extends (methods: Methods) => void>(options: {
  methods: Methods;
  attached: Attached;
}) => any;

var Component: C = () => {};

Component({
  methods: {
    bbb() {}, // no `this` annotation!
  },
  attached(methods) {
    methods.bbb(); // ok, yay!
  },
});
```

**Comment by Asweallcan** [comment]
> You can even workaround this particular situation by reordering your `attached` and `methods`. `attached` acts as a consumer here and it's better to put the consumer after the producer (`methods` here):
> 
> ```ts
> type C = <Methods, Attached extends (methods: Methods) => void>(options: {
>   methods: Methods;
>   attached: Attached;
> }) => any;
> 
> var Component: C = () => {};
> 
> Component({
>   methods: {
>     bbb() {}, // no `this` annotation!
>   },
>   attached(methods) {
>     methods.bbb(); // ok, yay!
>   },
> });
> ```

ohhhhhhhh, I will try this, thanks
