### ISSUE TITLE
How to stop emitting declaration files for tests 

### ISSUE THREAD

**Issue by truedrug** [microsoft/TypeScript#57576]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Hi Team,

I have a src dir, inside which there are certain files/dirs for which I do not want to generate declaration types for. If i mention these files in exclude, these files miss on typescript compilation, which is needed for my case. Is there a way to achieve this? Am I missing something obvious here?

I don't want to generate types for my tests. I am authoring a package
```[tasklist]
### Tasks
```

**Comment by RyanCavanaugh** [comment]
Project references - set up a `test` project with declaration off and reference the non-test project

**Comment by truedrug** [comment]
Got it, so i will either use this or may be run a script to delete these unnecessary d.ts files post build. Thanks. Will update here, so it helps the community

**Comment by jakebailey** [comment]
I personally put my tests in `__tests__` and then npmignore them, which also works (if you don't care about purity).

**Comment by imsushree** [comment]
@jakebailey thanks. I learned something new today :)

**Comment by truedrug** [comment]
@jakebailey thanks. I learned something new today :)

**Comment by truedrug** [comment]
For now, I have fixed this by running a script post webpack build. For someone interested:

`index.js`

```"use strict";

const deleteFilesAndDirectories = require("./delete-files-and-dirs");

class DeleteSelectiveDeclarationFiles {
  constructor(paths) {
    this.paths = paths;
  }

  apply(compiler) {
    compiler.hooks.afterEmit.tap("DeleteSelectiveDeclarationFiles", () => {
      deleteFilesAndDirectories("lib", this.paths);
    });
  }
}

module.exports = DeleteSelectiveDeclarationFiles;
```

`delete-files-and-dirs.js`:
```
const fs = require("fs").promises;
const path = require("path");
const glob = require("glob");

async function deleteFilesAndDirectories(directoryPath, patterns) {
  directoryPath = path.resolve(directoryPath);

  for (const pattern of patterns) {
    const filesAndDirectories = glob.sync(pattern, {
      cwd: directoryPath,
      dot: true,
    });

    for (const fileOrDir of filesAndDirectories) {
      const fullPath = path.join(directoryPath, fileOrDir);
      try {
        if ((await fs.lstat(fullPath)).isDirectory()) {
          await fs.rm(fullPath, { recursive: true });
        } else {
          await fs.unlink(fullPath);
        }
      } catch (error) {
        console.error(`Error deleting ${fullPath}: ${error.message}`);
      }
    }
  }
}

module.exports = deleteFilesAndDirectories;
```

`Usage inside webpack`
```
// Delete unwanted declaration files
const files = ["__tests__", "test-utils.d.ts", "theme", "**/*.stories.d.ts"];
const plugins = [
  ......,
  new DeleteSelectiveDeclarationFiles(files),
];
```
