### ISSUE TITLE
Error: Class incorrectly implements interface with no reason specified

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#5757]
The fix in https://github.com/Microsoft/TypeScript/issues/1734 does not handle all cases. 

From @hessryanm  post in https://github.com/Microsoft/TypeScript/issues/1734#issuecomment-158780467:

> I'm still having this problem, even though it's marked as fixed.
Please see Gist: https://gist.github.com/hessryanm/177b0cada8c51516371e
Error is: models/Card.ts(13,14): error TS2420: Class 'Card' incorrectly implements interface 'ICard'.

**Comment by RyanCavanaugh** [comment]
Repro provided in #5751
