### ISSUE TITLE
Type guard makes Typescript infer that the type is never

### ISSUE THREAD

**Issue by anicodemo** [microsoft/TypeScript#57577]
### 🔎 Search Terms

Type guard narrowing never

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/es/play?ts=5.4.0-beta#code/MYGwhgzhAEBi0G8BQ1oEsIEEAUBKAXNAC4AWG6Mmi0ATgKZECuNAdsWTGixEWC8HQD2AM2hUAvigoAhPIVLly06vSat2i7r35DRyyZKShIlaHQAeROiwAmMeAknGo0ZRau37iQ8EFboYACSWnwC0AC80Cx0AO5ieADcRn480ABGwTyhdBFRsa6JSEhoothBIToAdBg4uNAAPvUBmdoC1RCyuHW+3IIgdJUgggDm2ABEgaaCNK5juAnQAPSL0AAqJDnlWVU1eMQAngAOOcOMYDQ20MJgaCAQADToRNAAtmAA1nQwW605IgfHPIANzoNEqSCAA

### 💻 Code

```ts

class F {
  isA(): this is A { return this instanceof A }
  isB(): this is B { return this instanceof B }
}

class A extends F {}
class B extends F {}

const aInstance = new A();
const bInstance = new B();

if (aInstance.isA() || aInstance.isB()) console.log("Is A or B"); 
```

### 🙁 Actual behavior

The aInstance.isA() type guard fails, it makes aInstance of type never.

### 🙂 Expected behavior

If aInstance.isA() is true, then aInstance must be of type A

**Comment by snarbies** [comment]
I'm not really seeing an issue here. The error is within the context of the condition, in particular the right hand operand to `||`. 

`aInstance` is typed as `A`. If `aInstance.isA()` returns false then the contextual type of `aInstance` would be `Exclude<A, A>`, i.e. `never`. Which makes sense—when is an `A` not an `A`?

Based on the type information available, the right hand operand to `||`, `aInstance.isB()`, will never be evaluated.

**Comment by fatcerberus** [comment]
Also note that in the given repro, all the classes are structurally identical - see https://github.com/microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely

**Comment by anicodemo** [comment]
Hi @fatcerberus and @snarbies, sorry, I simplified the code so it wasn't tedious to read.

If `aInstance` is actually of type `A` (according to the type guard and the instantiation), why Typescript  assumes that `aInstance` is of type `never`? It doesn't makes sense to me.

![image](https://github.com/microsoft/TypeScript/assets/42047441/d07ea301-5312-4f27-a9f0-a0a87f8f04d4)

**Comment by MartinJohns** [comment]
`A` and `B` are still structurally the same.

**Comment by fatcerberus** [comment]
> If aInstance is actually of type A (according to the type guard and the instantiation), why Typescript assumes that aInstance is of type never? It doesn't makes sense to me.

So the problem is that you wrote `aInstance.isA() || aInstance.isB()` - as far as the compiler can tell, the first condition is always true, so at the point `aInstance.isB()` is evaluated, it can’t possibly be an `A` (logical OR is short-circuiting), so `aInstance` there must be some other type - and since there’s no other possibility, you get `never`.

**Comment by anicodemo** [comment]
> Also note that in the given repro, all the classes are structurally identical - see https://github.com/microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely

Thanks for your patience @fatcerberus @MartinJohns and @snarbies, I finally understood. Avoiding empty classes did the magic.

![image](https://github.com/microsoft/TypeScript/assets/42047441/97d1382c-edc8-4a2b-92e0-88625e86883c)
