### ISSUE TITLE
@deprecated leaks over comments from previous blocks

### ISSUE THREAD

**Issue by Knagis** [microsoft/TypeScript#57583]
### 🔎 Search Terms

deprecated comment

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.0-beta#code/PQKhCgAIUgBATApgBwE6IMYEMAuj5QwBmA9iQEZaqHDjDCQA2iOkAHgNzh1iGQCOAd0RDENcM1ZYuWSAF5IARi48I0OEjSZc+PqQpVxk9lzbylHIA

### 💻 Code

```ts
/**
 * @deprecated
 * foobar
 */
// let x;

/**
 * qweqwe
 */
let a;
a = 1;

/**
 * @deprecated
 * foobar
 */
let x;
x = 1;
```

### 🙁 Actual behavior

`a` is marked as deprecated. But the rest of the documentation block is omitted (hovering `a` does not include `foobar` text). Also, hovering `x` shows where the deprecation comes from but hovering `a` includes no such information

### 🙂 Expected behavior

`a` is not marked as deprecated since the `@deprecated` is in a previous unrelated documentation block.

**Comment by RyanCavanaugh** [comment]
There's a simple rule: `@deprecated` applies to the next declaration. The next declaration is `a`, so `a` is deprecated. That seems desirable from a predictability standpoint.

I don't see a lot of point in adding epicycles around what intervening trivia does/doesn't count for that rule; we didn't really see any of these free-floating `@deprecated` tags and it doesn't seem like people want to add them. Making sense of multiple adjacent comments will always be somewhat heuristic-based so the display of `foobar` is similarly open to interpretation.

**Comment by Knagis** [comment]
what feels strange is that `@deprecated` gets a special treatment, other jsdoc directives are not applied in the same manner:

```
// @ts-check

/**
 * asdasd
 * @type {number}
 * @deprecated
 */
/**
 */
let a;

a = 1;
```

`a` gets deprecated but doesn't get the type applied to. Also when `@deprecated` is within the last doc block, it shows the hint on hover where the deprecation comes from, but it doesn't when deprecated comes from the block before it.

The scenario where i ran into this as an issue is i commented out a lot of declarations in lib.dom.d.ts file and only by accident noticed that some declarations i left were now marked as deprecated. i actually did check whether the documentation blocks are interrupted by a simple `//` comment line - and thought they were, since it seems nothing else gets through.
