### ISSUE TITLE
Configurable auto barrel-exporting

### ISSUE THREAD

**Issue by ryuujo1573** [microsoft/TypeScript#57581]
### 🔍 Search Terms

auto barrel export, barrel file 

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

```ts
// path: src/demo.ts
import { foo, bar, baz } from "./barrel"

// path: src/barrel/index.ts
export * from "./foo"
export * from "./bar"
export * from "./baz"
// ...
```

It would be benefit that avoids manually managing **`barrel/index.ts`** to export \* from one another new submodule.

### 📃 Motivating Example

\+ src/barrel/foo.ts
\+ src/barrel/bar.ts
\- src/barrel/index.ts 
&nbsp;&nbsp;~export * from './foo'~

### 💻 Use Cases

This feature would be used to simplify barrel exporting for code splitting.

And currently, the barrel file should be managed manually, which needs to be updated whenever a new module joins.

This feature may work similar to an existing Code extension:
https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-typescript-exportallmodules

**Comment by MartinJohns** [comment]
This falls under this category:

> This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

**Comment by RyanCavanaugh** [comment]
Yep; if it's JS code that's going to appear in your final output, it's code you'll need to write yourself (or have a tool write for you as the case may be)
