### ISSUE TITLE
typescript editor slow to refresh error state

### ISSUE THREAD

**Issue by lucamorelli** [Microsoft/TypeScript#5758]
Hi,
  I'm using vs 2015 update 1 rc, with ts 1.7. Looks like that sometimes the typescript file editor is slow on updating the error status after changes
![untitled](https://cloud.githubusercontent.com/assets/127777/11349231/597efab0-922b-11e5-9511-13f2e6340e0b.png)

In this file I removed a parameter in the constructor, and although I have recompiled the file, the editor still show the error of the parameter that uses a non imported type

**Comment by mhegazy** [comment]
looks like a duplicate of #5063. this should be fixed in the next release.

**Comment by lucamorelli** [comment]
thanks, good news.
