### ISSUE TITLE
Cannot find a matching method signature.

### ISSUE THREAD

**Issue by LiST-GIT** [microsoft/TypeScript#57592]
### 🔎 Search Terms

generics, signature

### 🕗 Version & Regression Information

5.5.0-dev.20240229

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAogbhAdsAKuaBeKiCuBbAIwgCcoAfKAZ2GIEtEBzcqkQgewBsBuAKFElgJkAEQgBjDgENik4LTaJKULACVxbYgBMAPJMQgANFD0gA2gF0AfLx4TJlJQEFtw11AgAPYEk1L4SYFE7GTkFJVV1LV19IxMLS0soAG8eKDTjSk0ACgBKZNT0wuAAC1pKADpKHyyAckl6mqMARhyuKAB6dvdiYg0CtIBffqofbRR3Lx8-IVR0Syz+CAAuKBQjco3pBkoV12FTFHM8pKghodsw4GNlbAgAdyhnFML6yRXTXEIScwNh00WVv5kGhIOYVnEfjwBvNWjxJJVqnUGs1YUA

### 💻 Code

```ts
type EventType = number | string | symbol;
type EventDeclarations = Record<any, any[]>;

class A<DDD extends EventDeclarations = Record<any, any[]>> {
    asd() {
        this.send('aaa', 1); // error
    }
    send<T extends EventType>(type: T, ...args: DDD[T]) { }
}

const a = new A<{
    aaa: [number],
    [type: EventType]: any[],
}>();
a.send('aaa', 1);
```

### 🙁 Actual behavior

When I use ```this.send('aaa', 1);```, the signature I expect should be ```this.send('aaa', args:any[]);```, but it gives an error.

### 🙂 Expected behavior

The method signature should be ```this.send('aaa', args:any[]);```

**Comment by fatcerberus** [comment]
The error seems correct because:

```ts
const a = new A<{
    aaa: [string],
    [type: EventType]: any[],
}>();
a.send('aaa', 1);  // this is an error because 1 isn't a string
a.asd();  // ...but this sends a number
```

**Comment by LiST-GIT** [comment]
> The error seems correct because:
> 
> ```ts
> const a = new A<{
>     aaa: [string],
>     [type: EventType]: any[],
> }>();
> a.send('aaa', 1);  // this is an error because 1 isn't a string
> a.asd();  // ...but this sends a number
> ```
> 
> The implementation must be correct for any possible `DDD`, not just the constraint.

I don't understand what you mean. My issue is with the expectation of ```this.send('aaa', 1);```, not ```a.send('aaa', 1);```.

**Comment by fatcerberus** [comment]
Yes, I understand.  But that *should* be an error for the exact same reason `a.send('aaa', 1)` is an error in my example: it's not valid for all types that `DDD` can be.

**Comment by LiST-GIT** [comment]
> Yes, I understand. But that _should_ be an error for the exact same reason `a.send('aaa', 1)` is an error in my example: it's not valid for all types that `DDD` can be. If you're not allowed to pass a number to `send` from outside, why should you be able to from inside?

I need is an error when declaring ```aaa: [string]``` and using ```a.send('aaa', 1)```.
When I use ```this.send('aaa', 1);``` internally, I expect it to be ```this.send('aaa', any[]);```.

**Comment by fatcerberus** [comment]
So you'd be okay with the fact that
```ts
const a = new A<{
    aaa: [string],
    [type: EventType]: any[],
}>();
a.asd();
```
would be allowed despite possibly sending the wrong type?

**Comment by LiST-GIT** [comment]
I think I understand what you mean now. So, if I want to send an internal event type, what should I do?

```ts
type EventType = number | string | symbol;
type EventDeclarations = Record<any, any[]>;

class A<DDD extends EventDeclarations = Record<any, any[]>> {
    asd() {
        this.send('close'); // <-------- error
    }
    send<T extends EventType>(type: T, ...args: DDD[T]) { }
}

const a = new A<{
    aaa: [number],
    [type: EventType]: any[],
}>();
a.send('aaa', 1);
```
