### ISSUE TITLE
[discussion] type never should be threated as return

### ISSUE THREAD

**Issue by kettei-sproutty** [microsoft/TypeScript#57594]
### 🔍 Search Terms

`never`, `return never`, `infer never`

### ✅ Viability Checklist

- [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.) 
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Hello,
this is my first issue, please tell me if there is something wrong or if i need to change something.

I was getting little bit confused on how the type `never` is treated.
As docs, type `never` is represents the type of values that never occur, so in my mind it should inherit the same properties as the return type.

When I use a function that never returns, i expect that all the code below should be considered as "unreachable", and so on like i was using a return.

Edit: I'm not sure about the two above viability checks

### 📃 Motivating Example

In this case, i expect the typescript compiler to understand that:
1. a should be only of type `string`;
2. that all code below the `never` return type should be unreachable;

I don't understand if this is the expected behavior or a design choice, but in my opinion this little bit confusing, considering that i could use a function that returns never and don't understand why my code below the function is never executed.

```ts
const shouldNeverReturn = (): never => { 
    while(true) {}
}

const example = (a: string | null) => {
    if (!a) shouldNeverReturn();

    // here i expect a to be only of type `string`
    a.toUpperCase();
    
    shouldNeverReturn();
    // here i expect this code is unreachable
    console.log(a);
}
```

### 💻 Use Cases

1. What do you want to use this for? `better typing inference`
2. What shortcomings exist with current approaches? `explicit return on a function that returns never`
3. What workarounds are you using in the meantime? `explicit return on a function that returns never`

**Comment by MartinJohns** [comment]
This already works, but requires the function to have an explicit type annotation, and yours does not. This requirement is for performance reasons.

**Comment by kettei-sproutty** [comment]
> This already works, but requires the function to have an explicit type annotation, and yours does not. This requirement is for performance reasons.

Sorry can you provide me an example? I think i didn't understand where should i put the explicit type annotation.
I tried with the following:

```ts
// this function already explicit never return
const shouldNeverReturn = (): never => { 
    while(true) {}
}

// i tried to add void | never here
const example = (a: string | null): void | never => {
    if (!a) shouldNeverReturn();

    // here i expect a to be only of type `string`
    a.toUpperCase();

    shouldNeverReturn();
    // here i expect this code is unreachable
    console.log(a);
}
```

but the behavior is the same as before.

For reference i tried to use `5.3.3`, `beta` and `nightly`.

Let me know and thanks for the response :)

**Comment by MartinJohns** [comment]
`shouldNeverReturn` has an inferred type due to the missing type annotation. A type annotation is required.

**Comment by kettei-sproutty** [comment]
@MartinJohns  thank you for your answer, I was able to achieve the expected behavior:

```ts
type ReturnsNever = () => never;

const shouldNeverReturn: ReturnsNever = () => { 
    while(true) {}
}

const example = (a: string | null): void | never => {
    if (!a) shouldNeverReturn();

    // a is of type of string
    a.toUpperCase();

    shouldNeverReturn();
    // here is unreachable
    console.log(a);
}
```

Do you think that writing this inside docs could be a good idea? (or maybe it is already written?)
I never found something that was explaining how `never` type should behave in this cases.

Thanks again for your support
