### ISSUE TITLE
Formatter should remove spaces between `...` and type name in tuple spread

### ISSUE THREAD

**Issue by LiST-GIT** [microsoft/TypeScript#57590]
### 🔎 Search Terms

autoformat, spaces

### 🕗 Version & Regression Information

5.5.0-dev.20240229

### 💻 Code

```ts
let a: [...     any[]];
/**/           let b = 123;
```

### 🙁 Actual behavior

Do not remove extra spaces.

### 🙂 Expected behavior

```ts
let a: [...any[]];
/**/ let b = 123;
```

**Comment by LiST-GIT** [comment]
vscode setting.json
```json
{
    "[typescriptreact]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
}
```

**Comment by RyanCavanaugh** [comment]
I'm not really sure if the `/**/    let` gap should be removed. Comments are generally "ignored" as best we can for format purposes, so it looks more like an indentation than anything else.

`...     any` should definitely be trimmed, though
