### ISSUE TITLE
typescript can not detect the change after an async function and show it as compile error

### ISSUE THREAD

**Issue by Magicqy** [microsoft/TypeScript#57597]
### 🔎 Search Terms

- This comparison appears to be unintentional because the types
- ts(2367)

### 🕗 Version & Regression Information

- I tried version 5.3.3 and 3.3.3 in playground, and I reviewed the FAQ for entries about type overlap and error code ts(2367)

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/HYQwtgpgzgDiDGEAEAVaAXAosArmAwgPZhwBOyA3gFBK1IS5hIDK6I6OUS1dvL6ARiQBeJAAYANDT61WAJhFIBUmbPQBmRXJV0AvlWm0ANhHRIobDl1Gt2nAHSsBAbgO8QUAJ7B4SAGY4PugAloTAqBgAFACU3IZ8FnbW-EmO6HKuqkggAO4gwWYAgl4+AGKB8DGZqgD0NeieMNDwpMEwZvAg4cCEZgAmphDwZugAFsiJVkhgIJ5I8KNdAObIweFjyB7evgFBocDxvMF+SJGTnCLCNpYOrOqxPKr6vPrxWz7+FSFhSMXb5T4YnEsuQOKRuhAckgAAqkYjBKAQAA8ADdCME+gA+SKRchQQhGFEQCRIcgAKyG6FiwkxwKydER6BQwUghBw6Bx1Npj3pCRuyVsVjS6mqvN4eIJRKqhyeJIEYgV0VFfF0Svi+l0QA

### 💻 Code

namespace TestEnumCompare {
    enum Status {
        St1 = 0,
        St2 = 1,
        St3 = 2,
    }

    let status = Status.St1;

    async function Test() {
        status = Status.St2;
        await AsyncFunc();
        //typescript can not detect the status may change in the async function
        if (status === Status.St3) {
        }
    }

    async function AsyncFunc() {
        return new Promise<void>((resolve, reject) => {
            setTimeout(() => {
                status = Status.St3;
                resolve();
            }, 1000);
        });
    }
}

### 🙁 Actual behavior

v5.3.3 shows error:
This comparison appears to be unintentional because the types 'Status.St2' and 'Status.St3' have no overlap.ts(2367)

v3.3.3 shows error:
This condition will always return 'false' since the types 'Status.St2' and 'Status.St3' have no overlap.

### 🙂 Expected behavior

showing no error

**Comment by MartinJohns** [comment]
Another duplicate of #9998.

**Comment by Magicqy** [comment]
@MartinJohns @RyanCavanaugh 

    thanks for your reply, I'm a new guy using typescript only a short time.
    I check the issue you mentioned, it seem like the behaviour of this case has exists a very long time.
    so it's by design, not a bug?
    or is there any tsconfig options to turn this error off?

**Comment by MartinJohns** [comment]
It's by design / a design limitation.

**Comment by Magicqy** [comment]
@MartinJohns got it, I will try some other ways to work around this problem, thanks
