### ISSUE TITLE
Allow to create a literal string class

### ISSUE THREAD

**Issue by raythurnevoid** [microsoft/TypeScript#57617]
### 🔍 Search Terms

class, extends, string, literal

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow to define classes like this:

![image](https://github.com/microsoft/TypeScript/assets/53383860/5bb3907d-a09b-4050-ad43-3ec0da732d29)

![image](https://github.com/microsoft/TypeScript/assets/53383860/1d042b9b-e296-4518-a9bb-48f6058bed26)

### 📃 Motivating Example

It would allow grouping under a class all the logic related to a specific "literal string"

### 💻 Use Cases

1. What do you want to use this for?

Grouping logic related to a "literal string"

2. What shortcomings exist with current approaches?

I have to define the literal string type separately from its functionalities and I can't have a constructor out of the box eg:

![image](https://github.com/microsoft/TypeScript/assets/53383860/8da3b789-7af8-4f0e-ae49-c0f0cf26c02a)

3. What workarounds are you using in the meantime?

none

**Comment by fatcerberus** [comment]
> This ~~isn’t~~ *is* a runtime feature (e.g. library functionality, **non-ECMAScript syntax with JavaScript output**, new syntax sugar for JS, etc.)

This is out of scope for TypeScript.

**Comment by raythurnevoid** [comment]
> This is out of scope for TypeScript.

my example was incorrect I meant something like this:

`extends String<"USD" | "EUR">`

This doesn't require any runtime logic, it only requires to update the types for the String.

**Comment by RyanCavanaugh** [comment]
You're already able to write this:
```ts
class Currency<T extends "USD" | "EUR"> extends String {
    value: T;
    constructor(value: T) {
        super(value);
        this.value = value;
    }
  static parse(value: string): Currency<"USD" | "EUR"> {
    if (value === "USD" || value === "EUR") {
      return new Currency(value);
    } else {
      throw new Error("Invalid currency");
    }
  }
  valueOf(): T {
    return this.value;
  }
}
const currency = new Currency("USD");
if (currency.valueOf() === "GBP") {
    // Error as expected

}
```
