### ISSUE TITLE
an error in iteration

### ISSUE THREAD

**Issue by yhown589** [microsoft/TypeScript#57615]
### 🔎 Search Terms

error in iteration

### 🕗 Version & Regression Information

My current TypeScript version is typescript@5.3.3
My IDE is WebStorm, and its version is 2023.3.2

### 💻 Code

```
export interface DownloadOption {
    mp4Quality: "1080p" | "720p" | undefined,
}

enum mediaQualityMapping {
    "720p" = "m-hd",
    "1080p" = "hd"
}

function bug(downloadOption: DownloadOption) {

    let resInJson: any


    if (downloadOption.mp4Quality === undefined) {
        return;
    }

    // no error tips: put it into a variable
    // let mp4Quality = downloadOption.mp4Quality
    // if (Object.keys(resInJson['anyField']).some((ele) => ele.includes(mediaQualityMapping[mp4Quality]))) {
    //     console.log("some msg")
    // }

    // If it is located in the iteration object, an error message will appear.
    if (Object.keys(resInJson['anyField']).some((ele) => ele.includes(mediaQualityMapping[downloadOption.mp4Quality]))) {
        console.log("some msg")
    }
}

function noBug(downloadOption: DownloadOption) {
    let resInJson: any

    if (downloadOption.mp4Quality === undefined) {
        return
    }

    if (resInJson['anyField'][mediaQualityMapping[downloadOption.mp4Quality]] === undefined) {
        console.log("some msg")
    }
}
```

### 🙁 Actual behavior

Under the premise that I have added the judgment whether it is undefined: 
```
if (downloadOption.mp4Quality === undefined) {
    return;
}
```
if I put `downloadOption.mp4Quality` into a iteration
```
if (Object.keys(resInJson['anyField']).some((ele) => ele.includes(mediaQualityMapping[downloadOption.mp4Quality]))) {
    console.log("some msg")
}
```
that would be an error message like the following shows:
![PixPin_2024-03-03_03-17-56](https://github.com/microsoft/TypeScript/assets/158656896/03bcbccb-c6ac-4b56-bc19-37b475f5976e)

But if I put it into a variable, it's normal, no error message, like this:
![PixPin_2024-03-03_03-15-11](https://github.com/microsoft/TypeScript/assets/158656896/8adaffc7-325e-461d-a0dc-109a0daf08fa)

### 🙂 Expected behavior

Under the premise that I add the judgment of whether it is undefined, no matter whether it is placed in the iteration or not, there should be no error prompt.

**Comment by fatcerberus** [comment]
#9998
