### ISSUE TITLE
Default initializers for binding elements are not contextually typed appropriately

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5762]
The following example should error; instead, it passes because `v` is not contextually typed and instead gets the `any` type:

```ts
interface Foo {
    prop: (x: string) => number;
}

function f({ prop = v => v }: Foo) {
}
```

The following example should be free of errors; instead the compiler errors on `prop` with an assignability error:

```ts
interface Foo {
    prop: [string, number];
}

function f({ prop = ["hello", 1234] }: Foo) {
}
```

Error:

```
foo.ts(5,14): error TS2322: Type '(string | number)[]' is not assignable to type '[string, number]'.
  Property '0' is missing in type '(string | number)[]'.
```

Similarly, with string literal types:

```ts
interface Foo {
    prop: "foo" | "bar"
}

function f({ prop = "foo" }: Foo) {
}
```

Error:

```
foo.ts(5,14): error TS2322: Type 'string' is not assignable to type '"foo" | "bar"'.
  Type 'string' is not assignable to type '"bar"'.
```

**Comment by DanielRosenwasser** [comment]
To whomever is assigned, please include at least all three of the above tests, each with `noImplicitAny` set.

**Comment by sandersn** [comment]
PR #7298 fixes these cases as well as testing a few others.
