### ISSUE TITLE
[Vue TS Plugin] `remove Project::Project ...` keeps getting triggered for multiple tsconfigs repo

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/TypeScript#57633]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I'm not sure of the exact conditions under which the problem occurs, but it is reproducible reliably. In a Vue project containing multiple tsconfigs, enabling the Vue TS Plugin will cause 'remove Project::Project ...' keeps getting triggered.

### Steps to reproduce

1. Clone https://github.com/elk-zone/elk
2. Open the repo in VSCode, install [marketplace.visualstudio.com/items?itemName=Vue.volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar) 2.0.4
3. Open `components/account/AccountAvatar.vue`, the CPU usage of tsserver rises to 100%. `remove Project::Project '/Users/johnsonchu/Desktop/GitHub/elk/docs/tsconfig.json' (Configured)` is triggered every second: [tsserver.log.zip](https://github.com/microsoft/TypeScript/files/14482228/tsserver.log.zip)

**Comment by sheetalkamat** [comment]
the tsserver log has too many plugins involved. Please send logs with just the vue plugin to investigate this issue.

**Comment by johnsoncodehk** [comment]
Here it is: [tsserver.log.zip](https://github.com/microsoft/TypeScript/files/14489637/tsserver.log.zip)

https://github.com/microsoft/TypeScript/assets/16279759/92f2f521-3627-4f04-ae80-a09da46d53cc

**Comment by sheetalkamat** [comment]
@johnsoncodehk can you please try typescript nightly. i think this is fixed by https://github.com/microsoft/TypeScript/pull/56403 Dont have macOS to test it out but it does not repro on windows.

**Comment by johnsoncodehk** [comment]
The strange thing is that I can't reproduce the problem now, I have tried to restore the reproduction conditions as much as possible. I'm assuming this has something to do with the state of my system, once I successfully reproduce it again I'll let you know if the nightly build fixes the issue. thank you for your time!
