### ISSUE TITLE
[Vue TS Plugin] Modifications to InferredProject's language service were discarded

### ISSUE THREAD

**Issue by johnsoncodehk** [microsoft/TypeScript#57630]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Issue: https://github.com/vuejs/language-tools/issues/3942

Vue TS Plugin modifies project language service at [this line](https://github.com/vuejs/language-tools/blob/3793058ce0205849c6159ba6070ada232c071937/packages/typescript-plugin/index.ts#L62) to handle virtual code mapping, which works well for ConfiguredProject. But for InferredProject, tsserver seems to always discard the existing language service when switching columns from .vue files to .ts files, and the newly created language service instance will not pass the plugin's create hook, so the plugin cannot modify it again.

However, the plugin's modifications to the language service host are retained, causing the vue file to display unmapped virtual code diagnostic messages.

### Steps to reproduce

1. Clone https://github.com/johnsoncodehk/volar-starter
	Since it is just for demonstration purposes, node_modules will not be installed.
2. Delete the `tsconfig.json` file in repo
3. Open the repo in VSCode, install https://marketplace.visualstudio.com/items?itemName=Vue.volar 2.0.4 and open `src/components/HelloWorld.vue`
4. You should see TS errors reported due to missing dependencies, as shown below:
	<img width="796" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/0d871b2a-1346-46d3-8aa6-4a66c6f87925">
5. Close `HelloWorld.vue`, open `src/main.ts`, then re-open `HelloWorld.vue`
6. Errors in the image above is now displayed in the wrong location (end of file)
	<img width="1066" alt="image" src="https://github.com/vuejs/language-tools/assets/16279759/5215f618-b06a-4156-b200-20d134106345">

**Comment by sheetalkamat** [comment]
I dont see any issues. I am using typescript nightly. Did i miss something. 

https://github.com/microsoft/TypeScript/assets/8052792/0f8cef50-4096-452a-a6cd-e15fa340f716

**Comment by johnsoncodehk** [comment]
I found that you may also need to install https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode to reproduce the issue.

The triggering method for typescript nightly is slightly different. After reopening `HelloWorld.vue`, you need to execute the Restart TS Server command.

[tsserver.log.zip](https://github.com/microsoft/TypeScript/files/14489715/tsserver.log.zip)

https://github.com/microsoft/TypeScript/assets/16279759/86b45ed8-1e86-4655-bb5d-db1f46de0d1a

**Comment by sheetalkamat** [comment]
@johnsoncodehk after investigating this it seems the issue with the plugin  https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode   

This is what i did to repro the issue:
1. Open App.vue
2. Open Main.ts
3. And this is where things go off rail because the request goes to ts LS instead of the plugin.

After 2, when editor invokes the `getErr` request it fails as there is some issue with the `d.ts` added by that plugin but its script info is not present. 
After that tsserver receives request: 
```jsonc
    {
      "seq": 41,
      "type": "request",
      "command": "configurePlugin",
      "arguments": {
        "pluginName": "typescript-svelte-plugin",
        "configuration": {
          "enable": false
        }
      }
    }
```

This is where i think plugin reverts the LS to original ts LS and not just making itself pass through. That results in the vue plugin to be not in picture any more for the error requests.

**Comment by johnsoncodehk** [comment]
Thank you very much for your survey! I'll forward this to Svelte language tools maintainers.
