### ISSUE TITLE
Typescript project references cache not invalidated when @types/** version changes in package.json

### ISSUE THREAD

**Issue by en-yash** [microsoft/TypeScript#57647]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I'm tackling a monorepo utilizing TypeScript (`v4.9.5`) with project references for type checking across the repository. Recently, we transitioned to a new Node.js version (`18.19.1`), necessitating an update to `@types/node` in the package.json.

Upon running tsc -b tsconfig.json -v, TypeScript failed to type check the repository, citing the previous emitted cache as up to date. Consequently, it failed to detect errors in the code pertaining to changes in types introduced by the newer Node.js version.

When invoking tsc with the -b flag, my expectation was that TypeScript would invalidate the old cache due to the version change in `@types/node`. However, it didn't, indicating that the cache was already updated with the changes.

Is this behaviour expected?

**Comment by en-yash** [comment]
> You're nearly 5 TypeScript versions behind; can you try with a more recent version? Very possible this was fixed as there have been many build mode fixes in the last year+.
> 
@jakebailey thanks for the quick response, but could you confirm if this is something that has been fixed in the next versions? Our monorepo is huge, and while we are actively planning on upgrading it to TS 5.0+, it's still might take us a few months, but if the upgrade does not fix it, we would have to actively plan out a solution for this particular edge case

**Comment by jakebailey** [comment]
There have been quite a few fixes to incremental mode since 4.9; I don't think I can remember if any in particular address this specific behavior. @sheetalkamat may have a better memory than I do.

**Comment by sheetalkamat** [comment]
`tsc -b` only checks for timestamps of files that are your "input" files specified in tsconfig.json and not all the unlisted dependencies. That means the change in node version would need you to force the rebuild instead of just normal build, unless you configure it some other way (which is not recommended)

**Comment by en-yash** [comment]
@sheetalkamat thanks for the clarification. Closing this

**Comment by sudesh-poojari** [comment]
@sheetalkamat - is there a way to bust cache for third party dependencies similar to
Input files?
