### ISSUE TITLE
Add support for "this is X" style user-defined type guards

### ISSUE THREAD

**Issue by mrcrowl** [Microsoft/TypeScript#5764]
I'd like to use user-defined type guards in the following manner:
```typescript
abstract class Animal
{
    get isDog(): this is Dog;
}

class Dog extends Animal
{
    get isDog(): this is Dog { return true; }
    bark() { console.log("woof"); }
}

let animal = new Dog();
if (animal.isDog)
{
   animal.bark()
}

```

This use-case was suggested by @RyanCavanaugh when he opened #1007 but seems to be unsupported as of TypeScript 1.6.

**Comment by ahejlsberg** [comment]
Looks like a good suggestion to me.

**Comment by robyoder** [comment]
It looks like this wasn't implemented as described. I can't seem to set a type guard on a getter like in the example above, only on regular functions. On a getter, I'm told "A type predicate is only allowed in return type position for functions and methods."

**Comment by mhegazy** [comment]
that is correct. you can find more documentation in https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#this-based-type-guards

**Comment by robyoder** [comment]
I read that already, doesn't talk about this at all...

**Comment by mhegazy** [comment]
User define guards are not supported in property declaration or acccessor (getter or setter). that as specified in the original proposal, but was cut from the implementation.
