### ISSUE TITLE
An object does not satisfy Record<string, any>

### ISSUE THREAD

**Issue by vladmw5** [microsoft/TypeScript#57648]
### 🔎 Search Terms

React PropTypes generic, satisfies, 

### 🕗 Version & Regression Information

Typescript version 4.1.2, Typescript version 5.3.3

Tried on both versions

### ⏯ Playground Link

[[KYDwDg9gTgLgBDAnmYcCyEAmBDANgBSgjAGc4BeOAbwCg565jgA7ALjgCMIJdhtmA3HQYRmAYVwQSwdgAoAlBQB8cAG4QAlpiEM4AYwAWG3Jigt2](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCyEAmBDANgBSgjAGc4BeOAbwCg565jgA7ALjgCMIJdhtmA3HQYRmAYVwQSwdgAoAlBQB8cAG4QAlpiEM4AYwAWG3Jigt2-REIC+QmntEl4YIqQrVh9JmwRQArsAANJ6M4pLScorkKsx+uLjBuobGpuZwsfHB1nAk2DAaJABmGsBkAErADlCYADxOUBrMAOaBcJZKNPaO8Bg4uO6yLsQk7L14hMNRMXG4nUgocBNgACrIpTXLAGJ+zHr5omIQALaQzCzwoDAsmGSDriNwFVW19Y0tbcyISlMfXxQhWx2ew0B2Op3OcEu11uQ1I7EahWAUEeSxIP0scAA-Cj7nB2GdVEi7KBILAEGs4GI-E5jgBBZgkADuSLGBFxlCWqxQJBq82AEEK6CweCUQiAA)](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCyEAmBDANgBSgjAGc4BeOAbwCg565jgA7ALjgCMIJdhtmA3HQYRmAYVwQSwdgAoAlBQB8cAG4QAlpiEM4AYwAWG3Jigt2-REIC+QmntEl4YIqQrVh9JmwRQArsAANJ6M4pLScorkKsx+uLjBuobGpuZwsfHB1nAk2DAaJABmGsBkAErADlCYADxOUBrMAOaBcJZKNPaO8Bg4uO6ysi7EJOy9eIQjUTFxuPKdSChwk2AAKsilNasAYn7MevmiYhAAtpDMLPCgMCyYZEOuo3AVVbX1jS1tzIhK018-FBCOz2Bw0R1O50ucGut3uw1I7EahWAUGeKxIf0scAA-GjHnB2BdVCi7KBILAEBs4GI-E5TgBBZgkADuKPGBHxlBW6xQJBqi2AEEK6CweCUAiAA)

### 💻 Code

```ts
export type ModalProps = {
    open: boolean;
    onClose: () => void;
    children: any;
};

const props = {
    open: true,
    onClose: () => null,
    children: null,
} satisfies Record<string, any>

const Modal = (props: ModalProps) => null

type PropTypes<TFunctionComponent extends (props: Record<string, any>) => any> =
    TFunctionComponent extends (props: infer RProps) => any ? RProps : never;

export type CustomAnswerModalProps = PropTypes<typeof Modal>;
```

### 🙁 Actual behavior

CustomAnswerModalProps is inferred successfully, but there is an error on line 18:
```
Type '(props: ModalProps) => null' does not satisfy the constraint '(props: Record<string, any>) => any'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'Record<string, any>' is missing the following properties from type 'ModalProps': open, onClose, children(2344)
```

### 🙂 Expected behavior

CustomAnswerModalProps is inferred successfully and there is no error, as the Modal function definitely satisfies the constraint

**Comment by MartinJohns** [comment]
This is working as intended. Your object does extend `Record<string, any>`, but `(props: ModalProps) => null` does not extend `(props: Record<string, any>) => any`. When you disable `strictFunctionTypes` it will work.

See also: https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant

**Comment by MartinJohns** [comment]
> I still cannot get why (n: 5) => any does not satisfy (n: number) => any constraint, since 5 does satisfy number

The type expects a function that can accept **any** `number`, but the type passed is a function that can only accept **one** number (`5`).

Your `TFunctionComponent` expects a function that can accept **any** object (aka `Record<string, any>`), but you pass `Modal`, which is a function that expects **at least** `ModelProps`.

Your best option is to simply have `PropTypes<TFunctionComponent extends (props: any) => any>`.

**Comment by MichalMarsalek** [comment]
Contravariance can be confusing but that's not typescript's fault.

**Comment by fatcerberus** [comment]
Think of contravariance this way: let’s say I ask for something typed as

```ts
type Vet = (x: Animal) => Animal;
```

because I run a zoo and I have all sorts of animals.  If what you give me instead is

```ts
type Specialist = (x: Dog | Cat) => Dog | Cat;
```

then that’s not going to work for me because I might need to pass in an `Elephant` at some point.  So the subtyping relationship turns upside down when you’re the one giving *me* values instead of you using them yourself.

**Comment by fatcerberus** [comment]
Everybody trips over this at some point; I think it naturally confuses people because it doesn’t match how we talk about things day-to-day - in everyday language both `Vet` and `Specialist` would be described as types of doctors and *what we need a doctor to be able to do* is something we only care about when we call one - but in a type system those requirements are encoded right into the type so you end up having to care about them sooner
