### ISSUE TITLE
Built produced by tsc does not have extension in import statement

### ISSUE THREAD

**Issue by rdev06** [microsoft/TypeScript#57651]
### 🔎 Search Terms

`no extension in import statement`
`definition not found after build`
`file not found after build`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about extensionless-import-statement

### 💻 Code

foo.ts
```ts
export default function(){
return 'Hello World'
}
```
bar.ts
```ts
import foo from './foo';
console.log(foo())
```
then make a build
```sh
$ tsc
```
This will produce a file for bar.js
```js
import foo from './foo';
console.log(foo())
```
Upon executing this file with node js
```sh
node dist/bar.js
```

### 🙁 Actual behavior

throws error
`Cannot find module '/Users/roshandev/work/demo/dist/foo' imported from /Users/roshandev/work/demo/dist/bar.js
[tsconfig.json](https://github.com/microsoft/TypeScript/files/14496970/tsconfig.json)
`

### 🙂 Expected behavior

This should print
`Hello World`

### Additional information about the issue

I attached my tsconfig.json with this. Please suggest me how to proceed on this
As nodejs is not supporting extension-less import with `"type":"module"` when defined in package.json
But this is required to use `import` statement for es modules`
[package.json](https://github.com/microsoft/TypeScript/files/14497029/package.json)
[tsconfig.json](https://github.com/microsoft/TypeScript/files/14497052/tsconfig.json)

**Comment by fatcerberus** [comment]
Yes, you need to add the `.js` extension to the import.  Whatever import path you write in TS is exactly what gets imported at runtime.

**Comment by RyanCavanaugh** [comment]
https://www.typescriptlang.org/docs/handbook/modules/introduction.html
