### ISSUE TITLE
Why are generics not deducing nested objects correctly?

### ISSUE THREAD

**Issue by masterYi101** [microsoft/TypeScript#57658]
### 🔎 Search Terms

Generic derivation

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAggdiAShAxgewE4BMoF4rLrYA8AzsBgJZwDmANFAIYIB8A3AFCiRQBmceKMQAqUCAA9gEOFlJQA3kwBcsBIUw4AviwAUYRhkYBbUisWMVwgNoAiRjYC6UTQEo8LKNbuPOHdHHIoACMVfkE9A2NSN1wPeQ4oRKgMCGAAVwwBfUMTADpGDk1ff0CUQSCdeMSLBQSkxgBGFQaAJgBmOjrNTtdOIA

### 💻 Code

```ts
// Your code here
type AnyRecord = Record<string, any>;
type fn = <T extends { a: AnyRecord }>(params: { a: T["a"] }) => T["a"];

const b: fn = (params) => {
    return params.a
};

const c = b({
  a: {
    a1: 123,
  },
});

```

### 🙁 Actual behavior

Why isn't c deduced to the type I actually passed in?

### 🙂 Expected behavior

c is deduced to the type I actually passed in

**Comment by Andarist** [comment]
Indexed accesses like this are never used as inference sources - the information at this location is at best partial information for what `T` can be. That said, there is an open PR that would make this inference work: https://github.com/microsoft/TypeScript/pull/53017

You can just infer into the whole `T` like this: [TS playground](https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAggdiAShAxgewE4BMoF4rLrYA8AzsBgJZwDmANFAIYIB8A3AFCiRQBmceKMQAqUCAA9gEOFlJQA3kwBcsBIUw4AviwAUYRhkYBbUiuEBKPCyjCA2gCJG9gLqcO6OOSgAjFf0F6BsaklrjW8hxQUBgQwACuGAL6hiYAdIycmm4eXiiC3joRUYwqRVFMAIwqFQBMAMx0kVCajZrm2RwA9J1QAHoA-BxAA)

Or you can rewrite this signature using reverse-mapped types: [TS playground](https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAggdiAShAxgewE4BMoF4rLrYA8AzsBgJZwDmANFAIYIB8A3AFCiRQBmceKMQAqUCAA9gEOFlJQA3kwBcsBIUw4AviwAUYRhkYBbUivkcoUANoBpKNSgBrCCDS8owgLorhtz500ASjwWDysAIkZw-w4OdDhyKAAjFX5BPQNjUmDcUPNLDAhgAFcMAX1DEwA6RgDOOLQE4CgUQSSdfOUFC0smAEYVPoAmAGY6Hs1xoPqUDgB6OagAPQB+DiA)

Using the technique above you can even benefit from excess property check in the upcoming TS 5.4: [TS playground](https://www.typescriptlang.org/play?ts=5.4.1-rc#code/C4TwDgpgBAggdiAShAxgewE4BMoF4rLrYA8AzsBgJZwDmANFAIYIB8A3AFCiRQBmceKMQAqUCAA9gEOFlJQA3kwBcsBIUw4AviwAUYRhkYBbUivkcoUANoBpKNSgBrCCDS8oogGRQARIx8AuirCtgGcmgCUeCweVn6BnBzocORQAEYq-IJ6BsakUbgx5pYYEMAArhgC+oYmAHSM4YnJqSiCaTrFygoWlkwAjCr9AEwAzHS9mhORzRwA9HNQAHoA-BxJaCnAUCjD7Z29jGa9loyDUCPjkxOWGRcADFALYhgYmAwgjCAAhBwz60A)

**Comment by KabutoYamato** [comment]
i think the problem is that typescript cant know the final type of T because you are telling it  that  params will be {a:T["a"]} but you arent telling from where T type is going to receive its typings so it asumes T["a"] is AnyRecord
if you change it to (params:T) you are telling typescript that the type received in params is the same type as T so it can infere the real type [here](https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAggdiAShAxgewE4BMoF4rLrYA8AzsBgJZwDmANFAIYIB8A3AFCiRQBmceKMQAqUCAA9gEOFlJQA3kwBcsBIUw4AviwAUYRhkYBbUiuEBKPCyjCA2gCJG9gLqcO6OOSgAjFf0F6BsaklrjW8hxQUVAYEMAArhgC+oYmAHSMHJpuHl4ogt46EVGMKsXRjACMKpUATADMdJFQmk2a5pxAA) is the example
