### ISSUE TITLE
Make using symbols from dynamic imports consistent with using symbols from static imports

### ISSUE THREAD

**Issue by nolan-white** [microsoft/TypeScript#57657]
### 🔍 Search Terms

top-level await, dynamic imports, declaration

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Currently, when you use `import()` to import classes, the TypeScript compiler treats the classes as variables which prevents them from being used to declare another variable's type by themselves. Instead, you have to use the `typeof` a class's prototype in order declare another variable's type as that class.

The imported types can still be used with the `new` keyword to call their constructor(s), and when extending them to make subclasses, just like with static imports.

Here is an example of what I have described in code:

```ts
// test.ts

export class Test {
    constructor(
        readonly foo: any) {
    }
}

export class SubTest extends Test {
    constructor(
        foo: any,
        readonly bar: any
    ) {
        super(foo);
    }
}
```
```ts
// dynamic_import.ts

const {Test, SubTest} = await import("./test");

const testA: Test = new Test(''); // error TS2749: Test refers to a value, but is being used as a type here. Did you mean typeof Test?

const testB: typeof Test.prototype = new Test('')

console.log(testB.foo)

const testC: typeof Test.prototype = new SubTest('', '')

console.log(testC.foo)
console.log((testC as SubTest).bar) // error TS2749: SubTest refers to a value, but is being used as a type here. Did you mean typeof SubTest?
console.log((testC as typeof SubTest.prototype).bar)

class AnotherTest extends Test {
    constructor(
        foo: any,
        readonly baz: any) {
        super(foo);
    }
}

const testD: AnotherTest = new AnotherTest('', '');

export {};
```

This is inconsistent with static imports which allow both styles of declaring a variable's type:

```ts
// static_import.ts

import {Test, SubTest} from "./test.js";

const testA: Test = new Test('');

const testB: typeof Test.prototype = new Test('')

console.log(testB.foo)

const testC: typeof Test.prototype = new SubTest('', '')

console.log(testC.foo)
console.log((testC as SubTest).bar)
console.log((testC as typeof SubTest.prototype).bar)

class AnotherTest extends Test {
    constructor(
        foo: any,
        readonly baz: any) {
        super(foo);
    }
}

const testD: AnotherTest = new AnotherTest('', '');

export {};
```

I wouldn't say this inconsistency is wrong since static imports are not a typical `const` or `let` variable, but it's cumbersome to write `typeof ClassName.prototype` every time you want to declare the type of a variable.

It would be nice if the TypeScript compiler could recognize when a class from a dynamic import is being used to declare the type of a variable so that only the class name is needed. Inspecting the imported symbols in DevTools using both static and dynamic imports seems to reveal they are the exact same object, so I thought it might be doable.

**=== EDIT AFTER UPDATING TITLE ===**
_Relevant comment from me in the discussion below_

"I'm not invested in using a `const` as a type, it's just that the only way to do anything with the result of `import()` is to assign it to a `const`, `let`, or `var`, whether you await it or use it in a callback.

What I really want is to be able to use symbols from dynamic imports in the same way I can use symbols from static imports (and maybe that would be a better title for this suggestion). If I do `import {MyInterface, MyClass, myConst} from './my-module'`, I can use `MyInterface` as a type, `MyClass` as a type and a value, and `myConst` as a value. If I do `const {MyInterface, MyClass, myConst} = await import('./my-module');`, I can't import `MyInterface` because there is no runtime value for `MyInterface` and I can only use `MyClass` as a value, whereas I would expect to be able to use them the same way as a static import since that is how it works in vanilla JavaScript."

### 📃 Motivating Example

If you use top-level await for dynamically importing your external dependencies, you would be able to use the imported classes directly as types like you can with static imports, instead of having to use `typeof ClassName.prototype`.

```ts
// modules.d.ts

declare module MyModule {
    export class MyClass {
        readonly myProp: any
        constructor(myProp: any)
    }
}
```
```ts
// example.ts

function getURL(profile: 'dev' | 'prod'): string {
    switch (profile) {
        case 'dev':
            return 'http://localhost:8080/dev.js';
        case 'prod':
            return 'https://example.com/prod.js'
    }
}

const {MyClass} = await import(getURL('dev')) as typeof MyModule;

const myClass: MyClass = new MyClass('Hello world!'); // instead of `const myClass: typeof MyClass.prototype = new MyClass('Hello world!');`

console.log(myClass)

export {}
```

### 💻 Use Cases

1. What do you want to use this for?
I want to make my code less cluttered and esoteric when using types from dynamic imports. As for why I would want to use a top-level awaited dynamic import over a static import where this becomes relevant, it allows me to change the URL of external dependencies based on application configuration or fallback URLs with only vanilla TypeScript.

2. What shortcomings exist with current approaches?
It is inconsistent with how static imports are used despite the underlying objects being seemingly the same.

3. What workarounds are you using in the meantime?
`let myVar: typeof ClassName.prototype;`

**Comment by fatcerberus** [comment]
You could add a type alias to avoid writing the `typeof` expression over and over:
```ts
type Test = typeof Test.prototype;
```

**Comment by nolan-white** [comment]
> You could add a type alias to avoid writing the `typeof` expression over and over:
> 
> ```ts
> type Test = typeof Test.prototype;
> ```

Declaring the class as a type alias prevents it from being extended and from being used with the `new` keyword as a constructor. The compiler throws the opposite error from above: `TS2693: Test only refers to a type, but is being used as a value here.` That does make me wonder if static imports have special handling that allows them to be used as types and values.

**Comment by nolan-white** [comment]
Another thing I noticed is that interfaces cannot be imported using dynamic imports, presumably because they are erased at run time. Trying to import an interface with a dynamic import yields the error `TS2339: Property TestInterface does not exist on type typeof import("module")` even if that interface is exported in the module's declaration file. Obviously static imports must account for the runtime erasure somehow or we simply wouldn't be able to import interfaces. I wonder if that same handling could be applied to dynamic imports?

**Comment by RyanCavanaugh** [comment]
`const` declarations don't create types and it's not really practical for them to do so. In cases like this, you can generally use a top-level `import type { Test } from "./test"`

If every const created a type, this would be hugely breaking because local variable names would start shadowing global type names.

It can't be the rule that *only some* (e.g. classes) `const`s create types, because doing so would create a semantic circularity -- whether or not some symbol resolved to a class might depend on whether a meaning inside the expression resolved to a class; in the worst case this is undecidable and in the best case would make many otherwise-syntactic operations (just look up a value in a table) become unbounded in the amount of type work they'd have to do.

Ad-hoc rules that try to split the difference would make the language very confusing to reason about.

**Comment by nolan-white** [comment]
I see how it would be an issue to allow this behavior from `const`s, though I suppose I put myself in an XY problem here. I'm not invested in using `const` as a type, it's just that the only way to do anything with the result of `import()` is to assign it to a `const`, `let`, or `var`, whether you await it or use it in a callback.

What I really want is to be able to use symbols from dynamic imports in the same way I can use symbols from static imports (and maybe that would be a better title for this suggestion). If I do `import {MyInterface, MyClass, myConst} from './my-module'`, I can use `MyInterface` as a type, `MyClass` as a type and a value, and `myConst` as a value. If I do `const {MyInterface, MyClass, myConst} = await import('./my-module');`, I can't import `MyInterface` because there is no runtime value for `MyInterface` and I can only use `MyClass` as a value, whereas I would expect to be able to use them the same way as a static import since that is how it works in vanilla JavaScript.

Just spitballing here, but would changing the keyword for declaring the symbol be an option? I know vanilla JavaScript only allows `import` at the top of a file, but could TypeScript allow something like `import {MyInterface, MyClass, myConst} = await import('./my-module')`, and then during compilation remove the symbols that are only types and rewrite the statement to `const {MyClass, myConst} = await import('./my-module')`? It's a deviation from JavaScript syntax, but the symbols are declared the same way as a static import so a developer would likely expect they can be used the same way. I assume static imports already use a similar process to this because interface imports disappear from compiled code.

**Comment by andrewbranch** [comment]
> > You could add a type alias to avoid writing the `typeof` expression over and over:
> > ```ts
> > type Test = typeof Test.prototype;
> > ```
> 
> Declaring the class as a type alias prevents it from being extended and from being used with the `new` keyword as a constructor. The compiler throws the opposite error from above: `TS2693: Test only refers to a type, but is being used as a value here.` That does make me wonder if static imports have special handling that allows them to be used as types and values.

I think something must have gone wrong with that experiment; it should work: https://www.typescriptlang.org/play?#code/MYewdgzgLgBA3jASgUwIYBMDKUBOaC2MAvjALwyoDuqAlrDfgA4g5QAUARAGYQcCUAbgBQUAJ6NkSNFlwEyMMRJBcpGVACMANsmx5U+AHSMcIKKfHJhQ4JtQQIMALKiUGXXOQAPKMjDoHrjJ6hHBEQkJezKzwRAJAA

**Comment by nolan-white** [comment]
> > > You could add a type alias to avoid writing the `typeof` expression over and over:
> > > ```ts
> > > type Test = typeof Test.prototype;
> > > ```
> > 
> > 
> > Declaring the class as a type alias prevents it from being extended and from being used with the `new` keyword as a constructor. The compiler throws the opposite error from above: `TS2693: Test only refers to a type, but is being used as a value here.` That does make me wonder if static imports have special handling that allows them to be used as types and values.
> 
> I think something must have gone wrong with that experiment; it should work: https://www.typescriptlang.org/play?#code/MYewdgzgLgBA3jASgUwIYBMDKUBOaC2MAvjALwyoDuqAlrDfgA4g5QAUARAGYQcCUAbgBQUAJ6NkSNFlwEyMMRJBcpGbHlT4AdIxwgo+8cmFDgAG1QQIMALKiUa2ZpjIAHlGRh01hzI2E4IiEhN2ZWeCIBIA

It works in that example because it uses the previously declared `const` of `Test` for extension instead of the `type`. When I experimented with it I tried declaring the type in its own file where the import is awaited so that I only needed to make the type alias once for the whole project and then import that type normally everywhere else. Unfortunately that doesn't work, so you would need to define the type in each file you use it in. This would prevent writing `typeof Test.prototype` everywhere, but would introduce additional overhead of having to rename all of your type aliases if you renamed the class. Presumably most IDEs wouldn't do it for you because its meant to be an alias, not a redeclaration of the class type. In IntelliJ it does not.

**Comment by fatcerberus** [comment]
Ah, so you mean something like:

```ts
const { Foo } = await import("foo");
type Foo = typeof Foo.prototype;

export { Foo };
```

I think there might be an existing issue about that but yes, IIRC it's a known bug that that doesn't work.

**Comment by nolan-white** [comment]
Bumping this as I'm not sure if this got looked at again after the title and description was updated.
