### ISSUE TITLE
Class static side incorrectly extends mapped type in generic function

### ISSUE THREAD

**Issue by Aetherall** [microsoft/TypeScript#57674]
### 🔎 Search Terms

extending mapped type
generic mixin extends
Class static side incorrectly extends base class static side

### 🕗 Version & Regression Information

- Always have been this way
- This is a loss of typing information

### ⏯ Playground Link

https://www.staging-typescript.org/play?target=7&ts=5.5.0-dev.20240307#code/MYewdgzgLgBArjAvDAPKSsDKMCmAPKHMAEwhmgCcBLMAcwD4AKCALhkwEol6YBvAKBhCYAQwBGlEcFjAANiIhkA7nwC+g4RRxQ4FMDBUKYUAJ4AHHCABmBmADI+MANoBpGDXYBdNm-Xr+-FZwYNJU4DBWaODQ7LgERKTkUNR0TKzsXALCohLJUjLyijAAbnGEJGRwKJhpmerZWjp6Jfz+VowA5ITQHRz8QA

### 💻 Code

```ts
declare const u: <S extends string>() => { [K in S]: string } & (new () => any)

function f<const S extends string>(s: S) {
    abstract class v extends u<S>() {}
    return v
}

f('test').test

```

### 🙁 Actual behavior

Class static side 'typeof v' incorrectly extends base class static side '{ [K in S]: string; }'

### 🙂 Expected behavior

I dont really know, maybe it should defer the checking to when the concrete class is declared ?

In any case, the error message seems a little off to me

There is an existing error for the constructor return type:
`Base constructor return type '{0}' is not an object type or intersection of object types with statically known members`
Maybe we can use a variant here:
`Base constructor '{0}' is not an object type or intersection of object types with statically known members`

Tho I really need the checking to be deferred to the concrete declaration in my use cases

### Additional information about the issue

I played a bit debugging the checker.ts file, it seems like in the case of a known static key in baseclass, it will go through the `propertiesRelatedTo` method, which even tho `v` is not yet the full extended type, then will use `getPropertyOfType` on v to retrieve the same property symbol existing on the baseclass.

Couldn't we do the same thing with mapped types ? Something like `getMappedTypeOfType` which would then consider the mapped type of the result of `u` as something of its own since it extends it.

But even if we do that, we cannot ensure the caller of the generic function would not use types that would make the `v` declaration conflict with the `u` one. So IMO to support this use case we would need to only allow this on an abstract class, and defer some of the checks to the concrete class. Then we should be fine since we cannot construct abstract class right ?

I can provide more code samples.
I am building a typesafe library who has to use those features, so I'm full of use cases about recursive types that dont succeed as they should ( even with the ongoing PR about recursive types ) and other limitations (100 as any casts left on a 1000 lines library)

I am stunned how nice I can make my library api with the new features landing last year up until unmerged PRs I checked out. Great work <3

**Comment by RyanCavanaugh** [comment]
We can't defer errors inside the body of the function until it gets called. That doesn't really work.

I'm not sure how this function can *not* be an error. It's unsound to many calls:
```ts
function f<const S extends string>(s: S) {
    abstract class v extends u<S>() {
        foo: number = 3;
    }
    return v
}

f('foo')
```
It's also not going to ever be able to do the right thing in the presence of legal aliasing:
```ts
// No way for f to know about "bar"
f('foo' as 'foo' | 'bar');
```
Basically you need a downcast here if you want this to be accepted, because it's just doing unsafe things

**Comment by Aetherall** [comment]
Hi Ryan, thanks for answering the issue

> That doesn't really work

As in `type error bubbling to check generic is not a thing`
Or as in `it would not work anyway because it fundamentally makes no sense` ? 

> I'm not sure how this function can not be an error. It's unsound to many calls

If we can defer the errors (and if I am not mistaken) this function can actually produce a safe output, depending on the generic type
If we cant defer the errors inside the body, it should definitely be an error, but i don't think the current one is correct relative to how known static members are checked. (see additional information)

> Basically you need a downcast here if you want this to be accepted, because it's just doing unsafe things

What do you mean by a downcast ? Forcing the return type of u() to a statically known value ?
Or maybe I can coerce the generic into not containing keys defined in typeof v

Thanks for your explanations

**Comment by fatcerberus** [comment]
TypeScript generics don’t work like C++ templates - deferring type checking of the implementation of the function until it’s actually called is not a thing.  As in, e.g. Haskell, the implementation of a generic function is supposed to be valid *for all types `T`* and that’s what the compiler is trying to verify.
