### ISSUE TITLE
How to force compiler to check that library imported?

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#5768]
I use "Immutable-Js" in ny project. My project targets to "es6". Typical module looks like:

```
import * as Immutable from "immutable"

let map = Immutable.List<number>()
```

But sometimes I miss the `import` statement, and typescript silently compiles that. How to force to check that library is imported?

**Comment by kitsonk** [comment]
It should be throwing an error on the 3rd line.  TypeScript will emit on error, even if it isn't valid unless you specify the `noEmitOnError`.  If the compiler still thinks it is valid, without defining `Immutable` then you must have something declared in the project that defines that in the global scope (like you are including a `.d.ts` that is saying it is in the global space).

**Comment by Strate** [comment]
Yes, immutable's d.ts file contains `declare module Immutable`. Is it breaking?

**Comment by myitcv** [comment]
@Strate see https://github.com/facebook/immutable-js/pull/642

**Comment by Strate** [comment]
@myitcv merci!
