### ISSUE TITLE
Combining `importHelpers: true` and `module: preserve` results in TS2354

### ISSUE THREAD

**Issue by jgoz** [microsoft/TypeScript#57688]
### 🔎 Search Terms

TS2354 This syntax requires an imported helper but module 'tslib' cannot be found.
importHelpers
module
preserve

### 🕗 Version & Regression Information

Occurs in 5.4.2 and in ^5.5.0-dev.20240307.

- This changed between versions 5.3.3 and 5.4.2

^ This is not technically true because `"module": "preserve"` wasn't added until 5.4.2.

### ⏯ Playground Link

https://github.com/jgoz/typescript-module-preserve-issue

### 💻 Code

```ts
export class Foo {
  #foo: boolean;

  constructor() {
    this.#foo = false; // This syntax requires an imported helper but module 'tslib' cannot be found. ts(2354)
  }

  foo(): boolean {
    return this.#foo;
  }
}
```

```json
{
  "compilerOptions": {
    "moduleResolution": "bundler",
    "module": "preserve",
    "importHelpers": true,
    "outDir": "dist",
    "target": "es2021"
  }
}
```

### 🙁 Actual behavior

Error message indicates that tslib is not present, but it is.

### 🙂 Expected behavior

No error.

### Additional information about the issue

Not sure if this is a TS issue or an issue with the export maps in `tslib`.

**Comment by andrewbranch** [comment]
Have a fix on the way from the report at https://github.com/microsoft/TypeScript/issues/58325
