### ISSUE TITLE
Narrowed type not "carried" iteratively

### ISSUE THREAD

**Issue by eranhirsch** [microsoft/TypeScript#57690]
### 🔎 Search Terms

narrow, generic

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.4.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTAEF5NB1B5AlA0gZQpdH0CgsBMCmAxgDYCGATvqAGYCuAdoQC4CWA9vaCwM4AKZLerABGAKyJMAjAAosoULlJNSALlAMA1vTYB3egBosASjWLlXbqHhE25XAB5e5NgAd85JgE9E+T-vX0Wrr0AHwA3DgEJBRUhBzcTKAAtp4iopJqmtp6ESzUoNI8-KSCaRIyKWmSRkagAN5y8jS2BXH0CaAavqBs+QDaAESkA-4DwiOgA4QDALq1DU1NbR0E+G7kEMmpYpJ9XZ4zEYvyIIsAegD8jYvLiavrPp6W4BbFpWLl0vfutRegZcwAHT7bhffBrH6gNR9Q7XUAAXywiKwp3QoAAIrAAKLIAByABUYAhEGhMGTsKdYPRiJ4FHlqO58IwqMJ8EwdODOEwABZUABMXCSLmIlh4oB5VAA5kz3CxCKBCYJxbzxZ43P58AA3JmgHS8zgsRI8egAckStG4+FwgJtkSIZEoNAYzHYBr4AiEH2YfPs+JCsnkZlUASCekMJgUSlIFisNjsjmc6y8j38WWC4Tt0Udty2aT5mUC2XouXyhXdJU94m90kqYj5NXqcOoLWkOf2PX6QwmY270zmjeOoBz3w2L1roj5e18sMHpyalzh8mH4Ievmerw9AKYfLBEPIv3+XqYwLXu-WtWhM6aiMRQA

### 💻 Code

```ts
// === WORKS =============

declare function isPlainObject1(
  data: unknown,
): data is Record<PropertyKey, unknown>;

declare const myObj1: unknown;
if (isPlainObject1(myObj1)) {
    for (const key of ["a", "b", "c"]) {
      const deeper = myObj1[key];
      //    ^?
      const deeperKeys = isPlainObject1(deeper) ? Object.keys(deeper) : [];
    }
}

// === DOESNT WORK ================
// Only difference between the 2 impls is the generic T in the type, even when it isn't used...

declare function isPlainObject2<T>(
  data: unknown,
): data is Record<PropertyKey, unknown>;

declare const myObj2: unknown;
if (isPlainObject2(myObj2)) {
    for (const key of ["a", "b", "c"]) {
      const deeper = myObj2[key];
      //    ^?
      const deeperKeys = isPlainObject2(deeper) ? Object.keys(deeper) : [];
    }
}
```

### 🙁 Actual behavior

The `deeper` variable, which is nested deeper from the narrowed type is inferred as `any`.

### 🙂 Expected behavior

It is the result of accessing a prop on a `Record<PropertyKey, unknown>` so is expected to be `unknown`.

### Additional information about the issue

I maintain the Remeda utility functions library, I just got this reported here: https://github.com/remeda/remeda/issues/559 and there are additional anecdotal reports that upgrading to typescript 5.4 breaks several of our types.

I couldn't find a reasoning to this issue, including any new changes to Typescript in 5.4 which might explain it.

I'm not sure my title makes sense for this bug, as I don't fully understand what's going on here, or even how to build a truly *minimal* example.

**Comment by RyanCavanaugh** [comment]
Bisects to #57358

**Comment by mxschmitt** [comment]
Looks like [Playwright](https://github.com/microsoft/playwright) is also affected by this.


[Minimal Reproduction on the Playwright](https://www.typescriptlang.org/play?ts=5.5.0-dev.20240311#code/MYewdgzgLgBA1gSQLYAcA2BLYGoCURoCmAQgJ4AqAhgOYBylShAXDAN4wDaUN9jL0AJwxhqAXRYAKZjACiRRmCgBKGAF4AfDEHDqMAD4wwAVzRoYAXzVsAUOYDc166Eiw4ABQGEIhRZSgZwBDAAC0IhbjBgQjdKT0UIFnYuHgZpbRFxLSghEQ5RCytWaxgYAHIAEXLSlg4KgBlSgBoy8oQANVLRRuKW9urOes7ukoryftryhuaKvq6e0rqEcdKAeSmygFUGuZHyYhXygE1l8gBBYjqZIfnyKprS8lxr3YAxFZWx+7OLq52y8gAEicnn8HgCZKc7gNvpdnv8nl9wZCmv99kcUQ83h8MTDft17I5CAAPFAgASwABmRki-nAMBQsR8UDkhAUUBWAgAysFKAATEAAdwBIGgUnkTJYLLZSkl4sU+hg1N5hApwkIvJsJQwFJgYtZTIAdAy4sy5coeiVPFAjAIwDBCGajYzFFKmQ4tTqJABCB36xROk20EDKpQWmBWm1gd0wbW631sgNMoPKg1gYOEcikFCENSqVQwACMBZgAHoAFQwZOEA3lFYAYQ2AFkZLRyAB9F64U4AcWbrbbtAOMhgZZLMAAZOO447jUn0zBKBAYNy+YL8CBlAbgiLzSVLYRrbbp36oInFFWF0uV-yBevN9voNGI0elSq1byHOZHNYqTSAnbqAPZB0CwHBTiESh8CIPU2VlE8ZSyHJdAMYxTE1Usx1deIYApAQQCQGAoFCLQADddDAVIIAZKIYH5QwNxgHkSJzIwUGzARgEXHNuDoVIDR6ZxoBjVBMGwPACBzfNEBE0DxKIMgqF4xgOHjQ0eN4asoBADY2LCOsuIkJRRAAfgNGCmRUPQDFKUpo1jb0MBksSoMIUM93DA9I0MEw0GjEsxyCUJwnpTxvF8Wk7TwogYAFUJIsIABHIwME8Xl+JKfzGKgKAUASfyBQKg0BQAZgNMlqBLR4SwFSgMAAWliDBKDqgsDQAJhLABiZwKVEqA21CggjAitsUFCpk-H-Ns0zAQgeiIWBKEiLwtIEOC2QVVCzHzVTFGjWKMGiiQlqiaAyRUIp3ME2BZ3lfNbtNE8OWvQVhVFE6VvO6MSmu+lnSgJcpI8LwJoiwKwhwD6YhNCAOA+s6BANdTUlEb6Y09L0HqXKyYEx-79AMPGYYNYRgDQIxlQgCQHqRlJGCUNz3JgAAjTxKDgNH4dWqwHujL990PO1HJA5yJM-IA)
Bisect: https://github.com/microsoft/typescript/compare/2a0edf7949ad8427e3ef233a4c549ecbe32953e1...db3d54ffbc0a805fbdd5104c5a5137d7ca84420a
5.4.0-dev.20240214 bad
5.4.0-dev.20240213 good
