### ISSUE TITLE
Narrow generic mapped argument

### ISSUE THREAD

**Issue by KnightSlayer** [microsoft/TypeScript#57691]
### 🔍 Search Terms

"type narrowing for mapped type", "type narrowing for mapped argument", "type narrowing for generic mapped argument"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I came across a case where the type could obviously be narrowed down. but for some reason typescript doesn't support this. it was a frustrating experience

### 📃 Motivating Example

Here is code example

```ts
type T = 'a' | "b"
type M = {
  a: 1,
  b: 2
}

function f1(a: 'a') {}
function f2(a: 1) {}

function f<TT extends T>(t: TT, p: M[TT]) {
  switch (t) {
    case "a": {
      f1(t);
      f2(p); // Argument of type '1 | 2' is not assignable to parameter of type '1'.  Type '2' is not assignable to type '1'.
      break
    }
  }
}
```

### 💻 Use Cases

1. I want to write more clear code without workarounds
2. Current approach isn't intuitive
3. I'm using type casts as workaround in the meantime

**Comment by MartinJohns** [comment]
The error is correct. It's perfectly valid to write this call:

```typescript
f<'a' | 'b'>('a', 2);
```
