### ISSUE TITLE
Build mode output is not regenerated after being deleted from the filesystem

### ISSUE THREAD

**Issue by disog** [microsoft/TypeScript#57709]
### 🔎 Search Terms

build, mode, output

### 🕗 Version & Regression Information

- I'm using the latest version as of now (5.4.2)
- I did not have time to look for previous versions

### 💻 Code

Running `tsc -b` on a project whose output has been deleted from disk does not regenerate that output. For example, if my project is a directory containing an empty `test.ts` file and a `tsconfig.json` like the following:
```jsonc
{
  "compilerOptions": {
    "incremental": true,
    "skipLibCheck": true,
    "tsBuildInfoFile": ".tsbuildinfo",
  }
}
```

Running `tsc -b .` the first time produces the file `test.js`. If I delete that file and run the command again, nothing happens. If I edit the source and run the command again, then the `test.js` file is generated as expected.

This applies to `.d.ts` and `.map` files as well. Additionally, if output directories are specified, like so:
```jsonc
{
  "compilerOptions": {
    // same as above, plus
    "outDir": "./lib",
    "declarationDir": "./types",
    "declaration": true,
    "declarationMap": true,
  }
}
```

Then the `.d.ts` file does not get regenerated (after being deleted from disk) even if I edit the source file.

### 🙁 Actual behavior

The output files do not get regenerated after being deleted from disk.

### 🙂 Expected behavior

I'd expect alll output files to be regenerated after being deleted from disk.

**Comment by MartinJohns** [comment]
Duplicate of #30602.

**Comment by disog** [comment]
Thanks!
