### ISSUE TITLE
Wrong multiline parenthesis indent (JS)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#5771]
_From @alexanderby on November 19, 2015 9:27_

When formatting JavaScript the indent of right parenthesis (that is placed on different line) is too large.
This is expected to be
```javascript
function (
    arg1,
    arg2
) {
    if (
        arg1
        && arg2
    ) {
        //...
    }
}
```
but actually is
```javascript
function (
    arg1,
    arg2
    ) {
    if (
        arg1
        && arg2
        ) {
        //...
    }
}
```

_Copied from original issue: Microsoft/vscode#181_

**Comment by SaschaNaz** [comment]
See also #3436.

**Comment by mhegazy** [comment]
looks like it is fixed in latest. thanks @SaschaNaz

**Comment by alexanderby** [comment]
@mhegazy @SaschaNaz I've reported this issue for [VS Code](https://github.com/Microsoft/vscode/issues/181). The bug appears when formatting JavaScript and still remains.

**Comment by jrieken** [comment]
VS Code uses the TS formatter even for JS, that's why this bug is here

**Comment by mhegazy** [comment]
@alexanderby the issue has been fixed in the latest formatter, the next time VSCode picks up the update it should be fixed.

**Comment by alexanderby** [comment]
There is no issue when editing TypeScript, but JavaScript. Currently app uses TS1.6, so I've downloaded TS1.7.3 package and put it into "resources\app\extensions\typescript\server" folder. [Comment issue](https://github.com/Microsoft/TypeScript/issues/5772) has gone after this when formatting TypeScript, but JavaScript still have both issues.

**Comment by SaschaNaz** [comment]
I found resources\app\out\vs\languages\typescript\common\lib\typescriptServices.js and it says `var toolsVersion="1.5"`.
