### ISSUE TITLE
Functional Instantiation

### ISSUE THREAD

**Issue by sanskar-19** [microsoft/TypeScript#57713]
### 🔎 Search Terms

functional instantiation, es5

### 🕗 Version & Regression Information

- This is a bug

### 💻 Code

```
interface UserProfile {
    fName: string;
    lName: string;
    printFirstName: () => void;
    printLastName: () => void;
}

// Define user class
function User(this: UserProfile, fName: string, lName: string) {
    if (!(this instanceof User)) {
        return (new User(fName, lName));
    }

    this.fName = fName;
    this.lName = lName;
}

// Define prototype for print First name
User.prototype.printFirstName = function () {
    console.log(this.fName);
}

// Define prototype for print  Last name
User.prototype.printLastName = function () {
    console.log(this.lName);
}

const user = new User('John', 'Doe');
```

### 🙁 Actual behavior

`new` expression whose target lacks a constructor signature. Switching back to normal JS works as expected.

### 🙂 Expected behavior

Should compile without issues. It should point to the constructor by default present in the prototype object.

### Additional information about the issue

Typescript config : 

```
{
  "compilerOptions": {
    "target": "es2016",                             
    "module": "ESNext",                             
    "esModuleInterop": true,                        
    "forceConsistentCasingInFileNames": true,       
    "strict": true,                                 
    "outDir": "build",
    "skipLibCheck": true
  }
}
```

_No response_

**Comment by MartinJohns** [comment]
This is working as intended. See https://github.com/microsoft/TypeScript/issues/13013#issuecomment-662515967.

**Comment by sanskar-19** [comment]
> This is working as intended. See [#13013 (comment)](https://github.com/microsoft/TypeScript/issues/13013#issuecomment-662515967).
> 
> You can add an explicit `this` parameter.

<img width="1019" alt="image" src="https://github.com/microsoft/TypeScript/assets/63312055/4faab24a-ded7-415e-a2fe-07385098b9ca">

Can you please explain this !?

As far as I know, the constructor should have been by default referred to the function prototype constructor property.

**Comment by RyanCavanaugh** [comment]
TypeScript only supports classes written with the `class` keyword.
