### ISSUE TITLE
error TS2536: Type 'key' cannot be used to index type 'Store<string, S, G, {}>

### ISSUE THREAD

**Issue by coader** [microsoft/TypeScript#57712]
### 🔎 Search Terms

error TS2536

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
error TS2536: Type 'key' cannot be used to index type 'Store<string, S, G, {}>'.
354 [key in Keys]: () => Store<string, S, G, {}>[key];
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in ../../node_modules/.pnpm/pinia@2.1.7_typescript@5.4.2_vue@3.4.21/node_modules/pinia/dist/pinia.d.ts:354
```

### 🙁 Actual behavior

throw error TS2536

### 🙂 Expected behavior

it's ok in 5.3.3

**Comment by Andarist** [comment]
Please provide a repro case. Without it, the issue can't be investigated.

**Comment by dten** [comment]
myself and some others have been encountering this error upgrading to 5.4.5 https://github.com/vuejs/pinia/discussions/2605

here is a repro. this job first typechecks with 5.3.3 then installs typescript 5.4.5 and typecheck then fails

https://github.com/dten/pinia_ts_repro/actions/runs/8710652508/job/23893007875

**Comment by tilleps** [comment]
Discussion about this issue has been posted here: https://github.com/vuejs/pinia/discussions/2605

I posted a workaround: https://github.com/vuejs/pinia/discussions/2605#discussioncomment-9851659
