### ISSUE TITLE
`as const` does not always narrow array literals to tuple types

### ISSUE THREAD

**Issue by jflatow** [microsoft/TypeScript#57727]
### 🔎 Search Terms

as const, narrow, widen, tuple

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `as const` narrowing.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoGVkG8BQzkgQDuyAFAHSVxQDmAzgFzJwgCeA2gLoCUTLrAbhwBfHDlCRYiFAEF0AHgAKyCAA9IIACZ1ki9AD5seZOzhM6YKKBqcmAJQhxNAexAAbVjKhQ4reQGsIVmcYXX0hUXFwaHgkXUxcfHYAB3NLa1s0dAixMFZk2Vo6eVQVdQgtHQcnVw8vHz9A4NDFfQAaXTKNbXjDAF40Loqe9lAYaGQAMWAoCw7KcjGJhwtOYwB+E2nZsCHK5CaQzs2ASRALFiRUfIgldm3VwyZCADdoecovenkV3bVuqqOFzuTzeXwBIJHVrITa-ZBMLgdVprfAIzhCMQSGLSZB2eQyPY9ORKdqdf7DHR6QyJZAweQAEUJOkOoRk+lImiY9I6ZmQX2KMnY9M4SP0vGQL2cwE0ORwCFcFmQqmQAxpACMEQByACOms4zB07B1eo6AHpTSpvM4oMgiMAwAALZwAV12cENxpRyAQWt1IpEBu9CrAQnl512rBV2GQ2qYADlnQBbNUTYSBsMWDEwZ0gBBgYCuZCQCykKD2eR5ApHVQdSsQI6sMVGfBQcgwUiatWajrsACsPByQA

### 💻 Code

```ts
interface TS {
  new (...args: any[]): any;
}

interface AS<P extends PS> {
  [a: string]: ReadonlyArray<keyof P>;
}

interface PS {
  [p: string]: TS;
}

type Args<T extends ReadonlyArray<keyof P>, P extends PS> = T extends [infer First, ...infer Rest]
  ? [First extends keyof P ? InstanceType<P[First]> : never, ...Args<Rest extends ReadonlyArray<keyof P> ? Rest : [], P>]
  : [];


interface R<A extends AS<P>, P extends PS> {
  f<D extends keyof A>(d: D, a: Args<A[D], P>): void;
}

const x = {
  b: ['q'] as ['q'], // error without as ['q']
  c: ['q'],
} as const;
const y = { q: Number } as const;

function test(r: R<typeof x, typeof y>) {
  r.f('b', [5]);
}
```

### 🙁 Actual behavior

Without the `as ['q']` cast (see comment in code), the code fails to compile, presumably due to not correctly inferring the narrow tuple type and inferring an array type instead.

### 🙂 Expected behavior

When using the `as const` assertion on an object literal, TypeScript is expected to infer the most specific literal types for all properties, including narrowing array literals to tuple types. However, in the context of a mapped type and conditional type, this behavior seems to be inconsistent, leading to a type mismatch error.

### Additional information about the issue

The issue occurs in the context of mapped types (`AS<P>`) and conditional types (`Args<T, P>`). The `as const` assertion is expected to provide the most specific literal types, but it fails to narrow the array literal to a tuple type automatically, leading to the type mismatch error.

Possible Solution:
Ensure that the `as const` assertion consistently narrows array literals to tuple types within object literals, even in the context of mapped types and conditional types, aligning with the expected behavior described in the TypeScript documentation.

**Comment by Andarist** [comment]
I didn't analyze what you are trying to achieve here but I was able to fix ur problem by adding `readonly` to your inference target in `Args`: [TS playground](https://www.typescriptlang.org/play?ts=5.4.2#code/JYOwLgpgTgZghgYwgAgCoGVkG8BQzkgQDuyAFAHSVxQDmAzgFzJwgCeA2gLoCUTLrAbhwBfHDlCRYiFAEF0AHgAKyCAA9IIACZ1ki9AD5seZOzhM6YKKBqcmAJQhxNAexAAbVjKhQ4reQGsIVmcYXX0hUXFwaHgkXUxcfHYAB3NLa1s0dAixMFZk2Vo6eVQVdQgtHQcnVw8vHz9A4NDFfQAaXTKNbXjDAF40LoqeqEcXd1YTY1AYaGQAMWAoCzbjSnIZuYcVnE5jAH4p-GOFpYshyuQmkM7DgEkQCxYkVHyIJXZF5bBOQyZCABu0FWJ3w6y89Hk2zAFx61XGdW8vgCQRurWQh2hyCYXA6rRBxz2+BxnCEUUksRQdnkMlhOjkSnanTU3R0ekMiWQMHkABE6VdUaEZPpSJomDyOmZkBDijJ2DzOHj9LxkADnMBNDkcAhXOdVMgBpyAEY4gBEAEdTYrjAgzZbrcJmDodY8wEIXedJobkOamAA5ACuAFsjXNHXBnbq3WIYAGQAgwMBXMhIBZSFB7PI8gUbqoOtmIDdWMqjPgoOQYKRTUbTR12ABWHg5IA)

**Comment by RyanCavanaugh** [comment]
I don't see a defect demonstrated here. The additional `as` changes the type of the expression and as a result, type computations change.

It's the same as the difference between these two declarations:
```ts
/* explicitly annotated */
declare const x: { readonly b: readonly ['q'], readonly c: readonly ['q'] }
```
vs
```ts
/* inferred type from 'as' */
declare const x: { readonly b: ['q'], readonly c: readonly ['q'] }
```

**Comment by jflatow** [comment]
> I didn't analyze what you are trying to achieve here but I was able to fix ur problem by adding `readonly` to your inference target in `Args`: [TS playground](https://www.typescriptlang.org/play?ts=5.4.2#code/JYOwLgpgTgZghgYwgAgCoGVkG8BQzkgQDuyAFAHSVxQDmAzgFzJwgCeA2gLoCUTLrAbhwBfHDlCRYiFAEF0AHgAKyCAA9IIACZ1ki9AD5seZOzhM6YKKBqcmAJQhxNAexAAbVjKhQ4reQGsIVmcYXX0hUXFwaHgkXUxcfHYAB3NLa1s0dAixMFZk2Vo6eVQVdQgtHQcnVw8vHz9A4NDFfQAaXTKNbXjDAF40LoqeqEcXd1YTY1AYaGQAMWAoCzbjSnIZuYcVnE5jAH4p-GOFpYshyuQmkM7DgEkQCxYkVHyIJXZF5bBOQyZCABu0FWJ3w6y89Hk2zAFx61XGdW8vgCQRurWQh2hyCYXA6rRBxz2+BxnCEUUksRQdnkMlhOjkSnanTU3R0ekMiWQMHkABE6VdUaEZPpSJomDyOmZkBDijJ2DzOHj9LxkADnMBNDkcAhXOdVMgBpyAEY4gBEAEdTYrjAgzZbrcJmDodY8wEIXedJobkOamAA5ACuAFsjXNHXBnbq3WIYAGQAgwMBXMhIBZSFB7PI8gUbqoOtmIDdWMqjPgoOQYKRTUbTR12ABWHg5IA)

Thanks, that indeed fixes the error.

**Comment by jflatow** [comment]
> I don't see a defect demonstrated here. The additional `as` changes the type of the expression and as a result, type computations change.

Perhaps, but the change in type computations is at least odd to me. By adding the `as ['q']` it does indeed seem to change from interpreting as a tuple to an array in the given context. But the additional `readonly` seems to prevent that. I'm confused why this is happening without it but glad it makes sense to you.
