### ISSUE TITLE
Wrong comment indent in multiline expressions (TS, JS)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#5772]
_From @alexanderby on November 19, 2015 9:35_

When formatting JavaScript or TypeScript, comments placed between parts of multi-line expressions are placed wrong.
Expected to look like
```javascript
doStuff()
    .then()
    // Comment
    .then();
```
but actually is
```javascript
doStuff()
    .then()
// Comment
    .then();
```

_Copied from original issue: Microsoft/vscode#184_

**Comment by SaschaNaz** [comment]
Duplicate of #4563?

**Comment by mhegazy** [comment]
indeed. thanks @SaschaNaz!. it should be fixed in latest.
