### ISSUE TITLE
how do I use external JS module without using .d.ts or writing one myself?

### ISSUE THREAD

**Issue by helios1138** [Microsoft/TypeScript#5774]
Since type definitions for external modules are sometimes either missing or outdated or in conflict with each other - is there a way to just suppress the checks for specific module to avoid `TS2307: Cannot find module ***` error?

**Comment by kitsonk** [comment]
The easiest way, is to just to declare an ambient module yourself and put it a project `.d.ts`:

```typescript
declare module 'foo/bar' {
	export let fooBar: any;
}
```

**Comment by helios1138** [comment]
@kitsonk, thanks.

In case anyone has the same problem: my case was a module that had a default export which is a function so apparently this works:

```ts
declare module 'foobar' {
  export default function (...any: any[]): any;
}
```

**Comment by kitsonk** [comment]
That is a good point of why you wouldn't want to just turn it off, because having at least an idea of what the module returns (e.g. a function or a object) is useful and then lets you potentially incrementally decorate the ambient module as you want to in the future.

**Comment by helios1138** [comment]
Makes sense. Ability to be able to incrementally decorate modules is exactly what I was looking for
