### ISSUE TITLE
No auto-import from aliased symbol from ts files in js files

### ISSUE THREAD

**Issue by jasonlyu123** [microsoft/TypeScript#57740]
### 🔎 Search Terms

default export
auto-import
barrel export

### 🕗 Version & Regression Information

- This changed between versions __5.3__ and __5.4__

### ⏯ Playground Link

Reproduction repository instead of playground because it needs at least 2 files. One in ts and one in js.
https://github.com/jasonlyu123/auto-import-aliased

### 💻 Code

```ts
// foo.ts

export default function foo() {}

function foo2() {}
export { foo2 }
```

```ts
// index.js
foo
// ^trigger completion here
```

### 🙁 Actual behavior

No auto-import to import the function `foo` and `foo2`

### 🙂 Expected behavior

Has auto-import like in 5.3.

### Additional information about the issue

This only happens in js files when trying to auto-import values from a ts file and the symbol has some alias or is a default export. This seems to have to do with #53619. In another check for type-only-location, the symbol flags are combined with flags from the aliased symbol and the symbol has flags like `class` and `function`.

**Comment by RyanCavanaugh** [comment]
`foo` not being offered is correct; this is not an externally-visible name. `foo2` should be offered, though

**Comment by dummdidumm** [comment]
Why is `foo` not externally visible? If I type `foo` inside a `.ts` file, I get offered the default import as autocompletion. I would expect the same to be true in a `.js` file.
