### ISSUE TITLE
Can't paste in playground anymore

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#57759]
### 🔎 Search Terms

Playground copy paste

### 🕗 Version & Regression Information

Playground bug

### ⏯ Playground Link

https://www.typescriptlang.org/play?filetype=js#code/FA0QwZwE1Eg

### 🙁 Actual behavior

Cannot paste anything in playground

### 🙂 Expected behavior

Paste in playground either Ctrl+V or right click "Paste"

### Additional information about the issue

No console errors, Chrome 122, Windows 11

**Comment by MartinJohns** [comment]
Works on my machine. Perhaps you accidentally disabled pasting for that website in your browser?

In general, this is the repository for the playground: https://github.com/microsoft/TypeScript-Website
