### ISSUE TITLE
bitwise operations in if structure

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#5775]
_From @gilberto389 on November 24, 2015 1:30_

if(window.innerWidth < 1600 <b>&</b> window.innerWidth > 1200){
....
}

the "<b>&</b>" It allowed in javascript. It is a bitwise operation
![Uploading bitwise.png…]()

http://diyo.netai.net/bitwise.png

_Copied from original issue: Microsoft/vscode#526_

**Comment by RyanCavanaugh** [comment]
As the error message suggests, `&&` is by far the better operator to use for booleans. `&` is dangerous to use for logical operations.
