### ISSUE TITLE
Incorrect variable renaming when two default exports in a file

### ISSUE THREAD

**Issue by ahkhanjani** [microsoft/TypeScript#57754]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2 (user setup)
- OS Version: Windows_NT x64 10.0.22631

I accidentally came across this bug. Although this is not valid JavaScript code but the way VS Code handles it is unexpected.

Steps to Reproduce:

1. Create a `.js`/`.ts` file.
2. Create two functions with distinct names, both with default export.
```ts
export default function a() {}
export default function b() {}
```
3. Go to the second function and globally rename it using <kbd>F2</kbd>.

Instead of the function we were trying to rename, the first default export gets renamed.

**Comment by mjbvz** [comment]
The code is invalid so I'm not sure there is a correct behavior for rename. In TS or with JS error reporting, you'll see 

![Image](https://github.com/microsoft/TypeScript/assets/12821956/37d35f06-2c8f-4783-9fdd-d96b277c26a1)

**Comment by ahkhanjani** [comment]
> The code is invalid so I'm not sure there is a correct behavior for rename. In TS or with JS error reporting, you'll see

Yes. I just found it a bit strange. I would expect it to at least error with something like this:

![Screenshot 2024-03-13 005934](https://github.com/microsoft/TypeScript/assets/72540492/08444dac-1afe-4a14-91ed-55f4b43f779a)

Or... perhaps rename the actual function?
