### ISSUE TITLE
TypeScript does not recognize getters with union types

### ISSUE THREAD

**Issue by wesleycho** [Microsoft/TypeScript#5776]
I have a particular setup

```js
class Foo {
  get bar() {
    return 'foobar';
  }
}

class Bar {
  get foo() {
    return 'foobar';
  }
}

class Foobar {
  data: Foo | Bar;

  baz() {
    if (isFooInstance(this.data) {
      return this.data.bar;
    }
  }
}
```

TypeScript throws an error in this situation saying `bar` does not exist on `Foo | Bar` - this is incorrect behavior IMO, especially if I have already screened out what type it is via other mechanisms.

**Comment by RyanCavanaugh** [comment]
Duplicate of #3812

**Comment by wesleycho** [comment]
Ah sorry, couldn't find anything mentioning union types in particular when searching for issues.
