### ISSUE TITLE
import suggestion from b to sibling a defined in paths compilerOptions

### ISSUE THREAD

**Issue by kebeclibre** [microsoft/TypeScript#57762]
### 🔎 Search Terms

sibling import node_modules parent paths

### 🕗 Version & Regression Information

Version 5.3.2
VSCode 1.87.2

### 💻 Code

Hello,

Have two JS projects:
```
- a
   jsconfig.json
   package.json
   node_modules
   feature1/
       f1.js

- b
   jsconfig.json
   package.json
   feature2/
       f2.js
   node_modules 
```
Given that `@odoo/owl` is in node_modules, defined as devDependencies in both package.json of a and b.

jsconfig.json in project b looks like:
```js
{
    "compilerOptions": {
        "moduleResolution": "node",
        "baseUrl": ".",
        "target": "ES2022",
        "noEmit": true,
        "disableSizeLimit": true,
        "paths": {
            "@feature1/*": ["../project_a/feature1/*"],
       }
}
```

f1.js:
```js
import { Component } from "@odoo/owl",
```

f2.js:
```js
import { someThing } from "@feature1/f1" 
import { Component } from "@odoo/owl",
```

Open only project B in VSCode (well or both, that doesn't matter)

### 🙁 Actual behavior

What we observe is that `@odoo/owl` is not proposed for auto imports in project_b, and that looking for definitions redirects to the module in project_a/node_modules.

We made a fix in our code, that re-defines the type "@odoo/owl" in project b as:
```ts
declare module "@odoo/owl" {
    export * from "@odoo/owl/dist/types/owl"
}
```
Also, not doing that fix and doing
```bash
rm -f project_b/node_modules
ln -s project_a/node_modules project_b/node_modules
```
Have the same effect: `@odoo/owl`: becomes suggested.

### 🙂 Expected behavior

We made the hypothesis that the node_modules in project A was resolved before the ones in project B, and shadow the ones of the latter.
We have the instinctive opinion that node_modules that aren't explicitly available should not shadow the ones that are.
 
Thanks, and sorry if this issue is filed under the wrong section, but i'll be grateful if you could tell me what you think.

**Comment by RyanCavanaugh** [comment]
We're going to need an actual repo to investigate. Speculating, the problem is in the package.json - auto-import will not offer modules that aren't explicitly in your `dependencies` or `devDependencies` list, since it's incorrect to depend on a transitive dependency.

**Comment by kebeclibre** [comment]
Hello, thanks for your answer
I made a mock repo here: https://github.com/kebeclibre/TypeScriptIssue-57762

I explain the steps I take in the commits

I could not reproduce my original problem on our production repo, since the two projects are in two separate repositories and one of them is private.

**Comment by RyanCavanaugh** [comment]
I don't see a dependency or other hint for to indicate that loading the other project for analysis is valid. Auto-import can only offer imports from files it knows about, and there's no reason it should suspect the peer folder is one it should be looking at.

**Comment by kebeclibre** [comment]
Yes, precisely.
But when an import preexists in project_b, even if it points to something in project_a that it is not supposed to be aware of, I have a suggestion for that import, and, when hitting F12 to see the definition, it does open the right file.

I'm not sure if it is VSCode or Typescript though.

Cheers anyway and thanks for looking at this

**Comment by RyanCavanaugh** [comment]
Right. TS isn't scanning your entire hard drive looking for files that might possibly be part of your project; there is obviously some limit. The limit is what you saw. But *once you have* an import into some other set of files, those files are available for analysis. That's the intended scoping mechanic.
