### ISSUE TITLE
typeof generic class returns any for all type arguments 

### ISSUE THREAD

**Issue by martaver** [microsoft/TypeScript#57763]
### 🔎 Search Terms

typeof generic class
strips type arguments
ignores type arguments
returns any for all type arguments

### 🕗 Version & Regression Information

Exhibited from `5.4.2` down to `4.9.x` and probably beyond.

### ⏯ Playground Link

https://tsplay.dev/wX0A1w

### 💻 Code

```ts

interface IHost {
  hostName: string
}

class Host1 implements IHost {
  declare private __XHost1__: '__XHost1__'

  constructor(readonly hostName: string) {}
}

class Host2 implements IHost {
  declare private __XHost2__: '__XHost2__'
  constructor(readonly hostName: string) {}
}

interface IPage<H extends IHost> {
  host: H
}

class Host2Page<H extends Host2> implements IPage<H> {
  constructor(readonly host: H) {}
}

type _This_Is_Obviously_False = Host2 extends Host1 ? true : false
type _Ctors_Also_False = (new (...args: any[]) => Host2) extends (new (...args: any[]) => Host1) ? true : false
type _Ctors_Of_Pages_Also_False = (new (...args: any[]) => IPage<Host2>) extends (new (...args: any[]) => IPage<Host1>) ? true : false
type _But_This_Is_True = typeof Host2Page extends (new (...args: any[]) => IPage<Host1>) ? true : false

function onlyHost1Pages(ctor: new (...args: any[]) => IPage<Host1>) {
  return new ctor()
}

/**
 * This shouldn't allow me to pass a Page whose `H` is constraints to `Host2`.
 */
onlyHost1Pages(Host2Page)
```

### 🙁 Actual behavior

TS happily allows `Host2Page` to be passed to a function that should only accept Ctors for `IPage<Host1>`.

### 🙂 Expected behavior

TS should return `false` when comparing `typeof Host2Page extends (new (...args: any[]) => IPage<Host1>) ? true : false`

TS should reject `Host2Page` when being passed to `onlyHost1Pages` as an argument.

### Additional information about the issue

If you use `Simplify` from `type-fest` to force TS to expand `typeof Host2Page` then you see that the prototype is evaluated with `H` as `any`. This would explain why TS reports that `Host2Page` extends an incompatible constructor.

The constrained base type of `H` is easily inferable with:
```
type BaseHost = typeof Host2Page extends new (...args: any[]) => IPage<infer U> ? U : never
```
And yet, TS ignores the constrained type of H in the former comparison.

This leads to inconsistent and unintuitive behaviour, and makes it impossible to reject class constructor types based on their type arguments.

**Comment by martaver** [comment]
To paraphrase @Andarist, my understanding of why `H` is inferred as `any` is because:
- `H` exists in two places, as a parameter and as a return type.
- `H` corresponds to `any` in the parameter in the inference context of `(...args: any[]) => IPage<Host1>`.
- `H` could also be `Host1`, but `typeof Host2Page` is invariant, and (IIUC) TS prefers the parameter type anyway, so `any` is inferred over `Host1`.

From this perspective, I think TS is acting as intended, and the problem is actually the misuse of `(...args: any[])` which has colloquially come to mean "I don't care about the parameters", instead of what it actually means which is "Must accept any and all parameters".

The solution we found was to use a constructor type as the inference context that allows parameters and return types to be contravariant and covariant respectively, e.g.

```
type PageCtor<T extends IHost, TIn extends T = T, TOut extends T = T> = new (host: TIn) => IPage<TOut>
```

This allows TIn and TOut to be inferred independently of each other, which is usually why `(...args: any[])` is used - to prevent the args from getting in the way of the return type.

Here it is in action: https://tsplay.dev/WGbO9m

I'm going to suggest that this issue is closed as 'working as intended', however it's probably worth considering whether there could be a better way to express a constructor type that keeps its variance.

**Comment by fatcerberus** [comment]
> `(...args: any[])` which has colloquially come to mean "I don't care about the parameters", instead of what it actually means which is "Must accept any and all parameters".

Yep, contravariance strikes again.  Just like how `(x: Animal) => void` doesn't mean "the parameter is some kind of animal" but rather "must accept any kind of animal"
