### ISSUE TITLE
`override` keyword is duplicated in vscode autocomplete when accepting suggested override when the `override` keyword is already there

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#57760]
### 🔎 Search Terms

override vscode

### 🕗 Version & Regression Information

typescript 5.4.2
vscode 1.87.1

### 💻 Code

```ts
class Foo {
    foo(a: number) {}
}

class Bar extends Foo {
    override fo//caret here
}
```

### 🙁 Actual behavior

```ts
class Foo {
    foo(a: number) {}
}

class Bar extends Foo {
    override override foo(a: number): void {
        
    }
}
```

### 🙂 Expected behavior

```ts
class Foo {
    foo(a: number) {}
}

class Bar extends Foo {
    override foo(a: number): void {
        
    }
}
```

### Additional information about the issue
![](https://github.com/microsoft/TypeScript/assets/57028336/fcf1f542-9793-4270-a02c-532ca03e22e3)

**Comment by jakebailey** [comment]
Try nightly, this was probably fixed by https://github.com/microsoft/TypeScript/pull/57643

**Comment by DetachHead** [comment]
looks like it's mostly fixed, but it seems to briefly insert the duplicated `override` before removing it because the duplicated keyword appears when pressing `ctrl+z` after accepting the suggestion:

![](https://github.com/microsoft/TypeScript/assets/57028336/8cddf710-661f-476b-9af4-384d32756eed)

**Comment by jakebailey** [comment]
Yep:

> The modifiers already present may be out of order, so we always add all the modifiers as part of the member completion entry, and send a code action to erase the present modifiers.
