### ISSUE TITLE
Branded string literals cannot be used in the computed property name of a type

### ISSUE THREAD

**Issue by peterflynn** [microsoft/TypeScript#57767]
### 🔎 Search Terms

type branding, nominal types, nominal typing

### 🕗 Version & Regression Information

Does not seem like a regression.  I've reproduced it in TS 5.4.2 and 4.8.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTAEBUAsEsGdQO4HsBOBrWAuUBDUsAXFaAOwHMBaAG2gIFMUcrQBjJEwnEg1r0AIzqgArrDoATUKVAFIQtgFsADsPqSlKJEoYEAnqBI4FQpADNcM3dtDi6LKjkYFo7AFCnhJFs-b5oyqjoAdVQ0UjIAYRwxAAoASlAAb1dQVNZ2QnSOAgA1JlAAXlAAIgAPXQAvYoBuVxS0vWsAVUKk+rS0gG02bLyqAF1sImE6dtAAX1rxutcQCBh4cSQ6eAA5AHlwRFCAGlwqWSRhMkgZBazObn3YJFBIaItTaFKJfCJw6loGfIA3JhGzjgeHBQGgSEgECRcDxFEpoIEZP5Rh4vD4ofxjlFYglkh0epl+IwSLZxBEMrkmNgypViqAAGRJAD6jNMSCQmAAjONUkVqVVcPAuLpamNGkIWkVcR0uoSuCSyb0mIMZCgRmNJq5pnU5gAFRzOfIhdCOI7E7AoOjRWDQMhQgi3PDgkgUWXE174ghcHiEYjkT70RjMMXuTzeFxQ5DGzSecQc+JtPHkgRE+XkvpU8r8hmJZms9lcnklTO0h5CkWJ7IiEiu1NKXQZmmtGsSBWEPrlhpWcWtKXS0CdTzN0laXTK4ajDoarWzMBQEF-YhA8O4H5IaDieAW7RL8hnIQ+8KgGgBpgh1HLyNoE0xgBM8d7Fx4OQAggAZVp8mpjD3JuUttOUpY2hmKAL7vtmuZspy3KtGBAq4CQwp1B0YqgBKCZ9v2YFjqqE5pFOrhAA

### 💻 Code

```ts
// This works: a string-literal constant can be used in the computed property name of a type declaration
function simpleWorkingCase() {
    const constVal = "xyz";

    type U = {
        [constVal]: true  // works
    };
}


// This does NOT work, although this constant also has a fixed string-literal value that is known at compile time
function bugCase() {
    const brandedConstVal: "xyz" & {__foo:1}  = "xyz" as any;

    type U = {
        [brandedConstVal]: true  // ERROR!
    };
}
```

### 🙁 Actual behavior

The second case gives compiler error ts(1170):
> A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol' type.

### 🙂 Expected behavior

Since the `brandedConstVal` still has a literal value that is known at compile time, it should work as a computed property name too.

This is a little weird, since in reality it's impossible for any object key to be itself an object containing fields (the `__foo` "brand" marker in this example).  But the compiler already ignores that impossibility in allowing type declarations like `string & { ...whatever ... }` in the first place – a useful trait in light of the nominal typing behaviors it enables.  Since that is already supported, computed property names should ideally work consistently with it as well.

### Additional information about the issue

The Playground link also illustrates a workaround (with two variations).

The workaround isn't ideal however.  For example, if `type U` is being declared in a different module from `brandedConstVal`, that module would have to now export two copies of the const (`brandedConstVal` _plus_ the unbranded copy `VAL`) – which is potentially more confusing for all clients of the module.

**Comment by peterflynn** [comment]
I'm also seeing some strange behavior with mapped object types: [Playground link](https://www.typescriptlang.org/play?#code/PTAEAUCcHsCMBsCmBbAzqArqglgOwOaiyQCGuAJouaKgC6R77p6jIkAO7VocAVogGNaoWgE8uqAFCSAZhlxDs0XJlzEylcgHVokANaMAwiVSIAFAEpQAb0mh7oAcrqPntAGol4oALygARAAeogBe-gDc0g4i4oigALIcXOQAKrG+NqAA2nqgLGJc0DKuuHSe8AC6AFwikBhxAL7h9iCZwSE19PWgDXYOBXGJnFQA0oii6H5640UJSVRpXM2grUGh-lEOrQCikDCQNQDkMtBwJJCHoOTQiOi40MKIgdgu+emHQ8mLiId99k6lYS0W60GqfBbpPzWUAnM4HUAATgRPUifxWYF2+xq31Ah1wGGQsEQFzydweoBMOHwuBICDitGgMS4uK6PzRAJcwLoACYwfNUpC2qEagBGAAMYpRmxaGL2uhqUGgXEgYlx7UuL1YLxwBDyKgGuOsDUusAwwkgiAAjhhsBbqG9mR9+d9ftEOUCQQBmPnDAXMqFS3rSOQKWhKFSm-DGUyWGzstxEUgUKiGNzlGprMKgABkNgA+nnYVURQ17H5M-4KegyKJUdEDeC-XEAzk9UzELN1MnyKnAeVqrVuk10TZS6AALTjgB8oHuoGmEwpFtA8BewPIAEI0Q3+WNF1MZsVG99mq1DhWc-nC6di8b7JOZ6bhAvQABJADKK7X3AAFsTEFuaKtAAcoyxL7KAVTjmY8aAiIII+l8grQrCsDnDUSJSkBYCgaA4G6JB0GwZyIK8nMvo4gG7SihKWHRCBYFypAhEwW6CZcrQ3rkUh-qZE0kgNEAA)

In this case there's
* (a) the tooltips for `MappedType` vs. `keyof MappedType` disagree with one another about what keys are present in the type! (the former says there are no keys, the latter lists the branded string as a key)
* (b) loss of expected type-checking behavior (type checking behaves as if there are no keys, agreeing with the empty tooltip for `MappedType`)

Seems like these issues probably has the same root cause, but please let me know if you'd rather I break that out as a separate GH issue.

**Comment by peterflynn** [comment]
Another oddity: the original bug above is that branded string constants can't be used as a computed property name in a type declaration. Branded string constants _can_ however be used as a computed property name in an object _value_ – but those strings are not correctly matched against plain/unbranded identifiers when type-checking:

```ts
function bugCase() {
    const brandedConstVal: "xyz" & {__foo:1}  = "xyz" as any;

    type U = {
        xyz: true
    };
    const u: U = {  // ERROR: Property 'xyz' is missing in type '{ [x: string]: boolean; }'
        [brandedConstVal]: true
    };
}
```

...this despite the fact that branded string constants _are_ assignable to matching plain/unbranded string types, outside the context of object keys:

```ts
function counterpoint() {
    const VAL = "xyz";
    const brandedConstVal: "xyz" & {__foo:1}  = "xyz" as any;

    let foo: "xyz" = VAL;
    foo = brandedConstVal;  // works!
}
```

[More detailed Playground of this here](https://www.typescriptlang.org/play?#code/PTAEHUHsCcGsGcBcoAOAbAhgSwHangC7S4DmAtGlgQKbQZqgDGkOhGOBoArvNQCagM8JpAC2KLjQEpokFLQIBPUDgyjqoXKEgAjAFbVGnAG70u1AFAAzLjiNYW3Oy0J1c-AMpZxaalDikAMJC1AAUAJSgAN4WoHEirJwAagCCADKgALygAEQAHooAXjkA3Bax8cyJ3FnRcSCgSvKQVjXZUaAFhcg6kJC+7CWgAL4V8fEA2qlpALrIROZjI2WjFg0eMAQYoADuMAg9dDh8-PhEpBRUtPTcvAJCIuKSpzJyCsqq6pp4ugZGoKY0IsGgA6MEAIQAqgAVRoACw0v0MBAA5MJcFZaNBTk0NFhhKIuIw4aBRDANKYSOZ4exBL1jJYbHYCA48LYqq5sDh+OCjic+P5YEEQhFoksOZwdHz+IEXAQkvRkPkijlQAAyaIAfU1Vj6iAAjMM4tllcVBMJ2IoyuK5W06qAGriWnaOhM8shXKQ5qBev1qIMRktxhMpex+bLEgq0N6FpZxsMVuU1mBoXD8bt9kh4Rp0FyzsQcORKDQ6AxmE8pKhZPJoEpcl1VenRBgCMTTsxoNijGhlARINnNCcOFgrFhaKAAAZdCffRqKeSgSHWdksxzwbzoPz7YW8UUxcYS0DTWqm0rlca4xe1ffjeJdebQRbxsoH21cZCQ69BybTGOPuPxAmFirMmoAACKQNQwgAHIAPKwnscDzAiPrSgInqFpcJY3OWEiVq8NZ1hOp5qmCIIznwkEwfBpItsSA5YEOLKjuOU5FDOWiXkuTL2I4OhcCQwS7pEN5xIeobHDKcpRkqDbqlqOp6oaxr1iq5qCDgVrnvEXFfred5FA+T6AS+lRvh+171GAACiABKtmwbZyAAArVu8oAol0KKaAS+LroWs6XiirruvmXo9H0Aw4EMwwot+cQhmhEaEFGf7GXEQEgQ0ACa1CcJyhbUD2AA08LpmBsHWR4GZIYIqFhqcGFFlcpZzguACS1VCOuJCqDoviNP2BAoc2rZpgFuZaE1WHXAwuLLsyrIiLYJYoJAuAEHuNrVMeJoNqZYm2hJ4bSYqqlmhqUTarqkAGkaJ5yQ8lrWuMvicDdslqdk0wHaAN21MdUmRvQQwOmAiEIAAhMBFhAA).

So overall, it seems there's a general issue with branded string constants used as keys in object types.  It's not totally disallowed to use them as keys, but you get a lot of undesirable type-checking behavior that is sometimes looser than you want (see my previous comment) and sometimes stricter than you want (original report plus this comment).

**Comment by RyanCavanaugh** [comment]
> Since the brandedConstVal still has a literal value that is known at compile time, it should work as a computed property name too.

I'm not clear on what the alleged bug is here.

The error about the branded type not being a well-formed string name is a legitimate choice IMO. A branded type *isn't* a string type and there are architectural reasons why we need to be able resolve these without performing any type resolution. Once we open the door for anything but a bare string type, there are tons of *new* inconsistencies that would appear -- we can't remove this line between readily-resolved types and non-readily-resolved types, so the line has to be somewhere, and putting the line at "really, a string literal" seems like by far the least inconsistent and clearest behavior.

In value space there are different rules because, well, values aren't types, and we have to do something in most cases.

The behavior in this example
```ts
    type MappedType = { [k in typeof brandedConstVal]: true }; // {}  --> no keys are listed!
    type MappedKeys = keyof MappedType; // '"xyz" & {__foo:1}'  --> but key IS listed here!
```
is admittedly odd but sort follows from the definition of a homomorphic mapped type. It doesn't create an unsoundness, though:
```ts
    type MappedType = { [k in typeof brandedConstVal]: true }; // {}  --> no keys are listed!
    type MappedKeys = keyof MappedType; // '"xyz" & {__foo:1}'  --> but key IS listed here!
    let s: MappedKeys = null! as any;
    const test: MappedType = { foobar: 99 };
    const p = test[s];
    //          ^ error, can't do that
```
