### ISSUE TITLE
TypeScript only find types

### ISSUE THREAD

**Issue by regseb** [microsoft/TypeScript#57789]
### 🔎 Search Terms

TS18042, TS2693, import, exports, types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (_5.4.2_ and _5.0.2_), and I reviewed the FAQ for entries about _exports_.

### 💻 Code

- `package.json`

  ```JSON
  {
    "name": "testcase",
    "version": "1.0.0",
    "type": "module",
    "dependencies": {
      "subproject": "./subproject/",
      "typescript": "5.4.2"
    }
  }
  ```

- `index.js`

  ```JavaScript
  import sub from "subproject";

  console.log(sub.foo);
  ```

- `subproject/`
  - `package.json`

    ```JSON
    {
      "name": "subproject",
      "version": "1.0.0",
      "type": "module",
      "exports": {
        ".": {
          "types": "./sub.d.ts",
          "default": "./sub.js"
        }
      }
    }
    ```

  - `sub.js`

    ```JavaScript
    export default {
      foo: "bar",
      baz: 42,
    };
    ```

  - `sub.d.ts`

    ```TypeScript
    declare type _default = {
      foo: string;
      baz: number;
    };

    export default _default;
    ```

1. `npm install`
2. `npx tsc --noEmit --checkJs --module nodenext index.js`
   or `npx tsc --noEmit --checkJs --module nodenext --moduleResolution nodenext index.js`

### 🙁 Actual behavior

```
index.js:1:8 - error TS18042: 'sub' is a type and cannot be imported in JavaScript files. Use 'import("subproject").sub' in a JSDoc type annotation.

1 import sub from "subproject";
         ~~~

index.js:3:13 - error TS2693: 'sub' only refers to a type, but is being used as a value here.

3 console.log(sub.foo);
              ~~~


Found 2 errors in the same file, starting at: index.js:1
```

### 🙂 Expected behavior

No error.

### Additional information about the issue

I also reproduce the bug with `npm pack` and:

```JSON
{
  "dependencies": {
    "subproject": "./subproject/subproject-1.0.0.tgz",
  }
}
```

**Comment by regseb** [comment]
I'm having the same problem with a TypeScript file:

```TypeScript
// index.ts
import type subType from "subproject";
import sub from "subproject";

const a: subType = {
    foo: "bar",
    baz: "Not a Number",
};
const b: sub = {
    foo: "bar",
    baz: "Not a Number",
};

console.log(sub.foo);
```

`npx tsc --noEmit --module nodenext index.ts`

```
index.ts:7:5 - error TS2322: Type 'string' is not assignable to type 'number'.

7     baz: "Not a Number",
      ~~~

  node_modules/subproject/sub.d.ts:3:5
    3     baz: number;
          ~~~
    The expected type comes from property 'baz' which is declared here on type '_default'

index.ts:11:5 - error TS2322: Type 'string' is not assignable to type 'number'.

11     baz: "Not a Number",
       ~~~

  node_modules/subproject/sub.d.ts:3:5
    3     baz: number;
          ~~~
    The expected type comes from property 'baz' which is declared here on type '_default'

index.ts:14:13 - error TS2693: 'sub' only refers to a type, but is being used as a value here.

14 console.log(sub.foo);
               ~~~


Found 3 errors in the same file, starting at: index.ts:7
```

**Comment by IllusionMH** [comment]
`types` in `exports` section override/shadow `import`/`require` and in your declarations you only export type.

To export value you need to declare const and export it as default IIRC

**Comment by jakebailey** [comment]
```ts
declare const _default = {
  foo: string;
  baz: number;
};

export default _default;
```

**Comment by jakebailey** [comment]
If you're already using TypeScript, you'd be better of using it to produce your declaration files instead of doing it by hand; it would have done the right thing.

**Comment by regseb** [comment]
Thank you for your feedback. I understood the association between _.js_ and _.d.ts_ files. The _.d.ts_ file:

- must **not** export the type of JavaScript objects.
- must export typed JavaScript objects.

---

I want to add typing to a JavaScript project. That's why I'm writing the declaration file by hand. And then I use TypeScript and JSDoc to validate the types in the JavaScript files.
