### ISSUE TITLE
Declaring a named module with call signature?

### ISSUE THREAD

**Issue by jseanxu** [Microsoft/TypeScript#5778]
I'm having trouble typing the following scenario.

defs.d.ts
```
declare module "my/module" {
  export = (arg: string) => any;
}
```

main.ts
```
import myModule = require("my/module");
myModule("hello");
```

Line 2 in `main.ts` compiles fine, VS even shows the correct call signature, however, `defs.d.ts` does not compile correctly:
`error TS2304: Cannot find name 'any'`

**Comment by vladima** [comment]
can you define "my/module" like this?
```ts
declare module "my/module" {
    function f(arg: string) => any;
    export = f;
}
```

**Comment by jseanxu** [comment]
That works, thanks!
