### ISSUE TITLE
Use Decorators for Validation: How to extend knockout observables with Decorators using Typescript?

### ISSUE THREAD

**Issue by Eisenspalter** [Microsoft/TypeScript#5779]
I have the same issue like this guy [link to stackoverflow](http://stackoverflow.com/questions/33858657/how-to-extend-knockout-observables-with-decorators-using-typescript).

**Comment by aleksey-bykov** [comment]
why do you need decorators? how are they better than the extend method?

**Comment by Eisenspalter** [comment]
Cleaner constructor and class. Easier to change and maintenance things, like validation outside the class.

**Comment by mhegazy** [comment]
StackOverflow is probably better for such questions.  you might find this useful: https://github.com/Microsoft/TypeScript/issues/4218#issuecomment-128840766
