### ISSUE TITLE
Function overload prompt issue

### ISSUE THREAD

**Issue by fuxichen** [microsoft/TypeScript#57791]
### 🔍 Search Terms

function overloading

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

It is expected to optimize the prompt when hovering over the function

old issue: https://github.com/microsoft/TypeScript/issues/57787#issue-2187582082

### 📃 Motivating Example

DEMO: https://www.typescriptlang.org/play?ssl=16&ssc=1&pln=16&pc=8#code/KYOwrgtgBAygLgQzsKBvAUFKBBKBeKAcgUIBpMoAhfIgIzPQF90AzMEAYzgEsB7EKMgDOcAGLsAFCKTAAXPBkA6bKSgATJAlkiATtxABzAJSyAbr25qA3K3Zc+A4WMnTk8xMkWVVGxLPAQtMA6JuaWNmycPPyCwCLiIFIecgrIPpracHqGUAA+UAFBIWgUHPxCvAA2wIqVvAZJMumIRkzo7R3oTgkSqTWURkA

![image](https://github.com/microsoft/TypeScript/assets/17411462/ccac42f7-041c-4bcb-84cb-3629a61439d2)
![image](https://github.com/microsoft/TypeScript/assets/17411462/f0c0d7f2-7585-4e89-8b1e-9fcf3cc87835)

As shown in the above diagram:

1. When the parameter state of the function testFun is set to State.A, the data parameter is of type string.
2. When the parameter state of the function testFun is set to State.B, the data parameter is of type number.
Typescript indeed enforces type restrictions as expected. However, when using testFun and passing the parameter state=State.B, hovering over the function shows a prompt indicating that the data parameter is of type string instead of number. Nevertheless, accurate prompts are displayed when inputting the data parameter.

It is expected to optimize the prompt when hovering over the function.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by RyanCavanaugh** [comment]
We already have this logic for signature help, so just need to use that same code for deciding what to show in quick info
