### ISSUE TITLE
Support for abstract static methods, or add a way to specify a static method on an interface

### ISSUE THREAD

**Issue by nhusby** [microsoft/TypeScript#57797]
### 🔍 Search Terms

abstract static, static method interface

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Support abstract static properties and methods.

### 📃 Motivating Example

abstract class BaseClass {
  public abstract static staticMethod(): Promise<void>;
  
  static doStuff(){
    // do some some stuff, then something that's different for each class
    this.staticMethod()
    // ...
  }
}

// this should throw a compile time error because staticMethod is not implemented.
class DerivedClass  extends BaseClass {

}

### 💻 Use Cases

1. What do you want to use this for? writing base classes that are extended by derived classes written by junior devs
3. What shortcomings exist with current approaches?  TypeScript doesn't support abstract static, and I can't make an interface with static properties/methods that the classes are required to implement.
4. What workarounds are you using in the meantime?  Nothing.  Other devs waste time figuring out why their derived class doesn't work because they were missing a required property they expected TypeScript would have pointed out.

**Comment by RyanCavanaugh** [comment]
Duplicate #34516

**Comment by nhusby** [comment]
> Duplicate #34516

thanks, I'll check that out.
