### ISSUE TITLE
tsc --watch via directory-level fsevents not working on macOS 14.4

### ISSUE THREAD

**Issue by nfarina** [microsoft/TypeScript#57792]
### 🔎 Search Terms

fsevents tsc watch macOS 14.4 not watching working detecting changes found 0 errors

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.4.2 (also occurs in 5.5 dev latest)

### ⏯ Playground Link

https://gist.github.com/nfarina/d5538d16343830e41c9f3e031a65237e

### 💻 Code

Reproducible with just this `package.json` and an arbitrary `test.ts` file (see Gist link):

```json
{
  "name": "tsc-test",
  "version": "1.0.0",
  "description": "tsc watch problem repro",
  "license": "ISC",
  "scripts": {
    "start": "tsc test.ts --watch"
  },
  "dependencies": {
    "typescript": "^5.4.2"
  }
}
```

### 🙁 Actual behavior

This is confusing to me because it seems like _many_ people would be experiencing this right now, but I have tested quite a lot and, for me, TypeScript 5.4.2 broke folder watching completely on my system. (This is a brand new M3 MacBook Air running macOS 14.4).

This works:

```json
"watchFile": "useFsEvents"
```

And this doesn't:

```json
"watchFile": "useFsEventsOnParentDirectory"
```

On TypeScript 5.3.3 and below, both work as expected.

### 🙂 Expected behavior

`tsc --watch` should observe file changes using fsevents folder watching

### Additional information about the issue

I did some digging in the tsc codebase to find where fsevents is being used but was unsuccessful - I'm happy to investigate further if anyone can give me a lead.

**Comment by NMinhNguyen** [comment]
Just to add an observation: I think this issue is Sonoma specific as watch seems to work on 13.6.4 (Ventura).

**Comment by llllvvuu** [comment]
When testing this issue, make sure you don't use Vim. Creating/deleting files seems to trigger the file watcher, so it's possible for Vim users to not notice this issue while VSCode users do.

**Comment by llllvvuu** [comment]
I found the bisect:
```typescript
git checkout dc113f8170 // latest `main` as of this post
git revert e40730f
npm run build && npm run build:compiler
```

**Comment by o-alexandrov** [comment]
For anyone (like me just now) who stumbles on this, the fix hasn't been released on `npm` yet in non-`next` tags.
