### ISSUE TITLE
New files are not recognized in the language server

### ISSUE THREAD

**Issue by divmgl** [microsoft/TypeScript#57796]
### 🔎 Search Terms

There's a million issues about this problem and they're all closed. It's still happening.

### 🕗 Version & Regression Information

N/A

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

N/A

### 🙂 Expected behavior

N/A

### Additional information about the issue

https://github.com/microsoft/TypeScript/issues/45721
https://github.com/microsoft/TypeScript/issues/43290

**Comment by RyanCavanaugh** [comment]
> It's still happening.

It = what? Repro steps, please!

**Comment by zburgermeiszter** [comment]
When I create a new `.ts` file, it is not picked up by the language server in vscode.
I have to manually restart the TS server.

**Comment by RyanCavanaugh** [comment]
I'm asking for what filename you're editing, what its content is, what your tsconfig and package.json are (if any), and what file you're creating, what its content are, your editor watch settings (if not default), and OS.

**Comment by RyanCavanaugh** [comment]
Please log new issue(s) with enough information for us to reproduce the problem.
