### ISSUE TITLE
Add '====' as an alias for '==' to inform code readers that the use of IsLooselyEqual semantics was a deliberate choice.

### ISSUE THREAD

**Issue by djziegler** [microsoft/TypeScript#57805]
### 🔍 Search Terms

isLoosleyEqual == === loose equal strict equal

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Transpile "====" to "==" to inform code readers that the use of IsLooselyEqual semantics was a deliberate choice.

### 📃 Motivating Example

The Javascript equals '==' operator has complicated  legacy semantics (IsLooselyEqual  in the JS spec) , mostly triggered when the two operands have different types.  Most current developers never use '==' to avoid this complication and always use the newer '===' operator that implements the more expected IsStrictlyEqual semantics.

Because of this, when many developers see a '==' in the code, they assume it is an error and convert it to a '==='.

The issue is that sometimes I am writing code where '==' is exactly what I want (usually because JS has two null like values - null and undefined), but if I use '==' to express this I am at risk of some future developer 'fixing' it.  This results in a subtle error being introduced into the code.

I am proposing that '====' be a way of using '==' that informs code readers that using '==' was a deliberate choice. 

### 💻 Use Cases

1. What do you want to use this for?

Using the '==' operator semantics (as opposed to the more usual '===' semantics) in a way that informs code readers that this was a deliberate choice.

2. What shortcomings exist with current approaches?

Code readers often assume that '==' is a typo, and will will replace it with '===' which introduces a bug when you actually needed the '==' semantics.

3. What workarounds are you using in the meantime?

Either comments like : 

// Note: use of '==' below is deliberate 

OR

 refactoring to use an || and two === expressions.

**Comment by MartinJohns** [comment]
This is out of scope for TypeScript. The viability checklist contain these points:

> - This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, **new syntax sugar for JS**, etc.)  
> - This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

In general, anything that has to be "rewritten" when compiling is a no-go, except for supporting older ECMAScript versions and some legacy features (namespaces, enums).

And frankly, the better option for this case is to either wrap the comparison in a helper function, or just add a comment.

**Comment by ritschwumm** [comment]
i'd prefer a comment anyway to explain _why_ loose comparison was chosen, something an operator like `====` can't do.

**Comment by djziegler** [comment]
Withdrawn based on intial feedback.
