### ISSUE TITLE
Regression when spreading Types in an Alias: TS1265: A rest element cannot follow another rest element.

### ISSUE THREAD

**Issue by pfeileon** [microsoft/TypeScript#57828]
### 🔎 Search Terms

TS1265

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.4.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.2#code/MYewdgzgLgBAZgSwE7QPICMBWBTYsC8MA3nCCAFwwDkpIVAvjAIYQyiRQDcAUO9DBFzgAJhhx4YhIuiZJKVGUgbNWfLt17h+iFFADCWqEzAEYAbSpMANlaoAaGADpnACjG4ojgNbYAnhBcdNCwPAEpQgF0VNkMeNQEhMGEDDmNTC2tbB2dHNxC8bz8AwXZRfKhwqJYYjh5uKF8AB2wYADFkaAAVJpbCBuaQOHgO-UM0nn6WgGVE4W7myRhJwYTSlOhxjUmYAwBbdAQwbDmexaRsJmFwK19zbhgnZ3bdeew7e8fHGdLX94ieIA

### 💻 Code

```ts repro
const firstObject = {foo: 'foo'} as const;
const secondObject = {bar: 'bar'} as const;

const firstConstant = ['all', ...(Object.keys(firstObject))] as const;
const secondConstant = ['all', ...(Object.keys(secondObject))] as const;

type FirstType = typeof firstConstant;
type SecondType = typeof secondConstant;

type CombinedType = readonly [
  ...FirstType,
  ...SecondType,
];

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBAZgSwE7QPICMBWBTYsC8MA3nCCAFwwDkpIVAvjAIYQyiRQDcAUO9DBFzgAJhhx4YhIuiZJKVGUgbNWfLt17h+iFFADCWqEzAEYAbSpMANlaoAaGADpnACjG4ojgNbYAnhBcdNCwPAEpQgF0VNkMeNQEhMGEDDmNTC2tbB2dHNxC8bz8AwXZRfKhwqJYYjh5uKF8AB2wYADFkaAAVJpbCBuaQOHgO-UM0nn6WgGVE4W7myRhJwYTSlOhxjUmYAwBbdAQwbDmexaRsJmFwK19zbhgnZ3bdeew7e8fHGdLX94ieIA)

### 🙁 Actual behavior

A rest element cannot follow another rest element.(1265)

### 🙂 Expected behavior

No error

**Comment by Andarist** [comment]
This is working as intended now and was changed [here](https://github.com/microsoft/TypeScript/pull/57031/commits/70715eae3ba4ded0ea7f4f0b3792aeae35944c8f), see the discussion before [this comment](https://github.com/microsoft/TypeScript/pull/57031#discussion_r1450709671)

**Comment by pfeileon** [comment]
> This is working as intended now and was changed [here](https://github.com/microsoft/TypeScript/pull/57031/commits/70715eae3ba4ded0ea7f4f0b3792aeae35944c8f), see the discussion before [this comment](https://github.com/microsoft/TypeScript/pull/57031#discussion_r1450709671)

Is it? In my example it's all strings, the tuples aren't of mixed types.

**Comment by Andarist** [comment]
It doesn't matter what are the types contained in those arrays. The reported error is pretty generic and is only concerned with the fact that you are using multiple rest elements:
> A rest element cannot follow another rest element.(1265)
