### ISSUE TITLE
Allow Infinity, -Infinity and NaN as an enum key name for string enum

### ISSUE THREAD

**Issue by XeroAlpha** [microsoft/TypeScript#57845]
### 🔍 Search Terms

infinity nan enum string

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow the usage of `Infinity`, `-Infinity`, and `NaN` as key names in a string enum.

I understand the reasoning behind disallowing numeric names as enum keys, as they can cause conflicts with reverse mapping.
However, in the case of a string enum where every value is a string, reverse mapping is not applied. Therefore, it does not make sense to disallow numeric names in this scenario.

### 📃 Motivating Example

```ts
enum SomeEnum {
    Infinity = 1, // This should fail!
    Apple = Number.POSITIVE_INFINITY,
}

enum MinecraftEnchantmentTypes {
    Infinity = 'infinity', // This should pass!
    Unbreaking = 'unbreaking'
}
```

### 💻 Use Cases

1. What do you want to use this for?
To maintain compatibility with existing code.

2. What shortcomings exist with current approaches?
Please refer to the suggestion provided.

3. What workarounds are you using in the meantime?
Currently, there are no workarounds available except renaming enum members, which would introduce breaking changes.

**Comment by MartinJohns** [comment]
This was allowed before, but then it was intentionally removed again: #56161

**Comment by RyanCavanaugh** [comment]
I don't think this rule makes sense to apply to string enums. Will discuss.
