### ISSUE TITLE
`void | T` allows narrowing of `undefined | T`

### ISSUE THREAD

**Issue by robbiespeed** [microsoft/TypeScript#57855]
### 🔎 Search Terms

void, union, undefined, narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about void

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.2#code/GYVwdgxgLglg9mABMOdEAoBuAuRm4wAmiAPomCALYBGApgE4CUuFNDpi4htwMYtxAN4AoRIgD04vAWJ0AFgENMfAOaIANjADWtTmG69+hUYhjAMUAJ4AHWnHOZEAXheIARHGoArWtDeNEETExTABuCSl+TAYTMXpaKBB6MFCTAF8TMwxHAEJXLh4+AQCg4PjE5LxwyXIqOnoMahAoRAg4EHVieIV1dUtEOkQFMEsoOVVGdOETcqSU4QzhUEhYBAGFBvRmRABnKHpVQMRZyrc5Wl64N0Q01OE2sD31gC9cLecAPmkiZ3X6O5QcHQ1A2W0Y1UicBaPXUcAA7gIlqhgQpnmCIUNLgjZM1ELR9DtONZjgk5ocFLt9odhEA

### 💻 Code

```ts
function foo (v: void | number): number | undefined {
  // void behaving like undefined
  if (typeof v === "object") {
    v; // never
    return;
  }
  if (v !== undefined) {
    return v; // number (but could really be anything)
  }

  return;
}

function bar (): string { return "hello" };

const baz: () => void = bar;

foo(bar()); // not allowed
foo(baz()); // allowed but ends up returning a string 
```

### 🙁 Actual behavior

`void | number` narrows as if it were `undefined | number` leading to incorrect application state.

### 🙂 Expected behavior

`void | number` should only narrow to number using `v === numericLiteral` or `typeof v === "number"`

### Additional information about the issue

It's a bit unclear whether `typeof v === "object"` should narrow v to `object | null` instead of `never`, since in some cases like function return types void acts as `unknown`.

As an aside it seems like `void` isn't very useful now that we have `unknown` ([modified playground](https://www.typescriptlang.org/play?ts=5.4.2#code/GYVwdgxgLglg9mABMOdEAoBuAuR4DWYcA7kgD6JggC2ARgKYBOAlLlXU4heACb3Aww9HogDeAKESIA9NMSY4MEQwAWAQ0yCA5ogA2MfPTxg+AoT0mIYwDFACeAB3pwbmRAF5PiAERxaAK3pob2YxSylMAG4ZOT9A6C5KEF1dcMRGeigQRjBIywBfS2sMNwBCL15+QWFQiSkpDKyc+WjZRAAVRyMAclF87qsAZ0o4KEQ1QcGYLTA1Wl0jKDR7J0Ru9gZGboA6AvFLRuzc8ULxUEhYBERaNUYMVkRBqEZtMXTMo58VehS4b0R8nlxBAEE9rmoAF64dChdwAPmMhBISHc4MYQJQcHQN0YMOYrTkRDGal+xGEZ1Q2MheIJ41JwmuIDG9BMwxADneTTArzUj2er3EQA) replacing void with unknown and it catches the issue).

**Comment by MartinJohns** [comment]
Related: #42709

In general a union with `void` makes absolutely no sense. Unfortunately a lot of people think `void` means "no value", but that's not the case.

**Comment by robbiespeed** [comment]
@MartinJohns Thanks for pointing me to that issue I was tempted to make a feature request for at the very least inferring function returns as undefined by default, if not outright removing void in strict mode.

I do agree that in general void shouldn't be used with a union, but it illustrates the inconsistent behaviour of void well. An example without a union is:
```
declare const v: void;
if (v !== undefined) {
  v; // type is never (void narrowed as if it was undefined)
} else {
  v; // void?
}
```

**Comment by RyanCavanaugh** [comment]
I think #42709 is the controlling issue here - removing all conflations of `void` and `undefined` is really the knot to untangle

**Comment by robbiespeed** [comment]
@RyanCavanaugh I don't agree, that issue seems to be centered around replacing `void` with `undefined` as the default inferred value for non returning functions, but still allowing explicit use of `void`.

This specific bug will still be present regardless of the decision there.

**Comment by RyanCavanaugh** [comment]
There's #46837 then

**Comment by robbiespeed** [comment]
Just saw that as well, will close this.

**Comment by fatcerberus** [comment]
I still get a kick out of this comment

> We've spent several dozen person-hours in the past few months beating this particular horse to death without much forward progress, but I remain optimistic that we'll eventually make some progress on it.

Given that that was posted over 3 years ago, I think it's safe to say the horse is well and truly dead by now and any further progress it will almost assuredly require enlisting the services of a necromancer
