### ISSUE TITLE
The type of the return value is omitted.

### ISSUE THREAD

**Issue by starski** [microsoft/TypeScript#57868]
This will return an error, and that's how it's supposed to be:
```
const demoArray: number[] = [0,1,2,3,4,5];
const updatedArray: number[] = ['x', ...demoArray];
// Type 'string' is not assignable to type 'number'.
```
BUT somehow I managed to add 'x' to number[]
(I entered 'value :any' on purpose, it's the only way to indicate the problem/incorrect operation.)
```
function pushFirst(array: number[], value: any): number[]{
    return [value, ...array];
}
let demoArray: number[] = [0,1,2,3,4,5];
let updatedArray: number[] = pushFirst(demoArray, 'x');
console.log(
    demoArray,
    updatedArray
);
```
And in the console I have:
```
Array(6) [0, 1, 2, 3, 4, 5]
Array(7) ["x", 0, 1, 2, 3, 4, 5]
```

**Comment by RyanCavanaugh** [comment]
Indeed. See https://www.typescriptlang.org/docs/handbook/basic-types.html#any

**Comment by starski** [comment]
Sure, I understand that. The 'any' type is not the problem I am bringing to your attention.
Of course, I could provide the type number instead of 'any' and it would work as it should, but the behavior I encountered allows to break the contract.
The problem is that a variable that has a type specified as number[] and a function that has a declared return value also as number[] pass the string 'x' to value with type number[].

If this is intentional, I have a very hard time accepting it.

**Comment by RyanCavanaugh** [comment]
Your example errors *unless* you use `any`. The point of `any` is to *not* generate errors.

**Comment by starski** [comment]
However, I thought that:
- 'any' allows the function to accept any type of a given parameter
- return number[] ensures that regardless of the parameters the function takes, only number values will be provided in the returned array.

Thank you for your answers and patience.
Now I am aware that this can happen, although it is a bit unintuitive. I'll keep an eye out for this in my code.
Regards!

**Comment by fatcerberus** [comment]
If you want a type that means "any possible value" but is actually typesafe, you should use `unknown` instead of `any`.  `any` basically *means* "don't typecheck this value in any context"
