### ISSUE TITLE
Regression 5.4: the new conditional type constraint is not working with a type parameter representing union type

### ISSUE THREAD

**Issue by Alexsey** [microsoft/TypeScript#57864]
### 🔎 Search Terms

regression, type parameter, 5.4

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.3.3 and 5.4.2

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.2#code/C4TwDgpgBAggznAlgcwHYCUJwK4BtgA8MATsVBAB7ASoAmcUA9gEYBWEAxsANoC6AfFAC8sUgCgxAeklRuqPLgA0UeQFtmEYsux0IAM0SoItZXGDFDyXsMFzs6zafOXeY0JCgAxRPk1FSygAqjADyqojAgiIkZJTUdAzchnqaUAASEACGJlAAdPnJqYGZPq5QUAD86Vm05FQ09FDBYRFi5eVV3r7EBMU+QaHhkW3tAFyyGdnK+bld1D19Sk2DEfxlUON8ANwS7tAA6ozEANZwAAoWRwCsACwEAMp18Y0s7FxQAD4qClGwCCgYLB4QhzPz3ZTyXC4fj8XbgA5HU7CP5INCYHD4AignqvTjAT7fKEQn78IA

### 💻 Code

This is the simplified code
```ts
type AssignResult<Arr extends object[]> = Arr

// [null, number, undefined, string] => [number, string]
type Filter<Arr, ToOmit> = Arr extends [infer Head, ...infer Tail]
  ? Head extends ToOmit
    ? Filter<Tail, ToOmit>
    : [Head, ...Filter<Tail, ToOmit>]
  : [];

type WorksPrior54<S extends object | null> = AssignResult<Filter<S, null>>

type Works = AssignResult<Filter<object | null, null>>
```
<details>
  <summary>This is the full code (error message is slightly different, but probably they are the same):</summary>

```typescript
type AssignResult<Arr extends object[]> = Arr extends [...infer Rest extends object[], infer Last]
  ? {
    [K in keyof Last | keyof AssignResult<Rest>]: K extends keyof Last
      ? Last[K]
      : K extends keyof AssignResult<Rest>
        ? AssignResult<Rest>[K]
        : never;
  }
  : object;

type Filter<Arr, ToOmit> = Arr extends [infer Head, ...infer Tail]
  ? Head extends ToOmit
    ? Filter<Tail, ToOmit>
    : [Head, ...Filter<Tail, ToOmit>]
  : [];

declare function assignByDescriptors<
  Target extends object,
  // replace the two lines below to make it work with the this line
  // Sources extends (object | null | undefined)[],
  Source extends object | null | undefined,
  Sources extends Source[],
  Result extends AssignResult<[Target, ...Filter<Sources, null | undefined>]> = AssignResult<[Target, ...Filter<Sources, null | undefined>]>
>(target: Target, ...sources: Sources): Result
```

</details>

### 🙁 Actual behavior

I would expect to have no error for 5.4, the same as there was no error before it. Especially considering that there were not breaking changes in 5.4 announcement.

As for the simplified code, there should be no difference between how `WorksPrior54` and `Works`.

As for the full version of the code, there should be no difference if part of `Sources` type parameter is extracted into an intermediate `Source` type parameter, or not

### 🙂 Expected behavior

Error (in the simplified version): 
```
TS2344: Type Filter<S, null> does not satisfy the constraint object[]
Type [] | [unknown] is not assignable to type object[]
Type [unknown] is not assignable to type object[]
```
Error (in the full version):
```
TS2344: Type
[Target, ...Filter<Sources, null | undefined>]
does not satisfy the constraint object[]
Type
Target | Filter<Sources, null | undefined>[number]
is not assignable to type object
Type Filter<Sources, null | undefined>[number] is not assignable to type object
Type
(Source extends null | undefined ? [] : [Source])[number] | (Source extends null | undefined ? [] : [Source])[number]
is not assignable to type object
Type
(Source extends null | undefined ? [] : [Source])[number]
is not assignable to type object
```

**Comment by DanielRosenwasser** [comment]
I think this is working as intended in TypeScript 5.4:

https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#more-accurate-conditional-type-constraints

> In a conditional type like `T extends Foo ? TrueBranch : FalseBranch`, where `T` is generic, the type system would look at the constraint of `T`, substitute it in for `T` itself, and decide on either the true or false branch.
> 
> But this behavior was inaccurate because it was overly-eager.
> Even if the constraint of `T` isn't assignable to `Foo`, that doesn't mean that it won't be instantiated with something that is.
> And so the more correct behavior is to produce a union type for the constraint of the conditional type in cases where it can't be proven that `T` *never* or *always* extends `Foo.`
> 
> TypeScript 5.4 adopts this more accurate behavior.
> What this means in practice is that you may begin to find that some conditional type instances are no longer compatible with their branches.

The way you can get around this is either

1. by changing the constraint of `Arr` in `AssignResult` to `unknown[]` instead of `object[]` ([playground link](https://www.typescriptlang.org/play?ts=5.4.2#code/C4TwDgpgBAggznAlgcwHYCUJwK4BtgA8MATsVBAB7ASoAmcU2qA1qgPYDuqA2gLoB8UALyxSAKDEB6SVG6o8uADRR5AWwBGEYsqa0IAM0SoItZXGDEjyXsMFzsGrWYtXeY0JCgAxRPi1FSZQAVNgB5VURgQRESMkpqOgZuI30tKAAJCABDUygAOgKUtKCs3zcoKAB+DOzacioaeigQ8MixCorqnz9iAhLfYLCIqPaOgC5ZTJzlArzu6l7+pWahyP5yqAm+AG4JD2gAdTZiZjgABUtjgFYAFgIAZXqEprZ1ACsIAGNgKAAfFQU0VgCBQGCweEI83892U8lwuH4-D24EOx1OwmBSDQmBw+AIUN6rw+3z+APhsMB-CAA)),
2. by adding an `object` constraint to `Head` and an `object[]` constraint to `Tail` ([playground link](https://www.typescriptlang.org/play?ts=5.4.2#code/C4TwDgpgBAggznAlgcwHYCUJwK4BtgA8MATsVBAB7ASoAmcUA9gEYBWEAxsANoC6AfFAC8sUgCgxAeklRuqPLgA0UeQFtmEYsux0IAM0SoItZXGDFDyXsMFzs6zafOXeY0JCgAxRPk1FSygAqjADyqojAgiIkZJTUdAzchnqaUAASEACGtORUNPRMbJzAygB05cmpgZk+ufEFLOxcfK5QUAD86Vk5cfkMwWERYm1tnd6+xATVPkGh4ZHDIwBcshnZZeXj1JPTSlAD8-ytUCt8ANwS7tAA6ozEANZwAAoWdwCsACwEAMp1fYVNYBQAA+KgUUVgCBQGCweEIWz832U8lwuH4-Eu4Bud0ewkhSDQmBw+AICMmjWKILBqOR4P4QA)).

**Comment by Alexsey** [comment]
@DanielRosenwasser Thank you for taking a look, this is probably the change that cause the error!

But here the situation is right the opposite of how it says it should work:
"if the constraint of `T` isn't assignable to `Foo`, that doesn't mean that it won't be instantiated with something that is."
-> in the example:
"if the condition of `Filter` isn't assignable to `AssignResult`, that doesn't mean that it won't be instantiated with something that is.". And `Filter` will be instantiated with `object[]` - exactly with the type that `AssignResult` is expecting!
So here we are having a "cases where it can't be proven that `T` never or always extends `Foo`", but the compiler is considering that it can be proven

Moreover, if you would take a look at the full example you will note that the fix I've proposed was just to inline the intermediate `Source` type parameter. And everything will work with `Filter` and `AssignResult` as they are

**Comment by DanielRosenwasser** [comment]
So without having been deeply in the guts of conditional type instantiation, I'm going to do my best on this one!

From the https://github.com/microsoft/TypeScript/pull/56004:

> A type variable represents any possible type within its constraint. So, given a type parameter `T` with the constraint `C`, the constraint of `T extends X ? A : B` is
> 
> * `A` when `C` is known to always extend `X`,
> * `B` when `C` is known to never extend `X`, or
> * `A | B` when `C` possibly extends `X`.
> 
> We previously didn't consider the third possibility.

So previously, we'd end up saying "`object | null`, eh? Do any of those that extend a `[infer Head, ...infer Tail]`? Definitely not!"

So we'd always jump into the negative case and end up with `[]`. That satisfies basically every array type, but not every tuple type. [Try it out in the 5.3.3 playground](https://www.typescriptlang.org/play?ts=5.3.3#code/C4TwDgpgBAYglgG2BATgHgIIpQGigFQHsB5AWzmAD4oBeKLFKCAD2QDsATAZygG042AM1RQAEhACGHPADo5A4Y3wTEAXQBQUKAH4xkjk1YROPImQqatO2ImTpliPGfJVLWgFx9xU2XPhJUNAcEJxIXSg0PPlUAbnV1QQBXNgBjYDhCNihBNABlQ3ZuKEIAIwArCDSoAB8oNkSEBEoACmZPfzs8vHrGygBKKABvSxTMrmAoCU9SirTeVVooZjitUbZxqBLPetIS1HnF5agAemOoAHVRDHxtEbGJlM9xlAEAcwO6I9OLq5vLO-WEw4ng+SxiJzOxAA1hIQHhgAALCQTFhgBAqdZQCgyAEbCAgmaVYALT7g74ATUSYHhCLgPEy0FeEGAPAkWVQKEIjAAtFBSBIoRAeFxjCK6oQAO44gC+6iAA).

```
type Filter<Arr, ToOmit> = Arr extends [infer Head, ...infer Tail]
  ? Head extends ToOmit
    ? Filter<Tail, ToOmit>
    : [Head, ...Filter<Tail, ToOmit>]
  : [];

function f<S extends object | null>(x: Filter<S, null>) {
  const a: object[] = x;
  const b: number[] = x; // WHAT?
  const c: string[] = x; // WHAT?
  
  const d: [] = x; // Okay, that explains it.
  const e: [object] = x; // Yup, this one gets an error - makes sense now.
}
```

As you can see from the examples, that's not correct though! An `object` doesn't extend an array, but that doesn't necessarily mean `S` itself couldn't be an array. [In 5.4+, these all error as expected](https://www.typescriptlang.org/play?ts=5.4.2#code/C4TwDgpgBAYglgG2BATgHgIIpQGigFQHsB5AWzmAD4oBeKLFKCAD2QDsATAZygG042AM1RQAEhACGHPADo5A4Y3wTEAXQBQUKAH4xkjk1YROPImQqatO2ImTpliPGfJVLWgFx9xU2XPhJUNAcEJxIXSg0PPlUAbnV1QQBXNgBjYDhCNihBNABlQ3ZuKEIAIwArCDSoAB8oNkSEBEoACmZPfzs8vHrGygBKKABvSxTMrmAoCU9SirTeVVooZjitUbZxqBLPetIS1HnF5agAemOoAHVRDHxtEbGJlM9xlAEAcwO6I9OLq5vLO-WEw4ng+SxiJzOxAA1hIQHhgAALCQTFhgBAqdZQCgyAEbCAgmaVYALT7g74ATUSYHhCLgPEy0FeEGAPAkWVQKEIjAAtFBSBIoRAeFxjCK6oQAO44gC+6iAA).

_____

> inlining it is fixing the error

Not sure exactly what you mean, but it might be related to a tradeoff we consciously made. The new behavior only kicks in on higher-order types (i.e. type parameters). In other words, if you pass in `object | null`, we don't say "well *maybe* that `object` is actually an array type" and try all the branches.

**Comment by Alexsey** [comment]
@DanielRosenwasser, I'm terribly sorry. I made a typo when simplifying the initial code. Of course, `object | null` is never an array—it should have been `(object | null)[]`, and this one is working just fine!

I will take another try to simplify the initial code to a short snippet tomorrow. Thank you for your time, I truly appreciate your effort in taking a look at the issue!
