### ISSUE TITLE
Duplicate entires in SyntaxKind enum

### ISSUE THREAD

**Issue by sebbi08** [microsoft/TypeScript#57876]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Here you can see that some indices are duplicated in the SyntaxKind enum

https://github.com/microsoft/TypeScript/blob/6ea273cdcca99db809074d2b2d38d0e5b59ee81b/lib/typescript.d.ts#L4558

**Comment by MartinJohns** [comment]
And?

**Comment by sebbi08** [comment]
shouldn't ENUMmembers be unique ? 

I am wanting to print an error message about a SyntaxKind.NumericLiteral but when accasing SyntaxKind[typeNode.kind] it gives my "FirstLiteralToken" or are they the same. 

But i see there is already a discusion as always found after seaching for an hour :/ 

https://github.com/microsoft/TypeScript/issues/18062

**Comment by RyanCavanaugh** [comment]
See also #54950
