### ISSUE TITLE
NoInfer and overloaded function argument inference

### ISSUE THREAD

**Issue by kevinresol** [microsoft/TypeScript#57873]
### 🔎 Search Terms

NoInfer, overload

### 🕗 Version & Regression Information

Version 5.4.3
- I was unable to test this on prior versions because this is a new feature

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcYdhkwQAKRALngDkcBJVREGAHgoEp4BeAPngA3HFmD8utbn0EixAbgBQoSLAQp02PIWKly7AIL8qtBs1YcKsAOa0DPAcNHjJ8KzFvx7MpwsWKwPABnDHgADykHWWc+HRIySmlHAEYuJUDUEPgATykbWhCYLFRrKN9gWKJ48goKITLUpSA

### 💻 Code

```ts
declare function produce(f: NoInfer<() => void>): () => void;
declare function produce<A>(f: NoInfer<(arg: A) => void>): (arg: A) => void;

const x: () => void = produce(() => 1); // works
const y: (arg: string) => void = produce((v) => 1); // Parameter 'v' implicitly has an 'any' type.
```

### 🙁 Actual behavior

Because `const y` is explicitly typed and thanks to the new utility `NoInfer` type, the compiler is able to figure out (from the return type) it is calling the `produce<string>()` overload. (Without `NoInfer` it would just be `produce<any>()`). 

However, apparently it does not apply this knowledge to the function parameter `f` and thus the non type-hinted argument `v` is inferred as `any`

![Screenshot 2024-03-21 at 12 04 31](https://github.com/microsoft/TypeScript/assets/1103788/ab13b92d-4b17-4a9d-9f56-d4d0e603681c)

### 🙂 Expected behavior

Since the compiler already knows `f` is of type `NoInfer<(arg:string)=>void>` it should be able to infer the lambda argument `v` to be of `string` type.

![Screenshot 2024-03-21 at 12 13 46](https://github.com/microsoft/TypeScript/assets/1103788/f7ab9d10-46d2-456a-947d-951e65afb837)

**Comment by Andarist** [comment]
This isn't related to `NoInfer` as this doesn't assign the correct contextual parameter here either:
```ts
declare function produce(f: () => void): () => void;
declare function produce<A>(f: (arg: A) => void): (arg: A) => void;
const y: (arg: string) => void = produce((v) => 1);
```

There is a good chance that this PR might solve your issue: https://github.com/microsoft/TypeScript/pull/57421

**Comment by Andarist** [comment]
Since @RyanCavanaugh has prepared a playground for that mentioned PR (thanks!) we can now quickly confirm that it fixes this issue: [TS playground](https://www.staging-typescript.org/play?ts=5.5.0-pr-57421-28#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcYdhkwQAKRALngoEp4BeAPngDccth7aHm2nbgG4AsAChQkWAhTpseQsVLkAPAEEWVPrADmtdY1YcuPHTH3xDAkyIlg8AZwzwAnucvOYWVLqODTZiUSMkoKdn94AEZ6MXEJKWg4JDRMXHwiEPIAJm14ADkcAElURBAYVX5jIWAWXjpImrjEmRT5dOCVEGyNLRoC4tLyyr0DRtM6jzGbJvsnF1dsqfgvHz8ZwKZO0NzwyJjhIA)
