### ISSUE TITLE
NoInfer type not being narrowed properly

### ISSUE THREAD

**Issue by matheusvellone** [microsoft/TypeScript#57883]
### 🔎 Search Terms

NoInfer narrowing not working as expected

### 🕗 Version & Regression Information

- This was introduced with `NoInfer` utility type
- The error persists even in Playground's nightly version (`5.5.0-dev20240321`)

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYOwrgtgBAKgggZQNIH0BycCyBRBUDeAsAFBSwCGAzgNYoCMANCWTFbQExPEC+JJAxgHsQlAC5QACuQBO5CMFHBplKAF4CzKAG14ydFlwA6VjXoBdAFwEootnSujpYYFG5cyOxKgw4Extijslta2NOwOTi5uJLzEJKIAngAOLlKy8orKAPIAZgA8MFDAAB6KIAAmKrreBggAfGpQABSJKYI5kjJyCkqUAJQ6ZnzErS4A4gpp3ZmUuQVFpaCVsF76vg3qTX1qDVMZvXMwdcOjFDQAwoIQAEaCKupEpNom1FAAliArej64wY9kZFC1CsL00ZCSXX2yisaEEAEkQDklHk9j1svkXg0AD5QCaiVEzQ5sOrHJ6xbieb61IZxYhCETiJwgF6NJrlci2EFsS43O7bVQNf5QeliEJsBhQCHpNEqbiNdm2YZkEXiADmk0hMtZ-MFYPeHRayWA7UlmpmalU6gA5DkwCB+KI3sIrdshQCoNIFGBpJ8pdNels9bE9QB6ENQAASShcMDwYjeABsE1BKAALQQAdxsqY5UCtfqhlCtUAg5ASUGuLnIUAARHiCQccjXDKHwzBU28VAnBIJqF23tQq58lNJBNIJZX+OQwJQXG9RCoSikHcBytnOzZBBWXDX8DY7FZboIE8ByJ85Ti90DwhWeyezwBuVw11tQOEdDMuT0QQQANxcoipjusIIki0g1lAOSjtACYfC4dAABwSvOUAZmOfZQFQCzLoo5R6p6ojer6Zq9JowZPCqprpPcUDqviJHKIGtLKsIlDHsAhjdqqLTilRcj9DEQA

### 💻 Code

```ts
enum TASK_NAMES {
  Task_1,
  Task_2,
}

const Parameters = {
  [TASK_NAMES.Task_1]: { task1: true },
  [TASK_NAMES.Task_2]: { task2: true },
}

type ParametersOf<T extends TASK_NAMES> = (typeof Parameters)[T]

type GetParametersOf<T extends TASK_NAMES> = () => ParametersOf<T>

type TaskCombos = {
  [Task in TASK_NAMES]: {
    task: Task
    parameters: NoInfer<ParametersOf<Task> | GetParametersOf<Task>>
  }
}[TASK_NAMES]

const runTask = (data: TaskCombos) => {
  const { task, parameters } = data

  const getParameters = () => {
    if (typeof parameters === 'function') {
      return parameters()
    }

    // Here TS still show that 'parameters' may be a "GetParametersOf".
    // This looks like an error, because its expected this to be "{ task1: boolean } | { task2: boolean; }"
    // If we remove the "NoInfer" from line 18, it works as expected
    return parameters
  }

  const params = getParameters()

  console.log(task, params)
}
```

### 🙁 Actual behavior

`NoInfer` not being narrowed by exclusion (`typeof` condition with a `return` statement)

### 🙂 Expected behavior

Expected `NoInfer` type to be narrowed correctly outside a `typeof` condition with a `return` statement

### Additional information about the issue

I've used `enum` to better replicate my scenario, but I believe this is reproducible without enums too

**Comment by RyanCavanaugh** [comment]
Narrowing can't narrow `X<A | B>` to `A` or `B` when `X` is nondistributive like `NoInfer` is. You need to write `NoInfer<ParametersOf<Task>> | NoInfer<GetParametersOf<Task>>`

**Comment by RyanCavanaugh** [comment]
Aside: I'm also trying to figure out why you're using `NoInfer` in the first place here.

**Comment by matheusvellone** [comment]
> Aside: I'm also trying to figure out why you're using NoInfer in the first place here.

I removed the place where I define an array of `TaskCombos[]`.

```ts
const combos = [
  {
    task: TASK_NAMES.Task1,
    parameters: { task2: true }, // This is wrong
  },
] satisfies TaskCombos[]
```

I want to avoid TS telling me that I'm passing the wrong `task`, because in this case the `task` "locks" the type and `parameters` should respect it (not inferring from it)

I'll close the issue, since making it `NoInfer<ParametersOf<Task>> | NoInfer<GetParametersOf<Task>>` works.

**Comment by RyanCavanaugh** [comment]
That's also an error without using `NoInfer`, though?

**Comment by matheusvellone** [comment]
Yes, without `NoInfer` the error still appears, but in more complex cases, with more parameters and more tasks, I feel that the error is better presented when using `NoInfer` and also makes more sense from the developer experience sight

In my project, there are around 80 tasks, each one with its parameter type.
But some tasks parameters are very similar, which tricks (i think) TS into showing that I'm using the wrong task for that parameters in some cases.

In this case, `NoInfer` makes sense to me, because I'm telling TS to avoid inferring the Task from the Parameters and only trust the `task` prop
