### ISSUE TITLE
Adding methods to class prototype produces error

### ISSUE THREAD

**Issue by hath995** [Microsoft/TypeScript#5788]
I'm trying to build a class which has a number of very similar methods, such that they could be constructed using a higher order function. I want them to be saved on the class to conform to an existing interface and for convenience. 

```
class MyObj {
... //plenty of nice unique functions here
}

function generateMethod(fn: (a: MyObj, b: MyObj) => MyObj ) {
///business logic/bookeeping here
  return function(that: MyObj) {
    //more logic
    return fn(this, that);
  }
}

MyObj.prototype.add = generateMethod(add); //line 20 lets says
MyObj.prototype.subtract = generateMethod(sub);
// a fair number more of these repetitive methods
```
When I compile I get the error message that
line 20: Property 'add' does not exist on type 'MyObj' 
Which is a little confusing considering I am adding that property at that time. 

Is there an existing mechanism I can use to address this error? Is there another approach besides abandoning the class syntax and reverting to all prototypical construction?

**Comment by weswigham** [comment]
Try adding a declaration like
```ts
interface MyObj { // Same name as class
  add(...args: any[]): any;
}
```
below you class to tell TS about these generated members and their types. Class & interface merging is a fairly recent addition to TS.

**Comment by hath995** [comment]
That produces numerous errors, among them not related to generics:
Individual declarations in merged declaration 'MyObj' must be all exported or all local.
Individual declarations in merged declaration 'Series' must be all exported or all local.

I am running the nightly typescript build.

**Comment by WreckedAvent** [comment]
@weswigham 's suggestion works fine for me, check out this [playground](http://www.typescriptlang.org/Playground#src=class%20MyObj%20%7B%0A%09%2F%2F%20stuff%20%2F%2F%0A%7D%0A%0A%2F%2F%20stubs%20to%20get%20the%20example%20to%20compile%0Afunction%20add(a%3A%20MyObj%2C%20b%3A%20MyObj)%20%7B%20return%20a%3B%20%7D%0Afunction%20sub(a%3A%20MyObj%2C%20b%3A%20MyObj)%20%7B%20return%20b%3B%20%7D%0A%0Afunction%20generateMethod(fn%3A%20(a%3A%20MyObj%2C%20b%3A%20MyObj)%20%3D%3E%20MyObj%20)%20%7B%0A%2F%2F%2Fbusiness%20logic%2Fbookeeping%20here%0A%20%20return%20function(that%3A%20MyObj)%20%7B%0A%20%20%20%20%2F%2Fmore%20logic%0A%20%20%20%20return%20fn(this%2C%20that)%3B%0A%20%20%7D%0A%7D%0A%0Ainterface%20MyObj%20%7B%0A%09add(a%3A%20MyObj%2C%20b%3A%20MyObj)%3A%20MyObj%0A%09subtract(a%3A%20MyObj%2C%20b%3A%20MyObj)%3A%20MyObj%0A%7D%0A%0AMyObj.prototype.add%20%3D%20generateMethod(add)%3B%20%2F%2Fline%2020%20lets%20says%0AMyObj.prototype.subtract%20%3D%20generateMethod(sub)%3B%0A%0Avar%20obj%20%3D%20new%20MyObj()%3B%0Aobj.add(obj%2C%20obj)%3B%20%2F%2F%20compiles%20fine) link. 

Your error sounds like you're not exporting both the interface and the class. [Both would have to be exported for the declaration to merge right](http://www.typescriptlang.org/Playground#src=export%20class%20MyObj%20%7B%0A%09%2F%2F%20stuff%20%2F%2F%0A%7D%0A%0A%2F%2F%20stubs%20to%20get%20the%20example%20to%20compile%0Afunction%20add(a%3A%20MyObj%2C%20b%3A%20MyObj)%20%7B%20return%20a%3B%20%7D%0Afunction%20sub(a%3A%20MyObj%2C%20b%3A%20MyObj)%20%7B%20return%20b%3B%20%7D%0A%0Afunction%20generateMethod(fn%3A%20(a%3A%20MyObj%2C%20b%3A%20MyObj)%20%3D%3E%20MyObj%20)%20%7B%0A%2F%2F%2Fbusiness%20logic%2Fbookeeping%20here%0A%20%20return%20function(that%3A%20MyObj)%20%7B%0A%20%20%20%20%2F%2Fmore%20logic%0A%20%20%20%20return%20fn(this%2C%20that)%3B%0A%20%20%7D%0A%7D%0A%0Aexport%20interface%20MyObj%20%7B%0A%09add(a%3A%20MyObj%2C%20b%3A%20MyObj)%3A%20MyObj%0A%09subtract(a%3A%20MyObj%2C%20b%3A%20MyObj)%3A%20MyObj%0A%7D%0A%0AMyObj.prototype.add%20%3D%20generateMethod(add)%3B%20%2F%2Fline%2020%20lets%20says%0AMyObj.prototype.subtract%20%3D%20generateMethod(sub)%3B%0A%0Avar%20obj%20%3D%20new%20MyObj()%3B%0Aobj.add(obj%2C%20obj)%3B%20%2F%2F%20compiles%20fine).

**Comment by hath995** [comment]
huh, it seems to be my editor plugin shows the errors when saving, but running tsc does compile just fine.

**Comment by hath995** [comment]
@weswigham and @WreckedAvent thanks for the help.
