### ISSUE TITLE
array in conditional type issue 

### ISSUE THREAD

**Issue by marc0n3** [microsoft/TypeScript#57881]
Hi this is the code to reproduce the issue
```typescript 
class Item{
    name:string
}
abstract class ItemContainer{
    items: Item[]
}

class Drawer extends ItemContainer{
    size:number
}




type ArrayInnerType< A> =  A extends (infer inferred)[]?inferred:A;



class Manager<T extends ItemContainer>{
    manage(object:T){
        type rightType = ArrayInnerType<ItemContainer["items"]>;
        type wrongType =ArrayInnerType<T["items"]>;
        //   ^?
    }
}
```

I expect the type of wrongType to be **Item** but it is `(inferred & inferred[]) | T["items"]`

can you help me understand why?
Thanks

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
