### ISSUE TITLE
can't narrow from `unknown` to "not a number or bigint"

### ISSUE THREAD

**Issue by ljharb** [microsoft/TypeScript#57899]
### 🔎 Search Terms

number bigint narrow

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

https://tsplay.dev/wX09ow

### 💻 Code

```ts
function nonNumeric(x: null | undefined | string | boolean | symbol | object, y: unknown) {
	return true;
}

function foo(x: unknown, y: unknown) {
	if (typeof x === 'number' || typeof x === 'bigint') {
		return false;
	}
	return nonNumeric(x, y);
}
```

### 🙁 Actual behavior

errors with `Argument of type 'unknown' is not assignable to parameter of type 'string | boolean | symbol | object | null | undefined'.(2345)`

### 🙂 Expected behavior

passes, because the typeof check ensures that `unknown` is properly narrowed to `string | boolean | symbol | object | null | undefined`.

**Comment by MartinJohns** [comment]
I would say this is a design limitation.

`unkown` is not a union of the types you listed, so the compiler can't narrow the type in the `else` branch. This would require a type "`unknown`, except `number`", which would first require negated types (#4196).

**Comment by ljharb** [comment]
Why isn't `unknown` a union of all possible types? I would expect it to be a named shorthand for `null | undefined | string | boolean | number | bigint | symbol | object` since that includes every possible JS value.

**Comment by ljharb** [comment]
oof, ok - that issue is actually my precise need for that exact same library. That's very unfortunate.

**Comment by craigphicks** [comment]
Consider this working code 
```
function nonNumericTypeof(typeofx: "string" | "boolean" | "symbol" | "undefined" | "object" | "function") {
	return true; 
}

function foo(x: unknown) {
    const t = typeof x;
	if (t === 'number' || t === 'bigint') {
		return false;
	}
    t; // const t: "string" | "boolean" | "symbol" | "undefined" | "object" | "function"
    return nonNumericTypeof(t);
}
```
Conceivably, type information could embed the results of `typeof` comparisons  (both true and false branches because `typeof` range is finite) .  However, there are reasons why that very hard to integrate into current TypeScript, one of which is that `number`, `string`, etc. can be promoted to objects for type comparison.

**Comment by ljharb** [comment]
How difficult it would be to achieve is entirely separate and not something I have knowledge of.

However, I can't conceive of any code where this narrowing would be incorrect, including your example.
