### ISSUE TITLE
Async/Await with custom promise when targeting ES6 and CommonJS

### ISSUE THREAD

**Issue by JerryGingerFox** [Microsoft/TypeScript#5789]
Seems like tsc uses invalid class name when targeting ES6 and CommonJS, at least with custom promises in async functions.

```typescript
// Task.ts
export class Task<T> extends Promise<T> {}

// Test.ts
import { Task } from "./Task";
class Test
{
    async Example<T>(): Task<T> {}
}
```

compiled to

```typescript
// Task.js
class Task extends Promise {}
exports.Task = Task;

// Test.js
var __awaiter = ...
var Task_1 = require("./Task");
class Test
{
    Example() { return __awaiter(this, void 0, Task, function* () {}); }
}
```

Instead of `return __awaiter(this, void 0, Task, function* () {});` should be `return __awaiter(this, void 0, Task_1.Task, function* () {});` since `Task` is imported as `Task_1.Task` when using commonjs.

1.8.0-dev.20151125
tsc --target es6 --module commonjs

**Comment by vladima** [comment]
@rbuckton can you take a look?

**Comment by JerryGingerFox** [comment]
Also if custom promise is referenced only as return type in async method tsc removes import from generated js.

**Comment by omefire** [comment]
Trying to repro this issue, I get the following generated .js:

-- Test.js:
```"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, Promise, generator) {
    return new Promise(function (resolve, reject) {
        generator = generator.call(thisArg, _arguments);
        function cast(value) { return value instanceof Promise && value.constructor === Promise ? value : new Promise(function (resolve) { resolve(value); }); }
        function onfulfill(value) { try { step("next", value); } catch (e) { reject(e); } }
        function onreject(value) { try { step("throw", value); } catch (e) { reject(e); } }
        function step(verb, value) {
            var result = generator[verb](value);
            result.done ? resolve(result.value) : cast(result.value).then(onfulfill, onreject);
        }
        step("next", void 0);
    });
};
class Test {
    Example() {
        return __awaiter(this, void 0, Task, function* () {
            return;
        });
    }
}
```

**Comment by omefire** [comment]
It seems to me like a require('Task') statement is missing from the generated js.

**Comment by JerryGingerFox** [comment]
@omefire Try this.

```typescript
// Test.ts

import { Task } from "./Task";
class Test
{
	async Example<T>(): Task<T> {}

	static Dummy(): string { return Task.toString(); }
}
```

As already mentioned, when class is referenced only as return type tsc removes import, so it's just a part of the problem - `__awaiter` still called with `Task`, when `Dummy` uses correct `Task_1.Task`. 

```javascript
"use strict";
var __awaiter = ...
var Task_1 = require("./Task");
class Test {
    Example() {
        return __awaiter(this, void 0, Task, function* () {});
    }
    static Dummy() { return Task_1.Task.toString(); }
}
```

**Comment by omefire** [comment]
@JerryGingerFox , Adding the 'Dummy' method, I've been able to repro and get the same results as you.
I'll keep investigating the issue ...

**Comment by rbuckton** [comment]
This is a regression. This used to work correctly, but a recent change to fix another issue regressed this functionality. I've added a test to validate this issue and prevent future regressions.

**Comment by mhegazy** [comment]
@omefire and @JerryGingerFox can you give `typescript@next` a try later tonight, and let us know if the issue is resolved.

**Comment by JerryGingerFox** [comment]
@mhegazy Fixed.

1.8.0-dev.20151202
tsc --target es6 --module commonjs

**Comment by mhegazy** [comment]
thanks @JerryGingerFox !
