### ISSUE TITLE
.NET (DLL) Compiler

### ISSUE THREAD

**Issue by Montago** [microsoft/TypeScript#579]
Could someone please explain to me why the Typescript Compiler is written in Typescript (JS) ??

One funky reason I can think of, is that it enables the online Typescript showcase / editor...

But for productivity it would make a lot more sense to write it in .NET (C# / VB#) - so it could be invoked in the build process or on the fly. Right now, developers have to do sorcery with Javascript engines, in order to use the compiler... 

In our solution we have a dynamic ressource-includer (somewhat mimicking BundleTable) which recently got upgraded with TypeScript support. The way we did it, was to include TSC.exe in the solution, which then dynamically compiles TypeScript ressources. 

When we wanted to publish this solution to our Test and Production environment, we discovered that TSC.exe is dependent on Internet Explorer 10 (the JS Engine) - our webservers only run IE9, so now our TS solution is broken (unless we upgrade our servers which is a big problem) 

I get that TS is opensource and all that stuff - but a .NET version would be awesome !

**Comment by DrSammyD** [comment]
I might suggest checking out (Edge.js)[https://github.com/tjanczuk/edge] as well if you want to run typescript in .NET

**Comment by mhegazy** [comment]
@Montago how are you installing typescript on your server? the installer has the correct logic and will detect which version of IE is installed and install the correct dlls. Looks like you copied some files from an installation on a different machine, and that would not work as you have wrong .dll. please run the installer on your build machine, or at least on a machine similar to it, and then capture the correct.dlls if that is what you want to do.
