### ISSUE TITLE
TypeScript cannot deduce decomposed array type.

### ISSUE THREAD

**Issue by jun-sheaf** [microsoft/TypeScript#57904]
### 🔎 Search Terms

array, types

### 🕗 Version & Regression Information

N/A

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDOwBOBLAdgcwNoF0oIAPYCTAEySgKgB8aUMdCHcmtsAaKAOn444ChAPxQ0AV2gAuKADMAhgBskEANwAoJRGBQFsuIknqgA

### 💻 Code

```ts
type A = string[] extends [] | [string] | [string, ...string[]] ? true : false;
let a: A = true;
```

### 🙁 Actual behavior

The compiler throws because it doesn't understand the condition.

### 🙂 Expected behavior

The compiler should compile successfully.

**Comment by MartinJohns** [comment]
I don't see why it should. A mutable array with arbitrary amount of elements does neither extend a tuple that's always empty, nor a tuple with always exactly one element, nor a tuple that has at least one element.

**Comment by jun-sheaf** [comment]
> I don't see why it should. A mutable array with arbitrary amount of elements does neither extend a tuple that's always empty, nor a tuple with always exactly one element, nor a tuple that has at least one element.

I'm sorry, I don't understand what is being stated here. Assuming you used tuple to distinguish between resizable and fixed-sized arrays, then it's incorrect to assume `[string, ...string[]]` is a tuple with at least 1 element. This can be seen with the base case `[...string[]]` which `string[]` extends to correctly.

**Comment by snarbies** [comment]
It does seem inconsistent. If, conceptually, `boolean` extends `true | false` (only) when the union is taken as a whole, it follows that `T[]` extends `[] | [T, ...T[]]` in much the same way. `[] | [T, ...T[]]` could be reduced to `[...T[]]`, which typescript *does* treat as equivalent to `T[]`.

**Comment by jun-sheaf** [comment]
> If a value is not assignable to any member of a union individually, it's not assignable to the union.

This is completely false. @snarbies came up with the very simple example of `boolean extends true | false`.

**Comment by snarbies** [comment]
Well to be fair, `boolean` is literally just an alias for `true | false`. I'm just grasping at straws trying to come up with a "conceptual union" that's not defined in terms of a union in typescript.

**Comment by nmain** [comment]
The exact example given above can be easily rewritten to give the desired output, and be much simpler too:

```typescript
type A = true;
let a: A = true;
```

Is this `[] | [T] | [T, ...T]` construction something that actually comes up in code or is it just a case of "I can reason that something is true, so the type checker should be able to prove it."?

**Comment by RyanCavanaugh** [comment]
https://github.com/microsoft/TypeScript/issues/57904#issuecomment-2015699231 is correct

T is assignable to A | B | C if there's a valid assignment from T to A, T to B, or T to C. That's it. The relationships between A, B, and C aren't considered.

TypeScript isn't a theorem prover and can't use the sort of "If it wasn't A, then it must have been B or C, and if it wasn't B, then it must have been C, therefore it's a C" logic that you're applying to reach that result.

**Comment by jcalz** [comment]
The kind of machinery needed to verify things like this in general seems like it would be unscalably expensive. Try to imagine implementing the compiler to notice this. Would it have to split every array type into a potentially unbounded union of various tuple types? Or look at every union of tuple types and try to figure out how to combine them? Would anyone have an idea of how this would happen in a scalable way? It feels like [this @RyanCavanaugh Twitter thread](https://twitter.com/SeaRyanC/status/1544414378383925250): any straightforward analysis would quickly become impossible for all but the most trivial of cases.

**Comment by jun-sheaf** [comment]
It seems this issue was misconstrued over the course of discussion. The purpose of this issue is to resolve the specific case when an array type is compared against a union of tuples of varying length, not for any `A`, `B`, and `C` in `A extends B | C`. The hope was that TypeScript could reduce the union, but since the assumption in https://github.com/microsoft/TypeScript/issues/57904#issuecomment-2015344280 is correct, it seems the compiler is limited in this area. Please feel free to close the issue.

**Comment by RyanCavanaugh** [comment]
Gonna be pondering whether `{ x: string } > { y: number }` for the purposes of that tree for the whole weekend 😉

**Comment by jun-sheaf** [comment]
@RyanCavanaugh I think there is a misunderstanding lol. The case in https://github.com/microsoft/TypeScript/issues/57904#issuecomment-2015814086 I was talking about is when you are comparing arrays and tuples of the same type (`number[], [number], etc.`). Nothing more general than that.

**Comment by fatcerberus** [comment]
@jun-sheaf Point taken, but since this is a type-level question (is type A assignable to type B), generally the preference is to have general rules that can be applied uniformly to any type rather than a bunch of special cases.
