### ISSUE TITLE
array in conditional type issue

### ISSUE THREAD

**Issue by marc0n3** [microsoft/TypeScript#57901]
### 🔎 Search Terms

array in conditional type issue inheritance accessor function

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAECSAuBTAtgbwFDS9AdmZiAhAFwTwBOAljgOboC+6YARmeWMPNKJDAigGEA9jnhhqichmzRKSZBBJx5AbQC6DdOh5RoAEXYB3SdEQAPJDgAmfecNHick6dgiUAXkWI4ArsmaSmlpa8ACeAA6I0ACC5OyhsDhO5AAqEYgAPDEAfNAAvFjRphaI1jAAFNQAZibVkuSIVgCU6gD8dXGNxNEA3MHa4LoAsmB4NJIZKcWWNsqCImIS5NkuWMijYOPlQswAVoicxClNqzLQYZHQVDQAFvBplwWx8YnJD5n8yPaLySoARHIUBA-mpsn0ztgAPSQiEAPVamAh53S0EM5BENHe+WeYASSUk70m-0BChBYMREOh2HhFOgjHoQA

### 💻 Code

```ts
class Item{
    name!:string
}
abstract class ItemContainer{
    items!: Item[]
}

class Drawer extends ItemContainer{
    size!:number
}




type ArrayInnerType< A> =  A extends (infer inferred)[]?inferred:A;



class Manager<T extends ItemContainer>{
    manage(object:T){
        type rightType = ArrayInnerType<ItemContainer["items"]>;
        //      ^?
        type wrongType =ArrayInnerType<T["items"]>;
        //   ^?
    }
}
```

### 🙁 Actual behavior

actual type of wrongType is `(inferred & inferred[]) | T["items"]`

### 🙂 Expected behavior

wrongType  is Item

**Comment by MartinJohns** [comment]
This is a design limitation. Resolving of conditional types involving unbound generic types is deferred. The compiler does not know what type `T` is, so it can't know what the conditional type resolves to.

**Comment by marc0n3** [comment]
Thanks!
cannot the fact that a base class for T (ItemContainer) is defined help in getting at least base class property types?

**Comment by RyanCavanaugh** [comment]
It'd be wrong to produce `Item` here since `T` might be instantiated with a class with a more-specific type in that field, e.g.
```ts
class Item {
    name!: string
}
class SuperItem extends Item {
    isSuper!: true;
}
abstract class ItemContainer {
    items!: Item[]
}
class SuperItemContainer extends ItemContainer {
    items!: SuperItem[];
}

class Drawer extends ItemContainer {
    size!: number
}

type ArrayInnerType<A> = A extends (infer inferred)[] ? inferred : A;

class Manager<T extends ItemContainer> {
    manage(object: T): ArrayInnerType<T["items"]> {
        // Alleged: Should be just 'Item'
        type wrongType = ArrayInnerType<T["items"]>;
        // Then this is OK
        const p: wrongType = new Item();
        return p;
    }
}

const p = new Manager<SuperItemContainer>();
// x: SuperItem, but it's actually an Item
const x = p.manage(new SuperItemContainer());

```
