### ISSUE TITLE
missing import for `fetchUrl` in quick fix menu

### ISSUE THREAD

**Issue by justschen** [microsoft/TypeScript#57907]
Well yes, my import is valid, the import is suggested while typing, see for "fetchUrl" :
<img width="553" alt="Capture d’écran 2024-03-22 à 09 46 50" src="https://github.com/microsoft/vscode/assets/5735310/3dac64be-f577-48bc-8861-56e05d608361">

However, the import is not suggested to me on the quick fix and nothing happens when using Cmd + S :
<img width="498" alt="Capture d’écran 2024-03-22 à 09 47 07" src="https://github.com/microsoft/vscode/assets/5735310/2b848904-5c2b-445d-ba8b-bc83aeaa9bdc">

_Originally posted by @kasty in https://github.com/microsoft/vscode/issues/208293#issuecomment-2014638336_

**Comment by RyanCavanaugh** [comment]
Please open a new issue with complete repro steps. Thanks!

**Comment by RyanCavanaugh** [comment]
cc @kasty whose code this is
