### ISSUE TITLE
Add missing test coverage found in #57909

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#57911]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

#57909 hit two DT tests and 1 user project but didn't affect any compiler baselines. We need equivalent coverage from those breaks

**Comment by Andarist** [comment]
FYI, I'm already in the process of extracting those test cases

**Comment by Andarist** [comment]
I'm leaving this here for posterity: [TS playground](https://www.typescriptlang.org/play?ts=5.4.3#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4Aoc4AOxiSk3STgFEAPdGABRzAGc4Ab3Jw4ANxQAbAK5IAXAQCC+OAB8CAITLkAvpQAmSNJJRE4madQzAI1OGiIo6LSUhBJaAHi5wkbOtT6AoI6AHwAFCJwMACeYPKIxDAAdABilta2AMK4kNQeMN6haomcyTngtgVZJnx8RSV8MFA0AOYANFFgvHwA-ArhyGWKMM3AAEbSdAIAZHBcAJQl1NKSkp2iyVtoABbAkvpE1ApDGMmnMAByEIYA2gC65AsnSedJLm4FRRTkhsamzFc8AA6lAUGB4lAXmUAFIAZQAGh93LQctQmlBpBhoJ52JweBB+KEfgB6En2aRQI7wGiYegeNBIcgOVDOVwomDhUHgyHtITiKSyBT4LIqHQLChkuB8FDuOAoAQocYQMRIPkAK2kTTgAHdgDAdtEdsxafQiPponFmKZWtIOb42GBJMA0PrJDE4N0VcBDBbjURmY42Z8vHiMASiVywRD6HzBAKZAkRWKJeQpTqdk44K0IDTqHSqUgLbYjcxxmCrIbwmgVaZgChaPLqDEAAbSpCuDBFuAq+j2WzNFASFoN+Bh7g9BaB1lIZFfBsxCLcmNQOMJoUEUVwcU-Gh0BhMODpKwwGzUCp5L4+AC8QjCQii4S9-AUi2hGDnXgXxXUKzWFD0P4TDMf46jgC8qi8LhimEUQa3RZosRgaAnx6V9U1EKVHH0Wx3U9NDShw6h3W+XQqFoehGEZcDckgmAagVeobzvGConyHU4FQwk+HQhQIPyKDiTI8j9yo5gLk-QoogAFQdAIgmlMZqFaEp4SRdlqlsDEkJxb84GvKJRHUDE2kM1TEUktFtOxKBPG-TpWNEWJ4gUaSAMoZzmDUyytMQmyGgMozOK4l95iWa9igkjSv2bH84D-SQpyC8J2M458eLC-Tin4+dYtTX4jGA5gLBPM97CDWdopgABJPgIBMOh9G8OSPAUkIIiiTyFGPTJz1ogTCmgkoctRWomLikzlI2fDuP6eZllWdYngUMQIB9H4gIBOAgTgZdIVq+qnCLBRvKqqy-OQ2zxwjPghOnI7JIOhqiyjHl6Ceo79DXCRE2FLcd3u4MOQ+xrcQ4cMeiXaN9rq56vv5H6N2TbdUxZB6qpBos7Ni16V0x+H40RpN-olOAyQMQqtvg7V0oUBcHgoTaQN8xSnDp5tJXJNBKWpPDTSgHi03JcJ3ANG4liyKQTHGVwetPWxkh5Ej6fuPl8lVKAHjVu1xnoCIDWADLwgNjKVb5LZFagVoMvV+gHnC4oVhAXXVyNQ3FCt9mYi1+UrZtpANfthQnZdziAGoAEYew1yQIBQfQpylEsUDgcsG12OB9Uz-N6EFqURaQMWE-AqWlVljJ5eoRWIWV5sfYXbXnb1429iNk2vZ9i2bVN5sHfinXYzdvgPdaDvVd962veefum6gcOo97KBY-jqcHmSMAtR2aunRiEK+D5JonHX3h6FPJA+FTKU6vlNZs5vyRM-gPgkDcARnQAa2tfth3rRsWwXNsOYn4diMI1aOfZ4KDh-qOOALZbaa3uC2cgQA). This one has a React-based repro (and its slimmed down version) - I don't want to include the full-blown React repro in the test suite.
