### ISSUE TITLE
Plugable modular ES.next features

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5791]
I want plugable modular es.next feature implementations and lib.d.ts likes babel plugins using npm for testability, maintainability, and quick release for each plugin. This is following of ecma script specifications development style.

Or segregate the type checking and transforms.

**Comment by mhegazy** [comment]
which features are you interested in?

**Comment by mhegazy** [comment]
related to https://github.com/Microsoft/TypeScript/issues/5595

**Comment by falsandtru** [comment]
It issue almost covered my needs (without pluggability). I move to #5595. Thanks for telling me.
