### ISSUE TITLE
FinalizationRegistry.unregister should return boolean instead of void

### ISSUE THREAD

**Issue by jameslan** [microsoft/TypeScript#57919]
### ⚙ Compilation target

ES2021

### ⚙ Library

es2021.weakref.d.ts

### Missing / Incorrect Definition

`FinalizationRegistry.unregister` is now defined as:

```typescript
    unregister(unregisterToken: WeakKey): void;
```

But it should return a boolean value that is `true` if at least one cell was unregistered and `false` if no cell was unregistered.

### Sample Code

```TypeScript
const obj = {};
const registry = new FinalizationRegistry(() => {});
registry.register(obj, obj, obj);
const removed = registry.unregister(obj); // failed compilation here
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/unregister

**Comment by heysujal** [comment]
Can I work on this issue?
