### ISSUE TITLE
LSP inserts duplicate `async` keyword

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/TypeScript#57928]
### 🔎 Search Terms

lsp, intellisense, suggestions, async keyword, autocomplete

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I don't have that much time on my hands.

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQgjgG8AoOOKYJAEzQAoA3TAGwFdgAuOJdgWwBGaADRwIMABZoeAZxhRkAcwCUPAApQI-BLOAAeeYqRKAfAG4yAXzJlsrTLNkEiASX5hWiD62D8aMM6ExOSUAPRhcAAqAJ5geABEjjFI2FQ09FAJcNLUcJh0+di4YPCy7EpKwPIIEEgAdBRwES5QcLLaeNSOdXCucNgFSBLpYFq07LiI8MhwUniemDFKWux0Ik0tguzwg0iI+0yy2BD0cADuCFJz0nCgOGWY-tEAynBMaLK1DU3WQA

### 💻 Code

```ts
export interface Foo {
  render(value: number, other: string): Promise<string>;
}

class FooImpl implements Foo {
  // Type "async render" here and accept suggestion.
  // For some reason I cannot reproduce it in the playground,
  // but can in vscode with the exact same TS version.
  
}
```

### 🙁 Actual behavior

This was originally discovered in https://github.com/denoland/deno/issues/23046#event-12225857552 . We assumed that it is an issue with the TSC fork in Deno's LSP, but turns out that the same issue exists in tsc itself. Best explained via a video:

https://github.com/microsoft/TypeScript/assets/1062408/d85446c7-2eb6-4d51-9030-be447210aabc

### 🙂 Expected behavior

It should not insert duplicative `async` keywods:

```ts
export interface Foo {
  render(value: number, other: string): Promise<string>;
}

class FooImpl implements Foo {
  // only one async keyword
  async render(value: number, other: string): Promise<string> {
    
  }
}
```

**Comment by jakebailey** [comment]
I think this was fixed in #57643?

**Comment by RyanCavanaugh** [comment]
@marvinhagemeister can you replicate in nightly? This likely depends on some user-specific settings and I don't want to mistriage

**Comment by RyanCavanaugh** [comment]
Thanks!
