### ISSUE TITLE
Why can't I declare a union of functions with different parameter types?

### ISSUE THREAD

**Issue by disog** [microsoft/TypeScript#57932]
### 🔎 Search Terms

merge function param union 

### 🕗 Version & Regression Information

- This is reproducible in the playground

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMYB4AqA+KBeKAKMAQwCdCBbALijQEocs0BuAWACgAbCYKAMyvmQoAzsGIBLBAHMsAH1iJUCOGQBGEYllx5CVQghB1sWQi1Y88ARhqmgA

### 💻 Code

```ts
type Func<T> = (param: T) => T;
let f: Func<string> | Func<number> = (a: any) => a;
f(1);
```

### 🙁 Actual behavior

The following error appears in the "Errors" tab:
```
Argument of type 'number' is not assignable to parameter of type 'never'.
```

### 🙂 Expected behavior

I'd expect the type of the function parameter be a union of the original types, just like it is done for the return type.

**Comment by RyanCavanaugh** [comment]
`f` might be a `Func<string>`, in which case it would receive a `number`.

**Comment by disog** [comment]
Fair enough. I'll close this issue then. Thanks!

**Comment by fatcerberus** [comment]
contravariance strikes again
