### ISSUE TITLE
Always true/false condition makes typeguard fail

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript#57939]
### 🔎 Search Terms

typeguard is always equal TS2367

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about typeguards

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAjgZwMowE5wgcwAoA3AQwBsAuZUiATwEpqzzU1k0c99kBvYZMmwBTGGGwoYdAA7CEIZC2QBeVcgBEnXAXUBuYAF9goSLESSAjIVLZ81AErCoCbABMAPFu4AaZBDAAtgBGwtgAfAA+-sGhTBxcBHwCgqgKhGxY2kQ2+AwqaiAUaMLIERHIUrLyNLbIAIRqAOReBI3IefwpXcjOEJzIdCo1+PrdKSJiEsiNjaMpRsmCvf0AXkM5usgA9FscABYIYOSuyCEaEMLEoeqLQqLiKDP6C+DQ8EgVAEzWtg5OLh4WvhfNEQuEooEwXEgUkunA0hkEtlbHlVMpkIVyMVkAAyHEVGRyBQ5epNUGhNodW5dZYwAbrWxzMYTB7TWa3BY0pCrBkjba7NAHI4nM7qcnYG5dFlTJ6GYBAA

### 💻 Code

```ts
function isString(val: any): val is string {
  return typeof val === "string";
}

function t1(arg: Record<string, number>|number): string {
    if ( isString(arg) === false || typeof arg !== 'string' ) {
        const y = arg;
        return '';
    }

    const z = arg; // should be "never"
    return '';
}

function t2(arg: Record<string, number>|number): string {
    if ( isString(arg) === false && typeof arg !== 'number' ) {
        const y = arg;
        return '';
    }

    const z = arg; // should be "number"
    return '';
}
```

### 🙁 Actual behavior

Types are incorrectly asserted when using a redundant condition

### 🙂 Expected behavior

Line 12 should be never
Line 22 should be number

### Additional information about the issue

Possibly related to https://github.com/microsoft/TypeScript/issues/55698

**Comment by RyanCavanaugh** [comment]
The first one is consistent with a regular "and", for which intersection is a good representation of what "must" be true about what's going on
```ts
    if (isString(arg)) {
      if (typeof arg === 'string') {
        const z = arg;
        //    ^?
      }
    }
```

The second one... I don't know what to make of this. It's possible for a `string` to end up there; the handling of this situation seems correct.
```ts
const s1: {} = "";
const s: Record<string, number> = s1;
t2(s);
```

**Comment by RyanCavanaugh** [comment]
`z` isn't unreachable in legal code, though.
```ts
const n1 = "hello";
const n2: { length: number } = n1;
const n3: Record<string, number> = n2;
t1(n3);
```
