### ISSUE TITLE
Make switch exhaustiveness check as a configuration of tsc.

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#57944]
### 🔍 Search Terms

switch exhaustiveness check

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The switch-exhaustiveness-check can help us avoid a lot of bugs when we add more union to an existed tag union type, but the tsc can not check the changes of tags union type, i know that the typescript-eslint can do exhaustiveness checking for switch statement, may be we can add this check to tsc too.

### 📃 Motivating Example

[tsc playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqlC8UDeAoKVSQFxQIxqgDsBDAWwhwGdgAnAS0IHMUBfKAH2QMwqgCYCxRr0IBXUgCMINVhy7oeOAMwFKEAB44xk6axQoAxgHtC1KKITI2xSrBSUA7nWAGAFlAAUogHQ8AlPJQBjbQuDio6OgELKxAA)
```typescript
type U = {
  type: 1
  name: string
} | {
  type: 2
  age: number
} | {
  type: 3
  sex: number
}

const u = {} as U
switch (u.type) {
  case 1: {
    
  }
}
```
No warnings in tsc.
```
No errors.
```

[typescript-eslint-playground](https://typescript-eslint.io/play/#ts=5.4.3&fileType=.tsx&code=C4TwDgpgBAqlC8UDeBYAUFKpIC4oEZ1MA7AQwFsI8BnYAJwEtiBzdAXygB9kitwqoAJl6lmA4gFdyAIwh12XHhj64oAZl7UIADzySZc9unQBjAPbFaUCQmQdS1WOmoB3BsBMALKAAoJAOmwIAEolTBMHaHw8VGVMXjZ2IA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAd0vzIAt6AHrwCGsZPkoA3RExTJafRGQDW6MAEZwYAL4htQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

Warnings in typescript-eslint playgound.
```
Switch is not exhaustive. Cases not matched: 2 | 3 13:9 - 13:15
> Add branches for missing cases.
```

### 💻 Use Cases

This would be useful when you do not or can not using typescript-eslint.

**Comment by MartinJohns** [comment]
Good practice to just add `default: u satisfies never`.
