### ISSUE TITLE
Compilation error when reassigning destructurig array variable names

### ISSUE THREAD

**Issue by wataBottl** [microsoft/TypeScript#57949]
### 🔎 Search Terms

"compilation error", "destructuring"

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=5&ssc=28&pln=1&pc=1#code/DYUwLgBA2glmIFsCMAaCdECYC6EC80AREoWgOSZnYDcAULQMYD2AdgM5OgB0wTA5gAoMyNMMwBKerHgj0MnPmhkAhmXIAjKkA

### 💻 Code

```ts
let [item1, item2] = ["1", '2'];

console.log(item1, item2)

[item1, item2] = ['a', 'b']
```

### 🙁 Actual behavior

Compilation error: 

### 🙂 Expected behavior

Expected the variables to be reassignable.

### Additional information about the issue

Adding a `;` at the end of `console.log` fixes the issue.

**Comment by MartinJohns** [comment]
This is working as intended. ASI does not insert a semicolon there, so you essentially wrote `console.log(item1, item2)[item1, item2] = ['a', 'b']`.
