### ISSUE TITLE
Inconsistent behavior with type inference for generic contraints

### ISSUE THREAD

**Issue by DanielBertocci** [microsoft/TypeScript#58009]
### 🔎 Search Terms

type, type inference, generic constraints

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries. Tested on version 4.3.3 and 5.5.0-dev.20240330 (the latest was available at the time of the issue creation).

### ⏯ Playground Link

[Playground here](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/PTAEGUFMBcFcAcBQ0Ce9KgKIA8CGBbeAG0gBU0MBeUAb1HgCcB7dB1ALlACMmmTcAdqAC+AbkQlooBpABmkGQIDGkTjgLEyFUNTqMWCjqGgNYGMYkQhQpABYZU6Y7dxSAlgJNMAJrBUBnZwxYAUhsdCVoSG9uSBcANzcmBgA6ZG0AYRYUcnQAHlIAPh1aRFBQAG0ABVAPUABrSBQmWRsAXU5SarbxCyswDPsletrW6HtQXH9-NwBzAXxIT1AAd2T6-zTJUCUh+s4s+ByKPPVCElzIYt16ZlYjEzMRcX6bSH8pFbdx0FmlhTcSh2TAEHwYuA80E2iFkIUiSSEUQ+BVAYSiAm8gTOmkuhQAFPBcOD8AdspcCoUAJSlcqE4kpfT3FAlR6QUSgawASSkSiYhDcJGhtKJBBSgiY4wUVTuhmZ1FZ7K5Um8THeoAEEuB-JIABpJoEwhEot40sLiSU9DK2ChOKznhywNzQCq1RqeXz4ALIHq3ajwpBItFTaBtrsA-tQIdjvkihbbgZrbbTOZFY7larAr7edrverNYaA8a0sIgA)

### 💻 Code

```ts

1. // Setup
2. type ExampleType = { property: boolean };
3. let reference: ExampleType = { property: true };
4. 
5. // The type that introduces the unexpected behavior.
6. type CopyType<T> = {
7.   [P in keyof T]: T[P];
8. };
9. 
10. // Check if the assignment works.
11. let check: CopyType<ExampleType> = { property: true };
12. 
13. // Test with generic constraints.
14. function test<T extends ExampleType>(param: CopyType<T>) {
15.   param.property = true; // It compiles.
16.   param.anotherProperty = true; // It does not compile, as expected.
17.   param = { property: true }; // It does not compile, not expected.
18.   let check: CopyType<T> = { property: true }; // It does not compile, not expected.
19. }

```

### 🙁 Actual behavior

The compiler partially infers the type: it doesn't compile as expected when I do the assignment `param.anotherProperty = true`. This makes me think that there is some understanding of the type thanks to the generic constraint.
In the other two lines (17 and 18) it doesn't compile with the corresponding error:
- Type '{ property: true; }' is not assignable to type 'CopyType<T>'.

### 🙂 Expected behavior

I would expect a consistent behavior:
- If it should be capable of inferring the type, that the code compiles.
- If something is incorrect in that definition, that also line 16 doesn't compile.

### Additional information about the issue

I came out with this example from an unexpected behavior using ts-essential, that has more unexpected behaviors:

```ts
// Setup
type ExampleType = { propertyA: boolean; propertyB: number };
type KeepBooleanProperties<T> = PickProperties<T, boolean>;
let check1: KeepBooleanProperties<ExampleType> = { propertyA: true }; // Compiles, expected.
let check2: KeepBooleanProperties<ExampleType> = { propertyA: true, propertyB: 1 }; // It doesn't compile, expected.

// Test with generic constraints.
function test<T extends ExampleType>(param: KeepBooleanProperties<T>) {
  param.propertyA = true; // It doesn't compile, not expexted.
  param.anotherProperty = true; // It does not compile, expected.
  param = { propertyA: true }; // It does not compile, not expected.
  let check: CopyType<T> = { property: true }; // It does not compile, not expected.
```

**Comment by whzx5byb** [comment]
I don't see failure here, and it's nothing to do with `CopyType<T>`. Just consider:
```ts
function test<T extends ExampleType>(param: T) {
    param = { property: true };
}
```
You can't assign `{property: true}` to `T` here because `T` could be a subtype with more properties.

**Comment by DanielBertocci** [comment]
Thank you @whzx5byb you are right. I think the example I have built in my initial post is not effective. I missed probably the key point that is visible in the section "Additional information". I think the following version is the proper example, where I have unrolled ts-essential:

```ts
// Setup
type ExampleType = { propertyA: boolean; propertyB: number };

type BooleanKeys<T> = {
  [Key in keyof T]: T[Key] extends boolean ? Key : never;
}[keyof T];
let booleanKeysCheck1: BooleanKeys<ExampleType> = 'propertyA'; // Compiles, expected.
let booleanKeysCheck2: BooleanKeys<ExampleType> = 'propertyB'; // It doesn't compile, expected.

type KeepBooleanProperties<T> = Pick<T, BooleanKeys<T>>;
let check1: KeepBooleanProperties<ExampleType> = { propertyA: true }; // Compiles, expected.
let check2: KeepBooleanProperties<ExampleType> = { propertyA: true, propertyB: 1 }; // It doesn't compile, expected.

// Test with generic constraints.
function test<T extends ExampleType>(param: KeepBooleanProperties<T>) {
  param.propertyA = true; // It doesn't compile, not expexted.
  param.propertyB = 1; // It does not compile, expected.
  param = { propertyA: true }; // It does not compile, expected after comment of whzx5byb.
  let check: CopyType<T> = { property: true }; // It does not compile, expected after comment of whzx5byb.
}
```

**Comment by jcalz** [comment]
What if `T` is `{propertyA: false, propertyB: 0}`? Then you're assigning `true` to `false`. Even if you "fix" this you'll just be taking advantage of the hole (https://github.com/microsoft/TypeScript/issues/28952#issuecomment-446417624) that lets you assign properties directly. I don't see anything here that isn't a combination of *existing* missing features, design limitations, intentional tradeoffs.  Your `BooleanKeys` confuses the compiler because of the lack of #48992, assignments to generics with nongeneric values are often problematic, see [Why can't I return a generic 'T' to satisfy a Partial<T>?](https://stackoverflow.com/q/46980763/2887218).

**Comment by DanielBertocci** [comment]
Really insight full. I haven't considered that case and it makes perfectly sense. Let's take a step aside and avoid assignments. 
I see that my case comes from the similar need of #48992. But what about the following (and more compact) example?

[Playground here](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/PTAEGUFMBcFcAcBQ0Ce9KgKIA8CGBbeAG0gBU0MBeUAb1HgCcB7dB1AQQC5QAjJpkrgB2AbnrNWqAELchsfD0gNQAXxHIKodgB5SAPlDUaAbQDSkFKACWQ0AGsLTAGahSAXW7mUK4w5TPXN3VEEmhQAGMAC0hwuwBGbh0cAmIyCgNqAHJGFiUOTPVQiOjYgCZE7WTCEnJ0DNBsiTyUKQLERBBXSABnMIB3K2hI0ABzSCElK3CIpiFehlwbaG6AOkQnWCFw6CtZ0Gge6F1QSGwDoQATbqw8arS6gAp4XAX8Cv0ASlpEUGsXJ5eBBWOUkKHYXzonRw6G2kAu9iETD6thBzVAAyGoE2dkRyP2FDWv1+nQAMkwRlMVlSfqp2r8rP9nq9jI1cmwwZk3BDQFDsDCDvCcUiUU12QAadGDYbY3G2VDoQlE0nkynU34qRAqIA)

```ts
// Setup
type ExampleType = { propertyA: boolean; propertyB: number };
type A<T> = {[Key in keyof T]: Key}[keyof T];

let check1: A<ExampleType> = 'propertyA';
let check2: A<ExampleType> = 'propertyB';

// Test with generic constraints.
function test<T extends ExampleType>(param: A<T>) {
  if (param.propertyA) { // Expected known property with unknown type.
    // Logic...
  }

  if (param['propertyA']) { // Expected known property, with unknown type.
    // Logic...
  }
}
```
I understand that there are many cases about types, so after the example of @jcalz I understand that there are problems deriving types. But It seems to me that the access to that property is not ambiguous, where I could use a type guard function, for example.
I also took the distances from the need of filtering the properties by type.

**Comment by MartinJohns** [comment]
> expected known property

But why? `T` can be any type with arbitrary amount of properties. It doesn't only contain `propertyA`. Having it typed that way would be very misleading.

**Comment by RyanCavanaugh** [comment]
In this example, a legal call is
```ts
test('propertyA');
```
I don't understand why we would be expected to be able to access the property `.propertyA` on a string. It's not there.

**Comment by DanielBertocci** [comment]
Yes I messed up the previous example. I did several attempts, and this is the latest example I have:

[Playground here](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/PTAEGUFMBcFcAcBQ0Ce9KgKIA8CGBbeAG0gBU0MBeUAb1HgCcB7dB1AQQC5QAjJpkrgB2AbnrNWqAELchsfD0gNQAXxHIKoAAoBLAMYBrLRKXQdkAM4AecugA0oAGq4isSAD5Q1XYZsUHNIigoADaANKQKKA6QqAGkUwAZqC2kAC63KnhkWmgkNjQkEIAJhZOLm6gAPygEVGykABuSuoqIfEoSSkUae7qJNCgegAWkIYAjNw+RiZs5tY4BMRk-rz8gkKe1HSMLKYoXKDQDJVqoCCgAMJMhDokFg756HqFxQB0iANDo4YATFP6GZ7OaWKyLQgkVIOPgCSDCLa0cTAjjcY5uBy7SQoGSgcaqMQXACSg2KTEsQgA5IM9Dd4HdII9sM9Xh9EBdSJZBgB3HTQYagADmRSU+iGTCEFmOuBi0AsH0SsCELx04qOnJseQKRVKWDwEJW6HcAAp4LgGAQAYZjMj5jZoes4ZsAJS0ILRRIms0EN6Y-bsJ10c5gYmgUnkqli24kBxCJiDJ5jFlu4IXAAyTAF+jdKkQOeQnKNNF9bAOqJOkBUToJwbKfKUGGEUS5uCi0CYQxcRDVktAPL5TFggzrSKxoAARMWOGOqkA)
```ts
// Setup
type ExampleType = { propertyA: boolean; propertyB: number };
type PickProperties<Type, Value> = Pick<Type, {
  [Key in keyof Type]: Type[Key] extends Value ? Key : never;
}[keyof Type]>;
let check1: PickProperties<ExampleType, boolean> = { propertyA: true }; // Compiles, expected.
let check2: PickProperties<ExampleType, boolean> = { propertyA: true, propertyB: 1 }; // It doesn't compile, expected.

// Test with generic constraints.
function test<T extends ExampleType>(param: PickProperties<T, boolean>) {
  if(param.propertyA){  // It doesn't compile, not expected.
    // Logic
  }
}

test({propertyA: true}); // Is there any way to call test without the property "propertyA"?
```

This though is about the same topic mentioned by @jcalz, because I filter the properties based on a type.
That means I will wait for updates on the issues mentioned. Thanks for the support.
