### ISSUE TITLE
TS2585: 'Symbol' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.

### ISSUE THREAD

**Issue by congjunhua** [microsoft/TypeScript#58005]
### 🔎 Search Terms

TS2585: 'Symbol' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.

### 🕗 Version & Regression Information

```shell
$ npm view typescript version
5.4.3
```

### 💻 Code

```ts
// Your code here
let s = Symbol('1')
```

`tsconfig.json`
```json
{
    "compilerOptions": {
        "target": "ES2023"
    }
}
```

### 🙁 Actual behavior

```shell
$ tsc app.ts
app.ts:1:9 - error TS2585: 'Symbol' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the 'lib' compiler option to es2015 or later.

1 let s = Symbol('1')
          ~~~~~~


Found 1 error in app.ts:1
```
![image](https://github.com/microsoft/TypeScript/assets/95909681/76e74144-f558-4f9c-afc4-37a740851677)

### 🙂 Expected behavior

normal

**Comment by MartinJohns** [comment]
When passing a list of filenames to `tsc` your local tsconfig will not be used, so the target is the default value.
