### ISSUE TITLE
Incorrect type inference from type union with conditional type

### ISSUE THREAD

**Issue by Qsppl** [microsoft/TypeScript#58016]
### 🔎 Search Terms

inference union with conditional type

### 🕗 Version & Regression Information

- This is incorrect type evaluation
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "conditional type"/ "union" / "inference"
- This bug is repeated on all versions that I looked at

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240331#code/C4TwDgpgBACgTgSwLYOAgbhA8nA4hYYCOAHgBUA+KAXgCgooAfKACjKggA8iA7AEwDOUAcEQ8A5kyg8ArkgBGxKfID2KgDYQAhjykz+EAGYIeEPlAD8UdgC5pETHACU9KSxbqtIgGpb1MiDsyJxoqYNpaAHpI4QB3LTAoYAALCAFoYFiVKDAtOGAhFUMk1KTwaH0EFR5aUEgofEJiHHhkVAwIcio6BmZ3Tx8-AKCQ6jCXXtZ2Ll5BYVETSWZZBSVmVQ1tXWZ9PiMTM0trKDtTRxcI6KgAYlu7+4eHqABhL2hqiAiAb1dDfQBjNDVKCGLSAlRwEBdFjoIaBWCIFBoTA4RpEUiUJx2VpIjqogjorpQH4MBhwAgyOC6WH+CAAblcAF8IgwrmRylAAOQiMTiTlQBBCHgqYBQLwCBDiHhaeSaJLZOrQTksUZUHmLTkAOgKLAATABmXW6iYgsHACEgdyqqAAIhtJqu8hkopSxGgAmSKhk6nMimk2WIcAhAEJaMzaCSQQCgbpQeDIdCacMGgTmnAce1MF0sSmmnAWojM51KMTXGSKVSoEn6UyWVArjpzK6OHAg3AoHxBQlIHkBKGGHHzZCraFbfawxEojFHjOZy83kkshFFVAAKLcOBmnCSkwkGDdWAcbgQfhCDPI7B4VOkEyGJTb8QmKhWB8mE72RwMlev3TUNcbrdEEfHgSBVUd1QkCgpygAB1aAuEgQEoAAAwg8RkIFXQfwAGigJ1RVQhYJDcMCxnmXknAw-4VCQNI8LBABrYMgA

### 💻 Code

```ts
type PrimitiveOrGetter<T> =
  | (T extends string | number | boolean | undefined ? T : never)
  | ((lastValue: T) => T)

// swap these two parts of the type union
type GetterOrPrimitive<T> =
  | ((lastValue: T) => T)
  | (T extends string | number | boolean | undefined ? T : never)


// #################### Case one

{
  function factory<T>(value: PrimitiveOrGetter<T>): PrimitiveOrGetter<T> {
    return value;
  }

  // Type 'string' is not assignable to type '() => string'.ts(2322)
  factory(() => "")
  // but there should be no error!
}

{
  function factory<T>(value: GetterOrPrimitive<T>): GetterOrPrimitive<T> {
    return value;
  }

  // and the error disappears!
  factory(() => "")
}


// #################### Case two

type ExtractOrigin<P> = P extends PrimitiveOrGetter<infer Origin> ? Origin : never;
type Origin = ExtractOrigin<() => string>
// We expect `string` in Origin, but `string | (() => string)` comes back!
```

### 🙁 Actual behavior

Typescript shows that there is an error in the example.

The type of `Origin` is `string | (() => string)`.

Union of types `A | B` is not equal to the union of types `B | A`.

### 🙂 Expected behavior

Typescript should not find errors in the example.

The type of `Origin` must be `string`.

Union of types `A | B` must be equal to the union of types `B | A`.

**Comment by Andarist** [comment]
Both of those behave the same way:
```ts
type PrimitiveOrGetter<T> =
  | (T extends string | number | boolean | undefined ? T : never)
  | ((lastValue: T) => T);

type GetterOrPrimitive<T> =
  | ((lastValue: T) => T)
  | (T extends string | number | boolean | undefined ? T : never);

type ExtractOrigin<P> = P extends PrimitiveOrGetter<infer Origin>
  ? Origin
  : never;
type Origin = ExtractOrigin<() => string>;

type ExtractOrigin2<P> = P extends GetterOrPrimitive<infer Origin>
  ? Origin
  : never;
type Origin2 = ExtractOrigin2<() => string>;
```

In fact, your both functions infer the same way too. When you have sufficiently incompatible inference candidates the first one gets picked as the inferred type. So it just happens that when you reorder your union the first candidate is different. This leads to this observable effect. However, it's not that one of those infers differently - like one can be matched better. There is just nothing that would discriminate your union here. Both of those inferences are totally valid in this situation (`string` and `() => string`).

**Comment by Qsppl** [comment]
I would expect that you could put the type into a generic type and then return it somewhere else via inference.
(`A = Array<string>` -> `T = Array<infer T>`)

For [example](https://www.typescriptlang.org/play?ts=5.5.0-dev.20240331#code/PTAEElQUwDwBygYwC6mQCwIaoJ4HsBXURTAO1DgNUzRwVAEtyaBzKUqAJwcQCgRQAIVABeUADEAPAEEAfL35gyAEzTp2oNqgaoARpkQBrUAGc8AWygB3dZyjQANiaiLQ0gIyi3oPADMhMvICsAgoAFxunlAAjgSYDmh4bgoCgp5iUh5BYCFIyBFp0LHxiUIpYNIATF7SPv5pga654W7VMXEJyEkePpzJvMh09pmyorygoAA+oAAUtbDI7MompsjcpCxToKQE5rpcW7p4eA5QZFsEpMpQvkxQqgD83hEcAG5cAJTjWzMzDpgmZAANXiBCgEWkH1Eo0hAyGEFIvi4kkEozEwgWSxWUiYSL6clAT1qLyg704AG4FABvb4CRDqIxhb6Dei1MSA9YsZnw4QZRrc1npBF4lGjAQ4KBwAX2Qp8rKgcWShQTFn2KpecCI5FpMVgCVSiYCHSgKx4TiGEwAQl4AF9qdLvOy1kwuSqeV4RrSwExAWdVH5aPQAESCIMm+zITCGew0V6g+wB1WgENB76IPCkQGgOMOMFeGZQkSjIOph09MSakWqgM5sG67Z4BAO2USGTueukRsuMvVCtazgo9sKsCdpuGsDKPBQFad1Cm80zW1AA):
```TS
// I expect that you can put a type in a generic
// B = F<A>

// and then get it back somewhere else
// A1 = A of B<A>
// expect: A1 equal to A

// B1 = F<A1>
// expect: B1 equal to B

// A2 = A of B1<A>
// expect: A2 equal to A1 or A

type F<A> =
  | (A extends string | number | boolean | undefined ? A : never)
  | ((lastValue: A) => A)
type Infer<B> = B extends F<infer A> ? A : never;

{
  // check:
  type A = string
  type B = F<A>

  type A1 = Infer<B> // yep
  type B1 = F<A1> // yep

  type A2 = Infer<B1> // yep
  // it works!
}

{
  type A = string
  type B = F<A>
  // instead of type "B" we take a value of type "B"
  const value = () => ""

  type A1 = Infer<typeof value> // nope
  type B1 = F<A1> // nope

  type A2 = Infer<B1> // nope
  // does not work(
}
```

If I just misunderstood how infering is supposed to work, let's close the issue.

**Comment by fatcerberus** [comment]
In general you can only reliably `F<infer A>` when `A` is witnessed somewhere in the type computed by `F<A>`, as inference is structural.  It's basically the same problem as:

1. `8 * 0 = 0`
2. `x * 0 = 0`, now solve for `x`

**Comment by Qsppl** [comment]
1. `8 * 2 = 16`
2. `x * 2 = 16`
3. therefore `x` is `8`, but we observe `8` or `16`

this thesis, despite its rhetorical beauty, is not absolutely true. Typescript is not Euclidean algebra, but something like set theory.

If we think of `() => string` as `F<A>`, then `A` can only be a `string`, but it can never be `() => string`.

![image](https://github.com/microsoft/TypeScript/assets/22717464/58100e7b-2807-4fdd-b4ed-685279852db3)

**Comment by fatcerberus** [comment]
> this thesis, despite its rhetorical beauty, is not absolutely true. Typescript is not Euclidean algebra, but something like set theory.

In this *specific* case (`infer A`), it is - inference is done structurally by examining the type given and "working backwards" to figure out `A`.  It's very much a "solve for `x`" style operation.

> If we think of `() => string` as `F<A>`, then `A` can only be a `string`, but it can never be `() => string`.

Yeah, I get what you're saying there and your reasoning is sound - but AFAIK conditional types are basically opaque to inference, TS doesn't have the smarts to do that kind of backwards reasoning on them--and they're Turing complete, so you run into issues like the halting problem, etc.  It's a design limitation, but one that's unlikely to go away any time soon.
