### ISSUE TITLE
Incorrect Type Deduction in Recursive Conditional Generics Types

### ISSUE THREAD

**Issue by Yangff** [microsoft/TypeScript#58012]
### 🔎 Search Terms

generics, type deduction, nested generics, conditional type, type inferring 

### 🕗 Version & Regression Information

```
type Comparable<T> = T extends ComparableBase ? true : ( T extends Option<infer U> ? Comparable<U> : false);
```
is supported only after v4.1.5 and the function breaks for every version since that.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240330#code/FAFwngDgpgBA8hEBLA9gOwDwBUB8MC8MAyigLZTZ4A+MAculANzBJohQBOAZgIYDGsEuUowA3sBiSYAfRA8A5gC4YAIgDOZKCoA0EqQDceAGwCuUZVmABfYCzadeAugzF7JshcpVoGK67fBoGABhMggeDh4AIyMoACEeNVhCNBNSKM4YGiiUFFieNCyYVKMjIpM0ABMoLlYoSqK1MHS8oqikeVYQZlBIWFDScMiYilwCGCwYKAAPdiq1ELCI6NiEpJgAfhgQDjMYZQAKCanZqHn4RFRMVi5MgFU8LYGhlYoH-ZheIySASh7A2AAQXGz2WIwwqXSnBwvSCcRBS2GsQwCGQ6AhaQyHBwMIBIQRgzByNRVxRl3RkKxONxfRgABECS9wWodqx5DSggBRRlEigk9EsjhsnGw2AAMR5SL55Mw-MwguFIuAAHpldtaQAlKD6ThJOn1Ex8NGYMaEUFSkQzOaVBZfdZbNDazLKApgRgwVUwADuKA4AGs1KKYFqdRw9QajaTTYtCRaxlazjbtrtYFtXR9HaH3Z6fCBvb6A7Y+EZEgssABZEws82vbAna0LEO6qD6yqG42UPDiKQwQymcwTZg9vjoQXt30HaYWH6uHs9kAACyQagAdH29oRpkOpDYbCq1bE8zxxo6vRNK9XEbWFWh2QcVDxHyo-h61fg8GoFygTEYGpwOL6wCHjAUQnlAZ4VlWIA1uClLQgcACMABMADMfxAVAeZ8GBEEXtBV7gnKGJQtiOAHKIHhKKoGjkDovbGGYijIShVgvp6n7fr+xQoHm-6AcBDQpOB55QTBxIymSHZwaRZGiDIchUeomh0euA4UQpXg0Vo2j0f2yjMVYrHZmqHE-g0uZTBwAEcPuMDAckxTCZBl6xrWRE3uysmUZpyk6apigPk+RmvgQH5fmZlnWcAQA

### 💻 Code

```ts
type Option<T> = Some<T> | None;
interface Some<T> {
    _tag: "some",
    value: T
}

interface None {
    _tag: "none"
}

type ComparableBase = number | boolean | null | undefined | symbol | bigint;

type Comparable<T> = T extends ComparableBase ? true : ( T extends Option<infer U> ? Comparable<U> : false);

type A = Comparable<number>
type B = Comparable<Option<number>>
type C = Comparable<Option<Option<number>>>
type D = Comparable<string>
type E = Comparable<Option<string>>
type F = Comparable<Option<Option<string>>>

// type ReverseDeduction<T> = Comparable<T> extends false ? never : any; // works
type ReverseDeduction<T> = Comparable<T> extends true ? any : never; // not works

class TMustComparable<T extends ReverseDeduction<T>> {
    value: T;
    constructor(x: T) {
        this.value = x;
    }
}

// let a = new TMustComparable<string>("aaa"); // => should error
let b = new TMustComparable<number>(123);
let c = new TMustComparable<Option<number>>({_tag: "some", value:123}); // should not error
let d = new TMustComparable<Option<Option<number>>>({ _tag: "some", value: {_tag: "some", value: 123}}); // should not error
// let e = new TMustComparable<Option<string>>({_tag: "some", value:"aaa"}); // => should error

```

### 🙁 Actual behavior

The following errors are given
```
Type 'Option<number>' does not satisfy the constraint 'never'.
  Type 'None' is not assignable to type 'never'.
Type 'Option<Option<number>>' does not satisfy the constraint 'never'.
  Type 'None' is not assignable to type 'never'.
```
it's because the type of `Comparable<Option<number>>` is calcuated as `boolean`  (result of `true | false` I think, looks like something here about `?:` is being treated as OR ) instead of `true`, similar happens to `Comparable<Option<Option<number>>>`

### 🙂 Expected behavior

The code should compile. Actually if you replace line 24 with line 23, it works. but in the end I think the type system should be able to accurately deduct the type to either true or false, instead of true, false and boolean in this case.
Although both cases will go through `T extends Option<infer U> ? Comparable<U>`, the false case -- `Comparable<Option<string>>` will have no problem being recognized as `false` in both cases.

**Comment by ZakuroSoda** [comment]
Nice

**Comment by guillaumebrunerie** [comment]
A type of the form `T extends ...` distributes on unions, so it doesn't do what you expect when applying it to `Option` (which is a union).

You can change the `Comparable` type to the following and it works:
```ts
type Comparable<T> = [T] extends [ComparableBase] ? true : ( [T] extends [Option<infer U>] ? Comparable<U> : false);
```

Note the brackets, which prevent the type from being distributive.

**Comment by Yangff** [comment]
> A type of the form `T extends ...` distributes on unions, so it doesn't do what you expect when applying it to `Option` (which is a union).
> 
> You can change the `Comparable` type to the following and it works:
> 
> ```ts
> type Comparable<T> = [T] extends [ComparableBase] ? true : ( [T] extends [Option<infer U>] ? Comparable<U> : false);
> ```
> 
> Note the brackets, which prevent the type from being distributive.

Thanks, that solve the problem!

**Comment by Yangff** [comment]
> A type of the form `T extends ...` distributes on unions, so it doesn't do what you expect when applying it to `Option` (which is a union).
> 
> You can change the `Comparable` type to the following and it works:
> 
> ```ts
> type Comparable<T> = [T] extends [ComparableBase] ? true : ( [T] extends [Option<infer U>] ? Comparable<U> : false);
> ```
> 
> Note the brackets, which prevent the type from being distributive.

Nonetheless, I'm still a weirded by the fact that here I'm trying to infer type U from the `Option<U>`. 
Even though `Option` is distributive, it shouldn't affect U to have only the unique type `number`, right? (Even number | number shouldn't generate any false?)

And, if I manually apply the `Option<number>` to where the T is, it also gives me the correcet result.

```
type X = Option<number> extends ComparableBase ? true : ( Option<number> extends Option<infer U> ? Comparable<U> : false) // => true
```
