### ISSUE TITLE
New Website Logo: Ericsson 

### ISSUE THREAD

**Issue by mattkaiser** [Microsoft/TypeScript#5801]
Please fill the following out:

- Name: Ericsson 
- Homepage url: http://www.ericsson.com 
- Brand Guidelines/Licensing: http://www.ericsson.com/article/logotype_914590152_c 
http://www.ericsson.com/thecompany/press
- Logo:
![ericsson](https://cloud.githubusercontent.com/assets/11627354/11419844/170d70b2-9465-11e5-9814-bba7462f7519.JPG)

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by BarryVickers** [comment]
Hi there,

If there is anyway of making this happen here a little quicker, we'd be delighted. We are a big supporter of TypeScript and are the host of the Ireland Typescript Meetup group (http://www.meetup.com/Dublin-TypeScript-Meetup/events/226080932/)

**Comment by RyanCavanaugh** [comment]
@BarryVickers thanks for your support! We do these the website logo updates in batches so the delay can be a bit long depending on where we are in the cycle. @mhegazy any idea when the next update is?

**Comment by mattkaiser** [comment]
Hi Barry,

Let me know if you need me to do anything

**Comment by BarryVickers** [comment]
I see this is live now – thank you all!
