### ISSUE TITLE
Allow `ts-expect-error` to specify the expected error code(s)

### ISSUE THREAD

**Issue by RamonBalthazar** [microsoft/TypeScript#58021]
### 🔍 Search Terms

"ts-expect-error"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow the `@ts-expect-error` annotation to be narrowed to one or multiple error codes.

Example:
```typescript
function getFirst(chars: string[]): string {
  // @ts-expect-error(2532)
  return chars[0].tolowercase()
}
```
For the above code, TS would:
* Show an error for the misspelled `toLowerCase` (TS2551)
* Ignore `chars[0]` being possibly undefined (TS2532)

You could specify one or multiple error codes in the brackets, comma separated.

### 📃 Motivating Example

When bringing code from other codebases with less strict rules, you sometimes would want to fix the typing issues over time. You could mark all of the failing lines with `@ts-expect-error`, to be fixed in subsequent code changes, but what if in the meantime someone makes an unrelated type mistake in one of those lines and it causes a run-time error?

Having the ability to specify what error you're expecting in those lines adds a layer of safety for a code you didn't really want to make unsafe.

### 💻 Use Cases

**1. What do you want to use this for?**
To be more granular about what errors to expect.

**2. What shortcomings exist with current approaches?**
They allow for any error to exist in a given line.

**3. What workarounds are you using in the meantime?**
None

**Comment by MartinJohns** [comment]
Duplicate of #45937. Used search terms: `ts-expect-error in:title`

**Comment by RamonBalthazar** [comment]
Ah shoot, I missed that one 🤔
Thanks
