### ISSUE TITLE
Improve new issue template selection - reorder and handle "this is crash" check better

### ISSUE THREAD

**Issue by rubiesonthesky** [microsoft/TypeScript#58052]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I propose that templates would be reordered so that "Types not correct in/with callback" would be first one. It may first feel unnecessary to have it as first but I think it would get people to use it more when it's applicable. -> Meaning those could be handled quickly differently

About "Bug report", I think it would be good to separate compiler / language server crash to different template than the other problems. Or alternatively, improve "This is crash" text to make it clear that what it means. Now so many type error issues are flagged as "this is crash" because people do not understand what it means.  :)

**Comment by RyanCavanaugh** [comment]
I'm pretty happy with the templates as-is

**Comment by fatcerberus** [comment]
> Types not correct in/with callback
> get people to use it more when it's applicable

The whole point of that template is that it's *never* applicable - it only exists to tell you that the behavior it describes (which people tend to assume is a bug) is by design/design limitation and you shouldn't post the issue at all because it will just be duped to #9998.
