### ISSUE TITLE
"declare class" in a global is not visible in external files

### ISSUE THREAD

**Issue by jayshah123** [microsoft/TypeScript#58056]
### 🔎 Search Terms

"declare class" in a global is not visible in external files,
extending typescript global object with "declare class",
declared class in global not found,
typescript globals.d.ts declared global class not found

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about globals and declaration files [here](https://github.com/Microsoft/TypeScript/wiki/FAQ#common-bugs-that-arent-bugs) 

### ⏯ Playground Link

https://github.com/jayshah123/typescript-declare-global-class-issue

### 💻 Code

```ts
// global.d.ts
export { };

declare global {
    var myGlobalVariable: string;
    class WorldClass {
        constructor();
        important: number;
    }
}
```

```ts
// index.ts
const w = new global.WorldClass(); // Property 'WorldClass' does not exist on type 'typeof globalThis'.ts(2339)
\
const h = global.myGlobalVariable;

console.log(h);
```

### 🙁 Actual behavior

Class declared in global not allowed
<img width="1365" alt="Screenshot 2024-04-03 at 6 47 07 PM" src="https://github.com/microsoft/TypeScript/assets/659202/eae1eaf2-bd3e-4aed-9836-d314c7ca3628">

### 🙂 Expected behavior

Class declared in global should be allowed.

**Comment by MartinJohns** [comment]
Your "Playground" link does not work and leads to a 404.

**Comment by jayshah123** [comment]
> Your "Playground" link does not work and leads to a 404.

It's a github link: https://github.com/jayshah123/typescript-declare-global-class-issue

**Comment by whzx5byb** [comment]
See https://github.com/microsoft/TypeScript/issues/39504#issuecomment-655662448

> That’s because `class`, `let` and `const` don’t create own properties on the global object, instead they create variable bindings on a [Declarative Environment Record](https://tc39.es/ecma262/#sec-declarative-environment-records), so this is the expected behaviour.

If you still want to do this, try this workaround.
```ts
declare global {
    namespace globalThis {
        class WorldClass {
            constructor();
            important: number;
        }
        export { WorldClass }
    }
}

const w = new global.WorldClass(); // OK
```

**Comment by jayshah123** [comment]
> And I'm telling you that your link doesn't work, it leads to a 404 page. Perhaps you have set it to private.

My bad, made it public

**Comment by jayshah123** [comment]
Is this a common pattern for globals declaration - `declare interface` + `declare var`,
```ts
/**
 * The URL interface represents an object providing static methods used for creating object URLs.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/URL)
 */
interface URL {
    hash: string;
    host: string;
    hostname: string;
    href: string;
    toString(): string;
    readonly origin: string;
    password: string;
    pathname: string;
    port: string;
    protocol: string;
    search: string;
    readonly searchParams: URLSearchParams;
    username: string;
    toJSON(): string;
}

declare var URL: {
    prototype: URL;
    new(url: string | URL, base?: string | URL): URL;
    canParse(url: string | URL, base?: string): boolean;
    createObjectURL(obj: Blob | MediaSource): string;
    revokeObjectURL(url: string): void;
};
```

 if the behavior mentioned in the issue description is an expcted one, 
 should we add this to FAQ?

**Comment by fatcerberus** [comment]
The behavior mentioned matches JS runtime behavior:

```ts
<script>
class Foo {}
console.log(Foo);  // [class Foo]
console.log(globalThis.Foo);  // undefined
</script>
```

I don't think it needs to be documented separately if the types match the runtime reality.
