### ISSUE TITLE
Spread operator doesn't remove readonly from object properties

### ISSUE THREAD

**Issue by Perfectoff** [microsoft/TypeScript#58071]
### 🔎 Search Terms

spread remove readonly

### 🕗 Version & Regression Information

- This appeared sometime after #15036

### 💻 Code

```ts
    interface ReadOnlyData {
       readonly value: string;
    }
    let data: ReadOnlyData = { value:'foo' }
    
    let copyOfData = {...data};
    
    copyOfData.value = 'bar';   // Error: Attempt to assign to const or readonly variable
```

### 🙁 Actual behavior

error:  Attempt to assign to const or readonly variable

### 🙂 Expected behavior

the copy should be writeable

### Additional information about the issue

This bug was fixed many years ago ( #15036), but it exists again in current versions of the language.

**Comment by RyanCavanaugh** [comment]
I'm not seeing the error either

**Comment by Perfectoff** [comment]
ok, sorry, it was just a problem with some syntax plugin in my IDE
