### ISSUE TITLE
Is there a way to get an ambient module from typescript.d.ts of 1.6?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5807]
Before version 1.6 `typescript.d.ts` used to be an ambient module declaration file. Now it is so called typing file. Where a typing is a sort of hybrid between an external module and ambient declaration. It [might turn out](https://github.com/Microsoft/TypeScript/issues/5805) that typings aren't always a desirable way to go. 

The current `typescript.d.ts` can be transformed into an ambient declaration just by replacing the last line:
```
export=ts;
```
with
```
declare module 'typescript' {
   export = ts;
}
```
But that means I have to take the ownership of it and lose the automatic updates.

So my question: is there a way to get an ambient module from a typing file without having to modify it by hands?

**Comment by blakeembrey** [comment]
You shouldn't be using ambient module declarations. You can use a tool like `typings` to do this though, but if you're using node module resolution it shouldn't be needed.

For example: https://github.com/TypeStrong/ts-node/blob/master/typings.json#L11

**Comment by aleksey-bykov** [comment]
it doesn't work with nested typings

**Comment by blakeembrey** [comment]
@aleksey-bykov Can you elaborate?

**Comment by aleksey-bykov** [comment]
see the link in the original issue description

**Comment by blakeembrey** [comment]
But that issue isn't related right? I understand it's a problem you're having, but I can't comment on that right now. I answered your question in this issue. Did my answer not work for you?

**Comment by aleksey-bykov** [comment]
that issue is what brought up this question in the first place, I
appreciate you opinion, but I would like to get an answer from the design
team

**Comment by mhegazy** [comment]
Ambient declarations pollute the global namespace, proper modules do not, so if you are asking for recommendation i would say do not use ambient module declarations unless you have to.

For typescript, we still have the other file, this is what we upload to definitelytyped. the file is generated by `jake local` under typescript_standalone.d.ts, if that helps.
