### ISSUE TITLE
Inconsistent behaviour of es6 and esnext property initializers when using experimental property decorators

### ISSUE THREAD

**Issue by jameskeane** [microsoft/TypeScript#58070]
### 🔎 Search Terms

decorator esnext initializer

### 🕗 Version & Regression Information

- This changed between versions es6 and esnext

### 💻 Code

```ts
function provide<T extends object, K extends keyof T>(target: T, propertyKey: K) {
  Object.defineProperty(target, propertyKey, {
    get: () => console.log('get called'),
    set: () =>  console.log('set called')
  });
}

class Example {
  @provide
  state = {
    abc: 123,
    things: [4, 5, 6]
  }
}

const j = new Example();
```

### 🙁 Actual behavior

With `target: esnext`, console does not print 'set called'.

### 🙂 Expected behavior

Console should print 'set called' as it does when `target: es6`

### Additional information about the issue

I think this is related to `target: esnext` using native javascript class property initializers instead of embedding the initializer at the end of the constructor. The issue is consistent across Chrome & Firefox.

This is a very common property decorator pattern.

**Comment by MartinJohns** [comment]
This is working as intended. The default value for [useDefineForClassFields](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) changes with your `target`, resulting in different behavior.

**Comment by fatcerberus** [comment]
> I think this is related to `target: esnext` using native javascript class property initializers instead of embedding the initializer at the end of the constructor

NB: key word is *native*.  Once decorators are also natively supported in JS and TS is capable of outputting them without downleveling, this will be the runtime behavior for this code, so this pattern is already inherently fragile.  TS current design philosophy is to match JS runtime behavior as closely as possible.
