### ISSUE TITLE
`noUncheckedIndexedAccess` does not narrow properly when iterating with `for...in`

### ISSUE THREAD

**Issue by NoahAndrews** [microsoft/TypeScript#58082]
### 🔍 Search Terms

"noUncheckedIndexedAccess"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When iterating through a `Record` type with a `for...in` loop, detect that the record's key is guaranteed to be present when doing lookups on the object. If the `Record` does not have `null` or `undefined` keys, this will allow code to not have to handle the possibility of an `undefined` value when `noUncheckedIndexedAccess` is enabled.

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true#code/MYewdgzgLgBCBGArAXDASgU1AJwCYB5psBLMAcwBoYwBXAW3g2wD4YBeGAbwCgY+YARADNiGADa4AjANSSKvfsNESATDJgr5AX27chIbDAAUoSLBHjcAOQCGdDDFJwkASi4K+Aek8wAQlhsaCAcLCVt7GAB3GwgYYGwMGygMXBh4AE8YGxh9bAA6AqcxEBAABxgoAAskx2TsJIxYquwQGjJKisqHTBxUhEQsKHl+GG8c5Ws7B2JYshoberBklIqQNIdShOCluDBOh37B4xiYYvIspq6ErOuwNZj0sGAYCC6wGzBiMg+IF2H+MYQNb9ADaoUm9gAui9Kq0JDBqgA3BzZKDpUoHITUeiMbBUO6wWgMJgwAA+MBoYFwGBEYBSeQ8cXA0HGlgAajYxDQMKgibj2M5EGCJuEMJCANzcLRAA)

### 📃 Motivating Example

Iterating through a Record with non-null/undefined values with `noUncheckedIndexedAccess` enabled will no longer force handling of `undefined`

### 💻 Use Cases

Without this change, I have to either leave `noUncheckedIndexAccess` disabled, or add unnecessary boilerplate whenever I'm iterating through a `Record`.

**Comment by NoahAndrews** [comment]
A similar case to this was reported as https://github.com/microsoft/TypeScript/issues/43614, and resolved in https://github.com/microsoft/TypeScript/pull/51653.

**Comment by jcalz** [comment]
Could you edit to talk about [index signatures](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) instead of `Record`s? A `Record<K, V>` isn't required to have an index signature (e.g., `Record<"a", string>`).

**Comment by RyanCavanaugh** [comment]
You could still write
```ts
const arr = [1, 2, 3, 4, 5];
for (const idx in arr) {
    arr.length = 0; // n.b. might be an indirect side effect of other code!
    const m = arr[idx];
}
```
Which would give you a wrong type at `m`

We don't intend to make `noUncheckedIndexedAccess` any smarter than it already is - nearly any attempt to make it smarter induces soundness holes in one case or another, and the point of the flag was to not have any indexing holes.

**Comment by NoahAndrews** [comment]
Gotcha, that's fair. Thanks for responding!
