### ISSUE TITLE
Omit private symbols from type

### ISSUE THREAD

**Issue by dhmk083** [microsoft/TypeScript#58089]
### 🔍 Search Terms

private symbols
return type of exported function has or is using private name

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Omit symbol property from auto-inferred type, if this symbol is defined locally inside a function. This would allow to mimic private properties for plain objects.

### 📃 Motivating Example

See below

### 💻 Use Cases

1. What do you want to use this for?

```ts
// Error: Return type of exported function has or is using private name '_'.
export function createSomething() {
    const _ = Symbol()

    function createItem() {
        return {
            name: 'item',
            [_]: {
                implementationDetails: ''
            }
        }
    }

    return {
        items: Array<ReturnType<typeof createItem>>(),

        someMethod() {
            this.items[0][_].implementationDetails
        },
    } 
}

// {
//     name: string;
//     [_]: {          <---- this should be omitted
//         implementationDetails: string;
//     };
// }
type Item = ReturnType<typeof createSomething>['items'][0]

function handleItem(x: Item) {}

handleItem({name: 'test'}) // Error: Property '[_]' is missing in type '{ name: string; }' but required in type
```

2. What shortcomings exist with current approaches?

You need to explicitly set return type of the function.

**Comment by jcalz** [comment]
It mimics private properties the way it is now, by preventing you from assigning external stuff to it. If you do `class Foo {private a = 0}` then you cannot write `const x: Foo = {}`, on purpose. Private properties aren't *completely invisible*, they're just inaccessible.  It seems to me that anyone using code of the form used in your example might well want it to behave just as it does now (except for maybe the declaration error) and keep track of the inaccessible property.  What, specifically, is wrong with having to annotate the type to be what you want?

**Comment by dhmk083** [comment]
Sorry, but I don't understand why would anyone want to keep track of the inaccessible property? Also, type annotations are fine, I just like to keep things concise. With explicit annotations you have to write an interface first and then repeat it in implementation. Otherwise, you can just write an implementation and use inferred type as a contract. Seems better to me, but maybe I am wrong.

I see this suggestion as syntactic sugar, kinda like this `... constructor(private name: string) { } ...` or other shortcuts.

**Comment by jcalz** [comment]
The following code is using [JS private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties) and demonstrates exactly why inaccessible but visible is important. This is how JS works, it's how TS's `private` works, and it's how things currently work with symbols.

```ts
class Foo {
  name;
  #val;
  constructor(name: string, val: string) {
    this.name = name;
    this.#val = val;
  }
  compareOther(other: Foo) {
    return this.#val.toUpperCase() === other.#val.toUpperCase();
  }
}

const foo1 = new Foo("foo1", "foo");
const foo2 = new Foo("foo2", "Foo");
foo1.compareOther(foo2);

const notAFoo = { name: "notAFoo", compareOther(other: Foo) { return false } };
foo1.compareOther(notAFoo); // error
```

**Comment by RyanCavanaugh** [comment]
The proposed behavior seems really buggy if you don't expect it, especially if you consider the case of type operations occurring *within* the context of `createSomething` where you might be tracking necessary internal state.

**Comment by dhmk083** [comment]
Yeah, turned out it wasn't well thought.

**Comment by trusktr** [comment]
Can we make this not an error when `noUncheckedIndexAccess` is enabled?

Then it would be valid because people would need to check for `undefined`. Maybe then `someSymbol in someObject` checks can be used to eliminate the `undefined`.
