### ISSUE TITLE
Incorrect type inference for reduce method accumulator when value is number

### ISSUE THREAD

**Issue by mznx** [microsoft/TypeScript#58092]
### 🔎 Search Terms

incorrect type inference for reduce

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAggLhgJQKagE4BMA80MCWYA5gDQxgCuAtgEaoYwA+FlANmwHwwC8MA3gF8A3AChQkWBBoBGXjADytAFbooAOgBuAQzaVUEABRwAlOoyoslYKkOHp1E724OYAahgzyABhNjRAPQBFCAwDBggGBAwAO4EUAAWMPhExDBE6WDxBLoAarr64uDQyTQATPJKqsAaOnoGxmYWVjZ2Dk48LjTunuQA5H1+okA

### 💻 Code

```ts
const A: Record<string, number | null> = {};
const sum1 = Object.values(A).reduce((sum) => sum + 1, 0);
//                                             ^ error: 'sum' is possibly 'null'

// no errors with string in initialValue
const sum2 = Object.values(A).reduce((sum) => sum + 1, '');

```

### 🙁 Actual behavior

TypeScript incorrectly infers the type of the accumulator in the `reduce` method as `number | null` even when the initial value is number.

### 🙂 Expected behavior

TypeScript should infer the type of the accumulator the `reduce` method as `number` when the initial value is a number.

### Additional information about the issue

Explicitly specifying the types resolves the issue, but TypeScript should correctly infer the type without explicit types.

```ts
const A: Record<string, number | null> = {};
const sum1 = Object.values(A).reduce((sum: number) => sum + 1, 0);
//                                         ^^^^^^      ^ no errors
```

**Comment by nmain** [comment]
> Probably the first overload (non-generic) is being selected since your arguments are all valid subtypes of the parameter types.

That's what's going on.  I think the ordering priority of the overloads is justified.  If you call `reduce` with an `initialValue` that is compatible with the element type of the array, isn't it more likely that you want that element type and not a subtype?

One can easily devise examples of reasonable-looking operations that fail if the overloads are switched: [Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8CCUp3QHgBUA+ZAbwChlrkoIATAVyQAoE4AbDgI0QGsYIAFzIWABzoA3YAHtGAZwBqnRhBGEANMgSMcEcMo6r1WnXvABJEPQgAPESEYBbbtC1wcedQG0AugEpkAF5SQn91AG4qGgB6GORCAAtgeWQU5BlJaA4ZOHpkAGY0kGRsXHQtbkYwZCdMhmRGMWK0LE90aOo6JiR8AFViNk4efkERcSlZBUNjZD7TXToDFTUEhfMwKxt7ZEcXN2QPcp8A4NJ54uAwYE4Z1b7wuaiaWgZmCCGuXgQBYVEJCDSORKFYmbSLfRgO5gsxLTbWOwOZyuKDudonQIhNaXa63UEJR6EKIAXwoFDA6DEKAAQh5guRkBSqSIAEQIGQgeRgODgFlaST4vYo5DE5AAHwZTNWLLAdAgfOQHAgMDAIlpqNowAA5olVch1SKyTYEBwPCgBVBDiIynh8OriBQ4glkql2FxkAB3GRQPjyChwAB03XeLBYiAQ-M4mNILDIjMp0tlEHlWiVKpE4a0UG1upEAo4Iv8WjjUtZ7M53N5kaMqwADIWjRATWbkBbkNwRBgbQR7Y74kl0m6C-BgBxUh6rok5DU7GIOMAEFcOOh42JQFrGYkUMGkIcoFrnJCKNwg29WGGEBHW1GzqISwnWUmU4rlXrM5qdXr84Xi6vpeWuR5MAFXzWZ62JfwyRPHcIDtDxBgvK982jO8-0fOUFTTN9LyzHMv04H9JQfZA2Q5QCq2vGsRHAyCgA)

**Comment by mznx** [comment]
d
