### ISSUE TITLE
Compiler outputs files to the wrong directory structure

### ISSUE THREAD

**Issue by enlight** [Microsoft/TypeScript#5809]
I've noticed a couple of issues with the way the compiler resolves the output directory structure. I've created a [minimal project](https://github.com/enlight/typescript-output-dir-structure-issues) that can be used to reproduce these issues, it's setup as an NPM package, so after cloning/extracting run `npm install` to install the latest nightly build of TypeScript (support for filenames in the `--project` compiler option was added very recently).

Issue 1
======
From the package root run
```
node ./node_modules/typescript/bin/tsc --project src/good-tsconfig.json
```
Note that the output directory structure is (as expected):
```
lib/
  first/
    file1.js
  second/
    file2.js
```
Now run
```
node ./node_modules/typescript/bin/tsc --project src/bad-tsconfig.json
```
Note that the output directory structure is missing the subdir `second`:
```
lib2/
  file2.js
```
While the expected output directory structure is:

```
lib2/
  second/
    file2.js
```

Issue 2
======
I'm not sure if this is a bug or just user error, but it can be reproduced starting with TypeScript 1.6.2 (and possibly earlier, that's just the oldest version I've tried). Run
```
node ./node_modules/typescript/bin/tsc --project src/second
```
Note that the output directory structure is:
```
lib3/
  second/
    first/
      file1.js
    second/
      file2.js
```
While the expected output directory structure is:
```
lib3/
  first/
    file1.js
  second/
    file2.js
```

**Comment by falsandtru** [comment]
`--rootDir` option will solve your issue. See: https://github.com/Microsoft/TypeScript/wiki/Compiler-Options

**Comment by enlight** [comment]
Thanks for the tip @falsandtru. Setting `rootDir` to `.` in bad-tsconfig.json does indeed solve the first issue, though it seems to me like that ought to be the default value of `rootDir` anyway.

Unfortunately I can't seem to fix the second issue by setting `rootDir`, I've tried modifying `src/second/tsconfig.json` like so:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": true,
        "sourceMap": false,
        "declaration": false,
        "noLib": false,
        "outDir": "../../lib3",
        "rootDir": ".."
    },
    "files": [
        "first/file1.ts",
        "second/file2.ts"
    ]
}
```
but the compiler then fails to find the source files:
```
error TS6053: File 'src/second/first/file1.ts' not found.
error TS6053: File 'src/second/second/file2.ts' not found.
```

**Comment by falsandtru** [comment]
Correct code:

```ts
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": true,
        "sourceMap": false,
        "declaration": false,
        "noLib": false,
        "outDir": "../../lib3",
        "rootDir": ".."
    },
    "files": [
        "../first/file1.ts",
        "../second/file2.ts"
    ]
}
```

**Comment by enlight** [comment]
That does indeed work, thanks @falsandtru.

**Comment by falsandtru** [comment]
Not at all. Let's complete a issue with closing of it.

**Comment by enlight** [comment]
For future reference, the explanation of the `rootDir` option in https://github.com/Microsoft/TypeScript/pull/2772 is vastly better than the two short sentences written about it in https://github.com/Microsoft/TypeScript/wiki/Compiler-Options
