### ISSUE TITLE
Is there a good way to accurately identify the cause of an error in a union type?

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#58109]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

![image](https://github.com/microsoft/TypeScript/assets/21278900/3571f685-0d4c-4b1c-8957-45e7e9bda3ec)
Here the type of form is:
```
/**
 * @type {Ref<{
 *  type: 'create'
 *  value: CreateForm
 * } | {
 *  type: 'edit'
 *  value: EditForm
 * }>}
 */
const form = ref({
  /** @type {'create' | 'edit'} */
  type: 'create',
  value: {},
})
```
The type `CreateForm` and `EditForm` are complicated, from the screen-shot, it says that the value type of form is not compatible, it took me a few minutes to figure out the reason, but still can not found it.

**Comment by Mng12345** [comment]
> There usually is more error elaboration than that. Without a full code example, it’s impossible to say why it’s not diving into `EditForm` and `CreateForm`.
This is the minmum reproducing example.
```
type CreateApi = {
    alarmType: number
    alarmLevel: number
    alarmPerson: { personName: string, concatInfo: string, deleted: boolean }[]
    alarmTarget: ({
        deleted: boolean
        managementDep: number
        associatedProjectId: number
    } | {
        deleted: boolean
        managementDep: number
        dataSetId: number
    })[]
}

type EditApi = {
    id: number
    alarmType: number
    alarmLevel: number
    alarmPerson: { personName: string, concatInfo: string, deleted: boolean, id?: number }[]
    alarmTarget: ({
        deleted: boolean
        managementDep: number
        associatedProjectId: number
        id?: number
    } | {
        deleted: boolean
        managementDep: number
        tableName: string
        id?: number
    })[]
}

type Detail = {
    id: number
    alarmTarget: {id: number, managementDep: number, dataSetId?: number, associatedProjectId?: number, deleted: boolean}[]
    alarmPerson: {id: number, personName: string, concatInfo: string, deleted: boolean}[]
    alarmType: number
    alarmLevel: number
    createTime: number
}

type AlarmPersonItem = Detail['alarmPerson'][0]
type AlarmTargetItem = Detail['alarmTarget'][0]
type AlarmPersonRecord = Pick<AlarmPersonItem, 'deleted'> & Partial<Omit<AlarmPersonItem, 'deleted'>> & {_id: string, _active: boolean}
type AlarmTargetRecord = Pick<AlarmTargetItem, 'deleted'> & Partial<Omit<AlarmTargetItem, 'deleted'>> & {_id: string, _active: boolean}

type CreateForm = Partial<Omit<CreateApi, 'alarmTarget' | 'alarmPerson'> & {alarmTarget?: AlarmTargetRecord[], alarmPerson: AlarmPersonRecord[]}>
type EditForm = Partial<Omit<EditApi, 'alarmTarget' | 'alarmPerson'> & {alarmTarget?: AlarmTargetRecord[], alarmPerson?: AlarmPersonRecord[]}>

const init = async () => {
    const getDetail = (): Promise<Detail> => {
        throw new Error('unimplemented')
    }
    const detail = await getDetail()
    const createForm: CreateForm = {
        ...detail,
    }
}
```
playground [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgThAhsCBBMBLKBeKBvAKCmKkQBtE4BbAFXAgC4oA7AVyoCMI4iTzKqAGQgA3CGSZtO3XsX7UACtwDOAe2ZM8USHDXMAcoiqMoy4HAzMA5gBooAY3X3kASWYAzVUzMXrdgCbiECj+TByqqmRIzFAAvgDaALqypBTUNJRWwUwAFIQkBVCBUSFhEVGIzCkFVJWIWcbMwAAiEGCS7Fw8hXzKavYYyBD+CnCqAFYQ9sAuoSydMgWxUAA++NUkxcHDZZHRG8S1zPUQjS1tHdLdPUXIiADKwbOXXSmxAJRJBLEEBKCQUAAov4MMB0FhcPkSBg5lJXgV5LR6C9Fnw0kJROIUdc5OilLp1JptCp1IZjN5zJZbA4nK4PF5TJS-EUgqUoOE9pU7DCAPzYuJfBHojJwLLAXJQnpbNkcipVG5QI4nM6tdrzK4HUh9VQDIYjMaTabPdXwm687FvVbrBXSnbs8r7BVKhoQJqqi0K4CIDhRMkmHxUzXmk2o4gfL4-P70KCtL0YMg4a3Q2ELHGpAQisWaGHYuzO06u85quHcAJ3R4zfx8kNwOyIbW6kKjCZTSvVku1lklO2y6IJZJCgT4vTZlNXOw6PR+im+amOZjOGb0mdUgKsnsOyr9lKIuiQD1ogTCMQSGspewIIY0DDks+R-7QVB4knMFwoKiJ2OIePxADkiOHdRf0SeIAAZkgfKAnwzTInnfT9gm-Mg-13WDgGAsCIOjaDFBfAAlKZVDgfxEwUDB7AAawAHhwqhANfd87F-W1-F-AA+KAADIoAUShgEGMgqIAeSoUEaOfAkGNOJiWPYjjuLwAB9HNGVnOxFMQaYMDEXY5R+SDaMzYICMcYjSPI6jDLQt9pKgZj11Y+SeL4gThNE4BxJg0U4Ns+zu0cpylJUgNmQ0rSdPtTlmHvaN4CQFAADEiI-XBeLgfjyDcsS4qGcEmNQ7z0Ktf8JL0diuPwAqxWrKzCpMoj-CSOtSsJKCWuYeriKSWI2KjAFgVBJLqFIlzMpEsSBrBTB8uFNDf2KgCX3KhSquCGrZrqwiusSZqhxfda9skzrGsSHrfnnMwoEsUFE3rEAFygHJ3hwDjJRpZhLrFL940TJ6mGbUTlAgKjvrIDjsFezVgAACzGAB3FgIARwE4DGOAcl-VhmBvMAojOYZf3eN5z3US7AjjBNcEQOHv2AKAvsQ+MnpJj66YveKICGqgmByxLksTN6CgAOhF8mkJsYnYiAA)

I know that the reason which causes type incompatible is because of the alarmTarget and alarmPerson are different between CreateForm and Detail, but it still need to take a few minutes to find out what the differences are, what i want to know is that are there some good ways or tools can help us locating the type incompatible problem more easily? thanks.

**Comment by andrewbranch** [comment]
In the playground, the elaboration is fairly detailed and tells the full path of mismatched properties.

**Comment by fatcerberus** [comment]
To be fair, the signal-to-noise ratio in that elaboration is pretty low because it's all object literal types.

**Comment by andrewbranch** [comment]
Yeah. It would probably be more readable if more of these types were defined as interface containing other interfaces rather than a deeply-nested literal type with aliases picking pieces out.

**Comment by Mng12345** [comment]
```ts
interface AlarmPerson { personName: string, concatInfo: string, deleted: boolean }
interface ProjectAlarmTarget {
    deleted: boolean
    managementDep: number
    associatedProjectId: number
}
interface TableAlarmTarget {
    deleted: boolean
    managementDep: number
    dataSetId: number
}
interface CreateApi {
    alarmType: number
    alarmLevel: number
    alarmPerson: AlarmPerson[]
    alarmTarget: (ProjectAlarmTarget | TableAlarmTarget)[]
}

interface EditAlarmPerson extends AlarmPerson {
    id?: number
}
interface EditProjectAlarmTarget extends ProjectAlarmTarget {
    id?: number
}
interface EditTableAlarmTarget extends TableAlarmTarget {
    id?: number
}
interface EditApi {
    id: number
    alarmType: number
    alarmLevel: number
    alarmPerson: EditAlarmPerson[]
    alarmTarget: (EditProjectAlarmTarget | EditTableAlarmTarget)[]
}

interface DetailAlarmTarget {
    id: number, managementDep: number, dataSetId?: number, associatedProjectId?: number, deleted: boolean
}

interface DetailAlarmPerson {
    id: number, personName: string, concatInfo: string, deleted: boolean
}

interface Detail {
    id: number
    alarmTarget: DetailAlarmTarget[]
    alarmPerson: DetailAlarmPerson[]
    alarmType: number
    alarmLevel: number
    createTime: number
}

interface AlarmPersonRecord {
    id?: number, personName?: string, concatInfo?: string, deleted: boolean, _id: string, _active: boolean
}
interface AlarmTargetRecord {
    id?: number, managementDep?: number, dataSetId?: number, associatedProjectId?: number, deleted: boolean, _id: string, _active: boolean
}

interface CreateForm {
    alarmType?: number
    alarmLevel?: number
    alarmPerson?: AlarmPersonRecord[]
    alarmTarget?: DetailAlarmTarget[]
}

interface EditForm {
    id: number
    alarmType?: number
    alarmLevel?: number
    alarmPerson?: AlarmPersonRecord[]
    alarmTarget?: AlarmTargetRecord[]
}

const init = async () => {
    const getDetail = (): Promise<Detail> => {
        throw new Error('unimplemented')
    }
    const detail = await getDetail()
    const createForm: CreateForm = {
        ...detail,
    }
}
```
playground [here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIIBs5QLYAVoDOA9iMgN7IAOhJAcnNhAFzIFhSgDmANMgiQjhgAkiBhEWbDiB7IAJhHQRIclgCMiRJXFIBfAFChIsRClxQiAKwgIwGLNgAqWTsvL7kn+YuURVyDS0IHQ8vbB04V0ZwABEIShYQAFdsNWhQzzgCYgRgIT9zKxsRf2TU9IMjaHgkZGc1JXscZyhXMHcvbyUVdU1tEAzkcJBIiGiwOITkMrSoQbkhOABlZWFSlNn9SvBq02QAYShgyFRKYA6vOExmgE9qRI30zquHABkIADdFB-K55+u8DQQCwmoCoMQQABtAC6gxezRcyhYAApCtZbKCWm1kAAfOpwBoQTGIsAAShhW30hh2JlqAFE5MA7AD8OCSMgIAAPSAgOQENAsoEXTzAOQAfh+m22xhqKAZTLRxWJrTcXJ5fOQioxAKxbjIg1FEumjzm0t29MZYHqjR1JI53IgvP51qJtpV7X1nUNkoq1Jle3ldjOwuQop9f0uOruzGNvzhAPeX3Q4fjDlZEJYgdB6ZIFP+Dl1YBRga1zILdrxgZdyra5NhBj95pQcTAcGA6BreoN61+vGGo3Gk3DvAWrZWJSNM2gvCyOTyKlLa0nJpHPh6AT6wQGDaqtObyjbHcFbNInq8Ydjs141BP9EYknYXF4-BAghEYgkrEfMlX3T8vSCEIdxpWVkBbQ8QwvKcI0yN02hYcD207MA80jNMgQQg8kOPCFUNggtoxTfMcETb5LyeLwECOfJHGAe9yNNKld1A7MgQAJRsIgoDkSDxWHKggTvCAjSkJ8+AEIRRHEETv1kBQ-38QJ+l4AB9C9RJ-ZAVMQMBgC+AD+kpZi9mQjj+G43jl17IYIiiR0JniKyr3kRZxyXfjZyIXJ8jkRc+IY39fEUzcdFU9TZNUnS9JjJSt0pRs9wOajIAAMS47AQ3hJxoycij8JIz5FFymDkCynMQCNViTzMri5Dw0q4OUI1EKPct3QpYD-QtJk0pwXiiLQ25qGK1MCqTEbiLBCFKpwkgau4+qssLGa2raea6vrKkXzYUMQCZZAAF5SoIG5X2QZFSUOgA+ENtvaNoWsO87SRYQpsGAAgIAAHham6Dpus9Ok8MAAAsLAAd2mCBIbpKALCgZEAHIkj27BKCUcY-ER0lBgMTo7u8Vt2yeuBwbbe7lBai7BgJqjjggXrsBYQ56cZp7AaBgA6bmFCJ9BuFxrYgA)

I have replaced all type aliases and object literal types with interfaces, and now the error messages are simpler and clearer. However, due to the large number of interfaces I have written, I am finding it difficult to remember some of the interface names. Is there a best practice for deciding when to choose between using an interface and a type?

**Comment by Mng12345** [comment]
Vscode may omit some type definitions. How can I expand them?
![image](https://github.com/microsoft/TypeScript/assets/21278900/9c1b35b8-bbe2-432e-9c16-122ee30c0b4c)

**Comment by andrewbranch** [comment]
@Mng12345 https://www.typescriptlang.org/tsconfig#noErrorTruncation

There’s also a future feature being discussed and designed that might allow you to interactively expand truncations in VS Code.

**Comment by Mng12345** [comment]
@andrewbranch I found that noErrorTruncation can cause ordinary hover tooltips to slow down significantly.

**Comment by Mng12345** [comment]
May be we can push this function into the tooltips dialog, let it expanding by user.
