### ISSUE TITLE
Commenting a function in an array emits duplicate comments

### ISSUE THREAD

**Issue by kenfdev** [Microsoft/TypeScript#5810]
Hi all,

Commenting a function inside an array emits duplicated comments after the `ts` is transpiled to `js`.

below is an example.

```js
// TypeScript file
var testArrayWithFunc = [
    // 関数
    function() {
        console.log();
    },
    // 文字列
    '1',
    // 数値
    2
]
```

The transpiled `js` file is as below

```js
// Transpiled JavaScript file
var testArrayWithFunc = [
    // 関数
    // 関数
    function () {
        console.log();
    },
    // 文字列
    '1',
    // 数値
    2
];
```

The `// 関数` part is emitted two times.  It looks like it is emitted only if the target is a function.
I apologize not having enough time to narrow down the problem further and thanks in advance.

**Comment by DanielRosenwasser** [comment]
Confirmed in for Version 1.8.0-dev.20151127

**Comment by DanielRosenwasser** [comment]
Thanks for the fix @DanCorder!
