### ISSUE TITLE
Methods with generic properties in a class cannot be assigned to unknown.

### ISSUE THREAD

**Issue by LiST-GIT** [microsoft/TypeScript#58108]
### 🔎 Search Terms

generic
method

### 🕗 Version & Regression Information

v5.4.4

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYGwhgzhAECCA8AVAfNA3gWAFDV9AJgKahgBOh0AZgK4B2wAXNABQBuYI1hTiAlNAF5UrAPYBLfAG5seaMA4hm-TDll5gI2hAAu0MEwR0A1rREB3WqgHRtACzERpq3AF9sbrEA

### 💻 Code

```ts
class A<T> {
    declare func: (value: T) => void;
    call() {
        const a: A<unknown> = this;
           // ^
    }
}
```
```
Type 'this' is not assignable to type 'A<unknown>'.
  Type 'A<T>' is not assignable to type 'A<unknown>'.
    Type 'unknown' is not assignable to type 'T'. // <-----
      'T' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.
```

### 🙁 Actual behavior

Judging from the error message, could it be that the comparison was written in reverse?

### 🙂 Expected behavior

Any value can be assigned to unknown.

**Comment by jakebailey** [comment]
This error is correct. Say you have an `A<number>`. It must be the case that you can only pass numbers into its `func`. But if you assign an `A<number>` to `A<unknown>`, now `func` can accept `unknown`, which is _anything_, which violates what `func` of `A<number>`.
