### ISSUE TITLE
Why use double quotes for strings

### ISSUE THREAD

**Issue by squarepants** [Microsoft/TypeScript#5811]
I have read this wiki [《Coding guidelines》](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines), it says we should use double quotes for strings and I have no problems with that.

But I can't stop wondering that what are the reasons behind this?

**Comment by DanielRosenwasser** [comment]
Hi there @squarepants, did you read the top paragraph?

> While **these guidelines are mainly meant for contributors to the TypeScript project**, certain suggestions apply as to how idiomatic TypeScript code should be written (e.g. the "Names" and "Style" sections).

**Comment by DanielRosenwasser** [comment]
But to specifically answer your question, we occasionally work in languages other than TypeScript. All those languages either *require* double quotes for strings (e.g. C#, C++, F#) or at least allow double quotes for strings (e.g. Python, Ruby). It's easier not to ask people to shift their muscle memory when switching back and forth between languages.

One of the most common head-scratching problems with JSON is "why can't my JSON file be parsed?" and an hour later you'll find out single-quoted strings aren't part of the JSON standard.

So double quotes have the least cognitive burden for us on the team. Hope that answers your question!

**Comment by aleksey-bykov** [comment]
we decided to ban single quotes after a day of full text searching for
"width" in code and not being able to find it because it was written 'width'

On Fri, Nov 27, 2015 at 1:44 PM, Daniel Rosenwasser <
notifications@github.com> wrote:

> But to specifically answer your question, we occasionally work in
> languages other than TypeScript. All those languages either *require*
> double quotes for strings (e.g. C#, C++, F#) or at least allow double
> quotes for strings (e.g. Python, Ruby). It's easier not to ask people to
> shift their muscle memory when switching back and forth between languages.
>
> One of the most common head-scratching problems with JSON is "why can't my
> JSON file be parsed?" and an hour later you'll find out single-quoted
> strings aren't part of the JSON standard.
>
> So double quotes have the least cognitive burden for us on the team. Hope
> that answers your question!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/TypeScript/issues/5811#issuecomment-160187924>
> .
>



-- 
Aleksey Bykov

**Comment by squarepants** [comment]
Thank you @DanielRosenwasser , I take your point completely.
