### ISSUE TITLE
NoInfer introduced in 5.4 is undocumented

### ISSUE THREAD

**Issue by xuhdev** [microsoft/TypeScript#58121]
### 🔎 Search Terms

doc, NoInfer

### 🕗 Version & Regression Information

- Since 5.4, [NoInfer](https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#the-noinfer-utility-type) was introduced, but it remains undocumented.

### 🙁 Actual behavior

`NoInfer` is undocumented.

### 🙂 Expected behavior

`NoInfer` should be documented, may be in the [Utility Types Page](https://www.typescriptlang.org/docs/handbook/utility-types.html). 

### Additional information about the issue

Without the official documentation, it remains unclear what we can and we cannot do with `NoInfer`. For example, must `NoInfer` be applied directly to a generic param? In other words, is `NoInfer<Array<T>>` allowed?

**Comment by xuhdev** [comment]
Do you consider it documented if it is only mentioned on devblog.microsoft.com? (A real question, I don't know the doc policy of typescript)

It doesn't seem to be mentioned anywhere in the official document: https://www.google.com/search?q=%22NoInfer%22+site%253Atypescriptlang.org

**Comment by MartinJohns** [comment]
When 5.4 is released you'll find the release notes on the website, e.g. for 5.3: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html

**Comment by xuhdev** [comment]
I've created a PR to get this fixed: https://github.com/microsoft/TypeScript-Website/pull/3053
