### ISSUE TITLE
Error reported only in `node_modules` directory

### ISSUE THREAD

**Issue by regseb** [microsoft/TypeScript#58128]
### 🔎 Search Terms

TS7016, node_modules

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _node_modules_

### 💻 Code

```
.
├─ package.json
├─ index.js
└─ not_node_modules/
   └─ sub/
      ├─ source.js
      └─ type.d.ts
```

- `package.json`

  ```JSON
  {
    "name": "testcase",
    "version": "1.0.0",
    "devDependencies": {
      "typescript": "5.4.4"
    }
  }
  ```

- `index.js`

  ```JavaScript
  /**
   * @type {import("./node_modules/sub/type.d.ts")}
   */
  const baz = true;

  /**
   * @type {import("./not_node_modules/sub/type.d.ts")}
   */
  const qux = true;

  // Use variable to remove "'xxx' is declared but its value is never read."
  console.log(baz, qux);
  ```

- `not_node_modules/`
  - `not_node_modules/sub/`
    - `not_node_modules/sub/source.js`

      ```JavaScript
      export default {
          BAR: 0,
      };
      ```

    - `not_node_modules/sub/type.d.ts`

      ```TypeScript
      import type Foo from "./source.js";

      export type keyofFoo = (typeof Foo)[keyof typeof Foo];
      export default keyofFoo;
      ```

1. Unzip [testcase.zip](https://github.com/microsoft/TypeScript/files/14916509/testcase.zip)
2. `cd testcase/`
3. `npm install`
4. `cp -r not_node_modules/sub/ node_modules/`
5. `npx tsc --noEmit --checkJs --strict index.js`

### 🙁 Actual behavior

```
node_modules/sub/type.d.ts:1:22 - error TS7016: Could not find a declaration file for module './source.js'. '/home/regseb/testcase/node_modules/sub/source.js' implicitly has an 'any' type.

1 import type Foo from "./source.js";
                       ~~~~~~~~~~~~~


Found 1 error in node_modules/sub/type.d.ts:1
```

### 🙂 Expected behavior

No error. Or 2 errors with `node_modules/sub/type.d.ts` and **`not_node_modules/sub/type.d.ts`**

### Additional information about the issue

The two imported directories (`not_node_modules/sub/type.d.ts` and `node_modules/sub/type.d.ts`) are identical, but TypeScript only reports an error for the file in the `node_modules` directory.

---

I have this problem in my projects. TypeScript doesn't report an error in _Metalint_ (the sub-project). But when I import it into _Cast Kodi_, TypeScript reports the error.

- [`metalint`](https://github.com/regseb/metalint)
  - [`level.js`](https://github.com/regseb/metalint/blob/v0.16.0/src/core/levels.js#L15-L18) (≃ `sub/source.js`)
  - [`level.d.ts`](https://github.com/regseb/metalint/blob/v0.16.0/src/types/level.d.ts#L6-L9) (≃ `sub/type.d.ts`)
- [`castkodi`](https://github.com/regseb/castkodi)
  - [`metalint.config.js`](https://github.com/regseb/castkodi/blob/v7.7.0/.metalint/metalint.config.js#L8) (≃ `index.js`)

**Comment by andrewbranch** [comment]
TypeScript analyzes JavaScript files for type info under `allowJs`, but this behavior is disabled by default inside `node_modules` for performance reasons. You can change it via [`maxNodeModulesJsDepth`](https://www.typescriptlang.org/tsconfig#maxNodeModuleJsDepth).

**Comment by regseb** [comment]
Thanks @andrewbranch for the explanation. There are no more errors with the: `npx tsc --noEmit --checkJs --strict index.js --maxNodeModuleJsDepth 2`

But I can't ask users of my application to add the `maxNodeModuleJsDepth` option to their _tsconfig.json_ file. Is there a best practice for this problem?
