### ISSUE TITLE
Cannot find module 'fs'

### ISSUE THREAD

**Issue by sjclemmy** [Microsoft/TypeScript#5812]
Possibly related to https://github.com/Microsoft/TypeScript/issues/5149 
I'm getting the above error when trying to compile a node reference. I've set up all the typings correctly I believe, my IDE (webStorm) is comfortable with the module name resolution and the compiled files are correct. However the compiler is still throwing these errors for core node components. 
Is this a current issue or am I missing something?

**Comment by kitsonk** [comment]
What is your `moduleResolution` compiler setting?

**Comment by sjclemmy** [comment]
I wasn't aware of that flag, but I've just added it and put in 'node' as the option and I still get the error.

**Comment by DanielRosenwasser** [comment]
WebStorm doesn't use the TypeScript language service, so I'd file an issue on JetBrains. I think their issue tracker is located at https://youtrack.jetbrains.com/issues/WEB.

**Comment by DanielRosenwasser** [comment]
Whoops, misread the original issue and removed my comment.

**Comment by DanielRosenwasser** [comment]
I'm not able to reproduce the issue. You're saying that you're getting issues at the command line, right? What version of TypeScript are you using? What are you typing on the command line to execute the compiler?

**Comment by sjclemmy** [comment]
I've isolated the commands and created a new folder etc, and I can't reproduce the issue. Let me see if it's something to do with some other element in the ts file I've created.

**Comment by sjclemmy** [comment]
Found the issue.
My script has `#!/usr/local/bin/node` at the top. This causes the issue.

**Comment by vladima** [comment]
this is bug - we should ignore shebang trivia similar to what we do with other kinds if trivia when processing reference comments

**Comment by daslicht** [comment]
Even tho I installed the latest node @types i get an error when tying to use : 
```import * as fs from "fs";```

How about this one :
```const config = require( __dirname+'/../../../config.json');```

I tried it with :
```import * as config from '/../../../config.json';```
But I just get Cannot find module...
