### ISSUE TITLE
`noImplicitAny` infers `any` for typed parameter of union's common function

### ISSUE THREAD

**Issue by adamhamlin** [microsoft/TypeScript#58133]
### 🔎 Search Terms

`noImplicitAny` `any` `union`

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about: noImplicitAny

### ⏯ Playground Link

https://www.typescriptlang.org/play?noImplicitAny=false&ts=4.9.5#code/JYOwLgpgTgZghgYwgAgLIE8Aq6AOKDeAUMicsACYD8AXMiAK4C2ARtANzGkhyMS0DOYKKADmHAL6FCMeiARhgAexDJG6AGKyEACgA2wQQHkoqODloZseANoBdZAB80ZgDyDhIEQBo0WXBAA+AEpaADdFCmQiUmR9IxMzADoYRSgAUUQAC21tRWYAKyDkAF4AqM4YknIIXQhIZDz8xIoOGPEgiUIgA

### 💻 Code

```ts
interface MyType {
    id?: number;
    name: string;
}

function myFunc(listOrMap: MyType[] | Map<string, MyType>): void {
    // When `noImplicitAny` is on, obj parameter is correctly inferred as `MyType`
    // When `noImplicitAny` is off, obj parameter is inferred as `any`
    listOrMap.forEach((obj) => {
        delete obj.id;
    });
}
```

### 🙁 Actual behavior

With `noImplicitAny=false`, the type of the `forEach` parameter is inferred as `any`.

### 🙂 Expected behavior

With `noImplicitAny=false`, the type of the `forEach` parameter is inferred as `MyType`

### Additional information about the issue

Fyi, the type is correctly inferred when `noImplicitAny=true`, or if not using the union type for `myFunc`'s parameter

**Comment by MartinJohns** [comment]
This is working as intended: https://github.com/microsoft/TypeScript/issues/52748#issuecomment-1430044120

**Comment by adamhamlin** [comment]
Ok, thanks for the info @MartinJohns
