### ISSUE TITLE
Wrapper Function that Runs Generic Function Doesn't Honor Generic Function Return Type

### ISSUE THREAD

**Issue by af-lozano** [microsoft/TypeScript#58134]
### 🔎 Search Terms

Generic Function, Wrapper, Return Type

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play?ssl=16&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgEoQM4AcD2IMoDeAUMshmHGAK4YBcyARNFDlI8gD5MbUJIYMjANylkAW0wY4AcwgB+BhSigZosgBMqcRcjggAnqIC+xMxAAeuKGGQI8FPQjDA8AdShwsWaMgC8ehgGIAjIADxiACrIlpAgGhjIABQAdGlwUDL0eoYA2gC6AJT+AHzIAAqs4sAEYejYDhAlADTEJUliiC54DJGthQyVONW1AIIA7nDAkBp1EDRQIJEGPmGRJRulyCRkZPb4tlCY-nqT007dIEmF6rtHCyDIRxgmokA

### 💻 Code

```ts
interface Response {
  status: "error" | "success";
  message?: string;
  data?: any;
}


export const actionWrapper = async <
  T extends (...args: any[]) => Promise<Response>,
>(
  action: T,
): Promise<Awaited<ReturnType<T>>> => {
    const res = await action();
    return res;
};

```

### 🙁 Actual behavior

A wrapper function that recieves an async generic function and runs it, doesn't honor the return type. In this case, the generic function returns a type of response and the wrapper function has type annotation that indicates a return of response, but when running the generic function and the result is returned, Typescript says it cannot be assigned.

### 🙂 Expected behavior

There shouldnt be a problem when returning the result.

**Comment by Andarist** [comment]
This one is better written as:
```ts
export const actionWrapper = async <Args extends any[], R>(
  action: (...args: Args) => Promise<R>,
): Promise<R> => {
  const args: Args = [] as any;
  const res = await action(...args);
  return res;
};
```

In fact, your `action()` in the original should fail. It's called with no arguments and we can't guarantee that it's sound to call `T` with no arguments here
```ts
interface Response {
  status: "error" | "success";
  message?: string;
  data?: any;
}

export const actionWrapper = async <
  T extends (...args: any[]) => Promise<Response>,
>(
  action: T,
): Promise<Awaited<ReturnType<T>>> => {
  const res = await action(); // why is this call allowed?
  return res;
};
```

**Comment by af-lozano** [comment]
You're right! Thanks a lot. I was providing the arguments in each context that called the wrapper, but i think it's cleaner to do it this way. It also supports the type hinting for each function that implements the wrapper.
