### ISSUE TITLE
Hover references/docs for JSX files  (like for regular HTML and CSS files)

### ISSUE THREAD

**Issue by mlntr** [microsoft/TypeScript#58132]
Upon hover, elements and attributes in HTML and CSS files display a useful small documentation window (tooltip) containing docs from W3C/WHATWG and link to MDN.

JSX should have this too, as it'd be more helpful than what is currently displayed.

Currently this is displayed (JSX):
![image](https://github.com/microsoft/vscode/assets/17552475/d24ca3ea-74dd-4ade-b8b3-39e19751f18a)

Suggestion:
![image](https://github.com/microsoft/vscode/assets/17552475/ef28926e-dd46-48f2-92da-7af4ccec677d)

**Comment by nmain** [comment]
This could (and maybe should?) be fixed in types:  [Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAbwL4G4BQaAmwDGAbAQymDgDci4AlYAnGdLXQ4uAczwgCMC9E044AOwIBbYAGcwtEgCkAygA0+AgQEtBMYFABm0uAEkNUdeNU4AonmBiN45SoEB6AFTO4AdQDy7uABVPngAyvvoACnDOjvwOcJiqpOgOSNHJyWgAPHGkcI4AfOhAA)

```tsx
export {};

declare var React;

declare global {
  namespace JSX {
    interface IntrinsicElements {
      /** WOW TOOLTIP */
      div;
    }
  }
}

<div />;
```

**Comment by andrewbranch** [comment]
@eps1lon do you know if this has been discussed for DOM elements/attributes in React typings?

**Comment by eps1lon** [comment]
It's a great idea. 

I haven't tried if it would be enough to just add JSDoc to https://github.com/definitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L4283-L4466. Would appreciate if somebody could try it out and file a PR.
