### ISSUE TITLE
Property 'matches' does not exist on type 'Element'

### ISSUE THREAD

**Issue by xabufr** [Microsoft/TypeScript#5813]
Example: 
```typescript
let node: Element = document.querySelector("mySelector");
node.matches("mySelector");
```
Raise the following error: `Property 'matches' does not exist on type 'Element'`
Defined in DOM Living Standard 
 * https://developer.mozilla.org/en-US/docs/Web/API/Element/matches
 * https://dom.spec.whatwg.org/#dom-element-matches

**Comment by mhegazy** [comment]
thanks @xabufr!
