### ISSUE TITLE
Shadowed import bindings require cross-file knowledge even with `isolatedModules`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#58131]
### 🔎 Search Terms

isolatedModules import duplicate

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?ts=5.4.4#code/PTAEAEGcAsHsHcCiBbAlgFwFAggQwDby4CekAyugE6oDG6oVArgKbZjiqSz67rMAmAWVj9G+ZpAaUWbCADdmlAEa9UyYaPFliAO3S4AHlJlt2AM1TiduZMwBcoM7FgA6dJEzMDAB1iV66MTezKAAYs6gALygAN4AvgDcnj5+9DSwOpD0AEK4lFGxiZimEBZWNvagqDr8Xm4ear7+sWHOADSguflxjpSwyKAA5C7ATrCDxWaMOnSoGa2wABQAlIWYUzPoczqdeStrmEA

### 💻 Code

```ts
/// @filename: index.ts
import { Foo, Bar } from './foo'

function Foo() {}
function Bar() {}
```
```ts
/// @filename: foo.ts
export type Foo = {};
export const Bar = {};
```

### 🙁 Actual behavior

TS complains about the redeclaration of `Bar` but not about the redeclaration of `Foo`

### 🙂 Expected behavior

Given that inside `index.ts` `Foo` and `Bar` are used exactly the same way, they both should be an error (or both allowed, but it's less desirable).

### Additional information about the issue

This was originally reported to Babel at https://github.com/babel/babel/issues/16423, but we cannot match the TS semantics because they require cross-file knowledge (and `isolatedModules` is supposed to prevent that).

**Comment by andrewbranch** [comment]
You forgot colons in your bug workbench compiler options. The behavior you’re looking for already exists: https://www.typescriptlang.org/dev/bug-workbench/?isolatedModules=true&verbatimModuleSyntax=true&ts=5.4.4#code/PTAEAEGcAsHsHcCiBbAlgFwFAggQwDby4CekAyugE6oDG6AXKFQK4Cm2Y4qks+u6rACYBZWIOb5WkRi3Y5wAN1aUARv1TJR4yWWIA7dLgAeMym0wdOAM1SS9uZK0ZXYsAHTpImVkYAOsSnQmYl9WUAAxV1AAXlAAbwBfAG5vPwCgmlg9SCCAIVxKGPjkixBrW1Z7R0ZUPUEfDy8Nf0D4iNcAGlB8woTQK0pYZFAAcjdgF1gRiytmPTpULPbYAAoASmLMWfn0Rb1ugvXNzCA

**Comment by nicolo-ribaudo** [comment]
Oh thanks 🙃

**Comment by sapphi-red** [comment]
Thanks :pray:
