### ISSUE TITLE
A class with only getters satisfies some type without checking for the possibility of changing these fields

### ISSUE THREAD

**Issue by Crinax** [microsoft/TypeScript#58141]
### 🔎 Search Terms

getters, types, classes, classes with getters

### 🕗 Version & Regression Information

- This is incorrect type inference
- This is the behavior in every version I tried, I tried on Nightly, 5.4.4, 3.3.3, 4.3.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.4#code/C4TwDgpgBAggCgJwPZgM5QLxQN4CgoFQCWAJgFxQB2ArgLYBGECA3LgL664DGANgIap0MHPkJcklVMATUuwJAgAUYBEQBufYNAQQ+JCTxBQVKVBXjI0AShwdRBAOYRgxEoqsUaDJiMJ+oOsDUCJRQwAAWRKgAdCZo0aSsfhx24pIuEOaIpphUEADusIrYrhQAjFBsVqy4EAkkuQDMzEA

### 💻 Code

```ts
type AProps = {
    id: number;
}

class A {
    constructor(private readonly props: AProps) {}

    get id(): number {
        return this.props.id;
    }
}

const e: AProps = new A({ id: 1 });

e.id = 3;
```

### 🙁 Actual behavior

Fails on execute without typescript errors

### 🙂 Expected behavior

It is necessary to notify the user that the class type and the user-defined type of the function argument are incompatible with each other

**Comment by jcalz** [comment]
Getters without setters result in`readonly` properties, which by #13347 are mutually assignable with read-write properties. This is all working as designed and is one of the mostly unavoidable soundness holes in the language.
