### ISSUE TITLE
需要一个更为简单的ts

### ISSUE THREAD

**Issue by pbw-langwang** [microsoft/TypeScript#58147]
### 🔍 Search Terms

Simplify

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I hope to create a concise version of TS that does not validate project plugins or HTML events, but only focuses on type validation, allowing developers to focus more on handling code rather than introducing things to solve plugins or HTML types!

### 📃 Motivating Example

Enable developers to focus more on handling code rather than introducing things to solve plugins or HTML types!

### 💻 Use Cases

Nowadays, using ts+vite and other tools, when introducing plugins or component libraries, there is no correct prompt to solve it, and we can only rely on the official website or experience! And developers don't care about the types of plugins, component libraries, or HTML events. What really matters is the running and logic of the code, not anything else

**Comment by MartinJohns** [comment]
You might want to expand a bit (or a lot) on your suggestion. It's absolutely not clear what you are actually trying to suggest.

**Comment by RyanCavanaugh** [comment]
I don't know what we're doing that's specified to plugins or HTML. A lot more clarity is required here; please open a new issue if you have specific actionable details to discuss.
