### ISSUE TITLE
checkJs finds hundreds of errors in .JS produced by TypeScript itself

### ISSUE THREAD

**Issue by zilqarneyn** [microsoft/TypeScript#58149]
### 🔎 Search Terms

checkJs

### 🕗 Version & Regression Information

 v.4.9.3
- I was unable to test this on prior versions because of having to compile whole Tone.js library retrieved from GitHub (TypeScript gives no errors, but then with --checkJs option that library gives 342 errors).

### 💻 Code

```ts
// Your code here
```
import * as Tone from "../../doc/Tone.js/Tone.js/build/esm/Tone/index.js";

function helloTone() {
    const synth = new Tone.Synth().toDestination();
    synth.triggerAttackRelease("C4", "8n");
}
document.getElementById('button0').addEventListener('click', () => { helloTone(); });

### 🙁 Actual behavior

step1   The Tone.js (from github) has two sections (the library & test sections), when tsc
is invoked the library section compiles without any error messages from tsc (the test section has multiple errors/missing) 

step2    The sample code I posted also compiles "flawlessly" through tsc (--target es6)
    
step3    Does not work when invoked/imported from .html

step4    invoking tsc "--target es6 --checkJs sample.js" issues 342 errors for that library that had been compiled by tsc itself.

### 🙂 Expected behavior

When TypeScript/tsc produces some .js (from .ts) without giving errors (nor warnings), then that .js should not have errors/warnings when checked with the --checkJs option (as far as tsc is capable of linting/checking those) -- so far as I thought/expected from TypeScript.

### Additional information about the issue

(1) The not working when loaded rom .html, is not necessarily because of "existence of errors" -- because, for example, the --checkJs option finds 506 "errors" at three.module.js, although that library works just fine.

  (2) The Tone.js release (v.14.7.77, different from v.14.8 at github) through npm is pre-compiled, & although it works fine as a bundled library (not module/import), tsc finds error (some undefined import/file) within its esm hierarchy.

**Comment by RyanCavanaugh** [comment]
> When TypeScript/tsc produces some .js (from .ts) without giving errors (nor warnings), then that .js should not have errors/warnings when checked with the --checkJs option (as far as tsc is capable of linting/checking those) -- so far as I thought/expected from TypeScript.

This is not an invariant and it's not even clear how that would be possible.

**Comment by zilqarneyn** [comment]
> You're not generating declaration files. Without declaration files the type information for your JavaScript is lost, and as a result you definitely will get errors trying to run the JavaScript through tsc.

But the explanation for the checkJs option ( https://www.typescriptlang.org/tsconfig ) suggests that JavaScript files are checked w.r.t. the internal knowledge of TypeScript (not from user-supplied declaration files): 
             "For example, this is incorrect JavaScript according to the parseFloat type definition which comes with TypeScript:
        // parseFloat only takes a string
        module.exports.pi = parseFloat(3.142);"


BTW, I wonder how tsc/checkJs generates some extra errors if/when the extra type informations are not supplied (rather than vice versa). In the example quoted above from a TypeScript document, for example, checkJs is capable of pointing out the error exactly because that definition of parseFloat comes with TypeScript.
                                             
 BTW, ironically, in the step4 of the actual behavior, I have made a typo (or, two),
         

> tsc "--target es6 --checkJs sample.js"

                                            
instead of
         "tsc --target es6 --checkJs sample.ts"
& that reminds of one utility of TypeScript, namely, a typo-checker (like also the strict-mode of JavaScript), not only a tool bag of lots of extra types beyond JavaScript.

**Comment by zilqarneyn** [comment]
In the previous comment above I have written, while writing the portion


> BTW, I wonder how tsc/checkJs generates some extra errors if/when the extra type informations are not supplied (rather than vice versa). In the example quoted above from a TypeScript document, for example, checkJs is capable of pointing out the error exactly because that definition of parseFloat comes with TypeScript.

I meant "what type annotation (that JavaScript does not see) is convincing tsc?" However, after posting the comment, then I thought that, perhaps, the term "declaration" also includes some option(s)/pragma(s) that suppress the warnings/errors that tsc would issue at step1 -- and/or some type annotation that is authorized to suppress warnings/errors (like how options/pragmas do in other languages/compilers).

Then, I looked into the tsconfig.json ( https://github.com/Tonejs/Tone.js/blob/dev/tsconfig.json ), and one of the source files ( https://github.com/Tonejs/Tone.js/blob/dev/Tone/source/Source.ts ) that contains an error. (BTW, github lists that as (now/latest) v.14.7.39, but its package.json lists the version as "14.8.0", why I had thought as if it were 14.8.0)

The error I quote from tsc is
> ../../doc/Tone.js/Tone.js/build/esm/Tone/source/Source.js:244:30 - error TS2551: Property '_start' does not exist on type 'Source'. Did you mean 'start'?                           >
> 244                         this._start(time, this.toSeconds(stateEvent.offset) + startOffset, duration);

As it stands, it is surely erroneous, and therefore web browser & the --checkJs option are exactly right in opposing it (because there is an attempt to call some undefined function).

So, how does TypeScript accept-&-translate it? In the source code (Source.ts), there are the lines (that do not exist in the corresponding/output .js file, & nothing else seems to compensate it, if not overwritten by some subclass, that both web browser & --checkJs ignore)

( https://github.com/Tonejs/Tone.js/blob/08df7ad68cb9ed4c88d697f2230e3864ca15d206/Tone/source/Source.ts#L166 )
>         // overwrite these functions
>         protected abstract _start(time: Time, offset?: Time, duration?: Time): void;

So, TypeScript needs to make the result acceptable/working for JavaScript, too  -- with or without any accompanying .d.ts files (because web browsers do not care about those .d.ts files, anyway).

**Comment by zilqarneyn** [comment]
When compiling with "tsc  --target es6  --checkJs  sample.ts", you get                     "Found 342 errors in 53 files." However, more than half of that are not language related. If you want to see only the errors that --checkJs reports for the source code itself, then you may add 3 extra options, namely, (1) --noEmit agains the javascript-overwriting quirk of tsc, and (2) the couple of "--moduleResolution node  --importHelpers" (to import tslib.js). Then, it becomes "Found 134 errors in 36 files."
                                                                                           
This methodology (checking with "--checkJs  --noEmit ...") after having compiled your project, seems essential for now (that is, at least, until TypeScript people integrate that self-verification into tsc itself).                                                                                                                                                        BTW, after seeing the previous error, that of "type-erasure" that deletes not only the types (protected, abstract), but also the variables (the function pointers listed there), you may have thought "I don't use suc things, so, it's not my problem", but that is not the only type of problem among those 134 language-based errors. Then, for example, see the next example bug/error from that list, and at no other than the simple sample posted on this page.

Although in the .ts file ( https://github.com/Tonejs/Tone.js/blob/08df7ad68cb9ed4c88d697f2230e3864ca15d206/Tone/instrument/Instrument.ts#L153 ), the 3rd & 4th parameters are optional, 
> triggerAttackRelease(note: Frequency, duration: Time, time?: Time, velocity?: NormalRange): this        

in the corresponding JS file that tsc produces, 
> triggerAttackRelease(note, duration, time, velocity)

they become regular (not default parameters, &, BTW, no default values provided at .ts, either, and TypeScript accepts that kind of "optional" (and so far as I know/remember, old/regular JS also accepts the missing ones, listing them as undefined, but modules/strictmode consider that an error, & here we are in the module-based world) and, as a result, --checkJs issues an error for it:
>  error TS2554: Expected 4 arguments, but got 2.
>
>     synth.triggerAttackRelease("C4", "8n");
>            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
>  ../../doc/Tone.js/Tone.js/build/esm/Tone/instrument/Instrument.js:118:42
>    118     triggerAttackRelease(note, duration, time, velocity) {
>                                                 ~~~~
>    An argument for 'time' was not provided.

**Comment by zilqarneyn** [comment]
Oops! The "old" JS style I mentioned/remembered is really so ( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters ) -- & if you would like
 to support also the pre-2016 browsers, you may still use it -- but (so far as I have not b
een able to fact-check the other part) the strictmode and/or module-based code also does not seem to prohibit it despite how I commented the last time:                                                                                                                          

> so far as I know/remember, old/regular JS also accepts the missing ones, listing them as undefined, but modules/strictmode consider that an error, & here we are in the module-based world) and, as a result, --checkJs issues an error for it                                                                                                                                                                                                                       

BTW, as such, the optionality operator, '?' (question mark), may be listed as an example of suppressor of warnings/errors. That is, if/when declarations are not there, an if --checkJ is checking the JS with highest suspicion (& without a global-view), then --checkJs issues errors when actually that may be acceptable code for JS.                                                                                                                             

The mentioned function (triggerAttackRelease())  itself does not do any typeof/undefined checks & passes them to other function(s), and therefore (even if --checkJs may accept it when the function itself guards against undefineds), it may have been categorized as a "using of the undefined variables" (alternatively, --checkJs could have looked through to where those are passed, to find out whether that other function is guarding against undefined variables, before listing the thing as an error).                                               

As such, as I had said, not having the type declarations, is not necessarily a reason to list "errors" (however, may list as warnings, if potentially/sometimes error-prone). However, --checkJs may have chosen to be overly cautious, labeling valid JS code as errors.
