### ISSUE TITLE
noImplicitReturns compile error for void functions as of 1.8.0-dev.20151126

### ISSUE THREAD

**Issue by myitcv** [Microsoft/TypeScript#5814]
As of `1.8.0-dev.20151126` the following now generates a compile error when `noImplicitReturns` is specified in `tsconfig.json`:

```typescript
let x = () => { console.log("Test"); }
```

```
Not all code paths return a value.
```

even though the type of `x` is `() => void`

This feels like a bug to me...

**Comment by DanielRosenwasser** [comment]
@vladima this is what I mentioned in the PR; I don't think we should be this strict if there are no return statements at all. I'm going to mark this as a bug.

**Comment by myitcv** [comment]
:+1: thanks very much! Confirmed all is good as of `1.8.0-dev.20151201`
