### ISSUE TITLE
New Website Logo: Inedo

### ISSUE THREAD

**Issue by apapadimoulis** [Microsoft/TypeScript#5815]
We :heart: TypeScript, and have tightly integrated it in all of our front-ends of our products. It has made JavaScript infinitely better to work with!

- Name: Inedo
- Homepage url: http://inedo.com/
- Brand Guidelines/Licensing: open to use - http://inedo.com/company/media
- Logo: attached png, but a svg is available here (GitHub does'nt allow upload of .svg) - https://s3.amazonaws.com/cdn.inedo.com/company/media/inedo-assets.zip

![inedo-logo](https://cloud.githubusercontent.com/assets/3965467/11450253/233929ec-9566-11e5-8e9d-8fa4d0dfe6c4.png)

**Comment by DanielRosenwasser** [comment]
We're glad to hear that! TypeScript :heart:s you too. :smile:
