### ISSUE TITLE
Typed key accessor fails to infer type when used with generic

### ISSUE THREAD

**Issue by Howard-Lam-UnitedVanning** [microsoft/TypeScript#58153]
### 🔎 Search Terms

Typed key access generic

### 🕗 Version & Regression Information

This is the behavior in every version I tried (4.9.5 and latest 5.4.4), and I reviewed the FAQ for entries about "Generics", "Type Guards"

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.4#code/JYOwLgpgTgZghgYwgAgJIBFgGcAOAbOATzgCM8UBvAKGVuTAHtNcDCAKASgC5kswpQAcwDcVAL5UwhHCgBiAVxAIAShDDyoILAGV+Q5AF5knQwD5eekCMnSUGbPiKlyAaQiEAPABVzR6rQBtF2RQZABrdwYYZC8AXR4vINjkCAAPSBAAEyw0ZkdiMhQAfmRgnhAIADdoUTEAiMIomNjRKRlkADU4PGBMt08fQ2R-ZCCQkHDI6LiEpJT0iCyc+xYnQuQAH2QFJVV1TR1LQWQSsuQK6qha+qnm0SpQSFhEFABRVLgAW3xKGnOviA8PgCKyiWhwQSA4Z-WiMPKsThAo5g5BiFEkL48TgGUzAoS1KgIBhaMDIIl4LA8Fb5ZwQfoed5fH6mALJIwBADkEIgHIANMgORjPnyBSAARyWoTiXwyQw8Dwuj0+u4GR9vuQWWzRlzISLBV89WLPjzJVQYIoEGBgMT6BA+ABGbymNipBL8hBU+FrVwqnwcaF0WUk20yoypAIISWBqBqDQTSB8AB0cIcCI4BPNSitNoTYAATE6XW6yQrur16X6A3QicHc0Nw5GUbRgNE2G0IE06wZuwLM5brSAOf6RtHY5oQ2BOE3USkKb9A7QY-t43awMmmKmiFOYajxGaLdmV3wAMxF5CM9UQd2lpX0i-M4c7msyrvIBtRugt4ztzurww9jk+0PIcq1HZcJ23QMxFnLB5wXJc4wndcvXYdMdwkMQgA

### 💻 Code

```ts
interface IDisplayable {
    toDisplay(): string;
}
type FuncReturnsString = () => string;
type IDisplayableKey<T> = {
  [K in keyof T]: T[K] extends IDisplayable ? K : never;
}[keyof T];
type ValidKey<T> = {
  [K in keyof T]: T[K] extends IDisplayable | FuncReturnsString ? K : never;
}[keyof T];

interface Example {
  name: string;
  age: {
    toDisplay(): string;
  };
  bam: ()=>string;
}
const cols: IDisplayableKey<Example>[] = ['age', 'bam', 'name'];
const col: ValidKey<Example>[] = ['age', 'bam', 'name'];

function test1<T>(x: T, c: IDisplayableKey<T>) {
    const test = x[c];
    return test.toDisplay();
}
function test2<T>(x: T, c: ValidKey<T>) {
    const test = x[c];
    if (typeof test === 'function') {
      return test();
    } else {
      return test.toDisplay();
    }
}
function test3(x: Example, c: ValidKey<Example>) {
    const test = x[c];
    if (typeof test === 'function') {
      return test();
    } else {
      return test.toDisplay();
    }
}
```

### 🙁 Actual behavior

Compiler and intellisense fail to determine that test in test1, test2 functions have the toDisplay function even though they can determine that when T is explicitly stated as Example in test3. As a result, there are errors in the functions test1 and test2 but not test3.

### 🙂 Expected behavior

There should be no error with test and test2 because T[ValidKey[T]] can only return fields of type IDisplayable or function type ()=>string

**Comment by RyanCavanaugh** [comment]
You'd need #48992 for this
