### ISSUE TITLE
AudioContextState missing in lib.d.ts

### ISSUE THREAD

**Issue by rixrix** [Microsoft/TypeScript#5816]
Hi

This has been implemented in Chrome(Opera), Firefox, Safari and lately Edge. 

Reference:
https://webaudio.github.io/web-audio-api/#idl-def-AudioContextState
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/state
https://dev.windows.com/en-us/microsoft-edge/platform/status/webaudioapi

**Comment by mhegazy** [comment]
@zhengbli is this covered in your update for the spec?

**Comment by zhengbli** [comment]
@mhegazy It was not covered in my update. 
@rixrix You are welcomed to contribute to the lib.d.ts bugs :) ! The instruction is at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes
Or I'll fix it later.

**Comment by rixrix** [comment]
Hello, thanks for looking into this PR,

@zhengbli thanks for the docs, I'd love to submit a PR ;)
