### ISSUE TITLE
Function returning `never` in branch doesn't narrow type if it's not explicitly annotated

### ISSUE THREAD

**Issue by nicolo-ribaudo** [microsoft/TypeScript#58170]
### 🔎 Search Terms

function callback never type narrowing inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwxgE8AFWAZxAAowAjALniqlpxg0aoEp4BeAPnioQANxAweA+GgDWqHAHdUXRiJxZgAbgBQ2jEQAOCAIJ94AbwKGQjAETHb8AL479R+ACEzltzfi2PRxddUEhYBDA8cgwhHFBGUwAfTx09YjIYSmZWdj5Bc214IvgWNgwdYvgAeir4AD0Afl1KrEQmeVAAOl8+Xl5-Bx5S9m5UyrgMZBh8DoRyKGxyRCwQchTq2tsAFWt4AHIkzz34YBxV2Jj5xcQiAgALBBAADyNMEGArdz2PPdttJy4ukIpAo1GyZU4kkEwjEEjyFkKxVa7TiIG6uz6-XstiGOQwo2axQmUxmqPgVywSxWaw8OgB2iAA

### 💻 Code

```ts
declare function tryParse(cb: (abort: () => never) => unknown): void;

type A = { type: "A" };
type B = { type: "B" };

declare const node: A | B;

tryParse(abort => {
    abort;
    // ^?

    if (node.type === "A") abort();

    return node satisfies B; // "Type 'A | B' does not satisfy the expected type 'B'"
})

tryParse((abort: () => never) => {
    if (node.type === "A") abort();

    return node satisfies B;
})
```

### 🙁 Actual behavior

In the first case, `node` is not refined to `B` but it still has type `A | B`

### 🙂 Expected behavior

The two usages of `tryParse` are exactly the same, `abort` has exactly the same type in both, so they should both narrow the type of `node`.

**Comment by MartinJohns** [comment]
This is working as intended and done for performance reasons. See #51075 and many many others.

**Comment by nmain** [comment]
While not precisely a duplicate of https://github.com/microsoft/TypeScript/issues/51075, this is related to that and a known limitation of `never` narrowing.  In order for narrowing to work, the type of the variable being called needs to be known before the inference pass happens.

**Comment by nicolo-ribaudo** [comment]
Oh thanks 👍
