### ISSUE TITLE
Resolving contextual `this` type in object like a class declaration

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#5817]
Graceful type inference proposal.

```ts
var o = {
  method() {
    this; // `this` is `o` object
  },
  anon: function () {
    this; // `this` is `o` object
  }
};
```

**Comment by mydiscogr** [comment]
+1
I Agree with you, I've post this proposal, but I dunno why is dissapear, such declaration correct some issues... and for me the current "traspiling" of a class is wrong... (for me)
so give a look here https://github.com/mydiscogr/jscontextproblem this is the demostration that current implementation is bugus :) and seems to there's not an hack to avoid such porblem

**Comment by DanielRosenwasser** [comment]
I think this is partially a duplicate of #3694 (see "Functions and 'this'").

**Comment by falsandtru** [comment]
I agree. Should I merge into #3694 ?

**Comment by mhegazy** [comment]
@falsandtru please post that comment in #3694.

**Comment by falsandtru** [comment]
All right, thanks.
