### ISSUE TITLE
Type Intersection incorrect for optional parameters in functions with `exactOptionalPropertyTypes: true`. `undefined` type is flip based off Intersection types

### ISSUE THREAD

**Issue by JDMathew** [microsoft/TypeScript#58174]
This issue seem to only be related when `exactOptionalPropertyTypes: true` option is set

If I have:
```typescript
type A = {
  disabled?: boolean;
};

type B = {
  disabled?: boolean | undefined;
};

type C = {
  disabled?: boolean;
};

type AB = A & B;
type AC = A & C;

const fnA = ({disabled}: A) => {
  disabled //disabled: boolean | undefined
};

const fnB = ({disabled}: B) => {
  disabled //disabled: boolean | undefined
};

// case AB is incorrect in this function!
const fnAB = ({disabled}: AB) => {
  disabled //disabled: boolean 
};

const fnAC = ({disabled}: AC) => {
  disabled //disabled: boolean | undefined
};
```

Consider `fnA`, since a property that is optional may be `undefined` when it is called it makes sense that `undefined` is added to the type, as is in the case in fnA `// disabled: boolean | undefined`. (fnB example added for completeness). 

Now consider `fnAB` with the intersection type `AB`, property disabled type should also be `// disabled: boolean | undefined` but it is not, instead it is `// disabled: boolean`

Finally `fnAC` with the intersection type `AC`, the property disabled type is now correct being `// disabled: boolean | undefined`. 

It seems like in the above example with `fnAB` (intersection of AB) the `undefined`'s are canceling out since `undefined` is added with the `?` optional parameter. A similar issue can be observed with two undefined such as ` { disabled?: boolean | undefined; } &&  { disabled?: boolean | undefined; }` would result in `//disabled: boolean`

It's worth noting this doesn't seem to only be limited to function parameter de-structuring since a similar issue is seen in:
```typescript
// incorrect
function fnAB(props: AB) {
  props.disabled //disabled?: boolean
}

// correct
function fnAC(props: AC) {
  props.disabled //disabled?: boolean | undefined
}
```

When `exactOptionalPropertyTypes: false` property disabled is always `disabled //disabled: boolean | undefined` which is correct

**Comment by andersk** [comment]
This bug causes the [`@typescript-eslint/no-unnecessary-boolean-literal-compare` rule](https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare/) to produce an unsafe automatic fix:

```diff
 const options: { flag?: boolean } & { flag?: boolean | undefined } = {};
-console.log(options.flag === false);
+console.log(!options.flag);
```

which changes the code’s output from `false` to `true`.

- typescript-eslint/typescript-eslint#9105
