### ISSUE TITLE
Allow exporting only declarations

### ISSUE THREAD

**Issue by jjrv** [Microsoft/TypeScript#5818]
Now that `outFile` supports modules, the produced `.d.ts` bundle is very similar to [dts-generator](/SitePen/dts-generator) output. It would be nice to have a command line flag to suppress actual code generation and only produce the `.d.ts` file, or to allow bundling the definitions even if the module type is commonjs or es2015.

**Comment by mhegazy** [comment]
can you elaborate on the use case? are you using npm to distribute your code?

**Comment by mhegazy** [comment]
please reopen if there is more information.
