### ISSUE TITLE
Update README.md, CONTRIBUTING.md and SECURITY.md to reduce mistakes

### ISSUE THREAD

**Issue by skanda890** [microsoft/TypeScript#58185]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Update README.md, CONTRIBUTING.md and SECURITY.md to reduce mistakes.

**Comment by MartinJohns** [comment]
Many of the proposed changes are **clearly wrong**.

**Comment by fatcerberus** [comment]
Protip: Don't run Grammarly over technical documentation.  The result is never pretty.

**Comment by skanda890** [comment]
Just don't correct the code, only correct the sentences in English.

**Comment by MartinJohns** [comment]
> only correct the sentences in English.

Which it also doesn't correctly do all the time. You also changed legal wording in some of your PRs. And links.

Running Grammarly over the files and submitting PR is just a colossal waste of everyone's time.
