### ISSUE TITLE
Type refinement on properties no longer refines the whole structure

### ISSUE THREAD

**Issue by sukovanej** [microsoft/TypeScript#58197]
### 🔎 Search Terms

type guard, type refinement, typescript 5.4.3

### 🕗 Version & Regression Information

- This changed between versions 5.4.2 and 5.4.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBA6lC8UDeUBOECGATA9gOwBsQpRIAuKAcg0oG4oAjCvAVwFsGJUoBfWgKFLQAWgmRpMuQsSEVKDOlADGFAM7BUASzwBzXgKFQAGmLgAfKMIH8sEJQQzpl+dVAAeFI9aUvgUTaoAgmIAFLJUNFAW8pQAlBSGARGUCAB8JODQ8NnJ1poAZlAhAYEhbgB0QrGxyPxQ7uUM9AD0ze5QABYYqlAYGZDG-njqklA4hTD8PEA

### 💻 Code

```ts
type W = { readonly type: 'a'; b: number };
type Z = { readonly type: 'b'; c: string };
type X = W | Z;

declare const x: X;

const isA = (type: 'a' | 'b'): type is 'a' => type === 'a';

if (isA(x.type)) {
  x.b; // x has a type X instead of W
}
```

### 🙁 Actual behavior

the `x` has the wider type `X`

### 🙂 Expected behavior

`x` has the concrete type `W`

**Comment by Andarist** [comment]
Likely this was depending on the PR that got reverted (see https://github.com/microsoft/TypeScript/pull/57750 )

**Comment by RyanCavanaugh** [comment]
-> #45770
