### ISSUE TITLE
Modify the issue templates `bug_report.yml` and `feature_request.yml` to improve the quality of further submitted issues

### ISSUE THREAD

**Issue by graphemecluster** [microsoft/TypeScript#58206]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Per [Ryan’s comment](https://github.com/microsoft/TypeScript/pull/58155#issuecomment-2057520029), here are my proposed changes to the issue templates `bug_report.yml` and `feature_request.yml`:

- Move the guidances up in both templates to make the text slightly bigger and clearer
- Add a reminder to read CONTRIBUTING.md before opening an issue in both templates
- Add a line about the number of opening bugs in `bug_report.yml` to parallelize with `feature_request.yml`
- Remove the duplicated “List/Write them (down) here so that others can find this bug more easily” in `bug_report.yml`

You may find a preview of the changes in #58155 (I am not going to copy the `diff` here) and the previews of the modified templates here:

- [`bug_report.yml`](https://github.com/graphemecluster/TypeScript/issues/new?assignees=&labels=&projects=&template=bug_report.yml)
- [`feature_request.yml`](https://github.com/graphemecluster/TypeScript/issues/new?assignees=&labels=&projects=&template=feature_request.yml)

I try to be helpful rather than making a nuisance of myself. If I am doing so by opening this issue, please kindly inform me and close it.

**Comment by RyanCavanaugh** [comment]
> Move the guidances up in both templates to make the text slightly bigger and clearer

OK

> Add a reminder to read CONTRIBUTING.md before opening an issue in both templates

This file is too long to realistically expect people to read it all

> Add a line about the number of opening bugs in bug_report.yml to parallelize with feature_request.yml

No

> Remove the duplicated “List/Write them (down) here so that others can find this bug more easily” in bug_report.yml

I don't see a problem duplicating the placeholder text with what's above it

**Comment by graphemecluster** [comment]
> I don't see a problem duplicating the placeholder text with what's above it

Then what if I duplicate the text also in `feature_request.yml`?

**Comment by graphemecluster** [comment]
Instead of all these back-and-forth communications, I think it would have saved a bunch of time to have the Team make such small modifications.

**Comment by graphemecluster** [comment]
And, forgive my pointless remarks, those are due to my OCD

**Comment by graphemecluster** [comment]
Apologies for my petulant words. I can see your standpoint now.
Undesirable changes are now removed from the PR.
