### ISSUE TITLE
Interface cannot override predicate return type with boolean

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#58202]
### 🔎 Search Terms

- must be a type predicate

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.4.5 and 5.5.0-dev.20240415

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240415#code/JYOwLgpgTgZghgYwgAgGIHt3IN4CgCQwAzhugBQAeAXMnCAJ4CUNYAFsch6QNy4C+uXKEixEKAEJwoyCBUggAJkTSYcBYqUo06TFlACuEXsj5A

### 💻 Code

```ts
interface Foo {
	isFoo(x: any): this is Foo;
}

interface Bar extends Foo {
	isFoo(x: any): true;
}
```

### 🙁 Actual behavior

In bar, see:

```
Signature '(x: any): true' must be a type predicate
```

### 🙂 Expected behavior

No error

### Additional information about the issue

Encountering this in the VS Code repo. Seems like an unexpected regression

**Comment by gabritto** [comment]
Caused by #57341.
