### ISSUE TITLE
Suggestion: from ... import

### ISSUE THREAD

**Issue by louy** [Microsoft/TypeScript#5821]
So one of the tiny silliest things when writing in typescript is that completion for import statements.
The ES6 spec suggests that import statements should look like this: 
```ts
import someFunc from './someFunc';
```
That spec was apparently designed to be an alternative to `var someFunc = require('./someFunc');`. They clearly didn't have autocompletion in mind, which is one of the best features in TS.

My suggestion is introducing a new syntax to import files in Typescript that better suites the purposes of the language. 
```ts
from './someFunc' import someFunc;
```

And the same thing should apply to "export from" statements.

```ts
from './someFile' export *;
```

In fact this issue is so annoying it [got mentioned](https://youtu.be/K6EBpMesubo?t=29m15s) in this year's //build/ conf.

**Comment by DanielRosenwasser** [comment]
We understand it can be a pain, and we've gotten this request a few times now:

* #5029
* #2371
* #4880

As I replied elsewhere:

> While the import syntax doesn't lend well to intellisense/completion, I don't think it would be appropriate to deviate from ES6.

> As @danquirk suggests in #2371 (comment), our IDE experience should compensate for this problem using something like snippets.

**Comment by louy** [comment]
I'm sorry I haven't seen those earlier. Reading your comments there I think I get why it's the case. We should probably request this in ES7 or something.
Cheers!
