### ISSUE TITLE
Constrained type param with `keyof` seems to have inconsistent behavior

### ISSUE THREAD

**Issue by Phryxia** [microsoft/TypeScript#58223]
### 🔎 Search Terms

generic, keyof, constrained, mapped type, conditional type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "This conditional type returns never when it should return the true branch"
- Also inspected #57827 #56912 

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.5#code/C4TwDgpgBAYgPAFQDRQNID4oF41QgD2AgDsATAZygGsIQB7AMygSgH5mBtVAXT0JIpRywAE4BLYgHM2UUQFdoALigMAhgBtySqMQgA3CCIBQoSFADiiFKj5EylGvSYJMOBF14E7g4eKkz5bTVNCCMTcGgWHABvKHxlYjkAWwAjQxQQZV8JaQBfMNNoGGBsWCtqWkZmTAB6GqgUujp1CFVicLNzEpxLZAqnaqg6lQ0tIA

### 💻 Code

```ts
type F<T, K> = K extends keyof T ? T[K] extends string ? true : false : never
type G<T, K extends keyof T> = T[K] extends string ? true : false

type T = { x: number, y: string }

type Ft = F<T, keyof T> // boolean
type Gt = G<T, keyof T> // false
```

### 🙁 Actual behavior

`Ft` is `boolean` while `Gt` is `false`

### 🙂 Expected behavior

I'm not sure, in my opinion the first one (`Ft`) seems reasonable. But one thing is clear. Their result should be same.

### Additional information about the issue

I suspected `G<T, K>` doesn't count external condition. I think `G<T, K>` just consider `T[keyof T]` undecidable, so that just fallb back to falsy type. But I'm not sure why it didn't happend with unconstrained one(`F<T, K>`)- which conditionally branched.

**Comment by MartinJohns** [comment]
The first is a distributive conditional type. Check the documentation about conditional types. This is unrelated to `keyof`.

**Comment by Phryxia** [comment]
@MartinJohns 

Thank you for your reply. I think I misunderstood some concept of distributive conditional logic. I'll check it out once more. I'll close this as completed.
