### ISSUE TITLE
API: Can't seem to extract JsDoc tags from declaration

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript#58249]
### 🔎 Search Terms

* `ts.getJSDocTags`
* ClassDeclaration 

### 🕗 Version & Regression Information

5.4

### ⏯ Playground Link

https://stackblitz.com/edit/vitejs-vite-jf5qkp?file=src%2Fmain.ts

### 💻 Code

```ts
import ts from 'typescript';

const filename = 'example.ts';
const code = `

/** 
 * @description foobar
 * 
 * @see test
 */
class Foo  {};
`;

const sourceFile = ts.createSourceFile(filename, code, ts.ScriptTarget.ESNext);

const visitNode = (node: ts.Node) => {
  ts.forEachChild(node, visitNode);
  console.log(ts.SyntaxKind[node.kind], ts.getJSDocTags(node));
  ts.forEachLeadingCommentRange(
    sourceFile.text,
    node.getFullStart(),
    (pos, end) => {
      console.log(sourceFile.text.slice(pos, end));
    }
  );
  console.log('-------');
};

ts.forEachChild(sourceFile, visitNode);

```

### 🙁 Actual behavior

No JSDocs tags are extracted from a file. 

### 🙂 Expected behavior

The JSDocs tags to be extracted.

**Comment by RyanCavanaugh** [comment]
JS Doc tags need parent pointers to be found. Call ` ts.createSourceFile(filename, code, ts.ScriptTarget.ESNext, true)` and this works as expected

**Comment by JeanMeche** [comment]
Thanks for the answer 👌
