### ISSUE TITLE
Where is documentation on the placement of declarations/references, etc?

### ISSUE THREAD

**Issue by da99** [Microsoft/TypeScript#5825]
Is there any place in the [TypeScript Handbook](http://www.typescriptlang.org/Handbook), or any other documentation, that goes into detail about the placement of `/// <reference path` and similar declarations? 

I've found that any code, (e.g. `"use code";`, `var my_var...`), leads to an error if placed above the declaration:

```typescript
"use script"
/// <reference path="underscore.d.ts" />

var list: Array<Number> = [1,2,3];
_.map(list, function (i) { return i;});
```
Everything compiles fine once the code is placed under `/// <reference ...`.

**Comment by mhegazy** [comment]
there is not, but we have an issue to add some documentation there. and yes, the `/// <reference ... />` is ignored if is not the first line in the file. 

Issue #1920 is tracking reporting an error if a `/// <reference ... />` tag is not at the top of the file.
