### ISSUE TITLE
`NoInfer` isn't erased and breaks type narrowing

### ISSUE THREAD

**Issue by patroza** [microsoft/TypeScript#58266]
### 🔎 Search Terms

NoInfer

### 🕗 Version & Regression Information

- This changed between versions 5.3 and 5.4 (introduced)

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240419#code/C4TwDgpgBAglC8UDeB9YBDA5gLigInTwF8AoUSKAIQWTS1zwCNiSzxoBVGuAHytYD0AqOWgA5APYBJAHYAzCACcATAB4YAPm6sAxhJkBnYFAC2uJIogGArgBtguSbIWLVHDUQDaAXRo-WctYyOsAAlvqm6GDqADRUGgAUocAQJga4lugAJvq2ILA+cXK4CeiO0vJK6hoAlAhalHVIUJbA1ooyUFDJqQYAdCZRCXJ1pEJQEDJZBlDWYFDoM1AJzZY29uXOVe4A3FBEUHwydrY1Pt2GKdlQEnLLq1Z2DrB7B0cnZ94kepdQBhImCDAAAWoRkmBogzACRMcQSKDq8C0KD6ayefToEPg2PwhCgAH5kFA+iSUHE0RsoCiKcYDrhjrZTiQgA

### 💻 Code

```ts
type A = {_tag: "a"}
type B = {_tag: "b"}

type U = A | B

// type NoInfer2<A> = A

const m: { result: NoInfer<U> }[] = []

function map<A, B>(items: readonly A[], f: (a: NoInfer<A>) => B) { return  items.map(f) }
// ends up as  ({ result: NoInfer<U>; } | null)[] instead of ({ result: A; } | null)[]
const something = map(m, (_) => _.result._tag === "a" ? { ..._, result: _.result } : null)
```

### 🙁 Actual behavior

ends up as  `({ result: NoInfer<U>; } | null)[]`

### 🙂 Expected behavior

`({ result: A; } | null)[]`

### Additional information about the issue

use the custom `NoInfer2` type instead, and it works as expected.

Here's the actual source that lead me to the problem https://www.typescriptlang.org/play#code/JYWwDg9gTgLgBAbzgQSlAhgTwDRwKIBmBApgMYy4DyYMwEAdnAL5wFQQhwBExRZMXAFCDSDAM7woxMQFcANjDFwAvHADahEuQB0s0qWLEAJgAoAjAEptYYGGInN-bcQAewCvj4709IwBUAC2J6E1d3FQA+OBMkMPgmCwtcRx0oGXoAZUx6UgsAXWFReglWdGA5YxUUNCxtAnKYYigAWXQwEylZBTFcEwB9C0jBOBG+5zcYbT6YdABzFWVVLgAxMrkZKS44AH44aloGXQ57JG0zvtw4gC44MbjmQZv9unptegZ7C0EvoA

**Comment by saram-aman** [comment]
@patroza can i work on the issue?

**Comment by patroza** [comment]
> @patroza can i work on the issue? if so then please assign!

please feel free. I know @Andarist wants to look into it next days, but no time like the present :)

**Comment by jakebailey** [comment]
https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md#issue-claiming
