### ISSUE TITLE
function with overloading incorrectly defines generic variables

### ISSUE THREAD

**Issue by orangebokov** [microsoft/TypeScript#58267]
### 🔎 Search Terms

function with overloading incorrectly defines generic variables

### 🕗 Version & Regression Information

This is a crash

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/PTAEFMA8EMFsAcA25QHsBmEBOXVYLABQRAxqgHYDOALqAJboCiil4AjKAFygDeRooADwANADSgAmuIBaESNXDkAJpVDCAfKAAUAN2iIAruG5bInYQEpQAXk2R6q6eIoAxfaxNnpV25OfkAFSwjT05GSBJDJXARGXUfTQkLUMsbRIBufiExSU1dfRDtM1TfACNUVGRocn83FmMi8wS-NEDghtMmtMlkxpKMogBfG20AOnHoLABzSk5qgE8AbQBdZq1x0cmZufIl1e6AIjoEZFhFamhqOgpQJVRwSnIAclpYS4UsA9BoVQWiUgoNFAkUoAAkfhxrEIAnIFMpVKCAgBZAAyzHAZ3I1Dy5DgxhoWDo5Cma3AiE4AV65Uq4Gq3TJo0iP0oKLoNEZFAuRMoWlxZws-0IZCotCgcCQ4AA8kwcHguNoyZxEaj0ZjqM0FiMGMxWGwtCDwZQ9U8mZRKAA5PFPCziTC+dDucDiWi+ajtAXEQggYGoWBq0DUAAWKHQdCwQMQRJQ1SUAeD2FwWFAAHc6IhEKBSigphRwILhUDtfUAEzyviEATe2ItWRQOEqNR5PSGDrFZr2NmgJytOoeRrebpSVpBQqdcKRAzRavSeKD3qdfqSTIV7LiCRNgqtrplCpVGo9x0pZpDigjreLpJHwfL4ZQ9YTaazBYrNYbLZP3Yvw7HCVqy7XchbnuR4XlAN5qA+L4fm+XZ80BWgDR+UsoUEGE60UBtlTRU5zhxPFOAJIkSW6LRFUpbhqT3elEEZRBmVZdlhS5KheTxD0ARFONwEYWUsAASUoABxXN5VI8ksNVc4NV2LUmBLfUWENYstBNOizUtM5rVtboHXqZ1ujdIwPSAA

### 💻 Code

```ts
// example of error

const ifElse1 : {
  <X, Y, Z extends X> (value: (x:X) => x is Z, onFalse: (x:Z) => Y, onTrue: (x:Exclude<X, Z>) => Y): (x:X) => Y;
  <X, Y> (value: (x:X) => boolean, onFalse: (x:X) => Y, onTrue: (x:X) => Y): (x:X) => Y;
} = (...args:any[]) => (...args:any[]) => "implementation doesn't matter" as any

const clsHas1 = <T extends HTMLElement> (name:string) => (el:T): boolean => el.classList.contains(name)

const exampleOfError : (el:HTMLElement) => any = ifElse1(clsHas1('className'), f => false, t => true)

// comment the first line and the error will be gone

const ifElse2 : {
  // <X, Y, Z extends X> (value: (x:X) => x is Z, onFalse: (x:Z) => Y, onTrue: (x:Exclude<X, Z>) => Y): (x:X) => Y;
  <X, Y> (value: (x:X) => boolean, onFalse: (x:X) => Y, onTrue: (x:X) => Y): (x:X) => Y;
} = (...args:any[]) => (...args:any[]) => "implementation doesn't matter" as any

const clsHas2 = <T extends HTMLElement> (name:string) => (el:T): boolean => el.classList.contains(name)

const theErrorIsGone : (el:HTMLElement) => any = ifElse2(clsHas2('className'), f => false, t => true)
```

### 🙁 Actual behavior

look at the example and playground, everything is completely clear there

### 🙂 Expected behavior

look at the example and playground, everything is completely clear there

**Comment by MartinJohns** [comment]
> This is a crash

It's not a crash.

Just change the order of your overloads. The order matters.

**Comment by orangebokov** [comment]
I would never have thought that order matters.

After all, these two overloads are not related to each other.

By swapping the overloads, the error will start to appear in a different place. This is strange.

Plus, if you make two functions instead of overloading, it will work great.

What doesn't the compiler like?

**Comment by RyanCavanaugh** [comment]
Order does matter. Overload resolution chooses the first "working" signature in the list. I don't see any way that second argument is reachable unless you have explicit type arguments.
