### ISSUE TITLE
JSDoc comment string with the keyword "@private" before import statement in JS file result in cryptic error TS1191 during compilation

### ISSUE THREAD

**Issue by mde** [microsoft/TypeScript#58265]
### 🔎 Search Terms

comment import statement bug private

### 🕗 Version & Regression Information

Version 5.4.5

I am the author and maintainer of the `ejs` library, which is widely used and has to work in old JavaScript runtimes. I am exploring `tsc` as a possibility for writing more modern JS, but transpiling back to ES5 for release. I have a tsconfig with `allowJs` true, and a single JS file where the actual code is a single import statement, and running `tsc` on it resulted in a cryptic error message, ` TS1191: An import declaration cannot have modifiers.`

After more than an hour of fruitlessly searching the Web, and trying different things, I finally realized that this error was happening because of a multi-line comments (specifically JSDoc), just above my import statement that contained the string `@private`.

### 💻 Code

Minimal breaking example. Actual JSDoc in the comment is much more verbose, but does include `@private` as a reference to the namespace

```js
'use strict';

/** @private */

import { foo } from './test.js';

console.log(foo);
```

### 🙁 Actual behavior

Compiler exits with `error TS1191: An import declaration cannot have modifiers.`

### 🙂 Expected behavior

I expected it to compile my file, because my file is valid JavaScript.

**Comment by saram-aman** [comment]
@mde would you like to assign the task to me, i got a fix!

**Comment by mde** [comment]
I do not appear to have the ability to assign an owner, presumably because I am not in the org? I am logged into GH, but there is no active UI around those actions.

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by mde** [comment]
Thank you for fixing this, @a-tarasyuk!
