### ISSUE TITLE
no error when re-exporting wildcard import from module and redefining a name from it

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#58270]
### 🔎 Search Terms

wildcard import redefine

### 🕗 Version & Regression Information

5.5.0-dev.20240421

### 💻 Code

```ts
// foo.ts

export const foo: number = 1;
```
```ts
// bar.ts

export * from "./foo";
export const foo: string = "asdf"; // no error
```

### 🙁 Actual behavior

no error

### 🙂 Expected behavior

error, because `foo` is already defined in `foo.ts`, so it's likely a mistake to redeclare it in `bar.ts`.

**Comment by RyanCavanaugh** [comment]
There's no runtime error and "last one in wins" semantics is well-precedented in JS. Plus, there'd be no reasonable way to opt out of this error. This seems like a job for a lint rule if it's really idiomatically an error in your codebase.
