### ISSUE TITLE
`T extends infer I1 extends { K: infer I2 }` infers I2 to unknown

### ISSUE THREAD

**Issue by mjy9088** [microsoft/TypeScript#58279]
### 🔎 Search Terms

infer extends

### 🕗 Version & Regression Information

- This syntax is introduced between versions 4.7
- This is the behavior in every version I tried

### 💻 Code

```ts
type X<T> = T extends infer I1 extends { K: infer I2 } ? { i1: I1, i2: I2 }: never;

type Result = X<{ K: 42 }>;

// Result['i2'] is unknown (42 expected)
```

### 🙁 Actual behavior

I2 is inferred as unknown

### 🙂 Expected behavior

I2 should be inferred as 42

**Comment by whzx5byb** [comment]
IMO it makes no sense to use `infer` in an infer constraint. Are there some real world code examples?

**Comment by fatcerberus** [comment]
This is like, two levels of constraint-solving.  I would never expect the compiler to be able to do this, and even if it could, there isn't just one correct answer (in particular, `unknown` is a valid solution for `I2`).

**Comment by RyanCavanaugh** [comment]
It's not wrong and there doesn't seem to be any reason to write it this way in the first place.

**Comment by mjy9088** [comment]
In my case:

```ts
type XHRMethod = "GET" | "POST"

// example
type API = { method: "GET", path: "/test" } | { method: "POST", path: "/test" };

/*
type ItWorks = {
    "GET:/test": {
        method: "GET";
        path: "/test";
    };
} | {
    "POST:/test": {
        method: "POST";
        path: "/test";
    };
}
*/
type ItWorks =
  API extends infer I
  ? I extends {
    method: infer IMethod extends XHRMethod;
    path: infer IPath extends string;
  }
  ? { [K in `${IMethod}:${IPath}`]: I }
  : never
  : never
  ;

/*
type ItDoesntWork = {
    [x: `GET:${string}`]: API;
    [x: `POST:${string}`]: API;
}
*/
type ItDoesntWork =
  API extends infer I extends {
    method: infer IMethod extends XHRMethod;
    path: infer IPath extends string;
  }
  ? { [K in `${IMethod}:${IPath}`]: I }
  : never
  ;
```

Why I need redundant `infer I`:

```ts
type XHRMethod = "GET" | "POST"

// example
type API = { method: "GET", path: "/test" } | { method: "POST", path: "/test" };

/*
type WithoutInferI = {
    "GET:/test": API;
    "POST:/test": API;
}
*/
type WithoutInferI =
    API extends {
        method: infer IMethod extends XHRMethod;
        path: infer IPath extends string;
    }
    ? { [K in `${IMethod}:${IPath}`]: API }
    : never
    ;

/*
type WithInferI = {
    "GET:/test": {
        method: "GET";
        path: "/test";
    };
} | {
    "POST:/test": {
        method: "POST";
        path: "/test";
    };
}
*/
type WithInferI =
    API extends infer I ? I extends {
        method: infer IMethod extends XHRMethod;
        path: infer IPath extends string;
    }
    ? { [K in `${IMethod}:${IPath}`]: I }
    : never : never
    ;
```

I don't think this feature is necessary, but it could improve the code in some cases.

And I think, without it, is somewhat unintuitive.

I'm really not sure about this: is implementing this feature impossible or not suitable for the purpose?

I would appreciate any guidance on this :)

**Comment by RyanCavanaugh** [comment]
You can use a helper type if you want to clean up the display a little, but this does what you want:
```ts
type WithHelper = { [K in API['method'] as `${K}:${(API & { method: K })['path']}`]: API & { method: K } };
```

**Comment by mjy9088** [comment]
It works on the example where one method has one path...

However, `{ [K in ... as ...]: ... }` seems super useful for me! I could not have thought of that. Thanks 😄😄😄
