### ISSUE TITLE
Allow explicit declaration of an object property to be omitted when the property is typed as `undefined`

### ISSUE THREAD

**Issue by C0RR1T** [microsoft/TypeScript#58272]
### 🔍 Search Terms

* undefined object
* object undefined explicit

### ✅ Viability Checklist

- [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Given this code:
```ts
type TestType =
  | {
      as: "link";
      id: string;
    }
  | {
      as: "div";
      id: undefined
    };

const test = ({as, id}: TestType) =>  as === 'link' ? `help ${id}`  : ''

// @ts-expect-error should error, id is required
test({
  as: 'link',
})

// throws an error aswell altough id is typed as undefined, we have to explicitly declare id as undefined
test({
  as: 'div',
})
```
This code defines a discrimanted union. In this union, `id` is either strongly typed as string or undefined, depending on the value of `as`. When invoking a function which has an object with the shape of `TestProps` and `as` with the value of `div`, we need to explicitly set `id` to `undefined`. This shouldn't be neccessary though since JS already does this for us (`({a: undefined}).a === ({}).a` is equal to `true`), so there is actually no need to explicitly type `undefined`.

### 📃 Motivating Example

We removed the need to explicitly type `undefined` when a property of an object is strictly defined as `undefined`. This can improve the readibility of your discrimanted union, when one union member disallows a property which another member requires.

### 💻 Use Cases

1. What do you want to use this for?
When using discrimanting unions, this feature would be specially useful since it would allow the removal of a property based on an other property easily. 
3. What shortcomings exist with current approaches?
There is currently this approach, which does throw the error `Property 'id' does not exist on type 'TestType'` when defining the function:
```ts
type TestType =
  | {
      as: "link";
      id: string;
    }
  | {
      as: "div";
    };

const test = ({as, id}: TestType) =>  as === 'link' ? `help ${id}`  : ''
```
The other way is to type it like this:
```ts
type TestType = {
  as: 'div' | 'link';
  id?: string;
}
```
This works of course, but it doesn't express the **intent** of the type nearly as good as my suggested Typing (with `undefined`). When sharing this type in a team, the other member cannot extract when the id is actually `undefined`. We could write a comment of course, but It would be nice to actually express the intent through code. 

The last way is - of course - to explicitly set `id` to `undefined` when calling the function. This is really ugly -  and as said before - "duplicates" the default behaviour of what JavaScript would atually do.

5. What workarounds are you using in the meantime?
I think I'll just go with this:
```ts
type TestType = {
  as: 'div' | 'link';
  id?: string;
}
```
since Im too lazy to type undefined everywhere I want to use the function

**Comment by whzx5byb** [comment]
What about
```ts
type TestType =
  | {
      as: "link";
      id: string;
    }
  | {
      as: "div";
      id?: undefined
    };
```

**Comment by C0RR1T** [comment]
Strictly speaking, this could be a breaking change when not implemented correctly. Based on [this question](https://stackoverflow.com/questions/47065002/setting-an-undefined-key-of-an-object-to-undefined-in-javascript) on StackOverflow, JS discrimates between implicitly setting a property to `undefined` vs. setting it implicitly as `undefined` (by not defining it). So there is the possibility that this could be breaking, for example in this code:

```ts
type TestType = {
  as: 'div';
  id?: undefined;
}

const test = (props: TestType) => "id" in props;


// true
console.log(test({as: 'div', id: undefined}));

// false
console.log(test({as: 'div'}));
```

I don't have an idea to on how this could be implemented without breaking prior code. Im also not sure if the code above has actually been written before since I don't see how the code above could be useful.

**Comment by C0RR1T** [comment]
> What about
> 
> ```ts
> type TestType =
>   | {
>       as: "link";
>       id: string;
>     }
>   | {
>       as: "div";
>       id?: undefined
>     };
> ```
Lol, haven't thought of that, thanks for your comment. Maybe `id?: never` would be even better.

Imo, this code doesn't express the intent as good as `id: undefined` would, but I mean, it works. What do you guys think?

**Comment by whzx5byb** [comment]
> Maybe id?: never would be even better.
Yeah, if you want ts report error on `test({as: 'div', id: undefined})` you can replace `id?: undefined` with `id?: never` and please make sure to turn on `exactOptionalPropertyTypes: true`

**Comment by C0RR1T** [comment]
Alright, thanks alot @whzx5byb! Im gonna go ahead and close this feature since this would be a breaking change for a small (and arguable) improvement. Consider the solutions provided by whzx or me :).
