### ISSUE TITLE
object with `?:` property type, spread last --> allowed (but shouldn't)

### ISSUE THREAD

**Issue by gnarlex** [microsoft/TypeScript#58283]
### 🔎 Search Terms

"undefined spread", "undefined ?: spread", "last partial spread"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries by searching for `spread`, `?:`, `undefined`".

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.5.0-dev.20240419#code/C4TwDgpgBAYg9nKBeKBvARgQwE4C4oB2ArgLboTYC+AUAMZwEDOwUWjE+8iKGO+AHJQDc1agHoxUAJYEANjOiMw2CJgAmdBs2mzZEAOaZZnBMjQA6S2wgAaKJfO88UIgTUQAZgrWVhoidIEHhQqalAAbjhSmOh6UKCQmkwsru4eIGZO+Kme3jT0yTp6hrogJtwWVpjsdg456X7ikkoq6lAABgAKOMDRsu1J2mA9ffjd2L1GADxcAHyZWM71eYMsxUblmQ7WtZbDE31+BYxweubV7BMAFMsEEGFIj1DrsuaLdgDkbzjSjC5uuTuag+AEoRE0oC1VGF2gB+XADY4sfaTUr4JzwwikchUBZ8f5pPIiJHPAxGWRlWCmHjbaq2ex7EbkkBHLSnCDnRiXYA3AFeIHIJ4vCnfbCfUW-AmA+6gkRAA

### 💻 Code

```ts
type Foo = {bar: number}
const base: Foo = {bar: 8};


// --- vvv --- TS compiler reports errors (rightfully so)

// inline spread
const illegal: Foo = {...base, ...{bar: undefined}};

// inferred variable type
const undefy = {bar: undefined}
const illegally: Foo = {...base, ...undefy};


// --- vvv --- I'd expect the TS compiler to also report errors below

// spread `Partial`
const partial: Partial<Foo> = {bar: undefined}
const legal: Foo = {...base, ...partial};
console.assert(undefined === legal.bar, '.bar is undefined');

// spread `?:`
const partially: {bar?: number} = {bar: undefined};
const legally: Foo = {...base, ...partially};
console.assert(undefined === legally.bar, '.bar is undefined');

```

### 🙁 Actual behavior

TS compiler allows me to assign `undefined` to a variable with non-undefined property type, by spreading a `Partial` object last. This is wrong, because I expect a property that is typed as not-undefined, not to be undefined.

### 🙂 Expected behavior

I expect that the TS compiler reports an error, when a `Partial` object is spread last in a "no undefined properties" object assignment.

**Comment by MartinJohns** [comment]
This is working as intended. That's exactly what the compiler option `exactOptionalPropertyTypes` was introduced for.

**Comment by RyanCavanaugh** [comment]
Updated the [FAQ entry](https://github.com/microsoft/TypeScript/wiki/FAQ#require-properties-to-either-be-missing-or-not-undefined-exactoptionalpropertytypes) to include "spread" as a term/example
