### ISSUE TITLE
VSCode code suggestion is wired, how to reset 

### ISSUE THREAD

**Issue by whatoeat2night** [microsoft/TypeScript#58285]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1。88。0
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. type div when using coding react 
2. see the picture, the first div suggestion is a diaster 
![target](https://github.com/microsoft/vscode/assets/13723721/960f6ed9-4f89-4c26-ac18-f112165456bf)

I will never use the div from three/examples/jsm/nodes/Nodes.js", how could it become the very first option.....
This code suggestion bothered me for a very long time. I use autocomplete for div almost every time. but now I need to select the second option every time.

**Comment by andrewbranch** [comment]
`three` has gone out of their way to explicitly mark things in `examples` as importable via [their package.json `"exports"`](https://unpkg.com/browse/three@0.163.0/package.json). I don’t think we should hard-code any special behavior here. We’re reading the intent from the package metadata.

**Comment by andrewbranch** [comment]
This is a good use for the `autoImportFileExcludePatterns` preference, though. 


<img width="571" alt="image" src="https://github.com/microsoft/TypeScript/assets/3277153/caa3ab10-fb0d-45b1-835c-d105ad00942a">

**Comment by mjbvz** [comment]
Thanks @andrewbranch! I just gave the exclude setting a try but couldn't get it working. What pattern can you use to exclude these files?

**Comment by andrewbranch** [comment]
I think `three/examples/**` should do it? I believe there is a bug where TS Server has to be restarted after changing the setting (or it may be a file-level cache bug, but restarting gets around it anyway).
