### ISSUE TITLE
Wrong type narrowing on union type.

### ISSUE THREAD

**Issue by Mng12345** [microsoft/TypeScript#58280]
### 🔎 Search Terms

type narrowing

### 🕗 Version & Regression Information

typescript version: 5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgNgQwOZQLxQIxQD5QEw5QDMhALIQKwBQVAxgPYB2AzsFALYICWjaUAFAEo0APigBvKlGlQGLNgDNESAFyxlfDFJlzWUYAgBOSCMDWMAruwBGEQ3yLbpXBQKXI0qdBmGSZ-2SZmejgIADo4eiR+AAN3FC5mTBjBJwDDUwtDRjSAXygIOGZoFzcNL3Q8XzT-XRDwyOi4jUT8FJqZDOAsnP98wuKJDudXfgNjU090UmqAucCWeoio2PGTNlbSdvn0zOzhqFyDgHpjqAALO2hgS-1wCHpXeKhWxggANzsAGhe2ZnP6BY4AATKC2YhkSgHUr8Z4VYizHY6IJLRqxZ6tIjbeZHPo0XJAA

### 💻 Code

```ts
type Flag = 1 | 2 | 3 | 4 | 5

const main = () => {
    const flag: Flag = 1
    const target: number = 3
    if (flag === 1) {
        console.log(`flag is 1`)
        return
    } else if (flag === 2) {
        console.log(`flag is 2`)
        return
    } else {
        if (target === 4) {
            console.log(`target is 4`)
            return
        }
        // here the typeof flag is never, it should be 3 | 4 | 5
        if (flag === 3) {
            console.log(`flag is 3`)
        }
    }

}
```

### 🙁 Actual behavior

The type of variable flag at line 18 is never.

### 🙂 Expected behavior

The type of variable flag at line 18 should be 3 | 4 | 5, because the `target === 4` should not narrow the type of flag.

**Comment by MartinJohns** [comment]
This is working as intended. `flag` is already `never` in line 9, because at that point TypeScript can tell that it's `never`, because the only value ever assigned to it is `?1`, and you already checked `1`.

**Comment by Mng12345** [comment]
Ohh, my mistaked the literal type.
