### ISSUE TITLE
"This comparison appears to be unintentional" and control flow analysis with a variable updated in lambda

### ISSUE THREAD

**Issue by dimikot** [microsoft/TypeScript#58291]
### 🔎 Search Terms

This comparison appears to be unintentional
control flow
callback

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "control flow callback"

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.5#code/IYZwngdgxgBAZgV2gFwJYHsIwKYA9tQLLYAUmAogE6XqUBcMJA+ttQ1TZTAD4xIAm2OKgjZ+AShgBeAHwwAbulQSYAbwBQMGAHptMAHSHNMCtVolRAdxgdzAImB3x4gNzqAvuvWhIsRCgwsSiQSSQ0tABtsZBhKbBAECOQGACN0dCjgLCkYZGDsN2NgS2BUGLwCIlJQ6TlwrVj4xJicuGAIkALjd1cvLVQ4RjiEpOkpVvbOsOMtKEwQDOx9CPQAcxI7Vk4nNy1PYzjkBEogpqS3feCIUJcgA

### 💻 Code

```ts
async function execute(onError: (_err: Error | undefined) => void) {
  // ...
  onError(new Error("a"));
}

async function run() {
  let result: boolean = true;

  await execute(() => {
    result = false;
  });

  if (result === false) { // <-- This comparison appears to be unintentional because the types 'true' and 'false' have no overlap.(2367)
    console.log("error");
  }

  return result;
}

run();
```

### 🙁 Actual behavior

It doesn't compile: "This comparison appears to be unintentional because the types 'false' and 'true' have no overlap.ts(2367)"

![CleanShot 2024-04-22 at 17 49 25@2x](https://github.com/microsoft/TypeScript/assets/65643/0b47050e-d393-4af1-8a93-875964af9581)

### 🙂 Expected behavior

Since I told TS that result is boolean explicitly, and since there is lambda assigning to that variable, it could've understand that it should relax the control flow analysis.

### Additional information about the issue

There are some somewhat similar issues and discussions on StackOverflow, but this particular example is a crystal essence.

And the behavior is BLOCKING: it's not clear, how to write the code in TS to work it around (without quirks like "as boolean" or "as any").

**Comment by fatcerberus** [comment]
#9998 covers the mutation in the arrow function; the narrowing on assignment is intentional.

**Comment by dimikot** [comment]
@fatcerberus Yes, there are lots of similar issues (and it seems like a wontfix), but I could not find any work-around (except "as boolean" or "as any" in nasty parenses), how to rewrite such a code, as a pattern. Is there any?

**Comment by MartinJohns** [comment]
You found the workaround / pattern already. Using a type assertion here is not a quirk.

**Comment by 60x20** [comment]
>  if (result === false) { // <-- This comparison appears to be unintentional because the types 'true' and 'false' have no overlap.(2367)
>    console.log("error");
>  }

Some other workarounds:
- if (Boolean(result) === false) console.log("error");
- if (!result) console.log("error");

This one doesn't work though:
- if (!!result === false) console.log("error");
