### ISSUE TITLE
TS Server should inform 'clients' about recomputed diagnostics

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5829]
Clients currently need to actively request diagnostics for TS files from the tsserver. The are not pushed 'automatically' by the tsserver. This causes problems when the tsconfig.json file changes. Consider the following test case:
- a TS file with use of decorators.
- tsconfig.json doesn't have a experimentalDecorators flag.
- editor shows a corresponding error

User edits the tsconfig.json file and adds experimentalDecorators: true. 

Depending on timing the errors in the editor disappear. Here is what happens in detail in VSCode and tsserver:
- the tsconfig.json file gets saved: both tsserver and VSCode receive the file event
- case 1.) VSCode processes the file event first and requests diagnostics but the tsserver hasn't processed the event yet. As a result the errors don't disappear.
- case 2.) tsserver has processed the file event before VSCode requests diagnostics. The errors disappear.

To reliable fix this the tsserver must either inform the editor about a 'reload' of the tsconfig.json file so that the editor re-requests all diagnostics. Of we change the protocol in a way that the tsserver can decide by itself to re-compute diagnostics.

**Comment by mhegazy** [comment]
we should recompute diagnostics.

**Comment by dbaeumer** [comment]
If we go with the recompute diagnostics path then we should make this consistent and remove the geterr request. The tsserver should decide by itself when it is best to produce diagnostics based on document open, change and close calls.

**Comment by mhegazy** [comment]
We do not want to be computing errors unless the editor is interested in them as it is a long and blocking operation. what we could do is remember which file you asked for errors in the past, and give them to you if anything changes.

**Comment by dbaeumer** [comment]
But the tsserver could better optimize this. Consider the case where the server manages two 'open' tsconfig.json project. Now one tsconfig.json file changes. If the editor needs to request the errors it will do it for all open file since the editor doesn't want to recode the logic of knowing which files are covered by which tsconfig.json file. However the tsserver already has that knowledge and only recomputes errors for open files covered by the tsconfig.json file that changed. This results in shorter blocking calls at the end.

**Comment by zhengbli** [comment]
As we are now moving to a more sophisticated solution to get project level diagnostics, this issue should be better solved after 2.0.

**Comment by waderyan** [comment]
@dbaeumer did you say this issue would become obsolete with builder logic?

**Comment by dbaeumer** [comment]
Yes, this is better done in the builder.

**Comment by mjbvz** [comment]
I believe this was partially addressed by the `projectsUpdatedInBackground` event. We now re-request diagnostics when receiving one of those

Building would provide a more complete fix
