### ISSUE TITLE
`export type * ...` statements in `.d.ts` files do not work (5.4 regression)

### ISSUE THREAD

**Issue by Blckbrry-Pi** [microsoft/TypeScript#58304]
### 🔎 Search Terms

"ts2339", "export *", ".d.ts", "regression", "5.4", "namespace", "Property does not exist"

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.4.2
- Hasn't been fixed on nightly

### ⏯ Playground Link
(Just found out about Bug Workbench)
- [5.3.3 version](https://www.typescriptlang.org/dev/bug-workbench/?ts=5.3.3#code/PTAEAEDMEsBsFMB2BDAtvAXKA9gJ2gOYB0AJkQC4DOAsAFDwAeADnuaAMbaKVurYkBXBAFl4qAEbxcWAESM0TBDIDcdOiAgwEKdFlzxGLXOVIUa9Zq1DkAnk3igAVKEi5sqUDKLA8hU1RU1Wg0oOCQ0TA4uSgF0XDM6aFQjNmdkSlAAEXgYRGhyaGiXNw8vYH1DViIAK0pA2k5ubAQiWGwCAAps3PzC7iI+QRExSVwASmVQDQBRXDdcDIALKQcuUABWIgAWIgAmOiA)
- [5.4.5 version](https://www.typescriptlang.org/dev/bug-workbench/?ts=5.4.5#code/PTAEAEDMEsBsFMB2BDAtvAXKA9gJ2gOYB0AJkQC4DOAsAFDwAeADnuaAMbaKVurYkBXBAFl4qAEbxcWAESM0TBDIDcdOiAgwEKdFlzxGLXOVIUa9Zq1DkAnk3igAVKEi5sqUDKLA8hU1RU1Wg0oOCQ0TA4uSgF0XDM6aFQjNmdkSlAAEXgYRGhyaGiXNw8vYH1DViIAK0pA2k5ubAQiWGwCAAps3PzC7iI+QRExSVwASmVQDQBRXDdcDIALKQcuUABWIgAWIgAmOiA)
- [Nightly version](https://www.typescriptlang.org/dev/bug-workbench/?ts=5.5.0-dev.20240424#code/PTAEAEDMEsBsFMB2BDAtvAXKA9gJ2gOYB0AJkQC4DOAsAFDwAeADnuaAMbaKVurYkBXBAFl4qAEbxcWAESM0TBDIDcdOiAgwEKdFlzxGLXOVIUa9Zq1DkAnk3igAVKEi5sqUDKLA8hU1RU1Wg0oOCQ0TA4uSgF0XDM6aFQjNmdkSlAAEXgYRGhyaGiXNw8vYH1DViIAK0pA2k5ubAQiWGwCAAps3PzC7iI+QRExSVwASmVQDQBRXDdcDIALKQcuUABWIgAWIgAmOiA)

#### Bug workbench
```ts repro
// @filename: orig.d.ts
export const moduleMember: "example";

// @filename: reexport.d.ts
export type * from "./orig.d.ts";

// @filename: consumer.ts
import * as Definitions from "./reexport.js";
console.log(Definitions.moduleMember); // Errors here on 5.4.2

```

#### Normal filesystem
`orig.d.ts`:
```ts
export const moduleMember: "example";
```

`reexport.d.ts`:
```ts
export type * from "./orig.d.ts";
```

`consumer.ts`:
```ts
import * as Definitions from "./reexport.js";
console.log(Definitions.moduleMember); // Errors here on 5.4.2+
```

### 🙁 Actual behavior

`./node_modules/typescript-v5.3.3/bin/tsc --noEmit *.ts` exited without errors

`./node_modules/typescript-v5.4.2/bin/tsc --noEmit *.ts` emitted error 2339:
```
consumer.ts:2:25 - error TS2339: Property 'moduleMember' does not exist on type 'typeof import("reexport")'.

2 console.log(Definitions.moduleMember); // Errors here on 5.4.2+
                          ~~~~~~~~~~~~
```

### 🙂 Expected behavior

`./node_modules/typescript-v5.3.3/bin/tsc --noEmit *.ts` to exit without errors

`./node_modules/typescript-v5.4.2/bin/tsc --noEmit *.ts` to exit without errors

### Additional information about the issue

I was unable to build versions `5.4.0` and `5.4.1` with `every-ts`, and AFAIK, bug workbench doesn't support versions other than the most recent patch version.

This change may have happened by 5.4.0 or 5.4.1, but I know it definitely changed between `5.3.3` and `5.4.2`.

**Comment by RyanCavanaugh** [comment]
`reexport` says it's only exporting the types from `orig`, so it's correct to not re-export the values. That's the difference between `export *` and `export type *`.

**Comment by Blckbrry-Pi** [comment]
Am I correct in saying that it does break backwards compatibility with Typescript 5.3.* if you were relying on `export type *` to behave like `export *` in a `.d.ts` file?

**Comment by RyanCavanaugh** [comment]
Bug fixes can break compat, yes
