### ISSUE TITLE
when using ts.getJSDocTags, the value of @type is not returned. Is there any solution?

### ISSUE THREAD

**Issue by canyuegongzi** [microsoft/TypeScript#58314]
### 🔎 Search Terms

ts.getJSDocTags、type、get jsDoc、 get js doc tags

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ___5.4.5___ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts

export default interface CommonHeaderIProps {
  /**
   * name
   *
   * @title name
   * @type string
   * @default true
   */
  testList: TestListData;
}

// code
const jsdoc = ts.getJSDocTags(node);
// code
```

### 🙁 Actual behavior

the value of type is not actually returned
{ title: 'name', type: undefined, default: 'true' }
<img width="879" alt="image" src="https://github.com/microsoft/TypeScript/assets/32031360/4448788f-3c61-44ad-93ea-f805124e5ca1">

### 🙂 Expected behavior

Can correctly return the value string of @type annotation instead of returning undefined，
example：
{ title: 'name', type: 'string', default: 'true' }

**Comment by IllusionMH** [comment]
Syntax is `@type {typeName}` and your example is missing curly braces. Does it work if you add them?
