### ISSUE TITLE
isolatedDeclarations wrongly enabled in VSCode

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#58328]
### 🔎 Search Terms

isolatedDeclaration

### 🕗 Version & Regression Information

5.5.0-beta

### ⏯ Playground Link

https://github.com/Jack-Works/reproduce/tree/main/typescript-5.5-isolatedDeclarations-vscode

### 💻 Code

```sh
git clone https://github.com/Jack-Works/reproduce/ --filter=blob:none
cd typescript-5.5-isolatedDeclarations-vscode
code . # start vscode at the current directory
```

Open `b/index.ts` in the editor. (you must not open `a/index.ts` otherwise the error won't appear)

### 🙁 Actual behavior

<img width="874" alt="img" src="https://github.com/microsoft/TypeScript/assets/5390719/8ae1db7e-4cde-4998-864f-2f02283037fc">

But A does not have `isolatedDeclarations` enabled.

<img width="858" alt="图片" src="https://github.com/microsoft/TypeScript/assets/5390719/57a514e9-a0c1-40d0-bcb1-438eca4b5301">

If you open `a/index.ts`, the error is gone, and if you close it, the error appears again.

### 🙂 Expected behavior

Works

**Comment by RyanCavanaugh** [comment]
Requires this setting to be on
![image](https://github.com/microsoft/TypeScript/assets/6685088/b70e1eed-cbcb-4fb9-9666-9aaec6503102)
