### ISSUE TITLE
Incorrect definition of createIndex function of IDBObjectStore

### ISSUE THREAD

**Issue by aksharpatel47** [Microsoft/TypeScript#5832]
I'm trying to create a composite index in Indexeddb such as

```typescript
store.createIndex('user_id,todo_id', ['user_id', 'todo_id'], {unique: true});
```

but I'm getting an error in the keyPath field due to the createIndex function having the following signature

```typescript
createIndex(name: string, keyPath: string, optionalParameters?: any): IDBIndex;
```

I checked the IndexedDB specification on w3.org and it states that keyPath can be a string or an array of strings. Hence, the function should have the following signature:

```typescript
createIndex(name: string, keyPath: string | string[], optionalParameters?: any): IDBIndex;
```

**Comment by mhegazy** [comment]
PRs are welcomed. here is some documentation on how to submit lib.d.ts fixes: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes

**Comment by aksharpatel47** [comment]
Great. I'll do it tonight.

**Comment by aksharpatel47** [comment]
The definition of createIndex is in webworker.generated.d.ts. I checked out https://github.com/Microsoft/TSJS-lib-generator. It seems I'll have to change the specification written in browser.webidl.xml in the inputfiles directory of TSJS-lib-generator. Please correct me if I'm wrong.

**Comment by mhegazy** [comment]
We should not be changing the specification, we have inputfiles/overridingTypes.json that allows you to override existing declarations when the script runs. @zhengbli can help you more.

**Comment by zhengbli** [comment]
Hi @aksharpatel47, you don't have to change the xml file, if you only want your changes to affect webworker.generated.d.ts, you can put a `"flavor":"worker"` in the added json file. Similar to 
https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/sample.json#L29

**Comment by aksharpatel47** [comment]
Thanks @zhengbli. I'll keep that in mind. However, the changes I propose should be reflected in both the dom.generated.d.ts and webworker.generated.d.ts. I added a createIndex method in the overridingTypes.json. I'm on mac, so ran build.sh. Got an error saying 

```
TSJS-lib-generator/Shared.fsx(419,17): error FS0039: The value, constructor, namespace or type 'distinct' is not defined
```
I have mono 4.2.1 installed. Can you help me out here.

**Comment by zhengbli** [comment]
@aksharpatel47 That's because you are not on F# 4.0, which normally because you are not using mono 4.2+. I tried again on a mac mini using the installer at http://www.mono-project.com/download/alpha/, which builds for me. Do you see 4.2.1 if you run `mono --version` from terminal?

**Comment by aksharpatel47** [comment]
@zhengbli Yes. 4.2.1 is what's showing up. I installed it through homebrew. I'll remove it and try to install using the universal installer on the link you just shared.
