### ISSUE TITLE
Watch cannot handle large amount of file changes

### ISSUE THREAD

**Issue by 2767mr** [microsoft/TypeScript#58342]
### 🔎 Search Terms

watch, tsc, tsserver, files, Cannot find module, or its corresponding type declarations

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about (tsc v5.4.5)

### ⏯ Playground Link

https://github.com/2767mr/tsbug

### 🙁 Actual behavior

After deleting and regenerating a large amount of auto-generated files, typescript reports an error as seen below when using `--watch`. This also affects the VS Code tsserver.
```
src/main.ts:1:32 - error TS2307: Cannot find module './app/services/generated' or its corresponding type declarations.

1 import { TranslationDto } from "./app/services/generated";
``` 

### 🙂 Expected behavior

Typescript should pick up new files even when there are a lot of them.

### Additional information about the issue

Reproduction:
1. Clone https://github.com/2767mr/tsbug
2. `npm install`
3. Open one terminal with `npm run watch`
4. After a few seconds, open another terminal with `npm run copy`

Here is the tsserver log that is created when doing this: [tsserver.log](https://github.com/microsoft/TypeScript/files/15138615/tsserver.log)

Possibly related issues:
#57330
#22710
#37514
#54511 (same use case as we have - but on our end it does not work at all instead of being slow)

**Comment by 2767mr** [comment]
Note that this bug does not happen if you reduce the amount of files that will be copied by `npm run copy`

**Comment by sheetalkamat** [comment]
Thank you for repro as thats the most helpful and crucial in investigating such issues.
