### ISSUE TITLE
Union in template literal simplifying unexpectedly

### ISSUE THREAD

**Issue by rj-lee** [microsoft/TypeScript#58340]
### 🔎 Search Terms

template literal union distributive conditional type

### 🕗 Version & Regression Information

5.4.5 and Nightly

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.4.5#code/C4TwDgpgBAYg9nAclAvFABgMwQEgN4DkAjAAwkFQA+UAFOvgHYCuAtgEYQBOAvulAGRQ83AJS8A3ACgA9NKihIsBMjRZceenmbsuvAUO68ZciAA9IAY2AQAJqigAibHFIkHVDM-ybtHHn0FhXiA

### 💻 Code

```ts
type FooN = `foo${'100' | (`${number}` & {})}`;
// type FooN = `foo${`${number}` & {}}`
// expected = "foo100" | `foo${`${number}` & {}}`
```

### 🙁 Actual behavior

`'100'` and `` `${number}` & {} `` are being simplified to `` `${number}` & {} ``. `FooN` does not have autocomplete for `'foo100'`

### 🙂 Expected behavior

`FooN` should be of type ``"foo100" | `foo${`${number}` & {}}`` and provide autocomplete for `foo100` while allowing `foo101` or any other number

**Comment by jcalz** [comment]
(There are no distributive conditional types in this issue)

#48034 #48044 #49839 #54188 #56458 #54648 #57807 #57918

From previous issues having to do with branded primitives in template literals, it's not clear what the "correct" behavior should be here. Looks like different people have very different expectations.

**Comment by rj-lee** [comment]
I can see how people might want it differently, but what if we wanted to intentionally distribute it?

```ts
type Foo<T extends string> = T extends T ? `foo${T}` : never;
type FooN = Foo<`100` | `${number & {}}`>;
// FooN is still `foo${number & {}}`
```

**Comment by RyanCavanaugh** [comment]
I don't know any good way to reason about this. Either `foo100` *is* a `foo${number & {}}`, in which case reduction is correct, or it isn't, in which case `foo${number & {}}` has no constituents.

**Comment by jcalz** [comment]
Possibly if #33471 is ever implemented there would be a way to have this work also. The issue isn’t that the reduction is incorrect, but that it obscures information people want to keep around.

**Comment by fatcerberus** [comment]
@RyanCavanaugh I assume this to be the template-string analogue of

```ts
type T = 1 | 2 | 3 | (number & {});
```

which is (IIUC, very much intentionally) *not* reduced today even though `1 | 2 | 3` are all subsumed by `number & {}`
