### ISSUE TITLE
Calling decorators with @ loses type safety with function as argument

### ISSUE THREAD

**Issue by stavalfi** [microsoft/TypeScript#58354]
### 🔎 Search Terms

decorator, function, type-safety, @, covariance, contravariance

### 🕗 Version & Regression Information

all versions

### ⏯ Playground Link

https://www.typescriptlang.org/play/?experimentalDecorators=true&emitDecoratorMetadata=true&ts=5.5.0-beta#code/PTAEHcAsFMDtQLbQC6QPYBMCMoBmBDASwBsBnUAWgD5QBjfYsvB4gI31oGsJDVRVooUviSh8AJwDmAVySxk5NLkQp02AFC5psWskJp4BRuy4AeALKrMWAGLxoAD2RwM5G9t37YAGlA2WJpx2oI7OsK6glqjWdlQAFAAO4mgJpABcoADezMYcQbAZ-rlcwQC+AJRZ6qCg4ijS4oYeegZxyBKSKBn4sACe3tU1oEkp0OLIvQDS0L0ZpMjihLCSA0OgGNCktIsJyGjiGQAqvQnQGAAKyafjvQAim9uEu-sWVtixg5WZgzUgoIQIBLEaByZA5Nh5UDENCSQi0AB0iJ+tXqjXWDx2e3Eg1KAG51KV1Oo-gBhFjo2j7fBYnh8AAClBosDQdDQgJI1K8IXEyXEoDScSJtGI+FI5HMvRJIrFOG+vzAAEkQg5TroxKz2SKWvYeftQKxoPRpKRBEUISV4Bg0JtQMywaEXJE3rZYIM6UZzZw4tkPYE7BlEld0llQA4MrBZAa+RU0hGEFHQABeGjZOrIBrwAAMoFKOcqf3A+04pAAhBBIL0APyVwbzTm0FTRbBS0WkQNoYPZGO2yNjKprNMZ0BYHEEomk8kbSnial6jCEOq6Yi9RkahIc7Xc3n88pEianPwBPLBROgOKBhIdjLZMM9+N9ipJpm98SVdT7wRRNQupNni9XkNH2TO8ozfdQpxFOpWVgeZwT9AozXg8DDUgwRKRgsEkCbF00i-GJXWJMASTZdctS5MZtwoChQAAQQAZWVVVnAwEsS00I8zDw94fEQ49YHiTJfT4vM4gjRhvAAIiwCTvEyAA3BhpGgNIsO-OwKkItYtO0moAD19IMwygA

### 💻 Code

```ts
// when method1 fails -> calls fallback with the same arguments of method1
function fallback<Method1Fn extends Function, FallbackFn extends Method1Fn>(props: { fallbackFn: FallbackFn }) {
  return function(target: any,
    propertyKey: string,
    descriptor: TypedPropertyDescriptor<Method1Fn>
  ) {
    // implement fallback logic...
    return descriptor
  };
}

// Call decorator with @ -> no compilation error :(

class MyClass1 {
  // I expect a compilation error because FallbackFn does not extend Method1Fn
  @fallback({ fallbackFn: (props: { x: number }):number => { return 0 } }) // works! why??
  static method1Class(pros: { }): number {
    return 1
  }
}

// Call decorator directly -> compilation error :)

type FallbackFn = ((prpos: { x: number }) => number) 
type Method1Fn = ((prpos: { }) => number) 

declare const fallbackFn:FallbackFn
declare const method1Fn:Method1Fn

// Compilation error -- AS expected!!
fallback<Method1Fn,FallbackFn>({fallbackFn })(null,"1",{value:method1Fn})
//                 ^^^^^^^^^^
```

### 🙁 Actual behavior

The decorator have constriant: `FallbackFn extends Method1Fn` but it is not honored when calling a decorator with `@`. But it is honored when calling the decorator as a function directly.

### 🙂 Expected behavior

Expect the same error when calling the decorator with `@` as we see when calling the decorator as a function directly.

**Comment by jcalz** [comment]
This isn't a TypeScript bug and doesn't have anything to do with decorators, really. It's method parameter bivariance, which is [working as intended](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-method-bivariance).  With [`--strictFunctionTypes`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#strict-function-types) enabled, `Method1Fn` and `typeof MyClass1["method1Class"]` are checked differently even though their IntelliSense looks the same. If you change `Method1Fn` to 

```ts
type Method1Fn = typeof MyClass1["method1Class"];
```

then the error goes away in both instances, [see Playground Link](https://www.typescriptlang.org/play/?experimentalDecorators=true&emitDecoratorMetadata=true&ts=5.5.0-beta#code/PTAEHcAsFMDtQLbQC6QPYBMCMoBmBDASwBsBnUAWgD5QBjfYsvB4gI31oGsJDVRVooUviSh8AJwDmAVySxk5NLkQp02AFC5psWskJp4BRuy4AeALKrMWAGLxoAD2RwM5G9t37YAGlA2WJpx2oI7OsK6glqjWdlQAFAAO4mgJpABcoADezMYcQbAZ-rlcwQC+AJRZ6qCg4ijS4oYeegagccgSkigZ+LAAnt7VNaBJKdDiyH0A0tB9GaTI4oSwkoPDoBjQpLRLCcho4hkAKn0J0BgACslnE30AIls7hHsHFlbYsUOVmUM1IKCEBAJYjQOTIHJsPKgYhoSSEWgAOiRv1q9UaG0eu324iGpQA3OpSup1P8AMIsDG0A74bE8PgAAUoNFgaDoaCBJBpXhC4mS4lAaTixNoxHwpHI5j6pNF4pwPz+YAAkiEHGddGI2RzRS17LyDqBWNB6NJSIIipCSvAMGgtqAWeDQi5Iu9bLAhvSjBbOHFsp7AnYMolruksqAHBlYLJDfyKhGo+NQABeGjZOrIBrwAAMoFKOcq-3AB04pAAhBBIH0APyVoYLLm0FTRbDSsWkINoEOZWN2+P8+XDNMZ0BYXGE4lkimbKniGn6jCEOq6Yh9JliMislmahKcnU8vkCoXqSZnPwBPLBRNtIMJDsZbLhnsIaN5pPM3vlI+nQRRNSupP8L8lEiKUZVILAAG0ACIkCbLAW3FSCAF0CXUKdRTqNlYAWCF-QKU9inyVCjXQwQqSw8EYN-ANnVguxiT9PI3lonx8K9WIfRw894AqOJI0YXxIKwSDfGyAA3BhpGgDJKJibiPyAA).

**Comment by stavalfi** [comment]
link to extended discussion + solution: https://discord.com/channels/508357248330760243/1234218094293946551/1234218095392981043
