### ISSUE TITLE
Segmentation fault on Node.js 22

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/TypeScript#58369]
### 🔎 Search Terms

"segmentation fault"

### 🕗 Version & Regression Information

- This is a crash

### ⏯ Playground Link

https://github.com/remarkjs/remark/tree/main/packages/remark-parse

### 💻 Code

The code is not actually relevant. It still happens if you remove the content of [`packages/remark-parse/lib/index.js`](https://github.com/remarkjs/remark/blob/main/packages/remark-parse/lib/index.js). The existence of the file is important.

### 🙁 Actual behavior

Using Node.js 22, running `tsc --build` from the [`remark-parse`](https://github.com/remarkjs/remark/tree/main/packages/remark-parse) workspace, yields:

```
$ tsc -b     
[1]    57135 segmentation fault (core dumped)  tsc -b
```

### 🙂 Expected behavior

It generates type definitions

### Additional information about the issue

It works in Node.js 20, but not Node.js 22.

If the project is built with Node.js 20, then an incremental build with Node.js 22 won’t crash TypeScript.

Neither `tsc` nor `tsc --showConfig` not `tsc --build --clean` causes a crash, only `tsc --build`.

See https://github.com/remarkjs/remark/pull/1291#issuecomment-2084920007 for some more info where this was first discovered.

**Comment by wooorm** [comment]
Also repro’d at https://github.com/syntax-tree/unist-util-visit-parents/actions/runs/8893972759, which is simpler.

The segment fault goes away by removing `declaration: true` in tsconfig

**Comment by remcohaszing** [comment]
I narrowed it down to a repo with the following files:

```jsonc
// tsconfig.json
{}
```

```ts
// index.ts
import 'mdast'
```

**Comment by remcohaszing** [comment]
I narrowed it down even further by removing parts from `@types/mdast`. I trimmed it down to this:

```ts
/**
 * How phrasing content is aligned
 * ({@link https://drafts.csswg.org/css-text/ | [CSSTEXT]}).
 *
 * * `'left'`: See the
 *   {@link https://drafts.csswg.org/css-text/#valdef-text-align-left | left}
 *   value of the `text-align` CSS property
 * * `'right'`: See the
 *   {@link https://drafts.csswg.org/css-text/#valdef-text-align-right | right}
 *   value of the `text-align` CSS property
 * * `'center'`: See the
 *   {@link https://drafts.csswg.org/css-text/#valdef-text-align-center | center}
 *   value of the `text-align` CSS property
 * * `null`: phrasing content is aligned as defined by the host environment
 *
 * Used in GFM tables.
 */
export type AlignType = "center" | "left" | "right" | null;


/**
 * Internal relation from one node to another.
 *
 * Whether the value of `identifier` is expected to be a unique identifier or
 * not depends on the type of node including the Association.
 * An example of this is that they should be unique on {@link Definition},
 * whereas multiple {@link LinkReference}s can be non-unique to be associated
 * with one definition.
 */
export interface Association {
    identifier: string;

    /**
     * Relation of association, in parsed form.
     *
     * `label` is a `string` value: it works just like `title` on {@link Link}
     * or a `lang` on {@link Code}: character escapes and character references
     * are parsed.
     *
     * It can match another node.
     */
    label?: string | null | undefined;
}

export interface Reference {
}

/**
 * Registry of all mdast nodes that can occur as children of {@link Root}.
 *
 * > 👉 **Note**: {@link Root} does not need to be an entire document.
 * > it can also be a fragment.
 *
 * This interface can be augmented to register custom node types:
 *
 *
 * For a union of all {@link Root} children, see {@link RootContent}.
 */
export interface RootContentMap {
}
```

This still causes a crash, but at this point, even removing random chunks from comments resolves the issue.

**Comment by wooorm** [comment]
random ideas:
- could it be the emoji?
- or the `[` and `]` in the link text (`[CSSTEXT]`)?

**Comment by remcohaszing** [comment]
I tried removing the emoji. That did make a difference, but so did keeping the emoji and removing another random piece of comment instead.

**Comment by wooorm** [comment]
Removing the line below the emoji does not change anything for me in `mdast-util-to-string`. Nor does the non empty line. Nor both together. For me the emoji is consistent

**Comment by fatcerberus** [comment]
The TypeScript compiler is JavaScript code, which should never be able to cause a segfault.  This sound more like a Node and/or V8 bug to me.

**Comment by wooorm** [comment]
The crash does not happen in TS 5.0.4. But does occur with typescript@5.1.0-beta.

**Comment by fatcerberus** [comment]
My point stands.  tsc is pure JS code; if any version of the compiler can cause a segmentation fault that crashes the Node.js process, that's a potential security issue and should be brought up to the Node.js team.

**Comment by jakebailey** [comment]
Thanks for narrowing that down. Realistically, nothing in that PR should have been able to segfault node (or anything in JS at all, period), so if this is new in Node 22, it's definitely a Node bug if anything.

I wasn't sure how to test with your repro, though; if you can make a branch or new repo with that content, that'd be helpful for experimentation and reporting upstream.

**Comment by remcohaszing** [comment]
Fair. I pushed the reproduction repo to https://github.com/remcohaszing/typescript-bug-58369.

**Comment by RyanCavanaugh** [comment]
Not reproing for me on Windows x64 Node 22.0.0 5.5.0-dev.20240430, potato laptop

**Comment by remcohaszing** [comment]
After setting up everything again to make a nice reproduction, I see the behaviour @wooorm described: the `👉` emoji causes the crash, it’s not random anymore.

I have also setup a test matrix in GitHub actions which shows that this errors occurs in Linux. It can’t be reproduced on Windows, because npm shipped with Node.js 22 on Windows appears to be broken.

**Comment by jakebailey** [comment]
This is actually "fixed" on TS main by #58339; that PR prevents out of bounds accesses in more places, among other tweaks, so it sounds like Node 22 has a string handling bug.

**Comment by remcohaszing** [comment]
I just confirmed using `typescript@next` fixed it for me.

**Comment by RyanCavanaugh** [comment]
Do we have a standalone (not all of tsc) repro we can hand off to Node/V8?

**Comment by jakebailey** [comment]
I have nothing yet. At 3358157469d805df1deec01d26269c5d9d6b23ae, the segfault happens in `scanJSDocCommentTextToken`, but if you add console log inside of the for loop, it stops segfaulting.

**Comment by jakebailey** [comment]
Even extracting the code out, I can't reproduce this with the same inputs to that function. At this point, I don't think there's any mimization that can be done and the only next steps are to bisect Node to see when it broke between v20 and v22 (and then when it's inevitably just a "pull in v8" change, bisect that too).

**Comment by jakebailey** [comment]
In any case, I don't think this is a problem that TS can handle; if the bug is "fixed" by adding an innocuous console log, that's a runtime problem.
