### ISSUE TITLE
staging-typescript website downtime

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#58375]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

We're doing a little hosting switcheroo on typescriptlang.org and there will be some downtime on staging-typescript.org as a result of the handoff process. If everything goes well you shouldn't see any downtime on typescriptlang.org itself, but it's also possible things won't go well. Documentation is always still available at https://github.com/microsoft/TypeScript-Website/tree/v2/packages/documentation/copy/en should you need it

**Comment by RyanCavanaugh** [comment]
Certificate problems, of course. Investigating.

**Comment by RyanCavanaugh** [comment]
We're back! Thanks for your patience everyone 😅

staging-typescript will return in a few days

**Comment by jakebailey** [comment]
A few days was just one day; staging-typescript.org is now redirecting to the main site.
