### ISSUE TITLE
Type inference: is that a bug?

### ISSUE THREAD

**Issue by jcayzac** [microsoft/TypeScript#58382]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I'm not sure if the following is a bug or if it's working as intended.

```ts
interface Entry<P, D> {
  point: P
  datum: D
}

class X<P, D, E extends Entry<P, D>> {
  readonly p: P
  readonly d: D

  constructor(entry: E) {
    this.p = entry.point
    this.d = entry.datum
  }
}

const a = new X({ point: 1, datum: 'a'})
```

Here, `a` is inferred to be of type `X<unknown, unknown, { point: number; datum: string; }>` (while `a.p` and `a.d` have the correct types).

I expected it to be of type `X<number, string, { point: number; datum: string; }>`.

Can anybody explain what's going on here? I'm using Typescript 5.4.3.

**Comment by Andarist** [comment]
This is just not something that TS supports. Inference targets have to appear in parameter lists - the "sources" in constraints of other type parameters are ignored. An even simpler repro:
```ts
interface Box<T> {
  value: T;
}
function test<T, B extends Box<T>>(a: B) {}
test({ value: 10 });
```

Arguably, you probably don't want this signature. In situations like this you probably don't want to allow such calls:
```ts
new X<number, string, { point: 1, datum: 'a' }>({ point: 1, datum: 'a' })
```

I'd assume that your `E` should be strictly `{ point: number, datum: string }` here but your signature allows different subtypes of that.

**Comment by jcalz** [comment]
see #7234 which was not implemented in favor of having people use intersections instead.

**Comment by jcayzac** [comment]
Thank you both, @Andarist @jcalz
