### ISSUE TITLE
Should javascript files report errors like cannot find module?

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/TypeScript#5838]
moduleTest\a.js
```typescript
import {a} from "b";
a++;
```
After compiling this as 
```
tsc moduleTest\a.js --allowJs --outDir moduleTest\OutDir --module commonjs
```
no errors are reported.

**Comment by sheetalkamat** [comment]
https://github.com/Microsoft/TypeScript/commit/5657469666c8257a9e6bb32d02925e074bf9e522#diff-5f84377bdd5fb13a5afbefcee52563d2R10 shows has testcase for this

**Comment by DanielRosenwasser** [comment]
But it looks like https://github.com/Microsoft/TypeScript/commit/5772dade970d366f61c8b5bffb0f7d60b1edf8d1#diff-5f84377bdd5fb13a5afbefcee52563d2R10 actually *should* resolve correctly given that it has a `c.js` in `node_modules`

**Comment by sheetalkamat** [comment]
@DanielRosenwasser  we do not pick *.js or *.jsx from external package. Only typescript files irrespective of allowJs

**Comment by mhegazy** [comment]
After discussing this, JS file should report "appropriate" errors. https://github.com/Microsoft/TypeScript/issues/7162 tracks doing that.
