### ISSUE TITLE
[isolatedDeclarations][5.5] Adding `satisfies` to a const expression makes it require explicit type annotation

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#58397]
### 🔎 Search Terms

isolated declarations, satisfies, const

### 🕗 Version & Regression Information

This changed in commit or PR https://github.com/microsoft/TypeScript/pull/58201

### ⏯ Playground Link

https://tsplay.dev/wRbGEw

### 💻 Code

```ts
export const foo = {
  a: 42
} as const satisfies Record<string, number>;
```

### 🙁 Actual behavior

`Variable must have an explicit type annotation with --isolatedDeclarations.ts(9010)`

### 🙂 Expected behavior

No errors

**Comment by jakebailey** [comment]
My impression was that `satisfies` may impact the contextual type of an expression and cause its type to change, such that its type may not be syntactically inferable. (Need to dig up that example again, though.)

**Comment by MichaelMitchell-at** [comment]
> My impression was that `satisfies` may impact the contextual type of an expression and cause its type to change, such that its type may not be syntactically inferable. (Need to dig up that example again, though.)

Yep I've definitely seen cases where `satisfies` influences the contextual type of an expression, but I wonder if the `as const` + direct assignment to a variable is a sufficiently well-defined scenario that we can always trivially extract the type.

**Comment by dragomirtitian** [comment]
It is not unfortunately:

```ts
const x = [function() { return "A"}] as const satisfies Array<() => "A">
const x = [function() { return "A"}] as const
```
[Playground Link](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAHjAvDA2gMwK5mFAluACgEoYBvGAJwFMoMKwYAiAQUYF8BdGAQwhlEiwI3PBDS4qfZhQrcAngB5iSAHxNWKgFADo8JKkzY8hEuWq1669l179w0IA)

**Comment by MichaelMitchell-at** [comment]
I wonder if the problem boils down to it not being possible to determine whether the `const` inference of an expression or the `satisfies` inference or combination of the two leads to the more specific type, then can we defer that decision down the line, so that
```ts
export const x = [function() { return "A"}] as const satisfies Array<() => "A">
```
would be emitted as
```ts
export declare const x: Resolve<readonly [() => string], [() => "A"]>
```

Are there cases where knowing only the `const` inference of an expression + the `satisfies` type isn't sufficient to determine the contextually inferred type?

**Comment by MichaelMitchell-at** [comment]
Forgive me for pushing on this, as I'm sure folks are eager to treat this as an open and shut case. We have hundreds of instances of this pattern in our code base, the majority in which are cases where `satisfies` wouldn't affect the contextually inferred type. We adopted the operator early on under a different a different assumption
> The new satisfies operator lets us validate that the type of an expression matches some type, without changing the resulting type of that expression[0]

So while we could migrate back to our old pattern (since duplicating the structure of the expression with an explicit type is the less desirable) of doing a type test like
``tsx
function upcast<T>(value: T): void { return value }

export const foo = {
  a: 42
} as const;
upcast<Record<string, number>>(foo);
```
asking developers to write unidiomatic code with an abstruse explanation is an outcome I want to push against.

[0] https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#satisfies

**Comment by fatcerberus** [comment]
`satisfies` invoking contextual typing is a necessary evil imo; you want e.g. `[42] satisfies [number]` to succeed, but for that you need to contextually type `[42]` by `[number]` so that it doesn't widen to an array type before it can be checked.  But that in turn means that `[42]` ultimately gets inferred as a tuple type instead of an array type.  There's no mechanism to "reverse" that after-the-fact because it actually changes which type is *initially* inferred for the expression.

**Comment by jakebailey** [comment]
There's a general class of "operators that affect the actual type", including but not limited to:

- `satisfies`
- `... ? ... : ...`
- Some forms of destructuring + defualting
- basically anything with widening / freshness (including Symbol, unfortunately)

Isolated declarations is designed to be syntax-only, meaning an external implementation (or TS internally) must always be able to detect when there's a problem or produce an equivalent annotation / initializer.

If we do want to allow these things, then dts emit is going to have to gain some sort of syntax or builin type to describe these behaviors, but right now, they don't really exist.

**Comment by RyanCavanaugh** [comment]
If the `satisfies` operator doesn't change the type of the inferred expression, then it's always safe to rewrite this into two lines:
```ts
export const foo = {
  a: 42
} as const;
foo satisfies Record<string, number>;
```

**Comment by MichaelMitchell-at** [comment]
> If the `satisfies` operator doesn't change the type of the inferred expression, then it's always safe to rewrite this into two lines:
> 
> ```ts
> export const foo = {
>   a: 42
> } as const;
> foo satisfies Record<string, number>;
> ```

While visually will take some getting used to, I suppose that's a good enough solution (thank you for providing one and not just mansplaining how things work).
