### ISSUE TITLE
Unable to type nested fields in a Node.js module.

### ISSUE THREAD

**Issue by akwotom** [microsoft/TypeScript#58406]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.88.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Setup a node.js project
2. `npm install tranzak-node@3.1.3`
3. Write the following code. 
```js
import TRANZAK from 'tranzak-node'
const client = new TRANZAK(/* Just leave the credentials empty */)

// Now, we expect auto complete with the nested fields
const sendFxn = client.sms.send; // VS code doesn't think this is a function. It thinks it is 'any'
// However, the function is actually defined in the module.
// If you Ctrl+Click, on 'sms', you would see the definition of the 'send' function.
```

Within the node module itself (e.g in `index.mjs`), you would find that the code is correctly completed.

**Comment by mjbvz** [comment]
Their typings files are importing js files:

![Image](https://github.com/microsoft/TypeScript/assets/12821956/3701691f-9484-4186-bfcb-ed0b7e9788c3)

TS team can weigh in but seems like an issue on the package side to me

**Comment by RyanCavanaugh** [comment]
ATTW says this is misconfigured: https://arethetypeswrong.github.io/?p=tranzak-node%403.1.3

**Comment by akwotom** [comment]
> ATTW says this is misconfigured: https://arethetypeswrong.github.io/?p=tranzak-node%403.1.3

Thanks for the insight. I didn't even know such a tool existed.

**Comment by akwotom** [comment]
> ATTW says this is misconfigured: https://arethetypeswrong.github.io/?p=tranzak-node%403.1.3

Here's a screenshot from ATTW

![Screenshot from 2024-05-03 05-53-12](https://github.com/microsoft/TypeScript/assets/91361600/99a0934a-ecf9-46c2-bc6e-ad1733a6d18d)

It says `CJSOnlyExportsDefault`, which according to my intuition means, only commonjs exports have been done by the package.

However, the actual `package.json` has configuration for `modulejs` (mjs), and `types`


![Screenshot from 2024-05-03 06-00-00](https://github.com/microsoft/TypeScript/assets/91361600/c167921f-7c91-4867-af8a-8578c0e8e9d1)

And in the index.d.ts, it simply imports the main class of the package. 

![Screenshot from 2024-05-03 06-04-17](https://github.com/microsoft/TypeScript/assets/91361600/7204a1d7-1d63-4789-8dbd-2ae37d4f4db7)

At this point, I expect VS code to correctly infer the type. And yes, it does.

The problem is, **nested fields are not working**.

**Comment by akwotom** [comment]
> ATTW says this is misconfigured: https://arethetypeswrong.github.io/?p=tranzak-node%403.1.3

![Screenshot from 2024-05-03 06-13-26](https://github.com/microsoft/TypeScript/assets/91361600/331075c0-e4ce-43ca-84db-e357bedfa7f4)

Clearly, the error isn't even about types.

**Comment by jakebailey** [comment]
The layout of this package is nonsensical; they're importing from `index.mjs`, but there is no `index.d.mts` that describes it. I have no idea how this could have been working before.

**Comment by akwotom** [comment]
The package has `index.d.ts`, but no `index.d.mts`.
And, locally, I just tried renaming all `.d.ts` files to `.d.mts`, and changing the reference in `package.json`, but the situation didn't improve.

**Comment by jakebailey** [comment]
That really isn't the problem; the problem is that there really are not any type definitions for this class. Renaming things won't help when there's no type info at at all. This is most definitely a problem with the package.

**Comment by akwotom** [comment]
![327650413-7204a1d7-1d63-4789-8dbd-2ae37d4f4db7](https://github.com/microsoft/TypeScript/assets/91361600/42e3b7ae-635e-46f9-9b67-f63788321d8f)

VS code has JS-TS interoperability, where you can import a JavaScript class, and it would be typed correctly.
And when you look at the `index.d.ts` file, you see how **TRANZAK** is imported from `index.mjs`
The expected behaviour, is that VS code would perform it's regular type inference.
