### ISSUE TITLE
[transpileDeclaration API][5.5] Type containing enum values is incorrectly emitted

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#58423]
### 🔎 Search Terms

transpile declaration api emit enum missing

### 🕗 Version & Regression Information

- This changed in commit or PR https://github.com/microsoft/TypeScript/pull/58261 @weswigham 

### ⏯ Playground Link

https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro

### 💻 Code

```ts repro
// @strict: true
// @declaration: true
// @showEmit
// @showEmittedFile: a.d.ts
// @showEmittedFile: b.d.ts

// @filename: a.ts
export enum Foo {
  A = 'a',
  B = 'b',
}

// @filename: b.ts
import {Foo} from './a';

export type Bar = {
  [Foo.A]: 1;
  [Foo.B]: 2;
}

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=7&ts=5.5.0-dev.20240502#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoEEATLRAGwENYzp4B7AOzU13ygAsaB3AUQFt5o8YNp179oWAgDF4JLGjIA6AguiRBESO259o4qTLmgARkpVr14AGYG6ZHocWqcWAB4AHGrGigsdDD1BJGhpQAG8cUFAAQVAAXlAAcjIEgBoI0AAhOMSjVJwAXxwLa1lbezQTJ3geDy8woJp80EtYGgCEhWBkgG4i11rvaABPNyxMimzwyIBtBoUogF00AEZembmMpdAAJl7CoA)

### 🙁 Actual behavior

Refer to this program which invokes the `ts.transpileDeclaration` API:
https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro/blob/main/transpile.mjs

Basic instructions to invoke it can be found in
https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro/blob/main/README.md

When using the API, `b.d.ts` is emitted as
```ts
export type Bar = {};
```
while when using `tsc` it gets emitted as
```ts
import { Foo } from './a';
export type Bar = {
    [Foo.A]: 1;
    [Foo.B]: 2;
};
```

### 🙂 Expected behavior

Using the API should emit
```ts
import { Foo } from './a';
export type Bar = {
    [Foo.A]: 1;
    [Foo.B]: 2;
};
```

### Additional information about the issue

It's entirely possible that usage of the API is incorrect, though it doesn't seem to deviate from the patterns demonstrated in https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

**Comment by jakebailey** [comment]
Did you check the returned errors from the transpile function?

**Comment by MichaelMitchell-at** [comment]
> errors

Yeah, no errors

**Comment by jakebailey** [comment]
@weswigham should this have errored through the API? (Or will it after your PR?)
