### ISSUE TITLE
5.5 Beta - Error assigning const string to enum from another file

### ISSUE THREAD

**Issue by lukpsaxo** [microsoft/TypeScript#58424]
### 🔎 Search Terms

error 5.5 beta "has a string type, but must have syntactically recognizable string syntax when 'isolatedModules' is enabled"

### 🕗 Version & Regression Information

- This changed between versions 5.4 and 5.5 beta

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.0-beta&ssl=5&ssc=3&pln=1&pc=1#code/KYDwDg9gTgLgBAYwgOwM7wXAvHARAQVwG4AoE4ZAVwFs4AhOAbxLlbgENtEAaEgXyJA

### 💻 Code

The playground doesn't reproduce - I guess it only happens when importing from another file

otherFile
```ts
export const c = "A";
```

```ts
import * as otherFile from './otherFile';

enum B {
    a = otherFile.c,
};
```

### 🙁 Actual behavior

'otherFile.c' has a string type, but must have syntactically recognizable string syntax when 'isolatedModules' is enabled

### 🙂 Expected behavior

No error like in 5.4 - or a better explanation of what I am doing wrong :/

### Additional information about the issue

This seems to have also come up in the new errors report:

https://github.com/microsoft/TypeScript/issues/57922

**Comment by jakebailey** [comment]
Isolated modules means that an emitter only needs to see a single file to know how to emit it. In this case, the error is correct because the type of `a` impacts whether or not the enum has a reverse mapping or not, and is therefore disallowed as only tsc could know that via analyzing other files.

See also https://github.com/microsoft/TypeScript/issues/56153

**Comment by lukpsaxo** [comment]
Reading the linked issue, I think I get it now.. It just wasn't obvious from the error message - "but must have syntactically recognizable string syntax" - I was thinking somehow the type of the constant was ending up `string` instead of a specific string e.g. `"A"`

**Comment by jfirebaugh** [comment]
If you actually need to assign an enum value using an imported constant, and also need `isolatedModules`, how do you actually provide a syntactically recognizable string syntax?

Neither of these work:

```ts
enum B {
    a = FOO satisfies string, // Type 'string' is not assignable to type 'number' as required for computed enum member values.
    b = FOO as string, // Same
};
```

**Comment by RedPineapple** [comment]
@jfirebaugh 

You can do it with a template literal, like this:

```
enum B {
  a = `${FOO}`,
}
```
