### ISSUE TITLE
Enum allows numeric keys with leading 0s 

### ISSUE THREAD

**Issue by laurenz-rausche** [microsoft/TypeScript#58435]
### 🔎 Search Terms

"enum leading 0", "enum numeric"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "enums"

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.0-dev.20240504#code/KYOwrgtgBAKsDOAXAouCBvAUFKAiA+gAy5QC8eAJgPYJQDuVATgNZQCG8UAlolPABZUwAGwq5seYmTxRqtEFV4MW7Tjz6CRFKAsS4ANBNyEp5XMuacARmF4ChonYoNHCARhJn6TS1Bt3NR10XAF9MTDgkVEgAOiIIhBQ0GMIEqOSTNKTY9yA

### 💻 Code

```ts
enum TestEnum{
  "_0" = "does work as it should"
  "0" = " does not work as it should not",
  "00" = "works but should not",
  "01" = " works but should not",
}

TestEnum._0
TestEnum.0
TestEnum.00
TestEnum.01
```

### 🙁 Actual behavior

An enum can be set with a numeric key when a leading 0 is added.

### 🙂 Expected behavior

The enum keys "00", "01", ... should not be allowed to be set, as they are unvalid to write as `TestEnum.00`, `TestEnum.01`, ...

**Comment by xiBread** [comment]
Bracket notation is still valid: `TestEnum["00"]`

**Comment by laurenz-rausche** [comment]
Yeah, but in that sense `TestEnum["0"]` would also be valid.

**Comment by fatcerberus** [comment]
It's not about whether or not you can write `TestEnum.Foo` (e.g. `"Foo Bar" = "works"` is also legal) but whether the name of a member could potentially clash with a reverse mapping, so keys that overlap with the canonical string representation of a number are intentionally not allowed.

**Comment by jcalz** [comment]
This isn't a bug: all of the following are intentionally allowed:
```ts
enum TestEnum {
  "1e2",
  "3.40",
  ".567",
  "88888888888888888"
}
```
It's for the reason @fatcerberus said; while those can be parsed as numbers, they are not how those numbers would be represented when converted to strings, so they cannot conflict with [reverse mappings](https://www.typescriptlang.org/docs/handbook/enums.html#reverse-mappings).  If there were no reverse mappings, all numeric keys would be allowed.

**Comment by laurenz-rausche** [comment]
Oh okay! Thank you for the information, and sorry for the wrong assumption and the disturbance :D
