### ISSUE TITLE
[transpileDeclaration API][5.5] Type-only import is missing when type is used as arrow function argument

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#58430]
### 🔎 Search Terms

transpile declaration api emit missing import

### 🕗 Version & Regression Information

- This changed in commit or PR https://github.com/microsoft/TypeScript/pull/58261 @weswigham 

### ⏯ Playground Link

https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro/tree/bug2

### 💻 Code

```ts repro
// @strict: true
// @declaration: true
// @showEmit
// @showEmittedFile: a.d.ts
// @showEmittedFile: b.d.ts

// @filename: a.ts
export interface Type {}

// @filename: b.ts
import { type Type } from "./a";

export const foo = (_: Type): void => {};
export const bar = (_: import("./a").Type): void => {};

```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=7&ts=5.5.0-dev.20240502#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoEEATLRAGwENYzp4B7AOzU13ygAsaB3AUQFt5o8YNp179oWAgDF4JLGjIA6AguiRBESO259o4qTLmgARkpVr14AGYG6ZHocWqcWAB4AHGrGih4dcbEsyRCxQABUATzcQgG8AXxwLa1lbezQTJ3geDy9QaPRIkIio0FjQS1gaHlAAIgVgMmqAbgTXbO9EehgymhpQAF5QAAoAfTQirABKNAA3GngCfoA+XNjm1s92zu8jCn6h0Z8sjcHa+uqJhXGp0Fn5pZXmoA)

### 🙁 Actual behavior

Refer to this program which invokes the `ts.transpileDeclaration` API:
https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro/blob/bug2/transpile.mjs

Basic instructions to invoke it can be found in
https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro/blob/bug2/README.md

When using the API, `b.d.ts` is emitted as
```ts
export declare const foo: (_: Type) => void;
export declare const bar: (_: any) => void;
```
while when using `tsc` it gets emitted as
```ts
import { type Type } from "./a";
export declare const foo: (_: Type) => void;
export declare const bar: (_: import("./a").Type) => void;
```

### 🙂 Expected behavior

Using the API should emit
```ts
import { type Type } from "./a";
export declare const foo: (_: Type) => void;
export declare const bar: (_: import("./a").Type) => void;
```

**Comment by robpalme** [comment]
The bug description seems to have a typo because the Actual vs Expected code snippets are identical.

**Comment by fatcerberus** [comment]
I'm guessing the `tsc` and API output are mistakenly swapped under Actual Behavior.

**Comment by MichaelMitchell-at** [comment]
> ### 🔎 Search Terms
> 
> 
> 
> transpile declaration api emit missing import
> 
> 
> 
> 
> 
> ### 🕗 Version & Regression Information
> 
> 
> 
> - This changed in commit or PR https://github.com/microsoft/TypeScript/pull/58261 @weswigham 
> 
> 
> 
> ### ⏯ Playground Link
> 
> 
> 
> https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro/tree/bug2
> 
> 
> 
> ### 💻 Code
> 
> 
> 
> ```ts repro
> 
> // @strict: true
> 
> // @declaration: true
> 
> // @showEmit
> 
> // @showEmittedFile: a.d.ts
> 
> // @showEmittedFile: b.d.ts
> 
> 
> 
> // @filename: a.ts
> 
> export interface Type {}
> 
> 
> 
> // @filename: b.ts
> 
> import { type Type } from "./a";
> 
> 
> 
> export const foo = (_: Type): void => {};
> 
> export const bar = (_: import("./a").Type): void => {};
> 
> 
> 
> ```
> 
> 
> 
> [Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=7&ts=5.5.0-dev.20240502#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoEEATLRAGwENYzp4B7AOzU13ygAsaB3AUQFt5o8YNp179oWAgDF4JLGjIA6AguiRBESO259o4qTLmgARkpVr14AGYG6ZHocWqcWAB4AHGrGih4dcbEsyRCxQABUATzcQgG8AXxwLa1lbezQTJ3geDy9QaPRIkIio0FjQS1gaHlAAIgVgMmqAbgTXbO9EehgymhpQAF5QAAoAfTQirABKNAA3GngCfoA+XNjm1s92zu8jCn6h0Z8sjcHa+uqJhXGp0Fn5pZXmoA)
> 
> 
> 
> ### 🙁 Actual behavior
> 
> 
> 
> Refer to this program which invokes the `ts.transpileDeclaration` API:
> 
> https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro/blob/bug2/transpile.mjs
> 
> 
> 
> Basic instructions to invoke it can be found in
> 
> https://github.com/MichaelMitchell-at/transpile_declaration_bug_repro/blob/bug2/README.md
> 
> 
> 
> When using the API, `b.d.ts` is emitted as
> 
> ```ts
> export declare const foo: (_: Type) => void;
> 
> export declare const bar: (_: any) => void;
> 
> ```
> 
> while when using `tsc` it gets emitted as
> 
> ```ts
> 
> import { type Type } from "./a";
> 
> export declare const foo: (_: Type) => void;
> 
> export declare const bar: (_: import("./a").Type) => void;
> 
> ```
> 
> 
> 
> 
> 
> ### 🙂 Expected behavior
> 
> 
> 
> Using the API should emit
> 
> ```ts
> 
> import { type Type } from "./a";
> 
> export declare const foo: (_: Type) => void;
> 
> export declare const bar: (_: import("./a").Type) => void;
> 
> ```
> 
> 
> 
> ### Additional information about the issue
> 
> 
> 
> 

Corrected, thanks

**Comment by MichaelMitchell-at** [comment]
> The bug description seems to have a typo because the Actual vs Expected code snippets are identical.

Corrected, thanks
