### ISSUE TITLE
A function with a return type of void can't be awaited without a warning

### ISSUE THREAD

**Issue by mybearworld** [microsoft/TypeScript#58459]
### 🔎 Search Terms

await promise void "'await' has no effect on the type of this expression" function return type parameter

### 🕗 Version & Regression Information

- This changed between versions 3.6.3 and 3.7.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.0-dev.20240507#code/MYewdgzgLgBAJiAyiAtgUygCwJZgOYwC8MAhhAJ5jAwAUwJANgwEYnADWAXLQJREB8MAG4hscPoUEBvAFAxSAdxLZY9Jqw40eMgL4yZCZOiy48NMpWpaBMWfID09mADpXunkA

### 💻 Code

```ts
const doSomething = async (callback: () => void) => {
  await callback()
}

doSomething(async () => {
  // ...
})
```

### 🙁 Actual behavior

There is an error at the "await" saying
```
'await' has no effect on the type of this expression.(80007)
```
But the return type might be a promise.

### 🙂 Expected behavior

No warning

**Comment by MartinJohns** [comment]
> There is an error at the "await" saying

There is no error. It's a hint, and that's working as intended, see #34508.

**Comment by fatcerberus** [comment]
Looking through the comments in #34508 and remembering that I've seen several duplicates recently, I'm baffled why so many people seem to think this is an *error*.  It's not.  It's just the language service trying to be helpful by offering you a refactor; you're free to ignore it.

**Comment by mybearworld** [comment]
> Yeah, `void` return type is basically saying "I'm not going to do anything with the return value of this function". If it happens to return a promise and you await it, that's observable.

Ah, that makes sense. I was thinking in terms of "`void | Promise<void>` is redundant, because anything `Promise<void>` accepts is also accepted by `void`".

(And "error" was a typo, I meant "warning", I'll correct it)

**Comment by fatcerberus** [comment]
It’s not even a warning really - it’s more of a suggestion “here’s a thing that might or might not be wrong that you could think about changing”

**Comment by mybearworld** [comment]
> It’s not even a warning really - it’s more of a suggestion “here’s a thing that might or might not be wrong that you could think about changing”

That same "suggestion" style is also used when you use parameters without types if TypeScript isn't set up strict enough, for example. Most of the time, following the suggestion would be good - I'd see them as warnings.

**Comment by MartinJohns** [comment]
> Most of the time, following the suggestion would be good

That's actually the case here too. If you want to `await` your value, then you should represent this intention in your types as well.
