### ISSUE TITLE
Does the TypeScript implementation of `for...of` call the `return` function of `IterableIterator`?

### ISSUE THREAD

**Issue by eggers** [Microsoft/TypeScript#5846]
for example:

```TypeScript
let iterator: IterableIterator<any> = {
  next(value?: any) { return { value: true, done: false}; },
  return() { console.log('for..of break'); return null; },
  [Symbol.iterator]() { return this; }
}

for (const value of iterator) {
  break;
}

// should log 'for..of break' ??
```

**Comment by eggers** [comment]
Similarly, this: 

```TypeScript
function* foo() {
  try {
    while (true) {
      yield true;
    }
  } finally {
    console.log('finally');
  }
}

for (let x of foo()) {
  break;
}
// Should log 'finally' ?
```

**Comment by mhegazy** [comment]
if you are compiling with `--target es3` or `--target es5`, the only supported target for a `for..of` loop is an array. the emitted code always assume it is an array and does a simple indexed loop over it. the iterator protocol is only supported if you target ES6.

you can find more information about this in https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Iterators%20and%20Generators.md#targeting-es5-and-es3

As for generators, generators are not supported for ES3/ES5 emit at the time being. it is on the road map for the next release though. so stay tuned.

**Comment by eggers** [comment]
@mhegazy Yeah, it must be an issue with node 4.2.1 not calling `return()` on breaking from the `for...of` loop since I found the same issues running plain es6 code with node. And, running the code through `babel-node` worked fine.

Thanks.
