### ISSUE TITLE
Incorrect type inference in class implementation of interface with method Accepting partial type

### ISSUE THREAD

**Issue by klarnakasamac** [microsoft/TypeScript#58467]
### 🔎 Search Terms

typescript class implementation interface method partial type

### 🕗 Version & Regression Information

This behavior has been observed in the latest version of TypeScript (5.4.5) 

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.4.5#code/JYOwLgpgTgZghgYwgAgJIFk4AcA86B8yA3gFDLnIC22AKgPYBqdwAJgBSUBcyACnFGGBwANnnwBKbgDdmLEgF8SJMAE8sKAIJbkAXmJkKcI91IUzyAEZXuAZzBRQAcwPlFikgmFwbN5JiwayMCUWMIQlBDgvhjYOFoahKYU1Fj0TKwc3PGSyDKs+uYUCHQgdsgAHrpUAHRGcNVWFi7mxaV0YdXCdI5s5eLNbkqtZQgiwlV4ADT4HNjcMbgE4rqJBinVKWmybETy-e6jwsJsIBAA7n7YGmzi4kA

### 💻 Code

```ts
interface IMap<M> {
    mapToVoid(m: Partial<M>): void
}

type AAA = {
    aaa: {
        bbb: string
    }
}

class MapA implements IMap<AAA> {
    mapToVoid(m: AAA): void {
        const x = m.aaa.bbb
        console.log(x)
    }
}

const call = <M,>(map: IMap<M>) => {
  map.mapToVoid({})
}

call(new MapA())
```

### 🙁 Actual behavior

No typecheck errors but during the runtime the `MapA.mapToVoid()` raises an error `Cannot read properties of undefined (reading 'bbb') `

### 🙂 Expected behavior

Typechecking should have an error saying something like `Property 'mapToVoid' is missing in type 'MapA' but required in type 'IMap<AAA>'.` since the `MapA.mapToVoid` method signature accept a narrower parameter than what the interface expects

**Comment by MartinJohns** [comment]
This is working as intended, methods are bivariant. See this FAQ entry: [Why Method Bivariance?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-method-bivariance)

You can use the property syntax to get covariant behavior: `mapToVoid: (m: Partial<M>) => void`

**Comment by klarnakasamac** [comment]
@MartinJohns Thank you, I read the article even though I don't 100% understand but I get that it's kind of a limitation, not sure I'll classify it as `working as intended` since it is clearly not working in the runtime and caused a bug in my project

but since we have a way forward I think I'll close the ticket

**Comment by fatcerberus** [comment]
> not sure I'll classify it as `working as intended` since it is clearly not working in the runtime and caused a bug in my project

"Working as intended" = working as the TypeScript compiler devs intend.  The behavior of TypeScript here is intentional, even if it leads to runtime errors.  The type system is intentionally not fully sound: to quote the design goals, TS is designed to "strike a balance between correctness and productivity"; in this case, enforcing `strictMethodTypes` would be a major roadblock in practice for almost any code people would want to write so it isn't done.

**Comment by klarnakasamac** [comment]
@fatcerberus I understand exactly why isn't it done, I'm happy too that there's way to solve my problem and move forward so I closed the issue, I know it's what the ts devs are aware of but to me it sounds more like a limitation or known issue where they just accepted that it's not worth fixing (if there was a magic way to fix it without any negative impact I think they would do it), `working as intended` for me is something is working based on your design
