### ISSUE TITLE
Different behavior between const and readonly for multidimensional array access/strict null checking

### ISSUE THREAD

**Issue by delosford** [microsoft/TypeScript#58476]
### 🔎 Search Terms

different behavior between readonly and const 

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I'm using TS Playground
- update: I tested it back a few versions after I was told how to on TS Playground and it produces the same errors.

### 💻 Code

```ts
//this gives an error about possible null values
let someArray: Array<Array<Array<number | null> | null> | null> = new Array<Array<Array<number | null> | null> | null>();
let someInt = 0;

if (someArray[someInt] !== null && someArray[someInt][someInt] != null)
 console.log(someInt);

//this gives no error about possible null values, meaning the problem seems to be that someInt could theoretically be modified
let someArray: Array<Array<Array<number | null> | null> | null> = new Array<Array<Array<number | null> | null> | null>();
const someInt = 0;

if (someArray[someInt] !== null && someArray[someInt][someInt] != null)
 console.log(someInt);

//this however gives an error, with or without readonly

function itsaFunction(arrayAccessors: readonly number[])
{
	let someArray: Array<Array<Array<number | null> | null> | null> = new Array<Array<Array<number | null> | null> | null>();

	if (someArray[arrayAccessors[0]] !== null && someArray[arrayAccessors[0]][arrayAccessors[1]] != null)
 		console.log(arrayAccessors);
}

```

### 🙁 Actual behavior

Errors about possible null values do not treat const and readonly the same

### 🙂 Expected behavior

const and readonly should produce/fix the same errors in the same way

**Comment by delosford** [comment]
> > * I was unable to test this on prior versions because I'm using TS Playground
> 
> Especially on the playground it's easy to test this on prior versions because the playground has a version selector on the top left.

I was unaware of that.  Thanks for letting me know.  I tested it back a few versions and they all produce the same errors.

**Comment by ahejlsberg** [comment]
This is working as intended. A `readonly` reference doesn't guarantee that the underlying object isn't mutated. I just guarantees that it isn't mutated through _that_ reference. You need to store the value in a `const` local to get the desired behavior.

**Comment by delosford** [comment]
```ts
function itsaFunction(arrayAccessors: readonly number[])
{
	let someArray: Array<Array<Array<number | null> | null> | null> = new Array<Array<Array<number | null> | null> | null>();

	const arrAcc1 = arrayAccessors[0];
	const arrAcc2 = arrayAccessors[1];

	if (someArray[arrAcc1] !== null && someArray[arrAcc1][arrAcc2] != null)
 		console.log(arrayAccessors);
}
```

Strangely, this doesn't work, either.  Gives the same error.

**Comment by whzx5byb** [comment]
> Strangely, this doesn't work, either.

This works in 5.5 beta. For more information, see https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#control-flow-narrowing-for-constant-indexed-accesses

**Comment by delosford** [comment]
> > Strangely, this doesn't work, either.
> 
> This works in 5.5 beta. For more information, see https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#control-flow-narrowing-for-constant-indexed-accesses

Thanks for the info.  Good to know this is at least being addressed.
