### ISSUE TITLE
5.5.0 regression - Named exports of functions are not emitted for CommonJS

### ISSUE THREAD

**Issue by Knagis** [microsoft/TypeScript#58473]
### 🔎 Search Terms

commonjs export

### 🕗 Version & Regression Information

- This changed between versions 5.4.5 and 5.5.0

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=7&module=1&isolatedModules=true&verbatimModuleSyntax=false&ts=5.5.0-beta#code/GYVwdgxgLglg9mABMOcAUBKAXIgbnGAE0QG8AoAXzLIFMAPABzgCcpSzFPlUAaSgbjJA

### 💻 Code

```ts
function foo(): void {
}

export {
    foo,
};
```

### 🙁 Actual behavior

ts 5.5.0-beta and 5.5.0-dev-20240508 both emit:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
function foo() {
}
```

note missing last line

### 🙂 Expected behavior

ts 5.4.5 emit

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
function foo() {
}
exports.foo = foo;

```

**Comment by Knagis** [comment]
the problem shows up only with functions. exporting classes or variables via `export { foo }` work fine. also `export function foo() {}` works fine.

**Comment by jakebailey** [comment]
Most likely this was https://github.com/microsoft/TypeScript/pull/57669 (you could try using https://www.npmjs.com/package/every-ts to bisect and verify).

**Comment by Knagis** [comment]
Bisect confirms that it is the cause

```
881f449a8a10839db5d535c3a407621d53c78666 is the first bad commit
commit 881f449a8a10839db5d535c3a407621d53c78666
Author: Ron Buckton
Date:   Wed Mar 6 18:43:59 2024 -0500

    Hoist function exports to top of module body in CJS/AMD/UMD (#57669)
```

**Comment by jakebailey** [comment]
Yeah, the issue appears to be that `collectExternalModuleInfo` doesn't do the same thing it does for function declarations when processing export declarations.

**Comment by Knagis** [comment]
@jakebailey is there a chance the fix for this could be merged before 5.5.1?

**Comment by meriouma** [comment]
I'm facing the same or similar issue with 5.5.4 and 5.6.0-beta. I'm not sure if it's a different issue.

**input**
```typescript
import { Mocked, mocked } from 'jest-mock';
import { ComponentProps, FunctionComponent, JSXElementConstructor } from 'react';

type MockedComponent<T> = keyof JSX.IntrinsicElements | JSXElementConstructor<T>;

export function mockedClassComponent<T extends MockedComponent<ComponentProps<T>>>(
    component: T,
): Mocked<FunctionComponent<ComponentProps<T>>> {
    return mocked(component as FunctionComponent<ComponentProps<T>>);
}
```


**output**
```typescript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mockedClassComponent = mockedClassComponent;
const jest_mock_1 = require("jest-mock");
function mockedClassComponent(component) {
    return (0, jest_mock_1.mocked)(component);
}
```

**Comment by jakebailey** [comment]
What version of TS is the above output from? Is that expected output? Unexpected output?


That output is assigning `mockedClassComponent` to the exports, not omitting it entirely, so I don't think what you've described is the same thing (and shows that the current state is working).

**Comment by meriouma** [comment]
Sorry, I think I was tracking the wrong issue.
