### ISSUE TITLE
possibly 'undefined'. emitted after Boolean constructor check in Visual Studio

### ISSUE THREAD

**Issue by kdevay** [microsoft/TypeScript#58485]
### 🔎 Search Terms

- possibly 'undefined'
- visual studio code
- VS code
- Boolean wrapper not supported
- Boolean constructor not supported

### 🕗 Version & Regression Information

- This is the behavior in TS Version 5.4.3, and I reviewed the FAQ for entries about _undefined values after a boolean check_

### ⏯ Playground Link

https://replit.com/join/cwiubczice-kdevay

### 💻 Code

```ts
interface Message {
  text: string;
  isBot: boolean;
}

interface ConversationProps {
  messages?: Message[];
}

const Conversation: React.FC<ConversationProps> = ({ messages }) => {
  return (
    <div
      id="conversation"
      className="flex flex-col gap-2 h-conversation overflow-y-scroll text-white"
    >
      {Boolean(messages && messages.length) &&
        messages.map((message, index) => (
          <div
            key={index}
            className="flex flex-row w-full"
          >
            <div>
              `${message.isBot ? '🤖' : 'you'}: ${message.text}`
            </div>
          </div>
        ))}
    </div>
  );
};

export default Conversation;

```

### 🙁 Actual behavior

I am seeing a red squiggle on `messages.map` stating that it is possibly undefined
<img width="559" alt="Screenshot 2024-05-09 at 9 33 01 AM" src="https://github.com/microsoft/TypeScript/assets/93360928/176fa58f-ee93-4fca-ae5d-8d4334917da4">

### 🙂 Expected behavior

I should not see any error, because I performed this check: `Boolean(messages && messages.length) `.   

I do not see an error message when I add the check without the Boolean constructor, like
```ts
      {(messages && messages.length) &&
        messages.map((message, index) => (
```

### Additional information about the issue

TypeScript
Version 5.4.3  

Visual Studio Code
Version: 1.89.0 (Universal)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:10:10.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0  

My Machine
Model: Macbook pro
Chip: Apple M2 
OS: Sonoma 14.4

**Comment by fatcerberus** [comment]
More or less the same as https://github.com/microsoft/TypeScript/issues/16655
