### ISSUE TITLE
Event `type` (name string) doesn't get properly checked or suggestions when using addEventListener() on an Union of multiple HTMLElement types

### ISSUE THREAD

**Issue by LifeJustDLC** [microsoft/TypeScript#58497]
### 🔎 Search Terms

"event type", "addEventListener", "suggestion"

### 🕗 Version & Regression Information

- This is a crash

### 💻 Code

```typescript
type DivOrSpan = HTMLDivElement | HTMLSpanElement
const divOrSpan = document.querySelector<DivOrSpan>(".could-be-div-or-span")!
divOrSpan.addEventListener("typo", () => {}) // neither complain or suggest when first typing

const div = document.querySelector<HTMLDivElement>(".div")!
div.addEventListener("click", () => {}) // doesn't complain either but get suggestions automatically as well as pressing ctrl+i
```

### 🙁 Actual behavior

first one neither complain or suggest when first typing.

### 🙂 Expected behavior

get suggestions automatically as well as pressing `ctrl+i` like the second one.

**Comment by fatcerberus** [comment]
for the record: this is not a crash

**Comment by LifeJustDLC** [comment]
@fatcerberus sorry, I didn't have the time to bisect the versions.

**Comment by fatcerberus** [comment]
No, I just meant that you put

> This is a crash

but it’s not - the compiler didn’t crash.  It’s just not doing what you expect

**Comment by jcalz** [comment]
I suspect this is just a caveat of #29011, you're calling a union of overloaded and generic methods.  Feels like a design limitation to me (who is just a nosy bystander and not a TS team member)

**Comment by LifeJustDLC** [comment]
@jcalz Thanks for your insights.

> The caveats are that only one type in the list of union members is allowed to have overloads, and only one type within the list of union members is allowed to have type parameters.

I didn't fully understand that post, but I think it's a little different:

![图片](https://github.com/microsoft/TypeScript/assets/112793544/95fc4a45-368e-4dfe-9b10-b68e1ad9031d)

![图片](https://github.com/microsoft/TypeScript/assets/112793544/3f8822b5-13e9-413b-b957-99624a3ae88b)

As @weswigham described, and as I understand, it will at least get an intersected signature (suggestion)? which is `"2"` in the above case. but in the similar case of `HTMLDivElement` and `HTMLSpanElement`, this seems doesn't work.

**Comment by RyanCavanaugh** [comment]
These signatures don't merge because the `this` value is different in the callbacks
