### ISSUE TITLE
Marking a constructor as `@internal` emits no constructor declaration at all instead of a private constructor

### ISSUE THREAD

**Issue by lazarljubenovic** [microsoft/TypeScript#58503]
### 🔎 Search Terms

internal, constructor

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "internal" and "private"

### ⏯ Playground Link

https://www.typescriptlang.org/play/?stripInternal=true#code/MYGwhgzhAEBiD29oG8BQ0PQPQCofQAEBLAOwBcBTAJxLBGhy3U2HhIjKoFdgz4roACjAAuaCS4BbAEbUAlCmgBfVCtShIMAEJgBaTNAAOVIgDcwlaK3acefAcLESZ8xSpVA

### 💻 Code

```ts
// source
class Foo {
  /** @internal */
  constructor (a: number) {
    console.log(a.toString())
  }
}
```

```ts
// emitted declaration
declare class Foo { }
```

```ts
// usage from another lib
const foo = new Foo()  // TS fine,   JS errors
const foo = new Foo(1) // TS errors, JS fine
```

### 🙁 Actual behavior

- I'm able to call the constructor as a library consumer
- I'm forced to call it with wrong arguments

### 🙂 Expected behavior

- I'm not able to call the constructor at all as a library consumer

### Additional information about the issue

When you use `@internal` on a method, it's fully removed on emission because the consumers of the library are not supposed to use it. To keep the same mental model, using `@internal` on a constructor should emit a `private constructor ();` in the declaration file.

**Comment by MartinJohns** [comment]
Duplicate of #51486.

**Comment by lazarljubenovic** [comment]
Bah, didn't think of `in:title`. Thanks.
