### ISSUE TITLE
value of type never can be created using document.all

### ISSUE THREAD

**Issue by tyilo** [microsoft/TypeScript#58502]
### 🔎 Search Terms

- document.all
- HTMLAllCollection

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Common "Bugs" That Aren't Bugs

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.4.5#code/GYVwdgxgLglg9mABMAFANwFyLAUzTgJwEos04YATRAbwChEHEIEBnOAGxwDp24BzFAAMAygAs4IdhTAByKIgBGORAAc4LFjAWcMggDSI0RANy0AvrVrMwLeQA9EAXkQU4EEAFscYKFwCG7OymMMCIKFAAnio4cKEOjgmIMuAUOMAwuBQyRDT0jKh2JuZAA

### 💻 Code

```ts
function f(v: never): void {
    console.log(`Shouldn't be possible:`, v);
}

const x = document.all;
if (typeof x === 'undefined') {
    f(x);
}
```

### 🙁 Actual behavior

The code type checks and `f` is called at runtime even though it has a parameter of type `never`.

### 🙂 Expected behavior

The type of `x` should not be narrowed have type `undefined` when `typeof x === 'undefined'` has been established.
Instead it's type should be narrowed to `undefined | HTMLAllCollection`.

**Comment by snarbies** [comment]
That's not how type narrowing works. If the declared type is `X` and CFA can determine that the type is also `Y`, then the proper inference is that the type is `X & Y`, not `X | Y`. It must be *both*, not either/or.

And since we know that it is both `HTMLAllCollection` and `undefined`, the correct inference is `never`.

Or are you suggesting that the typing of `Document.all` be changed to `undefined | HTMLAllCollection`?

**Comment by fatcerberus** [comment]
@snarbies `document.all` is a weird animal: because of spec weirdness for the purpose of not breaking the web, `typeof document.all === 'undefined'` is true (as well as it being falsy and loosely equal to both `null` and `undefined`) despite it *really* being an `HTMLAllCollection`.

**Comment by tyilo** [comment]
@snarbies No, I'm saying that the given the information that `typeof x === "undefined"`, the conclusion is only that `x` has type `undefined | HTMLAllCollection` and not that `x` has type `undefined`. This is because `typeof document.all` is `"undefined"` even though it has type `HTMLAllCollection`.

**Comment by fatcerberus** [comment]
fwiw I doubt TS is going to make a special case in the type checker specifically to account the weirdness of `document.all`.  This situation can't happen with any other value in JS and `document.all` is deprecated anyway; MDN recommends against using it at all.

**Comment by snarbies** [comment]
I'm not sure I would even characterize this as a soundness issue. It's closer to magic.

There are scenarios that the type system simply can not convey, and this is true of most any type system. Magic, including exotics, by its very nature can and will defy the type system.

The only fix here would be to introduce type magic around the `HTMLAllCollection`, which we can pretty safely assume wouldn't be happening.

**Comment by guillaumebrunerie** [comment]
A better fix would be to remove the type definition for `document.all` entirely. Why would anyone use it in a Typescript project?
The only reason it still exists is to avoid breaking antiquated websites, but they most likely don't use Typescript anyway (or are not being maintained anymore).

**Comment by RyanCavanaugh** [comment]
`document.all` is already marked deprecated.
