### ISSUE TITLE
ts.createSourceFile trims leading newlines, causing stored line numbers to mismatch

### ISSUE THREAD

**Issue by Artur-** [microsoft/TypeScript#58517]
### 🔎 Search Terms

createSourceFile newlines trim

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about createSourceFile

### 💻 Code

```ts



import React from 'react';

export default function HelloWorldView() {
  return <span>Hello</span>;
}
```

### 🙁 Actual behavior

Given this TSX file, React tooling will store a source reference on the `<span>` element as e.g. 
```
$0.__reactFiber$wzqrbgzp6o._debugSource
```

and it will contain

```
{
columnNumber: 10,
fileName: ".../something.tsx",
lineNumber: 7
}
```

However, if you feed the TSX file into `ts.createSourceFile` and look for an element on line 7, you will not find anything because the file has been changed to
```
import React from 'react';

export default function HelloWorldView() {
  return <span>Hello</span>;
}
```
and it only has 5 lines

### 🙂 Expected behavior

ts.createSourceFile does no transformations whatsoever on the given input

**Comment by Artur-** [comment]
Not sure this is a meaningful test, reproducing what is shown in a larger case is always difficult. I will dig more into this tomorrow and ensure the problem is not elsewhere. Anyway, given `a.ts`
```




const ts = require("typescript");
const { readFileSync } = require("fs");

const sourceText = readFileSync("a.ts", {encoding: 'utf-8'});
const sourceFile = ts.createSourceFile('test.tsx', sourceText, ts.ScriptTarget.Latest, true);
console.log(sourceFile.getText());





```

and `package.json` 

```
{
  "name": "tstest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "typescript": "^5.4.5"
  }
}
```

then running

```
node_modules/.bin/tsc a.ts && node a
```

outputs
```
const ts = require("typescript");
const { readFileSync } = require("fs");

const sourceText = readFileSync("a.ts", {encoding: 'utf-8'});
const sourceFile = ts.createSourceFile('test.tsx', sourceText, ts.ScriptTarget.Latest, true);
console.log(sourceFile.getText());




```

which includes trailing newlines but not leading ones.

**Comment by RyanCavanaugh** [comment]
Use `getFullText()` for that operation

**Comment by Artur-** [comment]
Ok, so now that I am aware of `getFullText()` I am guessing that the main problem is the use of `getStart()` and `getEnd()` instead of `getFullStart()` and `getFullWidth()` in our code. Where should I have been able to find out about full vs non-full versions of the methods?
