### ISSUE TITLE
Union argument type with and spread operator

### ISSUE THREAD

**Issue by mageekguy** [microsoft/TypeScript#58513]
### 🔎 Search Terms

spread, argument, union, type.

### 🕗 Version & Regression Information

It is a "strange" and maybe abnormal behavior of type checking algorithm when union is used on function/method argument with spread operator.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDjAVzABtgAeAZwQC9gA+OAbwCg425tiFgUAxaAHIEAtgCM0FAJIUAFADoFcJCPFQKALiUq0AbQC6cAGRM4pJAHMYAC01VacAL4BKTQDcICACYBuZg+bMnJgUFHCYSACeACpEpJQ09IjCJMDCPDChhCnxtAws7HBgUAiumKhaYhKaypVQ+kYmZpY2cHZ4Dr6s7NgQSBQwUATYMNDyijWqGhWq9caMpjzNtglwTkxdBWzWCBRyExJwALzTEr4F-hscXOn8UEK1UrKc3CiaY3InatXadQZzCxZrMt7M4jgx3F4XHAIZ51ptutcUO98FYdnsfhQnGd2P4LkEQvhiil4KBUEhPKFwtFYuQAMx5S49PoDIYjKAyJAARm+tSOcAADAAaJQAJh5qj5QqUtPFaEla3y8NaRDQHM5wqQIo1tKxl1xASZ-TgnmAWAIxBgUSJpHgxyQwAA7oSEMSZLrmCazRarS6bZc5M8boIMdIZJcCmqNVrpWtDnkOL0KBBSHJiBBzJHRdqsY5Lk5mN4gA

### 💻 Code

```ts
interface tuple<size> {
    clientForNumbersIs(... numbers: number[] & { length: size }): void;
}

class anyTuple<size> implements tuple<size> {
    private numbers: number[] & { length: size };

    constructor(... numbers: number[] & { length: size ) {
        this.numbers = numbers;
    }

    clientForNumbersIs(client: (... numbers: number[] & { length: size }) => void): void {
        client(... this.numbers);
    }
}

class triplet extends anyTuple<3> {
    constructor(n1: number = 0, n2: number = 0, n3: number = 0) {
        super(n1, n2, n3);
    }
}

const defaultTriplet = new triplet();

defaultTriplet
    .clientForNumbersIs(
        (n1, n2, n3) => { console.log(n1, n2, n3); }
    )
;
```

### 🙁 Actual behavior

The code generate these following errors:

```
Property 'clientForNumbersIs' in type 'anyTuple<size>' is not assignable to the same property in base type 'tuple<size>'.
  Type '(client: (...numbers: number[] & { length: size; }) => void) => void' is not assignable to type '(...numbers: number[] & { length: size; }) => void'.
    Types of parameters 'client' and 'numbers' are incompatible.
      Property '0' is missing in type 'number[] & { length: size; }' but required in type '[client: (...numbers: number[] & { length: size; }) => void]'.
Argument of type 'number[]' is not assignable to parameter of type 'number[] & { length: size; }'.
  Type 'number[]' is not assignable to type '{ length: size; }'.
    Types of property 'length' are incompatible.
      Type 'number' is not assignable to type 'size'.
        'size' could be instantiated with an arbitrary type which could be unrelated to 'number'.
Argument of type '(n1: number, n2: number, n3: number) => void' is not assignable to parameter of type '(...numbers: number[] & { length: 3; }) => void'.
  Types of parameters 'n1' and 'numbers' are incompatible.
    Type 'number[] & { length: 3; }' is not assignable to type '[n1: number, n2: number, n3: number]'.
```

However, from my point of view, there is no problem with type because `this.numbers` in `anyTuple` match requirement of interface `tuple`, and it is the same for `this.numbers` from `triplet` instance.
So, i see two options:

- I haven't understood in the right way the type checking algorithm or its philosophy;
- There is a problem in the type checking algorithm in this context.

So, is there someone here to show me the light ;), or confirm the bogus behavior?

### 🙂 Expected behavior

No error.

**Comment by RyanCavanaugh** [comment]
TS doesn't realize that `...` will preserve `.length`; WLOG you could write `client.apply(null, this.numbers);` instead

The second error is because function expressions don't get a literal `length` property; it's not really clear what the upside of that would be except for this exact situation
