### ISSUE TITLE
Mix indexed and non-indexed properties

### ISSUE THREAD

**Issue by denis-sokolov** [Microsoft/TypeScript#5851]
How can I specify that I accept any object, whose property values are `T`?
Here is my experience so far ([Playground](http://www.typescriptlang.org/Playground#src=%0Afunction%20foo(param%3A%20%7B%5Bk%3A%20string%5D%3A%20number%7D)%20%7B%0A%7D%0A%0A%2F%2F%20This%20is%20not%20an%20error%2C%20correct%3A%0Afoo(%7B%20a%3A%202%20%7D)%0A%0A%2F%2F%20This%20should%20not%20be%20an%20error%20either%3A%0Afoo(%7B%20a%3A%202%20%7D%20as%20%7B%20a%3A%20number%20%7D)%0A)):

```typescript
function foo(param: {[k: string]: number}) {
}

// This is not an error, correct:
foo({ a: 2 })

// This should not be an error either, but it is:
foo({ a: 2 } as { a: number })

// In real life code there is no explicit cast, but an interface:
interface MyFoo {
  a: number
}
foo(getMyFoo())
```

**Comment by mhegazy** [comment]
if you are casting, you are not using the contextual type from the function declaration, and thus did not inherit the index signature so you will need to explicitly add it:

```ts
foo({ a: 2 } as { a: number; [k:string]:number })
```

in the case of your interface, add the constraint on it to ensure the two are compatible:
```ts
interface MyFoo {
  a: number;
  [k:string]: number;
}
```
