### ISSUE TITLE
transpileDeclaration - Errors on unresolvable globals

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#58535]
### 🔎 Search Terms

transpileDeclaration globals

### 🕗 Version & Regression Information

- This changed between versions 5.4 and 5.5 beta

### ⏯ Playground Link

[Playground](https://www.typescriptlang.org/dev/bug-workbench/?emitDeclarationOnly=true#code/PTAEAEBMFMGMBsCGAnRAXAlgewHYC41kBXaAWACgQJoBbDNAETiVU1wHkd4BPPUQkhQpVwAMwzxoAOUQ1ofAObwsAI0TwAzgDo0Gimm4AHaKACyGDRow4FAcWVr4AFSMmAvKABES1es8BuChgEFBNYXA00UDpLazsHdQA1dRI+TwBBAOEwMQlpWXlQaxgADx09SjA0AAsLfmhI0ERLIjkNfmroZBM6jSw5UB9HUBhxHHpsHHbRLGQzCysbe19nVyacSGiFuOXHZPgSDvQm7tAcLCjEADdECUQVSX4sflQpwzymENZJimgSw1mUXCUyiJT45liSwSq2MoA8OCI8HgAEJAuQ-gDkECIlFRDg4aAABSIcHbKErFzGACUpMh8QpazcAD4zoiUWiMYDQMDGniAEwE4m0xb0xyU6BUuEshFI5FNdoQkW7dTitG-f5cnmgvl8AzGLCiLZ05XwfaHeFs1HqzHYkGgPEAZkFJP4rgNRqV0LNEt1bsNMU9K29UtZso5Gqx3Jx9pwABZnb79f6yaKkikJSGZSj5a6kx6dl702ryNbNdHnnwAN4UUC10AAbQDBaD6YAunxIsg4hQAL4ErOooA)

### 💻 Code

```ts
// @declaration:true
// @emitDeclarationOnly: true

// @fileName: globals.ts
type MissingGlobalType = "global";
declare const missingGlobalValue: "A";
// @fileName: index.ts
// this test assumes there is some global definitions for MissingGlobalType and missingGlobalValue that are not available to transpileDeclaration
export const x: MissingGlobalType = null!;
export const fn = (a: MissingGlobalType): MissingGlobalType => null!;
export const fn2 = (a: MissingGlobalType) => null! as MissingGlobalType;

export const x2: typeof missingGlobalValue = null!;
export const fn3 = (a: typeof missingGlobalValue): typeof missingGlobalValue => null!;
export const fn4 = (a: typeof missingGlobalValue) => null! as typeof missingGlobalValue;


export const o : {
    [missingGlobalValue]: string
} = null!;
```

### 🙁 Actual behavior

`trasnpileDeclaration` will return errors since it can't find `MissingGlobalType` and `missingGlobalValue`

### 🙂 Expected behavior

`trasnpileDeclaration` should not error or missing symbols. It does not have enough information to know if that symbol is resolvable.

**Comment by dragomirtitian** [comment]
cc: @weswigham

**Comment by weswigham** [comment]
Yeah, see my comment on #58496 - the issue is that `isEntityNameVisible` conflates does-not-exist with not-reachable. We should extend its' return type to represent both states separately, and only issue the "X does not have access to private Y" type errors when the entity name exists but isn't accessible, rather than doesn't exist at all (since when it doesn't exist at all, `resolveName` in the checker pass is already going to error and we're just duplicating it with a more confusing error).
