### ISSUE TITLE
Why is Promise<void> accepted as void

### ISSUE THREAD

**Issue by TarSzator** [microsoft/TypeScript#58556]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I am looking for an official explanation why TS accepts Promise<void> as void.
[Playground](https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&suppressImplicitAnyIndexErrors=true#code/GYVwdgxgLglg9mABACwIZgCYBsCmBhVLLAI1QgGsAKAZyhGGAC5FKBKRAXgD5EAFAJzgBbGNRwAeAG5wYGHgB9E02a2bKMiAN4BYAFCJEtesDYBuPQF89etJlwEipCpTZqZG7lr0GICanFwAOiw4AHNKAHJkEGiI1nNdC3jrXVtsfEISMipXPkERMSl3Hk8dfURfMH8gkPComJA4hIN+HDp+JAFhURxA1urJHDNLZN0UtPtMpypUagBPSBZVPO7C9RKeMp8-AN7ayOjY0aTTIA)

When I provide a higher-order function that accepts a callback `() => void` I do not want user's to inject a function `() => Promise<void>` because I do not handle the rejection case of the Promise inside my higher-order function which might lead to an unhandled promise rejection.

Same goes from the other direction if by accident I put a callback `() => Promise<void>` into an higher-order function that only accepts `() => void` I would like to be informed that the higher-order function will not handle the Promise rejection correctly because it does not expect a Promise to be returned by the callback but void.

But I assume there was a thought process behind the decision to accept Promise<void> as void but I could not find in the official reason.

**Comment by MartinJohns** [comment]
This is working as intended. A callback returning `void` means "can be whatever, I don't care". If the user wants to return a promise, so be it. When they want to return an object, so be it.

https://github.com/microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

See also: #42709

**Comment by Jamesernator** [comment]
> Same goes from the other direction if by accident I put a callback `() => Promise<void>` into an higher-order function that only accepts `() => void` I would like to be informed that the higher-order function will not handle the Promise rejection correctly because it does not expect a Promise to be returned by the callback but void.

Typescript-eslint has a [rule for this](https://typescript-eslint.io/rules/no-misused-promises#checksvoidreturn) if you really want to ensure you're not using this behaviour.

**Comment by TarSzator** [comment]
Thank you @MartinJohns that helped

Thanks also @Jamesernator I knew about that but good that it is written here as well for others 😄
