### ISSUE TITLE
parse identifiers automatically

### ISSUE THREAD

**Issue by ali-abdalla** [Microsoft/TypeScript#5856]
Here's a simple code from my project

```bash
class CommentId {
  constructor(public value: number) {}
}

let id = new CommentId("Text");
```

it compiles successfully. How is that ?!

**Comment by kitsonk** [comment]
TypeScript by default always emits on error, but there is [an error reported with your example](http://www.typescriptlang.org/Playground#src=class%20CommentId%20%7B%0A%20%20constructor(public%20value%3A%20number)%20%7B%7D%0A%7D%0A%0Alet%20id%20%3D%20new%20CommentId(%22Text%22)%3B%0A).

To have no emit on error, you need to enable the `noEmitOnError` [compiler option](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options).
