### ISSUE TITLE
Typescript Stickers

### ISSUE THREAD

**Issue by trevh3** [microsoft/TypeScript#58586]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Hey, where can I get a good typescript logo sticker for my laptop?

**Comment by xiBread** [comment]
Can you not use Google?

**Comment by trevh3** [comment]
Instead of using a pair of rhetorical questions meant to shame another person, perhaps you can seek to understand the intent behind the question?

I would like to avoid purchasing an unlicensed sticker, and I couldn’t find an officially sanctioned one. Also, I used the “new issue” flow and selected “other” for a question that didn’t fit into any other category. It ended up in this list. 

it would be greatly beneficial if you could link to an official sticker or provide a better venue to ask the question.

**Comment by MartinJohns** [comment]
There are no sanctioned or official stickers to purchase. And what purchase options you have also heavily depends on your country of residence, which you did not mention.

**Comment by trevh3** [comment]
Thank you.

**Comment by RyanCavanaugh** [comment]
https://www.typescriptlang.org/branding/, though this page might get deprecated

I did a die-cut sticker from an SVG a few years back; this needs a small bit of manual cleanup but looks nice IMO

![TypeScript with Die](https://github.com/microsoft/TypeScript/assets/6685088/35c73fd0-2373-4fdc-8424-86912bdc8343)

**Comment by trevh3** [comment]
Thank you @RyanCavanaugh!
