### ISSUE TITLE
`const wrong = () => (1 < 3) as true // type: () => true` this should be an error. 

### ISSUE THREAD

**Issue by jko206** [microsoft/TypeScript#58636]
### 🔎 Search Terms

- typescript bug return type true
- () => true bug

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "typescript bug return type true"

### ⏯ Playground Link

https://

### 💻 Code

```ts
const wrong = () => (2 < 3) as true
```

### 🙁 Actual behavior

This doesn't trigger a TS error.

### 🙂 Expected behavior

It should.

### Additional information about the issue

I know this would be a hard challenge to solve, but I thought you guys should at least know about it.

**Comment by dragomirtitian** [comment]
Maybe I'm just slow today, but why should this trigger an error?

**Comment by fatcerberus** [comment]
@dragomirtitian This is just a guess but maybe OP expects an error because `2 < 3` is always false?  But then `false as true` isn’t an error either so…

**Comment by jko206** [comment]
I should have been more clear. 

as @fatcerberus mentioned, I was expecting the above code to be an error, since the `1 < 3` is always false.

**Comment by whzx5byb** [comment]
Note that all of these are valid...
```ts
const a = false as true;
const b = 'x' as 'y';
const c = 1 as 2;
```

**Comment by KDwevedi** [comment]
> ...I was expecting the above code to be an error, since the 1 < 3 is always false.

Why is `1 < 3` false? `<` is just the *less than* comparison operator, correct?

**Comment by MartinJohns** [comment]
This is working as intended. Using a type assertion you tell the compiler "shh.. trust me, it's this type, I know what I'm doing..."

@KDwevedi They surely mean the `1 > 3` case.

**Comment by jcalz** [comment]
I'm amazed that people figured out what this issue meant. My brain was imploding trying to understand what could possibly have been the bug: "Why would the `() =>` part matter here? Why is the desired behavior just "an error" without mentioning, like, what *kind* of error? Wait, has 3 cut in front of 1 and 2 in the number line again? Why wouldn't you be allowed to narrow from `boolean` to `true` in a type assertion? Am I... am I dreaming? This is a dream, isn't it?"

**Comment by fatcerberus** [comment]
3 is always cutting in front of 1 and 2, he thinks he's so important having his visage plastered everywhere.  Still better than that jerk 7.  6 *still* needs therapy to this day after witnessing `t h e   i n c i d e n t`
