### ISSUE TITLE
[isolatedDeclarations][5.5] Optional parameter annotated with imported type has isolatedDeclarations error

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#58647]
### 🔎 Search Terms

isolated declarations optional import error explicit type annotation

### 🕗 Version & Regression Information

- This changed between versions 5.5.0-dev.20240517 and 5.5.0-dev.20240524

### ⏯ Playground Link

https://www.typescriptlang.org/dev/bug-workbench/?target=7&isolatedDeclarations=true&all=true&noCheck=true&emitDeclarationOnly=true&ts=5.5.0-dev.20240524#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoEEATLRAGwENYzp4B7AOzU133HkhvOiwIBFjzK1epEaxseMOCwBbeND6kKVWnQDydEgE9R4lmRIkaAdwBSI0ADN9kZpLo0AwgAtiAax22IkJ8YCis6AkvHyN-OS4CADF4Eiw0MgA6AgToSBwg8AsYrDoyaTjQRNT0+GkABxpYaFAAb3RNMqxQSJoaUABfS1gaaVAAcgIaLEgAWntoEawADzZoPoBudOmKqtBEYWqyUABeUAAKCgBzAH40FpoASjQANxp4Ah2APlr2nGXK6osMOmQVUAAjA6wE5nVpXUC3e4vIA

### 💻 Code

```ts repro
// @strict: true
// @declaration: true
// @isolatedDeclarations: true
// @emitDeclarationOnly: true
// @allowJs: false
// @noCheck: true
// @showEmit
// @showEmittedFile: a.d.ts

// @filename: a.ts

import { type Foo } from 'does-not-exist';

export const a = (arg?: Foo): void => {}
export function b(arg?: Foo): void {}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?target=7&isolatedDeclarations=true&all=true&noCheck=true&emitDeclarationOnly=true&ts=5.5.0-dev.20240524#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoEEATLRAGwENYzp4B7AOzU133HkhvOiwIBFjzK1epEaxseMOCwBbeND6kKVWnQDydEgE9R4lmRIkaAdwBSI0ADN9kZpLo0AwgAtiAax22IkJ8YCis6AkvHyN-OS4CADF4Eiw0MgA6AgToSBwg8AsYrDoyaTjQRNT0+GkABxpYaFAAb3RNMqxQSJoaUABfS1gaaVAAcgIaLEgAWntoEawADzZoPoBudOmKqtBEYWqyUABeUAAKCgBzAH40FpoASjQANxp4Ah2APlr2nGXK6osMOmQVUAAjA6wE5nVpXUC3e4vIA)

### 🙁 Actual behavior

`arg` has `Parameter must have an explicit type annotation with --isolatedDeclarations.(9011)`

### 🙂 Expected behavior

No errors

### Additional information about the issue

This only seems to happen if the import path doesn't exist. cc @weswigham @dragomirtitian

**Comment by dragomirtitian** [comment]
I think this is already fixed by https://github.com/microsoft/TypeScript/pull/58637. I will check.

**Comment by MichaelMitchell-at** [comment]
Looks like it's fixed
