### ISSUE TITLE
Lose generic when spreading `T | undefined` where T is a generic object type

### ISSUE THREAD

**Issue by yfzhe** [microsoft/TypeScript#58645]
### 🔎 Search Terms

spread, union

### 🕗 Version & Regression Information

There are 2 problems. The first was changed between versions 4.0.5 and 4.1.5, and the second exists in every version of TS I tried in the Playground.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdE4AjAK22gD4AKKALkSwB9FwjtgYxsRAJSIA3gChEiAE7YoIaUlGIAdGqgAaZKlYAWAEyIAvgG5xR8eNCRYCRBQCG0zDnyFS5arSiMWbRJzcvPyCIhJSsvKKYqrqxmZGQA

### 💻 Code

```ts
// spread and add a property
function foo<T extends object>(t: T | undefined) {
  return { ...t, foo: 42 };
}

// just spread
function bar<T extends object>(t: T | undefined) {
  return { ...t };
}
```

### 🙁 Actual behavior

1. The result type of `foo` is `{ foo: number }`.
2. The result type of `bar` is `{}`. 

### 🙂 Expected behavior

1. The result type of `foo` is`(T & { foo: number }) | { foo: number }`.
2. The result type of `bar` is `T`.

### Additional information about the issue

I'm not sure if this is same with #58617. But as there are some previous versions of TS work as I expected, I tend to treat it as a different issue and a bug.

**Comment by ahejlsberg** [comment]
I don't think there is a bug here. Spreading an `undefined` value creates no properties, so `{ ...t }` produces `{}` when `t` is `undefined`. Thus, the result is `T | {}`, which reduces to just `{}` by subtype reduction.

**Comment by yfzhe** [comment]
I'm confused a little on the situation of `foo`. I think it is also because of subtype reduction which the type of `{ ...t, foo: number }` is `{ foo: number }`. But as we see it was `(T & { foo: number }) | { foo: number }` in some old versions of TS, did there happen some "breaking changes" on subtype reduction?
