### ISSUE TITLE
React import is being omitted in --jsx preserve case

### ISSUE THREAD

**Issue by ngbrown** [Microsoft/TypeScript#5865]
When using `--jsx preserve`, the React declaration is removed if not directly used.  Issue #3764 fixed this for `--jsx react` but not for the preserve case.

```ts
import * as React from "react";
import * as ReactDOM from "react-dom";

var targetEl = document.getElementById("app");
ReactDOM.render(
  <div>{"Some Text"}</div>,
  targetEl)
```

This breaks the the app after ran through webpack -> babel

Currently, the workaround is to include a dummy reference to `React;`, but this shouldn't be necessary and the imports should pass through to babel.

**Comment by mhegazy** [comment]
the current behavior is the intended design, `React` is never used as we are not emitting it, so it is removed. having said that, we should make this scenario work. all workaround are ugly,

**Comment by ngbrown** [comment]
@RyanCavanaugh Thanks!
