### ISSUE TITLE
Generic type parameter not inferring properly

### ISSUE THREAD

**Issue by dpizzo-at-aops** [microsoft/TypeScript#58651]
### 🔎 Search Terms

"object key order matters"
"infer first occurrence"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about generics
- This changed (for the better) between versions 4.6.4 and 4.7.4 (more info below)

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play/?ts=5.4.5#code/KYDwDg9gTgLgBDAnmYcBiEJwLxwN4BQAkAGaYBccAzjFAJYB2A5gNwEC+bBoksCyqAMIQGNKAENGMADxo4oGMAYATKukwA+HPmJhxsAIwAKAJSU0bIntgAmI2APmzcAG4Q6ytpwLdw0eEgocMKitJIMMDay8iCKKmoYEFq4hFb6MMbOFrrpdg6UAHIQAJIMJMBQshrObh5eXAD0DXAASsBgADbiAMaMTHAABiFi4TADcADudDAAFoPDYVI24zPiagxYynQk5VBK3cC+vPDdIjRwjLsAyjAArjva0QpKqupJRrN9lAsSUlUmOC0qT2dygDAQMz69R8TTgABVIWpTlA9t0YB1EBcyhU1LNUIFUNZxABbYCKKAILCrFyoABGEFmENQAzIEHG4hUg1p+nGAGtgIg1AA6EUEU6hODI1HwXCXCo3e4kIypawZUw6IhEEG3MEazWsygAIm5UENABpiJqTUbuQAvc2W7xEdgWtK2ewGAF4F0cEyNZoioWTSEdfGIuDKCDAdYMuCBsVneCMKXANHaOVQBU7ZU5d0OL0+t1qr2W7W61L6ihwY36B2aojW6t2uvOyw+9gmGEBkVwWm3ALhyPRuDiJjhOAAfgTEomqxgxSoAAlxGAUAw+unsZm7tmVbl1d7XarMnqy+CK6QqzXTa6rfobeJ7bene3O0A)

### 💻 Code

```ts
export type Foo = {
	foo: string;
};

export type Constraint<F extends Foo> = {
	part1(): F;
	part2(p1: F): void;
};

export type Constraint2<F extends Foo> = {
	part1(): F;
	part2(p1: NoInfer<F>): void;
};

// Replacing `Constraint` with `Constraint2` has no difference
export const inferStuff = <F extends Foo>(thing: Constraint<F>) => {
	return thing;
};

// This correctly infers the type parameter to have both the `foo` and `bar` keys ...
const correct = inferStuff({
	part1() {
		return {
			foo: "bar",
			bar: "baz",
		};
	},
	part2(p1) {},
});

// ... while this does not ...
const incorrect = inferStuff({
	part2(p1) {},
	part1() {
		return {
			foo: "bar",
			bar: "baz",
		};
	},
})

// ... but this does again ?
const whatIsHappening = inferStuff({
	part2() {},
	part1() {
		return {
			foo: "bar",
			bar: "baz",
		};
	},
})
```

### 🙁 Actual behavior

When `part1` appears before `part2`, or when the parameter to `part2` is omitted, then the type parameter is properly inferred. When `part2` appears before `part1` with a parameter, then the type parameter is inferred incorrectly, even when using `Constraint2` which has `NoInfer` on that parameter's type.

In 4.6.4 and below, `correct` has the same type as `incorrect` (the order of the keys in the object didn't matter, but inferred less specifically).

### 🙂 Expected behavior

All three usages should be equivalent to each other, and in particular, should infer as `Constraint<{ foo: string; bar: string; }>`.

### Additional information about the issue

Here's another example, that shows relatedly incorrect behavior: [playground](https://www.typescriptlang.org/play/?ts=5.4.5#code/KYDwDg9gTgLgBDAnmYcBiEJwLxwN4BQAkAGaYBccAzjFAJYB2A5gNwEC+bBA9N3AELAANhADuAGgQALVAAMwAQ1gAmWVTjAoUaHEZwARhBhSNIBQFswQ4Ov3AAxgoCuVVMbfJUddYxKaowAAmcCTa5nDySjAAjLIAdDx8AJIkcIgQTtSiCmDSqNCBmnAQqZGwsXAKDMFlMKpw9ExS8DIBugwRAMIQDDRQCowwspLuHe4RiuVqcKJ0QkIaWjqMNMAKgQmgkLAInnDdvbQDDDAAPGimMMDV6hgQAHw4+MSTMQAUAJSUaGxEr8qfb5sTgEAhbaDwew9GjtPxQADKMCcJFSuHOl2ugVumHub2MjCYlAOfWOZzQ9w+OEehCIASRUDGUgJwK4UMOxQYwAAKjIGFzRFhcL5NIjkSQ3jTXtFPs8iLTgPSOjS5WQIJQAET6JTq8TEOVaqAarUALx1epBRHYur+UQBlOVdKcDNlKoocE12utcvMwDEGp9YjNcotVo4Hy4vDgcWjMyZ1mk3jggQgNjgDCMUejBDZMJgAp51wA8pynsKEUiURKXraZQ6FU6lXrSG6PVAg97faJ-Z32yHrVLa3rHc7lc21e6De2iAajQpTV6+2GWEA)

**Comment by RyanCavanaugh** [comment]
See #47599
