### ISSUE TITLE
Type Error in Array.includes() method when the array contains only string keys 

### ISSUE THREAD

**Issue by LoganTann** [microsoft/TypeScript#58671]
### 🔎 Search Terms

"typescript for in string" "typescript keyof for in" "array includes keyof"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "for in", "keyof"

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEAiYBcwGFxWgbwFDV9ADgK4BGIAlsNGAPwBc0ECATmQHYDmA3DnkaRdGJ1orQgFtiAUybcAvlmAB7Vo2hl2rRU0kATANKSAnjHoAKANZHFAMziIUaCAEoA2gF1oAXjwuA5GF83bgVlVR1gAEkVJFZgSS8RSQB3OyRUSAhTJ25wqMYwWMkAOjAEgCJlSTKcyOiCuKLiBIAmbmstaFMlaOhLQzVWaFy6wqdMHlwyW1MAQnVNbX0jCCK2UEIdSUy+pzHsPAPobohFEGKQRXZTMuH8wpcAUggPbyeygBpeo0+AZWY2K63GJxFx9Ny7bgHeTyLBAA

### 💻 Code

```ts
class DataClass {
    public a?: string;
    public b?: number;
}
const ignoredKeys : (keyof DataClass)[] =   ['a'];

const dcInstance = new DataClass();
dcInstance.a = "one";
dcInstance.b = 2;
for (const key in dcInstance) {
    if (!ignoredKeys.includes(key)) {
        console.log("dcInstance[%s] = %s", key, String(dcInstance[key]));
    }
}
```

### 🙁 Actual behavior

Actual behavior : 

- In statement `ignoredKeys.includes(key)`, error Argument of type 'string' is not assignable to parameter of type 'keyof DataClass'
- In statement `dcInstance[key]`, error Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'DataClass'. No index signature with a parameter of type 'string' was found on type 'DataClass'.
- `const key` is typed as "string"

### 🙂 Expected behavior

The statement `ignoredKeys.includes(key)` should not throw any type errors. The `Array.includes()` method should accept strings as arguments when all items stored in the `ignoredKeys` array are string keys.

_Other expected behavior, but not important at all :_
_- Variable `key` should be of type `keyof typeof dcInstance` instead of "string"_
_- No type errors in statement `dcInstance[key]`_

### Additional information about the issue

I have an entity and would like to iterate over the keys of that object, excluding some keys.

**Comment by MartinJohns** [comment]
Duplicate of #14520.

**Comment by nmain** [comment]
> `ignoredKeys.includes(key)` should not throw any type errors

See https://github.com/microsoft/TypeScript/issues/14520, and other duplicates linked from it.  My search terms were "array includes lower bounds".

> Variable key should be of type `keyof typeof dcInstance` instead of `string`

Types are not sealed, so this is not true in general.  See https://github.com/microsoft/TypeScript/issues/12936 for more details.

> No type errors in statement `dcInstance[key]`

This follows from the above; once `key` is `string`, the indexing is no longer safe.

**Comment by LoganTann** [comment]
Linking another duplicate, thanks for the clarifications.

https://github.com/microsoft/TypeScript/issues/55090

Closing this issue.

**Comment by LoganTann** [comment]
Except casting using unknown or any types, are there any workarounds for the simple example I provided here ?
