### ISSUE TITLE
Attribute and Method Visibility depending on generics in form of `private` return type

### ISSUE THREAD

**Issue by Anatoly03** [microsoft/TypeScript#58672]
### 🔍 Search Terms

method visibility, shadow generics, type guards and method availability, generics with type hinting, generic polymoprhism

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Introduce the visibility modifiers to be used by generics in attributes and methods, that take effect as type hinting.

```ts
class ArrayWrapper<Mutable extends boolean> {
    private data: number[]
    private mutable: Mutable
    
    constructor(data: number[], mutable: Mutable) {
        this.data = data
        this.mutable = mutable
    }

    get(index: number): number | undefined {
        return data[index]
    }

    set(index: number, value: number): Mutable instanceof true ? void : private {
        data[index] = value
    }

    reverse(): Mutable instanceof true ? void : private {
        // Because of the return type, you can assume `Mutable instanceof true` holds here.
        this.data.reverse()
    }
}
```

This will construct the methods `get` and `set` for `ArrayWrapper<true>`, but only `get` for `ArrayWrapper<false>`. This can also be used when working with SDK's that connect to a server and can extend their base class when `Client<Connected extends boolean>`. This would essentially allow an easier and compact way to "generate" classes that have common and interchangeable behaviour without having the need to create all the variations among inheritance routes.

When using the conditional construction on a variable, you would get the same results:

```ts
class Client<ConnectState extends boolean> {
    public data: ConnectState instanceof true ? .... : private
}
```

Say you have a data packet and scopes in which client has them, and scopes in which these are not initialised. You could use the generic `ConnectState` to achieve precisely the described result. The more complex example would be:

```ts
class Connection<ReadAccess extends boolean, WriteAccess extends boolean> {
    private socket: ...

    receive(callback: (b: Buffer) => void): ReadAccess instanceof true ? void : private {
        socket.receive(callback)
    }

    send(data: Buffer): WriteAccess instanceof true ? void : private {
        socket.send(data)
    }
}
```

In practice, this would act like a regular generic and the class methods/ variables are not explicitly undefined, just hidden. `private` would not work with `|`, `&` or be used in a utility type, but it can only act as a standalone type. You cannot cast to private. `private` as type would only work in class and interface methods.

### 📃 Motivating Example

This features allows to use generics to hide certain methods and variables creating a powerful ability to have a class as a factory with common behaviour and minimal changes.

### 💻 Use Cases

1. What do you want to use this for?

Powerful API writing, ability to use generics for conditional visibility of class methods depending on program state or "state-of-the-class"

2. What shortcomings exist with current approaches?

Right now you would have to write different classes without generics, use inheritance to solve this problem, but since you have to create a class for a "combination" it could get extremely unbeautiful very quick.

3. What workarounds are you using in the meantime?

As described in 2

**Comment by fatcerberus** [comment]
`Mutable instanceof true`?  What does that even mean?

**Comment by jcalz** [comment]
Maybe using `instanceof` makes it so that you don't need `this` when referring to instance properties. Kidding, kidding.

For this use case I would use a `this` parameter and not try to add new syntax to the language:

```ts
class ArrayWrapper<Mutable extends boolean> {
  private data: number[]
  private mutable: Mutable

  constructor(data: number[], mutable: Mutable) {
    this.data = data
    this.mutable = mutable
  }

  get(index: number): number | undefined {
    return this.data[index] // <-- this.data, not data.
  }

  set(this: Mutable extends true ? this : never, index: number, value: number) {
    this.data[index] = value // <-- this.data, not data
  }

  reverse(this: Mutable extends true ? this : never) {
    this.data.reverse()
  }
}

const mut = new ArrayWrapper([1, 2, 3], true);
mut.set(0, 7);
mut.reverse();

const imm = new ArrayWrapper([4, 5, 6], false);
imm.set(0, 7); // error
imm.reverse(); // error
```
[Playground link](https://www.typescriptlang.org/play/?noErrorTruncation=true#code/MYGwhgzhAECCBO8wE8DqSAOGCm8A8AsgK4AuYARiNtNgB4nYB2AJjOQPbtViMB80AbwCwAKGjQM8AJYA3MA2jN5YAFzRGRALblcAbQC6o8ZNnzqm0hSpriZStlFHowdowgl4RYCXbwAFEpkahraevoANNAWdtbQtlbYAJSCTuIkABZSEAB0gWDQALyKyqnQGVnZ0QmFUZb2TgC+jmLQAObYJH5SLHTBWjrwiX2h8NAAPtBEPQBm3djMKS3i8B1E8IxlmTl5ut3MdPrQAPRH0HgAtOebFXmRjOwkxWTZjc3iEB1+5RA2dVQ09CYrDKnmoAH5rjBgtgZLhInteup+nDoHIQERsMMBslhEtIbllLserRDkU0RjjqcLldvgSyHcHk8wK8RE4VrD4B8vltfjFqHQGCwYB4KRDvtBoRycaVaXlsuzcFzEiymqyRC43I9ojVGNgAO5wRAodBgLC4Py6ACMkQATJEAMwREEYxIAblE0WyH06AAZIgB2N0e0jymGK7B+INqjXuaBSTSaHX6w1INCYHD+XQAFkiAFZIgA2J3TMAgD5R+OaL2fP3QQOuyk0RC+USV0McpUNk5N+C+IA)

**Comment by Anatoly03** [comment]
Yes, that's what I was looking for the past days! Thank you, very much., @jcalz, I was trying to approach the problem from the wrong angle.
