### ISSUE TITLE
WebWorker NotificationOptions type issue

### ISSUE THREAD

**Issue by unadlib** [microsoft/TypeScript#58674]
### 🔎 Search Terms

TS2769

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions 5.0 and 5.4.5
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

in ServiceWorker.

```ts
self.registration.showNotification(`test`, {
      actions: [
        {
          action: 'ignoreCall',
          title: 'test',
        },
        {
          action: 'answerCall',
          title: 'test',
        },
      ],
    });
```

/** [MDN Reference](https://developer.mozilla.org/docs/Web/API/ServiceWorkerRegistration/showNotification) */
    showNotification(title: string, options?: NotificationOptions): Promise<void>;

### 🙁 Actual behavior

No overload matches this call.
  Overload 1 of 2, '(title: string, options?: NotificationOptions | undefined): Promise<void>', gave the following error.
    Object literal may only specify known properties, and 'actions' does not exist in type 'NotificationOptions'.
  Overload 2 of 2, '(title: string, options?: NotificationOptions | undefined): Promise<void>', gave the following error.
    Object literal may only specify known properties, and 'actions' does not exist in type 'NotificationOptions'.ts(2769)
(property) actions: {
    action: string;
    title: string;
}[]

### 🙂 Expected behavior

There should be no error message

**Comment by jcalz** [comment]
Duplicates https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1725
