### ISSUE TITLE
TS 5.5.0-beta Regression: generated .d.ts is not compatible 

### ISSUE THREAD

**Issue by ericanderson** [microsoft/TypeScript#58682]
### 🔎 Search Terms

".d.ts", "typeof", "5.5-beta"

### 🕗 Version & Regression Information

This is a regression from prior versions. You need two packages to reproduce so you can repro here: https://github.com/ericanderson/ts55-beta-regression

Simply changing from 5.4 to 5.5-beta causes `typeof` references to no longer produce proper/compatible .d.ts files.

### ⏯ Playground Link

https://github.com/ericanderson/ts55-beta-regression

### 💻 Code

`dep/src/index.ts`:
```ts
interface Shape<T extends string> {
    hmm: T
}

const _Holder = {
    hmm: "foo"
} satisfies Shape<"foo">;

type _Holder = typeof _Holder;
export interface Holder extends _Holder { }
export const Holder = _Holder as Holder;
```

`main/src/index.ts`:
```ts
import { Holder } from "dep";
Holder.hmm;
```

### 🙁 Actual behavior

```
src/index.ts:3:8 - error TS2339: Property 'hmm' does not exist on type 'Holder'.

3 Holder.hmm;
         ~~~
```

`dep/lib/index.d.ts`
```ts
declare const _Holder: typeof _Holder;
type _Holder = typeof _Holder;
export interface Holder extends _Holder {
}
export declare const Holder: Holder;
export {};
```

### 🙂 Expected behavior

No errors.

`dep/lib/index.d.ts`:
```ts
declare const _Holder: {
    hmm: "foo";
};
type _Holder = typeof _Holder;
export interface Holder extends _Holder {
}
export declare const Holder: Holder;
export {};
```

### Additional information about the issue

In the repo directory, you can fully reproduce by running:
`pnpm install` (to link the packages)
`pnpm run test`

**Comment by fatcerberus** [comment]
This looks very similar to https://github.com/microsoft/TypeScript/issues/58557

**Comment by dragomirtitian** [comment]
This is fixed in the nightly [Playground Link](https://www.typescriptlang.org/play/?ts=5.5.0-dev.20240528#code/JYOwLgpgTgZghgYwgAgMoAs4AcIB4AqyEAHpCACYDOylYUoA5gHzIDeAUMl8ugLa8AuZPnYBfduwQB7ELWQB9ABJSANuWjIAvG07c+g5ACIYUqYbE04YYJRjAI1DNjzHThpgG4JYAJ44Fymoa2r44UjABqupQXiRYUlBgyKCQsIgogdFEpBAU1EpRGqzI4nEJSdKySZnBkUFQyHDUNTFAA)
