### ISSUE TITLE
[ts-beta 5.5] Function declarations are not exported when targeting commonJS - js emit regression 

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#58699]
### 🔎 Search Terms

JavaScript emit commonjs

### 🕗 Version & Regression Information

- This changed between versions 5.4 and 5.5beta

### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play/?moduleResolution=99&target=99&module=1&ts=5.5.0-dev.20240528#code/GYVwdgxgLglg9mABAcwKZQAoCc7KwQwFsAKAZzhCwlQC5FSosYxkBKRAbwF8AoVADwAOcLFE4p02XAUIAaRAGFEXIA)

### 💻 Code

```ts
function getProgram(source: string) {}
export { getProgram }
```

### 🙁 Actual behavior

The following js is generated:

```js
Object.defineProperty(exports, "__esModule", { value: true });
exports.getProgram = void 0;
function getProgram(source) { }
```

This does not actually add the function to the export. So when importing `getProgram` it will be undefined.

### 🙂 Expected behavior

Emit should be the same as 5.4 where the function is actually exported:

```js
Object.defineProperty(exports, "__esModule", { value: true });
exports.getProgram = void 0;
function getProgram(source) { }
exports.getProgram = getProgram;
```

### Additional information about the issue

This seems to affect only function declarations. Variables, classes seem to be exported correctly.

**Comment by Andarist** [comment]
I think a fix for this was merged just yesterday: https://github.com/microsoft/TypeScript/pull/58489

**Comment by jakebailey** [comment]
The CI got cancelled and screwed with things, manually fixing it right now

**Comment by jakebailey** [comment]
Website should be okay now
