### ISSUE TITLE
Object.values and Object.entries return any instead of the actual value when object values are an intersection

### ISSUE THREAD

**Issue by alissawix** [microsoft/TypeScript#58690]
### 🔎 Search Terms

ts "Object.values" returns array of any for generic type, Object.values and Object.entries return any when object values are an intersection

### 🕗 Version & Regression Information

- This is a crash - no
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Object.values
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAaghgGwJYBM7AgHgCpQgDwwDsUBnKAbygG0BrCEALilOACckiBzAXWYFcitIgHsA7kSgBfAHxQAvJQBQUVTXogonKBpEAzKNj6G6DHlABkytTahxmRfgFsARhDYBuFbdUvmrDm4vGykvUKU9QQBjYCQRST0RERw8QggScipTJhZ2Tl4BIVEJaRkAChEXACtmeGQ0DBwZAEprNSj41jsFKEqq6gByUgGeADo4DygAeinHV3dvVVBIKGA1nrLliH1e6ubqOCIQHkWoDqIu4DgNiik7cjXgZvHVGbm3NlPzroA3RH4IORFAB5aoQGKjP4IAGkCp7aZTQ4gagnGxsCDAfhsSR9MJKCJJMpUUjMKj2KAARgANFA-FABgAmAbSaTNLxAA

### 💻 Code

```ts
type Validate<T extends { [key: string]: unknown }> = {
    [key in keyof T]: T[key] & {
        a: number;
        b: string;
    };
};
function foo<T extends { [key: string]: unknown }>(obj: Validate<T>) {
    const a = obj['s'].a;    //number
    type ttt = (typeof obj)[any]
    const ta = ({} as ttt).a      //number
    const values = Object.values(obj)    //any[]
    return obj;
}

foo({ s: { a: 1, b: '2' } });
```

### 🙁 Actual behavior

if I access any key on the `obj` directly I get the correct type
even if I use `(typeof obj)[any]` I get the correct type

but if I use `Object.values(obj)` I get `any[]` which means that I can't access `a` and `b` properties

### 🙂 Expected behavior

I would expect the  `Object.values(obj)` to return `{a: number, b: string}[]`
since we know from the intersection that a and b will be there

**Comment by alissawix** [comment]
@jcalz thank you for quick response, why doesn't TS see `T` as having an index signature?
btw, if I remove the `T[key] & ` it works

**Comment by jcalz** [comment]
Um, I guess I should have said `Validate<T>` and not `T`, and that TS doesn't *infer* an index signature there.  It is willing to "see" it, in the sense that the manually specified type argument works. As for *why* it happens exactly, that's not something I can answer, maybe someone else has a clue. Still isn't a bug with `Object.values()`, though.
