### ISSUE TITLE
Type narrowing not work in forEach callback

### ISSUE THREAD

**Issue by xiaoxiyao** [microsoft/TypeScript#58707]
### 🔎 Search Terms

narrow forEach

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about "common-bugs-that-arent-bugs"

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.4.5#code/FAGwpgLgBAZg9nAXFAzhATgSwHYHMoA+UAguugIYCeAPGlngHwDcww8cUAvFANoC6LNggB0ABwCuKABYAKAORyAlEygB6VXADWrAMZxsaKOTJdec8nIA0UOQCMrNnXIGt46KDL0HoKKHBhGZIpQAN7AUBGwIhLSMijKaqpR7v5QmL5awAC+rMbowm4AouQ6sr6cDKHhkexikmUJ6lBgZHDo2cqsmAEypBSUwul9VDLsisFhkYH5RSVlXJWTUzXR9XGNSS3obdURWZ05bOLYOhCY+lAQYGgyE7tRcHWxChvNrejWALZUtmBQ2HBoAB3NqaNLYWDHU7nCEAfmywCAA

### 💻 Code

```ts
let foo: string | Array<string>;

foo = [];

foo.push(''); //ok

const arr = ['a', 'b', 'c'];

for (const s of arr) {
    foo.push(s); // for of is ok
}

arr.forEach(s => {
    foo.push(s); // error
});

if (Array.isArray(foo)) {
    arr.forEach(s => {
        foo.push(s); // error
    });
}

function test() {
    foo.push(''); // error, maybe not work in function ?
}
```

### 🙁 Actual behavior

Type narrowing not work in forEach callback

### 🙂 Expected behavior

Type narrowing work as expected

**Comment by fatcerberus** [comment]
> error, maybe not work in function ?

Correct - see #9998.
