### ISSUE TITLE
resolving type parameter

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5871]
```
interface A<b> {
  value: b[]
};

type C = A<string>;
```

I am traversing the shown types starting the type alias `C` which led me to type `A` which has a member `value` of type `Array` which has a type argument that is type parameter `b` of `A`. Now being at **this** point: 

- What do I have to do to resolve `b` to `string`?

**Comment by DanielRosenwasser** [comment]
Before I start a response, are you trying to understand compiler internals, or are you just trying to just get information about the state of your program?

**Comment by aleksey-bykov** [comment]
I need to traverse my data structures starting from the root interface down
though the properties to their types etc till until I get all types that
directly or indirectly consitute the root interface. Once that done I need
to generate a report with the name of the properies, their **resolved**
types and JDOC annotations.

If this can be done via compiler API that would be great.

**Comment by DanielRosenwasser** [comment]
You can get a `TypeChecker` instance and use `TypeChecker#getTypeAtLocation` on `C`. Here's some code that currently might do something similar to what you want to do: https://github.com/Microsoft/TypeScript/pull/5332/files

**Comment by aleksey-bykov** [comment]
I already did that. How do I get the`value` property resolved to `string
[]`?

**Comment by aleksey-bykov** [comment]
(getting it as an unresolved `b[]` is trivial)

**Comment by DanielRosenwasser** [comment]
Have you been using `typeChecker.getPropertiesOfType` and `typeChecker.getPropertyOfType`?

**Comment by aleksey-bykov** [comment]
no I used `Type.getProperties`, let me try doing it via the checker

**Comment by DanielRosenwasser** [comment]
I think that should still work, though let us know if that's the problem.

**Comment by mhegazy** [comment]
`Type.getProperties` is just a wrapper around `checker.getPropertiesOfType(Type)`. do you have a sample i can debug?

**Comment by aleksey-bykov** [comment]
ok this is what did it:

```typescript
function seePropertyType(node: ts.TypeAliasDeclaration, checker: ts.TypeChecker) : void {
    let type = checker.getTypeAtLocation(node.type);
    let props = checker.getPropertiesOfType(type);
    props.forEach(prop => {
         let resolvedPropertyType = checker.getTypeOfSymbolAtLocation(prop, undefined);
         console.log(resolverPropertyType);
    });
}
```

thank you for you help
