### ISSUE TITLE
Resolve peer dependencies from current project

### ISSUE THREAD

**Issue by xixixao** [microsoft/TypeScript#58721]
### 🔍 Search Terms

peer local file

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When a dependency is specified in a library's peer dependencies, and it is installed in the current project, it should be resolved from the current project's node_modules, not from the library's node_modules, when `file://` is used for testing the library locally.

### 📃 Motivating Example

Say you have a project "test" and a library "foo". "foo" has "react" in its peer dependencies, "test" has react and @types/react installed. With this change, you can now test "foo" in "test" with `file://../foo` without needing to delete its node_modules.

### 💻 Use Cases

1. What do you want to use this for? Library development
2. What shortcomings exist with current approaches? It leads to incorrect type errors
3. What workarounds are you using in the meantime? Deleting the library's node_modules

I tested that this doesn't work with typescript@next

**Comment by RyanCavanaugh** [comment]
I'm not quite sure what you're getting at here. Some code examples might help?
