### ISSUE TITLE
With strictNullChecks false, infer in conditional type can covert null type to unknown

### ISSUE THREAD

**Issue by Ellisthion** [microsoft/TypeScript#58723]
### 🔎 Search Terms

strictNullChecks, infer, conditional, null, unknown 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types and strictNullChecks. In Playground, v3.3.3 infers the `unknown` as `{}` instead, but is still `null` for strictNullChecks true. All later versions match the current behaviour.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?strictNullChecks=false&ts=5.4.5#code/PTAEFEA8EMFsAcA2BTUAzA9gJ1AcgJIB2ayWWAloQOagDq5ALgBaWgDCGhAJo+Z9IlAAVAJ7xkAZ1zosGWKC4YAxhICwAKBCgmDBvAkAuEAHdTAOgZjJSivAaJo1M9irBFK4E0dcARhgwA1sAATMBKnDwMfIQCALSW4hJmOrCIAMSUJGSUVLHGjCyEseHcvPyI8VZq6gmoAGIOusiEADyi4gB8oAC8wlagyJAMzVwSoACCZNAiLZmkoPjDsF0A-AtLoAZ94gDcGhpa+BISAK7IGigM6I1bDdBNrYQniIgdO6Ba7ajkYyeEAYQMMZCKBsKAni8FMhxKVqKCQRIGBQlAwAHLPRBsJjIJQBaqXUAANy2EMEvTQjXehzQoG88MQIlA5BpiORaIxWJxeJ66AEEmQABpQEpoCd+WNSLIsFsvng-gCgYRpD9wRgrtBjuQqDEfChQAwMPr+rhSbgzEA

### 💻 Code

```ts
// Example for 'Inferring Within Conditional Types' from docs
// https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types
type Flatten<Type> = Type extends Array<infer Item> ? Item : Type;

// Issue
let flat: Flatten<null>; // Type is unknown or null depending on strictNullChecks
let v: null = flat; // If and only if strictNullChecks = false, causes error: Type 'unknown' is not assignable to type 'null'.
```

### 🙁 Actual behavior

The conditional type resolves the `null` type as `unknown` when strictNullChecks is false, which can cause compile errors because `unknown` can't be assigned to `null` even in that mode.

### 🙂 Expected behavior

The conditional type resolves the `null` type as `null`, even when strictNullCheck is false

### Additional information about the issue

Real-world issue using Vue Ref types (which use this kind of type unwrapping) combined with a 3rd-party library that uses properties typed as `null`.

**Comment by MartinJohns** [comment]
With `strictNullChecks` disabled the type `null` doesn't exist and is ignored. This is working as intended.

**Comment by Ellisthion** [comment]
> With `strictNullChecks` disabled the type `null` doesn't exist and is ignored. This is working as intended.

If the `null` type was simply ignored then this wouldn't be causing a compile error, but it is.

Normally, library code that is written with more-strict types for use with strictNullChecks enabled will still work perfectly in application code that has strictNullChecks disabled, but in this case it doesn't.

**Comment by fatcerberus** [comment]
Martin is right, but this probably warrants further explanation.  With `strictNullChecks` disabled, `T | null` is equivalent to `T`; since it always simplifies out, `null` by itself becomes a kind of bottom type, similar to `never` and is therefore a subtype of everything, which causes the conditional type to take the true branch (because `null` is, in fact, assignable to `Array<...>` with SNC off) - and since there's nothing to infer `Item` from there, it defaults to its constraint of `unknown`.

**Comment by fatcerberus** [comment]
> With strictNullChecks off, should that actually be an error?

Yes, for the same reason that `let v: never = null as unknown` is an error even with SNC on.

> All this really boils down to the annoying question of: if `strictNullChecks` is off, what exactly does the type `null` mean to the compiler? The answer seems to be "it's weird". Even if this is how it currently works, it doesn't feel desirable to work like this.

I can't argue there.  If anything it'd probably make more sense for `Flatten<null>` to work like `Flatten<never>` (i.e. distribution over an empty union returning the original type).

**Comment by Ellisthion** [comment]
> Yes, for the same reason that `let v: never = null as unknown` is an error even with SNC on.

Yeah that makes sense.

> If anything it'd probably make more sense for `Flatten<null>` to work like `Flatten<never>`

That's a good point. `Flatten<never>` returns `never`, despite the fact that `never` is assignable to `Array<T>`, just like `null` is.

**Comment by RyanCavanaugh** [comment]
>  if strictNullChecks is off, what exactly does the type null mean to the compiler? The answer seems to be "it's weird"

I don't think there's anything coherent we can say about this. If SNC is off, you shouldn't be talking about `null`, it doesn't exist.

**Comment by Ellisthion** [comment]
A specific goal of the original non-nullable types implementation was to preserve compatibility. It was a clear goal that declaration files designed for non-nullable types would be usable by code that did not use that setting.

https://github.com/Microsoft/TypeScript/pull/7140
"Thus, declaration files that are updated to use null- and undefined-aware types can still be used in regular type checking mode for backwards compatiblity."

Assuming that having `strictNullChecks: false` is still considered supported, the current behaviour goes against this original intent. App code without strict nulls cannot use a declaration file designed for strict nulls and guarantee that it will compile.

>  If SNC is off, you shouldn't be talking about null, it doesn't exist.

We are specifically talking about non-strict-nulls app code using a 3rd party .d.ts file that was designed to support strict-nulls. This is specifically part of the above goal of the original non-nullable types implementation.

Every TS compiler option for strictness is, afaik, designed in this way, for compatibility with less-strict options. I've been using Typescript for over 10 years, since the betas, and this is the first time I've seen a compile error _introduced_ by a _less strict_ compiler option.

If:
* `strictNullChecks: false` is supported; and
* A .d.ts file designed to support `strictNullChecks: true` should be backwards compatible for use by code with `strictNullChecks: false`, as per the original implementation notes in https://github.com/Microsoft/TypeScript/pull/7140

Then this issue breaks that compatibility and is a bug.
