### ISSUE TITLE
Generic argument type changes inside function body

### ISSUE THREAD

**Issue by rotu** [microsoft/TypeScript#58731]
### 🔎 Search Terms

Object.values, const modifier, extends, widening 

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

<details>
<summary>Original example</summary>
### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&jsx=0&ts=5.5.0-dev.20240531&q=5#code/MYewdgzgLgBCBGArGBeGBvARARkwLk3AFNMBfGAQwhlEigCh6AzAVzGCgEtwYnsAeWtBgAVGEQAeUImAAm1BIiIcAfAAooeUQEoMMAE5EoLfWBgB5JMqgA6AG4UANiyIQNu0vSGwK2VL2w1RW0AbhgAenDKMABPAG0AXXpImFSYAD0AfkZWdi4eJgAmQXBhMUlpOWpLJVUNLRFddAMjEzMa63snFzcoDy9Sn0L-IqCkUIioiljE5Ki0rJy2Dm4zJgBmErpRcSkZeRgAJWUQfVl+aH1OMABzABoYNgBrMBAAdzAVdU0dPUNjUwWKwcLrOVzuGCebyUdYjdZjRATFLPV4fWYpBbZZjLfJrAAsWzKu0qB3QpG+DSaLQB7WBtgcYN6-WhFDxIzxCKRURR7zA6PmqUWA22FAArP4OiCGT01FhcARiGRdClLtcbvy0hksSyAGwSumgmXBSYwQhgEgazFAA ~~

### 💻 Code

```ts
const obj = {"1":"one"} as const

function f1<const T extends object>(t: T) { return Object.values(t) }
const a1 = f1(obj); // any[]
//    ^?

function f2<const T extends Object>(t: T) { return Object.values(t) }
const a2 = f2(obj); // any[]
//    ^?

function f3<const T extends Record<string, unknown>>(t: T) { return Object.values(t) }
const a3 = f3(obj); // unknown[]
//    ^?

function f4<const T extends {}>(t: T) { return Object.values(t) }
const a4 = f4(obj); // unknown[]
//    ^?

const a5 = Object.values({"1":"one"}) // string[]
//    ^?

const a6 = Object.values(obj) // "one"[]
//    ^?
```

### 🙁 Actual behavior

Accidental type widening occurs despite the `const` modifier on type parameter `T`.

a1, a2 are inferred as type `any[]`.
a3, a4 are inferred as type `unknown[]`.

### 🙂 Expected behavior

It is expected that `a1`, `a2`, `a3`, `a4` are inferred as the same type.
Further, due to the const modifier, it is expected that these match either the type of a5 (`string[]`) or the type of a6 (`"one[]"`).

### Additional information about the issue

I think the `any[]` vs `unknown[]` is from the overload of `Object.values`:

https://github.com/microsoft/TypeScript/blob/ef514af2675389d38c793d6cc1945486c367e6fa/src/lib/es2017.object.d.ts#L6
https://github.com/microsoft/TypeScript/blob/ef514af2675389d38c793d6cc1945486c367e6fa/src/lib/es2017.object.d.ts#L12

</details>

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&jsx=0&ts=5.6.0-dev.20240607&q=5#code/MYewdgzgLgBCBGArGBeGBvARARkwLk3AFNMBfGAQwhlEigCh6B6JmKACwEtruYB3dhVh8iAcgBORNuICenMAHM2IGAFtO64ADoYAFXZTJUAK7iwbGQAcpvACZFrYe2Fjg2BmPMvHYUK0S16WmgYBRAKABtUGAB5JCJgKC0AN0jjIggACgREAEoYFhhCMBIAbQBdZlYYGoA9AH5GQswAORUQZKJxCPDbNSFgA2oOXmBIiK1MGABaPRgIimAAa2GPP2sacGhxCnlfFQghbgAzGVj4xJS0jPpj4zBEzjdj7AAeXQA+TKg8PXz0GBGUzmOKIBJJVIRdJZKD5UhBLawAD62GiL2ySHyhXuSzAID4YAqVRqdUaxIAkqJVDAiAAPayPRTuQxEExmCwbEDHGDHABMyhg8CkCiIJXEnGAnnMugANIKfJ4oKJqJE+BQZNQcXiCUS7g8oE9zHz3jTaVBRbZqOhSF8fn8MIDWcDzmDLpDod84cSSSSGgi6DAkfy0Mb1kQuXAkF8cljWFr8YTKoVfWTCuSYIJOgLQF1gFJdAKKPMMtRLJJgNwWaBxH0w1K4DWugKRb4POKFOxYED2WHbvdHs8AMwmunmpxW0pLesUMAycp4XSTogyCO6co276-XT-R1skEXCHXGFe5M+mB+4LIwdowcYvIFVjFMpJ6qkpqsABCCs43PTxggUhFmWCSVv0ljWLW-hyhwLJ7hyNgqgouzmPGOqVHqA5GgALCOZoWhOU7yDASzLqu86Lks662luO7dvurqHlCGSejA8Knj6F6IoGWFolhd6xjAqGJt6pJAA

### 💻 Code

```ts
const obj = {"1":"one"} as const

// this is what we're trying to mimic. The return type is dependent on the input type.
const goal = Object.values(obj) // "one"[]
//    ^?

// "No overload matches this call." - T lacks the type constraint to satisfy Object.values
function f1<T>(t: T) { return Object.values(t) }
const _1 = f1(obj) // unknown[]
//    ^?

// I'm expecting the return type of f2 to be generic in T, but it's always unknown[]
function f2<T extends {}>(t: T) { return Object.values(t) }
//       ^?
const _2 = f2<typeof obj>(obj) // unknown[]
//    ^?

// I have to coerce T to a less precise record type in order to get the right return type
function f3<T extends {[k in any]:T[keyof T]}>(t: T) { return Object.values(t) }
//       ^?
const _3 = f3(obj) // "one"[]
//    ^?

// But if I use a precise mapped type, the return type is again unknown[]
function f4<T extends {[k in keyof T]:T[k]}>(t: T) { return Object.values(t) }
//       ^?
const _4 = f4(obj) // unknown[]
//    ^?
```

### 🙁 Actual behavior

The generic function's return type is not dependent on the argument type.

### 🙂 Expected behavior

I expect the generic function's return value to be based on the input type, as if one substituted the object literal for the argument.

It was originally my impression that adding a `const` qualifier should make generics "work like this" but that's apparently incorrect.

**Comment by jcalz** [comment]
The `const` modifier only affects type inference when you call the function, and in each case you’re passing in `obj`, a value whose type is fixed ahead of time. There’s nothing for `const` to do in any of your examples (on mobile now but I’d check that by removing `const` and seeing if anything changes at all; my claim is it won’t).

You seem to think a `const` modifier does something to the constraint of the generic?  And that’s why you expect the return type of the functions to depend on it?  That’s not how it works, though.  

Or am I missing something? I just don’t see a bug here.

**Comment by rotu** [comment]
@jcalz The point of the `as const` was to ensure the function must remain generic as long as possible and not optimized down to `function f(t:{}){return Object.values(t)`.

Why does the `extends` clause change the type of `t`? I expect `extends` to constrain what `T` could be, *not* to rewrite `T`, and certainly not to weaken the type bound `T`.

**Comment by jcalz** [comment]
"The point of the `as const`" <-- ? On `obj`? How does that affect any of the functions as all? Or are you talking about the `const` type parameter, in which case, that's not `as const`. Typo or something? I'm not following.

**Comment by rotu** [comment]
> "The point of the `as const`" <-- ? On `obj`? How does that affect any of the functions as all? Or are you talking about the `const` type parameter, in which case, that's not `as const`. Typo or something? I'm not following.

D'oh! You're right. I meant the point of the `const` on the type parameter `const T`.

**Comment by fatcerberus** [comment]
> I expect `extends` to constrain what `T` could be, not to rewrite `T`, and certainly not to weaken the type.

The constraint is also used as a contextual type, so it can affect type inference for arguments (which can in turn influence inference of `T` itself).  In fact this is a big reason for why `const` type parameters were introduced - they imply `as const` on any passed-in object literals via the same contextual typing machinery.

**Comment by jcalz** [comment]
TS quite often widens generics to their constraints inside generic functions. This has nothing to do with `const` or `as const` though.  Possibly you want something like `Object.values(t as Record<string, T[keyof T]>)`, to guide TS's behavior. But this isn't a bug in TS, as far as I can tell.

**Comment by rotu** [comment]
So how do I allow the `extends` constraint to *only* narrow the type and not widen it?

A couple other attempted workarounds: even if I use a mapped type or intersection type, it seems to ignore the type parameter `T`:

```ts
const obj = {"1":"one"} as const

type Obj = typeof obj
function f6<const T>(t: T) {
    type S = { [s in keyof T]: T[s] } 
    return Object.values(t as S)
}
const a6 = f6(obj); // unknown []
//    ^?

function f7<const T>(t: T) {
    type S = T & { [k in string]: unknown } 
    return Object.values(t as S)
}
const a7 = f7(obj); // unknown []
//    ^?

function f8<const T>(t: T) {
    type K = keyof T
    type V = T[K]
    return Object.values(t as Record<K,V>)
}
const a8 = f8(obj); // unknown []
//    ^?

```

**Comment by jcalz** [comment]
> So how do I allow the `extends` constraint to *only* narrow the type and not widen it?

I don't understand this question, sorry.  If you're trying to narrow from `T` to something `Object.values()` will see as satisfying the overload with the generic call signature, then maybe `T & Record<string, T[keyof T]>`.    In any case, I don't think this is a forum for such a discussion so I'm going to disengage now.

**Comment by rotu** [comment]
You're right. `T & Record<string, T[keyof T]>` does make `Object.values` come out right. It's also a fundamentally different type (for example `keyof` that object is `string`, not `"1"`)

The original intention is to create a function that passes the argument through to `Object.values` with its type intact. Adding an index signature causes code to completely *ignore* the typed properties for purposes of `Object.value`.

I think my original confusion is that `Object.values` uses the generic overload for object literals only because of the [implicit index signature](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#implicit-index-signatures) (see also #7029). But the `extends` clause (needed for `Object.values`) clobbers that index signature.

**Comment by RyanCavanaugh** [comment]
This seems to be a misunderstanding of what the `const` modifier does. It doesn't change the return type inference for `f1`; it only has effects at call sites

**Comment by rotu** [comment]
@RyanCavanaugh Yes, that's true, I'll reword the issue so that it doesn't implicate `const`.

**Comment by rotu** [comment]
@RyanCavanaugh Alright I rewrote it. There is a lot of confusion here on my part - as you point out, `const` is not at fault here. I'm sure this has something to do with the semantics of index signatures and maybe with the slightly weird signature of Object.values.

**Comment by RyanCavanaugh** [comment]
The relevant signature of `Object.values` here is
```ts
   values<T>(o: { [s: string]: T; } | ArrayLike<T>): T[];
```
If you write out the return value into a temp:
```ts
function f2<T extends {}>(t: T) {
    const p = Object.values(t);
    p;
}
```
During inference we don't have anything to line up `[s: string]: T]` for, so `T = unknown` -- this is a fallback effect from collecting zero candidates. Once `T` has a constraint, then there's something to match, and the expected result occurs. `f4` then flips back to `unknown` because `T[k]` isn't a capturable inference candidate (it depends on `k` which would be lexically free in the inference result).

The only reasonable fix would be to synthesize `[k in any]:T[keyof T]` or some equivalent during the inference process, and it doesn't seem like that's worth it given that the result isn't unsound.
