### ISSUE TITLE
Recursive mapped type with callable signatures not working correctly.

### ISSUE THREAD

**Issue by miguel-leon** [microsoft/TypeScript#58732]
### 🔎 Search Terms

recursive mapped type callable signature

### 🕗 Version & Regression Information

Present in latest version today v5.4.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAglC8UDeUCGAuKAKAlAgfMlAEaYB2ArgLbEQBOUAvkwNwBQHokUAGgkagD8mXASLFhUSjXpNWbLtACa-AAqo6wAJaoANrpABJKmF0QqEMsAgATADwx87RVAD6ajdr0Hjp85et7UXhCFAB6MKgtK3oLGx1rKAgADzBUMgBnLQB7MjYoApJyalo6dkZ8BXBoAC1+JHzCoUwkZgAybGDQxsLCiWKZBgAfKAoyGwgAM2jbdl7GPBGxiemyWbZGdg5JsYBjbVyoSbIARiwMXjxWth2yfZyyI7IAJnPMJSvGG72Dx+OAZjeUBqnw4N1OWBQFy62BQAHc6LkAOauMCIyCaECYAAMTDwCxYUAiSToiLoABooEjstkbODXlCRHgQrCoAjkaj0fRQDi8XjCcS0hkMhAMpTiKg6QDIWgmWIZeyyCi0dkMTyoLiFvyiZF6GTKdTaWDONUoOpNDp9EYTGYLDF7AAVQiIBoASAA2gBrKKPT0QEDZSZQB0AXUk5q8Vt8toCtjsDq9IacGygHRgGQjlp8Nv89oAYj8HvHk1VuOnM95rX47YEC3dfsWEGxXQ6kslrOMMtgAHS9jRIjKYaKTWQwOgD5mEYeyABKEGAFDoj0EzddWF73f7g9g44yk7NnizVZj9rsc4XS8I6FXY09ZGycLI7CAA

### 💻 Code

The intention is to map the type `{ a: () => { b: number } }` into something like `{ a?: () => { b?: number } }`, i.e., a recursive partial that preserves callable signatures on which the return types are also mapped to recursive partials.

The following utility type accomplishes such thing. It preserves callable signatures with an intersection because I believe there's no other way of doing it along with mapped types in your language.

```ts
type PartiallyImplemented<T> = {
	[k in keyof T]?: PartiallyImplemented<T[k]>;
} & AsPartiallyImplementedFunction<T>;

type AsPartiallyImplementedFunction<T> =
	T extends (...args: infer Args) => infer Return ?
		(...args: Args) => PartiallyImplemented<Return> :
		unknown;
```

The compiler (hovering in playground) says it expands to the following type which is relativetely correct and most importantly typechecks correctly.

```ts
PartiallyImplemented<{ a: () => { b: number } }>
===
{
    a?: {} & (() => {
        b?: number | undefined;
    }) | undefined;
}
```

The problem is it only works if I literally copy and use the expanded type, i.e., using the utility type itself doesn't typecheck correctly.
So, the same two types are behaving in different ways, hence the bug 🐛.

```ts
function fn1(a: PartiallyImplemented<{ a: () => { b: number } }>) {}
function fn2(a: { a?: {} & (() => { b?: number | undefined; }) | undefined;}) {}

fn1({ a: () => ({ wrong_property: 0 }) }); // passes, bad
fn2({ a: () => ({ wrong_property: 0 }) }); // error, good 
```

PS: I also tried a slighly different utility type, to not intersect with `unknown` and to try not to with `{}`. The result is exactly the same: [playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAglC8UDeUCGAuKAKAlAgfMlAEaYB2ArgLbEQBOUAvkwNwBQHokUAGgkagD8mXASLFhUSjXpNWbLtACa-AAqo6wAJaoANrpABJKmF0QqEMsAgATADwx87RVABa-JGyje0krP7x4Qk8fUJJJaVoGAB8oCjIbCAAzLTJbdlDGPAAyZCyoWPjElLSbdkZ2DiT4gGNtAHsyKCSyAEYsDF48JEY2arI6rUbmsgAmDswlbt7+weGWgGYJt2mOPrasFE7RIOwUAHc6RoBzAH0wI8hNEEwABiY8LJYoAHoXqHojugAaKGP6+o2dbjLYiQKETZQQ4nc6XeigO4PB7PN5QMCoADOGIgGN+xFQQMWkO24L2UKOZDOF3qVwRUHu+Ser3en3qPz+AKBawU4Gg6k0On0RhMZgsVlsdgAKoREJKPgAPawJDHILw+LAAOi1GmOGMwqSSshgdF1OH1ZENDAAShBgBQ6GRylBBKrQprtSa9bBPWaoPztHoDMZTOZLNZ7Da7Q6nGxmLkQj4ANoAaygqSgyYgIHqSSgkoAupJ-YKgyLQ+L7JKU-mY8xMAnvCm001M9ncwWixoA0Lg6KwxKq8ma+V2EA)

```ts
type PartiallyImplemented<T> = T extends {
    (...args: infer Args): infer Return;
} ? {
    (...args: Args): PartiallyImplemented<Return>;
} & {
    [k in keyof T]?: PartiallyImplemented<T[k]>;
} : {
    [k in keyof T]?: PartiallyImplemented<T[k]>;
};
``` 

### 🙁 Actual behavior

Typechecks incorrectly.

### 🙂 Expected behavior

Typechecks correctly.

**Comment by ahejlsberg** [comment]
I haven't analyzed why your formulation isn't working, but this simpler type seems to do the trick:

```ts
type PartiallyImplemented<T> =
    T extends (...args: infer A) => infer R ? (...args: A) => PartiallyImplemented<R> :
    T extends object ? { [K in keyof T]?: PartiallyImplemented<T[K]> } :
    T;
```

**Comment by miguel-leon** [comment]
@ahejlsberg, of course that wouldn't work with a type that is both callable and has properties like `{ a: { (): number; b: string } }`.
To be clear, the issue is not how to achieve the mapping with a workaround type, is that two supposedly equal types don't work the same.

**Comment by ahejlsberg** [comment]
I did a little digging, and the issue you're running into is a bit subtle. Types where all properties are optional are called "weak types" and we error when a weak type has no properties in common with a type being assigned to it. For a variety of reasons that check only happens at the top level in intersection types and is disabled in checks of contained member types. That's what's happening in your example. The reason it works when you manually write out the type is that an explicitly written `{}` in an intersection with another object type is optimized away, so no intersection actually results.

Here's a formulation of the type that works, even for types with both call signatures and properties:

```ts
type PartiallyImplemented<T> =
    (T extends (...args: infer A) => infer R ? (...args: A) => PartiallyImplemented<R> : unknown) &
    (T extends object ? keyof T extends never ? {} : { [K in keyof T]?: PartiallyImplemented<T[K]> } : T);
```

Note the `keyof T extends never ? {} : ...` check to use an explicitly written `{}` for objects with no properties such that the intersection is optimized away.

**Comment by miguel-leon** [comment]
I guess as usual, there's the recital of buzz names and the variety of reasons of why they (ought to?) behave in the undocumented unexpected ways they do, along with the new name for bugs: Design Limitation. And it ends up coming down to using workarounds/hacks/gymnastics.

An answer like "yes, two equal types shouldn't behave differently, this is a bug but it is too difficult to resolve" would've been perfectly understandable. Instead it always sounds like an attempt at justification combined with gaslighting.

But it's alright, Typescript is a gift and nobody can make any demands. It's just that the pitch gets a little tiring.
I know I'm no one to be saying these things, I'm just venting a little.
This is not particularly directed at you, please forgive that is you on the other end.

I understand all the complexities and that we are all humans after all.

Thanks for your response and for the workaround ✌️.

**Comment by ahejlsberg** [comment]
> An answer like "yes, two equal types shouldn't behave differently, this is a bug but it is too difficult to resolve" would've been perfectly understandable. Instead it always sounds like an attempt at justification combined with gaslighting.

Hopefully my explanation will be useful to someone else.

**Comment by fatcerberus** [comment]
I for one have always liked that the TS team is transparent about their implementation and the limitations it brings.  It’s something you don’t see often and is refreshing.

There’s nothing wrong IMO with a developer explaining to other developers (since TypeScript *is* a compiler after all) exactly why things are the way they are, as long as it’s done in good faith, and as far as I’ve been able to tell, it usually is.

**Comment by miguel-leon** [comment]
I'm sorry, there's been a missunderstanding. I hadn't realize this explanation (and others in other issues) was for the sake of transparency. My bad, I'm all up for transparency.
I always thought of them like sort of turning a blind eye or deflecting that there's was a real bug.
I understand now. Thank you.
Hopefully there's desire in the future to overcome these limitations.
