### ISSUE TITLE
Promise<T> where T is an object allows additional keys on T

### ISSUE THREAD

**Issue by mildfuzz** [microsoft/TypeScript#58744]
### 🔎 Search Terms

Promise, Promise Generic

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=3.3.3#code/C4TwDgpgBAKhDOwoF4oG8CGAuKiBOAlgHYDmAvgFAUDGA9kYlNrAkqpjgOQacA0UUAEZdBnSlToMkwqAAU8tALYF4EADxxEAPhRyFy1QDo8CWgBsAbhAAUHKNz4CZnUWQCUQA

### 💻 Code

type Test = {a: string}

const a: Test = {a: 'a',  b: 'b'}

const b: Promise<Test> = Promise.resolve({a: 'a',  b: 'b'})

### 🙁 Actual behavior

`const b: Promise<Test> = Promise.resolve({a: 'a',  b: 'b'})` does not highlight error in return type

### 🙂 Expected behavior

`const b: Promise<Test> = Promise.resolve({a: 'a',  b: 'b'})` should show error as `b` does not appear on `Test`

### Additional information about the issue

n/a

**Comment by MartinJohns** [comment]
This is working as intended.

The type for your `resolve` call is inferred by the argument, and then compatibility with the variable type is checked. Additional properties are allowed, objects are not sealed. If you want the excess property check to kick in here you must let TypeScript explicitly know the type of your `resolve` call: `Promise.resolve<Test>(...)`
