### ISSUE TITLE
[TS2742] Occurs building a library that depends on `@reduxjs/toolkit`

### ISSUE THREAD

**Issue by ryuujo1573** [microsoft/TypeScript#58743]
### 🔎 Search Terms

TS2742, redux, rtk

### 🕗 Version & Regression Information

I refered to [this comment from #42873](https://github.com/microsoft/TypeScript/issues/42873#issuecomment-2066874644) and I found that this does not work in `typescript@beta` (5.5.0-beta) as well.

~~And if I try `import * as foo from '../node_modules/@reduxjs/....'` d.ts emission works like a charm.~~
This doesn't work as `d.ts` ends up with empty `export {};`

### ⏯ Playground Link

https://github.com/ryuujo1573/rtk-ts2742-demo

### 💻 Code

```ts
// only this line fixes the problem
import * as _ from "../node_modules/@reduxjs/toolkit/dist/createSlice"
```

### 🙁 Actual behavior

TS2742

### 🙂 Expected behavior

Resolve type definitions from "@reduxjs/toolkit" (`@reduxjs/toolkit/dist/createSlice.d.ts`) properly, and generate types as expected

### Additional information about the issue

reduxjs/redux-toolkit#3962
and this
reduxjs/redux-toolkit#4066
```[tasklist]
### Tasks
```

**Comment by weswigham** [comment]
This was fixed upstream in `@reduxjs/toolkit` - they had some inaccessible internal types that needed to be exported.
