### ISSUE TITLE
Conditional type does not work when generic

### ISSUE THREAD

**Issue by ehmicky** [microsoft/TypeScript#58765]
### 🔎 Search Terms

intersection, empty, generic

### 🕗 Version & Regression Information

This is the behavior in every version I tried (from 3.3.3 to 5.5.0-beta), and I reviewed the FAQ for entries about intersections and conditional types.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.0-beta#code/C4TwDgpgBAggznCAnY84EsDmA7AhgIwBsIAeAVQBooAVKCAD2AmwBM4oyA+KAXhoFgAUENCRYJWnwCu2ANbYA9gHds3PgG8wSBWABcUAAx1GzNjSgB+KMCRTo+gGa5CiAL4BuEeGgwATL1gEZFQELDwiUhgqGBIDTk53KAB6JKgAMVx0FyEvMQAhCQCZeWVVAM1tPUNjJlZ2WisbOyhHZzcoADIodQ9c6Dz-PjRgtDCCYhI8qgK4hOTUgGUpAGNliAg2HMFRaABhQuk5RRU1aoZaswbrW3soJxcIT23vKF3BwMQUUZxx0l2qfazRIpKBLVbrNhAA

### 💻 Code

```ts
type AssertAssignable<U, T extends U> = T

type A<T = unknown> = {prop: 0 extends T ? true : false};
type A2 = AssertAssignable<A, A<0>>; // Fails

type B<T = unknown> = {prop: 0 extends T ? true : false} & {};
type B2 = AssertAssignable<B, B<0>>; // Succeeds

type C<T = unknown> = 0 extends T ? true : false;
type C2 = AssertAssignable<C, C<0>>; // Succeeds
```

### 🙁 Actual behavior

Type `A2` fails with:

```
Type 'A<0>' does not satisfy the constraint 'A<unknown>'.
  Type 'unknown' is not assignable to type '0'.
```

### 🙂 Expected behavior

`A<0>` should be assignable to `A`. I.e. `A2` should not fail.

### Additional information about the issue

`B2` does not fail, i.e. adding `& {}` seems to strangely work around this problem.

`C2` does not fail, i.e. this problem seems to only occur inside object properties.

**Comment by RyanCavanaugh** [comment]
Duplicate #44945

It's looking increasingly likely the only good fix here is going to be introducing an `unreliable` (name???) companion to the `in` and `out` variance markers and let users specify that
