### ISSUE TITLE
Assignment fails with boolean return type and recursive type

### ISSUE THREAD

**Issue by camsteffen** [microsoft/TypeScript#58766]
### 🔎 Search Terms

assign boolean return recursive type

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I tried running every-ts and got an error "Unknown system error -86"

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAsiDCB7AdgMwJYHMoF4oG8AoKKAI0UQBsAFAJ0TAC4yLKIBDZAbmKkWAAWEWnQbMAzsFrpkmHgF8ehUJChI0WAMqQAxgB4AKgD5cUA1AgAPYBGQATcX1IArCDuC8A-ASgBtANJQMlAA1hAgiKhmALrM6hiY2m6GAdEm8rxxKAlJOgBq7JQArhCGRkoq0PFaugXFpcamRCRg9HZFOsLMABQAlLgmBgpKOiiSUDaSAEKsHMhZGom6enDVmCZ4zSxUokwEvCQA9IdQAKIASucA8ucHUK2I7Z20Pf04JjNUc90A5D+9ABpePIgSR+EIRPQ9lsWm0Ol0oH0BlA-qCoBlFIQgA

### 💻 Code

```ts
type MyConfig = {
  boolProp: boolean;
  otherProp: string;
};

type ConfigSpec<T> = T extends object
  ? { [K in keyof T]: ConfigSpec<T[K]> }
  : ConfigSpecValue<T>;

type ConfigSpecValue<T> = {
  producer: () => T;
};

const testBoolean: ConfigSpec<MyConfig> = {
  boolProp: {
    // ERROR
    producer: () => Boolean(''),
  },
  otherProp: {
    producer: () => '',
  }
};
```

### 🙁 Actual behavior

Error output:
```text
Type '() => boolean' is not assignable to type '(() => false) | (() => true)'.
  Type '() => boolean' is not assignable to type '() => false'.
    Type 'boolean' is not assignable to type 'false'.(2322)
input.tsx(10, 3): The expected type comes from property 'producer' which is declared here on type 'ConfigSpecValue<false> | ConfigSpecValue<true>'
```

It seems to treat boolean as special somehow.

### 🙂 Expected behavior

It compiles.

**Comment by fatcerberus** [comment]
You need to disable distributivity for the conditional type: `[T] extends [object] ? …` otherwise you’ll have this problem for any union-typed properties (`boolean` is equivalent to `true | false`)…

**Comment by camsteffen** [comment]
😩 thanks
