### ISSUE TITLE
[Wiki] Breaking changes. TypeScript 3.9. Exports Now Use Getters for Live Bindings. 

### ISSUE THREAD

**Issue by yor-so** [microsoft/TypeScript#58773]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Since wiki can only be fixed by contributors,
The url of the pr that applies that change if broken, please update it.

Broken link: https://github.com/microsoft/TypeScript/pull/359670
Must be: https://github.com/microsoft/TypeScript/pull/35967

**Comment by jakebailey** [comment]
The wiki is PR-able at https://github.com/microsoft/TypeScript-wiki

**Comment by yor-so** [comment]
Then please close this. I'll open a bug ticket in the wiki repo and I'll send a pr.
Thanks.
