### ISSUE TITLE
Incorrect function return type: expected it to match generic type parameter

### ISSUE THREAD

**Issue by thomas-darling** [Microsoft/TypeScript#5877]
I may just be abusing the type system here, but there's no warnings or errors, so I have to assume it should work. I'm trying to dispatch a command to a registered handler and return the result, which should be of the type specified by the command.

Question is, why is the result always of type object, when the type parameter is clearly a string? Is this a bug or known limitation, and if so, is it a bug that there is no error or warning here?

```typescript
interface Command<T>
{
}

class TestCommand implements Command<string>
{
}

function dispatch<T>(command: Command<T>): T
{
    let result: any = "Result of executing the command handler";

    return result as T;
}

let result = dispatch(new TestCommand());
// Why is result of type object? I expected it to be a string.
```

**Comment by mhegazy** [comment]
The problem is that T is never manifested in the object, and since it is a structural type system, setting T to a string without using it has no impact on the inference. if you add a property `p: T` to your interface, your result should be of type `T`, in this case, `string` as you would expect.

**Comment by thomas-darling** [comment]
Ahhh, that makes sense, although it would likely have been a while before I figured that one out on my own - looking at the code it kinda feels like it should just work. But thanks for the quick response, the workaround solved my problem :-)
