### ISSUE TITLE
Inline JSX.Element import for component returning null conditionally

### ISSUE THREAD

**Issue by aminpaks** [microsoft/TypeScript#58770]
### 🔎 Search Terms

isolated declarations, jsx, react element

### 🕗 Version & Regression Information

- This is an auto fix provided for the missing type declaration in 5.5

### ⏯ Playground Link

Sorry, couldn't make it work in the Playground :|

### 💻 Code

```tsx
export function ConfirmationModal() {
  if (Math.random() < 0.5) {
    return null;
  }

  return <div>check</div>;
}
```

### 🙁 Actual behavior

```tsx
export function ConfirmationModal(): import("react/jsx-runtime").JSX.Element | null {
  if (Math.random() < 0.5) {
    return null;
  }

  return <div>check</div>;
}
```

### 🙂 Expected behavior

```tsx
import {JSX} from 'react/jsx-runtime';

export function ConfirmationModal(): JSX.Element | null {
  if (Math.random() < 0.5) {
    return null;
  }

  return <div>check</div>;
}
```

### Additional information about the issue

This issue doesn't seem to happen when the component just returns jsx.

**Comment by aminpaks** [comment]
I'm not actually sure we should have the `JSX` imported or not. It's available implicitly.

**Comment by RyanCavanaugh** [comment]
These are both equally valid, not sure what the intended semantics you're going for here are. Is the rule that we should never use `import` references?

**Comment by aminpaks** [comment]
closing as it's not an issue.
