### ISSUE TITLE
Autocomplete is not reliable with subpath exports

### ISSUE THREAD

**Issue by jansedlon** [microsoft/TypeScript#58777]
### 🔎 Search Terms

- subpath autocomplete
- exports autocomplete
- subpath

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about Export maps aren't respected

### ⏯ Playground Link

https://github.com/jansedlon/ts-monorepo-issue/tree/main

### 💻 Code

```json
{
  "exports": {
      "./package.json": "./package.json",
      "./zod/base": {
        "types": "./dist/src/zod/base.d.ts",
        "import": "./dist/src/zod/base.js"
      },
      "./zod": {
        "types": "./dist/src/zod/index.d.ts",
        "import": "./dist/src/zod/index.js"
      }
    },
}
```

```ts
import { index } from "@ts-monorepo/validation/zod";
//        One level depth is autocompleted    ^
// This works ONLY if there's one level depth export in package.json

import { EmailSchema } from "@ts-monorepo/validation/zod/base.ts";
//                      No autocomplete beyond this ^
// If there's no `./zod` export in `exports`, not even `zod` path is autocompleted
```

### 🙁 Actual behavior

As you can see in the example, my base `tsconfig.json` has `resolvePackageJsonExports` set to `true`.
My packages have `exports` field in `package.json` to export a bunch of things. There are actually two issues.
1. There's no autocomplete beyond one level depth of `exports`.
2. In my production application, there's like 90% chance that any given thing exported from my packages are not suggested for imports. **I have to import it at least once for it to appear later**. And even that is forgotten after some time.

### 🙂 Expected behavior

It should autocomplete all given paths defined in `exports` field.
It should suggest all exported things from a package

### Additional information about the issue

The second issue is tricky because it doesn't happen in this small reproduction.
My app have around 100k LOC and almost all exported things in my packages cannot be autoimported because typescript somehow doesn't know about them.

If i import them once, they can be autoimported later on somwhere else. However after some time (or after vscode reload), it's forgotten again.

**Comment by jansedlon** [comment]
Seems like `"typescript.preferences.includePackageJsonAutoImports": "on"` option in vscode fixed it but I'm not sure what's the performance penalty for this? I already struggle with autocomplete performance.

**Comment by RyanCavanaugh** [comment]
This is the expected behavior with that flag off, and turning that flag on is the correct thing to do
