### ISSUE TITLE
Intellisense stops working after exporting interface

### ISSUE THREAD

**Issue by FranjoMindek** [microsoft/TypeScript#58785]
### 🔎 Search Terms

typescript, intellisense, interface, extends, react, create-react-app, svg

### 🕗 Version & Regression Information

- The issue exists on both versions 4.9.5, 5.4.5
- The issue exists from the start of the project, since the problematic interface was firstly introduced 

### 💻 Code

```ts
export interface SvgIcon {
  icon: React.FunctionComponent<
    React.SVGProps<SVGSVGElement> & {
      title?: string | undefined;
    }
  >;
}

export interface TileOption extends SvgIcon {
  readonly value: string;
  readonly label: string;
  readonly description: string;
}
```

### 🙁 Actual behavior

IntelliSense is loading indefinitely.

![image](https://github.com/microsoft/TypeScript/assets/84568328/5bc509a0-6a30-487d-a8ce-6c0c150bbb12)
![image](https://github.com/microsoft/TypeScript/assets/84568328/6a4fc337-ee4f-436f-8d12-137cc6ec142b)

The problem is also shared by all the team members.
Same thing happens on both VSC and Webstorm.

### 🙂 Expected behavior

IntelliSense is working properly.

### Additional information about the issue

Not exporting the interface fixes the problem:
![image](https://github.com/microsoft/TypeScript/assets/84568328/1982d4fb-6719-449f-8555-a5affe2c624f)

Exporting the interface without extends SvgIcon fixes the problem.
![image](https://github.com/microsoft/TypeScript/assets/84568328/abd075e7-65e7-4325-be72-823d67bc7257)

SvgIcon represents the type of SvgReactComponents generated by create-react-app setup.
![image](https://github.com/microsoft/TypeScript/assets/84568328/705f6521-3b6d-4408-a0ce-575b33d8d45c)

While having organize imports enabled on-save in VSC settings.json, this type also made the VSC get stuck on organizing imports action. However switching import organization to `prettier-plugin-organize-imports` fixed that problem.

Before settings.json:
```
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": "explicit",
  "source.organizeImports": "explicit"
},
```
After settings.json:
```
"editor.codeActionsOnSave": {
  "source.fixAll.eslint": "explicit",
},
```

It's also worth noting that there is no problem when exporting interface extending SvgIcon in separate file.
![image](https://github.com/microsoft/TypeScript/assets/84568328/c901e48a-dd07-4391-a22f-3d88942db42d)

**Comment by RyanCavanaugh** [comment]
We need a repo we can clone to demonstrate the behavior, or otherwise fully-specified user scenario here. Too many other variables at play than just the code snippet
