### ISSUE TITLE
Object is possibly 'null' when using type guard for for loops

### ISSUE THREAD

**Issue by fzn0x** [microsoft/TypeScript#58787]
### 🔍 Search Terms

```ts
if ((uploaded || []).length !== 0) {
  for (let data of uploaded) { // -> this line throws let uploaded: unknown[] | null 'uploaded' is possibly 'null'.ts(18047)
  }
}
```

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Should not throw

### 📃 Motivating Example

-

### 💻 Use Cases

-

**Comment by fatcerberus** [comment]
This is kind of an odd construction.  At any rate TS can't tell that `[].length` is always 0 (it's just checking the `.length` of something with an array type, which in general could be anything) so as far as the compiler is concerned `uploaded` could still be nullish after this check

**Comment by fzn0x** [comment]
Thanks for tracking this as "Design Limitation". 👍
