### ISSUE TITLE
Types of parameters 'property' and 'property' are incompatible. Type 'string | number | symbol' is not assignable to type 'keyof NamingDetail'. 

### ISSUE THREAD

**Issue by ashokReddy00931993** [microsoft/TypeScript#58780]
### 🔎 Search Terms

React app  with typescript version as 4.95 
alling with the following reason; Type '(event: React.MouseEvent, property: keyof FileNamingDetail) => void' is not assignable to type '(event: MouseEvent<HTMLButtonElement, MouseEvent>, property: string | number | symbol) => void'. Types of parameters 'property' and 'property' are incompatible. Type 'string | number | symbol' is not assignable to type 'keyof NamingDetail'. Type 'string' is not assignable to type 'keyof NamingDetail'. 971 | order={order} 972 | orderBy={orderBy}

973 | onRequestSort={handleRequestSort} | ^^^^^^^^^^^^^ 974 | />

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
   table displaying file.tsx     
export type NamingDetail = {
     name: string,
    test: string,
    value: string,
    
};

export interface HeadCell<T> {
    disablePadding?: boolean;
    id: keyof T;
    label: string;
    numeric: boolean;
    width?: string;
}

 const headCells: HeadCell<NamingDetail>[] = [
    {
      id: 'name', numeric: false, label: 'Name', width: '12%'
    },
    {
      id: 'test', numeric: false, label: 'TEST', width: '12%'
    },
    {
      id: 'value', numeric: false, label: 'Value', width: '9%'
    },
    ]
    
    
     const [order, setOrder] = useState<Order>('asc');
  const [orderBy, setOrderBy] = useState<keyof NamingDetail>('name');
  
  
            <CustomTableSort
                headCells={headCells}
                order={order}
                orderBy={orderBy}
                onRequestSort={handleRequestSort}
              />
              const handleRequestSort = (
    event: React.MouseEvent<HTMLButtonElement>,
    property: keyof NamingDetail,
  ) => {
    const isAsc = orderBy === property && order === 'asc';
    setOrder(isAsc ? 'desc' : 'asc');
    setOrderBy(property);
  };
  
  
  ----TableSort.tsx file 
  
  interface CustomTableSortProps<T> {
    onRequestSort: (event: React.MouseEvent<HTMLButtonElement>, property: keyof T) => void;
    order: Order;
    orderBy: keyof T;
  

}

const CustomTableSort: FunctionComponent<CustomTableSortProps<any>> = <T,>({
    onRequestSort, order, orderBy, headCells
}: CustomTableSortProps<T>) => {
    const createSortHandler =
        (property: keyof T) => (event: React.MouseEvent<HTMLButtonElement>) => {
            onRequestSort(event, property);
        };
    return (<> sorting header cell logic</>
  
export default CustomTableSort; 
```

### 🙁 Actual behavior

onRequestSort={handleRequestSort}  it is not accepting the accept the typescript type is as  keyof NamingDetail for the   <CustomTableSort
                headCells={headCells}
                order={order}
                orderBy={orderBy}
                onRequestSort={handleRequestSort} --->error Type 'string | number | symbol' is not assignable to type 'keyof NamingDetail'. Type 'string' is not assignable to type 'keyof NamingDetail'
              />

### 🙂 Expected behavior

onRequestSort={handleRequestSort}  it is should the accept the typescript type is as  keyof NamingDetail for the   <CustomTableSort
                headCells={headCells}
                order={order}
                orderBy={orderBy}
                **onRequestSort={handleRequestSort}** ---->
              />

**Comment by hreinhardt** [comment]
Try changing this line:
```typescript
const CustomTableSort: FunctionComponent<CustomTableSortProps<any>> = <T,>({
```
to this:
```typescript
const CustomTableSort = <T,>({
```

Because you are explicitly specifying the type `CustomTableSortProps<any>` you are preventing TypeScript from correctly assigning the type-variable `T`.

**Comment by RyanCavanaugh** [comment]
This doesn't clearly demonstrate a bug. Please reduce this further and open a new issue.
