### ISSUE TITLE
instanceof has been used and there is a type inference error

### ISSUE THREAD

**Issue by moshuying** [microsoft/TypeScript#58793]
### 🔎 Search Terms

Property 'dispose' does not exist on type 'string | number | boolean | Record<string, any> | Color | ((material: Material) => Material)

### 🕗 Version & Regression Information

![image](https://github.com/microsoft/TypeScript/assets/37231523/64901ca8-b2b6-47b8-97fa-15c49967121a)

### 💻 Code

```ts
export function disposeMaterial(material: THREE.Material) {
  if (material instanceof THREE.Material) {
    for (const key in material) {
      const k = key as keyof THREE.Material
      if (material[k] instanceof THREE.Texture) {
        //@ts-ignore 
        material[k].dispose()
      }
    }
    material.dispose()
  }
}
```

### 🙁 Actual behavior

no error

### 🙂 Expected behavior

no error

**Comment by moshuying** [comment]
I can fix it, but I don't think it's right
```ts
export function disposeMaterial(material: THREE.Material) {
  if (material instanceof THREE.Material) {
    for (const key in material) {
      const k = key as keyof THREE.Material
      const e = material[k]
      if (e instanceof THREE.Texture) {
        // 销毁纹理
        e.dispose()
      }
    }
    // 销毁材质
    material.dispose()
  }
}
```

**Comment by Andarist** [comment]
The upcoming 5.5 release fixes this: https://github.com/microsoft/TypeScript/pull/57847
