### ISSUE TITLE
Add typings for Iterator instance methods: take, find, map, etc.

### ISSUE THREAD

**Issue by vsDizzy** [microsoft/TypeScript#58792]
### 🔎 Search Terms

iterator take

### 🕗 Version & Regression Information

- This is not present in 5.6.0

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&ts=5.6.0-dev.20240606#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCKhwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HUiQ58D0Ii8fLpDKZgj5SWxfPADlQAHJhAA5SASPlBFQAeS+ZHegmdWkgR1QjgUrmkeFATjNOmGWH0KAQiGhwkuNok4uiIgMHGxCyYrA4PCCimSXFg9UaACocRRgZwGLBYBQlTrQABvRQldw0WD4pyo3kARgA3Cu3Dn+msaLuDyUepiUErUGR2JAF8uSiU8BQYK4N2Qt6gLy+ANpfj+-CcKeAC6PKgP+oGrKgLqbiiNAANQnrBYF-gAvooWHSo0VJXJAACOkHJBOjTTrO84BHm8SQEqADMOoHkAA

### 💻 Code

```ts
function* fibonacci() {
  let current = 1;
  let next = 1;
  while (true) {
    yield current;
    [current, next] = [next, current + next];
  }
}

const seq = fibonacci().take(3);
```

### 🙁 Actual behavior

Property 'take' does not exist on type 'Generator<number, void, unknown>'.(2339)

### 🙂 Expected behavior

No error

### Additional information about the issue

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/take

It is not only the take, but all instance methods: map, reduce, find, every, etc.

**Comment by MartinJohns** [comment]
The API is still experimental and only supported by one major engine. Usually at least two major engines should support the API.

**Comment by xiBread** [comment]
There's also already a draft PR for this: #58222
