### ISSUE TITLE
"Move to file" on global code unnecessarily imports/exports, generates invalid code

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#58801]
```ts
// main.ts

interface String {
    malkovich(): string;
}

[|String.prototype.malkovich = function (): string {
    return "malkovich";
}|]
```

1. Select the range.
2. Request "move to a new file"

## Current

```ts
// newFile.ts
import { String } from "./strs";

String.prototype.malkovich = function (): string {
    return "malkovich";
};

// main.ts
export export export export export export export interface String {
    malkovich(): string;
}

export export export export export export 
```

## Expected

```ts
// newFile.ts
String.prototype.malkovich = function (): string {
    return "malkovich";
};

// main.ts
interface String {
    malkovich(): string;
}

**Comment by fatcerberus** [comment]
Wait, it really produces strings of `export` keywords like that?  What the heck.

**Comment by nick-fallon** [comment]
This is very specific to Visual Studio Code dropdown menus. This cannot be reproduced as specified on any other IDE, such as Intellij/JetBrains.

So, it seems to tie in to how the IDE is refactoring things.

**Comment by DanielRosenwasser** [comment]
The logic is provided from TypeScript's language server. It is possible that this is an issue with VS Code, but I don't see any evidence of that yet. It is more likely that JetBrains is providing its own refactorings that are not powered by our language service.
