### ISSUE TITLE
Make TypeScript Compilable to Native Machine Code!

### ISSUE THREAD

**Issue by HarunaMahjong** [microsoft/TypeScript#58808]
### 🔍 Search Terms

native, machine, binary, aot, ahead-of-time

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

[ReasonML](https://reasonml.github.io/en/), a language [compiled to javascript can also be compiled to native binary](https://reasonml.github.io/docs/en/what-and-why). I hope TypeScript could also be compiled to native binary like ReasonML.

### 📃 Motivating Example

Adding the capability to compile to native binary, in addition to replacing and complementing JavaScript as it currently does, could encourage developers to use TypeScript for a wider range of purposes.

### 💻 Use Cases

Adding the capability to compile to native binary, in addition to replacing and complementing JavaScript as it currently does, could encourage developers to use TypeScript for a wider range of purposes.

**Comment by MartinJohns** [comment]
This is out of scope. You checked the point with the "Design Goals", I suggest you to read those design goals again.

Same issue as #27362 and others.

**Comment by AlQubaiisi** [comment]
Ok I will .,
Thx a lot
في سبت، 8 يونيو، 2024 في 7:47 م، كتب Martin Johns ***@***.***

**Comment by finom** [comment]
@AlQubaiisi maybe this will help? https://www.assemblyscript.org/

**Comment by RyanCavanaugh** [comment]
See also #375, etc..
