### ISSUE TITLE
URLSearchParams not accept number as a value

### ISSUE THREAD

**Issue by IncognitaDev** [microsoft/TypeScript#58823]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

The URLSearchParams only accepts a `Record<string, string>`, but a number can be accepted for a value without any problems, why not use a `Record<string, string | number>`, I think this can be more friendly to not force to use a bunch of type casts in code.

If this is ok, I can make this contribuition.

**Comment by MartinJohns** [comment]
Duplicate of #43738.

**Comment by IncognitaDev** [comment]
sorry, thaks for reply.
