### ISSUE TITLE
Bad Link in Handbook

### ISSUE THREAD

**Issue by Think7** [Microsoft/TypeScript#5882]
The documentation on the following page seems to be missing: 
https://typescript.codeplex.com/wikipage?title=https://github.com/Microsoft/TypeScript/issues&referringTitle=Writing Definition (.d.ts) Files 

I found the link on this page: 
http://www.typescriptlang.org/Handbook 

Writing .d.ts files > Guidelines and Specifics > Examples > Please post a comment [HERE] if there's a pattern... 

Thank You :palm_tree:

**Comment by DanielRosenwasser** [comment]
Thanks @Think7, we're in the process of updating the handbook and this should be fixed soon.

**Comment by mhegazy** [comment]
For future references, the handbook has moved to https://github.com/Microsoft/TypeScript-Handbook
