### ISSUE TITLE
Ignored tsconfig when targeting file

### ISSUE THREAD

**Issue by lveillard** [microsoft/TypeScript#58821]
### 🔎 Search Terms

I found this issue but is closed:
https://github.com/microsoft/TypeScript/issues/6591

### 🕗 Version & Regression Information

Always

### 💻 Code

This breaks lint-staged behaviour in monorepos as lint-staged picks individually the staged files before being commited

### 🙁 Actual behavior

running 
```
tsc --noEmit --pretty 
```
targeting an specific folder, ignores the tsconfig. And there is no way to pass it as a project

### 🙂 Expected behavior

Either grab the tsconfig.ts from the current path, or at least dont block us from manually pointing to a tsconfig.file using -project

**Comment by MartinJohns** [comment]
This is working as intended and documented: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

> When input files are specified on the command line, `tsconfig.json` files are ignored.

You want #27379.

**Comment by lveillard** [comment]
Ah YES! Thanks closing this one.
