### ISSUE TITLE
DOM.AsyncIterable not recognized as a valid lib

### ISSUE THREAD

**Issue by thomas-darling** [microsoft/TypeScript#58834]
### 🔎 Search Terms

dom.asynciterable lib

### 🕗 Version & Regression Information

- This changed in commit or PR #56723
- This changed between versions ______ and 5.4.5

### 💻 Code

My `tsconfig.json` file, as I wanted it to look:

```json
{
  "compilerOptions": {
    "lib": [
      "ES2022",
      "WebWorker.ImportScripts",
      "DOM",
      "DOM.Iterable",
      "DOM.AsyncIterable" // This is not recognized as a valid lib
    ],
    "module": "ES2022",
    "target": "ES2022",
    etc...
  }
  etc...
}
```

### 🙁 Actual behavior

[This line in es2022.full.d.ts](https://github.com/microsoft/TypeScript/blob/main/src/lib/es2022.full.d.ts#L6C1-L6C42) indicates there should be a lib named `DOM.AsyncIterable` - but when I try to add that to my own set of libs in my `tsconfig.json` file, it says no such lib exists.

### 🙂 Expected behavior

I was under the impression that all the libs referenced in those `*.full.d.ts` files should also be available for use individually - meaning that I should be able to specify `DOM.AsyncIterable` as a lib in my `tsconfig.json` file.

### Additional information about the issue

The documentation for libs in general is extremely lacking, and really needs to be improved.

**Comment by fatcerberus** [comment]
Just to be clear, is this a full-on compile-time error, or is it only your IDE (VSCode?) saying it’s not valid?  Because if it’s the latter then it would just mean the JSON schema VSCode is using hasn’t been updated yet.

**Comment by thomas-darling** [comment]
It's both, actually - and it's a little weird.

VS Code highlights it as a schema violation:

<img width="994" alt="image" src="https://github.com/microsoft/TypeScript/assets/6388663/8c924f87-c1e9-44e2-a37d-2b75f841524c">
&nbsp;

But the error it shows is slightly different from what it shows for some random, non-existent lib name:

<img width="984" alt="image" src="https://github.com/microsoft/TypeScript/assets/6388663/6f52c4f6-bd02-49b2-ba6f-04e00b9c0a95">
&nbsp;

If I add it anyway, the build fails with _lots_ of errors that are completely unrelated to this particular lib, as if the whole tsconfig just somehow breaks. But despite all these errors, it does _not_ log anything about the libs being invalid, which could make this a fairly confusing developer experience...

<img width="1258" alt="image" src="https://github.com/microsoft/TypeScript/assets/6388663/05d399af-fe34-447b-a66c-e0624d685773">
&nbsp;

And finally, if I remove that one lib, all the errors go away:

<img width="1255" alt="image" src="https://github.com/microsoft/TypeScript/assets/6388663/83491f4f-708f-4e83-8d89-bead7501cd04">
&nbsp;

Here's my tsconfig.json file, and the file it extends:

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "src",
    "lib": [
      "ES2022",
      "WebWorker.ImportScripts",
      "DOM",
      "DOM.Iterable",
      "DOM.AsyncIterable"
    ],
    "module": "ES2022",
    "target": "ES2022",
  },
  "include": [
    "src"
  ]
}
```
```json
{
  "compilerOptions": {
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitOverride": false,
    "noPropertyAccessFromIndexSignature": false,
    "noUncheckedIndexedAccess": false,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "removeComments": false,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "strictPropertyInitialization": false,
    "strictFunctionTypes": false,
    "stripInternal": true,
    "useDefineForClassFields": false,
    "useUnknownInCatchVariables": false,
    "exactOptionalPropertyTypes": false,
    "plugins": [
      {
        "name": "typescript-tslint-plugin",
        "alwaysShowRuleFailuresAsWarnings": false
      }
    ]
  },
  "exclude": [
    "**/~*"
  ]
}
```

**Comment by fatcerberus** [comment]
Those errors are definitely bizarre, but it looks like they're all coming up while running TSLint; TSLint has been deprecated since 2019; I expect the TS devs would tell you that it's not officially supported and you should have switched to ESLint by now.

https://palantir.github.io/tslint/

> :warning: TSLint [has been deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) as of 2019. Please see this issue for more details: [Roadmap: TSLint → ESLint](https://github.com/palantir/tslint/issues/4534). [typescript-eslint](https://typescript-eslint.io/) is now your best option for linting TypeScript.

**Comment by thomas-darling** [comment]
Sorry, I just updated my comment - seems the errors are something else
