### ISSUE TITLE
Type guards do not flow when used as callbacks

### ISSUE THREAD

**Issue by Eazash** [microsoft/TypeScript#58855]
### 🔎 Search Terms

inference
type guard
callback
type predicate

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about inference of type predicate from type guards

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.1-rc#code/C4TwDgpgBAYglgZwBZQLxQN5QQdzgWwC5tgAnOAOwHMoBfAbgChRIoAhOUgEzUygDMANiGIIylGg0aN+AVwoBjYHAD2FKInjIAFJGDEtKAD7tOXAJTE9GhLEQoMjKFFIRgs0uoDkuAl43qeoy00gpqYlB6AEwG9lAmHNy8WL5EUF6AvBuAZTv+tFAAhraG8abcTDLySqrq+G5IKlwAPAAqAHzaTlBUbsAQpMTa5mitUM0ANIxDjs6u7p5dPX2DwaHhwJFuAJIIhgDM6LXA9Vzag6gjmva6blHm5owA9A+j4NB9pCqkjHD8UNfA2z2U06YQoCBUgggADpBCoqP8olDUuYmLQgA

### 💻 Code

```ts
type Fish = { swim: string };
type Bird = { fly: string };

function isFish(pet: Fish | Bird): pet is Fish {
  return 'swim' in pet
}

const petObj: Fish | Bird = { swim: '💦' } as Fish | Bird;

function method<T>(
  getter: () => T,
) {
  return getter()
}

const petIsFish= method(()=> isFish(petObj))
// Type error
if (petIsFish) {
  console.log(petObj.swim);
  // Property 'swim' does not exist on type 'Fish | Bird'.
}
```

### 🙁 Actual behavior

The type of `petObj` remains `Bird | Fish`

### 🙂 Expected behavior

The type of `petObj` is narrowed to `Fish` as the `isFish` type guard is being used

**Comment by RyanCavanaugh** [comment]
Type predicates like `pet is Fish` aren't standalone types, so they can't inhabit `T`. We'd need some other kind of type here that was something like `petObj is Fish` and instantiate that for `T` in `method` for this to work, but that would be a separate feature.
