### ISSUE TITLE
Map containing array with strict nullable doesn't work right

### ISSUE THREAD

**Issue by delosford** [microsoft/TypeScript#58860]
### 🔎 Search Terms

map containing array may be null or undefined 

### 🕗 Version & Regression Information

This is the current behavior even in 5.5.1-rc

### 💻 Code

```ts
function itsaFunction()
{
	let someMap = new Map<(String | null), (Array<String> | null)>();
	const someString = "someString";

	if (someMap.get(someString) !== null && someMap.get(someString) !== undefined)
		console.log(someMap.get(someString)[0]);

}
```

### 🙁 Actual behavior

Compiler complains that the result of the Map.get operation could be null or undefined

### 🙂 Expected behavior

The null and undefined check should be recognized as ensuring that the Map.get operation does not return a null or undefined.

### Additional information about the issue

I posted a similar issue recently about multidimensional arrays, but that was solved by 5.5.0 beta/5.5.1-rc.  This problem is not solved by them.

**Comment by fatcerberus** [comment]
`.get(someString)` from the perspective of the compiler is just another method call.  There’s no way for it to know it returns the same result every time.  So you can’t narrow it that way, and I probably wouldn’t write the code this way anyway.  Call `.get()` once, assign the result to a variable, and narrow that.

**Comment by RyanCavanaugh** [comment]
+1 to the above comment. I'm not even sure *given* the capability, we would do it -`Map`s are mutable and the key being there on one call isn't a guarantee it's there in another call. FWIW there's another open feature request which I can't find (because the keywords are useless) about using `has` as a narrowing method for subsequent `get` calls.

**Comment by jakebailey** [comment]
That'd be #13086 and kinda #9619.
