### ISSUE TITLE
Add k  command-line flag to allow user specify the module option on their  tsconfig.json file at build time.

### ISSUE THREAD

**Issue by timothyAgevi** [microsoft/TypeScript#58871]
### 🔍 Search Terms

flag, options,module

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

would love PR https://github.com/microsoft/TypeScript/pull/58868 to be reviewed and merged.

### 📃 Motivating Example

-It  a bad practice manually editing the tsconfig,json file ,however sometimes situations can force one to do so when they need to change the module option from maybe module to commonJs or whichever. So why not give developers power to decide their module option at build time? 

### 💻 Use Cases

1. What do you want to use this for?
-Specify module option within the tsconfig,json file at build time.
2. What shortcomings exist with current approaches?
-current approach of manually editing tsconfig.json file is prone to error and fails to adhere to best practise. 
3. What workarounds are you using in the meantime?
-have a -k flag used alongside the tsc init command e.g tsc init -k cm  to specify commonJs or whichever other module option to be used within the project.

**Comment by RyanCavanaugh** [comment]
You can write `tsc -p tsconfig.json --module commonjs`, etc.. Commandline-provided flags will override those in the tsconfig.

**Comment by timothyAgevi** [comment]
Well noted, though this one just modifies the module option at build time, unlike tsc -p tsconfig.json --module commonjs which has to be entered after tsconfig.json has already been generated.

lastly, just a clarification which tsconfig are you referring to is it this repositories tsconfig or users' tsconfig while they use typescript?

**Comment by RyanCavanaugh** [comment]
If you want to modify the tsconfig JSON before running, I'm sure there are ways to accomplish that programmatically that don't need to involve tsc itself doing that modification.
