### ISSUE TITLE
TypeScript 5.5 "Control Flow Narrowing for Constant Indexed Accesses" is not working

### ISSUE THREAD

**Issue by Alexsey** [microsoft/TypeScript#58883]
### 🔎 Search Terms

5.5 Control Flow Narrowing for Constant Indexed Accesses

### 🕗 Version & Regression Information

- This is a crash - No
- This changed in [commit](https://github.com/microsoft/TypeScript/pull/57847)
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.1-rc#code/C4TwDgpgBA0lC8UDkAPJUA+yRIFC9EigHkEoBvXKaqFALigDsBXAWwCMIAnXAX3wAmEAMYAbAIZdowgPaMAzsCgBrBjFxCxk6XMVQZDYvgCWAMygAKZVGON9ASgpUashTNEQAdKJkBzCzIA2soAuvZ8QA

### 💻 Code

```ts
type K = 'x' | 'y'

type O = {
    x: number
}

declare const k: K
declare const o: O

if (k in o) {
  // Element implicitly has an 'any' type because expression of type 'K' can't be used to index type 'O'.
  // Property 'y' does not exist on type 'O'.(7053)
    console.log(o[k])
}
```

### 🙁 Actual behavior

The error is present in the v5.5.1-rc. The error text:
```
Element implicitly has an 'any' type because expression of type 'K' can't be used to index type 'O'. Property 'y' does not exist on type 'O'.(7053)
```

### 🙂 Expected behavior

The error should've been [resolved](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#control-flow-narrowing-for-constant-indexed-accesses) in the TypeScript 5.5

**Comment by MartinJohns** [comment]
What makes you think this should work? Neither the commit nor the blog mentions the `in` operator.

**Comment by Alexsey** [comment]
@MartinJohns you are correct, I mistakingly assumed a broader feature scope. Anyway, considering [this logic](https://github.com/microsoft/TypeScript/pull/57847#issuecomment-2161523143) TypeScript cannot guess a better type for `O[k]` then `unknown`
