### ISSUE TITLE
Support project-only exports

### ISSUE THREAD

**Issue by MichaelMitchell-at** [microsoft/TypeScript#58891]
### 🔍 Search Terms

project only exports isolated declarations

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Introduce a keyword/syntax for declaring that an export should only be visible to other files within the same project. Ideally this would also cause the export to be elided from declaration emit which would also allow it to be exempt from the requirements of isolated declarations.

### 📃 Motivating Example

Use cases:
- Exports only used in tests, e.g. mocking, stubbing .
- Relieve some of the burden of providing explicit type annotations for more complex types which are only used internally within a project.
- Potential to optimize dependency graph of composite projects: If A depends on B which uses C internally, A should be able to start typechecking if declarations for B have been emitted without waiting for declarations of C to be emitted (There would need to be follow-up tooling be built that can perform such an analysis. Right now the build system we use naively assumes that type dependencies are transitive).
- May address https://github.com/microsoft/TypeScript/issues/41425 if equivalent JSDoc tag is provided.
- May help with a subset of the cases where https://github.com/microsoft/TypeScript/issues/46011 might be an issue.

### 💻 Use Cases

1. See above
2. n/a
3. Wrap exports in a `class` and make them `private`. Other files in the project can access the `private` member via `index['_notation']`. Other projects can still technically access the members but they will be typed as `any`.

**Comment by fatcerberus** [comment]
Similar issues: https://github.com/microsoft/TypeScript/issues/58250, https://github.com/microsoft/TypeScript/issues/41316, https://github.com/microsoft/TypeScript/issues/5228, and maybe https://github.com/microsoft/TypeScript/issues/35554

**Comment by MichaelMitchell-at** [comment]
Actually I think `@internal` jsdoc tags with the `"stripInternal": true` tsconfig setting accomplish what I'm looking for.
