### ISSUE TITLE
`ts` object has no properties when loading typescript.js in a browser with v5.5-rc

### ISSUE THREAD

**Issue by lauraharker** [microsoft/TypeScript#58893]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

This came up after sending the initial Google v5.5-beta feedback in https://github.com/Microsoft/TypeScript/issues/58685 since I was just looking at build failures for that feedback.

Apologies if this isn't an officially supported way of using the TypeScript compiler or not - most of the docs I can find are specific to running the compiler via Node.

Google has some internal web apps that load the bundled TSC from https://github.com/microsoft/TypeScript/blob/v5.5-rc/lib/typescript.js file in a browser. One example use case is a tool similar to https://www.typescriptlang.org/play/.

In TS 5.5 these apps break at runtime because they call methods on the global `ts` object like `ts.createLanguageService`, but `ts` is now just an empty object with no properties. I narrowed this down to the bundling changes in https://github.com/microsoft/TypeScript/pull/57133. Here's typescript.js before & after:

[v5.4.2](https://raw.githubusercontent.com/microsoft/TypeScript/v5.4.2/lib/typescript.js):

``` js
var ts = (() => {
  // lots and lots of code
  return require_typescript();
})();

if (typeof module !== "undefined" && module.exports) { module.exports = ts; }
```

[v5.5-rc](https://raw.githubusercontent.com/microsoft/TypeScript/v5.5-rc/lib/typescript.js):

``` js
var ts = {}; ((module) => {
// lots and lots of code
module.exports = __toCommonJS(typescript_exports);
// even more code
})(typeof module !== "undefined" && module.exports ? module : { exports: ts });
if (typeof module !== "undefined" && module.exports) { ts = module.exports; }
```

I'd assume that in v5.5-rc, `ts` was intended to be instantiated via passing `{exports : ts }` as the `module` argument to this IIFE, causing the exported functions that are put on `module.exports` to also be defined as properties on `ts`. Instead the `module.exports = __toCommonJS(typescript_exports);` assignment just overwrites `ts` in `{exports: ts}` and `ts` is just an empty object.

**Comment by jakebailey** [comment]
Ugh, I thought this was tested.

Apparently our browser test only tests that the code executes, not that it actually declares a working global. Will fix this ASAP.

**Comment by jakebailey** [comment]
Note that I wouldn't 100% consider this supported; it's possible that this loading method may go away in a PR like #58419. But, there's not one form that works for both without going through a bundler or esm.sh or something.

**Comment by lauraharker** [comment]
Thanks for the quick fix & additional context @jakebailey! We can certainly switch to loading tsc as an ES module in browsers if/when that lands

**Comment by fatcerberus** [comment]
@hossain666 Please stop posting spammy comments everywhere
