### ISSUE TITLE
VSCode JavaScript/TypeScript Intellisense show WRONG ICON

### ISSUE THREAD

**Issue by LdoDoeg222** [microsoft/TypeScript#58892]
# VSCode TS Intellisense Bug

Does this issue occur when all extensions are disabled?: **Yes**/No

# Description
When I import a class/interface/type when using the JS/TS intellisense, the logo will not appear as expected.
It's not a fatal error, but it's annoying to me.

# Enviroment

- VS Code Version: 1.90.1
- OS Version: Windows 10
- Extensions: @builtin JS/TS support

# Reproduction

- Init a JS/TS project or use repo: https://github.com/LdoDoeg222/VSCode-ts-import-issue
  - Use repo
    - Code yourself
      1. Type to use a class/interface/type and you can see: the intellisense will support a c/i/t with correct logo.
      2. Import the c/i/t then use it, and you can see: the logo of c/i/t will change to a var logo, which infers to (alias) c/i/t Xxxx
    - Use snippet
      1. Use snippet "test", "test2", "test3" to reproduce the bug.
  - Make an enviroment of the project by yourself, then code yourself.v (install some package, or write some class/interface/type code in a file)
    1. Type to use a class/interface/type and you can see: the intellisense will support a c/i/t with correct logo.
    2. Import the c/i/t then use it, and you can see: the logo of c/i/t will change to a var logo, which infers to (alias) c/i/t Xxxx

I try `export {<interface>}`, `export default <interface>`, `export interface <interface>`, `export default interface <interface>`, but all of them are wrong.
Except `declare interface <interface>` first, but it will cause ts2404 error if I don't use default export.

It seems that the problem is caused by the import alias.
- `import {<interface> [as <alias>]} from '<path>'`
- `export { <interface> [as <alias>] }`

Both of the sentences use aliases (even if they may not be used), the logo will change to a var logo as soon.

# What Expected

Expect: When i use a class/interface/type import, even if i use alias import (like `import type { AxiosResponse as AResp } from 'axios'`), I can see the correct logo.

This is the expected result, the logo is correct.
![interface-without-import](https://github.com/microsoft/vscode/assets/42036737/1066ff5e-535c-42b2-8d9a-f9dc4e35da11)

This is the actual result, the logo is wrong.
![(alias)-interface-with-import](https://github.com/microsoft/vscode/assets/42036737/8ec051ed-85bb-4a52-8c52-99a7fe6431a9)

This is the expected result, the logo is correct.
![local-interface-without-import](https://github.com/microsoft/vscode/assets/42036737/60afafc0-dc82-4061-b60c-38a42748c45c)

This is the actual result, the logo is wrong.
![(alias)-local-interface-with-import](https://github.com/microsoft/vscode/assets/42036737/7ceab219-fdb8-4a7b-9387-e2cad1d515ae)

What the develop tools show:
![expected-logo](https://github.com/microsoft/vscode/assets/42036737/adaac981-9e71-4aa8-8f79-4042d5fc39f5)
![actual-logo](https://github.com/microsoft/vscode/assets/42036737/d259f5dd-30c8-468a-aee4-98d51fcbced9)

**Comment by RyanCavanaugh** [comment]
Duplicate #45111
