### ISSUE TITLE
angle brackets formatting problem

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5890]
```
// given
export type All = Map<
    number, {
        type: zit.Type;
        index: number;
    }
>;
```

```
// actual
export type All = Map<
    number, {
        type: zit.Type;
        index: number;
    }
    >;
```

```
// expected
export type All = Map<
    number, {
        type: zit.Type;
        index: number;
    }
>;
```

**Comment by DanCorder** [comment]
@SaschaNaz has made a lot of changes to import and export formatting on #4609 that appear to fix this.
I checked out the fixImportExportFormatting branch from https://github.com/SaschaNaz/TypeScript, made a test for this exact case and it passed.

**Comment by SaschaNaz** [comment]
@DanCorder I checked out the branch with a bit surprise but I don't see this fixed. Maybe a comment on a wrong issue?

**Comment by DanCorder** [comment]
@SaschaNaz Sorry, you are correct. This is the issue I meant to comment on, but my test was broken. This is still an issue.

**Comment by DanielRosenwasser** [comment]
Thanks @saschanaz!
