### ISSUE TITLE
Generic index into two types not seen as assignable, even if the two types are identical for all relevant keys

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript#58905]
### 🔎 Search Terms

generic, indexed access, supertype

### 🕗 Version & Regression Information

- This changed between versions 3.3 and 3.5
- This changed in commit or PR #30769, probably

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240617#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnJwBcyAzmFKAOYA0+yARiSAK4C2D0uAvrrqJFiIUAIThRkEAB6QQAE1JpMOeghINMAGwhwQPPjBYgEYYOhCNxAHgDSkmRHmKA1hACe6GMjFQAfAApnEhsaZAA3Eh8AbRsAXQBKHGReXENjU3NkGExbe1kFZFcPLwx0AKDkEPCSUpiElQIGcUDQsPj9IA)

### 💻 Code

```ts
interface Foo {
  a: string,
  b: number
}

interface Bar extends Foo {
  c: boolean
}

function bar<K extends keyof Bar>(k: K, v: Bar[K]) { }

function foo<K extends keyof Foo>(k: K, v: Foo[K]) {
  bar(k, v) // error!
  //     ~
  // Argument of type 'Foo[K]' is not assignable to parameter of type 'Bar[K]'.
  //   Property 'c' is missing in type 'Foo' but required in type 'Bar'.(2345)
}

```

### 🙁 Actual behavior

`bar(k, v)` fails because `Foo[K]` is supposedly not assignable to `Bar[K]`.

### 🙂 Expected behavior

`bar(k, v)` should succeed because `Foo[K]` is identical to `Bar[K]`; the only difference between `Foo` and `Bar` occurs in a key that `K` can never be.

### Additional information about the issue

This is presumably a design limitation introduced with #30769. And while it's similar to #32693, it's different enough that I'd like to see an official word about it. If there is an existing issue that's the same as this, I didn't find it. Can anyone find one this duplicates?  I'm investigating [a SO question](https://stackoverflow.com/q/78634435/2887218) and while I feel certain I've seen this before, I keep hitting things like #32693 which aren't about generics at all.

On the face of it, if `Pick<Foo, KC>` and `Pick<Bar, KC>` are identical, then for generic `K extends KC`, `Foo[K]` and `Bar[K]` should also be identical. Yes, if `K` turns out to be a union, then you run into the soundness issue that #30769 fixed. We already allow `T[K]` to be assignable to `T[K]` if `K` is generic, so it's not really *soundness* that's at play here.... we've already decided that generic keys are a way of sidestepping this (I'm looking at you, #47109).  I'm guessing it's just not worth the performance hit to check assignability of *parts* of the source and target object types, so it's a design limitation?  Maybe?

**Comment by RyanCavanaugh** [comment]
> the only difference between Foo and Bar occurs in a key that K can never be.

How does one arrive at this conclusion except via exhaustive analysis of possible values of `K`? Note that from TS's perspective, this example isn't any different from one with
```ts
interface Foo {
  a: string,
  b: number,
}

interface Bar {
  a: string,
  b: number,
  c: boolean
}
```

**Comment by RyanCavanaugh** [comment]
Right, exactly
