### ISSUE TITLE
Object circular assignment never error

### ISSUE THREAD

**Issue by Jevin0** [microsoft/TypeScript#58925]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

https://www.typescriptlang.org/play/?ts=5.0.4#code/JYOwLgpgTgZghgYwgAgMoBtgBNoBUD2+6YwADgApT6kDOyA3gLABQyyWwNcARuhFgH4AXMm6E+cEAG4WbUukQQAthHDDkNMFFABzGa2ScAInCgBrdWKIRJ+gL4sWCfCE3Iw4khSq0RGbHieZJTUdAC8DLLsnDx8WCLw6DQQLA7MTi5uWHBgcEIAShAAjgCuwFD8ADz+OFAERF4htAB8yBFMBhxcvPwJcEkQADRR8ooq4CIARB6kk8MGxqZmfQPzaSww+FDIABTOrmDIZhAAnoYg7kHeoQCUkQb7bgD6x2cRr8hwdK-4MGiYtXqxGCPho+ii2VyAG0XqcALptS4NEGhGGvOFRR7WAB06HwOh2sJON1SjmYQA

**Comment by snarbies** [comment]
You are trying to copy, key-by-key, from this type:

```typescript
{
  disabled?: boolean;
  placement?: string;
  isDark?: boolean;
}
```
...to this type...

```typescript
{
  disabled: boolean;
  placement: string;
  isDark: boolean;
}
```

That would mean copying values that might be `undefined` to properties that don't accept `undefined`.

This is simply a case of typescript doing its job and telling you you've made a mistake.

**Comment by Jevin0** [comment]
> You are trying to copy, key-by-key, from this type:
> 
> ```ts
> {
>   disabled?: boolean;
>   placement?: string;
>   isDark?: boolean;
> }
> ```
> 
> ...to this type...
> 
> ```ts
> {
>   disabled: boolean;
>   placement: string;
>   isDark: boolean;
> }
> ```
> 
> That would mean copying values that might be `undefined` to properties that don't accept `undefined`.
> 
> This is simply a case of typescript doing its job and telling you you've made a mistake.



> You are trying to copy, key-by-key, from this type:
> 
> ```ts
> {
>   disabled?: boolean;
>   placement?: string;
>   isDark?: boolean;
> }
> ```
> 
> ...to this type...
> 
> ```ts
> {
>   disabled: boolean;
>   placement: string;
>   isDark: boolean;
> }
> ```
> 
> That would mean copying values that might be `undefined` to properties that don't accept `undefined`.
> 
> This is simply a case of typescript doing its job and telling you you've made a mistake.

ok, I know, thank you
