### ISSUE TITLE
Arrow function input parameter transpilation

### ISSUE THREAD

**Issue by aayushkapoor206** [Microsoft/TypeScript#5892]
```
arr.forEach(dimension => {
})
dim.forEach((val) => {
})
```
Both the functions output the brackets in the arrow function's parameter as passed when transpiling to ES6. There should be a standard output like using brackets even if it isn't present in the .ts file
So the output should be 
```
arr.forEach((dimension) => {
})
dim.forEach((val) => {
})
```
if the brackets are enforced in the output

**Comment by mhegazy** [comment]
both are valid ES6 syntax. the compiler tries to keep the output close to the input, if you think the output should have a pair of parentheses, add then to the input.
