### ISSUE TITLE
Generic is "`any`-like" for relational operators

### ISSUE THREAD

**Issue by Rudxain** [microsoft/TypeScript#58938]
### 🔎 Search Terms

generics templates comparison compare less-than more-than unknown unsound function inline

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about relational operators and comparisons

### ⏯ Playground Link

https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&target=10&jsx=0&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&suppressImplicitAnyIndexErrors=true&ts=5.6.0-dev.20240619&noStrictGenericChecks=true#code/MYewdgzgLgBMC2AHGBeGAeAKgGgHwAoAPALhhxgE9TMBKVXGQjSgWACh2wBXAGx+e592CRPkE9sMcTXbsuYACYBTAGYBLMEoXN5y9ZoXCk+Xao1bJp-Vpkc2AZQrwARiB7466GI5duPR0R9XdxpJIL8aWyA

### 💻 Code

```ts
const cmp = <T,>(x: T, y: T) => x < y

null < null
cmp(null, null)

undefined < undefined
cmp(undefined, undefined)

Symbol() < Symbol()
cmp(Symbol(), Symbol())
```

### 🙁 Actual behavior

Error messages:
1. "The value 'null' cannot be used here.(18050)"
2. "The value 'undefined' cannot be used here.(18050)"
3. "The '<' operator cannot be applied to type 'symbol'.(2469)"

The errors show up for both operands of the relational operator except `symbol`s, which only error on LHS.

The arrow fn `cmp` doesn't trigger any errors, even at call sites

### 🙂 Expected behavior

`cmp` should trigger an error on definition, because even though both params are same-type, they can't always be compared (`symbol`s throw at runtime)

**Comment by fatcerberus** [comment]
Technically both parameters aren't even guaranteed to be the same type, because `T` might be a union.

**Comment by RyanCavanaugh** [comment]
See #52807; this is a rather breaky change to make and we're evaluating what the right course of action is. There are a *lot* of unconstrained (or insufficiently constrained) type parameters out there

**Comment by Rudxain** [comment]
Should I close this issue (as dupe) and open one about the weird single-sidedness of `symbol`s? Or should I keep it as-is?
