### ISSUE TITLE
Multiple source roots - or something like classpath, like python_path, like include_path !!!

### ISSUE THREAD

**Issue by iongion** [Microsoft/TypeScript#5893]
I need to have the following structure:
 * build
   * debug
   * release
 * sources
   * clients
     *  APIClient.ts
   * runtime
   * services
 * test
   * cases
     * clients
       * APIClientTest.ts
     * runtime
     * services
 * typings

My goal is that in the tests I want to be able to import the associated tested class without using `/// reference`.

This would work out of the box if the test would stay right next to the class, not in separate directories:
 * build
   * debug
   * release
 * sources
   * clients
     * APIClient.ts
     * APIClientTest.ts
   * runtime
   * services
 * typings

But it is *extremly ugly* and dirty and it gets even more so when these folders start growing(hundreds of classes, hundreds of tests ...)

My second attempt was to use a `tsconfig.json`:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": true,
        "noEmitOnError": true,
        "outDir": "./build/debug",
        "rootDir": "./",
        "sourceMap": false
    },
    "exclude": [
        "build",
        "node_modules"
    ]
}
```

But this creates weird folder structure inside build, understandable because it considers project root as source root which is not the same thing at all. Now, from what I've tried, the ideal situation would be to have multiple source directories that output in the same build dir. In this way, the tests would be able to avoid having to declare the horor that is `/// reference`.

I could use different `tsconfig.json` for sources and test directories, but then how do you specify the tests that references can be found additionally in another directory too.

What do you recommend, what can be done ?

**Comment by vladima** [comment]
if you are using modules then [this proposal](https://github.com/Microsoft/TypeScript/issues/5039) might be helpful

**Comment by frankwallis** [comment]
In every source directory create a directory called ```__tests__``` where you keep your unit tests? This approach is used by test runners like [jest](https://facebook.github.io/jest/docs/tutorial.html). 

You can then import the units under test using relative paths and it has the advantage that your tests are very visible and easy to find, but don't clutter up the source directories.
