### ISSUE TITLE
inherit interface/type block comment

### ISSUE THREAD

**Issue by Tzxhy** [microsoft/TypeScript#58940]
### 🔍 Search Terms

comment inherit 

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Add more block comment mechanism.

### 📃 Motivating Example

```ts
export enum TreeNodeExpanderStatus {
    /** full expanded */
    FullExpanded,
    /** full collapsed */
    FullCollapsed,
    /** partial expanded */
    PartialExpanded,
}
interface Props {
    

    status: TreeNodeExpanderStatus
    /** callback when click expand icon */
    onClickExpand(): void;
    /** callback when click collapse icon */
    onClickCollapse(): void;
}

```

When i use IDE to see `Props.status`, shows: 
![image](https://github.com/microsoft/TypeScript/assets/18610809/2b3dfcb6-8d34-48b7-9beb-4432d7205246)

But if it can show the `TreeNodeExpanderStatus ` comment, it will better. Right? Like this:
![image](https://github.com/microsoft/TypeScript/assets/18610809/f49e8491-d6be-45c8-9db3-ef214dca6194)

Also, this should work when no other comments upper on property `status`.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

1. Write less comments.
2. No appropriate comments inheritance mechanism.
3. Write more comments.

**Comment by RyanCavanaugh** [comment]
This gets very confusing because you don't know whether the comment is referring to the type or the property.

It's also very noisy because it means comments for commonly-used types (`RegEx`, etc) show up *everywhere* which is very rarely useful
