### ISSUE TITLE
Is the "Roadmap" wiki page still maintained?

### ISSUE THREAD

**Issue by ssalka** [microsoft/TypeScript#58949]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

Long-time follower of TypeScript here 👋  love the language & keeping up-to-date with new features as it evolves. However I noticed over the last year, this [Roadmap](https://github.com/microsoft/TypeScript/wiki/Roadmap) page on the GitHub wiki has not been updated since the 5.0 release. I have often used this page in the past to get a high-level overview of new features; I find it convenient to have bookmarked instead of looking through recent [blog posts](https://devblogs.microsoft.com/typescript/).

Is there any plan to keep using this page & update it when future releases occur? If not, it probably should be archived/removed from the wiki.

Thanks team & happy typing,
@ssalka

**Comment by DanielRosenwasser** [comment]
Because there are so many release tasks, it often is hard to curate the roadmap page so consistently. More recently, I have been putting out the iteration plans with the release posts being the actual sources of truth. Maybe you are right and we should consider explicitly archiving it.

**Comment by ssalka** [comment]
Makes sense that the release process for documentation is probably quite time consuming, totally understand if it's not worth the time to update yet another page.
