### ISSUE TITLE
Isolated declarations quick fix suggests `boolean` return type for predicates

### ISSUE THREAD

**Issue by bgenia** [microsoft/TypeScript#58948]
### 🔎 Search Terms

isolated declarations, quick fix, type predicates

### 🕗 Version & Regression Information

TS 5.5+

### ⏯ Playground Link

https://www.typescriptlang.org/play/?isolatedDeclarations=true#code/GYVwdgxgLglg9mABDAzgZSgJxmA5gCgDcBDAGxAFMAuRcAazDgHcwBKRAbwChFfFMKUEJiRQAngAcKcYIhLkKiALwrEAIhRYcuNVwC+XIA

### 💻 Code

```ts
function isString(value: unknown) {
    return typeof value === "string"
}
```

### 🙁 Actual behavior

Quick fix suggests 'boolean' return type annotation

### 🙂 Expected behavior

Quick fix should suggest the inferred 'value is string` predicate annotation

**Comment by RyanCavanaugh** [comment]
cc @danvk

**Comment by Ankita-lal** [comment]
> ### 🔎 Search Terms
> isolated declarations, quick fix, type predicates
> 
> ### 🕗 Version & Regression Information
> TS 5.5+
> 
> ### ⏯ Playground Link
> https://www.typescriptlang.org/play/?isolatedDeclarations=true#code/GYVwdgxgLglg9mABDAzgZSgJxmA5gCgDcBDAGxAFMAuRcAazDgHcwBKRAbwChFfFMKUEJiRQAngAcKcYIhLkKiALwrEAIhRYcuNVwC+XIA
> 
> ### 💻 Code
> ```ts
> function isString(value: unknown) {
>     return typeof value === "string"
> }
> ```
> 
> ### 🙁 Actual behavior
> Quick fix suggests 'boolean' return type annotation
> 
> ### 🙂 Expected behavior
> Quick fix should suggest the inferred 'value is string` predicate annotation
> 
> ### Additional information about the issue
> _No response_

We can write the code this way to make it work,
function isString(value: unknown): boolean {
    return typeof value === "string";
}
