### ISSUE TITLE
`/// <reference lib` is stripped out of `d.ts` file

### ISSUE THREAD

**Issue by SimenB** [microsoft/TypeScript#58956]
### 🔎 Search Terms

reference lib elided disposable

### 🕗 Version & Regression Information

- This changed between versions 5.4.5 and 5.5.2

(not fixed in nightly)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.2#code/PQgEB4CcFMDNpgOwMbVAGwJYCMC8AiaAZ0WgA8AXAOgBNMiAHAeyIENt1p9RgA+AKH7lmkCqEyIKCWK1SgAKgAsJAc1DkpiGkVAAReszYc0AbwC+QA

### 💻 Code

```ts
/// <reference lib="esnext.disposable" />

export interface Thing extends Disposable {}
```

### 🙁 Actual behavior

Output `d.ts` is

```ts
export interface Thing extends Disposable {
}
```

### 🙂 Expected behavior

The `.d.ts` file should be like it was in 5.4.5

```ts
/// <reference lib="esnext.disposable" />
export interface Thing extends Disposable {
}
```

**Comment by jakebailey** [comment]
This is by design: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#simplified-reference-directive-declaration-emit

Changed in https://github.com/microsoft/TypeScript/pull/57681.

You must now write:

```ts
/// <reference lib="esnext.disposable" preserve="true" />
```

**Comment by SimenB** [comment]
Ah, somehow missed that. Thanks!
