### ISSUE TITLE
Typescript 5.5 is not working with yarn v4 and nodeLinker pnp, it forces switching to nodeLinker node-modules

### ISSUE THREAD

**Issue by andrew-aladjev** [microsoft/TypeScript#58950]
### 🔎 Search Terms

Typescript 5.5 and yarn berry/canary/v3/v4/etc and pnp mode, found no bug reports.

### 🕗 Version & Regression Information

- This changed between versions 5.4.5 and 5.5.0

### 💻 Code

Something has significantly changed from typescript `5.4.5` to `5.5.0`. `yarn config set nodeLinker pnp` was working fine together with `yarn exec tsc`. Today I had to switch to `yarn config set nodeLinker node-modules` in order to use `yarn exec tsc` together with typescript `5.5.0`.

Typescript config is standard:
```
{
  "include": ["src/**/*.ts"],
  "compilerOptions": {
    "target": "esnext",
    "lib": ["esnext"],
    "module": "NodeNext",
    "rootDir": "src",
    "moduleResolution": "nodenext",
    "outDir": "dist",
  }
}
```

### 🙁 Actual behavior

If you are trying to run `yarn exec tsc` (when `yarn` v4 is in pnp mode) than typescript 5.5.0 will fail with something like:

```
error TS2503: Cannot find namespace 'NodeJS'
error TS2304: Cannot find name 'setTimeout'
error TS2304: Cannot find name 'clearTimeout'
```

### 🙂 Expected behavior

`yarn exec tsc` (when `yarn` v4 is in pnp mode) works without errors.

### Additional information about the issue

Did you break something related to `node_modules` dir in typescript 5.5.0? Thank you.

**Comment by andrew-aladjev** [comment]
Sorry, it is hard to provide playground, because I see no sandboxes supports yarn in pnp mode. Please just use the following shell script:

```
mkdir ts-5.5.0 && cd ts-5.5.0
echo '{ "name": "bug-1", "private": true, "dependencies": { "typescript": "5.5.2", "@types/node": "*" } }' | jq > package.json
yarn set version stable
yarn config set nodeLinker pnp
yarn install
mkdir src && mkdir dist
echo 'setTimeout(() => {}, 0);' > src/bug.ts
echo '{ "include": ["src/**/*.ts"], "compilerOptions": { "target": "esnext", "lib": ["esnext"], "module": "NodeNext", "rootDir": "src", "moduleResolution": "nodenext", "outDir": "dist" }}' | jq > tsconfig.json
yarn exec tsc
```

Result is the following:

```
src/bug.ts:1:1 - error TS2304: Cannot find name 'setTimeout'.
```

You can fix it by using the following shell script:

```
yarn config set nodeLinker node-modules
yarn install
yarn exec tsc
```

And it will finish without errors.

**Comment by merceyz** [comment]
This happens with roughly every new TypeScript release but it's not on the TypeScript team to handle.

You'll need to wait for https://github.com/yarnpkg/berry/pull/6349 to be released or if you want you can use that PR version of Yarn by running the following in your project:
```sh
yarn set version from sources --branch 6349
yarn install
```

**Comment by andrew-aladjev** [comment]
@merceyz, Thank you, it works perfect. Lets wait until it will be released.

**Comment by merceyz** [comment]
It was released 22 minutes ago https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.3.1
