### ISSUE TITLE
Unresolved `any` behaves different from `any`

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/TypeScript#58960]
### 🔎 Search Terms

_“unresolved any”_

### 🕗 Version & Regression Information

- This changed between versions 5.4.5 and 5.5.2

### ⏯ Playground Link

https://www.typescriptlang.org/play/?&filetype=ts#code/PTAEBcE8AcFNQAoCcD20DOoC8oCGA7SAKCjlADEUVtFUMiSZ4BZAEQA0BhFfcWX5Gkw4AFAAZQsAB598AE0wBGUADIKVUAH5QAbwC+oAFzqUASiJA

### 💻 Code

```ts
// type Props = any

type MDXContentProps = (0 extends 1 & Props ? {} : Props)
```

### 🙁 Actual behavior

The type of `MDXContentProps` is `any`

### 🙂 Expected behavior

The type of `MDXContentProps` is `{}`

### Additional information about the issue

When you hover over a type that doesn’t exist, the editor shows `/*unresolved*/ any`. In TypeScript 5.4, this type was equivalent to `any`. In TypeScript 5.5, it behaves slightly different. This can be seen in the playground by toggling the line `type Props = any` and hovering the `MDXContentProps` type.

If an unresolved `any` is assigned to another type, that type becomes equivalent to an unresolved `any`, except the `/*unresolved*/` label is gone when hovering over it.

---

I use this pattern in MDX analyzer (https://github.com/mdx-js/mdx-analyzer/blob/vscode-mdx@1.8.8/packages/language-service/lib/virtual-code.js#L96). This allows users to optionally define props for their MDX file. This used to work great, but now everything is just inferred to `any`.

If there’s a better way to detect whether a type is defined, I would love to hear about it.

**Comment by RyanCavanaugh** [comment]
If you're `ts-ignore`ing something in declaration space, all bets are off. Do not take dependencies on discoveries made this way.

**Comment by so1ve** [comment]
Any way to detect if a type exists?

**Comment by uhyo** [comment]
Even though it is not a defect, I'm very curious which PR caused this change. 👀

**Comment by Andarist** [comment]
This changed in 5.5.0-dev.20240524, here is [the diff](https://github.com/microsoft/TypeScript/compare/ddf43cd0e0091057254b1fcfcaf880140dfb7ea1...cffc425ad75bd7b1298abb78ce09337d08cc94b9). Likely "culprit" would be: https://github.com/microsoft/TypeScript/pull/58610

**Comment by remcohaszing** [comment]
> If you're `ts-ignore`ing something in declaration space, all bets are off.

I think this is fair. My example abuses `ts-ignore` to check whether a type exists (due to the lack of a better alternative). I think it would be totally fair for TypeScript to change this type to `unknown` for example, or even a special type `unresolved`.

However, TypeScript uses a type that looks like `any` on inspection, but doesn’t behave like `any`. This I would call a defect. Another practical example is that this type could come from a dependency if the user uses `skipLibCheck` true.

The following mechanism appears to work between TypeScript versions to check whether a type is `any`, `unknown`, or unresolved `any`. ([playground](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgGJwDYYEaINbIDeAUMmcvFrgngFzIDOYUoA5sQL7HFgCeADigAKUCDGiiAJsgC8yOCF7cIAD34B7KGGR9ByAOoLI0uQDd1waasghJDZCLESI0gPxpMOfMnqPxUKWIAeiDyMPIAPVdiIA))

```ts
interface Fallback {
    fallback: string
}

type Preferred = any

export type Wanted = void extends Preferred ? Fallback : Preferred
```

**Comment by remcohaszing** [comment]
I made a new playground to better show why I believe the behaviour is problematic: https://www.typescriptlang.org/play/?#code/PTAECUFMHMFcBsCGAnUBBAdgTwFABcsAHSdUAXlEWxxFEBwCYAKlFg2UgGcB7eAN0gAmoRmCpZAuASguGUAAsu-ZABpQAI0izE-DqAEBLAGYHI7DHlAHkXALaVqBYqABC5UABEunAHJc8AUQAPPQ48GjAASQx9EL0MOGDNVXgSSxt6MUlpOQUTFXVNbVB4PQBrEid8IhIAYVcKsNBqzTiSPFkSZLw8E1I8LmcpVFq+qVUOE35KUABjZugSLgNQNtaq90rHN1cABlBIAO6onQBGUAAyUgB+ZeRYEgAuC0R4cYbQUAA9S5wgA
