### ISSUE TITLE
An unobvious point when developing a Button-or-Link component. Optional href for tag a and mandatory for Link from Next.js.  [5.5.2]

### ISSUE THREAD

**Issue by MrOxMasTer** [microsoft/TypeScript#58973]
### 🔎 Search Terms

Polymorphic Link/Button Components in React & TypeScript

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [How to conditionally render a button / Link Next.js Component with TypeScript](https://stackoverflow.com/questions/72866352/how-to-conditionally-render-a-button-link-next-js-component-with-typescript)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdWAHpLHMAHYxZQF5ZwAQgFcYMCB0FosABWJh0AbzpxVcADbIARlnUAuOKhhROAc3pq4AN2QnkXAwCIwJkLYCejuAB84j1Fi4EgAmHl6+jtywwGE+fqEcpjyOFmrqEMjBZgD8BloQEOo4HKmq6ZlmACrMMLlw+YXF9AC+DDDuYAIAEpUAsgAyImISchAKcAC8cMqWABaUBHUcWFY8LXAAZJhUMAB0Q+IcPQMAgmImWqJYqAA8x4OihwCiRSBYXAB89HTtnXD3Jw4uFm0FG4ymMzU8ywBAMRhMiXWW2weD2gOB0AB52Al24twBQJBUBeWDen2+zFY8F+AgOI3k6CmdMk0jB6C2AAoCRioGy4vdmWyAJQUljQeBBDhGISPCSTOAcyFlbS6AA0KjUNjsXHVlnKWUSurSGQNpmqTBgRtUuxtLjGqDozQMgoZQsmH2mGtUwAICrtCl20IIbqVljglBgwigHDgN2Q0xtu39qGaH0Umh06maNwA9MgPl64M1SnBCxGozGbrjDnAaRNHNWJI5FInk804B9c42OF9HTQgA

### 💻 Code

In the playground

### 🙁 Actual behavior

Highlights an error with silly information

### 🙂 Expected behavior

So that an error is not highlighted, which also incorrectly indicates

### Additional information about the issue

I can't make one component for the link and button depending on the href. Why does he think that the button is a link if I have a condition.

**Comment by MartinJohns** [comment]
Please fill out the issue template completely.

Just checking for truthiness of `props.href` is not enough to narrow the type, because the `string` can be **empty** and thus falsy. In that case your props still can be typed `HTMLAnchorProps` in line 31, which has incompatible properties with `<button>`.

You can explicitly check for a `string` instead: `typeof props.href === "string"`

**Comment by MrOxMasTer** [comment]
> You can explicitly check for a `string` instead: `typeof props.href === "string"`

It works in playground, but it doesn't work in my project. I am using nextjs 14.2.4

![image](https://github.com/microsoft/TypeScript/assets/59291123/59a3fcfb-8b84-4792-acdc-9af76ddb34cc)
![image](https://github.com/microsoft/TypeScript/assets/59291123/3e41831f-22cb-4085-adcb-6e3e676d385b)
![image](https://github.com/microsoft/TypeScript/assets/59291123/478e6264-6634-42fb-99c1-a12bf51acaad)
![image](https://github.com/microsoft/TypeScript/assets/59291123/fa146557-afa6-490c-afa9-818ae21cd977)

**Comment by MrOxMasTer** [comment]
The predicate works, but my typing is broken
![image](https://github.com/microsoft/TypeScript/assets/59291123/21c97715-81ee-4249-984e-d30f50e52ece)
![image](https://github.com/microsoft/TypeScript/assets/59291123/52443e3a-fa1b-4b28-b011-be693a162d07)
![image](https://github.com/microsoft/TypeScript/assets/59291123/1f0a6055-79ab-4c33-9261-a4d94848d3c3)

**Comment by MrOxMasTer** [comment]
![image](https://github.com/microsoft/TypeScript/assets/59291123/25f9e713-eec8-43ca-9efe-891fc08fedc8)
![image](https://github.com/microsoft/TypeScript/assets/59291123/33954a96-02ad-4dc5-a554-af55d8174439)

And as I understand it, it's about the raf, which can now be passed as an argument and you don't need forwardRef for that.

**Comment by MrOxMasTer** [comment]
But at the same time, I still have the old versions

![image](https://github.com/microsoft/TypeScript/assets/59291123/bc93fa79-6062-4943-9037-0948ab297af8)
![image](https://github.com/microsoft/TypeScript/assets/59291123/d1e285d9-a5d4-416f-ad77-49e51490cbee)

**Comment by MrOxMasTer** [comment]
I've updated and the error still hasn't gone away.
![image](https://github.com/microsoft/TypeScript/assets/59291123/2fdec8fd-6a18-4256-89d6-1caa2b4e2a15)
![image](https://github.com/microsoft/TypeScript/assets/59291123/e72d77aa-5e0d-4289-9e7f-61869394a3a5)
![image](https://github.com/microsoft/TypeScript/assets/59291123/c05effd3-4b0a-4664-8101-5256ef71e3c2)

**Comment by MartinJohns** [comment]
From your pictures it's not clear what your issue is, but nothing indicates a bug in TypeScript, just trouble using it, and this issue tracker is not suitable as a general help forum. Perhaps you should try StackOverflow or the TypeScript discord?

**Comment by MrOxMasTer** [comment]
> From your pictures it's not clear what your issue is, but nothing indicates a bug in TypeScript, just trouble using it, and this issue tracker is not suitable as a general help forum. Perhaps you should try StackOverflow or the TypeScript discord?

Okay, I'll try another way now. If it is not clear, then I will try to contact another place. The fact is that there are several problems at once that it is unclear how to describe and they all arise in different situations.

1 problem: I'm using your ```ts props.href === "string"``` method

![image](https://github.com/microsoft/TypeScript/assets/59291123/ff1cb1b5-df91-4b3a-9e95-c16371433ec0)

**Comment by MrOxMasTer** [comment]
The chain of actions and the appearance of errors:

1 Problem:
First there is the props type of the regular button and the props type of the link component from Next.js:
![image](https://github.com/microsoft/TypeScript/assets/59291123/36016612-c828-4c81-9601-8e0f389e02fb)

My button is highlighted in red just like that...
![image](https://github.com/microsoft/TypeScript/assets/59291123/67d120b9-c3f9-4be5-9847-fcbe0af10710)

Questions:
Why is the button highlighted in red if there is nothing superfluous except the "POSSIBLE" href?

Even if I do a restructuring, I still have a mistake:
![image](https://github.com/microsoft/TypeScript/assets/59291123/f9e64bcf-78b0-4c9f-88ca-0e1cb9369376)

**Comment by MrOxMasTer** [comment]
2 problem: When adding 3 object fields, or variantsProps.

Having these types:
![image](https://github.com/microsoft/TypeScript/assets/59291123/ff1cb1b5-df91-4b3a-9e95-c16371433ec0)
![image](https://github.com/microsoft/TypeScript/assets/59291123/13f785a5-00b9-42d2-879b-4979d181ef62)


The button is highlighted in red
![image](https://github.com/microsoft/TypeScript/assets/59291123/1cd220af-0486-4daf-a897-27d7cb8db7a4)

Questions: 
1. Why is the button highlighted in red if only the types belonging to the button should have remained. I pulled out the rest?
2. Why is it not highlighted that I put unknown arguments in the link and nothing is highlighted in red?

**Comment by MrOxMasTer** [comment]
> From your pictures it's not clear what your issue is, but nothing indicates a bug in TypeScript, just trouble using it, and this issue tracker is not suitable as a general help forum. Perhaps you should try StackOverflow or the TypeScript discord?

because it seems to me that there is not a problem with misuse, but a specific problem and perhaps more than one.

**Comment by MrOxMasTer** [comment]
> From your pictures it's not clear what your issue is, but nothing indicates a bug in TypeScript, just trouble using it, and this issue tracker is not suitable as a general help forum. Perhaps you should try StackOverflow or the TypeScript discord?

https://stackoverflow.com/staging-ground/78658292

**Comment by MrOxMasTer** [comment]
![image](https://github.com/microsoft/TypeScript/assets/59291123/474c7b56-3b3a-433a-b3c5-6cc134fe9d96)
![image](https://github.com/microsoft/TypeScript/assets/59291123/6535d2dc-641f-42e5-8802-143cb2741caa)
![image](https://github.com/microsoft/TypeScript/assets/59291123/dd7f517a-de7c-4caf-b964-d8e19b3b4fdf)

**Comment by MrOxMasTer** [comment]
https://codesandbox.io/p/devbox/test-typescript-q89n2h

**Comment by MrOxMasTer** [comment]
> From your pictures it's not clear what your issue is, but nothing indicates a bug in TypeScript, just trouble using it, and this issue tracker is not suitable as a general help forum. Perhaps you should try StackOverflow or the TypeScript discord?

https://codesandbox.io/p/devbox/test-typescript-q89n2h

**Comment by MartinJohns** [comment]
Screenshots are a **terrible** way to describe your issue, because most information is not accessible.

Nothing here indicates a bug in TypeScript, just a lack of understanding of either the types you work with, or how narrowing works.

In your "NextJS" case the `typeof` check for `string` does not work, because the `href` property of `HTMLLinkProps` is typed `string | UrlObject`. So if you check only for `string` it can still be a `UrlObject` in the `else`-branch, and this means the type `HTMLButtonProps | HTMLLinkProps` can't be narrowed to `HTMLButtonProps`, resulting in incompatible properties for your `<button>` from the still remaining `HTMLLinkProps` type.

For these types you can just check for `undefined`, because either it's `undefined` (or missing) from the `HTMLButtonProps`, or it's `string | UrlObject` (but never `undefined`) from the `HTMLLinkProps`. So by checking for `undefined` you make sure your value is not a `HTMLButtonProps`.

**Comment by MrOxMasTer** [comment]
> For these types you can just check for `undefined`, because either it's `undefined` (or missing) from the `HTMLButtonProps`, or it's `string | UrlObject` (but never `undefined`) from the `HTMLLinkProps`. So by checking for `undefined` you make sure your value is not a `HTMLButtonProps`.

I originally had this check, which also caused an error. If it were that simple, I wouldn't be writing here.

You told me exactly the opposite (that you need to check the href for "string"), despite the fact that I said that this is an unusual html link tag, a Link, which the screenshots prove. But even if you omit this point, it still causes an error If I correct for another check.

Once again, please go in for example and see that it still causes an error. I made 2 components with different checks. One specifically for undefined, and the other for the presence of this props in principle:
https://codesandbox.io/p/devbox/test-typescript-q89n2h

**Comment by MartinJohns** [comment]
If your `href` property is `undefined`, then you're dealing with a `HTMLButtonProps`. In your image you're trying to use `HTMLButtonProps` for the `<Link>` element, and vice versa `HTMLLinkProps` for the `<button>` element.

Either swap the elements, or check if `href` is **not** `undefined`: `typeof props.href !== "undefined"`.

**Comment by MrOxMasTer** [comment]
> Either swap the elements, or check if `href` is **not** `undefined`: `typeof props.href !== "undefined"`.

Okay, I'll agree on that. I wrote the condition incorrectly because I was in a hurry. 

Let's move on. Why do I lose button typing if I don't have an href?
![image](https://github.com/microsoft/TypeScript/assets/59291123/89edceeb-5c96-43f8-9a19-9b537fe662ff)

https://codesandbox.io/p/devbox/test-typescript-q89n2h

**Comment by MartinJohns** [comment]
I'm sorry, but I'll drop out of this issue. Again, nothing you have shown here indicates a bug with TypeScript, and this is the wrong place for general support / for teaching language basics. The issue tracker is not meant as a support forum, it's for bugs with TypeScript and feature requests.

**Comment by MrOxMasTer** [comment]
> I'm sorry, but I'll drop out of this issue. Again, nothing you have shown here indicates a bug with TypeScript, and this is the wrong place for general support / for teaching language basics. The issue tracker is not meant as a support forum, it's for bugs with TypeScript and feature requests.

I understand it wasn't obvious before, but the button types are not highlighted here, if only they should be. How can this be?

**Comment by MrOxMasTer** [comment]
> Let's move on. Why do I lose button typing if I don't have an href? ![image](https://private-user-images.githubusercontent.com/59291123/342067007-89edceeb-5c96-43f8-9a19-9b537fe662ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTA3MDAsIm5iZiI6MTcxOTE1MDQwMCwicGF0aCI6Ii81OTI5MTEyMy8zNDIwNjcwMDctODllZGNlZWItNWM5Ni00M2Y4LTlhMTktOWI1MzdmZTY2MmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEzNDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMjJkMTAzMDhmMjc2MjFkNWRhYTRkNjMzYmU0ZTc5MzY0NmM1Y2Q5OGJlMjYyNDkxNmJkYThlMWNhMWYyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7P6m6ZdejhX-4vWf86Dz7Ht89TDUwOWow0Pe1Ob78aU)
> 

At the same time, this is fixed if I explicitly specify href={undefined}, but now he complains about something else that is unclear:
![image](https://github.com/microsoft/TypeScript/assets/59291123/adc5cd5b-b227-42ec-a8a2-03109fc4fd39)

**Comment by MrOxMasTer** [comment]
> For some reason, button types are shown here only if undefined is explicitly specified 
![image](https://private-user-images.githubusercontent.com/59291123/342069070-adc5cd5b-b227-42ec-a8a2-03109fc4fd39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTE1MDEsIm5iZiI6MTcxOTE1MTIwMSwicGF0aCI6Ii81OTI5MTEyMy8zNDIwNjkwNzAtYWRjNWNkNWItYjIyNy00MmVjLWE4YTItMDMxMDlmYzRmZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE0MDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjI1NTViMTE0ZTE4NGFlYjk4MjU2MzhmNjZlMzhiNDIzMjBiMGYyYmJiMjU5ZDQ4NWExNWUzNjQ0MWQ0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Bg8SjvmsIFRZRt5KNO4XHsNW_UnuzrVTjWwyn4HuXA)

It may then open up a new issue for this problem that typescript does not implicitly define undefined (props that do not pass)

**Comment by MrOxMasTer** [comment]
> And just checking for truthyness of `href` like in your first image does not work, because it can be an empty `string`, which is falsy, but it's not enough to narrow the type.

Why does the question highlight to me the error of a ton of unnecessary text, but does not highlight the main one, that my UrlObject type does not fit the condition or string does not fit the condition or that I may have an empty one that does not fit or fits (again, to the reflection that string prevents me). Why is this the purpose of this tool, but it just doesn't perform this function to protect me from unnecessary types. It does, but what's the point of doing it as a dev tool if it helps the developer half and, conversely, confuses

**Comment by MrOxMasTer** [comment]
Thanks: learn the basics. Your task of the tool, as well as typing, is to protect against non-obvious moments and strange javascript typing, so that it would be more explicit. From unnecessary or incorrect types, but instead, on the contrary, it confuses me even more and does not help.
That's why I use your tool, so that there are no problems, but it seems exactly the opposite
