### ISSUE TITLE
Narrowing parametric union types

### ISSUE THREAD

**Issue by hath995** [Microsoft/TypeScript#5897]
I have a fair amount of code which is of the following form. 
```
function doWork<A>(a: A | A[]) {
...
}
```
Currently, I've handled this by doing.
```
function doWork<A>(a: A | A[]) {
  if(Array.isArray(a) ){
     //array code
  }else{
     let singluar_a = <A>a;
     //singular code 
  }
}
```
I'm curious if there is a way to narrow the union type to the parametric type rather than casting. Logically, it would seem like the else branch should know that a is no longer A | A[] but A by exclusion. Casting feels a bit like cheating the type system.

**Comment by weswigham** [comment]
What version of TS are you using? Given that we do the right thing [on the playground](http://www.typescriptlang.org/Playground#src=%0D%0Afunction%20generic%3CA%3E(x%3A%20A%20%7C%20A%5B%5D)%20%7B%09%0D%0A%09if%20(Array.isArray(x))%20%7B%0D%0A%09%09x%3B%0D%0A%09%7D%0D%0A%09else%20%7B%0D%0A%09%09x%3B%0D%0A%09%7D%0D%0A%7D) this may be a regression.

**Comment by hath995** [comment]
Nevermind, using the nightly seems to resolve the issue.
