### ISSUE TITLE
Required triple-slash types reference no longer generated in TS 5.5

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/TypeScript#58985]
### 🔎 Search Terms

triple slash reference types omitted

https://github.com/microsoft/TypeScript/pull/57681

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.5.0

### ⏯ Playground Link

https://github.com/lit/lit/pull/4682

### 💻 Code

I couldn't make a playground that shows the problem, because it requires a dependency.

package.json:
```json
  "dependencies": {
    "@types/trusted-types": "^2.0.2"
  },
```
tsconfig.json
```json
{
  "compilerOptions": {
    "types": ["trusted-types"]
  },
}
```

index.ts (part of package `dep`)
```ts
export const foo = (html: string | TrustedHTML) => Foo;
```

app.js (part of package `app`, depends on the package `dep`):
```
import {foo} from 'dep';
```

### 🙁 Actual behavior

When compiling the package `app`, the compile error is that in dep/index.d.ts, the type `TrustedHTML` isn't found.

### 🙂 Expected behavior

No compile errors.

### Additional information about the issue

The problem seems to be that a triple-slash directive used to be emitted and now isn't:

```ts
/// <reference types="trusted-types" />
```

This is might due to https://github.com/microsoft/TypeScript/pull/57681 however this isn't about not preserving a reference, since the reference used to be generated by the compiler. This is about the compiler newly not generating a required reference at all.

Changing the library code to:
index.ts (as part of package `dep`)

```ts
/// <reference types="trusted-types" preserve="true" />
export const foo = (html: string | TrustedHTML) => Foo;
```

fixes the problem, but this seems like a bug because before the compiler was correctly inferring that the reference was required for the declaration file, and now it's not.

**Comment by IllusionMH** [comment]
It's intentional for user-written reference directives as well and mentioned in https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#simplified-reference-directive-declaration-emit

**Comment by justinfagnani** [comment]
Thanks. I looked for issues, but missed that in the release notes 🤦‍♂️

> Reference directives are no longer synthesized

Since this is intentional, I'll close the issue.
