### ISSUE TITLE
Inferred Type Predicates don't work with the Boolean function

### ISSUE THREAD

**Issue by jakeleventhal** [microsoft/TypeScript#58999]
### 🔎 Search Terms

Inferred Type Predicates Boolean

### 🕗 Version & Regression Information

This is a new issue introduced in 5.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?isolatedDeclarations=true#code/PTAEGEHsCdoUwMYBcA2BPUBLAdgMztAM6hJoAOcoAhsYUtDgOYBQCk2doA7jANaEAuUHQbZGAbQC6oALyhxAOiUBBWFTQAKAKwBKSc1CHQCgLZUyGgG6yAfKADeBo88y5QV0AFIATLJlyABh0HJ2cw0HgkAFdobFAAcipheiZ4gG5QsIBfZkznSJi47CiUFAznLJ1MhVxMFCQCDxk7AEIWyx0M5hBQABFIOEJseKRuPlBcGGFIE0p4GnZQOEs4OKQAC0goxnWsJGIAIxpMBCpSjA3KQipZ1nZOABMBoaQAdT4ARiERJilZeSUClU0HU2j01TMFmszRC4UMrnc1h8fkCwUccLCBViCSSPzE6TyRhyhMMWKKJTKmUq1Vq9Ua0LsHS6PXAVGwoxw+GgoAAQpBICg4GyxtBeEw7hxRk9Buz3qLvN8UmI-nJFCo1JpdPpnKZzE07Oi4QiPMj-KjYRijGScclRIwCRjiRjrcVSuUiVUdbSGtANHyBULsJ0JY9nrK+ABmRV2lUA9UgzXgnWQ-UW8LGpG+M2gIJpy3WxK21Lu8JOuEuikl0DUr11H2p-2CtlWHTB5hAA

### 💻 Code

```ts
// Correctly infers type as string
const works: string[] = [...Array(5)]
    .map(v => {
        if (v %2 === 0) {
            return 'a string';
        }

        return null;
    })
    .filter(v => !!v);

// Doesn't work for some reason even though its basically the same
const doesntWork1: string[] = [...Array(5)]
    .map(v => {
        if (v %2 === 0) {
            return 'a string';
        }

        return null;
    })
    .filter(v => v);

// Cant infer Boolean working
const doesntWork2: string[] = [...Array(5)]
    .map(v => {
        if (v %2 === 0) {
            return 'a string';
        }

        return null;
    })
    .filter(Boolean);
const doesntWork3: string[] = [...Array(5)]
    .map(v => {
        if (v %2 === 0) {
            return 'a string';
        }

        return null;
    })
    .filter(v => Boolean(v));
```

### 🙁 Actual behavior

See playground; it can't infer types properly.

### 🙂 Expected behavior

All have the same type

**Comment by jakebailey** [comment]
`Boolean` is not a type predicate. See https://github.com/microsoft/TypeScript/issues/50387#issuecomment-2037968462 and #16655

**Comment by MichalMarsalek** [comment]
https://github.com/microsoft/TypeScript/pull/57465#issuecomment-2184080281

**Comment by jakeleventhal** [comment]
Closing, but this is kind of sad
