### ISSUE TITLE
allow decorator return function with different returnType

### ISSUE THREAD

**Issue by LongTengDao** [microsoft/TypeScript#59008]
### 🔍 Search Terms

decorator

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

use decorator like higher-order function

### 📃 Motivating Example

```ts
function co<T> (method :() => Generator<void, T, void>, context :ClassMethodDecoratorContext) {
    return function () :T {
        const generator = method();
        let result;
        while ( !( result = generator.next() ).done ) ) {}
        return result.value;
    };
}

class X {
    @co
    * method () { return 1; }
}
```

```ts
function reiterable<T> (method :() => Generator<T, void, void>, context :ClassMethodDecoratorContext) {
    return function () :Iterable<T> {
        return { [Symbol.iterator]: method };
    };
}

class X {
    @reiterable
    * method () { yield 1; }
}
```

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by MartinJohns** [comment]
You will have better success with your issue if you fill out the issue template.

**Comment by andrewbranch** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions _completely_, follow them, and then fill in _all_ the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
