### ISSUE TITLE
Incorrect link in spec

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#5900]
From [4.14 - The `new` Operator](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#4.14):

> If C has one or more apparent construct signatures (section [3.11.1](https://github.com/Microsoft/TypeScript/blob/f7303cdcf10a42dd64edbc3d9620a7c9e0171eaf/doc/spec.md#3.11.1)), the expression is processed in the same manner as a function call, but using the construct signatures as the initial set of candidate signatures for overload resolution. The result type of the function call becomes the result type of the operation.

But [3.11.1](https://github.com/Microsoft/TypeScript/blob/f7303cdcf10a42dd64edbc3d9620a7c9e0171eaf/doc/spec.md#3.11.1) is the **Apparent Members** section.

**Comment by ahejlsberg** [comment]
An apparent construct signature *is* an apparent member.
