### ISSUE TITLE
`import "os"` compiles even if `types` is set to `[]` in tsconfig.json

### ISSUE THREAD

**Issue by rhysd** [microsoft/TypeScript#59010]
### 🔎 Search Terms

is:issue is:open types empty tsconfig label:Bug

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about all sections under 'Common "Bugs" That Aren't Bugs'
- I was unable to test this on prior versions because _______

### 💻 Code

Create a new npm project and add the dependencies:

```sh
npm init
npm install --save-dev typescript @types/node
```

Create `tsconfig.json` in the same directory:

```json
{
  "compilerOptions": {
    "target": "es2022",
    "module": "nodenext",
    "strict": true,
    "types": []
  },
  "include": [
    "index.ts"
  ]
}
```

And write `index.ts`:

```ts
import 'os';
```

### 🙁 Actual behavior

`npx tsc -p .` compiles with no errors.

### 🙂 Expected behavior

`npx tsc -p .` should raise an error since `types` is empty.

```
index.ts:1:8 - error TS2307: Cannot find module 'os' or its corresponding type declarations.

1 import 'os';
         ~~~~

Found 1 error in index.ts:1
```

### Additional information about the issue

When modifying the `import` statement in `index.ts` as follows,

```ts
import {} from 'os';
```

`tsc` reports an error as expected:

```
index.ts:1:16 - error TS2307: Cannot find module 'os' or its corresponding type declarations.

1 import {} from 'os';
                 ~~~~

Found 1 error in index.ts:1
```

**Comment by MartinJohns** [comment]
This is working as intended. See this comment: https://github.com/microsoft/TypeScript/issues/58725#issuecomment-2141625477

> These imports are canonically unchecked by design.

**Comment by rhysd** [comment]
I see. This is a workaround for supporting code like `import "./some.css"`. Can we limit the behavior only when relative import (starting with `./` or `../`) so that we can limit the bad effect of the workaround as minimal as possible?

**Comment by rhysd** [comment]
Okay. Thank you for the clear answer. Closong.
