### ISSUE TITLE
Support type guards as the last element of comma operator lists

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#5902]
For example:

```ts
let x: string | string[];
if (x = getValue(), Array.isArray(x)) {
  // x should be string[]
}
else {
  // x should be string
}
```

or

```ts
var x: string | string[] = (x = getValue(), Array.isArray(x)) ? x[0] : x;
```

You can certainly argue this use of the comma operator is gratuitous, but it seems like a slight oversight that we don't respect it when looking at type guards.

**Comment by arusakov** [comment]
These type guards already exist in current master (3bdff73c16b5a7eca2407500254764618b35bce4).

**Comment by RyanCavanaugh** [comment]
Confirmed
