### ISSUE TITLE
utf object property is rendered as `\u` on hover

### ISSUE THREAD

**Issue by scarf005** [microsoft/TypeScript#59037]
| object | type |
| - | - |
| ![image](https://github.com/microsoft/vscode-typescript-next/assets/54838975/29b3fb56-8370-4c87-bb69-b8ca433637af) | ![image](https://github.com/microsoft/vscode-typescript-next/assets/54838975/895aee5c-3b31-4592-8e28-f30ce7e7f474) |

when there's spaces or unicode symbols in property name, hover info does not display unicode as their 'rendered' form but in `\u` form.

## comparison to firefox console

![image](https://github.com/microsoft/vscode-typescript-next/assets/54838975/9f719110-a0e8-4ab0-a349-ef3639714a7d)

### Version

Typescript Version: v5.5.20240321
VSCode Version: 1.87.0

**Comment by mjbvz** [comment]
Confirmed that the response from TS appears to be over escaped:

```
\\uD55C\\uAE00\";\n    \"\\uD55C*\\uAE00\": \"\\uD55C*\\uAE00\";\n
```

**Comment by RyanCavanaugh** [comment]
Duplicate #57539
