### ISSUE TITLE
TS 5.5.2: JavaScript and TypeScript language service has been disabled after crashing repeatedly

### ISSUE THREAD

**Issue by bjornbacklund** [microsoft/TypeScript#59032]
### 🔎 Search Terms

JavaScript and TypeScript language service has been disabled after crashing repeatedly

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions SDK 5.3 and NuGet 5.5.2

TS language server crashes after I upgraded my csproj:s (from 5.3 SDK) to use NuGet version of TS (v 5.5.2).
I've restarted VS, cleaned and recompiled.
Any idea how I can track down what the problem might be?
VS Community 2022 (64-bit). Version 17.10.3
Windows 11.

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

VS reports:

"The highest TypeScript version from all loaded projects is the NuGet package's TypeScript version 5.5. Using this version for IntelliSense.
The JavaScript and TypeScript language service has been disabled after crashing repeatedly. You may see reduced IntelliSense support for your project. Please try reloading your solution to reenable the language service."

### 🙂 Expected behavior

Working language service

**Comment by jakebailey** [comment]
The nuget package was pulled and is being fixed.

**Comment by bjornbacklund** [comment]
Installed 5.5.3 and everything is back to normal. Thanks! Coding without LS was nearly impossible.
