### ISSUE TITLE
Allow type predicates to be within parenthesis

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#5904]
This is valid:
```ts
function isA<A>(x: any): (boolean) { return false; }
```
This doesn't parse:
```ts
function isA<A>(x: any): (x is A) { return false; }
```

**Comment by DanielRosenwasser** [comment]
What is the compelling scenario here?

**Comment by weswigham** [comment]
Consistency.

**Comment by mhegazy** [comment]
Do not think it would block any scenario, though I agree with consistency, would take a fix for it, but do not think it is worth keeping around.
