### ISSUE TITLE
TS 5.5 - Imports used by decorator output are removed

### ISSUE THREAD

**Issue by RomainLanz** [microsoft/TypeScript#59051]
### 🔎 Search Terms

remove import compilation decorator

### 🕗 Version & Regression Information

- This changed between versions 5.4 and 5.5

### ⏯ Playground Link

https://github.com/RomainLanz/typescript-output-issue

```sh
npm install
npm run build
```

### 💻 Code

```ts
import { DateTime } from "luxon";
import { column } from "@adonisjs/lucid/orm";

class User {
  @column.dateTime()
  declare createdAt: DateTime;
}
```

### 🙁 Actual behavior

When compiled the `DateTime` import is being removed (because it is only used as a type in our file), but the compilation of `@column.dateTime()` will use the import.

```ts
// ...

import { column } from "@adonisjs/lucid/orm";
class User {
}
__decorate([
    column.dateTime(),
    __metadata("design:type", typeof (_a = typeof DateTime !== "undefined" && DateTime) === "function" ? _a : Object)
], User.prototype, "createdAt", void 0);
```

### 🙂 Expected behavior

The import should be kept like in TypeScript 5.4.

```ts
import { DateTime } from "luxon";
import { column } from "@adonisjs/lucid/orm";
class User {
}
__decorate([
    column.dateTime(),
    __metadata("design:type", typeof (_a = typeof DateTime !== "undefined" && DateTime) === "function" ? _a : Object)
], User.prototype, "createdAt", void 0);
```

**Comment by RomainLanz** [comment]
Here is a discussion that may be related : https://github.com/microsoft/TypeScript/issues/54493#issuecomment-1615409830

**Comment by Max10240** [comment]
I met this too

**Comment by zanminkian** [comment]
That means a project which enables following features at the same time will be unusable under TS 5.5:
1. enable both `emitDecoratorMetadata` and `experimentalDecorators` in tsconfig.
2. use `declare` keyword for class properties.
3. `verbatimModuleSyntax` is false.

Some of my projects cannot upgrade to TS 5.5 too.

**Comment by jakebailey** [comment]
Using every-ts - npm, this bisects to #58366. @weswigham

**Comment by jakebailey** [comment]
It looks like this bit was added:

```ts
        if (location.flags & NodeFlags.Ambient) {
            return; // References within types and declaration files are never going to contribute to retaining a JS import
        }
```

Which explicitly skips marking references for `declare`.
