### ISSUE TITLE
Incorrect transform when namespace is empty

### ISSUE THREAD

**Issue by Roise-yue** [microsoft/TypeScript#59053]
### 🔎 Search Terms

namespace empty commonjs export 

### 🕗 Version & Regression Information

- This is the behavior in every version I tried（Including the latest version）

### 💻 Code

```ts
namespace x {}
export = x;
```

### 🙁 Actual behavior

```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

### 🙂 Expected behavior

```ts
var x = {};
module.exports = x;
```

### Additional information about the issue

The configuration information is as follows：
tsc V5.5.2
node.js:v20.14.0

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["es2023","dom"]
  },
  "include": [
    "TScorpus/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

package.json
```json
{
  "name": "tscfuzz",
  "version": "1.0.0",
  "main": "index.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "nyc --reporter=text --reporter=lcov mocha "
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.24.7",
    "@babel/core": "^7.24.7",
    "@babel/preset-env": "^7.24.7",
    "@babel/preset-typescript": "^7.24.7",
    "@types/node": "^20.14.9",
    "jshint": "^2.13.6",
    "mocha": "^10.4.0",
    "nyc": "^15.1.0"
  },
  "description": ""
}
```

**Comment by DanielRosenwasser** [comment]
`namespace` declarations come in two forms - instantiated and uninstantiated namespaces. When a namespace has no runtime statements, it is considered uninstantiated, and it therefore has no emit.

You can get an idea of what sorts of statements cause a namespace to be emitted or not ([playground link](https://www.typescriptlang.org/play/?#code/HYQwtgpgzgDiDGEAEwkG8CwAoJukHp8kBRMGAFwE9sBfbbUSWBZVTHPQpAFUpmiQB7YABtqHXFX5IAYoMFIAvCgCuYAEYQATgG56EpAEtg5bQDMWSAEIgt6OlgcNw0OIhTpseAkVIVKSFDkIKaQJl54eo76jK6WbBG4XABqtoYg6iLIACYQ8CK2IYbCiUgQAB4wglrkSFm15UpIAIwADFFOWLHM7gkGXMSVWtBQxahBIRBh5FCl5QDU81HejcqNAFTrSABMHTEuPaye-UQAwgVQUNCl+SCXSKfH3g40QA)):

```ts
namespace n {
    // Empty
}

namespace n {
    // Types only
    type Foo = number;

    interface Bar {}
}

namespace n {
    // Empty statement
    ;
}

namespace n {
    // Variable declaration
    export let x = 10;
}

namespace n {
    // Expression statements
    x++;
    x = x ** 2;
}

namespace n {
    // Classes
    class C {
    }
}
```

Output:

```js
"use strict";
var n;
(function (n) {
    // Empty statement
    ;
})(n || (n = {}));
(function (n) {
    // Variable declaration
    n.x = 10;
})(n || (n = {}));
(function (n) {
    // Expression statements
    n.x++;
    n.x = n.x ** 2;
})(n || (n = {}));
(function (n) {
    // Classes
    class C {
    }
})(n || (n = {}));
```
