### ISSUE TITLE
How to correctly obtain the type of return value after the decorator

### ISSUE THREAD

**Issue by XDUyhfu** [microsoft/TypeScript#59060]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

```typescript
import { Observable, of } from "rxjs";
const observable = (target: any, context: ClassMethodDecoratorContext) => function (...args: unknown[]): Observable<string> {
	return of<string>(target.apply(this, args))
}
class Test {
	@observable
	print() {
		return "print test";
	}
}
new Test().print().subscribe(console.log)
```

What I expect is that after using the observable decorator, the type of the return value of my method can be successfully deduced into Observable instead of the original string type.

what should i do

**Comment by MartinJohns** [comment]
Decorators can't currently change the types of whatever they're applied to. This would first require #4881 to be supported.
