### ISSUE TITLE
Investigate Adopting `--isolatedDeclarations` in TypeScript's Codebase

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#59097]
We would like to enable the `isolatedDeclarations` flag on the TypeScript codebase. One reason for this is simple dog-fooding (i.e. making sure we understand what users are experiencing). Another is to enable faster builds, whether that be through parallelized declaration emit, or through handing declaration emit off to a faster build tool.

First thing's first though - enable the flag, see what this feels like, and understand the pain points.

**Comment by escaton** [comment]
I came across this by accident, but have a suggestion to at least try `oxc-transform` for `d.ts` generation. I found it to be the fastest and closest to what tsc emits on my project (20k TS files).
