### ISSUE TITLE
TSC version 5.5.3 - output file looses tripple slash reference comment hence compilation fails

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/TypeScript#59094]
### 🔎 Search Terms

tripple slash reference path

### 🕗 Version & Regression Information

- This changed between versions 5.4.5 and 5.5.3

### 💻 Code

Steps to reproduce:

- clone https://github.com/dbaeumer/tsc-bug.git
- cd into tsc-bug
- npm install
- cd p1
- npm run compile

See everything compiles correctly and the `p1/lib/common/api.d.ts` file has a `/// reference` comment at the top

- run git clean -xfd .
- open package.json file in the workspace root and change the typescript dependency from `^5.4.5` to `^5.5.3`
- npm install
- cd p1
- npm run compile

### 🙁 Actual behavior

The compile fails complaining about the missing `Thenable` in `lib/common/api.d.ts`

```
lib/common/api.d.ts:1:32 - error TS2304: Cannot find name 'Thenable'.

1 export declare function foo(): Thenable<string>;
```

Also observe that the `p1/lib/common/api.d.ts` file has **NO** `/// reference` comment at the top

### 🙂 Expected behavior

Code compiles like it did under `5.4.5`

**Comment by MartinJohns** [comment]
This is working as intended and documented: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#simplified-reference-directive-declaration-emit

**Comment by jakebailey** [comment]
Yes, this is working as designed. Add `preserve="true"` to directives you intend to be included in the compiled output.

**Comment by jakebailey** [comment]
Based on the example and the project where it came from (https://github.com/microsoft/vscode-languageserver-node/blob/6d2a392547ea60db1723e027b4b55d268aa282ea/server/typings/thenable.d.ts), this could just be a type defined and imported, which would end up being handled properly. (Not sure why it's a global...)

**Comment by dbaeumer** [comment]
@jakebailey good question. It has always been that way I and don't really know why we went down that path 10 years ago ;-). I will look what the best way to fix it is.
