### ISSUE TITLE
filter type inference does not work with extra conditions

### ISSUE THREAD

**Issue by Axnyff** [microsoft/TypeScript#59109]
### 🔎 Search Terms

filter inference conditions predicate

### 🕗 Version & Regression Information

5.5.3

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ssl=16&ssc=113&pln=1&pc=1#code/C4TwDgpgBA4g9nAJgSWBAtlAvFA3gKCiKlEgC4oAiAcwUUoG5DiBnYAQ2AFcWLKWukAE6UoAHyoA3CEJADhlfAF98+UtABC7FGkw4CxEuAh8ARtsWG2nHmYvLV6qKgzZYdF5gladGJvgBjOAA7NigAS11eZ10AbQBdNwTVINDgKFokT2j4LLjEnEiMFgA6ADNwgBs0IQAKIr0APgjdEqcsDpo6SgBKJlSw6VkAZUEZXN90HI98twbSiuqZet1sZoa242xOzPooADJ9lowS624WbZxKIbkxkT6gA

### 💻 Code

```ts
type GoodItem = {
    type: "good";
    status: "super" | "verysuper"
}

type BadItem = {
    type: "bad"
    status: "bad"
}

type Item = GoodItem | BadItem;

const items: Item[] = []

const goodItems: GoodItem[] = items.filter(item => item.type ==="good");
const verySuperGoodItems: GoodItem[] = items.filter(item => item.type ==="good" && item.status === "verysuper");
```

### 🙁 Actual behavior

There is a type error because veryGoodItems is inferred to be Item[] instead of GoodItem[];

### 🙂 Expected behavior

There should be no type error

### Additional information about the issue

I'm not sure it should be classified as a bug but I was quite surprised when cleaning up my code thanks to the bump to typescript 5.5 to have this behavior.

Thanks in advance

**Comment by Andarist** [comment]
Type predicated have to refine their parameters *exhaustively*. It means that if the type predicate is supplied with a type matching the type predicate it won't ever return false.

In your case, it's very much possible to return `false` for a valid `GoodItem`. The else branch still contains the `GoogItem`:
```ts
const verySuperGoodItems: GoodItem[] = items.filter((item) => {
  if (item.type === "good" && item.status === "verysuper") {
    item;
    // ^? (parameter) item: GoodItem
    return true;
  }

  item;
  // ^? (parameter) item: Item
  return true;
});
```

**Comment by Axnyff** [comment]
Ok I get it, that's why this code won't compile either
```
type MyPred = (item: Item) => item is GoodItem

const myPred: MyPred = (item: Item) => {
    return item.type === "good" && item.status === "verysuper"
}
```

Anyway, this is definitely not a bug so I'll close my issue

Thanks a lot for your time
