### ISSUE TITLE
Make call to super() implicit within constructor

### ISSUE THREAD

**Issue by nippur72** [Microsoft/TypeScript#5910]
Calling `super()` within a constructor is a bit redundant and annoying... can we have it called implicitly if call to super is omitted? 

For example this
```TypeScript
class Manager extends Employee {
   constructor() {
      this.title = "The Manager";
   }
}
```
should be equivalent to 
```TypeScript
class Manager extends Employee {
   constructor() {
      super(); // call to default constructor added implicitly      
      this.title = "The Manager";
   }
}
```

(C# also does a similar thing and it's a nice feature).

**Comment by coreh** [comment]
What would be the default behavior for the parameters? Would they be passed on to the super class if the signature was the same?

**Comment by nippur72** [comment]
@coreh that would be a possibility, since you can always override it by making an explicit call to `super()`. It would do no harm to existing code.

**Comment by GoToLoop** [comment]
Gonna add that like C#, Java does the same too for empty super constructors!  :D

**Comment by mhegazy** [comment]
TypeScript is and should be a super set of JavaScript ES6 semantics has no implicit call for constructors, if TS supports that, a TS/ES6 class are not identical in behavior.

**Comment by GoToLoop** [comment]
As long as some handy feature isn't detrimental to ES6 compatibilty, I don't see why it should be thrown away.  
This proposal merely asks for TS' compiler to match the smartness of C# & Java compilers.  
It won't affect codes which don`t use this unburden feature.

**Comment by nippur72** [comment]
peraphs there could be a compiler flag like #274 to turn on and off features like this one.

**Comment by jasonwilliams200OK** [comment]
What if my intention was to call super() after the `this.title` assignment.
We cannot generalize when the user wants to call super() ctor, therefore this seems like bit over-engineering TBH.

**Comment by nippur72** [comment]
@jasonwilliams200OK the new behaviour would be:
- if there's no `super()` call and the class has a default constructor, instead of throwing an error, make a call to `super()` as the first thing in the constructor.
- else work as before

Your special case would be covered by calling super explicitly. (And btw, is it possible to refer to `this` before super?)

**Comment by RyanCavanaugh** [comment]
> What if my intention was to call super() after the this.title assignment in certain use-case.

Note that this is disallowed in ES6. You cannot access `this` until after the `super` call.

**Comment by jasonwilliams200OK** [comment]
@RyanCavanaugh, thanks, `this.` was indeed a bad example. The point was to retain user in control to defer super() call as first thing in the ctor.

**Comment by mhegazy** [comment]
As mentioned above, we would like to keep the semantics matching JS, and issue warnings to help guide the user the correct behavior.

**Comment by fis-cz** [comment]
Its bit old and you probably would not agree but what if super class argument less constructors will be called implicitly and the warning/error will be shown just in case the super class constructor requires parameters, even if these parameters are optional?

`
class Super {
    // no constructor declared at all or argument less constructor
   constructor() {
   } 
}

class Extension extends Super {

   constructor(optional?: string) {
      // super can be called implicitly as it does not require arguments
   }

}

class ExtensionOfExtension1 extends Extension {

   constructor() {
      super(""); // super class constructor requires arguments (even optional) so it must be explicitly called
   }

}

`
