### ISSUE TITLE
Typescript can't type regconize error

### ISSUE THREAD

**Issue by long-kr** [microsoft/TypeScript#59114]
### 🔎 Search Terms

"Wrong array type"

### 🕗 Version & Regression Information

- This is a dev time bug
- Typescript version: 5.2.2
- OS: Window
- Editor: VSCode

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.2.2#code/FAAhGMHsDsGcBcQEt4FMC2sQF4QG1QwiBvQoogBwCdIATAV3HgH0laAuEAIjQQEYATAGYuAGjLkQANwCGVJDOgs2nHqn7CxE8gEd6i+CgCenQUPGTKNdJEMwACjQbgAkh2694ZrZYC+FogBdAG5gMKg4RAALRVoAG1QAQVpaFzRMABVIAGE5RFwZWCNocBAACgkUDFhOUktqOkZldwR5aABzUMtZeQNWFvg2zu0QPQNjTmh6dAAjVCouyQabO2hmBudmgH5OVqQOxbBfPECAsEIAShwAPhBiXzDgGOh4pJS06qzcqngyqswLkA

### 💻 Code

```ts
// Your code here
 const items = [
    {
      product_id: productId,
      variant_id: variantId,
      quantity: submitQuantity,
      promotionProductId: promotionProductId,
    },
];
    
const handleAddItemsToCart = async (
    items: {
      product_id: string;
      variant_id: string;
      quantity: number;
      promotion_product_id?: string;
    }[] 
) => {}
  
handleAddItemsToCart(items)
```

### 🙁 Actual behavior

- When I pass `items` as argument into `handleAddItemsToCart` function. Typescript doesn't show me that I `promotionProductId` is not a valid field in array item. If I change `promotion_product_id?: string;` to not nulable `promotion_product_id: string;`, typescript will show me that I'm passing wrong field. 
- I'm new to typescript, please correct me if I'm doing wrong here.

### 🙂 Expected behavior

- Typescript will show error when passing item with field `promotionProductId: promotionProductId`.

**Comment by MartinJohns** [comment]
There is no bug here. Additional properties are allowed to exist on objects. This is working as intended.

**Comment by long-kr** [comment]
> There is no bug here. Additional properties are allowed to exist on objects, and `promotion_product_id` is optional and may be missing. This is working as intended.
> 
> See also the FAQ: https://github.com/microsoft/TypeScript/wiki/FAQ#indirect-excess-properties-are-ok

I see, thank you for fast responding. Is there a way for me to strictly type for object type? @MartinJohns

**Comment by fatcerberus** [comment]
No, see #12936

**Comment by long-kr** [comment]
> No, see #12936

Thank you! I was confusing a bit. Should I close the issue?
