### ISSUE TITLE
[Generic type] Function type of the returned result is not mapped to the parameter

### ISSUE THREAD

**Issue by inevermore** [microsoft/TypeScript#59124]
### 🔎 Search Terms

"Generic Type","Function","Parameters","ReturnType"

### 🕗 Version & Regression Information

- This is a bug
- This changed between versions v5.6.0

### ⏯ Playground Link
https://www.typescriptlang.org/play/?#code/C4TwDgpgBAKhDOwbmgXigbwFBSgQwC5MdcoBjAewBsKAnIxWgSwDsBzAbhIF8vcAjItlJR+dACYR6URq048uvLFkotE5PFSrwo6YRq1xEQkrhZ4AthCIByMpqpHgNgDSmoAMwCuLMkQA8MFAQAB7AECziOgDWECAUHrAISCgAfAAU0UQwAJS6qcQiuLQQwF60LJjc+DpOyJAA2jAAunyk3G64HVhKWKCQUADCDjp6JA0A0lCsULHxif0QCQbazSYi5lZEE2243r5Ei8v2WvCTzQ02+2Q2rQo9XFiSZFR4JZ4+ZMBMFJUnVABlYDMdhQQLBMIRKKzOLLYanFxQABiEPCkR08O0TQuV0+twyJAAjrQQERMWcWpdNhBbp0oAA6RlvNjwIgABTellKUng-iRqSwOSIACVSuUWPUIHyBcpVOoSvAvFRgLoVkCQWx0nYHE5XFAbHgbDVyL9EDkgA

### 💻 Code

```ts
type TestType = {
  a: {
    color: string;
  };
  b: {
    border: string;
  };
};

const calls = {
  callTest: {
    name: 'callTest',
    func: <T extends keyof TestType>(k: T) => {
      return {} as TestType[T];
    },
  },
};

type Calls = {
  [K in keyof typeof calls]: {
    name: K;
    func: typeof calls[K]['func'];
  };
};

declare const callString = <T extends keyof Calls, F extends Calls[T]['func']>(
  qry: Calls[T]['name'],
  ...args: Parameters<F>
): ReturnType<F>

const result = callString('callTest', 'a' as const)
```

### 🙁 Actual behavior

`result` type is `{color: string} | {border: string}`. The type of the returned result is not mapped to the parameter

- [ ] 

### 🙂 Expected behavior

`result` type is `{color: string}`.  The type should map to parameter 'a'

**Comment by jcalz** [comment]
I think for this to work TS would need to infer type arguments from indexed access types, but it doesn't.  This isn't considered a bug but a missing feature, which is possibly implemented at #20126 and/or #53017, neither of which have been merged.

**Comment by inevermore** [comment]
Looking forward the feature

**Comment by RyanCavanaugh** [comment]
The feature needed here is the more complex "Given a set of parameter types, produce what an equivalent call expression would have done". `ReturnType<F>` is definitely not that.
