### ISSUE TITLE
Using Parameters With Union Types

### ISSUE THREAD

**Issue by iair2750** [microsoft/TypeScript#59148]
### 🔎 Search Terms

parameters union-tpes

### 🕗 Version & Regression Information

- I am using "typescript": "^4.9.5"
- see the code below 

### 💻 Code

```
onValueChange: ((value: string[]) => void) | ((value: string) => void) | ((selectedItems: SelectOption[]) => void) | ((selectedItem: string) => void) | ((value: string) => void) | undefined

type ValueType = Parameters<NonUndefined<typeof onValueChange>>[0];
const value: ValueType = '0';
onValueChange?.(value);

```

### 🙁 Actual behavior

Argument of type 'string' is not assignable to parameter of type 'string[] & string & SelectOption[]'.ts(2345)

### 🙂 Expected behavior

I think the code should pass without errors

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template. It asks you to provide a playground link, and the code should be self-sufficiently working (if possible).

This is working as intended. When trying to call a union of functions your argument must match the argument type of each function, meaning an intersection: `string[] & string & SelectOption[]`, because the compiler doesn't know **which** function you're actually dealing with.

`Parameters<>` works distributive, you're getting a union of each argument type. That means the value can be a `string`, but the actual function you're calling is one that requires a `string[]`.

**Comment by iair2750** [comment]
Hi @MartinJohns and thanks for your response. 
Here is a [playground link](https://codesandbox.io/p/sandbox/typescript-gqnkj7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly8qowbq00063p6i2zoidlng%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly8qowbp00023p6iof96q83y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly8qowbp00033p6iq4w5mlve%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly8qowbp00053p6i9jeugkao%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly8qowbp00023p6iof96q83y%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly8qowbo00013p6ihyodu9yp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cly8qowbp00023p6iof96q83y%2522%252C%2522activeTabId%2522%253A%2522cly8qowbo00013p6ihyodu9yp%2522%257D%252C%2522cly8qowbp00053p6i9jeugkao%2522%253A%257B%2522id%2522%253A%2522cly8qowbp00053p6i9jeugkao%2522%252C%2522activeTabId%2522%253A%2522cly8qp9sv001h3p6i34rufz7r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly8qowbp00043p6iulfofgqd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cly8qp9sv001h3p6i34rufz7r%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cly8qowbp00033p6iq4w5mlve%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cly8qowbp00033p6iq4w5mlve%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). So the `Parameters<>` is working as expected, but is there a way to use a utility type for this case? It would be great if there were a way to extract the right type from a union of functions.

**Comment by MartinJohns** [comment]
> a way to extract the right type from a union of functions.

It **is** the right type. You have a union of functions, that means your function can **either** be `(value: string[]) => void` **or** `(value: string) => void`, but the compiler **can't know** which one it is. So whatever argument you provide must match **all** of the functions, so it doesn't matter which one it is - the argument works for both.
