### ISSUE TITLE
Switch type by generic enum

### ISSUE THREAD

**Issue by Howard-Lam-UnitedVanning** [microsoft/TypeScript#59149]
### 🔍 Search Terms

switch conditional type

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

A new way to define a generic type based on what another generic type extends by switch rather than chaining ternary operator

### 📃 Motivating Example

Current implementation
``` typescript
enum ModelType {
    DateTime,
    Date,
    Period,
}
type DateType< T extends (ModelType | undefined) = undefined> = T extends ModelType.Period ? DatePeriod : T extends ModelType.Date ? DateOnly : DateTime;
```

Potential new implementation
```
type DateType<T> = T switch {
    ModelType.Period => DatePeriod,
    ModelType.Date => DateOnly,
    _ => DateTime,
}
```
One should also be able to do this with a list of strings

### 💻 Use Cases

1. What do you want to use this for? For enforcing input model value type based on an option value
2. What shortcomings exist with current approaches? Long chain of ternary operators, hard to read
3. What workarounds are you using in the meantime? Long chain of ternary operators

**Comment by MartinJohns** [comment]
Duplicate of #51375.

**Comment by Howard-Lam-UnitedVanning** [comment]
Closing duplicate
