### ISSUE TITLE
Typescript Promise duplicate issue

### ISSUE THREAD

**Issue by cknightdevelopment** [Microsoft/TypeScript#5915]
I have been having a heck of a time getting es6 promises to work with Typescript in a ASP.NET 5 project. I installed the es6-promise.d.ts via tsd install es6-promise. However, I get errors about Promise being duplicated. When I hover on the Promise declaration in the es6-promise.d.ts file, I get the error below (see the blue section ac the bottom of the image). It seems to be conflicting with some typescript definition file from a Microsoft SDK, which is obviously not part of my project.

![error](http://i.stack.imgur.com/v09Pc.png)

Does anyone have an idea on why this might be happening or how I can fix this?

**Comment by DanielRosenwasser** [comment]
Are your build settings targeting ES6/ES2015? If so, that's the issue. You're getting the definition of `Promise` from our `lib.es6.d.ts`, in which case, you shouldn't need `es6-promise.d.ts` in theory.

**Comment by cknightdevelopment** [comment]
Thanks, that makes sense. This question can be closed.
