### ISSUE TITLE
discriminated union using non-literal-type

### ISSUE THREAD

**Issue by kim-jaedeok** [microsoft/TypeScript#59151]
### 🔎 Search Terms

"discriminated union", "discriminated union using non-literal-type"

### 🕗 Version & Regression Information

typescript@5.2.2

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAYg9nKBeKBvAUFKBDAXFAZ2ACcBLAOwHMBuTKAI3yLKtoF9bRIoAhbY5Gjp4o5AK4BbehGK0sjUZOmz0HdOi7QAqhTjlB8RAB9e-WugBmY8gGNgpPVGAQiAClQ4ANAyht8O8j0ASiEsUgsoV004COxkJBQAImYKSkSQjCwsbDks+ly2VXQgA

### 💻 Code

```ts
type Foo = {
  a: string;
  b: string;
};
type Bar = {
  a: number;
  b: number;
};

type Uinon = Foo | Bar;

function test({ a, b }: Uinon) {
  if (typeof a === "string") {
    a; // a is string
    b; // b is string | number
  }
}
```

### 🙁 Actual behavior

Inside the test function, b's type does not narrow down to string when a type is string.
why discriminated union only works with literal type?

### 🙂 Expected behavior

i think b's type should be string

### Additional information about the issue

https://stackoverflow.com/questions/78707864/type-narrowing-doesnt-work-when-using-a-non-type-literal-field-as-a-tag/78707873#78707873

**Comment by REDAMANS** [comment]
I don't think discriminated unions work the same way with non-literal-types, the documentation does not address the issue since they only did them with literal types, but there are other ways to achieve the same goal, for example, there's this workaround with type predicates:
```typescript
type Foo = {
  a: string;
  b: string;
};
type Bar = {
  a: number;
  b: number;
};

type Uinon = Foo | Bar;

function isObjFoo(obj: Uinon): obj is Foo {
  if(typeof (obj as Foo).a === "string")return true;
  return false;
}

function test(obj: Uinon) {
  if (isObjFoo(obj)) {
    obj.a; // string
    obj.b; // string
  }
}
```
This code is a little bit longer. I don't know if this will help, but it surely works.
