### ISSUE TITLE
empty return statement should be a compiler error when return type is specified

### ISSUE THREAD

**Issue by tejacques** [Microsoft/TypeScript#5916]
Currently this function compiles just fine

```.ts
function foo(x): string {
	return;
}
```

I understand that it's happening because `undefined` is a valid result for a variable of type `string`, and this sort of related back to #185, but a midway point could be to simply require the return statement to not be empty.

Similarly, this code fails to compile:

```.ts
function foo(x): string {
}
```

But this one compiles:

```.ts
function foo(x): string {
	if(false) {
		return;
	}
}
```

I think the expected behavior is that every branch should require an explicit return statement.

A side benefit of this is that you can get exhausting matching completeness basically for free:

```.ts
function foo(x: number | string | boolean): string {
	if(typeof x === 'number') {
		return x.toString();
	} else if (typeof x === 'string') {
		return x;
	}
}
```

Currently the above compiles, but if TypeScript required an explicit return in every branch for non void return functions, there would be a compiler error because there are remaining types in the union. However this would compile:

```.ts
function foo(x: number | string | boolean): string {
	if(typeof x === 'number') {
		return x.toString();
	} else if (typeof x === 'string') {
		return x;
	} else if (typeof x === 'boolean') {
		return ''+x;
	}
}
```

This is pretty nice! There is one edge case still -- because of the implicit `void` included in `x`, calling `foo(null)` or `foo(undefined)` will return `undefined`. I don't know what to do about this because it relates pretty heavily to #185. I think for now it can be ignored, and whatever resolution that (hopefully) happens there will take care of it.

**Comment by vladima** [comment]
```ts
function foo(x: number | string | boolean): string {
    if(typeof x === 'number') {
        return x.toString();
    } else if (typeof x === 'string') {
        return x;
    }
}
```
as a note, currently if you compile this code snippet with `--noImplicitReturns` flag you'll get error
```
test.ts(1,45): error TS7030: Not all code paths return a value.
```

**Comment by tejacques** [comment]
Ah -- that's exactly what I was looking for. Thanks @vladima! I'm guessing this will be in `1.8.0`?

**Comment by mhegazy** [comment]
yes. And it is already in `typescript@next`

**Comment by mhegazy** [comment]
so does this take care of the issue in OP?

**Comment by DanielRosenwasser** [comment]
I don't entirely think so; this does't cover accidentally omitting a return expression. But I shouldn't put words in @tejacques' mouth, so I'll let him speak for himself. :smile:

**Comment by mhegazy** [comment]
we can make `--noImplicitReturns` flag return statements with no expression if the function return type is not void or any. not sure if that would be too restrictive though.

**Comment by tejacques** [comment]
I personally don't think it's too restrictive because the programmer has already declared their intent by specifying a return type on the function. If it remains as a flag, then doubly-so because it is opt-in. It's also a lot clearer that it is intentionally returning `undefined` if it is explicitly written out.

**Comment by mhegazy** [comment]
@vladima thoughts?

**Comment by RyanCavanaugh** [comment]
Accepting PRs. Make this an error only under the `noImplicitReturns` flag

**Comment by basarat** [comment]
Just for the interest of people here. Note the original example: 

```ts
function foo(x): string {
    return;
}
```

will automatically be an error in `--strictNullChecks` : https://github.com/Microsoft/TypeScript/pull/7140 as I understand :rose:

**Comment by mhegazy** [comment]
thanks @martine!
