### ISSUE TITLE
Regression in types starting with 5.1

### ISSUE THREAD

**Issue by sag-tobias-frey** [microsoft/TypeScript#59176]
### 🔎 Search Terms

types regression not generic 

### 🕗 Version & Regression Information

- This is a type regression
- This changed between versions 5.0 and 5.1
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about breaking changes

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.1.6#code/PQKhCgAIUgBATApgBwE6IMYEMAuj6QCqAzopAAYCiAHhgDYCuS5kaA9gG4CWSBARgE9IAFQHJEAZQyouyHJC4A7YnizwAdFBDBwiasjap5SelnSQcYsgBEuAMzsAeYZD15F8YpADWiAWztILEUBABoiV2p3Tx8-AKCQgD5IAF5IAAoAbyhIXIBtAAUFRREAXQAuSAKAbnAAX0gAMkhs3PyipSIKyEVEDkRUWobm1ra86kqVGUUAc27e-sH6gEo84VLa0AhoOCQ0TFx8IlILAAsyReIuNhL2bl5IQRErKRk5YpVENU1oHT0DIyQEx0MxkSziSAAeQAtlwcI5COEANKRaJeXz+QKEZJpApcDDeBHhWwORwY+KIyBIxKJWq6fSGYyYEHmcE2RAoApmHBcLB0Zw4lo5drFWKYsoAfkqwkKpVRiA8XnSSjsAyIqzlEsg1g5yC5Rl5-OxeTl0tl8sVkDYfAAVph5FqdZzuYbnLLkmaCht6nT-oygczQRYrJAAJISSx0RAAMQYigwPJuzgjAijxAKqDYyGI4WEKajEkQ8jcCpi4cjkiLyYrhZwNNSGXY2el+cQ6cz2eWqWSTr1Lr51dTlbrmzAWkgACUUOhSIocF5EHDzqggpAVEPIHY4wnriUcKdcBYsL4vJ111HWB2vMECOgcAxUMpV8h+3Q1xXSDhQuPDM-X++h0-K1bXtH4YEyBA2AwABhQ4ZkMIRyyHWN40TRRIVQSEQITOotD+BlAWBIM2TDVsUJ3G4MKwu0E0HNMMyzHMRFbWsLTLFiqzzGsi3rNIkKjci0LotsGOzXMOLrSAAB9tV1fUeQHLih1rWlwHpAF5CUPBUDsLAMDIUMJywAB3VshTaSAtmFXIYAAQToOg2GMyAMGILwODMXk+DTcIpiUGYmOtGj53USAAHVTi4C9jLIYhTjYBg6AIA9+kgaFDFinAZATYNkH86ydmXRBwhfIxelQa9zD4TNfBKTpoWCIQ432eB8RwLBvLIbBSC8YyityttpFkeRsEUAByTTFFVVACpgfcyBkGZTnkcF-NCgAZNg2FnfyzjBMRdpwNhHjYfcggcpzN1-Vz3M8jq0wSAhTuXM5-OIH4LO0ay8gxSYsv87pGtqCyrIsnZbGIZAQSERQsGhMg7F-eaAKjD62i+izWsh6GADk4cQKV32mGZgbaUHPt2acDjwAgAFoRHONdECjBNDF61AsGQcQVy4LxFGOxzZjVdAAEcGC4dANEgABNBK0qwIQ1AIUgWaOiqgi8K5vLeixjuegZZpRsgmwGHk23COguF8NLtpGtzaaUWmbS8S3qs8ts1wYLnGTRmydAslX7TZwnRjByAfr8P7ie6fjEFJ3I6iGNS-UIwNWRDWOACEsBOPijNMitpKJ3aZN0ugThkxRErfGS4yQOwlHwUdtnAyCYLghDSIrbPSFs1AOYEXDfnU-0tIGXT9K7oce8QPuB7Yrw54VxxY+SbJcNBmBY+o+0F9XDnnPPMggvtJi+AYeQ+Uc4zNeZoP1aOx4yHrxv4HHOu1WRwPWfV-mkDAuAyAGDawwOOCC8AoKwTwPBVAiFWxDy+inJkph04Qljg2LOOcyAyUwb3fuCtfQEWQSyfaaCJLCVYiWS0sdawUJ4g2UO4dfrF1mIDEIQxBSMMKKKckgQYRwjoV+SAY1iDAOgmwaEBhehzlbMQMaiQY6tiGE0cybRRF8HEZIm4CocCyJDgVMYHQSi8OYtxHAeQRFiIkVInRsixqlEURWQSu4qLYXhI1cIjVVIWUTj6IAA

### 💻 Code

```ts repro
/**
 * @deprecated Use `Exclude` provided by TypeScript instead.
 */
export declare type Diff<T extends keyof any, U extends keyof any> = ({
    [P in T]: P;
} & {
    [P in U]: never;
} & {
    [x: string]: never;
})[T];
/**
 * @deprecated Use the version provided by TypeScript instead.
 */
export declare type Omit<U, K extends keyof U> = Pick<U, Diff<keyof U, K>>;

export declare type DeepPartial<T> = {
    [P in keyof T]?: T[P] extends (infer U)[] ? DeepPartial<U>[] : T[P] extends object ? DeepPartial<T[P]> : T[P];
};

export declare type IStyleFunction<TStylesProps, TStyleSet extends IStyleSet<TStyleSet>> = (props: TStylesProps) => DeepPartial<TStyleSet>;
/**
 * Represents either a style function that takes in style props and returns a partial styleset,
 * or a partial styleset object.
 * {@docCategory IStyleFunctionOrObject}
 */
export declare type IStyleFunctionOrObject<TStylesProps, TStyleSet extends IStyleSet<TStyleSet>> = IStyleFunction<TStylesProps, TStyleSet> | DeepPartial<TStyleSet>;

export interface IRawStyle {
    /**
     * Allow css variables, strings, objects. While we should have more strict typing
     * here, partners are broken in many unpredictable cases where typescript can't infer
     * the right typing. Loosening the typing to both allow for css variables and other things.
     */
    [key: string]: any;
    /**
     * Display name for the style.
     */
    displayName?: string;
    /**
     * @deprecated - The selectors wrapper is no longer required. You may add selectors as siblings to other
     * style properties, like most css-in-js libraries support.
     */
    selectors?: {
        [key: string]: IStyle;
    };
}

export declare type IStyleBase = IRawStyle | string | false | null | undefined;
/**
 * {@docCategory IStyleBaseArray}
 */
export interface IStyleBaseArray extends Array<IStyle> {
}
/**
 * IStyleObject extends a raw style objects, but allows selectors to be defined
 * under the selectors node.
 * @public
 * {@docCategory IStyle}
 */
export declare type IStyle = IStyleBase | IStyleBaseArray;

export declare type IStyleSet<TStyleSet extends IStyleSet<TStyleSet> = {
    [key: string]: any;
}> = {
    [P in keyof Omit<TStyleSet, 'subComponentStyles'>]: IStyle;
} & {
    subComponentStyles?: {
        [P in keyof TStyleSet['subComponentStyles']]: IStyleFunctionOrObject<any, any>;
    };
};
```

### 🙁 Actual behavior

Type 'IStyleSet' is not generic.
Type 'IStyleSet' is not generic.
Type alias 'IStyleSet' circularly references itself.
Type parameter 'TStyleSet' has a circular constraint.
Type 'IStyleSet' is not generic.
Type parameter 'P' has a circular constraint.
Type 'string' does not satisfy the constraint 'keyof TStyleSet'.
Type '"subComponentStyles"' cannot be used to index type 'TStyleSet'.

### 🙂 Expected behavior

No errors

### Additional information about the issue

I'm using **@fluentui/merge-styles** with version 8.5.15. This ships with the provided types above. This worked before Typescript version 5.1. Commenting out the custom **Omit** fixes the issue. However, I cannot change the code and cannot upgrade to a newer version right now.

**Comment by RyanCavanaugh** [comment]
```ts
export declare type IStyleSet<TStyleSet extends IStyleSet<TStyleSet> = {
```
Circular constraints like this never really fully worked in the first place and were always intended to be disallowed. See https://github.com/microsoft/TypeScript/issues/55743#issuecomment-1723909861
