### ISSUE TITLE
Can't emit types for subclassed abstract class: error TS4094

### ISSUE THREAD

**Issue by paulmillr** [microsoft/TypeScript#59184]
### 🔎 Search Terms

ts4094, abstract, class, property, protected, private

### 🕗 Version & Regression Information

- This is a crash
- Happens in the 5.6-dev, 5.x, 4.x, etc

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240708#code/JYWwDg9gTgLgBAbzgZwBYEMBMBWAbHdZOAfTSzzgF84AzKCEOAcgAEA7CAIwBsBTAegxpeyfmRy4mAbgBQvAB6RYcAMYQ2yeOIoBeEttxSgA

### 💻 Code

Cloneable repo: https://github.com/paulmillr/ts-bug-4094.

So there's abstract class which declares protected property (https://github.com/paulmillr/noble-hashes/blob/main/src/_md.ts#L33):

```ts
export abstract class HashMD<T extends HashMD<T>> extends Hash<T> {
  protected buffer: Uint8Array;
}
```

The class is subclassed (https://github.com/paulmillr/noble-hashes/blob/e804a2f9eff77c92e21705f876d99c3069037988/src/sha256.ts#L31C1-L32C1):

```ts
class SHA256 extends HashMD<SHA256> {}
```

The protected `buffer` property is not used as emit type anywhere. 

https://github.com/paulmillr/noble-hashes/blob/e804a2f9eff77c92e21705f876d99c3069037988/src/_md.ts#L33

### 🙁 Actual behavior

It doesn't compile, error emitted: TS4094: Property 'buffer' of exported class expression may not be private or protected

### 🙂 Expected behavior

It should compile

**Comment by paulmillr** [comment]
I think it's because SHA256 is not exported, but the error is not clear.

**Comment by weswigham** [comment]
Yeah, correct - because SHA256 isn't exported, we try to write an anonymous type for it in the output, but can't because of the protected properties in the class type, hence the errors.
