### ISSUE TITLE
TSX files don't get compiled when using systemjs jspm.

### ISSUE THREAD

**Issue by GauSim** [Microsoft/TypeScript#5918]
Ahoi, 
Im providing the `"jsx": "react"` flag in the compilerOptions for systemjs in the config.js file of jspm.
But the file don't get compiled, im always getting `"Unexpected token <"` Error, because of the jsx syntax.
For normal *.ts-files everything is working fine. Compiling the tsx file with tsc works fine as well.  

I have a repo with an example here:
https://github.com/GauSim/jspm-typescript-jsx-react

**Comment by mhegazy** [comment]
//CC @vladima, i thought that was fixed.

**Comment by vladima** [comment]
the issue is we don't parse literal values out of `typescriptOptions` from configuration. if [this line](https://github.com/GauSim/jspm-typescript-jsx-react/blob/master/config.js#L8) is replaced with `"jsx": 2` it should fix the issue

**Comment by Edward-Lombe** [comment]
This has to be better documented somewhere, currently takes a little too much head scratching and researching to find that the only thing wrong with my setup is that `"jsx" : "react"` needs to be replace with `"jsx" : 2`. Why?!

**Comment by mhegazy** [comment]
Passing that code into the TypeScript compiler would have flagged the issue ;)
