### ISSUE TITLE
verbatimModuleSyntax enables isolatedModules errors, even when isolatedModules is disabled

### ISSUE THREAD

**Issue by daniele-orlando** [microsoft/TypeScript#59186]
### 🔎 Search Terms

enum, verbatimModuleSyntax, isolatedModules

### 🕗 Version & Regression Information

**TypeScript: 5.5.3**

- This changed between versions 5.4 and 5.5

### ⏯ Playground Link

[Reproduction Project](https://github.com/user-attachments/files/16134226/ts-bug.zip)

### 💻 Code

See the attached project.

### 🙁 Actual behavior

_verbatimModuleSyntax_ = **false**
_isolatedModules_ = **undefined**

```sh
npx -p typescript@5.5.3 tsc --showConfig -p tsconfig.verbatime-false.json | grep isolatedModules
// outputs nothing.
// CORRECT

npx -p typescript@5.5.3 tsc --noEmit -p tsconfig.verbatime-false.json
// PASSES
```

---

_verbatimModuleSyntax_ = **true**
_isolatedModules_ = **undefined**

```sh
npx -p typescript@5.5.3 tsc --showConfig -p tsconfig.verbatime-true.json | grep isolatedModules
// outputs "isolatedModules": true.
// WRONG

npx -p typescript@5.5.3 tsc --noEmit -p tsconfig.verbatime-true.json
// FAILS
// ... has a string type, but must have syntactically recognizable string syntax when 'isolatedModules' is enabled.
```

---

_verbatimModuleSyntax_ = **true**
_isolatedModules_ = **false**

```sh
npx -p typescript@5.5.3 tsc --showConfig -p tsconfig.verbatime-true,isolated-false.json | grep isolatedModules
// outputs "isolatedModules": false.
// CORRECT

// BUT
npx -p typescript@5.5.3 tsc --noEmit -p tsconfig.verbatime-true,isolated-false.json
// FAILS
// ... has a string type, but must have syntactically recognizable string syntax when 'isolatedModules' is enabled.
```

### 🙂 Expected behavior

Setting `verbatimModuleSyntax: true` should not enable `isolatedModules`.
Setting `verbatimModuleSyntax: true` and `isolatedModules: false` should disable `isolatedModules`.

**Comment by daniele-orlando** [comment]
_At the attention of_: @weswigham

**Comment by RyanCavanaugh** [comment]
It's always been the intent of VMS to be a superset of IM, see https://github.com/microsoft/TypeScript/issues/51479#issuecomment-1335765803

**Comment by daniele-orlando** [comment]
Thanks for the clarification. 

I think it should be documented inside the doc that `verbatimModuleSyntax` implies `isolatedModules`. From what I can see, there is not mention in the [Reference TSConfig Documentation](https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax).

**Comment by daniele-orlando** [comment]
How/where can I report the issue about the documentation?

**Comment by jakebailey** [comment]
If you send a PR to https://github.com/microsoft/TypeScript-Website/blob/4503af71d2c4ae95cbc4188a4ce29ca272bd9f57/packages/tsconfig-reference/scripts/tsconfigRules.ts#L201 which marks `isolatedModules: trueIf("verbatimModuleSyntax")`, that would update the site to show that.

**Comment by daniele-orlando** [comment]
Thank you very much @jakebailey. Following you suggestion I opened a PR for the doc website.

https://github.com/microsoft/TypeScript-Website/pull/3179.

**Comment by daniele-orlando** [comment]
I close this issue as it is documentation issue.
