### ISSUE TITLE
`Index signature for type 'string' is missing in type` when extending `Record<string, unknown>`

### ISSUE THREAD

**Issue by effektsvk** [microsoft/TypeScript#59199]
### 🔎 Search Terms

"Index signature for type string is missing in type", "extending record"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (4.9.5, 5.0.4, 5.4.5, 5.5.3, v5.6.0-dev.20240709), and I reviewed the FAQ for entries "Common bugs that aren't bugs"

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.3#code/C4TwDgpgBACgTgewGYEsA2EDCCB2qDmUAvFAEoQDGCcAJgDwDOwcKO+ANFAK44DWOCAO44AfAChQkKNjwp8AWQCGYYmUrV6TFm07xk6LLgLiJ4aDIKqLcpSoBkUAN5iorqMAhMAYjgBcUAAoASmIRbj4BYTEAXzExKhwmKDQERRprQhJg-wzQpxc3BKSEpFVnNwqoRQAjCn9HRX8ARmj2AsqoGggkesaoACZW9qhYiqLgd09gH1Vs8P4hHDyAIhqKZeG4CGAuOCXyjqgAOhOStsPJ7xxzt1jooA

### 💻 Code

```ts
type ProfileConfig = Record<string, unknown>
type ConfigMap = Record<string, ProfileConfig>

type Config = ConfigMap & {
    testFn: () => unknown
}

const loadConfig = (): Config => {
    const conf = {
        abc: {a: 1},
        def: {a: 2},
    }
    const testFn = (): unknown => "abc"
    return {
        ...conf,
        testFn,
    }
}
```

### 🙁 Actual behavior

I'm getting an error on the line 14 (return of the `loadConfig` function):
```
Type '{ testFn: () => unknown; abc: { a: number; }; def: { a: number; }; }' is not assignable to type 'Config'.
  Type '{ testFn: () => unknown; abc: { a: number; }; def: { a: number; }; }' is not assignable to type 'ConfigMap'.
    Property 'testFn' is incompatible with index signature.
      Type '() => unknown' is not assignable to type 'ProfileConfig'.
        Index signature for type 'string' is missing in type '() => unknown'.(2322)
```

### 🙂 Expected behavior

I was expecting the `& { testFn: ... }` part to override the `Record<string, unknown>` from the `ConfigMap` type so I can add custom functions to the object.

I was also testing `type Config = Omit<ConfigMap, 'testFn'> & { testFn: ... }`, but with no success.

**Comment by Andarist** [comment]
> I was expecting the & { testFn: ... } part to override the Record<string, unknown> from the ConfigMap type so I can add custom functions to the object.

This is how it works. You can expect this to be valid and type-checked:
```ts
loadConfig().testFn()
```

The problem is that your return type annotation also expect this to be allowed:
```ts
loadConfig().whatever
```

But the object that you return doesn't have an index signature so it doesn't allow for arbitrary property access. This is what causes the error you are facing.

Depending on your needs this might work for you:
```ts
type ProfileConfig = Record<string, unknown>;
type ConfigMap = Record<string, ProfileConfig>;

type Config = ConfigMap & {
  testFn: () => unknown;
};

const loadConfig = () => {
  const conf = {
    abc: { a: 1 },
    def: { a: 2 },
  } satisfies ConfigMap;
  const testFn = (): unknown => "abc";
  return {
    ...conf,
    testFn,
  };
};
```

If you need to preserve the index signature though... they are lost when spreading, see: https://github.com/microsoft/TypeScript/issues/27273

You might do things like this though:
```ts
type ProfileConfig = Record<string, unknown>;
type ConfigMap = Record<string, ProfileConfig>;

type Config = ConfigMap & {
  testFn: () => unknown;
};

function toConfigMap<T extends {}>(obj: T): T & ConfigMap {
  return obj;
}

const loadConfig = () => {
  const conf = {
    abc: { a: 1 },
    def: { a: 2 },
  } satisfies ConfigMap;
  const testFn = (): unknown => "abc";
  return toConfigMap({
    ...conf,
    testFn,
  });
};
```

**Comment by effektsvk** [comment]
I see. Yes, the `toConfigMap` function works.

I will find out whether it is super important for us that the `configMap` is spread there, because I think the easier solution would be to do this:
```ts
type Config = {
  configMap: ConfigMap,
  testFn: () => unknown,
}
```
I'd rather not use any "workarounds" for such a small obstacle, to keep the code a bit cleaner.

So I'm assuming this isn't really a bug, since the index signature needs to stay as it is. We can probably close this issue, as it is already reported in the one you mentioned.

And thank you for a quick reply! It was very helpful!

**Comment by MartinJohns** [comment]
> You can expect this to be valid and type-checked:

But be aware of the unsoundness with such types. It's possible to assign whatever value to `testFn` using the index signature and a `string` typed key.
