### ISSUE TITLE
.focus() on an HTMLElement also sends a click event, which it shouldn't

### ISSUE THREAD

**Issue by jalqueza** [microsoft/TypeScript#59194]
### 🔎 Search Terms

.focus() on an HTMLElement sends a click event

### 🕗 Version & Regression Information

- Version 5.3.3

### 💻 Code

```ts
htmlElement.focus()
```

### 🙁 Actual behavior

focus on the htmlElement, WITHOUT a click event on the htmlElement

### 🙂 Expected behavior

focus on the htmlElement, WITH a click event on the htmlElement

**Comment by fatcerberus** [comment]
This is a runtime issue, it has nothing to do with TypeScript.
