### ISSUE TITLE
Enum value lookup by string variable should be typed as the enum type.

### ISSUE THREAD

**Issue by marcind** [microsoft/TypeScript#592]
I'm trying to map a value in a JSON blob that is serialized as a string to application logic code in TypeScript where the value is logically one of a set of values (and then map that back to JSON as a string to send back to a server). Naturally this maps quite well to enums. However, the type of enum value lookups via string variables is inferred as `any` whereas I would expect it to be the type of the enum. Here's an example:

``` typescript
enum Letter {
    A,
    B
}

var apiModel: { letter: string } = JSON.parse("{'letter':'A'}");
var deserialized = Letter[apiModel.letter]; // Expect inferred type as Letter, but inferred as any
var notALetter: boolean = deserialized; // This should not compile, but it does
```

I propose that a change be made so that member access of an enum 'type' via a variable typed as string should be an expression with a value that is that enum 'type'.

Some more examples of what I would expect

``` typescript
enum Letter {
    A,
    B
}

var n = 1;
var s = "A";

var fromN = Letter[n]; // Inferred string - as expected
var fromConst = Letter["A"] // Inferred Letter - as expected
var fromS = Letter[s]; // Inferred any - would expect Letter

var numberFromN: number = Letter[n]; // Fails to compile as expected
var numberFromS: number = Letter[s]; // Compiles fine as expected

var letterFromN: Letter = Letter[n]; // Fails to compile as expected
var letterFromS: Letter = Letter[s]; // Compiles fine as expected

var boolFromN: boolean = Letter[n]; // Fails to compile as expected
var boolFromS: boolean = Letter[s]; // Compiles fine - would expect failure

var stringFromN: string = Letter[n]; // Compiles fine as expected
var stringFromS: string = Letter[s]; // Compiles fine - would expect failure
```

**Comment by masaeedu** [comment]
@RyanCavanaugh Now that we have string literal types and union types, couldn't this be improved somewhat?

**Comment by RyanCavanaugh** [comment]
@masaeedu which parts specifically?

**Comment by masaeedu** [comment]
Just spitballing here, but maybe you could automatically generate a union string literal type composed of all the entries in the enum. Any string assignable to that type produces a number, any other string produces `any`.

**Comment by RyanCavanaugh** [comment]
You're aware that `Letter['A']` is already of type `number`, right?

**Comment by RyanCavanaugh** [comment]
Or you're talking about the case where you have `var x: 'A' | 'B'` and you're indexing by that?

**Comment by masaeedu** [comment]
@RyanCavanaugh Yeah, that one. That lets users dynamically pick the string, but still get the correct type.

**Comment by masaeedu** [comment]
Low priority, I know, but if you think it has a shot I could open an issue and attempt a PR.

**Comment by RyanCavanaugh** [comment]
I think we're already tracking this (essentially) at #6080.

Instead of special-casing enums, we can just say that indexing `x` by `"A"|"B"` produces the type of `x["A"]|x["B"]`
