### ISSUE TITLE
Many interfaces seem to be broken when `exactOptionalPropertyTypes` is enabled.

### ISSUE THREAD

**Issue by Gnuxie** [microsoft/TypeScript#59227]
### ⚙ Compilation target

ES2018

### ⚙ Library

lib.es.2018.regexp.d.ts

### Missing / Incorrect Definition

```typescript

interface RegExpExecArray {
    groups?: {
        [key: string]: string;
    };
}
```

### Sample Code

With `"exactOptionalPropertyTypes": true,` then this interface implies that for all properties of groups there will always be a string, which is wrong. I suspect that this pattern is largely endemic when using `exactOptionalPropertyTypes`. 

```typescript
const matrixToRegexp =
  /^https:\/\/matrix\.to\/#\/(?<entity>[^/?]+)\/?(?<eventId>[^?]+)?(?<query>\?[^]*)?$/;

const url = matrixToRegexp.exec(matrixTo)?.groups;
if (!url) {
  return ActionError.Result(`Not a valid matrix.to URL: ${matrixTo}`);
}
const eventID = url.eventId // eventID is typed as `string` when it should be `string | undefined`
``` 

Why is this a recommended setting when it actually quite dangerous[^1]? Especially when combined with `typescript-eslint`'s  [no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary-condition/) rule, which will use typescript's incorrect information to recommend removal of "redundant" checks. This is quite serious. 

[^1]: https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes
```


### Documentation Link

_No response_

**Comment by RyanCavanaugh** [comment]
Seems like you want to turn on `noUncheckedIndexedAccess`

**Comment by Gnuxie** [comment]
Hey, that's right, thank you!

**Comment by Gnuxie** [comment]
Maybe https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess should be recommended though
