### ISSUE TITLE
With noUncheckedIndexedAccess, "Object is possibly 'undefined'" returned on array object element access but not on const object element access

### ISSUE THREAD

**Issue by dandv** [microsoft/TypeScript#59228]
### 🔎 Search Terms

noUncheckedIndexedAccess
"Object is possibly 'undefined'"
JSON.parse

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed these FAQ entries:
- https://github.com/Microsoft/TypeScript/wiki/FAQ#assume-array-access-might-be-out-of-bounds-nouncheckedindexedaccess
- https://github.com/Microsoft/TypeScript/wiki/FAQ#additional-logic-in-nouncheckedindexedaccess

### ⏯ Playground Link

https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&ts=5.6.0-dev.20240710#code/JYOwLgpgTgZghgYwgAgLIE8DyAjAVsgbwChlkYB7cgLmRAFcBbbaIgXyKIXJAGcxk4NDDlwBtALrIAvMgkBuDmCjpCJAaICMkmQCkAypgByAOgAOcKDwgAKAOQEARBXIOaG1rYCUC0nE3jjZ2lkACY5UgB6COQHEQgEfmAeZFNyHh5gbAAbFVs6EAATCBhQCALbB2RgGFpyAFUQBAALeIBrMoBJQogADzKAQQQkdLUuXn4e4L8tYP0jMwsrO3osrK8fZB7AymCwyOiQcmQGcigUWLx4xOTU9Myc5DzukpAyiqqaw4bmts7uvoKg2GPDYyAQcDAzVUpDGPHIWQgxmgUFOdi6ADc4FlgAVkHNDF42EQgA

### 💻 Code

```ts
interface MyObj {
  foo: number
}

const a: MyObj[] = [];

try {
  a[1] = JSON.parse('{"foo": 1}');
  a[1].foo = 2;  // "Object is possibly 'undefined'" if noUncheckedIndexedAccess
  const x = a[1] = JSON.parse('null');
  x.foo = 2;  // no more "Object is possibly 'undefined'" if noUncheckedIndexedAccess
} catch {
  console.error('Invalid JSON')
}
```

### 🙁 Actual behavior

1. JSON.parse() can actually never return undefined
2. If there was a JSON parsing error, execution would never reach `a[1].foo = 2`, so `a[1]` *will* be defined at that point

![image](https://github.com/microsoft/TypeScript/assets/33569/0b7b003a-581f-48df-b72b-0a20544422d3)

### 🙂 Expected behavior

Assigning a[1] to x shouldn't change this (incorrect) error, but the error should not be returned in the first place.

**Comment by jcalz** [comment]
`JSON.parse()` returns `any`, which intentionally turns off type checking when indexing. Then that assignment propagates the type `any` from `JSON.parse('null')` all the way to `x` and `a[1]` really doesn't matter at all. So this has nothing to do with `noUncheckedIndexedAccess`.  Mostly this has to do with your expectation that `const x = y = z` should have `x` inferred to be the type of `y`, whereas actually it is inferred to have the type of `z`.
