### ISSUE TITLE
AsyncReturnType<T> a utility type designed to obtain return type of an asynchronous function.

### ISSUE THREAD

**Issue by Nitlix** [microsoft/TypeScript#59239]
### 🔍 Search Terms

typescript ts get returntype of an async function
typescript ts utility class to get return type of an async function
typescript asyncreturntype

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [ ] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

There should be a way for developers to extract complex asynchronous function returns on the go.
I've already designed the code that should be put in, however, let me quickly walk you through my line of thought.

### 📃 Motivating Example

Although this is a new Utility Type suggestion, I believe this is something the entire developer community could agree on and actually like to be added to TypeScript.

Have a look at this:
```ts
// Consider this function below
function getFoo(): "foo" {
    return "foo";
}
// Let's say this was actually a complex function, and 
// developers wanted to save time, and avoid duplication by using ReturnType<typeof getFoo> instead of "foo".
// This way, if the return type of getFoo changes, the return type of ReturnType<typeof getFoo> will change as well.

type fooReturn = ReturnType<typeof getFoo>; // "foo"



// However, when attempting the same approach with asynchronous functions,
// the ReturnType<typeof getUser> will not work as expected.
async function getLoo(): Promise<"loo"> {
    return "loo";
}

type looReturn = ReturnType<typeof getLoo>; // Promise<"loo">


// Now, there are definitely already some things that developers can do to avoid this, however
// all of them are not as clean as having a seperate brand new ReturnType for asynchronous functions.
// This is where the AsyncReturnType comes in. It is a utility type that 
// allows developers to get the return type of an asynchronous function.

// An example of usage could be a developer using Prisma and including many custom parameters in their returning data. 
// Prisma's types are autogenerated, and therefore the return type of the function would also be auto-generated, eliminating wasted development time.

// Here's the function.

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
    ...args: any
) => Promise<infer U>
    ? U
    : never;

// Working similar to ReturnType, AsyncReturnType will return the type of the promise that the function resolves to.

//This is useful as developers don't have to keep doing TypeScript trickery like this...
type ExtractPromiseType<T> = T extends Promise<infer U> ? U : never;

// Example usage
async function getLoo(): Promise<"loo"> {
    return "loo";
}

type LooType = ExtractPromiseType<ReturnType<typeof getLoo>>; // "loo"

// ...to avoid those errors.
```

Something that would extremely helpful is if this _one_ simple line could be added to TypeScript:
`type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (...args: any) => Promise<infer U> ? U : never;`

Many thanks for your attention! ;)

 

### 💻 Use Cases

**1. What do you want to use this for?**
    General development
**2. What shortcomings exist with current approaches?**
       No shortcomings, just developer annoyance.
**3. What workarounds are you using in the meantime?**
      The one described above.

**Comment by MartinJohns** [comment]
Did you read [No New Utility Types](https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types)?

**Comment by RyanCavanaugh** [comment]
See also https://github.com/microsoft/TypeScript/wiki/FAQ#pre-declined-feature-requests or the checklist in the issue template

**Comment by Nitlix** [comment]
_Clearly looks like you read the suggestion_. Very well done.

**Comment by RyanCavanaugh** [comment]
I realize that you wrote this:

> Although this is a new Utility Type suggestion, I believe this is something the entire developer community could agree on and actually like to be added to TypeScript.

but anyone wanting to add a utility type is going to think this is true of the type they're proposing, otherwise they wouldn't do it in the first place. The boundary we've set here is quite explicit and saying "Ah yes but this is a good one" isn't going to change that boundary.
