### ISSUE TITLE
Make new ChakraHost a generic extension point for platform hosting

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#5924]
A separate issue to follow on [my comment](https://github.com/Microsoft/TypeScript/commit/2799d2e561358321281669dc58e226f4d0981fee#commitcomment-14783754) on #5880 

> How about making this useful for other non-Chakra scenarios?
>
> You could make your actual Chakra host to export `ts.sys` directly instead of `ChakraHost`. Then have this code here at line 66 instead of the whole Chakra handling:
>
> ```typescript
> if (ts.sys) return ts.sys;
> ```
>
>The benefit is that a whole host of other platform-hosting scenarios become easily possible:
> * emulated environment in browser
> * [Rhino](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino)
> * [Nashorn](http://openjdk.java.net/projects/nashorn/)
> * [nginxScript](https://www.nginx.com/blog/launching-nginscript-and-looking-ahead/)
> * ActionScript/Flash
> * JScript.NET
> * [Jint](https://github.com/sebastienros/jint)
> * [IronJS](https://github.com/fholm/IronJS)
> * [Jurassic](https://github.com/prepare/Jurassic)

Also note that @DanielRosenwasser [commented](https://github.com/Microsoft/TypeScript/pull/5880#issuecomment-161199473) on the original PR:
> Should this be called `NativeHost`? It's not unreasonable to expect another host that exposes the same functionality.

And @yuit [replied](https://github.com/Microsoft/TypeScript/pull/5880#issuecomment-161402902):
> @DanielRosenwasser is that what interface `System` for ?

So that is exactly my suggestion: use `System` interface and `ts.sys` variable as an extension point for interested parties to implement a host for the whole `tsc.js` compiler.

Currently the way to run tsc.js on an 'exotic' host you need to emulate WScript or node, or now also ChakraHost with this latest feature. But only node emulation gives fully-functional host, with the main downside is lack of `watchFile/watchDirectory` in both WScript and ChakraHost. And node emulation is actually a bit of a pain, particularly with the need to implement [Buffer](https://github.com/Microsoft/TypeScript/blob/2799d2e561358321281669dc58e226f4d0981fee/src/compiler/sys.ts#L39) at least partially, as `getNodeSystem` in fact relies on it for BOF detection and whatnot.

When I need to run tsc from within an embedded/emulated/hosted environment, I am up for pain dealing with peculiarities of WScript or node semantics — even as I might not be using neither.

TypeScript has a lot of potential in enterprise, as a loose analog of VBA for user-authored scripting. And that often means compiling on-demand in embedded scenarios.

If you make `ts.sys` and `System` interface a proper extension point, it would help a lot.

**Comment by mihailik** [comment]
Just to make it clear how the code would look:

[/src/compiler/sys.ts at line 65:](https://github.com/Microsoft/TypeScript/blob/2799d2e561358321281669dc58e226f4d0981fee/src/compiler/sys.ts#L65)
```typescript
    export var sys: System = (function () {
      if (ts.sys) return ts.sys; // use host-provided implementation if available
```

So the host can do something like:

```
// pseudo-code
  ExpandoObject tsNamespace = new ExpandoObject();
  tsNamespace.setProperty('sys', myNativePlatformAbstractionImplementation);
  jsContext.GlobalObject.setProperty('ts', tsNamespace);
```

Whatever is the way to inject objects into the global scope, the host will inject ts, add sys onto it and let the tsc get on with it.

**Comment by vladima** [comment]
TypeScript currently already exposes a few extensibility points: [CompilerHost](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2629) and [LanguageServiceHost](https://github.com/Microsoft/TypeScript/blob/master/src/services/services.ts#L1016) for anyone who wants to embed TypeScript in their applications and customize interactions with the host environment. `sys` is an implementation detail for the default version of `CompilerHost` that is used by the batch compiler. We've already cleaned up most of the source code from direct usage of `sys` in favor of recommended `*Host` interfaces and I think that introducing another extensibility point without compelling reason will not yield anything but confusion

**Comment by mhegazy** [comment]
@mihailik are you working on supporting any of these engines at the moment? i would not be opposed to adding a new name to check when initializing System. i would not call it `ts.sys`, `NativeHost` or something more unique `TypeScriptNativeHost` maybe.

**Comment by mihailik** [comment]
@mhegazy yep, I am hosting typescript in low-end browsers almost since it was made public:

[Debugging TypeScript in browser](http://mihailik.blogspot.co.uk/2012/11/debugging-typescript-in-browser.html) - see IE6, Blackberry screenshot from November 2012:
![screenshot of typescript running on devices](http://4.bp.blogspot.com/-riutfX8t8B4/ULVfy2ANWOI/AAAAAAAAXLI/5LAUBpWTUCU/s640/20121128_004646-1.jpg)

That was a toy research which now turned into a project I am planning to ship properly next year: a portable environment for running code across wide variety of platforms. Typescript helps a lot, although not without its minor pains.

I've experimented with other exotic hosts, some of them having serious problems (like keyword collisions) and others just need a bit of emulation layer.

I have been picking ES3 incompatibilites in tsc/typescriptServices and submitting PRs, you might have seen those. I indeed care about hosting.

**Comment by mhegazy** [comment]
> I have been picking ES3 incompatibilites in tsc/typescriptServices and submitting PRs, you might have seen those. I indeed care about hosting.

I definitely have seen these. thanks for the contributions


> I've experimented with other exotic hosts, some of them having serious problems (like keyword collisions) and others just need a bit of emulation layer.

Do you run the command line compiler directly, or there are other uses? can you use the typescript API and provide an implementation for the compilerHost instead?

**Comment by mihailik** [comment]
Previously, like on that 2012 screenshot I did run `tsc.js` as-is, or recompiled with sourcemaps (emulating WScript or node at some points).

Currently I am running `typescriptServices.js` and thus my extension point is `ILanguageServiceHost`. Its IDE services are brilliant, but for a simple build function it takes a bit of extra effort, in both passing the inputs as well as deciphering the outputs. I'd much rather had the

**Comment by mhegazy** [comment]
The assumption that tsc.js/tsserver.js will only run on node and tsc.exe (chakrahost). these are the two scenarios we test. others one can get broken easily, you probably know this first hand with the ES3 fixes. for that i would recommend not relying on System, but using the CompilerHost/LanguageServiceHost, which has a better testing support in other tools already. 

If you chose to use tsc.js, implementing `ChakraHost` should do the trick. we can rename it if that makes it more engine agnostic, but that is just ascetics.

**Comment by mihailik** [comment]
I've seen several teams (some of them my former colleagues), and heard of others who want to express business logic in JavaScript. They say JavaScript, but what they really want is better, safer JavaScript. We all know what that means ;-)

Such use cases need an easy embedding API, not one full of compilation/IDE 'hairy' details: resolution, parsing/preparsing/SourceFile business, extracting various types of errors through different calls.

Here's a specific and very real use case. You have a complex financial instrument as an object graph in no-SQL db, and its custom business logic stored next to it as *.ts.

When such 'instrument' needs to be activated and used, you load *.ts, build it in a simple predictable way and marry to the data from the graph. And all that running inside a complex/legacy enterprise application, doing heaven knows what C++/C#/F#/Java.

`System` is ideal, `ChakraHost` is almost as good, except for:
* missing watchFile/watchDirectory
* CRLF assumption, potentially screwing up debugging/sourcemaps on Unix

ChakraHost name is not a concern, but accomodating for these functional features would be brilliant!

Huge thanks for looking into this, by the way. I immensely appreciate your openness and good will!

**Comment by mhegazy** [comment]
> System is ideal, ChakraHost is almost as good, except for:

if needed, these two issues should be fixed with one line change each, and should not cause any breaks in other places of the system.

> ChakraHost name is not a concern, but accommodating for these functional features would be brilliant!

I think you can get these scenarios working with small changes; we would love to accept PRs to clean up any of these.
