### ISSUE TITLE
Expose TypeChecker.getAwaitedType for public api

### ISSUE THREAD

**Issue by yeonjuan** [microsoft/TypeScript#59256]
### 🔍 Search Terms

getAwaitedType
public api

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

`TypeChecker.getAwaitedType` is currently an Internal API. I propose to expose it as a public API.https://github.com/microsoft/TypeScript/blob/46410044add2e9f53cea58e445de18dcda53443f/src/compiler/types.ts#L4971-L4972

### 📃 Motivating Example

In `typescript-eslint`, I'm working on improving the `no-unsafe-return` rule to check for types that returns `Promise<any>`.
- https://github.com/typescript-eslint/typescript-eslint/issues/8674
- https://github.com/typescript-eslint/typescript-eslint/pull/8693

To implement this feature, we need to get the awaited type of the promise. And it looks like this functionality is already implemented in `TypeChecker getAwaitedType`.
If getAwaitedType is provided as public, I think we can avoid duplicating the same logic in multiple tools that need similar functionality.

### 💻 Use Cases

1. What do you want to use this for? Use it in the typescript-eslint.
2. What shortcomings exist with current approaches?

4. What workarounds are you using in the meantime? There is a way to get the first type argument of a Promise generic. But it doesn't catch some cases. (https://github.com/typescript-eslint/typescript-eslint/pull/8693#discussion_r1672039318)

**Comment by RyanCavanaugh** [comment]
@rbuckton any objections? This seems fine to me

**Comment by jakebailey** [comment]
I've wanted to do this for a while to simplify ts-eslint (but apparently forgot to make an issue).
