### ISSUE TITLE
Unexpected return type of overloaded function

### ISSUE THREAD

**Issue by rotu** [microsoft/TypeScript#59251]
### 🔎 Search Terms

overload, multiple call signature

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about overloads

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&jsx=0&ts=4.8.4&q=5#code/JYOwLgpgTgZghgYwgAgHIHswG8BQz-IAUAHgFzIBG66ANhHCAJTlW30gDceBJ58NAZwjNkYKAFcIXAkTKiJwvnEFTu+XpWp0GI1ts44AvjhwATCAhpwoKAG7XkITKQxgcCdCAFhHmAIIgAJ7IALy+YIRikshwAjFBjMgA9Eny0QCEAPxZOCkyAHqZQA

### 💻 Code

```ts
interface Not{
    (x: boolean): boolean;
    (x: false): true;
    (x: true): false;
    (x: boolean): boolean;
}

declare var not:Not
const notAny = not(true as any) // true !?!?
//    ^?
```

### 🙁 Actual behavior

The type of `notAny` is inferred as `true`, the return type of the second overload call signature.

### 🙂 Expected behavior

The type of `notAny` should infer to `boolean`, as the first applicable signature without assignment to `any` (described as the expected behavior [here](https://github.com/microsoft/TypeScript/issues/59064#issuecomment-2218436861))

Alternately the type of `notAny` should infer to `boolean` as the last signature (and thus the type `ReturnType<Not>`).

### Additional information about the issue

Variation of this issue originally reported in #59064.

**Comment by MartinJohns** [comment]
This still sounds like a duplicate of #39833.

**Comment by rotu** [comment]
> This still sounds like a duplicate of #39833.

Looking at that issue again, I think it is.

I interpreted the referenced comment to mean "assignment *to* a parameter of type `any`" not "assignment *from* an argument of type `any`", so I may have missed that.

> as the first applicable signature without assignment to `any` (described as the expected behavior [here](https://github.com/microsoft/TypeScript/issues/59064#issuecomment-2218436861))
