### ISSUE TITLE
Inconsistent predicate type after using a function (TS 5.5)

### ISSUE THREAD

**Issue by RoxBow** [microsoft/TypeScript#59254]
### 🔎 Search Terms

"Infer type predicate", "predicate"

### 🕗 Version & Regression Information

This bug has been detected since the `5.5` release.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/LAKAxgNghgzjAEBBCAHAFleBTAHgFywDsATBAUQCcKB7C+AbwF9RJYEAhCqAN2u3yKl4lGnSYtoceAGEMFCAEss-AiXJVaDZiFAAzAK6EweBdULwFMZOigAKLBooAuYY4CUDUAEgKWPPopzB1ELQhg8KCMsal0kVAxQbRYzcPgCcJdrDHgAH3hOHj482Sh5JXgAXnhCLAB3fK5eWzcAblBQAHoAKngAeQBreC6O0AVdW3S8UPDIsGjYrKg3elB4NfgwFOoILAA6CGoAcwmscNbE7AgYZTGT1IUwiKiYhsKPFZB1ja2d-aO7vDnECMS7XTyfdabMLbPYHY6TNyJdogbquELDUbjSyLAFuZarSE-WH-BFtYGgm7jSbTJ5zF4FXjvAlrKEwGF-eGnQFkkFYK7KD5fVnsuG4xJAA

### 💻 Code

```ts
class Alpha extends Error {}
class Bravo extends Error {}
class Charlie extends Error {}

function isAlpha(error: Error) {
	return error instanceof Alpha
}

const test: Alpha | Bravo | Charlie = new Bravo();

/* Ok */
if(test instanceof Alpha){
    console.log(test);
} else if(test instanceof Bravo) {
    console.log(test);
} else {
    console.log(test)
}

/* Error */
if(isAlpha(test)){
    console.log(test);
} else if(test instanceof Bravo) {
    console.log(test);
} else {
    console.log(test)
}
```

### 🙁 Actual behavior

After using the `isAlpha` function, `test` is typed as `never` then trigger the error : 
`The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.`
So here we have a consistency issue about the type when we use a function (`isAlpha`) or not (inline `instanceof`).

### 🙂 Expected behavior

I would expect that behavior :
- in the `if` =>`test` typed as `Alpha | Bravo | Charlie`
- in the `elseif` => `test` typed as `Bravo | Charlie`
- in the `else` => `test` typed as `Charlie`

**Comment by MartinJohns** [comment]
This is working as intended. Your types are all structurally the same, so when it's not `Alpha`, it's also not `Bravo` or `Charlie`. See also the FAQ: [Why do these empty classes behave strangely?](https://github.com/microsoft/TypeScript/wiki/FAQ#why-do-these-empty-classes-behave-strangely)

You're now getting an error in 5.5 because of this new feature: [Inferred Type Predicates](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html#inferred-type-predicates)  
Before 5.5 the return type of your `isAlpha` function is inferred as `boolean`, so calling the method is not used to narrow any types. Since 5.5 the return type is inferred as `error is Alpha`, so it's used for narrowing.

**Comment by RoxBow** [comment]
Hi MartinJohns

`instanceof` is able to narrow the type, even when my classes are structurally identical. 
Whereas `isAlpha` doesn't, just wanted to point out that inconsistency.

Also, I tried to add some unique properties on my classes and the type detection doesn't work as intended even with `intanceof`:

```ts
class Alpha extends Error {
    aa = 'aa'
}
class Bravo extends Error {
    bb = 'bb'
}
class Charlie extends Error {
    cc = 'cc'
}

if(test instanceof Alpha){
    console.log(test); // test is Alpha & Bravo
} else if(test instanceof Bravo) {
    console.log(test); // test is Bravo
} else {
    console.log(test) // test is never
}
```

Note: Looks like the `const test: Alpha | Bravo | Charlie = new Bravo();` definition messes with the type inference because if I remove the `new Bravo()` part, it's only half failing: 
```ts
if(test instanceof Alpha){
    console.log(test); // test is Alpha
} else if(test instanceof Bravo) {
    console.log(test); // test is Bravo
} else {
    console.log(test) // test is Alpha | Bravo | Charlie
}
```

**Comment by RyanCavanaugh** [comment]
TypeScript can read your code, so when it sees
```ts
const test: Alpha | Bravo | Charlie = new Bravo();
```
it can tell that `test` is a `Bravo` and acts accordingly. Without the initializer (say you wrote `declare const test: Alpha | Bravo | Charlie`, each branch gets `Alpha`/`Bravo`/`Charlie` respectively, as expected
