### ISSUE TITLE
`"module": "nodenext"` causes dynamic imports to be double default-wrapped - e.g. `{ default: { default: Foo } }`

### ISSUE THREAD

**Issue by magicmark** [microsoft/TypeScript#59257]
@jakebailey says:

> ...this is a runtime issue with TypeScript's CJS import helpers, so the issue should be files on TypeScript.

### 🔎 Search Terms

dynamic import default wrapped

### 🕗 Version & Regression Information

`"typescript": "^5.5.3"`

### ⏯ Playground Link

https://stackblitz.com/edit/typescript-dynamic-import-issue?file=tsconfig.json,README.md%3AL6

And run this: `$ npx tsc --outDir build && node build/bar.js`

### 💻 Code

**`foo.ts`**
```javascript
export default function MyFoo() {
  return 'foo';
}
```

**`bar.ts`**
```javascript
(async function main() {
  const foo = await import('./foo.js');
  console.log(foo);
})();
```

**`tsconfig.json`**
```json
{
  "compilerOptions": {
    "module": "nodenext"
  },
  "include": ["src/**/*"]
}
```

### 🙁 Actual behavior

```javascript
const foo = await import('../src/foo');
console.log(foo);
```

This produces the following output:

```
[Module: null prototype] {
  __esModule: true,
  default: { default: [Function: MyFoo] }
}
```

### 🙂 Expected behavior

Expected behavior is that it produces the following output:

```
[Module: null prototype] {
  __esModule: true,
  default: [Function: MyFoo]
}
```

### Additional information about the issue

Initially raised here https://github.com/tsconfig/bases/issues/273

**Comment by rbuckton** [comment]
@weswigham, @andrewbranch: As far as I can tell, the emit for `foo.js` is correct given that it's a CommonJS module. Is the emit for the `await import` in `bar.js` correct?

```js
// bar.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
(async function main() {
    const foo = await import('./foo.js');
    console.log(foo.default);
})();
```

It looks like the `await import()` is returning a Module object with only a `default` property pointing to the entire `exports` of `foo.js`, and thus to access the default export requires `foo.default.default`. Changing this to a static `import foo from "./foo.js"` results in a transformation to `const foo = __importDefault(require("./foo.js"))`, so imports here are not consistent.

Does the correct behavior here depend on NodeJS statically recognizing the exports of `foo.js`?

**Comment by rbuckton** [comment]
This may be due to NodeJS static analysis. Removing `default` from the export in `foo.ts` results in proper nesting. Adding a second `export const bar = 0` results in the module object containing `{ bar: 0, default: { bar: 0, default: MyFoo } }`, so it looks like NodeJS does not recognize `default` as a valid static export.

**Comment by rbuckton** [comment]
As best as I can tell the types and emit are accurate, if an unfortunate outcome of NodeJS's `import(cjs)` rules: https://nodejs.org/docs/latest/api/esm.html#commonjs-namespaces, https://github.com/nodejs/cjs-module-lexer

**Comment by andrewbranch** [comment]
Yes, this is working as intended. This is ESM/CJS interop as Node.js designed.
