### ISSUE TITLE
Iterator and AsyncIterator missing Symbol.dispose method in esnext.disposable

### ISSUE THREAD

**Issue by jsonnull** [microsoft/TypeScript#59263]
### ⚙ Compilation target

ESNext

### ⚙ Library

esnext.disposable

### Missing / Incorrect Definition

Iterator and AsyncIterator are missing types for Symbol.dispose method.

### Sample Code

```TypeScript
function* myIterable() {
  using stack = new DisposableStack();
  stack.defer(console.log('cleanup'));

  yield 1;
  yield 2;
  yield 3;
}

{
  using iter = myIterable();
  //           ^^^^^^^^^^ error
  iter.next();
}
```

```
The initializer of a 'using' declaration must be either an object with a '[Symbol.dispose]()' method, or be 'null' or 'undefined'.
  Property '[Symbol.dispose]' is missing in type 'Generator<number, void, void>' but required in type 'Disposable'.ts(2850)
lib.esnext.disposable.d.ts(34, 5): '[Symbol.dispose]' is declared here.
```

### Documentation Link

The proposal lists these extensions:

- https://github.com/tc39/proposal-explicit-resource-management?tab=readme-ov-file#built-in-disposables

core-js implementation of the proposal includes the new built-ins:

- https://github.com/zloirock/core-js/pull/1151
- https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/esnext.iterator.dispose.js
- https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/esnext.async-iterator.async-dispose.js

**Comment by rbuckton** [comment]
These will need to be added to the new `BuiltinIterator` and `BuiltinAsyncIterator`, as `[Symbol.dispose]` and `[Symbol.asyncDispose]` are only present by default on built-in iterators and generators. They don't need to be added to `Iterator` or `AsyncIterator` as they are not requirements for the iterator protocol itself.
