### ISSUE TITLE
Incorrect formatting for single parameter in arrow functions

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#5926]
_From @xeoneux on December 3, 2015 18:20_

Using Format Code, `array.map(val=>val*2);` gets formatted to `array.map(val=> val * 2);`

There's no space between the parameter `val` and the `=>` after formatting.

_Copied from original issue: Microsoft/vscode#982_

**Comment by mhegazy** [comment]
thanks @SaschaNaz!
