### ISSUE TITLE
getSymbolAtLocation(node: Identifier) return undefined, in WatchCompilerHost, after change dependency source file

### ISSUE THREAD

**Issue by uasan** [microsoft/TypeScript#59270]
### 🔎 Search Terms

getSymbolAtLocation, createNameResolver

### 🕗 Version & Regression Information

- This is a crash 

### 💻 Code

File `A.ts`
```ts
export type Observable = Record<string, any>;

export interface User {
  id: number;
}

type Users = Observable[] & User[];

export const users: Users = [{ id: 1 }]
```

File `B.ts`
```ts
import { users as renameUsers } from './A.ts'
```

Calling `getSymbolAtLocation(renameUsers)` at the stage of `emit` the `B.ts` file, this returns the symbol for the first time, but after changing the type declaration in the `A.ts` file, calling `getSymbolAtLocation(renameUsers)` at the stage of `emit` the `B.ts ` file, always returns undefined, need to restart the compiler to do it all over again worked correctly.

This happens in all versions of TS known to me, for us this is a big problem, it seems that for language services in VScode this is also a problem, for this reason VScode often does not correctly refactor the code and does not find all the references for variables.

### 🙁 Actual behavior

getSymbolAtLocation(renameUsers) return undefined

### 🙂 Expected behavior

getSymbolAtLocation(renameUsers) return symbol

### Additional information about the issue

I can’t place the code on the playground because I need the compiler’s watch mode, because this is only reproduced in watch mode on subsequent compilation iterations after changing the files on which the file in which getSymbolAtLocation is called depends.

My research into this problem showed that the problem is in `checker.resolveName()` in the `location.locals` map, the `renameUsers` key disappears, so we get undefined, this looks like a TS bug.

**Comment by RyanCavanaugh** [comment]
> Calling getSymbolAtLocation(renameUsers) at the stage of emit the B.ts file, this returns the symbol for the first time, but after changing the type declaration in the A.ts file, calling getSymbolAtLocation(renameUsers) at the stage of emit the B.ts  file, always returns undefined, need to restart the compiler to do it all over again worked correctly.

We need the API-calling code side of this as well to confirm the repro. There are invariants here that might be getting violated from the calling side

**Comment by uasan** [comment]
@RyanCavanaugh, in the process of creating a test example, I noticed that the problem is on our side, in one place there was a mutation of escapedText, after that the symbol was not found, this is not a TS problem, I'm closing, thanks.
