### ISSUE TITLE
spread operator infer to wrong type with method override and generic

### ISSUE THREAD

**Issue by syi0808** [microsoft/TypeScript#59281]
### 🔎 Search Terms

generic spread 

### 🕗 Version & Regression Information

- This changed on version 5.3.0-dev.20231027

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.3&ssl=9&ssc=72&pln=10&pc=79#code/C4TwDgpgBAsg9gYwNYDECGDhwE4gOoCWwAFgBIQA2k2APDFALxQCuAdkq3AO6sB8jUABQBYAFBQoBALZgcwAPLYCAcwKs0FAFw0AKlAgAPYBFYATAM6wBMXoICUjfgAVscKQXMRdvMQ4bO0bGACDRoAJQgEHFMaJAgQOAAzWAAaKDRWEF4fUVBIKBc3Dwh4ZHRMHHwiMkpqOgE2Dm4+ARFxSRk5RRU1DU0oXX0jEwsrJht7RwLXd09vXynC2a8nQODQiKjsGLiE5Jg0jKzssTEo1nNgFmCtKABvMQkpRCRvQWfTZgoIfqXi7zSiQwWFwAH5+qVUMDKoQSOQqBBaDpeHZ+gA3OAEUyPKDPZBvD5fH7TIpzZGA6Fg34zYqQ8ogqpw2qI7yoqAYrFiAC+Age7TxSH6gkm-nuXIcaEsR25AG5TqJBJKQKwEFBEmxMAQ4KxJnyJMwbgA6AWCaSyIKCADkYDQJEtdkO5mVqtNnSC3VU6gofn4gj1EighqDiq4aCIHXNCiUno09jsOPFdjlonF9hlQA

### 💻 Code

```ts
type MockFactoryWithHelper<M = unknown> = (
  importOriginal:<T extends M = M>() => Promise<T>
) => Partial<Record<keyof M, any>>
type PromiseMockFactoryWithHelper<M = unknown> = (
  importOriginal: <T extends M = M>() => Promise<T>
) => Promise<Partial<Record<keyof M, any>>>

const util: {
  mock<T>(module: Promise<T>, factory?: MockFactoryWithHelper<T>): void
  mock<T>(module: Promise<T>, factory?: PromiseMockFactoryWithHelper<T>): void
} = {
  mock: (() => {}) as any
};

(async function() {
  util.mock(import('path'), async (importOriginal) => ({
    ...(await importOriginal())
  }));
})();
```

### 🙁 Actual behavior

Typescirpt throw error like `Spread types may only be created from object types.(2698);` on line spread syntax

### 🙂 Expected behavior

Typescirpt should not throw error on inline spread syntax.

**Comment by RyanCavanaugh** [comment]
The error here is because you're trying to spread a `never`. This is not a syntax error.

**Comment by syi0808** [comment]
> The error here is because you're trying to spread a `never`. This is not a syntax error.

But it works well on version 5.2.2. Return value of importOriginal should never be deduced as `never` type.

**Comment by syi0808** [comment]
And if this is an unintended bug, I would love to contribute. Where can I find the changes to the 5.3.0-dev.20231027 distribution version?

**Comment by RyanCavanaugh** [comment]
`every-ts` can bisect to a specific commit

**Comment by syi0808** [comment]
I'll try it within a week. Thanks for sharing.

**Comment by Andarist** [comment]
Given that overloads are generally picked from the top to the bottom. Shouldn't this be fixed at the definition site of this `mock` method? If you swap those overloads it works OK: [TS playground](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240715&ssl=21&ssc=6&pln=1&pc=1#code/C4TwDgpgBAsg9gYwNYDECGDhwE4gOoCWwAFgBIQA2k2APDFALxQCuAdkq3AO6sB8jUABQBYAFBQoBALZgcwAPLYCAcwKs0FAFxQaAFSgQAHsAisAJgGdYAmL0EBKRvwAK2OFIIWIe3gBoxjgwuaNjABBo0AEoQCDhmNEgQIHAAZrC+UGisILy8ANxioJBQru6eEPDI6Jg4+ERklNR0Amwc3HwCIuKSMnKKKmoa2noGxqaW1ky2Dk4lbh5ePv6igS7z5TTOIWER0bHY8YnJaTAZWTm5BaJisawWwCxhWlAA3mISUohIPoKfZswUCDaUoLby6PxQFIYLC4AD8wPWXkqqGhtUIJHIVAgtHB9m0ADc4AQzFcPl8fn8AUC5mVFuCMlCanDtMjqjC6hjGtifHioITiVcAL4CN7dT7IbSCGZBV6CxxoKznZaCq5iMwxCghaApNiYAhwVhQZQQYBbEjwf6AhwI2neF5QTjYKQaAgALwggjAaBI2nuSlYyl5frUyiggvyYjEggVIFYCEhurCBqEjlFEmYTwAdOKkIJjabvcQLVSHGcLLH44JpLJQv1VOoKKshGmJFBM+3o1w0EQejWFEp6xoHPZlhI5fYhfYHKrrrOgA)

Similarly, it works OK if you combine those 2 overloads into a single signature: [TS playground](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240715#code/C4TwDgpgBAsghiARhACgJwPYFsCWBnCAHgBUA+KAXimKgB8p1t8iyBuAWACgvRJYMAxgGsAYnAHAMaEAHUcwABYAJCABtIaQjEpQArgDsh+jAHd95KgAouUKDixgpwAPJocAcxz64qgFxQSKAgAD2AIfQATPFgdGFJLAEpKckZcAhJSABouJIpyeCRUTDSiFDg0YBwfQgAlCAEpCMIhCBAMADNYTKg4fRBSAY5uTgb9PGA9Sr8oAG8bKCxBIQzLRYjdVQh-VOYM7vbxSWkAfn8YJbEJKVl5ZTUNDIT-ADcMHAihgF8dOc5bReE-ksiWSs0+STg0V6IGynE+Qy4EXqqnK0HaBgkOAw+ig7ggwDKinO602iW2xV2MygxjQWB8OAAXhBLGA4Ip-OM3Pp3E8oJyvO4oJ9SAjOJZISB9AIoOipZVsVAQb9bLopgA6AFCSx4glshTEjbMhLdCVSxX2RwVVweLw+XLkSzK2xQNWu8UmODyOwOJzWzzeVSJY3zcEJL4JRJDIA)

**Comment by RyanCavanaugh** [comment]
I agree with @Andarist 's comments in the PR - this doesn't seem like a bug.
