### ISSUE TITLE
This comparison appears to be unintentional because the types 'U[K]' and 'T[K]' have no overlap.ts(2367)

### ISSUE THREAD

**Issue by FasalMohammadh** [microsoft/TypeScript#59291]
### 🔎 Search Terms

This comparison appears to be unintentional because the types 'U[K]' and 'T[K]' have no overlap.ts(2367)

### 🕗 Version & Regression Information

- This is a crash
- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because i just need this utility function and randomly this error occured

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABAWwKYCcDmqBCBPAHgBUAaRAVTIGlFUAPKVMAEwGdEBRB9AQ2gIDWqPHGCJSiISLHkAfLIAUAKESIe6XngCMALnEBtALokVajTzwAmPeSMnVUvVSUBKPQqKIAZBRdHEAN6mEAisUIhgqADuAILmeO6ePuR+hogAvIhGANxKpsBw6IgKIWBhiDCMyIiiZppaLoGmqqXlyDxQEAAWGXUWlgB0wDAsCgowjemyFfpSaekLFVWzwoYuuaqqMGIKUHgADqi17Z09AISLAETgzKjDkcyXjUGbm5Gx8QP7IKxdCgGIAZAyqoZBkIEDE7dRAAX3WzVhphheVU6FQUBA6CQ7zimlyyKU9H2hXCALQWFweFh2SAA

### 💻 Code

```ts
function mergeBy<T, U, K extends Extract<keyof T, keyof U>>(
  array1: T[],
  array2: U[],
  key: K
): (T & U)[] {
  const newArray: (T & U)[] = [];

  for (const item of array1) {
    const match = array2.find((i) => i[key] === item[key]);
    if (typeof match !== "undefined") {
      newArray.push({ ...item, ...match });
    }
  }

  return newArray;
}

export { mergeBy };
```

### 🙁 Actual behavior

i need to find the matching element with the same key (eg:- same id) in the second array in order to merge them and form a one array but inside array.prototype.filter when i compare both values to find the match ts throws this error

ts version 5.5.3

### 🙂 Expected behavior

it shouldn't throw this error in here i think

**Comment by RyanCavanaugh** [comment]
This is the intended behavior. Most of the time you have two type parameters, they're for different purposes, so this is most likely to be an error. A type assertion is appropriate if you're doing this on purpose.

**Comment by FasalMohammadh** [comment]
Got it, thanks for explaining.
