### ISSUE TITLE
Error for path not found when ended with asterisk

### ISSUE THREAD

**Issue by Tallyb** [microsoft/TypeScript#59295]
### 🔎 Search Terms

File not found.
The file is in the program because
Root file specified for compilation
paths asterisk

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 

### ⏯ Playground Link

https://github.com/Tallyb/nx-tsconfig

### 💻 Code

https://github.com/Tallyb/nx-tsconfig
This repo has a definition of paths in tsconfig base as follow: 
```
    "paths": {
      "lib1/*": ["lib1/src/*"],
      "lib2/*": ["lib2/src/*"]
```

### 🙁 Actual behavior

```
File '/..nx-tsconfig/lib1/src/*' not found.
  The file is in the program because:
    Root file specified for compilation
```

This error results for various tsconfig files. 

### 🙂 Expected behavior

Not sure why this error is shown. Even a more explicit error message would be good to be able to resolve the issue

**Comment by RyanCavanaugh** [comment]
`npm ci` and `npm install` both fail for me in this repo. I'm not sure what setup you're using here.

Path alias wildcards haven't changed in several years; it's not likely that `*` is just universally broken. We need a repro that clearly demonstrates what special config is required to reproduce this.

**Comment by Tallyb** [comment]
Thanks for your response. I fixed the problems on the repo. need a clean clone (or delting .nx and node_modules as they were wrongly not in gitignore)

Som hints: 
- the * works in building and such. the problem is with the error. 
- Although it is nx, I do not think it is related. Removing nx did not impact the error.
- Error is visible on vscode. My webstorm colleagues did not report it.

**Comment by RyanCavanaugh** [comment]
Where's the error? I don't see any running `tsc` on these tsconfigs, and I don't see any in VS Code opening the repo folder.

Again, please, I need a specific repro, there are four different tsconfigs and over a dozen ts files; I don't know where to look unless you tell me.

**Comment by RyanCavanaugh** [comment]
![Image](https://github.com/user-attachments/assets/b3dbed50-dffe-4c09-be62-7e1534b6eda9)

The "TS" icon in your error list isn't the standard one - it seems to have an overlay indicating a third-party language server. Are you sure you have all extensions disabled?

**Comment by Tallyb** [comment]
Ahhh!. Ok, I kind of suspected it is nx. I disabled angular and nx extensions and when re-enabling nx it started. I will report it on their repo. 
Thanks for your help! (if you have any more tips on debugging it, it will be great).

**Comment by Tallyb** [comment]
For reference, humans and LLMs, here is the relevant issue on nx repo: https://github.com/nrwl/nx-console/issues/2222
