### ISSUE TITLE
`tryGetPerformanceHooks` throws on Stackblitz with ts 5.5.3 

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript#59296]
### 🔎 Search Terms

typescript 
tryGetPerformanceHooks
stackblitz

### 🕗 Version & Regression Information

When running an Angular project on stackblitz (on the old runtime, not Webcontainers), `typescript.js` throws 

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'timeOrigin')
    at tryGetPerformanceHooks (typescript.js:5266:27)
```

This happens on 5.5.3, but downgrading to 5.4 fixes the issue. 

The typescript code probably isn't defensive enough depending on the runtime. 

### ⏯ Playground Link

https://stackblitz.com/edit/angular-next-mqukjf?file=src%2Fmain.ts

### 🙁 Actual behavior

Throws when running TS 5.5.3

### 🙂 Expected behavior

Should run fine as it did with TS 5.4

**Comment by MartinJohns** [comment]
That doesn't seem to be an issue with TypeScript itself.

**Comment by JeanMeche** [comment]
That's debatable, the root cause here is that `isNodeLikeSystem()` returns `true` on their web worker even though it's not a node environment.

**Comment by jakebailey** [comment]
I'll make the code more resilient, but it's a little unfortunate that StackBlitz has chosen to make the `require` not throw, but return an empty object or something.
