### ISSUE TITLE
Incorrect Error Message: "Cannot assign to 'name' because it is a constant" Instead of "Identifier 'name' is not defined" for Undefined Identifier Assignment

### ISSUE THREAD

**Issue by Roise-yue** [microsoft/TypeScript#59317]
### 🔎 Search Terms

TS2304 TS2588 constant

### 🕗 Version & Regression Information

- This changed between versions _5.4.5_ and _5.5.3______

### 💻 Code

```ts
// function A():void{
//     let yso: string = "bob";
//     name = "smith";
// }

let yso: string = "bob";
name = "smith";

```

### 🙁 Actual behavior

error massage:
```ts
TS2588
Cannot assign to 'name' because it is a constant.
'name' is deprecated.
```

### 🙂 Expected behavior

error massage:
```ts
can not find 'name'  / 'name' is not defined
```

### Additional information about the issue

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "lib": ["es2023","dom"]
  },
  "include": [
    "TScorpus/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by MartinJohns** [comment]
> * This changed between versions _5.4.5_ and _5.5.3______

I don't see any difference in behaviour between these versions.

This is, unfortunately, working as intended. In the browser context you have a global `name` variable. See also #18433.

**Comment by Roise-yue** [comment]
Thank you for your response to this question. I didn't quite understand why name is a constant before, but now I have a better understanding of this issue.
