### ISSUE TITLE
Auto complete and auto import not work (ReactJS, ChakraUI)

### ISSUE THREAD

**Issue by TonyStark** [microsoft/TypeScript#59321]
Problem: I am developing react JS project with Chakra UI. When i try to type `Box, Grid, GridItem` or any other component of chakra ui, vs code cant auto complete or auto import those component from chakra ui module.

Screen Shot:
![Screenshot from 2024-07-17 11-49-44](https://github.com/user-attachments/assets/32c30de8-df87-4a7e-a0ea-b9ece1523728)

Does this issue occur when all extensions are disabled?: Yes
- Even occur when all extensions are enabled

VS Code Information:
```
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.6-76060506-generic
```
Installed Extension:
```
ES7+ React/Redux/React-Native snippets
npm Intellisense
Prettier - Code formatter
```
TypeScript Version: 5.5.2

Steps to Reproduce:

1. Installed VS Code. Installed reactJS, ChakraUI. Open Layout.jsx.
2. I type "Gri" to check if it auto import/complete `Grid` component from ChakraUI

**Comment by RyanCavanaugh** [comment]
We need a project that reproduces the issue; this behavior may or may not be correct based on your configuration

**Comment by TonyStark** [comment]
@RyanCavanaugh 
Here you can clone repo >> https://github.com/TonyStark/vite-start-d15-CRUD-with-router

**Comment by TonyStark** [comment]
For fresh start i have created `vite-project` by using `pnpm create vite` > React > Javascript
Later `cd vite-project` and installed chakra ui `pnpm add @chakra-ui/react @emotion/react @emotion/styled framer-motion`

**Comment by RyanCavanaugh** [comment]
TS Server log says

> Info 1142 [15:22:35.143] AutoImportProviderProject: attempted to add more than 10 dependencies. Aborting.

You likely need to change this setting from "auto" to "on" and verify you don't have any exclusion patterns that would exclude the target files



![Image](https://github.com/user-attachments/assets/5248c317-f1fb-4d2e-8916-9517d1e64730)

With proper configuration

![Image](https://github.com/user-attachments/assets/f6207842-fb08-4c72-a729-7413c684b9d9)

**Comment by TonyStark** [comment]
@RyanCavanaugh 
Hello,
I set JSON Auto import as `on`
and then restart vscode.
but still not getting auto suggestion.
![Screenshot from 2024-07-27 09-21-22](https://github.com/user-attachments/assets/5e0295c5-30d8-4070-85ff-6bafad1b4f01)
i also scrolled through end, but no `Grid` components suggested in that

**Comment by TonyStark** [comment]
I think it happened in linux version only

**Comment by RyanCavanaugh** [comment]
We've never really had a Linux-specific auto-import bug. Did you also modify the path exclusion list?

**Comment by TonyStark** [comment]
this is my current settings, rest are as default
```
{
  "javascript.updateImportsOnFileMove.enabled": "always",
  "[javascriptreact]": {},
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "prettier.printWidth": 8000,
  "editor.minimap.enabled": false,
  "tabnine.experimentalAutoImports": true,
  "explorer.confirmDelete": false,
  "editor.multiCursorModifier": "ctrlCmd",
  "typescript.preferences.includePackageJsonAutoImports": "on"
}

```
