### ISSUE TITLE
`null` prop with `satisfies`, `strictNullChecks: false`  + `noImplicitAny: true` gives any report

### ISSUE THREAD

**Issue by Grohden** [microsoft/TypeScript#59343]
### 🔎 Search Terms

satisfies, implicitly has any type, strictNullChecks, noImplicitAny

### 🕗 Version & Regression Information

- Tested this from 4.9.5 to 5.5.3 in playground

### ⏯ Playground Link

https://www.typescriptlang.org/play/?strict=false&strictNullChecks=false&ts=5.5.3#code/C4TwDgpgBAYg9nKBeKBvAUFLUwCc5gD8AXFAM7C4CWAdgOZQA+UNArgDbvoC+66AxnBoUoAMwTI0mLHgKk2nHuQCGwKmVFUIZWAiA

### 💻 Code

```ts
type Foo {
    prop?: string | null
}

const foo = {
   prop: null // Object literal's property 'prop' implicitly has an 'any' type.
} satisfies Foo
```
And tsconfig with `strictNullChecks: false, noImplicitAny: true`

### 🙁 Actual behavior

our typescript setup is a little weird here and we kinda ended up with these flags:

```json
{
    "strict": false,
    "strictNullChecks": false,
    "noImplicitAny": true
}
```

with these, using the satisfies operator makes the null prop be considered any instead of null

### 🙂 Expected behavior

Don't know how the internals work, but I would expect it to be inferred to null even though I'm not using `strictNullChecks: true`

### Additional information about the issue

I can fix the code with a cast:

```typescript
const foo = {
   prop: null as null
} satisfies Foo
```

**Comment by RyanCavanaugh** [comment]
This is consistent, albeit admittedly somewhat confusing. The error accurately reflects what's happening (`foo.prop` is `any`) and is consistent with the design of `satisfies`, which is that the inferred type of `foo` shouldn't be different from if you had written
```ts
const foo2 = {
    prop: null
};
```
which is also an implicit `any` error.

> I would expect it to be inferred to null even though I'm not using `strictNullChecks: true`

Sort of the whole point of `strictNullChecks` is that the type `null`/`undefined` doesn't really exist and shouldn't be inferred.

**Comment by Grohden** [comment]
@RyanCavanaugh oh... would be nice to have a better message (I thought I was crazy), but if thats expected then ok 🙏 

should I close this one?

**Comment by Grohden** [comment]
@RyanCavanaugh one thing though.. shouldn't `const foo: Foo = { prop: null }` also give the same issue?

**Comment by Grohden** [comment]
I'll close it, feel free to open if needed :D
