### ISSUE TITLE
es6-promise Promise.all error

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#5935]
When I use the es6-promise type definitions, given this code:

``` js
Promise.all([
    Promise.resolve('foo'),
    Promise.resolve(['bar'])
]);
```

I get the following error:

```
The type argument for type parameter 'R' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
Type argument candidate 'string' is not a valid type argument because it is not a supertype of candidate 'string[]'.
```

Can you explain why this is? I don't understand the error.

**Comment by blakeembrey** [comment]
If you're using https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-promise/es6-promise.d.ts#L59, I found it's because those two items in the array resolve to different promise types. Try specifying it explicitly, usually works for me:

```
Promise.all<[string, string[]]>([
    Promise.resolve('foo'),
    Promise.resolve(['bar'])
])
```

**Comment by OliverJAsh** [comment]
Can you help me understand why this can't be inferred?

**Comment by blakeembrey** [comment]
> Can you help me understand why this can't be inferred?

I'm not the best person for that, I'll leave it for the TypeScript team to answer.

**Comment by OliverJAsh** [comment]
@blakeembrey I believe this is the correct syntax:

```
Promise.all<string | string[]>([
    Promise.resolve('foo'),
    Promise.resolve(['bar'])
])
```

If you try adding `.then((x) => x)` to the end of your assertion, you get errors.

**Comment by blakeembrey** [comment]
Not causing issues for me. What version are you using?

http://www.typescriptlang.org/Playground#src=Promise.all%3Cstring%20%7C%20string%5B%5D%3E(%5B%0A%20%20%20%20Promise.resolve('foo')%2C%0A%20%20%20%20Promise.resolve(%5B'bar'%5D)%0A%5D).then((x)%20%3D%3E%20x)%0A%0A%0A%2F%2F%2F%20FROM%20DEFINITELYTYPED%3A%0A%0A%2F%2F%20Type%20definitions%20for%20es6-promise%0A%2F%2F%20Project%3A%20https%3A%2F%2Fgithub.com%2Fjakearchibald%2FES6-Promise%0A%2F%2F%20Definitions%20by%3A%20Fran%C3%A7ois%20de%20Campredon%20%3Chttps%3A%2F%2Fgithub.com%2Ffdecampredon%2F%3E%2C%20vvakame%20%3Chttps%3A%2F%2Fgithub.com%2Fvvakame%3E%0A%2F%2F%20Definitions%3A%20https%3A%2F%2Fgithub.com%2Fborisyankov%2FDefinitelyTyped%0A%0Ainterface%20Thenable%3CR%3E%20%7B%0A%20%20%20%20then%3CU%3E(onFulfilled%3F%3A%20(value%3A%20R)%20%3D%3E%20U%20%7C%20Thenable%3CU%3E%2C%20onRejected%3F%3A%20(error%3A%20any)%20%3D%3E%20U%20%7C%20Thenable%3CU%3E)%3A%20Thenable%3CU%3E%3B%0A%20%20%20%20then%3CU%3E(onFulfilled%3F%3A%20(value%3A%20R)%20%3D%3E%20U%20%7C%20Thenable%3CU%3E%2C%20onRejected%3F%3A%20(error%3A%20any)%20%3D%3E%20void)%3A%20Thenable%3CU%3E%3B%0A%7D%0A%0Adeclare%20class%20Promise%3CR%3E%20implements%20Thenable%3CR%3E%20%7B%0A%09%2F**%0A%09%20*%20If%20you%20call%20resolve%20in%20the%20body%20of%20the%20callback%20passed%20to%20the%20constructor%2C%0A%09%20*%20your%20promise%20is%20fulfilled%20with%20result%20object%20passed%20to%20resolve.%0A%09%20*%20If%20you%20call%20reject%20your%20promise%20is%20rejected%20with%20the%20object%20passed%20to%20reject.%0A%09%20*%20For%20consistency%20and%20debugging%20(eg%20stack%20traces)%2C%20obj%20should%20be%20an%20instanceof%20Error.%0A%09%20*%20Any%20errors%20thrown%20in%20the%20constructor%20callback%20will%20be%20implicitly%20passed%20to%20reject().%0A%09%20*%2F%0A%09constructor(callback%3A%20(resolve%20%3A%20(value%3F%3A%20R%20%7C%20Thenable%3CR%3E)%20%3D%3E%20void%2C%20reject%3A%20(error%3F%3A%20any)%20%3D%3E%20void)%20%3D%3E%20void)%3B%0A%0A%09%2F**%0A%09%20*%20onFulfilled%20is%20called%20when%2Fif%20%22promise%22%20resolves.%20onRejected%20is%20called%20when%2Fif%20%22promise%22%20rejects.%0A%09%20*%20Both%20are%20optional%2C%20if%20either%2Fboth%20are%20omitted%20the%20next%20onFulfilled%2FonRejected%20in%20the%20chain%20is%20called.%0A%09%20*%20Both%20callbacks%20have%20a%20single%20parameter%20%2C%20the%20fulfillment%20value%20or%20rejection%20reason.%0A%09%20*%20%22then%22%20returns%20a%20new%20promise%20equivalent%20to%20the%20value%20you%20return%20from%20onFulfilled%2FonRejected%20after%20being%20passed%20through%20Promise.resolve.%0A%09%20*%20If%20an%20error%20is%20thrown%20in%20the%20callback%2C%20the%20returned%20promise%20rejects%20with%20that%20error.%0A%09%20*%0A%09%20*%20%40param%20onFulfilled%20called%20when%2Fif%20%22promise%22%20resolves%0A%09%20*%20%40param%20onRejected%20called%20when%2Fif%20%22promise%22%20rejects%0A%09%20*%2F%0A%20%20%20%20then%3CU%3E(onFulfilled%3F%3A%20(value%3A%20R)%20%3D%3E%20U%20%7C%20Thenable%3CU%3E%2C%20onRejected%3F%3A%20(error%3A%20any)%20%3D%3E%20U%20%7C%20Thenable%3CU%3E)%3A%20Promise%3CU%3E%3B%0A%20%20%20%20then%3CU%3E(onFulfilled%3F%3A%20(value%3A%20R)%20%3D%3E%20U%20%7C%20Thenable%3CU%3E%2C%20onRejected%3F%3A%20(error%3A%20any)%20%3D%3E%20void)%3A%20Promise%3CU%3E%3B%0A%0A%09%2F**%0A%09%20*%20Sugar%20for%20promise.then(undefined%2C%20onRejected)%0A%09%20*%0A%09%20*%20%40param%20onRejected%20called%20when%2Fif%20%22promise%22%20rejects%0A%09%20*%2F%0A%09catch%3CU%3E(onRejected%3F%3A%20(error%3A%20any)%20%3D%3E%20U%20%7C%20Thenable%3CU%3E)%3A%20Promise%3CU%3E%3B%0A%7D%0A%0Adeclare%20module%20Promise%20%7B%0A%09%2F**%0A%09%20*%20Make%20a%20new%20promise%20from%20the%20thenable.%0A%09%20*%20A%20thenable%20is%20promise-like%20in%20as%20far%20as%20it%20has%20a%20%22then%22%20method.%0A%09%20*%2F%0A%09function%20resolve%3CR%3E(value%3F%3A%20R%20%7C%20Thenable%3CR%3E)%3A%20Promise%3CR%3E%3B%0A%0A%09%2F**%0A%09%20*%20Make%20a%20promise%20that%20rejects%20to%20obj.%20For%20consistency%20and%20debugging%20(eg%20stack%20traces)%2C%20obj%20should%20be%20an%20instanceof%20Error%0A%09%20*%2F%0A%09function%20reject(error%3A%20any)%3A%20Promise%3Cany%3E%3B%0A%0A%09%2F**%0A%09%20*%20Make%20a%20promise%20that%20fulfills%20when%20every%20item%20in%20the%20array%20fulfills%2C%20and%20rejects%20if%20(and%20when)%20any%20item%20rejects.%0A%09%20*%20the%20array%20passed%20to%20all%20can%20be%20a%20mixture%20of%20promise-like%20objects%20and%20other%20objects.%0A%09%20*%20The%20fulfillment%20value%20is%20an%20array%20(in%20order)%20of%20fulfillment%20values.%20The%20rejection%20value%20is%20the%20first%20rejection%20value.%0A%09%20*%2F%0A%09function%20all%3CR%3E(promises%3A%20(R%20%7C%20Thenable%3CR%3E)%5B%5D)%3A%20Promise%3CR%5B%5D%3E%3B%0A%0A%09%2F**%0A%09%20*%20Make%20a%20Promise%20that%20fulfills%20when%20any%20item%20fulfills%2C%20and%20rejects%20if%20any%20item%20rejects.%0A%09%20*%2F%0A%09function%20race%3CR%3E(promises%3A%20(R%20%7C%20Thenable%3CR%3E)%5B%5D)%3A%20Promise%3CR%3E%3B%0A%7D%0A%0Adeclare%20module%20'es6-promise'%20%7B%0A%09var%20foo%3A%20typeof%20Promise%3B%20%2F%2F%20Temp%20variable%20to%20reference%20Promise%20in%20local%20context%0A%09module%20rsvp%20%7B%0A%09%09export%20var%20Promise%3A%20typeof%20foo%3B%0A%09%7D%0A%09export%20%3D%20rsvp%3B%0A%7D

**Comment by OliverJAsh** [comment]
Yes, that works. Sorry, I was trying to say the type assertion you provided didn't work (`Promise.all<Promise<string> | Promise<string[]>>`).

This is what I have ended up with:

``` js
Promise.all<any>([
    Promise.resolve('1'),
    Promise.resolve(1)
])
    .then(([x, y]: [string, number]) => {
        x
        y
    })
```

I provide the type of the tuple in the `then` callback function so I can continue to use the type checker. If I did the following:

``` js
Promise.all<string | number>([
    Promise.resolve('1'),
    Promise.resolve(1)
])
    .then(([x, y]) => {
        x
        y
    })
```

… then the compiler wouldn't know if `x` is a string or number.

This is a bit of a PITA. I'm trying to understand if it's possible to write a better type definition for `Promise.all` so assertions are not needed?

**Comment by blakeembrey** [comment]
Right, I understand. I don't think it's currently possible to do that since there's no way to express the generic variadically, but this discussion might relate to the proposal in https://github.com/Microsoft/TypeScript/issues/5453. The TypeScript team should chime in if there's a better approach at the moment, but I've done the same thing as you ended up with in the past.

**Comment by mhegazy** [comment]
untill #5453 is in, we can add a punch of overloads (say 2-10) to make `Promise.all` more user friendly. something like:

```ts
interface PromiseConstructor {
    all<T1, T2>(values: [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>]): Promise<[T1, T2]>;
    all<T1, T2, T3>(values: [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>, T3 | PromiseLike<T3>]): Promise<[T1, T2, T3]>;
    all<T1, T2, T3, T4>(values: [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>, T3 | PromiseLike<T3>, T4 | PromiseLike<T4>]): Promise<[T1, T2, T3, T4]>;
    ..............
}
```

@sandersn thoughts?

**Comment by sandersn** [comment]
Yes, multiple overloads is the accepted workaround until we have variadic generics from #5453.

I put variadic kinds behind this-types functions because this-types don't have a simple (albeit verbose) workaround. So I think it's worthwhile to add the overloads now until variadic kinds are in. I'll link the PR  when it's done.

**Comment by sandersn** [comment]
Here's the PR: #5973.
