### ISSUE TITLE
lib.es5.d.ts: Default ArrayConstructor generic parameter to `undefined`

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript#59379]
### ⚙ Compilation target

ES2015

### ⚙ Library

lib.es5.d.ts

### Missing / Incorrect Definition

The two constructor declaration lines without generics (`new (arrayLength?: number): any[];` and `(arrayLength?: number): any[];`)

https://github.com/microsoft/TypeScript/blob/903e82b368c8328dba95b70b21415e7a48339857/src/lib/es5.d.ts#L1488-L1497

Suggestion:

```diff
interface ArrayConstructor {
-   new (arrayLength?: number): any[];
-   new <T>(arrayLength: number): T[];
+   new <T = undefined>(arrayLength: number): T[];
    new <T>(...items: T[]): T[];
-   (arrayLength?: number): any[];
-   <T>(arrayLength: number): T[];
+   <T = undefined>(arrayLength: number): T[];
    <T>(...items: T[]): T[];
    isArray(arg: any): arg is any[];
    readonly prototype: any[];
}
```

### Sample Code

Using [the `@typescript-eslint/no-unsafe-assignment` ESLint rule](https://typescript-eslint.io/rules/no-unsafe-assignment) 

```TypeScript
const arr: undefined[] = Array(10); // 💥 Unsafe assignment of type `any[]` to a variable of type `undefined[]`. eslint (@typescript-eslint/no-unsafe-assignment)
```

### Documentation Link

> In some operations, empty slots behave as if they are filled with undefined.
>
> ```js
> const arr = [1, 2, , , 5]; // Create a sparse array
> 
> // Indexed access
> console.log(arr[2]); // undefined
> 
> // For...of
> for (const i of arr) {
>   console.log(i);
> }
> // Logs: 1 2 undefined undefined 5
> 
> // Spreading
> const another = [...arr]; // "another" is [ 1, 2, undefined, undefined, 5 ]
> ```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections#sparse_arrays:~:text=In%20some%20operations%2C%20empty%20slots%20behave%20as%20if%20they%20are%20filled%20with%20undefined.

Since TypeScript does not have a primitive for "empty slot", `undefined` seems like the closest default.

cc @JoshuaKGoldberg @bradzacher

**Comment by karlhorky** [comment]
## Workaround

To address the problem in [the `@typescript-eslint/no-unsafe-assignment` ESLint rule](https://typescript-eslint.io/rules/no-unsafe-assignment) without changing the `lib.es5.d.ts` declarations, pass in a generic type argument `undefined` to the `Array` constructor (which I'm arguing should be the default):

```ts
const arr: undefined[] = Array<undefined>(10);
```

**Comment by MartinJohns** [comment]
Somewhat related: #24834

---

Your suggestion would be quite a breaking change.

**Comment by RyanCavanaugh** [comment]
I don't see why someone would initialize an array with a length except in the rare case where they were about to fill it. This would break a number of cases, especially in JS where you can't easily specify type arguments.

**Comment by karlhorky** [comment]
My original motivation was actually that - spreading a newly-initialized array into a new array literal:

[`typescript-eslint` Playground](https://typescript-eslint.io/play/#ts=5.5.2&fileType=.ts&code=NoOjEECdIQwTwBQFYCUBdEBbGAHBCA3GAGwBoACASwDsATAUwA8VyBeAPirqZSA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0URNGgdokcGAC%2BITUA&tsconfig=&tokens=false)

```ts
[
  ...Array(5) // 💥 Unsafe spread of an `any` value in an array. ESLint @typescript-eslint/no-unsafe-assignment 
].map((val, index) => index)
```

![Screenshot 2024-07-29 at 22 07 46](https://github.com/user-attachments/assets/0e2504f4-3578-4f91-9173-098f710f31b2)

Providing the `undefined` type argument makes this problem disappear:

[`typescript-eslint` Playground](https://typescript-eslint.io/play/#ts=5.5.2&fileType=.ts&code=NoOjEECdIQwTwDwFcB2ATApgMwJYo2gHwAUArAJQC6IAtjAA7HEBuMANgDQAEemAHuS4BeQj3QYBQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0URNGgdokcGAC%2BITUA&tsconfig=&tokens=false)

```ts
[...Array<undefined>(5)].map((val, index) => index)
```

Upon first thinking about it, it seemed like a logical default to me.
