### ISSUE TITLE
Mixin types are intersections rather than proper subclasses

### ISSUE THREAD

**Issue by nex3** [microsoft/TypeScript#59394]
### 🔎 Search Terms

mixin override subtype subclass

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about mixins

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.3#code/C4TwDgpgBAwg9gOwM7AE4FcDGw6qgXigQgHcoAKAOmoENUBzJALihoRAG0BdASgID4oAbwC+AbgBQEzABsaSJFABicOMIlQoAM1XkAbjRnoILBOgC2AIwioAPilQBLBPR4tLqmRDbDUEYOioCFBoxiIS4dJyClAAIo5+2ADK6Jay8ooQAB7AEAgAJooqakIa2roGRiZEFtaoblAecF4+Qn4BQSEYEOGRWugI2I6IUACyjlnOADwAKgBC8tDZuQWK8Mih2Lj85AtI1fOLfKWa7YHB6THLeYVQe9AnmuVw+obGprU2DU0twW3+5y6YTK4giUkuinGkwQKTS0UyORukImznIxWOkWIZHiiWAsIh5B4lB0LwARJY6KS+AB6alQACiqFQuFYCMg2Ag+QkWLGKJhqQJRJJ5HJlJpdIAcmobMzUEA

### 💻 Code

```ts
type Constructor = new (...args: any[]) => {};

class Foo {
  foo(value: number|string): boolean {return true}
}

class DirectSubclass extends Foo {
  foo(value: number): boolean {return true}
}

function Mixin<TBase extends Constructor>(Base: TBase) {
  return class extends Base {
    foo(value: number): boolean {return true}
  };
}

class MixinSubclass extends Mixin(Foo) {}

new DirectSubclass().foo("bar") // Error as expected
new MixinSubclass().foo("bar") // No error
```

### 🙁 Actual behavior

The subclass through a mixin doesn't have the same semantics as the direct subclass. The narrower method becomes a new overload, and the broader one is still available as far as the type system is concerned.

### 🙂 Expected behavior

The narrower method type should override the broader one, the same way it works for a direct subclass.

### Additional information about the issue

I tried to work around this by manually creating a constructor interface with an overridden method, but https://github.com/microsoft/TypeScript/issues/2225 makes it impossible to do so in a generic way without running into the same issue with intersection types working differently than subclasses.

**Comment by RyanCavanaugh** [comment]
We don't have a type system primitive to represent "subclass", so intersection is the best available approximation. This approximation is correct as long as the subclass is a proper subtype of the base type, which is almost always true for valid mixins.
