### ISSUE TITLE
Nonsensical error when creating a mixin with a type parameter

### ISSUE THREAD

**Issue by STRd6** [microsoft/TypeScript#59411]
### 🔎 Search Terms

"mixin type parameter"

### 🕗 Version & Regression Information

At least since v3.3.3

### 💻 Code

```ts
type Constructor<T = {}> = new (
  ...args: any[]
) => T;

export const Undo = <Base extends Constructor>(
  S: Base,
) => {
  abstract class C<T> extends S {
    constructor(...args: any[]) {
      super(...args)
    }
    abstract f(x: T): T
  }

  return C;
};
```

### 🙁 Actual behavior

```
A mixin class must have a constructor with a single rest parameter of type 'any[]'.(2545)
class C<T>
```

### 🙂 Expected behavior

An error message explaining that mixins can't have type parameters since it already has a constructor function with a rest parameter of type `any[]`.

**Comment by jcalz** [comment]
duplicate #37142
