### ISSUE TITLE
Detect the use of objects when constructed class is need for getters/setters and functions

### ISSUE THREAD

**Issue by BobFrankston** [microsoft/TypeScript#59445]
### 🔍 Search Terms

class instance object

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The commonality of objects and classes in TypeScript is very useful but this makes to it too easy to forget that the object instance doesn't have the class prototypes.

### 📃 Motivating Example

I had a 

```
class foo {
    element: HTMLElement;
    get input() {return element as HTMLInputElement;
}. 

const fx: foo = {element: bar}
```

but, of course, fx.input failed. Since it was in the browser the fail was silent.

It would be nice to detect that I am using an object rather than a class instance by tracking the fact that fx was created without using a constructor.

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

Class instances and objects are very similar which makes such errors too easy and nonobvious. The work-around is DDT (Don't Do That) but the point of TypeScript is to assist in my avoiding such pitfalls.

**Comment by MartinJohns** [comment]
I'm not sure what you're suggesting? The code you showed does produce errors, the object literal is required to have `input`.

**Comment by BobFrankston** [comment]
You're right. I had forgotten that I (foolishly) put in as "as any" to work around the message.
