### ISSUE TITLE
Extending the Function interface in the presence of an import statement

### ISSUE THREAD

**Issue by bgrieder** [Microsoft/TypeScript#5944]
I would like to extend `Function` and this compiles fine

    interface Function {
    	hello(): any
    }
    Function.prototype.hello = function() {
    	console.log('hello world')
    }
	
	function noop() {}
	
	noop.hello() //==> 'hello world' in the console

However, as soon as I try to add an import statement, say

    import { sayHello } from './Anything'

where `Anything` only contains

    export function sayHello() { console.log('hello')}

The compilation fails on `Function.protoype.hello` with the message `error TS2339: Property 'hello' does not exist on type 'Function'`

Why ?

[View in Playground][1]

Note1: the compilation fails with tsc options set to either `--target es5 --module commonjs` or `--target es6`
Note2: my final goal is to export utilities in a library to be able to write code like `myfunc.liftM(myMonad1, MyMonad2)` or `myfunc1.compose(myfunc2)`, etc...

  [1]: http://www.typescriptlang.org/Playground#src=%0A%20%20%20%20interface%20Function%20%7B%0A%20%20%20%20%09hello()%3A%20any%0A%20%20%20%20%7D%0A%20%20%20%20Function.prototype.hello%20%3D%20function()%20%7B%0A%20%20%20%20%09console.log('hello%20world')%0A%20%20%20%20%7D%0A%09%0A%09function%20noop()%20%7B%7D%0A%09%0A%09noop.hello()%0A%09%0A%09%2F%2Fimport%20%7B%20hello%20%7D%20from%20'whatever'%20%20%0A%09%2F*%0A%09%20*%20Adding%20the%20import%20statement%20(also)%20triggers%20the%20Error%3A%20%0A%09%20*%20Property%20'hello'%20does%20not%20exists%20on%20type%20%60Function%60%0A%09%20*%20Why%20%3F%0A%09%20*%2F

**Comment by yortus** [comment]
In the TypeScript spec section 11.3 it states

> Source files that contain at least one module import or export declaration are considered separate modules.

In your original working version, there are no import or export declarations, so the things you've declared there are in the global namespace. So you've told `tsc` that the global `Function` type has a 'hello' member (your declaration of `Function` merges with the built-in declaration).

When you introduce the `export` line, the quote above kicks in and now the whole file is considered to be in its own separate namespace. So now you have a local type called `Function` that has a `hello` member, and this is completely distinct from the global `Function` type.

The final line `noop.hello()` should still work if you run the emitted code, but the compiler error is because the global `Function` type does not have a `hello` member.

**Comment by yortus** [comment]
As per your 'Note2' you want to monkey-patch built-in objects, which is frowned on if it can be avoided.

Having said that, TypeScript can model monkey-patching just fine if you must do it. Just declare the additions to the built-ins ambiently in a .d.ts file. Any TypeScript project using your library would need to include that .d.ts file in its own build to pick up the patched types. E.g.:

```typescript
// file: monkey.d.ts
interface Function {
    hello(): any
}

// file: monkey.ts
export function patch() {
    Function.prototype.hello = function() {
        console.log('hello world')
    }
}


// file: example.ts
///<reference path="monkey.d.ts" />
import monkey = require('./monkey');
monkey.patch();

function noop() {}

noop.hello() // OK: should pick up 'hello' member declared in monkey.d.ts
```

Hopefully you can see the pitfalls of doing this (eg what if you forget to call `monkey.patch()?`). But that's how you can do it.

**Comment by yortus** [comment]
See also #4166

**Comment by bgrieder** [comment]
@yortus Great answer. Thanks. 
https://github.com/Microsoft/TypeScript/issues/4166 is spot on (and this can be considered as a duplicate)

So, unfortunately there is no way to "export" augmentation to the existing interfaces from a library.

I understand the dangers of monkey patching but still see this as unfortunate: I come from the Scala world where there is a way to "pimp" existing types without having to resort to monkey patching.
Such a powerful mechanism is badly missed in the javascript/typescript world....

**Comment by yortus** [comment]
Agreed. It's trivial to do in JavaScript, so it would be good to be able to model it just as easily in TypeScript.
