### ISSUE TITLE
JSON.parse also works with null, not just a string

### ISSUE THREAD

**Issue by ic-768** [microsoft/TypeScript#59457]
### ⚙ Compilation target

esnext

### ⚙ Library

typescript

### Missing / Incorrect Definition

`JSON.parse` works if first argument is null. Current type definition doesn't allow null, only a string.

### Sample Code

```TypeScript
JSON.parse(null)
```

**Comment by nmain** [comment]
This has been rejected before.  See https://github.com/microsoft/TypeScript/pull/39266 and others linked from that.
