### ISSUE TITLE
String template literal CFA does not account for bound variables

### ISSUE THREAD

**Issue by xav-ie** [microsoft/TypeScript#59461]
### 🔎 Search Terms

"string template literal cfa"
"template literal type binding"
"string template narrowing"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried (4.5.5, 4.9.5, 5.6-beta, nightly), and I reviewed the FAQ for entries about Generics
- I was unable to test this on prior versions because I don't think using `every-ts` is necessary. I think this is just an unaddressed issue.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240729#code/C4TwDgpgBAggNnA9gdwgEwKJwgWwgO2AGcoBeKAcgAsBGCqAH0qoCZ6nqBmd5gFh+oBWAVQBsAsALgBLAQFc4FANwAoFQGNE+IsCgRseQmSgAKfQC5YCFOiy4CxADRQwAJ0Rgilna+n4A5gDaALrO6lTScGgAysCu3nF+-gCUZAB8UADeKlBQrhDAcq74UAAGADwAJJn6AL5Q1W4eRAB0AFaIfib0FMm1adXhkTFxteUA9NV1aaVQAIYkmtrAqrUq4+NQSzp6Bg6WZnCW8EiomHuERM5Nngm+ASFhEVGx8VA+SamkGeubFbQNTIfAL9arA-xjca0GaMMrlAFgxIggZApEQiasGFMX5whGo+4QlHgyFUThY3E0QHEolokm8ck4-6UxEE0H4pIkwTkplU2k01kY0QMjYU3ms-kciZgcktWVQADsnCgOEQ+SgspasIqCjFHIlIImChmahFpX0s2kJAARog5Pg0JroogoAAzIrAKgQVxQORECAkRAuqDSXREKi2qJQK3QJDqADW6E1AElQxBcCQZAmoAAVcAQaLqXxgXSWqBoToBH34fAQdT+ohzVwgKDIVVxqCe-ItNTbXT6eyEADiBC90nUxnK2b0AA9gAQ0CQTjZzgPiGlDpZs9d3Ld3mjHltniM3uCvhlsrl8oVinCpnB6o0d60Ol0en0UUMXqMJnf+rMFlsWg6KsOK9rsq7DjWvjqJYk4znO9qLtYZx2IYa4bjm27NHcSQHp+x44QEZ6MlUmTZg+7LIiykqTGRf44tmEQkKW0bAHO3pWnIuj4IgujIFQcy6EmLZzIQKhAA

### 💻 Code

```ts
type AllowedElements = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'li' | 'ul';

const element = (el: AllowedElements, props: string[], childStr: string) => {
  return `<${el} ${props.join(' ')}>${childStr}</${el}>` as const;
}
// const element: (el: AllowedElements, props: string[], childStr: string) => 
// `<h1 ${string}>${string}</h1>` | `<h1 ${string}>${string}</h2>` | 
// `<h1 ${string}>${string}</h3>` | `<h1 ${string}>${string}</h4>` | 
// `<h1 ${string}>${string}</h5>` | `<h1 ${string}>${string}</h6>` | 
// `<h1 ${string}>${string}</p>` | ... 73 more ... | `<ul ${string}>${string}</ul>`

// `el` is bound. So further uses of it should be locked. It seems like TypeScript is doing unnecessary work here.

const elementGeneric = <T extends AllowedElements>(el: T, props: string[], childStr: string) => {
  return `<${el} ${props.join(' ')}>${childStr}</${el}>` as const;
}
// const elementGeneric: <T extends AllowedElements>(el: T, props: string[], childStr: string) =>
// `<${T} ${string}>${string}</${T}>`
// This is better but not what I want
```

### 🙁 Actual behavior

```ts
type AllowedElements = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'li' | 'ul';

const element = (el: AllowedElements, props: string[], childStr: string) => {
  return `<${el} ${props.join(' ')}>${childStr}</${el}>` as const;
}
// const element: (el: AllowedElements, props: string[], childStr: string) =>
// `<h1 ${string}>${string}</h1>` | `<h1 ${string}>${string}</h2>` | 
// `<h1 ${string}>${string}</h3>` | `<h1 ${string}>${string}</h4>` |
// `<h1 ${string}>${string}</h5>` | `<h1 ${string}>${string}</h6>` | 
// `<h1 ${string}>${string}</p>` | ... 73 more ... | `<ul ${string}>${string}</ul>`
```

The actual behavior shows that the argument `el` is not bound by TypeScript. It is wrong because it is producing lots of extra types that are not accurate nor wanted. I can't think of a case where `el` would change mid-template literal, either.

### 🙂 Expected behavior

```ts
type AllowedElements = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'li' | 'ul';

const element = (el: AllowedElements, props: string[], childStr: string) => {
  return `<${el} ${props.join(' ')}>${childStr}</${el}>` as const;
}
// const element: (el: AllowedElements, props: string[], childStr: string) =>
// `<h1 ${string}>${string}</h1>` | `<h2 ${string}>${string}</h2>` | 
// `<h3 ${string}>${string}</h3>` | `<h4 ${string}>${string}</h4>` |
// `<h5 ${string}>${string}</h5>` | `<h6 ${string}>${string}</h6>` | 
// `<p ${string}>${string}</p>` | `<li ${string}>${string}</li>` | 
// `<ul ${string}>${string}</ul>`
```

I would like for the variable to be bound from the union type when making a string literal. 

A workaround could include adding a generic, but I just don't think that is the right answer. It should be able to infer that it is a template literal with the same bound variable used twice. It does not change like the type suggests.

**Comment by RyanCavanaugh** [comment]
Simpler repro
```ts
type ABC = 'a' | 'b' | 'c';

// Expected 'aa' | 'bb' | 'cc', not 'aa' | 'ab' | 'ac' ...
const element = (el: ABC) => {
  const e = el;
  return `${e}${e}` as const;
}
```

**Comment by RyanCavanaugh** [comment]
Duplicate #49132
