### ISSUE TITLE
Typescript 5.5 does not infer event handler types in MUI

### ISSUE THREAD

**Issue by marc-at-brightnight** [microsoft/TypeScript#59472]
I'm wondering what the recent changes were in Typescript 5.5 for it suddenly not to infer types from Material UI's standard `onClick` and `onChange` event handlers. Example below.

```
<IconButton onClick={(event) => handleCopyScenarioClick(event, i)}>
  <ContentCopyIcon />
</IconButton>

// TS error:
src/MyComponent.tsx:184:27 - error TS7006: Parameter 'event' implicitly has an 'any' type.
184                 onClick={(event) => handleCopyScenarioClick(event, i)}
```

Changing to an explicit type, as below, fixes the error:
```
  onClick={(event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => handleCopyScenarioClick(event, i)}
```

To me, this seems like a step in the wrong direction, since Typescript has and should correctly infer the type from the underlying prop. I'm sure there's a good reason for this but haven't found it in the release notes.

Thanks in advance for your help.

**Comment by jakebailey** [comment]
You must have used the wrong template; you'd want to be using the bug template on https://github.com/microsoft/TypeScript/issues/new/choose
