### ISSUE TITLE
string not assignable to Record with specific number key

### ISSUE THREAD

**Issue by camsteffen** [microsoft/TypeScript#59489]
### 🔎 Search Terms

string not assignable record key number object

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "Here are some behaviors that may look like bugs, but aren't."

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.4#code/FAUwHgDg9gTgLgAgGYFcB2BjOBLKaEDmIcA0iAJ4A8Z5C4cIaAJgM4IDWFUSCAhmuQA0CAGq8ANihAA+ABTAAkADcJUgFwIASiAywm1CsLGSZgxZ3IaaZgJQbjUhAG9FMYihj4VJgNoWAugDcwAC+wAD04XQwMLDARKQUsgBEAIwATADMycIADDbBEVFQ7PHENCkZ2Xl8bGgoALYARiAwBWWJ5LI+qcLpwpn+ee1AA

### 💻 Code

```ts

export function getKey<Key extends keyof any, Value>(
	value: Record<Key, Value>,
	key: Key,
): Value {
	return value[key];
}
// error
getKey("123", 0);

// ok
getKey("123", 0 as number);
getKey([1, 2, 3], 0);
```

### 🙁 Actual behavior

An error occurs because a string is not assignable to a record type with an index type that is a specific number. This seems wrong because string are generally indexable by numbers. And array types are indexable by specific number types.

### 🙂 Expected behavior

No error when trying to assign a string to a record type where the index is a specific number.

### Additional information about the issue

I bumped into this when trying to implement a generic comparator function like `compareBy(0)('abc', '123') === 1`.

**Comment by camsteffen** [comment]
Here's another example, closer to what I was trying to do:

```typescript
type Comparator<T> = (a: T, b: T) => number;

function compareBy<K extends keyof any>(
	key: K,
): Comparator<Record<K, unknown>> {
	return (a, b) => {
		// TODO
	};
}

function test(list: string[]) {
	// error
	list.sort(compareBy(0));
	// ok
	list.sort(compareBy(0 as number));
}
```

**Comment by RyanCavanaugh** [comment]
It's a little awkward to try to figure out the intended semantics here. It seems like you'd want `compareBy("x")` to only accept things with a declared `{ x: something }`, but then for `0`, strings don't have a declared `0` property (and indeed might be zero-length), so rejecting `""` because it doesn't have `{ 0: something }` is just as correct as the rejection of `"x"`.

**Comment by camsteffen** [comment]
> It seems like you'd want `compareBy("x")` to only accept things with a declared `{ x: something }`,

`compareBy(0)` could also be used for comparing lists by the first element. I admit indexing strings is a little edgy, but I think there is value in having this work generically.

> so rejecting "" because it doesn't have { 0: something } is just as correct as the rejection of "x"

I don't think that holds up because the error occurs even if you change the string type to a specific non-zero-length string.

Also I think we should expect strings and arrays to be consistent in this regard.

```typescript
function hasZeroKey(x: Record<0, any>) {}
function hasNumberKey(x: Record<number, any>) {}
hasZeroKey("abc"); // error
hasNumberKey("abc"); // ok
hasZeroKey([1, 2, 3]); // ok
hasNumberKey([1, 2, 3]); // ok
```

**Comment by RyanCavanaugh** [comment]
It is consistent, it's just that strings don't get any contextual tuple-like inference the way arrays do (it's unclear where that would ever be useful):
```ts
const arr = [1, 2, 3];
hasZeroKey(arr); // Error
```

**Comment by camsteffen** [comment]
There doesn't need to be tuple-like inference. Typescript optimistically assumes that indexing an unknown-length array will yield an element. It should also assume that indexing a string yields a string. In fact `string[number]` or `string[0]` does equal `string`, but it just doesn't allow you to express that rule in terms of a record type. But you can with arrays. So that seems definitely inconsistent to me.

**Comment by camsteffen** [comment]
I found a workaround for my `compareBy` use case.

```ts
type Comparator<T> = (a: T, b: T) => number;

type CompareBy<K extends keyof any> = Comparator<
	| Record<K, unknown>
        // explicitly allow string here
	| (K extends number ? string : never)
>

function compareBy<K extends keyof any>(key: K): CompareBy<K> {
	return (a, b) => {
		if (a[k] < b[k]) return -1;
		if (a[k] < b[k]) return 1;
		return 0;
	};
}

function test(list: string[]) {
	// ok - fixed
	list.sort(compareBy(0));
}
```

**Comment by RyanCavanaugh** [comment]
The thing that allows this
```ts
function hasZeroKey(x: Record<0, any>) {}
hasZeroKey([1, 2, 3]); // ok
```
is that the `[1, 2, 3]` literal gets inferred to be a tuple (which has declared `0`, `1`, `2` properties). Without that tuple inference, it's just an object with a numeric index signature, and it's intentional that an index signature isn't allowed to satisfy a declared property.

**Comment by camsteffen** [comment]
That's not true. It also works with `number[]`. [playground](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABACwIYGcBaBTATnAaWwE8AKADwC5EAlbCOXAEwB4AGAGkVTGID4AlIgDeAXwBQoSLAQoMAORABbAEZ4iZKrXqNWYZWtxce-IWPFoseQiVIAiVCoh2BAbkQB6D4jz5cFhQN1WwcnF3cvRDgAawCrfA1SAG0ARi4AJi4AZgBdN09vGLjFVWCyVIzsvIjC2KloeCQobHQoUgAbGFbqfVLcJLyRcQBISxwE2wrETMRc-Mii0SA)

**Comment by camsteffen** [comment]
Hmm I see. I thought I saw it working with `number[]` but it doesn't.
