### ISSUE TITLE
Polymorphic `this` breaks valid TS 1.6 code:

### ISSUE THREAD

**Issue by sccolbert** [Microsoft/TypeScript#5948]
This code compiles fine in 1.6 but fails in 1.7. I assume this is related to polymorphic `this`:
```typescript
class Foo {
	
	root(): Foo {
		let foo = this;
		while (foo._parent) {
			foo = foo._parent;  // type 'Foo' is not assignable to type 'this'
		}
		return foo;
	}
	private _parent: Foo;
}
```

http://www.typescriptlang.org/Playground#src=%0A%0Aclass%20Foo%20%7B%0A%09%0A%09root()%3A%20Foo%20%7B%0A%09%09let%20foo%20%3D%20this%3B%0A%09%09while%20(foo._parent)%20%7B%0A%09%09%09foo%20%3D%20foo._parent%3B%0A%09%09%7D%0A%09%09return%20foo%3B%0A%09%7D%0A%09private%20_parent%3A%20Foo%3B%0A%7D

**Comment by sccolbert** [comment]
Since this is a backwards incompatibility, the current `1.7` release violates semver.

**Comment by DanielRosenwasser** [comment]
@sccolbert you're right that this is a breaking change, and [we've documented it on the breaking changes list](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#changes-in-inferring-the-type-from-this) for future reference. I'm sorry about the inconvenience that this caused, but the workaround here is small enough that it shouldn't be anything more than adding a type annotation to `foo` in your example.

Regarding semver, you're also right in that respect, but in general we don't really follow semver. It's not something we're unaware of, but I'm probably not the right person to answer why TypeScript 1.7 isn't called TypeScript 7.

**Comment by sccolbert** [comment]
@DanielRosenwasser Thanks for the quick response.

Is following semver something that the TS team would consider, given how vital it is to the way `npm` and other package managers do things?
