### ISSUE TITLE
Version 5.5.4 tsc cannot find package.json in VS Code terminal

### ISSUE THREAD

**Issue by Eidar** [microsoft/TypeScript#59480]
### 🔎 Search Terms

npx tsc, default, error, package.json, not, found, wsl, windows 10

### 🕗 Version & Regression Information

- This changed between versions 5.5.4 and 5.5.3

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

Running `tsc` command works perfectly fine but using `npx tsc` throws an error:

![image](https://github.com/user-attachments/assets/576bf9c8-be71-4ab2-90e5-557ba08d7afb)

Note that this error occurs only in VS Code terminal.

### 🙂 Expected behavior

`npx tsc` should be able to find it's way from to root folder to the package.json file

### Additional information about the issue

- Node 22.5.1
- npm 10.8.2
- tsc - 5.5.4
- nvm - 0.35.3
- WSL Ubuntu 20.04.6 LTS

**Comment by MartinJohns** [comment]
This doesn't seem to be TypeScript related.

**Comment by MartinJohns** [comment]
What's the working directory of the command prompt you're running? It looks like it's `$`, which doesn't seem like your project directory.

**Comment by RyanCavanaugh** [comment]
I don't think there's a plausible change [between 5.5.3 and 5.5.4](https://github.com/microsoft/TypeScript/compare/v5.5.3...v5.5.4) that could have caused this. We don't control `npx` or VS Code's terminal window -- without a proposed root cause, this seems likely to be a local misconfiguration.

**Comment by Eidar** [comment]
Absolutely. After some days of rummaging through everything, seems like I hade some typescript misconfigurations like multiple tsc binaries and similar. I did set up a cwd on a task, and that could have been the actual problem as it had searched for package.json in /home/user/project/node_modules/bin.

Basically it was set up like this:

`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Fastify with tsx",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "tsx",
      "program": "${workspaceFolder}/src/index.ts",
      "cwd": "${workspaceFolder}",
      "preLaunchTask": "tsc: build - tsconfig.json",
      "skipFiles": ["<node_internals>/**"],
      "trace": true
    }
  ]
}`

Maybe that cwd option made a mess?
