### ISSUE TITLE
I have a small error and I think it is related to ts since all the data is correct.

### ISSUE THREAD

**Issue by anzor1qqqqq** [microsoft/TypeScript#59498]
### 🔎 Search Terms

Type '"packTypes"' cannot be used to index type 'IProdSchemas[T]["unitTypes"][Y]'

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgJIAUoHsAmBlBACwgFs4BnZAbwChl7kA5AVzCmDgBtOAuauhoOYhgYACoBPAA4RyfWoMUMWbDtwD6AIywAPeQKWHkOTQGE4kAOZYoEvuVUhLBo4qmIA1pJlz+r-8ggrOxcnFq66uQQYHxi6J7esqiQJHjRANoAui4BikGqoeE66gCMABx8GAnSSSlZObkM+SEa2sUlACyV8QheNeTJpPWNhs1qYW3qAExT3dU+gyTDI3nB40WlAAxzvYkDddkrqwWtEQCcO30LBw3+AL63ig9Gzwyv9ADScFAkEgAitn0RmEoj2QICXx+-zw6Eini2Hks4JG7l2-WRR2QHm+vxw5Ck6hAEAA7nDeuocFhLOQEUi0D0rrUhodMfRsVC8QTyPCSptEepOMASB4bCRLntFstWezcfiyR5aeopNgAG5C4Di-qSlmswXC0VK1VCiCa67Mx4vC1vK2fHHQ2GTEgQTgK+C+BQrVGM9021wAIkdztdFHUmwAdABmUNhjqIv2mplLHWYgMRJ0u9Ru6NRkphgCs-KmYb5lnj9PmialKcDGaz4ajUTAZbiFf2pDSYCruXerh7Rkhvz+MPlpQLdI9KNbGKOMoknJHJTHAqFIp+CbbSd9Rln8+55MX-OVWDVJA15bRZs3rPoetXJENx+N6+1W+t3d9A-tC9j49f9C9YJ+NeO5ynuCqdPyt6is+NzXsgUE-A+J4mue3ovkcfaGJhSifkOsJgaUZSItOAQAeiQHSnau48kRlgUhA8DMJwMSoRKsErNhTyPD2DwPDQoCQLAiAoFUF6JhRyDEhAwCWIQLEOOwTguMwURQAyiR-LICBQPYjjOEIIjiDUaTfEQABCdjIApoD6QwZEyCZUDmZZE6KCQuAodZSmCD2MhQAAqoZfBBCQmjQC4CBYCQTrgLpim2fQKnQOpNRxTZNB8WANTIC2Ykbh2yAALzIAA8qeYAADyiWhKQADTIAA5H5gWiA1AB8yAAGQSc1QXIAAglAUBwBIVXoNALWdpkbUuN8YDAAgnCyGlTj1HxAnQPASD0hNhkSVJMlycFzCheFghzQtS0rQlyC9aIx2nVAGU0DQWUyDlLWJBVYjIBAOiQCAeJYhAEhYDA9LYPgRCkBQHXFR4INgxDuAEMQZDkOkYiZOkDUgkZPgNZkADcL1vSguWMt9v3-RAgOUAjoPgxgkOozD5D1QAmtTANA2In01N9bVw8gLgM0jzMo9D6OY9juOGXshPpBzsv2bIhMvRtQnbagADi0STQA6tJsmVeYVhYBI3O00DYtM5gktoxQ9WTYkVt0x9IhfWbEDWBIbX1Sl71-TzlAU17Fg+xbzvyzUQsSQgEfWICyDe77JMGaCqXIC7NTp3ZFZ8IHEAk3cQA

### 💻 Code

I'm applying a link to the playground above

### 🙁 Actual behavior

In our TPackType type, we cannot access the packTypes field

### 🙂 Expected behavior

In the TPackType type, we need to access this field as it is in each of our nested objects

### Additional information about the issue

My team and I have tried many options and have not found an actual error.

**Comment by RyanCavanaugh** [comment]
Simpler repro to demonstrate what's happening
```ts
type Sample = {
    top: {
        fixed: {
            middle: {
                bottom: {
                    foo: string;
                }
            }
        }
    }
}
type MiddleKey<K extends keyof Sample> = keyof Sample[K]['fixed'];
type Deferred<K1 extends keyof Sample, K2 extends MiddleKey<K1>> = keyof Sample[K1]["fixed"][K2]["bottom"];
```
Deferred indexed access types don't enumerate all their possible inhabitants, so can't be indexed that way. You'd need to use someting like this:
```ts
type Sample = {
    top: {
        fixed: {
            middle: {
                bottom: {
                    foo: string;
                }
            }
        }
    }
}
type MiddleKey<K extends keyof Sample> = keyof Sample[K]['fixed'];
type ReadProp<T, K extends keyof any> = T extends Record<K, infer U> ? U : never;
type Deferred<K1 extends keyof Sample, K2 extends MiddleKey<K1>> = keyof ReadProp<Sample[K1]["fixed"][K2], "bottom">;
type S = Deferred<"top", "middle">;
```

**Comment by RyanCavanaugh** [comment]
> Search Terms: Type '"packTypes"' cannot be used to index type 'IProdSchemas[T]["unitTypes"][Y]'

Aside: Why are you searching for code that would only ever appear in your codebase?

**Comment by nmain** [comment]
This can be reworked slightly to be more friendly to the compiler: [Playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAEghgZwKoDsCWwAq4IIIIoAmACnAMYDW2kCUAvFAEoRkD2AToQDwLDtooA5gBooAbygBXdFhwIAXExYduvfkNESw5KnMXM2nHnwEioASVKVquc8AgBbAEKIIAbQC6APigBfH-4A3ABQwQL27ABm5NCW7KyEAMpkABaOiFAQAB72RLTwyDI2+ERWujTiwVDVUABykiZwADZNimJVNZ3SGMVtHZ0DdQ38zU0A+gBGrFl9g3M1hBMAwnD2ghwgimqm-fMD2tZ6lXsnUCjDaKOT02MIEMCKmGXFdo6J9567pwPnjS3XWTGAEYAByKSw6F72Byfb7zX4jf5TQFAgAs4OecleMI8Xzh1QRlyRNwATCSMZCsdDYfifhcrsjgQAGCmHGjYmm0mqEhk3ACcrPKtmpuK5vjxg3F8ylNRl1QA0nB2A4QAARdibY5zbqyGizU6K5VqxLEW46ZkUQT6-EHIUKLVc6oUJUqwgIMBjFAQADuZsoY0IrEECAtVosmPZIolcOdRrdHoQ5qBTMtYyaaAcFA4DkFUMcnMdsdd7r9FFDYzA8QAbhm0LmqfnRY7qunM9mK9WMxB65HG9Hpf3ZYOFS7jabGQ4IE0y9F7e0ubbeg7HQAiCdTmeIMZMgB0AGZtzvUZaVz3hX3m9U1zdJ9OxrPDwegTuAKypkk7lOCU-hym9nHDns16Arem4hruB53MAP5PH+54OO8wAFt8cp7Kh8yGiqqomqWwJvmG860ouRyEc2RYgPGuFAvhaYZlmypnggHJNmRo6UYm-rUamlasDWDh1r+bLwchtKtvRDgdrxXaMcxgGdOhcwKYMmFjlRx4EXJNTEXqy5cuR7FJuptFtgxgl2rJl5QGJ7Y8Xx3ZmXmAFioBSkDCp2GmhxZagpa1pwtpuB+XpbEll5wIgqmhAQNEkhNA8DkNk5tKufJ0aoeK4phCgETRGQsQRvBLh3Mu3oQGgggpPF2xCLskh3OwBWqrgZDsFsJg1V0RQ4O8SqpE4mrVYIuwBT17B9ZqpEDA4CT2YNuyoWwDiTtlbXqENXT1QVq2mJ0wSZeEEBRDECX-pkOQQHkJ2Fa4y6QOwqAYIo5wOBMh17aEB1HXlUCwUJTHQohZ25G6V3-Y4RXQJNd0PfFeDsOwcAgFwliHTDnheLsSrAGgZBNIFUCDZ8+3ZYduX5ajMglWVFXxc9r3sJj7DY7js3tetWkU49ZySC9b2ZaAkA-Q9NhcJgQMXSDFAQCArCROG8RJKk6QID4DBSzLctxAkyRpA4iBuJgHhuAA5DqxTGx4ITBAL0C-UKovi5d6uy-L2tK3rCCiAAmo7IOYMLOCi14qtQLszua8QCs68rBtG6bXU0Bbbhe3HAUIBbH0k19sQAOL3DDADq1OVVwKxrKwIC+7Q4eu4ruuIKIMM2FXQvoCLZcQOsIBeKIBUt3b7erJ3FeNwnEDB8uZBD+sGqKB3XchJ1PQ4IoTc4IvWlwYoBUhL4QA)

**Comment by anzor1qqqqq** [comment]
> > Условия поиска: тип «packTypes» нельзя использовать для индексации типа «IProdSchemas[T]["unitTypes"][Y]»
> 
> Замечание: почему вы ищете код, который может появиться только в вашей кодовой базе?

I did not understand the essence of the question

**Comment by anzor1qqqqq** [comment]
I need this type to narrow down the IGetUnitWeight type
