### ISSUE TITLE
Cannot assign after merging generic parameters.

### ISSUE THREAD

**Issue by LiST-GIT** [microsoft/TypeScript#59496]
### 🔎 Search Terms

generic

### 🕗 Version & Regression Information

5.6.0

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-beta#code/C4TwDgpgBAogbhAdsAIhAxgGwIYCdvACWA9ogM5QC8UAShsbgCYA8ZwuhiA5gDRQCuiANaJiAd0QBtALoA+ANwAoRZ2ARcAM2zpoASQDCpNQA9gUAN6Ko1qBATIAEtkSNM6sgC5Y91Bhz4iUjIeRQBfZVBIKAAjfkJMYF1EeCRfLDwCEnIqCysbSSEIEC8AAwAVXQBZGBoPABJzRH4AW2j1UJLpL0km1vVpENClRQB6EahI6BTHZ1d3ZkNkCFNbUyRGCgMjZeA+NHSArIod9YpptP9MoJzY+MTkn33LwOyAMihFk2BJAHI7VKcLjcuDIPzkOTGUGahDY2EKikm3gBs2BZAW2xWJxcm0+Oz2fgyL2Oa2xSOQT0JRxucQSSXOFMOQVkEPGxCEeWs5igkkRnCghRAxA0UAZV3I0gA-F4ABToDHALy40x8AB0arwXE83LVKtFRJ54AgAygOsEInEUmk0gAlFRmXBiIRGFAhsoNIJ0C8oABBdFLTEkjZQLb+4CyaW2yw2KBy8hmbBec6AuYgv1fZnUKPRmw-CrVWoARgADCWfjLY18+Ng+NE+OhbZRmVns9nsByWzZIQA9CXtjsxPsd7u9-vR9CDlvDicukLR13hIA

### 💻 Code

```ts
type EventDeclarations = Record<string, unknown[]>;

interface IContext {
    eventHandlers: EventDeclarations,
}

type builtInEventDeclarations = {
    [key: `TIMER:${number}`]: [number],
};

type EventHandlers<Context extends IContext, Declarations extends EventDeclarations = builtInEventDeclarations & Context['eventHandlers']> = // mistake
// type EventHandlers<Context extends IContext, Declarations extends EventDeclarations = builtInEventDeclarations> = // ok
    { [type in keyof Declarations]?: (context: Context, ...args: [...Declarations[type], ...unknown[]]) => void };

function A<Context extends IContext>() {
    const a: EventHandlers<Context> = {
         // ERROR: Type '{ 'TIMER:1000': (context: Context, a: [...(builtInEventDeclarations & Context["eventHandlers"])["TIMER:1000"], ...unknown[]][0], b: [...(builtInEventDeclarations & Context["eventHandlers"])["TIMER:1000"], ...unknown[]][1], c: [......][2]) => void; }' is not assignable to type 'EventHandlers<Context, builtInEventDeclarations & Context["eventHandlers"]>'.(2322)
        'TIMER:1000': (context, a, b, c) => {
            a
            // ^?
            b
            // ^?
            c
            // ^?
        },
    };
}

```

### 🙁 Actual behavior

I want to generate event handling through like `{event:[arg1:number,arg2:string]}`, with built-in events and custom events, but when I merge two objects, an error occurs.

### 🙂 Expected behavior

My expectation is that `builtInEventDeclarations & Context['eventHandlers']` equals `builtInEventDeclarations & {}`.

**Comment by RyanCavanaugh** [comment]
This is a correct error; if you returned `a` then you could manifest an unsoundness:
```ts
function A<Context extends IContext>() {
    const a: EventHandlers<Context> = {
        'TIMER:1000': (context, a, b, c) => {
            a
            // ^?
            b
            // ^?
            c
            // ^?
        },
    };
    return a;
}

const p = A<IContext & { eventHandlers: { x : string } }>();
let r = p.x; // <- there's no x on p
```

**Comment by LiST-GIT** [comment]
```ts

function A<Context extends IContext>(context:Context) {
    const a: EventHandlers<Context> = { // There is still an error
        'TIMER:1000': (context, a, b, c) => {
            a
            // ^?
            b
            // ^?
            c
            // ^?
        },
    };
    for (const name in context.eventHandlers) {
        a[name] = function() {};
    }
    return a;
}

const p = A<IContext & { eventHandlers: {x:[string]} }>({ eventHandlers: { x: ['asd'] } });
let x = p.x; // x on p
```
https://www.typescriptlang.org/play/?ts=5.6.0-beta&ssl=34&ssc=1&pln=14&pc=1#code/C4TwDgpgBAogbhAdsAIhAxgGwIYCdvACWA9ogM5QC8UAShsbgCYA8ZwuhiA5gDRQCuiANaJiAd0QBtALoA+ANwAoRZ2ARcAM2zpoASQDCpNQA9gUAN6Ko1qBATIAEtkSNM6sgC5Y91Bhz4iUjIeRQBfZVBIKAAjfkJMYF1EeCRfLDwCEnIqCysbSSEIEC8AAwAVXQBZGBoPABJzRH4AW2j1UJLpL0km1vVpENClRUjoFMdnV3dmQ2QIU1tTJEYKAyN54D40dICsig3linG0-0ygnNj4xOSfbdPA7IAyKFmTYEkAcjtUpxc3XDIHzkOQA9CCoM1CGxsIVFGCoKNvD9Jv8yDN1gsDi5Vq8Nls-BkHvsltikcg7oS9hc4gkkscKbsgrJQeDiEI8tZzFBJIjOFBCiBiBooAyzuRpAB+LwACnQGOAXlxpj4ADo1XguJ5uWqVaKiTzwBABlAdYIROIpNJpABKKjMuDEQiMKBDZQaQToB5QACC6LmmJJKyga39wFksvlHiVwFtlhsUDl5DM2C8x1+UwBfrezOocfjNg+FWqtQAjAAGCsfGWJt58bB8aJ8dC2yjMvP5-PYDkdmzwgB6Eu7PZiQ57-cHw-j6FHHfHM5dIXjrvjGgYUAjSagiGwzWgfJrGxV3wmf3csfn2B6O6NOXdiE9WWlseXNnC8dwEGA-FwiCg2CU4SKImbBQGAOS+iGbxQM8XLHsA6aol45jGB4khsBw3DSKELrhrBPgIe4SFQCh3IfNgZCMECLoutaShuGYxg5GAKrGEoQA

**Comment by jcalz** [comment]
The initializing value is still not of the correct type. It doesn't matter if you fix it afterwards. See #35086. 

Even with #35086 I doubt you could do this with a loop. You need a type assertion if you want to say this.

**Comment by LiST-GIT** [comment]
The point is the error in `const a: EventHandlers<Context>`, not the error in the loop assignment. I just wanted to say that x on p is okay, but there is still an error when assigning to a.

**Comment by LiST-GIT** [comment]
In the type of x, undefined is present, so even if x is not on p, it should still be allowed, right?
```ts
let x: ((context: IContext & {
    eventHandlers: {
        x: [string];
    };
}, args_0: string, ...args: unknown[]) => void) | undefined
```
