### ISSUE TITLE
`[key: string]: string` overrides more specific properties

### ISSUE THREAD

**Issue by Arctomachine** [microsoft/TypeScript#59495]
### 🔎 Search Terms

"[key: string]: string"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `[key: string]` (one mention and seems to be not it)
- I was unable to test this on prior versions because it starts at 3.3.3 already

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240731#code/C4TwDgpgBAKghgJwOYWFAvFA3gWAFBRQD0RUwAFgJYDO+hAxlQDYAmCEAdgFzZ2FSUWPasASUOSANx8AvgG0AutLwyoAMl4EocgNYQQw0eKQLDYicpnL8oSFACSHMAFc0mXFpJQ4HFmSrU3uwCLJzAlPRwTHxe1AD2-vpQ1ORxzqxQAEbQ9HEAtmCIEH7ACRBwjFBxFBAIMaTiIuV+cQBm2noGyUYSpt3mSHyMlKzs3Jr8IWbGyoTySvhW+Pi5HCICTq48ji5uE1DDo5w8clhTUABE5BBMTHEXUDIKADSL1nitzhz04XEc3vR6BAwMB7MAIHkABTARAoYA8eDIVAASn27GAzgQ-xhSOAlmWeAqQJBYIhkPEu2RyiAA

### 💻 Code

```ts
type Target = {
  // this
  children: {
    id: string;
  }[];
} & {
  [key: string]: string;
};

type Input = {
  // and this are identical
  // so they should be compared to each other
  // instead of [key: string]: string
  children: {
    id: string;
  }[];
};

const input: Input = {
  children: [{ id: "hello" }],
};

function acceptItem(target: Target) {
  return target;
}

acceptItem(input);

```

### 🙁 Actual behavior

If `key: string]: string` is present in target type, it overrides more specific fields. Even if both target and input have identically defined fields, it will be used instead and might give error (if this field is not string).

### 🙂 Expected behavior

As less specific, it should be used as fallback. This way it will allow more specific fields to be compared first and avoid potential type error for valid js.

**Comment by LiST-GIT** [comment]
https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240731#code/C4TwDgpgBAKghgJwOYWFAvFA3gWAFBRQD0RUwAFgJYDO+hAxlQDYAmCEAdgFzZ2FSUWPasASUOSANx8AvgG0AutLwyoAMl4EocgNYQQw0eKQLDYiVAA+m-sVLlgwMNS4kA7h4B0oSNXpiwYCY4CU8Ae2QiFjD6aiJyEJYAIzCwnSIAJiIwpIArCHpgak8HAFsmAGJxFggADwBaakokDjhgAFd2agASAAY+QkEzY2VCeSV8GWV8H2gASQ4wdrRMXC0SKESyKmpN9gEajmBKejgmPg3qMO39KGpyMPbWKCToejDSsEQIFjJriDgjCgYQoEAQF1I4hEAN+YQAZto9AY7kYJKYUeYkHxGJRWOxuDZ+EMMSNZIplFN8Ph3hwRAJFsseAslitCTi8ZweHIsAceAAicgQJhMMJ8qAyBQAGkm0zwcPaHEKlDCHE29HoEECc2AEFKAApgIgUMAePBkKgAJSE9gdBCqw3m4AUql4QEarU6-XiFkW5RAA

**Comment by jcalz** [comment]
Index signatures don't imply "fallback"; they apply to every property.  This isn't a bug in TypeScript, it's the intended behavior.  You're looking for the feature requested at #17867.
