### ISSUE TITLE
Inferred Type Predicates doesn't narrow type if using other conditional expressions

### ISSUE THREAD

**Issue by zyoshoka** [microsoft/TypeScript#59509]
### 🔎 Search Terms

"Inferred Type Predicates"

### 🕗 Version & Regression Information

5.6.0-dev.20240801

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240801#code/C4TwDgpgBA8lC8UDeUDWEQC4oGdgCcBLAOwHMoBfAbgCgBjAe2LygYCMArHbACjgB8oxAK4AbUQEoA2gF0EUKSnRYoAcgCGqygBpkaDNlVstFXSPEzajZsCgAzQqOAR8EACYBGeey4A6B04uPDgIAHy4UACEiOaSVFAA9AmwsvRMLAHOrm4ATN6cOP6OWcFhEdFCYqJQAGQ1uL7KCIgaqhLxSVB8UIKx0jJpNvbFLu4AzPl+mUEh8OEhFX1Fgfilcw1N8C2a7YnJMKlAA

### 💻 Code

```ts
type O = { key: string };
const objs: (O | null)[] = [{ key: 'a' }, { key: 'b' }, null];
const filtered1 = objs.filter(s => s != null); // O[]
const filtered2 = objs.filter(s => s != null && s.key == 'a'); // (O | null)[]
const filtered3 = objs.filter(s => s != null).filter(s => s.key == 'a'); // O[]
```

### 🙁 Actual behavior

The type inferred for `filtered2` is `(O | null)[]` instead of `O[]`.

### 🙂 Expected behavior

I would expect `filtered2` to have the inferred type `O[]`, similar to `filtered1` and `filtered3`.

**Comment by MichalMarsalek** [comment]
This is working as intended. There are no one-sided typeguards.

**Comment by jcalz** [comment]
See #57465, where it mentions #15048

**Comment by zyoshoka** [comment]
Got it, thank you. I'm closing this issue.
