### ISSUE TITLE
emojis within string cause and issue(s)

### ISSUE THREAD

**Issue by radekcols** [microsoft/TypeScript#59512]
### 🔎 Search Terms

string, emoji

### 🕗 Version & Regression Information

5.4.2

### 💻 Code

```ts
const x = "🤖🦄🚀🌈🦋🐲🌚👽";
const index = x.indexOf("🦋")
const butterfly = x[4]
console.log(index)
console.log(butterfly)

```

### 🙁 Actual behavior

8
�

### 🙂 Expected behavior

4
🦋

### Additional information about the issue

seems like it typescript have some issues with emoji in strings..

**Comment by MartinJohns** [comment]
That's just how JavaScript works. It's completely unrelated to TypeScript.

See also: [What is a surrogate pair?](https://stackoverflow.com/questions/31986614/what-is-a-surrogate-pair)

**Comment by jcalz** [comment]
Indeed, this is not a bug in TypeScript. JavaScript strings are UTF-16, on purpose. See 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters, especially "string indexes refer to the index of each UTF-16 code unit."
