### ISSUE TITLE
Arrow functions cannot be used as user-defined type guards

### ISSUE THREAD

**Issue by pimterry** [Microsoft/TypeScript#5951]
User defined type guards work perfectly well for classic function statements, as in the release notes:

```typescript
interface Animal {name: string; }
interface Cat extends Animal { meow(); }

function isCat(a: Animal): a is Cat {
  return a.name === 'kitty';
}
```

However, it appears that the arrow function equivalent isn't acceptable:

```typescript
// Doesn't compile
var isReallyCat: (a: Animal) => a is Cat = (cat) => cat.name === 'kitty';
```

This gives "Type '(cat: Animal) => boolean' is not assignable to type '(a: Animal) => a is Cat'. Signature '(cat: Animal): boolean' must have a type predicate". I'm not clear how I would give that arrow function a 'type predicate', beyond what's already included here.

Is there a good reason for this? I can't seem to find it documented anywhere.

**Comment by Arnavion** [comment]
Using a type assertion instead of type annotation does work

```typescript
var isReallyCat = <(a: Animal) => a is Cat>((cat) => cat.name === 'kitty');
```

so I imagine it's just an oversight rather than deliberate.

**Comment by DanielRosenwasser** [comment]
The issue is that you don't want a `boolean`-returning function to be assignable to a type-guard.

```ts
function isHippopotamusFood(a: Animal): boolean {

}

let isReallyCat: (a: Animal) => a is Cat = isHippopotamusFood;

For that reason, type predicates need to be placed on the return type of the function proper. The declaration itself needs to opt in.

The following also works:

```ts
var isReallyCat: (a: Animal) => a is Cat = (cat): cat is Cat => cat.name === 'kitty';
```

or just

```ts
var isReallyCat = (cat): cat is Cat => cat.name === 'kitty';
```

__________

We could contextually type the return type to be a type predicate when appropriate, but I don't know if it'd really be worth it, and we usually never touch return types when performing contextual typing.

**Comment by Arnavion** [comment]
>The issue is that you don't want a boolean-returning function to be assignable to a type-guard.

Why not? Nothing prevents me from implementing a `x is Foo` function with `Math.random()` either.

**Comment by DanielRosenwasser** [comment]
Sure, but you have to intentionally opt in to that, and if you're totally sure you want to sabotage your users' experiences, more power to you. We're trying to avoid people from accidentally assigning an arbitrary function to a type predicate.
