### ISSUE TITLE
Instantiation expressions shouldn't be allowed in write positions

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#59535]
### 🔎 Search Terms

instantiation expression write read positions type arguments functions

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240805#code/JYOwLgpgTgZghgYwgAgKoGdrIN4ChnIhwC2EAXMumFKAOYDc+yct5hArsQEbSMC+uXKEixEKAPJcAVjiYwQAHgAqAPgAUASgpL+uACYQEAGzhQUCAPYgqyC9IqSpjfYZNnkl62GTtMUALIWCADWFJrIALwqaH7OAPRxyGAAFsDolMkW7EZ6IADk3jzMRkYWAO4Qerh2UgB08goY0NERPn6BIc4GxqYoRhDe8hTK6hqR0UqCCUmp6eiZ2bkFyEVwJeWVyBDAKdC4DU1QLW3QHcG4QA

### 💻 Code

```ts
interface User {
  name: string;
  age: number;
}

interface Obj {
  fn<T>(): T;
}
declare const obj: Obj;

declare const userMock: () => User;

// this shouldn't be allowed
obj.fn<User> = userMock;

declare let fn: <T>() => T

// this shouldn't be allowed either
fn<User> = userMock
```

### 🙁 Actual behavior

Those instantiation expressions are allowed

### 🙂 Expected behavior

They shouldn't be

### Additional information about the issue

it has been "discovered" here: https://x.com/kettanaito/status/1820456054724993191 😅

**Comment by jakebailey** [comment]
Just to show the unsafety here:

```tsx
let obj: { fn?: <T>() => T } = {};

obj.fn<number> = () => 1234;

if (obj.fn) {
    const stringValue: string = obj.fn();
    console.log(`typeof stringValue = ${typeof stringValue}`);
}
```

Will of course print "typeof stringValue = number"

[Playground Link](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240805&ssl=8&ssc=2&pln=7&pc=43#code/DYUwLgBA9gRgVgLggbwgMwHYH4kB4AqAfABQCUEAvIRPhAL6Up0DcAUK7HAHSa4YCuAWxggATtQoQylagEYATAGYALG1YBLNFM48M5ZKwhGIAYygYAzpCuj1GAOYA1AIbB+IJDbv3GOzGTZjU3MLKFAuYCh7YgADMABPAAcQKC0vBxc3EEYAEmQE5NSIdKdXdzoY0jY6IA)


And even weirder, if you do this with a function, you also get a nonsense error:

```tsx
let getValue: <T>() => T;

getValue<number> = () => 1234;

const stringValue: string = getValue();

console.log(`typeof stringValue = ${typeof stringValue}`);
```

[Playground Link](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240805#code/DYUwLgBA5uBqCGwCuIBcEA8AVAfACgEoIBeHCLAbgCgqYwFkQMA7JAWwCMQAnM4iQiTIBGAEwBmACzUqAYwD2zAM6QV3AJbMoDFOjWaoJaHEQpCMhcvmgAdMHlQ8AAzABPAA4h5AMwj6tOiBGACQA3m6ePn5gGgGmIAC+TgQUQA)

![image](https://github.com/user-attachments/assets/eb1f4d81-3fc2-4687-90ae-17208bd12334)

So the checker has no idea that this thing is actually in an assignment.

Add the `!` and it of course typechecks:

```tsx
let getValue!: <T>() => T;

getValue<number> = () => 1234;

const stringValue: string = getValue();

console.log(`typeof stringValue = ${typeof stringValue}`);
```

[Playground Link](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240805#code/DYUwLgBA5uBqCGwCuICEAuCAeAKgPgAoBKCAXjwhwG4AoGmMBZELAOyQFsAjEAJwtIRiZCgEYATAGYALLRoBjAPasAzpDW8AlqyhMUmDdqhlocRCmJylqxaAB0wRVAIADMAE8ADiEUAzCIY6eiAmACQA3h7efgFgWkHmIAC+LkRUQA)

**Comment by kettanaito** [comment]
How to approach a situation when I want to override a method with a more permissive type argument with a mock with a more narrow type argument (exact example from above)? That won't be possible unless I cast something into something else. Would love to hear general guidance on this.

**Comment by RyanCavanaugh** [comment]
If you're doing something unsafe it's almost always going to require a type assertion. That's sort of definitional.

**Comment by kettanaito** [comment]
@RyanCavanaugh, not sure how unsafe that example is. Assigning a more narrow but still matching type to a more broad type argument doesn't sound unsafe but I may be wrong. 

```ts
const obj = {
  foo<T>(e: T): void {}
}

const mock: (e: User) => {}

obj.foo = mock
```

Is this considered unsafe to do? When you use `obj.foo`, you _are_ providing an exact type of `T`. Why cannot a different function do the same?

**Comment by jakebailey** [comment]
That is unsafe and results in an error: [Playground Link](https://www.typescriptlang.org/play/?ssl=9&ssc=11&pln=9&pc=15#code/C4TwDgpgBAqgzhATlAvFA3lAdgQwLYQBcUcwiAllgOZQC+A3AFCMDGA9lqVGwEYBWqDIyhQAZmzYAeACoA+ABREo0gJTEAbm3IATDLUb7G2iCwA2ORNHadgUPGxYBrYouLwkK1LL1NGvPgB04myC9k5AA)

```
Type '(e: User) => {}' is not assignable to type '<T>(e: T) => void'.
  Types of parameters 'e' and 'e' are incompatible.
    Type 'T' is not assignable to type 'User'.(2322)
```

I can take your code and then call `obj.foo<string>()` even though the underlying function is expecting a `User`.

What you're asking for is effectively an in-type system way to be able to violate the substitution principle.

**Comment by jakebailey** [comment]
Debugging, this is actually a regression; go back to TS 4.9, and these are all errors:

[Playground Link](https://www.typescriptlang.org/play/?ts=4.9.5#code/DYUwLgBA9gRgVgLggbwgMwHYH4kB4AqAfABQCUEAvIRPhAL6Up0DcAULHAHSa4YCuAWxggATtQoQylagEYATAGYALG1atQkAObgAagENgfEHiJSqNNtrD7DIXoOFjGZ2YpVr14CFZtG5AQhMScnN8S10DP3shUXFJENdlNiA)

Our reference check uses `skipOuterExpressions` to skip assertions, but as of #50820, that now treats instantiation expressions as an assertion, so we treat this as legal.
