### ISSUE TITLE
The use of generics with keyof in the class does not return the expected result.

### ISSUE THREAD

**Issue by LiST-GIT** [microsoft/TypeScript#59534]
### 🔎 Search Terms

generics
keyof

### 🕗 Version & Regression Information

5.6.0

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-beta#code/C4TwDgpgBAogbhAdsAagQwDYEsAmbgD2ATgM5QC8UAShAMbE4A8JwRWiA5gDRQEBGAKzrAAfAG4AUBIBmAV0S1gWAoihp1aABRoAXFBZtOASigBvKAF8pchUpVQwsvthIALRvUQsoAFR-hoCAAPYCQcMgBrCBACaVgEZHRsPEJSEU1QSD0-AKM9OAJcMwkoUrUNDNyJKwlaDDQSMgBBRh8oYNDEcPikVExcfGISEWKyhycXd09vHMh2kLDI6NjfdMyIbP9IPKgCotMSsbKNLXWTAHpzqCaiDlkAW17eOPWoAHIDdg4oAB8oRAefAgRF++hA9z4BAwbygWDIiAIwDUjSwHEQaGc0EIDjQRDQj1CIJWrw+rC+bwAdIdSlYLEA

### 💻 Code

```ts
type EventValidators = Record<string, object>;

function aaaa(a: string) { }

function publish<const TType extends keyof EventValidators>(type: TType): void {
    aaaa(type)
}

class A<T extends EventValidators> {
    publish<const TType extends keyof T>(type: TType): void {
        aaaa(type) // Argument of type 'string | number | symbol' is not assignable to parameter of type 'string'.
    }
}
```

### 🙁 Actual behavior

The use of generics with keyof in the class does not return the expected result.

### 🙂 Expected behavior

Expected to return string.

**Comment by MartinJohns** [comment]
This is working as intended. The type of `T` could be `Record<string | number | symbol, object>`.

**Comment by jcalz** [comment]
This is working as intended. Generic constraints don't prohibit extra properties. You can write
```ts
const s = Symbol(); new A<{ [s]: 1 }>().publish(s);
```

Duplicate https://github.com/microsoft/TypeScript/issues/44234#issuecomment-847313848 https://github.com/microsoft/TypeScript/issues/58253#issuecomment-2067193842
