### ISSUE TITLE
Annotated callback parameters are not prioritized above un-annotated ones

### ISSUE THREAD

**Issue by Rugvip** [microsoft/TypeScript#59548]
### 🔎 Search Terms

"callback inference", "method inference" 

### 🕗 Version & Regression Information

Testing this in the playground it seems to be an issue all the way back to 3.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.4#code/GYVwdgxgLglg9mABFApgZygHgCoD4AUcADrAmgFyIDeAUIosGAIyX5SXYCUiAvLogDc4MACYBuOgzAAmVu0Rde-IaIkBfTpRUjqamjQD0BxADFw0eEiIAnYmkQBaRAHc41gNZoaqDPlr1GFmQlXQAaSUZZRDZKDGsYMABzbj4wmg0JQ2MAWRQoAAs4EXtnGALEAEMwMDgoCtIkYBhrDEcXN09vdCg-COYYxDiE5LSAmTZuKjVwjP0jRFyCopKy-Mrq2vrLRAAbCtanETh0MAByKHaPLt9-KSYJ0alpAaGkyen0zjEgA

### 💻 Code

```ts
function test<T>(options: {
  fn1: (t: T) => void;
  fn2: (t: T) => void;
}): void {}

// Function props - works
test({
  fn1: t => {},
  fn2: (t: string) => {},
});

// Methods with annotation first - works
test({
  fn1(t: string) {},
  fn2(t) {},
});

// Methods with annotation last - doesn't work
test({
  fn1(t) {},
  fn2(t: string) {},
});
```

### 🙁 Actual behavior

When providing multiple function properties with the same type parameter as a function parameter, the type parameter will always be inferred from the first function property.

### 🙂 Expected behavior

I'm expecting the explicitly annotated function callbacks to have higher inference priority than the ones without annotations.

### Additional information about the issue

Not sure whether this is a bug or intended behavior, but though I'd report it to check. It seems related to #18654, although turning off strict function types doesn't change the behavior, it just removes the type error where the `unknown` param is not assignable to `string`.

It also looks like it's related to for example #58746, but slightly different.

**Comment by Andarist** [comment]
This one boils down to https://github.com/microsoft/TypeScript/issues/47599

Contextual parameters are assigned in source order and it isn't a unique limitation for callbacks contained in objects. The same happens for arguments lists: [TS playground](https://www.typescriptlang.org/play/?ts=5.5.4#code/PTAEHcEsBcAtQPYCMBWAoAJgUwMYBsBDAJy1ADMBXAOx2kgStGiwGdoAeAFQD4AKZFAC5QAbzShQAByIIMFHFmG9iAc2HUA1lQTgqASlABebqE4BucaBwMWFALaLQyomtMHjoAG4JIGCwF89YW9fCzRmNl4xCWlZeUdnFXcTABYAJgAaS2sqWwclVWTRSwlVCwkJEAA9AH5LfyzAsIjoKOybewTCoxNoirKS0Gq6iQbLWLkFApci9Ma9MJAIGHhVTqpoUDxINkxcQhJyalp6RhauPnGZSa6XdSotHX0e0yyJHLzb104ikIwsoJeHx+NDhVitSyJWaZSHdDx9UoucoVYb1AHNcG8WEzF4I0ADCpDYC1NHYpIvOZoBZoIA)

**Comment by Rugvip** [comment]
@Andarist yep I noticed that too, just found the object form to be a simpler thing to report really 😅

Closing this and adding a 👍 to #47599 instead
