### ISSUE TITLE
TSX to JSX transformation doesn't match closing tag correctly

### ISSUE THREAD

**Issue by vjau** [Microsoft/TypeScript#5955]
With following TSX code :

```ts
Import {Provider} from "react-redux"

ReactDOM.render(
        <Provider>
          <App />
        </Provider> , document.getElementById('app')
      );
```

I get following JSX code

```ts
ReactDOM.render(<react_redux_1.Provider>
      <App_1.default />
    </Provider>, document.getElementById('app'));
```
"/Provider" closing tag doesn't match "react_redux_1.Provider" opening tag

What am i doing wrong ?

typescript 1.8.0-dev.20151204 Target es5 Modules commonjs jsx preserve

**Comment by DanielRosenwasser** [comment]
I think this is a bug. @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
Fixed in master
