### ISSUE TITLE
"Go to Symbol in Workspace…" does not show symbols in dependencies

### ISSUE THREAD

**Issue by tinder-tannerbennett** [microsoft/TypeScript#59551]
### 🔎 Search Terms

typescript, symbol, go to symbol in workspace, dependencies

### 🕗 Version & Regression Information

I only just noticed this behavior as it is a feature I don't use often

### 🙁 Actual behavior

When using the "Go to Symbol in Workspace…" feature in VS Code, only symbols within my project are shown.

### 🙂 Expected behavior

"Go to Symbol in Workspace…" should show symbols in my project _and_ my dependencies.

### Additional information about the issue

This UI is populated by the language server, so that is why I'm filing the issue against Typescript and not against VS Code.

Tested using Typescript `5.5.4` and VS Code `1.92.0`

**Comment by RyanCavanaugh** [comment]
This is intentional
