### ISSUE TITLE
Add support for Iterator Helpers (now stage 3)

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#59568]
### ⚙ Compilation target

ESNext

### ⚙ Library

n/a

### Missing / Incorrect Definition

IterableIterator should have map/filter/etc.

### Sample Code

```TypeScript
// Tested in both Node 22 and latest Edge

const m = new Map([[1, 2], [3, 4]]);
const keys = m.keys(); // IterableIterator<number>
const iter = keys.map(n => n * 100);
// Property 'map' does not exist on type 'IterableIterator<number>'.ts(2339)

const val = iter.next();
console.log(val);
// {value: 100, done: false}
```

### Documentation Link

* https://github.com/tc39/proposal-iterator-helpers
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/map
* https://caniuse.com/?search=JavaScript%20built-in%3A%20Iterator%3A%20map

**Comment by xiBread** [comment]
Already added in #58222

**Comment by jakebailey** [comment]
Yep: [Playground Link](https://www.typescriptlang.org/play/?target=99&ts=5.6.0-dev.20240808#code/PTAEBUFMGcBdICagJYDtQCMD2sAWoA5LBSUAJjNAENUkAbK+OUAUQQHNIAoLgYy1TMAtqAC8oVJADuoALJUADgAoA2ioCMAGnIBdbSoDM2gCw6dASgDcfAcwDWkAJ7QxoIQDoHzpVdAhQAJLwAE5UGHSQQZChsFjBADyoAK5CGNEAfDaCsCghrl7Q7kKKSuii6RKgAFSg6gAMdVZc-gAKwVgK0bCOoADkxQq9oAhYMBI4oJAAHsjMAqDdnX1RoeGRIYxxiSlpwem97rDQSmQGBgCc5jz82aAAblR0rsgh7pJTsD7WN9BYEe50LDsJQPOhNfwAb1BSUgAC5ag1tCNJPCAGaPaCQAC+QA)

**Comment by sdegutis** [comment]
Ah I thought I saw this somewhere. Thanks guys.

**Comment by sdegutis** [comment]
Why do those docs say

> and for some reason `reduce`

? Like, is reduce known to be useless in lazy iterators or something?

**Comment by RyanCavanaugh** [comment]
I have no idea lol. @DanielRosenwasser ?

**Comment by DanielRosenwasser** [comment]
It was just a playful dig at the method. `reduce` can be useful but unfortunately I find most uses of it are super inefficient, are just a bad `forEach`, or overly clever. You can feel free to use `reduce` and I won't judge you. 😄

**Comment by sdegutis** [comment]
True, I can't remember how many years it's been since I actually used reduce.
