### ISSUE TITLE
TypeScriptModuleResolution 'node'  doesn't follow links in Visual Studio

### ISSUE THREAD

**Issue by woppa684** [Microsoft/TypeScript#5956]
I'm using typescript 1.7.4 in Visual Studio 2015. Because of our (MSBuild) build system I can not create an actual node_modules folder where my sources reside. Since Visual Studio supports linked files and folders I tried creating links like this:

```
  <ItemGroup>
    <Content Include="<some location>\node_modules\**\*.d.ts">
      <Link>node_modules\%(RecursiveDir)%(FileName)%(Extension)</Link>
    </Content>
  </ItemGroup>
```

This nicely links all the files I actually need to compile in my project. However, the typescript compiler doesn't understand these links and only works if I actually have those files physically available in the virtual location... How can I solve this without actually putting those files where my source files are?

Previously, before Angular2 switched entirely to this node-style resolution I was able to link to bundled d.ts files and put them in a virtual "typings" folder. This worked like a charm :)

**Comment by mhegazy** [comment]
I am not sure i see what links have to do with node module resolution. what is your configuration options? can you share a project?
Content files are ignored by the TS compiler, only TypeScriptCompile items are honored. also consider using a tsconfig.json with TS 1.8, see  https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-support-for-tsconfigjson-in-visual-studio-2015 for more details.

**Comment by mhegazy** [comment]
Please reopen with more information.
