### ISSUE TITLE
the union type bug?

### ISSUE THREAD

**Issue by eveningwater** [microsoft/TypeScript#59572]
### 🔎 Search Terms

union type

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______
all version

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-beta#code/C4TwDgpgBAMglgZ2AFQPaoDYIEoQI4CuESUAvFAN4BQUtUcAJgPwBcUSATnAHYDmA3FQC+VUJFiJgAETgBDXt1QJEuQsWBlKNOo1btgXPoJFjoAYVQBbS6m64EAHmQA+TdTpQAxqgYQ9nHgFtWgZZYFk9ZEEPSwRefwNA41FwaHgkNEwEKTDZe01cbw4GBwC+ABp9Q15nAG0AXUFTCSQZeUVlbNz88kLUYtLEiqrAusaU8XSUdCxNAAoAOiXZDl4EFinMrFUiEgaASjJXAAUOK0QIBwtrW3sHTZmu8PtnZybUluk5BSVEeaWFis1mwpm0fp0duoDkcoKdzghLtcbHZiPdJGCOogcs9iK9BFRvNwSBhJFt1p8yf9lqsEIdSK53HRCQhMBAFhhULw5gBGXncypA2nRDwcCDAAgcbhQbgQADusLOlguczmopZGAAbhA6a41ZgtXMKF4fBAWAByABMAAYrWbKqFwiwGpVYrxzcB1NyzUJ9vthATbMT0d9MeTQSHfggqYCaTqtB5jUTWezOTy+QLY8K6KLxZLpXKFfCICq9ZrtTDSwajd5fObrbb7bknfUXXF3eoLd7ff6MGKoJYxQALHwg4PtSNQAA+FMe+Ig3AIligAFkhz5kB9GbQpABJACCAHEAHIAeQAyjuz5ozQwI507cEoFtr8AZmb-cyNAAzKXkOamNhV2AYcGA3SA4y3egv3-D5SDglc11A1IFl3Q9TwvM99kgmJEM0ElWjvRAsygEQPDgaDmjg8ggJAsC2S2LDHxw4CfDw0lZ0fERH3IuYBxYhhGITOgAHphKgQA+DcAFF3KllQcQHoKNgOgPiQKgXwGAITwIAYKBBwgUU2EWalgRnLJoXpQslQRK4rGRO4HiybE8lxZwmJEsSdylJT+hASo4A0BBhwIDAdIAI2gWQoAIbg4FsKBTDc2gVJ8OZ9gWJTuFVYgYWZZMOS5NVfWIkQRCAA

### 💻 Code

```ts
type ListToolsRequest = {
    id?: string;
}
type ListDiagnosisRequest = {
    id?: string;
}
type CommonRes<T> = {
    code?: string;
    data?: T;
    msg?: string;
}
type ListToolsDataRes = Record<string, string>[];
type ListDiagnosisDataRes = Record<string, string>[];
type ListTools = (...args:ListToolsRequest []) => Promise<CommonRes<ListToolsDataRes>>;
type ListDiagnosis = (...args: ListDiagnosisRequest[]) => Promise<CommonRes<ListDiagnosisDataRes>>;

const listTools: ListTools = (...args) => {
    console.log(1111, args);
     return new Promise((resolve) => resolve({ code:'200', data:[], msg:'测试1'}))
}
const listDiagnosis: ListDiagnosis = (...args) => {
     console.log(1111, args);
     return new Promise((resolve) => resolve({ code:'200', data:[], msg:'测试2'}))
}
let method: ListDiagnosis | ListTools;

enum MethodType {
    DIAGNOSIS = 'diagnosis',
    Tool = 'tool'
}
const fn = (type: MethodType) => {
    if(type === MethodType.DIAGNOSIS){
        method = listDiagnosis;
    }
    if(type === MethodType.Tool){
        method = listTools;
    }

    if(method){
      // 🤔, why is the method deduced here: (...args: ListTools[]) => Promise<CommonRes<ListToolsDataRes>>
// In theory, it should be a union type
        method().then(res => console.log(res));
    }
}

```

Why is the method deduced here: `(...args: ListTools[]) => Promise<CommonRes<ListToolsDataRes>>`
In theory, it should be a union type?

### 🙁 Actual behavior

(...args: ListTools[]) => Promise<CommonRes<ListToolsDataRes>>

### 🙂 Expected behavior

method: (...args: ListDiagnosisRequest[]) => Promise<CommonRes<ListDiagnosisDataRes>> | (...args:ListToolsRequest []) => Promise<CommonRes<ListToolsDataRes>>;

### Additional information about the issue

the type is error

**Comment by MartinJohns** [comment]
This is working as intended. Your types are absolutely the same, so they're simplified.

**Comment by eveningwater** [comment]
> This is working as intended. Your types are absolutely the same, so they're simplified.

I understand, thanks！
