### ISSUE TITLE
Type inference considers only type amendments (if any are present), ignoring original typings

### ISSUE THREAD

**Issue by nicky1038** [microsoft/TypeScript#59576]
### 🔎 Search Terms

type inference amended types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type inference

### ⏯ Playground Link

[Link](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240809#code/JYOwLgpgTgZghgYwgAgOIRNYCCiA3DMAFTigHMIwAeI-QgOTgFsUIAPSEAEwGdkewUUGQA0yWgXDJ2nXsjrgAfMgDeAKACQcLlwVgAMsAEZoALmQAKMAE8ADhHMSGzCGIA2RzmcsRJYR3oAlMgAvMp4APbAXMFhyJHRapoA9Mn8ESwAFhEA7mLAMMjaun6GxphQyEbIXBAIbqQQXMhgmdU5cNZirdAo1SAR0lBQEVBqyBPIqUU6emVeUFZ2DuJ6jCzuniZQ5ha+hAF+seFRMeYJXGoAvkkIESACM1zz26HINGsu0hwYcgJCIFEqz831kfD0igsmh4EQArlAkOZ0BVsHoSORKB8-OtXMDCIoRONJvtwDjDs4NmpAudTqFlOoNDD4UgAHTFOZbCp7bEuMQWY6qK6Ba5JaY2exFFjcKVgNSgSCwRAoADqoC4uVUmnZpU50CW9nMAHIELCBBk9IbNuVvFY2jxzKruLkxCT-PIjnTkLCQABrAY5EBiCK2MDAe48AD85hUQppiRuammOVGPvtVTAyBYcAeLUycAz4pQLmlhBqEQgPBAhozUAgtgaSGQo2AZFAcDcLTswh4ahyatybNmOuti0NLB4PDgFEtlgFMeF03VFarGeTUB95kLVRAMF6IEb9zc1mQdwe0WgfC3xa4MuQACNYRmBhnm62QO3O7Zu2pii8uX2nTyZAxwrSdpwXNJ2HrbBgAzHh7AQApsHzMMQCbQot1sUgXAVPgmDgH0K3TZA1x9H8dD-aAqBAicpwgGcIQsAD1SAmiwPowIgA)

### 💻 Code

```ts
interface GenericEventTarget<TEventName extends string, TEvent extends Event> {
	addEventListener: (type: TEventName, listener: (event: TEvent) => void) => void

        // somehow, if addEventListener is declared this way, there is no error
        // addEventListener(type: TEventName, listener: (event: TEvent) => void): void
}

const addListener = <TEventName extends string, TEvent extends Event>(
	source: GenericEventTarget<TEventName, TEvent>,
    eventName: TEventName,
): void => {
	source.addEventListener(eventName, () => {})
}

// type amendment
interface Window {
	addEventListener(type: 'customEvent', listener: (this: Window, event: Event) => unknown, options?: {}): void
}

// works: it means that type amendment doesn't replace original typings
window.addEventListener('message', () => {})
// doesn't work: type inference only considers type amendment but not original typings
addListener(window, 'message')
// explicit specification of type parameters makes it work
addListener<'message', Event>(window, 'message')
```

### 🙁 Actual behavior

`TS-2345` error in the line `addListener(window, 'message')`: `Argument of type '"message"' is not assignable to parameter of type '"customEvent"'`.
It is wrong because Typescript infers `TEventName ` as `customEvent`, considering only type amendment and ignoring original typings.

### 🙂 Expected behavior

No errors are expected, because original typings for `Window` should also be considered

### Additional information about the issue

I have a generic utility function that subscribes to certain event of provided event source, it looks like one in the example.

I use this utility function including for subscribing to events of `window`. After [vite](https://github.com/vitejs/vite/pull/17615/files#diff-9377bf04a22205467980e8409cb506410c7684f31069a146edba29a5d26c4e4f) added its own type amendment for `Window` interface, errors in my code occurred, because in the case there are any type amendments, Typescript doesn't consider original typings for `Window` interface during type inference.

**Comment by RyanCavanaugh** [comment]
The original typings are considered, but the newly-added overload in this case is chosen when there's no other inference information available. I think you want to augment the underlying map instead here
```ts
interface WindowEventMap {
	customEvent: Event & { neat: string };
}
window.addEventListener("customEvent", x => {
	x.neat; // works
});
```

**Comment by nicky1038** [comment]
@RyanCavanaugh thank you for this suggestion! I'll offer using this way of adding new event type to `Window` interface in vite repo.
But could you please clarify why is no other inference information available? As shown in the example, the original typings are visible, so it seems like `TEventName` should also be inferred from them?

**Comment by RyanCavanaugh** [comment]
It'd take a very long time to step through the inference process and figure out what all the candidates are, etc.. The example is reproducible without interface augmentation, so is therefore not related to it:
```ts
interface Thing {
	// Your definition (goes in first):
	addEventListener(type: 'customEvent', listener: (this: Window, event: Event) => unknown, options?: {}): void

	// lib.dom.d.ts definitions:
    addEventListener<K extends keyof WindowEventMap>(type: K, listener: (this: Window, ev: WindowEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
}
interface GlobalThing {
	addEventListener<K extends keyof WindowEventMap>(type: K, listener: (this: Window, ev: WindowEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
	addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
}

// Local version
declare const someThing: GlobalThing & Thing;
someThing.addEventListener('message', () => {})
addListener(someThing, 'message')
addListener<'message', Event>(someThing, 'message')
```
