### ISSUE TITLE
Empty class type is satisfied by literally anything

### ISSUE THREAD

**Issue by sdegutis** [microsoft/TypeScript#59588]
### 🔎 Search Terms

I am too tired to think of variable names for this bug report, let alone search terms to describe it. I struggled to write the title.

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYGwhgzhAECC0G9oF8BQwD2A7CAXaYAXHNALzQDkARhQNypA

### 💻 Code

```ts
class Foo { }
const definitelyNotAString: Foo = 'uhh';
```

### 🙁 Actual behavior

Type error.

### 🙂 Expected behavior

The everything's-okay-alarm goes off continuously.

### Additional information about the issue

(I actually hate the simpsons.)

**Comment by sdegutis** [comment]
I get why. It's an empty class, and so the class's type is essentially an empty interface. And `'uhh' satisfies interface{}`.

And I get that it will fail the moment I put something in Foo, like bar='qux' or solveWorldHunger(){await worldPeace()}.

But it just seems like, for consistency, it should fail early. Although I get now why it doesn't: the moment I add a=1 into Foo, and try to assign new Set() to foo:Foo, it will fail because a lack of *duck-typed overlap*. And in theory, that's the point of structural-type-checking.

The problem with that is, this *does* work:

```ts
class Foo {
  size = 3; // size is a (read-only) number on Set; a random-value, read-write property with the same name *technically* is compatible
}
const definitelyNotAString: Foo = new Set();
```

***That shouldn't work either.***

**Comment by sdegutis** [comment]
I don't know, maybe I'm wrong. I mean technically a Set meets all the behavioral characteristics of a Foo right now.

Except that Foo is not an interface but a class. So `: Foo` in line 4 above should guarantee `somefoo instanceof Foo === true`.

I guess that's the bug I'm trying to describe.

**Comment by sdegutis** [comment]
Ah I just guessed the response I should expect:

> Technically `const foo: Foo = someFoo()` can't guarantee `foo instanceof Foo` simply because `someFoo()` might return another value at runtime that we don't know about, especially if it returns `any` either explicitly or implicitly. It's the nature of a dynamic language, we just can't know that `foo` is really a `Foo`, so we have to use `instanceof` at runtime to check.

Okay, true, but should we be allowed to *directly assign known non-Foo values* to a Foo? I'm confusing myself. I'll see myself out.

**Comment by MartinJohns** [comment]
This is working as intended and mentioned in the FAQ.
