### ISSUE TITLE
"node:child_process" exec function has compiling error

### ISSUE THREAD

**Issue by maxktz** [microsoft/TypeScript#59599]
### 🔎 Search Terms

"child_process exec function error",
"node_modules/@types/node/child_process.d.ts:1023:14",
"exec function error node.js"

### 🕗 Version & Regression Information

- This is the behavior in every of @types/node version I tried.
- This is the behavior in every of Node.js version I tried.

### 💻 Code

My `index.ts`
```ts
import { exec } from "child_process";

async function main() {
  const cmd = `ls`;
  const runningProcess = exec(cmd, { shell: true }); // here error happens
}

main();
```

My `tsconfig.json`:
```json
{
  "include": ["src/**/*"],
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "rootDir": "./src",
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```
Dependencies (last time I run it. In general I tried many versions):
```json
{
  "@types/node": "^22.2.0",
  "ts-node": "^10.9.2",
  "typescript": "^5.5.4",
}
```

### 🙁 Actual behavior

Compiler error shows that `exec` function takes only `command` and `callback`

But in node.js it has one more argument, `options`, which I'm trying to pass.

[Node.js documentation reference](https://nodejs.org/docs/latest-v20.x/api/child_process.html#child_processexeccommand-options-callback)

When I tried to `// @ts-ignore` this error, it works well, or if you run same code without TypeScript. So the error in @types/node.

**Comment by xiBread** [comment]
File an issue at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/), they handle the Node types.

**Comment by maxktz** [comment]
thx
