### ISSUE TITLE
vscode should honor tsconfig.app.json - not just tsconfig.json 

### ISSUE THREAD

**Issue by Gorthog** [microsoft/TypeScript#59592]
### 🔍 Search Terms

vscode ignoring tsconfig.app.json
not honoring tsconfig.app.json
not respecting tsconfig.app

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When building the app using tsc, we can tell tsc which tsconfig we use to build, and thus do not get any errors. But vscode in editor only respects tsconfig.json, and thus our build and editor do not agree.

### 📃 Motivating Example
Default value of strictNullChecks is true, and since vscode does not respect tsconfig.app.json, it does not know that strictNullChecks is set to false.

https://github.com/Gorthog/vscode-tsconfig.app.json

### 💻 Use Cases

1. Use case: In monorepo, we have multiple tsconfig.json files in the same folder. one for app, and one for test. 
2. Motivation: Build and editor disagree
3. Workaround: create a dedicated tsconfig file only for vscode editor

**Comment by MartinJohns** [comment]
That's a VSCode issue, not TypeScript.

Duplicate of https://github.com/microsoft/vscode/issues/12463.

**Comment by Gorthog** [comment]
You are correct. My bad. Closing issue.
