### ISSUE TITLE
Use-before-assignment check misses uses of vars defined in previous branch in switch

### ISSUE THREAD

**Issue by mheiber** [microsoft/TypeScript#59591]
### 🔎 Search Terms

use-before-assignment, ReferenceError

### 🕗 Version & Regression Information

I tested on the following versions and saw the same behavior in all of them:

v5.6.0-dev.20240811, 5.6.0-beta, 5.5.4, 5.4.5, 5.3.3, 5.2.2, 5.1.6, 5.0.4, 4.9.5, 4.8.4, 4.7.4, 4.6.4, 4.5.5, 4.4.4, 4.3.5, 4.2.3, 4.1.5, 4.0.5, 3.9.7, 3.8.3, 3.7.5, 3.6.3, 3.5.1, 3.3.3

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240811#code/C4TwDgpgBA8gTgHgCoBooFUB8UC8AoKQqAHygG9gBDAcwC4oByAezgBkIAzYBtAN0oA2AVwj0kAXwJFSFGvWZwASgEtqAC259BI+unEBuPHlCQoAZQBGuKAAoAzvTvA4ygHbUAlLmwWmTARCUroZ4HEKuAMbAykyuUHDhNgAe9PAIlmiWmB70luRShHYA7srAEWq2SQB0VJ75RA1QEZR20ABELOxcbbQFjQ0RsU5QINbV-MIQhv39cBDAQnBxINMzza1QHUqqGj19M1AA9IdQrhBJwFACbtAclMoCdlCUlwmu0QC2EFVQAKJJkCiEAAJlAkGYoMAmFAwHAmMChBFoJQoEJWnAALQWTgsCAYlp2VSuL7vKDA5Q0VxMJzKCL7GZzBZLSpeHDYEDJDz6I4nRScCBzSIQX5wOFwegAYSCVMulAiSLsTwYIAYUGxHFxUDcpQp1wAXi8Yq4jA1JJI8G8bLI6JsWCp1MA2lpJvQbAB9VnYZwicQeGxtYAQGnuNoeIA

### 💻 Code

```ts
type Or<T, U> =
    | {tag: 'orLeft', value: T}
    | {tag: 'orRight', value: U};

type Sb = (s: string) => boolean;

function run(x: Or<Sb, Sb>): Sb {
    switch (x.tag) {
        case "orLeft":
            const y = x.value;
            return y;
        case "orRight":
            // next line fails at runtime. Expected TS to produce a use-before-assignment error
            return (x) => y(x); // ReferenceError: Cannot access 'y' before initialization

    }
}

run({tag: "orRight", value: (_) => true})("testing")
```

### 🙁 Actual behavior

TS produces no type errors.

### 🙂 Expected behavior

Expected TS to give a use-before-assignment error because the variable `y` is referenced before assignment.

**Comment by whzx5byb** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/19503.

**Comment by mheiber** [comment]
duplicate of https://github.com/microsoft/TypeScript/issues/19503, thanks @whzx5byb for finding the dupe
