### ISSUE TITLE
breaking change between ts 1.6 & ts 1.7.3

### ISSUE THREAD

**Issue by cmichaelgraham** [Microsoft/TypeScript#5960]
note: with [skeleton-navigation-typescript-vscode](https://github.com/cmichaelgraham/skeleton-navigation-typescript-vscode), you will encounter problems with typescript > 1.6 - seems to make errors around the system register generated code

**Comment by mhegazy** [comment]
Can you elaborate on the issues? and if they are covered by the known breaking changes in https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-17

**Comment by cmichaelgraham** [comment]
i don't believe that it is covered.  when i inspect the generated code, the ts 1.7.3 looks like this:

the error that occures when running the ts 1.7.3 generated code is:

```
shim.min.js:1773 Error: Unexpected anonymous System.register call.
Error loading http://localhost:9000/dist/main.js
at l.<anonymous> (http://localhost:9000/jspm_packages/system.js:5:929)
at l.<anonymous> (http://localhost:9000/jspm_packages/system.js:5:5404)
at l.reduceRegister_ (http://localhost:9000/jspm_packages/system.js:5:12561)
at l.pushRegister_ (http://localhost:9000/jspm_packages/system.js:4:28310)
at l.register (http://localhost:9000/jspm_packages/system.js:5:452)
at execute (http://localhost:9000/dist/main.js:7:20)
at u (http://localhost:9000/jspm_packages/system.js:5:97)
at Object.execute (http://localhost:9000/jspm_packages/system.js:5:3188)
at y (http://localhost:9000/jspm_packages/system.js:4:9948)
at w (http://localhost:9000/jspm_packages/system.js:4:10327)
```

```javascript
System.register(['bootstrap'], function (_export) {
    'use strict';

    _export('configure', configure);

    function configure(aurelia) {
        aurelia.use.standardConfiguration().developmentLogging();

        aurelia.start().then(function (a) {
            return a.setRoot();
        });
    }

    return {
        setters: [function (_bootstrap) {}],
        execute: function () {}
    };
});
```

and the ts 1.7.3 looks like this:

```javascript
//main.js in dist/
System.register([], function (_export) {
    "use strict";

    return {
        setters: [],
        execute: function () {
            System.register(['bootstrap'], function (exports_1) {
                function configure(aurelia) {
                    aurelia.use.standardConfiguration().developmentLogging();

                    aurelia.start().then(function (a) {
                        return a.setRoot();
                    });
                }
                exports_1("configure", configure);
                return {
                    setters: [function (_1) {}],
                    execute: function execute() {}
                };
            });
        }
    };
});
```

**Comment by mhegazy** [comment]
this took a while of digging :)

so the issue is in your tsconfig.json you specify [`module: system` and `target: ES6`](https://github.com/cmichaelgraham/skeleton-navigation-typescript-vscode/blob/master/tsconfig.json#L5).   in TS 1.6.2 this was an illigal combination, and running it on the command line would give you an error; gulp-typescript for some reason does not show this error (@ivogabe  can you comment on why this error was not surfaced?).

In TS 1.7.3, you can use this combination, the problem is your babel step did not expect that, so it wrapped your module in another layer of system.register.

Removing the `module` field from tsconfig.json, or setting it to `module`: `es6` should address the issue.

**Comment by cmichaelgraham** [comment]
@mhegazy - i am in awe :+1: :+1:

**Comment by ivogabe** [comment]
@mhegazy I don't know why, I've opened ivogabe/gulp-typescript#247

**Comment by cmichaelgraham** [comment]
@mhegazy @ivogabe @EisenbergEffect - check out what we can do in aurelia and typescript now that you fixed that:

(open source work)

here's a running sample of Aurelia framework launching a globe with earth quakes.

* click-drag to spin the globe
* right-click-drag to change the horizon

[esri globe with earth quake data](http://cmichaelgraham.github.io/skel-nav-esri4-vs-ts/index-release.html#/esri-globe)

[source code repository for the sample](https://github.com/cmichaelgraham/skel-nav-esri4-vs-ts) - clone and open with vs2015

![image](https://cloud.githubusercontent.com/assets/10272832/11682515/b407ad4e-9e22-11e5-9724-93049b7ad6a7.png)

for that sample, this is the html view [esri-globe.html](https://github.com/cmichaelgraham/skel-nav-esri4-vs-ts/blob/master/skel-nav-esri4-vs-ts/views/esri-globe.html):

```html
<template>
    <section class="fill-vertical">
        <div class="fill-vertical" id="globe"></div>
    </section>
</template>
```

and the typescript view model [esri-globe.ts](https://github.com/cmichaelgraham/skel-nav-esri4-vs-ts/blob/master/skel-nav-esri4-vs-ts/views/esri-globe.ts)

```javascript
import EMap = require("esri/Map");
import SceneView = require("esri/views/SceneView");
import ArcGISDynamicLayer = require("esri/layers/ArcGISDynamicLayer");
import domReady = require("dojo/domReady!");

export class EsriGlobe {
    map: EMap;
    view: SceneView;
    constructor() { }
    attached() {
        // Earth quake layer
        var poolPermitLyr = new ArcGISDynamicLayer({
            url: "https://sampleserver6.arcgisonline.com/arcgis/rest/services/PoolPermits/MapServer"
        });

        var eqLyr = new ArcGISDynamicLayer({
            url: "https://tmservices1.esri.com/arcgis/rest/services/LiveFeeds/Earthquakes/MapServer"
        });

        this.map = new EMap({
            basemap: "streets",
            layers: [eqLyr, poolPermitLyr]
        });

        this.view = new SceneView({
            container: "globe",
            map: this.map,
            scale: 50000000,
            center: [-101.17, 21.78]
        });
    }
}
```

here's a cool video of an oil and gas bubble map - we actually rotate off the flat map and look at 3d bubles below the map :smile:

https://www.youtube.com/watch?v=pRvJNUkQBFM

**Comment by ivogabe** [comment]
@cmichaelgraham Nice to see what you're building! One thing, when you drag the globe is somehow rotating, the north isn't on the top any more. Besides that, awesome
