### ISSUE TITLE
Can i write typescript with in <Script> tag?

### ISSUE THREAD

**Issue by zzz6519003** [microsoft/TypeScript#59614]
### 🔍 Search Terms

[Can i write typescript with in <Script> tag?](https://stackoverflow.com/questions/56106649/can-i-write-typescript-with-in-script-tag)

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

```
<!-- Some HTML -->
<script>
    Your Typescript
</script>
<!-- Some HTML -->
```

### 📃 Motivating Example

```
<!-- Some HTML -->
<script>
    Your Typescript
</script>
<!-- Some HTML -->
```

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by MartinJohns** [comment]
This repository tracker is meant for bug reports or feature requests. Questions like this are better suited for StackOverflow or the TypeScript Discord.

To my knowledge there is not a single browser that can execute TypeScript, so **no, you can't write TypeScript in `<script>` tags.**

You could load the TypeScript compiler in the browser and compile the TypeScript code on-the-fly, but that will be more pain than it's worth.

**Comment by zzz6519003** [comment]
How pain, this is a request, lol

**Comment by MartinJohns** [comment]
It's not clear whether this is a question or an actual feature request. Based on the title it looks like a question, and the issue template was not filled out correctly.

If you're requesting for TypeScript to be able to be run in the browser, then I can tell you that it's clearly out of scope for TypeScript.. and not really something the TypeScript team can do. It would require support by the browser vendors.

**Comment by tocque** [comment]
If you want to write TypeScript in HTML, you should turn to WHATWG, who establishes the HTML specifications, rather than asking in the TypeScript repository.

**Comment by zzz6519003** [comment]
Thx!
