### ISSUE TITLE
Conditionnal return type not recognized inside the function

### ISSUE THREAD

**Issue by Tristan-WorkGH** [microsoft/TypeScript#59618]
### 🔎 Search Terms

"not assignable",
"parametized argument",
"conditional return"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 5.1.6

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.1.6#code/JYOwLgpgTgZghgYwgAgJIBMLmDYcBGANigN7LDoBcyAzmFKAOYDcyIcAthAPzV0MgWyAL4BYAFASYAVxAIwwAPYhkHAJ4y5AHgAqGMMggAPSCHQ00mbLgLFkAHzbTChAHwAKUDEU1qe9GAAlH76hiZY5pZYCjZEKNy09EzI1CDOhMgkEsg55DDIniDeFgC8JU4ugZnZubVQEGDSUCppLsw1tTkA9F0AolBQfmoADigA5K2EY+QWIIoGcDQ0wIzscchgihsj4-4GxqaRGNE4eOsJ-Mmp6WMAdO4ATADMDw+BHSKGhDSkH3UNTRUXh8two7XEnVyPX6g2QOh2yDGl0E02As3myEWy1WthQm22o0RezChwsx2sZzsFySghSFSm92er3eENyYnE7IkxAMYA4w2Q5XUmgQ7kmgXBPRKrmQ3I2fOuLi5DTlwweAtUGlkIpI7C41DGYwANOQqIixsJxRJJdLZbzVXwaYwJEA

### 💻 Code

```ts
interface Identifiable { id: string; name?: string; }

function myfunc<TIdt extends Identifiable | null>(infos: TIdt): TIdt extends Identifiable ? string : null {
    if (infos == null) {
        return null;
        //Err: Type 'null' is not assignable to type 'TIdt extends Identifiable ? string : null'.(2322)
    } else {
        return infos.id;
        //Err: Type 'string' is not assignable to type 'TIdt extends Identifiable ? string : null'.(2322)
    }
}

let tmp = myfunc(null);
//=> let tmp: null
let tmp2 = myfunc({name: '', id: ''});
//=> let tmp2: string
```

### 🙁 Actual behavior

`tsc` doesn't seem to match the `if` statement with the conditional return.

On the other hand it understand what I want to say when calling the method.

### 🙂 Expected behavior

What I expect is for typescript to understand in the if that if the argument is `null` then I can only return `null`, and alse only return a `string`, like defined in the function signature.

### Additional information about the issue

I have the impression that the signature is correct as typescript infer correctly when calling the function, so the problem is inside the function with the `if`?

**Comment by MartinJohns** [comment]
Duplicate of #33912.

**Comment by muradkhan995** [comment]
**Solution**

You can resolve this by using type assertions or by separating the logic into distinct functions. Here's a solution using type assertions:

_typescript_

```
interface Identifiable { id: string; name?: string; }

function myfunc<TIdt extends Identifiable | null>(infos: TIdt): TIdt extends Identifiable ? string : null {
    if (infos == null) {
        return null as any;
    } else {
        return infos.id as any;
    }
}
```

_In the code above:_

    return null as any; tells TypeScript to treat null as the correct return type (TIdt extends Identifiable ? string : null).
    return infos.id as any; similarly tells TypeScript to treat infos.id as the correct return type.

**Explanation**

    as any works as a workaround to convince TypeScript to accept the return value. However, this can be less safe, as it bypasses some of TypeScript's type checks.

Alternatively, you can split the logic into two functions, which can be more type-safe:

**typescript**

```
function myfuncIdentifiable(infos: Identifiable): string {
    return infos.id;
}

function myfunc<TIdt extends Identifiable | null>(infos: TIdt): TIdt extends Identifiable ? string : null {
    if (infos == null) {
        return null as any;
    } else {
        return myfuncIdentifiable(infos as Identifiable) as any;
    }
}
```

_This way, the type logic is handled separately, and TypeScript is less likely to encounter problems with narrowing.
Summary_

    The root cause of this issue is TypeScript's inability to correctly narrow the conditional type within the function body.
    The workaround involves using type assertions to force TypeScript to accept the return type.
    Alternatively, splitting the function can make the type logic clearer and safer.

**Comment by MartinJohns** [comment]
Looks like a garbage ChatGPT response.

**Comment by Tristan-WorkGH** [comment]
Effectively a duplicate of #33912, will watch this one.

Will use [function overloading](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads) in the meantime.
