### ISSUE TITLE
add `generateTrace` to tsconfig's `compilerOptions`

### ISSUE THREAD

**Issue by dimitropoulos** [microsoft/TypeScript#59617]
### 🔍 Search Terms

generateTrace analyze-trace @typescript/analyze-trace

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Would a PR be accepted to add `generateTrace` ([the existing CLI option](https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options)) to the `tsconfig.json`'s `compilerOptions`?  [Similar to `generateCpuProfile`](https://www.typescriptlang.org/tsconfig/#generateCpuProfile) being in both the CLI and the config.

### 📃 Motivating Example

I am making a monorepo tool that will attempt to generate traces and leverage the [analyze-trace](https://github.com/microsoft/typescript-analyze-trace) tool to give users information about hotspots in their monorepo.  Adding this to the tsconfig makes what this tool is trying to do a lot easier: monorepos may have hundreds of `"typecheck": "tsc"` package.json scripts, and it may not be feasible or desirable to modify them all.

### 💻 Use Cases

1. What do you want to use this for?
metaprogramming for monorepo library diagnositcs

2. What shortcomings exist with current approaches?
Adding the CLI flag requires more complexity to support different package managers (yarn, pnpm, npm, etc.), whereas if a compilerOption existed, it'd be easier.

3. What workarounds are you using in the meantime?
In a repo I'm working with that has 500+ packages, I'm using find-and-replace to modify the `typecheck` commands in each package.

**Comment by RyanCavanaugh** [comment]
@sheetalkamat any concerns if we do this? Seems fine to me

**Comment by dimitropoulos** [comment]
@RyanCavanaugh @sheetalkamat hopefully it's not tooo presumptuous but I suddenly realized how quickly the 5.6 release is approaching (wow!) and given how small this change is I'm really hoping there's a way to fit it in while it's still Beta season: https://github.com/microsoft/TypeScript/pull/59636
