### ISSUE TITLE
JSON.stringify can return undefined

### ISSUE THREAD

**Issue by farnoy** [microsoft/TypeScript#59616]
### ⚙ Compilation target

ES2018

### ⚙ Library

es2018

### Missing / Incorrect Definition

JSON.stringify always returns string https://github.com/microsoft/TypeScript/blob/01a874a8baf6a5fc0c9b47d3902221311671b01c/src/lib/es5.d.ts#L1151

But `JSON.stringify(undefined)` returns undefined

### Sample Code

```TypeScript
const whatever: string | undefined = `JSON.stringify(undefined)`;
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#return_value

**Comment by jcalz** [comment]
Duplicate #18879

See https://github.com/microsoft/TypeScript/issues/18879#issuecomment-1399758565
