### ISSUE TITLE
Provide a way to omit first generic parameter when it can be inferred

### ISSUE THREAD

**Issue by fwolff** [microsoft/TypeScript#59629]
### 🔍 Search Terms

generic parameters, type inference

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When a type is created with two or more generic parameters (eg. `type Context<T, P = any>`), the first parameter can be inferred only if the second one isn't provided explicitly (see example).

### 📃 Motivating Example

In this example, Test3 doesn't compile, the first parameter cannot be inferred and must be duplicated if the second one is provided:

```
type Context<T, P = any> = {
    value: T
    parent: P
}

type DecoratorProps<T, P = any> = {
    callback: (context: Context<T, P>) => void
}

function decor<T>(callback: (context: Context<T>) => void) {
    return function _(_: any, context: ClassFieldDecoratorContext<unknown, T>) {
        const metadata = context.metadata! as Record<PropertyKey, DecoratorProps<T>>
        metadata[context.name] = { callback }
    }
}

class Test {
    @decor((context) => {}) // (parameter) context: Context<string | null, any>. T is correctly inferred
    name: string | null = null
}

class Test2 {
    @decor((context: Context<string | null, Test>) => {}) // (parameter) context: Context<string | null, Test>, T signature must be duplicated
    name: string | null = null
}

class Test3 {
    @decor((context: Context<, Test>) => {}) // Doesn't compile: Type expected. 
    name: string | null = null
}
```

See playground [here](https://www.typescriptlang.org/play/?ts=5.5.4#code/C4TwDgpgBAwg9gO2BAHsAPAFQDRQApQC8UAhgiAHxFQDeAUFI1AG4kA2ArhAFxSYNMwJAE4QkvPHQC+dOqEhQAIhADGcYSWDq8wuGADOWXAWJlK1ekygr2bAEYkVAa14AKNUlTBe8T2iP4FACURFTMcACWACbSsgBmHAgqwBGIUFGq6lgU7rYOzm4eyGg+iMUYmMGhLJFRIZZMosAcwghQCUkpaQD6rt28ZrhFXj5sJPr6AGIREGxRymoaWsK+5eiJTghwAO4IuJX1AlaMHvrAUAC2EMAkUZok1MNoAHRXN3c3AISk+lAASplhFF0Do9BBhKAANIQEC4BbqTTaXQGbIUI7HN63e4AbSewGeCBIVwAuhZrHlHE4oDIrDIZHQVGMJnwIGdaOiAAIZRaudxlLwhQhUGhSEIAejFUFcQg0b3BITxpT8GDOwgiCAA5lAAD5QBAcNhsXBmCjPPhQCK-RaiZJsEAWhBxcGiGJWQlXXiq9Va3X6w3UP1sWIMpm-TCs4AAJnZVi5gN5itg-P8Xs1Or1BqNLLOVSFtFFUAlUplROu8usye8SeV6FTPozhv2EYo+yg+giGsJzVElw4bLs0CiHDAbAiNmQrqY7p4beAarTvszAczwcZ4zDEYAzDGmHGeXzlUq1k2c4LhQWi4o4KyEAByc5qC5gCJsGeYcDQVCQZIQKJm9HTp6c7eumgbLoawZ0EAA).

### 💻 Use Cases

1. What do you want to use this for? avoid duplicating types that could be inferred
2. What shortcomings exist with current approaches? the syntax `Context<, Test>` is only a possible option, another way to express this type omission would be fine.
3. What workarounds are you using in the meantime? provide the first parameter like in `Test2`

**Comment by MartinJohns** [comment]
Duplicate of #26242.

**Comment by fwolff** [comment]
Ok, thanks for your answer, sorry for the bother!
