### ISSUE TITLE
Error when using "Legacy" external modules + SystemJS

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#5963]
Hi, I get the following error:
```
error TS1218: Export assignment is not supported when '--module' flag is 'system'.
```
When I try to compile an external module (not ES6 module):

```
export = arrays;
// and
import arrays = require("./arrays.ts");
```
I'm using TypeScript `1.8.0-dev.20151204` and a class like the following:
```
class Arrays {

  // ...

}

var arrays = new Arrays();
export = arrays;
```

Is it possible to compile using `--module`  `system` and "legacy" external modules?

**Comment by mhegazy** [comment]
No. SystemJS does not have a parallel to `export =` like in other module loaders e.g. commonJs and AMD. 

use `export default arrays` instead.

**Comment by remojansen** [comment]
@mhegazy thanks for the answer, can I use?

    import arrays = require("./arrays.ts")

If I use `export =` ?

**Comment by mhegazy** [comment]
You can use `import arrays = require("./arrays")` which will be equivalent to import * as arrays from "./arrays";` but you can not use `export=`.

**Comment by wejsi** [comment]
PT-BR -- Configure o seu tsconfig.json desta maneira.

{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "typings"
  ]
}
