### ISSUE TITLE
Un-initialized class fields are omitted from the emitted JS, compared to the field counterparts in JS

### ISSUE THREAD

**Issue by loucadufault** [microsoft/TypeScript#59632]
### 🔎 Search Terms

field, initializer, uninitialized, class, getOwnPropertyDescriptor

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about class fields

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.4#code/MYGwhgzhAEAKD2BLAdgF2gbwFDWgDwC5pkBXAWwCMBTAJ2gB9oTkATKgMxSpYG4doAnkVKVaDJqw5deWAL5YsweMgjoADtAC8xKgHc4SNAAoAlAqUr4IKgDoQ8AOZGA8hQBWVYKhsOqqZ7rIsDTwarSoAgAiVBDANIhqqPA0RmoANNAA5HiZJmZAA

### 💻 Code

```ts
class Point {
  x: number | undefined;
  y: number | undefined;
}

const p = new Point()

console.log(Object.getOwnPropertyDescriptor(p, 'x'))
```

### 🙁 Actual behavior

The output of `Object.getOwnPropertyDescriptor(p, 'x')` is undefined. This is because the property is completely omitted from the emitted JS:

```js
class Point {
}
```

### 🙂 Expected behavior

One would expect the class to be emitted as the below, valid JS which is analogous:

```js
class Point {
  x
  y
}
```

Where the output of `Object.getOwnPropertyDescriptor(p, 'x')` would be the present descriptor.

### Additional information about the issue

This is disruptive for example when unit testing with jest, where a test case like the below is invalid:

```ts
it('mocks a property on the class', () => {
  const p = new Point()
  jest.replaceProperty(p, 'x', 25);
  // ^ fails the test with 'Property `x` does not exist in the provided object'
  // see https://github.com/jestjs/jest/blob/0d96de975783ee78192c1037862ea3089f52dc25/packages/jest-mock/src/index.ts#L1302
})
```

A workaround is to add initializers:

```ts
class Point {
  x: number | undefined = undefined;
  y: number | undefined = undefined;
}
```

In which case the properties are correctly set in the emitted JS.

---

Marked this as a bug, since an unsuspecting developer migrating code from JS to TS like the following:

```js
class Point {
  x
  y
}
```

would be introducing functional changes to their program by virtue of renaming the file to `.ts`, despite the identical syntax, which could be a source of bugs.

**Comment by MartinJohns** [comment]
This is working as intended. You either need to target ES2022 or later, or turn `useDefineForClassFields` on.

**Comment by loucadufault** [comment]
> You either need to target ES2022 or later

Can you share an example? Try it in the playground link shared above and there was no difference.

**Comment by MartinJohns** [comment]
> Try it in the playground link shared above and there was no difference.

The default value for `useDefineForClassFields` depends on the `target`. When the `target` is set to ES2022 or later, then the default is `true`. However, the playground does not support default values for compiler options, and in your playground link `useDefineForClassFields` is set to `false`.
