### ISSUE TITLE
ts `Move to a new file` doesn't respect `importModuleSpecifier` setting

### ISSUE THREAD

**Issue by tjx666** [microsoft/TypeScript#59649]
@mjbvz @justschen 

reproduce repo: https://github.com/tjx666/ts-none-relative-reproduce

a little like https://github.com/microsoft/vscode/issues/160304.

setting:

```json
{
    "typescript.tsdk": "node_modules/typescript/lib",
    "javascript.preferences.importModuleSpecifier": "non-relative",
    "typescript.preferences.importModuleSpecifier": "non-relative"
}
```

## problem

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/4ca64d5f-cfe6-4d82-92b9-523fffcb34b9">

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/2c74af30-8e86-435c-b3c4-827e1cb9af9c">

## expect

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/733cc8ba-9e84-492e-957e-583860e90603">

## screen recoding

https://github.com/user-attachments/assets/a9f5592b-85fc-4276-a67c-f971737ad668

## versions

```
"typescript": "^5.5.4"
Version: 1.92.1 (Universal)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by DanielRosenwasser** [comment]
Thanks @a-tarasyuk!

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-5.6

**Comment by dgreensp** [comment]
Does this also fix the refactoring changes made when you move a file to a different folder in the explorer?
