### ISSUE TITLE
Function type expression won't infer the rest parameter type correctly

### ISSUE THREAD

**Issue by jasomimo** [microsoft/TypeScript#59640]
### 🔎 Search Terms

infer rest parameter type,

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.4#code/MYewdgzgLgBAZgVzMAjALhgCgA4CcCWAtgIa4CeGYChARgKa4A0MAdG8QCYf5T7jEAbStXq4A2gF0AlDAC8APhhVaDOVjxFSZZp269+AmQpgBvAFAxLMXTz5hBLJBAAW+OFBwES5KQG4rAPQBMAAqAMowAKK4uCC4GAAKsdgMUGQwAOROru4ZMBwgdBBKILB0AB740DDgMGkpmcqiGSwWVrh0UAi4YDAovmYAvgNmiMj6vWPAAEyemuTCKkys7Fy2BouiklKbquZW1msTDtluHhreZH5tlh1dPX0Dw2ZmoJCwUwDManOXu8tsFg2Y5CJQiBjbf5yRT7KzAuwnSA5c5eLTXA53bq9fpDAZAA

### 💻 Code

```ts
const func1: (primary: number, ...additional: number[]) => number = (primary, additional) => {
    additional.unshift(primary);   // TS Error: Property 'unshift' does not exist on type 'number'.
    return 1;
};

function func2(primary: number, ...additional: number[]): number {
    additional.unshift(primary);
    return 1;
};

const func3 = (primary: number, ...additional: number[]): number => {
    additional.unshift(primary);
    return 1;
};
```

### 🙁 Actual behavior

Parameter `additional` in `func1` is inferred as `number` and hence TS reports an error: `Property 'unshift' does not exist on type 'number'.`

### 🙂 Expected behavior

Parameter `additional` in `func1` should be inferred as `number[]`. The behavior between `func1`, `func2` and `func3` should be consistent.

**Comment by snarbies** [comment]
Your type annotation has a rest parameter, `(primary: number, ...additional: number[]) => number`, but your implementation does not, `(primary, additional) =>`. 

Since the invocation won't pack the arguments into an array, I would say this is the correct inference.

**Comment by jasomimo** [comment]
Oh, my bad, you are right.
