### ISSUE TITLE
Inheriting from 21 combined mixins causes "type instantiation is excessively deep and possibly infinite"

### ISSUE THREAD

**Issue by boconnell** [microsoft/TypeScript#59659]
### 🔎 Search Terms

Mixin mixins 20 21 type instantiation is excessively deep and possibly infinite

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/IYIwzgLgTsDGEAJYBthjAgQmgpgeRACsEBvAKAUqQHsA7SKAV3mqgAoA6L4KAczABcCYLQCeAbQC6ASlIBfMgrIUEAM0a14ASzoIAKjC0QADADEAPHuxgcCHAA8IOWgBMMEUQAcc1VVlwEhAB8bNY4Qla40uRUwuDQcIgoaBgGwEbGdo7Obv428iqUUDgQjFC0+oYmKkoq6poQOhVpRgCMFpH5Dk6u7l4+fmGBIWERYdGFcQyJSKjolekQrVk9uWEFscWl5QttNcp1Gtq6LRAATB3r3Tl93r55+EQjuGNRMVSg0-CzKbvnKzcHhsqFsys0qmd9spKPVjuDFgBmS64AG9BAeO6DAJPUIvfTjd6UT4Jb7JeanBGotYokgKTYlMF-BFQw4NJp-AAsyK62TRGIGD2GuJsrxsE1ixJgpLmqSqHKpGHWtMmoJ2pw5LJhR0aJyqAFZubZrnz+vchjjRvi3pNJTMybLFnqFUDlfTtvCjHrNWptezTgA2Q3O-lm7HBYXhK1iwlTElJGV-f3OpV0kEMtVVf3e2E6j0QADsQeNuRDWJsQstnRw4o+8Sl8d+p3zyZpqaK6bz+ezvt1iwAHEXeSXTWXHuHKwSbXW7QnTn2W-lXWn3X8+922b2jABOQerW4C83jvFVmtE6fSxtVLcL2xL9sr05b9dwv6tMyWK5D-eh8sW4+TiVzwbckqjfG9gXvRlTjfZ9c1fdoPxRYtv1HCt-2tQCvmAh02mWZCXTbBBVTzVpWlgv1QIuRCeT3dER0FP8RSjasY1tC8QMWVoznAu8iI7V9IUoWotQ3EikWoo0vzozEGKPJiT1YoCfg4tpKXwlMVX46DmSEg4RJfaCuQk4N6MPZ55IA2ssOUnClnldTW00h9QI1XToR9UTXwNYz8NLWTzMjBSp2s+0vJ4wjiK88jNyWQMfKkvyzIjUUWOCuMbNfJMHMXCKtNArM3NZAzQMLeLaMSsMApS09Y3rDLoObbLb1y5zOK7Qr9Lg6CBzKwEKt-OTAsss8QtnUD5yaiC+Nato1w6jzis4ndepNGSkonDCrPS0LoOvSbeMi3borzM53yrEy1sq5LmJqtjsL+U7wqcqCIWMY6HoQ87fNMq6NujNK6p2iE8KkjS3RexYzjItzYDoSAEAAYToWAthwdYAF4PtMNhTlO7Hdvx8bCba4m2kDHHQINCnOK5anVNJpYLjppZ2mZt8GZ3ZmB2ZwtmfJ04qfVBmkWZpnoIZswI0CaQZdluX5YV6QAG5lFCpHNFRhGAAstGQFxnXVlGSjR1sgA

### 💻 Code

```ts
abstract class BaseObj {
    constructor(...args: any[]) {}
}


  function Trait0F<TBase extends typeof BaseObj>(Base: TBase){
    abstract class Trait0 extends Base {}
    return Trait0
  }


  function Trait1F<TBase extends typeof BaseObj>(Base: TBase){
    abstract class Trait1 extends Base {}
    return Trait1
  }

// ...


  function Trait21F<TBase extends typeof BaseObj>(Base: TBase){
    abstract class Trait21 extends Base {}
    return Trait21
  }

const ConcreteBase = Trait21F(Trait20F(Trait19F(Trait18F(Trait17F(Trait16F(Trait15F(Trait14F(Trait13F(Trait12F(Trait11F(Trait10F(Trait9F(Trait8F(Trait7F(Trait6F(Trait5F(Trait4F(Trait3F(Trait2F(Trait1F(Trait0F(BaseObj)))))))))))))))))))))); // excessively deep

class ConcreteChild extends ConcreteBase {}
```

### 🙁 Actual behavior

The line with `Trait21F(...)` where we assign to `ConcreteBase` throws the "type instantiation is excessively deep" error. The error goes away if there is at most 20 mixins (e.g. the last one is `Trait19F`), so any number more than 20 seems to be the problem.

It's worth noting that if for every trait we had a static class e.g. `class Trait0 extends Trait0F(BaseObj)` and then intersected them all together, e.g. `const ConcreteBase = typeof Trait21 & ... & typeof Trait0 & typeof BaseObj` that everything works ([TS playground](https://www.typescriptlang.org/play/?#code/IYIwzgLgTsDGEAJYBthjAgQmgpgeRACsEBvAKAUqQHsA7SKAV3mqgAoA6L4KAczABcCYLQCeAbQC6ASlIBfMgrIo0GACowAlhAAMCHAA8IOWgBMM2MPiLyyy1OgQbg2gIz6jJ81lwFiJJRVHZ20AJg9jMwtfGwC7IPUtCABmCK9oqz9be1UnJIAWNKifTNjAh0SXCABWIu9La39y3JCIADY6jMbshLyqgHZOku64nOCkgA4hhqzR3taATmmYpviKvrc9Q0j6lZ711td3bfTh2ebxqtdwk+KZsrWWpNdU293S1bHKt0K3rvPHpc3LU-mcHl8NhBXB1QfdPvNnoNYXs5gdnlNkR99k8rktMSMLt8IKEtp47ijCZDQscye8CXZTDgVFAcDR6IgAMJ0WAs4wNIQQUQABxw1AAZmDiAAyBCCkXiyF6GVy0USw4IZXC1VUjWyrUK1qpTXytUFXUqg1JWrG7WtDo2y0Dc3601VKYO13aJYeyGuJV6k2+9w+w7hEPPI0B23PQrhq7WqOOtz2xOeqGDONud2p33enOtEnOwMF1yAjBc2g8nDGDkAC00yFMQwrVb5uHkQA)), which feels like it should be functionally equivalent.

Expressing this the manual way, by having the equivalent trait classes extend each other statically (`class Trait1 extends Trait0` etc...), also works: [TS Playground](https://www.typescriptlang.org/play/?#code/IYIwzgLgTsDGEAJYBthjAgQmgpgeRACsEBvAKAUqQHsA7SKAV3mqgAoA6L4KAczABcCYLQCeAbQC6ASlIBfMgrIo0GACowAlhAAMCHAA8IOWgBMM2MPiLyyy1OgQbg2gIz6jJ80627b91R8XCAAmD2MzdV93EiUVR2dtAGZwryjgsNi7ePTtABZUyKDk-xziiABWQu9EiAKsgITfADZq3MrSh3aAdjby1oay2oAOPtrewa7ygE4x31HJwNrXPUMImt9Zxabg13c1tPKVzqXosIOi5Zi4qeWUi43dzJvT3YKH9tcU7c+qj6P6i8dm5Wv9llUfkdemDogMgZ9RjDdhN4UdZki3AtUbUQqtPJdoltsb4Qvt8Y9tLjSnRIAgAMJ0WBQHDGSw4BAAXnKpIA3NkpgzaEyWTg6QALTTIUx9QXC1m4eRAA)

### 🙂 Expected behavior

I would expect this to not error. This recursion isn't infinite and doesn't seem like it would exceed the depth limit of 100 currently hard-coded into the compiler, and in general the 2 alternatives which work should be equivalent.

### Additional information about the issue

Related:
https://github.com/microsoft/TypeScript/issues/34933
https://github.com/microsoft/TypeScript/issues/54533

**Comment by boconnell** [comment]
OK checked more versions and this is technically a regression from version 3.51.

**Comment by RyanCavanaugh** [comment]
> I would expect this to not error. This recursion isn't infinite

The error message says "excessively deep" and, yeah, a 20-deep function call qualifies as "too deep" for the purposes of not crashing/hanging in other codebases. You'll need to use a workaround.

**Comment by boconnell** [comment]
This is not strictly about function depth though. If you annotate the functions with return types or make the return type inference more straightforward, the error goes away: [TS playground](https://www.typescriptlang.org/play/?#code/IYIwzgLgTsDGEAJYBthjAgQmgpgeRACsEBvAKAUqQHsA7SKAV3mqgAoA6L4KAczABcCYLQCeAbQC6ASlIBfMgrIUEAM0a14ASzoIAKjC0QADADEAPHuxgcCHAA8IOWgBMMEUQAcc1VVlwEhAB8bNY4Qla40hFhCABk8qQqlKAMcIgoaBgGwEbG8skIUDgQjFC0iWgIHt6++oYm8fphKkoq6poQOhU5RgCMFpE2do7ObtVePn5hgSFhMVELwwkkcklUwuDQ6Uio6PW5EH0FG8Wl5ZXuk3W9R01DOK3K7RraurcATIOxDk6uV7VpgEiHNcEscNFmrgmqt1lRUtt4LssgcjB8TlQzmUKrCqjUpqiIOiEg8nspKB03j0GgBmb7Q35jAEEmYg0JgqE2SEPGFrcgbBEwJGZfa3GkYyhYi645k3Wn3FqUNoU15dd4NAAs9OGjP+E0B-hss3ZNnB3NiKz5hUFOxF2U1EqKJWxl31BNuGoVuDJL063UJAFZtbZdeN8XVWcETeFORDwby4SktkKMnt7YcA46pTi1njrn5bpmSYqEMq1Kr-bcAGzBkZ-MP5w34NnzWPm6GWxObNLCtOEqtZ53S3OygsNAfF71K54qv3qw4AdlrodHTeNrYe7eWiX58OTtr7twXg-OOeEq6PXpsPtnVMJAA5l6M9eGgUaWxzN-HO7ukz3Uyitz3ieLoym6cqHMBk7XtO5LlnO1KHAAnE+9arpGoKmm2347ta+69oBDRISBw7nuBY7IVejywb6d63H0ZiWD8z4NgaGHRmaOGwr+3aIgBooNAxJFnnmBr0fk0HUaWM7wXRgkDExDIsehwJRhuYRbrYP54f+yICYcfTHKshTZq6r6EoZVE3rJaqIf0XyKTqynkWuH5YV+sYJjxNoEfp9nCWZjb0cSsbWZStkWXSjkhs55nsepiyedpAr4fx6b9OKxmnEOIkXoJ4qSWFFbzv0WrRXWTIufFn4aVxVopbpdoWZ6WWYjlgViYJnqFTRt4RfRQblSuVWqZhMYeTyyV7o1h6CZmrWSu1YHmQNVm9TZlaCTWQ2xY21XubVSW4Q1fF6elRwDgtTqnh17pbWt0lweFm0GUuO1oSN75qTViWTcd02nU19HHldpnLUFgnHj1j20f1gmPu9lVxaNHHYUd3E6YDs0GcBoNLSOLn0VBoXrc9JVHChiMvntKMJVydVdj5aUWcReM3eDnUGcR0NlmTdlEoxPLDcjX1jZx6P1QDKZnYSHz5GzoEEytDRyw9vPFfzHwKULu1sbTP30xLjOpTLnxGQo2Xs0rEOHFravKLAdCQAgADCdCwGcOCxAAvLLAxsJ8ZgB4JKHBzjphh-0S6RxdEcDXHXUJwZdIx30Xyp-74lJ0YodAdnEDR9W+dBjHWoxynnz55nDRB5G0j1w3jdN830gANwO32buaJ7LsABZaMgLgVXqXceyUXvQqsQA).

As I mentioned before, this basically flattens out to static class extension, which is also fine.

This feels firmly like something to do with the mixin code path, as the problem does not apply more generally. Isn't that inconsistent worth considering a bug?

**Comment by avetisk** [comment]
@RyanCavanaugh is there a way to locally increase the max depth?

Because sometimes with complex concepts, we really need a lot of depth.
