### ISSUE TITLE
How to publish a project as library with external module dependencies

### ISSUE THREAD

**Issue by joesonw** [Microsoft/TypeScript#5965]
I started with normal ts files, and simply export them directly. but it cannot generate declaration file. I read some source code from several open source projects, but they were using rather complicate build scripts or non external dependencies.

So, If I want to build my project into a library (a .js file and a .d.ts declaration file). How am I suppose to do that if I cannot use external modules in internal modules.

dts-generator does not work very well. I want keep the file structure hierarchy  (aka namespaces) in the final single declaration file.

**Comment by mhegazy** [comment]
Can you elaborate on what is the shape of your library? what is the shape of your dependencies? and how are you distributing your library?

**Comment by joesonw** [comment]
@mhegazy 

say I have `src/App.ts` , `src/entity/Request.ts`, `src/entity/Response.ts`. an example dependency would `node.d.ts`, I need to use `http.Server` from `http`. When i only reference the definition, the compiler goes `Cannot find namespace 'http' `. I have to add a line to it ` import http = require('http')` . But this breaks the internal module I referenced (Request and Response), this two will be undefined.

**Comment by mhegazy** [comment]
is this a nodeJS application?

**Comment by joesonw** [comment]
@mhegazy yes

**Comment by mhegazy** [comment]
then every file is a module already, you should be importing `request` and `response` and there should not be any internal module references.. what am i missing?

**Comment by joesonw** [comment]
I'm trying to keep the namespaces while exporting the declaration.
like
```
/// <reference path="mylib.d.ts"/>

import mylib = require('mylib');

var A:mylib.A;
var aB:mylib.a.B;
```

**Comment by mhegazy** [comment]
who is building `mylib.d.ts`? are you using --out to build it? what is the point of using both namespaces and modules? modules give you isolation and modularity already, and since this is a node app, you have a built-in loader, so what is the point of adding namespaces into the mix? 

I would recommend you take a look at this page in the handbook: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md#do-not-use-namespaces-in-modules

**Comment by joesonw** [comment]
But in the generated declaration file, all exported members are under one "namespace". So I can only do `My.AddForm` rather than `My.Application.Customer.AddForm`

**Comment by mhegazy** [comment]
but each module has a name already, and you need to import it by name first, so i would say there is nothing much lost here in terms of modularity.

**Comment by joesonw** [comment]
I was saying if it's published as node_modules. it would be tricky to keep the namespace/file structure. I'm trying with `export namespace` with some build scripts, hope it wont be too complex.
