### ISSUE TITLE
`void` is treated as covariant with everything when overriding a method from a base class

### ISSUE THREAD

**Issue by Thorn1089** [microsoft/TypeScript#59660]
### 🔎 Search Terms

void override method, void covariance

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about [_________](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240816#code/IYIwzgLgTsDGEAJYBthjAgYge2wg3gFAIIAOAriMgJawKiQzwIAm2O2AFAJQBcCIXMgCmwAHYBuYmUo06DaHERsAQsCg9+AN2zUWUgL6FCKNBjVQEwgB4RhYlhg4FpFKrQTYtwqFD3DWdlxNBEZqMQBzFxISKGEIcigxBAByADNcFKkSI1dZDy8fPxYA1XUQsMjomLiEpNSQdSzpXJI3OUCANV0WEJ09atj4xOSU-pZmnMJc2GwxSARwyHFYAIBeBDFhAHcECx4pJYgV4QA6Ng4DwiOT8+x97gkgA

### 💻 Code

```ts
abstract class Foo {
  public abstract doFoo(): boolean;
  public abstract doBar(): void;
}

class Bar extends Foo {
  public override doFoo(): string {
    return 'foo';
  }

  public override doBar(): string {
    return 'bar';
  }

  public doVoid(): void {
    return 'void';
  }
}
```

### 🙁 Actual behavior

The derived class `Bar` is allowed to supply a non-void returning method for the override `doBar`. I see the FAQ entry about void substitutability for _callbacks_ but this behavior is unexpected and undesirable when implementing methods from a base class - all types should _not_ be treated as covariant with `void`.

### 🙂 Expected behavior

 For example, this problem manifested in production code when an engineer supplied an `async` method returning `Promise<void>` instead of a sync method returning `void`, which I expected would have failed to compile.

### Additional information about the issue

I have read the FAQ entry here (https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void) but believe it should not apply in the case of class method overriding (versus functions as callback arguments, where this behavior is indeed desirable).

**Comment by RyanCavanaugh** [comment]
This is still correct, and for the same reason.

You might be confusing `void` with `undefined`?
