### ISSUE TITLE
typescript@1.7.3 doesn't have newLine compiler option

### ISSUE THREAD

**Issue by yoav-zibin** [Microsoft/TypeScript#5968]
The newLine option is documented here:
https://github.com/Microsoft/TypeScript/wiki/Compiler-Options

--newLine		Use the specified end of line sequence to be used when emitting files: 'CRLF' (dos) or 'LF' (unix)."

I have this line in my tsconfig.json:
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": false,
        "removeComments": false,
        "rootDir": ".",
        "outDir": "ts_output_readonly_do_NOT_change_manually/",
        "sourceMap": false,
        "noLib": false,
        "newLine": "CRLF"
    },

But when I run tsc it complains about Unknown compiler option 'newLine' 

yzibin-macbookpro2:multiplayer-games-web yzibin$ npm install typescript --save-dev
typescript@1.7.3 node_modules/typescript
yzibin-macbookpro2:multiplayer-games-web yzibin$ tsc
error TS5023: Unknown compiler option 'newLine'.
yzibin-macbookpro2:multiplayer-games-web yzibin$ tsc --newLine CRLF
error TS5023: Unknown compiler option 'newline'.
yzibin-macbookpro2:multiplayer-games-web yzibin$ tsc --version
message TS6029: Version 1.5.0-beta

**Comment by yoav-zibin** [comment]
Ok, it was a version issue :)

I got confused between typescript and tsc.

And I had different versions of tsc installed (locally and globally):
yzibin-macbookpro2:multiplayer-games-web yzibin$ ./node_modules/tsc/bin/tsc -version
message TS6029: Version 1.5.3
yzibin-macbookpro2:multiplayer-games-web yzibin$ tsc -version
message TS6029: Version 1.5.0-beta

I did 
sudo npm install tsc -g
which solved the problem !

**Comment by blakeembrey** [comment]
@yoav-zibin `tsc` isn't the right package either (it's https://www.npmjs.com/package/tsc), it should probably have been `npm install -g typescript`.

**Comment by yoav-zibin** [comment]
Thanks! Now I finally have the correct version:
yzibin-macbookpro2:multiplayer-games-web yzibin$ tsc --version
message TS6029: Version 1.7.3

It's interesting the other project (tsc) got formed in order to give stable APIs. 
It's pretty far behind: message TS6029: Version 1.5.3
I guess in the past you made incompatible changes a lot.
Thanks again :)
