### ISSUE TITLE
Intellisense doesn't show type info about array index access on hover

### ISSUE THREAD

**Issue by lionel-rowe** [microsoft/TypeScript#59696]
### 🔍 Search Terms

intellisense, array, array index access, array square bracket access, hover

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Array index access, e.g. `arr[0]`, to show type info when hovering over the index.

### 📃 Motivating Example

```ts
const arr = [0, 1]

arr[0] // 💥 no hover. Expected "(property) 0: number" or "(property) 0?: number | undefined" with `noUncheckedIndexedAccess`
arr['1'] // 💥 no hover. Expected "(property) 1: number" or "(property) 1?: number | undefined" with `noUncheckedIndexedAccess`
arr['0'] // 💥 no hover. Expected "(property) 0: number" or "(property) 0?: number | undefined" with `noUncheckedIndexedAccess`
arr[1] // 💥 no hover. Expected "(property) 1: number" or "(property) 1?: number | undefined" with `noUncheckedIndexedAccess`
arr[2] // 💥 no hover. Expected "(property) 2: number" or "(property) 2?: number | undefined" with `noUncheckedIndexedAccess`

// for comparison
const obj = { 0: 0, '1': 1, key: 2 }
const tuple = [0, 1] as const
const extendedArr = Object.assign([0, 1] , { key: 2 })

obj.key // ✅ ok
obj['key'] // ✅ ok
obj[0] // ✅ ok
obj['1'] // ✅ ok
obj['0'] // ✅ ok
obj[1] // ✅ ok

tuple[0] // ✅ ok
tuple['1'] // ✅ ok
tuple['0'] // ✅ ok
tuple[1] // ✅ ok
tuple[2] // ✅ ok (fails type check as expected)

extendedArr.key // ✅ ok
extendedArr['key'] // ✅ ok
extendedArr[0] // 💥 no hover
extendedArr['1'] // 💥 no hover
extendedArr['0'] // 💥 no hover
extendedArr[1] // 💥 no hover
```

### 💻 Use Cases

1. What do you want to use this for?
    - DX/quality of life improvement
2. What shortcomings exist with current approaches?
    - Less good DX
3. What workarounds are you using in the meantime?
    - N/A

**Comment by jcalz** [comment]
Looks like #58908
