### ISSUE TITLE
Document `maxNodeModuleJsDepth` behavior

### ISSUE THREAD

**Issue by louwers** [microsoft/TypeScript#59699]
### Demo Repo

https://github.com/louwers/ts-potential-bug

### Which of the following problems are you reporting?

The module specifier resolves at runtime, but not at build time

### Demonstrate the defect described above with a code sample.

```
npx tsc -p scripts/jsconfig.json
```

Results in type errors

```
Found 9 errors in the same file, starting at: node_modules/csscolorparser/csscolorparser.js:101
```

Despite the fact that there is a `.d.ts` file which declares

```
declare module "csscolorparser";
```

So the implementation of the module should be ignored.

### Run `tsc --showConfig` and paste its output here

```
{
    "compilerOptions": {
        "allowJs": true,
        "maxNodeModuleJsDepth": 2,
        "allowSyntheticDefaultImports": true,
        "skipLibCheck": true,
        "noEmit": true,
        "strict": true,
        "checkJs": true,
        "module": "nodenext",
        "resolveJsonModule": true,
        "target": "esnext",
        "moduleResolution": "nodenext",
        "moduleDetection": "force",
        "esModuleInterop": true,
        "useDefineForClassFields": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictBindCallApply": true,
        "strictPropertyInitialization": true,
        "alwaysStrict": true,
        "useUnknownInCatchVariables": true
    },
    "files": [
        "./myscript.mjs",
        "./csscolorparser.d.ts"
    ],
    "include": [
        "./**/*.mjs",
        "**/*.d.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

### Run `tsc --traceResolution` and paste its output here

https://gist.github.com/louwers/46daae56f4af8c9df665763451afb342

### Paste the `package.json` of the *importing* module, if it exists

```
{
  "name": "typescript-bug",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "csscolorparser": "^1.0.3",
    "typescript": "^5.5.4"
  }
}
```

### Paste the `package.json` of the *target* module, if it exists

```
{
  "name": "csscolorparser",
  "version": "1.0.3",
  "author": "Dean McNamee <dean@gmail.com>",
  "keywords": ["css", "color", "html5", "parser"],
  "repository": {
    "type": "git",
    "url": "https://github.com/deanm/css-color-parser-js"
  },
  "license": "MIT",
  "main": "csscolorparser.js"
}
```

### Any other comments can go here

VS Code navigates to the .d.ts file when I control click on the import.

Adding

```
/// <reference path="csscolorparser.d.ts" /> 
```

At the top of the importing file does not resolve the issue.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior -- module resolution occurs before processing of ambient module declarations.

You can configure this to get the desired behavior by adding
```
    "maxNodeModuleJsDepth": 0
```
to your jsconfig

**Comment by louwers** [comment]
@RyanCavanaugh According to the documentation, 0 should be the default? https://www.typescriptlang.org/tsconfig/#maxNodeModuleJsDepth

**Comment by louwers** [comment]
Opened an issue here:

- https://github.com/microsoft/TypeScript-Website/pull/3208

**Comment by RyanCavanaugh** [comment]
The setting's default value is 0 in tsconfig, but 3 (I think?) in jsconfig

**Comment by louwers** [comment]
@RyanCavanaugh Oh there are different defaults?

**Comment by RyanCavanaugh** [comment]
Right, for example `allowJs` is on by default

**Comment by louwers** [comment]
@RyanCavanaugh I thought it was only `allowJs`...

**Comment by louwers** [comment]
Thanks for clarifying!
