### ISSUE TITLE
Object.keys doesn't return correct type

### ISSUE THREAD

**Issue by duke79** [microsoft/TypeScript#59706]
### 🔎 Search Terms

object.keys type, object.keys keyof typeof

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAtgTwPICMBWMC8MDeAoGGAawFMEBGALhgHIA3AQwBsBXE8mgGgOLICZq9Zmz408AXwDcePKEixSCCFhio0JYFAB0iiAApEagJTS8AejO8lMAJbKQAMxhQEABxIxoAJxtgA5gDaALrmligssL7QJAwAJp4AFiAsTPEoHnqKjs5uJNmG6EbBQA

### 💻 Code

```ts
const myObj = {
  key1: 'value1',
  key2: 'value2'
};

const keys = Object.keys(myObj);
```

### 🙁 Actual behavior

keys is of type `string[]`

### 🙂 Expected behavior

but instead should be of type `(keyof typeof myObj)[]`

**Comment by whzx5byb** [comment]
Work as intended, see https://github.com/microsoft/TypeScript/issues/45390#issuecomment-895661910.
Just search `Object.keys in:title` and you'll find dozens of it.

**Comment by xiBread** [comment]
This is also in the [FAQ](https://github.com/microsoft/TypeScript/wiki/FAQ#indirect-excess-properties-are-ok).
