### ISSUE TITLE
`rootDirs` is not working as expected.

### ISSUE THREAD

**Issue by Mlocik97** [microsoft/TypeScript#59718]
### 🔎 Search Terms

- `rootDirs`

### 🕗 Version & Regression Information

version: 5.5.4

### 💻 Code

```ts
{
    compilerOptions: {
        allowJS: true,
        checkJS: true,
        module: "NodeNext",
        moduleDetection: "force",
        isolatedModules: true,
        verbatimModuleSyntax: true,
        allowSyntheticDefaultImports: true,
        rootDirs: [ "./src/*", "./src/*/types/_gen" ]
    },
    include: [ "./src/**" ]
}
```

### 🙁 Actual behavior

I have two files:

```
./src/example/file.js
./src/example/types/_gen/file.d.ts
```

With configured rootDirs, TSC should see:

```
./src/example/file.js
./src/example/file.d.ts
```

Which should make `file.js` automatically type-checked against `file.d.ts` that is collocated (same as when they are collocated in FS)

`./src/example/types/_gen/file.d.ts` contains:
```ts
type File = (foo: string, bar: number) => boolean;

export default File;
```

`./src/example/file.js` contains:
```js
module.exports = (foo, bar) => {
    return true;
}
```

But both foo and bar are typed as any.

### 🙂 Expected behavior

Both foo and bar have correct type (string and number), and TSC throwing error if don't return boolean.

### Additional information about the issue

I tested it without wildcard (glob pattern) too, but still same behavior. It doesn't show correct types.

E.g. even if I set: `  rootDirs: [ "./src/example", "./src/example/types/_gen" ]`

**Comment by DanielRosenwasser** [comment]
When you say "TSC should see", can you provide more details? TypeScript doesn't merge these into a view of one file, `rootDirs` is entirely about how paths are resolved when you write an import. So do you have an example file that tries to import `./file` in some way?

**Comment by MartinJohns** [comment]
@DanielRosenwasser OP probably refers to the example from the documentation: https://www.typescriptlang.org/tsconfig/#rootDirs

> `rootDirs` can be used to provide a separate “type layer” to files that are not TypeScript or JavaScript by providing a home for generated `.d.ts` files in another folder.

**Comment by DanielRosenwasser** [comment]
Yeah, I get that - but there might be a misunderstanding because if you hover over the `.js` file, we won't try to "unify" TypeScript's understanding between the `.d.ts` and the `.js` files. If you use a type-checker for Python, this might be the expectation. Currently, an issue proposing something like that exists over at https://github.com/microsoft/TypeScript/issues/30304.

The way `rootDirs` works is that some file (let's call it `importer.ts`) has to try to import a path that could resolve to either the `file.d.ts` or the `.js` file as it's written. When resolving the path, the `.d.ts` takes higher precedence. `importer.ts` itself will "see" the `.d.ts` file, not the `.js` file (except when special logic for editor scenarios like "Go to Source Definition" are requested).

**Comment by Mlocik97** [comment]
First let me explain what I mean without rootDirs.

If I create `./src/file.js` and `./src/file.d.ts`, I define:

```ts
type Example = (foo: string, bar: number) => boolean;

export default Example
```

in `.d.ts` file and

```js
module.exports = (foo, bar) => {
//                ^^^  ^^^
//                string, number
     return "test"; // this throws, because string is not assignable to boolean.
}
```

This is how it works without rootDirs. Now let's just move `.d.ts` to different directory.

What I'm trying to achieve is https://svelte.dev/blog/zero-config-type-safety

When you have .js and .d.ts file collocated and with same name, JS file get automatically type-checked against type definition file.

In Svelte, they use:

```
		"rootDirs": [
			"..",
			"./types"
		],
```

in `.svelte-kit/tsconfig.json`, which works fine. For type definition file inside `.svelte-kit/types/src/routes/$types.d.ts` it match against `./src/routes/+page.svelte`, as both `both files looks virtually as if they are inside directory `./src/routes/`, and with LSP modification and TS plugin, it makes it possible for `$types.d.ts` to hold types used to type-check `+page.svelte` file (and other Svelte specific files).

This works well if they are in two separate directories (e.g. they don't have common "root"). E.g. for paths:

```
./src/types/example/file.d.ts
./src/implementation/example/file.js
```

But not if types directory is inside directory that holds implementation. E.g.

```
./src/types/example/file.d.ts
./src/example/file.js
```

Where `./src/` is root directory, and `/types/example/` should be virtually just `/example/`.

Note, `rootDirs` really doesn't affect only imports, but what TSC virtually see (structure of files vs real file-system structure).

**Comment by Mlocik97** [comment]
I will try to retest it in different scenarios tomorrow and provide more details.

**Comment by DanielRosenwasser** [comment]
> ```js
> module.exports = (foo, bar) => {
> //                ^^^  ^^^
> //                string, number
>      return "test"; // this throws, because string is not assignable to boolean.
> }
> ```
> 
> ...
> 
> 
> When you have .js and .d.ts file collocated and with same name, JS file get automatically type-checked against type definition file.


I might be wrong, but above I stated that TypeScript specifically doesn't work that way. If you have an example project, please let me know.

**Comment by Mlocik97** [comment]
> > ```js
> > module.exports = (foo, bar) => {
> > //                ^^^  ^^^
> > //                string, number
> >      return "test"; // this throws, because string is not assignable to boolean.
> > }
> > ```
> > 
> > ...
> > 
> > 
> > When you have .js and .d.ts file collocated and with same name, JS file get automatically type-checked against type definition file.
> 
> 
> I might be wrong, but above I stated that TypeScript specifically doesn't work that way. If you have an example project showing otherwise, please let me know.

I know that by default doesn't. I use TS plugin that allows this, I wrote myself (mostly copied from others).But I think you are right this issue may be unrelated to rootDirs. Will check my TS plugin tomorrow.

**Comment by DanielRosenwasser** [comment]
Thanks! Can you provide details on what TS plugin does this?

**Comment by Mlocik97** [comment]
@DanielRosenwasser It's mostly inspired by https://github.com/sveltejs/language-tools/commit/03740003d12d547be2af573ba8ebed58d29195a5
