### ISSUE TITLE
Function inference is incorrect with inline const objects

### ISSUE THREAD

**Issue by Binek115** [microsoft/TypeScript#59721]
### 🔎 Search Terms

inline inference, function return type, as const

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAZmAjDAvDAFASlQPhgWQEMoALAOgCdCwATEAWyxjwAYYB+DAbxkIC4YAckSCYAX14QYoSFGwCeAIwGDFosQCgNM6PDAAmVBmwo8XDTGnhdIRQCsApsCgBBCAGFrsNOh78hIuKSVrKYFjAUDlAArhRgBMTkVLQMTKwcMLaOzm6esjAKMMpCauIA3BpiQA

### 💻 Code

```ts
const fn1 = () => Math.random() > 0 ? ({ a: '1' } as const) : { b: 'b' }

const fn2 = () => {
  const objectAsConst = ({ a: '1' } as const)
  return Math.random() > 0 ? objectAsConst : { b: 'b' };
}
```

### 🙁 Actual behavior

Return type for `fn1` is 
```typescript
{
    readonly a: "1";
    b?: undefined;
} | {
    b: string;
    readonly a?: undefined;
}
```
while for `fn2` is
```typescript
{
    readonly a: "1";
} | {
    b: string;
}
```

### 🙂 Expected behavior

Return type for both functions should be
```typescript
{
    readonly a: "1";
} | {
    b: string;
}
```
Inlining object should not change type of function

**Comment by jcalz** [comment]
[Improved type inference for object literals](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#improved-type-inference-for-object-literals) is working as intended as implemented in #19513.  

Also see #57563.
