### ISSUE TITLE
Can't understand error -> Operator '+' cannot be applied to types 'BigInt' and 'BigInt'

### ISSUE THREAD

**Issue by khaled4vokalz** [microsoft/TypeScript#59739]
### 🔎 Search Terms

Operator '+' cannot be applied to types 'BigInt' and 'BigInt'

### 🕗 Version & Regression Information

N/A

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=10#code/MYGwhgzhAEAyCWEAuA5A9gEwKbQN4ChpoAHAVwCMR5hoA3MEALmgDtSBbcrAJwG5CSFKjRZYAHkmYJk6bNAA+rUiBD8iwNC2TdSwJGm4AKekyWceAGlbjJcRKkw5FbFQEo8AokgAWiAHQm0AC8dAxqRNA+-qISwdYS4QC++Mn4AGakLHrwmtAA5lioHFxGptIOcs7KIK7MAELweQCSLEgeRCCFZiVxDc2thgAMruGdbZ20WCBxAIyjXSyOcaoCAO6+ndCGi9juBBHdPNAA1CF9LUiGE1PQAFSsjgEMI57Q19O3ITOD4UQ7OCF-n4YkgkgJuIVSNwWIc+Cl0plsrkCkgECwANZYDDlABi3DQ7BQxR4LQASlhJtwIFhthx6o0LrU7DIllUVO1oPA0ls2OxgkEzgyBsM9q8IUgoTDRKtmRUaYMrC4amD1JpkGYWgBlJDceAsPJxAAGABJcLzEob5m0IRBlLZyrInEp2YDquE0gYtmNOXEfj6ADwalja3X6vydfU+Xic47HUUHLlbG12-mutwcg7JkBtQFYGUOxyGInmIy8rU6vV5ADa8AAuq5FdUXgdEtAptSMxEsznrPn7I6i8TSxxy6Hq3WG9Bu82IskiHOp5DoYvbdn+MkMlkkDkYWAMBgACqrNDFkoQQwCEAzKT91nOkAWS8AJhvLMq9-wTIL76VHPFkvyQo0UxbF7DxAlTxJFhyUpalDBRSDShmdxjkAooSyuJ9XBeZIgA

### 💻 Code

```ts
class ListNode {
  public val: number;
  public next: ListNode | null;
  constructor(val: number, next: ListNode | null) {
    this.val = val;
    this.next = next;
  }
}

function getNumber(l: ListNode | null): BigInt {
  let number = BigInt(0);
  let level = 1;
  let node = l;
  while (node) {
    number += BigInt(level * node.val);
    level *= 10;
    node = node.next;
  }
  return number;
}
function getLinkedListFromNumberInReverse(num: BigInt): ListNode | null {
  if (num === BigInt(0)) {
    return new ListNode(0, null);
  }
  const numInString = `${num}`;
  let result: ListNode | null = null;
  for (let i = 0; i < numInString.length; i++) {
    if (result === null) {
      result = new ListNode(Number(numInString[i]), null);
    } else {
      result = new ListNode(Number(numInString[i]), result);
    }
  }
  return result;
}
function addTwoNumbers(
  l1: ListNode | null,
  l2: ListNode | null
): ListNode | null {
  return getLinkedListFromNumberInReverse(getNumber(l1) + getNumber(l2));
}

```

### 🙁 Actual behavior

I really don't understand this message.... Is this something that's following the RC? I can do that same in Browser console without any error, why is typescript complaining?

![image](https://github.com/user-attachments/assets/6131e366-03aa-4b19-8ebf-4fa53a69ccbd)

### 🙂 Expected behavior

probably give a better error message?

**Comment by xiBread** [comment]
The return type should be `bigint`, not `BigInt`.

**Comment by Josh-Cena** [comment]
See: https://typescript-eslint.io/rules/no-wrapper-object-types

**Comment by khaled4vokalz** [comment]
Thanks for the hints.... But I still think it'd have been helpful for the DEV if the message was a bit elaborate on `How this is a problem only in TS` because it's obvious that we can do the same in JS without any error thrown. 
![image](https://github.com/user-attachments/assets/84da5b23-425b-4c52-a9ad-4b7a7d3e7acd)

As TS has wrapped the built in `BigInt` to it's own structure the problem appears... One problem here is that I couldn't find anything while searching in google regarding this...

**Comment by nmain** [comment]
@khaled4vokalz This is alluded to in the handbook https://www.typescriptlang.org/docs/handbook/2/everyday-types.html

> The type names String, Number, and Boolean (starting with capital letters) are legal, but refer to some special built-in types that will very rarely appear in your code. Always use string, number, or boolean for types.

And has linter rules such as https://eslint.org/docs/latest/rules/no-new-wrappers.  The Javascript expression `Object(BigInt(4))` has a type, so Typescript needs some way to represent it.
