### ISSUE TITLE
false ? ... behavior is weird.

### ISSUE THREAD

**Issue by sparecycles** [microsoft/TypeScript#59731]
### 🔎 Search Terms

ternary false inference

### 🕗 Version & Regression Information

Looks like this has been the case forever. (since oldest playground version 3.333<span style="text-decoration: overline">3̅</span>)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMAFAfQFyIM5QE4xgDmAlIgN4C+A3AFAA2AplIgB5a4HGIA+i4AE0bBCjAXQgJciAI5YARnDhMAhkgC8ifCEYSpLGRESbgK+tkaIV2RJLC46tGYgD8bV8hSsyWMCHr0iL7+9HSGHqweqN5BiH4BsfGhtKbmlm6RbtE+cSGJIdRAA

### 💻 Code

```ts
function f(_: string) {};
let x: string | undefined;
const q: boolean = true;
const qc = false as const;

q ? x ? f(x) : null : null;
qc ? x ? f(x) : null : null; // no error as below despite qc being `const false` so it should behave the same?
false ? x ? f(x) : null : null; // error on `x` being string | undefined in impossible branch after x is checked.
```

### 🙁 Actual behavior

<img width="782" alt="image" src="https://github.com/user-attachments/assets/d84c8aaa-be84-4dbc-84d2-d9faa8873d1f">

### 🙂 Expected behavior

Either disable typechecking in unreachable code or still apply narrowing (as is done in the `qc ? ...` line)?

### Additional information about the issue

Just sharing since it surprised me a little.

**Comment by MartinJohns** [comment]
> Either disable typechecking in unreachable code or still apply narrowing

#26914
