### ISSUE TITLE
Type unions are previewed out of order

### ISSUE THREAD

**Issue by Nixinova** [microsoft/TypeScript#59746]
### 🔎 Search Terms

type union vscode preview display out of order digits/numbers

### 🕗 Version & Regression Information

- [ ] This changed between versions ______ and _______
- [ ] This changed in commit or PR _______
- [ ] This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- [x] I was unable to test this on prior versions because this behavior is from the VSCode previewer.

### 💻 Code

```ts
type digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
```

### 🙁 Actual behavior

![image](https://github.com/user-attachments/assets/0a801832-a74e-4f66-a88c-666c02633b2b)
Why is 0 between 2 and 3?

### 🙂 Expected behavior

Preview says `type digit = "0" | "1" | "2" | "3" ...`

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

Duplicate of #17944. The order of types in a union is not guaranteed.

**Comment by Nixinova** [comment]
no i didn't? and okay will close as duplicate. still weird that only 0 is out of place though.
