### ISSUE TITLE
5.6 regression: Function inference with multiple T newly chooses less specific type

### ISSUE THREAD

**Issue by trevorade** [microsoft/TypeScript#59766]
### 🔎 Search Terms

Inference

### 🕗 Version & Regression Information

- This changed between versions 5.5.4 and 5.6.0-beta (still happening in 5.6.1-rc)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.1-rc#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYQhVBgB4AVAPjgG8AoOObAVyimBQBFMZMAuOOQDaAXQDcDOAGcIrXN14DyEgL506MAJ5g8AWR7YAFmgrUAvHAAUAEx79BogJRwz1cnAA+cZkmvB0yMDWEnR+2AA2mOxw6D7YMAhEcAC2BoamlpK2ig4iADSSMnLASgWMqTBGaAL6lcZQpgWOSp5wSMzh4ep0yKgYOHgAyhDJwOTaePSMYFAQYAD8AlIwUMgA5qrqYZHRsUjxiUjSI2MTtVVQNnYCw6PjOk43J-d4Xj5+AUhBIdtReNhEZZMIioEAwASEYhg0gQABGACtgPFKCEAUggQA3TDhFwpNKZRho0EwAB0LDYHBgCkwZWBUNJRSg8jstJkdzOaTQTQAhBIseEJAB6QUAPXmdCAA

### 💻 Code

```ts
export interface Context<T> {
  currentData: T[];
  sourceData: T;
}

type Matcher<T> = (data: T[]) => T | undefined;

declare function match<T>(
  data: T[],
  source: T,
  matcher: Matcher<T>,
): T | null


interface SomeType {
  prop?: string;
}

declare function someTypeMatcher(data: SomeType[]): SomeType | undefined;

declare const context: Context<object>;

const val = match(
  context.currentData,
  context.sourceData,
  someTypeMatcher,
)!;
val;
//^?
```

### 🙁 Actual behavior

`val` has type `object`

### 🙂 Expected behavior

`val` has type `SomeType` as it did in previous releases

### Additional information about the issue

Again, this example was simplified from the true source.

I'm not really clear on the best title of this issue. If able, feel free to change it or suggest a better name.

(Google note: relevant source location http://shortn/_cSN29Lycl0)

**Comment by RyanCavanaugh** [comment]
This seems unambiguously correct, since this is a legal implementation of `match` with a legal call (and the resulting code crashes):
```ts
export interface Context<T> {
  currentData: T[];
  sourceData: T;
}

type Matcher<T> = (data: T[]) => T | undefined;

function match<T>(
  data: T[],
  source: T,
  matcher: Matcher<T>,
): T | null {
  return source;
}

interface SomeType {
  prop?: string;
}

declare function someTypeMatcher(data: SomeType[]): SomeType | undefined;

declare const context: Context<object>;

const obj: object = { prop: 32 };
const val = match(
  context.currentData,
  obj,
  someTypeMatcher,
)!;
val.prop?.toLocaleLowerCase();
//^?
```

You could write
```ts
declare function match<T, U extends T>(
  data: U[],
  source: U,
  matcher: Matcher<T>,
): T | null
```
instead if it's actually doing some kind of filtering operation
