### ISSUE TITLE
5.6 regression: Array.prototype.reduce type inference regression

### ISSUE THREAD

**Issue by trevorade** [microsoft/TypeScript#59763]
### 🔎 Search Terms

Inference, Reduce

### 🕗 Version & Regression Information

- This changed between versions 5.5.4 and 5.6.0-beta (still happening in 5.6.1-rc)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.1-rc#code/JYOwLgpgTgZghgYwgAgMoHsC2EAqBPABxQG8AoZC5CEAVwC40sIBRWzAblIF9TTqbMjbKwHIylZAEFkAXmQBGADTlKAIVnIATMokBhDQGYdlACIaALMp6kAJhAQAbOFBQJ0IAM5hkANzgOPBgxsfCIAbQBdTlI3T28PTH8HCC8RDT8AgDoXGxokAAoVCnzMUBFFX38ASlkAPmQAWTgwAAtM0pASstoKjMz+KuMKYJY2TJNlKs4EpJSwEU4AekXkAD0AfiA

### 💻 Code

```ts
interface SomeType {
    enu: SomeEnum;
}

enum SomeEnum {
    A = 1,
    B = 2,
    C = 3,
    D = 4,
}

declare const vals: SomeType[];

const smallestEnu = vals.reduce(
    (minEnu, val) => Math.min(minEnu, val.enu),
    SomeEnum.D,
);
smallestEnu;
// ^?
```

### 🙁 Actual behavior

`smallestEnu` has type `number`

### 🙂 Expected behavior

`smallestEnu` has type `SomeEnum` as it did in previous releases

### Additional information about the issue

Interestingly, this does not repro if you remove the container type:
https://www.typescriptlang.org/play/?ts=5.6.1-rc#code/KYOwrgtgBAyg9hYBRc0DeAoK2oEEoC8UAjADRY4BChUATOTlAMI0DMDOAIjQCzkC+GDABNgAYwA2AQwBOwKGLggAzgBcooSMoBcsBMlQBtALoBuIYpXrlEKRInA1KMDU0RlAOjnCwY4AAoKbH8IAEsQZ1INcABKQgA+KABZKVUACw8wkBDwyOiwGI5seERnCA9OchjzGzsHJ3BzAHomqAA9AH4MIA

(Google note: relevant source location http://shortn/_JgMRGaMa4e)

**Comment by RyanCavanaugh** [comment]
🤔

Building TypeScript...
TypeScript built successfully!
git bisect good
a71841c77bb42f9c691d2ae3572cd71ce48d4364 is the first bad commit
commit a71841c77bb42f9c691d2ae3572cd71ce48d4364
Author: Mateusz Burzyński <mateuszburzynski@gmail.com>
Date:   Tue Jun 18 00:25:06 2024 +0200

**Comment by RyanCavanaugh** [comment]
I would say this is a correct result. From the compiler's POV, `Math.min` is no different from `Math.pow`, and it's inarguable that
```ts
const smallestEnu = vals.reduce(
    (minEnu, val) => Math.pow(minEnu, val.enu),
    SomeEnum.D,
);
```
would more correctly be `number` than `SomeEnum`

**Comment by trevorade** [comment]
I can see this being an improvement as well in this specific case.

It's a bit harder though to more abstractly decide what is appropriate behavior for code like:

```ts
function func<T>(a: T, b: T): T;
```

When called with `a` and `b` that are slightly different types.

I would argue that past behavior should be the guiding principle.

I have another regression I'm about to log that is similar to this.

**Comment by trevorade** [comment]
Confirmed that https://github.com/microsoft/TypeScript/pull/59709 does not resolve this issue.

**Comment by Andarist** [comment]
Eh, for some reason I was looking at the other playground - the one that doesn't reproduce the issue.

I agree with @RyanCavanaugh that this is more correct (although number enums are at times more permissive/unsound, see bitmasks using them)

**Comment by Andarist** [comment]
The difference between those 2 cases is quite surprising here - especially given how this was accidentally affected by the change in inferred type selection. It boils down to how `reduce` overloads are structured:
```ts
    reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T): T;
    reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T, initialValue: T): T;
    reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U;
```

`callbackfn` is given those 2 types respectively:
```ts
(minEnu: SomeEnum, val: SomeType) => number
(minEnu: SomeEnum, enu: SomeEnum) => number
```

Notice that the first one uses different (unrelated) types for its parameters while the second one has parameters of the same type. So what happens here is that the second case never gets to the inference-based overload*, it stops at the second one since this candidate is perfectly applicable**.

*It gets to it in the first subtype-based pass but not in the second assignable-based pass of `chooseOverload`
**Perfectly applicable under current set of rules according to which number always is assignable to numeric enums
