### ISSUE TITLE
jsdoc @overload rest params and tuple

### ISSUE THREAD

**Issue by VanillaMaster** [microsoft/TypeScript#59773]
### 🔎 Search Terms

jsdoc, `@overload`, rest params, tuple

### 🕗 Version & Regression Information

This behaviour aplicable to ts versions starting from 5.0

### 💻 Code

declaring rest parameters with tuple converts it into single parameter
```js
/**
 * @overload
 * @param { number } arg0
 * @param  { [arg1: number, arg2: string] } args 
 * @returns { void }
 */
/**
 * @param { any } arg0 
 * @param  { ...any } args 
 * @returns { void }
 */
function foo(arg0, ...args) {}
```

### 🙁 Actual behavior

```ts
function foo(arg0: number, args: [arg1: number, arg2: string]): void
```

### 🙂 Expected behavior

```ts
function foo(arg0: number, arg1: number, arg2: string): void
```

**Comment by MartinJohns** [comment]
You don't have a rest parameter with your only overload. You need to write `@param  { ...[arg1: number, arg2: string] } args`.

**Comment by VanillaMaster** [comment]
@MartinJohns If done without overloading rest param in my example properly typed, and btw, with spread syntax type become like this 
```ts
function foo(arg0: number, ...args: [arg1: number, arg2: string][]): void
```
(Also incorrect)

**Comment by Andarist** [comment]
This produces the signature you want (just like @MartinJohns suggested):
```ts
/**
 * @overload
 * @param { number } arg0
 * @param  { ...[arg1: number, arg2: string] } args 
 * @returns { void }
 */
/**
 * @param { any } arg0 
 * @param  { ...any } args 
 * @returns { void }
 */
function foo(arg0, ...args) { }
```

Note that only the `@overload` signature is visible publicly, the other one is a private implementation signature that you won't observe externally at all. If you want multiple public overloads then you need to declare multiple `@overload` signatures here

**Comment by VanillaMaster** [comment]
@Andarist , @MartinJohns you both are right, problem related to mine instance of TS LSP
