### ISSUE TITLE
Type discrimination bug with string literal tuple.

### ISSUE THREAD

**Issue by gyurielf** [microsoft/TypeScript#59785]
### 🔎 Search Terms

"discriminated union", "discrimination", "literal tuple", "string literal tuple"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAQghgZ2gXigbwLACgq6gSwBMB+ALigWACd8A7AcwG5s8oBrCEMi6up7AL7ZsoSFACCAFXAp0LPHCpU4IcgG0A5HA0BdZjjwAzfBAA2hBNzRRacALYRulGgwA0UOIUJUICS+Wc+AUYoAHpQqAAxE3MEDx8PU1MAewB3CEIoZNpTEChDZKooLQ1BfREZWGkxVEwDXEVlVShNACNdfVYfQnwfAGNgAFUAJQAZchHRqAAfHhcmMIjhiABHAFdejPzC4vay4SxRaHE4WkIYatk61kaVdRL3DXadGZanjUftPXlcbs2ByYTMavQIMELhKDLdabTIFIrvH5QQgQQxwNamYAASWAEDs3BKr3enSMMQsVhs9kcAV4bg8Xh8ficNPowUWUVJcUU0DgSTSW1SAAsILQoK1ksABcVtB4zrsNPFoGAGcLgPssBUxABhbLGehQVDwJBQABkUAAFFJKrMLlaJKdzpcAJTlLB9bKUKA4yjkbW0XX6uRYACQt2ami+rmwQb+-SGY3IGgFwGAYAQpHCEAAHvYwKYIAA6N12eXhAA85YAtFXPQL8HEEALkujMhKqGkZVAIEpCvnBEA

### 💻 Code

```ts
type Base = {
    id?: string;
    key?: string;
}

type AType = {
    array: ['a'];
    fields?: { name?: string, address?: string}; // Fields are allowed only for 'a'
};

type BType = {
    array: ['b'];
    redirectURL: URL | string; // Required for 'b'
};

type AandBType = {
    array: ['a', 'b'] | ['b', 'a'];
    redirectURL: URL | string; // Required for 'b'
    defaultItem?: 'a' | 'b';
    fields?: { name?: string, address?: string}; // Fields are allowed when both 'a' and 'b' are present
};

type Config = Base & (AType | BType | AandBType);

const test: Config = {
	array: ['a'],
	redirectURL: 'https://example.com' //<<<--- this should throw an error.
}
```

### 🙁 Actual behavior

The following test variable is suggest every field regardless of the `array: ['a']`.

```ts
const test: Config = {
	array: ['a']
}
```
And it not thrown errors if i declare a non related property.

```ts
const test: Config = {
	array: ['a'],
	redirectURL: 'https://example.com', //<<<--- this should throw an error.
	defaultItem: 'a' //<<<--- this should throw an error as well.
}
```

### 🙂 Expected behavior

The following test variable should suggest the discriminated type fields by default.

```ts
const test: Config = {
	array: ['a']
}
```
And it not thrown errors if i declare a non related property.

```ts
const test: Config = {
	array: ['a'],
	redirectURL: 'https://example.com', //<<<--- this should throw an error.
	defaultItem: 'a' //<<<--- this should throw an error as well.
}
```

**Comment by RobertSandiford** [comment]
`Config` can be rewritten as `type Config = (Base & AType) | (Base & BType) | (Base & AandBType)` with the same result.
I looked at this and figured that when checking compatibility the checker could look for matching union members, then apply the Excess Property Check to each matching member, ruling out any that fail, or throw an EPC error if they all fail. But it doesn't seem to.

Changing `array` to a string, which TS seems to need to use it as a discriminator makes the EPC kick in. But I'm just not getting why an EPC check on a union needs a discriminator. I may be missing something, but seemed solvable to me.

**Comment by MartinJohns** [comment]
> But I'm just not getting why an EPC check on a union needs a discriminator.

#20863

**Comment by jcalz** [comment]
The word is “tuple”, not “touple”. Could you edit so this issue can be found via searches on “tuple”?
