### ISSUE TITLE
Array.forEach args type error

### ISSUE THREAD

**Issue by chenyulun** [microsoft/TypeScript#59791]
### 🔎 Search Terms

```
export interface TypeA {
  name: string
}

export interface TypeB extends TypeA {
  unit: string
}

const xxx: { a: TypeB[], b: TypeA[] } = {
  a: [],
  b: [],
};
(['a', 'b'] as const).forEach((key) => {
  const yyy = xxx[key]

  yyy.forEach((item) => { // (parameter) item: TypeA

    if('unit' in item) {
      console.log(item.unit) // (property) unit: unknown
    }
  })
})
```

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

```bash
mkdir test-ts5.5
cd $_
pnpm init
pnpm add typescript
```
package.json
```json
{
  "name": "test-ts5.5",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "typescript": "^5.5.4"
  }
}

```

### 💻 Code

```ts
export interface TypeA {
  name: string
}

// export interface TypeB extends TypeA {
 export interface TypeB {
  name: string
  unit: string
}

const xxx: { a: TypeB[], b: TypeA[] } = {
  a: [],
  b: [],
};
(['a', 'b'] as const).forEach((key) => {
  const yyy = xxx[key]

  yyy.forEach((item) => {
    if('unit' in item) {
      console.log(item.unit)
    }
  })
})
```

### 🙁 Actual behavior

`item` type Only `TypeA`

### 🙂 Expected behavior

`item` type sould be `TypeA | TypeB`

### Additional information about the issue

I have not idea

**Comment by chenyulun** [comment]
but `item.unit` type  be `unknown`

**Comment by MartinJohns** [comment]
Objects are not sealed. It's possible that your `TypeA` values have a `unit` property that is not a `string`, that's why checking for a property using the `in` operator results in `unknown`.

**Comment by chenyulun** [comment]
> Objects are not sealed. It's possible that your `TypeA` values have a `unit` property that is not a `string`, that's why checking for a property using the `in` operator results in `unknown`.

So there is a problem with item's type recognition
But it was marked as non-defective in another issue

**Comment by chenyulun** [comment]
How should I write best practices for the following code
```ts
export interface TypeA {
  name: string;
}

export interface TypeB {
  name: string;
  unit: string;
}
let unit: string; 
const testObject: { a: TypeB[], b: TypeA[] } = {
  a: [],
  b: [],
};
(['a', 'b'] as const).forEach((key) => {
  const ObjectValue = testObject[key]

  ObjectValue.forEach((item) => {
    if('unit' in item) {
      unit = item.unit // error ts(2322)
    }
  })
})
```

**Comment by chenyulun** [comment]
```ts
export interface TypeA {
  name: string;
}

export interface TypeB {
  name: string;
  unit: string;
}
  type TypeTest = TypeA[] | TypeB[]
  type Item = TypeTest extends Array<infer R> ? R : never // Item type to be TypeA
```

**Comment by MartinJohns** [comment]
> So there is a problem with item's type recognition

No, it's working as intended. There is no defect.

**Comment by chenyulun** [comment]
> ```ts
> export interface TypeA {
>   name: string;
>   // age: number;
> }
> 
> export interface TypeB {
>   name: string;
>   unit: string;
> }
> type TypeTest = TypeA[] | TypeB[]
> // type TypeTest = string[] | boolean[];
> 
> 
> 
> 
> type Item = TypeTest extends Array<infer R> ? R : never // as  type Item = TypeA
> // because this?
> type IsBExtendsA = TypeB extends TypeA ? 'true' : 'false' // 'true'
> ```

Although the logic is fine, the `extends` judgment in real use scenarios doesn't make sense, and this may involve too much underlying design.

**Comment by chenyulun** [comment]
> > So there is a problem with item's type recognition
> 
> No, it's working as intended. There is no defect.


But he realistically lost the type of `unit` as `string`，Is there a better way to practice this situation？

**Comment by MartinJohns** [comment]
As mentioned in the other issue, it's due to subtype reduction. Look it up, there are many issues about it. It's working as intended.

You can either explicitly check if `unit` is a `string` by doing `'unit' in item && typeof item.unit === 'string'` or just use a type assertion `item.unit as string`. But again, objects are not sealed. Values of `TypeA` are permitted to have a `unit` property at runtime, which may not be typed `string`. This adjustment of your code demonstrates it:

```typescript
interface TypeA {
  name: string;
}

interface TypeB {
  name: string;
  unit: string;
}
let unit: string; 
const testObject: { a: TypeB[], b: TypeA[] } = {
  a: [],
  b: [],
};


// The value is compatible with TypeA, so it can be pushed to the TypeA array.
const value = { name: 'example', unit: 12345 };
testObject.b.push(value);


(['a', 'b'] as const).forEach((key) => {
  const ObjectValue = testObject[key]

  ObjectValue.forEach((item) => {
    if('unit' in item) {
      console.log(item.unit)
      unit = item.unit // error ts(2322)
    }
  })
})
```
