### ISSUE TITLE
JSDoc @import statement for side effects

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/TypeScript#59796]
### 🔎 Search Terms

JSDoc, @import 

### 🕗 Version & Regression Information

I don't think this is supported right now; perhaps intentionally.

### 💻 Code

I created a `global.d.ts` like so:

```ts
export interface GlobalData {
    myString: string;
}

declare global {
    interface Window {
        globalData: GlobalData;
    }
}
```

In an `app.js` file I have this code which imports the `global.d.ts` with the desire of augmenting the `window` object:

```ts
/**
 * @typedef {import('./globals')}
 */
```

With this in place `window` is augmented as desired.

Looking at TS 5.5 release notes: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-jsdoc-import-tag I wondered if an `@import` statement could be used instead to support "side effects only" imports:

```ts
/** @import "./globals" */
```

But it doesn't appear to.  Perhaps this is intentional?

### 🙁 Actual behavior

<img width="410" alt="image" src="https://github.com/user-attachments/assets/57694465-9d36-4ebb-a7dd-918205010376">

Imagine the `import` worked in the same manner as the `typedef` - that'd be great, right?

### 🙂 Expected behavior

I wondered if it might work - it didn't.

### Additional information about the issue

Also discussed here: https://stackoverflow.com/questions/77427341/jsdoc-globalthis-window-object-extend/78927974#78927974

**Comment by GulgDev** [comment]
Why do we need this if we have regular `import`?

**Comment by jakebailey** [comment]
If it's for side-effects, can you just use `/// <reference path="./globals" />``?

**Comment by johnnyreilly** [comment]
Yep I can confirm that `/// <reference path="./globals" />` works, as does:

```ts
/**
 * @typedef {import('./globals')}
 */
```

This is more a question than anything else: is it intentional that `/** @import "./globals" */` / side effects JSDoc type imports isn't supported.  It's totally fine BTW - I am in no way blocked; I'm just curious if this was an intentional "nope, we don't want to support that usecase; we don't need to / it's bad for reason X etc"

**Comment by trusktr** [comment]
Yeah, as `import type` is not available in JavaScript, it makes sense with the new `@import` JSDoc tag that simply wrapping the `import type` with in a comment would work. For example: 

TS ([playground](https://www.typescriptlang.org/play/?&filetype=ts#code/JYWwDg9gTgLgBDAnmApnA3gZQMYoHYoC+cAZlBCHAOQA2AriClQFDPYR4DO8ncAvBmIBDXjnwpWnAHSROwGMA5wA9MrgQA1kA)):

```ts
import type {Scene} from 'lume'

const s = {} as Scene

s.position // ok
```

JS (not working, [playground](https://www.typescriptlang.org/play/?filetype=js#code/PQKhAIAEEsFsAcD2AnALuVBPeBTcBvAZQGMcA7HAX3ADNlFZwByAGwFdYcnwRgAoPsURkAzuhHgAvOFAhIWXARLkqvABT5KASgEiAdEhHRU0YTODgRAC0RsWAE3AAjPIgDWQA)):

```js
/** @import type {Scene} from 'lume' */

const s = /**@type {Scene}*/({})

s.position // should be ok
```
