### ISSUE TITLE
Import named `Disposable` is not moved when moving code to another file

### ISSUE THREAD

**Issue by alexdima** [microsoft/TypeScript#59799]
```ts
// @filename: src/_producer.ts
export class Disposable {}
```

```ts
// @filename: src/_consumer.ts
import { Disposable } from './_producer';

class Something extends Disposable {
}
```
Doing move to a new file on `Something` generates the following 🐛 (note how `Disposable` is not imported from `_producer.ts`):

```ts
// @filename: src/Something.ts
class Something extends Disposable {
}

```

**Comment by iisaduan** [comment]
Was this found in [microsoft/vscode](https://github.com/microsoft/vscode), and if so, could you link the/a location in the repo where this happens? Currently, with the reported case, the import is correctly generated (#59884). 

My guess is that this behavior is related to the `autoImportFileExcludePatterns` setting. I fixed a related crash few months ago (https://github.com/microsoft/TypeScript/pull/58537), and the default case, if we could not find a non-excluded file to import from, was to finish the rest of the codefix without generating that particular import.

**Comment by alexdima** [comment]
Appologies for the slow reply. I'm really sorry, I spent 20 minutes trying to reproduce in a separate project than vscode, but I did not manage (I tried bringing over the tsconfig from vscode, the settings from the vscode folder, but to no avail).

Here are the steps:
* clone https://github.com/microsoft/vscode
* `npm i`
* open vscode insiders `Version: 1.95.0-insider / Commit: c33745f66ce1cd626c3282112671e2a66471ce4f / Date: 2024-10-04T05:03:41.673Z (4 hrs ago)`
* (this will use TS version `5.7.0-dev.20240927`)
* open `src/vs/workbench/contrib/chat/browser/chatEditingService.ts#L338`
* move `ChatEditingSession` to a new file

https://github.com/user-attachments/assets/41ec8198-ec4a-41d2-88c4-f2b005beb932

**Comment by iisaduan** [comment]
This looks like a name resolving bug, thanks for providing the repo location!
