### ISSUE TITLE
`keyof` operator for union types? possibly incorrect behaviour

### ISSUE THREAD

**Issue by Number-3434** [microsoft/TypeScript#59818]
### 🔍 Search Terms

- keyof

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

The `keyof` operator should include all the values in the union type instead of emitting them.

For example:

```ts
type Key = "a" | "b";
type Obj = {
    a: {
      isA: true,
      isObj: true
    },
    b: {
      isB: true,
      isObj: true
    },
}
type Test = Obj[Key]  // Should return "isA" | "isB" | "isObj", but instead "isObj"
```

### 📃 Motivating Example

For example, take this code:

```ts
type Key = "a" | "b";


const cars = {
  "mini-cooper": {
    displayName: "Mini Cooper",
    paints: ["", "blue", "lime", "pink"]
  },
  "renault-r5": {
    displayName: "Renault R5",
    paints: ["", "pink-green", "purple-yellow"]
  }
} as const;

const car: cars["mini-cooper" | "renault-r5"]; // e.g. because we don't know which it will be
const carId: "mini-cooper" | "renault-r5";

if (!cars[carId].paints.includes(car.paintId)) {  // ERROR: Argument of type `"" | "blue" | "lime" | "pink" | "pink-green" | "purple-yellow"` is not assignable to parameter of type "" 
  // do something
}

```

### 💻 Use Cases

1. What do you want to use this for?
Above use case

2. What shortcomings exist with current approaches?
Casting it to type `any` isn't very good, since it may muffle potential type errors

3. What workarounds are you using in the meantime?
I have to cast it to type `any`

**Comment by MartinJohns** [comment]
This is working as intended. `keyof` applied on a union will produce the keys common across each union type. See #12948.

**Comment by Number-3434** [comment]
What workarounds would you recommend?

Currently I have to use an array instead.

**Comment by jcalz** [comment]
You can write your own utility type like `type AllKeys<T> = T extends unknown ? keyof T : never` to distribute `keyof` across unions in `T`, but that's not going to fix anything with `includes()` and the motivating example in the OP is syntactically invalid pseudocode anyway so I can't easily show how to make it work.

**Comment by Number-3434** [comment]
@jcalz Wow thanks, I didn't know that worked!

Closing this issue as this fixes my use case.

Thanks!
