### ISSUE TITLE
`this` becomes any inside function within object when using generic method types that `extends` + syntax highlighting breaks

### ISSUE THREAD

**Issue by alexwork1611** [microsoft/TypeScript#59811]
### 🔎 Search Terms

this object any, this object scope any, this becomes any inside method inside object

### 🕗 Version & Regression Information

I'm using TypeScript 5.5 and this is the first time I've faced this issue. Please check the playground linked below.

### ⏯ Playground Link

https://github.com/alexwork1611/typescript-this-keyword-bug-investigation/blob/main/src/models/user.ts

### 💻 Code

https://github.com/alexwork1611/typescript-this-keyword-bug-investigation/blob/main/src/models/user.ts

```ts
import bcrypt from 'bcryptjs';
import { Schema, Types, model } from 'mongoose';

const userRoleNameEnum = ['king', 'magistrate', 'citizen', 'child'] as const;

const userSchema = new Schema(
  {
    _id: {
      type: Schema.Types.ObjectId,
      default: () => new Types.ObjectId(),
    },
    username: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      match: [/.+@.+\..+/, 'Must match an email address!'],
    },
    password: {
      type: String,
      required: true,
      minlength: 5,
    },
    role: {
      type: {
        name: { type: String, enum: userRoleNameEnum },
        locations: [String],
      },
      required: true,
    },
  },
  {
    methods: {
      /**
       * Checking if a given matches the current one.
       */
      async isCorrectPassword(password: string) {
        return await bcrypt.compare(password, this.password);
      },

      /**
       * Getting the user's resources by query.
       */
      async getResources(resourceType: keyof App.Models.UserPopulatePaths) {
        return (
          await this.populate<App.Models.UserPopulatePaths>(resourceType)
        )[resourceType] as App.Models.UserPopulatePaths[typeof resourceType];
      },

      /**
       * Getting the user's resources by query.
       */
      async getResourcesV2<
        const TResourceType extends keyof App.Models.UserPopulatePaths,
      >(resourceType: TResourceType) {
        return (await this.populate<TResourceType>(resourceType))[
          resourceType
        ] as App.Models.UserPopulatePaths[TResourceType];
      },

      /**
       * This works.
       */
      async thisWorks() {
        return this.populate('something');
      },
    },
  },
);

const User = model('User', userSchema);

export default User;
```

### 🙁 Actual behavior

When I introduce the `getResourcesV2` method to the object scope, I am not getting info on the three `this` vars (see https://github.com/alexwork1611/typescript-this-keyword-bug-investigation/blob/main/src/models/user.ts#L51, https://github.com/alexwork1611/typescript-this-keyword-bug-investigation/blob/main/src/models/user.ts#L61, https://github.com/alexwork1611/typescript-this-keyword-bug-investigation/blob/main/src/models/user.ts#L70).

The method is found here: https://github.com/alexwork1611/typescript-this-keyword-bug-investigation/blob/main/src/models/user.ts#L58-L64.

### 🙂 Expected behavior

I should get the type of the `this` built-in variable, but I'm getting `any` instead (plus, the syntax highlighting breaks). Try removing or commenting the `getResourcesV2` method to see the changes. I also tried removing the `const` modifier from the `getResourcesV2` generic type `TResourceType`, but to no success.

### Additional information about the issue

I'm not sure if I've messed up the syntax or something, but I think I might have found a very specific/exotic bug in TypeScript.

**Comment by RyanCavanaugh** [comment]
We'd need a repro that is self-isolated (i.e. not dependent on the `mongoose` types, which are extremely complex, or any other dependencies for that matter) in order to investigate.

**Comment by alexwork1611** [comment]
@RyanCavanaugh that's fair. Will try to do a more vanilla repro. Thanks!

**Comment by alexwork1611** [comment]
I've tried replicating a vanilla example for this issue and there were no problems. Thanks for your support!

**Comment by alexwork1611** [comment]
However, I will add that syntax highlighting breaks when the following syntax is present:
![image](https://github.com/user-attachments/assets/c826e3dc-06a6-485c-bdc1-ec61b3a34a35)

If you'd like, the code for the above snipped can be found here: https://github.com/alexwork1611/typescript-this-keyword-bug-investigation/blob/main/src/test.ts#L25.

Forwarding this issue to Mongoose.
