### ISSUE TITLE
Failure of Object.entries to infer value type

### ISSUE THREAD

**Issue by JeongHeonK** [microsoft/TypeScript#59833]
### 🔎 Search Terms

Failure of Object.entries to infer value type
Object.entries

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `Object.entries()`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.4#code/JYOwLgpgTgZghgYwgAgCoQM5gN4ChkHJwBcyIArgLYBG0+h1pFNdhyCp1A9lwDYRwQuAL65cCLiCzIu1AFal00gLzJsRUgEYANMmrJSAJl0dk8XhgiiA9NeQA3OL3IQA5BmRgAngAcUwD0EvcUlpCHAoYExkVQB5eQgEMAA6cLBIzAAKWTkASgBuMW8-NF8IJTAYtXoCEjIqWigavSYG1kJTbj4BIVEQqUqcw0Uyiqr1Op09A2RjdlJzSxs7R2c3D2L-D2ZG5AAfPR5+QX6wiKiMQyr4uUSUtIyMbPlDAqA

### 💻 Code

```ts
interface InterfaceTest {
    a: number
    b: number
    c: boolean
}

const obj: InterfaceTest = { a: 1, b : 2, c: false}
// value's type is any
const entries = Object.entries(obj);

type TypeTest = {
    a: number
    b: number
    c: boolean
}

const obj2: TypeTest = { a: 1, b : 2, c: false}
// value's type is number | boolean
const entries2 = Object.entries(obj2);
```

### 🙁 Actual behavior

when using `Object.entry(object)`

```
interface Test{
    a: number
    b: number
    c: boolean
}

const obj: Test = { a: 1, b : 2, c: false}
const entries = Object.entries(obj);
```
entries[1] type is `any`

### 🙂 Expected behavior

when using `Object.entry(object)`
I expected that I would get value type that object's values have
like
```
interface Test{
    a: number
    b: number
    c: boolean
}

const obj: Test = { a: 1, b : 2, c: false}
const entries = Object.entries(obj);
```
entries[1] type is `number | boolean`

**Comment by Andarist** [comment]
This is a surprising result. I'm not entirely sure about this but I think it stems from the fact that interfaces can be augmented. So there is no actual guarantee that the inferred type will stay the same with code changes. 

Type literals can't be augmented so type literals have "inferable indexes". If you take a look at the function signature of `Object.entries` you might see this kind of type:
```ts
type ObjectEntries = {
    <T>(o: {
        [s: string]: T;
    } | ArrayLike<T>): [string, T][];
    (o: {}): [string, any][];
}
```

As we see here... `T` can only be inferred from an index signature. So since interface types don't have one... ye, the type is not inferred there.

**Comment by Andarist** [comment]
I might be misreading what you are saying but in the TS type system both interfaces and types are usually compared structurally. Nominal types can be achieved using classes with private properties.

**Comment by Oblarg** [comment]
@Andarist They're compared structurally but during compilation, references to interfaces are treated nominally (rather than the entire structure being inlined) until a comparison occurs.  This is a big difference and has a lot of downstream effects (e.g. in mouseover tooltip behavior).

**Comment by jcalz** [comment]
This is a combination of #15300 with #38520. 

(Calling interfaces "nominally typed" is confusing at best, so let's desist from doing that.)
