### ISSUE TITLE
Feature request: LSP refactor for filling an object literal with zero values

### ISSUE THREAD

**Issue by golopot** [microsoft/TypeScript#59846]
### 🔍 Search Terms

"LSP", "filling", "object literal"

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Add an LSP code action to fill in an object literal with zero values.

### 📃 Motivating Example

```ts
const foo: ComplexObject = { <> }
```
Select the code action "Fill in object literal". It fills every required properties with zero value:

```ts
const foo: ComplexObject = { 
  a: 0,
  b: "",
  c: "",
 }
```
This refactor become more valuable when there are 10+ keys.

### 💻 Use Cases

1. What do you want to use this for?
Save time for filling in object properties.
2. What shortcomings exist with current approaches?
Need to fill in properties keys manually or through completions one by one.
3. What workarounds are you using in the meantime?
Fill in properties keys manually or through completions one by one.

**Comment by jasonlyu123** [comment]
Isn't there already a quick fix for this? Maybe it's more of a problem with a specific case where there isn't a quick fix available.

**Comment by golopot** [comment]
> Isn't there already a quick fix for this? Maybe it's more of a problem with a specific case where there isn't a quick fix available.

Indeed! The quick fix is available for function argument, but not for variable declaration: 

Have quick fix:
```ts
function f(a : T) {}
f({ ▌})
```

No quick fix:
```ts
const t: T = { ▌};
```

**Comment by jasonlyu123** [comment]
Could you provide a playground link for the case? Simple type does seem to work in both parameter and variable declaration. So it might have something to do with the type differences.

**Comment by golopot** [comment]
My bad, I didn't notice the quick fix on the variable name. I thought a code action would be offered on the object literal part. An improvement might be to offer a quick fix or code action when cursor is on the object literal part. I don't know if this is feasible. Feel free to close the issue.
