### ISSUE TITLE
Cannot import Disposable

### ISSUE THREAD

**Issue by alexdima** [microsoft/TypeScript#59842]
* in the vscode repo, open `src/vs/base/common/strings.ts`
* type:
```
class X extends Disposable {
}
```
* do cmd+.
* observe that the import Disposable from lifecycle.ts quick fix is not offerred 

![Image](https://github.com/user-attachments/assets/040470e4-353a-401a-bc0c-12a46a49e9d4)

**Comment by mjbvz** [comment]
The root cause is that there's a global `Disposable` type that comes from `globals.d.ts` in `@types/node`

**Comment by jakebailey** [comment]
Note that you'd hit this with just plain TS too, if your lib is high enough, since `Disposable` is a global too: https://github.com/microsoft/TypeScript/blob/29d92edd1c105b09bc5dbf567e11f34657977d44/src/lib/esnext.disposable.d.ts#L17

Node is just declaring it early because they have the feature.
