### ISSUE TITLE
ES6 lexically scoped functions

### ISSUE THREAD

**Issue by zhuravlikjb** [Microsoft/TypeScript#5985]
In ECMAScript 6, function declarations are lexically scoped.
TypeScript currently reports an error in such case:
```
   {
        function f1() { }

        {
            function f1() { }
            f1();  
        }

        f1();
    }
```

The question is, will it be somehow handled in TypeScript, or will it be left as is?
Sorry if the same issue already exists, I didn't find anything similar.

**Comment by kitsonk** [comment]
What in the ECMAScript 6 standard are you seeing this?

`let`, `const`, and `class` are lexically scoped, `function` and `var` do not change its scoping, arrow functions are anonymous only.  If `function` or `var` changed their scoping, it would break the internet.

**Comment by zhuravlikjb** [comment]
http://kangax.github.io/compat-table/es6/#test-block-level_function_declaration
http://www.ecma-international.org/ecma-262/6.0/#sec-functiondeclarationinstantiation

Okay, the semantics is a bit more complicated than just block-scoping for all the cases, according to discussion here:
http://stackoverflow.com/questions/31419897/what-are-the-precise-semantics-of-block-level-functions-in-es6

And also to note, for example Babel correctly transpiles such constructs:
https://babeljs.io/repl/

**Comment by falsandtru** [comment]
seems a duplicate: #3714

**Comment by DanielRosenwasser** [comment]
Thanks for catching that @falsandtru.

**Comment by falsandtru** [comment]
no problem.
