### ISSUE TITLE
Typescript allows assignment of wrong type to property on union type

### ISSUE THREAD

**Issue by markusjohnsson** [microsoft/TypeScript#59862]
### 🔎 Search Terms

generic union type property assignment

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _generic union property assignment_

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAcgrgWwgJwJYGMBqBDANnaAXigG8oBrVAOwBMAuKAcisQCMVGBuKANzwIYsE7ZNwC+nAFChIUAMrA0VAOY58RUhWr0mAZ0XVlXXvwgN9S5eKkzoaqMXhI0WU1AA+8gyrUEp08GgAKV01AB4AFSgIAA9gCFpdKDUAPgcoCIBtACI+dWyAXX8AemKoAGEAC2wVaGxWAHseaFxqaGAGqGBK1F0AGigamigEEAAxOCp0YFQGqih0BuRkCGncEGjlpd0AOihJUqgoAFooACE4YC6epN6oKgar7CTddDx63Ag9g7LbKBDwlFYvFEsk8GliEC4gkaEknCgML5oAB+e5sFBQBhQkGwryWJFQVEWQyY+4QZqiSQBWQADXSALwYXhLiRKW4hyEImp0AAmvTQoyFPjTGyjodiSoqQAzSbTWbzUYTKYzOaRaLQ0GpAAUDVYACssQBKBgM3CRNIkSRHI6LKj6XgmgVmiIQqAARgATABmdllXSVBpwXDDFDIJZQLXIw1W626vU7PIEdKen3WtNiv0BoMhrbICNRmNHFbAODIeYp7jpqsZqD+wPBzZhvOR6NiKm2+0NBj2YhkSi0BjZCXKbIDRNmKDZSoQXC4BrZKASSQdq66czeZTpRWylVUHWGyuHADyACVrndnrpUMoqEgqKusw3Q0tuRl0lrbA0pVAGoacuPCl9WsN2XOZdAaT4djnZQdQTUwD2rGtMgAGSPABxAoGBTKlDnKJYVjWDZn2QNdQLtK4eDdR1wiFQxWWTb1K0Q9NDmIsj7R4D1qMZZlERFdJsnqdBsiY5jWNzdirgaLiwVwdI+20Qdh1HEx1Cw71FyY8Sm0kn8vW7PB5K0AdJ05FAVPHQchIXCQoG0l8gA

### 💻 Code

```ts
type NumericValue = { kind: 'number'; value: number; };
type StringValue = { kind: 'string'; value: string; };
type Val = NumericValue | StringValue;

type JsVal<T extends Val> = T["value"];

// Change above line to this, and myFunction correctly errors. 
//  - But this is not as scalable. 
// type JsVal<T extends Val> = T extends NumericValue ? number : T extends StringValue ? string : never;

type X = JsVal<NumericValue>; // number
type Y = JsVal<StringValue>;  // string

function myFunction<T extends Val>(obj: T): JsVal<T> {
    const v: JsVal<T> = 123; // should error (?)
    obj.value = 123;         // should error (?)
    return 123;              // should error (?)
}

const o: Val = { kind: "string", value: "hello" };
const s: string = myFunction(o);  // OR this assignment should error
type T = (typeof o)["value"]; // string
console.log(o.value);         // [LOG]: 123

// Correctly errors:
const v1: JsVal<StringValue> = 123;               // error
const v2: JsVal<NumericValue> = "abc";            // error
const o2: Val = { kind: "string", value: 123 };   // error
const o3: Val = { kind: "number", value: "abc" }; // error

```

### 🙁 Actual behavior

No errors in myFunction
No errors in call to myFunction 
No errors in assignment of return value from myFunction 

### 🙂 Expected behavior

Errors in myFunction

### Additional information about the issue

```ts
// What I actually was trying to do:
function myFunction2<T extends Val>(t: T["kind"]): JsVal<T> {
    if (t === "number") {
        // I would like it if T itself was narrowed to NumericValue
        // But here I can return string without complaints
        return "abc";
    }
    else {
        // I would like it if T itself was narrowed to StringValue
        // But here I can return number without complaints
        return 123;
    }
}

const o4 = myFunction2<NumericValue>('number');
type P = typeof o4;     // number
console.log(typeof o4); // [LOG]: "string"
```

EDIT: syntax highlighting

**Comment by markusjohnsson** [comment]
Another example:

```ts
type NumericValue = { kind: 'number'; value: number; };
type StringValue = { kind: 'string'; value: string; };
type Val = NumericValue | StringValue;

type JsVal<T extends Val> = T["value"];

function f1<T extends Val>(): JsVal<T> {
    return 123;
}

function f2<T extends Val>(obj: T): JsVal<T> {
    return 123;
}

const o: Val = { kind: "string", value: "hello" };
const s1: string = f1();  // Error!
const s2: string = f2(o); // No error!
```

**Comment by RyanCavanaugh** [comment]
`JsVal<T>` in this position doesn't stay deferred since `T["value"]` will go to the constraint; it's the same as `string | number`. You'd want to write it instead as
```ts
type JsVal<T extends Val> = T extends { value: infer U } ? U :never;
function myFunction<T extends Val>(obj: T): JsVal<T> {
    const v: JsVal<T> = 123; // is error
    return "ok"; // is error
}
```

I'm not getting why the second repro is supposed to be a defect.

**Comment by markusjohnsson** [comment]
@RyanCavanaugh 

> I'm not getting why the second repro is supposed to be a defect.

Well, `obj.value = 123;` can cause `obj` to be `{ kind: "string", value: 123 }`, which is neither a NumericValue nor a StringValue, which makes it not `Val`, which in turn makes it not T, right?

**Comment by markusjohnsson** [comment]
Sorry, I thought you meant the second line in the first code.

The issue with https://github.com/microsoft/TypeScript/issues/59862#issuecomment-2330773843 is that s2 will have the value `123` but type `string`, but typescript does not complain about it:

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAcgrgWwgJwJYGMBqBDANnaAXigG8oBrVAOwBMAuKAcisQCMVGBuKANzwIYsE7ZNwC+nAFChIUAMrA0VAOY58RUhWr0mAZ0XVlXXvwgN9S5eKkzoaqMXhI0WU1AA+8gyrUEp08GgAKV01AB4AFSgIAA9gCFpdKDUAPgcoCIBtACI+dWyAXX8AMzgqdGBUAHsqKGKARkjouISaJNSACgBKBhDwiLSSSSgRqGQIYDhkWvqAJgBmKTFJSVLyypq62abY+MTkvBSOqtYAKwYInqg+vEjB4dHxyemoOcXJZcl0Gv0oKoZ7MQyJRaAxshZDNkADQmdRggAWEFwuCq2SgEi+P2AUF09XM3mU6Qa3W4UAA9GSoABRZDIKrIACEmKov10s3xliJs2OXW4FNgVWitPpTO+LKquAgADoUcoOmzeeTKZkADIAeQA4gUGG8oJIgA

**Comment by markusjohnsson** [comment]
@RyanCavanaugh thank you for clarifying that `T["value"]` will not work in this case. 

However, with all occurrences of JsVal<T>, I think this should produce an error:

```ts
type NumericValue = { kind: 'number'; value: number; };
type StringValue = { kind: 'string'; value: string; };
type Val = NumericValue | StringValue;

function myFunction<T extends Val>(obj: T) {
    obj.value = 123;         // should error (?)
}

const o: Val = { kind: "string", value: "hello" };
myFunction(o);                // OR this assignment should error
type T = (typeof o)["value"]; // string
console.log(o.value);         // [LOG]: 123

```
https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240904#code/C4TwDgpgBAcgrgWwgJwJYGMBqBDANnaAXigG8oBrVAOwBMAuKAcisQCMVGBuKANzwIYsE7ZNwC+nAFChIUAMrA0VAOY58RUhWr0mAZ0XVlXXvwgN9S5eKkzoaqMXhI0WU1AA+8gyrUEpkgDM4KnRgVAB7KigEEAAxYNCIqgAeABUoCAAPYAhaXSg1AD4ACnDWACsGVIBKUkkoBqgy8oA6PnUHKABGACYAZm5GoagAehGoXQALcLhcGgzkZHDkKGKAfmrJMUlJdEj9JoZ7YjJKWgYAIgtDC4AaE3VLyYhcXHCLqAlJGPiQsMjStVBsMQY0xlAAPIAJSgwEmqHy2F0ulQyioSCowAm01m8xQS2Q0nA0HSxGKtnCASa1QA2hd2gQLgBdbjg64qXb7cK4CAtN7KUptUxA0ENcE0gAyEIA4kyGL0+pIgA

**Comment by RyanCavanaugh** [comment]
Property writes in general aren't sound whenever you're aliasing something. It's the same situation as this one:
```ts
type NumericValue = { kind: 'number'; value: number; };
type StringValue = { kind: 'string'; value: string; };
type Val = NumericValue | StringValue;
function myFunction(obj: Val) {
    obj.value = 123;
}
```

**Comment by markusjohnsson** [comment]
@RyanCavanaugh That's surprising. I guess I should stick to immutable objects. Thank you for taking your time and explaining.

**Comment by markusjohnsson** [comment]
This is still weird to me (v5.6.2, v5.7.0-dev.20240922):

```ts
type NumericValue = { kind: 'number'; value: number; };
type StringValue = { kind: 'string'; value: string; };
type Val = NumericValue | StringValue;

type R1 = number | string;
type R2<T extends Val> = T["value"];

function f1(): R1 {
    return 123;
}

function f2(obj: Val): R1 {
    return 123;
}

function f3<T extends Val>(): R2<T> {
    return 123;
}

function f4<T extends Val>(obj: T): R2<T> {
    return 123;
}

const o: Val = { kind: "string", value: "hello" };

const s1: string = f1();  // Error!
const s2: string = f2(o); // Error!
const s3: string = f3();  // Error!
const s4: string = f4(o); // No error!
```
