### ISSUE TITLE
Wrong inferred initial value in reduce

### ISSUE THREAD

**Issue by nop33** [microsoft/TypeScript#59863]
### 🔎 Search Terms

"reduce initial value", "wrong inferred initial value in reduce"

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBGCuBbARgUwE4QILvQQwE8YBeGAbQEYAaGeMAE1QDMBLMVemgJhoGYa6jVu04wArAF0AsAChZAG1Sw2LKCzzyAahvioAXHCRp0JGAAZZs0JFgQkiPOiKkEKDNlyEAdOg7xgqAAUgXjAwDQAbjqoAJQkAHwwAN6yMGkwvlDw6GAwocAwANQwgVHyujAA-JXmMbIAvjQqahra5bFAA

### 💻 Code

```ts
const numbersArray = [1, undefined, 2, 3, undefined, 5]

let initialValue: number = 0

const summary = numbersArray.reduce((acc, value) => {
    return acc + (value ?? 0)
}, initialValue)
```

### 🙁 Actual behavior

`acc` is `number | undefined` instead of `number`

### 🙂 Expected behavior

Since an `initialValue` is provided the type of `acc` should be inferred from it and not from the first element of the `numbersArray`.

> A value to which accumulator is initialized the first time the callback is called. If initialValue is specified, callbackFn starts executing with the first value in the array as currentValue.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

> **How does TypeScript infer the type of the accumulator in reduce()?**
TypeScript infers the type of the accumulator based on the initial value provided (if any) and the return type of the reducer function. If no initial value is provided, it infers the type from the first element of the array.
https://www.geeksforgeeks.org/typescript-array-reduce-method/

**Comment by MartinJohns** [comment]
I believe this is working as intended.  `reduce()` has several overloads, and the one used does not have an additional type argument for the `initialValue` because the provided value is compatible with your array type.

A workaround is to explicitly choose the overload with the type argument by providing it: `numbersArray.reduce<number>(...)`
