### ISSUE TITLE
Error out if using node builtin modules and global variables in browser environment

### ISSUE THREAD

**Issue by croraf** [microsoft/TypeScript#59873]
### 🔍 Search Terms

NodeJS, Browser, built-in modules, global variables, @types/node, references

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Allow user to specify "browser" environment, an environment that won't have NodeJS built-in modules and global variables.

This means that if the user tries to import such module, or use NodeJS built-in global variable, they will get an error.

### 📃 Motivating Example

Currently if @types/node are installed such imports and global variables are available to the user. Removing @types/node is not always possible as it might be needed elsewhere.

For example I want to have a file (build script) that should have access to NodeJS stuff.
While the rest of the project shouldn't have access to that.

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": [ "ES2020", "DOM", ],
    "module": "ESNext",
  },
  "include": [ "src" ],
  "references": [ { "path": "./tsconfig.node.json" } ]
}
```

tsconfig.node.json
```
{
  "compilerOptions": {
    "module": "ESNext",
  },
  "include": [ "vite.config.ts" ]
}
```

**Comment by RyanCavanaugh** [comment]
You can set `"types": []` in your tsconfig to prevent the Node globals from showing up

Unintentionally importing a node type is the kind of thing that should be addressed by lint rules and such. TypeScript doesn't have any built-in understanding of what "node" even is; it's just another .d.ts that can be imported.
