### ISSUE TITLE
Dangerous Property Initializers in Classes

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#5987]
This is [valid](http://www.typescriptlang.org/Playground#src=class%20One%20%7B%0A%09two%28%29%20%7B%7D%3B%0A%7D%0A%0Aclass%20Foo%20%7B%0A%09two%20%3D%20this.one.two%28%29%3B%0A%09one%20%3D%20new%20One%28%29%3B%0A%7D%0A), but seem very dangerous:

``` typescript
class One {
    two() {};
}

class Foo {
    two = this.one.two();
    one = new One();
}
```

The emit goes in order of declaration which will cause a runtime error:

``` javascript
var One = (function () {
    function One() {
    }
    One.prototype.two = function () { };
    ;
    return One;
})();
var Foo = (function () {
    function Foo() {
        this.two = this.one.two();
        this.one = new One();
    }
    return Foo;
})();
```

**Comment by kitsonk** [comment]
I suspect this got lost in the pile.  Any thoughts, or is it just and edge case that isn't worth bothering with?

**Comment by DanielRosenwasser** [comment]
Sorry about that, this past month's been busy and naturally some people are out.

I wonder if this should fall under the umbrella of #2234.

**Comment by kitsonk** [comment]
Clearly it is related to #2234, but I would suspect a lot of users would be "surprised" that they have to think about the ordering of a property initializers in a class, although I just checked the ES Stage 1 proposal for [class properties and initializers](https://github.com/jeffmo/es-class-fields-and-static-properties#instance-field-initialization-process) and it appears that this would break there too, so the emit is valid.  In that case, stupid is as stupid does and it would logically fall in the realm of use before initialization.

cc/@adidahiya

**Comment by RyanCavanaugh** [comment]
"Order of emit is order of declaration" is a must-have behavior for ES6 compat.

I don't see why we wouldn't error here, though. We can treat these as if they were `let` declarations in terms of TDZ rules.

**Comment by theseyi** [comment]
@kitsonk Thoughts?

**Comment by kitsonk** [comment]
I don't know if it is similar.  It is valid, though illogical.  My opinion would be that it should be an error as well (sort of the same class as use before assigned).

**Comment by JoshuaKGoldberg** [comment]
The original code now correctly gives a type checking error! ✨

```ts
class One {
    two() {};
}

class Foo {
    two = this.one.two();
               ~~~ // Property 'one' is used before its initialization.ts(2729)
    one = new One();
}
```

However, `x: any = this.x;` is still allowed but shouldn't be.

**Comment by chriskrycho** [comment]
Hey folks, the Ember TS crowd just noted an issue with the PR that closed this; see my comment [here](https://github.com/microsoft/TypeScript/pull/29395#issuecomment-497376445).
