### ISSUE TITLE
Understanding type checker cache

### ISSUE THREAD

**Issue by JesusTheHun** [microsoft/TypeScript#59878]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I've written a library that offers complex types, the in-editor performance used to be very poor (> 2sec to get autocompletion). While looking at the trace and the output of  `--extendedDiagnostics`, I noticed more than 4M+ instantiations. So I've started to dive deep down the performance of the lib and through many optimizations I managed to lower the instantiations to about 1.4M and autocompletion to something that feels ~200ms.

1.4M instantiations still feels quite high though, compared to other lib I've written, admittedly less complex.

So my question focuses on in-editor performance more than type-checking during build.

1. Is there a way to measure improvement made on cache usage ? I assume `--extendedDiagnostics` will show less instantiations, right ? The check time can vary quite a bit, making it difficult to know if we are moving in the right direction.

2. Given the following :

  ```ts
type Arg1 = { title: string };
type Arg2 = { title: string };

type AsArray<T> = T extends unknown ? [T] : never;

type Result1 = AsArray<Arg1>;
type Result1bis = AsArray<Arg1>;
type Result2 = AsArray<Arg2>;
```

Will the cache be used to evaluate `Result1bis` ? What about `Result2` ? It's a different alias but it's exactly the same type.
  I've read a bit of the compiler cache source code and I think it uses the type alias id so I would guess cache is used for `Result1bis` because it's the same type alias, but cache would not be used for `Result2`.

3. What about in a nested, conditional type ?

```ts
type Describe<T> =
  T extends string ? `string: ${T}` :
    T extends number ? `number: ${T}` :
    `unknown`
;

type DescribeAll<T> = T extends readonly [infer A] ? Describe<A> : never;

type Result1 = DescribeAll<['hi']>;
type Result2 = DescribeAll<[3, 'hi']>;
```

In this scenario, will the cache be used when evaluating `Result2` ? `Describe<'hi'>` has already been evaluated before for `Result1`, so that step uses cache, right ?

4. Is there any particular condition that would prevent hitting the cache ?

**Comment by RyanCavanaugh** [comment]
> Is there a way to measure improvement made on cache usage ? I assume --extendedDiagnostics will show less instantiations, right ?

Correct; the counts here are a good proxy for how much work is being saved/not-saved

> Will the cache be used to evaluate `Result1bis` ? What about `Result2` ? It's a different alias but it's exactly the same type.

There's no interning of "identical" object types, so computations on `Arg1` and `Arg2` will be independent (literal types *are* interned). Identical instantiations are cached, so `Result1` and `Result1bis` will point to the same type.

> In this scenario, will the cache be used when evaluating Result2 ? `Describe<'hi'>` has already been evaluated before for Result1, so that step uses cache, right ?

Yes (because literal types are interned)

> Is there any particular condition that would prevent hitting the cache ?

This is pretty vague; I don't know how to give a useful answer

**Comment by JesusTheHun** [comment]
> Yes (because literal types are interned)

So the following wouldn't hit the cache because the type arguments are objects ?

```ts
type Result3 = DescribeAll<[{ title: string }, { tags: string[] }]>;
```

> This is pretty vague; I don't know how to give a useful answer

For example, for tail recursive evaluation to take place, the following conditions need to be met :

> We tail-recurse for generic conditional types that (a) have not already been evaluated and cached, and
(b) are non distributive, have a check type that is unaffected by instantiation, or have a non-union check
type. Note that recursion is possible only through aliased conditional types, so we only increment the tail

**Comment by JesusTheHun** [comment]
Come on @typescript-bot ! Unlike you, humans need to rest !

For the following code, the number of instantiation increases by 4 each type I compute `AsArray<Arg1>`. 

```ts
type Arg1 = { title: string };

type AsArray<T> = T extends unknown ? [T] : never;

type Result1 = AsArray<Arg1>; // Instantiations : 4
type Result2 = AsArray<Arg1>; // Instantiations : 8
type Result3 = AsArray<Arg1>; // Instantiations : 12
```

I expected the number of instantiation to stay exactly the same, but apparently the evaluation it's not skipped entirely.
So I ran the following :

```ts
type Describe<T> = T extends string
  ? `string: ${T}`
  : T extends number
    ? `number: ${T}`
    : `unknown`;

type DescribeAll<T extends ReadonlyArray<unknown>> = T extends [infer A, ...infer Rest]
  ? Describe<A> | DescribeAll<Rest>
  : never;

// 29 instantiations

type Result1 = DescribeAll<['hi']>; // + 42 (71)
type Result2 = DescribeAll<['hi']>; // + 13 (84)
type Result3 = DescribeAll<['hi']>; // + 13 (97)
type Result4 = DescribeAll<['John']>; // + 22 (119)
type Result5 = DescribeAll<['Doe']>; // + 22 (141)

type Obj = { title: string };
type Obj2 = { title: string };

type Result6 = DescribeAll<[Obj]>; // + 22 instantiations (163)
type Result7 = DescribeAll<[Obj]>; // + 15 instantiations (178)
type Result8 = DescribeAll<[Obj2]>; // + 22 instantiations (200)
```

So it looks like some things are cached. The first call to `DescribeAll` triggers `42` instantiations while subsequent calls with the same parameter cost only `13`. Calls with a new string parameter cost `22` so I guess out of the `42` instantiations required to evaluate the type, 13 can't ever be cached, and 9 needs to be evaluate for each new parameter met.

**Comment by RyanCavanaugh** [comment]
> So the following wouldn't hit the cache because the type arguments are objects ?

Correct, type literals will get their own ID and thus be a cache miss.

At the level of analysis you're doing here, I'd recommend setting a few breakpoints in tsc and stepping through it. It'll be much more instructive (and accurate!) than my prose.

**Comment by alecmev** [comment]
@JesusTheHun Have you looked further into this? Have you figured out why the `AsArray` example results in new instantiations? I tested a similar piece of code, but with `Partial<Arg1>` instead of `AsArray<Arg1>`, and its instantiation counter remained constant.

**Comment by JesusTheHun** [comment]
@alecmev with TypeScript 5.4.5, it results in a constant number of instantiations 👌
