### ISSUE TITLE
electron-node.js is consuming so much memory and cpu and intellisense becomes slow because of this.

### ISSUE THREAD

**Issue by devhik0** [microsoft/TypeScript#59906]
Type: <b>Performance Issue</b>

Open a .tsx or .ts file and check performance results via Process Explorer.

VS Code version: Code - Insiders 1.90.0-insider (81c89c4d00663e1718871bab2f9bf2064a060b63, 2024-05-22T09:31:22.258Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.27GB free)|
|Process Argv|--crash-reporter-id 4696966f-1613-4508-bab7-54b015895995|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   104	  2908	code-insiders main
    1	   124	  1304	   gpu-process
    0	   137	  2272	extensionHost [1]
    0	   224	  2288	     electron-nodejs (tsserver.js )
    0	    86	  4440	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    86	  9732	     "C:\Users\aydin\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\aydin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=2272
    0	   113	 12220	     electron-nodejs (tsserver.js )
    0	   169	 14360	     electron-nodejs (eslintServer.js )
    0	    85	  2788	ptyHost
    0	     7	 13848	     conpty-agent
    0	     5	 13872	     "C:\Program Files\Git\bin\bash.exe" --login -i
    0	    11	  8476	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe" --login -i
    0	   105	  5472	window [2] (Process Explorer)
    0	    79	  5576	fileWatcher [1]
    0	    28	  6672	   crashpad-handler
    1	   102	  6696	shared-process
    0	    40	  9276	   utility-network-service
    0	   223	 15544	window [1] (task-kanban.tsx - client-app - Visual Studio Code - Insiders)
    2	    96	 16116	window [3] (Issue Reporter)
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-eslint|dba|2.4.4
prettier-vscode|esb|10.4.0
material-icon-theme|PKi|5.3.0
vscode-yaml|red|1.14.0

(1 theme extensions excluded)

</details>

**Comment by RyanCavanaugh** [comment]
Please disable any plugins/extensions you have and check again. It looks like the `next` VS Code plugin is enabled and can cause delays.

**Comment by theMasix** [comment]
same here.
