### ISSUE TITLE
Iterator Helpers Typing

### ISSUE THREAD

**Issue by nikolaybotev** [microsoft/TypeScript#59908]
### ⚙ Compilation target

ESNext

### ⚙ Library

lib.esnext.d.ts

### Missing / Incorrect Definition

global Iterator class

### Sample Code

```TypeScript
Iterator.from([1, 2, 3, 4, 5])
  .map(n => n + 1)
  .filter(n => n > 2)
  .drop(1)
  .take(2)
  .toArray() // [4, 5]
```

See also all the validation tests (working since Node.js 22.0.0) at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helpers

However, the following code should (ideally) continue working:

```
const customIterator: Iterator<number> = { next: () => ({ value: 42 }) };
```

### Documentation Link

* TC39 Proposal: https://github.com/tc39/proposal-iterator-helpers
* MDN Documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helpers

**Comment by nikolaybotev** [comment]
How are you guys going to handle the new `Iterator` class introduced in the Iterator helpers proposal?

The methods of this class, if introduced as a TypeScript `class` declaration will merge with the pre-exisiting `Iterator` interface (that describes the Iterator protocol) and break all code that uses the `Iterator` type to describe custom iterators.

This could be an uncommon occurrence, and it might be acceptable to rename the `Iterator` interface to `IteratorProtocol`.

Have you guys given this any consideration?

**Comment by nikolaybotev** [comment]
See a clear demonstration of the problem here: https://github.com/nikolaybotev/DefinitelyTyped/pull/1/files

**Comment by Josh-Cena** [comment]
Isn't this just a rehash of https://github.com/microsoft/TypeScript/issues/54481, in which it was decided that `Iterator` would refer to different things in type space and value space (that is, `Iterator()` does not return you an object of type `Iterator`, but of type `BuiltinIterator`?)

**Comment by nikolaybotev** [comment]
The downside with the approach taken in #58222 is that by maintaining backwards compatibility, new typing information is omitted / incorrect and can result in both working code failing type validation and failing code passing type validation.

1. `instanceof Iterator` will not expose the Iterator Helpers to users:

Have you considered this?

```
let it: object;

if (it instanceof Iterator) {
  it.toArray(); // this should work!
}
```

2. The absence of the `next` etc methods of iterator protocol from the Iterator class (which should ideally be defined as abstract in typescript which is not possible due to the Iterator interface from es2015 holding up that name):

```
class IncompleteIterator extends Iterator {
  constructor() { super(); }
}

const it = new IncompleteIterator();

it.next(); // Uncaught TypeError: it.next is not a function, but accepted by TypeScript
```

Was it a conscious decision to pay this price to maintain backwards compatibility? 

Is this going to be mentioned in the release notes for TS6, which is where I assume this lands?

**Comment by nikolaybotev** [comment]
Nevermind, I see that both of the above examples are handled correctly with the new type definitions...
