### ISSUE TITLE
URLs in comments don't get their fragment parts

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5990]
![image](https://cloud.githubusercontent.com/assets/937933/11660184/f2c55416-9d99-11e5-86f1-6a3575c1f1ed.png)

**Comment by mhegazy** [comment]
i am assuming this screenshot is from VS. if so, this a VS feature that TypeScript really has no hand in. you might find this helpful: https://github.com/Microsoft/TypeScript/issues/3952#issuecomment-123497591
