### ISSUE TITLE
TypeScript Generates Syntactically Invalid JS (tsx)

### ISSUE THREAD

**Issue by JKillian** [Microsoft/TypeScript#5991]
If you compile this code with `jsx: 'React'`:

```typescript
const class1 = "foo";
const class2 = "bar";
const elem = <div className={class1, class2}/>
```

the code compiles without warning but produces invalid JS. (Note that this is targeting ES5, so object literal shorthand declarations are not available. And even if they were, then the generated code would be semantically different.)

```js
var class1 = "foo";
var class2 = "bar";
var elem = React.createElement("div", {"className": class1, class2});
```

Although `className={class1, class2}` is probably seldom intended, it seems to me that it should be valid TS. Thus I think the generated output should be:

```js
var class1 = "foo";
var class2 = "bar";
var elem = React.createElement("div", {"className": (class1, class2)});
```

**Comment by RyanCavanaugh** [comment]
I agree we should parenthesize the output.

Thinking about the original testcase... should this be an error? It seems vastly more likely the author thinks they're writing a shorthand object literal there.

**Comment by JKillian** [comment]
In my case, I meant to wrap my arguments in a function call, `className={classNames(class1, class2)}`. What you suggested seems like it would be an even more common error: `prop={prop1, prop2}` instead of the intended `prop={{prop1, prop2}}`.

Still, the comma operator is a well-defined part of JS, and it seems constraining to disallow the syntactically _valid_ `prop={prop1, prop2}`. I think this comes down to the philosophy of tsc: should the compiler warn for valid but almost certainly unintended constructs? My personal opinion is no by default but yes with some sort of "warnings/pedantic" mode flag.

I know there's an unreachable code detection feature in the pipeline - I feel that it does the same thing: warns about valid but most likely unintended code. So I'd probably expect this to behave the same way as that feature does. (Although this is obviously a smaller scope thing.)

**Comment by RyanCavanaugh** [comment]
According to the JSX spec, this is invalid code:

https://facebook.github.io/jsx/
> 
JSXAttributeValue :
> " JSXDoubleStringCharactersopt "
> ' JSXSingleStringCharactersopt '
> { AssignmentExpression }
> JSXElement

Comma operator is not a valid `AssignmentExpression`, so this code simply should not parse.

**Comment by JKillian** [comment]
Ah, good call on that one @RyanCavanaugh, I hadn't looked at the JSX spec or realized that. Agreed that the result should just be a compiler error then. :+1:
