### ISSUE TITLE
The function type should not inherit the built-in object type

### ISSUE THREAD

**Issue by guaijie** [microsoft/TypeScript#59938]
### 🔎 Search Terms

"object type", "exlude function type", "typeof Function instance is 'function'"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ___object______

### 💻 Code

```ts
typeof new Map() // return 'object' for map
typeof [] //  return 'object' for array
typeof {} // return 'object' for plain object
typeof new Set() // return 'object' for set

type (() => {}) // return 'function' for function
```
In summary, the function type should not inherit the object type

### 🙁 Actual behavior

```ts
type A = Function extends object ? 1 : 2  // 1
```

### 🙂 Expected behavior

```ts
type A = Function extends object ? 1 : 2  // 2

const isObject = (value: unknown): value is object =>
  value !== null && typeof value === 'object'

type A = { prop: string} | () => void | undefined

const a: A = {prop: 'prop'}

const b = isObject(a) ? () => a : a // b is Function or undefined

```

**Comment by jcalz** [comment]
This isn't a bug. The [TS `object` type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#object-type) intentionally means "a non-primitive value". Functions are objects, not primitives. So they are assignable to `object`.  The fact that the [JS `typeof` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) does or does not return a particular string for a value isn't really indicative on what the [TS `typeof` operator](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html) does for the same value:

```ts
const a = "a";
console.log(typeof a); // "string"
type A = typeof a; // "a" (not string)

const b = null;
console.log(typeof b); // "object"
type B = typeof b; // null (not object)

const c = new Date();
console.log(typeof c); // "object"
type C = typeof c; // Date (not object)
```
[Playground link](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAhjAvDARHFBuAUFAngBwFMYBBJGPIkAM3gxgHoHV0tRIQAbQgOk5ADmACkqEa8AJSNmKaACcAlmAEosbcNBgAjcmACunTtlEwAQuVHit9JjH2H1Hbn0EiCY2lok2ZILQCtCYChVR01gXUIAdxgAETgoQiFvHHcYAGELd3FgHziEwjCuXn5hS1pgb2lUP0Dg0KA)

Maybe it would be nice for there to be a type like "a non-function object" in TypeScript, but that sounds like a feature request, not a bug report.

**Comment by RyanCavanaugh** [comment]
Also worth noting that
```js
function f() { }
f instanceof Object // <- true
```
