### ISSUE TITLE
Types as Values (Symbols?)

### ISSUE THREAD

**Issue by titouandk** [microsoft/TypeScript#59943]
### 🔍 Search Terms

Types as Values Symbols

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Could TypeScript eventually compile types/interfaces to Symbols, when used as values?

I think this could be useful to link a type to one particular value (dependency injection by example) :

```ts
const instance: T = {method: () => true }

container.register(T, instance) // replace T by a reference to a TS generated symbol
```

(Would it be considered a runtime feature?
Looks more like a build-step, pre-processor like operation to me.)

### 📃 Motivating Example

See above.

### 💻 Use Cases

See above.

**Comment by xiBread** [comment]
This is a runtime feature.

> non-ECMAScript syntax with JavaScript output

**Comment by titouandk** [comment]
Isn't this an ECMAScript compatible syntax, strictly speaking?

For the moment, this code would raise a ReferenceError when accessing T (you can catch it), and not a SyntaxError (you cannot).

Am I going too far? Heheh...
