### ISSUE TITLE
Function parameter type inference error

### ISSUE THREAD

**Issue by lengyuxuan** [microsoft/TypeScript#59949]
### 🔎 Search Terms

Function parameter

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/zh/play/?#code/KYOwrgtgBAKgngB2FA3gWAFBSgQQDSbYBCBGAvppgJYgAuwATgGYCGAxsvEgLIsKqEoAbS7AAdDgC6ALigBnWgxoBzANyCRicURlRwEAEaN15ShlpaoADQA8MKMAAe9EABM5sLQD4oAXmyivAgikiaYTGAgbLRUAPYgUBFRdg7OoO6eSF4AFBZIsjB4qS6usrYwXgCUAlhQVExQuZa+LZniONXotdgA9D1QAOoAFnBQAEROJWNQechUHiCxtPKKKlAA-IK9-dkILAwsEMD0DNWT6bIKSiDKUAA+epBGDPdQBrGxADbALCBbUGx4nIvuJPrFlE0kEVzm5KiZsBRTBhwpE2NlRBIigByLFwlFRdFaMQkKAARjhQA

### 💻 Code

```ts
enum Type {
  A,
  B,
}

interface TypeMap {
  [Type.A]: string;
  [Type.B]: number;
}

type X<T extends Type> =  TypeMap[T];

function func<T extends Type>(type: T, extend: X<T>) {
  if (type === Type.A) {
    // Why "extend" type is not string ?
    // (parameter) extend: string | number | boolean
    console.log(type, extend);
  }
}

func(Type.A, '');
func(Type.B, 1);
```

### 🙁 Actual behavior

In the example， Why "extend" type is not string ?

### 🙂 Expected behavior

The "type" constrained to "Type.A"，so "extend" shuld be "string".

**Comment by MartinJohns** [comment]
Because checking what value `type` is does not have any relevance for what type the value of `extend` is.

This is a perfectly valid call: `func<Type.A | Type.B>(Type.A, 1);`

**Comment by lengyuxuan** [comment]
> Because checking what value `type` is does not have any relevance for what type the value of `extend` is.
> 
> This is a perfectly valid call: `func<Type.A | Type.B>(Type.A, 1);`

How should I constrain the type of "extend" ? Do you have any suggestions ? Thank you so much !

**Comment by jcalz** [comment]
Duplicate #33014

For now, if you need this behavior you either need to rewrite in terms of #47109 and use generic indexing instead of control flow anlaysis:

```ts
function func<T extends Type>(type: T, extend: X<T>) {
    const x: { [K in Type]: (type: K, x: X<K>) => void } = {
        [Type.A](type, extend) {
            console.log(type, extend);
            //                ^? (parameter) extend: string
        },
        [Type.B](type, extend) {

        }
    }
    x[type](type, extend);
}
func(Type.A, '');
func(Type.B, 1);
func(Math.random() < 0.99 ? Type.A : Type.B, 1); // still allowed, #47109 technically unsound this way
```

or, you need to use control flow analysis on a discriminated union and not use generics:


```ts
function func(...[type, extend]: { [T in Type]: [type: T, extend: X<T>] }[Type]) {
    if (type === Type.A) {
        console.log(type, extend);
        //                ^? (parameter) extend: string
    }
}

func(Type.A, '');
func(Type.B, 1);
func(Math.random() < 0.99 ? Type.A : Type.B, 1); // error
```
[Playground link to code](https://www.typescriptlang.org/play/?noErrorTruncation=true#code/HYQwtgpgzgDiDGEAEBxCwICcCW8Ca0AwgPbAAumxANgGJXEDuAgqFQJ5TZQByxSA3gCgkIpOgCuYJABU2MZENFKkTADTDlIgELqlAX0EaR2clgBmCZLPkBZEDAFHlAbWsQAdEwC6ALiRQKEwBzAG4nJVc5Dy1fJGBJACMsMP1DJTIopAANAB5pMQAPMnQAEygZKIA+JABeCtt7Vy8wpzNxYHgybFIkNo68wuLgMvqISoAKDPk-aVVB0r9c6UqASkdNEXhSAKQCv34kZwBpJBNR2MmovyO5veyco9Xa6oA3YmwSpD1a9Y2It08Xku8jmECKpTWij+Gy2wCg1A89CCwIgoPBwxWKWhmgA9DjsZoAHoAfiQ4zgmHAEGKmDWYKGJT8ARwwCC4Q2el0BMi8ncMRRaIZkLSBIMfzFGwKzimECBMsFEKxIgMrXa8HGALUSAA5NrMaqOhqony5gBGfVKPrquxkAAW7kpw2IYHGaxySAADO4AJzepCkzVIGbGnRIc0hJB4-xdKhUJAgWOMCAlQQq0CQWCWVDoLC4XgkciUWj0ZisDhcAjlKEiCRSNy-TRqdnaLnKkXGUyYCyIUZ2BzVlya2LM4JKwch2LxMBJTBjlVOGX3fL00rlNzVOpuPtNFqWtVdHpW8buE-SqIK4axA6uU7Ac5+M-TGQXxlLypeL482XCv7YMxkxcaiA0ZPB-AlYXhKhEWIZF5XmDExz+KMCSUEkyQpKkaTpdFXxHVlmy+JwVT3Q1NTmXULVEI8AVDcMDWtEA7QdEAnRdN1PR9P0A2NJggxA2jMUjfEsEoTBUyAA)

**Comment by lengyuxuan** [comment]
> Duplicate #33014
> 
> For now, if you need this behavior you either need to rewrite in terms of #47109 and use generic indexing instead of control flow anlaysis:
> 
> ```ts
> function func<T extends Type>(type: T, extend: X<T>) {
>     const x: { [K in Type]: (type: K, x: X<K>) => void } = {
>         [Type.A](type, extend) {
>             console.log(type, extend);
>             //                ^? (parameter) extend: string
>         },
>         [Type.B](type, extend) {
> 
>         }
>     }
>     x[type](type, extend);
> }
> func(Type.A, '');
> func(Type.B, 1);
> func(Math.random() < 0.99 ? Type.A : Type.B, 1); // still allowed, #47109 technically unsound this way
> ```
> 
> or, you need to use control flow analysis on a discriminated union and not use generics:
> 
> ```ts
> function func(...[type, extend]: { [T in Type]: [type: T, extend: X<T>] }[Type]) {
>     if (type === Type.A) {
>         console.log(type, extend);
>         //                ^? (parameter) extend: string
>     }
> }
> 
> func(Type.A, '');
> func(Type.B, 1);
> func(Math.random() < 0.99 ? Type.A : Type.B, 1); // error
> ```
> 
> [Playground link to code](https://www.typescriptlang.org/play/?noErrorTruncation=true#code/HYQwtgpgzgDiDGEAEBxCwICcCW8Ca0AwgPbAAumxANgGJXEDuAgqFQJ5TZQByxSA3gCgkIpOgCuYJABU2MZENFKkTADTDlIgELqlAX0EaR2clgBmCZLPkBZEDAFHlAbWsQAdEwC6ALiRQKEwBzAG4nJVc5Dy1fJGBJACMsMP1DJTIopAANAB5pMQAPMnQAEygZKIA+JABeCtt7Vy8wpzNxYHgybFIkNo68wuLgMvqISoAKDPk-aVVB0r9c6UqASkdNEXhSAKQCv34kZwBpJBNR2MmovyO5veyco9Xa6oA3YmwSpD1a9Y2It08Xku8jmECKpTWij+Gy2wCg1A89CCwIgoPBwxWKWhmgA9DjsZoAHoAfiQ4zgmHAEGKmDWYKGJT8ARwwCC4Q2el0BMi8ncMRRaIZkLSBIMfzFGwKzimECBMsFEKxIgMrXa8HGALUSAA5NrMaqOhqony5gBGfVKPrquxkAAW7kpw2IYHGaxySAADO4AJzepCkzVIGbGnRIc0hJB4-xdKhUJAgWOMCAlQQq0CQWCWVDoLC4XgkciUWj0ZisDhcAjlKEiCRSNy-TRqdnaLnKkXGUyYCyIUZ2BzVlya2LM4JKwch2LxMBJTBjlVOGX3fL00rlNzVOpuPtNFqWtVdHpW8buE-SqIK4axA6uU7Ac5+M-TGQXxlLypeL482XCv7YMxkxcaiA0ZPB-AlYXhKhEWIZF5XmDExz+KMCSUEkyQpKkaTpdFXxHVlmy+JwVT3Q1NTmXULVEI8AVDcMDWtEA7QdEAnRdN1PR9P0A2NJggxA2jMUjfEsEoTBUyAA)

Good job
