### ISSUE TITLE
Narrow types with boolean literal discriminants

### ISSUE THREAD

**Issue by NAlexPear** [microsoft/TypeScript#59944]
### 🔍 Search Terms

boolean discriminant truthiness

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When narrowing the type of a union of Objects that include a boolean literal, we should be able to use truthiness checks against that boolean field to narrow the type of the union.

### 📃 Motivating Example

```ts
type Success = { success: true } | { success: false, error: string }
const result = { success: true } as Success

if (!result.success) {
  console.log(result.error) // Property 'error' does not exist on type '{ success: true; }'
}

if (results.success === false) {
  console.log(result.error) // compiles fine because of the boolean literal comparison
}
```

### 💻 Use Cases

1. What do you want to use this for?

    This :point_up: pattern is pretty common in a codebase that doesn't want to `throw` anywhere, and prefers an explicit `success` field. 

3. What shortcomings exist with current approaches?

    The truthiness check is intuitive in JS, and unnecessarily clunky in TS. In theory, this specific case of truthiness type narrowing should allow for narrowing to the boolean type literal.

5. What workarounds are you using in the meantime?

    Explicit boolean literal comparisons as described in the motivating example.

**Comment by MartinJohns** [comment]
This already works with `strictNullChecks` enabled, and with `strictNullChecks` disabled it wouldn't be valid because `null` and `undefined` are valid values in both union cases.

**Comment by NAlexPear** [comment]
Thanks @MartinJohns, that did exactly what I was looking for :+1:
