### ISSUE TITLE
Organize imports preferences don't seem to work

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#59942]
### 🔎 Search Terms

- Organize imports
- Sort imports

### 🕗 Version & Regression Information

5.6, not a regression 

### 💻 Code

1. In VS Code set:
```json
  "typescript.preferences.organizeImports": {
    "caseFirst": "upper"
  },
```

2. Open a TS file:
```ts
import './a';
import './A';
```

3. Run organize imports

### 🙁 Actual behavior

No change

### 🙂 Expected behavior

Should sort imports so upper case comes first?

I confirmed that we send along `"organizeImportsCaseFirst": "upper"` in the `configure` request for the file

None of the other organize imports settings seems to work either

**Comment by grallbring** [comment]
Can comfirm, using the `typeOrder` setting also doesn't seem to work.

```json
"typescript.preferences.organizeImports": {
    "typeOrder": "first"
}
```

Using this setting, type-only imports are not sorted to be first.

**Comment by jakebailey** [comment]
When was this option added? I thought this had to be like: https://github.com/microsoft/TypeScript/blob/460be92510abf07b7fb87e1d2a6649823805e195/.vscode/settings.template.json#L25-L38

**Comment by iisaduan** [comment]
@jakebailey The way they are entered into the non-unstable `typescript` settings is different. They were added to VSCode over the summer (I think August?).

@grallbring In the meantime while I am investigating why the vscode preferences don't work/fixing this issue, specifying the settings under unstable, like mentioned in Jake's comment, should work, and I believe the unstable settings should override any of the non-working settings.

**Comment by grallbring** [comment]
@iisaduan These unstable settings do not seem to have any effect whatsoever.
```json
"typescript.unstable": {
	"typeOrder": "first"
}
```

Using this setting, type-only imports are mixed with the other imports like before.
VS Code also gives me this hint when using the unstable setting:
![Image](https://github.com/user-attachments/assets/0c8049b8-d18c-4732-a854-b57744b1c818)

I'm using version 1.94.2.

**Comment by iisaduan** [comment]
@grallbring The input for the unstable are under different names, since they are directly passed to our `preferences` object. For type order first, this is the setting you should include. You'll also need a tsserver version of >5.4.

```
"typescript.unstable": { 
     "organizeImportsTypeOrder": "first" 
}
```

**Comment by grallbring** [comment]
@iisaduan I see. I've adjusted the setting:
```json
"typescript.unstable": {
	"organizeImportsTypeOrder": "first"
}
```

However, the issue remains.
Is the tsserver version the same as the typescript version my project uses?
I'm using `"typescript": "^5.6.3",`.

**Comment by iisaduan** [comment]
@grallbring It's supposed to apply to only named imports:
```
import { type Router, type T, A, b, y, Z } from "@remix-run/router"; 
```
The order of declarations are sorted by module specifier, and if there are multiple declarations of different specifiers, then we[ tie-break by type of import declaration ](https://github.com/microsoft/TypeScript/blob/e99e6e2e87a6d7f152eb7cc491ce11da1926662b/src/services/organizeImports.ts#L821). IIRC, this ordering is to keep compatibility with ESlint and other formatters.

**Comment by iisaduan** [comment]
@grallbring The tsserver version, by default, is the one that your project uses, but it is possible to specify a different version using the vscode setting `"typescript.tsdk"`
https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript

**Comment by grallbring** [comment]
@iisaduan Understood, then I misunderstood the purpose of the setting. Thanks for the detailed explanation!
