### ISSUE TITLE
`AutoFill` is missing a few valid tokens for the `autocomplete` attribute

### ISSUE THREAD

**Issue by fcrozatier** [microsoft/TypeScript#59955]
### Acknowledgement

- [X] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

The `AutoFill` type of `lib.dom` is missing the following tokens:
- bday
- cc-additional-name
- language
- nickname
- organization-title
- photo
- sex
- url  

https://html.spec.whatwg.org/#autofill-field

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator/

**Comment by fcrozatier** [comment]
Thanks I moved the issue here: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1802
