### ISSUE TITLE
Generic Conditional Type resolved to `any` when passed an error `any` type

### ISSUE THREAD

**Issue by Eazash** [microsoft/TypeScript#59981]
### 🔎 Search Terms

"generic", "conditional type", "is any", "implicit any", "error", "module has no export member"

### 🕗 Version & Regression Information

- This changed between versions 5.4.5 and 5.5.4

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.5.4#code/C4TwDgpgBAkgzgQQHYgDwBUB8UC8UAMUEAHsBEgCZxQCMUAZFOlAPxTABOArtAFxQAzAIYAbOBABQEihADGIoR2gBbAPYUuI6ACI4q5RAC0ajVu1QA3gF8JoSLGVgRAS1nPgyELnbgIqgVDOjqocwAAUuvpGJpoQ2gCUAHQywprAUnbQAEoQcGne8J6oMI4ubh4omBIA9NVQ9Q0AeiwZvlAAosSQsmQUOXkiwAWIKKhClTV19c1AA

### 💻 Code

```ts
type IsAny<T> = 0 extends 1 & T ? true : false

declare module "some-module" {}
type ImplicitAny = typeof import("some-module").default

type Result = IsAny<ImplicitAny> // any

type ExpectedResult = IsAny<any> // true
type ExpectedResult2 = IsAny<{}> // false
```

### 🙁 Actual behavior

The conditional type resolves to `any`

### 🙂 Expected behavior

The conditional type should resolve to either TrueType or FalseType. In this specific example, it should resolve to `true`

### Additional information about the issue

While I was unable to use `every-ts`, after manually bisecting I've foudn that the first release with this buggy behaviour is [5.5.0-dev.20240524](https://www.npmjs.com/package/typescript/v/5.5.0-dev.20240524)

**Comment by Eazash** [comment]
Related to #58960, possible cause outlined here (https://github.com/microsoft/TypeScript/issues/58960#issuecomment-2183887474)

**Comment by lucaimbalzano** [comment]
The problem stems from how TypeScript infers types from modules. If "some-module" exports a default value with any (but the type isn’t explicitly declared), TypeScript might not treat it exactly the same as any.

To resolve this, you should explicitly declare the default export as any in your module. 
Here's how:
1) Explicitly Declare the Module's Default Export as any:
```typescript
declare module "some-module" {
  const _default: any;
  export default _default;
}
```

2) Type Checking with IsAny: Now, when you check IsAny<ImplicitAny>, it should correctly detect the any type:
```typescript
type IsAny<T> = 0 extends 1 & T ? true : false;

type ImplicitAny = typeof import("some-module").default;

type Result = IsAny<ImplicitAny>; // true
type ExpectedResult = IsAny<any>; // true
```

⏯  Here's you can check by ts live-code :
```tsx
// Declare the module "some-module" with an explicit 'any' type for the default export
declare module "some-module" {
  const _default: any;
  export default _default;
}

// A utility type to check if...
```

[Playground Link](https://www.typescriptlang.org/play/?ts=5.5.4#code/PTAEBEFMGMBsEMBOlQBcAWKC2B7AJgK6woBEAzjlpALS6HEmgDuAlhqPAHaiQAeADrBbQ2oAORcAnmLST+KAGY5EaTKDyQF8Iqh4DlqAFAa4SbPiKkKVWhYagA3odChoOTmV0B9DVp0AuDk5JAG5nPX4DdU1tWG9fWNQwgF9DQxBQAEFQAlQWIVRJWXk0HFdMaABrUBYFDmKUABUasnEpMUNCkoBJMkzggB5GgD5QAF5QAAY9VEhOPFaACgBGUAAyUEaASlAAfjREAhRArVgySDD0sABxSF0MFC6UHDqH6L84iKiFREpVc3oVkoNDolhInTkKG6WEEwjY-SKEyeLxqMIMi3IwNsgJIWwAdAkdJcMgBhCrVWriaGwkSoBEyLh4NrBBnIaKzaCzJnwVoSFkQkoAJUgZB041AvQRA2pQlpCOGIVAGVQh0gABpQGQWJxoFCYbL4cEWszpAKUABRAQwLnC0WfCaSwZSBVKsAqo4ankmmQsVoaDlcwxAA)

**Comment by Andarist** [comment]
@Eazash you have already found the other issue about it, this is no different from it. I think it would be best to close this issue to keep the discussion focused in the original thread about this change.

**Comment by Eazash** [comment]
@Andarist In my opinion, there is a difference. The other issue is referring to the  "Unresolved `any`" when a type doesn't exist, and how that exhibits different behavior. This issue is describing how an error any behaves differently from a regular `any`. Unlike unresolved there is no label/comment on hover, yet it breaks the contract of a conditional type. A conditional type by definition should return from either the *true* or *false* branch. By returning `any` it is quietly introducing a third branch.

**Comment by Andarist** [comment]
Both are just the same for the compiler. It still feels to me that you could move this discussion to the other issue and try to advocate there that your use case is different than the one presented there (IMHO it's still the same but that's beyond this argument :P).

As Ryan said there, once you have an error "all bets are off" 😉 

> A conditional type by definition should return from either the true or false branch.

This isn't technically true. Sometimes it returns both :D
```ts
type Test = any extends string ? 1 : 2
//   ^? type Test = 1 | 2
```

**Comment by Eazash** [comment]
@lucaimbalzano The playground I linked to is a simplified version of a downstream bug (see nuxt/nuxt#29021). The intention was to show that the implicit `any` created from an "No export error" changes the behaviour of the conditional type. 

> If "some-module" exports a default value with any (but the type isn’t explicitly declared), TypeScript might not treat it exactly the same as any.

In this scenario, "some-module" does not have default exports. Also "some-module" would be any number of third-party modules, explicitly defining `any` is not an option

@Andarist 
>This isn't technically true. Sometimes it returns both :D

Thank you, I stand corrected. However, the bug still persists for a conditional like `type IsTwo<T> = T extends 2 ? true : false` and `IsTwo<ImplicitAny>` is supposed to be a boolean but becomes `any` (see this [playgroud](https://www.typescriptlang.org/play/?ts=5.5.0-dev.20240523#code/C4TwDgpgBAkgzgFQO4HsA8CB8UC8UFQQAewEAdgCZxQBMUA-FMAE4Cu0AXFAGYCGANnAgAoYRQgBjfr2bQAtigqt+0AERwUciAFoFSlaqgBvAL7DQkWHLD8AlhNvAAgmRC4m4CCm5Rb1lMzAABTqmjp6yhCqAJQAdOJ8ysCiFtAAShBwSe7wyOgw1nYOzq6YwgD05VDVNQB69KKVUC5uErxkUABG0J0owAAWADRM-azU3RKatmQA5l0oKCrt5p5QAKJEkBKkFBlZ-MA5iKho7SBlTdX1K5YbWzt7SXR4uSc0F1VX9EA))

**Comment by RyanCavanaugh** [comment]
The propagating behavior of the error `any` is intentional, so that when you have one type error, it doesn't result in (potentially) tens of thousands of downstream errors.

You should write this instead if you'd prefer the other behavior
```ts
type PossibleDefault<T> = T extends { default: infer U } ? U : any;
type ImplicitAny = PossibleDefault<typeof import("some-module")>;
```
