### ISSUE TITLE
Typescript v5.6.2 resulting in "Overload signatures must all be optional or required." on alpine linux arm64

### ISSUE THREAD

**Issue by Pranav2612000** [microsoft/TypeScript#59982]
### 🔎 Search Terms

"Overload signature must all be optional", "error TS2386"

### 🕗 Version & Regression Information

- This changed between versions 5.6.2 and earlier versions

### ⏯ Playground Link

-

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

`tsc` threw an error when trying to compile node types

```
node_modules/@types/node/module.d.ts(107,13): error TS2386: Overload signatures must all be optional or required.
```

### 🙂 Expected behavior

`tsc` should have been able to compile correctly but threw an error

### Additional information about the issue

This worked when downgrading typescript to `5.1.6`

**Comment by zyhou** [comment]
Same issue here, the solution is to update @types/node dependency to a compatible version

related -> https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70562 and https://github.com/microsoft/TypeScript/pull/59259#issuecomment-2228833941

**Comment by hisashiyamaguchi** [comment]
I have the same issue. Any workarounds?

$ npx tsc --version
Version 5.8.3

**Comment by AngularIsAwfull** [comment]
@hisashiyamaguchi , updating `@types/node` to a compatible version of node <-> typescript fixed this issue for me. I hope this helps!
