### ISSUE TITLE
File watching is registering thousands of redundant watchers

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#59984]
### 🔎 Search Terms

file watcher performance efficiency watching events

### 🕗 Version & Regression Information

I am not sure when this changed, but ever since `typescript.tsserver.experimental.useVsCodeWatcher` was added it becomes more visible now, at least to me as owner of the file watcher component in VS Code.

### ⏯ Playground Link

https://github.com/Microsoft/vscode/

### 🙁 Actual behavior

When you open `vscode` repository (https://github.com/Microsoft/vscode/) and open a TS file (e.g. `vs/base/strings.ts`) and wait a bit until the TS/JS language service has settled, notice how there are the following recursive file watchers:
* `node_modules`
* `src/vs`
* `src/@bpasero`, `src/node:vm`, `src/fs`,... (actually `83` more for each and every module we depend on, these folders do not exist on disk)

And then there are `>4000` (!) requests for non-recursive files for pretty much every single TS file in the project (for example `src/vs/base/browser/ui/menu/menu.ts`).

![Image](https://github.com/user-attachments/assets/c6382dc8-768d-4b4b-9d72-353dd0389793)

### 🙂 Expected behavior

A lot less requests for watching:
- all of the thousands of non-recursive watch requests are obsolete given you watch `src/vs` already recursively
- paths like `src/fs` are made up and do not exist, I am not even sure how it would make sense to watch `src/<node module>`?

### Additional information about the issue

Here is how you can see the data:
* after you have opened `vscode` and a TS file, select "Set Log Level" and pick "Trace" from the command picker
* in the output panel, select the "File Watcher" channel
* you should see output like this:

```
[File Watcher] request stats:

[Summary]
- Recursive Requests:     total: 89, suspended: 85, polling: 2
- Non-Recursive Requests: total: 4344, suspended: 50, polling: 0
- Recursive Watchers:     total: 4, active: 4, failed: 0, stopped: 0
- Non-Recursive Watchers: total: 4294, active: 10, failed: 1, reusing: 4283
- I/O Handles Impact:     total: 16
```

//cc @sheetalkamat @DanielRosenwasser

**Comment by sheetalkamat** [comment]
This is by design since we want accurate information on some of the watches which are watched specifically and are watched using "watchFile" and then some we have more room for file addition and removal which we are watched as "directory". 
Client can decide to deduplicate these.

**Comment by bpasero** [comment]
> Client can decide to deduplicate these.

Can you please explain? To my knowledge node.js does not deduplicate watch requests. 

In VS Code I think this issue is now somewhat mitigated with the watcher service re-using recursive watchers if present for all these requests, but how does this behave in other editors such as VS?

**Comment by sheetalkamat** [comment]
we do not deduplicate as node.js events are not reliable and hence the distinction.  Its upto client on what they want to deduplicate. We expect to receive events on both watchers (eg one watched by "watchFile" - to watch specific location and "watchDirectory" ) for correct behaviour
