### ISSUE TITLE
Built-in URL is not compatible with `@types/node` URL

### ISSUE THREAD

**Issue by noahbald** [microsoft/TypeScript#59996]
### ⚙ Compilation target

es6

### ⚙ Library

lib.dom.d.ts

### Missing / Incorrect Definition

I get an error after updating from `5.5.4` -> `5.6.2` because the builtin URL is not longer compatible with node's URL. This is problematic because the builtin URL and node's URL are often used interchangeably.
Even if their types aren't strictly the same, I'd normally expect there not to be an error when using one in place of the other.

In the following example, the line where we use `new URL(origin)` has an error because `import("url")` doesn't match the builtin `URL`.
Perhaps the typing of `@types/node` need to be updated?
```log
error TS2345: Argument of type 'string | import("url").URL' is not assignable to parameter of type 'string | URL'.
  Type 'URL' is not assignable to type 'string | URL'.
    Type 'import("url").URL' is not assignable to type 'URL'.
      The types returned by 'searchParams.entries()' are incompatible between these types.
        Type 'IterableIterator<[string, string]>' is missing the following properties from type 'URLSearchParamsIterator<[string, string]>': map, filter, take, drop, and 9 more.
```

### Sample Code

```TypeScript
// agent.ts
import { URL } from 'url';

export function agent(url: URL | string) {/* ... */};

// factory.ts
const createAgent = (origin: Parameters<typeof agent>[0]) => {
  const { protocol } = new URL(origin);
  // ...
}
```

### Documentation Link

This was probably introduces as part of the strict iterator checks
https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#strict-builtin-iterator-checks-(and---strictbuiltiniteratorreturn)

**Comment by rbuckton** [comment]
This should be addressed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70648

**Comment by Renegade334** [comment]
@types/node v18.19.56 / v20.16.12 / v22.7.6 should be compatible with esnext.iterator.

**Comment by capaj** [comment]
This is PITA. I just added SST3 to a monorepo and it broke our TSC compilation, because we were only using node lib

we would get dozens of errors like this one:

```ts
tests/unit/integrations/gitlab-url-parsing.test.ts:76:33 - error TS2345: Argument of type 'import("url").URL' is not assignable to parameter of type 'URL'.
  Type 'URL' is missing the following properties from type 'URL': createObjectURL, revokeObjectURL, canParse

76     const parsed = detectGitLab(new URL("https://gitlab.com/windok-cloud"));
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

so I was able to resolve it by adding:
```ts
    "lib": ["ESNext", "DOM"], // we don't want DOM in the backend, but sst3 breaks TSC compilation without it https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/826
```

of course this broke some of our current valid typings too, but I guess this is what you get when you start extending global interface like URL.
