### ISSUE TITLE
CommonJS module output broken after updating from 5.5.4 to 5.6.2

### ISSUE THREAD

**Issue by SBoudrias** [microsoft/TypeScript#59991]
### 🔎 Search Terms

5.6 commonjs cjs node10 moduleResolution modules regression

### 🕗 Version & Regression Information

- This changed between versions 5.5.4 and 5.6.2
- This changed in commit or PR: Example of the failure on `inquirer` https://github.com/SBoudrias/Inquirer.js/pull/1554

### ⏯ Playground Link

https://github.com/SBoudrias/Inquirer.js/pull/1554

### 💻 Code

My tsconfig.cjs.json

```ts
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "lib": ["es2023"],
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node10",
    "outDir": "dist/cjs",
    "declarationDir": "dist/cjs/types"
  }
}
```

### 🙁 Actual behavior

The files outputted in `dist/cjs` are now using esm module syntax instead fo cjs (`import ... from`).

### 🙂 Expected behavior

As of version 5.5.4, the files outputted in `dist/cjs` were cjs (`require(...)`).

**Comment by Andarist** [comment]
bisects to https://github.com/microsoft/TypeScript/pull/59479

**Comment by Andarist** [comment]
So it seems that before this PR it would ignore the fact that your files are authored using `.mts` and it would allow you to compile that to a commonjs module. With the new version the extension is always taken into consideration, even with `"moduleResolution": "node10"`. 

We can trace back this work to https://github.com/microsoft/TypeScript/pull/57896 and https://github.com/microsoft/TypeScript/pull/58825 . They mention that from now on extensions should be considered in more `module` modes but they are not as explicit when it comes to what does it mean for `moduleResolution` modes.

This is a one-line change to fix your issue but the changed code is also almost explicit when it comes to applying the new logic for extensions regardless of `moduleResolution`... so I think it's best to ping @andrewbranch and defer to his opinion about this.

Minimal repro case:
```ts
// @moduleResolution: node10
// @module: commonjs

// @filename: index.mts
export const foo = ''
```

**Comment by andrewbranch** [comment]
Yes, this is working as intended. Compiling .mts files to CommonJS-containing .mjs files was not something we ever intended to support—the fact that it ever worked was a bug / unintentional side effect of other work.

**Comment by MartinJohns** [comment]
Related: https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#respecting-file-extensions-and-package.json-from-within-node_modules

**Comment by SBoudrias** [comment]
Thanks for the answer! I'll review how I dual ship then.

It might be good to document cases where tsc ignore settings. I combed through the documentation first and this behavior didn't appear obvious to me.

**Comment by Andarist** [comment]
If you were relying on `tsc` for dual emit then it might be the easiest to switch to using [tshy](https://github.com/isaacs/tshy). If you prefer to handroll the solution then I'd recommend switching to `.ts` files. I've seen you have post-processing step to fixup extensions and stuff - that step could be reused. It feels that if you just tweak its logic a little bit to handle a different set of files and do a slightly different fixup then it should work. Note that I didn't take too deep into your current setup so what I'm saying is not a guarantee but rather a conclusion drawn solely on a first impression of a very tiny slice of your repo ;p

**Comment by KpjComp** [comment]
Came across this issue using `ts.transpileModule(source..`

My issue was the resolved file was the `.mjs`,  but my compile chain was also checking for `cjs` variant, it would load this one if existed, but the `filename` in `transpileModule` kept the same extension, also transforming the `filename` extension fixed this issue.. :)

Of course the above makes total sense, but wonder if your going to ignore `module: ts.ModuleKind.CommonJS,` it might make sense to throw an exception, it took me a long time to track this bug down.  So might help others who have there own compiler chain using Typescript.
