### ISSUE TITLE
Incorrect type deducted for accumulator in reduce

### ISSUE THREAD

**Issue by nielstron** [microsoft/TypeScript#59999]
### 🔎 Search Terms

"type inference reduce" "type inference tuple type"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=3.8.3&q=84#code/DYUwLgBMDOYFwQHYFcC2AjEAnA2gXXwgF4IccAGPPAbgChRIAPYicugYwHtFYIvOsAE2gIcKDNgA0SNJiwE8LGGAB0WEIOTsQACh0BDdu2lZOAd2kBLAJTEAfBADeEFy9quPUcBABWLNu6eLobsKgAOyNAAFjo4ltI+eNbUnoFB6mDIWIgQIXQeAL7S+NZAA

### 💻 Code

```ts
let lst: number[][] = [[0]];
let x = 0;
const coords: [number, number][] = lst.reduce((acc, row, i) => {     
        let j = 0;
        acc.push([i, j]);     
        return acc;
    }, [])
```

### 🙁 Actual behavior

Typescript infers type `number[]`for acc and throws this error:

```
Type 'number[]' is not assignable to type '[number, number][]'.
```

### 🙂 Expected behavior

Typescript should infer type `[number, number][]`.
When passing this type explicitely, the code compiles, i.e. it is possible to derive a correct type annotation.

```
let lst: number[][] = [[0]];
let x = 0;
const coords: [number, number][] = lst.reduce((acc: [number, number][], row, i) => {     
        let j = 0;
        acc.push([i, j]);     
        return acc;
    }, [])
```
https://www.typescriptlang.org/play/?ts=5.6.2&ssl=7&ssc=11&pln=1&pc=1&q=84#code/DYUwLgBMDOYFwQHYFcC2AjEAnA2gXXwgF4IccAGPPAbgChRIAPYicugYwHtFYIvOsAE2gIcKDNgA0SNJiwE8LGGAB0WEIOTsQACh0BDdu1Hi5009gXSsnAO7SAlgEpiAPggBvCN++0f-qHAIACsWNj8A70N2FQAHZGgACx0cB2lgvCdqAIjI9TBkLEQIaLp-AF9pfCcgA

**Comment by MartinJohns** [comment]
Duplicate of #59863.

**Comment by nielstron** [comment]
I see, this seems right. Thank you!
