### ISSUE TITLE
add type parameters to polymorphic this type

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#5999]
It would be enormously helpful if `this` recognized type parameters:

```typescript
abstract class Functor<a> {
   abstract map<b>(map: (value: a) => b): this<b>;
}

abstract class Monad<a> extends Functor<a> {
   abstract bind<b>(bind: (value: a) => this<b>): this<b>;
}
```

**Comment by mhegazy** [comment]
looks like a duplicate of  #5845

**Comment by aleksey-bykov** [comment]
I don't think it is a duplicate, 

Higher kinded types are superior to what I am asking here, it would be great if TypeScript had HKT's, please please please, but in meanwhile, since the polymorphic this type was (surprisingly) added here, why not to tweak it a bit by allowing type parameters to it?

**Comment by mhegazy** [comment]
i do not think it is a "tweak". I am not sure I even understand the semantics of `this<T>` in this context; what if the extending class is not generic, what if it but the extending class type parameter count does not match that of the base, what if the type parameters are not the "same" type parameter of the base...

**Comment by aleksey-bykov** [comment]
... crap, fair questions, this inheritance thing never works out nicely, what's even more upsetting is that `this` "polimorfic" type is here but due to that inheritance nonsense you can only use it for 23% of what you wish you could, nevermind
