### ISSUE TITLE
Suggestion: abstract classes

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#6]
Support an `abstract` keyword for classes and their methods

Examples:
```TypeScript
abstract class Base {
    abstract getThing(): string;
    getOtherThing() { return 'hello'; }
}
var x = new Base(); // Error, 'Base' is abstract

// Error, must either be 'abstract' or implement concrete 'getThing'
class Derived1 extends Base { }

class Derived2 extends Base {
    getThing() { return 'hello'; }
    foo() { super.getThing(); } // Error: cannot invoke abstract members through 'super'
}
var x = new Derived2(); // OK
var y: Base = new Derived2(); // Also OK
y.getThing(); // OK
y.getOtherThing(); // OK

abstract class Empty { } // OK
```

**Comment by vnenkpet** [comment]
:+1:

**Comment by Griffork** [comment]
@RyanCavanaugh thanks for that, I totally didn't think of that!

**Comment by tbenbrahim** [comment]
This should be implemented in the compiler, will all due respect to all who are working on a runtime solution

Here is how it could work, with just abstract methods

1. The programmer defines:
````typescript
class AbstractShape{
    public get X()...
    public get Y()...
    protected abstract draw();
}````
It does not matter what the compiler generates here, even if it needs to define and empty method body for draw, so be it. The magic happens in the next step.
2. For any class with abstract methods, create an internal interface, with the abstract methods
   interface IAbstractShapeInternal$1234{
       draw(): void;
   }
3. Any class that extends AbstractShape also automatically implements the internal interface IAbstractShapeInternal$1234. If you forget to implement the abstract methods, you get the same error you would if you  implemented an interface and did not define the corresponding methods.

**Comment by bwindels** [comment]
This would also be really useful for me.

One solution to avoid having to implement a runtime check could be to just not implement the abstract method in the abstract class in javascript, and let it throw a TypeError if you somehow manage to instantiate the abstract class and try to call an abstract method. It's not perfect, but it respects typescript philosophy of not doing anything typescript specific in the generated javascript and already helps a lot.

It could look like this:
```typescript
class AbstractGreeter {
	constructor(private name: string) {}
	
	greet() {
		return this.salutation() + ", " + this.name;
	}
	
	abstract salutation(): string;
}

class HiGreeter extends AbstractGreeter {
	salutation(): string {
		return "hi";
	}
}

var g = new AbstractGreeter("Typescript");	//compile error
var ctor = AbstractGreeter;

function makeMaybe(ctor): AbstractGreeter {
	if(Math.random() > 0.5) {
		return new ctor("Typescript");
	}
	else {
		return null;
	}
}

var ag1 = new AbstractGreeter("Typescript"); //compile error

var hg = makeMaybe(HiGreeter); //compiles
if(hg) {
	console.log(hg.greet()); //logs "hi, Typescript"
}

var ag = makeMaybe(AbstractGreeter); //compiles 
if(ag) {
	console.log(ag.greet()); //throws "TypeError: undefined is not a function"
}
```

With the generated javascript looking like this, not defining ```salutation()``` in ```AbstractGreeter```:

```javascript
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var AbstractGreeter = (function () {
    function AbstractGreeter(name) {
        this.name = name;
    }
    AbstractGreeter.prototype.greet = function () {
        return this.salutation() + ", " + this.name;
    };
    return AbstractGreeter;
})();
var HiGreeter = (function (_super) {
    __extends(HiGreeter, _super);
    function HiGreeter() {
        _super.apply(this, arguments);
    }
    HiGreeter.prototype.salutation = function () {
        return "hi";
    };
    return HiGreeter;
})(AbstractGreeter);
var g = new AbstractGreeter("Typescript"); //compile error
var ctor = AbstractGreeter;
function makeMaybe(ctor) {
    if (Math.random() > 0.5) {
        return new ctor("Typescript");
    }
    else {
        return null;
    }
}
var ag1 = new AbstractGreeter("Typescript"); //compile error
var hg = makeMaybe(HiGreeter); //compiles
if (hg) {
    console.log(hg.greet()); //logs "hi, Typescript"
}
var ag = makeMaybe(AbstractGreeter); //compiles 
if (ag) {
    console.log(ag.greet()); //throws "TypeError: undefined is not a function"
}
```

**Comment by bwindels** [comment]
Thinking about the above example. I don't know how elaborate the type system is inside the compiler, but wouldn't the compiler be able to determine in the example above that the ```makeMaybe()``` function receives constructor of an abstract class and in some cases that constructor function is used with the ```new``` operator inside the function?

**Comment by Griffork** [comment]
My concern is a long story that involves dynamic require statements (requires that are given a variable instead of a hard coded string). 
Those required files export one class, and that class is created at run time. 
Some bugs have caused abstract classes to be instantiated in this manner, which isn't ideal, this the request for the ability for the constructor to be able to error if not called by a derived class. Note: some of these abstract classes don't contain any virtual functions (all functions have implementation) but they are not 'complete' enough to be used for anything in their own. 

I was hoping for native Typescript support for that, but since I'll be able to write the check myself that works too. As long as I can avoid the hours it took to find out I was instantiating an abstract class that it did the first time ;-).

**Comment by rolyp** [comment]
:+1: Long overdue :)

**Comment by am11** [comment]
There is a hint of abstract classes support in 2.0 roadmap: https://github.com/Microsoft/TypeScript/wiki/Roadmap#20

**Comment by bvaughn** [comment]
+1

**Comment by bryanrideshark** [comment]
+1 to include the feature as a compile-only error (without throwing errors in the constructor). All I want is to know that I've forgotten to override a method. It would be awesome if Intellisense in Visual Studio could generate stubs for you when you begin defining a class which extends the abstract class. IMO, the benefit of Typescript revolves around composing code, not changing the execution behavior. I've been waiting for abstract classes for a while, for that purpose : to help me write code, and catch errors at compile time.

**Comment by bryceg** [comment]
+1

**Comment by Nimbus89** [comment]
+ 1

**Comment by gotenxds** [comment]
+1 How does this not exist yet!?!

**Comment by DanielRosenwasser** [comment]
@gotenxds as mentioned, we're hoping to address this more closely once we finish off most of our ES6 work.

**Comment by RyanCavanaugh** [comment]
Going to delete a bunch of :+1: comments to make this thread shorter (upvote feature please GitHub!).

List of fine people who have :+1:'d:
basarat, ddotlic, nathggns, ca0v, oswdr, Mogglewump, jeffmay, Lenne231, Griffork, filipstachura, Vadorequest, mihhail-lapushkin, cy, koloboid, Elephant-Vessel, pspi, am11, FedericoZanin, Kagiyama, vnenkpet, rolyp, bvaughn, bryceg, Nimbus89, gotenxds

**Comment by RyanCavanaugh** [comment]
Accepting PRs.

Design notes for potential implementors:
 * No runtime checking, per our usual design goals
 * It is an error to invoke `new` on an identifier that binds to an abstract class declaration. Indirect invocations, e.g. `var x = MyAbstractClass; var y = new x();` are allowed, and the static side of abstract classes have the same construct signatures they would have if they weren't abstract
 * No abstract methods/properties/fields at this time

**Comment by DickvdBrink** [comment]
For the record, I'm currently (trying) to implement this

**Comment by mhegazy** [comment]
We are open to looking at incremental changes. Just make sure the first iteration is substantial enough to warrant feedback. 

I would recommend sharing your approach and design on this issue before jumping into implementation. this way we can help save you time early on.

**Comment by jeffreymorlan** [comment]
> Indirect invocations, e.g. `var x = MyAbstractClass; var y = new x();` are allowed, and the static side of abstract classes have the same construct signatures they would have if they weren't abstract

I think this should be reconsidered. Special-casing only a direct "new MyAbstractClass" (rather than removing abstract classes' `new()` signatures) is hacky, and makes it easy to accidentally pass an abstract class to a function that instantiates it (`function constructAndDoOtherStuff(clazz: new() => Foo) { ... }`)

Earlier, this code was given as an example in favor of abstract classes having a `new()` signature:
````
class B extends Abs { /* ... */ }
class C extends Abs { /* ... */ }

var t: typeof Abs;
if(/*... */) {
  t = B;
} else {
  t = C;
}
var j = new t(); // error here if `typeof Abs` is not instantiable
````
But `t` could be declared as `new() => Abs` instead, which better describes what is expected of a valid `t` value anyway. (There is no backward compatibility to worry about, since there are no `abstract` classes in existing TypeScript code.)

In fact, using `typeof Abs` here may already be an error even *without* `abstract`! Suppose that `Abs` has an extra constructor parameter, which `B` and `C` supply in their `super(...)` calls (This is a pattern I use a lot - currently, it's the only way for a class to have an abstract-like "hole" that is supplied by subclasses):
````
class Abs { constructor(public typeName: string) {} }
class B extends Abs { constructor() { super("Class B"); } }
class C extends Abs { constructor() { super("Class C"); } }

var t: typeof Abs;
t = B;
new t(); // Error here - wrong number of parameters
````
Because `Abs` has the wrong constructor signature, we are already required to use `new() => Abs` instead of `typeof Abs` in this case. It doesn't seem an undue burden to require the same if `Abs`'s "holes" take the form of `abstract` methods rather than constructor parameters.

**Comment by Griffork** [comment]
@jeffreymorlan there was a suggestion that users can program their abstract classes to error in the constructor if they wanted it to (it's above) like this:

``` Typescript 
class classa {
    constructor () {
        if(Object.getPrototypeOf && (Object.getPrototypeOf(this) === classa.prototype) {
            throw new error("classa is abstract and should not be directly instantiated");
        } 
    } 
} 
```
This specifically checks of classa is 'bottom' of the prototype chain.

**Comment by RyanCavanaugh** [comment]
Merged into `master` and will be available in our 1.6 release. Thanks @aozgaa !

**Comment by jasonwilliams200OK** [comment]
In case you are wondering, it all happened with #3579 (with no back reference to this *original* issue :cry:)

**Comment by ddotlic** [comment]
Yeah, thanks @aozgaa! Lately, I've been adding many, many `throw new Error('this should not have been called, it's abstract')` across my codebase with the intention of replacing it all with proper `abstract` support.

Beta/Alpha 1.6 cannot come soon enough :wink:

**Comment by aozgaa** [comment]
My apologies about not offering the back-reference. Thanks @jasonwilliams200OK for linking above!
