### ISSUE TITLE
Weird behavior with recursive generic types

### ISSUE THREAD

**Issue by droooney** [microsoft/TypeScript#60018]
### 🔎 Search Terms

recursive generic types

### 🕗 Version & Regression Information

v5.6.2

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAysD2AnCAeAqgZwogIgQ2DwD4oBeKAbwCgooBzCYALigAoBKMkzbfQgbhpQszNgBMCeFj1yTOpEgDd4ASzGCAvoKqhIUAIJhIAOzEBheMeAQAHsACMKQ2ACiiiFYA0UGX2JlKITA8ZCsWFwAbCABbJyM3D2BvX0kiTW1daGcPc0trOwAmONd3Lx8sWUIScmpaYNDRSJjihLKUqvSqKgAzAFdjAGNgFUsoCPg6AAUQxJbSpPLeVNZ6xPCo2OdWhfbidhZlNUoNLoGIvAwMKCbN+Pnkir8SWuEEZAB+FjgkVF20rtoeCMOVYQxsLGypgsVlsDjmiQeSyq+yghzEgVotHGUxmVlBwBsADpVlZ2IJaCcTlQBpYMMAoGD7BDgVC8rDHMYIO5EN5jL1ogAjbDVY5QC4GFm5GF2Dlc7DeOmIFTGOj-am0+lggrMkxS-LAIqc7m8-lCxAiigaMVXSF62GGuU815KlVpIA

### 💻 Code

```ts
type Store<UserData> = {
  get: () => UserData;
  set: (data: UserData) => void;
};

type AppendContext1<AppEvent, UserData> = {
  parent: Elem<AppEvent, UserData>;
};

type AppendContext2<AppEvent, UserData> = {
  parent: Elem<AppEvent, UserData>;
};

function logParent<AppEvent, UserData>(parent: Elem<AppEvent, UserData>): void {}

class Elem<AppEvent, UserData> {
  store?: Store<UserData>;

  append(ctx: AppendContext1<AppEvent, UserData>): void {
    logParent(ctx.parent);
  }
}

const ctx1: AppendContext1<never, number> = {} as AppendContext1<never, string>;

const ctx2: AppendContext2<never, number> = {} as AppendContext2<never, string>;
```

### 🙁 Actual behavior

Only the second assignment errors

### 🙂 Expected behavior

Both assignment should error because their respective `Store`s differ

### Additional information about the issue

This is the most minimal reproducible example that I could create and it probably has the most weird bits of behavior in TS that I've ever seen:

- if you remove the `AppEvent` parameter (that doesn't really affect anything as it would seem) from everywhere, both assignments result in an error, just like they should
- if you remove `append` method from the `Elem` class, both assigments result in an error
- if you replace the `parent` parameter type in `logParent` with `any`, both assigments result in an error
- finally if you remove the `logParent` statement (which definitely shouldn't affect typings in this case), again both assignments error

**Comment by RyanCavanaugh** [comment]
This can happen due to shortfalls in the variance measurement algorithm when you have mutually-recursive types like this. See https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#optional-variance-annotations-for-type-parameters - the code here is basically isomorphic to the example in the blog post.

**Comment by droooney** [comment]
Thank you so much for clearing this out for me! I've wasted hours on this problem, glad to finally figure out what was wrong with my code. Honestly never heard of these explicit `in`/`out` before and there doesn't seem to be a lot of info/help online about those, but they look quite powerful when applied correctly. Again thank you so much!
