### ISSUE TITLE
Property 'difference' does not exist on type 'Set'

### ISSUE THREAD

**Issue by occassionally** [microsoft/TypeScript#60012]
### 🔎 Search Terms

is:issue set difference does not exist 

### 🕗 Version & Regression Information

I tested this on the Nightly TypeScript version, 5.7, 5.6, etc.

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `FAQ (For Issue Filers)`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20240919#code/PTAEAsBdIBwZwFwgCYFMBuqA2B7GqAnAOgFscAvASyywEMicCBzYVAOwFoBVAZWGRwBjOMADqqAEbAAUrXS0eggpRiRgAJVQAzQu0GpgAcVwTaWAPoB5CQCtUgyCJ6o1ySlp0E9qACQAGAChBHDY4SFAcZGQ4UABeUDZUAHdQZ0gACgBtAEYAGlAAZnyAVnyAdnyATgBdAEoAbiCQsNA4AEcAV1ovGPjElLSsvNAAFiq6xuDQnCxUIlwmdMjoojcPXTZ9dPauntqG0BBUl3SC2tAAb0KS8tAAXyA

### 💻 Code

```ts
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference$0
const odds = new Set([1, 3, 5, 7, 9]);
const squares = new Set([1, 4, 9]);
console.log(odds.difference(squares)); // Set(3) { 3, 5, 7 }
```

### 🙁 Actual behavior

```ts
Property 'difference' does not exist on type 'Set<number>'.ts(2339)
```

TypeScript does not recognize the property.

### 🙂 Expected behavior

I expected TypeScript to recognize the property, since:
1) MDN confirms it is [widely available](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/difference#browser_compatibility)
2) #57228 and #57230 seem to have accepted and merged this back in May.

Why is the compiler still showing that it isn't recognized?

**Comment by itsramiel** [comment]
@occassionally why did you close this? How did you resolve the issue?

**Comment by occassionally** [comment]
@itsramiel I closed it because I tested it and the functions aren't available on Node 20.16.0, and possibly not in JavaScript itself either (still in draft phase, I didn't test specifically), so I figured this was why TypeScript didn't recognize it. I just wrote my own implementations.

I re-opened it though, so we can get the maintainers' feedback.

**Comment by jcalz** [comment]
Make sure your `--target` is for a version of JavaScript that supports this. In this case, esnext: [playground link](https://www.typescriptlang.org/play/?target=99&ts=5.7.0-dev.20240919#code/PTAEAsBdIBwZwFwgCYFMBuqA2B7GqAnAOgFscAvASyywEMicCBzYVAOwFoBVAZWGRwBjOMADqqAEbAAUrXS0eggpRiRgAJVQAzQu0GpgAcVwTaWAPoB5CQCtUgyCJ6o1ySlp0E9qACQAGAChBHDY4SFAcZGQ4UABeUDZUAHdQZ0gACgBtAEYAGlAAZnyAVnyAdnyATgBdAEoAbiCQsNA4AEcAV1ovGPjElLSsvNAAFiq6xuDQnCxUIlwmdMjoojcPXTZ9dPauntqG0BBUl3SC2tAAb0KS8tAAXyA)

**Comment by itsramiel** [comment]
> Make sure your `--target` is for a version of JavaScript that supports this. In this case, esnext: [playground link](https://www.typescriptlang.org/play/?target=99&ts=5.7.0-dev.20240919#code/PTAEAsBdIBwZwFwgCYFMBuqA2B7GqAnAOgFscAvASyywEMicCBzYVAOwFoBVAZWGRwBjOMADqqAEbAAUrXS0eggpRiRgAJVQAzQu0GpgAcVwTaWAPoB5CQCtUgyCJ6o1ySlp0E9qACQAGAChBHDY4SFAcZGQ4UABeUDZUAHdQZ0gACgBtAEYAGlAAZnyAVnyAdnyATgBdAEoAbiCQsNA4AEcAV1ovGPjElLSsvNAAFiq6xuDQnCxUIlwmdMjoojcPXTZ9dPauntqG0BBUl3SC2tAAb0KS8tAAXyA)

yes works
