### ISSUE TITLE
tsserver requires `npm` to be installed on `neovim` trough `mason`

### ISSUE THREAD

**Issue by lorypelli** [microsoft/TypeScript#60022]
### 🔎 Search Terms

tsserver, neovim, nvim, mason

### 🕗 Version & Regression Information

I can't install `tsserver` because I don't have `npm`

### 🙁 Actual behavior

I can't install `tsserver` because I don't have `npm`

### 🙂 Expected behavior

You should check for the package manager installed on the system (`pnpm` in my case) and use that.

**Comment by guillaumebrunerie** [comment]
This repository is about TypeScript itself, not about mason or Neovim. Duplicate of williamboman/mason.nvim#1786, which also contains a workaround for exactly this use case.
