### ISSUE TITLE
keep getting this one or more errors occurred

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6002]
![image](https://cloud.githubusercontent.com/assets/937933/11671590/85e0608c-9dd7-11e5-9217-a79d76a64003.png)

**Comment by RyanCavanaugh** [comment]
As you might imagine, we'll need more information to be able to act on this

**Comment by ahejlsberg** [comment]
In particular, we need to know whether *one* or *more* errors occurred! :stuck_out_tongue_winking_eye:

**Comment by aleksey-bykov** [comment]
I wish I knew where to look for it. The problem happens randomly around
severe syntax break downs (unfinished expression in a function lacking
balanced parentheses leaking to module level).

**Comment by aleksey-bykov** [comment]
I couple of times a weak during some syntax intense refactorings. There is
a significant wait time when everything is frozen that leads to this crash.
Looks like a regex goes out of orbit.

**Comment by aleksey-bykov** [comment]
Is there a log file or something tgag might contain more details which I could send to you?

**Comment by vladima** [comment]
can you check if you have any error entries in windows event log with the source .NET runtime?

**Comment by aleksey-bykov** [comment]
running VS with the [/Log](https://msdn.microsoft.com/en-us/library/ms241272.aspx) flag on, will let you know when I get something:

**Comment by aleksey-bykov** [comment]
gonna close this one until get some evidence
