### ISSUE TITLE
Visual Studio 2015 MSBuild Error: VSTSC Out of stack space

### ISSUE THREAD

**Issue by kenhowardpdx** [Microsoft/TypeScript#6005]
I'm running Visual Studio 2015 w/ TypeScript 1.6 and have been getting the following error. It happens intermittently. I don't know what the steps are to reproduce. There's only one project with this issue so far. The screenshot is from a failed build on AppVeyor. Rebuilding the commit fixed the issue.

Note: I recently installed TypeScript 1.6 for VS 2015 from typescriptlang.org (before VS Update 1 was released... still not running update 1).

```
VSTSC : tsc.js(29825, 17) JavaScript runtime error : Out of stack space [C:\projects\xyz\****.csproj]
```

![screen shot 2015-12-08 at 6 38 51 pm](https://cloud.githubusercontent.com/assets/1892667/11675048/52c6bb02-9ddb-11e5-8fd5-45e81d1ed822.png)

Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA787
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA787
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA787
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA787
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.20626.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Chutzpah Context Menu   4.1.0
Enables you to run JavaScript unit tests via Chutzpah from the context menu

Chutzpah Test Adapter for Visual Studio 2012   4.1.0
Chutzpah adapter for the Visual Studio 2012 Unit Test Explorer. Chutzpah is an open source JavaScript test runner which enables you to run JavaScript unit tests from the command line and from inside of Visual Studio.

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Code Digger   0.9
Microsoft Code Digger

Microsoft.Pex.VisualStudio   1.0
Pex

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

WakaTime   1.0

**Comment by mhegazy** [comment]
@kenhowardpdx is there a chance you can share the project that is exhibiting the issue?

**Comment by kenhowardpdx** [comment]
@mhegazy It's a private repo. Email me @ kenh@csgpro.com so you can have a look.

**Comment by kenhowardpdx** [comment]
At this point I'm not able to get the client's approval to release the code for debugging. 

I did find this (http://stackoverflow.com/questions/31409941/visual-studio-typescript-out-of-stack-space) and wonder if my problem is related to the `let` keyword as I've been using it more frequently.

I still get the error, but can put up with it for now.

**Comment by DanielRosenwasser** [comment]
Hey @kenhowardpdx, sorry about the delay, Mohamed's out for this week. Is it at all possible to use Node in the mean time to avoid the error?

**Comment by kenhowardpdx** [comment]
Yeah. It's working fine from the command line. Just annoying that AppVeyor needs to be watched and PR's need to get rebuilt frequently.

**Comment by vladima** [comment]
closing this since it is not actionable without a repro bits.

**Comment by frederikprijck** [comment]
I've got the same problem. 
I've got no repro bits either, it randomly started happenis in my current project.
It doesn't happen every time. Let's say 5 times out of 10 builds I manage to compile without an error.

@kenhowardpdx  did you manage to resolve ur issue without using node?

**Comment by kenhowardpdx** [comment]
@frederikprijck The project that had this issue is frozen. We are no longer developing it. I was able to use tsc from the command line without issue.

**Comment by frederikprijck** [comment]
Yep running tsc from cli works as workaround.
