### ISSUE TITLE
Unexpected imports relative paths in declaration files

### ISSUE THREAD

**Issue by CarlosCortizasCT** [microsoft/TypeScript#60056]
### 🔎 Search Terms

invalid declaration files imports

### 🕗 Version & Regression Information

Hello ✋ 

We're experiencing an error in our monorepo regarding how Typescript files declarations are generated when building our packages we don't understand and, after investigating it for some days, we decided to raise this issue hoping for some help 🙏.

We've created [this repository](https://github.com/jaikumar-tj/preconstruct-playground) with the minimal code which reproduces the error.

We have three packages in that monorepo with this relationship:
![image](https://github.com/user-attachments/assets/a2aed19c-a051-4f35-93ce-01235af7bf9f)

The problem we see when we build the repo is that the `types.d.ts` file generated for the `Product` package looks like this:

![image](https://github.com/user-attachments/assets/6c40c98a-b0a3-4243-9914-beab88697c9c)

As you can see, **the import for the `Category` packages is correct, but the one for the `ProductType` package is not.**
Also, we see a `declarations-type` folder in the `product/dist` directory that seems weird and does not exist in the other packages.

This is how the `package.json` file of the `Product` package looks like:
![image](https://github.com/user-attachments/assets/df80e605-0274-4bc1-b245-f712dd25d60a)

Our theory is that maybe the packages names can be the root of the problem, but even if that's true, changing the name of the packages is not an option for us and we would like to know if this could be an issue in the Typescript build process.

Thanks for your help 🙇 

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

We get invalid imports in the declaration files:
![image](https://github.com/user-attachments/assets/8cc8dc7d-6029-4ca9-8e92-a58a411869f6)

### 🙂 Expected behavior

We would expect the import to use the package name:
![image](https://github.com/user-attachments/assets/be67c5e5-e8cb-44d4-92b3-7a5246a990b9)

**Comment by RyanCavanaugh** [comment]
You need a tsconfig in each package for monorepos to work correctly. Having a top-level tsconfig like this isn't supported.

If there's some external tool that's trying to shim that behavior, it's not doing its job correctly.

**Comment by CarlosCortizasCT** [comment]
Hi @RyanCavanaugh 

Thanks a lot for your answer 🙇 

I'm wondering how the tsconfig file for each package should look like. Do they need just to extend the top-level one? Do we  need to repeat the same configuration for each package?

So far we've been using just a top-level tsconfig file for some years without problem. The issue only appeared when we had, for instance, package `product-type` set as a dependency of `product` package.

We're using `preconstruct` in the repository to build the packages and I've debugged all the runtime flow double checking everything works as expected until it internally calls Typescript to compile the code (with the correct config).

Thanks again for your support 👍

**Comment by CarlosCortizasCT** [comment]
Just to provide some more feedback, I've just tried by adding the same `tsconfig` file in each package (updated in the [demo repository](https://github.com/jaikumar-tj/preconstruct-playground/tree/main)) but the build fails with this error:
![image](https://github.com/user-attachments/assets/495ec828-2027-4246-a86a-d6cab6fbed02)
