### ISSUE TITLE
After the syntax tree is parsed incrementally, the identifiers content is lost.

### ISSUE THREAD

**Issue by YZJcode** [microsoft/TypeScript#60055]
### 🔎 Search Terms

identifiers

### 🕗 Version & Regression Information

latest version v5.6.2

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

After the syntax tree is parsed incrementally, identifiers contain only incrementally changed content. The original identifier is lost. As a result, the method name is duplicate when the method is extracted.

### 🙂 Expected behavior

After the syntax tree is parsed incrementally, identifiers contain the complete content.

**Comment by RyanCavanaugh** [comment]
Please provide concrete repro steps in a new issue
