### ISSUE TITLE
Object mistyped as Array when Array is spread into Object

### ISSUE THREAD

**Issue by StefanDBTLabs** [microsoft/TypeScript#60063]
### 🔎 Search Terms

destructure array in to object
array spread in to object

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about arrays and objects

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.2#code/C4TwDgpgBAYg9nKBeKBvKAjAhgJwFxQDOwOAlgHYDmUAvgNwCwAUAGYCu5AxsKXOVC3IAKYAXhwA2gF0AlGig4IwNjn7AAdAFssYISGQA+KAEJjIOTWac+xBcnnrHE9NnxQARMTJV3tKbUZWYRwZOiA

### 💻 Code

```ts
type Foo = { bar: string };
function fn(t: Foo[]) { return t.map(y => !!y) }
const r = { ...[{ bar: "string" }] };
fn(r);
```

### 🙁 Actual behavior

`Foo` Allows me to pass an `Object` when it wants an `Array`. when `fn` is called with `Object` it throws an error because there is no `map` on an `Object`

![image](https://github.com/user-attachments/assets/e7689430-f23c-4dd5-b6d2-a1b527a9e559)

### 🙂 Expected behavior

There should be a typescript error when passing an `Object` to function that wants an `Array`

### Additional information about the issue

In the d.ts file you can see how it has created a type for `r` that looks like an array.

**Comment by RyanCavanaugh** [comment]
Enumerability/ownness is not tracked in the type system, so we don't have any mechanism to recognize that this won't work. See [#9726](https://github.com/microsoft/TypeScript/issues/9726)

**Comment by RyanCavanaugh** [comment]
I'm curious what the actual bug you had was. It might worth erroring when spreading something sufficiently arraylike in an object spread position.

**Comment by StefanDBTLabs** [comment]
@RyanCavanaugh the bug was accidentally passing an Object to a function that wanted an array and that function tried to use the array methods which did not exist. that's the screenshot I attached above.

**Comment by RyanCavanaugh** [comment]
Were you calling `assign` or doing a spread?

**Comment by StefanDBTLabs** [comment]
@RyanCavanaugh I was doing the spread I have in the above example 
```
const r = { ...[{ bar: "string" }] };
fn(r);
```
but this was a mistake on my part. I would have wanted to do 
```
const r = [ ...[{ bar: "string" }] ];
fn(r);
```
or even
```
const r = [{ bar: "string" }];
fn(r);
```

but but over looked it and would have hoped typescript would have given me a type error.

**Comment by StefanDBTLabs** [comment]
though if you look at the generated JS from the playground it seems to be doing an Object.assign after generation.
https://www.typescriptlang.org/play/?ts=5.6.2#code/C4TwDgpgBAYg9nKBeKBvKAjAhgJwFxQDOwOAlgHYDmUAvgNwCwAUAGYCu5AxsKXOVC3IAKYAXhwA2gF0AlGig4IwNjn7AAdAFssYISGQA+KAEJjIOTWac+xBcnnrHE9NnxQARMTJV3tKbUZWYRwZOiA

**Comment by martijnarts** [comment]
Just to add to this: it's really easy to run into this when refactoring a property from an object into an array. This causes Typescript to generate Javascript that's broken ([playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBA6glsAFgQQE6qgXigbygQwC4oBnYVOAOwHMBuKAI2LVXxAB48BjYsim+gF8AfFEG0AUBK4B7SmQLpm6Npyg9S5KnTGjsAbW7EARMAhljYgLqTZ84FDMLseIlGMAzGTOMAaRsR4AHQh+OhiYpLSciQyADYQQXEy1AAUTsBBDEEAtvhgqfhYovgAlKWSQA)):

```typescript
type WithArr = { a: string; b: Array<{ c: string; }> };

const arr: Array<{ c: string; }> = [{ c: "test" }];
const test = { a: "foo", b: { ...arr } };

console.log(test.b.map(a => a));
// test.b.map is not a function
```

**Comment by jcalz** [comment]
dupe of #34780
