### ISSUE TITLE
Richer type errors for mismatching signatures on overloaded functions

### ISSUE THREAD

**Issue by blended-bram** [microsoft/TypeScript#60072]
### 🔍 Search Terms

TS2394

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I'd prefer similar output when an interface mismatches, then it clearly states what fields are missing or mismatching in type.
In the case of function overloads it is pretty similar to an assignment failure; since essentially all overloads must be assignable to the implementation.

1. Signal when the return type of impl is not compatible with an overload.
2. Signal when an argument (and which) is not compatible with an overload.
3. Describe type compatibility issues (whether return-type or argument-type) with the same high-level of detail as available with other type assignment failures.

### 📃 Motivating Example

```typescript
type HeaderValue = string | string[] | number | boolean | null | undefined
type QueryValue = string | string[] | number | boolean | null | undefined
interface RequestBlueprint {
  service:string
  method: string
  path: string
  query?: Record<string, QueryValue>
  headers?: Record<string, HeaderValue>
}

class X {
  private async _probe(options: RequestBlueprint): Promise<AxiosResponse<unknown, unknown>>
  private async _probe<T>(
    options: RequestBlueprint & { parse: (response: AxiosResponse<unknown, unknown>) => T }
  ): Promise<T>
  private async _probe(
    options: RequestBlueprint & {
      parse?: (response: AxiosResponse<unknown, unknown>) => unknown
    }
  ) {
    const response: AxiosResponse = await (undefined as never)
    return options.parse ? options.parse(response) : response
  }
}
```

### Current output

```
some/file/in/project.ts:302:17 - error TS2394: This overload signature is not compatible with its implementation signature.

302   private async _probe(options: RequestBlueprint): Promise<AxiosResponse<unknown, unknown>>
                    ~~~~~~

  some/file/in/project.ts:306:17
    306   private async _probe(options: {
                        ~~~~~~
    The implementation signature is declared here.
```

### Assignment test

Compare that with the output of testing the signature through assignment:

```typescript
type Overload1 = (input: RequestBlueprint) => Promise<AxiosResponse>
type Overload2 = <T>(
  input: RequestBlueprint & { parse: (response: AxiosResponse<unknown, unknown>) => T }
) => Promise<T>

function impl(
  input: RequestBlueprint & { parse?: (response: AxiosResponse<unknown, unknown>) => never }
): Promise<AxiosResponse> {
  return new Promise(() => input as never as AxiosResponse)
}

const test: Overload1 & Overload2 = impl
```

Produces:

```
some/file/in/project.ts:382:7 - error TS2322: Type '(input: RequestBlueprint & { parse?: ((response: AxiosResponse<unknown, unknown>) => never) | undefined; }) => Promise<AxiosResponse<any, any>>' is not assignable to type 'Overload1 & Overload2'.
  Type '(input: RequestBlueprint & { parse?: ((response: AxiosResponse<unknown, unknown>) => never) | undefined; }) => Promise<AxiosResponse<any, any>>' is not assignable to type 'Overload2'.
    Types of parameters 'input' and 'input' are incompatible.
      Type 'RequestBlueprint & { parse: (response: AxiosResponse<unknown, unknown>) => T; }' is not assignable to type 'RequestBlueprint & { parse?: ((response: AxiosResponse<unknown, unknown>) => never) | undefined; }'.
        Type 'RequestBlueprint & { parse: (response: AxiosResponse<unknown, unknown>) => T; }' is not assignable to type '{ parse?: ((response: AxiosResponse<unknown, unknown>) => never) | undefined; }'.
          The types returned by 'parse(...)' are incompatible between these types.
            Type 'T' is not assignable to type 'never'.

382 const test: Overload1 & Overload2 = impl
          ~~~~

  some/file/in/project.ts:372:19
    372 type Overload2 = <T>(
                          ~
    This type parameter might need an `extends never` constraint.

```

This error reporting contains much more detail as to why the overload was not compatible with the implementation and gives the programmer a direction to look for solving the problem.

### 💻 Use Cases

1. Understanding what part of the definition mismatches; is it the return type or an argument?
2. Understanding for arguments what subsets of values are mismatched

**Comment by jcalz** [comment]
Duplicate #48186
