### ISSUE TITLE
Using `import type...` generates `export {};` into the JS file

### ISSUE THREAD

**Issue by bpasero** [microsoft/TypeScript#60074]
### 🔎 Search Terms

esm module import export

### 🕗 Version & Regression Information

This reproduces with version `5.6`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?module=7#code/JYWwDg9gTgLgBDAnmApnAVHAhgZzgIyyjgDMoIQ4ByEiCKgbgCgmBjAG1zwDE64BvFnGFwwUYADcsMNDJwwAFAEoBTEevYp4WAFxwAdgFcQ+FFGbqRWOAF4EAC2A4AdKwphDM5RZEBfNu6eKMp6RiZmqjD25ADuBihxAKJQ5FAKAEQAslr2EAAmBhDwoGCaICj6MnnO6UrM-qxQWDHsypHREHH6CXDJqRnZUfmFxeBlFVU1dUz+vkA

### 💻 Code

```ts
import type * from 'foo';

class Foo {

    private test() {
       let a: number;
       a = this.compute();
    }
compute(): number {
throw new Error("Method not implemented.");
}
crawl() {
throw new Error("Method not implemented.");
}
}
```

### 🙁 Actual behavior

There is a `export {};` at the end of the JS file.

### 🙂 Expected behavior

`import type` should have no side-effects on the generated JS.

### Additional information about the issue

The issue here is that this forces the JS file to be ESM when it maybe is not. This makes it hard to convert from JS to TS where in JS I have more control over this.

**Comment by RyanCavanaugh** [comment]
A syntactically valid example is always appreciated.

You can use `typeof import(` in script contexts to get imports
```ts
type a = typeof import("foo");
```

**Comment by bpasero** [comment]
> A syntactically valid example is always appreciated.

Is there a way in the playground to import another module of the playground?

> You can use typeof import( in script contexts to get imports

Yes, that seems like a good workaround. I still believe `import type` should be with no impact on JS files though.

**Comment by RyanCavanaugh** [comment]
This isn't valid syntax
```
import type * from 'foo';
```

>  I still believe import type should be with no impact on JS files though.

It is intentional that all `import` forms behave consistently
