### ISSUE TITLE
Type-directed emit breaks language design goals. Is it worth it?

### ISSUE THREAD

**Issue by yortus** [microsoft/TypeScript#6007]
#### Project A:

``` typescript
// file: foo-a.ts
import BluebirdPromise = require('bluebird');
export async function foo(): BluebirdPromise { }  //  <== has type annotation

// file: foo-a.js
function foo() {
    return __awaiter(this, void 0, BluebirdPromise, function* () { });
}
exports.foo = foo;

```
#### Project B:

``` typescript
// file: foo-b.ts
import BluebirdPromise = require('bluebird');
export async function foo() { }                   //  <== no type annotation

// file: foo-b.js
function foo() {
    return __awaiter(this, void 0, Promise, function* () { });
}
exports.foo = foo;
```

These two projects differ only by a single type annotation, but they produce different JavaScript code with different runtime behaviour.

(Compiled with v1.7.3 with `target=ES6, module=commonjs, noEmitHelpers=true`).

(Note elison bug #6003 is also visible here but not the subject of this issue.)
#### Bug or by design?

I understand this is [by design](https://github.com/Microsoft/TypeScript/issues/5911#issuecomment-161736662) (sorry I can't find a better ref).

However I strongly feel this should be considered a bug, because having a _"fully erasable, structural type system"_ is a core design principle of TypeScript (quote is from the [design goals page](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#goals)).

If this is tagged as 'by design', could we please get some sort of statement from the team to clarify where TypeScript now stands on the "fully erasable type system" goal and the _"[don't] emit different code based on the results of the type system"_ non-goal?

**Comment by DanielRosenwasser** [comment]
I agree that this goes against the idea of type-directed emit, and I think that's been a great guiding principle, but I'm not entirely sure what a better approach would be. Do you have any suggestions for how to continue with the current approach? @mhegazy and @rbuckton, we were discussing this the other day.

**Comment by yortus** [comment]
For what it's worth this is how I look at the situation with `async` functions (the feature that has introduced type-directed emit to TypeScript).

Sorry this is a long comment - I'm just trying to lay out my ideas as accurately as I can. If this comment would be better elsewhere I'd be happy to delete it from here and put it elsewhere.


#### Scenario 1 (COMMON): target >= ES6, normal usage, no custom Promise needed

- Users just want to write `async function() {...}` and let `tsc` do the magic. No messing with custom promises.

- No need for type-directed emit based on return type annotation.

- Return type annotation can work like it does everywhere else (i.e. for type checking. If present it must be a type that's *assignable from* `Promise<T>` (such as `PromiseLike<T>`), in the same way that a generator function return type annotation has to be assignable from `Iterator<T>`).


#### Scenario 2 (COMMON): target ES3/ES5, no built-in Promise

- The user would have to provide a polyfill Promise implemtation in this scenario. Of course they can name this using any identifier they want but my suggestion would be that to work with TypeScript's `async` function feature, it must be called `Promise` (which is standard practice for a polyfill anyway).

- `Promise` can be polyfilled as a global but needn'd be - it just has to be in scope (e.g. `import Promise from 'bluebird'` at file/module scope using commonjs).

- The type system can check, at the site of an `async function` declaration, if there is an in-scope identifier called `Promise` and that it has the right shape. If no `Promise` identifier is in scope, generate a compile error like 'async function requires a `Promise` identifier to be in scope'.

- The downleveled emit uses the `Promise` identifier in the emitted code.

- No need for type-directed emit based on return type annotation.

- Return type annotation can work like it does everywhere else (i.e. for type checking. If present it must be a type that's *assignable from* `Promise<T>` (such as `PromiseLike<T>`), in the same way that a generator function return type annotation has to be assignable from `Iterator<T>`).


#### Scenario 3 (MAYBE COMMON?): target >=ES6, supports builtin Promise, but user wants to use a custom Promise implementation instead

- e.g. platform is node 4.x/5.x but user wants to use 'bluebird' promises because they are faster.

- This could be handled exactly the same as scenario 2



#### Scenario 4 (PROBABLY UNCOMMON): target ESany, async functions must produce Promise instances of several different types in a single project, instead of or in addition to the builtin `Promise`

- User wants to choose what Promise implementation is returned on a per-async-function basis.

- This is the use case that tsc v1.7 is geared toward with its type-directed emit.

- I personally haven't encountered a real world project with this need (scenarios 2 and 3 cover all practical 'custom promise' cases that I've seen). But I guess they may exist. Please speak up, anyone who knows of such a project!

- Because async function declarations don't explicitly reference a `Promise` identifier, there's no obvious way to 'pass' a specific promise class to a specific async function declaration.

- Current implementation solves this scenario using type annotations, but in so doing makes TypeScript no longer have a "fully erasable type system".

- ES7 async function spec also needs to consider how custom promises could be supported. Notably any solution decided there would have to be a runtime mechanism, which TypeScript would presumably adopt in future. Or ES7 may not support this scenario at all. Either way the current type annotation method won't comply with ES7 syntax/semantics.


---
My personal view is that TypeScript should support scenarios 1 - 3 now and drop support for scenario 4 until the ES7 async function spec is finalised and the ES7 mechanism to support this scenario (if any) is known.

Scenarios 1 - 3 can be achieved in a straightforward way, fully consistent with TypeScript's "fully erasable type system", and without resorting to type-directed emit.

Scenario 4 is probably uncommon. TypeScript v1.7 is running ahead of the spec to support this and the final ES7 mechanism is 100% sure not to be a type annotation. It seems a shame to sacrifice the erasability of the type system to solve an uncommon problem in a way that won't match ES7 anyway.

---
As a breaking change I know backing out the type-directed emit is probably not gonna happen. But in case scenario 4 was dropped in v1.8, then the upgrade pathway from 1.7 to 1.8 would be from this:

```typescript
import BluebirdPromise from 'bluebird';
export async function foo(): BluebirdPromise { }
```

...to this:

```typescript
import Promise from 'bluebird';
export async function foo(): Promise { }
```

The latter case is already valid in v1.7 so anyone doing it that way already wouldn't see any breaking changes.

**Comment by yortus** [comment]
If we must accept that type-directed emit is here to stay, could we at least fix the inconsistency described in #6027? If that was done, then the type-directed emit of async functions would at least be in harmony with the expected behaviour of type annotations, rather than in conflict with it.

**Comment by yortus** [comment]
> I agree that this goes against the idea of type-directed emit, and I think that's been a great guiding principle, but I'm not entirely sure what a better approach would be. Do you have any suggestions for how to continue with the current approach?

Why does TypeScript need to do this at at? ES7 async functions do not support returning custom Promise types - they always return ES6 Promise instances, even if `global.Promise` has been overwritten (see #6068). I may have missed something, but I haven't yet seen the compelling reason to lose the quality of type erasability in order to implement a feature that is not in line with ES semantics.

For ES3/ES5 there is no ES6 Promise available so there *must* be a way to polyfill `Promise`. But why on a function-by-function basis? Wouldn't it be more sensible to polyfill once per project?

**Comment by yortus** [comment]
Thanks team and especially @rbuckton for addressing this for ES6+. With #6631 merged, async functions are more ES7-compliant and return type annotations no longer affect the emitted JavaScript with target >= ES6.

I'd like this issue to remain open however to discuss async function support for ES3/ES5 (via downlevelling), which is currently [slated for v2.0](https://github.com/Microsoft/TypeScript/wiki/Roadmap/f5faca60dcc846b8353a22abaec123139a86c8a6#20). It seems it may still use return type annotations to emit different code (eg see comments [here](https://github.com/Microsoft/TypeScript/pull/6631#discussion_r50919498) and [here](https://github.com/Microsoft/TypeScript/pull/6631#discussion_r50930093)).

As a web developer targeting older browsers, It would be great to be able to write with `async function` syntax and have them downlevelled to equivalent ES5. The way I'd like to do that would something like be:
1. bootstrap code in browser feature-detects `Promise` support. If absent, assign a Promises/A+-compliant polyfill to `window.Promise`. Now we can reuse the same Promise-based code regardless of the host's ES-level.
2. Use an appropriate typings file that ambiently declares the global `Promise` type.
3. Write a bunch of async functions same as I would in ES6+ and expect them to pick up the `Promise` from `window`, regardless whether it's native or polyfilled.

In particular I don't wan't to have to add a type annotation to every async function telling it what kind of promise to return. Standard practice is to do polyfilling once at startup, not at every function site.

**Comment by yortus** [comment]
Bumping this issue again, since 2.1RC [just came out](https://blogs.msdn.microsoft.com/typescript/2016/11/08/typescript-2-1-rc-better-inference-async-functions-and-more/) and is the first release with downlevel async/await (congrats on another great batch of features!).

### Better to annotate each async function, or just polyfill Promise?

A few weeks ago I brought up the quirks of annotating async functions ([here](https://github.com/Microsoft/TypeScript/issues/10844#issuecomment-247829362) and [here](https://github.com/Microsoft/TypeScript/issues/10844#issuecomment-247829746)). @RyanCavanaugh [responded](https://github.com/Microsoft/TypeScript/issues/10844#issuecomment-248064330):
 
> `async` / `await` is indeed the only place where type-directed emit occurs. This is only considered OK because [...] this is a *huge* value add, perhaps the highest emit value prop in the language....

However I noticed the 2.1RC blog post makes no mention of this 'huge' feature when demonstrating [how to use async/await is ES3/5 environments](https://blogs.msdn.microsoft.com/typescript/2016/11/08/typescript-2-1-rc-better-inference-async-functions-and-more/#user-content-downlevel-async-functions). Rather, the blog post describes using a runtime `Promise` polyfill (if necessary) and suitable `Promise` typings. This is the same approach described in the comment before this one.

So to renew the discussion, may I ask again **are non-erasable, non-structural return type annotations really a worthwhile exception in the type system?** They don't seem to have been promoted anywhere. As the blog post shows, they aren't even necessary for using async/await in ES3/5. And they have several downsides.

### Downsides to annotating async functions

Importantly, there are *downsides* to using return type annotations for type-directed emit:
* **it violates a number of TS design goals**, most obviously *"9. Use a consistent, fully erasable, structural type system."*
* it is a divergence from ES2017 async functions, and is *not allowed* in ES6+ targets anyway
* it invite users to write ES3/5 code that cannot be simply updated to an ES6+ target.
* it is repetitive/non-DRY, requiring manual annotations on individual async functions instead of a single polyfill.
* it reduces type-system expressivity (an example is [here](https://github.com/Microsoft/TypeScript/issues/6686#issuecomment-176758649))
* it is inconsistent with all other type annotations in TS (hence surprising/confusing)
* the annotations are non-erasable in ES3/5, since adding/removing them can change runtime behaviour
* the annotations are non-structural in ES6+ as described [here](https://github.com/Microsoft/TypeScript/issues/10844#issuecomment-247829746)

### Future TS Versions?

So is there any chance of a future version having async function return type annotations that are consistent with the rest of the language? The breaking change is straightforward for users to fix, and I suspect most users are not even aware of the current behaviour.

The scenario that type-directed emit specifically caters for is when a project has async functions that must produce several different implementations of `Promise`. How common is that? And it could be achieved through simple wrappers anyway.

**Comment by RyanCavanaugh** [comment]
Polyfilled Promises are rapidly vanishing from the earth; I think we're satisfied with the design as-is here unless there are more concrete manifestations down the line (please raise those as new issues if so)
