### ISSUE TITLE
Shared generics allow optional value for a required field

### ISSUE THREAD

**Issue by vnnh** [microsoft/TypeScript#60090]
### 🔎 Search Terms

`generic function`, `shared generic`, `same generic`, `optional value in required field`

### 🕗 Version & Regression Information

This behavior occurs in `5.5.3` and `5.6.2`, which are the only versions I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABKMAeAKgPgBQEMBci6ANIgEaHoCUiA3ogL4BQTECAzlIm2JwE64YYLgF46iPgFMAjiBhSAJgH1gMSQBsFhKHxCTGAbibrJXCuThwTuJAB9E4BZNVhJCoymw9+g4aXpSsvJuKmqahGSMVAaIAPSxiAByAPKIAKIAShnJGTEAggAyBckA6gDKiABiOYh5iYjJAAroAJLJiYWIAGqFAKppAHSIJdmJAOIAhCye3jq+UP4SMnKKoRpaiDp6UTHxiADucHwA1uyIuGeSAB4ADpLQbkwzHHNCC+KBKyGq64SOzkI3Ds4glJHw+EczhdENc7g93IgALYgThI3BQCAAC02AE87og4MBkGEFE9wF4XgI3osBGAFHBEWtwptdPoGNEQTDwZDzpdbvcoG4YmA4DCrnNXHAUcT1uwyWAKbxXn46OzdqDuXwoXy4YKEcjUU4XPpcOp1DLNGchOcgA

### 💻 Code

```ts
function fun<T>(a: T, b: T) { }

const constraint = { required_field: true };
let b: boolean | undefined;
fun(constraint, { required_field: b }); // NO ERROR; ALLOWS FOR AN OPTIONAL VALUE. WRONG!

fun(constraint, { required_field: true }); // works as expected
fun(constraint, { required_field: undefined }); // errors as expected; must match type of field
fun(constraint, { random_field: true }); // errors as expected; no extraneous fields
fun(constraint, {}); // errors as expected; must define all fields in a
```

### 🙁 Actual behavior

TypeScript does not bring up an error for the first case, even though an optional value is passed for a required field defined by the constraint type in the parameter `a`.

### 🙂 Expected behavior

The first case should have an error.

It is expected that the second parameter `b` should have to strictly match the type defined in the first parameter `a`. The four cases at the bottom of the code snippet align with this behavior. However, TypeScript does not find any errors with the first case, even though an optional value is being passed for a required field. This is not consistent with the previous behavior.

### Additional information about the issue

It must be noted that using a variable has different behavior from simply passing the value as a parameter.
For example,
```ts
fun({ required: true }, { random_field: true });
/*
Generic in this case is
{
    required: boolean;
    random_field?: undefined;
} | {
    random_field: boolean;
    required?: undefined;
}
*/
```
Whereas the problem snippet uses a variable, which seems to make the other parameter constrained to strictly match it.

The behavior seems as if giving an optional value makes the generic revert back to the same behavior as when a value is passed in rather than a variable.

**Comment by MartinJohns** [comment]
> It is expected that the second parameter `b` should have to strictly match the type defined in the first parameter `a`.

But that's not the case. Inference can occur from both arguments. If you want to prevent this, then you can use `NoInfer<>` to stop inference from the second argument: `function fun<T>(a: T, b: NoInfer<T>) { }`

**Comment by vnnh** [comment]
Thank you! `NoInfer<T>` does solve my problem; I never would have guessed that it existed. My problem was that I was assuming they strictly matched when passing a variable for `a`, because all of the other lines of code behaved as if that was the case (didn't allow any extraneous fields, etc.), except for this case where the second argument had an optional *variable* passed in for a field.
