### ISSUE TITLE
Ignore the unreachable code detection error about a tail throw statement as a tail unreachable statement assertion

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6009]
Unreachable code detection cannot to be the perfect in JavaScript because JavaScript cannot segregate the main statement block(for detect the tail statement of main flow in function) and the declaration block like a where statement of Haskell. We cannot find the tail statement without an assertion such as return, throw or assert(false).

So unreachable code detection should ignore once about a tail throw statement:

expected:

```ts
function f(n) {
    switch (n) {
        case 0:
            return 0;
        default:
            if (n > 0) {
                return n;
            }
            else {
                return -n;
            }
    }
    // tail unreachable statement assertion
    throw new Error; // should not be unreachable code error
    throw new Error; // unreachable code error

    function g() {
    }
    // many functions...
    function z() {
    }

    // bad hidden code
    return n; // unreachable code error
}
```

fault but no error:

```ts
function f(n) {
    switch (n) {
        case 0:
            return 0;
        default:
            if (n > 0) {
                return n;
            }
            // forgotten else...
            //else {
            //    return -n;
            //}
    }
    // tail unreachable statement assertion
    // throw new Error;
    // throw new Error; // unreachable code error

    function g() {
    }
    // many functions...
    function z() {
    }

    // bad hidden code
    return n; // not unreachable code error
}
```

This fault code cannot detect by `--noImplicitReturns` and unreachable code detection but those language functions reject the tail unreachable statement assertion. It is bad conflict.

**Comment by vladima** [comment]
I'd say that the reason for this issue is specific coding style and thus it can be captured by syntactic linting rules (something like function declarations at the end of function body should not be mixed with statements).

**Comment by falsandtru** [comment]
> this issue is specific coding style ... something like function declarations at the end of function body should not be mixed with statements

Yes, but it is not the point.

> it can be captured by syntactic linting rules

It is good rules but how can I get it error?

Those language functions cannot reject that mistakes caused by that coding style, and reject the correct counter measure. Those constraints makes a new risk. Will you accept it risk and weakness as a spec? I think, it is not good as a language.

**Comment by DanielRosenwasser** [comment]
We can't pick apart what would be considered an "acceptable" snippet of code that's unreachable. Better than a `throw` statement would be a filler comment like `////////////////////////////`.

**Comment by DanielRosenwasser** [comment]
Alternatively, you can use a `fail` function for now:

```ts
function fail() {
    throw "Unreachable";
}
```

**Comment by falsandtru** [comment]
How do I use it function? It seems useless.

```ts
function f() {
  if (true) return;
  fail(); // unreachable error
  function fail() {
    throw "Unreachable";
  }
}
```
