### ISSUE TITLE
Array.some should reflect that the array is not empty

### ISSUE THREAD

**Issue by matthieusieben** [microsoft/TypeScript#60103]
### ⚙ Compilation target

es5

### ⚙ Library

es5

### Missing / Incorrect Definition

`some` in `lib.es5.d.ts` could be defined as follows (return type from `boolean` to `this is [T, ...T[]]`):

```ts
interface Array<T> {
    some(predicate: (value: T, index: number, array: T[]) => unknown, thisArg?: any): this is [T, ...T[]];
}
```

### Sample Code

[playground](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABAJwKYEcQzQZwPJioCSUqAtgDwAqAfABQCGyyDAngFyIDaVANIgDohVLgF1RASkQBvAL4AoeaEiwEiGDgBicONXoxSZTlSnT5iFKighkSKMhCp5C+RAQ4oiJi1aIAvNwAjPwATKKKMMCIjMxsAjhwZKh0GtpwEqbmlpjYqPiEJOQxPhLOEWCkyMAMEKiIAIKxrHoyWRYA9O2IAKqQiUkViFBwQ3lQ7G2InYgJSXQADmgAJjAQDKScdABuDAA2jsb8MGBLqAAenGAgZABGqMj83mzGYlJ+NIjgANZgcADuYH4UAAFhpGgBzAD8nAYYFYEk4II06hw3D4gmEYlEAG4ykA)

```TypeScript

function requiresOneItem<T>(array: [T, ...T[]]) {}
function isFoo<T>(item: T) { return true }

const array = [1, 2]

if (array.some(isFoo)) {
  requiresOneItem(array) // Argument of type 'number[]' is not assignable to parameter of type '[number, ...number[]]'.
}


interface Array<T> {
    // Uncomment to test:
    // some(predicate: (value: T, index: number, array: T[]) => unknown, thisArg?: any): this is [T, ...T[]];
}

```

### Documentation Link

N.A. Calling `.some()` on an array can only ever return true if the array is not empty.

**Comment by RyanCavanaugh** [comment]
Type guards must *always* return `true` if the object matches the specified type.
```ts
function requiresOneItem<T>(array: [T, ...T[]]) {}

function isEven(item: number) {
  return item % 2 == 0;
}

const array: [number, ...number[]] = [1, 2]

if (array.some(isEven)) {
  requiresOneItem(array)
} else {
  const n = array;
  // n: never, which is wrong
}

interface Array<T> {
    // Uncomment to test:
    some(predicate: (value: T, index: number, array: T[]) => unknown, thisArg?: any): this is [T, ...T[]];
}
```

**Comment by matthieusieben** [comment]
Right. Too bad we can't model non empty arrays in a way that would make this work.

**Comment by matthieusieben** [comment]
Thank you for you help and your time still :-)
