### ISSUE TITLE
Index signature type checking too strict

### ISSUE THREAD

**Issue by TotempaaltJ** [Microsoft/TypeScript#6011]
Setting an index signature as anything else than `number` or `string` will throw TS1023 error "An index signature parameter type must be 'string' or 'number'." Thus it does not allow constructs like:

    type Foo = string;
    interface Indexed {
        [index: Foo]: any;
    }

It also doesn't allow setting the type as `number | string`, although that may be intended behaviour? Can't think of any reason why it wouldn't be allowed but then I'm not that intimately familiar with Typescript.

**Comment by RyanCavanaugh** [comment]
It's currently disallowed by the grammar because we haven't seen any reason to allow a different syntax.

What's the goal of using `Foo` here? It seems obfuscatory (I have to look up `Foo` to see if it's `number` or `string`, which are the only two things it could possibly be), and there's already a place (`index`) to put a descriptive name if you want to give consumers an indication of what the key names should consist of.

**Comment by adidahiya** [comment]
I ran into a similar issue. I'd like to index into an object with an enum:

```ts
enum SortDirection {
    ASC,
    DESC
}

const SORT_LABEL_MAP: {[key: SortDirection]: string} = {
    [SortDirection.ASC]: "↑",
    [SortDirection.DESC]: "↓"
};

function getColumnLabel(sortDirection: SortDirection) {
    return SORT_LABEL_MAP[sortDirection];
}

getColumnLabel(SortDirection.ASC); // "↑"
```

**Comment by TotempaaltJ** [comment]
Ah yes, you're probably right @RyanCavanaugh. I've been thinking a bit more about it and I don't think it's a necessary feature anymore, so I guess @adidahiya's issue is still left.

**Comment by adidahiya** [comment]
@RyanCavanaugh I'd be happy to open a separate issue if you prefer.

**Comment by GoToLoop** [comment]
> (I have to look up Foo to see if it's number or string, which are the only two things it could possibly be)

Perhaps besides string & number, it should also accept string literals & enums?

**Comment by DanielRosenwasser** [comment]
@adidahiya that would be #2491.

**Comment by RyanCavanaugh** [comment]
Re #2491 -- we discussed it and decided against it. Given the number of suggestions already in the queue, we don't have resources to endlessly relitigate things. People can leave their comments there and we can review again at a later date, but its short-term status remains declined.

**Comment by adidahiya** [comment]
cool, that makes sense. thanks :+1:

**Comment by championswimmer** [comment]
Ok, How about this ? 

```typescript
export interface ProductCategoryAttributes {
    id: number,
    name: string,
    emi_allowed: boolean,
}

type ProductKeys = keyof ProductCategoryAttributes

interface ProductDefineAttributes {
    [x: ProductKeys]: string | DataTypeAbstract | DefineAttributeColumnOptions
}

export const productCategoryAttrs: ProductDefineAttributes = {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    name: {
        type: Sequelize.STRING,
        allowNull: false,
        unique: true
    },
    emi_allowed: {
        type: Sequelize.BOOLEAN,
        defaultValue: false
    }
}
```

**Comment by mhegazy** [comment]
did you mean:

```ts
type ProductDefineAttributes = {
    [x in ProductKeys]: string | DataTypeAbstract | DefineAttributeColumnOptions
}
```

**Comment by championswimmer** [comment]
Whoops ! Didn't know it works in `type` 

Thanks a lot !
