### ISSUE TITLE
Destructuring result of String.split gives too strong type.

### ISSUE THREAD

**Issue by ThePlenkov** [microsoft/TypeScript#60111]
### 🔎 Search Terms

I checked docs

### 🕗 Version & Regression Information

"typescript": "~5.5.2",

### 💻 Code

```ts
const npm_config_user_agent = process.env["npm_config_user_agent"] || '';
const [packageManager, engine, platform, arch, ...rest] = npm_config_user_agent.split(" ");
const [engineName, engineVersion] = engine.split("/");
```

### 🙁 Actual behavior

- npm_config_user_agent is a variable of type string, which is right because we're adding || ''
- engine - has also a string type, while only first element of split array should have a strict string type
- all next elemets should have weaker type string | undefined because if not splitted - they are just empty
- as a result the last destructuring command gives no errors while it fails in runtime because engine is undefined

### 🙂 Expected behavior

- split command should return strong string only for a first array element and starting from second one it's string | undefined

This is especially important for destructuring operations. Of course for code like

for..of it should not matter because it makes sure element is created.

### Additional information about the issue

nothing special

**Comment by Andarist** [comment]
You are interested in `noUncheckedIndexedAccess`: https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess

**Comment by ThePlenkov** [comment]
@Andarist right on spot! Thanks, then is not an issue of course!
