### ISSUE TITLE
A type to unwrap a boxed type (analogous to Awaited<T>) only works if implemented exactly like Awaited<T>

### ISSUE THREAD

**Issue by itsgiacoliketaco** [microsoft/TypeScript#60112]
### 🔎 Search Terms

unwrap, unbox, awaited

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ (I looked through the whole thing!)
    - Maybe it has to do with [Structural vs Instantiation-Based Inference]?
(https://github.com/Microsoft/TypeScript/wiki/FAQ#structural-vs-instantiation-based-inference)
- This is observable in 4.1.5 as tested in the TS playground; I was unable to test this on prior versions because the `Unbox<T>` type cannot be defined as such: "Type alias 'Unbox' circularly references itself."
- Tried to search for related issues but I'm not sure what keywords are relevant.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.2#code/PTBQIAgIQewDwKYBMIBcCeAHBECuBnZCASwDs0ALHAMxgBs6YB3MgcwgTgEMBbTOhADpwYUGVQIATtS4BjHLERIAPABUAfBADeoCBABuXOrgQAuCKoDcoXRB5dM5gBTVSzrpNbnVASggBeTX0YYiQ-QIMQpGsAXxsREQgAVVIAI3g2CHxUSS4JVnQIAEZhEETVCmJ8CCQYBGrSGFQIJhhJAGtS0QxsZLT4NU1-Cw44CVIkasVkZTJqKQgANU0Afj70uGVliG9rUFkYUmyISXr6fQRplGG1ABp1J1RvCAAfaHgZjR9zK+UUjcGQ00ACJGs1iHwBDwEKQJEhgRAuNUuKR0HsDkdmhJslcAhA7g9DMYzCM3r8vgFNDo9BjjhsiMNTvhzpcPkgnESTD49npIABRSSSNqmWy0rH1J4jYb0pCCTkIHkQGWCeyYJwcoxcynaWy84AQAVCyQivR6ixYHAAcn+Aw0lpIDSaiPw+GIrFIXFSAjQMDQFogltUluEpogkD0gftB1wdBQqRwZGyKNQxDyRBYqAoiPIHlSxByHkKPRwTEqsiz0djSpwuFIpzoaZQqF91v6mztIdN4bQ+CcACYAMx9vs+XUQMVoCXPYby6x6GLc0AxPYJSA2uCZbK5fKFPtdcqVaq1eoQMEtNqdBKgYvreB9wZ41SjcaTbQGTUkuYLRYQGIQNbrve2y7DYE5MiyVx9niBKPM8ZJsoM3zvEofxtveGhAhAoJOhC-AINCsLIAiSLZmioGHMc2KoJB0GqPcGrEnByGfOo4RUqKFHNDKeLgXQFyQQxXKKvygrChxmKTtk05Kmycofoqyqquq8psTqoYiUaJqmhOVHSbOtgLrEK5lGubabgWO4QAOtwtGWWaMDA7TIhAjDNHQxDtDgACCTBcPmLH7pAFRVOeHT4Pu17+uuA4PsMT6cC+1RaHYDguG4JCkPMkgQAAYjZggFR4rD4OYX7ZQA+khKKFHEehrDlz4wq+gmfpl375YVnglRlWUQJV2rVWOAFtjFyxjuYpAIBcki2CB+ycScZx8aySgDrR9GSk+8EoV8PwIdFgLath4KQvhMJwsRyKouiC1UVca03HRhIfkx5Ksdq1Ljgt3GMkt-FsgOLWLrYkAAOoXiV4mUVOUoyUocnEgpslKUDH1jmDENaTSt0w0+M7yQZi7LvEJn6ny3CnS0+ZZgACkKPBVAgNmlsQ5Z4IQEA+X5cIPs2eBtl0EAHiFnC8HhoVORFOkSnTMAMxzj30fKTGy-LCCIWj2MSZg9OM3iquM4IvEXEDio63LhuZjCykfqpn1muDYVY19Em6bD+nzkTlhAA

### 💻 Code

```ts
interface Boxed<T> {
  value: T;

  map: (fn: (arg: T) => void) => void;
}

type Unbox<T> = T extends Boxed<infer V> ? Unbox<V> : T;

const resolveBoxed = <T>(t: T | Boxed<T>): Boxed<Unbox<T>> => {
  return "not implemented" as any;
};

const testBoxed = <T>(value: T | Boxed<T>) => {
  const boxed = resolveBoxed(value);
  // Error:
  const test: T = boxed.value;
};
```

### 🙁 Actual behavior

I receive the error:
```
Type 'Unbox<T>' is not assignable to type 'T'.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'Unbox<T>'.
```

### 🙂 Expected behavior

I would not expect an error.

### Additional information about the issue

What I find curious is that the following implementation of `Unbox<T>` _does_ work:
```ts
type Unbox<T> = T extends { map(fn: infer F, ...args: infer _): any }
  ? F extends (value: infer V, ...args: infer _) => any
    ? Unbox<V>
    : never
  : T;
```

This implementation is inspired by the implementation of `Awaited<T>`.  As shown in the provided TS playground, an analogous version of my `testBoxed` function using promises works.

Is this a bug? I understand that it may not be!  However, it's not intuitive to me why adding this extra layer of indirection/conditional type suddenly makes things work.  Given the premise of my example, I would expect things to either always work or always fail, regardless of the implementation of `Unbox<T>` (assuming it is meant to recursively unwrap a `Boxed<T>`).

Thanks!

**Comment by guillaumebrunerie** [comment]
I don't think that the `testBoxed` function is correct. For instance assume that `T` itself is `Boxed<number>`, then `boxed.value` is of type `number` which is not assignable to `T`.

> I would expect things to either always work or always fail, regardless of the implementation of `Unbox<T>` (assuming it is meant to recursively unwrap a `Boxed<T>`).

I would definitely not expect that. Even if the two implementations did exactly the same thing, it doesn't mean that TypeScript can statically analyze them in the same way. Now I don't know exactly why the second one works, but the fact that there is a difference in behavior isn't particularly surprising to me, you often have to be careful with how exactly you implement a given generic type so that it will work in all situations you care about.

**Comment by itsgiacoliketaco** [comment]
Thanks for weighing in @guillaumebrunerie.

> I don't think that the testBoxed function is correct. For instance assume that T itself is Boxed<number>, then boxed.value is of type number which is not assignable to T.

Yes, good point.  I recognize this ambiguity.  Without an `extends` constraint on the generic, `T | Boxed<T>` is sort of equivalent to just `T`, at least until `T` is bound to a specific type.  (If I could do `T extends Not<Boxed<T>>` then it might make sense!)

That said, I'm not sure it's _incorrect_—or at least no _more_ incorrect than the type for `Promise.resolve()` in the standard library 😄   (Implementing `resolvedBoxed` with overloads does not seem to change the behavior.)

```ts
// From typescript/lib/lib.es2015.promise.d.ts

interface PromiseConstructor {
    // ...
    resolve(): Promise<void>;
    resolve<T>(value: T): Promise<Awaited<T>>;
    resolve<T>(value: T | PromiseLike<T>): Promise<Awaited<T>>;
}
```

I can accept that different implementations of `Unbox<T>` will behave differently for what appear to me to be obscure reasons.  I can just follow the implementation of `Awaited<T>`, since I know that will continue to work in future versions.

I'll go ahead and close this issue.
