### ISSUE TITLE
Intellisense "includes" breaks after many large files

### ISSUE THREAD

**Issue by oriooctopus** [microsoft/TypeScript#60124]
### 🔎 Search Terms

vscode, includes, large

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about includes

### ⏯ Playground Link

The readme describes how to reproduce the issue

https://github.com/oriooctopus/intellisense-bug

### 🙁 Actual behavior

Intellisense fails with an `includes` error even though the file is included. This directly correlates with the number of files in the `images/animations` folder. If you remove even one of them, the error will go away. This is because after reaching a certain amount of large files, typescript begins to have the issue

![Screenshot 2024-10-02 at 10 40 32 PM](https://github.com/user-attachments/assets/8b8d3ed2-fef3-4acf-bf83-9bf9563ebb75)

### 🙂 Expected behavior

I understand that typescript encourages `excludes`, but sometimes that is not easily achieved as we need these image file. At the very least though, the error shown is a misleading one.

### Additional information about the issue

This appears on intellisense but I believe the problem/solution most likely lies within Typescript itself

**Comment by RyanCavanaugh** [comment]
We have a hardcoded limit of 20 MB of ingestion here. You'll need to put them in `files` if you really truly want to process that much input (I don't recommend doing that, but it is what it is).
