### ISSUE TITLE
If `tsc` finds 0 errors, log using `console.log` instead of `console.error`

### ISSUE THREAD

**Issue by Anoesj** [microsoft/TypeScript#60128]
### 🔍 Search Terms

- Found {0} errors. Watching for file changes.
- Found 0 errors. Watching for file changes.
- Vite "ERROR" in `tsc` / `vue-tsc`

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

While `tsc` watches for changes in files, it logs the number of errors it found. However, it always logs them using `console.error`, even if 0 errors are found. In Vite, this results in the following confusing message:
![image](https://github.com/user-attachments/assets/f15ae8a1-b3b7-4d80-af42-41492702b651)

I know I'm nitpicking here, but it would be nice and clean if `tsc` would use `console.log` if `errorCount === 0`.

Related: https://github.com/vuejs/language-tools/issues/3579

### 📃 Motivating Example

In the past, `tsc` would report that 0 errors were found using `console.error`, which may be confusing to users of Vite, where error logs are labeled with a big red ERROR block.
![Screenshot from 2024-10-03 13-45-35](https://github.com/user-attachments/assets/68625ede-69cf-4e6c-9552-10d545e5dab6)
To prevent confusion, `tsc` now uses `console.log` when zero errors were found.

### 💻 Use Cases

1. What do you want to use this for? ➡️ _Prevent confusion for Vite users._
3. What shortcomings exist with current approaches? ➡️ _There are no real shortcomings, it's just a minor inconvenience._
4. What workarounds are you using in the meantime? ➡️ _None._

**Comment by Anoesj** [comment]
Ah, I'm sorry! I did take a look at the TypeScript codebase to find out more about the logging system, but couldn't really fully understand it. I'll see if this is a `vue-tsc` issue and close this issue then.

**Comment by RyanCavanaugh** [comment]
I used to own a logging component for a divisional test framework; at the end of the test it would print e.g.

> 0 errors found
>
> Test passed

Someone emailed me to ask why we were marking tests as passed when there were "`errors found`"

Anyway I suspect that's what's happening here 🙂
