### ISSUE TITLE
ScriptKind.Deferred treated as LanguageVariant.Standard

### ISSUE THREAD

**Issue by blake-newman** [microsoft/TypeScript#60125]
### 🔎 Search Terms

Deferred ScriptKind TSX
Deferred ScriptKind Standard

Vue, eslint, tsx parser error

### 🕗 Version & Regression Information

Currently looking at TypeScript 5.5+ likely affects most versions of typescript.

### 💻 Code

Not specific to TS code but compiler and parsing. 

### 🙁 Actual behavior

When using typescript-eslint with there new projectSettings option, along side vue with tsx. The file fails to parse

```
Component.vue
41:8  error  Parsing error: '>' expected
```

Deferred ScriptKinds are treated as `LanguageVariant.Standard` rather than `LanguageVariant.JSX`

https://github.com/microsoft/TypeScript/blob/main/src/compiler/parser.ts#L1746
https://github.com/microsoft/TypeScript/blob/main/src/compiler/utilities.ts#L8832

### 🙂 Expected behavior

Under the assumption that ScriptKind.Deferred could be treated as `LanguageVariant.JSX` then this resolves `typescript-eslints` issue with parsing extraFileExtensions such as `vue` files. 

I'm unsure what the consequences and other use cases of `ScriptKind.Deferred` are so it could be as simple as adjusting `getLanguageVariant`.

### Additional information about the issue

https://github.com/typescript-eslint/typescript-eslint/issues/9934

**Comment by RyanCavanaugh** [comment]
This would just change how the problem could happen. In a non-JSX file you might need have a `<type>expr` type assertion that would then parse incorrectly.

I don't know why typescript-eslint is using `Deferred` but that's probably the root cause here

**Comment by blake-newman** [comment]
@RyanCavanaugh sorry for the delay; was looking more into the source of `typescript-eslint` source code to understand why it was marked as Deferred.

From what I understand `extraFileExtensions` such as vue are marked as `Deferred` as they are never part of the root files of a project. So this allows the project service to resolve the extra file extension when it is discovering files in the project. This happens as part of the project service internals and not typescript-eslint. 

Marking the file as `ScriptKind.TSX/TS` for the extra file extensions for the project service will result in the following error:
> Parsing error: ....vue was not found by the project service

This is due to the project service being unable to resolve the file as part of a project because it's not a known extension and thus means ts doesn't respect it as part of the program root files. 

---

From my perspective, it makes sense for `typescript-eslint` to mark the extra file extensions as `Deferred` as they are not truly part of the TS project.

> This would just change how the problem could happen. In a non-JSX file you might need have a <type>expr type assertion that would then parse incorrectly.

Yes agree; however this now means we run into issues where Deferred files use TSX syntax, and thus they can't parse. As mentioned we can't flip the logic as this would break the other assumption...

I've tested adding the ability of a new `DeferredTSX` for the script kind, so consumers can specify the language type as for the deferred file types. This solves things in typescript eslint as now we can specify extra file extensions to use the correct language type for parsing extra files based on the ` ecmaFeatures: { jsx: true },` option.

**Comment by RyanCavanaugh** [comment]
> Changing to...

We could try a PR for this.

**Comment by sheetalkamat** [comment]
There is host configuration command on tsserver that lets you set script kind for file extensions .. using deferred is just default and let plugins handle through wrapping getScriptKind kind of facility so I don’t think the change you are suggesting is the one you need

**Comment by sheetalkamat** [comment]
> From what I understand `extraFileExtensions` such as vue are marked as `Deferred` as they are never part of the root files of a project. So this allows the project service to resolve the extra file extension when it is discovering files in the project. This happens as part of the project service internals and not typescript-eslint.

Also from plugin perspective they are part of root projects and they are provided through `getExternalFiles` in normal editing scenario. A

**Comment by blake-newman** [comment]
> There is host configuration command on tsserver that lets you set script kind for file extensions .. using deferred is just default and let plugins handle through wrapping getScriptKind kind of facility so I don’t think the change you are suggesting is the one you need

```ts
service.setHostConfiguration({
      extraFileExtensions: extraFileExtensions.map(extension => ({
        extension,
        isMixedContent: false,
        scriptKind: ts.ScriptKind.Deferred,
      })),
    });
```

Typescript eslint does what you are describing i believe.

However if you say set set `scriptKind` to `ts.ScriptKind.TSX`, the internals of [getSupportedExtensions](https://github.com/microsoft/TypeScript/blob/main/src/compiler/utilities.ts#L9867) will end up stripping that extension out as it's not regarded as a `Deferred` script kind. 

That method is then used in many places (when building up the project state). 

Is there an alternative host configuration that should be set?

**Comment by blake-newman** [comment]
@sheetalkamat just a ping to see if you have any follow up information. No matter what combinations I've tried, the only way I seem to be able to solve is via #60178

It seems we need typescript to run with Deferred script kind, because `.vue` is an extra extension that TS shouldn't care about.  The above change in the PR allows differed script kinds to be marked as a supported extension.

**Comment by eric-gitta-moore** [comment]
For any friends who have found this, if you are using the `@typescript-eslint/consistent-type-exports` ESLint rule and it has caused the `<script lang='tsx' setup>` in Vue to fail to be linted and parsed, resulting in the error `error  Parsing error: '>' expected`,

Solution:
- If you continue to use the `consistent-type-exports` rule, please patch the `typescript` compiler with [typescript.patch](https://github.com/leondreamed-archives/vue-eslint-plugin-jsx-bug/blob/main/patches/typescript%2B4.6.3.patch).
- If you only use `consistent-type-imports` and not `consistent-type-exports`, then please set `parserOptions.project` and `parserOptions.projectService` in `.eslintrc.js` to `false`.
