### ISSUE TITLE
Is there any plan to support tc39/proposal-decorators/EXTENSIONS?

### ISSUE THREAD

**Issue by alamhubb** [microsoft/TypeScript#60127]
### 🔍 Search Terms

Is there any plan to support tc39/proposal-decorators/EXTENSIONS?

https://github.com/tc39/proposal-decorators/blob/master/EXTENSIONS.md#let-decorators

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

https://github.com/tc39/proposal-decorators/blob/master/EXTENSIONS.md#let-decorators

### 📃 Motivating Example

https://github.com/tc39/proposal-decorators/blob/master/EXTENSIONS.md#let-decorators

### 💻 Use Cases

https://github.com/tc39/proposal-decorators/blob/master/EXTENSIONS.md#let-decorators

**Comment by alamhubb** [comment]
> The extensions are not standardized, so no.

I really want this feature. If TypeScript cannot support it, what other options do I have? Do you have any suggestions? Thank you.

**Comment by nmain** [comment]
Typescript generally only supports things that have a TC39 proposal for them, and have then advanced to Stage 3.    In this case, decorators are stage 3, but that extensions document is just a collection of possible future ideas which were not submitted as part of the decorators proposal.

**Comment by RyanCavanaugh** [comment]
Extensions aren't stage 3; we don't add things to TS until that point

**Comment by alamhubb** [comment]
> Extensions aren't stage 3; we don't add things to TS until that point

I really want this feature. If TypeScript cannot support it, what other options do I have? Do you have any suggestions? Thank you.

Does typescript support custom syntax plugins?

**Comment by MartinJohns** [comment]
> Does typescript support custom syntax plugins?

No.

> I really want this feature. If TypeScript cannot support it, what other options do I have? Do you have any suggestions?

I'm not aware of any language that supports this feature, so your options are almost non-existent. You could fork TypeScript and add the feature yourself (and maintain the fork).

**Comment by alamhubb** [comment]
> > Does typescript support custom syntax plugins?
> 
> No.
> 
> > I really want this feature. If TypeScript cannot support it, what other options do I have? Do you have any suggestions?
> 
> I'm not aware of any language that supports this feature, so your options are almost non-existent. You could fork TypeScript and add the feature yourself (and maintain the fork), but you're on your own in doing so.
> 
> Realistically, you just have to do without this feature, no matter how much you want it.

Thank you for your advice
