### ISSUE TITLE
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

### ISSUE THREAD

**Issue by danikane** [microsoft/TypeScript#60132]
Hi, 
JavaScript and TypeScript Nightly version `5.7.20240928` and subsequent versions report the above message.

Next.js 13 or 14, pages router
Windows 10 with WSL2
VSCode 1.93.1

This is a React Fragment and there are several workarounds, but none of them are desired:
- import React obviously
- change `"jsx": "preserve"` -> to `"jsx": "react-jsx"` in `tsconfig.json` in which case Next will slap you 
![image](https://github.com/user-attachments/assets/12499928-4afa-4df3-9440-4794410e129f)
- change to `div` or whatever :)

![image](https://github.com/user-attachments/assets/30ffaa44-8e92-46ac-9c47-ddd7040eddd1)

![image](https://github.com/user-attachments/assets/2f0eb4f8-8df2-42f7-a6a7-1203d0058f63)
![image](https://github.com/user-attachments/assets/8283468f-1593-4704-9f6d-f2b4245028ea)

On a side note **ESLint** doesn't pick it up when linting, but then again it's misleading.
Thanks!

**Comment by iisaduan** [comment]
@danikane does this only happen when the config is set to `jsx: preserve`? If so, can you install and try https://github.com/microsoft/TypeScript/pull/60122#issuecomment-2389709418?

**Comment by danikane** [comment]
Yes, exactly. That's what Next.js automatically sets anyway.
I can try tomorrow if that's ok with and get back with the results.
Thanks!

**Comment by danikane** [comment]
By the way should I leave the latest nightly installed?

**Comment by iisaduan** [comment]
If you `npm install` the dev version I linked, it will remove the nightly version and install the dev version in its place. You can either reference it in your dev dependencies and then run npm install, or use `npm install typescript@npm:@typescript-deploys/pr-build@5.7.0-pr-60122-2` (regardless of what is in your dependencies) to try it out.

**Comment by iisaduan** [comment]
I've made changes to that PR that _shouldn't_ affect typechecking, but I've packed a new version just in case: https://github.com/microsoft/TypeScript/pull/60122#issuecomment-2392749843
`"typescript": "npm:@typescript-deploys/pr-build@5.7.0-pr-60122-16"`

**Comment by danikane** [comment]
Thank you, I confirm the error is no longer reported!

![image](https://github.com/user-attachments/assets/29fa7f35-a676-4934-87c1-20b0fb76689f)

**Comment by iisaduan** [comment]
Great, thank you for confirming!

**Comment by imranbarbhuiya** [comment]
Seems like it's happening in stable release too using `"jsx": "react-native",`

**Comment by imranbarbhuiya** [comment]
Hi @iisaduan, sorry for the ping but should i create a new issue for it or this can fixed from this issue only?

**Comment by ChromeQ** [comment]
> Seems like it's happening in stable release too using `"jsx": "react-native",`

Same thing here

**Comment by iisaduan** [comment]
@imranbarbhuiya Either is fine, thanks for the ping! I'm looking into it.

**Comment by ChromeQ** [comment]
Another nudge as it's been a while, any progress looking into this for `"jsx": "react-native"`?

**Comment by iisaduan** [comment]
@ChromeQ can you try out nightly, and see if the error still occurs? 

For `react-native`, it should be tracked by the new issue and fixed by https://github.com/microsoft/TypeScript/pull/60615 . We haven't had an official release (patch) since 5.7, so there's no stable version with the fix yet

**Comment by jakebailey** [comment]
The PR which closed this issue was in 5.7's RC; are you talking about some other fix? https://github.com/microsoft/TypeScript/pull/60615 mentioned above was in 5.7.3. I don't think there is anything in this thread that is unreleased in some stable version.

**Comment by techgerm** [comment]
@jakebailey my apologies, to my knowledge there doesn't seem to be an easy way for me to check in which release a certain fix was included so I tried double checking the `5.7` branch and clearly made a mistake then.

Regardless, I was double checking whether the fix was included in `5.7.3` because after updating to this version, it still does not resolve the problem for us and we're also using `"jsx": "react-native".

@ChromeQ can you install `5.7.3` and see if this fixes the problem for you?

**Comment by jakebailey** [comment]
It's possible this is an extension I have, but:

![Image](https://github.com/user-attachments/assets/3c97e93b-22ab-4d30-9dfe-7c889cfbcd30)

![Image](https://github.com/user-attachments/assets/d46d8092-ee5c-4e14-ab63-69f193d55f86)

**Comment by techgerm** [comment]
@jakebailey sorry could you share specifically which extension you have?

**Comment by jakebailey** [comment]
I believe this is something Refined GitHub does.

**Comment by ChromeQ** [comment]
> @techgerm 
> [@ChromeQ](https://github.com/ChromeQ) can you install `5.7.3` and see if this fixes the problem for you?

I've upgraded to latest (and tried downgrading to reproduce the error but cannot anymore) and I can confirm it is working perfectly for me using `"jsx": "react-native"` 🎉 Thank you.

**Comment by techgerm** [comment]
Actually I can confirm that's working for us as well - I didn't realize that my VSCode was using `5.7.2` as appose to my workspace TS version. Thanks @jakebailey! 👏
