### ISSUE TITLE
@types/node's URL is no longer assignable to TS 5.6's DOM URL type

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#60141]
### 🔎 Search Terms

5.6 node DOM URL assignable error

### 🕗 Version & Regression Information

- This changed between versions 5.5 and 5.6

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&ts=5.6.2#code/JYWwDg9gTgLgBAbzgVQEoBk4EMDOcByEAJgKZqYC+cAZlBCHAEQB2xJAXAK5QA2jAUPxIAPSLDgBjCMxzxqECOxQY4AXjjMSAdwJtyACkaMAlENHR4UmfABGWKEsKlyajduXpDJ-kA

### 💻 Code

```ts
import { URL as NodeURL } from "node:url"

export const foo: URL = new NodeURL("")
export const bar: NodeURL = new URL("")
```

### 🙁 Actual behavior

```
Type 'import("url").URL' is not assignable to type 'URL'.
  The types returned by 'searchParams.entries()' are incompatible between these types.
    Type 'IterableIterator<[string, string]>' is missing the following properties from type 'URLSearchParamsIterator<[string, string]>': map, filter, take, drop, and 9 more.
```

### 🙂 Expected behavior

No error.

### Additional information about the issue

Repro here: https://github.com/remcohaszing/typescript-node-dom-url

Thanks @remcohaszing for finding this bug and creating repros for it.

**Comment by rbuckton** [comment]
This should be addressed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70648
