### ISSUE TITLE
Is there an official typescript ebnf? Is the official willing to maintain one?

### ISSUE THREAD

**Issue by alamhubb** [microsoft/TypeScript#60153]
### 🔍 Search Terms

JavaScript has an ECMAScript language specification, https://tc39.es/ecma262/. Does TypeScript have such a specification file?

**Comment by MartinJohns** [comment]
TypeScript does not have any form of specification, and afaik does not intend do have one again. They used to have a specification, but it was heavily outdated and the manpower needed to keep it up to date was much better used elsewhere.

**Comment by alamhubb** [comment]
> TypeScript 没有任何形式的规范，据我所知，他们也不打算再制定一个。他们曾经有一个规范，但它已经严重过时了，而保持其更新所需的人力最好用在其他地方。
> 
> 另请参阅：[#15711（评论）](https://github.com/microsoft/TypeScript/issues/15711#issuecomment-409282464)

Thank you for answering my question so promptly.

**Comment by alamhubb** [comment]
> TypeScript does not have any form of specification, and afaik does not intend do have one again. They used to have a specification, but it was heavily outdated and the manpower needed to keep it up to date was much better used elsewhere.
> 
> See also: [#15711 (comment)](https://github.com/microsoft/TypeScript/issues/15711#issuecomment-409282464)

Thank you for answering my question so promptly.
