### ISSUE TITLE
Generic type that split members of union type when using extends keyword

### ISSUE THREAD

**Issue by marcvincenti** [microsoft/TypeScript#60154]
### 🔎 Search Terms

return type boolean union extends

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about extends keyword.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.2#code/C4TwDgpgBA6gTgQzAMQHYB4AqA+KBeKTKCAD2AlQBMBnKZAV1QGNgBLAe1SgH5CoAuKAAoAlPlyYA3AChpoSFABC7dgBs0+WIhQYARitUQEqbDOkB6c1AASEONGVqN96moBu0YOygADIaPEoADMEVWoIMQAfYQC8XGA4egifCytFemAoVkzqAAt2elVKKF1oPzE4koMjVBTpJk5qTP0nVEFHdS4CUUEWw2NAhKTJKFSoAFE4OHY4QUxwaAByWNw+msWs2lR2TIRqalYAc1QEXUMoLwuFqEWOtEWAOmkgA

### 💻 Code

```ts
type WrapFn<T> = T extends Function ? T : () => T;

type BoolFn = WrapFn<boolean>;

// Here BoolFn resolve to `(() => false) | (() => true)`
// But it should be `() => boolean` or `() => false | true`

const boolFn: BoolFn = (): boolean => true; 
// Error: Type '() => boolean' is not assignable to type 'BoolFn'.
```

### 🙁 Actual behavior

`WrapFn<boolean>` is splitted in `(() => false) | (() => true)`.

So when an interface wait for `WrapFn<boolean>`, i cannot use a function with the signature `() => boolean`

### 🙂 Expected behavior

The `WrapFn<boolean>` should resolve to one function type `() => boolean` or `() => false | true`. 
This shouldn't return an union of function types.

### Additional information about the issue

This problem extends to all union types.

**Comment by jcalz** [comment]
Working as intended, duplicate #51822
