### ISSUE TITLE
Support for Alias in Specific Imports

### ISSUE THREAD

**Issue by rkrisztian** [microsoft/TypeScript#60168]
### 🔍 Search Terms

Import with namespace for specific imports

### ✅ Viability Checklist

- [X] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [X] This wouldn't change the runtime behavior of existing JavaScript code
- [X] This could be implemented without emitting different JS based on the types of the expressions
- [X] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [X] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [X] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I would like to propose support for the following import syntax in TypeScript:

```typescript
import { readFile, writeFile } as fs from 'node:fs';
```

### 📃 Motivating Example

The reason is, star imports make the bundle size hard to optimize by bundlers, as they can't use tree shaking effectively:

Currently, using star imports can lead to suboptimal bundle sizes because bundlers struggle to perform effective tree shaking:

```typescript
// Tree shaking issue
import * as fs from 'node:fs';
```

On the other hand, importing specific functions loses the ability to group them under a namespace, which helps identify the module source:

```typescript
// Lost the ability to put functions in a namespace
import { readFile, writeFile } from 'node:fs';
```

### 💻 Use Cases

* By allowing specific imports to be grouped under an alias, bundlers can perform better tree shaking, resulting in smaller bundle sizes.
* This feature would enable developers to maintain a clear namespace for imported functions, improving code readability and maintainability.

Thank you for considering this feature request.

**Comment by rkrisztian** [comment]
Note: I probably should have proposed this to the EcmaScript standard, but nothing seems to be happening in terms of this kind of readability improvement, even though I’m not the only one who finds it useful:

https://stackoverflow.com/questions/72888348/es6-modules-import-specific-functions-as-aname

**Comment by jcalz** [comment]
So you're aware that it's a JS thing and not a TS-only thing, then? That means this should not be checked:

> * [x]  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)

and as such, they're just going to decline this. TS is no longer in the business of adding new runtime stuff.

**Comment by rkrisztian** [comment]
Well, addressing the ES standard is much harder. So I thought let's try in a language that is better...
