### ISSUE TITLE
Ambiguous scoping of if statement body

### ISSUE THREAD

**Issue by acutmore** [microsoft/TypeScript#60175]
### 🔎 Search Terms

type, scoping, ifStatement

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type scoping

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.2#code/GYVwdgxgLglg9mABMAjACgJSIN4ChEGIzCJpQBOIAphvoYVAJ4AOViAzogLwcUxgBzANx16iCAnZwANlQB00uALQAiFYgCGndhhH1cAX1y5QkWAmQAmTDlFESZSjVtj6TVh269y-YXaP0EmBSsgpKqupaHLqGuEA

### 💻 Code

```ts
function f1() {
    if (true)
       type s = string;
       console.log("" as s);
}

function f2() {
    if (true) {
         type s = string;
    }
    console.log("" as s);
}
```

### 🙁 Actual behavior

From type-system perspective in the first `if` it appear that the `console.log` is part of the body of the `if` because the type is in scope. However the JS emit is:

```js
function f1() {
    if (true)
        ;
    console.log("");
}
```

So the `console.log` is not part of the if body.

### 🙂 Expected behavior

```ts
function f1() {
    if (true)
       type s = string;
       // @ts-expect-error : "cannot find name 's'"
       console.log("" as s);
}
```

Also happy for this to be a parse error. An if statement with only a type declaration as a body hopefully has no use cases.

**Comment by RyanCavanaugh** [comment]
Parse error seems like the best option; we can use the same logic that disallows
```ts
if (true) let n = 3;
```

**Comment by milkcask** [comment]
Currently, the logic in `checkGrammarForDisallowedBlockScopedVariableStatement` only checks against `VariableStatement`. To address this new issue, we could add a similar check.

From another perspective, 
```ts
type s = string;
``` 
isn't actually a JavaScript statement but the parser doesn't recognize it as an EmptyStatement.

We might be able to add a check against `TypeAliasDeclaration` (and `InterfaceDeclaration`). Or make some changes to both the parser and the checker, introducing a new `SyntaxKind` to handle this scenario.

The two related error messages:
- `The body of an 'if' statement cannot be the empty statement. ts(1313)`
- `'let' declarations can only be declared inside a block. ts(1156)`
