### ISSUE TITLE
Make ScriptVersion.Latest default for JS files

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#6017]
As just discussed we should make sure that Latest becomes the default for JS files when fed into the TypeScript compiler/language service.

**Comment by mhegazy** [comment]
we talked about a new option "JSLanguageVersion" (or some better name), that if present will enforce some "restrictions" on the syntax allowed in JS files. If you agree, i think this is already tracked by #4556.

**Comment by jrieken** [comment]
Makes sense to me.
