### ISSUE TITLE
Inferred `never` values don't properly type guard

### ISSUE THREAD

**Issue by VoiceNPO** [microsoft/TypeScript#60185]
### 🔎 Search Terms

never type guard

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about type guarding

### ⏯ Playground Link

https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&moduleResolution=99&target=99&module=199&exactOptionalPropertyTypes=true&ts=5.6.3#code/GYVwdgxgLglg9mABAExgUwBQEoBcixoBuaATogN4BQiNiJaUIJSYIANm4gIYDO+RpANyUAvpUqhIsBIhhhgpACLpsFarXqNmKFVmFjKyNBDZd6iCAh5READzzWScgOaIAPvnZthlGMEQYAIS2WGq0svJKuvritoKIAPQJdrJ81jAciAAOcDw8MABGbACenhzifgHBoVThqJh6orHxSSlgcADuFlxgAOQ2BWhlbEA

### 💻 Code

```ts
function die(): never {
    return null as never;
}

function inferDie() {
    return die();
}

declare const x: string | null;

if (!x) {
    inferDie();
}

x; // x is still possibly null

if (!x) {
    die();
}

x; // x now can't be null
```

### 🙁 Actual behavior

Two functions that have "identical" signatures, `() => never`, are not acting the same

### 🙂 Expected behavior

I'd expect both of these to act the same way since, for everything I can see, TS sees their signatures as being identical.

**Comment by Andarist** [comment]
as per https://github.com/microsoft/TypeScript/pull/32695 :

> - the call occurs as a top-level expression statement, and
> - the call specifies a single identifier or a dotted sequence of identifiers for the function name, and
> - each identifier in the function name references an entity with an explicit type, and
> - the function name resolves to a function type with an asserts return type or an explicit never return type annotation.

Your `inferDie` has no explicit never return type so it's not treated as an assertion

**Comment by VoiceNPO** [comment]
I'd argue that this behavior is wrong, but alternatively tooling should be able to tell the difference.  As far as I can tell, TS doesn't actually expose the difference.

**Comment by MartinJohns** [comment]
The behavior is intentional, not wrong, and was done for performance reasons.

**Comment by VoiceNPO** [comment]
Oh ffs, I'm done reporting issues to you guys.  You make stupid ass decisions and then try to justify them.  It's utterly pathetic.

**Comment by MartinJohns** [comment]
Neither me nor Andarist are part of the TypeScript team. But you can be assured that the team does not make these decisions willy-nilly or out of spite, there's reasons behind them. They're not "stupid ass decisions", they're technical decisions with benefits and drawbacks.

And you're advised to check out the [Code of Conduct](https://opensource.microsoft.com/codeofconduct/). :-)

**Comment by VoiceNPO** [comment]
Oh nooo, you're offended.

Like I give a single fuck
