### ISSUE TITLE
types typescript does not work when using the spread operator

### ISSUE THREAD

**Issue by anzor1qqqqq** [microsoft/TypeScript#60182]
### 🔎 Search Terms

types typescript, spread operator

### 🕗 Version & Regression Information

in all version typscript

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAZgSwE7RgXhgbwLACgYEwCGA5gKYBcMATNXgL556iSxFU76FhEC2lMaEgRgSDdFjyEYAOjmIUUADRTufAQHIiYAF4gkGhkA

### 💻 Code

const first = {
    age: 22
}

const a: {
    name: string
} = {
    ...first,
    name: 'anzor'
}

### 🙁 Actual behavior

the compiler does not cause an error in the second object type

### 🙂 Expected behavior

the ts compiler should warn about the type mismatch

**Comment by MartinJohns** [comment]
Duplicate of #39998. Excess property checks are not performed when spreading.

There is no type mismatch. Additional properties are allowed to exist on objects.

**Comment by anzor1qqqqq** [comment]
> Duplicate of [#39998](https://github.com/microsoft/TypeScript/issues/39998). Excess property checks are not performed when spreading.
> 
> There is no type mismatch. Additional properties are allowed to exist on objects.

How can this be defeated??????????

**Comment by MartinJohns** [comment]
It's a fundamental part of TypeScripts type system, it's intentional.
