### ISSUE TITLE
Incorrect generic type inference in class context

### ISSUE THREAD

**Issue by chapterjason** [microsoft/TypeScript#60193]
### 🔎 Search Terms

TS2345
Parameters<T[K]>
Generic Type Inference
class context
inheritance

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.3#code/C4TwDgpgBAKgsgQzGAlgOwOZQLxQEoQDGA9gE4AmAPAM7CnoYA0UAFAHQcKkbUBcUCNCADaAXQCUOAHwChUgNwAoRYQA2CatSgAhDREowoEAB7AIaclvhJUmGQG9FUZ1DABXAEaqUhKIQSqqpQA0kam5pZQANYQIMQAZrBSLGgIALYQ-MHMHGxcPPwAClzpEGak1AbCwaJSko4ujVAA9M1QaMTEYE4uAL6K-YqgkFCIyAwAjDhQDS4AROQIwAhz-Cz5E-y09JiS2DIAbsQo5Eq9SkPg0GO2GABM07POc25gi2arrBv8aG5pHhBSHtDsdTgMLmoNFoAMLENCEUhlfSGExmCxaG6TGSoiJaXTUZEOHrOEhobZuQjAMgserEprUV6AmkXJouYAACxQ1DY-kCLAWSxWzDmEzuAGY5uJ5C02gBRUikMj8GAAZXFABYAKz8ACC3D+5mAUASUGG0AA5MIReK5qJzVAue1iEaoSgMKkvNAqa4ShlysbEmaoObiqRSuVKjAre8VrVzWw6f1BpDNFBYfDEWYpjj0Wm4QikZRMZgJgAyYv3ImNUnkynU2ms5wMyCkZnKRumznc3mqfkxubC0USqUyqAAOWIUHlitIdMaHK5PICvZebyWEAHUCHI9a48n07IiYGyjQEAA7nmM0iaUu+QLlpu5lqAGyS6W7idThWH08X9MFrMbx7PtBUfF831HT8D1nX9LwAiAJiA5d+Ved4N2YF8dzaKDv1nFQ4VoH0wzSPgoFDcNAUqCsJmjUDammK0h1td9sP3XCgA

### 💻 Code

```ts
type TMapping = Record<string, (...args: any[]) => any>;

class Base<T extends TMapping> {
    public call<K extends keyof T>(name: K, ...args: Parameters<T[K]>) {
        // noop
    }
}

type Mapping1 = {
    "data": (arg1: string) => void;
};

type Mapping2 = {
    "update": (arg1: number) => void;
};

class Concrete<T extends Mapping1> extends Base<T> { // Type is generic
    constructor() {
        super();

        this.call("data", "123"); // Error: TS2345: Argument of type '["123"]' is not assignable to parameter of type 'Parameters<T["data"]>'.
    }
}

class Concrete1 extends Concrete<Mapping1&Mapping2> { // Type is "global" available
    constructor() {
        super();

        this.call("data", "123"); // No Error
        this.call("update", 123); // No Error
    }
}

new Concrete().call("data", "456"); // No Error
new Concrete1().call("data", "456"); // No Error
new Concrete1().call("update", 456); // No Error

const params: Parameters<Mapping1["data"]> = ["123"]; // No Error
```

### 🙁 Actual behavior

In the Concrete class, when I try to call the `call` method with a valid argument, it throws the error:

```
TS2345: Argument of type ["123"] is not assignable to parameter of type Parameters<T["data"]>.
```

However, calling the same method outside of the constructor does not produce this error, even though the argument types are identical.
This suggests that there's an issue with type inference of the type in the class context, but the expected behavior works correctly elsewhere.

### 🙂 Expected behavior

I expect it to infer the types correctly in both contexts — in the class and outside of it — without throwing an type error, as the argument passed matches the expected type Parameters<T["data"]>.

### Additional information about the issue

My goal is to create a strong type `EventEmitter` with the support of derived classes which can also supply its `EventMapping`.
But in the actual usage of those TypeEventEmitter I always face this issue.

**Comment by jcalz** [comment]
Duplicate #39222

**Comment by chapterjason** [comment]
Haven't seen that one, thanks. As it is a bit old, has anything changed in the type system to make it possible?

Found a workaround for me, polutes the runtime, but works:

https://www.typescriptlang.org/play/?target=99&module=1&ts=5.6.3#code/C4TwDgpgBAKgsgQzGAlgOwOZQLxQEoQDGA9gE4AmAPAM7CnoYA0UAFAHQcKkbUBcUCNCADaAXQCUOAHwChUgNwAoRYQA2CatSgAhDREowoEAB7AIaclvhJUmHLETIGMgN6KoHqGACuAI1UohFCECKqqlADSRqbmllAA1hAgxABmsFIsaAgAthD8EcwcbFw8-AAKXDkQZqTUBsIRolLi-ABuxCjkUG6evVAA9P1QaMTEYO6eAL6K04qgkFCOthgAjPY9ngBE5AjACJv8LCUr-LT0mJLYMu2dSpNKKuqaUADCxGiEpNX6Ex6GJmYLFolgw1rgQZgVoxFDIAbEtLpqPoYK5flAvghyO9VCAoABiCDZFDAGr8RH6CGrBTKXokNBnbyEYBkFiSDZ9KDUbyQUish4cjzAAAWKGobAJRJJEFI9mFoqUAqgcrFEuJNTYITCLG2u32zE2KwATABmTbieQDIYAOWIUAAoqRSGQ0dNZvNoJTDfZKWsAGTdNGbbk7MwHVjHfhobzZXzSy7XDrkO4PNQaLRvD5fMxrOFA17vT7fSie1G9DFYtA4-GEtXSsl6Ys2BiG6loukMpkstlo3pcnl8mkC5XimtSmW4ZX8ocilWj9Wa1TakN6qAGk1mi2DKA2+2O52K4eqsca0KLoNgEMQTbMI3G82W7e2h1O0gumbKNAQADu+cz31ZJ5ajqezXquAAsACsABsG4Pjuz7Op+P4ZoW2YAQuS66qBmyQTB95bvBe6vkhv6oRAKzoae2rBrsV7MLh+HWk+RHKO2wBeJU2R8FAFSkFUNR1D6wjAfsTT2MJt6bKIm5MbuL5AA

```ts
type TMapping = Record<string, (...args: any[]) => any>;

class Base<T extends TMapping = TMapping> {
    public call<K extends keyof T>(name: K, ...args: Parameters<T[K]>): void {
        // noop
    }
}

type Mapping1 = {
    "data": (arg1: string) => void;
};

class Concrete<
    T extends Mapping1 = Mapping1,
> extends Base<T> {
    readonly #emitter: Base<Mapping1>;

    constructor() {
        super();

        this.#emitter = this;
        this.#emitter.call("data", "123"); // No Error
    }
}

type Mapping2 = Mapping1 & {
    "update": (arg1: number) => void;
};

class Concrete1 extends Concrete<Mapping2> {
    readonly #emitter: Base<Mapping2>;

    constructor() {
        super();

        this.#emitter = this;

        this.#emitter.call("data", "123"); // No Error
        this.#emitter.call("update", 123); // No Error
    }
}

new Concrete().call("data", "456"); // No Error
new Concrete1().call("data", "456"); // No Error
new Concrete1().call("update", 456); // No Error

const params: Parameters<Mapping1["data"]> = ["123"]; // No Error
```
