### ISSUE TITLE
Adding boolean type assertion changes type narrowing 

### ISSUE THREAD

**Issue by jauwesome** [microsoft/TypeScript#60190]
### 🔎 Search Terms

Type Narrowing
Boolean
Undefined

### 🕗 Version & Regression Information

Version: 5.6.3
Regression: Unknown

### ⏯ Playground Link

https://www.typescriptlang.org/play/?noUnusedLocals=true&noUnusedParameters=true#code/GYVwdgxgLglg9mABFApgZygeTCgFMOOALkQwCcYwBzRAH0XABMVhKVGBKRAbwChEBiCAgzIAFpRoBeRAEJZBOAG5+gmMFxQJ1Ln0H7EZFFBBkkigHQQxAQzIBBKLgAMHFfoC+qgUZNnEAORMLGyMAbxevKCQsAjI6FAAKgDucPiEJOSSdAxgzKw4nDzeQiJQ4pIkAEaEADYoNkgy8oruahpakrol+r6m5oRWtg5Orm0CXr3G-YHBBezhHkA

### 💻 Code

```
function testOne(foo: string | undefined) {
    const thing = !!foo;
    if(thing) {
        // Foo type is String
        return foo.charAt(0);
    }
    return 'undefined'
}

function testTwo(foo: string | undefined) {
    const thing: boolean = !!foo;
    if(thing) {
         // Foo type is string | undefined
        return foo.charAt(0);
    }
    return 'undefined'
}
```

### 🙁 Actual behavior

`foo` is typed as `string | undefined` if `thing` has explicit type of `boolean`

### 🙂 Expected behavior

`foo` should be typed as `string` if `thing` has type of `boolean` just like if `thing`'s type is inferred

**Comment by RyanCavanaugh** [comment]
This was an intentional boundary in #44730

**Comment by jauwesome** [comment]
@RyanCavanaugh Thanks for the quick response! Is there a specific reason why this choice was made? I don't see that listed. Regardless we can close the ticket.

**Comment by RyanCavanaugh** [comment]
IIRC it's possible to get into a type resolution circularity with this inference in a way that wouldn't really be solvable, so you need some "out" in cases where you're not using it for narrowing purposes

**Comment by jauwesome** [comment]
Good to know! That makes sense. Thanks again for your help!
