### ISSUE TITLE
Differently named type parameters are not considered "identical" for interfaces

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6020]
```ts
interface Foo<T> {
    x: T;
}

interface Foo<U> {
    x: U;
}
```

We give the error "All declarations of an interface must have identical type parameters."

**Comment by RyanCavanaugh** [comment]
Why `bug`? This is the intended behavior.

**Comment by ahejlsberg** [comment]
This is by design. We require the names to be identical in each declaration.
