### ISSUE TITLE
Presence of function changes 'this' value, even if the function is not executed

### ISSUE THREAD

**Issue by ridiculousfish** [Microsoft/TypeScript#6021]
I have some code in which 'this' seems to change unexpectedly. Here is a reduced test case:
```
class Foo {
    stuff() {
      const savedThis = this
      for (let i=0; i < 4; i++) {
        console.log("I know me outer: " + (savedThis == this))
        for (let j=0; j < 4; j++) {
          console.log("I know me inner: " + (savedThis == this))
          continue
          function yikes() { j }
        }
    }
  }
}
(new Foo()).stuff()
```

In this code the value of `this` changes unexpectedly. `this` matches `savedThis` within the outer loop, but not within the inner loop.

However remove the `function yikes`, and `this` returns to its expected value. This is very surprising to me since the function `yikes` is never actually encountered.

`tsc --version` shows "message TS6029: Version 1.6.2"

**Comment by RyanCavanaugh** [comment]
Looks like this has been fixed in `master` at some point -- this outputs `true` in either case in all lines for me.

Can you verify using the nightly build (`npm install typescript@next`) ?

**Comment by ridiculousfish** [comment]
Yes, it no longer repros in master. Closing. Thanks for your quick response.
