### ISSUE TITLE
Typescript incorrectly inferring type without conditional expression when using `Record` with undefined values

### ISSUE THREAD

**Issue by kishore03109** [microsoft/TypeScript#60239]
### 🔎 Search Terms

Typescript is unable to assign the values properly help of explicit conditionals to help narrow the type. 

### 🕗 Version & Regression Information

This is the behavior in every version I tried.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20241015#code/C4TwDgpgBAogHgQwLZgDYQCrmgXigJQgGMB7AJwBMAeAOwFckAjCMgGigGdgyBLGgcwB8UAD4Fi5avSYt2dGhQgAzPhAqCAUBtI0uUAG4JUdXFADkZqAg5R5AaxokA7jSs2uvAaNsLlqilo6enYQIABcUNLMZFB4AIxaAPQAVMkaUMlQWJDmAN5QANpwEVEsALoRHnz83vKKKjRqANxQAL6WPDaOwG4cPPw0CIzoUMAko9jm8MhomNhmAHTAHAAUAEwAzGtrAJTpyYnaJLo9xbCIKOjZprnphSEgFQZGJqwarYHHeuHnM1eTODuhmM0AAhDg8HU-I0AlA4VAAPxQW7w1H3UJPYGvO6oj6oiIotFwgoPTEvCBvIkfIA

### 💻 Code

```ts
type ExampleType = Record<number, string> | Record<number, undefined>

const value = '' as unknown as string | undefined

const key: number = 1

/**
 * Type '{ [x: number]: string | undefined; }' is not assignable to type 'ExampleType'.ts(2322)
 */
const x: ExampleType = {
  [key]: value,
}

const y: ExampleType =
  value !== undefined
    ? {
        [key]: value,
      }
    : {
        [key]: value,
      }

```

### 🙁 Actual behavior

Type error observed for x : `Type '{ [x: number]: string | undefined; }' is not assignable to type 'ExampleType'.(2322)`

### 🙂 Expected behavior
No type error should be observed for x

**Comment by jcalz** [comment]
duplicate of #8289, #39169

**Comment by kishore03109** [comment]
@jcalz Thank you, while unfortunate, makes sense why this would be an exceptionally difficult problem to fix
