### ISSUE TITLE
TS fails to detect lost `this` binding

### ISSUE THREAD

**Issue by Rudxain** [microsoft/TypeScript#60235]
### 🔎 Search Terms

context TypeError Cannot convert `undefined` or `null` to object `noImplicitThis` disambiguator

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `this`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&jsx=0&ts=5.7.0-dev.20241015#code/PTAEDMEsDsFMCgAUBtAugOgM4HsBOAXASkUIG54kBGUAMhtDSzyJPJFAFVoBjAQwFcA5gAt8oACoBPAA6wAorlx4AXKADCvaNGxju2aADdYBUP2gATWFDjnQeUNH4AbJ6HzY7AIwBWsbvnh2UGDeMRwTRAAeTX1JAFtsfkwAPkIKJ1gw0ABeBgxw-HJMVkCwLj4hUQkZeUUVdU1tXX0jEzNLa1hbe0cXNw9sHz8AoJCw5lAomOh4xJTCIA

### 💻 Code

```ts
// fine
([].sort)();

(1 && [].sort)();
// Uncaught TypeError: Cannot convert undefined or null to object
//    at sort (<anonymous>)

let s = [].sort;
s();
// Uncaught TypeError: Cannot convert undefined or null to object
//    at sort (<anonymous>)
```

### 🙁 Actual behavior

Run-time error

### 🙂 Expected behavior

Compile-time error

### Additional information about the issue

mdn/content#36355

**Comment by jcalz** [comment]
duplicate #7968
