### ISSUE TITLE
Nullable nested properties breaks inference for type guards

### ISSUE THREAD

**Issue by leonaves** [microsoft/TypeScript#60244]
### 🔎 Search Terms

nullable items nested typeguard type guards

### 🕗 Version & Regression Information

- This changed between versions 0 and 5.6.3

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20241016#code/ATAuE8AcFNgMQPYIEIEMBOwC8wDeAoEEAIwwC5gBnUdASwDsBzYAH2HoFcAbLgbkOABffgIgxgAOW5dUxLtACSoaAFtseASABmSCohQZW7afxDD8oqLAkJQUnrPlLV6gkWA6EepGnSmhIiAAxgj01MC0yioAEqiU+uoAFJGqFPYycopRAJQUKWq0lJK26Y5ZLlgAfBru6NCgHOj0EVEAdJ7AAIRYOJw8-uYCIWGgLapFOADamjXuHrqzc8Ck6BQA5AAW0DwIawA0M2YH7oLHRLjzXsY8QmcAuoHAw+FcCIwAgujoqOAA8lrOFQTYCJLQcehBQGUNIlaRlQGTO7ZbDVNxEZ4IeStV6MUHgyFRSjZAaPZ6jLS0LjKOoAEyh6nylHalOpySisXiSGJAhxn2+fwBhNBLOgtKhxKAA

### 💻 Code

```ts
  type FooBar = {
    bar: string | null;
  };

  type NullableItem = {
    foo: FooBar | null;
  };

  type NotNullableItem = {
    foo: FooBar;
  };

  const itemHasFoo = (item: NullableItem): item is NotNullableItem => {
    return item.foo !== null;
  };

  const items = [
    {
      foo: {
        bar: 'hello',
      },
    },
    { foo: null },
  ];

  const logArrayOfItems = (funcItems: NotNullableItem[]) => {
    console.log(funcItems);
  };

  const filteredItems = items.filter(itemHasFoo);
  logArrayOfItems(filteredItems);
```

### 🙁 Actual behavior

Type guard itemHasFoo does not narrow type to NotNullableItem, but when `FooBar` is changed to:

```
  type FooBar = {
    bar: string;
  };
```

It works fine, something about the nullable property of FooBar seems to stop the inference of that type correctly.

### 🙂 Expected behavior

I expect the typeguard to correctly narrow the type to `NotNullableItem` and therefore not error.

**Comment by jcalz** [comment]
This has little to do with type guards, or even nullability. It's just assignability.  The following is an error, for good reason:

```ts
declare const i: { foo: { bar: string | null } };
const j: ({ foo: { bar: string } } | { foo: null }) = i; // error!
```

but removing `| null` from `i`'s type fixes it, also for good reason:
```ts
declare const i: { foo: { bar: string } };
const j: ({ foo: { bar: string } } | { foo: null }) = i; // okay
```

Those are the same types from your example, and the error in the top one is the thing that prevents TS from selecting the type guard overload for `filter()`.

TypeScript can't know that you intend `items` to be of type `NullableItem[]` so it doesn't recognize `itemHasFoo` as a valid narrowing of its elements. If you want that type, you can annotate it like `const items: NullableItem[] = ⋯`.  I'm not seeing a TS bug anywhere here.

**Comment by leonaves** [comment]
Hmm okay I get the question of assignability in this case, but why doesn’t the type guard error that I’m passing an argument of the wrong type to it if items can’t be coerced to NullableItem[]?

**Comment by jcalz** [comment]
`{ foo: { bar: string } } | { foo: null }` is assignable to `NullableItem`, not vice versa. So `filter()` is happy to accept a callback of type `(x: NullableItem) => void`, since `NullableItem` is wider, and functions are contravariant in their parameters.  But since `NotNullableItem` isn't seen as narrower than `{ foo: { bar: string } } | { foo: null }`, then TS can't select the overload that deals with type predicates.  In `arr.filter(pred)` where `arr` is of type `T[]` and `pred` is of type `(x: U) => x is V`, the call will *succeed* as long as `T extends U`, but it will only narrow `arr` if `V extends T`.

**Comment by RyanCavanaugh** [comment]
> Leads to myThing being reduced never, and erroring on the console.log. I don't think that makes sense to me. I think never as a type shouldn't come out of a type guard call

This would just make it inconsistent with narrowing semantics. It's idiomatic and common for something to be reduced to `never` for one reason or another, e.g. exhaustive `switch` statements.
