### ISSUE TITLE
Emit for default exports doesn't actually export original name

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6025]
Potentially related to #6023.

Input:
```ts
export default class C {
}
```

Output:
```js
var C = (function () {
	function C() {
	}
	return C;
})();
exports.default = C;
```

Notice we don't add a binding like `exports.C = C;`

**Comment by vladima** [comment]
this behavior is by design: [exported names](https://tc39.github.io/ecma262/#sec-exports-static-semantics-exportednames) for `export default ClassDeclaration` include only `default`.

**Comment by DanielRosenwasser** [comment]
To clarify, this was confusing because *ExportedBindings* is distinct from *ExportedNames*.
