### ISSUE TITLE
when importing .js is imported .d.ts

### ISSUE THREAD

**Issue by vadimmos** [microsoft/TypeScript#60259]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: System:
  Linux Mint 21.3
  Kernel: 5.15.0-122-generic x86_64

![Image](https://github.com/user-attachments/assets/4db08d52-8467-41f3-91b0-19b3007eb188)

there are 3 files:

"module1_.d.ts":
```d.ts
interface Foo {
    bar: boolean
}
```

"module_1.js":
```javascript
/**@param {Foo} foo */
export default function fn(foo) { return foo.bar };
```

"module_2.js":
```javascript
import fn from './module_1.js';
console.log(fn({ bar: true }));
```

Despite the fact that it is explicitly specified which file should be imported, the editor tries to import exactly the d.ts file and swears that it is not a module.
![Image](https://github.com/user-attachments/assets/5d2900cc-fa96-49bf-a562-3d3e495ea765)

**Comment by MartinJohns** [comment]
I believe this is intentional. When a .d.ts file exists it's used for type information for the ja file. You're importing a module, so TypeScript looks for the accompanying declaration file. It should either match your code, or be renamed (so it's not the declaration file for that specific module).

**Comment by vadimmos** [comment]
the import clearly says which file needs to be imported. Why is the editor trying to import something else?

**Comment by MartinJohns** [comment]
It's not importing something else. It's importing that module, and that module ships with an accompanying declaration file that describes the types of the module.

**Comment by vadimmos** [comment]
if export is described in the file "module_1.d.ts", then typing stops working in the file "module_1.js", in order for it to work again, I have to import "module_1.d.ts" into the file "module_1.js" as a module. As I understand it, in this case, "module_1.d.ts" starts working as an independent typing module, and not as a co-summary file to a file "module_1.js ".

**Comment by vadimmos** [comment]
![Image](https://github.com/user-attachments/assets/b27b5026-f38a-40ed-8bcf-bc32a02aac59)

**Comment by vadimmos** [comment]
In one case, import does not work correctly, in the other - typing.
