### ISSUE TITLE
Cannot get `["name"]` of type constrained to a constructor

### ISSUE THREAD

**Issue by jeengbe** [microsoft/TypeScript#60258]
### 🔎 Search Terms

constructor type narrowing constrained name extends cannot be used to index type

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _N/A_

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20241017#code/C4TwDgpgBAwlC8UB2EDuUAUBKBA+KAhkiANwBQZokUAGgrANoBESBAthEwLrlXQCaAHgAqUCAA9gEJABMAzrHyJhzVh27kgA

### 💻 Code

```ts
type C = new () => any;

type X = C["name"];
type Y<T extends C> = T["name"];
                      ~~~~~~~~~ Type '"name"' cannot be used to index type 'T'.
```

### 🙁 Actual behavior

.

### 🙂 Expected behavior

As the first type `X` shows, `T["name"]` is a valid index on a type that is equally constrained to the same `C`. The auto-completion understands this.

![Image](https://github.com/user-attachments/assets/c824c3d3-8e4b-4f9c-993e-6cd43d851b2b)

**Comment by jeengbe** [comment]
This appears to be specific to `new () => any`. If you set `type X = string;` and replace `"name"` with `"charAt"`, it works as intended.

**Comment by MartinJohns** [comment]
What would this be useful for? It's always going to be `string`.

**Comment by RyanCavanaugh** [comment]
`name` isn't in the `keyof` set of a function/constructor; it exists because it's an apparent property via `Function`. You can access apparent properties on concrete types, but not through constrained parameters, because apparent properties can be overridden by *incompatible* manifest properties in specific instantiations, which would end up violating invariants elsewhere.

**Comment by jeengbe** [comment]
> What would this be useful for? It's always going to be `string`.

Nothing at all. I stumbled across this while experimenting with something similar and found it a strange inconsistency.

**Comment by jeengbe** [comment]
The only bug then would be that the language server still provides autocompletion for the correctly invalid property.
