### ISSUE TITLE
checker.typeToString() omits null from unions

### ISSUE THREAD

**Issue by everdimension** [microsoft/TypeScript#60256]
### 🔎 Search Terms

When I use `checker.typeToString()` to print out the type, it omits `null` if some values are defined in a manner of `value: string | null`.

### 🕗 Version & Regression Information

I see this in Version 5.6.3
I haven't tried other versions

### 💻 Code

I have interface like this:

```ts
interface A {
  prop: {
    prop1: string | null;
    prop2: {};
    prop3?: number | string;
    prop4: number | null | string;
    prop5: null;
    prop6: undefined;
    prop7: null | undefined;
    prop8: number | null | undefined;
  };
}
```

I'm printing out the type of `A['prop']` using `checker.typeToString(typeOfPropSymbol, undefined, ts.TypeFormatFlags.NoTruncation)`

### 🙁 Actual behavior

Here's what I'm getting:

```
{
  prop1: string; // <-- missing | null
  prop2: {};
  prop3?: string | number;
  prop4: string | number;  // <-- missing | null
  prop5: null;
  prop6?: undefined;
  prop7: null; // <-- missing | undefined
  prop8: number; // <-- missing | null | undefined
}
```

### 🙂 Expected behavior

This is what I expect:

```
{
   prop1: string | null;
   prop2: {};
   prop3?: number | string;
   prop4: number | null | string;
   prop5: null;
   prop6: undefined;
   prop7: null | undefined;
   prop8: number | null | undefined;
 }
```

### Additional information about the issue

Version 5.6.3

**Comment by MartinJohns** [comment]
Have you enabled `strictNullChecks` in your config?

**Comment by RyanCavanaugh** [comment]
For API bugs, we need a fully complete code sample

**Comment by everdimension** [comment]
@MartinJohns Thank you, adding `strictNullChecks: true` to `createProgram` options improved the output

Although now optional value of `{ prop?: number }` renders as `{ prop?: number | undefined }`

I understand that it has different meaning, but is it configurable to preserve nulls, but keep optionals rendered as `{ prop?: number }`?

**Comment by MartinJohns** [comment]
Likely `exactOptionalPropertyTypes`.

**Comment by everdimension** [comment]
@MartinJohns Thanks! 

I guess I didn't expect these options to be in `createProgram` and instead expected them to be options of the `checker` or of the `typeToString` method
