### ISSUE TITLE
About # and 'private'. Why not '#private' ?

### ISSUE THREAD

**Issue by mberdev** [microsoft/TypeScript#60275]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I was thinking about this topic : https://github.com/microsoft/TypeScript/issues/31670

The conversation can go on.

The facts : 
- `private` is a Typescript keyword
- `private field` does not get transpiled into `#field` or any constraining code, as per Typescript philosophy.
- `#` is Javascript syntax.
- `#` is considered awkward by many Typescript devs, because:
  - it's carried around alongside the variable name. 
  - it's stealing the spot of what `private` would be used for in the vast majority of OOP languages.
  
There's got to be a way of getting the best of both.

**What do you think of this ?**
- **A new typescript keyword,** '#private'
- It gets transpiled into a #field
- Example : `#private field: number`. Then in Typescript it's used normally: `this.field = 12;`. In Javascript it's compiled as `this.#field = 12;`

**Comment by jcalz** [comment]
This proposal would require type-directed emit as described in the issue you linked and will therefore not happen. TS cannot *sometomes* emit `x.y = 0` as `x.#y = 0` depending on what `x` is.
