### ISSUE TITLE
feat: type-safe `Map` type

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript#60280]
### 🔍 Search Terms

typescript type-safe map type

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [ ] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

See closed issue:

- https://github.com/microsoft/TypeScript/issues/43101

### 📃 Motivating Example

In --- @RyanCavanaugh asked

> "Why aren't you using an object"

Because objects can only have string and symbol keys. Maps can have anything as a key.

Here's a usage example that shows the desired result:

```ts
const keyA: Function = () => {}
const keyB: {a: number} = {a: 123}

// ...create type-safe Map somehow...

// set type-safe values in the map:
map.set(keyA, 123) // ok
map.set(keyB, true) // ok

// These would be type errors:
// map.set(keyA, true)
// map.set(keyB, 123)

// type-safe usage:
const a: number = map.get(keyA)
const b: boolean = map.get(keyB)
```

No non-type-safe casting of the `get` method's return values would be needed.

### 💻 Use Cases

1. What do you want to use this for? Type safe Maps with known value types for given key types (because it is impossible with regular objects)
2. What shortcomings exist with current approaches? It may be possible to do this with cumbersome overriding of method types. The feature would make it easy.
3. What workarounds are you using in the meantime? Making custom method types and using `extends` types could make it doable, but cumbersome.

**Comment by trusktr** [comment]
I'm not sure if

> This isn't a request to add a new utility type

so I unchecked that.

**Comment by jcalz** [comment]
How do you eliminate `undefined` from the types returned from `get()`? Do you expect TypeScript to keep track of the *identities* of the keys (in which case this is a very large feature request indeed) or just the *types* of the keys (in which case this can be done yourself, but I'd expect `undefined` in the domain of `get()`)

**Comment by jcalz** [comment]
I threw this together:

```ts
type Entries = [any, any]
interface DependentMap<E extends Entries> {
  forEach(callbackfn: <K extends E[0]>(
    value: Extract<E, [K, any]>[1], key: K, map: DependentMap<E>
  ) => void, thisArg?: any): void;
  get<K extends E[0]>(key: K): Extract<E, [K, any]>[1] | undefined;
  set<K extends E[0]>(key: K, value: Extract<E, [K, any]>[1]): this;
  readonly size: number;
  [Symbol.iterator](): IterableIterator<E>;
  entries(): IterableIterator<E>;
  keys(): IterableIterator<E[0]>;
  values(): IterableIterator<E[1]>;
  readonly [Symbol.toStringTag]: string;
}

interface DependentMapConstructor {
  new <E extends Entries>(
    entries: E[]
  ): DependentMap<E>;
  new <E extends Entries>(): DependentMap<E>;
  readonly prototype: DependentMap<any>;
}

const DependentMap = Map as DependentMapConstructor;

const keyA: Function = () => { }
const keyB: { a: number } = { a: 123 }

const map = new DependentMap<[Function, number] | [{ a: number }, boolean]>

map.set(keyA, 123) // ok
map.set(keyB, true) // ok

const a: number | undefined = map.get(keyA)
const b: boolean | undefined = map.get(keyB)

map.set(keyA, true)
map.set(keyB, 123)
```
[Playground link](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAogdsATgSwgZygXigbQIZwgA0UBIAugFDIISIBmeAxtACISRwAmECAsnjAAeGFAgAPYLy4Z4SVGgB8UAN6UoUegHtEMZgAsAFEzwAbUwCNmAa3pwAXFCEBpMZOmycABnKLD6jSgANzMAVwhHGElEZmAREhxnEjJfHABGchJrCBBHJKgAW0FHdk4efkERRQCASixlIK1kLhJgfWQ0AEFEAHMAfkcyGsdG5oBuAJ6IONcJKW5PHz9s3KhnYdho2PjcfJTFdPIoAB8oUO4IehoILgmNNGmXN3mZWG9fQxW8khDTcMitkw4jAEntCKkMhs2h07lBEBA8FwtHBTCAoGhkAAvCJQOChAoWOiwnAAZRABK0pgAdMgpDFgDpyIYNgBJOl4CymCBsuh4BmIKqw3jydDMxw8mKc7ns-mCgIrNBiqASjlclWymDvRSw37hRWs9lS9U6ESHbUBeGI5Go3BkinUhkk+RwHoAFTwPXIjjQzp6EwAvpRqLQGMw2BxpMKBGAAMLIn2IUJAnSqAJwCAAdycojmHlgCBQ6D8AQ0wsLaEiOCoGg2pUjFWEMHNGnTWZEzzzcnLflrEYuDblGktSJRaLAiC0DNAkBKffKwGjQjI5sDlCY8eAUDr-YXgiwUGjpAw2-n0bjcATSf5EzXG6gK06jgAYucgchkfvmfVVFBA+uL5uKwAEKOCopCOHiBJ0L++5gXgjhpAATAAzL+Qb-j6hR7tgrZbnOUaVDgL5wG+yIkJBhKIEcpw4HBEH4pRv4kBYWiUgicC+EGRRgFSDzAJ8OSdCQSHIXUAD0YlQFo1iUNxvHTAJIBAa0iYQOJknSehd7wbiDHQac5w8Fc6ZcPuclTPxD41LeAFQBYjgsWxBAnGcFzGTcZmCFSFmKUB1myV5fGKUJUBIOE1lyUFwHCSh1lAA)

What specific feature is this missing or doing incorrectly, which can't be done without a modification to TypeScript itself?

**Comment by trusktr** [comment]
> How do you eliminate `undefined` from the types returned from `get()`?

If the values are provided up front, it could be enforced. f.e. in plain JS it would be

```js
const keyA: Function = () => {}
const keyB: {a: number} = {a: 123}

new Map([
  [keyA, 123],
  [keyB, true],
])

// ... usage from above ...
```

> Do you expect TypeScript to keep track of the _identities_ of the keys

Just the type would be good enough for me (and most use cases I'm imagining). For any duplicate keys that are the same type as `keyA` above, they'd all accept `number`s only.



> I threw this together:

That's nifty, but also fairly complicated! I would not expect the average web dev to want to (or even be able to) write that. You yourself are a TypeScript expert, but a lot of people just want the type safety aspects, and learning how to write types like that is a whole new level.

In my view, because `Map` is already an intrinsic part of both JS and TS, it would be nice to have a type safe option out of the box. Someone has to ship (if not write) that type for for a built-in language feature. If it came out of the box, we'd all standardize on it in a nice way.

**Comment by trusktr** [comment]
This one doesn't work:

```ts
const m = new DependentMap<['a', number] | [boolean, string]>([['a', 1], [true, '123']])

m.set('a', 2)
m.set(false, 'blah') // error (unexpected)
```

[playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAogdsATgSwgZygXigbQIZwgA0UBIAugFDIISIBmeAxtACISRwAmECAsnjAAeGFAgAPYLy4Z4SVGgB8UAN6UoUegHtEMZgAsAFEzwAbUwCNmAa3pwAXFCEBpMZOmycABnKLD6jSgANzMAVwhHGElEZmAREhxnEjJfHABGchJrCBBHJKgAW0FHdk4efkERRQCASixlIK1kLhJgfWQ0AEFEAHMAfkcyGsdG5oBuAJ6IONcJKW5PHz9s3KhnYdho2PjcfJTFdPIoAB8oUO4IehoILgmNNGmXN3mZWG9fQxW8khDTcMitkw4jAEntCKkMhs2h07lBEBA8FwtHBTCAoGhkAAvCJQOChAoWOiwnAAZRABK0pgAdMgpDFgDpyIYNgBJOl4CymCBsuh4BmIKqw3jydDMxw8mKc7ns-mCgIrNBiqASjlclWymDvRSw37hRWs9lS9U6ESHbUBeGI5Go3BkinUhkk+RwHoAFTwPXIjjQzp6EwAvpRqLQGMw2BxpMKBGAAMLIn2IUJAnSqAJwCAAdycojmHlgCBQ6D8AQ0wsLaEiOCoGg2pUjFWEMHNGnTWZEzzzcnLflrEYuDblGktSJRaLAiC0DNAkBKffKwGjQjI5sDlCY8eAUDr-YXgiwUGjpAw2-n0bjcATSf5EzXG6gK06jgAYucgchkfvmfVVFBA+uL5uKwAEKOCopCOHiBJ0L++5gXgjhpAATAAzL+Qb-j6hR7tgrZbnOUaVDgL5wG+yIkJBhKIEcpw4HBEH4pRv4kBYWiUgicC+EGRRgFSDzAJ8OSdCQSHIXUAD0YlQFo1iUNxvHTAJIBAa0iYQOJknSehd7wbiDHQac5w8Fc6ZcPuclTPxD41LeAFQBYjgsWxBAnGcFzGTcZmCFSFmKUB1mUBJUAAALAGgAC0EiQECEWIBOiCyV5fGKUJUBIOE1mBSF4WRRA0V0HFCU8UlwHCSh-kYZuBT7rhJ4EcIOAAOR4A15F6VRLk4I5XIECQCY0J6fg4I1zXCZkuBpRAJANSJDXkOQ-kFPJ-FNS1UCIdZi1JYwpgPFNnJ4PoDXqa5OVAh507QPlOiUEAA)

But more importantly, see how web devs (not just TS devs) would want simple type safety, but they wouldn't want to deal with the complexity of implementing the above beast and having to work out such issues?

**Comment by jcalz** [comment]
> If the values are provided up front, it could be enforced. 
Explain how? TS doesn't track *identities* of values so there's no way to know that the thing you're passing to `get()` is the same thing you passed in either via `set()` or the constructor. With `const map = new Map([[keyA, 123],[keyB, true],])` how woud TypeScript tell the difference between `map.get(keyA)` and `map.get(()=>{})`, the second of which is certainly going to return `undefined`?  

> This one doesn't work:
Okay, for `boolean` or other subtypes of the key you could write it like

```ts
type KeyToValue<K, E extends Entries> =
  E extends [infer EK, infer EV] ? K extends EK ? EV : never : never;

interface DependentMap<E extends Entries> {
  forEach(callbackfn: <K extends E[0]>(
    value: KeyToValue<K, E>, key: K, map: DependentMap<E>
  ) => void, thisArg?: any): void;
  get<K extends E[0]>(key: K): KeyToValue<K, E> | undefined;
  set<K extends E[0]>(key: K, value: KeyToValue<K, E>): this;
  readonly size: number;
  [Symbol.iterator](): IterableIterator<E>;
  entries(): IterableIterator<E>;
  keys(): IterableIterator<E[0]>;
  values(): IterableIterator<E[1]>;
  readonly [Symbol.toStringTag]: string;
}
```
[Playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAogdsATgSwgZygXigbQIZwgA0UBIAugFCiRQDSEIAKgPYBqeANgK4QA8dEjCgQAHsAhwAJhnhJUaAHxZKUWCPGSZuZHABmERLEFRdBozDbkoAfnoaJ02XVuw2UAFxQ4EAG6HPbz9DAG5KSl0JRD08AGNoABEISGlJYABZPDA+YTFHbTkUdGUAb1UoPRZEGDiACwAKWK5OACM4gGs9OC8BBy1ZHAAGckV68rVfLl4vBmZ2Kf4TGEUSdsYZkgBbLK8klKk0zOzl8oBKLGVfFmQpEmBa5DQAQUQAcxsvMlOvK5uwtVeEGAvTy-VgQxG9TWIBm33ojFYHB4iyEygAPlBuKk9LoIFJ-lA0ECQZonODhqNoRsoJNkTMEfNkQJUXD7o8CYgIHgpCw4JwQITkAAvCBeODcTYtULlHAAZRAkpYnAAdMgonhgFVyPU4QBJdUtTgQfWGDVVHKKAlpIpoHVeE2IPCG43qzWIC0E6G2vUGo0Os3umAQy3lWm8b3230u01unI4ACMIw5XJ5fIFcoVLSVys1svkcFeTDwr3IXjQ+deYQAvuFIoYYvEoHstIcsgBhXnlxDcWJuqBlNQ+ADuUByfTJhQUo2tCi8QfIcObqQQRw95WHo9ypIKCBto0XyRbK6ya7UnO5vP5UDAiBYmpooqbh+XGRPZBDNcosU7wCf+1bYBYFARykBgS4HMeYAdnAXY9m6YRfj+UDQk8XgAGJYr2yC8kBOoXP2UA1t+MG-tCABCXglKQYoSlKRhVkBVF4F48YAEwAMyEeExHllA2yAdgG7gQBfA4BhcBYbyJDipKhjWBiOBMTRsn0SQWZKlycAjOE-HKkSwBQowTwkGx7HnAA9OZUAsO0lC6fphkgGRdzdhAFlWTZ3FIcx3i0QEGJYgcOI+FIQG6YCBkoaciEkVALReOpRoEFAAXYrioXYOFQKOWR0WUJZUAAALAGgAC0YiQL25WILeiB2VkenZShLm8NFBXFWVFUQFVhi1fVYCNZFjDOVApl5Txv6bEBQnPhBr7ZDgADkeCLdJfmIPJuCJZpJBdroJajDgS0rSZ5AkDgSC8CQi2mYt5ALjpg31Mtq1QKx0WbE9MScES12GngtSLeclBAA)

>  I would not expect the average web dev to want to (or even be able to) write that. 

I wasn't imagining that "the average web dev" would be writing this; it would more likely be some library maintained by interested/knowledgeable parties who would are willing to maintain `DependentMap` (no, don't look at me). 

> out of the box

But they have been pretty clear about declining requests to load stuff into the box unless it's needed for TypeScript the language itself. Are you asking for an exception to this rule? Or are you saying that the use case for a heterogeneous `Map` is so common and useful that it should be part of the built-in `Map` type definitions? (And how would that work, given that it would almost certainly destabilize existing uses?)

**Comment by trusktr** [comment]
Hmm, perhaps not worth it. The above can be copy/pasted for anyone that lands here.

> how would that work, given that it would almost certainly destabilize existing uses?

Maybe with an `extends tuple` check for `Map` generic args?

**Comment by Ashishsonavane** [comment]
I VERYIFY CODE SEND
