### ISSUE TITLE
Type parameter extraction via `infer` does not work with polymorphic `this`

### ISSUE THREAD

**Issue by jonathanhefner** [microsoft/TypeScript#60298]
### 🔎 Search Terms

"polymorphic this", "infer"

### 🕗 Version & Regression Information

The bug was present in all versions of TypeScript that I tried via the Playground:
- TypeScript 5.7.0-beta 
- TypeScript 5.6.3 
- TypeScript 5.0.4
- TypeScript 4.9.5
- TypeScript 4.0.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-beta#code/C4TwDgpgBA6glgEwOYWAFXBAPGqEAewEAdggM5QBCArklgIbEgB8zUAvAFBRS4FGkKNOnGIAzCACde8ZKjYB+GYhTAoALijEIANymdOAYwA29MkNo5ZqtgG9uUAO4rUARk3XUGSFmFWXwKwOznLAAEweAd7YwAAWcGTMBjyGAPbEZMCS1IbAqZIAFCGqmmiewACUUPY8PAD0dbD5ANZkAIQOPHEJAHTFbhxOAcm1DVAAopKS+aWYUADkZQHzUAlaqWpmZHBIxPQARsbQeVCgkAvl0VjdifOdp-FkfQFhg-3ADgC+nJ9AA

### 💻 Code

```ts
type WidgetType<T extends Bug<any>> =
  T extends Bug<infer TWidget> ? TWidget : never

class Bug<TWidget> {
  widget1: WidgetType<Bug<TWidget>>
  widget2: WidgetType<this>

  constructor(widget: TWidget) {
    // Works!
    this.widget1 = widget

    // Error: Type 'TWidget' is not assignable to type 'WidgetType<this>'
    this.widget2 = widget
  }
}
```

### 🙁 Actual behavior

The type checker correctly infers the type parameter from a generic type (`WidgetType<Bug<TWidget>>` == `TWidget`), but fails to do so when operating on polymorphic `this` (`WidgetType<this>` != `TWidget`).

### 🙂 Expected behavior

The type checker should recognize that `WidgetType<this>` == `TWidget`.

**Comment by jcalz** [comment]
`WidgetType<T>` is a [distributive conditional type](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) and [polymorphic `this`](https://www.typescriptlang.org/docs/handbook/2/classes.html#this-types) is implicitly generic inside the class, so evaluation of `WidgetType<this>` is deferred like any other generic distributive conditional type.  That is, I think TS is behaving as designed here and it's not a bug. I'm sure there are existing GitHub issues like this but I haven't found them yet.

**Comment by jonathanhefner** [comment]
@jcalz Thank you for your response!  I understood the two pages you linked, but I do not know enough about TypeScript's type checker to understand why the behavior is by design.  If there is a hard technical reason the behavior cannot be changed, that is unfortunate.  As a user, the behavior is surprising and _feels_ like a bug.  If it cannot be changed, a more explanatory error message might mitigate the surprise.

**Comment by RyanCavanaugh** [comment]
I don't know what you're trying to do with `WidgetType` here; it's recursive in a way that doesn't really work in structural positions.
```ts
class Subbug extends Bug<string | number> { }
const x = new Subbug(32);
const y = x.widget2; // type instantiation is excessively deep and possibly infinite
```

**Comment by jonathanhefner** [comment]
> I don't know what you're trying to do with `WidgetType` here

The intent of `WidgetType` is to extract the generic type parameter.  Perhaps a more clear example would be:

```typescript
type ItemType<T extends Collection<any>> =
  T extends Collection<infer TItem> ? TItem : never

class Collection<TItem> {
  first(): TItem { return }
  last(): ItemType<this> { return }
}

let list: Collection<number>
let item1: ItemType<typeof list> // typeof item1 is number
let item2 = list.last() // typeof item2 is number
```

In real-world code, though, the extraction might go deeper than one level.  For example, something like:

```typescript
interface Component { }

type ComponentType<T extends ComponentManager<any>> =
  T extends ComponentManager<infer TCollection> ? ItemType<TCollection> : never

class ComponentManager<TCollection extends Collection<Component>> {
  components: TCollection
}

type MyComponent = Component & { foo: string }
let manager: ComponentManager<Collection<MyComponent>>
let component: ComponentType<typeof manager> // typeof component is MyComponent
```

However, TypeScript won't let me use polymorphic `this` with `ComponentType`:

```typescript
class ComponentManager<TCollection extends Collection<Component>> {
  components: TCollection

  first(): ComponentType<this> {
    // ERROR: Type 'Component' is not assignable to type 'ComponentType<this>'.
    return this.components.first()
  }

  last(): ComponentType<this> {
    // ERROR: Type 'ItemType<TCollection>' is not assignable to type 'ComponentType<this>'.
    return this.components.last()
  }
}
```

It feels surprising that TypeScript is unable to reconcile those return types.

> it's recursive in a way that doesn't really work in structural positions.

I do not know enough about TypeScript to understand why that is the case.  Is it related to conditional types?  Would it necessarily be true even with some other mechanism to extract generic type parameters (other than conditional type + `infer`)?
