### ISSUE TITLE
custom regex as type that accepts only matching strings

### ISSUE THREAD

**Issue by antonioconselheiro** [microsoft/TypeScript#60292]
### 🔍 Search Terms

"regex type", "regular expression type"

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Hey people, how are you doing?
I would like to suggest use regex as a custom type:

```typescript
const hexId: /[a-z\d]+/ = 'b9283d50ff2db1d95c08395e73556bc5c147e22125280e78c569603ac6854fe6';
```

also

```typescript
type HexString = /[a-z\d]+/;
const hexId: HexString = 'b9283d50ff2db1d95c08395e73556bc5c147e22125280e78c569603ac6854fe6';
```

I searched through the closed and open issues and didn't find any suggestions exactly like this, but maybe I didn't look hard enough, because it seems like a very obvious suggestion to me.

### 📃 Motivating Example

This will help me create any custom string type.

### 💻 Use Cases

1. **What do you want to use this for?**
After validate a string with a regex, by using the regex as type I will be suure that I no need validate that data again.

2. **What shortcomings exist with current approaches?**
I found nothing functional that can bring me something like this.

3. What workarounds are you using in the meantime?
I'm using string type and crying.

**Comment by Josh-Cena** [comment]
https://github.com/microsoft/TypeScript/issues/41160

**Comment by antonioconselheiro** [comment]
I found this issue, but I was not sure if was exactly that

**Comment by MartinJohns** [comment]
It is exactly that.

**Comment by antonioconselheiro** [comment]
closed as duplicated
