### ISSUE TITLE
require("fs"); does not have types in .ts

### ISSUE THREAD

**Issue by huseeiin** [microsoft/TypeScript#60297]
### 🔎 Search Terms

when i change the extension to .js, the type of `require("fs").readFileSync` changes to `function readFileSync(path: PathOrFileDescriptor, options?: {
    encoding?: null | undefined;
    flag?: string | undefined;
} | null): Buffer` which is good and expected, but why is it not in .ts too?

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

it doesn't have intellisense

### 🙂 Expected behavior

to show types like in .js

**Comment by MartinJohns** [comment]
Your search terms are really messed up, no surprise you didn't find anything.

https://www.typescriptlang.org/tsconfig/#typeAcquisition

**Comment by huseeiin** [comment]
> Your search terms are really messed up, no surprise you didn't find anything.
> 
> https://www.typescriptlang.org/tsconfig/#typeAcquisition

that didn't fix the issue

**Comment by MartinJohns** [comment]
> that didn't fix the issue

The documentation tells you that it's intentional:

> In TypeScript projects you need to include the types in your projects explicitly.

So you need to include the types explicitly. Most likely you're missing the `@types/node` NPM package.

**Comment by RyanCavanaugh** [comment]
To expedite the triage process, we need everyone to follow the issue template and instructions.

When you clicked "Create New Issue", the issue form was pre-populated with a template and some instructions. We need you to read those instructions *completely*, follow them, and then fill in *all* the fields in that template.

We are not able to assist with issues that don't follow the template instructions as they represent a significantly larger amount of work compared to issues which are correctly specified. Thank you for understanding.
