### ISSUE TITLE
Auto imports break with exports in package.json when dependencies grow in Monorepo

### ISSUE THREAD

**Issue by makezi** [microsoft/TypeScript#60307]
### 🔎 Search Terms

"exports", "auto-import", "monorepo", "turborepo"

### 🕗 Version & Regression Information

The bug is present from all the versions of TypeScript I've tried ranging from v5.3.3 - v5.6.3

### 🙁 Actual behavior

Within a monorepo (turborepo for instance), when you have an internal package with `exports` being consumed by an app that has a large list of dependencies then the auto-import suggestions don't seem to work anymore. I [created the issue on turborepo](https://github.com/vercel/turborepo/issues/9298#issue-2601133773) which has more details about the issue. 

Basically if you use the `kitchen-sink` example and import a component from the internal package then VSCode will suggest the import correctly:

![Screenshot 2024-10-21 at 12 59 51 PM](https://github.com/user-attachments/assets/2ba5572a-16eb-4c1b-a9db-91f51030ee02)

This will break when the consuming app's dependencies grow (somewhere around a minimum of ~20 total dependencies)

![Screenshot 2024-10-21 at 1 14 43 PM](https://github.com/user-attachments/assets/187b18eb-ee2e-4d64-a533-58111347d346)

![Screenshot 2024-10-21 at 12 58 32 PM](https://github.com/user-attachments/assets/ec475298-b3ff-4ea5-96d7-29315e65a7fb)

This fixes itself if you were to remove some dependencies from the consuming app. You can also circumvent this by doing the right hand expression import of `repo/ui/counter-button` to get it to work again:

![Screenshot 2024-10-21 at 12 59 00 PM](https://github.com/user-attachments/assets/f6938e94-6ace-4f2e-9b68-5d8cc7d53430)

But upon workspace / tsserver restart it will tend to forget where the import is from as the dependencies grow / app grows larger. This issue persists in other IDEs besides VSCode such as Zed or Intellij Webstorm so it seems like its an issue with TypeScript itself.

To reproduce I have an example that uses said kitchen sink demo from Turborepo: https://github.com/makezi/turborepo-ts-exports-bug. I made sure to test in both VSCode and VSCode Insiders with no extensions.

1. `pnpm dlx create-turbo@latest --example kitchen-sink`
2. Go to `storefront`'s `package.json` file and add more dependencies so that the total number of dependencies is in the ballpack of ~20 or so. You can add the following to quickly reproduce:

```
"@t3-oss/env-nextjs": "^0.7.1",
"@tanstack/react-query": "^5.18.1",
"@vercel/analytics": "^0.1.1",
"@vercel/edge-config": "^1.2.1",
"@vercel/speed-insights": "^1.0.3",
"axios": "^1.4.0",
"date-fns": "^2.30.0",
"humps": "^2.0.1"
```

3. Delete everything in `page.tsx` so that there isn't a reference to `CounterButton` existing and just paste the following:

```ts
export default function Page() {
  // Auto import doesn't work
  return <Counter
}
```

And to get it working again just remove a package from the dependency list:

1. Remove `humps`
2. `pnpm i`
3. Reload workspace / tsserver
4. Auto import should work again

Note that every time I add / remove a package I always reload the workspace / TSServer for a clean slate otherwise VSCode will remember the import previously.

Perhaps there is a config issue I'm missing? 

### 🙂 Expected behavior

Auto import / suggestions to work for internal packages that expose code via `exports` within apps that have a large number of dependencies.

**Comment by jvandenaardweg** [comment]
Seeing the exact same behaviour and it's driving me nuts :)

I notice the import works fine when you already have a reference somewhere in a monorepo app (in your example `./apps/storefront`). So it's probably cached then by TS and uses that reference. But for new files, that are not used yet, there's no auto import suggestion.
