### ISSUE TITLE
Extension doesn't disable/update VSCode's built-in TS language features for TSConfig intellisense

### ISSUE THREAD

**Issue by jhmaster2000** [microsoft/TypeScript#60305]
Given a sample simplified TSConfig:
```json
{
    "compilerOptions": {
        "lib": [
            "ES2024.Collection"
        ]
    }
}
```
I am given a warning from the built-in "TypeScript and JavaScript Language Features" (Confirmed by running VSCode under "Reload with all extensions disabled") intellisense:
```js
Value is not accepted. Valid values: "ES5", "ES6", "ES2015", "ES2015.Collection", "ES2015.Core", "ES2015.Generator", "ES2015.Iterable", "ES2015.Promise", "ES2015.Proxy", "ES2015.Reflect", "ES2015.Symbol.WellKnown", "ES2015.Symbol", "ES2016", "ES2016.Array.Include", "ES2017", "ES2017.Intl", "ES2017.Object", "ES2017.SharedMemory", "ES2017.String", "ES2017.TypedArrays", "ES2018", "ES2018.AsyncGenerator", "ES2018.AsyncIterable", "ES2018.Intl", "ES2018.Promise", "ES2018.Regexp", "ES2019", "ES2019.Array", "ES2019.Intl", "ES2019.Object", "ES2019.String", "ES2019.Symbol", "ES2020", "ES2020.BigInt", "ES2020.Promise", "ES2020.String", "ES2020.Symbol.WellKnown", "ESNext", "ESNext.Array", "ESNext.AsyncIterable", "ESNext.BigInt", "ESNext.Collection", "ESNext.Intl", "ESNext.Object", "ESNext.Promise", "ESNext.Regexp", "ESNext.String", "ESNext.Symbol", "DOM", "DOM.AsyncIterable", "DOM.Iterable", "ScriptHost", "WebWorker", "WebWorker.AsyncIterable", "WebWorker.ImportScripts", "Webworker.Iterable", "ES7", "ES2021", "ES2020.SharedMemory", "ES2020.Intl", "ES2020.Date", "ES2020.Number", "ES2021.Promise", "ES2021.String", "ES2021.WeakRef", "ESNext.WeakRef", "ES2021.Intl", "ES2022", "ES2022.Array", "ES2022.Error", "ES2022.Intl", "ES2022.Object", "ES2022.String", "ES2022.SharedMemory", "ES2022.RegExp", "ES2023", "ES2023.Array", "Decorators", "Decorators.Legacy", "ES2017.Date", "ES2023.Collection", "ESNext.Decorators", "ESNext.Disposable".(1)
```
Things to note: No `ES2024.*` options listed.

However by running `npx tsc --noEmit --lib invalid` in a project with `typescript@next` (v5.7.0-dev.20241021) installed, it yields:
```js
error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'es2022', 'es2023', 'es2024', 'esnext', 'dom', 'dom.iterable', 'dom.asynciterable', 'webworker', 'webworker.importscripts', 'webworker.iterable', 'webworker.asynciterable', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2016.intl', 'es2017.arraybuffer', 'es2017.date', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2019.intl', 'es2020.bigint', 'es2020.date', 'es2020.promise', 'es2020.sharedmemory', 'es2020.string', 'es2020.symbol.wellknown', 'es2020.intl', 'es2020.number', 'es2021.promise', 'es2021.string', 'es2021.weakref', 'es2021.intl', 'es2022.array', 'es2022.error', 'es2022.intl', 'es2022.object', 'es2022.string', 'es2022.regexp', 'es2023.array', 'es2023.collection', 'es2023.intl', 'es2024.arraybuffer', 'es2024.collection', 'es2024.object', 'es2024.promise', 'es2024.regexp', 'es2024.sharedmemory', 'es2024.string', 'esnext.array', 'esnext.collection', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.disposable', 'esnext.bigint', 'esnext.string', 'esnext.promise', 'esnext.weakref', 'esnext.decorators', 'esnext.object', 'esnext.regexp', 'esnext.iterator', 'decorators', 'decorators.legacy'.
```
Things to note: `ES2024.*` options exist, including `ES2024.Collection` (casing irrelevant)

The [ES2024.Collection](https://github.com/microsoft/TypeScript/blob/main/src/lib/es2024.collection.d.ts) lib, as linked, adds `Map.groupBy`, which I can verify that despite the built-in extension's warning, is successfully added in a .ts file in the project, and removed should I heed the warning and remove the lib entry.

Additionally, if I provide an *actually* invalid lib entry in the tsconfig, I get an actual error (instead of warning) from *this* extension, with the same proper message as the `npx tsc` command above, in accordance to the nightly TS settings.

**Expected behavior:** Suppress the warnings from the non-nightly built-in features if this extension is providing its own proper equivalents.

## Environment
**VSCode:**
Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**typescript@next Extension:**
Version: 5.7.2024.10.20

**TypeScript: Select TypeScript Version command:**
Selected: "Use VSCode Version (5.7.0-dev.20241020)"

**There is no typescript package globally npm installed so there is no possible interference from such**

**Comment by mjbvz** [comment]
The json gets validated using https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/jsconfig.json

We typically only update this when the TypeScript release is stabilized. Until then you can ignore the error and the value still should be respected

Moving to TS to see if they want to change this process based on this feedback

**Comment by jhmaster2000** [comment]
Ignoring the error is definitely possible and it will still work fine as I've tested yes, personally I opted for using `ESNext.Collection`, instead as a way to trick it (being aware it has a few extra things but that's fine to me) but it's still a subpar experience for typescript@next users.

I suppose with this new information this becomes a kind of feature request, for the addition of a "tsconfig-next.json" variant of the JSON schema that IDEs like VSCode could then pick accordingly based on the TS version in use?

**Comment by RyanCavanaugh** [comment]
This is the first feedback we've gotten on this and it doesn't seem like a blocker. It's fine to send a PR to SchemaStore early if you'd like though

**Comment by jhmaster2000** [comment]
Without version distinction in the SchemaStore (as far as I can see) would that not simply create the reverse issue, where non-next users will see in their dropdowns the option for values they can not yet use, erroring later in the CLI? I suppose that sounds less annoying than an irremovable false-error, but neither seems desirable?
