### ISSUE TITLE
Constant variable flagged as unused when used as an object key

### ISSUE THREAD

**Issue by MariaSolOs** [microsoft/TypeScript#60310]
### 🔎 Search Terms

unused variable

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/PTAEAEDMEsBsFMB2BDAtvUkD2WB0AXAZwCh4APABywCd9QBjLRQugMQHl3QBeUAcg7s+AbmLEQEGAhTpQAI2TUCJaKiq1QAb1CDQAX0zUsqfrmDYsI4o2Z0F1Hlp2cAXKACM+4UA

### 💻 Code

```ts
// @filename foo.ts
export const FOO = 'FOO';

// @filename bar.ts
import { FOO } from './foo'; // 'FOO' is declared but its value is never read
const bar = { FOO: 1 };
```

### 🙁 Actual behavior

`FOO` is indeed used as a key in `bar` (surprisingly enough the code compiles just fine).

### 🙂 Expected behavior

For `FOO` above to not be marked as unused, or if this is by design for this to be properly documented.

**Comment by MartinJohns** [comment]
![Image](https://github.com/user-attachments/assets/3048e068-da71-49d8-bb98-74d52e88f8b8)

**Comment by MariaSolOs** [comment]
@MartinJohns Yes, pardon my TypeScript skill issues.
