### ISSUE TITLE
Generic VariadicOperation type helper (Higher-Kind types)

### ISSUE THREAD

**Issue by vladmw5** [microsoft/TypeScript#60325]
### 🔍 Search Terms

type helpers as type parameters, recursive types, variadic type

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Consider the following code sample:
```ts
type Intersection<L, R> = L & R;
```

I was not satisfied with the limitation of being able to pass only 2 operands, so I created a recursive type `MultipleIntersection`:
```ts
type MultipleIntersection<A extends any[]> = A extends [infer F, ...infer R extends any[]]
  ? Intersection<F, R extends [infer L] ? L : MultipleIntersection<R>>
  : never;

type x = {
  a: string;
}

type y = {
  b: number;
}

type z = {
  c: boolean;
}

type w = {
  d: string[];
}

type testCortege = [x, y, z, w];

type test = MultipleIntersection<testCortege> // x & y & z & w

// Basically my MultipleIntersection type does the following:
type validTest = Intersection<testCortege[0], Intersection<testCortege[1], Intersection<testCortege[2], testCortege[3]>>>
```

Generally speaking, in the implementation of the `MultipleIntersection` type, if I replace the `Intersection` type helper with any other **binary** type helper, I would get the "Multiple" (or n-ary, aka **variadic**) version of that type.

My question is: is it possible (is there any TS syntax for that) to create a generic `VariadicOperation<A extends any[], O extends ???what>` type that would allow to pass a **binary** type-helper?

[full code example](https://www.typescriptlang.org/play/?ssl=28&ssc=122&pln=28&pc=1#code/C4TwDgpgBAHlC8UDeAoKUCGAuKBnYATgJYB2A5gNwoC+KKokUICyaUARjiQK4C27EAlVr1w0AF4tU6AMY52AewUAbCBhLC6DaAHcpbACY58xcgG0AuptGNgEfAGEFBO2WiIzMADRMf4nzpWdDbQAJIkdgS4EDLARAokADwAMj4ASgB8LMlQAGRQaVQhUACy3MpxYKrhkdGx8UkAglAQMHYkBriYJCCWWYjNre2dUGakAGaCUABiPgB0CxNTaS1tEB1d6r0WFmwA-FA1gnVxCYmzBavDXWMkkwRQyRZQBzk4ZRVEVRBHUTGnSUyGTYXAgADdBEVtFA7PgWB9KtUIsd-g1ErDgE4XBA3MDimCMMoiAYACr2YAsX4nNEYrGuCBmAAMFh8VNRZ1pznpZgAjCzDsi-vUOeS6TiGQAmfmc7FuMwAZgsGWVKCAA)

### 📃 Motivating Example

Typescript is finally Turing complete with this feature!!!

### 💻 Use Cases

1. To be able to create generic and reusable type helpers
2. No TS syntax supports that behavior
3. I don't know any workarounds at the moment

**Comment by xiBread** [comment]
#1213

**Comment by RyanCavanaugh** [comment]
> Typescript is finally Turing complete with this feature!!!

This has been true for a long time, for better or worse 🥵
