### ISSUE TITLE
Allow importing files from JSON schemas

### ISSUE THREAD

**Issue by cshaa** [microsoft/TypeScript#60329]
### 🔍 Search Terms

JSON schemas are the standard for describing the structure of JSON and YAML data. They are essentially a stripped down version of TS types. It would greatly increase DX if one could just import a JSON schema and use it as a type in TS. Currently, one has to manually convert the schema into TS using something like `npx json-schema-to-typescript -i schema.json -o schema.ts`.

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

There are several ways this could be realized. The most straightforward seems to be to build on [import attributes](https://github.com/tc39/proposal-import-attributes).
```ts
import type Schema from "./schema.json" with { type: "json-schema" };
```

We could also allow specifying a schema for imported JSON files:
```ts
import config from "./config.json" with { type: "json", $schema: "./schema.json" };

// ... would be the same as:
import config_ from "./config.json" with { type: "json" };
import type Schema from "./schema.json" with { type: "json-schema" };
const config = config_ as Schema;
```

Feel free to bikeshed the syntax.

### 📃 Motivating Example

```ts
import type Person from "https://example.com/person-schema.json" with { type: "json-schema" };

const res = await fetch("https://example.com/get-person");
if (res.ok) {
  const p: Person = await res.json();
  p.name // correctly typed!
}
```

```ts
import type Config from "https://example.com/config-schema.json" with { type: "json-schema" };
const config: Config = YAML.parse(
  await Deno.readTextFile("./config.yml")
);
config.version // correctly typed!
```

### 💻 Use Cases

Simplifying working with JSONs and YAML files, not having to run `json-schema-to-typescript`.

**Comment by MartinJohns** [comment]
I'd call this almost a duplicate of #49314.  
Relevant comment: https://github.com/microsoft/TypeScript/issues/49314#issuecomment-1142727347

> The Venn diagram of things supported by JSON Schema and by TypeScript has substantial area in both non-overlapping regions, including things we're likely to not ever implement (maxProperties, minLength, etc). Without a 1:1 translation between JSON Schema and TS we'd be left making a ton of policy decisions that people might need to be configurable, and it'd just be a huge mess.

**Comment by cshaa** [comment]
Yeah, you're right. Closing this in favor of the linked issue.
