### ISSUE TITLE
Wrong message type in Error constructor

### ISSUE THREAD

**Issue by hhelwich** [Microsoft/TypeScript#6032]
The JavaScript `Error` constructor can handle any type for the `message` parameter [1] and then converts it to a string (non nullable) `message` property.
So in the `ErrorConstructor` definition in `src/lib/core.d.ts` [2] the type for the `message` parameter should be `any` instead of `string`.

[1] http://www.ecma-international.org/ecma-262/6.0/#sec-error-message
[2] https://github.com/Microsoft/TypeScript/blob/f10c7cc154cb5b62a9368790e30d65b9a2bcfc3d/src/lib/core.d.ts#L869

**Comment by mhegazy** [comment]
This is true to a lot of JS APIs, e.g. parseInt. the lib.d.ts definitions favors expressiveness over accuracy here. All declarations in this file are augmentable, so adding a declaration like below to one of your files should do the trick.

```ts
interface ErrorConstructor {
    new (message?: any): Error;
    (message?: any): Error;
}
```
