### ISSUE TITLE
wiki: JSDoc link not found

### ISSUE THREAD

**Issue by plehegar** [microsoft/TypeScript#60338]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

From https://github.com/microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio#vsdoc
[[
VSDoc is no longer supported in favor of [JSDoc](http://usejsdoc.org/about-getting-started.html) which is easier to write and the accepted standard for JavaScript.
]]

The above link to JSDoc returns a 404 : http://usejsdoc.org/about-getting-started.html

You may consider replacing it with https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc

**Comment by jakebailey** [comment]
The wiki does accept PRs: https://github.com/microsoft/TypeScript-wiki

**Comment by plehegar** [comment]
Thanks. I'll open a PR there.
