### ISSUE TITLE
interface 中字段的类型使用 typeof 时希望默认能继承 typeof 后表达式的 jsdoc 注释

### ISSUE THREAD

**Issue by yamiwamiyu** [microsoft/TypeScript#60341]
### 🔍 Search Terms

"typeof","jsdoc"

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

```
/** JSDoc1 */
const test = { a: 0 }

declare module 'vue' {
  interface ComponentCustomProperties {
    /** JSDoc2 */
    testInInterface: typeof test,
  }
}

const test2 = {
  /** JSDoc3 */
  test
}
```
我希望不写 JSDoc2 或 JSDoc3 时，testInInterface 和 test2.test 能具备 const test 的注释内容 JSDoc1

### 📃 Motivating Example

interface 具备声明合并的特性，让开发者扩展组件库中定义的接口。在前端开发中，扩展 vue 的全局组件，指令，属性是经常用到的。

下面以一个 vue 组件的为例，包含其全局引入，局部引入的使用方案，现在都缺少 JSDoc 注释
- 全局引入
```
import vueComponentWithJsDoc from './test.vue'

declare module 'vue' {
  interface GlobalComponents {
    vueComponentWithoutJsDoc: typeof vueComponentWithJsDoc
  }
}
```
- 局部引入
```
import vueComponentWithJsDoc from './test.vue'
import { defineComponent } from 'vue'

export default defineComponent({
  components: { vueComponentWithoutJsDoc: vueComponentWithJsDoc  }
})
```

在 .vue 的模板中使用组件时，以上两种方案都缺少了 JSDoc 注释
```
<template>
  <vue-component-without-js-doc />
</template>
```

### 💻 Use Cases

1. 让扩展的全局内容具备 JSDoc 注释
2. 当然也有将 JSDoc 只写到接口中，实现中不写的做法。但这样也不行，因为实现也可能不是全局引用而是单独引用，例如 vue 的组件，单独引用时也需要有 JSDoc 注释
3. 目前需要将具体实现的 JSDoc 注释拷贝到扩展的接口中，但这样需要维护两份注释

**Comment by RyanCavanaugh** [comment]
Sorry, we need reports to be in English
