### ISSUE TITLE
unexpected argument in new decorators function

### ISSUE THREAD

**Issue by OlegDokuka** [Microsoft/TypeScript#6034]
Hi guys!

Today I have moved to typescript 1.7.3, and got unexpected issue in my decorator (there is some code below)

```
export function inject(requestType: Class, ...genericTypes: Class[]): any {
        return (prototype: any, ...properties: any[]) => {
            let argsCount = properties.length;

            switch (argsCount) {
                case 1: {
                    //some code
                } break;
                case 2: {
                    if (typeof properties[1] === typeof 1) {
                       //some code
                    }
                } break;
            }
        }
    }
```

This worked perfectly with TS 1.6, where decorators function looked like 

```
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
    switch (arguments.length) {
        case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
        case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
        case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
    }
};
```

and compiler for TS code
```
class NoiseMakerClass {
    @inject(SimpleNoiser) ownNoiser:SimpleNoiser = undefined;

    doWork() {
        this.ownNoiser.makeNoise();
    }
}
```
generate next JS code

```
__decorate([
        inject(SimpleNoiser)
    ], NoiseMakerClass.prototype, "ownNoiser");
```

***BUT*** new TS 1.7.3 generate a bit different function with new one unexpected argument

```
__decorate([
        inject(SimpleNoiser)
    ], NoiseMakerClass.prototype, "ownNoiser", void 0);
```
Also, I have found that last 'void 0' argument added only if my `tsconfig.json` contains next code

```
{
  "version": "1.7.3",
  "compilerOptions": {
    "target": "es5",
    "declaration": true,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": false,
    "sourceMap": true,
    "listFiles": true,
    "outDir": "",
    "out": "Compiled/typejector.js",
    "experimentalDecorators": true
  },
  "files": [
    "app.ts"
  ]
}
```

Can someone explain me why compiler add 'void 0' argument in this case?

**Comment by OlegDokuka** [comment]
Hi guys, again. I spend a bit more time on this issue and found, that this additional argument added only when in my `tsconfig.json` exist `"target": "es5",` property

**Comment by OlegDokuka** [comment]
Also, due to *lib.d.ts*, `MethodDecorator` declaration should  have next list of parameters
```
declare type MethodDecorator = <T>(target: Object, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<T>) => TypedPropertyDescriptor<T> | void;
```
but in compiled JS code there are no passings of `descriptor` argument

For example:
```
 @postConstructor
    doWork() {
        this.ownNoiser.makeNoise();
    }
```
compiled to 
```
__decorate([
        postConstructor
    ], NoiseMakerClass.prototype, "doWork");
```
or for ES5 to 
```
__decorate([
        postConstructor
    ], NoiseMakerClass.prototype, "doWork", null);
```

Is it okay???

**Comment by OlegDokuka** [comment]
Also, I created [example](http://www.typescriptlang.org/Playground#src=function%20test(a%3A%20any%2C%20b%3F%3A%20any%2C%20c%3F%3A%20any)%3A%20void%20%7B%0A%0A%7D%0A%40test%0Aclass%20Greeter%20%7B%0A%20%20%20%20%40test%20greeting%3A%20string%3B%0A%09%0A%09%0A%20%20%20%20constructor(%40test%20message%3A%20string)%20%7B%0A%20%20%20%20%20%20%20%20this.greeting%20%3D%20message%3B%0A%20%20%20%20%7D%0A%09%40test%0A%20%20%20%20greet()%20%7B%0A%20%20%20%20%20%20%20%20return%20%22Hello%2C%20%22%20%2B%20this.greeting%3B%0A%20%20%20%20%7D%0A%7D%0A) with this issue

**Comment by OlegDokuka** [comment]
Also, I understand that by ES 3 specification there are no Property descriptor, but if I targeting on ES5, or even on ES6, why should I gtt this?

**Comment by DanielRosenwasser** [comment]
@rbuckton could you take a stab at answering the concerns here?

**Comment by OlegDokuka** [comment]
So, is it my lack of knowledge or it is an issue?

**Comment by mhegazy** [comment]
@rbuckton can you take a look.

**Comment by rbuckton** [comment]
The `__decorate` helper was modified to optimize for ES3, and introduced the additional argument to specially handle "fields". 

In ES5/6, we effectively call each decorator for a field like this:
```js
// ts
class C {
  @dec field;
}

// pseudo-js
dec(C.prototype, "field", void 0);
```

When TypeScript passes `void 0` (e.g. `undefined`) to the `__decorate` helper, it indicates that:
* The decorator target is a "field" 
* That it is safe for the decorator to return a new property descriptor that can be piped into any remaining decorators
* That it is safe call `Object.defineProperty` with any resulting property descriptor.

When TypeScript passes `null` to the `__decorate` helper, it indicates that:
* The existing descriptor should be read by calling `Object.getOwnPropertyDescriptor`
* It is safe to call `Object.defineProperty` with the result.

For ES5, TypeScript may eventually pass a cached copy of the PropertyDescriptor used for an accessor instead of `null`.

For ES3, TypeScript will not provide this argument. This indicates that the `__decorate` helper will not provide the descriptor to any decorators, and it is not safe to call `Object.getOwnPropertyDescriptor` or `Object.defineProperty`.

As a result, you might be better off writing your decorator as follows:

```ts
export function inject(requestType: Class, ...genericTypes: Class[]): any {
  return (target: any, ...args: any[]) => {
    if (args.length === 0) {
        // constructor
        // ...code...
    }
    else if (args.length === 1) {
        // property/field (ES3) 
        const [name]: [PropertyKey] = args;
        // ...code...
    }
    else if (args.length === 2 && typeof args[1] === "number") {
        // parameter
        const [name, paramIndex]: [PropertyKey, number] = args;
        // ...code...
    }
    else if (args.length === 2 && typeof args[1] === "undefined") {
        // field (ES5+)
        const [name]: [PropertyKey] = args;
        // ...code...
    }
    else if (args.length === 2) {
        // property (ES5+)
        const [name, descriptor]: [PropertyKey, PropertyDescriptor] = args;
        // ...code...
    }
  }
}
```

We are currently working with TC39 to determine what decorators will look like for ES2016 (ES7), and ways of making this more consistent in the future.

**Comment by rbuckton** [comment]
As this is presently the expected behavior for TypeScript, I am closing this issue until such a time as TC39 has adopted a stage 3 proposal for decorators.
