### ISSUE TITLE
TypeScript confuses exports resolution from dependencies in a monorepo setup

### ISSUE THREAD

**Issue by ferferga** [microsoft/TypeScript#60350]
### 🔎 Search Terms

``monorepo``, ``exports in monorepo``, ``exports conflicts``

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about monorepos, imports and exports

### ⏯ Playground Link

**Monorepo setup**
https://stackblitz.com/edit/vitejs-vite-9abzaz?file=packages%2Fconfigs%2Feslint.config.ts

#### Steps to reproduce:

1. Hover over the imported ``Linter`` and ``Linter.Config[]`` statement:
![Image](https://github.com/user-attachments/assets/475b6338-21f6-47cf-9068-81853a05fd6b)
![Image](https://github.com/user-attachments/assets/98dc2984-9e9e-4c6b-b8dd-8140c1d10156)

2. Do the same with ``packages/main/eslint.config.ts``. See how the imports are resolved correctly there.

*A workaround*:

1. Rename ``packages/configs/eslint`` folder to ``packages/configs/eslint-new``
2. Change the ``exports`` field in ``packages/configs/package.json`` from ``eslint`` to ``eslint-new`` as well.
3. Repeat the reproduction steps above and the types will be imported correctly

**Minimal setup without a monorepo (where the issue doesn't reproduce)**: https://stackblitz.com/edit/vitejs-vite-xqvbde?file=eslint.config.ts
### 💻 Code

In a package of a monorepo setup with the following package.json (with the bare minimum elements):

```json
"exports": {
    "./library": "./whatever"
},
"devDependencies": {
    "library": "x.y.z"
}
```
The type ``X`` is not recognised, even though it's exported by the ``library`` from ``devDependencies``.

```ts
import type { X } from 'library'';
```

This **does not** occur in a non-monorepo setup.

### 🙁 Actual behavior

TypeScript resolves the type as ``any``, despite being exported by ``library``.

### 🙂 Expected behavior

When TypeScript finds a conflicting import, TypeScript should do a fallback

### Additional information about the issue

I provided 2 reproductions: one without a monorepo, and another with the monorepo.

A lot of issues are similar (https://github.com/microsoft/TypeScript/issues/59620 and https://github.com/microsoft/TypeScript/issues/60331 are similar, specially the former). However, I believe (I might be wrong though) that TypeScript should do a fallback in this case and none of the issues are exactly the same (no one mentions the conflict with an installed package).

**Comment by andrewbranch** [comment]
`import type { Linter } from 'eslint'` is resolving to `./eslint/index.ts` because you have `"baseUrl": "."` set in your tsconfig.json. [(docs on `baseUrl`)](https://www.typescriptlang.org/docs/handbook/modules/reference.html#baseurl)

**Comment by ferferga** [comment]
@andrewbranch Thank you very much and sorry for my oversight!
