### ISSUE TITLE
Unable to disable tsc .tsbuildinfo file creation

### ISSUE THREAD

**Issue by kadirgun** [microsoft/TypeScript#60360]
### 🔎 Search Terms

.tsbuildinfo disable

### 🕗 Version & Regression Information

- This changed between versions 5.6 and 5.6.3

### 💻 Code

```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "composite": false,
    "incremental": false,

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": "."
  },
  "include": ["src"]
}
```

### 🙁 Actual behavior

```bash
tsc -b
```

command started generating .tsbuildinfo file in version 5.6.3. In version 5.5 it did not.

### 🙂 Expected behavior

When the incremental option is set to false, it should not create a .tsbuildinfo file.

**Comment by MartinJohns** [comment]
This is working as intended. See: https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#.tsbuildinfo-is-always-written

**Comment by AlttiRi** [comment]
This file does not look useful for me.
I want to disable `.tsbuildinfo` file creation.
Is it possible?
