### ISSUE TITLE
Generic abstract class inheritance is broken

### ISSUE THREAD

**Issue by p-jack** [microsoft/TypeScript#60363]
### 🔎 Search Terms

abstract generic class inheritance

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about classes and generics.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.3#code/IYIwzgLgTsDGEAJYBthjAgggHgCoD4EBvAKAQVEhngoAoIAuXASibIoCZ6nniEoAphACuUAHYJEAXxIySlaHEQo0GAEJ5CAgB4QBYgCYYcBYuwXVEIbizbkQXRiz6CR4yQhlyV6BAGFNBB09Q3VA0nJgG14ifiFRCWl2aycYuLdEz1kSElgAezFIJAQAXgQxAQB3f2wxYQBbEAEofFpmXIKi4FL-ADpgLgBGYfb8wqsev16HWg459pIAekWEADk8vUkAC2BEMQKAWgBzfWaAS1gKcEUaM7Et84hgMVgBBEq8qABrDDQg7QADgJ4AIDAwchYlEhUL4ABpmSLXSwIbTcOqNZqsdFNKDsbSOBjYzEueLuaQIbLyJFQnwYACa-xCRgQ8IiVyoUIAnmiGjisbzmuxOQSiVA0q4Eh4pBTvDCMAAtRn6ZkMtmoxii8WkzIycjcjUCsUkjJSyljIoALx6FWq8raHXGKJ6Ft6+Now0Go06iE5zt6wtm8wdYDyyAEvWQeSOtCI2gANAhOVJmEA

### 💻 Code

```ts
abstract class A<T> {
  abstract a(t:T):T
  a2(t:T) { return t }
}

abstract class B<T> extends A<T> {
  abstract b(t:T):T
  b2(t:T) { return t }
}

class C<T> extends B<T> {
  override a(t:T) { return t }
  override b(t:T) { return t }
}

const c = new C<number>()
const a = C.a2(111)
const b = C.b2(222)

// Note that non-generic abstract inheritance works as expected:

abstract class X {
  abstract x(t:number):number
  x2(t:number) { return t } 
}

abstract class Y extends X {
  abstract y(t:number):number
  y2(t:number) { return t } 
}

class Z extends Y {
  x(t:number) { return t }
  y(t:number) { return t }
}

const z = new Z()
const x = z.x2(111)
const y = z.y2(222)
console.log({x, y})
```

### 🙁 Actual behavior

Compiler errors: 

TS2339: Property 'a2' does not exist on type 'typeof C'.
TS2339: Property 'b2' does not exist on type 'typeof C'.

### 🙂 Expected behavior

I can access inherited properties in an instance of a class with multiple generic abstract super classes.

### Additional information about the issue

Seems to have been broken since at least 3.3.3, the earliest version available in the playground.

**Comment by MartinJohns** [comment]
> I can access inherited properties in an instance of a class

You're not trying to access the instance properties. In line 17 and 18 you wrote `C` (referring to the static elements) instead of `c` (your instance). Change it to `c` and it compiles just fine.
