### ISSUE TITLE
BUG: Code Logic Changes When Compiling TypeScript to ES2022 Compared to Previous Versions

### ISSUE THREAD

**Issue by LMskt** [microsoft/TypeScript#60364]
### 🔎 Search Terms

ES2022 
JavaScript Class Field Declarations
Code Logic Changes 

### 🕗 Version & Regression Information

- This is the behavior in every version

### ⏯ Playground Link

https://www.typescriptlang.org/zh/play/?target=9&jsx=0&module=7#code/IYIwzgLgTsDGEAJYBthjAggitGDeAUAsUgPYB2kUArvKVABQCUChJ7ZlpyApgHTJSAcwYByTAGFU6UUwDcRDsQgALAJZg+a8mohrgyNQC8ezBUuKwKYbv0EjxU3AFptu-YZOzzFq114CwmLY0mCiADQIDKoaCGhx5ACeTHzkwAC2PPKKxAC+BDlx4NBwiG56BsamTABcCABupGoAJgr5BDjoCABCnRg8AB4QPOTNGCG4rDkADlBq9cDDCGmZdVTaQgqFflS0EPTMUxacNgH2Yt1OMtnHYNTTPIw3vta2gQ6Xoc53D1Dehewdm9zqJeqEIggYpoVlkfHkCuxyh4qoc2BY1AAzKIAQihqQyWSOxxIQLOQVEhmo6X03DUVJp-2JJDxMIQAF4EBS6dTgKRRHCOPl2Pl2jsypQIMByLAeOzljwAO49PpmAjaSBSmVaHQVTzVLZAA

### 💻 Code

```
abstract class Aclass {
    constructor() {
        console.log('AClass');
        this.initialize();
        console.log('AClass-initialize');
        console.log('Aclass', (this as any).name);
    }
    abstract initialize(): void;
}
class Bclass extends Aclass {
   private name: string;

    constructor() {
        console.log('BClass');
        super();
        console.log('BClass-super');
        console.log('Bclass', this.name);
    }

    initialize() {
        if (!this.name) {
            console.log('liumiaoliumiao');
            this.name = 'liumiao';
        }
    }
}
const instance = new Bclass();
instance.initialize();
```

### 🙁 Actual behavior

When compiling TypeScript code to the ES2022 target, the resulting JavaScript code differs from the code compiled to earlier versions.  Specifically, in ES2022, class fields are preserved.  This preservation of class fields changes the logic of my class, **resulting in different log outputs.**

- When compiling to ES2022, the above TypeScript code is compiled into the following JavaScript code:

```
class Aclass {
    constructor() {
        console.log('AClass');
        this.initialize();
        console.log('AClass-initialize');
        console.log('Aclass', this.name);
    }
}
class Bclass extends Aclass {
    name;
    constructor() {
        console.log('BClass');
        super();
        console.log('BClass-super');
        console.log('Bclass', this.name);
    }
    initialize() {
        if (!this.name) {
            console.log('liumiaoliumiao');
            this.name = 'liumiao';
        }
    }
}
const instance = new Bclass();
instance.initialize();

```
and the log output is:
```
BClass
AClass
liumiaoliumiao
AClass-initialize
Aclass liumiao
BClass-super
Bclass undefined
liumiaoliumiao
```
- When compiling to ES2015, the above TypeScript code is compiled into the following JavaScript code:
```
class Aclass {
    constructor() {
        console.log('AClass');
        this.initialize();
        console.log('AClass-initialize');
        console.log('Aclass', this.name);
    }
}
class Bclass extends Aclass {
    constructor() {
        console.log('BClass');
        super();
        console.log('BClass-super');
        console.log('Bclass', this.name);
    }
    initialize() {
        if (!this.name) {
            console.log('liumiaoliumiao');
            this.name = 'liumiao';
        }
    }
}
const instance = new Bclass();
instance.initialize();
```
and the log output is:
```
BClass
AClass
liumiaoliumiao
AClass-initialize
Aclass liumiao
BClass-super
Bclass liumiao
```
**_Obviously, in ES2022 and later, the class field of the class is preserved, resulting in a change in the logic of the entire class_**

### 🙂 Expected behavior

My expectation is that no matter what version of js code is compiled to, the internal logic of the classes in TS should not change. Otherwise, it will cause uncontrollable effects.

**Comment by whzx5byb** [comment]
> Specifically, in ES2022, class fields are preserved.
This is the standard behavior for es6 class fields. 

For details, see https://www.typescriptlang.org/tsconfig/#useDefineForClassFields, and  https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#usedefineforclassfields-now-defaults-to-true-on-esnext-and-eventually-on-es2022

**Comment by LMskt** [comment]
Thank you for your response.
 I read the document (https://www.typescriptlang.org/tsconfig/#useDefineForClassFields) which mentions that this behavior occurs after ES2022. However, I am confused because the behavior of TypeScript code differs before and after ES2022. Is this behavior expected?
﻿
﻿

**Comment by MartinJohns** [comment]
> However, I am confused because the behavior of TypeScript code differs before and after ES2022. Is this behavior expected?

Yes. The documentation he linked states that the default value for `useDefineForClassFields` depends on your target version, so if you don't specify this setting yourself it will change from ES2022 onwards.

**Comment by LMskt** [comment]
Got it, I understand that if this option is not configured, the difference in code logic in TS after ES2022 is expected. Is it possible to change this default value? Our project did not set this property, which caused issues after packaging.

**Comment by LMskt** [comment]
Additionally, as far as I know, many TS users are not aware of this configuration.

**Comment by MartinJohns** [comment]
> Is it possible to change this default value?

No, but it's possible to set `useDefineForClassFields` explicitly. The default change with ES2022 is intentional, because when people use ES2022 they usually expect ES2022 behavior.

> Additionally, as far as I know, many TS users are not aware of this configuration.

There's no good solution to the problem of users not reading documentation.

**Comment by LMskt** [comment]
Got it, thank you very much. I will close this issue immediately.
