### ISSUE TITLE
HTMLInputElement element does not contain webkitdirectory property

### ISSUE THREAD

**Issue by JosuaCarl** [microsoft/TypeScript#60373]
During checking, I get
```
Type '{ style: { display: string; }; id: string; name: string; type: "file"; accept: string; multiple: boolean; webkitdirectory: boolean; onChange: (e: ChangeEvent<HTMLInputElement>) => void; disabled: boolean; }' is not assignable to type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.
  Property 'webkitdirectory' does not exist on type 'DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>'.ts(2322)
```
The webkitdirectory is present, as mentioned in [https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory).

**Comment by MartinJohns** [comment]
It's present in 5.6.3: [Playground Link](https://www.typescriptlang.org/play/?#code/CYUwxgNghgTiAEYD2A7AzgF3gNyhAXPABIAqAsgDICSKADgK4YCiEIAtiChgFC4QB0AdxAAjANYBLDMAlwwGJDACe8ALzwMMeiADc3IA)

**Comment by nmain** [comment]
It's been there since at least 4.4.4:

https://www.typescriptlang.org/play/?ts=4.4.4#code/CYUwxgNghgTiAEYD2A7AzgF3gNyhAXPABIAqAsgDICSKADgK4YCiEIAtiChgFC4QB0AdxAAjANYBLDMAlwwGJDACe8ALzwMMeiADc3IA

**Comment by JosuaCarl** [comment]
You are of correct, it is an issue with React, which I found out a few minutes later. I wanted to close this issue an hour ago, but could not find it again, after creation. Don't know why, but anyway, sorry for your time not well spent.
