### ISSUE TITLE
Type of global `navigator` object incorrect since node.js 21

### ISSUE THREAD

**Issue by fabb** [microsoft/TypeScript#60387]
### 🔎 Search Terms

navigator, node

### 🕗 Version & Regression Information

- This issue happens since updating to node.js 21

### 💻 Code

This is a next.js app with server-rendering.

```ts
export const EditorControls: FunctionComponent<EditorControlsProps> = (props) => {
    const metaKey = typeof navigator !== 'undefined' && navigator.appVersion.indexOf('Mac') !== -1 ? '⌘' : 'Strg'
    return null
}
```

### 🙁 Actual behavior

This crashes at runtime because since node.js 21, a global `navigator` object was introduced which only contains a few keys and is not compatible with the `Navigator` interface defined in `lib.dom.d.ts`. See https://github.com/nodejs/node/issues/50269

### 🙂 Expected behavior

Typescript should regard the node.js `navigator` object type and make all keys on it optional, except when accessed via `window.navigator`

**Comment by MartinJohns** [comment]
> Typescript should regard the node.js `navigator` object type and make all keys on it optional

That would be a massive breaking change for something that's essentially a configuration error. You shouldn't be using `lib.dom.d.ts` in a NodeJS context. And there's a lot more in this definition file that's not supported by NodeJS, you want to make that all optional too, or special case this one instance?

**Comment by Josh-Cena** [comment]
That would be an issue far more general than this: https://github.com/microsoft/TypeScript/issues/53971

**Comment by RyanCavanaugh** [comment]
The reality is that many projects end up with both node and DOM typings loaded at the same time due to transitive dependencies. There's not really a straightforward solution that would fix this situation without breaking huge swathes of working code.
