### ISSUE TITLE
Type inference problem when using inline vs declared generator function

### ISSUE THREAD

**Issue by patrickshipe** [microsoft/TypeScript#60382]
### 🔎 Search Terms

async generator inference pipeline anonymous

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about declared vs anonymous function inference

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=99&ts=5.6.3#code/JYWwDg9gTgLgBAbzmYYCmAbYA7NcC+cAZlBCHAOTYQAmaAXAM4xRoCGIA9GKSMI2kYUA3AChRbRgE9sAY2IBXOTGARscEGxwAKAJSJRcOLLXM4OMAvgBeOAG0AjABo4AJhcBmFwBYAumMM4NgB3LXgUdCxcbUCjCysnWKDpOUVlVWwAKjhtRggFKFk0fQQkoyJoINDgeG0TbDNZAAslAGs4CCI4PIKikrKjOClgTBpjFux27NcxQcH8JPxEuckZeSIlWRU1bNz8wuKDOfLKkLCc+saJ9s7u-b6j46Nh0fG2uABqOAdZ44W5pZJVapDbpNQ5HoHfpPCpQKrnOqmeDNd63SEPUpPIyXCAYNAAOgwEAA5toKAAxHBsDBwbAKEAAIzQUCELhRk10vwBi2WcE5ogWEhS60223UmhwABVghA9I9LvB4jZ7M43J4fP5xNikUEaDQAPK4OC2YEisFZHJJdEMOAAQWFAEkYMy2Ay8QAeOmM5kAPl5unoduFAHE0LgoGwYNBPfSmVAXAA3CDAGguNjYKQ+x4nOFnGoXHXsm5da3Q44vDBjIufb5cgiBfABIx58KoTA4NAxOZK3nN4VpLYZXal7ODWHw-OIhrI64dEv3Q6YrEVquz6Z1oz-ea93UG3A700DsUQhdlubjlsF6dvSZzu69RcDbUNXEEomkilUmleuOsm+tfkni3Td-TEQUJWwPQxAg6VZX5IA

### 💻 Code

```ts
import { pipeline } from 'node:stream/promises';

async function main() {
  const input = [1, 2, 3, 4];

  await pipeline(
    input,
    async function* (source) {
      for await (const chunk of source) {
        yield chunk * 2;
      }
    },
    async function* (source) {
      for await (const chunk of source) {
        yield chunk + 1;
      }
    },
    async function (source) {
      for await (const chunk of source) {
        console.log('Final numbers', chunk);
      }
    },
  );
}

async function mainTwo() {
  const input = [1, 2, 3, 4];

  const addOne = async function* (
    source: AsyncIterable<number>,
  ): AsyncGenerator<number, void, any> {
    for await (const chunk of source) {
      yield chunk + 1;
    }
  };

  await pipeline(
    input,
    async function* (source) {
      for await (const chunk of source) {
        yield chunk * 2;
      }
    },
    addOne,
    async function (source) {
      for await (const chunk of source) {
        console.log('Final numbers', chunk);
      }
    },
  );
}

main();
mainTwo();
```

### 🙁 Actual behavior

When inlining the `addOne` function (in `main`), the type of the rest of the pipeline is inferred.

Type of function:

![Image](https://github.com/user-attachments/assets/cbe3dae7-fd96-4ee0-8065-122e87040e7b)

Type of argument in the next function:

![Image](https://github.com/user-attachments/assets/88b4f56e-cb2b-4f48-8c10-94812a54de97)

When extracting `addOne` (in `mainTwo`), even matching the exact same types, the compiler is unable to infer the type of the next async iterable and you get an error for implicit `any`.

Type of function (exact same as before 🤔 )

![Image](https://github.com/user-attachments/assets/ff56e305-3ffa-4314-8722-26b84f6aa356)

Type of argument in the next function not inferred:

![Image](https://github.com/user-attachments/assets/99034620-34c1-4d17-9c34-c501554fbac3)

### 🙂 Expected behavior

The second example should behave exactly as the first, and `source` should be inferred.

### Additional information about the issue

I was hesitant to file this issue given the possibility something is wrong with `@types/node`, but this seems to be beyond the typings because the typings shouldn't know/care whether or not I declare the function inline or reference it.

**Comment by Andarist** [comment]
With `@types/node` inlined: [TS playground](https://www.typescriptlang.org/play/?target=99&noErrorTruncation=true&ts=5.7.0-dev.20241030#code/JYOwLgpgTgZghgYwgAgOpWGOAjANhAZTCgjgFtkBvAKGWQHcMs8IAuZbAe0-zhAG5aDJhAAU2AK4wY0dgGdioAOYAaZAmwB+dqOhRtyAKJQonKMgA+yEBNy4AlMgC8APmQA3TsAAm99lx5SASFGTDEFKHlFEFV1LR09A2NTcysbO0dXDy9ff25eYLoIEG9RDQNRTLdPHz9kMAALYDlBIpLRbzgsKIwYtXKdKuza9kbm1uRi0oie5X745Ernapy6sZbqAF9qUEhYRBQAJVJOliISciohC9P8PMC+CZvROWAALwgDGzJsaDqI5QTAAOcAkcjEayaGzoJDkEjIENGUImzQACqDwaU6gECsDgECIAAeAAqkwAHpASnI0EwcPhzqQyC5REI6N4IApQF1gJwQOxiSpWchOECwDyQHIDJRJiUDDigpZkBIShAYKAIN5kJtBXQ6sSJsqgfixOzOSBubyDOhMHTCMRGZDxiEoHAgaIeN4GeR2Mc4Lc7RcyI7ocgANoEACePx4ADo4HIIyAEABJPZdMwAXUq7AAggmk6noLbCy6wGZCQCYi5BNsduBoPAkMhfd5rZAvRQIBSptSW7aO2o2-37ZdKLWwBGCchUcbcOqCJwJFAkCS3E5kCXbavBBOpzOCXOQBBiS6JTAzGQF0uV8S19PZ-PF8uibfFfuIIfj6e5OeoGRCXwEZqLeO6Tig76fiefA-hehIEOSlLeNSEHqlBZ4Xlez4ASAEYuGoACqa5CFYLZtgGjLEYsLJ0DRyByE+SDsPBXaIdS1G0TRMZcXAUBKHI7CAaGGZCrqywbmmLCEqAMjmAQr5WHmiYphJ+BSSAMnIHJLgiTRmjIIpBYqUSWk6XQTE6jRQwGcpRaSYR9igXuD5HgAIhyYrmmKvKbiwABiyoIF5ICrs4ixCPR15sPp+Y2S6km3oKVkxT5qmAdW1C7uBzkQG5ZoWiAqKmGQzQQP5SZBSSaione7ERc+ubJUZq6JWJhWcMV4KEtVjlZQe6q5R5+WEkIzHdlS959UeaEwX+mErmlFmooKd6jaxE0fqh36-peDFEtJ0CabeQiaDpVhDmcI5kKd62fgNXJBSlpUBRVJkcW+2V3Z54ptR1T3leKcECtO2lmdYEDuNAPU3eqP0lXBCE9tDrnufdAOAWoaVEXQq2IyhyN5UFsPgmVgVozhaj7eY1VCnpRNEtTtHsHThI1N46XUOyCC4DxKAwM94rIEak1EkIOYI+NeOELt2G4RZxIAIzi0hSNftB22EjmGM4XhQjEgATEryHZdN6sK1rstCAAQobKufUN+vmzrzLhbtuYWcQasXvL-Ly+7W0Xnr-J6xZpqDUF7CW4lTPZczlvs-GSnIHz-28sgZBwKASw0HQCC8goyCgECEhgKFoa+8gwfIAAzGoAAsGaCEIcD0BnJdCxtR7sXQhfFxZdAJ0mSf87yABUix1UgjjZxxv7IM3reLLnEolwgDTKgA1sKMB0btU+mcgEbAB+mqrxvyBj3rEy0ds1993PMVDynIBjy8u9XG9s-z5gi95yva8gJvTg28J4QD3m9Ogh9j7qH-pvAA1MgeWV8aI32QXfAeCBH6k1Tq-SKYCZ5mDni3b+ZRf7QLPkAneuD37gKXvRfAMZcCcCUKIAARL5LkuBrDwl+FAOQLD+gwIcjpFBdBtRCCEbWdBmCgppwziAYk9BOBZyELQkuPcS7rjLmoSuNdkD10bjnUhfpvAAHkjyhSkcnLBz8wq0RAQ1JSj1CTfB4TrXUDikwAHFihFjLFAZx3DoBqFZo7ahdBP5EJLiQ5eZCAFb0oc+PBtFIG4BPjA5A8DEFChQZsAxhCF7t0-F3AuIAi5gDQQ-KxQUX4gKSTRCJC9on51PnEihtSwkcRSWks+F8kGiOyWg7wpijwVMTlUgWODEkdPCQQr+UTVGxMAcAt+083q0MCAwphrD2Hmk4S46AfCBEbyEW9ERWoLISOoNQLsQIzAlzHIIIAA)

**Comment by Andarist** [comment]
This one is tricky and falls back under https://github.com/microsoft/TypeScript/issues/47599 umbrella.

The problem is that inference is performed in 2 passes when context-sensitive functions are involved. The first one replaces such functions with "any function type" and blocks inference from it. The problem is that the signature inferred from the first pass has to pass `getSignatureApplicabilityError` (or well, fail it - as in, it can't result in an applicability error) for the inference to move to the second pass. I verified locally that if we'd move to the second pass this would succeed but that also had some undesired effects on other existing test cases.

So what happens here after this second pass that the third param type gets computed as `PipelineTransform<PipelineTransform<number[], any>, any>` which is basically equivalent to `ReadWriteStream | ((source: ReadWriteStream | AsyncIterable<any>) => AsyncIterable<any>)`. And your function doesn't satisfy this requirement because it can only accept an async iterable (but not a stream). 

The reason why we get this param type is that it's derived from constraints (in absence of legit inference candidates and at this point - as I mentioned - your context-senstivie functions were ignored). The reason why it works when it's inlined is that in that scenario it's also context-sensitive so it's also excluded. So the inference is OK with the signature inferred from the first pass and moves to the second.

**Comment by patrickshipe** [comment]
Wow, thank you for the explanation! What's even more fascinating is that if I tweak the `addOne` function in my example to use generics, everything seems to work:

```ts
  const addOne = async function* <T extends number>(
    source: AsyncIterable<T>,
  ): AsyncGenerator<number, void, any> {
    for await (const chunk of source) {
      yield chunk + 1;
    }
  };
```

**Comment by Andarist** [comment]
Yee, IIRC the generic functions are also skipped by the first pass - although perhaps that's done conditionally.

**Comment by patrickshipe** [comment]
The inference seems weak though, e.g. the output type `T` seemes to be the minimum type governed by the `extends`, not based on what I actually passed in. At least it's a workaround to getting typing to work with the preceding function in the pipeline, since if it returns an incompatible type TS will still catch it.
