### ISSUE TITLE
Incorrectly inferred call signature

### ISSUE THREAD

**Issue by boris-kolar** [microsoft/TypeScript#60388]
### 🔎 Search Terms

call signature, overloaded call

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about call signature

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.0-dev.20241101#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIAUAHgFzICMAlOQEz5FnK03IDMuAvrrmAJ4AHFAGE4AGzEBlYAHMQcMAFcoEADwAVAHzIAvMnXIIxSCAAmAZyIA6GwPKgY0ZAAUqu7Q6cAlZAH5rtuSu7sg+5Oq8gigA6lDoIDLqUbrIohLScgrKahjo2gD0+Yx0bjrabEA

### 💻 Code

```ts
interface Foo {
  (x: 1): 2
  (x: 2): 3
}

type CallSignature<T> = T extends (...p: infer P) => infer R ? (...p: P) => R : T
type WrongType = CallSignature<Foo> // (x: 2) => 3
```

### 🙁 Actual behavior

The inferred type is not compatible with actual type

### 🙂 Expected behavior

The inferred type should (at minimum) be compatible with actual type (ideally `{ (x: 1) => 2; (x: 2) => 3 }`).

**Comment by MartinJohns** [comment]
This is working as intended / a design limitation. See the documentation: [Inferring Within Conditional Types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types)

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the *last* signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

**Comment by jcalz** [comment]
see #26591 and other issues
