### ISSUE TITLE
TSServer needs some way of specifying editor options

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6039]
Currently, the options are hard-coded ([see here](https://github.com/Microsoft/TypeScript/blob/58400ed7716826bbaff22d3c15feba2eeee2cf8c/src/server/session.ts#L623-L630)).

We need some way of letting the client specify their editor options to fix issues like https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/382

**Comment by basarat** [comment]
> We need some way of letting the client specify their editor options to fix issues like

How about using `tsconfig.json` : https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#formatcodeoptions :rose:

At some point I imagined seeing TSServer do this. Must have been mistaken.

**Comment by weswigham** [comment]
:+1: for adding editor options to the tsconfig in the default host.

**Comment by angelozerr** [comment]
It should be really cool too if tsserver could support editorconfig http://editorconfig.org/ which is a lot of used and supported by many IDE.

**Comment by zhengbli** [comment]
On a second thought, I think putting editor options inside tsconfig is not an optimal solution. For example, you would have to have a tsconfig file to set editor options, which might bring side effects if you don't previously have one. In addition, it would overlap with the settings in editors in vscode / editorconfig file, and things get complex if there are conflicts. Also, there would be no way to change the "default" behavior (loose file scenario).

As tsserver already provides APIs for the host to configure editor options [here](https://github.com/Microsoft/TypeScript/blob/dc60e684689e121223c72f3813f0d8949f329145/src/server/session.ts#L1078), I think the support for editorconfig files can be done by VSCode or other hosts. As VSCode already has workspace specific setting files, that solves per-project setting scenario too. The reason why it doesn't work today is we didn't honor the configure options passed in, so as long as we fix that we should be good.

**Comment by zhengbli** [comment]
I think we still need this issue open to track the progress of honoring the editor options passed by the editor, and the issue remains a bug because currently it doesn't work as expected. Reopening.

**Comment by mhegazy** [comment]
@zhengbli we have https://github.com/Microsoft/TypeScript/issues/6923

**Comment by zhengbli** [comment]
@mhegazy makes sense. And it seems that other than the new line character, nothing else is hard-coded. I'll send a PR for that separately. Closing this.

**Comment by basarat** [comment]
> On a second thought, I think putting editor options inside tsconfig is not an optimal solution

Agreed. This time with alm I went with a bit more staggered approach. EditorConfig for the options that it provides : https://basarat.gitbooks.io/alm/content/config/editorconfig.html and then `tsconfig.formatCodeOptions` for the ones specific to TypeScript : https://basarat.gitbooks.io/alm/content/config/tsconfig.html#formatcodeoptions :rose:

**Comment by zhengbli** [comment]
@basarat nice to hear about your solution. Though does that mean if the user wants to change the indent size, he/she needs to have a dedicated editorconfig file?

**Comment by basarat** [comment]
> he/she needs to have a dedicated editorconfig file

Yes. But the good news is that if they edit it they get the same experience for all their team mates that might use some other editor http://editorconfig.org/#download :rose:

**Comment by zhengbli** [comment]
Indeed. With so many different requirement to meet, each solution is a double-edged sword.
