### ISSUE TITLE
"Move to a new file" refactor was recently broken for some import names

### ISSUE THREAD

**Issue by CGNonofr** [microsoft/TypeScript#60408]
### 🔎 Search Terms

refactor, move to new file

### 🕗 Version & Regression Information

- This changed between versions 5.7.0-dev.20241021 and 5.7.0-dev.20241104
- This changed in commit or PR https://github.com/microsoft/TypeScript/pull/60333

### 💻 Code

- test1.ts:
```typescript
import Event from './test2.js';

export function test(test: Event): void {
	console.log(test);
}
```
- test2.ts
```typescript
export default class Event {
}
```

then tries to "move to new file" the test function from test1.ts

### 🙁 Actual behavior

the function is moved to a new file, but not the import so `Event` is not resolved in the new file

### 🙂 Expected behavior

the whole content of the test1.ts file is moved to a new file (with the import)

### Additional information about the issue

It looks like it has something to do with the name, as if it's imported as something else than `Event` there is no issue

**Comment by Andarist** [comment]
Could u share a full repro case in a form of a repository to clone or something?

This test case passes just fine on `main`:
```ts
/// <reference path='fourslash.ts' />

// @Filename: /a.ts
//// export default class Event {}

// @Filename: /b.ts
//// import Event from './a.js';
//// [|export function test(test: Event): void {}|]

verify.noErrors();

verify.moveToNewFile({
    newFileContents: {
        "/b.ts": "",

        "/test.ts":
`import Event from './a';

export function test(test: Event): void { }
`,
    },
});
```

**Comment by Andarist** [comment]
Failing test case:
```ts
/// <reference path='fourslash.ts' />

// @lib: dom

// @Filename: /a.ts
//// export default class Event {}

// @Filename: /b.ts
//// import Event from './a.js';
//// [|export function test(test: Event): void {}|]

verify.noErrors();

verify.moveToNewFile({
    newFileContents: {
        "/b.ts": "",

        "/test.ts":
`import Event from './a';

export function test(test: Event): void { }
`,
    },
});
```
