### ISSUE TITLE
【proposal】Support object keyword，Like Kotlin's object keyword，Solve the problem that static methods cannot be overridden after inheritance

### ISSUE THREAD

**Issue by alamhubb** [microsoft/TypeScript#60418]
### 🔍 Search Terms

`object keyword`，`extend object`，`Overriding static methods`，`Static methods cannot be overridden by subclasses`,

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Supports the object keyword and object extends. object can extends object , object can extends class, and class can extends object . 

### 📃 Motivating Example

Hello, thank you for watching. If there are any deficiencies in the following content, please forgive me. I am deeply sorry.

This syntax sugar will be good news for static method lovers because it implements static method overriding and inheritance in another way.

And in the case of singleton objects, it also avoids the lengthy class syntax and merges the class declaration with the object creation.

Compared with Object.assign({}, parent, child), the object keyword can have better type hints and support class inheritance. This should be just syntax sugar for class syntax.

I would like to discuss the syntax of the inherited object keyword.

### 💻 Use Cases

1. What do you want to use this for?.

The object keyword syntax can replace and solve the problem that static classes cannot be overridden, improve development efficiency, make the syntax more concise, and is suitable for scenarios with singleton objects.

Before this keyword, our code needed to be written like this

```
class Parent {
    name :string
    echoMyName() {
        console.log(`my name is:${this.name}`)
    }
}

class Child extends Parent{
    age : number
    echoMyInfo(){
        super.echoMyName()
        console.log(`age:${this.age}`)
    }
}

const parent = new Parent()
parent.name = 'parent'

const child = new Child()
child.name = 'child'
child.age = 20

parent.echoMyName() //my name is:parent
child.echoMyInfo() //my name is:child  age:20
```

3. What shortcomings exist with current approaches?

```
object Parent {
    name :string = 'parent'
    echoMyName(){
        console.log(`my name is:${this.name}`)
    }
}

object Child extends Parent{
    age : number = 20
    echoMyInfo(){
        super.echoMyName()
        console.log(`age:${this.age}`)
    }
}

Parent.echoMyName()
Child.echoMyInfo()
```

### Inspiration

The following is an explanation of the inspiration for this proposal.

I often use static methods in program development. Compared with ordinary functions, static methods have better static prompts and module distinction functions.

But I encountered a problem, that is, static methods cannot be inherited and overridden, which is a unified design specification in the language I am familiar with.

But this did bring some inconveniences during the development process. There is a website called Zhihu in China

Why don't static methods be used in java?
Why can't static methods be overridden?
What will happen if the functions of class and object keywords in kotlin are combined?

Discussion, this topic has caused widespread discussion. Some people think that using static syntax is not enough for OOP, while others think that this method does bring enough efficiency improvement to development and improves the development experience.

Many people have encountered the same problem as me, that is, when using static development, abstract parent classes are needed, and when methods are reused, static cannot be overridden, which reduces development efficiency.

However, due to the special logic of static, it seems inappropriate to support the overriding of static methods.

So can a new keyword object be supported to achieve this function?

Objects have the functions of classes, can be integrated by classes, can be inherited by objects, and can also be used directly.

Regarding OOP, there are many practical applications in Java and Kotlin, so please allow me to use Java as an example to illustrate. In Java Web development, the Spring framework is an indispensable framework. The object instances managed by Spring are all singletons, that is, a class will only have one instance, which is the case in most cases. However, in this case, we need to declare a class first, and then instantiate this class to get the object. This process is a bit cumbersome. We can completely combine these two steps into one step, that is, declare an object with a type hint, and then use it immediately.

In kotlin, there is the object keyword syntax. The following code can be run in kotlin

```
object ParentObject {
    var name = "ParentObject"

    fun echoName() = "name:${name}"
}

// Use
fun main() {
    println(ParentObject.echoName()) // Output: ParentObject
}
```

And kotlin's object supports inheritance from class, but not from object, which still can't solve the problem I encountered at the beginning

So I want to ask if this function can be supported in js/ts

Looking forward to your reply, thank you very much

**Comment by alamhubb** [comment]
> You checked this
> 
> > * [x]  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
> 
> but clearly it is a runtime feature, which you acknowledge explicitly by describing the behavior as being syntax sugar for `class` syntax.
> 
> If you want runtime behavior, then TypeScript isn't the right place for it to originate. You'd need to propose this to be a JavaScript feature and therefore follow the [TC39 process](https://tc39.es/process-document/). Once a feature makes it to stage 3 of that process, TypeScript will implement it. Of course there's no guarantee that your proposed feature would make it to stage 3, but either so, it won't happen here directly and you should probably close this issue.
> 
> (note well, I am not a member of the TS team; I'm just a community member. So if you want to ignore me and wait for a TS team member to triage it, that's up to you. But I do recommend you save them the trouble.)

Thank you for your reminder. Sorry, I haven't thought this issue through. I'll think about it. I'll close this issue first. Thank you for your reminder.

**Comment by alamhubb** [comment]
> You checked this
> 
> > * [x]  This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
> 
> but clearly it is a runtime feature, which you acknowledge explicitly by describing the behavior as being syntax sugar for `class` syntax.
> 
> If you want runtime behavior, then TypeScript isn't the right place for it to originate. You'd need to propose this to be a JavaScript feature and therefore follow the [TC39 process](https://tc39.es/process-document/). Once a feature makes it to stage 3 of that process, TypeScript will implement it. Of course there's no guarantee that your proposed feature would make it to stage 3, but either so, it won't happen here directly and you should probably close this issue.
> 
> (note well, I am not a member of the TS team; I'm just a community member. So if you want to ignore me and wait for a TS team member to triage it, that's up to you. But I do recommend you save them the trouble.)

Hello, I want to bother you, I don't know if you have time, if you don't, please ignore my comment, sorry for bothering you

I understand that this is a compile-time syntactic sugar, not a runtime syntactic sugar, do you agree with my understanding, this syntactic sugar can compile the object keyword code into the equivalent class code at compile time

So do you suggest that I can continue with this proposal?

**Comment by jcalz** [comment]
I understood that it is a "compile-time syntactic sugar" when I wrote my first comment. If you want non-JavaScript code (e.g., `object Foo {}`) to compile to JavaScript code (e.g., `const Foo = new (class {})()`) code, then it's a runtime feature and will be declined.

**Comment by alamhubb** [comment]
> I understood that it is a "compile-time syntactic sugar" when I wrote my first comment. If you want non-JavaScript code (e.g., `object Foo {}`) to compile to JavaScript code (e.g., `const Foo = new (class {})()`) code, then it's a runtime feature and will be declined.

Thank you for your answer. I understand that this problem is caused by my misunderstanding of "ts does not modify runtime code". Thank you for your help and I wish you a happy life.
