### ISSUE TITLE
Refactor to add missing switch cases for enum

### ISSUE THREAD

**Issue by golopot** [microsoft/TypeScript#60429]
### 🔍 Search Terms

"switch", "enum", "refactor", "code action"

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Provide a refactor to autocomplete the missing switch cases for a enum value.

### 📃 Motivating Example

```typescript
enum E  {
    a = 1,
    b = 2,
    c = 3
}

function f(e: E) {
    switch (e) {
        // provide refactor here to add missing case branches 
    }
}
```

### 💻 Use Cases

1. What do you want to use this for? Better DX
2. What shortcomings exist with current approaches? manual input
3. What workarounds are you using in the meantime? manual input

**Comment by RyanCavanaugh** [comment]
It's already there in the `case` completion:
![Image](https://github.com/user-attachments/assets/7a3c9c28-e0bd-43e2-bbff-cd2e4a100799)

**Comment by golopot** [comment]
Thanks, I didn't noticed this completion exists. Maybe it is too hard for users to discover? I think it would help to add this completion at the "enum dot" position:
![Image](https://github.com/user-attachments/assets/515571db-8265-4a56-b6c9-8846261a9499)
