### ISSUE TITLE
error TS2323: Cannot redeclare exported variable

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6043]
A following code was compiled with no error on TS1.7 but latest nightly build is not. Is this breaking changes?

```ts
declare module "a" {
  export default 0
  export const a;
  export type a = typeof a;
}
```

```
$ node_modules/.bin/tsc --version
Version 1.8.0-dev.20151210
$ node_modules/.bin/tsc a.d.ts
a.d.ts(3,16): error TS2323: Cannot redeclare exported variable 'a'.
a.d.ts(4,3): error TS2323: Cannot redeclare exported variable 'a'.
```

**Comment by vladima** [comment]
meanings of `const a` and `type a` don' collide so it should be allowed. @weswigham can you have a look?

**Comment by weswigham** [comment]
I need to add an exception to the duplicated exported identifiers check for `type` declarations.
