### ISSUE TITLE
Counterintuitive behaviour when working with generics and type maps

### ISSUE THREAD

**Issue by ale18V** [microsoft/TypeScript#60435]
### 🔎 Search Terms

- generics
- mapping
- type map
- conditional

### 🕗 Version & Regression Information

Tested on typescript versions  5.3.2 to 5.6.3 . As far as I know this is not a regression.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241106#code/KYDwDg9gTgLgBDAnmYcAiwYEMCWAbAZwFksw4BeOAbwCg44AiAYyygYC5qA7AVwFsA8gDMA6gAtgwQp158ARsCgBfOozB4sXYB25Y+wTgRhQcXAOYr6DY7i46qfLCADKKYABMZ-BcpoqkKHAAolzGiABCWO4APAAqcKAwwFzuBHAA1sCIEELomLiEJGSUmdm5GNj4xKQAfBTUqgEGcLF+cABkeZWFpADasQC6NDRMEFxGCMATlAAUWJwhYZHuAJQUdbT0OEJzAHRNFOSUzKwMa5v0cFi7ssLikoRwAPQAVMEASu8C73Cql5cABSgEBQsEQcAA5LdRBIpAQIXB3BApnAuBB4KAcBMxghkKgIYsoIhoqUcl0CtUwDUIbs-v96UCQYokJDofc4QikSi0RiQFj4DiDhCqLiUJxSeV8lUigBuOBKDrUVF6ZpGEzmOWWS4vJ6qFQqGgHQmIADiEAgMXiiWSqQyWTJFQpRXqEvJ0tq9StICSKTSrsd7rIAH44DMLvQmpxWgrOgGemB+gM1jJgAA3RTDUbjeBJIwAJnqcwWoSJZota3IGzp2z2ByOxxYbHOdP+1zZsMeTyecBNAgEaDp+qAA

### 💻 Code

```ts
export type DetailsMap = {
  "car": {numOfWheels: number}
  "plane": {name: string}
  "train": {maxSpeed: number}
}
type EntryBad<T extends keyof DetailsMap = keyof DetailsMap> = {
  type: T
} & DetailsMap[T]

const test = (a: EntryBad) => {
  if(a.type === "car") {
    a.numOfWheels /* ERROR 
        Property 'numOfWheels' does not exist on type 'Entry<keyof DetailsMap>'.
            Property 'numOfWheels' does not exist on type '{ type: keyof DetailsMap; } & { name: string; }
    */
  }
}

type EntryGood<T extends keyof DetailsMap = keyof DetailsMap> = T extends keyof DetailsMap ? ({
    type: T
} & DetailsMap[T]) : never

const test2 = (a: EntryGood) => {
    if(a.type === "car") {
        a.numOfWheels // GOOD
    }
}
```

### 🙁 Actual behavior

Typescript doesn't narrow the attributes of the object of type `EntryBad` after successfully checking for its `type` field.
However, by adding a redundant check on the type of the generic, which is known to be always true, typescript successfully narrows. 

### 🙂 Expected behavior

I believe what is expected is that `EntryBad` should be narrowed correctly after checking `type`

**Comment by MartinJohns** [comment]
`T` can be a union type. With `EntryGood` you have distributive types, which is good in this case. In the bad version not.

**Comment by ale18V** [comment]
So the reason `EntryGood` works is because it is spread to an union type when evaluating the conditional check? This still seems counterintuitive to me: there is a 1:1 mapping between `EntryBad.type` and `DetailsMap` so I see no reason why checking the type should not provide narrowing

**Comment by RyanCavanaugh** [comment]
This behavior follows from the output of `EntryBad`. A legal call is
```ts
let a: EntryBad = {
  type: "car",
  name: "foo"
}
test(a);
```

**Comment by ale18V** [comment]
That is indeed a legal call. However inside the `test` function there is no way to type narrow the parameter, and you must resort to casting it manually if you want type assistance. This seems strange to me because the type of `a` can be inferred:
```ts
const test = (a: EntryBad) => {
  if(a.type === "car") {
    console.log((a as EntryBad<"car">).numOfWheels)
    // Should infer that `a` is of type EntryBad<"car"> if a.type === "car" (?)
  }
}
```

However feel free to close this issue if everything is working as expected. The problem may be just me misunderstanding how typescript works.

**Comment by MartinJohns** [comment]
> // Should infer that `a` is of type EntryBad<"car"> if a.type === "car" (?)

But that's exactly wrong in the case of unions. The type could be `"car" | "plane"`. And since you not the type argument and it defaults to `keyof DetailsMap` you are dealing with a union type. To clarify: `EntryBad` is the same as `EntryBad<"car" | "plane" | "train">`, which results in a single object type where the `type` property is typed `"car" | "plane" | "train"`. You don't have a union of object types with each distinct type.

**Comment by ale18V** [comment]
Ah, I see. Even if `a.type === "car"` the type of `a` can still be `EntryBad<"car" | "plane">` or `EntryBad<"car" | "train">` or whatever union. If that's the case, I wonder why typescript doesn't just infer `EntryBad<"car">` i.e. the smallest supertype, but that's a different question. Thanks for providing a clear explanation, I'll close the issue.
