### ISSUE TITLE
Missing formal rule for homomorphic nature of mapped types.

### ISSUE THREAD

**Issue by hearnden** [microsoft/TypeScript#60445]
### 🔎 Search Terms

"homomorphic"
"mapped type" and "intersection"

### 🕗 Version & Regression Information

This is the behavior in every version I tried, and I reviewed the FAQ for entries about "homomorphic" and "mapped types".

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.3#code/PTAEGUHsFsFNQGYFcB2BjALpATqAYgHSigAqAFvAG4CG2AltevACaSwDOKA5BqNNRgyxsBAFAYAngAd4eADwkAfKAC8oABQBKVcpIBuUaJCgAgn2pSZzUJJk2yA0BakAbOh3xjb8ALILlagDeoADaANKgdCigANawEpAIpAC6AFz4CuHJygC+BkZgfiSgAGSgAKrKdOyIOPwuLhJO7Ox0AOYo1ABGLvBYoEXKZX6VYsjoGHSQ0XTMAIwKADQViuqQ6UWlK5ob-lsjyoGixNiwGEjY0ZAGOYbGBA+gXUi8g-tylZE1KJC8CHXUBpNagtdqdHp9SADBRbUaicaYKYzZgAJiWKzWuyU70qO2hxTKnyOJzOFyuemIxhI0ngXDeww+ii4X1AP14INaHW6vRsUO8oDpMMJTII6hRAGYUSjNKJbkA

### 💻 Code

```ts
// Some functor F.  The variance doesn't matter.
type F<T> = () => T;

// A mapped type that applies F.
type M<T> = { [K in keyof T]: F<T[K]> };

// M<T & U> is formally assignable to M<T> & M<U>.
function id1<T, U>(o: M<T & U>): M<T> & M<U> {
  return o;
}

// ... but M<T> & M<U> is not formally assignable to M<T & U>.
function id2<T, U>(o: M<T> & M<U>): M<T & U> {
  return o;  // Type 'M<T> & M<U>' is not assignable to type 'M<T & U>'.(2322)
}
```

### 🙁 Actual behavior

Type error on assigning `M<T> & M<U>` to `M<T & U>`.

### 🙂 Expected behavior

No error when assigning `M<T> & M<U>` to `M<T & U>`.

### Additional information about the issue

If I understand correctly, mapped types are meant to be homomorphic, by definition.
That means a mapped type should distribute over `&`, in both directions.
```ts
M<T & U>  ==  M<T> & M<U>
```

**Comment by jcalz** [comment]
What happens when `T` and `U` share keys with differing properties? Let's say that `T` is `{a: X}` and `U` is `{a: Y}`. Then you're suggesting that `{a: F<X & Y>}` should be mutually assignable with `{a: F<X>} & {a: F<Y>}`, and presumably then that `F<X & Y>` should be mutually assignable with `F<X> & F<Y>`.  That means variance definitely does matter. If `F` is covariant then one of those two directions works for sure, and the other direction is... uh... well, `(() => X) & (() => Y)` is an overload and you're comparing it to `() => (X & Y)` and... this is definitely more complicated than your wording above implies.

**Comment by RyanCavanaugh** [comment]
This is just not true. There are instantiations of `M` where the output is `never` even though the input is not
```ts
type AX = { a: "x" };
type AY = { a: "y" };

declare const ab: M<AX> & M<AY>;
ab.a(); // Overloaded function
const output = id2<AX, AY>(ab);
// output: never
```

**Comment by hearnden** [comment]
> What happens when T and U share keys with differing properties?

That's the easy case:
```ts
type Out<T> = () => T;
type In<T> = (x: T) => void;

type MOut<T> = { [K in keyof T]: Out<T[K]> };
type MIn<T> = { [K in keyof T]: In<T[K]> };

type Q1 = MOut<{ p: string }> & MOut<{ q: number }> extends MOut<{ p: string } & { q: number }> ? 1: 0;
// ^?
type Q2 = MOut<{ p: string } & { q: number }> extends MOut<{ p: string }> & MOut<{ q: number }> ? 1: 0;
// ^?
type Q3 = MIn<{ p: string }> & MIn<{ q: number }> extends MIn<{ p: string } & { q: number }> ? 1: 0;
type Q4 = MIn<{ p: string } & { q: number }> extends MIn<{ p: string }> & MIn<{ q: number }> ? 1: 0;
```

The trouble only happens when T and U have intersecting properties, where `&` interpreted as an overload operator.
That already introduces a source of unsoundness.


> There are instantiations of M where the output is never even though the input is not


`&` already produces cases of assignability to `never`.

```ts
const ax = { a: "x" };
const a1 = { a: 1 };
const n: never = Object.assign({}, ax, a1).a;
```
