### ISSUE TITLE
Spead args pick bugs

### ISSUE THREAD

**Issue by VictorTrumpel** [microsoft/TypeScript#60452]
### 🔎 Search Terms

```typescript
type CustomAwait<T> = T extends null | undefined
    ? never
    : T extends { then: (...args: infer Args) => any }
        ? Args[0] extends ((value: infer V) => unknown)
            ? V
            : never
        : never

type AwaitResult = CustomAwait<Promise<string>> // never ??

const res: AwaitResult = 'why never?'
```

### 🕗 Version & Regression Information

v 5.6.3

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ssl=12&ssc=1&pln=1&pc=1#code/C4TwDgpgBAwgrgZ2AewLYEEDuBDAlsAHgBUA+KAXiiKggA9gIA7AEwSkbgBtOoAfKOCwgAzXIwjMAUFBlQA-OwgA3CACdpsgFxUa9JqygBvKMAAWTbQAoAdLeyqA5gm1jhaqOkcIAlBTLZGECgAXw1ZWQVPJwBtAAYAXV0GFjZLSyVsTjgIF0Y3VSgANV9yMkEAa0ZkTEZvMPCGhUL6hq1FFXVWmW1xDslJUEgPHHwAJQgELmAKWEQUDBHCAAVVNFwECAIkVTEHEjIAegP29zk5foBjZEYkKFUJ7Sw8YHHJzmnKAHJMUyDetTkn36kiAA

### 💻 Code

```ts
type CustomAwait<T> = T extends null | undefined
    ? never
    : T extends { then: (...args: infer Args) => any }
        ? Args[0] extends ((value: infer V) => unknown)
            ? V
            : never
        : never

type AwaitResult = CustomAwait<Promise<string>> // never ??

const res: AwaitResult = 'why never?'
```

### 🙁 Actual behavior

AwaitResult become never

### 🙂 Expected behavior

AwaitResult become string

**Comment by RyanCavanaugh** [comment]
`Args[0]` includes `undefined`, so it doesn't unconditionally `extend` the RHS. You need
```ts
type CustomAwait<T> = T extends null | undefined
    ? never
    : T extends { then: (...args: infer Args) => any }
        ? NonNullable<Args[0]> extends ((value: infer V) => unknown)
            ? V
            : Args
        : never

type AwaitResult = CustomAwait<Promise<string>> // string
```
