### ISSUE TITLE
Type narrrowing on Subclassed Generic.

### ISSUE THREAD

**Issue by jasuperior** [microsoft/TypeScript#60455]
### 🔍 Search Terms

"Type narrowing on classes", "class generics type inference", "union type generics"

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

When extending a class that has a generic type, any methods defined on the parent class which utilize the generic are not narrowed by the sub class correctly. 

For instance, if I have a type `T` which is a union of `number` and I create a subclass which passes the type `1|2|3|4|5` to `T`, T still contains the type `number` although it would make more sense that the type `T` be the more specific type. 

### 📃 Motivating Example

```ts
class A<T extends string> {
    method( props: { [Key in T]?: number }) { //noop }
}
class B<T extends "a"|"b"|"c"> extends A<T> {
   newMethod() {
       return this.method({ c: 3}); // error: Object literal may only specify known properties, and 'c' does not exist in type '{ [Key in T]?: number | undefined; }'
   }
}

// `T` on `method` will always be `string` even though `B` narrows it in the definition.
```

Currently, the only way to fix this is to reimplement the method on class `B`

```ts
//...
class B<T extends "a"|"b"|"c"> extends A<T> {
  method( props: { [Key in T]?: number }) { 
      return super.method(props)
   } 
}
//...
```

### 💻 Use Cases

1. What do you want to use this for?
General purpose. In JS, when creating an instance of a sub class, the value of `this` in methods defined on the super class will be the same type as the sub class instance. It seems reasonable that the types should be inherited (when used by the sub class). 

2. What shortcomings exist with current approaches?
In order to create a generalized method that all subclasses extend from, you have to reimplement the method for every subclass, even if the implementation is the same. This is only to gain the type information. 
 
3. What workarounds are you using in the meantime?
doing as stated above, simply reimplementing the method for each subclass.

**Comment by RyanCavanaugh** [comment]
This is correct and the same behavior you'd see from outside the class, e.g.:
```ts
const m = new B<"a">();
// Not a legal call
m.method({ c: 3 });
```

It seems like you mean
```ts
class B<T extends "a"|"b"|"c"> extends A<"a" | "b" | "c"> {
   newMethod() {
       return this.method({ c: 3 }); // error: Object literal may only specify known properties, and 'c' does not exist in type '{ [Key in T]?: number | undefined; }'
   }
}
```
which is a different thing

**Comment by jasuperior** [comment]
When you write it like this, I'm realizing my mistake. This was all just a complete oversight on my part.  I'll close the issue.
