### ISSUE TITLE
No error raised by incorrectly casting built-in types

### ISSUE THREAD

**Issue by olfek** [microsoft/TypeScript#60468]
### 🔎 Search Terms

No error raised by incorrectly casting built-in types

### 🕗 Version & Regression Information

n/a

### ⏯ Playground Link

https://www.typescriptlang.org/play/?jsx=0&ts=5.5.4#code/FAej4sAICEEEAiVIpMYAzArgOwMYAuAlgPY5Tb7FkCMAFCQA7U4DOAXFACoCmAHgQQ88JACY8ATgHlmpNgEooAb2BQ1UEWwJQAtgE8AagEMJRIwCMANjygBeKAB5WBUzgDmAPiYtWAbmQgUAByJFCSEiQSUBJGRKw8olDmelBE+JESwtp4Rs5pbgB0wAC+6JSEchS4FWQATAyyZBzc-ILCYpIyPooq6hpN2vrGphbWdlDecqxQuVDOrm7+0CFhEhFRMXEJSSlpImtZGrnE7kWlmNUsVVRyAMwNPpy8AkIi4tKNCsqq6prOuoYTGYrDZ7JMmnMjMRWBgiDxpvN8r4SuhUJAoABxKRSJBoiDoNIESQYIx4GwAWT0AEkcESJCSyd8+owIoxOIj3CiLjcyNcajgACwPKacSk0ukMng9H5qP6DQEjEHjJwufJeT5+LnlK7auQAVmFTVF1NpxNJUqZvwGAOGwLGYI1MwRqvcyPOut5HpwADZDWxjeKzWTpX05TagaNQRNHawoXFYfC5i7Fly8eAoABRIK4tMgIA

### 💻 Code

n/a

### 🙁 Actual behavior

n/a

### 🙂 Expected behavior

n/a

**Comment by mkantor** [comment]
`TextDecoderOptions` is a [weak type](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#weak-type-detection) (all of its properties are optional). [If you adjust your test interface to also be weak you'll see the same behavior.](https://www.typescriptlang.org/play/?jsx=0&ts=5.5.4#code/GYVwdgxgLglg9mABKSsEEYAUcAOawDOAXIgCoCmAHlACLkRwAm5ATgPJ7yECUiA3gChEwxA0JREAWwCeANQCGLGPIBGAG3KIAvIgA8BKErABzAHy58BANwCAvgIEpoXZOGcIATNk4JiZKrT0TKwclryCIqK+EjIKSqoa2ogWXASI8mkGRsY29o5u+K6oXADM3pYkFNR0DMzsPjz8QiJiBlJyisrqmjopvogE8rAEwDDkmYYwJrkODlNQrMDyEJoAstIAkmALLEsrTZE4LLgA-CRZU8Z2Dk6Ft1wALOWpJOtbO3vk4c3CrTEd8W6SX0kxM5ga1mu+WKCCK7jAAFZnr5Xpttotll8Di1ou04l1Er0IekJtkZtD4XD8AA2ZGEVHvDErb6RP54zoJHrJYmDYajcYDUE5a5AA
