### ISSUE TITLE
TypeScript API `typescript.sys.fileExists` callback triggers @typescript-eslint/unbound-method error

### ISSUE THREAD

**Issue by valler** [microsoft/TypeScript#60477]
### 🔎 Search Terms

"typescript-eslint error", "typescript-eslint error unbound-method"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "FAQs-for-API-Consumers" and the FAQ

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBDAznAZlCI4CIYE8wCmiAxlMGDFgNwBQNxEAdovAIZwC8CiAdCsIwAmAYSb8A5gDFgAGwIAKLDwD0WADTceiXL35yAogA9gLRBpwkxwcTwBWiJlgCUtekxZwARp038hoxglpOXkaOGwVdTC4ZWU4IhkBGABaQRNWTzlkxgJDFMScuAABPEISMgpkhKTlAFdGTwh6wWSQAhgACwhBaKQtHT5ZAiMTJDVoiwZA6zsHRiiXOimPYh8+vxErKSHFSI15RCdOAD5NbV0hkdMDp3MkKYlZx0WgA

### 💻 Code

```ts
import ts from "typescript";

const a = ts.findConfigFile("./", ts.sys.fileExists, "tsconfig.json");

const b = ts.findConfigFile(
  "./",
  // eslint-disable-next-line @typescript-eslint/unbound-method
  ts.sys.fileExists,
  "tsconfig.json",
);

const c = ts.findConfigFile("./", (s) => ts.sys.fileExists(s), "tsconfig.json");

```

### 🙁 Actual behavior

Given the code example, a combination of the TypeScript API and @typescript-eslint/unbound-method forces the API consumer into writing code in form of (b) or (c).

While (b) maybe considered ugly, (c) requires runtime code different from (a).

Both (b) and (c) are arguably non-solutions, because API implementations allowing for (a) are certainly possible, therefore eliminating the need for workarounds by effectively all users on all call sites, respectively API consumption sites.

### 🙂 Expected behavior

No conflict with linters, which supposedly means:

- API implementors use arrow functions for callbacks, so the user does not have to, or
- callback receiving APIs switch to objects and call their methods internally, again to save the user from having to wrap the callbacks provided by the API

### Additional information about the issue

I originally opened this as a typescript-eslint bug https://github.com/typescript-eslint/typescript-eslint/issues/10318 about inference on method binding.

Over there the stance is that most devs would disagree with (a), therefor also not opt for (b) and advocate for (c) leaving the safe implementation method/callback binding to the user. I strongly disagree. I want a safe API and/or tooling which prevents me from writing buggy code or unnecessary overhead.

The linter might be right in terms of complexity and compilation time (or linting performance) when it comes to checking for `this`. Which leads me to believe that the TS API authors should take a look at this, either to fix it, or to give usage recommendations.

**Comment by RyanCavanaugh** [comment]
This isn't part of our recommended configuration. It's impossible to make an API that is resistant to every lint rule a person could possibly turn on; if a lint rule is giving you false positives, turn it off or use a suppression.

**Comment by valler** [comment]
@RyanCavanaugh thanks. I guess your answer also implies that (a) would be the intended usage of the API, not (c). So even TS devs recommend unbinding to pass callbacks? Ok, turning it off then it is.
