### ISSUE TITLE
tsc does not compiling 'with' statement ie ```import... from file.json with {type:'json'}```

### ISSUE THREAD

**Issue by chidam02** [microsoft/TypeScript#60499]
### 🔎 Search Terms

with assertion statement

### 🕗 Version & Regression Information

Typescript version : 4.7

### 💻 Code

```ts
import schedulePayloadSchema from "../validators/jobScheduleSchema.json" with { type: "json" };
```

### 🙁 Actual behavior

after compiling with ```tsc filename.ts``` 

output: 
```js
import schedulePayloadSchema from "../validators/jobScheduleSchema.json";
with ({ type: "json" })
    ;
```

### 🙂 Expected behavior

expected: 
```js
import schedulePayloadSchema from "../validators/jobScheduleSchema.json" with { type: "json" } ;
```

### Additional information about the issue

typescript compiler does not compiling import assertion statement written with 'with' statement but its working properly with 'assert' keyword which is deprecated in node latest version 22

**Comment by MartinJohns** [comment]
> Typescript version : 4.7

This version is over two years old.

**Comment by chidam02** [comment]
is there any fix for importing json file in typescript which can be compiled to run in node js

**Comment by chidam02** [comment]
I installed typescript v 5.6.3 its working now.
