### ISSUE TITLE
Aliasing affects assignability of indexed mapped types

### ISSUE THREAD

**Issue by bgenia** [microsoft/TypeScript#60503]
### 🔎 Search Terms

type alias, interface, assignability, indexed access type, mapped type

### 🕗 Version & Regression Information

- The core issue has existed in every version I tried since 3.3.
- Before 4.2, indirect type aliases worked while indirect interfaces did not.
- In 4.2, both produced errors.
- Since 4.3, indirect type aliases give errors, but indirect interfaces do not.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.6.3#code/C4TwDgpgBAyg9gVwE4GMIGkIigXigZ2CQEsA7AcwChRIoAVAQyXImE2zwCJgJDPLq4aADUGAGwTQ8CUgGtScAO6kBNaAFkQAJQgo4SACYAedFAgAPHqQP4osrHABmUBqRAA+XFADeUANoAClBkUOgAugBcUKIS0AC+grSaAPLAABYQSDp6hiZmlhDWtvYgTi5unni+gcGkoZHR4pJQCZQGumJM0HqkhASIqBAA+uLEDPgQBlGa2frG8Mho7O5tHV1QPX34A2gjYmMTBkNw6ZnTIKkZWbpzRguDy6sonUjdcL3A-YvDALYMYJApj5-EEQvcllgGjFmgl2s91ptPttvkMyO1zJMotUAlFwRhIVFofEBGQeEhHAw0FAAJLWYivFDAWlkilUixWGxQGY3XKMZisZY+BJqGl0hnAACC+3GXm5OWMfJYbCwK0opMyrOgtIM9N0TNILMpEEumXyHNsKVO13lRkVApVQsSWrFeqlBxNSFlFyts15TCVjyeL2gYlYUGA-tYewOkyGOvF519Csjyo8QfWoc+Ef5wGj41j8b1xyt5w9SdtKcecODUEz4ZTecOqJdjMbUW1usZbvG6detbD2aVjdjaM7udG42LV3bLcl0vwHt7IYHDYnTdH4ubhrQM8LjOZGqNS-7WdX85Hs63h92J2nor3+u3xqtx7rg6jfwBmOBNRCdtTUJNMS1YZiuOZDPsZLiFi4a8MAhJAS0qhnjGRwPl4yKDMOBhQAA9LhUDJOg1AofmaFjhhOzDGusa3pkJHgTR5HipRKKfoCDFDkxcYUXgmG7GiFiTMhjHnsxRZ0Z6fFUdhnFRtxD5Tqa0kotxkl4QRRFyeOYk8Zu6kqVh7HCe+OmoXpElWqxWGCRiBgiVxukbkWa7WbsTHadhzaKa5hnubpkmedxzmtr5XxGf8HGmV5IVmTKfnDLZwlBU5l5rkpUnhf5qEpeZsWNhlbnUQFL7RcFaXzoVCVDMZ9llalPmVQZWWJdYQn2blZHeWOV7kkaRXYRphHEfVeWXuqfVUtVamlaR67jQa15SC1NWRSZc0XopE2agNSUdaNXX5dtRpVStHkHfNW2LZNwzNfxxXmep+HDZ1l09cdN5WdVtWvZt73XZqp33d57UOR+a04dNYmebVA0zVcMMQwNP3RbD1V7WDuaQZk4hw9D0XY0guNQ49s3gYTxMrSjDYU2Iu1tXZlBAA

### 💻 Code

Simple example:
```ts
type F<T> = T extends Record<"test", unknown> ? true : false

type A = Record<string, unknown>
type t1 = F<A>
//   ^? type t1 = false

type t2 = F<Record<string, unknown>>
//   ^? type t2 = true
```

Assignability testing:
```ts
type SourceKey = string
type TargetKey = "test"

type Value = unknown

type MyRecord<K extends keyof any> = { [P in K]: Value }
type MyOtherRecord<K extends keyof any> = { [P in K]: Value }

declare const source_aliased: MyRecord<SourceKey>
declare const source_aliased_other: MyOtherRecord<SourceKey>
declare const source_mapped: { [P in SourceKey]: Value }
declare const source_indexed: { [P: SourceKey]: Value }

interface IndirectInterface extends MyRecord<TargetKey> {}
type IndirectAlias = MyRecord<TargetKey>

interface IndirectInterfaceOther extends MyOtherRecord<TargetKey> {}
type IndirectAliasOther = MyOtherRecord<TargetKey>

declare let target_aliased_direct: MyRecord<TargetKey>
declare let target_aliased_direct_other: MyOtherRecord<TargetKey>
declare let target_aliased_indirect_alias: IndirectAlias
declare let target_aliased_indirect_alias_other: IndirectAliasOther
declare let target_aliased_indirect_interface: IndirectInterface
declare let target_aliased_indirect_interface_other: IndirectInterfaceOther
declare let target_mapped: { [P in TargetKey]: Value }
declare let target_literal: { test: Value }

target_aliased_direct = source_aliased // OK
target_aliased_direct = source_aliased_other
target_aliased_direct = source_mapped
target_aliased_direct = source_indexed

target_aliased_direct_other = source_aliased
target_aliased_direct_other = source_aliased_other // OK
target_aliased_direct_other = source_mapped
target_aliased_direct_other = source_indexed

target_aliased_indirect_alias = source_aliased
target_aliased_indirect_alias = source_aliased_other
target_aliased_indirect_alias = source_mapped
target_aliased_indirect_alias = source_indexed

target_aliased_indirect_alias_other = source_aliased
target_aliased_indirect_alias_other = source_aliased_other
target_aliased_indirect_alias_other = source_mapped
target_aliased_indirect_alias_other = source_indexed

target_aliased_indirect_interface = source_aliased // OK
target_aliased_indirect_interface = source_aliased_other
target_aliased_indirect_interface = source_mapped
target_aliased_indirect_interface = source_indexed

target_aliased_indirect_interface_other = source_aliased
target_aliased_indirect_interface_other = source_aliased_other // OK
target_aliased_indirect_interface_other = source_mapped
target_aliased_indirect_interface_other = source_indexed

target_mapped = source_aliased
target_mapped = source_aliased_other
target_mapped = source_mapped
target_mapped = source_indexed

target_literal = source_aliased
target_literal = source_aliased_other
target_literal = source_mapped
target_literal = source_indexed
```

### 🙁 Actual behavior

It seems that an indexed mapped type is only assignable to an object if each is either a direct instantiation of the same type alias or an interface extending from such an instantiation.

### 🙂 Expected behavior

I don't expect aliasing to affect assignability, nor do I expect such differences between type aliases and interfaces.

**Comment by MartinJohns** [comment]
https://github.com/microsoft/TypeScript/issues/43374#issuecomment-807109391

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/wiki/FAQ#structural-vs-instantiation-based-inference

This is one of the few cases where it matters *and* you're not doing anything "wrong" per se. Depending on interpretation, the correct result is either.
