### ISSUE TITLE
Regression in DTS generation between TypeScript 5.6 and 5.7

### ISSUE THREAD

**Issue by crisbeto** [microsoft/TypeScript#60506]
### 🔎 Search Terms

.d.ts generation, TypeScript 5.7

### 🕗 Version & Regression Information

- This changed between versions 5.6.3 and 5.7.1-rc

### ⏯ Playground Link

**Note: look at the ".D.TS" tab in the playground**

https://www.typescriptlang.org/play/?ts=5.7.1-rc#code/KYDwDg9gTgLgBAYwDYEMDOa4DFoFsDCEAdjFBEgDwAqAfHAN4BQccAbikgK7ACEAXHCoBuRgF9GoSLESoM2PAHEynMNTpMWCYqXJp+gkeMbJ0mHFFwAhTgEskAE2BQGzOAHNlqqnFAxgRe0x6URoACldNbTIkNAEqABpXAEoBc1wlCBUKegBtAGk4GyI4AGtgAE8IADNBAF1UvEISaOp82poQlxYWKGAYTihiok4kJB4RFnEjLSI0eCqAIzgAXjgiYAB3eQtrO0coUKSRRgB6E7gAOnsLmExe-sG4GHKwYELMIq0oXoR4IrgAKwXADsFwAjABaKAIOCZGBgTgwPinc4sNIZLL0ewoGAoARzKBFNw5WpwAA+axGSBCKLgAElikCAGwXADMyLO3XRnmy2NxDQsTR0lAJRJJ5Mpow6NAk4Gg804RF+NmI7j6GLAhy6cHuA2KiwuHkymo03T5eLg4vQcFFRGJpIpw1GiUmRzEjFpAHUbDAABb-P02TBVOzAeJPX1vZ6vWE1AAGbnVnkOcfecA4GxQ5UwXx+MHDaAgtMDmBQCAQwDkGazmA20BKaAujETMA1hwuM2FjfNF3YXGAQiAA

### 💻 Code

```ts
export class FormControl<T> {
  value!: T;
}
export class FormGroup<T> {
  controls!: T;
}

class FormBuilder {
  group<T extends {}>(
    controls: T,
  ): FormGroup<{[K in keyof T]: FormControl<T[K]>}> {
    return null!;
  }
}

const fb = new FormBuilder();

export function getGroup() {
  return fb.group({
    data: [] as string[] | null,
  });
}
```

### 🙁 Actual behavior

Given the code above, TypeScript 5.7 produces a `.d.ts` file that looks like this:

```
export declare function getGroup(fb: FormBuilder): FormGroup<{
    data: string[] | null; // <----- Incorrect
}>;
```

### 🙂 Expected behavior

It should produce something like this:

```
export declare function getGroup(fb: FormBuilder): FormGroup<{
    data: FormControl<string[] | null>;
}>;
```

### Additional information about the issue

Source code of Angular's `FormBuilder`: https://github.com/angular/angular/blob/main/packages/forms/src/form_builder.ts

**Comment by alxhub** [comment]
Note that _within_ the file, `getGroup()`'s type is correct. It's only the `.d.ts` emit that shows the bug.

**Comment by trevorade** [comment]
FYI, here's a simpler repro with a few tweaks that can be made to resolve the issue:

https://www.typescriptlang.org/play/?ts=5.7.1-rc#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHMYdkAHAHgBV4QAPDEVYAZ3gG8BfAPgAow8MxCMwBc8SgEoxbANoBpeFnwBrEAE8cicQF1pANygRkIMZXnaOHANwAoG6EiwE-VMwzxgUDFADyAIwArAEZpT28xNxglAms7OlIcGHcUdGw8eGRmEABxYjIeCXYbeHgXNw8vX0CAJngAXiKSkrCoMQByNvgoVkjogBp4AHpB+AAlEABbHD1o+AADbvhe1AI5+DhmHAg9EFYsZmZjADpi+FjT4fWQDGQYfCISUh4W-2CJKyGRgHVE5WZTuA3O6EPJPF41d6feAASXQiTgmBsHDsly+WAwAAslPBMfskFgICABpiEBg1KQEJp5pkcqCCms8YYAO5QNSsfgwBEYAabGyXXGsKBgMC7QUQFls+BM37ME403KPApHFpHAxGEC2IA
