### ISSUE TITLE
Migrate-a-thon: Mutt-Match

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript#6051]
URL: https://github.com/Laura-Harris/Mutt-Match

Size: Medium
Tech: HTML, JSX, puppies

**Comment by RyanCavanaugh** [comment]
# Notes

**Comment by RyanCavanaugh** [comment]
String literals as types become *super dangerous* when porting:
```ts
let MyClass = myLib.createClass({
  foo1: "thing",
  bar: "Testing",
  bazOther: "something"
});
```

```ts
class MyClass {
  foo1 = "thing";
  bar: "Testing";
  bazOther = "something";
}
var x = new MyClass();
console.log(x.bar); // undefined, wat?
```

**Comment by RyanCavanaugh** [comment]
Would save work if we allowed commas between class members

**Comment by RyanCavanaugh** [comment]
Several big problems in backbone.d.ts

**Comment by RyanCavanaugh** [comment]
"Go to def" should work on prototype member of classes

**Comment by RyanCavanaugh** [comment]
Why is this an error?
```ts
class Base {
	method() { }
}

class Derived1 extends Base {
	method = () => {
		super.method();
	}
}
```

**Comment by RyanCavanaugh** [comment]
Had to fix #6029 to unblock myself

**Comment by RyanCavanaugh** [comment]
It is *crazy* frustrating to not be able to type an external module import as `any` without doing extra work

**Comment by RyanCavanaugh** [comment]
This project sometimes imports things and sometimes doesn't (relying on the global pollution of libraries instead). How can we help users enforce a consistent policy?

**Comment by sandersn** [comment]
1+ for commas between class members.

**Comment by Arnavion** [comment]
>String literals as types become *super dangerous* when porting:

This bit someone in the IRC channel today in a slightly different way. They had something like `class Scope { keyword: "" }; scope.keyword = someArray.join(",");`, got `Type string is not assignable to type '""'` and couldn't understand why a string couldn't be assigned to a string. They worked around it by changing it to `keyword: any;` but of course their real intention was `keyword = "";`

The error message could probably be clearer. Perhaps something like `Type string is not assignable to type '"foo" | "bar"''. The latter only allows strings of value "foo" or "bar".` ?

**Comment by RichiCoder1** [comment]
Casually was reading this and these are also huge pain points for us:
>This project sometimes imports things and sometimes doesn't (relying on the global pollution of libraries instead). How can we help users enforce a consistent policy?

>"Go to def" should work on prototype member of classes

>It is crazy frustrating to not be able to type an external module import as  any  without doing extra work
