### ISSUE TITLE
Inconsistent type narrowing behavior between compound assignment operators and their expanded equivalents

### ISSUE THREAD

**Issue by hanwenguo** [microsoft/TypeScript#60520]
### 🔎 Search Terms

"assignment operator" "type narrowing"

### 🕗 Version & Regression Information

- This is the behavior in every version in the Playground that I tried, and I reviewed the FAQ for entries about assignment operators and narrowing (there isn't any, though)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241116#code/GYVwdgxgLglg9mABAdzgJwNYGcAUAHAQzQIFsAuRLKNGMAc0QB9EwQSAjAUzQEoKqa9RAG8AUIkSFiJRAF5JRUogDUiAEQE1AbnGI0nKCDRIppLYgD0FxAEEIETniicAJhQDkpku8QwsLIjQ4ZFdEKDhEdwFaOndRAF9RUVBIWARKAAs4EAAbFxscrDgAdXQMACEQKAAROE4sADk4KHxFckpqGKYWNi5efk6hMQkvFXkNbV19Q2MFaXMrRAAVAE88TkQAUTQgtA8vHz9EAH0wZuOAneDQ8Mjo+jj4oA

### 💻 Code

```ts
function works(param: string | number): string {
  param = param + "a";
  return param; // Accepted: 'param' is narrowed to 'string'
}

function shouldAlsoWorkButDoesNot(param: string | number): string {
  param += "a";
  return param; // Type Error: 'param' is _not_ narrowed to 'string'
}
```

### 🙁 Actual behavior

Compound assignments (`+=`) and their expanded equivalents (`x = x + ...`) behave differently: `param = param + "a"` correctly narrows but `param += "a"` does not.

### 🙂 Expected behavior

`+=` should behave equivalently to `x = x + ...` with respect to type narrowing.

### Additional information about the issue

The code example is taken from [here](https://github.com/microsoft/TypeScript/issues/47027#issuecomment-1112358908).

Another less relevant issue which also reveals the inconsistency between `+=` and `x = x + ...` is #60521.

**Comment by jcalz** [comment]
duplicate-ish of #9815 and/or #17204 and/or #44553? Also related to #47027 (as linked above).
