### ISSUE TITLE
language services: If tsconfig.json under the ConguredProject project ignores some files, such as d.ts, opening these d.ts will create a new InferredProject. Is it designed like this?

### ISSUE THREAD

**Issue by schizobulia** [microsoft/TypeScript#60535]
### 🔎 Search Terms

If tsconfig.json under the ConguredProject project ignores some files, such as d.ts, opening these d.ts will create a new InferredProject. Is it designed like this?

### 🕗 Version & Regression Information

version: 5.6.3

### 💻 Code

```ts
// Your code here
```

### 🙁 Actual behavior

The two project paths are the same, but the ProjectKind is different

### 🙂 Expected behavior

Expect not to create a new project

**Comment by RyanCavanaugh** [comment]
Yes - why wouldn't it?

**Comment by schizobulia** [comment]
> Yes - why wouldn't it?

Can I ask why it is designed this way? 😀  @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
The most likely scenario of opening a `.d.ts` file that wasn't part of a configured project is that it's the *output* of that configured project, so merging it into the same project context as the tsconfig would result in many "duplicate identifier" errors

**Comment by schizobulia** [comment]
Got it. Thank you @RyanCavanaugh
