### ISSUE TITLE
I very much hope that ts will provide any as an implicit type, thank you

### ISSUE THREAD

**Issue by 1057105012** [microsoft/TypeScript#60536]
### 🔍 Search Terms

When writing ts, sometimes the type must be given, such as lambda. If you don’t want to write it, you must also give it: any. One is fine, but if there are many, the mental burden is very heavy

I want any to be the default type. If the function parameter type, function return value type, and variable type are not specified, the default type will be automatically deduced to any instead of reporting an error.

For asynchronous functions, the return value is allowed to be declared as a basic type and automatically inferred as a Promise, and defaults are also allowed.

The main purpose is to natively support js syntax in ts. Make ts an add-on rather than a coercion

----- Other suggestions ------
The second problem is that the official documentation of typescript is best to set all the type gymnastics as advanced tutorials and the basic type system as basic tutorials. For most scenarios, we only need type inference of ts, and do not need so many type gymnastics. Moreover, some type gymnastics can be realized through some basic type combinations. this will be complicated

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

无

### 📃 Motivating Example

无

### 💻 Use Cases

1. What do you want to use this for?
2. What shortcomings exist with current approaches?
3. What workarounds are you using in the meantime?

**Comment by jcalz** [comment]
You didn't fill out the full template.  

This already happens if you disable [`--noImplicitAny`](https://www.typescriptlang.org/tsconfig/#noImplicitAny), right? Does that not suffice?

**Comment by nmain** [comment]
It's hard to say because you didn't provide specific code examples as requested by the issue template, but you might also want [noEmitOnError: false](https://www.typescriptlang.org/tsconfig/#noEmitOnError).
