### ISSUE TITLE
Incorrect behavior evaluating `extends` in conditional type

### ISSUE THREAD

**Issue by davimiku** [microsoft/TypeScript#60531]
### 🔎 Search Terms

conditional types, type infer in conditional types, constraint validation

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about conditional types. It might be related to [this issue about 'never'](https://github.com/microsoft/TypeScript/issues/31751) regarding distributive conditional types but I don't think so, since this issue doesn't involve `never`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAIhDGB7AJhAKgQwOZQLxQHIBBAqAH0ICFSKCBhAgKEYEsA7YCAJwDMN5ocJKi4AeNABoomHBAAenNsgDOsBCnTYAfFADejKIahcIGZIjYAbEFFTCIALigAKdmACuwJ+7YBrNogA7mwAlHg6aIwAvszsnLz8guoiRFDyiipq9mI+-kFsUsQEOroxcdx8AlkaXJRpChBKqkI1ogBGiIiWpgVUxXplHBWJ1SJ09RnNydyiysBc7FiFDCUxjKCQUACSbDwzMBONmS0iorkBwYUkWjr4B+lHU9mi7Htc0lKv3NLaUAZGAH4frIGk1CCQ-kYoVAgcQIf9oVAnDJDmCCNQEYjAVQMVjocjsKjMvQmHi8bC6AxMWSjE42BAAG7cTF0xnMxh2SwYExQJBsOZQZQACwwkCIThO3CIHIQXJ5fIFwtFEEoEumtRl8Dl0AVwEFIsgdDV2TozA20DQEDmAEY8NtdjNzYgePrlUQtIwAPSeowAPX9-v1iHclmQUDa0DhpAj8Aw7mU0AABiiHmiSImgyGwxGoPN3BAzeALVbgAAmO07N6iJ0upWQSge700rEB1tt32Z0Ph6AYNhpLhcRDvGNxhO5oUsVTmK1sAh65QYYCTng2XVcDBxKCJgDKBogZz8F16RS0icK1CgAEJU8SSIXNpa5gBmCsOsQ112Gxs+5vQ9v-ztsx7PtuEHYcEFHaBgAnKdEBnOdBUXZdVwsOZ103Hc9wPPJLnBYoz0IBgrxvVQimYIA

### 💻 Code

```ts
type DecodeTag = 'A' | 'B' | 'C'

interface Decoder<T, Tag extends DecodeTag> {
    readonly decode: (input: unknown) => T
}

interface DecoderA extends Decoder<unknown, 'A'> {}
interface DecoderB extends Decoder<boolean, 'B'> {}
interface DecoderC extends Decoder<string, 'C'> {}

type Infer<D extends Decoder<unknown, 'A'>> = D extends Decoder<infer T, infer Tag> 
    ? Tag extends 'A' 
        ? 'AA' 
        : Tag extends 'B'
            ? 'BB'
            : Tag extends 'C'
                ? 'CC'
                : never
    : never

declare const shapeA: DecoderA
declare const shapeB: DecoderB
declare const shapeC: DecoderC

type Test1 = Infer<typeof shapeA>
//   ^^^^^ should be 'AA' because `Tag extends 'A'` should be true

type Test2 = Infer<typeof shapeB>
//                 ^^^^^^^^^^^^^ should be an error because this doesn't satisfy constraint `Shape<unknown, 'A'>`, because 'B' doesn't extends 'A'

type Test3 = Infer<typeof shapeC>
//                 ^^^^^^^^^^^^^ should be an error because this doesn't satisfy constraint `Shape<unknown, 'A'>`, because 'C' doesn't extends 'A'

```

### 🙁 Actual behavior

It seems like there's two separate issues in the code example above:

1. `Test1` evaluates to `"AA" | "BB" | "CC"`
2. `Test2` and `Test3` evaluate to `"AA" | "BB" | "CC"`

### 🙂 Expected behavior

1. `Test1` should evaluate to `"AA"` because `"A"` is being passed in for `Tag`, and `"A" extends "A"` should be true
2. `Test2` and `Test3` should error under `typeof shapeB` and `typeof shapeC` respectively. These should be an error because the type being passed in to `Infer` doesn't satisfy the constraint that `Infer` has. Namely, `"B" extends "A"` and `"C" extends "A"` wouldn't be satisfied

### Additional information about the issue

If you change the `Decoder` interface to remove the first type parameter (meaning that `Tag` would be the first type parameter rather than the second), everything works as expected. It seems to only occur when the arguments are not passed in the first position.

**Comment by jcalz** [comment]
Your `Decoder<T, Tag>` interface is structurally independent of `Tag` so it will definitely behave strangely: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-doesnt-type-inference-work-on-this-interface-interface-foot--

Add some structure depending on `Tag` and the problem should go away, like
```ts
interface Decoder<T, Tag extends DecodeTag> {
    x: Tag // or some other structural dependence
    readonly decode: (input: unknown) => T
}
```
[Playground link](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAIhDGB7AJhAKgQwOZQLxQHIBBAqAH0ICFSKCBhAgKEYEsA7YCAJwDMN5ocJKi4AeNABoomHBAAenNsgDOsBCnTYAfFADejKIahyAXNOxQA9JaiIuUZYgC20RMAAW3B8C4BXeMC+XBgANlCokEoQbAIGRlwQGMiIbCEg4eqoZgAU7GC+wGa+bADWbIgA7mwAlHg6aIwAvszsnLz8gpncRFDyiipqwtyixWWVbFLEBDq6UM2t3HwCgxpclL0K0QNCq6IARoiIIYkTVNN6c6wcix0rInQb-ao7IqLKPuxYkwwzl4ygkCgAEk2DxhjBHltnl0xKNylVJiQtDp8BC+lC7sN2GD7JIoNivDItHFDAB+cyyTZKVRTKDk4gkKBmGSQ6lnOlUahMimsgb0Uj0ugMEnctgQABu3BFZjFkq4zFQ8BCGASUCQbHeDncGEgRDML26jEVytV6s1ym1kEo+phlCNCBN0DNwC1OogdBtQy4dGYAOgAC08JiuD10WyDWICfYABpSKNQACaOnJAG1Y4mALqiiVS-7gaBoCDvACMQZBONEfsQPFduuJ1iMAD1m82tYhfCFkFA9tAGaQe-AML5lNAAAYssN8kijtsdrs9qA+XwQX356RF4AAJjLoOGVZrFrdlHrNiMZ-PZ5bV+vjdnne70AwbF6XC4dgfg+H0A8LFUySLbAEC6ygYMAv48OkzrBK0UCjgAypaEAjKU8KnFMWijpMXIAISTjSJCroChbvAAzDuFb7rW7onhetGXjeN53vOj7Ptwb72AOQ4jou7i-uEiAAUBDigeBkEpO80EcLBCFushYwIoQSKYYQDBQLhVJTkwjBAA)

Unused generic type parameters should be avoided.

**Comment by davimiku** [comment]
I see, so is the compiler doing "dead code elimination" on the unused type parameter when evaluating the type, essentially as an optimization? It seems different than that FAQ, which is about inference whereas this is about type **substitution**, but maybe it's the same underlying procedure.

That's unfortunate that we have to add a runtime value for something that needs to only be checked at compiletime. Actually, the current behavior is beneficial for what I'm building (the lack of error actually works in my favor), but it just didn't match my knowledge of how type substitution works in type checking algorithms which is why I logged it. It could be nice to have something akin to ["phantom" type parameters](https://doc.rust-lang.org/rust-by-example/generics/phantom.html) in Rust to keep compiletime checks at compiletime only, without having to change the runtime code/data.

**Comment by jcalz** [comment]
Maybe https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-astring-assignable-to-anumber-for-interface-at-- is a better FAQ entry.

It's not an optimization, it's structural typing.
