### ISSUE TITLE
Incorrect `This condition will always return 'false' since JavaScript compares objects by reference, not value` warning

### ISSUE THREAD

**Issue by johndoknjas** [microsoft/TypeScript#60545]
### 🔎 Search Terms

"this condition will always return false since javascript compares objects by reference typescript github issue"

### 🕗 Version & Regression Information

Saw this message in vscode and the typescriptlang playground.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCKhwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HUiQ58D0Ii8fLpDKZgj5SWxfPADlQAHJhAA5SASPlBFQAeS+ZHegmdWkgR1QjgUrmkeFATjNOmGWH0KAQiGhwkuNok4uiIgMHGxCyYrA4PCCJWljVl8sVSoA2gBGAC6PN5451QA

### 💻 Code

```ts
console.log([1] == 1)
```

### 🙁 Actual behavior

Hovering over the line gives the warning `This condition will always return 'false' since JavaScript compares objects by reference, not value.`

### 🙂 Expected behavior

No warning, since the comparison results in `true`.

**Comment by RyanCavanaugh** [comment]
I don't really see much point either special-casing the `==` case or muddying the wording of the `===` case. There's no reason to write code this way and the error gets the point across
