### ISSUE TITLE
`Set.has()` should accept any value, and could be a type predicate

### ISSUE THREAD

**Issue by jthemphill** [microsoft/TypeScript#60547]
### ⚙ Compilation target

ES2015

### ⚙ Library

`lib.es2015.collection.d.ts`

### Missing / Incorrect Definition

https://github.com/microsoft/TypeScript/blob/d85767abfd83880cea17cea70f9913e9c4496dcc/src/lib/es2015.collection.d.ts#L87-L90

I believe

```ts
Set<T>.has(value: T): boolean
```

should become

```ts
Set<T>.has(value: unknown): value is T
```

This applies for other methods as well, such as `Map<K, V>.has(key: K): boolean`, as well as other ES standards.

Essentially, it's *not* an error to pass an arbitrary value to `Set.has()`. It doesn't lead to a crash, exception, or error of any sort, even when we pass weird values like `{}`, `[]`, or `NaN`, so the typechecker shouldn't stop us from doing it. We simply get a `true` if the value is in the Set, or a `false` if the value is not. And since the `Set` can only contain values of type `T`, the boolean returned by `Set.has()` also becomes proof that `value` is of type `T`. This makes it an ideal candidate for a type predicate.

This would immediately fix several regressions in our codebase that we saw when we upgraded TypeScript from 5.3 to 5.5. TypeScript's inferred type predicates are amazing, but they narrowed the types of our Sets and caused several of our `Set.has()` method calls to become errors. The sample code is a simplified example of what we've found in the wild in our codebase.

### Sample Code

```TypeScript
declare function defaultAttrs(subtype: string): string[]
declare function getAttrs(): string[]

type MyAttribute = `_${string}`
function isMyAttribute(key: string): key is MyAttribute {
  return key.startsWith('_')
}

export function myAttrs(subtype: string) {
  const defaults = defaultAttrs(subtype)
  return new Set(
    Object.keys(defaults).filter((key) => {
      return isMyAttribute(key)
    }),
  )
}

function attrInSet(subtype: string) {
  const myAttrSet = myAttrs(subtype)
  for (const attr of getAttrs()) {
    // Argument of type 'string' is not assignable to parameter of type '`_${string}`'.ts(2345)
    if (myAttrSet.has(attr)) {
      return true
    }
  }
  return false
}
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has

**Comment by RyanCavanaugh** [comment]
Basically the same as #26255; we don't agree that making `arrayOfDogs.includes(cat)` legal or `setOfCats.has(dog)` is a good idea. You can add an overload to the global type via interface augmentation (note that the reverse is *not* true; if we changed this to never be an error, no one could opt in to the current behavior).

**Comment by jthemphill** [comment]
Thank you for the quick response!

> we don't agree that making `arrayOfDogs.includes(cat)` legal or `setOfCats.has(dog)` is a good idea.

Well, `Cat` and `Dog` are disjoint types. From your discussions in the linked issues, it's clear you've seen that the real problem is when the types are not disjoint. When `setOfCats.has(cat)` leads to a type error, simply because `setOfCats` has been refined to `Set<MaineCoon | Tabby | ... | ScottishFold>`. To fix this error, our options are to unsafely cast `setOfCats` to a `Set<Cat>`, or to pass the `cat` value through a gauntlet of type refinements until it's finally worthy of the `.has()` method.

* https://github.com/microsoft/TypeScript/issues/14520

> [Once that was implemented, we absolute would change the signature to something like `includes(arg: T | super T)`](https://github.com/microsoft/TypeScript/issues/26255#issuecomment-736680802)

But isn't `unknown` a subset of `super T`? This seems like allowing `arg: unknown` with extra steps. If a generic has no upper bound, the typechecker will always be able to resolve it to the top type.

To get the best of both worlds, you would need some way of enforcing non-disjointness. After creating the `super` keyword, we did not use the `super` keyword in Hack's `C\contains()` method. Instead, we added `<<__NonDisjoint>>` constraints to the generics, which enforce that `T1` and `T2` are not disjoint:

https://github.com/facebook/hhvm/blob/9591b86b9eff17f35bb7d5eb029ca13ee6757bff/hphp/hsl/src/c/introspect.php#L41-L54

```hack
function contains<
  <<__NonDisjoint>> T1,
  <<__NonDisjoint>> T2
>(
  readonly Traversable<T1> $traversable,
  readonly T2 $value,
)[]: bool;
```

TypeScript may have a more elegant way of expressing this, using conditional types. I encourage finding a way to express the disjointness of types, because I think using the `super` keyword will wind up allowing arbitrary values anyway.

* https://github.com/microsoft/TypeScript/issues/51678

Sorry, yes. I didn't realize that type guards work both ways.

**Comment by LukeAbby** [comment]
While not completely ideal, a type that can mostly fit the utility of `<<__NonDisjoint>>` in regular TypeScript code does exist:
```ts
type OverlapsWith<Param, Shape> = [Param & Shape] extends [never] ? Shape : Param;

declare global {
    interface Set<T> {
        has<V>(value: OverlapsWith<V, T>): boolean;
    }
}

const s = new Set([1, 2, 3]);
s.has(Math.random() ? 1 : "foo");
```

It's less implicit but it should have the same power as `<<__NonDisjoint>>` does ultimately.

I think it becoming a built-in type would be ideal for better errors. Plus I doubt that the TypeScript team would want to add this conditional type to the library files today, the requirement of making it generic is a bit strange at a glance and the errors can be a bit subpar in some cases.

**Comment by RyanCavanaugh** [comment]
Yeah, `super` isn't quite the right thing here. Instead of non-disjoint we call it "comparable" which basically covers the same concept. It's the type relation that covers whether `x === y` is allowed and would ideally be something you could use in type-land

**Comment by jthemphill** [comment]
Yes! We are on the same page!

For completeness, [here's a playground example](https://www.typescriptlang.org/play/?#code/PTAEHEHtIEwQgFADMCuA7AxgFwJaTaAIYBOxhAngJKYA2KMApgM4Ay0ADgCI5MBWkONFgA8AFQCMAGlCiATAD4AFCTLkAXDNkBtALrSAboToMNEgJQaARtBoNCBAN4JQoJJGKhFGfEyygAHqCQSESkFGagTi4uIDIAFjyg3gC27CQ8+ETs7HbETKBYkKCWDKDoglgMQnhoRsUMGIQoTKVYca3kOfkA5HLdRGgwoL3i-XGE+qVoRZCTxDSE7AB0irIAzABsAOxmztE4IYqBALynoIbGEVHRLsQMWCjEBFjEKAwA3HsuAL57v7f3R4EJBGFqfX4IWJQWCIVCYXCZFQUagYOiMVgcABy+G4fAEQjEUk0oAY-kqg3yEiUSPUml0BiMb1M4gsxRsdkcezcHi8Pj8gWCoVUVy+oAOnhOZwubxFNwBDyeBVeH1F-1AaruCuBoJVENiAFlCABrZigZKlJiEGBLG3IdDYGpC5G0ejMABCKBwNFwaEJ0jkJLJVRglPE1LCtLk9POjJMMhZVnZ9kie1iAEFiABzFDmoRBEJYTqlEb9RLTPyEJhMHCZ2qWWwFIppMjmyoeQWFnLDPpLVNgFy9WT9bwoGhDEpitC+ey4QiVIYAdxwbQGoUsy7IxHIBSLoAXCQwcSSkFH49K6DuC3nje7oxW6wALABWXbyoFO8hLQSo11MRTShgzHBBAgA) showing that the typechecker is more forgiving towards `===` in a `for` loop than it is to `array.includes()`:

```ts
// Good!
function arrayIncludesLoopDisjoint<T1, T2>(array: T2[], value: T1): boolean {
  for (const x of array) {
    // This comparison appears to be unintentional because the types 'T2' and 'T1' have no overlap.(2367)
    if (x === value) {
      return true;
    }
  }
  return false;
}

// Good!
function arrayIncludesLoopNonDisjoint<T1, T2 extends T1>(array: T2[], value: T1): boolean {
  for (const x of array) {
    if (x === value) {
      return true;
    }
  }
  return false;
}

// Makes me sad...
function arrayIncludesBuiltin<T1, T2 extends T1>(array: T2[], value: T1): boolean {
  // Argument of type 'T1' is not assignable to parameter of type 'T2'.
  //   'T2' could be instantiated with an arbitrary type which could be unrelated to 'T1'.(2345)
  return array.includes(value);
}
```

**Comment by sod** [comment]
> we don't agree that making arrayOfDogs.includes(cat) legal or setOfCats.has(dog) is a good idea

It's more like:

```
arrayOfDogs.includes(whatTheHeckIsThis)
```

It's a more recent concern as typescript got more powerful. Especially `as const`. `as const` is very nice to get way better code completion as you sets of values can be autosuggested (and don't boil down to `string`). But I'd still like to compare user input against it. E.g. why is this ok:

```
const userInput1 = 'cat'
const dogsString = ['foo', 'bar', 'baz'];
dogsString.includes(userInput1); // ok
```

but this isn't:
```
const userInput2 = 'cat'
const dogsConst = ['foo', 'bar', 'baz'] as const;
dogsConst.includes(userInput2); // ts-error
```

[playground](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBArhApgJwJJgA5ygRhgXhgHJgBDKIgKFElgBMQBzCAZSmQEsxGCYBtIgDMQIIgBpiAI1LJxU0gC8iAXQDclBszaduAOi7AANnDqIIACgQp0WXAEp11cNHhI0mbACZeJclRoumhAAws6whALCohJE0rIx0krKMKQQMAFQ6kGhtPpgRiZmlm42Xg6UQA)
