### ISSUE TITLE
Module resolution: Module resolved to indirect dependency rather than direct local one when versions are the same

### ISSUE THREAD

**Issue by grigasp** [microsoft/TypeScript#60556]
### 🔎 Search Terms

"local module resolution", "module resolution same version"

### 🕗 Version & Regression Information

- Noticed in `5.6.3`, also reproduced with `next`, `4.6`, `4.8`, `5.0`.
- I reviewed the FAQ for entries including "resol".

### ⏯ Playground Link

https://github.com/grigasp/ts-deps-issue

### 💻 Code

Package `a@1.0.0` is released with the following:
```ts
export type A1 = number;
```

Locally we have this package at the same version, but with an additional type:
```ts
export type A1 = number;
export type A2 = string;
```

Locally we also have a package `b`, that has a dependency on a **released** version of `a@1.0.0` and exports the following type:
```ts
import { A1 } from "a";
export type B = A1;
```

Finally, locally we also have a package `c`, that has dependencies on local workspace versions of packages `b` and `a` and imports types from them both:
```ts
// Switching order of these import fixes the build
import { B } from "b";
import { A2 } from "a";

const b: B = 1;
const a2: A2 = "a2";
```

### 🙁 Actual behavior

When building package `c`, the build fails with error:
```
> c@1.0.0 build
> tsc

src/index.ts:3:10 - error TS2305: Module '"a"' has no exported member 'A2'.

3 import { A2 } from "a";
```

### 🙂 Expected behavior

When building package `c`, TypeScript resolves package `a` to our local version which does have the `A2` type, and the build succeeds.

### Additional information about the issue

I tried running `tsc -traceResolution` for package `c` and it seems that both - released package and the local one - are assigned the same Package ID:

```
...
======== Resolving module 'a' from 'E:/temp/ts-deps-issue/packages/c/src/index.ts'. ========
...
======== Module name 'a' was successfully resolved to 'E:/temp/ts-deps-issue/packages/a/lib/index.d.ts' with Package ID 'a/lib/index.d.ts@1.0.0'. ========

======== Resolving module 'a' from 'E:/temp/ts-deps-issue/packages/b/lib/index.d.ts'. ========
...
======== Module name 'a' was successfully resolved to 'E:/temp/ts-deps-issue/node_modules/.pnpm/a@file+packages+a+a-1.0.0.tgz/node_modules/a/lib/index.d.ts' with Package ID 'a/lib/index.d.ts@1.0.0'. ========
...
```

I suppose that could cause a cache collision or something like that.

**Comment by andrewbranch** [comment]
> I suppose that could cause a cache collision or something like that.

Exactly; we deduplicate packages by name and version; a different symptom of the same cause was closed as a design limitation here: https://github.com/microsoft/TypeScript/issues/51976. I’m not sure what we could do about this.

**Comment by grigasp** [comment]
> > I suppose that could cause a cache collision or something like that.
> 
> Exactly; we deduplicate packages by name and version; a different symptom of the same cause was closed as a design limitation here: [#51976](https://github.com/microsoft/TypeScript/issues/51976). I’m not sure what we could do about this.

Just throwing out a couple of ideas...

- Could you use full path to the module for package id? So instead of `a/lib/index.d.ts@1.0.0`, it would be `E:/temp/ts-deps-issue/packages/a/lib/index.d.ts` or `E:/temp/ts-deps-issue/node_modules/.pnpm/a@file+packages+a+a-1.0.0.tgz/node_modules/a/lib/index.d.ts`.
 
- Could you detect that the module is from a workspace package and for such packages use a special version identifier, e.g. `a/lib/index.d.ts@workspace`?

**Comment by andrewbranch** [comment]
We deduplicate packages for a reason, so defeating the deduplication is just trading one problem for another. Including the same code multiple times can cause bogus errors. While it would fix your specific use case here, it could just as easily create duplicate declaration errors for someone else.

**Comment by RyanCavanaugh** [comment]
> Isn't it the job of package manager to do that?

This hasn't always been the case; older versions of npm would not deduplicate when sub-dependencies needed to be nested, but it's a huge performance problem for TS if we need to e.g. resolve 30 copies of `lodash@3.0.0` in different subfolders.

You can argue that an ideally set-up package manager wouldn't do this, but I'd also argue that a correctly set-up package manager can't produce two packages with the same version and the same name but with different contents, which is the setup your repro depends on. It doesn't really fly to say we should rely on one invariant while ignoring the other.
