### ISSUE TITLE
class implements Awaited<any> [bug]

### ISSUE THREAD

**Issue by MaxmaxmaximusFree** [microsoft/TypeScript#60568]
### 🔎 Search Terms

implements Awaited bug

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### 💻 Code

This works:

```typescript
async function test() {

    class Cat implements Awaited<any> {
    
    }

    await new Cat()
}
```

but This error:
```typescript
async function test() {

    class Cat implements Awaited<any> {
        then(){ }
    }

    await new Cat()
}
```

![Image](https://github.com/user-attachments/assets/42bace86-a090-429d-91a5-95f29656a62e)

### 🙁 Actual behavior

bug

### 🙂 Expected behavior

normal await

**Comment by MartinJohns** [comment]
You forgot to fill out the issue template.

What makes you think this is a bug? The error message indicates this is intentional.
