### ISSUE TITLE
tsc hangs and loops consuming CPU on a single input file

### ISSUE THREAD

**Issue by t0yv0** [Microsoft/TypeScript#6057]
TypeScript compiler hangs for me and does not complete compilation within 5 minutes on a 50 KB source file. To reproduce, run on this input file:

https://raw.githubusercontent.com/Tachyus/gluon/master/src/Gluon.Client/Gluon.ts

```
Platform: Windows 10 64-bit

tsc --version
message TS6029: Version 1.7.3

node --version
v5.2.0
```

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/5849

**Comment by mhegazy** [comment]
Can you try [VS2015 TS 1.7.6 Update](http://go.microsoft.com/fwlink/?LinkID=717098) or [VS 2013 1.7.5 Update](http://go.microsoft.com/fwlink/?LinkID=717464) and let us know if it solves the issue?

**Comment by t0yv0** [comment]
Yea sounds like a good idea to try. Can I install 1.7.6 via NPM?

**Comment by vladima** [comment]
you can use `typescript@next` to install the latest nightly build

**Comment by t0yv0** [comment]
Nice. Thank you. Indeed, with Version 1.8.0-dev.20151210 everything is fine.

**Comment by mhegazy** [comment]
thanks @t0yv0!
