### ISSUE TITLE
Type 'ArrayBufferLike' is not assignable to type 'BlobPart'.

### ISSUE THREAD

**Issue by Yonom** [microsoft/TypeScript#60579]
### 🔎 Search Terms

ArrayBufferLike BlobPart SharedArrayBuffer ES2024

### 🕗 Version & Regression Information

- This changed between versions `5.7.2` and `5.6.3`
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?target=11&ts=5.7.2#code/MYewdgzgLgBFICEA2IBGMC8MAUATAhlPgFwwCqAlmFABwCCATg-gJ4A0cLADgKanQMqAcwCUmAHwwA3jABQMGAx5QArgzAwwPAO4xkabAG0CRAHSoVAM0s8GAXQ4yo3HjAC+IgNyy3QA

### 💻 Code

When targetting ES2024, the following code throws a type error:

```ts
const toBlob = (data: Uint8Array, type: string) => { 
  return new Blob([data.buffer], { type });
}
```

### 🙁 Actual behavior

```
Type 'ArrayBufferLike' is not assignable to type 'BlobPart'.
  Type 'SharedArrayBuffer' is not assignable to type 'BlobPart'.
    Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, transferToFixedLength
```

### 🙂 Expected behavior

Backwards compatibility with ES2023

**Comment by jcalz** [comment]
The [TS 5.7 release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#notable-behavioral-changes) and #59417 explain what's going on here. If you want a `Uint8Array` whose `buffer` property is a suitable `BlobPart` you'll have to ask for it explicitly like

```ts
const toBlob = (data: Uint8Array<ArrayBuffer>, type: string) => { 
  return new Blob([data.buffer], { type });
}
```
[Playground link](https://www.typescriptlang.org/play/?target=11&ts=5.7.2#code/MYewdgzgLgBFICEA2IBGMC8MAUATAhlPgFwwCqAlmFABwCCATg-gJ4A8jzLCArgGZ8ApgwB8AGjgsADoNLQGVAOYBKTCJgBvGACgYMBoKg8GYGGEEB3GMjTYA2gSIA6VPyEMAuhK1RpgmAC+ygDc2gFAA)

And of course that might have to propagate throughout your code base. Maybe the TS team has a recommendation for how to proceed in general with this sort of thing; the release notes only mention updating node.

**Comment by MonstraG** [comment]
Yea, it would be very nice to see some recommendations. `@types/node` is updated to `22.10.1`, and I'm hitting a similar issue with

https://www.typescriptlang.org/play/?target=99#code/MYewdgzgLgBARgQwE4C4YEElIQTwEICuAZkQKZIAyAlgNakwC8MYpA7jAKpVhQAcm2HAAoAlAG4gA
