### ISSUE TITLE
Expressive Reversed type for tuples

### ISSUE THREAD

**Issue by redpulp** [microsoft/TypeScript#60575]
### ⚙ Compilation target

ES2024

### ⚙ Library

5.6.3

### Missing / Incorrect Definition

```ts
interface Array<T> {
    reverse: T[];
}
```
This loses all information of the order of reversed tuples, I usually have to use the following code to  override the behaviour of `Array.prototype.reverse`
```ts
type ReversedTuple<T extends any[], R extends any[] = []> = ReturnType<T extends [infer F, ...infer L] ? () => Reverse<L, [F, ...R]> : () => R>;
type ReversedTupleOrArray<T> = T extends [any, ...any[]] ? Reverse<T> : T;
```

### Sample Code

```TypeScript
const myTuple: [number, string, string] = [1, 'hello', 'world']
const reversedTuple = myTuple.reverse() // (string | number)[]
```

**Comment by MartinJohns** [comment]
Related: https://github.com/microsoft/TypeScript/issues/13360#issuecomment-271365952

And in general `reverse()` is troublesome for tuples, because it modifies the array in-place.
