### ISSUE TITLE
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

### ISSUE THREAD

**Issue by imranbarbhuiya** [microsoft/TypeScript#60588]
### 🔎 Search Terms

Hi, from ts 5.7, I'm getting the same error as reported in #60132 but for `jsx: react-native`. Wheneven I use `<></>`, I get the above error

### 🕗 Version & Regression Information

- This changed between versions 5.6 and 5.7

### ⏯ Playground Link

https://www.typescriptlang.org/play/?jsx=3&ts=5.7.2#code/JYWwDg9gTgLgBAbzgNWAUwO5wL5wGZQQhwDkUaAhgMYwC0AdhTMAG5okDcAUF2gB6RY+AK70awCPTgBhIpHpp6MABQBKBD3IxhUKQB4AfFzhw9qTAb0B6cxiMmz6O9dv3TVo9iA

### 💻 Code

```ts
import { View } from 'react-native';

export function Component(){

return <>
  <View></View>
  <View></View>
  </>
}
```

### 🙁 Actual behavior

The fragment shows an error

### 🙂 Expected behavior

This should work like ts 5.6 and shouldn't error

**Comment by mrlika** [comment]
The issue is reproducible with the latest Expo 52 default app and TypeScript 5.7:
```
npx create-expo-app my-app
cd my-app
npx tsc
```

The issue is not reproducible with Expo 51 and TypeScript 5.7:
```
npx create-expo-app my-app --template default@51
cd my-app
npx tsc
```

But on Expo Discord channel think that the issue is in the latest TypeScript because lower versions of TypeScript work fine.
