### ISSUE TITLE
`NoInfer` interfere with `Exclude` in Exclude<NoInfer<I>, undefined>`

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript#60594]
### 🔎 Search Terms

* NoInfer
* inteference 
* Exclude

### 🕗 Version & Regression Information

This is not a regression, and doesn't work with 5.7 :

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAogHgYwDYFcAmECqA7DAzAS2wjQB4AlAPigF5ZFUNSA5AewEls8IAnCygDRQUuCIWJpKAbgBQMpBGBRsARgBc9ZOiyjxJUthQBbAEa8oAH2G6iJanRH5baKVDduA9B6isA1vMVlACYNeC0MHCcJFmMzHktrKLtaRLFnV3coL2VWJQgGbTQApQBndU1GHSSyEuAeIgBzBMc0iXtUvRdMrO8-YqgSkIrtSNb9AGU6xuabNpSWzoz3bOxcqHzwkn60crDK0c7SABEAQ2BoKwXndquJJcyVtY3KooUlE54eXYKI2f1DUy8ADaAF0ZtUbn8uo88j8tm8fCYAFbfTYHZykADeAF9wWNJPMofdlr1-AjDEgkKj9lCDChKXjOpDqvdsn0gA

### 💻 Code

```ts
type ExcludeUndefined<R> = Exclude<NoInfer<R>, undefined>;

let n1: ExcludeUndefined<number | undefined> = undefined;     // ok
let n2: ExcludeUndefined<Number | undefined> = undefined;     // not excluded
let s1: ExcludeUndefined<string | undefined> = undefined;     // ok
let s2: ExcludeUndefined<String | undefined> = undefined;     // not excluded
let d1: ExcludeUndefined<Date | undefined> = undefined;       // not excluded
let arr1: ExcludeUndefined<number[] | undefined> = undefined; // not excluded
let obj1: ExcludeUndefined<{} | undefined> = undefined;       // ok
let null1: ExcludeUndefined<null | undefined> = undefined;    // ok
```

### 🙁 Actual behavior

`undefined` is not consistantly excluded. 

### 🙂 Expected behavior

`undefined` should be consistantly excluded.

**Comment by RyanCavanaugh** [comment]
This isn't a supported way to use `NoInfer`. Not sure what the intent of this is.

**Comment by jcalz** [comment]
What if you have a function whose return type involves `NoInfer` because you don't want it to be inferred from the variable to which you assign it? I mean, if you have a function that looks like `declare function foo<T>(⋯): Exclude<NoInfer<T>, undefined>` then you could end up with `foo<Date | undefined>(⋯)` producing one of these things.

**Comment by Andarist** [comment]
I agree with @jcalz and `NoInfer`ing within a return type is actually something I recommended last month to somebody as a fix for their problems. It's a legit pattern.
