### ISSUE TITLE
How to know the version of typescript used in an IDE.

### ISSUE THREAD

**Issue by heroboy** [Microsoft/TypeScript#6059]
For example: http://www.typescriptlang.org/Playground, vs2015 or vscode.
Can I know what is the version or feature enabled by js generated or intellisense?

**Comment by DanielRosenwasser** [comment]
In the Playground, it's 1.7.4. There's no way to tell unless you open up the services/server code being used, or potentially if you have some way of interacting with the runtime. For example, in http://www.typescriptlang.org/Script/vs/languages/typescript/common/lib/typescriptServices.js, look for the string `version="` and that should help find it.

**Comment by DanielRosenwasser** [comment]
To clarify, for VS2015, I believe you can look in add/remove installed programs. 

I'm not sure about with VSCode. @egamma, I don't see where one can find out the current version of each bundled language service.

**Comment by egamma** [comment]
We currently do not expose the TS version in the UI. In general, in VS Code we bundle the latest official TS version that is available for the monthly update. So the December update will include 1.7.*. 

Users can configure another TS version using the `typescript.tsdk` configuration setting.

**Comment by DanielRosenwasser** [comment]
Thanks for the response @egamma! Hope that helps @heroboy.

**Comment by heroboy** [comment]
Thanks @DanielRosenwasser . But I want a general method. In languages like c++, I can get the version or feature by macro. Typescript is a frequently updated language, the language features and compiler bugs are frequently changed. If I can get the version more easily, then it can make me better to search the issues or report the issues.
Another problem is in an IDE sometime the typescript used by intellisense and compiling is not the same. For example, vscode use a task file to compile project, it runs tsc in global path, they may be not the some one. I'm very worried about it.

**Comment by SaschaNaz** [comment]
@egamma I have found that resources\app\out\vs\languages\typescript\common\lib\typescriptServices.js is from version 1.5 (from #5771), do you know why this file is not updated?

**Comment by egamma** [comment]
@SaschaNaz you a found the version of TS used for the Javascript language service. We haven't updated this one as eagerly as the one used for the TS language service, since we plan to migrate to Salsa soon and each upgrade has development costs. 

This is the location with the typescript used by the typescript language service:
`resources\app\extensions\typescript\server\typescript\lib`

**Comment by SaschaNaz** [comment]
@egamma Thanks for your explanation :+1: There are some old formatter problems in JS so I wondered why.
