### ISSUE TITLE
Provide completion lists for string literals

### ISSUE THREAD

**Issue by danquirk** [Microsoft/TypeScript#606]
Many JavaScript frameworks are heavily based on using string values to do many things, from getting and setting attributes via the property name in string form, to defining event handlers to handle browsing to particular URLs. TypeScript added specialized signatures in overloads as one means to help mitigate the pain associated with these types of APIs. Unfortunately for a number of patterns this is insufficient and not general enough. Rather than try to design a specific type system enhancement that could handle some or all of the many ways these frameworks use string literals we could try some simple tricks in Visual Studio to help out. Namely, when typing a string literal the editor should provide a completion list based on other string literals already used in your program. Some other tools already provide similar capabilities (ex Sublime Text).

Consider something like this in a Backbone View class:

```TypeScript
class TodoView extends Backbone.View<TodoModel> {
    initialize() {
        this.listenTo(this.model, 'change', () => this.render());
        this.listenTo(this.model, 'todoDescriptionChanged', () => this.render());
        this.listenTo(this.model, 'destory', () => this.remove());
    }
```

At another point I may attempt to manually trigger one of these events:

```ts
    updateTodo() {
        var desc = this.$input.val().trim();
        var todo = this.model;
        if (desc) {
            todo.save({ title: desc });
            // provide completion list inside this string literal showing 
            // todoDescriptionChanged to avoid hard to debug typos 
            // and speed up development
            todo.trigger('todoDescriptionChanged'); 
        }
     }
```

This should be a relatively cheap solution to a common set of problems that we've always hoped TypeScript can improve on over JavaScript. If you did accidentally make a typo in one use of the literal this could also help you discover that when seeing 2 completion list items that are similar but slightly different.

**Comment by jbondc** [comment]
:+1: Related is enums:
![image](https://cloud.githubusercontent.com/assets/199519/10107114/ca442adc-6386-11e5-9366-823e93d109d2.png)

Likely two improvements (applied to interfaces too):

- Member/prop names of string literals should show up a ```list["a"] = 0``` 
- Autocomplete works on string literals

**Comment by DanielRosenwasser** [comment]
Now that string literal types are a thing in the compiler, this will become more useful.

Additionally, much like object literal completions are informed by its contextual type, we should consider doing the same with string literal completions. For instance:

```TypeScript
type T = "foo" | "bar";

let x: T = "$
```

At `$`, I expect my completions to be only `"foo"` and `"bar"`, regardless of any other identifiers in the file.

**Comment by mrcrowl** [comment]
+1 please! Just to give you a user's point of view... I had assumed this would be included when string literals were released.  But regardless would love to see this done when you guys are able!

**Comment by NoelAbrahams** [comment]
:+1: .

I hope this goes in soon as it will be quite useful.

Also JSDoc should be supported for the values:

```ts
    /** Defines the permissible size measures. */
    export type SizeRule =

        /** Indicates the smallest possible size */
        'tiny' |

        'small' | ...;
```

**Comment by danquirk** [comment]
@DanielRosenwasser is this really fixed? #8125 looks like it fixes the enum issue @jbondc mentioned in https://github.com/Microsoft/TypeScript/issues/606#issuecomment-143290638 but all the tests in that PR look enum related. This issue is really a broader suggestion around string literal values outside of the type system.

**Comment by DanielRosenwasser** [comment]
GitHub is not good at auto-closing if you just refer to the comment. Thanks for the heads up Dan. :smile:

**Comment by danquirk** [comment]
@mhegazy It doesn't look to me like #8428 addresses the example in the original suggestion. The compiler now gives type directed string literal suggestions but it doesn't just generally supply previously used string literals as completion options (like Sublime Text and other text editors do). Is that right?
