### ISSUE TITLE
Autocompletion for private `class` properties

### ISSUE THREAD

**Issue by timursaurus** [microsoft/TypeScript#60607]
### 🔎 Search Terms

private properties, is private and only accessible within class

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about private keyword
From 3.3.3 up to 5.7.2 this bug occurs

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEBCCuBzaBvAUNTmAOAnAlgG5gAuAptHgPbbQC80A5AO5W4DWEjaAvmmqEgwASmWwhoZAB7kAdgBMYCZOiyZgVWRBK54wEmwAUASlQY1FiPGxlcJ8xawkAFvggA6arQD03yblw2B0doFzcAbUYvRgBdaF9oWSp-QNxg6D4+IA

### 💻 Code

```ts
class Bug {
     private prop = 'should not be accessible'
}

class Repl extends Bug {
     constructor() {
          super()
          this.prop // error ✅
          this['prop'] // no error ❌
     }
}

```

### 🙁 Actual behavior

We're able to access private properties of the class with brackets

### 🙂 Expected behavior

Accessing private properties with brackets should not be possible

**Comment by MartinJohns** [comment]
This is working as intended, see #19335.
