### ISSUE TITLE
I expect there to be a new enumeration type where the value of the enumeration type is equal to the key of the enumeration

### ISSUE THREAD

**Issue by yanguoliang** [microsoft/TypeScript#60604]
### 🔍 Search Terms

"new enumeration type", "new enum", "enum key value"

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

I expect there to be a new enumeration type where the value of the enumeration type is equal to the key of the enumeration，

### 📃 Motivating Example

When I define an enumeration so that the key and value are the same string, I need to write as follows：
```
enum Action {
  EDIT = 'EDIT',
  ADD= 'ADD',
  DELETE = 'DELETE',
}
```
This way a lot of redundant code is written.

I expect there to be a new enumeration type where the value of the enumeration type is equal to the key of the enumeration，
```
enumStr Action {
  EDIT,
  ADD,
  DELETE,
}
console.log(Action.EDIT === 'EDIT') // true
console.log(Action.ADD === 'ADD') // true
console.log(Action.DELETE === 'DELETE') // true
console.log(Action.EDIT === 0) // false
console.log(typeof Action.EDIT) // string
console.log(typeof Action.ADD) // string
console.log(typeof Action.DELETE) // string
```
A new keyword `enumStr` is used here to define an enumeration. The key and value of the enumeration are the same string.

### 💻 Use Cases

1. What do you want to use this for?
answer: Simplified syntax，Keep the original enum syntax unchanged，from
```
enum Action {
  EDIT = 'EDIT',
  ADD= 'ADD',
  DELETE = 'DELETE',
}
```
to
```
enumStr Action {
  EDIT,
  ADD,
  DELETE,
}
```
2. What shortcomings exist with current approaches?
answer: I need to repeat a literal for key and value

**Comment by MartinJohns** [comment]
Duplicate fo #16464.
