### ISSUE TITLE
default export in external modules vs. default export in ES6 modules

### ISSUE THREAD

**Issue by remojansen** [Microsoft/TypeScript#6060]
I have the following module in a file named `arrays.ts`:
```
///<reference path="../../interfaces.d.ts" />

class Arrays implements IArrays {

  // Returns the first element of an array. 
  // Passing n will return the first n elements of the array.
  // e.g. first([5, 4, 3, 2, 1], 3)
  public first<T>(array : Array<T>, n = 1) : Array<T> {
    var result = [];
    for(var i = 0;  i < n; i++) {
      var value = array[i];
      if(typeof value === "undefined"){
        return result;
      }
      result.push(array[i]);
    }
    return result;
  }

  // Returns the last element of an array. 
  // Passing n will return the last n elements of the array.
  // e.g. last([5, 4, 3, 2, 1], 3)
  public last<T>(array : Array<T>, n = 1) : Array<T> {
    return this.first(array.reverse(), n);
  }

}

var arrays = new Arrays();
export default arrays;
```

### import default export using ES6 syntax (Works as expected)
```
///<reference path="../../interfaces.d.ts" />

import arrays from "./arrays";

var VERSION = "1.0.0";

export { VERSION, arrays };
```

### import default export using external module syntax

When I import `arrays.ts` using the external module syntax `default` doesn't seems to work as I would expect because I have to use the following code to achieve the same behaviour than the preceding example (ES6 modules).

```
///<reference path="../../interfaces.d.ts" />

import _arrays = require("./arrays");

var VERSION = "1.0.0",
    arrays = _arrays.default; // ?

export { VERSION, arrays };
```
I'm using TS `1.8.0-dev.20151204`. The code is [here](https://github.com/remojansen/TsCookbook/tree/master/chapter_03/src/module_definitions/design_time/external) and the compilation tasks [here](https://github.com/remojansen/TsCookbook/blob/master/chapter_03/gulpfile.js#L70) and [here](https://github.com/remojansen/TsCookbook/blob/master/chapter_03/gulpfile.js#L154).

Thanks!

**Comment by DanielRosenwasser** [comment]
Hey @remojansen. `import foo from "bar" is not semantically equivalent to `import foo = require("bar")`. default exports should be thought of as exporting a member on the module named `default`. The concepts serve the same purpose, but the CommonJS defaulting mechanism was a bit of a hack.

**Comment by remojansen** [comment]
Thanks for clarifying it :) @DanielRosenwasser
