### ISSUE TITLE
Since 5.7.2: Using JSX fragments requires fragment factory 'React' to be in scope, but it could not be found.

### ISSUE THREAD

**Issue by RobertSandiford** [microsoft/TypeScript#60603]
### 🔎 Search Terms

Search/Keywords: Using JSX fragments requires fragment factory 'React' to be in scope, but it could not be found.

### 🕗 Version & Regression Information

Since 5.7.2. No 5.7.0 or 5.7.1 available. OK in 5.6.3

### ⏯ Playground Link

[Best effort Playground](https://www.typescriptlang.org/play/?ssl=13&ssc=60&pln=11&pc=1#code/JYWwDg9gTgLgBAbzgZVGANgUwMIXBAO0wPgF84AzKPOAchgFcCBzAZxmNrgHpu4YAnmEysAXHAAMAOgCMUgKwyAsAChVmAB6RYcAMboAhq1ZwAMhGbNMAEwDyDeJo4FrJ1OCy58REolVwAvUJneABeOAAKAEo4UIA+SP9A5IAeBN44AEk4VkxMfgALfOQAUWxbADkAEThMKGooOCKofOACOBABWoIAN2BqAhBiGCTksbgUgpk480sbOHsYFO4p9L5sqsraABUcvMLgEzqGuDaOruI+gaGSUbHluLuo1VJVVQzdAoMWNuY4beQcB6dVYwEI-AgQIUUgAbFIAMx7TAgEwwSGfb5WQr5ADu0Gsv3efAgFGxlH67Fq9WgkQIEHg31OxgYrXanW6V0INxgUQANHBvtYBehWBAiXAWiAIMDUUU4AAxKAGZjcqkNflGU7wawQESnNkXXr9LnDVRAA)

### 💻 Code

```ts
    <>
        <h1>Logged Out</h1>
    </>
```

### 🙁 Actual behavior

Since TS 5.7.2 JSX Fragments are no longer accepted.

Compile error:  error TS2879: Using JSX fragments requires fragment factory 'React' to be in scope, but it could not be found.

### 🙂 Expected behavior

JSX Fragments should continue to work

### Additional information about the issue

I have a custom JSX setup, I'm not using React. `babel-preset-react` is used to transform JSX. This grabs `Fragment` from the JSX runtime provided and passes this as the node type when creating the element via the JSX runtime. It has been working since TS 4 until now.

Compiled output:
```ts
import { jsx as _jsx, Fragment as _Fragment } from "tungsten/jsxRuntime.js";
...
    _jsx(_Fragment, {
        children: _jsx("h1", {
            children: "Logged Out"
        })
    })
```

The error message about React is odd, JSX and React are independent, why would React anything be needed to use JSX fragments? `babel-preset-react` with `runtime: "automatic"` loads jsx functions and the `Fragment` constant from a specified JSX runtime and does not rely on anything called `React`.

**Comment by iisaduan** [comment]
What JSX setting are you currently using in your tsconfig? The "requires `React` to be in scope" sounds like it could be hitting a default error message, so knowing your jsx setting would help me diagnose the issue

Since you are using a custom setup, the fix might be to specify `jsxFactoryFragment: null` as in #60122

**Comment by RobertSandiford** [comment]
@iisaduan
> What JSX setting are you currently using in your tsconfig? The "requires `React` to be in scope" sounds like it could be hitting a default error message, so knowing your jsx setting would help me diagnose the issue
> 
> Since you are using a custom setup, the fix might be to specify `jsxFactoryFragment: null` as in [#60122](https://github.com/microsoft/TypeScript/pull/60122)

It's just ` "jsx": "preserve"` as the JSX transform is a post-tsc build step.

It seems that with `"jsx": "preserve"` TS should not care about any JSX factories.

I've tried `"jsxFragmentFactory": null`, but it makes no difference.

Here is a new playground that now matches what I see in editor: [playground 2](https://www.typescriptlang.org/play/?jsx=1#code/JYWwDg9gTgLgBAbzgZVGANgUwMIXBAO0wPgF84AzKPOAchgFcCBzAZxmNrgHpu4YAnmEysAXHAAMAOgCMUgKwyAsAChVmAB6RYcAMboAhq1ZwAMhGbNMAEwDyDeJo4FrJ1OCy58REolVwAvUJneABeOAAKAEo4UIA+SP9A5IAeBN44AEk4VkxMfgALfOQAUWxbADkAEThMKGooOCKofOACOBABWoIAN2BqAhBiGCTksbgUgpk480sbOHsYFO4p9L5sqsraABUcvMLgEzqGuDaOruI+gaGSUbHluLuo1VJVVQzdAoMWNuY4beQcB6dVYwEI-AgQIUUgAbFIAMx7TAgEwwSGfb5WQr5ADu0Gsv3efAgFGxlH67Fq9WgkQIEHg31OxgYrXanW6V0INxgUQANHBvtYBehWBAiXAWiAIMDUUU4AAxKAGZjcqkNflGU7wawQESnNkXXr9LnDVRAA)

Thanks

**Comment by RobertSandiford** [comment]
@iisaduan Thanks
