### ISSUE TITLE
base64/hex methods missing from `Uint8Array`

### ISSUE THREAD

**Issue by printfn** [microsoft/TypeScript#60612]
### ⚙ Compilation target

ESNext

### ⚙ Library

ESNext

### Missing / Incorrect Definition

[`Uint8Array.fromBase64()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/fromBase64)
[`Uint8Array.fromHex()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/fromHex)
[`Uint8Array.prototype.setFromBase64()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/setFromBase64)
[`Uint8Array.prototype.setFromHex()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/setFromHex)
[`Uint8Array.prototype.toBase64()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toBase64)
[`Uint8Array.prototype.toHex()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toHex)

These functions are implemented in stable Firefox and in the Safari Technology Preview.

### Sample Code

```TypeScript
new TextEncoder().encode('Hello World').toBase64()
// "SGVsbG8gV29ybGQ="
```

### Documentation Link

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toBase64

https://github.com/tc39/proposal-arraybuffer-base64

**Comment by RyanCavanaugh** [comment]
Yeah, you'll have to wait for this to be widely-supported first. Please open a new issue at that time

**Comment by joakim** [comment]
I'll just add a simple workaround until it's widely supported. In `global.d.ts`, add:

```ts
declare global {
  interface Uint8ArrayConstructor {
    fromBase64: (base64: string) => Uint8Array
    fromHex: (hex: string) => Uint8Array
  }

  interface Uint8Array {
    toBase64: () => string
    toHex: () => string
  }
}
```

**Comment by aryzing** [comment]
Seems it's now [available in two major engines](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/toHex#browser_compatibility) no? Bun supports this too.

**Comment by joakim** [comment]
@aryzing Still not in V8, see [this issue](https://issues.chromium.org/issues/42204568). I think we'll have to wait for that, as it covers most of the runtimes.

**Comment by dontwanttothink** [comment]
This feature is supported in Bun, Deno, Firefox, Safari, and others. It has exceeded the threshold for inclusion that exists for DOM APIs. It should be added.
