### ISSUE TITLE
Documentation on TypeScript 1.7/1.8

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6061]
Currently were are at the verge of TypeScript 1.8, but the documentation (handbook and language spec) don't even comprehensively document TypeScript *1.5*.

How are we supposed to use the new features if only obsolete documentation is available?

Please finalize the documentation and add a title to it stating the version it fully describes.

**Comment by johnfn** [comment]
This is a very good resource in the meantime: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript

**Comment by DanielRosenwasser** [comment]
We're working on it. A more up-to-date version of the handbook is on https://github.com/Microsoft/TypeScript-Handbook.

**Comment by JKillian** [comment]
:+1:  Glad to hear a new handbook is coming! It seems possible to find up-to-date info right now, but you often have to hunt around in the GitHub issues or other places to find it.

**Comment by DanielRosenwasser** [comment]
Yeah, I'm deeply sorry that this has become a problem, but we've been working on it. I'm hoping to get the new handbook content published by the end of the month.

**Comment by SetTrend** [comment]
@DanielRosenwasser:

Thanks. Excellent! I'm very much looking forward to it.
<br/>
@johnfn :

Thanks for pointing. Yet, I believe it's important for users and learners to have *one single* place of truth; reference material with a good structure and a sufficiently detailed TOC is required to quickly and easily lookup a language feature when a question arises during development. Or even to browse the TOC for ideas on how things may be solved by a language feature., For instance

 * Data Types
   * number
   * string
   * void
   * Tuples
   * Unions
   * ...

Particularly the new module syntax and the AtScript part are crucial to the new version of the language.

It can not be the intention of the creators of such great language to have developers around the globe stop their work every time a question comes up and cumb through a plethora of 3rd party information.
