### ISSUE TITLE
Incorrectly validates interface implementation

### ISSUE THREAD

**Issue by ThomasHillLF** [microsoft/TypeScript#60625]
### 🔎 Search Terms

"interface", "validation"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about interface implementation
- Maybe is explained by: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgJIBUIGczIN4BQyxyA7gPZQDWWAFAJQBcyAbucACYDcBAvgQVCRYiFKgDC5EFgCuAW2j4iJAOblakHMwzYwTVu258BQ6PCRpMOAKIAPSCA4QOyCPYiOsl3UpLIARlDkVB4MzGycPPwEAPQxyFgAFuQyADYuIOS4-ihw-qkoYOTIcnAhyGCJwF5wWFjAKiAK4AQIUjjIbdLy0NqS3QpQyAC8vqrqmmDaVmB2Dk4c9PjIcd4dSSnpyJnZuXUNIHkFFcU6Nu6Ozsp+xJMAdIHBofQ8fvzRXbKDd2q0eLwvAhAA

### 💻 Code

```ts
interface ITest {
    works(): void;
}

interface IConsumer {
    go(test: ITest): void;
}

interface ITestExtended extends ITest {
    broken(): void;
}

// should not be able to make this assignment
const consumer: IConsumer = {
    go(test: ITestExtended) { // ITest should not be assignable to ITestExtended
        test.broken();
    }
}

consumer.go({}); // throws "test.broken is not a function"
```

### 🙁 Actual behavior

Allows assignment of object to `IConsumer`.

### 🙂 Expected behavior

Should not allow the assignment. `ITestExtended` is assignable to `ITest` but I think that the type check should be the other way around, i.e. it should be checking that `ITest` is assignable to `ITestExtended`. If this same code is implemented in Java then if you have an implementer for an interface method whose signature differs at all, it will throw a compilation error.

**Comment by MartinJohns** [comment]
This is working as intended. Numerous issues about it, and also mentioned in the FAQ: https://github.com/microsoft/typescript/wiki/faq#why-method-bivariance
