### ISSUE TITLE
listFiles[Only] does not list upstream package.json files whose exports were used for path resolution

### ISSUE THREAD

**Issue by ddurschlag** [microsoft/TypeScript#60629]
### 🔎 Search Terms

listFiles listFilesOnly package.json exports

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about listFiles

I tried 3.9.5 which also doesn't list the upstream package.json (though it actually doesn't list the .d.ts file either, so that's even worse).

### ⏯ Playground Link

https://github.com/ddurschlag/typescript-listFiles-demo/

### 💻 Code

When doing a bare import:

```ts
import { sayHello } from 'upstream';
```

...if the upstream module's exports are specified in the package.json:

```
  "exports": {
    ".": "./dist/specific_name.js",
    "./*": "./dist/*"
  }
```

tsc's listFiles and listFilesOnly features do not list this package.json. This is problematic for, e.g., detecting if the project has changed such that a rebuild may be required.

### 🙁 Actual behavior

Upstream package.json was not listed in the file output.

### 🙂 Expected behavior

Upstream package.json is listed in the file output.

**Comment by RyanCavanaugh** [comment]
`listFiles` shows the source files we'd use for compilation, not the complete list of files on disk we consulted. A correct list for detecting rebuilds would be much be longer than just including `package.json` files -- it'd include many probes for non-existing files, etc..

**Comment by ddurschlag** [comment]
So is there any way to get a list of files whose update should trigger a rebuild, @RyanCavanaugh ? Let's say, to make it easier, I'm ok with not including "files that could force a rebuild by coming into existence," since I understand that list could potentially be extremely lengthy.

**Comment by RyanCavanaugh** [comment]
There isn't a user-facing way to get that info. You'd need to use the compiler API and provide a file system host to intercept the I/O calls to see what parts of the fs are being looked at.

**Comment by Andarist** [comment]
I'm not sure what's the OP's use case but maybe `--traceResolution` could be used for this. By scanning its output you could learn about every file used to determine the resolution.
