### ISSUE TITLE
How to initialize string[] & {d: string} ?

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript#60639]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

The first line is valid.  The second is not, because `c.d` must be initialized right away. 
```typescript
let a:(string[] & {b?: string}) = []
let c:(string[] & {d: string}) = []
```
How can I initialize `c` to its correct type?

**Comment by MartinJohns** [comment]
`Object.assign`. Questions like this are better suited for sites like StackOverflow or the Discord.
