### ISSUE TITLE
`override` isn't required in ambient contexts with `noImplicitOverride`

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript#60635]
### 🔎 Search Terms

override ambient type declaration class dts noImplicitOverride

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://www.typescriptlang.org/play/?noImplicitOverride=true&ts=5.8.0-dev.20241128&ssl=15&ssc=2&pln=1&pc=1#code/PTAEAEDsHsEkFsAOAbAlgY1QFwPIDcBTAJyNQBMCAuULIgVwIChGL1kBDIg0N9gZz6gAQv24BvRqFAAjapDrxpxANyMAvs1YcuPDgNAARYqkJlQBAB5YCkMoJF9xkmXIVKiqjSwK8dvfQ4EAEygYl5anNz+gkakpiGW1rb2oiESUtCEJOTcsqDyiirqjEA

### 💻 Code

```ts
// @noImplicitOverride: true

declare class Base {
  b: number;
}

declare class Derived extends Base {
  b: number; // no error
}

declare class Base2 {}

declare class Derived2 extends Base2 {
  override b: number; // error
}
```

### 🙁 Actual behavior

A property in a derived class in ambient context doesn't have to have `override` modifier with `noImplicitOverride`. `override` is still checked when present though.

### 🙂 Expected behavior

It feels slightly inconsistent. I couldn't find any note about this in the docs and I had to look into the source code and dig up the PR that implemented `override` to check if it's a bug or not.

### Additional information about the issue

I believe this works like that since `noImplicitOverride` was introduced in https://github.com/microsoft/TypeScript/pull/39669 in 4.3: [TS playground](https://www.typescriptlang.org/play/?noImplicitOverride=true&ts=4.3.5#code/PTAEAEDsHsEkFsAOAbAlgY1QFwPIDcBTAJyNQBMCAuULIgVwIChGL1kBDIg0N9gZz6gAQv24BvRqFAAjapDrxpxANyMAvs1YcuPDgNAARYqkJlQBAB5YCkMoJF9xkmXIVKiqjSwK8dvfQ4EAEygYl5anNz+gkakpiGW1rb2oiESUtCEJOTcsqDyiirqjEA)

**Comment by whzx5byb** [comment]
Seems like there was a decision:

>     - Should this apply to declaration files?
>       - Argument for yes: correctness for the same reason
>       - Argument for no: convenience, no need to mess with declaration emitter
>       - If no: Declaration emitter will need to emit `override` modifier (same way `any` works) if one was not present explicitly
>       - Decision: Not enforced

 _Originally posted by @RyanCavanaugh in [#9034](https://github.com/microsoft/TypeScript/issues/9034#issuecomment-224763350)_
