### ISSUE TITLE
No auto import suggestions for react-icons

### ISSUE THREAD

**Issue by devinjohw** [microsoft/TypeScript#60659]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: macOS 14.6.1

Steps to Reproduce:

1. run `npm init` to init a basic npm projct
2. create jsconfig.json file
3. add react-icons, with `npm install react-icons`
4. create a jsx file called Comp.jsx
5. attempt to add a icon like `<MdDashboard />`, you will find the auto import suggestion doesn't work. While if you remove jsconfig.json file, it works.

**Comment by RyanCavanaugh** [comment]
This is an intended behavior of configured projects (which only load the implied input files plus auto-imports from package.json) vs inferred projects (which load nearly everything).

**Comment by devinjohw** [comment]
> This is an intended behavior of configured projects (which only load the implied input files plus auto-imports from package.json) vs inferred projects (which load nearly everything).

How should I configure this behavior? 😊
