### ISSUE TITLE
TS allows the assign an object to a more specific type (Record<string, T>), which can cause a runtime error

### ISSUE THREAD

**Issue by tomasz-fijalkowski-monday** [microsoft/TypeScript#60657]
### 🔍 Search Terms

"Record type", "assign an object to record", "undefined values in Record"

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

Let's define
```
type User = { name: string };
const user = { name: 'User 1' };
```
Now, consider five ways of playing with this.

### 1. Using implicit types (Correct TS behavior)
```
const v1 = { a: user };
console.log(v1.a.name);
console.log(v1.b.name); // TS2339: Property b does not exist on type { a: { name: string; }; }
```

### 2. Assign object to specific Record (Correct TS behavior)
```
const v2: Record<'a', User> = { a: user };
console.log(v2.a.name);
console.log(v2.b.name); // TS2339: Property b does not exist on type Record<'a', User>
```

### 3. Assign object to over-specific Record (Correct TS behavior)
```
const v3: Record<'a' | 'b', User> = { a: user }; // TS2741: Property b is missing in type { a: { name: string; }; } but required in type Record<'b' | 'a', User>
console.log(v3.a.name);
console.log(v3.b.name); // No TS error, but error on declaring v3
```

### 4. Assign object to string key Record (**Incorrect TS behavior**)
```
const v4: Record<string, User> = { a: user };
console.log(v4.a.name);
console.log(v4.b.name); // No TS error, but runtime error v4.b is undefined
```
`Record<string, User>` means that there is a defined value for any string key. **TS doesn't raise an error, which leads to runtime issues.**

### 5. Assign object to string key Record but with undefinedable values (Correct TS behavior)
```
const v5: Record<string, User | undefined> = { a: user };
console.log(v5.a.name); // TS18048: v5.a is possibly undefined
console.log(v5.b.name); // TS18048: v5.b is possibly undefined
```
TS allows access to any record key, but developers must handle undefined.

## Summary
TS protects developers in cases 1, 2, 3, and 5. However, in case 4 TS does not protect against bugs.

### 4. Assign object to string key Record (**Incorrect TS behavior**)
```
const v4: Record<string, User> = { a: user };
console.log(v4.a.name);
console.log(v4.b.name); // No TS error, but runtime error v4.b is undefined
```
`Record<string, User>` means that there is a defined value for any string key. **TS doesn't raise an error, which leads to runtime issues**.
TS should not allow `const v4: Record<string, User> = { a: user };`. Allowed options could be
1. `const v2: Record<'a', User> = { a: user };` or
2. Record<string, User | undefined> = { a: user };
What prevents runtime errors?

There could be an introduced config flag, so the change can be backward compatible.

### 💻 Use Cases

1. Pervent runtime errors what object is assigned to Record with string type key

**Comment by MartinJohns** [comment]
This is working as intended and what the compiler option `noUncheckedIndexedAccess` is for.

**Comment by tomasz-fijalkowski-monday** [comment]
wow, I did not know the `noUncheckedIndexedAccess` flag. Very useful, thanks!
