### ISSUE TITLE
Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptProjectPropertyPage.resources

### ISSUE THREAD

**Issue by xielongjiang** [Microsoft/TypeScript#6065]
Right click on the project and go to the properties. Then select “TypeScript Build” tab Tip this error

尝试加载该页时出错。
未能找到任何适合于指定的区域性或非特定区域性的资源。请确保在编译时已将“Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptProjectPropertyPage.resources”正确嵌入或链接到程序集“Microsoft.VisualStudio.LanguageServices.TypeScript”，或者确保所有需要的附属程序集都可加载并已进行了完全签名。

**Comment by DanielRosenwasser** [comment]
Translated:

> Error trying to load the page. Could not find any suitable resource for the specified culture or a neutral culture. Please ensure at compile time will "Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptProjectPropertyPage.resources" correctly embedded or linked assemblies "Microsoft.VisualStudio.LanguageServices.TypeScript", Or ensure that all satellite assemblies can be loaded and has been fully signed.

**Comment by DanielRosenwasser** [comment]
@xielongjiang what version of TypeScript are you using?

**Comment by paulvanbrenk** [comment]
@xielongjiang and which version of VS? Can you post the image in 'Help->About'

**Comment by xielongjiang** [comment]
@DanielRosenwasser @paulvanbrenk  This Error in Visual Studio 2015 update1. I using 'Typescript Tools for Microfot Visual Studio 2015 1.7.40' found this error.When it comes to this error, I try take this version relegation to the latest 1.6. But unfortunately, this makes Visual Studio unable to work properly.
I thought it would be a problem with the Visual Studio 2015 update1,but the truth tells me,there are 2015 versions of this problem.

**Comment by paulvanbrenk** [comment]
Yes, the only version of TypeScript that works with Visual Studio 2015 Update 1 is TypeScript 1.7. 

Can you try a repair of Visual Studio?

Do the rest of the TypeScript features work, like colorization in a .ts file and IntelliSense?

**Comment by xielongjiang** [comment]
@paulvanbrenk 
I've tried many times to repair operation, but sorry to tell you, this does not effect. I guess this is after the Visual Studio 2015 RTM has been existing problems.

**Comment by paulvanbrenk** [comment]
Where did you install TS 1.7.4 from?

**Comment by xielongjiang** [comment]
@paulvanbrenk  http://www.typescriptlang.org/

**Comment by cyj100** [comment]
I have this error too.
I using latest typescript and visual studio 2015 update1.
I want and AMD, but now I can't.

**Comment by nova-qiang** [comment]
I have the error, maybe it is caused by chinese resource file?

**Comment by cyj100** [comment]
Every computer here have the error. 
so "LanguageServices" give the clue.

**Comment by paulvanbrenk** [comment]
Trying to reproduce, but can you try the 1.7.6 version from here [0]. Note: this does require Visual Studio 2015 Update 1.

[0] https://www.microsoft.com/en-us/download/details.aspx?id=48593

**Comment by nova-qiang** [comment]
@paulvanbrenk thanks for your suggestion, but the error is still not solved.

**Comment by xielongjiang** [comment]
@paulvanbrenk I try to use you to download address.but the error is still not solved.

**Comment by h82258652** [comment]
same problem with 1.7.6 version.
maybe missing some resources?

**Comment by paulvanbrenk** [comment]
I have a repro and a fix, I'll let you know when we'll be able to patch this.

**Comment by cyj100** [comment]
but now, what can I do if I want comile with AMD moudle?
Have to wait for Typescript 1.8?

**Comment by DanielRosenwasser** [comment]
For now you can either create a [`tsconfig.json`](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) file that sets your compile options, or temporarily switch the language to English (or something else you're familiar with).

@paulvanbrenk might know another workaround.

**Comment by nova-qiang** [comment]
@DanielRosenwasser Could you please explain how to switch the language to English? If you mean installing an English version, yes , I have selected the English version when upgrading to 1.7.6.

**Comment by cyj100** [comment]
I put tsconfig.json file there, and still get the TS1148 error. 
I have to use command line tsc.exe to compile the project.

**Comment by xielongjiang** [comment]
@cyj100 Luckily, I have the same situation with you

**Comment by paulvanbrenk** [comment]
You can change the language here:

![image](https://cloud.githubusercontent.com/assets/5273975/11939078/5425f3ca-a7d4-11e5-9552-659259b47af0.png)

Or edit the project file, using the items described here:

https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects

**Comment by cyj100** [comment]
Thank you very much.
I have try to add option in project file  .csproj:
<TypeScriptModuleKind>AMD</TypeScriptModuleKind>
but still get compile error.

**Comment by paulvanbrenk** [comment]
Can you share the contents of the project file and the compiler error you're seeing?

**Comment by nova-qiang** [comment]
@cyj100 I have tried the solution (https://github.com/Microsoft/TypeScript/issues/4300), it works.

**Comment by cyj100** [comment]
![tsc-module](https://cloud.githubusercontent.com/assets/222300/11945778/59381b3a-a88e-11e5-9ba6-bc7c0271542f.png)

and the point.ts file:

<pre>
/// <reference path="../arcgis-js-api.d.ts"/>
import AGSPoint = require("esri/geometry/Point");
export = Point;
class Point extends AGSPoint {
  log() {
    console.log(this.type, this.x, this.y);
  }
}
</pre>

**Comment by paulvanbrenk** [comment]
And the project file?

**Comment by nova-qiang** [comment]
Yes, after I have installed the English package for VS, the problem is solved. @paulvanbrenk Thank you very much.

**Comment by cyj100** [comment]
I  change vs2015 to English version, and find the AMD option is there checked.  compile it still get error.
So I change the module option to CommonJS, then compile correctly.  Now I change back to AMD,It's work.
Maybe something wrong in my project file, but now I think the file is changed. so I don't upload it.
Thanks!

**Comment by cyj100** [comment]
but now, all Chinese in .ts compile to .js be messy code like these:
��Ҫ˵�������ͼ�õ���4490����Ϊϵͳ�ںܶ�ط�ȱʡ�Ķ���4326������������������4490�Ļ��ᵼ������

**Comment by ArvinHsieh** [comment]
I also have the same problem. It occurred in VS 2015 and VS 2015 Update1. using TypeScript 1.6 - 1.76.
Below...
![vserror](https://cloud.githubusercontent.com/assets/4669056/11978527/36ba9670-a9c7-11e5-8c4c-9f848bff66f9.png)

My VS 2015 is used in Traditional Chinese Language. But i change the English language after normal..
Below..
![vserror2](https://cloud.githubusercontent.com/assets/4669056/11978637/0d71181a-a9c8-11e5-9c5a-41a9d5e8a40d.png)

**Comment by mhegazy** [comment]
The fix should be included in the next public TypeScript release.
