### ISSUE TITLE
JS export missing value when using unique symbols in declared namespaces

### ISSUE THREAD

**Issue by kristiannotari** [microsoft/TypeScript#60668]
### 🔎 Search Terms

export, missing, unique symbol, declare namespace

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about namespaces and unique symbols

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.2#code/KYDwDg9gTgLgBAbzgQTgQwM5wCrAzAfVQF8AoU0SWOAE2AGMAbNKYOAOzQFs8w162qBKTii49CO3xwARgC44AV3YBLAI6K2GAJ5cZERqTIVw0eBKnw0cALxwARBgg8YACxXsA5vaA

### 💻 Code

When writing the following code, where you declare a namespace and put a unique symbol in there, maybe to use it as a type for properties of other types and interfaces inside such namespace, and you export the namespace without explicitly saying it's `export type`, you get a value export in the resulting js, after using `tsc`. Such export refers to a value which is not there, since the namespace is only declared.

```ts
export { A as Test_A }

export declare namespace A {
    const b: unique symbol
}

export const a = "something"
```

### 🙁 Actual behavior

```js
export { A as Test_A }; // ❌ this should not be here, at least I didn't expect it to be here
export const a = "something";
```

### 🙂 Expected behavior

```js
// no export for A or A_Test
export const a = "something";
```

If you use `export type` no js export is produced. It would be great to have a compile time error or some kind of indication when you try to export a declared namespace, which can't produce a js value, suggesting to use `type` in the export or something similar.

### Additional information about the issue

I tried on the playground with versions 5.5.4 and 5.7.2, but I guess the same problem can be found in every recent typescript version.

**Comment by kristiannotari** [comment]
Using `unique symbol` in this issue was indeed a little misleading by me. Now I understood that the "issue" occurs when expressing that the `A` namespace has a value inside.

Thing is: if you write down the export and don't put something at the value level inside the namespace `A`, the produced `js` doesn't have any export. As soon as you add a value, it does have such export. I found that strange, at least, but maybe that's me not understanding correctly the role of typescript here.

So given the following ts:
```ts
// ts
export { A as Test_A }

export declare namespace A {
    const b: string // having this here makes typescript decide it has to generate an export in the js
}

export const a = "something"
```
it generates the following js:
```js
// js
export { A as Test_A };
export const a = "something";
```
But if you don't explicitly says what's value is inside `A`, but just declare things at the type level, it doesn't:
```ts
// ts
export { A as Test_A }

export declare namespace A {
    type b = string
}

export const a = "something"
```
then no export in the generated js:
```js
// js
export const a = "something";
```

As a side note: if I don't want to declare that an `A` object exists, but would like to have a namespaced representation of my types (eg. accessing as `My.Type.Namespace`), optionally using `unique symbol`s to make them unique at the type level, I should really not use namespace as that's not their goal, or at least, be prepared that this "export" issue (I keep saying issue in the sense it produced broken code for me as it was trying to export a thing which didn't existed at runtime, but that's just my use case where I misunderstood the use of namespaces) could happen if I forget to add `type` to my `export` as in `export type { ... }`, right?

**Comment by RyanCavanaugh** [comment]
> As soon as you add a value, it does have such export. I found that strange, at least, but maybe that's me not understanding correctly the role of typescript here.

```ts
export declare namespace A {
    const b: string
}
```
*what you are saying* is that there is a value `A` with a property `b` in it, so TypeScript believes you and generates the corresponding `export { A as Test_A }` line, which is the correct thing to do if that value exists (which you said it did). It would be incorrect to *not* have this line, because you told TS to export `A`, and said that there's a value `A` to export.

> ..., right?

Basically? The rule is "don't make false statements to the compiler". You can write `namespace A { type b = string }` because that doesn't imply the existence of any `b` value.

If you're going to use `unique symbol` you'll really need an actual `const` somewhere, otherwise you will in one way or another be declaring a value that doesn't actually exist and open yourself up to problems later.
