### ISSUE TITLE
Declare a module must satisfy a given type

### ISSUE THREAD

**Issue by nfroidure** [microsoft/TypeScript#60667]
### 🔍 Search Terms

I'd like for in a framework to be able to guide users while they create some standard components.

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

It could be something like:
```ts
declare module 'src/commands/*.ts' satifies/extends {
  name: string;
  definition: CommandDefinition;
  default: Command;
}
```

When editing the module, users will have typescript errors until the module is validating the types declares.

### 📃 Motivating Example

Improving the developer experience is a major issue for framework authors, I think it would significantly improve framework usages. I need it for helping users [declaring handlers](https://github.com/nfroidure/whook/blob/main/packages/whook-example/src/handlers/getTime.ts) that will always have the same shape but I think frameworks like NextJS/React etc... would benefit from it too.

### 💻 Use Cases

1. What do you want to use this for? Developer experience
2. What shortcomings exist with current approaches?
Currently the only way I know to do this is to use satisfies for each export of each module which relies on developers attention and is error prone:
```
export const x ... satifies MyModuleType[x];
export const y ... satifies MyModuleType[y];
```
3. What workarounds are you using in the meantime?
There is no alternative atm afaik.

**Comment by MartinJohns** [comment]
Duplicate of #38511.

**Comment by nfroidure** [comment]
Thanks @MartinJohns closing then and commenting there ;)
