### ISSUE TITLE
Type hinting on Generic union type callback is broken in 1 of the 2 union options

### ISSUE THREAD

**Issue by Brocktho** [microsoft/TypeScript#60671]
🔎 Search Terms
generic
function union types

🕗 Version & Regression Information
Not sure when but I believe this was previously working earlier in Typescript 5

⏯ Playground Link
https://www.typescriptlang.org/play/?#code/FAUwHgDg9gTgLgAjgTwiBBZAhhAIluLABRiggGcAeAFQXDhADsATchAQRhi2UoFdGAa0ZQA7owB8EhAF4EAb2AIEAYwAWASwA2zGEwBcCABRGAbli18Qh6gG1GfALYAjEDAC6ASlnTycGBqMAObeAD7GZhZWNvZOrh4ANAiBzOCGDi5u3jK+-oEhANxKCMwEWDZFygBmFlrOWCqCAPyGRtm5AcFFAL5FwCpQjH4IuCA1fFpwAGK19Y2yxu3GxcoARGogWlpQq8CefeDQ8CVjWBOIVQIqcBqDmDj4hDR0YAwsbJzcvALCYpISRkUynU2l0TASxVKhAh1VmDUEC1G40mMy2c0EEO6hmweDKJDIVGoEm8QOSVSMUKwshkcgEqSqgRAzG8ejgfBgjAQNTR8MqCGKGiqxkpADotEwgnA1NS5AAGEkrBCs9mc7l1eFtPndYDFZUckplEWOHBGEE6PSMfbAbXAS6Ma63TnUEB+HGPLBtUkDIaIBh+d0LWyK+QaZiGACM3RhygUocMACYo8G4wgAMza5TuPrKRUAelzCAAwlhOYwQKY3MlGFU3EwVOgpegGTBhgJHcVvcNAjWLfXcFAXYw4AB1WAIuRusqAxXKSmGP1wd3RmOqTTmgzGDQMRxLAAGABIQ9uRaHurvFd1PHmC8XOd3a-aGxsEOQQN7mAg24MO4Mu9WH-Wo4wIIbATg8U6kiuc5IC6i5lMuMZmmCjCtFuICOAkAD6e6HmhjgnswZ4XleOY2vmHAIKIY4IFgpB0ggZA3IM+g6qAkCwL6qDoJOhD4hQADK+Tis89BMKwHBcDw-BCCI4hSAsXprshrTmJY1gIHYGTxF4PgvnkwSQmUFTFGq6ItIsul+J0QQ9Ac7HHCgaD3LivGkBQACSLDgCJrxiR8knfDJfzyXIimghaKlROpmlxG47hJCkaQIFpWSWfpNmGYQxmwjyjTmW0aXWT0OqHBxXJXExnI4kBgicFAdKCcEwm0KJ7wSV80m-HJAJheujDRpS0amfCiKnOcqLqo0mLYuBrkEo1QTNcSCgCuSlIyp+XkMmWzJKiAbL6sNjR8qtwqGuKwRSht8orSueqqnCjSasUNrKPdBqEEaJpIRaVo2qVxx2g6dzVWOdV0p5qRgD5bziZ8Uk-LJ-zTsCSkWgN8EmY944jGNKLY9Nznunx5CQ95RIKsogoUmUG10mMjK7e9R2CCdVNCjTn0XZK0o0nKlMxsz2PPcor17QdnKisaECmmjTB-TqQOVRpsE1eDLCej+Powf6tNyEGK4hmGCCRghRsJkmhspumxRZjqOYruRABCUBXfevYupR1GyQgzh8IgZZMgg8YIKszCCj2TBwKsySOBA4qOFHBCOuQWvDOQQkgJ5kePjVoHOWrdEsAt4ooyuH3lDrcHQjOq7hRuRh4ThR7oQRRErpeaeIIlYDZwBIB5wsoPAerzBk2AZdQUZVdLrXP0N3hWHN3hbfnh3JH8t0QA

💻 Code
```ts
export type MapDataProps<T extends Array<unknown>> = {
  children: ((value: T[number]) => string) | ((value: T[number], index: number) => string);
  data: T;
  fallback?: () => string;
};

const DefaultFallback = () => (
    "hello"
);

export default function MapData<T extends Array<unknown>>({
  children,
  data,
  fallback = DefaultFallback,
}: MapDataProps<T>) {
  if(data === undefined) return fallback;
  
  if (data.length === 0) {
    return fallback();
  }

  return data.map(children);
}

function TestMapData(){
  const testData = [
    {id: 1},
    {id: 2},
    {id: 3}
  ];

  
    // Can never inference the single parameter function of the union
  const inferenceDoesntWork = MapData({
      data: testData,
      children: (item) => `${item.id}`
    })
    // Can inference the second union with two parameters
  const inferenceWorks = MapData({
      data: testData,
      children: (item,__) => `${item.id}`
    })
  
}
```
🙁 Actual behavior
This line fails inference:
```ts
children: (item) => `${item.id}`
```
saying the type of item cannot be inferred from outside usage despite being a fairly trivial case.
🙂 Expected behavior
Inference should work on the single argument function as well as the two argument function with unused parameter. I'm unsure of why the two argument case just works out of the box. Maybe a skill issue here but would love to know a solution outside of the one I have in the playground link.

**Comment by RyanCavanaugh** [comment]
There's no need for the union on `children` here; you can just write
```ts
export type MapDataProps<T extends Array<unknown>> = {
  children: (value: T[number], index: number) => string;
  data: T;
  fallback?: () => string;
};
```
and everything works as hoped-for.
