### ISSUE TITLE
Destructuring in declarations and assignments - really an improvement to language?

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6067]
Am I the only one to believe that the language feature of destructuring in declarations and assignments rather adds confusion to source code than being a valuable addition?

I have a very hard time reading code examples using destructuring. To me the syntax is in no way self-explanatory or intuitive. The only benefit I apprehend is to avoid accessing properties in property syntax or arrays in array syntax - which I don't even tend to believe being a benefit as there usually is a semantical reason for grouping values in classes or arrays.

I would rather see this feature deprecated.

... other opinions?

**Comment by sandersn** [comment]
Destructuring is an EcmaScript feature, so it is not up to Typescript to decide what to do with it.
