### ISSUE TITLE
Organize imports should not move bare imports / side effect imports

### ISSUE THREAD

**Issue by golopot** [microsoft/TypeScript#60688]
### 🔎 Search Terms

"organize imports", "bare import", "side effect import"

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________

### 💻 Code

```ts
import './instrument';
import {a} from  'a';
a()
```

### 🙁 Actual behavior

Organize imports moves the bare import:

```ts
import { a } from 'a';
import './instrument';
a()
```

### 🙂 Expected behavior

Organize imports should not move `import './instrument';`

**Rationale:**
This order is important because the `./instrument` contains codes that must be executed before any other codes.

It is safe to assume that bare imports contains side effects, and side effects often requires an specific order of execution, so there is a good chance moving bare imports break people's code.

**Comment by jakebailey** [comment]
If you use groups, organize imports will not reorder them.


```ts
import './instrument';

import {a} from  'a';
a()
```

(I would also suggest using a linter with group support to enforce this sort of thing, like `eslint-plugin-simple-import-sort` or similar.)

**Comment by golopot** [comment]
Thanks, adding a comment below also prevents reordering:

```ts
import './instrument';
// ./instrument must be imported first
import {a} from  'a';
a()
```
