### ISSUE TITLE
Getting element of array is always defined, while it might be undefined

### ISSUE THREAD

**Issue by deser** [microsoft/TypeScript#60719]
### 🔎 Search Terms

Number , array

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because ___x____

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAhgLhmArgWwEYFMBOBtAXRgF4ZCAoS0SWDE+PABgKvAhABssA6DkAcwAUGAJRA

### 💻 Code

```ts
const a: number[] = []


const b = a[0]

console.log(b)
```
![Image](https://github.com/user-attachments/assets/7e721ecf-8dcb-45d1-b906-95d7cc5016c1)

### 🙁 Actual behavior

`b` get type `number`

### 🙂 Expected behavior

`b` get type `number | undefined`

**Comment by MartinJohns** [comment]
This is working as intended. You have to enable [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess).

**Comment by deser** [comment]
ah, ok, thx
