### ISSUE TITLE
Suppressing one function argument error suppresses them all

### ISSUE THREAD

**Issue by timmyichen** [microsoft/TypeScript#60731]
### 🔎 Search Terms

function argument typecheck error ignore ts-ignore ts-expect-error

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about ts-expect-error

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAZgVzMGBeGAKAhgJwOYBcM0OAlmHgJRFgIC2ARgKY5oB8MA3gFAx8w4mUBDjAwAjAG5uAX27dEyDL37iANCr4B6LTAACUCAFomADwAOTYFBM4cIHJpgAiLBAAmcZxsrcgA

### 💻 Code

```ts
const func = (arg: string): number => {
    return 1;
}

func(
    1,
    // @ts-expect-error
    "asdf",
)
```

### 🙁 Actual behavior

No type errors raised

### 🙂 Expected behavior

I'd expect the type error evaluation to move onto the first argument (as it does if you remove the second argument and the ts-expect-error), as the first argument to `func` is not valid.

### Additional information about the issue

This is unexpected to me since in the [3.9 docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html) introducing ts-expect-error:

> When a line is preceded by a `// @ts-expect-error` comment, TypeScript will suppress that error from being reported; but if there’s no error, TypeScript will report that `// @ts-expect-error` wasn’t necessary.

But here, it suppresses the error on the next line, as well as related errors.  I'm not sure if "related" is the right term here - dependent?  Has to do with the order in which TS evaluates errors for function arguments, but I'm also not sure if this is just expected behavior.

Using `ts-ignore` results in the same outcome.

**Comment by MartinJohns** [comment]
I'd call this a duplicate of #47551.

**Comment by timmyichen** [comment]
Thanks for finding that - happy to close this with that explanation.
