### ISSUE TITLE
The import attributes should be preserved in .d.ts.

### ISSUE THREAD

**Issue by NWYLZW** [microsoft/TypeScript#60736]
### 🔎 Search Terms

"import attributes", "import assert", "import with"

### 🕗 Version & Regression Information

- This changed between versions 4.0 and latest
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBAbzgVwM7AMowIY2HAXzgDMoIBbOAcimGwGMYq4B3ASxgAtFrbUIANshhsIAOwC05CABNgVAFzVpM5APmEAUJtCRYceuNTwkaYAGFsAgQCMGAa0JwAvHGwtsHOG3J6YACho6RioAGh52LiUkIP4hEXEpWXklIIBHZDZaZiICAEpNIA

### 💻 Code

```ts
export { useState } from 'react' with { 'resolution-mode': 'module' }

export const { useCallback } = await import('react', { with: { 'resolution-mode': 'require' } })
```

### 🙁 Actual behavior

`.d.ts`
```ts
export { useState } from 'react';
export declare const useCallback: typeof import("react").useCallback;
```

### 🙂 Expected behavior

`.d.ts`
```
export { useState } from 'react' with { 'resolution-mode': 'module' };
export declare const useCallback: typeof import("react", { with: { 'resolution-mode': 'require' } }).useCallback;
```

**Comment by Jack-Works** [comment]
TypeScript is correct in the examples you have given.

```ts
export { useState } from 'react' with { 'resolution-mode': 'module' }
export const { useCallback } = await import('react', { with: { 'resolution-mode': 'require' } })
```

resolution-mode is a type-level feature that will not affect the actual module resolution, thus those attributes will not be used nor emitted in the `.d.ts` file.

**Comment by RyanCavanaugh** [comment]
Jack-Works is correct

**Comment by NWYLZW** [comment]
@RyanCavanaugh

In fact, I am using the API of TypeScript to do some work. For example, I use the emit method to obtain the generated dts file. At this time, when I need the attribute-related descriptions of the corresponding import statement, I cannot obtain them. I can only obtain them through some tricky methods, such as using sourcemap to restore the attributes of the corresponding import statement. But I don't think this is a good thing. We can see that in other compilation tools of TypeScript, such as esbuild and swc, they all provide related APIs:
 - esbuild: [supported.import-attributes](https://esbuild.github.io/api/#supported:~:text=import%2Dassertions-,import%2Dattributes,-import%2Dmeta)
 - swc: [jsc.experimental.keepImportAttributes](https://swc.rs/docs/configuration/compilation#jscexperimentalkeepimportattributes).

If TypeScript can also provide this feature as much as possible, it will be a very good thing for us downstream developers.

Thank you for your confirmation.
