### ISSUE TITLE
In VSCode, monorepo's sub-packages should load `@types/node` which has been installed in their own node_modules

### ISSUE THREAD

**Issue by zanminkian** [microsoft/TypeScript#60748]
### 🔎 Search Terms

vscode monorepo load types

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.

Let's say I hava a monorepo. There is a unit test file in a sub-package. If this unit test file cannot match any `tsconfig.json` in this monorepo, there will be some importing errors (eg `import assert from "node:assert"`) in VSCode editor, even though it has already installed `@types/node`.

### ⏯ Playground Link

https://github.com/zanminkian/bug-report/tree/typescript/should_load_nearest_node_modules_types_bug

### 💻 Code

Please open https://github.com/zanminkian/bug-report/tree/typescript/should_load_nearest_node_modules_types_bug and read the readme to reproduce. Thanks.

Reproduce steps:

1. Clone this repo and checkout `typescript/should_load_nearest_node_modules_types_bug` branch.
2. Open this project using VSCode.
3. Run `pnpm i` in the root of this project.
4. Refresh VSCode (close all tabs).
5. Open `./packages/foo/src/foo.spec.ts` file.

Some related codes:

```json
// Root tsconfig.json
{
  "include": ["${configDir}/src"],
  "exclude": ["**/*.spec.ts","**/*.test.ts"],
  "compilerOptions": {
    "lib": ["ES2022"],
    "target": "ES2022",
    "module": "Node16",
    "moduleResolution": "node16",
    "outDir": "${configDir}/dist"
  }
}
```

```json
// Sub-package tsconfig.json
{
  "extends": "../../tsconfig.json"
}
```

```ts
// Unit test file
import assert from "node:assert"; // There is a importing error here
import { describe, it } from "node:test"; // There is a importing error here
import { foo } from "./foo.js";

describe("foo", async () => {
  it("foo should be /foo/bar", () => {
    assert.strictEqual(foo, '/foo/bar')
  })
})
```

### 🙁 Actual behavior

![Image](https://github.com/user-attachments/assets/5683b22f-05eb-4f37-a422-5eba80b9697a)

See the screenshot above. There are some importing errors.

### 🙂 Expected behavior

No errors in VSCode.

**Comment by RyanCavanaugh** [comment]
We have no way to know that `node:assert` comes in from `@types/node` -- an ambiently-declared module like that could come from anywhere. You'd need to add
```ts
/// <reference types="node" />
```
to `foo.spec.ts` if you want the inferred project to load it

**Comment by RyanCavanaugh** [comment]
We call it an *inferred* project for a reason - we can only guess at what you want to happen. We can guess differently but that's going to break different people with other scenarios, and they'll ask for the guess to change back to the current behavior.
