### ISSUE TITLE
🍯 Grouping of functions without being a dependency to align with tests describes

### ISSUE THREAD

**Issue by willi84** [microsoft/TypeScript#60747]
### 🔍 Search Terms

group

### ✅ Viability Checklist

- [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
- [x] This wouldn't change the runtime behavior of existing JavaScript code
- [x] This could be implemented without emitting different JS based on the types of the expressions
- [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
- [x] This isn't a request to add a new utility type: https://github.com/microsoft/TypeScript/wiki/No-New-Utility-Types
- [x] This feature would agree with the rest of our Design Goals: https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

### ⭐ Suggestion

(no idea what to be checked in ✅ Viability Checklist)

In Tests I can organize a set of tests with e.g. describe, but in TS (or JS) its just possible, when I create Modules, Classes, Namespaces etc. But this creates dependencies I dont want to have.

The suggestion is a sugar feature, which groups my functions the same like describe does but dont creates depency

```
group {
   export const makeTooltip()
   export const makeButtons()
}

// but still be callable as

makeTooltip()
```

### 📃 Motivating Example

currently u have to organize groups of functions in namespaces or classes

```
namespace ns {
  export const myFunction1()
  export const myFunction2()
}

// calling
ns.myFunction1()
```

but it would be better to avoid such dependency but still make functions for the developer organizable

```
group myCustomgroup {
  export const myFunction1()
  export const myFunction2()
}

// calling
myFunction1()
```

### 💻 Use Cases

1. What do you want to use this for? organizing my code better and aligining it with my tests
2. What shortcomings exist with current approaches?  dependencies or longer callees of functions (foo.bar.lorem.ipsum.myFunction())
3. What workarounds are you using in the meantime? namespace or class e.g.

**Comment by JoostK** [comment]
You're looking for https://github.com/Microsoft/TypeScript/issues/11073, which might already be achievable with plugins depending on the IDE you're using.

**Comment by jcalz** [comment]
> no idea what to be checked in ✅ Viability Checklist

Well, you checked "This isn't a runtime feature", but it is a runtime feature.  This is something that would have to exist in JavaScript (Stage 3 of [the TC39 Process](https://tc39.es/process-document/)) before TypeScript would implement it. You could try to go through the TC39 process, but I doubt this would ever be accepted. It's the same as the deprecated [`with` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with), or the unsupported `import * from 'module'`.

**Comment by willi84** [comment]
@jcalz thats the reason why I was honest, I just checked to submit but was not sure where to put the right checkboxes

**Comment by willi84** [comment]
@JoostK thanks :-)
