### ISSUE TITLE
type predicate inference: full union match results in loss of infered predicate "v is T" for a simple "boolean"

### ISSUE THREAD

**Issue by akomm** [microsoft/TypeScript#60741]
### 🔎 Search Terms

type predicate type guard inference union full complete match

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about 5.5.4 though 5.8.0-dev.20241211

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241211#code/C4TwDgpgBAYg9nKBeKBvUkBcUDk844A0UAZgtgHYCuAtgEYQBOAvgFAbQBCAho8mh2w4ejIlDq9sAZ2CMAlhQDmbDrAQj+6cBCH4RYsnBHY6CADYRuFNqwD0t8dwAmUALRQIAD0gBjYBCdsADduMyg5KTVEAB8oEQBuKEYIHwg5IICTc0sKVhIqCj85OAoofxkAQQAKELNsfChYkQBKKFsAKigsuAsrKHaHVFYoJIhgKkZS2oA6VSR5qAAifEXG2Jm5hcWRRdYbeyhFBCc8gqKSsogZThrQ+oRGuN5HvV5Wjq6oWvDIhqbngZoYajcaTL6hWbaZBbFZrcFmSGQaEoba8XbMIA

### 💻 Code

```ts
type Foo = {type: 'Foo', foo: number}
type Bar = {type: 'Bar', bar: string}
type FooBar = {type: 'FooBar', fooBar: boolean}

// bad - expected: val is Foo | Bar; received: boolean
function testA(val: Foo | Bar) /* : boolean */ {
  return val.type === "Foo" || val.type === "Bar"
}

// good
function testB(val: Foo | Bar | FooBar) /* : val is Foo | Bar */ {
  return val.type === "Foo" || val.type === "Bar"
}
```

### 🙁 Actual behavior

The inferred return type of `testA` is `boolean`

### 🙂 Expected behavior

The inferred return type of `testA` should be `val is Foo | Bar`

**Comment by jcalz** [comment]
This is working as designed; TS doesn't bother generating type predicates for things that don't narrow their inputs at all: https://github.com/microsoft/TypeScript/pull/57465/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R37508

What exactly is the utility of a type guard function that doesn't narrow?  Do you have some code whose behavior is actually improved when `function f(x: X) { return true; }` is given the return type of `x is X` instead of `boolean`?

**Comment by akomm** [comment]
[example effect-ts](https://effect.website/docs/error-management/expected-errors/#catchif)
Here based on the example above that filters only `HttpError`, an adjusted one that filters all types:
[TS Playground](https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241212#code/JYWwDg9gTgLgBAbzgUQGaoKYGMYBo4BKAhgHYAmEIcAvnKlJXAEQbrYxMBQnWANkQGcBcABIwYYZFAZREnOHCgYiFErwCecAPowiAczgBeZmIlSZXatz6DhANSK9gZIjGAQS56HIVKVHjW1dA2MmBycXNw8vKEtuAHp4hWS4QBhSQABSTJQ2HAAeARgoYBI9fFNJaW8AHzhw51d3T0qofBIMADcMKAA+TkSUhUAe0h4PArgwBj0oIipjNEwcADo9DBIAClQAVxIcRoAqODWASh84LFH4EgBGIzh1YAxeMgPickpFtoAPGHkzi7gSAAmW73R7PQikCggD4Yb6-YCoQ7XOC5OAABkWAFYTghfgpQU8DvN2ItUERgLw1m0AO6icQVGTHI6-KwKBFI4GojHY074h6E7ILGCk8mUmm1Rz1KJNRlHZkKVmKDAwTZQEjMASUDBKgSbXgcTjUZl9JIDDJZAQACwgerIcAARtriXkCkUSq0Ol0PZ0eg7NvBgMJnTB8oViqU6WZmnAanVIo0Yt6ur1+gNhucSGMlOcfRg7cYJhApjNFmBgGAMGsTSkAHoAfl+wcWWFcWEtAElUFWUmsujIToZunA+9BFjp9EZDKFyjEmDGaiOoGPgpPQnGGtFmkxcHjDgOh03dVgsBg82smARsBAfeG6AwqDOt-K4MyjkA)

The issue is that the predicate does not have to be always *static*, it might also be dynamic so just picking "catchAll" is not a solution.
You have code that type checks correctly and then a variable change elsewhere and suddenly it breaks.

**Comment by jcalz** [comment]
(I'm not a TS team member so feel free to ignore me)

I don't think I can really commit to understanding Effect-TS to look at an example; do you have a self-contained example of such a "dynamic" predicate? 

Even if you provide this, I doubt they plan to modify the existing behavior to work for it, since it would cause lots of type predicates to appear in the wild for code that doesn't even attempt to narrow anything, triggering a whole bunch of extra control flow analysis where it doesn't need to happen. Consistency is nice, but it doesn't outweigh compiler performance.

**Comment by akomm** [comment]
While its effectively the same, there is a difference in:
`function f(x: X) { return true; }` 

and:
`return val.type === "Foo" || val.type === "Bar"`. 

The first one does not provide any expression for TS to evaluate, while the later does.

Correct me if wrong, but for TS to figure out the input is not narrowed down, it has to evaluate it anyway? So what is left then is for it to decide whether to resolve / infer it as a predicate or not based on already computed context.

If your concern is that the performance cost comes *later* when *wild* predicates propagate further throughout the code, then maybe the solution could be to behave like it does now, except the type annotation explicitly defines a type predicate?

Here is how the refinement function is typed in effect-ts example:
![Image](https://github.com/user-attachments/assets/eb0e60bd-d8a5-4370-9cc4-4d6d32c1e510)

Yet TS decides to *drop* the context and make it `boolean`.

**Comment by akomm** [comment]
A simpler Example without effect-ts: [TS Playground](https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241212#code/C4TwDgpgBAYg9nKBeKBvUkBcUDkAzBHAGigLmwDsBXAWwCMIAnAXwCgNoAhAQ0eTQ7YcdXsSgjG2AM7BGASwoBzNqwAmEAMYAbXtDxUKG4HLgUoUgNZywASTwAeAIIlOUCAA9gECqqlRHAHwAFNxS2I4A2gC6JGCMEKpyGtxe2CHhAJTIAVDcUHJ+nBnYAKLu2lTqTi4B0axqmjrxUBqmMvleNGFQQfCIAD5QPIwZdaytFO2MAIz8ltZ2QXKdUiTLEDTZHRsAdBzISCgARGRHGawA9BdQN1AAegD8423AUIwATHNWtnhLK2udLbrGh7cDQQ7HU5QfqDYGgyAHY4SM6Xa63R5AA)

**Comment by RyanCavanaugh** [comment]
It seems like someone writing that code has a bug, or at least has code suspicious enough to warrant additional verbiage to indicate that they know what they're doing.

**Comment by akomm** [comment]
The code is 1:1 reduction of what @Effect-TS (the example) does. 

It takes a set A, a subset (B) of A and subtracts the subset B from set A. 

A subset can contain *all* elements of a set, means be equal. Then the difference is an empty set. In TS that is basically never.

The logic by which you omit the predicate makes only sense in a subset of cases. That are those, where you don't inverse, subtract / reduce. In other cases it breaks.

I can open an issue in @Effect-TS if you still think its a bug or mistake.

**Comment by RyanCavanaugh** [comment]
60 lines? I don't know. Do what you need to do, but I have never seen a good type system change that couldn't be well-motivated by a single screenful of code.

What does Effect-TS lose if it adds the non-predicate overload?

**Comment by akomm** [comment]
> What does Effect-TS lose if it adds the non-predicate overload?

As I've previously suspected in https://github.com/microsoft/TypeScript/issues/60741#issuecomment-2538491424
> In order for Effect-TS to solve that they would have to assume that the inferred return type of the Refinement being boolean (conditional type) implies that the predicate did not narrow down at all to produce the correct type result. Sounds like a bold assumption they would have to make there. Not sure if a good idea at all.

The issue is, that when the predicate is removed, the `const true`-return type is widened to `boolean`. So you can't safely overload:
[TS-Playground](https://www.typescriptlang.org/play/?ts=5.8.0-dev.20241212#code/MYGwhgzhAEASAu8AOBRATmg9m6BvAUNNGgKZgAmmAdiAJ7QD68YA5tALzQBECy6WaLvgC++fKEgwAamBABLcmHhzq-bHkLEylGvSasO3GfMXLVGbENH5yJCaWgAzAK5VgZqtHgkI8ADwAKgA00ABK0CQAHt5U5DABAHwAFI5UAFzQSQBuGQEAlBwJ0FnQcjCheRkokaDOtoEhoQn4APQt0ACMAHTQwJgAtv0kVPClVC2YzqOYWSRoIJgUNnbgDi5uHl4+-okp6Zk50PmF0ABGmJggZFSV0FQks2hibdAA6iS9YFQA5KPApEoPmBoEgsEg5tAZnMFhQ0q12gEAMrQSg+O6YUYAK2cvi0-ShXgAFh9QSRyHJgICnFh+tBgVw+lRcfA0M4SFwnK53CpPKR4M40FQQqcpnSQBBMNAAO4KYYweDE7iM5ms9leSVcc6Xa5CF4AJh6fUGw1GchGE1FUPmi3I8Ns9g+6251C2vkCyVSGWyuQK7CKLLZt3ujzEytGaA6hm8viSSTmAgyvFQFhwAB9oMYFEoeWo0L6ivHsF19Gx2GXuEncxzU+nC2hi8xS+WuJnTDmU1w8vCiEQAHoAfnE1FxaD1Ue2sbricQyYE0HTrez5gE+YiKYbBjLnB4M6rXZePYHQ6Z4YAzOOY3GU9O+Cn5xnZFmPLnV45ZBASPv2ofBy8rTDySoNgXU1C4ri+DkynRcMSHkMBTiuEJICIBUPlICBnBAUZ+jkFhCVGU4PnOBUvFVOlYicd8SCAA)

**Comment by mikearnaldi** [comment]
> 60 lines? I don't know. Do what you need to do, but I have never seen a good type system change that couldn't be well-motivated by a single screenful of code.
> 
> What does Effect-TS lose if it adds the non-predicate overload?

Effect does have a refinement overload the issue here is that TS infers the type predicate as returning boolean because the predicate doesn't narrow the input

**Comment by RyanCavanaugh** [comment]
Why is it `: never` instead of
```ts
declare function test<T>(fn: (v: T) => boolean): T;
```
?

**Comment by akomm** [comment]
The example has two choices, 1. & 2. that can be comment out / in (either 1. or 2.)

The goal is to achieve the Effect of `Exclude<T, R>` for `declare function test<T, R extends T>(fn: (v: T) => v is R): Exclude<T, R>`.
If we do not narrow down, then `T = R`. That means `Exclude<T, R>` is `never`.

In order to be able to create the proposed overloading, we would need to be able to detect `const true` return type on the predicate.

When the predicate does *not* narrow down, the return type is basically `const true`. But because of type-widening, it becomes `boolean`, so we can not use overloading to precisely catch the `does not narrow down` case.

**Comment by RyanCavanaugh** [comment]
Looking at the PR... trying to help Effect-TS breaks fp-ts. I hate picking sides 😅

**Comment by akomm** [comment]
I know, you it still is relevant for those who use fp-ts, but this might be a relevant info for a decision:
![Image](https://github.com/user-attachments/assets/0914a3c3-d1f3-4b33-8640-b3b1c34dd99c)
(https://effect.website/docs/additional-resources/effect-vs-fp-ts/)
