### ISSUE TITLE
Type inference of intersected type (&) with a discriminated union (|) is off in TS < v5.4.5

### ISSUE THREAD

**Issue by marinsokol5** [microsoft/TypeScript#60740]
### 🔎 Search Terms

type inference, discriminated unions

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.4.5, today it's fixed.

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=4.9.5#code/C4TwDgpgBAQghgZwgeTMAlgewHYKgXigG8AoKcqAegCpqyKpqoAVAZSgBFMBjKAM0wAnKJjRZsARnoVqlaSLE4JALigAjTJgA2EONgDcJAL4kSoSFADCOACboMOOFtQPcBKPIA+xeQxp0GQKZgQQBXaABaAD4Wdi5eAWFRVwAmXwZZdPJk8RTVEPDDQPITBm9SYvJ-LPImPickKGjYzh5+IQVUmsY5Ss7cgH5Veq0keSMPM3BoF3E8QngkWZw8ADIrW3txJ2XcQxJuFeB+ldVd+Z8GHKVVABpjQyA

### 💻 Code

```ts
type BaseOptions = {
    /**
     * TS Doc for option1
     */
    option1: boolean;
}

type ConditionalOptions = 
    | {
        /**
         * true -> TS Doc for option2
         */
        option2: true;
       }
    | {
        /**
         * false -> TS Doc for option2
         */
        option2?: false
    } 

type Options = BaseOptions & ConditionalOptions;

const options: Options = {
    option1: ,
};

```

### 🙁 Actual behavior

When hovered over the option1 inside of the Playground, it's considered as `any` and TSDoc is not acknowledged. 
![Image](https://github.com/user-attachments/assets/cf18c377-628f-4877-83a1-1138f6d8f439)

### 🙂 Expected behavior

I expected to see the correct type there (`boolean`) with it's accompanying TSDoc, like it does today in v5.4.5 or in earlier versions when discriminated union is not intersected with. 
![Image](https://github.com/user-attachments/assets/86883206-2da6-4fd2-bd69-8d0e4fe51c5f)

**Comment by Andarist** [comment]
For context, this was improved in: https://github.com/microsoft/TypeScript/pull/56088 . TypeScript doesn't backport such improvements. So the best you can do is to wait for your customers to start using the new TS version.

**Comment by marinsokol5** [comment]
Thank you @Andarist, and yeah that does make sense to not backport all the small improvements. 

Do you maybe know if there is any similar Typescript behaviour that we could leverage today that doesn't hit this quick info bug?

**Comment by Andarist** [comment]
Nothing comes to my mind. Before my PR it always ignored multiple symbols (cause how would you know which JSDocs to pick?, with my PR it first deduplicates them and if one is left then it's used. In your case, that helps because it's a shared symbol between all constituent members. So while the change was really simple I doubt you can somehow trick it to get the behavior you want in those older TS versions
