### ISSUE TITLE
`Awaited<T>` is documented as, but doesn't, return `never` for non-Promise thenables

### ISSUE THREAD

**Issue by rotu** [microsoft/TypeScript#60742]
### 🔎 Search Terms

Awaited

### 🕗 Version & Regression Information

- This changed between versions 4.8.4 and 4.9.5

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.2#code/MYewdgzgLgBAtgTwCoAsCmYCGAjANmmAXhgG8AoGSmKdMACgCc0IRcA3NALjoA9OwArnGxoGASkIA+NiACWAEwA0MJgCs0wKNwB0uzAwDmETgLABrMCADuYANoBdCdLnyx5Kh5XNWHOgBYAJjEKKgBfMnCoBAAHAiQiGABBK0xZKDR5AB4o2JAAM3hkWhx8STIAenKqAD0AfjJMCAQwYBg8001ZcDaQEDo3EMpQSFgEBMwUtMLUDBK0QZhKjzqIsiA

### 💻 Code

```ts
const myThenable = {
    then(resolve:(x:number)=>void, reject:(...args:unknown[])=>void){
        resolve(42)
    }
}
type T = Awaited<typeof myThenable>
//   ^? type T = number
async function foo(){
    const y = await myThenable
    //    ^? const y: number
}
```

### 🙁 Actual behavior

When you mouse over `Awaited`, it returns the help text:

> Recursively unwraps the "awaited type" of a type. Non-promise "thenables" should resolve to never. This emulates the behavior of await.

But `Awaited` and `await` both return `number`.

### 🙂 Expected behavior

The documentation and behavior of `Awaited` should agree. I think the documentation is in error.

**Comment by rbuckton** [comment]
This is working as expected. What you have illustrated is a Promise/A+-like "thenable", which both `Awaited` and `await` are able to resolve. By "non-Promise 'thenable'", we are describing an object that has a callable `then()` method that does *not* take a callback as its first argument:

```ts
const myThenable = {
    then(resolve: string){
    }
}
type T = Awaited<typeof myThenable>
//   ^? type T = never
async function foo(){
    const y = await myThenable // error: Type of 'await' operand must either be a valid promise or must not contain a callable 'then' member.
    //    ^? const y: any
}
```

[Playground](https://www.typescriptlang.org/play/?ts=5.7.2#code/MYewdgzgLgBAtgTwCoAsCmYCGAjANmmAXhgG8AoGSmKdMACgCc0IRcA3NALhmgYEswAcwCU5KjAC+ZKVAQAHAkiIwAggHdMfKGgAmAHlkKQAM3jJaOfAD4yAeltUAegH4ymCAjDAYxgK5eoPnAfEBA6UQoqUEhYBGVMDS0zVAxLNEjKe3EXaTIgA)

**Comment by rotu** [comment]
@rbuckton Is there a better way to phrase this? I think the term "thenable" implies promise-like.

Maybe instead of:
> Recursively unwraps the "awaited type" of a type. Non-promise "thenables" should resolve to never. This emulates the behavior of await.

it would be clearer as this?
> Recursively unwraps the "awaited type" of a type. Types with a promise-incompatible "then" method should resolve to never. This emulates the behavior of await.

**Comment by rbuckton** [comment]
I think this is a misunderstanding of what "thenable" means. A "thenable" is just any object with a `then` method, per https://promisesaplus.com/#point-7. "thenable" does not imply promise-like.

**Comment by RyanCavanaugh** [comment]
I don't understand. Why isn't `myThenable` a "non-promise thenable"? It has a `then` method, but isn't a `Promise`.

**Comment by rotu** [comment]
> "thenable" does not imply promise-like.

I think that was the understanding when "Promises/A+" was written but it's not clearly the case anymore, especially in passing mention.

Now that JavaScript has `Promise`, it is confusing to rely on the distinction between a "promise" in the "Promises/A+" sense and a "`Promise`" in the ECMAScript sense.

MDN [strongly implies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables) that conforming thenables are *not* promises:

> To interoperate with the existing Promise implementations, the language allows using thenables in place of promises.

And the ECMAScript spec has a [`IsPromise` operation](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-ispromise) which returns false for promise-compliant thenables.
