### ISSUE TITLE
How to mock a typescript interface to test some use cases in a lib

### ISSUE THREAD

**Issue by zedryas** [microsoft/TypeScript#60753]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

I did ask this question on [StackOverflow](https://stackoverflow.com/questions/79218277/how-to-mock-a-typescript-interface-to-test-some-use-cases-in-a-lib) but did not get any answers so i try to post it here

I would like to have an interface populated only for test environment.

Let say i have this interface in the lib code base
```ts
// file MyInterface.ts

export interface MyInterface {}
```

And later in end user code base so he can populates MyInterface like so
```ts
// in the library user code base

declare module 'my-lib/MyInterface'
{
    interface MyInterface
    {
        user-property: unknown // some type here
    }
}
```

I need to test types in the library that uses `Myinterface`, and to do so i might need to test some keys and values associated to that key that are not relevant toward the lib but need some tests

I know I can define an interface `_TestMyInterface` which extends `MyInterface` and is not exported by the library but I will also have to redefine all the tests using `MyInterface` to use the `_TestMyInterface` interface instead and this will require me to do so duplicate the entire codebase. For example :
```ts
import {MyInterface} from './MyInterface'
import {_TestMyInterface} from './_TestMyInterface'

export type TypeThatUseMyInterface<K extends keyof MyInterface> = K // do something with K

type _TestTypeThatUseMyInterface<K extends keyof _TestMyInterface> = K // do something with K to allow testing for specific values that are not relevant to the library but might be relevant to the end user.
```

Is they're a better way to achieve this and mock `MyInterface` for testing purposes only?

I am using `vitest` for my testing environment

**Comment by mrazauskas** [comment]
> I am using `vitest` for my testing environment

Did you try asking this in the [`vitest`](https://github.com/vitest-dev/vitest/discussions) repo? Their community could have a solution.

**Comment by zedryas** [comment]
@mrazauskas it is more a `typescript` ability than a `vitest` ability, if we can't do it in `typescript` how could `vitest` achieves it ? I feels this relates to #60751
