### ISSUE TITLE
Ensuring an object literal fully implements an interface

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#6078]
```typescript
interface Foo {
	foo: string;
}
interface Bar extends Foo {
	bar: string;
}

function useFoo(foo: Foo) {}

useFoo({ foo: "" } as Bar); // I want an error here, what can I do?

let b: Bar = { foo: "" }; // Error occurs
useFoo(b);
```

Is there a good way to declare the object literal as `Bar` without an additional variable so that compiler can show an error when more members are required for the object to be `Bar`?

**Comment by falsandtru** [comment]
Probably, interface is structural subtyping.

You can get an error on a following code.

```ts
declare class Foo {
    private id;
    foo: string;
}
declare class Bar {
    private id;
    foo: string;
    bar: string;
}

function useFoo(foo: Foo) {}

useFoo({ foo: "" } as Bar); // error
```

But you cannot get an error if you use the inheritance.

```ts
declare class Foo {
    private FOO;
    foo: string;
}
declare class Bar extends Foo {
    private BAR;
    bar: string;
}

function useFoo(foo: Foo) {}

useFoo({ foo: "" } as Bar); // no error
```

I think this is a feature of structural subtyping and nominal subtyping.

**Comment by SaschaNaz** [comment]
@falsandtru That makes `useFoo({ foo: "", bar: "" } as Bar);` as an error too. I would want compiler not to complain with this.

**Comment by falsandtru** [comment]
Probably, it is impossible because it seems a design of type system of TypeScript.

**Comment by SaschaNaz** [comment]
Then this is my proposal:

```typescript
// Error when the object literal does not fully implement the target interface
useFoo({ foo: "" } implements Bar);
```

> _object-literal_ `implements` _type_

**Comment by RyanCavanaugh** [comment]
I can't think of a way to do this at the argument level.

You could assert the left side instead:
```ts
// Error
(useFoo as (n: Bar) => void)({ foo: "" });
// OK
(useFoo as (n: Bar) => void)({ foo: "", bar: '' });
```

Given how rarely this is desired in practice, I don't think it merits a new type operator.

**Comment by SaschaNaz** [comment]
Usable workaround. Thanks :)

**Comment by SaschaNaz** [comment]
Note that it still won't work when assigning to a variable: 

```typescript
interface Foo {
    foo: string;
}
interface Bar extends Foo {
    bar: string;
}
interface Baz {
    baz: Foo;
}

function baz() {
    let result: Baz = {};
    if (true) {
        result.baz = { foo: "" } as Bar; // Well.. what can I do, generics?
    }
    else {
        result.baz = { foo: "" } as Foo;
    }
}
```
