### ISSUE TITLE
Typescript 5.7.2: Can't extend DataView - TS2508: No Base constructor has the specified number of type arguments

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [microsoft/TypeScript#60808]
### 🔎 Search Terms

"dataview", "ts2508", "no base constructor has the specified number of type arguments"

### 🕗 Version & Regression Information

- This changed between versions 5.6.3 and 5.7.2
- This **probably** changed in commit or PR #59417
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about DataView and TypedArray
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.2#code/MYGwhgzhAEAa0FMAeAXBA7AJjAImFYAagJYIDu0A3gL5A

### 💻 Code

```ts
class X extends DataView {}
```

### 🙁 Actual behavior

error TS2508: No base constructor has the specified number of type arguments.

### 🙂 Expected behavior

build should run without any issues and class X should use the default constructor of DataView

**Comment by MartinJohns** [comment]
This is working as intended, see [the release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#typedarrays-are-now-generic-over-arraybufferlike) and the PR you linked; #59417

`DataView` is now a generic type accepting one type argument. You don't provide a type argument.

**Comment by meszaros-lajos-gyorgy** [comment]
@MartinJohns could you please provide an example? I tried the following:
```ts
class X extends DataView<Uint8Array> {}
```
But this gave me another error: 
```
Type 'Uint8Array<ArrayBufferLike>' does not satisfy the constraint 'ArrayBufferLike & { BYTES_PER_ELEMENT?: undefined; }'.
  Type 'Uint8Array<ArrayBufferLike>' is not assignable to type 'ArrayBuffer & { BYTES_PER_ELEMENT?: undefined; }'.
    Type 'Uint8Array<ArrayBufferLike>' is not assignable to type '{ BYTES_PER_ELEMENT?: undefined; }'.
      Types of property 'BYTES_PER_ELEMENT' are incompatible.
        Type 'number' is not assignable to type 'undefined'.
```

**Comment by meszaros-lajos-gyorgy** [comment]
Okay, I got it working like this:
```ts
class X extends DataView<Uint8Array['buffer']> {}
```

**Comment by meszaros-lajos-gyorgy** [comment]
Okay, sorry, I had to reopen as I still can't make it work:

```ts
class X extends DataView<Uint8Array['buffer']> {}
```

Hovering over DataView I see the following error: No base constructor has the specified number of type arguments.ts(2508)
