### ISSUE TITLE
Why ts dont undestand to event.target.value when i type event how InputEvent

### ISSUE THREAD

**Issue by anzor1qqqqq** [microsoft/TypeScript#60806]
### 🔎 Search Terms

 event.target.value does not see value

### 🕗 Version & Regression Information

- This changed between versions ______ and _______
- This changed in commit or PR _______
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about _________
- I was unable to test this on prior versions because _______

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAFgQzAEwDYFMCSYAOBXKAYUTAHN0YBeGACnQDd0woAuGbfKAUUeYEoqAPhgBvAFAxJMUJFhQEAJ3KxqDJlAB08peigBuCVJkQQGDahCka25RvoJUedHwMBfPUA

### 💻 Code

example in ts playground link 

### 🙁 Actual behavior

Property 'value' does not exist on type 'EventTarget'.(2339)

### 🙂 Expected behavior

I have to access value without problems.

**Comment by MartinJohns** [comment]
Because event bubbling is a thing in JavaScript.
