### ISSUE TITLE
Value of string literal type as property name.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#6080]
For example:

``` ts
type Method = 'get' | 'post';

let app = {
    get() { },
    post() { },
    foo() { },
    bar: 123
};

let methodA = 'get';
let handlerA = app[methodA]; // typeof handlerA === () => void

let methodB: Method;
let handlerB = app[methodB]; // typeof handlerB === () => void
```

**Comment by SaschaNaz** [comment]
See also #394.

**Comment by vilic** [comment]
@SaschaNaz Thanks for the reference. So basically now we may have `memberof` operator return a string literal type, that's interesting. Hopefully somebody would take that PR.

**Comment by DanielRosenwasser** [comment]
I know @weswigham has brought this up, though I'm not sure if there's an existing issue for it.

**Comment by masaeedu** [comment]
@vilic What does the snippet demonstrate?

**Comment by vilic** [comment]
@masaeedu Hmm, I think it's about finding a common type among several properties (within the range of string literals union).

**Comment by mhegazy** [comment]
This should be addressed by the new indexing support for literal types in https://github.com/Microsoft/TypeScript/pull/11929
