### ISSUE TITLE
`satisfies` does not check function input within the object

### ISSUE THREAD

**Issue by josejulio** [microsoft/TypeScript#60827]
### 🔎 Search Terms

satisfies function input

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about `satisfies`

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=5.7.2&q=45#code/https://www.typescriptlang.org/play/?ts=5.7.2&q=45#code/C4TwDgpgBAsiAq4IB54D4oF4oG8BQUUwA9mAFxTwDcBUAZhQBTAXwCUWG1eAvnngHoBlABYBLAM5QJI4gHcpAQwB2UCACd1xdVDwBjYsonAiEY1ly0S5KACI6xYrYA0tBlGYV7j2x0wZvJyhFKQMjYFohSiQoAHJPOwcnPwCk21ioSShlYhMQiTEAc2VFACMAG2gSIhj4lmlgdTFlQpSGppbY3mDQw3MJRWBJOjEzWAQkZGMOwrQqIA

### 💻 Code

```ts
type MyType<T> = {
  top: T;
  f: (t: T) => T;
}

// This shows an error 
const test = {
  top: "foo",
  f: (t: "foo") => "foo" as const
// Type '(t: "foo") => "foo"' is not assignable to type '(t: string) => string'
} as const satisfies MyType<string>;
```

### 🙁 Actual behavior

`satisfies` does not seem to be trying to use the type on the input of the functions.

### 🙂 Expected behavior

`satisfies` should be able to check that the type is actually a literal - it does in the other properties but not on the function inputs.

**Comment by guillaumebrunerie** [comment]
The error is correct, `(t: "foo") => "foo"` is not assignable to `(t: string) => string`, check the documentation of `strictFunctionTypes`: https://www.typescriptlang.org/tsconfig/#strictFunctionTypes

**Comment by josejulio** [comment]
I guess I was under the false impression that `satisfies` would narrow the type to something like `MyType<"foo">`.
Now it makes more sense.

thanks!
