### ISSUE TITLE
Visual studio JSDoc comments do not collapse

### ISSUE THREAD

**Issue by Gambero81** [microsoft/TypeScript#6082]
Collapse to definition on typescript code do not collapse JSDoc multiline comments.
Please add collapse functionality for jsdoc comments as done in c# with vsdoc comments.

**Comment by DanielRosenwasser** [comment]
Which version of Visual Studio are you running?

![image](https://cloud.githubusercontent.com/assets/972891/11775213/ae67b2f8-a1f1-11e5-8397-a5124cc065c4.png)

**Comment by Gambero81** [comment]
I use Visual Studio 2015 Update 1
The collapse sign (+ and -) are present and manual collapse work, but if i collapse all code in file with contextual menu Outlining -> Collapse to definitions, JSDoc comments remains expanded and not collapse:

![jsdoccollapse](https://cloud.githubusercontent.com/assets/13186600/11782506/b0e00190-a271-11e5-921f-bc257a695d0c.png)

if i collapse manually comment is now displayed:

![jsdoccollapse2](https://cloud.githubusercontent.com/assets/13186600/11782562/f455ba3c-a271-11e5-8d59-9dfa7a9e81f9.png)

but it would be nice to show it as done in c# collapsed comments:

![jsdoccollapse3](https://cloud.githubusercontent.com/assets/13186600/11782591/0fd1191e-a272-11e5-8d1b-18b81c3cabfb.png)

**Comment by DanielRosenwasser** [comment]
Hmm, I think it was originally desired behavior to not collapse comments. @CyrusNajmabadi, any thoughts?

**Comment by Gambero81** [comment]
As done for vsdoc comments it would be very nice to collapse comments when user choose "Collapse to definition", because this feature allow read all functions signs in a compact way, viewing comment preview on collapsed comment is also a very good feature for read short comments.. please reply the behaviour of c# vsdoc comments :-)
Thanks

**Comment by CyrusNajmabadi** [comment]
The current behavior is to not collapse comments.  But we've been talking on Roslyn if we should have a collapse-comments command.  Or some other way to get comments out of the view so that you can focus on the code.  No plans as of yet though.

**Comment by Gambero81** [comment]
I see @CyrusNajmabadi, but can't understand the advantages of current behaviour compared to vsdoc comment behaviour (collapsible with comment preview on collapsed line), hope in a change!
Thanks

**Comment by DanielRosenwasser** [comment]
Because the command right now is "Collapse to Definitions"; not necessarily "Collapse Comments". What one person thinks is desirable, another might feel the opposite about.

So @CyrusNajmabadi, there's no Roslyn issue open for this at all?

**Comment by CyrusNajmabadi** [comment]
Not that I know of.

**Comment by Gambero81** [comment]
Some news about this issue?

**Comment by Gambero81** [comment]
up

**Comment by RyanCavanaugh** [comment]
Closing due to lack of other interest

**Comment by Gambero81** [comment]
It is a must have feature!
Please consider to schedule it!

TypeScript collapse simply need to have the same behavior of c# code..

**Comment by RyanCavanaugh** [comment]
> It is a must have feature!
Please consider to schedule it!

You are literally the only person to talk about this feature in nearly five years. 😐

**Comment by eJJonatah** [comment]
actually, i just found out this problem. I Think that the point here is why people migrate to visual-code when dealing with typescript. Because when you point-out quality of life bug when visualizing code, people will say that you're the only one asking for it.

**Comment by BigBigPlant** [comment]
I want this feature
