### ISSUE TITLE
Incorrect Apparent Type of a Union of Constructors

### ISSUE THREAD

**Issue by LukeAbby** [microsoft/TypeScript#60839]
### 🔎 Search Terms

union of constructors, InstanceType, narrowing

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about constructor type narrowing

### ⏯ Playground Link

https://www.typescriptlang.org/play/?ts=4.9.5#code/CYUwxgNghgTiAEkoGdnwKIA8oFsAOEIAwtKvAN4CwAUPHfHjAPZ4Bc8AdgK44BGIMANw0AvjRoAXAJ54EAFSgBrEMiy4CIADxz4ITBJAdgaNfkIkUyAHzwAvPDnDqkmfJUTtu-YePxpspgAzDGwzYlI0AB94AAoOEAB3WIBKOxsmXgArcAlkm3sdPQMjNH8QIJD1cwiaengAfgclFVMNTQBJDmQJKA4wEDlXbSsrWvoAenG66bqAPQdXeAByTu7e-sHZYaX4YCYVTiYJeGQoCQBLZECpPwALBDAmLokYKHOOY6XW6sslgDoxnRJjMQXVNggllwOIoOEwEhwdpdDsdLOcAOYcKC8Qh+Jh+RZfUIaCyof6A+DA0FUhayZYZbJgY7Rb7hX7wJGwlGodGY7EICR4srLFkk5Bk2gTKbU6kABWYshg0mWjBYiLQOEuyHeaPZHHxtKW5BEO14XGOcAAjlxznBgLr9RCRRFxXV2PEAG4CQRAA

### 💻 Code

```ts
declare class ExampleClass {
    prop: number;
}

type TakesExample<T extends ExampleClass> = T;

type Test<T extends typeof ExampleClass | (new () => object)> = T extends typeof ExampleClass
    ? TakesExample<InstanceType<T>>
    //             ^ Type 'InstanceType<T>' does not satisfy the constraint 'ExampleClass'.
    //                 Type 'unknown' is not assignable to type 'ExampleClass'.
    //                   Type 'object | ExampleClass' is not assignable to type 'ExampleClass'.
    //                     Property 'prop' is missing in type '{}' but required in type 'ExampleClass'.
    : never;
```

### 🙁 Actual behavior

This errors because it appears to lose the context that `T` is `typeof ExampleClass` when ran through `InstanceType`. I find this especially odd because if you make a `TakesExampleClass<T>` it'll succeed.

### 🙂 Expected behavior

No error.

**Comment by Andarist** [comment]
I believe this is because how infer-type arguments usually have no constraints at all - even if they were inferred from contained positions. The simplest example of that can be seen here:
```ts
type TakesString<T extends string> = T;
type Test<T extends string> = 
  T extends infer R
    ? TakesString<R> // error
    : never;
```

**Comment by LukeAbby** [comment]
That makes sense. Unfortunate nonetheless.
