### ISSUE TITLE
Support python

### ISSUE THREAD

**Issue by STofone** [microsoft/TypeScript#60845]
### Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.

### Comment

typescript makes js like an optional static language, and I hope to use it in python as well.
I make a [topic ](https://discuss.python.org/t/replace-current-type-hint-with-typescript-syntax/75026)in python

**Comment by alextraub** [comment]
I'm confused what you're trying to achieve here. Are you looking for a type checking layer for python? Or are you actually trying to use typescript in Python?

If the first, a quick google search brought up mypy: https://github.com/python/mypy

If the second, that fundamentally wouldn't work. Python syntax rules are so different from JavaScript the [AST](https://en.m.wikipedia.org/wiki/Abstract_syntax_tree)s wouldn't look even remotely similar. You need a language specific solution.
