### ISSUE TITLE
Type Guard complaining when type hinting with an herited abstract class

### ISSUE THREAD

**Issue by plopinou** [Microsoft/TypeScript#6085]
I stumbled upon this problem while playing with angular 2 new Form Builder.

```typescript
abstract class AbstrCtrl {
}

class Ctrl extends AbstrCtrl {
  _value: any
  setValue(value: any) {
    this._value = value;
  }
}
class Ctrl2 extends AbstrCtrl {
  //... other things
}

class CtrlGrp extends AbstrCtrl {
  constructor(public controls: {[key: string]: AbstrCtrl}) {
    super();
  }
}

let group = new CtrlGrp({ name: new Control() });
group.controls['name'].setValue('Hello World!');
//--> error TS2339: Property 'setValue' does not exist on type 'AbstrCtrl'.
```

Because we want groups to be able to contain others groups, we type hint the CtrlGrp constructor with AbstrCtrl instead of Ctrl. But then, Type Guard complains that the AbstrCtrl class does not have a setValue method, even thought we clearly pass as argument to CtrlGrp instances of Control.

Is it a normal behavior ?

Note: I'm using typescript 1.7.3

**Comment by weswigham** [comment]
This is normal behavior - to do what you want, [consider using a generic class.](http://www.typescriptlang.org/Playground#src=abstract%20class%20AbstrCtrl%20%7B%0A%7D%0A%0Aclass%20Ctrl%20extends%20AbstrCtrl%20%7B%0A%20%20_value%3A%20any%0A%20%20setValue(value%3A%20any)%20%7B%0A%20%20%20%20this._value%20%3D%20value%3B%0A%20%20%7D%0A%7D%0Aclass%20Ctrl2%20extends%20AbstrCtrl%20%7B%0A%20%20%2F%2F...%20other%20things%0A%7D%0A%0Aclass%20CtrlGrp%3CT%20extends%20AbstrCtrl%3E%20extends%20AbstrCtrl%20%7B%0A%20%20constructor(public%20controls%3A%20%7B%5Bkey%3A%20string%5D%3A%20T%7D)%20%7B%0A%20%20%20%20super()%3B%0A%20%20%7D%0A%7D%0A%0Alet%20group%20%3D%20new%20CtrlGrp(%7B%20name%3A%20new%20Control()%20%7D)%3B%0Agroup.controls%5B'name'%5D.setValue('Hello%20World!')%3B)

**Comment by plopinou** [comment]
Thank you for your answer, I'm still learning typescript and this indeed correct the problem.
