### ISSUE TITLE
Invoking TypeScript with `--outDir src` makes some source files invisible

### ISSUE THREAD

**Issue by jthemphill** [microsoft/TypeScript#60867]
### 🔎 Search Terms

outDir globalThis declarations exclude include not found error

> TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature

### 🕗 Version & Regression Information

- This changed between versions `5.5.0-dev.20240426` and `5.5.0-dev.20240427`
- This changed in commit or PR https://github.com/microsoft/TypeScript/pull/58335

### ⏯ Playground Link

https://github.com/jthemphill/ts-5.5-repro

### 💻 Code

Run with `tsc --outDir src`.

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "noEmit": true,
    "noImplicitAny": true
  },
  "files": ["src/test.spec.ts"],
  "include": ["./src/**/*"]
}
```

`src/test.spec.ts`:

```ts
globalThis.__IS_CI__ = true;
```

`common.ts`:

```ts
declare global {
  namespace globalThis {
    var __IS_CI__: boolean;
  }
}
export {};
```

### 🙁 Actual behavior

On TS 5.4, the command passes.

On TS 5.5 or newer, the command fails with the error:

```
src/test.spec.ts:5:12 - error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

5 globalThis.__IS_CI__ = true;
```

### 🙂 Expected behavior

I expect both commands to pass.

### Additional information about the issue

* I'm trying to migrate a large codebase off of Typescript 5.3, and this is the last blocker remaining.
* `--outDir src` is passed to `tsc` via a Bazel build rule.
* If `{"outDir": "src"}` is added to `tsconfig.json`, then typechecking will fail on both versions of TypeScript.
  * Therefore, I believe that https://github.com/microsoft/TypeScript/pull/58335 is a legitimate bugfix which stopped TypeScript from ignoring `--outDir src` on the command line.

As I understand it, according to https://github.com/microsoft/TypeScript/issues/58327, `outDir` causes source files to be excluded because otherwise, we'll overwrite the `.d.ts` files we're using as source files.

But if you don't specify `outDir` at all, your output directory will be the same as your source directory anyway, and somehow this won't be a problem. [According to the TypeScript docs](https://www.typescriptlang.org/tsconfig/#outDir):

> If [`outDir` is] not specified, `.js` files will be emitted in the same directory as the `.ts` files they were generated from.

Since we already have *default* behavior where the source and output directories are the same, why does *specifying* `outDir` cause such a different behavior?

**Comment by MartinJohns** [comment]
See: https://www.typescriptlang.org/tsconfig/#exclude

Unless explicitly specified, `exclude` includes `outDir` as a default value.

**Comment by jthemphill** [comment]
Ah, thank you! I may ask to add a link from `outDir` to `exclude` in the docs so that future mes are less confused🙂

**Comment by jthemphill** [comment]
This is the correct answer to my question!
