### ISSUE TITLE
Please add default values to tsconfig.json compiler options specification

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6086]
Please add default values to [tsconfig.json compiler options specification](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options) so it won't be a matter of guessing whether to be required to add a setting.

**Comment by GoToLoop** [comment]
:+1:

**Comment by GamesMaxed** [comment]
Shouldn't this issue be closed now considering it has been done?

**Comment by mhegazy** [comment]
thanks!
