### ISSUE TITLE
Consistency between generic type parameter of extends generic type based on another generic type parameter is not enforced

### ISSUE THREAD

**Issue by Metritutus** [microsoft/TypeScript#60870]
### 🔎 Search Terms

generic parameter extends generic type parameter based on generic parameter

### 🕗 Version & Regression Information

3.3.333 to 5.7.2 (ie the versions supported by Typescript Playground)

### ⏯ Playground Link

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEAqCmEAuBhcUA8sAiYlgD5oBvAXwChzgB7AO2WiUSQEYAuOZtSCDY6AG5gQAV3jtoyAE4BLWgHNopIgF5oteAHdOybpn5DR4jtLmLlACgCUAbkoAzEbWBIZdRswBiT4FmjwADyZaABMYBF10Xhw8QgAaOFx8AgtDMQ5YBJDYjKSwKxJKCnImZG9nC1LWBINhMQAmDhYAFiVbaAB6DugASWhNahEQEP8AgAd4F0YACxkYJGpoezAZEAA6Eq8fLC4ovkE640kkWQUlAhqDo0b1EQBbACN4KXPK5hZLtPgblrabTu6fQGQxGgQmUyQs3mixC8HschkTBAAE8lisQNBIJIRFJ4CjErFJNNBsNoE8ZvBJGA7pT7NQXg9qJCAPxAA

### 💻 Code

```typescript
class TestClass<TData> {}

const test1: TestClass<{ value1: string }> = new TestClass<{ value1: string }>();

function testFunc<T extends TestClass<TData>, TData>(value: T, data: TData) {

}

testFunc(test1, { value2: 14 }); // I would expect this to fail.
testFunc<TestClass<{ value1: string }>, { value2: number }>(test1, { value2: 14 }); // I would expect this to definitely fail as surely TData should be the same for both?
```

### 🙁 Actual behavior

No errors are highlighted for the two calls to `testFunc()`.

### 🙂 Expected behavior

Both calls to `testFunc()` should be highlighted as errors.
The first call should fail because `{ value2: number}` is not the `TData` type used for the `TestClass<TData>` instance assigned to `test1`.
The second call should fail highlighting the generic parameter type inconsistency for `TData`.

### Additional information about the issue

I am attempting to create a generic method with two generic type parameters and two parameters using those generic types, where the generic type of the second is tied to the generic type of the first:

```typescript
class TestClass<TData> {}

function testFunc<T extends TestClass<TData>, TData>(value: T, data: TData) {
}
```

However, when attempting to use it there does not seem to be any consistency enforced between the TData parameters:

```typescript
const test1: TestClass<{ value1: string }> = new TestClass<{ value2: string }>();

testFunc(test1, { value1: 14 }); // I would expect this to fail.
testFunc<TestClass<{ value1: string }>, { value2: number }>(test1, { value2: 14 }); // I would expect this to definitely fail as surely TData should be enforced as the same for both?
```

Explicitly specifying the types incorrectly as shown in the second call to `testFunc()` above does not result in any apparent errors either.

I am unsure if the behaviour I am seeing is a bug or if this is something I am doing incorrectly.

**Comment by MartinJohns** [comment]
See: https://github.com/microsoft/typescript/wiki/faq#why-do-these-empty-classes-behave-strangely

**Comment by Metritutus** [comment]
> See: https://github.com/microsoft/typescript/wiki/faq#why-do-these-empty-classes-behave-strangely

I didn't think it was this as the generic types being used are not empty?

I cannot do this for example:
```typescript
let test: { value1: string } = { value2: 14 };
```
Or this:
```typescript
let test2: { value1: string } = { value1: 14 };
```

Unless I'm missing something?

**Comment by MartinJohns** [comment]
> I didn't think it was this as the generic types being used are not empty?

You're not using the genetic type `TData` anywhere, so it might as well not exist. TypeScript uses structural typing, and the structure of `TestClass<string>` and `TestClass<number>` is absolutely identical. As far as TypeScript is concerned these types are identical and thus compatible.

**Comment by Metritutus** [comment]
> > I didn't think it was this as the generic types being used are not empty?
> 
> You're not using the genetic type `TData` anywhere, so it might as well not exist. TypeScript uses structural typing, and the structure of `TestClass<string>` and `TestClass<number>` is absolutely identical. As far as TypeScript is concerned these types are identical and thus compatible.

Aaaah, now I understand, you're referring to the `TData` parameter on `TestClass`, not the `TData` parameter on `testFunc()`.

Adding a property to `TestClass` that uses `TData` does indeed subsequently cause the expected errors to appear.

I didn't anticipate the absence of the usage of `TData` on `TestClass` would not be negated by the use of `TData` in `testFunc` if the generic type constraint made it clear that the generic type was supposed to be the same for both.

**Comment by MartinJohns** [comment]
The inferred type for `TData` on your function can be a union type as well, so it could easily be `{ value1: string } | { value2: number }`, making the invocation perfectly valid.

As the FAQ mentions, you should generally never have unused type arguments.

Everything working as intended.

**Comment by Metritutus** [comment]
> The inferred type for `TData` on your function can be a union type as well, so it could easily be `{ value1: string } | { value2: number }`, making the invocation perfectly valid.
> 
> As the FAQ mentions, you should generally never have unused type arguments.
> 
> Everything working as intended.

In reference to your last sentence, that's fine, I'm not disputing that it is working as intended - as I stated in the original post, I was unsure if the behaviour I was encountering was a bug or something I was doing incorrectly.  As has been made quite clear, it is the latter.

Although I did not use the generic type in the class definition, I did not make the link between this behaviour and the behaviour specified in the FAQ (which I did check!), whose example only shows two instances of the _same_ class, `Something<T>`, whereas the `TData` parameter was being directly used in my `testFunc()` definition.

In attempting to further my understanding of this behaviour, I attempted the following:
```typescript
class Something<TData> { }

function testFunc<TData>(value: Something<TData>, data: TData) {

}

testFunc(new Something<number>(), 'test');
```

Interestingly, this errors for the second parameter, claiming correctly that `Argument of type 'string' is not assignable to parameter of type 'number'`.  It looks like it inferred `TData` as being of type `number`.

If I explicity specifiy `TData` as `string` however then I see no error (because, I assume, as per the above explanations, `Something` itself doesn't use the type parameter and thus does not care):
```typescript
testFunc<string>(new Something<number>(), 'test');
```

**Comment by Metritutus** [comment]
For the benefit of anyone happening upon this in the future, this is how I altered the definition of `TestClass` earlier to resolve the problem:
```typescript
class TestClass<TData> { private _?: TData; }
```

What I was actually originally working on was a generic type alias, but it's the same issue, and so this, for example, would be the approach there:
```typescript
export type TestType<TData> = { _: TData }
```

Hopefully my stumblings here help someone else in the future.

Thank you for your explanations, @MartinJohns.
