### ISSUE TITLE
TSC fails when having Angular2 referenced in Visual Studio project

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6087]
After having set tsconfig.json according to documentation, TSC fails, claiming that it required Angular2 TypeScript sources:

![typescript compiler fails](https://cloud.githubusercontent.com/assets/9283914/11766917/585e7442-a19b-11e5-9f28-c4feae8b526e.png)

Angular2 isn't part of my project. Providing a `rootDir` option to tsconfig.json should even confirm that the Angular2 sources are *not* supposed to be compiled by TSC.

The default Visual Studio TSC configuration should exclude `node_modules` path by default. Why does it still try to compile the Angular2 module?

**Comment by DanielRosenwasser** [comment]
The default `tsconfig.json` has `node_modules ` excluded by default, but it is not implicit because not every user necessarily wants that behavior. You'll need to add it yourself.

**Comment by SetTrend** [comment]
Thank you for enlightening me on this.

I see. Please allow me these follow-up questions:

 * Can I edit the *default* `tsconfig.json` file on my machine?
 * Is there a switch available in Visual Studio (Tools > Options ...) to have TSC log it's actions to the output window messages like:
    * `Searching @ ...\...\ due to 'rootDir' setting`
    * `Ignoring folders '...\...\', '...\...\' due to 'exclude' setting`
    * ...
 * Doesn't the `rootDir` setting restrict the search path to that root dir? If it doesn't, then why? Which switch does?

**Comment by SetTrend** [comment]
I just moved the `tsconfig.json` file up the hierarchy to be applied only to the `/scripts/` folder, but to no avail: Although the `/node_modules/` folder is now outside the `tsconfig.json`, it's still being considered by TSC.

![typescript compiler fails](https://cloud.githubusercontent.com/assets/9283914/11789848/f3be1c6e-a298-11e5-8c7b-4728653719bd.png)

I wonder how the statement given in #3645 ("you can have multiple tsconfig today, each pointing to overlapping set of files. so one at src\tsconfig.json, one in tests\tsconfig.json, etc.") works.

**Comment by DanielRosenwasser** [comment]
> Can I edit the default tsconfig.json file on my machine?

You can feed options into `tsc` when you use `tsc --init`.

> Is there a switch available in Visual Studio (Tools > Options ...) to have TSC log it's actions to the output window

Unfortunately not as of present, though @paulvanbrenk might want a heads up on that.

> Doesn't the rootDir setting restrict the search path to that root dir? If it doesn't, then why? Which switch does?

I'm not entirely certain; `rootDir` will inform the directory structure to use when using `outDir`. While it would make sense to inform the compilation scope here, I think it would be ideal to keep the behavior simple.

______

As a follow up, let me just confirm the major problem here: the Angular 2 `.ts` files in `node_modules` are giving errors when using `rootDir`, correct?

**Comment by billti** [comment]
I'm not sure I'm fully following. Are you able to provide the project so I can load it up and see what is happening first hand? Is this only a problem if the `rootDir` option is provided?

If interested, I just got a skeleton ASP.NET 5 RC with Angular2 Beta solution running VS2015. I uploaded it to https://github.com/billti/ASPNET5-with-Angular2 . Take a look and see if anything in here helps in terms of configuration or setup.

**Comment by SetTrend** [comment]
Yes, it looks like the error still appears after having set the "exclude" config setting.

Here's a link to the respository: https://github.com/SetTrend/AspNet.Security.OpenIdConnect.Samples

The actual project I'm working with within this solution is @ "...\samples\Multiple Projects Sample\Clients\AngularClient\"
