### ISSUE TITLE
what are the guidelines to adding new error codes?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6089]
What are 1000-2000-3000-4000-5000-6000 ranges for?

**Comment by DanielRosenwasser** [comment]
It used to matter, but now it's kinda sorta just about grouping related things somewhat closely.

For instance, I'd place something [regarding warning users of parameter covariance](https://github.com/Microsoft/TypeScript/issues/3523#issuecomment-164284633) as soon after the `noImplicitAny` errors as possible.

**Comment by aleksey-bykov** [comment]
Thanks!

**Comment by mhegazy** [comment]
for future references here are the meanings:https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#diagnostic-message-codes

**Comment by aleksey-bykov** [comment]
Thanks!

Offtopic: I am surprised you encourage the use of the map and filter
functions over arrays but say nothing about fold/reduce

**Comment by DanielRosenwasser** [comment]
I think it usually turns out that folds are a little less readable, and are mostly useful when you want to "atomically" initialize a value. It's all subjective, but this is coming from a guy who really likes Haskell, SML, and F# if that counts for anything.

**Comment by aleksey-bykov** [comment]
i wish for once someone defined "readable" for me
will you be that guy?
what audience are we keeping in mind saying "readable"?
ugly truth is, FP isn't a mainstream paradigm whereas TypeScript is a mainstream language...






back to work.
