### ISSUE TITLE
How to make an isomorphic single file node module without Browserify

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#6090]
Proposal of a new wiki content. TypeScript 1.8 can make a isomorphic single file node module without Browserify using a following snippet. It will be a good PR point of TypeScript:

https://gist.github.com/falsandtru/390683f4880aa3e4467a

Sample product:

https://github.com/falsandtru/arch-stream

Overview of changes for switching from Browserify to TypeScript:

https://github.com/falsandtru/arch-stream/compare/v0.0.36...v0.0.40
See `arch-stream.csproj`, `arch-stream.ts`, `gulpfile.js`, and `package.json`. Others are noises.

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh and @vladima, would this be something we want to put out as a best practice?

**Comment by falsandtru** [comment]
Design of module system compatibility and interoperability:

Module|Browser|Browserify|Node|AMD
---|---|---|---|---
Compatibility|Yes|Yes|Yes|Maybe weak
Interoperability|Both|Both|Both|Maybe weak
Import|`window['module']`|`require('module')`|`require('module')`|`define(['module'], ...)`
Export|Global variable|Alias mapping|Native|RequireJS

- Unsupport the `module` object in Node(Unsupport `export =` syntax.).
- Browserify requires the mapping of global variables for importing of global objects.
- AMD module loader may conflict local module paths such as `src/...`.

**Comment by falsandtru** [comment]
How about?

**Comment by DanielRosenwasser** [comment]
I'm not clear on what that chart is supposed to tell users and why it would be significant to a TypeScript user. Can you elaborate a little bit?

**Comment by falsandtru** [comment]
What should I do?

**Comment by mhegazy** [comment]
@falsandtru can you elaborate on what the wiki page should be about? what information is needed?

**Comment by falsandtru** [comment]
@mhegazy is this pr accepted, or not accepted? Where can I add this content in wiki pages, new page? I don't know that well.

**Comment by mhegazy** [comment]
depending on the content. but https://github.com/Microsoft/TypeScript-Handbook would be the right place.

**Comment by mhegazy** [comment]
i do not think @DanielRosenwasser or I understand the original request though.
