### ISSUE TITLE
use `const` rather than `var` for es6 module grammar when target es6 and the module is commonjs

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#6092]
eg:
```typescript
import * as url from "url";
let a = url.resolve("http://example.com/", "a");
```
Now the generated js is:
```typescript
var url = require("url");
let a = url.resolve("http://example.com/", "a");
```
I think it is better:

```typescript
const url = require("url"); // changes here
let a = url.resolve("http://example.com/", "a");
```

considering the url is a `const`, no bad things happen:

```typescript
import * as url from "url";
url = ""; // the error here is "Invalid left-hand side of assignment expression"
```

history:

~~suggest `let`~~

**Comment by kitsonk** [comment]
Actually, the block scoping of `let` and the temporal dead zone effects would likely cause issues if that were used.  According to the [ES6 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-static-semantics-importentriesformodule) imports actually behave more like this:

```js
(function (url) {
    let a = url.resolve("http://example.com/", "a");
})(url);
```

I think technically rules against redeclaration do not apply, but considering the spec for the module loader is [still churning away](https://github.com/whatwg/loader/issues/101), my opinion is that changing semantics now would be premature.

What there a particular reason you felt it was better?

**Comment by plantain-00** [comment]
For ES6 js code, basically all variables are declared by `let` or `const`, eg `a`(above), but the `url`(above) is a `var`(is it a variable?), so use `let` or `var` may be a good idea.

So it's just a reason that it looks good.

**Comment by mhegazy** [comment]
thanks @plantain-00!
