### ISSUE TITLE
Docs and VS config options of `--suppressImplicitAnyIndexErrors `

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6093]
Please add a `--suppressImplicitAnyIndexErrors ` flag to:

https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript
https://github.com/Microsoft/TypeScript/wiki/Roadmap

And please add a `Suppress implicit any index errors ` checkbox after an `Allow implicit any types` checkbox in Visual Studio.

**Comment by mhegazy** [comment]
Not all options are visible on the project property pages. only the ones deemed common. you can still set all the options either in a tsconfig.json, or manually in your project file (see the MSBuild properties corresponding to compiler options: https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects)
