### ISSUE TITLE
Define function, which transforms an object, keeping keys

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#6095]
I need to define a function, which accepts an object of this type:
```
interface Source<A> {
    [index: string]: A
}
```
and transforms that object, keeping the keys, but replaces a values:
```
interface Target<B> {
    [index: string]: B
}
```
and I also want to keep typechecking for that case. This is JS example:
```
function transform(source) {
    var result = {}
    Object.keys(source).forEach((key) => {
        result[key] = source[key] + "prefix"
    })
}

var target = transform({
    "key1": 1,
    "key2": 2,
})

// now target has a {"key1": "1prefix", "key2": "2prefix"}

var three = target.key3 // I want to get type error here on compile-time
```

Any way to do that?

**Comment by RyanCavanaugh** [comment]
There isn't a way to represent this in the type system today.

**Comment by Strate** [comment]
Any plans to future? Maybe some existing issue?

**Comment by SaschaNaz** [comment]
This may be close but the problem here is the value types of `key1` and `key2` is not `string|number` but `number`.

```typescript
interface SourceOrTarget<T> {
    [index: string]: T
}

function transform<T extends SourceOrTarget<string|number>>(source: T) {
    var result = {} as T;
    Object.keys(source).forEach((key) => {
        result[key] = source[key] + "prefix"
    })
	return result;
}

var target = transform({
    "key1": 1,
    "key2": 2,
})

// now target has a {"key1": "1prefix", "key2": "2prefix"}

var three = target.key3 // error here
```

**Comment by Strate** [comment]
This is not about `string|number`, this is more about keeping object shape replacing types of values. The real-world case is trannsforming object of plain strings to object of complex objects, i.e.:

```
let out = defineMessages("idPrefix.", {
    id1: "Some message"
})

out === {
    id1: {
        id: "idPrefix.id1",
        defaultMessage: "Some message"
    }
}
```

This function transforms `{[index: string]: string}` to `{[index: string]: { id: string, defaultMessage: string }}`. I want to keep keys in this case.

I don't know how this can be achieved :)

**Comment by myitcv** [comment]
@Strate see https://github.com/Microsoft/TypeScript/issues/4967#issuecomment-153810944 for a related question
