### ISSUE TITLE
System.register __moduleName support

### ISSUE THREAD

**Issue by guybedford** [Microsoft/TypeScript#6097]
I don't mean to be making work, but I think it's worth generically supporting this `__moduleName` identifier for System.register at this point and it is a relatively simple addition to the format of the form:

```javascript
System.register([], function(_export, __moduleName) {
  // ...
});
```

This allows use cases like relative dynamic loading relative to the module being executed. The argument can even be omitted when it is not needed with binding detection as well.

Up until now I've been avoiding this hoping to make the second argument to System.register the ES loader module context which will provide similar functionality, but I don't think this contextual spec will be appearing for quite some time yet and the use case needs to be properly supported in the mean time.

For the original issue see https://github.com/systemjs/builder/issues/416, and just let me know if there are any questions at all.

**Comment by capaj** [comment]
:+1:

**Comment by DanielRosenwasser** [comment]
@guybedford is this something that TypeScript users are supposed to use directly? I'm not familiar with the intended usage here.

**Comment by guybedford** [comment]
Yes this is a user API, for use cases like for relative dynamic loading:

```javascript
export function loadNewStuff() {
  return System.import('./parent-relative', __moduleName)
  .then(function(stuff) {
    // ...
  });
}
```

**Comment by DanielRosenwasser** [comment]
Spoke offline with @vladima about this and this seems reasonable, but to support this automatically, we'd have to specially support a hard-coded `__moduleName` in the type system, which we'd need to discuss.

The more-likely workaround is that that users would need to define an uninitialized `var`-scoped variable named `__moduleName` like so:

```ts
declare var __moduleName: string;
```

Given that, I'm going to say we should wait on @mhegazy to return to make that call.

**Comment by guybedford** [comment]
Thanks for the feedback. A user-level declaration like that sounds fine to me.

**Comment by guybedford** [comment]
Any update here?

**Comment by DanielRosenwasser** [comment]
@mhegazy will be available again by the beginning of next week, and I'm mostly waiting on that.

**Comment by mhegazy** [comment]
thanks @guybedford!

**Comment by DanielRosenwasser** [comment]
@mhegazy why is this considered a breaking change?

**Comment by guybedford** [comment]
@mhegazy many thanks for the update! Unfortunately we've since been discussing an adjustment to this in the mean time. It may be worth reverting this for https://github.com/Microsoft/TypeScript/issues/6359.

**Comment by mhegazy** [comment]
this has been reverted in https://github.com/Microsoft/TypeScript/pull/6362

**Comment by arloduff** [comment]
`declare var __moduleName: string` works, but is it possible to specify the existence of this variable in a configuration, so we don't have to include this line in every single component file?

**Comment by mhegazy** [comment]
> but is it possible to specify the existence of this variable in a configuration, so we don't have to include this line in every single component file?

you just need to include it in one global file (i.e. a file with no import or export) or just a `.d.ts` and all your files will see it.

alternatively define it in one of your files as:
```ts
declare global {
    var __moduleName: string
}
```

**Comment by arloduff** [comment]
@mhegazy Thanks! That works.
