### ISSUE TITLE
Inconsistent "else" after compiling

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#6099]
Sometimes `else` will come in the next line, sometimes it'll stay in the same line, like this generated UMD:

```js
(function (factory) {
  if (typeof module === 'object' && typeof module.exports === 'object') {
    var v = factory(require, exports); if (v !== undefined) module.exports = v;
  } 
  else if (typeof define === 'function' && define.amd) {
    define(['require', 'exports'], factory);
  }
})
```

those will stay on the same line:

```js
  for (var i = 0; i < path.length; i++) {
    var j = path[i];

    if (isObject(obj) || isArray(obj)) {
      if (ownPropertiesOnly) {
        if (_hasOwnProperty.call(obj, j)) {
          obj = obj[j];
        } else {
          return false;
        }
      } else {
        if (j in obj) {
          obj = obj[j];
        } else {
          return false;
        }
      }
    } else {
      return false;
    }

  }
```

most of the time, the `else` is in the same line as the `}` and the `{` as expected. can it be made consistent? `standard` doesn't like this

**Comment by DanielRosenwasser** [comment]
Could you post the code sample that generates the latter example?

**Comment by pocesar** [comment]
actually, in closer look, the `else` and `else if` are always on the next line, could them be made to the same line? (or even change the way the compiled code is generated, through a configuration like jscs?)

**Comment by DanielRosenwasser** [comment]
Sorry, that's probably better served by another external tool, like a JS pretty printer.
