### ISSUE TITLE
Unable to set sourceRoot in tsconfig

### ISSUE THREAD

**Issue by flyon** [Microsoft/TypeScript#6101]
I'm trying to start using tsconfig.json, which works perfectly, except that it does not pick up "sourceRoot", making it impossible for me to debug in the current setup. 

My editor (WebStorm) only allows either a compiler command, OR a tsconfig. So right now I cannot switch without support for sourceRoot in tsconfig

**Comment by DanielRosenwasser** [comment]
@flyon does `sourceRoot` get respected by `tsc` on its own? Which version of the TypeScript compiler are you running?

**Comment by mhegazy** [comment]
@flyon please reactive if this still an issue, and provide more information.
