### ISSUE TITLE
VS freezes up when trying to perform a semantic operation within the first 10 seconds of opening Monaco

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6103]
1. Clone VS Code
2. Open a file
3. Try to get quick info
4. VS freezes

**Comment by vladima** [comment]
@DanielRosenwasser can you make a dump using [procdump](https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx) at the moment when VS stops responding?

**Comment by vladima** [comment]
this looks like a consequence of https://github.com/dotnet/roslyn/issues/7403, so resolving it as external
