### ISSUE TITLE
Incorrect parsing for comma-separated interface/type literal properties with no type annotation

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#6108]
The following snippets should be equivalent:

``` ts
interface I {
    a; // semicolon
    b: number,
    c: string;
}
```

``` ts
interface I {
    a, // comma
    b: number,
    c: string;
}
```

![image](https://cloud.githubusercontent.com/assets/972891/11823305/292f9b72-a328-11e5-8b18-b9a7a1f6bf9d.png)

![image](https://cloud.githubusercontent.com/assets/972891/11823326/3cf6a3c6-a328-11e5-97e4-1d704c528ed2.png)

**Comment by j-oliveras** [comment]
It seems to be solved: [playground](https://www.typescriptlang.org/play/#src=interface%20I1%20%7B%0D%0A%20%20%20%20a%3B%20%2F%2F%20semicolon%0D%0A%20%20%20%20b%3A%20number%2C%0D%0A%20%20%20%20c%3A%20string%3B%0D%0A%7D%0D%0Ainterface%20I2%20%7B%0D%0A%20%20%20%20a%2C%20%2F%2F%20comma%0D%0A%20%20%20%20b%3A%20number%2C%0D%0A%20%20%20%20c%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Aconst%20a%3A%20I1%20%3D%20%7B%0D%0A%20%20%20%20a%3A%201%2C%0D%0A%20%20%20%20b%3A%201%2C%0D%0A%20%20%20%20c%3A%20''%0D%0A%7D%0D%0A%0D%0Aconst%20b%3A%20I2%20%3D%20a%3B%0D%0A).

**Comment by Andarist** [comment]
I can also confirm that this one is already fixed, cc @jakebailey
