### ISSUE TITLE
Proposal: Support for optional chaining as in Swift

### ISSUE THREAD

**Issue by cuterajat26** [Microsoft/TypeScript#6112]
Proposal to implement forced and optional unwrapping in Typescript to avoid boilerplate null checking code.This is a feature in Apple's swift language and very helpful in following clean code practices.

Reference -https://developer.apple.com/library/mac/documentation/Swift/Conceptual/Swift_Programming_Language/OptionalChaining.html

**Comment by DanielRosenwasser** [comment]
Thanks for filing, but this is a duplicate of #16.
