### ISSUE TITLE
__awaiter is not defined

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6113]
Was there something changed recently on the `async/await` for typescript? I'm using `typescript@next` to compile my project.

With below version it works fine:
```
$ tsc --version
Version 1.8.0-dev.20151210
```

But for this version it doesn't:
```
$ tsc --version
Version 1.8.0-dev.20151216
```

I got a runtime error:
```
ReferenceError: __awaiter is not defined
```

And in my code I have a bunch of object literals that has async functions:
```
let a: {
  f: async () => { ... }
}
```

I'm targetting es6. Though I cannot produce a self-contained test. Even though I compile the whole file excluding dependecies it includes the `__awaiter`. Only when I compile the whole project, just one file misses to have `__awaiter` on top of the file.

There must have been some very recent change. Since my CI started to bark today.

**Comment by DanielRosenwasser** [comment]
@rbuckton any clue?

**Comment by DanielRosenwasser** [comment]
@tinganho looks like you have a typo - did you mean

```ts
let a = {
  f: async () => { /*...*/ }
}
```

I get an awaiter here.

**Comment by rbuckton** [comment]
@tinganho I am also unable to reproduce this issue. We recently fixed an issue where __awaiter was added to the top of every file following a file with an async function, even when those files did not contain an async function. Could it be that the file in question does not have a valid async function?

**Comment by tinganho** [comment]
@rbuckton I think they are correctly defined. There are no compile errors though. 

I think I narrowed down the root cause. The one file that is not including an `__awaiter` on the top has some circular dependencies. At least, when I remove the circular dependency the `__awaiter` comes back.

**Comment by tinganho** [comment]
@rbuckton @DanielRosenwasser I could produce a self contained test now:

`a.ts`:
```typescript
import { b } from './b';
export let a = {
    f: async () => {
        await b.f();
    }
}
```
`b.ts`
```typescript
import { a } from './a';
export let b = {
    f: async () => {
        await a.f();
    }
}
```
`shell:`
```
tsc a.ts --target es6
```

`output of a.js`:
```javascript
import { b } from './b';
export let a = {
    f: () => __awaiter(this, void 0, Promise, function* () {
        yield b.f();
    })
};
```

No, `__awaiter` on `a.js`.

**Comment by DanielRosenwasser** [comment]
Confirmed; `b.js` is getting an awaiter, but not `a.js`.
