### ISSUE TITLE
Transferring props in TSX

### ISSUE THREAD

**Issue by xmehaut** [Microsoft/TypeScript#6115]
Hello,
There is a very useful syntactic feature of React JSX which misses in typescript react, ie the ability to transfer props to chlidren: 
```
<Component {...this.props} more="values" />
 ````
(https://facebook.github.io/react/docs/transferring-props.html)

Could it be possible to add it? 
regards

**Comment by adidahiya** [comment]
This is called JSX spread and it is supported by TypeScript...

**Comment by xmehaut** [comment]
normally yes, but with 'this.props' an error is indicated

**Comment by adidahiya** [comment]
I think this is fixed in the latest version of eclipse-typescript, but if not, please file an issue on the project here: https://github.com/palantir/eclipse-typescript

**Comment by derekcicerone** [comment]
@adidahiya Is this fixed in a newer version of TypeScript? The Eclipse plugin has no special functionality for JSX...

**Comment by xmehaut** [comment]
mea culpa :(
It actually works... What I did it was to port a javascript code into typescript... but I forgot that typescript makes a types checking even on the {...this.props} statement, i.e. the props hich have to be destructured into the component are checked to see if the attributes are compatible to the one the component accepts.... What was accepted in javascript, was not anymore in typescript...for safe... 
It is a good case to show that we may make unsafe code in javascript...

sorry for the inconvenience
xavier
