### ISSUE TITLE
"use strict" should be emitted after triple slash references

### ISSUE THREAD

**Issue by yuit** [Microsoft/TypeScript#6116]
currently we emit 
```js
"use strict"
/// <reference-path ....
```

Thought triple-slash reference has no particular meaning in js. It is desirable to emit it correctly as a good example.

**Comment by ahejlsberg** [comment]
The issue basically is that triple slash references are ignored after the first token in a file, so emitting `"use string"` before triple slash references silently causes the references to have no effect.

**Comment by mhegazy** [comment]
This should be fixed now.
