### ISSUE TITLE
Code Generation using Annotation Processors (JSR 269)

### ISSUE THREAD

**Issue by ENikS** [Microsoft/TypeScript#6119]
I would like to propose a feature: 
It would be extremely nice if TypeScript compiler allowed code generation and annotation processing similar to JSR 269.

Code in TS relies on runtime reflection for everything. If some of the analysis done at compile time and properly statically linked code generated, it would have huge performance increase during run time.
For example of successful implementation of this approach look and Google's Dagger 2.

**Comment by mhegazy** [comment]
With issue https://github.com/Microsoft/TypeScript/issues/5595 in place, a lot of these scenarios should be enabled.
