### ISSUE TITLE
Getting Promise implementation for async methods from a property of the current class

### ISSUE THREAD

**Issue by thorn0** [microsoft/TypeScript#6122]
As per @rbuckton in #3364:

> For an async function, the return type annotation must be both a type and a value in the same scope.

It's nice as it allows using any compatible Promise implementation. However, it requires that this implementation should be assigned to a variable in the scope. Unfortunately, this doesn't always work well with AngularJS (Angular 1.x), whose approach discourages globals in favour of dependency injection for the sake of testability. Consider this code of an AngularJS controller:

``` ts
type $q<T> = Promise<T>;
class MainController {
    public name: string;
    constructor(private $q: PromiseConstructor, private myService: MyService) {}
    async fn1(): $q<void> {
        this.name = await this.myService.fn1();
    }
}
module.angular('myApp').controller('MainController', MainController);
```

The promise implementation `$q` is injected to the constructor by AngularJS here. Of course, it doesn't work as TypeScript looks for `$q`, not for `this.$q`. So as for now, the only solution for this situation is saving `$q` to a global variable. Please consider adding the property lookup for async methods.

**Comment by DanielRosenwasser** [comment]
You mean being able to write the following?

```ts
    async fn1(): this.$q<void> {
        this.name = await this.myService.fn1();
    }
```

**Comment by thorn0** [comment]
I don't think a new syntax is needed. Now when the TypeScript compiler sees this:
```ts
    async fn1(): $q<void> {
        this.name = await this.myService.fn1();
    }
```
it looks for the variable `$q`. I propose that it should look first for the property `$q` within the current class, and then for the variable if the property isn't found. *Not* having a special syntax for this would, in particular, allow omitting the type declaration if `$q` is assigned to the property `Promise`.
```ts
class MainController {
    public name: string;
    constructor(private Promise: PromiseConstructor, private myService: MyService) {}
    async fn1() { // the return type is inferred as Promise<void>
        this.name = await this.myService.fn1();
    }
}
module.angular('myApp')
    .factory('Promise', $q => $q)
    .controller('MainController', MainController);
```
would be transpiled to
```js
    // ...
    fn1() {
        return __awaiter(this, void 0, this.Promise, function* () {
            this.name = yield this.myService.fn1();
        });
    }
    // ...
```
Angular users would *really* appreciate such clean code.

However, there is a risk with this code that the developer can forget to inject `Promise` to the constructor so that the global variable `Promise` would be silently used by the TS compiler instead of the property as there is an ambient declaration of this variable in `lib.es6.d.ts`. Is there a way to 'undeclare' it somehow?

**Comment by thorn0** [comment]
What if in place of the current logic, we had some kind of mapping in tsconfig: 
`async return type -> promise constructor expression`
?

```json
"promiseConstructors": {
    "ng.IPromise": "this.$q",
    "QQPromise": "this.$qq"
}
```

After a successful lookup, the found expression should be type-checked, so that in the example above, we have a compiler error if the current class doesn't have the `$q` property.

IMHO such a mapping looks more explicit and less magic than the current logic.

**Comment by thorn0** [comment]
Solved this by overriding the `__awaiter` helper. Fortunately, the context (`this`) is passed to `__awaiter`, so `this.$q` can be accessed:
```ts
const __awaiter = (
	thisArg: { $q: PromiseConstructor },
	_arguments: any,
	P: any,
	generatorFunction: GeneratorFunction
) => {
	P = thisArg.$q;
	if (!P) throw Error('$q not defined in ' + thisArg.constructor.name);
	return new P<any>((resolve, reject) => {
		// ... the rest in unchanged
	});
};
```
