### ISSUE TITLE
Annoying autocompletions of Generics

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript#6123]
Press enter key:

``` ts
new Array<n
```

expected:

``` ts
new Array<number
```

actual:

``` ts
new Array < number
```

**Comment by DanielRosenwasser** [comment]
That happens to be a combination of auto-formatting on the enter key even though a completion list was present.

**Comment by mhegazy** [comment]
it is a valid production, not sure if there is much we can do here.

**Comment by DanielRosenwasser** [comment]
I don't think this should be closed yet.

Isn't there a way to ensure that we don't pick up on certain key presses when a completion list is present? @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
> Isn't there a way to ensure that we don't pick up on certain key presses when a completion list is present?

Code in question is here:

Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller_Commit.cs

line 124:

```c#
            var document = this.SubjectBuffer.CurrentSnapshot.GetOpenDocumentInCurrentContextWithChanges();
            var formattingService = document.GetLanguageService<IEditorFormattingService>();

            var commitCharTriggersFormatting = commitChar != null && 
                    (formattingService?.SupportsFormattingOnTypedCharacter(document, commitChar.GetValueOrDefault()) 
                     ?? false);

            if (formattingService != null && (item.ShouldFormatOnCommit || commitCharTriggersFormatting))
```

We probably want to fix things such that *if* the enter is not actually sent through to the editor, then formatting doesn't happen.  If the enter *is* sent through to the editor, then it would be appropriate to format here (as that's what you would get if you hit enter without completion up).

Do you guys send enter through?  Or does the completion list capture it and leave you on the same line?

**Comment by CyrusNajmabadi** [comment]
If you guys send enter through, then i would resolve this as the correct behavior.  If you don't, then you can likely fix this on our end.  Note: we're in escrow now for Update2, so it's unlikely to make it in for that release.  But this could go out for the next release after that.

**Comment by paulvanbrenk** [comment]
@CyrusNajmabadi This looks to be case where the enter is handled by something that's not supposed to handle it... this is our enter key rule `defaultEnterKeyRule: EnterKeyRule.Never` any ideas?

**Comment by CyrusNajmabadi** [comment]
Sounds like a bug in Roslyn then.  Can you file something on our end about providing a way for languages to say that they don't want formatting to occur in this case?

**Comment by RyanCavanaugh** [comment]
This doesn't seem to be affecting anyone
