### ISSUE TITLE
Destructuring of Array argument in arrow function requires parentheses 

### ISSUE THREAD

**Issue by Dynalon** [Microsoft/TypeScript#6128]
I don't know if this is a bug, a feature request or not possible to implement at all, but it would be nice if destructuring of a single array argument in an arrow function would work without the parentheses.

A real-world code example taken from dealing with angular promises:
```typescript
interface IPromise<T> {
	then<TResult>(successCallback: (promiseValue: T) => IPromise<TResult>|TResult);
}
interface IQService {
	all<T>(promises: IPromise<any>[]): IPromise<T[]>;
}

let $q: IQService;
let p1: IPromise<any>, p2: IPromise<any>;

// works with parentheses
$q.all([p1, p2]).then(([r1, r2]) => {});

// syntax error without parentheses
$q.all([p1, p2]).then([r1, r2] => {});

```
Tested locally with TS 1.7.5. (update: fixed signature of IPromise interface)

**Comment by falsandtru** [comment]
It would be a es6 specification.

Destructuring declaration is not BindingIdentifier.

> ArrowParameters[Yield] :
BindingIdentifier[?Yield]
CoverParenthesizedExpressionAndArrowParameterList[?Yield]

http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions

>     someArray.map([x,y] => x+y)   // SyntaxError
    someArray.map(([x,y]) => x+y) // OK

http://www.2ality.com/2015/01/es6-destructuring.html

**Comment by DanielRosenwasser** [comment]
Yup; to elaborate, you were expecting a *BindingPattern*. See http://tc39.github.io/ecma262/#prod-CoverParenthesizedExpressionAndArrowParameterList.
