### ISSUE TITLE
Question about type parameter assignment error with inheritance

### ISSUE THREAD

**Issue by fzzzt** [Microsoft/TypeScript#6133]
I have something like this:
```
interface Foo {
  state(): any;
}
class GenericTable<A> implements Foo {
  public state() { ... }
}
class MyTable extends GenericTable<A> { ... }
static function DoStuff(foo: Foo) { ... }

DoStuff(MyTable);
```

I get these errors in VS 2015:

```
Argument of type 'typeof MyTable' is not assignable to parameter of type 'Foo'.
Argument of type 'typeof MyTable' is not assignable to parameter of type 'Foo'.
  Property 'state' is missing in type 'MyTable'.
```

This is using TSX in VS with `tsc` 1.7.5. Using the `as` operator doesn't help. It would seem that this should work but it isn't realizing that Table ultimately does implement Foo and should be able to be cast to that, or maybe my assumption is invalid, or maybe the generic piece in the middle is causing a problem. Is it possible to do this?

**Comment by ahejlsberg** [comment]
You're passing the `MyTable` *constructor function* to a function that expects a `MyTable` *instance*. You need to write:

```typescript
static function DoStuff(foo: Foo) { ... }

DoStuff(new MyTable());
```

Or, if you actually intend to pass the constructor function, you need to write something like:

```typescript
static function DoStuff(foo: new () => Foo) { ... }

DoStuff(MyTable);
```
