### ISSUE TITLE
Method type declarations violate a es6 specification

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6138]
``` ts
var es5obj = {
    method: function(){}
};
var es6obj = {
    method(){}
};

'prototype' in es5obj.method; // true
new es5obj.method(); // ok

'prototype' in es6obj.method; // false
new es6obj.method(); // TypeError: es6obj.method is not a constructor
```
1. Methods cannot call with `new` keyword.
2. Methods must not have a `prototype` property.

Class declarations also have same problems.

``` ts
class C {
    m() {
    }
}
var c: C;
c.m.prototype; // should be a compile error
new c.m(); // should be a compile error
```

> 14.3.9 In ECMAScript 2015, the function objects that are created as the values of the [[Get]] or [[Set]] attribute of accessor properties in an ObjectLiteral are not constructor functions and they do not have a prototype own property. In the previous edition, they were constructors and had a prototype property.

http://www.ecma-international.org/ecma-262/6.0/

**Comment by DanielRosenwasser** [comment]
It says functions created for get/set accessors, which these functions aren't, so it's not clear that this is actually a problem.

**Comment by falsandtru** [comment]
I could not find a just said section about this behavior. This spec is a closest explanation about this behavior. I thought this is spec because there is this behavior in chrome and firefox. But edge has not this behavior. Sorry, now I cannot know that which implementation reflects a spec.

**Comment by DanielRosenwasser** [comment]
> now I cannot know that which implementation reflects a spec.

That's the fun of it though! :smile:

**Comment by DanielRosenwasser** [comment]
@bterlson any clue what this section corresponds to specifically?

**Comment by vladima** [comment]
spec is clear (at least regarding to prototype) and TypeScript should be more strict:
[DefineMethod](https://tc39.github.io/ecma262/#sec-runtime-semantics-definemethod) accepts optional parameter `functionPrototype` that is not passed during [PropertyDefinitionEvaluation](https://tc39.github.io/ecma262/#sec-method-definitions-runtime-semantics-propertydefinitionevaluation)

**Comment by falsandtru** [comment]
I checked v8 and spidermonkey bug tracker but it seems has not reports about this implementation. As a spec, I also agree with @vladima . Edge seems has correct implementations.

**Comment by DanielRosenwasser** [comment]
A fix will need a way to propagate this information along with the signature or type. I think this also would be a breaking change.

**Comment by RyanCavanaugh** [comment]
Doesn't appear to be worth fixing
