### ISSUE TITLE
Go To Symbol (Ctrl+Shift+O) doesn't pick up on prototype methods

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#6145]
_From @KrofDrakula on December 17, 2015 18:13_

It seems that the code editor only scans for symbols with named functions, not functions assigned to variables, which makes the following code not have any symbols to go to, except for the constructor:

```js
function A() {}
A.prototype.myMethod = function() {};
```

## Expected behavior

The Go To Symbol command should find the `myMethod` function symbol instead of just `A` in the dropdown list.

## Current behavior (0.10.3)

The Go To Symbol dropdown only lists `A` as the only symbol in the file (the only named function).

_Copied from original issue: Microsoft/vscode#1428_

**Comment by jrieken** [comment]
_From @egamma on December 18, 2015 7:47_

@jrieken fyi

**Comment by jrieken** [comment]
Will move to TypeScript since they to the math for us.

**Comment by billti** [comment]
See #6644, as they can be done together.

**Comment by alvinsight** [comment]
Hey guys, any news on this ?

**Comment by RyanCavanaugh** [comment]
We'll be picking this up in the 2.1 milestone, which will start after 2.0 is released. Sorry for the delay

**Comment by alvinsight** [comment]
Hi,
Thank you for the reply, so is 2.0 going to be the next release ? Or do we
have to wait for 1.6, 1.7, etc
Cheers,
Alvin

**Comment by RyanCavanaugh** [comment]
2.0 is already out in RC form; it's the next release. And 1.8 already happened :wink:

**Comment by alvinsight** [comment]
Hi Ryan,
This is great to hear, so it shouldn't take too long.
I know it's not related to this issue, but were there any discussions
regarding a possible UI (for settings and shortcuts, like Atom has) ?
Thank you again,
Alvin

**Comment by mhegazy** [comment]
Should be working correctly in latest drop of TypeSript (`typescript@next`). VSCode ships with an older version of TypeScript. Please see [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) documentation for more details on updating your VSCode to use a different version of TypeScript.
