### ISSUE TITLE
Working with async/await and bluebird

### ISSUE THREAD

**Issue by coderfox** [Microsoft/TypeScript#6148]
I know TypeScript recently adds `async/await` keyword, which is of great use to program async codes. And I use `Bluebird` instead of the built-in `Promise` object since it has useful utilities like `.promisifyAll()`, `.spread()` and so on. However, I found it unable to use `Bluebird` instead of the built-in `Promise` with async functions.

I have ignored the errors created related to bluebird definitions, and the js emit was successfully updated, but it cannot execute properly in runtime.

My source code is:

```ts
/// <reference path="../references.d.ts" />

import userModel = require('../models/user');

export var reg = async (username: String, password: String): Promise<[userModel.IUser, number]> => {
  var user: userModel.IUser = new userModel.User({
    username: username
  });
  user.setPassword(password);
  var result = await user.saveAsync<userModel.IUser>();
  return result;
}
```

Note that `user.saveAsync()` returns a `bluebird Promise`.

When targeting either `ES5` or `ES6`, it throws in runtime:

```
TypeError: cUser.reg(...).spread is not a function
```

Even if I add `import Promise = require('bluebird');` does not work.

**Comment by coderfox** [comment]
Sorry, I have found a solution now: manually set

```ts
global.Promise = require("bluebird");
```

since bluebird won't set it when Promise already exists. Then I can make all the Promises into bluebird version.

Issue closed.

**Comment by DanielRosenwasser** [comment]
For the record, you can also specifically annotate your function with the type of Bluebird's promise type, and the emit will adjust for this.
