### ISSUE TITLE
unreachable code detection for default case in switches with exhausted cases based on a string literal type

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6150]
```typescript
type foo = 'hey' | 'nay';
switch (<foo>undefined) {
   case 'hey': doThis(); break;
   case 'nay': doThat(); break;
   default: console.log('never the case'); break; // expected unreachable code, actual no problem
}
```

**Comment by RyanCavanaugh** [comment]
The code you have there *does* reach the `default` label...

**Comment by vladima** [comment]
btw, this is similar to why F# compiler does not consider match over all cases of enum as exaustive: rule cannot be enforced in runtime
```f#
type E = Foo = 1 | Bar = 2
let e: E = enum 3
let s = 
    match e with // 'incomplete match' warning here
    | E.Foo -> "Foo"
    | E.Bar -> "Bar"
```

**Comment by aleksey-bykov** [comment]
> The code you have there does reach the default label...

Enlighten me please, how come it does? Can't see any typos.

Provided a value of foo (by contract) cannot be anything other than `'hey'` or '`nay`' and we are not falling through.

**Comment by RyanCavanaugh** [comment]
I'm not sure if you're trolling us on nullability or not?
![image](https://cloud.githubusercontent.com/assets/6685088/11903662/c24bf2e4-a56f-11e5-8d02-56e94d0e5dfd.png)

The "unreachable code" rule is only for code that is *provably* unreachable. You could easily be writing code like this:

```ts
type Verb = 'GET' | 'POST';
interface Request {
  verb: Verb;
  url: string;
}
function parseRequest(x: string) {
  let data = <Request>JSON.parse(x);
  switch(data.verb) {
    case 'GET': return $http.get(data.url);
    case 'POST': return $http.post(data.url);
    default: throw new Error('Unrecognized verb ' + data.verb);
  }
}

```

**Comment by aleksey-bykov** [comment]
wasn't trolling you sorry, i never use undefined or type assertions myself, so to me this piece of code is rock solid
