### ISSUE TITLE
New Website Logo: Artist Growth

### ISSUE THREAD

**Issue by fredpalmer** [Microsoft/TypeScript#6152]
Please fill the following out:

- Name: Artist Growth
- Homepage url: https://artistgrowth.com/

- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: (svg if possible, pngs over 500x200px with transparent backgrounds are also acceptable)
![primary-mark-space](https://cloud.githubusercontent.com/assets/32422/11902012/95372ce2-a574-11e5-86b9-b5d6a5fe9d56.png)

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
