### ISSUE TITLE
const enum should allow "Infinity" as a valid name

### ISSUE THREAD

**Issue by speigg** [Microsoft/TypeScript#6153]
```typescript
	declare const enum CameraDeviceFocusMode {
		Normal = 0,
		TriggerAuto = 1,
		ContinuousAuto = 2,
		Infinity = 3, // <- error: An enum cannot have a numeric name
		Macro = 4
	}
```

**Comment by RyanCavanaugh** [comment]
This is intentional because `Infinity` is also a valid enum *value*; we disallow any name that might be a value because the lookup object only works if no names are values and no values are names.

Recommended fix is to just use `Infinite` instead of `Infinity`

**Comment by speigg** [comment]
What is the lookup object exactly? Using the name `Infinity` as a property key is completely valid in javascript by the way.

**Comment by RyanCavanaugh** [comment]
I missed that this enum was `const`. We don't need to enforce this rule for those.

**Comment by RyanCavanaugh** [comment]
(Lookup object, see http://stackoverflow.com/a/28818850/1704166)

**Comment by speigg** [comment]
Not enforcing that rule for `const` sounds great.

**Comment by RyanCavanaugh** [comment]
Approved even for non-`const` enums.

The suggested implementation was to skip any leading `-`, then see if the next (or first) character is a digit. Only names matching this rule should be subject to restriction. This should allow `Infinity` and `NaN` but still disallow names like `5`.

**Comment by DanielRosenwasser** [comment]
So what's the new rule now for numeric names? Same as before but make a special exception for "Infinity" and "NaN"?

Also @jmatthiesen

**Comment by RyanCavanaugh** [comment]
> Same as before but make a special exception for "Infinity" and "NaN"?

Correct (as well as `-Infinity`)

**Comment by YuichiNukiyama** [comment]
@RyanCavanaugh [A JavaScript identifier must start with a letter, underscore (_), or dollar sign ($);](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Variables). So,  I think `-Infinity` is invalid.

**Comment by RyanCavanaugh** [comment]
Enum members need not be identifiers - they can be quoted much like the property names in object literals

**Comment by jbondc** [comment]
Reported here too #3572
