### ISSUE TITLE
consider allowing exhaustive switch statement

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6155]
```typescript
type foo = 'hey' | 'nay';
let value : foo = 'hey';
switch (value) {
    case 'hey': doThis(); break;
    case 'nay': doThat(); break;
    default: void; // <-- syntax TBD that indicates: 1. no other than known options are allowed 2. all known options must be considered
}
```

**Comment by aleksey-bykov** [comment]
(it's up to the developer to take the responsibility for possible contract violations at runtime)

**Comment by weswigham** [comment]
The `default` branch in your example can be triggered when `value` is `undefined` or `null` as both `let value : foo = null;` and `let value : foo = undefined;` are valid for type `foo`.

**Comment by aleksey-bykov** [comment]
let's
- either require them explicitly too
```
case undefined: void;
case null: void;
```
- or leave it up to the developer whether or not to guard the switch  
```
if (value != null) {
     switch() {
     }
}
```

**Comment by aleksey-bykov** [comment]
slippery moment here is that the `undefined` is just a variable, not a literal, but hey, why would you want to mess with it? anyway the emitter can take care of it:

```javascript
case void undefined: doSomethingElse
```

TypeScript should stop this nonsense and straiten things up by proclaiming `undefined` a **literal** and thus prevent it from being assigned. How is that?

**Comment by aleksey-bykov** [comment]
On top of that please admit that `Undefined` is a real type that can be referenced as well as `Null` for goodness sake. It's never a good idea to depart from what the real world is (I mean JavaScript here) by trying to model it using wrong entities (void type in TypeScript).

**Comment by RyanCavanaugh** [comment]
> TypeScript should stop this nonsense and straiten things up by proclaiming undefined a literal and thus prevent it from being assigned. 

This is already the case in strict mode.

As for the null and undefined types, I think we want to keep their names "off limits" until we address nullability as a real language feature and understand the desired semantics there.

**Comment by mhegazy** [comment]
with https://github.com/Microsoft/TypeScript/pull/7140 in place we should be able to make better decisions  here.

**Comment by aleksey-bykov** [comment]
I am super excited to welcome non-nullables, but exhaustive stitches is a different beast isn't it?

**Comment by ahejlsberg** [comment]
Checking for exhaustive switch statements is now possible with #9407.

**Comment by aleksey-bykov** [comment]
best day ever! thanks a bunch
