### ISSUE TITLE
function and inside var with same name

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/TypeScript#6162]
if I have:
```
export class SomeClass {
    public someNumber(): number {
        var someNumber = 6;
        return someNumber;
    }
}
```
The resulting SourceFile AST nodes are confusing me: the "var someNumber = 6" is a variable statement, variable declaration list, variable declaration, which is fine, but the symbol flags for the identifier, someNumber indicate that the variable is a function scoped variable rather than a block scoped variable. Any help would be appreciated!

**Comment by sandersn** [comment]
Are you talking about the `someNumber` that's part of the `var someNumber`? Wouldn't you expect it to be function-scoped since `var` is function-scoped?

**Comment by RyanCavanaugh** [comment]
This code doesn't parse?

**Comment by ToddThomson** [comment]
@sandersn Yes, if the var is changed to a let then the someNumber identifier symbol flags indicate a block scoped variable. lt is clear now - long day.

**Comment by ToddThomson** [comment]
@RyanCavanaugh Sorry Ryan, the above example parses correctly ( after edit of 'function' to 'public' above ).
