### ISSUE TITLE
Idea - ES6 Shared import statements centralized to a single file within directory

### ISSUE THREAD

**Issue by diegohb** [Microsoft/TypeScript#6165]
Wondering if something like the "_ViewStart" for MVC could be added to TS... 

If a directory has 5 files and each of them share a common set of ES6 import...from statements then creating a file (preferably not called _ViewStart) could be created at the parent directory and this will ensure each class has all of those scopes included for intellisense and they can be injected during compilation.

nice to have would be to be able to nest these so that following a directory structure will result in all of the usings at the deepest level flattened out from parent "viewStart" using listings.

**Comment by mhegazy** [comment]
looks like a duplicate/variant of https://github.com/Microsoft/TypeScript/issues/17
