### ISSUE TITLE
Outdated link at end of handbook for typescriptlang.org

### ISSUE THREAD

**Issue by bartvanderwal** [Microsoft/TypeScript#6166]
Hi,
Could you update a link? I think it's great that you're on GitHub now, instead of on Codeplex. However I just read a large part of your handbook at:
http://www.typescriptlang.org/Handbook

The handbook is pretty great, but at the end of it, it still points users to the old CodePlex issues page for issues:
https://typescript.codeplex.com/wikipage?title=https%3a%2f%2fgithub.com%2fMicrosoft%2fTypeScript%2fissues

The outdated link is in the word `here` in the very last sentence of the page:
`Please post a comment **here** if there's a pattern you'd like to see documented! We'll add to this as we can.`

I guess the link now needs to be:
https://github.com/Microsoft/TypeScript/issues/new

Or is there a separate place to put issues with documentation? Because I guess this issue itself then also needs to go there :).

**Comment by DanielRosenwasser** [comment]
We're planning on relaunching the handbook soon. You can also read a more up-to-date version on https://GitHub.com/Microsoft/TypeScript-Handbook

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript-Handbook#140

**Comment by bartvanderwal** [comment]
:+1:
