### ISSUE TITLE
React context handling : context instance variable

### ISSUE THREAD

**Issue by xmehaut** [Microsoft/TypeScript#6172]
Hello,
in the same way that we pass Props and State to the component at creation, could we not pass Context at the same time, e.g. 
```
 export MyClass extends React.Component<MyPropsInterface, MyStatesInterface, MyContextInterface> {...}
```
It would avoid use to redefine the "context" instance variable in subclasses like ``` context:MyContextInterface``` to be able to access directly context properties without having a compiler error, e.g. this.context.myprop.

Furthermore, as we have context types , could we avoid in the same time to redefine types in the containing component? We have currently in pure react :
```
   childContextTypes: {
         foo: React.PropTypes.string.isRequired
    },

    getChildContext: function() {
         return { foo: "I m the grandparent" };
    },
```
we could only have :
```
getChildContext: MyContextInterface {
         return { foo: "I m the grandparent" };
    },
```
because we already have all the information in the context typing statement.

best regards

**Comment by RyanCavanaugh** [comment]
I think you're just talking about issues with react.d.ts? We don't own that file.

**Comment by xmehaut** [comment]
Thanks Ryan for the information ; i thought that the react integration was
made by the typescript team... how to transmit the requirement to Asana or
AssureSign for updating the definition file?
best regards

2015-12-21 19:45 GMT+01:00 Ryan Cavanaugh <notifications@github.com>:

**Comment by RyanCavanaugh** [comment]
You can just send a pull request to DefinitelyTyped
