### ISSUE TITLE
Generic decorators...

### ISSUE THREAD

**Issue by xmehaut** [microsoft/TypeScript#6173]
Hello,
it could be interessant to be able to define generic decorators, for instance for managing react context , e.g. :

```
    @Context<MyContextType>
    export class MyComponent extends React.Component<MYProps,MyState,MyContextType> {...
```

with :

```
  export  function Context<C>(target: any) {
    target.contextTypes = target.contextTypes || {};
   // a loop towards the properties on the Co,ntext type and auto filling, e.g.
    target.contextTypes.myprop= React.PropTypes.bool.isRequired;
}
```

This could enable to write react contexts simpler, especially with the Context setting in the component extension. (see #6172).

by doing this, we could also easily handle context hierarchy like :

```
      @Context<MYGrandFatherContextType>
      @Context<MyFatherContextType>
      export class MyComponent....
```

And we could add two kinds of decorators :

```
      @Context<C>
     @ChildContext<C>
```

the later being to define the  

```
     static childContextTypes= {
        open:  React.PropTypes.func.isRequired
      }
```

other part of the context definition
best regards

**Comment by DanielRosenwasser** [comment]
Currently you can use a generic function as a decorator, but you'll need to rely on type inference for your type parameters.

One workaround for now is to make `Context` a decorator factory so that it could be called like `@Context<MyContextType>()` and that would work.

If we decided to allow this, the grammar would would need to be augmented to expect an expression with type arguments much like how we allow in `extends` heritage clauses. 

Pinging @rbuckton and @RyanCavanaugh.

**Comment by zheeeng** [comment]
I encountered 'Declaration expected' warning while declaring generic in using decorator. I have to give up decorator usage in this situation.

**Comment by zheeeng** [comment]
Hope more progress on this issue. It's very inconvenient for using decorator. https://github.com/Microsoft/TypeScript/issues/19245 came up it again. That demo shows that TS can't infer the return type of decorated class and using generic causes syntax error (I know we can't return a generic casted function at present, but it is useful for decorator).

as @DanielRosenwasser suggested, using factory:

```ts
interface Klass {
    new (): any
}

function factory<P>() {
    return function decorator(klass: Klass) {
        return class extends klass {
            test(p: P) {
                return p
            }
        }
    }
}

@factory<string>()
class Test { }

const t = new Test()
// Error: Property 'test' does not exist on type 'Test'.
t.test('123')

const Test2 = factory<string>()(class { })
const t2 = new Test2()
// Argument of type '5' is not assignable to parameter of type 'string'.
t2.test(5)
```
TS still doesn't know the decorated `Test`'s instance has `test` method. Without decorator, TS can infer that `Test2`'s instance has `test` method.

**Comment by aluanhaddad** [comment]
it would be interesting to have arbitrary generic values, properties, and indexer declarations. Generic decorators could be a subset that falls out of a more general but more complex implementation.

**Comment by RyanCavanaugh** [comment]
This is allowed now
