### ISSUE TITLE
problem with interfaces 

### ISSUE THREAD

**Issue by jeevan-reddy** [Microsoft/TypeScript#6175]
**Error:
Argument of type '{ size: number; label: string; }' is not assignable to parameter of type '{ label: string; }'.
  Object literal may only specify known properties, and 'size' does not exist in type '{ label: string; }'.**

My typesscript version is **1.7.5**

*Steps to recreate the Error:*
1) Create a .ts file named script.ts
2) type the following code :
``` javascript
function printLabel(labelledObj: {label: string}) {
  console.log(labelledObj.label);
}
var myObj = {size: 10, label: "Size 10 Object"};  // myObj is of type {size:number;label:string}
// printLabel(myObj);
printLabel({size: 10, label: "Size 10 Object"});   // the object being passed to printLabel is also of type {size:number;label:string}
```
3) Compile the script.ts using command *tsc script* either from command prompt/powershell

it is clearly mentioned in documentation  that if we send extra arguments it is ok .please refer to attached code-snippet
![code-snippet](https://cloud.githubusercontent.com/assets/15384537/11918884/31811042-a767-11e5-8d3a-416edadc28e5.JPG)

*But what is the difference if i assign an object to a variable , pass that variable as argument  and if i directly pass the object as argument ?*

**Comment by kitsonk** [comment]
The handbook is currently wrong as of TypeScript 1.6.3.  It was discussed in #3755 and was changed in #3823.

IIRC, the team are in the process of doing a whole update of the handbook, because there are a few other issues with it.

**Comment by DanielRosenwasser** [comment]
Thanks for catching this @jeevan-reddy, I'll be amending this in https://github.com/Microsoft/TypeScript-Handbook/issues/64

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript-Handbook#139

**Comment by DanielRosenwasser** [comment]
Should be fixed when the docs get refreshed.
