### ISSUE TITLE
Unstable behavior of code and type information

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6182]
Sometimes I get different popup type information on Visual Studio. For example, when VS is busy, I get `C<any, string>` type. When VS is idle, I get `C<number, string>` type. I didn't change any definition. It seems a interim result of calculation. Is there document about this behavior? Or please tell me internal spec of this behavior.

**Comment by vladima** [comment]
Symptoms don't sounds good, can you provide more information about the repro scenario (ideally with some code where this issue appear)?

**Comment by aleksey-bykov** [comment]
Sounds exactly like #6002

**Comment by vladima** [comment]
not really, #6002 looks like an unhandled exception that lead to Watson report and as a consequence to the UI freeze (that I why I was curious if there are any error related entries in Windows Event log - this information can be used to trace reported Watson). This issue is more about observing intermediate results of the typechecking

**Comment by falsandtru** [comment]
Sorry, I cannot provide the repro scenario because this problem is too stateful, and I already fixed my code.

My scenario(experience) was:

1. Edit a code(VS was busy).
1. Check the type inference on VS: Well, type is `C<any, string>`. Not good.
1. Check related codes.
1. After 3~5 seconds.
1. Check the type inference again: Type is `C<number, string>` ... why this type changed?

It also seems a problem of caching. I was confused. I didn't meet this problem on VS2013 with TS1.6 because it environment was hang when VS is busy. VS2015 with TS1.7 was not hang but I meet this problem. This issue is a reporting and a question. I don't request the fix because I cannot provide the good repro scenario. Thanks.

**Comment by mhegazy** [comment]
I do not think there is much we could do here. please reactivate if you run into this again with a repro you can share.
