### ISSUE TITLE
TypeScript Compiler Options Missing --filesGlob Parameter

### ISSUE THREAD

**Issue by kutyel** [Microsoft/TypeScript#6185]
We have the following project structure

```
+-- views
    +-- viewXXX
        +-- ts
        ¦    +-- controller.ts
        ¦    +-- helper.ts
        ¦    +-- ... (*.ts)
        +-- viewXXX.ctrl.js // this is the desired output file
        +-- viewXXX.ctrl.map.js
        +-- viewXXX.html
```

We are trying to configure a task in VSCode that allows to compile following this structure...

```json
// A task runner that calls the Typescript compiler (tsc)
{
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"showOutput": "silent",
	"args": [
        "-t",
        "es5",
        "-m",
        "commonjs",
        "--sourceMap",
        "--out",
        "${fileDirname}.ctrl.js",
        // "--filesGlob", missing
        "${fileDirname}\\ts\\*.ts"
    ],
	"problemMatcher": "$tsc"
}
```

And we are not able to make it work because there is no **--filesGlob** parameter, or any other way to pass a ***regex*** to compile many files.

**Comment by RyanCavanaugh** [comment]
What is `filesGlobal` ? I can't find any documentation on this

**Comment by kutyel** [comment]
It's a parameter we use in our *tsconfig.json* similar to the `files: [ ]` one but that accepts regexps to match files... Unless it has been working by chance 😳

**Comment by RyanCavanaugh** [comment]
:confused: Do you mean `filesGlob` ? That is a feature the Atom plugin does on its own (https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md) and isn't supported by TSC

**Comment by kutyel** [comment]
Ok I'm sorry for he confusion, is there any way to achieve what I am trying
to do with the tsc compiler options?

**Comment by RyanCavanaugh** [comment]
I think #1927 tracks what you're looking for

**Comment by kutyel** [comment]
True, thank you!
