### ISSUE TITLE
ES6 definitions only available when target: es6

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#6186]
I am writing some TypeScript as ES6 and want to compile to ES5. I am using Promise, so I want to take advantage of TypeScript’s type definitions for this. However, I noticed they are only available when the `target` is set to `es6`. Why are they not available when compiling to ES5, and is there any way to add them? (I am using a polyfill at runtime)

**Comment by Arnavion** [comment]
If all things available in ES6 were also available when targeting ES5, then there'd be no way for a TS author to know whether they're using features unavailable on the target or not.

To specify their intent to use a thing unavailable in regular ES5, they would use a .d.ts that provides that thing. In your case, that would be the .d.ts for your polyfill, such as the [es6-promise one.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-promise/es6-promise.d.ts)

**Comment by RyanCavanaugh** [comment]
Any time you're targeting an in-between target, you have a few options:

 * Target the newer version and be mindful of what syntax you use
 * Target the older version, but manually include the higher version's lib file and be mindful of which newer features are actually in your runtime
 * Target the older version and include a .d.ts file for a polyfill equivalent to whatever newer features are in your runtime

**Comment by yortus** [comment]
related: #4692
