### ISSUE TITLE
Add option to Visual Studio TypeScript Extension to Specify tsc binary

### ISSUE THREAD

**Issue by fernap3** [Microsoft/TypeScript#6188]
Hi all,

I have a collection of TypeScript files that, on Windows, compile under tsc when run under node, but throw bogus errors (I can clearly see the source contradicts them) when compiled via the Visual Studio TypeScript 1.7.6.0 extension which uses tsc.exe.  I implemented a very temporary workaround by creating my own `tsc.exe` which simply invokes the compiler via node and overrwrote the default `tsc.exe`, found in `c:\Program Files (x86)\Microsoft SDKs\TypeScript\1.7\` with my own.

It would be great if the Visual Studio extension allowed the user the option to specify the compiler implementation to use, Node or tsc.exe.

**Comment by vladima** [comment]
@fernap3 do I understand you correctly that you can compiling your code using `node` and `tsc` does not yield the same result? if yes - can you please share the source code so we can check if this is something that needs to be fixed in JavaScript engine used by `tsc`?

**Comment by fernap3** [comment]
@vladima, thanks for the reply; unfortunately I can't share the source code.  It's a lot of files (148) and there are liability issues with the company.

**Comment by fernap3** [comment]
@vladima, I managed to get a reproduce from two source files, the first of which is copied 17 times.  I’ve attached a zip file with the source.

Here is the command I use to compile, after changing the working directory to the folder 
with the files:

`"C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.7\tsc.exe" @ts-files.txt`

This produces the following errors:

    File1.ts(1,7): error TS2300: Duplicate identifier 'Class5'.
    File1.ts(72,29): error TS2304: Cannot find name 'Class6'.
    File1.ts(100,58): error TS2304: Cannot find name 'Class7'.
    File1.ts(117,30): error TS2304: Cannot find name 'Class8'.
    File1.ts(126,31): error TS2304: Cannot find name 'Class9'.
    File1.ts(180,26): error TS2304: Cannot find name 'Class8'.
    File1_1.ts(1,7): error TS2300: Duplicate identifier 'Class5'.
    File1_1.ts(72,29): error TS2304: Cannot find name 'Class6'.
    File1_1.ts(100,58): error TS2304: Cannot find name 'Class7'.
    ...
    File2.ts(145,12): error TS2339: Property 'StaticFunction' does not exist on type 'typeof Class3'.
    File2.ts(156,12): error TS2339: Property 'StaticFunction' does not exist on type 'typeof Class3'.

The first batch of errors I’m not worrying about because they are legitimate.  The last two errors, however, are bogus.  Our actual TypeScript codebase compiles without error using the compiler under node, but throws the bogus errors above (and other bogus errors) when compiling with `tsc.exe`.  `StaticFunction` does indeed exist as a static function on `Class3`.  Also if you note the output for `File2.ts`, the compiler puts `StaticFunction` on the prototype of `Class3`, not the object itself.

This has been a really tricky issue to nail down.  It seems like the more copies of "File1" I compile against, the more consistant the bogus errors are.  With fewer files, sometimes the error happens, sometimes it doesn’t.  Also interesting is that if you alter `ts-files.txt` so `File2.ts` appears at the top instead of the bottom, the bogus errors do not occur.

I have reproduced with `tsc.exe`  1.5, 1.6, and 1.7, but cannot reproduce with 1.4.

Please let me know if you need more info or if you have difficulty reproducing.  If this is a TypeScript (or IE) issue it would be really great for us to get it fixed.

Thanks,
Peter

[TSC_Reproduce.zip](https://github.com/Microsoft/TypeScript/files/71184/TSC_Reproduce.zip)

**Comment by fernap3** [comment]
Also, here is my system info; I'm running on Windows 7:

![image](https://cloud.githubusercontent.com/assets/1057057/11983776/2a500890-a984-11e5-8e62-7986fd007814.png)

**Comment by vladima** [comment]
@fernap3 thanks! I was able to repro this locally - it appears to be fixed in the most recent local bits.

**Comment by fernap3** [comment]
Great!  Thanks
