### ISSUE TITLE
Better support for functions

### ISSUE THREAD

**Issue by louy** [Microsoft/TypeScript#6189]
As a heavy user of Typescript now there's one very annoying thing that I face all the time. It's the bad (or lack of) support for `Function.prototype.apply/call/bind`. 

I don't know if this has been requested previously, but this is a big thing to me and I'd like to ask for a solution. Like it or not, `bind` is used a lot in javascript. Returning `any` is not a good solution IMHO. Functions are first-class citizens in Javascript, which is one of the reasons that it's the best language to me, but they're not so much in Typescript.

I don't have a syntax in mind unfortunately, so this is an open discussion. If anyone has any ideas please step in.

Cheers,

**Comment by RyanCavanaugh** [comment]
Duplicate #212

**Comment by sandersn** [comment]
Proposals #5453 and #6018 will allow us to type `Function.prototype.apply/call/bind`. I'm working on #6018 right now because it's useful in quite a few other places.
