### ISSUE TITLE
Contextual type of 'any' should be ignored

### ISSUE THREAD

**Issue by sandersn** [Microsoft/TypeScript#6190]
`getContextuallyTypedParameterType` should return `undefined` instead of `any`

```ts
let x: { f(a, b): any, g(): any } = {
    f: (a = "none", b) => a.length, 
    g: (a = "none", b) { return a.length }
}
```

For both `f` and `g`, the parameter `a: any` but should be `a: string`.

I also ran into this with implemented/inherited functions in PR #6118.

**Comment by RyanCavanaugh** [comment]
I don't think that's correct. In this example (slightly modified):

```ts
let x: { f(a: any, b: any): any, g(): any } = {
    f: (a = "none", b) => a.length, 
    g: (a = "none", b) { return a.length }
}
```
... you shouldn't see any implicit `any` warnings, which *would* happen if getContextuallyTypedParameterType return `undefined`

**Comment by sandersn** [comment]
Maybe it should be handled above (`getTypeForVariableLikeDeclaration`) or below (`getTypeAtPosition`) then.

**Comment by mhegazy** [comment]
i agree with @RyanCavanaugh this is by design.
