### ISSUE TITLE
Enum usage compiling issue in VS Studio 2015

### ISSUE THREAD

**Issue by Alex2357** [Microsoft/TypeScript#6191]
Enum definition
```ts
declare enum FeedStatus {
    noFeedSpecified = 0,
....
....
}
```

The code
```
    var feedStatuses = {};
    feedStatuses[FeedStatus.noFeedSpecified] =      "Not specified";
```
In VS 2013(I believe 1.0 Typescript tools I had) it was compiling into
```
    feedStatuses[0 /* noFeedSpecified */] = "Not specified"; 
```
In VS 2015(Typescript tools 1.7 ) it is compiled into 
```
    var feedStatuses = {};
    feedStatuses[FeedStatus.noFeedSpecified] = "Not specified";
```
This thing causes javascript error "Uncaught ReferenceError: FeedStatus is not defined"

**Comment by vladima** [comment]
consider replacing `declare enum` with `const enum` if you want the value of enum member to be inlined: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#enum-reference-in-lining-changes

**Comment by RyanCavanaugh** [comment]
Enum emit rules have changed a bit between TypeScript 1.0 and 1.7.

See also http://stackoverflow.com/questions/28818849/how-do-the-different-enum-variants-work-in-typescript
