### ISSUE TITLE
typescript 1.7 spec

### ISSUE THREAD

**Issue by davidmoshal** [Microsoft/TypeScript#6192]
Hi, wondering where the spec is for 1.7?
Thanks

**Comment by DanielRosenwasser** [comment]
There is a Word document (.docx), a PDF, and an [online-readable markdown version](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md). Just check this repo's [`doc`](https://github.com/Microsoft/TypeScript/tree/master/doc) folder.

**Comment by davidmoshal** [comment]
Yes, and they are all for 1.6 !

**Comment by DanielRosenwasser** [comment]
Sorry for the misunderstanding. @ahejlsberg should be in the process of updating the spec for 1.7 changes.
