### ISSUE TITLE
Requirements for subclass constructors

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#6203]
It seems Promise has some requirements for subclass constructors. (https://github.com/domenic/promises-unwrapping/issues/87, http://www.ecma-international.org/ecma-262/6.0/#sec-newpromisecapability)

> NOTE C is assumed to be a constructor function that supports the parameter conventions of the Promise constructor (see 25.4.3.1).

Thus any subclass constructor should support `init: (resolve, reject) => void` parameter. Ignoring this restriction will cause an error on runtime:

``` typescript
new (class extends Promise {
  constructor() {
    super((resolve, reject) => resolve());
  }
})().then(() => console.log("passed"))
// Edge - 'Promise' is not a function (typeof Promise is "function" though...)
// Firefox Nightly - TypeError: A Promise subclass passed a non-callable value as the resolve function.
```

``` typescript
new (class extends Promise {
  constructor(init) {
    super(init);
  }
})((resolve, reject) => resolve()).then(() => console.log("passed"))
// passes
```

Can this restriction be supported on TypeScript type system? In other words, is this within the TypeScript scope?

**Comment by mhegazy** [comment]
I would say it is within the scope. Do not know how though :). Any proposals?

**Comment by RyanCavanaugh** [comment]
I don't think we have any plausible way of handling this
