### ISSUE TITLE
ClassExpressions hide generic types on base classes

### ISSUE THREAD

**Issue by DouglasLivingstone** [Microsoft/TypeScript#6207]
With a generic base class,

	class GenericBase<T> {
		value: T;
	}

this compiles without errors:

	class StringBase extends GenericBase<string> { }
	class Foo extends StringBase { }
	var foo = new Foo();
	foo.value.charCodeAt(0); // OK
	
but this produces an error that `Property 'charCodeAt' does not exist on type 'T'`:

	function makeBase<T>() {
		return class extends GenericBase<T> { };
	}
	class Bar extends makeBase<string>() { }
	var bar = new Bar();
	bar.value.charCodeAt(0); // compile error

Since `string` has been used as the generic parameter for `makeBase`, it seems that none of the properties on `Bar` should be typed as `T`.

**Comment by vladima** [comment]
does not repro on the latest bits in master, can you try `typescript@next` on npm to see if you still have this issue?

**Comment by DouglasLivingstone** [comment]
Thanks, yes, this has been fixed already

**Comment by vladima** [comment]
duplicate of #5400
