### ISSUE TITLE
Inconsistent error message between generic interface merging and generic ambient class/interface merging

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6211]
This code...

```ts
interface Foo<T> {
    n: T;
}
interface Foo<U> {
    y: U;
}
```

...gets the error `All declarations of an interface must have identical type parameters.`

This code...

```ts
class Foo<T> {
    n: T;
}
interface Foo<U> {
    y: U;
}
```

...gets no error.

**Comment by sandersn** [comment]
Probably related to the other issue with type parameters not being identical: #6210

**Comment by sandersn** [comment]
This is fixed now.
