### ISSUE TITLE
Promise.then should use `this` return type

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/TypeScript#6220]
```typescript
class Subclass<T> extends Promise<T> { }
new Subclass<void>((resolve, reject) => resolve()).then() instanceof Subclass
// true
```

**Comment by weswigham** [comment]
Problem: there's no way to rebind the generic parameters of the `this` type to match the return type of the function passed to `then` - and, conceptually, a given subclass may not even be generic.

**Comment by kitsonk** [comment]
I realised that this is directly related to #6223.  In a theory, not being able to express some sort of generic resolution of polymorphic this will cause challenges.

**Comment by aleksey-bykov** [comment]
#5999

**Comment by mhegazy** [comment]
see #6223 and #5999
