### ISSUE TITLE
Const enum intersection type

### ISSUE THREAD

**Issue by NoelAbrahams** [microsoft/TypeScript#6222]
We have a use-case where a subset of a const enum should be used in certain contexts, while the whole enum should be available in other contexts.

Here's a simplified example:

``` typescript


const enum LetterKeys {
    a = 1,
    b = 2,
    // ..
    z = 26
}

const enum ControlKeys {
    control = 27,
    alt = 28,
    shift = 29
}

const enum NavigationKeys {

    up = 30,
    down = 31,
    left = 32,
    right  = 33
}

type Keyboard = LetterKeys & ControlKeys & NavigationKeys;

```

We would like to be able to access `Keyboard` in a value position without the compiler issuing an error (as it does now):

``` typescript
const myKey = Keyboard.alt;  // Error: Cannot find name 'Keyboard'
```

It's possible that changing the semantics of the `type` keyword may cause too many problems, in which case, I suggest the following be permitted:

``` typescript
const enum Keyboard = LetterKeys & ControlKeys & NavigationKeys;
```

**Comment by RyanCavanaugh** [comment]
Doesn't seem to have gathered much interest
