### ISSUE TITLE
Question: Why can't type parameters be used inside type parameters?

### ISSUE THREAD

**Issue by ryansmith94** [Microsoft/TypeScript#6224]
Hey all, hoping to be educated by someone. I think I need to reuse type parameters inside type parameters (see example code below, specifically the reuse of `Y`), but this is firstly not allowed by TypeScript (and perhaps other languages too), and secondly it seems "odd". So I'm wondering, why can't type parameters be used inside type parameters? Is there a solution to this I'm missing?

```typescript
class A {
  // ...
}

class B<Z extends A> {
  public a: Z;
  // ...
}

class C<Y extends A, X extends B<Y>> {
  public a: Y;
  public b: X;
  // ...
}
```

**Comment by SaschaNaz** [comment]
I think that is to prevent circular reference. Will this solve your problem?

```typescript
class C<Y extends A> {
  public a: Y;
  public b: B<Y>
}
```

**Comment by ryansmith94** [comment]
Thanks for your response @SaschaNaz. That's the solution I'm using to overcome this at the moment, I'm just wondering if there is perhaps a better one, since to extend that class with a subclass of B I must override the parameter.

**Comment by ryansmith94** [comment]
Has @SaschaNaz deleted their comment?

> I think that is to prevent circular reference. Will this solve your problem?

> ```typescript
class C<Y extends A> {
  public a: Y;
  public b: B<Y>
}
```

**Comment by SaschaNaz** [comment]
@ryansmith94 Ah, I thought my answer was not 100% right so I deleted it, sorry.

**Comment by ryansmith94** [comment]
Ah no worries, I wouldn't worry about posting something you're unsure about as long as you say that you're not sure :smile:

**Comment by DanielRosenwasser** [comment]
Try installing the nightly of TypeScript (`npm install -g typescript@next`) where we should now support type parameters referencing other type parameters (see #5949 and https://github.com/Microsoft/TypeScript/wiki/Roadmap#18).

**Comment by ryansmith94** [comment]
Awesome! Thanks @DanielRosenwasser :+1:
