### ISSUE TITLE
Lookup index in tuple

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#6226]
``` ts
const x: [number, string] = [1, 'foo'];
const y = x[1]
y
```

TypeScript knows `y` is a `string`. However, if I ask for `x[2]`, TypeScript tells me it is `string | number`. Why is this? I expected it not to compile.

**Comment by SaschaNaz** [comment]
It seems it need more discussion. See also #5203.

**Comment by DanielRosenwasser** [comment]
This is because a tuple of length `n` is an anonymous type that has properties `0`, ... `n - 1`, and which effectively extends an array of the union of all element types. Since it's a subtype of `Array`, it gets an index signature, whose output type is the union of all element types.
