### ISSUE TITLE
AMD module with `--outFile` option emits declaration file references

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6228]
Referenced file does not exist.

```ts
// index.ts
import './types';

// types.d.ts
export default function f()
```

```
$ node built/local/tsc.js -t es5 -m amd --outFile bundle.js index
```

```js
// bundle.js
define("index", ["require", "exports", './types'], function (require, exports) {
    "use strict";
});
```

**Comment by DanielRosenwasser** [comment]
For the most part `--module` and `--outFile` have nonsensical behavior. You'd be better served by a module bundler.

**Comment by vladima** [comment]
just to clarify, what should be expected output from your perespective?

**Comment by falsandtru** [comment]
expected:

```js
// bundle.js
define("index", ["require", "exports"], function (require, exports) {
    "use strict";
});
```

actual:

```js
// bundle.js
define("index", ["require", "exports", './types'], function (require, exports) {
    "use strict";
});
```

**Comment by vladima** [comment]
Compiler never elides import statements that lack import clause because they are usually used only for side-effect that happen during module loading and removing them will be incorrect.

**Comment by falsandtru** [comment]
Certainly, TypeScript compiler needs side-effect. But runtime is not. Declaration files have not actual behavior. This emit has unnecessary references. It seems emits will be not incorrect.

**Comment by vladima** [comment]
declaration file just describes the public surface but does not tell if loading of the module will trigger any effects. Compiler has to be conservative here especially given that the main reason why people use import declaration without import clause is side-effects.

**Comment by falsandtru** [comment]
Excuse me, a following case causes an error. Why it is correct?

```ts
// index.ts
import './types.d';
```

```
$ node built/local/tsc.js -t es5 -m commonjs index
```

```js
// index.js
"use strict";
require('./types.d');
```

```
$ node index.js
module.js:328
    throw err;
    ^

Error: Cannot find module './types.d'
```

**Comment by vladima** [comment]
import / export declaration is ES6 constructions with semantic described by ES6 spec. TypeScript follows it and the only extra thing it does - removes imports that were not used in value positions (imports that were used only to bring types into the scope). If import is not removed it will fail in runtime since there are no actual exported value. Imports without import clause and imports that were used as values are never elided even if module cannot be found.
```ts
import {X} from "./a"
let a = new X();
```
```
vladima@vladima-W520:~/sources/git/TypeScript$ node built/local/tsc.js -m commonjs t.ts
t.ts(1,17): error TS2307: Cannot find module './a'.
vladima@vladima-W520:~/sources/git/TypeScript$ cat t.js
"use strict";
var a_1 = require("./a");
var a = new a_1.X();
```

Answering your question: I can easily imagine this situation somewhere in the middle of transition of some codebase from JavaScript to TypeScript: when `index.ts` is already converted to TypeScript but `./types.d.js` - not. The fact that TypeScript compiler cannot find module does not mean that it should remove its import.

**Comment by falsandtru** [comment]
Thanks for your kindness!

> TypeScript compiler cannot find module

Compile was succeeded because there is:

```ts
// types.d.ts
export default function f()
```

completely:

```ts
// index.ts
import './types';

// types.d.ts
export default function f()
```

same as:

```ts
// index.ts
import './types.d';

// types.d.ts
export default function f()
```

My specified error is a runtime error, not a compile error.

**Comment by vladima** [comment]
Ambient declarations describe shape of things whose code is not accessible to the compiler. In your example the assumption is that `types.d.ts` define the public surface the API for some module 'types' that will exist in runtime. This is similar to:
```ts 
declare function someFunction(a: string): number;
someFunction("123").toFixed();
``` 
compiler does not have the code for 'someFunction' so it have to trust that declaration provided by the user is correct and hope that it runtime this function will be defined.

**Comment by falsandtru** [comment]
I understood your explained concept. Thank you very much!

Note: Then I think, compiler is probably better to emit(expected):

```js
"use strict";
require('./types');
```

actual:

```js
"use strict";
require('./types.d');
```

in this directory structure:

```
./
- index.ts
- types.d.ts
- types.js or types/
```

for code semantics. Thanks.
