### ISSUE TITLE
`string` is not assignable to string union for TSX component props

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#6231]
Sample code : 

```ts
type Foo = "f"|"o";
const FooComp = (props:{foo:Foo}) => <span>{props.foo}</span>;
<FooComp foo={"f"}/>; // Okay
<FooComp foo="f"/>; // Error : Type string is not assignable to "f"|"o";  Should be allowed and type checked 🌹
```

PS: can we get a JSX / TSX label. Would help me to search :rose:

**Comment by DanielRosenwasser** [comment]
Nice catch @basarat! I guess we never ran into this since non-expression initializers weren't susceptible to contextual typing.

**Comment by DanielRosenwasser** [comment]
I just sent out a fix.

**Comment by DanielRosenwasser** [comment]
Thanks @basarat, this should be fixed in `master`. Check out the nightly.

**Comment by basarat** [comment]
🌹
