### ISSUE TITLE
Performance: Config Option to Use Functions in place of defineProperty() Getter/Setters

### ISSUE THREAD

**Issue by Cleod9** [Microsoft/TypeScript#6233]
I've found there are potential performance implications when it comes to `Object.defineProperty` getter/setters across various browsers:

http://jsperf.com/es5-getters-setters-versus-getter-setter-methods/10

I would like to suggest a configuration option to output `get`/`set` class properties as regular functions instead of their `Object.defineProperty` counterparts. For example:

```typescript
public get myprop() {
  //do some stuff
  return this._myprop;
}
public set myprop(value) {
  //do some stuff
  this._myprop = value;
}
```
would be transpiled to something like the following, free of  `Object.defineProperty`:
```typescript
MyClass.prototype.__getmyprop() {
  //do some stuff
  return this._myprop;
}
MyClass.prototype.__setmyprop(value) {
  //do some stuff
  this._myprop = value;
}
```
This would be extremely useful in the event that application performance is impacted by the use of `get`/`set`.

I should also note that in an AS3->JS transpiler I wrote awhile back it did essentially exactly this, so I do believe it is possible from a syntactical standpoint. I think this would be a great feature to have with hopefully not too much effort.

**Comment by DanielRosenwasser** [comment]
You can't do this because any consumer of your JavaScript now has to specifically know that they need to use a method call. If that's what you want, you can already achieve identical behavior anyway through overloads:

```ts
class C {
    public myProp(): string;
    public myProp(value: string): void;
    public myProp(value?: string) {
        if (!value) {
            return this._myProp;
        }
        this._myProp = value;
    }
}
```

**Comment by Cleod9** [comment]
@DanielRosenwasser I should have noted that the purpose of this feature wouldn't be for code that's going to be consumed by non-TS code. The sole purpose would be to allow for the sugar of `get/set` without the potential overhead of `Object.defineProperty` in some environments. (Maybe it could have been a decorator or something)

But anyway, the overloading solution isn't quite what I was looking for since I want to be able to toggle on `Object.defineProperty` in environments where it was already fast (or faster). In a graphically intensive application I'm profiling, in one specific environment I'm seeing these `defineProperty` functions taking significantly more time to execute in rapid succession than essentially any regular function in the app (they literally show up at the top of the profiler). And they are really only being used as proxies for the most part in some abstractions built into the app, no extra logic that should result in such slowdowns.I think there could be significant benefits from being able to easily switch on a feature like the one I'm suggesting.

If there is still no interest in adding this feature for technical reasons then I'll let it go, though I'd like to kindly ask you to reconsider.

**Comment by DanielRosenwasser** [comment]
The problem is you have no way of knowing when to switch out a property/element access with a call expression apart from the type of the left side of the dot. How exactly would we preserve the correct semantics if your value ended up getting typed as `any` and you still performed the property access?

**Comment by Cleod9** [comment]
If the value had become casted as `any` I'd expect to receive a runtime error that the property doesn't exist, which I think should be trivial to debug if the feature is opt-in. The main idea is that this would be a feature designed around maximizing performance in areas of the code that are fully invested in the TS typing paradigm, and not likely to fall into these situations

**Comment by DanielRosenwasser** [comment]
Unfortunately, I don't think imposing that sort of edge case is in the best interest of users. Defining a regular property or using the above overload workaround should be sufficient.

**Comment by Cleod9** [comment]
Alrighty, well it was worth a shot. I appreciate the feedback at least.
