### ISSUE TITLE
New Website Logo: Villamedia

### ISSUE THREAD

**Issue by villamedia** [Microsoft/TypeScript#6236]
Hello TypeScript friends!

- Name: Villamedia
- Homepage url: http://www.villamedia.ca
- Brand Guidelines/Licensing: Please request alternate version of logo if using on a dark background
- Logo: ![Villamedia Logo](http://villamedia.ca/villamedia-logo.svg)
- Logo src: http://villamedia.ca/villamedia-logo.svg

Keep up the awesome work!

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
