### ISSUE TITLE
Couldn't to set private fields with the same names like in base class

### ISSUE THREAD

**Issue by greybax** [Microsoft/TypeScript#6237]
![ts_issue](https://cloud.githubusercontent.com/assets/3235047/11994569/e7bf2096-aa51-11e5-86e3-7f9b153e16b7.png)

**Comment by DanielRosenwasser** [comment]
This is by design. At runtime, both classes refer to the same property slot for `b`, so any usage of that property by `ClassB` would conflict with the expectations of `ClassA`.

If you want to allow `ClassB` to use the same property, declare `b` as protected in `ClassA`.

**Comment by greybax** [comment]
@DanielRosenwasser this design is not so clear. For example the same behavior in C# code is working fine and it's clear for OOP. 
```protected``` and ```private``` by design have another logic.

***Please let me share my thoughts with the simple example:***

I've implemented myself library with some classes. And in these classes I've implemented some ```private``` fields. So after that another guy take my library and inherited from it and would like to implement himself ```private``` property. But this property can has the same name like in library and so he couldn't do that.

If I've implemented all ```private``` properties as ```protected``` so it will be broken encapsulation in my library classes.

**Comment by DanielRosenwasser** [comment]
> But this property can has the same name like in library and so he couldn't do that.

Correct, and that's because at runtime, that other guy's class will refer to the same property, and will accidentally use it in unintended ways. Any person extending your class will just need to create a distinctly named property.

The semantics are different in C#, and that's because C# is a distinct language with a different runtime and different goals.
