### ISSUE TITLE
async/await compiles to yield outside of a generator

### ISSUE THREAD

**Issue by ryansmith94** [Microsoft/TypeScript#6242]
The following TypeScript with async/await...
```typescript
public async get(from: number, to: number): Promise<Array<M>> {
  let models: Array<M> = await this.persistant_repo.get(from, to);
```

produces the following JavaScript with a yield outside of a generator...
```javascript
ModelsRepoDecorator.prototype.get = function (from, to) {
  var _this = this;
  var models = yield this.persistant_repo.get(from, to);
```

I'm not certain, but I don't think `yield` should work outside of a generator. I'm running `tsc src/**/*.ts --outDir dist --sourceMap` and my tsconfig looks like this...

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES6",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "jsx": "react"
  }
}
```

I think this may be a duplicate of #4135, but I'm not sure how the solution there can be applied here.

**Comment by DanielRosenwasser** [comment]
I'm not seeing this behavior. Can you try out the current nightly by running `npm install -g typescript@next` and letting us know if that fixes it?

**Comment by ryansmith94** [comment]
I have new errors on the nightly build, will look into this after Christmas @DanielRosenwasser, merry Christmas! :smile:

**Comment by ryansmith94** [comment]
@DanielRosenwasser the compiler seems to be ignoring my tsconfig.json file.

**Comment by DanielRosenwasser** [comment]
Can you share a minimal repro? Or share the project itself?

**Comment by ryansmith94** [comment]
Nothing has changed in my project, on the nightly build you can use my tsconfig with a typescript file using a promise, run the command I shared above and you'll hit `error TS2304: Cannot find name 'Promise'.`

**Comment by ryansmith94** [comment]
Ok fixed those errors by just stuffing all of my options into a command. Now I get module errors like
```
error TS2307: Cannot find module
```

**Comment by ryansmith94** [comment]
Everything compiles fine, but when I run `tsc` with the tsconfig below, I get TS2307 and TS2304 errors like it's ignoring the "node_modules" and "typings" directories. For the record, my project has three directories, "node_modules", "typings", and "src" (which contains my ts files). I'm running `tsc` from the root.

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "jsx": "react",
    "outDir": "es6",
    "rootDir": "src"
  },
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```

```
error TS2307: Cannot find module 'firebase'.
error TS2304: Cannot find name 'process'.
```

**Comment by DanielRosenwasser** [comment]
Without knowing more about your actual project, it's difficult for me to diagnose the issue. Can you share the repo at all?

**Comment by ryansmith94** [comment]
Yeah sorry, I understand that, I can't share the repo though unfortunately. My original issue is resolved in the nightly so I'm happy to close this issue, however I think there are some issues in the nightly around node_modules and typings. If I manage to figure out exactly why I'll create a new issue. Thanks for trying to help @DanielRosenwasser.

**Comment by ryansmith94** [comment]
For the record I've isolated my TS2307 issue in https://github.com/ryansmith94/TS2307-Issue @DanielRosenwasser

**Comment by ryansmith94** [comment]
That issue has been resolved on Gitter.

**Comment by DanielRosenwasser** [comment]
In the interest of helping people who run into any similar issue, [here is the link](https://gitter.im/Microsoft/TypeScript?at=568309380199d70069e026eb to the resolution in the Gitter chat on [December 29, 2015 5:29 PM](https://gitter.im/Microsoft/TypeScript?at=568309380199d70069e026eb).
