### ISSUE TITLE
Broken JSX output when using imported classes

### ISSUE THREAD

**Issue by louy** [Microsoft/TypeScript#6249]
Hi, I have a very strange issue with tsx. I'm getting opening/closing tags that don't match each other. Here's my setup:

## child.tsx
```tsx
import * as React from 'react';

class Child extends React.Component<{}, void> {
  render() {
    return <div />;
  }
}

export default Child;
```

## parent.tsx
```tsx
import * as React from 'react';
import Child from './child';

class Parent extends React.Component<{}, void> {
  render() {
    return (
      <Child></Child>
    );
  }
}

export default Parent;
```

## tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "jsx": "preserve"
  },
  "exclude": [
    "node_modules"
  ]
}
```

The issue is in the following output file:
## parent.jsx
```jsx
var React = require('react');
var child_1 = require('./child');
class Parent extends React.Component {
    render() {
        return (<child_1.default></Child>);
    }
}
exports.default = Parent;
```

I've tried changing `export default` to `export class` and it still didn't work. Same issue. Also tried changing `module` to `amd` and `target` to `es5` and it didn't help. Here's a [demo project](https://github.com/louy/tsx-issue). I'm stuck now. Help!

**Comment by DanielRosenwasser** [comment]
Current behavior on our nightly is

```js
"use strict";
var React = require('react');
var child_1 = require('./child');
class Parent extends React.Component {
    render() {
        return (<child_1.default></child_1.default>);
    }
}
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Parent;
```

But I think that's a problem because I think that'll get intepreted as a JSX intrinsic element.

**Comment by louy** [comment]
You're right. It's fixed in nightly. Is there a chance that you can release a patch for this instead of waiting for 1.8? I don't want to use nightly builds for production projects.

Also I have another concern. Is it possible to avoid renaming `Child` to `child_1`?

**Comment by louy** [comment]
The issue has nothing to do with `default` in import/export btw.

**Comment by louy** [comment]
Yeah "intrinsic element" is what I meant with avoiding renaming imported variables. Do you know what's the reason behind renaming all imported variables anyway?

**Comment by louy** [comment]
The simplest (and cleanest) solution I can think of for the "intrinsic" part of the issue is converting this:
```ts
import Child from './child';
```
to this:
```ts
var Child = require('./child').default;
```

I think it's much cleaner than always referencing `child_1.default`. I wish you'd also apply this to non-jsx output.

**Comment by DanielRosenwasser** [comment]
Actually, I think this is the correct behavior. A dotted name [seems to be interpreted as a component by Babel 5.x](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=var%20x%20%3D%20%3Ca.foo%3E%3C%2Fa.foo%3E). I'll wait on @RyanCavanaugh before saying anything definite.

**Comment by RyanCavanaugh** [comment]
Dotted names are never intrinsic.

As for the naming of the synthetic imports, I don't think any casing has obvious advantages over the other. Unless there's a real reason to do otherwise, I'd rather leave it alone.

Regarding this

 > var Child = require('./child').default;

I'm not sure this is a safe transform. The default export is just the name `default`, nothing fancy, so it's not guaranteed that it's not a getter or something else with side effects.

If there's not a concrete repro with a real issue, I'll close this.

**Comment by louy** [comment]
Okay. #6264 discusses the naming convention.
This issue has been solved in **typescript@next** already but it still affects **1.7.5**. Any deadline for **1.8**?
Thanks btw. 😊

**Comment by RyanCavanaugh** [comment]
Pretty much everyone is out for the holidays, but I'll see if we can get a 1.7.6 release out to address this one. I don't have a timeline for 1.8 available.
