### ISSUE TITLE
Respect encoding of source file

### ISSUE THREAD

**Issue by LNWD** [Microsoft/TypeScript#6253]
The generated js file is always in ANSI (or the current codepage). My TypeScript source is in UNICODE but the generated output not. On Internet Explorer this is not a problem. But other browsers like Chrome or Safari struggles if the HTML page is in UNICODE and the included js file is not. So it would be nice to specify the file encoding (ANSI, UTF-8, UNICODE) of the output or inherit it from the source file.

**Comment by DanielRosenwasser** [comment]
If you used `--emitBOM`, then your generated `.js` files would have a UTF-8 byte order mark. I think this would be the more appropriate fix. Supporting more target encodings is not a complexity that's worth taking on.
