### ISSUE TITLE
Need Documentation for VS2015 tools and Angular 2

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/TypeScript#6254]
It's too complex to set up Angular 2 development set up with VS2015 typescript html application template, and nowhere to look up, and almost no reference.

some hello world from typescript tools for VS2015 example would suffice

**Comment by akeloin** [comment]
I give up with VS2015. I had begin to use VS code instead.

**Comment by alanpurple** [comment]
@akeloin  I just manually installed npm typescript globally and used tsc -w in powershell,  I gave up with 'HTML Application with TypeScript' template

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript-Handbook#166
