### ISSUE TITLE
What is the default target? (please clarify)

### ISSUE THREAD

**Issue by glen-84** [Microsoft/TypeScript#6256]
[This page](https://github.com/Microsoft/TypeScript/wiki/Compiler%20Options) shows a default target of ES3, and [this page](http://json.schemastore.org/tsconfig) shows a default target of ES5 – is this intentional (when a tsconfig file is used, the default changes?) or is this a "bug"?

Also, what is the default for "module", or does that depend on the target?

Thanks. =)

**Comment by DanielRosenwasser** [comment]
I'm not entirely familiar with what a JSON schema considers as a default. By default, we *generate* a `tsconfig.json` that uses ES5 as a target, but if the value is *omitted*, we will default to ES3.

I think it's probably the latter, so schemastore probably has it wrong.

The default for `module` is that there is no module system at all; you're just writing script files that don't utilize modules at all.

Also, while schemastore lists `moduleResolution`'s default as `classic`, it depends on your `module` option (i.e. using `node` resolution for `commonjs`, but not for `amd`).

**Comment by DanielRosenwasser** [comment]
Actually, I'm not 100% sure, so @paulvanbrenk and @madskristensen, can you answer what "default" is intended to mean?

**Comment by paulvanbrenk** [comment]
That's probably a bug in the schema. I'll update that.

**Comment by glen-84** [comment]
@mhegazy I don't think that this has been fixed yet.

**Comment by mhegazy** [comment]
@paulvanbrenk commented on a PR to fix this one: https://github.com/SchemaStore/schemastore/pull/80/files#r48884389

**Comment by glen-84** [comment]
Ah cool, thanks guys. =)

**Comment by paulvanbrenk** [comment]
And a better PR: https://github.com/SchemaStore/schemastore/pull/136
