### ISSUE TITLE
"for of" does no transpile to a fully optimized "for" loop

### ISSUE THREAD

**Issue by sdenel** [Microsoft/TypeScript#6258]
This snippet:
```
let A: string[] = ['1', '2', '3', '4'];
for(let a of A) {
    console.log(a);
}
```
transpiles to:
```
var A = ['1', '2', '3', '4'];
for (var _i = 0, A_1 = A; _i < A_1.length; _i++) {
    var a = A_1[_i];
    console.log(a);
}
```

IMHO, it should compile to something like:
```
var A = ['1', '2', '3', '4'];
for (var _i = 0, A_1 = A, A_1_length = A_1.length; _i < A_1_length; _i++) {
    var a = A_1[_i];
    console.log(a);
}
```
To avoid calling length property during each iteration.

**Comment by DanielRosenwasser** [comment]
We need to maintain this behavior because it's possible to modify the array while it is being iterated over. While it's not a common case for many people, some will take advantage of that behavior.

**Comment by sdenel** [comment]
Hi Daniel,

For the record, according to:
* http://stackoverflow.com/a/17995000/1795027
* and more precisely this jsperf: http://jsperf.com/cache-length-no-cache

My suggestion seems to be less optimized anyway.

**Comment by felixfbecker** [comment]
@DanielRosenwasser but isn't it impossible to modify the iterator of a `for..of` loop?

**Comment by DanielRosenwasser** [comment]
@felixfbecker you have to be more specific about what you mean.

**Comment by felixfbecker** [comment]
@DanielRosenwasser I basically meant that the value you iterate over gets "copied" once at the beginning of the `for..of` loop and if you modify the underlying array, it will have no effect. I could be wrong though.

**Comment by DanielRosenwasser** [comment]
@felixfbecker that's not the behavior as far as I can tell. Check out the section [22.1.5.1 CreateArrayIterator Abstract Operation](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-createarrayiterator).

[CoreJS will exhibit the same behavior](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=let%20x%20%3D%20%5B1%2C2%2C3%5D%3B%0D%0Alet%20b%20%3D%20false%3B%0D%0A%0D%0Afor%20(let%20k%20of%20x)%20%7B%0D%0A%20%20if%20(!b)%20%7B%0D%0A%20%20%20%20x.pop()%3B%0D%0A%20%20%20%20b%20%3D%20true%3B%0D%0A%20%20%7D%0D%0A%20%20console.log(k)%3B%0D%0A%7D) with the following:

```js
let x = [1,2,3];
let b = false;

for (let k of x) {
  if (!b) {
    x.pop();
    b = true;
  }
  console.log(k);
}
```

Output:

```
1
2
```
