### ISSUE TITLE
"for of" loops should not allow loop variabe to be overriden.

### ISSUE THREAD

**Issue by sdenel** [Microsoft/TypeScript#6259]
Consider this snippet:

```
let A: any[] = [[1], [2], [3], [4]];
console.log(A); // displays: [ [ 1 ], [ 2 ], [ 3 ], [ 4 ] ]
for(let element of A) {
    element = "hello";
}
console.log(A); // displays: [ [ 1 ], [ 2 ], [ 3 ], [ 4 ] ]
```

IMHO, "element" should be read-only, to avoid such writings that are error-prone.

**Comment by DanielRosenwasser** [comment]
You should use a `const` declaration for `element` since that's its purpose. Otherwise, I don't think it'd be reasonable to disallow this.
