### ISSUE TITLE
Methods should be private by default

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6260]
Isn't it safer if class methods are private by default? Calling methods that aren't meant to be called outside a class definition would yield erroneous result.

People often type the method names and accidentally forget to type the keyword `private`. Also functions in modules are private by default and you can only make it public by the `export` keyword. I don't see any reason why class methods shouldn't be.

**Comment by kitsonk** [comment]
a) that would break everyones code...
b) isn't aligned to the ES standard, which is a major design goal of TypeScript
c) there isn't really "private" in JavaScript
d) languages that do not require a specific scoping of methods infer public, not the other way around

**Comment by tinganho** [comment]
To be fair, the `private` keyword already breaks `b), c), d)`.

Even though it breaks everyone's code I think it would be easy to just convert everyone's code by just inserting a `public` keyword infront. Swift has adopted a strategy of breaking code and offered a tool to convert.

**Comment by kitsonk** [comment]
> Swift has adopted a strategy of breaking code and offered a tool to convert.

Yes, but TypeScript has this design goal:

> 11. Do not cause substantial breaking changes from TypeScript 1.0.

I still don't think you justified your case though.  Why would this be a good idea.  Most languages either require scoping to be explicit or it is implied public.  TypeScript is implied public, which means that a TypeScript and ES6 can be interchangeable in this case:

```typescript
class A {
    foo () { return 'bar'; }
}
```

What you are proposing, for what advantage I am still not clear, makes ES6 and TypeScript incompatible.

**Comment by DanielRosenwasser** [comment]
In addition to TypeScript breaking changes, this would cause a lot of friction for any existing ES6 code. This is exacerbated by the potential for [future ECMAScript proposals for opt-in member privacy](https://github.com/wycats/javascript-private-state), which I think would create a lot of confusion for future users.

**Comment by umagon** [comment]
I would like a flag to turn this on or off... I've found myself seeing methods in intellisense that were not designed to be called outside the class that defines it. And that's the nature of 90% of my methods!

**Comment by kitsonk** [comment]
>  I've found myself seeing methods in intellisense that were not designed to be called outside the class that defines it.

Can you show a screenshot where a private method is being displayed in intellisense?  Because that shouldn't be happening.

**Comment by umagon** [comment]
It's working fine. I meant that almost all my methods are designed to be used only by the class itself so a flag to turn on or off "private by default" would be useful.

**Comment by ackvf** [comment]
While developing React web applications, I never had the need to write a publicly available method. A flag for implicit `private` accessor would be handy.

**Comment by aMoniker** [comment]
I have the same use case with React components: almost every method should be private.

What's the argument against making this behavior configurable with a flag?
