### ISSUE TITLE
Building as library

### ISSUE THREAD

**Issue by gotenxds** [Microsoft/TypeScript#6261]
Hello, I'm trying to create a small librery using TypeScript.

I want to compile all of my files to a single file and allow the users to import any or all of the classes included in that file in an easy why.

What would be the recomanded way to achive this ?

**Comment by DanielRosenwasser** [comment]
In our nightly builds of TypeScript, we support module bundling by using the `--module` and `--outFile` flags. You'll need to install the nightlies by running `npm install -g typescript@next`.

**Comment by DanielRosenwasser** [comment]
I'm not sure if we support putting together a single `.d.ts` file though. @weswigham and @vladima should know what the situation is on that.

**Comment by weswigham** [comment]
We do - we generate an ambient declaration file.

**Comment by DanielRosenwasser** [comment]
Then give it a shot @gotenxds :smile:
