### ISSUE TITLE
Mixin error on getters and setters 

### ISSUE THREAD

**Issue by gotenxds** [Microsoft/TypeScript#6262]
Hello, I'm trying use mixing to combine a class with 2 outer classes like so:

```
export default class JustContext extends ContextDecorator implements ChangeNotifyingContext, RedrawableContext {
// Some code
}
```

I then apply the mixin

``
`applyMixins(JustContext, [ChangeNotifyingContext, RedrawableContext]);```

ChangeNotifyingContext extends ContextDecorator as well, that has a getter:
```
export default class ContextDecorator {
    private context:CanvasRenderingContext2D;

    get strokeStyle() : string | CanvasGradient | CanvasPattern{

        return this.context.strokeStyle;
    }
```

At runtime I get the error : 

```
Uncaught (in promise) Error: Cannot set property 'strokeStyle' of undefined(…)
```
at the apply mixing method:

```
applyMixins(derivedCtor:any, baseCtors:any[]) {
    baseCtors.forEach(baseCtor => {
        Object.getOwnPropertyNames(baseCtor.prototype).forEach(name => {
            if (name !== 'constructor') {
                derivedCtor.prototype[name] = baseCtor.prototype[name]; // Error is here
            }
        });
    });
```
For some reason the mixin tries to run the getter method but for no instance so the property of `canvas` is undefined.

Why dos this happen ?

**Comment by louy** [comment]
Apparently `derivedCtor.prototype` is undefined. Try adding this:

    derivedCtor.prototype = derivedCtor.prototype || {};

Should solve the error, but won't make what you want happen.
AFAIK, getters/setters are not prototype methods. They use `Object.defineProperty` in the constructor function. You can't use them like this.

**Comment by gotenxds** [comment]
Hi, thanks for the replay, I tried your suggestion but like I said it not
the prototype that is undefined.
You call also see this here in this picture I took from the debugger:

[image: תמונה מוטבעת 1]

2015-12-27 18:18 GMT+02:00 Louy Alakkad <notifications@github.com>:

**Comment by mhegazy** [comment]
From the information available here looks like you never initialize the `context`. also this kind of issues would be more suited to StackOverFlow.
