### ISSUE TITLE
Feature Request: TypeScript Engine for .NET

### ISSUE THREAD

**Issue by neurospeech** [Microsoft/TypeScript#6263]
It is good to have TypeScript compiled into JavaScript. But at the same time, it would be nice to have a TypeScript Engine pretty much same as JInt or IronJS, which will allow us to execute TypeScript right within .NET.

Use case:
1. Create reusable TypeScript components that can be used in nodeJS as well as ASP.NET MVC
2. Can reuse Entity Framework or any .NET based library within TypeScript Engine

**Comment by DanielRosenwasser** [comment]
This is similar to #2565 and #5200. That's not really in the scope of the TypeScript project, and if someone else would be willing to do that, that'd be great. To achieve something similar, I would recommend looking into [Edge.js](http://tjanczuk.github.io/edge/) to achieve something like this, and look into node packages that are able to run TS code on the fly if that's really a necessity.
