### ISSUE TITLE
`_1` suffix when converting ES6 import to ES5

### ISSUE THREAD

**Issue by louy** [Microsoft/TypeScript#6264]
Consider this code:
```ts
import Test from 'test-file'; 
new Test();
```
currently it gets compiled to:

```js
var test_file_1 = require('test-file');
new test_file_1.default();
```

what I would expect is this:

```js
var Test = require('test-file').default;
new Test();
```

This doesn't fit with the design goals of Typescript. It also causes some problems like #6249 in tsx/jsx.
Any reason for it being the way it is?

**Comment by louy** [comment]
Same thing for non-default import.
```ts
import {Test} from 'test-file'; 
new Test();
```
```js
var test_file_1 = require('test-file');
new test_file_1.Test();
```

**Comment by vladima** [comment]
it is done to preserve ES6 semantic for imports: 
```ts
// module1
export let x = 1;
// module2
import {x} from "./module1"
```
During [ModuleDeclarationInstantiation](https://tc39.github.io/ecma262/#sec-moduledeclarationinstantiation) of `module2` [CreateImportBinding](https://tc39.github.io/ecma262/#sec-createimportbinding) for `x` will create indirect binding to `x` in `module1`. This means that whenever `x` in `module1` is changed `module2` should see new value.  If compiler will convert `import {x} from "./module1"` to `var x = require("./module1").x` it will capture initial value of `x` but will miss all subsequent changes

**Comment by louy** [comment]
Oh nice. I didn't know about that. So what about the `_1` suffix then? Wouldn't something like `test_file` work just fine?

**Comment by vladima** [comment]
this is just a way TypeScript compiler generates fresh unique names, also makes it easier to visually distinguish synthesized names from user defined ones.

**Comment by abirmingham** [comment]
How can one track browser progress on supporting sourcemaps for mapping import bindings, e.g. x to x_1? Are there particular issues for this request?
