### ISSUE TITLE
Resolved value from promise is always {} from compile time, cause error

### ISSUE THREAD

**Issue by alanpurple** [Microsoft/TypeScript#6269]
it seems that type checking always fails except type 'any; for resolved value from Promise

public data:SomeType

getData(){
   this._someService.getData().then(data=>this.data=data);  // always emit TS2332 error
}

==========================

with
public data;

it works

**Comment by vladima** [comment]
cannot repro locally using the latest bits on master:
```ts
interface SomeType { x }
interface Service { getData(): Promise<SomeType> }
class A {
    _someService: Service;
    data: SomeType;
    getData(){
        this._someService.getData().then(data=>this.data=data);
    }
}
```
`node built\local\tsc.js D:\sources\bugs\a.ts -t es6` yields no errors and produces the following javascript:
```javascript
class A {
    getData() {
        this._someService.getData().then(data => this.data = data);
    }
}
```

Can you check if your scenario has any specifics that reveal the problem?

**Comment by alanpurple** [comment]
@vladima 

official angular2 site tutorial

https://angular.io/docs/ts/latest/tutorial/toh-pt4.html

export class AppComponent implements OnInit {
  public title = 'Tour of Heroes';
  public heroes: Hero[];
  public selectedHero: Hero;
  constructor(private _heroService: HeroService) { }
  getHeroes() {
    this._heroService.getHeroes().then(heroes => this.heroes = heroes);
  }
  ngOnInit() {
    this.getHeroes();
  }
  onSelect(hero: Hero) { this.selectedHero = hero; }
}

TS2332: length property missing,    {} cannot be assigned to type Hero[]

**Comment by vladima** [comment]
still cannot repro. I've downloaded the sample from [this link](https://angular.io/resources/live-examples/toh-4/ts/plnkr.html), added `tsconfig.json` and tried to build the code - still cannot see any errors. My repro bits can be found [here](https://github.com/vladima/ts-6269), can you check if there are any differences in your code?

**Comment by alanpurple** [comment]
@vladima  If my code is wrong, without ':Hero[]' there should be an error also

and even before compiling, there's already an red underscore error mark from intellisense

my environment is Windows 10 x64 + VS2015 + TypeScript 1.7.5

**Comment by alanpurple** [comment]
![image](https://cloud.githubusercontent.com/assets/4515120/12045788/ec885674-aeed-11e5-9e79-02f5525350e3.png)

tsconfig - same as angular.io quickstart guide

car.ts

export interface Car {
    id: number,
    name: string
}

car.service.ts

import {Injectable} from 'angular2/core';
import {Car} from './car';
import {CARS} from './mock-cars';

@Injectable()
export class CarService {
    getCars() {
        return new Promise(resolve=>
            setTimeout(() => resolve(CARS), 2000)
        );
    }
}

**Comment by DanielRosenwasser** [comment]
@alanpurple I've been fixing your examples, but you should surround your code samples with [code fences](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

Start your code off with ` ```ts ` and end it with ` ``` `.

**Comment by alanpurple** [comment]
@DanielRosenwasser Yeah thanks for the tip :)

**Comment by DanielRosenwasser** [comment]
I think the problem is that there's nothing we can infer for the type argument in `getCars`. If you make your `getCars` the following:

```ts
    getCars() {
        // Notice the type argument 'Car[]'
        return new Promise<Car[]>(resolve=>
            setTimeout(() => resolve(CARS), 2000)
        );
    }
```

I think that should take care of it.

#5254 is probably related.

**Comment by alanpurple** [comment]
@DanielRosenwasser  Thx, solved, and sorry for not seeing correctly

**Comment by DanielRosenwasser** [comment]
No problemo! It can be pretty subtle.
