### ISSUE TITLE
Property 'float' does not exist on type 'CSSStyleDeclaration'

### ISSUE THREAD

**Issue by sgnix** [microsoft/TypeScript#6270]
Property `float` should be part of the CSSStyleDeclaration.

```
var left = document.createElement('div');
left.style.float = "left";
```

Returns error: Property 'float' does not exist on type 'CSSStyleDeclaration'

**Comment by rielz** [comment]
To access the CSS float property you have to use [`cssFloat`](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-cssfloat).

**Comment by DanielRosenwasser** [comment]
Thanks @rielz, you seem to be correct.

From https://developer.mozilla.org/en-US/docs/Web/CSS/float

> Note: If you're referring to this property from JavaScript as a member of the `element.style` object, you must spell it as `cssFloat`. Also note that Internet Explorer versions 8 and older spelled this `styleFloat`. This is an exception to the rule that the name of the DOM member is the camel-case name of the dash-separated CSS name (and is due to the fact that "float" is a reserved word in JavaScript, as with the need to escape "class" as "className" and escape `<label>`'s "for" as "htmlFor").

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by huytd** [comment]
It is currently working, with TypeScript v4.6.2

https://www.typescriptlang.org/play?#code/DYUwLgBCwQvBATA9gYwK4FsQDswDoBzcAUVC1wCEBPASQQAoAiAJySTEYEoBuAKAEsAZhHrROEAN68IMqMDwBnMFVB5BwJAENI8RgAtoGxnwC+QA

I think we can close this issue.

**Comment by RyanCavanaugh** [comment]
Thanks!
