### ISSUE TITLE
Symbols couldn't convert properly with String() method

### ISSUE THREAD

**Issue by greybax** [Microsoft/TypeScript#6272]
The next statement should return ```true```:

```javascript
return String(Symbol("foo")) === "Symbol(foo)";
```

**Comment by weswigham** [comment]
This statement is always false - the lefthand side if the equality is not a string primitive, but rather a string object - string objects are only checked by reference equality. Since the right hand side is not a string object (its a string primitive), the two are never equal. This isn't a typescript thing - this is normal JS behavior.

**Comment by oleg-py** [comment]
@weswigham in JS when you call String(obj) without `new`, you get a primitive string, same as using `obj+''`

**Comment by johnfn** [comment]
@weswigham Typing that command into the Javascript console on Chrome (with the experimental Javascript flag on) returns `true` for me.

**Comment by SaschaNaz** [comment]
The same is `true` on Edge and Firefox.

**Comment by weswigham** [comment]
Op, sorry, I was mistaken - totally though I saw `new`.

**Comment by DanielRosenwasser** [comment]
I believe that this either depends on your JS runtime or your polyfill, so this isn't TypeScript-specific.

**Comment by greybax** [comment]
@DanielRosenwasser this feature one of the required for full support of Symbols in TypeScript.
This issue also mentioned in [compat-table/es6](http://kangax.github.io/compat-table/es6/#typescript)
![q](https://cloud.githubusercontent.com/assets/3235047/12031295/631afc02-ae1b-11e5-9a5f-aeb92cbf3921.png)

**Comment by kitsonk** [comment]
@greybax but if you notice, it is not something that is down emittable to ES5.  All the transpilers don't (cannot) support it, because it depends on the runtime engine behaving different in ES6.

**Comment by DanielRosenwasser** [comment]
@kitsonk is correct. Babel achieves this here by bundling core.js. We could also bundle core.js to achieve some of the runtime polyfills, but we'd prefer to avoid adding a dependency if possible and let users opt in to that on their own.

**Comment by greybax** [comment]
ok
