### ISSUE TITLE
How can I write tslint rule for check await to async functions

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#6273]
foo.ts
```typescript
export async function foo(){}
```

bar.ts
```typescript
import {foo} from './foo';
async function bar(){
   foo(); // I need lint warning that I forgot await keyword
}
```

I've tried write some code, but I don't understand how works typescript typechecker
```typescript
export class Rule extends Lint.Rules.AbstractRule {
    public apply(sourceFile: ts.SourceFile): Lint.RuleFailure[] {
        var options: ts.CompilerOptions = { target: ts.ScriptTarget.ES6 };
        var program = ts.createProgram([sourceFile.fileName], options);
        var typeChecker = program.getTypeChecker();
        return this.applyWithWalker(<Lint.RuleWalker>(new NoManyWalker(sourceFile, this.getOptions(), typeChecker)));
    }
}

class NoManyWalker extends Lint.RuleWalker {
    constructor(sourceFile: ts.SourceFile, options: Lint.IOptions, private typeChecker: ts.TypeChecker){
      super(sourceFile, options);
    }
    public visitCallExpression(node: ts.Node) {
        console.log("visitCallExpression");
        var type = this.typeChecker.getResolvedSignature(<any>node);
        var isAsync = Lint.isNodeFlagSet(type.declaration, ts.NodeFlags.Async);
        console.log(isAsync);
        super.visitCallExpression(node);
    }
}
```

It works for local async functions, but for imported functions I have a ts error: 
```
var moduleExports = getSymbolOfNode(location).exports;
TypeError: Cannot read property 'exports' of undefined
```

**Comment by DanielRosenwasser** [comment]
I'm vaguely familiar with the issue, but my understanding is that tslint doesn't do cross-module checking, which means that you won't have full semantic information about your program.

@weswigham is familiar with this. As a heads up these questions are probably more appropriate on the tslint repo itself.

(Also, you shouldn't need to assert any type to `any` for our API.)

**Comment by DanielRosenwasser** [comment]
See https://github.com/palantir/tslint/issues/680 and https://github.com/palantir/tslint/issues/692.

**Comment by adidahiya** [comment]
see https://github.com/palantir/tslint/issues/892

@DanielRosenwasser is correct about lacking full semantic information about the program to be able to write this rule right now. @JKillian explains more [here](https://github.com/palantir/tslint/issues/892#issuecomment-167029369)
