### ISSUE TITLE
Allow binding patterns in rest binding elements

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6275]
See https://github.com/Microsoft/TypeScript/issues/2519#issuecomment-167590461.

---

New grammar rules:

&nbsp;&nbsp;&nbsp;&nbsp;_BindingRestElement_<sub>`[Yield]`</sub>:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`...`_BindingIdentifier_<sub>`[?Yield]`</sub>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`...`_BindingPattern_<sub>`[?Yield]`</sub>

Relevant section:

https://tc39.github.io/ecma262/#sec-destructuring-binding-patterns

Old work for disalllowing the construct was performed here: #2754.

**Comment by JsonFreeman** [comment]
Remember to test this with ObjectBindingPattern as well, not just ArrayBindingPattern

**Comment by ajafff** [comment]
@DanielRosenwasser there are actually two separate parts to this issue:
* ParameterDeclaration and VariableDeclaration
  * only needs to remove the grammar check
  * downlevel emit already works as expected
* allow BindingPattern for FunctionRestParameter
  * needs to remove the grammar check
  * currently there is no downlevel emit at all

**Comment by weswigham** [comment]
Fixed by #26017
