### ISSUE TITLE
Improve error message when there is `input` is not closed in `tsx`

### ISSUE THREAD

**Issue by plantain-00** [Microsoft/TypeScript#6280]
The case is: I copied something from `html` file to `tsx` file, there is some `input`s that are not closed(which is legal in html, but not in jsx):

```ts
let TestComponent = React.createClass({
    getInitialState: function() {
        return {
            name: ""
        };
    },
    render: function() {
        return (
            <div>
                <input type="text" name="name">
            </div>
        );
    },
});
```

When compiled, the error message is:

```
components/test.tsx(17,1): error TS17002: Expected corresponding JSX closing tag for 'div'.
```

The line number is wrong, and it's not `div` that is not closed. 

It is easy to find the error for this code, but it's hard to find which tags are not closed when there are too much code.

**Comment by DanielRosenwasser** [comment]
Oddly, using the language service, I get at least two different error messages.

![image](https://cloud.githubusercontent.com/assets/972891/12030262/34f5c948-adca-11e5-99e8-e74a73c3b1bf.png)

![image](https://cloud.githubusercontent.com/assets/972891/12030306/b4357a78-adca-11e5-8770-0065004d2f07.png)

Would you find it more helpful if the original tag was underlined instead?
