### ISSUE TITLE
Add an ES6 lib.webworker.d.ts

### ISSUE THREAD

**Issue by bwalderman** [Microsoft/TypeScript#6282]
I ran into this when I tried to use ES6 features in a web worker script. The lib typings do not yet include an ES6 version of lib.webworker.d.ts. This makes it difficult to target ES6 for a project meant to run in a web worker.

As a workaround, I created lib.webworker.es6.d.ts which is a copy of the original that references lib.core.es6.d.ts instead of lib.core.d.ts. The permanent fix should be to generate this with the rest of the typings in the Jakefile.

**Comment by yuit** [comment]
We will fix this using library modularization. With the new flag `--lib`, to use both web-worker and es6, one can just do `--lib webworker es6`. So we will not generating the new combining lib file

**Comment by mhegazy** [comment]
This should be fixed by https://github.com/Microsoft/TypeScript/pull/7715. `--lib` support should be available now in `typescript@next` and in the next TypeScript release.
