### ISSUE TITLE
Promise catch error parameter should not be of type any.

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6283]
Is there any chance, you could change the any type on error parameter on the catch method of a Promise, to a type argument instead? The type argument is provided in the `Promise<R, E>` type annotation, instead of just `Promise<R>` .

```typescript

	/**
	 * Sugar for promise.then(undefined, onRejected)
	 *
	 * @param onRejected called when/if "promise" rejects
	 */
	catch<U>(onRejected?: (error: any) => U | Thenable<U>): Promise<U>;
```
I need to type annotate many catch method calls right now with:
```typescript
.catch(error:  HTTPResponse<ErrorResponse> | Error)
```

**Comment by DanielRosenwasser** [comment]
@rbuckton can you weigh in here?

**Comment by ivogabe** [comment]
I think it's not possible to type that accurately, as errors in a previous listener will be passed to the catch listener. Functions are not annotated with their possible errors, so the error could be everything, so `any` would be the most accurate type.
```typescript
somePromise.then(x => {
  throw "foo";
}).catch(error => {
  // error can also be a string here
});
```

**Comment by tinganho** [comment]
@ivogabe maybe it could be better handled with a union of type `any`?
```typescript
.catch(error:  HTTPResponse<ErrorResponse> | any)
```
Promise rejection are not exceptions only. you consciously reject sometimes. And I just think it is a good idea that people can handle those conscious rejections, i.e. give it a type.

**Comment by tinganho** [comment]
But after think about it. Maybe better to wait until default type argument lands in #2175? So that default error type is `any`. It also don't break anyones code then :smile: .

**Comment by aleksey-bykov** [comment]
anything united with `any` cannot be differentiated, if it has any it will stay `any`

try:
```typescript
function isString(value: string | any) : value is String {
    return typeof value === 'string';
}
let value : string | any;
if (isString(value)) {
    value // <-- check me
}
```

**Comment by tinganho** [comment]
Hmm strange, `typeof` guards works. 
```typescript
let value : string | any;
if ( typeof value === 'string') {
    value // <-- check me
}
```

**Comment by tinganho** [comment]
Just reported it here #6301.

**Comment by rbuckton** [comment]
@ivogabe is correct. The exception is typed `any` because we cannot guarantee the correct type of the exception at design time, and neither TypeScript nor JavaScript provide the ability to guard exception types at run time. Your best option is to use type guards to provide both a design-time and run-time check in your code.
