### ISSUE TITLE
VS15 Breakpoint not hit when redirecting output

### ISSUE THREAD

**Issue by piranha771** [Microsoft/TypeScript#6286]
Debugger doesn't stop at breakpoints if I activate output redirection in the project settings.

Issue Setup:
* Open Visual Studio 2015 Community Edition (Update 1)
* Create new project 'Blank Node.js Web Application'.
* Add directory to project root called 'publish'
* Add typescript file to project root called 'hello.ts'
* Add following code into 'hello.ts' and save it

`function sayHello() {
    console.log('Hello!');
}
export = sayHello;`

* Make a breakpoint on `console.log('Hello!');
* Open 'server.ts' and add `import sayHello = require('./hello');
sayHello();`
* Open project settings and activate output redirection with path: './publish'
* Run the project

Expected behavior:
The debugger stops at the console.log('Hello!'); line.

Observed behavior:
The debugger doesn't stop at the breakpoint.

Notes:
Any breakpoints in the startup file ('server.ts') are working. In every other file they are not. When the output redirection is deactivated the debugger works as expected in all files.

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look

**Comment by mhegazy** [comment]
this should be fixed in latest.
