### ISSUE TITLE
add a flag for preserving whitespaces

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6289]
The emmiter strips whitespaces agressively. It would be nice to keep the original formatting as much as possible in JavaScript.

**Comment by mhegazy** [comment]
The emitter tries to keep formatting as much as possible. but in general output formatting requests has mostly been out of scope. if there is a specific case you are running into with a simple fix we would consider.

**Comment by aleksey-bykov** [comment]
we favor functional style with lots of nested callas which gets output into a single line:


![image](https://cloud.githubusercontent.com/assets/937933/12103205/7ea72d0e-b30e-11e5-89fb-902086800dc8.png)

**Comment by mhegazy** [comment]
This looks isolated enough. we would consider a PR for adding a new line in call expressions if the source had one.
