### ISSUE TITLE
How to assign object literal to variable with private properties

### ISSUE THREAD

**Issue by claycephas** [Microsoft/TypeScript#6292]
Consider the following class:

```
class MyClass
{
  public prop1: string;
  private prop2: string;
}
```

How can I assign to an instance of this class using an object literal?

```
var x: MyClass = {
  prop1: "a",
  prop2: "b" // compiler complains that prop2 is public not private
};
```

**Comment by RyanCavanaugh** [comment]
Cross-posted at http://stackoverflow.com/questions/34523334/how-to-assign-object-literal-to-variable-with-private-properties
