### ISSUE TITLE
Decorator metadata does not work with inferred type from default value.

### ISSUE THREAD

**Issue by vilic** [Microsoft/TypeScript#6294]
For example:

```ts
class Foo {
    @deco
    bar = 10;

    @deco
    biu(yo = 'ha') { }
}
```

Emits `__metadata('design:type', Object)` for `bar`, and `__metadata('design:paramtypes', [Object])` for `biu`.

**Comment by mhegazy** [comment]
this is by design. only types specified by the user will be used, any inferred types will not. this allows for consistent emit even if we are not doing full program compilation, i.e. --isolatedModules.
