### ISSUE TITLE
Compilation Issues using tsc compiler and the VS IDE typescript tools. 

### ISSUE THREAD

**Issue by Karthick-NR** [Microsoft/TypeScript#6303]
I have been working on Typescript using both TSC compiler and VS typescript tools and came across the issue that compilation of variable in a class with two dataTypes using OR operator succeeds in VS2015 IDE but fails in tsc compiler. 

How can that differ?

Attached the screenshots .

TypeScript code
![typescript](https://cloud.githubusercontent.com/assets/13884205/12062972/6097c674-afcc-11e5-9c79-d658bcf43bdd.PNG)

JavaScript generated from TypeScript
![jsfromts](https://cloud.githubusercontent.com/assets/13884205/12062979/76beb67e-afcc-11e5-93b7-85f1a1a24faf.PNG)

alert from code for number
![alert1](https://cloud.githubusercontent.com/assets/13884205/12062996/b0d417aa-afcc-11e5-9503-f1ef75af9bde.PNG)

alert from code for string 
![alert2](https://cloud.githubusercontent.com/assets/13884205/12062997/ba81f722-afcc-11e5-9013-94b810a3134e.PNG)

compilation error in cmd prompt
![tscissue](https://cloud.githubusercontent.com/assets/13884205/12063003/c9a66710-afcc-11e5-98be-ecd5f090cb43.PNG)

**Comment by ivogabe** [comment]
It looks like the command line compiler is an older version. Can you run `tsc -v`?

**Comment by Karthick-NR** [comment]
![capture](https://cloud.githubusercontent.com/assets/13884205/12063308/85c210fc-afd2-11e5-92ba-f0b0949c37ef.PNG)

**Comment by Karthick-NR** [comment]
I have installed TypeScript now and again checked the version it says the same version.

![updated](https://cloud.githubusercontent.com/assets/13884205/12063359/9d4a4e5a-afd3-11e5-8cc2-24ffce4ab70d.PNG)

**Comment by Karthick-NR** [comment]
it seems that the issue is same as https://github.com/Microsoft/TypeScript/issues/2068
