### ISSUE TITLE
Flattening or elliminating/ignoring duplicate typings?

### ISSUE THREAD

**Issue by ffMathy** [Microsoft/TypeScript#6305]
Hi. Please see the question I have made here for a description of the problem.

http://stackoverflow.com/questions/34546446/flattening-typescript-typings-or-interfaces

Here's the post:

As a TypeScript developer, I have become too used to "Duplicate identifier" issues when working with `.d.ts` files.

Most recently, this occurred because I needed both the typings (`.d.ts` files) of Angular 2, and Parse. 

Angular 2 doesn't distribute their `.d.ts` files through `DefinitelyTyped`, so I had to fetch Angular 2 through NPM which includes the source files as well.

Now, Parse's `.d.ts` come from `DefinitelyTyped`. Fine - so far, so good.

The issue then arises because both of these libraries depend on Node JS typings. The Node JS typings of Parse are located in the `typings` folder, whereas the Node JS typings of Angular 2 are located in a subfolder under `node_modules/angular2`.

This gives me a huge amount of duplicate identifier issues when compiling.

<h3>So, the big question(s)</h3>
- Can I flatten `.d.ts` files so that it doesn't have duplicates somehow?
- Can I somehow make the TypeScript compiler ignore duplicate interface definitions?

**Comment by ffMathy** [comment]
I believe this is the biggest issue with TypeScript right now.

**Comment by kitsonk** [comment]
This is essentially duplicate, will be resolved by #4433.
