### ISSUE TITLE
Optional parameter metadata output.

### ISSUE THREAD

**Issue by jamcoupe** [Microsoft/TypeScript#6308]
Problem: I am parsing objects from strings using the "design:paramtypes" metadata parameter, however I want to specify optional parameters. I will need to create my own decorator to tell my parser when a parameter is optional. Much like Angular2 has done with their `@Optional` decorator.

Could the TypeScript compiler not output a new "design:paramoptionals" or something similar with a boolean array based on the `property?: Type` information?

**Comment by DanielRosenwasser** [comment]
Pinging @rbuckton

**Comment by mhegazy** [comment]
The changes coming to the decorator spec should address this request. though in a different way. please see https://github.com/wycats/javascript-decorators for more up-to-date information about the proposal being discussed by TC39 (the JavaScript standardization body). once that proposal is mature enough, TypeScript will be implementing these changes. closing this issue for now, as we do not intend to make any changes to the decorator design until the proposal is finalized.
