### ISSUE TITLE
Unable to rename the property of destructuring assignment

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6312]
Rename `a` to `b`.

``` ts
function f({a}: {a}) {
    f({a});
}
```

expected:

``` ts
function f({b}: {b}) {
    f({b});
}
```

actual:

``` ts
// rename the variable
function f({b}: {a}) {
    f({b});
}
// rename the declaration
function f({a}: {b}) {
    f({b});
}
```

**Comment by mhegazy** [comment]
Please check the repro in https://github.com/Microsoft/TypeScript/issues/6459#issue-126305999 as well.

**Comment by falsandtru** [comment]
I was able to reproduce that problem.

```ts
// renamed `A#foo` to `A#bar`
class A {
  bar: string;
}

class B {
  syntax1(a: A): void {
    let { foo } = a; // error, should be `{ bar }`
  }
  syntax2(a: A): void {
    let { bar: foo } = a;
  }
}
```

**Comment by RyanCavanaugh** [comment]
Another repro courtesy of @falsandtru that we should add tests for:

**Code**

Rename `var a` to `var c` in `a.ts`.

```ts
// a.ts
export var a;
// b.ts
import {a} from './a';
export {a}
```

**Expected behavior:**

```ts
import {c} from './a';
export {c}
```

**Actual behavior:** 

```ts
import {c} from './a';
export {a}
```

**Comment by sheetalkamat** [comment]
Another repro from test cases found during fixing this about destructuring assignment:
```TypeScript````
interface I {
    [|property1|]: number;
    property2: string;
}
var elems: I[];

var p2;
for ({ /*This should be referenced too*/property1 : p2 } of elems) {
}
```

**Comment by andy-ms** [comment]
This still does not work reliably. For example:

```ts
const x = 1;
const o = { x };
{
    const { x } = o;
    x;
}
```

Renaming any `x` will result in broken code.

**Comment by mhegazy** [comment]
leaving this issue and using https://github.com/Microsoft/TypeScript/issues/15787 to track the change.
