### ISSUE TITLE
Bug for this-type in literal object type

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/TypeScript#6315]
This code causes an error:

	type X<A> = {x: A}

	interface Foo {
		// works
		a(): X<this>
		// does not work
		b(): {x: this}
	}

Output:

	foo.ts(7,11): error TS2526: A 'this' type is available only in a non-static member of a class or interface.

It errors if the object type is defined inline, but works for a typedef.

**Comment by ahejlsberg** [comment]
This is by design. See discussion [here](https://github.com/Microsoft/TypeScript/pull/4910#issuecomment-142610342).
