### ISSUE TITLE
New Website Logo: Amirkabir Data Miners

### ISSUE THREAD

**Issue by MeTe-30** [Microsoft/TypeScript#6321]
- Name: Amirkabir Data Miners
- Homepage url: https://adm-co.net
- Brand Guidelines/Licensing: none
- Logo: https://adm-co.net/content/images/ADM_logo.svg

![adm_logo-01](https://cloud.githubusercontent.com/assets/4802801/12075323/a6b30b16-b191-11e5-8ba9-34d949942068.png)

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
