### ISSUE TITLE
Suggestion for autocompletion does not work in second type parameter

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6322]
VS2015 and Playground.

```ts
class C<T, U> {
}

new C<number, number>(); // work
var c = new C<number, n
                       ^
```

**Comment by mhegazy** [comment]
:) that is subtle. the completion position is a valid identifier definition location, it is parsed as:
`var (c = ((new C) <  number)) , n`, where parens indicate nodes.

I think this is a valid grammar production, and thus behaves as intended.

**Comment by DanielRosenwasser** [comment]
I'm going back and forth on this. Just because this is grammatically valid one way doesn't mean it should be a complete completion blocker. We have made efforts elsewhere to speculatively prepare for other constructs. I wonder if we could do better. But I'll close this for now.
