### ISSUE TITLE
ES6 modules unable to export global variables by their identifier

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6323]
```ts
export {console}
```

```
$ node_modules/.bin/tsc -m commonjs index
```

expected:

```js
"use strict";
exports.console = console;
```

actual:

```js
"use strict";
```

**Comment by vladima** [comment]
It is an open question if this is allowed. Per [15.2.1.16.2GetExportedNames( exportStarSet ) Concrete Method#](https://tc39.github.io/ecma262/#sec-getexportednames)
>For each ExportEntry Record e in module.[[LocalExportEntries]], do
**Assert: module provides the direct binding for this export.**

And in [15.2.1.16.4ModuleDeclarationInstantiation( ) Concrete Method](https://tc39.github.io/ecma262/#sec-moduledeclarationinstantiation) bindings in module are created for `VarScopedDeclarations ` and `LexicallyScopedDeclarations` of the module body so there will be no  bindings for global names in the module and assert above presumably should fail //cc @bterlson

**Comment by falsandtru** [comment]
It seems you are right. I agree with es spec.

**Comment by bterlson** [comment]
Quoth ES6:

> It is a Syntax Error if any element of the ExportedBindings of ModuleItemList does not also occur in either the VarDeclaredNames of ModuleItemList, or the LexicallyDeclaredNames of ModuleItemList.

this should be an early syntax error.

**Comment by falsandtru** [comment]
@vladima I am unable to get your defined re-exporting globals error in my reported case, why?

**Comment by vladima** [comment]
works fine for me using the latest bits from the master
```
vladima@vladima-W520:~/sources/git/TypeScript$ cat t.ts
export {console};
vladima@vladima-W520:~/sources/git/TypeScript$ node built/local/tsc.js -m commonjs t.ts
t.ts(1,9): error TS2661: Cannot re-export name that is not defined in the module.
```

**Comment by falsandtru** [comment]
sorry, I mistook the path. works well.
