### ISSUE TITLE
import syntax to support import of all exported types

### ISSUE THREAD

**Issue by a8775** [Microsoft/TypeScript#6324]
I have TS code that imports some types from a single file:
```import {TypeA,TypeB,TypeC} from './file';```

It would be nice to import of all exported types from a file with a star syntax, eg:
```import {*} from './file';```

**Comment by vladima** [comment]
looks like a duplicate of #2956 per [this comment](https://github.com/Microsoft/TypeScript/issues/2819#issuecomment-163134136).
