### ISSUE TITLE
Remove destructive methods in tuple type

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6325]
I think, tuple type should not have destructive methods because these methods break consistency between the interface and actual properties.

- Array#push
- Array#pop
- Array#shift
- Array#unshift
- Array#splice

```ts
var t: [boolean, number];
t.shift(); // now actual t type is [number]
```

**Comment by DanielRosenwasser** [comment]
I'm not sure we'd be willing to take that breaking change, but there is discussion at https://github.com/Microsoft/TypeScript/issues/4988#issuecomment-145705203 regarding an alternative interface from tuple types.

**Comment by aleksey-bykov** [comment]
@falsandtru, you might also find the following helpful, provided whole awkwardness of tuples in TypeScript:
```
interface T2<a, b> {
	1: a;
	2: b;
}
function t2<a, b>(one: a, another: b) : T2<a, b> {
	return <any> [one, another];
}

let pair = t2('hey', true);
let text = pair[1];
let flag = pair[2];
let problem = pair[3];
```

**Comment by mhegazy** [comment]
Tuples are just arrays. and thus can have these methods. at least this is the current design. @aleksey-bykov's answer should allow you to limit your tuples to a more strict subset.
