### ISSUE TITLE
Union returntype with void must return a value

### ISSUE THREAD

**Issue by Pajn** [Microsoft/TypeScript#6326]
I have a method declared as `stop(): void|Promise<void> {}` which get the error
>A function whose declared type is neither 'void' nor 'any' must return a value

As void is a valid return type I would expect that to be fully valid code. Specifying only void is working.

**Comment by RyanCavanaugh** [comment]
Proposing changing spec section 6.3

> An explicitly typed function whose return type isn't the Void or the Any type must have at least one return statement somewhere in its body

to

> An explicitly typed function whose return type isn't *the Void type, the Any type, or a union type containing the Void or Any type as a member* must have at least one return statement somewhere in its body

**Comment by DanielRosenwasser** [comment]
That still doesn't actually cover `Promise<void>` on its own though.

**Comment by RyanCavanaugh** [comment]
Not sure I understand the comment

**Comment by DanielRosenwasser** [comment]
The change you're proposing doesn't permit an async function whose return type annotation is `Promise<void>` to have no return statements.

**Comment by RyanCavanaugh** [comment]
I don't think anyone would want that behavior (@Pajn, care to weigh in?)

**Comment by Pajn** [comment]
It would be nice if Promise<void> didn't require a return statement in an async function. However for the issue I had the already proposed change would be enough.

**Comment by RyanCavanaugh** [comment]
Approved, accepting PRs. Should be easy.

**Comment by masaeedu** [comment]
@RyanCavanaugh Regarding:

> An explicitly typed function whose return type isn't the Void type, the Any type, or a union type containing the Void **or Any type as a constituent** must have at least one return statement somewhere in its body

Isn't the emphasized part redundant? The following already compiles:

    function f(): number | any {
    }

**Comment by RyanCavanaugh** [comment]
I think that's an implementation side effect of the compiler. The spec doesn't specify that `number | any` is equivalent to the Any type, though.
