### ISSUE TITLE
Too many forks to display

### ISSUE THREAD

**Issue by mihailik** [Microsoft/TypeScript#6332]
Since migrating from Codeplex, we've been able to follow every minute development via the Network tab:

https://github.com/Microsoft/TypeScript/network

Sadly, since around this Christmas the 1000 threshold had been crossed, and the page now opens with:

![screenshot from 2016-01-03 23-17-06](https://cloud.githubusercontent.com/assets/4041967/12081424/3d530164-b270-11e5-9378-1b82b2347497.png)

Any ideas?

Prune the forks somehow?
Pick some outdated branches and turn them into tags, maybe Github viz. gods ignore tags?
Talk to Github gang to show a subset of forks rather than that dummy message?

I've just killed my own repo so it dropped from 1016 to 1015.

**Comment by RyanCavanaugh** [comment]
We can't remove other people's forks and I doubt GitHub cares (it's not like we're the first repo to have over 1,000 forks). I don't think pruning our local branches will do anything either. Unfortunately I don't think there's any solution here other than GitHub fixing their display.

**Comment by DanielRosenwasser** [comment]
The branch view is still available at https://github.com/Microsoft/TypeScript/branches, which tends to be more useful for our repo.
