### ISSUE TITLE
Wiki broken for tsconfig.json

### ISSUE THREAD

**Issue by vamsivarikuti** [Microsoft/TypeScript#6335]
Refer: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json

**Comment by RyanCavanaugh** [comment]
It looks OK to me after a quick glance. What specifically is wrong?

**Comment by vamsivarikuti** [comment]
I tried to open multiple times, it is returning incomplete HTML, so everything looked like non-rendered HTML text file in the browser.
<img width="1436" alt="screen shot 2016-01-04 at 12 57 30 pm" src="https://cloud.githubusercontent.com/assets/7098541/12085156/c7e1a926-b2e2-11e5-9437-36cb4a6a035d.png">

**Comment by RyanCavanaugh** [comment]
This seems like more of a GitHub issue? Unless you think this is related to some specific content we put in the wiki

**Comment by vamsivarikuti** [comment]
Yes, I think its GitHub issue, Is there a place to log this bug report to GitHub?

I am able to read all other Wiki Pages. Only `tsconfig.json` is broken
Is this because of `.json` extension at the end of URL?

**Comment by RyanCavanaugh** [comment]
Unfortunately GitHub itself doesn't have an issue tracker. There's this form https://github.com/contact, though -- maybe you can just drop a link to this issue.
