### ISSUE TITLE
Declare module as a global variable

### ISSUE THREAD

**Issue by surenyonjan** [Microsoft/TypeScript#6338]
Hi, is there any workaround to generate module as a global variable?

When I declare a module like this: 
 
    // module.ts
    module p {
     export class Person {
        name: string
     }
    }
will obviously generated to:
 
    var p;
    (function (p) {
      var Person = (function () {
        function Person() {
        }
        return Person;
    })();
    })(p || (p = {}));

But I want `p` to be declared as global variable.

Ok, the reason I want specifically this is I am trying to use Meteor with Typescript. And I am defining my models inside a package. Since, Meteor Package Bundler only allows global variable to be exported, I always get `p.Person` as undefined

**Comment by vladima** [comment]
if you want `Person` to be visible outside of containing module you should export it:
```ts
// module.ts
module p {
 export class Person {
    name: string
 }
}
```
```javascript
// module.ts
var p;
(function (p) {
    var Person = (function () {
        function Person() {
        }
        return Person;
    })();
    p.Person = Person;
})(p || (p = {}));

```

**Comment by surenyonjan** [comment]
sorry, I forgot to put `export` but it did not solve my problem. The tweak was adding `this.p = p` after module declaration

Actually, Meteor intelligently parses the package code files and only allows global variable to be exported. So, `var p` remains hidden (not accessible from other packages also if it is exported) and I hoped if there is any workaround to get module `p` transpiled directly to `global variable p`
