### ISSUE TITLE
Issue in indentation when formatting consecutive objects

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#6339]
_From @louy on December 26, 2015 11:41_

There's a very annoying issue when hitting "format code" in a TS file. Here's an example:
```ts
[{
}, {
}]
// or
fn({
}, {
})
```
becomes:
```ts

[{
}, {
  }]
// or
fn({
}, {
  })
```

This gets really annoying when you have large nested objects containing things like functions etc...

_Copied from original issue: Microsoft/vscode#1661_

**Comment by dbaeumer** [comment]
_From @bpasero on December 28, 2015 8:5_

I guess this needs to be reported against TS.

**Comment by dbaeumer** [comment]
_From @louy on December 28, 2015 8:10_

So all code formatting is done in the tsserver? There are a couple of other issues as well.

**Comment by louy** [comment]
Duplicate: #6271
