### ISSUE TITLE
Permit merging of function and enum declarations

### ISSUE THREAD

**Issue by nexussays** [Microsoft/TypeScript#634]
```typescript
module foobar
{
   export function foo()
   {
      return;
   }

   export enum foo
   {
      bar,
      baz
   }
} 
```
results in valid javascript:
```javascript
var foobar;
(function (foobar) {
    function foo() {
        return;
    }
    foobar.foo = foo;

    (function (foo) {
        foo[foo["bar"] = 0] = "bar";
        foo[foo["baz"] = 1] = "baz";
    })(foobar.foo || (foobar.foo = {}));
    var foo = foobar.foo;
})(foobar || (foobar = {}));
```
...and even shows proper code hinting/completion in Visual Studio.

Yet it doesn't compile due to a duplicate identifier error: `Error	2	Duplicate identifier 'foo'`

Seeing as both the resulting JS and IDE support are already functioning, why is this a syntax error to tsc?

**Comment by RyanCavanaugh** [comment]
Seems like workarounds are OK and no one else is looking for this.
