### ISSUE TITLE
Find All References / Shift F12 Not Working across project

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#6341]
_From @jeffschwartz on December 17, 2015 14:53_

Invoking "Find All References" in a project .ts file only yields results for that file and not for all the other files in the project that also contain the reference, which is what I would expect it to have done.

I can also confirm that it the same behavior is also present in Atom's Typescript plugin.

My environment is:
Mac OS X 10.9.5
Code Version 0.10.3 (0.10.3)
Atom 1.3.2

_Copied from original issue: Microsoft/vscode#1416_

**Comment by dbaeumer** [comment]
_From @egamma on December 17, 2015 15:0_

You need to define a `tsconfig.json` file to define the scope of your project, pls see the [vscode ts doc](https://code.visualstudio.com/docs/languages/typescript).

**Comment by dbaeumer** [comment]
_From @jeffschwartz on December 17, 2015 15:7_

Hi @egamma. Thanks for the quick response. My project does have a tsconfig.json file and its contents are as follows:
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    },
    "filesGlob": [
        "**/*.ts",
        "**/*.tsx",
        "!node_modules/**"
    ],
    "compileOnSave": true,
    "buildOnSave": true,
    "atom": {
        "rewriteTsconfig": true
    },
    "files": [
        "src/core/api/CallStack.ts",
        "src/core/api/describe.ts",
        "src/core/api/it.ts",
        "src/core/environment/environment.ts",
        "src/core/queue/iqueueitem.ts",
        "src/core/queue/queue.ts",
        "src/core/queue/QueueManager.ts",
        "src/main.ts",
        "typings/q/Q.d.ts",
        "typings/tsd.d.ts"
    ]
}

**Comment by dbaeumer** [comment]
_From @egamma on December 17, 2015 15:12_

`filesGlob` is an extension to tsconfig.json that is specific to 'atom-typescript' it is not supported by the TypeScript Server and therefore by vscode. Could that be the cause that the scope is only a single file?

A reference search from src/main.ts should find the references in the files listed under the `files` section.

**Comment by dbaeumer** [comment]
_From @jeffschwartz on December 17, 2015 15:51_

Hi @egamma and thanks again for your quick response. I did some sherlocking. I removed all atom specific json entries from the tsconfig.json file and restarted Code. The results were identical. Then I invoked Find All References for a number of variables and types and noticed that it didn't work for interfaces, such as

interface IQueueItem {
    path: string,
    callback: () => void
}

which is the interface I was looking for originally and which raised the issue for me.

Please see the 2 images I have provided. One shows the results of plain old search for IQueueItem which finds it in numerous files. The other shows the results of Find All References for IQueueItem which finds it in only the current file.
![screen shot 2015-12-17 at 10 40 20 am](https://cloud.githubusercontent.com/assets/271288/11874008/6f4f27ec-a4ab-11e5-98a6-126d2ee9b3ae.png)
![screen shot 2015-12-17 at 10 41 24 am](https://cloud.githubusercontent.com/assets/271288/11874007/6f4768cc-a4ab-11e5-9415-c24099dcbe18.png)

I would expect that Find All References for IQueueItem to yield all the files in which the interface was used but that isn't the case.

**Comment by dbaeumer** [comment]
_From @jrieken on December 17, 2015 16:2_

By using `export =` you lose tracking of the `IQueueItem` cos it won't be referenced by that name anymore

**Comment by dbaeumer** [comment]
_From @jeffschwartz on December 17, 2015 16:19_

Hi @jrieken and thank you for your quick response. OK I understand but it still smells like a bug to me :). Find All References and even Change All Occurrences should be able to resolve export = value, object and type across files otherwise project-wide refactoring is severely hobbled IMHO.

**Comment by dbaeumer** [comment]
_From @jrieken on December 18, 2015 9:39_

I agree, but this very likely an issue on the TypeScript server side. I will wait for@dbaeumer to confirm.

**Comment by dbaeumer** [comment]
_From @jeffschwartz on December 18, 2015 12:26_

@jrieken thank you.

**Comment by dbaeumer** [comment]
As @jrieken already pointed out this is an issue in the tsserver not reporting the reference. Moving to the TypeScript team.

**Comment by mhegazy** [comment]
@jeffschwartz, what you are seeing is correct to me. i do not think the two names `IQueueItem` are the same. it just happens that hey have the same name. consider this example:

```ts
// file1.d.ts
declare namespace N {
     export var x: number;
}

declare module "M" {
    export = N;
}

// file2.ts

import N = require("M"); 

N; // Renaming N here would rename the namespace "N" above, 
   // which would not be expected, and is not correct as it is a public API, 
   // what you really want is to rename is the local import N, not all references to the namespace N.
```

The `N` in `import N = require("M")` is just a local name, just like you would have writen `var x = mod.x;` and should be part of the references to the other name.

if you want to get a consisten behaviour where you rename one and all instance are renamed, export it as a property, and not as `export =`

so your `iqueueItems.ts` should look like:
```ts
export interface IQueueItem {
    ....
}
```
and your `callstack.ts` would look like:

```ts
import {IQueueItem} from "..\queue\iqueueItem";

...
```
