### ISSUE TITLE
Can't compile TypeScript project

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6342]
I have just forked and cloned the `Microsoft/TypeScript` project, ran `npm install` in the root and started VS Code there.

All code files are cluttered with red squiggles and when I hit `SHIFT+CTRL+B` I get this error message:

```
couldn't be found.
Running jake --tasks didn't list any tasks. Did you run npm install?
Command "jake" is either misspelled or could not be found.
```

What am I doing wrong? Your help is very much appreciated.

**Comment by sandersn** [comment]
Did you do npm install -g jake?

**Comment by SetTrend** [comment]
Terrific! Works like a charm now. Thanks a lot!

All I struggling with now are quite a number of warnings in the jakefile.js, complaining Code doesn't know what `jake`, `task`, `fail` etc. is.

Am I perhaps missing some configuration for this?

**Comment by mhegazy** [comment]
you probaly need https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jake/jake.d.ts.

**Comment by SetTrend** [comment]
Absolutely, yes. That did the trick. Thanks a bunch!
