### ISSUE TITLE
allow partially specified type arguments

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6344]
Currently when it comes to using generics a developer has 2 options:
- to specify all type arguments 
- to omit all of them altogether

I am a big fan of the latter but it doesn't always work because of inference failure. Quite often it only takes  one explicitly specified type argument to help the inference algorithm to deduce the rest of the types, but there is no such option to specify just one.

```typescript
function fold<Values, Value, Cursor, Direction, Hint, Result>(
   values: Values,
   result: Result,
   start: (values: Values) => Cursor | void,
   advance: (cursor: Cursor) => Cursor | void,
   valueAt: (cursor: Cursor) => Value & Direction,
   hintAt: (cursor: Cursor) => Hint
   folding: (result: Result, value: Value & Direction, hint: Hint) => Result
) : Result {
return undefined;
}
```
Example. Almost everything is inferred but the Direction type parameter, which is specified explicitly via hypothetical syntax:
```typescript
let result = fold<,,, AsTowardsLatest,,>(values, result, start, advance, valueAt, hintAt, folding);
```
Alternatively named arguments might be considered (hypothetical syntax)
```typescript
let result = fold<Direction = AsTowardsLatest>(values, result, start, advance, valueAt, hintAt, folding);
```

**Comment by mhegazy** [comment]
This looks confusing, with little value. https://github.com/Microsoft/TypeScript/issues/2175 should be the way to go.
