### ISSUE TITLE
TSX: Stateless components error if one uses ref

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#6350]
The following demonstrates this: 

```tsx
interface FooProps{}
const Foo = (props:FooProps) => <div/>;
const foo = <Foo ref="foo"/>; // Error : Property `ref` does not exists on type `IntrinsicAttributes & FooProps`
```

I have latest react.d.ts and typescript as of yesterday :rose: /cc @RyanCavanaugh https://github.com/Microsoft/TypeScript/issues/5478

**Comment by RyanCavanaugh** [comment]
This is a correct error. You'd get a runtime error if you instantiated `foo`

**Comment by basarat** [comment]
Of course :rose:

**Comment by RyanCavanaugh** [comment]
Ref http://codepen.io/anon/pen/WrRqWb in case anyone else lands here
