### ISSUE TITLE
Typescript doesn't compile or map at saving time on TS 1.7.6 on Asp Net 5 rc 1 upd 1

### ISSUE THREAD

**Issue by mdelgadov** [Microsoft/TypeScript#6351]
I have VS 15 upd 1 with asp net 5 rc 1 upd 1.

My project is based in the asp net 5 template "Web Application"
I tried versions 4.5.2 to 4.6 of .net with the same result.

Usually when saving a TS file in wwwroot/app a Js and Js.Map files are generated.
I tested on templates other than Asp Net 5 and all work fine this way.

But since I installed VS 15 update 1 (and asp net 5 rc 1 upd 1 with it) the TS no longer compiles the js and map files.

**Comment by mhegazy** [comment]
@paulvanbrenk can you take a look?

**Comment by paulvanbrenk** [comment]
@mdelgadov Do you use a `tsconfig.json` file and do you have `Compile on save` enabled (see screenshot).

![image](https://cloud.githubusercontent.com/assets/5273975/12963677/ddcce954-d000-11e5-8952-35132182fa7a.png)
