### ISSUE TITLE
System.register module name update

### ISSUE THREAD

**Issue by guybedford** [Microsoft/TypeScript#6359]
Since posting https://github.com/Microsoft/TypeScript/issues/6097, we've decided to alter the format of `System.register` (while we still can!), to rather use a module context object as the second argument:

So that:

```javascript
export let name = __moduleName;
```

Becomes:

```javascript
System.register([], function($export, $moduleContext) {
  return {
    setters: [],
    execute: function() {
      $export('name', $moduleContext.id);
    }
  };
});
```

instead of:

```javascript
System.register([], function($export, __moduleName) {
  return {
    setters: [],
    execute: function() {
      $export('name', __moduleName);
    }
  };
});
```

This is so that this context argument can potentially be amended in future with additional metadata if and when this is specified at any point in future in the language.

My knowledge of TypeScript internals is quite limited, so I wasn't able to quickly get together a transformer to replace `__moduleName` with `$moduleContext.id`, but this should be relatively straightforward to do.

In the mean time, it may be worth reverting https://github.com/Microsoft/TypeScript/issues/6097 to avoid unnecessary breaking changes here.

This corresponds to Traceur PR https://github.com/google/traceur-compiler/pull/2051 and Babel PR https://github.com/babel/babel/pull/3166.

Apologies for any confusion here!

**Comment by mhegazy** [comment]
@guybedford feel free to send a PR when the design has stabilized on the SystemJs side.

**Comment by guybedford** [comment]
@mhegazy many thanks for understanding! We have the context object implementations merged into Traceur and Babel now (https://github.com/google/traceur-compiler/pull/2051 and https://github.com/babel/babel/pull/3166), so it would be great to get this in TypeScript. This would involve replacing instances of `__moduleName` with a `_context.id` member expression. I can try and give this a go again, but any tips for how to put such a transformation together would be very much appreciated too.

**Comment by mhegazy** [comment]
@guybedford any news about this?

**Comment by guybedford** [comment]
@mhegazy I'm still not sure what the best way would be to implement `__moduleName` identifier replacement within the existing TypeScript implementation. If someone can give me some pointers to how to go about this, I'll gladly dive in.

**Comment by vladima** [comment]
@guybedford out of curiosity, will it be simpler if instead of replacing `__moduleName` with `_context.id`  we'll inject `var __moduleName = _context.id` at the very beginning of the rewritten module?

**Comment by guybedford** [comment]
@vladima yes that would work! In the Babel and Traceur implementations, we only do this rewriting when needed to keep the output simple, but it works just as well.

**Comment by guybedford** [comment]
I've implemented the above suggestion in https://github.com/Microsoft/TypeScript/pull/6688.
