### ISSUE TITLE
Cannot use type that is re-exported by another module

### ISSUE THREAD

**Issue by lethalman** [Microsoft/TypeScript#6360]
I'm trying to re-export a class from a module `bar.ts` that has been imported from `foo.ts`. The class itself is usable but its type cannot be used for declaring variables. I'm using latest typescript 1.8.0-dev.20160105 from npm:

foo.ts (type definition):
```
export class Foo {
}
```

bar.ts (type re-export):
```
export = {
  Foo: require('./foo')
};
```

qux.ts (type usage):
```
import Bar = require('./bar');
var foo: Bar.Foo;
```

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs"
  }
}
```

The actual error:
```
$ tsc
qux.ts(2,10): error TS2503: Cannot find namespace 'Bar'.
```

I haven't found a way to re-export a type. It's useful for me to split up several database models in multiple files, and then aggregate all of them in a single file. However actually I'm losing the types.

**Comment by DanielRosenwasser** [comment]
With `bar.ts`:

```ts
export = {
  Foo: require('./foo')
};
```

We don't recognize that as `require` as an import form, so there's no type/namespace side that we know of.

Instead, I'd suggest you use an ES2015 style export:

* New `bar.ts`

  ```ts
  export { Foo } from "./foo";
  ```

While you're at it, you might as well use a new import form in `qux.ts` as well:

```ts
import * as Bar from "./bar";
let foo: Bar.Foo;
```

**Comment by lethalman** [comment]
Yeah I understand the problem, thanks for the answer.

Using `import * as Bar from "./bar"` gives `qux.ts(1,22): error TS2497: Module '"bar"' resolves to a non-module entity and cannot be imported using this construct.`.

While for `export { Foo } from "./foo";`, I don't have a `Foo` inside `foo.ts`, it's an `export = `.

**Comment by DanielRosenwasser** [comment]
If you really need to keep it as an `export =`, you'll need to use the old-style imports like so:

```ts
export import Foo = require("./foo");
```

for `foo.ts`.

If you use a module loader that automatically fixes up `export =` forms to `default` exports, you can use the `--allowSyntheticDefaultImports` which is available in the nightly.

**Comment by lethalman** [comment]
I think I will avoid using classes directly and go for `export class Foo` + `export { Foo} from './foo'`. It's quite ok, thanks :)

**Comment by lethalman** [comment]
Also `export import Foo = require('./foo');` + `export = Foo;` works very well.

**Comment by DanielRosenwasser** [comment]
Sounds good - I think we an close this up then.
