### ISSUE TITLE
Proposal: Add --pretty to tsconfig.json

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6363]
It's currenty hard to read TypeScript errors in VS Code:

![errors 1](https://cloud.githubusercontent.com/assets/9283914/12127104/99089e0c-b3f5-11e5-989e-93c11f91b98a.png)
<br/>
There is a `--pretty` option for TypeScript, but AFAIK it can't be used when using `gulp-typescript` or other task runner plug-ins.

So I'd like to suggest to add `pretty: boolean` to the `tsconfig.json` definition.
<br/>
Plus, I'd like to suggest to pimp the colors even more so the message and code positions can easily be read, too (not only the - rather uninformative - constant word "error"):

![errors 2](https://cloud.githubusercontent.com/assets/9283914/12127169/fcb69c6a-b3f5-11e5-9685-438ae84f14be.png)
*(Suggested colors are: green for code position, red for error keyword/code and dark yellow for the error message.)*

**Comment by mhegazy** [comment]
pretty is a supported configuration in your tsconfig today (using 1.8). however this only affects the output of tsc. what you are asking for is a request for gulp-typescript, the TS API has no control on how the gulp error messages are reported.
