### ISSUE TITLE
No support for scoped packages

### ISSUE THREAD

**Issue by WreckedAvent** [Microsoft/TypeScript#6364]
Hi,

Given a folder structure such as 

    node_modules/
      test/
        index.ts

      @ns/
        test/
          index.ts

    app/
      a.ts

    tsconfig.json

with both `index.ts` files consisting of

```typescript
export class Test {
  constructor(public name: string) { }
}
```

and `a.ts` consisting of

```typescript
import * as testNonScoped from 'test'
import * as testScope from '@ns/test'

const resultScoped = new testScope.Test('hi')
const resultUnScoped = new testNonScoped.Test('hi')
```
`tsc` 1.7.5 will error out with:

    app/a.ts: error TS2306: Cannot find module '@ns/test'

However, this will only occur for the [scoped npm package](https://docs.npmjs.com/misc/scope). My tsconfig is very simple and just sets the module system to ES6 and includes the tsd typings in addition to the `a.ts` file. 

Is there something I'm missing or are these simply just not supported?

**Comment by vladima** [comment]
I cannot reproduce this locally using the latest bits from master. I've created the following folder structure.
```
│   tsconfig.json
│
├───app
│       a.ts
│
└───node_modules
    ├───@ns
    │   └───test
    │           index.ts
    │
    └───test
            index.ts
```
Content of every file is the same with your repro and content of `tsconfig.json` is 
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "exclude": [
        "node_modules"
    ]
}
```
Running `node D:\sources\git\TypeScript\built\local\tsc.js -p .` produced no errors.

**Comment by WreckedAvent** [comment]
Your tsconfig was different from mine, so I retried `tsc` with your exact one and it was able to pick up the scoped package.

However, I still had it set to es6 so that I could downstep the compilation and let babel take care of async/await.

Here's my exact repo tsconfig:

```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "target": "es6",
        "sourceMap": true
    },
    "files": [
        "typings/tsd.d.ts",
        "app/a.ts"
    ]
}
```

**Comment by WreckedAvent** [comment]
Figured it out. You need a special compiler option set in order to get this to work:

```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "target": "es6",
        "sourceMap": true,
        "moduleResolution": "node"
    },
    "files": [
        "typings/tsd.d.ts",
        "app/a.ts"
    ]
}
```

Now the question is why this works fine when `target` is not set to `es6`.

**Comment by vladima** [comment]
`node` module resolution is enabled if you either turn it on explicitly (by using `"moduleResolution": "node"`) or if target module kind is `commonjs`. This explains why it didn't work for you if you just specify `"target": "es6"` - in this case (and also if you target any other module kinds without setting `moduleResolution`) compiler will use default pre-TypeScript-1.6 module resolution strategy that walks folder all the way up to the root and checks if current folder contains requested module and that is not compatible with `node`

**Comment by WreckedAvent** [comment]
Okay, I see. It's not that it was `es5` causing it per se, just that setting to `es6` disallows setting the `module`, and `commonjs` implies the `node`-style module resolution.

That seems to solve the mystery of why that fix works, and all that leaves now is the question mark over why it found `test` in `node_modules` if the non-node resolution system is incompatible with it. I presume based on your explanation it should have been looking for a `test` folder in the root where the `tsconfig.json` is, not in `node_modules`?

**Comment by vladima** [comment]
yes, this is correct. It should not be able to find both `test` and `@ns/test` and in fact this is what I'm seeing locally if I keep only `"target": "es6"` in `tsconfig.json`.
```json
{
    "compilerOptions": {
        "target": "es6",
        "noImplicitAny": false,
        "sourceMap": false
    }
}
```
```
D:\sources\bugs\scoped>node D:\sources\git\TypeScript\built\local\tsc.js -p .
app/a.ts(1,32): error TS2307: Cannot find module 'test'.
app/a.ts(2,28): error TS2307: Cannot find module '@ns/test'.
```

**Comment by WreckedAvent** [comment]
OK, figured out that piece to the puzzle. I had a file on disc in the same folder with the same name I was importing, but it wasn't in the csproj so I had forgotten about it. 

So my directory was *actually* this:

    node_modules/
      test/
        index.ts

      @ns/
        test/
          index.ts

    app/
      a.ts
      test.ts

    tsconfig.json

In a sense, this meant that `./test` and `test` were referring to the same module. It still worked when I switched it to the node resolution, but was actually pointing at the `test/index.ts` instead of `test.ts`. 

This solves all pieces of the puzzle. Thanks.
