### ISSUE TITLE
Debug tsserver from vscode

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#6368]
Hello,

I'd like to know if it is possible to debug tsserver from vscode.

typescript.tsdk points to the typescript sdk folder and the tsserver is running from the custom link(not from vscode tsserver).
So, when I modify the ts file in vscode, I'd like to get the breakpoints from Visual Studio 2015 dev mode. 

What is the config to achieve my goal ?

Thanks in advance for your help.

**Comment by vladima** [comment]
I would ask this question on [vscode](https://github.com/Microsoft/vscode) issue tracker since the way how VSCode loads `tsserver.js` and exposes hooks for debugging is not owned or maintained by TypeScript team.
