### ISSUE TITLE
Import Line from pre-ES6 module being skipped

### ISSUE THREAD

**Issue by erfangc** [Microsoft/TypeScript#6372]
This TS file, when transpiled to ES5/CommonJS, some how does Not have a require statement for 'highcharts-release'. It does have the proper require statements for React.

(this code compiles with out an error by the way, using `highcharts.d.ts` provided through `tsd`, I had to make a few modifications)

```tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import Highcharts = require('highcharts-release');

class Chart extends React.Component<any,any> {

    private chart:HighchartsChartObject;

    constructor(props:any) {
        super(props);
    }

    componentDidMount() {
        const node = ReactDOM.findDOMNode(this);

        var chartOptions = {
            chart: {
                type: 'area',
                renderTo: node as HTMLElement
            },
            title: {
                text: 'Historic and Estimated Worldwide Population Growth by Region'
            },
            subtitle: {
                text: 'Source: Wikipedia.org'
            },
            xAxis: {
                categories: ['1750', '1800', '1850', '1900', '1950', '1999', '2050'],
                tickmarkPlacement: 'on',
                title: null
            },
            yAxis: {
                title: {
                    text: 'Billions'
                },
                labels: {
                    formatter: function ():string {
                        return (this.value / 1000).toString();
                    }
                }
            },
            tooltip: {
                shared: true,
                valueSuffix: ' millions'
            },
            plotOptions: {
                area: {
                    stacking: 'normal',
                    lineColor: '#666666',
                    lineWidth: 1,
                    marker: {
                        lineWidth: 1,
                        lineColor: '#666666'
                    }
                }
            },
            series: [ ... ]
        };

        this.chart = new Highcharts.Chart(chartOptions);
        var axis:HighchartsAxisOptions = {
            id: "stuff",
            opposite: true,
            title: {
                text: "New Axis"
            }
        };
        this.chart.addAxis(axis);
        debugger;
    }

    render() {
        return <div></div>;
    }
}

ReactDOM.render(<Chart/>, document.body);
```

Excerpt of the transpiled output

```js
var __extends = (this && this.__extends) || function (d, b) {
...
};
var React = require('react');
var ReactDOM = require('react-dom');
var Chart = (function (_super) {
    __extends(Chart, _super);
    function Chart(props) {
        _super.call(this, props);
    }
   ...
})(React.Component);
ReactDOM.render(React.createElement(Chart, null), document.body);
//# sourceMappingURL=Chart.js.map
```

Notice the absence of the `require('highcharts-release');` line

this is my `tsconfig.json`

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "sourceMap": true,
        "jsx": "react"
    },
    "exclude": [
        "node_modules",
        "jspm_packages"
    ]
}
```

### TypeScript version: 1.7.5

**Comment by erfangc** [comment]
Please note that I added the following lines to `highcharts.d.ts`

```ts
declare module 'highcharts-release' {
    export = HighchartsStatic;
}
```

this is to make the "Cannot find module highcharts-release` go away

see original file [Here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/highcharts/highcharts.d.ts)

### Note

if I remove the `declare module` lines, the resulting CommonJS/ES5 output have the proper `require` statement. However, the "Cannot find module highcharts-release" comes back

**Comment by vladima** [comment]
as I can see In your code `Highcharts ` is never used as value so compiler elides this import assuming that it is either not necessary or it is used only to get types and keeping it in generated code is incorrect. If you are importing this module only for some module loading side-effect use import declaration without import clause:
```ts
import "highcharts-release";
```

**Comment by mhegazy** [comment]
@vladima i see the import used in a value position, see `this.chart = new Highcharts.Chart(chartOptions);`

@erfangc i can not get a repro for this locally. can you provide more details?

**Comment by vladima** [comment]
@mhegazy my bad, didn't notice that. I can confirm that I also cannot repro this locally

**Comment by erfangc** [comment]
I created a small test Repo to demonstrate 

```bash
git clone https://github.com/erfangc/ts-highcharts.git
```

you don't need `node` or `jspm` if  `tsc` is already globally installed

you can run `tsc` on `Demo.ts` and see the output is empty in `Demo.js`

**Comment by mhegazy** [comment]
imports are elided if they are not used in value position. your sample does not use `Highcharts` anywhere. either use it as a value somewhere, or to force import it (e.g. for side effects-only modules) use `import 'highcharts-release';`

**Comment by erfangc** [comment]
Actually, I think this is the cause - please let me know if I am correct:

If in the `.d.ts` file I write:
```ts
declare module 'highcharts-release' {
    export = HighchartsStatic;
}
```

then a `require` statement is *not* emitted

but If I write

```ts
declare var Highcharts:HighchartsStatic;
declare module 'highcharts-release' {
    export = Highcharts;
}
```

then the `require` is emitted because `Highcharts` is a `var` thus generates a value, whereas `HighchartsStatic` is just a interface.

Is that correct?

**Comment by erfangc** [comment]
@mhegazy thanks that make sense. But to elaborate on the response see my last post. 
Not only does a value from the import be used, a value must be *exported* instead of a interface. (see the latest version of the repo)

does it make sense to always emit a require statement if the `.d.ts` file uses the `export = ` syntax. In that case, the user is always importing a library written in `commonjs` and thus the require statement is always needed for the compiled code to work.

**Comment by mhegazy** [comment]
no. it does not depend on the declaration of the module `highcharts-release` at all. it only depeneds on the module importing it.

so in your `app.ts`:

```ts
import thisWillBeEmitted = require("highcharts-release");
import thisWillNot = require("highcharts-release");

console.log (thisWillBeEmitted.SomeValue); // the import is used in a value position, it will be emitted, as it is needed at runtime.

var a: thisWillNot.SomeType;  // the import is *only* used in a type position, it is not used in any code at runtime, it will not be emitted as it is not used.
```

if you want a module import to be emitted **all** the time, regardless of how it is used:

```ts
import "highcharts-release"; // always emitted.
```

**Comment by erfangc** [comment]
Thanks for that explanation I will certainly remember that going forward. 

On the other hand, in my code, I used `new Highcharts.Chart()`,  (`.Chart` is a property of an interface) and it still didn't work ... it worked after I changed the declaration file to export `Highcharts`, which is declared to be a `var`. 

In the case of forcing ```import "highcharts-released"```, how will the user assign it a local name to access the exported members?

You can experiment with this by `pulling` my test repo again, and just change one line in `highcharts.d.ts` from `export = HighchartsStatic` to `exports = Highcharts` and recompile.

**Comment by mhegazy** [comment]
> On the other hand, in my code, I used new Highcharts.Chart(), (.Chart is a property of an interface) and it still didn't work ... it worked after I changed the declaration file to export Highcharts, which is declared to be a var.

that is a  bug that needs to be fixed. can you provide a repro with using your import as you mentioned and not having it emitted. the above code results in the import emitted for me.

**Comment by erfangc** [comment]
the repository i provided should reproduce the issue, let me make a Gist as well to demostrate

**Comment by erfangc** [comment]
this does not emit: 
https://gist.github.com/erfangc/bc21c34af396e5d35a56

this does emit:
https://gist.github.com/erfangc/f9d525d6ff40cb7d2bee

**Comment by mhegazy** [comment]
The .d.ts file is irrelevant. can you share your source?

**Comment by erfangc** [comment]
sure

```ts
/// <reference path="typings/tsd.d.ts" />
import Highcharts = require('highcharts-release');

var element = document.getElementById("container");
var chartOptions: HighchartsOptions = {
	chart: {
		renderTo: element,
		type: "line"
	},
	title: {
		text: "This Highchart was Created from a TypeScript File!"
	},
	xAxis: {
		title: {
			text: "Days"
		},
		categories: ["Mon","Tues","Wed","Thurs","Fri"]
	},
	yAxis: {
		title: {
			text: "Amount of Awesomeness"
		}
	},
	series: [
		{
			name: "Stuff",
			data: [1, 5, 8, 1, 3]
		}
	],
	credits: {
		enabled: false
	},
	subtitle: {
		text: "Some Subtitle!"
	}
};

var chart = new Highcharts.Chart(chartOptions);
chart.addAxis({
	opposite: true,
	title: {
		text: "This is a secondary axis dynamically added!"
	}
});
```

**Comment by mhegazy** [comment]
OK. i have a repro now. thanks.

**Comment by erfangc** [comment]
no problem, thanks for your time!

**Comment by vladima** [comment]
this is by design.

let's start with scenario that works:

```ts
// highcharts.d.ts

declare var Highcharts: HighchartsStatic;

interface HighchartsChart {
    new (): any;
}

interface HighchartsStatic {
    Chart: HighchartsChart;
}

declare module 'highcharts-release' {
    export = Highcharts;
}
```

```ts
import Highcharts = require('highcharts-release');
var chart = new Highcharts.Chart();
```

In this case import `Highcharts` is a value of type `HighchartStatic` (because of `export = <variable>`) and it is preserved since it is used in value position in `new Highcharts.Chart`.

Now for the case that does not work.
```ts
highcharts.d.ts
declare var Highcharts: HighchartsStatic;

interface HighchartsChart {
    /**
     * This is the constructor for creating a new chart object.
     * @param  {HighchartsOptions} options The chart options
     * @return {HighchartsChartObject}
     */
    new (): any;
}


interface HighchartsStatic {
    Chart: HighchartsChart;
}

declare module 'highcharts-release' {
    export = HighchartsStatic;
}
```
this `.d.ts` file contains declaration of ambient module `highcharts-release` that is effectively an alias of type `HighchartsStatic` (because of `export = <interface>`) and global variable `Highcharts` of type `HighchartsStatic`. In the code `new Highcharts.Chart()` `Highcharts` is resolved not to the `import Highchart` (since import has only type meaning and new expression needs something with a value side) but rather to global variable `Highcharts`. As a consequence since import is not used anywhere it is elided by the compiler.

Having said that there is still a bug in language service - for quickinfo / goto definition we do not chase aliases an as a consequence attempt to do any of these operations on `Highcharts` identifier in expression `new Highcharts.Chart()` will use import as target which is wrong and misleading. I'll file a separate issue to track it.
