### ISSUE TITLE
Supporting build solutions (browserify, webpack, etc)

### ISSUE THREAD

**Issue by moostad** [Microsoft/TypeScript#6374]
There are a lot of package out there for supporting build solutions but all of them have their own problems (most common, error TS2304 for importing node packages or type checking) and there is no straightforward workflow. It would be great if you made an official support for this problems like what babeljs team does.

**Comment by mhegazy** [comment]
Can you elaborate on the tools you used, and the issues you ran into?

have you also looked at the samples available in https://github.com/Microsoft/TypeScriptSamples?

**Comment by moostad** [comment]
I'm using VSCode on Mac for editing, Node.Js for backend and React based app for frontend.
Basicly I want to TSX -> ES6 -> Babel -> ES5 for frontend which in my experience make smallest file size. so to make this happening there is 2 common workflow for build system:

1. using combination of gulp (htmls, styles) and browserify ( javascripts ) 
2. using webpack

webpack is looks faster to setup and run (for both build and debug) but loaders for typescript are not reliable for example:
https://github.com/denvned/webpack-typescript need to add ```/// <reference path="/typings/tsd.d.ts" />``` to every single file to work so I have to count how many ```../``` do I need on behind the typings in each file. however it's doing job done but will report  ```error TS2304 for importing 'package name'``` in console and I can't be sure that work or not  and even worse that make it hard to find real errors in middle of bunch of bug/fake error reports.
It's his statement about this issue https://github.com/denvned/webpack-typescript/issues/2

This was only one example, I tried so many of them and some are deprecated or work with old version of Typescript and I can't be sure they are reliable.

I believe this kind of problems should be handled with Typescript team and it is as much essential as TSD.
You are doing great but bable team represent it much better if you know what I mean.

![image](https://cloud.githubusercontent.com/assets/10362398/12217575/f147076c-b719-11e5-8037-6e84c2883a0d.png)

**Comment by jbrantly** [comment]
> but loaders for typescript are not reliable

@moostad Have you taken a look at [ts-loader](https://github.com/TypeStrong/ts-loader)? It's actively maintained and supports the advanced module resolution scenarios that webpack provides.

**Comment by mhegazy** [comment]
you can find build tool/packaging tool information at: https://github.com/Microsoft/TypeScript/wiki/Integrating-with-Build-Tools
