### ISSUE TITLE
export = {class expression} does not correctly export the type

### ISSUE THREAD

**Issue by taxilian** [microsoft/TypeScript#6377]
See this gist: https://gist.github.com/taxilian/0d23df3aee984cf9a937/f7eb774425ef3c7ba02543b5069ead5ee30da05a

``` typescript
// testService.ts broken
export = class testService {
    private someFlag = false;
    constructor() {
        console.log("Do something cool");
    }
};
```

``` typescript
// other.ts
import testService = require('./testService');

var a: testService;

var b = new testService();

var b: (typeof b);
```

The type is not correctly exported in this case and the displayed error is shown.

```
other.ts(3,8): error TS2304: Cannot find name 'testService'.
```

If I put `export = classname` at the bottom of the file it works correctly, as shown in this version: https://gist.github.com/taxilian/0d23df3aee984cf9a937

``` typescript
// testService.ts working
class testService {
    private someFlag = false;
    constructor() {
        console.log("Do something cool");
    }
}; export = testService;
```

`$ tsc --version
message TS6029: Version 1.7.5`

**Comment by mhegazy** [comment]
This behavior matches the intended design. `export =` only exports the value of the right hand side expression, the exception is `export = <identifier>` that exports all meanings of the identifier. 

the workaround as you mentioned is to make it a class declaration and export it.

That said, we should reconsider the case of class expression.

**Comment by RyanCavanaugh** [comment]
This works now
