### ISSUE TITLE
Cannot reference TSC v1.8 compilation

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6382]
I'm not sure but it looks like an error to me:

I don't seem to be able to reference a TypeScript file transpiled with TSC v1.8.

I have [set up a repository with a sample project and a description of the errors](https://github.com/SetTrend/TS18) I get when I try to reference the transpiled JavaScript type definition file:

![referenceerror](https://cloud.githubusercontent.com/assets/9283914/12157624/58f51e92-b4d3-11e5-83a0-037869b7f78d.png)

![importerror](https://cloud.githubusercontent.com/assets/9283914/12157627/5c9a2538-b4d3-11e5-9834-b70a52366d14.png)

**Comment by vladima** [comment]
`all.d.ts` is not an external module but just a `.d.ts` file that contains declarations for three ambient modules.
```ts
declare module "_Base" {
    export default class _Base {
        protected element: HTMLElement;
        private _var;
        constructor(element: HTMLElement);
    }
}
declare module "Derived" {
    import _Base from "_Base";
    export default class Derived extends _Base {
        constructor(element: HTMLElement);
    }
}
declare module "Manager" {
    import _Base from "_Base";
    export default class Manager {
        private _provider;
        constructor(provider: _Base);
    }
}
```

as a consequence:
- it cannot be imported as is since the file itself is not a module
- it can be referenced to bring these 3 modules into scope.

```ts
// main.ts

/// <reference path="../../output/headers/all.d.ts" />
import Derived from "Derived";
import Manager from "Manager";

const d: Derived = new Derived(null);
const m: Manager = new Manager(d);
```

**Comment by SetTrend** [comment]
Thanks for enlightening me! :cake: 

Yet, I'm surprised about the syntax. I've not seen this before:
```ts
import Derived from "Derived";
import Manager from "Manager";
```

Would you mind pointing me to where this is documented? I want to understand how this works.

**Comment by mhegazy** [comment]
you can find Module documentation at https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md

**Comment by SetTrend** [comment]
The suggested solution doesn't appear to work. It creates false `require()` statements in the JavaScript file:

![importerror](https://cloud.githubusercontent.com/assets/9283914/12215840/1d3aea52-b6cd-11e5-9e71-e374709b1974.png)

**Comment by mhegazy** [comment]
> The suggested solution doesn't appear to work. It creates false define() statements in the JavaScript file:

what does "false define()" mean? can you provide the expected output?
