### ISSUE TITLE
When will ES 2015 typing definitions be available on lib.d.ts

### ISSUE THREAD

**Issue by santiagohdzb** [Microsoft/TypeScript#6383]
Just wondering when are you guys updating the typing definitions. I'm missing the [property 'name'](http://www.ecma-international.org/ecma-262/6.0/#sec-function-instances-name) in [Function interface](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L229), just to name one.

**Comment by mhegazy** [comment]
it is already available in [lib.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts). this file is added automatically if `--target ES6`. you can also include this file directly in your project and get all the ES6 definitions.

**Comment by santiagohdzb** [comment]
great, thanks!

**Comment by mhegazy** [comment]
> BTW that one doesn't have the Function.name property yet :/

I see it defined https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L218

**Comment by santiagohdzb** [comment]
yeah you're right, I was looking at the other definition: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L1544

@mhegazy thanks a lot!
