### ISSUE TITLE
Adding Breakpoints to TypeScript file in Visual Studio

### ISSUE THREAD

**Issue by DavidBrower** [Microsoft/TypeScript#6385]
__Microsoft Visual Studio Enterprise 2015__
__Version 14.0.24720.00 Update 1__
__TypeScript   1.7.6.0__

We have a visual studio project with TypeScript which is correctly creating source maps. When I add a breakpoint (or ```debugger;```) to a TypeScript file and run the app with IE11 it opens up the transpiled JavaScript (although the editor tab says "```file_name.ts [dynamic]```)" at the same line number as the breakpoint in the original TypeScript file. 

As I step through the code the debug cursor repeatedly brings up the JavaScript file. However, I can switch back to the TypeScript and do a watch of the variables. However, whenever I step on I am then taken back to the JavaScript file. 

I've followed the instructions from this [answer](http://stackoverflow.com/questions/28834065/how-to-debug-typescript-in-visual-studio-2015-asp-net-5) to a question on StackOverflow. But it doesn't resolve the problem. 

![image](https://cloud.githubusercontent.com/assets/8066997/12167396/d1c8bbe4-b523-11e5-9c69-c4ba6ed48f00.png)

**Comment by wwwlicious** [comment]
+1

**Comment by mhegazy** [comment]
@sheetalkamat can you take a look.

**Comment by DavidBrower** [comment]
Any update on this, guys?

**Comment by sheetalkamat** [comment]
@DavidBrower is it possible to get the repro app. I tried debugging using TypeScript HTML app and it seems to be working fine for me. Having your repro can help me investigate this.

**Comment by mhegazy** [comment]
@DavidBrower please provide a repro project?

**Comment by mhegazy** [comment]
without a project to look at this is no actionable. closing for now. please reopen if more information is available.
