### ISSUE TITLE
Newest VS tools for typescript marked as trial in gallery

### ISSUE THREAD

**Issue by dziedrius** [Microsoft/TypeScript#6386]
For some reason, tools for VS2013 and VS2015 are marked as trial on gallery:
https://www.visualstudiogallery.msdn.microsoft.com/c7ba4ae7-e161-4e9d-a764-ada948e0e215
https://www.visualstudiogallery.msdn.microsoft.com/77b22d98-4345-41ef-a98f-ac25563b7ec5

Is there any reason for this, because our devops are feeling itchy seeing "trial" next to this :)

**Comment by mhegazy** [comment]
no reason. @yuit can we remove the tag?

**Comment by yuit** [comment]
@dziedrius Thanks for reporting this! I will get the tag removed. Sorry for confusion here
