### ISSUE TITLE
Allow structural reference-finding in the language service

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#6388]
Consider the following:

``` ts
interface A {
    a: string;
    b: number;
}

declare function f(x: A): void;

var v = { a: "hello", b: 10 };
f(v);
```

This code works because `{ a: string; b: number }` is structurally compatible with `A`.

Imagine that a user tries to rename `a` in either the interface or the object literal. Right now, renaming either one will cause an error, because the two are not considered the same property in their containing type. This leads to an unpleasant refactoring experience, because code actually stops working correctly.

We should consider fixing this by testing whether the containing type is structurally compatible.

This change should definitely affect:
- Finding references
- Finding rename locations
- Finding document highlight spans

**Comment by mhegazy** [comment]
The scope of this change is more than a bug fix. marking it as a suggestion. there is also a VS/Editor aspect here as there is a new UI/option to be provided to the user at rename time.

**Comment by DanielRosenwasser** [comment]
Note to implementors: a basic, but useful, useful test case would be

```ts
interface A {
    a: string;
}
function f(): Promise<A> {
    return Promise.resolve({
        a: '',
    });
}
```

taken from #6244.

**Comment by aleksey-bykov** [comment]
I think it should stay as it is now. `v` is of literal type that happened to be very similar to the interface, that's it, they are not related.

**Comment by aleksey-bykov** [comment]
Correct me if I am wrong, your latter example would work aout of the box, had TypeScript crave the type out of the context which it doesn't currently do. You would've killed many birds with a single shot if it did.

**Comment by DanielRosenwasser** [comment]
The proposal is an option to look for compatible types when performing a rename/search, so this wouldn't affect you if you didn't want it to.

It depends what you mean by "crave", because what it comes down to in our current algorithms is stepping through levels of type argument inference and contextual typing. If there's a solid and general idea about figuring that out, it'd be worth considering.

**Comment by RyanCavanaugh** [comment]
Closing due to lack of additional feedback
