### ISSUE TITLE
API Feature Request : AutoComplete - Base class methods show up

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#6390]
E.g. `componentDidMount` for a class that inherits from `React.Component`

```ts
class Foo extends React.Component<any, any>{
    com/*here*/
}
```

refs https://github.com/TypeStrong/atom-typescript/issues/809

**Comment by DanielRosenwasser** [comment]
I think this is partially related to #3377.

**Comment by mhegazy** [comment]
PRs are welcomed!

**Comment by mhegazy** [comment]
closing in favor of #7158
