### ISSUE TITLE
Unable to insert content to files in VS when 'module' is set to ES6

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6392]
Found by @malekpour on Gitter on [January 7, 2016 11:57 PM](https://gitter.im/Microsoft/TypeScript?at=568f41bc87cb99b53b87e0e6)

1. Create an empty file `foo.ts`
2. `tsc --init --module es6 foo.ts`
3. Open `foo.ts` in Visual Studio.
4. Try typing a key other than Enter, Tab, or Spacebar.

Expected: The corresponding character is entered into the buffer.
Actual: The buffer remains unchanged.

I'm not sure if this is related to the language service being blocked on module dependencies, but in this example, **there are no dependencies**.

**Comment by vladima** [comment]
this is not related to module resolution, issue is `ModuleKind` declaration on the managed side should exactly match its script side counterpart and was violated when `ModuleKind.ES6` was added

**Comment by vladima** [comment]
pinging @paulvanbrenk

**Comment by paulvanbrenk** [comment]
I have a fix checked in for 1.8

**Comment by malekpour** [comment]
@paulvanbrenk any idea about 1.8 release date?
Also noticed that `"module": "ES2015"` causes the same issue.

**Comment by paulvanbrenk** [comment]
Yes, I fixed that too. No concrete date for the 1.8 release.
