### ISSUE TITLE
signature overloading breaking change?

### ISSUE THREAD

**Issue by Artazor** [Microsoft/TypeScript#6397]
Looks like that in 1.7.5 overloading order became significant in some cases

1) specific first
```TypeScript
declare class A {
	f(x:string): any;
	f(x:{[key: string]: any}): A;
}

var a: A;
var x = a.f("A") + 1;  // OK in both TS 1.7.5 and TS 1.5.3
```

2) specific second
```TypeScript
declare class A {
	f(x:{[key: string]: any}): A;
	f(x:string): any;
}

var a: A;
var x = a.f("A") + 1; // Fails on TS 1.7.5 (Worked on 1.5.3). Inferred f result as A
```

Is it by design?

**Comment by ahejlsberg** [comment]
Yes, it is by design. Specifically, it is an effect of the change in #4074.

**Comment by RyanCavanaugh** [comment]
Overloading has always been order-sensitive -- the first signature that matches is the one that's selected.

Recommended fix would be to replace `[key: string]: any` with `[key: string]: {}`

**Comment by Artazor** [comment]
@ahejlsberg, @RyanCavanaugh - thank you for explanation
