### ISSUE TITLE
Proposal: set target to es6 by default for tsserver

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#6398]
Hello,

For now, you have to specify the target in tsconfig.json when you want to use es6 features in tsserver
It would be great to enable es6 by default only for tsserver, so there is no need for a tsconfig.json file.
We could downgrade by using tsconfig.json as usual.

Hope this could help others.

**Comment by mhegazy** [comment]
@dbaeumer, @egamma and @jrieken can you way in on this. Do you get similar feedback?

**Comment by egamma** [comment]
Node.js doesn't fully [support es6](https://nodejs.org/en/docs/es6/) yet. So setting the default to es6 might be confusing when doing node development. See this issue for an example Microsoft/vscode#1556.

**Comment by Alphapage** [comment]
OK I understand you want to align tsc and tsserver.
But browsers like ie 11, old firefox ... won't support all es6 features, so you will always stay to es5!
The current ECMAScript is es6, so I think it would be great to switch only tsserver to es6 (for vscode) and throw an error from tsc when compiling, telling that this feature is not yet supported (: to target es5 or to target es6 and to use another transpiler like babeljs to transpile to es5 for example) instead of showing the diagnostic error for unsupported generators...

This is another way and I think it will be a new step to es6.

**Comment by mhegazy** [comment]
for generators and async/await we would like to get them transpiled to ES5 by [2.0](https://github.com/Microsoft/TypeScript/wiki/Roadmap#20).
