### ISSUE TITLE
Help people who confuse `export = ` with `export default`

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript#6401]
We get questions like this all the time: http://stackoverflow.com/questions/34682541

The problem is that people think `export =` and `export default` are the same thing. The error message we issue is not at all helpful in diagnosing the problem, especially because we write the type of the module as `typeof "filename"`, which is completely opaque.

Suggestion: When a type comparison fails and the source type is an anonymous module type, see if the `default` property of the source type is assignable to the target type. If so, issue a more specialized error (e.g. "Did you mean to import the default object of the module?")

**Comment by mhegazy** [comment]
+1

**Comment by RyanCavanaugh** [comment]
We have very good docs now
