### ISSUE TITLE
Is creating a type definition difficult?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [Microsoft/TypeScript#6402]
I was doing this tutorial in order to learn Meteor + Angular 2 and I also found out about TypeScript: http://www.angular-meteor.com/tutorials/socially/angular2/

I noticed that there's no type definition for this API that I'm going to use: https://github.com/ethereum/web3.js

Is creating a type definition difficult? Could I do it myself, even though I don't know JavaScript? I'm only planning on learning TypeScript through that tutorial and I noticed that definitelytyped.org seems to have all the information that I need in order to create a type definition myself. Maybe the interfaces chapter from here could also help: http://www.typescriptlang.org/Handbook

Can I do it? Is it difficult? Btw, should I do a JavaScript tutorial first or will I know enough JavaScript by simply practicing, using Google when confused and maybe reading the TypeScript handbook fully?

**Comment by DanielRosenwasser** [comment]
@Laurentiu-Andronache it's not usually that difficult, but one of the bigger issues around declaration files is people writing them incorrectly. I'd personally suggest you get familiar with JavaScript and TypeScript just a bit more before you dive into writing a declaration file. Get a good understanding of how the type system represents various JS constructs.

On the other hand, if you test your definitions well as you write them, this might not be a problem, and that would be a great way to learn.
