### ISSUE TITLE
--emitDecoratorMetadata flag under ES6 target results in code that will not execute

### ISSUE THREAD

**Issue by meirgottlieb** [Microsoft/TypeScript#6404]
Given the file test.ts as follows:
```
"use strict";

class A {
    @Test
    b: B;
}

class B {

}

function Test(target: Object, propertyName: string): void {

}
```

If you compile this file using the command:
`tsc test.ts -t ES6 --experimentalDecorators --emitDecoratorMetadata`

and then run using `node test`, you get the following error:

```
ReferenceError: B is not defined
    at Object.<anonymous> (/Users/meir/Source/artifacthealth/hydrate/test.js:15:31)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

However, if you compile with:
`tsc test.ts -t ES6 --experimentalDecorators` 
or 
`tsc test.ts -t ES5 --experimentalDecorators --emitDecoratorMetadata` 
then the resulting JavaScript will execute fine.

I understand that moving the class declaration for B will fix the problem. However, the issue I'm raising is that the --emitDecoratorMetadata option breaks code that would otherwise work fine.

**Comment by mhegazy** [comment]
The core issue here is classes in JS have a different semantics than functions. Functions are hoisted to the top of the enclosing scope, so you can call a function before it is defined, where classes are not. so a class can not be used before it is defined. you can read more about this in https://github.com/Microsoft/TypeScript/issues/4521

Classes in ES6 has `let` semantics, i.e. they can not be used before they are declared. see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let for more details. this is why you are getting a `ReferenceError`.
in ES5, the class is transpiled as a `var`, and vars do not have this restrction.
