### ISSUE TITLE
Does not work suggestion and autocompletion with union types

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6405]
``` ts
function f(p: void | PropertyDescriptor) {
}
f({}); // does not suggest parameter object properties.
```

**Comment by DanielRosenwasser** [comment]
This actually tends to be a problem with overloads as well, because you'll often get resolved to the incorrect overload and get the incorrect contextual type.

**Comment by falsandtru** [comment]
thanks!

**Comment by DanielRosenwasser** [comment]
I think the ideal behavior would be to show the union of both members until there are any distinguishing elements. At that point, we could filter these down. Easiest thing would be to just always show the union.

**Comment by alxhub** [comment]
I run into this in overloads as well. This Playground example reproduces the problem: http://goo.gl/D5tYfG
