### ISSUE TITLE
Default typings have difference of the type checking credibility

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6407]
```ts
var as: ArrayLike<number | string> = <ArrayLike<string>>null;
var an: ArrayLike<number> = <ArrayLike<number | string>>as; // detect incompatibility

var ps: PromiseLike<number | string> = <PromiseLike<string>>null;
var pn: PromiseLike<number> = <PromiseLike<number | string>>ps; // cannot detect
```

We must add the following additional definition to detect the incompatibility of `PromiseLike`, like a `ArrayLike`.

```ts
interface PromiseLike<T> {
    _?: T;
}
```

```ts
interface PromiseLike<T> {
    _?: T;
}
var ps: PromiseLike<number | string> = <PromiseLike<string>>null;
var pn: PromiseLike<number> = <PromiseLike<number | string>>ps; // detect incompatibility
```

This behavior is the spec, but this incompleteness is unfavorable.

**Comment by mhegazy** [comment]
it is a structural typesystem. the definition of PromiseLike does not manifest the type parameter in any way that makes the comparison fails. i do not think there is much we can do unless we add some sort of tagging/nominal support (https://github.com/Microsoft/TypeScript/issues/202)
