### ISSUE TITLE
window.open return type

### ISSUE THREAD

**Issue by JirkaDellOro** [Microsoft/TypeScript#6418]
In the lib.d.ts I found, that the return type of the window.open method is declared as any. Shouldn't it be Window?

**Comment by RyanCavanaugh** [comment]
@zhengbli can you confirm?

**Comment by zhengbli** [comment]
The reason it is `any` now is that technically it returns a `WindowProxy` object, for which the spec does have a definition. 
However according to the [spec](http://www.w3.org/TR/2009/WD-html5-20090423/browsers.html#windowproxy):
> As mentioned earlier, each browsing context has a WindowProxy object. This object is unusual in that it must proxy all operations to the Window object of the browsing context's active document. It is thus indistinguishable from that Window object in every way, except that it is not equal to it.

So it might be ok to use `window` instead in `lib.d.ts`
