### ISSUE TITLE
A way to separate type annotations from implementation.

### ISSUE THREAD

**Issue by Lenne231** [Microsoft/TypeScript#6421]
It would be nice if we could separate the type annotations from the implementation. This would make the code much more cleaner and we could write plain JavaScript in many cases. 

Instead of

```typescript
type MyFunction = (props : { title: string }) => { tag: string, children: any[] };

let myFunction : MyFunction = ({ title }) => ({ 
    tag: 'div', 
    children: [title] 
});
```
this should work as well:

```typescript
type myFunction = (props : { title: string }) => { tag: string, children: any[] };

let myFunction = ({ title }) => ({ 
    tag: 'div', 
    children: [title] 
});
```

**Comment by falsandtru** [comment]
In this case, you should use `declare let` instead of `type`. `var/let/const` and `type` have different namespace for declarations and typings.

See https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Declaration%20Merging.md#basic-concepts

```ts
declare let myFunction: (props : { title: string }) => { tag: string, children: any[] };

myFunction = ({ title }) => ({ 
    tag: 'div', 
    children: [title] 
});
```

**Comment by Lenne231** [comment]
@falsandtru This compiles but does not generate valid JavaScript, "let" is missing.

**Comment by falsandtru** [comment]
Sorry, fix it to:

```ts
let myFunction: (props : { title: string }) => { tag: string, children: any[] };

myFunction = ({ title }) => ({ 
    tag: 'div', 
    children: [title] 
});
```

emit:

```js
var myFunction;
myFunction = function (_a) {
    var title = _a.title;
    return ({
        tag: 'div',
        children: [title]
    });
};
```

**Comment by Lenne231** [comment]
@falsandtru This does not keep the type annotations and implementation separated.

**Comment by mhegazy** [comment]
can you elaborate on how this is useful?

**Comment by Lenne231** [comment]
There doesn't seem to be a simple way to do this.
