### ISSUE TITLE
Example code for intermixing namespaces an exports?

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/TypeScript#6422]
Just for the sake of spreading knowledge:

What are valid combinations/permutations of `namespace`, `module` and `export`?

For instance: I don't seem to be able to export something from within a namespace.

I apprehend it's discouraged to do so. Yet my question is solely aiming at getting a comprehensive declaration of the TypeScript language syntax of how the above three keyboards can be intermingled in flat code, modules and ambient modules.

**Comment by mhegazy** [comment]
You can find more information about `module`, `import` and `export` at: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md
and you can find more information about `namespace` at: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Namespaces.md

Give these pages a look and let us know if you still have unanswered questions.

**Comment by SetTrend** [comment]
Nope. If that was the case than I wouldn't have asked. Can you get clear on the passages answering above questions?

You are closing issues to quickly for my liking. Please re-open.

**Comment by mhegazy** [comment]
Can you be more specific?

**Comment by mhegazy** [comment]
and in general, StackOverFlow / gitter chat room would be a good place for questions. this repo should be for compiler/language issues.

**Comment by SetTrend** [comment]
Yes, I agree with you. Yet I didn't *ever* get any (satisfying) TypeScript related answers on StackOverflow yet. And I can't have Gitter on all the time. It's hard to find answers there if you come back a day later. [(Waiting for Gitter proposal to get implemented)](/gitterHQ/gitter/issues/1008).

I believe that the `namespace` page is new to me, though. Please let me have a short revisit and I'll close right afterwards.
