### ISSUE TITLE
Suggestion: Custom class extend methods

### ISSUE THREAD

**Issue by aguzubiaga** [Microsoft/TypeScript#6425]
It would be great if a class could have a method to handle inheritance when another class extends it, like `self.inherited` in Ruby. 

I think it could be helpful for example if I want to keep track of inherited classes, setup something static, or enable static getter/setter inheritance by using `Object.getOwnPropertyDescriptor` / `Object.defineProperty`. 

I know I can implement my custom `__extends` function, but that will only work in the file the class is, would affect every class in the file and wont work if I import the class and extend it somewhere else. 

```ts
class MyClass {
  static extend(subclass) {
    // do something with subclass
  }
} 
```

It can be easily implemented by just adding a check for `b.extend` and a call in the `__extends` function:
```js
var __extends = (this && this.__extends) || function (d, b) {
    if (b.extend) return b.extend(d); // <==
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
```

I would be happy to send a PR if this is accepted.

**Comment by aguzubiaga** [comment]
Maybe naming it `extend` can lead to unexpected calls to methods already defined with that name, is there a chance to use Symbols? Similar to `Symbol.iterator`

**Comment by mhegazy** [comment]
this would be outside the scope of typescript. the `__extend` function is designed to be extensible/replaceable. so your solution of definition a new `__extends` should work just fine.

**Comment by aguzubiaga** [comment]
Ok, but how I replace the "__extends" function of my API users?

**Comment by mhegazy** [comment]
you can use `--noEmitHelpers` to avoid emitting the helper all together, since you are overriding it.

**Comment by aguzubiaga** [comment]
Ok, great. Thanks!
