### ISSUE TITLE
Incorrect narrowing of unions

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6430]
```typescript
class A {
}
class B {
}
function isAOrB(x: any): x is A | B {
	return true;
}

let ab: A | B;

if (isAOrB(ab)) {
	ab; // of type A only
}
```

**Comment by kitsonk** [comment]
I think it is because `class A` and `class B` are the same structural type.  This works as expected:

```typescript
class A {
	a: any;
}
class B {
	b: any;
}
function isAOrB(x: any): x is A | B {
    return true;
}

let ab: A | B;

if (isAOrB(ab)) {
    ab; // of type A | B
}
```

And so technically, the first case works as designed.

**Comment by tinganho** [comment]
I think they should narrow based on "symbolic type" behaviour.

Here is my original example. And the types are not structural the same:
```typescript
interface ModelData {
    id: string;

    [prop: string]: any;
}

export abstract class Model<T> {
}

function isArrayOfModels(x: any): x is ModelData[] | Model<any>[] {
    return x instanceof Array;
}

let m: Model<any> | Model<any>[] | ModelData | ModelData[];

if (isArrayOfModels(m)) {
	m;
}
```

**Comment by ahejlsberg** [comment]
Your `Model<T>` class never uses `T` and is effectively equivalent to `{}`. For this reason, `Model<any>` is a supertype of `ModelData`, so `ModelData[] | Model<any>[]` gets reduced to just `Model<any>[]`.

There's a discussion of support for nominal typing in #202.

**Comment by tinganho** [comment]
Thanks @ahejlsberg . In my real usecase, the abstract class `Model` has many properties and one of them was the `id` property, which made it a supertype of `ModelData`. Though it wasn't so clear `Model` was a supertype of `ModelData`. Just pure coincidence.
