### ISSUE TITLE
Naming arrow functions

### ISSUE THREAD

**Issue by jscriptcoder** [microsoft/TypeScript#6433]
Hi there,

Not sure whether this has been already mentioned before (I would be surpirsed if it never was)... Wouldn't it be a good idea to name arrow functions, which is what apparently ES6 does?. Think about the benefits of this in the stacktrace. It's quite useful to have a "named" function in there, instead of an anonymous one ;-)

So, this:

``` javascript
const double = x => x * 2;
```

would be transpiled down to:

``` javascript
var double = function double(x) {
  return x * 2;
};
```

Just to mention that Babel does it like that ;-)

Thanks.

**Comment by adidahiya** [comment]
This would also be nice to have for arrow functions used as class methods/properties. 

```ts
private handleDocumentClick = (...) => {
    ...
}
```

**Comment by RyanCavanaugh** [comment]
> Wouldn't it be a good idea to name arrow functions, **which is what apparently ES6 does**?

Can you clarify this part?

**Comment by RyanCavanaugh** [comment]
> This would also be nice to have for arrow functions used as class methods/properties.

Note that we can't safely name class methods -- a reference to `handleDocumentClick` in the method body must refer to whatever that name means in the enclosing lexical scope is, not the function.

**Comment by RyanCavanaugh** [comment]
Consulted with @bterlson and we think this is a spec-affecting behavior, specifically the places where the abstract `SetFunctionName` operation is invoked https://tc39.github.io/ecma262/#sec-setfunctionname 

Regular function expressions have very noncomplaint behavior in current runtimes and should probably just be left alone (specifically, Edge, Chrome, and Node all produce an own property of `name` on functions, when they shouldn't)

**Comment by jscriptcoder** [comment]
Hi @RyanCavanaugh, answering your question... as far as I know in ES6 if an arrow function is defined on the right-hand-side of an assignment expression, the ‎engine will take the name on the left-hand-side and set the arrow function's ".name" based on that

Thanks

**Comment by nojvek** [comment]
Hi @RyanCavanaugh, could you explain the SetFunctionName operation? I couldn't fully grasp why it should be an issue.

I tried this in chrome.

```
let l = {log(){}}
console.log(l.log.name) //outputs 'log'
```
Generated typescript:
```
var l = { log: function () { } };
l.log.name // empty
```

So it seems under the covers v8 does to nice named anonymous functions.

**Comment by basarat** [comment]
Tried the following in the chrome dev console. Was surprised :rose: 

```ts
let foo = function(){}
foo.name; // "foo"
```

![image](https://cloud.githubusercontent.com/assets/874898/15493635/a83d78ca-21c8-11e6-90e5-e389a169c0cc.png)

**Comment by dsherret** [comment]
@basarat It didn't happen to me in v50.0.2661.102m, but I just upgraded to v51.0.2704.63m and now it's doing that.

**Comment by mhegazy** [comment]
PRs welcomed

**Comment by Podlas29** [comment]
I will attempt to make a PR in following days or weeks, depending on how difficult it turns out to be. ;)

**Comment by Podlas29** [comment]
@mhegazy For clarification - should PR for this issue fix all naming issues according to ES6 spec (naming arrow function object properties etc...), or only this one case of `const x = () => {}`?

**Comment by mhegazy** [comment]
I would say all lambdas/function expressions should behave as such. feel free to send us incomplete PRs if you want to get early feedback. please tag @rbuckton on your PRs.

**Comment by sebinsua** [comment]
See also: #6757.

I notice the PR hasn't been merged, is anybody working on this?

**Comment by mpodlasin** [comment]
I worked on it for some time but I am currently not.

**Comment by bresleveloper** [comment]
using TypeScript 2.3.3, issue hasn't been solved, [#6757](https://github.com/Microsoft/TypeScript/issues/6757) is a dup.

**Comment by christianalfoni** [comment]
@mpodlasin Would you have some pointers on where to start with this issue? I would love to fix it as the name of functions are valuable when building devtools.

**Comment by mpodlasin** [comment]
No, my approach was not good as you will see in review of my PR: https://github.com/Microsoft/TypeScript/pull/16001

I did not work on it after that.

Good luck!

**Comment by trotyl** [comment]
For symbols the function name would be wrapped in brackets:

```javascript
const sym = Symbol('SYMBOL_NAME')
const obj = { [sym]: () => 42 }
console.log(obj[sym].name) // [SYMBOL_NAME]
```

As long as arrow function as property being respected, it may need adding runtime helpers to properly setting the name per spec.

**Comment by sabrehagen** [comment]
My issue #33408 was marked as a duplicate and closed. I have a working repro here where native JavaScript vs JavaScript compiled from TypeScript produces different functionality:

```
git clone https://github.com/sabrehagen/tsc-function-repro
yarn --cwd tsc-function-repro test
```

**Comment by sabrehagen** [comment]
Can we get an ETA on the resolution of this bug? There have been at least 6 github issues created since January 2016 regarding it, and it's still unresolved. Would be great to get some clarity on likelihood of resolution as our production code is affected by this functional inconsistency.

**Comment by jscriptcoder** [comment]
I cannot believe this is still happening after I reported this issue almost 4 years ago. Maybe we need a reminder:

**Typescript** today:
<img width="1214" alt="Screenshot 2019-09-24 at 11 07 54" src="https://user-images.githubusercontent.com/613724/65498148-ac270600-debb-11e9-9172-b5ec119b6eac.png">

**Babel**, at least 4 years ago:
<img width="1160" alt="Screenshot 2019-09-24 at 11 07 36" src="https://user-images.githubusercontent.com/613724/65498177-b6490480-debb-11e9-9313-9bcf723e600e.png">

**Chrome** since arrow functions were introduced:
![Screenshot 2019-09-24 at 11 11 52](https://user-images.githubusercontent.com/613724/65498539-60289100-debc-11e9-955f-18f1ec6c3b5f.png)

**Comment by RyanCavanaugh** [comment]
In case it isn't clear, anyone's free to send a PR when an issue is in the Backlog milestone.

**Comment by BrendanBall** [comment]
So I'm using typescript 3.6 with node v12.10.0 and targeting es2018.
this works:
```
const foo = () => ({ foo: 'foo' })
export { foo }
console.log(foo.name)
```
This doesn't:
```
export const foo = () => ({ foo: 'foo' })
console.log(foo.name)
```
directly exporting a const changes the name behaviour

**Comment by nojvek** [comment]
@BrendanBall if you’re targeting es2018 then TS may not even be transpiling and letting node handle the arrow function. 

This is really about how TS down transpiles arrow functions. 

If I am correct this fix would be in the emit stage. Arrow functions need to know if they are assigned to a const. If so, emit with the name of the const

**Comment by BrendanBall** [comment]
@nojvek You are correct that TS isn't transpiling the arrow function, however it's still the TS transpilation that breaks the naming for me and the end result is the same, my arrow functions aren't named when they should be. Shall I open a separate issue for this? In my case it's breaking because of how `export const` is being transpiled to commonjs.

**Comment by OfficerHalf** [comment]
![image](https://user-images.githubusercontent.com/4851889/71209155-5b336d80-2270-11ea-802b-834d9c3a7b49.png)

This is the main reason that this change would be useful to me, since this is my React devtools at the moment, at least without manually setting `.displayname`.

**Comment by dragomirtitian** [comment]
@OfficerHalf doesn't react use babel for compilation anyway? So what TS transpilation  looks like should not really matter.. 

@DanielRosenwasser In order to fix this babel mangles the variable names beyond recognition ([ex](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAHg3AUFCBeCYCmBjArmAzgS2DWQD4IBvOCaifAMwgAoBCdbPQtASkpr9TQAXHADtojQWCzd4fAL5UaaADa5ivftXTCwYgIyyaChaEgBPZNHgJLjLqQqKtQ0eK6HqiFHYcbN21yg7Dwg5eDC4GxQ2HAIiXydaBhYYjiIeRL4A3XFJaXdEhT4VNUdNZx19EONIjAB7EVw65TQAOmU6gHNGM0Y6EFVudyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-1%2Cstage-2%2Cstage-3&prettier=true&targets=&version=7.7.7&externalPlugins=)).

Wouldn't a partial fix here for functions that do not reference themselves in the body be good enough ? Adding a name to those will not cause (*) any shadowing issues and it will cover most common scenarios while not mangling the output.

On the other hand this solution will require an extra pass over all arrow function to determine if they do reference themselves, which may impact performance so it might just make sense to label this as will not fix and closing it 🤷‍♀️  

_(*) as far as I can tell_

**Comment by OfficerHalf** [comment]
Sure, if you use CRA it uses babel. But you don't have to - if you use `"jsx": "react"` in your tsconfig, typescript will handle that part of the compilation. In this particular project we don't use babel.

**Comment by RyanCavanaugh** [comment]
I'm inclined to agree with @dragomirtitian that we should just Won't Fix this due to the rapidly-evaporating ecosystem of ES5-only runtimes. The actual impact here is quite minimal compared to the sheer ugliness of the required emit.

**Comment by ljharb** [comment]
IE 11 isn’t vanishing particularly rapidly.

**Comment by OfficerHalf** [comment]
Agreed - over 50% of traffic I see in my particular industry comes from IE11. We can't deprecate it yet since some customers are unable to upgrade even if they wanted to.

**Comment by DanielRosenwasser** [comment]
Would it be acceptable if the names were set to something "sufficiently close" to the original name? The point in that being that it would make debugging easier even if it's not the correct behavior. So in

```ts
const foo = () => {
}
```

we would rewrite that to

```ts
var foo = function foo_1() {
}
```

**Comment by ljharb** [comment]
while that's certainly better than outputting no name at all, or a mangled name, that seems like a short-term workaround pending an actual fix.

**Comment by basarat** [comment]
Why would A be easier than the desired B?

* A (proposed workaround)
```ts
var foo = function foo_1() {
}
```
* B (desired)
```ts
var foo = function foo() {
}
```

**Comment by dragomirtitian** [comment]
@basarat Picking a name that does not conflict with anything else would remove the need to rewrite variable names if the body of the function references the the variable. 

Ex:
```
var x;
x = recursive => {
    console.log("original x")
    return x(true); // The function assigned to x below is actually called
}
var y = x;
x = function () {
  console.log("new x")
}
y(true)
```
If you give the first function the name `x`, then the body of the function will see the function itself as `x` not the variable `x` (which is reassigned later) which will make the behavior different to the original code in ES2015 and above.

So you end up having to do a lot of variable name rewrites, which get pretty ugly pretty fast: [ex](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=G4QwTgBAHg3AUFCBeCYCmBjArmAzgS2DWQD4IBvOCaifAMwgAoBCdbPQtASkpr9TQAXHADtojQWCzd4fAL5UaaADa5ivftXTCwYgIyyaChaEgBPZNHgJLjLqQqKtQ0eK6HqiFHYcbN21yg7Dwg5eDC4GxQ2HAIiXydaBhYYjiIeRL4A3XFJaXdEhT4VNUdNZx19EONIjAB7EVw65TQAOmU6gHNGM0Y6EFVudyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-1%2Cstage-2%2Cstage-3&prettier=true&targets=&version=7.7.7&externalPlugins=)

**Comment by ljharb** [comment]
Variable names aren’t observable, however, while function names are.

**Comment by remorses** [comment]
Can someone implement this please?

**Comment by ljharb** [comment]
When it was standardized isn't important; it was present in every version of every web browser except IE, and it's web reality that code expects it to work. It's also polyfillable in IE 9+, with https://npmjs.com/function.prototype.name, and there's lots of websites that rely on that working, including airbnb.com.

**Comment by DanielRosenwasser** [comment]
Every product will have a set of tradeoffs it has to make, and prioritizing the work to do this "by the book" is work with a likely tail of bugs and emit size implications. I can't speak for others who are on this issue, but I tend to agree with Ron that the people who would benefit from this have shrunk a lot as a group. For example:

> there's lots of websites that rely on that working, including airbnb.com (when i last checked, at least).

Windows 10 (released late July 2015) actually makes it hard to access IE11. In fact, it will automatically punt you to Edge unless you disable a setting within Edge. But for the sake of it, here's Airbnb running in IE11:

https://user-images.githubusercontent.com/972891/136441070-7c308981-183b-43e1-8b91-4fa7306f3275.mp4

**Comment by sandersn** [comment]
This is not practical to fix: the costs far outweigh the benefits.

**Comment by ljharb** [comment]
@sandersn even behind an option?
