### ISSUE TITLE
Proposal: Real private member for a class using a WeakMap or Map object

### ISSUE THREAD

**Issue by Thomas-P** [Microsoft/TypeScript#6437]
# 
## Problem
If I use the private modifier of a class, this would not create a real private member of a class. So I lose the control of reading and writing on this member, because everyone who use the code in javascript are able to read/wirte the member directly. 
I am aware that this is due to the desing of Javascript, but I think, we could handle this by using a WeakMap or Map object  for private members on a class object. 
## Concept
Instead of using the context of the class object for a member which is declared as private, we pass the private object by using. In every method where private members are used, we call the WeakMap object in the first line. the compiler knows which member are private, so he is able the change the **this** context into **weakmap** context.

For legacy support it would be possible to use Map or an hash object, but here we lose the garbage collector functionallity. Instead I would prefer a flag, which gives the functionallity with a real weakmap and the transpile into ES6 would be done by another tool.
### TypeScript
This is a typescript snipplet, for demonstration
```TypeScript
class Test {
	private _x:number;
	constructor(private _y:number) {
		this._x = 42;
	}
	
	get x():number {
		return this._x;
	}
	
	get y():number {
		return this._y;
	}
}

var test = new Test(23);
```
### actual convertion
```JavaScript
var Test = (function () {
    function Test(_y) {
        this._y = _y;
        this._x = 42;
    }
    Object.defineProperty(Test.prototype, "x", {
        get: function () {
            return this._x;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(Test.prototype, "y", {
        get: function () {
            return this._y;
        },
        enumerable: true,
        configurable: true
    });
    return Test;
})();
var test = new Test(23);
```
### with WeakMap
```JavaScript
var Test = (function () {
    var privatesMember = new WeakMap();

    function Test(_y) {
        var privateObject = {};
        privatesMember.set(this, privateObject);

        privateObject._y = _y;
        privateObject._x = 42;
    }
    Object.defineProperty(Test.prototype, "x", {
        get: function () {
            var privateObject = privatesMember.get(this);
            return privatesMember.get(this) && privatesMember.get(this)._x;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(Test.prototype, "y", {
        get: function () {
            var privateObject = privatesMember.get(this);
            return privatesMember.get(this) && privatesMember.get(this)._y;
        },
        enumerable: true,
        configurable: true
    });

    return Test;
})();
var test = new Test(23);
```

**Comment by aguzubiaga** [comment]
I think you mean:
```ts
    Object.defineProperty(Test.prototype, "y", {
        get: function () {
            var privateObject = privatesMember.get(this);
            return privateObject.get(this) && privateObject.get(this)._y;
        },
        enumerable: true,
        configurable: true
    });
```

Instead of:
```ts
    Object.defineProperty(Test.prototype, "y", {
        get: function () {
            var privateObject = privatesMember.get(this);
            return privatesMember.get(this) && privatesMember.get(this)._y;
        },
        enumerable: true,
        configurable: true
    });
```

I like the idea and the use of WeakMap to take adventage of garbage collection, but wouldn't this be a significant breaking change?

**Comment by kitsonk** [comment]
Also, it seems a bit illogical to down emit `class` to ES5 with something that doesn't exist in ES5... Right?

**Comment by RyanCavanaugh** [comment]
As usual I have to question this assumption

 > because everyone who use the code in javascript are able to read/wirte the member directly. 

Why is this a problem that is effectively solved with the amount of code you're proposing?

If you're concerned about *accidental* mutation of private members, there's just as much of a problem with accidental mutation of public members. And control over enumerability seems like a more tractable solution in general for other code mistakenly messing with your class's members.

If you're concerned about *malicious* mutation of private members... that is not a game you can reasonably win. For example, in the proposed codegen, someone could overwrite the global symbol `WeakMap` with a malicious implementation that intercepted the values.

**Comment by Thomas-P** [comment]
Thats right, for es5. Therefore you had to use a shim, but the idea of supporting real private members, by setting them into a WeakMap or a Map should also work with objects created from a class. 

The idea of private members is that you have control over it. And while typescript already knows where a private member is used in the implementation, it should be able to choose the reference from the map, instead of the own reference.

**Comment by Thomas-P** [comment]
@RyanCavanaugh I know that it is possible to mutate the states, it is just an idea for handling good designed class interfaces. By writing interfaces you want that others use the documented way and not doing creepy things with the infrastructure behind. It is  just an idea.

**Comment by kitsonk** [comment]
> Thats right, for es5. Therefore you had to use a shim, but the idea of supporting real private members, by setting them into a WeakMap or a Map should also work with objects created from a class.

So you want to impose a runtime overhead on everyone?  How do you suggest that you ensure everyone what the shim loaded at runtime?

The emit when targeting ES6 is:

```js
class Test {
    constructor(_y) {
        this._y = _y;
        this._x = 42;
    }
    get x() {
        return this._x;
    }
    get y() {
        return this._y;
    }
}
const test = new Test(23);
```

How would you suggest this changing?

**Comment by RyanCavanaugh** [comment]
I've had this discussion in a lot of places since we launched. I still don't understand the *problem* that is being solved.

It's like complaining that the lock on my front door is susceptible to lockpicking -- the fact that the door is locked is enough to keep honest people out, and the door is susceptible to a sledgehammer regardless of the design of the lock. There isn't any obvious gain in overcomplicating the lock mechanism because it doesn't change the fundamental situation in any meaningful way.

**Comment by SamuelEnglard** [comment]
As someone who suggested a way to have "true" private members in the past and was successfully convinced it was pointless by @RyanCavanaugh, I think the idea is pretty cool...but functionally pointless.

Think of C#, massively popular language that has "true" private members... yeah not. I can't keep track of the number of times I've broken that using Reflection and Reflection.Emit.

The idea of Private is to say "I don't think you should use this" more than it is to jump through hoops so its really really complex and hard to use.

**Comment by Pajn** [comment]
You got symbols which you can keep private if you want something that's truly private

**Comment by Thomas-P** [comment]
Okay, I think I understand what you mean.I thought that if I declare something to private that it could be hidable from the interface. We don't have really privates in Javascript, so the way to do it is to encapsulate it in a closure. And it the only fact i wish this, is to have a clean interface. I think, I should persuade the others to use typescript instead of javascript. 

@kitsonk The Sample then looks like this.
```Javascript
var Test = (function() {
    'use strict';
    var privateStore = new WeakMap();

    class Test {
        constructor(_y) {
            let privateObject = {};
            privateStore.set(this,privateObject);
            privateObject._y = _y;
            privateObject._x = 42;
        }

        get x() {
            let privateObject = privateStore.get(this);
            return privateObject._x;
        }

        get y() {
            let privateObject = privateStore.get(this);
            return privateObject._y;
        }
    }

    return Test;
})();

const test = new Test(23);
```

**Comment by kitsonk** [comment]
@Thomas-P I guess I still do not understand why you want to impose run-time overhead on others.

In particular this runs afoul of one of the TypeScript design goals:

> 3. Impose no runtime overhead on emitted programs.

Also, the "what about ES5" and ensuring that some sort of polyfill is loaded is addressed.  Specifically TypeScript has avoided any sort of emits that require additional polyfills to be loaded.

Why does this feature justify breaking these rules?

There is nothing preventing you from hiding your variables yourself in the fashion you are suggesting.  I often use WeakMaps for managing data on classes that I don't want exposed to others.  Also, as @Pajn points out, if you are targeting ES6, you could use a symbol to store your privates that no one would see:

```typescript
const privates = Symbol('privates');

class Test {

    constructor(y: number) {
        this[privates] = {};
        this[privates].x = 42;
        this[privates].y = y;
    }

    get x():number {
        return this[privates].x;
    }

    get y():number {
        return this[privates].y;
    }
}

const test = new Test(23);
```

**Comment by Thomas-P** [comment]
Ok, thanks for the clarification. I'll close this issue.
