### ISSUE TITLE
Three minor formatting issues in the Markdown specification grammar

### ISSUE THREAD

**Issue by lucaswerkmeister** [microsoft/TypeScript#6439]
I found three minor formatting problems in the Markdown spec’s grammar (both in the main text and in the appendix), which make it unnecessarily inconvenient to use the grammar programmatically:
- In _ClassExtendsClause_, there is an extra space before _ClassType_.
- In _EnumMember_, the equals sign is not surrounded by backticks.
- _NamespaceElement_’s last four right-hand sides are surrounded by a single pair of `*`s instead of one pair per right-hand side.

In the Markdown document, these can be fixed by applying the following patch: https://gist.github.com/lucaswerkmeister/be5d347c1fa033d997ad

However, the problems also seem to be present in the `.docx` version, so you’ll probably want to fix them there.

**Comment by mhegazy** [comment]
@lucaswerkmeister, the sepc is created from the word doc in `doc\TypeScript Language Specification.docx` and running `jake generate-spec`. PRs are welcomed.

**Comment by lucaswerkmeister** [comment]
Well, I don’t have Microsoft Office, and I don’t know what LibreOffice will do with the document – and `doc/README.md` seemed to suggest that you’d prefer to edit the docx document yourselves anyways. But sure, I can submit a PR and we’ll see how it goes.

**Comment by lucaswerkmeister** [comment]
Hm, doesn’t look like anything’s happening – it prints a `cscript` command and then exits. Is this a Windows-only build?

**Comment by mhegazy** [comment]
i believe it needs the MS Word API. never mind then, I, or some one with MS Office can do it.

**Comment by lucaswerkmeister** [comment]
That’s probably better, thanks. I could give you my docx (in fact, why not: 919bae1fef314bee40f601fa5b42e74ffc85bc31), but given that LibO managed to shrink the file by about 35%, it’s probably useless to you.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
