### ISSUE TITLE
export default class compile error

### ISSUE THREAD

**Issue by welefen** [Microsoft/TypeScript#6450]
```ts
export default class {
  
}
```

compiled code is:

```js
class {
}
exports. = default_1;

```

compile command is `tsc --module commonjs --target ES6 default.ts`, TypeScript version is 1.7.5

**Comment by welefen** [comment]
when set --target ES5, it's correct

**Comment by vladima** [comment]
duplicate of #5844, should be fixed in master. Can you give a try to `typescript@next` on npm to see if it resolves the problem?

**Comment by mhegazy** [comment]
should be fixed in latest.
