### ISSUE TITLE
Use original import alias with generated code

### ISSUE THREAD

**Issue by techird** [Microsoft/TypeScript#6454]
For the typescript below

```tsx
import { Person } from './person';
let person = new Person();
```

will be generated as (use CMD)

```js
var Person_1 = require('./person');
var person = new Person_1.Person();
```

In this case, when debug the code with sourcemap, the browser can not provide `Person` information on hover. 

For debugging convinient, I suggest the generated code looks like below.

```js
var Person_1 = require('./person');
var Person = Person_1.Person;
var person = new Person();
```

I have no idea if this is more reasonable, if not, anyone tell me the points?

**Comment by mhegazy** [comment]
That does not match the expected ES6 semantics.. the ES6 module semantics allows for importing modules to observe changes to exported properties. (see example [here](https://github.com/ModuleLoader/es6-module-loader/wiki/Circular-References-&-Bindings))

**Comment by techird** [comment]
@mhegazy Thank's for the explain.
