### ISSUE TITLE
New Website Logo: OutSystems

### ISSUE THREAD

**Issue by mmv** [Microsoft/TypeScript#6455]
- Name: OutSystems
- Homepage url: https://www.outsystems.com/
- Brand Guidelines/Licensing: none
- Logo: http://downloads.outsystems.com/Resources/Image/OutSystems_sticker.svg

We've been using TypeScript ever since 0.8 came out, adding sanity to our JS development process and making use of the type information to generate strongly typed proxies bridging JS and other execution environments.

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
