### ISSUE TITLE
Autocomplete IntelliSense only showing options for first options overload, missing the rest

### ISSUE THREAD

**Issue by Zlatkovsky** [microsoft/TypeScript#646]
Suppose I create a function that can take multiple overload types.  For example:

``` typescript
function getElement(reference: { name: string });
function getElement(reference: { index: number });
function getElement(reference: { id: string });
function getElement(reference: any) {
    // do something with reference
}
```

When I go to use the function, IntelliSense correctly shows me that there are three possible overloads:

> ![getelement1](https://cloud.githubusercontent.com/assets/2230453/4222906/7f821e54-3917-11e4-970a-d5f3e636349f.png)
> ![getelement2](https://cloud.githubusercontent.com/assets/2230453/4222909/826edd3c-3917-11e4-8b51-85f87bc77947.png) 
> Etc.

However, when I type a curly bracket and then press ctrl-space to get the autocomplete list, it only shows me the first type (“name”), and not any of the other overloads (“index” and “id”)

> ![getelementoptionsmissing](https://cloud.githubusercontent.com/assets/2230453/4222912/882d321e-3917-11e4-8330-4326828c1d5f.png)

**Comment by RyanCavanaugh** [comment]
This works as expected now
