### ISSUE TITLE
Need support for type alias checking...

### ISSUE THREAD

**Issue by qdwang** [Microsoft/TypeScript#6461]
```typescript
type price = number;
type size = number;

var a: price = 1;
var b: price = 1;

var c: size = 1;
var d: size = 1;

console.log(a + b); // this should work;
console.log(a + c); // this should fail;
```

Or is there an alternative way to achieve this?

**Comment by sandersn** [comment]
You can use an interface with a private brand, but type aliases are pure aliases -- they have no [nominal] identity of their own. #364 covers units of measure, which is related, and actually has a concrete proposal open.

**Comment by RyanCavanaugh** [comment]
See also #202
