### ISSUE TITLE
Cannot define type while destructuring in a $q.all 

### ISSUE THREAD

**Issue by khagesh** [Microsoft/TypeScript#6463]
<pre>
$q.all([
  IPromise&lt;type does not work here&gt;promise1,
  promise2
])
.then([result1: &lt;can't define type here as well&gt;, result2] => { }`
</pre>

I have tried to type cast promise and tried to define type in `.then` as well and it still gives error. I have tried with simple function as well and it does not work for simple functions as well.

**Comment by kitsonk** [comment]
These are best for other forums, like StackOverflow or gitter.im.

You need to understand tuple types in TypeScript better.

```typescript
$q.all([ promise1, promise2 ])
    .then(( [ result1, result2 ]: [ string, string ] ) => { });
```

**Comment by khagesh** [comment]
@kitsonk Sorry, I did not know we could do something like this and thought it might be a bug. Thanks for reply.
