### ISSUE TITLE
New Website Logo:Traeger Industry Components GmbH

### ISSUE THREAD

**Issue by loisl61** [Microsoft/TypeScript#6464]
Please fill the following out:

- Name: Traeger Industry Components GmbH
- Homepage url:https://www.traeger.de
- Brand Guidelines/Licensing: nothing
- Logo: https://www.traeger.de/pub/downloads/traeger_industry_components_logo.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by loisl61** [comment]
Traeger Industry Components is using TypeScript.

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
