### ISSUE TITLE
Support for new ES6 string methods?

### ISSUE THREAD

**Issue by cerebrl** [Microsoft/TypeScript#6468]
I just wanted to ask if there was any intention of adding the new ES6 string methods to Typescript. Doing something like `"string".includes("in");` warns with "prototype 'includes' does not exist on type 'string'." Thanks in advance for any information.

Ref: http://www.ecma-international.org/ecma-262/6.0/#sec-string.prototype.includes

**Comment by kitsonk** [comment]
Are you targeting `es6` or `es2015` because it is in [core.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/911d07a81b9348dd576985f263955c8e0968277e/lib/lib.core.es6.d.ts#L4259)?

**Comment by RyanCavanaugh** [comment]
Indeed, just `--target es6` and you're good to go

**Comment by cerebrl** [comment]
So, if I target ES5, it won't transpile it to valid ES5?

**Comment by RyanCavanaugh** [comment]
I maybe don't understand the question.

If you're targeting ES5, ES6 string methods aren't available. If you include a polyfill at runtime, just include the corresponding .d.ts file for that polyfill and you're back in good shape.

**Comment by cerebrl** [comment]
Oh, okay. I think I may have had a misunderstanding of Typescript's features. I was thinking Typescript allows authoring in ES6 and it will transpile to ES5 (like Babel), but it seems that Typescript only does that for select ES6 features, like modules.

If one wanted this ES6 to ES5 functionality, would I add Babel to my build process? Is that what most Typescript users do?

Sorry for the stupid questions (and assumptions). Thanks for the replies @kitsonk and @RyanCavanaugh!

**Comment by kitsonk** [comment]
> So, if I target ES5, it won't transpile it to valid ES5?

> but it seems that Typescript only does that for select ES6 features, like modules.

TypeScript does not add runtime polyfills/shims.  It is a [TypeScript non-design goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals):

> 6. Provide additional runtime functionality or libraries. Instead, use TypeScript to describe existing libraries.

It only deals with language constructs (e.g. classes, variables, operators).  Many people use [es6-shim](https://github.com/paulmillr/es6-shim) or [core.js](https://github.com/zloirock/core-js).  In [Dojo Toolkit](https://github.com/dojo/core), we have chosen not to polyfill globals and provide many of the functional features as a module which offloads to native if present or otherwise fills the functionality.  For example, importing [dojo/core/Promise](https://github.com/dojo/core/blob/master/src/Promise.ts) would provide you with something that always behaved like a ES6 Promise, but didn't interfere with anyone else.  This is because we believe that you aren't always fully in control of your runtime environment in complex projects, so why mess with globals and potentially break someone else's code.

**Comment by RyanCavanaugh** [comment]
I think you're confusing transpilation with auto-polyfilling. TypeScript doesn't automatically polyfill for you like Babel does, but *does* perform syntactic downleveling (e.g. for arrow functions).

If you want to use ES6 runtime prototype methods, I'd simply include an appropriate ES6 polyfill and its accompanying definition file.

**Comment by cerebrl** [comment]
You are correct. I am confusing transpilation with polyfilling. I will look into an appropriate solution. Still getting used to all this terminology, so thank you for putting up with me :)

**Comment by xjamundx** [comment]
Hey so I'm trying to figure this out. 

Seeing this message:

```
```

**Comment by xjamundx** [comment]
Running into the same issue. Again I'm coming from a babel ecosystem and have a polyfill for these. I noticed these online, but not quite sure how to install them:
http://definitelytyped.org/docs/typescript-services--typescriptServices/classes/typescript.stringutilities.html

**Comment by cerebrl** [comment]
@xjamundx I did a bit of research, and it seems extending the "basic types" in TypeScript is pretty easy. I just tossed the below `interface` into my *custom* typings directory (not the "typings" directory that is managed by `typings`, the NPM module), and all my ES6 string methods were essentially ignored by the compiler and complied as written:

```js
// arbitrarily named "es6-string-methods.d.ts"
interface String {
	repeat: (string) => string;
	startsWith: (string) => string;
	endsWith: (string) => string;
	includes: (string) => string;
}

// Original TypeScript file "greeting.ts"
let overlyFriendly = 'hello'.repeat(3);

// Compile JavaScript file "greeting.js"
var overlyFriendly = 'hello'.repeat(3);
```

Just use it as an "ambient definition", meaning it's treated like a global definition. As long as you have the polyfill to handle the new string methods, It Just Works (TM). Let me know if it works for you.

**Comment by xjamundx** [comment]
Thanks @cerebrl 

I just changed my `target` to `es6` and it all worked fine without needing any of this. Also looks like Typescript 2.0 has more explicit support for this kind of thing here:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#including-built-in-type-declarations-with---lib
