### ISSUE TITLE
Support `nameof(Enum)` or equivalent

### ISSUE THREAD

**Issue by kamranayub** [Microsoft/TypeScript#6470]
I understand to get the string name of an Enum I can do:

    MyModule.MyEnum[MyModule.MyEnum.Foo]

However it would be neat/more concise to support something like C#'s `nameof` operator:

    nameof(MyModule.MyEnum.Foo)

Which would output the longer version for runtime. The only benefits of this really are less typing and less verbose (annoying with long namespaces). And if TS supported `nameof` on parameters, it would be a bonus.

**Comment by RyanCavanaugh** [comment]
How is this different from #1579?

**Comment by kamranayub** [comment]
Looks like that is a full proposal of `nameof`. I suppose this would be a smaller implementation scoped to enums only, which seems a lot easier to get out the door than a full nameof proposal. I also didn't find that issue since it was Closed. Also, there was no mention of Enum types in that issue.
