### ISSUE TITLE
React's 'children' property is not properly recognized

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#6471]
say I have:

```
class Parent extends React.Component<{children:any}, {}>{
  render() {
     return <div> {this.props.children}</div>
  }
}

class Container extends React.Component<{},{}> {
	
	render() {
		return <Parent> //typescript shows error here cause no 'children' attribute present
		 <h2>Hello</Hello>
		</Parent>
	}
}
```

In this case, `Container` is calling `Parent` correctly by passing in the children as nested elements.
However, Typescript still complains that it doesnt see an explicit 'children' attribute.

Typescript should know that 'children' attribute is special.

TS version 1.7.3

**Comment by RyanCavanaugh** [comment]
We've decided not to special-case the `children` attribute because it's so React-specific.

The recommended practice is to write the `props` type as `{children?: any}`

**Comment by simonbuchan** [comment]
Seems like strange reasoning if you have `complierOptions.jsx` set to `react`, looking for a namespace `React`, with handling of react intrinsic properties like `ref` and `key`, to be worried about being react specific any more :)

Perhaps `JSX.ContentAttributesProperty` with `@types/react` declaring `{ children: ReactNode }`?

**Comment by mhegazy** [comment]
https://github.com/Microsoft/TypeScript/issues/13618 should address this.
