### ISSUE TITLE
Language Serivice support in Angular 2 inline templates

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#6477]
_From @jgw96 on January 13, 2016 2:1_

I love the code formatting feature in vscode, simply awesome, but not perfect in my opinion. I have been using angular 2 alot lately and have run into an issue where the code formatting feature will not format an inline html template. This would be ideal, especially when copy/pasting html into an inline template. Would love to hear what everyone has to say about this.

_Copied from original issue: Microsoft/vscode#1968_

**Comment by mhegazy** [comment]
//CC: @billti @chuckjaz

related to #5470

**Comment by thorn0** [comment]
@jgw96 Why did you write "tsx" in the title of this issue? Do you use JSX for Angular templates?

**Comment by mhegazy** [comment]
closing in favor of #5470
