### ISSUE TITLE
Allow defining static index signature

### ISSUE THREAD

**Issue by iby** [microsoft/TypeScript#6480]
``` ts
class Foo {
    [key: string]: any;
    static BAR:string = 'bar';
    static BAZ:string = 'baz';
}

console.log(Foo['BAR']);
console.log(Foo['B' + 'A' + 'Z']);
console.log(Foo['qux']);
```

I get the following errors with this:

```
tst.ts(8,13): error TS7017: Index signature of object type implicitly has an 'any' type.
tst.ts(9,13): error TS7017: Index signature of object type implicitly has an 'any' type.
```

I've read in the gitter archives that this should be working. Should it? How can I get a static property value using a dynamic key?

**Comment by ianbytchek** [comment]
Figured that I can access the value of a static property using the following notation. Is that error expected though? Is that because `[key: string]: any` for instances only?

```ts
console.log((<any>Foo)['B' + 'A' + 'Z']);
console.log((<any>Foo)['qux']);
```

**Comment by RyanCavanaugh** [comment]
You're correct -- the declared index signature only applies to the instance side of the class, not the constructor function itself.

Presumably we'd allow you to fix this without a type assertion by writing `static [key: string]: any` in the class declaration but that's currently disallowed. I don't see any obvious reason why it couldn't be allowed, though.

**Comment by ianbytchek** [comment]
Frankly `static [key: string]: any` was the first instinct. Tried it. Didn't work. I think it would be a very natural thing to have.

**Comment by RyanCavanaugh** [comment]
It makes sense from purely a code perspective... but what are you doing, exactly? When designing this feature we basically said "Do we ever need `static` index signatures?" and thought about it a bunch and came up with no user scenarios, so it'd be great to understand what kind of pattern you're writing. Thanks!

**Comment by ianbytchek** [comment]
I have a class which acts like enum and holds a bunch of constants. Though there are string enums, this is more appropriate & convenient for my case. And I need to check if the constant is there or not, which doesn't work nicely with `Foo['…']` syntax.

**Comment by RyanCavanaugh** [comment]
Accepting PRs. This should be a fairly easy change for someone familiar with the compiler, just checking for some flags during type construction.

**Comment by markspolakovs** [comment]
Has there been any progress on this in the past year? I'm running into this in a project, and it's blocking me, but I am not "familiar with the compiler", so I cannot make the fix myself.

**Comment by nikis05** [comment]
Obviously need this feature. My usecase:
• I write a framework that offers a class that is to be extended by the user;
• The extended class can have additional methods, both instance (no problem with this) and **static**;
• The framework needs to operate on these methods added by the user, aka
’’’javascript
let method = isMethodStatic ? ExtendedClass[methodName] : new ExtendedClass(someData)[methodName]
’’’

**Comment by kitsonk** [comment]
**Accepting PRs** means that the core team do not have the time to address this and it is open to the community to solve.

**Comment by Kingwl** [comment]
friendly ping @ianbytchek @nikis05 @markspolakovs 

I have a pr for this one.
You could take a preview [here](https://www.typescriptlang.org/play/index.html?ts=3.9.0-pr-37797-5#code/MYGwhgzhAECC0G8BQ1XQgFzBglsaA2gNYCmAngFzoYBOOAdgOYC6V9ArgLYBGJNSAXyRJYAOgBmAe0nQAvNACMSIA)(if you still need that).

**Comment by hengkx** [comment]
same problem.

**Comment by DanielRosenwasser** [comment]
Thanks @Kingwl!
