### ISSUE TITLE
#! -> treat as comment

### ISSUE THREAD

**Issue by Bigous** [Microsoft/TypeScript#6481]
When writing a node software that should create a batch or symbolic link, we need to put the folowing line at the begining of the .js file:
```javascript
#!/bin/node
```
So npm knows it is a node executable script and creates a batch file with all the necessary stuff in it.
If we put it at a typescript file to be transpiled to javascript, it works, but gives annoying compilation error.
I purpose that lines started with ```#!``` shoud be treated as a special case of commentary line that should always go to the transpiled file.

**Comment by jesseschalken** [comment]
What error are you getting? I'm using 1.7.5 and the `#!/bin/node` line is kept (copied to the `.js` file) without any error. (I believe #2749 first added `#!` support.)

**Comment by jesseschalken** [comment]
Maybe you're running into Microsoft/vscode#899?

**Comment by RyanCavanaugh** [comment]
This is a duplicate suggestion of #2749 -- if you're running bits that have that change, please post a specific bug report if that feature isn't working.

**Comment by Bigous** [comment]
That's it @jesseschalken ...
![image](https://cloud.githubusercontent.com/assets/6886560/12335305/a6bc48ea-bae5-11e5-81c9-eaaf026d7f38.png)
You can threat it as a duplicate - sorry about that (didn't know it was called shebangs)
