### ISSUE TITLE
Duplicate identifier, please provide a flag in tsconfig to disable, can't work like this...

### ISSUE THREAD

**Issue by born2net** [Microsoft/TypeScript#6483]
Duplicate identifier, please provide a flag in tsconfig to disable, can't work like this...
I know this is a duplicate issue but I don't see any traction from TS team.

We are developing a large scale TS App and we can't actual see TS errors as they are obscured by all the Duplicate identifier noise in the error log in and in the editor.... 

How hard would it be to add a --ignoreDups flag to TS to hide this error? 
come on guys, please resolve once and for all.... 

TX

Sean

**Comment by sandersn** [comment]
+1ing an existing issue is a more effective way to raise an issue's prominence. Here's a recent issue with more detail: #6475.
