### ISSUE TITLE
autocomplete imports

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript#6486]
_From @amb-it-ion on January 5, 2016 14:42_

I am not sure why I could not find any mention of this: I am really missing a feature to autocomplete on missing classes, e.g. when using Http from angular2/http, and given that angular2 is on the node_modules default path (or inside my tsconfig files configuration) I would expect the autocompletion to pick this definition up and add the corresponding import statement.

_Copied from original issue: Microsoft/TypeScript-Sublime-Plugin#425_

**Comment by mhegazy** [comment]
_From @amb-it-ion on January 8, 2016 15:20_

Just to clarify, I am talking about SystemJS import, .e.g. 'import {XYZ} from "XYZ/XYZ"'

**Comment by DanielRosenwasser** [comment]
Duplicate of #188.
