### ISSUE TITLE
Object initializer creates unused variable

### ISSUE THREAD

**Issue by SamuelMarks** [Microsoft/TypeScript#6488]
https://github.com/Microsoft/TypeScript/issues/1082 called for [Object initializer](the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) ES6 syntax.

Using tsc/typescript 1.7.5 with Node 5.3.0.

##### Input:
```
const x = {['c']: 'b'};
```

##### Output [`tsc input.ts`]:
```
var x = (_a = {}, _a['c'] = 'b', _a);
var _a;
```

**Comment by RyanCavanaugh** [comment]
I'm confused by which variable you think is unused? `_a` is used as a temporary during object initialization and cannot be removed. What do you expect the emit to be?

**Comment by SamuelMarks** [comment]
What's with line 2?

**Comment by RyanCavanaugh** [comment]
Again, what do you expect the emit to be?

**Comment by SamuelMarks** [comment]
Either the `_a` being declared before its use, or not declared with `var` at all.

**Comment by DanielRosenwasser** [comment]
`var` declarations are hoisted. We take advantage of this in the emit and aggregate all temporaries we determine we need as we emit. Then, at the end of an appropriate scope, we emit the declaration for all temporaries. There's nothing wrong with this semantically, and the variables are not unused.
