### ISSUE TITLE
Compiler doesn't give appropriate suggestions for static members from instance methods

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6491]
With #6469 in, we now give nice suggestions for the following

```ts
class C {
    static foo: string;

    static bar() {
        let k = foo;
    }
}
```

where we will report "Did you mean the static member 'C.foo'?".

A small snag is that it won't give you suggestions for a static member from an instance method.

```ts
class C {
    static foo: string;

    bar() {
        let k = foo;
    }
}
```

You'll just get "Cannot find name 'foo'." We should change this.

**Note that the following should have no suggestions:**

```ts
class C {
    foo: string;

    static bar() {
        let k = foo;
    }
}
```

**Comment by mhegazy** [comment]
//CC: @ShyykoSerhiy

**Comment by masaeedu** [comment]
@DanielRosenwasser Looks like `location & NodeFlags.Static` [here](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts#L794) is the culprit. I don't know enough about the test harness to PR though.
