### ISSUE TITLE
Remove WeakMap/WeakSet#clear method

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6500]
changes:

```diff
// lib.es6.d.ts and lib.core.es6.d.ts
// also WeakSet
 interface WeakMap<K, V> {
-    clear(): void;
     delete(key: K): boolean;
     get(key: K): V;
     has(key: K): boolean;
     set(key: K, value?: V): WeakMap<K, V>;
     [Symbol.toStringTag]: "WeakMap";
 }
```

https://tc39.github.io/ecma262/#sec-weakmap-constructor
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
https://bugzilla.mozilla.org/show_bug.cgi?id=1101817

**Comment by LPGhatguy** [comment]
What runtime environments have this implemented?

I did a quick test against the latest Chrome, Node.js, and Edge and none of them had `WeakSet.prototype.clear` defined as far as I could tell.

**Comment by mhegazy** [comment]
@LPGhatguy it needs to be removed. it was part of the spec at an earlier draft but has since been removed.

**Comment by DanielRosenwasser** [comment]
Thanks @falsandtru!
