### ISSUE TITLE
Update IndexedDB interfaces

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6501]
See https://github.com/Microsoft/TSJS-lib-generator/pull/51

**Comment by mhegazy** [comment]
@falsandtru please provide more details when logging issues. other users may be searching for the same issue in the future.

**Comment by falsandtru** [comment]
All right, is there any format or template?

- IDBObjectStore#autoIncrement
- IDBObjectStore#keyPath
- IDBDatabase#transaction
- IDBCursor#source
- IDBRequest#source
- WorkerUtils implements IDBEnvironment

and please tell me about https://github.com/Microsoft/TSJS-lib-generator/issues/50.

**Comment by falsandtru** [comment]
@mhegazy I want to add a fix: `IDBIndex#openCursor` method's first parameter type must be `any`.

**Comment by mhegazy** [comment]
@falsandtru, i would open a different issue for that. also feel free to send a PR for it.

**Comment by falsandtru** [comment]
@mhegazy okay, I opened #7218.
