### ISSUE TITLE
Type inference is overly strict when dealing w/ Union types and overloads

### ISSUE THREAD

**Issue by nimish** [Microsoft/TypeScript#6503]
interface OverloadedMethod {
        (a:string): Object;
        (a:number): void;
    }
    
    const bar : string|number = 0;
    const foo : OverloadedMethod = null;
    foo(bar) // red squiggles here under bar: Argument of type 'string | number' is not assignable to 'string'. Type 'string | number' is not assignable to 'number'

This is a minimal example of where typescript complains that `bar` cannot unify with any of the individual methods on `foo`, even though it could reasonable deduce that since there's only one implementation of said method, that `(a:string|number) : Object|void` is a perfectly cromulent alternative.

Looks like this is a consequence of https://github.com/Microsoft/TypeScript/issues/5766 and it rears it head when dealing w/ Express routing's d.ts.

**Comment by RyanCavanaugh** [comment]
Please search for duplicates before logging new issues. #1805
