### ISSUE TITLE
Is there a reference implementation of tsconfig.json being used in Visual Studio?

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#6504]
This is probably related to https://github.com/Microsoft/TypeScript/issues/6317 but not exactly the same.

Having not used Visual Studio for a while I've just come back to it and been trying to use `tsconfig.json` in a standard ASP.Net MVC 5 project.  For reasons that aren't clear to me the `tsconfig.json` doesn't appear to be being detected by Visual Studio in the way I would hope.  There doesn't appear to be a reference implementation that I can refer to of how `tsconfig.json` should look in a Visual Studio project.  Here's my assumptions / experiences:

- `tsconfig.json` is included with a *Build Action* of "Content" and a *Copy to Output Directory* of "Do not copy"
- `tsconfig.json` can sit in the root of the Visual Studio project (alongside `package.json` etc)
- you can't stop Visual Studio forcing these options upon your `csproj`:

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptJSXEmit>None</TypeScriptJSXEmit>
    <TypeScriptCompileOnSaveEnabled>False</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
    <TypeScriptModuleKind>None</TypeScriptModuleKind>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptOutFile />
    <TypeScriptOutDir />
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
    <TypeScriptSourceMap>False</TypeScriptSourceMap>
    <TypeScriptMapRoot />
    <TypeScriptSourceRoot />
  </PropertyGroup>
```

It's non-negotiable; you take them out it'll put them right back in next time you edit your project properties in VS.

I've kind of given up on `tsconfig.json` in Visual Studio now as I think I'm somehow missing the point.  It would be great if there was an example implementation to refer back to.  I notice that there doesn't  seem to be a File -> New Project experience for `tsconfig.json` which is a shame.

**Comment by paulvanbrenk** [comment]
Your second assumption is wrong, `tsconfig.json` has to sit in a `scripts` folder, and can't be in the root at this time.

More info see the [Using TypeScript With ASP.NET 5](https://github.com/Microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5).

**Comment by johnnyreilly** [comment]
Thanks @paulvanbrenk - I'll give it a try. This guide is for ASP.Net 5 project types - I assume that old school projects (pre-ASP.Net 5) will work as well?

**Comment by paulvanbrenk** [comment]
No, this only works in ASP.NET 5 for now.. we're planning on making changes in the next public release of TypeScript to support more project types.

**Comment by johnnyreilly** [comment]
Thanks @paulvanbrenk - so part of TypeScript 1.8?

**Comment by paulvanbrenk** [comment]
@johnnyreilly Yes, that's the plan.
