### ISSUE TITLE
tsc --watch regression in typescript@next: not detecting .tsx file changes (only .ts)

### ISSUE THREAD

**Issue by chbrown** [Microsoft/TypeScript#6511]
I'm using typescript@next (specifically, 1.8.0-dev.20160115) instead of typescript@1.7.5 because I want stateless functional component support in my React code. Running `tsc --watch` in my root project directory is working great for `.ts` files:

    9:08:58 PM - File change detected. Starting incremental compilation...
    9:09:00 PM - Compilation complete. Watching for file changes.

But it's not even flinching when a `.tsx` file changes. I downgraded to 1.7.5, and now (with no other changes) running `tsc --watch` recognizes changes to both `.ts` and `.tsx` files (despite complaining a bit about my JSX not evaluating to proper Elements or whatever).

I'm using a tsconfig.json with:

    "compilerOptions": {
      "jsx": "react",
      "module": "commonjs",
      "moduleResolution": "node",
      "target": "ES6"
    },

And a bunch of files added by hand, including both `.ts` and `.tsx` files in the root directory.

Like I said, 1.7.5 works just fine, so it's not something weird with my editor. Has `.tsx` been deprecated? (Which would be awesome— I'm all for deprecating `.tsx` and compiling all `.ts` files as if they were `.tsx` if `compilerOptions.jsx !== undefined`.)

**Comment by chbrown** [comment]
Update: just switched to working on a different project that didn't have the problem, and found it was running typescript@1.8.0-dev.20160108. So the regression happened sometime in the last week.

**Comment by mhegazy** [comment]
Looks like a bug. @zhengbli this looks related to your watch fix. Can you take a look?

**Comment by zhengbli** [comment]
This should be the same problem that https://github.com/Microsoft/TypeScript/pull/6509 was fixing. I tested using the one from master and `.tsx` files work fine now.

@chbrown can you try the tsc.js I created at https://gist.github.com/zhengbli/0e63584b3daf3b521671 ?

**Comment by zhengbli** [comment]
@chbrown the latest nightly should contain the fix. Can you give it a try? Thanks

**Comment by chbrown** [comment]
Awesome! Just updated to `typescript@1.8.0-dev.20160116` and it's recognizing `.tsx` changes again. Thanks @zhengbli (and @mhegazy for the diagnosis & triage)!

**Comment by mhegazy** [comment]
Thanks @chbrown!
