### ISSUE TITLE
Give template strings a different classification type

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6513]
At the time, we just used `"stringLiteral"` because it was such a PITA to sync between the managed side and whatnot. We never followed up on it. Prompted by #6508.

Open questions:
1. Do we want to classify `${` and `}` specially?
2. If we do want to classify `${` and `}` specially in templates, do we want to classify backticks?
3. What colors do we want to use in VS?

@derekcicerone @basarat

**Comment by derekcicerone** [comment]
Thanks for checking. I don't have a strong opinion on the highlighting for string templates. It never hurts to have more specific classifications though - worst case we can keep coloring as strings. The syntax coloring I'd still really like is to distinguish between a normal comment and JSDoc.

**Comment by basarat** [comment]
I am very happy with what is there currently in the syntactic analyzer (the one between lexical and semantic) :rose:
