### ISSUE TITLE
Circular dependency and class inheritance

### ISSUE THREAD

**Issue by Vloz** [Microsoft/TypeScript#6516]
I dunno if it work as intended (if so, i m sorry), but calling extended class from it's base class file doesnt work:

parent.ts
```javascript
import {Child} from './child'; //Circular dependency there

export class Parent {
    constructor(){
    }
}

new Child(); // <= error there
```

child.ts
```javascript
import {Parent} from './parent'; //Circular dependency there

export class Child extends Parent{
    constructor(){
            super();
    }
}
```

***node parent.js*** throws me:
```shell
new child_1.Child();
^

TypeError: child_1.Child is not a function
```

**Comment by basarat** [comment]
As soon as you have : 

```
 import {Child} from './child'; //Circular dependency there
```

NodeJS will pause execution of `parent.js` and execute `child.js`. If `child.js` as for something from `parent.js` then node gives it `{}`. 

**TypeScript doesn't care about circular dependencies at the moment**. It is up to you to analyze your code based on the module system you are using (e.g. nodejs https://nodejs.org/api/modules.html#modules_cycles) 

That said I've written something to analyze these cycles for you : https://github.com/alm-tools/alm/tree/master/docs/features#dependency-view but its not released yet :rose:

**Comment by Vloz** [comment]
Ok, then i guess it works as atended. ^^
Thank you very much for the explaination basarat!
