### ISSUE TITLE
Discussion: Type casting and typing = position ambiguity

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#6519]
Hello,

Here is my code example:
```
let value : any;                   // ok javascript like 
(<string[]>value).length     // why not (value<string[]>).length
```

< string[] > value is more c# like : (string[])value in c#

Why not using a javascript style for typing and type casting: always put typing at the end of the expression ? (I mean "javascript style" because :any signature seems to be adopted)

Thanks in advance for your answers.

**Comment by ahejlsberg** [comment]
We already support postfix type assertions using the `as` operator, so if you prefer that you can simply write `(value as string[]).length`.

**Comment by Alphapage** [comment]
Thank you. You learn me something. +1
