### ISSUE TITLE
consider separating TypeScript API from binaries and start using semver versioning for it

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/TypeScript#6520]
Currently the version of the NPM package of TypeScript hardly makes any semver sense as it is supposed to:
- breaking changes to the language features do not a get major number bump
- breaking API changes are shipped under the same version as the language

It's not clear what drives these version changes.

Consider making some use of semantic versioning, because it has its benefits, especially in the context of NPM.

**Comment by mhegazy** [comment]
We have an API version that we have not been changing. i agree we should change everytime we ship and when we make any breaking changes.

**Comment by mhegazy** [comment]
i do not think there is an intimidate action item here. so i will close this, and next time we make a change to the API we will update the API version.
