### ISSUE TITLE
Typing assertions with as operator not working with tsserver

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#6522]
Hello,

In vscode, when type casting like this:
```
let array:any;
(array as string[]).length // I don't get intellisense
```
But if I use < string[] > array, then I get intellisense.

Is as operator only available for tsx ?

Thanks in advance for your help.

**Comment by DanielRosenwasser** [comment]
Nope, you should be seeing it. Are you possibly using an older version of VS Code? The latest is 0.10.6.

**Comment by Alphapage** [comment]
I'm using latest version of vscode 0.10.6 with tsserver 1.7.5 and I'm getting "cannot find name as"

**Comment by RyanCavanaugh** [comment]
The only reason you'd see this error is that VS Code is loading the wrong version of TypeScript.

**Comment by Alphapage** [comment]
It compiles but I get an error from tsserver 1.7.5. From which version approximatively was 'as' implemented?

**Comment by RyanCavanaugh** [comment]
1.6

**Comment by mhegazy** [comment]
![animation](https://cloud.githubusercontent.com/assets/8000722/12429759/ef6fc97c-bea0-11e5-95f2-879a5d49a895.gif)

**Comment by Alphapage** [comment]
Does it work only with tsx file ? I tried with .ts file

**Comment by RyanCavanaugh** [comment]
It works with .ts as well.

**Comment by Alphapage** [comment]
Ok sorry.I will try on a fresh virtualbox asap. Thank you

**Comment by Alphapage** [comment]
I tried on a fresh virtualbox and it is working as expected. I have uninstalled, reinstalled vscode and I get intellisense now.
I'm sorry that you have lost your time.
Thank you very much for your help.

**Comment by RyanCavanaugh** [comment]
Glad you got it working!
