### ISSUE TITLE
Flow type casting alignment ?

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/TypeScript#6523]
Hello,

Do you plan to implement type casting like in Flow ?

http://flowtype.org/blog/2015/02/18/Typecasts.html

It is related to a previous question :https://github.com/Microsoft/TypeScript/issues/6519

I think Flow implementation respects more javascript typing philosophy by putting type at the end of the expression.

Thanks in advance for your answers.

**Comment by Arnavion** [comment]
>by putting type at the end of the expression.

So does the `as` operator that Anders told you about in the other issue.

Are you asking to support Flow's `:` operator in addition to TS's `as` operator?

**Comment by Alphapage** [comment]
Personally, I hope so if possible for the reason I describe.
I think it would help to implement common rules and let developers choose what typing feature they prefer to remove less used or depreciate them.

**Comment by aleksey-bykov** [comment]
What you are asking is hardly feasible. There is no reason to give 2 syntaxes for the same thing other than to confuse the users. Kind of late to the party.

**Comment by aleksey-bykov** [comment]
Would you elaborate on "javascript typing philosophy". Haven't heard of such. Fascinated to read about it.

**Comment by Alphapage** [comment]
C# philosophy: string str; ((string)str) // typing before expression
Javascript philosophy: let str:string; // typing after expression except for type casting

**Comment by aleksey-bykov** [comment]
FYI, JavaScript doesn't have types to declare and associate with variables.
All you have is a type associated with a value at runtime at a given moment
that can change later which has nothing to do with the pascal style
declarations you referring to.

**Comment by RyanCavanaugh** [comment]
See discussion in #296 and my comment here https://github.com/Microsoft/TypeScript/issues/3203#issuecomment-103310660 in particular
