### ISSUE TITLE
Make a method of a generic interface A<T> available only if T is of a certain type

### ISSUE THREAD

**Issue by thorn0** [Microsoft/TypeScript#6529]
Let's look at the library Lodash for the example. Values of any type can be wrapped in `_`:
```ts
_({ a: 1 })
_([1,2,3])
_(x => x * x)
```
However, not all the methods of the wrapper make sense for any type of the wrapped value. For example, calling `_(z),memoize()` makes sense only if `z` is a function. So let's try to create a type definition for this situation:
```ts
interface Lodash {
    <T>(value: T): LodashWrapper<T>;
}
interface LodashWrapper<T> {
    memoize(): LodashWrapper<T>;
}
```
AFAIK for now it's not possible to write such a constraint for `memoize` that a call to it will type-check only when `T` is a function. Is it going to be possible in the future versions? Is there already an issue for this?

**Comment by DanielRosenwasser** [comment]
You could make a subclass of `LodashWrapper`

```ts
interface LodashFunctionWrapper<T> extends LodashWrapper<T> {
    memoize(): LodashFunctionWrapper<T>;
}
```

and add an overload whose parameter is constrained to functions

```ts
interface Lodash {
    <T extends Function>(x: T): LodashFunctionWrapper<T>;
}
```

[This is already done to some extent in DefinitelyTyped's declaration file for lodash.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/70bf7e2bfeb0d5b1b651ef3219bcc65c8eec117e/lodash/lodash.d.ts#L41-L46)

By the way, while I can help out with this now, in the future you should really post questions like this to StackOverflow or our Gitter room.

Hope that helps!

**Comment by thorn0** [comment]
I posted on SO, but didn't get an answer. And Lodash is just for example. My question is about a specific language feature, that's why I decided that it's okay to write here.

**Comment by thorn0** [comment]
And we can get `LodashWrapper<Function>` not only from a call to `_`. So we'll have to add an overload to all the other functions that return a wrapper if we use this approach.

**Comment by thorn0** [comment]
In the extreme, this feature could allow overloads like these:
```ts
interface Foo<T> {
    bar(): string if T is Function;
    bar(): number; // otherwise
}
```

**Comment by thorn0** [comment]
Turns out there is already an issue for this: #1290.
