### ISSUE TITLE
No compile time warning on using `event`

### ISSUE THREAD

**Issue by AJamesPhillips** [Microsoft/TypeScript#6530]
Is this expected behaviour?

	function broken(evt: Event) {
		// Meant to do something with `evt` but typed it incorrectly.
		Event.target;  // Errors correctly
		event.target;  // No error.  Expected behaviour?
	}

tsc version: 1.7.5

**Comment by DanielRosenwasser** [comment]
[`event` has an ambient declaration in `lib.d.ts`](https://github.com/Microsoft/TypeScript/blob/31bbac3c11c82af6cb93fd26ccf1632da6a04353/src/lib/dom.generated.d.ts#L12686). We've run into similar problems with `name`. I don't think there's anything we can do about this. Ideally one could write a linter rule forbidding use of these declarations.

**Comment by AJamesPhillips** [comment]
Got it.  Thanks for the speedy response!

**Comment by adidahiya** [comment]
we've run into this problem as well. filed a TSLint issue to track it https://github.com/palantir/tslint/issues/922

**Comment by DanielRosenwasser** [comment]
Thanks @adidahiya!
