### ISSUE TITLE
JSX bug: TS2605 on stateless component

### ISSUE THREAD

**Issue by polkovnikov-ph** [Microsoft/TypeScript#6531]
// test.tsx
	/// <reference path="react/react.d.ts" />
	/// <reference path="react/react-dom.d.ts" />
	import React = require('react');
	import ReactDOM = require('react-dom');
	let Test = (state: any) => <div />;
	ReactDOM.render(<Test />, document.getElementById('react'));

compiled with

	$ tsc test.tsx --jsx react --module commonjs

results in

	error TS2605: JSX element type 'Element' is not a constructor function for JSX elements.

In case we translate JSX by hand and use

	let Test = state => React.createElement("div", null);
	ReactDOM.render(React.createElement(Test, null), document.getElementById('react'));

everything works as expected.

**Comment by polkovnikov-ph** [comment]
@RyanCavanaugh @sheetalkamat, please :)

**Comment by polkovnikov-ph** [comment]
Now's time for some surprises. In case we translate JSX by hand and use

	let Test = state => React.createElement("div", null);
	ReactDOM.render(React.createElement(Test, null), document.getElementById('react'));

everything works as expected.

**Comment by thorn0** [comment]
Duplicate of #6353

**Comment by polkovnikov-ph** [comment]
Confirmed.

**Comment by polkovnikov-ph** [comment]
Nope, this still doesn't work.

	function test<T>(x: T): T {
		return x;
	}
	let Test = test((state: any) => <div />);
	ReactDOM.render(<Test />, document.getElementById('react'));

emits

	error TS2605: JSX element type 'Element' is not a constructor function for JSX elements.
	  Property 'render' is missing in type 'Element'.

**Comment by polkovnikov-ph** [comment]
Nope, still doesn't work.

	function test<T>(x: T): T {
		return x;
	}
	let Test = test((state: any) => <div />);
	ReactDOM.render(<Test />, document.getElementById('react'));

emits

	error TS2605: JSX element type 'Element' is not a constructor function for JSX elements.
	  Property 'render' is missing in type 'Element'.

**Comment by thorn0** [comment]
It hasn't been released yet. Use `typescript@next` if you need it now.

**Comment by RyanCavanaugh** [comment]
What @thorn0 said (thanks!)

**Comment by polkovnikov-ph** [comment]
@RyanCavanaugh But that's what I've seen in typescript@next and master!
