### ISSUE TITLE
DecodeErrorCallback in the Web Audio API has the wrong signature

### ISSUE THREAD

**Issue by CShankland** [Microsoft/TypeScript#6534]
Relevant spec excerpt from section 2.1:
```
callback DecodeErrorCallback = void (DOMException error);
```

Definition from `src/lib/dom.generated.d.ts`:
```
interface DecodeErrorCallback {
    (): void;
}
```

**Comment by CShankland** [comment]
A related issue is missing `disconnect` overloads in `AudioNode` (section 2.4):
```
    void      disconnect ();
    void      disconnect (unsigned long output);
    void      disconnect (AudioNode destination);
    void      disconnect (AudioNode destination, unsigned long output);
    void      disconnect (AudioNode destination, unsigned long output, unsigned long input);
    void      disconnect (AudioParam destination);
    void      disconnect (AudioParam destination, unsigned long output);
```

Existing `dom.generated.d.ts` definition:
```
disconnect(output?: number): void;
```

**Comment by mhegazy** [comment]
link to spec: https://webaudio.github.io/web-audio-api/#BaseAudioContext

**Comment by mhegazy** [comment]
PRs are welcomed. You can find more informaiton about contributing lib.d.ts fixes at: https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes
