### ISSUE TITLE
Infer union type for spread argument arrays

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/TypeScript#6536]
```
function f1<T>(...args: T[]) { ... }

function f2<T>(args: T[]) { ... }

f1(10, "foo"); // Infers T = any, or errors if noImplicitAny
f2([10, "foo"]); // Infers T = number | string
```

It would be nice if `T` was inferred as `number | string` for the invocation of `f1`.

**Comment by RyanCavanaugh** [comment]
I don't think this should be an implicit any, especially since we're breaking symmetry anyway from an explicit two-argument version of `f1`.

**Comment by masaeedu** [comment]
@RyanCavanaugh Actually, I think I might be wrong about `any` being inferred for the case where `noImplicitAny` isn't used. I just tried this out in [playground](http://goo.gl/he05kW), which doesn't use `noImplicitAny`, and it complains about being unable to infer `f1` (as opposed to inferring `any`). My bad.

Nevertheless, I think it would be reasonable to infer `T` as the union of the arguments here.

**Comment by RyanCavanaugh** [comment]
The error is the correct behavior.

We have (human) logic that says if you write
```ts
function compare<T>(x: T, y: T): boolean { ... }
// wat?
let t = compare(42, "foo");
```
It should be an error if `a` and `b` are of incompatible types. We used to infer `{}`, it was a giant bug trap and people complained about it all the time; inferring a union type would be just as bad.

So in the rest argument case, it would be odd to not apply the same logic.

Let's say you wrote this code
```ts
f1(
  getThing(1),
  getThing(2),
  getThing); // Oops
```
It would be really odd to infer `X|(n: number) =>X`. And when `T` doesn't appear in the return type, it makes the genericness useless -- you may as well have written `...args: any[]`

**Comment by masaeedu** [comment]
@RyanCavanaugh The actual use case is one where the `T` appears in the return type. Regarding the example you provided, I don't see why you would expect:

```
f1(
  getThing(1),
  getThing(2),
  getThing); // Oops
```

To behave any differently from:

```
f1([
  getThing(1),
  getThing(2),
  getThing]); // Oops
```

The error in this cae is easily caught when the user tries to do something with the type related to `T` that is returned and the compiler complains when his expectations are violated. Let's say `f1` was implemented like this:

    function f1<T>(...args: T, project: (arg: T) => R): R[] { }

Now the user tries to do this:

```
f1([
  getThing(1),
  getThing(2),
  getThing], thing => thing.someProperty) // Whoops, a (n: number) => Thing can't behave like a Thing
```

I hope you will reconsider this.

**Comment by masaeedu** [comment]
In case you're interested in the actual use case, I don't want to have to type this:

    Observable.mergeAll<Observable<string>|Observable<number>|Observable<Date>[]>(obs1, obs2, obs3);

**Comment by masaeedu** [comment]
Finally, regarding the `compare` example, the issue is with the signature of the generic `compare` function. It's unlikely you could implement a `compare` function that took two instances of any type whatsoever and managed to compare them, unless the type provides some way of being compared to another. In this case, the signature should be:

```
interface IComparable<T> {
    compareTo(other: T);
}
function compare<T extends IComparable<T>>(arg1: T, arg2: T) {
    ...
}
// Assume string implements IComparable<string>, number implements IComparable<number>

compare("foo", 10); // Will error, as expected
```

(Sorry for triple posting :smile:)

**Comment by RyanCavanaugh** [comment]
I don't understand why the type `Observable<string>|Observable<number>|Observable<Date>[]>` is at all useful. Are you really decomposing it again later? Why not just write `Observable<{}>` ?

**Comment by masaeedu** [comment]
@RyanCavanaugh There are many cases where you need to provide a default value, or you need to zip together observables of different types, or provide stream from multiple sources of non homogeneous data. It is useful to be able to lose some safety when working with streams like this, rather than all safety. E.g. if you had source that provided `Observable<Observable<string>>`, `Promise<string>` or `string`, it would be nice to remember that you're getting those three things, without having to degrade to `{}` or `any`. Right now that's still possible, you just have to explicitly type out the long and unwieldy union type argument.
