### ISSUE TITLE
Types get merged into the global namespace unexpectedly when using module.exports

### ISSUE THREAD

**Issue by tylerchurch** [Microsoft/TypeScript#6539]
As someone new to TypeScript after writing a lot of JavaScript for nodejs, I found an issue that I think is either a bug or warrants adding some kind of warning when you use `module.exports`. When using module.exports, types defined in my nodejs files act as if they are globally available to the whole program.

For the sake of example, let's say I have some code in a file named `main.ts` that looks like this:

```ts
class ComputationClass {
    public value: number;

    constructor(a: number, b: number) {
        this.value = a * b;
    }
}

console.log("Hello, World!");
console.log(new ComputationClass(1, 2).value);

module.exports = {
    something: function() {
        console.log("Something!");
    }
};
```

And some code in another file named `other.ts` that looks like this:

```ts
let x = new ComputationClass(1, 4);
```

And a `tsconfig.json` that looks like this:

```json
{
    "compilerOptions": {
        "target": "ES5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "noImplicitAny": false
    },
    "exclude": [
    ]
}
```

I also have the nodejs typings from DefinitelyTyped installed.

I would expect when I compile this to get an error that looks like this:

```
other.ts(1,13): error TS2304: Cannot find name 'ComputationClass'.
```

Except I don't. It compiles without any warnings or errors, even though `ComputationClass` is not available in `other.ts`.

This made me sad, as one of the type safety benefits I was hoping to reap from TypeScript was TypeScript telling me if some code tried to use something without actually importing it.

After a long foray trying to understand where I went wrong, I found the `export =` syntax:

```ts
export = {
    something: function() {
        console.log("Something!");
    }
};
```

If I do that, I get the error message I was expecting.

As someone who writes a lot of nodejs, seeking out this `export =` syntax didn't occur to me for the longest time, because module.exports Just Worked. Except when it worked, it made some of my types appear as if they were globally available when they weren't.

Before stumbling across the `export =` syntax, some Googling and digging into the TypeScript source landed me on this code, which further confused me:
https://github.com/Microsoft/TypeScript/blob/master/src/compiler/checker.ts#L15666

```ts
forEach(host.getSourceFiles(), file => {
    if (!isExternalOrCommonJsModule(file)) {
        mergeSymbolTable(globals, file.locals);
    }
    if (file.moduleAugmentations) {
        (augmentations || (augmentations = [])).push(file.moduleAugmentations);
    }
});
```

Well, it is a commonjs module! I'm using commonjs features! And I told `tsconfig.json` to be in commonjs mode. Evenually I traced this `isExternalOrCommonJsModule` expression through to this section of code, which is looking for `module.exports`: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/binder.ts#L1196

However, that code is wrapped in a `if (isInJavaScriptFile(node)) {` block, for reasons I don't know enough to understand.

If I move this line up a little bit, so it's available:

```ts
const specialKind = getSpecialPropertyAssignmentKind(node);
```

And add the following code above line 1212, so it is outside of the `if (isInJavaScriptFile(node)) {` block:

```ts
switch (specialKind) {
    case SpecialPropertyAssignmentKind:
        bindExportsPropertyAssignment(node);
        break;
    case SpecialPropertyAssignmentKind.ModuleExports:
        bindModuleExportsAssignment(node);
        break;
}
```

I get the error I should've gotten all along with module.exports.

I can submit this change as a pull request, if it makes sense to those more familiar with how TypeScript internals work. Or perhaps a new kind of warning or change to the docs is in order if this is intended behavior, as I'm sure other people new to TypeScript but familiar with nodejs have run into this problem (personal anecdote: one of my coworkers was having this problem as well.)

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh @vladima

**Comment by mhegazy** [comment]
TypeScript follows the ES6/ES2015 module semantics. i.e. a file is considered as a module if it has a top-level `import`/`export`. if the file does not have any of these, it is considered a global script.

CommonJS, AMD, and SystemJS are other module formats, that have different semantics from the ES6 module spec. As you noted TypeScript could try and understand these, but that just adds complexity to the language, and the module syntax (which is already [complicated enough](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md)). there are also problems with emitting the output code to other module systems. 

What is supported however, is to write your modules in ES6 compatible format, and the TS compiler will emit it to CommonJS/AMD/SystemJS/ES6 modules. This way you get your interoperability, but still use the standard syntax. 


> Or perhaps a new kind of warning or change to the docs is in order if this is intended behavior, as I'm sure other people new to TypeScript but familiar with nodejs have run into this problem (personal anecdote: one of my coworkers was having this problem as well.)

PRs to update the docs (https://github.com/Microsoft/TypeScript-Handbook) or a proposal to update the error message are definitlly welcomed.
