### ISSUE TITLE
Error message for type guards are vague about rules

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6540]
From #6538

```ts
interface Animal {
    animal;
}

interface Dog extends Animal {
    dog;
}

interface Car {
    car;
}

let thing: Dog | Car;

function isAnimal(x: Car | Dog): x is Animal {
    return "animal" in x;
}
```

Currently we just report

>Type 'Animal' is not assignable to 'Car | Dog'.
>&nbsp;&nbsp;&nbsp;&nbsp;etc.

But that should be the *elaboration*. The first thing the user sees should be something like

> A type guard's type must be assignable to its parameter's type.`
>&nbsp;&nbsp;&nbsp;&nbsp;Type 'Animal' is not assignable to 'Car | Dog'.
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;etc.

**Comment by DanielRosenwasser** [comment]
This is a really easy bug t fix for anyone who wants to take a stab at this.

**Comment by Vinatorul** [comment]
I am trying to do this. It was not hard to add new diagnostic message, but I am not sure where should I check that I am checking the assignability of the guarded type. Is there a special way to find it out like backtrace?

**Comment by DanielRosenwasser** [comment]
`checkTypePredicate` is where the magic happens. Specifically, this has to do with the call to `checkTypeAssignableTo`.

**Comment by DanielRosenwasser** [comment]
Thanks @Vinatorul!
