### ISSUE TITLE
Spec grammar does not clarify relation to ES6’s parameterized rules

### ISSUE THREAD

**Issue by lucaswerkmeister** [microsoft/TypeScript#6542]
The TypeScript specification includes these two rules:

> &emsp;&emsp;_[UnaryExpression](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a2-expressions):_  _( Modified )_
> &emsp;&emsp;&emsp;…
> &emsp;&emsp;&emsp;`<`&emsp;_Type_&emsp;`>`&emsp;_UnaryExpression_
> 
> &emsp;&emsp;_[Declaration](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a3-statements):_  _( Modified )_
> &emsp;&emsp;&emsp;…
> &emsp;&emsp;&emsp;_InterfaceDeclaration_
> &emsp;&emsp;&emsp;_TypeAliasDeclaration_
> &emsp;&emsp;&emsp;_EnumDeclaration_

They append to the following ES6 rules:

> &emsp;&emsp;_[UnaryExpression](http://www.ecma-international.org/ecma-262/6.0/#sec-expressions)_<sub>[Yield]</sub> :
> &emsp;&emsp;&emsp;_PostfixExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`delete` _UnaryExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`void` _UnaryExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`typeof` _UnaryExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`++` _UnaryExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`--` _UnaryExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`+` _UnaryExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`-` _UnaryExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`~` _UnaryExpression_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;`!` _UnaryExpression_<sub>[?Yield]</sub>
> 
> &emsp;&emsp;_[Declaration](http://www.ecma-international.org/ecma-262/6.0/#sec-statements)_<sub>[Yield]</sub> :
> &emsp;&emsp;&emsp;_HoistableDeclaration_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;_ClassDeclaration_<sub>[?Yield]</sub>
> &emsp;&emsp;&emsp;_LexicalDeclaration_<sub>[In, ?Yield]</sub>

However, they don’t specify the behavior with regard to the ES6 rules’ parameters.

Since ES6 parameterized rules are [defined](http://www.ecma-international.org/ecma-262/6.0/#sec-grammar-notation) to be abbreviations for rules such as

> &emsp;&emsp;_UnaryExpression_ :
> &emsp;&emsp;&emsp;_PostfixExpression_
> &emsp;&emsp;&emsp;…
> 
> &emsp;&emsp;_UnaryExpression_Yield_ :
> &emsp;&emsp;&emsp;_PostfixExpression_Yield_
> &emsp;&emsp;&emsp;…

one possible reading of these rules is that only the unparameterized _UnaryExpression_ rule is augmented with the additional `<` _Type_ `>` _UnaryExpression_ production, whereas the parameterized rule _UnaryExpression_<sub>[Yield]</sub>, i. e. _UnaryExpression_Yield_, is left unaugmented (likewise for _Declaration_). This would mean that whenever the ES6 grammar produces the parameterized version, the TypeScript augmentations are unavailable. I don’t yet understand what the parameterization actually _does_ (I can only see that it’s passed through almost everywhere), but nevertheless this doesn’t sound like a reasonable interpretation to me. I think §2.1 of the TypeScript specification should clarify this.

**Comment by mhegazy** [comment]
I would say the augmentation applies to both parameterized and unparameterized forms.

**Comment by lucaswerkmeister** [comment]
At least the `<` *Type* `>` *UnaryExpression* production should probably propagate the parameter too.

I’m not sure if *Interface-*, *TypeAlias-* and *EnumDeclaration* should be parameterized as well.

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
