### ISSUE TITLE
Can't get to the instance type of a wrapped class across modules

### ISSUE THREAD

**Issue by jwbay** [Microsoft/TypeScript#6543]
Ran into this trying to leverage higher-order React components but it doesn't take much to reproduce:

Thing.ts
```typescript
class Thing { }

function wrap<T>(classType: T): T {
    return classType;
}

export default wrap(Thing);
```

ThingImporter.ts
```typescript
import Thing from "./Thing";

let thingInstance: Thing; //error: Cannot find name 'Thing'
let thingConstructor: typeof Thing; //ok
```

Even though the wrap function returns exactly what it takes in, the type gets changed from `class Thing` to `typeof Thing` and it seems this causes it to lose the class-reference-equals-instance-type magic in other modules.

TS versions: 1.7.5 and 1.8.0-dev.20160119
tsconfig:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5"
  }
}
```

**Comment by RyanCavanaugh** [comment]
Thanks for reducing the repro.

When we see an `export default` declaration, we expose "all meanings" of the expression on the right. The expression on the right, in this case, does not have any types, so there is no type meaning to expose.

Doing a general purpose expansion of the right-hand side here is generally not tractable.

If you wanted to create a default export that had a type meaning, you could write something like this:
```ts
class _Thing { }

function wrap<T>(classType: T): T {
    return classType;
}

const Thing: typeof _Thing = wrap(_Thing);
type Thing = _Thing;
export default Thing;
```

**Comment by jwbay** [comment]
Thanks for the quick reply! That works like a charm. I never would have thought to make an alias/local type with the same name as the actual export.

For anyone else who runs across this -- the root cause seems to be the wrap function and not so much the export. The same problem and fix applies within a single file.

```typescript
function wrap<T>(classType: T): T {
    return classType;
}

class Thing { }

const ThingTwo = wrap(Thing);
const ThingThree = wrap(Thing);
type ThingThree = Thing;

let thingTwo: ThingTwo; //error: Cannot find name "ThingTwo"
let thingThree: ThingThree; //ok 
```
