### ISSUE TITLE
[react/tsx] Visual Studio weird formatting for html (ctrl+k,ctrl+d)

### ISSUE THREAD

**Issue by yaananth** [Microsoft/TypeScript#6548]
![image](https://cloud.githubusercontent.com/assets/12280011/12454060/e75c1c90-bf63-11e5-9ca7-9992f05598ed.png)

As you can see, HTML tags won't match up on auto format.

**Comment by mhegazy** [comment]
looks fixed in latest.
![image](https://cloud.githubusercontent.com/assets/8000722/12457062/6ce88428-bf57-11e5-9785-3a0cc40a90be.png)

**Comment by mhegazy** [comment]
also including the text along with the screenshot would help in the next bug report.

**Comment by ddaghan** [comment]
@mhegazy paste image to one note and get the text from the image :)
