### ISSUE TITLE
TypeScript handbook still refers to old modules (aka namespaces)

### ISSUE THREAD

**Issue by mprobst** [Microsoft/TypeScript#6550]
When Googling (or Binging!) for TypeScript modules, the first hit is http://www.typescriptlang.org/Handbook#modules, which actually talks about namespaces in new nomenclature.

It'd be nice to update those docs, this causes some confusion for users about how they should structure their code.

**Comment by mhegazy** [comment]
the updated documentation is in https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Modules.md, we are in the process of rewriting the main website, and the new one should include the updated docs.
