### ISSUE TITLE
Derived class function parameter accepts {} regardless of base function parameter type

### ISSUE THREAD

**Issue by mykohsu** [Microsoft/TypeScript#6555]
This is on VS 2015 Typescript 1.7.6
See sample code below

```
class Param {
    Something: string;
}

class MoreParam extends Param {
    MoreSomething: boolean;
}

class Base {
    F(p: Param): void {
        p = { };  // Not assignable as expected
    }
}

class Extended extends Base {
    F(p: MoreParam): void {        // OK, instance of type MoreParam is assignable to Param
    }
}

class Empty extends Base {
    F(p: { }): void {        // Does not error as expected. {} is not assignable to Param
    }
}

class Else extends Base {
    F(p: { SomethingElse: number }): void {        // Not assignable as expected
    }
}
```

**Comment by DanielRosenwasser** [comment]
Actually, the usual "correct" direction should be that you check whether `Param` is assignable to `{}`. This idea is called contravariance. The idea is that it's okay to say that a function takes more properties even if it needs less.

But in TypeScript we use bivariance when comparing function parameters. See [this question on our FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant).
