### ISSUE TITLE
Incorrect code generation for ES6 imports

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#6556]
Using TypeScript 1.7.3.

Here is a portion of my `tsconfig.json`:

```
 "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "jsx": "react"
  }
 ```

This issue was seen when using the [`react-select`](https://github.com/JedWatson/react-select) library.

When using SystemJS (with JSPM), I had an import like this:

```
import Select from 'react-select';
```

Sample usgae of `Select` in code: 
```
render ()
{
	return <Select
		name="form-field-name"
		value={this.state.selectedMetricOption}
	/>
}
```

However, recently we switched to Webpack, so i told typescript to generate commonjs modules:

Thus in `tsconfig.json`:

```
	"module": "commonjs",
```

Now however doing 

```
import Select from 'react-select';
```

results in the value of `Select` being `null`.

Instead we have to do:

```
import * as Select from 'react-select';
```

and now `Select` works properly.

This seems like a Typescript bug.

Changing the output module style shouldnt require me to change my code.

**Comment by mhegazy** [comment]
SystemJS wraps commonjs/AMD modules (anything that does not have an __esModule property) as the default export of the module. so the only way to get to them is to use `import D from 'module'`. this is why your imports will only work if you are running on JSPM/SystemJs. `import * as N from "mod"` is going to work everywhere.
