### ISSUE TITLE
Type checker continues type checking after type conversion removed

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#6557]
_From @MIchaelMainer on January 20, 2016 8:15_

Repro step:
1) Add .d.ts file that contains a type definition for a class that doesn't contain a member referenced in the code file. In the attached image, I change the first line to <code> var imageRange = context.document.getSelection() as Word.Range;</code>. <code> Word.Range</code> showed as IntelliSense (auto-completion)
2) Then the type checker gives the warning you see in the image, 'Property X does not exist on type Y.' This behavior is correct as that property is not listed in the .d.ts file. (it is in the js library).
3) Then, if I remove the <code>as Word.Range</code> conversion from the first line, I'd expect that the warning would go away since I'd expect that the type check would go away. The actual behavior is that it looks like it is using a type check cache -- I removed the type conversion for the variable but it still states that the property doesn't exist on the object. I'd expect that message to go away as the code doesn't provide the object type. 

![capture](https://cloud.githubusercontent.com/assets/8527305/12442639/6e3cf968-bf06-11e5-8f6a-02cc4213c9f2.PNG)

_Copied from original issue: Microsoft/vscode#2119_

**Comment by dbaeumer** [comment]
_From @jrieken on January 20, 2016 9:34_

@weinand Please do not assign typescript items to me

**Comment by dbaeumer** [comment]
_From @MIchaelMainer on January 20, 2016 10:36_

This issue would only come up if the definitions are not in sync with the library.

**Comment by mhegazy** [comment]
@zhengbli can you take a look?

**Comment by zhengbli** [comment]
@MIchaelMainer What is the inferred type of the `imageRange` object? Namely if you hover on it, does the signature show type `any` or some other type?

**Comment by MIchaelMainer** [comment]
@zhengbli 
```imageRange``` shows as type ```Word.Range```.

![capture](https://cloud.githubusercontent.com/assets/8527305/12504347/6344b4ce-c091-11e5-8520-c794d1bffbf8.PNG)

If I close and reopen VSCode, ```imageRange``` still shows as type ```Word.Range```, and the original error message 'Property X does not exist on type Y.' still exists on the member without a definition.

Interesting. If I add the missing definition for the member to the .d.ts, save it, and then hover over the member, the red squiggle indicating an error remains, the error message 'Property X does not exist on type Y.' remains, and then the member description is appended to the hover text.  

![capture](https://cloud.githubusercontent.com/assets/8527305/12504513/ef6e8e42-c092-11e5-9af8-f6ca13b82259.PNG)

If I then close and reopen VSCode, if I hover over imageRange in ```var imageRange = context.document.getSelection();```, it still shows as type ```Word.Range```. The red squiggle is not present. If I hover over insertInlinePictureFromBase64, it shows the member description.

**Comment by zhengbli** [comment]
I believe it is not really a bug here. The reason why you get this error message is because typescript inferred the `ImageRange` object to be of the type `Word.Range`, which doesn't contain the property `Y`. This is supposed to be the right behavior. You don't really need to cast it using `as` to make the type system work.

However you said after you added the missing definition to the `.d.ts` and go back to the file you still saw the error. What if you do some editing in this file, does the error go away then? It may just have some delay between the editor and the server.
