### ISSUE TITLE
Encounter error TS1204 when work with newest "Tools for Apache Cordova".

### ISSUE THREAD

**Issue by hwzhou** [Microsoft/TypeScript#6558]
Today, I upgrade my "Tools for Apache Cordova" to version 14.0.60106.1, and upgrade TSC to version 1.7.5.
When I build my cordova app, I encountered error TS1204:
    Build: Cannot compile modules into 'es6' when targeting 'ES5' or lower.
My tsconfig.json files is like this:
```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "inlineSources": true,
    "target": "es6",
    "outDir": "../dist/scripts",
    "module": "es6"
  }
}
```
My project uese some ES6 features. If I change module to "amd", "system" other than "es6" or "es2015", the error disappears. But TSC emits other ES6 related errors.
My cordova app can build before I upgrade "Tools for Apache Cordova" and TSC. I try to uninstall TSC 1.7.5, and reinstall TSC 1.7.3. The error remains.

I create a new empty cordova project with typescript. Then change tsconfig.json file to the following:
```
{
  "compilerOptions": {
    "module": "es6",
    "target": "es6"
  }
}
```
The error still remains. Can anyone tell me how to fix this issue?

**Comment by mhegazy** [comment]
i can not get a repro for this. i created a new project using the TypeScript Apache Cordova template, updated the tsconfig.json to use your configurations, built (ran into the issue in http://microsoft.github.io/vstacoblog/2016/01/20/npm-issues.html first, but got past that). Build succeeds and no errors. 

please provide more information on how to reproduce this issue.

**Comment by hwzhou** [comment]
My steps are the followings:
1. Create a new cordova project: select TypeScript -> Blank App (Apache Cordova)
2. If you run build, you can see build success
3. Open file "tsconfig.json" under directory "scripts"
4. Change "target" to "es6"
5. Add another option "module", set value to "es6"
6. Build again, the error shows

My build environments are:
1. VS2015 Enterprise, version 14.024720.00 Update 1
2. Tools for Apache Cordova, version 14.0.60106.1 (the latest version)
3. TypeScript 1.7.5
4. Node.js 4.2.3

**Comment by mhegazy** [comment]
I see. the Cordova tools is overriding the configuration in the tsconfig by passing target=es5. The TSC compiler gets target=es5, and module=es6, which is an invalid configuration, that is why you get the error.

Pinging @mbraude for this issue.

**Comment by dlevine82** [comment]
This bug has been fixed in the Update 6 release of the Tools for Apache Cordova. However, the fix only applies to new projects created with the templates that shipped with Update 6. For those projects that were created by older versions of the tools, the fix is to edit the offending project's jsproj file, and to remove the following line:

<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />

**Comment by RyanCavanaugh** [comment]
@dlevine82 is there any external issue we can link to?

**Comment by mbraude** [comment]
@RyanCavanaugh no, sorry, our source and bugs are not available externally. Ping Dan and me internally if you want a TFS bug number.
