### ISSUE TITLE
Update error messages suggesting `tsconfig.json` to also suggesting `jsconfig.json`

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/TypeScript#6564]
Now we are adding support for `jsconfig.json`, it may be appropriate to update the error messages suggesting adding `tsconfig.json` to also suggesting `jsconfig.json` in some cases. The suggestion can be different depending on the context. 

For example, in the cases where creating a project is needed for `.js` files, "add a `jsconfig.json`" is easier to understand than "add a `tsconfig.json` file with `allowJs` set to `true`".

**Comment by mhegazy** [comment]
The only applicable message that has tsconfig.json is the module one, and i would argue we should just remove it now.
