### ISSUE TITLE
Duplicate symbols when using 'Go to Symbols' and 'Show all Symbols'

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#6566]
_From @egamma on January 22, 2016 9:10_

Setup
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "allowJs": true  
    },
    "exclude": [
        "node_modules"
    ]
}

Create a single file with a single function.

![symbols](https://cloud.githubusercontent.com/assets/172399/12506560/2c0b9f40-c0f0-11e5-80c4-efc124be7d65.png)

_Copied from original issue: Microsoft/vscode#2172_

**Comment by dbaeumer** [comment]
I looked into it and the problem is that the function myFunction appears two times in the result. In the root and under the module node. See screen shot

![capture](https://cloud.githubusercontent.com/assets/1931590/12506819/d1a8443e-c0f1-11e5-8468-4cd7b3f97a70.png)

May be this is a specific problem with commonjs which I use in the setup.

**Comment by mhegazy** [comment]
@vladima looked into it today, and the code generating the list is adding it twice. We should remove that duplication.

**Comment by andy-ms** [comment]
Appearing twice like that is (currently) the intended behavior. Suppose we have:

    function fun() {}
    class X {
        y() {}
        z() {}
    }

In Visual Studio's navbar, the top-level symbols (left part of the navbar) will be:

    global
        fun
        X

(with indent just showing VS's indent level, not actually a relationship in the returned data!)

For the children (right part of the navbar), we have:
* `global`'s child is `fun`
* `fun` has no children of its own
* `X`'s children are `y` and `z`

So `fun` appears twice: once as a top-level symbol, and once as a child of `global`. Top-level symbols have their children listed even if their children are also technically considered top-level.

We will need to discuss exactly what we want to be doing with navTo and navBar in the future. For that, see #7523.
