### ISSUE TITLE
Generated JS files not included when publishing to Azure web site

### ISSUE THREAD

**Issue by dsmeltz** [Microsoft/TypeScript#6570]
I'm running Visual Studio 2015 update 1 and TypeScript 1.7.6.   When attempting to publish to an Azure web site, the TypeScript generated javascript files are not included in the preview.  That being the case I'm assuming they wouldn't be published to the remote site.  

The generation of the .js and .map files works perfectly and I am able to run locally via IIS Express.

Is there a setting or something that needs to be tweaked or does 1.7.6 have a bug that is causing this?  The only work around I can come up with is including the js files in the project, which I don't really want to do.

**Comment by mhegazy** [comment]
@dsmeltz can you share your build log, with `/verbosity:diagnostic`.

**Comment by dsmeltz** [comment]
Here's the build log.  I currently have the generated *.js files included in the project.
[TSBuildLog.txt](https://github.com/Microsoft/TypeScript/files/101222/TSBuildLog.txt)

**Comment by dsmeltz** [comment]
Sorry, accidentally hit the Close button.

**Comment by mhegazy** [comment]
is there a chance we can get a sample project demonstrating the issue?

**Comment by dsmeltz** [comment]
I whipped up a stub project and the issue does not happen with that one.  I'm guessing there's something missing in the project file that I'm using.

**Comment by dsmeltz** [comment]
I think I found the magic.  This line:
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />

in the project file was near the bottom with the nuget stuff.  I moved it up, to a similar spot like my test project, and now things work.  Note, this new spot is above the TypeScript configuration nodes in the project file.  (So that line was below those nodes before I moved it.)

I've included the before and afters of my project file so you can see the differences.

[ProjBefore-NotWorking.csproj.txt](https://github.com/Microsoft/TypeScript/files/101327/ProjBefore-NotWorking.csproj.txt)
[ProjAfter-Working.csproj.txt](https://github.com/Microsoft/TypeScript/files/101328/ProjAfter-Working.csproj.txt)

**Comment by mhegazy** [comment]
the import needs to be below the configurations for the configurations to take effect. MSBuild is sequential when evaluating these targets and properties.

**Comment by mhegazy** [comment]
looks like the issue is expected, and moving the targets import to the correct location should solve the issue.

**Comment by ADefWebserver** [comment]
I ran into this same problem but I was able to fix it by installing the latest Typescript plug-in for Visual Studio.
