### ISSUE TITLE
Grammar (in the documentation) misses definition for ClassBody

### ISSUE THREAD

**Issue by CWBudde** [Microsoft/TypeScript#6577]
While writing an interpreter for TypeScript definition files I noticed that the grammar seems to be a bit incomplete. For several items I'm not sure whether it's just me or whether it is a logic inconsistency, but for the ClassBody a definition is definitely missing.

By comparing with older versions it seems it is identical to AmbientClassBody, but it should be written/marked as such.

I hope to report a few more inconsistencies if I am sure.

**Comment by RyanCavanaugh** [comment]
The spec grammar augments the ES6 grammar, which defines `ClassBody` http://www.ecma-international.org/ecma-262/6.0/#sec-class-definitions
