### ISSUE TITLE
Error too strict for `arguments` as parameter name.

### ISSUE THREAD

**Issue by mhevery** [Microsoft/TypeScript#6580]
```
export class Task {
  constructor(arguments: Args) {
    // In my opinion parameter name `arguments` is valid here.
  }
}
```

Error: `error TS1210: Invalid use of 'arguments'. Class definitions are automatically in strict mode.`

**Comment by DanielRosenwasser** [comment]
There's not much I can add that the error doesn't already tell you. Classes put you in a strict-mode context, where you can't name an entity `arguments`.
