### ISSUE TITLE
New Website Logo: MapLarge

### ISSUE THREAD

**Issue by GlennKirbo** [Microsoft/TypeScript#6584]
Please fill the following out:

- Name: MapLarge
- Homepage url: http://MapLarge.com
- Brand Guidelines/Licensing: http://maplarge.com/branding
- Logo: http://maplarge-public.s3.amazonaws.com/logo/MapLarge-Logo-Large.png

> Example:
>
> Name: Microsoft
> Homepage url: https://microsoft.com
> Brand Guidelines/Licensing: https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx
> Logo: https://news.microsoft.com/microsoft-news-center-photos/msft_logo_rgb_c-gray/

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
