### ISSUE TITLE
Read compilation settings from package.json

### ISSUE THREAD

**Issue by Brocco** [Microsoft/TypeScript#6590]
The tsconfig.json file was introduced around version 1.5 (or so) to store TypeScript compilation settings.

Proposal: leave configuration values being pulled from that file as the default but if it doesn't exist instead of just passing directly to no command options, attempt to pull the settings from package.json under a key of `typescript`

This is similar to the ideas posed in issue #4090 but instead of creating another config file it would just utilize a configuration file that already exists in a large number of projects.

**Comment by mhegazy** [comment]
while I do agree that package.json is a nice place to keep all your configuration, I do not see the value of adding yet another variation (we have 2 already, tsconfig, and command line arguments). so I would punt on this one for now. assuming we have enough user demand we can revisit.

**Comment by tivac** [comment]
https://github.com/Microsoft/vscode/issues/13786

I find this outcome pretty disappointing.

**Comment by pygy** [comment]
@tivac indeed... These config files are pure noise to me as well.

**Comment by CraigPhillips** [comment]
+1 - would get used on my team as well.
