### ISSUE TITLE
Typescript should infer types and catch null bugs

### ISSUE THREAD

**Issue by nojvek** [Microsoft/TypeScript#6593]
After reading through flow docs, it seems the biggest sell point is that it catches null and type bugs through type inference.

This compiles totally fine in typescript without any errors.

```
function len(x) {
  return x.length;
}

var total = len(8) + len(null);
```

Wouldn't it be really awesome if typescript did some inference and caught the null / type bugs ?
Since this would be a breaking change for some code bases put it under a commandline param --inferTypes

Since ts is a superset of js. If any developer is able to run tsc on top of their js codebase to catch static type bugs, it would really add a lot of net new developers for tsc. No?

**Comment by falsandtru** [comment]
Probably: https://github.com/Microsoft/TypeScript/issues/185

**Comment by nojvek** [comment]
Ha! I see there is a huge discussion already.
