### ISSUE TITLE
Confusing type error message in `concat`

### ISSUE THREAD

**Issue by elbarzil** [Microsoft/TypeScript#6594]
Typechecking this code:

    var x: string[] = ["A","B","C"];
    x = x.concat([1,2,3])

will throw up with

    Argument of type 'number[]' is not assignable to parameter of type 'string'.

This happens even without the `x =` assignment, and that shows that it would make more sense if the error was either of:

    Argument of type 'number' is not assignable to parameter of type 'string'.

or

    Argument of type 'number[]' is not assignable to parameter of type 'string[]'.

**Comment by ahejlsberg** [comment]
Agreed. The `Array<T>` interface declares the `concat` as two overloads:

```typescript
interface Array<T> {
    // ...
    concat<U extends T[]>(...items: U[]): T[];
    concat(...items: T[]): T[];
}
```

Those declarations were written before we permitted union types and used a generic constraint to work around some other issues. We need to update the declaration to this instead:

```typescript
interface Array<T> {
    // ...
    concat(...items: (T | T[])[]): T[];
}
```

This will also allow us to correctly check an argument list that mixes single elements and arrays, such as `numberArray.concat(1, [2, 3, 4], 5, [6])`. (Now, technically arrays can be nested to any level in the argument list, but declaring that would require an intermediate recursive generic type and would adversely affect type inference, so I would just keep it simple like the above.)

**Comment by SlurpTheo** [comment]
This is a good/simple correction that needs to happen (I figured I must have had a head cold Friday when the [playground](http://www.typescriptlang.org/Playground/#src=function%20A()%20%7B%0A%09const%20x%20%3D%20%5B1%5D.concat(2%2C%20%5B3%2C%204%5D)%3B%0A%7D%0A) kept complaining to me about `const x = [1].concat(2, [3, 4])`).

How about just "deprecating" `Array<T>::concat()` in TypeScript though? We have `Array<T>::push()` aided by `SpreadElementExpression`-awesomeness. What besides `number[]` could a code reviewer expect `x` to be here?
```typescript
const x = [1];
x.push(2, ...[3, 4]);
```
Clear. Now, as for:
```typescript
var x = [1];
x = x.concat(2, [3, 4]);
```
-OR- (my historical, personal problem with `concat`):
```typescript
var x = [1];
x.concat(2, [3, 4]);  // forgot that I have to assign the expression result back over x
```
Ick.


... I don't like `concat` (from Node.js v4.2.6 REPL):
```node
>
> [1].concat(2, [3])
[ 1, 2, 3 ]
>
> [1].concat(2, [3], [[4]])
[ 1, 2, 3, [ 4 ] ]
>
```

**Comment by elbarzil** [comment]
@ahejlsberg, there is a subtle point there with what `concat` is doing, where something like:

    var a: number[][] = [[1],[2]];
    a.concat([9]);

should be a type error because JS would add just `9`.  Hopefully the order of the `T` and `T[]` would make that work both for type errors and for the above (being an error too).  And there's no deeper nesting of `concat` arguments, IIRC...  (Otherwise this could be a problem in a way that I ran into with `flatten` in Typed Racket, BTW.)

@SlurpTheo: I don't know how things are done in JS VMs, but a spread that gets translated to `apply` might be either more limited or less efficient since it passes a huge number of arguments instead of keeping them in the original array.  That's with the obvious difference of `concat` being functional and `push` modifying the array.

**Comment by LPGhatguy** [comment]
I'll take a crack at this issue since I've already got the `lib.d.ts` generator setup on my system.

**Comment by LPGhatguy** [comment]
@ahejlsberg would removing the generic variant of `concat` be a breaking change?

**Comment by SlurpTheo** [comment]
So, the issue isn't simply that TypeScript isn't accepting enough input scenarios; it's that TypeScript as-is today is already type-incorrect when calling `Array<T>.concat()` for a `T` which is an array of more than one dimension... yikes!
```typescript
const x: number[][] = [[1]];
const y: number[][] = x.concat([2]);
```
Execution-result in JavaScript (from Node.js v4.2.6 REPL):
```node
>
> x = [[1]]
[ [ 1 ] ]
> x.concat([2])
[ [ 1 ], 2 ]
>
```

**Comment by DanielRosenwasser** [comment]
Hmm, the proposed fix doesn't actually address that either.

**Comment by LPGhatguy** [comment]
Is there a solution to that problem that wouldn't introduce extra typing complexity? JS's handling of `Array.concat` with arrays-of-arrays is a mucky edge case!

**Comment by DanielRosenwasser** [comment]
I discussed something with @RyanCavanaugh offline. I was wondering whether @sandersn's `this`-typing could help us here at all.

**Comment by sandersn** [comment]
What would concat's this be if not Array<T>? 
concat<U>(this:U, ...args:U|U[])
It's already

**Comment by DanielRosenwasser** [comment]
I had something like

```ts
interface Array<T> {
    concat<U, ArrayElement extends Array<U>>(this: ArrayElement[], ...args: (ArrayElement | ArrayElement[])[]): ArrayElement[];
}
```

which partially almost works.

**Comment by sandersn** [comment]
I don't think that buys us anything beyond Ander's first proposal. It just binds U locally instead of inheriting it from the containing class.

**Comment by DanielRosenwasser** [comment]
Thanks @LPGhatguy!

**Comment by SlurpTheo** [comment]
If `T` is `number[]` why should someone be allowed to pass in something of type `number[]` instead of requiring them to pass `number[][]`? The return type (if allowed to pass `number[]`) really should not be `number[][]` as the type of the array created by JavaScript is actually `(number | number[])[]`.

Why not be more restrictive/"limiting"/safe?
```typescript
interface Array<T> {
    // ...
    concat(...items: T[][]): T[];
}
```


Has there been talk of creating a ~`"use strict";` (`"use explicit;"`?) directive/flag to opt-in to only allowing type-safe/good programming and dump (more) historical JavaScript baggage? For example, I'd totally sign-up for more Ridiculousness Blocking™ right at the point of TypeScript compilation/Visual Studio IDE squiggly-feedback:
```javascript
let testStr = "ABCDEFG";
testStr[1] = "6";      // Ick, the 2nd character isn't updated

const testNumber = 1234;
testNumber[2];         // Ick, this returns undefined

let myNum = 1;
let myAnyString: any = "hi";
myNum += myAnyString;  // Ick, my "number" variable contains "1hi"
```
Not really sure how any such directive/flag would effect a definition file change like this, but seems similarish in my mind.

**Comment by LPGhatguy** [comment]
@SlurpTheo I feel that would be the job of a linter like `tslint`, not the base compiler.

**Comment by aluanhaddad** [comment]
@SlurpTheo I would prefer ```concat``` because it does not modify the original array. At any rate, the two are not equivalent.
