### ISSUE TITLE
Declaration merging issues with ambient modules

### ISSUE THREAD

**Issue by andrew-w-ross** [Microsoft/TypeScript#6595]
Hi I'm having a problem with writing ambient modules with declaration merging for the typings project (typings/typings#119).

I am trying to write decleration files for the [expect-jsx](https://github.com/algolia/expect-jsx) library. I've previously written the [expect declarations](https://github.com/andrew-w-ross/typings-expect) and have written the [expect-jsx declarations](https://github.com/andrew-w-ross/typings-expect-jsx). [When I try to use these definitions](https://github.com/andrew-w-ross/react-typescript-unit-testing) the decleration merging fails unless I add [a reference path to the module I want to merge with](https://github.com/andrew-w-ross/react-typescript-unit-testing/blob/master/typings/browser/ambient/expect-jsx/expect-jsx.d.ts#l3) directly in the module.  Does an ambient module have to have a direct reference to the module it's merging with? Isn't it enough to have both declerations referenced [by another file?](https://github.com/andrew-w-ross/react-typescript-unit-testing/blob/master/typings/browser.d.ts#l2-l3) Is this expected behaviour or a bug?

Thanks In Advance

**Comment by ahejlsberg** [comment]
See #4166.

**Comment by andrew-w-ross** [comment]
@ahejlsberg Just one question will this work if I use the nightly build?

**Comment by mhegazy** [comment]
@andrew-w-ross, yes. you can find more documentation in https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#augmenting-globalmodule-scope-from-modules

**Comment by andrew-w-ross** [comment]
@mhegazy Thanks a lot.
