### ISSUE TITLE
TypeScript 1.7.6 for Visual Studio 2015 - Release Notes

### ISSUE THREAD

**Issue by snerks** [Microsoft/TypeScript#6598]
I just noticed this version as being available since January 13 2016.

Is there any documentation available regarding the changes made in this version?

**Comment by RichiCoder1** [comment]
https://github.com/Microsoft/TypeScript/releases
Specifically: https://github.com/Microsoft/TypeScript/releases/tag/v1.7.5

VS Typescript Exception Version numbers are always a patch number higher than the official release.

**Comment by snerks** [comment]
Thanks
