### ISSUE TITLE
'tsconfig.json' errors should be file diagnostics, not compiler diagnostics

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6600]
If a `tsconfig.json` was successfully loaded, and there are contents, the compiler should supply some sort of error span within the file. That way, users can at least see that there is an error with the file itself.

**Comment by NaridaL** [comment]
![image](https://user-images.githubusercontent.com/10828874/30786944-c61df0fe-a17e-11e7-8645-c8027434904a.png)
This seems to be fixed, or am I misunderstanding this issue?

**Comment by mhegazy** [comment]
thanks @NaridaL !
