### ISSUE TITLE
Question: Grammar change to allow `,` in type annotations

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript#6604]
I couldn't find any issue regarding this, but the following works now: 

```ts
var foo: {a:any,b:any} // notice the `,` 
```

Was this change intentional. Should I consider it stable?

I see that the team still uses `;` e.g. check the interface members in https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts :rose:

**Comment by RyanCavanaugh** [comment]
Intentional and it won't be going away (it's been there quite a while actually!). See also #1971, #1969

**Comment by basarat** [comment]
Cheers :rose: Having been using TS for so long I didn't notice this till a new dev did it the new way intitively ... so good call :+1:
