### ISSUE TITLE
[Typescript] getting error when set 'experimentalAsyncFunctions' to true

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#6609]
_From @moostad on January 21, 2016 16:37_

I'm not sure it's related to #608 or not but typescript compiler stop working when i add experimentalAsyncFunctions to tsconfig.json file.

![ww](https://cloud.githubusercontent.com/assets/10362398/12486887/dc8a4316-c079-11e5-9bbc-79dc5fbaef56.gif)

_Copied from original issue: Microsoft/vscode#2154_

**Comment by dbaeumer** [comment]
@moostad from the message it looks like the plugin host got in trouble. Is this reproducible for you. If so, is the code some public so that we can try to reproduce this locally.

@alexandrudima does the plugin host error message ring a bell.

**Comment by dbaeumer** [comment]
_From @alexandrudima on January 22, 2016 10:52_

From the partial error message, it is not clear to me if the tsserver crashes and we report that error, or if the entire extension host crashed.

**Comment by dbaeumer** [comment]
_From @moostad on January 22, 2016 13:15_

@dbaeumer my apology, Ignore that message box, that's happened once on recording when I pushed shortcut-key for "Reload Window". The issue that I'm referring to is different and just to be clear i checked that in two different machine (Mac and Windows) with two different projects.
cc @alexandrudima 

![wwe](https://cloud.githubusercontent.com/assets/10362398/12511203/ba2aebbc-c124-11e5-9365-0bb6f31fba42.gif)

**Comment by dbaeumer** [comment]
_From @moostad on January 22, 2016 14:16_

@dbaeumer I just add a very simple repository for this issue. just clone https://github.com/moostad/vscodeTypescriptAsync.git and check ```app.tsx```

**Comment by dbaeumer** [comment]
@moostad Thanks for the repository. Now I see your problem. Since TS 1.7.x (which is bundled with VSCode 0.10.6) async await is an official feature and the flag got removed. However that should not make the tsserver to fail so drastically. 

Moving to the TypeScript team since there is nothing VSCode can do about it.

**Comment by mhegazy** [comment]
@zhengbli, tsserver should fail gracefully for invalid tsconfig files.

**Comment by zhengbli** [comment]
@dbaeumer With #8311, I'm adding a new event for config file errors. The event body contains information of the config file name, the file that triggers the error checking on the config file, and the error message. Would that be sufficient for VSCode?

**Comment by zhengbli** [comment]
As #8311 is now merged, the server now sends a `configFileDiag` event to the host if there are errors found in config files. This issue should be solved on our end.
