### ISSUE TITLE
_awaiter redundancy ?

### ISSUE THREAD

**Issue by pranaydutta89** [Microsoft/TypeScript#6610]
_awaiter function is getting generated in every file js in the project even the files in which i had not written and async await, is this a bug or it's designed like this only ??
![untitled](https://cloud.githubusercontent.com/assets/3788500/12548573/3c06505e-c37d-11e5-8354-16a6f7e82a06.png)

**Comment by valaxy** [comment]
I think it's designed, but the redundancy code is indeed not necessary in some conditions.

**Comment by vladima** [comment]
might be something that was addressed in #6495. Can you try our nightly builds available via `typescript@next` on `npm` and check if you still see the problem. If issue still can be reproduced - can  you please share a minimal repro code so we can make sure that this issue is fixed

**Comment by pranaydutta89** [comment]
i am using in visual studio will typescript@next will work in this  ??

**Comment by mhegazy** [comment]
if you are not build through nodejs, then `typescript@next` is not going to work for you, it is an npm package. The tools (tsc.exe) is release with the VS installer. We now have nightlly NuGet packages that map to `typescript@next` see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#official-typescript-nuget-package
