### ISSUE TITLE
Advanced Regular Expressions

### ISSUE THREAD

**Issue by 2426021684** [Microsoft/TypeScript#6617]
Using [XRegExp](http://xregexp.com) allows for more powerful regular expressions. It compiles advanced regular expressions down to normal javascript regular expressions. All existing regular expressions are compatible.
XRegExp provides the following features:
* Adds new regex and replacement text syntax, including comprehensive support for named capture.
* Adds new regex flags: s, to make dot match all characters; x, for free-spacing and line comments; n, for explicit capture mode; and A, for astral mode (full 21-bit Unicode matching).
* Provides a suite of functions that make complex regex processing easier.
* Fixes or helps you avoid the most commonly encountered cross-browser inconsistencies in regex behavior and syntax.
* Supports addons that add even more new regex syntax, flags, and methods. Offical addons support Unicode, recursive matching, and grammatical patterns.

(Taken from website)

Currently, using XRegExp is tedious.
```typescript
var regexp = XRegExp(String.raw`
    (\d)+
`, "xi")
```
It could be better if
```typescript
var regexp = /
    (\d)+
/xi
```
compiled to
```typescript
var regex = XRegExp(String.raw`
    (\d)+
`, "xi")
```
if a compiler flag was enabled.

**Comment by 2426021684** [comment]
It should be possible to compile the XRegExp regular expression a to a normal javascript regular expression with a xregexp property added for named captures.

**Comment by 2426021684** [comment]
Working on pull request

**Comment by DanielRosenwasser** [comment]
@2426021684 I just want to mention that I don't think we'd be willing to take that PR. We haven't actually discussed the issue, and this is extremely tied to a single library.

Additionally, this is an extension of expression level syntax, and we are strongly conservative on those changes unless it is tied to a promising ECMAScript proposal that looks like it will be ratified into the standard.

**Comment by 2426021684** [comment]
Would
```typescript
var regexp = /
    (\d)+
/xi
```
compiling to
```typescript
var regexp = new RegExp("(\d)+", "i")
```
using the XRegExp library at compile time instead of at runtime be better? Then XRegExp would only be needed at runtime if the regexp contained named captures.

**Comment by DanielRosenwasser** [comment]
I don't think that would be better. In general, we've been pretty lax about our regular expression parsing because there are various extensions that might exist, so we're fairly hands-off about it. We don't try to report errors if your regular expression is malformatted, and detecting various extensions is in the same league of complexity.

If XRegExps are so tedious, why not make a helper function?

```ts
function xregexp(t: TemplateStringsArray, ...args[]) {
    let result = t.raw[0];
    for (let i = 1; i < args.length; i++) {
        result += t.raw[i];
        result += args[i];
    }
    return XRegExp(result);
}
```

**Comment by 2426021684** [comment]
Ok
