### ISSUE TITLE
export types not found

### ISSUE THREAD

**Issue by amcdnl** [Microsoft/TypeScript#6622]
This might be a tad 'anti-typescript' but figured I throw it out anyway. I have a function that reads a array and dynamically creates exports like so:

```
const methods = ['head', 'options', 'get', 'post', 'put', 'patch', 'del', 'delete', 'all']
methods.forEach(method => {
  let methName = method.charAt(0).toUpperCase() + method.slice(1);
  exports[`http${methName}`] = route.bind(null, method);
});
```

For obvs reasons, TypeScripts complains on compiling about this:

```
[100;30m
src/api/ApplicationController.ts(1,22): error TS2305: Module '"src/common/routing"' has no exported member 'httpGet'.
```

Is there anything on the roadmap to do this type of dynamic / functional exports?

**Comment by WreckedAvent** [comment]
You could do something like this:

```typescript
const methods = ['head', 'options', 'get', 'post', 'put', 'patch', 'del', 'delete', 'all'];
const toExport: {[action: string]: () => void} = {};

methods.forEach(method => {
  let methName = method.charAt(0).toUpperCase() + method.slice(1);
  toExport[`http${methName}`] = route.bind(null, method);
});

export = toExport;
```

Whatever you type `toExport` to be should be what other files get from their `import`.

**Comment by amcdnl** [comment]
Interesting, thanks @WreckedAvent

**Comment by amcdnl** [comment]
@WreckedAvent  - I do other exports in the module, so I get a error saying like `export assignment can not be used with other export assignments...`

**Comment by mhegazy** [comment]
The shape of the module needs to be statically known. anything that is dynamic will not work. This is also the same semantics as ES6 modules. you are better of defining each as an export:

```ts
export const httpHead = route.bind(undefined, "head"); 
```

the other alternative, is you put these one level deeper inside the module:

```ts
export var exportedMethods: IMethods = {}

methods.forEach(method => {
  let methName = method.charAt(0).toUpperCase() + method.slice(1);
  exportedMethods[`http${methName}`] = route.bind(null, method);
});
```

**Comment by amcdnl** [comment]
@mhegazy thanks!
