### ISSUE TITLE
FunctionConstructor doesn't have a name property

### ISSUE THREAD

**Issue by tinganho** [Microsoft/TypeScript#6623]
I think there should exist typing for the name property below:
```typescript
class A {
}
A.constructor.name // error
```
If I recall it correctly the `name` property of a function is readonly.
```typescript
interface FunctionConstructor {
    /**
      * Creates a new function.
      * @param args A list of arguments the function accepts.
      */
    new (...args: string[]): Function;
    (...args: string[]): Function;
    prototype: Function;
    name: string; // added
}
```

**Comment by mhegazy** [comment]
the name property on interface `Function` is defined in lib.es6.d.ts. if you compile with `--target ES6` you should see it. alternatively you can define it locally:

```ts
interface Function {
    name: string;
}
```

we are working on fixing up the lib/target interaction for the next release. see https://github.com/Microsoft/TypeScript/issues/4168
