### ISSUE TITLE
Minor language error in the handbook

### ISSUE THREAD

**Issue by Romke-vd-Meulen** [Microsoft/TypeScript#6624]
From the [handbook](http://www.typescriptlang.org/Handbook#classes-privatepublic-modifiers), section "Parameter properties":

```
The properties let you can create and initialize a member in one step.
```

**Comment by mhegazy** [comment]
This issue was moved to Microsoft/TypeScript-Handbook#143

**Comment by mhegazy** [comment]
moved to the https://github.com/Microsoft/TypeScript-Handbook repo.
