### ISSUE TITLE
MsBuild compiler options don't support node modules properly

### ISSUE THREAD

**Issue by Tuesdaysgreen** [Microsoft/TypeScript#6625]
I'm trying to get the Angular2 beta to work with ASP.Net Web API but can either get intellisense with the Angular2 node libraries to work in Visual Studio, or compiling to work, but not both.  The project I'm referring to is here: https://github.com/Tuesdaysgreen/angular2-webapi

According to your [msbuild documentation](https://github.com/Microsoft/TypeScript/wiki/Setting-Compiler-Options-in-MSBuild-projects), you should specify "NodeJs" instead of "node" for the TypeScriptModuleResolution for node modules projects.  If I use this, then the Visual Studio editor is able to resolve the Angular2 node libraries, but if I try to compile, I hit this error: 

`Build: Argument for '--moduleResolution' option must be 'node' or 'classic'.	angular2-webapi	C:\git\angular2-webapi\angular2-webapi\VSTSC`

If I change TypeScriptModuleResolution to "node" instead of "NodeJs", then I can compile, but lose intellisense for the Angular2 node modules in the editor.  For example, when I hover over the error from this import statement, it says "cannot find module "angular2/core"

`import {Component} from 'angular2/core'`

Here's my TypeScript arguments from my csproj file:

`  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptJSXEmit>None</TypeScriptJSXEmit>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
    <TypeScriptModuleKind>System</TypeScriptModuleKind>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptExperimentalDecorators>true</TypeScriptExperimentalDecorators>
    <TypeScriptModuleResolution>NodeJs</TypeScriptModuleResolution>
    <TypeScriptEmitDecoratorMetadata>true</TypeScriptEmitDecoratorMetadata>
  </PropertyGroup>
`

It seems like the module resolution should always be "node" instead of "NodeJs", so I'm not sure if this is a VS bug, or an msbuild bug, or a TypeScript compiler bug but I figure I would start here.  Please let me know if you need any more info.

**Comment by mhegazy** [comment]
That is a bug. will get this fixed asap.

**Comment by mhegazy** [comment]
The change requires an update to the VS plugin in. it should be available with the next public release of TS.

**Comment by Tuesdaysgreen** [comment]
Wow. Thanks for the quick turnaround!  :)

**Comment by stasberkov** [comment]
Until this is fixed you can use the following workaround
```
  <PropertyGroup>      
    <TypeScriptModuleResolution>NodeJs</TypeScriptModuleResolution>
  </PropertyGroup>
   ...
  <Target Name="FixTsBuildConfiguration" BeforeTargets="CompileTypeScript" >
    <PropertyGroup>
      <TypeScriptBuildConfigurations>$(TypeScriptBuildConfigurations.Replace("--moduleResolution NodeJs", "--moduleResolution node"))</TypeScriptBuildConfigurations>
   </PropertyGroup>
  </Target>
```

**Comment by carvadero** [comment]
Thanks for the quick turnaround @mhegazy and thank you for the workaround @stasberkov :)

**Comment by petrelselina** [comment]
@stasberkov Hi, I am using typescript 1.7.6 and vs2015 14.0.24720.00 Update1, and I use your workaround but this error still showing, but someone resolve it. Is there something let this workaround no effect? Seems it didn't excuse. I set it like this:
_  <PropertyGroup>
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
    
    <TypeScriptModuleKind>System</TypeScriptModuleKind>
    <TypeScriptJSXEmit>None</TypeScriptJSXEmit>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
    <TypeScriptOutFile />
    <TypeScriptOutDir />
    <TypeScriptGeneratesDeclarations>True</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>False</TypeScriptNoEmitOnError>
    <TypeScriptMapRoot />
    <TypeScriptSourceRoot />
    <TypeScriptExperimentalDecorators>true</TypeScriptExperimentalDecorators>
    <TypeScriptModuleResolution>NodeJs</TypeScriptModuleResolution>
    <TypeScriptAllowUnreachableCode>true</TypeScriptAllowUnreachableCode>
  </PropertyGroup>_

...
<Target Name="FixTsBuildConfiguration" BeforeTargets="CompileTypeScript">
    <PropertyGroup>
      <TypeScriptBuildConfigurations>$(TypeScriptBuildConfigurations.Replace("--moduleResolution NodeJs", "--moduleResolution node"))</TypeScriptBuildConfigurations>
    </PropertyGroup>
  </Target>

**Comment by stasberkov** [comment]
@petrelselina make sure you reloaded project/solution after changes. Try close-open visual studio.

**Comment by petrelselina** [comment]
@stasberkov Yes, I try a lot, even uninstall vs and reinstall it, and still got this error.

**Comment by stasberkov** [comment]
@petrelselina typescript 1.8 is released, you don't need this workaround anymore.

**Comment by petrelselina** [comment]
@stasberkov Our project contains some problem with ts 1.8, so we use 1.7, I finally find the cause. Because I installed 1.8 before, and it leave some cache in C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript. So i delete them and reinstall 1.7, the workaroud worked fine. Thx anyway.

**Comment by busbina** [comment]
I installed the vs2015 1.8.6 plugin and I am still getting this. Any ideas?

**Comment by mhegazy** [comment]
@busbina this looks like a different issue. can fie a new issue and share your project file or tsconfig.json.

**Comment by sharathgg5** [comment]
![image](https://cloud.githubusercontent.com/assets/12963683/21213545/5981d686-c295-11e6-9595-0a9fbc0df639.png)

i cannot able to save and reload the csproj...
