### ISSUE TITLE
'jake LKG' creates platform-specific line-endings when generating JS

### ISSUE THREAD

**Issue by LPGhatguy** [Microsoft/TypeScript#6630]
On OS X, I ran `jake LKG` to update some files in `lib`, where all of the JS files have Windows-style (CRLF) line endings. After running the tool, the file was replaced with Unix-style (LF) line endings, which made for a messy diff when I went to stage hunks.

My system is set to checkout and commit line-endings as-is; is this an issue with the generator, or my git configuration?

**Comment by DanielRosenwasser** [comment]
While it's not a problem per se, it makes diffing the LKG difficult, just like you saw.

We should standardize the LKG with the `--newLine` flag. I'm partial to going with `--newLine LF`, but what are your thoughts @mhegazy?

**Comment by mhegazy** [comment]
Sounds reasonable. +1
