### ISSUE TITLE
Bad TS2346

### ISSUE THREAD

**Issue by srfrnk** [Microsoft/TypeScript#6638]
Following code gives compile error: `error TS2346: Supplied parameters do not match any signature of call target.`

As far as I get it all should work here.
Notice that if you comment '`foo(v:any):any;`' compile passes.

Happens also on http://www.typescriptlang.org/Playground

```
type cb = (v:any)=>any;

class Test {
	
	foo(v:any):any;
	foo(v:any,cb?:cb):any {
		
	}
	
	constructor() {
		this.foo({},(v)=>{return v;});
	}
}
```

**Comment by yortus** [comment]
The following variations both work:

```typescript
type cb = (v:any)=>any;

class Test1 {

    foo(v:any,cb?:cb):any { // removed both overloads
    }

    constructor() {
        this.foo({},(v)=>{return v;});
    }
}

class Test2 {

    foo(v:any):any;
    foo(v:any,cb?:cb):any; // Added this overload
    foo(v:any,cb?:cb):any {
    }

    constructor() {
        this.foo({},(v)=>{return v;});
    }
}


```

It seems all the overload signatures must be declared ambiently, in addition to the implementation. But in your example the implementation covers all the ambient signatures anyway, so they are not needed at all. That's just my hunch, maybe a team member can clarify what's going on.

**Comment by srfrnk** [comment]
This is a nice workaround @yortus - 10x.
I still think it's a bug since it doesn't look like it should go that way in the docs:
( see http://www.typescriptlang.org/Handbook#functions-overloads )
```
function pickCard(x: {suit: string; card: number; }[]): number;
function pickCard(x: number): {suit: string; card: number; };
function pickCard(x): any {
.
.
.
```

**Comment by RyanCavanaugh** [comment]
The implementation signature is not visible. Need to add this to the FAQ

**Comment by mhegazy** [comment]
added docs at: https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-supplied-parameters-do-not-match-any-signature-error
