### ISSUE TITLE
Provide a way to disable/control d.ts loading from npm modules

### ISSUE THREAD

**Issue by Sleepyowl** [Microsoft/TypeScript#6639]
Currently TypeScript compiler automatically loads d.ts files from node_modules.

While convenient, in some cases it leads to ambient definition clash, for instance, between angular2/../protractor.d.ts and jquery.d.ts.

Please provide a way to control this loading behaviour so I can exclude protractor.d.ts when building the project. 

At the very least, please provide an option to disable automatic .d.ts discovery and loading in npm packages.

**Comment by mhegazy** [comment]
use `--moduleResolution classic` to disable loading of typings from node_modules.

**Comment by mhegazy** [comment]
Can you share your setup, i would like to take a look at the modules causing the conflicts and see what we can do better there.

**Comment by Sleepyowl** [comment]
@mhegazy here you are
[typingproblem.zip](https://github.com/Microsoft/TypeScript/files/108222/typingproblem.zip)
```
npm i
.\node_modules\.bin\tsc
```
=>
```
node_modules/angular2/typings/angular-protractor/angular-protractor.d.ts(1679,13): error TS2403: Subsequent variable declarations must have the same type.  Variable '$' must be of type 'JQueryStatic', but here has type 'cssSelectorHelper'.
```

**Comment by mhegazy** [comment]
mmm, i do not see any conflicts here.

```cmd
c:\test\6639\typingproblem>.\node_modules\.bin\tsc --v
message TS6029: Version 1.7.5

c:\test\6639\typingproblem>tsc

c:\test\6639\typingproblem>echo %ErrorLevel%
0
```

I also do not think you need `typings\angular2\angular2.d.ts`, the angular package already have one.

**Comment by Sleepyowl** [comment]
@mhegazy could you please try running `tsc` from `.\node_modules\.bin` and not from PATH? I suspect that you ran `tsc` version 1.0 because that's where PATH points on Windows machines with VisualStudio installed (even if you have other versions).

Also thank you for pointing out that `typings/angular2/angular2.d.ts` is redundant. I'm aware of that (the file itself contains nothing but comment on that) I just forgot to remove it.

**Comment by mhegazy** [comment]
> could you please try running tsc from .\node_modules\.bin and not from PATH? I suspect that you ran tsc version 1.0 because that's where PATH points on Windows machines with VisualStudio installed (even if you have newer TypeScript versions).

i did, hence the `tsc --v` comment above. it tried your sample on `1.7.5`, and got no errors.

**Comment by Sleepyowl** [comment]
@mhegazy Please look again. You're calling tsc with --v key from `node_modules` but **on the next line** you call it from PATH.

**Comment by Sleepyowl** [comment]
> `c:\test\6639\typingproblem>tsc`
^^^^^^^^^^^^^^^^^^

**Comment by Sleepyowl** [comment]
@mhegazy Please disregard previous comments. It seems angular team fixed it in their recent release.  I don't get this error anymore after reinstalling angular2.

**Comment by Sleepyowl** [comment]
@mhegazy Here's the [sample](https://github.com/Microsoft/TypeScript/files/110241/typingproblem_v2.zip) to reproduce the issue just in case you need it. It uses angular2 2.0.0-beta.1 which has the problem. They've fixed it in beta 2.

**Comment by mhegazy** [comment]
aah.. thanks.. looks like an angular bug then. i think the compiler catches this correctly. they are overloading the `$` which will not work if you are using JQuery obviously.
