### ISSUE TITLE
Old Browser Support

### ISSUE THREAD

**Issue by mustafacoskuncom** [Microsoft/TypeScript#6640]
I want to learn how can I test my typescript/angular2 application runs on old Chrome, Firefox, Safari or IE? It takes so much time if I test one by one for all browsers different version... Maybe a few weeks I need to test these browsers. Is there any simple way of this process like ie tester tools or anyway? Someone can tell me, at least Chrome start Canary version, Firefox start 3.1.2 Version etc. Thanks for your helps and beneficial informations...

**Comment by RyanCavanaugh** [comment]
https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#3-do-you-have-a-question

Please don't ask general JavaScript questions on the TypeScript bug tracker.
