### ISSUE TITLE
Generics in indexers

### ISSUE THREAD

**Issue by pankleks** [Microsoft/TypeScript#6641]
Hi,

I was wondering why something like that is not possible:
```javascript
interface IDictionary<TKey, TValue> {
  [index: TKey]: TValue;
}
```

it tells me: index signature parameter must be string or number

I agree, but why I could not get this error when trying to use something else than string or number as TKey? Generics are analyzed at build time right? if so, this should be easy to find.

```javascript
  temp: IDictionary<number, ...>;
```
should work.

I could even do something like this, to be more precise:
```javascript
interface IDictionary<TKey extends string | number, TValue>
```

**Comment by RyanCavanaugh** [comment]
String indexers and number indexers have very different effects on the types they're contained in. They're not really interchangeable in any meaningful way, so it's pointless to make them able to be based on generic type parameters.

Practically speaking, you really have two types: `IDictionaryString<T> { [s: string]: T }` and `IDictionaryNumber<T> { [n: number]: T }`. There's nothing gained by making them generic.

**Comment by pankleks** [comment]
ok thanks.
