### ISSUE TITLE
Feature request: Code hinting/Intellisense for custom angularJS modules

### ISSUE THREAD

**Issue by jrieken** [Microsoft/TypeScript#6643]
_From @cozzbie on January 15, 2016 22:51_

Would be really lovely if VSC can support hinting and intellisense for custom angular modules created by devs in a project and not just the default angularJS support.

1: Create a new angularJS module e.g services in a separate file eg services.js
2: return to a separate file say controller.js and create a new controller.
3: reference service from controller and as one is typing code hints and intellisense popup showing related function created in service.

Thanks

_Copied from original issue: Microsoft/vscode#2052_

**Comment by mhegazy** [comment]
Supporting a new module kind is not a trivial undertaking. with angular2 moving to ES6 modules, this suggestion would be out of scope.
