### ISSUE TITLE
Salsa doesn't show any outline for this source code

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6644]
_From @alexandrudima on January 27, 2016 10:39_

Testing #2218 

No `jsconfig.json`

```javascript
exports.something = function() {
    return true;
}
```

![salsa-outline](https://cloud.githubusercontent.com/assets/5047891/12610905/7ee618e6-c4ea-11e5-8fa6-a766ee84f750.gif)

_Copied from original issue: Microsoft/vscode#2427_

**Comment by billti** [comment]
`something` is not available at the global scope. It is a property of an object. The symbol list generally doesn't show these. Why would this be expected here? Should exports get special behavior (even though they are symbols you cannot just directly reference).

**Comment by alexandrudima** [comment]
Well, imagine the following use-case: I have configured the module system to be commonjs. I am in a consumer of the module and do Ctrl-Space on the module. I get to see `something` plus possibly many other exported symbols. I then navigate to the producer module and want to iterate through its exported APIs. Not critical, but would be nice :)

**Comment by billti** [comment]
It seems reasonable. Things exported are conceptually 'top level' in how you thing about a module. Ryan, how hard would it be to surface CommonJS style exports as top level items for navigation?

**Comment by RyanCavanaugh** [comment]
@egamma  What API does VS Code use to populate the list?

**Comment by billti** [comment]
I believe it is the 'navbar' command [VSCode side](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/documentSymbolProvider.ts#L65) and [TypeScript side](https://github.com/Microsoft/TypeScript/blob/master/src/server/client.ts#L460)

**Comment by billti** [comment]
Note: Just stepped into it in the debugger - it is 'navbar', which ultimately calls into getNavigationBarItems.

**Comment by billti** [comment]
Need to come up with a design for this. This is neither a function declaration, nor a global value, so we don't put it in the nav bar today. Arguably we should treat exports specially here.

**Comment by billti** [comment]
Changing the navbar for TypeScript and JavaScript would be quite invasive at this late point for 1.8, but seeing as the JavaScript support is quite new, we can special case JavaScript behavior to temporarily make this experience better, then work to align the JavaScript and TypeScript (and 'navbar' and 'navto' logic) longer term.

After discussion with @egamma, @jrieken, and @mhegazy , I've come up with something like can be seen below. The logic is contained in [this commit](https://github.com/Microsoft/TypeScript/commit/080f639ff826be55c0381a9547dce07d2f846ce3) (not yet merged anywhere).

Basically any function/method is a container of other items. They are named by either the given name, or the property/variable they are assigned to (e.g. `exports.foo`), or just `<function>` if nothing else can be inferred. If a function expression is named `<function>` and does not contain other items, then this is not added to the navbar (to avoid pollution with lots of little lambda expressions). This also recognizes `define` calls and adds it as a module, with either the name given in the first arg, or the containing file name.

It needs a little tidy up (e.g. getters/setters aren't done yet) and hardening, but let me know if this looks good for your needs.

![jsnavbar](https://cloud.githubusercontent.com/assets/993909/13731068/e693a768-e91d-11e5-9c48-53285e3658d7.gif)

**Comment by jrieken** [comment]
:+1:

**Comment by egamma** [comment]
This looks good and it is a huge improvement :+1:

**Comment by warpdesign** [comment]
@billti nice! Will it solve problems with closures as well ? See #7134
