### ISSUE TITLE
Salsa is weird around assigning twice to the same member

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6645]
_From @alexandrudima on January 26, 2016 16:17_

Testing #2218

typescript@next version 1.9.0-dev.20160126

```javascript
function Person(age) {
    if (age >= 18) {
        this.canVote = true;
    } else {
        this.canVote = false;
    }
}
```

![image](https://cloud.githubusercontent.com/assets/5047891/12586444/8fde8fb0-c450-11e5-9df3-f735b0ad26c6.png)

_Copied from original issue: Microsoft/vscode#2385_

**Comment by vladima** [comment]
should this one be closed since it is fixed?

**Comment by mhegazy** [comment]
@RyanCavanaugh can you port this change to release-1.8

**Comment by RyanCavanaugh** [comment]
@vladima just keeping Fixed label on so I can keep track of which bugs have pending PRs and which don't

@mhegazy will do. It'll be one megaport of JSDoc bugs for sanity's sake.
