### ISSUE TITLE
Salsa cross TS-JS find all references does not work

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6647]
_From @alexandrudima on January 27, 2016 14:38_

Testing #2218 

`producer.js`:
```javascript
/**
 * @param {number} one
 */
exports.hi = function(one) {
	return 5;
}

exports.ciao = 'ciao';
```

`consumer.ts`
```typescript

import * as p from './producer';

class A {
	public something: boolean;
	public foo(): void {}
}

var x = p.ciao;
```

![salsa-ts-js-find-references](https://cloud.githubusercontent.com/assets/5047891/12616506/e1a97434-c50b-11e5-9fcc-564f6239c698.gif)

_Copied from original issue: Microsoft/vscode#2457_

**Comment by billti** [comment]
Same (subset) of code path for #6648

**Comment by zhengbli** [comment]
Should be fixed by https://github.com/Microsoft/TypeScript/pull/6632
