### ISSUE TITLE
Salsa: renaming in TypeScript does not rename in JavaScript

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6648]
_From @alexandrudima on January 27, 2016 14:33_

Testing #2218 

`producer.js`:
```javascript
/**
 * @param {number} one
 */
exports.hi = function(one) {
	return 5;
}

exports.ciao = 'ciao';
```

`consumer.ts`:
```typescript

import * as p from './producer';

class A {
	public something: boolean;
	public foo(): void {}
}

var x = p.ciao;
```

![salsa-ts-js-rename](https://cloud.githubusercontent.com/assets/5047891/12616400/3f548c78-c50b-11e5-8b02-b72d123a5b46.gif)

_Copied from original issue: Microsoft/vscode#2456_

**Comment by billti** [comment]
@zhengbli Did you have a fix for this already?

**Comment by zhengbli** [comment]
Yes, the fix is in a PR at https://github.com/Microsoft/TypeScript/pull/6632

**Comment by alexandrudima** [comment]
Great! :+1:
