### ISSUE TITLE
Should not suggest "caller" in strict mode as it causes TypeError

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6649]
_From @alexandrudima on January 27, 2016 14:22_

Testing #2218

```javascript

function restricted()
{
	"use strict";
	restricted.ca
}

console.log(restricted());

```

![image](https://cloud.githubusercontent.com/assets/5047891/12616078/86662484-c509-11e5-9926-be664d667425.png)

Since we're at it, it could also highlight the `caller` and `arguments` below with a squiggly indicating a `TypeError`:

```javascript

function restricted()
{
	"use strict";
	restricted.caller;    // throws a TypeError
	restricted.arguments; // throws a TypeError
}

console.log(restricted());
```

_Copied from original issue: Microsoft/vscode#2454_

**Comment by billti** [comment]
This is beyond syntax and type checking. TypeScript also doesn't error here. This would be a considerable new feature to add.

**Comment by RyanCavanaugh** [comment]
Not clear anyone is making this mistake
