### ISSUE TITLE
Salsa does not discover properties defined with Object.defineProperty

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6651]
_From @alexandrudima on January 27, 2016 13:46_

```javascript
var obj1 = {};
Object.defineProperty(obj1, "x", { value: 42, writable: false });

obj1.
```

![image](https://cloud.githubusercontent.com/assets/5047891/12615226/ba5d10fe-c504-11e5-9b30-f8cec9b41cbe.png)

_Copied from original issue: Microsoft/vscode#2451_

**Comment by billti** [comment]
Per TypeScript semantics, we see `obj1` as a `{}`, and don't support augmenting it (e.g. we also don't recognized adding via `obj1.x = ...`).

The type of `obj1` can be explicitly set via a JsDoc comment. If you feel expando and defineProperty support is critical for Salsa, please reopen.

**Comment by alexandrudima** [comment]
:+1:
