### ISSUE TITLE
Salsa: "Implicit globals" leak into member completions but not global completions?

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6654]
_From @alexandrudima on January 27, 2016 13:34_

Testing #2218 

IMHO member completions should get less suggestions than the global completions, not the other way around:

```javascript
function f() {
	// helloWorld leaks from here into the global space?
	if (helloWorld) {
		return 3;
	}
	return 5;
}

// helloWorld is proposed here
// Number(3).

// helloWorld is not proposed here
// hello
```

![salsa-member-completion](https://cloud.githubusercontent.com/assets/5047891/12614921/eea75ac4-c502-11e5-8250-9c2f1fb2ae2d.gif)

_Copied from original issue: Microsoft/vscode#2447_

**Comment by RyanCavanaugh** [comment]
@billti how should we fix this?

* Add all tokens in the current file to the global completion list. -- or --
* Remove token-based items from the member list (when it is non-empty)

**Comment by mhegazy** [comment]
the later is an problem when we guess things wrong:

```ts
var x = {};
x.a = 0;
x.b = "string";
x.|
```

The earlier seems like a more consistent approach. VSCode should show these completions as a different icon. the CompletionEntry.kind field should be the marker here, also CompletionEntry.sortKey should push these all to the bottom.

**Comment by egamma** [comment]
>VSCode should show these completions as a different icon.

@mhegazy we have already changed the icon in our latest:
![proposal2](https://cloud.githubusercontent.com/assets/172399/12647353/011b9b16-c5d5-11e5-814b-686a8e1e4ea3.png)
.

**Comment by pflannery** [comment]
@RyanCavanaugh Did this fix scope variables leaking in to instance completions? 

I just got the latest vscode 0.10.10 and now see this type of polluted intellisense all over my js apps:

![image](https://cloud.githubusercontent.com/assets/1727302/13584736/ccf60f52-e4af-11e5-90d1-3d1a01b29497.png)

I would only expect to see similar to this

![image](https://cloud.githubusercontent.com/assets/1727302/13585087/a7cd7736-e4b1-11e5-97a2-b7413c3ef1d3.png)

Source:
```js
class SomeClass {
  constructor(param1, param2, param3) {
    this.param1 = param1;
    this.param2 = param2;
    this.param3 = param3;
  }
  
  doSomething() {
    
  }
}
var a, b, c, d, e;
var instance = new SomeClass(1, 2, 3);
```

**Comment by billti** [comment]
This is by design. We show the properties we know to exist with a definitive icon at the top, and the rest of the identifiers in the file afterwards. In the more recent builds the assignment to `this.` in the constructor would be recognized also (e.g. as shown below on my machine).

![constructor](https://cloud.githubusercontent.com/assets/993909/13585448/c010e440-e470-11e5-88a0-d4dd77010a4f.png)

**Comment by pflannery** [comment]
@billti thanks for the info. Is there a way to turn of this noise?

**Comment by mnpenner** [comment]
@billti Is there any way to hide the extraneous identifiers? I don't see how `x.Foo` or `x.get` would ever make sense.
