### ISSUE TITLE
Salsa does not understand parameters with properties JSDoc

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6661]
_From @alexandrudima on January 27, 2016 12:57_

Testing #2218 

Please see http://usejsdoc.org/tags-param.html#parameters-with-properties

```javascript
/**
 * Assign the project to an employee.
 * @param {Object} employee - The employee who is responsible for the project.
 * @param {string} employee.name - The name of the employee.
 * @param {string} employee.department - The employee's department.
 */
function helloWorld(employee) {
    employee.
}
```

![image](https://cloud.githubusercontent.com/assets/5047891/12614058/d6fbb014-c4fd-11e5-9932-69ac3ecb53c3.png)

_Copied from original issue: Microsoft/vscode#2441_

**Comment by billti** [comment]
We support the object literal format, or a type name, currently for a param. There are several JsDoc variations and formats in use, and we have tried to pick the most common initially, and then expand if/when feedback indicates a pattern is common enough to support, or is needed to fill a gap.

Please reopen if you believe this is a common format for your users and we should add support. Else we'll add later based on demand (or a ready to go pull request :wink: ).

**Comment by alexandrudima** [comment]
Works for me :+1:

**Comment by astral-sa** [comment]
Oh darn, I was just about to report this very issue now that https://github.com/Microsoft/TypeScript/issues/6825 is fixed and I ran into it myself. Is there somewhere else I should go to request support for this?

As far as I'm aware, it's a pretty common pattern for describing properties of object params:
- http://usejsdoc.org/tags-param.html#parameters-with-properties
- http://stackoverflow.com/questions/6460604/how-to-describe-object-arguments-in-jsdoc

P.S. Thank you all for your awesome work!

**Comment by RyanCavanaugh** [comment]
@astral-sa we'll revisit this if we decide to increase the set of JSDoc constructs we understand.

If you're feeling ambitious and want to send a PR to implement it, I'd be happy to take a look.

**Comment by abgivant** [comment]
Has there been any additional work on this? This is the pattern I use for documenting object properties as well, so it would be great to be able to get intellisense from it.

**Comment by mhegazy** [comment]
@abgivant the example in the OP is working locally for me, as well as using it inside an object literal declaration. if you have a different pattern that is not working please file a new issue and give us more details to be able to diagnose the problem.

**Comment by abgivant** [comment]
I just tried it again, and the object literal syntax is working, but the separately defined properties are not working for me. I tried on both the most recent stable build, as well as on the most recent insiders build. I am also updated to the latest version of TypeScript.

Here are my examples:

![image](https://cloud.githubusercontent.com/assets/3431954/17941227/0a0c0f04-69f8-11e6-9376-f15203d665d5.png)

![image](https://cloud.githubusercontent.com/assets/3431954/17941232/0f7ab620-69f8-11e6-9ee0-bbf06462c2da.png)

Also, and this isn't really a problem, but I noticed that the object literal syntax doesn't work when it is broken up over multiple lines.

![image](https://cloud.githubusercontent.com/assets/3431954/17941334/74482574-69f8-11e6-96f1-d2777a68642c.png)

**Comment by mhegazy** [comment]
Please file another issue for the multiline case.

**Comment by abgivant** [comment]
Just opened #10535 for the multiline issue.

**Comment by Wenzil** [comment]
+1. We are facing the same problem here.

**Comment by errorx666** [comment]
So the [JSDoc standard way](http://usejsdoc.org/tags-param.html#parameters-with-properties) of specifying parameter properties is broken, but it's OK because the [non-standard object literal](https://github.com/Microsoft/TypeScript/issues/10535#issuecomment-242536308) syntax works?
