### ISSUE TITLE
Salsa type inference should find or types

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6663]
_From @alexandrudima on January 27, 2016 10:49_

Testing #2218 

```javascript
function a1() {
    return 5;
}

function a2() {
    if (1) {
        return 5;
    } else {
        return '5';
    }
}
```

Hovering over a1() shows its return type is `number`. Hovering over a2() shows its return type is `any`. IMHO it should show `number|string` -- maybe this inference code was written before or types were introduced?

_Copied from original issue: Microsoft/vscode#2431_

**Comment by billti** [comment]
In TypeScript this is an error of "unknown type". If the types are relatable, we return the type that is the super-type of all return expressions. We explicitly don't try and synthesize a type as this code pattern often indicates a bug.

**Comment by mhegazy** [comment]
@billti, we should reconsider this one. the reason we stop this in TS, is we want ppl to go look at their code and make sure this is what they really intend. for JS, we do not have this error, so it seems unjustified to just block inference from the return types.

**Comment by RyanCavanaugh** [comment]
We could easily make the checker say that the function returns `number|string` (instead of `unknownType`) but still issue an error. I don't think that would have any meaningful impact to TypeScript. Seems reasonable?

**Comment by billti** [comment]
I'm wary of adding complexity to the code base and diverging the TypeScript and JavaScript behavior too greatly. If it's simple enough that the benefit outweighs the cost, sounds good to me.

**Comment by alexandrudima** [comment]
Thank you! :+1:
