### ISSUE TITLE
Salsa unreachable code detected is not so smart

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6665]
_From @alexandrudima on January 27, 2016 10:45_

Testing #2218 

```javascript
function xx() {
    if (true) {
        return 5;
    } else {
        return '5';
    }
}
```

This shows a squiggly on the second return saying 'Unreachable code detected'.

The following or any other const expression does not:
```javascript
function xx() {
    if (true || true) {
        return 5;
    } else {
        return '5';
    }
}
```
same with `if (!false)` or `if (!true)`, etc.

_Copied from original issue: Microsoft/vscode#2430_

**Comment by egamma** [comment]
_From @alexandrudima on January 27, 2016 10:46_

Also doesn't work with `if(1)` or `if(0)` -- it appears to be hard coded for true or false

**Comment by alexandrudima** [comment]
ok :)

**Comment by RyanCavanaugh** [comment]
Sorry, forgot to leave a comment. We intentionally don't compute these complex expressions because it's pretty common to write e.g. `if(true || oldCondition)` while debugging
