### ISSUE TITLE
Salsa formatting gives overlapping edits in this case

### ISSUE THREAD

**Issue by egamma** [microsoft/TypeScript#6666]
_From @alexandrudima on January 27, 2016 10:57_

Testing #2218 

``` javascript
function a1() {
        try {
                        throw new Error('x');         } catch(x) {}
}
```

Right click > Format

Observe in the developer console. This happens when the passed in edits are invalid or overlap (touch):
![image](https://cloud.githubusercontent.com/assets/5047891/12611500/1bcb5c46-c4ed-11e5-8154-7418ec1255d4.png)

_Copied from original issue: Microsoft/vscode#2435_

**Comment by billti** [comment]
@vladima @zhengbli Same as prior issue. Is this Salsa specific, or does TypeScript exhibit this also?

**Comment by zhengbli** [comment]
FYI I saw this problem on `.ts` files too.

**Comment by mjbvz** [comment]
Just tested in VS Code 1.74 and this seems to be working fine now
