### ISSUE TITLE
Formatting honours tab vs spaces setting only sometimes?

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6667]
_From @alexandrudima on January 27, 2016 13:6_

Testing #2218 

I have the following settings:
```json
// Place your settings in this file to overwrite default and user settings.
{
	"typescript.tsdk": "C:\\Alex\\salsa\\node_modules\\typescript\\lib",
	"editor.tabSize": 4,
	"editor.insertSpaces": false
}
```

If I have a function indented with 5 spaces, and choose format, the 5 spaces get replaced with a tab:
```javascript
function howdyAgain(name) {
     return 'hi';
}
```

If I have the same function indented with 4 spaces, and choose format, the 4 spaces do not get replaced with a tab:
```javascript
function howdyAgain(name) {
    return 'hi';
}
```

_Copied from original issue: Microsoft/vscode#2443_

**Comment by billti** [comment]
@zhengbli @vladima Any idea what's going on here? Do we see the same problem in TypeScript code?

**Comment by zhengbli** [comment]
I saw this problem on `.ts` files too.

**Comment by mhegazy** [comment]
duplicate of #2306
