### ISSUE TITLE
Salsa type inference could pass through argument types

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6668]
_From @alexandrudima on January 27, 2016 10:54_

Testing #2218 

Would be nice if it knew the result is a string.

![image](https://cloud.githubusercontent.com/assets/5047891/12611403/aacf6550-c4ec-11e5-82cb-f7c6b700157c.png)

_Copied from original issue: Microsoft/vscode#2433_

**Comment by billti** [comment]
We are using the TypeScript inference system, and have no plans to add call-site inference at this point. (Or inferring a generic signature of the function). The param should be given a type via JsDoc (just as TypeScript params require a type to not be any).

If this become a major pain-point and source of feedback, we can revisit.

**Comment by mhegazy** [comment]
If we decide to solve this, we should do some analysis on the type flow of inputs to outputs. if we can "detect" that the parameter types are manifested in the return type, and there were no type annotation (JSDoc), we should treat the function as generic.

**Comment by alexandrudima** [comment]
Agreed, JSDoc should do the trick here, I just thought it would be a cool idea to infer generics too, but I'm totally fine with that being outside the scope. :+1:
