### ISSUE TITLE
[Salsa] load .js files from node packages

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6670]
_From @alexandrudima on January 27, 2016 14:48_

Testing #2218

File structure:
* node_modules
  * something2
    * main.js
    * package.json
* consumer.js

`node_modules/something2/main.js`: 
```javascript
var f = function() {
	if (true || true) {
		return 5;
	}
	return '5';
}
exports.x = f();
```

`node_modules/something2/package.json`:
```json
{
	"name": "something2",
	"version": "0.0.0",
	"main": "./main.js"
}
```

`consumer.js`
```javascript
var s2 = require('something2');
s2.
```

> Observe: `x` is not suggested for `s2`

_Copied from original issue: Microsoft/vscode#2459_

**Comment by billti** [comment]
We could potentially add this discovery to JavaScript and TypeScript resolution. For TypeScript we would still honor the 'typings' property first if present.

@vladima any thoughts?

**Comment by billti** [comment]
A concern is this could lead to an explosion of files loaded by following the 'require' chain through the dependencies. It could be possible that only following the chain a certain 'distance' from the program root files would give a usable experience however (e.g. load 'something2' above, but don't try and load anything that it 'require's).

The goal is that our automatic typing acquisition would auto-detect and download any Node modules installed by the user, and that these typings would be used and provide a richer definition than could be inferred from the JavaScript anyway.

On the other hand, this would be relatively simple to add (we already search the node_modules hierarchy and crack the package.json to look for TypeScript definitions), and would add value in situations where .d.ts files aren't present or can't be automatically obtained (e.g. there aren't any for that library, the user is offline, etc.). There are a number of reasons there may not be a typing published (e.g. it may be in the 'long tail' of packages, it could be a private NPM repository inside an enterprise, it could be under development and hasn't been published yet, etc...), but this is likely dwarfed by the usage of the most common modules that typings do exist for.

Our current decision is to get the automatic typing acquisition feature added, and then see if this is still a pain point that needs addressing.

**Comment by massimocode** [comment]
@mhegazy @billti I believe that the automatic typing acquisition is not sufficient for the exact same reasons you state above: "There are a number of reasons there may not be a typing published (e.g. it may be in the 'long tail' of packages, it could be a private NPM repository inside an enterprise, it could be under development and hasn't been published yet, etc...)"

Just to point out my colleague is now using Tern.JS with Sublime text and gets useful intellisense for all of our private NPM repository modules. It would be useful if it was at least configurable so that we could enable it ourselves.

Like you say, the majority of packages have typing files available. We could rely on those where available and perform analysis on the packages for which typing files aren't available.

**Comment by billti** [comment]
Pull request #7075 is out for this currently.

**Comment by mattflix** [comment]
Please keep in mind that node_modules folders aren't "only" used for external packages.  Rather, they are an intergral part of _overall_ module resolution when using Node, Browserify, Webpack, or any other of these _extremely popular_ tools that implements the Node module resolution algorithm.

So all these requests to better support "Node" or packages isn't necessarily about "getting typings" or supporting NPM dependencies only.  This is about Javascript project organization and modular programming using a system hierarchical dependencies afforded by the de facto standard Node module resolution algorithm.

For example, an extremely useful Javscript project structure is as follows:

- ${workspaceRoot}/
  - src
    - node_modules
      - foo
        - index.js
      - bar
        - index.js
    - main.js

Here, note that src/node_modules has _nothing to do with_ external packages or NPM.  There is no use of NPM in sight.  It is simply a place to put application-private modules that can be found by each other and throughout the rest of the application code _by name_ (e.g., require("foo"), import "bar", etc.) with _zero configuration_ and complete avoidance of "../../../.. hell".

Going further, of course, if any external, published modules are required, then a node_modules folder can simply be added at the top-level:

- ${workspaceRoot}/
  - node_modules/
    - (modules installed via npm)
  - src
    - node_modules
      - foo
        - index.js
      - bar
        - index.js
    - main.js

And then all of the application code, including the private modules application code, equally, can also begin referring to the external dependencies by name.

This is the beauty of the Node module resolution algorithm.  Hierarchical dependencies.  Please try to support it as a first-class citizen.

**Comment by billti** [comment]
#7075 has been merged in now. Closing this.
