### ISSUE TITLE
tsc doesn't honor a 'jsconfig.json' when it is present

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6671]
The workaround is to use `tsc -p jsconfig.json`

**Comment by mhegazy** [comment]
tsc should only know about tsconfig.json. the server, additionally knows about `jsconfig.json`, just because it supports a JS edition scenarios. i do not think there is a scenario for a JS-only project to use the typescript compiler, unless they are int he middle of a migration, and renaming jsconfig.json to tsconfig.json or using `--p` seems like a reasonable solution.

**Comment by egamma** [comment]
What about a project that is using ES6 but wants to use tsc to down level compile to ES5?
Or a project that is using JSX and wants to use tsc to compile the .jsx files?

**Comment by mhegazy** [comment]
what is wrong with just using `tsconfig.json` then? it does the same thing.

**Comment by egamma** [comment]
Undersood, but I've setup my project using a jsconfig.json file, since it JS only.

**Comment by mhegazy** [comment]
here is how i am thinking about it. you can either be:
- a TS user already, so tsconfig.json makes sense to you, so no-op here
- a JS user, who do not really care about how the editor provides the JS intellisense, or wheter it uses TypeScript in the back end or not, and want to provide some additional configurations to the editor (e.g. want to use ES8 decorators), so tsconfig.json seems like an intrusion here, as you do not really care about the TS compiler. so having the server understand jsconfig.json seems like the right thing to do.
- a JS user who is experimenting with TS or in the process of migration. for These you can copy/rename your jsconfig.json to tsconfig.json, decide what you want to do with your output from ts compiler, etc.. but this seems like a one time thing, so renaming is not a problem.


My concerns are:
- it is a breaking change to make the tsc compiler crawl for tsconfig; some code bases that use VSCode today have both tsconfing.json and jsconfig.json to allow for viewing the output JS files, and for these, their build will start behaving differently with this change.
- it is yet another concept we need the compiler users to learn about. and mental complexity from having documentation with jsconfig.json and tsconfig.json, and then when do you use one or the other, what is better to which project questions, etc..

**Comment by billti** [comment]
I think we should locate config files the same way in the compiler we do in the language service, else I'm going to have a folder open in the editor getting one behavior, then at the command-line running `tsc` in the same folder get different behavior.
