### ISSUE TITLE
Salsa - fails when installed modules are not excluded

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6673]
"version": "1.9.0-dev.20160127"

- git clone https://github.com/Microsoft/vscode-samples.git
- cd node-express-javascript
- open code on this folder
- open app.js
- hover over an identifier -> you get type information.

All is good, but now:
- switch to the terminal
- npm install   <== @billti this step was missing when I first reported problems with this project
- open code on this folder (or reload the window)
- open app.js
- hover over an identifer -> you get no type information
- edit the jsconfig.json so that the node_modules folder is exclude:
```json
{
	"compilerOptions": {
		"target": "ES5",
		"module": "commonjs"
	},
    "exclude": [
        "node_modules"
    ]
}
```

- Restart Code.
- open app.js
- hover over an identifier -> you get type information.

These steps illustrate that Salsa has issues digesting the node_module.

**Comment by egamma** [comment]
Much simpler steps.
`typescript@1.9.0-dev.20160128`

- create a file hello.js
```javascript
function hello() {   
}
```
- hover over hello and you get type information
- `npm install gulp`
- restart code
- hover over hello and you get type information.
- add jsconfig.json
```json
{
    "compilerOptions": {
       "module": "commonjs"
    }
}
- restart code
- hover over hello and you do **not** get type information

**Comment by billti** [comment]
Trying to look into this currently...

**Comment by billti** [comment]
Got a simpler repro for this and worked with @RyanCavanaugh on a fix. He'll get a pull request out for this shortly.

**Comment by billti** [comment]
Crash is fixed with private changes, but below scenario caused 'gulp' to still return no intellisense (assigning an identifier to `module.exports`, instead of a literal). Please fix also:

**fails to export correctly**
```javascript
// mod.js
var exp = {a: true, b: 42};
module.exports = exp;
```

**this pattern works**
```javascript
module.exports = {a: true, b: 42};
```

**Comment by egamma** [comment]
great, thanks. I'll update the VS Code release notes.
