### ISSUE TITLE
Salsa - reference search across commonjs fails

### ISSUE THREAD

**Issue by egamma** [Microsoft/TypeScript#6682]
In the following setup:

version: `typescript@1.9.0-dev.20160127`

jsconfig.json
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5"
    },
    "exclude": [
        "node_modules"
    ]
}
```

circle.js
```javascript
const PI = Math.PI;

exports.area = function (r) {
  return PI * r * r;
};
```
geometry.js
```javascript
const circle = require('./circle.js');
console.log( `The area of a circle of radius 4 is ${circle.area(4)}`);
```

Go to definition from geometry.js `area` works and navigates to the file circle.js.

Doing a reference search from circle.js exports.area doesn't result in any references.

When changing the code of circle.js to:
```javascript
const PI = Math.PI;

export function area (r) {
  return PI * r * r;
};
```
then the reference search returns the correct result.

**Comment by zhengbli** [comment]
This should be fixed by #6632
