### ISSUE TITLE
TSX closing tags indentation still wrong after code format using ntypescript 1.201601272211.1

### ISSUE THREAD

**Issue by bgrieder** [Microsoft/TypeScript#6687]
This is a follow up of issue: https://github.com/Microsoft/TypeScript/issues/3838 because ntypescript 1.201601272211.1 does not fix the issue

As referenced in https://github.com/TypeStrong/atom-typescript/issues/823, @basarat released atom-typescript 8.2.0 in an attempt to fix the issue.

atom-typescript  8.2.0  uses ntypescript 1.201601272211.1 as can be seen from here  https://github.com/TypeStrong/atom-typescript/blob/master/package.json#L63

![tsx-formatting](https://cloud.githubusercontent.com/assets/797684/12636782/396673b4-c590-11e5-9477-af790a9fa27a.gif)

The first "wrapping" closing tag (`div`) is systematically moved to one full ident to the right. 
Parent closing tags "follow"

**Comment by mhegazy** [comment]
//CC @SaschaNaz

**Comment by SaschaNaz** [comment]
This works on Visual Studio with TS 1.8.1 beta. Is this an atom-specific issue?

![tsx](https://cloud.githubusercontent.com/assets/3396686/12678800/f8ce6046-c6e3-11e5-962d-00b987d31cea.gif)

**Comment by basarat** [comment]
@SaschaNaz Sorry about that :rose: Its working for me as well 

![render](https://cloud.githubusercontent.com/assets/874898/12679184/e2fdfff2-c6f6-11e5-8ed4-529257d02223.gif)


@bgrieder perhaps your atom-ts didn't update? 

PS: atom-ts uses the language service as it is. No fancy formatting magic different from the official one :rose:

**Comment by bgrieder** [comment]
@basarat mhhh... definitely not working for me.
Interference with another plugin ? I will run a few tests

![format](https://cloud.githubusercontent.com/assets/797684/12679391/39c9339a-c6a4-11e5-9d04-d7dac4cf11f6.gif)

**Comment by basarat** [comment]
@bgrieder what keyboard shortcut are you using, is it `alt-cmd-l`? Perhaps it is some other package. Try disabling everything except atom-ts / linter :rose:

**Comment by bgrieder** [comment]
@basarat I have disabled all plugins (but atom-ts and linter) and still get the same behaviour, which is the same one I was getting with the previous version and I am getting with VS Code 0.10.6. We have tested on another developer machine: VS Code 0.10.6 also behaves incorrectly however his atom with the new 8.2.0 plugin works as expected.

The only difference we could see between his machine and mine is that I have TS 1.7.5 installed globally. I removed it but there was no improvement.

In any case, this must be linked to my set-up. I have a feeling that the atom-typescript plugin is picking up a 1.7.5 tsc version somewhere. If I find out what it is, I will report back on this thread but you can consider this issue closed

Thank you for your help

**Comment by alexgorbatchev** [comment]
I'm still having this issue. I maintain [gulp-tsfmt](https://github.com/alexgorbatchev/gulp-tsfmt) and can't get the closing tag to align properly using the TypeScript 1.8.9 API.

The strange thing is that in VSCode "Format Code" function what one expects well. I tried searching through the code and found the usage of `formatDocument` ([here](https://github.com/Microsoft/vscode/blob/11ea2b653ea7a907caa3fb7cc10a7b46269ea524/src/vs/editor/contrib/format/common/format.ts#L46)). I'm using `TypeScript.formatting.formatDocument` ([here](https://github.com/alexgorbatchev/gulp-tsfmt/blob/master/src/index.ts#L51)) but don't get the same results.

Last night I tried rewriting the formatter to use `getFormattingEditsForDocument` ([here](https://github.com/alexgorbatchev/gulp-tsfmt/blob/v2/src/index.ts#L66)) and unfortunately getting the same results.

Could somebody give me a pointer or two on what I'm doing wrong? Clearly there's a way to get the correct results as VSCode does it, but I can't grasp the whole context of everything that's going on in that massive code base to figure out what I'm doing differently.

**Comment by mhegazy** [comment]
I am assuming you are getting other edits working correctly, it is just this bug, correct? is there a sample we can debug through to see what is happening?

**Comment by alexgorbatchev** [comment]
I'm an idiot... I went to create an example and everything worked... my package was NPM linked with old modules... please ignore my comment, sorry for wasting your time.

**Comment by mhegazy** [comment]
thanks for getting back on this. glad the issue has been fixed.
