### ISSUE TITLE
No compile error with Object.assign

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#6689]
```
interface Struct {
  a: boolean
  b: number
}
let v1: Struct = {a: true, b:1}
let v2: Struct = Object.assign({}, v1, {
  b: false
})
```
`v2` variable now contains `{a: true, b: false}`, which is definetely not `Struct` type. But there is no compile-time error there. How come?

**Comment by ahejlsberg** [comment]
This is a duplicate of the issue raised in #6613. We currently don't have the ability to exactly express the semantics of `Object.assign`.
