### ISSUE TITLE
Internal modifier for namespaces

### ISSUE THREAD

**Issue by SalihKARAHAN** [Microsoft/TypeScript#6694]
Hi,
Why don't implemented internal class in typescript?

Element.ts: 
```
namespace Library {
    export class Element {
        //....
    }
}
``` 

SelectElement.ts:
```
namespace Library{
    export class SelectElement extends Element {
        //....
    }
}
```

Program.ts:
```
namespace Library{
    export class Program {
        var selectElement = new Library.SelectElement();
        var element = new Library.Element();
    }
}
```

If i put to export keyword before Element class, other developer can access to Element class, but i remove export keyword i don't use Element class in Library namespace. Does internal class will be able to use now or next version?

**Comment by aleksey-bykov** [comment]
might be related #321

**Comment by mhegazy** [comment]
indeed duplicate of #321

**Comment by SalihKARAHAN** [comment]
Where is related issues? :scream:
