### ISSUE TITLE
ES6 Module were finalized

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#670]
According to Dr. Axel Rauschmayer the modules keywords and functionality proposal are considered final 

http://www.2ality.com/2014/09/es6-modules-final.html

so, since Typescript uses it's own type of import / require, will it be able to do `import * from 'lib';`, `import {a, b} from 'lib';` or `import * as lib from 'lib';`, `export default` any time soon?

**Comment by tarh** [comment]
Nested modules no longer exists in ES6.
What will be the future syntax for modules in TypeScript?

Will the full name of a class ("MyModule1.MyModule2.MyClass") disappear?

**Comment by mhegazy** [comment]
see #/2242
