### ISSUE TITLE
constrained generic type can't be passed to another method as a type parameter

### ISSUE THREAD

**Issue by ps2goat** [Microsoft/TypeScript#6706]
What I'm trying to do:
Load a component dynamically in Angular2 (2.0.0.beta.1) in Typescript 1.7.5.  I made a service that should be able to take in any component that extends my base class, `Foo`.

Service, trimmed for brevity:
```
private doStuff<TComponent extends Foo>(nextTo: ElementRef) {
  return this.componentLoader.loadIntoLocation(TComponent, nextTo.location, 'templateVarName');
}
```

Problem:
`TComponent` is not recognized when passing it to `loadIntoLocation`.

Compilation Error: 
> error TS1135: Argument expression expected.

IDE error: 
> cannot find name 'TComponent'

I would expect this to work similar to .NET.  Can this be done, or has it been implemented after Typescript version 1.7.5?

**Comment by ps2goat** [comment]
For reference, here is the angular2 definition for that method:

  `  abstract loadIntoLocation(type: Type, hostLocation: ElementRef, anchorName: string, providers?: ResolvedProvider[], projectableNodes?: any[][]): Promise<ComponentRef>;`

It works if I change the `TComponent` directly to `Foo`, but the goal is to be able to supply any child type that derives from `Foo` so the correct component gets loaded.

**Comment by RyanCavanaugh** [comment]
See https://github.com/Microsoft/TypeScript/wiki/FAQ#why-cant-i-write-typeof-t-or-instanceof-t-in-my-generic-function
