### ISSUE TITLE
Suggestion: Transpile path mappings based module resolution imports to relative paths

### ISSUE THREAD

**Issue by dsherret** [Microsoft/TypeScript#6710]
Taking example 2 from the original issue (#5039):

```
projectRoot
├── folder1
│   ├── file1.ts
│   └── file2.ts
├── generated
│   ├── folder1
│   └── folder2
│       └── file3.ts (Contains: import 'folder1/file2';)
└── tsconfig.json (with "baseUrl": ".")
```

When doing...

```typescript
import 'folder1/file2';
```

...in `file3.ts` it current compiles to the same thing as above. Would it be possible if we could add a compiler option or some way that would convert this to the relative path? So it would transpile it to:

```typescript
import './../../folder1/file2';
```

That way the paths don't have to be managed in two places. I couldn't find this discussed anywhere and didn't want to clutter the original issue so I'm opening this here.

**Comment by mhegazy** [comment]
Can you elaborate on the use case here.

**Comment by mhegazy** [comment]
please reopen if you have more information.

**Comment by LaurensRietveld** [comment]
@mhegazy : to avoid opening another issue with the same topic, I'd like to pitch in. 
As far as I see, what @dsherret means is that the `import * as something from 'folder1/file2'` is transpiled to something like `const something = require('folder1/file2')` (assuming commonjs). 
The transpiled JS won't work without some hacking around, i.e. duplicating the same functionality that typescript already has, but now for rewriting these javascript require statements.

I assumed that this conversion to relative paths was part of these new ts 2.0 features, but just like @dsherret I fail to find relevant documentation for this scenario

ps. Feel free to correct me if I reinterpret you incorrectly @dsherret  ;)

**Comment by dsherret** [comment]
Yes, basically I think it would be extremely nice if the emitter handled emitting the module specifier to a relative path if the module specifier is resolved using baseUrl, path mappings, or rootDirs.

Right now it emits `import 'folder1/file2';` to have the same module specifier—`'folder1/file2'`. That means I have to configure the module loader to know the configuration in *tsconfig.json*... in this case `"baseUrl": "."`.

So current problems:

1. I have to configure `"baseUrl": "."` in TypeScript AND in my module loader configuration.
2. I have to hope that whatever module loader I'm using has support for the feature I use in *tsconfig.json* (baseUrl, path mappings, rootDirs).

It would be nice if the emitter would handle all this. That would mean that I would only need to keep this configuration in *tsconfig.json*.
