### ISSUE TITLE
Nuget Packages - TSC 1.8 is not preferred to Typescript tooling (TSC 1.7.6)

### ISSUE THREAD

**Issue by snerks** [Microsoft/TypeScript#6715]
In a VS2015 Typescript HTML App, if I reference the Nuget packages for the 1.8 Typescript compiler and MSBuild Tasks, does the 1.8 TSC compiler in the Nuget package get used in preference to the version associated with the VS2015 Typescript tooling (1.7.6)?

I'm seeing that an attempt to reference a Stateless Functional Component (as shown in the  SimpleGreeter example in the release notes) in (say) an App.tsx file, I still get the TSC 1.7 compiler "error":

Error TS2605	JSX element type 'Element' is not a constructor function for JSX elements.

 Property 'render' is missing in type 'Element'.

**Comment by mhegazy** [comment]
Currently the `TypeScriptToolsVersion` needs to be 1.8 for it to work. I agree that the NuGet package version should take precedence. so we should fix this.
Meanwhile, please manually update your `<TypeScriptToolsVersion>` property to `1.8.`.

**Comment by snerks** [comment]
[@mhegazy](https://github.com/mhegazy) - Thanks for the feedback. However, having tried your suggestion to change the `TypeScriptToolsVersion` to `1.8.0`, I see the same compiler error.

Is there an example project available that shows the Nuget TSC compiler + MSBuild combination working?

**Comment by paulvanbrenk** [comment]
@snerks It should be `1.8` exactly

**Comment by snerks** [comment]
Thanks @paulvanbrenk. I tried this:

    <TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>

Same compiler error.

**Comment by paulvanbrenk** [comment]
Can you share the detailed build diagnostics?

**Comment by snerks** [comment]
How do I collect detailed build diagnostics?

**Comment by snerks** [comment]
For info, I'm seeing this after a build attempt:

Warning	0	Your project file uses a newer version of the TypeScript compiler and tools than supported by this version of Visual Studio.  Your project may be using TypeScript language features that will result in errors when compiling with this version of the TypeScript tools.  To remove this warning, remove the <TypeScriptToolsVersion> element from your project file.

**Comment by snerks** [comment]
What is the preferred way to deliver detailed build diagnostics (2555 lines)?

**Comment by snerks** [comment]
[https://github.com/snerks/Ts18Vs2015Issue](https://github.com/snerks/Ts18Vs2015Issue)

Detailed Build Output:
[https://github.com/snerks/Ts18Vs2015Issue/blob/master/DetailedBuildOutput.txt](https://github.com/snerks/Ts18Vs2015Issue/blob/master/DetailedBuildOutput.txt)

**Comment by paulvanbrenk** [comment]
You're importing the typescript targets and props file twice, remove the once, which don't point to the NuGet package folder.

See here https://github.com/Microsoft/TypeScript/wiki/Configuring-MSBuild-projects-to-use-NuGet

**Comment by snerks** [comment]
I removed MSBuild references not pointing to the Nuget package folder. The detaild Build output now reports success:

1>Build succeeded.
1>
1>Time Elapsed 00:00:00.10
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

Should I expect to see squigglys in the IDE and the original compiler error in the Error List?

Screenshot:
[https://github.com/snerks/Ts18Vs2015Issue/blob/master/Ts182HtmlApp.Issue.png](https://github.com/snerks/Ts18Vs2015Issue/blob/master/Ts182HtmlApp.Issue.png)

**Comment by mhegazy** [comment]
> Should I expect to see squigglys in the IDE and the original compiler error in the Error List?

The version of your VS installation (1.7.6) is a different one from the one you are using to build in NuGet (1.8.0), so the error is expected. you can upgrade your VS installation, or use the older NuGet package to build.

**Comment by snerks** [comment]
@mhegazy @paulvanbrenk 
OK. Thanks for the additional info.

**Comment by paulvanbrenk** [comment]
Added logic to help determine when the version of the Nuget package doesn't match the version of the language service in VS, and show a warning in VS.
