### ISSUE TITLE
TSX: Space is added before closing parenthesis

### ISSUE THREAD

**Issue by djanosik** [Microsoft/TypeScript#6716]
When I format document a space is added before closing parenthesis.

![image](https://cloud.githubusercontent.com/assets/858180/12673144/383f4664-c67b-11e5-9307-c5343a1f1635.png)

It should not be added.

**Comment by SaschaNaz** [comment]
Possibly related to #5834.

**Comment by ibratoev** [comment]
This is possibly related to another issue that I fight with in the moment in a TSX file:
```
  return (
    <span>({paramList})</span>
  );
```
is formatted to 
```
  return (
    <span>({paramList}) </span>
  );
```

The space actually changes the behavior - something a formatter must not do.

**Comment by chicoxyzzy** [comment]
wow bug in last comment is really serious and should be fixed
