### ISSUE TITLE
Visual Studio 2015 build property pane errors when using tsconfig.json

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#6718]
I'm using Visual Studio 2015 with the new TypeScript 1.8 beta.  The project I'm using has a `tsconfig.json` in the root.  When I go to the `TypeScript Build` tab on the property panes I was expecting it to be just greyed out because I'm using a `tsconfig.json`.  In actual fact I experienced this:

![visualstudio2015tsconfig jsonpropertypageserror](https://cloud.githubusercontent.com/assets/1010525/12674248/d7ccf20a-c679-11e5-8d7e-830dd1ea13d8.png)

I'm also using the new NuGet version of TypeScript in the project but I'm not sure if that is relevant.  I mention it for completeness.

**Comment by johnnyreilly** [comment]
It looks like this may be related to using the Nuget version of TypeScript.  When I dropped using that I started getting the expected greyed out pane:

![nowwithoutnugettypescriptinthemix](https://cloud.githubusercontent.com/assets/1010525/12674800/920c3470-c67d-11e5-995e-ab2d331f3afc.png)

**Comment by paulvanbrenk** [comment]
I don't reproduce this on my machine.. can you share a project in which this reproduces?

**Comment by mhegazy** [comment]
Please give 1.8.4 a try and reopen if you still see the issue.

**Comment by johnnyreilly** [comment]
Just checked and all seems fine

**Comment by mhegazy** [comment]
thanks @johnnyreilly!
