### ISSUE TITLE
Visual Studio 2015 having problems processing tsconfig.json

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#6719]
Using the new VS 2015 1.8 TypeScript plugin I was expecting `tsconfig.json` to now be first class.  I have a project with a `tsconfig.json` in the scripts folder.  However, it's throwing this error:

> 4>VSTSC : tsc.js(31086, 13) JavaScript runtime error : Unable to get property 'compilerOptions' of undefined or null reference

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "inlineSourceMap": true,
    "inlineSources": true,
    "noImplicitAny": true,
    "preserveConstEnums": true,
    "removeComments": false,
    "sourceMap": false
  },
  "atom": {
    "rewriteTsconfig": true
  }
}
```

I did wonder if the `atom` addition was causing problems but it doesn't appear to be.

**Comment by johnnyreilly** [comment]
I tracked this down to a stray:

```
    <TypeScriptToolsVersion>1.7</TypeScriptToolsVersion>
```

in my csproj.  By switching to 

```
    <TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>
```

the problem resolved.  It would be nice if there was more informative error in VS.  I'm not sure if this should be closed or not?

**Comment by mhegazy** [comment]
This was a bug in 1.7, should be fixed in 1.8, I do not think there is much we can do for 1.7 at this point.

**Comment by jagt** [comment]
In case of anyone having this problem after installing VS2015 update 2, I find that it didn't really install 1.8 sdk but reuses the 1.7 one I previously installed. [Download 1.8.6 from here ](https://www.microsoft.com/en-us/download/details.aspx?id=48593)worked for me.

**Comment by mhegazy** [comment]
@jagt, can you share your install logs using http://aka.ms/vscollect

**Comment by jagt** [comment]
@mhegazy I've downloaded and executed the `Collect.exe`. Is there any other thing I needs to do? Thanks!

**Comment by mhegazy** [comment]
please share the resulting `vslogs.zip`.

I should have been more clear, here are the steps:

- download the tool from the link: http://aka.ms/vscollect
- put the exe in your temp folder (`%temp%`)
- run the exe. It will produce the logs folder called `vslogs.zip`.

**Comment by jagt** [comment]
@mhegazy Ok I'll upload it when I get home.
