### ISSUE TITLE
Visual Studio 2015 tsconfig.json without files does not include *.d.ts

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#6720]
Given a `tsconfig.json` that looks like this: (i.e. without a `files` element)

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "inlineSourceMap": true,
    "inlineSources": true,
    "noImplicitAny": true,
    "preserveConstEnums": true,
    "removeComments": false,
    "sourceMap": false
  }
}
```

which is placed in a `Scripts` folder which contains all TypeScript files (both code and typings).  I would expect this to detect all TS files.  However, upon compilation none of the `*.d.ts` files appear to be being detected.  (It's a world of *Cannot find namespace 'ng'.* etc)

The workaround is to manually include every file in the `files` property.  However, given this project has hundreds of files that's a pain to write.  (To save time I'm using atom-typescript's [filesGlob](https://github.com/TypeStrong/atom-typescript/blob/master/docs/tsconfig.md#filesglob) to generate this for me.  Thanks @basarat!)

**Comment by paulvanbrenk** [comment]
What kind of project are you using? And can you share the detailed msbuild log?

**Comment by johnnyreilly** [comment]
It's a classic ASP.Net project. C# / MVC 5.2.3 / Web API. I won't be have access to the build until next week but I could probably share it then.

**Comment by paulvanbrenk** [comment]
Thanks, I'll try some other things to reproduce in the meanwhile.

**Comment by johnnyreilly** [comment]
Cool - the typings came from Definitely Typed and were installed via nuget if that helps. As far as I can tell all *.d.ts files were ignored (Angular / Knockout etc).

**Comment by paulvanbrenk** [comment]
And IntelliSense works as expected, just build that fails?

**Comment by johnnyreilly** [comment]
Yup - intelligence just fine. And not a red squiggly in sight.

**Comment by johnnyreilly** [comment]
Just the build - that acts up.

**Comment by paulvanbrenk** [comment]
Ok, thanks... I have a couple of theories, but the build logs should give some clarity.

**Comment by johnnyreilly** [comment]
Hey @paulvanbrenk,

Here's the detailed build output:

[detailedbuildoutput.txt](https://github.com/Microsoft/TypeScript/files/111987/detailedbuildoutput.txt)

**Comment by paulvanbrenk** [comment]
Thanks.. does the same thing happen I you run either of these from the command line?

`C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\Source\TFS\SOLUTIONNAME\Development\PROJECTNAME\Scripts\tsconfig.json"`

and 
`C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\Source\TFS\SOLUTIONNAME\Development\PROJECTNAME\Scripts\"`

**Comment by johnnyreilly** [comment]
Hi @paulvanbrenk,

I'll test tomorrow and report back.

**Comment by johnnyreilly** [comment]
Hey @paulvanbrenk 

`C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\Source\TFS\SOLUTIONNAME\Development\PROJECTNAME\Scripts\tsconfig.json"`

Same problem.

`C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\Source\TFS\SOLUTIONNAME\Development\PROJECTNAME\Scripts\"`

Same problem.

Hope that helps.

**Comment by paulvanbrenk** [comment]
Yeah, this shows that it's not a VS or MSBuild issue, but something in the compiler. Can you create a 2 file sample, I still have trouble reproducing.

**Comment by johnnyreilly** [comment]
2 file sample? Which files? Just one ts and one d.ts? Can't promise but might be able to take a look tomorrow

**Comment by paulvanbrenk** [comment]
Yep, and the `tsconfig.json`, or the minimum number of files required to repro.

**Comment by johnnyreilly** [comment]
[TSConfig_d_ts_problems2.zip](https://github.com/Microsoft/TypeScript/files/115838/TSConfig_d_ts_problems2.zip)

Hey @paulvanbrenk,  The zip above was the minimum no of files required for a repro.  There's a solution which contains a single project.  The project itself contains 2 TS files:`scripts\site.ts` and `scripts\typings\jquery\jquery.d.ts` besides the `tsconfig.json`.

There's a few other files in the project but not many.  I hope that's minimal enough for you.   It ended up taking rather longer to create a minimal use case that I intended and I reached a point where I had to draw a line under it.  There may be a couple of extraneous files still in there but not many.

**Comment by johnnyreilly** [comment]
[TSConfig_d_ts_problems2.zip](https://github.com/Microsoft/TypeScript/files/115851/TSConfig_d_ts_problems2.zip)

**Comment by paulvanbrenk** [comment]
Thanks, we found the issue... the way we checked for the extension of files using the new ChakraCore based compiler didn't behave correct for `.d.ts` files.

This should be in the nightly NuGet package tonight.

**Comment by mhegazy** [comment]
@johnnyreilly, please give the nightly (on or after 2/4) a try and let us know if things are working correctly.

**Comment by johnnyreilly** [comment]
Happy to help @paulvanbrenk. @mhegazy, do you have a link to the nightly nuget feed? I'll check when at work tomorrow.

**Comment by johnnyreilly** [comment]
Sorry, this one isn't nuget is it? It's the Visual Studio plugin / power tool. That's published as part of nightlies too? Point me there and I'll have a go!

**Comment by paulvanbrenk** [comment]
This is not a problem in the VS tools, just the compiler bits, which we do ship on MyGet [0].

[0] https://www.myget.org/gallery/typescript-preview

**Comment by johnnyreilly** [comment]
Cool - I see the page.  I guess it's just a case of following the instructions [here](https://github.com/Microsoft/TypeScript/wiki/Configuring-MSBuild-projects-to-use-NuGet) to swap out the build in the project for a NuGet one (or in this case MyGet one) and seeing if the error still happens?

Presumably this would also allow me to test https://github.com/Microsoft/TypeScript/issues/6721 is resolved as well.

**Comment by paulvanbrenk** [comment]
Yes, that should be fixed on MyGet too.

**Comment by johnnyreilly** [comment]
Sorry didn't get chance to look at this today. Will tomorrow.

**Comment by johnnyreilly** [comment]
Tested with:

```
  <package id="Microsoft.TypeScript.MSBuild" version="1.8.20160205.1-beta" targetFramework="net45" developmentDependency="true" />
```

It built locally with no errors when I removed the `files` element from `tsconfig.json`.   So LGTM.

**Comment by paulvanbrenk** [comment]
thanks for following up
