### ISSUE TITLE
Using MSBuild projects with NuGet errors on TFS build server with "The given path's format is not supported."

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#6721]
This issue reported [here](https://github.com/Microsoft/TypeScript/issues/6215) regarding path problems occurs when you use the MSBuild with NuGet.  Attempting to build using this approach results in:

> C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets (182): Unable to copy file "C:\Builds\3\PROJECTNAME\Nightly Test Run\src\PROJECT\Scripts\validationUtils.js" to "C:\Builds\3\PROJECTNAME\Nightly Test Run\bin\Pantheon.AppsPortal\_PublishedWebsites\PROJECT\C:\Builds\3\PROJECTNAME\Nightly Test Run\src\PROJECT\Scripts\validationUtils.js". The given path's format is not supported.

I'm guessing the resolution to #6215 just needs to be carried across to MSBuild / NuGet?

**Comment by mhegazy** [comment]
@johnnyreilly can you share the full build log?

**Comment by johnnyreilly** [comment]
I won't have access to it until next week but yes I should be able to then.

**Comment by johnnyreilly** [comment]
Hey @mhegazy,

Here's the detailed build log:

[detailedbuildoutputTFS.txt](https://github.com/Microsoft/TypeScript/files/112039/detailedbuildoutputTFS.txt)

**Comment by paulvanbrenk** [comment]
Yes, this was a bad merge. I have a fix checked in, which should be in the nightlies on MyGet.

**Comment by johnnyreilly** [comment]
Sweet! Thanks.

**Comment by johnnyreilly** [comment]
Tested with:

```
  <package id="Microsoft.TypeScript.MSBuild" version="1.8.20160205.1-beta" targetFramework="net45" developmentDependency="true" />
```

It built on our build server (which has TS 1.7 installed).   No errors experienced.

**Comment by paulvanbrenk** [comment]
Thanks for following up
