### ISSUE TITLE
Add separate compiler option for generated declarations output directory.

### ISSUE THREAD

**Issue by ylepikhov** [Microsoft/TypeScript#6723]
I need to make an automated building of my typescript projects. Typescript compilation results (i.e .js and .d.ts files) need further separate processing. 

It would be nice if there is separate compilation option to specify output directory for generated declarations. Something like this:

```javascript
//tsconfig.json
{
  "CompilerOptions": {
    ...
      "declaration": true,
      "declarationDir": "target/typings"
    ...
  }
}```

**Comment by RyanCavanaugh** [comment]
Didn't come up with a name, but we'd take a PR on this. Should be easy enough.

**Comment by masaeedu** [comment]
@RyanCavanaugh I think I've narrowed it down to some fooling around that needs to be done here: https://github.com/Microsoft/TypeScript/blob/a324176102b4657b4de6759b5d03f5eeda38f422/src/compiler/utilities.ts#L2070. Some questions though...

What organization should be followed inside the declarations folder? Do I just remove the `.js` from a file, snip the path relative to the `outDir` or project root (whichever comes first), and plant that relative to the `declarationDir`?

Also, how would I write a test to check where declaration files end up?

**Comment by mhegazy** [comment]
the logic should map to that of --outDir today. for tests just add compliler tests, with flags as "@" comments (see https://github.com/Microsoft/TypeScript/blob/master/tests/cases/compiler/outModuleConcatAmd.ts) the output will have the file name in it

**Comment by masaeedu** [comment]
@mhegazy It seems the generated JS file from the test doesn't contain any artifact that lets you see where the file ends up relative to the project root. E.g. the JS file generated for the following test:

```typescript
// @allowJs: true,map
// @sourcemap: true
// @outdir: out

// @filename: a.ts
class c {
}

// @filename: b.js.map
function foo() {
}

// @filename: b.js
function bar() {
}
```

is: 

```javascript
//// [tests/cases/compiler/jsFileCompilationWithMapFileAsJsWithOutDir.ts] ////

//// [a.ts]

class c {
}

//// [b.js.map]
function foo() {
}

//// [b.js]
function bar() {
}

//// [a.js]
var c = (function () {
    function c() {
    }
    return c;
}());
//# sourceMappingURL=a.js.map
```

There's no mention of the `out` directory specified in the `outDir` option. I was expecting something like `//// [out/a.js]`. Is there a good way to write a test for this?

**Comment by mhegazy** [comment]
my bad. that would be the project tests: e.g: https://github.com/Microsoft/TypeScript/blob/master/tests/cases/project/rootDirectory.json, and the output should be in https://github.com/Microsoft/TypeScript/tree/master/tests/baselines/reference/project/rootDirectory/node

**Comment by masaeedu** [comment]
@mhegazy Thanks. This is slightly off topic, but it looks like the test harness stops emitting as soon as it detects a single difference between the local and reference baselines. This means you have to run the testcase until it chokes, copy the mismatched file to the reference folder, run it again until it finds the next difference, and so on. Is this by design?

**Comment by RyanCavanaugh** [comment]
@masaeedu the tests keep running when they detect differences. Afterwards you can run `jake baseline-accept` to move the new baselines from `local` to `reference` automatically.

**Comment by ca0v** [comment]
I couldn't figure it out from reading the above comments but will there be a similar "declarationOutFile" which will concatenate all the definitions into one?  Something akin to what https://github.com/SitePen/dts-generator is doing?

**Comment by masaeedu** [comment]
@ca0v There isn't a declarationOutFile yet (although this was discussed on the PR). You can file an issue if you need it.
