### ISSUE TITLE
New Website Logo: Exago, Inc.

### ISSUE THREAD

**Issue by fernap3** [Microsoft/TypeScript#6724]
Please fill the following out:

- Name: Exago, Inc.
- Homepage url: http://www.exagoinc.com
- Brand Guidelines/Licensing: N/A
- Logo: [exago_logo.zip](https://github.com/Microsoft/TypeScript/files/109862/exago_logo.zip)

**Comment by filipesilva** [comment]
You sure this is the right repo?

**Comment by fernap3** [comment]
Hi Filipe, we use TypeScript in the web app component of our core product (demoed in a bunch of videos here: [http://www.exagoinc.com/learn/end-user-video](http://www.exagoinc.com/learn/end-user-video)).  We recently converted all of our Javascript (200+ source files) to TypeScript with the idea that it will streamline the development process as our amount of client-side code increases.

**Comment by filipesilva** [comment]
Ah this is for a list of websites that use Typescript? I wasn't getting what the issue meant, my bad!

**Comment by mhegazy** [comment]
Logo uploaded, should be out in the next site refresh.
