### ISSUE TITLE
The Typescript language service died unexpectedly 5 times in the last 5 Minutes

### ISSUE THREAD

**Issue by khanyuriy** [Microsoft/TypeScript#6726]
Hi, something is killing this service, after upgrading node to 5.5.  
I have got this message "The Typescript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report"
Any suggest ?

**Comment by RyanCavanaugh** [comment]
Can you post a file that causes this problem?

**Comment by khanyuriy** [comment]
Hi, RyanCavanaugh!
It doesn't work in every file of my code base. 
I have created clean project with one ts file and service work.
Is there some diagnostic tool or may be dump files to get the cause of service crash in my code? 
Do you ask me to send any file of my project ?

**Comment by mhegazy** [comment]
@khanyuriy we need some repro steps to be able to diagnose the issue. What version of vscode are u using? What version of TS? Do you have a custom tssdk? What are your compiler options? Can you build this project on the commandline? Does it reproduce on any file outside ur project?

**Comment by khanyuriy** [comment]
hi, mhegazy!

>  What version of vscode are u using?
Version 0.10.6
Commit a80232bbcfe8a5cdad1ebc98638673d9dcb02458
Date 2015-12-19T11:34:58.895Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1

> What version of TS
Version 1.0.3.0

> Do you have a custom tssdk
no, i haven't

> What are your compiler options? 
{
	"compilerOptions": {
		"module": "commonjs",
		"target": "es5",
		"sourceMap": true
	}
}

> Can you build this project on the commandline
yes, i build it with gulp-tsc

> Does it reproduce on any file outside ur project
yes i have all js file compiled successfully

**Comment by mhegazy** [comment]
can you share a project that reproduces the issue. i can not get it to reproduce with the information supplied.

**Comment by khanyuriy** [comment]
mhegazy,
i guess i found the cause. I think it tries to parse node_modules that resides in root dir. Structure of node_modules is changed since node 0.10, thats is why it was dead after node upgrade. When i removed this folder service is worked like a charm.
is there anyway to tell vscode to ignore this folder?

**Comment by billti** [comment]
Add "node_modules" to the "excludes" option (see https://github.com/billti/ng2demo/blob/master/tsconfig.json#L10 as an example).

**Comment by khanyuriy** [comment]
hi, billti!
thank you. It was helpfull

**Comment by mhegazy** [comment]
#6670 should add node_modules to the excludes by default, so should handle this issue.

**Comment by Alphapage** [comment]
Hello,

I have the same error message from vscode, but I know where my problem comes from:
I'm using Virtualbox with Windows 10 as host and guest. From guest, if I open the project from C:, then no problem. But if I open the project from shared folder drive, then I get the same error message:
"The Typescript language service died unexpectedly 5 times in the last 5 Minutes. Please consider to open a bug report".
The problem seems to come from the file watchers which are unable to start or to detect changing.
Virtualbox team doesn't seem to want to implement some notifications for shared folders.

Do you have a workaround to make tsserver working with virtualbox shared folders (something like polling maybe) ?

Thank you in advance for your answers.

**Comment by mhegazy** [comment]
@zhengbli, any ideas here?

**Comment by zhengbli** [comment]
It seems that virtualbox shared folder didn't implement the underlying file change notification mechanism that the non-polling `fs.watch` depends on (related: https://www.virtualbox.org/ticket/10660, https://github.com/mitchellh/vagrant/issues/707, though the guest in these examples are not windows, but I suspect the same issue exists). We do need a way to detect the failure, and switch to polling watchers in this case.

**Comment by billti** [comment]
@zhengbli Can you open a new issue to track this and assign to yourself (if you haven't already). thanks.

**Comment by zhengbli** [comment]
FYI: I repro this issue with the same set up, and running `tsc --watch` gives me an error message saying:
```
UNC Paths are not supported. Defaulting to Windows directory.
```
Calling `fs.watch` directly on shared folder caused exit without information; while calling `fs.watchFile` works fine.
