### ISSUE TITLE
relative path import does not work when module is not "commonjs"

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript#6730]
Here is an example:
https://github.com/coolcodeexamples/timely-wealth-game

Change tsconfing.json to module: "system"
and then run tsc.

The error is:
`error TS2307: Cannot find module './App.ts'.`

Please ignore the "Module ''domready'' has no default export" when compiling in .`commonjs` or in `system` with 1.7.5. That's related to systemjs (I'm using JSPM to run so it is working correctly in both count).

**Comment by unional** [comment]
Seems like resolving relative path only works for commonjs. system, amd, umd, es6/es2015 all report the same error.

**Comment by zhengbli** [comment]
@unional You can set `"moduleResolution": "node"` while still use `"module": "system"`

**Comment by unional** [comment]
Excellent!  Is there any doc related to `moduleResolution`? I only see it in the compileOptions but it doesn't mention what it does (and how it works).

**Comment by zhengbli** [comment]
All doc of the compiler options can be found on this [wiki page](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options). Basically it decides how to resolve modules
