### ISSUE TITLE
Merged external modules break protected member access checking

### ISSUE THREAD

**Issue by masaeedu** [Microsoft/TypeScript#6731]
Having some difficulty utilizing the external module augmentations feature merged in #6213. Here is a test case to demonstrate the problem:

```
// a.ts
export class A {
    protected protected: any;
    
    public setProtected(val: any) {
        this.protected = val;
    }
}
```

```
// b.ts
import {A} from './a'; // Only here to make b.ts an external module

declare module "./a" {
    interface A { }
}
```

This results in the following error:

> a.ts(5,9): error TS2446: Property 'protected' is protected and only accessible through an instance of class 'A'.

It looks like the problem is that [`checkClassPropertyAccess`](https://github.com/Microsoft/TypeScript/blob/1ae7d5ca092d883213f0a5f10c609fda7fa5cccc/src/compiler/checker.ts#L8777) in checker.ts ends up obtaining the merged interface as the enclosing class of the property access, rather than the actual enclosing class, then tries to ensure that this interface is derived from the class which declares the property, which isn't the case.

**Comment by vladima** [comment]
this is not specific to module augmentations and can be reproduced with two script files:
```ts
// file1.ts
class A {
    protected protected: any;

    public setProtected(val: any) {
        this.protected = val;
    }
}
```
```ts
// file2.ts
interface A { }
```

**Comment by masaeedu** [comment]
@vladima Not sure if this is related, but overrides of protected members are still broken:

```
// a.ts
export class A {
    protected protected: any;
    
    protected setProtected(val: any) {
        this.protected = val;
    }
}
```

```
// b.ts
import {A} from './a';

declare module "./a" {
    interface A { }
}

export class B extends A {
    protected setProtected() {
        
    }
}
```

This results in:

> b.ts(7,14): error TS2415: Class 'B' incorrectly extends base class 'A'. Property 'setProtected' is protected but type 'B' is not a class derived from 'A'.

**Comment by vladima** [comment]
the crux of the problem is the same but in different part of the checker - have a fix for it.

**Comment by vladima** [comment]
filed #6762 to track it.
