### ISSUE TITLE
"use strict"; is not emitted for ES6 targets without modules

### ISSUE THREAD

**Issue by sparseinference** [Microsoft/TypeScript#6733]
In a file without an explicit module defined, the strict prologue is not emitted, causing the "captured let/const in loops" feature to fail in that async/await example of "What's new in Typescript?".

That example is for Typescript 1.7, but shouldn't it now be ok to write that without the strict prologue, letting the compiler handle it?

**Comment by vladima** [comment]
`"use strict"` is emitted in modules because in ES6 modules are always in a strict mode so TypeScript just replicates proper ES6 semantic. This is not true for script files so user has to explicitly set prologue directive if he wants the file to be parsed in the script mode

**Comment by sparseinference** [comment]
Well OK, but I think there's still a problem: the "captured let/const in loops" feature fails without a strict prologue. That means it can't be mixed with non-strict code. This is very error-prone.

**Comment by vladima** [comment]
can you please elaborate what is not working? This is code from [this example](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#allow-captured-letconst-in-loops)
```ts
let list = [];
for (let i = 0; i < 5; i++) {
    list.push(() => i);
}

list.forEach(f => console.log(f()));
```

it is compiled to
```javascript
var list = [];
var _loop_1 = function(i) {
    list.push(function () { return i; });
};
for (var i = 0; i < 5; i++) {
    _loop_1(i);
}
list.forEach(function (f) { return console.log(f()); });
```
```
vladima@vladima-HP:~/Sources/git/TypeScript$ cat t.ts
let list = [];
for (let i = 0; i < 5; i++) {
    list.push(() => i);
}

list.forEach(f => console.log(f()));
vladima@vladima-HP:~/Sources/git/TypeScript$ node built/local/tsc.js t.ts
vladima@vladima-HP:~/Sources/git/TypeScript$ cat t.js
var list = [];
var _loop_1 = function(i) {
    list.push(function () { return i; });
};
for (var i = 0; i < 5; i++) {
    _loop_1(i);
}
list.forEach(function (f) { return console.log(f()); });
vladima@vladima-HP:~/Sources/git/TypeScript$ node --version
v5.3.0
vladima@vladima-HP:~/Sources/git/TypeScript$ node t.js
0
1
2
3
4

```

**Comment by sparseinference** [comment]
Yes, it's the example from "What's new in Typescript?", at 1.7 .

```
// printDelayed is a 'Promise<void>'
async function printDelayed(elements: string[]) {
    for (const element of elements) {
        await delay(1000);
        console.log(element);
    }
}

async function delay(milliseconds: number) {
    return new Promise<void>(resolve => {
        setTimeout(resolve, milliseconds);
    });
}

printDelayed(["Hello", "beautiful", "asynchronous", "world"]).then(() => {
    console.log();
    console.log("Printed every element!");
});
```
Without the "use strict"; It prints: 

```
Hello
Hello
Hello
Hello

Printed every element!
```

**Comment by mhegazy** [comment]
this looks like a v8 bug to me.

**Comment by vladima** [comment]
+1, just tried output in Edge without string mode prologue directive and result was expected

**Comment by sparseinference** [comment]
I'm using node v5.5.0

**Comment by vladima** [comment]
there is something funky here, simplified example
```javascript
for (const x of [1,2,3]) console.log(x)
```
Node: 5.3.0: prints `1 1 1`
Edge: complains that const should be initialized

```javascript
for (let x of [1,2,3]) console.log(x)
```
Node: error because `Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`
Edge: print `1 2 3`

**Comment by vladima** [comment]
does not repro on the reasonably fresh version of ChakraCore so it should be fixed in Edge
