### ISSUE TITLE
MouseEvent constructor is missing parameters

### ISSUE THREAD

**Issue by mryanmurphy** [Microsoft/TypeScript#674]
MouseEvent constructor is defined incorrectly in lib.d.ts. The constructor should take two parameters: a string for event type and a parameters object.

**Comment by jzelenka** [comment]
Is there any way around this except patching lib.d.ts like this:

declare var MouseEvent: {
    prototype: MouseEvent;
    new(): MouseEvent;
    new(type: string, options: any): MouseEvent;
}

**Comment by mhegazy** [comment]
This is the only way i can think of as well.

**Comment by dperelman** [comment]
It's not a great solution, but another workaround is that the current TypeScript will let you use the deprecated method [`initMouseEvent()`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent).
