### ISSUE TITLE
[Question] How to prevent to compile Async and Decorator

### ISSUE THREAD

**Issue by moostad** [Microsoft/TypeScript#6747]
I'm using babel for transpiling like:
```TSX -> ES6 -> Babel + webpack -> ES5```
and I set ```noEmitHelpers``` to ```true``` in ```tsconfig.json```, because babel handle it with single global helper instead of multiple helpers in each file but it doesn't work with Acyncs and Decorators and after compile i'm getting 
``` __decorate(...) ```  
and 
``` 
__awaiter(this, void 0, Promise, function* () {
        ...
        });
```
How can I  prevent tsc to compile Asyncs and Decorators and let babel handle them?

**Comment by yortus** [comment]
This is not yet possible, unfortunately. See #5361. Maybe add your voice over there to bump the issue.
