### ISSUE TITLE
Super class constructor calling an extended method can result in weird behaviour

### ISSUE THREAD

**Issue by michaelowens** [microsoft/TypeScript#675]
Explanation:
- Class A has constructor that calls empty init method
- Class B extends from Class A, adds public property and overrides init function that changes that public property
- Public property is not changed by init function

How to reproduce:

http://www.typescriptlang.org/Playground#src=class%20First%20%7B%0A%09public%20constructor()%20%7B%0A%09%09this.init()%3B%0A%09%7D%0A%09%0A%09public%20init()%20%7B%0A%09%7D%0A%7D%0A%0Aclass%20Test%20extends%20First%20%7B%0A%09public%20testVar%20%3D%201%3B%0A%09%0A%09public%20init()%20%7B%0A%09%09this.testVar%20%3D%202%3B%0A%09%7D%0A%7D%0A%0Avar%20t%20%3D%20new%20Test()%3B%0Aalert(t.testVar)%3B

If the code is ran you can see it will alert 1, rather than the intended 2.

To be honest, I don't know if this is intended behaviour or a bug. I can say is that this particular code rewritten into CoffeeScript seems to work just fine:

http://coffeescript.org/#try:class%20First%0A%20%20constructor%3A%20-%3E%0A%20%20%20%20%40init()%0A%0A%20%20init%3A%20-%3E%0A%0Aclass%20Test%20extends%20First%0A%20%20testVar%3A%201%0A%0A%20%20init%3A%20-%3E%0A%20%20%20%20%40testVar%20%3D%202%0A%0At%20%3D%20new%20Test()%0Aalert(t.testVar)

I didn't quite know how to formulate this into 1 sentence, hence the weird title.

**Comment by thealjey** [comment]
@RyanCavanaugh an example with `[]` is just plain bogus.
Sure, if you put an `Array` onto a prototype and then modify it's contents, the change would affect all objects inheriting that prototype (although, on some rare occasions that might actually be desirable).
But that's simply because `[]` is a mutable property, unlike `1` and `2` in the @michaelowens example.

    "This is also the ES6 class behavior."
this this just lies, shame on you ;)

The solution for me was to stick with Traceur until TypeScript is fully aligned the ES6 standard.

http://thealjey.tumblr.com/the-fatal-flaw-of-typescript

**Comment by RyanCavanaugh** [comment]
> this this just lies, shame on you ;)

Can you clarify on exactly what you're referring to? ES6 classes do put their properties on the instance rather than the prototype.

Your blog post is confusing in context because Traceur's compiler *also* emits code that prints "Hello world".

**Comment by thealjey** [comment]
@RyanCavanaugh, here's a line from the ECMAScript standard:

    If a constructor function needs to perform superclass initialization, it must do so by explicitly calling super(/*arguments*/) at some point within the constructor body.

thus, if I don't want to call super - I don't have to; if want to have the super call at the end of the overriding method body - neither JavaScript not Traceur sure ant gonna stop me from doing that

The difference also, is that ES6 does not make it look like it is possible to define a class property (unlike TypeScript) by listing it in the class body, outside of the methods.
You either assign values to `this` or to `prototype`, the language does not hide that away from you.

I have worked with Traceur for a considerable amount of time and I never have to look into the compiled code to figure out what's going on, unfortunately this isn't always the case with TypeScript.

Types are no doubt cool and the tooling is awesome, but the resulting code is very Microsoft-ish and does not stand a chance when compared to Traceur.
