### ISSUE TITLE
NuGet package should remove existing targets and imports

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#6750]
If there are existing TypeScript targets and props imports the NuGet package should remove them, to prevent the compiler from being invoked multiple times.

**Comment by stffabi** [comment]
It seems like the removing doesn't work anymore for VS2017 and TypeScript 2.3.3 NuGet package. The original imports remain in the project after installing the NuGet package.

`<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />`

`<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets')" />`

TypeScript 2.0.6 NuGet package seems to be the first package that is failing to remove the original imports. Installing TypeScript 1.8.11 NuGet package removes the imports correctly.

**Comment by stffabi** [comment]
Ah seems to be by design, https://github.com/Microsoft/TypeScript/issues/12527#issuecomment-294560020
