### ISSUE TITLE
Colorization of inner types in JSX

### ISSUE THREAD

**Issue by olmobrutall** [Microsoft/TypeScript#6756]
I've found a small issue related to https://github.com/Microsoft/TypeScript/issues/4835 when using inner types, like `Navbar.Header`, `Navbar.Brand` and `Navbar.Toggle` as defined in https://github.com/flyon/react-bootstrap-typescript-definitions.

The text should be in the same red as the other tags, instead of black. 

![image](https://cloud.githubusercontent.com/assets/720953/12696673/dc9d850e-c770-11e5-9f6c-c6f8b3f685d2.png)

**Comment by olmobrutall** [comment]
Hoy the same but somehow related is the fact that imported types are not colored as types but as variables. 

![image](https://cloud.githubusercontent.com/assets/720953/12710845/b5dc9158-c8ba-11e5-842a-277bb6daf809.jpg)

In the foto EntityBase, Lite, Entity, TypeContext, PropertyRoute, etc should all be dark teal instead of black. 

Sent from my handy.

**Comment by techird** [comment]
Can not agree more with @olmobrutall, the imported classes and interfaces are all black, low readability, as well as #5515

**Comment by vladima** [comment]
fix is submitted, now normal and dotted jsx names should look consistent.
![dottednames_jsx](https://cloud.githubusercontent.com/assets/8052307/12732200/54469d38-c8e9-11e5-8725-19311f058850.PNG).

Re: non-colored imports, this is a different issue and I think it was already filed.

**Comment by olmobrutall** [comment]
Thanks! I'll follow https://github.com/Microsoft/TypeScript/issues/5515 for import colorization. Or there's a more appropriate issue?

**Comment by mhegazy** [comment]
#5515 seems like a good place for this issue.
