### ISSUE TITLE
tsc chokes on switches in --example=VALUE format

### ISSUE THREAD

**Issue by ghost** [Microsoft/TypeScript#6758]
Every now and then I pick up tsc and the following type of thing happens:

````
$ tsc --module=commonjs ./foo.ts
error TS5023: Unknown compiler option 'module=commonjs'.
$ # arrgh!
$ tsc --module commonjs ./foo.ts
$
````

**Comment by DanielRosenwasser** [comment]
I'd be okay with this if the complexity of the command line parser didn't get too crazy. @mhegazy @rbuckton @RyanCavanaugh any thoughts?

**Comment by ahejlsberg** [comment]
I'm not super crazy about this idea. One problem is that that it only works if there are no blanks before or after the `=`. Another is that it doesn't work well for boolean options (at least not with the suggested implementation). For example, `--declaration=true` would become `--declaration` followed by `true`, and we'd go look for a file named `true.ts`.

**Comment by viispade** [comment]
> it only works if there are no blanks before or after the `=`

The pull request isn't really going rogue and making some spectacular design decision.  It's more like the opposite.  See my comment in the pull request about `ls` et al.  If there are spaces around the "=", failure is the expected outcome.

This is really about getting `tsc` to treat long options like most every other command-line tool on my system does--including`git`--without surprising anybody.

> Another is that it doesn't work well for boolean options

Yeah, I noticed that sometime after pushing to my branch this afternoon.  It's easy enough to fix.

**Comment by viispade** [comment]
For comparison:

````
$ ls ./bin --format= long
ls: ambiguous argument ‘’ for ‘--format’
Valid arguments are:
  - ‘verbose’, ‘long’
  - ‘commas’
  - ‘horizontal’, ‘across’
  - ‘vertical’
  - ‘single-column’
Try 'ls --help' for more information.
$ ls ./bin --format=long
total 8
-rwxrwxr-x 1 tim tim 45 Jan 30 18:26 tsc
-rwxrwxr-x 1 tim tim 50 Jan 30 18:26 tsserver
$ 
````

**Comment by RyanCavanaugh** [comment]
Suggestions from ghosts are too spooky. If anyone feels like picking this up the PR should still be usable.
