### ISSUE TITLE
no way to specify type parameters inside tsx code

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#6761]
I have a react component like this:

```
class MultiSelect<D> extends React.Component<{list:D},{}>
```

If i want to use it:

```
<MultiSelect list={items}/>
```

I will get an error above cause I cannot define `D` anywhere.

**Comment by DanielRosenwasser** [comment]
I think this is related to #6761 and #3960.

**Comment by RyanCavanaugh** [comment]
#6395
