### ISSUE TITLE
Permit specification of 1.8 compiler options on properties page for Visual Studio projects

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#6767]
I would like to specify some of these options via the settings for a Visual Studio project.

```
--noImplicitReturns.
--noFallthroughCasesInSwitch
--allowJs
```

Currently, this is not possible:

![image](https://cloud.githubusercontent.com/assets/1106823/12701691/1632e4e2-c809-11e5-905e-9130085d27f6.png)

I am aware that VS now supports `.tsconfig`. Is that going to be the only way forward?

**Comment by mhegazy** [comment]
have you considered using a tsconfig.json?

**Comment by NoelAbrahams** [comment]
@mhegazy, as I said at the end of the post I was thinking along the same lines. But I'm not sure how `tsconfig.json` is going to play with NTVS projects. Are you pushing `tsconfig.json` as the comprehensive solution going forward?

**Comment by paulvanbrenk** [comment]
`tsconfig.json` should work with all project types... if you run into issue I would love to hear about them.

NTVS projects was one of the reasons for broader `tsconfig.json` support, that way you can contain both the client- and server-side javascript in the same project, but use different settings for both.

**Comment by mhegazy** [comment]
`tsconfig.json` is where we would like the configuration to live moving forward. it is easier to edit and understand for most JS developers, and cheaper to change for us (vs. the property pages UI); also works well with other tools in the build chain.

**Comment by NoelAbrahams** [comment]
@paulvanbrenk,@mhegazy, that's good to hear. We have some dependencies on the old `_references.ts` that we need to rewrite, before switching to `tsconfig`. I'll let you know how things go.

I'm also glad that NTVS is being taken into account on par with TypeScript development. Their project [seems to be slowly lapsing into oblivion](https://github.com/Microsoft/nodejstools/pulse) and as TypeScript moves forward, it's a bit worrying. There is no good alternative in Visual Studio for developing, testing and debugging NodeJS projects. If you are privy to any information on this, I think a lot of people would be interested.

**Comment by mhegazy** [comment]
No "lapsing into oblivion", I would assure you. and we do care about our NodeJS developers. it is just hard to keep updating the UI for the property pages for every option added to the compiler, and tsconfig should solve that moving forward.

**Comment by NoelAbrahams** [comment]
I was referring to the lack of commits in the NTVS github project - not to the commitment on the TypeScript side (which of course is exceptional). There are a few key issues that have not been resolved on the NTVS side (such as this one Microsoft/nodejstools#223, which has been open since June last year).

**Comment by mhegazy** [comment]
that is what i meant :). @mousetraps can add more.

**Comment by mousetraps** [comment]
Hey @NoelAbrahams. @mhegazy is correct - in fact, we are actually in the midst of growing the team! The fact is, however, that we do have a *very* small core team, can only do so many things at any given time, and unfortunately much of the work that we have been doing lately is not externally visible. That said, your post prompted me to consider potential opportunities to improve communication going forward, so I really appreciate your feedback and would love for you to be involved in this discussion :smiley:. https://github.com/Microsoft/nodejstools/issues/677

**Comment by jslew** [comment]
The problem for me is that the presence of tsconfig.json seems to shut off VS2015's "Compile On Save" option, despite the fact that it is not really a compiler-level option.  So it's seemingly impossible to get "Compile On Save" and "AllowJs" at the same time without manually firing up an external "tsc --watch".

**Comment by mhegazy** [comment]
Compile on Save while you have a tsconfig.json is disabled by default, to enable it go to tools\options\Text Editor\TypeScript\Project and check "Automatically compile typescript files which are not part of a project". note that there is no way in TS 1.8 beta to disable/enable it for a single tsconfig.json file. With https://github.com/Microsoft/TypeScript/issues/2326, which should be in the next TS 1.8 release should have a property ("compileOnSave") to enable/disable Compile on Save in tsconfig.json.

**Comment by jslew** [comment]
Thanks for the tip. That will work even if the files are part of the csproj?

**Comment by mhegazy** [comment]
Starting with 1.8.2, setting "compileOnSave" in your tsconfig should enable/disable the feature for this tsconfig.json file.

**Comment by mhegazy** [comment]
see https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#compileonsave

**Comment by NoelAbrahams** [comment]
@mhegazy, the original problem was not to do with compile-on-save; it was to permit all compiler options to be set via the setting page. As it stands it doesn't make much sense.

Why not just have a free text box so that users can set what they like?

**Comment by paulvanbrenk** [comment]
@NoelAbrahams not sure what you mean with a free text box? But I am working on an easier to maintain properties page, so adding changes will be easier in the future.

**Comment by NoelAbrahams** [comment]
Just a text box to enter any compiler option that one may want, e.g. 
![image](https://cloud.githubusercontent.com/assets/1106823/13233345/35b36040-d9ab-11e5-9993-4307625637fb.png)

This just gets passed to the compiler.

I'm not sure if this is great UX, but at least it'll get the job done.

**Comment by mhegazy** [comment]
json files provide a similar experience, and most js devleopers are already familiar with its syntax. so my recommendation still stands.

**Comment by NoelAbrahams** [comment]
Well, yes, we'll probably migrate to using the json config at some point ourselves. My point had more do to with leaving behind a half complete settings page.
