### ISSUE TITLE
Merging TSJS lib.d.ts into TS1.8

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#6768]
Can you merge the latest lib.d.ts generated by Microsoft/TSJS-lib-generator into TS1.8?

**Comment by zhengbli** [comment]
A [PR](https://github.com/Microsoft/TypeScript/pull/6769) is sent to master, and will also be merged to the release-1.8 branch once it got in. Thanks for the notice!

**Comment by falsandtru** [comment]
Thanks!
