### ISSUE TITLE
Add a cmd line options to suppress warnings

### ISSUE THREAD

**Issue by paulvanbrenk** [Microsoft/TypeScript#6771]
Instead of adding a Boolean argument for each warning we want to suppress implement a more generic method to suppress, the warnings.

e.g instead of the `--noFallthroughCasesInSwitch` just suppress warning `7029`

**Comment by sandersn** [comment]
:+!:

**Comment by mhegazy** [comment]
why?

**Comment by sandersn** [comment]
`--warn x,y,z` pulls all the "even stricter" flags under a single flag. Otherwise we'll end up with a million optional strictness flags that will drown out the other flags in documentation.

**Comment by mhegazy** [comment]
looking at `--noFallthroughCasesInSwitch` tells you what it does., but `--suppressWarning 7029` is meaningless. 
The other issue here is diluting the value proposition. the main value of typescript is to catch type errors. the tooling quality depends on some of these errors being addressed by the user. if we muffle some of these errors, the whole experience would degrade. On the other hand, what we provide is a set of known knobs to switch off certain groups of errors, that we have deemed as safe to ignore.
I do not think there is anything wrong with being prescriptive here. For documentation, we could split the help into main, and extended to make sure we are not drowning common flags in the `--suppres*` ones
