### ISSUE TITLE
String literal types and type inference issues

### ISSUE THREAD

**Issue by guncha** [Microsoft/TypeScript#6772]
I'm lacking in the proper terminology to describe the issue, but see the example below:

```typescript
interface A {
  type: "A"
}

interface X {
  fn(): A
}

class C implements X {
  fn() {
    return { type: "A" }
  }
}
```

When trying to compile this file, an error is thrown:
```
$ tsc --version
Version 1.9.0-dev.20160131

$ tsc issue.ts
issue.ts(9,7): error TS2420: Class 'C' incorrectly implements interface 'X'.
  Types of property 'fn' are incompatible.
    Type '() => { type: string; }' is not assignable to type '() => A'.
      Type '{ type: string; }' is not assignable to type 'A'.
        Types of property 'type' are incompatible.
          Type 'string' is not assignable to type '"A"'.
```

If I explicitly say that `fn()` returns type `A`, it works fine.

**Comment by DanielRosenwasser** [comment]
This is mostly a symptom of #1373. For now the workaround is the explicit type annotation you mentioned.

**Comment by DanielRosenwasser** [comment]
Yup, I'm going to close this as a symptom of #1373. #6118 should fix this. @sandersn, can you add a test case based on the repro?

**Comment by sandersn** [comment]
OK, done. It was a good test -- exposed a bug in the code.

**Comment by guncha** [comment]
Thanks, guys, we appreciate all the good work you're doing!
