### ISSUE TITLE
Functions with same argument overloads should use union types not intersection types on the return type

### ISSUE THREAD

**Issue by andrew-w-ross** [Microsoft/TypeScript#6779]
## The Problem
It's lately becoming quite common to extend an existing frameworks in node, especially testing frameworks. For example look at [expect](https://github.com/mjackson/expect) and [expect-jsx](https://github.com/algolia/expect-jsx).

```javascript
//before including expect-jsx
expect(<div><TestComponent /></div>).toIncludeJSX(<TestComponent />); //Error toIncludeJSx is not a function

//after including expect-jsx
expect(<div><TestComponent /></div>).toIncludeJSX(<TestComponent />); //Works
```

This is pretty easy to write definitions for due to operator overloading,[here is an example of the code to extend](https://github.com/andrew-w-ross/typings-expect/blob/master/expect.d.ts#l197-#l201) and [here it is being extended](https://github.com/andrew-w-ross/typings-expect-jsx/blob/master/expect-jsx.d.ts#l18-l20).

The problem lies when operators collide on the arguments but have different return types. To demonstrate the problem I've created an example module `foo`.

```javascript
//foo.d.ts
declare module "foo"{
	interface IFactory{
		(...args:any[]) : IFoo;
	}
	
	interface IFoo{
		fooProp:string;
	}
	
	export function instantiator(factory : IFactory);	
}
```

In module `foo` the `IFactory` interface is defined as a function that will take any number of arguments and return an `IFoo`.

```javascript
import {instantiator, IFoo} from "foo";

function fooFactory():IFoo{
	return {
		fooProp : "foo"
	};
}

instantiator(fooFactory);
```

At this point I introduce module `bar` it extends instantiator function so it can take in a function that returns an `IBar`. The best way to go about this is to extend the definition of the `IFactory` to be a function that can also return an `IBar`.

```javascript
//bar.d.ts
declare module "foo"{	
	import {IBar} from "bar";
	
	interface IFactory{
		(...args:any[]) : IBar;
	}
}

declare module "bar"{
	interface IBar{
		barProp:string;
	}
}
```

This now breaks the the original code and doesn't reflect the intention of the author. 

```javascript
import {instantiator, IFoo} from "foo";

function fooFactory():IFoo{
	return {
		fooProp : "foo"
	};
}

instantiator(fooFactory); //Error : Argument of type '() => IFoo' is not assignable to parameter of type 'IFactory'. 
```

This is because the new definition for `IFactory` after merging is :
```javascript
interface IFactory{
	(...args:any[]) : IBar & IFoo;
}
```

## Current Workaround

The current workaround is to declare all functions using the original interface with an overload of a new interface. An example of bar : 
```javascript
/// <reference path="foo.d.ts" />

declare module "foo"{	
	import {IBar} from "bar";
	
	interface IBarFactory{		
		(...args:any[]) : IBar ;
	}
	
	export function instantiater(factory : IBarFactory);
}

declare module "bar"{
	interface IBar{
		barProp:string;
	}
}
```

This is painful but it works, but it'll become a much bigger issue when a third library is introduced that uses the definition of `IFactory`. Even worse is refactoring will pretty much be broken, if `instantiater` had it's spelling corrected to `instantiator` then only one set of function names would be picked up as a problem. 

## Preposed Change
 
It would be much better for the compiler to internally define the factory function using a union type:
```javascript
   interface IFactory{
         (...args:any[]) : IBar | IFoo;
   }
``` 
This won't break existing valid javascript code and hopefully will lead to less "fighting" with the compiler. If the intention of the author to have `IFactory` to be an intersection type of `IFoo` and `IBar` then they could have easily have done so.

```javascript
/bar.d.ts
declare module "foo"{	
	interface IFactory{
		(...args:any[]) : IBar & IFoo;
	}
}
```

The final representation would have been :
```javascript
   interface IFactory{
         (...args:any[]) : IFoo | IBar & IFoo;
   }
``` 

Again existing code will still be valid in this case.

**Comment by RyanCavanaugh** [comment]
This pattern is very confusing and I'm not sure the current definition makes any sense.

At its core, the problem is that someone said that a function returned a `foo`, then someone else came along and said it could also return a `bar`. So anyone that was previously relying on the function always returning a `foo` is, theoretically, broken by the change that the function might now return a `bar`.

It seems like what you actually have here is a function that should just return `any` (or `{}`) and it's up to the caller to specify what they know the return type would be (clearly, the caller *must* know the return type, since it's dependent on the arguments).

What do you think?

**Comment by andrew-w-ross** [comment]
@RyanCavanaugh It's more about defining the shape of what a valid function would look like. In the use case I have it's not the caller that does anything with the result it's something else and using a function `any` is a complete cop-out.  What I am challenging is the current logic or module merging with this specific situation could be done better. 

With that being said you do raise a good point about functions previously relying on the output breaking. If you think of it either way something that was or is valid can be made invalid. Perhaps my proposed solution isn't the best either but the current isn't all that great either.

**Comment by RyanCavanaugh** [comment]
I don't think we should change the signature merging semantics (which would be a big breaking change) to fit this oddball pattern.

**Comment by andrew-w-ross** [comment]
@RyanCavanaugh  Why would you call this pattern oddball?

**Comment by RyanCavanaugh** [comment]
a) In nearly 7,000 issues on GitHub, this is the first time it's been brought up b) it breaks basic principles of substitutability and c) I'm not aware of any libraries that do this in a way where you wouldn't be better off returning some bottom type (e.g. `{}`) or just using interface augmentation
