### ISSUE TITLE
New modifer to make member only visisble to a specific class and/or package

### ISSUE THREAD

**Issue by billccn** [Microsoft/TypeScript#6780]
(This is rather difficult to search for so apologies in advance for duplicates.)

TS lacks Java-like inner classes or package-scoped visibility which makes it cumbersome to encapsulate parent-children object relationship where the child needs to manipulate parent's internal datastructure. This is not only common in many complicated object graphs but also in OO designs where an object wants to issue a limited "handle"-like object that only implements a specific subset of features.

Currently the use cases above can only be implemented by exposing the internal datasturectures to the "child" or handing out loads of lambdas. This adds more tight coupling.

An good example is the API to remove of an `Element` in the DOM. Currently one have to call `parent.removeChild(child)` which is not only clumsy but also makes it difficult for the child to impose additional logic on the removal. Ideally, we'd want to have a `remove()` method on the child (like in jQuery) and make the `Node.removeChild()` method only visible to `Node` implementors.

Proposed solution:

Create a pseudo- or built-in decorator that accepts a list of types. Members decorated with this can only be accessed by types listed. Alternatively, can extend the `private` keyword to accept an argument list like `private (to A, B) name:type...`

**Comment by techird** [comment]
May be just a keyword `internal` just like c#. In typescript, `internal` can be simply assume as "in the same or child directory".

For example:

```
(root)
    /tablepanel
        /Body.ts
        /Header.ts
        /index.ts
    /button
        /Button.ts
```

If a class `Body` is defined in `Body.ts`:

```ts
internal class Body {

}
```

`Header.ts` and `index.ts` under the `tablepanel` directory can visit the `Body` class very well.

But in `Button.ts` under the `button` directory, the visit is forbidden and will raise an error.

Just a naive idea, need a disscussion here.

**Comment by RyanCavanaugh** [comment]
There are already plenty of options for encapsulation (namespaces, modules, class expressions, `private`, `protected`, explicit closures, symbols, weakmaps, etc...) and not enough compelling use cases where you'd absolutely *need* something more complex than what's already available.
