### ISSUE TITLE
Compile on Build / Compile on Save problems with TS 1.8 in Visual Studio 2015

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/TypeScript#6782]
Since I installed TS 1.8 I've started noticing that the compile step is not being executed in Visual Studio either on save or upon build when there are existing `*.js` files in place.

So if I'm working on `viewModel.ts` then I need to delete `viewModel.js` and trigger a Visual Studio build in order that a new `viewModel.js` is created.

My `tsconfig.json` looks like this:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "inlineSourceMap": true,
    "inlineSources": true,
    "noEmitOnError": true,
    "noImplicitAny": true,
    "preserveConstEnums": true,
    "removeComments": false,
    "sourceMap": false,
    "target": "es5"
  },
  "filesGlob": [
    "**/*.ts"
  ],
  "files": [
    // lots of files here - excluded for brevity
  ],
  "atom": {
    "rewriteTsconfig": true
  }
}
```

I wondered if it might be related to presence of the `compileOnSave` flag in `tsconfig.json` (which I believe is supported as of TS 1.8?).  However setting it to `true` and removing it entirely made no discernible differerence to behaviour.  (I tried closing and reopening the project in between changes in case there were caching issues but no change.)

So `compileOnSave` seems entirely broken (i.e. it never compiles on save) and compile on build only works if the existing js files are deleted.

**Comment by mhegazy** [comment]
the `compileOnSave` property support is not in a released version yet, @paulvanbrenk checked it in today :). it should be available for the 1.8.2.

Can you check your tools\options\Text Editor\TypeScript\Project\Compile on Save, do you have "Automatically compile TypeScript files that are not part of a project" checked? my guess is no, and that is why it is not working. with #2326, you should be able to turn it on using `compileOnSave` property in tsconfig.json.

**Comment by johnnyreilly** [comment]
Yup that solved it. Thanks @mhegazy.I'll look out for `compileOnSave` lighting up in when 1.8.2 ships.

**Comment by johnnyreilly** [comment]
@mhegazy - I'm guessing with the VS 2015 TypeScript 1.8 beta plugin I **shouldn't** expect `compileOnSave` to be working?

I've noticed that using Visual Studio that saving is generating the js files still (even though the flag is set in `tsconfig.json`)

**Comment by paulvanbrenk** [comment]
@johnnyreilly Indeed, the `compileOnSave` option needs new Visual Studio bits.

**Comment by johnnyreilly** [comment]
Thanks @paulvanbrenk.

**Comment by mythz** [comment]
Is `tsconfig.json` and `compileOnSave` expected to work on VS 2013? I've installed the latest v1.8.2 of TypeScript for VS2013 and it's missing the "TypeScript JSON Configuration File" new item template for tsconfig.json, adding it manually doesn't disable the TypeScript property page on project properties and none of the configuration on `tsconfig.json` seems to be overriding either?

**Comment by mhegazy** [comment]
@mythz, tsconfig.json is not supported for Visual Studio 2013. only Visual Studio 2015.

**Comment by codler** [comment]
Seems `compileOnSave` are not executing same path as VS project root, because `out` is generating on different path when i do build respective save

**Comment by mhegazy** [comment]
@codler can you share your project?

**Comment by paulvanbrenk** [comment]
@codler which version of TypeScript? We've fixed issues in that area.

**Comment by hcapp01** [comment]
@paulvanbrenk I can repro colder's issue on 1.8.4.0.

**Comment by mhegazy** [comment]
@hcapp01 can you share a repro project.

**Comment by hcapp01** [comment]
@mhegazy 
I created a minimum repro below. main.js is output to two different path.
https://github.com/hcapp01/tsrepro

**Comment by paulvanbrenk** [comment]
@hcapp01 change `out` to `outFile` in your `tsconfig.json` file

**Comment by hcapp01** [comment]
@paulvanbrenk that works. thanks.

**Comment by NoelAbrahams** [comment]
@mhegazy, do you know what the status of this is?

I'm having trouble getting `compile-on-save` working. This is the setup I have:

**TS Version**: 1.8.9 (says 1.8.31.0 on the Visual Studio `Help -> About page`)
**VS Version**: VS 2015 Update 2
**tsconfig**:

```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "noImplicitAny": true,
    "sourceMap": true,
    "noEmitOnError": true
  },
  "compileOnSave": true
}
```
 
When I build the whole project via `right-click -> Build`, all the files are compiled correctly.

When I save a specific `.ts` file, the status bar says "Generation of 'myproject/foo.ts' complete. Remaining files still compiling." This just hangs, and the `.js` output never gets generated.

Things were working fine before I introduced `.tsconfig`.

I tried some of the suggested workarounds including turning off `noEmitOnError` and setting `Automatically compile files that are not part of the project...`, but nothing seems to work.

**Comment by mhegazy** [comment]
> When I save a specific .ts file, the status bar says "Generation of 'myproject/foo.ts' complete. Remaining files still compiling." This just hangs, and the .js output never gets generated.

The message is somewthing i would expect. it just says it generated `foo.ts` and working on generating the rest in the background. but it should not hang.

how do you build from the commandline? `tsc --p` ? or you use a build driver? what happens when you run `tsc --p <path to tsconfig.json> --listFiles` do you see files that should not be there?

**Comment by NoelAbrahams** [comment]
@mhegazy, I'm just using Visual Studio. The message "generated foo.js" is also wrong because the file is unchanged.

Sent from my iPhone

On 9 May 2016, at 00:12, Mohamed Hegazy <notifications@github.com<mailto:notifications@github.com>> wrote:


When I save a specific .ts file, the status bar says "Generation of 'myproject/foo.ts' complete. Remaining files still compiling." This just hangs, and the .js output never gets generated.

The message is somewthing i would expect. it just says it generated foo.ts and working on generating the rest in the background. but it should not hang.

how do you build from the commandline? tsc --p ? or you use a build driver? what happens when you run tsc --p <path to tsconfig.json> --listFiles do you see files that should not be there?

-

**Comment by mhegazy** [comment]
Given the language semantics, generating one file might not be sufficient to get correct output, e.g. Const. enums changes, namespaces, etc.. In VS when saving a file, the file will be generated, then all other files in the project will be generated in the background one at a time. This should end at sometime though :) so what u are seeing seems like a bug.

**Comment by cmichaelgraham** [comment]
i was seeing something similar.  i ***believe*** that unloading the project and reloading it seems to have fixed the compile on save that i added to tsconfig.json.  maybe it doesn't take effect until the project is reloaded?

**Comment by cmichaelgraham** [comment]
& hello again @mhegazy :smile:

**Comment by mhegazy** [comment]
> it seems to have fixed the compile on save that i added to tsconfig.json.

This looks like a bug to me. @paulvanbrenk thoughts?

**Comment by mhegazy** [comment]
@cmichaelgraham do you mind filing another issue for this?

**Comment by mhegazy** [comment]
and hello @cmichaelgraham, good to see!

**Comment by paulvanbrenk** [comment]
Not sure, are the other settings in the `tsconfig.json` picked up?

**Comment by Methodician** [comment]
Here's what I don't get: it sometimes works fine and others it doesn't!

I can't for the life of me figure out what I'm doing right or wrong when, or if I even have any influence on this at all. It's almost more frustrating to have it work "sometimes" than to just never work.

**My workaround sucks**. Today, it simply doesn't work so I am back to the habit of hitting "Rebuild" every time I make the tiniest change. Please tell me you've found a better temporary workflow/workaround until this is fixed!!!

But yesterday it was all unicorns and rainbows. Everything was flowing beautifully in the same solution, same IDE, same computer. No idea what changed. If it works sometimes, maybe there's a tweak to get it to work always?

**Comment by Methodician** [comment]
**# Please share your workarounds**

I guess this problem has been around for a while now and like me, if you're still pushing through you must have come up with a pattern, habit, workflow, or workaround that is getting you through each day until this is fixed. Mine is to "rebuild" the whole solution every time I make the tiniest change to any .ts file. Surely someone has come up with a better way. Please do tell!

**Comment by paulvanbrenk** [comment]
We found an issue with compile on save and `tsconfig.json` files, that depended on the order we processed files, which is not always the same. This fix is part of VS 2015 Update 3 [0].

[0] I can't tell you when that will be released, but the RC release has other TypeScript issues, so don't install that.

**Comment by Methodician** [comment]
I installed the Update 3 RC and it has helped with a lot of other problems. Most vitally, _it made the .tfignore file work_, which I absolutely need when committing lots of small typescript files to source control and wanting to ignore the transpiled .js and .map.js files.

**Comment by gleno** [comment]
I have very similar issues. Everything compiles correctly, but it takes a very long time, and sometimes randomly flakes out. Wasn't like this with the previous version of TSC.

**Comment by mhegazy** [comment]
@gleno this is an old issue. do you mind filing a new issue, sharing more details about what you are seeing, what version of VS you are using what version of TS, and a project to help investigate the issue.

**Comment by mikelunn** [comment]
I'm using VS 2015 Update 3 and are experiencing a very similar issue. The typescript compiler seems to only work when I do a build. However, if I do a build, and no server side code has changed, the typescript code will not compile.

**Comment by gleno** [comment]
I've recovered my problem by installing an older version of node tools. If
you have just updated, this may be your issue.

**Comment by paulvanbrenk** [comment]
@mikelunn As Mohamed mentioned this is a very old issue, can you file a new issue with a sample project. And `diagnostic` build logs. Thanks

**Comment by dudih** [comment]
I had the same problem in my visual studio update 3.
It's seems that widows didn't get my typescript 1.8 version, but hold the 1.0 version. so I changed it manually. Now it's work. on saving a .ts file, all my project being transpiled correctly.

For more info:  [vs2015-adding-watch-true-to-tsconfig-json-causing-jserrorscriptexception-0x/39022452#39022452](http://stackoverflow.com/questions/39021808/vs2015-adding-watch-true-to-tsconfig-json-causing-jserrorscriptexception-0x/39022452#39022452)

**Comment by ybarbaria** [comment]
In typescript 2, you need to delete "outDir" in your tsconfig. Works for me.
