### ISSUE TITLE
Spec allows missing initializer in destructuring lexical bindings

### ISSUE THREAD

**Issue by nickie** [microsoft/TypeScript#6785]
[TypeScript's specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#53-let-and-const-declarations) seems to allow a missing initializer for destructuring lexical bindings, whereas the [EC262 specification](http://tc39.github.io/ecma262/#sec-let-and-const-declarations) does not.  Is this intentional?  In that case, I believe it should only be allowed in the case that a type annotation is present, e.g., in `let [x, y]: number[];`  The current playground implementation seems to disallow this.

**Comment by RyanCavanaugh** [comment]
The initializer for *DestructuringLexicalBinding* should not be *opt*

**Comment by RyanCavanaugh** [comment]
The spec is now an "archived" artifact and we won't be tracking defects against it anymore.
