### ISSUE TITLE
Property getters can self reference, setting up an infinite loop.

### ISSUE THREAD

**Issue by thesandbender** [Microsoft/TypeScript#6788]
Feature request.  TSC 1.7.5 allows you to create a property that returns a reference to the getter:

```
class Foobar {
	private _cyclic:string = 'test';

	public get cyclic():string {
		return this.cyclic;  // should be return this._cyclic;
	}

	constructor() {}
}

var f:Foobar = new Foobar();

console.log(f.cyclic);
```

It would be nice is TSC warned on questionable code like this.

**Comment by RyanCavanaugh** [comment]
It's possible it's not wrong (e.g. you have a `return` earlier in the codepath and intend to be recursive).
