### ISSUE TITLE
Significally reduce the need for this keyword in classes

### ISSUE THREAD

**Issue by riax** [microsoft/TypeScript#679]
The need to prefix all calls to methods and variables in the class body with the **this** keyword makes the code harder to read and look cluttered. 

Instead the TypeScript compiler could add the **this** keyword automatically during the compilation to JavaScript. This would make code that looks like this…

``` javascript
var something = this.doSomething(this.getSomething());
this.addSomething(something);
```

look like..

``` javascript
var something = doSomething(getSomething());
addSomething(something);
```

If I’m not mistaken it should be easy to determine if the **this** keyword should be prefixed or not. I know that TypeScript tries to resemble the ES6 syntax. But to me code clarity feels more important.

**Comment by panuganti** [comment]
As riax commented, ambiguous reference can be compilation error. You guys might want to look at some options. Having way too many 'this' in code makes code look ugly....
