### ISSUE TITLE
TS config ui for ASP.NET 5

### ISSUE THREAD

**Issue by sayedihashimi** [Microsoft/TypeScript#6793]
Originally filed by @mbeckenbach at https://github.com/aspnet/Tooling/issues/364

The typescript section in project properties should reflect what you can do with tsconfig.json

**Comment by paulvanbrenk** [comment]
An obvious challenge is what happens with multiple `tsconfig.json` files in the project.

**Comment by mhegazy** [comment]
tsconfig.json files are now supported as the main source of configuration for any project type. multiple tsconfig.json files are allowed now. Most JavaScript developers are familiar with JSON, and are comfortable editing it. this is also less work for us. so moving forward, tsconfig.json is the recommended way of managing ts configuration.
