### ISSUE TITLE
External Runtime Helpers

### ISSUE THREAD

**Issue by knpwrs** [Microsoft/TypeScript#6796]
I've done some Googling and some searching around this issue tracker and couldn't find anything, so please excuse me if this has been discussed prior.

I was wondering if there were any plans to possibly introduce the ability to externalize helper functions non-globally. For example, how [`babel-plugin-transform-runtime`](https://www.npmjs.com/package/babel-plugin-transform-runtime) does it. They import helpers from the `babel-runtime` package. In Typescript there is the `--noEmitHelpers` option but as far as I'm aware that requires putting the helpers in the global scope e.g., with the [`typescript-helpers`](https://github.com/tifosiblack/typescript-helpers) package.

**Comment by mhegazy** [comment]
yes. should be tracked by https://github.com/Microsoft/TypeScript/issues/3364
