### ISSUE TITLE
JS files in our test suite always get a file overwrite error

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript#6799]
See [here](https://github.com/Microsoft/TypeScript/blob/67a77b608fd34206a0098fb515569da8ca186909/tests/baselines/reference/exportDefaultInJsFile01.errors.txt#L1) with relevant discussion on #6797.

**Comment by vladima** [comment]
you can use `suppressOutputPathCheck` option do disable this check

**Comment by mhegazy** [comment]
:) that was quick

**Comment by RyanCavanaugh** [comment]
@vladima how do I use this option in a compiler baseline?

**Comment by RyanCavanaugh** [comment]
Implemented in #7007
